Cataclysm DDA: src/achievement.h File Reference
achievement.h File Reference
#include <array>
#include <functional>
#include <iosfwd>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "calendar.h"
#include "cata_variant.h"
#include "event_subscriber.h"
#include "translation.h"
#include "type_id.h"
Classes
struct enum_traits< achievement_comparison >
struct enum_traits< achievement_completion >
class achievement
class achievement::time_bound
struct enum_traits< achievement::time_bound::epoch >
struct achievement_state
class achievement_tracker
class achievements_tracker
Namespaces
cata
Macros
#define CATA_SRC_ACHIEVEMENT_H
Enumerations
enum class achievement_comparison : int {
equal , less_equal , greater_equal , anything ,
last
}
enum class achievement_completion : int { pending , completed , failed , last }
Functions
achievements_tracker & get_achievements ()
Macro Definition Documentation
CATA_SRC_ACHIEVEMENT_H
#define CATA_SRC_ACHIEVEMENT_H
Definition at line 3 of file achievement.h.
Enumeration Type Documentation
achievement_comparison
enum achievement_comparison : int strong
Enumerator
equal
less_equal
greater_equal
anything
last
Definition at line 36 of file achievement.h.
                                   : int {
     equal,
     less_equal,
     greater_equal,
     anything,
     last,
 };
achievement_completion
enum achievement_completion : int strong
Enumerator
pending
completed
failed
last
Definition at line 49 of file achievement.h.
                                   : int {
     pending,
     completed,
     failed,
     last
 };
Function Documentation
get_achievements()
achievements_tracker& get_achievements ()
Definition at line 13802 of file game.cpp.
 {
     return g->achievements();
 }
Referenced by achievement_attained(), debug_menu::debug(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_achievment(), debug_menu::unlock_all(), and memorial_logger::write_json_memorial().