Cataclysm DDA: src/achievement.cpp File Reference
achievement.cpp File Reference
#include "achievement.h"
#include <cstdlib>
#include <set>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "cata_assert.h"
#include "color.h"
#include "debug.h"
#include "enum_conversions.h"
#include "enums.h"
#include "event.h"
#include "event_statistics.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "generic_factory.h"
#include "init.h"
#include "json.h"
#include "json_error.h"
#include "past_achievements_info.h"
#include "stats_tracker.h"
#include "string_formatter.h"
#include "translations.h"
Classes
struct enum_traits< requirement_visibility >
struct achievement_requirement
class requirement_watcher
Namespaces
anonymous_namespace{achievement.cpp}
io
Enumerations
enum class requirement_visibility : int {
always , when_requirement_completed , when_achievement_completed , never ,
last
}
Functions
template<>
std::string io::enum_to_string< achievement_comparison > (achievement_comparison data)
template<>
std::string io::enum_to_string< achievement::time_bound::epoch > (achievement::time_bound::epoch data)
template<>
std::string io::enum_to_string< requirement_visibility > (requirement_visibility data)
static nc_color color_from_completion (bool is_conduct, achievement_completion comp, bool is_title)
static time_point epoch_to_time_point (achievement::time_bound::epoch e)
static std::optional< std::string > text_for_requirement (const achievement_requirement &req, const cata_variant &current_value, achievement_completion ach_completed)
static std::string format_requirements (const std::vector< std::optional< std::string >> &req_texts, nc_color c)
template<>
std::string io::enum_to_string< achievement_completion > (achievement_completion data)
Variables
static const achievement_id achievement_achievement_arcade_mode ("achievement_arcade_mode")
generic_factory< achievement > anonymous_namespace{achievement.cpp}::achievement_factory ("achievement")
Enumeration Type Documentation
requirement_visibility
enum requirement_visibility : int strong
Enumerator
always
when_requirement_completed
when_achievement_completed
never
last
Definition at line 83 of file achievement.cpp.
                                   : int {
     always,
     when_requirement_completed,
     when_achievement_completed,
     never,
     last
 };
Function Documentation
color_from_completion()
static nc_color color_from_completion (bool is_conduct, achievement_completion comp, bool is_title) static
Definition at line 147 of file achievement.cpp.
 {
     switch( comp ) {
         case achievement_completion::pending:
             return is_conduct ? c_light_green : ( is_title ? c_white : c_light_cyan );
         case achievement_completion::completed:
             return c_light_green;
         case achievement_completion::failed:
             return c_red;
         case achievement_completion::last:
             break;
     }
     cata_fatal( "Invalid achievement_completion" );
 }
References c_light_cyan, c_light_green, c_red, c_white, cata_fatal, completed, failed, last, and pending.
Referenced by achievement_tracker::ui_text(), achievement::time_bound::ui_text(), and achievement_state::ui_text().
epoch_to_time_point()
static time_point epoch_to_time_point (achievement::time_bound::epoch e) static
Definition at line 264 of file achievement.cpp.
 {
     switch( e ) {
         case achievement::time_bound::epoch::cataclysm:
             return calendar::start_of_cataclysm;
         case achievement::time_bound::epoch::game_start:
             return calendar::start_of_game;
         case achievement::time_bound::epoch::last:
             break;
     }
     cata_fatal( "Invalid epoch" );
 }
References cata_fatal, achievement::time_bound::cataclysm, achievement::time_bound::game_start, achievement::time_bound::last, calendar::start_of_cataclysm, and calendar::start_of_game.
Referenced by achievement::time_bound::target().
format_requirements()
static std::string format_requirements (const std::vector< std::optional< std::string >> & req_texts, nc_color c) static
Definition at line 515 of file achievement.cpp.
 {
     bool some_missing = false;
     std::string result;
     for( const std::optional<std::string> &req_text : req_texts ) {
         if( req_text ) {
             result += "  " + *req_text + "\n";
         } else {
             some_missing = true;
         }
     }
     if( some_missing && !result.empty() ) {
         result += colorize( _( "  (further requirements hidden)" ), c );
     }
     return result;
 }
References _, c, and colorize().
Referenced by achievement_tracker::ui_text(), and achievement_state::ui_text().
text_for_requirement()
static std::optional<std::string> text_for_requirement (const achievement_requirement & req, const cata_variant & current_value, achievement_completion ach_completed) static
Definition at line 486 of file achievement.cpp.
 {
     bool is_satisfied = req.satisfied_by( current_value );
     if( !req.is_visible( ach_completed, is_satisfied ) ) {
         return std::nullopt;
     }
     nc_color c = is_satisfied ? c_green : c_yellow;
     std::string result;
     if( req.description ) {
         result = req.description->translated();
     } else if( req.comparison == achievement_comparison::anything ) {
         result = string_format( _( "Triggered by %s" ), req.statistic->description().translated() );
     } else if( current_value.type() == cata_variant_type::int_ ) {
         int current = current_value.get<int>();
         int target = req.target.get<int>();
         result = string_format( _( "%s/%s %s" ), current, target,
                                 req.statistic->description().translated( target ) );
     } else {
         // The tricky part here is formatting an arbitrary cata_variant value.
         // It might be possible, but for now we punt the problem to content
         // developers.
         result = "ERROR: Non-integer requirements must provide a custom description";
     }
     return colorize( result, c );
 }
References _, anything, c, c_green, c_yellow, colorize(), achievement_requirement::comparison, achievement_requirement::description, event_statistic::description(), cata_variant::get(), int_, achievement_requirement::is_visible(), achievement_requirement::satisfied_by(), achievement_requirement::statistic, string_format(), achievement_requirement::target, translation::translated(), and cata_variant::type().
Referenced by requirement_watcher::ui_text(), and achievement_state::ui_text().
Variable Documentation
achievement_achievement_arcade_mode
const achievement_id achievement_achievement_arcade_mode("achievement_arcade_mode") ("achievement_arcade_mode") static
Referenced by achievements_tracker::is_hidden().