Cataclysm DDA: src/activity_actor.cpp File Reference
activity_actor.cpp File Reference
#include "activity_actor.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <initializer_list>
#include <iterator>
#include <list>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <string_view>
#include <type_traits>
#include <unordered_set>
#include <utility>
#include <vector>
#include "action.h"
#include "activity_actor_definitions.h"
#include "activity_handlers.h"
#include "advanced_inv.h"
#include "avatar.h"
#include "avatar_action.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "character.h"
#include "character_id.h"
#include "clzones.h"
#include "contents_change_handler.h"
#include "coordinates.h"
#include "craft_command.h"
#include "creature.h"
#include "creature_tracker.h"
#include "debug.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "faction.h"
#include "field_type.h"
#include "flag.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "gates.h"
#include "gun_mode.h"
#include "handle_liquid.h"
#include "harvest.h"
#include "iexamine.h"
#include "inventory.h"
#include "item.h"
#include "item_components.h"
#include "item_contents.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "json.h"
#include "json_error.h"
#include "line.h"
#include "magic_enchantment.h"
#include "map.h"
#include "map_iterator.h"
#include "map_selector.h"
#include "mapdata.h"
#include "martialarts.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "pickup.h"
#include "pimpl.h"
#include "player_activity.h"
#include "pocket_type.h"
#include "point.h"
#include "ranged.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "shearing.h"
#include "skill.h"
#include "sounds.h"
#include "string_formatter.h"
#include "translation.h"
#include "translations.h"
#include "trap.h"
#include "try_parse_integer.h"
#include "ui.h"
#include "uistate.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "vpart_range.h"
Namespaces
activity_actors
Enumerations
enum class hack_result : int { UNABLE , FAIL , NOTHING , SUCCESS }
enum class hack_type : int { SAFE , DOOR , GAS , NONE }
Functions
static int hack_level (const Character &who, item_location &tool)
static hack_result hack_attempt (Character &who, item_location &tool)
static hack_type get_hack_type (const tripoint &examp)
static int get_quality_from_string (const std::string_view s)
static void print_data_handling_tally (Character &who, int encrypted_cards, int photos, int songs, const std::vector< recipe_id > &recipes, int extended_photos, int monster_photos)
static std::string enumerate_ints_to_string (const std::vector< int > &vec)
static bool is_valid_book (const item_location &book)
static bool cancel_if_book_invalid (player_activity &act, const item_location &book, const Character &who)
static void cancel_pickup (Character &who)
static void debug_drop_list (const std::vector< drop_or_stash_item_info > &items)
static bool is_bulk_unload (const item_location &lhs, const item_location &rhs)
static std::list< item > obtain_activity_items (std::vector< drop_or_stash_item_info > &items, contents_change_handler &handler, Character &who, bool &bulk_unload)
static void stash_on_pet (const std::list< item > &items, monster &pet, Character &who)
static int item_move_cost (Character &who, item_location &item, bool bulk_cost)
static bool is_bulk_load (const item_location &lhs, const item_location &rhs)
static ret_val< void > try_insert (item_location &holster, drop_location &holstered_item, int *charges_added, Character *carrier)
static bool check_if_disassemble_okay (item_location target, Character &who)
static bool check_stealing (Character &who, item &it)
static void chop_single_do_turn (player_activity &act)
static void move_item (Character &you, item &it, const int quantity, const tripoint_bub_ms &src, const tripoint_bub_ms &dest, vehicle *src_veh, int src_part)
void serialize (const cata::clone_ptr< activity_actor > &actor, JsonOut &jsout)
void deserialize (cata::clone_ptr< activity_actor > &actor, const JsonValue &jsin)
Variables
static const activity_id ACT_AIM ("ACT_AIM")
static const activity_id ACT_AUTODRIVE ("ACT_AUTODRIVE")
static const activity_id ACT_BIKERACK_RACKING ("ACT_BIKERACK_RACKING")
static const activity_id ACT_BIKERACK_UNRACKING ("ACT_BIKERACK_UNRACKING")
static const activity_id ACT_BINDER_COPY_RECIPE ("ACT_BINDER_COPY_RECIPE")
static const activity_id ACT_BOLTCUTTING ("ACT_BOLTCUTTING")
static const activity_id ACT_CHOP_LOGS ("ACT_CHOP_LOGS")
static const activity_id ACT_CHOP_PLANKS ("ACT_CHOP_PLANKS")
static const activity_id ACT_CHOP_TREE ("ACT_CHOP_TREE")
static const activity_id ACT_CHURN ("ACT_CHURN")
static const activity_id ACT_CLEAR_RUBBLE ("ACT_CLEAR_RUBBLE")
static const activity_id ACT_CONSUME ("ACT_CONSUME")
static const activity_id ACT_CONSUME_MEDS_MENU ("ACT_CONSUME_MEDS_MENU")
static const activity_id ACT_CRACKING ("ACT_CRACKING")
static const activity_id ACT_CRAFT ("ACT_CRAFT")
static const activity_id ACT_DATA_HANDLING ("ACT_DATA_HANDLING")
static const activity_id ACT_DISABLE ("ACT_DISABLE")
static const activity_id ACT_DISASSEMBLE ("ACT_DISASSEMBLE")
static const activity_id ACT_DROP ("ACT_DROP")
static const activity_id ACT_EAT_MENU ("ACT_EAT_MENU")
static const activity_id ACT_EBOOKSAVE ("ACT_EBOOKSAVE")
static const activity_id ACT_FIRSTAID ("ACT_FIRSTAID")
static const activity_id ACT_FORAGE ("ACT_FORAGE")
static const activity_id ACT_FURNITURE_MOVE ("ACT_FURNITURE_MOVE")
static const activity_id ACT_GLIDE ("ACT_GLIDE")
static const activity_id ACT_GUNMOD_ADD ("ACT_GUNMOD_ADD")
static const activity_id ACT_GUNMOD_REMOVE ("ACT_GUNMOD_REMOVE")
static const activity_id ACT_HACKING ("ACT_HACKING")
static const activity_id ACT_HACKSAW ("ACT_HACKSAW")
static const activity_id ACT_HAIRCUT ("ACT_HAIRCUT")
static const activity_id ACT_HARVEST ("ACT_HARVEST")
static const activity_id ACT_HOTWIRE_CAR ("ACT_HOTWIRE_CAR")
static const activity_id ACT_INSERT_ITEM ("ACT_INSERT_ITEM")
static const activity_id ACT_INVOKE_ITEM ("ACT_INVOKE_ITEM")
static const activity_id ACT_LOCKPICK ("ACT_LOCKPICK")
static const activity_id ACT_LONGSALVAGE ("ACT_LONGSALVAGE")
static const activity_id ACT_MEDITATE ("ACT_MEDITATE")
static const activity_id ACT_MIGRATION_CANCEL ("ACT_MIGRATION_CANCEL")
static const activity_id ACT_MILK ("ACT_MILK")
static const activity_id ACT_MOP ("ACT_MOP")
static const activity_id ACT_MOVE_ITEMS ("ACT_MOVE_ITEMS")
static const activity_id ACT_MULTIPLE_CHOP_TREES ("ACT_MULTIPLE_CHOP_TREES")
static const activity_id ACT_OPEN_GATE ("ACT_OPEN_GATE")
static const activity_id ACT_OXYTORCH ("ACT_OXYTORCH")
static const activity_id ACT_PICKUP ("ACT_PICKUP")
static const activity_id ACT_PICKUP_MENU ("ACT_PICKUP_MENU")
static const activity_id ACT_PLAY_WITH_PET ("ACT_PLAY_WITH_PET")
static const activity_id ACT_PRYING ("ACT_PRYING")
static const activity_id ACT_READ ("ACT_READ")
static const activity_id ACT_REEL_CABLE ("ACT_REEL_CABLE")
static const activity_id ACT_RELOAD ("ACT_RELOAD")
static const activity_id ACT_SHAVE ("ACT_SHAVE")
static const activity_id ACT_SHEARING ("ACT_SHEARING")
static const activity_id ACT_STASH ("ACT_STASH")
static const activity_id ACT_TENT_DECONSTRUCT ("ACT_TENT_DECONSTRUCT")
static const activity_id ACT_TENT_PLACE ("ACT_TENT_PLACE")
static const activity_id ACT_TRY_SLEEP ("ACT_TRY_SLEEP")
static const activity_id ACT_UNLOAD ("ACT_UNLOAD")
static const activity_id ACT_UNLOAD_LOOT ("ACT_UNLOAD_LOOT")
static const activity_id ACT_VEHICLE_FOLD ("ACT_VEHICLE_FOLD")
static const activity_id ACT_VEHICLE_UNFOLD ("ACT_VEHICLE_UNFOLD")
static const activity_id ACT_WASH ("ACT_WASH")
static const activity_id ACT_WEAR ("ACT_WEAR")
static const activity_id ACT_WIELD ("ACT_WIELD")
static const activity_id ACT_WORKOUT_ACTIVE ("ACT_WORKOUT_ACTIVE")
static const activity_id ACT_WORKOUT_HARD ("ACT_WORKOUT_HARD")
static const activity_id ACT_WORKOUT_LIGHT ("ACT_WORKOUT_LIGHT")
static const activity_id ACT_WORKOUT_MODERATE ("ACT_WORKOUT_MODERATE")
static const ammotype ammo_plutonium ("plutonium")
static const efftype_id effect_docile ("docile")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_gliding ("gliding")
static const efftype_id effect_paid ("paid")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_sensor_stun ("sensor_stun")
static const efftype_id effect_sheared ("sheared")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_tied ("tied")
static const efftype_id effect_took_thorazine ("took_thorazine")
static const efftype_id effect_worked_on ("worked_on")
static const faction_id faction_your_followers ("your_followers")
static const flag_id json_flag_ALWAYS_AIMED ("ALWAYS_AIMED")
static const flag_id json_flag_NO_RELOAD ("NO_RELOAD")
static const furn_str_id furn_f_gunsafe_mj ("f_gunsafe_mj")
static const furn_str_id furn_f_gunsafe_ml ("f_gunsafe_ml")
static const furn_str_id furn_f_safe_c ("f_safe_c")
static const furn_str_id furn_f_safe_o ("f_safe_o")
static const gun_mode_id gun_mode_DEFAULT ("DEFAULT")
static const item_group_id Item_spawn_data_forage_autumn ("forage_autumn")
static const item_group_id Item_spawn_data_forage_spring ("forage_spring")
static const item_group_id Item_spawn_data_forage_summer ("forage_summer")
static const item_group_id Item_spawn_data_forage_winter ("forage_winter")
static const item_group_id Item_spawn_data_trash_forest ("trash_forest")
static const itype_id itype_2x4 ("2x4")
static const itype_id itype_detergent ("detergent")
static const itype_id itype_disassembly ("disassembly")
static const itype_id itype_liquid_soap ("liquid_soap")
static const itype_id itype_log ("log")
static const itype_id itype_paper ("paper")
static const itype_id itype_pseudo_bio_picklock ("pseudo_bio_picklock")
static const itype_id itype_soap ("soap")
static const itype_id itype_splinter ("splinter")
static const itype_id itype_stick_long ("stick_long")
static const itype_id itype_water ("water")
static const itype_id itype_water_clean ("water_clean")
static const json_character_flag json_flag_SAFECRACK_NO_TOOL ("SAFECRACK_NO_TOOL")
static const move_mode_id move_mode_prone ("prone")
static const move_mode_id move_mode_walk ("walk")
static const mtype_id mon_manhack ("mon_manhack")
static const proficiency_id proficiency_prof_lockpicking ("prof_lockpicking")
static const proficiency_id proficiency_prof_lockpicking_expert ("prof_lockpicking_expert")
static const proficiency_id proficiency_prof_safecracking ("prof_safecracking")
static const quality_id qual_HACK ("HACK")
static const quality_id qual_LOCKPICK ("LOCKPICK")
static const quality_id qual_PRY ("PRY")
static const quality_id qual_PRYING_NAIL ("PRYING_NAIL")
static const quality_id qual_SAW_M ("SAW_M")
static const quality_id qual_SHEAR ("SHEAR")
static const skill_id skill_computer ("computer")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_fabrication ("fabrication")
static const skill_id skill_mechanics ("mechanics")
static const skill_id skill_survival ("survival")
static const skill_id skill_traps ("traps")
static const species_id species_ZOMBIE ("ZOMBIE")
static const ter_str_id ter_t_card_reader_broken ("t_card_reader_broken")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_dirtmound ("t_dirtmound")
static const ter_str_id ter_t_door_c ("t_door_c")
static const ter_str_id ter_t_door_locked_alarm ("t_door_locked_alarm")
static const ter_str_id ter_t_door_metal_c ("t_door_metal_c")
static const ter_str_id ter_t_door_metal_locked ("t_door_metal_locked")
static const ter_str_id ter_t_stump ("t_stump")
static const ter_str_id ter_t_trunk ("t_trunk")
static const ter_str_id ter_t_underbrush_harvested_autumn ("t_underbrush_harvested_autumn")
static const ter_str_id ter_t_underbrush_harvested_spring ("t_underbrush_harvested_spring")
static const ter_str_id ter_t_underbrush_harvested_summer ("t_underbrush_harvested_summer")
static const ter_str_id ter_t_underbrush_harvested_winter ("t_underbrush_harvested_winter")
static const trait_id trait_SCHIZOPHRENIC ("SCHIZOPHRENIC")
static const vproto_id vehicle_prototype_none ("none")
static const zone_type_id zone_type_LOOT_IGNORE ("LOOT_IGNORE")
static const zone_type_id zone_type_LOOT_IGNORE_FAVORITES ("LOOT_IGNORE_FAVORITES")
static const zone_type_id zone_type_STRIP_CORPSES ("STRIP_CORPSES")
static const zone_type_id zone_type_UNLOAD_ALL ("UNLOAD_ALL")
const std::unordered_map< activity_id, std::unique_ptr< activity_actor > JsonValue activity_actors::deserialize_functions
Enumeration Type Documentation
hack_result
enum hack_result : int strong
Enumerator
UNABLE
FAIL
NOTHING
SUCCESS
Definition at line 736 of file activity_actor.cpp.
                        : int {
     UNABLE,
     FAIL,
     NOTHING,
     SUCCESS
 };
hack_type
enum hack_type : int strong
Enumerator
SAFE
DOOR
GAS
NONE
Definition at line 743 of file activity_actor.cpp.
                      : int {
     SAFE,
     DOOR,
     GAS,
     NONE
 };
Function Documentation
cancel_if_book_invalid()
static bool cancel_if_book_invalid (player_activity & act, const item_location & book, const Character & who) static
Definition at line 1778 of file activity_actor.cpp.
 {
     if( !is_valid_book( book ) ) {
         who.add_msg_player_or_npc(
             _( "You no longer have the book!" ),
             _( "<npcname> no longer has the book!" ) );
         act.set_to_null();
         return true;
     }
     return false;
 }
References _, act, Character::add_msg_player_or_npc(), and is_valid_book().
Referenced by read_activity_actor::do_turn(), read_activity_actor::finish(), and read_activity_actor::start().
cancel_pickup()
static void cancel_pickup (Character & who) static
Definition at line 2437 of file activity_actor.cpp.
 {
     who.cancel_activity();
     if( who.is_hauling() && !get_map().has_haulable_items( who.pos() ) ) {
         who.stop_hauling();
     }
     who.drop_invalid_inventory();
 }
References Character::cancel_activity(), Character::drop_invalid_inventory(), get_map(), Character::is_hauling(), Creature::pos(), and Character::stop_hauling().
Referenced by pickup_activity_actor::do_turn().
check_if_disassemble_okay()
static bool check_if_disassemble_okay (item_location target, Character & who) static
Definition at line 5148 of file activity_actor.cpp.
 {
     item *disassembly = target.get_item();
     // item_location::get_item() will return nullptr if the item is lost
     if( !disassembly ) {
         who.add_msg_player_or_npc(
             _( "You no longer have the in progress disassembly in your possession.  "
                "You stop disassembling.  "
                "Reactivate the in progress disassembly to continue disassembling." ),
             _( "<npcname> no longer has the in progress disassembly in their possession.  "
                "<npcname> stops disassembling." ) );
         return false;
     }
     return true;
 }
References _, Character::add_msg_player_or_npc(), and item_location::get_item().
Referenced by disassemble_activity_actor::do_turn(), and disassemble_activity_actor::start().
check_stealing()
static bool check_stealing (Character & who, item & it) static
Definition at line 6004 of file activity_actor.cpp.
 {
     if( !it.is_owned_by( who, true ) ) {
         // Has the player given input on if stealing is ok?
         if( who.get_value( "THIEF_MODE" ) == "THIEF_ASK" ) {
             Pickup::query_thief();
         }
         if( who.get_value( "THIEF_MODE" ) == "THIEF_HONEST" ) {
             if( who.get_value( "THIEF_MODE_KEEP" ) != "YES" ) {
                 who.set_value( "THIEF_MODE", "THIEF_ASK" );
             }
             return false;
         }
     }
     return true;
 }
References Creature::get_value(), item::is_owned_by(), Pickup::query_thief(), and Creature::set_value().
Referenced by avatar_action::check_stealing(), wear_activity_actor::do_turn(), and wield_activity_actor::do_turn().
chop_single_do_turn()
static void chop_single_do_turn (player_activity & act) static
Definition at line 6226 of file activity_actor.cpp.
 {
     const map &here = get_map();
     sfx::play_activity_sound( "tool", "axe", sfx::get_heard_volume( here.getlocal( act.placement ) ) );
     if( calendar::once_every( 1_minutes ) ) {
         //~ Sound of a wood chopping tool at work!
         sounds::sound( here.getlocal( act.placement ), 15, sounds::sound_t::activity, _( "CHK!" ) );
     }
 }
References _, act, sounds::activity, sfx::get_heard_volume(), get_map(), map::getlocal(), calendar::once_every(), sfx::play_activity_sound(), and sounds::sound().
Referenced by chop_logs_activity_actor::do_turn(), chop_planks_activity_actor::do_turn(), and chop_tree_activity_actor::do_turn().
debug_drop_list()
static void debug_drop_list (const std::vector< drop_or_stash_item_info > & items) static
Definition at line 4062 of file activity_actor.cpp.
 {
     if( !debug_mode ) {
         return;
     }
     std::string res( "Items ordered to drop:\n" );
     for( const drop_or_stash_item_info &it : items ) {
         item_location loc = it.loc();
         if( !loc ) {
             // some items could have been destroyed by e.g. monster attack
             continue;
         }
         res += string_format( "Drop %d %s\n", it.count(), loc->display_name( it.count() ) );
     }
     popup( res, PF_GET_KEY );
 }
References debug_mode, item::display_name(), PF_GET_KEY, popup(), and string_format().
Referenced by obtain_activity_items().
deserialize()
void deserialize (cata::clone_ptr< activity_actor > & actor, const JsonValue & jsin)
Definition at line 7778 of file activity_actor.cpp.
 {
     if( jsin.test_null() ) {
         actor = nullptr;
     } else {
         JsonObject data = jsin.get_object();
         if( data.has_member( "actor_data" ) ) {
             activity_id actor_type;
             data.read( "actor_type", actor_type );
             auto deserializer = activity_actors::deserialize_functions.find( actor_type );
             if( deserializer != activity_actors::deserialize_functions.end() ) {
                 JsonValue jv = data.get_member( "actor_data" );
                 actor = deserializer->second( jv );
             } else {
                 debugmsg( "Failed to find activity actor deserializer for type \"%s\"", actor_type.c_str() );
                 actor = nullptr;
             }
         } else {
             debugmsg( "Failed to load activity actor" );
             actor = nullptr;
         }
     }
 }
References string_id< T >::c_str(), debugmsg, activity_actors::deserialize_functions, keycode::end, JsonObject::get_member(), JsonValue::get_object(), JsonObject::has_member(), JsonObject::read(), and JsonValue::test_null().
Referenced by options_manager::load(), and auto_pickup::player_settings::load().
enumerate_ints_to_string()
static std::string enumerate_ints_to_string (const std::vector< int > & vec) static
Definition at line 1484 of file activity_actor.cpp.
 {
     return enumerate_as_string( vec, []( const int &it ) {
         return std::to_string( it );
     } );
 }
References enumerate_as_string(), and to_string().
Referenced by bikerack_racking_activity_actor::finish(), and bikerack_unracking_activity_actor::finish().
get_hack_type()
static hack_type get_hack_type (const tripoint & examp) static
Definition at line 790 of file activity_actor.cpp.
 {
     hack_type type = hack_type::NONE;
     map &here = get_map();
     const furn_t &xfurn_t = here.furn( examp ).obj();
     const ter_t &xter_t = here.ter( examp ).obj();
     if( xter_t.has_examine( iexamine::pay_gas ) || xfurn_t.has_examine( iexamine::pay_gas ) ) {
         type = hack_type::GAS;
     } else if( xter_t.has_examine( "cardreader" ) ||
                xfurn_t.has_examine( "cardreader" ) ) {
         type = hack_type::DOOR;
     } else if( xter_t.has_examine( iexamine::gunsafe_el ) ||
                xfurn_t.has_examine( iexamine::gunsafe_el ) ) {
         type = hack_type::SAFE;
     }
     return type;
 }
References DOOR, map::furn(), GAS, get_map(), iexamine::gunsafe_el(), map_data_common_t::has_examine(), NONE, int_id< T >::obj(), iexamine::pay_gas(), SAFE, and map::ter().
Referenced by hacking_activity_actor::finish().
get_quality_from_string()
static int get_quality_from_string (const std::string_view s) static
Definition at line 957 of file activity_actor.cpp.
 {
     const ret_val<int> try_quality = try_parse_integer<int>( s, false );
     if( try_quality.success() ) {
         return try_quality.value();
     } else {
         debugmsg( "Error parsing photo quality: %s", try_quality.str() );
         return 0;
     }
 }
References debugmsg, ret_val_common::str(), ret_val_common::success(), try_parse_integer< int >(), and ret_val< T >::value().
Referenced by data_handling_activity_actor::do_turn().
hack_attempt()
static hack_result hack_attempt (Character & who, item_location & tool) static
Definition at line 764 of file activity_actor.cpp.
 {
     // TODO: Remove this once player -> Character migration is complete
     {
         who.practice( skill_computer, 20 );
     }
     // only skilled supergenius never cause short circuits, but the odds are low for people
     // with moderate skills
     const int hack_stddev = 5;
     int success = std::ceil( normal_roll( hack_level( who, tool ), hack_stddev ) );
     if( success < 0 ) {
         who.add_msg_if_player( _( "You cause a short circuit!" ) );
         tool->ammo_consume( tool->ammo_required(), tool.position(), &who );
         if( success <= -5 ) {
             tool->ammo_consume( ( tool->ammo_required() * 2 ), tool.position(), &who );
         }
         return hack_result::FAIL;
     } else if( success < 6 ) {
         return hack_result::NOTHING;
     } else {
         return hack_result::SUCCESS;
     }
 }
References _, Character::add_msg_if_player(), item::ammo_consume(), item::ammo_required(), ceil(), FAIL, hack_level(), normal_roll(), NOTHING, item_location::position(), Character::practice(), skill_computer, and SUCCESS.
Referenced by hacking_activity_actor::finish().
hack_level()
static int hack_level (const Character & who, item_location & tool) static
Computer increases success chance of hacking Intelligence increases success chance of hacking
Definition at line 750 of file activity_actor.cpp.
 {
     // Quality of 2 is a base electrohack, which results in no modifier
     int tool_quality_modifier = tool->get_quality( qual_HACK ) - 2;
     ///\EFFECT_COMPUTER increases success chance of hacking
     // odds go up with int>8, down with int<8
     // 4 int stat is worth 1 computer skill here
     ///\EFFECT_INT increases success chance of hacking
     // tool_quality_modifier may increase or reduce the success chance of hacking
     return round( who.get_greater_skill_or_knowledge_level( skill_computer ) + tool_quality_modifier +
                   static_cast<float>
                   ( who.int_cur ) / 2.0f - 8 );
 }
References Character::get_greater_skill_or_knowledge_level(), item::get_quality(), Character::int_cur, qual_HACK, round(), and skill_computer.
Referenced by hack_attempt().
is_bulk_load()
static bool is_bulk_load (const item_location & lhs, const item_location & rhs) static
Definition at line 4544 of file activity_actor.cpp.
 {
     if( lhs.where() == rhs.where() && lhs->stacks_with( *rhs ) ) {
         switch( lhs.where() ) {
             case item_location::type::container:
                 return lhs.parent_item() == rhs.parent_item();
                 break;
             case item_location::type::map:
             case item_location::type::vehicle:
                 return lhs.position() == rhs.position();
                 break;
             default:
                 break;
         }
     }
     return false;
 }
References item_location::container, item_location::map, item_location::parent_item(), item_location::position(), item::stacks_with(), item_location::vehicle, and item_location::where().
Referenced by insert_item_activity_actor::finish().
is_bulk_unload()
static bool is_bulk_unload (const item_location & lhs, const item_location & rhs) static
Definition at line 4080 of file activity_actor.cpp.
 {
     if( lhs.where() == item_location::type::container &&
         rhs.where() == item_location::type::container && lhs.parent_item() == rhs.parent_item() ) {
         return true;
     }
     return false;
 }
References item_location::container, item_location::parent_item(), and item_location::where().
Referenced by obtain_activity_items().
is_valid_book()
static bool is_valid_book (const item_location & book) static
Definition at line 1769 of file activity_actor.cpp.
 {
     // If book is invalid, perhaps we lost it during the activity
     // If book is valid but not a book, it's probably due to a bug where
     // `item_location` points to the wrong item after a save/load cycle.
     // In both cases cancel activity to avoid segfault.
     return book && book->is_book();
 }
References item::is_book().
Referenced by read_activity_actor::can_resume_with_internal(), cancel_if_book_invalid(), read_activity_actor::get_progress_message(), and read_activity_actor::serialize().
item_move_cost()
static int item_move_cost (Character & who, item_location & item, bool bulk_cost) static
Definition at line 4530 of file activity_actor.cpp.
 {
     if( !bulk_cost ) {
         // Cost to take an item from a container or map
         const int obtain_cost = item.obtain_cost( who );
         // Cost to move an item to a container, vehicle or the ground
         const int move_cost = Pickup::cost_to_move_item( who, *item );
         return obtain_cost + move_cost;
     } else {
         // Pure cost to handling item excluding overhead.
         return std::max( who.item_handling_cost( *item, true, 0, -1, true ), 1 );
     }
 }
References Pickup::cost_to_move_item(), Character::item_handling_cost(), max(), and item::obtain_cost().
Referenced by insert_item_activity_actor::finish(), and insert_item_activity_actor::start().
move_item()
static void move_item (Character & you, item & it, const int quantity, const tripoint_bub_ms & src, const tripoint_bub_ms & dest, vehicle * src_veh, int src_part) static
Definition at line 6996 of file activity_actor.cpp.
 {
     item leftovers = it;
     if( quantity != 0 && it.count_by_charges() ) {
         // Reinserting leftovers happens after item removal to avoid stacking issues.
         leftovers.charges = it.charges - quantity;
         if( leftovers.charges > 0 ) {
             it.charges = quantity;
         }
     } else {
         leftovers.charges = 0;
     }
     map &here = get_map();
     // Check that we can pick it up.
     if( it.made_of_from_type( phase_id::SOLID ) ) {
         you.mod_moves( -activity_handlers::move_cost( it, src, dest ) );
         put_into_vehicle_or_drop( you, item_drop_reason::deliberate, { it }, dest );
         // Remove from map or vehicle.
         if( src_veh ) {
             vehicle_part &vp_src = src_veh->part( src_part );
             src_veh->remove_item( vp_src, &it );
         } else {
             here.i_rem( src, &it );
         }
     }
     // If we didn't pick up a whole stack, put the remainder back where it came from.
     if( leftovers.charges > 0 ) {
         if( src_veh ) {
             vehicle_part &vp_src = src_veh->part( src_part );
             if( !src_veh->add_item( vp_src, leftovers ) ) {
                 debugmsg( "SortLoot: Source vehicle failed to receive leftover charges." );
             }
         } else {
             here.add_item_or_charges( src, leftovers );
         }
     }
 }
References vehicle::add_item(), map::add_item_or_charges(), item::charges, item::count_by_charges(), debugmsg, deliberate, get_map(), map::i_rem(), item::made_of_from_type(), Creature::mod_moves(), activity_handlers::move_cost(), vehicle::part(), put_into_vehicle_or_drop(), vehicle::remove_item(), and SOLID.
Referenced by unload_loot_activity_actor::do_turn().
obtain_activity_items()
static std::list<item> obtain_activity_items (std::vector< drop_or_stash_item_info > & items, contents_change_handler & handler, Character & who, bool & bulk_unload) static
Definition at line 4090 of file activity_actor.cpp.
 {
     std::list<item> res;
     debug_drop_list( items );
     auto it = items.begin();
     for( ; it != items.end(); ++it ) {
         item_location loc = it->loc();
         if( !loc ) {
             // some items could have been destroyed by e.g. monster attack
             continue;
         }
         int consumed_moves;
         if( !bulk_unload ) {
             // Cost to take an item from a container or map
             consumed_moves = loc.obtain_cost( who, it->count() );
         } else {
             // Pure cost to handling item excluding overhead.
             consumed_moves = std::max( who.item_handling_cost( *loc, true, 0, it->count(), true ), 1 );
         }
         if( !who.is_npc() && who.get_moves() <= 0 && consumed_moves > 0 ) {
             break;
         }
         // Check if next is bulk unload before moving item.
         auto it_next = std::next( it );
         if( it_next != items.end() && it_next->loc() ) {
             bulk_unload = is_bulk_unload( loc, it_next->loc() );
         }
         who.mod_moves( -consumed_moves );
         // If item is inside another (container/pocket), unseal it, and update encumbrance
         if( loc.has_parent() ) {
             // Save parent items to be handled when finishing or canceling activity,
             // in case there are still other items to drop from the same container.
             // This assumes that an item and any of its parents/ancestors are not
             // dropped at the same time.
             handler.unseal_pocket_containing( loc );
         } else {
             // when parent's encumbrance cannot be marked as dirty,
             // mark character's encumbrance as dirty instead (correctness over performance)
             who.set_check_encumbrance( true );
         }
         // Take off the item or remove it from where it's been
         if( loc.where_recursive() == item_location::type::map ||
             loc.where_recursive() == item_location::type::vehicle ) {
             item copy( *loc );
             if( loc->count_by_charges() && loc->count() > it->count() ) {
                 copy.charges -= it->count();
             }
             loc.remove_item();
             res.push_back( copy );
         } else if( who.is_worn( *loc ) ) {
             who.takeoff( loc, &res );
         } else if( loc->count_by_charges() ) {
             res.push_back( who.reduce_charges( &*loc, it->count() ) );
         } else {
             res.push_back( who.i_rem( &*loc ) );
         }
     }
     // Remove handled items from activity
     items.erase( items.begin(), it );
     return res;
 }
References item::charges, item::count(), item::count_by_charges(), debug_drop_list(), Creature::get_moves(), item_location::has_parent(), Character::i_rem(), is_bulk_unload(), Character::is_npc(), Character::is_worn(), Character::item_handling_cost(), item_location::map, max(), Creature::mod_moves(), item_location::obtain_cost(), Character::reduce_charges(), item_location::remove_item(), Character::set_check_encumbrance(), Character::takeoff(), contents_change_handler::unseal_pocket_containing(), item_location::vehicle, and item_location::where_recursive().
Referenced by drop_activity_actor::do_turn(), and stash_activity_actor::do_turn().
print_data_handling_tally()
static void print_data_handling_tally (Character & who, int encrypted_cards, int photos, int songs, const std::vector< recipe_id > & recipes, int extended_photos, int monster_photos) static
Definition at line 1094 of file activity_actor.cpp.
 {
     if( !recipes.empty() ) {
         who.add_msg_if_player( m_good, _( "Downloaded %d %s: %s." ), recipes.size(),
                                n_gettext( "recipe", "recipes", recipes.size() ),
         enumerate_as_string( recipes, []( const recipe_id & rid ) {
             return rid->result_name();
         } ) );
     }
     if( monster_photos > 0 ) {
         who.add_msg_if_player( m_good, _( "You have updated your monster collection." ) );
     }
     if( extended_photos > 0 ) {
         who.add_msg_if_player( m_good, _( "You have downloaded your photos." ) );
     }
     if( encrypted_cards > 0 ) {
         who.add_msg_if_player( m_bad, _( "%d %s appeared to be encrypted or corrupted." ),
                                encrypted_cards, n_gettext( "card", "cards", encrypted_cards ) );
     }
     if( photos > 0 && who.is_avatar() ) {
         who.add_msg_if_player( m_good, _( "Downloaded %d new %s." ),
                                photos, n_gettext( "photo", "photos", photos ) );
     }
     if( songs > 0 && who.is_avatar() ) {
         who.add_msg_if_player( m_good, _( "Downloaded %d new %s." ),
                                songs, n_gettext( "song", "songs", songs ) );
     }
     if( !( photos || songs || monster_photos || extended_photos || !recipes.empty() ) ) {
         who.add_msg_if_player( m_warning, _( "No new data has been discovered." ) );
     }
 }
References _, Character::add_msg_if_player(), enumerate_as_string(), Creature::is_avatar(), m_bad, m_good, m_warning, n_gettext, and recipe::result_name().
Referenced by data_handling_activity_actor::canceled(), and data_handling_activity_actor::finish().
serialize()
void serialize (const cata::clone_ptr< activity_actor > & actor, JsonOut & jsout)
Definition at line 7764 of file activity_actor.cpp.
 {
     if( !actor ) {
         jsout.write_null();
     } else {
         jsout.start_object();
         jsout.member( "actor_type", actor->get_type() );
         jsout.member( "actor_data", *actor );
         jsout.end_object();
     }
 }
References JsonOut::end_object(), activity_actor::get_type(), JsonOut::member(), JsonOut::start_object(), and JsonOut::write_null().
Referenced by edit_json(), activity_handlers::fill_liquid_do_turn(), options_manager::save(), auto_pickup::player_settings::save(), and serialize_liquid_source().
stash_on_pet()
static void stash_on_pet (const std::list< item > & items, monster & pet, Character & who) static
Definition at line 4314 of file activity_actor.cpp.
 {
     units::volume remaining_volume = pet.storage_item->get_total_capacity() - pet.get_carried_volume();
     units::mass remaining_weight = pet.weight_capacity() - pet.get_carried_weight();
     map &here = get_map();
     for( const item &it : items ) {
         if( it.volume() > remaining_volume ) {
             add_msg( m_bad, _( "%1$s did not fit and fell to the %2$s." ), it.display_name(),
                      here.name( pet.pos() ) );
             here.add_item_or_charges( pet.pos(), it );
         } else if( it.weight() > remaining_weight ) {
             add_msg( m_bad, _( "%1$s is too heavy and fell to the %2$s." ), it.display_name(),
                      here.name( pet.pos() ) );
             here.add_item_or_charges( pet.pos(), it );
         } else {
             pet.add_item( it );
             remaining_volume -= it.volume();
             remaining_weight -= it.weight();
         }
         // TODO: if NPCs can have pets or move items onto pets
         item( it ).handle_pickup_ownership( who );
     }
 }
References _, monster::add_item(), map::add_item_or_charges(), add_msg(), monster::get_carried_volume(), monster::get_carried_weight(), get_map(), item::handle_pickup_ownership(), m_bad, map::name(), Creature::pos(), monster::storage_item, and monster::weight_capacity().
Referenced by stash_activity_actor::do_turn().
try_insert()
static ret_val<void> try_insert (item_location & holster, drop_location & holstered_item, int * charges_added, Character * carrier) static
Definition at line 4576 of file activity_actor.cpp.
 {
     item &it = *holstered_item.first;
     ret_val<void> ret = ret_val<void>::make_failure( _( "item can't be stored there" ) );
     if( holster.get_item()->has_flag( json_flag_NO_RELOAD ) ) {
         return ret_val<void>::make_failure( _( "destination can't be reloaded" ) );
     }
     if( charges_added == nullptr ) {
         if( it.is_bucket_nonempty() ) {
             debugmsg( "ACT_INSERT_ITEM tried to stash a spillable container without spilling its contents first" );
             return ret_val<void>::make_failure( _( "item would spill" ) );
         }
         ret = holster->can_contain_directly( it );
         if( !ret.success() ) {
             return ret;
         }
         ret = holster.parents_can_contain_recursive( &it );
         if( !ret.success() ) {
             return ret;
         }
         return holster->put_in( it, pocket_type::CONTAINER, /*unseal_pockets=*/true, carrier );
     }
     ret = holster->can_contain_partial_directly( it );
     if( !ret.success() ) {
         return ret;
     }
     ret_val<int> max_parent_charges = holster.max_charges_by_parent_recursive( it );
     if( !max_parent_charges.success() ) {
         return ret_val<void>::make_failure( max_parent_charges.str() );
     }
     int charges_to_insert = std::min( holstered_item.second, max_parent_charges.value() );
     *charges_added = holster->fill_with( it, charges_to_insert, /*unseal_pockets=*/true,
                                          /*allow_sealed=*/true, /*ignore_settings*/true, /*into_bottom*/true, carrier );
     if( *charges_added <= 0 ) {
         return ret_val<void>::make_failure( _( "item can't be stored there" ) );
     }
     return ret;
 }
References _, CONTAINER, debugmsg, game_menus::inv::holster(), item::is_bucket_nonempty(), json_flag_NO_RELOAD, ret_val< T >::make_failure(), min(), cata::hash64_detail::ret, ret_val_common::str(), ret_val_common::success(), and ret_val< T >::value().
Referenced by insert_item_activity_actor::finish().
Variable Documentation
ACT_AIM
const activity_id ACT_AIM("ACT_AIM") ("ACT_AIM") static
ACT_AUTODRIVE
const activity_id ACT_AUTODRIVE("ACT_AUTODRIVE") ("ACT_AUTODRIVE") static
ACT_BIKERACK_RACKING
const activity_id ACT_BIKERACK_RACKING("ACT_BIKERACK_RACKING") ("ACT_BIKERACK_RACKING") static
ACT_BIKERACK_UNRACKING
const activity_id ACT_BIKERACK_UNRACKING("ACT_BIKERACK_UNRACKING") ("ACT_BIKERACK_UNRACKING") static
ACT_BINDER_COPY_RECIPE
const activity_id ACT_BINDER_COPY_RECIPE("ACT_BINDER_COPY_RECIPE") ("ACT_BINDER_COPY_RECIPE") static
ACT_BOLTCUTTING
const activity_id ACT_BOLTCUTTING("ACT_BOLTCUTTING") ("ACT_BOLTCUTTING") static
ACT_CHOP_LOGS
const activity_id ACT_CHOP_LOGS("ACT_CHOP_LOGS") ("ACT_CHOP_LOGS") static
ACT_CHOP_PLANKS
const activity_id ACT_CHOP_PLANKS("ACT_CHOP_PLANKS") ("ACT_CHOP_PLANKS") static
ACT_CHOP_TREE
const activity_id ACT_CHOP_TREE("ACT_CHOP_TREE") ("ACT_CHOP_TREE") static
ACT_CHURN
const activity_id ACT_CHURN("ACT_CHURN") ("ACT_CHURN") static
ACT_CLEAR_RUBBLE
const activity_id ACT_CLEAR_RUBBLE("ACT_CLEAR_RUBBLE") ("ACT_CLEAR_RUBBLE") static
ACT_CONSUME
const activity_id ACT_CONSUME("ACT_CONSUME") ("ACT_CONSUME") static
Referenced by consume_activity_actor::finish().
ACT_CONSUME_MEDS_MENU
const activity_id ACT_CONSUME_MEDS_MENU("ACT_CONSUME_MEDS_MENU") ("ACT_CONSUME_MEDS_MENU") static
Referenced by firstaid_activity_actor::finish().
ACT_CRACKING
const activity_id ACT_CRACKING("ACT_CRACKING") ("ACT_CRACKING") static
ACT_CRAFT
const activity_id ACT_CRAFT("ACT_CRAFT") ("ACT_CRAFT") static
ACT_DATA_HANDLING
const activity_id ACT_DATA_HANDLING("ACT_DATA_HANDLING") ("ACT_DATA_HANDLING") static
ACT_DISABLE
const activity_id ACT_DISABLE("ACT_DISABLE") ("ACT_DISABLE") static
ACT_DISASSEMBLE
const activity_id ACT_DISASSEMBLE("ACT_DISASSEMBLE") ("ACT_DISASSEMBLE") static
ACT_DROP
const activity_id ACT_DROP("ACT_DROP") ("ACT_DROP") static
ACT_EAT_MENU
const activity_id ACT_EAT_MENU("ACT_EAT_MENU") ("ACT_EAT_MENU") static
Referenced by firstaid_activity_actor::finish().
ACT_EBOOKSAVE
const activity_id ACT_EBOOKSAVE("ACT_EBOOKSAVE") ("ACT_EBOOKSAVE") static
ACT_FIRSTAID
const activity_id ACT_FIRSTAID("ACT_FIRSTAID") ("ACT_FIRSTAID") static
Referenced by consume_activity_actor::finish().
ACT_FORAGE
const activity_id ACT_FORAGE("ACT_FORAGE") ("ACT_FORAGE") static
ACT_FURNITURE_MOVE
const activity_id ACT_FURNITURE_MOVE("ACT_FURNITURE_MOVE") ("ACT_FURNITURE_MOVE") static
ACT_GLIDE
const activity_id ACT_GLIDE("ACT_GLIDE") ("ACT_GLIDE") static
ACT_GUNMOD_ADD
const activity_id ACT_GUNMOD_ADD("ACT_GUNMOD_ADD") ("ACT_GUNMOD_ADD") static
ACT_GUNMOD_REMOVE
const activity_id ACT_GUNMOD_REMOVE("ACT_GUNMOD_REMOVE") ("ACT_GUNMOD_REMOVE") static
ACT_HACKING
const activity_id ACT_HACKING("ACT_HACKING") ("ACT_HACKING") static
ACT_HACKSAW
const activity_id ACT_HACKSAW("ACT_HACKSAW") ("ACT_HACKSAW") static
ACT_HAIRCUT
const activity_id ACT_HAIRCUT("ACT_HAIRCUT") ("ACT_HAIRCUT") static
ACT_HARVEST
const activity_id ACT_HARVEST("ACT_HARVEST") ("ACT_HARVEST") static
ACT_HOTWIRE_CAR
const activity_id ACT_HOTWIRE_CAR("ACT_HOTWIRE_CAR") ("ACT_HOTWIRE_CAR") static
ACT_INSERT_ITEM
const activity_id ACT_INSERT_ITEM("ACT_INSERT_ITEM") ("ACT_INSERT_ITEM") static
ACT_INVOKE_ITEM
const activity_id ACT_INVOKE_ITEM("ACT_INVOKE_ITEM") ("ACT_INVOKE_ITEM") static
ACT_LOCKPICK
const activity_id ACT_LOCKPICK("ACT_LOCKPICK") ("ACT_LOCKPICK") static
ACT_LONGSALVAGE
const activity_id ACT_LONGSALVAGE("ACT_LONGSALVAGE") ("ACT_LONGSALVAGE") static
ACT_MEDITATE
const activity_id ACT_MEDITATE("ACT_MEDITATE") ("ACT_MEDITATE") static
ACT_MIGRATION_CANCEL
const activity_id ACT_MIGRATION_CANCEL("ACT_MIGRATION_CANCEL") ("ACT_MIGRATION_CANCEL") static
ACT_MILK
const activity_id ACT_MILK("ACT_MILK") ("ACT_MILK") static
ACT_MOP
const activity_id ACT_MOP("ACT_MOP") ("ACT_MOP") static
ACT_MOVE_ITEMS
const activity_id ACT_MOVE_ITEMS("ACT_MOVE_ITEMS") ("ACT_MOVE_ITEMS") static
ACT_MULTIPLE_CHOP_TREES
const activity_id ACT_MULTIPLE_CHOP_TREES("ACT_MULTIPLE_CHOP_TREES") ("ACT_MULTIPLE_CHOP_TREES") static
Referenced by chop_tree_activity_actor::finish().
ACT_OPEN_GATE
const activity_id ACT_OPEN_GATE("ACT_OPEN_GATE") ("ACT_OPEN_GATE") static
ACT_OXYTORCH
const activity_id ACT_OXYTORCH("ACT_OXYTORCH") ("ACT_OXYTORCH") static
ACT_PICKUP
const activity_id ACT_PICKUP("ACT_PICKUP") ("ACT_PICKUP") static
ACT_PICKUP_MENU
const activity_id ACT_PICKUP_MENU("ACT_PICKUP_MENU") ("ACT_PICKUP_MENU") static
ACT_PLAY_WITH_PET
const activity_id ACT_PLAY_WITH_PET("ACT_PLAY_WITH_PET") ("ACT_PLAY_WITH_PET") static
ACT_PRYING
const activity_id ACT_PRYING("ACT_PRYING") ("ACT_PRYING") static
ACT_READ
const activity_id ACT_READ("ACT_READ") ("ACT_READ") static
ACT_REEL_CABLE
const activity_id ACT_REEL_CABLE("ACT_REEL_CABLE") ("ACT_REEL_CABLE") static
ACT_RELOAD
const activity_id ACT_RELOAD("ACT_RELOAD") ("ACT_RELOAD") static
ACT_SHAVE
const activity_id ACT_SHAVE("ACT_SHAVE") ("ACT_SHAVE") static
ACT_SHEARING
const activity_id ACT_SHEARING("ACT_SHEARING") ("ACT_SHEARING") static
ACT_STASH
const activity_id ACT_STASH("ACT_STASH") ("ACT_STASH") static
ACT_TENT_DECONSTRUCT
const activity_id ACT_TENT_DECONSTRUCT("ACT_TENT_DECONSTRUCT") ("ACT_TENT_DECONSTRUCT") static
ACT_TENT_PLACE
const activity_id ACT_TENT_PLACE("ACT_TENT_PLACE") ("ACT_TENT_PLACE") static
ACT_TRY_SLEEP
const activity_id ACT_TRY_SLEEP("ACT_TRY_SLEEP") ("ACT_TRY_SLEEP") static
ACT_UNLOAD
const activity_id ACT_UNLOAD("ACT_UNLOAD") ("ACT_UNLOAD") static
ACT_UNLOAD_LOOT
const activity_id ACT_UNLOAD_LOOT("ACT_UNLOAD_LOOT") ("ACT_UNLOAD_LOOT") static
Referenced by unload_loot_activity_actor::do_turn().
ACT_VEHICLE_FOLD
const activity_id ACT_VEHICLE_FOLD("ACT_VEHICLE_FOLD") ("ACT_VEHICLE_FOLD") static
ACT_VEHICLE_UNFOLD
const activity_id ACT_VEHICLE_UNFOLD("ACT_VEHICLE_UNFOLD") ("ACT_VEHICLE_UNFOLD") static
ACT_WASH
const activity_id ACT_WASH("ACT_WASH") ("ACT_WASH") static
ACT_WEAR
const activity_id ACT_WEAR("ACT_WEAR") ("ACT_WEAR") static
ACT_WIELD
const activity_id ACT_WIELD("ACT_WIELD") ("ACT_WIELD") static
ACT_WORKOUT_ACTIVE
const activity_id ACT_WORKOUT_ACTIVE("ACT_WORKOUT_ACTIVE") ("ACT_WORKOUT_ACTIVE") static
Referenced by workout_activity_actor::start().
ACT_WORKOUT_HARD
const activity_id ACT_WORKOUT_HARD("ACT_WORKOUT_HARD") ("ACT_WORKOUT_HARD") static
Referenced by workout_activity_actor::start().
ACT_WORKOUT_LIGHT
const activity_id ACT_WORKOUT_LIGHT("ACT_WORKOUT_LIGHT") ("ACT_WORKOUT_LIGHT") static
Referenced by workout_activity_actor::start().
ACT_WORKOUT_MODERATE
const activity_id ACT_WORKOUT_MODERATE("ACT_WORKOUT_MODERATE") ("ACT_WORKOUT_MODERATE") static
Referenced by workout_activity_actor::start().
ammo_plutonium
const ammotype ammo_plutonium("plutonium") ("plutonium") static
Referenced by unload_activity_actor::unload().
effect_docile
const efftype_id effect_docile("docile") ("docile") static
Referenced by disable_activity_actor::finish().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by glide_activity_actor::do_turn().
effect_gliding
const efftype_id effect_gliding("gliding") ("gliding") static
Referenced by glide_activity_actor::do_turn(), glide_activity_actor::finish(), and glide_activity_actor::glide_activity_actor().
effect_paid
const efftype_id effect_paid("paid") ("paid") static
Referenced by disable_activity_actor::can_disable_or_reprogram().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by stash_activity_actor::do_turn().
effect_sensor_stun
const efftype_id effect_sensor_stun("sensor_stun") ("sensor_stun") static
Referenced by disable_activity_actor::can_disable_or_reprogram().
effect_sheared
const efftype_id effect_sheared("sheared") ("sheared") static
Referenced by shearing_activity_actor::finish().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by try_sleep_activity_actor::do_turn(), and try_sleep_activity_actor::finish().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by shearing_activity_actor::canceled(), milk_activity_actor::finish(), shearing_activity_actor::finish(), and shearing_activity_actor::start().
effect_took_thorazine
const efftype_id effect_took_thorazine("took_thorazine") ("took_thorazine") static
Referenced by read_activity_actor::npc_read(), and read_activity_actor::player_read().
effect_worked_on
const efftype_id effect_worked_on("worked_on") ("worked_on") static
Referenced by disable_activity_actor::do_turn(), and disable_activity_actor::start().
faction_your_followers
const faction_id faction_your_followers("your_followers") ("your_followers") static
Referenced by read_activity_actor::npc_read().
furn_f_gunsafe_mj
const furn_str_id furn_f_gunsafe_mj("f_gunsafe_mj") ("f_gunsafe_mj") static
Referenced by lockpick_activity_actor::finish().
furn_f_gunsafe_ml
const furn_str_id furn_f_gunsafe_ml("f_gunsafe_ml") ("f_gunsafe_ml") static
Referenced by lockpick_activity_actor::finish().
furn_f_safe_c
const furn_str_id furn_f_safe_c("f_safe_c") ("f_safe_c") static
Referenced by safecracking_activity_actor::finish().
furn_f_safe_o
const furn_str_id furn_f_safe_o("f_safe_o") ("f_safe_o") static
Referenced by hacking_activity_actor::finish().
gun_mode_DEFAULT
const gun_mode_id gun_mode_DEFAULT("DEFAULT") ("DEFAULT") static
Referenced by gunmod_remove_activity_actor::gunmod_remove().
Item_spawn_data_forage_autumn
const item_group_id Item_spawn_data_forage_autumn("forage_autumn") ("forage_autumn") static
Referenced by forage_activity_actor::finish().
Item_spawn_data_forage_spring
const item_group_id Item_spawn_data_forage_spring("forage_spring") ("forage_spring") static
Referenced by forage_activity_actor::finish().
Item_spawn_data_forage_summer
const item_group_id Item_spawn_data_forage_summer("forage_summer") ("forage_summer") static
Referenced by forage_activity_actor::finish().
Item_spawn_data_forage_winter
const item_group_id Item_spawn_data_forage_winter("forage_winter") ("forage_winter") static
Referenced by forage_activity_actor::finish().
Item_spawn_data_trash_forest
const item_group_id Item_spawn_data_trash_forest("trash_forest") ("trash_forest") static
Referenced by forage_activity_actor::finish().
itype_2x4
const itype_id itype_2x4("2x4") ("2x4") static
Referenced by chop_planks_activity_actor::finish().
itype_detergent
const itype_id itype_detergent("detergent") ("detergent") static
Referenced by wash_activity_actor::finish().
itype_disassembly
const itype_id itype_disassembly("disassembly") ("disassembly") static
Referenced by disassemble_activity_actor::start().
itype_liquid_soap
const itype_id itype_liquid_soap("liquid_soap") ("liquid_soap") static
Referenced by wash_activity_actor::finish().
itype_log
const itype_id itype_log("log") ("log") static
Referenced by chop_logs_activity_actor::finish().
itype_paper
const itype_id itype_paper("paper") ("paper") static
Referenced by bookbinder_copy_activity_actor::finish().
itype_pseudo_bio_picklock
const itype_id itype_pseudo_bio_picklock("pseudo_bio_picklock") ("pseudo_bio_picklock") static
Referenced by lockpick_activity_actor::use_bionic().
itype_soap
const itype_id itype_soap("soap") ("soap") static
Referenced by wash_activity_actor::finish().
itype_splinter
const itype_id itype_splinter("splinter") ("splinter") static
Referenced by chop_logs_activity_actor::finish(), and chop_planks_activity_actor::finish().
itype_stick_long
const itype_id itype_stick_long("stick_long") ("stick_long") static
Referenced by chop_logs_activity_actor::finish().
itype_water
const itype_id itype_water("water") ("water") static
Referenced by wash_activity_actor::finish().
itype_water_clean
const itype_id itype_water_clean("water_clean") ("water_clean") static
Referenced by wash_activity_actor::finish().
json_flag_ALWAYS_AIMED
const flag_id json_flag_ALWAYS_AIMED("ALWAYS_AIMED") ("ALWAYS_AIMED") static
Referenced by aim_activity_actor::do_turn().
json_flag_NO_RELOAD
const flag_id json_flag_NO_RELOAD("NO_RELOAD") ("NO_RELOAD") static
Referenced by try_insert().
json_flag_SAFECRACK_NO_TOOL
const json_character_flag json_flag_SAFECRACK_NO_TOOL("SAFECRACK_NO_TOOL") ("SAFECRACK_NO_TOOL") static
Referenced by safecracking_activity_actor::do_turn().
mon_manhack
const mtype_id mon_manhack("mon_manhack") ("mon_manhack") static
Referenced by disable_activity_actor::can_disable_or_reprogram().
move_mode_prone
const move_mode_id move_mode_prone("prone") ("prone") static
Referenced by try_sleep_activity_actor::canceled(), and try_sleep_activity_actor::start().
move_mode_walk
const move_mode_id move_mode_walk("walk") ("walk") static
Referenced by try_sleep_activity_actor::canceled(), try_sleep_activity_actor::finish(), and try_sleep_activity_actor::query_keep_trying().
proficiency_prof_lockpicking
const proficiency_id proficiency_prof_lockpicking("prof_lockpicking") ("prof_lockpicking") static
Referenced by lockpick_activity_actor::finish().
proficiency_prof_lockpicking_expert
const proficiency_id proficiency_prof_lockpicking_expert("prof_lockpicking_expert") ("prof_lockpicking_expert") static
Referenced by lockpick_activity_actor::finish().
proficiency_prof_safecracking
const proficiency_id proficiency_prof_safecracking("prof_safecracking") ("prof_safecracking") static
Referenced by safecracking_activity_actor::do_turn(), and safecracking_activity_actor::safecracking_time().
qual_HACK
const quality_id qual_HACK("HACK") ("HACK") static
Referenced by hack_level().
qual_LOCKPICK
const quality_id qual_LOCKPICK("LOCKPICK") ("LOCKPICK") static
Referenced by lockpick_activity_actor::finish().
qual_PRY
const quality_id qual_PRY("PRY") ("PRY") static
Referenced by prying_activity_actor::handle_prying(), and prying_activity_actor::prying_time().
qual_PRYING_NAIL
const quality_id qual_PRYING_NAIL("PRYING_NAIL") ("PRYING_NAIL") static
Referenced by prying_activity_actor::start().
qual_SAW_M
const quality_id qual_SAW_M("SAW_M") ("SAW_M") static
Referenced by hacksaw_activity_actor::start().
qual_SHEAR
const quality_id qual_SHEAR("SHEAR") ("SHEAR") static
Referenced by shearing_activity_actor::do_turn(), and shearing_activity_actor::start().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by hack_attempt(), and hack_level().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by disable_activity_actor::can_disable_or_reprogram(), and disable_activity_actor::get_disable_turns().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by chop_planks_activity_actor::finish(), and prying_activity_actor::handle_prying_nails().
skill_mechanics
const skill_id skill_mechanics("mechanics") ("mechanics") static
Referenced by disable_activity_actor::can_disable_or_reprogram(), hotwire_car_activity_actor::do_turn(), hotwire_car_activity_actor::finish(), lockpick_activity_actor::finish(), disable_activity_actor::get_disable_turns(), and prying_activity_actor::handle_prying().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by harvest_activity_actor::finish(), and forage_activity_actor::finish().
skill_traps
const skill_id skill_traps("traps") ("traps") static
Referenced by safecracking_activity_actor::do_turn(), lockpick_activity_actor::finish(), and safecracking_activity_actor::safecracking_time().
species_ZOMBIE
const species_id species_ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by glide_activity_actor::do_turn().
ter_t_card_reader_broken
const ter_str_id ter_t_card_reader_broken("t_card_reader_broken") ("t_card_reader_broken") static
Referenced by hacking_activity_actor::finish().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by chop_logs_activity_actor::finish().
ter_t_dirtmound
const ter_str_id ter_t_dirtmound("t_dirtmound") ("t_dirtmound") static
Referenced by churn_activity_actor::finish().
ter_t_door_c
const ter_str_id ter_t_door_c("t_door_c") ("t_door_c") static
Referenced by lockpick_activity_actor::select_location().
ter_t_door_locked_alarm
const ter_str_id ter_t_door_locked_alarm("t_door_locked_alarm") ("t_door_locked_alarm") static
Referenced by lockpick_activity_actor::finish().
ter_t_door_metal_c
const ter_str_id ter_t_door_metal_c("t_door_metal_c") ("t_door_metal_c") static
Referenced by hacking_activity_actor::finish().
ter_t_door_metal_locked
const ter_str_id ter_t_door_metal_locked("t_door_metal_locked") ("t_door_metal_locked") static
Referenced by hacking_activity_actor::finish().
ter_t_stump
const ter_str_id ter_t_stump("t_stump") ("t_stump") static
Referenced by chop_logs_activity_actor::finish().
ter_t_trunk
const ter_str_id ter_t_trunk("t_trunk") ("t_trunk") static
Referenced by chop_logs_activity_actor::finish().
ter_t_underbrush_harvested_autumn
const ter_str_id ter_t_underbrush_harvested_autumn("t_underbrush_harvested_autumn") ("t_underbrush_harvested_autumn") static
Referenced by forage_activity_actor::finish().
ter_t_underbrush_harvested_spring
const ter_str_id ter_t_underbrush_harvested_spring("t_underbrush_harvested_spring") ("t_underbrush_harvested_spring") static
Referenced by forage_activity_actor::finish().
ter_t_underbrush_harvested_summer
const ter_str_id ter_t_underbrush_harvested_summer("t_underbrush_harvested_summer") ("t_underbrush_harvested_summer") static
Referenced by forage_activity_actor::finish().
ter_t_underbrush_harvested_winter
const ter_str_id ter_t_underbrush_harvested_winter("t_underbrush_harvested_winter") ("t_underbrush_harvested_winter") static
Referenced by forage_activity_actor::finish().
trait_SCHIZOPHRENIC
const trait_id trait_SCHIZOPHRENIC("SCHIZOPHRENIC") ("SCHIZOPHRENIC") static
Referenced by read_activity_actor::npc_read(), and read_activity_actor::player_read().
vehicle_prototype_none
const vproto_id vehicle_prototype_none("none") ("none") static
Referenced by vehicle_unfolding_activity_actor::unfold_vehicle().
zone_type_LOOT_IGNORE
const zone_type_id zone_type_LOOT_IGNORE("LOOT_IGNORE") ("LOOT_IGNORE") static
Referenced by unload_loot_activity_actor::do_turn().
zone_type_LOOT_IGNORE_FAVORITES
const zone_type_id zone_type_LOOT_IGNORE_FAVORITES("LOOT_IGNORE_FAVORITES") ("LOOT_IGNORE_FAVORITES") static
Referenced by unload_loot_activity_actor::do_turn().
zone_type_STRIP_CORPSES
const zone_type_id zone_type_STRIP_CORPSES("STRIP_CORPSES") ("STRIP_CORPSES") static
Referenced by unload_loot_activity_actor::do_turn().
zone_type_UNLOAD_ALL
const zone_type_id zone_type_UNLOAD_ALL("UNLOAD_ALL") ("UNLOAD_ALL") static
Referenced by unload_loot_activity_actor::do_turn().