Cataclysm DDA: src/activity_handlers.h File Reference
activity_handlers.h File Reference
#include <algorithm>
#include <functional>
#include <list>
#include <map>
#include <optional>
#include <string>
#include <unordered_set>
#include <vector>
#include "coordinates.h"
#include "requirements.h"
#include "type_id.h"
#include "units_fwd.h"
Classes
struct activity_reason_info
Namespaces
activity_handlers
Macros
#define CATA_SRC_ACTIVITY_HANDLERS_H
Enumerations
enum class requirement_check_result : int { SKIP_LOCATION = 0 , CAN_DO_LOCATION , RETURN_EARLY }
enum class butcher_type : int {
BLEED , QUICK , FULL , FIELD_DRESS ,
SKIN , QUARTER , DISMEMBER , DISSECT ,
NUM_TYPES
}
enum class do_activity_reason : int {
CAN_DO_CONSTRUCTION , CAN_DO_FETCH , NO_COMPONENTS , DONT_HAVE_SKILL ,
NO_ZONE , ALREADY_DONE , UNKNOWN_ACTIVITY , NEEDS_CLEARING ,
NEEDS_HARVESTING , NEEDS_PLANTING , NEEDS_TILLING , BLOCKING_TILE ,
NEEDS_BOOK_TO_LEARN , NEEDS_CHOPPING , NEEDS_TREE_CHOPPING , NEEDS_BIG_BUTCHERING ,
NEEDS_BUTCHERING , NEEDS_CUT_HARVESTING , ALREADY_WORKING , NEEDS_VEH_DECONST ,
NEEDS_VEH_REPAIR , WOULD_PREVENT_VEH_FLYING , NEEDS_MINING , NEEDS_MOP ,
NEEDS_FISHING , NEEDS_CRAFT , NEEDS_DISASSEMBLE
}
enum class item_drop_reason : int { deliberate , too_large , too_heavy , tumbling }
Functions
template<typename Point , typename Container >
std::vector< Point > get_sorted_tiles_by_distance (const Point &center, const Container &tiles)
std::vector< tripoint_bub_ms > route_adjacent (const Character &you, const tripoint_bub_ms &dest)
int butcher_time_to_cut (Character &you, const item &corpse_item, butcher_type action)
void activity_on_turn_drop ()
void activity_on_turn_move_loot (player_activity &act, Character &you)
bool generic_multi_activity_handler (player_activity &act, Character &you, bool check_only=false)
void activity_on_turn_fetch (player_activity &, Character *you)
int get_auto_consume_moves (Character &you, bool food)
bool try_fuel_fire (player_activity &act, Character &you, bool starting_fire=false)
void put_into_vehicle_or_drop (Character &you, item_drop_reason, const std::list< item > &items)
void put_into_vehicle_or_drop (Character &you, item_drop_reason, const std::list< item > &items, const tripoint_bub_ms &where, bool force_ground=false)
std::vector< item_location > drop_on_map (Character &you, item_drop_reason reason, const std::list< item > &items, const tripoint_bub_ms &where)
void repair_item_finish (player_activity *act, Character *you, bool no_menu)
bool activity_handlers::resume_for_multi_activities (Character &you)
void activity_handlers::generic_game_turn_handler (player_activity *act, Character *you, int morale_bonus, int morale_max_bonus)
void activity_handlers::adv_inventory_do_turn (player_activity *act, Character *you)
activity_do_turn functions:
void activity_handlers::armor_layers_do_turn (player_activity *act, Character *you)
void activity_handlers::atm_do_turn (player_activity *act, Character *you)
void activity_handlers::build_do_turn (player_activity *act, Character *you)
void activity_handlers::dismember_do_turn (player_activity *act, Character *you)
void activity_handlers::chop_trees_do_turn (player_activity *act, Character *you)
void activity_handlers::consume_drink_menu_do_turn (player_activity *act, Character *you)
void activity_handlers::consume_food_menu_do_turn (player_activity *act, Character *you)
void activity_handlers::consume_meds_menu_do_turn (player_activity *act, Character *you)
void activity_handlers::eat_menu_do_turn (player_activity *act, Character *you)
void activity_handlers::fertilize_plot_do_turn (player_activity *act, Character *you)
void activity_handlers::fetch_do_turn (player_activity *act, Character *you)
void activity_handlers::fill_liquid_do_turn (player_activity *act, Character *you)
void activity_handlers::find_mount_do_turn (player_activity *act, Character *you)
void activity_handlers::fish_do_turn (player_activity *act, Character *you)
void activity_handlers::game_do_turn (player_activity *act, Character *you)
void activity_handlers::generic_game_do_turn (player_activity *act, Character *you)
void activity_handlers::hand_crank_do_turn (player_activity *act, Character *you)
void activity_handlers::jackhammer_do_turn (player_activity *act, Character *you)
void activity_handlers::move_loot_do_turn (player_activity *act, Character *you)
void activity_handlers::multiple_butcher_do_turn (player_activity *act, Character *you)
void activity_handlers::multiple_chop_planks_do_turn (player_activity *act, Character *you)
void activity_handlers::multiple_construction_do_turn (player_activity *act, Character *you)
void activity_handlers::multiple_craft_do_turn (player_activity *act, Character *you)
void activity_handlers::multiple_dis_do_turn (player_activity *act, Character *you)
void activity_handlers::multiple_farm_do_turn (player_activity *act, Character *you)
void activity_handlers::multiple_fish_do_turn (player_activity *act, Character *you)
void activity_handlers::multiple_read_do_turn (player_activity *act, Character *you)
void activity_handlers::multiple_mine_do_turn (player_activity *act, Character *you)
void activity_handlers::multiple_mop_do_turn (player_activity *act, Character *you)
void activity_handlers::operation_do_turn (player_activity *act, Character *you)
void activity_handlers::pickaxe_do_turn (player_activity *act, Character *you)
void activity_handlers::pulp_do_turn (player_activity *act, Character *you)
void activity_handlers::repair_item_do_turn (player_activity *act, Character *you)
void activity_handlers::robot_control_do_turn (player_activity *act, Character *you)
void activity_handlers::start_fire_do_turn (player_activity *act, Character *you)
void activity_handlers::study_spell_do_turn (player_activity *act, Character *you)
void activity_handlers::tidy_up_do_turn (player_activity *act, Character *you)
void activity_handlers::travel_do_turn (player_activity *act, Character *you)
void activity_handlers::tree_communion_do_turn (player_activity *act, Character *you)
void activity_handlers::vehicle_deconstruction_do_turn (player_activity *act, Character *you)
void activity_handlers::vehicle_repair_do_turn (player_activity *act, Character *you)
void activity_handlers::vibe_do_turn (player_activity *act, Character *you)
void activity_handlers::view_recipe_do_turn (player_activity *act, Character *you)
void activity_handlers::wait_stamina_do_turn (player_activity *act, Character *you)
void activity_handlers::atm_finish (player_activity *act, Character *you)
activity_finish functions:
void activity_handlers::butcher_finish (player_activity *act, Character *you)
void activity_handlers::eat_menu_finish (player_activity *act, Character *you)
void activity_handlers::fish_finish (player_activity *act, Character *you)
void activity_handlers::generic_game_finish (player_activity *act, Character *you)
void activity_handlers::gunmod_add_finish (player_activity *act, Character *you)
void activity_handlers::heat_item_finish (player_activity *act, Character *you)
void activity_handlers::jackhammer_finish (player_activity *act, Character *you)
void activity_handlers::mend_item_finish (player_activity *act, Character *you)
void activity_handlers::operation_finish (player_activity *act, Character *you)
void activity_handlers::pickaxe_finish (player_activity *act, Character *you)
void activity_handlers::plant_seed_finish (player_activity *act, Character *you)
void activity_handlers::pull_creature_finish (player_activity *act, Character *you)
void activity_handlers::pulp_finish (player_activity *act, Character *you)
void activity_handlers::repair_item_finish (player_activity *act, Character *you)
void activity_handlers::robot_control_finish (player_activity *act, Character *you)
void activity_handlers::socialize_finish (player_activity *act, Character *you)
void activity_handlers::spellcasting_finish (player_activity *act, Character *you)
void activity_handlers::start_engines_finish (player_activity *act, Character *you)
void activity_handlers::start_fire_finish (player_activity *act, Character *you)
void activity_handlers::study_spell_finish (player_activity *act, Character *you)
void activity_handlers::teach_finish (player_activity *act, Character *you)
void activity_handlers::toolmod_add_finish (player_activity *act, Character *you)
void activity_handlers::train_finish (player_activity *act, Character *you)
void activity_handlers::vehicle_finish (player_activity *act, Character *you)
void activity_handlers::vibe_finish (player_activity *act, Character *you)
void activity_handlers::view_recipe_finish (player_activity *act, Character *you)
void activity_handlers::wait_finish (player_activity *act, Character *you)
void activity_handlers::wait_npc_finish (player_activity *act, Character *you)
void activity_handlers::wait_stamina_finish (player_activity *act, Character *you)
void activity_handlers::wait_weather_finish (player_activity *act, Character *you)
int activity_handlers::move_cost (const item &it, const tripoint_bub_ms &src, const tripoint_bub_ms &dest)
int activity_handlers::move_cost_cart (const item &it, const tripoint_bub_ms &src, const tripoint_bub_ms &dest, const units::volume &capacity)
int activity_handlers::move_cost_inv (const item &it, const tripoint_bub_ms &src, const tripoint_bub_ms &dest)
Variables
const std::vector< std::string > do_activity_reason_string
const std::map< activity_id, std::function< void(player_activity *, Character *)> > activity_handlers::do_turn_functions
const std::map< activity_id, std::function< void(player_activity *, Character *)> > activity_handlers::finish_functions
Macro Definition Documentation
CATA_SRC_ACTIVITY_HANDLERS_H
#define CATA_SRC_ACTIVITY_HANDLERS_H
Definition at line 3 of file activity_handlers.h.
Enumeration Type Documentation
butcher_type
enum butcher_type : int strong
Enumerator
BLEED
QUICK
FULL
FIELD_DRESS
SKIN
QUARTER
DISMEMBER
DISSECT
NUM_TYPES
Definition at line 48 of file activity_handlers.h.
                         : int {
     BLEED,          // bleeding a corpse
     QUICK,          // quick butchery
     FULL,           // full workshop butchery
     FIELD_DRESS,    // field dressing a corpse
     SKIN,           // skinning a corpse
     QUARTER,        // quarter a corpse
     DISMEMBER,      // destroy a corpse
     DISSECT,        // dissect a corpse for CBMs
     NUM_TYPES       // always keep at the end, number of butchery types
 };
do_activity_reason
enum do_activity_reason : int strong
Enumerator
CAN_DO_CONSTRUCTION
CAN_DO_FETCH
NO_COMPONENTS
DONT_HAVE_SKILL
NO_ZONE
ALREADY_DONE
UNKNOWN_ACTIVITY
NEEDS_CLEARING
NEEDS_HARVESTING
NEEDS_PLANTING
NEEDS_TILLING
BLOCKING_TILE
NEEDS_BOOK_TO_LEARN
NEEDS_CHOPPING
NEEDS_TREE_CHOPPING
NEEDS_BIG_BUTCHERING
NEEDS_BUTCHERING
NEEDS_CUT_HARVESTING
ALREADY_WORKING
NEEDS_VEH_DECONST
NEEDS_VEH_REPAIR
WOULD_PREVENT_VEH_FLYING
NEEDS_MINING
NEEDS_MOP
NEEDS_FISHING
NEEDS_CRAFT
NEEDS_DISASSEMBLE
Definition at line 60 of file activity_handlers.h.
                               : int {
     CAN_DO_CONSTRUCTION,    // Can do construction.
     CAN_DO_FETCH,           // Can do fetch - this is usually the default result for fetch task
     NO_COMPONENTS,          // can't do the activity there due to lack of components /tools
     DONT_HAVE_SKILL,        // don't have the required skill
     NO_ZONE,                // There is no required zone anymore
     ALREADY_DONE,           // the activity is done already ( maybe by someone else )
     UNKNOWN_ACTIVITY,       // This is probably an error - got to the end of function with no previous reason
     NEEDS_CLEARING,         // For farming - tile was neglected and became overgrown, can be cleared.
     NEEDS_HARVESTING,       // For farming - tile is harvestable now.
     NEEDS_PLANTING,         // For farming - tile can be planted
     NEEDS_TILLING,          // For farming - tile can be tilled
     BLOCKING_TILE,           // Something has made it's way onto the tile, so the activity cannot proceed
     NEEDS_BOOK_TO_LEARN,    // There is book to learn
     NEEDS_CHOPPING,         // There is wood there to be chopped
     NEEDS_TREE_CHOPPING,    // There is a tree there that needs to be chopped
     NEEDS_BIG_BUTCHERING,   // There is at least one corpse there to butcher, and it's a big one
     NEEDS_BUTCHERING,       // THere is at least one corpse there to butcher, and there's no need for additional tools
     NEEDS_CUT_HARVESTING,   // There is a plant there which needs a grass-cutting tool to harvest
     ALREADY_WORKING,        // somebody is already working there
     NEEDS_VEH_DECONST,       // There is a vehicle part there that we can deconstruct, given the right tools.
     NEEDS_VEH_REPAIR,       // There is a vehicle part there that can be repaired, given the right tools.
     WOULD_PREVENT_VEH_FLYING, // Attempting to perform this activity on a vehicle would prevent it from flying
     NEEDS_MINING,           // This spot can be mined, if the right tool is present.
     NEEDS_MOP,               // This spot can be mopped, if a mop is present.
     NEEDS_FISHING,           // This spot can be fished, if the right tool is present.
     NEEDS_CRAFT,             // There is at least one item to craft.
     NEEDS_DISASSEMBLE        // There is at least one item to disassemble.
 };
item_drop_reason
enum item_drop_reason : int strong
Enumerator
deliberate
too_large
too_heavy
tumbling
Definition at line 170 of file activity_handlers.h.
                             : int {
     deliberate,
     too_large,
     too_heavy,
     tumbling
 };
requirement_check_result
enum requirement_check_result : int strong
Enumerator
SKIP_LOCATION
CAN_DO_LOCATION
RETURN_EARLY
Definition at line 42 of file activity_handlers.h.
                                     : int {
     SKIP_LOCATION = 0,
     CAN_DO_LOCATION,
     RETURN_EARLY       //another activity like a fetch activity has been started.
 };
Function Documentation
activity_on_turn_drop()
void activity_on_turn_drop ()
activity_on_turn_fetch()
void activity_on_turn_fetch (player_activity & , Character * you)
activity_on_turn_move_loot()
void activity_on_turn_move_loot (player_activity & act, Character & you)
Definition at line 1991 of file activity_item_handling.cpp.
 {
     enum activity_stage : int {
         //Initial stage
         INIT = 0,
         //Think about what to do first: choose destination
         THINK,
         //Do activity
         DO,
     };
     int &stage = act.index;
     //Prepare activity stage
     if( stage < 0 ) {
         stage = INIT;
         //num_processed
         act.values.push_back( 0 );
     }
     int &num_processed = act.values[ 0 ];
     map &here = get_map();
     const tripoint_abs_ms abspos = you.get_location();
     zone_manager &mgr = zone_manager::get_manager();
     if( here.check_vehicle_zones( here.get_abs_sub().z() ) ) {
         mgr.cache_vzones();
     }
     if( stage == INIT ) {
         // TODO: fix point types
         act.coord_set.clear();
         for( const tripoint_abs_ms &p :
              mgr.get_near( zone_type_LOOT_UNSORTED, abspos, ACTIVITY_SEARCH_DISTANCE, nullptr,
                            _fac_id( you ) ) ) {
             act.coord_set.insert( p.raw() );
         }
         stage = THINK;
     }
     if( stage == THINK ) {
         //initialize num_processed
         num_processed = 0;
         // TODO: fix point types
         std::vector<tripoint_abs_ms> src_set;
         src_set.reserve( act.coord_set.size() );
         for( const tripoint &p : act.coord_set ) {
             src_set.emplace_back( p );
         }
         // sort source tiles by distance
         const auto &src_sorted = get_sorted_tiles_by_distance( abspos, src_set );
         for( const tripoint_abs_ms &src : src_sorted ) {
             act.placement = src;
             // TODO: fix point types
             act.coord_set.erase( src.raw() );
             const tripoint_bub_ms src_loc = here.bub_from_abs( src );
             if( !here.inbounds( src_loc ) ) {
                 if( !here.inbounds( you.pos() ) ) {
                     // p is implicitly an NPC that has been moved off the map, so reset the activity
                     // and unload them
                     you.cancel_activity();
                     you.assign_activity( ACT_MOVE_LOOT );
                     you.set_moves( 0 );
                     g->reload_npcs();
                     return;
                 }
                 std::vector<tripoint_bub_ms> route;
                 route = here.route( you.pos_bub(), src_loc, you.get_pathfinding_settings(),
                                     you.get_path_avoid() );
                 if( route.empty() ) {
                     // can't get there, can't do anything, skip it
                     continue;
                 }
                 stage = DO;
                 you.set_destination( route, act );
                 you.activity.set_to_null();
                 return;
             }
             std::vector<zone_data const *> zones;
             bool ignore_contents = false;
             // check ignorable zones for ignore_contents enabled
             for( const auto &zone_type : ignorable_zone_types ) {
                 // add zones using mgr.get_zones_at
                 for( zone_data const *zone : mgr.get_zones_at( src, zone_type, _fac_id( you ) ) ) {
                     ignorable_options const &options = dynamic_cast<const ignorable_options &>( zone->get_options() );
                     if( options.get_ignore_contents() ) {
                         ignore_contents = true;
                         break;
                     }
                 }
                 if( ignore_contents ) {
                     break;
                 }
             }
             // skip tiles in IGNORE zone or with ignore option,
             // tiles on fire (to prevent taking out wood off the lit brazier)
             // and inaccessible furniture, like filled charcoal kiln
             if( mgr.has( zone_type_LOOT_IGNORE, src, _fac_id( you ) ) ||
                 ignore_contents ||
                 here.get_field( src_loc, fd_fire ) != nullptr ||
                 !here.can_put_items_ter_furn( src_loc ) ) {
                 continue;
             }
             //nothing to sort?
             const std::optional<vpart_reference> vp = here.veh_at( src_loc ).cargo();
             if( ( !vp || vp->items().empty() ) && here.i_at( src_loc ).empty() ) {
                 continue;
             }
             bool is_adjacent_or_closer = square_dist( you.pos_bub(), src_loc ) <= 1;
             // before we move any item, check if player is at or
             // adjacent to the loot source tile
             if( !is_adjacent_or_closer ) {
                 std::vector<tripoint_bub_ms> route;
                 bool adjacent = false;
                 // get either direct route or route to nearest adjacent tile if
                 // source tile is impassable
                 if( here.passable( src_loc ) ) {
                     route = here.route( you.pos_bub(), src_loc, you.get_pathfinding_settings(),
                                         you.get_path_avoid() );
                 } else {
                     // impassable source tile (locker etc.),
                     // get route to nearest adjacent tile instead
                     route = route_adjacent( you, src_loc );
                     adjacent = true;
                 }
                 // check if we found path to source / adjacent tile
                 if( route.empty() ) {
                     add_msg( m_info, _( "%s can't reach the source tile.  Try to sort out loot without a cart." ),
                              you.disp_name() );
                     continue;
                 }
                 // shorten the route to adjacent tile, if necessary
                 if( !adjacent ) {
                     route.pop_back();
                 }
                 // set the destination and restart activity after player arrives there
                 // we don't need to check for safe mode,
                 // activity will be restarted only if
                 // player arrives on destination tile
                 stage = DO;
                 you.set_destination( route, act );
                 you.activity.set_to_null();
                 return;
             }
             stage = DO;
             break;
         }
     }
     if( stage == DO ) {
         // TODO: fix point types
         const tripoint_abs_ms src( act.placement );
         const tripoint_bub_ms src_loc = here.bub_from_abs( src );
         bool is_adjacent_or_closer = square_dist( you.pos_bub(), src_loc ) <= 1;
         // before we move any item, check if player is at or
         // adjacent to the loot source tile
         if( !is_adjacent_or_closer ) {
             stage = THINK;
             return;
         }
         // the boolean in this pair being true indicates the item is from a vehicle storage space
         auto items = std::vector<std::pair<item *, bool>>();
         const std::optional<vpart_reference> vpr = here.veh_at( src_loc ).cargo();
         //Check source for cargo part
         //map_stack and vehicle_stack are different types but inherit from item_stack
         // TODO: use one for loop
         if( vpr ) {
             for( item &it : vpr->items() ) {
                 items.emplace_back( &it, true );
             }
         }
         for( item &it : here.i_at( src_loc ) ) {
             items.emplace_back( &it, false );
         }
         bool unload_mods = false;
         bool unload_molle = false;
         bool unload_sparse_only = false;
         int unload_sparse_threshold = 20;
         bool unload_always = false;
         std::vector<zone_data const *> const zones = mgr.get_zones_at( src, zone_type_UNLOAD_ALL,
                 _fac_id( you ) );
         // get most open rules out of all stacked zones
         for( zone_data const *zone : zones ) {
             unload_options const &options = dynamic_cast<const unload_options &>( zone->get_options() );
             unload_molle |= options.unload_molle();
             unload_mods |= options.unload_mods();
             unload_sparse_only |= options.unload_sparse_only();
             unload_sparse_threshold |= options.unload_sparse_threshold();
             unload_always |= options.unload_always();
         }
         //Skip items that have already been processed
         for( auto it = items.begin() + num_processed; it < items.end(); ++it ) {
             ++num_processed;
             item &thisitem = *it->first;
             // skip items not owned by you
             if( !thisitem.is_owned_by( you, true ) ) {
                 continue;
             }
             // skip unpickable liquid
             if( !thisitem.made_of_from_type( phase_id::SOLID ) ) {
                 continue;
             }
             // skip favorite items in ignore favorite zones
             if( thisitem.is_favorite && mgr.has( zone_type_LOOT_IGNORE_FAVORITES, src, _fac_id( you ) ) ) {
                 continue;
             }
             // Only if it's from a vehicle do we use the vehicle source location information.
             const std::optional<vpart_reference> vpr_src = it->second ? vpr : std::nullopt;
             const zone_type_id id = mgr.get_near_zone_type_for_item( thisitem, abspos,
                                     ACTIVITY_SEARCH_DISTANCE, _fac_id( you ) );
             // checks whether the item is already on correct loot zone or not
             // if it is, we can skip such item, if not we move the item to correct pile
             // think empty bag on food pile, after you ate the content
             if( id != zone_type_LOOT_CUSTOM && mgr.has( id, src, _fac_id( you ) ) ) {
                 continue;
             }
             if( id == zone_type_LOOT_CUSTOM &&
                 mgr.custom_loot_has( src, &thisitem, zone_type_LOOT_CUSTOM, _fac_id( you ) ) ) {
                 continue;
             }
             const std::unordered_set<tripoint_abs_ms> dest_set =
                 mgr.get_near( id, abspos, ACTIVITY_SEARCH_DISTANCE, &thisitem, _fac_id( you ) );
             // if this item isn't going anywhere and its not sealed
             // check if it is in a unload zone or a strip corpse zone
             // then we should unload it and see what is inside
             bool move_and_reset = false;
             bool moved_something = false;
             if( mgr.has_near( zone_type_UNLOAD_ALL, abspos, 1, _fac_id( you ) ) ||
                 ( mgr.has_near( zone_type_STRIP_CORPSES, abspos, 1, _fac_id( you ) ) && it->first->is_corpse() ) ) {
                 if( dest_set.empty() || unload_always ) {
                     if( you.rate_action_unload( *it->first ) == hint_rating::good &&
                         !it->first->any_pockets_sealed() ) {
                         std::unordered_map<itype_id, int> item_counts;
                         if( unload_sparse_only ) {
                             for( item *contained : it->first->all_items_top( pocket_type::CONTAINER ) ) {
                                 if( !contained->made_of( phase_id::LIQUID ) && !contained->made_of( phase_id::GAS ) ) {
                                     item_counts[contained->typeId()]++;
                                 }
                             }
                         }
                         for( item *contained : it->first->all_items_top( pocket_type::CONTAINER ) ) {
                             // no liquids don't want to spill stuff
                             if( !contained->made_of( phase_id::LIQUID ) && !contained->made_of( phase_id::GAS ) ) {
                                 if( unload_sparse_only &&
                                     item_counts[contained->typeId()] > unload_sparse_threshold ) {
                                     continue;
                                 }
                                 move_item( you, *contained, contained->count(), src_loc, src_loc, vpr_src );
                                 it->first->remove_item( *contained );
                             }
                         }
                         for( item *contained : it->first->all_items_top( pocket_type::MAGAZINE ) ) {
                             // no liquids don't want to spill stuff
                             if( !contained->made_of( phase_id::LIQUID ) && !contained->made_of( phase_id::GAS ) ) {
                                 if( it->first->is_ammo_belt() ) {
                                     if( it->first->type->magazine->linkage ) {
                                         item link( *it->first->type->magazine->linkage, calendar::turn, contained->count() );
                                         if( vpr_src ) {
                                             vpr_src->vehicle().add_item( vpr_src->part(), link );
                                         } else {
                                             here.add_item_or_charges( src_loc, link );
                                         }
                                     }
                                 }
                                 move_item( you, *contained, contained->count(), src_loc, src_loc, vpr_src );
                                 it->first->remove_item( *contained );
                             }
                         }
                         for( item *contained : it->first->all_items_top( pocket_type::MAGAZINE_WELL ) ) {
                             // no liquids don't want to spill stuff
                             if( !contained->made_of( phase_id::LIQUID ) && !contained->made_of( phase_id::GAS ) ) {
                                 move_item( you, *contained, contained->count(), src_loc, src_loc, vpr_src );
                                 it->first->remove_item( *contained );
                             }
                         }
                         moved_something = true;
                     }
                     // if unloading mods
                     if( unload_mods ) {
                         // remove each mod, skip irremovable
                         for( item *mod : it->first->gunmods() ) {
                             if( mod->is_irremovable() ) {
                                 continue;
                             }
                             you.gunmod_remove( *it->first, *mod );
                             // need to return so the activity starts
                             return;
                         }
                     }
                     // if unloading molle
                     if( unload_molle ) {
                         while( !it->first->get_contents().get_added_pockets().empty() ) {
                             item removed = it->first->get_contents().remove_pocket( 0 );
                             move_item( you, removed, 1, src_loc, src_loc, vpr_src );
                             moved_something = true;
                         }
                     }
                     if( it->first->has_flag( flag_MAG_DESTROY ) && it->first->ammo_remaining() == 0 ) {
                         if( vpr_src ) {
                             vpr_src->vehicle().remove_item( vpr_src->part(), it->first );
                         } else {
                             here.i_rem( src_loc, it->first );
                         }
                         num_processed = std::max( num_processed - 1, 0 );
                         return;
                     }
                     // after dumping items go back to start of activity loop
                     // so that can re-assess the items in the tile
                     // perhaps move the last item first however
                     if( unload_always && moved_something ) {
                         move_and_reset = true;
                     } else if( moved_something ) {
                         return;
                     }
                 }
             }
             for( const tripoint_abs_ms &dest : dest_set ) {
                 const tripoint_bub_ms dest_loc = here.bub_from_abs( dest );
                 units::volume free_space;
                 //Check destination for cargo part
                 if( const std::optional<vpart_reference> ovp = here.veh_at( dest_loc ).cargo() ) {
                     free_space = ovp->items().free_volume();
                 } else {
                     free_space = here.free_volume( dest_loc );
                 }
                 // skip tiles with inaccessible furniture, like filled charcoal kiln
                 if( !here.can_put_items_ter_furn( dest_loc ) ||
                     static_cast<int>( here.i_at( dest_loc ).size() ) >= MAX_ITEM_IN_SQUARE ) {
                     continue;
                 }
                 // check free space at destination
                 if( free_space >= thisitem.volume() ) {
                     move_item( you, thisitem, thisitem.count(), src_loc, dest_loc, vpr_src );
                     // moved item away from source so decrement
                     if( num_processed > 0 ) {
                         --num_processed;
                     }
                     break;
                 }
             }
             if( you.get_moves() <= 0 || move_and_reset ) {
                 return;
             }
         }
         //this location is sorted
         stage = THINK;
         return;
     }
     // If we got here without restarting the activity, it means we're done
     add_msg( m_info, _( "%s sorted out every item possible." ), you.disp_name( false, true ) );
     if( you.is_npc() ) {
         npc *guy = dynamic_cast<npc *>( &you );
         guy->revert_after_activity();
     }
     you.activity.set_to_null();
 }
References _, anonymous_namespace{activity_item_handling.cpp}::_fac_id(), act, ACT_MOVE_LOOT, Character::activity, ACTIVITY_SEARCH_DISTANCE, map::add_item_or_charges(), add_msg(), item::all_items_top(), item::ammo_remaining(), item::any_pockets_sealed(), Character::assign_activity(), map::bub_from_abs(), zone_manager::cache_vzones(), map::can_put_items_ter_furn(), Character::cancel_activity(), optional_vpart_position::cargo(), map::check_vehicle_zones(), CONTAINER, item::count(), zone_manager::custom_loot_has(), Character::disp_name(), item_stack::empty(), fd_fire, flag_MAG_DESTROY, map::free_volume(), g, GAS, map::get_abs_sub(), item_contents::get_added_pockets(), item::get_contents(), map::get_field(), Creature::get_location(), zone_manager::get_manager(), get_map(), Creature::get_moves(), zone_manager::get_near(), zone_manager::get_near_zone_type_for_item(), Character::get_path_avoid(), Character::get_pathfinding_settings(), get_sorted_tiles_by_distance(), zone_manager::get_zones_at(), good, Character::gunmod_remove(), item::gunmods(), zone_manager::has(), item::has_flag(), zone_manager::has_near(), map::i_at(), map::i_rem(), ignorable_zone_types, map::inbounds(), INIT, item::is_ammo_belt(), item::is_corpse(), item::is_favorite, Character::is_npc(), item::is_owned_by(), LIQUID, m_info, item::made_of_from_type(), itype::magazine, MAGAZINE, MAGAZINE_WELL, max(), MAX_ITEM_IN_SQUARE, move_item(), PATH_INFO::options(), map::passable(), Creature::pos(), Creature::pos_bub(), Character::rate_action_unload(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), visitable::remove_item(), item_contents::remove_pocket(), npc::revert_after_activity(), map::route(), route_adjacent(), Character::set_destination(), Creature::set_moves(), player_activity::set_to_null(), item_stack::size(), SOLID, square_dist(), calendar::turn, item::type, map::veh_at(), item::volume(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), zone_type_LOOT_CUSTOM, zone_type_LOOT_IGNORE, zone_type_LOOT_IGNORE_FAVORITES, zone_type_LOOT_UNSORTED, zone_type_STRIP_CORPSES, zone_type_UNLOAD_ALL, and zones.
Referenced by activity_handlers::move_loot_do_turn().
butcher_time_to_cut()
int butcher_time_to_cut (Character & you, const item & corpse_item, butcher_type action)
Definition at line 676 of file activity_handlers.cpp.
 {
     const mtype &corpse = *corpse_item.get_mtype();
     const int factor = you.max_quality( action == butcher_type::DISSECT ? qual_CUT_FINE : qual_BUTCHER,
                                         PICKUP_RANGE );
     int time_to_cut;
     switch( corpse.size ) {
         // Time (roughly) in turns to cut up the corpse
         case creature_size::tiny:
             time_to_cut = 150;
             break;
         case creature_size::small:
             time_to_cut = 300;
             break;
         case creature_size::medium:
             time_to_cut = 450;
             break;
         case creature_size::large:
             time_to_cut = 600;
             break;
         case creature_size::huge:
             time_to_cut = 1800;
             break;
         default:
             debugmsg( "ERROR: Invalid creature_size on %s", corpse.nname() );
             time_to_cut = 450; // default to medium
             break;
     }
     // At factor 0, base 100 time_to_cut remains 100. At factor 50, it's 50 , at factor 75 it's 25
     time_to_cut *= std::max( 25, 100 - factor );
     switch( action ) {
         case butcher_type::QUICK:
         case butcher_type::BLEED:
             break;
         case butcher_type::FULL:
             if( !corpse_item.has_flag( flag_FIELD_DRESS ) || corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) {
                 time_to_cut *= 6;
             } else {
                 time_to_cut *= 4;
             }
             break;
         case butcher_type::FIELD_DRESS:
         case butcher_type::SKIN:
             time_to_cut *= 2;
             break;
         case butcher_type::QUARTER:
             time_to_cut /= 4;
             if( time_to_cut < 1200 ) {
                 time_to_cut = 1200;
             }
             break;
         case butcher_type::DISMEMBER:
             time_to_cut /= 10;
             if( time_to_cut < 600 ) {
                 time_to_cut = 600;
             }
             break;
         case butcher_type::DISSECT:
             time_to_cut *= 6;
             break;
         case butcher_type::NUM_TYPES:
             debugmsg( "ERROR: Invalid butcher_type" );
             break;
     }
     if( corpse_item.has_flag( flag_QUARTERED ) ) {
         time_to_cut /= 4;
     }
     time_to_cut *= ( 1.0f - ( get_player_character().get_num_crafting_helpers( 3 ) / 10.0f ) );
     return time_to_cut;
 }
References action, BLEED, corpse, debugmsg, DISMEMBER, DISSECT, FIELD_DRESS, flag_FIELD_DRESS, flag_FIELD_DRESS_FAILED, flag_QUARTERED, FULL, item::get_mtype(), Character::get_num_crafting_helpers(), get_player_character(), item::has_flag(), huge, large, max(), Character::max_quality(), medium, NUM_TYPES, PICKUP_RANGE, qual_BUTCHER, qual_CUT_FINE, QUARTER, QUICK, SKIN, small, and tiny.
Referenced by butcher_submenu(), and set_up_butchery().
drop_on_map()
std::vector<item_location> drop_on_map (Character & you, item_drop_reason reason, const std::list< item > & items, const tripoint_bub_ms & where)
Definition at line 339 of file activity_item_handling.cpp.
 {
     if( items.empty() ) {
         return {};
     }
     map &here = get_map();
     const std::string ter_name = here.name( where );
     const bool can_move_there = here.passable( where );
     if( same_type( items ) ) {
         const item &it = items.front();
         const int dropcount = items.size() * it.count();
         const std::string it_name = it.tname( dropcount );
         switch( reason ) {
             case item_drop_reason::deliberate:
                 if( can_move_there ) {
                     you.add_msg_player_or_npc(
                         n_gettext( "You drop your %1$s on the %2$s.",
                                    "You drop your %1$s on the %2$s.", dropcount ),
                         n_gettext( "<npcname> drops their %1$s on the %2$s.",
                                    "<npcname> drops their %1$s on the %2$s.", dropcount ),
                         it_name, ter_name
                     );
                 } else {
                     you.add_msg_player_or_npc(
                         n_gettext( "You put your %1$s in the %2$s.",
                                    "You put your %1$s in the %2$s.", dropcount ),
                         n_gettext( "<npcname> puts their %1$s in the %2$s.",
                                    "<npcname> puts their %1$s in the %2$s.", dropcount ),
                         it_name, ter_name
                     );
                 }
                 break;
             case item_drop_reason::too_large:
                 you.add_msg_if_player(
                     n_gettext( "There's no room in your inventory for the %s, so you drop it.",
                                "There's no room in your inventory for the %s, so you drop them.", dropcount ),
                     it_name
                 );
                 break;
             case item_drop_reason::too_heavy:
                 you.add_msg_if_player(
                     n_gettext( "The %s is too heavy to carry, so you drop it.",
                                "The %s is too heavy to carry, so you drop them.", dropcount ),
                     it_name
                 );
                 break;
             case item_drop_reason::tumbling:
                 you.add_msg_if_player(
                     m_bad,
                     n_gettext( "Your %1$s tumbles to the %2$s.",
                                "Your %1$s tumble to the %2$s.", dropcount ),
                     it_name, ter_name
                 );
                 break;
         }
         if( get_option<bool>( "AUTO_NOTES_DROPPED_FAVORITES" ) && it.is_favorite ) {
             const tripoint_abs_omt your_pos = you.global_omt_location();
             if( !overmap_buffer.has_note( your_pos ) ) {
                 overmap_buffer.add_note( your_pos, it.display_name() );
             } else {
                 overmap_buffer.add_note( your_pos, overmap_buffer.note( your_pos ) + "; " + it.display_name() );
             }
         }
     } else {
         switch( reason ) {
             case item_drop_reason::deliberate:
                 if( can_move_there ) {
                     you.add_msg_player_or_npc(
                         _( "You drop several items on the %s." ),
                         _( "<npcname> drops several items on the %s." ),
                         ter_name
                     );
                 } else {
                     you.add_msg_player_or_npc(
                         _( "You put several items in the %s." ),
                         _( "<npcname> puts several items in the %s." ),
                         ter_name
                     );
                 }
                 break;
             case item_drop_reason::too_large:
             case item_drop_reason::too_heavy:
             case item_drop_reason::tumbling:
                 you.add_msg_if_player( m_bad, _( "Some items tumble to the %s." ), ter_name );
                 break;
         }
     }
     std::vector<item_location> items_dropped;
     for( const item &it : items ) {
         item &dropped_item = here.add_item_or_charges( where, it );
         items_dropped.emplace_back( map_cursor( where.raw() ), &dropped_item );
         item( it ).handle_pickup_ownership( you );
     }
     you.recoil = MAX_RECOIL;
     return items_dropped;
 }
References _, map::add_item_or_charges(), Character::add_msg_if_player(), Character::add_msg_player_or_npc(), overmapbuffer::add_note(), item::count(), deliberate, item::display_name(), get_map(), Creature::global_omt_location(), item::handle_pickup_ownership(), overmapbuffer::has_note(), item::is_favorite, m_bad, MAX_RECOIL, n_gettext, map::name(), overmapbuffer::note(), overmap_buffer, map::passable(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), Character::recoil, same_type(), item::tname(), too_heavy, too_large, and tumbling.
Referenced by butchery_drops_harvest(), move_items_activity_actor::do_turn(), talk_function::player_weapon_drop(), and put_into_vehicle_or_drop().
generic_multi_activity_handler()
bool generic_multi_activity_handler (player_activity & act, Character & you, bool check_only = false)
Definition at line 3153 of file activity_item_handling.cpp.
 {
     map &here = get_map();
     const tripoint_abs_ms abspos = here.getglobal( you.pos() );
     // NOLINTNEXTLINE(performance-unnecessary-copy-initialization)
     activity_id activity_to_restore = act.id();
     // Nuke the current activity, leaving the backlog alone
     if( !check_only ) {
         you.activity = player_activity();
     }
     // now we setup the target spots based on which activity is occurring
     // the set of target work spots - potentially after we have fetched required tools.
     std::unordered_set<tripoint_abs_ms> src_set =
         generic_multi_activity_locations( you, activity_to_restore );
     // now we have our final set of points
     std::vector<tripoint_abs_ms> src_sorted = get_sorted_tiles_by_distance( abspos, src_set );
     // now loop through the work-spot tiles and judge whether its worth traveling to it yet
     // or if we need to fetch something first.
     // check: if a fetch act was assigned but no need to do that anymore, restore our task
     // may cause infinite loop if something goes wrong
     // Maybe it makes more harm than good? I don't know.
     if( activity_to_restore == activity_id( ACT_FETCH_REQUIRED ) && src_sorted.empty() ) {
         // remind what you failed to fetch
         if( !check_only && !you.backlog.empty() ) {
             player_activity &act_prev = you.backlog.front();
             if( !act_prev.str_values.empty() && you.as_npc() ) {
                 you.as_npc()->job.fetch_history[act_prev.str_values.back()] = calendar::turn;
             }
         }
         return true;
     }
     for( const tripoint_abs_ms &src : src_sorted ) {
         const tripoint_bub_ms &src_loc = here.bub_from_abs( src );
         if( !here.inbounds( src_loc ) && !check_only ) {
             if( !here.inbounds( you.pos() ) ) {
                 // p is implicitly an NPC that has been moved off the map, so reset the activity
                 // and unload them
                 you.assign_activity( activity_to_restore );
                 you.set_moves( 0 );
                 g->reload_npcs();
                 return false;
             }
             const std::vector<tripoint_bub_ms> route = route_adjacent( you, src_loc );
             if( route.empty() ) {
                 // can't get there, can't do anything, skip it
                 continue;
             }
             you.set_moves( 0 );
             you.set_destination( route, player_activity( activity_to_restore ) );
             return false;
         }
         activity_reason_info act_info = can_do_activity_there( activity_to_restore, you,
                                         src_loc, ACTIVITY_SEARCH_DISTANCE );
         // see activity_handlers.h enum for requirement_check_result
         const requirement_check_result req_res = generic_multi_activity_check_requirement(
                     you, activity_to_restore, act_info, src, src_loc, src_set, check_only );
         if( req_res == requirement_check_result::SKIP_LOCATION ) {
             continue;
         } else if( req_res == requirement_check_result::RETURN_EARLY ) {
             return true;
         }
         std::vector<tripoint_bub_ms> route_workbench;
         if( activity_to_restore == ACT_MULTIPLE_CRAFT || activity_to_restore == ACT_MULTIPLE_DIS ) {
             // returns empty vector if we can't reach best tile
             // or we are already on the best tile
             route_workbench = route_best_workbench( you, src_loc );
         }
         // If we are doing disassemble we need to stand on the "best" tile
         if( square_dist( you.pos_bub(), src_loc ) > 1 || !route_workbench.empty() ) {
             std::vector<tripoint_bub_ms> route;
             // find best workbench if possible
             if( !route_workbench.empty() ) {
                 route = route_workbench;
             } else {
                 route = route_adjacent( you, src_loc );
             }
             // check if we found path to source / adjacent tile
             if( route.empty() ) {
                 check_npc_revert( you );
                 continue;
             }
             if( !check_only ) {
                 if( you.get_moves() <= 0 ) {
                     // Restart activity and break from cycle.
                     you.assign_activity( activity_to_restore );
                     return true;
                 }
                 // set the destination and restart activity after player arrives there
                 // we don't need to check for safe mode,
                 // activity will be restarted only if
                 // player arrives on destination tile
                 you.set_destination( route, player_activity( activity_to_restore ) );
                 return true;
             }
         }
         // we checked if the work spot was in darkness earlier
         // but there is a niche case where the player is in darkness but the work spot is not
         // this can create infinite loops
         // and we can't check player.pos() for darkness before they've traveled to where they are going to be.
         // but now we are here, we check
         if( activity_to_restore != ACT_TIDY_UP &&
             activity_to_restore != ACT_MULTIPLE_MOP &&
             activity_to_restore != ACT_MOVE_LOOT &&
             activity_to_restore != ACT_FETCH_REQUIRED &&
             you.fine_detail_vision_mod( you.pos() ) > 4.0 ) {
             you.add_msg_if_player( m_info, _( "It is too dark to work here." ) );
             return false;
         }
         if( !check_only ) {
             if( !generic_multi_activity_do( you, activity_to_restore, act_info, src, src_loc ) ) {
                 // if the activity was successful
                 // then a new activity was assigned
                 // and the backlog was given the multi-act
                 return false;
             }
         } else {
             return true;
         }
     }
     if( !check_only ) {
         if( you.get_moves() <= 0 ) {
             // Restart activity and break from cycle.
             you.assign_activity( activity_to_restore );
             you.activity_vehicle_part_index = -1;
             return false;
         }
         // if we got here, we need to revert otherwise NPC will be stuck in AI Limbo and have a head explosion.
         if( you.backlog.empty() || src_set.empty() ) {
             check_npc_revert( you );
             if( player_activity( activity_to_restore ).is_multi_type() ) {
                 you.assign_activity( activity_id::NULL_ID() );
             }
         }
         you.activity_vehicle_part_index = -1;
     }
     // scanned every location, tried every path.
     return false;
 }
References _, act, ACT_FETCH_REQUIRED, ACT_MOVE_LOOT, ACT_MULTIPLE_CRAFT, ACT_MULTIPLE_DIS, ACT_MULTIPLE_MOP, ACT_TIDY_UP, Character::activity, ACTIVITY_SEARCH_DISTANCE, Character::activity_vehicle_part_index, Character::add_msg_if_player(), Creature::as_npc(), Character::assign_activity(), Character::backlog, map::bub_from_abs(), can_do_activity_there(), check_npc_revert(), job_data::fetch_history, Character::fine_detail_vision_mod(), g, generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_locations(), get_map(), Creature::get_moves(), get_sorted_tiles_by_distance(), map::getglobal(), string_id< T >::id(), map::inbounds(), npc::job, m_info, string_id< activity_type >::NULL_ID(), Creature::pos(), Creature::pos_bub(), RETURN_EARLY, route_adjacent(), route_best_workbench(), Character::set_destination(), Creature::set_moves(), SKIP_LOCATION, square_dist(), player_activity::str_values, and calendar::turn.
Referenced by activity_handlers::chop_trees_do_turn(), npc::do_player_activity(), activity_handlers::fetch_do_turn(), npc::find_job_to_perform(), activity_handlers::multiple_butcher_do_turn(), activity_handlers::multiple_chop_planks_do_turn(), activity_handlers::multiple_construction_do_turn(), activity_handlers::multiple_craft_do_turn(), activity_handlers::multiple_dis_do_turn(), activity_handlers::multiple_farm_do_turn(), activity_handlers::multiple_fish_do_turn(), activity_handlers::multiple_mine_do_turn(), activity_handlers::multiple_mop_do_turn(), activity_handlers::multiple_read_do_turn(), activity_handlers::tidy_up_do_turn(), activity_handlers::vehicle_deconstruction_do_turn(), and activity_handlers::vehicle_repair_do_turn().
get_auto_consume_moves()
int get_auto_consume_moves (Character & you, bool food)
Definition at line 3448 of file activity_item_handling.cpp.
 {
     if( you.is_npc() ) {
         return 0;
     }
     const tripoint pos = you.pos();
     zone_manager &mgr = zone_manager::get_manager();
     zone_type_id consume_type_zone( "" );
     if( food ) {
         consume_type_zone = zone_type_AUTO_EAT;
     } else {
         consume_type_zone = zone_type_AUTO_DRINK;
     }
     map &here = get_map();
     const std::unordered_set<tripoint_abs_ms> &dest_set =
         mgr.get_near( consume_type_zone, here.getglobal( pos ), ACTIVITY_SEARCH_DISTANCE, nullptr,
                       _fac_id( you ) );
     if( dest_set.empty() ) {
         return 0;
     }
     item_location best_comestible;
     for( const tripoint_abs_ms &loc : dest_set ) {
         if( loc.z() != you.pos().z ) {
             continue;
         }
         const auto visit = [&]( item_location & it ) {
             if( !you.can_consume_as_is( *it ) ) {
                 return VisitResponse::NEXT;
             }
             if( it->has_flag( json_flag_NO_AUTO_CONSUME ) ) {
                 // ignored due to NO_AUTO_CONSUME flag
                 return VisitResponse::NEXT;
             }
             if( it->is_null() || it->is_craft() || !it->is_food() ||
                 you.fun_for( *it ).first < -5 ) {
                 // not good eatings.
                 return VisitResponse::NEXT;
             }
             if( food && you.compute_effective_nutrients( *it ).kcal() < 50 ) {
                 // not filling enough
                 return VisitResponse::NEXT;
             }
             if( !you.will_eat( *it, false ).success() ) {
                 // wont like it, cannibal meat etc
                 return VisitResponse::NEXT;
             }
             if( !it->is_owned_by( you, true ) ) {
                 // it aint ours.
                 return VisitResponse::NEXT;
             }
             if( !food && it->get_comestible()->quench < 15 ) {
                 // not quenching enough
                 return VisitResponse::NEXT;
             }
             if( !food && it->is_watertight_container() && it->made_of( phase_id::SOLID ) ) {
                 // it's frozen
                 return VisitResponse::NEXT;
             }
             const use_function *usef = it->type->get_use( "BLECH_BECAUSE_UNCLEAN" );
             if( usef ) {
                 // it's unclean
                 return VisitResponse::NEXT;
             }
             if( it->get_comestible()->addictions.count( addiction_alcohol ) &&
                 !you.has_addiction( addiction_alcohol ) ) {
                 return VisitResponse::NEXT;
             }
             if( !best_comestible || comestible_sort_compare( you, it, best_comestible ) ) {
                 best_comestible = it;
             }
             return VisitResponse::NEXT;
         };
         const optional_vpart_position vp = here.veh_at( here.getlocal( loc ) );
         if( vp ) {
             if( const std::optional<vpart_reference> vp_cargo = vp.cargo() ) {
                 for( item &it : vp_cargo->items() ) {
                     item_location i_loc( vehicle_cursor( vp->vehicle(), vp->part_index() ), &it );
                     visit_item_contents( i_loc, visit );
                 }
             }
         } else {
             for( item &it : here.i_at( here.getlocal( loc ) ) ) {
                 item_location i_loc( map_cursor( here.getlocal( loc ) ), &it );
                 visit_item_contents( i_loc, visit );
             }
         }
     }
     if( best_comestible ) {
         //The moves it takes you to walk there and back.
         int consume_moves = 2 * you.run_cost( 100, false ) * std::max( rl_dist( you.pos_bub(),
                             best_comestible.pos_bub() ), 1 );
         consume_moves += to_moves<int>( you.get_consume_time( *best_comestible ) );
         you.consume( best_comestible );
         // eat() may have removed the item, so check its still there.
         if( best_comestible.get_item() && best_comestible->is_container() ) {
             best_comestible->on_contents_changed();
         }
         return consume_moves;
     }
     return 0;
 }
References anonymous_namespace{activity_item_handling.cpp}::_fac_id(), ACTIVITY_SEARCH_DISTANCE, addiction_alcohol, Character::can_consume_as_is(), optional_vpart_position::cargo(), comestible_sort_compare(), Character::compute_effective_nutrients(), Character::consume(), Character::fun_for(), item::get_comestible(), Character::get_consume_time(), item_location::get_item(), zone_manager::get_manager(), get_map(), zone_manager::get_near(), itype::get_use(), map::getglobal(), map::getlocal(), Character::has_addiction(), item::has_flag(), map::i_at(), item::is_container(), item::is_craft(), item::is_food(), Character::is_npc(), item::is_null(), item::is_owned_by(), item::is_watertight_container(), json_flag_NO_AUTO_CONSUME, nutrients::kcal(), item::made_of(), max(), NEXT, item::on_contents_changed(), Creature::pos(), math_opers::pos(), Creature::pos_bub(), item_location::pos_bub(), rl_dist(), Character::run_cost(), SOLID, item::type, map::veh_at(), visit_item_contents(), Character::will_eat(), tripoint::z, zone_type_AUTO_DRINK, and zone_type_AUTO_EAT.
Referenced by player_activity::do_turn().
get_sorted_tiles_by_distance()
template<typename Point , typename Container > std::vector<Point> get_sorted_tiles_by_distance (const Point & center, const Container & tiles)
Definition at line 25 of file activity_handlers.h.
 {
     const auto cmp = [center]( const Point & a, const Point & b ) {
         const int da = rl_dist( center, a );
         const int db = rl_dist( center, b );
         return da < db;
     };
     std::vector<Point> sorted( tiles.begin(), tiles.end() );
     std::sort( sorted.begin(), sorted.end(), cmp );
     return sorted;
 }
References a, b, center, rl_dist(), and sorted.
Referenced by activity_on_turn_move_loot(), unload_loot_activity_actor::do_turn(), find_refuel_spot_zone(), generic_multi_activity_handler(), perform_zone_activity_turn(), route_adjacent(), route_best_workbench(), and tidy_activity().
put_into_vehicle_or_drop() [1/2]
void put_into_vehicle_or_drop (Character & you, item_drop_reason reason, const std::list< item > & items)
Definition at line 442 of file activity_item_handling.cpp.
 {
     return put_into_vehicle_or_drop( you, reason, items, you.pos_bub() );
 }
References Creature::pos_bub(), and put_into_vehicle_or_drop().
Referenced by Character::add_or_drop_with_msg(), Character::apply_damage(), Character::complete_disassemble(), veh_interact::complete_vehicle(), damage_item(), Character::dispose_item(), move_items_activity_actor::do_turn(), drop_activity_actor::do_turn(), suffer::from_item_dropping(), Character::hardcoded_effects(), vehicle::invalidate_towing(), Character::migrate_items_to_storage(), move_item(), place_craft_or_disassembly(), put_into_vehicle_or_drop(), vehicle::reload_seeds(), set_item_inventory(), and tidy_activity().
put_into_vehicle_or_drop() [2/2]
void put_into_vehicle_or_drop (Character & you, item_drop_reason reason, const std::list< item > & items, const tripoint_bub_ms & where, bool force_ground = false)
Definition at line 448 of file activity_item_handling.cpp.
 {
     map &here = get_map();
     const std::optional<vpart_reference> vp = here.veh_at( where ).cargo();
     if( vp && !force_ground ) {
         put_into_vehicle( you, reason, items, *vp );
         return;
     }
     drop_on_map( you, reason, items, where );
 }
References optional_vpart_position::cargo(), drop_on_map(), get_map(), put_into_vehicle(), and map::veh_at().
repair_item_finish()
void repair_item_finish (player_activity * act, Character * you, bool no_menu)
Definition at line 2385 of file activity_handlers.cpp.
 {
     const std::string iuse_name_string = act->get_str_value( 0, "repair_item" );
     repeat_type repeat = static_cast<repeat_type>( act->get_value( 0,
                          static_cast<int>( repeat_type::INIT ) ) );
     weldrig_hack w_hack;
     item_location *ploc = nullptr;
     if( !act->targets.empty() ) {
         ploc = act->targets.data();
     }
     item *main_tool = &( !w_hack.init( *act ) ?
                          ploc ?
                          **ploc : you->i_at( act->index ) : w_hack.get_item() );
     if( main_tool == nullptr ) {
         debugmsg( "Empty main tool for repair" );
         act->set_to_null();
         return;
     }
     item *used_tool = main_tool->get_usable_item( iuse_name_string );
     if( used_tool == nullptr ) {
         debugmsg( "Lost tool used for long repair" );
         act->set_to_null();
         return;
     }
     const use_function *use_fun = used_tool->get_use( iuse_name_string );
     // TODO: De-uglify this block. Something like get_use<iuse_actor_type>() maybe?
     const repair_item_actor *actor = dynamic_cast<const repair_item_actor *>
                                      ( use_fun->get_actor_ptr() );
     if( actor == nullptr ) {
         debugmsg( "iuse_actor type descriptor and actual type mismatch" );
         act->set_to_null();
         return;
     }
     // Valid Repeat choice and target, attempt repair.
     if( repeat != repeat_type::INIT && act->targets.size() >= 2 ) {
         item_location &fix_location = act->targets[1];
         // Remember our level: we want to stop retrying on level up
         const int old_level = you->get_skill_level( actor->used_skill );
         const repair_item_actor::attempt_hint attempt = actor->repair( *you, *used_tool,
                 fix_location, repeat == repeat_type::REFIT_ONCE || repeat == repeat_type::REFIT_FULL );
         // If the item being repaired has been destroyed stop further
         // processing in case the items being used for the repair was
         // contained by the item being repaired, which will result
         // in the tool being invalid
         if( attempt == repair_item_actor::AS_DESTROYED ) {
             act->set_to_null();
             return;
         }
         if( attempt != repair_item_actor::AS_CANT ) {
             if( ploc && ploc->where() == item_location::type::map ) {
                 used_tool->ammo_consume( used_tool->ammo_required(), ploc->position(), you );
             } else {
                 you->consume_charges( *used_tool, used_tool->ammo_required() );
             }
         }
         // TODO: Allow setting this in the actor
         // TODO: Don't use charges_to_use: welder has 50 charges per use, soldering iron has 1
         if( !used_tool->ammo_sufficient( you ) ) {
             you->add_msg_if_player( _( "Your %s ran out of charges." ), used_tool->tname() );
             act->set_to_null();
             return;
         }
         // Print message explaining why we stopped
         // But only if we didn't destroy the item (because then it's obvious)
         const bool destroyed = attempt == repair_item_actor::AS_DESTROYED;
         const bool cannot_continue_repair = attempt == repair_item_actor::AS_CANT || destroyed ||
                                             !actor->can_repair_target( *you, *fix_location, !destroyed, true );
         if( cannot_continue_repair ) {
             // Cannot continue to repair target, select another target.
             // **Warning**: as soon as the item is popped back, it is destroyed and can't be used anymore!
             act->targets.pop_back();
         }
         const bool event_happened = attempt == repair_item_actor::AS_FAILURE ||
                                     attempt == repair_item_actor::AS_SUCCESS ||
                                     old_level != static_cast<int>( you->get_skill_level( actor->used_skill ) );
         const bool can_refit = !destroyed && !cannot_continue_repair &&
                                fix_location->has_flag( flag_VARSIZE ) &&
                                !fix_location->has_flag( flag_FIT );
         const bool need_input =
             ( repeat == repeat_type::ONCE ) ||
             ( repeat == repeat_type::EVENT && event_happened ) ||
             ( repeat == repeat_type::FULL && cannot_continue_repair ) ||
             ( repeat == repeat_type::REFIT_ONCE ) ||
             ( repeat == repeat_type::REFIT_FULL && !can_refit );
         if( need_input ) {
             repeat = repeat_type::INIT;
             if( no_menu ) {
                 act->set_to_null();
                 return;
             }
         }
     }
     // Check tool is valid before we query target and Repeat choice.
     if( !actor->can_use_tool( *you, *used_tool, true ) ) {
         act->set_to_null();
         return;
     }
     // target selection and validation.
     while( act->targets.size() < 2 ) {
         item_location item_loc = game_menus::inv::repair( *you, actor, main_tool );
         if( item_loc == item_location::nowhere ) {
             you->add_msg_if_player( m_info, _( "Never mind." ) );
             act->set_to_null();
             return;
         }
         if( actor->can_repair_target( *you, *item_loc, true, true ) ) {
             act->targets.emplace_back( item_loc );
             repeat = repeat_type::INIT;
         }
     }
     const item &fix = *act->targets[1];
     const bool can_refit = fix.has_flag( flag_VARSIZE ) && !fix.has_flag( flag_FIT );
     if( repeat == repeat_type::INIT ) {
         const int level = you->get_skill_level( actor->used_skill );
         repair_item_actor::repair_type action_type = actor->default_action( fix, level );
         if( action_type == repair_item_actor::RT_NOTHING ) {
             you->add_msg_if_player( _( "You won't learn anything more by doing that." ) );
         }
         const std::pair<float, float> chance = actor->repair_chance( *you, fix, action_type );
         if( chance.first <= 0.0f ) {
             action_type = repair_item_actor::RT_PRACTICE;
         }
         std::string title = string_format( _( "%s %s\n" ),
                                            repair_item_actor::action_description( action_type ),
                                            fix.tname() );
         ammotype current_ammo;
         std::string ammo_name;
         if( used_tool->has_flag( flag_USE_UPS ) || used_tool->has_link_data() ) {
             ammo_name = _( "battery" );
             current_ammo = ammo_battery;
         } else if( used_tool->has_flag( flag_USES_BIONIC_POWER ) ) {
             ammo_name = _( "bionic power" );
         } else {
             if( used_tool->ammo_current().is_null() ) {
                 current_ammo = item_controller->find_template( used_tool->ammo_default() )->ammo->type;
             } else {
                 current_ammo = item_controller->find_template( used_tool->ammo_current() )->ammo->type;
             }
             ammo_name = item::nname( used_tool->ammo_current() );
         }
         int ammo_remaining = used_tool->ammo_remaining( you, true );
         std::set<itype_id> valid_entries = actor->get_valid_repair_materials( fix );
         const inventory &crafting_inv = you->crafting_inventory();
         std::function<bool( const item & )> filter;
         if( fix.is_filthy() ) {
             filter = []( const item & component ) {
                 return component.allow_crafting_component();
             };
         } else {
             filter = is_crafting_component;
         }
         std::vector<std::string> material_list;
         for( const auto &component_id : valid_entries ) {
             if( item::count_by_charges( component_id ) ) {
                 if( crafting_inv.has_charges( component_id, 1 ) ) {
                     material_list.push_back( string_format( _( "%s (%d)" ), item::nname( component_id ),
                                                             crafting_inv.charges_of( component_id ) ) );
                 }
             } else if( crafting_inv.has_amount( component_id, 1, false, filter ) ) {
                 material_list.push_back( string_format( _( "%s (%d)" ), item::nname( component_id ),
                                                         crafting_inv.amount_of( component_id, false ) ) );
             }
         }
         title += string_format( _( "Charges: <color_light_blue>%s/%s</color> %s (%s per use)\n" ),
                                 ammo_remaining, used_tool->ammo_capacity( current_ammo, true ),
                                 ammo_name,
                                 used_tool->ammo_required() );
         title += string_format( _( "Materials available: %s\n" ), string_join( material_list, ", " ) );
         title += string_format( _( "Skill used: <color_light_blue>%s (%s)</color>\n" ),
                                 actor->used_skill.obj().name(), level );
         title += string_format( _( "Success chance: <color_light_blue>%.1f</color>%%\n" ),
                                 100.0f * chance.first );
         title += string_format( _( "Damage chance: <color_light_blue>%.1f</color>%%" ),
                                 100.0f * chance.second );
         if( act->values.empty() ) {
             act->values.resize( 1 );
         }
         do {
             repeat = repeat_menu( title, repeat, can_refit );
             if( repeat == repeat_type::CANCEL ) {
                 act->set_to_null();
                 return;
             }
             act->values[0] = static_cast<int>( repeat );
             // BACK selected, redo target selection next.
             if( repeat == repeat_type::INIT ) {
                 you->activity.targets.pop_back();
                 return;
             }
             if( repeat == repeat_type::FULL && fix.damage() <= fix.degradation() && !can_refit ) {
                 const char *msg = fix.damage_level() > 0 ?
                                   _( "Your %s is repaired as much as possible, considering the degradation." ) :
                                   _( "Your %s is already fully repaired." );
                 you->add_msg_if_player( m_info, msg, fix.tname() );
                 repeat = repeat_type::INIT;
             }
         } while( repeat == repeat_type::INIT );
     }
     // Otherwise keep retrying
     act->moves_left = actor->move_cost;
 }
References _, act, repair_item_actor::action_description(), Character::activity, Character::add_msg_if_player(), ammo_battery, item::ammo_capacity(), item::ammo_consume(), item::ammo_current(), item::ammo_default(), item::ammo_remaining(), item::ammo_required(), item::ammo_sufficient(), inventory::amount_of(), repair_item_actor::AS_CANT, repair_item_actor::AS_DESTROYED, repair_item_actor::AS_FAILURE, repair_item_actor::AS_SUCCESS, repair_item_actor::can_repair_target(), repair_item_actor::can_use_tool(), CANCEL, inventory::charges_of(), Character::consume_charges(), item::count_by_charges(), Character::crafting_inventory(), item::damage(), item::damage_level(), debugmsg, repair_item_actor::default_action(), item::degradation(), EVENT, filter, flag_FIT, flag_USE_UPS, flag_USES_BIONIC_POWER, flag_VARSIZE, FULL, use_function::get_actor_ptr(), weldrig_hack::get_item(), Character::get_skill_level(), item::get_usable_item(), item::get_use(), repair_item_actor::get_valid_repair_materials(), visitable::has_amount(), read_only_visitable::has_charges(), item::has_flag(), item::has_link_data(), Character::i_at(), INIT, weldrig_hack::init(), is_crafting_component(), item::is_filthy(), string_id< T >::is_null(), item_controller, m_info, item_location::map, repair_item_actor::move_cost, Skill::name(), item::nname(), item_location::nowhere, string_id< T >::obj(), ONCE, REFIT_FULL, REFIT_ONCE, repair_item_actor::repair(), game_menus::inv::repair(), repair_item_actor::repair_chance(), repeat_menu(), repair_item_actor::RT_NOTHING, repair_item_actor::RT_PRACTICE, string_format(), string_join(), player_activity::targets, music::title, item::tname(), and repair_item_actor::used_skill.
Referenced by activity_handlers::repair_item_finish().
route_adjacent()
std::vector<tripoint_bub_ms> route_adjacent (const Character & you, const tripoint_bub_ms & dest)
Definition at line 660 of file activity_item_handling.cpp.
 {
     std::unordered_set<tripoint_bub_ms> passable_tiles;
     map &here = get_map();
     for( const tripoint_bub_ms &tp : here.points_in_radius( dest, 1 ) ) {
         if( tp != you.pos_bub() && here.passable( tp ) ) {
             passable_tiles.emplace( tp );
         }
     }
     const std::vector<tripoint_bub_ms> &sorted =
         get_sorted_tiles_by_distance( you.pos_bub(), passable_tiles );
     const std::unordered_set<tripoint> &avoid = you.get_path_avoid();
     for( const tripoint_bub_ms &tp : sorted ) {
         std::vector<tripoint_bub_ms> route =
             here.route( you.pos_bub(), tp, you.get_pathfinding_settings(), avoid );
         if( !route.empty() ) {
             return route;
         }
     }
     return {};
 }
References get_map(), Character::get_path_avoid(), Character::get_pathfinding_settings(), get_sorted_tiles_by_distance(), map::passable(), map::points_in_radius(), Creature::pos_bub(), map::route(), and sorted.
Referenced by activity_on_turn_move_loot(), can_do_activity_there(), unload_loot_activity_actor::do_turn(), activity_handlers::find_mount_do_turn(), generic_multi_activity_handler(), and generic_multi_activity_locations().
try_fuel_fire()
bool try_fuel_fire (player_activity & act, Character & you, bool starting_fire = false)
Definition at line 3559 of file activity_item_handling.cpp.
 {
     const tripoint_bub_ms pos = you.pos_bub();
     std::vector<tripoint_bub_ms> adjacent = closest_points_first( pos, PICKUP_RANGE );
     adjacent.erase( adjacent.begin() );
     map &here = get_map();
     std::optional<tripoint_bub_ms> best_fire =
         starting_fire ? here.bub_from_abs( act.placement ) : find_best_fire( adjacent, pos );
     if( !best_fire || !here.accessible_items( *best_fire ) ) {
         return false;
     }
     std::optional<tripoint_bub_ms> refuel_spot = find_refuel_spot_zone( pos, _fac_id( you ) );
     if( !refuel_spot ) {
         refuel_spot = find_refuel_spot_trap( adjacent, pos );
         if( !refuel_spot ) {
             return false;
         }
     }
     // Special case: fire containers allow burning logs, so use them as fuel if fire is contained
     bool contained = here.has_flag_furn( ter_furn_flag::TFLAG_FIRE_CONTAINER, *best_fire );
     fire_data fd( 1, contained );
     time_duration fire_age = here.get_field_age( *best_fire, fd_fire );
     // Maybe TODO: - refueling in the rain could use more fuel
     // First, simulate expected burn per turn, to see if we need more fuel
     map_stack fuel_on_fire = here.i_at( *best_fire );
     for( item &it : fuel_on_fire ) {
         it.simulate_burn( fd );
         // Unconstrained fires grow below -50_minutes age
         if( !contained && fire_age < -40_minutes && fd.fuel_produced > 1.0f &&
             !it.made_of( phase_id::LIQUID ) ) {
             // Too much - we don't want a firestorm!
             // Move item back to refueling pile
             // Note: move_item() handles messages (they're the generic "you drop x")
             move_item( you, it, 0, *best_fire, *refuel_spot, std::nullopt );
             return true;
         }
     }
     // Enough to sustain the fire
     // TODO: It's not enough in the rain
     if( !starting_fire && ( fd.fuel_produced >= 1.0f || fire_age < 10_minutes ) ) {
         return true;
     }
     // We need to move fuel from stash to fire
     map_stack potential_fuel = here.i_at( *refuel_spot );
     for( item &it : potential_fuel ) {
         if( it.made_of( phase_id::LIQUID ) ) {
             continue;
         }
         float last_fuel = fd.fuel_produced;
         it.simulate_burn( fd );
         if( fd.fuel_produced > last_fuel ) {
             int quantity = std::max( 1, std::min( it.charges, it.charges_per_volume( 250_ml ) ) );
             // Note: move_item() handles messages (they're the generic "you drop x")
             move_item( you, it, quantity, *refuel_spot, *best_fire, std::nullopt );
             return true;
         }
     }
     return true;
 }
References anonymous_namespace{activity_item_handling.cpp}::_fac_id(), map::accessible_items(), act, map::bub_from_abs(), item::charges, item::charges_per_volume(), closest_points_first(), fd_fire, find_best_fire(), find_refuel_spot_trap(), find_refuel_spot_zone(), fire_data::fuel_produced, map::get_field_age(), get_map(), map::has_flag_furn(), map::i_at(), LIQUID, item::made_of(), max(), min(), move_item(), PICKUP_RANGE, math_opers::pos(), Creature::pos_bub(), item::simulate_burn(), and TFLAG_FIRE_CONTAINER.
Referenced by player_activity::do_turn(), and activity_handlers::start_fire_do_turn().
Variable Documentation
do_activity_reason_string
const std::vector<std::string> do_activity_reason_string
Initial value:
= {
    "CAN_DO_CONSTRUCTION",
    "CAN_DO_FETCH",
    "NO_COMPONENTS",
    "DONT_HAVE_SKILL",
    "NO_ZONE",
    "ALREADY_DONE",
    "UNKNOWN_ACTIVITY",
    "NEEDS_CLEARING",
    "NEEDS_HARVESTING",
    "NEEDS_PLANTING",
    "NEEDS_TILLING",
    "BLOCKING_TILE",
    "NEEDS_BOOK_TO_LEARN",
    "NEEDS_CHOPPING",
    "NEEDS_TREE_CHOPPING",
    "NEEDS_BIG_BUTCHERING",
    "NEEDS_BUTCHERING",
    "NEEDS_CUT_HARVESTING",
    "ALREADY_WORKING",
    "NEEDS_VEH_DECONST",
    "NEEDS_VEH_REPAIR",
    "WOULD_PREVENT_VEH_FLYING",
    "NEEDS_MINING",
    "NEEDS_MOP",
    "NEEDS_FISHING",
    "NEEDS_CRAFT",
    "NEEDS_DISASSEMBLE"
}
Definition at line 92 of file activity_handlers.h.
Referenced by generic_multi_activity_check_requirement().