Cataclysm DDA: src/activity_handlers.cpp File Reference
activity_handlers.cpp File Reference
#include "activity_handlers.h"
#include <algorithm>
#include <climits>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <optional>
#include <ostream>
#include <queue>
#include <set>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include "activity_actor.h"
#include "activity_type.h"
#include "advanced_inv.h"
#include "avatar.h"
#include "avatar_action.h"
#include "bionics.h"
#include "bodypart.h"
#include "butchery_requirements.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "character_attire.h"
#include "character_id.h"
#include "character_martial_arts.h"
#include "clzones.h"
#include "colony.h"
#include "color.h"
#include "construction.h"
#include "coordinates.h"
#include "creature.h"
#include "creature_tracker.h"
#include "cuboid_rectangle.h"
#include "debug.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "fault.h"
#include "field_type.h"
#include "flag.h"
#include "flexbuffer_json-inl.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "handle_liquid.h"
#include "harvest.h"
#include "iexamine.h"
#include "inventory.h"
#include "inventory_ui.h"
#include "item.h"
#include "item_factory.h"
#include "item_location.h"
#include "item_stack.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "magic.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "martialarts.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "omdata.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player_activity.h"
#include "pocket_type.h"
#include "point.h"
#include "proficiency.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translation.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_interact.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weakpoint.h"
#include "weather.h"
Classes
struct weldrig_hack
Namespaces
io
Macros
#define dbg(x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Typedefs
using I = std::underlying_type_t< repeat_type >
Enumerations
enum class repeat_type : int {
INIT = 0 , ONCE = 1 , FULL = 3 , EVENT = 4 ,
REFIT_ONCE = 5 , REFIT_FULL = 6 , CANCEL = 7
}
Functions
template<>
std::string io::enum_to_string< butcher_type > (butcher_type data)
static void assign_multi_activity (Character &you, const player_activity &act)
static bool check_butcher_dissect (const int roll)
static bool butcher_dissect_item (item &what, const tripoint &pos, const time_point &age, const int roll)
static void set_up_butchery (player_activity &act, Character &you, butcher_type action)
int butcher_time_to_cut (Character &you, const item &corpse_item, const butcher_type action)
static int corpse_damage_effect (int weight, const harvest_drop_type_id &entry_type, int damage_level)
static int butchery_dissect_skill_level (Character &you, int tool_quality, const harvest_drop_type_id &htype)
static int roll_butchery_dissect (int skill_level, int dex, int tool_quality)
static double butchery_dissect_yield_mult (int skill_level, int dex, int tool_quality)
static std::vector< item > create_charge_items (const itype *drop, int count, const harvest_entry &entry, const item *corpse_item, const Character &you)
static bool butchery_drops_harvest (item *corpse_item, const mtype &mt, Character &you, butcher_type action)
static void butchery_quarter (item *corpse_item, const Character &you)
static bool magic_train (player_activity *act, Character *you)
static constexpr bool operator>= (const I &lhs, const repeat_type &rhs)
static constexpr bool operator<= (const I &lhs, const repeat_type &rhs)
static constexpr I operator- (const repeat_type &lhs, const repeat_type &rhs)
static repeat_type repeat_menu (const std::string &title, repeat_type last_selection, const bool can_refit)
void repair_item_finish (player_activity *act, Character *you, bool no_menu)
static void rod_fish (Character *you, const std::vector< monster * > &fishables)
template<typename fn >
static void cleanup_tiles (std::unordered_set< tripoint_abs_ms > &tiles, fn &cleanup)
static void perform_zone_activity_turn (Character *you, const zone_type_id &ztype, const std::function< bool(const tripoint_bub_ms &)> &tile_filter, const std::function< void(Character &you, const tripoint_bub_ms &)> &tile_action, const std::string &finished_msg)
static void blood_magic (Character *you, int cost)
Variables
static const activity_id ACT_ADV_INVENTORY ("ACT_ADV_INVENTORY")
static const activity_id ACT_ARMOR_LAYERS ("ACT_ARMOR_LAYERS")
static const activity_id ACT_ATM ("ACT_ATM")
static const activity_id ACT_BLEED ("ACT_BLEED")
static const activity_id ACT_BUILD ("ACT_BUILD")
static const activity_id ACT_BUTCHER ("ACT_BUTCHER")
static const activity_id ACT_BUTCHER_FULL ("ACT_BUTCHER_FULL")
static const activity_id ACT_CONSUME_DRINK_MENU ("ACT_CONSUME_DRINK_MENU")
static const activity_id ACT_CONSUME_FOOD_MENU ("ACT_CONSUME_FOOD_MENU")
static const activity_id ACT_CONSUME_MEDS_MENU ("ACT_CONSUME_MEDS_MENU")
static const activity_id ACT_DISMEMBER ("ACT_DISMEMBER")
static const activity_id ACT_DISSECT ("ACT_DISSECT")
static const activity_id ACT_EAT_MENU ("ACT_EAT_MENU")
static const activity_id ACT_FERTILIZE_PLOT ("ACT_FERTILIZE_PLOT")
static const activity_id ACT_FETCH_REQUIRED ("ACT_FETCH_REQUIRED")
static const activity_id ACT_FIELD_DRESS ("ACT_FIELD_DRESS")
static const activity_id ACT_FILL_LIQUID ("ACT_FILL_LIQUID")
static const activity_id ACT_FIND_MOUNT ("ACT_FIND_MOUNT")
static const activity_id ACT_FISH ("ACT_FISH")
static const activity_id ACT_GAME ("ACT_GAME")
static const activity_id ACT_GENERIC_GAME ("ACT_GENERIC_GAME")
static const activity_id ACT_HAND_CRANK ("ACT_HAND_CRANK")
static const activity_id ACT_HEATING ("ACT_HEATING")
static const activity_id ACT_JACKHAMMER ("ACT_JACKHAMMER")
static const activity_id ACT_MEND_ITEM ("ACT_MEND_ITEM")
static const activity_id ACT_MOVE_LOOT ("ACT_MOVE_LOOT")
static const activity_id ACT_MULTIPLE_BUTCHER ("ACT_MULTIPLE_BUTCHER")
static const activity_id ACT_MULTIPLE_CHOP_PLANKS ("ACT_MULTIPLE_CHOP_PLANKS")
static const activity_id ACT_MULTIPLE_CHOP_TREES ("ACT_MULTIPLE_CHOP_TREES")
static const activity_id ACT_MULTIPLE_CONSTRUCTION ("ACT_MULTIPLE_CONSTRUCTION")
static const activity_id ACT_MULTIPLE_CRAFT ("ACT_MULTIPLE_CRAFT")
static const activity_id ACT_MULTIPLE_DIS ("ACT_MULTIPLE_DIS")
static const activity_id ACT_MULTIPLE_FARM ("ACT_MULTIPLE_FARM")
static const activity_id ACT_MULTIPLE_FISH ("ACT_MULTIPLE_FISH")
static const activity_id ACT_MULTIPLE_MINE ("ACT_MULTIPLE_MINE")
static const activity_id ACT_MULTIPLE_MOP ("ACT_MULTIPLE_MOP")
static const activity_id ACT_MULTIPLE_READ ("ACT_MULTIPLE_READ")
static const activity_id ACT_OPERATION ("ACT_OPERATION")
static const activity_id ACT_PICKAXE ("ACT_PICKAXE")
static const activity_id ACT_PLANT_SEED ("ACT_PLANT_SEED")
static const activity_id ACT_PULL_CREATURE ("ACT_PULL_CREATURE")
static const activity_id ACT_PULP ("ACT_PULP")
static const activity_id ACT_QUARTER ("ACT_QUARTER")
static const activity_id ACT_REPAIR_ITEM ("ACT_REPAIR_ITEM")
static const activity_id ACT_ROBOT_CONTROL ("ACT_ROBOT_CONTROL")
static const activity_id ACT_SKIN ("ACT_SKIN")
static const activity_id ACT_SOCIALIZE ("ACT_SOCIALIZE")
static const activity_id ACT_SPELLCASTING ("ACT_SPELLCASTING")
static const activity_id ACT_START_ENGINES ("ACT_START_ENGINES")
static const activity_id ACT_START_FIRE ("ACT_START_FIRE")
static const activity_id ACT_STUDY_SPELL ("ACT_STUDY_SPELL")
static const activity_id ACT_TIDY_UP ("ACT_TIDY_UP")
static const activity_id ACT_TOOLMOD_ADD ("ACT_TOOLMOD_ADD")
static const activity_id ACT_TRAIN ("ACT_TRAIN")
static const activity_id ACT_TRAIN_TEACHER ("ACT_TRAIN_TEACHER")
static const activity_id ACT_TRAVELLING ("ACT_TRAVELLING")
static const activity_id ACT_TREE_COMMUNION ("ACT_TREE_COMMUNION")
static const activity_id ACT_VEHICLE ("ACT_VEHICLE")
static const activity_id ACT_VEHICLE_DECONSTRUCTION ("ACT_VEHICLE_DECONSTRUCTION")
static const activity_id ACT_VEHICLE_REPAIR ("ACT_VEHICLE_REPAIR")
static const activity_id ACT_VIBE ("ACT_VIBE")
static const activity_id ACT_VIEW_RECIPE ("ACT_VIEW_RECIPE")
static const activity_id ACT_WAIT ("ACT_WAIT")
static const activity_id ACT_WAIT_NPC ("ACT_WAIT_NPC")
static const activity_id ACT_WAIT_STAMINA ("ACT_WAIT_STAMINA")
static const activity_id ACT_WAIT_WEATHER ("ACT_WAIT_WEATHER")
static const ammotype ammo_battery ("battery")
static const bionic_id bio_painkiller ("bio_painkiller")
static const damage_type_id damage_acid ("acid")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_cut ("cut")
static const damage_type_id damage_stab ("stab")
static const efftype_id effect_asocial_dissatisfied ("asocial_dissatisfied")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_controlled ("controlled")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_social_dissatisfied ("social_dissatisfied")
static const efftype_id effect_social_satisfied ("social_satisfied")
static const efftype_id effect_under_operation ("under_operation")
static const furn_str_id furn_f_compost_empty ("f_compost_empty")
static const furn_str_id furn_f_compost_full ("f_compost_full")
static const furn_str_id furn_f_fvat_empty ("f_fvat_empty")
static const furn_str_id furn_f_fvat_wood_empty ("f_fvat_wood_empty")
static const furn_str_id furn_f_fvat_wood_full ("f_fvat_wood_full")
static const furn_str_id furn_f_plant_seed ("f_plant_seed")
static const harvest_drop_type_id harvest_drop_blood ("blood")
static const harvest_drop_type_id harvest_drop_bone ("bone")
static const harvest_drop_type_id harvest_drop_flesh ("flesh")
static const harvest_drop_type_id harvest_drop_offal ("offal")
static const harvest_drop_type_id harvest_drop_skin ("skin")
static const itype_id itype_animal ("animal")
static const itype_id itype_battery ("battery")
static const itype_id itype_burnt_out_bionic ("burnt_out_bionic")
static const itype_id itype_muscle ("muscle")
static const itype_id itype_pseudo_magazine ("pseudo_magazine")
static const json_character_flag json_flag_ASOCIAL1 ("ASOCIAL1")
static const json_character_flag json_flag_ASOCIAL2 ("ASOCIAL2")
static const json_character_flag json_flag_CANNIBAL ("CANNIBAL")
static const json_character_flag json_flag_PAIN_IMMUNE ("PAIN_IMMUNE")
static const json_character_flag json_flag_PSYCHOPATH ("PSYCHOPATH")
static const json_character_flag json_flag_SAPIOVORE ("SAPIOVORE")
static const json_character_flag json_flag_SILENT_SPELL ("SILENT_SPELL")
static const json_character_flag json_flag_SOCIAL1 ("SOCIAL1")
static const json_character_flag json_flag_SOCIAL2 ("SOCIAL2")
static const mongroup_id GROUP_FISH ("GROUP_FISH")
static const proficiency_id proficiency_prof_dissect_humans ("prof_dissect_humans")
static const quality_id qual_BUTCHER ("BUTCHER")
static const quality_id qual_CUT_FINE ("CUT_FINE")
static const quality_id qual_FISHING_ROD ("FISHING_ROD")
static const skill_id skill_computer ("computer")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_survival ("survival")
static const species_id species_FERAL ("FERAL")
static const species_id species_HUMAN ("HUMAN")
static const species_id species_ZOMBIE ("ZOMBIE")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_tree ("t_tree")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_SPIRITUAL ("SPIRITUAL")
static const trait_id trait_STOCKY_TROGLO ("STOCKY_TROGLO")
static const zone_type_id zone_type_FARM_PLOT ("FARM_PLOT")
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 109 of file activity_handlers.cpp.
Typedef Documentation
I
using I = std::underlying_type_t<repeat_type>
Definition at line 2265 of file activity_handlers.cpp.
Enumeration Type Documentation
repeat_type
enum repeat_type : int strong
Enumerator
INIT
ONCE
FULL
EVENT
REFIT_ONCE
REFIT_FULL
CANCEL
Definition at line 2253 of file activity_handlers.cpp.
                        : int {
     // INIT should be zero. In some scenarios (vehicle welder), activity value default to zero.
     INIT = 0,       // Haven't found repeat value yet.
     ONCE = 1,       // Attempt repair (and refit if possible) just once
     // value 2 obsolete - previously used for reinforcement
     FULL = 3,       // Continue repairing until damage==0 (and until refitted if possible)
     EVENT = 4,      // Continue repairing (and refit if possible) until something interesting happens
     REFIT_ONCE = 5, // Try refitting once, but don't repair
     REFIT_FULL = 6, // Continue refitting until item fits, but don't repair
     CANCEL = 7,     // Stop repeating
 };
Function Documentation
assign_multi_activity()
static void assign_multi_activity (Character & you, const player_activity & act) static
Definition at line 371 of file activity_handlers.cpp.
 {
     const bool requires_actor = activity_actors::deserialize_functions.find( act.id() ) !=
                                 activity_actors::deserialize_functions.end();
     if( requires_actor ) {
         // the activity uses `activity_actor` and requires `player_activity::actor` to be set
         you.assign_activity( player_activity( act ) );
     } else {
         // the activity uses the older type of player_activity where `player_activity::actor` is not used
         you.assign_activity( act.id() );
     }
 }
References act, Character::assign_activity(), activity_actors::deserialize_functions, and string_id< T >::id().
Referenced by activity_handlers::resume_for_multi_activities().
blood_magic()
static void blood_magic (Character * you, int cost) static
Definition at line 3779 of file activity_handlers.cpp.
 {
     std::vector<uilist_entry> uile;
     std::vector<bodypart_id> parts;
     int i = 0;
     for( const bodypart_id &bp : you->get_all_body_parts( get_body_part_flags::only_main ) ) {
         const int hp_cur = you->get_part_hp_cur( bp );
         uilist_entry entry( i, hp_cur > cost, i + 49, body_part_hp_bar_ui_text( bp ) );
         const std::pair<std::string, nc_color> &hp = get_hp_bar( hp_cur, you->get_part_hp_max( bp ) );
         entry.ctxt = colorize( hp.first, hp.second );
         uile.emplace_back( entry );
         parts.push_back( bp );
         i++;
     }
     int action = -1;
     while( action < 0 ) {
         action = uilist( _( "Choose part\nto draw blood from." ), uile );
     }
     you->mod_part_hp_cur( parts[action], - cost );
     you->mod_pain( std::max( 1, cost / 3 ) );
 }
References _, action, body_part_hp_bar_ui_text(), bp, colorize(), uilist_entry::ctxt, Creature::get_all_body_parts(), get_hp_bar(), Creature::get_part_hp_cur(), Creature::get_part_hp_max(), hp, max(), Character::mod_pain(), Character::mod_part_hp_cur(), and only_main.
Referenced by activity_handlers::spellcasting_finish().
butcher_dissect_item()
static bool butcher_dissect_item (item & what, const tripoint & pos, const time_point & age, const int roll) static
Definition at line 410 of file activity_handlers.cpp.
 {
     if( roll < 0 ) {
         return false;
     }
     bool success = check_butcher_dissect( roll );
     map &here = get_map();
     if( what.is_bionic() && !success ) {
         item burnt_out_cbm( itype_burnt_out_bionic, age );
         add_msg( m_good, _( "You discover a %s!" ), burnt_out_cbm.tname() );
         here.add_item( pos, burnt_out_cbm );
     } else if( success ) {
         add_msg( m_good, _( "You discover a %s!" ), what.tname() );
         here.add_item( pos, what );
     }
     return success;
 }
References _, map::add_item(), add_msg(), check_butcher_dissect(), get_map(), item::is_bionic(), itype_burnt_out_bionic, m_good, math_opers::pos(), and item::tname().
Referenced by butchery_drops_harvest().
butcher_time_to_cut()
int butcher_time_to_cut (Character & you, const item & corpse_item, const butcher_type action)
Definition at line 676 of file activity_handlers.cpp.
 {
     const mtype &corpse = *corpse_item.get_mtype();
     const int factor = you.max_quality( action == butcher_type::DISSECT ? qual_CUT_FINE : qual_BUTCHER,
                                         PICKUP_RANGE );
     int time_to_cut;
     switch( corpse.size ) {
         // Time (roughly) in turns to cut up the corpse
         case creature_size::tiny:
             time_to_cut = 150;
             break;
         case creature_size::small:
             time_to_cut = 300;
             break;
         case creature_size::medium:
             time_to_cut = 450;
             break;
         case creature_size::large:
             time_to_cut = 600;
             break;
         case creature_size::huge:
             time_to_cut = 1800;
             break;
         default:
             debugmsg( "ERROR: Invalid creature_size on %s", corpse.nname() );
             time_to_cut = 450; // default to medium
             break;
     }
     // At factor 0, base 100 time_to_cut remains 100. At factor 50, it's 50 , at factor 75 it's 25
     time_to_cut *= std::max( 25, 100 - factor );
     switch( action ) {
         case butcher_type::QUICK:
         case butcher_type::BLEED:
             break;
         case butcher_type::FULL:
             if( !corpse_item.has_flag( flag_FIELD_DRESS ) || corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) {
                 time_to_cut *= 6;
             } else {
                 time_to_cut *= 4;
             }
             break;
         case butcher_type::FIELD_DRESS:
         case butcher_type::SKIN:
             time_to_cut *= 2;
             break;
         case butcher_type::QUARTER:
             time_to_cut /= 4;
             if( time_to_cut < 1200 ) {
                 time_to_cut = 1200;
             }
             break;
         case butcher_type::DISMEMBER:
             time_to_cut /= 10;
             if( time_to_cut < 600 ) {
                 time_to_cut = 600;
             }
             break;
         case butcher_type::DISSECT:
             time_to_cut *= 6;
             break;
         case butcher_type::NUM_TYPES:
             debugmsg( "ERROR: Invalid butcher_type" );
             break;
     }
     if( corpse_item.has_flag( flag_QUARTERED ) ) {
         time_to_cut /= 4;
     }
     time_to_cut *= ( 1.0f - ( get_player_character().get_num_crafting_helpers( 3 ) / 10.0f ) );
     return time_to_cut;
 }
References action, BLEED, corpse, debugmsg, DISMEMBER, DISSECT, FIELD_DRESS, flag_FIELD_DRESS, flag_FIELD_DRESS_FAILED, flag_QUARTERED, FULL, item::get_mtype(), Character::get_num_crafting_helpers(), get_player_character(), item::has_flag(), huge, large, max(), Character::max_quality(), medium, NUM_TYPES, PICKUP_RANGE, qual_BUTCHER, qual_CUT_FINE, QUARTER, QUICK, SKIN, small, and tiny.
Referenced by butcher_submenu(), and set_up_butchery().
butchery_dissect_skill_level()
static int butchery_dissect_skill_level (Character & you, int tool_quality, const harvest_drop_type_id & htype) static
Definition at line 810 of file activity_handlers.cpp.
 {
     // DISSECT has special case factor calculation and results.
     if( htype.is_valid() ) {
         float sk_total = 0;
         int sk_count = 0;
         for( const skill_id &sk : htype->get_harvest_skills() ) {
             sk_total += you.get_average_skill_level( sk );
             sk_count++;
         }
         return round( ( sk_total + tool_quality ) / ( sk_count > 0 ? sk_count : 1 ) );
     }
     return round( you.get_average_skill_level( skill_survival ) );
 }
References Character::get_average_skill_level(), harvest_drop_type::get_harvest_skills(), string_id< T >::is_valid(), round(), and skill_survival.
Referenced by butchery_drops_harvest().
butchery_dissect_yield_mult()
static double butchery_dissect_yield_mult (int skill_level, int dex, int tool_quality) static
Definition at line 845 of file activity_handlers.cpp.
 {
     const double skill_score = skill_level / 10.0;
     const double tool_score = ( tool_quality + 50.0 ) / 100.0;
     const double dex_score = dex / 20.0;
     return 0.5 * clamp( skill_score, 0.0, 1.0 ) +
            0.3 * clamp( tool_score, 0.0, 1.0 ) +
            0.2 * clamp( dex_score, 0.0, 1.0 );
 }
References clamp().
Referenced by butchery_drops_harvest().
butchery_drops_harvest()
static bool butchery_drops_harvest (item * corpse_item, const mtype & mt, Character & you, butcher_type action) static
Definition at line 885 of file activity_handlers.cpp.
 {
     const int tool_quality = you.max_quality( action == butcher_type::DISSECT ? qual_CUT_FINE :
                              qual_BUTCHER, PICKUP_RANGE );
     //all BUTCHERY types - FATAL FAILURE
     if( action != butcher_type::DISSECT &&
         roll_butchery_dissect( round( you.get_average_skill_level( skill_survival ) ), you.dex_cur,
                                tool_quality ) <= ( -15 ) && one_in( 2 ) ) {
         return false;
     }
     you.add_msg_if_player( m_neutral, mt.harvest->message() );
     int monster_weight = to_gram( mt.weight );
     monster_weight += std::round( monster_weight * rng_float( -0.1, 0.1 ) );
     if( corpse_item->has_flag( flag_QUARTERED ) ) {
         monster_weight *= 0.95;
     }
     if( corpse_item->has_flag( flag_GIBBED ) ) {
         monster_weight = std::round( 0.85 * monster_weight );
         if( action != butcher_type::FIELD_DRESS ) {
             you.add_msg_if_player( m_bad,
                                    _( "You salvage what you can from the corpse, but it is badly damaged." ) );
         }
     }
     if( corpse_item->has_flag( flag_UNDERFED ) ) {
         monster_weight = std::round( 0.9 * monster_weight );
         if( action != butcher_type::FIELD_DRESS && action != butcher_type::SKIN &&
             action != butcher_type::DISSECT ) {
             you.add_msg_if_player( m_bad,
                                    _( "The corpse looks a little underweight" ) );
         }
     }
     if( corpse_item->has_flag( flag_SKINNED ) ) {
         monster_weight = std::round( 0.85 * monster_weight );
     }
     const int entry_count = ( action == butcher_type::DISSECT &&
                               !mt.dissect.is_empty() ) ? mt.dissect->get_all().size() : mt.harvest->get_all().size();
     int monster_weight_remaining = monster_weight;
     int practice = 0;
     if( mt.harvest.is_null() ) {
         debugmsg( "ERROR: %s has no harvest entry.", mt.id.c_str() );
         return false;
     }
     if( action == butcher_type::DISSECT )    {
         int dissectable_practice = 0;
         int dissectable_num = 0;
         for( item *item : corpse_item->all_items_top( pocket_type::CORPSE ) ) {
             dissectable_num++;
             const int skill_level = butchery_dissect_skill_level( you, tool_quality,
                                     item->dropped_from );
             const int butchery = roll_butchery_dissect( skill_level, you.dex_cur, tool_quality );
             dissectable_practice += ( 4 + butchery );
             int roll = butchery - corpse_item->damage_level();
             roll = roll < 0 ? 0 : roll;
             add_msg_debug( debugmode::DF_ACT_BUTCHER, "Roll penalty for corpse damage = %s",
                            0 - corpse_item->damage_level() );
             butcher_dissect_item( *item, you.pos(), calendar::turn, roll );
         }
         if( dissectable_num > 0 ) {
             practice += dissectable_practice / dissectable_num;
         }
     }
     map &here = get_map();
     for( const harvest_entry &entry : ( action == butcher_type::DISSECT &&
                                         !mt.dissect.is_empty() ) ? *mt.dissect : *mt.harvest ) {
         const int skill_level = butchery_dissect_skill_level( you, tool_quality, entry.type );
         const int butchery = roll_butchery_dissect( skill_level, you.dex_cur, tool_quality );
         practice += ( 4 + butchery ) / entry_count;
         const float min_num = entry.base_num.first + butchery * entry.scale_num.first;
         const float max_num = entry.base_num.second + butchery * entry.scale_num.second;
         int roll = 0;
         // mass_ratio will override the use of base_num, scale_num, and max
         if( entry.mass_ratio != 0.00f ) {
             roll = static_cast<int>( std::round( entry.mass_ratio * monster_weight ) );
             roll = corpse_damage_effect( roll, entry.type, corpse_item->damage_level() );
         } else {
             roll = std::min<int>( entry.max, std::round( rng_float( min_num, max_num ) ) );
             // will not give less than min_num defined in the JSON
             roll = std::max<int>( corpse_damage_effect( roll, entry.type, corpse_item->damage_level() ),
                                   entry.base_num.first );
         }
         itype_id drop_id = itype_id::NULL_ID();
         const itype *drop = nullptr;
         if( entry.type->is_itype() ) {
             drop_id = itype_id( entry.drop );
             drop = item::find_type( drop_id );
         }
         // Check if monster was gibbed, and handle accordingly
         if( corpse_item->has_flag( flag_GIBBED ) && ( entry.type == harvest_drop_flesh ||
                 entry.type == harvest_drop_bone ) ) {
             roll /= 2;
         }
         if( corpse_item->has_flag( flag_UNDERFED ) && ( entry.type == harvest_drop_flesh ) ) {
             roll /= 1.6;
         }
         if( corpse_item->has_flag( flag_SKINNED ) && entry.type == harvest_drop_skin ) {
             roll = 0;
         }
         // QUICK BUTCHERY
         if( action == butcher_type::QUICK ) {
             if( entry.type == harvest_drop_flesh ) {
                 roll /= 4;
             } else if( entry.type == harvest_drop_bone ) { // NOLINT(bugprone-branch-clone)
                 roll /= 2;
             } else if( corpse_item->get_mtype()->size >= creature_size::medium &&
                        entry.type == harvest_drop_skin ) {
                 roll /= 2;
             } else if( entry.type == harvest_drop_offal ) {
                 roll /= 5;
             } else {
                 continue;
             }
         }
         // RIP AND TEAR
         if( action == butcher_type::DISMEMBER ) {
             if( entry.type == harvest_drop_flesh ) {
                 roll /= 6;
             } else {
                 continue;
             }
         }
         // field dressing ignores skin, flesh, and blood
         if( action == butcher_type::FIELD_DRESS ) {
             if( entry.type == harvest_drop_bone ) {
                 roll = rng( 0, roll / 2 );
             }
             if( entry.type == harvest_drop_flesh ) {
                 continue;
             }
             if( entry.type == harvest_drop_skin ) {
                 continue;
             }
         }
         // you only get the blood from bleeding
         if( action == butcher_type::BLEED ) {
             if( entry.type != harvest_drop_blood ) {
                 continue;
             }
         }
         // you only get the skin from skinning
         if( action == butcher_type::SKIN ) {
             if( entry.type != harvest_drop_skin ) {
                 continue;
             }
             if( corpse_item->has_flag( flag_FIELD_DRESS_FAILED ) ) {
                 roll = rng( 0, roll );
             }
         }
         // field dressing removed innards and bones from meatless limbs
         if( ( action == butcher_type::FULL || action == butcher_type::QUICK ) &&
             corpse_item->has_flag( flag_FIELD_DRESS ) ) {
             if( entry.type == harvest_drop_offal ) {
                 continue;
             }
             if( entry.type == harvest_drop_bone ) {
                 roll = ( roll / 2 ) + rng( roll / 2, roll );
             }
         }
         // unskillfull field dressing may damage the skin, meat, and other parts
         if( ( action == butcher_type::FULL || action == butcher_type::QUICK ) &&
             corpse_item->has_flag( flag_FIELD_DRESS_FAILED ) ) {
             if( entry.type == harvest_drop_offal ) {
                 continue;
             }
             if( entry.type == harvest_drop_bone ) {
                 roll = ( roll / 2 ) + rng( roll / 2, roll );
             }
             if( entry.type == harvest_drop_flesh || entry.type == harvest_drop_skin ) {
                 roll = rng( 0, roll );
             }
         }
         // quartering ruins skin
         if( corpse_item->has_flag( flag_QUARTERED ) ) {
             if( entry.type == harvest_drop_skin ) {
                 //not continue to show fail effect
                 roll = 0;
             } else {
                 roll /= 4;
             }
         }
         if( drop != nullptr ) {
             // divide total dropped weight by drop's weight to get amount
             if( entry.mass_ratio != 0.00f ) {
                 // apply skill before converting to items, but only if mass_ratio is defined
                 roll *= butchery_dissect_yield_mult( skill_level, you.dex_cur, tool_quality );
                 monster_weight_remaining -= roll;
                 roll = std::ceil( static_cast<double>( roll ) /
                                   to_gram( drop->weight ) );
             } else {
                 monster_weight_remaining -= roll * to_gram( drop->weight );
             }
             const translation msg = action == butcher_type::FIELD_DRESS ?
                                     entry.type->field_dress_msg( roll > 0 ) :
                                     action == butcher_type::QUICK || action == butcher_type::FULL ||
                                     action == butcher_type::DISMEMBER ? entry.type->butcher_msg( roll > 0 ) : translation();
             if( !msg.empty() ) {
                 you.add_msg_if_player( m_bad, msg.translated() );
             }
             if( roll <= 0 ) {
                 you.add_msg_if_player( m_bad, _( "You fail to harvest: %s" ), drop->nname( 1 ) );
                 continue;
             }
             if( drop->phase == phase_id::LIQUID ) {
                 item obj( drop, calendar::turn, roll );
                 if( obj.has_temperature() ) {
                     obj.set_item_temperature( corpse_item->temperature );
                     if( obj.goes_bad() ) {
                         obj.set_rot( corpse_item->get_rot() );
                     }
                 }
                 for( const flag_id &flg : entry.flags ) {
                     obj.set_flag( flg );
                 }
                 for( const fault_id &flt : entry.faults ) {
                     obj.faults.emplace( flt );
                 }
                 // TODO: smarter NPC liquid handling
                 // If we're not bleeding the animal we don't care about the blood being wasted
                 if( you.is_npc() || action != butcher_type::BLEED ) {
                     drop_on_map( you, item_drop_reason::deliberate, { obj }, you.pos_bub() );
                 } else {
                     liquid_handler::handle_all_liquid( obj, 1 );
                 }
             } else if( drop->count_by_charges() ) {
                 std::vector<item> objs = create_charge_items( drop, roll, entry, corpse_item, you );
                 for( item &obj : objs ) {
                     here.add_item_or_charges( you.pos(), obj );
                 }
             } else {
                 item obj( drop, calendar::turn );
                 obj.set_mtype( &mt );
                 if( obj.has_temperature() ) {
                     obj.set_item_temperature( corpse_item->temperature );
                     if( obj.goes_bad() ) {
                         obj.set_rot( corpse_item->get_rot() );
                     }
                 }
                 for( const flag_id &flg : entry.flags ) {
                     obj.set_flag( flg );
                 }
                 for( const fault_id &flt : entry.faults ) {
                     obj.faults.emplace( flt );
                 }
                 if( !you.backlog.empty() && you.backlog.front().id() == ACT_MULTIPLE_BUTCHER ) {
                     obj.set_var( "activity_var", you.name );
                 }
                 for( int i = 0; i != roll; ++i ) {
                     here.add_item_or_charges( you.pos(), obj );
                 }
             }
             you.add_msg_if_player( m_good, _( "You harvest: %s" ), drop->nname( roll ) );
         }
         practice++;
     }
     // 20% of the original corpse weight is not an item, but liquid gore
     monster_weight_remaining -= monster_weight / 5;
     // add the remaining unusable weight as rotting garbage
     if( monster_weight_remaining > 0 && action != butcher_type::BLEED ) {
         if( action == butcher_type::FIELD_DRESS ) {
             // 25% of the corpse weight is what's removed during field dressing
             monster_weight_remaining -= monster_weight * 3 / 4;
         } else if( action == butcher_type::SKIN ) {
             monster_weight_remaining -= monster_weight * 0.85;
         } else {
             // a carcass is 75% of the weight of the unmodified creature's weight
             if( ( corpse_item->has_flag( flag_FIELD_DRESS ) ||
                   corpse_item->has_flag( flag_FIELD_DRESS_FAILED ) ) &&
                 !corpse_item->has_flag( flag_QUARTERED ) ) {
                 monster_weight_remaining -= monster_weight / 4;
             } else if( corpse_item->has_flag( flag_QUARTERED ) ) {
                 monster_weight_remaining -= ( monster_weight - ( monster_weight * 3 / 4 / 4 ) );
             }
             if( corpse_item->has_flag( flag_SKINNED ) ) {
                 monster_weight_remaining -= monster_weight * 0.15;
             }
         }
         const itype_id &leftover_id = mt.harvest->leftovers;
         const int item_charges = monster_weight_remaining / to_gram( item::find_type(
                                      leftover_id )->weight );
         if( item_charges > 0 ) {
             item ruined_parts( leftover_id, calendar::turn );
             ruined_parts.set_mtype( &mt );
             ruined_parts.set_item_temperature( corpse_item->temperature );
             ruined_parts.set_rot( corpse_item->get_rot() );
             if( !you.backlog.empty() && you.backlog.front().id() == ACT_MULTIPLE_BUTCHER ) {
                 ruined_parts.set_var( "activity_var", you.name );
             }
             for( int i = 0; i < item_charges; ++i ) {
                 here.add_item_or_charges( you.pos(), ruined_parts );
             }
         }
     }
     if( action == butcher_type::DISSECT ) {
         you.practice( skill_firstaid, std::max( 0, practice ), mt.size + std::min( tool_quality, 3 ) + 2 );
         mt.families.practice_dissect( you );
     } else {
         you.practice( skill_survival, std::max( 0, practice ), std::max( mt.size - creature_size::medium,
                       0 ) + 4 );
     }
     // after this point, if there was a liquid handling from the harvest,
     // and the liquid handling was interrupted, then the activity was canceled,
     // therefore operations on this activity's targets and values may be invalidated.
     // reveal hidden items / hidden content
     if( action != butcher_type::FIELD_DRESS && action != butcher_type::SKIN &&
         action != butcher_type::BLEED ) {
         for( item *content : corpse_item->all_items_top( pocket_type::CONTAINER ) ) {
             if( ( roll_butchery_dissect( round( you.get_average_skill_level( skill_survival ) ), you.dex_cur,
                                          tool_quality ) + 10 ) * 5 > rng( 0, 100 ) ) {
                 //~ %1$s - item name, %2$s - monster name
                 you.add_msg_if_player( m_good, _( "You discover a %1$s in the %2$s!" ), content->tname(),
                                        corpse_item->get_mtype()->nname() );
                 here.add_item_or_charges( you.pos(), *content );
             } else if( content->is_bionic() ) {
                 here.spawn_item( you.pos(), itype_burnt_out_bionic, 1, 0, calendar::turn );
             }
         }
     }
     you.invalidate_crafting_inventory();
     return true;
 }
References _, ACT_MULTIPLE_BUTCHER, action, map::add_item_or_charges(), add_msg_debug, Character::add_msg_if_player(), item::all_items_top(), Character::backlog, BLEED, butcher_dissect_item(), butchery_dissect_skill_level(), butchery_dissect_yield_mult(), string_id< T >::c_str(), ceil(), CONTAINER, CORPSE, corpse_damage_effect(), itype::count_by_charges(), create_charge_items(), item::damage_level(), debugmsg, deliberate, Character::dex_cur, debugmode::DF_ACT_BUTCHER, DISMEMBER, DISSECT, mtype::dissect, drop_on_map(), item::dropped_from, translation::empty(), mtype::families, FIELD_DRESS, item::find_type(), flag_FIELD_DRESS, flag_FIELD_DRESS_FAILED, flag_GIBBED, flag_QUARTERED, flag_SKINNED, flag_UNDERFED, FULL, harvest_list::get_all(), Character::get_average_skill_level(), get_map(), item::get_mtype(), item::get_rot(), liquid_handler::handle_all_liquid(), mtype::harvest, harvest_drop_blood, harvest_drop_bone, harvest_drop_flesh, harvest_drop_offal, harvest_drop_skin, item::has_flag(), mtype::id, Character::invalidate_crafting_inventory(), string_id< T >::is_empty(), Character::is_npc(), string_id< T >::is_null(), itype_burnt_out_bionic, harvest_list::leftovers, LIQUID, m_bad, m_good, m_neutral, max(), Character::max_quality(), medium, harvest_list::message(), min(), Character::name, itype::nname(), mtype::nname(), string_id< itype >::NULL_ID(), int_id< T >::obj(), one_in(), itype::phase, PICKUP_RANGE, Creature::pos(), Creature::pos_bub(), Character::practice(), weakpoint_families::practice_dissect(), qual_BUTCHER, qual_CUT_FINE, QUICK, rng(), rng_float(), roll_butchery_dissect(), round(), item::set_item_temperature(), item::set_mtype(), item::set_rot(), item::set_var(), mtype::size, skill_firstaid, skill_survival, SKIN, map::spawn_item(), item::temperature, units::to_gram(), translation::translated(), calendar::turn, itype::weight, and mtype::weight.
Referenced by activity_handlers::butcher_finish().
butchery_quarter()
static void butchery_quarter (item * corpse_item, const Character & you) static
Definition at line 1226 of file activity_handlers.cpp.
 {
     corpse_item->set_flag( flag_QUARTERED );
     you.add_msg_if_player( m_good,
                            _( "You roughly slice the corpse of %s into four parts and set them aside." ),
                            corpse_item->get_mtype()->nname() );
     map &here = get_map();
     tripoint pos = you.pos();
     // 4 quarters (one exists, add 3, flag does the rest)
     for( int i = 1; i <= 3; i++ ) {
         here.add_item_or_charges( pos, *corpse_item, true );
     }
 }
References _, map::add_item_or_charges(), Character::add_msg_if_player(), flag_QUARTERED, get_map(), item::get_mtype(), m_good, mtype::nname(), Creature::pos(), math_opers::pos(), and item::set_flag().
Referenced by activity_handlers::butcher_finish().
check_butcher_dissect()
static bool check_butcher_dissect (const int roll) static
Definition at line 397 of file activity_handlers.cpp.
 {
     // Failure rates for dissection rolls
     // 100% at roll 0, 66% at roll 1, 50% at roll 2, 40% @ 3, 33% @ 4, 28% @ 5, ... , 16% @ 10
     // Roll is roughly a rng(0, -3 + 1st_aid + fine_cut_quality + 1/2 electronics + small_dex_bonus)
     // Roll is reduced by corpse damage level, but to no less then 0
     add_msg_debug( debugmode::DF_ACT_BUTCHER, "Roll = %i", roll );
     add_msg_debug( debugmode::DF_ACT_BUTCHER, "Failure chance = %f%%",
                    ( 10.0f / ( 10.0f + roll * 5.0f ) ) * 100.0f );
     const bool failed = x_in_y( 10, ( 10 + roll * 5 ) );
     return !failed;
 }
References add_msg_debug, debugmode::DF_ACT_BUTCHER, failed, and x_in_y().
Referenced by butcher_dissect_item().
cleanup_tiles()
template<typename fn > static void cleanup_tiles (std::unordered_set< tripoint_abs_ms > & tiles, fn & cleanup) static
Definition at line 3507 of file activity_handlers.cpp.
 {
     auto it = tiles.begin();
     map &here = get_map();
     while( it != tiles.end() ) {
         auto current = it++;
         const tripoint_bub_ms &tile_loc = here.bub_from_abs( *current );
         if( cleanup( tile_loc ) ) {
             tiles.erase( current );
         }
     }
 }
References map::bub_from_abs(), and get_map().
Referenced by perform_zone_activity_turn().
corpse_damage_effect()
static int corpse_damage_effect (int weight, const harvest_drop_type_id & entry_type, int damage_level) static
Definition at line 752 of file activity_handlers.cpp.
 {
     const float slight_damage = 0.9f;
     const float damage = 0.75f;
     const float high_damage = 0.5f;
     const int destroyed = 0;
     switch( damage_level ) {
         case 2:
             // "damaged"
             if( entry_type == harvest_drop_offal ) {
                 return std::round( weight * damage );
             }
             if( entry_type == harvest_drop_skin ) {
                 return std::round( weight * damage );
             }
             if( entry_type == harvest_drop_flesh ) {
                 return std::round( weight * slight_damage );
             }
             break;
         case 3:
             // "mangled"
             if( entry_type == harvest_drop_offal ) {
                 return destroyed;
             }
             if( entry_type == harvest_drop_skin ) {
                 return std::round( weight * high_damage );
             }
             if( entry_type == harvest_drop_bone ) {
                 return std::round( weight * slight_damage );
             }
             if( entry_type == harvest_drop_flesh ) {
                 return std::round( weight * damage );
             }
             break;
         case 4:
             // "pulped"
             if( entry_type == harvest_drop_offal ) {
                 return destroyed;
             }
             if( entry_type == harvest_drop_skin ) {
                 return destroyed;
             }
             if( entry_type == harvest_drop_bone ) {
                 return std::round( weight * damage );
             }
             if( entry_type == harvest_drop_flesh ) {
                 return std::round( weight * high_damage );
             }
             break;
         default:
             // "bruised" modifier is almost impossible to avoid; also includes no modifier (zero damage)
             break;
     }
     return weight;
 }
References harvest_drop_bone, harvest_drop_flesh, harvest_drop_offal, harvest_drop_skin, and round().
Referenced by butchery_drops_harvest().
create_charge_items()
static std::vector<item> create_charge_items (const itype * drop, int count, const harvest_entry & entry, const item * corpse_item, const Character & you) static
Definition at line 855 of file activity_handlers.cpp.
 {
     std::vector<item> objs;
     while( count > 0 ) {
         item obj( drop, calendar::turn, 1 );
         obj.charges = std::min( count, DEFAULT_TILE_VOLUME / obj.volume() );
         count -= obj.charges;
         if( obj.has_temperature() ) {
             obj.set_item_temperature( corpse_item->temperature );
             if( obj.goes_bad() ) {
                 obj.set_rot( corpse_item->get_rot() );
             }
         }
         for( const flag_id &flg : entry.flags ) {
             obj.set_flag( flg );
         }
         for( const fault_id &flt : entry.faults ) {
             obj.faults.emplace( flt );
         }
         if( !you.backlog.empty() && you.backlog.front().id() == ACT_MULTIPLE_BUTCHER ) {
             obj.set_var( "activity_var", you.name );
         }
         objs.push_back( obj );
     }
     return objs;
 }
References ACT_MULTIPLE_BUTCHER, Character::backlog, DEFAULT_TILE_VOLUME, harvest_entry::faults, harvest_entry::flags, item::get_rot(), min(), Character::name, int_id< T >::obj(), item::temperature, and calendar::turn.
Referenced by butchery_drops_harvest().
magic_train()
static bool magic_train (player_activity * act, Character * you) static
Definition at line 1944 of file activity_handlers.cpp.
 {
     if( !you ) {
         return false;
     }
     const spell_id &sp_id = spell_id( act->name );
     if( sp_id.is_valid() ) {
         const bool knows = you->magic->knows_spell( sp_id );
         if( knows ) {
             spell &studying = you->magic->get_spell( sp_id );
             const int expert_multiplier = act->values.empty() ? 0 : act->values[0];
             const int xp = roll_remainder( studying.exp_modifier( *you ) * expert_multiplier );
             studying.gain_exp( *you, xp );
             you->add_msg_player_or_npc( m_good, _( "You learn a little about the spell: %s" ),
                                         _( "<npcname> learns a little about the spell: %s" ), sp_id->name );
         } else {
             you->magic->learn_spell( act->name, *you );
             // you can decline to learn this spell , as it may lock you out of other magic.
             if( you->magic->knows_spell( sp_id ) ) {
                 you->add_msg_player_or_npc( m_good, _( "You learn %s." ),
                                             _( "<npcname> learns %s." ), sp_id->name.translated() );
             } else {
                 act->set_to_null();
             }
         }
         return true;
     }
     return false;
 }
References _, act, Character::add_msg_player_or_npc(), spell::exp_modifier(), spell::gain_exp(), string_id< T >::is_valid(), m_good, Character::magic, spell_type::name, roll_remainder(), and translation::translated().
operator-()
static constexpr I operator- (const repeat_type & lhs, const repeat_type & rhs) static constexpr
Definition at line 2276 of file activity_handlers.cpp.
 {
     return static_cast<I>( lhs ) - static_cast<I>( rhs );
 }
operator<=()
static constexpr bool operator<= (const I & lhs, const repeat_type & rhs) static constexpr
Definition at line 2271 of file activity_handlers.cpp.
 {
     return lhs <= static_cast<I>( rhs );
 }
operator>=()
static constexpr bool operator>= (const I & lhs, const repeat_type & rhs) static constexpr
Definition at line 2266 of file activity_handlers.cpp.
 {
     return lhs >= static_cast<I>( rhs );
 }
perform_zone_activity_turn()
static void perform_zone_activity_turn (Character * you, const zone_type_id & ztype, const std::function< bool(const tripoint_bub_ms &)> & tile_filter, const std::function< void(Character &you, const tripoint_bub_ms &)> & tile_action, const std::string & finished_msg) static
Definition at line 3522 of file activity_handlers.cpp.
 {
     const zone_manager &mgr = zone_manager::get_manager();
     map &here = get_map();
     const tripoint_abs_ms abspos = you->get_location();
     std::unordered_set<tripoint_abs_ms> unsorted_tiles = mgr.get_near( ztype, abspos );
     cleanup_tiles( unsorted_tiles, tile_filter );
     // sort remaining tiles by distance
     const std::vector<tripoint_abs_ms> &tiles =
         get_sorted_tiles_by_distance( abspos, unsorted_tiles );
     for( const tripoint_abs_ms &tile : tiles ) {
         const tripoint_bub_ms &tile_loc = here.bub_from_abs( tile );
         std::vector<tripoint_bub_ms> route =
             here.route( you->pos_bub(), tile_loc, you->get_pathfinding_settings(),
                         you->get_path_avoid() );
         if( route.size() > 1 ) {
             route.pop_back();
             you->set_destination( route, you->activity );
             you->activity.set_to_null();
             return;
         } else {
             // we are at destination already
             /* Perform action */
             tile_action( *you, tile_loc );
             if( you->get_moves() <= 0 ) {
                 return;
             }
         }
     }
     add_msg( m_info, finished_msg );
     you->activity.set_to_null();
 }
References Character::activity, add_msg(), map::bub_from_abs(), cleanup_tiles(), Creature::get_location(), zone_manager::get_manager(), get_map(), Creature::get_moves(), zone_manager::get_near(), Character::get_path_avoid(), Character::get_pathfinding_settings(), get_sorted_tiles_by_distance(), m_info, Creature::pos_bub(), map::route(), Character::set_destination(), and player_activity::set_to_null().
Referenced by activity_handlers::fertilize_plot_do_turn().
repair_item_finish()
void repair_item_finish (player_activity * act, Character * you, bool no_menu)
Definition at line 2385 of file activity_handlers.cpp.
 {
     const std::string iuse_name_string = act->get_str_value( 0, "repair_item" );
     repeat_type repeat = static_cast<repeat_type>( act->get_value( 0,
                          static_cast<int>( repeat_type::INIT ) ) );
     weldrig_hack w_hack;
     item_location *ploc = nullptr;
     if( !act->targets.empty() ) {
         ploc = act->targets.data();
     }
     item *main_tool = &( !w_hack.init( *act ) ?
                          ploc ?
                          **ploc : you->i_at( act->index ) : w_hack.get_item() );
     if( main_tool == nullptr ) {
         debugmsg( "Empty main tool for repair" );
         act->set_to_null();
         return;
     }
     item *used_tool = main_tool->get_usable_item( iuse_name_string );
     if( used_tool == nullptr ) {
         debugmsg( "Lost tool used for long repair" );
         act->set_to_null();
         return;
     }
     const use_function *use_fun = used_tool->get_use( iuse_name_string );
     // TODO: De-uglify this block. Something like get_use<iuse_actor_type>() maybe?
     const repair_item_actor *actor = dynamic_cast<const repair_item_actor *>
                                      ( use_fun->get_actor_ptr() );
     if( actor == nullptr ) {
         debugmsg( "iuse_actor type descriptor and actual type mismatch" );
         act->set_to_null();
         return;
     }
     // Valid Repeat choice and target, attempt repair.
     if( repeat != repeat_type::INIT && act->targets.size() >= 2 ) {
         item_location &fix_location = act->targets[1];
         // Remember our level: we want to stop retrying on level up
         const int old_level = you->get_skill_level( actor->used_skill );
         const repair_item_actor::attempt_hint attempt = actor->repair( *you, *used_tool,
                 fix_location, repeat == repeat_type::REFIT_ONCE || repeat == repeat_type::REFIT_FULL );
         // If the item being repaired has been destroyed stop further
         // processing in case the items being used for the repair was
         // contained by the item being repaired, which will result
         // in the tool being invalid
         if( attempt == repair_item_actor::AS_DESTROYED ) {
             act->set_to_null();
             return;
         }
         if( attempt != repair_item_actor::AS_CANT ) {
             if( ploc && ploc->where() == item_location::type::map ) {
                 used_tool->ammo_consume( used_tool->ammo_required(), ploc->position(), you );
             } else {
                 you->consume_charges( *used_tool, used_tool->ammo_required() );
             }
         }
         // TODO: Allow setting this in the actor
         // TODO: Don't use charges_to_use: welder has 50 charges per use, soldering iron has 1
         if( !used_tool->ammo_sufficient( you ) ) {
             you->add_msg_if_player( _( "Your %s ran out of charges." ), used_tool->tname() );
             act->set_to_null();
             return;
         }
         // Print message explaining why we stopped
         // But only if we didn't destroy the item (because then it's obvious)
         const bool destroyed = attempt == repair_item_actor::AS_DESTROYED;
         const bool cannot_continue_repair = attempt == repair_item_actor::AS_CANT || destroyed ||
                                             !actor->can_repair_target( *you, *fix_location, !destroyed, true );
         if( cannot_continue_repair ) {
             // Cannot continue to repair target, select another target.
             // **Warning**: as soon as the item is popped back, it is destroyed and can't be used anymore!
             act->targets.pop_back();
         }
         const bool event_happened = attempt == repair_item_actor::AS_FAILURE ||
                                     attempt == repair_item_actor::AS_SUCCESS ||
                                     old_level != static_cast<int>( you->get_skill_level( actor->used_skill ) );
         const bool can_refit = !destroyed && !cannot_continue_repair &&
                                fix_location->has_flag( flag_VARSIZE ) &&
                                !fix_location->has_flag( flag_FIT );
         const bool need_input =
             ( repeat == repeat_type::ONCE ) ||
             ( repeat == repeat_type::EVENT && event_happened ) ||
             ( repeat == repeat_type::FULL && cannot_continue_repair ) ||
             ( repeat == repeat_type::REFIT_ONCE ) ||
             ( repeat == repeat_type::REFIT_FULL && !can_refit );
         if( need_input ) {
             repeat = repeat_type::INIT;
             if( no_menu ) {
                 act->set_to_null();
                 return;
             }
         }
     }
     // Check tool is valid before we query target and Repeat choice.
     if( !actor->can_use_tool( *you, *used_tool, true ) ) {
         act->set_to_null();
         return;
     }
     // target selection and validation.
     while( act->targets.size() < 2 ) {
         item_location item_loc = game_menus::inv::repair( *you, actor, main_tool );
         if( item_loc == item_location::nowhere ) {
             you->add_msg_if_player( m_info, _( "Never mind." ) );
             act->set_to_null();
             return;
         }
         if( actor->can_repair_target( *you, *item_loc, true, true ) ) {
             act->targets.emplace_back( item_loc );
             repeat = repeat_type::INIT;
         }
     }
     const item &fix = *act->targets[1];
     const bool can_refit = fix.has_flag( flag_VARSIZE ) && !fix.has_flag( flag_FIT );
     if( repeat == repeat_type::INIT ) {
         const int level = you->get_skill_level( actor->used_skill );
         repair_item_actor::repair_type action_type = actor->default_action( fix, level );
         if( action_type == repair_item_actor::RT_NOTHING ) {
             you->add_msg_if_player( _( "You won't learn anything more by doing that." ) );
         }
         const std::pair<float, float> chance = actor->repair_chance( *you, fix, action_type );
         if( chance.first <= 0.0f ) {
             action_type = repair_item_actor::RT_PRACTICE;
         }
         std::string title = string_format( _( "%s %s\n" ),
                                            repair_item_actor::action_description( action_type ),
                                            fix.tname() );
         ammotype current_ammo;
         std::string ammo_name;
         if( used_tool->has_flag( flag_USE_UPS ) || used_tool->has_link_data() ) {
             ammo_name = _( "battery" );
             current_ammo = ammo_battery;
         } else if( used_tool->has_flag( flag_USES_BIONIC_POWER ) ) {
             ammo_name = _( "bionic power" );
         } else {
             if( used_tool->ammo_current().is_null() ) {
                 current_ammo = item_controller->find_template( used_tool->ammo_default() )->ammo->type;
             } else {
                 current_ammo = item_controller->find_template( used_tool->ammo_current() )->ammo->type;
             }
             ammo_name = item::nname( used_tool->ammo_current() );
         }
         int ammo_remaining = used_tool->ammo_remaining( you, true );
         std::set<itype_id> valid_entries = actor->get_valid_repair_materials( fix );
         const inventory &crafting_inv = you->crafting_inventory();
         std::function<bool( const item & )> filter;
         if( fix.is_filthy() ) {
             filter = []( const item & component ) {
                 return component.allow_crafting_component();
             };
         } else {
             filter = is_crafting_component;
         }
         std::vector<std::string> material_list;
         for( const auto &component_id : valid_entries ) {
             if( item::count_by_charges( component_id ) ) {
                 if( crafting_inv.has_charges( component_id, 1 ) ) {
                     material_list.push_back( string_format( _( "%s (%d)" ), item::nname( component_id ),
                                                             crafting_inv.charges_of( component_id ) ) );
                 }
             } else if( crafting_inv.has_amount( component_id, 1, false, filter ) ) {
                 material_list.push_back( string_format( _( "%s (%d)" ), item::nname( component_id ),
                                                         crafting_inv.amount_of( component_id, false ) ) );
             }
         }
         title += string_format( _( "Charges: <color_light_blue>%s/%s</color> %s (%s per use)\n" ),
                                 ammo_remaining, used_tool->ammo_capacity( current_ammo, true ),
                                 ammo_name,
                                 used_tool->ammo_required() );
         title += string_format( _( "Materials available: %s\n" ), string_join( material_list, ", " ) );
         title += string_format( _( "Skill used: <color_light_blue>%s (%s)</color>\n" ),
                                 actor->used_skill.obj().name(), level );
         title += string_format( _( "Success chance: <color_light_blue>%.1f</color>%%\n" ),
                                 100.0f * chance.first );
         title += string_format( _( "Damage chance: <color_light_blue>%.1f</color>%%" ),
                                 100.0f * chance.second );
         if( act->values.empty() ) {
             act->values.resize( 1 );
         }
         do {
             repeat = repeat_menu( title, repeat, can_refit );
             if( repeat == repeat_type::CANCEL ) {
                 act->set_to_null();
                 return;
             }
             act->values[0] = static_cast<int>( repeat );
             // BACK selected, redo target selection next.
             if( repeat == repeat_type::INIT ) {
                 you->activity.targets.pop_back();
                 return;
             }
             if( repeat == repeat_type::FULL && fix.damage() <= fix.degradation() && !can_refit ) {
                 const char *msg = fix.damage_level() > 0 ?
                                   _( "Your %s is repaired as much as possible, considering the degradation." ) :
                                   _( "Your %s is already fully repaired." );
                 you->add_msg_if_player( m_info, msg, fix.tname() );
                 repeat = repeat_type::INIT;
             }
         } while( repeat == repeat_type::INIT );
     }
     // Otherwise keep retrying
     act->moves_left = actor->move_cost;
 }
References _, act, repair_item_actor::action_description(), Character::activity, Character::add_msg_if_player(), ammo_battery, item::ammo_capacity(), item::ammo_consume(), item::ammo_current(), item::ammo_default(), item::ammo_remaining(), item::ammo_required(), item::ammo_sufficient(), inventory::amount_of(), repair_item_actor::AS_CANT, repair_item_actor::AS_DESTROYED, repair_item_actor::AS_FAILURE, repair_item_actor::AS_SUCCESS, repair_item_actor::can_repair_target(), repair_item_actor::can_use_tool(), CANCEL, inventory::charges_of(), Character::consume_charges(), item::count_by_charges(), Character::crafting_inventory(), item::damage(), item::damage_level(), debugmsg, repair_item_actor::default_action(), item::degradation(), EVENT, filter, flag_FIT, flag_USE_UPS, flag_USES_BIONIC_POWER, flag_VARSIZE, FULL, use_function::get_actor_ptr(), weldrig_hack::get_item(), Character::get_skill_level(), item::get_usable_item(), item::get_use(), repair_item_actor::get_valid_repair_materials(), visitable::has_amount(), read_only_visitable::has_charges(), item::has_flag(), item::has_link_data(), Character::i_at(), INIT, weldrig_hack::init(), is_crafting_component(), item::is_filthy(), string_id< T >::is_null(), item_controller, m_info, item_location::map, repair_item_actor::move_cost, Skill::name(), item::nname(), item_location::nowhere, string_id< T >::obj(), ONCE, REFIT_FULL, REFIT_ONCE, repair_item_actor::repair(), game_menus::inv::repair(), repair_item_actor::repair_chance(), repeat_menu(), repair_item_actor::RT_NOTHING, repair_item_actor::RT_PRACTICE, string_format(), string_join(), player_activity::targets, music::title, item::tname(), and repair_item_actor::used_skill.
Referenced by activity_handlers::repair_item_finish().
repeat_menu()
static repeat_type repeat_menu (const std::string & title, repeat_type last_selection, const bool can_refit) static
Definition at line 2281 of file activity_handlers.cpp.
 {
     uilist rmenu;
     rmenu.text = title;
     rmenu.addentry( static_cast<int>( repeat_type::ONCE ), true, '1',
                     can_refit ? _( "Attempt to refit or repair once" ) : _( "Attempt to repair once" ) );
     rmenu.addentry( static_cast<int>( repeat_type::FULL ), true, '2',
                     can_refit ? _( "Repeat until refitted and fully repaired" ) : _( "Repeat until fully repaired" ) );
     rmenu.addentry( static_cast<int>( repeat_type::EVENT ), true, '3',
                     can_refit ? _( "Refit or repair until success/failure/level up" ) :
                     _( "Repair until success/failure/level up" ) );
     rmenu.addentry( static_cast<int>( repeat_type::REFIT_ONCE ), can_refit, '4',
                     _( "Attempt to refit once" ) );
     rmenu.addentry( static_cast<int>( repeat_type::REFIT_FULL ), can_refit, '5',
                     _( "Repeat until refitted" ) );
     rmenu.addentry( static_cast<int>( repeat_type::INIT ), true, '6', _( "Back to item selection" ) );
     rmenu.selected = last_selection - repeat_type::ONCE;
     rmenu.query();
     if( rmenu.ret >= repeat_type::INIT && rmenu.ret <= repeat_type::REFIT_FULL ) {
         return static_cast<repeat_type>( rmenu.ret );
     }
     return repeat_type::CANCEL;
 }
References _, uilist::addentry(), CANCEL, EVENT, FULL, INIT, ONCE, uilist::query(), REFIT_FULL, REFIT_ONCE, uilist::ret, uilist::selected, uilist::text, and music::title.
Referenced by repair_item_finish().
rod_fish()
static void rod_fish (Character * you, const std::vector< monster * > & fishables) static
Definition at line 2880 of file activity_handlers.cpp.
 {
     map &here = get_map();
     //if the vector is empty (no fish around) the player is still given a small chance to get a (let us say it was hidden) fish
     if( fishables.empty() ) {
         const std::vector<mtype_id> fish_group = MonsterGroupManager::GetMonstersFromGroup(
                     GROUP_FISH, true );
         const mtype_id fish_mon = random_entry_ref( fish_group );
         here.add_item_or_charges( you->pos(), item::make_corpse( fish_mon, calendar::turn + rng( 0_turns,
                                   3_hours ) ) );
         you->add_msg_if_player( m_good, _( "You caught a %s." ), fish_mon.obj().nname() );
     } else {
         monster *chosen_fish = random_entry( fishables );
         chosen_fish->fish_population -= 1;
         if( chosen_fish->fish_population <= 0 ) {
             g->catch_a_monster( chosen_fish, you->pos(), you, 50_hours );
         } else {
             here.add_item_or_charges( you->pos(), item::make_corpse( chosen_fish->type->id,
                                       calendar::turn + rng( 0_turns,
                                               3_hours ) ) );
             you->add_msg_if_player( m_good, _( "You caught a %s." ), chosen_fish->type->nname() );
         }
     }
     for( item &elem : here.i_at( you->pos() ) ) {
         if( elem.is_corpse() && !elem.has_var( "activity_var" ) ) {
             elem.set_var( "activity_var", you->name );
         }
     }
 }
References _, map::add_item_or_charges(), Character::add_msg_if_player(), monster::fish_population, g, get_map(), MonsterGroupManager::GetMonstersFromGroup(), GROUP_FISH, map::i_at(), mtype::id, m_good, item::make_corpse(), Character::name, mtype::nname(), string_id< T >::obj(), Creature::pos(), random_entry(), random_entry_ref(), rng(), calendar::turn, and monster::type.
Referenced by activity_handlers::fish_do_turn().
roll_butchery_dissect()
static int roll_butchery_dissect (int skill_level, int dex, int tool_quality) static
Survival randomly increases butcher rolls Dexterity >8 randomly increases butcher rolls, slightly, <8 decreases
Definition at line 826 of file activity_handlers.cpp.
 {
     double skill_shift = 0.0;
     ///\EFFECT_SURVIVAL randomly increases butcher rolls
     skill_shift += rng_float( 0, skill_level - 3 );
     ///\EFFECT_DEX >8 randomly increases butcher rolls, slightly, <8 decreases
     skill_shift += rng_float( 0, dex - 8 ) / 4.0;
     if( tool_quality < 0 ) {
         skill_shift -= rng_float( 0, -tool_quality / 5.0 );
     } else {
         skill_shift += std::min( tool_quality, 4 );
     }
     return static_cast<int>( std::round( skill_shift ) );
 }
References min(), rng_float(), and round().
Referenced by activity_handlers::butcher_finish(), and butchery_drops_harvest().
set_up_butchery()
static void set_up_butchery (player_activity & act, Character & you, butcher_type action) static
Definition at line 429 of file activity_handlers.cpp.
 {
     const int factor = you.max_quality( action == butcher_type::DISSECT ? qual_CUT_FINE : qual_BUTCHER,
                                         PICKUP_RANGE );
     const item &corpse_item = *act.targets.back();
     const mtype &corpse = *corpse_item.get_mtype();
     if( action != butcher_type::DISSECT ) {
         if( factor == INT_MIN ) {
             you.add_msg_if_player( m_info,
                                    _( "None of your cutting tools are suitable for butchering." ) );
             act.set_to_null();
             return;
         } else if( factor < 0 && one_in( 3 ) ) {
             you.add_msg_if_player( m_bad,
                                    _( "You don't trust the quality of your tools, but carry on anyway." ) );
         }
     }
     if( action == butcher_type::DISSECT ) {
         switch( factor ) {
             case INT_MIN:
                 you.add_msg_if_player( m_info, _( "None of your tools are sharp and precise enough to do that." ) );
                 act.set_to_null();
                 return;
             case 1:
                 you.add_msg_if_player( m_info, _( "You could use a better tool, but this will do." ) );
                 break;
             case 2:
                 you.add_msg_if_player( m_info, _( "This tool is great, but you still would like a scalpel." ) );
                 break;
             case 3:
                 you.add_msg_if_player( m_info, _( "You dissect the corpse with a trusty scalpel." ) );
                 break;
             case 5:
                 you.add_msg_if_player( m_info,
                                        _( "You dissect the corpse with a sophisticated system of surgical grade scalpels." ) );
                 break;
         }
     }
     const std::pair<float, requirement_id> butchery_requirements =
         corpse.harvest->get_butchery_requirements().get_fastest_requirements( you.crafting_inventory(),
                 corpse.size, action );
     // Requirements for the various types
     const requirement_id butchery_requirement = butchery_requirements.second;
     if( !butchery_requirement->can_make_with_inventory(
             you.crafting_inventory( you.pos(), PICKUP_RANGE ), is_crafting_component ) ) {
         std::string popup_output = _( "You can't butcher this; you are missing some tools.\n" );
         for( const std::string &str : butchery_requirement->get_folded_components_list(
                  45, c_light_gray, you.crafting_inventory( you.pos(), PICKUP_RANGE ), is_crafting_component ) ) {
             popup_output += str + '\n';
         }
         for( const std::string &str : butchery_requirement->get_folded_tools_list(
                  45, c_light_gray, you.crafting_inventory( you.pos(), PICKUP_RANGE ) ) ) {
             popup_output += str + '\n';
         }
         act.set_to_null();
         popup( popup_output );
         return;
     }
     if( action == butcher_type::BLEED && ( corpse_item.has_flag( flag_BLED ) ||
                                            corpse_item.has_flag( flag_QUARTERED ) || corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ||
                                            corpse_item.has_flag( flag_FIELD_DRESS ) ) ) {
         you.add_msg_if_player( m_info, _( "This corpse has already been bled." ) );
         act.targets.pop_back();
         return;
     }
     if( action == butcher_type::DISSECT && ( corpse_item.has_flag( flag_QUARTERED ) ||
             corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) ) {
         you.add_msg_if_player( m_info,
                                _( "It would be futile to dissect this badly damaged corpse." ) );
         act.targets.pop_back();
         return;
     }
     if( action == butcher_type::FIELD_DRESS && ( corpse_item.has_flag( flag_FIELD_DRESS ) ||
             corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) ) {
         you.add_msg_if_player( m_info, _( "This corpse is already field dressed." ) );
         act.targets.pop_back();
         return;
     }
     if( action == butcher_type::SKIN && corpse_item.has_flag( flag_SKINNED ) ) {
         you.add_msg_if_player( m_info, _( "This corpse is already skinned." ) );
         act.targets.pop_back();
         return;
     }
     if( action == butcher_type::QUARTER ) {
         if( corpse.size == creature_size::tiny ) {
             you.add_msg_if_player( m_bad, _( "This corpse is too small to quarter without damaging." ),
                                    corpse.nname() );
             act.targets.pop_back();
             return;
         }
         if( corpse_item.has_flag( flag_QUARTERED ) ) {
             you.add_msg_if_player( m_bad, _( "This is already quartered." ), corpse.nname() );
             act.targets.pop_back();
             return;
         }
         if( !( corpse_item.has_flag( flag_FIELD_DRESS ) ||
                corpse_item.has_flag( flag_FIELD_DRESS_FAILED ) ) &&
             corpse_item.get_mtype()->harvest->has_entry_type( harvest_drop_offal ) ) {
             you.add_msg_if_player( m_bad, _( "You need to perform field dressing before quartering." ),
                                    corpse.nname() );
             act.targets.pop_back();
             return;
         }
     }
     const bool is_human = corpse.id == mtype_id::NULL_ID() || ( ( corpse.in_species( species_HUMAN ) ||
                           corpse.in_species( species_FERAL ) ) &&
                           !corpse.in_species( species_ZOMBIE ) );
     // applies to all butchery actions except for dissections
     if( is_human && action != butcher_type::DISSECT && !( you.has_flag( json_flag_CANNIBAL ) ||
             you.has_flag( json_flag_PSYCHOPATH ) || you.has_flag( json_flag_SAPIOVORE ) ) ) {
         //first determine if the butcherer has the dissect_humans proficiency.
         if( you.has_proficiency( proficiency_prof_dissect_humans ) ) {
             //if it's player doing the butchery, ask them first.
             if( you.is_avatar() ) {
                 if( query_yn(
                         _( "Really desecrate the mortal remains of a fellow human being by butchering them for meat?" ) ) ) {
                     //give the player a random message showing their disgust and cause morale penalty.
                     switch( rng( 1, 3 ) ) {
                         case 1:
                             you.add_msg_if_player( m_bad, _( "You clench your teeth at the prospect of this gruesome job." ) );
                             break;
                         case 2:
                             you.add_msg_if_player( m_bad, _( "This will haunt you in your dreams." ) );
                             break;
                         case 3:
                             you.add_msg_if_player( m_bad,
                                                    _( "You try to look away, but this gruesome image will stay on your mind for some time." ) );
                             break;
                     }
                     get_player_character().add_morale( MORALE_BUTCHER, -50, 0, 2_days, 3_hours );
                 } else {
                     //player has the dissect_humans prof, so they're familiar with dissection. reference this in their refusal to butcher
                     you.add_msg_if_player( m_good, _( "You were trained for autopsies, not butchery." ) );
                     act.targets.pop_back();
                     return;
                 }
             } else {
                 //if not the avatar, don't ask, just do it and suffer without comment
                 you.add_morale( MORALE_BUTCHER, -50, 0, 2_days, 3_hours );
             }
         } else {
             //this runs if the butcherer does NOT have prof_dissect_humans
             if( you.is_avatar() ) {
                 if( query_yn( _( "Would you dare desecrate the mortal remains of a fellow human being?" ) ) ) {
                     //random message and morale penalty
                     switch( rng( 1, 3 ) ) {
                         case 1:
                             you.add_msg_if_player( m_bad, _( "You clench your teeth at the prospect of this gruesome job." ) );
                             break;
                         case 2:
                             you.add_msg_if_player( m_bad, _( "This will haunt you in your dreams." ) );
                             break;
                         case 3:
                             you.add_msg_if_player( m_bad,
                                                    _( "You try to look away, but this gruesome image will stay on your mind for some time." ) );
                             break;
                     }
                     get_player_character().add_morale( MORALE_BUTCHER, -50, 0, 2_days, 3_hours );
                 } else {
                     //player doesn't have dissect_humans, so just give a regular refusal to mess with the corpse
                     you.add_msg_if_player( m_good, _( "It needs a coffin, not a knife." ) );
                     act.targets.pop_back();
                     return;
                 }
             } else {
                 //again, don't complain about it, or inform about it, just do it
                 you.add_morale( MORALE_BUTCHER, -50, 0, 2_days, 3_hours );
             }
         }
     }
     // applies to only dissections, so that dissect_humans training makes a difference.
     if( is_human && action == butcher_type::DISSECT && !( you.has_flag( json_flag_CANNIBAL ) ||
             you.has_flag( json_flag_PSYCHOPATH ) || you.has_flag( json_flag_SAPIOVORE ) ) ) {
         if( you.has_proficiency( proficiency_prof_dissect_humans ) ) {
             //you're either trained for this, densensitized, or both. doesn't bother you.
             if( you.is_avatar() ) {
                 //this is a dissection, and we are trained for dissection, so no morale penalty, and lighter flavor text.
                 switch( rng( 1, 3 ) ) {
                     case 1:
                         you.add_msg_if_player( m_good, _( "You grit your teeth and get to work." ) );
                         break;
                     case 2:
                         you.add_msg_if_player( m_good,
                                                _( "The task at hand is unpleasant, but you steel your nerves regardless." ) );
                         break;
                     case 3:
                         you.add_msg_if_player( m_good,
                                                _( "Hopefully whatever you can glean from this autopsy is worth the effort." ) );
                         break;
                 }
             }
             //if we're not the avatar, we aren't getting a morale penalty as usual, and no message, so nothing happens
         } else {
             //we don't have dissect_humans but are trying to dissect anyways.
             if( you.is_avatar() ) {
                 if( query_yn( _( "Really dissect the remains of a fellow human being?" ) ) ) {
                     //give us a message indicating we are dissecting without the stomach for it, but not actually butchering. lower morale penalty.
                     switch( rng( 1, 3 ) ) {
                         case 1:
                             you.add_msg_if_player( m_bad,
                                                    _( "This is nothing like dissecting a frog in biology class.  You feel sick inside." ) );
                             break;
                         case 2:
                             you.add_msg_if_player( m_bad, _( "You wonder how anyone manages to do this ghastly work." ) );
                             break;
                         case 3:
                             you.add_msg_if_player( m_bad,
                                                    _( "The grim nature of your task deeply upsets you, leaving you feeling disgusted with yourself." ) );
                             break;
                     }
                     get_player_character().add_morale( MORALE_BUTCHER, -40, 0, 1_days, 2_hours );
                 } else {
                     //standard refusal to butcher
                     you.add_msg_if_player( m_good, _( "It needs a coffin, not a knife." ) );
                     act.targets.pop_back();
                     return;
                 }
             } else {
                 //if we're not player and don't have dissect_humans, just add morale penalty.
                 you.add_morale( MORALE_BUTCHER, -40, 0, 1_days, 2_hours );
             }
         }
     }
     act.moves_left = butcher_time_to_cut( you, corpse_item, action ) * butchery_requirements.first;
     // We have a valid target, so preform the full finish function
     // instead of just selecting the next valid target
     act.index = false;
 }
References _, act, action, Character::add_morale(), Character::add_msg_if_player(), BLEED, butcher_time_to_cut(), c_light_gray, requirement_data::can_make_with_inventory(), corpse, Character::crafting_inventory(), DISSECT, FIELD_DRESS, flag_BLED, flag_FIELD_DRESS, flag_FIELD_DRESS_FAILED, flag_QUARTERED, flag_SKINNED, requirement_data::get_folded_components_list(), requirement_data::get_folded_tools_list(), item::get_mtype(), get_player_character(), mtype::harvest, harvest_drop_offal, harvest_list::has_entry_type(), item::has_flag(), Character::has_flag(), Character::has_proficiency(), Creature::is_avatar(), is_crafting_component(), json_flag_CANNIBAL, json_flag_PSYCHOPATH, json_flag_SAPIOVORE, m_bad, m_good, m_info, Character::max_quality(), MORALE_BUTCHER, string_id< mtype >::NULL_ID(), one_in(), PICKUP_RANGE, popup(), Creature::pos(), proficiency_prof_dissect_humans, qual_BUTCHER, qual_CUT_FINE, QUARTER, query_yn(), rng(), SKIN, species_FERAL, species_HUMAN, species_ZOMBIE, and tiny.
Referenced by activity_handlers::butcher_finish().
Variable Documentation
ACT_ADV_INVENTORY
const activity_id ACT_ADV_INVENTORY("ACT_ADV_INVENTORY") ("ACT_ADV_INVENTORY") static
ACT_ARMOR_LAYERS
const activity_id ACT_ARMOR_LAYERS("ACT_ARMOR_LAYERS") ("ACT_ARMOR_LAYERS") static
ACT_ATM
const activity_id ACT_ATM("ACT_ATM") ("ACT_ATM") static
ACT_BLEED
const activity_id ACT_BLEED("ACT_BLEED") ("ACT_BLEED") static
Referenced by activity_handlers::butcher_finish().
ACT_BUILD
const activity_id ACT_BUILD("ACT_BUILD") ("ACT_BUILD") static
ACT_BUTCHER
const activity_id ACT_BUTCHER("ACT_BUTCHER") ("ACT_BUTCHER") static
Referenced by activity_handlers::butcher_finish().
ACT_BUTCHER_FULL
const activity_id ACT_BUTCHER_FULL("ACT_BUTCHER_FULL") ("ACT_BUTCHER_FULL") static
Referenced by activity_handlers::butcher_finish().
ACT_CONSUME_DRINK_MENU
const activity_id ACT_CONSUME_DRINK_MENU("ACT_CONSUME_DRINK_MENU") ("ACT_CONSUME_DRINK_MENU") static
ACT_CONSUME_FOOD_MENU
const activity_id ACT_CONSUME_FOOD_MENU("ACT_CONSUME_FOOD_MENU") ("ACT_CONSUME_FOOD_MENU") static
ACT_CONSUME_MEDS_MENU
const activity_id ACT_CONSUME_MEDS_MENU("ACT_CONSUME_MEDS_MENU") ("ACT_CONSUME_MEDS_MENU") static
ACT_DISMEMBER
const activity_id ACT_DISMEMBER("ACT_DISMEMBER") ("ACT_DISMEMBER") static
Referenced by activity_handlers::butcher_finish().
ACT_DISSECT
const activity_id ACT_DISSECT("ACT_DISSECT") ("ACT_DISSECT") static
Referenced by activity_handlers::butcher_finish().
ACT_EAT_MENU
const activity_id ACT_EAT_MENU("ACT_EAT_MENU") ("ACT_EAT_MENU") static
ACT_FERTILIZE_PLOT
const activity_id ACT_FERTILIZE_PLOT("ACT_FERTILIZE_PLOT") ("ACT_FERTILIZE_PLOT") static
ACT_FETCH_REQUIRED
const activity_id ACT_FETCH_REQUIRED("ACT_FETCH_REQUIRED") ("ACT_FETCH_REQUIRED") static
ACT_FIELD_DRESS
const activity_id ACT_FIELD_DRESS("ACT_FIELD_DRESS") ("ACT_FIELD_DRESS") static
Referenced by activity_handlers::butcher_finish().
ACT_FILL_LIQUID
const activity_id ACT_FILL_LIQUID("ACT_FILL_LIQUID") ("ACT_FILL_LIQUID") static
ACT_FIND_MOUNT
const activity_id ACT_FIND_MOUNT("ACT_FIND_MOUNT") ("ACT_FIND_MOUNT") static
Referenced by activity_handlers::find_mount_do_turn().
ACT_FISH
const activity_id ACT_FISH("ACT_FISH") ("ACT_FISH") static
ACT_GAME
const activity_id ACT_GAME("ACT_GAME") ("ACT_GAME") static
ACT_GENERIC_GAME
const activity_id ACT_GENERIC_GAME("ACT_GENERIC_GAME") ("ACT_GENERIC_GAME") static
ACT_HAND_CRANK
const activity_id ACT_HAND_CRANK("ACT_HAND_CRANK") ("ACT_HAND_CRANK") static
ACT_HEATING
const activity_id ACT_HEATING("ACT_HEATING") ("ACT_HEATING") static
ACT_JACKHAMMER
const activity_id ACT_JACKHAMMER("ACT_JACKHAMMER") ("ACT_JACKHAMMER") static
ACT_MEND_ITEM
const activity_id ACT_MEND_ITEM("ACT_MEND_ITEM") ("ACT_MEND_ITEM") static
ACT_MOVE_LOOT
const activity_id ACT_MOVE_LOOT("ACT_MOVE_LOOT") ("ACT_MOVE_LOOT") static
ACT_MULTIPLE_BUTCHER
const activity_id ACT_MULTIPLE_BUTCHER("ACT_MULTIPLE_BUTCHER") ("ACT_MULTIPLE_BUTCHER") static
Referenced by butchery_drops_harvest(), and create_charge_items().
ACT_MULTIPLE_CHOP_PLANKS
const activity_id ACT_MULTIPLE_CHOP_PLANKS("ACT_MULTIPLE_CHOP_PLANKS") ("ACT_MULTIPLE_CHOP_PLANKS") static
ACT_MULTIPLE_CHOP_TREES
const activity_id ACT_MULTIPLE_CHOP_TREES("ACT_MULTIPLE_CHOP_TREES") ("ACT_MULTIPLE_CHOP_TREES") static
ACT_MULTIPLE_CONSTRUCTION
const activity_id ACT_MULTIPLE_CONSTRUCTION("ACT_MULTIPLE_CONSTRUCTION") ("ACT_MULTIPLE_CONSTRUCTION") static
ACT_MULTIPLE_CRAFT
const activity_id ACT_MULTIPLE_CRAFT("ACT_MULTIPLE_CRAFT") ("ACT_MULTIPLE_CRAFT") static
ACT_MULTIPLE_DIS
const activity_id ACT_MULTIPLE_DIS("ACT_MULTIPLE_DIS") ("ACT_MULTIPLE_DIS") static
ACT_MULTIPLE_FARM
const activity_id ACT_MULTIPLE_FARM("ACT_MULTIPLE_FARM") ("ACT_MULTIPLE_FARM") static
ACT_MULTIPLE_FISH
const activity_id ACT_MULTIPLE_FISH("ACT_MULTIPLE_FISH") ("ACT_MULTIPLE_FISH") static
Referenced by activity_handlers::fish_finish().
ACT_MULTIPLE_MINE
const activity_id ACT_MULTIPLE_MINE("ACT_MULTIPLE_MINE") ("ACT_MULTIPLE_MINE") static
ACT_MULTIPLE_MOP
const activity_id ACT_MULTIPLE_MOP("ACT_MULTIPLE_MOP") ("ACT_MULTIPLE_MOP") static
ACT_MULTIPLE_READ
const activity_id ACT_MULTIPLE_READ("ACT_MULTIPLE_READ") ("ACT_MULTIPLE_READ") static
ACT_OPERATION
const activity_id ACT_OPERATION("ACT_OPERATION") ("ACT_OPERATION") static
ACT_PICKAXE
const activity_id ACT_PICKAXE("ACT_PICKAXE") ("ACT_PICKAXE") static
ACT_PLANT_SEED
const activity_id ACT_PLANT_SEED("ACT_PLANT_SEED") ("ACT_PLANT_SEED") static
ACT_PULL_CREATURE
const activity_id ACT_PULL_CREATURE("ACT_PULL_CREATURE") ("ACT_PULL_CREATURE") static
ACT_PULP
const activity_id ACT_PULP("ACT_PULP") ("ACT_PULP") static
ACT_QUARTER
const activity_id ACT_QUARTER("ACT_QUARTER") ("ACT_QUARTER") static
Referenced by activity_handlers::butcher_finish().
ACT_REPAIR_ITEM
const activity_id ACT_REPAIR_ITEM("ACT_REPAIR_ITEM") ("ACT_REPAIR_ITEM") static
ACT_ROBOT_CONTROL
const activity_id ACT_ROBOT_CONTROL("ACT_ROBOT_CONTROL") ("ACT_ROBOT_CONTROL") static
ACT_SKIN
const activity_id ACT_SKIN("ACT_SKIN") ("ACT_SKIN") static
Referenced by activity_handlers::butcher_finish().
ACT_SOCIALIZE
const activity_id ACT_SOCIALIZE("ACT_SOCIALIZE") ("ACT_SOCIALIZE") static
ACT_SPELLCASTING
const activity_id ACT_SPELLCASTING("ACT_SPELLCASTING") ("ACT_SPELLCASTING") static
ACT_START_ENGINES
const activity_id ACT_START_ENGINES("ACT_START_ENGINES") ("ACT_START_ENGINES") static
ACT_START_FIRE
const activity_id ACT_START_FIRE("ACT_START_FIRE") ("ACT_START_FIRE") static
ACT_STUDY_SPELL
const activity_id ACT_STUDY_SPELL("ACT_STUDY_SPELL") ("ACT_STUDY_SPELL") static
ACT_TIDY_UP
const activity_id ACT_TIDY_UP("ACT_TIDY_UP") ("ACT_TIDY_UP") static
Referenced by activity_handlers::fish_finish().
ACT_TOOLMOD_ADD
const activity_id ACT_TOOLMOD_ADD("ACT_TOOLMOD_ADD") ("ACT_TOOLMOD_ADD") static
ACT_TRAIN
const activity_id ACT_TRAIN("ACT_TRAIN") ("ACT_TRAIN") static
ACT_TRAIN_TEACHER
const activity_id ACT_TRAIN_TEACHER("ACT_TRAIN_TEACHER") ("ACT_TRAIN_TEACHER") static
Referenced by activity_handlers::train_finish().
ACT_TRAVELLING
const activity_id ACT_TRAVELLING("ACT_TRAVELLING") ("ACT_TRAVELLING") static
Referenced by activity_handlers::travel_do_turn().
ACT_TREE_COMMUNION
const activity_id ACT_TREE_COMMUNION("ACT_TREE_COMMUNION") ("ACT_TREE_COMMUNION") static
ACT_VEHICLE
const activity_id ACT_VEHICLE("ACT_VEHICLE") ("ACT_VEHICLE") static
ACT_VEHICLE_DECONSTRUCTION
const activity_id ACT_VEHICLE_DECONSTRUCTION("ACT_VEHICLE_DECONSTRUCTION") ("ACT_VEHICLE_DECONSTRUCTION") static
ACT_VEHICLE_REPAIR
const activity_id ACT_VEHICLE_REPAIR("ACT_VEHICLE_REPAIR") ("ACT_VEHICLE_REPAIR") static
ACT_VIBE
const activity_id ACT_VIBE("ACT_VIBE") ("ACT_VIBE") static
ACT_VIEW_RECIPE
const activity_id ACT_VIEW_RECIPE("ACT_VIEW_RECIPE") ("ACT_VIEW_RECIPE") static
ACT_WAIT
const activity_id ACT_WAIT("ACT_WAIT") ("ACT_WAIT") static
ACT_WAIT_NPC
const activity_id ACT_WAIT_NPC("ACT_WAIT_NPC") ("ACT_WAIT_NPC") static
ACT_WAIT_STAMINA
const activity_id ACT_WAIT_STAMINA("ACT_WAIT_STAMINA") ("ACT_WAIT_STAMINA") static
ACT_WAIT_WEATHER
const activity_id ACT_WAIT_WEATHER("ACT_WAIT_WEATHER") ("ACT_WAIT_WEATHER") static
ammo_battery
const ammotype ammo_battery("battery") ("battery") static
Referenced by weldrig_hack::get_item(), activity_handlers::hand_crank_do_turn(), and repair_item_finish().
bio_painkiller
const bionic_id bio_painkiller("bio_painkiller") ("bio_painkiller") static
Referenced by activity_handlers::operation_do_turn().
damage_acid
const damage_type_id damage_acid("acid") ("acid") static
Referenced by activity_handlers::pulp_do_turn().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by activity_handlers::pulp_do_turn().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by activity_handlers::pulp_do_turn().
damage_stab
const damage_type_id damage_stab("stab") ("stab") static
Referenced by activity_handlers::pulp_do_turn().
effect_asocial_dissatisfied
const efftype_id effect_asocial_dissatisfied("asocial_dissatisfied") ("asocial_dissatisfied") static
Referenced by activity_handlers::tree_communion_do_turn().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by activity_handlers::operation_do_turn().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by activity_handlers::operation_do_turn().
effect_controlled
const efftype_id effect_controlled("controlled") ("controlled") static
Referenced by activity_handlers::find_mount_do_turn().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by activity_handlers::operation_do_turn().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by activity_handlers::robot_control_finish().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by activity_handlers::operation_do_turn().
effect_social_dissatisfied
const efftype_id effect_social_dissatisfied("social_dissatisfied") ("social_dissatisfied") static
Referenced by activity_handlers::tree_communion_do_turn().
effect_social_satisfied
const efftype_id effect_social_satisfied("social_satisfied") ("social_satisfied") static
Referenced by activity_handlers::tree_communion_do_turn().
effect_under_operation
const efftype_id effect_under_operation("under_operation") ("under_operation") static
Referenced by activity_handlers::operation_do_turn(), and activity_handlers::operation_finish().
furn_f_compost_empty
const furn_str_id furn_f_compost_empty("f_compost_empty") ("f_compost_empty") static
Referenced by activity_handlers::fill_liquid_do_turn().
furn_f_compost_full
const furn_str_id furn_f_compost_full("f_compost_full") ("f_compost_full") static
Referenced by activity_handlers::fill_liquid_do_turn().
furn_f_fvat_empty
const furn_str_id furn_f_fvat_empty("f_fvat_empty") ("f_fvat_empty") static
Referenced by activity_handlers::fill_liquid_do_turn().
furn_f_fvat_wood_empty
const furn_str_id furn_f_fvat_wood_empty("f_fvat_wood_empty") ("f_fvat_wood_empty") static
Referenced by activity_handlers::fill_liquid_do_turn().
furn_f_fvat_wood_full
const furn_str_id furn_f_fvat_wood_full("f_fvat_wood_full") ("f_fvat_wood_full") static
Referenced by activity_handlers::fill_liquid_do_turn().
furn_f_plant_seed
const furn_str_id furn_f_plant_seed("f_plant_seed") ("f_plant_seed") static
Referenced by activity_handlers::plant_seed_finish().
GROUP_FISH
const mongroup_id GROUP_FISH("GROUP_FISH") ("GROUP_FISH") static
Referenced by rod_fish().
harvest_drop_blood
const harvest_drop_type_id harvest_drop_blood("blood") ("blood") static
Referenced by butchery_drops_harvest().
harvest_drop_bone
const harvest_drop_type_id harvest_drop_bone("bone") ("bone") static
Referenced by butchery_drops_harvest(), and corpse_damage_effect().
harvest_drop_flesh
const harvest_drop_type_id harvest_drop_flesh("flesh") ("flesh") static
Referenced by butchery_drops_harvest(), and corpse_damage_effect().
harvest_drop_offal
const harvest_drop_type_id harvest_drop_offal("offal") ("offal") static
Referenced by butchery_drops_harvest(), corpse_damage_effect(), and set_up_butchery().
harvest_drop_skin
const harvest_drop_type_id harvest_drop_skin("skin") ("skin") static
Referenced by butchery_drops_harvest(), and corpse_damage_effect().
itype_animal
const itype_id itype_animal("animal") ("animal") static
Referenced by activity_handlers::start_engines_finish().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by weldrig_hack::get_item(), and activity_handlers::hand_crank_do_turn().
itype_burnt_out_bionic
const itype_id itype_burnt_out_bionic("burnt_out_bionic") ("burnt_out_bionic") static
Referenced by butcher_dissect_item(), and butchery_drops_harvest().
itype_muscle
const itype_id itype_muscle("muscle") ("muscle") static
Referenced by activity_handlers::start_engines_finish().
itype_pseudo_magazine
const itype_id itype_pseudo_magazine("pseudo_magazine") ("pseudo_magazine") static
Referenced by weldrig_hack::get_item().
json_flag_ASOCIAL1
const json_character_flag json_flag_ASOCIAL1("ASOCIAL1") ("ASOCIAL1") static
Referenced by activity_handlers::tree_communion_do_turn().
json_flag_ASOCIAL2
const json_character_flag json_flag_ASOCIAL2("ASOCIAL2") ("ASOCIAL2") static
Referenced by activity_handlers::tree_communion_do_turn().
json_flag_CANNIBAL
const json_character_flag json_flag_CANNIBAL("CANNIBAL") ("CANNIBAL") static
Referenced by set_up_butchery().
json_flag_PAIN_IMMUNE
const json_character_flag json_flag_PAIN_IMMUNE("PAIN_IMMUNE") ("PAIN_IMMUNE") static
Referenced by activity_handlers::operation_do_turn().
json_flag_PSYCHOPATH
const json_character_flag json_flag_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by set_up_butchery().
json_flag_SAPIOVORE
const json_character_flag json_flag_SAPIOVORE("SAPIOVORE") ("SAPIOVORE") static
Referenced by set_up_butchery().
json_flag_SILENT_SPELL
const json_character_flag json_flag_SILENT_SPELL("SILENT_SPELL") ("SILENT_SPELL") static
Referenced by activity_handlers::spellcasting_finish().
json_flag_SOCIAL1
const json_character_flag json_flag_SOCIAL1("SOCIAL1") ("SOCIAL1") static
Referenced by activity_handlers::tree_communion_do_turn().
json_flag_SOCIAL2
const json_character_flag json_flag_SOCIAL2("SOCIAL2") ("SOCIAL2") static
Referenced by activity_handlers::tree_communion_do_turn().
proficiency_prof_dissect_humans
const proficiency_id proficiency_prof_dissect_humans("prof_dissect_humans") ("prof_dissect_humans") static
Referenced by set_up_butchery().
qual_BUTCHER
const quality_id qual_BUTCHER("BUTCHER") ("BUTCHER") static
Referenced by activity_handlers::butcher_finish(), butcher_time_to_cut(), butchery_drops_harvest(), and set_up_butchery().
qual_CUT_FINE
const quality_id qual_CUT_FINE("CUT_FINE") ("CUT_FINE") static
Referenced by butcher_time_to_cut(), butchery_drops_harvest(), and set_up_butchery().
qual_FISHING_ROD
const quality_id qual_FISHING_ROD("FISHING_ROD") ("FISHING_ROD") static
Referenced by activity_handlers::fish_do_turn().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by activity_handlers::robot_control_finish().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by butchery_drops_harvest().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by activity_handlers::butcher_finish(), butchery_dissect_skill_level(), butchery_drops_harvest(), activity_handlers::fish_do_turn(), activity_handlers::pulp_do_turn(), and activity_handlers::start_fire_finish().
species_FERAL
const species_id species_FERAL("FERAL") ("FERAL") static
Referenced by set_up_butchery().
species_HUMAN
const species_id species_HUMAN("HUMAN") ("HUMAN") static
Referenced by set_up_butchery().
species_ZOMBIE
const species_id species_ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by set_up_butchery().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by activity_handlers::plant_seed_finish().
ter_t_tree
const ter_str_id ter_t_tree("t_tree") ("t_tree") static
Referenced by activity_handlers::pickaxe_finish().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by activity_handlers::build_do_turn().
trait_SPIRITUAL
const trait_id trait_SPIRITUAL("SPIRITUAL") ("SPIRITUAL") static
Referenced by activity_handlers::tree_communion_do_turn().
trait_STOCKY_TROGLO
const trait_id trait_STOCKY_TROGLO("STOCKY_TROGLO") ("STOCKY_TROGLO") static
Referenced by activity_handlers::pickaxe_finish().
zone_type_FARM_PLOT
const zone_type_id zone_type_FARM_PLOT("FARM_PLOT") ("FARM_PLOT") static
Referenced by activity_handlers::fertilize_plot_do_turn().