Cataclysm DDA: src/activity_actor.h File Reference
activity_actor.h File Reference
#include <memory>
#include <string>
#include <unordered_map>
#include "activity_type.h"
#include "clone_ptr.h"
#include "type_id.h"
Classes
class activity_actor
Namespaces
activity_actors
Macros
#define CATA_SRC_ACTIVITY_ACTOR_H
Functions
void serialize (const cata::clone_ptr< activity_actor > &actor, JsonOut &jsout)
void deserialize (cata::clone_ptr< activity_actor > &actor, const JsonValue &jsin)
Macro Definition Documentation
CATA_SRC_ACTIVITY_ACTOR_H
#define CATA_SRC_ACTIVITY_ACTOR_H
Definition at line 3 of file activity_actor.h.
Function Documentation
deserialize()
void deserialize (cata::clone_ptr< activity_actor > & actor, const JsonValue & jsin)
Definition at line 7778 of file activity_actor.cpp.
 {
     if( jsin.test_null() ) {
         actor = nullptr;
     } else {
         JsonObject data = jsin.get_object();
         if( data.has_member( "actor_data" ) ) {
             activity_id actor_type;
             data.read( "actor_type", actor_type );
             auto deserializer = activity_actors::deserialize_functions.find( actor_type );
             if( deserializer != activity_actors::deserialize_functions.end() ) {
                 JsonValue jv = data.get_member( "actor_data" );
                 actor = deserializer->second( jv );
             } else {
                 debugmsg( "Failed to find activity actor deserializer for type \"%s\"", actor_type.c_str() );
                 actor = nullptr;
             }
         } else {
             debugmsg( "Failed to load activity actor" );
             actor = nullptr;
         }
     }
 }
References string_id< T >::c_str(), debugmsg, activity_actors::deserialize_functions, keycode::end, JsonObject::get_member(), JsonValue::get_object(), JsonObject::has_member(), JsonObject::read(), and JsonValue::test_null().
Referenced by options_manager::load(), and auto_pickup::player_settings::load().
serialize()
void serialize (const cata::clone_ptr< activity_actor > & actor, JsonOut & jsout)
Definition at line 7764 of file activity_actor.cpp.
 {
     if( !actor ) {
         jsout.write_null();
     } else {
         jsout.start_object();
         jsout.member( "actor_type", actor->get_type() );
         jsout.member( "actor_data", *actor );
         jsout.end_object();
     }
 }
References JsonOut::end_object(), activity_actor::get_type(), JsonOut::member(), JsonOut::start_object(), and JsonOut::write_null().
Referenced by edit_json(), activity_handlers::fill_liquid_do_turn(), options_manager::save(), auto_pickup::player_settings::save(), and serialize_liquid_source().