Cataclysm DDA: src/advanced_inv.cpp File Reference
advanced_inv.cpp File Reference
#include "advanced_inv.h"
#include <algorithm>
#include <climits>
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <initializer_list>
#include <iterator>
#include <list>
#include <memory>
#include <optional>
#include <string>
#include <tuple>
#include <unordered_set>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "activity_type.h"
#include "advanced_inv_listitem.h"
#include "advanced_inv_pagination.h"
#include "auto_pickup.h"
#include "avatar.h"
#include "calendar.h"
#include "cata_assert.h"
#include "cata_scope_helpers.h"
#include "catacharset.h"
#include "character.h"
#include "color.h"
#include "coordinates.h"
#include "debug.h"
#include "enums.h"
#include "game.h"
#include "game_constants.h"
#include "input.h"
#include "input_context.h"
#include "input_enums.h"
#include "inventory.h"
#include "inventory_ui.h"
#include "item.h"
#include "item_category.h"
#include "item_contents.h"
#include "item_location.h"
#include "localized_comparator.h"
#include "map.h"
#include "messages.h"
#include "options.h"
#include "output.h"
#include "panels.h"
#include "pimpl.h"
#include "player_activity.h"
#include "point.h"
#include "popup.h"
#include "ret_val.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "units.h"
#include "units_utility.h"
#include "vehicle.h"
Classes
struct advanced_inv_sorter
class query_destination_callback
Namespaces
io
anonymous_namespace{advanced_inv.cpp}
Typedefs
using move_all_entry = std::pair< std::pair< int, int >, drop_or_stash_item_info >
Functions
template<>
std::string io::enum_to_string< aim_exit > (const aim_exit v)
template<>
std::string io::enum_to_string< aim_entry > (const aim_entry v)
void create_advanced_inv ()
void kill_advanced_inv ()
void temp_hide_advanced_inv ()
void cancel_aim_processing ()
Cancels ongoing move all action.
Variables
static const activity_id ACT_ADV_INVENTORY ("ACT_ADV_INVENTORY")
static const flag_id json_flag_NO_RELOAD ("NO_RELOAD")
static const flag_id json_flag_NO_UNLOAD ("NO_UNLOAD")
std::unique_ptr< advanced_inventory > anonymous_namespace{advanced_inv.cpp}::advinv
Typedef Documentation
move_all_entry
using move_all_entry = std::pair<std::pair<int, int>, drop_or_stash_item_info>
Definition at line 76 of file advanced_inv.cpp.
Function Documentation
cancel_aim_processing()
void cancel_aim_processing ()
Cancels ongoing move all action.
TODO: Make this not needed.
Definition at line 2375 of file advanced_inv.cpp.
 {
     uistate.transfer_save.re_enter_move_all = aim_entry::START;
     uistate.transfer_save.aim_all_location = AIM_AROUND_BEGIN;
     uistate.transfer_save.exit_code = aim_exit::none;
 }
References advanced_inv_save_state::aim_all_location, AIM_AROUND_BEGIN, advanced_inv_save_state::exit_code, none, advanced_inv_save_state::re_enter_move_all, START, uistatedata::transfer_save, and uistate.
Referenced by pickup_activity_actor::do_turn(), kill_advanced_inv(), and advanced_inventory::temp_hide().
create_advanced_inv()
void create_advanced_inv ()
Definition at line 119 of file advanced_inv.cpp.
 {
     if( !advinv ) {
         advinv = std::make_unique<advanced_inventory>();
     }
     advinv->display();
     // keep the UI and its ui_adaptor running if we're returning
     if( uistate.transfer_save.exit_code != aim_exit::re_entry || get_avatar().activity.is_null() ) {
         kill_advanced_inv();
     }
 }
References anonymous_namespace{advanced_inv.cpp}::advinv, advanced_inv_save_state::exit_code, get_avatar(), kill_advanced_inv(), re_entry, uistatedata::transfer_save, and uistate.
Referenced by activity_handlers::adv_inventory_do_turn(), and game::do_regular_action().
kill_advanced_inv()
void kill_advanced_inv ()
Definition at line 131 of file advanced_inv.cpp.
 {
     advinv.reset();
     cancel_aim_processing();
 }
References anonymous_namespace{advanced_inv.cpp}::advinv, and cancel_aim_processing().
Referenced by create_advanced_inv().
temp_hide_advanced_inv()
void temp_hide_advanced_inv ()
Definition at line 137 of file advanced_inv.cpp.
 {
     if( advinv ) {
         advinv->temp_hide();
     }
 }
References anonymous_namespace{advanced_inv.cpp}::advinv.
Referenced by choose_direction(), and choose_direction_rel_ms().
Variable Documentation
ACT_ADV_INVENTORY
const activity_id ACT_ADV_INVENTORY("ACT_ADV_INVENTORY") ("ACT_ADV_INVENTORY") static
Referenced by advanced_inventory::action_examine(), and advanced_inventory::do_return_entry().
json_flag_NO_RELOAD
const flag_id json_flag_NO_RELOAD("NO_RELOAD") ("NO_RELOAD") static
Referenced by advanced_inventory::action_move_item(), and advanced_inventory::move_all_items().
json_flag_NO_UNLOAD
const flag_id json_flag_NO_UNLOAD("NO_UNLOAD") ("NO_UNLOAD") static
Referenced by advanced_inventory::action_move_item(), and advanced_inventory::move_all_items().