Cataclysm DDA: src/advanced_inv.h File Reference
advanced_inv.h File Reference
#include <array>
#include <memory>
#include <string>
#include <vector>
#include "advanced_inv_area.h"
#include "advanced_inv_pane.h"
#include "cursesdef.h"
Classes
class advanced_inventory
Macros
#define CATA_SRC_ADVANCED_INV_H
Functions
void create_advanced_inv ()
void cancel_aim_processing ()
Cancels ongoing move all action.
Macro Definition Documentation
CATA_SRC_ADVANCED_INV_H
#define CATA_SRC_ADVANCED_INV_H
Definition at line 3 of file advanced_inv.h.
Function Documentation
cancel_aim_processing()
void cancel_aim_processing ()
Cancels ongoing move all action.
TODO: Make this not needed.
Definition at line 2375 of file advanced_inv.cpp.
 {
     uistate.transfer_save.re_enter_move_all = aim_entry::START;
     uistate.transfer_save.aim_all_location = AIM_AROUND_BEGIN;
     uistate.transfer_save.exit_code = aim_exit::none;
 }
References advanced_inv_save_state::aim_all_location, AIM_AROUND_BEGIN, advanced_inv_save_state::exit_code, none, advanced_inv_save_state::re_enter_move_all, START, uistatedata::transfer_save, and uistate.
Referenced by pickup_activity_actor::do_turn(), kill_advanced_inv(), and advanced_inventory::temp_hide().
create_advanced_inv()
void create_advanced_inv ()
Definition at line 119 of file advanced_inv.cpp.
 {
     if( !advinv ) {
         advinv = std::make_unique<advanced_inventory>();
     }
     advinv->display();
     // keep the UI and its ui_adaptor running if we're returning
     if( uistate.transfer_save.exit_code != aim_exit::re_entry || get_avatar().activity.is_null() ) {
         kill_advanced_inv();
     }
 }
References anonymous_namespace{advanced_inv.cpp}::advinv, advanced_inv_save_state::exit_code, get_avatar(), kill_advanced_inv(), re_entry, uistatedata::transfer_save, and uistate.
Referenced by activity_handlers::adv_inventory_do_turn(), and game::do_regular_action().