Cataclysm DDA: src/advanced_inv_pane.cpp File Reference
advanced_inv_pane.cpp File Reference
#include "advanced_inv_pane.h"
#include <cstddef>
#include <iterator>
#include <list>
#include <memory>
#include <string>
#include <vector>
#include "advanced_inv_area.h"
#include "advanced_inv_pagination.h"
#include "avatar.h"
#include "cata_assert.h"
#include "character.h"
#include "character_attire.h"
#include "flag.h"
#include "item.h"
#include "item_search.h"
#include "make_static.h"
#include "map.h"
#include "map_selector.h"
#include "options.h"
#include "pocket_type.h"
#include "type_id.h"
#include "uistate.h"
#include "units.h"
#include "vehicle.h"
#include "vehicle_selector.h"
Functions
static std::vector< std::vector< item_location > > item_list_to_stack (const item_location &parent, std::list< item * > item_list)
converts a raw list of items to "stacks" - items that are not count_by_charges that otherwise stack go into one stack
Function Documentation
item_list_to_stack()
static std::vector<std::vector<item_location> > item_list_to_stack (const item_location & parent, std::list< item * > item_list) static
converts a raw list of items to "stacks" - items that are not count_by_charges that otherwise stack go into one stack
Definition at line 115 of file advanced_inv_pane.cpp.
 {
     std::vector<std::vector<item_location>> ret;
     for( auto iter_outer = item_list.begin(); iter_outer != item_list.end(); ++iter_outer ) {
         std::vector<item_location> item_stack( { item_location( parent, *iter_outer ) } );
         for( auto iter_inner = std::next( iter_outer ); iter_inner != item_list.end(); ) {
             if( ( *iter_outer )->display_stacked_with( **iter_inner ) ) {
                 item_stack.emplace_back( parent, *iter_inner );
                 iter_inner = item_list.erase( iter_inner );
             } else {
                 ++iter_inner;
             }
         }
         ret.push_back( item_stack );
     }
     return ret;
 }
References item_stack::erase(), and cata::hash64_detail::ret.
Referenced by advanced_inventory_pane::add_items_from_area(), avatar::get_AIM_inventory(), and outfit::get_AIM_inventory().