Cataclysm DDA: src/ammo_effect.cpp File Reference
ammo_effect.cpp File Reference
#include "ammo_effect.h"
#include <set>
#include "debug.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "generic_factory.h"
#include "init.h"
Functions
generic_factory< ammo_effect > & get_all_ammo_effects ()
Variables
ammo_effect_id AE_NULL
Function Documentation
get_all_ammo_effects()
generic_factory<ammo_effect>& get_all_ammo_effects ()
Definition at line 11 of file ammo_effect.cpp.
 {
     static generic_factory<ammo_effect> all_ammo_effects( "ammo effects" );
     return all_ammo_effects;
 }
Referenced by ammo_effects::check_consistency(), ammo_effect::count(), ammo_effects::finalize_all(), ammo_effects::get_all(), int_id< T >::id(), string_id< T >::id(), string_id< T >::is_valid(), int_id< T >::is_valid(), ammo_effects::load(), string_id< T >::obj(), int_id< T >::obj(), ordered_static_globals(), and ammo_effects::reset().
Variable Documentation
AE_NULL
ammo_effect_id AE_NULL
Definition at line 179 of file ammo_effect.cpp.
Referenced by string_id< T >::id().