Cataclysm DDA: src/ammo_effect.h File Reference
ammo_effect.h File Reference
#include <cstddef>
#include <string>
#include <string_view>
#include <utility>
#include <vector>
#include "explosion.h"
#include "field_type.h"
#include "type_id.h"
Classes
struct ammo_effect
Namespaces
ammo_effects
Macros
#define CATA_SRC_AMMO_EFFECT_H
Functions
generic_factory< ammo_effect > & get_all_ammo_effects ()
void ammo_effects::load (const JsonObject &jo, const std::string &src)
void ammo_effects::finalize_all ()
void ammo_effects::check_consistency ()
void ammo_effects::reset ()
const std::vector< ammo_effect > & ammo_effects::get_all ()
Variables
ammo_effect_id AE_NULL
Macro Definition Documentation
CATA_SRC_AMMO_EFFECT_H
#define CATA_SRC_AMMO_EFFECT_H
Definition at line 3 of file ammo_effect.h.
Function Documentation
get_all_ammo_effects()
generic_factory<ammo_effect>& get_all_ammo_effects ()
Definition at line 11 of file ammo_effect.cpp.
 {
     static generic_factory<ammo_effect> all_ammo_effects( "ammo effects" );
     return all_ammo_effects;
 }
Referenced by ammo_effects::check_consistency(), ammo_effect::count(), ammo_effects::finalize_all(), ammo_effects::get_all(), int_id< T >::id(), string_id< T >::id(), string_id< T >::is_valid(), int_id< T >::is_valid(), ammo_effects::load(), string_id< T >::obj(), int_id< T >::obj(), ordered_static_globals(), and ammo_effects::reset().
Variable Documentation
AE_NULL
ammo_effect_id AE_NULL extern
Definition at line 179 of file ammo_effect.cpp.
Referenced by string_id< T >::id().