Cataclysm DDA: src/anatomy.cpp File Reference
anatomy.cpp File Reference
#include "anatomy.h"
#include <algorithm>
#include <cmath>
#include <map>
#include <set>
#include <string>
#include <unordered_set>
#include "ballistics.h"
#include "character.h"
#include "creature.h"
#include "debug.h"
#include "flag.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "generic_factory.h"
#include "init.h"
#include "json_error.h"
#include "messages.h"
#include "output.h"
#include "rng.h"
#include "type_id.h"
#include "weighted_list.h"
Namespaces
anonymous_namespace{anatomy.cpp}
Variables
static const anatomy_id anatomy_human_anatomy ("human_anatomy")
static const json_character_flag json_flag_ALWAYS_BLOCK ("ALWAYS_BLOCK")
static const json_character_flag json_flag_BIONIC_LIMB ("BIONIC_LIMB")
static const json_character_flag json_flag_LIMB_LOWER ("LIMB_LOWER")
static const json_character_flag json_flag_LIMB_UPPER ("LIMB_UPPER")
static const json_character_flag json_flag_NONSTANDARD_BLOCK ("NONSTANDARD_BLOCK")
static const limb_score_id limb_score_block ("block")
generic_factory< anatomy > anonymous_namespace{anatomy.cpp}::anatomy_factory ("anatomy")
Variable Documentation
anatomy_human_anatomy
const anatomy_id anatomy_human_anatomy("human_anatomy") ("human_anatomy") static
Referenced by anatomy::check_consistency().
json_flag_ALWAYS_BLOCK
const json_character_flag json_flag_ALWAYS_BLOCK("ALWAYS_BLOCK") ("ALWAYS_BLOCK") static
Referenced by anatomy::select_blocking_part().
json_flag_BIONIC_LIMB
const json_character_flag json_flag_BIONIC_LIMB("BIONIC_LIMB") ("BIONIC_LIMB") static
Referenced by anatomy::get_organic_size_sum().
json_flag_LIMB_LOWER
const json_character_flag json_flag_LIMB_LOWER("LIMB_LOWER") ("LIMB_LOWER") static
Referenced by anatomy::select_body_part().
json_flag_LIMB_UPPER
const json_character_flag json_flag_LIMB_UPPER("LIMB_UPPER") ("LIMB_UPPER") static
Referenced by anatomy::get_all_eligable_parts(), and anatomy::select_body_part().
json_flag_NONSTANDARD_BLOCK
const json_character_flag json_flag_NONSTANDARD_BLOCK("NONSTANDARD_BLOCK") ("NONSTANDARD_BLOCK") static
Referenced by anatomy::select_blocking_part().
limb_score_block
const limb_score_id limb_score_block("block") ("block") static
Referenced by anatomy::select_blocking_part().