Cataclysm DDA: src/armor_layers.cpp File Reference
armor_layers.cpp File Reference
#include <algorithm>
#include <climits>
#include <cstddef>
#include <iterator>
#include <list>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "activity_type.h"
#include "body_part_set.h"
#include "bodypart.h"
#include "catacharset.h"
#include "character.h"
#include "character_attire.h"
#include "color.h"
#include "creature.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "enums.h"
#include "flag.h"
#include "flat_set.h"
#include "game_inventory.h"
#include "input_context.h"
#include "inventory.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "line.h"
#include "output.h"
#include "pimpl.h"
#include "player_activity.h"
#include "point.h"
#include "string_formatter.h"
#include "subbodypart.h"
#include "translation.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
Classes
struct anonymous_namespace{armor_layers.cpp}::mid_pane_status
Namespaces
anonymous_namespace{armor_layers.cpp}
Functions
std::string anonymous_namespace{armor_layers.cpp}::clothing_layer (const item &worn_item)
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_properties (const item &worn_item, int width, const Character &, const bodypart_id &bp)
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_protection (const item &worn_item, int width, const bodypart_id &bp)
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_flags_description (const item &worn_item, int width)
std::string anonymous_namespace{armor_layers.cpp}::body_part_names (const std::vector< bodypart_id > &parts)
mid_pane_status anonymous_namespace{armor_layers.cpp}::draw_mid_pane (const catacurses::window &w_sort_middle, std::list< item >::const_iterator const worn_item_it, Character &c, const bodypart_id &bp, mid_pane_status &status)
void anonymous_namespace{armor_layers.cpp}::add_category_and_values (std::vector< std::string > &current_text, const int field_width, const std::string &category_name, const std::vector< std::pair< std::string, std::string >> &names_and_values)
std::vector< std::pair< std::string, std::string > > anonymous_namespace{armor_layers.cpp}::collect_protection_subvalues (const resistances &worst_res, const resistances &best_res, const resistances &median_res, const bool display_median, const damage_type_id &type)
static void draw_grid (const catacurses::window &w, int left_pane_w, int mid_pane_w, int encumb_top)
Variables
static const activity_id ACT_ARMOR_LAYERS ("ACT_ARMOR_LAYERS")
static const flag_id json_flag_HIDDEN ("HIDDEN")
Function Documentation
draw_grid()
static void draw_grid (const catacurses::window & w, int left_pane_w, int mid_pane_w, int encumb_top) static
Definition at line 579 of file armor_layers.cpp.
 {
     const int win_w = getmaxx( w );
     const int win_h = getmaxy( w );
     draw_border( w );
     mvwhline( w, point( 1, 2 ), 0, win_w - 2 );
     mvwhline( w, point( left_pane_w + 2, encumb_top - 1 ), 0, mid_pane_w );
     mvwvline( w, point( left_pane_w + 1, 3 ), 0, win_h - 4 );
     mvwvline( w, point( left_pane_w + mid_pane_w + 2, 3 ), 0, win_h - 4 );
     // intersections
     mvwputch( w, point( 0, 2 ), BORDER_COLOR, LINE_XXXO ); // '|-'
     mvwputch( w, point( win_w - 1, 2 ), BORDER_COLOR, LINE_XOXX ); // '-|'
     mvwputch( w, point( left_pane_w + 1, encumb_top - 1 ), BORDER_COLOR, LINE_XXXO ); // '|-'
     mvwputch( w, point( left_pane_w + mid_pane_w + 2, encumb_top - 1 ), BORDER_COLOR,
               LINE_XOXX ); // '-|'
     mvwputch( w, point( left_pane_w + 1, 2 ), BORDER_COLOR, LINE_OXXX ); // '^|^'
     mvwputch( w, point( left_pane_w + 1, win_h - 1 ), BORDER_COLOR, LINE_XXOX ); // '_|_'
     mvwputch( w, point( left_pane_w + mid_pane_w + 2, 2 ), BORDER_COLOR, LINE_OXXX ); // '^|^'
     mvwputch( w, point( left_pane_w + mid_pane_w + 2, win_h - 1 ), BORDER_COLOR, LINE_XXOX ); // '_|_'
     wnoutrefresh( w );
 }
References BORDER_COLOR, draw_border(), catacurses::getmaxx(), catacurses::getmaxy(), LINE_OXXX, LINE_XOXX, LINE_XXOX, LINE_XXXO, catacurses::mvwhline(), mvwputch(), catacurses::mvwvline(), and catacurses::wnoutrefresh().
Referenced by outfit::sort_armor().
Variable Documentation
ACT_ARMOR_LAYERS
const activity_id ACT_ARMOR_LAYERS("ACT_ARMOR_LAYERS") ("ACT_ARMOR_LAYERS") static
Referenced by outfit::sort_armor().
json_flag_HIDDEN
const flag_id json_flag_HIDDEN("HIDDEN") ("HIDDEN") static
Referenced by outfit::sort_armor().