Cataclysm DDA: src/assign.h File Reference
assign.h File Reference
#include <iterator>
#include <limits>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include "calendar.h"
#include "damage.h"
#include "flat_set.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "type_id.h"
#include "units.h"
Classes
class detail::is_optional_helper< T >
class detail::is_optional_helper< std::optional< T > >
class is_optional< T >
Namespaces
detail
details
Macros
#define CATA_SRC_ASSIGN_H
Functions
void report_strict_violation (const JsonObject &jo, const std::string &message, std::string_view name)
template<typename T , std::enable_if_t< std::is_arithmetic_v< T >, int > = 0>
bool assign (const JsonObject &jo, std::string_view name, T &val, bool strict=false, T lo=std::numeric_limits< T >::lowest(), T hi=std::numeric_limits< T >::max())
bool assign (const JsonObject &jo, std::string_view name, bool &val, bool strict=false)
template<typename T , std::enable_if_t< std::is_arithmetic_v< T >, int > = 0>
bool assign (const JsonObject &jo, const std::string_view name, std::pair< T, T > &val, bool strict=false, T lo=std::numeric_limits< T >::lowest(), T hi=std::numeric_limits< T >::max())
template<typename T , std::enable_if_t< std::is_class_v< T > &&!is_optional< T >::value, int > = 0>
bool assign (const JsonObject &jo, std::string_view name, T &val, bool strict=false)
template<typename T , typename Set >
bool details::assign_set (const JsonObject &jo, const std::string_view name, Set &val)
template<typename T >
std::enable_if_t< std::is_constructible_v< T, std::string >, bool > assign (const JsonObject &jo, const std::string_view name, std::set< T > &val, bool=false)
template<typename T >
std::enable_if_t< std::is_constructible_v< T, std::string >, bool > assign (const JsonObject &jo, const std::string_view name, cata::flat_set< T > &val, bool=false)
bool assign (const JsonObject &jo, std::string_view name, units::volume &val, bool strict=false, units::volume lo=units::volume_min, units::volume hi=units::volume_max)
bool assign (const JsonObject &jo, std::string_view name, units::mass &val, bool strict=false, units::mass lo=units::mass_min, units::mass hi=units::mass_max)
bool assign (const JsonObject &jo, std::string_view name, units::length &val, bool strict=false, units::length lo=units::length_min, units::length hi=units::length_max)
bool assign (const JsonObject &jo, std::string_view name, units::money &val, bool strict=false, units::money lo=units::money_min, units::money hi=units::money_max)
bool assign (const JsonObject &jo, const std::string &name, nc_color &val, bool strict=false)
template<typename T >
std::enable_if_t< std::is_same_v< std::decay_t< T >, time_duration >, bool > read_with_factor (const JsonObject &jo, const std::string_view name, T &val, const T &factor)
template<typename T >
std::enable_if_t< std::is_same_v< std::decay_t< T >, time_duration >, bool > assign (const JsonObject &jo, const std::string &name, T &val, bool strict, const T &factor)
template<typename T >
bool assign (const JsonObject &jo, const std::string_view name, std::optional< T > &val, const bool strict=false)
bool assign (const JsonObject &jo, std::string_view name, damage_instance &val, bool strict=false, const damage_instance &lo=damage_instance(damage_type_id::NULL_ID(), 0.0f, 0.0f, 0.0f, 0.0f), const damage_instance &hi=damage_instance(damage_type_id::NULL_ID(), float_max, float_max, float_max, float_max))
Variables
constexpr float float_max = std::numeric_limits<float>::max()
Macro Definition Documentation
CATA_SRC_ASSIGN_H
#define CATA_SRC_ASSIGN_H
Definition at line 3 of file assign.h.
Function Documentation
assign() [1/14]
bool assign (const JsonObject & jo, const std::string & name, nc_color & val, bool strict = false)
Definition at line 436 of file assign.cpp.
 {
     if( !jo.has_member( name ) ) {
         return false;
     }
     const nc_color out = color_from_string( jo.get_string( name ) );
     if( out == c_unset ) {
         jo.throw_error_at( name, "invalid color name" );
     }
     if( strict && out == val ) {
         report_strict_violation( jo,
                                  "cannot assign explicit value the same as default or inherited value",
                                  name );
     }
     val = out;
     return true;
 }
References c_unset, color_from_string(), JsonObject::get_string(), JsonObject::has_member(), om_direction::name(), report_strict_violation(), strict, and JsonObject::throw_error_at().
assign() [2/14]
template<typename T > std::enable_if_t<std::is_same_v<std::decay_t<T>, time_duration>, bool> assign (const JsonObject & jo, const std::string & name, T & val, bool strict, const T & factor) inline
Definition at line 264 of file assign.h.
 {
     T out{};
     double scalar;
     // Object via which to report errors which differs for proportional/relative values
     JsonObject err = jo;
     err.allow_omitted_members();
     JsonObject relative = jo.get_object( "relative" );
     relative.allow_omitted_members();
     JsonObject proportional = jo.get_object( "proportional" );
     proportional.allow_omitted_members();
     // Do not require strict parsing for relative and proportional values as rules
     // such as +10% are well-formed independent of whether they affect base value
     if( read_with_factor( relative, name, out, factor ) ) {
         err = relative;
         strict = false;
         out = out + val;
     } else if( proportional.read( name, scalar ) ) {
         err = proportional;
         if( scalar <= 0 || scalar == 1 ) {
             err.throw_error_at( name, "multiplier must be a positive number other than 1" );
         }
         strict = false;
         out = val * scalar;
     } else if( !read_with_factor( jo, name, out, factor ) ) {
         return false;
     }
     if( strict && out == val ) {
         report_strict_violation( err, "cannot assign explicit value the same as default or inherited value",
                                  name );
     }
     val = out;
     return true;
 }
References JsonObject::allow_omitted_members(), JsonObject::get_object(), om_direction::name(), JsonObject::read(), read_with_factor(), report_strict_violation(), strict, and JsonObject::throw_error_at().
assign() [3/14]
template<typename T > std::enable_if_t<std::is_constructible_v<T, std::string>, bool> assign (const JsonObject & jo, const std::string_view name, cata::flat_set< T > & val, bool = false)
Definition at line 200 of file assign.h.
 {
     return details::assign_set<T, cata::flat_set<T>>( jo, name, val );
 }
References om_direction::name().
assign() [4/14]
template<typename T > bool assign (const JsonObject & jo, const std::string_view name, std::optional< T > & val, const bool strict = false) inline
Definition at line 308 of file assign.h.
 {
     if( !jo.has_member( name ) ) {
         return false;
     }
     if( jo.has_null( name ) ) {
         val.reset();
         return true;
     }
     if( !val ) {
         val.emplace();
     }
     return assign( jo, name, *val, strict );
 }
References assign(), JsonObject::has_member(), JsonObject::has_null(), om_direction::name(), and strict.
assign() [5/14]
template<typename T , std::enable_if_t< std::is_arithmetic_v< T >, int > = 0> bool assign (const JsonObject & jo, const std::string_view name, std::pair< T, T > & val, bool strict = false, T lo = std::numeric_limits<T>::lowest(), T hi = std::numeric_limits<T>::max())
Definition at line 96 of file assign.h.
 {
     std::pair<T, T> out;
     if( jo.has_array( name ) ) {
         JsonArray arr = jo.get_array( name );
         arr.read( 0, out.first );
         arr.read( 1, out.second );
     } else if( jo.read( name, out.first ) ) {
         out.second = out.first;
     } else {
         return false;
     }
     if( out.first > out.second ) {
         std::swap( out.first, out.second );
     }
     if( out.first < lo || out.second > hi ) {
         jo.throw_error_at( name, "value outside supported range" );
     }
     if( strict && out == val ) {
         report_strict_violation( jo, "cannot assign explicit value the same as default or inherited value",
                                  name );
     }
     val = out;
     return true;
 }
References JsonObject::get_array(), JsonObject::has_array(), cata::hash64_detail::lo, om_direction::name(), JsonObject::read(), JsonArray::read(), report_strict_violation(), strict, cata::swap(), and JsonObject::throw_error_at().
assign() [6/14]
template<typename T > std::enable_if_t<std::is_constructible_v<T, std::string>, bool> assign (const JsonObject & jo, const std::string_view name, std::set< T > & val, bool = false)
Definition at line 193 of file assign.h.
 {
     return details::assign_set<T, std::set<T>>( jo, name, val );
 }
References om_direction::name().
assign() [7/14]
bool assign (const JsonObject & jo, std::string_view name, bool & val, bool strict = false)
Definition at line 23 of file assign.cpp.
 {
     bool out;
     if( !jo.read( name, out ) ) {
         return false;
     }
     if( strict && out == val ) {
         report_strict_violation( jo, "cannot assign explicit value the same as default or inherited value",
                                  name );
     }
     val = out;
     return true;
 }
References om_direction::name(), JsonObject::read(), report_strict_violation(), and strict.
Referenced by overmap_special_connection::deserialize(), Character::load(), activity_type::load(), fault_fix::load(), vpart_category::load(), weakpoint_effect::load(), weakpoint::load(), saw_barrel_actor::load(), saw_stock_actor::load(), molle_attach_actor::load(), molle_detach_actor::load(), weigh_self_actor::load(), generic_factory< T >::load(), mattack_actor::load(), mission_type::load(), mtype::load(), overmap_land_use_code::load(), oter_type_t::load(), overmap_special::load(), recipe::load(), start_location::load(), vpart_info::load(), ter_t::load(), profession_group::load(), body_part_type::load(), move_mode::load(), trap::load(), vehicle_prototype::load(), weather_type::load(), ascii_art::load(), scent_type::load(), furn_workbench_info::load(), plant_data::load(), mut_transform::load(), material_type::load(), place_trap_actor::data::load(), unpack_actor::load(), change_scent_iuse::load(), salvage_actor::load(), inscribe_actor::load(), place_trap_actor::load(), emit_actor::load(), deploy_tent_actor::load(), bionic_data::load(), weakpoint_family::load(), load_mat_burn_data(), mod_manager::load_modfile(), MonsterGroupManager::LoadMonsterGroup(), and parse_vp_reqs().
assign() [8/14]
bool assign (const JsonObject & jo, std::string_view name, damage_instance & val, bool strict = false, const damage_instance & lo = damage_instance(damage_type_id::NULL_ID(), 0.0f, 0.0f, 0.0f, 0.0f), const damage_instance & hi = damage_instance(damage_type_id::NULL_ID(), float_max, float_max, float_max, float_max))
Definition at line 627 of file assign.cpp.
 {
     // What we'll eventually be returning for the damage instance
     damage_instance out;
     std::string id_err = "no id found";
     // Grab the id for good error reporting
     if( jo.has_string( "id" ) ) {
         id_err = jo.get_string( "id" );
     }
     bool assigned = false;
     if( jo.has_array( name ) ) {
         out = load_damage_instance_inherit( jo.get_array( name ), val );
         assigned = true;
     } else if( jo.has_object( name ) ) {
         out = load_damage_instance_inherit( jo.get_object( name ), val );
         assigned = true;
     }
     // Object via which to report errors which differs for proportional/relative values
     const JsonObject &err = jo;
     JsonObject relative = jo.get_object( "relative" );
     relative.allow_omitted_members();
     JsonObject proportional = jo.get_object( "proportional" );
     proportional.allow_omitted_members();
     // Currently, we load only either relative or proportional when loading damage
     // There's no good reason for this, but it's simple for now
     if( relative.has_object( name ) ) {
         assign_dmg_relative( out, val, load_damage_instance( relative.get_object( name ) ), strict );
         assigned = true;
     } else if( relative.has_array( name ) ) {
         assign_dmg_relative( out, val, load_damage_instance( relative.get_array( name ) ), strict );
         assigned = true;
     } else if( proportional.has_object( name ) ) {
         assign_dmg_proportional( proportional, name, out, val,
                                  load_damage_instance( proportional.get_object( name ) ),
                                  strict );
         assigned = true;
     } else if( proportional.has_array( name ) ) {
         assign_dmg_proportional( proportional, name, out, val,
                                  load_damage_instance( proportional.get_array( name ) ),
                                  strict );
         assigned = true;
     }
     if( !assigned ) {
         // Straight copy-from, not modified by proportional or relative
         out = val;
     }
     check_assigned_dmg( err, name, out, lo, hi );
     if( assigned && strict && out == val ) {
         report_strict_violation( err,
                                  "cannot assign explicit damage value the same as default or inherited value", name );
     }
     // Now that we've verified everything in out is all good, set val to it
     val = out;
     return true;
 }
References JsonObject::allow_omitted_members(), assign_dmg_proportional(), assign_dmg_relative(), check_assigned_dmg(), JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_object(), JsonObject::has_string(), cata::hash64_detail::lo, load_damage_instance(), load_damage_instance_inherit(), om_direction::name(), report_strict_violation(), and strict.
assign() [9/14]
template<typename T , std::enable_if_t< std::is_class_v< T > &&!is_optional< T >::value, int > = 0> bool assign (const JsonObject & jo, std::string_view name, T & val, bool strict = false)
Definition at line 135 of file assign.h.
 {
     T out;
     if( !jo.read( name, out ) ) {
         return false;
     }
     if( strict && out == val ) {
         report_strict_violation( jo, "cannot assign explicit value the same as default or inherited value",
                                  name );
     }
     val = out;
     return true;
 }
References om_direction::name(), JsonObject::read(), report_strict_violation(), and strict.
assign() [10/14]
template<typename T , std::enable_if_t< std::is_arithmetic_v< T >, int > = 0> bool assign (const JsonObject & jo, std::string_view name, T & val, bool strict = false, T lo = std::numeric_limits<T>::lowest(), T hi = std::numeric_limits<T>::max())
Definition at line 44 of file assign.h.
 {
     T out;
     double scalar;
     // Object via which to report errors which differs for proportional/relative values
     const JsonObject *err = &jo;
     JsonObject relative = jo.get_object( "relative" );
     relative.allow_omitted_members();
     JsonObject proportional = jo.get_object( "proportional" );
     proportional.allow_omitted_members();
     // Do not require strict parsing for relative and proportional values as rules
     // such as +10% are well-formed independent of whether they affect base value
     if( relative.read( name, out ) ) {
         err = &relative;
         strict = false;
         out += val;
     } else if( proportional.read( name, scalar ) ) {
         err = &proportional;
         if( scalar <= 0 || scalar == 1 ) {
             err->throw_error_at( name, "multiplier must be a positive number other than 1" );
         }
         strict = false;
         out = val * scalar;
     } else if( !jo.read( name, out ) ) {
         return false;
     }
     if( out < lo || out > hi ) {
         err->throw_error_at( name, "value outside supported range" );
     }
     if( strict && out == val ) {
         report_strict_violation( *err,
                                  "cannot assign explicit value the same as default or inherited value",
                                  name );
     }
     val = out;
     return true;
 }
References JsonObject::allow_omitted_members(), JsonObject::get_object(), om_direction::name(), JsonObject::read(), report_strict_violation(), strict, and JsonObject::throw_error_at().
Referenced by assign().
assign() [11/14]
bool assign (const JsonObject & jo, std::string_view name, units::length & val, bool strict = false, units::length lo = units::length_min, units::length hi = units::length_max)
Definition at line 170 of file assign.cpp.
 {
     const auto parse = [&name]( const JsonObject & obj, units::length & out ) {
         if( obj.has_int( name ) ) {
             out = units::from_millimeter<std::int64_t>( obj.get_int( name ) );
             return true;
         }
         if( obj.has_string( name ) ) {
             out = read_from_json_string<units::length>( obj.get_member( name ), units::length_units );
             return true;
         }
         return false;
     };
     units::length out;
     // Object via which to report errors which differs for proportional/relative values
     const JsonObject *err = &jo;
     JsonObject relative = jo.get_object( "relative" );
     relative.allow_omitted_members();
     JsonObject proportional = jo.get_object( "proportional" );
     proportional.allow_omitted_members();
     // Do not require strict parsing for relative and proportional values as rules
     // such as +10% are well-formed independent of whether they affect base value
     if( relative.has_member( name ) ) {
         units::length tmp;
         err = &relative;
         if( !parse( *err, tmp ) ) {
             err->throw_error_at( name, "invalid relative value specified" );
         }
         strict = false;
         out = val + tmp;
     } else if( proportional.has_member( name ) ) {
         double scalar;
         err = &proportional;
         if( !err->read( name, scalar ) || scalar <= 0 || scalar == 1 ) {
             err->throw_error_at( name, "multiplier must be a positive number other than 1" );
         }
         strict = false;
         out = val * scalar;
     } else if( !parse( jo, out ) ) {
         return false;
     }
     if( out < lo || out > hi ) {
         err->throw_error_at( name, "value outside supported range" );
     }
     if( strict && out == val ) {
         report_strict_violation( *err,
                                  "cannot assign explicit value the same as default or inherited value",
                                  name );
     }
     val = out;
     return true;
 }
References JsonObject::allow_omitted_members(), JsonObject::get_object(), JsonObject::has_member(), units::length_units, om_direction::name(), int_id< T >::obj(), JsonObject::read(), report_strict_violation(), strict, and JsonObject::throw_error_at().
assign() [12/14]
bool assign (const JsonObject & jo, std::string_view name, units::mass & val, bool strict = false, units::mass lo = units::mass_min, units::mass hi = units::mass_max)
Definition at line 106 of file assign.cpp.
 {
     const auto parse = [&name]( const JsonObject & obj, units::mass & out ) {
         if( obj.has_int( name ) ) {
             out = units::from_gram<std::int64_t>( obj.get_int( name ) );
             return true;
         }
         if( obj.has_string( name ) ) {
             out = read_from_json_string<units::mass> ( obj.get_member( name ), units::mass_units );
             return true;
         }
         return false;
     };
     units::mass out;
     // Object via which to report errors which differs for proportional/relative values
     const JsonObject *err = &jo;
     JsonObject relative = jo.get_object( "relative" );
     relative.allow_omitted_members();
     JsonObject proportional = jo.get_object( "proportional" );
     proportional.allow_omitted_members();
     // Do not require strict parsing for relative and proportional values as rules
     // such as +10% are well-formed independent of whether they affect base value
     if( relative.has_member( name ) ) {
         units::mass tmp;
         err = &relative;
         if( !parse( *err, tmp ) ) {
             err->throw_error_at( name, "invalid relative value specified" );
         }
         strict = false;
         out = val + tmp;
     } else if( proportional.has_member( name ) ) {
         double scalar;
         err = &proportional;
         if( !err->read( name, scalar ) || scalar <= 0 || scalar == 1 ) {
             err->throw_error_at( name, "multiplier must be a positive number other than 1" );
         }
         strict = false;
         out = val * scalar;
     } else if( !parse( jo, out ) ) {
         return false;
     }
     if( out < lo || out > hi ) {
         err->throw_error_at( name, "value outside supported range" );
     }
     if( strict && out == val ) {
         report_strict_violation( *err,
                                  "cannot assign explicit value the same as default or inherited value",
                                  name );
     }
     val = out;
     return true;
 }
References JsonObject::allow_omitted_members(), JsonObject::get_object(), JsonObject::has_member(), units::mass_units, om_direction::name(), int_id< T >::obj(), JsonObject::read(), report_strict_violation(), strict, and JsonObject::throw_error_at().
assign() [13/14]
bool assign (const JsonObject & jo, std::string_view name, units::money & val, bool strict = false, units::money lo = units::money_min, units::money hi = units::money_max)
Definition at line 234 of file assign.cpp.
 {
     const auto parse = [&name]( const JsonObject & obj, units::money & out ) {
         if( obj.has_int( name ) ) {
             out = units::from_cent( obj.get_int( name ) );
             return true;
         }
         if( obj.has_string( name ) ) {
             out = read_from_json_string<units::money>( obj.get_member( name ), units::money_units );
             return true;
         }
         return false;
     };
     units::money out;
     // Object via which to report errors which differs for proportional/relative values
     const JsonObject *err = &jo;
     JsonObject relative = jo.get_object( "relative" );
     relative.allow_omitted_members();
     JsonObject proportional = jo.get_object( "proportional" );
     proportional.allow_omitted_members();
     // Do not require strict parsing for relative and proportional values as rules
     // such as +10% are well-formed independent of whether they affect base value
     if( relative.has_member( name ) ) {
         units::money tmp;
         err = &relative;
         if( !parse( *err, tmp ) ) {
             err->throw_error_at( name, "invalid relative value specified" );
         }
         strict = false;
         out = val + tmp;
     } else if( proportional.has_member( name ) ) {
         double scalar;
         err = &proportional;
         if( !err->read( name, scalar ) || scalar <= 0 || scalar == 1 ) {
             err->throw_error_at( name, "multiplier must be a positive number other than 1" );
         }
         strict = false;
         out = val * scalar;
     } else if( !parse( jo, out ) ) {
         return false;
     }
     if( out < lo || out > hi ) {
         err->throw_error_at( name, "value outside supported range" );
     }
     if( strict && out == val ) {
         report_strict_violation( *err,
                                  "cannot assign explicit value the same as default or inherited value",
                                  name );
     }
     val = out;
     return true;
 }
References JsonObject::allow_omitted_members(), units::from_cent(), JsonObject::get_object(), JsonObject::has_member(), units::money_units, om_direction::name(), int_id< T >::obj(), JsonObject::read(), report_strict_violation(), strict, and JsonObject::throw_error_at().
assign() [14/14]
bool assign (const JsonObject & jo, std::string_view name, units::volume & val, bool strict = false, units::volume lo = units::volume_min, units::volume hi = units::volume_max)
Definition at line 41 of file assign.cpp.
 {
     const auto parse = [name]( const JsonObject & obj, units::volume & out ) {
         if( obj.has_int( name ) ) {
             out = obj.get_int( name ) * units::legacy_volume_factor;
             return true;
         }
         if( obj.has_string( name ) ) {
             out = read_from_json_string<units::volume>( obj.get_member( name ), units::volume_units );
             return true;
         }
         return false;
     };
     units::volume out;
     // Object via which to report errors which differs for proportional/relative values
     const JsonObject *err = &jo;
     JsonObject relative = jo.get_object( "relative" );
     relative.allow_omitted_members();
     JsonObject proportional = jo.get_object( "proportional" );
     proportional.allow_omitted_members();
     // Do not require strict parsing for relative and proportional values as rules
     // such as +10% are well-formed independent of whether they affect base value
     if( relative.has_member( name ) ) {
         units::volume tmp;
         err = &relative;
         if( !parse( *err, tmp ) ) {
             err->throw_error_at( name, "invalid relative value specified" );
         }
         strict = false;
         out = val + tmp;
     } else if( proportional.has_member( name ) ) {
         double scalar;
         err = &proportional;
         if( !err->read( name, scalar ) || scalar <= 0 || scalar == 1 ) {
             err->throw_error_at( name, "multiplier must be a positive number other than 1" );
         }
         strict = false;
         out = val * scalar;
     } else if( !parse( jo, out ) ) {
         return false;
     }
     if( out < lo || out > hi ) {
         err->throw_error_at( name, "value outside supported range" );
     }
     if( strict && out == val ) {
         report_strict_violation( *err,
                                  "cannot assign explicit value the same as default or inherited value",
                                  name );
     }
     val = out;
     return true;
 }
References JsonObject::allow_omitted_members(), JsonObject::get_object(), JsonObject::has_member(), units::legacy_volume_factor, om_direction::name(), int_id< T >::obj(), JsonObject::read(), report_strict_violation(), strict, JsonObject::throw_error_at(), and units::volume_units.
read_with_factor()
template<typename T > std::enable_if_t<std::is_same_v<std::decay_t<T>, time_duration>, bool> read_with_factor (const JsonObject & jo, const std::string_view name, T & val, const T & factor) inline
Definition at line 242 of file assign.h.
 {
     int tmp;
     if( jo.read( name, tmp, false ) ) {
         // JSON contained a raw number -> apply factor
         val = tmp * factor;
         return true;
     } else if( jo.has_string( name ) ) {
         // JSON contained a time duration string -> no factor
         val = read_from_json_string<time_duration>( jo.get_member( name ), time_duration::units );
         return true;
     }
     return false;
 }
References JsonObject::get_member(), JsonObject::has_string(), om_direction::name(), JsonObject::read(), and time_duration::units.
Referenced by assign().
report_strict_violation()
void report_strict_violation (const JsonObject & jo, const std::string & message, std::string_view name)
Definition at line 11 of file assign.cpp.
 {
     try {
         // Let the json class do the formatting, it includes the context of the JSON data.
         jo.throw_error_at( name, message );
     } catch( const JsonError &err ) {
         // And catch the exception so the loading continues like normal.
         debugmsg( "(json-error)\n%s", err.what() );
     }
 }
References debugmsg, mapgen_defer::message, om_direction::name(), and JsonObject::throw_error_at().
Referenced by assign().
Variable Documentation
float_max
constexpr float float_max = std::numeric_limits<float>::max() constexpr
Definition at line 324 of file assign.h.