Cataclysm DDA: src/auto_note.h File Reference
auto_note.h File Reference
#include <cstdint>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "cata_path.h"
#include "catacharset.h"
#include "color.h"
#include "map_extras.h"
#include "type_id.h"
Classes
class auto_notes::custom_symbol
class auto_notes::auto_note_manager_gui
Class implementing the user interface for the auto note configuration.
class auto_notes::auto_note_settings
A class storing auto note settings for all map features for a given player.
Namespaces
auto_notes
Macros
#define CATA_SRC_AUTO_NOTE_H
Functions
auto_notes::auto_note_settings & get_auto_notes_settings ()
Macro Definition Documentation
CATA_SRC_AUTO_NOTE_H
#define CATA_SRC_AUTO_NOTE_H
Definition at line 3 of file auto_note.h.
Function Documentation
get_auto_notes_settings()
auto_notes::auto_note_settings& get_auto_notes_settings ()
Definition at line 606 of file auto_note.cpp.
 {
     static auto_notes::auto_note_settings staticSettings;
     return staticSettings;
 }
Referenced by overmap::add_extra_note(), auto_notes::auto_note_manager_gui::auto_note_manager_gui(), game::do_regular_action(), auto_notes::auto_note_manager_gui::fill_custom_symbols_cache(), game::load(), game::load_static_data(), game::save(), auto_notes::auto_note_manager_gui::show(), and game::start_game().