Cataclysm DDA: src/auto_pickup.cpp File Reference
auto_pickup.cpp File Reference
#include "auto_pickup.h"
#include <algorithm>
#include <cstddef>
#include <functional>
#include <iosfwd>
#include <map>
#include <memory>
#include <string_view>
#include <utility>
#include <vector>
#include "cata_path.h"
#include "cata_utility.h"
#include "character.h"
#include "color.h"
#include "cursesdef.h"
#include "filesystem.h"
#include "flag.h"
#include "flat_set.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "input_context.h"
#include "item.h"
#include "item_factory.h"
#include "item_location.h"
#include "item_stack.h"
#include "itype.h"
#include "json.h"
#include "map.h"
#include "map_selector.h"
#include "material.h"
#include "options.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
Functions
static bool check_special_rule (const std::map< material_id, int > &materials, std::string_view rule)
auto_pickup::player_settings & get_auto_pickup ()
static bool within_autopickup_limits (const item *pickup_item)
The function will return true if the user has set all limits to a value of 0.
static rule_state get_autopickup_rule (const item *pickup_item)
static void empty_autopickup_target (item *what, tripoint where)
Drop all items from the given container that match special auto pickup rules.
static std::vector< item_location > get_autopickup_items (item_location &from)
Iterate through every item inside the container to find items that match auto pickup rules.
Variables
static const ammotype ammo_battery ("battery")
Function Documentation
check_special_rule()
bool check_special_rule (const std::map< material_id, int > & materials, std::string_view rule) static
Definition at line 788 of file auto_pickup.cpp.
 {
     char type = ' ';
     std::vector<std::string> filter;
     if( rule[1] == ':' ) {
         type = rule[0];
         filter = string_split( rule.substr( 2 ), ',' );
     }
     if( filter.empty() || materials.empty() ) {
         return false;
     }
     if( type == 'm' ) {
         return std::any_of( materials.begin(),
         materials.end(), [&filter]( const std::pair<material_id, int> &mat ) {
             return std::any_of( filter.begin(), filter.end(), [&mat]( const std::string_view search ) {
                 return lcmatch( mat.first->name(), search );
             } );
         } );
     } else if( type == 'M' ) {
         return std::all_of( materials.begin(),
         materials.end(), [&filter]( const std::pair<material_id, int> &mat ) {
             return std::any_of( filter.begin(), filter.end(), [&mat]( const std::string_view search ) {
                 return lcmatch( mat.first->name(), search );
             } );
         } );
     }
     return false;
 }
References filter, and string_split().
Referenced by auto_pickup::rule_list::create_rule(), auto_pickup::rule_list::refresh_map_items(), and auto_pickup::rule::test_pattern().
empty_autopickup_target()
static void empty_autopickup_target (item * what, tripoint where) static
Drop all items from the given container that match special auto pickup rules.
The items will be removed from the container and dropped in the designated location.
Parameters
from container to drop items from.
where location on the map to drop items to.
Definition at line 107 of file auto_pickup.cpp.
 {
     bool is_rigid = what->all_pockets_rigid();
     for( item *entry : what->all_items_top() ) {
         const rule_state ap_rule = get_autopickup_rule( entry );
         // rigid containers want to keep as much items as possible so drop only blacklisted items
         // non-rigid containers want to drop as much items as possible so keep only whitelisted items
         if( is_rigid ? ap_rule == rule_state::BLACKLISTED : ap_rule != rule_state::WHITELISTED ) {
             // drop the items on the same tile the container is on
             get_map().add_item( where, what->remove_item( *entry ) );
         }
     }
 }
References map::add_item(), item::all_items_top(), item::all_pockets_rigid(), BLACKLISTED, get_autopickup_rule(), get_map(), visitable::remove_item(), and WHITELISTED.
Referenced by get_autopickup_items(), and auto_pickup::select_items().
get_auto_pickup()
auto_pickup::player_settings& get_auto_pickup ()
Definition at line 52 of file auto_pickup.cpp.
 {
     static auto_pickup::player_settings single_instance;
     return single_instance;
 }
Referenced by advanced_inventory::display(), game::do_regular_action(), get_autopickup_rule(), game::inventory_item_menu(), game::load(), game::load_static_data(), main_menu::opening_screen(), game::save(), and game::start_game().
get_autopickup_items()
static std::vector<item_location> get_autopickup_items (item_location & from) static
Iterate through every item inside the container to find items that match auto pickup rules.
In most cases whitelisted items will be included and blacklisted one will be excluded however there are special cases. Below is an overview of selection rules for container auto pickup.
Containers and items will never be picked up when:
they are owned by player and AUTO_PICKUP_OWNED game option is disabled.
they exceed volume or weight user auto pickup limitations.
they are blacklisted in auto pickup rules.
Containers will always be picked up when:
the container is sealed.
there is any liquids stored in container pockets.
all items inside the container are marked for pickup.
Containers will never be picked up when:
only batteries were selected and the container is battery powered.
the container is a non-whitelisted corpse.
Items will NOT be picked up when:
the parent container is non-rigid and the item is not whitelisted.
Parameters
from item to search for items to auto pickup from.
Returns
sequence of items to auto pickup from given container.
Definition at line 150 of file auto_pickup.cpp.
 {
     item *container_item = from.get_item();
     // items sealed in containers should never be unsealed by auto pickup
     bool force_pick_container = container_item->any_pockets_sealed();
     bool pick_all_items = true;
     std::vector<item_location> result;
     // do not auto pickup owned containers or items
     if( !get_option<bool>( "AUTO_PICKUP_OWNED" ) &&
         container_item->is_owned_by( get_player_character() ) ) {
         return result;
     }
     std::list<item *> contents = container_item->all_items_top();
     result.reserve( contents.size() );
     bool any_whitelisted = false;
     std::list<item *>::iterator it;
     for( it = contents.begin(); it != contents.end(); ++it ) {
         item *item_entry = *it;
         if( !within_autopickup_limits( item_entry ) ) {
             pick_all_items = false;
             continue;
         }
         const rule_state pickup_state = get_autopickup_rule( item_entry );
         if( pickup_state == rule_state::WHITELISTED ) {
             any_whitelisted = true;
             if( !force_pick_container ) {
                 if( item_entry->is_container() ) {
                     // whitelisted containers should exclude contained blacklisted items
                     empty_autopickup_target( item_entry, from.position() );
                 } else if( item_entry->made_of_from_type( phase_id::LIQUID ) ) {
                     // liquid items should never be picked up without container
                     force_pick_container = true;
                     break;
                 }
                 // pick up the whitelisted item
                 result.emplace_back( from, item_entry );
             }
         } else if( !force_pick_container && item_entry->is_container() &&
                    !item_entry->is_container_empty() ) {
             // get pickup list from nested item container
             item_location location = item_location( from, item_entry );
             std::vector<item_location> result_nested = get_autopickup_items( location );
             // container with content was NOT marked for pickup
             if( result_nested.size() != 1 || result_nested[0] != location ) {
                 pick_all_items = false;
             }
             result.reserve( result_nested.size() + result.size() );
             result.insert( result.end(), result_nested.begin(), result_nested.end() );
         } else {
             // skip not whitelisted items that are not containers with items
             pick_all_items = false;
         }
     }
     // all items in container were approved for pickup
     if( !contents.empty() && ( pick_all_items || force_pick_container ) ) {
         // only auto pickup corpses if they are whitelisted
         // blacklisted containers should still have their contents picked up but themselves should be excluded.
         // If all items inside blacklisted container match then just pickup the items without the container
         rule_state pickup_state = get_autopickup_rule( container_item );
         if( pickup_state == rule_state::BLACKLISTED || !any_whitelisted ||
             ( container_item->is_corpse() && pickup_state != rule_state::WHITELISTED ) ) {
             return result;
         }
         bool all_batteries = true;
         bool powered_container = container_item->ammo_capacity( ammo_battery );
         if( powered_container ) {
             // when dealing with battery powered tools there should only be one pocket
             // and one battery inside but this could change in future so account for that here
             all_batteries = std::all_of( result.begin(), result.end(),
             []( const item_location & il ) {
                 return il.get_item()->is_battery();
             } );
         }
         bool batteries_from_tool = powered_container && all_batteries;
         // make sure container is allowed to be picked up
         // when picking up batteries from powered containers don't pick container
         if( within_autopickup_limits( container_item ) && !batteries_from_tool ) {
             result.clear();
             result.push_back( from );
         } else if( force_pick_container ) {
             // when force picking never pick individual items
             result.clear();
         }
     }
     return result;
 }
References item::all_items_top(), ammo_battery, item::ammo_capacity(), item::any_pockets_sealed(), BLACKLISTED, anonymous_namespace{item_tname.cpp}::contents(), empty_autopickup_target(), get_autopickup_rule(), item_location::get_item(), get_player_character(), item::is_container(), item::is_container_empty(), item::is_corpse(), item::is_owned_by(), LIQUID, location, item::made_of_from_type(), item_location::position(), WHITELISTED, and within_autopickup_limits().
Referenced by auto_pickup::select_items().
get_autopickup_rule()
static rule_state get_autopickup_rule (const item * pickup_item) static
Parameters
pickup_item item to get the auto pickup rule for.
Returns
rule_state associated with the given item.
Definition at line 80 of file auto_pickup.cpp.
 {
     std::string item_name = pickup_item->tname( 1, false );
     rule_state pickup_state = get_auto_pickup().check_item( item_name );
     if( pickup_state == rule_state::WHITELISTED ) {
         return rule_state::WHITELISTED;
     } else if( pickup_state != rule_state::BLACKLISTED ) {
         //No prematched pickup rule found, check rules in more detail
         get_auto_pickup().create_rule( pickup_item );
         if( get_auto_pickup().check_item( item_name ) == rule_state::WHITELISTED ) {
             return rule_state::WHITELISTED;
         }
     } else {
         return rule_state::BLACKLISTED;
     }
     return rule_state::NONE;
 }
References BLACKLISTED, auto_pickup::base_settings::check_item(), auto_pickup::player_settings::create_rule(), get_auto_pickup(), tname::item_name(), NONE, item::tname(), and WHITELISTED.
Referenced by empty_autopickup_target(), get_autopickup_items(), and auto_pickup::select_items().
within_autopickup_limits()
static bool within_autopickup_limits (const item * pickup_item) static
The function will return true if the user has set all limits to a value of 0.
Parameters
pickup_item item to check.
Returns
true if given item's weight and volume is within auto pickup user configured limits.
Definition at line 63 of file auto_pickup.cpp.
 {
     bool valid_item = !pickup_item->has_any_flag( cata::flat_set<flag_id> { flag_ZERO_WEIGHT, flag_NO_DROP } );
     int weight_limit = get_option<int>( "AUTO_PICKUP_WEIGHT_LIMIT" );
     int volume_limit = get_option<int>( "AUTO_PICKUP_VOLUME_LIMIT" );
     bool valid_volume = pickup_item->volume() <= volume_limit * 50_ml;
     bool valid_weight = pickup_item->weight() <= weight_limit * 50_gram;
     return valid_item && ( volume_limit <= 0 || valid_volume ) && ( weight_limit <= 0 || valid_weight );
 }
References flag_NO_DROP, flag_ZERO_WEIGHT, item::has_any_flag(), item::volume(), and item::weight().
Referenced by get_autopickup_items(), and auto_pickup::select_items().
Variable Documentation
ammo_battery
const ammotype ammo_battery("battery") ("battery") static
Referenced by get_autopickup_items(), and auto_pickup::select_items().