Cataclysm DDA: src/auto_pickup.h File Reference
auto_pickup.h File Reference
#include <functional>
#include <list>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#include "enums.h"
#include "item_stack.h"
Classes
class auto_pickup::cache
The currently-active set of auto-pickup rules, in a form that allows quick lookup.
class auto_pickup::rule
A single entry in the list of auto pickup entries rule_list.
class auto_pickup::rule_list
A list of rules.
class auto_pickup::user_interface
class auto_pickup::user_interface::tab
class auto_pickup::base_settings
class auto_pickup::player_settings
class auto_pickup::npc_settings
Namespaces
auto_pickup
Macros
#define CATA_SRC_AUTO_PICKUP_H
Functions
std::list< std::pair< item_location, int > > auto_pickup::select_items (const std::vector< item_stack::iterator > &from, const tripoint &location)
Select which items on the map tile should be auto-picked up.
auto_pickup::player_settings & get_auto_pickup ()
Macro Definition Documentation
CATA_SRC_AUTO_PICKUP_H
#define CATA_SRC_AUTO_PICKUP_H
Definition at line 3 of file auto_pickup.h.
Function Documentation
get_auto_pickup()
auto_pickup::player_settings& get_auto_pickup ()
Definition at line 52 of file auto_pickup.cpp.
 {
     static auto_pickup::player_settings single_instance;
     return single_instance;
 }
Referenced by advanced_inventory::display(), game::do_regular_action(), get_autopickup_rule(), game::inventory_item_menu(), game::load(), game::load_static_data(), main_menu::opening_screen(), game::save(), and game::start_game().