Cataclysm DDA: src/auto_note.cpp File Reference
auto_note.cpp File Reference
#include "auto_note.h"
#include <cstddef>
#include <iosfwd>
#include <iterator>
#include <string>
#include <type_traits>
#include "cata_utility.h"
#include "color.h"
#include "cursesdef.h"
#include "filesystem.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "generic_factory.h"
#include "input_context.h"
#include "json.h"
#include "map_extras.h"
#include "options.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translation.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
Namespaces
auto_notes
Functions
auto_notes::auto_note_settings & get_auto_notes_settings ()
Function Documentation
get_auto_notes_settings()
auto_notes::auto_note_settings& get_auto_notes_settings ()
Definition at line 606 of file auto_note.cpp.
 {
     static auto_notes::auto_note_settings staticSettings;
     return staticSettings;
 }
Referenced by overmap::add_extra_note(), auto_notes::auto_note_manager_gui::auto_note_manager_gui(), game::do_regular_action(), auto_notes::auto_note_manager_gui::fill_custom_symbols_cache(), game::load(), game::load_static_data(), game::save(), auto_notes::auto_note_manager_gui::show(), and game::start_game().