Cataclysm DDA: src/avatar_action.cpp File Reference
avatar_action.cpp File Reference
#include "avatar_action.h"
#include <algorithm>
#include <climits>
#include <cstdlib>
#include <list>
#include <map>
#include <memory>
#include <ostream>
#include <set>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>
#include "action.h"
#include "activity_actor_definitions.h"
#include "avatar.h"
#include "body_part_set.h"
#include "calendar.h"
#include "character.h"
#include "color.h"
#include "creature.h"
#include "creature_tracker.h"
#include "debug.h"
#include "enums.h"
#include "fault.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "gun_mode.h"
#include "inventory.h"
#include "item.h"
#include "item_location.h"
#include "item_pocket.h"
#include "itype.h"
#include "line.h"
#include "magic_enchantment.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "math_defines.h"
#include "messages.h"
#include "monster.h"
#include "move_mode.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "pimpl.h"
#include "player_activity.h"
#include "projectile.h"
#include "ranged.h"
#include "ret_val.h"
#include "rng.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
Macros
#define dbg(x) DebugLog((x),D_SDL) << __FILE__ << ":" << __LINE__ << ": "
Functions
static bool check_water_affect_items (avatar &you)
static float rate_critter (const Creature &c)
static void update_lum (item_location loc, bool add)
Variables
static const efftype_id effect_amigara ("amigara")
static const efftype_id effect_glowing ("glowing")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_hunger_engorged ("hunger_engorged")
static const efftype_id effect_incorporeal ("incorporeal")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_psi_stunned ("psi_stunned")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_winded ("winded")
static const furn_str_id furn_f_safe_c ("f_safe_c")
static const itype_id itype_swim_fins ("swim_fins")
static const move_mode_id move_mode_prone ("prone")
static const skill_id skill_swimming ("swimming")
static const ter_str_id ter_t_door_bar_locked ("t_door_bar_locked")
static const ter_str_id ter_t_door_locked ("t_door_locked")
static const ter_str_id ter_t_door_locked_alarm ("t_door_locked_alarm")
static const ter_str_id ter_t_door_locked_interior ("t_door_locked_interior")
static const ter_str_id ter_t_door_locked_peep ("t_door_locked_peep")
static const ter_str_id ter_t_fault ("t_fault")
static const ter_str_id ter_t_grass ("t_grass")
static const ter_str_id ter_t_grass_alien ("t_grass_alien")
static const ter_str_id ter_t_grass_dead ("t_grass_dead")
static const ter_str_id ter_t_grass_golf ("t_grass_golf")
static const ter_str_id ter_t_grass_white ("t_grass_white")
static const trait_id trait_GRAZER ("GRAZER")
static const trait_id trait_RUMINANT ("RUMINANT")
static const trait_id trait_SHELL2 ("SHELL2")
static const trait_id trait_SHELL3 ("SHELL3")
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_SDL) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 101 of file avatar_action.cpp.
Function Documentation
check_water_affect_items()
static bool check_water_affect_items (avatar & you) static
Definition at line 103 of file avatar_action.cpp.
 {
     if( you.has_effect( effect_stunned ) || you.has_effect( effect_psi_stunned ) ) {
         return true;
     }
     std::vector<item_location> dissolved;
     std::vector<item_location> destroyed;
     std::vector<item_location> wet;
     for( item_location &loc : you.all_items_loc() ) {
         if( loc->has_flag( flag_WATER_DISSOLVE ) && !loc.protected_from_liquids() ) {
             dissolved.emplace_back( loc );
         } else if( loc->has_flag( flag_WATER_BREAK ) && !loc->is_broken()
                    && !loc.protected_from_liquids() ) {
             destroyed.emplace_back( loc );
         } else if( loc->has_flag( flag_WATER_BREAK_ACTIVE ) && !loc->is_broken()
                    && !loc.protected_from_liquids() ) {
             wet.emplace_back( loc );
         }
     }
     if( dissolved.empty() && destroyed.empty() && wet.empty() ) {
         return query_yn( _( "Dive into the water?" ) );
     }
     uilist menu;
     menu.title = _( "Diving will destroy the following items.  Proceed?" );
     menu.text = _( "These items are not inside a waterproof container." );
     menu.addentry( 0, true, 'N', _( "No" ) );
     menu.addentry( 1, true, 'Y', _( "Yes" ) );
     auto add_header = [&menu]( const std::string & str ) {
         menu.addentry( -1, false, -1, "" );
         uilist_entry header( -1, false, -1, str, c_yellow, c_yellow );
         header.force_color = true;
         menu.entries.push_back( header );
     };
     if( !dissolved.empty() ) {
         add_header( _( "Will be dissolved:" ) );
         for( item_location &it : dissolved ) {
             menu.addentry( -1, false, -1, it->display_name() );
         }
     }
     if( !destroyed.empty() ) {
         add_header( _( "Will be destroyed:" ) );
         for( item_location &it : destroyed ) {
             menu.addentry( -1, false, -1, it->display_name() );
         }
     }
     if( !wet.empty() ) {
         add_header( _( "Will get wet:" ) );
         for( item_location &it : wet ) {
             menu.addentry( -1, false, -1, it->display_name() );
         }
     }
     menu.query();
     if( menu.ret != 1 ) {
         you.add_msg_if_player( _( "You back away from the water." ) );
         return false;
     }
     return true;
 }
References _, debug_menu::add_header(), Character::add_msg_if_player(), uilist::addentry(), Character::all_items_loc(), c_yellow, effect_psi_stunned, effect_stunned, uilist::entries, flag_WATER_BREAK, flag_WATER_BREAK_ACTIVE, flag_WATER_DISSOLVE, uilist_entry::force_color, Creature::has_effect(), uilist::query(), query_yn(), uilist::ret, uilist::text, uilist::title, and wet.
Referenced by avatar_action::move().
rate_critter()
static float rate_critter (const Creature & c) static
Definition at line 699 of file avatar_action.cpp.
 {
     const npc *np = dynamic_cast<const npc *>( &c );
     if( np != nullptr ) {
         item_location wielded = np->get_wielded_item();
         if( wielded ) {
             return np->weapon_value( *wielded );
         } else {
             return np->unarmed_value();
         }
     }
     const monster *m = dynamic_cast<const monster *>( &c );
     return m->type->difficulty;
 }
References c, mtype::difficulty, Character::get_wielded_item(), monster::type, Character::unarmed_value(), and Character::weapon_value().
update_lum()
static void update_lum (item_location loc, bool add) static
Definition at line 1093 of file avatar_action.cpp.
 {
     switch( loc.where() ) {
         case item_location::type::map:
             get_map().update_lum( loc, add );
             break;
         default:
             break;
     }
 }
References get_map(), item_location::map, map::update_lum(), and item_location::where().
Referenced by avatar_action::use_item().
Variable Documentation
effect_amigara
const efftype_id effect_amigara("amigara") ("amigara") static
Referenced by avatar_action::move().
effect_glowing
const efftype_id effect_glowing("glowing") ("glowing") static
Referenced by avatar_action::swim().
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by avatar_action::move().
effect_hunger_engorged
const efftype_id effect_hunger_engorged("hunger_engorged") ("hunger_engorged") static
Referenced by avatar_action::eat_here().
effect_incorporeal
const efftype_id effect_incorporeal("incorporeal") ("incorporeal") static
Referenced by avatar_action::move(), avatar_action::plthrow(), and avatar_action::use_item().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by avatar_action::swim().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by avatar_action::move().
effect_psi_stunned
const efftype_id effect_psi_stunned("psi_stunned") ("psi_stunned") static
Referenced by check_water_affect_items(), and avatar_action::move().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by avatar_action::move().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by check_water_affect_items(), and avatar_action::move().
effect_winded
const efftype_id effect_winded("winded") ("winded") static
Referenced by avatar_action::swim().
furn_f_safe_c
const furn_str_id furn_f_safe_c("f_safe_c") ("f_safe_c") static
Referenced by avatar_action::move().
itype_swim_fins
const itype_id itype_swim_fins("swim_fins") ("swim_fins") static
Referenced by avatar_action::swim().
move_mode_prone
const move_mode_id move_mode_prone("prone") ("prone") static
Referenced by avatar_action::move().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by avatar_action::swim().
ter_t_door_bar_locked
const ter_str_id ter_t_door_bar_locked("t_door_bar_locked") ("t_door_bar_locked") static
Referenced by avatar_action::move().
ter_t_door_locked
const ter_str_id ter_t_door_locked("t_door_locked") ("t_door_locked") static
Referenced by avatar_action::move().
ter_t_door_locked_alarm
const ter_str_id ter_t_door_locked_alarm("t_door_locked_alarm") ("t_door_locked_alarm") static
Referenced by avatar_action::move().
ter_t_door_locked_interior
const ter_str_id ter_t_door_locked_interior("t_door_locked_interior") ("t_door_locked_interior") static
Referenced by avatar_action::move().
ter_t_door_locked_peep
const ter_str_id ter_t_door_locked_peep("t_door_locked_peep") ("t_door_locked_peep") static
Referenced by avatar_action::move().
ter_t_fault
const ter_str_id ter_t_fault("t_fault") ("t_fault") static
Referenced by avatar_action::move().
ter_t_grass
const ter_str_id ter_t_grass("t_grass") ("t_grass") static
Referenced by avatar_action::eat_here().
ter_t_grass_alien
const ter_str_id ter_t_grass_alien("t_grass_alien") ("t_grass_alien") static
Referenced by avatar_action::eat_here().
ter_t_grass_dead
const ter_str_id ter_t_grass_dead("t_grass_dead") ("t_grass_dead") static
Referenced by avatar_action::eat_here().
ter_t_grass_golf
const ter_str_id ter_t_grass_golf("t_grass_golf") ("t_grass_golf") static
Referenced by avatar_action::eat_here().
ter_t_grass_white
const ter_str_id ter_t_grass_white("t_grass_white") ("t_grass_white") static
Referenced by avatar_action::eat_here().
trait_GRAZER
const trait_id trait_GRAZER("GRAZER") ("GRAZER") static
Referenced by avatar_action::eat_here().
trait_RUMINANT
const trait_id trait_RUMINANT("RUMINANT") ("RUMINANT") static
Referenced by avatar_action::eat_here().
trait_SHELL2
const trait_id trait_SHELL2("SHELL2") ("SHELL2") static
Referenced by avatar_action::move(), and avatar_action::plthrow().
trait_SHELL3
const trait_id trait_SHELL3("SHELL3") ("SHELL3") static
Referenced by avatar_action::move(), and avatar_action::plthrow().