Cataclysm DDA: src/avatar.h File Reference
avatar.h File Reference
#include <array>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <string_view>
#include <unordered_set>
#include <utility>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "character.h"
#include "character_id.h"
#include "coordinates.h"
#include "enums.h"
#include "game_constants.h"
#include "item.h"
#include "magic_teleporter_list.h"
#include "mdarray.h"
#include "point.h"
#include "type_id.h"
#include "units.h"
Classes
struct monster_visible_info
class avatar
struct avatar::daily_calories
Namespaces
catacurses
Contains the curses interface used by the whole game.
debug_menu
Macros
#define CATA_SRC_AVATAR_H
Functions
avatar & get_avatar ()
std::unique_ptr< talker > get_talker_for (avatar &me)
std::unique_ptr< talker > get_talker_for (avatar *me)
Macro Definition Documentation
CATA_SRC_AVATAR_H
#define CATA_SRC_AVATAR_H
Definition at line 3 of file avatar.h.
Function Documentation
get_avatar()
avatar& get_avatar ()
Definition at line 13817 of file game.cpp.
 {
     return g->u;
 }
Referenced by anonymous_namespace{item.cpp}::_stacks_clothing_size(), computer_session::action_complete_disable_external_power(), computer_session::action_emerg_ref_center(), advanced_inventory::action_examine(), advanced_inventory::action_move_item(), computer_session::action_repeater_mod(), Character::activate_bionic(), timed_event::actualize(), advanced_inventory_pane::add_items_from_area(), talker_npc::add_mission(), Character::add_traits(), construction::adjusted_time(), aim_activity_actor::aim_activity_actor(), map::apparent_light_helper(), jmapgen_remove_npcs::apply(), item::armor_full_protection_info(), inventory::assign_empty_invlet(), talk_function::assign_mission(), anonymous_namespace{monexamine.cpp}::attach_bag_to(), effect_on_conditions::avatar_death(), talk_function::basecamp_mission(), item::basic_info(), basic_item_filter(), best_installer(), debug_menu::bleed_self(), item::book_info(), vehicle::build_electronics_menu(), map::build_map_cache(), zone_manager::cache_avatar_location(), zone_manager::cache_data(), veh_interact::calc_lift_requirements(), disable_activity_actor::can_disable_or_reprogram(), can_interact_at(), overmap::can_place_special(), veh_interact::can_remove_part(), shopkeeper_item_group::can_sell(), move_furniture_activity_actor::canceled(), veh_interact::cant_do(), anonymous_namespace{item_tname.cpp}::category(), drawsq_params::center(), debug_menu::change_weather(), debug_menu::character_edit_desc_menu(), debug_menu::character_edit_menu(), check_deploy_square(), choose_adjacent_highlight(), basecamp_action_components::choose_components(), basecamp::choose_new_leader(), turn_handler::cleanup_at_end(), doors::close_door(), anonymous_namespace{item_tname.cpp}::clothing_size(), display::colorized_compass_legend_text(), complete_construction(), construction_menu(), basecamp_action_components::consume_components(), activity_handlers::consume_drink_menu_do_turn(), Character::consume_effects(), activity_handlers::consume_food_menu_do_turn(), activity_handlers::consume_meds_menu_do_turn(), avatar::control_npc(), debug_menu::control_npc_menu(), avatar::control_npc_menu(), create_advanced_inv(), creature_tracker::creature_at(), creature_select_menu(), debug_menu::damage_self(), debug_menu::debug(), debug_menu::debug_menu_game_state(), debug_menu::debug_menu_spawn_vehicle(), stats_tracker::deserialize(), map::detach_vehicle(), diary::diary(), spell_effect::directed_push(), Character::disassemble(), Character::dismount(), advanced_inventory::display(), faction_manager::display(), overmap_ui::display(), item::display_name(), veh_interact::do_install(), veh_interact::do_mend(), veh_interact::do_remove(), veh_interact::do_repair(), aim_activity_actor::do_turn(), editmap::do_ui_invalidation(), item::dps(), map::draw(), overmap_ui::draw_ascii(), anonymous_namespace{animation.cpp}::draw_bullet_curses(), mission_ui_impl::draw_controls(), explosion_handler::draw_custom_explosion(), anonymous_namespace{animation.cpp}::draw_custom_explosion_curses(), anonymous_namespace{animation.cpp}::draw_explosion_curses(), anonymous_namespace{animation.cpp}::draw_hit_player_curses(), anonymous_namespace{animation.cpp}::draw_line_curses(), map::draw_maptile(), mission_ui_impl::draw_mission_names(), overmap_ui::draw_om_sidebar(), anonymous_namespace{animation.cpp}::draw_sct_curses(), mission_ui_impl::draw_selected_description(), dummy_wgt_render(), dialogue::dynamic_line(), activity_handlers::eat_menu_do_turn(), editmap::edit(), debug_menu::mission_debug::edit_player(), eff_fun_fake_common_cold(), eff_fun_fake_flu(), map::emit_field(), trap::examine(), npc::execute_action(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_active_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control_menu(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_mission(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_monsters_in_direction(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_safe_mode_trigger(), mission::fail(), item::final_info(), Character::fine_detail_vision_mod(), consume_activity_actor::finish(), firstaid_activity_actor::finish(), fire(), iuse::fish_trap_tick(), anonymous_namespace{item_tname.cpp}::food_traits(), Character::forced_dismount(), map::furn_set(), iuse::geiger_active(), mapgen_basic_container::generate(), Character::get_active_moncams(), get_character_from_id(), get_compass_for_direction(), disable_activity_actor::get_disable_turns(), player_activity::get_distractions(), kill_tracker::get_kills_text(), map::get_known_connections(), get_memory_at(), talker_npc::get_topics(), weather_generator::get_weather_conditions(), talker_npc::give_item_to(), anonymous_namespace{monexamine.cpp}::give_items_to(), grab(), iuse::granade_act(), iuse::grenade_inc_act(), item::gun_info(), iuse::gun_repair(), handle_key_blocking_activity(), vehicle::handle_potential_theft(), haul_toggle(), game_menus::inv::holster(), pointmenu_cb::impl_t::impl_t(), debug_menu::import_folower(), learn_spell_actor::info(), advanced_inv_area::init(), tutorial_game::init(), exosuit_interact::insert_replace_activate_mod(), iexamine::intercom(), mission::is_complete(), read_inventory_preset::is_known(), debug_menu::kill_area(), Character::knock_back_to(), talk_function::lead_to_safety(), diary::load(), load_available_constructions(), main_menu::load_game(), aim_activity_actor::load_RAS_weapon(), anonymous_namespace{item_tname.cpp}::location_hint(), icg_entry::matches(), widget_clause::meets_condition(), map::memory_clear_vehicle_points(), vehicle::merge_appliance_into_grid(), monexamine::mfriend_menu(), iuse::molotov_lit(), anonymous_namespace{do_turn.cpp}::monmove(), Character::mount_creature(), avatar_action::move(), activity_handlers::move_cost(), pocket_favorite_callback::move_item(), iuse::multicooker(), iuse::multicooker_tick(), Character::needs_food(), main_menu::new_character_tab(), diary::new_page(), debug_menu::normalize_body(), memorial_logger::notify(), eoc_events::notify(), npc_select_menu(), effect_on_conditions::om_move(), mission::on_creature_death(), item::on_drop(), iexamine::on_smoke_out(), open(), open_movement_mode_menu(), main_menu::opening_screen(), orient_part(), anonymous_namespace{do_turn.cpp}::overmap_npc_move(), mission_type::parse_funcs(), map::partial_con_remove(), Character::perform_technique(), anonymous_namespace{monexamine.cpp}::pet_armor_loc(), monexamine::pet_menu(), photo_def_for_camera_point(), pick_usb(), overmap_special::place(), place_construction(), pldrive(), Character::pour_into(), effect_on_conditions::prevent_death(), item::process_fake_mill(), monster::process_one_effect(), effect_on_conditions::process_reactivate(), iuse::radiocontrol_tick(), rate_location(), read(), advanced_inventory::recalc_pane(), basecamp::recruit_return(), teleporter_callback::refresh(), iuse::remoteveh(), debug_menu::mission_debug::remove_mission(), map::remove_trap(), DefaultRemovePartHandler::removed(), aim_activity_actor::restore_view(), mission_start::reveal_refugee_center(), reveal_map_actor::reveal_targets(), target_ui::run(), pointmenu_cb::impl_t::select(), veh_interact::serialize_activity(), mission_util::set_assign_om_target(), debug_menu::set_automove(), advanced_inv_area::set_container_position(), debug_menu::show_sound(), sleep(), smash(), spell_effect::spawn_ethereal_item(), debug_menu::spawn_npc(), monster::speed_description(), diary::spell_changes(), Character::stagger(), diary::store(), anonymous_namespace{monexamine.cpp}::tack_loc(), takeoff(), map::ter_set(), item::tool_info(), npc_trading::trade(), ter_furn_transform::transform(), iexamine::translocator(), map::trap_set(), vehicle::turrets_aim(), aim_activity_actor::unload_RAS_weapon(), update_mapgen_function_json::update_map(), veh_interact::update_part_requirements(), computer_session::use(), inscribe_actor::use(), vehicle::use_dishwasher(), vehicle::use_monster_capture(), vehicle::use_washing_machine(), anonymous_namespace{item_tname.cpp}::vars(), debug_menu::vehicle_battery_charge(), debug_menu::vehicle_export(), map::vehicle_vehicle_collision(), wear(), main_menu::world_tab(), mission::wrap_up(), anonymous_namespace{debug_menu.cpp}::write_min_archive(), memorial_logger::write_text_memorial(), and pointmenu_cb::impl_t::~impl_t().
get_talker_for() [1/2]
std::unique_ptr<talker> get_talker_for (avatar & me)
Definition at line 1795 of file avatar.cpp.
 {
     return std::make_unique<talker_avatar>( &me );
 }
Referenced by spell::accuracy(), effect_on_condition::activate(), Character::activate_bionic(), activate_consume_eocs(), martialart::activate_eocs(), Character::activate_mutation(), spell::aoe(), spell::aoe_string(), effect_on_conditions::avatar_death(), cata_event_dispatch::avatar_moves(), item::basic_info(), eoc_examine_actor::call(), leap_actor::call(), mon_spellcasting_actor::call(), melee_actor::call(), gun_actor::call(), overmap::can_place_special(), shopkeeper_item_group::can_sell(), spell::casting_time(), debug_menu::change_spells(), debug_menu::change_weather(), game::chat(), Character::complete_craft(), spell::create_field(), spell::damage(), spell::damage_dot(), spell::damage_string(), Character::deactivate_bionic(), Character::deactivate_mutation(), debug_menu::debug(), monster::die(), faction_manager::display(), player_activity::do_turn(), mission_ui_impl::draw_selected_description(), draw_spellbook_info(), spell::duration(), spell::duration_string(), spell_effect::effect_on_condition(), map::emit_field(), spell::energy_cost(), Character::evaluate_techniques(), npc_attack_spell::evaluate_tripoint(), game::examine(), npc::execute_action(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), spell::field_intensity(), enchant_cache::force_add(), mapgen_basic_container::generate(), spell::get_difficulty(), spell::get_max_level(), enchantment::get_value_add(), enchantment::get_value_multiply(), weather_generator::get_weather_conditions(), spell::in_aoe(), iexamine::intercom(), enchantment::is_active(), mission::is_complete(), spell::is_max_level(), reflex_activation_data::is_trigger_true(), effect_on_conditions::load_existing_character(), effect_on_conditions::load_new_character(), icg_entry::matches(), widget_clause::meets_condition(), monexamine::mfriend_menu(), spell::min_leveled_accuracy(), spell::min_leveled_aoe(), spell::min_leveled_damage(), spell::min_leveled_dot(), spell::min_leveled_duration(), suffer::mutation_power(), eoc_events::notify(), game::npc_menu(), effect_on_conditions::om_move(), damage_type::ondamage_effects(), damage_type::onhit_effects(), mission_type::parse_funcs(), parse_tags(), Character::perform_technique(), monexamine::pet_menu(), overmap_special::place(), effect_on_conditions::prevent_death(), Character::process_bionic(), effect_on_conditions::process_effect_on_conditions(), effect_on_conditions::process_reactivate(), spell::range(), mission_start::reveal_refugee_center(), addiction::run_effect(), run_item_eocs(), event_bus::send_with_talker(), mission_util::set_assign_om_target(), debug_menu::spell_description(), avatar::talk_to(), known_magic::time_to_learn_spell(), effect_on_conditons_actor::use(), and game::use_computer().
get_talker_for() [2/2]
std::unique_ptr<talker> get_talker_for (avatar * me)
Definition at line 1799 of file avatar.cpp.
 {
     return std::make_unique<talker_avatar>( me );
 }