Cataclysm DDA: src/avatar.cpp File Reference
avatar.cpp File Reference
#include "avatar.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <functional>
#include <iterator>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <utility>
#include "action.h"
#include "activity_actor_definitions.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_id.h"
#include "character_martial_arts.h"
#include "color.h"
#include "creature.h"
#include "cursesdef.h"
#include "debug.h"
#include "diary.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "faction.h"
#include "field_type.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "help.h"
#include "inventory.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_memory.h"
#include "mapdata.h"
#include "martialarts.h"
#include "messages.h"
#include "mission.h"
#include "morale.h"
#include "morale_types.h"
#include "move_mode.h"
#include "mutation.h"
#include "npc.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "pathfinding.h"
#include "pimpl.h"
#include "profession.h"
#include "ranged.h"
#include "recipe.h"
#include "ret_val.h"
#include "rng.h"
#include "scenario.h"
#include "skill.h"
#include "stomach.h"
#include "string_formatter.h"
#include "talker.h"
#include "talker_avatar.h"
#include "timed_event.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
Functions
std::unique_ptr< talker > get_talker_for (avatar &me)
std::unique_ptr< talker > get_talker_for (avatar *me)
Variables
static const bionic_id bio_cloak ("bio_cloak")
static const bionic_id bio_soporific ("bio_soporific")
static const efftype_id effect_alarm_clock ("alarm_clock")
static const efftype_id effect_boomered ("boomered")
static const efftype_id effect_depressants ("depressants")
static const efftype_id effect_happy ("happy")
static const efftype_id effect_irradiated ("irradiated")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_pkill ("pkill")
static const efftype_id effect_psi_stunned ("psi_stunned")
static const efftype_id effect_relax_gas ("relax_gas")
static const efftype_id effect_sad ("sad")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_sleep_deprived ("sleep_deprived")
static const efftype_id effect_slept_through_alarm ("slept_through_alarm")
static const efftype_id effect_stim ("stim")
static const efftype_id effect_stim_overdose ("stim_overdose")
static const efftype_id effect_stunned ("stunned")
static const faction_id faction_your_followers ("your_followers")
static const itype_id itype_guidebook ("guidebook")
static const itype_id itype_mut_longpull ("mut_longpull")
static const json_character_flag json_flag_ALARMCLOCK ("ALARMCLOCK")
static const json_character_flag json_flag_PAIN_IMMUNE ("PAIN_IMMUNE")
static const json_character_flag json_flag_WEBBED_HANDS ("WEBBED_HANDS")
static const move_mode_id move_mode_crouch ("crouch")
static const move_mode_id move_mode_prone ("prone")
static const move_mode_id move_mode_run ("run")
static const move_mode_id move_mode_walk ("walk")
static const string_id< monfaction > monfaction_player ("player")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_dirtmound ("t_dirtmound")
static const ter_str_id ter_t_floor ("t_floor")
static const ter_str_id ter_t_grass ("t_grass")
static const ter_str_id ter_t_pit ("t_pit")
static const ter_str_id ter_t_pit_shallow ("t_pit_shallow")
static const trait_id trait_ARACHNID_ARMS ("ARACHNID_ARMS")
static const trait_id trait_ARACHNID_ARMS_OK ("ARACHNID_ARMS_OK")
static const trait_id trait_CENOBITE ("CENOBITE")
static const trait_id trait_CHITIN2 ("CHITIN2")
static const trait_id trait_CHITIN3 ("CHITIN3")
static const trait_id trait_CHITIN_FUR3 ("CHITIN_FUR3")
static const trait_id trait_CHLOROMORPH ("CHLOROMORPH")
static const trait_id trait_COMPOUND_EYES ("COMPOUND_EYES")
static const trait_id trait_DEBUG_CLOAK ("DEBUG_CLOAK")
static const trait_id trait_INSECT_ARMS ("INSECT_ARMS")
static const trait_id trait_INSECT_ARMS_OK ("INSECT_ARMS_OK")
static const trait_id trait_M_SKIN3 ("M_SKIN3")
static const trait_id trait_PROF_DICEMASTER ("PROF_DICEMASTER")
static const trait_id trait_SHELL2 ("SHELL2")
static const trait_id trait_SHELL3 ("SHELL3")
static const trait_id trait_STIMBOOST ("STIMBOOST")
static const trait_id trait_THICK_SCALES ("THICK_SCALES")
static const trait_id trait_THRESH_SPIDER ("THRESH_SPIDER")
static const trait_id trait_UNDINE_SLEEP_WATER ("UNDINE_SLEEP_WATER")
static const trait_id trait_WATERSLEEP ("WATERSLEEP")
static const trait_id trait_WEB_SPINNER ("WEB_SPINNER")
static const trait_id trait_WEB_WALKER ("WEB_WALKER")
static const trait_id trait_WEB_WEAVER ("WEB_WEAVER")
static const trait_id trait_WHISKERS ("WHISKERS")
static const trait_id trait_WHISKERS_RAT ("WHISKERS_RAT")
static const std::array< int, 20 > xp_cutoffs
Function Documentation
get_talker_for() [1/2]
std::unique_ptr<talker> get_talker_for (avatar & me)
Definition at line 1795 of file avatar.cpp.
 {
     return std::make_unique<talker_avatar>( &me );
 }
Referenced by spell::accuracy(), effect_on_condition::activate(), Character::activate_bionic(), activate_consume_eocs(), martialart::activate_eocs(), Character::activate_mutation(), spell::aoe(), spell::aoe_string(), effect_on_conditions::avatar_death(), cata_event_dispatch::avatar_moves(), item::basic_info(), eoc_examine_actor::call(), leap_actor::call(), mon_spellcasting_actor::call(), melee_actor::call(), gun_actor::call(), overmap::can_place_special(), shopkeeper_item_group::can_sell(), spell::casting_time(), debug_menu::change_spells(), debug_menu::change_weather(), game::chat(), Character::complete_craft(), spell::create_field(), spell::damage(), spell::damage_dot(), spell::damage_string(), Character::deactivate_bionic(), Character::deactivate_mutation(), debug_menu::debug(), monster::die(), faction_manager::display(), player_activity::do_turn(), mission_ui_impl::draw_selected_description(), draw_spellbook_info(), spell::duration(), spell::duration_string(), spell_effect::effect_on_condition(), map::emit_field(), spell::energy_cost(), Character::evaluate_techniques(), npc_attack_spell::evaluate_tripoint(), game::examine(), npc::execute_action(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), spell::field_intensity(), enchant_cache::force_add(), mapgen_basic_container::generate(), spell::get_difficulty(), spell::get_max_level(), enchantment::get_value_add(), enchantment::get_value_multiply(), weather_generator::get_weather_conditions(), spell::in_aoe(), iexamine::intercom(), enchantment::is_active(), mission::is_complete(), spell::is_max_level(), reflex_activation_data::is_trigger_true(), effect_on_conditions::load_existing_character(), effect_on_conditions::load_new_character(), icg_entry::matches(), widget_clause::meets_condition(), monexamine::mfriend_menu(), spell::min_leveled_accuracy(), spell::min_leveled_aoe(), spell::min_leveled_damage(), spell::min_leveled_dot(), spell::min_leveled_duration(), suffer::mutation_power(), eoc_events::notify(), game::npc_menu(), effect_on_conditions::om_move(), damage_type::ondamage_effects(), damage_type::onhit_effects(), mission_type::parse_funcs(), parse_tags(), Character::perform_technique(), monexamine::pet_menu(), overmap_special::place(), effect_on_conditions::prevent_death(), Character::process_bionic(), effect_on_conditions::process_effect_on_conditions(), effect_on_conditions::process_reactivate(), spell::range(), mission_start::reveal_refugee_center(), addiction::run_effect(), run_item_eocs(), event_bus::send_with_talker(), mission_util::set_assign_om_target(), debug_menu::spell_description(), avatar::talk_to(), known_magic::time_to_learn_spell(), effect_on_conditons_actor::use(), and game::use_computer().
get_talker_for() [2/2]
std::unique_ptr<talker> get_talker_for (avatar * me)
Definition at line 1799 of file avatar.cpp.
 {
     return std::make_unique<talker_avatar>( me );
 }
Variable Documentation
bio_cloak
const bionic_id bio_cloak("bio_cloak") ("bio_cloak") static
Referenced by avatar::basic_symbol_color().
bio_soporific
const bionic_id bio_soporific("bio_soporific") ("bio_soporific") static
Referenced by avatar::try_to_sleep().
effect_alarm_clock
const efftype_id effect_alarm_clock("alarm_clock") ("alarm_clock") static
Referenced by avatar::wake_up().
effect_boomered
const efftype_id effect_boomered("boomered") ("boomered") static
Referenced by avatar::basic_symbol_color().
effect_depressants
const efftype_id effect_depressants("depressants") ("depressants") static
Referenced by avatar::reset_stats().
effect_happy
const efftype_id effect_happy("happy") ("happy") static
Referenced by avatar::reset_stats().
effect_irradiated
const efftype_id effect_irradiated("irradiated") ("irradiated") static
Referenced by avatar::reset_stats().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by avatar::basic_symbol_color().
effect_pkill
const efftype_id effect_pkill("pkill") ("pkill") static
Referenced by avatar::reset_stats().
effect_psi_stunned
const efftype_id effect_psi_stunned("psi_stunned") ("psi_stunned") static
Referenced by avatar::basic_symbol_color().
effect_relax_gas
const efftype_id effect_relax_gas("relax_gas") ("relax_gas") static
Referenced by avatar::try_break_relax_gas().
effect_sad
const efftype_id effect_sad("sad") ("sad") static
Referenced by avatar::reset_stats().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by avatar::wake_up().
effect_sleep_deprived
const efftype_id effect_sleep_deprived("sleep_deprived") ("sleep_deprived") static
Referenced by avatar::reset_stats().
effect_slept_through_alarm
const efftype_id effect_slept_through_alarm("slept_through_alarm") ("slept_through_alarm") static
Referenced by avatar::wake_up().
effect_stim
const efftype_id effect_stim("stim") ("stim") static
Referenced by avatar::reset_stats().
effect_stim_overdose
const efftype_id effect_stim_overdose("stim_overdose") ("stim_overdose") static
Referenced by avatar::reset_stats().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by avatar::basic_symbol_color().
faction_your_followers
const faction_id faction_your_followers("your_followers") ("your_followers") static
Referenced by avatar::control_npc(), and avatar::get_faction().
itype_guidebook
const itype_id itype_guidebook("guidebook") ("guidebook") static
Referenced by avatar::read().
itype_mut_longpull
const itype_id itype_mut_longpull("mut_longpull") ("mut_longpull") static
Referenced by avatar::longpull().
json_flag_ALARMCLOCK
const json_character_flag json_flag_ALARMCLOCK("ALARMCLOCK") ("ALARMCLOCK") static
Referenced by avatar::wake_up().
json_flag_PAIN_IMMUNE
const json_character_flag json_flag_PAIN_IMMUNE("PAIN_IMMUNE") ("PAIN_IMMUNE") static
Referenced by avatar::add_pain_msg().
json_flag_WEBBED_HANDS
const json_character_flag json_flag_WEBBED_HANDS("WEBBED_HANDS") ("WEBBED_HANDS") static
Referenced by avatar::reset_stats().
monfaction_player
const string_id<monfaction> monfaction_player("player") ("player") static
Referenced by avatar::get_monster_faction().
move_mode_crouch
const move_mode_id move_mode_crouch("crouch") ("crouch") static
Referenced by avatar::activate_crouch_mode(), and avatar::toggle_crouch_mode().
move_mode_prone
const move_mode_id move_mode_prone("prone") ("prone") static
Referenced by avatar::toggle_prone_mode().
move_mode_run
const move_mode_id move_mode_run("run") ("run") static
Referenced by avatar::toggle_run_mode().
move_mode_walk
const move_mode_id move_mode_walk("walk") ("walk") static
Referenced by avatar::reset_move_mode(), avatar::toggle_crouch_mode(), avatar::toggle_prone_mode(), and avatar::toggle_run_mode().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by avatar::try_to_sleep().
ter_t_dirtmound
const ter_str_id ter_t_dirtmound("t_dirtmound") ("t_dirtmound") static
Referenced by avatar::try_to_sleep().
ter_t_floor
const ter_str_id ter_t_floor("t_floor") ("t_floor") static
Referenced by avatar::try_to_sleep().
ter_t_grass
const ter_str_id ter_t_grass("t_grass") ("t_grass") static
Referenced by avatar::try_to_sleep().
ter_t_pit
const ter_str_id ter_t_pit("t_pit") ("t_pit") static
Referenced by avatar::try_to_sleep().
ter_t_pit_shallow
const ter_str_id ter_t_pit_shallow("t_pit_shallow") ("t_pit_shallow") static
Referenced by avatar::try_to_sleep().
trait_ARACHNID_ARMS
const trait_id trait_ARACHNID_ARMS("ARACHNID_ARMS") ("ARACHNID_ARMS") static
Referenced by avatar::reset_stats().
trait_ARACHNID_ARMS_OK
const trait_id trait_ARACHNID_ARMS_OK("ARACHNID_ARMS_OK") ("ARACHNID_ARMS_OK") static
Referenced by avatar::reset_stats().
trait_CENOBITE
const trait_id trait_CENOBITE("CENOBITE") ("CENOBITE") static
Referenced by avatar::disp_morale().
trait_CHITIN2
const trait_id trait_CHITIN2("CHITIN2") ("CHITIN2") static
Referenced by avatar::reset_stats().
trait_CHITIN3
const trait_id trait_CHITIN3("CHITIN3") ("CHITIN3") static
Referenced by avatar::reset_stats().
trait_CHITIN_FUR3
const trait_id trait_CHITIN_FUR3("CHITIN_FUR3") ("CHITIN_FUR3") static
Referenced by avatar::reset_stats().
trait_CHLOROMORPH
const trait_id trait_CHLOROMORPH("CHLOROMORPH") ("CHLOROMORPH") static
Referenced by avatar::try_to_sleep().
trait_COMPOUND_EYES
const trait_id trait_COMPOUND_EYES("COMPOUND_EYES") ("COMPOUND_EYES") static
Referenced by avatar::reset_stats().
trait_DEBUG_CLOAK
const trait_id trait_DEBUG_CLOAK("DEBUG_CLOAK") ("DEBUG_CLOAK") static
Referenced by avatar::basic_symbol_color().
trait_INSECT_ARMS
const trait_id trait_INSECT_ARMS("INSECT_ARMS") ("INSECT_ARMS") static
Referenced by avatar::reset_stats().
trait_INSECT_ARMS_OK
const trait_id trait_INSECT_ARMS_OK("INSECT_ARMS_OK") ("INSECT_ARMS_OK") static
Referenced by avatar::reset_stats().
trait_M_SKIN3
const trait_id trait_M_SKIN3("M_SKIN3") ("M_SKIN3") static
Referenced by avatar::try_to_sleep().
trait_PROF_DICEMASTER
const trait_id trait_PROF_DICEMASTER("PROF_DICEMASTER") ("PROF_DICEMASTER") static
Referenced by avatar::read().
trait_SHELL2
const trait_id trait_SHELL2("SHELL2") ("SHELL2") static
Referenced by avatar::basic_symbol_color(), and avatar::try_to_sleep().
trait_SHELL3
const trait_id trait_SHELL3("SHELL3") ("SHELL3") static
Referenced by avatar::basic_symbol_color(), and avatar::try_to_sleep().
trait_STIMBOOST
const trait_id trait_STIMBOOST("STIMBOOST") ("STIMBOOST") static
Referenced by avatar::reset_stats().
trait_THICK_SCALES
const trait_id trait_THICK_SCALES("THICK_SCALES") ("THICK_SCALES") static
Referenced by avatar::reset_stats().
trait_THRESH_SPIDER
const trait_id trait_THRESH_SPIDER("THRESH_SPIDER") ("THRESH_SPIDER") static
Referenced by avatar::try_to_sleep().
trait_UNDINE_SLEEP_WATER
const trait_id trait_UNDINE_SLEEP_WATER("UNDINE_SLEEP_WATER") ("UNDINE_SLEEP_WATER") static
Referenced by avatar::try_to_sleep().
trait_WATERSLEEP
const trait_id trait_WATERSLEEP("WATERSLEEP") ("WATERSLEEP") static
Referenced by avatar::try_to_sleep().
trait_WEB_SPINNER
const trait_id trait_WEB_SPINNER("WEB_SPINNER") ("WEB_SPINNER") static
Referenced by avatar::try_to_sleep().
trait_WEB_WALKER
const trait_id trait_WEB_WALKER("WEB_WALKER") ("WEB_WALKER") static
Referenced by avatar::try_to_sleep().
trait_WEB_WEAVER
const trait_id trait_WEB_WEAVER("WEB_WEAVER") ("WEB_WEAVER") static
Referenced by avatar::try_to_sleep().
trait_WHISKERS
const trait_id trait_WHISKERS("WHISKERS") ("WHISKERS") static
Referenced by avatar::reset_stats().
trait_WHISKERS_RAT
const trait_id trait_WHISKERS_RAT("WHISKERS_RAT") ("WHISKERS_RAT") static
Referenced by avatar::reset_stats().
xp_cutoffs
const std::array<int, 20> xp_cutoffs static
Initial value:
= { {
        300, 900, 2700, 6500, 14000,
        23000, 34000, 48000, 64000, 85000,
        100000, 120000, 140000, 165000, 195000,
        225000, 265000, 305000, 355000, 405000
    }
}
Definition at line 1126 of file avatar.cpp.
Referenced by avatar::free_upgrade_points(), and avatar::upgrade_stat_prompt().