Cataclysm DDA: src/bionics.cpp File Reference
bionics.cpp File Reference
#include "bionics.h"
#include <algorithm>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <cstdint>
#include <forward_list>
#include <iterator>
#include <list>
#include <memory>
#include <optional>
#include <ostream>
#include <string>
#include <unordered_map>
#include <utility>
#include "action.h"
#include "activity_actor_definitions.h"
#include "activity_type.h"
#include "assign.h"
#include "avatar.h"
#include "avatar_action.h"
#include "ballistics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "character_attire.h"
#include "character_martial_arts.h"
#include "colony.h"
#include "color.h"
#include "condition.h"
#include "coordinates.h"
#include "creature.h"
#include "damage.h"
#include "debug.h"
#include "dialogue.h"
#include "dispersion.h"
#include "effect.h"
#include "effect_on_condition.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "field_type.h"
#include "flag.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game.h"
#include "generic_factory.h"
#include "global_vars.h"
#include "handle_liquid.h"
#include "init.h"
#include "inventory.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "json.h"
#include "json_error.h"
#include "line.h"
#include "magic_enchantment.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "material.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player_activity.h"
#include "pocket_type.h"
#include "point.h"
#include "projectile.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "safe_reference.h"
#include "sounds.h"
#include "string_formatter.h"
#include "talker.h"
#include "teleport.h"
#include "translations.h"
#include "ui.h"
#include "units.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "viewer.h"
#include "vpart_position.h"
#include "weather.h"
#include "weather_gen.h"
Classes
struct Character::bionic_fuels
Namespaces
anonymous_namespace{bionics.cpp}
Functions
std::vector< bodypart_id > get_occupied_bodyparts (const bionic_id &bid)
List of bodyparts occupied by a bionic.
static social_modifiers load_bionic_social_mods (const JsonObject &jo)
static bool attempt_recharge (Character &p, bionic &bio, units::energy &amount)
int bionic_success_chance (bool autodoc, int skill_level, int difficulty, const Character &target)
int bionic_manip_cos (float adjusted_skill, int bionic_difficulty)
std::string list_occupied_bps (const bionic_id &bio_id, const std::string &intro, const bool each_bp_on_new_line)
void reset_bionics ()
static bionic_id migrate_bionic_id (const bionic_id &original)
std::vector< bionic_id > bionics_cancelling_trait (const std::vector< bionic_id > &bios, const trait_id &tid)
Variables
static const activity_id ACT_OPERATION ("ACT_OPERATION")
static const bionic_id afs_bio_dopamine_stimulators ("afs_bio_dopamine_stimulators")
static const bionic_id bio_blood_anal ("bio_blood_anal")
static const bionic_id bio_cqb ("bio_cqb")
static const bionic_id bio_emp ("bio_emp")
static const bionic_id bio_evap ("bio_evap")
static const bionic_id bio_flashbang ("bio_flashbang")
static const bionic_id bio_geiger ("bio_geiger")
static const bionic_id bio_gills ("bio_gills")
static const bionic_id bio_jointservo ("bio_jointservo")
static const bionic_id bio_lighter ("bio_lighter")
static const bionic_id bio_lockpick ("bio_lockpick")
static const bionic_id bio_magnet ("bio_magnet")
static const bionic_id bio_meteorologist ("bio_meteorologist")
static const bionic_id bio_nanobots ("bio_nanobots")
static const bionic_id bio_painkiller ("bio_painkiller")
static const bionic_id bio_radscrubber ("bio_radscrubber")
static const bionic_id bio_remote ("bio_remote")
static const bionic_id bio_resonator ("bio_resonator")
static const bionic_id bio_shockwave ("bio_shockwave")
static const bionic_id bio_teleport ("bio_teleport")
static const bionic_id bio_torsionratchet ("bio_torsionratchet")
static const bionic_id bio_water_extractor ("bio_water_extractor")
static const efftype_id effect_assisted ("assisted")
static const efftype_id effect_asthma ("asthma")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_heating_bionic ("heating_bionic")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_operating ("operating")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_under_operation ("under_operation")
static const fault_id fault_bionic_salvaged ("fault_bionic_salvaged")
static const itype_id itype_anesthetic ("anesthetic")
static const itype_id itype_radiocontrol ("radiocontrol")
static const itype_id itype_remotevehcontrol ("remotevehcontrol")
static const itype_id itype_water_clean ("water_clean")
static const json_character_flag json_flag_BIONIC_GUN ("BIONIC_GUN")
static const json_character_flag json_flag_BIONIC_NPC_USABLE ("BIONIC_NPC_USABLE")
static const json_character_flag json_flag_BIONIC_POWER_SOURCE ("BIONIC_POWER_SOURCE")
static const json_character_flag json_flag_BIONIC_TOGGLED ("BIONIC_TOGGLED")
static const json_character_flag json_flag_BIONIC_WEAPON ("BIONIC_WEAPON")
static const json_character_flag json_flag_ENHANCED_VISION ("ENHANCED_VISION")
static const json_character_flag json_flag_MANUAL_CBM_INSTALLATION ("MANUAL_CBM_INSTALLATION")
static const json_character_flag json_flag_PAIN_IMMUNE ("PAIN_IMMUNE")
static const material_id fuel_type_metabolism ("metabolism")
static const material_id fuel_type_sun_light ("sunlight")
static const material_id fuel_type_wind ("wind")
static const material_id material_budget_steel ("budget_steel")
static const material_id material_ch_steel ("ch_steel")
static const material_id material_hc_steel ("hc_steel")
static const material_id material_iron ("iron")
static const material_id material_lc_steel ("lc_steel")
static const material_id material_mc_steel ("mc_steel")
static const material_id material_muscle ("muscle")
static const material_id material_qt_steel ("qt_steel")
static const material_id material_steel ("steel")
static const requirement_id requirement_data_anesthetic ("anesthetic")
static const skill_id skill_computer ("computer")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_mechanics ("mechanics")
static const trait_id trait_CENOBITE ("CENOBITE")
static const trait_id trait_DEBUG_BIONICS ("DEBUG_BIONICS")
static const trait_id trait_MASOCHIST_MED ("MASOCHIST_MED")
static const trait_id trait_NONE ("NONE")
static const trait_id trait_PROF_AUTODOC ("PROF_AUTODOC")
static const trait_id trait_PROF_MED ("PROF_MED")
static const trait_id trait_PYROMANIA ("PYROMANIA")
static const trait_id trait_THRESH_MEDICAL ("THRESH_MEDICAL")
generic_factory< bionic_data > anonymous_namespace{bionics.cpp}::bionic_factory ("bionic")
std::vector< bionic_id > anonymous_namespace{bionics.cpp}::faulty_bionics
Function Documentation
attempt_recharge()
static bool attempt_recharge (Character & p, bionic & bio, units::energy & amount) static
Parameters
p the player
bio the bionic that is meant to be recharged.
amount the amount of power that is to be spent recharging the bionic.
Returns
indicates whether we successfully charged the bionic.
Definition at line 1536 of file bionics.cpp.
 {
     const bionic_data &info = bio.info();
     units::energy power_cost = info.power_over_time;
     bool recharged = false;
     if( power_cost > 0_kJ ) {
         if( info.has_flag( STATIC( json_character_flag( "BIONIC_ARMOR_INTERFACE" ) ) ) ) {
             // Don't spend any power on armor interfacing unless we're wearing active powered armor.
             if( !p.worn.is_wearing_active_power_armor() ) {
                 const units::energy armor_power_cost = 1_kJ;
                 power_cost -= armor_power_cost;
             }
         }
         if( p.get_power_level() >= power_cost ) {
             // Set the recharging cost and charge the bionic.
             amount = power_cost;
             bio.charge_timer = info.charge_time;
             recharged = true;
         }
     }
     return recharged;
 }
References bionic_data::charge_time, bionic::charge_timer, Character::get_power_level(), bionic_data::has_flag(), bionic::info(), outfit::is_wearing_active_power_armor(), bionic_data::power_over_time, STATIC, and Character::worn.
Referenced by Character::process_bionic().
bionic_manip_cos()
int bionic_manip_cos (float adjusted_skill, int bionic_difficulty)
Definition at line 2040 of file bionics.cpp.
 {
     if( get_player_character().has_trait( trait_DEBUG_BIONICS ) ||
         get_player_character().has_flag( json_flag_MANUAL_CBM_INSTALLATION ) ) {
         return 100;
     }
     int chance_of_success = 0;
     // we will base chance_of_success on a ratio of skill and difficulty
     // when skill=difficulty, this gives us 1.  skill < difficulty gives a fraction.
     float skill_difficulty_parameter = static_cast<float>( adjusted_skill /
                                        ( 4.0 * bionic_difficulty ) );
     // when skill == difficulty, chance_of_success is 50%. Chance of success drops quickly below that
     // to reserve bionics for characters with the appropriate skill.  For more difficult bionics, the
     // curve flattens out just above 80%
     chance_of_success = static_cast<int>( ( 100 * skill_difficulty_parameter ) /
                                           ( skill_difficulty_parameter + std::sqrt( 1 / skill_difficulty_parameter ) ) );
     return chance_of_success;
 }
References get_player_character(), json_flag_MANUAL_CBM_INSTALLATION, sqrt(), and trait_DEBUG_BIONICS.
Referenced by bionic_success_chance(), and Character::uninstall_bionic().
bionic_success_chance()
int bionic_success_chance (bool autodoc, int skill_level, int difficulty, const Character & target)
Definition at line 2034 of file bionics.cpp.
 {
     return bionic_manip_cos( target.bionics_adjusted_skill( autodoc, skill_level ), difficulty );
 }
References iexamine::autodoc(), bionic_manip_cos(), and Character::bionics_adjusted_skill().
Referenced by best_installer(), Character::can_install_bionics(), Character::can_uninstall_bionic(), bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), Character::install_bionics(), game::save_cyborg(), and Character::uninstall_bionic().
bionics_cancelling_trait()
std::vector<bionic_id> bionics_cancelling_trait (const std::vector< bionic_id > & bios, const trait_id & tid)
Definition at line 3199 of file bionics.cpp.
 {
     // Vector of bionics to return
     std::vector<bionic_id> bionics_cancelling;
     // Search through the vector of of bionics, and see if the trait is cancelled by one of them
     for( const bionic_id &bid : bios ) {
         for( const trait_id &trait : bid->canceled_mutations ) {
             if( trait == tid ) {
                 bionics_cancelling.emplace_back( bid );
             }
         }
     }
     return bionics_cancelling;
 }
Referenced by set_traits().
get_occupied_bodyparts()
std::vector<bodypart_id> get_occupied_bodyparts (const bionic_id & bid)
List of bodyparts occupied by a bionic.
Definition at line 260 of file bionics.cpp.
 {
     std::vector<bodypart_id> parts;
     for( const std::pair<const string_id<body_part_type>, size_t> &element : bid->occupied_bodyparts ) {
         if( element.second > 0 ) {
             parts.push_back( element.first.id() );
         }
     }
     return parts;
 }
References bionic_data::occupied_bodyparts.
Referenced by Character::is_installable(), and activity_handlers::operation_do_turn().
list_occupied_bps()
std::string list_occupied_bps (const bionic_id & bio_id, const std::string & intro, const bool each_bp_on_new_line)
Definition at line 2622 of file bionics.cpp.
 {
     if( bio_id->occupied_bodyparts.empty() ) {
         return "";
     }
     std::string desc = intro;
     for( const std::pair<const bodypart_str_id, size_t> &elem : bio_id->occupied_bodyparts ) {
         desc += ( each_bp_on_new_line ? "\n" : " " );
         //~ <Bodypart name> (<number of occupied slots> slots);
         desc += string_format( _( "%s (%i slots);" ),
                                body_part_name_as_heading( elem.first.id(), 1 ),
                                elem.second );
     }
     return desc;
 }
References _, body_part_name_as_heading(), bionic_data::occupied_bodyparts, and string_format().
Referenced by item::bionic_info(), and draw_description().
load_bionic_social_mods()
static social_modifiers load_bionic_social_mods (const JsonObject & jo) static
Definition at line 293 of file bionics.cpp.
 {
     social_modifiers ret;
     jo.read( "lie", ret.lie );
     jo.read( "persuade", ret.persuade );
     jo.read( "intimidate", ret.intimidate );
     return ret;
 }
References JsonObject::read(), and cata::hash64_detail::ret.
Referenced by bionic_data::load().
migrate_bionic_id()
static bionic_id migrate_bionic_id (const bionic_id & original) static
Definition at line 3118 of file bionics.cpp.
 {
     bionic_id bid = original;
     // limit up to 10 migrations per bionic (guard in case of accidental loops)
     for( int i = 0; i < 10; i++ ) {
         const auto &migration_it = bionic_data::migrations.find( bid );
         if( migration_it == bionic_data::migrations.cend() ) {
             break;
         }
         bid = migration_it->second;
     }
     if( bid != original ) {
         DebugLog( D_WARNING, D_MAIN ) << "Migrating bionic with id " << original.str() << " to " <<
                                       bid.str();
     }
     return bid;
 }
References D_MAIN, D_WARNING, DebugLog(), bionic_data::migrations, and string_id< T >::str().
Referenced by bionic::deserialize().
reset_bionics()
void reset_bionics ()
Definition at line 2900 of file bionics.cpp.
 {
     bionic_data::migrations.clear();
     faulty_bionics.clear();
     bionic_factory.reset();
 }
References anonymous_namespace{bionics.cpp}::bionic_factory, anonymous_namespace{bionics.cpp}::faulty_bionics, and bionic_data::migrations.
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
ACT_OPERATION
const activity_id ACT_OPERATION("ACT_OPERATION") ("ACT_OPERATION") static
Referenced by Character::install_bionics(), and Character::uninstall_bionic().
afs_bio_dopamine_stimulators
const bionic_id afs_bio_dopamine_stimulators("afs_bio_dopamine_stimulators") ("afs_bio_dopamine_stimulators") static
Referenced by Character::process_bionic().
bio_blood_anal
const bionic_id bio_blood_anal("bio_blood_anal") ("bio_blood_anal") static
Referenced by Character::activate_bionic().
bio_cqb
const bionic_id bio_cqb("bio_cqb") ("bio_cqb") static
Referenced by Character::activate_bionic(), and Character::deactivate_bionic().
bio_emp
const bionic_id bio_emp("bio_emp") ("bio_emp") static
Referenced by Character::activate_bionic().
bio_evap
const bionic_id bio_evap("bio_evap") ("bio_evap") static
Referenced by Character::activate_bionic(), and Character::process_bionic().
bio_flashbang
const bionic_id bio_flashbang("bio_flashbang") ("bio_flashbang") static
Referenced by Character::activate_bionic().
bio_geiger
const bionic_id bio_geiger("bio_geiger") ("bio_geiger") static
Referenced by Character::activate_bionic().
bio_gills
const bionic_id bio_gills("bio_gills") ("bio_gills") static
Referenced by Character::process_bionic().
bio_jointservo
const bionic_id bio_jointservo("bio_jointservo") ("bio_jointservo") static
Referenced by Character::activate_bionic().
bio_lighter
const bionic_id bio_lighter("bio_lighter") ("bio_lighter") static
Referenced by Character::activate_bionic().
bio_lockpick
const bionic_id bio_lockpick("bio_lockpick") ("bio_lockpick") static
Referenced by Character::activate_bionic().
bio_magnet
const bionic_id bio_magnet("bio_magnet") ("bio_magnet") static
Referenced by Character::activate_bionic().
bio_meteorologist
const bionic_id bio_meteorologist("bio_meteorologist") ("bio_meteorologist") static
Referenced by Character::activate_bionic().
bio_nanobots
const bionic_id bio_nanobots("bio_nanobots") ("bio_nanobots") static
Referenced by Character::process_bionic().
bio_painkiller
const bionic_id bio_painkiller("bio_painkiller") ("bio_painkiller") static
Referenced by Character::has_enough_anesth(), and Character::process_bionic().
bio_radscrubber
const bionic_id bio_radscrubber("bio_radscrubber") ("bio_radscrubber") static
Referenced by Character::activate_bionic().
bio_remote
const bionic_id bio_remote("bio_remote") ("bio_remote") static
Referenced by Character::activate_bionic(), Character::deactivate_bionic(), and Character::process_bionic().
bio_resonator
const bionic_id bio_resonator("bio_resonator") ("bio_resonator") static
Referenced by Character::activate_bionic().
bio_shockwave
const bionic_id bio_shockwave("bio_shockwave") ("bio_shockwave") static
Referenced by Character::activate_bionic().
bio_teleport
const bionic_id bio_teleport("bio_teleport") ("bio_teleport") static
Referenced by Character::activate_bionic().
bio_torsionratchet
const bionic_id bio_torsionratchet("bio_torsionratchet") ("bio_torsionratchet") static
Referenced by Character::activate_bionic().
bio_water_extractor
const bionic_id bio_water_extractor("bio_water_extractor") ("bio_water_extractor") static
Referenced by Character::activate_bionic().
effect_assisted
const efftype_id effect_assisted("assisted") ("assisted") static
Referenced by Character::bionics_adjusted_skill().
effect_asthma
const efftype_id effect_asthma("asthma") ("asthma") static
Referenced by Character::process_bionic().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by Character::process_bionic().
effect_heating_bionic
const efftype_id effect_heating_bionic("heating_bionic") ("heating_bionic") static
Referenced by Character::heat_emission().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by Character::introduce_into_anesthesia(), and Character::uninstall_bionic().
effect_operating
const efftype_id effect_operating("operating") ("operating") static
Referenced by Character::uninstall_bionic().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by Character::uninstall_bionic().
effect_under_operation
const efftype_id effect_under_operation("under_operation") ("under_operation") static
Referenced by Character::bionics_install_failure(), Character::bionics_uninstall_failure(), Character::install_bionics(), and Character::uninstall_bionic().
fault_bionic_salvaged
const fault_id fault_bionic_salvaged("fault_bionic_salvaged") ("fault_bionic_salvaged") static
Referenced by Character::bionics_install_failure(), Character::is_installable(), Character::perform_uninstall(), and Character::uninstall_bionic().
fuel_type_metabolism
const material_id fuel_type_metabolism("metabolism") ("metabolism") static
Referenced by Character::bionic_fuel_check(), and Character::burn_fuel().
fuel_type_sun_light
const material_id fuel_type_sun_light("sunlight") ("sunlight") static
Referenced by Character::burn_fuel().
fuel_type_wind
const material_id fuel_type_wind("wind") ("wind") static
Referenced by Character::burn_fuel().
itype_anesthetic
const itype_id itype_anesthetic("anesthetic") ("anesthetic") static
Referenced by Character::uninstall_bionic().
itype_radiocontrol
const itype_id itype_radiocontrol("radiocontrol") ("radiocontrol") static
Referenced by Character::deactivate_bionic().
itype_remotevehcontrol
const itype_id itype_remotevehcontrol("remotevehcontrol") ("remotevehcontrol") static
Referenced by Character::deactivate_bionic().
itype_water_clean
const itype_id itype_water_clean("water_clean") ("water_clean") static
Referenced by Character::activate_bionic().
json_flag_BIONIC_GUN
const json_character_flag json_flag_BIONIC_GUN("BIONIC_GUN") ("BIONIC_GUN") static
Referenced by Character::activate_bionic(), bionic_data::check_bionic_consistency(), npc::check_or_use_weapon_cbm(), npc::deactivate_or_discharge_bionic_weapon(), bionic::initialize_pseudo_items(), and bionic_data::load().
json_flag_BIONIC_NPC_USABLE
const json_character_flag json_flag_BIONIC_NPC_USABLE("BIONIC_NPC_USABLE") ("BIONIC_NPC_USABLE") static
Referenced by Character::is_installable().
json_flag_BIONIC_POWER_SOURCE
const json_character_flag json_flag_BIONIC_POWER_SOURCE("BIONIC_POWER_SOURCE") ("BIONIC_POWER_SOURCE") static
Referenced by bionic::is_safe_fuel_on(), and Character::process_bionic().
json_flag_BIONIC_TOGGLED
const json_character_flag json_flag_BIONIC_TOGGLED("BIONIC_TOGGLED") ("BIONIC_TOGGLED") static
Referenced by Character::activate_bionic(), Character::can_deactivate_bionic(), bionic::initialize_pseudo_items(), and bionic_data::load().
json_flag_BIONIC_WEAPON
const json_character_flag json_flag_BIONIC_WEAPON("BIONIC_WEAPON") ("BIONIC_WEAPON") static
Referenced by Character::activate_bionic(), bionic_data::check_bionic_consistency(), npc::check_or_use_weapon_cbm(), Character::deactivate_bionic(), bionic::initialize_pseudo_items(), and Character::uninstall_bionic().
json_flag_ENHANCED_VISION
const json_character_flag json_flag_ENHANCED_VISION("ENHANCED_VISION") ("ENHANCED_VISION") static
Referenced by Character::add_bionic().
json_flag_MANUAL_CBM_INSTALLATION
const json_character_flag json_flag_MANUAL_CBM_INSTALLATION("MANUAL_CBM_INSTALLATION") ("MANUAL_CBM_INSTALLATION") static
Referenced by bionic_manip_cos(), Character::can_install_bionics(), Character::has_enough_anesth(), Character::install_bionics(), and Character::uninstall_bionic().
json_flag_PAIN_IMMUNE
const json_character_flag json_flag_PAIN_IMMUNE("PAIN_IMMUNE") ("PAIN_IMMUNE") static
Referenced by Character::bionics_install_failure(), Character::bionics_uninstall_failure(), and Character::has_enough_anesth().
material_budget_steel
const material_id material_budget_steel("budget_steel") ("budget_steel") static
Referenced by Character::activate_bionic().
material_ch_steel
const material_id material_ch_steel("ch_steel") ("ch_steel") static
Referenced by Character::activate_bionic().
material_hc_steel
const material_id material_hc_steel("hc_steel") ("hc_steel") static
Referenced by Character::activate_bionic().
material_iron
const material_id material_iron("iron") ("iron") static
Referenced by Character::activate_bionic().
material_lc_steel
const material_id material_lc_steel("lc_steel") ("lc_steel") static
Referenced by Character::activate_bionic().
material_mc_steel
const material_id material_mc_steel("mc_steel") ("mc_steel") static
Referenced by Character::activate_bionic().
material_muscle
const material_id material_muscle("muscle") ("muscle") static
Referenced by Character::get_bionic_fueled_with_muscle().
material_qt_steel
const material_id material_qt_steel("qt_steel") ("qt_steel") static
Referenced by Character::activate_bionic().
material_steel
const material_id material_steel("steel") ("steel") static
Referenced by Character::activate_bionic().
requirement_data_anesthetic
const requirement_id requirement_data_anesthetic("anesthetic") ("anesthetic") static
Referenced by Character::consume_anesth_requirement(), and Character::has_enough_anesth().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by Character::bionics_pl_skill().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by Character::bionics_pl_skill(), and Character::install_bionics().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by Character::bionics_pl_skill(), and Character::install_bionics().
skill_mechanics
const skill_id skill_mechanics("mechanics") ("mechanics") static
Referenced by Character::bionics_pl_skill(), and Character::install_bionics().
trait_CENOBITE
const trait_id trait_CENOBITE("CENOBITE") ("CENOBITE") static
Referenced by Character::introduce_into_anesthesia().
trait_DEBUG_BIONICS
const trait_id trait_DEBUG_BIONICS("DEBUG_BIONICS") ("DEBUG_BIONICS") static
Referenced by bionic_manip_cos(), Character::can_install_bionics(), Character::has_enough_anesth(), Character::install_bionics(), Character::introduce_into_anesthesia(), and Character::uninstall_bionic().
trait_MASOCHIST_MED
const trait_id trait_MASOCHIST_MED("MASOCHIST_MED") ("MASOCHIST_MED") static
Referenced by Character::introduce_into_anesthesia().
trait_NONE
const trait_id trait_NONE("NONE") ("NONE") static
Referenced by Character::add_bionic().
trait_PROF_AUTODOC
const trait_id trait_PROF_AUTODOC("PROF_AUTODOC") ("PROF_AUTODOC") static
Referenced by Character::bionics_pl_skill(), and Character::install_bionics().
trait_PROF_MED
const trait_id trait_PROF_MED("PROF_MED") ("PROF_MED") static
Referenced by Character::bionics_pl_skill(), and Character::install_bionics().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by Character::activate_bionic().
trait_THRESH_MEDICAL
const trait_id trait_THRESH_MEDICAL("THRESH_MEDICAL") ("THRESH_MEDICAL") static
Referenced by Character::introduce_into_anesthesia().