Cataclysm DDA: src/bionics.h File Reference
bionics.h File Reference
#include <cstddef>
#include <map>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <utility>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "damage.h"
#include "enums.h"
#include "flat_set.h"
#include "item.h"
#include "magic.h"
#include "npc.h"
#include "translation.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
Classes
struct bionic_data
struct bionic
class bionic_collection
Macros
#define CATA_SRC_BIONICS_H
Functions
std::vector< bodypart_id > get_occupied_bodyparts (const bionic_id &bid)
List of bodyparts occupied by a bionic.
void reset_bionics ()
char get_free_invlet (Character &p)
std::string list_occupied_bps (const bionic_id &bio_id, const std::string &intro, bool each_bp_on_new_line=true)
int bionic_success_chance (bool autodoc, int skill_level, int difficulty, const Character &target)
int bionic_manip_cos (float adjusted_skill, int bionic_difficulty)
std::vector< bionic_id > bionics_cancelling_trait (const std::vector< bionic_id > &bios, const trait_id &tid)
Macro Definition Documentation
CATA_SRC_BIONICS_H
#define CATA_SRC_BIONICS_H
Definition at line 3 of file bionics.h.
Function Documentation
bionic_manip_cos()
int bionic_manip_cos (float adjusted_skill, int bionic_difficulty)
Definition at line 2040 of file bionics.cpp.
 {
     if( get_player_character().has_trait( trait_DEBUG_BIONICS ) ||
         get_player_character().has_flag( json_flag_MANUAL_CBM_INSTALLATION ) ) {
         return 100;
     }
     int chance_of_success = 0;
     // we will base chance_of_success on a ratio of skill and difficulty
     // when skill=difficulty, this gives us 1.  skill < difficulty gives a fraction.
     float skill_difficulty_parameter = static_cast<float>( adjusted_skill /
                                        ( 4.0 * bionic_difficulty ) );
     // when skill == difficulty, chance_of_success is 50%. Chance of success drops quickly below that
     // to reserve bionics for characters with the appropriate skill.  For more difficult bionics, the
     // curve flattens out just above 80%
     chance_of_success = static_cast<int>( ( 100 * skill_difficulty_parameter ) /
                                           ( skill_difficulty_parameter + std::sqrt( 1 / skill_difficulty_parameter ) ) );
     return chance_of_success;
 }
References get_player_character(), json_flag_MANUAL_CBM_INSTALLATION, sqrt(), and trait_DEBUG_BIONICS.
Referenced by bionic_success_chance(), and Character::uninstall_bionic().
bionic_success_chance()
int bionic_success_chance (bool autodoc, int skill_level, int difficulty, const Character & target)
Definition at line 2034 of file bionics.cpp.
 {
     return bionic_manip_cos( target.bionics_adjusted_skill( autodoc, skill_level ), difficulty );
 }
References iexamine::autodoc(), bionic_manip_cos(), and Character::bionics_adjusted_skill().
Referenced by best_installer(), Character::can_install_bionics(), Character::can_uninstall_bionic(), bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), Character::install_bionics(), game::save_cyborg(), and Character::uninstall_bionic().
bionics_cancelling_trait()
std::vector<bionic_id> bionics_cancelling_trait (const std::vector< bionic_id > & bios, const trait_id & tid)
Definition at line 3199 of file bionics.cpp.
 {
     // Vector of bionics to return
     std::vector<bionic_id> bionics_cancelling;
     // Search through the vector of of bionics, and see if the trait is cancelled by one of them
     for( const bionic_id &bid : bios ) {
         for( const trait_id &trait : bid->canceled_mutations ) {
             if( trait == tid ) {
                 bionics_cancelling.emplace_back( bid );
             }
         }
     }
     return bionics_cancelling;
 }
Referenced by set_traits().
get_free_invlet()
char get_free_invlet (Character & p)
Definition at line 198 of file bionics_ui.cpp.
 {
     if( p.is_npc() ) {
         // npcs don't need an invlet
         return ' ';
     }
     for( const char &inv_char : bionic_chars ) {
         if( p.as_avatar()->bionic_by_invlet( inv_char ) == nullptr ) {
             return inv_char;
         }
     }
     return ' ';
 }
References Creature::as_avatar(), avatar::bionic_by_invlet(), bionic_chars, and Character::is_npc().
Referenced by Character::add_bionic().
get_occupied_bodyparts()
std::vector<bodypart_id> get_occupied_bodyparts (const bionic_id & bid)
List of bodyparts occupied by a bionic.
Definition at line 260 of file bionics.cpp.
 {
     std::vector<bodypart_id> parts;
     for( const std::pair<const string_id<body_part_type>, size_t> &element : bid->occupied_bodyparts ) {
         if( element.second > 0 ) {
             parts.push_back( element.first.id() );
         }
     }
     return parts;
 }
References bionic_data::occupied_bodyparts.
Referenced by Character::is_installable(), and activity_handlers::operation_do_turn().
list_occupied_bps()
std::string list_occupied_bps (const bionic_id & bio_id, const std::string & intro, bool each_bp_on_new_line = true)
Definition at line 2622 of file bionics.cpp.
 {
     if( bio_id->occupied_bodyparts.empty() ) {
         return "";
     }
     std::string desc = intro;
     for( const std::pair<const bodypart_str_id, size_t> &elem : bio_id->occupied_bodyparts ) {
         desc += ( each_bp_on_new_line ? "\n" : " " );
         //~ <Bodypart name> (<number of occupied slots> slots);
         desc += string_format( _( "%s (%i slots);" ),
                                body_part_name_as_heading( elem.first.id(), 1 ),
                                elem.second );
     }
     return desc;
 }
References _, body_part_name_as_heading(), bionic_data::occupied_bodyparts, and string_format().
Referenced by item::bionic_info(), and draw_description().
reset_bionics()
void reset_bionics ()
Definition at line 2900 of file bionics.cpp.
 {
     bionic_data::migrations.clear();
     faulty_bionics.clear();
     bionic_factory.reset();
 }
References anonymous_namespace{bionics.cpp}::bionic_factory, anonymous_namespace{bionics.cpp}::faulty_bionics, and bionic_data::migrations.
Referenced by DynamicDataLoader::unload_data().