Cataclysm DDA: src/bodypart.cpp File Reference
bodypart.cpp File Reference
#include "bodypart.h"
#include <algorithm>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "assign.h"
#include "body_part_set.h"
#include "debug.h"
#include "enum_conversions.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "generic_factory.h"
#include "init.h"
#include "json.h"
#include "json_error.h"
#include "localized_comparator.h"
#include "rng.h"
#include "subbodypart.h"
Namespaces
io
anonymous_namespace{bodypart.cpp}
Functions
side opposite_side (side s)
Returns the opposite side.
template<>
std::string io::enum_to_string< side > (side data)
template<>
std::string io::enum_to_string< body_part_type::type > (body_part_type::type data)
static body_part legacy_id_to_enum (const std::string &legacy_id)
const bodypart_str_id & convert_bp (body_part bp)
Returns the new id for old token.
std::string body_part_name (const bodypart_id &bp, int number)
Returns the matching name of the body_part token.
std::string body_part_name_accusative (const bodypart_id &bp, int number)
Returns the matching accusative name of the body_part token, i.e.
std::string body_part_name_as_heading (const bodypart_id &bp, int number)
Returns the name of the body parts in a context where the name is used as a heading or title e.g.
std::string body_part_hp_bar_ui_text (const bodypart_id &bp)
Returns the body part text to be displayed in the HP bar.
std::string encumb_text (const bodypart_id &bp)
Returns the matching encumbrance text for a given body_part token.
Variables
const bodypart_str_id body_part_arm_l ("arm_l")
const bodypart_str_id body_part_arm_r ("arm_r")
const bodypart_str_id body_part_bp_null ("bp_null")
const bodypart_str_id body_part_eyes ("eyes")
const bodypart_str_id body_part_foot_l ("foot_l")
const bodypart_str_id body_part_foot_r ("foot_r")
const bodypart_str_id body_part_hand_l ("hand_l")
const bodypart_str_id body_part_hand_r ("hand_r")
const bodypart_str_id body_part_head ("head")
const bodypart_str_id body_part_leg_l ("leg_l")
const bodypart_str_id body_part_leg_r ("leg_r")
const bodypart_str_id body_part_mouth ("mouth")
const bodypart_str_id body_part_torso ("torso")
const sub_bodypart_str_id sub_body_part_sub_limb_debug ("sub_limb_debug")
generic_factory< body_part_type > anonymous_namespace{bodypart.cpp}::body_part_factory ("body part")
generic_factory< limb_score > anonymous_namespace{bodypart.cpp}::limb_score_factory ("limb score")
Function Documentation
body_part_hp_bar_ui_text()
std::string body_part_hp_bar_ui_text (const bodypart_id & bp)
Returns the body part text to be displayed in the HP bar.
Definition at line 812 of file bodypart.cpp.
 {
     return bp->hp_bar_ui_text.translated();
 }
References bp, body_part_type::hp_bar_ui_text, and translation::translated().
Referenced by blood_magic().
body_part_name()
std::string body_part_name (const bodypart_id & bp, int number)
Returns the matching name of the body_part token.
Definition at line 791 of file bodypart.cpp.
 {
     // See comments in `body_part_type::load` about why these two strings are
     // not a single translation object with plural enabled.
     return number > 1 ? bp->name_multiple.translated() : bp->name.translated();
 }
References bp, body_part_type::name, body_part_type::name_multiple, and translation::translated().
Referenced by iexamine::autodoc(), basic_item_filter(), Character::block_hit(), npc::complain(), trapfunc::crossbow(), Character::deal_damage(), effect::disp_desc(), effect::disp_name(), draw_health_summary(), eff_fun_bleed(), npc::estimate_armour(), mattack::flesh_golem(), suffer::from_sunburn(), Character::hardcoded_effects(), Character::heal(), mattack::lunge(), Character::mend(), memorial_logger::notify(), Character::process_one_effect(), Character::reduce_healing_effect(), Character::regen(), anatomy::select_blocking_part(), anatomy::select_body_part(), trapfunc::shotgun(), game::slip_down_chance(), Character::update_bodytemp(), Character::update_frostbite(), suffer::water_damage(), and outfit::wear_item().
body_part_name_accusative()
std::string body_part_name_accusative (const bodypart_id & bp, int number = 1)
Returns the matching accusative name of the body_part token, i.e.
"Shrapnel hits your X". These are identical to body_part_name above in English, but not in some other languages.
Definition at line 798 of file bodypart.cpp.
 {
     // See comments in `body_part_type::load` about why these two strings are
     // not a single translation object with plural enabled.
     return number > 1 ? bp->accusative_multiple.translated() : bp->accusative.translated();
 }
References body_part_type::accusative, body_part_type::accusative_multiple, bp, and translation::translated().
Referenced by mattack::acid_barf(), avatar::add_pain_msg(), mattack::bio_op_impale(), mattack::bio_op_takedown(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), anonymous_namespace{armor_layers.cpp}::body_part_names(), melee_actor::call(), mattack::dermatik(), explosion_handler::do_blast(), Character::fire_gun(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::growplants(), Character::hardcoded_effects(), mattack::lunge(), monster::melee_attack(), Creature::messaging_projectile_attack(), melee_actor::on_damage(), activity_handlers::operation_do_turn(), trapfunc::pit_glass(), trapfunc::pit_spikes(), game::place_player(), smash(), trapfunc::snare_heavy(), mattack::stretch_attack(), and mattack::vine().
body_part_name_as_heading()
std::string body_part_name_as_heading (const bodypart_id & bp, int number)
Returns the name of the body parts in a context where the name is used as a heading or title e.g.
"Left Arm".
Definition at line 805 of file bodypart.cpp.
 {
     // See comments in `body_part_type::load` about why these two strings are
     // not a single translation object with plural enabled.
     return number > 1 ? bp->name_as_heading_multiple.translated() : bp->name_as_heading.translated();
 }
References bp, body_part_type::name_as_heading, body_part_type::name_as_heading_multiple, and translation::translated().
Referenced by item::bionic_info(), Character::can_install_bionics(), Character::extended_description(), list_occupied_bps(), avatar::power_bionics(), Character::print_encumbrance(), and outfit::sort_armor().
convert_bp()
const bodypart_str_id& convert_bp (body_part bp)
Returns the new id for old token.
Definition at line 217 of file bodypart.cpp.
 {
     static const std::vector<bodypart_str_id> body_parts = {
         body_part_torso,
         body_part_head,
         body_part_eyes,
         body_part_mouth,
         body_part_arm_l,
         body_part_arm_r,
         body_part_hand_l,
         body_part_hand_r,
         body_part_leg_l,
         body_part_leg_r,
         body_part_foot_l,
         body_part_foot_r,
         bodypart_str_id::NULL_ID(),
     };
     if( bp > num_bp || bp < bp_torso ) {
         debugmsg( "Invalid body part token %d", bp );
         return body_parts[ num_bp ];
     }
     return body_parts[static_cast<size_t>( bp )];
 }
References body_part_arm_l, body_part_arm_r, body_part_eyes, body_part_foot_l, body_part_foot_r, body_part_hand_l, body_part_hand_r, body_part_head, body_part_leg_l, body_part_leg_r, body_part_mouth, body_part_torso, bp, bp_torso, debugmsg, string_id< body_part_type >::NULL_ID(), and num_bp.
Referenced by basic_item_filter(), body_part_type::check(), body_part_type::check_consistency(), effect::deserialize(), and Creature::load().
encumb_text()
std::string encumb_text (const bodypart_id & bp)
Returns the matching encumbrance text for a given body_part token.
Definition at line 817 of file bodypart.cpp.
 {
     return bp->encumb_text.translated();
 }
References bp, body_part_type::encumb_text, and translation::translated().
Referenced by outfit::wear_item().
legacy_id_to_enum()
static body_part legacy_id_to_enum (const std::string & legacy_id) static
Definition at line 108 of file bodypart.cpp.
 {
     static const std::unordered_map<std::string, body_part> body_parts = {
         { "TORSO", bp_torso },
         { "HEAD", bp_head },
         { "EYES", bp_eyes },
         { "MOUTH", bp_mouth },
         { "ARM_L", bp_arm_l },
         { "ARM_R", bp_arm_r },
         { "HAND_L", bp_hand_l },
         { "HAND_R", bp_hand_r },
         { "LEG_L", bp_leg_l },
         { "LEG_R", bp_leg_r },
         { "FOOT_L", bp_foot_l },
         { "FOOT_R", bp_foot_r },
         { "NUM_BP", num_bp },
     };
     const auto &iter = body_parts.find( legacy_id );
     if( iter == body_parts.end() ) {
         debugmsg( "Invalid body part legacy id %s", legacy_id.c_str() );
         return num_bp;
     }
     return iter->second;
 }
References bp_arm_l, bp_arm_r, bp_eyes, bp_foot_l, bp_foot_r, bp_hand_l, bp_hand_r, bp_head, bp_leg_l, bp_leg_r, bp_mouth, bp_torso, debugmsg, and num_bp.
Referenced by body_part_type::load().
opposite_side()
side opposite_side (side s)
Returns the opposite side.
Definition at line 40 of file bodypart.cpp.
 {
     switch( s ) {
         case side::BOTH:
             return side::BOTH;
         case side::LEFT:
             return side::RIGHT;
         case side::RIGHT:
             return side::LEFT;
         case side::num_sides:
             debugmsg( "invalid side %d", static_cast<int>( s ) );
             break;
     }
     return s;
 }
References BOTH, debugmsg, LEFT, num_sides, and RIGHT.
Referenced by outfit::adjust_worn(), and item::swap_side().
Variable Documentation
body_part_arm_l
const bodypart_str_id body_part_arm_l("arm_l") ("arm_l")
Referenced by Character::armwear_factor(), convert_bp(), Character::deal_damage(), eff_fun_cold(), Character::forced_dismount(), game::get_dangerous_tile(), anonymous_namespace{item.cpp}::left_side_parts(), avatar::reset_stats(), and workout_activity_actor::start().
body_part_arm_r
const bodypart_str_id body_part_arm_r("arm_r") ("arm_r")
Referenced by Character::armwear_factor(), convert_bp(), Character::deal_damage(), eff_fun_cold(), Character::forced_dismount(), game::get_dangerous_tile(), item::on_wear(), avatar::reset_stats(), anonymous_namespace{item.cpp}::right_side_parts(), and workout_activity_actor::start().
body_part_bp_null
const bodypart_str_id body_part_bp_null("bp_null") ("bp_null")
Referenced by debug_menu::character_edit_hp_menu(), melee_actor::do_grab(), Creature::get_part_id(), Creature::has_part(), and mon_effect_data::load().
body_part_eyes
const bodypart_str_id body_part_eyes("eyes") ("eyes")
Referenced by display::bodytemp_color(), convert_bp(), game::get_dangerous_tile(), outfit::get_env_resist(), Character::get_env_resist(), Character::mut_cbm_encumb(), outfit::power_armor_conflicts(), and outfit::wear_item().
body_part_foot_l
const bodypart_str_id body_part_foot_l("foot_l") ("foot_l")
Referenced by convert_bp(), eff_fun_cold(), eff_fun_frostbite(), eff_fun_hot(), Character::forced_dismount(), game::get_dangerous_tile(), Character::is_immune_field(), anonymous_namespace{item.cpp}::left_side_parts(), Character::shoe_type_count(), Character::swim_speed(), Character::update_bodytemp(), and Character::update_frostbite().
body_part_foot_r
const bodypart_str_id body_part_foot_r("foot_r") ("foot_r")
Referenced by convert_bp(), eff_fun_cold(), eff_fun_frostbite(), eff_fun_hot(), Character::forced_dismount(), game::get_dangerous_tile(), Character::is_immune_field(), anonymous_namespace{item.cpp}::right_side_parts(), Character::shoe_type_count(), Character::swim_speed(), Character::update_bodytemp(), and Character::update_frostbite().
body_part_hand_l
const bodypart_str_id body_part_hand_l("hand_l") ("hand_l")
Referenced by Character::bonus_item_warmth(), convert_bp(), Character::deal_damage(), eff_fun_cold(), eff_fun_frostbite(), eff_fun_hot(), suffer::from_sunburn(), game::get_dangerous_tile(), anonymous_namespace{item.cpp}::left_side_parts(), outfit::prepare_bodymap_info(), Character::swim_speed(), and Character::update_frostbite().
body_part_hand_r
const bodypart_str_id body_part_hand_r("hand_r") ("hand_r")
Referenced by Character::bonus_item_warmth(), convert_bp(), Character::deal_damage(), eff_fun_cold(), eff_fun_frostbite(), eff_fun_hot(), suffer::from_sunburn(), game::get_dangerous_tile(), outfit::prepare_bodymap_info(), anonymous_namespace{item.cpp}::right_side_parts(), Character::swim_speed(), and Character::update_frostbite().
body_part_head
const bodypart_str_id body_part_head("head") ("head")
Referenced by Character::bonus_item_warmth(), Character::calc_all_parts_hp(), Character::can_use_hood(), Character::can_wear(), convert_bp(), Character::deal_damage(), eff_fun_cold(), eff_fun_hot(), Character::forced_dismount(), suffer::from_sunburn(), game::get_dangerous_tile(), outfit::get_env_resist(), Creature::get_root_body_part(), Character::healing_rate_medicine(), outfit::is_wearing_power_armor(), Character::on_hurt(), npc::patient_assessment(), outfit::power_armor_conflicts(), outfit::prepare_bodymap_info(), avatar::reset_stats(), Character::update_bodytemp(), and wet_character().
body_part_leg_l
const bodypart_str_id body_part_leg_l("leg_l") ("leg_l")
Referenced by convert_bp(), eff_fun_cold(), eff_fun_hot(), Character::floor_item_warmth(), Character::forced_dismount(), game::get_dangerous_tile(), Character::is_immune_field(), Character::is_snuggling(), anonymous_namespace{item.cpp}::left_side_parts(), avatar::reset_stats(), and workout_activity_actor::start().
body_part_leg_r
const bodypart_str_id body_part_leg_r("leg_r") ("leg_r")
Referenced by convert_bp(), eff_fun_cold(), eff_fun_hot(), Character::floor_item_warmth(), Character::forced_dismount(), game::get_dangerous_tile(), Character::is_immune_field(), Character::is_snuggling(), item::on_wear(), avatar::reset_stats(), anonymous_namespace{item.cpp}::right_side_parts(), and workout_activity_actor::start().
body_part_mouth
const bodypart_str_id body_part_mouth("mouth") ("mouth")
Referenced by Character::bonus_item_warmth(), Character::can_use_collar(), convert_bp(), eff_fun_cold(), eff_fun_frostbite(), suffer::from_sunburn(), game::get_dangerous_tile(), Character::get_sick(), outfit::power_armor_conflicts(), outfit::prepare_bodymap_info(), avatar::try_break_relax_gas(), and Character::update_frostbite().
body_part_torso
const bodypart_str_id body_part_torso("torso") ("torso")
Referenced by Character::apply_damage(), item::armor_full_protection_info(), Character::check_needs_extremes(), convert_bp(), Character::cough(), Character::deal_damage(), eff_fun_cold(), eff_fun_hot(), Character::floor_item_warmth(), Character::forced_dismount(), game::get_dangerous_tile(), item::get_layer(), Character::healing_rate_medicine(), Character::is_snuggling(), Character::on_hit(), Character::on_hurt(), npc::patient_assessment(), outfit::power_armor_conflicts(), Character::process_one_effect(), Character::update_bodytemp(), and wet_character().
sub_body_part_sub_limb_debug
const sub_bodypart_str_id sub_body_part_sub_limb_debug("sub_limb_debug") ("sub_limb_debug")
Referenced by body_part_type::consolidate().