Cataclysm DDA: src/bodygraph.cpp File Reference
bodygraph.cpp File Reference
#include "bodygraph.h"
#include <algorithm>
#include <cstddef>
#include <initializer_list>
#include <memory>
#include <set>
#include <tuple>
#include "bodypart.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_attire.h"
#include "creature.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "enums.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "generic_factory.h"
#include "init.h"
#include "input_context.h"
#include "json_error.h"
#include "make_static.h"
#include "memory_fast.h"
#include "output.h"
#include "point.h"
#include "string_formatter.h"
#include "subbodypart.h"
#include "translation.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "weather.h"
Classes
struct bodygraph_display
Namespaces
anonymous_namespace{bodygraph.cpp}
Macros
#define BPGRAPH_MAXROWS 20
#define BPGRAPH_MAXCOLS 40
Typedefs
using part_tuple = std::tuple< bodypart_id, const sub_body_part_type *, const bodygraph_part *, bool >
Functions
static const bodygraph_id & get_bg_rows (const bodygraph_id &bgid)
void display_bodygraph (const Character &u, const bodygraph_id &id)
std::vector< std::string > get_bodygraph_lines (const Character &u, const bodygraph_callback &fragment_cb, const bodygraph_id &id, int width, int height)
Returns a prepared bodygraph ready to be rendered line-by-line.
Variables
static const bodygraph_id bodygraph_full_body ("full_body")
generic_factory< bodygraph > anonymous_namespace{bodygraph.cpp}::bodygraph_factory ("bodygraph")
Macro Definition Documentation
BPGRAPH_MAXCOLS
#define BPGRAPH_MAXCOLS 40
Definition at line 40 of file bodygraph.cpp.
BPGRAPH_MAXROWS
#define BPGRAPH_MAXROWS 20
Definition at line 39 of file bodygraph.cpp.
Typedef Documentation
part_tuple
using part_tuple = std::tuple<bodypart_id, const sub_body_part_type *, const bodygraph_part *, bool>
Definition at line 240 of file bodygraph.cpp.
Function Documentation
display_bodygraph()
void display_bodygraph (const Character & u, const bodygraph_id & id)
Definition at line 645 of file bodygraph.cpp.
 {
     bodygraph_display bgd( &u, id );
     bgd.display();
 }
References bodygraph_display::display(), and u.
Referenced by bodygraph_display::display(), game::do_regular_action(), handle_player_display_action(), and game::npc_menu().
get_bg_rows()
static const bodygraph_id& get_bg_rows (const bodygraph_id & bgid) static
Definition at line 400 of file bodygraph.cpp.
 {
     if( !!bgid->mirror ) {
         return get_bg_rows( bgid->mirror.value() );
     }
     return bgid;
 }
References bodygraph::mirror.
Referenced by get_bodygraph_lines().
get_bodygraph_lines()
std::vector<std::string> get_bodygraph_lines (const Character & u, const bodygraph_callback & fragment_cb, const bodygraph_id & id = bodygraph_id::NULL_ID(), int width = 0, int height = 0)
Returns a prepared bodygraph ready to be rendered line-by-line.
The callback function is for processing a bodygraph symbol. The args are as follows:
Parameters
bodygraph_part points to the graph part represented in the symbol (or nullptr if none)
string the default symbol to use if no other processing is done
Returns
the final colorized symbol
Definition at line 651 of file bodygraph.cpp.
 {
     width = ( width <= 0 || width > BPGRAPH_MAXCOLS ) ? BPGRAPH_MAXCOLS : width;
     height = ( height <= 0 || height > BPGRAPH_MAXROWS ) ? BPGRAPH_MAXROWS : height;
     std::vector<std::string> ret;
     // Bodypart not present on character
     if( !!id->parent_bp && !u.has_part( *id->parent_bp, body_part_filter::equivalent ) ) {
         std::string txt = string_format( u.is_avatar() ?
                                          //~ 1$ = 2nd person pronoun (You), 2$ = body part (left arm)
                                          _( "%1$s do not have a %2$s." ) :
                                          //~ 1$ = name of character, 2$ = body part (left arm)
                                          _( "%1$s does not have a %2$s." ), u.disp_name( false, true ),
                                          id->parent_bp->obj().name.translated() );
         for( int y = 0; y < height; y++ ) {
             if( y == height / 2 ) {
                 txt.insert( txt.begin(), center_text_pos( txt, 0, width ), ' ' );
                 ret.emplace_back( colorize( txt, c_light_red ) );
             } else {
                 ret.emplace_back( width, ' ' );
             }
         }
         return ret;
     }
     const bool hflip = !!id->mirror;
     const bodygraph_id &rid = get_bg_rows( id );
     for( int i = 0; static_cast<size_t>( i ) < rid->rows.size() && i < height; i++ ) {
         std::string ret_row;
         int j = hflip ? rid->rows[i].size() - 1 : 0;
         for( int x = 0 ; x < width && j < BPGRAPH_MAXCOLS && j >= 0; hflip ? j-- : j++, x++ ) {
             std::string sym = id->fill_sym.empty() ? rid->rows[i][j] : id->fill_sym;
             auto iter = id->parts.find( rid->rows[i][j] );
             const bodygraph_part *bgp = nullptr;
             if( iter != id->parts.end() ) {
                 bgp = &iter->second;
                 bool missing_section = true;
                 for( const bodypart_id &bp : iter->second.bodyparts ) {
                     if( u.has_part( bp, body_part_filter::equivalent ) ) {
                         missing_section = false;
                     }
                 }
                 for( const sub_bodypart_id &sp : iter->second.sub_bodyparts ) {
                     if( u.has_part( sp->parent, body_part_filter::equivalent ) ) {
                         missing_section = false;
                     }
                 }
                 sym = missing_section ? " " : ( id->fill_rows.empty() ? iter->second.sym : id->fill_rows[i][j] );
             }
             if( rid->rows[i][j] == " " ) {
                 sym = " ";
             }
             ret_row.append( fragment_cb( bgp, sym ) );
         }
         ret.emplace_back( ret_row );
     }
     return ret;
 }
References _, bp, BPGRAPH_MAXCOLS, BPGRAPH_MAXROWS, c_light_red, center_text_pos(), colorize(), equivalent, get_bg_rows(), int_id< T >::id(), cata::hash64_detail::ret, bodygraph::rows, string_format(), and u.
Referenced by item::armor_info(), display::colorized_bodygraph_text(), and bodygraph_display::draw_graph().
Variable Documentation
bodygraph_full_body
const bodygraph_id bodygraph_full_body("full_body") ("full_body") static
Referenced by bodygraph_display::bodygraph_display(), and bodygraph_display::display().