Cataclysm DDA: src/bonuses.cpp File Reference
bonuses.cpp File Reference
#include "bonuses.h"
#include <algorithm>
#include <string>
#include <type_traits>
#include <utility>
#include "character.h"
#include "damage.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "string_formatter.h"
#include "translation.h"
#include "translations.h"
Functions
static bool needs_damage_type (affected_stat as)
static scaling_stat scaling_stat_from_string (const std::string &s)
static affected_stat affected_stat_from_string (const std::string &s)
static std::string string_from_affected_stat (const affected_stat &s)
static std::string string_from_scaling_stat (const scaling_stat &s)
Variables
static const skill_id skill_archery ("archery")
static const skill_id skill_bashing ("bashing")
static const skill_id skill_cutting ("cutting")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_drive ("drive")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_gun ("gun")
static const skill_id skill_launcher ("launcher")
static const skill_id skill_melee ("melee")
static const skill_id skill_pistol ("pistol")
static const skill_id skill_rifle ("rifle")
static const skill_id skill_shotgun ("shotgun")
static const skill_id skill_smg ("smg")
static const skill_id skill_spellcraft ("spellcraft")
static const skill_id skill_stabbing ("stabbing")
static const skill_id skill_swimming ("swimming")
static const skill_id skill_throw ("throw")
static const skill_id skill_unarmed ("unarmed")
static const std::map< std::string, affected_stat > affected_stat_map
static const std::map< std::string, scaling_stat > scaling_stat_map
static const std::map< affected_stat, std::string > affected_stat_map_translation
static const std::map< scaling_stat, std::string > scaling_stat_map_translation
Function Documentation
affected_stat_from_string()
static affected_stat affected_stat_from_string (const std::string & s) static
Definition at line 93 of file bonuses.cpp.
 {
     const auto &iter = affected_stat_map.find( s );
     if( iter != affected_stat_map.end() ) {
         return iter->second;
     }
     return affected_stat::NONE;
 }
References affected_stat_map, and NONE.
Referenced by bonus_container::load().
needs_damage_type()
static bool needs_damage_type (affected_stat as) static
Definition at line 35 of file bonuses.cpp.
 {
     return as == affected_stat::DAMAGE ||
            as == affected_stat::ARMOR ||
            as == affected_stat::ARMOR_PENETRATION;
 }
References ARMOR, ARMOR_PENETRATION, and DAMAGE.
Referenced by affected_type::affected_type(), bonus_container::get_description(), and bonus_container::load().
scaling_stat_from_string()
static scaling_stat scaling_stat_from_string (const std::string & s) static
Definition at line 83 of file bonuses.cpp.
 {
     const auto &iter = scaling_stat_map.find( s );
     if( iter == scaling_stat_map.end() ) {
         return STAT_NULL;
     }
     return iter->second;
 }
References scaling_stat_map, and STAT_NULL.
Referenced by effect_scaling::effect_scaling().
string_from_affected_stat()
static std::string string_from_affected_stat (const affected_stat & s) static
Definition at line 118 of file bonuses.cpp.
 {
     const auto &iter = affected_stat_map_translation.find( s );
     return iter != affected_stat_map_translation.end() ? _( iter->second ) : "";
 }
References _, and affected_stat_map_translation.
Referenced by bonus_container::get_description().
string_from_scaling_stat()
static std::string string_from_scaling_stat (const scaling_stat & s) static
Definition at line 150 of file bonuses.cpp.
 {
     const auto &iter = scaling_stat_map_translation.find( s );
     return iter != scaling_stat_map_translation.end() ? _( iter->second ) : "";
 }
References _, and scaling_stat_map_translation.
Referenced by bonus_container::get_description().
Variable Documentation
affected_stat_map
const std::map<std::string, affected_stat> affected_stat_map static
Initial value:
= {{
        std::make_pair( "hit", affected_stat::HIT ),
        std::make_pair( "crit_chance", affected_stat::CRITICAL_HIT_CHANCE ),
        std::make_pair( "dodge", affected_stat::DODGE ),
        std::make_pair( "block", affected_stat::BLOCK ),
        std::make_pair( "block_effectiveness", affected_stat::BLOCK_EFFECTIVENESS ),
        std::make_pair( "speed", affected_stat::SPEED ),
        std::make_pair( "movecost", affected_stat::MOVE_COST ),
        std::make_pair( "damage", affected_stat::DAMAGE ),
        std::make_pair( "armor", affected_stat::ARMOR ),
        std::make_pair( "arpen", affected_stat::ARMOR_PENETRATION ),
        std::make_pair( "target_armor_multiplier", affected_stat::TARGET_ARMOR_MULTIPLIER )
    }
}
Definition at line 42 of file bonuses.cpp.
Referenced by affected_stat_from_string().
affected_stat_map_translation
const std::map<affected_stat, std::string> affected_stat_map_translation static
Initial value:
= {{
        std::make_pair( affected_stat::HIT, translate_marker( "Accuracy" ) ),
        std::make_pair( affected_stat::CRITICAL_HIT_CHANCE, translate_marker( "Critical Hit Chance" ) ),
        std::make_pair( affected_stat::DODGE, translate_marker( "Dodge" ) ),
        std::make_pair( affected_stat::BLOCK, translate_marker( "Block" ) ),
        std::make_pair( affected_stat::BLOCK_EFFECTIVENESS, translate_marker( "Block effectiveness" ) ),
        std::make_pair( affected_stat::SPEED, translate_marker( "Speed" ) ),
        std::make_pair( affected_stat::MOVE_COST, translate_marker( "Move cost" ) ),
        std::make_pair( affected_stat::DAMAGE, translate_marker( "damage" ) ),
        std::make_pair( affected_stat::ARMOR, translate_marker( "Armor" ) ),
        std::make_pair( affected_stat::ARMOR_PENETRATION, translate_marker( "Armor penetration" ) ),
        std::make_pair( affected_stat::TARGET_ARMOR_MULTIPLIER, translate_marker( "Target armor multiplier" ) ),
    }
}
Definition at line 103 of file bonuses.cpp.
Referenced by string_from_affected_stat().
scaling_stat_map
const std::map<std::string, scaling_stat> scaling_stat_map static
Initial value:
= {{
        std::make_pair( "str", STAT_STR ),
        std::make_pair( "dex", STAT_DEX ),
        std::make_pair( "int", STAT_INT ),
        std::make_pair( "per", STAT_PER ),
        std::make_pair( "bash", SKILL_BASHING ),
        std::make_pair( "cut", SKILL_CUTTING ),
        std::make_pair( "dodge", SKILL_DODGE ),
        std::make_pair( "melee", SKILL_MELEE ),
        std::make_pair( "stab", SKILL_STABBING ),
        std::make_pair( "athletics", SKILL_SWIMMING ),
        std::make_pair( "unarmed", SKILL_UNARMED ),
        std::make_pair( "marksmanship", SKILL_GUN ),
        std::make_pair( "pistol", SKILL_PISTOL ),
        std::make_pair( "rifle", SKILL_RIFLE ),
        std::make_pair( "shotgun", SKILL_SHOTGUN ),
        std::make_pair( "smg", SKILL_SMG ),
        std::make_pair( "archery", SKILL_ARCHERY ),
        std::make_pair( "throw", SKILL_THROW ),
        std::make_pair( "launcher", SKILL_LAUNCHER ),
        std::make_pair( "drive", SKILL_DRIVE ),
        std::make_pair( "firstaid", SKILL_FIRSTAID ),
        std::make_pair( "spellcraft", SKILL_SPELLCRAFT )
    }
}
Definition at line 57 of file bonuses.cpp.
Referenced by scaling_stat_from_string().
scaling_stat_map_translation
const std::map<scaling_stat, std::string> scaling_stat_map_translation static
Initial value:
= {{
        std::make_pair( STAT_STR, translate_marker( "strength" ) ),
        std::make_pair( STAT_DEX, translate_marker( "dexterity" ) ),
        std::make_pair( STAT_INT, translate_marker( "intelligence" ) ),
        std::make_pair( STAT_PER, translate_marker( "perception" ) ),
        std::make_pair( SKILL_BASHING, translate_marker( "bashing" ) ),
        std::make_pair( SKILL_CUTTING, translate_marker( "cutting" ) ),
        std::make_pair( SKILL_DODGE, translate_marker( "dodging" ) ),
        std::make_pair( SKILL_MELEE, translate_marker( "melee" ) ),
        std::make_pair( SKILL_STABBING, translate_marker( "stabbing" ) ),
        std::make_pair( SKILL_SWIMMING, translate_marker( "swimming" ) ),
        std::make_pair( SKILL_UNARMED, translate_marker( "unarmed" ) ),
        std::make_pair( SKILL_GUN, translate_marker( "marksmanship" ) ),
        std::make_pair( SKILL_PISTOL, translate_marker( "pistols" ) ),
        std::make_pair( SKILL_RIFLE, translate_marker( "rifles" ) ),
        std::make_pair( SKILL_SHOTGUN, translate_marker( "shotguns" ) ),
        std::make_pair( SKILL_SMG, translate_marker( "SMGs" ) ),
        std::make_pair( SKILL_ARCHERY, translate_marker( "archery" ) ),
        std::make_pair( SKILL_THROW, translate_marker( "throwing" ) ),
        std::make_pair( SKILL_LAUNCHER, translate_marker( "launchers" ) ),
        std::make_pair( SKILL_DRIVE, translate_marker( "driving" ) ),
        std::make_pair( SKILL_FIRSTAID, translate_marker( "health care" ) ),
        std::make_pair( SKILL_SPELLCRAFT, translate_marker( "spellcraft" ) ),
    }
}
Definition at line 124 of file bonuses.cpp.
Referenced by string_from_scaling_stat().
skill_archery
const skill_id skill_archery("archery") ("archery") static
Referenced by effect_scaling::get(), and item::gun_type().
skill_bashing
const skill_id skill_bashing("bashing") ("bashing") static
Referenced by effect_scaling::get().
skill_cutting
const skill_id skill_cutting("cutting") ("cutting") static
Referenced by effect_scaling::get().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by effect_scaling::get().
skill_drive
const skill_id skill_drive("drive") ("drive") static
Referenced by effect_scaling::get().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by effect_scaling::get().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by effect_scaling::get().
skill_launcher
const skill_id skill_launcher("launcher") ("launcher") static
Referenced by effect_scaling::get().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by effect_scaling::get().
skill_pistol
const skill_id skill_pistol("pistol") ("pistol") static
Referenced by effect_scaling::get().
skill_rifle
const skill_id skill_rifle("rifle") ("rifle") static
Referenced by effect_scaling::get().
skill_shotgun
const skill_id skill_shotgun("shotgun") ("shotgun") static
Referenced by effect_scaling::get().
skill_smg
const skill_id skill_smg("smg") ("smg") static
Referenced by effect_scaling::get().
skill_spellcraft
const skill_id skill_spellcraft("spellcraft") ("spellcraft") static
Referenced by effect_scaling::get().
skill_stabbing
const skill_id skill_stabbing("stabbing") ("stabbing") static
Referenced by effect_scaling::get().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by effect_scaling::get().
skill_throw
const skill_id skill_throw("throw") ("throw") static
Referenced by effect_scaling::get().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by effect_scaling::get().