Cataclysm DDA: src/calendar.h File Reference
calendar.h File Reference
#include <optional>
#include <string>
#include <utility>
#include <vector>
#include <climits>
#include "units_fwd.h"
Classes
struct enum_traits< season_type >
struct enum_traits< time_accuracy >
class time_duration
A duration defined as a number of specific time units.
class time_point
A point in the game time.
struct season_effective_time
Namespaces
calendar
Time keeping class.
Macros
#define CATA_SRC_CALENDAR_H
Enumerations
enum season_type {
SPRING = 0 , SUMMER = 1 , AUTUMN = 2 , WINTER = 3 ,
NUM_SEASONS
}
Real world seasons.
enum moon_phase {
MOON_NEW = 0 , MOON_WAXING_CRESCENT , MOON_HALF_MOON_WAXING , MOON_WAXING_GIBBOUS ,
MOON_FULL , MOON_WANING_GIBBOUS , MOON_HALF_MOON_WANING , MOON_WANING_CRESCENT ,
MOON_PHASE_MAX
}
Phases of the moon.
enum class time_accuracy { NONE = 0 , PARTIAL = 1 , FULL = 2 , NUM_TIME_ACCURACY }
enum class clipped_align : int { none , right , compact }
enum class clipped_unit : int {
forever , second , minute , hour ,
day , week , season , year
}
enum class weekdays : int {
SUNDAY = 0 , MONDAY , TUESDAY , WEDNESDAY ,
THURSDAY , FRIDAY , SATURDAY
}
Functions
bool calendar::once_every (const time_duration &event_frequency)
Predicate to handle rate-limiting.
bool calendar::eternal_season ()
void calendar::set_eternal_season (bool is_eternal_season)
bool calendar::eternal_night ()
void calendar::set_eternal_night (bool is_eternal_night)
bool calendar::eternal_day ()
void calendar::set_eternal_day (bool is_eternal_day)
time_duration calendar::year_length ()
time_duration calendar::season_length ()
void calendar::set_season_length (int dur)
void calendar::set_location (float latitude, float longitude)
float calendar::season_ratio ()
float calendar::season_from_default_ratio ()
std::string calendar::name_season (season_type s)
Returns the translated name of the season (with first letter being uppercase).
template<typename T >
constexpr T to_turns (const time_duration &duration)
template<typename T >
constexpr T to_seconds (const time_duration &duration)
template<typename T >
constexpr T to_minutes (const time_duration &duration)
template<typename T >
constexpr T to_hours (const time_duration &duration)
template<typename T >
constexpr T to_days (const time_duration &duration)
template<typename T >
constexpr T to_weeks (const time_duration &duration)
template<typename T >
constexpr T to_moves (const time_duration &duration)
template<typename T >
constexpr T to_turn (const time_point &point)
template<typename T >
constexpr time_duration operator/ (const time_duration &lhs, T rhs)
template<typename T >
time_duration & operator/= (time_duration &lhs, T rhs)
template<typename T >
constexpr time_duration operator* (const time_duration &lhs, T rhs)
template<typename T >
constexpr time_duration operator* (T lhs, const time_duration &rhs)
template<typename T >
time_duration & operator*= (time_duration &lhs, T rhs)
bool x_in_y (const time_duration &a, const time_duration &b)
std::string to_string (const time_duration &d, bool compact=false)
Returns a string showing a duration.
std::pair< int, clipped_unit > clipped_time (const time_duration &d)
Returns a value representing the passed in duration truncated to an appropriate unit along with the unit in question.
std::string to_string_clipped (const time_duration &d, clipped_align align=clipped_align::none)
Returns a string showing a duration as whole number of appropriate units, e.g.
std::string to_string_approx (const time_duration &dur, bool verbose=true)
Returns approximate duration.
std::string to_string_writable (const time_duration &dur)
Returns a string that is writable to JSON that is also readable from JSON.
time_duration time_past_midnight (const time_point &p)
time_duration time_past_new_year (const time_point &p)
template<typename T >
T minute_of_hour (const time_point &p)
template<typename T >
T hour_of_day (const time_point &p)
template<typename T >
T day_of_season (const time_point &p)
This uses the current season length.
season_type season_of_year (const time_point &p)
std::string to_string (const time_point &p)
std::string to_string_time_of_day (const time_point &p)
std::string get_diary_time_str (const time_point &turn, time_accuracy acc)
Time approximation based on the player's timekeeping capability, formatted for diary pages.
std::string get_diary_time_since_str (const time_duration &turn_diff, time_accuracy acc)
Time approximation based on the player's timekeeping capability, formatted for diary pages.
time_duration lunar_month ()
Returns the default duration of a lunar month (duration between syzygies)
moon_phase get_moon_phase (const time_point &p)
Returns the current phase of the moon.
time_point sunrise (const time_point &p)
Returns the current sunrise time based on the time of year.
time_point sunset (const time_point &p)
Returns the current sunset time based on the time of year.
time_point daylight_time (const time_point &p)
Returns the time it gets light based on sunrise.
time_point night_time (const time_point &p)
Returns the time it gets dark based on sunset.
time_point noon (const time_point &p)
Returns the time when the clock displays 12:00.
bool is_night (const time_point &p)
Returns true if it's currently night time - after dusk and before dawn.
bool is_day (const time_point &p)
Returns true if it's currently day time - after dawn and before dusk.
bool is_dusk (const time_point &p)
Returns true if it's currently dusk - between sunset and and twilight_duration after sunset.
bool is_dawn (const time_point &p)
Returns true if it's currently dawn - between sunrise and twilight_duration after sunrise.
float default_daylight_level ()
How much light is provided in full daylight.
float max_sun_irradiance ()
float sun_light_at (const time_point &p)
Returns the current sunlight.
float sun_irradiance (const time_point &p)
float sun_moon_light_at (const time_point &p)
Returns the current sunlight plus moonlight level.
float sun_moon_light_at_noon_near (const time_point &p)
How much light is provided at the solar noon nearest to given time.
std::pair< units::angle, units::angle > sun_azimuth_altitude (time_point)
std::optional< rl_vec2d > sunlight_angle (const time_point &)
Returns the offset by which a ray of sunlight would move when shifting down one z-level, or nullopt if the sun is below the horizon.
weekdays day_of_week (const time_point &p)
constexpr time_duration operator""_turns (const unsigned long long int v)
Convert the given number into an duration by calling the matching time_duration::from_* function.
constexpr time_duration operator""_seconds (const unsigned long long int v)
constexpr time_duration operator""_minutes (const unsigned long long int v)
constexpr time_duration operator""_hours (const unsigned long long int v)
constexpr time_duration operator""_days (const unsigned long long int v)
constexpr time_duration operator""_weeks (const unsigned long long int v)
Variables
const int calendar::INDEFINITELY_LONG
A number that represents the longest possible action.
const time_duration calendar::INDEFINITELY_LONG_DURATION
The expected duration of the cataclysm.
time_point calendar::start_of_cataclysm = calendar::turn_zero
time_point calendar::start_of_game = calendar::turn_zero
time_point calendar::turn = calendar::turn_zero
season_type calendar::initial_season = SPRING
constexpr time_point calendar::before_time_starts = time_point::from_turn(-1)
A time point that is always before the current turn, even when the game has just started.
constexpr time_point calendar::turn_zero = time_point::from_turn(0)
Represents time point 0.
constexpr time_point calendar::turn_max = time_point::from_turn(INT_MAX)
Largest possible time point.
Macro Definition Documentation
CATA_SRC_CALENDAR_H
#define CATA_SRC_CALENDAR_H
Definition at line 3 of file calendar.h.
Enumeration Type Documentation
clipped_align
enum clipped_align : int strong
Enumerator
none
right
compact
Definition at line 403 of file calendar.h.
                          : int {
     none,
     right,
     compact
 };
clipped_unit
enum clipped_unit : int strong
Enumerator
forever
second
minute
hour
day
week
season
year
Definition at line 409 of file calendar.h.
                         : int {
     forever,
     second,
     minute,
     hour,
     day,
     week,
     season,
     year,
 };
moon_phase
enum moon_phase
Phases of the moon.
Enumerator
MOON_NEW
New (completely dark) moon.
MOON_WAXING_CRESCENT
One quarter of moon lit, amount lit is increasing every day.
MOON_HALF_MOON_WAXING
One half of moon lit, amount lit is increasing every day.
MOON_WAXING_GIBBOUS
Three quarters of moon lit, amount lit is increasing every day.
MOON_FULL
Full moon.
MOON_WANING_GIBBOUS
Three quarters of moon lit, amount lit decreases every day.
MOON_HALF_MOON_WANING
Half of moon is lit, amount lit decreases every day.
MOON_WANING_CRESCENT
One quarter of moon lit, amount lit decreases every day.
MOON_PHASE_MAX
Not a valid moon phase, but can be used for iterating through enum.
Definition at line 35 of file calendar.h.
                 {
     /** New (completely dark) moon */
     MOON_NEW = 0,
     /** One quarter of moon lit, amount lit is increasing every day */
     MOON_WAXING_CRESCENT,
     /** One half of moon lit, amount lit is increasing every day */
     MOON_HALF_MOON_WAXING,
     /** Three quarters of moon lit, amount lit is increasing every day */
     MOON_WAXING_GIBBOUS,
     /** Full moon */
     MOON_FULL,
     /** Three quarters of moon lit, amount lit decreases every day */
     MOON_WANING_GIBBOUS,
     /** Half of moon is lit, amount lit decreases every day */
     MOON_HALF_MOON_WANING,
     /** One quarter of moon lit, amount lit decreases every day */
     MOON_WANING_CRESCENT,
     /** Not a valid moon phase, but can be used for iterating through enum */
     MOON_PHASE_MAX
 };
season_type
enum season_type
Real world seasons.
Enumerator
SPRING
SUMMER
AUTUMN
WINTER
NUM_SEASONS
Definition at line 21 of file calendar.h.
                  {
     SPRING = 0,
     SUMMER = 1,
     AUTUMN = 2,
     WINTER = 3,
     NUM_SEASONS
 };
time_accuracy
enum time_accuracy strong
Enumerator
NONE
No accuracy, no idea what time it is.
PARTIAL
Estimated time, can see the sky.
FULL
Full accuracy, using a timekeeping device.
NUM_TIME_ACCURACY
Unused, only for string conversions.
Definition at line 56 of file calendar.h.
{
     /** No accuracy, no idea what time it is **/
     NONE = 0,
     /** Estimated time, can see the sky **/
     PARTIAL = 1,
     /** Full accuracy, using a timekeeping device **/
     FULL = 2,
     /** Unused, only for string conversions **/
     NUM_TIME_ACCURACY
 };
weekdays
enum weekdays : int strong
Enumerator
SUNDAY
MONDAY
TUESDAY
WEDNESDAY
THURSDAY
FRIDAY
SATURDAY
Definition at line 640 of file calendar.h.
                     : int {
     SUNDAY = 0,
     MONDAY,
     TUESDAY,
     WEDNESDAY,
     THURSDAY,
     FRIDAY,
     SATURDAY,
 };
Function Documentation
clipped_time()
std::pair<int, clipped_unit> clipped_time (const time_duration & d)
Returns a value representing the passed in duration truncated to an appropriate unit along with the unit in question.
"10 days" or "1 minute". The chosen unit will be the smallest unit, that is at least as much as the given duration. E.g. an input of 60 minutes will return "1 hour", an input of 59 minutes will return "59 minutes".
Definition at line 503 of file calendar.cpp.
 {
     if( d >= calendar::INDEFINITELY_LONG_DURATION ) {
         return { 0, clipped_unit::forever };
     }
     if( d < 1_minutes ) {
         const int sec = to_seconds<int>( d );
         return { sec, clipped_unit::second };
     } else if( d < 1_hours ) {
         const int min = to_minutes<int>( d );
         return { min, clipped_unit::minute };
     } else if( d < 1_days ) {
         const int hour = to_hours<int>( d );
         return { hour, clipped_unit::hour };
     } else if( d < 7_days ) {
         const int day = to_days<int>( d );
         return { day, clipped_unit::day };
     } else if( d < calendar::season_length() || calendar::eternal_season() ) {
         // eternal seasons means one season is indistinguishable from the next,
         // therefore no way to count them
         const int week = to_weeks<int>( d );
         return { week, clipped_unit::week };
     } else if( d < calendar::year_length() && !calendar::eternal_season() ) {
         // TODO: consider a to_season function, but season length is variable, so
         // this might be misleading
         const int season = to_turns<int>( d ) / to_turns<int>( calendar::season_length() );
         return { season, clipped_unit::season };
     } else {
         // TODO: consider a to_year function, but year length is variable, so
         // this might be misleading
         const int year = to_turns<int>( d ) / to_turns<int>( calendar::year_length() );
         return { year, clipped_unit::year };
     }
 }
References day, calendar::eternal_season(), forever, hour, calendar::INDEFINITELY_LONG_DURATION, min(), minute, season, calendar::season_length(), second, week, year, and calendar::year_length().
Referenced by anonymous_namespace{item.cpp}::_stacks_rot(), and to_string_clipped().
day_of_season()
template<typename T > T day_of_season (const time_point & p) inline
This uses the current season length.
Definition at line 574 of file calendar.h.
 {
     return to_days<T>( ( p - calendar::turn_zero ) % calendar::season_length() );
 }
References calendar::season_length(), and calendar::turn_zero.
day_of_week()
weekdays day_of_week (const time_point & p)
Definition at line 666 of file calendar.cpp.
 {
     /* Design rationale:
      * <kevingranade> here's a question
      * <kevingranade> what day of the week is day 0?
      * <wito> Sunday
      * <GlyphGryph> Why does it matter?
      * <GlyphGryph> For like where people are and stuff?
      * <wito> 7 is also Sunday
      * <kevingranade> NOAA weather forecasts include day of week
      * <GlyphGryph> Also by day0 do you mean the day people start day 0
      * <GlyphGryph> Or actual day 0
      * <kevingranade> good point, turn 0
      * <GlyphGryph> So day 5
      * <wito> Oh, I thought we were talking about week day numbering in general.
      * <wito> Day 5 is a thursday, I think.
      * <wito> Nah, Day 5 feels like a thursday. :P
      * <wito> Which would put the apocalypse on a saturday?
      * <Starfyre> must be a thursday.  I was never able to get the hang of those.
      * <ZChris13> wito: seems about right to me
      * <wito> kevingranade: add four for thursday. ;)
      * <kevingranade> sounds like consensus to me
      * <kevingranade> Thursday it is */
     const int day_since_cataclysm = to_days<int>( p - calendar::turn_zero );
     static const weekdays start_day = weekdays::THURSDAY;
     const int result = day_since_cataclysm + static_cast<int>( start_day );
     return static_cast<weekdays>( result % 7 );
 }
References THURSDAY, and calendar::turn_zero.
Referenced by weather_forecast().
daylight_time()
time_point daylight_time (const time_point & p)
Returns the time it gets light based on sunrise.
Definition at line 333 of file calendar.cpp.
 {
     return sun_at_altitude( civil_dawn, location.longitude, p, false );
 }
References civil_dawn, location, lat_long::longitude, and sun_at_altitude().
Referenced by anonymous_namespace{math_parser_diag.cpp}::time_until_eval(), and wait().
default_daylight_level()
float default_daylight_level ()
How much light is provided in full daylight.
Definition at line 47 of file calendar.cpp.
 {
     return 100.0f;
 }
Referenced by game::natural_light_level(), monster::process_triggers(), Creature::sees(), and monster::sight_range().
get_diary_time_since_str()
std::string get_diary_time_since_str (const time_duration & turn_diff, time_accuracy acc)
Time approximation based on the player's timekeeping capability, formatted for diary pages.
Definition at line 847 of file calendar.cpp.
 {
     const int days = to_days<int>( turn_diff );
     const int hours = to_hours<int>( turn_diff ) % 24;
     const int minutes = to_minutes<int>( turn_diff ) % 60;
     std::string days_text;
     std::string hours_text;
     std::string minutes_text;
     switch( acc ) {
         case time_accuracy::FULL:
             if( days > 0 ) {
                 days_text = string_format( n_gettext( "%d day, ", "%d days, ", days ), days );
             }
             if( hours > 0 ) {
                 hours_text = string_format( n_gettext( "%d hour, ", "%d hours, ", hours ), hours );
             }
             minutes_text = string_format( n_gettext( "%d minute", "%d minutes", minutes ), minutes );
             break;
         case time_accuracy::PARTIAL:
             if( days > 0 ) {
                 days_text = string_format( n_gettext( "%d day", "%d days", days ), days );
             } else if( hours > 0 ) {
                 //~ Estimate of how much time has passed since the last entry
                 days_text = _( "Less than a day" );
             } else {
                 //~ Estimate of how much time has passed since the last entry
                 days_text = _( "Not long" );
             }
             break;
         default:
             DebugLog( DebugLevel::D_WARNING, DebugClass::D_GAME )
                     << "Unknown time_accuracy " << io::enum_to_string<time_accuracy>( acc );
         /* fallthrough */
         case time_accuracy::NUM_TIME_ACCURACY:
         case time_accuracy::NONE:
             //~ Estimate of how much time has passed since the last entry
             days_text = days > 0 ? _( "A long while" ) : hours > 0 ? _( "A while" ) : _( "A short while" );
             break;
     }
     //~ %1$s is xx days, %2$s is xx hours, %3$s is xx minutes
     return string_format( _( "%1$s%2$s%3$s since last entry" ), days_text, hours_text, minutes_text );
 }
References _, D_GAME, D_WARNING, DebugLog(), io::enum_to_string< time_accuracy >(), FULL, n_gettext, NONE, NUM_TIME_ACCURACY, PARTIAL, and string_format().
Referenced by diary::get_head_text().
get_diary_time_str()
std::string get_diary_time_str (const time_point & turn, time_accuracy acc)
Time approximation based on the player's timekeeping capability, formatted for diary pages.
Definition at line 891 of file calendar.cpp.
 {
     const int year = to_turns<int>( turn - calendar::turn_zero ) /
                      to_turns<int>( calendar::year_length() ) + 1;
     const int day = day_of_season<int>( turn ) + 1;
     switch( acc ) {
         case time_accuracy::FULL:
             return to_string( turn );
         case time_accuracy::PARTIAL:
             // partial accuracy, able to see the sky
             //~ Time of year:
             //~ $1 = year since Cataclysm
             //~ $2 = season
             //~ $3 = day of season
             //~ $4 = approximate time of day
             return string_format( _( "Year %1$d, %2$s, day %3$d, %4$s" ), year,
                                   calendar::name_season( season_of_year( turn ) ),
                                   day, display::time_approx( turn ) );
         default:
             DebugLog( DebugLevel::D_WARNING, DebugClass::D_GAME )
                     << "Unknown time_accuracy " << io::enum_to_string<time_accuracy>( acc );
         /* fallthrough */
         case time_accuracy::NUM_TIME_ACCURACY:
         case time_accuracy::NONE: {
             // normalized to 100 day seasons
             const int day_norm = ( day * 100 ) / to_days<int>( calendar::season_length() );
             std::string seas_point;
             if( day_norm < 33 ) {
                 //~ Estimated point in the current season
                 seas_point = pgettext( "time of season", "Early" );
             } else if( day_norm < 66 ) {
                 //~ Estimated point in the current season
                 seas_point = pgettext( "time of season", "Mid" );
             } else {
                 //~ Estimated point in the current season
                 seas_point = pgettext( "time of season", "Late" );
             }
             //~ Estimated day-of-season string: $1 = Early/Mid/Late, $2 = Spring/Summer/Fall/Winter
             std::string season = string_format( _( "%1$s %2$s" ), seas_point,
                                                 calendar::name_season( season_of_year( turn ) ) );
             //~ Time of year: $1 = year since Cataclysm, $2 = season
             return string_format( _( "Year %1$d, %2$s" ), year, season );
         }
     }
     return std::string();
 }
References _, D_GAME, D_WARNING, day, DebugLog(), io::enum_to_string< time_accuracy >(), FULL, calendar::name_season(), NONE, NUM_TIME_ACCURACY, PARTIAL, pgettext, season, calendar::season_length(), season_of_year(), string_format(), display::time_approx(), to_string(), calendar::turn, calendar::turn_zero, year, and calendar::year_length().
Referenced by diary::get_head_text(), and diary::get_pages_list().
get_moon_phase()
moon_phase get_moon_phase (const time_point & p)
Returns the current phase of the moon.
Definition at line 98 of file calendar.cpp.
 {
     const time_duration moon_phase_duration = calendar::season_from_default_ratio() * lunar_month();
     // Switch moon phase at noon so it stays the same all night
     const int num_middays = to_days<int>( p - calendar::turn_zero + 1_days / 2 );
     const time_duration nearest_midnight = num_middays * 1_days;
     const double phase_change = nearest_midnight / moon_phase_duration;
     const int current_phase = static_cast<int>( std::round( phase_change * MOON_PHASE_MAX ) ) %
                               static_cast<int>( MOON_PHASE_MAX );
     return static_cast<moon_phase>( current_phase );
 }
References lunar_month(), MOON_PHASE_MAX, round(), calendar::season_from_default_ratio(), and calendar::turn_zero.
Referenced by moon_light_at(), anonymous_namespace{math_parser_diag.cpp}::moon_phase_eval(), and relic::try_recharge().
hour_of_day()
template<typename T > T hour_of_day (const time_point & p) inline
Definition at line 567 of file calendar.h.
 {
     return to_hours<T>( ( p - calendar::turn_zero ) % 1_days );
 }
References calendar::turn_zero.
is_dawn()
bool is_dawn (const time_point & p)
Returns true if it's currently dawn - between sunrise and twilight_duration after sunrise.
Definition at line 367 of file calendar.cpp.
 {
     const time_duration now = time_past_midnight( p );
     return now < 12_hours && is_twilight( p );
 }
References is_twilight(), and time_past_midnight().
Referenced by photo_def_for_camera_point(), and display::time_approx().
is_day()
bool is_day (const time_point & p)
Returns true if it's currently day time - after dawn and before dusk.
Definition at line 350 of file calendar.cpp.
 {
     return sun_altitude( p ) >= sunrise_angle;
 }
References sun_altitude(), and sunrise_angle.
Referenced by can_recharge_solar().
is_dusk()
bool is_dusk (const time_point & p)
Returns true if it's currently dusk - between sunset and and twilight_duration after sunset.
Definition at line 361 of file calendar.cpp.
 {
     const time_duration now = time_past_midnight( p );
     return now > 12_hours && is_twilight( p );
 }
References is_twilight(), and time_past_midnight().
Referenced by photo_def_for_camera_point(), and display::time_approx().
is_night()
bool is_night (const time_point & p)
Returns true if it's currently night time - after dusk and before dawn.
Definition at line 345 of file calendar.cpp.
 {
     return sun_altitude( p ) <= civil_dawn;
 }
References civil_dawn, and sun_altitude().
Referenced by can_recharge_lunar(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_day(), photo_def_for_camera_point(), sounds::process_sound_markers(), display::time_approx(), and weather_forecast().
lunar_month()
time_duration lunar_month ()
Returns the default duration of a lunar month (duration between syzygies)
Definition at line 57 of file calendar.cpp.
 {
     return 29.530588853 * 1_days;
 }
Referenced by get_moon_phase().
max_sun_irradiance()
float max_sun_irradiance ()
Definition at line 52 of file calendar.cpp.
 {
     return 1000.f;
 }
Referenced by sun_irradiance(), vehicle::total_solar_epower(), Character::update_bodytemp(), and vehicle::update_time().
minute_of_hour()
template<typename T > T minute_of_hour (const time_point & p) inline
Definition at line 561 of file calendar.h.
 {
     return to_minutes<T>( ( p - calendar::turn_zero ) % 1_hours );
 }
References calendar::turn_zero.
night_time()
time_point night_time (const time_point & p)
Returns the time it gets dark based on sunset.
Definition at line 328 of file calendar.cpp.
 {
     return sun_at_altitude( civil_dawn, location.longitude, p, true );
 }
References civil_dawn, location, lat_long::longitude, and sun_at_altitude().
Referenced by anonymous_namespace{math_parser_diag.cpp}::time_until_eval(), and wait().
noon()
time_point noon (const time_point & p)
Returns the time when the clock displays 12:00.
Definition at line 338 of file calendar.cpp.
 {
     const time_duration time_of_day = ( p - calendar::turn_zero ) % 1_days;
     const time_duration till_noon = time_of_day - 12_hours;
     return ( till_noon > 0_seconds ) ? p - till_noon : p + till_noon;
 }
References calendar::turn_zero.
Referenced by anonymous_namespace{math_parser_diag.cpp}::time_since_eval(), and anonymous_namespace{math_parser_diag.cpp}::time_until_eval().
operator""_days()
constexpr time_duration operator""_days (const unsigned long long int v) constexpr
Definition at line 383 of file calendar.h.
 {
     return time_duration::from_days( v );
 }
References time_duration::from_days().
operator""_hours()
constexpr time_duration operator""_hours (const unsigned long long int v) constexpr
Definition at line 379 of file calendar.h.
 {
     return time_duration::from_hours( v );
 }
References time_duration::from_hours().
operator""_minutes()
constexpr time_duration operator""_minutes (const unsigned long long int v) constexpr
Definition at line 375 of file calendar.h.
 {
     return time_duration::from_minutes( v );
 }
References time_duration::from_minutes().
operator""_seconds()
constexpr time_duration operator""_seconds (const unsigned long long int v) constexpr
Definition at line 371 of file calendar.h.
 {
     return time_duration::from_seconds( v );
 }
References time_duration::from_seconds().
operator""_turns()
constexpr time_duration operator""_turns (const unsigned long long int v) constexpr
Convert the given number into an duration by calling the matching time_duration::from_* function.
Definition at line 367 of file calendar.h.
 {
     return time_duration::from_turns( v );
 }
References time_duration::from_turns().
operator""_weeks()
constexpr time_duration operator""_weeks (const unsigned long long int v) constexpr
Definition at line 387 of file calendar.h.
 {
     return time_duration::from_weeks( v );
 }
References time_duration::from_weeks().
operator*() [1/2]
template<typename T > constexpr time_duration operator* (const time_duration & lhs, T rhs) constexpr
Definition at line 338 of file calendar.h.
{
             return time_duration( lhs.turns_ * rhs );
         }
Referenced by pimpl< T >::deserialize(), pimpl< T >::operator=(), pimpl< T >::operator==(), and pimpl< T >::serialize().
operator*() [2/2]
template<typename T > constexpr time_duration operator* (T lhs, const time_duration & rhs) constexpr
Definition at line 342 of file calendar.h.
{
             return time_duration( lhs * rhs.turns_ );
         }
operator*=()
template<typename T > time_duration& operator*= (time_duration & lhs, T rhs) inline
Definition at line 346 of file calendar.h.
{
             return lhs = time_duration( lhs.turns_ * rhs );
         }
operator/()
template<typename T > constexpr time_duration operator/ (const time_duration & lhs, T rhs) constexpr
Definition at line 330 of file calendar.h.
{
             return time_duration( lhs.turns_ / rhs );
         }
operator/=()
template<typename T > time_duration& operator/= (time_duration & lhs, T rhs) inline
Definition at line 334 of file calendar.h.
{
             return lhs = time_duration( lhs.turns_ / rhs );
         }
season_of_year()
season_type season_of_year (const time_point & p)
Returns
The season of the of the given time point. Returns the same season for any input if the calendar::eternal_season yields true.
Definition at line 810 of file calendar.cpp.
 {
     static time_point prev_turn = calendar::before_time_starts;
     static season_type prev_season = calendar::initial_season;
     if( p != prev_turn ) {
         prev_turn = p;
         if( calendar::eternal_season() ) {
             // If we use calendar::start to determine the initial season, and the user shortens the season length
             // mid-game, the result could be the wrong season!
             return prev_season = calendar::initial_season;
         }
         return prev_season = static_cast<season_type>(
                                  to_turn<int>( p ) / to_turns<int>( calendar::season_length() ) % 4
                              );
     }
     return prev_season;
 }
References calendar::before_time_starts, calendar::eternal_season(), calendar::initial_season, and calendar::season_length().
Referenced by sounds::add_footstep(), map_data_common_t::color(), display::date_string(), dead_plant(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_season(), forage_activity_actor::finish(), iexamine::flower_marloss(), talk_function::forage_return(), basecamp::gathering_return(), get_common_data(), get_diary_time_str(), map_data_common_t::get_harvest(), MonsterGroupManager::GetResultFromGroup(), glare(), monster::mating_angry(), monexamine::pet_menu(), map::restock_fruits(), calendar_ui::select_time_point(), sounds::sound(), map_data_common_t::symbol(), weather_generator::test_weather(), to_string(), and monster::try_reproduce().
sun_azimuth_altitude()
std::pair<units::angle, units::angle> sun_azimuth_altitude (time_point ti)
Definition at line 188 of file calendar.cpp.
 {
     const season_effective_time t = season_effective_time( ti );
     units::angle right_ascension;
     units::angle declination;
     time_duration timezone = angle_to_time( location.longitude );
     std::tie( right_ascension, declination ) = sun_ra_declination( t, timezone );
     const units::angle sidereal_time = sidereal_time_at( t, location.longitude, timezone );
     const units::angle hour_angle = sidereal_time - right_ascension;
     // Use a two-step transformation to convert equatorial coordinates to
     // horizontal.
     // https://en.wikipedia.org/wiki/Celestial_coordinate_system#Equatorial_%E2%86%94_horizontal
     const rl_vec3d intermediate(
         cos( hour_angle ) * cos( declination ),
         sin( hour_angle ) * cos( declination ),
         sin( declination ) );
     const rl_vec3d horizontal(
         -intermediate.x * sin( location.latitude ) +
         intermediate.z * cos( location.latitude ),
         intermediate.y,
         intermediate.x * cos( location.latitude ) +
         intermediate.z * sin( location.latitude )
     );
     // Azimuth is from the South, turning positive to the west
     const units::angle azimuth = normalize( -atan2( horizontal.xy() ) + 180_degrees );
     units::angle altitude = units::asin( horizontal.z );
     if( calendar::eternal_day() ) {
         altitude = 90_degrees;
     }
     if( calendar::eternal_night() ) {
         altitude = astronomical_dawn - 10_degrees;
     }
     /*printf(
         "\n"
         "right_ascension = %f, declination = %f\n"
         "sidereal_time = %f, hour_angle = %f\n"
         "aziumth = %f, altitude = %f\n",
         to_degrees( right_ascension ), to_degrees( declination ),
         to_degrees( sidereal_time ), to_degrees( hour_angle ),
         to_degrees( azimuth ), to_degrees( altitude ) );*/
     return std::make_pair( azimuth, altitude );
 }
References angle_to_time(), units::asin(), astronomical_dawn, atan2(), cos(), calendar::eternal_day(), calendar::eternal_night(), lat_long::latitude, location, lat_long::longitude, normalize(), sidereal_time_at(), sin(), sun_ra_declination(), rl_vec3d::x, rl_vec3d::xy(), rl_vec3d::y, and rl_vec3d::z.
Referenced by iuse::sextant(), sun_altitude(), display::sundial_text_color(), and sunlight_angle().
sun_irradiance()
float sun_irradiance (const time_point & p)
Definition at line 406 of file calendar.cpp.
 {
     const units::angle solar_alt = sun_altitude( p );
     if( solar_alt < 0_degrees ) {
         return 0;
     }
     return max_sun_irradiance() * sin( solar_alt );
 }
References max_sun_irradiance(), sin(), and sun_altitude().
Referenced by iuse::dbg_lux_meter(), and incident_sun_irradiance().
sun_light_at()
float sun_light_at (const time_point & p)
Returns the current sunlight.
Based entirely on astronomical circumstances; does not account for e.g. weather. For most situations you actually want to call the below function which also includes moonlight.
Definition at line 383 of file calendar.cpp.
 {
     const units::angle solar_alt = sun_altitude( p );
     if( solar_alt < astronomical_dawn ) {
         return 0;
     } else if( solar_alt <= nautical_dawn ) {
         // Sunlight rises exponentially from 0 to 3.7f as sun rises from -18 to -12
         return 3.7f * ( std::exp2( to_degrees( solar_alt - astronomical_dawn ) / 6.f ) - 1 );
     } else if( solar_alt <= civil_dawn ) {
         // Sunlight rises exponentially from 3.7f to 5.0f as sun rises from -12 to -6
         return ( 5.0f - 3.7f ) * ( std::exp2( to_degrees( solar_alt - nautical_dawn ) / 6.f ) - 1 ) + 3.7f;
     } else if( solar_alt <= sunrise_angle ) {
         // Sunlight rises exponentially from 5.0f to 60 as sun rises from -6 to -1
         return ( 60 - 5.0f ) * ( std::exp2( to_degrees( solar_alt - civil_dawn ) / 5.f ) - 1 ) + 5.0f;
     } else if( solar_alt <= 60_degrees ) {
         // Linear increase from -1 to 60 degrees light increases from 60 to 125 brightness.
         return ( 65.f / 61 ) * to_degrees( solar_alt ) + 65.f / 61  + 60;
     } else {
         return 125.f;
     }
 }
References astronomical_dawn, civil_dawn, nautical_dawn, sun_altitude(), sunrise_angle, and units::to_degrees().
Referenced by iuse::dbg_lux_meter(), incident_sunlight(), sun_moon_light_at(), and display::sundial_text_color().
sun_moon_light_at()
float sun_moon_light_at (const time_point & p)
Returns the current sunlight plus moonlight level.
Based entirely on astronomical circumstances; does not account for e.g. weather.
Definition at line 416 of file calendar.cpp.
 {
     return sun_light_at( p ) + moon_light_at( p );
 }
References moon_light_at(), and sun_light_at().
Referenced by game::natural_light_level(), and sun_moon_light_at_noon_near().
sun_moon_light_at_noon_near()
float sun_moon_light_at_noon_near (const time_point & p)
How much light is provided at the solar noon nearest to given time.
Definition at line 421 of file calendar.cpp.
 {
     const time_point solar_noon = solar_noon_near( p );
     return sun_moon_light_at( solar_noon );
 }
References solar_noon_near(), and sun_moon_light_at().
Referenced by editmap::update_view_with_help().
sunlight_angle()
std::optional<rl_vec2d> sunlight_angle (const time_point & t)
Returns the offset by which a ray of sunlight would move when shifting down one z-level, or nullopt if the sun is below the horizon.
Definition at line 244 of file calendar.cpp.
 {
     units::angle azimuth;
     units::angle altitude;
     std::tie( azimuth, altitude ) = sun_azimuth_altitude( t );
     if( altitude <= sunrise_angle ) {
         // Sun below horizon
         return std::nullopt;
     }
     rl_vec2d horizontal_direction( -sin( azimuth ), cos( azimuth ) );
     rl_vec3d direction( horizontal_direction * cos( altitude ), sin( altitude ) );
     direction /= -direction.z;
     return direction.xy();
 }
References cos(), sin(), sun_azimuth_altitude(), and sunrise_angle.
sunrise()
time_point sunrise (const time_point & p)
Returns the current sunrise time based on the time of year.
Definition at line 318 of file calendar.cpp.
 {
     return sun_at_altitude( sunrise_angle, location.longitude, p, false );
 }
References location, lat_long::longitude, sun_at_altitude(), and sunrise_angle.
Referenced by MonsterGroupManager::GetResultFromGroup(), is_spawn_valid(), and anonymous_namespace{math_parser_diag.cpp}::time_until_eval().
sunset()
time_point sunset (const time_point & p)
Returns the current sunset time based on the time of year.
Definition at line 323 of file calendar.cpp.
 {
     return sun_at_altitude( sunrise_angle, location.longitude, p, true );
 }
References location, lat_long::longitude, sun_at_altitude(), and sunrise_angle.
Referenced by MonsterGroupManager::GetResultFromGroup(), is_spawn_valid(), display::sundial_text_color(), and anonymous_namespace{math_parser_diag.cpp}::time_until_eval().
time_past_midnight()
time_duration time_past_midnight (const time_point & p) inline
Definition at line 550 of file calendar.h.
 {
     return ( p - calendar::turn_zero ) % 1_days;
 }
References calendar::turn_zero.
Referenced by is_dawn(), is_dusk(), print_time_just_hour(), season_effective_time::season_effective_time(), solar_noon_near(), anonymous_namespace{math_parser_diag.cpp}::time_since_eval(), to_string_time_of_day(), wait(), and weather_temperature_from_common_data().
time_past_new_year()
time_duration time_past_new_year (const time_point & p) inline
Definition at line 555 of file calendar.h.
 {
     return ( p - calendar::turn_zero ) % calendar::year_length();
 }
References calendar::turn_zero, and calendar::year_length().
Referenced by get_common_data(), weather_generator::get_water_temperature(), map::produce_sap(), weather_generator::test_weather(), and to_string().
to_days()
template<typename T > constexpr T to_days (const time_duration & duration) constexpr
Definition at line 278 of file calendar.h.
{
             return static_cast<T>( duration.turns_ ) / static_cast<T>( 60 * 60 * 24 );
         }
to_hours()
template<typename T > constexpr T to_hours (const time_duration & duration) constexpr
Definition at line 274 of file calendar.h.
{
             return static_cast<T>( duration.turns_ ) / static_cast<T>( 60 * 60 );
         }
to_minutes()
template<typename T > constexpr T to_minutes (const time_duration & duration) constexpr
Definition at line 270 of file calendar.h.
{
             return static_cast<T>( duration.turns_ ) / static_cast<T>( 60 );
         }
to_moves()
template<typename T > constexpr T to_moves (const time_duration & duration) constexpr
Definition at line 286 of file calendar.h.
{
             return to_turns<int>( duration ) * 100;
         }
to_seconds()
template<typename T > constexpr T to_seconds (const time_duration & duration) constexpr
Definition at line 266 of file calendar.h.
{
             return duration.turns_;
         }
to_string() [1/2]
std::string to_string (const time_duration & d, bool compact = false)
Returns a string showing a duration.
The string contains at most two numbers along with their units. E.g. 3661 seconds will return "1 hour and 1 minute" (the 1 additional second is clipped). An input of 3601 will return "1 hour" (the second is clipped again and the number of additional minutes would be 0 so it's skipped).
Parameters
compact True for compact display of time. Example: 1 min 15 secs
Definition at line 546 of file calendar.cpp.
 {
     if( d >= calendar::INDEFINITELY_LONG_DURATION ) {
         return _( "forever" );
     }
     if( d <= 1_minutes ) {
         return to_string_clipped( d );
     }
     time_duration divider = 0_turns;
     if( d < 1_hours ) {
         divider = 1_minutes;
     } else if( d < 1_days ) {
         divider = 1_hours;
     } else if( d < 1_weeks ) {
         divider = 1_days;
     } else if( d < calendar::season_length() || calendar::eternal_season() ) {
         divider = 1_weeks;
     } else if( d < calendar::year_length() ) {
         divider = calendar::season_length();
     } else {
         divider = calendar::year_length();
     }
     if( d % divider != 0_turns ) {
         if( compact ) {
             //~ %1$s - greater units of time (e.g. 3 hours), %2$s - lesser units of time (e.g. 11 minutes).
             return string_format( pgettext( "time duration", "%1$s %2$s" ),
                                   to_string_clipped( d, clipped_align::compact ),
                                   to_string_clipped( d % divider, clipped_align::compact ) );
         } else {
             //~ %1$s - greater units of time (e.g. 3 hours), %2$s - lesser units of time (e.g. 11 minutes).
             return string_format( _( "%1$s and %2$s" ),
                                   to_string_clipped( d ),
                                   to_string_clipped( d % divider ) );
         }
     }
     return to_string_clipped( d );
 }
References _, compact, calendar::eternal_season(), calendar::INDEFINITELY_LONG_DURATION, pgettext, calendar::season_length(), string_format(), to_string_clipped(), and calendar::year_length().
Referenced by abstract_read_var_info(), target_ui::action_switch_mode(), assemble_scenario_details(), iexamine::autoclave_full(), iexamine::autodoc(), eoc_examine_actor::call(), camp_trip_description(), cata_variant::cata_variant(), small_literal_vector< T, kInlineCount, SizeT >::check_capacity(), basecamp::choose_new_leader(), color_number(), comestible_inventory_preset::comestible_inventory_preset(), talk_function::commune_carpentry(), talk_function::commune_forage(), talk_function::commune_menial(), talk_function::commune_refuge_caravan(), item_pocket::contents_info(), cata::convert(), basecamp::craft_description(), debug_menu::debug(), debug_menu::debug_menu_force_temperature(), map::decay_fields_and_scent(), item::disassembly_info(), effect::disp_desc(), units::display(), draw_bionics_titlebar(), prof_window::draw_details(), draw_proficiencies_info(), mission_ui_impl::draw_selected_description(), game_menus::inv::ebooksave(), edit_integer(), editmap::edit_itm(), spell::energy_cost_string(), spell::energy_cur_string(), enumerate_ints_to_string(), jmath_func::eval(), monster::extended_description(), npc::faction_display(), base_camps::faction_encode_abs(), basecamp::farm_description(), item::food_info(), iuse::foodperson(), map::generate(), debug_menu::generate_effect_list(), generic_multi_activity_check_requirement(), basecamp::get_available_missions_by_dir(), get_diary_time_str(), basecamp::get_equipment(), vehicle::get_folded_item(), TextJsonIn::get_int(), TextJsonIn::get_int64(), cata::string_formatter::get_nth_arg_as(), bionic_install_preset::get_operation_duration(), bionic_install_surgeon_preset::get_operation_duration(), npc::get_restock_interval(), construction::get_time_string(), TextJsonIn::get_uint(), get_unique_group_id(), get_unique_trait_group_id(), inventory_selector::get_weight_and_length_stat(), basecamp::give_equipment(), Character::heat_emission(), talk_function::hospital_raid(), basecamp::job_assignment_ui(), mutation_branch::load(), bionic_data::load(), item::make_corpse(), base_camps::max_upgrade_by_type(), item::med_info(), iuse::mininuke(), ml_to_string(), Character::mod_stamina(), moves_to_string(), basecamp::om_upgrade_description(), damage_type::ondamage_effects(), JsonArray::operator[](), cata::string_formatter::parse(), monexamine::pay_bot(), iexamine::pay_gas(), photo_def_for_camera_point(), display::power_balance_text_color(), display::power_text_color(), debug_menu::prepare_export_dir_and_find_unused_name(), print_damage_info(), anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount(), prompt_for_amount(), iexamine::quern_examine(), Character::queue_effect(), iuse::radiocontrol(), read_inventory_preset::read_inventory_preset(), recipe_info(), teleporter_callback::refresh(), reload_furniture(), game::save_achievements(), flexbuffer_disk_cache::save_to_disk(), talk_function::scavenger_patrol(), talk_function::scavenger_raid(), calendar_ui::select_time_point(), set_description(), safemode::show(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), basecamp::start_salt_water_pipe(), iexamine::stook_full(), Character::store(), text_style_check(), cata_variant_detail::convert< cata_variant_type::bool_ >::to_string(), cata_variant_detail::convert< cata_variant_type::character_id >::to_string(), cata_variant_detail::convert< cata_variant_type::int_ >::to_string(), cata_variant_detail::convert< cata_variant_type::chrono_seconds >::to_string(), tileray::to_string_azimuth_from_north(), achievement::time_bound::ui_text(), achievement_state::ui_text(), overmap::unserialize_omap(), update_emergency_recall(), options_manager::update_options_cache(), update_time_fixed(), update_time_left(), vol_to_string(), wait(), iuse::wash_items(), weight_to_string(), debug_menu::wind_speed(), cataimgui::window::window(), debug_menu::wisheffect(), and memorial_logger::write_text_memorial().
to_string() [2/2]
std::string to_string (const time_point & p)
Returns
The time point formatted to be shown to the player. Contains year, season, day and time of day.
Definition at line 830 of file calendar.cpp.
 {
     const int year = to_turns<int>( p - calendar::turn_zero ) / to_turns<int>
                      ( calendar::year_length() ) + 1;
     const std::string time = to_string_time_of_day( p );
     if( calendar::eternal_season() ) {
         const int day = to_days<int>( time_past_new_year( p ) );
         //~ 1 is the year, 2 is the day (of the *year*), 3 is the time of the day in its usual format
         return string_format( _( "Year %1$d, day %2$d %3$s" ), year, day, time );
     } else {
         const int day = day_of_season<int>( p ) + 1;
         //~ 1 is the year, 2 is the season name, 3 is the day (of the season), 4 is the time of the day in its usual format
         return string_format( _( "Year %1$d, %2$s, day %3$d %4$s" ), year,
                               calendar::name_season( season_of_year( p ) ), day, time );
     }
 }
References _, day, calendar::eternal_season(), calendar::name_season(), season_of_year(), string_format(), time_past_new_year(), to_string_time_of_day(), calendar::turn_zero, year, and calendar::year_length().
to_string_approx()
std::string to_string_approx (const time_duration & dur, bool verbose = true)
Returns approximate duration.
Parameters
verbose If true, 'less than' and 'more than' will be printed instead of '<' and '>' respectively.
Definition at line 587 of file calendar.cpp.
 {
     time_duration d = dur;
     const auto make_result = [verbose]( const time_duration & d, const char *verbose_str,
     const char *short_str ) {
         return string_format( verbose ? verbose_str : short_str, to_string_clipped( d ) );
     };
     time_duration divider = 0_turns;
     time_duration vicinity = 0_turns;
     // Minutes and seconds can be estimated precisely.
     if( d > 1_days ) {
         divider = 1_days;
         vicinity = 2_hours;
     } else if( d > 1_hours ) {
         divider = 1_hours;
         vicinity = 5_minutes;
     }
     if( divider != 0_turns ) {
         const time_duration remainder = d % divider;
         if( remainder >= divider - vicinity ) {
             d += divider;
         } else if( remainder > vicinity ) {
             if( remainder < divider / 2 ) {
                 //~ %s - time (e.g. 2 hours).
                 return make_result( d, _( "more than %s" ), ">%s" );
             } else {
                 //~ %s - time (e.g. 2 hours).
                 return make_result( d + divider, _( "less than %s" ), "<%s" );
             }
         }
     }
     //~ %s - time (e.g. 2 hours).
     return make_result( d, _( "about %s" ), "%s" );
 }
References _, dur, make_result(), string_format(), and to_string_clipped().
Referenced by item::disassembly_info(), mission_ui_impl::draw_selected_description(), dialogue::dynamic_line(), talker_npc::evaluation_by(), veh_interact::format_reqs(), get_fire_fuel_string(), get_freshness_description(), comestible_inventory_preset::get_time_left_rounded(), Character::mend_item(), and read_inventory_preset::read_inventory_preset().
to_string_clipped()
std::string to_string_clipped (const time_duration & d, clipped_align align = clipped_align::none)
Returns a string showing a duration as whole number of appropriate units, e.g.
"10 days" or "1 minute". The chosen unit will be the smallest unit, that is at least as much as the given duration. E.g. an input of 60 minutes will return "1 hour", an input of 59 minutes will return "59 minutes".
Parameters
align none, right, or compact.
Definition at line 539 of file calendar.cpp.
 {
     const std::pair<int, clipped_unit> time = clipped_time( d );
     return to_string_clipped( time.first, time.second, align );
 }
References clipped_time(), and to_string_clipped().
to_string_time_of_day()
std::string to_string_time_of_day (const time_point & p)
Returns
The time point formatted to be shown to the player. Contains only the time of day, not the year, day or season.
Definition at line 639 of file calendar.cpp.
 {
     const int hour = hour_of_day<int>( p );
     const int minute = minute_of_hour<int>( p );
     const int second = to_seconds<int>( time_past_midnight( p ) ) % 60;
     const std::string format_type = get_option<std::string>( "24_HOUR" );
     if( format_type == "military" ) {
         return string_format( "%02d%02d.%02d", hour, minute, second );
     } else if( format_type == "24h" ) {
         //~ hour:minute (24hr time display)
         return string_format( _( "%02d:%02d:%02d" ), hour, minute, second );
     } else {
         int hour_param = hour % 12;
         if( hour_param == 0 ) {
             hour_param = 12;
         }
         // Padding is removed as necessary to prevent clipping with SAFE notification in wide sidebar mode
         const std::string padding = hour_param < 10 ? " " : "";
         if( hour < 12 ) {
             return string_format( _( "%d:%02d:%02d%sAM" ), hour_param, minute, second, padding );
         } else {
             return string_format( _( "%d:%02d:%02d%sPM" ), hour_param, minute, second, padding );
         }
     }
 }
References _, hour, minute, second, string_format(), and time_past_midnight().
Referenced by anonymous_namespace{messages.cpp}::messages_impl::recent_messages(), advanced_inventory::redraw_sidebar(), display::sundial_time_text_color(), display::time_string(), to_string(), wait(), and weather_forecast().
to_string_writable()
std::string to_string_writable (const time_duration & dur)
Returns a string that is writable to JSON that is also readable from JSON.
Definition at line 626 of file calendar.cpp.
 {
     if( dur % 1_days == 0_seconds ) {
         return string_format( "%d d", static_cast<int>( dur / 1_days ) );
     } else if( dur % 1_hours == 0_seconds ) {
         return string_format( "%d h", static_cast<int>( dur / 1_hours ) );
     } else if( dur % 1_minutes == 0_seconds ) {
         return string_format( "%d m", static_cast<int>( dur / 1_minutes ) );
     } else {
         return string_format( "%d s", static_cast<int>( dur / 1_seconds ) );
     }
 }
References dur, and string_format().
Referenced by Character::check_outbounds_activity(), read_activity_actor::do_turn(), safecracking_activity_actor::do_turn(), read_activity_actor::finish(), avatar::read(), enchant_cache::serialize(), effect::set_duration(), harvest_activity_actor::start(), lockpick_activity_actor::start(), ebooksave_activity_actor::start(), read_activity_actor::start(), safecracking_activity_actor::start(), and shearing_activity_actor::start().
to_turn()
template<typename T > constexpr T to_turn (const time_point & point) constexpr
Definition at line 481 of file calendar.h.
{
             return point.turn_;
         }
to_turns()
template<typename T > constexpr T to_turns (const time_duration & duration) constexpr
The conversions is done with values of the given template type. That means using an integer type (e.g. int) will return a truncated value (amount of full minutes that make up the duration, discarding the remainder). Calling to_minutes<double> will return a precise number. Example: to_hours<int>(from_minutes(90)) == 1 to_hours<double>(from_minutes(90)) == 1.5
Definition at line 262 of file calendar.h.
{
             return duration.turns_;
         }
to_weeks()
template<typename T > constexpr T to_weeks (const time_duration & duration) constexpr
Definition at line 282 of file calendar.h.
{
             return static_cast<T>( duration.turns_ ) / static_cast<T>( 60 * 60 * 24 * 7 );
         }
x_in_y()
bool x_in_y (const time_duration & a, const time_duration & b)
See also
x_in_y(int,int)
Definition at line 784 of file calendar.cpp.
 {
     return ::x_in_y( to_turns<int>( a ), to_turns<int>( b ) );
 }
References a, and b.
Referenced by effect::activated(), overmap::add_mon_group(), alcohol_diazepam_add(), amphetamine_effect(), monster::anger_hostile_seen(), monster::anger_mating_season(), jmapgen_monster::apply(), jmapgen_vehicle::apply(), jmapgen_sealed_item::apply(), apply_ammo_effects(), projectile::apply_effects_damage(), iuse::bell(), Character::block_hit(), leap_actor::call(), melee_actor::call(), Character::can_escape_trap(), iuse::can_goo(), check_butcher_dissect(), Character::check_mount_is_spooked(), Character::complete_craft(), Character::cough(), Character::deal_damage(), Creature::deal_damage_handle_type(), explosion_handler::do_blast(), melee_actor::do_grab(), Character::drench(), mattack::dsa_drone_scan(), eff_fun_datura(), eff_fun_fungus(), eff_fun_hallu(), eff_fun_spores(), map::emit_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_x_in_y_chance(), heal_actor::finish_using(), activity_handlers::fish_do_turn(), game::fling_creature(), suffer::from_radiation(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus(), mattack::fungus_corporate(), map::generate(), CellularAutomata::generate_cellular_automaton(), bodypart::get_limb_techs(), item::handle_craft_failure(), Character::handle_gun_damage(), Character::hardcoded_effects(), basecamp::hunting_results(), Character::impact(), suffer::in_sunlight(), monster::is_immune_effect(), effect::kill_roll(), make_gun_projectile(), monster::melee_attack(), Character::melee_attack_abstract(), Character::melee_special_effects(), monster::move(), monster::move_effects(), Character::mutate_towards(), Character::mutation_attacks(), om_harvest_itm(), om_harvest_ter(), melee_actor::on_damage(), bite_actor::on_damage(), Character::on_damage_of_type(), monster::on_load(), distribution::one_in(), Character::pause(), Character::perform_technique(), game::perhaps_add_random_npc(), iuse::petfood(), game::place_player(), vehicle::place_spawn_items(), overmap::place_specials(), monster::plan(), vehicle::power_parts(), monster::process_one_effect(), item::process_tool(), monster::process_triggers(), npc::process_turn(), process_vehicle_items(), activity_handlers::pulp_do_turn(), map::rad_scorch(), iuse::radio_tick(), Character::reach_attack(), inventory::remove_randomly_by_volume(), mattack::resurrect(), Character::rooted(), map::shoot(), game::slip_down(), map::smash_items(), spawn_spores(), fungal_effects::spread_fungus_one_tile(), map::spread_gas(), vehicle::start_engine(), Character::test_crossing_threshold(), PATH_INFO::title(), Character::try_remove_bear_trap(), Character::try_remove_downed(), Character::try_remove_grab(), Character::try_remove_heavysnare(), Character::try_remove_impeding_effect(), Character::try_remove_lightsnare(), Character::try_remove_webs(), scenario::weighted_random(), and scenario::weighted_random_profession().