Cataclysm DDA: src/calendar.cpp File Reference
calendar.cpp File Reference
#include "calendar.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <limits>
#include <optional>
#include <ostream>
#include <string>
#include <tuple>
#include "debug.h"
#include "display.h"
#include "line.h"
#include "options.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
#include "units.h"
#include "units_utility.h"
Namespaces
io
Functions
float default_daylight_level ()
How much light is provided in full daylight.
float max_sun_irradiance ()
time_duration lunar_month ()
Returns the default duration of a lunar month (duration between syzygies)
template<>
std::string io::enum_to_string< moon_phase > (moon_phase phase_num)
template<>
std::string io::enum_to_string< time_accuracy > (time_accuracy acc)
moon_phase get_moon_phase (const time_point &p)
Returns the current phase of the moon.
static constexpr time_duration angle_to_time (const units::angle &a)
static std::pair< units::angle, units::angle > sun_ra_declination (season_effective_time t, time_duration timezone)
static units::angle sidereal_time_at (season_effective_time t, units::angle longitude, time_duration timezone)
std::pair< units::angle, units::angle > sun_azimuth_altitude (time_point ti)
static units::angle sun_altitude (time_point t)
std::optional< rl_vec2d > sunlight_angle (const time_point &t)
Returns the offset by which a ray of sunlight would move when shifting down one z-level, or nullopt if the sun is below the horizon.
static time_point solar_noon_near (const time_point &t)
static units::angle offset_to_sun_altitude (const units::angle &altitude, const units::angle &longitude, const season_effective_time &approx_time, const bool evening)
static time_point sun_at_altitude (const units::angle &altitude, const units::angle &longitude, const time_point &t, const bool evening)
time_point sunrise (const time_point &p)
Returns the current sunrise time based on the time of year.
time_point sunset (const time_point &p)
Returns the current sunset time based on the time of year.
time_point night_time (const time_point &p)
Returns the time it gets dark based on sunset.
time_point daylight_time (const time_point &p)
Returns the time it gets light based on sunrise.
time_point noon (const time_point &p)
Returns the time when the clock displays 12:00.
bool is_night (const time_point &p)
Returns true if it's currently night time - after dusk and before dawn.
bool is_day (const time_point &p)
Returns true if it's currently day time - after dawn and before dusk.
static bool is_twilight (const time_point &p)
bool is_dusk (const time_point &p)
Returns true if it's currently dusk - between sunset and and twilight_duration after sunset.
bool is_dawn (const time_point &p)
Returns true if it's currently dawn - between sunrise and twilight_duration after sunrise.
static float moon_light_at (const time_point &p)
float sun_light_at (const time_point &p)
Returns the current sunlight.
float sun_irradiance (const time_point &p)
float sun_moon_light_at (const time_point &p)
Returns the current sunlight plus moonlight level.
float sun_moon_light_at_noon_near (const time_point &p)
How much light is provided at the solar noon nearest to given time.
static std::string to_string_clipped (const int num, const clipped_unit type, const clipped_align align)
std::pair< int, clipped_unit > clipped_time (const time_duration &d)
Returns a value representing the passed in duration truncated to an appropriate unit along with the unit in question.
std::string to_string_clipped (const time_duration &d, const clipped_align align)
Returns a string showing a duration as whole number of appropriate units, e.g.
std::string to_string (const time_duration &d, const bool compact)
Returns a string showing a duration.
std::string to_string_approx (const time_duration &dur, const bool verbose)
Returns approximate duration.
std::string to_string_writable (const time_duration &dur)
Returns a string that is writable to JSON that is also readable from JSON.
std::string to_string_time_of_day (const time_point &p)
weekdays day_of_week (const time_point &p)
time_duration rng (time_duration lo, time_duration hi)
bool x_in_y (const time_duration &a, const time_duration &b)
season_type season_of_year (const time_point &p)
std::string to_string (const time_point &p)
std::string get_diary_time_since_str (const time_duration &turn_diff, time_accuracy acc)
Time approximation based on the player's timekeeping capability, formatted for diary pages.
std::string get_diary_time_str (const time_point &turn, time_accuracy acc)
Time approximation based on the player's timekeeping capability, formatted for diary pages.
Variables
static constexpr float moonlight_per_quarter = 1.5f
How much light moon provides per lit-up quarter (Full-moon light is four times this value)
static bool is_eternal_season = false
static bool is_eternal_night = false
static bool is_eternal_day = false
static int cur_season_length = 1
static lat_long location = { 42.36_degrees, -71.06_degrees }
static constexpr units::angle astronomical_dawn = -18_degrees
static constexpr units::angle nautical_dawn = -12_degrees
static constexpr units::angle civil_dawn = -6_degrees
static constexpr units::angle sunrise_angle = -1_degrees
static constexpr int real_world_season_length = 91
static constexpr int default_season_length = real_world_season_length
Function Documentation
angle_to_time()
static constexpr time_duration angle_to_time (const units::angle & a) static constexpr
Definition at line 110 of file calendar.cpp.
 {
     return a / 15.0_degrees * 1_hours;
 }
References a.
Referenced by offset_to_sun_altitude(), sun_at_altitude(), and sun_azimuth_altitude().
clipped_time()
std::pair<int, clipped_unit> clipped_time (const time_duration & d)
Returns a value representing the passed in duration truncated to an appropriate unit along with the unit in question.
"10 days" or "1 minute". The chosen unit will be the smallest unit, that is at least as much as the given duration. E.g. an input of 60 minutes will return "1 hour", an input of 59 minutes will return "59 minutes".
Definition at line 503 of file calendar.cpp.
 {
     if( d >= calendar::INDEFINITELY_LONG_DURATION ) {
         return { 0, clipped_unit::forever };
     }
     if( d < 1_minutes ) {
         const int sec = to_seconds<int>( d );
         return { sec, clipped_unit::second };
     } else if( d < 1_hours ) {
         const int min = to_minutes<int>( d );
         return { min, clipped_unit::minute };
     } else if( d < 1_days ) {
         const int hour = to_hours<int>( d );
         return { hour, clipped_unit::hour };
     } else if( d < 7_days ) {
         const int day = to_days<int>( d );
         return { day, clipped_unit::day };
     } else if( d < calendar::season_length() || calendar::eternal_season() ) {
         // eternal seasons means one season is indistinguishable from the next,
         // therefore no way to count them
         const int week = to_weeks<int>( d );
         return { week, clipped_unit::week };
     } else if( d < calendar::year_length() && !calendar::eternal_season() ) {
         // TODO: consider a to_season function, but season length is variable, so
         // this might be misleading
         const int season = to_turns<int>( d ) / to_turns<int>( calendar::season_length() );
         return { season, clipped_unit::season };
     } else {
         // TODO: consider a to_year function, but year length is variable, so
         // this might be misleading
         const int year = to_turns<int>( d ) / to_turns<int>( calendar::year_length() );
         return { year, clipped_unit::year };
     }
 }
References day, calendar::eternal_season(), forever, hour, calendar::INDEFINITELY_LONG_DURATION, min(), minute, season, calendar::season_length(), second, week, year, and calendar::year_length().
Referenced by anonymous_namespace{item.cpp}::_stacks_rot(), and to_string_clipped().
day_of_week()
weekdays day_of_week (const time_point & p)
Definition at line 666 of file calendar.cpp.
 {
     /* Design rationale:
      * <kevingranade> here's a question
      * <kevingranade> what day of the week is day 0?
      * <wito> Sunday
      * <GlyphGryph> Why does it matter?
      * <GlyphGryph> For like where people are and stuff?
      * <wito> 7 is also Sunday
      * <kevingranade> NOAA weather forecasts include day of week
      * <GlyphGryph> Also by day0 do you mean the day people start day 0
      * <GlyphGryph> Or actual day 0
      * <kevingranade> good point, turn 0
      * <GlyphGryph> So day 5
      * <wito> Oh, I thought we were talking about week day numbering in general.
      * <wito> Day 5 is a thursday, I think.
      * <wito> Nah, Day 5 feels like a thursday. :P
      * <wito> Which would put the apocalypse on a saturday?
      * <Starfyre> must be a thursday.  I was never able to get the hang of those.
      * <ZChris13> wito: seems about right to me
      * <wito> kevingranade: add four for thursday. ;)
      * <kevingranade> sounds like consensus to me
      * <kevingranade> Thursday it is */
     const int day_since_cataclysm = to_days<int>( p - calendar::turn_zero );
     static const weekdays start_day = weekdays::THURSDAY;
     const int result = day_since_cataclysm + static_cast<int>( start_day );
     return static_cast<weekdays>( result % 7 );
 }
References THURSDAY, and calendar::turn_zero.
Referenced by weather_forecast().
daylight_time()
time_point daylight_time (const time_point & p)
Returns the time it gets light based on sunrise.
Definition at line 333 of file calendar.cpp.
 {
     return sun_at_altitude( civil_dawn, location.longitude, p, false );
 }
References civil_dawn, location, lat_long::longitude, and sun_at_altitude().
Referenced by anonymous_namespace{math_parser_diag.cpp}::time_until_eval(), and wait().
default_daylight_level()
float default_daylight_level ()
How much light is provided in full daylight.
Definition at line 47 of file calendar.cpp.
 {
     return 100.0f;
 }
Referenced by game::natural_light_level(), monster::process_triggers(), Creature::sees(), and monster::sight_range().
get_diary_time_since_str()
std::string get_diary_time_since_str (const time_duration & turn_diff, time_accuracy acc)
Time approximation based on the player's timekeeping capability, formatted for diary pages.
Definition at line 847 of file calendar.cpp.
 {
     const int days = to_days<int>( turn_diff );
     const int hours = to_hours<int>( turn_diff ) % 24;
     const int minutes = to_minutes<int>( turn_diff ) % 60;
     std::string days_text;
     std::string hours_text;
     std::string minutes_text;
     switch( acc ) {
         case time_accuracy::FULL:
             if( days > 0 ) {
                 days_text = string_format( n_gettext( "%d day, ", "%d days, ", days ), days );
             }
             if( hours > 0 ) {
                 hours_text = string_format( n_gettext( "%d hour, ", "%d hours, ", hours ), hours );
             }
             minutes_text = string_format( n_gettext( "%d minute", "%d minutes", minutes ), minutes );
             break;
         case time_accuracy::PARTIAL:
             if( days > 0 ) {
                 days_text = string_format( n_gettext( "%d day", "%d days", days ), days );
             } else if( hours > 0 ) {
                 //~ Estimate of how much time has passed since the last entry
                 days_text = _( "Less than a day" );
             } else {
                 //~ Estimate of how much time has passed since the last entry
                 days_text = _( "Not long" );
             }
             break;
         default:
             DebugLog( DebugLevel::D_WARNING, DebugClass::D_GAME )
                     << "Unknown time_accuracy " << io::enum_to_string<time_accuracy>( acc );
         /* fallthrough */
         case time_accuracy::NUM_TIME_ACCURACY:
         case time_accuracy::NONE:
             //~ Estimate of how much time has passed since the last entry
             days_text = days > 0 ? _( "A long while" ) : hours > 0 ? _( "A while" ) : _( "A short while" );
             break;
     }
     //~ %1$s is xx days, %2$s is xx hours, %3$s is xx minutes
     return string_format( _( "%1$s%2$s%3$s since last entry" ), days_text, hours_text, minutes_text );
 }
References _, D_GAME, D_WARNING, DebugLog(), io::enum_to_string< time_accuracy >(), FULL, n_gettext, NONE, NUM_TIME_ACCURACY, PARTIAL, and string_format().
Referenced by diary::get_head_text().
get_diary_time_str()
std::string get_diary_time_str (const time_point & turn, time_accuracy acc)
Time approximation based on the player's timekeeping capability, formatted for diary pages.
Definition at line 891 of file calendar.cpp.
 {
     const int year = to_turns<int>( turn - calendar::turn_zero ) /
                      to_turns<int>( calendar::year_length() ) + 1;
     const int day = day_of_season<int>( turn ) + 1;
     switch( acc ) {
         case time_accuracy::FULL:
             return to_string( turn );
         case time_accuracy::PARTIAL:
             // partial accuracy, able to see the sky
             //~ Time of year:
             //~ $1 = year since Cataclysm
             //~ $2 = season
             //~ $3 = day of season
             //~ $4 = approximate time of day
             return string_format( _( "Year %1$d, %2$s, day %3$d, %4$s" ), year,
                                   calendar::name_season( season_of_year( turn ) ),
                                   day, display::time_approx( turn ) );
         default:
             DebugLog( DebugLevel::D_WARNING, DebugClass::D_GAME )
                     << "Unknown time_accuracy " << io::enum_to_string<time_accuracy>( acc );
         /* fallthrough */
         case time_accuracy::NUM_TIME_ACCURACY:
         case time_accuracy::NONE: {
             // normalized to 100 day seasons
             const int day_norm = ( day * 100 ) / to_days<int>( calendar::season_length() );
             std::string seas_point;
             if( day_norm < 33 ) {
                 //~ Estimated point in the current season
                 seas_point = pgettext( "time of season", "Early" );
             } else if( day_norm < 66 ) {
                 //~ Estimated point in the current season
                 seas_point = pgettext( "time of season", "Mid" );
             } else {
                 //~ Estimated point in the current season
                 seas_point = pgettext( "time of season", "Late" );
             }
             //~ Estimated day-of-season string: $1 = Early/Mid/Late, $2 = Spring/Summer/Fall/Winter
             std::string season = string_format( _( "%1$s %2$s" ), seas_point,
                                                 calendar::name_season( season_of_year( turn ) ) );
             //~ Time of year: $1 = year since Cataclysm, $2 = season
             return string_format( _( "Year %1$d, %2$s" ), year, season );
         }
     }
     return std::string();
 }
References _, D_GAME, D_WARNING, day, DebugLog(), io::enum_to_string< time_accuracy >(), FULL, calendar::name_season(), NONE, NUM_TIME_ACCURACY, PARTIAL, pgettext, season, calendar::season_length(), season_of_year(), string_format(), display::time_approx(), to_string(), calendar::turn, calendar::turn_zero, year, and calendar::year_length().
Referenced by diary::get_head_text(), and diary::get_pages_list().
get_moon_phase()
moon_phase get_moon_phase (const time_point & p)
Returns the current phase of the moon.
Definition at line 98 of file calendar.cpp.
 {
     const time_duration moon_phase_duration = calendar::season_from_default_ratio() * lunar_month();
     // Switch moon phase at noon so it stays the same all night
     const int num_middays = to_days<int>( p - calendar::turn_zero + 1_days / 2 );
     const time_duration nearest_midnight = num_middays * 1_days;
     const double phase_change = nearest_midnight / moon_phase_duration;
     const int current_phase = static_cast<int>( std::round( phase_change * MOON_PHASE_MAX ) ) %
                               static_cast<int>( MOON_PHASE_MAX );
     return static_cast<moon_phase>( current_phase );
 }
References lunar_month(), MOON_PHASE_MAX, round(), calendar::season_from_default_ratio(), and calendar::turn_zero.
Referenced by moon_light_at(), anonymous_namespace{math_parser_diag.cpp}::moon_phase_eval(), and relic::try_recharge().
is_dawn()
bool is_dawn (const time_point & p)
Returns true if it's currently dawn - between sunrise and twilight_duration after sunrise.
Definition at line 367 of file calendar.cpp.
 {
     const time_duration now = time_past_midnight( p );
     return now < 12_hours && is_twilight( p );
 }
References is_twilight(), and time_past_midnight().
Referenced by photo_def_for_camera_point(), and display::time_approx().
is_day()
bool is_day (const time_point & p)
Returns true if it's currently day time - after dawn and before dusk.
Definition at line 350 of file calendar.cpp.
 {
     return sun_altitude( p ) >= sunrise_angle;
 }
References sun_altitude(), and sunrise_angle.
Referenced by can_recharge_solar().
is_dusk()
bool is_dusk (const time_point & p)
Returns true if it's currently dusk - between sunset and and twilight_duration after sunset.
Definition at line 361 of file calendar.cpp.
 {
     const time_duration now = time_past_midnight( p );
     return now > 12_hours && is_twilight( p );
 }
References is_twilight(), and time_past_midnight().
Referenced by photo_def_for_camera_point(), and display::time_approx().
is_night()
bool is_night (const time_point & p)
Returns true if it's currently night time - after dusk and before dawn.
Definition at line 345 of file calendar.cpp.
 {
     return sun_altitude( p ) <= civil_dawn;
 }
References civil_dawn, and sun_altitude().
Referenced by can_recharge_lunar(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_day(), photo_def_for_camera_point(), sounds::process_sound_markers(), display::time_approx(), and weather_forecast().
is_twilight()
static bool is_twilight (const time_point & p) static
Definition at line 355 of file calendar.cpp.
 {
     units::angle altitude = sun_altitude( p );
     return altitude >= civil_dawn && altitude <= sunrise_angle;
 }
References civil_dawn, sun_altitude(), and sunrise_angle.
Referenced by is_dawn(), and is_dusk().
lunar_month()
time_duration lunar_month ()
Returns the default duration of a lunar month (duration between syzygies)
Definition at line 57 of file calendar.cpp.
 {
     return 29.530588853 * 1_days;
 }
Referenced by get_moon_phase().
max_sun_irradiance()
float max_sun_irradiance ()
Definition at line 52 of file calendar.cpp.
 {
     return 1000.f;
 }
Referenced by sun_irradiance(), vehicle::total_solar_epower(), Character::update_bodytemp(), and vehicle::update_time().
moon_light_at()
static float moon_light_at (const time_point & p) static
Definition at line 373 of file calendar.cpp.
 {
     int current_phase = static_cast<int>( get_moon_phase( p ) );
     if( current_phase > static_cast<int>( MOON_PHASE_MAX ) / 2 ) {
         current_phase = static_cast<int>( MOON_PHASE_MAX ) - current_phase;
     }
     return 1. + moonlight_per_quarter * current_phase;
 }
References get_moon_phase(), MOON_PHASE_MAX, and moonlight_per_quarter.
Referenced by sun_moon_light_at().
night_time()
time_point night_time (const time_point & p)
Returns the time it gets dark based on sunset.
Definition at line 328 of file calendar.cpp.
 {
     return sun_at_altitude( civil_dawn, location.longitude, p, true );
 }
References civil_dawn, location, lat_long::longitude, and sun_at_altitude().
Referenced by anonymous_namespace{math_parser_diag.cpp}::time_until_eval(), and wait().
noon()
time_point noon (const time_point & p)
Returns the time when the clock displays 12:00.
Definition at line 338 of file calendar.cpp.
 {
     const time_duration time_of_day = ( p - calendar::turn_zero ) % 1_days;
     const time_duration till_noon = time_of_day - 12_hours;
     return ( till_noon > 0_seconds ) ? p - till_noon : p + till_noon;
 }
References calendar::turn_zero.
Referenced by anonymous_namespace{math_parser_diag.cpp}::time_since_eval(), and anonymous_namespace{math_parser_diag.cpp}::time_until_eval().
offset_to_sun_altitude()
static units::angle offset_to_sun_altitude (const units::angle & altitude, const units::angle & longitude, const season_effective_time & approx_time, const bool evening) static
Definition at line 269 of file calendar.cpp.
 {
     units::angle ra;
     units::angle declination;
     time_duration timezone = angle_to_time( longitude );
     std::tie( ra, declination ) = sun_ra_declination( approx_time, timezone );
     double cos_hour_angle =
         ( sin( altitude ) - sin( location.latitude ) * sin( declination ) ) /
         cos( location.latitude ) / cos( declination );
     if( std::abs( cos_hour_angle ) > 1 ) {
         // It doesn't actually reach that angle, so we pretend that it does at
         // its maximum possible angle
         cos_hour_angle = cos_hour_angle > 0 ? 1 : -1;
     }
     units::angle hour_angle = units::acos( cos_hour_angle );
     if( !evening ) {
         hour_angle = -hour_angle;
     }
     const units::angle target_sidereal_time = hour_angle + ra;
     const units::angle sidereal_time_at_approx_time =
         sidereal_time_at( approx_time, location.longitude, timezone );
     return normalize( target_sidereal_time - sidereal_time_at_approx_time );
 }
References abs(), units::acos(), angle_to_time(), cos(), lat_long::latitude, location, lat_long::longitude, normalize(), sidereal_time_at(), sin(), and sun_ra_declination().
Referenced by sun_at_altitude().
rng()
time_duration rng (time_duration lo, time_duration hi)
Definition at line 779 of file calendar.cpp.
 {
     return time_duration( rng( lo.turns_, hi.turns_ ) );
 }
Referenced by item::_resist(), outfit::absorb_damage(), Character::absorb_hit(), mattack::absorb_meat(), mattack::acid_accurate(), mattack::acid_barf(), mdefense::acidsplash(), npc::act_on_danger_assessment(), computer_session::action_extract_rad_source(), computer_session::action_irradiator(), computer_session::action_miss_launch(), computer_session::action_radio_archive(), Character::activate_mutation(), timed_event::actualize(), Character::add_addiction(), vehicle::alarm(), alcohol_diazepam_add(), amphetamine_effect(), iuse::antibiotic(), iuse::anticonvulsant(), iuse::antiparasitic(), spell::aoe(), jmapgen_gaspump::apply(), jmapgen_loot::apply(), apply_ammo_effects(), projectile::apply_effects_damage(), weakpoint_effect::apply_to(), npc::assess_danger(), mission::assign(), iexamine::autodoc(), vehicle::autopilot_patrol(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), iuse::blech(), blobify(), Character::blossoms(), trapfunc::board(), mattack::boomer_glow(), vehicle::break_off(), iuse::break_stick(), bucket_index_from_weight_list(), overmap::build_city_street(), overmap::build_lab(), VehicleSpawnFunction::builtin_parkinglot(), map::burn_body_part(), MapExtras::burned_ground_parser(), activity_handlers::butcher_finish(), butchery_drops_harvest(), leap_actor::call(), melee_actor::call(), trapfunc::caltrops(), trapfunc::caltrops_glass(), iuse::camera(), iuse::can_goo(), Character::can_sleep(), talk_function::caravan_return(), talk_function::carpenter_return(), spell::cast_all_effects(), game::catch_a_monster(), Character::check_avoid_friendly_fire(), basecamp::choose_new_leader(), outfit::clatter_sound(), cluster_sounds(), iuse::coke(), mission_type::create(), Single_item_creator::create(), Item_group::create(), Trait_group_collection::create(), Trait_group_distribution::create(), map::create_anomaly(), spell::create_field(), map::create_hot_air(), Item_group::create_single(), Single_item_creator::create_single_without_container(), trapfunc::crossbow(), map::crush(), map::cut_down_tree(), salvage_actor::cut_up(), spell::damage(), vehicle::damage_all(), damage_targets(), mattack::dance(), mattack::darkman(), iuse::datura(), Character::deal_damage(), Creature::deal_damage_handle_type(), monster::deal_damage_handle_type(), monster::deal_projectile_attack(), map::decay_cosmetic_fields(), item::detonate(), avatar::disarm(), map::displace_water(), explosion_handler::do_blast(), vehicle::do_engine_damage(), melee_actor::do_grab(), do_purify(), iuse_transform::do_transform(), data_handling_activity_actor::do_turn(), Character::dodge_roll(), construct::done_dig_grave(), construct::done_trunk_plank(), map::draw_lab(), map::draw_maptile(), draw_rough_circle(), map::draw_slimepit(), map::drop_furniture(), map::drop_items(), drop_or_embed_projectile(), mattack::dsa_drone_scan(), spell::duration(), dialogue::dynamic_line(), eat(), eff_fun_antifungal(), eff_fun_datura(), eff_fun_fake_common_cold(), eff_fun_fake_flu(), eff_fun_fungus(), eff_fun_hallu(), eff_fun_hypovolemia(), eff_fun_onfire(), eff_fun_rat(), eff_fun_redcells_anemia(), eff_fun_sleep(), eff_fun_teleglow(), iuse::ehandcuffs_tick(), iuse::einktabletpc(), explosion_handler::emp_blast(), dbl_or_var::evaluate(), duration_or_var::evaluate(), npc::evaluate_character(), npc::evaluate_self(), mattack::evolve_kill_strike(), Character::expose_to_disease(), iuse::extinguisher(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), conditional_fun::anonymous_namespace{condition.cpp}::f_roll_contested(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), computer_session::failure_amigara(), computer_session::failure_damage(), computer_session::failure_manhacks(), computer_session::failure_pump_leak(), farm_action(), talk_function::field_harvest(), field_processor_extra_radiation(), field_processor_fd_electricity(), field_processor_fd_shock_vent(), city::finalize(), game::find_nearby_spawn_point(), game::find_or_make_stairs(), find_potential_computer_point(), mission_start::find_safety(), hotwire_car_activity_actor::finish(), lockpick_activity_actor::finish(), reload_activity_actor::finish(), play_with_pet_activity_actor::finish(), chop_logs_activity_actor::finish(), chop_planks_activity_actor::finish(), forage_activity_actor::finish(), gunmod_add_activity_actor::finish(), iuse::firecracker_pack_act(), activity_handlers::fish_do_turn(), iuse::fish_trap_tick(), mattack::flesh_golem(), game::fling_creature(), talk_function::forage_return(), Character::forced_dismount(), mattack::formblob(), suffer::from_artifact_resonance(), suffer::from_asthma(), suffer::from_bad_bionics(), suffer::from_chemimbalance(), suffer::from_nyctophobia(), suffer::from_other_mutations(), suffer::from_radiation(), suffer::from_stimulants(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus_big_blossom(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_haze(), mattack::fungus_inject(), mattack::fungus_sprout(), iexamine::gaspump(), relic_charge_template::generate(), relic_procgen_data::generate(), map::generate(), mapgen_basic_container::generate(), lightson_game::generate_change_coords(), overmap::generate_sub(), jmapgen_int::get(), item_components::get_and_remove_random_entry(), field_effect::get_duration(), monster::get_horde_attraction(), effect::get_mod(), get_music_description(), game::get_player_input(), get_random_index(), Character::get_sick(), weather_generator::get_weather(), MonsterGroupManager::GetRandomMonsterFromGroup(), MonsterGroupManager::GetResultFromGroup(), talk_function::give_aid(), talk_function::give_all_aid(), talk_function::give_equipment_allowance(), trapfunc::glass(), trapfunc::glow(), npc::good_escape_direction(), iuse::granade_act(), iuse::grenade_inc_act(), mattack::grow_vine(), mattack::growplants(), computer_session::hack_attempt(), hackveh(), handbrake(), Character::handle_gun_damage(), Character::handle_gun_overheat(), start_location::handle_heli_crash(), npc::handle_sound(), vehicle::handle_trap(), Character::hardcoded_effects(), hardcoded_mutation_attack(), iexamine::harvest_plant(), monster::hasten_upgrade(), monster::hear_sound(), Character::heartrate_bpm(), Character::hitall(), talk_function::hospital_raid_return(), trapfunc::hum(), basecamp::hunting_results(), Character::impact(), monster::impact(), iuse::inhaler(), vehicle::init_state(), Character::initialize(), Character::install_bionics(), Character::irradiate(), is_summon_friendly(), item::item(), mission_start::kill_nemesis(), vehicle::leak_fuel(), mattack::leech_spawner(), talk_function::lesser_give_aid(), talk_function::lesser_give_all_aid(), monster::load(), mattack::lunge(), iuse::mace(), iuse::magic_8_ball(), magical_polymorph(), monster::make_friendly(), map::make_rubble(), mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), mapgen_river_curved(), mapgen_river_curved_not(), mapgen_river_straight(), mapgen_rock_partial(), marloss_common(), iuse::measure_resonance(), monster::melee_attack(), melee_message(), Character::melee_special_effects(), melee_train(), iuse::meth(), Character::mod_speed_bonus(), Item_modifier::modify(), monster::monster(), map::monster_in_field(), talk_function::morale_chat(), talk_function::morale_chat_activity(), avatar_action::move(), monster::move_effects(), overmap::move_hordes(), overmap::move_nemesis(), monster::move_to(), npc::move_to(), npc::mug_player(), iuse::multicooker(), multicooker_hallu(), Character::mutate(), spell_effect::mutate(), Character::mutate_towards(), MapExtras::mx_casings(), MapExtras::mx_city_trap(), MapExtras::mx_corpses(), MapExtras::mx_helicopter(), MapExtras::mx_looters(), MapExtras::mx_minefield(), MapExtras::mx_pond(), MapExtras::mx_portal_in(), MapExtras::mx_reed(), MapExtras::mx_roadworks(), iuse::mycus(), lightson_game::new_level(), minesweeper_game::new_level(), monster::next_upgrade_time(), nicotine_effect(), vehicle::noise_and_smoke(), monster::nursebot_operate(), om_cutdown_trees(), melee_actor::on_damage(), Character::on_damage_of_type(), Character::on_dodge(), Character::on_hit(), monster::on_hit(), vehicle::operate_planter(), vehicle::operate_reaper(), vehicle::operate_scoop(), iuse::pack_cbm(), parse_tags(), vehicle::part_collision(), iexamine::pedestal_wyrm(), timed_event::per_turn(), Character::perform_special_attacks(), Character::perform_technique(), game::perhaps_add_random_npc(), iuse::petfood(), mattack::photograph(), groundcover_extra::pick(), pick_plant(), activity_handlers::pickaxe_finish(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), overmap::place_cities(), Character::place_corpse(), mission_start::place_deposit_box(), map::place_items(), overmap::place_mongroups(), start_location::place_player(), game::place_player(), overmap::place_radios(), overmap::place_ravines(), overmap::place_river(), overmap::place_rivers(), vehicle::place_spawn_items(), map::place_spawns(), overmap::place_special(), overmap::place_special_attempt(), overmap::place_swamps(), game::place_vehicle_nearby(), map::place_vending(), monster::plan(), map::player_in_field(), read_activity_actor::player_readma(), vehicle::pldrive(), iuse::portable_game(), iuse::portal(), iexamine::practice_survival_while_foraging(), computer_session::print_gibberish_line(), Character::process_bionic(), item::process_corpse(), item::process_litcig(), Character::process_one_effect(), monster::process_one_effect(), sounds::process_sound_markers(), Character::process_turn(), monster::process_turn(), projectile_attack(), iuse::prozac(), mattack::pull_metal_weapon(), activity_handlers::pulp_do_turn(), monster::push_to(), iuse::radio_tick(), radio_tower::radio_tower(), rand(), rand_char(), item::rand_degradation(), om_direction::random(), option_slider::random_level(), random_neighbor(), random_point(), body_part_type::random_sub_part(), avatar::randomize(), npc::randomize(), avatar::randomize_hobbies(), mattack::ratking(), Character::react_to_felt_pain(), SkillLevel::readBook(), basecamp::recruit_return(), vehicle::remove_part(), monster::reset_special_rng(), explosion_handler::resonance_cascade(), reveal_destination(), mattack::riotbot(), distribution::rng_roll(), activity_handlers::robot_control_finish(), robot_finds_kitten::robot_finds_kitten(), rod_fish(), activity_byproduct::roll(), shearing_entry::roll(), talk_trial::roll(), roll_melee_damage_internal(), map::rotten_item_spawn(), iuse::rpgdie(), game::save_cyborg(), scatter_chunks(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), mattack::science(), science_room(), basecamp::search_results(), mattack::searchlight(), vehicle::selfdrive(), set_description(), set_hobbies(), npc::set_omt_destination(), set_profession(), set_scenario(), set_up_butchery(), trapfunc::shadow(), map::shake_vehicle(), mattack::shockstorm(), map::shoot(), npc::shop_restock(), trapfunc::shotgun(), mattack::shriek_stun(), iexamine::shrub_wildveggies(), overmap::signal_hordes(), item::simulate_burn(), sinkhole_safety_roll(), mattack::slimespring(), smash(), vehicle::smash_security_system(), trapfunc::snake(), npc::spawn_at_omt(), map::spawn_monsters_submap(), map::spawn_monsters_submap_group(), spell_effect::spawn_summoned_monster(), vehicle::spew_field(), mattack::spit_sap(), mdeath::splatter(), map::spread_gas(), monster::stability_roll(), harvest_activity_actor::start(), play_with_pet_activity_actor::start(), snake_game::start_game(), starting_inv(), str_to_illiterate_str(), mattack::stretch_attack(), iuse::strong_antibiotic(), survive_random_encounter(), Target_attributes::Target_attributes(), mattack::taze(), teleport::teleport(), teleport::teleport_to_point(), map::ter_set(), iuse::thorazine(), Character::throw_item(), Character::thrown_item_total_damage_raw(), vehicle::thrust(), vehicle::transform_terrain(), iexamine::tree_hickory(), mattack::triffid_heartbeat(), trap::triggered_by_sound(), trapfunc::tripwire(), avatar::try_break_relax_gas(), Character::try_remove_grab(), monster::try_reproduce(), om_direction::turn_random(), Character::uninstall_bionic(), weather_manager::update_weather(), spell_effect::upgrade(), explosion_iuse::use(), consume_drug_iuse::use(), place_monster_iuse::use(), fireweapon_off_actor::use(), sew_advanced_actor::use(), npc_attack_melee::use(), game::vertical_move(), Character::vomit(), mongroup::wander(), map::water_from(), iuse::weak_antibiotic(), weed_msg(), wet_character(), suffer::while_awake(), suffer::while_grabbed(), suffer::while_underwater(), suffer::without_sleep(), iuse::xanax(), and mdefense::zapback().
season_of_year()
season_type season_of_year (const time_point & p)
Returns
The season of the of the given time point. Returns the same season for any input if the calendar::eternal_season yields true.
Definition at line 810 of file calendar.cpp.
 {
     static time_point prev_turn = calendar::before_time_starts;
     static season_type prev_season = calendar::initial_season;
     if( p != prev_turn ) {
         prev_turn = p;
         if( calendar::eternal_season() ) {
             // If we use calendar::start to determine the initial season, and the user shortens the season length
             // mid-game, the result could be the wrong season!
             return prev_season = calendar::initial_season;
         }
         return prev_season = static_cast<season_type>(
                                  to_turn<int>( p ) / to_turns<int>( calendar::season_length() ) % 4
                              );
     }
     return prev_season;
 }
References calendar::before_time_starts, calendar::eternal_season(), calendar::initial_season, and calendar::season_length().
Referenced by sounds::add_footstep(), map_data_common_t::color(), display::date_string(), dead_plant(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_season(), forage_activity_actor::finish(), iexamine::flower_marloss(), talk_function::forage_return(), basecamp::gathering_return(), get_common_data(), get_diary_time_str(), map_data_common_t::get_harvest(), MonsterGroupManager::GetResultFromGroup(), glare(), monster::mating_angry(), monexamine::pet_menu(), map::restock_fruits(), calendar_ui::select_time_point(), sounds::sound(), map_data_common_t::symbol(), weather_generator::test_weather(), to_string(), and monster::try_reproduce().
sidereal_time_at()
static units::angle sidereal_time_at (season_effective_time t, units::angle longitude, time_duration timezone) static
Definition at line 170 of file calendar.cpp.
 {
     // Repeat some calculations from sun_ra_declination
     const double days_since_epoch = to_days<double>( t.t - calendar::turn_zero - timezone );
     const units::angle angle_per_day = 360_degrees / to_days<int>( calendar::year_length() );
     // Sidereal Time
     //
     // For the origin of sidereal time consider that at the epoch at Greenwich,
     // it's midnight on the vernal equinox so sidereal time should be 180.
     // Timezone and longitude are both zero here, so L0 = 180.
     const units::angle L0 = 180_degrees;
     // Sidereal time advances by 360 per day plus an additional 360 per year
     const units::angle L1 = 360_degrees + angle_per_day;
     return L0 + L1 * days_since_epoch + longitude;
 }
References season_effective_time::t, calendar::turn_zero, and calendar::year_length().
Referenced by offset_to_sun_altitude(), and sun_azimuth_altitude().
solar_noon_near()
static time_point solar_noon_near (const time_point & t) static
Definition at line 259 of file calendar.cpp.
 {
     const time_point prior_midnight = t - time_past_midnight( t );
     return prior_midnight + 12_hours;
     // If we were using a timezone rather than local solar time this would be
     // calculated as follows:
     //constexpr time_duration longitude_hours = angle_to_time( location_boston.longitude );
     //return prior_midnight + 12_hours - longitude_hours + timezone;
 }
References time_past_midnight().
Referenced by sun_at_altitude(), and sun_moon_light_at_noon_near().
sun_altitude()
static units::angle sun_altitude (time_point t) static
Definition at line 239 of file calendar.cpp.
 {
     return sun_azimuth_altitude( t ).second;
 }
References sun_azimuth_altitude().
Referenced by is_day(), is_night(), is_twilight(), sun_irradiance(), and sun_light_at().
sun_at_altitude()
static time_point sun_at_altitude (const units::angle & altitude, const units::angle & longitude, const time_point & t, const bool evening) static
Definition at line 295 of file calendar.cpp.
 {
     const time_point solar_noon = solar_noon_near( t );
     units::angle initial_offset =
         offset_to_sun_altitude( altitude, longitude, season_effective_time( solar_noon ), evening );
     if( !evening ) {
         initial_offset -= 360_degrees;
     }
     const time_duration initial_offset_time = angle_to_time( initial_offset );
     const time_point initial_approximation = solar_noon + initial_offset_time;
     // Now we should have the correct time to within a few minutes; iterate to
     // get a more precise estimate
     units::angle correction_offset =
         offset_to_sun_altitude( altitude, longitude, season_effective_time( initial_approximation ),
                                 evening );
     if( correction_offset > 180_degrees ) {
         correction_offset -= 360_degrees;
     }
     const time_duration correction_offset_time = angle_to_time( correction_offset );
     return initial_approximation + correction_offset_time;
 }
References angle_to_time(), offset_to_sun_altitude(), and solar_noon_near().
Referenced by daylight_time(), night_time(), sunrise(), and sunset().
sun_azimuth_altitude()
std::pair<units::angle, units::angle> sun_azimuth_altitude (time_point ti)
Definition at line 188 of file calendar.cpp.
 {
     const season_effective_time t = season_effective_time( ti );
     units::angle right_ascension;
     units::angle declination;
     time_duration timezone = angle_to_time( location.longitude );
     std::tie( right_ascension, declination ) = sun_ra_declination( t, timezone );
     const units::angle sidereal_time = sidereal_time_at( t, location.longitude, timezone );
     const units::angle hour_angle = sidereal_time - right_ascension;
     // Use a two-step transformation to convert equatorial coordinates to
     // horizontal.
     // https://en.wikipedia.org/wiki/Celestial_coordinate_system#Equatorial_%E2%86%94_horizontal
     const rl_vec3d intermediate(
         cos( hour_angle ) * cos( declination ),
         sin( hour_angle ) * cos( declination ),
         sin( declination ) );
     const rl_vec3d horizontal(
         -intermediate.x * sin( location.latitude ) +
         intermediate.z * cos( location.latitude ),
         intermediate.y,
         intermediate.x * cos( location.latitude ) +
         intermediate.z * sin( location.latitude )
     );
     // Azimuth is from the South, turning positive to the west
     const units::angle azimuth = normalize( -atan2( horizontal.xy() ) + 180_degrees );
     units::angle altitude = units::asin( horizontal.z );
     if( calendar::eternal_day() ) {
         altitude = 90_degrees;
     }
     if( calendar::eternal_night() ) {
         altitude = astronomical_dawn - 10_degrees;
     }
     /*printf(
         "\n"
         "right_ascension = %f, declination = %f\n"
         "sidereal_time = %f, hour_angle = %f\n"
         "aziumth = %f, altitude = %f\n",
         to_degrees( right_ascension ), to_degrees( declination ),
         to_degrees( sidereal_time ), to_degrees( hour_angle ),
         to_degrees( azimuth ), to_degrees( altitude ) );*/
     return std::make_pair( azimuth, altitude );
 }
References angle_to_time(), units::asin(), astronomical_dawn, atan2(), cos(), calendar::eternal_day(), calendar::eternal_night(), lat_long::latitude, location, lat_long::longitude, normalize(), sidereal_time_at(), sin(), sun_ra_declination(), rl_vec3d::x, rl_vec3d::xy(), rl_vec3d::y, and rl_vec3d::z.
Referenced by iuse::sextant(), sun_altitude(), display::sundial_text_color(), and sunlight_angle().
sun_irradiance()
float sun_irradiance (const time_point & p)
Definition at line 406 of file calendar.cpp.
 {
     const units::angle solar_alt = sun_altitude( p );
     if( solar_alt < 0_degrees ) {
         return 0;
     }
     return max_sun_irradiance() * sin( solar_alt );
 }
References max_sun_irradiance(), sin(), and sun_altitude().
Referenced by iuse::dbg_lux_meter(), and incident_sun_irradiance().
sun_light_at()
float sun_light_at (const time_point & p)
Returns the current sunlight.
Based entirely on astronomical circumstances; does not account for e.g. weather. For most situations you actually want to call the below function which also includes moonlight.
Definition at line 383 of file calendar.cpp.
 {
     const units::angle solar_alt = sun_altitude( p );
     if( solar_alt < astronomical_dawn ) {
         return 0;
     } else if( solar_alt <= nautical_dawn ) {
         // Sunlight rises exponentially from 0 to 3.7f as sun rises from -18 to -12
         return 3.7f * ( std::exp2( to_degrees( solar_alt - astronomical_dawn ) / 6.f ) - 1 );
     } else if( solar_alt <= civil_dawn ) {
         // Sunlight rises exponentially from 3.7f to 5.0f as sun rises from -12 to -6
         return ( 5.0f - 3.7f ) * ( std::exp2( to_degrees( solar_alt - nautical_dawn ) / 6.f ) - 1 ) + 3.7f;
     } else if( solar_alt <= sunrise_angle ) {
         // Sunlight rises exponentially from 5.0f to 60 as sun rises from -6 to -1
         return ( 60 - 5.0f ) * ( std::exp2( to_degrees( solar_alt - civil_dawn ) / 5.f ) - 1 ) + 5.0f;
     } else if( solar_alt <= 60_degrees ) {
         // Linear increase from -1 to 60 degrees light increases from 60 to 125 brightness.
         return ( 65.f / 61 ) * to_degrees( solar_alt ) + 65.f / 61  + 60;
     } else {
         return 125.f;
     }
 }
References astronomical_dawn, civil_dawn, nautical_dawn, sun_altitude(), sunrise_angle, and units::to_degrees().
Referenced by iuse::dbg_lux_meter(), incident_sunlight(), sun_moon_light_at(), and display::sundial_text_color().
sun_moon_light_at()
float sun_moon_light_at (const time_point & p)
Returns the current sunlight plus moonlight level.
Based entirely on astronomical circumstances; does not account for e.g. weather.
Definition at line 416 of file calendar.cpp.
 {
     return sun_light_at( p ) + moon_light_at( p );
 }
References moon_light_at(), and sun_light_at().
Referenced by game::natural_light_level(), and sun_moon_light_at_noon_near().
sun_moon_light_at_noon_near()
float sun_moon_light_at_noon_near (const time_point & p)
How much light is provided at the solar noon nearest to given time.
Definition at line 421 of file calendar.cpp.
 {
     const time_point solar_noon = solar_noon_near( p );
     return sun_moon_light_at( solar_noon );
 }
References solar_noon_near(), and sun_moon_light_at().
Referenced by editmap::update_view_with_help().
sun_ra_declination()
static std::pair<units::angle, units::angle> sun_ra_declination (season_effective_time t, time_duration timezone) static
Definition at line 125 of file calendar.cpp.
 {
     // This derivation is mostly from
     // https://en.wikipedia.org/wiki/Position_of_the_Sun
     // https://en.wikipedia.org/wiki/Celestial_coordinate_system#Notes_on_conversion
     // The computation is inspired by the derivation based on J2000 (Greenwich
     // noon, 2000-01-01), but because we want to be capable of handling a
     // different year length than the real Earth, we don't use the same exact
     // values.
     // Instead we use as our epoch a point that won't change arbitrarily with a
     // different year length - Greenwich midnight on the vernal equinox
     // (note that the vernal equinox happens to be Spring day 1 in the game
     // calendar, which is convenient).
     const double days_since_epoch = to_days<double>( t.t - calendar::turn_zero - timezone );
     // The angle per day the Earth moves around the Sun
     const units::angle angle_per_day = 360_degrees / to_days<int>( calendar::year_length() );
     // It turns out that we want mean longitude to be zero at the vernal
     // equinox, which simplifies the calculations.
     const units::angle mean_long = angle_per_day * days_since_epoch;
     // Roughly 77 degrees offset between mean longitude and mean anomaly at
     // J2000, so use that as our offset too.  The relative drift is slow, so we
     // neglect it.
     const units::angle mean_anomaly = 77_degrees + mean_long;
     // The two arbitrary constants in the calculation of ecliptic longitude
     // relate to the non-circularity of the Earth's orbit.
     const units::angle ecliptic_longitude =
         mean_long + 1.915_degrees * sin( mean_anomaly ) + 0.020_degrees * sin( 2 * mean_anomaly );
     // Obliquity does vary slightly, but for simplicity we'll keep it fixed at
     // its J2000 value.
     static constexpr units::angle obliquity = 23.439279_degrees;
     // ecliptic rectangular coordinates
     const rl_vec2d eclip( cos( ecliptic_longitude ), sin( ecliptic_longitude ) );
     // rotate to equatorial coordinates
     const rl_vec3d rot( eclip.x, eclip.y * cos( obliquity ), eclip.y * sin( obliquity ) );
     const units::angle right_ascension = atan2( rot.xy() );
     const units::angle declination = units::asin( rot.z );
     return { right_ascension, declination };
 }
References units::asin(), atan2(), cos(), sin(), season_effective_time::t, calendar::turn_zero, rl_vec2d::x, rl_vec3d::xy(), rl_vec2d::y, calendar::year_length(), and rl_vec3d::z.
Referenced by offset_to_sun_altitude(), and sun_azimuth_altitude().
sunlight_angle()
std::optional<rl_vec2d> sunlight_angle (const time_point & t)
Returns the offset by which a ray of sunlight would move when shifting down one z-level, or nullopt if the sun is below the horizon.
Definition at line 244 of file calendar.cpp.
 {
     units::angle azimuth;
     units::angle altitude;
     std::tie( azimuth, altitude ) = sun_azimuth_altitude( t );
     if( altitude <= sunrise_angle ) {
         // Sun below horizon
         return std::nullopt;
     }
     rl_vec2d horizontal_direction( -sin( azimuth ), cos( azimuth ) );
     rl_vec3d direction( horizontal_direction * cos( altitude ), sin( altitude ) );
     direction /= -direction.z;
     return direction.xy();
 }
References cos(), sin(), sun_azimuth_altitude(), and sunrise_angle.
sunrise()
time_point sunrise (const time_point & p)
Returns the current sunrise time based on the time of year.
Definition at line 318 of file calendar.cpp.
 {
     return sun_at_altitude( sunrise_angle, location.longitude, p, false );
 }
References location, lat_long::longitude, sun_at_altitude(), and sunrise_angle.
Referenced by MonsterGroupManager::GetResultFromGroup(), is_spawn_valid(), and anonymous_namespace{math_parser_diag.cpp}::time_until_eval().
sunset()
time_point sunset (const time_point & p)
Returns the current sunset time based on the time of year.
Definition at line 323 of file calendar.cpp.
 {
     return sun_at_altitude( sunrise_angle, location.longitude, p, true );
 }
References location, lat_long::longitude, sun_at_altitude(), and sunrise_angle.
Referenced by MonsterGroupManager::GetResultFromGroup(), is_spawn_valid(), display::sundial_text_color(), and anonymous_namespace{math_parser_diag.cpp}::time_until_eval().
to_string() [1/2]
std::string to_string (const time_duration & d, bool compact = false)
Returns a string showing a duration.
The string contains at most two numbers along with their units. E.g. 3661 seconds will return "1 hour and 1 minute" (the 1 additional second is clipped). An input of 3601 will return "1 hour" (the second is clipped again and the number of additional minutes would be 0 so it's skipped).
Parameters
compact True for compact display of time. Example: 1 min 15 secs
Definition at line 546 of file calendar.cpp.
 {
     if( d >= calendar::INDEFINITELY_LONG_DURATION ) {
         return _( "forever" );
     }
     if( d <= 1_minutes ) {
         return to_string_clipped( d );
     }
     time_duration divider = 0_turns;
     if( d < 1_hours ) {
         divider = 1_minutes;
     } else if( d < 1_days ) {
         divider = 1_hours;
     } else if( d < 1_weeks ) {
         divider = 1_days;
     } else if( d < calendar::season_length() || calendar::eternal_season() ) {
         divider = 1_weeks;
     } else if( d < calendar::year_length() ) {
         divider = calendar::season_length();
     } else {
         divider = calendar::year_length();
     }
     if( d % divider != 0_turns ) {
         if( compact ) {
             //~ %1$s - greater units of time (e.g. 3 hours), %2$s - lesser units of time (e.g. 11 minutes).
             return string_format( pgettext( "time duration", "%1$s %2$s" ),
                                   to_string_clipped( d, clipped_align::compact ),
                                   to_string_clipped( d % divider, clipped_align::compact ) );
         } else {
             //~ %1$s - greater units of time (e.g. 3 hours), %2$s - lesser units of time (e.g. 11 minutes).
             return string_format( _( "%1$s and %2$s" ),
                                   to_string_clipped( d ),
                                   to_string_clipped( d % divider ) );
         }
     }
     return to_string_clipped( d );
 }
References _, compact, calendar::eternal_season(), calendar::INDEFINITELY_LONG_DURATION, pgettext, calendar::season_length(), string_format(), to_string_clipped(), and calendar::year_length().
Referenced by abstract_read_var_info(), target_ui::action_switch_mode(), assemble_scenario_details(), iexamine::autoclave_full(), iexamine::autodoc(), eoc_examine_actor::call(), camp_trip_description(), cata_variant::cata_variant(), small_literal_vector< T, kInlineCount, SizeT >::check_capacity(), basecamp::choose_new_leader(), color_number(), comestible_inventory_preset::comestible_inventory_preset(), talk_function::commune_carpentry(), talk_function::commune_forage(), talk_function::commune_menial(), talk_function::commune_refuge_caravan(), item_pocket::contents_info(), cata::convert(), basecamp::craft_description(), debug_menu::debug(), debug_menu::debug_menu_force_temperature(), map::decay_fields_and_scent(), item::disassembly_info(), effect::disp_desc(), units::display(), draw_bionics_titlebar(), prof_window::draw_details(), draw_proficiencies_info(), mission_ui_impl::draw_selected_description(), game_menus::inv::ebooksave(), edit_integer(), editmap::edit_itm(), spell::energy_cost_string(), spell::energy_cur_string(), enumerate_ints_to_string(), jmath_func::eval(), monster::extended_description(), npc::faction_display(), base_camps::faction_encode_abs(), basecamp::farm_description(), item::food_info(), iuse::foodperson(), map::generate(), debug_menu::generate_effect_list(), generic_multi_activity_check_requirement(), basecamp::get_available_missions_by_dir(), get_diary_time_str(), basecamp::get_equipment(), vehicle::get_folded_item(), TextJsonIn::get_int(), TextJsonIn::get_int64(), cata::string_formatter::get_nth_arg_as(), bionic_install_preset::get_operation_duration(), bionic_install_surgeon_preset::get_operation_duration(), npc::get_restock_interval(), construction::get_time_string(), TextJsonIn::get_uint(), get_unique_group_id(), get_unique_trait_group_id(), inventory_selector::get_weight_and_length_stat(), basecamp::give_equipment(), Character::heat_emission(), talk_function::hospital_raid(), basecamp::job_assignment_ui(), mutation_branch::load(), bionic_data::load(), item::make_corpse(), base_camps::max_upgrade_by_type(), item::med_info(), iuse::mininuke(), ml_to_string(), Character::mod_stamina(), moves_to_string(), basecamp::om_upgrade_description(), damage_type::ondamage_effects(), JsonArray::operator[](), cata::string_formatter::parse(), monexamine::pay_bot(), iexamine::pay_gas(), photo_def_for_camera_point(), display::power_balance_text_color(), display::power_text_color(), debug_menu::prepare_export_dir_and_find_unused_name(), print_damage_info(), anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount(), prompt_for_amount(), iexamine::quern_examine(), Character::queue_effect(), iuse::radiocontrol(), read_inventory_preset::read_inventory_preset(), recipe_info(), teleporter_callback::refresh(), reload_furniture(), game::save_achievements(), flexbuffer_disk_cache::save_to_disk(), talk_function::scavenger_patrol(), talk_function::scavenger_raid(), calendar_ui::select_time_point(), set_description(), safemode::show(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), basecamp::start_salt_water_pipe(), iexamine::stook_full(), Character::store(), text_style_check(), cata_variant_detail::convert< cata_variant_type::bool_ >::to_string(), cata_variant_detail::convert< cata_variant_type::character_id >::to_string(), cata_variant_detail::convert< cata_variant_type::int_ >::to_string(), cata_variant_detail::convert< cata_variant_type::chrono_seconds >::to_string(), tileray::to_string_azimuth_from_north(), achievement::time_bound::ui_text(), achievement_state::ui_text(), overmap::unserialize_omap(), update_emergency_recall(), options_manager::update_options_cache(), update_time_fixed(), update_time_left(), vol_to_string(), wait(), iuse::wash_items(), weight_to_string(), debug_menu::wind_speed(), cataimgui::window::window(), debug_menu::wisheffect(), and memorial_logger::write_text_memorial().
to_string() [2/2]
std::string to_string (const time_point & p)
Returns
The time point formatted to be shown to the player. Contains year, season, day and time of day.
Definition at line 830 of file calendar.cpp.
 {
     const int year = to_turns<int>( p - calendar::turn_zero ) / to_turns<int>
                      ( calendar::year_length() ) + 1;
     const std::string time = to_string_time_of_day( p );
     if( calendar::eternal_season() ) {
         const int day = to_days<int>( time_past_new_year( p ) );
         //~ 1 is the year, 2 is the day (of the *year*), 3 is the time of the day in its usual format
         return string_format( _( "Year %1$d, day %2$d %3$s" ), year, day, time );
     } else {
         const int day = day_of_season<int>( p ) + 1;
         //~ 1 is the year, 2 is the season name, 3 is the day (of the season), 4 is the time of the day in its usual format
         return string_format( _( "Year %1$d, %2$s, day %3$d %4$s" ), year,
                               calendar::name_season( season_of_year( p ) ), day, time );
     }
 }
References _, day, calendar::eternal_season(), calendar::name_season(), season_of_year(), string_format(), time_past_new_year(), to_string_time_of_day(), calendar::turn_zero, year, and calendar::year_length().
to_string_approx()
std::string to_string_approx (const time_duration & dur, bool verbose = true)
Returns approximate duration.
Parameters
verbose If true, 'less than' and 'more than' will be printed instead of '<' and '>' respectively.
Definition at line 587 of file calendar.cpp.
 {
     time_duration d = dur;
     const auto make_result = [verbose]( const time_duration & d, const char *verbose_str,
     const char *short_str ) {
         return string_format( verbose ? verbose_str : short_str, to_string_clipped( d ) );
     };
     time_duration divider = 0_turns;
     time_duration vicinity = 0_turns;
     // Minutes and seconds can be estimated precisely.
     if( d > 1_days ) {
         divider = 1_days;
         vicinity = 2_hours;
     } else if( d > 1_hours ) {
         divider = 1_hours;
         vicinity = 5_minutes;
     }
     if( divider != 0_turns ) {
         const time_duration remainder = d % divider;
         if( remainder >= divider - vicinity ) {
             d += divider;
         } else if( remainder > vicinity ) {
             if( remainder < divider / 2 ) {
                 //~ %s - time (e.g. 2 hours).
                 return make_result( d, _( "more than %s" ), ">%s" );
             } else {
                 //~ %s - time (e.g. 2 hours).
                 return make_result( d + divider, _( "less than %s" ), "<%s" );
             }
         }
     }
     //~ %s - time (e.g. 2 hours).
     return make_result( d, _( "about %s" ), "%s" );
 }
References _, dur, make_result(), string_format(), and to_string_clipped().
Referenced by item::disassembly_info(), mission_ui_impl::draw_selected_description(), dialogue::dynamic_line(), talker_npc::evaluation_by(), veh_interact::format_reqs(), get_fire_fuel_string(), get_freshness_description(), comestible_inventory_preset::get_time_left_rounded(), Character::mend_item(), and read_inventory_preset::read_inventory_preset().
to_string_clipped() [1/2]
static std::string to_string_clipped (const int num, const clipped_unit type, const clipped_align align) static
Definition at line 427 of file calendar.cpp.
 {
     switch( align ) {
         default:
         case clipped_align::none:
             switch( type ) {
                 default:
                 case clipped_unit::forever:
                     return _( "forever" );
                 case clipped_unit::second:
                     return string_format( n_gettext( "%d second", "%d seconds", num ), num );
                 case clipped_unit::minute:
                     return string_format( n_gettext( "%d minute", "%d minutes", num ), num );
                 case clipped_unit::hour:
                     return string_format( n_gettext( "%d hour", "%d hours", num ), num );
                 case clipped_unit::day:
                     return string_format( n_gettext( "%d day", "%d days", num ), num );
                 case clipped_unit::week:
                     return string_format( n_gettext( "%d week", "%d weeks", num ), num );
                 case clipped_unit::season:
                     return string_format( n_gettext( "%d season", "%d seasons", num ), num );
                 case clipped_unit::year:
                     return string_format( n_gettext( "%d year", "%d years", num ), num );
             }
         case clipped_align::right:
             switch( type ) {
                 default:
                 case clipped_unit::forever:
                     //~ Right-aligned time string. should right-align with other strings with this same comment
                     return _( "    forever" );
                 case clipped_unit::second:
                     //~ Right-aligned time string. should right-align with other strings with this same comment
                     return string_format( n_gettext( "%3d  second", "%3d seconds", num ), num );
                 case clipped_unit::minute:
                     //~ Right-aligned time string. should right-align with other strings with this same comment
                     return string_format( n_gettext( "%3d  minute", "%3d minutes", num ), num );
                 case clipped_unit::hour:
                     //~ Right-aligned time string. should right-align with other strings with this same comment
                     return string_format( n_gettext( "%3d    hour", "%3d   hours", num ), num );
                 case clipped_unit::day:
                     //~ Right-aligned time string. should right-align with other strings with this same comment
                     return string_format( n_gettext( "%3d     day", "%3d    days", num ), num );
                 case clipped_unit::week:
                     //~ Right-aligned time string. should right-align with other strings with this same comment
                     return string_format( n_gettext( "%3d    week", "%3d   weeks", num ), num );
                 case clipped_unit::season:
                     //~ Right-aligned time string. should right-align with other strings with this same comment
                     return string_format( n_gettext( "%3d  season", "%3d seasons", num ), num );
                 case clipped_unit::year:
                     //~ Right-aligned time string. should right-align with other strings with this same comment
                     return string_format( n_gettext( "%3d    year", "%3d   years", num ), num );
             }
         case clipped_align::compact:
             switch( type ) {
                 default:
                 case clipped_unit::forever:
                     return _( "forever" );
                 case clipped_unit::second:
                     return string_format( n_gettext( "%d sec", "%d secs", num ), num );
                 case clipped_unit::minute:
                     return string_format( n_gettext( "%d min", "%d mins", num ), num );
                 case clipped_unit::hour:
                     return string_format( n_gettext( "%d hr", "%d hrs", num ), num );
                 case clipped_unit::day:
                     return string_format( n_gettext( "%d day", "%d days", num ), num );
                 case clipped_unit::week:
                     return string_format( n_gettext( "%d wk", "%d wks", num ), num );
                 case clipped_unit::season:
                     return string_format( n_gettext( "%d seas", "%d seas", num ), num );
                 case clipped_unit::year:
                     return string_format( n_gettext( "%d yr", "%d yrs", num ), num );
             }
     }
 }
References _, compact, day, forever, hour, minute, n_gettext, none, right, season, second, string_format(), week, and year.
Referenced by add_disassemblables(), add_salvagables(), game::butcher(), butcher_submenu(), disassemble_inventory_preset::disassemble_inventory_preset(), effect::disp_desc(), item::final_info(), avatar::identify(), Messages::dialog::init(), avatar::power_mutations(), vehicle::print_fuel_indicator(), iexamine::quern_examine(), item::rot_info(), salvage_inventory_preset::salvage_inventory_preset(), Messages::dialog::show(), to_string(), to_string_approx(), and to_string_clipped().
to_string_clipped() [2/2]
std::string to_string_clipped (const time_duration & d, clipped_align align = clipped_align::none)
Returns a string showing a duration as whole number of appropriate units, e.g.
"10 days" or "1 minute". The chosen unit will be the smallest unit, that is at least as much as the given duration. E.g. an input of 60 minutes will return "1 hour", an input of 59 minutes will return "59 minutes".
Parameters
align none, right, or compact.
Definition at line 539 of file calendar.cpp.
 {
     const std::pair<int, clipped_unit> time = clipped_time( d );
     return to_string_clipped( time.first, time.second, align );
 }
References clipped_time(), and to_string_clipped().
to_string_time_of_day()
std::string to_string_time_of_day (const time_point & p)
Returns
The time point formatted to be shown to the player. Contains only the time of day, not the year, day or season.
Definition at line 639 of file calendar.cpp.
 {
     const int hour = hour_of_day<int>( p );
     const int minute = minute_of_hour<int>( p );
     const int second = to_seconds<int>( time_past_midnight( p ) ) % 60;
     const std::string format_type = get_option<std::string>( "24_HOUR" );
     if( format_type == "military" ) {
         return string_format( "%02d%02d.%02d", hour, minute, second );
     } else if( format_type == "24h" ) {
         //~ hour:minute (24hr time display)
         return string_format( _( "%02d:%02d:%02d" ), hour, minute, second );
     } else {
         int hour_param = hour % 12;
         if( hour_param == 0 ) {
             hour_param = 12;
         }
         // Padding is removed as necessary to prevent clipping with SAFE notification in wide sidebar mode
         const std::string padding = hour_param < 10 ? " " : "";
         if( hour < 12 ) {
             return string_format( _( "%d:%02d:%02d%sAM" ), hour_param, minute, second, padding );
         } else {
             return string_format( _( "%d:%02d:%02d%sPM" ), hour_param, minute, second, padding );
         }
     }
 }
References _, hour, minute, second, string_format(), and time_past_midnight().
Referenced by anonymous_namespace{messages.cpp}::messages_impl::recent_messages(), advanced_inventory::redraw_sidebar(), display::sundial_time_text_color(), display::time_string(), to_string(), wait(), and weather_forecast().
to_string_writable()
std::string to_string_writable (const time_duration & dur)
Returns a string that is writable to JSON that is also readable from JSON.
Definition at line 626 of file calendar.cpp.
 {
     if( dur % 1_days == 0_seconds ) {
         return string_format( "%d d", static_cast<int>( dur / 1_days ) );
     } else if( dur % 1_hours == 0_seconds ) {
         return string_format( "%d h", static_cast<int>( dur / 1_hours ) );
     } else if( dur % 1_minutes == 0_seconds ) {
         return string_format( "%d m", static_cast<int>( dur / 1_minutes ) );
     } else {
         return string_format( "%d s", static_cast<int>( dur / 1_seconds ) );
     }
 }
References dur, and string_format().
Referenced by Character::check_outbounds_activity(), read_activity_actor::do_turn(), safecracking_activity_actor::do_turn(), read_activity_actor::finish(), avatar::read(), enchant_cache::serialize(), effect::set_duration(), harvest_activity_actor::start(), lockpick_activity_actor::start(), ebooksave_activity_actor::start(), read_activity_actor::start(), safecracking_activity_actor::start(), and shearing_activity_actor::start().
x_in_y()
bool x_in_y (const time_duration & a, const time_duration & b)
See also
x_in_y(int,int)
Definition at line 784 of file calendar.cpp.
 {
     return ::x_in_y( to_turns<int>( a ), to_turns<int>( b ) );
 }
References a, and b.
Referenced by effect::activated(), overmap::add_mon_group(), alcohol_diazepam_add(), amphetamine_effect(), monster::anger_hostile_seen(), monster::anger_mating_season(), jmapgen_monster::apply(), jmapgen_vehicle::apply(), jmapgen_sealed_item::apply(), apply_ammo_effects(), projectile::apply_effects_damage(), iuse::bell(), Character::block_hit(), leap_actor::call(), melee_actor::call(), Character::can_escape_trap(), iuse::can_goo(), check_butcher_dissect(), Character::check_mount_is_spooked(), Character::complete_craft(), Character::cough(), Character::deal_damage(), Creature::deal_damage_handle_type(), explosion_handler::do_blast(), melee_actor::do_grab(), Character::drench(), mattack::dsa_drone_scan(), eff_fun_datura(), eff_fun_fungus(), eff_fun_hallu(), eff_fun_spores(), map::emit_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_x_in_y_chance(), heal_actor::finish_using(), activity_handlers::fish_do_turn(), game::fling_creature(), suffer::from_radiation(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus(), mattack::fungus_corporate(), map::generate(), CellularAutomata::generate_cellular_automaton(), bodypart::get_limb_techs(), item::handle_craft_failure(), Character::handle_gun_damage(), Character::hardcoded_effects(), basecamp::hunting_results(), Character::impact(), suffer::in_sunlight(), monster::is_immune_effect(), effect::kill_roll(), make_gun_projectile(), monster::melee_attack(), Character::melee_attack_abstract(), Character::melee_special_effects(), monster::move(), monster::move_effects(), Character::mutate_towards(), Character::mutation_attacks(), om_harvest_itm(), om_harvest_ter(), melee_actor::on_damage(), bite_actor::on_damage(), Character::on_damage_of_type(), monster::on_load(), distribution::one_in(), Character::pause(), Character::perform_technique(), game::perhaps_add_random_npc(), iuse::petfood(), game::place_player(), vehicle::place_spawn_items(), overmap::place_specials(), monster::plan(), vehicle::power_parts(), monster::process_one_effect(), item::process_tool(), monster::process_triggers(), npc::process_turn(), process_vehicle_items(), activity_handlers::pulp_do_turn(), map::rad_scorch(), iuse::radio_tick(), Character::reach_attack(), inventory::remove_randomly_by_volume(), mattack::resurrect(), Character::rooted(), map::shoot(), game::slip_down(), map::smash_items(), spawn_spores(), fungal_effects::spread_fungus_one_tile(), map::spread_gas(), vehicle::start_engine(), Character::test_crossing_threshold(), PATH_INFO::title(), Character::try_remove_bear_trap(), Character::try_remove_downed(), Character::try_remove_grab(), Character::try_remove_heavysnare(), Character::try_remove_impeding_effect(), Character::try_remove_lightsnare(), Character::try_remove_webs(), scenario::weighted_random(), and scenario::weighted_random_profession().
Variable Documentation
astronomical_dawn
constexpr units::angle astronomical_dawn = -18_degrees static constexpr
Definition at line 42 of file calendar.cpp.
Referenced by sun_azimuth_altitude(), and sun_light_at().
civil_dawn
constexpr units::angle civil_dawn = -6_degrees static constexpr
Definition at line 44 of file calendar.cpp.
Referenced by daylight_time(), is_night(), is_twilight(), night_time(), and sun_light_at().
cur_season_length
int cur_season_length = 1 static
Definition at line 33 of file calendar.cpp.
Referenced by calendar::season_length(), and calendar::set_season_length().
default_season_length
constexpr int default_season_length = real_world_season_length static constexpr
Definition at line 741 of file calendar.cpp.
Referenced by calendar::season_from_default_ratio().
is_eternal_day
bool is_eternal_day = false static
Definition at line 32 of file calendar.cpp.
Referenced by calendar::eternal_day(), and calendar::set_eternal_day().
is_eternal_night
bool is_eternal_night = false static
Definition at line 31 of file calendar.cpp.
Referenced by calendar::eternal_night(), and calendar::set_eternal_night().
is_eternal_season
bool is_eternal_season = false static
Definition at line 30 of file calendar.cpp.
Referenced by calendar::eternal_season(), and calendar::set_eternal_season().
location
lat_long location = { 42.36_degrees, -71.06_degrees } static
Definition at line 34 of file calendar.cpp.
Referenced by active_item_cache::add(), vehicle::all_parts_at_location(), autodoc_internal(), overmap_connection::check(), overmap::check_overmap_special_type(), game_menus::inv::common(), current_weather(), daylight_time(), advanced_inventory::display(), disassemble_activity_actor::do_turn(), craft_activity_actor::do_turn(), game_menus::inv::ebookread(), npc_attack_spell::evaluate_tripoint(), npc_attack_gun::evaluate_tripoint(), npc_attack_throw::evaluate_tripoint(), conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location(), conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::fill_skipblock(), get_autopickup_items(), get_best_fire(), overmapbuffer::get_camps_near(), overmapbuffer::get_cities_near(), get_common_data(), get_convection_temperature(), item::get_free_mod_locations(), get_heat_radiation(), get_local_windpower(), overmapbuffer::get_overmaps_near(), inventory_entry::get_selected_charges(), weather_manager::get_temperature(), inventory_entry::get_total_charges(), weather_generator::get_weather(), weather_generator::get_weather_conditions(), weather_generator::get_weather_temperature(), game_menus::inv::gunmod_to_remove(), inventory_selector::highlight(), map::i_rem(), inv_internal(), overmapbuffer::is_findable_location(), liquid_inventory_selector_preset::is_shown(), smokable_selector_preset::is_shown(), inventory_filter_preset::is_shown(), is_wind_blocker(), Creature::load(), advanced_inventory_pane::load_settings(), game_menus::inv::multidrop(), MapExtras::mx_casings(), MapExtras::mx_clay_deposit(), MapExtras::mx_grove(), MapExtras::mx_pond(), MapExtras::mx_shrubbery(), jmapgen_nested::neighbor_flag_any_check::neighbor_flag_any_check(), jmapgen_nested::neighbor_flag_check::neighbor_flag_check(), jmapgen_nested::neighbor_oter_check::neighbor_oter_check(), night_time(), offset_to_sun_altitude(), fixed_overmap_special_data::place(), overmap::place_special(), Creature::pos(), process_map_items(), cata::list< element_type, element_allocator_type >::reorder(), mattack::resurrect(), auto_pickup::select_items(), calendar::set_location(), sounds::sound_at(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), Creature::store(), sum_conditions(), sun_azimuth_altitude(), sunrise(), sunset(), ter_furn_transform::transform(), spell_effect::transform_blast(), editmap::uber_draw_ter(), game_menus::inv::unload(), npc_attack_spell::use(), npc_attack_melee::use(), npc_attack_gun::use(), npc_attack_throw::use(), and iuse::wash_items().
moonlight_per_quarter
constexpr float moonlight_per_quarter = 1.5f static constexpr
How much light moon provides per lit-up quarter (Full-moon light is four times this value)
Definition at line 24 of file calendar.cpp.
Referenced by moon_light_at().
nautical_dawn
constexpr units::angle nautical_dawn = -12_degrees static constexpr
Definition at line 43 of file calendar.cpp.
Referenced by sun_light_at().
real_world_season_length
constexpr int real_world_season_length = 91 static constexpr
Definition at line 740 of file calendar.cpp.
Referenced by calendar::season_ratio().
sunrise_angle
constexpr units::angle sunrise_angle = -1_degrees static constexpr
Definition at line 45 of file calendar.cpp.
Referenced by is_day(), is_twilight(), sun_light_at(), sunlight_angle(), sunrise(), and sunset().