Cataclysm DDA: src/cata_variant.cpp File Reference
cata_variant.cpp File Reference
#include "cata_variant.h"
#include "debug_menu.h"
#include "mutation.h"
Namespaces
io
Functions
template<size_t I>
static bool is_valid_impl_2 (const std::string &s)
template<size_t... I>
constexpr bool is_valid_impl (const cata_variant &v, std::index_sequence< I... >)
template<>
std::string io::enum_to_string< cata_variant_type > (cata_variant_type type)
Function Documentation
is_valid_impl()
template<size_t... I> constexpr bool is_valid_impl (const cata_variant & v, std::index_sequence< I... >) constexpr
Definition at line 13 of file cata_variant.cpp.
 {
     constexpr size_t num_types = static_cast<size_t>( cata_variant_type::num_types );
     constexpr std::array<bool( * )( const std::string & ), num_types> is_valid_helpers = {{
             is_valid_impl_2<I>...
         }
     };
     // No match
     return is_valid_helpers[static_cast<size_t>( v.type() )]( v.get_string() );
 }
References cata_variant::get_string(), num_types, and cata_variant::type().
Referenced by cata_variant::is_valid().
is_valid_impl_2()
template<size_t I> static bool is_valid_impl_2 (const std::string & s) static
Definition at line 6 of file cata_variant.cpp.
 {
     constexpr cata_variant_type T = static_cast<cata_variant_type>( I );
     return cata_variant_detail::convert<T>::is_valid( s );
 }