Cataclysm DDA: src/catacharset.h File Reference
catacharset.h File Reference
#include <cstddef>
#include <cstdint>
#include <iterator>
#include <string>
#include <string_view>
#include <vector>
Classes
class utf8_wrapper
UTF8-Wrapper over std::string.
class utf8_view
class utf8_view::iterator
Macros
#define CATA_SRC_CATACHARSET_H
Functions
uint32_t UTF8_getch (const char **src, int *srclen)
uint32_t UTF8_getch (const std::string &str)
int cursorx_to_position (const char *line, int cursorx, int *prevpos=nullptr, int maxlen=-1)
int utf8_width (std::string_view str, bool ignore_tags=false)
int utf8_width (const utf8_wrapper &str, bool ignore_tags=false)
std::string left_justify (const std::string &str, int width, bool ignore_tags=false)
std::string right_justify (const std::string &str, int width, bool ignore_tags=false)
std::string utf8_justify (const std::string &str, int width, bool ignore_tags=false)
int center_text_pos (const char *text, int start_pos, int end_pos)
Center text inside whole line.
int center_text_pos (const std::string &text, int start_pos, int end_pos)
int center_text_pos (const utf8_wrapper &text, int start_pos, int end_pos)
std::string utf32_to_utf8 (uint32_t ch)
std::string utf8_truncate (const std::string &s, size_t length)
std::string base64_encode (const std::string &str)
std::string base64_decode (const std::string &str)
std::wstring utf8_to_wstr (const std::string &str)
std::string wstr_to_utf8 (const std::wstring &wstr)
std::string wstr_to_native (const std::wstring &wstr)
std::string utf32_to_utf8 (std::u32string_view str)
std::u32string utf8_to_utf32 (std::string_view str)
std::vector< std::string > utf8_display_split (const std::string &)
void utf8_display_split_into (const std::string &, std::vector< std::string_view > &)
Variables
constexpr int ANY_LENGTH = 5
constexpr int NULL_UNICODE = 0x0000
constexpr int PERCENT_SIGN_UNICODE = 0x0025
constexpr int UNKNOWN_UNICODE = 0xFFFD
Macro Definition Documentation
CATA_SRC_CATACHARSET_H
#define CATA_SRC_CATACHARSET_H
Definition at line 3 of file catacharset.h.
Function Documentation
base64_decode()
std::string base64_decode (const std::string & str)
Definition at line 267 of file catacharset.cpp.
 {
     // do not decode if it is not base64
     if( str.empty() || str[0] != '#' ) {
         return str;
     }
     build_base64_decoding_table();
     std::string instr = str.substr( 1 );
     int input_length = instr.length();
     if( input_length % 4 != 0 ) {
         return str;
     }
     int output_length = input_length / 4 * 3;
     const char *data = instr.c_str();
     if( data[input_length - 1] == '=' ) {
         output_length--;
     }
     if( data[input_length - 2] == '=' ) {
         output_length--;
     }
     std::string decoded_data( output_length, '\0' );
     for( int i = 0, j = 0; i < input_length; ) {
         unsigned sextet_a = data[i] == '=' ? 0 & i++ : base64_decoding_table[static_cast<unsigned char>
                             ( data[i++] )];
         unsigned sextet_b = data[i] == '=' ? 0 & i++ : base64_decoding_table[static_cast<unsigned char>
                             ( data[i++] )];
         unsigned sextet_c = data[i] == '=' ? 0 & i++ : base64_decoding_table[static_cast<unsigned char>
                             ( data[i++] )];
         unsigned sextet_d = data[i] == '=' ? 0 & i++ : base64_decoding_table[static_cast<unsigned char>
                             ( data[i++] )];
         unsigned triple = ( sextet_a << 3 * 6 )
                           + ( sextet_b << 2 * 6 )
                           + ( sextet_c << 1 * 6 )
                           + ( sextet_d << 0 * 6 );
         if( j < output_length ) {
             decoded_data[j++] = ( triple >> 2 * 8 ) & 0xFF;
         }
         if( j < output_length ) {
             decoded_data[j++] = ( triple >> 1 * 8 ) & 0xFF;
         }
         if( j < output_length ) {
             decoded_data[j++] = ( triple >> 0 * 8 ) & 0xFF;
         }
     }
     return decoded_data;
 }
References base64_decoding_table, and build_base64_decoding_table().
Referenced by save_t::from_base_path().
base64_encode()
std::string base64_encode (const std::string & str)
Definition at line 233 of file catacharset.cpp.
 {
     //assume it is already encoded
     if( !str.empty() && str[0] == '#' ) {
         return str;
     }
     int input_length = str.length();
     int output_length = 4 * ( ( input_length + 2 ) / 3 );
     std::string encoded_data( output_length, '\0' );
     const unsigned char *data = reinterpret_cast<const unsigned char *>( str.c_str() );
     for( int i = 0, j = 0; i < input_length; ) {
         unsigned octet_a = i < input_length ? data[i++] : 0;
         unsigned octet_b = i < input_length ? data[i++] : 0;
         unsigned octet_c = i < input_length ? data[i++] : 0;
         unsigned triple = ( octet_a << 0x10 ) + ( octet_b << 0x08 ) + octet_c;
         encoded_data[j++] = base64_encoding_table[( triple >> 3 * 6 ) & 0x3F];
         encoded_data[j++] = base64_encoding_table[( triple >> 2 * 6 ) & 0x3F];
         encoded_data[j++] = base64_encoding_table[( triple >> 1 * 6 ) & 0x3F];
         encoded_data[j++] = base64_encoding_table[( triple >> 0 * 6 ) & 0x3F];
     }
     for( int i = 0; i < mod_table[input_length % 3]; i++ ) {
         encoded_data[output_length - 1 - i] = '=';
     }
     return "#" + encoded_data;
 }
References base64_encoding_table, and mod_table.
Referenced by save_t::base_path(), diary::load(), game::move_save_to_graveyard(), PATH_INFO::player_base_save_path(), PATH_INFO::player_base_save_path_path(), game::save(), and diary::store().
center_text_pos() [1/3]
int center_text_pos (const char * text, int start_pos, int end_pos)
Center text inside whole line.
Parameters
text to be centered.
start_pos printable position on line.
end_pos printable position on line.
Returns
First char position of centered text or start_pos if text is too big.
Definition at line 445 of file catacharset.cpp.
 {
     int full_screen = end_pos - start_pos + 1;
     int str_len = utf8_width( text );
     int position = ( full_screen - str_len ) / 2;
     if( position <= 0 ) {
         return start_pos;
     }
     return start_pos + position;
 }
References utf8_width().
Referenced by center_text_pos(), decorate_panel(), get_bodygraph_lines(), and recipe_result_info_cache::insert_iteminfo_block_separator().
center_text_pos() [2/3]
int center_text_pos (const std::string & text, int start_pos, int end_pos)
Definition at line 458 of file catacharset.cpp.
 {
     return center_text_pos( text.c_str(), start_pos, end_pos );
 }
References center_text_pos().
center_text_pos() [3/3]
int center_text_pos (const utf8_wrapper & text, int start_pos, int end_pos)
Definition at line 463 of file catacharset.cpp.
 {
     int full_screen = end_pos - start_pos + 1;
     int str_len = text.display_width();
     int position = ( full_screen - str_len ) / 2;
     if( position <= 0 ) {
         return start_pos;
     }
     return start_pos + position;
 }
References utf8_wrapper::display_width().
cursorx_to_position()
int cursorx_to_position (const char * line, int cursorx, int * prevpos = nullptr, int maxlen = -1)
Definition at line 161 of file catacharset.cpp.
 {
     int dummy;
     int i = 0;
     int c = 0;
     int *p = prevpos ? prevpos : &dummy;
     *p = 0;
     while( c < cursorx ) {
         const char *utf8str = line + i;
         int len = ANY_LENGTH;
         if( utf8str[0] == 0 ) {
             break;
         }
         uint32_t ch = UTF8_getch( &utf8str, &len );
         int cw = mk_wcwidth( ch );
         len = ANY_LENGTH - len;
         if( len <= 0 ) {
             len = 1;
         }
         if( maxlen >= 0 && maxlen < ( i + len ) ) {
             break;
         }
         i += len;
         if( cw <= 0 ) {
             cw = 0;
         }
         c += cw;
         if( c <= cursorx ) {
             *p = i;
         }
     }
     return i;
 }
References ANY_LENGTH, c, line(), mk_wcwidth(), and UTF8_getch().
Referenced by trim_by_length(), and utf8_truncate().
left_justify()
std::string left_justify (const std::string & str, int width, bool ignore_tags = false)
Definition at line 127 of file catacharset.cpp.
 {
     int str_width = utf8_width( str, ignore_tags );
     if( str_width >= width ) {
         return str;
     } else {
         return str + std::string( width - str_width, ' ' );
     }
 }
References utf8_width().
Referenced by talk_function::companion_choose(), bodygraph_display::draw_partlist(), draw_proficiencies_tab(), draw_spellbook_info(), Character::extended_description(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), avatar::read(), and utf8_justify().
right_justify()
std::string right_justify (const std::string & str, int width, bool ignore_tags = false)
Definition at line 137 of file catacharset.cpp.
 {
     int str_width = utf8_width( str, ignore_tags );
     if( str_width >= width ) {
         return str;
     } else {
         return std::string( width - str_width, ' ' ) + str;
     }
 }
References utf8_width().
Referenced by veh_interact::calc_overview(), camp_trip_description(), talk_response::create_option_line(), veh_interact::display_overview(), basecamp::recruit_return(), uilist::show(), and utf8_justify().
utf32_to_utf8() [1/2]
std::string utf32_to_utf8 (std::u32string_view str)
Definition at line 392 of file catacharset.cpp.
 {
     std::string ret;
     ret.reserve( str.length() );
     for( const char32_t c : str ) {
         ret += utf32_to_utf8( c );
     }
     return ret;
 }
References c, and cata::hash64_detail::ret.
Referenced by input_context::get_desc(), text_style_check_reader::get_next(), map_extra::get_symbol(), overmap_land_use_code::get_symbol(), oter_type_t::get_symbol(), weather_printable::get_symbol(), weather_type::get_symbol(), oter_t::get_symbol(), field_type::get_symbol(), auto_notes::custom_symbol::get_symbol_string(), string_editor_window::print_editor(), string_editor_window::query_string(), string_input_popup::query_string(), and vehicle_prototype::save_vehicle_as_prototype().
utf32_to_utf8() [2/2]
std::string utf32_to_utf8 (uint32_t ch)
Definition at line 43 of file json.cpp.
 {
     std::array<char, 5> out;
     char *buf = out.data();
     static constexpr std::array<unsigned char, 7> utf8FirstByte = {
         0x00, 0x00, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC
     };
     int utf8Bytes;
     if( ch < 0x80 ) {
         utf8Bytes = 1;
     } else if( ch < 0x800 ) {
         utf8Bytes = 2;
     } else if( ch < 0x10000 ) {
         utf8Bytes = 3;
     } else if( ch <= 0x10FFFF ) {
         utf8Bytes = 4;
     } else {
         utf8Bytes = 3;
         ch = UNKNOWN_UNICODE;
     }
     buf += utf8Bytes;
     switch( utf8Bytes ) {
         case 4: // NOLINT(bugprone-branch-clone)
             *--buf = ( ch | 0x80 ) & 0xBF;
             ch >>= 6;
         /* fallthrough */
         case 3:
             *--buf = ( ch | 0x80 ) & 0xBF;
             ch >>= 6;
         /* fallthrough */
         case 2:
             *--buf = ( ch | 0x80 ) & 0xBF;
             ch >>= 6;
         /* fallthrough */
         case 1:
             *--buf = ch | utf8FirstByte[utf8Bytes];
     }
     out[utf8Bytes] = '\0';
     return out.data();
 }
References UNKNOWN_UNICODE.
Referenced by get_escaped_or_unicode().
utf8_display_split()
std::vector<std::string> utf8_display_split (const std::string & s)
Definition at line 415 of file catacharset.cpp.
 {
     std::vector<std::string> result;
     std::vector<std::string_view> parts;
     utf8_display_split_into( s, parts );
     result.reserve( parts.size() );
     for( std::string_view part : parts ) {
         result.emplace_back( part );
     }
     return result;
 }
References utf8_display_split_into().
Referenced by vpart_variant::load(), bodygraph::load(), and main_menu::print_menu_items().
utf8_display_split_into()
void utf8_display_split_into (const std::string & s, std::vector< std::string_view > & result)
Definition at line 427 of file catacharset.cpp.
 {
     const char *pos = s.c_str();
     const char *glyph_begin = pos;
     const char *glyph_end = pos;
     int len = s.length();
     while( len > 0 ) {
         const uint32_t ch = UTF8_getch( &pos, &len );
         const int width = mk_wcwidth( ch );
         if( width > 0 && glyph_begin != glyph_end ) {
             result.emplace_back( glyph_begin, std::distance( glyph_begin, glyph_end ) );
             glyph_begin = glyph_end;
         }
         glyph_end = pos;
     }
     result.emplace_back( glyph_begin, std::distance( glyph_begin, glyph_end ) );
 }
References mk_wcwidth(), math_opers::pos(), and UTF8_getch().
Referenced by mapgen_function_json_base::setup_common(), and utf8_display_split().
UTF8_getch() [1/2]
uint32_t UTF8_getch (const char ** src, int * srclen)
Definition at line 20 of file catacharset.cpp.
 {
     const unsigned char *p = *reinterpret_cast<const unsigned char **>( src );
     int left = 0;
     bool overlong = false;
     bool underflow = false;
     uint32_t ch = UNKNOWN_UNICODE;
     if( *srclen == 0 ) {
         return UNKNOWN_UNICODE;
     }
     if( p[0] >= 0xFC ) {
         if( ( p[0] & 0xFE ) == 0xFC ) {
             if( p[0] == 0xFC && ( p[1] & 0xFC ) == 0x80 ) {
                 overlong = true;
             }
             ch = static_cast<uint32_t>( p[0] & 0x01 );
             left = 5;
         }
     } else if( p[0] >= 0xF8 ) {
         if( ( p[0] & 0xFC ) == 0xF8 ) {
             if( p[0] == 0xF8 && ( p[1] & 0xF8 ) == 0x80 ) {
                 overlong = true;
             }
             ch = static_cast<uint32_t>( p[0] & 0x03 );
             left = 4;
         }
     } else if( p[0] >= 0xF0 ) {
         if( ( p[0] & 0xF8 ) == 0xF0 ) {
             if( p[0] == 0xF0 && ( p[1] & 0xF0 ) == 0x80 ) {
                 overlong = true;
             }
             ch = static_cast<uint32_t>( p[0] & 0x07 );
             left = 3;
         }
     } else if( p[0] >= 0xE0 ) {
         if( ( p[0] & 0xF0 ) == 0xE0 ) {
             if( p[0] == 0xE0 && ( p[1] & 0xE0 ) == 0x80 ) {
                 overlong = true;
             }
             ch = static_cast<uint32_t>( p[0] & 0x0F );
             left = 2;
         }
     } else if( p[0] >= 0xC0 ) {
         if( ( p[0] & 0xE0 ) == 0xC0 ) {
             if( ( p[0] & 0xDE ) == 0xC0 ) {
                 overlong = true;
             }
             ch = static_cast<uint32_t>( p[0] & 0x1F );
             left = 1;
         }
     } else {
         if( ( p[0] & 0x80 ) == 0x00 ) {
             ch = static_cast<uint32_t>( p[0] );
         }
     }
     ++*src;
     --*srclen;
     while( left > 0 && *srclen > 0 ) {
         ++p;
         if( ( p[0] & 0xC0 ) != 0x80 ) {
             ch = UNKNOWN_UNICODE;
             break;
         }
         ch <<= 6;
         ch |= ( p[0] & 0x3F );
         ++*src;
         --*srclen;
         --left;
     }
     if( left > 0 ) {
         underflow = true;
     }
     if( overlong || underflow ||
         ( ch >= 0xD800 && ch <= 0xDFFF ) ||
         ( ch == 0xFFFE || ch == 0xFFFF ) || ch > 0x10FFFF ) {
         ch = UNKNOWN_UNICODE;
     }
     return ch;
 }
References keycode::left, and UNKNOWN_UNICODE.
Referenced by utf8_wrapper::at(), game::bury_screen(), utf8_wrapper::byte_start(), utf8_wrapper::byte_start_display(), folded_text::codepoint_coordinates(), cursorx_to_position(), utf8_view::iterator::decode(), folded_text::folded_text(), input_manager::get_input_event(), auto_notes::custom_symbol::get_symbol(), utf8_wrapper::init_utf8_wrapper(), vpart_variant::load(), rotatable_symbols::load(), string_editor_window::print_editor(), string_editor_window::query_string(), string_input_popup::query_string(), auto_notes::custom_symbol::set_symbol(), trim_by_length(), unicode_codepoint_from_symbol_reader(), utf8_display_split_into(), UTF8_getch(), utf8_to_utf32(), utf8_width(), utf8_width_notags(), and word_rewrap().
UTF8_getch() [2/2]
uint32_t UTF8_getch (const std::string & str) inline
Definition at line 21 of file catacharset.h.
 {
     const char *utf8str = str.c_str();
     int len = str.length();
     return UTF8_getch( &utf8str, &len );
 }
References utf8_wrapper::str(), and UTF8_getch().
utf8_justify()
std::string utf8_justify (const std::string & str, int width, bool ignore_tags = false)
Definition at line 147 of file catacharset.cpp.
 {
     if( width < 0 ) {
         return left_justify( str, -width, ignore_tags );
     } else {
         return right_justify( str, width, ignore_tags );
     }
 }
References left_justify(), and right_justify().
utf8_to_utf32()
std::u32string utf8_to_utf32 (std::string_view str)
Definition at line 402 of file catacharset.cpp.
 {
     int len = str.length();
     const char *dat = str.data();
     std::u32string ret;
     ret.reserve( len );
     while( len > 0 ) {
         ret.push_back( UTF8_getch( &dat, &len ) );
     }
     ret.shrink_to_fit();
     return ret;
 }
References cata::hash64_detail::ret, and UTF8_getch().
Referenced by text_style_check_reader::get_next(), and lcmatch().
utf8_to_wstr()
std::wstring utf8_to_wstr (const std::string & str)
Definition at line 340 of file catacharset.cpp.
 {
 #if defined(_WIN32)
     int sz = MultiByteToWideChar( CP_UTF8, 0, str.c_str(), -1, nullptr, 0 ) + 1;
     std::wstring wstr( sz, '\0' );
     MultiByteToWideChar( CP_UTF8, 0, str.c_str(), -1, wstr.data(), sz );
     strip_trailing_nulls( wstr );
     return wstr;
 #else
     std::size_t sz = std::mbstowcs( nullptr, str.c_str(), 0 );
     cata_assert( sz != static_cast<size_t>( -1 ) );
     std::wstring wstr( sz + 1, '\0' );
     [[maybe_unused]] const size_t converted = std::mbstowcs( wstr.data(), str.c_str(), sz );
     cata_assert( converted == sz );
     strip_trailing_nulls( wstr );
     return wstr;
 #endif
 }
References cata_assert, and strip_trailing_nulls().
Referenced by append_line(), game::check_safe_mode_allowed(), widget::graph(), inscribe_actor::item_inscription(), lowercase_first_letter(), obscure_message(), localized_comparator::operator()(), Character::shout(), string_empty_or_whitespace(), to_upper_case(), and uppercase_first_letter().
utf8_truncate()
std::string utf8_truncate (const std::string & s, size_t length)
Definition at line 195 of file catacharset.cpp.
 {
     if( length == 0 || s.empty() ) {
         return s;
     }
     int last_pos = cursorx_to_position( s.c_str(), length, nullptr, -1 );
     return s.substr( 0, last_pos );
 }
References cursorx_to_position(), and length.
Referenced by Character::print_encumbrance(), advanced_inventory::redraw_pane(), advanced_inventory::refresh_minimap(), set_traits(), options_manager::show(), and trunc_ellipse().
utf8_width() [1/2]
int utf8_width (const utf8_wrapper & str, bool ignore_tags = false)
Definition at line 122 of file catacharset.cpp.
 {
     return utf8_width( str.c_str(), ignore_tags );
 }
References utf8_wrapper::c_str(), and utf8_width().
utf8_width() [2/2]
int utf8_width (std::string_view str, bool ignore_tags = false)
Definition at line 104 of file catacharset.cpp.
 {
     if( ignore_tags ) {
         return utf8_width( remove_color_tags( s ) );
     }
     int len = s.size();
     const char *ptr = s.data();
     int w = 0;
     while( len > 0 ) {
         uint32_t ch = UTF8_getch( &ptr, &len );
         if( ch == UNKNOWN_UNICODE ) {
             continue;
         }
         w += mk_wcwidth( ch );
     }
     return w;
 }
References mk_wcwidth(), remove_color_tags(), UNKNOWN_UNICODE, and UTF8_getch().
Referenced by anonymous_namespace{armor_layers.cpp}::add_category_and_values(), add_folded_name_and_value(), append_line(), Character::body_window(), game::bury_screen(), query_popup::button::button(), uilist::calc_data(), center_print(), center_text_pos(), debug_menu::change_spells(), bodygraph::check(), Item_factory::check_definitions(), teleporter_list::choose_teleport_location(), veh_interact::create_or_get_ui_adaptor(), string_input_popup::create_window(), player_morale::display(), veh_interact::display_list(), veh_interact::display_mode(), veh_interact::display_name(), veh_interact::display_stats(), main_menu::display_sub_menu(), Character::dispose_item(), inventory_column::draw(), char_creation::draw_age(), overmap_ui::draw_ascii(), draw_bionics_tab(), char_creation::draw_blood(), bodygraph_display::draw_borders(), overmap_ui::draw_camp_labels(), talk_function::draw_camp_tabs(), overmap_ui::draw_city_labels(), draw_connectors(), inventory_selector::draw_footer(), char_creation::draw_gender(), draw_health_summary(), char_creation::draw_height(), target_ui::draw_help_notice(), char_creation::draw_location(), draw_medical_titlebar(), exosuit_interact::draw_menu(), help::draw_menu(), char_creation::draw_name(), char_creation::draw_outfit(), game::draw_panels(), draw_points(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_spellbook_info(), draw_stats_tab(), draw_subtab(), draw_tab(), draw_tabs(), exosuit_interact::exosuit_interact(), inventory_column::expand_to_fit(), Character::extended_description(), npc::faction_display(), uimenu::finalize_addentries(), fit_tabs_to_width(), multiline_list::fold_entries(), format_widget_multiline(), inventory_column::get_entry_cell_width(), inventory_selector::get_footer_min_width(), inventory_selector::get_header_min_width(), get_labeled_bar(), game::get_player_input(), known_magic::get_spellname_max_width(), cataimgui::window::get_text_height(), cataimgui::window::get_text_width(), scrollingcombattext::cSCT::getPosX(), scrollingcombattext::cSCT::getPosY(), widget::graph(), Messages::dialog::init(), insert_table(), item_filter_rule_string(), left_justify(), game::list_items(), game::list_monsters(), mtype::load(), widget::load(), ascii_art::load(), main_menu::load_character_tab(), map_key::map_key(), obscure_message(), target_ui::panel_cursor_info(), worldfactory::pick_world(), avatar::power_bionics(), bodygraph_display::prepare_infotext(), print_confidence_ratings(), Character::print_encumbrance(), snake_game::print_header(), npc::print_info(), monster::print_info(), advanced_inventory::print_items(), multiline_list::print_line(), main_menu::print_menu(), vehicle::print_part_list(), print_ranged_chance(), game::print_terrain_info(), game::print_vehicle_info(), query_for_template_name(), avatar::read(), advanced_inventory::redraw_pane(), wish_monster_callback::refresh(), wish_item_callback::refresh(), game::reset_item_list_state(), right_justify(), right_print(), satiety_bar(), overmap_ui::search(), select_crafter_and_crafting_recipe(), set_description(), set_hobbies(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), options_manager::cOpt::setNext(), shortcut_print(), options_manager::show(), safemode::show(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), spellcasting_callback::spell_info_text(), lightson_game::start_game(), minesweeper_game::start_game(), sokoban_game::start_game(), inventory_multiselector::toggle_entries(), trim_by_length(), trimmed_name_and_value(), trunc_ellipse(), overmap_ui::update_note_preview(), and utf8_width().
wstr_to_native()
std::string wstr_to_native (const std::wstring & wstr)
Definition at line 378 of file catacharset.cpp.
 {
 #if defined(_WIN32)
     int native_size = WideCharToMultiByte( CP_ACP, 0, &wstr[0], -1, nullptr, 0, nullptr,
                                            nullptr ) + 1;
     std::string result( native_size, '\0' );
     WideCharToMultiByte( CP_ACP, 0, &wstr[0], -1, &result[0], native_size, nullptr, nullptr );
     strip_trailing_nulls( result );
     return result;
 #else
     return wstr_to_utf8( wstr );
 #endif
 }
References strip_trailing_nulls(), and wstr_to_utf8().
wstr_to_utf8()
std::string wstr_to_utf8 (const std::wstring & wstr)
Definition at line 359 of file catacharset.cpp.
 {
 #if defined(_WIN32)
     int sz = WideCharToMultiByte( CP_UTF8, 0, wstr.c_str(), -1, nullptr, 0, nullptr, nullptr );
     std::string str( sz, '\0' );
     WideCharToMultiByte( CP_UTF8, 0, wstr.c_str(), -1, str.data(), sz, nullptr, nullptr );
     strip_trailing_nulls( str );
     return str;
 #else
     std::size_t sz = std::wcstombs( nullptr, wstr.c_str(), 0 );
     cata_assert( sz != static_cast<size_t>( -1 ) );
     std::string str( sz + 1, '\0' );
     [[maybe_unused]] const size_t converted = std::wcstombs( str.data(), wstr.c_str(), sz );
     cata_assert( converted == sz );
     strip_trailing_nulls( str );
     return str;
 #endif
 }
References cata_assert, and strip_trailing_nulls().
Referenced by append_line(), game::check_safe_mode_allowed(), widget::graph(), inscribe_actor::item_inscription(), lowercase_first_letter(), obscure_message(), localized_comparator::operator()(), Character::shout(), to_upper_case(), uppercase_first_letter(), and wstr_to_native().
Variable Documentation
ANY_LENGTH
constexpr int ANY_LENGTH = 5 constexpr
Definition at line 12 of file catacharset.h.
Referenced by cursorx_to_position(), and word_rewrap().
NULL_UNICODE
constexpr int NULL_UNICODE = 0x0000 constexpr
Definition at line 13 of file catacharset.h.
Referenced by game::get_player_input(), overmap_land_use_code::load(), oter_type_t::load(), and map_extra::load().
PERCENT_SIGN_UNICODE
constexpr int PERCENT_SIGN_UNICODE = 0x0025 constexpr
Definition at line 14 of file catacharset.h.
UNKNOWN_UNICODE
constexpr int UNKNOWN_UNICODE = 0xFFFD constexpr
Definition at line 15 of file catacharset.h.
Referenced by utf8_wrapper::at(), utf8_wrapper::byte_start(), utf8_wrapper::byte_start_display(), input_event::get_first_input(), input_manager::get_input_event(), utf8_wrapper::init_utf8_wrapper(), popup(), cataimgui::client::process_input(), utf32_to_utf8(), UTF8_getch(), UTF8_getch_raw(), utf8_width(), utf8_width_notags(), and utf8_width_raw().