Cataclysm DDA: src/cata_utility.cpp File Reference
cata_utility.cpp File Reference
#include "cata_utility.h"
#include <zconf.h>
#include <algorithm>
#include <cerrno>
#include <charconv>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cwctype>
#include <exception>
#include <fstream>
#include <iosfwd>
#include <ostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include "cached_options.h"
#include "cata_path.h"
#include "catacharset.h"
#include "debug.h"
#include "filesystem.h"
#include "flexbuffer_json.h"
#include "json.h"
#include "json_loader.h"
#include "ofstream_wrapper.h"
#include "options.h"
#include "output.h"
#include "pinyin.h"
#include "rng.h"
#include "string_formatter.h"
#include "translation.h"
#include "translations.h"
#include "unicode.h"
#include "zlib.h"
Namespaces
anonymous_namespace{cata_utility.cpp}
Functions
static double pow10 (unsigned int n)
double round_up (double val, unsigned int dp)
Round a value up at a given decimal place.
int divide_round_down (int a, int b)
int modulo (int v, int m)
bool isBetween (int test, int down, int up)
Determine whether a value is between two given boundaries.
bool lcmatch (const std::string_view str, const std::string_view qry)
Perform case insensitive search for a query string inside a subject string.
bool lcmatch (const translation &str, const std::string_view qry)
bool match_include_exclude (const std::string_view text, std::string filter)
Matches text case insensitive with the include/exclude rules of the filter.
double logarithmic (double t)
Basic logistic function.
double logarithmic_range (int min, int max, int pos)
Normalized logistic function.
int bound_mod_to_vals (int val, int mod, int max, int min)
Clamp the value of a modifier in order to bound the resulting value.
const char * velocity_units (const units_type vel_units)
Create a units label for a velocity value.
double kelvin_to_fahrenheit (double kelvin)
Convert a temperature from Kelvin to degrees Fahrenheit.
double clamp_to_width (double value, int width, int &scale)
Clamp (number and space wise) value to with, taking into account the specified preferred scale, returning the adjusted (shortened) scale that best fit the width, optionally returning a flag that indicate if the value was truncated to fit the width.
double clamp_to_width (double value, int width, int &scale, bool *out_truncated)
float multi_lerp (const std::vector< std::pair< float, float >> &points, float x)
From points, finds p1 and p2 such that p1.first < x < p2.first Then linearly interpolates between p1.second and p2.second and returns the result.
void write_to_file (const std::string &path, const std::function< void(std::ostream &)> &writer)
bool write_to_file (const std::string &path, const std::function< void(std::ostream &)> &writer, const char *const fail_message)
Open a file for writing, calls the writer on that stream.
void write_to_file (const cata_path &path, const std::function< void(std::ostream &)> &writer)
bool write_to_file (const cata_path &path, const std::function< void(std::ostream &)> &writer, const char *const fail_message)
std::istream & safe_getline (std::istream &ins, std::string &str)
std::string anonymous_namespace{cata_utility.cpp}::read_compressed_file_to_string (std::istream &fin)
bool read_from_file (const cata_path &path, const std::function< void(std::istream &)> &reader)
bool read_from_file (const fs::path &path, const std::function< void(std::istream &)> &reader)
bool read_from_file (const std::string &path, const std::function< void(std::istream &)> &reader)
Try to open and read from given file using the given callback.
std::unique_ptr< std::istream > read_maybe_compressed_file (const std::string &path)
Try to open and provide a std::istream for the given, possibly, gzipped, file.
std::unique_ptr< std::istream > read_maybe_compressed_file (const fs::path &path)
std::unique_ptr< std::istream > read_maybe_compressed_file (const cata_path &path)
std::optional< std::string > read_whole_file (const std::string &path)
Try to open and read the entire file to a string.
std::optional< std::string > read_whole_file (const fs::path &path)
std::optional< std::string > read_whole_file (const cata_path &path)
bool read_from_file_json (const cata_path &path, const std::function< void(const JsonValue &)> &reader)
bool read_from_file_optional (const std::string &path, const std::function< void(std::istream &)> &reader)
bool read_from_file_optional (const fs::path &path, const std::function< void(std::istream &)> &reader)
bool read_from_file_optional (const cata_path &path, const std::function< void(std::istream &)> &reader)
bool read_from_file_optional_json (const cata_path &path, const std::function< void(const JsonValue &)> &reader)
std::string obscure_message (const std::string &str, const std::function< char()> &f)
Apply fuzzy effect to a string like: Hello, world! --> H##lo, wurl#!
std::string serialize_wrapper (const std::function< void(JsonOut &)> &callback)
@group JSON (de)serialization wrappers.
void deserialize_wrapper (const std::function< void(const JsonValue &)> &callback, const std::string &data)
bool string_empty_or_whitespace (const std::string &s)
int string_view_cmp (const std::string_view l, const std::string_view r)
strcmp, but for string_view objects.
template<typename Integer >
Integer svto (const std::string_view s)
template int svto< int > (std::string_view)
std::vector< std::string > string_split (const std::string_view string, char delim)
Splits a string by delimiter into a vector of strings.
static bool is_easter (int day, int month, int year)
holiday get_holiday_from_time (std::time_t time, bool force_refresh)
Get the current holiday based on the given time, or based on current time if time = 0.
int bucket_index_from_weight_list (const std::vector< int > &weights)
Returns a random (weighted) bucket index from a list of weights.
std::optional< double > svtod (std::string_view token)
Function Documentation
bound_mod_to_vals()
int bound_mod_to_vals (int val, int mod, int max, int min)
Clamp the value of a modifier in order to bound the resulting value.
Ensures that a modifier value will not cause a base value to exceed given bounds when applied. If necessary, the given modifier value is increased or reduced to meet this constraint.
Giving a value of zero for min or max indicates that there is no minimum or maximum boundary, respectively.
Parameters
val The base value that the modifier will be applied to
mod The desired modifier to be added to the base value
max The desired maximum value of the base value after modification, or zero.
min The desired minimum value of the base value after modification, or zero.
Returns
Value of mod, possibly altered to respect the min and max boundaries
Definition at line 199 of file cata_utility.cpp.
 {
     if( val + mod > max && max != 0 ) {
         mod = std::max( max - val, 0 );
     }
     if( val + mod < min && min != 0 ) {
         mod = std::min( min - val, 0 );
     }
     return mod;
 }
References max(), and min().
Referenced by Character::process_one_effect().
bucket_index_from_weight_list()
int bucket_index_from_weight_list (const std::vector< int > & weights)
Returns a random (weighted) bucket index from a list of weights.
Parameters
weights vector with a list of int weights
Returns
random bucket index
Definition at line 844 of file cata_utility.cpp.
 {
     int total_weight = std::accumulate( weights.begin(), weights.end(), int( 0 ) );
     if( total_weight < 1 ) {
         return 0;
     }
     const int roll = rng( 0, total_weight - 1 );
     int index = 0;
     int accum = 0;
     for( int w : weights ) {
         accum += w;
         if( accum > roll ) {
             break;
         }
         index++;
     }
     return index;
 }
References rng().
Referenced by field_processor_fd_electricity().
clamp_to_width() [1/2]
double clamp_to_width (double value, int width, int & scale)
Clamp (number and space wise) value to with, taking into account the specified preferred scale, returning the adjusted (shortened) scale that best fit the width, optionally returning a flag that indicate if the value was truncated to fit the width.
Definition at line 233 of file cata_utility.cpp.
 {
     return clamp_to_width( value, width, scale, nullptr );
 }
Referenced by format_volume().
clamp_to_width() [2/2]
double clamp_to_width (double value, int width, int & scale, bool * out_truncated)
Definition at line 238 of file cata_utility.cpp.
 {
     if( out_truncated != nullptr ) {
         *out_truncated = false;
     }
     if( value >= std::pow( 10.0, width ) ) {
         // above the maximum number we can fit in the width without decimal
         // show the biggest number we can without decimal
         // flag as truncated
         value = std::pow( 10.0, width ) - 1.0;
         scale = 0;
         if( out_truncated != nullptr ) {
             *out_truncated = true;
         }
     } else if( scale > 0 ) {
         for( int s = 1; s <= scale; s++ ) {
             // 1 decimal separator + "s"
             int scale_width = 1 + s;
             if( width > scale_width && value >= std::pow( 10.0, width - scale_width ) ) {
                 // above the maximum number we can fit in the width with "s" decimals
                 // show this number with one less decimal than "s"
                 scale = s - 1;
                 break;
             }
         }
     }
     return value;
 }
deserialize_wrapper()
void deserialize_wrapper (const std::function< void(const JsonValue &)> & callback, const std::string & data)
Definition at line 657 of file cata_utility.cpp.
 {
     JsonValue jsin = json_loader::from_string( data );
     callback( jsin );
 }
References json_loader::from_string().
Referenced by deserialize_from_string().
divide_round_down()
int divide_round_down (int a, int b)
Definition at line 62 of file cata_utility.cpp.
 {
     if( b < 0 ) {
         a = -a;
         b = -b;
     }
     if( a >= 0 ) {
         return a / b;
     } else {
         return -( ( -a + b - 1 ) / b );
     }
 }
References a, and b.
Referenced by input_context::get_coordinates_text().
get_holiday_from_time()
holiday get_holiday_from_time (std::time_t time = 0, bool force_refresh = false)
Get the current holiday based on the given time, or based on current time if time = 0.
Parameters
time The timestampt to assess
force_refresh Force recalculation of current holiday, otherwise use cached value
Definition at line 772 of file cata_utility.cpp.
 {
     static holiday cached_holiday = holiday::none;
     static bool is_cached = false;
     if( force_refresh ) {
         is_cached = false;
     }
     if( is_cached ) {
         return cached_holiday;
     }
     is_cached = true;
     bool success = false;
     std::tm local_time;
     std::time_t current_time = time == 0 ? std::time( nullptr ) : time;
     /* necessary to pass LGTM, as threadsafe version of localtime differs by platform */
 #if defined(_WIN32)
     errno_t err = localtime_s( &local_time, &current_time );
     if( err == 0 ) {
         success = true;
     }
 #else
     success = !!localtime_r( &current_time, &local_time );
 #endif
     if( success ) {
         const int month = local_time.tm_mon + 1;
         const int day = local_time.tm_mday;
         const int wday = local_time.tm_wday;
         const int year = local_time.tm_year + 1900;
         /* check date against holidays */
         if( month == 1 && day == 1 ) {
             cached_holiday = holiday::new_year;
             return cached_holiday;
         }
         // only run easter date calculation if currently March or April
         else if( ( month == 3 || month == 4 ) && is_easter( day, month, year ) ) {
             cached_holiday = holiday::easter;
             return cached_holiday;
         } else if( month == 7 && day == 4 ) {
             cached_holiday = holiday::independence_day;
             return cached_holiday;
         }
         // 13 days seems appropriate for Halloween
         else if( month == 10 && day >= 19 ) {
             cached_holiday = holiday::halloween;
             return cached_holiday;
         } else if( month == 11 && ( day >= 22 && day <= 28 ) && wday == 4 ) {
             cached_holiday = holiday::thanksgiving;
             return cached_holiday;
         }
         // For the 12 days of Christmas, my true love gave to me...
         else if( month == 12 && ( day >= 14 && day <= 25 ) ) {
             cached_holiday = holiday::christmas;
             return cached_holiday;
         }
     }
     // fall through to here if localtime fails, or none of the day tests hit
     cached_holiday = holiday::none;
     return cached_holiday;
 }
References christmas, day, easter, halloween, independence_day, is_easter(), new_year, none, thanksgiving, and year.
Referenced by MonsterGroup::event_adjusted_freq_total(), main_menu::get_holiday_from_time(), Item_spawn_data::get_probability(), MonsterGroupManager::GetMonstersFromGroup(), MonsterGroupManager::GetRandomMonsterFromGroup(), and is_spawn_valid().
is_easter()
static bool is_easter (int day, int month, int year) static
Definition at line 744 of file cata_utility.cpp.
 {
     if( month == 3 ) {
         switch( year ) {
             // *INDENT-OFF*
             case 2024: return day == 31;
             case 2027: return day == 28;
             default: break;
             // *INDENT-ON*
         }
     } else if( month == 4 ) {
         switch( year ) {
             // *INDENT-OFF*
             case 2021: return day == 4;
             case 2022: return day == 17;
             case 2023: return day == 9;
             case 2025: return day == 20;
             case 2026: return day == 5;
             case 2028: return day == 16;
             case 2029: return day == 1;
             case 2030: return day == 21;
             default: break;
             // *INDENT-ON*
         }
     }
     return false;
 }
References day, and year.
Referenced by get_holiday_from_time().
isBetween()
bool isBetween (int test, int down, int up)
Determine whether a value is between two given boundaries.
Parameters
test Value to be tested.
down Lower boundary for value.
up Upper boundary for value.
Returns
True if test value is greater than lower boundary and less than upper boundary, otherwise returns false.
Definition at line 84 of file cata_utility.cpp.
 {
     return test > down && test < up;
 }
References keycode::down, and keycode::up.
kelvin_to_fahrenheit()
double kelvin_to_fahrenheit (double kelvin)
Convert a temperature from Kelvin to degrees Fahrenheit.
Returns
Temperature in degrees C.
Definition at line 228 of file cata_utility.cpp.
 {
     return 1.8 * ( kelvin - 273.15 ) + 32;
 }
lcmatch() [1/2]
bool lcmatch (std::string_view str, std::string_view qry)
Perform case insensitive search for a query string inside a subject string.
Searches for string given by qry inside a subject string given by str.
Supports searching for accented letters with a non-accented search key, for example, search key 'bo' matches 'B', but search key 'b' should not match with 'B' and only match with 'B' or 'B'.
Parameters
str Subject to search for occurrence of the query string.
qry Query string to search for in str
Returns
true if the query string is found at least once within the subject string, otherwise returns false
Definition at line 89 of file cata_utility.cpp.
 {
     // It will be quite common for the query string to be empty.  Anything will
     // match in that case, so short-circuit and avoid the expensive
     // conversions.
     if( qry.empty() ) {
         return true;
     }
     std::u32string u32_str = utf8_to_utf32( str );
     std::u32string u32_qry = utf8_to_utf32( qry );
     std::for_each( u32_str.begin(), u32_str.end(), u32_to_lowercase );
     std::for_each( u32_qry.begin(), u32_qry.end(), u32_to_lowercase );
     // First try match their lowercase forms
     if( u32_str.find( u32_qry ) != std::u32string::npos ) {
         return true;
     }
     // Then try removing accents from str ONLY
     std::for_each( u32_str.begin(), u32_str.end(), remove_accent );
     if( u32_str.find( u32_qry ) != std::u32string::npos ) {
         return true;
     }
     if( use_pinyin_search ) {
         // Finally, try to convert the string to pinyin and compare
         return pinyin::pinyin_match( u32_str, u32_qry );
     }
     return false;
 }
References pinyin::pinyin_match(), remove_accent(), u32_to_lowercase(), use_pinyin_search, and utf8_to_utf32().
Referenced by basic_item_filter(), debug_menu::change_spells(), veh_interact::do_install(), prof_window::filter(), input_context::filter_strings_by_phrase(), uilist::filterlist(), overmap::find_terrain(), overmapbuffer::get_extras(), read_inventory_preset::get_filter(), requirement_data::get_folded_list(), overmapbuffer::get_notes(), lcmatch(), match_include_exclude(), recipe_subset::search(), and worldfactory::show_worldgen_tab_modselection().
lcmatch() [2/2]
bool lcmatch (const translation & str, const std::string_view qry)
Definition at line 118 of file cata_utility.cpp.
 {
     return lcmatch( str.translated(), qry );
 }
References lcmatch(), and translation::translated().
logarithmic()
double logarithmic (double t)
Basic logistic function.
Calculates the value at a single point on a standard logistic curve.
Parameters
t Point on logistic curve to retrieve value for
Returns
Value of the logistic curve at the given point
Definition at line 161 of file cata_utility.cpp.
 {
     return 1 / ( 1 + std::exp( -t ) );
 }
Referenced by logarithmic_range().
logarithmic_range()
double logarithmic_range (int min, int max, int pos)
Normalized logistic function.
Generates a logistic curve on the domain [-6,6], then normalizes such that the value ranges from 1 to 0. A single point is then calculated on this curve.
Parameters
min t-value that should yield an output of 1 on the scaled curve.
max t-value that should yield an output of 0 on the scaled curve.
pos t-value to calculate the output for.
Returns
The value of the scaled logistic curve at point pos.
Definition at line 166 of file cata_utility.cpp.
 {
     const double LOGI_CUTOFF = 4;
     const double LOGI_MIN = logarithmic( -LOGI_CUTOFF );
     const double LOGI_MAX = logarithmic( +LOGI_CUTOFF );
     const double LOGI_RANGE = LOGI_MAX - LOGI_MIN;
     if( min >= max ) {
         debugmsg( "Invalid interval (%d, %d).", min, max );
         return 0.0;
     }
     // Anything beyond (min,max) gets clamped.
     if( pos <= min ) {
         return 1.0;
     } else if( pos >= max ) {
         return 0.0;
     }
     // Normalize the pos to [0,1]
     double range = max - min;
     double unit_pos = ( pos - min ) / range;
     // Scale and flip it to [+LOGI_CUTOFF,-LOGI_CUTOFF]
     double scaled_pos = LOGI_CUTOFF - 2 * LOGI_CUTOFF * unit_pos;
     // Get the raw logistic value.
     double raw_logistic = logarithmic( scaled_pos );
     // Scale the output to [0,1]
     return ( raw_logistic - LOGI_MIN ) / LOGI_RANGE;
 }
References debugmsg, logarithmic(), max(), min(), and math_opers::pos().
Referenced by Character::aim_per_move(), Character::block_hit(), player_morale::morale_point::get_net_bonus(), Character::get_stamina_dodge_modifier(), modified_sight_speed(), monster::plan(), and Character::update_bodytemp().
match_include_exclude()
bool match_include_exclude (std::string_view text, std::string filter)
Matches text case insensitive with the include/exclude rules of the filter.
Multiple includes/excludes are possible
Examle: bank,-house,tank,-car Will match text containing tank or bank while not containing house or car
Parameters
text String to be matched
filter String with include/exclude rules
Returns
true if include/exclude rules pass. See Example.
Definition at line 123 of file cata_utility.cpp.
 {
     size_t iPos;
     bool found = false;
     if( filter.empty() ) {
         return false;
     }
     do {
         iPos = filter.find( ',' );
         std::string term = iPos == std::string::npos ? filter : filter.substr( 0, iPos );
         const bool exclude = term.substr( 0, 1 ) == "-";
         if( exclude ) {
             term = term.substr( 1 );
         }
         if( ( !found || exclude ) && lcmatch( text, term ) ) {
             if( exclude ) {
                 return false;
             }
             found = true;
         }
         if( iPos != std::string::npos ) {
             filter = filter.substr( iPos + 1, filter.size() );
         }
     } while( iPos != std::string::npos );
     return found;
 }
References filter, and lcmatch().
Referenced by overmap::find_extras(), overmap::find_notes(), and overmap_ui::search().
modulo()
int modulo (int v, int m)
Definition at line 75 of file cata_utility.cpp.
 {
     // C++11: negative v and positive m result in negative v%m (or 0),
     // but this is supposed to be mathematical modulo: 0 <= v%m < m,
     const int r = v % m;
     // Adding m in that (and only that) case.
     return r >= 0 ? r : r + m;
 }
multi_lerp()
float multi_lerp (const std::vector< std::pair< float, float >> & points, float x)
From points, finds p1 and p2 such that p1.first < x < p2.first Then linearly interpolates between p1.second and p2.second and returns the result.
points should be sorted by first elements of the pairs. If x is outside range, returns second value of the first (if x < points[0].first) or last point.
Definition at line 267 of file cata_utility.cpp.
 {
     size_t i = 0;
     while( i < points.size() && points[i].first <= x ) {
         i++;
     }
     if( i == 0 ) {
         return points.front().second;
     } else if( i >= points.size() ) {
         return points.back().second;
     }
     // How far are we along the way from last threshold to current one
     const float t = ( x - points[i - 1].first ) /
                     ( points[i].first - points[i - 1].first );
     // Linear interpolation of values at relevant thresholds
     return ( t * points[i].second ) + ( ( 1 - t ) * points[i - 1].second );
 }
References second.
Referenced by damage_instance::di_considering_length(), islot_ammo::dispersion_considering_length(), Character::get_starvation(), Character::gun_value(), Character::kcal_speed_penalty(), Character::metabolic_rate(), and Character::thirst_speed_penalty().
obscure_message()
std::string obscure_message (const std::string & str, const std::function< char()> & f)
Apply fuzzy effect to a string like: Hello, world! --> H##lo, wurl#!
Parameters
str the original string to be processed
f the function that guides how to mess the message f() will be called for each character (lingual, not byte): [-] f() == -1 : nothing will be done [-] f() == 0 : the said character will be replace by a random character [-] f() == ch : the said character will be replace by ch
Returns
The processed string
Definition at line 606 of file cata_utility.cpp.
 {
     //~ translators: place some random 1-width characters here in your language if possible, or leave it as is
     std::string gibberish_narrow = _( "abcdefghijklmnopqrstuvwxyz" );
     std::string gibberish_wide =
         //~ translators: place some random 2-width characters here in your language if possible, or leave it as is
         _( "" );
     std::wstring w_gibberish_narrow = utf8_to_wstr( gibberish_narrow );
     std::wstring w_gibberish_wide = utf8_to_wstr( gibberish_wide );
     std::wstring w_str = utf8_to_wstr( str );
     // a trailing NULL terminator is necessary for utf8_width function
     // NOLINTNEXTLINE(modernize-avoid-c-arrays)
     char transformation[2] = { 0 };
     for( size_t i = 0; i < w_str.size(); ++i ) {
         transformation[0] = f();
         std::string this_char = wstr_to_utf8( std::wstring( 1, w_str[i] ) );
         // mk_wcwidth, which is used by utf8_width, might return -1 for some values, such as newlines 0x0A
         if( transformation[0] == -1 || utf8_width( this_char ) == -1 ) {
             // Leave unchanged
             continue;
         } else if( transformation[0] == 0 ) {
             // Replace with random character
             if( utf8_width( this_char ) == 1 ) {
                 w_str[i] = random_entry( w_gibberish_narrow );
             } else {
                 w_str[i] = random_entry( w_gibberish_wide );
             }
         } else {
             // Only support the case e.g. replace current character to symbols like # or ?
             if( utf8_width( transformation ) != 1 ) {
                 debugmsg( "target character isn't narrow" );
             }
             // A 2-width wide character in the original string should be replace by two narrow characters
             w_str.replace( i, 1, utf8_to_wstr( std::string( utf8_width( this_char ), transformation[0] ) ) );
         }
     }
     std::string result = wstr_to_utf8( w_str );
     if( utf8_width( str ) != utf8_width( result ) ) {
         debugmsg( "utf8_width differ between original string and obscured string" );
     }
     return result;
 }
References _, debugmsg, random_entry(), utf8_to_wstr(), utf8_width(), and wstr_to_utf8().
Referenced by iuse::radio_tick().
pow10()
static double pow10 (unsigned int n) static
Definition at line 40 of file cata_utility.cpp.
 {
     double ret = 1;
     double tmp = 10;
     while( n ) {
         if( n & 1 ) {
             ret *= tmp;
         }
         tmp *= tmp;
         n >>= 1;
     }
     return ret;
 }
References cata::hash64_detail::ret.
Referenced by round_up().
read_from_file() [1/3]
bool read_from_file (const cata_path & path, const std::function< void(std::istream &)> & reader)
Definition at line 447 of file cata_utility.cpp.
 {
     return read_from_file( path.get_unrelative_path(), reader );
 }
References cata_path::get_unrelative_path().
Referenced by build_resource_list(), get_playtime_from_save(), game::load(), read_from_file(), read_from_file_optional(), and sokoban_game::start_game().
read_from_file() [2/3]
bool read_from_file (const fs::path & path, const std::function< void(std::istream &)> & reader)
Definition at line 452 of file cata_utility.cpp.
 {
     std::unique_ptr<std::istream> finp = read_maybe_compressed_file( path );
     if( !finp ) {
         return false;
     }
     try {
         reader( *finp );
     } catch( const std::exception &err ) {
         debugmsg( _( "Failed to read from \"%1$s\": %2$s" ), path.generic_u8string().c_str(), err.what() );
         return false;
     }
     return true;
 }
References _, debugmsg, and read_maybe_compressed_file().
read_from_file() [3/3]
bool read_from_file (const std::string & path, const std::function< void(std::istream &)> & reader)
Try to open and read from given file using the given callback.
The file is opened for reading (binary mode), given to the callback (which does the actual reading) and closed. Any exceptions from the callbacks are caught and reported as debugmsg. If the stream is in a fail state (other than EOF) after the callback returns, it is handled as error as well.
The callback can either be a generic std::istream or a JsonIn stream (which has been initialized from the std::istream) or a JsonValue object.
The functions with the "_optional" prefix do not show a debug message when the file does not exist. They simply ignore the call and return false immediately (without calling the callback). They can be used for loading legacy files.
Returns
true is the file was read without any errors, false upon any error.
Definition at line 467 of file cata_utility.cpp.
 {
     return read_from_file( fs::u8path( path ), reader );
 }
References read_from_file().
read_from_file_json()
bool read_from_file_json (const cata_path & path, const std::function< void(const JsonValue &)> & reader)
Definition at line 562 of file cata_utility.cpp.
 {
     try {
         JsonValue jo = json_loader::from_path( path );
         reader( jo );
         return true;
     } catch( const std::exception &err ) {
         debugmsg( _( "Failed to read from \"%1$s\": %2$s" ), path.generic_u8string().c_str(),
                   err.what() );
         return false;
     }
 }
References _, debugmsg, json_loader::from_path(), and cata_path::generic_u8string().
Referenced by diary::load(), avatar::load_template(), read_from_file_optional_json(), and snippet_library::reload_names().
read_from_file_optional() [1/3]
bool read_from_file_optional (const cata_path & path, const std::function< void(std::istream &)> & reader)
Definition at line 594 of file cata_utility.cpp.
 {
     return read_from_file_optional( path.get_unrelative_path(), reader );
 }
References cata_path::get_unrelative_path(), and read_from_file_optional().
read_from_file_optional() [2/3]
bool read_from_file_optional (const fs::path & path, const std::function< void(std::istream &)> & reader)
Definition at line 585 of file cata_utility.cpp.
 {
     // Note: slight race condition here, but we'll ignore it. Worst case: the file
     // exists and got removed before reading it -> reading fails with a message
     // Or file does not exists, than everything works fine because it's optional anyway.
     return file_exist( path ) && read_from_file( path, reader );
 }
References file_exist(), and read_from_file().
read_from_file_optional() [3/3]
bool read_from_file_optional (const std::string & path, const std::function< void(std::istream &)> & reader)
Definition at line 576 of file cata_utility.cpp.
 {
     // Note: slight race condition here, but we'll ignore it. Worst case: the file
     // exists and got removed before reading it -> reading fails with a message
     // Or file does not exists, than everything works fine because it's optional anyway.
     return file_exist( path ) && read_from_file( path, reader );
 }
References file_exist(), and read_from_file().
Referenced by get_input_string_from_file(), main_menu::init_strings(), game::load(), main_menu::load_file(), load_keyboard_settings(), game::load_master(), overmap::open(), and read_from_file_optional().
read_from_file_optional_json()
bool read_from_file_optional_json (const cata_path & path, const std::function< void(const JsonValue &)> & reader)
Definition at line 600 of file cata_utility.cpp.
 {
     return file_exist( path.get_unrelative_path() ) && read_from_file_json( path, reader );
 }
References file_exist(), cata_path::get_unrelative_path(), and read_from_file_json().
Referenced by overmap::generate(), help::load(), options_manager::load(), panel_manager::load(), auto_notes::auto_note_settings::load(), auto_pickup::player_settings::load(), game::load(), color_manager::load_custom(), mod_manager::load_mod_info(), mod_manager::load_mods_list(), WORLD::load_options(), mod_manager::load_replacement_mods(), map_memory::load_submap(), zone_manager::load_world_zones(), zone_manager::load_zones(), and mapbuffer::unserialize_submaps().
read_maybe_compressed_file() [1/3]
std::unique_ptr<std::istream> read_maybe_compressed_file (const cata_path & path)
Definition at line 510 of file cata_utility.cpp.
 {
     return read_maybe_compressed_file( path.get_unrelative_path() );
 }
References cata_path::get_unrelative_path(), and read_maybe_compressed_file().
read_maybe_compressed_file() [2/3]
std::unique_ptr<std::istream> read_maybe_compressed_file (const fs::path & path)
Definition at line 477 of file cata_utility.cpp.
 {
     try {
         std::ifstream fin( path, std::ios::binary );
         if( !fin ) {
             throw std::runtime_error( "opening file failed" );
         }
         // check if file is gzipped
         // (byte1 == 0x1f) && (byte2 == 0x8b)
         std::array<char, 2> header;
         fin.read( header.data(), 2 );
         fin.clear();
         fin.seekg( 0, std::ios::beg ); // reset read position
         if( ( header[0] == '\x1f' ) && ( header[1] == '\x8b' ) ) {
             std::string outstring = read_compressed_file_to_string( fin );
             std::stringstream inflated_contents_stream;
             inflated_contents_stream.write( outstring.data(), outstring.size() );
             return std::make_unique<std::stringstream>( std::move( inflated_contents_stream ) );
         } else {
             return std::make_unique<std::ifstream>( std::move( fin ) );
         }
         if( fin.bad() ) {
             throw std::runtime_error( "reading file failed" );
         }
     } catch( const std::exception &err ) {
         debugmsg( _( "Failed to read from \"%1$s\": %2$s" ), path.generic_u8string().c_str(), err.what() );
     }
     return nullptr;
 }
References _, debugmsg, and anonymous_namespace{cata_utility.cpp}::read_compressed_file_to_string().
read_maybe_compressed_file() [3/3]
std::unique_ptr<std::istream> read_maybe_compressed_file (const std::string & path)
Try to open and provide a std::istream for the given, possibly, gzipped, file.
The file is opened for reading (binary mode) and tested to see if it is compressed. Compressed files are decompressed into a std::stringstream and returned. Uncompressed files are returned as normal lazy ifstreams. Any exceptions during reading, including failing to open the file, are reported as dbgmsg.
Returns
A unique_ptr of the appropriate istream, or nullptr on failure.
Definition at line 472 of file cata_utility.cpp.
 {
     return read_maybe_compressed_file( fs::u8path( path ) );
 }
Referenced by file_flexbuffer::get_source_stream(), read_from_file(), and read_maybe_compressed_file().
read_whole_file() [1/3]
std::optional<std::string> read_whole_file (const cata_path & path)
Definition at line 557 of file cata_utility.cpp.
 {
     return read_whole_file( path.get_unrelative_path() );
 }
References cata_path::get_unrelative_path(), and read_whole_file().
read_whole_file() [2/3]
std::optional<std::string> read_whole_file (const fs::path & path)
Definition at line 520 of file cata_utility.cpp.
 {
     std::string outstring;
     try {
         std::ifstream fin( path, std::ios::binary );
         if( !fin ) {
             throw std::runtime_error( "opening file failed" );
         }
         // check if file is gzipped
         // (byte1 == 0x1f) && (byte2 == 0x8b)
         std::array<char, 2> header;
         fin.read( header.data(), 2 );
         fin.clear();
         fin.seekg( 0, std::ios::beg ); // reset read position
         if( ( header[0] == '\x1f' ) && ( header[1] == '\x8b' ) ) {
             outstring = read_compressed_file_to_string( fin );
         } else {
             fin.seekg( 0, std::ios_base::end );
             std::streamoff size = fin.tellg();
             fin.seekg( 0 );
             outstring.resize( size );
             fin.read( outstring.data(), size );
         }
         if( fin.bad() ) {
             throw std::runtime_error( "reading file failed" );
         }
         return std::optional<std::string>( std::move( outstring ) );
     } catch( const std::exception &err ) {
         debugmsg( _( "Failed to read from \"%1$s\": %2$s" ), path.generic_u8string().c_str(), err.what() );
     }
     return std::nullopt;
 }
References _, debugmsg, keycode::end, anonymous_namespace{cata_utility.cpp}::read_compressed_file_to_string(), and om_direction::size.
read_whole_file() [3/3]
std::optional<std::string> read_whole_file (const std::string & path)
Try to open and read the entire file to a string.
The file is opened for reading (binary mode), read into a string, and then closed. Any exceptions during reading, including failing to open the file, are reported as dbgmsg.
Returns
A nonempty optional with the contents of the file on success, or std::nullopt on failure.
Definition at line 515 of file cata_utility.cpp.
 {
     return read_whole_file( fs::u8path( path ) );
 }
Referenced by flexbuffer_cache::parse_and_cache(), and read_whole_file().
round_up()
double round_up (double val, unsigned int dp)
Round a value up at a given decimal place.
Parameters
val Value to be rounded.
dp Decimal place to round the value at.
Returns
Rounded value.
Definition at line 54 of file cata_utility.cpp.
 {
     // Some implementations of std::pow does not return the accurate result even
     // for small powers of 10, so we use a specialized routine to calculate them.
     const double denominator = pow10( dp );
     return std::ceil( denominator * val ) / denominator;
 }
References ceil(), and pow10().
Referenced by armor_inventory_preset::armor_inventory_preset(), veh_interact::calc_overview(), comestible_inventory_preset::comestible_inventory_preset(), Character::compute_calories_per_effective_volume(), inventory_selector::get_weight_and_length_stat(), liquid_handler::perform_liquid_transfer(), pick_part(), vehicle::print_part_list(), and vol_to_info().
safe_getline()
std::istream& safe_getline (std::istream & ins, std::string & str)
Definition at line 364 of file cata_utility.cpp.
 {
     str.clear();
     std::istream::sentry se( ins, true );
     std::streambuf *sb = ins.rdbuf();
     while( true ) {
         int c = sb->sbumpc();
         switch( c ) {
             case '\n':
                 return ins;
             case '\r':
                 if( sb->sgetc() == '\n' ) {
                     sb->sbumpc();
                 }
                 return ins;
             case EOF:
                 if( str.empty() ) {
                     ins.setstate( std::ios::eofbit );
                 }
                 return ins;
             default:
                 str += static_cast<char>( c );
         }
     }
 }
References c.
Referenced by sokoban_game::parse_level().
serialize_wrapper()
std::string serialize_wrapper (const std::function< void(JsonOut &)> & callback)
@group JSON (de)serialization wrappers.
The functions here provide a way to (de)serialize objects without actually including "json.h". The *_wrapper function create the JSON stream instances and therefore require "json.h", but the caller doesn't. Callers should just forward the stream reference to the actual (de)serialization function.
The inline function do this by calling T::(de)serialize (which is assumed to exist with the proper signature).
Exceptions
std::exception Deserialization functions may throw upon malformed JSON or unexpected/invalid content.
Definition at line 649 of file cata_utility.cpp.
 {
     std::ostringstream buffer;
     JsonOut jsout( buffer );
     callback( jsout );
     return buffer.str();
 }
Referenced by map_memory::save(), and serialize().
string_empty_or_whitespace()
bool string_empty_or_whitespace (const std::string & s)
Definition at line 664 of file cata_utility.cpp.
 {
     if( s.empty() ) {
         return true;
     }
     std::wstring ws = utf8_to_wstr( s );
     return std::all_of( ws.begin(), ws.end(), []( const wchar_t &c ) {
         return std::iswspace( c );
     } );
 }
References c, and utf8_to_wstr().
Referenced by widget::layout().
string_split()
std::vector<std::string> string_split (std::string_view string, char delim)
Splits a string by delimiter into a vector of strings.
keyword: explode
Definition at line 703 of file cata_utility.cpp.
 {
     std::vector<std::string> elems;
     if( string.empty() ) {
         return elems; // Well, that was easy.
     }
     std::stringstream ss( std::string{ string } );
     std::string item;
     while( std::getline( ss, item, delim ) ) {
         elems.push_back( item );
     }
     if( string.back() == delim ) {
         elems.emplace_back( "" );
     }
     return elems;
 }
Referenced by check_special_rule(), past_games_info::ensure_loaded(), item::get_saved_recipes(), item::get_var(), gettext_gendered(), widget::layout(), debug_menu::teleport_overmap(), and wildcard_match().
string_view_cmp()
int string_view_cmp (std::string_view l, std::string_view r)
strcmp, but for string_view objects.
In C++20 this can be replaced with operator<=>
Definition at line 676 of file cata_utility.cpp.
 {
     size_t min_len = std::min( l.size(), r.size() );
     int result = memcmp( l.data(), r.data(), min_len );
     if( result ) {
         return result;
     }
     if( l.size() == r.size() ) {
         return 0;
     }
     return l.size() < r.size() ? -1 : 1;
 }
References min().
Referenced by JsonObject::find_map_key_idx().
svto()
template<typename Integer > Integer svto (const std::string_view s)
Definition at line 690 of file cata_utility.cpp.
 {
     Integer result = 0;
     const char *end = s.data() + s.size();
     std::from_chars_result r = std::from_chars( s.data(), end, result );
     if( r.ptr != end ) {
         cata_fatal( "could not parse string_view as an integer" );
     }
     return result;
 }
References cata_fatal, and keycode::end.
svto< int >()
template int svto< int > (std::string_view)
Referenced by string_to_ml().
svtod()
std::optional<double> svtod (std::string_view token)
Definition at line 881 of file cata_utility.cpp.
 {
     char *pEnd = nullptr;
     double const val = std::strtod( token.data(), &pEnd );
     if( pEnd == token.data() + token.size() ) {
         return { val };
     }
     errno = 0;
     return std::nullopt;
 }
Referenced by diag_value::dbl(), var::eval(), and anonymous_namespace{math_parser.cpp}::get_number().
velocity_units()
const char* velocity_units (units_type vel_units)
Create a units label for a velocity value.
Gives the name of the velocity unit in the user selected unit system, either "km/h", "ms/s" or "mph". Used to add abbreviated unit labels to the output of convert_velocity.
Parameters
vel_units type of velocity desired (i.e. wind or vehicle)
Returns
name of unit.
Definition at line 210 of file cata_utility.cpp.
 {
     if( get_option<std::string>( "USE_METRIC_SPEEDS" ) == "mph" ) {
         return _( "mph" );
     } else if( get_option<std::string>( "USE_METRIC_SPEEDS" ) == "t/t" ) {
         //~ vehicle speed tiles per turn
         return _( "t/t" );
     } else {
         switch( vel_units ) {
             case VU_VEHICLE:
                 return _( "km/h" );
             case VU_WIND:
                 return _( "m/s" );
         }
     }
     return "error: unknown units!";
 }
References _, VU_VEHICLE, and VU_WIND.
Referenced by Character::activate_bionic(), veh_interact::display_stats(), iuse::weather_tool(), and debug_menu::wind_speed().
write_to_file() [1/4]
void write_to_file (const cata_path & path, const std::function< void(std::ostream &)> & writer)
Definition at line 318 of file cata_utility.cpp.
 {
     // Any of the below may throw. ofstream_wrapper will clean up the temporary path on its own.
     ofstream_wrapper fout( path.get_unrelative_path(), std::ios::binary );
     writer( fout.stream() );
     fout.close();
 }
References ofstream_wrapper::close(), cata_path::get_unrelative_path(), and ofstream_wrapper::stream().
write_to_file() [2/4]
bool write_to_file (const cata_path & path, const std::function< void(std::ostream &)> & writer, const char *const fail_message)
Definition at line 326 of file cata_utility.cpp.
 {
     try {
         write_to_file( path, writer );
         return true;
     } catch( const std::exception &err ) {
         if( fail_message ) {
             const std::string msg =
                 string_format( _( "Failed to write %1$s to \"%2$s\": %3$s" ),
                                fail_message, path.generic_u8string(), err.what() );
             if( test_mode ) {
                 DebugLog( D_ERROR, DC_ALL ) << msg;
             } else {
                 popup( "%s", msg );
             }
         }
         return false;
     }
 }
References _, D_ERROR, DC_ALL, DebugLog(), cata_path::generic_u8string(), popup(), string_format(), test_mode, and write_to_file().
write_to_file() [3/4]
void write_to_file (const std::string & path, const std::function< void(std::ostream &)> & writer)
Definition at line 288 of file cata_utility.cpp.
 {
     // Any of the below may throw. ofstream_wrapper will clean up the temporary path on its own.
     ofstream_wrapper fout( fs::u8path( path ), std::ios::binary );
     writer( fout.stream() );
     fout.close();
 }
References ofstream_wrapper::close(), and ofstream_wrapper::stream().
Referenced by debug_menu::character_edit_menu(), copy_file(), debug_menu::debug(), edit_json(), npc::export_to(), debug_menu::generate_effect_list(), game::save(), input_manager::save(), panel_manager::save(), options_manager::save(), overmap::save(), auto_notes::auto_note_settings::save(), auto_pickup::player_settings::save(), safemode::save(), WORLD::save(), map_memory::save(), game::save_achievements(), color_manager::save_custom(), game::save_factions_missions_npcs(), worldfactory::save_last_world_info(), mod_manager::save_mods_list(), game::save_player_data(), item_pocket::save_presets(), mapbuffer::save_quad(), avatar::save_template(), zone_manager::save_world_zones(), zone_manager::save_zones(), mod_manager::set_default_mods(), diary::store(), weather_generator::test_weather(), debug_menu::vehicle_export(), debug_menu::write_city_list(), effect_on_conditions::write_eocs_to_file(), effect_on_conditions::write_global_eocs_to_file(), debug_menu::write_global_vars(), game::write_memorial_file(), and write_to_file().
write_to_file() [4/4]
bool write_to_file (const std::string & path, const std::function< void(std::ostream &)> & writer, const char * fail_message)
Open a file for writing, calls the writer on that stream.
If the writer throws, or if the file could not be opened or if any I/O error happens, the function shows a popup containing the fail_message, the error text and the path.
Returns
Whether saving succeeded (no error was caught).
Exceptions
The void function throws when writing fails or when the writer throws. The other function catches all exceptions and returns false.
Definition at line 296 of file cata_utility.cpp.
 {
     try {
         write_to_file( path, writer );
         return true;
     } catch( const std::exception &err ) {
         if( fail_message ) {
             const std::string msg =
                 string_format( _( "Failed to write %1$s to \"%2$s\": %3$s" ),
                                fail_message, path, err.what() );
             if( test_mode ) {
                 DebugLog( D_ERROR, DC_ALL ) << msg;
             } else {
                 popup( "%s", msg );
             }
         }
         return false;
     }
 }
References _, D_ERROR, DC_ALL, DebugLog(), popup(), string_format(), test_mode, and write_to_file().