Cataclysm DDA: src/character_morale.cpp File Reference
character_morale.cpp File Reference
#include <cmath>
#include <list>
#include <map>
#include <memory>
#include <unordered_map>
#include <utility>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "character_attire.h"
#include "coordinates.h"
#include "debug.h"
#include "effect.h"
#include "map_iterator.h"
#include "messages.h"
#include "morale.h"
#include "morale_types.h"
#include "pimpl.h"
#include "type_id.h"
#include "units.h"
Variables
static const efftype_id effect_took_prozac ("took_prozac")
static const efftype_id effect_took_xanax ("took_xanax")
static const itype_id itype_foodperson_mask ("foodperson_mask")
static const itype_id itype_foodperson_mask_on ("foodperson_mask_on")
static const trait_id trait_HOARDER ("HOARDER")
static const trait_id trait_NOMAD ("NOMAD")
static const trait_id trait_NOMAD2 ("NOMAD2")
static const trait_id trait_NOMAD3 ("NOMAD3")
static const trait_id trait_PROF_FOODP ("PROF_FOODP")
static const trait_id trait_THRESH_SPECIES_RAVENFOLK ("THRESH_SPECIES_RAVENFOLK")
Variable Documentation
effect_took_prozac
const efftype_id effect_took_prozac("took_prozac") ("took_prozac") static
Referenced by Character::hoarder_morale_penalty().
effect_took_xanax
const efftype_id effect_took_xanax("took_xanax") ("took_xanax") static
Referenced by Character::hoarder_morale_penalty().
itype_foodperson_mask
const itype_id itype_foodperson_mask("foodperson_mask") ("foodperson_mask") static
Referenced by Character::apply_persistent_morale().
itype_foodperson_mask_on
const itype_id itype_foodperson_mask_on("foodperson_mask_on") ("foodperson_mask_on") static
Referenced by Character::apply_persistent_morale().
trait_HOARDER
const trait_id trait_HOARDER("HOARDER") ("HOARDER") static
Referenced by Character::apply_persistent_morale().
trait_NOMAD
const trait_id trait_NOMAD("NOMAD") ("NOMAD") static
Referenced by Character::apply_persistent_morale().
trait_NOMAD2
const trait_id trait_NOMAD2("NOMAD2") ("NOMAD2") static
Referenced by Character::apply_persistent_morale().
trait_NOMAD3
const trait_id trait_NOMAD3("NOMAD3") ("NOMAD3") static
Referenced by Character::apply_persistent_morale().
trait_PROF_FOODP
const trait_id trait_PROF_FOODP("PROF_FOODP") ("PROF_FOODP") static
Referenced by Character::apply_persistent_morale().
trait_THRESH_SPECIES_RAVENFOLK
const trait_id trait_THRESH_SPECIES_RAVENFOLK("THRESH_SPECIES_RAVENFOLK") ("THRESH_SPECIES_RAVENFOLK") static
Referenced by Character::hoarder_morale_penalty().