Cataclysm DDA: src/character_id.h File Reference
character_id.h File Reference
#include <iosfwd>
Classes
class character_id
Macros
#define CATA_SRC_CHARACTER_ID_H
Functions
bool operator== (character_id l, character_id r)
bool operator!= (character_id l, character_id r)
bool operator< (character_id l, character_id r)
std::ostream & operator<< (std::ostream &o, character_id id)
Macro Definition Documentation
CATA_SRC_CHARACTER_ID_H
#define CATA_SRC_CHARACTER_ID_H
Definition at line 3 of file character_id.h.
Function Documentation
operator!=()
bool operator!= (character_id l, character_id r) inline
Definition at line 42 of file character_id.h.
 {
     return l.get_value() != r.get_value();
 }
References character_id::get_value().
operator<()
bool operator< (character_id l, character_id r) inline
Definition at line 47 of file character_id.h.
 {
     return l.get_value() < r.get_value();
 }
References character_id::get_value().
operator<<()
std::ostream& operator<< (std::ostream & o, character_id id)
Definition at line 5 of file character_id.cpp.
 {
     return o << id.get_value();
 }
operator==()
bool operator== (character_id l, character_id r) inline
Definition at line 37 of file character_id.h.
 {
     return l.get_value() == r.get_value();
 }
References character_id::get_value().