Cataclysm DDA: src/character.h File Reference
character.h File Reference
#include <algorithm>
#include <bitset>
#include <climits>
#include <cstdint>
#include <functional>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <queue>
#include <set>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "activity_tracker.h"
#include "activity_type.h"
#include "addiction.h"
#include "body_part_set.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character_attire.h"
#include "character_id.h"
#include "city.h"
#include "compatibility.h"
#include "coordinates.h"
#include "craft_command.h"
#include "creature.h"
#include "damage.h"
#include "enums.h"
#include "flat_set.h"
#include "game_constants.h"
#include "inventory.h"
#include "item.h"
#include "item_location.h"
#include "magic_enchantment.h"
#include "pimpl.h"
#include "player_activity.h"
#include "pocket_type.h"
#include "point.h"
#include "ranged.h"
#include "ret_val.h"
#include "safe_reference.h"
#include "stomach.h"
#include "string_formatter.h"
#include "subbodypart.h"
#include "type_id.h"
#include "units.h"
#include "visitable.h"
#include "weakpoint.h"
#include "weighted_list.h"
Classes
struct enum_traits< blood_type >
struct queued_eoc
struct eoc_compare
struct queued_eocs
struct queued_eocs::eoc_compare
struct aim_type
struct parallax_cache
struct aim_mods_cache
struct special_attack
struct consumption_event
struct stat_mod
struct enum_traits< read_condition_result >
struct ret_val< T >::default_success
struct ret_val< T >::default_failure
struct needs_rates
struct pocket_data_with_parent
struct speed_bonus_effect
struct run_cost_effect
class Character
struct Character::comfort_response_t
struct Character::has_mission_item_filter
struct Character::item_tweaks
Sometimes we need to calculate hypothetical volume or weight.
struct Character::craft_roll_data
struct Character::trait_data
struct Character::crafting_cache_type
struct Character::inv_search_cache
Cached results for functions that search through the inventory, like cache_visit_items_with.
struct enum_traits< character_stat >
Namespaces
catacurses
Contains the curses interface used by the whole game.
Macros
#define CATA_SRC_CHARACTER_H
Typedefs
using drop_location = int std::pair< item_location, int >
using drop_locations = std::list< drop_location >
using bionic_uid = unsigned int
Enumerations
enum vision_modes {
DEBUG_NIGHTVISION , NV_GOGGLES , NIGHTVISION_1 , NIGHTVISION_2 ,
NIGHTVISION_3 , FULL_ELFA_VISION , ELFA_VISION , CEPH_VISION ,
FELINE_VISION , BIRD_EYE , URSINE_VISION , BOOMERED ,
DARKNESS , IR_VISION , VISION_CLAIRVOYANCE , VISION_CLAIRVOYANCE_PLUS ,
VISION_CLAIRVOYANCE_SUPER , NUM_VISION_MODES
}
type of conditions that effect vision
enum class sleepiness_levels : int { TIRED = 191 , DEAD_TIRED = 383 , EXHAUSTED = 575 , MASSIVE_SLEEPINESS = 1000 }
enum sleep_deprivation_levels {
SLEEP_DEPRIVATION_HARMLESS = 2 * 24 * 60 , SLEEP_DEPRIVATION_MINOR = 4 * 24 * 60 , SLEEP_DEPRIVATION_SERIOUS = 7 * 24 * 60 , SLEEP_DEPRIVATION_MAJOR = 10 * 24 * 60 ,
SLEEP_DEPRIVATION_MASSIVE = 14 * 24 * 60
}
five levels of consequences for days without sleep
enum class blood_type {
blood_O , blood_A , blood_B , blood_AB ,
num_bt
}
enum edible_rating {
EDIBLE , INEDIBLE , INEDIBLE_MUTATION , ALLERGY ,
ALLERGY_WEAK , CANNIBALISM , PARASITES , ROTTEN ,
NAUSEA , TOO_FULL , NO_TOOL
}
how digestible or palatable an item is
enum crush_tool_type { CRUSH_EMPTY_HANDS , CRUSH_HAMMER , CRUSH_DRILL_OR_HAMMER_AND_SCREW , CRUSH_NO_TOOL }
enum class character_stat : char {
STRENGTH , DEXTERITY , INTELLIGENCE , PERCEPTION ,
DUMMY_STAT
}
Four ability stats available on character creation.
enum class customize_appearance_choice : int { EYES , HAIR , HAIR_F , SKIN }
enum class book_mastery { CANT_DETERMINE , CANT_UNDERSTAND , LEARNING , MASTERED }
enum class read_condition_result {
SUCCESS = 0 , NOT_BOOK = 1 << 0 , CANT_UNDERSTAND = 1 << 1 , MASTERED = 1 << 2 ,
DRIVING = 1 << 3 , ILLITERATE = 1 << 4 , NEED_GLASSES = 1 << 5 , TOO_DARK = 1 << 6 ,
MORALE_LOW = 1 << 7 , BLIND = 1 << 8
}
Functions
constexpr bool operator>= (const sleepiness_levels &lhs, const sleepiness_levels &rhs)
constexpr bool operator< (const sleepiness_levels &lhs, const sleepiness_levels &rhs)
template<typename T >
constexpr bool operator>= (const T &lhs, const sleepiness_levels &rhs)
template<typename T >
constexpr bool operator> (const T &lhs, const sleepiness_levels &rhs)
template<typename T >
constexpr bool operator<= (const T &lhs, const sleepiness_levels &rhs)
template<typename T >
constexpr bool operator< (const T &lhs, const sleepiness_levels &rhs)
template<typename T >
constexpr int operator/ (const sleepiness_levels &lhs, const T &rhs)
template<typename T >
constexpr int operator+ (const sleepiness_levels &lhs, const T &rhs)
template<typename T >
constexpr int operator- (const sleepiness_levels &lhs, const T &rhs)
template<typename T >
constexpr int operator- (const T &lhs, const sleepiness_levels &rhs)
social_modifiers operator+ (social_modifiers lhs, const social_modifiers &rhs)
Character & get_player_character ()
std::string get_stat_name (character_stat Stat)
Get translated name of a stat.
Variables
constexpr int MAX_CLAIRVOYANCE = 40
constexpr float KCAL_PER_KG = 3500 * 2.20462
const std::unordered_map< std::string, sleepiness_levels > sleepiness_level_strs
Macro Definition Documentation
CATA_SRC_CHARACTER_H
#define CATA_SRC_CHARACTER_H
Definition at line 3 of file character.h.
Typedef Documentation
bionic_uid
using bionic_uid = unsigned int
Definition at line 123 of file character.h.
drop_location
using drop_location = int std::pair<item_location, int> strong
Definition at line 120 of file character.h.
drop_locations
using drop_locations = std::list<drop_location>
Definition at line 121 of file character.h.
Enumeration Type Documentation
blood_type
enum blood_type strong
Enumerator
blood_O
blood_A
blood_B
blood_AB
num_bt
Definition at line 249 of file character.h.
                       {
     blood_O,
     blood_A,
     blood_B,
     blood_AB,
     num_bt
 };
book_mastery
enum book_mastery strong
Enumerator
CANT_DETERMINE
CANT_UNDERSTAND
LEARNING
MASTERED
Definition at line 452 of file character.h.
{
     CANT_DETERMINE, // book not yet identified, so you don't know yet
     CANT_UNDERSTAND, // does not have enough skill to read
     LEARNING,
     MASTERED // can no longer increase skill by reading
 };
character_stat
enum character_stat : char strong
Four ability stats available on character creation.
Default is 8. Minimum value is 4 and 14 is considered to be max human value.
Enumerator
STRENGTH
DEXTERITY
INTELLIGENCE
PERCEPTION
DUMMY_STAT
Definition at line 437 of file character.h.
                           : char {
     STRENGTH,
     DEXTERITY,
     INTELLIGENCE,
     PERCEPTION,
     DUMMY_STAT
 };
crush_tool_type
enum crush_tool_type
Enumerator
CRUSH_EMPTY_HANDS
CRUSH_HAMMER
CRUSH_DRILL_OR_HAMMER_AND_SCREW
CRUSH_NO_TOOL
Definition at line 290 of file character.h.
                      {
     CRUSH_EMPTY_HANDS,
     CRUSH_HAMMER,
     CRUSH_DRILL_OR_HAMMER_AND_SCREW,
     CRUSH_NO_TOOL
 };
customize_appearance_choice
enum customize_appearance_choice : int strong
Enumerator
EYES
HAIR
HAIR_F
SKIN
Definition at line 445 of file character.h.
                                        : int {
     EYES, // customize eye color
     HAIR, // customize hair
     HAIR_F, // customize facial hair
     SKIN  // customize skin color
 };
edible_rating
enum edible_rating
how digestible or palatable an item is
This tries to represent both rating and character's decision to respect said rating (ie "they can eat it, though they are disgusted by it")
Enumerator
EDIBLE
Edible or we pretend it is.
INEDIBLE
Not food at all.
INEDIBLE_MUTATION
Not food because character has mutated mouth/system.
ALLERGY
You can eat it, but it will hurt morale because of negative trait such as Hates Fruit.
ALLERGY_WEAK
Smaller allergy penalty.
CANNIBALISM
Penalty for eating human flesh (unless psycho/cannibal)
PARASITES
Comestible has parasites.
ROTTEN
Rotten (or, for saprophages, not rotten enough)
NAUSEA
Can provoke vomiting if you already feel nauseous.
TOO_FULL
We can eat this, but we'll suffer from overeat.
NO_TOOL
Some weird stuff that requires a tool we don't have.
Definition at line 265 of file character.h.
                    {
     /// Edible or we pretend it is
     EDIBLE,
     /// Not food at all
     INEDIBLE,
     /// Not food because character has mutated mouth/system
     INEDIBLE_MUTATION,
     /// You can eat it, but it will hurt morale because of negative trait such as Hates Fruit
     ALLERGY,
     /// Smaller allergy penalty
     ALLERGY_WEAK,
     /// Penalty for eating human flesh (unless psycho/cannibal)
     CANNIBALISM,
     /// Comestible has parasites
     PARASITES,
     /// Rotten (or, for saprophages, not rotten enough)
     ROTTEN,
     /// Can provoke vomiting if you already feel nauseous.
     NAUSEA,
     /// We can eat this, but we'll suffer from overeat
     TOO_FULL,
     /// Some weird stuff that requires a tool we don't have
     NO_TOOL
 };
read_condition_result
enum read_condition_result strong
Enumerator
SUCCESS
NOT_BOOK
CANT_UNDERSTAND
MASTERED
DRIVING
ILLITERATE
NEED_GLASSES
TOO_DARK
MORALE_LOW
BLIND
Definition at line 459 of file character.h.
{
     SUCCESS = 0,
     NOT_BOOK = 1 << 0,
     CANT_UNDERSTAND = 1 << 1,
     MASTERED = 1 << 2,
     DRIVING = 1 << 3,
     ILLITERATE = 1 << 4,
     NEED_GLASSES = 1 << 5,
     TOO_DARK = 1 << 6,
     MORALE_LOW = 1 << 7,
     BLIND = 1 << 8
 };
sleep_deprivation_levels
enum sleep_deprivation_levels
five levels of consequences for days without sleep
Sleep deprivation, distinct from sleepiness, is defined in minutes. Although most calculations scale linearly, malus is bestowed only upon reaching the tiers defined below.
Note
Sleep deprivation increases sleepiness. Sleepiness increase scales with the severity of sleep deprivation.
Sleep deprivation kicks in if lack of sleep is avoided with stimulants or otherwise for long periods of time
See also
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L5566
Enumerator
SLEEP_DEPRIVATION_HARMLESS
2 days
SLEEP_DEPRIVATION_MINOR
4 days
SLEEP_DEPRIVATION_SERIOUS
7 days
SLEEP_DEPRIVATION_MAJOR
10 days
SLEEP_DEPRIVATION_MASSIVE
14 days
Definition at line 236 of file character.h.
{
     /// 2 days
     SLEEP_DEPRIVATION_HARMLESS = 2 * 24 * 60,
     /// 4 days
     SLEEP_DEPRIVATION_MINOR = 4 * 24 * 60,
     /// 7 days
     SLEEP_DEPRIVATION_SERIOUS = 7 * 24 * 60,
     /// 10 days
     SLEEP_DEPRIVATION_MAJOR = 10 * 24 * 60,
     /// 14 days
     SLEEP_DEPRIVATION_MASSIVE = 14 * 24 * 60
 };
sleepiness_levels
enum sleepiness_levels : int strong
Enumerator
TIRED
DEAD_TIRED
EXHAUSTED
MASSIVE_SLEEPINESS
Definition at line 155 of file character.h.
                              : int {
     TIRED = 191,
     DEAD_TIRED = 383,
     EXHAUSTED = 575,
     MASSIVE_SLEEPINESS = 1000
 };
vision_modes
enum vision_modes
type of conditions that effect vision
Note
vision modes do not necessarily match json ids or flags
Enumerator
DEBUG_NIGHTVISION
NV_GOGGLES
NIGHTVISION_1
NIGHTVISION_2
NIGHTVISION_3
FULL_ELFA_VISION
ELFA_VISION
CEPH_VISION
FELINE_VISION
mutate w/ id "FEL_NV" & name "Feline Vision" see pretty well at night
BIRD_EYE
Bird mutation named "Avian Eyes": Perception +4.
URSINE_VISION
mutate w/ id "URSINE_EYE" & name "Ursine Vision" see better in dark, nearsight in light
BOOMERED
DARKNESS
IR_VISION
VISION_CLAIRVOYANCE
VISION_CLAIRVOYANCE_PLUS
VISION_CLAIRVOYANCE_SUPER
NUM_VISION_MODES
Definition at line 131 of file character.h.
                   {
     DEBUG_NIGHTVISION,
     NV_GOGGLES,
     NIGHTVISION_1,
     NIGHTVISION_2,
     NIGHTVISION_3,
     FULL_ELFA_VISION,
     ELFA_VISION,
     CEPH_VISION,
     /// mutate w/ id "FEL_NV" & name "Feline Vision" see pretty well at night
     FELINE_VISION,
     /// Bird mutation named "Avian Eyes": Perception +4
     BIRD_EYE,
     /// mutate w/ id "URSINE_EYE" & name "Ursine Vision" see better in dark, nearsight in light
     URSINE_VISION,
     BOOMERED,
     DARKNESS,
     IR_VISION,
     VISION_CLAIRVOYANCE,
     VISION_CLAIRVOYANCE_PLUS,
     VISION_CLAIRVOYANCE_SUPER,
     NUM_VISION_MODES
 };
Function Documentation
get_player_character()
Character& get_player_character ()
Definition at line 13807 of file game.cpp.
 {
     return g->u;
 }
Referenced by anonymous_namespace{item.cpp}::_stacks_location_hint(), mattack::absorb_meat(), npc::act_on_danger_assessment(), vehicle::act_on_map(), act_vehicle_unload_fuel(), computer_session::action_amigara_log(), computer_session::action_blood_anal(), computer_session::action_cascade(), computer_session::action_close_gate(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_deactivate_shock_vent(), computer_session::action_download_software(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), computer_session::action_irradiator(), computer_session::action_list_bionics(), computer_session::action_lock(), computer_session::action_map_sewer(), computer_session::action_map_subway(), computer_session::action_maps(), computer_session::action_miss_launch(), computer_session::action_open(), computer_session::action_open_gate(), computer_session::action_radio_archive(), computer_session::action_release(), computer_session::action_release_bionics(), computer_session::action_research(), computer_session::action_sample(), computer_session::action_shutters(), computer_session::action_srcf_elevator(), computer_session::action_srcf_seal(), computer_session::action_terminate(), computer_session::action_toll(), computer_session::action_unlock(), computer_session::activate_function(), mission_data::add(), memorial_logger::add(), timed_event_manager::add(), anonymous_namespace{monexamine.cpp}::add_armor(), map::add_camp(), talker_character::add_effect(), map::add_field(), inventory::add_item(), anonymous_namespace{monexamine.cpp}::add_leash(), npc::address_needs(), npc::address_player(), item::ammo_capacity(), veh_app_interact::app_loop(), map::apparent_light_at(), apply_ammo_effects(), apply_camp_ownership(), projectile::apply_effects_damage(), armor_encumb_header_info(), item::armor_fit_info(), item::armor_info(), npc::assess_danger(), assign_veh_to_follow(), monster::attack_at(), npc::attitude_to(), Creature::auto_find_hostile_target(), vehicle::automatic_fire_turret(), Pickup::autopickup(), talk_function::bionic_install(), talk_function::bionic_install_allies(), bionic_manip_cos(), talk_function::bionic_remove(), mattack::blow_whistle(), trapfunc::board(), board_up(), mattack::boomer(), mattack::boomer_glow(), mattack::brandish(), mattack::browse(), vehicle::build_bike_rack_menu(), vehicle::build_interact_menu(), map::build_map_cache(), map::build_vision_transparency_cache(), start_location::burn(), butcher_time_to_cut(), talk_function::buy_haircut(), talk_function::buy_shave(), veh_interact::cache_tool_availability(), veh_interact::cache_tool_availability_update_lifting(), melee_actor::call(), mattack::callblobs(), trapfunc::caltrops(), basecamp::camp_food_supply(), computer_session::can_activate(), can_butcher_at(), can_construct(), can_do_activity_there(), vehicle::can_enable(), can_examine_at(), Character::can_install_bionics(), can_interact_at(), requirement_data::can_make_with_inventory(), can_move_vertical_at(), veh_interact::can_potentially_install(), veh_app_interact::can_siphon(), Character::can_uninstall_bionic(), talk_function::caravan_dist(), talk_function::caravan_return(), talk_function::carpenter_return(), cast_spell(), trapfunc::cast_spell(), iexamine::chainfence(), change_armor_sprite(), debug_menu::change_spells(), mattack::chickenbot(), choose_adjacent(), choose_direction(), choose_direction_rel_ms(), basecamp::choose_new_leader(), ui::omap::choose_point(), close(), item::color_in_inventory(), colorized_trap_name_at(), comestible_inventory_preset::comestible_inventory_preset(), talk_function::companion_choose(), talk_function::companion_choose_return(), talk_function::companion_mission(), talk_function::companion_return(), npc::complain(), npc::complain_about(), construction_color(), npc::consume_food_from_camp(), vehicle::consume_fuel(), vehicle::control_doors(), vehicle::control_engines(), Character::count_trait_flag(), basecamp::craft_description(), mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), mission_start::create_lab_console(), anonymous_namespace{monexamine.cpp}::cull(), damage_targets(), mattack::darkman(), Character::deal_damage(), Creature::deal_damage_handle_type(), repair_item_actor::default_action(), mattack::dermatik(), item_location::deserialize(), item::detonate(), npc::die(), iuse::directional_hologram(), iexamine::dirtmound(), disassemble_inventory_preset::disassemble_inventory_preset(), item::disassembly_info(), veh_app_interact::disconnect(), map::displace_vehicle(), ui::omap::display(), overmap_ui::display(), ui::omap::display_editor(), ui::omap::display_hordes(), veh_interact::display_name(), ui::omap::display_scents(), ui::omap::display_visible_weather(), ui::omap::display_weather(), explosion_handler::do_blast(), melee_actor::do_grab(), veh_interact::do_main_loop(), Pickup::do_pickup(), advanced_inventory::do_return_entry(), construct::done_trunk_plank(), map::draw_from_above(), editmap::draw_main_ui_overlay(), advanced_inventory::draw_minimap(), overmap_ui::draw_notes(), overmap_ui::draw_om_sidebar(), mission_ui_impl::draw_selected_description(), draw_spellbook_info(), vehicle::drive_to_local_target(), talk_function::drop_stolen_item(), mattack::dsa_drone_scan(), anonymous_namespace{monexamine.cpp}::dump_items(), mattack::eat_carrion(), mattack::eat_food(), eff_fun_teleglow(), editmap::eget_direction(), explosion_handler::emp_blast(), talker_item_const::encumbrance_at(), known_magic::evaluate_opens_spellbook_data(), mattack::evolve_kill_strike(), npc::execute_action(), map_data_common_t::extended_description(), monster::extended_description(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lightning(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_friend(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_camp(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_know_recipe(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_profession(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_wants_to_talk(), basecamp::faction_display(), npc::faction_display(), computer_session::failure_alarm(), computer_session::failure_amigara(), computer_session::failure_damage(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), computer_session::failure_manhacks(), computer_session::failure_pump_explode(), computer_session::failure_secubots(), computer_session::failure_shutdown(), farm_action(), basecamp::farm_return(), talk_function::field_harvest(), talk_function::field_plant(), overmapbuffer::find_all_radio_stations(), npc::find_corpse_to_pulp(), overmapbuffer::find_radio_station(), mission_start::find_safety(), inventory::find_usable_cached_invlet(), heal_actor::finish_using(), mattack::flame(), mattack::flamethrower(), explosion_handler::flashbang(), talk_function::follow(), npc::follow_distance(), item::food_info(), monster::footsteps(), talk_function::forage_return(), known_magic::forget_spell(), veh_interact::format_reqs(), mattack::frag(), advanced_inventory_pane::free_volume(), advanced_inventory_pane::free_weight_capacity(), suffer::from_bad_bionics(), vehicle::fuel_left(), fungal_effects::fungalize(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::fungus_sprout(), vehicle::gain_moves(), dialogue::gen_responses(), debug_menu::generate_effect_list(), map::generate_lightmap(), generic_barber(), monster::get_attitude(), get_autopickup_items(), get_avatar_or_follower(), get_best_fire(), quality_requirement::get_color(), selection_column_preset::get_color(), bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), get_freshness_description(), sfx::get_heard_angle(), sfx::get_heard_volume(), get_heat_radiation(), inventory_entry::get_invlet_color(), advanced_inv_area::get_item_count(), liquid_handler::get_liquid_target(), item::get_min_str(), get_mission_om_origin(), veh_interact::get_most_repairable_part(), overmapbuffer::get_npcs_near_player(), npc::get_opinion_values(), overmap_ui::get_overmap_neighbors(), overmap_ui::get_overmap_path_to(), npc::get_path_avoid(), read_activity_actor::get_progress_message(), item::get_quality_nonrecursive(), Creature::get_summoner(), aim_activity_actor::get_weapon(), talk_function::give_aid(), talk_function::give_all_aid(), basecamp::give_basecamp_equipment(), talk_function::give_equipment_allowance(), talker_npc::give_item_to(), glare(), talker_furniture::global_omt_location(), talker_item_const::global_omt_location(), trapfunc::glow(), trapfunc::goo(), npc::good_escape_direction(), talk_function::goto_location(), grab(), mattack::graze(), mattack::grenadier(), mattack::grenadier_elite(), mattack::grow_vine(), gunmode_checks_weapon(), handbrake(), handle_action_menu(), talk_function::handle_outpost_mission(), handle_problematic_pickup(), npc::handle_sound(), vehicle::handle_trap(), handle_weather_effects(), Character::hardcoded_effects(), tool_comp::has(), item_comp::has(), quality_requirement::has(), player_morale::has_flag(), has_pre_terrain(), Character::has_trait_flag(), haul(), monster::hear_sound(), talk_function::hospital_raid(), talk_function::hospital_raid_return(), talk_function::hostile(), vehicle::idle(), npc::indoor_voice(), consume_drug_iuse::info(), heal_actor::info(), anonymous_namespace{monexamine.cpp}::insert_battery(), exosuit_interact::insert_replace_activate_mod(), exosuit_interact::interact_loop(), npc::is_ally(), debug_menu::is_debug_character(), npc::is_player_ally(), vehicle::is_rotorcraft(), item::is_worn_by_player(), iexamine::keg(), pocket_favorite_callback::key(), spellcasting_callback::key(), ma_style_callback::key(), mission_start::kill_nemesis(), monster::know_danger_at(), talk_function::labor_return(), talk_function::lesser_give_aid(), talk_function::lesser_give_all_aid(), loot(), monexamine::mech_hack(), item::med_info(), monster::melee_attack(), Character::melee_attack_abstract(), item::melee_combat_info(), monexamine::mfriend_menu(), anonymous_namespace{monexamine.cpp}::milk_source(), anonymous_namespace{messages.cpp}::messages_impl::modify_msg_with_exclamations(), talk_function::morale_chat(), talk_function::morale_chat_activity(), anonymous_namespace{monexamine.cpp}::mount_pet(), monster::move(), npc::move(), advanced_inventory::move_all_items(), npc::move_away_from(), activity_handlers::move_cost_cart(), activity_handlers::move_cost_inv(), overmapbuffer::move_hordes(), npc::move_to(), map::move_vehicle(), npc::mug_player(), multi_projectile_hit_message(), mattack::multi_robot(), spell_events::notify(), memorial_logger::notify(), read_activity_actor::npc_read(), npc_temp_orders_menu(), mattack::nurse_operate(), monster::nursebot_operate(), basecamp::om_upgrade_description(), melee_actor::on_damage(), vehicle::on_move(), item::on_pickup(), item::on_wear(), item::on_wield(), player_morale::on_worn_item_washed(), vehicle::open_or_close(), activity_handlers::operation_do_turn(), advanced_inv_sorter::operator()(), target_ui::panel_spell_info(), vehicle::part_collision(), vehicle::part_displayed_at(), monexamine::pay_bot(), timed_event::per_turn(), tutorial_game::per_turn(), liquid_handler::perform_liquid_transfer(), monexamine::pet_menu(), mattack::photograph(), pick_one_up(), activity_handlers::pickaxe_finish(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), pl_sees(), map::pl_sees(), mission_start::place_npc_software(), monster::plan(), vehicle::play_music(), anonymous_namespace{monexamine.cpp}::play_with(), basecamp::player_eats_meal(), player_hit_message(), talk_function::player_weapon_away(), talk_function::player_weapon_drop(), pldrive(), avatar_action::plthrow(), veh_app_interact::plug(), iuse::portable_game(), tutorial_game::post_action(), vehicle::power_parts(), vehicle::precollision_check(), npc::print_info(), monster::print_info(), advanced_inventory::print_items(), monster::process_effects(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::process_eoc(), map::process_fields_in_submap(), overmapbuffer::process_mongroups(), sounds::process_sound_markers(), monster::process_turn(), anonymous_namespace{monexamine.cpp}::push(), monster::push_to(), item::qualities_info(), veh_menu::query(), advanced_inventory::query_charges(), plot_options::query_seed(), Pickup::query_thief(), mission_util::random_house_in_closest_city(), mattack::ratking(), mattack::rattle(), rcdrive(), Character::reach_attack(), npc::reach_omt_destination(), item::ready_to_revive(), basecamp::recipe_batch_max(), basecamp::recruit_evaluation(), advanced_inventory::redraw_sidebar(), reflesh_favorite(), npc::regen_ai_cache(), vehicle::reload_seeds(), veh_app_interact::remove(), anonymous_namespace{monexamine.cpp}::remove_armor(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), anonymous_namespace{monexamine.cpp}::remove_battery(), talker_character::remove_effect(), talker_monster::remove_effect(), anonymous_namespace{monexamine.cpp}::remove_leash(), anonymous_namespace{monexamine.cpp}::remove_saddle_from(), remove_submap_turrets(), effect_source::resolve_creature(), explosion_handler::resonance_cascade(), mattack::resurrect(), reveal_destination(), mission_util::reveal_om_ter(), mission_start::reveal_refugee_center(), reveal_route(), item::rot_info(), run_item_eocs(), inventory::rust_iron_items(), npc::say(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), monster::scent_move(), mattack::searchlight(), map::seen_cache_process_ledges(), Creature::sees(), select_ammo_inventory_preset::select_ammo_inventory_preset(), Character::select_item_component(), auto_pickup::select_items(), vehicle::separate_from_grid(), target_ui::set_cursor_pos(), set_up_butchery(), player_morale::set_worn(), anonymous_namespace{monexamine.cpp}::shear_animal(), mattack::shockstorm(), explosion_handler::shockwave(), auto_pickup::user_interface::show(), auto_pickup::player_settings::show(), safemode::show(), trapfunc::sinkhole(), mattack::slimespring(), vehicle::smart_controller_handle_turn(), vehicle::smash_security_system(), outfit::sort_armor(), inventory_column::sort_compare(), map::spawn_monsters_submap_group(), spell_effect_area(), spellcasting_callback::spell_info_text(), spell_move(), consume_activity_actor::start(), advanced_inventory::start_activity(), basecamp::start_crafting(), vehicle::start_engine(), vehicle::start_engines(), activity_handlers::start_engines_finish(), basecamp::start_fortifications(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), talk_function::start_training(), talk_function::start_training_gen(), talk_function::start_training_npc(), talk_function::start_training_seminar(), str_to_illiterate_str(), anonymous_namespace{monexamine.cpp}::swap(), swap_pos(), widget::sym_text_cond(), mission_util::target_om_ter_random(), mattack::taze(), debug_menu::teleport_overmap(), debug_menu::teleport_short(), tell_magic_veh_to_follow(), tell_veh_stop_following(), safemode::test_pattern(), widget::text_cond(), vehicle::thrust(), activity_handlers::train_finish(), mattack::triffid_heartbeat(), trapfunc::tripwire(), try_consume(), try_set_alarm(), Character::unload(), unroll_digging(), inventory::update_invlet(), update_time_left(), editmap::update_view_with_help(), map::update_visibility_cache(), weather_manager::update_weather(), deploy_tent_actor::use(), npc_attack_melee::use(), vehicle::use_harness(), vehicle::use_vehicle_tool(), basecamp::validate_sort_points(), map::vehmove(), wait(), weather_sound(), npc::will_accept_from_player(), monster::will_reach(), talker_npc::will_talk_to_u(), within_visual_range(), npc::would_take_that(), and advanced_inventory::~advanced_inventory().
get_stat_name()
std::string get_stat_name (character_stat Stat)
Get translated name of a stat.
Definition at line 7609 of file character.cpp.
 {
     switch( Stat ) {
         // *INDENT-OFF*
     case character_stat::STRENGTH:     return pgettext( "strength stat", "STR" );
     case character_stat::DEXTERITY:    return pgettext( "dexterity stat", "DEX" );
     case character_stat::INTELLIGENCE: return pgettext( "intelligence stat", "INT" );
     case character_stat::PERCEPTION:   return pgettext( "perception stat", "PER" );
         // *INDENT-ON*
         default:
             break;
     }
     return pgettext( "fake stat there's an error", "ERR" );
 }
References DEXTERITY, INTELLIGENCE, PERCEPTION, pgettext, and STRENGTH.
operator+() [1/2]
template<typename T > constexpr int operator+ (const sleepiness_levels & lhs, const T & rhs) inline constexpr
Definition at line 210 of file character.h.
 {
     return static_cast<T>( lhs ) + rhs;
 }
operator+() [2/2]
social_modifiers operator+ (social_modifiers lhs, const social_modifiers & rhs) inline
Definition at line 429 of file character.h.
 {
     lhs += rhs;
     return lhs;
 }
operator-() [1/2]
template<typename T > constexpr int operator- (const sleepiness_levels & lhs, const T & rhs) inline constexpr
Definition at line 216 of file character.h.
 {
     return static_cast<T>( lhs ) - rhs;
 }
operator-() [2/2]
template<typename T > constexpr int operator- (const T & lhs, const sleepiness_levels & rhs) inline constexpr
Definition at line 222 of file character.h.
 {
     return lhs - static_cast<T>( rhs );
 }
operator/()
template<typename T > constexpr int operator/ (const sleepiness_levels & lhs, const T & rhs) inline constexpr
Definition at line 204 of file character.h.
 {
     return static_cast<T>( lhs ) / rhs;
 }
operator<() [1/2]
constexpr bool operator< (const sleepiness_levels & lhs, const sleepiness_levels & rhs) inline constexpr
Definition at line 174 of file character.h.
 {
     return static_cast<int>( lhs ) < static_cast<int>( rhs );
 }
operator<() [2/2]
template<typename T > constexpr bool operator< (const T & lhs, const sleepiness_levels & rhs) inline constexpr
Definition at line 198 of file character.h.
 {
     return lhs < static_cast<T>( rhs );
 }
operator<=()
template<typename T > constexpr bool operator<= (const T & lhs, const sleepiness_levels & rhs) inline constexpr
Definition at line 192 of file character.h.
 {
     return lhs <= static_cast<T>( rhs );
 }
operator>()
template<typename T > constexpr bool operator> (const T & lhs, const sleepiness_levels & rhs) inline constexpr
Definition at line 186 of file character.h.
 {
     return lhs > static_cast<T>( rhs );
 }
operator>=() [1/2]
constexpr bool operator>= (const sleepiness_levels & lhs, const sleepiness_levels & rhs) inline constexpr
Definition at line 169 of file character.h.
 {
     return static_cast<int>( lhs ) >= static_cast<int>( rhs );
 }
operator>=() [2/2]
template<typename T > constexpr bool operator>= (const T & lhs, const sleepiness_levels & rhs) inline constexpr
Definition at line 180 of file character.h.
 {
     return lhs >= static_cast<T>( rhs );
 }
Variable Documentation
KCAL_PER_KG
constexpr float KCAL_PER_KG = 3500 * 2.20462 constexpr
Definition at line 127 of file character.h.
Referenced by Character::bodyweight_fat(), Character::burn_move_stamina(), Character::get_bmi_fat(), and Character::get_healthy_kcal().
MAX_CLAIRVOYANCE
constexpr int MAX_CLAIRVOYANCE = 40 constexpr
Definition at line 125 of file character.h.
Referenced by Character::clairvoyance(), and Character::sees().
sleepiness_level_strs
const std::unordered_map<std::string, sleepiness_levels> sleepiness_level_strs
Initial value:
= { {
        { "TIRED", sleepiness_levels::TIRED },
        { "DEAD_TIRED", sleepiness_levels::DEAD_TIRED },
        { "EXHAUSTED", sleepiness_levels::EXHAUSTED },
        { "MASSIVE_SLEEPINESS", sleepiness_levels::MASSIVE_SLEEPINESS }
    }
}
Definition at line 161 of file character.h.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_need().