Cataclysm DDA: src/character_crafting.cpp File Reference
character_crafting.cpp File Reference
#include <algorithm>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <utility>
#include <vector>
#include "character.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "itype.h"
#include "pimpl.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "skill.h"
#include "type_id.h"
#include "value_ptr.h"
Functions
static bool check_nested_has_recipes (const recipe *r, const recipe_subset &res)
Function Documentation
check_nested_has_recipes()
static bool check_nested_has_recipes (const recipe * r, const recipe_subset & res) static
Definition at line 93 of file character_crafting.cpp.
 {
     for( const recipe_id &nestedr : r->nested_category_data ) {
         if( nestedr->is_nested() ) {
             // recursively check for a category that has stuff in it
             if( check_nested_has_recipes( &nestedr.obj(), res ) ) {
                 return true;
             }
         } else if( res.contains( &nestedr.obj() ) ) {
             return true;
         }
     }
     return false;
 }
References recipe_subset::contains(), recipe::is_nested(), recipe::nested_category_data, and string_id< T >::obj().
Referenced by Character::get_available_nested().