Cataclysm DDA: src/character_attire.cpp File Reference
character_attire.cpp File Reference
#include "character_attire.h"
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <iterator>
#include <memory>
#include <numeric>
#include <ostream>
#include "bodygraph.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "creature.h"
#include "damage.h"
#include "debug.h"
#include "display.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "fire.h"
#include "flag.h"
#include "flat_set.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game_constants.h"
#include "inventory.h"
#include "item_contents.h"
#include "item_pocket.h"
#include "itype.h"
#include "json.h"
#include "json_error.h"
#include "line.h"
#include "magic_enchantment.h"
#include "make_static.h"
#include "melee.h"
#include "messages.h"
#include "mutation.h"
#include "output.h"
#include "pimpl.h"
#include "pocket_type.h"
#include "point.h"
#include "relic.h"
#include "rng.h"
#include "string_formatter.h"
#include "translation.h"
#include "translations.h"
#include "value_ptr.h"
#include "viewer.h"
Functions
units::mass get_selected_stack_weight (const item *i, const std::map< const item *, int > &without)
static void layer_item (std::map< bodypart_id, encumbrance_data > &vals, const item &it, std::map< sub_bodypart_id, layer_level > &highest_layer_so_far, const Character &c)
static bool check_natural_attack_restricted_on_worn (const item &i)
static ret_val< void > test_only_one_conflicts (const item &clothing, const item &i)
static ret_val< void > rigid_test (const item &clothing, const item &i, const std::unordered_set< sub_bodypart_id > &to_test)
static void item_armor_enchantment_adjust (Character &guy, damage_unit &du, item &armor)
static std::vector< pocket_data_with_parent > get_child_pocket_with_parent (const item_pocket *pocket, const item_location &parent, item_location it, const int nested_level, const std::function< bool(const item_pocket *)> &filter=return_true< const item_pocket * >)
Variables
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_heating_bionic ("heating_bionic")
static const efftype_id effect_incorporeal ("incorporeal")
static const efftype_id effect_onfire ("onfire")
static const flag_id json_flag_HIDDEN ("HIDDEN")
static const flag_id json_flag_ONE_PER_LAYER ("ONE_PER_LAYER")
static const itype_id itype_shoulder_strap ("shoulder_strap")
static const material_id material_acidchitin ("acidchitin")
static const material_id material_bone ("bone")
static const material_id material_chitin ("chitin")
static const material_id material_fur ("fur")
static const material_id material_gutskin ("gutskin")
static const material_id material_leather ("leather")
static const material_id material_wool ("wool")
static const sub_bodypart_str_id sub_body_part_foot_sole_l ("foot_sole_l")
static const sub_bodypart_str_id sub_body_part_foot_sole_r ("foot_sole_r")
static const trait_id trait_ANTENNAE ("ANTENNAE")
static const trait_id trait_ANTLERS ("ANTLERS")
static const trait_id trait_HORNS_POINTED ("HORNS_POINTED")
static const trait_id trait_SQUEAMISH ("SQUEAMISH")
static const trait_id trait_VEGAN ("VEGAN")
static const trait_id trait_WOOLALLERGY ("WOOLALLERGY")
Function Documentation
check_natural_attack_restricted_on_worn()
static bool check_natural_attack_restricted_on_worn (const item & i) static
Definition at line 1139 of file character_attire.cpp.
 {
     return !i.has_flag( flag_ALLOWS_NATURAL_ATTACKS ) &&
            !i.has_flag( flag_SEMITANGIBLE ) &&
            !i.has_flag( flag_PERSONAL ) && !i.has_flag( flag_AURA );
 }
References flag_ALLOWS_NATURAL_ATTACKS, flag_AURA, flag_PERSONAL, flag_SEMITANGIBLE, and item::has_flag().
Referenced by outfit::natural_attack_restricted_on().
get_child_pocket_with_parent()
static std::vector<pocket_data_with_parent> get_child_pocket_with_parent (const item_pocket * pocket, const item_location & parent, item_location it, const int nested_level, const std::function< bool(const item_pocket *)> & filter = return_true<const item_pocket *>) static
Definition at line 2402 of file character_attire.cpp.
 {
     std::vector<pocket_data_with_parent> ret;
     if( pocket != nullptr ) {
         pocket_data_with_parent pocket_data = { pocket, item_location::nowhere, nested_level };
         const item_location new_parent = item_location( it );
         if( parent != item_location::nowhere ) {
             pocket_data.parent = item_location( parent, it.get_item() );
         }
         if( filter( pocket_data.pocket_ptr ) ) {
             ret.emplace_back( pocket_data );
         }
         for( const item *contained : pocket->all_items_top() ) {
             const item_location poc_loc = item_location( it, const_cast<item *>( contained ) );
             for( const item_pocket *pocket_nest : contained->get_all_contained_pockets() ) {
                 std::vector<pocket_data_with_parent> child =
                     get_child_pocket_with_parent( pocket_nest, new_parent,
                                                   poc_loc, nested_level + 1, filter );
                 ret.insert( ret.end(), child.begin(), child.end() );
             }
         }
     }
     return ret;
 }
References item_pocket::all_items_top(), filter, item_location::get_item(), item_location::nowhere, and cata::hash64_detail::ret.
Referenced by Character::get_all_pocket_with_parent().
get_selected_stack_weight()
units::mass get_selected_stack_weight (const item * i, const std::map< const item *, int > & without)
Definition at line 96 of file character_attire.cpp.
 {
     auto stack = without.find( i );
     if( stack != without.end() ) {
         int selected = stack->second;
         item copy = *i;
         copy.charges = selected;
         return copy.weight();
     }
     return 0_gram;
 }
References item::charges, and item::weight().
Referenced by Character::weight_carried_with_tweaks(), and outfit::weight_carried_with_tweaks().
item_armor_enchantment_adjust()
static void item_armor_enchantment_adjust (Character & guy, damage_unit & du, item & armor) static
Definition at line 1857 of file character_attire.cpp.
 {
     //If we're not dealing any damage of the given type, don't even bother.
     if( du.amount < 0.1f ) {
         return;
     }
     // FIXME: hardcoded damage types -> enchantments
     if( du.type == STATIC( damage_type_id( "acid" ) ) ) {
         du.amount = armor.calculate_by_enchantment( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_ACID );
     } else if( du.type == STATIC( damage_type_id( "bash" ) ) ) {
         du.amount = armor.calculate_by_enchantment( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_BASH );
     } else if( du.type == STATIC( damage_type_id( "biological" ) ) ) {
         du.amount = armor.calculate_by_enchantment( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_BIO );
     } else if( du.type == STATIC( damage_type_id( "cold" ) ) ) {
         du.amount = armor.calculate_by_enchantment( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_COLD );
     } else if( du.type == STATIC( damage_type_id( "cut" ) ) ) {
         du.amount = armor.calculate_by_enchantment( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_CUT );
     } else if( du.type == STATIC( damage_type_id( "electric" ) ) ) {
         du.amount = armor.calculate_by_enchantment( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_ELEC );
     } else if( du.type == STATIC( damage_type_id( "heat" ) ) ) {
         du.amount = armor.calculate_by_enchantment( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_HEAT );
     } else if( du.type == STATIC( damage_type_id( "stab" ) ) ) {
         du.amount = armor.calculate_by_enchantment( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_STAB );
     } else if( du.type == STATIC( damage_type_id( "bullet" ) ) ) {
         du.amount = armor.calculate_by_enchantment( guy, du.amount, enchant_vals::mod::ITEM_ARMOR_BULLET );
     }
     du.amount = std::max( 0.0f, du.amount );
 }
References damage_unit::amount, item::calculate_by_enchantment(), enchant_vals::ITEM_ARMOR_ACID, enchant_vals::ITEM_ARMOR_BASH, enchant_vals::ITEM_ARMOR_BIO, enchant_vals::ITEM_ARMOR_BULLET, enchant_vals::ITEM_ARMOR_COLD, enchant_vals::ITEM_ARMOR_CUT, enchant_vals::ITEM_ARMOR_ELEC, enchant_vals::ITEM_ARMOR_HEAT, enchant_vals::ITEM_ARMOR_STAB, max(), STATIC, and damage_unit::type.
Referenced by outfit::absorb_damage().
layer_item()
static void layer_item (std::map< bodypart_id, encumbrance_data > & vals, const item & it, std::map< sub_bodypart_id, layer_level > & highest_layer_so_far, const Character & c) static
Definition at line 823 of file character_attire.cpp.
 {
     body_part_set covered_parts = it.get_covered_body_parts();
     for( const bodypart_id &bp : c.get_all_body_parts() ) {
         if( !covered_parts.test( bp.id() ) ) {
             continue;
         }
         const std::vector<layer_level> item_layers = it.get_layer( bp );
         int encumber_val = it.get_encumber( c, bp.id() );
         int layering_encumbrance = clamp( encumber_val, 2, 10 );
         /*
          * Setting layering_encumbrance to 0 at this point makes the item cease to exist
          * for the purposes of the layer penalty system. (normally an item has a minimum
          * layering_encumbrance of 2 )
          * Personal layer items and semitangible items do not conflict.
          */
         if( it.has_flag( flag_SEMITANGIBLE ) ) {
             encumber_val = 0;
             layering_encumbrance = 0;
         }
         if( it.has_flag( flag_PERSONAL ) ) {
             layering_encumbrance = 0;
         }
         for( layer_level item_layer : item_layers ) {
             // do the sublayers of this armor conflict
             bool conflicts = false;
             // check if we've already added conflict for the layer and body part since each sbp is check individually
             std::map<layer_level, bool> bpcovered;
             // add the sublocations to the overall body part layer and update if we are conflicting
             for( sub_bodypart_id &sbp : it.get_covered_sub_body_parts() ) {
                 if( std::count_if( bp->sub_parts.begin(),
                 bp->sub_parts.end(), [sbp]( const sub_bodypart_str_id & bpid ) {
                 return sbp.id() == bpid;
                 } ) == 0 ) {
                     // the sub part isn't part of the bodypart we are checking
                     continue;
                 }
                 // bit hacky but needed since we are doing one layer at a time
                 std::vector<layer_level> ll;
                 ll.push_back( item_layer );
                 if( !it.has_layer( ll, sbp ) ) {
                     // skip this layer and sbp if it doesn't cover it
                     continue;
                 }
                 if( item_layer >= highest_layer_so_far[sbp] ) {
                     conflicts = vals[bp].add_sub_location( item_layer, sbp );
                 } else {
                     // if it is on a lower layer it conflicts for sure
                     conflicts = true;
                 }
                 highest_layer_so_far[sbp] = std::max( highest_layer_so_far[sbp], item_layer );
                 // Apply layering penalty to this layer, as well as any layer worn
                 // within it that would normally be worn outside of it.
                 for( layer_level penalty_layer = item_layer;
                      penalty_layer <= highest_layer_so_far[sbp]; ++penalty_layer ) {
                     // make sure we haven't already found a subpart that covers and would cause penalty
                     if( !bpcovered[penalty_layer] ) {
                         vals[bp].layer( penalty_layer, layering_encumbrance, conflicts );
                         bpcovered[penalty_layer] = true;
                     }
                 }
             }
         }
         vals[bp].armor_encumbrance += encumber_val;
     }
 }
References bp, c, clamp(), flag_PERSONAL, flag_SEMITANGIBLE, item::get_covered_body_parts(), item::get_covered_sub_body_parts(), item::get_encumber(), item::get_layer(), item::has_flag(), item::has_layer(), int_id< T >::id(), max(), body_part_type::sub_parts, and body_part_set::test().
Referenced by outfit::item_encumb().
rigid_test()
static ret_val<void> rigid_test (const item & clothing, const item & i, const std::unordered_set< sub_bodypart_id > & to_test) static
Definition at line 1363 of file character_attire.cpp.
 {
     // check each sublimb individually
     for( const sub_bodypart_id &sbp : to_test ) {
         // skip if the item doesn't currently cover the bp
         if( !i.covers( sbp ) ) {
             continue;
         }
         // skip if either item cares only about its layer and they don't match up
         if( ( i.is_bp_rigid_selective( sbp ) || clothing.is_bp_rigid_selective( sbp ) ) &&
             !i.has_layer( clothing.get_layer( sbp ), sbp ) ) {
             continue;
         }
         // allow wearing splints on integrated armor such as protective bark
         if( i.has_flag( flag_INTEGRATED ) && clothing.has_flag( flag_SPLINT ) ) {
             continue;
         }
         if( i.is_bp_rigid( sbp ) ) {
             return ret_val<void>::make_failure( _( "Can't wear more than one rigid item on %s!" ), sbp->name );
         }
     }
     return ret_val<void>::make_success();
 }
References _, item::covers(), flag_INTEGRATED, flag_SPLINT, item::get_layer(), item::has_flag(), item::has_layer(), item::is_bp_rigid(), item::is_bp_rigid_selective(), ret_val< T >::make_failure(), and ret_val< T >::make_success().
Referenced by outfit::check_rigid_conflicts().
test_only_one_conflicts()
static ret_val<void> test_only_one_conflicts (const item & clothing, const item & i) static
Definition at line 1308 of file character_attire.cpp.
 {
     const bool this_restricts_only_one = clothing.has_flag( json_flag_ONE_PER_LAYER );
     std::map<side, bool> sidedness;
     sidedness[side::BOTH] = false;
     sidedness[side::LEFT] = false;
     sidedness[side::RIGHT] = false;
     const auto sidedness_conflicts = [&sidedness]( side s ) -> bool {
         const bool ret = sidedness[s];
         sidedness[s] = true;
         if( sidedness[side::LEFT] && sidedness[side::RIGHT] )
         {
             sidedness[side::BOTH] = true;
             return true;
         }
         return ret;
     };
     if( i.has_flag( flag_ONLY_ONE ) && i.typeId() == clothing.typeId() ) {
         return ret_val<void>::make_failure( _( "Can't wear more than one %s!" ), clothing.tname() );
     }
     if( this_restricts_only_one || i.has_flag( json_flag_ONE_PER_LAYER ) ) {
         std::optional<side> overlaps = clothing.covers_overlaps( i );
         if( overlaps && sidedness_conflicts( *overlaps ) ) {
             return ret_val<void>::make_failure( _( "%1$s conflicts with %2$s!" ), clothing.tname(), i.tname() );
         }
     }
     return ret_val<void>::make_success();
 }
References _, BOTH, item::covers_overlaps(), flag_ONLY_ONE, item::has_flag(), json_flag_ONE_PER_LAYER, LEFT, ret_val< T >::make_failure(), ret_val< T >::make_success(), cata::hash64_detail::ret, RIGHT, item::tname(), and item::typeId().
Referenced by outfit::only_one_conflicts().
Variable Documentation
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by Character::can_wear().
effect_heating_bionic
const efftype_id effect_heating_bionic("heating_bionic") ("heating_bionic") static
Referenced by outfit::warmth().
effect_incorporeal
const efftype_id effect_incorporeal("incorporeal") ("incorporeal") static
Referenced by Character::can_wear().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by outfit::absorb_damage().
itype_shoulder_strap
const itype_id itype_shoulder_strap("shoulder_strap") ("shoulder_strap") static
Referenced by outfit::fire_options().
json_flag_HIDDEN
const flag_id json_flag_HIDDEN("HIDDEN") ("HIDDEN") static
Referenced by outfit::get_overlay_ids().
json_flag_ONE_PER_LAYER
const flag_id json_flag_ONE_PER_LAYER("ONE_PER_LAYER") ("ONE_PER_LAYER") static
Referenced by outfit::one_per_layer_change_side(), outfit::one_per_layer_sidedness(), and test_only_one_conflicts().
material_acidchitin
const material_id material_acidchitin("acidchitin") ("acidchitin") static
Referenced by Character::can_wear().
material_bone
const material_id material_bone("bone") ("bone") static
Referenced by Character::can_wear().
material_chitin
const material_id material_chitin("chitin") ("chitin") static
Referenced by Character::can_wear().
material_fur
const material_id material_fur("fur") ("fur") static
Referenced by Character::can_wear().
material_gutskin
const material_id material_gutskin("gutskin") ("gutskin") static
Referenced by Character::can_wear().
material_leather
const material_id material_leather("leather") ("leather") static
Referenced by Character::can_wear().
material_wool
const material_id material_wool("wool") ("wool") static
Referenced by Character::can_wear(), and outfit::warmth().
sub_body_part_foot_sole_l
const sub_bodypart_str_id sub_body_part_foot_sole_l("foot_sole_l") ("foot_sole_l") static
Referenced by outfit::is_barefoot().
sub_body_part_foot_sole_r
const sub_bodypart_str_id sub_body_part_foot_sole_r("foot_sole_r") ("foot_sole_r") static
Referenced by outfit::is_barefoot().
trait_ANTENNAE
const trait_id trait_ANTENNAE("ANTENNAE") ("ANTENNAE") static
Referenced by Character::can_wear().
trait_ANTLERS
const trait_id trait_ANTLERS("ANTLERS") ("ANTLERS") static
Referenced by Character::can_wear().
trait_HORNS_POINTED
const trait_id trait_HORNS_POINTED("HORNS_POINTED") ("HORNS_POINTED") static
Referenced by Character::can_wear().
trait_SQUEAMISH
const trait_id trait_SQUEAMISH("SQUEAMISH") ("SQUEAMISH") static
Referenced by Character::can_wear().
trait_VEGAN
const trait_id trait_VEGAN("VEGAN") ("VEGAN") static
Referenced by Character::can_wear().
trait_WOOLALLERGY
const trait_id trait_WOOLALLERGY("WOOLALLERGY") ("WOOLALLERGY") static
Referenced by Character::can_wear().