Cataclysm DDA: src/character_modifier.cpp File Reference
character_modifier.cpp File Reference
#include "character_modifier.h"
#include <algorithm>
#include <cmath>
#include <functional>
#include <limits>
#include <set>
#include "character.h"
#include "debug.h"
#include "effect.h"
#include "enum_conversions.h"
#include "flag.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "init.h"
#include "json_error.h"
#include "messages.h"
#include "move_mode.h"
#include "output.h"
#include "string_formatter.h"
Namespaces
anonymous_namespace{character_modifier.cpp}
Functions
static character_modifier::mod_type string_to_modtype (const std::string &s)
static float load_float_or_maxmovecost (const JsonObject &jo, const std::string &field)
static float aim_speed_skill_modifier (const Character &c, const skill_id &gun_skill)
static float aim_speed_dex_modifier (const Character &c, const skill_id &)
static float move_mode_move_cost_modifier (const Character &c, const skill_id &)
static float stamina_move_cost_modifier (const Character &c, const skill_id &)
static float limb_run_cost_modifier (const Character &c, const skill_id &)
static float call_builtin (const std::string &builtin, const Character &c, const skill_id &skill)
Variables
static const character_modifier_id character_modifier_limb_footing_movecost_mod ("limb_footing_movecost_mod")
static const character_modifier_id character_modifier_limb_speed_movecost_mod ("limb_speed_movecost_mod")
static const limb_score_id limb_score_manip ("manip")
static const limb_score_id limb_score_swim ("swim")
static const skill_id skill_archery ("archery")
static const skill_id skill_swimming ("swimming")
generic_factory< character_modifier > anonymous_namespace{character_modifier.cpp}::character_modifier_factory ("character modifier")
Function Documentation
aim_speed_dex_modifier()
static float aim_speed_dex_modifier (const Character & c, const skill_id &) static
Definition at line 287 of file character_modifier.cpp.
 {
     return ( c.get_dex() - 8 ) * 0.5f;
 }
References c.
Referenced by call_builtin().
aim_speed_skill_modifier()
static float aim_speed_skill_modifier (const Character & c, const skill_id & gun_skill) static
Definition at line 275 of file character_modifier.cpp.
 {
     float skill_mult = 0.25f;
     float base_modifier = 0.0f;
     if( gun_skill == skill_archery ) {
         skill_mult = 0.5f;
         base_modifier = -1.5f;
     }
     return skill_mult * std::min( static_cast<float>( MAX_SKILL ),
                                   c.get_skill_level( gun_skill ) ) + base_modifier;
 }
References c, MAX_SKILL, min(), and skill_archery.
Referenced by call_builtin().
call_builtin()
static float call_builtin (const std::string & builtin, const Character & c, const skill_id & skill) static
Definition at line 312 of file character_modifier.cpp.
 {
     static const std::map<std::string, std::function<float( const Character &, const skill_id & )>>
     func_map = {
         { "limb_run_cost_modifier", limb_run_cost_modifier },
         { "move_mode_move_cost_modifier", move_mode_move_cost_modifier },
         { "stamina_move_cost_modifier", stamina_move_cost_modifier },
         { "aim_speed_dex_modifier", aim_speed_dex_modifier },
         { "aim_speed_skill_modifier", aim_speed_skill_modifier }
     };
     auto iter = func_map.find( builtin );
     if( iter == func_map.end() ) {
         debugmsg( "Invalid builtin function %s for character modifier", builtin );
         return 0.0f;
     }
     return ( iter->second )( c, skill );
 }
References aim_speed_dex_modifier(), aim_speed_skill_modifier(), c, debugmsg, limb_run_cost_modifier(), spell_effect::map(), move_mode_move_cost_modifier(), and stamina_move_cost_modifier().
Referenced by character_modifier::modifier().
limb_run_cost_modifier()
static float limb_run_cost_modifier (const Character & c, const skill_id &) static
Definition at line 306 of file character_modifier.cpp.
 {
     return ( character_modifier_limb_footing_movecost_mod->modifier( c ) +
              character_modifier_limb_speed_movecost_mod->modifier( c ) * 2 ) / 3.0f;
 }
References c, character_modifier_limb_footing_movecost_mod, character_modifier_limb_speed_movecost_mod, and character_modifier::modifier().
Referenced by call_builtin().
load_float_or_maxmovecost()
static float load_float_or_maxmovecost (const JsonObject & jo, const std::string & field) static
Definition at line 90 of file character_modifier.cpp.
 {
     float val = 0.0f;
     if( jo.has_string( field ) ) {
         std::string val_str = jo.get_string( field );
         if( val_str == "max_move_cost" ) {
             val = MAX_MOVECOST_MODIFIER;
         } else {
             jo.throw_error( string_format( "invalid %s %s: use a float value or \"max_move_cost\"", field,
                                            val_str ) );
         }
     } else if( jo.has_float( field ) ) {
         mandatory( jo, false, field, val );
     }
     return val;
 }
References JsonObject::get_string(), JsonObject::has_float(), JsonObject::has_string(), mandatory(), MAX_MOVECOST_MODIFIER, string_format(), and JsonObject::throw_error().
Referenced by character_modifier::load().
move_mode_move_cost_modifier()
static float move_mode_move_cost_modifier (const Character & c, const skill_id &) static
Definition at line 292 of file character_modifier.cpp.
 {
     // Both walk and run speed drop to half their maximums as stamina approaches 0.
     // Convert stamina to a float first to allow for decimal place carrying
     return c.move_mode->move_speed_mult();
 }
References c.
Referenced by call_builtin().
stamina_move_cost_modifier()
static float stamina_move_cost_modifier (const Character & c, const skill_id &) static
Definition at line 299 of file character_modifier.cpp.
 {
     // Both walk and run speed drop to half their maximums as stamina approaches 0.
     // Convert stamina to a float first to allow for decimal place carrying
     return ( static_cast<float>( c.get_stamina() ) / c.get_stamina_max() + 1 ) / 2;
 }
References c.
Referenced by call_builtin().
string_to_modtype()
static character_modifier::mod_type string_to_modtype (const std::string & s) static
Definition at line 72 of file character_modifier.cpp.
 {
     static const std::map<std::string, character_modifier::mod_type> modtype_map = {
         { "+", character_modifier::ADD },
         { "ADD", character_modifier::ADD },
         { "X", character_modifier::MULT },
         { "*", character_modifier::MULT },
         { "MULT", character_modifier::MULT },
         { "", character_modifier::NONE }
     };
     const auto &iter = modtype_map.find( to_upper_case( s ) );
     if( iter == modtype_map.end() ) {
         debugmsg( "Invalid mod_type %s", s );
         return character_modifier::NONE;
     }
     return iter->second;
 }
References character_modifier::ADD, debugmsg, character_modifier::MULT, character_modifier::NONE, and to_upper_case().
Referenced by character_modifier::load().
Variable Documentation
character_modifier_limb_footing_movecost_mod
const character_modifier_id character_modifier_limb_footing_movecost_mod("limb_footing_movecost_mod") ("limb_footing_movecost_mod") static
Referenced by limb_run_cost_modifier().
character_modifier_limb_speed_movecost_mod
const character_modifier_id character_modifier_limb_speed_movecost_mod("limb_speed_movecost_mod") ("limb_speed_movecost_mod") static
Referenced by limb_run_cost_modifier().
limb_score_manip
const limb_score_id limb_score_manip("manip") ("manip") static
Referenced by Character::get_limb_score(), and Character::manipulator_score().
limb_score_swim
const limb_score_id limb_score_swim("swim") ("swim") static
Referenced by Character::get_limb_score().
skill_archery
const skill_id skill_archery("archery") ("archery") static
Referenced by aim_speed_skill_modifier().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by Character::get_limb_score().