Cataclysm DDA: src/character_martial_arts.cpp File Reference
character_martial_arts.cpp File Reference
#include "character_martial_arts.h"
#include <algorithm>
#include "action.h"
#include "character.h"
#include "color.h"
#include "enums.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "json.h"
#include "json_error.h"
#include "martialarts.h"
#include "messages.h"
#include "output.h"
#include "translation.h"
#include "translations.h"
Variables
static const matype_id style_kicks ("style_kicks")
static const matype_id style_none ("style_none")
Variable Documentation
style_kicks
const matype_id style_kicks("style_kicks") ("style_kicks") static
Referenced by character_martial_arts::character_martial_arts(), character_martial_arts::clear_styles(), and character_martial_arts::selected_style_check().
style_none
const matype_id style_none("style_none") ("style_none") static
Referenced by character_martial_arts::character_martial_arts(), character_martial_arts::clear_styles(), character_martial_arts::reset_style(), character_martial_arts::selected_is_none(), and character_martial_arts::selected_style_check().