Cataclysm DDA: src/character_inventory.cpp File Reference
character_inventory.cpp File Reference
#include <algorithm>
#include <bitset>
#include <climits>
#include <functional>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <ostream>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "activity_handlers.h"
#include "catacharset.h"
#include "character.h"
#include "character_attire.h"
#include "debug.h"
#include "enums.h"
#include "flag.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_location.h"
#include "item_pocket.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "map.h"
#include "map_selector.h"
#include "options.h"
#include "pimpl.h"
#include "pocket_type.h"
#include "point.h"
#include "ret_val.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "units_fwd.h"
#include "vehicle.h"
#include "visitable.h"
#include "vpart_position.h"
Functions
static void recur_internal_locations (item_location parent, std::vector< item_location > &list)
Function Documentation
recur_internal_locations()
static void recur_internal_locations (item_location parent, std::vector< item_location > & list) static
Definition at line 492 of file character_inventory.cpp.
 {
     for( item *it : parent->all_items_top( pocket_type::CONTAINER ) ) {
         item_location child( parent, it );
         recur_internal_locations( child, list );
     }
     list.push_back( parent );
 }
References item::all_items_top(), and CONTAINER.
Referenced by Character::all_items_loc(), and outfit::all_items_loc().