Cataclysm DDA: src/character_armor.cpp File Reference
character_armor.cpp File Reference
#include <algorithm>
#include <list>
#include <map>
#include <memory>
#include <string>
#include <utility>
#include <vector>
#include "bionics.h"
#include "bodypart.h"
#include "character.h"
#include "character_attire.h"
#include "damage.h"
#include "enums.h"
#include "flag.h"
#include "item.h"
#include "item_pocket.h"
#include "itype.h"
#include "line.h"
#include "magic_enchantment.h"
#include "make_static.h"
#include "map.h"
#include "material.h"
#include "memorial_logger.h"
#include "mutation.h"
#include "npc.h"
#include "output.h"
#include "pimpl.h"
#include "point.h"
#include "rng.h"
#include "subbodypart.h"
#include "translation.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "viewer.h"
Functions
static void armor_enchantment_adjust (Character &guy, damage_unit &du)
void destroyed_armor_msg (Character &who, const std::string &pre_damage_name)
void post_absorbed_damage_enchantment_adjust (Character &guy, damage_unit &du)
Variables
static const bionic_id bio_ads ("bio_ads")
static const json_character_flag json_flag_SEESLEEP ("SEESLEEP")
Function Documentation
armor_enchantment_adjust()
static void armor_enchantment_adjust (Character & guy, damage_unit & du) static
Definition at line 125 of file character_armor.cpp.
 {
     //If we're not dealing any damage of the given type, don't even bother.
     if( du.amount < 0.1f ) {
         return;
     }
     // FIXME: hardcoded damage types -> enchantments
     if( du.type == STATIC( damage_type_id( "acid" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_ACID );
     } else if( du.type == STATIC( damage_type_id( "bash" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_BASH );
     } else if( du.type == STATIC( damage_type_id( "biological" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_BIO );
     } else if( du.type == STATIC( damage_type_id( "cold" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_COLD );
     } else if( du.type == STATIC( damage_type_id( "cut" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_CUT );
     } else if( du.type == STATIC( damage_type_id( "electric" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_ELEC );
     } else if( du.type == STATIC( damage_type_id( "heat" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_HEAT );
     } else if( du.type == STATIC( damage_type_id( "stab" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_STAB );
     } else if( du.type == STATIC( damage_type_id( "bullet" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_BULLET );
     }
     if( du.type != STATIC( damage_type_id( "pure" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_ALL );
     }
     du.amount = std::max( 0.0f, du.amount );
 }
References damage_unit::amount, enchant_vals::ARMOR_ACID, enchant_vals::ARMOR_ALL, enchant_vals::ARMOR_BASH, enchant_vals::ARMOR_BIO, enchant_vals::ARMOR_BULLET, enchant_vals::ARMOR_COLD, enchant_vals::ARMOR_CUT, enchant_vals::ARMOR_ELEC, enchant_vals::ARMOR_HEAT, enchant_vals::ARMOR_STAB, Character::calculate_by_enchantment(), max(), STATIC, and damage_unit::type.
Referenced by Character::absorb_hit().
destroyed_armor_msg()
void destroyed_armor_msg (Character & who, const std::string & pre_damage_name)
Definition at line 157 of file character_armor.cpp.
 {
     if( who.is_avatar() ) {
         get_memorial().add(
             //~ %s is armor name
             pgettext( "memorial_male", "Worn %s was completely destroyed." ),
             pgettext( "memorial_female", "Worn %s was completely destroyed." ),
             pre_damage_name );
     }
     who.add_msg_player_or_npc( m_bad, _( "Your %s is completely destroyed!" ),
                                _( "<npcname>'s %s is completely destroyed!" ),
                                pre_damage_name );
 }
References _, memorial_logger::add(), Character::add_msg_player_or_npc(), get_memorial(), Creature::is_avatar(), m_bad, and pgettext.
Referenced by Character::ablative_armor_absorb(), and outfit::absorb_damage().
post_absorbed_damage_enchantment_adjust()
void post_absorbed_damage_enchantment_adjust (Character & guy, damage_unit & du)
Definition at line 171 of file character_armor.cpp.
 {
     // FIXME: hardcoded damage types -> enchantments
     if( du.type == STATIC( damage_type_id( "acid" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_ACID );
     } else if( du.type == STATIC( damage_type_id( "bash" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_BASH );
     } else if( du.type == STATIC( damage_type_id( "biological" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_BIO );
     } else if( du.type == STATIC( damage_type_id( "cold" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_COLD );
     } else if( du.type == STATIC( damage_type_id( "cut" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_CUT );
     } else if( du.type == STATIC( damage_type_id( "electric" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_ELEC );
     } else if( du.type == STATIC( damage_type_id( "heat" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_HEAT );
     } else if( du.type == STATIC( damage_type_id( "stab" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_STAB );
     } else if( du.type == STATIC( damage_type_id( "bullet" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_BULLET );
     }
     du.amount = std::max( 0.0f, du.amount );
 }
References damage_unit::amount, Character::calculate_by_enchantment(), enchant_vals::EXTRA_ACID, enchant_vals::EXTRA_BASH, enchant_vals::EXTRA_BIO, enchant_vals::EXTRA_BULLET, enchant_vals::EXTRA_COLD, enchant_vals::EXTRA_CUT, enchant_vals::EXTRA_ELEC, enchant_vals::EXTRA_HEAT, enchant_vals::EXTRA_STAB, max(), STATIC, and damage_unit::type.
Referenced by Character::absorb_hit().
Variable Documentation
bio_ads
const bionic_id bio_ads("bio_ads") ("bio_ads") static
Referenced by Character::absorb_hit().
json_flag_SEESLEEP
const json_character_flag json_flag_SEESLEEP("SEESLEEP") ("SEESLEEP") static
Referenced by Character::get_env_resist().