Cataclysm DDA: src/character_body.cpp File Reference
character_body.cpp File Reference
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>
#include "activity_tracker.h"
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_attire.h"
#include "color.h"
#include "creature.h"
#include "display.h"
#include "effect.h"
#include "enums.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "magic.h"
#include "magic_enchantment.h"
#include "make_static.h"
#include "map.h"
#include "mapdata.h"
#include "messages.h"
#include "morale_types.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "rng.h"
#include "stomach.h"
#include "string_formatter.h"
#include "translation.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vitamin.h"
#include "vpart_position.h"
#include "weather.h"
#include "weather_gen.h"
Functions
static int ticks_between (const time_point &from, const time_point &to, const time_duration &tick_length)
Variables
static const bionic_id bio_sleep_shutdown ("bio_sleep_shutdown")
static const character_modifier_id character_modifier_stamina_recovery_breathing_mod ("stamina_recovery_breathing_mod")
static const efftype_id effect_adrenaline ("adrenaline")
static const efftype_id effect_bandaged ("bandaged")
static const efftype_id effect_betablock ("betablock")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_blisters ("blisters")
static const efftype_id effect_cig ("cig")
static const efftype_id effect_cold ("cold")
static const efftype_id effect_common_cold ("common_cold")
static const efftype_id effect_disinfected ("disinfected")
static const efftype_id effect_flu ("flu")
static const efftype_id effect_frostbite ("frostbite")
static const efftype_id effect_frostbite_recovery ("frostbite_recovery")
static const efftype_id effect_hot ("hot")
static const efftype_id effect_hot_speed ("hot_speed")
static const efftype_id effect_hunger_blank ("hunger_blank")
static const efftype_id effect_hunger_engorged ("hunger_engorged")
static const efftype_id effect_hunger_famished ("hunger_famished")
static const efftype_id effect_hunger_full ("hunger_full")
static const efftype_id effect_hunger_hungry ("hunger_hungry")
static const efftype_id effect_hunger_near_starving ("hunger_near_starving")
static const efftype_id effect_hunger_satisfied ("hunger_satisfied")
static const efftype_id effect_hunger_starving ("hunger_starving")
static const efftype_id effect_hunger_very_hungry ("hunger_very_hungry")
static const efftype_id effect_hypovolemia ("hypovolemia")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_mending ("mending")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_wet ("wet")
static const itype_id itype_rm13_armor_on ("rm13_armor_on")
static const json_character_flag json_flag_COLDBLOOD ("COLDBLOOD")
static const json_character_flag json_flag_COLDBLOOD2 ("COLDBLOOD2")
static const json_character_flag json_flag_COLDBLOOD3 ("COLDBLOOD3")
static const json_character_flag json_flag_ECTOTHERM ("ECTOTHERM")
static const json_character_flag json_flag_HEATSINK ("HEATSINK")
static const json_character_flag json_flag_HEAT_IMMUNE ("HEAT_IMMUNE")
static const json_character_flag json_flag_IGNORE_TEMP ("IGNORE_TEMP")
static const json_character_flag json_flag_LIMB_LOWER ("LIMB_LOWER")
static const json_character_flag json_flag_NO_THIRST ("NO_THIRST")
static const json_character_flag json_flag_PAIN_IMMUNE ("PAIN_IMMUNE")
static const trait_id trait_BARK ("BARK")
static const trait_id trait_CHITIN_FUR ("CHITIN_FUR")
static const trait_id trait_CHITIN_FUR2 ("CHITIN_FUR2")
static const trait_id trait_CHITIN_FUR3 ("CHITIN_FUR3")
static const trait_id trait_DEBUG_LS ("DEBUG_LS")
static const trait_id trait_DEBUG_NOTEMP ("DEBUG_NOTEMP")
static const trait_id trait_FELINE_FUR ("FELINE_FUR")
static const trait_id trait_FUR ("FUR")
static const trait_id trait_LIGHTFUR ("LIGHTFUR")
static const trait_id trait_LUPINE_FUR ("LUPINE_FUR")
static const trait_id trait_M_DEPENDENT ("M_DEPENDENT")
static const trait_id trait_PYROMANIA ("PYROMANIA")
static const trait_id trait_SLIMY ("SLIMY")
static const trait_id trait_URSINE_FUR ("URSINE_FUR")
static const vitamin_id vitamin_blood ("blood")
Function Documentation
ticks_between()
static int ticks_between (const time_point & from, const time_point & to, const time_duration & tick_length) static
Definition at line 224 of file character_body.cpp.
 {
     return ( to_turn<int>( to ) / to_turns<int>( tick_length ) ) - ( to_turn<int>
             ( from ) / to_turns<int>( tick_length ) );
 }
Referenced by Character::update_body(), and Character::update_stomach().
Variable Documentation
bio_sleep_shutdown
const bionic_id bio_sleep_shutdown("bio_sleep_shutdown") ("bio_sleep_shutdown") static
Referenced by Character::update_bodytemp().
character_modifier_stamina_recovery_breathing_mod
const character_modifier_id character_modifier_stamina_recovery_breathing_mod("stamina_recovery_breathing_mod") ("stamina_recovery_breathing_mod") static
Referenced by Character::update_body().
effect_adrenaline
const efftype_id effect_adrenaline("adrenaline") ("adrenaline") static
Referenced by Character::update_heartrate_index().
effect_bandaged
const efftype_id effect_bandaged("bandaged") ("bandaged") static
Referenced by Character::body_window().
effect_betablock
const efftype_id effect_betablock("betablock") ("betablock") static
Referenced by Character::update_heartrate_index().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by Character::body_window().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by Character::body_window().
effect_blisters
const efftype_id effect_blisters("blisters") ("blisters") static
Referenced by Character::update_bodytemp().
effect_cig
const efftype_id effect_cig("cig") ("cig") static
Referenced by Character::update_heartrate_index().
effect_cold
const efftype_id effect_cold("cold") ("cold") static
Referenced by Character::update_bodytemp().
effect_common_cold
const efftype_id effect_common_cold("common_cold") ("common_cold") static
Referenced by Character::update_bodytemp().
effect_disinfected
const efftype_id effect_disinfected("disinfected") ("disinfected") static
Referenced by Character::body_window().
effect_flu
const efftype_id effect_flu("flu") ("flu") static
Referenced by Character::update_bodytemp().
effect_frostbite
const efftype_id effect_frostbite("frostbite") ("frostbite") static
Referenced by Character::update_bodytemp(), and Character::update_frostbite().
effect_frostbite_recovery
const efftype_id effect_frostbite_recovery("frostbite_recovery") ("frostbite_recovery") static
Referenced by Character::update_frostbite().
effect_hot
const efftype_id effect_hot("hot") ("hot") static
Referenced by Character::update_bodytemp().
effect_hot_speed
const efftype_id effect_hot_speed("hot_speed") ("hot_speed") static
Referenced by Character::update_bodytemp().
effect_hunger_blank
const efftype_id effect_hunger_blank("hunger_blank") ("hunger_blank") static
Referenced by Character::update_stomach().
effect_hunger_engorged
const efftype_id effect_hunger_engorged("hunger_engorged") ("hunger_engorged") static
Referenced by Character::update_stomach().
effect_hunger_famished
const efftype_id effect_hunger_famished("hunger_famished") ("hunger_famished") static
Referenced by Character::update_stomach().
effect_hunger_full
const efftype_id effect_hunger_full("hunger_full") ("hunger_full") static
Referenced by Character::update_stomach().
effect_hunger_hungry
const efftype_id effect_hunger_hungry("hunger_hungry") ("hunger_hungry") static
Referenced by Character::update_stomach().
effect_hunger_near_starving
const efftype_id effect_hunger_near_starving("hunger_near_starving") ("hunger_near_starving") static
Referenced by Character::update_stomach().
effect_hunger_satisfied
const efftype_id effect_hunger_satisfied("hunger_satisfied") ("hunger_satisfied") static
Referenced by Character::update_stomach().
effect_hunger_starving
const efftype_id effect_hunger_starving("hunger_starving") ("hunger_starving") static
Referenced by Character::update_stomach().
effect_hunger_very_hungry
const efftype_id effect_hunger_very_hungry("hunger_very_hungry") ("hunger_very_hungry") static
Referenced by Character::update_stomach().
effect_hypovolemia
const efftype_id effect_hypovolemia("hypovolemia") ("hypovolemia") static
Referenced by Character::update_body().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by Character::body_window().
effect_mending
const efftype_id effect_mending("mending") ("mending") static
Referenced by Character::body_window().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by Character::update_bodytemp().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by Character::update_bodytemp().
effect_wet
const efftype_id effect_wet("wet") ("wet") static
Referenced by Character::update_body_wetness().
itype_rm13_armor_on
const itype_id itype_rm13_armor_on("rm13_armor_on") ("rm13_armor_on") static
Referenced by Character::update_bodytemp().
json_flag_COLDBLOOD
const json_character_flag json_flag_COLDBLOOD("COLDBLOOD") ("COLDBLOOD") static
Referenced by Character::update_heartrate_index().
json_flag_COLDBLOOD2
const json_character_flag json_flag_COLDBLOOD2("COLDBLOOD2") ("COLDBLOOD2") static
Referenced by Character::update_heartrate_index().
json_flag_COLDBLOOD3
const json_character_flag json_flag_COLDBLOOD3("COLDBLOOD3") ("COLDBLOOD3") static
Referenced by Character::update_heartrate_index().
json_flag_ECTOTHERM
const json_character_flag json_flag_ECTOTHERM("ECTOTHERM") ("ECTOTHERM") static
Referenced by Character::update_heartrate_index().
json_flag_HEAT_IMMUNE
const json_character_flag json_flag_HEAT_IMMUNE("HEAT_IMMUNE") ("HEAT_IMMUNE") static
Referenced by Character::update_bodytemp().
json_flag_HEATSINK
const json_character_flag json_flag_HEATSINK("HEATSINK") ("HEATSINK") static
Referenced by Character::update_bodytemp().
json_flag_IGNORE_TEMP
const json_character_flag json_flag_IGNORE_TEMP("IGNORE_TEMP") ("IGNORE_TEMP") static
Referenced by Character::update_body_wetness(), and Character::update_bodytemp().
json_flag_LIMB_LOWER
const json_character_flag json_flag_LIMB_LOWER("LIMB_LOWER") ("LIMB_LOWER") static
Referenced by Character::update_bodytemp().
json_flag_NO_THIRST
const json_character_flag json_flag_NO_THIRST("NO_THIRST") ("NO_THIRST") static
Referenced by Character::update_stomach().
json_flag_PAIN_IMMUNE
const json_character_flag json_flag_PAIN_IMMUNE("PAIN_IMMUNE") ("PAIN_IMMUNE") static
Referenced by Character::body_window().
trait_BARK
const trait_id trait_BARK("BARK") ("BARK") static
Referenced by Character::update_bodytemp().
trait_CHITIN_FUR
const trait_id trait_CHITIN_FUR("CHITIN_FUR") ("CHITIN_FUR") static
Referenced by Character::update_body_wetness().
trait_CHITIN_FUR2
const trait_id trait_CHITIN_FUR2("CHITIN_FUR2") ("CHITIN_FUR2") static
Referenced by Character::update_body_wetness().
trait_CHITIN_FUR3
const trait_id trait_CHITIN_FUR3("CHITIN_FUR3") ("CHITIN_FUR3") static
Referenced by Character::update_body_wetness().
trait_DEBUG_LS
const trait_id trait_DEBUG_LS("DEBUG_LS") ("DEBUG_LS") static
Referenced by Character::update_stomach().
trait_DEBUG_NOTEMP
const trait_id trait_DEBUG_NOTEMP("DEBUG_NOTEMP") ("DEBUG_NOTEMP") static
Referenced by Character::update_bodytemp().
trait_FELINE_FUR
const trait_id trait_FELINE_FUR("FELINE_FUR") ("FELINE_FUR") static
Referenced by Character::update_body_wetness().
trait_FUR
const trait_id trait_FUR("FUR") ("FUR") static
Referenced by Character::update_body_wetness().
trait_LIGHTFUR
const trait_id trait_LIGHTFUR("LIGHTFUR") ("LIGHTFUR") static
Referenced by Character::update_body_wetness().
trait_LUPINE_FUR
const trait_id trait_LUPINE_FUR("LUPINE_FUR") ("LUPINE_FUR") static
Referenced by Character::update_body_wetness().
trait_M_DEPENDENT
const trait_id trait_M_DEPENDENT("M_DEPENDENT") ("M_DEPENDENT") static
Referenced by Character::update_stomach().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by Character::update_bodytemp().
trait_SLIMY
const trait_id trait_SLIMY("SLIMY") ("SLIMY") static
Referenced by Character::update_body_wetness().
trait_URSINE_FUR
const trait_id trait_URSINE_FUR("URSINE_FUR") ("URSINE_FUR") static
Referenced by Character::update_body_wetness().
vitamin_blood
const vitamin_id vitamin_blood("blood") ("blood") static
Referenced by Character::update_bloodvol_index(), and Character::update_body().