Cataclysm DDA: src/character_escape.cpp File Reference
character_escape.cpp File Reference
#include <algorithm>
#include <memory>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "character.h"
#include "character_attire.h"
#include "character_martial_arts.h"
#include "creature_tracker.h"
#include "damage.h"
#include "debug.h"
#include "effect.h"
#include "enums.h"
#include "flag.h"
#include "item.h"
#include "item_pocket.h"
#include "map.h"
#include "map_iterator.h"
#include "martialarts.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "output.h"
#include "pimpl.h"
#include "point.h"
#include "rng.h"
#include "translation.h"
#include "translations.h"
#include "type_id.h"
Variables
static const character_modifier_id character_modifier_grab_break_limb_mod ("grab_break_limb_mod")
static const efftype_id effect_beartrap ("beartrap")
static const efftype_id effect_crushed ("crushed")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_heavysnare ("heavysnare")
static const efftype_id effect_in_pit ("in_pit")
static const efftype_id effect_lightsnare ("lightsnare")
static const efftype_id effect_webbed ("webbed")
static const flag_id json_flag_GRAB ("GRAB")
static const itype_id itype_rope_6 ("rope_6")
static const itype_id itype_snare_trigger ("snare_trigger")
static const json_character_flag json_flag_DOWNED_RECOVERY ("DOWNED_RECOVERY")
static const limb_score_id limb_score_balance ("balance")
static const limb_score_id limb_score_grip ("grip")
static const limb_score_id limb_score_manip ("manip")
static const skill_id skill_melee ("melee")
static const skill_id skill_unarmed ("unarmed")
static const trait_id trait_SLIMY ("SLIMY")
static const trait_id trait_VISCOUS ("VISCOUS")
Variable Documentation
character_modifier_grab_break_limb_mod
const character_modifier_id character_modifier_grab_break_limb_mod("grab_break_limb_mod") ("grab_break_limb_mod") static
Referenced by Character::try_remove_grab().
effect_beartrap
const efftype_id effect_beartrap("beartrap") ("beartrap") static
Referenced by Character::move_effects(), Character::try_remove_bear_trap(), and Character::wait_effects().
effect_crushed
const efftype_id effect_crushed("crushed") ("crushed") static
Referenced by Character::move_effects(), and Character::try_remove_crushed().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by Character::move_effects(), Character::try_remove_downed(), and Character::wait_effects().
effect_heavysnare
const efftype_id effect_heavysnare("heavysnare") ("heavysnare") static
Referenced by Character::move_effects(), Character::try_remove_heavysnare(), and Character::wait_effects().
effect_in_pit
const efftype_id effect_in_pit("in_pit") ("in_pit") static
Referenced by Character::move_effects().
effect_lightsnare
const efftype_id effect_lightsnare("lightsnare") ("lightsnare") static
Referenced by Character::move_effects(), Character::try_remove_lightsnare(), and Character::wait_effects().
effect_webbed
const efftype_id effect_webbed("webbed") ("webbed") static
Referenced by Character::move_effects(), Character::try_remove_webs(), and Character::wait_effects().
itype_rope_6
const itype_id itype_rope_6("rope_6") ("rope_6") static
Referenced by Character::try_remove_heavysnare().
itype_snare_trigger
const itype_id itype_snare_trigger("snare_trigger") ("snare_trigger") static
Referenced by Character::try_remove_heavysnare().
json_flag_DOWNED_RECOVERY
const json_character_flag json_flag_DOWNED_RECOVERY("DOWNED_RECOVERY") ("DOWNED_RECOVERY") static
Referenced by Character::try_remove_downed().
json_flag_GRAB
const flag_id json_flag_GRAB("GRAB") ("GRAB") static
Referenced by Character::move_effects(), Character::try_remove_grab(), and Character::wait_effects().
limb_score_balance
const limb_score_id limb_score_balance("balance") ("balance") static
Referenced by Character::try_remove_downed().
limb_score_grip
const limb_score_id limb_score_grip("grip") ("grip") static
Referenced by Character::can_escape_trap().
limb_score_manip
const limb_score_id limb_score_manip("manip") ("manip") static
Referenced by Character::can_escape_trap().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by Character::try_remove_grab().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by Character::try_remove_grab().
trait_SLIMY
const trait_id trait_SLIMY("SLIMY") ("SLIMY") static
Referenced by Character::try_remove_grab().
trait_VISCOUS
const trait_id trait_VISCOUS("VISCOUS") ("VISCOUS") static
Referenced by Character::try_remove_grab().