Cataclysm DDA: src/character_guns.cpp File Reference
character_guns.cpp File Reference
#include <algorithm>
#include <cstddef>
#include <functional>
#include <iterator>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "character.h"
#include "color.h"
#include "debug.h"
#include "enums.h"
#include "flag.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "map_selector.h"
#include "player_activity.h"
#include "ret_val.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "value_ptr.h"
#include "vehicle_selector.h"
#include "visitable.h"
Functions
template<typename T , typename Output >
void find_ammo_helper (T &src, const item &obj, bool empty, Output out, bool nested)
Variables
static const itype_id itype_large_repairkit ("large_repairkit")
static const itype_id itype_small_repairkit ("small_repairkit")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
Function Documentation
find_ammo_helper()
template<typename T , typename Output > void find_ammo_helper (T & src, const item & obj, bool empty, Output out, bool nested)
Definition at line 38 of file character_guns.cpp.
 {
     src.visit_items( [&src, &nested, &out, &obj, empty]( item * node, item * parent ) {
         // This stops containers and magazines counting *themselves* as ammo sources
         if( node == &obj ) {
             return VisitResponse::SKIP;
         }
         // Spills are not valid. spilled liquids have no parent.
         if( parent == nullptr && node->made_of_from_type( phase_id::LIQUID ) ) {
             return VisitResponse::SKIP;
         }
         // Frozen liquids can't be loaded
         if( node->is_frozen_liquid() ) {
             return VisitResponse::SKIP;
         }
         // Do not steal ammo from magazines
         if( parent != nullptr && parent->is_magazine() ) {
             return VisitResponse::SKIP;
         }
         // Do not steal magazines from other items
         if( parent != nullptr && node == parent->magazine_current() ) {
             return VisitResponse::SKIP;
         }
         // Do not consider empty mags unless specified
         if( node->is_magazine() && !node->ammo_remaining() && !empty ) {
             return VisitResponse::SKIP;
         }
         if( node->has_flag( flag_SPEEDLOADER ) && obj.magazine_integral() ) {
             // Can't reload with empty speedloaders
             if( !node->ammo_remaining() ) {
                 return VisitResponse::SKIP;
             }
             // All speedloaders are accepted.
             // Ammo check is done somewhere else
             // Ammo check should probably happen here...
             if( obj.can_reload_with( *node, true ) ) {
                 if( parent != nullptr ) {
                     out = item_location( item_location( src, parent ), node );
                 } else {
                     out = item_location( src, node );
                 }
             }
             return VisitResponse::SKIP;
         }
         if( obj.can_reload_with( *node, true ) ) {
             if( parent != nullptr ) {
                 out = item_location( item_location( src, parent ), node );
             } else {
                 out = item_location( src, node );
             }
         }
         // Not-nested checks only top level containers and their immediate contents.
         return parent == nullptr || nested ? VisitResponse::NEXT : VisitResponse::SKIP;
     } );
 }
References item::ammo_remaining(), flag_SPEEDLOADER, item::has_flag(), item::is_frozen_liquid(), item::is_magazine(), LIQUID, item::made_of_from_type(), item::magazine_current(), int_id< T >::obj(), and SKIP.
Referenced by Character::find_ammo().
Variable Documentation
itype_large_repairkit
const itype_id itype_large_repairkit("large_repairkit") ("large_repairkit") static
Referenced by Character::gunmod_add().
itype_small_repairkit
const itype_id itype_small_repairkit("small_repairkit") ("small_repairkit") static
Referenced by Character::gunmod_add().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by Character::gunmod_add(), Character::gunmod_installation_odds(), and Character::gunmod_remove().