Cataclysm DDA: src/character_attire.h File Reference
character_attire.h File Reference
#include <cstddef>
#include <functional>
#include <iosfwd>
#include <list>
#include <map>
#include <optional>
#include <set>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>
#include "body_part_set.h"
#include "bodypart.h"
#include "color.h"
#include "item.h"
#include "item_location.h"
#include "ret_val.h"
#include "subbodypart.h"
#include "type_id.h"
#include "units.h"
#include "visitable.h"
Classes
struct item_penalties
struct layering_item_info
struct dispose_option
class outfit
Macros
#define CATA_SRC_CHARACTER_ATTIRE_H
Typedefs
using drop_location = std::pair< item_location, int >
using drop_locations = std::list< drop_location >
Functions
units::mass get_selected_stack_weight (const item *i, const std::map< const item *, int > &without)
void post_absorbed_damage_enchantment_adjust (Character &guy, damage_unit &du)
void destroyed_armor_msg (Character &who, const std::string &pre_damage_name)
Macro Definition Documentation
CATA_SRC_CHARACTER_ATTIRE_H
#define CATA_SRC_CHARACTER_ATTIRE_H
Definition at line 3 of file character_attire.h.
Typedef Documentation
drop_location
using drop_location = std::pair<item_location, int>
Definition at line 41 of file character_attire.h.
drop_locations
using drop_locations = std::list<drop_location>
Definition at line 42 of file character_attire.h.
Function Documentation
destroyed_armor_msg()
void destroyed_armor_msg (Character & who, const std::string & pre_damage_name)
Definition at line 157 of file character_armor.cpp.
 {
     if( who.is_avatar() ) {
         get_memorial().add(
             //~ %s is armor name
             pgettext( "memorial_male", "Worn %s was completely destroyed." ),
             pgettext( "memorial_female", "Worn %s was completely destroyed." ),
             pre_damage_name );
     }
     who.add_msg_player_or_npc( m_bad, _( "Your %s is completely destroyed!" ),
                                _( "<npcname>'s %s is completely destroyed!" ),
                                pre_damage_name );
 }
References _, memorial_logger::add(), Character::add_msg_player_or_npc(), get_memorial(), Creature::is_avatar(), m_bad, and pgettext.
Referenced by Character::ablative_armor_absorb(), and outfit::absorb_damage().
get_selected_stack_weight()
units::mass get_selected_stack_weight (const item * i, const std::map< const item *, int > & without)
Definition at line 96 of file character_attire.cpp.
 {
     auto stack = without.find( i );
     if( stack != without.end() ) {
         int selected = stack->second;
         item copy = *i;
         copy.charges = selected;
         return copy.weight();
     }
     return 0_gram;
 }
References item::charges, and item::weight().
Referenced by Character::weight_carried_with_tweaks(), and outfit::weight_carried_with_tweaks().
post_absorbed_damage_enchantment_adjust()
void post_absorbed_damage_enchantment_adjust (Character & guy, damage_unit & du)
Definition at line 171 of file character_armor.cpp.
 {
     // FIXME: hardcoded damage types -> enchantments
     if( du.type == STATIC( damage_type_id( "acid" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_ACID );
     } else if( du.type == STATIC( damage_type_id( "bash" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_BASH );
     } else if( du.type == STATIC( damage_type_id( "biological" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_BIO );
     } else if( du.type == STATIC( damage_type_id( "cold" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_COLD );
     } else if( du.type == STATIC( damage_type_id( "cut" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_CUT );
     } else if( du.type == STATIC( damage_type_id( "electric" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_ELEC );
     } else if( du.type == STATIC( damage_type_id( "heat" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_HEAT );
     } else if( du.type == STATIC( damage_type_id( "stab" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_STAB );
     } else if( du.type == STATIC( damage_type_id( "bullet" ) ) ) {
         du.amount = guy.calculate_by_enchantment( du.amount, enchant_vals::mod::EXTRA_BULLET );
     }
     du.amount = std::max( 0.0f, du.amount );
 }
References damage_unit::amount, Character::calculate_by_enchantment(), enchant_vals::EXTRA_ACID, enchant_vals::EXTRA_BASH, enchant_vals::EXTRA_BIO, enchant_vals::EXTRA_BULLET, enchant_vals::EXTRA_COLD, enchant_vals::EXTRA_CUT, enchant_vals::EXTRA_ELEC, enchant_vals::EXTRA_HEAT, enchant_vals::EXTRA_STAB, max(), STATIC, and damage_unit::type.
Referenced by Character::absorb_hit().