Cataclysm DDA: src/city.h File Reference
city.h File Reference
#include <string>
#include <string_view>
#include <vector>
#include "coordinates.h"
#include "type_id.h"
Classes
struct city
Macros
#define CATA_SRC_CITY_H
Functions
generic_factory< city > & get_city_factory ()
Macro Definition Documentation
CATA_SRC_CITY_H
#define CATA_SRC_CITY_H
Definition at line 3 of file city.h.
Function Documentation
get_city_factory()
generic_factory<city>& get_city_factory ()
Definition at line 19 of file city.cpp.
 {
     static generic_factory<city> city_factory( "city" );
     return city_factory;
 }
Referenced by city::check_consistency(), city::get_all(), city::load_city(), ordered_static_globals(), and city::reset().