Cataclysm DDA: select_ammo_inventory_preset Class Reference
select_ammo_inventory_preset Class Reference
Public Member Functions
select_ammo_inventory_preset (Character &you, const item_location &target, bool empty)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const override
Whether the first item is considered to go before the second.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual std::string get_denial (const item_location &) const
The reason why this entry cannot be selected.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Private Attributes
Character & you
const item_location target
bool empty
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 2783 of file game_inventory.cpp.
Constructor & Destructor Documentation
select_ammo_inventory_preset()
select_ammo_inventory_preset::select_ammo_inventory_preset (Character & you, const item_location & target, bool empty) inline
Definition at line 2786 of file game_inventory.cpp.
                                                    : you( you ),
             target( target ), empty( empty ) {
             _indent_entries = false;
             _collate_entries = true;
             append_cell( [&you]( const item_location & loc ) {
                 bool is_ammo_container = loc->is_ammo_container();
                 Character &player_character = get_player_character();
                 if( is_ammo_container || loc->is_container() ) {
                     if( is_ammo_container && you.is_worn( *loc ) ) {
                         return loc->type_name();
                     }
                     return string_format( _( "%s, %s" ), loc->type_name(), loc.describe( &player_character ) );
                 }
                 return loc.describe( &player_character );
             }, _( "LOCATION" ) );
             append_cell( [&you, target]( const item_location & loc ) {
                 for( const item_location &opt : get_possible_reload_targets( target ) ) {
                     if( opt->can_reload_with( *loc, true ) ) {
                         if( opt == target ) {
                             return std::string();
                         }
                         return string_format( _( "%s, %s" ), opt->type_name(), opt.describe( &you ) );
                     }
                 }
                 return std::string();
             }, _( "DESTINATION" ) );
             append_cell( []( const inventory_entry & entry ) {
                 if( entry.any_item()->is_ammo() ) {
                     return std::to_string( entry.chosen_count );
                 }
                 return std::string();
             }, _( "AMOUNT" ) );
             append_cell( [&you, &target]( const item_location & loc ) {
                 item::reload_option opt( &you, target, loc );
                 return std::to_string( opt.moves() );
             }, _( "MOVES" ) );
             append_cell( []( const item_location & loc ) {
                 const itype *ammo = loc->is_ammo_container() ? loc->first_ammo().ammo_data() :
                                     loc->ammo_data();
                 if( ammo ) {
                     const damage_instance &dam = ammo->ammo->damage;
                     return std::to_string( static_cast<int>( dam.total_damage() ) );
                 }
                 return std::string();
             }, _( "DAMAGE" ) );
             append_cell( []( const item_location & loc ) {
                 const itype *ammo = loc->is_ammo_container() ? loc->first_ammo().ammo_data() :
                                     loc->ammo_data();
                 if( ammo ) {
                     const damage_instance &dam = ammo->ammo->damage;
                     return std::to_string( static_cast<int>( dam.empty() ? 0.0f : ( *dam.begin() ).res_pen ) );
                 }
                 return std::string();
             }, _( "PIERCE" ) );
         }
References _, inventory_selector_preset::_collate_entries, inventory_selector_preset::_indent_entries, inventory_selector_preset::append_cell(), item_location::describe(), get_player_character(), get_possible_reload_targets(), item::is_ammo_container(), item::is_container(), Character::is_worn(), string_format(), target, item::type_name(), and you.
Member Function Documentation
is_shown()
bool select_ammo_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 2849 of file game_inventory.cpp.
{
             // todo: allow to reload a magazine/magazine well from a container pocket on the same item
             if( loc.parent_item() == target ) {
                 return false;
             }
             if( loc->made_of( phase_id::LIQUID ) && loc.where() == item_location::type::map ) {
                 map &here = get_map();
                 if( !here.has_flag_ter_or_furn( ter_furn_flag::TFLAG_LIQUIDCONT, loc.pos_bub() ) ) {
                     return false;
                 }
             }
             if( loc->is_frozen_liquid() ) {
                 return false;
             }
             if( !empty && loc->is_magazine() && !loc->ammo_remaining() ) {
                 return false;
             }
             std::vector<item_location> opts = get_possible_reload_targets( target );
             for( item_location &p : opts ) {
                 if( ( loc->has_flag( flag_SPEEDLOADER ) && p->allows_speedloader( loc->typeId() ) &&
                       loc->ammo_remaining() > 1 && p->ammo_remaining() < 1 ) && p->can_reload_with( *loc, true ) ) {
                     return true;
                 }
                 if( p->can_reload_with( *loc, true ) ) {
                     return true;
                 }
             }
             return false;
         }
References item::ammo_remaining(), flag_SPEEDLOADER, get_map(), get_possible_reload_targets(), item::has_flag(), map::has_flag_ter_or_furn(), item::is_frozen_liquid(), item::is_magazine(), LIQUID, item::made_of(), item_location::map, item_location::parent_item(), item_location::pos_bub(), TFLAG_LIQUIDCONT, item::typeId(), and item_location::where().
sort_compare()
bool select_ammo_inventory_preset::sort_compare (const inventory_entry & lhs, const inventory_entry & rhs) const inline override virtual
Whether the first item is considered to go before the second.
Reimplemented from inventory_selector_preset.
Definition at line 2887 of file game_inventory.cpp.
{
             item_location left = lhs.any_item();
             item_location right = rhs.any_item();
             if( left->ammo_remaining() == 0 || right->ammo_remaining() == 0 ) {
                 return ( left->ammo_remaining() != 0 ) > ( right->ammo_remaining() != 0 );
             }
             if( left.obtain_cost( you ) != right.obtain_cost( you ) ) {
                 return left.obtain_cost( you ) < right.obtain_cost( you );
             }
             if( left->ammo_remaining() != right->ammo_remaining() ) {
                 return left->ammo_remaining() > right->ammo_remaining();
             }
             return inventory_selector_preset::sort_compare( lhs, rhs );
         }
References inventory_entry::any_item(), keycode::left, keycode::right, and inventory_selector_preset::sort_compare().
Member Data Documentation
empty
bool select_ammo_inventory_preset::empty private
Definition at line 2909 of file game_inventory.cpp.
target
const item_location select_ammo_inventory_preset::target private
Definition at line 2908 of file game_inventory.cpp.
Referenced by select_ammo_inventory_preset().
you
Character& select_ammo_inventory_preset::you private
Definition at line 2907 of file game_inventory.cpp.
Referenced by select_ammo_inventory_preset().
The documentation for this class was generated from the following file:
src/game_inventory.cpp