Cataclysm DDA: JsonWithPath Class Reference
JsonWithPath Class Reference
#include <flexbuffer_json.h>
Public Member Functions
void throw_error (const std::string &message) const noexcept(false)
void throw_error (int offset, const std::string &message) const noexcept(false)
void throw_error_after (const std::string &message) const noexcept(false)
Protected Member Functions
JsonWithPath (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath &&path)
JsonWithPath (const JsonWithPath &)=default
JsonWithPath & operator= (const JsonWithPath &)=default
JsonWithPath (JsonWithPath &&) noexcept=default
JsonWithPath & operator= (JsonWithPath &&) noexcept=default
bool error_or_false (bool throw_on_error, const std::string &message) const noexcept(false)
Protected Member Functions inherited from Json
Json (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json)
~Json () noexcept=default
Json (const Json &)=default
Json & operator= (const Json &)=default
Json (Json &&) noexcept=default
Json & operator= (Json &&) noexcept=default
Json ()=delete
std::string str () const
void throw_error (const JsonPath &path, int offset, const std::string &message) const
void throw_error_after (const JsonPath &path, const std::string &message) const
void string_error (const JsonPath &path, int offset, const std::string &message) const
Protected Attributes
JsonPath path_
Protected Attributes inherited from Json
std::shared_ptr< parsed_flexbuffer > root_
flexbuffer json_
Additional Inherited Members
Protected Types inherited from Json
using flexbuffer = flexbuffers::Reference
Static Protected Member Functions inherited from Json
static const std::string & flexbuffer_type_to_string (flexbuffers::Type t)
static bool globally_report_unvisited_members (bool do_report)
Detailed Description
Definition at line 125 of file flexbuffer_json.h.
Constructor & Destructor Documentation
JsonWithPath() [1/3]
JsonWithPath::JsonWithPath (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath && path) inline protected
Definition at line 139 of file flexbuffer_json.h.
                                         : Json( std::move( root ), json ), path_{ std::move( path ) } {}
JsonWithPath() [2/3]
JsonWithPath::JsonWithPath (const JsonWithPath &) protected default
JsonWithPath() [3/3]
JsonWithPath::JsonWithPath (JsonWithPath &&) protected default noexcept
Member Function Documentation
error_or_false()
bool JsonWithPath::error_or_false (bool throw_on_error, const std::string & message) const inline protected noexcept
Definition at line 148 of file flexbuffer_json.h.
{
             if( throw_on_error ) {
                 throw_error( 0, message );
             }
             return false;
         }
References mapgen_defer::message, and Json::throw_error().
operator=() [1/2]
JsonWithPath& JsonWithPath::operator= (const JsonWithPath &) protected default
Referenced by JsonArray::operator=(), and JsonObject::operator=().
operator=() [2/2]
JsonWithPath& JsonWithPath::operator= (JsonWithPath &&) protected default noexcept
throw_error() [1/2]
void JsonWithPath::throw_error (const std::string & message) const inline noexcept
Definition at line 128 of file flexbuffer_json.h.
{
             throw_error( 0, message );
         }
References mapgen_defer::message, and Json::throw_error().
throw_error() [2/2]
void JsonWithPath::throw_error (int offset, const std::string & message) const inline noexcept
Definition at line 131 of file flexbuffer_json.h.
{
             Json::throw_error( path_, offset, message );
         }
References mapgen_defer::message, and Json::throw_error().
throw_error_after()
void JsonWithPath::throw_error_after (const std::string & message) const inline noexcept
Definition at line 134 of file flexbuffer_json.h.
{
             Json::throw_error_after( path_, message );
         }
References mapgen_defer::message, and Json::throw_error_after().
Member Data Documentation
path_
JsonPath JsonWithPath::path_ protected
Definition at line 156 of file flexbuffer_json.h.
Referenced by JsonObject::error_no_member(), JsonObject::error_skipped_members(), JsonObject::get_member(), JsonObject::get_member_opt(), JsonArray::next_enum_value(), JsonArray::operator[](), JsonObject::operator[](), JsonArray::string_error(), and JsonObject::throw_error().
The documentation for this class was generated from the following file:
src/flexbuffer_json.h