Cataclysm DDA: item_location Class Reference
item_location Class Reference
A lightweight handle to an item independent of it's location Unlike a raw pointer can be (de-)serialized to/from JSON Provides a generic interface of querying, obtaining and removing an item Is invalidated by many operations (including copying of the item)
#include <item_location.h>
Classes
class impl
Public Types
enum class type : int {
invalid = 0 , character = 1 , map = 2 , vehicle = 3 ,
container = 4
}
Public Member Functions
item_location ()
item_location (Character &ch, item *which)
item_location (const map_cursor &mc, item *which)
item_location (const vehicle_cursor &vc, item *which)
item_location (const item_location &container, item *which)
void serialize (JsonOut &js) const
void deserialize (const JsonObject &obj)
bool operator== (const item_location &rhs) const
bool operator!= (const item_location &rhs) const
operator bool () const
item & operator* ()
const item & operator* () const
item * operator-> ()
const item * operator-> () const
type where () const
Returns the type of location where the item is found.
type where_recursive () const
Returns the type of location where the topmost container of the item is found.
tripoint position () const
Returns the position where the item is found.
tripoint_bub_ms pos_bub () const
std::string describe (const Character *ch=nullptr) const
Describes the item location.
item_location obtain (Character &ch, int qty=-1)
Move an item from the location to the character inventory If the player fails to obtain the item (likely due to a menu) returns item_location{}.
int obtain_cost (const Character &ch, int qty=-1) const
Calculate (but do not deduct) number of moves required to obtain an item.
void remove_item ()
Removes the selected item from the game.
void on_contents_changed ()
Handles updates to the item location, mostly for caching.
void make_active ()
item * get_item ()
Gets the selected item or nullptr.
const item * get_item () const
void set_should_stack (bool should_stack) const
item_location parent_item () const
returns the parent item, or an invalid location if it has no parent
item_pocket * parent_pocket () const
Character * carrier () const
returns the character whose inventory contains this item, nullptr if none
bool held_by (Character const &who) const
returns true if the item is in the inventory of the given character
bool has_parent () const
true if this item location can and does have a parent
units::volume volume_capacity () const
Returns available volume capacity where this item is located.
units::mass weight_capacity () const
Returns available weight capacity where this item is located.
bool check_parent_capacity_recursive () const
Returns true if volume and weight capacity of all parent pockets >= 0.
bool protected_from_liquids () const
true if the item is inside a not open watertight container
ret_val< void > parents_can_contain_recursive (item *it) const
ret_val< int > max_charges_by_parent_recursive (const item &it) const
bool eventually_contains (item_location loc) const
Returns whether another item is eventually contained by this item.
void overflow ()
Overflow items into parent pockets recursively.
Static Public Attributes
static const item_location nowhere
Private Attributes
std::shared_ptr< impl > ptr
Detailed Description
A lightweight handle to an item independent of it's location Unlike a raw pointer can be (de-)serialized to/from JSON Provides a generic interface of querying, obtaining and removing an item Is invalidated by many operations (including copying of the item)
Definition at line 28 of file item_location.h.
Member Enumeration Documentation
type
enum item_location::type : int strong
Enumerator
invalid
character
map
vehicle
container
Definition at line 31 of file item_location.h.
                         : int {
             invalid = 0,
             character = 1,
             map = 2,
             vehicle = 3,
             container = 4
         };
Constructor & Destructor Documentation
item_location() [1/5]
item_location::item_location ()
Definition at line 755 of file item_location.cpp.
     : ptr( new impl::nowhere() ) {}
Referenced by item_location::impl::nowhere::obtain(), item_location::impl::item_in_container::obtain(), item_location::impl::item_on_map::obtain(), item_location::impl::item_on_person::obtain(), obtain(), and item_location::impl::parent_item().
item_location() [2/5]
item_location::item_location (Character & ch, item * which)
Definition at line 761 of file item_location.cpp.
     : ptr( new impl::item_on_person( ch, which ) ) {}
item_location() [3/5]
item_location::item_location (const map_cursor & mc, item * which)
Definition at line 758 of file item_location.cpp.
     : ptr( new impl::item_on_map( mc, which ) ) {}
item_location() [4/5]
item_location::item_location (const vehicle_cursor & vc, item * which)
Definition at line 764 of file item_location.cpp.
     : ptr( new impl::item_on_vehicle( vc, which ) ) {}
item_location() [5/5]
item_location::item_location (const item_location & container, item * which)
Definition at line 767 of file item_location.cpp.
     : ptr( new impl::item_in_container( container, which ) ) {}
Member Function Documentation
carrier()
Character * item_location::carrier () const
returns the character whose inventory contains this item, nullptr if none
Definition at line 1102 of file item_location.cpp.
 {
     return ptr->carrier();
 }
References ptr.
Referenced by advanced_inventory::action_examine(), item_location::impl::item_in_container::carrier(), reload_activity_actor::finish(), insert_item_activity_actor::finish(), held_by(), and item_pocket::overflow().
check_parent_capacity_recursive()
bool item_location::check_parent_capacity_recursive () const
Returns true if volume and weight capacity of all parent pockets >= 0.
Definition at line 1122 of file item_location.cpp.
 {
     return ptr->check_parent_capacity_recursive();
 }
References ptr.
Referenced by item_location::impl::item_in_container::check_parent_capacity_recursive(), and reload_activity_actor::finish().
describe()
std::string item_location::describe (const Character * ch = nullptr) const
Describes the item location.
Parameters
ch if set description is relative to character location
Definition at line 1022 of file item_location.cpp.
 {
     return ptr->describe( ch );
 }
References ptr.
Referenced by inventory_selector::_uncategorize(), inventory_selector::action_examine(), ebooksave_activity_actor::completed_scanning_current_book(), and select_ammo_inventory_preset::select_ammo_inventory_preset().
deserialize()
void item_location::deserialize (const JsonObject & obj)
Definition at line 810 of file item_location.cpp.
 {
     std::string type = obj.get_string( "type" );
     int idx = -1;
     tripoint pos = tripoint_min;
     obj.read( "idx", idx );
     obj.read( "pos", pos );
     if( type == "character" ) {
         character_id who_id;
         if( obj.has_member( "character" ) ) {
             obj.read( "character", who_id );
         } else {
             // This is for migrating saves before npc item locations were supported and all
             // character item locations were assumed to be on g->u
             who_id = get_player_character().getID();
         }
         ptr.reset( new impl::item_on_person( who_id, idx ) );
     } else if( type == "map" ) {
         ptr.reset( new impl::item_on_map( map_cursor( pos ), idx ) );
     } else if( type == "vehicle" ) {
         vehicle *const veh = veh_pointer_or_null( get_map().veh_at( pos ) );
         int part = obj.get_int( "part" );
         if( veh && part >= 0 && part < veh->part_count() ) {
             ptr.reset( new impl::item_on_vehicle( vehicle_cursor( *veh, part ), idx ) );
         }
     } else if( type == "in_container" ) {
         item_location parent;
         obj.read( "parent", parent );
         if( !parent.ptr->valid() ) {
             debugmsg( "parent location does not point to valid item" );
             ptr.reset( new impl::item_on_map( map_cursor( pos ), idx ) ); // drop on ground
             return;
         }
         const std::list<item *> parent_contents = parent->all_items_top();
         if( idx > -1 && idx < static_cast<int>( parent_contents.size() ) ) {
             auto iter = parent_contents.begin();
             std::advance( iter, idx );
             ptr.reset( new impl::item_in_container( parent, *iter ) );
         } else {
             // probably pointing to the wrong item
             debugmsg( "contents index greater than contents size" );
         }
     }
 }
References item::all_items_top(), debugmsg, JsonObject::get_int(), get_map(), get_player_character(), JsonObject::get_string(), Character::getID(), JsonObject::has_member(), math_opers::pos(), ptr, JsonObject::read(), tripoint_min, and veh_pointer_or_null().
eventually_contains()
bool item_location::eventually_contains (item_location loc) const
Returns whether another item is eventually contained by this item.
Definition at line 986 of file item_location.cpp.
 {
     while( loc.has_parent() ) {
         if( ( loc = loc.parent_item() ) == *this ) {
             return true;
         }
     }
     return false;
 }
References has_parent(), and parent_item().
Referenced by inventory_holster_preset::is_shown().
get_item() [1/2]
item * item_location::get_item ()
Gets the selected item or nullptr.
Definition at line 1087 of file item_location.cpp.
 {
     return ptr->target();
 }
References ptr.
Referenced by anonymous_namespace{npctrade.cpp}::_trading_price(), advanced_inventory::action_move_item(), anonymous_namespace{monexamine.cpp}::attach_saddle_to(), item::can_contain(), craft_activity_actor::canceled(), disassemble_activity_actor::canceled(), advanced_inv_area::canputitems(), change_armor_sprite(), item_search_data::check(), craft_activity_actor::check_if_craft_okay(), check_if_disassemble_okay(), Character::complete_disassemble(), Character::consume(), Character::create_in_progress_disassembly(), Character::crush_frozen_liquid(), salvage_actor::cut_up(), damage_item(), inventory_multiselector::deselect_contained_items(), disassemble_inventory_preset::disassemble_inventory_preset(), npc::discharge_cbm_weapon(), invoke_item_activity_actor::do_turn(), craft_activity_actor::do_turn(), inventory_pick_selector::execute(), unload_selector::execute(), favorite_ammo_or_select(), npc::find_item(), gunmod_remove_activity_actor::finish(), bionic_install_preset::get_anesth_amount(), get_auto_consume_moves(), get_autopickup_items(), get_child_pocket_with_parent(), gunmod_remove_inventory_preset::get_denial(), attach_veh_tool_inventory_preset::get_denial(), bionic_install_preset::get_denial(), bionic_install_surgeon_preset::get_denial(), bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), liquid_handler::get_liquid_target(), bionic_install_preset::get_operation_duration(), bionic_install_surgeon_preset::get_operation_duration(), craft_activity_actor::get_progress_message(), gunmod_remove_inventory_preset::gunmod_remove_inventory_preset(), heat_item(), activity_handlers::heat_item_finish(), game::inventory_item_menu(), inventory_holster_preset::is_shown(), salvage_inventory_preset::is_shown(), game::item_action_menu(), liquid_inventory_selector_preset::liquid_inventory_selector_preset(), aim_activity_actor::load_RAS_weapon(), map::make_active(), max_charges_by_parent_recursive(), target_handler::mode_reach(), advanced_inventory::move_all_items(), overflow(), parents_can_contain_recursive(), Character::perform_technique(), pick_one_up(), avatar_action::plthrow(), advanced_inventory::print_items(), rate_action_insert(), read(), item::reload(), game::reload(), reload_furniture(), run_item_eocs(), salvage_inventory_preset::salvage_inventory_preset(), item_pricing::set_values(), craft_activity_actor::start(), read_activity_actor::start(), Character::start_craft(), avatar::steal(), npc::stow_item(), inventory_multiselector::toggle_entries(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), salvage_actor::try_to_cut_up(), unload_activity_actor::unload(), map::update_lum(), holster_actor::use(), molle_attach_actor::use(), detach_gunmods_actor::use(), avatar_action::use_item(), salvage_actor::valid_to_cut_up(), and game::wield().
get_item() [2/2]
const item * item_location::get_item () const
Definition at line 1092 of file item_location.cpp.
 {
     return ptr->target();
 }
References ptr.
has_parent()
bool item_location::has_parent () const
true if this item location can and does have a parent
exists because calling parent_item() naively causes debug messages
Definition at line 876 of file item_location.cpp.
 {
     if( where() == type::container ) {
         return !!ptr->parent_item();
     }
     return false;
 }
References container, ptr, and where().
Referenced by inventory_selector::_uncategorize(), outfit::add_stash(), Character::can_crush_frozen_liquid(), advanced_inventory::change_square(), eventually_contains(), get_comestible_order(), inventory_holster_preset::get_denial(), pickup_inventory_preset::get_denial(), comestible_inventory_preset::get_order(), Character::handle_contents_changed(), inventory_selector::highlight(), game::inventory_item_menu(), wear_inventory_preset::is_shown(), pickup_inventory_preset::is_shown(), max_charges_by_parent_recursive(), obtain_activity_items(), parents_can_contain_recursive(), anonymous_namespace{inventory_ui.cpp}::path_to_top(), advanced_inventory::print_items(), protected_from_liquids(), item::reload(), contents_change_handler::unseal_pocket_containing(), avatar_action::use_item(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
held_by()
bool item_location::held_by (Character const & who) const
returns true if the item is in the inventory of the given character
Definition at line 1107 of file item_location.cpp.
 {
     return carrier() == &who;
 }
References carrier().
Referenced by advanced_inventory::action_move_item(), advanced_inventory::move_all_items(), item_location::impl::item_in_container::obtain(), item::reload(), avatar_action::use_item(), and npc::wants_to_sell().
make_active()
void item_location::make_active ()
Definition at line 1060 of file item_location.cpp.
 {
     if( !ptr->valid() ) {
         debugmsg( "item location does not point to valid item" );
         return;
     }
     switch( where() ) {
         case type::container: {
             parent_item().make_active();
             break;
         }
         case type::map: {
             get_map().make_active( *this );
             break;
         }
         case type::vehicle: {
             dynamic_cast<impl::item_on_vehicle *>( ptr.get() )->make_active( *this );
             break;
         }
         case type::invalid:
         case type::character: {
             // NOOP: characters don't cache active items
             break;
         }
     }
 }
References character, container, debugmsg, get_map(), invalid, make_active(), map::make_active(), map, parent_item(), ptr, vehicle, and where().
Referenced by insert_item_activity_actor::finish(), link_up_actor::link_extend_cable(), make_active(), liquid_handler::perform_liquid_transfer(), and avatar_action::use_item().
max_charges_by_parent_recursive()
ret_val< int > item_location::max_charges_by_parent_recursive (const item & it) const
Definition at line 927 of file item_location.cpp.
 {
     if( !has_parent() ) {
         return ret_val<int>::make_success( item::INFINITE_CHARGES );
     }
     float weight_multiplier = 1.0f;
     float volume_multiplier = 1.0f;
     units::mass max_weight = 1000_kilogram;
     units::volume max_volume = MAX_ITEM_VOLUME;
     item_location current_location = *this;
     //item_location class cannot return current pocket so use first pocket for innermost container
     //Only used for weight and volume multipliers
     const item_pocket *current_pocket = get_item()->get_all_standard_pockets().front();
     const pocket_data *current_pocket_data = current_pocket->get_pocket_data();
     //Repeat until top-most container reached
     while( current_location.has_parent() ) {
         //Multiply weight and volume multipliers for each container
         weight_multiplier = weight_multiplier * current_pocket_data->weight_multiplier;
         volume_multiplier = volume_multiplier * current_pocket_data->volume_multiplier;
         //Inserting into rigid pockets will not affect parent volume so stop keeping track
         if( current_pocket->rigid() ) {
             volume_multiplier = 0.0f;
         };
         //Weight multiplier of zero means parent containers are no longer affected so stop keeping track
         if( weight_multiplier > 0 ) {
             //Calculate effective remaining weight for current parent
             units::mass temp_weight = weight_capacity() / weight_multiplier;
             //Find the most restrictive weight to determine maximum charges
             max_weight = std::min( max_weight, temp_weight );
         }
         //Volume multiplier of zero means parent containers are no longer affected so stop keeping track
         if( volume_multiplier > 0 ) {
             //Calculate effective remaining volume for current parent
             units::volume temp_volume = volume_capacity() / volume_multiplier;
             //Find the most restrictive volume to determine maximum charges
             max_volume = std::min( max_volume, temp_volume );
         }
         //Move up one level of containers
         current_pocket = current_location.parent_pocket();
         current_pocket_data = current_pocket->get_pocket_data();
         current_location = current_location.parent_item();
     }
     int charges_weight = it.charges_per_weight( max_weight, true );
     if( charges_weight == 0 ) {
         return ret_val<int>::make_failure( 0, _( "item is too heavy for a parent pocket" ) );
     }
     int charges_volume = it.charges_per_volume( max_volume, true );
     if( charges_volume == 0 ) {
         return ret_val<int>::make_failure( 0, _( "item is too big for a parent pocket" ) );
     }
     return ret_val<int>::make_success( std::min( charges_weight, charges_volume ) );
 }
References _, item::charges_per_volume(), item::charges_per_weight(), item::get_all_standard_pockets(), get_item(), item_pocket::get_pocket_data(), has_parent(), item::INFINITE_CHARGES, ret_val< T >::make_failure(), ret_val< T >::make_success(), MAX_ITEM_VOLUME, min(), parent_item(), parent_pocket(), item_pocket::rigid(), volume_capacity(), pocket_data::volume_multiplier, weight_capacity(), and pocket_data::weight_multiplier.
Referenced by outfit::add_stash(), and Character::pour_into().
obtain()
item_location item_location::obtain (Character & ch, int qty = -1)
Move an item from the location to the character inventory If the player fails to obtain the item (likely due to a menu) returns item_location{}.
Parameters
ch Character who's inventory gets the item
qty if specified limits maximum obtained charges
Warning
caller should restack inventory if item is to remain in it
all further operations using this class are invalid
it is unsafe to call this within unsequenced operations (see #15542)
Returns
item_location for the item
Definition at line 1027 of file item_location.cpp.
 {
     if( !ptr->valid() ) {
         debugmsg( "item location does not point to valid item" );
         return item_location();
     }
     return ptr->obtain( ch, qty );
 }
References debugmsg, item_location(), and ptr.
Referenced by npc::do_npc_read(), read(), game::reload(), outfit::sort_armor(), takeoff(), saw_barrel_actor::use(), saw_stock_actor::use(), avatar_action::use_item(), and game::wield().
obtain_cost()
int item_location::obtain_cost (const Character & ch, int qty = -1) const
Calculate (but do not deduct) number of moves required to obtain an item.
See also
item_location::obtain
Definition at line 1036 of file item_location.cpp.
 {
     return ptr->obtain_cost( ch, qty );
 }
References ptr.
Referenced by obtain_activity_items(), item_location::impl::item_in_container::obtain_cost(), pick_one_up(), avatar_action::use_item(), game::wield(), avatar::wield(), and Character::wield_contents().
on_contents_changed()
void item_location::on_contents_changed ()
Handles updates to the item location, mostly for caching.
Definition at line 1051 of file item_location.cpp.
 {
     if( !ptr->valid() ) {
         debugmsg( "item location does not point to valid item" );
         return;
     }
     ptr->on_contents_changed();
 }
References debugmsg, and ptr.
Referenced by contents_change_handler::unseal_pocket_containing(), and avatar_action::use_item().
operator bool()
item_location::operator bool () const explicit
Definition at line 780 of file item_location.cpp.
 {
     return ptr->valid();
 }
operator!=()
bool item_location::operator!= (const item_location & rhs) const
Definition at line 775 of file item_location.cpp.
 {
     return ptr->target() != rhs.ptr->target();
 }
References ptr.
operator*() [1/2]
item & item_location::operator* ()
Definition at line 785 of file item_location.cpp.
 {
     return *ptr->target();
 }
References ptr.
operator*() [2/2]
const item & item_location::operator* () const
Definition at line 790 of file item_location.cpp.
 {
     return *ptr->target();
 }
References ptr.
operator->() [1/2]
item * item_location::operator-> ()
Definition at line 795 of file item_location.cpp.
 {
     return ptr->target();
 }
References ptr.
operator->() [2/2]
const item * item_location::operator-> () const
Definition at line 800 of file item_location.cpp.
 {
     return ptr->target();
 }
References ptr.
operator==()
bool item_location::operator== (const item_location & rhs) const
Definition at line 770 of file item_location.cpp.
 {
     return ptr->target() == rhs.ptr->target();
 }
References ptr.
overflow()
void item_location::overflow ()
Overflow items into parent pockets recursively.
Definition at line 996 of file item_location.cpp.
 {
     get_item()->overflow( position(), *this );
 }
References get_item(), item::overflow(), and position().
Referenced by move_items_activity_actor::do_turn(), Character::drop_invalid_inventory(), avatar_action::eat(), item_pocket::overflow(), smoker_load_food(), and avatar_action::use_item().
parent_item()
item_location item_location::parent_item () const
returns the parent item, or an invalid location if it has no parent
Definition at line 860 of file item_location.cpp.
 {
     if( where() == type::container ) {
         return ptr->parent_item();
     }
     return item_location::nowhere;
 }
References container, nowhere, ptr, and where().
Referenced by inventory_selector::_uncategorize(), inventory_column::add_entry(), advanced_inventory::change_square(), eventually_contains(), inventory_holster_preset::get_denial(), Character::handle_contents_changed(), inventory_selector::highlight(), game::inventory_item_menu(), is_bulk_load(), is_bulk_unload(), wear_inventory_preset::is_shown(), pickup_inventory_preset::is_shown(), select_ammo_inventory_preset::is_shown(), link_up_actor::link_extend_cable(), make_active(), max_charges_by_parent_recursive(), move_to_parent_pocket_recursive(), item::reload_option::moves(), parents_can_contain_recursive(), anonymous_namespace{inventory_ui.cpp}::path_to_top(), advanced_inventory::print_items(), protected_from_liquids(), item::reload(), Pickup::pick_info::set_src(), inventory_selector::toggle_categorize_contained(), contents_change_handler::unseal_pocket_containing(), avatar_action::use_item(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
parent_pocket()
item_pocket * item_location::parent_pocket () const
Definition at line 868 of file item_location.cpp.
 {
     if( where() == type::container ) {
         return ptr->parent_pocket();
     }
     return nullptr;
 }
References container, ptr, and where().
Referenced by Character::can_crush_frozen_liquid(), get_comestible_order(), comestible_inventory_preset::get_order(), Character::handle_contents_changed(), game::inventory_item_menu(), is_worn_ablative(), link_up_actor::link_extend_cable(), max_charges_by_parent_recursive(), move_to_parent_pocket_recursive(), parents_can_contain_recursive(), contents_change_handler::unseal_pocket_containing(), and avatar_action::use_item().
parents_can_contain_recursive()
ret_val< void > item_location::parents_can_contain_recursive (item * it) const
Definition at line 884 of file item_location.cpp.
 {
     item_pocket *parent_pocket;
     units::mass it_weight = it->weight();
     units::volume it_volume = it->volume();
     units::length it_length = it->length();
     item_location current_location = *this;
     //item_location class cannot return current pocket so use first pocket for innermost container
     //Only used for weight and volume multipliers
     const item_pocket *current_pocket = get_item()->get_all_standard_pockets().front();
     const pocket_data *current_pocket_data = current_pocket->get_pocket_data();
     //Repeat until top-most container reached
     while( current_location.has_parent() ) {
         parent_pocket = current_location.parent_pocket();
         //Ignore volume and length after innermost rigid container
         if( current_pocket->rigid() ) {
             it_volume = 0_ml;
             it_length = 0_mm;
         }
         //Multiply weight and volume multipliers for each container
         it_weight = it_weight * current_pocket_data->weight_multiplier;
         it_volume = it_volume * current_pocket_data->volume_multiplier;
         it_length = it_length * std::cbrt( current_pocket_data->volume_multiplier );
         if( it_weight > parent_pocket->remaining_weight() ) {
             return ret_val<void>::make_failure( _( "item is too heavy for a parent pocket" ) );
         } else if( it_volume > parent_pocket->remaining_volume() ) {
             return ret_val<void>::make_failure( _( "item is too big for a parent pocket" ) );
         } else if( it_length > parent_pocket->get_pocket_data()->max_item_length ) {
             return ret_val<void>::make_failure( _( "item is too long for a parent pocket" ) );
         }
         //Move up one level of containers
         current_pocket = parent_pocket;
         current_pocket_data = current_pocket->get_pocket_data();
         current_location = current_location.parent_item();
     }
     return ret_val<void>::make_success();
 }
References _, item::get_all_standard_pockets(), get_item(), item_pocket::get_pocket_data(), has_parent(), item::length(), ret_val< T >::make_failure(), ret_val< T >::make_success(), pocket_data::max_item_length, parent_item(), parent_pocket(), item_pocket::remaining_volume(), item_pocket::remaining_weight(), item_pocket::rigid(), item::volume(), pocket_data::volume_multiplier, item::weight(), and pocket_data::weight_multiplier.
Referenced by advanced_inventory::action_move_item(), and outfit::add_stash().
pos_bub()
tripoint_bub_ms item_location::pos_bub () const
Definition at line 1016 of file item_location.cpp.
 {
     // TODO: fix point types
     return tripoint_bub_ms( ptr->position() );
 }
References ptr.
Referenced by craft_activity_actor::check_if_craft_okay(), Character::complete_disassemble(), damage_item(), move_items_activity_actor::do_turn(), get_auto_consume_moves(), select_ammo_inventory_preset::is_shown(), and advanced_inventory::recalc_pane().
position()
tripoint item_location::position () const
Returns the position where the item is found.
Definition at line 1011 of file item_location.cpp.
 {
     return ptr->position();
 }
References ptr.
Referenced by inventory_selector::_uncategorize(), inventory_column::add_entry(), activity_handlers::butcher_finish(), Character::crush_frozen_liquid(), salvage_actor::cut_up(), disassemble_activity_actor::do_turn(), hacksaw_activity_actor::do_turn(), boltcutting_activity_actor::do_turn(), oxytorch_activity_actor::do_turn(), prying_activity_actor::do_turn(), craft_activity_actor::do_turn(), reload_activity_actor::finish(), firstaid_activity_actor::finish(), get_autopickup_items(), comestible_inventory_preset::get_denial(), hack_attempt(), heat_item(), vehicle::idle(), is_bulk_load(), pickup_inventory_preset::is_shown(), aim_activity_actor::load_RAS_weapon(), map::make_active(), vehicle::make_active(), overflow(), item_location::impl::item_in_container::position(), reload_furniture(), Pickup::pick_info::set_src(), iexamine::tree_maple(), iexamine::try_start_hacking(), map::update_lum(), Character::use(), and game::wield().
protected_from_liquids()
bool item_location::protected_from_liquids () const
true if the item is inside a not open watertight container
Definition at line 1127 of file item_location.cpp.
 {
     // check if inside a watertight which is not an open_container
     if( has_parent() ) {
         item_location parent = parent_item();
         // parent can protect the item against water
         if( parent->is_watertight_container() && !parent->will_spill() ) {
             return true;
         }
         // check the parent's parent
         return parent.protected_from_liquids();
     }
     // we recursively checked all containers
     // none are closed watertight containers
     return false;
 }
References has_parent(), item::is_watertight_container(), parent_item(), protected_from_liquids(), and item::will_spill().
Referenced by protected_from_liquids().
remove_item()
void item_location::remove_item ()
Removes the selected item from the game.
Warning
all further operations using this class are invalid
Definition at line 1041 of file item_location.cpp.
 {
     if( !ptr->valid() ) {
         debugmsg( "item location does not point to valid item" );
         return;
     }
     ptr->remove_item();
     ptr.reset( new impl::nowhere() );
 }
References debugmsg, and ptr.
Referenced by anonymous_namespace{monexamine.cpp}::add_armor(), anonymous_namespace{monexamine.cpp}::attach_saddle_to(), activity_handlers::butcher_finish(), craft_activity_actor::canceled(), Character::complete_disassemble(), veh_interact::complete_vehicle(), Character::consume(), Character::create_in_progress_disassembly(), salvage_actor::cut_up(), damage_item(), anonymous_namespace{iexamine.cpp}::atm_menu::do_exchange_cash(), wear_activity_actor::do_turn(), wield_activity_actor::do_turn(), craft_activity_actor::do_turn(), move_items_activity_actor::do_turn(), wash_activity_actor::finish(), reload_activity_actor::finish(), reel_cable_activity_actor::finish(), firstaid_activity_actor::finish(), gunmod_remove_activity_actor::gunmod_remove(), Character::handle_contents_changed(), Character::handle_melee_wear(), link_up_actor::link_extend_cable(), iexamine::nanofab(), npc::npc_dismount(), item_location::impl::item_in_container::obtain(), obtain_activity_items(), pick_one_up(), avatar::power_bionics(), item::reload(), reload_furniture(), smoker_load_food(), activity_handlers::start_fire_do_turn(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), unload_activity_actor::unload(), Character::unload(), ammobelt_actor::use(), molle_attach_actor::use(), Character::use(), Character::wear(), and game::wield().
serialize()
void item_location::serialize (JsonOut & js) const
Definition at line 805 of file item_location.cpp.
 {
     ptr->serialize( js );
 }
References ptr.
set_should_stack()
void item_location::set_should_stack (bool should_stack) const
Definition at line 1097 of file item_location.cpp.
 {
     ptr->should_stack = should_stack;
 }
References ptr.
volume_capacity()
units::volume item_location::volume_capacity () const
Returns available volume capacity where this item is located.
Definition at line 1112 of file item_location.cpp.
 {
     return ptr->volume_capacity();
 }
References ptr.
Referenced by link_up_actor::link_extend_cable(), and max_charges_by_parent_recursive().
weight_capacity()
units::mass item_location::weight_capacity () const
Returns available weight capacity where this item is located.
Definition at line 1117 of file item_location.cpp.
 {
     return ptr->weight_capacity();
 }
References ptr.
Referenced by link_up_actor::link_extend_cable(), and max_charges_by_parent_recursive().
where()
item_location::type item_location::where () const
Returns the type of location where the item is found.
Definition at line 1001 of file item_location.cpp.
 {
     return ptr->where();
 }
References ptr.
Referenced by inventory_selector::_uncategorize(), inventory_column::add_entry(), item::can_contain(), Character::consume(), salvage_actor::cut_up(), damage_item(), disassemble_activity_actor::do_turn(), craft_activity_actor::do_turn(), comestible_inventory_preset::get_denial(), Character::handle_contents_changed(), has_parent(), heat_item(), is_bulk_load(), is_bulk_unload(), anonymous_namespace{inventory_ui.cpp}::is_container(), pickup_inventory_preset::is_shown(), select_ammo_inventory_preset::is_shown(), link_up_actor::link_extend_cable(), make_active(), move_to_parent_pocket_recursive(), item_location::impl::item_in_container::obtain_cost(), parent_item(), parent_pocket(), rate_action_insert(), Character::rate_action_insert(), Pickup::pick_info::set_src(), read_activity_actor::start(), update_lum(), and game::wield().
where_recursive()
item_location::type item_location::where_recursive () const
Returns the type of location where the topmost container of the item is found.
Therefore can not return item_location::type::container
Definition at line 1006 of file item_location.cpp.
 {
     return ptr->where_recursive();
 }
References ptr.
Referenced by obtain_activity_items(), avatar_action::use_item(), and item_location::impl::item_in_container::where_recursive().
Member Data Documentation
nowhere
const item_location item_location::nowhere static
Definition at line 41 of file item_location.h.
Referenced by Character::add_or_drop_with_msg(), inventory_entry::any_item(), advanced_inventory::change_square(), game_menus::inv::common(), Character::create_in_progress_disassembly(), unload_activity_actor::deserialize(), reload_activity_actor::finish(), insert_item_activity_actor::finish(), Character::get_all_pocket_with_parent(), get_child_pocket_with_parent(), inventory_selector::highlight(), Character::i_add(), Character::i_add_or_fill(), inventory_examiner::inventory_examiner(), Character::migrate_items_to_storage(), item_location::impl::item_in_container::obtain(), parent_item(), pick_one_up(), advanced_inventory::print_header(), inventory_selector::rearrange_columns(), advanced_inventory::recalc_pane(), repair_item_finish(), set_item_inventory(), inventory_examiner::setup(), Character::try_add(), and Character::unload().
ptr
std::shared_ptr<impl> item_location::ptr private
Definition at line 160 of file item_location.h.
Referenced by carrier(), check_parent_capacity_recursive(), describe(), deserialize(), get_item(), has_parent(), make_active(), obtain(), obtain_cost(), on_contents_changed(), operator!=(), operator*(), operator->(), operator==(), parent_item(), parent_pocket(), pos_bub(), position(), remove_item(), serialize(), set_should_stack(), volume_capacity(), weight_capacity(), where(), and where_recursive().
The documentation for this class was generated from the following files:
src/item_location.h
src/item_location.cpp