Cataclysm DDA: tent_placement_activity_actor Class Reference
tent_placement_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
tent_placement_activity_actor (int moves_total, tripoint target, int radius, const item &it, string_id< furn_t > wall, string_id< furn_t > floor, std::optional< string_id< furn_t >> floor_center, string_id< furn_t > door_closed)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &p) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &, Character &p) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves_total
tripoint target
int radius = 1
item it
string_id< furn_t > wall
string_id< furn_t > floor
std::optional< string_id< furn_t > > floor_center
string_id< furn_t > door_closed
Detailed Description
Definition at line 1345 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
tent_placement_activity_actor()
tent_placement_activity_actor::tent_placement_activity_actor (int moves_total, tripoint target, int radius, const item & it, string_id< furn_t > wall, string_id< furn_t > floor, std::optional< string_id< furn_t >> floor_center, string_id< furn_t > door_closed) inline
Definition at line 1358 of file activity_actor_definitions.h.
                                                                        : moves_total( moves_total ), target( target ), radius( radius ),
             it( it ), wall( wall ), floor( floor ), floor_center( floor_center ),
             door_closed( door_closed ) {}
Member Function Documentation
canceled()
void tent_placement_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 5462 of file activity_actor.cpp.
 {
     map &here = get_map();
     here.add_item_or_charges( p.pos() + target, it, true );
 }
References map::add_item_or_charges(), get_map(), it, Creature::pos(), and target.
clone()
std::unique_ptr<activity_actor> tent_placement_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1373 of file activity_actor_definitions.h.
{
             return std::make_unique<tent_placement_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > tent_placement_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 5482 of file activity_actor.cpp.
 {
     item it;
     tent_placement_activity_actor actor( 0, {}, 0, it, {}, {}, {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "moves_total", actor.moves_total );
     data.read( "wall", actor.wall );
     data.read( "floor", actor.floor );
     data.read( "floor_center", actor.floor_center );
     data.read( "door_closed", actor.door_closed );
     data.read( "radius", actor.radius );
     data.read( "it", actor.it );
     data.read( "target", actor.target );
     return actor.clone();
 }
References JsonValue::get_object(), it, and JsonObject::read().
do_turn()
void tent_placement_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1369 of file activity_actor_definitions.h.
 {}
finish()
void tent_placement_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 5438 of file activity_actor.cpp.
 {
     map &here = get_map();
     const tripoint center = p.pos() + tripoint( ( radius + 1 ) * target.x, ( radius + 1 ) * target.y,
                             0 );
     // Make a square of floor surrounded by wall.
     for( const tripoint &dest : here.points_in_radius( center, radius ) ) {
         here.furn_set( dest, wall );
     }
     for( const tripoint &dest : here.points_in_radius( center, radius - 1 ) ) {
         here.furn_set( dest, floor );
     }
     // Place the center floor and the door.
     if( floor_center ) {
         here.furn_set( center, *floor_center );
     }
     here.furn_set( p.pos() + target, door_closed );
     add_msg( m_info, _( "You set up the %s on the ground." ), it.tname() );
     add_msg( m_info, _( "Examine the center square to pack it up again." ) );
     act.set_to_null();
 }
References _, act, add_msg(), center, door_closed, floor, floor_center, map::furn_set(), get_map(), it, m_info, map::points_in_radius(), Creature::pos(), radius, target, item::tname(), tripoint, wall, tripoint::x, and tripoint::y.
get_type()
activity_id tent_placement_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1364 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_TENT_PLACE" );
         }
References activity_id.
serialize()
void tent_placement_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 5468 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves_total", moves_total );
     jsout.member( "wall", wall );
     jsout.member( "floor", floor );
     jsout.member( "floor_center", floor_center );
     jsout.member( "door_closed", door_closed );
     jsout.member( "radius", radius );
     jsout.member( "it", it );
     jsout.member( "target", target );
     jsout.end_object();
 }
References door_closed, JsonOut::end_object(), floor, floor_center, it, JsonOut::member(), moves_total, radius, JsonOut::start_object(), target, and wall.
start()
void tent_placement_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 5432 of file activity_actor.cpp.
 {
     act.moves_total = moves_total;
     act.moves_left = moves_total;
 }
References act, and moves_total.
Member Data Documentation
door_closed
string_id<furn_t> tent_placement_activity_actor::door_closed private
Definition at line 1355 of file activity_actor_definitions.h.
Referenced by finish(), and serialize().
floor
string_id<furn_t> tent_placement_activity_actor::floor private
Definition at line 1353 of file activity_actor_definitions.h.
Referenced by finish(), and serialize().
floor_center
std::optional<string_id<furn_t> > tent_placement_activity_actor::floor_center private
Definition at line 1354 of file activity_actor_definitions.h.
Referenced by finish(), and serialize().
it
item tent_placement_activity_actor::it private
Definition at line 1351 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), finish(), and serialize().
moves_total
int tent_placement_activity_actor::moves_total private
Definition at line 1348 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
radius
int tent_placement_activity_actor::radius = 1 private
Definition at line 1350 of file activity_actor_definitions.h.
Referenced by finish(), and serialize().
target
tripoint tent_placement_activity_actor::target private
Definition at line 1349 of file activity_actor_definitions.h.
Referenced by canceled(), finish(), and serialize().
wall
string_id<furn_t> tent_placement_activity_actor::wall private
Definition at line 1352 of file activity_actor_definitions.h.
Referenced by finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp