Cataclysm DDA: hotkey_queue Class Reference
hotkey_queue Class Reference
#include <input_context.h>
Public Member Functions
input_event first (const input_context &ctxt) const
input_event next (const input_event &prev) const
Static Public Member Functions
static const hotkey_queue & alphabets ()
In keychar mode: a-z, A-Z In keycode mode: a-z, shift a-z.
static const hotkey_queue & alpha_digits ()
In keychar mode: 1-0, a-z, A-Z In keycode mode: 1-0, a-z, shift 1-0, shift a-z.
Private Attributes
std::vector< int > codes_keychar
std::vector< int > codes_keycode
std::vector< std::set< keymod_t > > modifiers_keycode
Detailed Description
Definition at line 483 of file input_context.h.
Member Function Documentation
alpha_digits()
const hotkey_queue & hotkey_queue::alpha_digits () static
In keychar mode: 1-0, a-z, A-Z In keycode mode: 1-0, a-z, shift 1-0, shift a-z.
Definition at line 1434 of file input_context.cpp.
 {
     // NOTE: if you want to add any parameters to this function, remove the static
     // modifier of `queue` and return by value instead of by reference.
     // NOTE: Removal of conflicting keys is handled by `input_context::next_unassigned_key`.
     static std::unique_ptr<hotkey_queue> queue;
     if( !queue ) {
         queue = std::make_unique<hotkey_queue>();
         for( int ch = '1'; ch <= '9'; ++ch ) {
             queue->codes_keycode.emplace_back( ch );
             queue->codes_keychar.emplace_back( ch );
         }
         queue->codes_keycode.emplace_back( '0' );
         queue->codes_keychar.emplace_back( '0' );
         for( int ch = 'a'; ch <= 'z'; ++ch ) {
             queue->codes_keycode.emplace_back( ch );
             queue->codes_keychar.emplace_back( ch );
         }
         for( int ch = 'A'; ch <= 'Z'; ++ch ) {
             queue->codes_keychar.emplace_back( ch );
         }
         queue->modifiers_keycode.emplace_back();
         queue->modifiers_keycode.emplace_back( std::set<keymod_t>( { keymod_t::shift } ) );
     }
     return *queue;
 }
References shift.
Referenced by uilist::calc_data().
alphabets()
const hotkey_queue & hotkey_queue::alphabets () static
In keychar mode: a-z, A-Z In keycode mode: a-z, shift a-z.
Definition at line 1413 of file input_context.cpp.
 {
     // NOTE: if you want to add any parameters to this function, remove the static
     // modifier of `queue` and return by value instead of by reference.
     // NOTE: Removal of conflicting keys is handled by `input_context::next_unassigned_key`.
     static std::unique_ptr<hotkey_queue> queue;
     if( !queue ) {
         queue = std::make_unique<hotkey_queue>();
         for( int ch = 'a'; ch <= 'z'; ++ch ) {
             queue->codes_keycode.emplace_back( ch );
             queue->codes_keychar.emplace_back( ch );
         }
         for( int ch = 'A'; ch <= 'Z'; ++ch ) {
             queue->codes_keychar.emplace_back( ch );
         }
         queue->modifiers_keycode.emplace_back();
         queue->modifiers_keycode.emplace_back( std::set<keymod_t>( { keymod_t::shift } ) );
     }
     return *queue;
 }
References shift.
Referenced by veh_interact::calc_overview(), and dialogue::opt().
first()
input_event hotkey_queue::first (const input_context & ctxt) const
Definition at line 1353 of file input_context.cpp.
 {
     if( ctxt.is_event_type_enabled( input_event_t::keyboard_code ) ) {
         if( !codes_keycode.empty() && !modifiers_keycode.empty() ) {
             return input_event( modifiers_keycode[0], codes_keycode[0], input_event_t::keyboard_code );
         } else {
             return input_event();
         }
     } else {
         if( !codes_keychar.empty() ) {
             return input_event( codes_keychar[0], input_event_t::keyboard_char );
         } else {
             return input_event();
         }
     }
 }
References codes_keychar, codes_keycode, input_context::is_event_type_enabled(), keyboard_char, keyboard_code, and modifiers_keycode.
Referenced by input_context::first_unassigned_hotkey().
next()
input_event hotkey_queue::next (const input_event & prev) const
Definition at line 1370 of file input_context.cpp.
 {
     switch( prev.type ) {
         default:
             return input_event();
         case input_event_t::keyboard_code: {
             if( prev.sequence.size() != 1 ) {
                 return input_event();
             }
             const auto code_it = std::find( codes_keycode.begin(), codes_keycode.end(),
                                             prev.get_first_input() );
             const auto mod_it = std::find( modifiers_keycode.begin(), modifiers_keycode.end(), prev.modifiers );
             if( code_it == codes_keycode.end() || mod_it == modifiers_keycode.end() ) {
                 return input_event();
             }
             if( std::next( code_it ) != codes_keycode.end() ) {
                 return input_event( prev.modifiers, *std::next( code_it ), prev.type );
             } else if( std::next( mod_it ) != modifiers_keycode.end() ) {
                 return input_event( *std::next( mod_it ), codes_keycode[0], prev.type );
             } else {
                 return input_event();
             }
             break;
         }
         case input_event_t::keyboard_char: {
             if( prev.sequence.size() != 1 ) {
                 return input_event();
             }
             const auto code_it = std::find( codes_keychar.begin(), codes_keychar.end(),
                                             prev.get_first_input() );
             if( code_it == codes_keychar.end() ) {
                 return input_event();
             }
             if( std::next( code_it ) != codes_keychar.end() ) {
                 return input_event( *std::next( code_it ), prev.type );
             } else {
                 return input_event();
             }
             break;
         }
     }
 }
References codes_keychar, codes_keycode, input_event::get_first_input(), keyboard_char, keyboard_code, input_event::modifiers, modifiers_keycode, input_event::sequence, and input_event::type.
Referenced by input_context::first_unassigned_hotkey(), and input_context::next_unassigned_hotkey().
Member Data Documentation
codes_keychar
std::vector<int> hotkey_queue::codes_keychar private
Definition at line 509 of file input_context.h.
Referenced by first(), and next().
codes_keycode
std::vector<int> hotkey_queue::codes_keycode private
Definition at line 510 of file input_context.h.
Referenced by first(), and next().
modifiers_keycode
std::vector<std::set<keymod_t> > hotkey_queue::modifiers_keycode private
Definition at line 511 of file input_context.h.
Referenced by first(), and next().
The documentation for this class was generated from the following files:
src/input_context.h
src/input_context.cpp