Cataclysm DDA: vehicle_stack Class Reference
vehicle_stack Class Reference
#include <vehicle.h>
Public Member Functions
vehicle_stack (vehicle &veh, vehicle_part &vp)
item_stack::iterator erase (item_stack::const_iterator it) override
void insert (const item &newitem) override
int count_limit () const override
Maximum number of items allowed here.
units::volume max_volume () const override
Maximum volume allowed here.
Public Member Functions inherited from item_stack
item_stack (cata::colony< item > *items)
virtual ~item_stack ()=default
size_t size () const
bool empty () const
virtual void clear ()
item & only_item ()
iterator get_iterator_from_pointer (item *it)
iterator get_iterator_from_index (size_t idx)
size_t get_index_from_iterator (const const_iterator &it)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
units::volume stored_volume () const
Total volume of the items here.
units::volume free_volume () const
int amount_can_fit (const item &it) const
Returns how many of the specified item (or how many charges if it's counted by charges) could be added without violating either the volume or itemcount limits.
item * stacks_with (const item &it)
Return the item (or nullptr) that stacks with the argument.
const item * stacks_with (const item &it) const
std::list< item > use_charges (const itype_id &type, int &quantity, const tripoint &pos, const std::function< bool(const item &)> &filter, bool in_tools=false)
Consumes specified charges (or fewer) from the stack.
Private Attributes
vehicle & veh
vehicle_part & vp
Additional Inherited Members
Public Types inherited from item_stack
using iterator = cata::colony< item >::iterator
using const_iterator = cata::colony< item >::const_iterator
using reverse_iterator = cata::colony< item >::reverse_iterator
using const_reverse_iterator = cata::colony< item >::const_reverse_iterator
Protected Attributes inherited from item_stack
cata::colony< item > * items
Detailed Description
Definition at line 173 of file vehicle.h.
Constructor & Destructor Documentation
vehicle_stack()
vehicle_stack::vehicle_stack (vehicle & veh, vehicle_part & vp)
Definition at line 184 of file vehicle.cpp.
                                                              :
     item_stack( &vp.items ), veh( veh ), vp( vp ) {}
Member Function Documentation
count_limit()
int vehicle_stack::count_limit () const override virtual
Maximum number of items allowed here.
Implements item_stack.
Definition at line 197 of file vehicle.cpp.
 {
     return MAX_ITEM_IN_VEHICLE_STORAGE;
 }
References MAX_ITEM_IN_VEHICLE_STORAGE.
erase()
vehicle_stack::iterator vehicle_stack::erase (item_stack::const_iterator it) override virtual
Implements item_stack.
Definition at line 187 of file vehicle.cpp.
 {
     return veh.remove_item( vp, it );
 }
References vehicle::remove_item(), veh, and vp.
Referenced by map::mop_spills(), and vehicle::operate_planter().
insert()
void vehicle_stack::insert (const item & newitem) override virtual
Implements item_stack.
Definition at line 192 of file vehicle.cpp.
 {
     veh.add_item( vp, newitem );
 }
References vehicle::add_item(), veh, and vp.
Referenced by veh_interact::complete_vehicle().
max_volume()
units::volume vehicle_stack::max_volume () const override virtual
Maximum volume allowed here.
Implements item_stack.
Definition at line 202 of file vehicle.cpp.
 {
     const vpart_info &vpi = vp.info();
     if( !vpi.has_flag( VPFLAG_CARGO ) || vp.is_broken() ) {
         return 0_ml;
     }
     // Set max volume for vehicle cargo to prevent integer overflow
     return std::min( vpi.size, 10000_liter );
 }
References vpart_info::has_flag(), vehicle_part::info(), vehicle_part::is_broken(), min(), vpart_info::size, vp, and VPFLAG_CARGO.
Referenced by veh_interact::display_stats(), advanced_inventory::print_items(), and vehicle::print_part_list().
Member Data Documentation
veh
vehicle& vehicle_stack::veh private
Definition at line 176 of file vehicle.h.
Referenced by erase(), and insert().
vp
vehicle_part& vehicle_stack::vp private
Definition at line 177 of file vehicle.h.
Referenced by erase(), insert(), and max_volume().
The documentation for this class was generated from the following files:
src/vehicle.h
src/vehicle.cpp