Cataclysm DDA: tab_list Class Reference
tab_list Class Reference
#include <output.h>
Public Member Functions
tab_list (std::vector< std::string > &_list)
void last ()
void next ()
void prev ()
int cur_index () const
std::string cur () const
void set_index (const size_t new_index)
Private Attributes
size_t _index = 0
std::vector< std::string > * _list
Detailed Description
Definition at line 1220 of file output.h.
Constructor & Destructor Documentation
tab_list()
tab_list::tab_list (std::vector< std::string > & _list) inline explicit
Definition at line 1226 of file output.h.
                                                          : _list( &_list ) {
         }
Member Function Documentation
cur()
std::string tab_list::cur () const inline
Definition at line 1247 of file output.h.
{
             if( _list->empty() ) {
                 return std::string();
             }
             return ( *_list )[_index];
         }
References _index, and _list.
cur_index()
int tab_list::cur_index () const inline
Definition at line 1243 of file output.h.
{
             return static_cast<int>( _index );
         }
References _index.
Referenced by avatar::create(), tab_manager::draw(), and select_crafter_and_crafting_recipe().
last()
void tab_list::last () inline
Definition at line 1229 of file output.h.
                     {
             if( !_list->empty() ) {
                 _index = _list->size() - 1;
             }
         }
References _index, and _list.
Referenced by avatar::create().
next()
void tab_list::next () inline
Definition at line 1235 of file output.h.
                     {
             _index = ( _index == _list->size() - 1 ? 0 : _index + 1 );
         }
References _index, and _list.
Referenced by tab_manager::handle_input().
prev()
void tab_list::prev () inline
Definition at line 1239 of file output.h.
                     {
             _index = ( _index == 0 ? _list->size() - 1 : _index - 1 );
         }
References _index, and _list.
Referenced by tab_manager::handle_input().
set_index()
void tab_list::set_index (const size_t new_index) inline
Definition at line 1254 of file output.h.
{
             if( new_index < _list->size() ) {
                 _index = new_index;
             }
         }
References _index, and om_direction::size.
Referenced by tab_manager::handle_input().
Member Data Documentation
_index
size_t tab_list::_index = 0 private
Definition at line 1223 of file output.h.
Referenced by cur(), cur_index(), last(), next(), prev(), and set_index().
_list
std::vector<std::string>* tab_list::_list private
Definition at line 1224 of file output.h.
Referenced by cur(), last(), next(), and prev().
The documentation for this class was generated from the following file:
src/output.h