Cataclysm DDA: drop_or_stash_item_info Class Reference
drop_or_stash_item_info Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
drop_or_stash_item_info ()
drop_or_stash_item_info (const item_location &_loc, const int _count)
void serialize (JsonOut &jsout) const
void deserialize (const JsonObject &jsobj)
const item_location & loc () const
int count () const
Private Attributes
item_location _loc
int _count = 0
Detailed Description
Definition at line 1018 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
drop_or_stash_item_info() [1/2]
drop_or_stash_item_info::drop_or_stash_item_info () inline
Definition at line 1021 of file activity_actor_definitions.h.
             : _loc( item_location::nowhere ) {}
drop_or_stash_item_info() [2/2]
drop_or_stash_item_info::drop_or_stash_item_info (const item_location & _loc, const int _count) inline
Definition at line 1023 of file activity_actor_definitions.h.
             : _loc( _loc ), _count( _count ) {}
Member Function Documentation
count()
int drop_or_stash_item_info::count () const inline
Definition at line 1033 of file activity_actor_definitions.h.
{
             return _count;
         }
References _count.
deserialize()
void drop_or_stash_item_info::deserialize (const JsonObject & jsobj)
Definition at line 4169 of file activity_actor.cpp.
 {
     jsobj.read( "loc", _loc );
     jsobj.read( "count", _count );
 }
References _count, _loc, and JsonObject::read().
loc()
const item_location& drop_or_stash_item_info::loc () const inline
Definition at line 1029 of file activity_actor_definitions.h.
{
             return _loc;
         }
References _loc.
serialize()
void drop_or_stash_item_info::serialize (JsonOut & jsout) const
Definition at line 4161 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "loc", _loc );
     jsout.member( "count", _count );
     jsout.end_object();
 }
References _count, _loc, JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
_count
int drop_or_stash_item_info::_count = 0 private
Definition at line 1038 of file activity_actor_definitions.h.
Referenced by count(), deserialize(), and serialize().
_loc
item_location drop_or_stash_item_info::_loc private
Definition at line 1037 of file activity_actor_definitions.h.
Referenced by deserialize(), loc(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp