Cataclysm DDA: border_helper Class Reference
border_helper Class Reference
#include <output.h>
Classes
struct border_connection
class border_info
Public Member Functions
border_info & add_border ()
void draw_border (const catacurses::window &win, nc_color border_color=BORDER_COLOR)
Private Attributes
std::optional< std::map< point, border_connection > > border_connection_map
std::forward_list< border_info > border_info_list
Friends
class border_info
Detailed Description
Definition at line 379 of file output.h.
Member Function Documentation
add_border()
border_helper::border_info & border_helper::add_border ()
Definition at line 727 of file output.cpp.
 {
     border_info_list.emplace_front( border_info( *this ) );
     return border_info_list.front();
 }
References border_info, and border_info_list.
Referenced by debug_menu::change_spells(), Character::disp_info(), and bodygraph_display::init_ui_windows().
draw_border()
void border_helper::draw_border (const catacurses::window & win, nc_color border_color = BORDER_COLOR)
Definition at line 733 of file output.cpp.
 {
     if( !border_connection_map.has_value() ) {
         border_connection_map.emplace();
         for( const border_info &info : border_info_list ) {
             const point beg = info.pos;
             const point end = info.pos + info.size;
             for( int x = beg.x; x < end.x; ++x ) {
                 const point ptop( x, beg.y );
                 const point pbottom( x, end.y - 1 );
                 if( x > beg.x ) {
                     border_connection_map.value()[ptop].left =
                         border_connection_map.value()[pbottom].left = true;
                 }
                 if( x < end.x - 1 ) {
                     border_connection_map.value()[ptop].right =
                         border_connection_map.value()[pbottom].right = true;
                 }
             }
             for( int y = beg.y; y < end.y; ++y ) {
                 const point pleft( beg.x, y );
                 const point pright( end.x - 1, y );
                 if( y > beg.y ) {
                     border_connection_map.value()[pleft].top =
                         border_connection_map.value()[pright].top = true;
                 }
                 if( y < end.y - 1 ) {
                     border_connection_map.value()[pleft].bottom =
                         border_connection_map.value()[pright].bottom = true;
                 }
             }
         }
     }
     const point win_beg( getbegx( win ), getbegy( win ) );
     const point win_end = win_beg + point( getmaxx( win ), getmaxy( win ) );
     for( const std::pair<const point, border_connection> &conn : border_connection_map.value() ) {
         if( conn.first.x >= win_beg.x && conn.first.x < win_end.x &&
             conn.first.y >= win_beg.y && conn.first.y < win_end.y ) {
             mvwputch( win, conn.first - win_beg, border_color, conn.second.as_curses_line() );
         }
     }
 }
References border_connection_map, border_info_list, keycode::end, catacurses::getbegx(), catacurses::getbegy(), catacurses::getmaxx(), catacurses::getmaxy(), mvwputch(), point, point::x, and point::y.
Referenced by debug_menu::change_spells(), Character::disp_info(), and bodygraph_display::draw_borders().
Friends And Related Function Documentation
border_info
friend class border_info friend
Definition at line 405 of file output.h.
Referenced by add_border().
Member Data Documentation
border_connection_map
std::optional<std::map<point, border_connection> > border_helper::border_connection_map private
Definition at line 415 of file output.h.
Referenced by draw_border().
border_info_list
std::forward_list<border_info> border_helper::border_info_list private
Definition at line 417 of file output.h.
Referenced by add_border(), and draw_border().
The documentation for this class was generated from the following files:
src/output.h
src/output.cpp