Cataclysm DDA: deploy_appliance_actor Class Reference
deploy_appliance_actor Class Reference
Deployable appliances from items.
#include <iuse_actor.h>
Public Member Functions
deploy_appliance_actor ()
~deploy_appliance_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
itype_id appliance_base
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Deployable appliances from items.
Definition at line 410 of file iuse_actor.h.
Constructor & Destructor Documentation
deploy_appliance_actor()
deploy_appliance_actor::deploy_appliance_actor () inline
Definition at line 415 of file iuse_actor.h.
 : iuse_actor( "deploy_appliance" ) {}
~deploy_appliance_actor()
deploy_appliance_actor::~deploy_appliance_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > deploy_appliance_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 1157 of file iuse_actor.cpp.
 {
     return std::make_unique<deploy_appliance_actor>( *this );
 }
info()
void deploy_appliance_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 1162 of file iuse_actor.cpp.
 {
     dump.emplace_back( "DESCRIPTION",
                        string_format( _( "Can be <info>activated</info> to deploy as an appliance (<stat>%s</stat>)." ),
                                       vpart_appliance_from_item( appliance_base )->name() ) );
 }
References _, appliance_base, om_direction::name(), string_format(), and vpart_appliance_from_item().
load()
void deploy_appliance_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 1169 of file iuse_actor.cpp.
 {
     mandatory( obj, false, "base", appliance_base );
 }
References appliance_base, and mandatory.
use()
std::optional< int > deploy_appliance_actor::use (Character * p, item & it, const tripoint & pos) const override virtual
Implements iuse_actor.
Definition at line 1174 of file iuse_actor.cpp.
 {
     ret_val<tripoint> suitable = check_deploy_square( p, it, pos );
     if( !suitable.success() ) {
         p->add_msg_if_player( m_info, suitable.str() );
         return std::nullopt;
     }
     place_appliance( suitable.value(), vpart_appliance_from_item( appliance_base ) );
     it.spill_contents( suitable.value() );
     p->mod_moves( -to_moves<int>( 2_seconds ) );
     return 1;
 }
References Character::add_msg_if_player(), appliance_base, check_deploy_square(), m_info, Creature::mod_moves(), place_appliance(), math_opers::pos(), item::spill_contents(), ret_val_common::str(), ret_val_common::success(), ret_val< T >::value(), and vpart_appliance_from_item().
Member Data Documentation
appliance_base
itype_id deploy_appliance_actor::appliance_base
Definition at line 413 of file iuse_actor.h.
Referenced by info(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp