Cataclysm DDA: VehicleGroup Class Reference
VehicleGroup Class Reference
This class is used to group vehicles together into groups in much the same way as item groups work.
#include <vehicle_group.h>
Public Member Functions
VehicleGroup ()=default
void add_vehicle (const vproto_id &type, const int &probability)
const vproto_id & pick () const
std::vector< vproto_id > all_possible_results () const
Static Public Member Functions
static void load (const JsonObject &jo)
static void reset ()
Private Attributes
weighted_int_list< vproto_id > vehicles
Detailed Description
This class is used to group vehicles together into groups in much the same way as item groups work.
Definition at line 31 of file vehicle_group.h.
Constructor & Destructor Documentation
VehicleGroup()
VehicleGroup::VehicleGroup () default
Member Function Documentation
add_vehicle()
void VehicleGroup::add_vehicle (const vproto_id & type, const int & probability) inline
Definition at line 36 of file vehicle_group.h.
{
             vehicles.add( type, probability );
         }
References type.
all_possible_results()
std::vector< vproto_id > VehicleGroup::all_possible_results () const
Definition at line 71 of file vehicle_group.cpp.
 {
     std::vector<vproto_id> result;
     for( const weighted_object<int, vproto_id> &wo : vehicles ) {
         result.push_back( wo.obj );
     }
     return result;
 }
load()
void VehicleGroup::load (const JsonObject & jo) static
Definition at line 80 of file vehicle_group.cpp.
 {
     VehicleGroup &group = vgroups[vgroup_id( jo.get_string( "id" ) )];
     for( JsonArray pair : jo.get_array( "vehicles" ) ) {
         group.add_vehicle( vproto_id( pair.get_string( 0 ) ), pair.get_int( 1 ) );
     }
 }
References JsonObject::get_array(), JsonObject::get_string(), vgroup_id, and vgroups.
Referenced by DynamicDataLoader::initialize().
pick()
const vproto_id& VehicleGroup::pick () const inline
Definition at line 40 of file vehicle_group.h.
{
             return *vehicles.pick();
         }
Referenced by jmapgen_vehicle::apply(), VehicleSpawnFunction::builtin_parkinglot(), and MapExtras::mx_helicopter().
reset()
void VehicleGroup::reset () static
Definition at line 89 of file vehicle_group.cpp.
 {
     vgroups.clear();
 }
References vgroups.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
vehicles
weighted_int_list<vproto_id> VehicleGroup::vehicles private
Definition at line 50 of file vehicle_group.h.
The documentation for this class was generated from the following files:
src/vehicle_group.h
src/vehicle_group.cpp