Cataclysm DDA: MonsterGroupManager Class Reference
MonsterGroupManager Class Reference
#include <mongroup.h>
Static Public Member Functions
static void LoadMonsterGroup (const JsonObject &jo)
static void LoadMonsterBlacklist (const JsonObject &jo)
static void LoadMonsterWhitelist (const JsonObject &jo)
static void FinalizeMonsterGroups ()
static std::vector< MonsterGroupResult > GetResultFromGroup (const mongroup_id &group, int *quantity=nullptr, bool *mon_found=nullptr, bool is_recursive=false, bool *returned_default=nullptr, bool use_pack_size=false)
static bool IsMonsterInGroup (const mongroup_id &group, const mtype_id &monster)
static bool isValidMonsterGroup (const mongroup_id &group)
static const mongroup_id & Monster2Group (const mtype_id &monster)
static std::vector< mtype_id > GetMonstersFromGroup (const mongroup_id &group, bool from_subgroups)
static const MonsterGroup & GetMonsterGroup (const mongroup_id &group)
static const MonsterGroup & GetUpgradedMonsterGroup (const mongroup_id &group)
static const mtype_id & GetRandomMonsterFromGroup (const mongroup_id &group)
Gets a random monster, weighted by frequency.
static void check_group_definitions ()
static void ClearMonsterGroups ()
static bool monster_is_blacklisted (const mtype_id &m)
static bool is_animal (const mongroup_id &group)
Private Types
using t_string_set = std::set< std::string >
Static Private Attributes
static std::map< mongroup_id, MonsterGroup > monsterGroupMap
static t_string_set monster_blacklist
static t_string_set monster_whitelist
static t_string_set monster_categories_blacklist
static t_string_set monster_categories_whitelist
static t_string_set monster_species_blacklist
static t_string_set monster_species_whitelist
Detailed Description
Definition at line 196 of file mongroup.h.
Member Typedef Documentation
t_string_set
using MonsterGroupManager::t_string_set = std::set<std::string> private
Definition at line 228 of file mongroup.h.
Member Function Documentation
check_group_definitions()
void MonsterGroupManager::check_group_definitions () static
Definition at line 600 of file mongroup.cpp.
 {
     for( const auto &e : monsterGroupMap ) {
         const MonsterGroup &mg = e.second;
         for( const MonsterGroupEntry &mge : mg.monsters ) {
             if( mge.is_group() ) {
                 if( !mge.group.is_valid() ) {
                     debugmsg( "monster group %s contains unknown subgroup %s", mg.name.c_str(), mge.group.c_str() );
                 } else {
                     check_group_def( mge.group );
                 }
             } else if( !mge.name.is_valid() ) {
                 // mon_null should not be valid here
                 debugmsg( "monster group %s contains unknown monster %s", mg.name.c_str(), mge.name.c_str() );
             }
         }
     }
 }
References string_id< T >::c_str(), check_group_def(), debugmsg, MonsterGroupEntry::group, MonsterGroupEntry::is_group(), string_id< T >::is_valid(), monsterGroupMap, MonsterGroup::monsters, MonsterGroupEntry::name, and MonsterGroup::name.
Referenced by DynamicDataLoader::check_consistency().
ClearMonsterGroups()
void MonsterGroupManager::ClearMonsterGroups () static
Definition at line 573 of file mongroup.cpp.
 {
     monsterGroupMap.clear();
     monster_blacklist.clear();
     monster_whitelist.clear();
     monster_whitelist_is_exclusive = false;
     monster_categories_blacklist.clear();
     monster_categories_whitelist.clear();
     monster_species_blacklist.clear();
     monster_species_whitelist.clear();
 }
References monster_blacklist, monster_categories_blacklist, monster_categories_whitelist, monster_species_blacklist, monster_species_whitelist, monster_whitelist, monster_whitelist_is_exclusive, and monsterGroupMap.
Referenced by DynamicDataLoader::unload_data().
FinalizeMonsterGroups()
void MonsterGroupManager::FinalizeMonsterGroups () static
Definition at line 424 of file mongroup.cpp.
 {
     for( const std::string &mtid : monster_whitelist ) {
         if( !mtype_id( mtid ).is_valid() ) {
             debugmsg( "monster on whitelist %s does not exist", mtid.c_str() );
         }
     }
     for( const std::string &mtid : monster_blacklist ) {
         if( !mtype_id( mtid ).is_valid() ) {
             debugmsg( "monster on blacklist %s does not exist", mtid.c_str() );
         }
     }
     // Further, remove all blacklisted monsters
     for( auto &elem : monsterGroupMap ) {
         MonsterGroup &mg = elem.second;
         for( FreqDef::iterator c = mg.monsters.begin(); c != mg.monsters.end(); ) {
             if( !c->is_group() && MonsterGroupManager::monster_is_blacklisted( c->name ) ) {
                 c = mg.monsters.erase( c );
             } else {
                 ++c;
             }
         }
         if( MonsterGroupManager::monster_is_blacklisted( mg.defaultMonster ) ) {
             mg.defaultMonster = mtype_id::NULL_ID();
         }
     }
 }
References c, debugmsg, MonsterGroup::defaultMonster, monster_blacklist, monster_is_blacklisted(), monster_whitelist, monsterGroupMap, MonsterGroup::monsters, mtype_id, and string_id< mtype >::NULL_ID().
Referenced by DynamicDataLoader::finalize_loaded_data().
GetMonsterGroup()
const MonsterGroup & MonsterGroupManager::GetMonsterGroup (const mongroup_id & group) static
Definition at line 355 of file mongroup.cpp.
 {
     const auto it = monsterGroupMap.find( group );
     if( it == monsterGroupMap.end() ) {
         debugmsg( "Unable to get the group '%s'", group.c_str() );
         // Initialize the group with a null-monster, it's ignored while spawning,
         // but it prevents further messages about invalid monster type id
         auto &g = monsterGroupMap[group];
         g.name = group;
         g.defaultMonster = mtype_id::NULL_ID();
         return g;
     } else {
         return it->second;
     }
 }
References debugmsg, g, monsterGroupMap, and string_id< mtype >::NULL_ID().
GetMonstersFromGroup()
std::vector< mtype_id > MonsterGroupManager::GetMonstersFromGroup (const mongroup_id & group, bool from_subgroups) static
Definition at line 324 of file mongroup.cpp.
 {
     const MonsterGroup &g = group.obj();
     std::vector<mtype_id> monsters;
     std::string opt = get_option<std::string>( "EVENT_SPAWNS" );
     const bool can_spawn_events = opt == "monsters" || opt == "both";
     for( const MonsterGroupEntry &elem : g.monsters ) {
         if( elem.event != holiday::none && ( !can_spawn_events ||
                                              elem.event != get_holiday_from_time() ) ) {
             continue;
         }
         if( elem.is_group() ) {
             if( from_subgroups ) {
                 std::vector<mtype_id> submons = GetMonstersFromGroup( elem.group, from_subgroups );
                 monsters.reserve( monsters.size() + submons.size() );
                 monsters.insert( monsters.end(), submons.begin(), submons.end() );
             }
         } else {
             monsters.push_back( elem.name );
         }
     }
     return monsters;
 }
References MonsterGroupEntry::event, g, get_holiday_from_time(), MonsterGroupEntry::group, MonsterGroupEntry::is_group(), MonsterGroupEntry::name, and none.
Referenced by jmapgen_corpse::apply(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), iuse::fish_trap_tick(), and rod_fish().
GetRandomMonsterFromGroup()
const mtype_id & MonsterGroupManager::GetRandomMonsterFromGroup (const mongroup_id & group) static
Gets a random monster, weighted by frequency.
Ignores cost multiplier.
Definition at line 619 of file mongroup.cpp.
 {
     const MonsterGroup &group = group_name.obj();
     int spawn_chance = rng( 1, group.event_adjusted_freq_total() );
     std::string opt = get_option<std::string>( "EVENT_SPAWNS" );
     const bool can_spawn_events = opt == "monsters" || opt == "both";
     for( const MonsterGroupEntry &monster_type : group.monsters ) {
         if( monster_type.event != holiday::none && ( !can_spawn_events ||
                 monster_type.event != get_holiday_from_time() ) ) {
             continue;
         }
         if( monster_type.frequency >= spawn_chance ) {
             if( monster_type.is_group() ) {
                 return GetRandomMonsterFromGroup( monster_type.group );
             }
             return monster_type.name;
         } else {
             spawn_chance -= monster_type.frequency;
         }
     }
     return group.defaultMonster;
 }
References MonsterGroupEntry::event, MonsterGroupEntry::frequency, get_holiday_from_time(), MonsterGroupEntry::group, MonsterGroupEntry::is_group(), MonsterGroupEntry::name, none, string_id< T >::obj(), and rng().
Referenced by add_summoned_mon(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), magical_polymorph(), game::spawn_hallucination(), and monster::try_upgrade().
GetResultFromGroup()
std::vector< MonsterGroupResult > MonsterGroupManager::GetResultFromGroup (const mongroup_id & group, int * quantity = nullptr, bool * mon_found = nullptr, bool is_recursive = false, bool * returned_default = nullptr, bool use_pack_size = false) static
Definition at line 204 of file mongroup.cpp.
 {
     const MonsterGroup &group = GetUpgradedMonsterGroup( group_name );
     int spawn_chance = rng( 1, group.event_adjusted_freq_total() );
     //Our spawn details specify, by default, a single instance of the default monster
     std::vector<MonsterGroupResult> spawn_details;
     bool monster_found = false;
     // Loop invariant values
     const time_point sunset = ::sunset( calendar::turn );
     const time_point sunrise = ::sunrise( calendar::turn );
     const season_type season = season_of_year( calendar::turn );
     std::string opt = get_option<std::string>( "EVENT_SPAWNS" );
     const bool can_spawn_events = opt == "monsters" || opt == "both";
     // Step through spawn definitions from the monster group until one is found or
     for( const MonsterGroupEntry &entry : group.monsters ) {
         if( !is_spawn_valid( entry, sunset, sunrise, season, can_spawn_events ) ) {
             continue;
         }
         // Only keep if the monsters frequency is at least the spawn_chance
         if( entry.frequency < spawn_chance ) {
             spawn_chance -= entry.frequency;
             continue;
         }
         const int pack_size =
             entry.pack_maximum > 1 ? rng( entry.pack_minimum, entry.pack_maximum ) : 1;
         if( entry.is_group() ) {
             // Check for monsters within subgroup
             for( int i = 0; i < pack_size; i++ ) {
                 std::vector<MonsterGroupResult> tmp_grp =
                     GetResultFromGroup( entry.group, quantity, mon_found, true );
                 spawn_details.insert( spawn_details.end(), tmp_grp.begin(), tmp_grp.end() );
             }
         } else if( use_pack_size ) {
             for( int i = 0; i < pack_size; i++ ) {
                 spawn_details.emplace_back( entry.name, pack_size, entry.data );
                 // And if a quantity pointer with remaining value was passed, will modify the external
                 // value as a side effect.  We will reduce it by the spawn rule's cost multiplier.
                 if( quantity ) {
                     *quantity -= std::max( 1, entry.cost_multiplier * pack_size );
                 }
             }
         } else {
             spawn_details.emplace_back( entry.name, pack_size, entry.data );
             // And if a quantity pointer with remaining value was passed, will modify the external
             // value as a side effect.  We will reduce it by the spawn rule's cost multiplier.
             if( quantity ) {
                 *quantity -= std::max( 1, entry.cost_multiplier * pack_size );
             }
         }
         monster_found = true;
         break;
     }
     // Force quantity to decrement regardless of whether we found a monster.
     if( quantity && !monster_found && !is_recursive ) {
         ( *quantity )--;
     }
     if( mon_found ) {
         ( *mon_found ) = monster_found;
     }
     if( !is_recursive && spawn_details.empty() ) {
         spawn_details.emplace_back( group.defaultMonster, 1, spawn_data() );
         if( returned_default ) {
             ( *returned_default ) = true;
         }
     }
     return spawn_details;
 }
References MonsterGroupEntry::cost_multiplier, MonsterGroupEntry::data, MonsterGroupEntry::frequency, GetUpgradedMonsterGroup(), MonsterGroupEntry::group, MonsterGroupEntry::is_group(), is_spawn_valid(), max(), MonsterGroupEntry::name, MonsterGroupEntry::pack_maximum, MonsterGroupEntry::pack_minimum, rng(), season, season_of_year(), sunrise(), sunset(), and calendar::turn.
Referenced by jmapgen_monster::apply(), eff_fun_teleglow(), field_processor_monster_spawn(), map::generate(), Character::hardcoded_effects(), basecamp::hunting_results(), map::place_spawns(), explosion_handler::resonance_cascade(), map::rotten_item_spawn(), map::spawn_monsters_submap_group(), and monster::try_upgrade().
GetUpgradedMonsterGroup()
const MonsterGroup & MonsterGroupManager::GetUpgradedMonsterGroup (const mongroup_id & group) static
Definition at line 115 of file mongroup.cpp.
 {
     const MonsterGroup *groupptr = &group.obj();
     if( get_option<float>( "MONSTER_UPGRADE_FACTOR" ) > 0 ) {
         const time_duration replace_time = groupptr->monster_group_time *
                                            get_option<float>( "MONSTER_UPGRADE_FACTOR" );
         while( groupptr->replace_monster_group &&
                calendar::turn - time_point( calendar::start_of_cataclysm ) > replace_time ) {
             groupptr = &groupptr->new_monster_group.obj();
         }
     }
     return *groupptr;
 }
References MonsterGroup::monster_group_time, MonsterGroup::new_monster_group, string_id< T >::obj(), MonsterGroup::replace_monster_group, calendar::start_of_cataclysm, and calendar::turn.
Referenced by GetResultFromGroup().
is_animal()
bool MonsterGroupManager::is_animal (const mongroup_id & group) static
Definition at line 567 of file mongroup.cpp.
 {
     const MonsterGroup *groupptr = &group_name.obj();
     return groupptr->is_animal;
 }
References MonsterGroup::is_animal, and string_id< T >::obj().
Referenced by map::generate(), and map::place_spawns().
IsMonsterInGroup()
bool MonsterGroupManager::IsMonsterInGroup (const mongroup_id & group, const mtype_id & monster) static
Definition at line 309 of file mongroup.cpp.
 {
     return group.obj().IsMonsterInGroup( monster );
 }
Referenced by monster::die(), and anonymous_namespace{math_parser_diag.cpp}::mon_check_group().
isValidMonsterGroup()
bool MonsterGroupManager::isValidMonsterGroup (const mongroup_id & group) static
Definition at line 350 of file mongroup.cpp.
 {
     return monsterGroupMap.count( group ) > 0;
 }
References monsterGroupMap.
Referenced by debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
LoadMonsterBlacklist()
void MonsterGroupManager::LoadMonsterBlacklist (const JsonObject & jo) static
Definition at line 371 of file mongroup.cpp.
 {
     add_array_to_set( monster_blacklist, jo, "monsters" );
     add_array_to_set( monster_categories_blacklist, jo, "categories" );
     add_array_to_set( monster_species_blacklist, jo, "species" );
 }
References add_array_to_set(), monster_blacklist, monster_categories_blacklist, and monster_species_blacklist.
Referenced by DynamicDataLoader::initialize().
LoadMonsterGroup()
void MonsterGroupManager::LoadMonsterGroup (const JsonObject & jo) static
Definition at line 452 of file mongroup.cpp.
 {
     float mon_upgrade_factor = get_option<float>( "MONSTER_UPGRADE_FACTOR" );
     MonsterGroup g;
     int freq_total = 0;
     std::pair<mtype_id, int> max_freq( { mon_null, 0 } );
     g.name = mongroup_id( jo.get_string( "name" ) );
     bool extending = false;  //If already a group with that name, add to it instead of overwriting it
     if( monsterGroupMap.count( g.name ) != 0 && !jo.get_bool( "override", false ) ) {
         g = monsterGroupMap[g.name];
         extending = true;
     }
     bool explicit_def_null = false;
     if( !extending || jo.has_string( "default" ) ) {
         g.defaultMonster = mtype_id( jo.get_string( "default", "mon_null" ) );
         if( jo.has_string( "default" ) && g.defaultMonster == mon_null ) {
             explicit_def_null = true;
         }
     } else if( extending && !jo.has_string( "default" ) && g.defaultMonster == mon_null ) {
         explicit_def_null = true;
     }
     g.is_animal = jo.get_bool( "is_animal", false );
     if( jo.has_array( "monsters" ) ) {
         for( JsonObject mon : jo.get_array( "monsters" ) ) {
             bool isgroup = false;
             std::string id_name;
             if( mon.has_string( "group" ) ) {
                 isgroup = true;
                 id_name = mon.get_string( "group" );
             } else {
                 id_name = mon.get_string( "monster" );
             }
             holiday event = mon.get_enum_value<holiday>( "event", holiday::none );
             int freq = mon.get_int( "weight", 1 );
             if( mon.has_int( "freq" ) ) {
                 freq = mon.get_int( "freq" );
             }
             if( freq > max_freq.second ) {
                 if( !isgroup && event == holiday::none ) {
                     max_freq = { mtype_id( id_name ), freq };
                 }
             }
             if( event == holiday::none ) {
                 freq_total += freq;
             }
             int cost = mon.get_int( "cost_multiplier", 1 );
             int pack_min = 1;
             int pack_max = 1;
             if( mon.has_member( "pack_size" ) ) {
                 JsonArray packarr = mon.get_array( "pack_size" );
                 pack_min = packarr.next_int();
                 pack_max = packarr.next_int();
             }
             static const time_duration tdfactor = 1_hours;
             time_duration starts = 0_turns;
             time_duration ends = 0_turns;
             if( mon.has_member( "starts" ) ) {
                 assign( mon, "starts", starts, false, tdfactor );
                 starts *= mon_upgrade_factor > 0 ? mon_upgrade_factor : 1;
             }
             if( mon.has_member( "ends" ) ) {
                 assign( mon, "ends", ends, false, tdfactor );
                 ends *= mon_upgrade_factor > 0 ? mon_upgrade_factor : 1;
             }
             spawn_data data;
             if( mon.has_object( "spawn_data" ) ) {
                 const JsonObject &sd = mon.get_object( "spawn_data" );
                 if( sd.has_array( "ammo" ) ) {
                     const JsonArray &ammos = sd.get_array( "ammo" );
                     for( const JsonObject adata : ammos ) {
                         data.ammo.emplace( itype_id( adata.get_string( "ammo_id" ) ), jmapgen_int( adata, "qty" ) );
                     }
                 }
             }
             MonsterGroupEntry new_mon_group = isgroup ?
                                               MonsterGroupEntry( mongroup_id( id_name ), freq, cost,
                                                       pack_min, pack_max, data, starts, ends, event ) :
                                               MonsterGroupEntry( mtype_id( id_name ), freq, cost, pack_min,
                                                       pack_max, data, starts, ends, event );
             if( mon.has_member( "conditions" ) ) {
                 for( const std::string line : mon.get_array( "conditions" ) ) {
                     new_mon_group.conditions.push_back( line );
                 }
             }
             g.event_freq[event] += freq;
             g.monsters.push_back( new_mon_group );
         }
         // If no default monster specified, use the highest frequency spawn as the default
         if( g.defaultMonster == mon_null && !explicit_def_null ) {
             g.defaultMonster = max_freq.first;
         }
     }
     g.replace_monster_group = jo.get_bool( "replace_monster_group", false );
     g.new_monster_group = mongroup_id( jo.get_string( "new_monster_group_id",
                                        mongroup_id::NULL_ID().str() ) );
     assign( jo, "replacement_time", g.monster_group_time, false, 1_days );
     g.is_safe = jo.get_bool( "is_safe", false );
     g.freq_total = jo.get_int( "freq_total", ( extending ? g.freq_total : 0 ) + freq_total );
     if( jo.get_bool( "auto_total", false ) ) { //Fit the max size to the sum of all freqs
         int total = 0;
         for( MonsterGroupEntry &mon : g.monsters ) {
             total += mon.frequency;
         }
         g.freq_total = total;
     }
     monsterGroupMap[g.name] = g;
 }
References spawn_data::ammo, assign(), MonsterGroupEntry::conditions, MonsterGroupEntry::frequency, g, JsonArray::get_array(), JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), itype_id, line, mon_null, mongroup_id, monsterGroupMap, mtype_id, JsonArray::next_int(), none, string_id< MonsterGroup >::NULL_ID(), and string_id< T >::str().
Referenced by DynamicDataLoader::initialize().
LoadMonsterWhitelist()
void MonsterGroupManager::LoadMonsterWhitelist (const JsonObject & jo) static
Definition at line 378 of file mongroup.cpp.
 {
     if( jo.has_string( "mode" ) && jo.get_string( "mode" ) == "EXCLUSIVE" ) {
         monster_whitelist_is_exclusive = true;
     }
     add_array_to_set( monster_whitelist, jo, "monsters" );
     add_array_to_set( monster_categories_whitelist, jo, "categories" );
     add_array_to_set( monster_species_whitelist, jo, "species" );
 }
References add_array_to_set(), JsonObject::get_string(), JsonObject::has_string(), monster_categories_whitelist, monster_species_whitelist, monster_whitelist, and monster_whitelist_is_exclusive.
Referenced by DynamicDataLoader::initialize().
Monster2Group()
const mongroup_id & MonsterGroupManager::Monster2Group (const mtype_id & monster) static
Definition at line 314 of file mongroup.cpp.
 {
     for( auto &g : monsterGroupMap ) {
         if( g.second.IsMonsterInGroup( monster ) ) {
             return g.second.name;
         }
     }
     return mongroup_id::NULL_ID();
 }
References g, monsterGroupMap, and string_id< MonsterGroup >::NULL_ID().
monster_is_blacklisted()
bool MonsterGroupManager::monster_is_blacklisted (const mtype_id & m) static
Definition at line 389 of file mongroup.cpp.
 {
     if( monster_whitelist.count( m.str() ) > 0 ) {
         return false;
     }
     const mtype &mt = m.obj();
     for( const auto &elem : monster_categories_whitelist ) {
         if( mt.categories.count( elem ) > 0 ) {
             return false;
         }
     }
     for( const auto &elem : monster_species_whitelist ) {
         if( mt.in_species( species_id( elem ) ) ) {
             return false;
         }
     }
     for( const auto &elem : monster_categories_blacklist ) {
         if( mt.categories.count( elem ) > 0 ) {
             return true;
         }
     }
     for( const auto &elem : monster_species_blacklist ) {
         if( mt.in_species( species_id( elem ) ) ) {
             return true;
         }
     }
     if( monster_blacklist.count( m.str() ) > 0 ) {
         return true;
     }
     // Return true if the whitelist mode is exclusive and any whitelist is populated.
     return monster_whitelist_is_exclusive &&
            ( !monster_whitelist.empty() || !monster_categories_whitelist.empty() ||
              !monster_species_whitelist.empty() );
 }
References mtype::categories, mtype::in_species(), monster_blacklist, monster_categories_blacklist, monster_categories_whitelist, monster_species_blacklist, monster_species_whitelist, monster_whitelist, monster_whitelist_is_exclusive, string_id< T >::obj(), and string_id< T >::str().
Referenced by creature_tracker::add(), map::add_spawn(), MonsterGenerator::finalize_mtypes(), FinalizeMonsterGroups(), and monster::try_upgrade().
Member Data Documentation
monster_blacklist
MonsterGroupManager::t_string_set MonsterGroupManager::monster_blacklist static private
Definition at line 229 of file mongroup.h.
Referenced by ClearMonsterGroups(), FinalizeMonsterGroups(), LoadMonsterBlacklist(), and monster_is_blacklisted().
monster_categories_blacklist
MonsterGroupManager::t_string_set MonsterGroupManager::monster_categories_blacklist static private
Definition at line 231 of file mongroup.h.
Referenced by ClearMonsterGroups(), LoadMonsterBlacklist(), and monster_is_blacklisted().
monster_categories_whitelist
MonsterGroupManager::t_string_set MonsterGroupManager::monster_categories_whitelist static private
Definition at line 232 of file mongroup.h.
Referenced by ClearMonsterGroups(), LoadMonsterWhitelist(), and monster_is_blacklisted().
monster_species_blacklist
MonsterGroupManager::t_string_set MonsterGroupManager::monster_species_blacklist static private
Definition at line 233 of file mongroup.h.
Referenced by ClearMonsterGroups(), LoadMonsterBlacklist(), and monster_is_blacklisted().
monster_species_whitelist
MonsterGroupManager::t_string_set MonsterGroupManager::monster_species_whitelist static private
Definition at line 234 of file mongroup.h.
Referenced by ClearMonsterGroups(), LoadMonsterWhitelist(), and monster_is_blacklisted().
monster_whitelist
MonsterGroupManager::t_string_set MonsterGroupManager::monster_whitelist static private
Definition at line 230 of file mongroup.h.
Referenced by ClearMonsterGroups(), FinalizeMonsterGroups(), LoadMonsterWhitelist(), and monster_is_blacklisted().
monsterGroupMap
std::map< mongroup_id, MonsterGroup > MonsterGroupManager::monsterGroupMap static private
Definition at line 227 of file mongroup.h.
Referenced by check_group_definitions(), ClearMonsterGroups(), FinalizeMonsterGroups(), GetMonsterGroup(), isValidMonsterGroup(), LoadMonsterGroup(), and Monster2Group().
The documentation for this class was generated from the following files:
src/mongroup.h
src/mongroup.cpp