Cataclysm DDA: json_flag Class Reference
json_flag Class Reference
Flags: json entity with "type": "json_flag", defined in flags.json, vp_flags.json Currently used by:
#include <flag.h>
Public Member Functions
json_flag ()=default
std::string info () const
Get informative text for display in UI.
std::string restriction () const
Get "restriction" phrase, saying what items with this flag must be able to do.
std::string name () const
Get name of the flag.
const translation & item_prefix () const
Custom prefix that is added to item name.
const translation & item_suffix () const
Custom suffix that is added to item name.
bool inherit () const
Is flag inherited by base items from any attached items?
bool craft_inherit () const
Is flag inherited by crafted items from any component items?
const std::string & requires_flag () const
Requires this flag to be installed on vehicle.
int taste_mod () const
The flag's modifier on the fun value of comestibles.
operator bool () const
Is this a valid (non-null) flag.
void check () const
Static Public Member Functions
static const json_flag & get (const std::string &id)
Fetches flag definition (or null flag if not found)
static bool is_ready ()
true, if flags were loaded
static const std::vector< json_flag > & get_all ()
Public Attributes
flag_id id = flag_NULL
std::vector< std::pair< flag_id, mod_id > > src
bool was_loaded = false
Private Member Functions
void load (const JsonObject &jo, std::string_view src)
Load flag definition from JSON.
Static Private Member Functions
static void load_all (const JsonObject &jo, const std::string &src)
Load all flags from JSON.
static void finalize_all ()
finalize
static void check_consistency ()
Check consistency of all loaded flags.
static void reset ()
Clear all loaded flags (invalidating any pointers)
Private Attributes
translation info_
translation restriction_
translation name_
translation item_prefix_
translation item_suffix_
std::set< std::string > conflicts_
bool inherit_ = true
bool craft_inherit_ = false
std::string requires_flag_
int taste_mod_ = 0
Friends
class DynamicDataLoader
class generic_factory< json_flag >
Detailed Description
Flags: json entity with "type": "json_flag", defined in flags.json, vp_flags.json Currently used by:
Items (itype, item), as int flag_id
Vehicles (vehicle_part), only to display flag info
Effects (effect_type), as int flag_id
Recipes (recipe), flag_id in recipe::flags_to_delete
When flag is used in any of these places, it must have it's definition in json (otherwise flag_id -> flag_id conversion can't be performed).
Definition at line 396 of file flag.h.
Constructor & Destructor Documentation
json_flag()
json_flag::json_flag () default
Referenced by get().
Member Function Documentation
check()
void json_flag::check () const
Definition at line 441 of file flag.cpp.
 {
     for( const auto &conflicting : conflicts_ ) {
         if( !flag_id( conflicting ).is_valid() ) {
             debugmsg( "flag definition %s specifies unknown conflicting field %s", id.str(),
                       conflicting );
         }
     }
 }
References conflicts_, debugmsg, and flag_id.
check_consistency()
void json_flag::check_consistency () static private
Check consistency of all loaded flags.
Definition at line 426 of file flag.cpp.
 {
     json_flags_all.check();
 }
References anonymous_namespace{flag.cpp}::json_flags_all.
Referenced by DynamicDataLoader::check_consistency().
craft_inherit()
bool json_flag::craft_inherit () const inline
Is flag inherited by crafted items from any component items?
Definition at line 443 of file flag.h.
{
             return craft_inherit_;
         }
References craft_inherit_.
finalize_all()
void json_flag::finalize_all () static private
finalize
Definition at line 451 of file flag.cpp.
 {
     json_flags_all.finalize();
 }
References anonymous_namespace{flag.cpp}::json_flags_all.
Referenced by DynamicDataLoader::finalize_loaded_data().
get()
const json_flag & json_flag::get (const std::string & id) static
Fetches flag definition (or null flag if not found)
Definition at line 404 of file flag.cpp.
 {
     static const json_flag null_value = json_flag();
     const flag_id f_id( id );
     return f_id.is_valid() ? *f_id : null_value;
 }
References string_id< T >::is_valid(), and json_flag().
Referenced by vehicle::break_off(), vehicle::can_mount(), vehicle::can_unmount(), vpart_info::check(), and vpart_info::format_description().
get_all()
const std::vector< json_flag > & json_flag::get_all () static
Definition at line 461 of file flag.cpp.
 {
     return json_flags_all.get_all();
 }
References anonymous_namespace{flag.cpp}::json_flags_all.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach().
info()
std::string json_flag::info () const inline
Get informative text for display in UI.
Definition at line 413 of file flag.h.
{
             return info_.translated();
         }
References info_, and translation::translated().
Referenced by item::properties_info().
inherit()
bool json_flag::inherit () const inline
Is flag inherited by base items from any attached items?
Definition at line 438 of file flag.h.
{
             return inherit_;
         }
References inherit_.
is_ready()
bool json_flag::is_ready () static
true, if flags were loaded
Definition at line 456 of file flag.cpp.
 {
     return !json_flags_all.empty();
 }
References anonymous_namespace{flag.cpp}::json_flags_all.
Referenced by Character::Character().
item_prefix()
const translation& json_flag::item_prefix () const inline
Custom prefix that is added to item name.
Definition at line 428 of file flag.h.
{
             return item_prefix_;
         }
References item_prefix_.
Referenced by item::update_prefix_suffix_flags().
item_suffix()
const translation& json_flag::item_suffix () const inline
Custom suffix that is added to item name.
Definition at line 433 of file flag.h.
{
             return item_suffix_;
         }
References item_suffix_.
Referenced by item::update_prefix_suffix_flags().
load()
void json_flag::load (const JsonObject & jo, std::string_view src) private
Load flag definition from JSON.
Definition at line 411 of file flag.cpp.
 {
     // TODO: mark fields as mandatory where appropriate
     optional( jo, was_loaded, "info", info_ );
     optional( jo, was_loaded, "conflicts", conflicts_ );
     optional( jo, was_loaded, "inherit", inherit_, true );
     optional( jo, was_loaded, "craft_inherit", craft_inherit_, false );
     optional( jo, was_loaded, "requires_flag", requires_flag_ );
     optional( jo, was_loaded, "taste_mod", taste_mod_ );
     optional( jo, was_loaded, "restriction", restriction_ );
     optional( jo, was_loaded, "name", name_ );
     optional( jo, was_loaded, "item_prefix", item_prefix_ );
     optional( jo, was_loaded, "item_suffix", item_suffix_ );
 }
References conflicts_, craft_inherit_, info_, inherit_, item_prefix_, item_suffix_, name_, optional(), requires_flag_, restriction_, taste_mod_, and was_loaded.
load_all()
void json_flag::load_all (const JsonObject & jo, const std::string & src) static private
Load all flags from JSON.
Definition at line 436 of file flag.cpp.
 {
     json_flags_all.load( jo, src );
 }
References anonymous_namespace{flag.cpp}::json_flags_all, and src.
Referenced by DynamicDataLoader::initialize().
name()
std::string json_flag::name () const inline
Get name of the flag.
Definition at line 423 of file flag.h.
{
             return name_.translated();
         }
References name_, and translation::translated().
Referenced by exosuit_interact::get_pocket_name(), item::gun_info(), and item::tool_info().
operator bool()
json_flag::operator bool () const explicit
Is this a valid (non-null) flag.
Definition at line 399 of file flag.cpp.
 {
     return id.is_valid();
 }
requires_flag()
const std::string& json_flag::requires_flag () const inline
Requires this flag to be installed on vehicle.
Definition at line 448 of file flag.h.
{
             return requires_flag_;
         }
References requires_flag_.
Referenced by vehicle::break_off(), vehicle::can_mount(), and vehicle::can_unmount().
reset()
void json_flag::reset () static private
Clear all loaded flags (invalidating any pointers)
Definition at line 431 of file flag.cpp.
 {
     json_flags_all.reset();
 }
References anonymous_namespace{flag.cpp}::json_flags_all.
Referenced by DynamicDataLoader::unload_data().
restriction()
std::string json_flag::restriction () const inline
Get "restriction" phrase, saying what items with this flag must be able to do.
Definition at line 418 of file flag.h.
{
             return restriction_.translated();
         }
References restriction_, and translation::translated().
Referenced by item_pocket::general_info().
taste_mod()
int json_flag::taste_mod () const inline
The flag's modifier on the fun value of comestibles.
Definition at line 453 of file flag.h.
{
             return taste_mod_;
         }
References taste_mod_.
Friends And Related Function Documentation
DynamicDataLoader
friend class DynamicDataLoader friend
Definition at line 398 of file flag.h.
generic_factory< json_flag >
friend class generic_factory< json_flag > friend
Definition at line 398 of file flag.h.
Member Data Documentation
conflicts_
std::set<std::string> json_flag::conflicts_ private
Definition at line 473 of file flag.h.
Referenced by check(), and load().
craft_inherit_
bool json_flag::craft_inherit_ = false private
Definition at line 475 of file flag.h.
Referenced by craft_inherit(), and load().
id
flag_id json_flag::id = flag_NULL
Definition at line 403 of file flag.h.
info_
translation json_flag::info_ private
Definition at line 468 of file flag.h.
Referenced by info(), and load().
inherit_
bool json_flag::inherit_ = true private
Definition at line 474 of file flag.h.
Referenced by inherit(), and load().
item_prefix_
translation json_flag::item_prefix_ private
Definition at line 471 of file flag.h.
Referenced by item_prefix(), and load().
item_suffix_
translation json_flag::item_suffix_ private
Definition at line 472 of file flag.h.
Referenced by item_suffix(), and load().
name_
translation json_flag::name_ private
Definition at line 470 of file flag.h.
Referenced by load(), and name().
requires_flag_
std::string json_flag::requires_flag_ private
Definition at line 476 of file flag.h.
Referenced by load(), and requires_flag().
restriction_
translation json_flag::restriction_ private
Definition at line 469 of file flag.h.
Referenced by load(), and restriction().
src
std::vector<std::pair<flag_id, mod_id> > json_flag::src
Definition at line 404 of file flag.h.
Referenced by load_all().
taste_mod_
int json_flag::taste_mod_ = 0 private
Definition at line 477 of file flag.h.
Referenced by load(), and taste_mod().
was_loaded
bool json_flag::was_loaded = false
Definition at line 405 of file flag.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/flag.h
src/flag.cpp