Cataclysm DDA: jmapgen_item_group Class Reference
jmapgen_item_group Class Reference
Place items from an item group.
Public Member Functions
jmapgen_item_group (const JsonObject &jsi, const std::string_view context)
void check (const std::string &context, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
item_group_id group_id
jmapgen_int chance
std::string faction
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place items from an item group.
"item": id of the item group. "chance": chance of items being placed, see repeat: number of times to apply this piece
Definition at line 2269 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_item_group()
jmapgen_item_group::jmapgen_item_group (const JsonObject & jsi, const std::string_view context) inline
Definition at line 2275 of file mapgen.cpp.
                                                                                   :
             chance( jsi, "chance", 100, 100 ) {
             JsonValue group = jsi.get_member( "item" );
             group_id = item_group::load_item_group( group, "collection",
                                                     str_cat( "mapgen item group ", context ) );
             if( jsi.has_int( "prob" ) ) {
                 debugmsg( "prob definition in group %s with context %s should be replaced with chance where chance is a percent and defaults to 100",
                           group_id.c_str(), context );
             }
             repeat = jmapgen_int( jsi, "repeat", 1, 1 );
             if( jsi.has_string( "faction" ) ) {
                 faction = jsi.get_string( "faction" );
             }
         }
References string_id< T >::c_str(), context, debugmsg, JsonObject::get_member(), JsonObject::get_string(), group_id, JsonObject::has_int(), JsonObject::has_string(), mapgen_defer::jsi, item_group::load_item_group(), jmapgen_piece::repeat, and str_cat().
Member Function Documentation
apply()
void jmapgen_item_group::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2295 of file mapgen.cpp.
{
             dat.m.place_items( group_id, chance.get(), point( x.val, y.val ), point( x.valmax, y.valmax ),
                                dat.zlevel() + z.get(), true,
                                calendar::start_of_cataclysm, 0, 0, faction );
         }
References chance, jmapgen_int::get(), group_id, mapgendata::m, map::place_items(), calendar::start_of_cataclysm, jmapgen_int::val, jmapgen_int::valmax, and mapgendata::zlevel().
check()
void jmapgen_item_group::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 2289 of file mapgen.cpp.
{
             if( !group_id.is_valid() ) {
                 debugmsg( "Invalid item_group_id \"%s\" in %s", group_id.str(), context );
             }
         }
References context, debugmsg, group_id, string_id< T >::is_valid(), and string_id< T >::str().
Member Data Documentation
chance
jmapgen_int jmapgen_item_group::chance
Definition at line 2273 of file mapgen.cpp.
Referenced by apply().
faction
std::string jmapgen_item_group::faction
Definition at line 2274 of file mapgen.cpp.
group_id
item_group_id jmapgen_item_group::group_id
Definition at line 2272 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_item_group().
The documentation for this class was generated from the following file:
src/mapgen.cpp