Cataclysm DDA: ui_adaptor Class Reference
ui_adaptor Class Reference
Adaptor between UI code and the UI management system.
#include <ui_manager.h>
Classes
struct debug_message_ui
struct disable_uis_below
Public Types
using redraw_callback_t = std::function< void(ui_adaptor &)>
using screen_resize_callback_t = std::function< void(ui_adaptor &)>
Public Member Functions
ui_adaptor ()
Construct a ui_adaptor which is automatically added to the UI stack, and removed from the stack when it is deconstructed.
ui_adaptor (disable_uis_below)
ui_adaptor constructed this way will block any UIs below from being redrawn or resized until it is deconstructed.
ui_adaptor (debug_message_ui)
Special constructor used by debug.cpp when showing a debug message popup.
ui_adaptor (const ui_adaptor &rhs)=delete
ui_adaptor (ui_adaptor &&rhs)=delete
~ui_adaptor ()
ui_adaptor & operator= (const ui_adaptor &rhs)=delete
ui_adaptor & operator= (ui_adaptor &&rhs)=delete
void position_from_window (const catacurses::window &win)
Set the position and size of the UI to that of win.
void position (const point &topleft, const point &size)
Set the position and size of the UI to that of an imaginary catacurses::window in normal font, except that the size can be zero.
void position_absolute (const point &topleft, const point &size)
like 'position', except topleft and size are given as pixels in tiled builds and console cells on curses builds
void on_redraw (const redraw_callback_t &fun)
Set redraw and resize callbacks.
void on_screen_resize (const screen_resize_callback_t &fun)
void set_cursor (const catacurses::window &win, const point &pos)
Automatically set the termianl cursor to a window position after drawing is done.
void record_cursor (const catacurses::window &win)
Record the current window cursor position and restore it when drawing is done.
void record_term_cursor ()
Record the current terminal cursor position (where the cursor was placed when refreshing the last window) and restore it when drawing is done.
void default_cursor ()
Use the terminal cursor position when the redraw callback returns.
void disable_cursor ()
Do not set cursor for this ui_adaptor.
void mark_resize () const
Mark this ui_adaptor for resizing the next time it is redrawn.
void invalidate_ui () const
Invalidate this UI so it gets redrawn the next redraw unless an upper UI completely occludes this UI.
void reset ()
Reset all callbacks and dimensions.
Static Public Member Functions
static void invalidate (const rectangle< point > &rect, bool reenable_uis_below)
static bool has_imgui ()
static void redraw ()
static void redraw_invalidated ()
static void screen_resized ()
Public Attributes
bool is_imgui
bool is_on_top
Private Types
enum class cursor { last , custom , disabled }
Static Private Member Functions
static void invalidation_consistency_and_optimization ()
Private Attributes
rectangle< point > dimensions
redraw_callback_t redraw_cb
screen_resize_callback_t screen_resized_cb
cursor cursor_type = cursor::last
point cursor_pos
bool disabling_uis_below
bool is_debug_message_ui
bool invalidated
bool deferred_resize
Detailed Description
Adaptor between UI code and the UI management system.
Using this class allows UIs to be correctly resized and redrawn when the game window is resized or when exiting from other UIs.
Usage example:
// Effective in the local scope
ui_adaptor ui;
// Ncurses window for drawing
catacurses::window win;
// Things to do when the game window changes size
ui.on_screen_resize([&](ui_adaptor & ui) {
    // Create an ncurses window
    win = catacurses::newwin( TERMX / 2, TERMY / 2, point( TERMX / 4, TERMY / 4 ) );
    // The window passed to this call must contain all the space the redraw
    // callback draws to, to ensure proper refreshing when resizing or exiting
    // from other UIs.
    ui.position_from_window( win );
});
// Mark the resize callback to be called on the first redraw
ui.mark_resize();
// Things to do when redrawing the UI
ui.on_redraw([&](ui_adaptor & ui) {
    // Clear UI area
    werase( win );
    // Print things
    mvwprintw( win, point_zero, "Hello World!" );
    // Record the cursor position for screen readers and IME preview to
    // correctly function on curses
    ui.record_cursor( win );
    // Write to frame buffer
    wnoutrefresh( win );
});
input_context ctxt("<CATEGORY_NAME>");
ctxt.register_action("QUIT");
while(true) {
    // Invalidate the top UI (that is, this UI) and redraw all
    // invalidated UIs (including lower UIs that calls this UI).
    // May call the resize callbacks.
    ui_manager::redraw();
    // Get user input. Note that this may call the resize and redraw
    // callbacks multiple times due to screen resize, rendering target
    // reset, etc.
    const std::string action = ctxt.handle_input();
    if( action == "QUIT" ) {
        break;
    }
}
Definition at line 74 of file ui_manager.h.
Member Typedef Documentation
redraw_callback_t
using ui_adaptor::redraw_callback_t = std::function<void(ui_adaptor &)>
Definition at line 79 of file ui_manager.h.
screen_resize_callback_t
using ui_adaptor::screen_resize_callback_t = std::function<void(ui_adaptor &)>
Definition at line 80 of file ui_manager.h.
Member Enumeration Documentation
cursor
enum ui_adaptor::cursor strong private
Enumerator
last
custom
disabled
Definition at line 243 of file ui_manager.h.
{
             last, custom, disabled
         };
Constructor & Destructor Documentation
ui_adaptor() [1/5]
ui_adaptor::ui_adaptor ()
Construct a ui_adaptor which is automatically added to the UI stack, and removed from the stack when it is deconstructed.
(When declared as a local variable, it is removed from the stack when leaving the local scope.)
Definition at line 33 of file ui_manager.cpp.
                        : is_imgui( false ), disabling_uis_below( false ),
     is_debug_message_ui( false ),
     invalidated( false ), deferred_resize( false )
 {
     ui_stack.emplace_back( *this );
 }
References ui_stack.
ui_adaptor() [2/5]
ui_adaptor::ui_adaptor (ui_adaptor::disable_uis_below) explicit
ui_adaptor constructed this way will block any UIs below from being redrawn or resized until it is deconstructed.
Definition at line 40 of file ui_manager.cpp.
                                                     : is_imgui( false ),
     disabling_uis_below( true ),
     is_debug_message_ui( false ), invalidated( false ), deferred_resize( false )
 {
     ui_stack.emplace_back( *this );
 }
References ui_stack.
ui_adaptor() [3/5]
ui_adaptor::ui_adaptor (ui_adaptor::debug_message_ui) explicit
Special constructor used by debug.cpp when showing a debug message popup.
If the UI is constructed when a redraw call is in progress, The redraw call will be restarted after this UI is deconstructed and the in progress callback returns, in order to prevent incorrect graphics caused by overwritten screen area and resizing.
Definition at line 47 of file ui_manager.cpp.
                                                    : is_imgui( false ),
     disabling_uis_below( true ),
     is_debug_message_ui( true ), invalidated( false ), deferred_resize( false )
 {
     cata_assert( !showing_debug_message );
     showing_debug_message = true;
     if( redraw_in_progress ) {
         restart_redrawing = true;
     }
 #if defined( TILES )
     // Reset the clip rect because the debug message UI might be created in a
     // redraw callback when a clip rect is active. When the UI is deconstructed,
     // restore the previous clip rect to prevent the redraw callback from
     // drawing outside the clip area, which will cause stuck graphics. This
     // alone does not prevent the graphics from becoming borked in other ways,
     // but `ui_manager` will redo the entire redrawing as soon as the redraw
     // callback returns.
     const SDL_Renderer_Ptr &renderer = get_sdl_renderer();
     if( SDL_RenderIsClipEnabled( renderer.get() ) ) {
         prev_clip_rect = SDL_Rect();
         SDL_RenderGetClipRect( renderer.get(), &prev_clip_rect.value() );
         SDL_RenderSetClipRect( renderer.get(), nullptr );
     } else {
         prev_clip_rect = std::nullopt;
     }
 #endif
     ui_stack.emplace_back( *this );
 }
References cata_assert, redraw_in_progress, restart_redrawing, showing_debug_message, and ui_stack.
ui_adaptor() [4/5]
ui_adaptor::ui_adaptor (const ui_adaptor & rhs) delete
ui_adaptor() [5/5]
ui_adaptor::ui_adaptor (ui_adaptor && rhs) delete
~ui_adaptor()
ui_adaptor::~ui_adaptor ()
Definition at line 76 of file ui_manager.cpp.
 {
     if( is_debug_message_ui ) {
         cata_assert( showing_debug_message );
         showing_debug_message = false;
 #if defined( TILES )
         // See ui_adaptor( debug_message_ui )
         if( prev_clip_rect.has_value() ) {
             const SDL_Renderer_Ptr &renderer = get_sdl_renderer();
             SDL_RenderSetClipRect( renderer.get(), &prev_clip_rect.value() );
         }
 #endif
     }
     for( auto it = ui_stack.rbegin(); it < ui_stack.rend(); ++it ) {
         if( &it->get() == this ) {
             ui_stack.erase( std::prev( it.base() ) );
             // TODO avoid invalidating portions that do not need to be redrawn
             ui_manager::invalidate( dimensions, disabling_uis_below );
             break;
         }
     }
 }
References cata_assert, dimensions, disabling_uis_below, ui_manager::invalidate(), is_debug_message_ui, showing_debug_message, and ui_stack.
Member Function Documentation
default_cursor()
void ui_adaptor::default_cursor ()
Use the terminal cursor position when the redraw callback returns.
This is the default. See also set_cursor.
Definition at line 189 of file ui_manager.cpp.
 {
 #if !defined( TILES )
     cursor_type = cursor::last;
 #else
     // Unimplemented
     cursor_type = cursor::disabled;
 #endif
 }
References cursor_type, disabled, and last.
disable_cursor()
void ui_adaptor::disable_cursor ()
Do not set cursor for this ui_adaptor.
If any higher or lower UI sets the cursor, that cursor position is used instead. If no UI sets the cursor, the final cursor position when drawing is done is used. See also set_cursor.
Definition at line 199 of file ui_manager.cpp.
 {
     cursor_type = cursor::disabled;
 }
References cursor_type, and disabled.
Referenced by Character::disp_info().
has_imgui()
bool ui_adaptor::has_imgui () static
Definition at line 330 of file ui_manager.cpp.
 {
     for( auto ui : ui_stack ) {
         if( ui.get().is_imgui ) {
             return true;
         }
     }
     return false;
 }
References ui_stack.
Referenced by cataimgui::window::~window().
invalidate()
void ui_adaptor::invalidate (const rectangle< point > & rect, bool reenable_uis_below) static
Definition at line 309 of file ui_manager.cpp.
 {
     if( rect.p_min.x >= rect.p_max.x || rect.p_min.y >= rect.p_max.y ) {
         if( reenable_uis_below ) {
             invalidation_consistency_and_optimization();
         }
         return;
     }
     // Always invalidate every UI, even if it is below another UI with
     // `disable_uis_below`, so when the UI with `disable_uis_below` is removed,
     // UIs below are correctly marked for redraw.
     for( auto it_upper = ui_stack.cbegin(); it_upper < ui_stack.cend(); ++it_upper ) {
         const ui_adaptor &ui_upper = it_upper->get();
         if( !ui_upper.invalidated && overlap( ui_upper.dimensions, rect ) ) {
             // invalidated by `rect`
             ui_upper.invalidated = true;
         }
     }
     invalidation_consistency_and_optimization();
 }
References dimensions, invalidated, invalidation_consistency_and_optimization(), overlap(), rectangle< Point, >::p_max, rectangle< Point, >::p_min, ui_stack, point::x, and point::y.
Referenced by ui_manager::invalidate().
invalidate_ui()
void ui_adaptor::invalidate_ui () const
Invalidate this UI so it gets redrawn the next redraw unless an upper UI completely occludes this UI.
May also cause upper UIs to redraw. Can be used to mark lower UIs for redrawing when their associated data has changed.
Definition at line 275 of file ui_manager.cpp.
 {
     if( invalidated ) {
         return;
     }
     auto it = ui_stack.cbegin();
     for( ; it < ui_stack.cend(); ++it ) {
         if( &it->get() == this ) {
             break;
         }
     }
     if( it == ui_stack.end() ) {
         return;
     }
     // If an upper UI occludes this UI then nothing gets redrawn
     for( auto it_upper = std::next( it ); it_upper < ui_stack.cend(); ++it_upper ) {
         if( contains( it_upper->get().dimensions, dimensions ) ) {
             return;
         }
     }
     // Always mark this UI for redraw even if it is below another UI with
     // `disable_uis_below`, so when the UI with `disable_uis_below` is removed,
     // this UI is correctly marked for redraw.
     invalidated = true;
     invalidation_consistency_and_optimization();
 }
References contains, dimensions, invalidated, invalidation_consistency_and_optimization(), and ui_stack.
Referenced by handle_player_display_action(), overmap_ui::place_ter_or_special(), trade_ui::recalc_values_cpane(), overmap_ui::search(), and diary::show_diary_ui().
invalidation_consistency_and_optimization()
void ui_adaptor::invalidation_consistency_and_optimization () static private
Definition at line 237 of file ui_manager.cpp.
 {
     // Only ensure consistency and optimize for UIs not disabled by another UI
     // with `disable_uis_below`, since if a UI is disabled, it does not get
     // resized or redrawn, so the invalidation flag is not cleared, and including
     // the disabled UI in the following calculation would unnecessarily
     // invalidate any upper intersecting UIs.
     auto rfirst = ui_stack.crbegin();
     for( ; rfirst != ui_stack.crend(); ++rfirst ) {
         if( rfirst->get().disabling_uis_below ) {
             break;
         }
     }
     const auto first = rfirst == ui_stack.crend() ? ui_stack.cbegin() : std::prev( rfirst.base() );
     for( auto it_upper = first; it_upper < ui_stack.cend(); ++it_upper ) {
         const ui_adaptor &ui_upper = it_upper->get();
         for( auto it_lower = first; it_lower < it_upper; ++it_lower ) {
             const ui_adaptor &ui_lower = it_lower->get();
             if( !ui_upper.invalidated && ui_lower.invalidated &&
                 overlap( ui_upper.dimensions, ui_lower.dimensions ) ) {
                 // invalidated by lower invalidated UIs
                 ui_upper.invalidated = true;
             }
             if( ui_upper.invalidated && ui_lower.invalidated &&
                 contains( ui_upper.dimensions, ui_lower.dimensions ) ) {
                 // fully obscured lower UIs do not need to be redrawn.
                 ui_lower.invalidated = false;
                 // Note: we don't need to re-test ui_lower from earlier iterations
                 // during which ui_upper.invalidated hadn't yet been determined to
                 // be true, because if the ui_lower would be obscured by ui_upper,
                 // it implies that ui_lower would overlap with ui_upper, by which
                 // we would have already determined ui_upper.invalidated to be true
                 // then.
             }
         }
     }
 }
References contains, dimensions, invalidated, overlap(), and ui_stack.
Referenced by invalidate(), and invalidate_ui().
mark_resize()
void ui_adaptor::mark_resize () const
Mark this ui_adaptor for resizing the next time it is redrawn.
This is normally called alongside on_screen_resize to initialize the UI on the first redraw. You should also use this function to explicitly request a reinitialization if any value the screen resize callback depends on (apart from the screen size) has changed.
Definition at line 213 of file ui_manager.cpp.
 {
     deferred_resize = true;
 }
References deferred_resize.
Referenced by debug_menu::change_spells(), veh_interact::create_or_get_ui_adaptor(), Character::disp_info(), inventory_examiner::execute(), diary::show_diary_ui(), and trade_ui::trade_ui().
on_redraw()
void ui_adaptor::on_redraw (const redraw_callback_t & fun)
Set redraw and resize callbacks.
The resize callback should call position or position_from_window to set the size of the UI, and (re-)calculate any UI data that is related to the screen size, including catacurses::window instances. In most cases, you should also call mark_resize along with on_screen_resize so the UI is initialized by the resizing callback when redrawn for the first time.
The redraw callback should only redraw to the area specified by the position or position_from_window call. Content drawn outside this area may not render correctly when resizing or exiting from other UIs. Transparency is not currently supported.
These callbacks should NOT:
Construct new ui_adaptor instances
Deconstruct old ui_adaptor instances
Call redraw or screen_resized
(Redraw callback) call position_from_window, position, or invalidate_ui
Call any function that does these things, except for debugmsg
Otherwise, display glitches or even crashes might happen.
Definition at line 143 of file ui_manager.cpp.
 {
     redraw_cb = fun;
 }
References redraw_cb.
Referenced by debug_menu::change_spells(), veh_interact::create_or_get_ui_adaptor(), Character::disp_info(), inventory_examiner::execute(), reset(), auto_pickup::user_interface::show(), safemode::show(), diary::show_diary_ui(), and trade_ui::trade_ui().
on_screen_resize()
void ui_adaptor::on_screen_resize (const screen_resize_callback_t & fun)
Definition at line 148 of file ui_manager.cpp.
 {
     screen_resized_cb = fun;
 }
References screen_resized_cb.
Referenced by debug_menu::change_spells(), Character::disp_info(), inventory_examiner::execute(), reset(), auto_pickup::user_interface::show(), safemode::show(), diary::show_diary_ui(), and trade_ui::trade_ui().
operator=() [1/2]
ui_adaptor& ui_adaptor::operator= (const ui_adaptor & rhs) delete
operator=() [2/2]
ui_adaptor& ui_adaptor::operator= (ui_adaptor && rhs) delete
position()
void ui_adaptor::position (const point & topleft, const point & size)
Set the position and size of the UI to that of an imaginary catacurses::window in normal font, except that the size can be zero.
Note that topleft and size are in console cells on both tiles and curses builds.
Definition at line 119 of file ui_manager.cpp.
 {
     const rectangle<point> old_dimensions = dimensions;
     // ensure position is updated before calling invalidate
 #ifdef TILES
     const window_dimensions dim = get_window_dimensions( topleft, size );
     dimensions = rectangle<point>( dim.window_pos_pixel,
                                    dim.window_pos_pixel + dim.window_size_pixel );
 #else
     dimensions = rectangle<point>( topleft, topleft + size );
 #endif
     invalidated = true;
     ui_manager::invalidate( old_dimensions, false );
 }
References dimensions, ui_manager::invalidate(), invalidated, and om_direction::size.
Referenced by veh_interact::create_or_get_ui_adaptor(), position_from_window(), and reset().
position_absolute()
void ui_adaptor::position_absolute (const point & topleft, const point & size)
like 'position', except topleft and size are given as pixels in tiled builds and console cells on curses builds
Definition at line 134 of file ui_manager.cpp.
 {
     const rectangle<point> old_dimensions = dimensions;
     // ensure position is updated before calling invalidate
     dimensions = rectangle<point>( topleft, topleft + size );
     invalidated = true;
     ui_manager::invalidate( old_dimensions, false );
 }
References dimensions, ui_manager::invalidate(), invalidated, and om_direction::size.
position_from_window()
void ui_adaptor::position_from_window (const catacurses::window & win)
Set the position and size of the UI to that of win.
This information is used to calculate which UIs need redrawing during resizing and when exiting from other UIs, so do call this function in the resizing callback and ensure win contains all the space you will be drawing to. Transparency is not supported. If win is null, the function has the same effect as position(point_zero, point_zero)
Definition at line 99 of file ui_manager.cpp.
 {
     if( !win ) {
         position( point_zero, point_zero );
     } else {
         const rectangle<point> old_dimensions = dimensions;
         // ensure position is updated before calling invalidate
 #ifdef TILES
         const window_dimensions dim = get_window_dimensions( win );
         dimensions = rectangle<point>(
                          dim.window_pos_pixel, dim.window_pos_pixel + dim.window_size_pixel );
 #else
         const point origin( getbegx( win ), getbegy( win ) );
         dimensions = rectangle<point>( origin, origin + point( getmaxx( win ), getmaxy( win ) ) );
 #endif
         invalidated = true;
         ui_manager::invalidate( old_dimensions, false );
     }
 }
References dimensions, catacurses::getbegx(), catacurses::getbegy(), catacurses::getmaxx(), catacurses::getmaxy(), ui_manager::invalidate(), invalidated, point, point_zero, and position().
Referenced by bodygraph_display::create_or_get_ui_adaptor(), exosuit_interact::create_or_get_ui_adaptor(), prof_window::create_or_get_ui_adaptor(), veh_app_interact::create_or_get_ui_adaptor(), veh_interact::create_or_get_ui_adaptor(), Character::disp_info(), inventory_examiner::execute(), auto_pickup::user_interface::show(), and safemode::show().
record_cursor()
void ui_adaptor::record_cursor (const catacurses::window & win)
Record the current window cursor position and restore it when drawing is done.
The most recent cursor position is recorded regardless of whether the terminal cursor is updated by refreshing the window. See also set_cursor.
Definition at line 166 of file ui_manager.cpp.
 {
 #if !defined( TILES )
     cursor_type = cursor::custom;
     cursor_pos = point( getbegx( w ) + getcurx( w ), getbegy( w ) + getcury( w ) );
 #else
     // Unimplemented
     cursor_type = cursor::disabled;
     static_cast<void>( w );
 #endif
 }
References cursor_pos, cursor_type, custom, disabled, catacurses::getbegx(), catacurses::getbegy(), catacurses::getcurx(), catacurses::getcury(), and point.
record_term_cursor()
void ui_adaptor::record_term_cursor ()
Record the current terminal cursor position (where the cursor was placed when refreshing the last window) and restore it when drawing is done.
See also set_cursor.
Definition at line 178 of file ui_manager.cpp.
 {
 #if !defined( TILES ) && !defined(_MSC_VER)
     cursor_type = cursor::custom;
     cursor_pos = point( getcurx( catacurses::newscr ), getcury( catacurses::newscr ) );
 #else
     // Unimplemented
     cursor_type = cursor::disabled;
 #endif
 }
References cursor_pos, cursor_type, custom, disabled, catacurses::getcurx(), catacurses::getcury(), catacurses::newscr, and point.
redraw()
void ui_adaptor::redraw () static
Definition at line 340 of file ui_manager.cpp.
 {
     if( !ui_stack.empty() ) {
         ui_stack.back().get().invalidated = true;
     }
     redraw_invalidated();
 }
References redraw_invalidated(), and ui_stack.
Referenced by ui_manager::redraw(), and screen_resized().
redraw_invalidated()
void ui_adaptor::redraw_invalidated () static
Definition at line 348 of file ui_manager.cpp.
 {
     if( test_mode || ui_stack.empty() ) {
         return;
     }
     // This boolean is needed when a debug error is thrown inside redraw_invalidated
     if( !imgui_frame_started ) {
         imclient->new_frame();
     }
     imgui_frame_started = true;
     restore_on_out_of_scope<bool> prev_redraw_in_progress( redraw_in_progress );
     restore_on_out_of_scope<bool> prev_restart_redrawing( restart_redrawing );
     redraw_in_progress = true;
     do {
         // Changed by the resize and redraw callbacks if they call `debugmsg`.
         // When this becomes true, the `debugmsg` call would have already changed
         // the resize and redraw flags according to the resized and redrawn states
         // so far, so we restart redrawing using the changed flags to redraw
         // the area invalidated by the debug message popup.
         restart_redrawing = false;
         // Find the first enabled UI. From now on enabling and disabling UIs
         // have no effect until the end of this call.
         auto first = ui_stack.rbegin();
         for( ; first != ui_stack.rend(); ++first ) {
             if( first->get().disabling_uis_below ) {
                 break;
             }
         }
         // Avoid a copy if possible to improve performance. `ui_stack_orig`
         // always contains the original UI stack, and `first_enabled` always points
         // to elements of `ui_stack_orig`.
         std::unique_ptr<ui_stack_t> ui_stack_copy;
         auto first_enabled = first == ui_stack.rend() ? ui_stack.begin() : std::prev( first.base() );
         ui_stack_t *ui_stack_orig = &ui_stack;
         // Apply deferred resizing.
         bool needs_resize = false;
         for( auto it = first_enabled; !needs_resize && it != ui_stack_orig->end(); ++it ) {
             ui_adaptor &ui = *it;
             if( ui.deferred_resize && ui.screen_resized_cb ) {
                 needs_resize = true;
             }
         }
         if( needs_resize ) {
             if( !ui_stack_copy ) {
                 // Callbacks may modify the UI stack; make a copy of the original one.
                 ui_stack_copy = std::make_unique<ui_stack_t>( *ui_stack_orig );
                 first_enabled = ui_stack_copy->begin() + ( first_enabled - ui_stack_orig->begin() );
                 ui_stack_orig = &*ui_stack_copy;
             }
             for( auto it = first_enabled; !restart_redrawing && it != ui_stack_orig->end(); ++it ) {
                 ui_adaptor &ui = *it;
                 if( ui.deferred_resize ) {
                     if( ui.screen_resized_cb ) {
                         ui.screen_resized_cb( ui );
                     }
                     if( !restart_redrawing ) {
                         ui.deferred_resize = false;
                     }
                 }
             }
         }
         // Redraw invalidated UIs.
         bool needs_redraw = false;
         if( !restart_redrawing ) {
             for( auto it = first_enabled; !needs_redraw && it != ui_stack_orig->end(); ++it ) {
                 const ui_adaptor &ui = *it;
                 if( ( ui.invalidated || ui.is_imgui ) && ui.redraw_cb ) {
                     needs_redraw = true;
                 }
             }
         }
         if( !restart_redrawing && needs_redraw ) {
             if( !ui_stack_copy ) {
                 // Callbacks may change the UI stack; make a copy of the original one.
                 ui_stack_copy = std::make_unique<ui_stack_t>( *ui_stack_orig );
                 first_enabled = ui_stack_copy->begin() + ( first_enabled - ui_stack_orig->begin() );
                 ui_stack_orig = &*ui_stack_copy;
             }
             std::optional<point> cursor_pos;
             auto top_ui = std::prev( ui_stack_orig->end() );
             for( auto it = first_enabled; !restart_redrawing && it != ui_stack_orig->end(); ++it ) {
                 ui_adaptor &ui = *it;
                 ui.is_on_top = it == top_ui;
                 if( ui.invalidated || ui.is_imgui ) {
                     if( ui.redraw_cb ) {
                         ui.default_cursor();
                         ui.redraw_cb( ui );
                         if( ui.cursor_type == cursor::last ) {
                             ui.record_term_cursor();
                             cata_assert( ui.cursor_type != cursor::last );
                         }
                         if( ui.cursor_type == cursor::custom ) {
                             cursor_pos = ui.cursor_pos;
                         }
                     }
                     if( !restart_redrawing ) {
                         ui.invalidated = false;
                     }
                 }
             }
             if( !restart_redrawing && cursor_pos.has_value() ) {
                 restore_cursor( cursor_pos.value() );
             }
         }
     } while( restart_redrawing );
 #if defined(EMSCRIPTEN)
     emscripten_sleep( 1 );
 #endif
     imclient->end_frame();
     imgui_frame_started = false;
     // if any ImGui window needed to calculate the size of its contents,
     //  it needs an extra frame to draw. We do that here.
     if( imclient->auto_size_frame_active() ) {
         redraw_invalidated();
     }
 }
References cata_assert, cursor_pos, custom, imclient, imgui_frame_started, last, redraw_in_progress, restart_redrawing, restore_cursor(), test_mode, and ui_stack.
Referenced by redraw(), and ui_manager::redraw_invalidated().
reset()
void ui_adaptor::reset ()
Reset all callbacks and dimensions.
Will cause invalidation of the previously specified screen area.
Definition at line 302 of file ui_manager.cpp.
 {
     on_screen_resize( nullptr );
     on_redraw( nullptr );
     position( point_zero, point_zero );
 }
References on_redraw(), on_screen_resize(), point_zero, and position().
screen_resized()
void ui_adaptor::screen_resized () static
Definition at line 473 of file ui_manager.cpp.
 {
     // Always mark every UI for resize even if it is below another UI with
     // `disable_uis_below`, so when the UI with `disable_uis_below` is removed,
     // UIs below are correctly marked for resize.
     for( ui_adaptor &ui : ui_stack ) {
         ui.deferred_resize = true;
     }
     redraw();
 }
References redraw(), and ui_stack.
Referenced by ui_manager::screen_resized().
set_cursor()
void ui_adaptor::set_cursor (const catacurses::window & win, const point & pos)
Automatically set the termianl cursor to a window position after drawing is done.
The cursor position of the last drawn UI takes effect. This ensures the cursor is always set to the desired position even if some subsequent drawing code moves the cursor, so screen readers (and in the case of text input, the IME preview) can correctly function. This is only supposed to be called from the on_redraw callback on the ui_adaptor argument of the callback. Currently only supports curses (on tiles, the windows may have different cell sizes, so the current implementation of recording the on-screen position does not work, and screen readers do not work with the current tiles implementation anyway).
Definition at line 153 of file ui_manager.cpp.
 {
 #if !defined( TILES )
     cursor_type = cursor::custom;
     cursor_pos = point( getbegx( w ), getbegy( w ) ) + pos;
 #else
     // Unimplemented
     cursor_type = cursor::disabled;
     static_cast<void>( w );
     static_cast<void>( pos );
 #endif
 }
References cursor_pos, cursor_type, custom, disabled, catacurses::getbegx(), catacurses::getbegy(), point, and math_opers::pos().
Member Data Documentation
cursor_pos
point ui_adaptor::cursor_pos private
Definition at line 247 of file ui_manager.h.
Referenced by record_cursor(), record_term_cursor(), redraw_invalidated(), and set_cursor().
cursor_type
cursor ui_adaptor::cursor_type = cursor::last private
Definition at line 246 of file ui_manager.h.
Referenced by default_cursor(), disable_cursor(), record_cursor(), record_term_cursor(), and set_cursor().
deferred_resize
bool ui_adaptor::deferred_resize mutable private
Definition at line 253 of file ui_manager.h.
Referenced by mark_resize().
dimensions
rectangle<point> ui_adaptor::dimensions private
Definition at line 235 of file ui_manager.h.
Referenced by invalidate(), invalidate_ui(), invalidation_consistency_and_optimization(), position(), position_absolute(), position_from_window(), and ~ui_adaptor().
disabling_uis_below
bool ui_adaptor::disabling_uis_below private
Definition at line 249 of file ui_manager.h.
Referenced by ~ui_adaptor().
invalidated
bool ui_adaptor::invalidated mutable private
Definition at line 252 of file ui_manager.h.
Referenced by invalidate(), invalidate_ui(), invalidation_consistency_and_optimization(), position(), position_absolute(), and position_from_window().
is_debug_message_ui
bool ui_adaptor::is_debug_message_ui private
Definition at line 250 of file ui_manager.h.
Referenced by ~ui_adaptor().
is_imgui
bool ui_adaptor::is_imgui
Definition at line 77 of file ui_manager.h.
is_on_top
bool ui_adaptor::is_on_top
Definition at line 78 of file ui_manager.h.
redraw_cb
redraw_callback_t ui_adaptor::redraw_cb private
Definition at line 236 of file ui_manager.h.
Referenced by on_redraw().
screen_resized_cb
screen_resize_callback_t ui_adaptor::screen_resized_cb private
Definition at line 237 of file ui_manager.h.
Referenced by on_screen_resize().
The documentation for this class was generated from the following files:
src/ui_manager.h
src/ui_manager.cpp