Cataclysm DDA: auto_pickup::base_settings Class Reference
auto_pickup::base_settings Class Reference abstract
#include <auto_pickup.h>
Public Member Functions
virtual ~base_settings ()=default
rule_state check_item (const std::string &sItemName) const
Protected Member Functions
void invalidate ()
Protected Attributes
cache map_items
Private Member Functions
virtual void refresh_map_items (cache &map_items) const =0
void recreate () const
Detailed Description
Definition at line 101 of file auto_pickup.h.
Constructor & Destructor Documentation
~base_settings()
virtual auto_pickup::base_settings::~base_settings () virtual default
Member Function Documentation
check_item()
rule_state base_settings::check_item (const std::string & sItemName) const
Definition at line 905 of file auto_pickup.cpp.
 {
     if( !map_items.ready ) {
         recreate();
     }
     const auto iter = map_items.find( sItemName );
     if( iter != map_items.end() ) {
         return iter->second;
     }
     return rule_state::NONE;
 }
References map_items, NONE, auto_pickup::cache::ready, and recreate().
Referenced by get_autopickup_rule(), and npc::item_name_whitelisted().
invalidate()
void base_settings::invalidate () protected
Definition at line 1057 of file auto_pickup.cpp.
 {
     map_items.ready = false;
 }
References map_items, and auto_pickup::cache::ready.
Referenced by auto_pickup::player_settings::clear_character_rules(), auto_pickup::player_settings::load(), auto_pickup::player_settings::remove_rule(), auto_pickup::player_settings::show(), and auto_pickup::npc_settings::show().
recreate()
void base_settings::recreate () const private
Definition at line 1048 of file auto_pickup.cpp.
 {
     map_items.clear();
     map_items.temp_items.clear();
     refresh_map_items( map_items );
     map_items.ready = true;
     map_items.temp_items.clear();
 }
References map_items, auto_pickup::cache::ready, refresh_map_items(), and auto_pickup::cache::temp_items.
Referenced by check_item().
refresh_map_items()
virtual void auto_pickup::base_settings::refresh_map_items (cache & map_items) const private pure virtual
Implemented in auto_pickup::npc_settings, and auto_pickup::player_settings.
Referenced by recreate().
Member Data Documentation
map_items
cache auto_pickup::base_settings::map_items mutable protected
Definition at line 104 of file auto_pickup.h.
Referenced by check_item(), auto_pickup::player_settings::create_rule(), auto_pickup::npc_settings::create_rule(), invalidate(), recreate(), auto_pickup::player_settings::refresh_map_items(), and auto_pickup::npc_settings::refresh_map_items().
The documentation for this class was generated from the following files:
src/auto_pickup.h
src/auto_pickup.cpp