Cataclysm DDA: JsonObject Class Reference
JsonObject Class Reference
#include <flexbuffer_json.h>
Classes
class const_iterator
Public Member Functions
JsonObject ()
JsonObject (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath &&path)
JsonObject (const JsonObject &rhs)
JsonObject & operator= (const JsonObject &rhs)
JsonObject (JsonObject &&rhs) noexcept
JsonObject & operator= (JsonObject &&rhs) noexcept
~JsonObject ()
size_t size () const
std::string get_string (const std::string &key) const
std::string get_string (const char *key) const
template<typename T , typename std::enable_if_t< std::is_convertible_v< T, std::string >> * = nullptr>
std::string get_string (const std::string &key, T &&fallback) const
template<typename T , typename std::enable_if_t< std::is_convertible_v< T, std::string >> * = nullptr>
std::string get_string (const char *key, T &&fallback) const
bool get_bool (std::string_view key) const
int get_int (std::string_view key) const
double get_float (std::string_view key) const
JsonArray get_array (std::string_view key) const
JsonObject get_object (std::string_view key) const
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value (const std::string &name) const
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value (const char *name) const
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value (const std::string &name, E fallback) const
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value (const char *name, E fallback) const
std::vector< int > get_int_array (std::string_view name) const
std::vector< std::string > get_string_array (std::string_view name) const
std::vector< std::string > get_as_string_array (const std::string &name) const
bool has_member (std::string_view key) const
bool has_null (std::string_view key) const
bool has_string (std::string_view key) const
bool has_bool (std::string_view key) const
bool has_number (std::string_view key) const
bool has_int (std::string_view key) const
bool has_float (std::string_view key) const
bool has_array (std::string_view key) const
bool has_object (std::string_view key) const
bool get_bool (std::string_view key, bool fallback) const
int get_int (std::string_view key, int fallback) const
double get_float (std::string_view key, double fallback) const
std::optional< JsonValue > get_member_opt (std::string_view key) const
JsonValue get_member (std::string_view key) const
JsonValue operator[] (std::string_view key) const
template<typename T >
bool read (std::string_view name, T &t, bool throw_on_error=true) const
template<typename T = std::string, typename Res = std::set<T>>
Res get_tags (std::string_view name) const
void throw_error (const std::string &err) const
void throw_error_at (std::string_view member, const std::string &err) const
void allow_omitted_members () const
void copy_visited_members (const JsonObject &rhs) const
const_iterator begin () const
const_iterator end () const
std::string str () const
Public Attributes
friend const_iterator
Static Protected Member Functions
static const auto & empty_object_ ()
Protected Attributes
flexbuffers::TypedVector keys_ = flexbuffers::TypedVector::EmptyTypedVector()
flexbuffers::Vector values_ = flexbuffers::Vector::EmptyVector()
tiny_bitset visited_fields_bitset_
Private Member Functions
void init (const flexbuffer &json, tiny_bitset *moved_visited_fields=nullptr)
JsonValue operator[] (size_t idx) const
flexbuffers::Reference find_value_ref (const std::string_view key) const
void mark_visited (size_t idx) const
void report_unvisited () const
void error_no_member (std::string_view member) const
void error_skipped_members (const std::vector< size_t > &skipped_members) const
Private Member Functions inherited from JsonWithPath
void throw_error (const std::string &message) const noexcept(false)
void throw_error (int offset, const std::string &message) const noexcept(false)
void throw_error_after (const std::string &message) const noexcept(false)
JsonWithPath (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath &&path)
JsonWithPath (const JsonWithPath &)=default
JsonWithPath & operator= (const JsonWithPath &)=default
JsonWithPath (JsonWithPath &&) noexcept=default
JsonWithPath & operator= (JsonWithPath &&) noexcept=default
bool error_or_false (bool throw_on_error, const std::string &message) const noexcept(false)
Static Private Member Functions
static bool find_map_key_idx (const std::string_view key, const flexbuffers::TypedVector &keys, size_t &idx)
Additional Inherited Members
Private Attributes inherited from JsonWithPath
JsonPath path_
Detailed Description
Definition at line 526 of file flexbuffer_json.h.
Constructor & Destructor Documentation
JsonObject() [1/4]
JsonObject::JsonObject () inline
Definition at line 540 of file flexbuffer_json.h.
                      : JsonWithPath( empty_object_(),
                                          flexbuffer_root_from_storage( empty_object_()->get_storage() ), {} ) {
             init( json_ );
         }
JsonObject() [2/4]
JsonObject::JsonObject (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath && path) inline
Definition at line 545 of file flexbuffer_json.h.
             : JsonWithPath( std::move( root ), json, std::move( path ) ) {
             init( json_ );
         }
References init, and Json::json_.
JsonObject() [3/4]
JsonObject::JsonObject (const JsonObject & rhs) inline
Definition at line 554 of file flexbuffer_json.h.
                                             : JsonWithPath( rhs ) {
             init( json_ );
         }
References init, and Json::json_.
JsonObject() [4/4]
JsonObject::JsonObject (JsonObject && rhs) inline noexcept
Definition at line 566 of file flexbuffer_json.h.
                                                 :
             JsonWithPath( std::move( static_cast<JsonWithPath &>( rhs ) ) )  {
             init( json_, &rhs.visited_fields_bitset_ );
             rhs.visited_fields_bitset_.set_all();
         }
References init, and Json::json_.
~JsonObject()
JsonObject::~JsonObject () inline
Definition at line 804 of file flexbuffer_json-inl.h.
 {
 #ifndef CATA_IN_TOOL
     if( std::uncaught_exceptions() == 0 && !visited_fields_bitset_.all() ) {
         report_unvisited();
     }
 #endif
 }
References tiny_bitset::all(), report_unvisited(), and visited_fields_bitset_.
Member Function Documentation
allow_omitted_members()
void JsonObject::allow_omitted_members () const inline
Definition at line 662 of file flexbuffer_json.h.
{
             visited_fields_bitset_.set_all();
         }
References tiny_bitset::set_all().
Referenced by assign(), details::assign_set(), panel_manager::deserialize(), zone_data::deserialize(), item::deserialize(), item_contents::deserialize(), activity_tracker::deserialize(), addiction::deserialize(), bionic::deserialize(), consumption_event::deserialize(), faction::deserialize(), mission::deserialize(), mongroup::deserialize(), player_morale::morale_point::deserialize(), npc_favor::deserialize(), event_multiset::deserialize(), stats_tracker::deserialize(), uistatedata::deserialize(), item::craft_data::deserialize(), translation::deserialize(), job_data::deserialize(), deserialize(), dynamic_line_t::dynamic_line_t(), dynamic_line_t::from_member(), get_dbl_or_var_part(), get_duration_or_var_part(), generic_factory< T >::handle_inheritance(), handle_proportional(), Character::load(), monster::load(), islot_armor::load(), mission_type::load(), mtype::load(), recipe_dictionary::load(), species_type::load(), profession::load(), Creature::load(), player_morale::load(), Item_factory::load(), Item_factory::load_basic_info(), load_charge_removal_blacklist(), Item_factory::load_definition(), load_eoc_vector_id_and_var(), load_ignored_type(), load_legacy_craft_data(), load_mapgen_function(), load_mod_tileset(), mod_manager::load_modfile(), load_nested_mapgen(), jmapgen_objects::load_objects(), load_temperature_removal_blacklist(), load_update_mapgen(), mapgen_function_json_base::mapgen_function_json_base(), generic_typed_reader< Derived >::operator()(), and mission_util::set_update_mapgen().
begin()
auto JsonObject::begin () const inline
Definition at line 99 of file flexbuffer_json-inl.h.
 {
     return const_iterator( *this, 0 );
 }
References const_iterator.
copy_visited_members()
void JsonObject::copy_visited_members (const JsonObject & rhs) const inline
Definition at line 666 of file flexbuffer_json.h.
{
             visited_fields_bitset_ = rhs.visited_fields_bitset_;
         }
References visited_fields_bitset_.
empty_object_()
static const auto& JsonObject::empty_object_ () inline static protected
Definition at line 533 of file flexbuffer_json.h.
{
             // NOLINTNEXTLINE(cata-almost-never-auto)
             static auto empty_object = flexbuffer_cache::parse_buffer( "{}" );
             return empty_object;
         }
References flexbuffer_cache::parse_buffer().
end()
auto JsonObject::end () const inline
Definition at line 104 of file flexbuffer_json-inl.h.
 {
     return const_iterator( *this, keys_.size() );
 }
References const_iterator, and keys_.
Referenced by report_unvisited().
error_no_member()
void JsonObject::error_no_member (std::string_view member) const private
Definition at line 297 of file flexbuffer_json.cpp.
 {
     std::unique_ptr<std::istream> original_json = root_->get_source_stream();
     std::string source_path = [&] {
         if( root_->get_source_path().empty() )
         {
             return std::string{ "<unknown source file>" };
         }
         return root_->get_source_path().u8string();
     }();
     TextJsonIn jsin( *original_json, source_path );
     advance_jsin( &jsin, flexbuffer_root_from_storage( root_->get_storage() ), path_ );
     TextJsonObject jo = jsin.get_object();
     jo.allow_omitted_members();
     jo.get_member( member );
     // Just to make sure the compiler understands we will error earlier.
     jo.throw_error( str_cat( "Failed to report missing member ", member ) );
 }
References advance_jsin(), TextJsonObject::allow_omitted_members(), flexbuffer_root_from_storage(), TextJsonObject::get_member(), TextJsonIn::get_object(), member, JsonWithPath::path_, Json::root_, str_cat(), and TextJsonObject::throw_error().
Referenced by get_member().
error_skipped_members()
void JsonObject::error_skipped_members (const std::vector< size_t > & skipped_members) const private
Definition at line 318 of file flexbuffer_json.cpp.
 {
     std::unique_ptr<std::istream> original_json = root_->get_source_stream();
     std::string source_path = [&] {
         if( root_->get_source_path().empty() )
         {
             return std::string{ "<unknown source file>" };
         }
         return root_->get_source_path().u8string();
     }();
     TextJsonIn jsin( *original_json, source_path );
     advance_jsin( &jsin, flexbuffer_root_from_storage( root_->get_storage() ), path_ );
     TextJsonObject jo = jsin.get_object();
     jo.allow_omitted_members();
     for( size_t skipped_member_idx : skipped_members ) {
         flexbuffers::String name = keys_[skipped_member_idx].AsString();
         try {
             if( strcmp( "//~", name.c_str() ) == 0 ) {
                 jo.throw_error_at(
                     name.c_str(),
                     "\"//~\" should be within a text object and contain comments for translators." );
             } else {
                 jo.throw_error_at( name.c_str(),
                                    string_format( "Invalid or misplaced field name \"%s\" in JSON data",
                                                   name.c_str() ) );
             }
         } catch( const JsonError &e ) {
             debugmsg( "(json-error)\n%s", e.what() );
         }
         mark_visited( skipped_member_idx );
     }
 }
References advance_jsin(), TextJsonObject::allow_omitted_members(), debugmsg, flexbuffer_root_from_storage(), TextJsonIn::get_object(), keys_, mark_visited(), om_direction::name(), JsonWithPath::path_, Json::root_, string_format(), and TextJsonObject::throw_error_at().
Referenced by report_unvisited().
find_map_key_idx()
static bool JsonObject::find_map_key_idx (const std::string_view key, const flexbuffers::TypedVector & keys, size_t & idx) inline static private
Definition at line 693 of file flexbuffer_json.h.
{
             // Handlrolled binary search because the STL does not provide a version that just uses indexes.
             std::make_signed_t<size_t>low = 0;
             std::make_signed_t<size_t>high = keys.size() - 1;
             while( low <= high ) {
                 std::make_signed_t<size_t> mid = ( high - low ) / 2 + low;
                 const std::string_view test_key = keys[ mid ].AsKey();
                 int res = string_view_cmp( test_key, key );
                 if( res == 0 ) {
                     idx = mid;
                     return true;
                 } else if( res < 0 ) {
                     low = mid + 1;
                 } else {
                     high = mid - 1;
                 }
             }
             return false;
         }
References irradiance::high, irradiance::low, and string_view_cmp().
Referenced by get_member(), get_member_opt(), get_string(), and has_member().
find_value_ref()
flexbuffers::Reference JsonObject::find_value_ref (const std::string_view key) const inline private
Definition at line 683 of file flexbuffer_json.h.
{
             size_t idx = 0;
             bool found = find_map_key_idx( key, keys_, idx );
             if( found ) {
                 return values_[ idx ];
             }
             return flexbuffers::Reference();
         }
Referenced by has_array(), has_bool(), has_null(), has_number(), has_object(), and has_string().
get_array()
JsonArray JsonObject::get_array (std::string_view key) const inline
Definition at line 855 of file flexbuffer_json-inl.h.
 {
     std::optional<JsonValue> member_opt = get_member_opt( key );
     if( member_opt.has_value() ) {
         return std::move( *member_opt );
     }
     return JsonArray{};
 }
References get_member_opt().
Referenced by add_array_to_set(), Item_factory::add_entry(), mutation_branch::add_entry(), mtype::add_regeneration_modifiers(), mtype::add_special_attacks(), apply_region_overlay(), assign(), assign_coverage_from_json(), conditional_t::conditional_t(), Item_factory::delete_qualities_from_json(), Item_factory::delete_techniques_from_json(), panel_manager::deserialize(), basecamp::deserialize(), known_magic::deserialize(), teleporter_list::deserialize(), bionic::deserialize(), armor_portion_data::deserialize(), mission::deserialize(), option_slider::option_slider_level::deserialize(), event_multiset::deserialize(), int_distribution::deserialize(), mm_region::deserialize(), diary::deserialize(), overmapbuffer::deserialize_overmap_global_state(), dynamic_line_t::dynamic_line_t(), Item_factory::extend_qualities_from_json(), Item_factory::extend_techniques_from_json(), effect_type::extract_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_debt(), conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string(), conditional_fun::anonymous_namespace{condition.cpp}::f_expects_vars(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_switch(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_trigger_event(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_weighted_list_eocs(), faction_template::faction_template(), eoc_math::from_json(), dynamic_line_t::from_member(), get_as_string_array(), get_dbl_or_var(), get_duration_or_var(), get_get_str_(), get_int_array(), get_string_array(), jmapgen_computer::jmapgen_computer(), jmapgen_field::jmapgen_field(), jmapgen_int::jmapgen_int(), jmapgen_monster::jmapgen_monster(), jmapgen_vehicle::jmapgen_vehicle(), json_talk_repeat_response::json_talk_repeat_response(), Character::load(), bonus_container::load(), json_talk_topic::load(), fault_fix::load(), json_item_substitution::load(), relic::load(), test_data::load(), VehicleGroup::load(), VehiclePlacement::load(), VehicleSpawn::load(), weakpoint::load(), eoc_examine_actor::load(), map_data_common_t::load(), generic_factory< T >::load(), ma_technique::load(), martialart::load(), mtype::load(), mutation_branch::load(), overmap_special::load(), recipe::load(), start_location::load(), vpart_info::load(), behavior::node_t::load(), bodygraph::load(), body_part_type::load(), character_modifier::load(), clothing_mod::load(), field_type::load(), species_type::load(), npc_class::load(), profession::load(), anonymous_namespace{recipe_groups.cpp}::recipe_group_data::load(), quality::load(), scenario::load(), trap::load(), vehicle_prototype::load(), weakpoints::load(), widget::load(), enchant_cache::load(), enchantment::load(), damage_type::load(), ter_furn_transform::load(), scen_blacklist::load(), relic_procgen_data::load(), map_bash_info::load(), material_type::load(), iuse_transform::load(), consume_drug_iuse::load(), place_monster_iuse::load(), change_scent_iuse::load(), reveal_map_actor::load(), repair_item_actor::load(), heal_actor::load(), sew_advanced_actor::load(), effect_on_conditons_actor::load(), bionic_data::load(), Item_factory::load(), effect_type::load_apply_msgs(), Item_factory::load_basic_info(), color_loader< ColorType >::load_colors(), load_construction(), load_damage_instance_inherit(), effect_type::load_decay_msgs(), load_distribution(), talk_effect_t::load_effect(), load_eoc_vector(), load_eoc_vector_id_and_var(), load_forest_mapgen_settings(), mission_util::load_funcs(), field_types::load_immunity(), leap_actor::load_internal(), melee_actor::load_internal(), gun_actor::load_internal(), Item_factory::load_item_group_data(), load_mapgen(), load_min_max(), load_mutation_attack(), jmapgen_objects::load_objects(), load_overlay_ordering_into_array(), load_overmap_feature_flag_settings(), load_overmap_lake_settings(), load_overmap_terrain_mapgens(), load_recipe_category(), load_region_overlay(), load_region_settings(), requirement_data::load_requirement(), load_season_array(), Skill::load_skill(), snippet_library::load_snippet(), load_str_arr(), Item_factory::load_string(), Item_factory::load_sub_ref(), mutation_branch::load_trait_blacklist(), mutation_branch::load_trait_group(), vitamin::load_vitamin(), load_world_option(), MonsterGroupManager::LoadMonsterGroup(), jmapgen_nested::neighbor_oter_check::neighbor_oter_check(), parse_vp_control_reqs(), parse_vp_reqs(), avatar::daily_calories::read_activity(), Item_factory::relative_qualities_from_json(), Item_factory::set_qualities_from_json(), Item_factory::set_techniques_from_json(), Item_factory::set_use_methods_from_json(), mapgen_function_json_base::setup_common(), mapgen_function_json_nested::setup_internal(), talk_trial::talk_trial(), json_item_substitution::trait_requirements::trait_requirements(), overmap::unserialize(), game::unserialize(), timed_event_manager::unserialize_all(), overmap::unserialize_omap(), and VehicleFacings::VehicleFacings().
get_as_string_array()
std::vector< std::string > JsonObject::get_as_string_array (const std::string & name) const inline
Definition at line 929 of file flexbuffer_json-inl.h.
 {
     std::vector<std::string> ret;
     if( has_array( name ) ) {
         JsonArray ja = get_array( name );
         ret.reserve( ja.size() );
         for( JsonValue jv : get_array( name ) ) {
             ret.emplace_back( jv );
         }
     } else {
         ret.emplace_back( get_string( name ) );
     }
     return ret;
 }
References get_array(), get_string(), has_array(), om_direction::name(), cata::hash64_detail::ret, and JsonArray::size().
Referenced by connect_group::load(), ter_t::load(), and furn_t::load().
get_bool() [1/2]
bool JsonObject::get_bool (std::string_view key) const inline
Definition at line 850 of file flexbuffer_json-inl.h.
 {
     return get_member( key );
 }
References get_member().
Referenced by Item_factory::add_entry(), auto_pickup::rule::deserialize(), bionic::deserialize(), item::craft_data::deserialize(), dynamic_line_t::dynamic_line_t(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_guard_pos(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_category(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_towards(), conditional_fun::anonymous_namespace{condition.cpp}::f_query(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), faction_template::faction_template(), get_get_str_(), get_str_translation_or_var(), item_search_data::item_search_data(), jmapgen_computer::jmapgen_computer(), jmapgen_trap::jmapgen_trap(), monster::load(), json_talk_topic::load(), ter_furn_data< T >::load(), widget_clause::load(), mtype::load(), recipe::load(), trap::load(), mutation_category_trait::load(), map_deconstruct_info::load(), map_bash_info::load(), firestarter_actor::load(), cast_spell_actor::load(), json_talk_response::load_condition(), load_construction(), load_effect_data(), load_explosion_data(), load_external_option(), leap_actor::load_internal(), gun_actor::load_internal(), Item_factory::load_item_blacklist(), Item_factory::load_item_group(), load_mapgen_function(), load_memory_card_data(), load_recipe_category(), faction_template::load_relations(), Skill::load_skill(), load_tech_effect_data(), mutation_branch::load_trait_migration(), MonsterGroupManager::LoadMonsterGroup(), and mission_util::parse_mission_om_target().
get_bool() [2/2]
bool JsonObject::get_bool (std::string_view key, bool fallback) const inline
Definition at line 1017 of file flexbuffer_json-inl.h.
 {
     std::optional<JsonValue> member_opt = get_member_opt( key );
     if( member_opt.has_value() ) {
         return *member_opt;
     }
     return fallback;
 }
References get_member_opt().
get_enum_value() [1/4]
template<typename E , typename > E JsonObject::get_enum_value (const char * name) const
Definition at line 879 of file flexbuffer_json-inl.h.
 {
     JsonValue value = get_member( name );
     try {
         return io::string_to_enum<E>( static_cast<std::string>( value ) );
     } catch( const io::InvalidEnumString & ) {
         value.throw_error( "invalid enumeration value" );
     }
 }
References get_member(), om_direction::name(), and JsonValue::throw_error().
get_enum_value() [2/4]
template<typename E , typename > E JsonObject::get_enum_value (const char * name, E fallback) const
Definition at line 895 of file flexbuffer_json-inl.h.
 {
     std::optional<JsonValue> value = get_member_opt( name );
     if( value.has_value() ) {
         try {
             return io::string_to_enum<E>( static_cast<std::string>( *value ) );
         } catch( const io::InvalidEnumString & ) {
             value->throw_error( "invalid enumeration value" );
         }
     } else {
         return fallback;
     }
 }
References get_member_opt(), and om_direction::name().
get_enum_value() [3/4]
template<typename E , typename > E JsonObject::get_enum_value (const std::string & name) const
Definition at line 874 of file flexbuffer_json-inl.h.
 {
     return get_enum_value<E>( name.c_str() );
 }
References om_direction::name().
Referenced by Item_factory::add_entry(), computer_option::deserialize(), computer_failure::deserialize(), computer_option::from_json(), computer_failure::from_json(), mission_type::load(), start_location::load(), field_type::load(), map_extra::load(), anonymous_namespace{recipe_groups.cpp}::recipe_group_data::load(), reveal_map_actor::load(), Item_factory::load_basic_info(), vitamin::load_vitamin(), jmapgen_nested::neighbor_oter_check::neighbor_oter_check(), mission_util::parse_mission_om_target(), and jmapgen_nested::predecessor_oter_check::predecessor_oter_check().
get_enum_value() [4/4]
template<typename E , typename > E JsonObject::get_enum_value (const std::string & name, E fallback) const
Definition at line 890 of file flexbuffer_json-inl.h.
 {
     return get_enum_value<E>( name.c_str(), fallback );
 }
References om_direction::name().
get_float() [1/2]
double JsonObject::get_float (std::string_view key) const inline
Definition at line 845 of file flexbuffer_json-inl.h.
 {
     return get_member( key );
 }
References get_member().
Referenced by abstract_read_var_info(), bionic::deserialize(), int_distribution::deserialize(), effect_scaling::effect_scaling(), get_proportional(), get_relative(), json_item_substitution::substitution::info::info(), islot_armor::load(), weakpoint_effect::load(), weakpoint_difficulty::load(), weather_generator::load(), mtype::load(), furn_t::load(), proficiency::load(), trap::load(), map_deconstruct_info::load(), repair_item_actor::load(), heal_actor::load(), Item_factory::load(), load_damage_unit(), load_distribution(), load_explosion_data(), load_external_option(), leap_actor::load_internal(), load_memory_card_data(), load_shrapnel_data(), and Item_factory::set_use_methods_from_json().
get_float() [2/2]
double JsonObject::get_float (std::string_view key, double fallback) const inline
Definition at line 1008 of file flexbuffer_json-inl.h.
 {
     std::optional<JsonValue> member_opt = get_member_opt( key );
     if( member_opt.has_value() ) {
         return *member_opt;
     }
     return fallback;
 }
References get_member_opt().
get_int() [1/2]
int JsonObject::get_int (std::string_view key) const inline
Definition at line 840 of file flexbuffer_json-inl.h.
 {
     return get_member( key );
 }
References get_member().
Referenced by Item_factory::add_entry(), mutation_branch::add_entry(), addiction::deserialize(), bionic::deserialize(), computer_option::deserialize(), effect::deserialize(), mission::deserialize(), player_morale::morale_point::deserialize(), npc_favor::deserialize(), item_demographic_test_data::deserialize(), uistatedata::deserialize(), blueprint_options::deserialize(), item::extended_photo_def::deserialize(), item::craft_data::deserialize(), item_location::deserialize(), anonymous_namespace{messages.cpp}::game_message::deserialize(), mm_region::deserialize(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_category(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), computer_option::from_json(), ma_skill_reader::get_next(), ma_weapon_damage_reader::get_next(), skilllevel_reader::get_next(), addiction_reader::get_next(), item_search_data::item_search_data(), jmapgen_computer::jmapgen_computer(), jmapgen_field::jmapgen_field(), jmapgen_int::jmapgen_int(), jmapgen_vehicle::jmapgen_vehicle(), Character::load(), monster::load(), relic::load(), weakpoint_effect::load(), weather_generator::load(), mission_type::load(), mtype::load(), damage_info_order::damage_info_order_entry::load(), trap::load(), vehicle_prototype::load(), dream::load(), npc_template::load(), map_deconstruct_info::load(), map_bash_info::load(), damage_over_time_data::load(), delayed_transform_iuse::load(), reveal_map_actor::load(), firestarter_actor::load(), fireweapon_off_actor::load(), fireweapon_on_actor::load(), manualnoise_actor::load(), musical_instrument_actor::load(), cast_spell_actor::load(), repair_item_actor::load(), heal_actor::load(), quality_requirement::load(), Item_factory::load(), load_construction(), load_effect_data(), load_explosion_data(), load_external_option(), leap_actor::load_internal(), Item_factory::load_item_group(), load_memory_card_data(), load_nested_mapgen(), load_shrapnel_data(), Skill::load_skill(), load_speech(), load_tech_effect_data(), avatar::load_template(), vitamin::load_vitamin(), MonsterGroupManager::LoadMonsterGroup(), mission_util::parse_mission_om_target(), parse_vp_reqs(), talk_trial::talk_trial(), game::unserialize(), and VehicleFacings::VehicleFacings().
get_int() [2/2]
int JsonObject::get_int (std::string_view key, int fallback) const inline
Definition at line 999 of file flexbuffer_json-inl.h.
 {
     std::optional<JsonValue> member_opt = get_member_opt( key );
     if( member_opt.has_value() ) {
         return *member_opt;
     }
     return fallback;
 }
References get_member_opt().
get_int_array()
std::vector< int > JsonObject::get_int_array (std::string_view name) const inline
Definition at line 909 of file flexbuffer_json-inl.h.
 {
     std::vector<int> ret;
     JsonArray ja = get_array( name );
     ret.reserve( ja.size() );
     for( JsonValue jv : get_array( name ) ) {
         ret.emplace_back( jv );
     }
     return ret;
 }
References get_array(), om_direction::name(), cata::hash64_detail::ret, and JsonArray::size().
Referenced by faction::deserialize(), activity_byproduct::load(), and shearing_entry::load().
get_member()
JsonValue JsonObject::get_member (std::string_view key) const inline
Definition at line 1038 of file flexbuffer_json-inl.h.
 {
     // Manually bsearch for the key idx to store in visited_fields_bitset_.
     // flexbuffers::Map::operator[] will probably be faster but won't give us the idx,
     // which we need to track visited fields.
     size_t idx = 0;
     bool found = find_map_key_idx( key, keys_, idx );
     if( found ) {
         mark_visited( idx );
         return JsonValue{ root_, values_[ idx ], &path_, idx };
     }
     error_no_member( key );
     return ( *this )[key];
 }
References error_no_member(), find_map_key_idx(), keys_, mark_visited(), JsonWithPath::path_, Json::root_, and values_.
Referenced by abstract_read_var_info(), deserialize(), mapgen_parameter::deserialize(), migration::content::deserialize(), translation::deserialize(), mapgen_value< Id >::distribution_source::distribution_source(), generic_typed_reader< Derived >::erase_values_from(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_bionic(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_alter_timed_events(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_activity(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_mission(), conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack(), conditional_fun::anonymous_namespace{condition.cpp}::f_bodytype(), conditional_fun::anonymous_namespace{condition.cpp}::f_can_see_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_clear_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_companion_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_deactivate_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_martial_art(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_recipe(), conditional_fun::anonymous_namespace{condition.cpp}::f_get_condition(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_achievment(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_bionics(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_category(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_items(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_martial_art(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_move_mode(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_proficiency(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_species(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_trait(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_visible_trait(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_wielded_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_wielded_with_weapon_category(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_worn_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_in_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_season(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_wearing(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_weather(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_martial_art(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_recipe(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_bionic(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_in_city(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_id(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), conditional_fun::anonymous_namespace{condition.cpp}::f_mission_goal(), conditional_fun::anonymous_namespace{condition.cpp}::f_mod_is_loaded(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_category(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_towards(), conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_aim_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_aim_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_recharge_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_cbm_recharge_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_reserve_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_cbm_reserve_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_class(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_faction(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_engagement_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_engagement_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_first_topic(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_has_class(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_override(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_role_nearby(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), conditional_fun::anonymous_namespace{condition.cpp}::f_query(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_active_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_item_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_until(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_condition(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), conditional_fun::anonymous_namespace{condition.cpp}::f_test_eoc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_toggle_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_line(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_mission(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_know_recipe(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_monsters_in_direction(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_profession(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_safe_mode_trigger(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_unset_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_using_martial_art(), faction_template::faction_template(), get_bool(), get_dbl_or_var(), get_duration_or_var(), get_enum_value(), get_float(), get_get_str_(), get_get_translation_(), get_int(), get_string(), generic_typed_reader< Derived >::insert_values_from(), jmapgen_item_group::jmapgen_item_group(), jmapgen_make_rubble::jmapgen_make_rubble(), jmapgen_monster::jmapgen_monster(), jmapgen_nested::jmapgen_nested(), jmapgen_trap::jmapgen_trap(), jmapgen_vending_machine::jmapgen_vending_machine(), Character::load(), json_item_substitution::load(), mtype::load(), overmap_special::load(), recipe::load(), vpart_info::load(), npc_class::load(), profession::load(), scenario::load(), mutation_category_trait::load(), map_deconstruct_info::load(), map_bash_info::load(), damage_over_time_data::load(), delayed_transform_iuse::load(), reveal_map_actor::load(), fireweapon_on_actor::load(), manualnoise_actor::load(), Item_factory::load(), load_construction(), talk_effect_t::load_effect(), load_effect_data(), emit::load_emit(), load_eoc_vector(), load_eoc_vector_id_and_var(), load_external_option(), Item_factory::load_item_group(), load_transform_results(), vitamin::load_vitamin(), mass_reader::operator()(), money_reader::operator()(), volume_reader::operator()(), operator[](), mission_util::parse_mission_om_target(), generic_typed_reader< Derived >::read_normal(), and read_with_factor().
get_member_opt()
std::optional< JsonValue > JsonObject::get_member_opt (std::string_view key) const inline
Definition at line 1027 of file flexbuffer_json-inl.h.
 {
     size_t idx = 0;
     bool found = find_map_key_idx( key, keys_, idx );
     if( found ) {
         mark_visited( idx );
         return JsonValue{ root_, values_[ idx ], &path_, idx };
     }
     return std::nullopt;
 }
References find_map_key_idx(), keys_, mark_visited(), JsonWithPath::path_, Json::root_, and values_.
Referenced by translation::deserialize(), get_array(), get_bool(), get_enum_value(), get_float(), get_int(), get_object(), get_tags(), vpart_info::load(), read(), and throw_error_at().
get_object()
JsonObject JsonObject::get_object (std::string_view key) const inline
Definition at line 864 of file flexbuffer_json-inl.h.
 {
     std::optional<JsonValue> member_opt = get_member_opt( key );
     if( member_opt.has_value() ) {
         return std::move( *member_opt );
     }
     return JsonObject{};
 }
References get_member_opt().
Referenced by Item_factory::add_entry(), snippet_library::add_snippets_from_json(), apply_region_overlay(), assign(), details::assign_set(), conditional_t::conditional_t(), item_demographic_test_data::deserialize(), uistatedata::deserialize(), Messages::deserialize(), generic_typed_reader< Derived >::do_relative(), dynamic_line_t::dynamic_line_t(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_guard_pos(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_items(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_id(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_talker(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_switch(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_line(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), conditional_fun::anonymous_namespace{condition.cpp}::f_x_in_y_chance(), dynamic_line_t::from_member(), handle_proportional(), handle_relative(), jmapgen_monster::jmapgen_monster(), jmapgen_sealed_item::jmapgen_sealed_item(), json_talk_repeat_response::json_talk_repeat_response(), json_talk_topic::load(), islot_armor::load(), json_item_substitution::load(), relic_charge_template::load(), test_data::load(), weakpoint::load(), map_data_common_t::load(), mission_type::load(), mtype::load(), mutation_branch::load(), recipe::load(), start_location::load(), vpart_info::load(), ter_t::load(), furn_t::load(), damage_info_order::damage_info_order_entry::load(), ammo_effect::load(), bodygraph::load(), body_part_type::load(), character_modifier::load(), field_type::load(), anonymous_namespace{gates.cpp}::gate_data::load(), spell_type::load(), map_extra::load(), species_type::load(), npc_class::load(), profession::load(), anonymous_namespace{recipe_groups.cpp}::recipe_group_data::load(), trap::load(), vehicle_prototype::load(), weather_type::load(), widget::load(), enchantment::load(), butchery_requirements::load(), damage_type::load(), reflex_activation_data::load(), npc_template::load(), furn_workbench_info::load(), plant_data::load(), mut_transform::load(), mut_personality_score::load(), map_deconstruct_info::load(), map_shoot_info::load(), map_bash_info::load(), material_type::load(), explosion_iuse::load(), reveal_map_actor::load(), heal_actor::load(), place_trap_actor::load(), bionic_data::load(), Item_factory::load(), Item_factory::load_basic_info(), load_construction(), load_distribution(), talk_effect_t::load_effect(), load_eoc_vector_id_and_var(), load_explosion_data(), load_forest_biome(), load_forest_biome_component(), load_forest_biome_terrain_dependent_furniture(), load_forest_mapgen_settings(), load_forest_trail_settings(), mission_util::load_funcs(), mapgen_palette::load_internal(), melee_actor::load_internal(), Item_factory::load_item_group(), Item_factory::load_item_group_data(), load_mapgen_function(), effect_type::load_mod_data(), load_monster_adjustment(), load_mutation_attack(), load_nested_mapgen(), overmap::load_oter_id_migration(), load_overmap_connection_settings(), load_overmap_feature_flag_settings(), load_overmap_forest_settings(), load_overmap_lake_settings(), load_overmap_ocean_settings(), load_overmap_ravine_settings(), mapgen_palette::load_place_mapings(), load_place_mapings_alternatively(), load_region_settings(), load_region_terrain_and_furniture_settings(), faction_template::load_relations(), requirement_data::load_requirement(), Skill::load_skill(), Item_factory::load_slot_optional(), avatar::load_template(), mutation_branch::load_trait_group(), load_update_mapgen(), MonsterGroupManager::LoadMonsterGroup(), jmapgen_nested::neighbor_oter_check::neighbor_oter_check(), generic_typed_reader< Derived >::operator()(), mission_util::parse_mission_om_target(), jmapgen_nested::predecessor_oter_check::predecessor_oter_check(), avatar::daily_calories::read_activity(), read_condition(), Item_factory::set_use_methods_from_json(), talk_effect_t::talk_effect_t(), and talk_response::talk_response().
get_string() [1/4]
std::string JsonObject::get_string (const char * key) const inline
Definition at line 817 of file flexbuffer_json-inl.h.
 {
     return get_member( key );
 }
References get_member().
get_string() [2/4]
template<typename T , typename std::enable_if_t< std::is_convertible_v< T, std::string >> * > std::string JsonObject::get_string (const char * key, T && fallback) const
Definition at line 829 of file flexbuffer_json-inl.h.
 {
     size_t idx = 0;
     bool found = find_map_key_idx( key, keys_, idx );
     if( found ) {
         return get_string( key );
     }
     return std::forward<T>( fallback );
 }
References find_map_key_idx(), get_string(), and keys_.
get_string() [3/4]
std::string JsonObject::get_string (const std::string & key) const inline
Definition at line 813 of file flexbuffer_json-inl.h.
 {
     return get_string( key.c_str() );
 }
Referenced by abstract_read_var_info(), Item_factory::add_entry(), mutation_branch::add_entry(), add_mapgen_update_func(), assign(), assign_coverage_from_json(), assign_function(), conditional_t::conditional_t(), MonsterGenerator::create_actor(), panel_manager::deserialize(), auto_pickup::rule::deserialize(), bionic::deserialize(), computer_option::deserialize(), damage_over_time_data::deserialize(), mission::deserialize(), npc_favor::deserialize(), blueprint_options::deserialize(), translation::deserialize(), item::extended_photo_def::deserialize(), item::craft_data::deserialize(), item_location::deserialize(), anonymous_namespace{messages.cpp}::game_message::deserialize(), effect_scaling::effect_scaling(), ma_weapon_damage_reader::erase_next(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_trigger_event(), faction_template::faction_template(), get_as_string_array(), get_get_str_(), get_get_translation_(), ma_skill_reader::get_next(), ma_weapon_damage_reader::get_next(), ma_buff_reader::get_next(), text_style_check_reader::get_next(), skilllevel_reader::get_next(), addiction_reader::get_next(), get_string(), get_talk_var_basename(), get_talk_varname(), generic_factory< T >::handle_inheritance(), iexamine_actor_from_jsobj(), item_search_data::item_search_data(), jmapgen_item_group::jmapgen_item_group(), jmapgen_loot::jmapgen_loot(), jmapgen_spawn_item::jmapgen_spawn_item(), jmapgen_variable::jmapgen_variable(), jmapgen_vehicle::jmapgen_vehicle(), jmapgen_zone::jmapgen_zone(), json_dynamic_line_effect::json_dynamic_line_effect(), json_talk_repeat_response::json_talk_repeat_response(), achievement::load(), activity_type::load(), json_talk_topic::load(), itype_variant_data::load(), connect_group::load(), json_item_substitution::load(), VehicleGroup::load(), VehiclePlacement::load(), VehicleSpawn::load(), vpart_variant::load(), map_data_common_t::load(), generic_factory< T >::load(), mattack_actor::load(), mission_type::load(), mtype::load(), oter_type_t::load(), overmap_special::load(), recipe::load(), start_location::load(), vpart_info::load(), recipe_dictionary::load(), behavior::node_t::load(), bodygraph::load(), field_type::load(), spell_type::load(), map_extra::load(), species_type::load(), move_mode::load(), npc_class::load(), profession::load(), anonymous_namespace{recipe_groups.cpp}::recipe_group_data::load(), scenario::load(), trap::load(), vehicle_prototype::load(), widget::load(), enchantment::load(), profession_blacklist::load(), scen_blacklist::load(), mutation_category_trait::load(), SkillDisplayType::load(), map_deconstruct_info::load(), map_bash_info::load(), explosion_iuse::load(), consume_drug_iuse::load(), place_monster_iuse::load(), change_scent_iuse::load(), place_npc_iuse::load(), deploy_furn_actor::load(), reveal_map_actor::load(), manualnoise_actor::load(), cast_spell_actor::load(), ammobelt_actor::load(), repair_item_actor::load(), sew_advanced_actor::load(), quality_requirement::load(), Item_factory::load(), ammunition_type::load_ammunition_type(), effect_type::load_apply_msgs(), Item_factory::load_basic_info(), bionic_data::load_bionic_migration(), load_construction(), load_damage_unit(), talk_effect_t::load_effect(), load_effect_data(), emit::load_emit(), load_external_option(), load_float_or_maxmovecost(), mission_util::load_funcs(), load_inline_topic(), mapgen_palette::load_internal(), item_action_generator::load_item_action(), Item_factory::load_item_group(), item_group::load_item_group(), Item_factory::load_item_group_data(), worldfactory::load_last_world_info(), load_mapgen(), load_mapgen_function(), load_memory_card_data(), global_variables::load_migrations(), mod_manager::load_modfile(), load_monster_adjustment(), load_mutation_attack(), load_mutation_type(), load_nested_mapgen(), DynamicDataLoader::load_object(), load_recipe_category(), requirement_data::load_requirement(), load_season_array(), load_shrapnel_data(), Skill::load_skill(), snippet_library::load_snippet(), Item_factory::load_sub_ref(), map_data_common_t::load_symbol(), load_talk_topic(), load_tech_effect_data(), mutation_branch::load_trait_group(), trait_group::load_trait_group(), load_transform_results(), load_update_mapgen(), vitamin::load_vitamin(), MonsterGroupManager::LoadMonsterGroup(), MonsterGroupManager::LoadMonsterWhitelist(), jmapgen_nested::neighbor_oter_check::neighbor_oter_check(), parse_vp_reqs(), jmapgen_nested::predecessor_oter_check::predecessor_oter_check(), read_condition(), mission_util::set_update_mapgen(), Item_factory::set_use_methods_from_json(), mapgen_function_json::setup_internal(), talk_effect_t::talk_effect_t(), talk_response::talk_response(), talk_trial::talk_trial(), Item_factory::usage_from_object(), and VehicleFunction_json::VehicleFunction_json().
get_string() [4/4]
template<typename T , typename std::enable_if_t< std::is_convertible_v< T, std::string >> * > std::string JsonObject::get_string (const std::string & key, T && fallback) const
Definition at line 823 of file flexbuffer_json-inl.h.
 {
     return get_string( key.c_str(), std::forward<T>( fallback ) );
 }
References get_string().
get_string_array()
std::vector< std::string > JsonObject::get_string_array (std::string_view name) const inline
Definition at line 919 of file flexbuffer_json-inl.h.
 {
     std::vector<std::string> ret;
     JsonArray ja = get_array( name );
     ret.reserve( ja.size() );
     for( JsonValue jv : get_array( name ) ) {
         ret.emplace_back( jv );
     }
     return ret;
 }
References get_array(), om_direction::name(), cata::hash64_detail::ret, and JsonArray::size().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), item_search_data::item_search_data(), jmapgen_computer::jmapgen_computer(), jmapgen_remove_vehicles::jmapgen_remove_vehicles(), islot_brewable::load(), islot_compostable::load(), weather_generator::load(), mtype::load(), ter_t::load(), furn_t::load(), spell_type::load(), learn_spell_actor::load(), Item_factory::load_basic_info(), load_memory_card_data(), load_mod_tileset(), load_overmap_lake_settings(), and load_talk_topic().
get_tags()
template<typename T , typename Res > Res JsonObject::get_tags (std::string_view name) const
Definition at line 1069 of file flexbuffer_json-inl.h.
 {
     Res res;
     std::optional<JsonValue> member_opt = get_member_opt( name );
     if( !member_opt.has_value() ) {
         return res;
     }
     JsonValue &member = *member_opt;
     // allow single string as tag
     if( member.test_string() ) {
         res.insert( T{ static_cast<std::string>( member ) } );
         return res;
     }
     // otherwise assume it's an array and error if it isn't.
     for( const std::string line : static_cast<JsonArray>( member ) ) {
         res.insert( T( line ) );
     }
     return res;
 }
References get_member_opt(), line, member, and om_direction::name().
Referenced by details::assign_set(), armor_portion_data::deserialize(), mission_type::load(), mtype::load(), recipe::load(), Item_factory::load(), Item_factory::load_basic_info(), load_construction(), Skill::load_skill(), load_speech(), jmapgen_nested::neighbor_join_check::neighbor_join_check(), mtype::remove_regeneration_modifiers(), and mtype::remove_special_attacks().
has_array()
bool JsonObject::has_array (std::string_view key) const inline
Definition at line 984 of file flexbuffer_json-inl.h.
 {
     flexbuffers::Reference ref = find_value_ref( key );
     return ref.IsAnyVector() && !ref.IsMap();
 }
References find_value_ref().
Referenced by Item_factory::add_entry(), mtype::add_regeneration_modifiers(), mtype::add_special_attacks(), apply_region_overlay(), assign(), assign_coverage_from_json(), details::assign_set(), anonymous_namespace{condition.cpp}::condition_parser::check(), sub_effect_parser::check(), conditional_t::conditional_t(), item::deserialize(), bionic::deserialize(), faction::deserialize(), armor_portion_data::deserialize(), dynamic_line_t::dynamic_line_t(), effect_type::extract_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_expects_vars(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_if(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), dynamic_line_t::from_member(), get_as_string_array(), get_dbl_or_var(), get_dbl_or_var_part(), get_duration_or_var(), get_duration_or_var_part(), get_get_str_(), get_talk_var_basename(), get_talk_varname(), jmapgen_computer::jmapgen_computer(), jmapgen_field::jmapgen_field(), jmapgen_int::jmapgen_int(), jmapgen_monster::jmapgen_monster(), jmapgen_npc::jmapgen_npc(), jmapgen_vehicle::jmapgen_vehicle(), json_talk_repeat_response::json_talk_repeat_response(), json_talk_topic::load(), fault_fix::load(), islot_brewable::load(), islot_compostable::load(), connect_group::load(), activity_byproduct::load(), relic::load(), shearing_entry::load(), speed_description_value::load(), test_data::load(), weakpoint_effect::load(), weakpoint::load(), map_data_common_t::load(), generic_factory< T >::load(), mtype::load(), mutation_branch::load(), oter_type_t::load(), overmap_special::load(), recipe::load(), start_location::load(), vpart_info::load(), behavior::node_t::load(), bodygraph::load(), body_part_type::load(), character_modifier::load(), spell_type::load(), npc_class::load(), profession::load(), trap::load(), vehicle_prototype::load(), widget::load(), enchant_cache::load(), enchantment::load(), damage_type::load(), map_bash_info::load(), material_type::load(), iuse_transform::load(), consume_drug_iuse::load(), place_monster_iuse::load(), change_scent_iuse::load(), inscribe_actor::load(), heal_actor::load(), bionic_data::load(), Item_factory::load(), effect_type::load_apply_msgs(), Item_factory::load_basic_info(), load_construction(), load_damage_instance_inherit(), load_damage_unit_inherit(), effect_type::load_decay_msgs(), load_distribution(), talk_effect_t::load_effect(), load_eoc_vector(), load_eoc_vector_id_and_var(), load_forest_mapgen_settings(), Creature::load_hit_range(), mapgen_palette::load_internal(), leap_actor::load_internal(), melee_actor::load_internal(), gun_actor::load_internal(), load_mapgen(), load_memory_card_data(), Item_factory::load_migration(), load_min_max(), load_mutation_attack(), load_overmap_feature_flag_settings(), load_overmap_lake_settings(), load_overmap_terrain_mapgens(), load_region_overlay(), load_region_settings(), load_season_array(), snippet_library::load_snippet(), load_str_arr(), Item_factory::load_string(), Item_factory::load_sub_ref(), load_talk_topic(), MonsterGroupManager::LoadMonsterGroup(), parse_vp_reqs(), avatar::daily_calories::read_activity(), Item_factory::set_qualities_from_json(), Item_factory::set_techniques_from_json(), Item_factory::set_use_methods_from_json(), mapgen_function_json_base::setup_common(), mapgen_function_json_nested::setup_internal(), and VehicleFacings::VehicleFacings().
has_bool()
bool JsonObject::has_bool (std::string_view key) const inline
Definition at line 978 of file flexbuffer_json-inl.h.
 {
     flexbuffers::Reference ref = find_value_ref( key );
     return ref.IsBool();
 }
References find_value_ref().
Referenced by bionic::deserialize(), dynamic_line_t::dynamic_line_t(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), json_talk_repeat_response::json_talk_repeat_response(), json_talk_topic::load(), weakpoint_effect::load(), widget_clause::load(), mtype::load(), recipe::load(), and mutation_branch::load_trait_migration().
has_float()
bool JsonObject::has_float (std::string_view key) const inline
Definition at line 961 of file flexbuffer_json-inl.h.
 {
     return has_number( key );
 }
References has_number().
Referenced by abstract_read_var_info(), bionic::deserialize(), islot_armor::load(), weakpoint_effect::load(), weakpoint_difficulty::load(), mtype::load(), furn_t::load(), proficiency::load(), load_damage_unit_inherit(), load_distribution(), and load_float_or_maxmovecost().
has_int()
bool JsonObject::has_int (std::string_view key) const inline
Definition at line 956 of file flexbuffer_json-inl.h.
 {
     return has_number( key );
 }
References has_number().
Referenced by addiction::deserialize(), bionic::deserialize(), effect::deserialize(), faction::deserialize(), mission::deserialize(), npc_favor::deserialize(), blueprint_options::deserialize(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_category(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), item_search_data::item_search_data(), jmapgen_item_group::jmapgen_item_group(), activity_byproduct::load(), mon_effect_data::load(), shearing_entry::load(), weakpoint_effect::load(), mtype::load(), recipe::load(), damage_info_order::damage_info_order_entry::load(), Item_factory::load(), Item_factory::load_basic_info(), load_explosion_data(), Skill::load_skill(), parse_vp_reqs(), and Item_factory::set_use_methods_from_json().
has_member()
bool JsonObject::has_member (std::string_view key) const inline
Definition at line 944 of file flexbuffer_json-inl.h.
 {
     size_t idx;
     return find_map_key_idx( key, keys_, idx );
 }
References find_map_key_idx(), and keys_.
Referenced by icg_entry_reader::_part_get_next(), abstract_read_var_info(), Item_factory::add_entry(), mutation_branch::add_entry(), add_if_exists(), snippet_library::add_snippet_from_json(), assign(), details::assign_set(), anonymous_namespace{condition.cpp}::condition_parser::check(), sub_effect_parser::check(), conditional_t::conditional_t(), deserialize(), avatar::daily_calories::deserialize(), zone_data::deserialize(), activity_tracker::deserialize(), bionic::deserialize(), armor_portion_data::deserialize(), shopkeeper_item_group::deserialize(), mutable_overmap_terrain::deserialize(), mutable_overmap_placement_rule::deserialize(), container_spawn_test_data::deserialize(), item_demographic_test_data::deserialize(), translation::deserialize(), Messages::deserialize(), item_location::deserialize(), int_distribution::deserialize(), dynamic_line_t::dynamic_line_t(), generic_typed_reader< Derived >::erase_values_from(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_items(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_if(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_towards(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), dynamic_line_t::from_member(), get_dbl_or_var(), get_duration_or_var(), text_style_check_reader::get_next(), get_optional(), get_proportional(), get_relative(), get_str_or_var(), get_translation_or_var(), handle_proportional(), mapgen_value< Id >::init_object(), generic_typed_reader< Derived >::insert_values_from(), jmapgen_gaspump::jmapgen_gaspump(), jmapgen_int::jmapgen_int(), jmapgen_make_rubble::jmapgen_make_rubble(), jmapgen_monster::jmapgen_monster(), jmapgen_nested::jmapgen_nested(), jmapgen_trap::jmapgen_trap(), jmapgen_vending_machine::jmapgen_vending_machine(), Character::load(), json_talk_topic::load(), event_source::load(), pocket_data::load(), json_item_substitution::load(), relic::load(), widget_clause::load(), generic_factory< T >::load(), ma_technique::load(), mission_type::load(), mtype::load(), oter_type_t::load(), overmap_special::load(), recipe::load(), vpart_info::load(), ter_t::load(), furn_t::load(), ammo_effect::load(), body_part_type::load(), character_modifier::load(), effect_on_condition::load(), field_type::load(), anonymous_namespace{gates.cpp}::gate_data::load(), harvest_drop_type::load(), spell_type::load(), map_extra::load(), species_type::load(), npc_class::load(), profession::load(), scenario::load(), vehicle_prototype::load(), weather_type::load(), enchantment::load(), ter_furn_transform::load(), map_bash_info::load(), iuse_transform::load(), explosion_iuse::load(), Item_factory::load(), Item_factory::load_basic_info(), json_talk_response::load_condition(), load_construction(), load_distribution(), talk_effect_t::load_effect(), load_eoc_vector(), load_eoc_vector_id_and_var(), load_external_option(), mission_util::load_funcs(), mapgen_palette::load_internal(), leap_actor::load_internal(), mon_spellcasting_actor::load_internal(), melee_actor::load_internal(), gun_actor::load_internal(), Item_factory::load_item_group(), Item_factory::load_item_group_data(), load_legacy_craft_data(), load_memory_card_data(), load_monster_adjustment(), jmapgen_objects::load_objects(), requirement_data::load_requirement(), load_season_array(), Item_factory::load_slot_optional(), Item_factory::load_string(), Item_factory::load_sub_ref(), map_data_common_t::load_symbol(), mutation_branch::load_trait_group(), mandatory(), generic_typed_reader< Derived >::operator()(), mass_reader::operator()(), money_reader::operator()(), volume_reader::operator()(), mission_util::parse_mission_om_target(), io::detail::has_archive_tag< T, typename enable_if_type< typename T::archive_type_tag >::type >::read(), read_condition(), generic_typed_reader< Derived >::read_normal(), mission_util::set_update_mapgen(), Item_factory::set_use_methods_from_json(), mapgen_function_json::setup_internal(), mapgen_function_json_nested::setup_internal(), talk_response::talk_response(), talk_trial::talk_trial(), overmap::unserialize(), and weather_manager::unserialize_all().
has_null()
bool JsonObject::has_null (std::string_view key) const inline
Definition at line 950 of file flexbuffer_json-inl.h.
 {
     flexbuffers::Reference ref = find_value_ref( key );
     return ref.IsNull();
 }
References find_value_ref().
Referenced by assign(), and game::unserialize().
has_number()
bool JsonObject::has_number (std::string_view key) const inline
Definition at line 966 of file flexbuffer_json-inl.h.
 {
     flexbuffers::Reference ref = find_value_ref( key );
     return ref.IsNumeric();
 }
References find_value_ref().
Referenced by has_float(), has_int(), recipe_proficiency::load(), oter_type_t::load(), and widget::load().
has_object()
bool JsonObject::has_object (std::string_view key) const inline
Definition at line 990 of file flexbuffer_json-inl.h.
 {
     flexbuffers::Reference ref = find_value_ref( key );
     return ref.IsMap();
 }
References find_value_ref().
Referenced by Item_factory::add_entry(), assign(), anonymous_namespace{condition.cpp}::condition_parser::check(), sub_effect_parser::check(), conditional_t::conditional_t(), generic_typed_reader< Derived >::do_relative(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), dynamic_line_t::from_member(), handle_proportional(), handle_relative(), jmapgen_monster::jmapgen_monster(), jmapgen_sealed_item::jmapgen_sealed_item(), json_talk_repeat_response::json_talk_repeat_response(), json_talk_topic::load(), test_data::load(), weakpoint::load(), map_data_common_t::load(), mtype::load(), mutation_branch::load(), recipe::load(), start_location::load(), ter_t::load(), furn_t::load(), damage_info_order::damage_info_order_entry::load(), bodygraph::load(), body_part_type::load(), field_type::load(), map_extra::load(), npc_class::load(), profession::load(), anonymous_namespace{recipe_groups.cpp}::recipe_group_data::load(), trap::load(), widget::load(), enchantment::load(), damage_type::load(), Creature::load(), reflex_activation_data::load(), map_deconstruct_info::load(), map_bash_info::load(), material_type::load(), explosion_iuse::load(), heal_actor::load(), bionic_data::load(), Item_factory::load_basic_info(), load_construction(), load_distribution(), talk_effect_t::load_effect(), load_explosion_data(), load_forest_biome(), load_forest_biome_component(), load_forest_biome_terrain_dependent_furniture(), load_forest_mapgen_settings(), load_forest_trail_settings(), mission_util::load_funcs(), melee_actor::load_internal(), load_mapgen_function(), effect_type::load_mod_data(), load_mutation_attack(), load_nested_mapgen(), load_overmap_connection_settings(), load_overmap_feature_flag_settings(), load_overmap_forest_settings(), load_overmap_lake_settings(), load_overmap_ocean_settings(), load_overmap_ravine_settings(), mapgen_palette::load_place_mapings(), load_region_settings(), load_region_terrain_and_furniture_settings(), requirement_data::load_requirement(), Skill::load_skill(), load_update_mapgen(), generic_typed_reader< Derived >::operator()(), read_condition(), Item_factory::set_use_methods_from_json(), talk_effect_t::talk_effect_t(), and talk_response::talk_response().
has_string()
bool JsonObject::has_string (std::string_view key) const inline
Definition at line 972 of file flexbuffer_json-inl.h.
 {
     flexbuffers::Reference ref = find_value_ref( key );
     return ref.IsString();
 }
References find_value_ref().
Referenced by abstract_read_var_info(), Item_factory::add_entry(), add_mapgen_update_func(), assign(), assign_coverage_from_json(), assign_function(), details::assign_set(), anonymous_namespace{condition.cpp}::condition_parser::check(), sub_effect_parser::check(), conditional_t::conditional_t(), bionic::deserialize(), mission::deserialize(), npc_favor::deserialize(), dynamic_line_t::dynamic_line_t(), effect_scaling::effect_scaling(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission(), faction_template::faction_template(), dynamic_line_t::from_member(), get_talk_var_basename(), get_talk_varname(), generic_factory< T >::handle_inheritance(), jmapgen_item_group::jmapgen_item_group(), jmapgen_loot::jmapgen_loot(), jmapgen_npc::jmapgen_npc(), jmapgen_spawn_item::jmapgen_spawn_item(), jmapgen_vehicle::jmapgen_vehicle(), jmapgen_zone::jmapgen_zone(), json_dynamic_line_effect::json_dynamic_line_effect(), json_talk_repeat_response::json_talk_repeat_response(), json_talk_topic::load(), itype_variant_data::load(), fake_spell::load(), connect_group::load(), ter_furn_migrations::load(), speed_description_value::load(), weakpoint_effect::load(), weakpoint::load(), cardreader_examine_actor::load(), vpart_variant::load(), map_data_common_t::load(), generic_factory< T >::load(), mattack_actor::load(), mission_type::load(), mtype::load(), oter_type_t::load(), recipe::load(), start_location::load(), vpart_info::load(), recipe_dictionary::load(), behavior::node_t::load(), bodygraph::load(), damage_info_order::load(), harvest_drop_type::load(), spell_type::load(), ma_requirements::load(), species_type::load(), npc_class::load(), profession::load(), anonymous_namespace{recipe_groups.cpp}::recipe_group_data::load(), scenario::load(), vehicle_prototype::load(), widget::load(), enchantment::load(), damage_type::load(), SkillDisplayType::load(), damage_over_time_data::load(), heal_actor::load(), weakpoint_family::load(), Item_factory::load(), effect_type::load_apply_msgs(), Item_factory::load_basic_info(), bionic_data::load_bionic_migration(), load_construction(), load_damage_instance_inherit(), Item_factory::load_definition(), talk_effect_t::load_effect(), load_effect_data(), load_float_or_maxmovecost(), mission_util::load_funcs(), Item_factory::load_item_group(), Item_factory::load_item_group_data(), load_mapgen(), Item_factory::load_migration(), global_variables::load_migrations(), mod_manager::load_modfile(), load_mutation_attack(), requirement_data::load_requirement(), load_season_array(), Skill::load_skill(), Item_factory::load_sub_ref(), mutation_branch::load_trait_migration(), load_transform_results(), vitamin::load_vitamin(), MonsterGroupManager::LoadMonsterGroup(), MonsterGroupManager::LoadMonsterWhitelist(), jmapgen_nested::neighbor_oter_check::neighbor_oter_check(), parse_vp_reqs(), read_condition(), read_with_factor(), Item_factory::set_use_methods_from_json(), mapgen_function_json::setup_internal(), talk_effect_t::talk_effect_t(), talk_response::talk_response(), and VehicleFunction_json::VehicleFunction_json().
init()
void JsonObject::init (const flexbuffer & json, tiny_bitset * moved_visited_fields = nullptr) inline private
Definition at line 582 of file flexbuffer_json.h.
{
             flexbuffers::Map json_map = json.AsMap();
             keys_ = json_map.Keys();
             values_ = json_map.Values();
             if( moved_visited_fields ) {
                 using namespace std;
                 swap( visited_fields_bitset_, *moved_visited_fields );
             } else {
                 visited_fields_bitset_.resize( keys_.size() );
             }
         }
References tiny_bitset::resize(), and cata::swap().
mark_visited()
void JsonObject::mark_visited (size_t idx) const inline private
Definition at line 716 of file flexbuffer_json.h.
{
             visited_fields_bitset_.set( idx );
         }
References tiny_bitset::set().
Referenced by error_skipped_members(), get_member(), get_member_opt(), JsonObject::const_iterator::operator*(), and operator[]().
operator=() [1/2]
JsonObject& JsonObject::operator= (const JsonObject & rhs) inline
Definition at line 558 of file flexbuffer_json.h.
{
             JsonWithPath::operator=( rhs );
             init( json_ );
             // Copying an object resets visited fields.
             visited_fields_bitset_.clear_all();
             return *this;
         }
References tiny_bitset::clear_all(), init, Json::json_, and JsonWithPath::operator=().
operator=() [2/2]
JsonObject& JsonObject::operator= (JsonObject && rhs) inline noexcept
Definition at line 572 of file flexbuffer_json.h.
{
             JsonWithPath::operator=( std::move( static_cast<JsonWithPath &>( rhs ) ) );
             init( json_, &rhs.visited_fields_bitset_ );
             rhs.visited_fields_bitset_.set_all();
             return *this;
         }
References init, Json::json_, and JsonWithPath::operator=().
operator[]() [1/2]
JsonValue JsonObject::operator[] (size_t idx) const inline private
Definition at line 1093 of file flexbuffer_json-inl.h.
 {
     mark_visited( idx );
     return JsonValue{ root_, values_[ idx ], &path_, idx };
 }
References mark_visited(), JsonWithPath::path_, Json::root_, and values_.
operator[]() [2/2]
JsonValue JsonObject::operator[] (std::string_view key) const inline
Definition at line 1053 of file flexbuffer_json-inl.h.
 {
     return get_member( key );
 }
References get_member().
read()
template<typename T > bool JsonObject::read (std::string_view name, T & t, bool throw_on_error = true) const
Definition at line 1059 of file flexbuffer_json-inl.h.
 {
     std::optional<JsonValue> member_opt = get_member_opt( name );
     if( !member_opt.has_value() ) {
         return false;
     }
     return ( *member_opt ).read( t, throw_on_error );
 }
References get_member_opt(), and om_direction::name().
Referenced by abstract_read_var_info(), snippet_library::add_snippet_from_json(), apply_region_overlay(), assign(), deserialize(), avatar::daily_calories::deserialize(), character_martial_arts::deserialize(), zone_data::deserialize(), comp_selection< CompType >::deserialize(), item::deserialize(), item_contents::deserialize(), known_magic::deserialize(), achievement_requirement::deserialize(), achievement::time_bound::deserialize(), achievement_state::deserialize(), achievements_tracker::deserialize(), activity_tracker::deserialize(), addiction::deserialize(), bionic::deserialize(), bodypart::deserialize(), consumption_event::deserialize(), outfit::deserialize(), damage_over_time_data::deserialize(), effect::deserialize(), value_constraint::deserialize(), faction::deserialize(), mapgen_parameter::deserialize(), memorial_log_entry::deserialize(), mission::deserialize(), player_morale::morale_point::deserialize(), npc_favor::deserialize(), mutable_special_connection::deserialize(), mutable_overmap_terrain::deserialize(), mutable_overmap_placement_rule_piece::deserialize(), mutable_overmap_placement_rule::deserialize(), learning_proficiency::deserialize(), event_summary::deserialize(), event_multiset::deserialize(), stats_tracker::deserialize(), nutrients::deserialize(), stomach_contents::deserialize(), efficiency_data::deserialize(), container_spawn_test_data::deserialize(), pocket_mod_test_data::deserialize(), npc_boarding_test_data::deserialize(), item_demographic_test_data::deserialize(), uistatedata::deserialize(), advanced_inv_pane_save_state::deserialize(), advanced_inv_save_state::deserialize(), plot_options::deserialize(), blueprint_options::deserialize(), ignorable_options::deserialize(), loot_options::deserialize(), unload_options::deserialize(), drop_or_stash_item_info::deserialize(), Pickup::pick_info::deserialize(), proficiency_set::deserialize(), item::craft_data::deserialize(), item_location::deserialize(), anonymous_namespace{messages.cpp}::game_message::deserialize(), mission_id::deserialize(), mutable_overmap_join::deserialize(), mutable_overmap_terrain_join::deserialize(), diary::deserialize(), overmap_static_spawns::deserialize(), overmap_special_spawns::deserialize(), overmap_special_connection::deserialize(), computer::deserialize(), trait_and_var::deserialize(), job_data::deserialize(), inventory_selector_save_state::deserialize(), data_handling_activity_actor::deserialize(), wear_activity_actor::deserialize(), wield_activity_actor::deserialize(), invoke_item_activity_actor::deserialize(), pickup_menu_activity_actor::deserialize(), aim_activity_actor::deserialize(), gunmod_remove_activity_actor::deserialize(), hacksaw_activity_actor::deserialize(), hacking_activity_actor::deserialize(), bookbinder_copy_activity_actor::deserialize(), hotwire_car_activity_actor::deserialize(), glide_activity_actor::deserialize(), bikerack_racking_activity_actor::deserialize(), bikerack_unracking_activity_actor::deserialize(), read_activity_actor::deserialize(), move_items_activity_actor::deserialize(), pickup_activity_actor::deserialize(), boltcutting_activity_actor::deserialize(), lockpick_activity_actor::deserialize(), ebooksave_activity_actor::deserialize(), open_gate_activity_actor::deserialize(), consume_activity_actor::deserialize(), try_sleep_activity_actor::deserialize(), safecracking_activity_actor::deserialize(), unload_activity_actor::deserialize(), craft_activity_actor::deserialize(), workout_activity_actor::deserialize(), drop_activity_actor::deserialize(), stash_activity_actor::deserialize(), harvest_activity_actor::deserialize(), reload_activity_actor::deserialize(), milk_activity_actor::deserialize(), shearing_activity_actor::deserialize(), disassemble_activity_actor::deserialize(), move_furniture_activity_actor::deserialize(), insert_item_activity_actor::deserialize(), tent_placement_activity_actor::deserialize(), oxytorch_activity_actor::deserialize(), play_with_pet_activity_actor::deserialize(), prying_activity_actor::deserialize(), tent_deconstruct_activity_actor::deserialize(), reel_cable_activity_actor::deserialize(), vehicle_folding_activity_actor::deserialize(), vehicle_unfolding_activity_actor::deserialize(), wash_activity_actor::deserialize(), chop_logs_activity_actor::deserialize(), chop_planks_activity_actor::deserialize(), chop_tree_activity_actor::deserialize(), churn_activity_actor::deserialize(), clear_rubble_activity_actor::deserialize(), disable_activity_actor::deserialize(), firstaid_activity_actor::deserialize(), forage_activity_actor::deserialize(), gunmod_add_activity_actor::deserialize(), longsalvage_activity_actor::deserialize(), mop_activity_actor::deserialize(), unload_loot_activity_actor::deserialize(), overmapbuffer::deserialize_overmap_global_state(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), faction_template::faction_template(), computer_option::from_json(), dynamic_line_t::from_member(), json_item_substitution::substitution::info::info(), jmapgen_computer::jmapgen_computer(), jmapgen_gaspump::jmapgen_gaspump(), jmapgen_graffiti::jmapgen_graffiti(), jmapgen_loot::jmapgen_loot(), jmapgen_make_rubble::jmapgen_make_rubble(), jmapgen_monster::jmapgen_monster(), jmapgen_npc::jmapgen_npc(), jmapgen_sign::jmapgen_sign(), legacy_volume_reader(), past_achievements_info::load(), event_source::load(), ter_furn_data< T >::load(), overmap_spawns::load(), recipe_proficiency::load(), book_recipe_data::load(), practice_recipe_data::load(), relic_charge_template::load(), relic_charge_info::load(), relic::load(), test_data::load(), link_up_actor::load(), mtype::load(), oter_type_t::load(), recipe::load(), start_location::load(), field_type::load(), anonymous_namespace{recipe_groups.cpp}::recipe_group_data::load(), trap::load(), enchantment::load(), Creature::load(), player_morale::load(), dream::load(), mutation_category_trait::load(), SkillDisplayType::load(), map_bash_info::load(), material_type::load(), iuse_transform::load(), unpack_actor::load(), message_iuse::load(), sound_iuse::load(), explosion_iuse::load(), consume_drug_iuse::load(), place_monster_iuse::load(), place_npc_iuse::load(), fireweapon_off_actor::load(), fireweapon_on_actor::load(), manualnoise_actor::load(), musical_instrument_actor::load(), holster_actor::load(), heal_actor::load(), effect_on_conditons_actor::load(), ammunition_type::load_ammunition_type(), Item_factory::load_basic_info(), load_bionic_social_mods(), load_charge_removal_blacklist(), load_construction(), Item_factory::load_definition(), load_explosion_data(), Creature::load_hit_range(), mapgen_palette::load_internal(), gun_actor::load_internal(), load_inv_state(), item_action_generator::load_item_action(), Item_factory::load_item_blacklist(), Item_factory::load_item_group(), load_mat_burn_data(), Item_factory::load_migration(), load_min_max(), effect_type::load_miss_msgs(), mod_manager::load_modfile(), load_monster_adjustment(), load_mutation_attack(), load_mutation_social_mods(), load_region_settings(), load_shrapnel_data(), Skill::load_skill(), load_speech(), Item_factory::load_string(), map_data_common_t::load_symbol(), load_temperature_removal_blacklist(), mutation_branch::load_trait_migration(), vitamin::load_vitamin(), mandatory(), one_char_symbol_reader(), optional(), mapgen_value< Id >::param_source::param_source(), past_game_info::past_game_info(), io::detail::has_archive_tag< T, E >::read(), avatar::daily_calories::read_activity(), read_and_set_or_throw(), read_legacy_creature_pos(), read_with_factor(), mapgen_function_json_base::setup_common(), mapgen_function_json::setup_internal(), mapgen_value< Id >::switch_source::switch_source(), talk_response::talk_response(), unicode_codepoint_from_symbol_reader(), overmap::unserialize(), global_variables::unserialize(), game::unserialize(), weather_manager::unserialize_all(), and overmap::unserialize_omap().
report_unvisited()
void JsonObject::report_unvisited () const private
Definition at line 252 of file flexbuffer_json.cpp.
 {
 #ifndef CATA_IN_TOOL
     if( !std::uncaught_exceptions() && report_unvisited_members && !visited_fields_bitset_.all() ) {
         std::vector<size_t> skipped_members;
         skipped_members.reserve( visited_fields_bitset_.size() );
         tiny_bitset::block_t *bits = visited_fields_bitset_.bits();
         size_t block_idx = 0;
         for( size_t last_whole_block = visited_fields_bitset_.size() / tiny_bitset::kBitsPerBlock;
              block_idx < last_whole_block; ++block_idx ) {
             tiny_bitset::block_t block = bits[block_idx];
             tiny_bitset::block_t mask = tiny_bitset::kLowBit << ( tiny_bitset::kBitsPerBlock - 1 );
             for( size_t bit_idx = 0; bit_idx < tiny_bitset::kBitsPerBlock; ++bit_idx ) {
                 if( !( block & mask ) ) {
                     skipped_members.emplace_back( block_idx * tiny_bitset::kBitsPerBlock + bit_idx );
                 }
                 mask >>= 1;
             }
         }
         tiny_bitset::block_t block = bits[block_idx];
         tiny_bitset::block_t mask = tiny_bitset::kLowBit << ( tiny_bitset::kBitsPerBlock - 1 );
         for( size_t bit_idx = 0, end = visited_fields_bitset_.size() % tiny_bitset::kBitsPerBlock;
              bit_idx < end; ++bit_idx ) {
             if( !( block & mask ) ) {
                 skipped_members.emplace_back( block_idx * tiny_bitset::kBitsPerBlock + bit_idx );
             }
             mask >>= 1;
         }
         // Don't error on skipped comments.
         skipped_members.erase( std::remove_if( skipped_members.begin(),
         skipped_members.end(), [this]( size_t idx ) {
             flexbuffers::String name = keys_[idx].AsString();
             return strncmp( "//", name.c_str(), 2 ) == 0 && strcmp( "//~", name.c_str() ) != 0;
         } ), skipped_members.end() );
         if( !skipped_members.empty() ) {
             error_skipped_members( skipped_members );
         }
         visited_fields_bitset_.set_all();
     }
 #endif
 }
References tiny_bitset::all(), tiny_bitset::bits(), om_direction::bits, end(), error_skipped_members(), tiny_bitset::kBitsPerBlock, keys_, tiny_bitset::kLowBit, om_direction::name(), anonymous_namespace{flexbuffer_json.cpp}::report_unvisited_members, tiny_bitset::set_all(), tiny_bitset::size(), and visited_fields_bitset_.
Referenced by ~JsonObject().
size()
size_t JsonObject::size () const inline
Definition at line 595 of file flexbuffer_json.h.
{
             return keys_.size();
         }
Referenced by new_field::deserialize().
str()
std::string Json::str
Definition at line 96 of file flexbuffer_json.cpp.
 {
     std::string ret;
     json_.ToString( false, true, ret );
     return ret;
 }
Referenced by conditional_t::conditional_t(), conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string(), eoc_math::from_json(), conditional_t::get_get_string(), conditional_t::get_get_translation(), get_talk_var_basename(), get_talk_varname(), Item_factory::load_item_group_data(), load_mapgen(), and talk_effect_t::parse_sub_effect().
throw_error()
void JsonObject::throw_error (const std::string & err) const
Definition at line 353 of file flexbuffer_json.cpp.
 {
     Json::throw_error( path_, 0, err );
 }
References JsonWithPath::path_, and Json::throw_error().
Referenced by abstract_read_var_info(), apply_region_overlay(), common_check_bounds(), conditional_t::conditional_t(), achievement_requirement::deserialize(), achievement::time_bound::deserialize(), climbing_aid::down_t::deserialize(), value_constraint::deserialize(), new_field::deserialize(), part_material::deserialize(), armor_portion_data::deserialize(), mutable_overmap_placement_rule::deserialize(), book_proficiency_bonus::deserialize(), int_distribution::deserialize(), dynamic_line_t::dynamic_line_t(), conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), eoc_math::from_json(), conditional_t::get_get_string(), conditional_t::get_get_translation(), get_talk_var_basename(), get_talk_varname(), generic_factory< T >::handle_inheritance(), iexamine_actor_from_jsobj(), mapgen_value< Id >::init_object(), io::JsonObjectInputArchive::io(), jmapgen_graffiti::jmapgen_graffiti(), jmapgen_loot::jmapgen_loot(), jmapgen_sign::jmapgen_sign(), json_talk_repeat_response::json_talk_repeat_response(), event_transformation::load(), event_statistic::load(), event_source::load(), pocket_data::load(), json_item_substitution::load(), weather_generator::load(), vpart_variant::load(), generic_factory< T >::load(), mutation_branch::load(), oter_type_t::load(), overmap_special::load(), recipe::load(), behavior::node_t::load(), character_modifier::load(), effect_on_condition::load(), mapgen_palette::load(), jmath_func::load(), npc_class::load(), overmap_location::load(), profession::load(), scenario::load(), trap::load(), weather_type::load(), profession_blacklist::load(), scen_blacklist::load(), inscribe_actor::load(), musical_instrument_actor::load(), Item_factory::load_basic_info(), load_construction(), load_distribution(), load_float_or_maxmovecost(), load_forest_biome(), load_forest_biome_component(), load_forest_biome_terrain_dependent_furniture(), load_forest_mapgen_settings(), load_forest_trail_settings(), load_mapgen_function(), Item_factory::load_migration(), load_mutation_attack(), load_overmap_connection_settings(), load_overmap_feature_flag_settings(), load_overmap_forest_settings(), load_overmap_lake_settings(), load_overmap_ocean_settings(), load_overmap_ravine_settings(), load_recipe_category(), load_region_overlay(), load_region_settings(), load_region_terrain_and_furniture_settings(), requirement_data::load_requirement(), load_season_array(), Item_factory::load_sub_ref(), map_data_common_t::load_symbol(), mutation_branch::load_trait_migration(), mandatory(), talk_effect_t::parse_sub_effect(), read_and_set_or_throw(), Item_factory::set_use_methods_from_json(), mapgen_function_json_base::setup_common(), mapgen_function_json::setup_internal(), mapgen_function_json_nested::setup_internal(), talk_response::talk_response(), and throw_error_at().
throw_error_at()
void JsonObject::throw_error_at (std::string_view member, const std::string & err) const
Definition at line 358 of file flexbuffer_json.cpp.
 {
     std::optional<JsonValue> member_opt = get_member_opt( member );
     if( member_opt.has_value() ) {
         ( *member_opt ).throw_error( err );
     } else {
         throw_error( err );
     }
 }
References get_member_opt(), member, and throw_error().
Referenced by snippet_library::add_snippet_from_json(), assign(), assign_dmg_proportional(), assign_function(), details::assign_set(), check_assigned_dmg(), common_check_bounds(), MonsterGenerator::create_actor(), translation::deserialize(), dynamic_line_t::dynamic_line_t(), json_item_substitution::substitution::info::info(), jmapgen_int::jmapgen_int(), json_talk_topic::load(), fault::load(), mon_effect_data::load(), speed_description_value::load(), vpart_variant::load(), mtype::load(), recipe::load(), rotatable_symbols::load(), field_type::load(), move_mode::load(), trap::load(), widget::load(), iuse_transform::load(), change_scent_iuse::load(), repair_item_actor::load(), sew_advanced_actor::load(), quality_requirement::load(), Item_factory::load(), Item_factory::load_basic_info(), load_construction(), load_distribution(), talk_effect_t::load_effect(), load_external_option(), gun_actor::load_internal(), Item_factory::load_item_group(), load_mapgen_function(), mod_manager::load_modfile(), DynamicDataLoader::load_object(), load_season_array(), mutation_branch::load_trait_group(), vitamin::load_vitamin(), load_world_option(), one_char_symbol_reader(), talk_effect_t::parse_string_effect(), read_condition(), Item_factory::relative_qualities_from_json(), report_strict_violation(), Item_factory::set_qualities_from_json(), Item_factory::set_techniques_from_json(), mapgen_function_json_base::setup_common(), talk_trial::talk_trial(), and unicode_codepoint_from_symbol_reader().
Member Data Documentation
const_iterator
friend JsonObject::const_iterator
Definition at line 673 of file flexbuffer_json.h.
Referenced by begin(), and end().
keys_
flexbuffers::TypedVector JsonObject::keys_ = flexbuffers::TypedVector::EmptyTypedVector() protected
Definition at line 529 of file flexbuffer_json.h.
Referenced by end(), error_skipped_members(), get_member(), get_member_opt(), get_string(), has_member(), JsonObject::const_iterator::operator*(), and report_unvisited().
values_
flexbuffers::Vector JsonObject::values_ = flexbuffers::Vector::EmptyVector() protected
Definition at line 530 of file flexbuffer_json.h.
Referenced by get_member(), get_member_opt(), and operator[]().
visited_fields_bitset_
tiny_bitset JsonObject::visited_fields_bitset_ mutable protected
Definition at line 531 of file flexbuffer_json.h.
Referenced by copy_visited_members(), report_unvisited(), and ~JsonObject().
The documentation for this class was generated from the following files:
src/flexbuffer_json.h
src/flexbuffer_json-inl.h
src/flexbuffer_json.cpp