Cataclysm DDA: talker_character Class Reference
talker_character Class Reference
#include <talker_character.h>
Public Member Functions
talker_character (Character *new_me)
~talker_character () override=default
Character * get_character () override
const Character * get_character () const override
Creature * get_creature () override
const Creature * get_creature () const override
void set_pos (tripoint new_pos) override
void set_str_max (int value) override
void set_dex_max (int value) override
void set_int_max (int value) override
void set_per_max (int value) override
void set_str_bonus (int value) override
void set_dex_bonus (int value) override
void set_int_bonus (int value) override
void set_per_bonus (int value) override
void set_power_cur (units::energy value) override
void set_mana_cur (int value) override
void set_spell_level (const spell_id &, int) override
void set_spell_exp (const spell_id &, int) override
void set_proficiency_practiced_time (const proficiency_id &prof, int turns) override
void train_proficiency_for (const proficiency_id &prof, int turns) override
void mutate (const int &highest_cat_chance, const bool &use_vitamins) override
void mutate_category (const mutation_category_id &mut_cat, const bool &use_vitamins) override
void mutate_towards (const trait_id &trait, const mutation_category_id &mut_cat, const bool &use_vitamins) override
void set_mutation (const trait_id &new_trait, const mutation_variant *=nullptr) override
void unset_mutation (const trait_id &old_trait) override
void activate_mutation (const trait_id &trait) override
void deactivate_mutation (const trait_id &trait) override
void set_skill_level (const skill_id &skill, int value) override
void set_skill_exp (const skill_id &skill, int value, bool raw=false) override
void learn_recipe (const recipe_id &recipe_to_learn) override
void forget_recipe (const recipe_id &recipe_to_forget) override
void add_effect (const efftype_id &new_effect, const time_duration &dur, const std::string &bp, bool permanent, bool force, int intensity) override
void remove_effect (const efftype_id &old_effect, const std::string &bp) override
void set_value (const std::string &var_name, const std::string &value) override
void remove_value (const std::string &var_name) override
std::vector< item * > items_with (const std::function< bool(const item &)> &filter) const override
std::list< item > use_charges (const itype_id &item_name, int count) override
std::list< item > use_charges (const itype_id &item_name, int count, bool in_tools) override
std::list< item > use_amount (const itype_id &item_name, int count) override
void i_add (const item &new_item) override
void i_add_or_drop (item &new_item, bool force_equip=false) override
void remove_items_with (const std::function< bool(const item &)> &filter) override
void set_stored_kcal (int value) override
void set_thirst (int value) override
void shout (const std::string &speech="", bool order=false) override
void set_sleepiness (int amount) override
void mod_pain (int amount) override
void set_pain (int amount) override
void mod_daily_health (int, int) override
void add_morale (const morale_type &new_morale, int bonus, int max_bonus, time_duration duration, time_duration decay_started, bool capped) override
void remove_morale (const morale_type &old_morale) override
void set_addiction_turns (const addiction_id &add_id, int amount) override
void mod_focus (int) override
void set_rad (int) override
void set_stim (int) override
void set_pkill (int) override
void set_stamina (int) override
void set_sleep_deprivation (int) override
void set_kill_xp (int) override
void set_age (int) override
void set_height (int) override
void add_bionic (const bionic_id &new_bionic) override
void remove_bionic (const bionic_id &old_bionic) override
std::vector< bodypart_id > get_all_body_parts (get_body_part_flags flags) const override
int get_part_hp_cur (const bodypart_id &id) const override
int get_part_hp_max (const bodypart_id &id) const override
void set_all_parts_hp_cur (int) const override
void set_part_hp_cur (const bodypart_id &id, int set) const override
bool get_is_alive () const override
void die () override
void attack_target (Creature &t, bool allow_special, const matec_id &force_technique, bool allow_unarmed, int forced_movecost) override
matec_id get_random_technique (Creature &t, bool crit, bool dodge_counter, bool block_counter, const std::vector< matec_id > &blacklist={}) const override
void learn_martial_art (const matype_id &id) const override
void forget_martial_art (const matype_id &id) const override
Public Member Functions inherited from talker_cloner< talker_character, talker_character_const >
std::unique_ptr< talker > clone () const override
Public Member Functions inherited from talker_character_const
talker_character_const (const Character *new_me)
~talker_character_const () override=default
std::string disp_name () const override
std::string get_name () const override
character_id getID () const override
bool is_male () const override
std::vector< std::string > get_grammatical_genders () const override
int posx () const override
int posy () const override
int posz () const override
tripoint pos () const override
tripoint_abs_ms global_pos () const override
tripoint_abs_omt global_omt_location () const override
int get_cur_hp (const bodypart_id &bp) const override
int get_hp_max (const bodypart_id &bp) const override
units::temperature get_cur_part_temp (const bodypart_id &bp) const override
int str_cur () const override
int dex_cur () const override
int int_cur () const override
int per_cur () const override
int attack_speed () const override
int pain_cur () const override
int perceived_pain_cur () const override
double armor_at (damage_type_id &dt, bodypart_id &bp) const override
int coverage_at (bodypart_id &) const override
int encumbrance_at (bodypart_id &) const override
int get_str_max () const override
int get_dex_max () const override
int get_int_max () const override
int get_per_max () const override
int get_str_bonus () const override
int get_dex_bonus () const override
int get_int_bonus () const override
int get_per_bonus () const override
units::energy power_cur () const override
units::energy power_max () const override
int mana_cur () const override
int mana_max () const override
bool has_trait (const trait_id &trait_to_check) const override
bool has_recipe (const recipe_id &recipe_to_check) const override
bool has_flag (const json_character_flag &trait_flag_to_check) const override
bool has_species (const species_id &species) const override
bool bodytype (const bodytype_id &bt) const override
bool crossed_threshold () const override
int num_bionics () const override
bool has_max_power () const override
bool has_bionic (const bionic_id &bionics_id) const override
bool knows_spell (const spell_id &sp) const override
int get_skill_level (const skill_id &) const override
int get_skill_exp (const skill_id &skill, bool raw=false) const override
int get_spell_level (const trait_id &) const override
int get_spell_level (const spell_id &) const override
int get_spell_exp (const spell_id &) const override
int get_highest_spell_level () const override
int get_spell_count (const trait_id &) const override
int get_spell_sum (const trait_id &school, int min_level) const override
bool knows_proficiency (const proficiency_id &proficiency) const override
time_duration proficiency_practiced_time (const proficiency_id &) const override
bool has_effect (const efftype_id &effect_id, const bodypart_id &bp) const override
effect get_effect (const efftype_id &effect_id, const bodypart_id &bp) const override
bool is_deaf () const override
bool is_mute () const override
std::optional< std::string > maybe_get_value (const std::string &var_name) const override
std::vector< skill_id > skills_teacheable () const override
std::vector< skill_id > skills_offered_to (const talker &student) const override
std::string skill_seminar_text (const skill_id &s) const override
std::string skill_training_text (const talker &, const skill_id &) const override
std::vector< proficiency_id > proficiencies_teacheable () const override
std::vector< proficiency_id > proficiencies_offered_to (const talker &student) const override
std::string proficiency_seminar_text (const proficiency_id &) const override
std::string proficiency_training_text (const talker &student, const proficiency_id &proficiency) const override
std::vector< matype_id > styles_teacheable () const override
std::vector< matype_id > styles_offered_to (const talker &student) const override
std::string style_seminar_text (const matype_id &) const override
std::string style_training_text (const talker &, const matype_id &) const override
std::vector< spell_id > spells_teacheable () const override
std::vector< spell_id > spells_offered_to (talker &student) const override
std::string spell_seminar_text (const spell_id &) const override
std::string spell_training_text (talker &, const spell_id &) const override
bool is_wearing (const itype_id &item_id) const override
int charges_of (const itype_id &item_id) const override
bool has_charges (const itype_id &item_id, int count) const override
bool has_charges (const itype_id &item_id, int count, bool in_tools) const override
bool has_amount (const itype_id &item_id, int count) const override
int get_amount (const itype_id &item_id) const override
int cash () const override
std::vector< const item * > const_items_with (const std::function< bool(const item &)> &filter) const override
bool unarmed_attack () const override
bool can_stash_weapon () const override
bool has_stolen_item (const talker &guy) const override
faction * get_faction () const override
std::string short_description () const override
bool has_activity () const override
bool is_mounted () const override
int get_activity_level () const override
int get_sleepiness () const override
int get_hunger () const override
int get_thirst () const override
int get_instant_thirst () const override
int get_stored_kcal () const override
int get_healthy_kcal () const override
int get_size () const override
bool is_in_control_of (const vehicle &veh) const override
bool worn_with_flag (const flag_id &flag, const bodypart_id &bp) const override
bool wielded_with_flag (const flag_id &flag) const override
bool wielded_with_weapon_category (const weapon_category_id &w_cat) const override
bool has_item_with_flag (const flag_id &flag) const override
int item_rads (const flag_id &flag, aggregate_type agg_func) const override
bool can_see () const override
bool can_see_location (const tripoint &pos) const override
int morale_cur () const override
int focus_cur () const override
int get_rad () const override
int get_stim () const override
int get_addiction_intensity (const addiction_id &add_id) const override
int get_addiction_turns (const addiction_id &add_id) const override
int get_pkill () const override
int get_stamina () const override
int get_sleep_deprivation () const override
int get_kill_xp () const override
int get_age () const override
int get_height () const override
int get_bmi_permil () const override
int get_weight () const override
const move_mode_id & get_move_mode () const override
int get_fine_detail_vision_mod () const override
int get_health () const override
units::temperature get_body_temp () const override
units::temperature_delta get_body_temp_delta () const override
bool knows_martial_art (const matype_id &id) const override
bool using_martial_art (const matype_id &id) const override
int climate_control_str_heat () const override
int climate_control_str_chill () const override
Public Member Functions inherited from talker_cloner< talker_character_const >
std::unique_ptr< talker > clone () const override
Public Member Functions inherited from talker
virtual ~talker ()=default
virtual npc * get_npc ()
virtual npc * get_npc () const
virtual item_location * get_item ()
virtual item_location * get_item () const
virtual monster * get_monster ()
virtual const monster * get_monster () const
virtual computer * get_computer ()
virtual const computer * get_computer () const
virtual std::string distance_to_goal () const
virtual bool will_talk_to_u (const Character &, bool)
virtual std::vector< std::string > get_topics (bool)
virtual void check_missions ()
virtual void update_missions (const std::vector< mission * > &)
virtual bool check_hostile_response (int) const
virtual int parse_mod (const std::string &, int) const
virtual int trial_chance_mod (const std::string &) const
virtual int get_count () const
virtual int get_grab_strength () const
virtual void store_chosen_training (const skill_id &, const matype_id &, const spell_id &, const proficiency_id &)
virtual std::string get_value (const std::string &key) const
virtual int value (const item &) const
virtual int debt () const
virtual void add_debt (int)
virtual int sold () const
virtual void add_sold (int)
virtual int cash_to_favor (int) const
virtual std::string give_item_to (bool)
virtual bool buy_from (int)
virtual bool buy_monster (talker &, const mtype_id &, int, int, bool, const translation &)
virtual std::vector< mission * > available_missions () const
virtual std::vector< mission * > assigned_missions () const
virtual mission * selected_mission () const
virtual void select_mission (mission *)
virtual void add_mission (const mission_type_id &)
virtual void set_companion_mission (const std::string &)
virtual void set_fac (const faction_id &)
virtual void add_faction_rep (int)
virtual bool is_following () const
virtual bool is_friendly (const Character &) const
virtual bool is_player_ally () const
virtual bool turned_hostile () const
virtual bool is_enemy () const
virtual void make_angry ()
virtual bool has_ai_rule (const std::string &, const std::string &) const
virtual void toggle_ai_rule (const std::string &, const std::string &)
virtual void set_ai_rule (const std::string &, const std::string &)
virtual void clear_ai_rule (const std::string &, const std::string &)
virtual std::string get_job_description () const
virtual std::string evaluation_by (const talker &) const
virtual std::string view_personality_traits () const
virtual bool is_myclass (const npc_class_id &) const
virtual void set_class (const npc_class_id &)
virtual void say (const std::string &)
virtual bool enslave_mind ()
virtual std::string opinion_text () const
virtual void add_opinion (const npc_opinion &)
virtual void set_first_topic (const std::string &)
virtual bool is_safe () const
virtual int get_anger () const
virtual void set_anger (int)
virtual void set_morale (int)
virtual int get_friendly () const
virtual void set_friendly (int)
virtual int get_volume () const
virtual void set_npc_trust (int)
virtual int get_npc_trust () const
virtual void set_npc_fear (int)
virtual int get_npc_fear () const
virtual void set_npc_value (int)
virtual int get_npc_value () const
virtual void set_npc_anger (int)
virtual int get_npc_anger () const
Protected Member Functions
talker_character ()=default
Protected Member Functions inherited from talker_character_const
talker_character_const ()=default
Protected Attributes
Character * me_chr
Protected Attributes inherited from talker_character_const
const Character * me_chr_const
Detailed Description
Definition at line 208 of file talker_character.h.
Constructor & Destructor Documentation
talker_character() [1/2]
talker_character::talker_character (Character * new_me) explicit
Definition at line 24 of file talker_character.cpp.
 {
     me_chr = new_me;
     me_chr_const = new_me;
 }
References me_chr, and talker_character_const::me_chr_const.
~talker_character()
talker_character::~talker_character () override default
talker_character() [2/2]
talker_character::talker_character () protected default
Member Function Documentation
activate_mutation()
void talker_character::activate_mutation (const trait_id & trait) override virtual
Reimplemented from talker.
Definition at line 269 of file talker_character.cpp.
 {
     me_chr->activate_mutation( trait );
 }
References Character::activate_mutation(), and me_chr.
add_bionic()
void talker_character::add_bionic (const bionic_id & new_bionic) override virtual
Reimplemented from talker.
Definition at line 1006 of file talker_character.cpp.
 {
     me_chr->add_bionic( new_bionic );
 }
References Character::add_bionic(), and me_chr.
add_effect()
void talker_character::add_effect (const efftype_id & new_effect, const time_duration & dur, const std::string & bp, bool permanent, bool force, int intensity) override virtual
Reimplemented from talker.
Definition at line 449 of file talker_character.cpp.
 {
     bodypart_id target_part;
     if( "RANDOM" == bp ) {
         target_part = get_player_character().random_body_part( true );
     } else {
         target_part = bodypart_str_id( bp );
     }
     me_chr->add_effect( new_effect, dur, target_part, permanent, intensity, force );
 }
References Creature::add_effect(), bp, dur, force, get_player_character(), intensity, me_chr, permanent, and Creature::random_body_part().
add_morale()
void talker_character::add_morale (const morale_type & new_morale, int bonus, int max_bonus, time_duration duration, time_duration decay_started, bool capped) override virtual
Reimplemented from talker.
Definition at line 816 of file talker_character.cpp.
 {
     me_chr->add_morale( new_morale, bonus, max_bonus, duration, decay_start, capped );
 }
References Character::add_morale(), and me_chr.
attack_target()
void talker_character::attack_target (Creature & t, bool allow_special, const matec_id & force_technique, bool allow_unarmed, int forced_movecost) override virtual
Reimplemented from talker.
Definition at line 1222 of file talker_character.cpp.
 {
     me_chr->melee_attack( t, allow_special, force_technique, allow_unarmed, forced_movecost );
 }
References me_chr, and Character::melee_attack().
deactivate_mutation()
void talker_character::deactivate_mutation (const trait_id & trait) override virtual
Reimplemented from talker.
Definition at line 274 of file talker_character.cpp.
 {
     me_chr->deactivate_mutation( trait );
 }
References Character::deactivate_mutation(), and me_chr.
die()
void talker_character::die () override virtual
Reimplemented from talker.
Reimplemented in talker_npc.
Definition at line 1210 of file talker_character.cpp.
 {
     me_chr->die( nullptr );
 }
References Character::die(), and me_chr.
forget_martial_art()
void talker_character::forget_martial_art (const matype_id & id) const override virtual
Reimplemented from talker.
Definition at line 1233 of file talker_character.cpp.
 {
     me_chr->martial_arts_data->clear_style( id );
 }
References Character::martial_arts_data, and me_chr.
forget_recipe()
void talker_character::forget_recipe (const recipe_id & recipe_to_forget) override virtual
Reimplemented from talker.
Definition at line 227 of file talker_character.cpp.
 {
     me_chr->forget_recipe( &*recipe_to_forget );
 }
References Character::forget_recipe(), and me_chr.
get_all_body_parts()
std::vector< bodypart_id > talker_character::get_all_body_parts (get_body_part_flags flags) const override virtual
Reimplemented from talker.
Definition at line 1180 of file talker_character.cpp.
 {
     return me_chr->get_all_body_parts( flags );
 }
References Creature::get_all_body_parts(), and me_chr.
get_character() [1/2]
const Character* talker_character::get_character () const inline override virtual
Reimplemented from talker_character_const.
Definition at line 218 of file talker_character.h.
{
             return me_chr_const;
         }
References talker_character_const::me_chr_const.
get_character() [2/2]
Character* talker_character::get_character () inline override virtual
Reimplemented from talker_character_const.
Definition at line 215 of file talker_character.h.
{
             return me_chr;
         }
References me_chr.
get_creature() [1/2]
const Creature* talker_character::get_creature () const inline override virtual
Reimplemented from talker_character_const.
Definition at line 224 of file talker_character.h.
{
             return me_chr_const;
         }
References talker_character_const::me_chr_const.
get_creature() [2/2]
Creature* talker_character::get_creature () inline override virtual
Reimplemented from talker_character_const.
Definition at line 221 of file talker_character.h.
{
             return me_chr;
         }
References me_chr.
get_is_alive()
bool talker_character::get_is_alive () const override virtual
Reimplemented from talker.
Definition at line 1205 of file talker_character.cpp.
 {
     return !me_chr->is_dead_state();
 }
References Character::is_dead_state(), and me_chr.
get_part_hp_cur()
int talker_character::get_part_hp_cur (const bodypart_id & id) const override virtual
Reimplemented from talker.
Definition at line 1185 of file talker_character.cpp.
 {
     return me_chr->get_part_hp_cur( id );
 }
References Creature::get_part_hp_cur(), and me_chr.
get_part_hp_max()
int talker_character::get_part_hp_max (const bodypart_id & id) const override virtual
Reimplemented from talker.
Definition at line 1190 of file talker_character.cpp.
 {
     return me_chr->get_part_hp_max( id );
 }
References Creature::get_part_hp_max(), and me_chr.
get_random_technique()
matec_id talker_character::get_random_technique (Creature & t, bool crit, bool dodge_counter, bool block_counter, const std::vector< matec_id > & blacklist = {}) const override virtual
Reimplemented from talker.
Definition at line 1215 of file talker_character.cpp.
 {
     return me_chr->pick_technique( t, me_chr->used_weapon(), crit, dodge_counter, block_counter,
                                    blacklist );
 }
References me_chr, Character::pick_technique(), and Character::used_weapon().
i_add()
void talker_character::i_add (const item & new_item) override virtual
Reimplemented from talker.
Definition at line 562 of file talker_character.cpp.
 {
     me_chr->i_add( new_item );
 }
References Character::i_add(), and me_chr.
i_add_or_drop()
void talker_character::i_add_or_drop (item & new_item, bool force_equip = false) override virtual
Reimplemented from talker.
Definition at line 567 of file talker_character.cpp.
 {
     if( force_equip ) {
         if( me_chr->can_wear( new_item ).success() ) {
             new_item.set_flag( json_flag_FIT );
             me_chr->wear_item( new_item, false );
             return;
         } else if( !me_chr->has_wield_conflicts( new_item ) &&
                    !me_chr->martial_arts_data->keep_hands_free && //No wield if hands free
                    me_chr->wield( new_item ) ) {
             return;
         }
     }
     me_chr->i_add_or_drop( new_item );
 }
References Character::can_wear(), Character::has_wield_conflicts(), Character::i_add_or_drop(), json_flag_FIT, Character::martial_arts_data, me_chr, item::set_flag(), ret_val_common::success(), Character::wear_item(), and Character::wield().
items_with()
std::vector< item * > talker_character::items_with (const std::function< bool(const item &)> & filter) const override virtual
Reimplemented from talker.
Definition at line 556 of file talker_character.cpp.
 {
     return me_chr->items_with( filter );
 }
References filter, visitable::items_with(), and me_chr.
learn_martial_art()
void talker_character::learn_martial_art (const matype_id & id) const override virtual
Reimplemented from talker.
Definition at line 1228 of file talker_character.cpp.
 {
     me_chr->martial_arts_data->add_martialart( id );
 }
References Character::martial_arts_data, and me_chr.
learn_recipe()
void talker_character::learn_recipe (const recipe_id & recipe_to_learn) override virtual
Reimplemented from talker.
Definition at line 222 of file talker_character.cpp.
 {
     me_chr->learn_recipe( &*recipe_to_learn );
 }
References Character::learn_recipe(), and me_chr.
mod_daily_health()
void talker_character::mod_daily_health (int amount, int cap) override virtual
Reimplemented from talker.
Definition at line 806 of file talker_character.cpp.
 {
     me_chr->mod_daily_health( amount, cap );
 }
References me_chr, and Character::mod_daily_health().
mod_focus()
void talker_character::mod_focus (int amount) override virtual
Reimplemented from talker.
Definition at line 832 of file talker_character.cpp.
 {
     me_chr->mod_focus( amount );
 }
References me_chr, and Character::mod_focus().
mod_pain()
void talker_character::mod_pain (int amount) override virtual
Reimplemented from talker.
Definition at line 723 of file talker_character.cpp.
 {
     me_chr->mod_pain( amount );
 }
References me_chr, and Character::mod_pain().
mutate()
void talker_character::mutate (const int & highest_cat_chance, const bool & use_vitamins) override virtual
Reimplemented from talker.
Definition at line 242 of file talker_character.cpp.
 {
     me_chr->mutate( highest_cat_chance, use_vitamins );
 }
References me_chr, and Character::mutate().
mutate_category()
void talker_character::mutate_category (const mutation_category_id & mut_cat, const bool & use_vitamins) override virtual
Reimplemented from talker.
Definition at line 247 of file talker_character.cpp.
 {
     me_chr->mutate_category( mut_cat, use_vitamins );
 }
References me_chr, and Character::mutate_category().
mutate_towards()
void talker_character::mutate_towards (const trait_id & trait, const mutation_category_id & mut_cat, const bool & use_vitamins) override virtual
Reimplemented from talker.
Definition at line 253 of file talker_character.cpp.
 {
     me_chr->mutate_towards( trait, mut_cat, nullptr, use_vitamins );
 }
References me_chr, and Character::mutate_towards().
remove_bionic()
void talker_character::remove_bionic (const bionic_id & old_bionic) override virtual
Reimplemented from talker.
Definition at line 1011 of file talker_character.cpp.
 {
     if( std::optional<bionic *> bio = me_chr->find_bionic_by_type( old_bionic ) ) {
         me_chr->remove_bionic( **bio );
     }
 }
References Character::find_bionic_by_type(), me_chr, and Character::remove_bionic().
remove_effect()
void talker_character::remove_effect (const efftype_id & old_effect, const std::string & bp) override virtual
Reimplemented from talker.
Definition at line 463 of file talker_character.cpp.
 {
     bodypart_id target_part;
     if( "RANDOM" == bp ) {
         target_part = get_player_character().random_body_part( true );
     } else {
         target_part = bodypart_str_id( bp );
     }
     me_chr->remove_effect( old_effect, target_part );
 }
References bp, get_player_character(), me_chr, Creature::random_body_part(), and Creature::remove_effect().
remove_items_with()
void talker_character::remove_items_with (const std::function< bool(const item &)> & filter) override virtual
Reimplemented from talker.
Definition at line 583 of file talker_character.cpp.
 {
     me_chr->remove_items_with( filter );
 }
References filter, me_chr, and Character::remove_items_with().
remove_morale()
void talker_character::remove_morale (const morale_type & old_morale) override virtual
Reimplemented from talker.
Definition at line 822 of file talker_character.cpp.
 {
     me_chr->rem_morale( old_morale );
 }
References me_chr, and Character::rem_morale().
remove_value()
void talker_character::remove_value (const std::string & var_name) override virtual
Reimplemented from talker.
Definition at line 485 of file talker_character.cpp.
 {
     me_chr->remove_value( var_name );
 }
References me_chr, and Creature::remove_value().
set_addiction_turns()
void talker_character::set_addiction_turns (const addiction_id & add_id, int amount) override virtual
Reimplemented from talker.
Definition at line 867 of file talker_character.cpp.
 {
     for( addiction &add : me_chr->addictions ) {
         if( add.type == add_id ) {
             add.sated += time_duration::from_turns( amount );
         }
     }
 }
References add, Character::addictions, time_duration::from_turns(), and me_chr.
set_age()
void talker_character::set_age (int amount) override virtual
Reimplemented from talker.
Definition at line 921 of file talker_character.cpp.
 {
     int years_since_cataclysm = to_turns<int>( calendar::turn - calendar::turn_zero ) /
                                 to_turns<int>( calendar::year_length() );
     me_chr->set_base_age( amount + years_since_cataclysm );
 }
References me_chr, Character::set_base_age(), calendar::turn, calendar::turn_zero, and calendar::year_length().
set_all_parts_hp_cur()
void talker_character::set_all_parts_hp_cur (int set) const override virtual
Reimplemented from talker.
Definition at line 1200 of file talker_character.cpp.
 {
     me_chr->set_all_parts_hp_cur( set );
 }
References me_chr, and Creature::set_all_parts_hp_cur().
set_dex_bonus()
void talker_character::set_dex_bonus (int value) override virtual
Reimplemented from talker.
Definition at line 157 of file talker_character.cpp.
 {
     me_chr->mod_dex_bonus( value );
 }
References me_chr, Character::mod_dex_bonus(), and talker::value().
set_dex_max()
void talker_character::set_dex_max (int value) override virtual
Reimplemented from talker.
Definition at line 137 of file talker_character.cpp.
 {
     me_chr->dex_max = value;
 }
References Character::dex_max, me_chr, and talker::value().
set_height()
void talker_character::set_height (int amount) override virtual
Reimplemented from talker.
Definition at line 943 of file talker_character.cpp.
 {
     me_chr->set_base_height( amount );
 }
References me_chr, and Character::set_base_height().
set_int_bonus()
void talker_character::set_int_bonus (int value) override virtual
Reimplemented from talker.
Definition at line 162 of file talker_character.cpp.
 {
     me_chr->mod_int_bonus( value );
 }
References me_chr, Character::mod_int_bonus(), and talker::value().
set_int_max()
void talker_character::set_int_max (int value) override virtual
Reimplemented from talker.
Definition at line 142 of file talker_character.cpp.
 {
     me_chr->int_max = value;
 }
References Character::int_max, me_chr, and talker::value().
set_kill_xp()
void talker_character::set_kill_xp (int amount) override virtual
Reimplemented from talker.
Definition at line 911 of file talker_character.cpp.
 {
     me_chr->kill_xp = amount;
 }
References Character::kill_xp, and me_chr.
set_mana_cur()
void talker_character::set_mana_cur (int value) override virtual
Reimplemented from talker.
Definition at line 785 of file talker_character.cpp.
 {
     me_chr->magic->set_mana( value );
 }
References Character::magic, me_chr, and talker::value().
set_mutation()
void talker_character::set_mutation (const trait_id & new_trait, const mutation_variant * variant = nullptr) override virtual
Reimplemented from talker.
Definition at line 259 of file talker_character.cpp.
 {
     me_chr->set_mutation( new_trait, variant );
 }
References me_chr, and Character::set_mutation().
set_pain()
void talker_character::set_pain (int amount) override virtual
Reimplemented from talker.
Definition at line 728 of file talker_character.cpp.
 {
     me_chr->set_pain( amount );
 }
References me_chr, and Character::set_pain().
set_part_hp_cur()
void talker_character::set_part_hp_cur (const bodypart_id & id, int set) const override virtual
Reimplemented from talker.
Definition at line 1195 of file talker_character.cpp.
 {
     me_chr->set_part_hp_cur( id, set );
 }
References me_chr, and Character::set_part_hp_cur().
set_per_bonus()
void talker_character::set_per_bonus (int value) override virtual
Reimplemented from talker.
Definition at line 167 of file talker_character.cpp.
 {
     me_chr->mod_per_bonus( value );
 }
References me_chr, Character::mod_per_bonus(), and talker::value().
set_per_max()
void talker_character::set_per_max (int value) override virtual
Reimplemented from talker.
Definition at line 147 of file talker_character.cpp.
 {
     me_chr->per_max = value;
 }
References me_chr, Character::per_max, and talker::value().
set_pkill()
void talker_character::set_pkill (int amount) override virtual
Reimplemented from talker.
Definition at line 886 of file talker_character.cpp.
 {
     me_chr->set_painkiller( amount );
 }
References me_chr, and Character::set_painkiller().
set_pos()
void talker_character::set_pos (tripoint new_pos) override virtual
Reimplemented from talker.
Definition at line 85 of file talker_character.cpp.
 {
     me_chr->setpos( new_pos );
 }
References me_chr, and Creature::setpos().
set_power_cur()
void talker_character::set_power_cur (units::energy value) override virtual
Reimplemented from talker.
Definition at line 315 of file talker_character.cpp.
 {
     me_chr->set_power_level( value );
 }
References me_chr, Character::set_power_level(), and talker::value().
set_proficiency_practiced_time()
void talker_character::set_proficiency_practiced_time (const proficiency_id & prof, int turns) override virtual
Reimplemented from talker.
Definition at line 428 of file talker_character.cpp.
 {
     me_chr->set_proficiency_practiced_time( prof, turns );
 }
References me_chr, and Character::set_proficiency_practiced_time().
set_rad()
void talker_character::set_rad (int amount) override virtual
Reimplemented from talker.
Definition at line 837 of file talker_character.cpp.
 {
     me_chr->set_rad( amount );
 }
References me_chr, and Character::set_rad().
set_skill_exp()
void talker_character::set_skill_exp (const skill_id & skill, int value, bool raw = false) override virtual
Reimplemented from talker.
Definition at line 345 of file talker_character.cpp.
 {
     me_chr->get_skill_level_object( skill ).set_exercise( value, raw );
 }
References Character::get_skill_level_object(), me_chr, SkillLevel::set_exercise(), and talker::value().
set_skill_level()
void talker_character::set_skill_level (const skill_id & skill, int value) override virtual
Reimplemented from talker.
Definition at line 335 of file talker_character.cpp.
 {
     me_chr->set_skill_level( skill, value );
 }
References me_chr, Character::set_skill_level(), and talker::value().
set_sleep_deprivation()
void talker_character::set_sleep_deprivation (int amount) override virtual
Reimplemented from talker.
Definition at line 906 of file talker_character.cpp.
 {
     me_chr->set_sleep_deprivation( amount );
 }
References me_chr, and Character::set_sleep_deprivation().
set_sleepiness()
void talker_character::set_sleepiness (int amount) override virtual
Reimplemented from talker.
Definition at line 801 of file talker_character.cpp.
 {
     me_chr->set_sleepiness( amount );
 }
References me_chr, and Character::set_sleepiness().
set_spell_exp()
void talker_character::set_spell_exp (const spell_id & sp, int new_level) override virtual
Reimplemented from talker.
Definition at line 413 of file talker_character.cpp.
 {
     me_chr->magic->set_spell_exp( sp, new_level, me_chr );
 }
References Character::magic, and me_chr.
set_spell_level()
void talker_character::set_spell_level (const spell_id & sp, int new_level) override virtual
Reimplemented from talker.
Definition at line 408 of file talker_character.cpp.
 {
     me_chr->magic->set_spell_level( sp, new_level, me_chr );
 }
References Character::magic, and me_chr.
set_stamina()
void talker_character::set_stamina (int amount) override virtual
Reimplemented from talker.
Definition at line 896 of file talker_character.cpp.
 {
     me_chr->set_stamina( amount );
 }
References me_chr, and Character::set_stamina().
set_stim()
void talker_character::set_stim (int amount) override virtual
Reimplemented from talker.
Definition at line 876 of file talker_character.cpp.
 {
     me_chr->set_stim( amount );
 }
References me_chr, and Character::set_stim().
set_stored_kcal()
void talker_character::set_stored_kcal (int value) override virtual
Reimplemented from talker.
Definition at line 679 of file talker_character.cpp.
 {
     me_chr->set_stored_kcal( value );
 }
References me_chr, Character::set_stored_kcal(), and talker::value().
set_str_bonus()
void talker_character::set_str_bonus (int value) override virtual
Reimplemented from talker.
Definition at line 152 of file talker_character.cpp.
 {
     me_chr->mod_str_bonus( value );
 }
References me_chr, Character::mod_str_bonus(), and talker::value().
set_str_max()
void talker_character::set_str_max (int value) override virtual
Reimplemented from talker.
Definition at line 132 of file talker_character.cpp.
 {
     me_chr->str_max = value;
 }
References me_chr, Character::str_max, and talker::value().
set_thirst()
void talker_character::set_thirst (int value) override virtual
Reimplemented from talker.
Definition at line 683 of file talker_character.cpp.
 {
     me_chr->set_thirst( value );
 }
References me_chr, Character::set_thirst(), and talker::value().
set_value()
void talker_character::set_value (const std::string & var_name, const std::string & value) override virtual
Reimplemented from talker.
Definition at line 480 of file talker_character.cpp.
 {
     me_chr->set_value( var_name, value );
 }
References me_chr, Creature::set_value(), and talker::value().
shout()
void talker_character::shout (const std::string & speech = "", bool order = false) override virtual
Reimplemented from talker.
Definition at line 693 of file talker_character.cpp.
 {
     me_chr->shout( speech, order );
 }
References me_chr, Character::shout(), and speech.
train_proficiency_for()
void talker_character::train_proficiency_for (const proficiency_id & prof, int turns) override virtual
Reimplemented from talker.
Definition at line 433 of file talker_character.cpp.
 {
     me_chr->practice_proficiency( prof, time_duration::from_seconds<int>( turns ) );
 }
References me_chr, and Character::practice_proficiency().
unset_mutation()
void talker_character::unset_mutation (const trait_id & old_trait) override virtual
Reimplemented from talker.
Definition at line 264 of file talker_character.cpp.
 {
     me_chr->unset_mutation( old_trait );
 }
References me_chr, and Character::unset_mutation().
use_amount()
std::list< item > talker_character::use_amount (const itype_id & item_name, int count) override virtual
Reimplemented from talker.
Definition at line 529 of file talker_character.cpp.
 {
     return me_chr->use_amount( item_name, count );
 }
References tname::item_name(), me_chr, and Character::use_amount().
use_charges() [1/2]
std::list< item > talker_character::use_charges (const itype_id & item_name, int count) override virtual
Reimplemented from talker.
Definition at line 514 of file talker_character.cpp.
 {
     return me_chr->use_charges( item_name, count );
 }
References tname::item_name(), me_chr, and Character::use_charges().
use_charges() [2/2]
std::list< item > talker_character::use_charges (const itype_id & item_name, int count, bool in_tools) override virtual
Reimplemented from talker.
Definition at line 519 of file talker_character.cpp.
 {
     if( !in_tools ) {
         return me_chr->use_charges( item_name, count );
     } else {
         return me_chr->use_charges( item_name, count, -1, return_true<item>, in_tools );
     }
 }
References tname::item_name(), me_chr, and Character::use_charges().
Member Data Documentation
me_chr
Character* talker_character::me_chr protected
Definition at line 313 of file talker_character.h.
Referenced by activate_mutation(), add_bionic(), add_effect(), add_morale(), attack_target(), talker_avatar::buy_monster(), deactivate_mutation(), die(), forget_martial_art(), forget_recipe(), get_all_body_parts(), get_character(), get_creature(), get_is_alive(), get_part_hp_cur(), get_part_hp_max(), get_random_technique(), i_add(), i_add_or_drop(), items_with(), learn_martial_art(), learn_recipe(), mod_daily_health(), mod_focus(), mod_pain(), mutate(), mutate_category(), mutate_towards(), talker_avatar::parse_mod(), remove_bionic(), remove_effect(), remove_items_with(), remove_morale(), remove_value(), set_addiction_turns(), set_age(), set_all_parts_hp_cur(), set_dex_bonus(), set_dex_max(), set_height(), set_int_bonus(), set_int_max(), set_kill_xp(), set_mana_cur(), set_mutation(), set_pain(), set_part_hp_cur(), set_per_bonus(), set_per_max(), set_pkill(), set_pos(), set_power_cur(), set_proficiency_practiced_time(), set_rad(), set_skill_exp(), set_skill_level(), set_sleep_deprivation(), set_sleepiness(), set_spell_exp(), set_spell_level(), set_stamina(), set_stim(), set_stored_kcal(), set_str_bonus(), set_str_max(), set_thirst(), set_value(), shout(), talker_avatar::talker_avatar(), talker_character(), talker_npc::talker_npc(), train_proficiency_for(), talker_avatar::trial_chance_mod(), unset_mutation(), use_amount(), and use_charges().
The documentation for this class was generated from the following files:
src/talker_character.h
src/talker_character.cpp