Cataclysm DDA: basecamp Class Reference
basecamp Class Reference
#include <basecamp.h>
Public Member Functions
basecamp ()
basecamp (const std::string &name_, const tripoint_abs_omt &omt_pos)
basecamp (const std::string &name_, const tripoint &bb_pos_, const std::vector< point > &directions_, const std::map< point, expansion_data > &expansions_)
bool is_valid () const
int board_x () const
int board_y () const
tripoint_abs_omt camp_omt_pos () const
const std::string & camp_name () const
tripoint get_bb_pos () const
void validate_bb_pos (const tripoint &new_abs_pos)
void set_bb_pos (const tripoint &new_abs_pos)
void set_by_radio (bool access_by_radio)
std::string board_name () const
void faction_display (const catacurses::window &fac_w, int width) const
void set_name (const std::string &new_name)
void query_new_name (bool force=false)
void abandon_camp ()
void scan_pseudo_items ()
void add_expansion (const std::string &terrain, const tripoint_abs_omt &new_pos)
void add_expansion (const std::string &bldg, const tripoint_abs_omt &new_pos, const point &dir)
void define_camp (const tripoint_abs_omt &p, std::string_view camp_type)
std::string expansion_tab (const point &dir) const
bool point_within_camp (const tripoint_abs_omt &p) const
bool has_provides (const std::string &req, const expansion_data &e_data, int level=0) const
bool has_provides (const std::string &req, const std::optional< point > &dir=std::nullopt, int level=0) const
void update_resources (const std::string &bldg)
void update_provides (const std::string &bldg, expansion_data &e_data)
void update_in_progress (const std::string &bldg, const point &dir)
std::string next_upgrade (const point &dir, int offset=1) const
Returns the name of the building the current building dir upgrades into, "null" if there isn't one.
std::vector< basecamp_upgrade > available_upgrades (const point &dir)
int recruit_evaluation () const
int recruit_evaluation (int &sbase, int &sexpansions, int &sfaction, int &sbonus) const
bool validate_sort_points ()
expansion_data parse_expansion (std::string_view terrain, const tripoint_abs_omt &new_pos)
bool set_sort_points ()
Invokes the zone manager and validates that the necessary sort zones exist.
nutrients camp_food_supply (nutrients &change)
Changes the faction food supply by change, returns the amount of kcal+vitamins consumed, a negative total food supply hurts morale Handles vitamin consumption when only a kcal value is supplied.
nutrients camp_food_supply (int change)
Constructs a new nutrients struct in place and forwards it. Passed argument should be in kilocalories.
nutrients camp_food_supply (time_duration work, float exertion_level=NO_EXERCISE)
Calculates raw kcal cost from duration of work and exercise, then forwards it to above.
void feed_workers (const std::vector< std::reference_wrapper< Character >> &workers, nutrients food, bool is_player_meal=false)
Evenly distributes the actual consumed food from a work project to the workers assigned to it.
void feed_workers (Character &worker, nutrients food, bool is_player_meal=false)
Helper, forwards to above.
void player_eats_meal ()
item make_fake_food (const nutrients &to_use) const
bool distribute_food ()
Takes all the food from the camp_food zone and increases the faction food_supply.
std::string name_display_of (const mission_id &miss_id)
void handle_hide_mission (const point &dir)
void handle_reveal_mission (const point &dir)
bool has_water () const
int camp_food_supply_days (float exertion_level) const
The number of days the current camp supplies lasts at the given exertion level.
int time_to_food (time_duration work, float exertion_level=NO_EXERCISE) const
Returns the total charges of food time_duration work costs.
int camp_discipline (int change=0) const
Changes the faction respect for you by change, returns respect.
int camp_morale (int change=0) const
Changes the faction opinion for you by change, returns opinion.
std::map< recipe_id, translation > recipe_deck (const point &dir) const
std::map< recipe_id, translation > recipe_deck (const std::string &bldg) const
int recipe_batch_max (const recipe &making) const
void form_crafting_inventory ()
void form_crafting_inventory (map &target_map)
std::list< item > use_charges (const itype_id &fake_id, int &quantity)
void search_results (int skill, const item_group_id &, int attempts, int difficulty)
spawn items or corpses based on search attempts
void hunting_results (int skill, const mission_id &miss_id, int attempts, int difficulty)
spawn items or corpses based on search attempts
void make_corpse_from_group (const std::vector< MonsterGroupResult > &group)
const tripoint_abs_ms & get_dumping_spot () const
const std::vector< tripoint_abs_ms > & get_liquid_dumping_spot () const
void set_dumping_spot (const tripoint_abs_ms &spot)
void set_liquid_dumping_spot (const std::vector< tripoint_abs_ms > &liquid_dumps)
void place_results (const item &result)
void add_available_recipes (mission_data &mission_key, mission_kind kind, const point &dir, const std::map< recipe_id, translation > &craft_recipes)
std::string recruit_description (int npc_count) const
std::string gathering_description ()
Provides a "guess" for some of the things your gatherers will return with to upgrade the camp.
std::string farm_description (const tripoint_abs_omt &farm_pos, size_t &plots_count, farm_ops operation)
Returns a string for the number of plants that are harvestable, plots ready to plant, and ground that needs tilling.
std::string craft_description (const recipe_id &itm)
Returns the description of a camp crafting options.
void get_available_missions (mission_data &mission_key, map &here)
void get_available_missions_by_dir (mission_data &mission_key, const point &dir)
void choose_new_leader ()
void reset_camp_workers ()
comp_list get_mission_workers (const mission_id &miss_id, bool contains=false)
bool handle_mission (const ui_mission_id &miss_id)
npc_ptr start_mission (const mission_id &miss_id, time_duration duration, bool must_feed, const std::string &desc, bool group, const std::vector< item * > &equipment, const skill_id &skill_tested, int skill_level, float exertion_level)
generic mission start function that wraps individual mission
npc_ptr start_mission (const mission_id &miss_id, time_duration duration, bool must_feed, const std::string &desc, bool group, const std::vector< item * > &equipment, float exertion_level, const std::map< skill_id, int > &required_skills={})
comp_list start_multi_mission (const mission_id &miss_id, bool must_feed, const std::string &desc, const skill_id &skill_tested, int skill_level)
comp_list start_multi_mission (const mission_id &miss_id, bool must_feed, const std::string &desc, const std::map< skill_id, int > &required_skills={})
void start_upgrade (const mission_id &miss_id)
std::string om_upgrade_description (const std::string &bldg, const mapgen_arguments &, bool trunc=false) const
Returns the description for the recipe of the next building bldg.
void start_menial_labor ()
void worker_assignment_ui ()
void job_assignment_ui ()
void start_crafting (const std::string &type, const mission_id &miss_id)
void start_cut_logs (const mission_id &miss_id, float exertion_level)
Called when a companion is sent to cut logs.
void start_clearcut (const mission_id &miss_id, float exertion_level)
void start_setup_hide_site (const mission_id &miss_id, float exertion_level)
void start_relay_hide_site (const mission_id &miss_id, float exertion_level)
void start_fortifications (const mission_id &miss_id, float exertion_level)
Called when a companion is sent to start fortifications.
bool common_salt_water_pipe_construction (const mission_id &miss_id, expansion_salt_water_pipe *pipe, int segment_number)
Called when a companion is sent to start digging down salt water pipes.
void start_salt_water_pipe (const mission_id &miss_id)
void continue_salt_water_pipe (const mission_id &miss_id)
void start_combat_mission (const mission_id &miss_id, float exertion_level)
void start_farm_op (const tripoint_abs_omt &omt_tgt, const mission_id &miss_id, float exertion_level)
drop_locations give_basecamp_equipment (inventory_filter_preset &preset, const std::string &title, const std::string &column_title, const std::string &msg_empty) const
Display items listed in equipment to let the player pick what to give the departing NPC, loops until quit or empty.
drop_locations give_equipment (Character *pc, const inventory_filter_preset &preset, const std::string &msg, const std::string &title, units::volume &total_volume, units::mass &total_mass)
drop_locations get_equipment (tinymap *target_bay, const tripoint &target, Character *pc, const inventory_filter_preset &preset, const std::string &msg, const std::string &title, units::volume &total_volume, units::mass &total_mass)
npc_ptr companion_choose_return (const mission_id &miss_id, time_duration min_duration)
called to select a companion to return to the base
npc_ptr companion_crafting_choose_return (const mission_id &miss_id)
void finish_return (npc &comp, bool fixed_time, const std::string &return_msg, const std::string &skill, int difficulty, bool cancel=false)
called with a companion comp who is not the camp manager, finishes updating their skills, consuming food, and returning them to the base.
npc_ptr mission_return (const mission_id &miss_id, time_duration min_duration, bool fixed_time, const std::string &return_msg, const std::string &skill, int difficulty)
a wrapper function for companion_choose_return and finish_return
npc_ptr crafting_mission_return (const mission_id &miss_id, const std::string &return_msg, const std::string &skill, int difficulty)
npc_ptr emergency_recall (const mission_id &miss_id)
select a companion for any mission to return to base
bool upgrade_return (const mission_id &miss_id)
Called to close upgrade missions, miss is the name of the mission id and dir is the direction of the location to be upgraded.
bool survey_field_return (const mission_id &miss_id)
Choose which expansion slot to check for field conversion.
bool survey_return (const mission_id &miss_id)
Choose which expansion you should start, called when a survey mission is completed.
bool menial_return (const mission_id &miss_id)
bool gathering_return (const mission_id &miss_id, time_duration min_time)
Called when a companion completes a gathering task mission.
void recruit_return (const mission_id &miss_id, int score)
bool farm_return (const mission_id &miss_id, const tripoint_abs_omt &omt_tgt)
Perform any mix of the three farm tasks.
void fortifications_return (const mission_id &miss_id)
bool salt_water_pipe_swamp_return (const mission_id &miss_id, const comp_list &npc_list)
bool salt_water_pipe_return (const mission_id &miss_id, const comp_list &npc_list)
void combat_mission_return (const mission_id &miss_id)
void validate_assignees ()
void add_assignee (character_id id)
void remove_assignee (character_id id)
std::vector< npc_ptr > get_npcs_assigned ()
void hide_mission (ui_mission_id id)
void reveal_mission (ui_mission_id id)
bool is_hidden (ui_mission_id id)
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
void load_data (const std::string &data)
const std::vector< const zone_data * > & get_storage_zone () const
void set_storage_zone (const std::vector< const zone_data * > &zones)
const std::unordered_set< tripoint_abs_ms > & get_storage_tiles () const
void set_storage_tiles (const std::unordered_set< tripoint_abs_ms > &tiles)
void form_storage_zones (map &here, const tripoint_abs_ms &abspos)
map & get_camp_map ()
void unload_camp_map ()
void set_owner (faction_id new_owner)
faction_id get_owner ()
Public Attributes
std::vector< point > directions
std::vector< std::vector< ui_mission_id > > hidden_missions
std::vector< tripoint_abs_omt > fortifications
std::vector< expansion_salt_water_pipe * > salt_water_pipes
std::string name
Private Member Functions
faction * fac () const
void reset_camp_resources (map &here)
void add_resource (const itype_id &camp_resource)
Private Attributes
faction_id owner = faction_id::NULL_ID()
tripoint_abs_omt omt_pos
std::vector< npc_ptr > assigned_npcs
tripoint bb_pos
std::map< point, expansion_data > expansions
comp_list camp_workers
basecamp_map camp_map
tripoint_abs_ms dumping_spot
std::vector< tripoint_abs_ms > liquid_dumping_spots
std::vector< const zone_data * > storage_zones
std::unordered_set< tripoint_abs_ms > src_set
std::set< itype_id > fuel_types
std::vector< basecamp_fuel > fuels
std::vector< basecamp_resource > resources
std::vector< std::vector< ui_mission_id > > temp_ui_mission_keys
inventory _inv
bool by_radio = false
Friends
class basecamp_action_components
Detailed Description
Definition at line 158 of file basecamp.h.
Constructor & Destructor Documentation
basecamp() [1/3]
basecamp::basecamp () default
basecamp() [2/3]
basecamp::basecamp (const std::string & name_, const tripoint_abs_omt & omt_pos)
Definition at line 127 of file basecamp.cpp.
                                                                             : name( name_ ),
     omt_pos( omt_pos_ )
 {
 }
basecamp() [3/3]
basecamp::basecamp (const std::string & name_, const tripoint & bb_pos_, const std::vector< point > & directions_, const std::map< point, expansion_data > & expansions_)
Definition at line 132 of file basecamp.cpp.
     : directions( directions_ ), name( name_ ), bb_pos( bb_pos_ ), expansions( expansions_ )
 {
 }
Member Function Documentation
abandon_camp()
void basecamp::abandon_camp ()
Definition at line 2158 of file faction_camp.cpp.
 {
     validate_assignees();
     for( npc_ptr &guy : overmap_buffer.get_companion_mission_npcs( 10 ) ) {
         npc_companion_mission c_mission = guy->get_companion_mission();
         if( c_mission.role_id != base_camps::id ) {
             continue;
         }
         const std::string return_msg = _( "responds to the emergency recall" );
         finish_return( *guy, false, return_msg, skill_menial.str(), 0, true );
     }
     for( npc_ptr &guy : get_npcs_assigned() ) {
         talk_function::stop_guard( *guy );
     }
     overmap_buffer.remove_camp( *this );
     map &here = get_map();
     const tripoint sm_pos = omt_to_sm_copy( omt_pos.raw() );
     const tripoint ms_pos = sm_to_ms_copy( sm_pos );
     // We cannot use bb_pos here, because bb_pos may be {0,0,0} if you haven't examined the bulletin board on camp ever.
     // here.remove_submap_camp( here.getlocal( bb_pos ) );
     here.remove_submap_camp( here.getlocal( ms_pos ) );
     add_msg( m_info, _( "You abandon %s." ), name );
 }
References _, add_msg(), finish_return(), overmapbuffer::get_companion_mission_npcs(), get_map(), get_npcs_assigned(), map::getlocal(), base_camps::id, m_info, name, omt_pos, omt_to_sm_copy(), overmap_buffer, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), overmapbuffer::remove_camp(), map::remove_submap_camp(), npc_companion_mission::role_id, skill_menial, sm_to_ms_copy(), talk_function::stop_guard(), string_id< T >::str(), and validate_assignees().
Referenced by talk_function::abandon_camp(), and handle_mission().
add_assignee()
void basecamp::add_assignee (character_id id)
Definition at line 499 of file basecamp.cpp.
 {
     npc_ptr npc_to_add = overmap_buffer.find_npc( id );
     if( !npc_to_add ) {
         debugmsg( "cant find npc to assign to basecamp, on the overmap_buffer" );
         return;
     }
     npc_to_add->assigned_camp = omt_pos;
     assigned_npcs.push_back( npc_to_add );
 }
References assigned_npcs, debugmsg, overmapbuffer::find_npc(), omt_pos, and overmap_buffer.
Referenced by talk_function::assign_camp().
add_available_recipes()
void basecamp::add_available_recipes (mission_data & mission_key, mission_kind kind, const point & dir, const std::map< recipe_id, translation > & craft_recipes)
Definition at line 771 of file faction_camp.cpp.
 {
     const std::string dir_abbr = base_camps::all_directions.at( dir ).bracket_abbr.translated();
     for( const auto &recipe_data : craft_recipes ) {
         const mission_id miss_id = {kind, recipe_data.first.str(), {}, dir};
         const std::string &title_e = dir_abbr + recipe_data.second;
         const std::string &entry = craft_description( recipe_data.first );
         const recipe &recp = recipe_data.first.obj();
         bool craftable = recp.deduped_requirements().can_make_with_inventory(
                              _inv, recp.get_component_filter() );
         mission_key.add_start( miss_id, title_e, entry, craftable );
     }
 }
References _inv, mission_data::add_start(), base_camps::all_directions, deduped_requirement_data::can_make_with_inventory(), craft_description(), recipe::deduped_requirements(), and recipe::get_component_filter().
Referenced by get_available_missions_by_dir().
add_expansion() [1/2]
void basecamp::add_expansion (const std::string & bldg, const tripoint_abs_omt & new_pos, const point & dir)
Definition at line 177 of file basecamp.cpp.
 {
     expansion_data e;
     e.type = base_camps::faction_decode( bldg );
     e.cur_level = -1;
     e.pos = new_pos;
     expansions[ dir ] = e;
     directions.push_back( dir );
     update_provides( bldg, expansions[ dir ] );
     update_resources( bldg );
 }
References expansion_data::cur_level, directions, expansions, base_camps::faction_decode(), expansion_data::pos, expansion_data::type, update_provides(), and update_resources().
add_expansion() [2/2]
void basecamp::add_expansion (const std::string & terrain, const tripoint_abs_omt & new_pos)
Definition at line 165 of file basecamp.cpp.
 {
     if( terrain.find( base_camps::prefix ) == std::string::npos ) {
         return;
     }
     const point dir = talk_function::om_simple_dir( omt_pos, new_pos );
     expansions[ dir ] = parse_expansion( terrain, new_pos );
     update_provides( terrain, expansions[ dir ] );
     directions.push_back( dir );
 }
References directions, expansions, talk_function::om_simple_dir(), omt_pos, parse_expansion(), base_camps::prefix, terrain, and update_provides().
Referenced by define_camp(), and survey_return().
add_resource()
void basecamp::add_resource (const itype_id & camp_resource) private
Definition at line 407 of file basecamp.cpp.
 {
     basecamp_resource bcp_r;
     bcp_r.fake_id = camp_resource;
     item camp_item( bcp_r.fake_id, calendar::turn_zero );
     bcp_r.ammo_id = camp_item.ammo_default();
     resources.emplace_back( bcp_r );
     fuel_types.insert( bcp_r.ammo_id );
 }
References item::ammo_default(), basecamp_resource::ammo_id, basecamp_resource::fake_id, fuel_types, resources, and calendar::turn_zero.
Referenced by reset_camp_resources(), and update_resources().
available_upgrades()
std::vector< basecamp_upgrade > basecamp::available_upgrades (const point & dir)
Definition at line 322 of file basecamp.cpp.
 {
     std::vector<basecamp_upgrade> ret_data;
     auto e = expansions.find( dir );
     if( e != expansions.end() ) {
         expansion_data &e_data = e->second;
         for( const recipe *recp_p : recipe_dict.all_blueprints() ) {
             const recipe &recp = *recp_p;
             const std::string &bldg = recp.result().str();
             // skip buildings that are completed
             if( e_data.provides.find( bldg ) != e_data.provides.end() ) {
                 continue;
             }
             // skip building that have unmet requirements
             size_t needed_requires = recp.blueprint_requires().size();
             size_t met_requires = 0;
             for( const auto &bp_require : recp.blueprint_requires() ) {
                 if( e_data.provides.find( bp_require.first ) == e_data.provides.end() ) {
                     break;
                 }
                 if( e_data.provides[bp_require.first] < bp_require.second ) {
                     break;
                 }
                 met_requires += 1;
             }
             if( met_requires < needed_requires ) {
                 continue;
             }
             bool should_display = true;
             bool in_progress = false;
             for( const auto &bp_exclude : recp.blueprint_excludes() ) {
                 // skip buildings that are excluded by previous builds
                 if( e_data.provides.find( bp_exclude.first ) != e_data.provides.end() ) {
                     if( e_data.provides[bp_exclude.first] >= bp_exclude.second ) {
                         should_display = false;
                         break;
                     }
                 }
                 // track buildings that are currently being built
                 if( e_data.in_progress.find( bp_exclude.first ) != e_data.in_progress.end() ) {
                     if( e_data.in_progress[bp_exclude.first] >= bp_exclude.second ) {
                         in_progress = true;
                         break;
                     }
                 }
             }
             if( !should_display ) {
                 continue;
             }
             if( recp.blueprint_build_reqs().reqs_by_parameters.empty() ) {
                 debugmsg( "blueprint recipe %s lacked any blueprint_build_reqs", recp.result().str() );
             }
             for( const std::pair<const mapgen_arguments, build_reqs> &args_and_reqs :
                  recp.blueprint_build_reqs().reqs_by_parameters ) {
                 const mapgen_arguments &args = args_and_reqs.first;
                 const requirement_data &reqs = args_and_reqs.second.consolidated_reqs;
                 bool can_make =
                     reqs.can_make_with_inventory( _inv, recp.get_component_filter(), 1 );
                 ret_data.push_back( { bldg, args, recp.blueprint_name(), can_make, in_progress } );
             }
         }
     }
     return ret_data;
 }
References _inv, recipe_dictionary::all_blueprints(), recipe::blueprint_build_reqs(), recipe::blueprint_excludes(), recipe::blueprint_name(), recipe::blueprint_requires(), requirement_data::can_make_with_inventory(), debugmsg, expansions, recipe::get_component_filter(), expansion_data::in_progress, expansion_data::provides, recipe_dict, parameterized_build_reqs::reqs_by_parameters, recipe::result(), and string_id< T >::str().
Referenced by get_available_missions_by_dir(), and name_display_of().
board_name()
std::string basecamp::board_name () const
Definition at line 139 of file basecamp.cpp.
 {
     //~ Name of a basecamp
     return string_format( _( "%s Board" ), name );
 }
References _, name, and string_format().
board_x()
int basecamp::board_x () const inline
Definition at line 169 of file basecamp.h.
{
             return bb_pos.x;
         }
References bb_pos, and tripoint::x.
board_y()
int basecamp::board_y () const inline
Definition at line 172 of file basecamp.h.
{
             return bb_pos.y;
         }
References bb_pos, and tripoint::y.
camp_discipline()
int basecamp::camp_discipline (int change = 0) const
Changes the faction respect for you by change, returns respect.
Definition at line 5952 of file faction_camp.cpp.
 {
     fac()->respects_u += change;
     return fac()->respects_u;
 }
References fac(), and faction_template::respects_u.
Referenced by recruit_evaluation().
camp_food_supply() [1/3]
nutrients basecamp::camp_food_supply (int change)
Constructs a new nutrients struct in place and forwards it. Passed argument should be in kilocalories.
Definition at line 5556 of file faction_camp.cpp.
 {
     nutrients added;
     // Kcal to calories
     added.calories = ( change * 1000 );
     return camp_food_supply( added );
 }
References nutrients::calories, and camp_food_supply().
camp_food_supply() [2/3]
nutrients basecamp::camp_food_supply (nutrients & change)
Changes the faction food supply by change, returns the amount of kcal+vitamins consumed, a negative total food supply hurts morale Handles vitamin consumption when only a kcal value is supplied.
Definition at line 5522 of file faction_camp.cpp.
 {
     nutrients consumed;
     if( change.calories < 0 && change.vitamins().empty() && fac()->food_supply.calories > 0 ) {
         // We've been passed a raw kcal value, we should also consume a proportional amount of vitamins
         // Kcals are used as a proxy to consume vitamins.
         // e.g. if you have a larder with 10k kcal, 100 vitamin A, 200 vitamin B then consuming 1000 kcal will
         // consume 10 vitamin A and *20* vitamin B. In other words, we assume the vitamins are uniformly distributed with the kcals
         // This isn't a perfect assumption but it's a necessary one to abstract away the food items themselves
         double percent_consumed = std::abs( static_cast<double>( change.calories ) ) /
                                   fac()->food_supply.calories;
         consumed = fac()->food_supply;
         if( std::abs( change.calories ) > fac()->food_supply.calories ) {
             //Whoops, we don't have enough food. Empty the larder! No crumb shall go un-eaten!
             fac()->food_supply += change;
             faction *yours = get_player_character().get_faction();
             if( fac()->id == yours->id ) {
                 yours->likes_u += fac()->food_supply.kcal() / 1250;
                 yours->respects_u += fac()->food_supply.kcal() / 625;
                 yours->trusts_u += fac()->food_supply.kcal() / 625;
             }
             fac()->food_supply *= 0;
             return consumed;
         }
         consumed *= percent_consumed;
         // Subtraction since we use the absolute value of change's calories to get the percent
         fac()->food_supply -= consumed;
         return consumed;
     }
     fac()->food_supply += change;
     consumed = change;
     return consumed;
 }
References abs(), nutrients::calories, fac(), faction_template::food_supply, Character::get_faction(), get_player_character(), faction_template::id, nutrients::kcal(), faction_template::likes_u, faction_template::respects_u, faction_template::trusts_u, and nutrients::vitamins().
Referenced by camp_food_supply(), npc::consume_food_from_camp(), distribute_food(), feed_workers(), finish_return(), player_eats_meal(), recruit_return(), start_mission(), and start_multi_mission().
camp_food_supply() [3/3]
nutrients basecamp::camp_food_supply (time_duration work, float exertion_level = NO_EXERCISE)
Calculates raw kcal cost from duration of work and exercise, then forwards it to above.
Definition at line 5564 of file faction_camp.cpp.
 {
     return camp_food_supply( -time_to_food( work, exertion_level ) );
 }
References camp_food_supply(), and time_to_food().
camp_food_supply_days()
int basecamp::camp_food_supply_days (float exertion_level) const
The number of days the current camp supplies lasts at the given exertion level.
Definition at line 5517 of file faction_camp.cpp.
 {
     return fac()->food_supply.kcal() / time_to_food( 24_hours, exertion_level );
 }
References fac(), faction_template::food_supply, nutrients::kcal(), and time_to_food().
Referenced by get_available_missions(), and recruit_return().
camp_morale()
int basecamp::camp_morale (int change = 0) const
Changes the faction opinion for you by change, returns opinion.
Definition at line 5958 of file faction_camp.cpp.
 {
     fac()->likes_u += change;
     return fac()->likes_u;
 }
References fac(), and faction_template::likes_u.
Referenced by recruit_evaluation().
camp_name()
const std::string& basecamp::camp_name () const inline
Definition at line 178 of file basecamp.h.
{
             return name;
         }
References name.
Referenced by talk_function::assign_camp(), and npc::faction_display().
camp_omt_pos()
tripoint_abs_omt basecamp::camp_omt_pos () const inline
Definition at line 175 of file basecamp.h.
{
             return omt_pos;
         }
References omt_pos.
Referenced by overmapbuffer::add_camp(), iexamine::bulletin_board(), faction_display(), talk_function::goto_location(), overmapbuffer::has_camp(), overmapbuffer::remove_camp(), and game::validate_camps().
choose_new_leader()
void basecamp::choose_new_leader ()
Definition at line 1601 of file faction_camp.cpp.
 {
     // This is ugly, but dialogue vars are stored as strings, even if they hold data for times.
     time_point last_succession_time = time_point::from_turn( std::stof(
                                           get_player_character().get_value( var_timer_time_of_last_succession ) ) );
     time_duration succession_cooldown = time_duration::from_turns( std::stof(
                                             get_globals().get_global_value(
                                                     var_time_between_succession ) ) );
     time_point next_succession_chance = last_succession_time + succession_cooldown;
     int current_time_int = to_seconds<int>( calendar::turn - calendar::turn_zero );
     if( next_succession_chance >= calendar::turn ) {
         popup( _( "It's too early for that.  A new leader can be chosen in %s." ),
                to_string( next_succession_chance - calendar::turn ) );
         return;
     }
     std::vector<std::string> choices;
     int choice = 0;
     choices.emplace_back _( "autocratic" );
     choices.emplace_back _( "sortition" );
     choices.emplace_back _( "democratic" );
     choice = uilist( _( "Choose how the new leader will be determined." ), choices );
     if( choice < 0 || static_cast<size_t>( choice ) >= choices.size() ) {
         popup( _( "You choose to wait" ) );
         return;
     }
     // Autocratic
     if( choice == 0 ) {
         if( !query_yn(
                 _( "As an experienced leader, only you know what will be required of future leaders.  You will choose.\n\nIs this acceptable?" ) ) ) {
             return;
         }
         get_avatar().control_npc_menu( false );
         // Possible to exit menu and not choose a *new* leader. However this doesn't reset global timer. 100% on purpose, since you are "choosing" yourself.
         get_player_character().set_value( var_timer_time_of_last_succession,
                                           std::to_string( current_time_int ) );
     }
     // Vector of pairs containing a pointer to an NPC and their modified social score
     std::vector<std::pair<shared_ptr_fast<npc>, int>> followers;
     // You is still a nullptr! We never want to actually call the first value, this will crash.
     shared_ptr_fast<npc> you;
     followers.emplace_back( you, rng( 0, 5 ) +
                             rng( 0, get_avatar().get_skill_level( skill_speech ) * 2 ) );
     int charnum = 0;
     for( const character_id &elem : g->get_follower_list() ) {
         shared_ptr_fast<npc> follower = overmap_buffer.find_npc( elem );
         if( follower ) {
             // Yes this is a very barren representation of who gets elected in a democracy. Too bad!
             int popularity = rng( 0, 5 ) + rng( 0, follower->get_skill_level( skill_speech ) * 2 );
             followers.emplace_back( follower, popularity );
             charnum++;
         }
     }
     // Sortition
     if( choice == 1 ) {
         if( !query_yn(
                 _( "You will allow fate to choose the next leader.  Whether it's by dice, drawing straws, or picking names out of a hat, it will be purely random.\n\nIs this acceptable?" ) ) ) {
             return;
         }
         int selected = rng( 0, charnum );
         // Vector starts at 0, we inserted 'you' first, 0 will always be 'you' pre-sort (that's why we don't sort unless democracy is called)
         if( selected == 0 ) {
             popup( _( "Fate calls for you to remain in your role as leader for now." ) );
             get_player_character().set_value( var_timer_time_of_last_succession,
                                               std::to_string( current_time_int ) );
             return;
         }
         npc_ptr chosen = followers.at( selected ).first;
         popup( _( "Fate chooses %s to lead your faction." ), chosen->get_name() );
         get_avatar().control_npc( *chosen, false );
         return;
     }
     // Democratic
     if( choice == 2 ) {
         if( !query_yn(
                 _( "A leader can only lead those willing to follow.  Everyone must get a say in choosing the new leader.\n\nIs this acceptable?" ) ) ) {
             return;
         }
         std::sort( followers.begin(), followers.end(), []( const auto & x, const auto & y ) {
             return x.second > y.second;
         } );
         npc_ptr elected = followers.at( 0 ).first;
         // you == nullptr
         if( elected == nullptr ) {
             popup( _( "You win the election!" ) );
             get_player_character().set_value( var_timer_time_of_last_succession,
                                               std::to_string( current_time_int ) );
             return;
         }
         popup( _( "%1$s wins the election with a popularity of %2$s!  The runner-up had a popularity of %3$s." ),
                elected->get_name(), followers.at( 0 ).second, followers.at( 1 ).second );
         get_avatar().control_npc( *elected, false );
     }
 }
References _, avatar::control_npc(), avatar::control_npc_menu(), overmapbuffer::find_npc(), time_point::from_turn(), time_duration::from_turns(), g, get_avatar(), get_globals(), get_player_character(), overmap_buffer, popup(), query_yn(), rng(), Creature::set_value(), skill_speech, to_string(), calendar::turn, calendar::turn_zero, var_time_between_succession, and var_timer_time_of_last_succession.
Referenced by handle_mission().
combat_mission_return()
void basecamp::combat_mission_return (const mission_id & miss_id)
Definition at line 4385 of file faction_camp.cpp.
 {
     npc_ptr comp = companion_choose_return( miss_id, 3_hours );
     if( comp != nullptr ) {
         bool patrolling = miss_id.id == Camp_Combat_Patrol;
         comp_list patrol;
         npc_ptr guy = overmap_buffer.find_npc( comp->getID() );
         if( guy ) {
             patrol.push_back( guy );
         }
         for( tripoint_abs_omt &pt : comp->companion_mission_points ) {
             const oter_id &omt_ref = overmap_buffer.ter( pt );
             int swim = comp->get_skill_level( skill_swimming );
             if( is_river( omt_ref ) && swim < 2 ) {
                 if( swim == 0 ) {
                     popup( _( "Your companion hit a river and didn't know how to swim" ) );
                 } else {
                     popup( _( "Your companion hit a river and didn't know how to swim well "
                               "enough to cross" ) );
                 }
                 break;
             }
             comp->death_drops = false;
             bool outcome = talk_function::companion_om_combat_check( patrol, pt, patrolling );
             comp->death_drops = true;
             if( outcome ) {
                 overmap_buffer.reveal( pt, 2 );
             } else if( comp->is_dead() ) {
                 popup( _( "%s didn't return from patrol" ), comp->get_name() );
                 comp->place_corpse( pt );
                 overmap_buffer.add_note( pt, "DEAD NPC" );
                 overmap_buffer.remove_npc( comp->getID() );
                 return;
             }
         }
         const std::string msg = _( "returns from patrol" );
         finish_return( *comp, true, msg, skill_combat.str(), 4 );
     }
 }
References _, overmapbuffer::add_note(), Camp_Combat_Patrol, companion_choose_return(), talk_function::companion_om_combat_check(), overmapbuffer::find_npc(), finish_return(), mission_id::id, is_river(), overmap_buffer, popup(), overmapbuffer::remove_npc(), overmapbuffer::reveal(), skill_combat, skill_swimming, string_id< T >::str(), avatar_action::swim(), and overmapbuffer::ter().
Referenced by handle_mission().
common_salt_water_pipe_construction()
bool basecamp::common_salt_water_pipe_construction (const mission_id & miss_id, expansion_salt_water_pipe * pipe, int segment_number)
Called when a companion is sent to start digging down salt water pipes.
Definition at line 3114 of file faction_camp.cpp.
 {
     const recipe &making = recipe_id(
                                miss_id.parameters ).obj(); //  Actually a template recipe that we'll rotate and mirror as required.
     int remaining_segments = pipe->segments.size() - 1;
     if( segment_number == 0 ) {
         if( !query_yn( _( "Number of additional sessions required: %i" ), remaining_segments ) ) {
             return false;
         }
     }
     mapgen_arguments arg;  //  Created with a default value.
     basecamp_action_components components( making, arg, 1, *this );
     if( !components.choose_components() ) {
         return false;
     }
     comp_list comp;
     if( segment_number == 0 ) {
         comp = start_multi_mission( miss_id, true,
                                     _( "Start constructing salt water pipes" ),
                                     making.required_skills );
         point connection_dir = pipe->connection_direction;
         const int segment_number = 0;
         point next_construction_direction;
         if( segment_number == pipe->segments.size() - 1 ) {
             next_construction_direction = { -connection_dir.x, -connection_dir.y };
         } else {
             next_construction_direction = { pipe->segments[segment_number + 1].point.x() - pipe->segments[segment_number].point.x(),
                                             pipe->segments[segment_number + 1].point.y() - pipe->segments[segment_number].point.y()
                                           };
         }
         bool orthogonal = true;
         bool mirror_horizontal = false;
         bool mirror_vertical = false;
         int rotation = 0;
         salt_water_pipe_orientation_adjustment( next_construction_direction, orthogonal, mirror_vertical,
                                                 mirror_horizontal, rotation );
         if( orthogonal ) {
             const update_mapgen_id id{ faction_expansion_salt_water_pipe_swamp_N };
             apply_construction_marker( id, pipe->segments[segment_number].point,
                                        miss_id.mapgen_args, mirror_horizontal,
                                        mirror_vertical, rotation, true );
         } else {
             const update_mapgen_id id{ faction_expansion_salt_water_pipe_swamp_NE };
             apply_construction_marker( id, pipe->segments[segment_number].point,
                                        miss_id.mapgen_args, mirror_horizontal,
                                        mirror_vertical, rotation, true );
         }
     } else {
         comp = start_multi_mission( miss_id, true,
                                     _( "Continue constructing salt water pipes" ),
                                     making.required_skills );
         point connection_dir = pipe->connection_direction;
         const point previous_construction_direction = { pipe->segments[segment_number - 1].point.x() - pipe->segments[segment_number].point.x(),
                                                         pipe->segments[segment_number - 1].point.y() - pipe->segments[segment_number].point.y()
                                                       };
         point next_construction_direction;
         if( segment_number == static_cast<int>( pipe->segments.size() - 1 ) ) {
             next_construction_direction = { -connection_dir.x, -connection_dir.y };
         } else {
             next_construction_direction = { pipe->segments[segment_number + 1].point.x() - pipe->segments[segment_number].point.x(),
                                             pipe->segments[segment_number + 1].point.y() - pipe->segments[segment_number].point.y()
                                           };
         }
         bool orthogonal = true;
         bool mirror_horizontal = false;
         bool mirror_vertical = false;
         int rotation = 0;
         salt_water_pipe_orientation_adjustment( previous_construction_direction, orthogonal,
                                                 mirror_vertical, mirror_horizontal, rotation );
         if( orthogonal ) {
             const update_mapgen_id id{ faction_expansion_salt_water_pipe_N };
             apply_construction_marker( id, pipe->segments[segment_number].point,
                                        miss_id.mapgen_args, mirror_horizontal,
                                        mirror_vertical, rotation, true );
         } else {
             const update_mapgen_id id{ faction_expansion_salt_water_pipe_NE };
             apply_construction_marker( id, pipe->segments[segment_number].point,
                                        miss_id.mapgen_args, mirror_horizontal,
                                        mirror_vertical, rotation, true );
         }
         salt_water_pipe_orientation_adjustment( next_construction_direction, orthogonal, mirror_vertical,
                                                 mirror_horizontal, rotation );
         if( orthogonal ) {
             const update_mapgen_id id{ faction_expansion_salt_water_pipe_N };
             apply_construction_marker( id, pipe->segments[segment_number].point,
                                        miss_id.mapgen_args, mirror_horizontal,
                                        mirror_vertical, rotation, true );
         } else {
             const update_mapgen_id id{ faction_expansion_salt_water_pipe_NE };
             apply_construction_marker( id, pipe->segments[segment_number].point,
                                        miss_id.mapgen_args, mirror_horizontal,
                                        mirror_vertical, rotation, true );
         }
     }
     if( !comp.empty() ) {
         components.consume_components();
         update_in_progress( miss_id.parameters, miss_id.dir.value() );  // Dir will always have a value
         pipe->segments[segment_number].started = true;
     }
     return !comp.empty();
 }
References _, apply_construction_marker(), basecamp_action_components::choose_components(), expansion_salt_water_pipe::connection_direction, basecamp_action_components::consume_components(), mission_id::dir, faction_expansion_salt_water_pipe_N, faction_expansion_salt_water_pipe_NE, faction_expansion_salt_water_pipe_swamp_N, faction_expansion_salt_water_pipe_swamp_NE, mission_id::mapgen_args, string_id< T >::obj(), mission_id::parameters, query_yn(), recipe::required_skills, salt_water_pipe_orientation_adjustment(), expansion_salt_water_pipe::segments, start_multi_mission(), update_in_progress(), point::x, and point::y.
Referenced by continue_salt_water_pipe(), and start_salt_water_pipe().
companion_choose_return()
npc_ptr basecamp::companion_choose_return (const mission_id & miss_id, time_duration min_duration)
called to select a companion to return to the base
Definition at line 3748 of file faction_camp.cpp.
 {
     return talk_function::companion_choose_return( omt_pos, base_camps::id, miss_id,
             calendar::turn - min_duration );
 }
References talk_function::companion_choose_return(), base_camps::id, omt_pos, and calendar::turn.
Referenced by combat_mission_return(), fortifications_return(), gathering_return(), mission_return(), survey_field_return(), and survey_return().
companion_crafting_choose_return()
npc_ptr basecamp::companion_crafting_choose_return (const mission_id & miss_id)
Definition at line 3755 of file faction_camp.cpp.
 {
     comp_list preliminary_npc_list = get_mission_workers( miss_id, true );
     comp_list npc_list;
     std::map<std::string, comp_list> lists = companion_per_recipe_building_type( preliminary_npc_list );
     const std::string bldg = recipe_group::get_building_of_recipe( miss_id.parameters );
     for( const npc_ptr &comp : lists[bldg] ) {
         if( comp->companion_mission_time_ret < calendar::turn ) {
             npc_list.emplace_back( comp );
         }
     }
     return talk_function::companion_choose_return( npc_list );
 }
References talk_function::companion_choose_return(), npc::companion_mission_time_ret, companion_per_recipe_building_type(), recipe_group::get_building_of_recipe(), get_mission_workers(), mission_id::parameters, and calendar::turn.
Referenced by crafting_mission_return().
continue_salt_water_pipe()
void basecamp::continue_salt_water_pipe (const mission_id & miss_id)
Definition at line 3426 of file faction_camp.cpp.
 {
     const point dir = miss_id.dir.value();  //  Dir will always have a value
     const recipe &making = recipe_id( miss_id.parameters ).obj();
     expansion_salt_water_pipe *pipe = nullptr;
     bool pipe_is_new = true;
     for( expansion_salt_water_pipe *element : salt_water_pipes ) {
         if( element->expansion == dir ) {
             pipe = element;
             pipe_is_new = false;
             break;
         }
     }
     if( pipe_is_new ) {
         debugmsg( "Trying to continue construction of a salt water pipe that isn't in progress" );
         return;
     }
     const int segment_number = salt_water_pipe_segment_of( making );
     if( segment_number == -1 ) {
         return;
     }
     if( pipe->segments[segment_number].finished ) {
         debugmsg( "Trying to construct a segment that's already constructed" );
         return;
     }
     common_salt_water_pipe_construction( miss_id, pipe, segment_number );
 }
References common_salt_water_pipe_construction(), debugmsg, mission_id::dir, string_id< T >::obj(), mission_id::parameters, salt_water_pipe_segment_of(), salt_water_pipes, and expansion_salt_water_pipe::segments.
Referenced by start_upgrade().
craft_description()
std::string basecamp::craft_description (const recipe_id & itm)
Returns the description of a camp crafting options.
converts fire charges to charcoal, allows dark crafting
Definition at line 5364 of file faction_camp.cpp.
 {
     const recipe &making = itm.obj();
     std::vector<std::string> component_print_buffer;
     int pane = FULL_SCREEN_WIDTH;
     const requirement_data &req = making.simple_requirements();
     auto tools = req.get_folded_tools_list( pane, c_white, _inv, 1 );
     auto comps = req.get_folded_components_list( pane, c_white, _inv,
                  making.get_component_filter(), 1 );
     component_print_buffer.insert( component_print_buffer.end(), tools.begin(), tools.end() );
     component_print_buffer.insert( component_print_buffer.end(), comps.begin(), comps.end() );
     std::string comp;
     for( auto &elem : component_print_buffer ) {
         str_append( comp, elem, "\n" );
     }
     comp = string_format( _( "Skill used: %s\nDifficulty: %d\n%s\nTime: %s\nCalories per craft: %s\n" ),
                           making.skill_used.obj().name(), making.difficulty, comp,
                           to_string( base_camps::to_workdays( making.batch_duration( get_player_character() ) ) ),
                           time_to_food( base_camps::to_workdays( making.batch_duration( get_player_character() ) ),
                                         itm.obj().exertion_level() ) );
     return comp;
 }
References _, _inv, recipe::batch_duration(), c_white, recipe::difficulty, recipe::exertion_level(), FULL_SCREEN_WIDTH, recipe::get_component_filter(), requirement_data::get_folded_components_list(), requirement_data::get_folded_tools_list(), get_player_character(), Skill::name(), string_id< T >::obj(), recipe::simple_requirements(), recipe::skill_used, str_append(), string_format(), time_to_food(), to_string(), and base_camps::to_workdays().
Referenced by add_available_recipes().
crafting_mission_return()
npc_ptr basecamp::crafting_mission_return (const mission_id & miss_id, const std::string & return_msg, const std::string & skill, int difficulty)
Definition at line 3830 of file faction_camp.cpp.
 {
     npc_ptr comp = companion_crafting_choose_return( miss_id );
     if( comp != nullptr ) {
         finish_return( *comp, false, return_msg, skill, difficulty );
     }
     return comp;
 }
References companion_crafting_choose_return(), and finish_return().
Referenced by handle_mission().
define_camp()
void basecamp::define_camp (const tripoint_abs_omt & p, std::string_view camp_type)
Definition at line 190 of file basecamp.cpp.
 {
     query_new_name( true );
     omt_pos = p;
     const oter_id &omt_ref = overmap_buffer.ter( omt_pos );
     // purging the regions guarantees all entries will start with faction_base_
     for( const std::pair<std::string, tripoint_abs_omt> &expansion :
          talk_function::om_building_region( omt_pos, 1, true ) ) {
         add_expansion( expansion.first, expansion.second );
     }
     const std::string om_cur = omt_ref.id().c_str();
     if( om_cur.find( base_camps::prefix ) == std::string::npos ) {
         expansion_data e;
         e.type = base_camps::faction_decode( camp_type );
         e.cur_level = -1;
         e.pos = omt_pos;
         expansions[base_camps::base_dir] = e;
         const std::string direction = oter_get_rotation_string( omt_ref );
         const oter_id bcid( direction.empty() ? "faction_base_camp_0" : "faction_base_camp_new_0" +
                             direction );
         overmap_buffer.ter_set( omt_pos, bcid );
         update_provides( base_camps::faction_encode_abs( e, 0 ),
                          expansions[base_camps::base_dir] );
     } else {
         expansions[base_camps::base_dir] = parse_expansion( om_cur, omt_pos );
     }
 }
References add_expansion(), base_camps::base_dir, string_id< T >::c_str(), expansion_data::cur_level, expansions, base_camps::faction_decode(), base_camps::faction_encode_abs(), int_id< T >::id(), talk_function::om_building_region(), omt_pos, oter_get_rotation_string(), overmap_buffer, parse_expansion(), expansion_data::pos, base_camps::prefix, query_new_name(), overmapbuffer::ter(), overmapbuffer::ter_set(), expansion_data::type, and update_provides().
Referenced by get_basecamp().
deserialize()
void basecamp::deserialize (const JsonObject & data)
Definition at line 4365 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     if( !data.read( "owner", owner ) ) {
         faction_id your_fac( "your_followers" );
         owner = your_fac;
     }
     data.read( "name", name );
     data.read( "pos", omt_pos );
     data.read( "bb_pos", bb_pos );
     data.read( "dumping_spot", dumping_spot );
     data.read( "liquid_dumping_spots", liquid_dumping_spots );
     for( int tab_num = base_camps::TAB_MAIN; tab_num <= base_camps::TAB_NW; tab_num++ ) {
         std::vector<ui_mission_id> temp;
         hidden_missions.push_back( temp );
     }
     int tab_num = base_camps::TAB_MAIN;
     for( JsonObject list : data.get_array( "hidden_missions" ) ) {
         list.allow_omitted_members();
         for( JsonObject miss_id_json : list.get_array( "dir" ) ) {
             miss_id_json.allow_omitted_members();
             ui_mission_id miss_id;
             miss_id_json.read( "mission_id", miss_id.id );
             miss_id.ret = false;
             hidden_missions[tab_num].push_back( miss_id );
         }
         tab_num++;
     }
     for( JsonObject edata : data.get_array( "expansions" ) ) {
         edata.allow_omitted_members();
         expansion_data e;
         point dir;
         if( edata.has_string( "dir" ) ) {
             // old save compatibility
             const std::string dir_id = edata.get_string( "dir" );
             dir = base_camps::direction_from_id( dir_id );
         } else {
             edata.read( "dir", dir );
         }
         edata.read( "type", e.type );
         if( edata.has_int( "cur_level" ) ) {
             edata.read( "cur_level", e.cur_level );
         }
         if( edata.has_array( "provides" ) ) {
             e.cur_level = -1;
             for( JsonObject provide_data : edata.get_array( "provides" ) ) {
                 provide_data.allow_omitted_members();
                 std::string id = provide_data.get_string( "id" );
                 int amount = provide_data.get_int( "amount" );
                 e.provides[ id ] = amount;
             }
         }
         // in case of save corruption, sanity check provides from expansions
         const std::string &initial_provide = base_camps::faction_encode_abs( e, 0 );
         if( e.provides.find( initial_provide ) == e.provides.end() ) {
             e.provides[ initial_provide ] = 1;
         }
         for( JsonObject in_progress_data : edata.get_array( "in_progress" ) ) {
             in_progress_data.allow_omitted_members();
             std::string id = in_progress_data.get_string( "id" );
             int amount = in_progress_data.get_int( "amount" );
             e.in_progress[ id ] = amount;
         }
         edata.read( "pos", e.pos );
         expansions[ dir ] = e;
         if( dir != base_camps::base_dir ) {
             directions.push_back( dir );
         }
     }
     for( JsonObject edata : data.get_array( "fortifications" ) ) {
         edata.allow_omitted_members();
         tripoint_abs_omt restore_pos;
         edata.read( "pos", restore_pos );
         fortifications.push_back( restore_pos );
     }
     for( JsonObject edata : data.get_array( "salt_water_pipes" ) ) {
         edata.allow_omitted_members();
         expansion_salt_water_pipe *pipe = new expansion_salt_water_pipe;
         edata.read( "expansion", pipe->expansion );
         edata.read( "connection_direction", pipe->connection_direction );
         for( JsonObject seg : edata.get_array( "segments" ) ) {
             seg.allow_omitted_members();
             expansion_salt_water_pipe_segment segment;
             seg.read( "point", segment.point );
             seg.read( "started", segment.started );
             seg.read( "finished", segment.finished );
             pipe->segments.push_back( segment );
         }
         salt_water_pipes.push_back( pipe );
     }
 }
References base_camps::base_dir, expansion_salt_water_pipe::connection_direction, expansion_data::cur_level, item_pocket::data, base_camps::direction_from_id(), expansion_salt_water_pipe::expansion, base_camps::faction_encode_abs(), JsonObject::get_array(), base_camps::id, ui_mission_id::id, expansion_data::in_progress, om_direction::name(), expansion_data::pos, expansion_data::provides, ui_mission_id::ret, coords::seg, expansion_salt_water_pipe::segments, base_camps::TAB_MAIN, base_camps::TAB_NW, temp, expansion_data::type, and your_fac().
Referenced by overmap::unserialize().
distribute_food()
bool basecamp::distribute_food ()
Takes all the food from the camp_food zone and increases the faction food_supply.
Definition at line 5676 of file faction_camp.cpp.
 {
     if( !validate_sort_points() ) {
         popup( _( "You do not have a camp food zone.  Aborting" ) );
         return false;
     }
     map &here = get_map();
     zone_manager &mgr = zone_manager::get_manager();
     if( here.check_vehicle_zones( here.get_abs_sub().z() ) ) {
         mgr.cache_vzones();
     }
     const tripoint_abs_ms &abspos = get_dumping_spot();
     const std::unordered_set<tripoint_abs_ms> &z_food =
         mgr.get_near( zone_type_CAMP_FOOD, abspos, 60 );
     double quick_rot = 0.6 + ( has_provides( "pantry" ) ? 0.1 : 0 );
     double slow_rot = 0.8 + ( has_provides( "pantry" ) ? 0.05 : 0 );
     nutrients nutrients_to_add;
     const auto rot_multip = [&]( const item & it, item * const container ) {
         if( !it.goes_bad() ) {
             return 1.;
         }
         float spoil_mod = 1.0f;
         if( container ) {
             if( item_pocket *const pocket = container->contained_where( it ) ) {
                 spoil_mod = pocket->spoil_multiplier();
             }
         }
         // Container seals and prevents any spoilage.
         if( spoil_mod == 0 ) {
             return 1.;
         }
         // @TODO: this does not handle fridges or things like root cellar, but maybe it shouldn't.
         const time_duration rots_in = ( it.get_shelf_life() - it.get_rot() ) / spoil_mod;
         if( rots_in >= 5_days ) {
             return 1.;
         } else if( rots_in >= 2_days ) {
             return slow_rot;
         } else {
             return quick_rot;
         }
     };
     const auto consume_non_recursive = [&]( item & it, item * const container ) {
         if( !it.is_comestible() ) {
             return false;
         }
         // Always reject in-progress craft item
         if( it.is_craft() ) {
             return false;
         }
         // Stuff like butchery refuse and other disgusting stuff
         if( it.get_comestible_fun() < -6 ) {
             return false;
         }
         if( it.has_flag( flag_INEDIBLE ) ) {
             return false;
         }
         if( it.rotten() ) {
             return false;
         }
         nutrients from_it = getAverageJoe().compute_effective_nutrients( it ) * it.count();
         // Do this multiplication separately to make sure we're using the *= operator with double argument..
         from_it *= rot_multip( it, container );
         nutrients_to_add += from_it;
         if( from_it.kcal() <= 0 ) {
             // can happen if calories is low and rot is high.
             return false;
         }
         return true;
     };
     // Returns whether the item should be removed from the map.
     const auto consume = [&]( item & it, item * const container ) {
         if( it.is_food_container() ) {
             std::vector<item *> to_remove;
             it.visit_items( [&]( item * content, item * parent ) {
                 if( consume_non_recursive( *content, parent ) ) {
                     to_remove.push_back( content );
                     return VisitResponse::SKIP;
                 }
                 return VisitResponse::NEXT;
             } );
             if( to_remove.empty() ) {
                 return false;
             }
             for( item *const food : to_remove ) {
                 it.remove_item( *food );
             }
             it.on_contents_changed();
             return false;
         }
         return consume_non_recursive( it, container );
     };
     for( const tripoint_abs_ms &p_food_stock_abs : z_food ) {
         // @FIXME: this will not handle zones in vehicle
         const tripoint p_food_stock = here.getlocal( p_food_stock_abs );
         map_stack items = here.i_at( p_food_stock );
         for( auto iter = items.begin(); iter != items.end(); ) {
             if( consume( *iter, nullptr ) ) {
                 iter = items.erase( iter );
             } else {
                 ++iter;
             }
         }
     }
     if( nutrients_to_add.kcal() <= 0 ) {
         popup( _( "No suitable items are located at the drop points" ) );
         return false;
     }
     popup( _( "You distribute %d kcal worth of food to your companions." ), nutrients_to_add.kcal() );
     camp_food_supply( nutrients_to_add );
     return true;
 }
References _, item_stack::begin(), zone_manager::cache_vzones(), camp_food_supply(), map::check_vehicle_zones(), Character::compute_effective_nutrients(), game_menus::inv::consume(), item::count(), item_stack::end(), map_stack::erase(), flag_INEDIBLE, map::get_abs_sub(), item::get_comestible_fun(), get_dumping_spot(), zone_manager::get_manager(), get_map(), zone_manager::get_near(), item::get_rot(), item::get_shelf_life(), getAverageJoe(), map::getlocal(), item::goes_bad(), item::has_flag(), has_provides(), map::i_at(), item::is_comestible(), item::is_craft(), item::is_food_container(), nutrients::kcal(), NEXT, item::on_contents_changed(), popup(), visitable::remove_item(), item::rotten(), SKIP, validate_sort_points(), item::visit_items(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and zone_type_CAMP_FOOD.
Referenced by handle_mission().
emergency_recall()
npc_ptr basecamp::emergency_recall (const mission_id & miss_id)
select a companion for any mission to return to base
Definition at line 3840 of file faction_camp.cpp.
 {
     npc_ptr comp = talk_function::companion_choose_return( omt_pos, base_camps::id, miss_id,
                    calendar::turn - 24_hours, false );
     if( comp != nullptr ) {
         //  Special handing for camp upgrades. If multiple companions are assigned, the remaining time
         //  is divided between the remaining workers. Note that this logic relies on there being only
         //  a single instance of each construction active, and thus all workers assigned to that
         //  blueprint are on the same mission. Won't work with e.g. crafting, as different instances of
         //  the same crafting mission may be in various stages of completion concurrently.
         if( comp->get_companion_mission().miss_id.id == Camp_Upgrade ) {
             comp_list npc_list = get_mission_workers( comp->get_companion_mission().miss_id );
             if( npc_list.size() > 1 ) {
                 time_duration remaining_time = comp->companion_mission_time_ret - calendar::turn;
                 if( remaining_time > time_duration::from_turns( 0 ) ) {
                     remaining_time = remaining_time * npc_list.size() / ( npc_list.size() - 1 );
                 }
                 for( npc_ptr &worker : npc_list ) {
                     if( worker != comp ) {
                         worker->companion_mission_time_ret = calendar::turn + remaining_time;
                     }
                 }
             }
         }
         const std::string return_msg = _( "responds to the emergency recall" );
         finish_return( *comp, false, return_msg, skill_menial.str(), 0, true );
     }
     return comp;
 }
References _, Camp_Upgrade, talk_function::companion_choose_return(), finish_return(), time_duration::from_turns(), get_mission_workers(), base_camps::id, omt_pos, skill_menial, string_id< T >::str(), and calendar::turn.
Referenced by handle_mission().
expansion_tab()
std::string basecamp::expansion_tab (const point & dir) const
Definition at line 834 of file basecamp.cpp.
 {
     if( dir == base_camps::base_dir ) {
         return _( "Base Missions" );
     }
     const auto &expansion_types = recipe_group::get_recipes_by_id( "all_faction_base_expansions" );
     const auto &e = expansions.find( dir );
     if( e != expansions.end() ) {
         recipe_id id( base_camps::faction_encode_abs( e->second, 0 ) );
         const auto e_type = expansion_types.find( id );
         if( e_type != expansion_types.end() ) {
             return e_type->second + _( "Expansion" );
         }
     }
     return _( "Empty Expansion" );
 }
References _, base_camps::base_dir, expansions, base_camps::faction_encode_abs(), recipe_group::get_recipes_by_id(), and base_camps::id.
Referenced by talk_function::name_mission_tabs().
fac()
faction * basecamp::fac () const private
Definition at line 664 of file faction_camp.cpp.
 {
     return g->faction_manager_ptr->get( owner );
 }
References g, and owner.
Referenced by camp_discipline(), camp_food_supply(), camp_food_supply_days(), camp_morale(), finish_return(), get_available_missions(), get_available_missions_by_dir(), player_eats_meal(), recipe_batch_max(), recruit_evaluation(), set_owner(), start_menial_labor(), start_mission(), and start_multi_mission().
faction_display()
void basecamp::faction_display (const catacurses::window & fac_w, int width) const
Definition at line 560 of file faction.cpp.
 {
     int y = 2;
     const nc_color col = c_white;
     Character &player_character = get_player_character();
     const tripoint_abs_omt player_abspos = player_character.global_omt_location();
     tripoint_abs_omt camp_pos = camp_omt_pos();
     std::string direction = direction_name( direction_from( player_abspos, camp_pos ) );
     mvwprintz( fac_w, point( width, ++y ), c_light_gray, _( "Press enter to rename this camp" ) );
     if( direction != "center" ) {
         mvwprintz( fac_w, point( width, ++y ), c_light_gray, _( "Direction: to the " ) + direction );
     }
     mvwprintz( fac_w, point( width, ++y ), col, _( "Location: %s" ), camp_pos.to_string() );
     faction *yours = player_character.get_faction();
     std::string food_text = string_format( _( "Food Supply: %s %d kilocalories" ),
                                            yours->food_supply_text(), yours->food_supply.kcal() );
     nc_color food_col = yours->food_supply_color();
     mvwprintz( fac_w, point( width, ++y ), food_col, food_text );
     std::pair<nc_color, std::string> vitamins = yours->vitamin_stores( vitamin_type::VITAMIN );
     mvwprintz( fac_w, point( width, ++y ), vitamins.first, _( "Worst vitamin:" ) + vitamins.second );
     std::pair<nc_color, std::string> toxins = yours->vitamin_stores( vitamin_type::TOXIN );
     mvwprintz( fac_w, point( width, ++y ), toxins.first, _( "Worst toxin:" ) + toxins.second );
     std::string bldg = next_upgrade( base_camps::base_dir, 1 );
     std::string bldg_full = _( "Next Upgrade: " ) + bldg;
     mvwprintz( fac_w, point( width, ++y ), col, bldg_full );
 }
References _, base_camps::base_dir, c_light_gray, c_white, camp_omt_pos(), direction_from(), direction_name(), faction_template::food_supply, faction::food_supply_color(), faction::food_supply_text(), Character::get_faction(), get_player_character(), Creature::global_omt_location(), nutrients::kcal(), mvwprintz(), next_upgrade(), point, string_format(), coords::coord_point_base< Point >::to_string(), TOXIN, VITAMIN, and faction::vitamin_stores().
Referenced by faction_manager::display().
farm_description()
std::string basecamp::farm_description (const tripoint_abs_omt & farm_pos, size_t & plots_count, farm_ops operation)
Returns a string for the number of plants that are harvestable, plots ready to plant, and ground that needs tilling.
Definition at line 5492 of file faction_camp.cpp.
 {
     std::pair<size_t, std::string> farm_data = farm_action( farm_pos, operation );
     std::string entry;
     plots_count = farm_data.first;
     switch( operation ) {
         case farm_ops::harvest:
             entry += _( "Harvestable: " ) + std::to_string( plots_count ) + "\n" + farm_data.second;
             break;
         case farm_ops::plant:
             entry += _( "Ready for Planting: " ) + std::to_string( plots_count ) + "\n";
             break;
         case farm_ops::plow:
             entry += _( "Needs Plowing: " ) + std::to_string( plots_count ) + "\n";
             break;
         default:
             debugmsg( "Farm operations called with no operation" );
             break;
     }
     return entry;
 }
References _, debugmsg, farm_action(), harvest, plant, plow, and to_string().
Referenced by get_available_missions_by_dir().
farm_return()
bool basecamp::farm_return (const mission_id & miss_id, const tripoint_abs_omt & omt_tgt)
Perform any mix of the three farm tasks.
Parameters
task
omt_tgt the overmap pos3 of the farm_ops
op whether to plow, plant, or harvest
Definition at line 4595 of file faction_camp.cpp.
 {
     farm_ops op;
     if( miss_id.id == Camp_Plow ) {
         op = farm_ops::plow;
     } else if( miss_id.id == Camp_Plant ) {
         op = farm_ops::plant;
     } else if( miss_id.id == Camp_Harvest ) {
         op = farm_ops::harvest;
     } else {
         debugmsg( "Farm operations called with no matching operation" );
         return false;
     }
     const std::string msg = _( "returns from working your fields" );
     npc_ptr comp = talk_function::companion_choose_return( omt_pos, base_camps::id, miss_id,
                    calendar::before_time_starts );
     if( comp == nullptr ) {
         return false;
     }
     farm_action( omt_tgt, op, comp );
     Character &player_character = get_player_character();
     //Give any seeds the NPC didn't use back to you.
     for( size_t i = 0; i < comp->companion_mission_inv.size(); i++ ) {
         for( const item &it : comp->companion_mission_inv.const_stack( i ) ) {
             if( it.charges > 0 ) {
                 player_character.i_add( it );
             }
         }
     }
     finish_return( *comp, true, msg, skill_survival.str(), 2 );
     return true;
 }
References _, calendar::before_time_starts, Camp_Harvest, Camp_Plant, Camp_Plow, talk_function::companion_choose_return(), debugmsg, farm_action(), finish_return(), get_player_character(), harvest, Character::i_add(), base_camps::id, mission_id::id, omt_pos, plant, plow, skill_survival, and string_id< T >::str().
Referenced by handle_mission().
feed_workers() [1/2]
void basecamp::feed_workers (Character & worker, nutrients food, bool is_player_meal = false)
Helper, forwards to above.
Definition at line 5637 of file faction_camp.cpp.
 {
     std::vector<std::reference_wrapper <Character>> work_party;
     work_party.emplace_back( worker );
     feed_workers( work_party, std::move( food ), is_player_meal );
 }
References feed_workers().
feed_workers() [2/2]
void basecamp::feed_workers (const std::vector< std::reference_wrapper< Character >> & workers, nutrients food, bool is_player_meal = false)
Evenly distributes the actual consumed food from a work project to the workers assigned to it.
Definition at line 5569 of file faction_camp.cpp.
 {
     const int num_workers = workers.size();
     if( num_workers == 0 ) {
         debugmsg( "feed_workers called without any workers to feed!" );
         return;
     }
     if( !is_player_meal && get_option<bool>( "NO_NPC_FOOD" ) ) {
         return;
     }
     // Split the food into equal sized portions.
     food /= num_workers;
     for( const auto &worker_reference : workers ) {
         Character &worker = worker_reference.get();
         item food_item = make_fake_food( food );
         // Handle allergies and other stuff
         bool query_player = !worker.is_npc();
         const ret_val<edible_rating> rating = worker.will_eat( food_item, query_player );
         switch( rating.value() ) {
             case EDIBLE:
                 // I'd like to use consume_activity_actor here, but our little trick with make_fake_food() requires that the
                 // item be consumed immediately.
                 worker.consume( food_item );
                 break;
             case TOO_FULL:
                 worker.add_msg_player_or_npc( m_neutral,
                                               _( "You are too full to eat right now, and put the meal back into storage." ),
                                               _( "<npcname> is too full to eat right now, and puts the meal back into storage." ) );
                 camp_food_supply( food );
                 break;
             case INEDIBLE:
             case INEDIBLE_MUTATION:
                 debugmsg( "Always-edible food somehow inedible, please report this error." );
                 camp_food_supply( food );
                 break;
             case ALLERGY:
                 worker.add_msg_if_npc( m_bad,
                                        _( "%s takes one look at the food and declines, explaining they're allergic." ),
                                        worker.get_name() );
                 camp_food_supply( food );
                 break;
             case ALLERGY_WEAK:
                 worker.add_msg_if_npc( m_bad,
                                        _( "%s takes a bite but spits it out.  It seems something in the food disagrees with them." ),
                                        worker.get_name() );
                 camp_food_supply( food );
                 break;
             case CANNIBALISM:
                 worker.add_msg_if_npc( m_bad,
                                        _( "%s thanks you for the meal, but when they see what's in the meal their attitude suddenly changes!" ),
                                        worker.get_name() );
                 if( worker.is_npc() ) {
                     worker.as_npc()->mutiny();
                 }
                 // Food specifically does not go back in the larder.
                 break;
             case PARASITES:
             // None of these should ever happen.
             case ROTTEN:
             case NAUSEA:
             case NO_TOOL:
                 break;
         }
     }
 }
References _, Creature::add_msg_if_npc(), Character::add_msg_player_or_npc(), ALLERGY, ALLERGY_WEAK, Creature::as_npc(), camp_food_supply(), CANNIBALISM, Character::consume(), debugmsg, EDIBLE, Character::get_name(), INEDIBLE, INEDIBLE_MUTATION, Character::is_npc(), m_bad, m_neutral, make_fake_food(), npc::mutiny(), NAUSEA, NO_TOOL, PARASITES, ROTTEN, TOO_FULL, ret_val< T >::value(), and Character::will_eat().
Referenced by feed_workers(), finish_return(), player_eats_meal(), start_mission(), and start_multi_mission().
finish_return()
void basecamp::finish_return (npc & comp, bool fixed_time, const std::string & return_msg, const std::string & skill, int difficulty, bool cancel = false)
called with a companion comp who is not the camp manager, finishes updating their skills, consuming food, and returning them to the base.
Definition at line 3771 of file faction_camp.cpp.
 {
     popup( "%s %s", comp.get_name(), return_msg );
     // this is the time the mission was expected to take, or did take for fixed time missions
     time_duration reserve_time = comp.companion_mission_time_ret - comp.companion_mission_time;
     time_duration mission_time = reserve_time;
     if( !fixed_time ) {
         mission_time = calendar::turn - comp.companion_mission_time;
     }
     if( !cancel ) {
         talk_function::companion_skill_trainer( comp, skill, mission_time, difficulty );
     }
     // Missions that are not fixed_time pay their food costs at the end, instead of up-front.
     int need_food = time_to_food( mission_time - reserve_time );
     if( fac()->food_supply.kcal() < need_food ) {
         popup( _( "Your companion seems disappointed that your pantry is empty" ) );
     }
     // movng all the logic from talk_function::companion return here instead of polluting
     // mission_companion
     comp.reset_companion_mission();
     comp.companion_mission_time = calendar::before_time_starts;
     comp.companion_mission_time_ret = calendar::before_time_starts;
     if( !cancel ) {
         for( size_t i = 0; i < comp.companion_mission_inv.size(); i++ ) {
             for( const item &it : comp.companion_mission_inv.const_stack( i ) ) {
                 if( !it.count_by_charges() || it.charges > 0 ) {
                     place_results( it );
                 }
             }
         }
     }
     comp.companion_mission_inv.clear();
     comp.companion_mission_points.clear();
     // npc *may* be active, or not if outside the reality bubble
     g->reload_npcs();
     validate_assignees();
     // Missions that are not fixed_time can try to draw more food than is in the food supply
     feed_workers( comp, camp_food_supply( -need_food ) );
     if( has_water() ) {
         comp.set_thirst( 0 );
     }
     comp.set_sleepiness( 0 );
     comp.set_sleep_deprivation( 0 );
 }
References _, calendar::before_time_starts, camp_food_supply(), cancel, inventory::clear(), npc::companion_mission_inv, npc::companion_mission_points, npc::companion_mission_time, npc::companion_mission_time_ret, talk_function::companion_skill_trainer(), inventory::const_stack(), fac(), feed_workers(), g, Character::get_name(), has_water(), need_food, place_results(), popup(), npc::reset_companion_mission(), Character::set_sleep_deprivation(), Character::set_sleepiness(), Character::set_thirst(), inventory::size(), time_to_food(), calendar::turn, and validate_assignees().
Referenced by abandon_camp(), combat_mission_return(), crafting_mission_return(), emergency_recall(), farm_return(), fortifications_return(), gathering_return(), mission_return(), salt_water_pipe_return(), salt_water_pipe_swamp_return(), survey_field_return(), survey_return(), and upgrade_return().
form_crafting_inventory() [1/2]
void basecamp::form_crafting_inventory ()
Definition at line 826 of file basecamp.cpp.
 {
     map &here = get_camp_map();
     form_crafting_inventory( here );
     here.save();
 }
References get_camp_map(), and map::save().
Referenced by reset_camp_resources().
form_crafting_inventory() [2/2]
void basecamp::form_crafting_inventory (map & target_map)
Definition at line 708 of file basecamp.cpp.
 {
     _inv.clear();
     zone_manager &mgr = zone_manager::get_manager();
     map &here = get_map();
     if( here.check_vehicle_zones( here.get_abs_sub().z() ) ) {
         mgr.cache_vzones();
     }
     if( !src_set.empty() ) {
         _inv.form_from_zone( target_map, src_set, nullptr, false );
     }
     /*
      * something of a hack: add the resources we know the camp has
      * the hacky part is that we're adding resources based on the camp's flags, which were
      * generated based on upgrade missions, instead of having resources added when the
      * map changes
      */
     // make sure the array is empty
     fuels.clear();
     for( const itype_id &fuel_id : fuel_types ) {
         basecamp_fuel bcp_f;
         bcp_f.ammo_id = fuel_id;
         fuels.emplace_back( bcp_f );
     }
     // find available fuel
     for( const tripoint_abs_ms &abs_ms_pt : src_set ) {
         const tripoint &pt = target_map.getlocal( abs_ms_pt );
         if( target_map.accessible_items( pt ) ) {
             for( const item &i : target_map.i_at( pt ) ) {
                 for( basecamp_fuel &bcp_f : fuels ) {
                     if( bcp_f.ammo_id == i.typeId() ) {
                         bcp_f.available += i.charges;
                         break;
                     }
                 }
             }
         }
     }
     for( basecamp_resource &bcp_r : resources ) {
         bcp_r.consumed = 0;
         item camp_item( bcp_r.fake_id, calendar::turn_zero );
         camp_item.set_flag( STATIC( flag_id( "PSEUDO" ) ) );
         if( !bcp_r.ammo_id.is_null() ) {
             for( basecamp_fuel &bcp_f : fuels ) {
                 if( bcp_f.ammo_id == bcp_r.ammo_id ) {
                     if( bcp_f.available > 0 ) {
                         bcp_r.available = bcp_f.available;
                         camp_item = camp_item.ammo_set( bcp_f.ammo_id, bcp_f.available );
                     }
                     break;
                 }
             }
         }
         _inv.add_item( camp_item );
     }
     //  We're potentially adding the same item multiple times if present in multiple expansions,
     //  but we're already that with the resources above. The resources are stored in expansions
     //  rather than in a common pool to allow them to apply only to their respective expansion
     //  in the future.
     for( auto &expansion : expansions ) {
         for( itype_id &it : expansion.second.available_pseudo_items ) {
             item camp_item = item( it );
             if( camp_item.is_magazine() ) {
                 for( basecamp_fuel &bcp_f : fuels ) {
                     if( camp_item.can_reload_with( item( bcp_f.ammo_id ), false ) ) {
                         if( bcp_f.available > 0 ) {
                             camp_item = camp_item.ammo_set( bcp_f.ammo_id, bcp_f.available );
                         }
                         break;
                     }
                 }
             }
             _inv.add_item( camp_item );
         }
     }
 }
References _inv, map::accessible_items(), inventory::add_item(), basecamp_fuel::ammo_id, item::ammo_set(), zone_manager::cache_vzones(), item::can_reload_with(), map::check_vehicle_zones(), inventory::clear(), expansions, flag_id, inventory::form_from_zone(), fuel_types, fuels, map::get_abs_sub(), zone_manager::get_manager(), get_map(), map::getlocal(), map::i_at(), item::is_magazine(), item, resources, item::set_flag(), src_set, STATIC, calendar::turn_zero, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
form_storage_zones()
void basecamp::form_storage_zones (map & here, const tripoint_abs_ms & abspos)
Definition at line 666 of file basecamp.cpp.
 {
     zone_manager &mgr = zone_manager::get_manager();
     if( here.check_vehicle_zones( here.get_abs_sub().z() ) ) {
         mgr.cache_vzones();
     }
     tripoint src_loc = here.getlocal( bb_pos ) + point_north;
     std::vector<tripoint_abs_ms> possible_liquid_dumps;
     if( mgr.has_near( zone_type_CAMP_STORAGE, abspos, 60 ) ) {
         const std::vector<const zone_data *> zones = mgr.get_near_zones( zone_type_CAMP_STORAGE, abspos,
                 60 );
         // Find the nearest unsorted zone to dump objects at
         if( !zones.empty() ) {
             if( zones != storage_zones ) {
                 std::unordered_set<tripoint_abs_ms> src_set;
                 for( const zone_data *zone : zones ) {
                     for( const tripoint_abs_ms &p : tripoint_range<tripoint_abs_ms>(
                              zone->get_start_point(), zone->get_end_point() ) ) {
                         src_set.emplace( p );
                     }
                 }
                 set_storage_tiles( src_set );
             }
             src_loc = here.getlocal( zones.front()->get_center_point() );
             set_storage_zone( zones );
         }
         map &here = get_map();
         for( const zone_data *zone : storage_zones ) {
             if( zone->get_type() == zone_type_CAMP_STORAGE ) {
                 for( const tripoint_abs_ms &p : tripoint_range<tripoint_abs_ms>(
                          zone->get_start_point(), zone->get_end_point() ) ) {
                     if( here.has_flag_ter_or_furn( ter_furn_flag::TFLAG_LIQUIDCONT, here.getlocal( p ) ) ) {
                         possible_liquid_dumps.emplace_back( p );
                     }
                 }
             }
         }
     }
     set_dumping_spot( here.getglobal( src_loc ) );
     set_liquid_dumping_spot( possible_liquid_dumps );
 }
References bb_pos, zone_manager::cache_vzones(), map::check_vehicle_zones(), map::get_abs_sub(), zone_manager::get_manager(), get_map(), zone_manager::get_near_zones(), map::getglobal(), map::getlocal(), map::has_flag_ter_or_furn(), zone_manager::has_near(), point_north, set_dumping_spot(), set_liquid_dumping_spot(), set_storage_tiles(), set_storage_zone(), src_set, storage_zones, TFLAG_LIQUIDCONT, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), zone_type_CAMP_STORAGE, and zones.
Referenced by talk_function::basecamp_mission(), place_results(), and validate_sort_points().
fortifications_return()
void basecamp::fortifications_return (const mission_id & miss_id)
Definition at line 4038 of file faction_camp.cpp.
 {
     npc_ptr comp = companion_choose_return( miss_id, 3_hours );
     if( comp != nullptr ) {
         auto &build_point = comp->companion_mission_points;
         for( std::vector<tripoint_abs_omt>::iterator::value_type point : build_point ) {
             if( miss_id.parameters == faction_wall_level_n_0_string ||
                 //  Handling of old format (changed mid 0.F) below
                 ( miss_id.parameters.empty() &&
                   comp->companion_mission_role_id == faction_wall_level_n_0_string ) ) {
                 tripoint_abs_omt fort_point = point;
                 fortifications.push_back( fort_point );
             }
         }
         apply_fortifications( miss_id, &comp, false );
         const std::string msg = _( "returns from constructing fortifications" );
         finish_return( *comp, true, msg, skill_construction.str(), 2 );
     }
 }
References _, apply_fortifications(), companion_choose_return(), faction_wall_level_n_0_string, finish_return(), fortifications, mission_id::parameters, point, skill_construction, and string_id< T >::str().
Referenced by handle_mission().
gathering_description()
std::string basecamp::gathering_description ()
Provides a "guess" for some of the things your gatherers will return with to upgrade the camp.
Definition at line 5467 of file faction_camp.cpp.
 {
     item_group_id itemlist = Item_spawn_data_forest;
     std::string output;
     // Functions like the debug item group tester but only rolls 6 times so the player
     // doesn't have perfect knowledge
     std::map<std::string, int> itemnames;
     for( size_t a = 0; a < 6; a++ ) {
         const std::vector<item> items = item_group::items_from( itemlist, calendar::turn );
         for( const item &it : items ) {
             itemnames[it.display_name()]++;
         }
     }
     // Invert the map to get sorting!
     std::multimap<int, std::string> itemnames2;
     for( const auto &e : itemnames ) {
         itemnames2.insert( std::pair<int, std::string>( e.second, e.first ) );
     }
     for( const auto &e : itemnames2 ) {
         str_append( output, "> ", e.second, "\n" );
     }
     return output;
 }
References a, Item_spawn_data_forest, item_group::items_from(), str_append(), and calendar::turn.
Referenced by get_available_missions_by_dir().
gathering_return()
bool basecamp::gathering_return (const mission_id & miss_id, time_duration min_time)
Called when a companion completes a gathering task mission.
Definition at line 3962 of file faction_camp.cpp.
 {
     npc_ptr comp = companion_choose_return( miss_id, min_time );
     if( comp == nullptr ) {
         return false;
     }
     std::string task_description = _( "gathering materials" );
     int danger = 20;
     int favor = 2;
     int threat = 10;
     std::string skill_group = "gathering";
     float skill = 2 * comp->get_skill_level( skill_survival ) + comp->per_cur;
     int checks_per_cycle = 6;
     if( miss_id.id == Camp_Foraging ) {
         task_description = _( "foraging for edible plants" );
         danger = 15;
         checks_per_cycle = 12;
     } else if( miss_id.id == Camp_Trapping ) {
         task_description = _( "trapping small animals" );
         favor = 1;
         danger = 15;
         skill_group = "trapping";
         skill = 2 * comp->get_skill_level( skill_traps ) + comp->per_cur;
         checks_per_cycle = 4;
     } else if( miss_id.id == Camp_Hunting ) {
         task_description = _( "hunting for meat" );
         danger = 10;
         favor = 0;
         skill_group = "hunting";
         skill = 1.5 * comp->get_skill_level( skill_gun ) + comp->per_cur / 2.0;
         threat = 12;
         checks_per_cycle = 2;
     }
     time_duration mission_time = calendar::turn - comp->companion_mission_time;
     if( one_in( danger ) && !survive_random_encounter( *comp, task_description, favor, threat ) ) {
         return false;
     }
     const std::string msg = string_format( _( "returns from %s carrying supplies and has a bit "
                                            "more experience" ), task_description );
     finish_return( *comp, false, msg, skill_group, 1 );
     item_group_id itemlist( "forest" );
     if( miss_id.id == Camp_Collect_Firewood ) {
         itemlist = Item_spawn_data_gathering_faction_camp_firewood;
     } else if( miss_id.id == Camp_Gather_Materials ) {
         itemlist = Item_spawn_data_forest;
     } else if( miss_id.id == Camp_Foraging ) {
         switch( season_of_year( calendar::turn ) ) {
             case SPRING:
                 itemlist = Item_spawn_data_foraging_faction_camp_spring;
                 break;
             case SUMMER:
                 itemlist = Item_spawn_data_foraging_faction_camp_summer;
                 break;
             case AUTUMN:
                 itemlist = Item_spawn_data_foraging_faction_camp_autumn;
                 break;
             case WINTER:
                 itemlist = Item_spawn_data_foraging_faction_camp_winter;
                 break;
             default:
                 debugmsg( "Invalid season" );
         }
     }
     if( miss_id.id == Camp_Trapping ||
         miss_id.id == Camp_Hunting ) {
         hunting_results( round( skill ), miss_id, checks_per_cycle * mission_time / min_time, 30 );
     } else {
         search_results( round( skill ), itemlist, checks_per_cycle * mission_time / min_time, 15 );
     }
     return true;
 }
References _, AUTUMN, Camp_Collect_Firewood, Camp_Foraging, Camp_Gather_Materials, Camp_Hunting, Camp_Trapping, companion_choose_return(), debugmsg, finish_return(), hunting_results(), mission_id::id, Item_spawn_data_foraging_faction_camp_autumn, Item_spawn_data_foraging_faction_camp_spring, Item_spawn_data_foraging_faction_camp_summer, Item_spawn_data_foraging_faction_camp_winter, Item_spawn_data_forest, Item_spawn_data_gathering_faction_camp_firewood, one_in(), round(), search_results(), season_of_year(), skill_gun, skill_survival, skill_traps, SPRING, string_format(), SUMMER, survive_random_encounter(), calendar::turn, and WINTER.
Referenced by handle_mission().
get_available_missions()
void basecamp::get_available_missions (mission_data & mission_key, map & here)
Definition at line 1393 of file faction_camp.cpp.
 {
     std::string entry;
     const point &base_dir = base_camps::base_dir;
     const base_camps::direction_data &base_data = base_camps::all_directions.at( base_dir );
     const std::string base_dir_id = base_data.id;
     reset_camp_resources( here );
     // Missions that belong exclusively to the central tile
     {
         if( directions.size() < 8 ) {
             bool free_non_field_found = false;
             for( const auto &dir : base_camps::all_directions ) {
                 if( dir.first != base_camps::base_dir && expansions.find( dir.first ) == expansions.end() &&
                     overmap_buffer.ter_existing( omt_pos + dir.first ) != oter_id( "field" ) ) {
                     free_non_field_found = true;
                     break;
                 }
             }
             if( free_non_field_found ) {
                 const mission_id miss_id = { Camp_Survey_Field, "", {}, base_dir };
                 comp_list npc_list = get_mission_workers( miss_id );
                 entry = string_format( _( "Notes:\n"
                                           "Nearby terrain can be turned into fields if it is completely "
                                           "cleared of terrain that isn't grass or dirt.  Doing so makes that "
                                           "terrain eligible for usage for standard base camp expansion.  Note "
                                           "that log cutting does this conversion automatically when the trees "
                                           "are depleted, but not all terrain can be logged.\n\n"
                                           "Skill used: N/A\n"
                                           "Effects:\n"
                                           "> If the expansion direction selected is eligible for conversion into "
                                           "a field this mission will perform that conversion.  If it is not eligible "
                                           "you are told as much, and would have to make it suitable for conversion "
                                           "by removing everything that isn't grass or soil.  Mining zones are useful to "
                                           "remove pavement, for instance.  Note that removal of buildings is dangerous, "
                                           "laborious, and may still fail to get rid of everything if e.g. a basement or "
                                           "an opening to underground areas (such as a manhole) remains.\n\n"
                                           "Risk: None\n"
                                           "Intensity: Moderate\n"
                                           "Time: 0 Hours\n"
                                           "Positions: %d/1\n" ), npc_list.size() );
                 mission_key.add_start( miss_id, name_display_of( miss_id ),
                                        entry, npc_list.empty() );
                 if( !npc_list.empty() ) {
                     entry = action_of( miss_id.id );
                     bool avail = update_time_left( entry, npc_list );
                     mission_key.add_return( miss_id, _( "Recover Field Surveyor" ),
                                             entry, avail );
                 }
             }
             bool possible_expansion_found = false;
             for( const auto &dir : base_camps::all_directions ) {
                 if( dir.first != base_camps::base_dir && expansions.find( dir.first ) == expansions.end() ) {
                     const oter_id &omt_ref = overmap_buffer.ter( omt_pos + dir.first );
                     const std::optional<mapgen_arguments> *maybe_args = overmap_buffer.mapgen_args(
                                 omt_pos + dir.first );
                     const auto &pos_expansions = recipe_group::get_recipes_by_id( "all_faction_base_expansions",
                                                  omt_ref, maybe_args );
                     if( !pos_expansions.empty() ) {
                         possible_expansion_found = true;
                         break;
                     }
                 }
             }
             const mission_id miss_id = { Camp_Survey_Expansion, "", {}, base_dir };
             comp_list npc_list = get_mission_workers( miss_id );
             entry = string_format( _( "Notes:\n"
                                       "Expansions open up new opportunities but can be expensive and "
                                       "time-consuming.  Pick them carefully, at most 8 can be built "
                                       "at each camp.\n\n"
                                       "Skill used: N/A\n"
                                       "Effects:\n"
                                       "> Choose any one of the available expansions.  Starting with "
                                       "a farm is always a solid choice since food is used to support "
                                       "companion missions and minimal investment is needed to get it going.  "
                                       "A forge is also a great idea, allowing you to refine resources for "
                                       "subsequent expansions, craft better gear and make charcoal.\n\n"
                                       "NOTE: Actions available through expansions are located in "
                                       "separate tabs of the Camp Manager window.\n\n"
                                       "Risk: None\n"
                                       "Intensity: Moderate\n"
                                       "Time: 3 Hours\n"
                                       "Positions: %d/1\n" ), npc_list.size() );
             mission_key.add_start( miss_id, name_display_of( miss_id ),
                                    entry, npc_list.empty() && possible_expansion_found );
             if( !npc_list.empty() ) {
                 entry = action_of( miss_id.id );
                 bool avail = update_time_left( entry, npc_list );
                 mission_key.add_return( miss_id, _( "Recover Surveyor" ),
                                         entry, avail );
             }
         }
     }
     if( !by_radio ) {
         {
             const mission_id miss_id = { Camp_Distribute_Food, "", {}, base_dir };
             entry = string_format( _( "Notes:\n"
                                       "Distribute food to your follower and fill your larders.  "
                                       "Place the food you wish to distribute in the camp food zone.  "
                                       "You must have a camp food zone, and a camp storage zone, "
                                       "or you will be prompted to create them using the zone manager.\n"
                                       "Effects:\n"
                                       "> Increases your faction's food supply value which in "
                                       "turn is used to pay laborers for their time\n\n"
                                       "Must have enjoyability >= -6\n"
                                       "Perishable food liquidated at penalty depending on "
                                       "upgrades and rot time:\n"
                                       "> Rotten: 0%%\n"
                                       "> Rots in < 2 days: 60%%\n"
                                       "> Rots in < 5 days: 80%%\n\n"
                                       "Total faction food stock: %d kcal\nor %d / %d / %d day's rations\n"
                                       "where the days is measured for Extra / Moderate / No exercise levels" ),
                                    fac()->food_supply.kcal(), camp_food_supply_days( EXTRA_EXERCISE ),
                                    camp_food_supply_days( MODERATE_EXERCISE ), camp_food_supply_days( NO_EXERCISE ) );
             mission_key.add( { miss_id, false }, name_display_of( miss_id ),
                              entry );
         }
         {
             const mission_id miss_id = { Camp_Determine_Leadership, "", {}, base_dir };
             entry = string_format( _( "Notes:\n"
                                       "Choose a new leader for your faction.\n"
                                       "<color_yellow>You will switch to playing as the new leader.</color>\n"
                                       "Difficulty: N/A\n"
                                       "Risk: None\n" ) );
             mission_key.add( { miss_id, false }, name_display_of( miss_id ),
                              entry );
         }
         {
             const mission_id miss_id = { Camp_Have_Meal, "", {}, base_dir };
             entry = string_format( _( "Notes:\n"
                                       "Eat some food from the larder.\n"
                                       "Nutritional value depends on food stored in the larder.\n"
                                       "Difficulty: N/A\n"
                                       "Risk: None\n" ) );
             mission_key.add( { miss_id, false }, name_display_of( miss_id ),
                              entry );
         }
         {
             validate_assignees();
             const mission_id miss_id = { Camp_Assign_Jobs, "", {}, base_dir };
             entry = string_format( _( "Notes:\n"
                                       "Assign repeating job duties to NPCs stationed here.\n"
                                       "Difficulty: N/A\n"
                                       "Effects:\n"
                                       "\n\nRisk: None\n"
                                       "Time: Ongoing" ) );
             mission_key.add( {miss_id, false}, name_display_of( miss_id ), entry );
         }
         {
             const mission_id miss_id = { Camp_Assign_Workers, "", {}, base_dir };
             entry = string_format( _( "Notes:\n"
                                       "Assign followers to work at this camp." ) );
             mission_key.add( {miss_id, false}, name_display_of( miss_id ), entry );
         }
         {
             const mission_id miss_id = { Camp_Abandon, "", {}, base_dir };
             entry = _( "Notes:\nAbandon this camp" );
             mission_key.add( {miss_id, false}, name_display_of( miss_id ), entry );
         }
     }
     // Missions assigned to the central tile that could be done by an expansion
     get_available_missions_by_dir( mission_key, base_camps::base_dir );
     // Loop over expansions
     for( const point &dir : directions ) {
         get_available_missions_by_dir( mission_key, dir );
     }
     if( !camp_workers.empty() ) {
         const mission_id miss_id = { Camp_Emergency_Recall, "", {}, base_dir };
         entry = string_format( _( "Notes:\n"
                                   "Cancel a current mission and force the immediate return of a "
                                   "companion.  No work will be done on the mission and all "
                                   "resources used on the mission will be lost.\n\n"
                                   "WARNING: All resources used on the mission will be lost and "
                                   "no work will be done.  Only use this mission to recover a "
                                   "companion who cannot otherwise be recovered.\n\n"
                                   "Companions must be on missions for at least 24 hours before "
                                   "emergency recall becomes available." ) );
         bool avail = update_emergency_recall( entry, camp_workers, 24_hours );
         mission_key.add_return( miss_id, _( "Emergency Recall" ),
                                 entry, avail );
     }
     std::vector<ui_mission_id> k;
     for( int tab_num = base_camps::TAB_MAIN; tab_num <= base_camps::TAB_NW; tab_num++ ) {
         if( temp_ui_mission_keys.size() < size_t( tab_num ) + 1 ) {
             temp_ui_mission_keys.push_back( k );
         } else {
             temp_ui_mission_keys[tab_num].clear();
         }
         //  mission_key offsets its entries by 1, reserving 0 for high prio entries.
         for( mission_entry &entry : mission_key.entries[size_t( tab_num ) + 1] ) {
             if( !entry.id.ret && entry.id.id.id != Camp_Reveal_Mission ) {
                 temp_ui_mission_keys[tab_num].push_back( entry.id );
             }
         }
     }
 }
References _, action_of(), mission_data::add(), mission_data::add_return(), mission_data::add_start(), base_camps::all_directions, base_camps::base_dir, by_radio, Camp_Abandon, Camp_Assign_Jobs, Camp_Assign_Workers, Camp_Determine_Leadership, Camp_Distribute_Food, Camp_Emergency_Recall, camp_food_supply_days(), Camp_Have_Meal, Camp_Reveal_Mission, Camp_Survey_Expansion, Camp_Survey_Field, camp_workers, directions, mission_data::entries, expansions, EXTRA_EXERCISE, fac(), get_available_missions_by_dir(), get_mission_workers(), recipe_group::get_recipes_by_id(), base_camps::direction_data::id, mission_id::id, overmapbuffer::mapgen_args(), MODERATE_EXERCISE, name_display_of(), NO_EXERCISE, omt_pos, overmap_buffer, reset_camp_resources(), string_format(), base_camps::TAB_MAIN, base_camps::TAB_NW, temp_ui_mission_keys, overmapbuffer::ter(), overmapbuffer::ter_existing(), update_emergency_recall(), update_time_left(), and validate_assignees().
Referenced by talk_function::basecamp_mission(), and iexamine::bulletin_board().
get_available_missions_by_dir()
void basecamp::get_available_missions_by_dir (mission_data & mission_key, const point & dir)
Definition at line 787 of file faction_camp.cpp.
 {
     std::string entry;
     const std::string dir_id = base_camps::all_directions.at( dir ).id;
     const std::string dir_abbr = base_camps::all_directions.at( dir ).bracket_abbr.translated();
     const tripoint_abs_omt omt_trg = omt_pos + dir;
     {
         // return legacy workers. How old is this legacy?...
         mission_id miss_id = { Camp_Upgrade, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id ); // Don't match any blueprints
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, base_camps::recover_ally_string.translated()
                                     + dir_abbr + base_camps::expansion_string.translated(),
                                     entry, avail );
         }
         // Generate upgrade missions for expansions
         std::vector<basecamp_upgrade> upgrades = available_upgrades( dir );
         std::sort( upgrades.begin(), upgrades.end(), []( const basecamp_upgrade & p,
                    const basecamp_upgrade & q )->bool {return p.name.translated_lt( q.name ); } );
         for( const basecamp_upgrade &upgrade : upgrades ) {
             miss_id.parameters = upgrade.bldg;
             miss_id.mapgen_args = upgrade.args;
             comp_list npc_list = get_mission_workers( miss_id );
             if( npc_list.empty() ) {
                 std::string display_name = name_display_of( miss_id );
                 const recipe &making = *recipe_id( miss_id.parameters );
                 const int foodcost = time_to_food( base_camps::to_workdays( time_duration::from_moves(
                                                        making.blueprint_build_reqs().reqs_by_parameters.find( miss_id.mapgen_args )->second.time ) ),
                                                    making.exertion_level() );
                 const int available_calories = fac()->food_supply.kcal();
                 bool can_upgrade = upgrade.avail;
                 entry = om_upgrade_description( upgrade.bldg, upgrade.args );
                 if( foodcost > available_calories ) {
                     can_upgrade = false;
                     entry += string_format( _( "Total calorie cost: %s (have %d)" ),
                                             colorize( std::to_string( foodcost ), c_red ),
                                             available_calories );
                 } else {
                     entry += string_format( _( "Total calorie cost: %s (have %d)" ),
                                             colorize( std::to_string( foodcost ), c_green ),
                                             available_calories );
                 }
                 mission_key.add_start( miss_id, display_name, entry, can_upgrade );
             } else {
                 entry = action_of( miss_id.id );
                 bool avail = update_time_left( entry, npc_list );
                 mission_key.add_return( miss_id,
                                         base_camps::recover_ally_string.translated() + dir_abbr +
                                         " " + upgrade.name, entry, avail );
             }
         }
     }
     if( has_provides( "gathering", dir ) ) {
         const mission_id miss_id = { Camp_Gather_Materials, "", {}, dir };
         std::string gather_bldg = "null";
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion to gather materials for the next camp "
                                   "upgrade.\n\n"
                                   "Skill used: survival\n"
                                   "Difficulty: N/A\n"
                                   "Gathering Possibilities:\n"
                                   "%s\n"
                                   "Risk: Very Low\n"
                                   "Intensity: Light\n"
                                   "Time: 3 Hours, Repeated\n"
                                   "Positions: %d/3\n" ), gathering_description(),
                                npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.size() < 3 );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_fixed( entry, npc_list, 3_hours );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Ally from Gathering" ),
                                     entry, avail );
         }
     }
     if( has_provides( "firewood", dir ) ) {
         const mission_id miss_id = { Camp_Collect_Firewood, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion to gather light brush and stout branches.\n\n"
                                   "Skill used: survival\n"
                                   "Difficulty: N/A\n"
                                   "Gathering Possibilities:\n"
                                   "> stout branches\n"
                                   "> withered plants\n"
                                   "> splintered wood\n\n"
                                   "Risk: Very Low\n"
                                   "Intensity: Light\n"
                                   "Time: 3 Hours, Repeated\n"
                                   "Positions: %d/3\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.size() < 3 );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_fixed( entry, npc_list, 3_hours );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Firewood Gatherers" ),
                                     entry, avail );
         }
     }
     if( has_provides( "sorting", dir ) ) {
         const mission_id miss_id = { Camp_Menial, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion to do low level chores and sort "
                                   "supplies.\n\n"
                                   "Skill used: fabrication\n"
                                   "Difficulty: N/A\n"
                                   "Effects:\n"
                                   "> Material left in the unsorted loot zone will be sorted "
                                   "into a defined loot zone."
                                   "\n\nRisk: None\n"
                                   "Time: 3 Hours\n"
                                   "Positions: %d/1\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.empty() );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Menial Laborer" ),
                                     entry, avail );
         }
     }
     if( has_provides( "logging", dir ) ) {
         const mission_id miss_id = { Camp_Cut_Logs, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion to a nearby forest to cut logs.\n\n"
                                   "Skill used: fabrication\n"
                                   "Difficulty: 2\n"
                                   "Effects:\n"
                                   "> 50%% of trees/trunks at the forest position will be "
                                   "cut down.\n"
                                   "> 100%% of total material will be brought back.\n"
                                   "> Repeatable with diminishing returns.\n"
                                   "> Will eventually turn forests into fields.\n"
                                   "Risk: None\n"
                                   "Intensity: Active\n"
                                   "Time: 6 Hour Base + Travel Time + Cutting Time\n"
                                   "Positions: %d/1\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.empty() );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Log Cutter" ),
                                     entry, avail );
         }
     }
     if( has_provides( "logging", dir ) ) {
         const mission_id miss_id = { Camp_Clearcut, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion to clear a nearby forest.\n\n"
                                   "Skill used: fabrication\n"
                                   "Difficulty: 1\n"
                                   "Effects:\n"
                                   "> 95%% of trees/trunks at the forest position"
                                   " will be cut down.\n"
                                   "> 0%% of total material will be brought back.\n"
                                   "> Forest should become a field tile.\n"
                                   "> Useful for clearing land for another faction camp.\n\n"
                                   "Risk: None\n"
                                   "Intensity: Active\n"
                                   "Time: 6 Hour Base + Travel Time + Cutting Time\n"
                                   "Positions: %d/1\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.empty() );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Clearcutter" ),
                                     entry, avail );
         }
     }
     if( has_provides( "relaying", dir ) ) {
         const mission_id miss_id = { Camp_Setup_Hide_Site, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion to build an improvised shelter and stock it "
                                   "with equipment at a distant map location.\n\n"
                                   "Skill used: survival\n"
                                   "Difficulty: 3\n"
                                   "Effects:\n"
                                   "> Good for setting up resupply or contingency points.\n"
                                   "> Gear is left unattended and could be stolen.\n"
                                   "> Time dependent on weight of equipment being sent forward.\n\n"
                                   "Risk: Medium\n"
                                   "Intensity: Light\n"
                                   "Time: 6 Hour Construction + Travel\n"
                                   "Positions: %d/1\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.empty() );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Hide Setup" ),
                                     entry, avail );
         }
     }
     if( has_provides( "relaying", dir ) ) {
         const mission_id miss_id = { Camp_Relay_Hide_Site, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Push gear out to a hide site or bring gear back from one.\n\n"
                                   "Skill used: survival\n"
                                   "Difficulty: 1\n"
                                   "Effects:\n"
                                   "> Good for returning equipment you left in the hide site "
                                   "shelter.\n"
                                   "> Gear is left unattended and could be stolen.\n"
                                   "> Time dependent on weight of equipment being sent forward or "
                                   "back.\n\n"
                                   "Risk: Medium\n"
                                   "Intensity: Light\n"
                                   "Time: 1 Hour Base + Travel\n"
                                   "Positions: %d/1\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ), entry,
                                npc_list.empty() );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Hide Relay" ),
                                     entry, avail );
         }
     }
     if( has_provides( "foraging", dir ) ) {
         const mission_id miss_id = { Camp_Foraging, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion to forage for edible plants.\n\n"
                                   "Skill used: survival\n"
                                   "Difficulty: N/A\n"
                                   "Foraging Possibilities:\n"
                                   "> wild vegetables\n"
                                   "> fruits and nuts depending on season\n"
                                   "May produce less food than consumed!\n"
                                   "Risk: Very Low\n"
                                   "Intensity: Light\n"
                                   "Time: 4 Hours, Repeated\n"
                                   "Positions: %d/3\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.size() < 3 );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_fixed( entry, npc_list, 4_hours );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Foragers" ),
                                     entry, avail );
         }
     }
     if( has_provides( "trapping", dir ) ) {
         const mission_id miss_id = { Camp_Trapping, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion to set traps for small game.\n\n"
                                   "Skill used: devices\n"
                                   "Difficulty: N/A\n"
                                   "Trapping Possibilities:\n"
                                   "> small and tiny animal corpses\n"
                                   "May produce less food than consumed!\n"
                                   "Risk: Low\n"
                                   "Intensity: Light\n"
                                   "Time: 6 Hours, Repeated\n"
                                   "Positions: %d/2\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.size() < 2 );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_fixed( entry, npc_list, 6_hours );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Trappers" ),
                                     entry, avail );
         }
     }
     if( has_provides( "hunting", dir ) ) {
         const mission_id miss_id = { Camp_Hunting, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion to hunt large animals.\n\n"
                                   "Skill used: marksmanship\n"
                                   "Difficulty: N/A\n"
                                   "Hunting Possibilities:\n"
                                   "> small, medium, or large animal corpses\n"
                                   "May produce less food than consumed!\n"
                                   "Risk: Medium\n"
                                   "Intensity: Moderate\n"
                                   "Time: 6 Hours, Repeated\n"
                                   "Positions: %d/1\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.empty() );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_fixed( entry, npc_list, 6_hours );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Hunter" ),
                                     entry, avail );
         }
     }
     if( has_provides( "walls", dir ) ) {
         mission_id miss_id = {
             Camp_OM_Fortifications, camp_om_fortifications_trench_parameter, {}, dir
         };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = om_upgrade_description( faction_wall_level_n_0_string, {} );
         //  Should add check for materials as well as active mission.
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.empty() );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Finish Map Fortifications" ),
                                     entry, avail );
         }
         entry = om_upgrade_description( faction_wall_level_n_1_string, {} );
         miss_id.parameters = camp_om_fortifications_spiked_trench_parameter;
         npc_list = get_mission_workers( miss_id );
         //  Should add check for materials as well as active mission.
         //  Should also check if there are any trenches to improve.
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry,
                                npc_list.empty() );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Finish Map Fortification Update" ),
                                     entry, avail );
         }
         //  Code to deal with legacy construction (Changed during 0.F)
         miss_id.parameters.clear();
         npc_list = get_mission_workers( miss_id );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Finish Map Fortifications" ),
                                     entry, avail );
         }
     }
     if( has_provides( "recruiting", dir ) ) {
         const mission_id miss_id = { Camp_Recruiting, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = recruit_description( npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ), entry,
                                npc_list.empty() );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Recruiter" ),
                                     entry, avail );
         }
     }
     if( has_provides( "scouting", dir ) ) {
         const mission_id miss_id = { Camp_Scouting, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion out into the great unknown.  High survival "
                                   "skills are needed to avoid combat but you should expect an "
                                   "encounter or two.\n\n"
                                   "Skill used: survival\n"
                                   "Difficulty: 3\n"
                                   "Effects:\n"
                                   "> Select checkpoints to customize path.\n"
                                   "> Reveals terrain around the path.\n"
                                   "> Can bounce off hide sites to extend range.\n\n"
                                   "Risk: High\n"
                                   "Intensity: Brisk\n"
                                   "Time: Travel\n"
                                   "Positions: %d/3\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.size() < 3 );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Scout" ),
                                     entry, avail );
         }
     }
     if( has_provides( "patrolling", dir ) ) {
         const mission_id miss_id = { Camp_Combat_Patrol, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         entry = string_format( _( "Notes:\n"
                                   "Send a companion to purge the wasteland.  Their goal is to "
                                   "kill anything hostile they encounter and return when "
                                   "their wounds are too great or the odds are stacked against "
                                   "them.\n\n"
                                   "Skill used: survival\n"
                                   "Difficulty: 4\n"
                                   "Effects:\n"
                                   "> Pulls creatures encountered into combat instead of "
                                   "fleeing.\n"
                                   "> Select checkpoints to customize path.\n"
                                   "> Can bounce off hide sites to extend range.\n\n"
                                   "Risk: Very High\n"
                                   "Intensity: Brisk\n"
                                   "Time: Travel\n"
                                   "Positions: %d/3\n" ), npc_list.size() );
         mission_key.add_start( miss_id, name_display_of( miss_id ),
                                entry, npc_list.size() < 3 );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id, dir_abbr + _( " Recover Combat Patrol" ),
                                     entry, avail );
         }
     }
     if( has_provides( "dismantling",
                       dir ) ) {  //  Obsolete (during 0.E), but we still have to be able to process existing missions.
         const mission_id miss_id = { Camp_Chop_Shop, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         if( !npc_list.empty() ) {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id,
                                     dir_abbr + _( " (Finish) Chop Shop" ), entry, avail );
         }
     }
     std::map<recipe_id, translation> craft_recipes = recipe_deck( dir );
     {
         mission_id miss_id = { Camp_Crafting, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id, true );
         if( npc_list.size() < 3 ) {
             add_available_recipes( mission_key, Camp_Crafting, dir, craft_recipes );
         }
         if( !npc_list.empty() ) {
             std::map<std::string, comp_list> lists = companion_per_recipe_building_type( npc_list );
             for( std::pair<std::string, comp_list> npcs : lists ) {
                 const std::string bldg = npcs.first;
                 miss_id.parameters = npcs.second.at( 0 )->get_companion_mission().miss_id.parameters;
                 bool avail = false;
                 entry.clear();
                 //  Room for moving the match of recipe group 'building_type' to return string into JSON
                 std::string return_craft;
                 if( bldg == base_recipe_group_string ) {
                     return_craft = _( " (Finish) Crafting" );
                 } else if( bldg == cook_recipe_group_string ) {
                     return_craft = _( " (Finish) Cooking" );
                 } else if( bldg == farm_recipe_group_string ) {
                     return_craft = _( " (Finish) Crafting" );
                 } else if( bldg == smith_recipe_group_string ) {
                     return_craft = _( " (Finish) Smithing" );
                 }
                 else {  //  No matching recipe group
                     return_craft = _( " (Finish) Crafting" );
                 }
                 for( npc_ptr &comp : npcs.second ) {
                     const bool done = comp->companion_mission_time_ret < calendar::turn;
                     avail |= done;
                     entry += comp->get_name() + " ";
                     if( done ) {
                         entry += _( "[DONE]\n" );
                     } else {
                         entry += " [" +
                                  to_string( comp->companion_mission_time_ret - calendar::turn ) +
                                  _( " left] " ) + action_of( miss_id.id );
                     }
                 }
                 mission_key.add_return( miss_id,
                                         dir_abbr + return_craft, entry, avail );
             }
         }
         if( !mission_key.entries[size_t( base_camps::all_directions.at( dir ).tab_order ) + 1].empty() ||
             ( !hidden_missions.empty() &&
               !hidden_missions[size_t( base_camps::all_directions.at( dir ).tab_order )].empty() ) ) {
             {
                 const mission_id miss_id = { Camp_Hide_Mission, "", {}, dir };
                 entry = string_format( _( "Hide one or more missions to clean up the UI." ) );
                 mission_key.add( { miss_id, false }, name_display_of( miss_id ),
                                  entry );
             }
             {
                 int count = 0;
                 if( !hidden_missions.empty() ) {
                     count = hidden_missions[base_camps::all_directions.at( dir ).tab_order].size();
                 }
                 const mission_id miss_id = { Camp_Reveal_Mission, "", {}, dir };
                 entry = string_format( _( "Reveal one or more missions previously hidden.\n"
                                           "Current number of hidden missions: %d" ),
                                        count );
                 mission_key.add( { miss_id, false }, name_display_of( miss_id ),
                                  entry, false, count != 0 );
             }
         }
     }
     if( has_provides( "farming", dir ) ) {
         size_t plots = 0;
         const mission_id miss_id = { Camp_Plow, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         if( npc_list.empty() ) {
             entry = _( "Notes:\n"
                        "Plow any spaces that have reverted to dirt or grass.\n\n" ) +
                     farm_description( omt_trg, plots, farm_ops::plow ) +
                     _( "\n\n"
                        "Skill used: fabrication\n"
                        "Difficulty: N/A\n"
                        "Effects:\n"
                        "> Restores only the plots created in the last expansion upgrade.\n"
                        "> Does not damage existing crops.\n\n"
                        "Risk: None\n"
                        "Intensity: Moderate\n"
                        "Time: 5 Min / Plot\n"
                        "Positions: 0/1\n" );
             mission_key.add_start( miss_id, name_display_of( miss_id ),
                                    entry, plots > 0 );
         } else {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id,
                                     dir_abbr + _( " (Finish) Plow fields" ), entry, avail );
         }
     }
     if( has_provides( "farming", dir ) ) {
         size_t plots = 0;
         const mission_id miss_id = { Camp_Plant, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         if( npc_list.empty() ) {
             entry = _( "Notes:\n"
                        "Plant designated seeds in the spaces that have already been "
                        "tilled.\n\n" ) +
                     farm_description( omt_trg, plots, farm_ops::plant ) +
                     _( "\n\n"
                        "Skill used: survival\n"
                        "Difficulty: N/A\n"
                        "Effects:\n"
                        "> Choose which seed type or all of your seeds.\n"
                        "> Stops when out of seeds or planting locations.\n"
                        "> Will plant in ALL dirt mounds in the expansion.\n\n"
                        "Risk: None\n"
                        "Intensity: Moderate\n"
                        "Time: 1 Min / Plot\n"
                        "Positions: 0/1\n" );
             mission_key.add_start( miss_id,
                                    name_display_of( miss_id ), entry,
                                    plots > 0 && warm_enough_to_plant( omt_trg ) );
         } else {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id,
                                     dir_abbr + _( " (Finish) Plant Fields" ), entry, avail );
         }
     }
     if( has_provides( "farming", dir ) ) {
         size_t plots = 0;
         const mission_id miss_id = { Camp_Harvest, "", {}, dir };
         comp_list npc_list = get_mission_workers( miss_id );
         if( npc_list.empty() ) {
             entry = _( "Notes:\n"
                        "Harvest any plants that are ripe and bring the produce back.\n\n" ) +
                     farm_description( omt_trg, plots, farm_ops::harvest ) +
                     _( "\n\n"
                        "Skill used: survival\n"
                        "Difficulty: N/A\n"
                        "Effects:\n"
                        "> Will dump all harvesting products onto your location.\n\n"
                        "Risk: None\n"
                        "Intensity: Moderate\n"
                        "Time: 3 Min / Plot\n"
                        "Positions: 0/1\n" );
             mission_key.add_start( miss_id,
                                    name_display_of( miss_id ), entry,
                                    plots > 0 );
         } else {
             entry = action_of( miss_id.id );
             bool avail = update_time_left( entry, npc_list );
             mission_key.add_return( miss_id,
                                     dir_abbr + _( " (Finish) Harvest Fields" ), entry, avail );
         }
     }
 }
References _, action_of(), mission_data::add(), add_available_recipes(), mission_data::add_return(), mission_data::add_start(), base_camps::all_directions, available_upgrades(), base_recipe_group_string, recipe::blueprint_build_reqs(), c_green, c_red, Camp_Chop_Shop, Camp_Clearcut, Camp_Collect_Firewood, Camp_Combat_Patrol, Camp_Crafting, Camp_Cut_Logs, Camp_Foraging, Camp_Gather_Materials, Camp_Harvest, Camp_Hide_Mission, Camp_Hunting, Camp_Menial, Camp_OM_Fortifications, camp_om_fortifications_spiked_trench_parameter, camp_om_fortifications_trench_parameter, Camp_Plant, Camp_Plow, Camp_Recruiting, Camp_Relay_Hide_Site, Camp_Reveal_Mission, Camp_Scouting, Camp_Setup_Hide_Site, Camp_Trapping, Camp_Upgrade, colorize(), companion_per_recipe_building_type(), cook_recipe_group_string, mission_data::entries, recipe::exertion_level(), base_camps::expansion_string, fac(), faction_wall_level_n_0_string, faction_wall_level_n_1_string, farm_description(), farm_recipe_group_string, faction_template::food_supply, time_duration::from_moves(), gathering_description(), get_mission_workers(), harvest, has_provides(), hidden_missions, mission_id::id, nutrients::kcal(), mission_id::mapgen_args, name_display_of(), om_upgrade_description(), omt_pos, mission_id::parameters, plant, plow, recipe_deck(), base_camps::recover_ally_string, recruit_description(), parameterized_build_reqs::reqs_by_parameters, smith_recipe_group_string, string_format(), time_to_food(), to_string(), base_camps::to_workdays(), calendar::turn, update_time_fixed(), update_time_left(), spell_effect::upgrade(), and warm_enough_to_plant().
Referenced by get_available_missions().
get_bb_pos()
tripoint basecamp::get_bb_pos () const inline
Definition at line 181 of file basecamp.h.
{
             return bb_pos;
         }
References bb_pos.
Referenced by npc::worker_downtime().
get_camp_map()
map & basecamp::get_camp_map ()
Definition at line 790 of file basecamp.cpp.
 {
     if( by_radio ) {
         if( !camp_map.map_ ) {
             camp_map.map_ = std::make_unique<map>();
             camp_map.map_->load( project_to<coords::sm>( omt_pos ) - point( 5, 5 ), false );
         }
         return *camp_map.map_;
     }
     return get_map();
 }
References by_radio, camp_map, get_map(), basecamp_map::map_, omt_pos, and point.
Referenced by talk_function::basecamp_mission(), basecamp_action_components::consume_components(), form_crafting_inventory(), place_results(), and start_mission().
get_dumping_spot()
const tripoint_abs_ms& basecamp::get_dumping_spot () const inline
Definition at line 302 of file basecamp.h.
{
             return dumping_spot;
         }
References dumping_spot.
Referenced by distribute_food(), and place_results().
get_equipment()
drop_locations basecamp::get_equipment (tinymap * target_bay, const tripoint & target, Character * pc, const inventory_filter_preset & preset, const std::string & msg, const std::string & title, units::volume & total_volume, units::mass & total_mass)
Definition at line 5241 of file faction_camp.cpp.
 {
     auto make_raw_stats = [&total_volume,
                            &total_mass]( const std::vector<std::pair<item_location, int>> &locs
     ) {
         total_volume = 0_ml;
         for( const auto &pair : locs ) {
             total_volume += pair.first->volume( false, true, pair.second );
         }
         total_mass = 0_gram;
         for( const auto &pair : locs ) {
             total_mass += pair.first->weight();
         }
         auto to_string = []( int val ) -> std::string {
             if( val == INT_MAX )
             {
                 return pgettext( "short for infinity", "inf" );
             }
             return string_format( "%3d", val );
         };
         using stats = inventory_selector::stats;
         return stats{ {
                 display_stat( _( "Volume (L)" ), total_volume.value() / 1000, INT_MAX, to_string ),
                 display_stat( _( "Weight (kg)" ), total_mass.value() / 1000000, INT_MAX, to_string )
             } };
     };
     inventory_multiselector inv_s( *pc, preset, msg,
                                    make_raw_stats, /*allow_select_contained =*/ true );
     inv_s.add_remote_map_items( target_bay, target );
     inv_s.set_title( title );
     inv_s.set_hint( _( "To select items, type a number before selecting." ) );
     if( inv_s.empty() ) {
         popup( std::string( _( "You have nothing to retrieve." ) ), PF_GET_KEY );
         return {};
     }
     drop_locations selected = inv_s.execute();
     return selected;
 }
References _, inventory_selector::add_remote_map_items(), display_stat(), inventory_selector::empty(), inventory_multiselector::execute(), PF_GET_KEY, pgettext, popup(), inventory_selector::set_hint(), inventory_selector::set_title(), string_format(), music::title, to_string(), and units::quantity< V, U >::value().
Referenced by start_relay_hide_site().
get_liquid_dumping_spot()
const std::vector<tripoint_abs_ms>& basecamp::get_liquid_dumping_spot () const inline
Definition at line 305 of file basecamp.h.
{
             return liquid_dumping_spots;
         }
References liquid_dumping_spots.
Referenced by place_results().
get_mission_workers()
comp_list basecamp::get_mission_workers (const mission_id & miss_id, bool contains = false)
Definition at line 597 of file basecamp.cpp.
 {
     comp_list available;
     for( const auto &elem : camp_workers ) {
         npc_companion_mission c_mission = elem->get_companion_mission();
         if( is_equal( c_mission.miss_id, miss_id ) ||
             ( contains && c_mission.miss_id.id == miss_id.id &&
               c_mission.miss_id.dir == miss_id.dir ) ) {
             available.push_back( elem );
         }
     }
     return available;
 }
References available, camp_workers, contains, mission_id::dir, mission_id::id, is_equal(), and npc_companion_mission::miss_id.
Referenced by companion_crafting_choose_return(), emergency_recall(), get_available_missions(), get_available_missions_by_dir(), and upgrade_return().
get_npcs_assigned()
std::vector< npc_ptr > basecamp::get_npcs_assigned ()
Definition at line 551 of file basecamp.cpp.
 {
     validate_assignees();
     return assigned_npcs;
 }
References assigned_npcs, and validate_assignees().
Referenced by abandon_camp(), talk_function::companion_choose(), and job_assignment_ui().
get_owner()
faction_id basecamp::get_owner ()
Definition at line 821 of file basecamp.cpp.
 {
     return owner;
 }
References owner.
get_storage_tiles()
const std::unordered_set<tripoint_abs_ms>& basecamp::get_storage_tiles () const inline
Definition at line 466 of file basecamp.h.
{
             return src_set;
         }
References src_set.
Referenced by inventory_selector::add_basecamp_items().
get_storage_zone()
const std::vector<const zone_data * >& basecamp::get_storage_zone () const inline
Definition at line 459 of file basecamp.h.
{
             return storage_zones;
         }
References storage_zones.
give_basecamp_equipment()
drop_locations basecamp::give_basecamp_equipment (inventory_filter_preset & preset, const std::string & title, const std::string & column_title, const std::string & msg_empty) const
Display items listed in equipment to let the player pick what to give the departing NPC, loops until quit or empty.
Definition at line 5178 of file faction_camp.cpp.
 {
     inventory_multiselector inv_s( get_player_character(), preset, column_title );
     inv_s.add_basecamp_items( *this );
     inv_s.set_title( title );
     if( inv_s.empty() ) {
         popup( std::string( msg_empty ), PF_GET_KEY );
         return {};
     }
     drop_locations selected = inv_s.execute();
     return selected;
 }
References inventory_selector::add_basecamp_items(), inventory_selector::empty(), inventory_multiselector::execute(), get_player_character(), PF_GET_KEY, popup(), inventory_selector::set_title(), and music::title.
Referenced by start_farm_op().
give_equipment()
drop_locations basecamp::give_equipment (Character * pc, const inventory_filter_preset & preset, const std::string & msg, const std::string & title, units::volume & total_volume, units::mass & total_mass)
Definition at line 5194 of file faction_camp.cpp.
 {
     auto make_raw_stats = [&total_volume,
                            &total_mass]( const std::vector<std::pair<item_location, int>> &locs
     ) {
         total_volume = 0_ml;
         for( const auto &pair : locs ) {
             total_volume += pair.first->volume( false, true, pair.second );
         }
         total_mass = 0_gram;
         for( const auto &pair : locs ) {
             total_mass += pair.first->weight();
         }
         auto to_string = []( int val ) -> std::string {
             if( val == INT_MAX )
             {
                 return pgettext( "short for infinity", "inf" );
             }
             return string_format( "%3d", val );
         };
         using stats = inventory_selector::stats;
         return stats{ {
                 display_stat( _( "Volume (L)" ), total_volume.value() / 1000, INT_MAX, to_string ),
                 display_stat( _( "Weight (kg)" ), total_mass.value() / 1000000, INT_MAX, to_string )
             } };
     };
     inventory_multiselector inv_s( *pc, preset, msg,
                                    make_raw_stats, /*allow_select_contained =*/ true );
     inv_s.add_character_items( *pc );
     inv_s.add_nearby_items( PICKUP_RANGE );
     inv_s.set_title( title );
     inv_s.set_hint( _( "To select items, type a number before selecting." ) );
     if( inv_s.empty() ) {
         popup( std::string( _( "You have nothing to send." ) ), PF_GET_KEY );
         return {};
     }
     drop_locations selected = inv_s.execute();
     return selected;
 }
References _, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), display_stat(), inventory_selector::empty(), inventory_multiselector::execute(), PF_GET_KEY, pgettext, PICKUP_RANGE, popup(), inventory_selector::set_hint(), inventory_selector::set_title(), string_format(), music::title, to_string(), and units::quantity< V, U >::value().
Referenced by start_relay_hide_site(), and start_setup_hide_site().
handle_hide_mission()
void basecamp::handle_hide_mission (const point & dir)
Definition at line 5908 of file faction_camp.cpp.
 {
     const base_camps::direction_data &base_data = base_camps::all_directions.at( dir );
     const size_t previously_hidden_count = hidden_missions[size_t( base_data.tab_order )].size();
     while( true ) {
         std::vector<std::string> pos_names;
         std::vector<ui_mission_id> reference;
         int choice = 0;
         pos_names.reserve( hidden_missions[size_t( base_data.tab_order )].size() );
         reference.reserve( hidden_missions[size_t( base_data.tab_order )].size() );
         for( ui_mission_id &miss_id : temp_ui_mission_keys[size_t( base_data.tab_order )] ) {
             if( !miss_id.ret &&
                 miss_id.id.id != Camp_Reveal_Mission ) {
                 // Filter out the onces we're hiding in this loop, as temp_ui_mission_keys isn't refreshed
                 bool hidden = false;
                 for( size_t i = previously_hidden_count; i < hidden_missions[size_t( base_data.tab_order )].size();
                      i++ ) {
                     if( is_equal( hidden_missions[size_t( base_data.tab_order )].at( i ), miss_id ) ) {
                         hidden = true;
                         break;
                     }
                 }
                 if( !hidden ) {
                     pos_names.push_back( name_display_of( miss_id.id ) );
                     reference.push_back( miss_id );
                 }
             }
         }
         choice = uilist( _( "Select mission(s) to hide, escape when done" ), pos_names );
         if( choice < 0 || static_cast<size_t>( choice ) >= pos_names.size() ) {
             popup( _( "You're done for now" ) );
             return;
         }
         hidden_missions[size_t( base_data.tab_order )].push_back( reference[choice] );
     }
 }
References _, base_camps::all_directions, Camp_Reveal_Mission, hidden_missions, is_equal(), name_display_of(), popup(), base_camps::direction_data::tab_order, and temp_ui_mission_keys.
Referenced by handle_mission().
handle_mission()
bool basecamp::handle_mission (const ui_mission_id & miss_id)
Definition at line 1716 of file faction_camp.cpp.
 {
     if( miss_id.id.id == No_Mission ) {
         return true;
     }
     const point &miss_dir = miss_id.id.dir.value();
     //  All missions should supply dir. Bug if they don't, so blow up during testing.
     const tripoint_abs_omt omt_trg = omt_pos + miss_dir;
     switch( miss_id.id.id ) {
         case Camp_Distribute_Food:
             distribute_food();
             break;
         case Camp_Determine_Leadership:
             choose_new_leader();
             break;
         case Camp_Have_Meal:
             player_eats_meal();
             break;
         case Camp_Hide_Mission:
             handle_hide_mission( miss_id.id.dir.value() );
             break;
         case Camp_Reveal_Mission:
             handle_reveal_mission( miss_id.id.dir.value() );
             break;
         case Camp_Assign_Jobs:
             job_assignment_ui();
             break;
         case Camp_Assign_Workers:
             worker_assignment_ui();
             break;
         case Camp_Abandon:
             abandon_camp();
             break;
         case Camp_Upgrade:
             if( miss_id.ret ) {
                 upgrade_return( miss_id.id );
             } else {
                 start_upgrade( miss_id.id );
             }
             break;
         case Camp_Emergency_Recall:
             emergency_recall( miss_id.id );
             break;
         case Camp_Crafting:
             if( miss_id.ret ) {
                 const std::string bldg = recipe_group::get_building_of_recipe( miss_id.id.parameters );
                 std::string msg;
                 if( bldg == base_recipe_group_string ) {
                     msg = _( "returns to you with something" );
                 } else if( bldg == cook_recipe_group_string ) {
                     msg = _( "returns from your kitchen with something" );
                 } else if( bldg == farm_recipe_group_string ) {
                     msg = _( "returns from your farm with something" );
                 } else if( bldg == smith_recipe_group_string ) {
                     msg = _( "returns from your blacksmith shop with something" );
                 }
                 else {
                     msg = _( "returns to you with something" );
                 }
                 crafting_mission_return( miss_id.id,
                                          msg,
                                          skill_construction.str(), 2 );
             } else {
                 const std::string bldg = recipe_group::get_building_of_recipe( miss_id.id.parameters );
                 start_crafting( recipe_group::get_building_of_recipe( miss_id.id.parameters ), miss_id.id );
             }
             break;
         case Camp_Gather_Materials:
             if( miss_id.ret ) {
                 gathering_return( miss_id.id, 3_hours );
             } else {
                 start_mission( miss_id.id, 3_hours, true,
                                _( "departs to search for materials" ), false, {}, skill_survival, 0, LIGHT_EXERCISE );
             }
             break;
         case Camp_Collect_Firewood:
             if( miss_id.ret ) {
                 gathering_return( miss_id.id, 3_hours );
             } else {
                 start_mission( miss_id.id, 3_hours, true,
                                _( "departs to search for firewood" ), false, {}, skill_survival, 0, LIGHT_EXERCISE );
             }
             break;
         case Camp_Menial:
             if( miss_id.ret ) {
                 menial_return( miss_id.id );
             } else {
                 start_menial_labor();
             }
             break;
         case Camp_Survey_Field:
             if( miss_id.ret ) {
                 survey_field_return( miss_id.id );
             } else {
                 start_mission( miss_id.id, 0_hours, true,
                                _( "departs to look for suitable fields" ), false, {}, skill_gun, 0, MODERATE_EXERCISE );
             }
             break;
         case Camp_Survey_Expansion:
             if( miss_id.ret ) {
                 survey_return( miss_id.id );
             } else {
                 start_mission( miss_id.id, 3_hours, true,
                                _( "departs to survey land" ), false, {}, skill_gun, 0, MODERATE_EXERCISE );
             }
             break;
         case Camp_Cut_Logs:
             if( miss_id.ret ) {
                 mission_return( miss_id.id, 6_hours, true,
                                 _( "returns from working in the woods" ),
                                 skill_construction.str(), 2 );
             } else {
                 start_cut_logs( miss_id.id, ACTIVE_EXERCISE );
             }
             break;
         case Camp_Clearcut:
             if( miss_id.ret ) {
                 mission_return( miss_id.id, 6_hours, true,
                                 _( "returns from working in the woods" ),
                                 skill_construction.str(), 1 );
             } else {
                 start_clearcut( miss_id.id, ACTIVE_EXERCISE );
             }
             break;
         case Camp_Setup_Hide_Site:
             if( miss_id.ret ) {
                 mission_return( miss_id.id, 3_hours, true,
                                 _( "returns from working on the hide site" ), skill_survival.str(), 3 );
             } else {
                 start_setup_hide_site( miss_id.id, LIGHT_EXERCISE );
             }
             break;
         case Camp_Relay_Hide_Site:
             if( miss_id.ret ) {
                 const std::string msg = _( "returns from shuttling gear between the hide site" );
                 mission_return( miss_id.id, 3_hours, true,
                                 msg, skill_survival.str(), 3 );
             } else {
                 start_relay_hide_site( miss_id.id, LIGHT_EXERCISE );
             }
             break;
         case Camp_Foraging:
             if( miss_id.ret ) {
                 gathering_return( miss_id.id, 4_hours );
             } else {
                 start_mission( miss_id.id, 4_hours, true,
                                _( "departs to search for edible plants" ), false, {}, skill_survival, 0, LIGHT_EXERCISE );
             }
             break;
         case Camp_Trapping:
             if( miss_id.ret ) {
                 gathering_return( miss_id.id, 6_hours );
             } else {
                 start_mission( miss_id.id, 6_hours, true,
                                _( "departs to set traps for small animals" ), false, {}, skill_traps, 0, LIGHT_EXERCISE );
             }
             break;
         case Camp_Hunting:
             if( miss_id.ret ) {
                 gathering_return( miss_id.id, 6_hours );
             } else {
                 start_mission( miss_id.id, 6_hours, true,
                                _( "departs to hunt for meat" ), false, {}, skill_gun, 0, MODERATE_EXERCISE );
             }
             break;
         case Camp_OM_Fortifications:
             if( miss_id.ret ) {
                 fortifications_return( miss_id.id );
             } else {
                 std::string bldg_exp = miss_id.id.parameters;
                 start_fortifications( miss_id.id, ACTIVE_EXERCISE );
             }
             break;
         case Camp_Recruiting:
             if( miss_id.ret ) {
                 recruit_return( miss_id.id,
                                 recruit_evaluation() );
             } else {
                 start_mission( miss_id.id, 4_days, true,
                                _( "departs to search for recruits" ), false, {}, skill_gun, 0, MODERATE_EXERCISE );
             }
             break;
         case Camp_Scouting:
         case Camp_Combat_Patrol:
             if( miss_id.ret ) {
                 combat_mission_return( miss_id.id );
             } else {
                 start_combat_mission( miss_id.id, BRISK_EXERCISE );
             }
             break;
         case Camp_Chop_Shop:  //  Removed during 0.E
             debugmsg( "Obsolete Function.  Use Vehicle Deconstruct zone instead.  Recover your companion with Emergency Recall." );
             break;
         case Camp_Plow:
         case Camp_Plant:
         case Camp_Harvest:
             if( miss_id.ret ) {
                 farm_return( miss_id.id, omt_trg );
             } else {
                 start_farm_op( omt_trg, miss_id.id, MODERATE_EXERCISE );
             }
             break;
         default:
             break;
     }
     return true;
 }
References _, abandon_camp(), ACTIVE_EXERCISE, base_recipe_group_string, BRISK_EXERCISE, Camp_Abandon, Camp_Assign_Jobs, Camp_Assign_Workers, Camp_Chop_Shop, Camp_Clearcut, Camp_Collect_Firewood, Camp_Combat_Patrol, Camp_Crafting, Camp_Cut_Logs, Camp_Determine_Leadership, Camp_Distribute_Food, Camp_Emergency_Recall, Camp_Foraging, Camp_Gather_Materials, Camp_Harvest, Camp_Have_Meal, Camp_Hide_Mission, Camp_Hunting, Camp_Menial, Camp_OM_Fortifications, Camp_Plant, Camp_Plow, Camp_Recruiting, Camp_Relay_Hide_Site, Camp_Reveal_Mission, Camp_Scouting, Camp_Setup_Hide_Site, Camp_Survey_Expansion, Camp_Survey_Field, Camp_Trapping, Camp_Upgrade, choose_new_leader(), combat_mission_return(), cook_recipe_group_string, crafting_mission_return(), debugmsg, mission_id::dir, distribute_food(), emergency_recall(), farm_recipe_group_string, farm_return(), fortifications_return(), gathering_return(), recipe_group::get_building_of_recipe(), handle_hide_mission(), handle_reveal_mission(), mission_id::id, ui_mission_id::id, job_assignment_ui(), LIGHT_EXERCISE, menial_return(), mission_return(), MODERATE_EXERCISE, No_Mission, omt_pos, mission_id::parameters, player_eats_meal(), recruit_evaluation(), recruit_return(), ui_mission_id::ret, skill_construction, skill_gun, skill_survival, skill_traps, smith_recipe_group_string, start_clearcut(), start_combat_mission(), start_crafting(), start_cut_logs(), start_farm_op(), start_fortifications(), start_menial_labor(), start_mission(), start_relay_hide_site(), start_setup_hide_site(), start_upgrade(), string_id< T >::str(), survey_field_return(), survey_return(), upgrade_return(), and worker_assignment_ui().
Referenced by talk_function::basecamp_mission(), and iexamine::bulletin_board().
handle_reveal_mission()
void basecamp::handle_reveal_mission (const point & dir)
Definition at line 5880 of file faction_camp.cpp.
 {
     if( hidden_missions.empty() ) { //  Should never happen
         return;
     }
     const base_camps::direction_data &base_data = base_camps::all_directions.at( dir );
     while( true ) {
         std::vector<std::string> pos_names;
         int choice = 0;
         pos_names.reserve( hidden_missions[size_t( base_data.tab_order )].size() );
         for( ui_mission_id &id : hidden_missions[size_t( base_data.tab_order )] ) {
             pos_names.push_back( name_display_of( id.id ) );
         }
         choice = uilist( _( "Select mission(s) to reveal, escape when done" ), pos_names );
         if( choice < 0 || static_cast<size_t>( choice ) >= pos_names.size() ) {
             popup( _( "You're done for now" ) );
             return;
         }
         hidden_missions[size_t( base_data.tab_order )].erase( hidden_missions[size_t(
                     base_data.tab_order )].begin() + choice );
     }
 }
References _, base_camps::all_directions, hidden_missions, name_display_of(), popup(), and base_camps::direction_data::tab_order.
Referenced by handle_mission().
has_provides() [1/2]
bool basecamp::has_provides (const std::string & req, const expansion_data & e_data, int level = 0) const
Definition at line 288 of file basecamp.cpp.
 {
     for( const auto &provide : e_data.provides ) {
         if( provide.first == req && provide.second > level ) {
             return true;
         }
     }
     return false;
 }
References expansion_data::provides.
Referenced by distribute_food(), get_available_missions_by_dir(), has_provides(), has_water(), and recruit_evaluation().
has_provides() [2/2]
bool basecamp::has_provides (const std::string & req, const std::optional< point > & dir = std::nullopt, int level = 0) const
Definition at line 298 of file basecamp.cpp.
 {
     if( !dir ) {
         for( const auto &e : expansions ) {
             if( has_provides( req, e.second, level ) ) {
                 return true;
             }
         }
     } else {
         const auto &e = expansions.find( *dir );
         if( e != expansions.end() ) {
             return has_provides( req, e->second, level );
         }
     }
     return false;
 }
References expansions, and has_provides().
has_water()
bool basecamp::has_water () const
Definition at line 316 of file basecamp.cpp.
 {
     // special case required for fbmh_well_north constructed between b9162 (Jun 16, 2019) and b9644 (Sep 20, 2019)
     return has_provides( "water_well" ) || has_provides( "fbmh_well_north" );
 }
References has_provides().
Referenced by npc::consume_food_from_camp(), and finish_return().
hide_mission()
void basecamp::hide_mission (ui_mission_id id)
Definition at line 557 of file basecamp.cpp.
 {
     const base_camps::direction_data &base_data = base_camps::all_directions.at( id.id.dir.value() );
     for( ui_mission_id &miss_id : hidden_missions[size_t( base_data.tab_order )] ) {
         if( is_equal( miss_id, id ) ) {
             return;
         }  //  The UI shouldn't allow us to hide something already hidden, but check anyway.
     }
     hidden_missions[size_t( base_data.tab_order )].push_back( id );
 }
References base_camps::all_directions, hidden_missions, is_equal(), and base_camps::direction_data::tab_order.
hunting_results()
void basecamp::hunting_results (int skill, const mission_id & miss_id, int attempts, int difficulty)
spawn items or corpses based on search attempts
Parameters
skill skill level of the search
task string to identify what types of corpses to provide (_faction_camp_hunting or _faction_camp_trapping)
attempts number of skill checks to make
difficulty a random number from 0 to difficulty is created for each attempt, and if skill is higher, an item or corpse is spawned
Definition at line 4711 of file faction_camp.cpp.
 {
     // corpses do not exist as discrete items, so we use monster groups instead
     int base_group_chance = GROUP_CAMP_HUNTING->freq_total;
     int mission_specific_chance = 0;
     mongroup_id mission_specific_group;
     if( miss_id.id == Camp_Trapping ) {
         mission_specific_group = GROUP_CAMP_TRAPPING;
         mission_specific_chance += GROUP_CAMP_TRAPPING->freq_total;
     } else if( miss_id.id == Camp_Hunting ) {
         mission_specific_group = GROUP_CAMP_HUNTING_LARGE;
         mission_specific_chance += GROUP_CAMP_HUNTING_LARGE->freq_total;
     }
     const int total_chance = base_group_chance + mission_specific_chance;
     int successful_hunts = 0;
     for( int i = 0; i < attempts; i++ ) {
         if( skill > rng( 0, difficulty ) ) {
             successful_hunts++;
         }
     }
     if( successful_hunts <= 0 ) {
         return;
     }
     int results_from_base_group = 0;
     int results_from_mission_group = 0;
     for( ; successful_hunts > 0; successful_hunts-- ) {
         if( x_in_y( base_group_chance, total_chance ) ) {
             results_from_base_group++;
         } else {
             results_from_mission_group++;
         }
     }
     make_corpse_from_group( MonsterGroupManager::GetResultFromGroup( GROUP_CAMP_HUNTING,
                             &results_from_base_group ) );
     make_corpse_from_group( MonsterGroupManager::GetResultFromGroup( mission_specific_group,
                             &results_from_mission_group ) );
 }
References Camp_Hunting, Camp_Trapping, MonsterGroup::freq_total, MonsterGroupManager::GetResultFromGroup(), GROUP_CAMP_HUNTING, GROUP_CAMP_HUNTING_LARGE, GROUP_CAMP_TRAPPING, mission_id::id, make_corpse_from_group(), rng(), and x_in_y().
Referenced by gathering_return().
is_hidden()
bool basecamp::is_hidden (ui_mission_id id)
Definition at line 581 of file basecamp.cpp.
 {
     if( hidden_missions.empty() ) {
         return false;
     }
     const base_camps::direction_data &base_data = base_camps::all_directions.at( id.id.dir.value() );
     for( ui_mission_id &miss_id : hidden_missions[size_t( base_data.tab_order )] ) {
         if( is_equal( miss_id, id ) ) {
             return true;
         }
     }
     return false;
 }
References base_camps::all_directions, hidden_missions, is_equal(), and base_camps::direction_data::tab_order.
is_valid()
bool basecamp::is_valid () const inline
Definition at line 166 of file basecamp.h.
{
             return !name.empty() && omt_pos != tripoint_abs_omt();
         }
References name, and omt_pos.
Referenced by update_in_progress(), update_provides(), update_resources(), upgrade_return(), and game::validate_camps().
job_assignment_ui()
void basecamp::job_assignment_ui ()
Definition at line 2326 of file faction_camp.cpp.
 {
     int entries_per_page = 0;
     catacurses::window w_jobs;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         const point term( TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0,
                           TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0 );
         w_jobs = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                      point( term.y, term.x ) );
         entries_per_page = FULL_SCREEN_HEIGHT - 5;
         ui.position_from_window( w_jobs );
     } );
     ui.mark_resize();
     size_t selection = 0;
     input_context ctxt( "FACTION_MANAGER" );
     ctxt.register_action( "INSPECT_NPC" );
     ctxt.register_navigate_ui_list();
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     validate_assignees();
     std::vector<npc *> stationed_npcs;
     npc *cur_npc = nullptr;
     ui.on_redraw( [&]( const ui_adaptor & ) {
         werase( w_jobs );
         const size_t top_of_page = entries_per_page * ( selection / entries_per_page );
         for( int i = 0; i < FULL_SCREEN_HEIGHT - 2; i++ ) {
             mvwputch( w_jobs, point( 45, i ), BORDER_COLOR, LINE_XOXO );
         }
         draw_border( w_jobs );
         mvwprintz( w_jobs, point( 46, 1 ), c_white, _( "Job/Priority" ) );
         const nc_color col = c_white;
         const std::string no_npcs = _( "There are no NPCs stationed here" );
         if( !stationed_npcs.empty() ) {
             draw_scrollbar( w_jobs, selection, entries_per_page, stationed_npcs.size(),
                             point( 0, 3 ) );
             for( size_t i = top_of_page; i < stationed_npcs.size(); i++ ) {
                 const int y = i - top_of_page + 3;
                 trim_and_print( w_jobs, point( 1, y ), 43, selection == i ? hilite( col ) : col,
                                 stationed_npcs[i]->disp_name() );
             }
             if( selection < stationed_npcs.size() ) {
                 int start_y = 3;
                 if( cur_npc ) {
                     if( cur_npc->has_job() ) {
                         for( activity_id &elem : cur_npc->job.get_prioritised_vector() ) {
                             const int priority = cur_npc->job.get_priority_of_job( elem );
                             player_activity test_act = player_activity( elem );
                             mvwprintz( w_jobs, point( 46, start_y ), c_light_gray, string_format( _( "%s : %s" ),
                                        test_act.get_verb(), std::to_string( priority ) ) );
                             start_y++;
                         }
                     } else {
                         mvwprintz( w_jobs, point( 46, start_y ), c_light_red, _( "No current job." ) );
                     }
                 }
             } else {
                 mvwprintz( w_jobs, point( 46, 4 ), c_light_red, no_npcs );
             }
         } else {
             mvwprintz( w_jobs, point( 46, 4 ), c_light_red, no_npcs );
         }
         mvwprintz( w_jobs, point( 1, FULL_SCREEN_HEIGHT - 2 ), c_light_gray,
                    _( "Press %s to inspect this follower." ), ctxt.get_desc( "INSPECT_NPC" ) );
         mvwprintz( w_jobs, point( 1, FULL_SCREEN_HEIGHT - 1 ), c_light_gray,
                    _( "Press %s to change this workers job priorities." ), ctxt.get_desc( "CONFIRM" ) );
         wnoutrefresh( w_jobs );
     } );
     while( true ) {
         // create a list of npcs stationed at this camp
         stationed_npcs.clear();
         for( const auto &elem : get_npcs_assigned() ) {
             if( elem ) {
                 stationed_npcs.push_back( elem.get() );
             }
         }
         cur_npc = nullptr;
         // entries_per_page * page number
         if( !stationed_npcs.empty() ) {
             cur_npc = stationed_npcs[selection];
         }
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         if( action == "INSPECT_NPC" ) {
             if( cur_npc ) {
                 cur_npc->disp_info();
             }
         } else if( navigate_ui_list( action, selection, 5, stationed_npcs.size(), true ) ) {
         } else if( action == "CONFIRM" ) {
             if( cur_npc ) {
                 while( true ) {
                     uilist smenu;
                     smenu.text = _( "Assign job priority (0 to disable)" );
                     int count = 0;
                     std::vector<activity_id> job_vec = cur_npc->job.get_prioritised_vector();
                     smenu.addentry( count, true, 'C', _( "Clear all priorities" ) );
                     count++;
                     for( const activity_id &elem : job_vec ) {
                         player_activity test_act = player_activity( elem );
                         const int priority = cur_npc->job.get_priority_of_job( elem );
                         smenu.addentry( count, true, MENU_AUTOASSIGN, string_format( _( "%s : %s" ), test_act.get_verb(),
                                         std::to_string( priority ) ) );
                         count++;
                     }
                     smenu.query();
                     if( smenu.ret == UILIST_CANCEL ) {
                         break;
                     }
                     if( smenu.ret == 0 ) {
                         cur_npc->job.clear_all_priorities();
                     } else if( smenu.ret > 0 && smenu.ret <= static_cast<int>( job_vec.size() ) ) {
                         activity_id sel_job = job_vec[size_t( smenu.ret - 1 )];
                         player_activity test_act = player_activity( sel_job );
                         const std::string formatted = string_format( _( "Priority for %s " ), test_act.get_verb() );
                         const int amount = string_input_popup()
                                            .title( formatted )
                                            .width( 20 )
                                            .only_digits( true )
                                            .query_int();
                         cur_npc->job.set_task_priority( sel_job, amount );
                     } else {
                         break;
                     }
                 }
             }
         } else if( action == "QUIT" ) {
             break;
         }
     }
 }
References _, action, uilist::addentry(), BORDER_COLOR, c_light_gray, c_light_red, c_white, job_data::clear_all_priorities(), Character::disp_info(), draw_border(), draw_scrollbar(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, input_context::get_desc(), get_npcs_assigned(), job_data::get_prioritised_vector(), job_data::get_priority_of_job(), player_activity::get_verb(), input_context::handle_input(), npc::has_job(), hilite(), npc::job, LINE_XOXO, MENU_AUTOASSIGN, mvwprintz(), mvwputch(), navigate_ui_list(), catacurses::newwin(), string_input_popup::only_digits(), point, uilist::query(), string_input_popup::query_int(), ui_manager::redraw(), input_context::register_action(), input_context::register_navigate_ui_list(), uilist::ret, job_data::set_task_priority(), string_format(), TERMX, TERMY, uilist::text, string_input_popup::title(), to_string(), trim_and_print(), UILIST_CANCEL, validate_assignees(), catacurses::werase(), string_input_popup::width(), catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by talk_function::assign_camp(), and handle_mission().
load_data()
void basecamp::load_data (const std::string & data)
Definition at line 860 of file basecamp.cpp.
 {
     std::stringstream stream( data );
     stream >> name >> bb_pos.x >> bb_pos.y;
     // add space to name
     replace( name.begin(), name.end(), '_', ' ' );
 }
References bb_pos, name, tripoint::x, and tripoint::y.
make_corpse_from_group()
void basecamp::make_corpse_from_group (const std::vector< MonsterGroupResult > & group)
Definition at line 4752 of file faction_camp.cpp.
 {
     for( const MonsterGroupResult &monster : group ) {
         const mtype_id target = monster.name;
         item result = item::make_corpse( target, calendar::turn, "" );
         if( !result.is_null() ) {
             int num_to_spawn = monster.pack_size;
             do {
                 place_results( result );
                 num_to_spawn--;
             } while( num_to_spawn > 0 );
         }
     }
 }
References item::is_null(), item::make_corpse(), monster::name(), place_results(), and calendar::turn.
Referenced by hunting_results().
make_fake_food()
item basecamp::make_fake_food (const nutrients & to_use) const
Definition at line 5653 of file faction_camp.cpp.
 {
     // This is dumb, but effective.
     std::string food_id = "camp_meal_small";
     if( to_use.kcal() > 3000 ) {
         food_id = "camp_meal_large";
     } else if( to_use.kcal() > 1000 ) {
         food_id = "camp_meal_medium";
     }
     item food_item( food_id );
     // Set the default nutritional of the item.
     // This doesn't persist through save/load, but that's ok, we will be eating it immediately.
     food_item.get_comestible()->default_nutrition = to_use;
     return food_item;
 }
References item::get_comestible(), and nutrients::kcal().
Referenced by feed_workers().
menial_return()
bool basecamp::menial_return (const mission_id & miss_id)
Definition at line 3950 of file faction_camp.cpp.
 {
     const std::string msg = _( "returns from doing the dirty work to keep the camp running" );
     npc_ptr comp = mission_return( miss_id,
                                    3_hours, true, msg, skill_menial.str(), 2 );
     if( comp == nullptr ) {
         return false;
     }
     comp->revert_after_activity();
     return true;
 }
References _, mission_return(), skill_menial, and string_id< T >::str().
Referenced by handle_mission().
mission_return()
npc_ptr basecamp::mission_return (const mission_id & miss_id, time_duration min_duration, bool fixed_time, const std::string & return_msg, const std::string & skill, int difficulty)
a wrapper function for companion_choose_return and finish_return
Definition at line 3819 of file faction_camp.cpp.
 {
     npc_ptr comp = companion_choose_return( miss_id, min_duration );
     if( comp != nullptr ) {
         finish_return( *comp, fixed_time, return_msg, skill, difficulty );
     }
     return comp;
 }
References companion_choose_return(), and finish_return().
Referenced by handle_mission(), menial_return(), and recruit_return().
name_display_of()
std::string basecamp::name_display_of (const mission_id & miss_id)
Definition at line 5794 of file faction_camp.cpp.
 {
     const std::string dir_abbr = base_camps::all_directions.at(
                                      miss_id.dir.value() ).bracket_abbr.translated();
     std::vector<basecamp_upgrade> upgrades;
     std::vector<std::string> pos_names;
     switch( miss_id.id ) {
         case No_Mission:
         case Scavenging_Patrol_Job:
         case Scavenging_Raid_Job:
         case Menial_Job:
         case Carpentry_Job:
         case Forage_Job:
         case Caravan_Commune_Center_Job:
         //  Faction camp tasks
         case Camp_Distribute_Food:
         case Camp_Determine_Leadership:
         case Camp_Have_Meal:
         case Camp_Hide_Mission:
         case Camp_Reveal_Mission:
         case Camp_Assign_Jobs:
         case Camp_Assign_Workers:
         case Camp_Abandon:
         case Camp_Emergency_Recall:
         case Camp_Gather_Materials:
         case Camp_Collect_Firewood:
         case Camp_Menial:
         case Camp_Survey_Field:
         case Camp_Survey_Expansion:
         case Camp_Cut_Logs:
         case Camp_Clearcut:
         case Camp_Setup_Hide_Site:
         case Camp_Relay_Hide_Site:
         case Camp_Foraging:
         case Camp_Trapping:
         case Camp_Hunting:
         case Camp_OM_Fortifications:
         case Camp_Recruiting:
         case Camp_Scouting:
         case Camp_Combat_Patrol:
         case Camp_Chop_Shop:
         case Camp_Plow:
         case Camp_Plant:
         case Camp_Harvest:
             return mission_ui_activity_of( miss_id );
         case Camp_Upgrade: {
             upgrades = available_upgrades( miss_id.dir.value() );
             auto upgrade_it = std::find_if(
                                   upgrades.begin(), upgrades.end(),
             [&]( const basecamp_upgrade & upgrade ) {
                 return upgrade.bldg == miss_id.parameters;
             } );
             if( upgrade_it == upgrades.end() ) {
                 return mission_ui_activity_of( miss_id ) + _( "<No longer valid construction>" );
             }
             std::string result = mission_ui_activity_of( miss_id ) + upgrade_it->name;
             const recipe &rec = *recipe_id( upgrade_it->bldg );
             for( const std::pair<const std::string, cata_variant> &arg : miss_id.mapgen_args.map ) {
                 result +=
                     string_format(
                         " (%s)", rec.blueprint_parameter_ui_string( arg.first, arg.second ) );
             }
             return result;
         }
         case Camp_Crafting: {
             const std::string dir_id = base_camps::all_directions.at( miss_id.dir.value() ).id;
             const std::string dir_abbr = base_camps::all_directions.at(
                                              miss_id.dir.value() ).bracket_abbr.translated();
             const std::map<recipe_id, translation> &recipes = recipe_deck( miss_id.dir.value() );
             const auto it = recipes.find( recipe_id( miss_id.parameters ) );
             if( it != recipes.end() ) {
                 return dir_abbr + it->second;
             } else {
                 return dir_abbr + _( " <Unsupported recipe>" );
             }
         }
         default:
             return "";
     }
 }
References _, base_camps::all_directions, available_upgrades(), recipe::blueprint_parameter_ui_string(), Camp_Abandon, Camp_Assign_Jobs, Camp_Assign_Workers, Camp_Chop_Shop, Camp_Clearcut, Camp_Collect_Firewood, Camp_Combat_Patrol, Camp_Crafting, Camp_Cut_Logs, Camp_Determine_Leadership, Camp_Distribute_Food, Camp_Emergency_Recall, Camp_Foraging, Camp_Gather_Materials, Camp_Harvest, Camp_Have_Meal, Camp_Hide_Mission, Camp_Hunting, Camp_Menial, Camp_OM_Fortifications, Camp_Plant, Camp_Plow, Camp_Recruiting, Camp_Relay_Hide_Site, Camp_Reveal_Mission, Camp_Scouting, Camp_Setup_Hide_Site, Camp_Survey_Expansion, Camp_Survey_Field, Camp_Trapping, Camp_Upgrade, Caravan_Commune_Center_Job, Carpentry_Job, mission_id::dir, Forage_Job, mission_id::id, mapgen_arguments::map, mission_id::mapgen_args, Menial_Job, mission_ui_activity_of(), No_Mission, mission_id::parameters, recipe_deck(), Scavenging_Patrol_Job, Scavenging_Raid_Job, string_format(), and spell_effect::upgrade().
Referenced by get_available_missions(), get_available_missions_by_dir(), handle_hide_mission(), and handle_reveal_mission().
next_upgrade()
std::string basecamp::next_upgrade (const point & dir, int offset = 1) const
Returns the name of the building the current building dir upgrades into, "null" if there isn't one.
Definition at line 265 of file basecamp.cpp.
 {
     const auto &e = expansions.find( dir );
     if( e == expansions.end() ) {
         return "null";
     }
     const expansion_data &e_data = e->second;
     int cur_level = -1;
     for( int i = 0; i < base_camps::max_upgrade_by_type( e_data.type ); i++ ) {
         const std::string candidate = base_camps::faction_encode_abs( e_data, i );
         if( e_data.provides.find( candidate ) == e_data.provides.end() ) {
             break;
         } else {
             cur_level = i;
         }
     }
     if( cur_level >= 0 ) {
         return base_camps::faction_encode_abs( e_data, cur_level + offset );
     }
     return "null";
 }
References expansions, base_camps::faction_encode_abs(), base_camps::max_upgrade_by_type(), expansion_data::provides, and expansion_data::type.
Referenced by faction_display(), and upgrade_return().
om_upgrade_description()
std::string basecamp::om_upgrade_description (const std::string & bldg, const mapgen_arguments & args, bool trunc = false) const
Returns the description for the recipe of the next building bldg.
Definition at line 219 of file basecamp.cpp.
 {
     const recipe &making = recipe_id( bldg ).obj();
     const requirement_data *reqs;
     time_duration base_time;
     const std::map<skill_id, int> *skills;
     if( making.is_blueprint() ) {
         auto req_it = making.blueprint_build_reqs().reqs_by_parameters.find( args );
         cata_assert( req_it != making.blueprint_build_reqs().reqs_by_parameters.end() );
         const build_reqs &bld_reqs = req_it->second;
         reqs = &bld_reqs.consolidated_reqs;
         base_time = time_duration::from_moves( bld_reqs.time );
         skills = &bld_reqs.skills;
     } else {
         reqs = &making.simple_requirements();
         base_time = making.batch_duration( get_player_character() );
         skills = &making.required_skills;
     }
     std::vector<std::string> component_print_buffer;
     const int pane = FULL_SCREEN_WIDTH;
     const auto tools = reqs->get_folded_tools_list( pane, c_white, _inv, 1 );
     const auto comps = reqs->get_folded_components_list( pane, c_white, _inv,
                        making.get_component_filter(), 1 );
     component_print_buffer.insert( component_print_buffer.end(), tools.begin(), tools.end() );
     component_print_buffer.insert( component_print_buffer.end(), comps.begin(), comps.end() );
     std::string comp;
     for( auto &elem : component_print_buffer ) {
         str_append( comp, elem, "\n" );
     }
     comp = string_format( _( "Notes:\n%s\n\nSkills used: %s\n%s\n" ),
                           making.description, making.required_all_skills_string( *skills ),
                           comp );
     if( !trunc ) {
         comp += string_format( _( "Risk: None\nTime: %s\n" ),
                                to_string( base_camps::to_workdays( base_time ) ) );
     }
     return comp;
 }
References _, _inv, recipe::batch_duration(), recipe::blueprint_build_reqs(), c_white, cata_assert, build_reqs::consolidated_reqs, recipe::description, time_duration::from_moves(), FULL_SCREEN_WIDTH, recipe::get_component_filter(), requirement_data::get_folded_components_list(), requirement_data::get_folded_tools_list(), get_player_character(), recipe::is_blueprint(), string_id< T >::obj(), parameterized_build_reqs::reqs_by_parameters, recipe::required_all_skills_string(), recipe::required_skills, recipe::simple_requirements(), build_reqs::skills, str_append(), string_format(), build_reqs::time, to_string(), base_camps::to_workdays(), and trunc().
Referenced by get_available_missions_by_dir().
parse_expansion()
expansion_data basecamp::parse_expansion (std::string_view terrain, const tripoint_abs_omt & new_pos)
Definition at line 154 of file basecamp.cpp.
 {
     expansion_data e;
     size_t last_bar = terrain.find_last_of( '_' );
     e.type = terrain.substr( base_camps::prefix_len, last_bar - base_camps::prefix_len );
     e.cur_level = std::stoi( str_cat( "0", terrain.substr( last_bar + 1 ) ) );
     e.pos = new_pos;
     return e;
 }
References expansion_data::cur_level, expansion_data::pos, base_camps::prefix_len, str_cat(), terrain, and expansion_data::type.
Referenced by add_expansion(), and define_camp().
place_results()
void basecamp::place_results (const item & result)
Definition at line 5964 of file faction_camp.cpp.
 {
     map &target_bay = get_camp_map();
     form_storage_zones( target_bay, target_bay.getglobal( target_bay.getlocal( bb_pos ) ) );
     tripoint new_spot = target_bay.getlocal( get_dumping_spot() );
     // Special handling for liquids
     // find any storage-zoned LIQUIDCONT we can dump them in, set that as the item's destination instead
     if( result.made_of( phase_id::LIQUID ) ) {
         for( tripoint_abs_ms potential_spot : get_liquid_dumping_spot() ) {
             // No items at a potential spot? Set the destination there and stop checking.
             // We could check if the item at the tile are the same as the item we're placing, but liquids of the same typeid
             // don't always mix depending on their components...
             if( target_bay.i_at( target_bay.getlocal( potential_spot ) ).empty() ) {
                 new_spot = target_bay.getlocal( potential_spot );
                 break;
             }
             // We've processed the last spot and haven't found anywhere to put it, we'll end up using dumping_spot.
             // Throw a warning to let players know what's going on. Unfortunately we can't back out of finishing the mission this deep in the process.
             if( potential_spot == get_liquid_dumping_spot().back() ) {
                 popup( _( "No eligible locations found to place resulting liquids, placing them at random.\n\nEligible locations must be a terrain OR furniture (not item) that can contain liquid, and does not already have any items on its tile." ) );
             }
         }
     }
     target_bay.add_item_or_charges( new_spot, result, true );
     apply_camp_ownership( target_bay, new_spot, 10 );
     target_bay.save();
 }
References _, map::add_item_or_charges(), apply_camp_ownership(), bb_pos, item_stack::empty(), form_storage_zones(), get_camp_map(), get_dumping_spot(), get_liquid_dumping_spot(), map::getglobal(), map::getlocal(), map::i_at(), LIQUID, item::made_of(), popup(), and map::save().
Referenced by finish_return(), make_corpse_from_group(), and search_results().
player_eats_meal()
void basecamp::player_eats_meal ()
Definition at line 1700 of file faction_camp.cpp.
 {
     int kcal_to_eat = 3000;
     Character &you = get_player_character();
     const int &food_available = fac()->food_supply.kcal();
     if( food_available <= 0 ) {
         popup( _( "You check storage for some food, but there is nothing but dust and cobwebs" ) );
         return;
     } else if( food_available <= kcal_to_eat ) {
         add_msg( _( "There's only one meal left.  Guess that's dinner!" ) );
         kcal_to_eat = food_available;
     }
     nutrients dinner = camp_food_supply( -kcal_to_eat );
     feed_workers( you, dinner, true );
 }
References _, add_msg(), camp_food_supply(), fac(), feed_workers(), faction_template::food_supply, get_player_character(), nutrients::kcal(), and popup().
Referenced by handle_mission().
point_within_camp()
bool basecamp::point_within_camp (const tripoint_abs_omt & p) const
Definition at line 852 of file basecamp.cpp.
 {
     return std::any_of( expansions.begin(), expansions.end(), [ p ]( auto & e ) {
         return p == e.second.pos;
     } );
 }
References expansions.
query_new_name()
void basecamp::query_new_name (bool force = false)
Definition at line 611 of file basecamp.cpp.
 {
     string_input_popup input_popup;
     bool done = false;
     bool need_input = true;
     do {
         input_popup.title( _( "Name this camp" ) )
         .width( 40 )
         .max_length( 25 )
         .query();
         if( input_popup.canceled() || input_popup.text().empty() ) {
             if( name.empty() || force ) {
                 popup( _( "You need to input the base camp name." ) );
             } else {
                 need_input = false;
             }
         } else {
             done = true;
         }
     } while( !done && need_input );
     if( done ) {
         name = input_popup.text();
     }
 }
References _, string_input_popup::canceled(), force, string_input_popup::max_length(), name, popup(), string_input_popup::query(), string_input_popup::text(), string_input_popup::title(), and string_input_popup::width().
Referenced by define_camp(), and faction_manager::display().
recipe_batch_max()
int basecamp::recipe_batch_max (const recipe & making) const
Definition at line 4677 of file faction_camp.cpp.
 {
     int max_batch = 0;
     const int max_checks = 9;
     for( size_t batch_size = 1000; batch_size > 0; batch_size /= 10 ) {
         for( int iter = 0; iter < max_checks; iter++ ) {
             time_duration work_days = base_camps::to_workdays( making.batch_duration(
                                           get_player_character(), max_batch + batch_size ) );
             int food_req = time_to_food( work_days );
             bool can_make = making.deduped_requirements().can_make_with_inventory(
                                 _inv, making.get_component_filter(), max_batch + batch_size );
             if( can_make && fac()->food_supply.kcal() > food_req ) {
                 max_batch += batch_size;
             } else {
                 break;
             }
         }
     }
     return max_batch;
 }
References _inv, recipe::batch_duration(), deduped_requirement_data::can_make_with_inventory(), recipe::deduped_requirements(), fac(), recipe::get_component_filter(), get_player_character(), time_to_food(), and base_camps::to_workdays().
Referenced by start_crafting().
recipe_deck() [1/2]
std::map< recipe_id, translation > basecamp::recipe_deck (const point & dir) const
Definition at line 388 of file basecamp.cpp.
 {
     std::map<recipe_id, translation> recipes;
     const auto &e = expansions.find( dir );
     if( e == expansions.end() ) {
         return recipes;
     }
     for( const auto &provides : e->second.provides ) {
         const auto &test_s = recipe_group::get_recipes_by_id( provides.first );
         recipes.insert( test_s.cbegin(), test_s.cend() );
     }
     return recipes;
 }
References expansions, and recipe_group::get_recipes_by_id().
Referenced by get_available_missions_by_dir(), name_display_of(), and start_crafting().
recipe_deck() [2/2]
std::map< recipe_id, translation > basecamp::recipe_deck (const std::string & bldg) const
Definition at line 402 of file basecamp.cpp.
 {
     return recipe_group::get_recipes_by_bldg( bldg );
 }
References recipe_group::get_recipes_by_bldg().
recruit_description()
std::string basecamp::recruit_description (int npc_count) const
Definition at line 5441 of file faction_camp.cpp.
 {
     int sbase;
     int sexpansions;
     int sfaction;
     int sbonus;
     int total = recruit_evaluation( sbase, sexpansions, sfaction, sbonus );
     std::string desc = string_format( _( "Notes:\n"
                                          "Recruiting additional followers is very dangerous and "
                                          "expensive.  The outcome is heavily dependent on the "
                                          "skill of the companion you send and the appeal of "
                                          "your base.\n\n"
                                          "Skill used: social\n"
                                          "Difficulty: 2\n"
                                          "Base Score:                   +%3d%%\n"
                                          "> Expansion Bonus:            +%3d%%\n"
                                          "> Faction Bonus:              +%3d%%\n"
                                          "> Special Bonus:              +%3d%%\n\n"
                                          "Total: Skill                  +%3d%%\n\n"
                                          "Risk: High\n"
                                          "Time: 4 Days\n"
                                          "Positions: %d/1\n" ), sbase, sexpansions, sfaction,
                                       sbonus, total, npc_count );
     return desc;
 }
References _, recruit_evaluation(), and string_format().
Referenced by get_available_missions_by_dir().
recruit_evaluation() [1/2]
int basecamp::recruit_evaluation () const
Definition at line 5432 of file faction_camp.cpp.
 {
     int sbase;
     int sexpansions;
     int sfaction;
     int sbonus;
     return recruit_evaluation( sbase, sexpansions, sfaction, sbonus );
 }
Referenced by handle_mission(), and recruit_description().
recruit_evaluation() [2/2]
int basecamp::recruit_evaluation (int & sbase, int & sexpansions, int & sfaction, int & sbonus) const
Definition at line 5390 of file faction_camp.cpp.
 {
     auto e = expansions.find( base_camps::base_dir );
     if( e == expansions.end() ) {
         sbase = 0;
         sexpansions = 0;
         sfaction = 0;
         sbonus = 0;
         return 0;
     }
     sbase = e->second.cur_level * 5;
     sexpansions = expansions.size() * 2;
     //How could we ever starve?
     //More than 5 farms at recruiting base
     int farm = 0;
     for( const point &dir : directions ) {
         if( has_provides( "farming", dir ) ) {
             farm++;
         }
     }
     sfaction = std::min( fac()->food_supply.kcal() / 10000, 10 );
     sfaction += std::min( camp_discipline() / 10, 5 );
     sfaction += std::min( camp_morale() / 10, 5 );
     //Secret or Hidden Bonus
     //Please avoid openly discussing so that there is some mystery to the system
     sbonus = 0;
     if( farm >= 5 ) {
         sbonus += 10;
     }
     //More machine than man
     //Bionics count > 10, respect > 75
     if( get_player_character().get_bionics().size() > 10 && camp_discipline() > 75 ) {
         sbonus += 10;
     }
     //Survival of the fittest
     if( g->get_kill_tracker().npc_kill_count() > 10 ) {
         sbonus += 10;
     }
     return sbase + sexpansions + sfaction + sbonus;
 }
References base_camps::base_dir, camp_discipline(), camp_morale(), directions, expansions, fac(), g, get_player_character(), has_provides(), min(), and om_direction::size.
recruit_return()
void basecamp::recruit_return (const mission_id & miss_id, int score)
Definition at line 4270 of file faction_camp.cpp.
 {
     const std::string msg = _( "returns from searching for recruits with "
                                "a bit more experience" );
     npc_ptr comp = mission_return( miss_id, 4_days, true, msg, skill_recruiting.str(), 2 );
     if( comp == nullptr ) {
         return;
     }
     npc_ptr recruit;
     //Success of finding an NPC to recruit, based on survival/tracking
     float skill = comp->get_skill_level( skill_survival );
     if( rng( 1, 20 ) + skill > 17 ) {
         recruit = make_shared_fast<npc>();
         recruit->normalize();
         recruit->randomize();
         popup( _( "%s encountered %s" ), comp->get_name(), recruit->get_name() );
     } else {
         popup( _( "%s didn't find anyone to recruit" ), comp->get_name() );
         return;
     }
     //Chance of convincing them to come back
     skill = ( 100 * comp->get_skill_level( skill_speech ) + score ) / 100;
     if( rng( 1, 20 ) + skill  > 19 ) {
         popup( _( "%s convinced %s to hear a recruitment offer from you" ), comp->get_name(),
                recruit->get_name() );
     } else {
         popup( _( "%s wasn't interested in anything %s had to offer" ), recruit->get_name(),
                comp->get_name() );
         return;
     }
     //Stat window
     int rec_m = 0;
     int appeal = rng( -5, 3 ) + std::min( skill / 3, 3.0f );
     int food_desire = rng( 0, 5 );
     while( true ) {
         std::string description = _( "NPC Overview:\n\n" );
         description += string_format( _( "Name:  %s\n\n" ), right_justify( recruit->get_name(), 20 ) );
         description += string_format( _( "Strength:        %10d\n" ), recruit->str_max );
         description += string_format( _( "Dexterity:       %10d\n" ), recruit->dex_max );
         description += string_format( _( "Intelligence:    %10d\n" ), recruit->int_max );
         description += string_format( _( "Perception:      %10d\n\n" ), recruit->per_max );
         description += _( "Top 3 Skills:\n" );
         const auto skillslist = Skill::get_skills_sorted_by(
         [&]( const Skill & a, const Skill & b ) {
             const int level_a = recruit->get_skill_level( a.ident() );
             const int level_b = recruit->get_skill_level( b.ident() );
             return localized_compare( std::make_pair( -level_a, a.name() ),
                                       std::make_pair( -level_b, b.name() ) );
         } );
         description += string_format( "%s:          %4d\n", right_justify( skillslist[0]->name(), 12 ),
                                       static_cast<int>( recruit->get_skill_level( skillslist[0]->ident() ) ) );
         description += string_format( "%s:          %4d\n", right_justify( skillslist[1]->name(), 12 ),
                                       static_cast<int>( recruit->get_skill_level( skillslist[1]->ident() ) ) );
         description += string_format( "%s:          %4d\n\n", right_justify( skillslist[2]->name(), 12 ),
                                       static_cast<int>( recruit->get_skill_level( skillslist[2]->ident() ) ) );
         description += _( "Asking for:\n" );
         description += string_format( _( "> Food:     %10d days\n\n" ), food_desire );
         description += string_format( _( "Faction Food:%9d days\n\n" ),
                                       camp_food_supply_days( NO_EXERCISE ) );
         description += string_format( _( "Recruit Chance: %10d%%\n\n" ),
                                       std::min( 100 * ( 10 + appeal ) / 20, 100 ) );
         description += _( "Select an option:" );
         std::vector<std::string> rec_options;
         rec_options.emplace_back( _( "Increase Food" ) );
         rec_options.emplace_back( _( "Decrease Food" ) );
         rec_options.emplace_back( _( "Make Offer" ) );
         rec_options.emplace_back( _( "Not Interested" ) );
         rec_m = uilist( description, rec_options );
         if( rec_m < 0 || rec_m == 3 || static_cast<size_t>( rec_m ) >= rec_options.size() ) {
             popup( _( "You decide you aren't interested" ) );
             return;
         }
         if( rec_m == 0 && food_desire + 1 <= camp_food_supply_days( NO_EXERCISE ) ) {
             food_desire++;
             appeal++;
         }
         if( rec_m == 1 ) {
             if( food_desire > 0 ) {
                 food_desire--;
                 appeal--;
             }
         }
         if( rec_m == 2 ) {
             break;
         }
     }
     // Roll for recruitment
     if( rng( 1, 20 ) + appeal >= 10 ) {
         popup( _( "%s has been convinced to join!" ), recruit->get_name() );
     } else {
         popup( _( "%s wasn't interested" ), recruit->get_name() );
         // nullptr;
         return;
     }
     // Time durations always subtract from camp food supply
     camp_food_supply( 1_days * food_desire );
     avatar &player_character = get_avatar();
     recruit->spawn_at_precise( player_character.get_location() + point( -4, -4 ) );
     overmap_buffer.insert_npc( recruit );
     recruit->form_opinion( player_character );
     recruit->mission = NPC_MISSION_NULL;
     recruit->add_new_mission( mission::reserve_random( ORIGIN_ANY_NPC,
                               recruit->global_omt_location(),
                               recruit->getID() ) );
     talk_function::follow( *recruit );
     g->load_npcs();
 }
References _, a, b, camp_food_supply(), camp_food_supply_days(), talk_function::follow(), g, get_avatar(), Creature::get_location(), Skill::get_skills_sorted_by(), overmapbuffer::insert_npc(), localized_compare, min(), mission_return(), name, NO_EXERCISE, NPC_MISSION_NULL, ORIGIN_ANY_NPC, overmap_buffer, popup(), mission::reserve_random(), right_justify(), rng(), skill_recruiting, skill_speech, skill_survival, string_id< T >::str(), and string_format().
Referenced by handle_mission().
remove_assignee()
void basecamp::remove_assignee (character_id id)
Definition at line 510 of file basecamp.cpp.
 {
     npc_ptr npc_to_remove = overmap_buffer.find_npc( id );
     if( !npc_to_remove ) {
         debugmsg( "cant find npc to remove from basecamp, on the overmap_buffer" );
         return;
     }
     npc_to_remove->assigned_camp = std::nullopt;
     assigned_npcs.erase( std::remove( assigned_npcs.begin(), assigned_npcs.end(), npc_to_remove ),
                          assigned_npcs.end() );
 }
References assigned_npcs, debugmsg, overmapbuffer::find_npc(), and overmap_buffer.
reset_camp_resources()
void basecamp::reset_camp_resources (map & here) private
Definition at line 464 of file basecamp.cpp.
 {
     reset_camp_workers();
     for( auto &e : expansions ) {
         expansion_data &e_data = e.second;
         for( int level = 0; level <= e_data.cur_level; level++ ) {
             const std::string &bldg = base_camps::faction_encode_abs( e_data, level );
             if( bldg == "null" ) {
                 break;
             }
             update_provides( bldg, e_data );
         }
         for( const auto &bp_provides : e_data.provides ) {
             update_resources( bp_provides.first );
         }
         for( itype_id &it : e.second.available_pseudo_items ) {
             add_resource( it );
         }
     }
     form_crafting_inventory( here );
 }
References add_resource(), expansion_data::cur_level, expansions, base_camps::faction_encode_abs(), form_crafting_inventory(), expansion_data::provides, reset_camp_workers(), update_provides(), and update_resources().
Referenced by get_available_missions().
reset_camp_workers()
void basecamp::reset_camp_workers ()
Definition at line 488 of file basecamp.cpp.
 {
     camp_workers.clear();
     for( const auto &elem : overmap_buffer.get_companion_mission_npcs() ) {
         npc_companion_mission c_mission = elem->get_companion_mission();
         if( c_mission.position == omt_pos && c_mission.role_id == "FACTION_CAMP" ) {
             camp_workers.push_back( elem );
         }
     }
 }
References camp_workers, overmapbuffer::get_companion_mission_npcs(), omt_pos, overmap_buffer, npc_companion_mission::position, and npc_companion_mission::role_id.
Referenced by reset_camp_resources().
reveal_mission()
void basecamp::reveal_mission (ui_mission_id id)
Definition at line 568 of file basecamp.cpp.
 {
     const base_camps::direction_data &base_data = base_camps::all_directions.at( id.id.dir.value() );
     for( auto it = hidden_missions[size_t( base_data.tab_order )].begin();
          it != hidden_missions[size_t( base_data.tab_order )].end(); it++ ) {
         if( is_equal( id.id, it->id ) ) {
             hidden_missions[size_t( base_data.tab_order )].erase( it );
             return;
         }
     }
     debugmsg( "Trying to reveal revealed mission.  Has no effect." );
 }
References base_camps::all_directions, debugmsg, hidden_missions, is_equal(), and base_camps::direction_data::tab_order.
salt_water_pipe_return()
bool basecamp::salt_water_pipe_return (const mission_id & miss_id, const comp_list & npc_list)
Definition at line 4151 of file faction_camp.cpp.
 {
     const recipe &making = recipe_id( miss_id.parameters ).obj();
     const point dir = miss_id.dir.value();  //  Will always have a value
     expansion_salt_water_pipe *pipe = nullptr;
     bool found = false;
     for( expansion_salt_water_pipe *element : salt_water_pipes ) {
         if( element->expansion == dir ) {
             pipe = element;
             found = true;
             break;
         }
     }
     if( !found ) {
         popup( _( "Error: Failed to find the pipe task that was to be constructed" ) );
         return false;
     }
     point connection_dir = pipe->connection_direction;
     const int segment_number = salt_water_pipe_segment_of( making );
     if( segment_number == -1 ) {
         return false;
     }
     const point previous_construction_direction = { pipe->segments[segment_number - 1].point.x() - pipe->segments[segment_number].point.x(),
                                                     pipe->segments[segment_number - 1].point.y() - pipe->segments[segment_number].point.y()
                                                   };
     point next_construction_direction;
     if( segment_number == static_cast<int>( pipe->segments.size() - 1 ) ) {
         next_construction_direction = { -connection_dir.x, -connection_dir.y };
     } else {
         next_construction_direction = { pipe->segments[segment_number + 1].point.x() - pipe->segments[segment_number].point.x(),
                                         pipe->segments[segment_number + 1].point.y() - pipe->segments[segment_number].point.y()
                                       };
     }
     bool orthogonal = true;
     bool mirror_horizontal = false;
     bool mirror_vertical = false;
     int rotation = 0;
     salt_water_pipe_orientation_adjustment( previous_construction_direction, orthogonal,
                                             mirror_vertical, mirror_horizontal, rotation );
     if( orthogonal ) {
         const update_mapgen_id id{ faction_expansion_salt_water_pipe_N };
         run_mapgen_update_func( id, pipe->segments[segment_number].point, {}, nullptr, true,
                                 mirror_horizontal, mirror_vertical, rotation );
         apply_construction_marker( id, pipe->segments[segment_number].point,
                                    miss_id.mapgen_args, mirror_horizontal,
                                    mirror_vertical, rotation, false );
     } else {
         const update_mapgen_id id{ faction_expansion_salt_water_pipe_NE };
         run_mapgen_update_func( id, pipe->segments[segment_number].point, {}, nullptr, true,
                                 mirror_horizontal, mirror_vertical, rotation );
         apply_construction_marker( id, pipe->segments[segment_number].point,
                                    miss_id.mapgen_args, mirror_horizontal,
                                    mirror_vertical, rotation, false );
     }
     salt_water_pipe_orientation_adjustment( next_construction_direction, orthogonal, mirror_vertical,
                                             mirror_horizontal, rotation );
     if( orthogonal ) {
         const update_mapgen_id id{ faction_expansion_salt_water_pipe_N };
         run_mapgen_update_func( id, pipe->segments[segment_number].point, {}, nullptr, true,
                                 mirror_horizontal, mirror_vertical, rotation );
         apply_construction_marker( id, pipe->segments[segment_number].point,
                                    miss_id.mapgen_args, mirror_horizontal,
                                    mirror_vertical, rotation, false );
     } else {
         const update_mapgen_id id{ faction_expansion_salt_water_pipe_NE };
         run_mapgen_update_func( id, pipe->segments[segment_number].point, {}, nullptr, true,
                                 mirror_horizontal, mirror_vertical, rotation );
         apply_construction_marker( id, pipe->segments[segment_number].point,
                                    miss_id.mapgen_args, mirror_horizontal,
                                    mirror_vertical, rotation, false );
     }
     pipe->segments[segment_number].finished = true;
     auto e = expansions.find( dir );
     //  Should be safe as the caller has already checked the result. Repeating rather than adding an additional parameter to the function.
     size_t finished_segments = 0;
     for( std::vector<expansion_salt_water_pipe_segment>::iterator::value_type element :
          pipe->segments ) {
         if( element.finished ) {
             finished_segments++;
         }
     }
     //  This is the last segment, so we can now allow the salt water pump to be constructed.
     if( finished_segments == pipe->segments.size() ) {
         const std::string token = salt_water_pipe_string_base + "0" + salt_water_pipe_string_suffix;
         if( e->second.provides.find( token ) == e->second.provides.end() ) {
             e->second.provides[token] = 0;
         }
         e->second.provides[token]++;
     }
     update_provides( miss_id.parameters, e->second );
     update_resources( miss_id.parameters );
     for( const npc_ptr &comp : npc_list ) {
         finish_return( *comp, true, _( "returns from construction of a salt water pipe segment" ),
                        "construction", 2 );
     }
     return true;
 }
References _, apply_construction_marker(), expansion_salt_water_pipe::connection_direction, mission_id::dir, expansions, faction_expansion_salt_water_pipe_N, faction_expansion_salt_water_pipe_NE, finish_return(), mission_id::mapgen_args, string_id< T >::obj(), mission_id::parameters, popup(), run_mapgen_update_func(), salt_water_pipe_orientation_adjustment(), salt_water_pipe_segment_of(), salt_water_pipe_string_base, salt_water_pipe_string_suffix, salt_water_pipes, expansion_salt_water_pipe::segments, update_provides(), update_resources(), point::x, and point::y.
Referenced by upgrade_return().
salt_water_pipe_swamp_return()
bool basecamp::salt_water_pipe_swamp_return (const mission_id & miss_id, const comp_list & npc_list)
Definition at line 4060 of file faction_camp.cpp.
 {
     const point dir = miss_id.dir.value();  //  Will always have a value
     expansion_salt_water_pipe *pipe = nullptr;
     bool found = false;
     for( expansion_salt_water_pipe *element : salt_water_pipes ) {
         if( element->expansion == dir ) {
             pipe = element;
             found = true;
             break;
         }
     }
     if( !found ) {
         popup( _( "Error: Failed to find the pipe task that was to be constructed" ) );
         return false;
     }
     point connection_dir = pipe->connection_direction;
     const int segment_number = 0;
     point next_construction_direction;
     if( segment_number == pipe->segments.size() - 1 ) {
         next_construction_direction = { -connection_dir.x, -connection_dir.y };
     } else {
         next_construction_direction = { pipe->segments[segment_number + 1].point.x() - pipe->segments[segment_number].point.x(),
                                         pipe->segments[segment_number + 1].point.y() - pipe->segments[segment_number].point.y()
                                       };
     }
     bool orthogonal = true;
     bool mirror_horizontal = false;
     bool mirror_vertical = false;
     int rotation = 0;
     salt_water_pipe_orientation_adjustment( next_construction_direction, orthogonal, mirror_vertical,
                                             mirror_horizontal, rotation );
     if( orthogonal ) {
         const update_mapgen_id id{ faction_expansion_salt_water_pipe_swamp_N };
         run_mapgen_update_func( id, pipe->segments[segment_number].point, {}, nullptr, true,
                                 mirror_horizontal, mirror_vertical, rotation );
         apply_construction_marker( id, pipe->segments[segment_number].point,
                                    miss_id.mapgen_args, mirror_horizontal,
                                    mirror_vertical, rotation, false );
     } else {
         const update_mapgen_id id{ faction_expansion_salt_water_pipe_swamp_NE };
         run_mapgen_update_func( id, pipe->segments[segment_number].point, {}, nullptr, true,
                                 mirror_horizontal, mirror_vertical, rotation );
         apply_construction_marker( id, pipe->segments[segment_number].point,
                                    miss_id.mapgen_args, mirror_horizontal,
                                    mirror_vertical, rotation, false );
     }
     pipe->segments[segment_number].finished = true;
     auto e = expansions.find( dir );
     //  Should be safe as the caller has already checked the result. Repeating rather than adding an additional parameter to the function.
     size_t finished_segments = 0;
     for( std::vector<expansion_salt_water_pipe_segment>::iterator::value_type element :
          pipe->segments ) {
         if( element.finished ) {
             finished_segments++;
         }
     }
     //  This is the last segment, so we can now allow the salt water pump to be constructed.
     if( finished_segments == pipe->segments.size() ) {
         const std::string token = salt_water_pipe_string_base + "0" + salt_water_pipe_string_suffix;
         if( e->second.provides.find( token ) == e->second.provides.end() ) {
             e->second.provides[token] = 0;
         }
         e->second.provides[token]++;
     }
     update_provides( miss_id.parameters, e->second );
     update_resources( miss_id.parameters );
     for( const npc_ptr &comp : npc_list ) {
         finish_return( *comp, true,
                        _( "returns from construction of the salt water pipe swamp segment" ), "construction", 2 );
     }
     return true;
 }
References _, apply_construction_marker(), expansion_salt_water_pipe::connection_direction, mission_id::dir, expansions, faction_expansion_salt_water_pipe_swamp_N, faction_expansion_salt_water_pipe_swamp_NE, finish_return(), mission_id::mapgen_args, mission_id::parameters, popup(), run_mapgen_update_func(), salt_water_pipe_orientation_adjustment(), salt_water_pipe_string_base, salt_water_pipe_string_suffix, salt_water_pipes, expansion_salt_water_pipe::segments, update_provides(), update_resources(), point::x, and point::y.
Referenced by upgrade_return().
scan_pseudo_items()
void basecamp::scan_pseudo_items ()
Definition at line 2182 of file faction_camp.cpp.
 {
     for( auto &expansion : expansions ) {
         expansion.second.available_pseudo_items.clear();
         tripoint_abs_omt tile = tripoint_abs_omt( omt_pos.x() + expansion.first.x,
                                 omt_pos.y() + expansion.first.y, omt_pos.z() );
         tinymap expansion_map;
         expansion_map.load( tile, false );
         tripoint mapmin = tripoint( 0, 0, omt_pos.z() );
         tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_pos.z() );
         for( const tripoint &pos : expansion_map.points_in_rectangle( mapmin, mapmax ) ) {
             if( expansion_map.furn( pos ) != furn_str_id::NULL_ID() &&
                 expansion_map.furn( pos ).obj().crafting_pseudo_item.is_valid() &&
                 expansion_map.furn( pos ).obj().crafting_pseudo_item.obj().has_flag( flag_ALLOWS_REMOTE_USE ) ) {
                 bool found = false;
                 for( itype_id &element : expansion.second.available_pseudo_items ) {
                     if( element == expansion_map.furn( pos ).obj().crafting_pseudo_item ) {
                         found = true;
                         break;
                     }
                 }
                 if( !found ) {
                     expansion.second.available_pseudo_items.push_back( expansion_map.furn(
                                 pos ).obj().crafting_pseudo_item );
                 }
             }
             if( expansion_map.veh_at( pos ).has_value() &&
                 expansion_map.veh_at( pos )->vehicle().is_appliance() ) {
                 for( const auto &[tool, discard_] : expansion_map.veh_at( pos )->get_tools() ) {
                     if( tool.has_flag( flag_PSEUDO ) &&
                         tool.has_flag( flag_ALLOWS_REMOTE_USE ) ) {
                         bool found = false;
                         for( itype_id &element : expansion.second.available_pseudo_items ) {
                             if( element == tool.typeId() ) {
                                 found = true;
                                 break;
                             }
                         }
                         if( !found ) {
                             expansion.second.available_pseudo_items.push_back( tool.typeId() );
                         }
                     }
                 }
             }
         }
     }
 }
References furn_t::crafting_pseudo_item, expansions, flag_ALLOWS_REMOTE_USE, flag_PSEUDO, tinymap::furn(), itype::has_flag(), string_id< T >::is_valid(), tinymap::load(), string_id< furn_t >::NULL_ID(), int_id< T >::obj(), string_id< T >::obj(), omt_pos, tinymap::points_in_rectangle(), math_opers::pos(), SEEX, SEEY, tripoint, tinymap::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by iexamine::bulletin_board().
search_results()
void basecamp::search_results (int skill, const item_group_id & group_id, int attempts, int difficulty)
spawn items or corpses based on search attempts
Parameters
skill skill level of the search
group_id name of the item_group that provides the items
attempts number of skill checks to make
difficulty a random number from 0 to difficulty is created for each attempt, and if skill is higher, an item or corpse is spawned
Definition at line 4698 of file faction_camp.cpp.
 {
     for( int i = 0; i < attempts; i++ ) {
         if( skill > rng( 0, difficulty ) ) {
             item result = item_group::item_from( group_id, calendar::turn );
             if( !result.is_null() ) {
                 place_results( result );
             }
         }
     }
 }
References item::is_null(), item_group::item_from(), place_results(), rng(), and calendar::turn.
Referenced by gathering_return().
serialize()
void basecamp::serialize (JsonOut & json) const
Definition at line 4278 of file savegame_json.cpp.
 {
     if( omt_pos != tripoint_abs_omt() ) {
         json.start_object();
         json.member( "owner", owner );
         json.member( "name", name );
         json.member( "pos", omt_pos );
         json.member( "bb_pos", bb_pos );
         json.member( "dumping_spot", dumping_spot );
         json.member( "liquid_dumping_spots", liquid_dumping_spots );
         json.member( "hidden_missions" );
         json.start_array();
         for( const std::vector<ui_mission_id> &list : hidden_missions ) {
             json.start_object();
             json.member( "dir" );
             json.start_array();
             for( const ui_mission_id &miss_id : list ) {
                 json.start_object();
                 json.member( "mission_id", miss_id.id );
                 json.end_object();
             }
             json.end_array();
             json.end_object();
         }
         json.end_array();
         json.member( "expansions" );
         json.start_array();
         for( const auto &expansion : expansions ) {
             json.start_object();
             json.member( "dir", expansion.first );
             json.member( "type", expansion.second.type );
             json.member( "provides" );
             json.start_array();
             for( const auto &provide : expansion.second.provides ) {
                 json.start_object();
                 json.member( "id", provide.first );
                 json.member( "amount", provide.second );
                 json.end_object();
             }
             json.end_array();
             json.member( "in_progress" );
             json.start_array();
             for( const auto &working : expansion.second.in_progress ) {
                 json.start_object();
                 json.member( "id", working.first );
                 json.member( "amount", working.second );
                 json.end_object();
             }
             json.end_array();
             json.member( "pos", expansion.second.pos );
             json.end_object();
         }
         json.end_array();
         json.member( "fortifications" );
         json.start_array();
         for( const auto &fortification : fortifications ) {
             json.start_object();
             json.member( "pos", fortification );
             json.end_object();
         }
         json.end_array();
         json.member( "salt_water_pipes" );
         json.start_array();
         for( expansion_salt_water_pipe * const &pipe : salt_water_pipes ) {
             json.start_object();
             json.member( "expansion", pipe->expansion );
             json.member( "connection_direction", pipe->connection_direction );
             json.member( "segments" );
             json.start_array();
             for( const expansion_salt_water_pipe_segment &segment : pipe->segments ) {
                 json.start_object();
                 json.member( "point", segment.point );
                 json.member( "started", segment.started );
                 json.member( "finished", segment.finished );
                 json.end_object();
             }
             json.end_array();
             json.end_object();
         }
         json.end_array();
         json.end_object();
     } else {
         return;
     }
 }
References JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), om_direction::name(), JsonOut::start_array(), JsonOut::start_object(), and working.
set_bb_pos()
void basecamp::set_bb_pos (const tripoint & new_abs_pos) inline
Definition at line 189 of file basecamp.h.
{
             bb_pos = new_abs_pos;
         }
References bb_pos.
set_by_radio()
void basecamp::set_by_radio (bool access_by_radio)
Definition at line 145 of file basecamp.cpp.
 {
     by_radio = access_by_radio;
 }
References by_radio.
Referenced by talk_function::basecamp_mission(), and iexamine::bulletin_board().
set_dumping_spot()
void basecamp::set_dumping_spot (const tripoint_abs_ms & spot) inline
Definition at line 309 of file basecamp.h.
{
             dumping_spot = spot;
         }
References dumping_spot.
Referenced by form_storage_zones().
set_liquid_dumping_spot()
void basecamp::set_liquid_dumping_spot (const std::vector< tripoint_abs_ms > & liquid_dumps) inline
Definition at line 312 of file basecamp.h.
{
             // Nowhere qualified to dump liquid? Dump it wherever everything else goes.
             if( liquid_dumps.empty() ) {
                 liquid_dumping_spots.clear();
                 liquid_dumping_spots.emplace_back( dumping_spot );
                 return;
             } //else
             liquid_dumping_spots.clear();
             liquid_dumping_spots = liquid_dumps;
         }
References dumping_spot, and liquid_dumping_spots.
Referenced by form_storage_zones().
set_name()
void basecamp::set_name (const std::string & new_name)
Definition at line 636 of file basecamp.cpp.
 {
     name = new_name;
 }
References name.
Referenced by game::validate_camps().
set_owner()
void basecamp::set_owner (faction_id new_owner)
Definition at line 809 of file basecamp.cpp.
 {
     for( const std::pair<faction_id, faction> fac : g->faction_manager_ptr->all() ) {
         if( fac.first == new_owner ) {
             owner = new_owner;
             return;
         }
     }
     //Fallthrough, id must be invalid
     debugmsg( "Could not find matching faction for new owner's faction_id!" );
 }
References debugmsg, fac(), g, and owner.
Referenced by get_basecamp().
set_sort_points()
bool basecamp::set_sort_points ()
Invokes the zone manager and validates that the necessary sort zones exist.
Definition at line 5306 of file faction_camp.cpp.
 {
     popup( _( "Sorting zones have changed.  Please create some sorting zones.  "
               "You must create a camp food zone, and a camp storage zone." ) );
     g->zones_manager();
     return validate_sort_points();
 }
References _, g, popup(), and validate_sort_points().
Referenced by validate_sort_points().
set_storage_tiles()
void basecamp::set_storage_tiles (const std::unordered_set< tripoint_abs_ms > & tiles) inline
Definition at line 470 of file basecamp.h.
{
             src_set = tiles;
         }
References src_set.
Referenced by form_storage_zones().
set_storage_zone()
void basecamp::set_storage_zone (const std::vector< const zone_data * > & zones) inline
Definition at line 463 of file basecamp.h.
{
             storage_zones = zones;
         }
References storage_zones, and zones.
Referenced by form_storage_zones().
start_clearcut()
void basecamp::start_clearcut (const mission_id & miss_id, float exertion_level)
Definition at line 2602 of file faction_camp.cpp.
 {
     std::vector<std::string> log_sources = { "forest", "forest_thick", "forest_trail", "rural_road_forest", "rural_road_turn_forest", "rural_road_turn1_forest", "rural_road_3way_forest",
                                              "dirt_road_forest", "dirt_road_3way_forest", "dirt_road_turn_forest", "forest_trail_intersection", "special_forest", "special_forest_thick", "forest_trail_isolated", "forest_trail_end"
                                            };
     popup( _( "Forests are the only valid cutting locations, with forest dirt roads, forest rural roads, and trails being valid as well.  Note that it's likely both forest and field roads look exactly the same after having been cleared." ) );
     tripoint_abs_omt forest = om_target_tile( omt_pos, 1, 50, log_sources, ot_match_type::type );
     if( forest != tripoint_abs_omt( -999, -999, -999 ) ) {
         standard_npc sample_npc( "Temp" );
         sample_npc.set_fake( true );
         int tree_est = om_cutdown_trees_est( forest, 95 );
         int tree_young_est = om_harvest_ter_est( sample_npc, forest,
                              ter_t_tree_young, 95 );
         int dist = rl_dist( forest.xy(), omt_pos.xy() );
         //Very roughly what the player does + 6 hours for prep, clean up, breaks
         time_duration chop_time = 6_hours + 1_hours * tree_est + 7_minutes * tree_young_est;
         time_duration travel_time = companion_travel_time_calc( forest, omt_pos, 0_minutes, 2 );
         time_duration work_time = travel_time + chop_time;
         if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( work_time,
                        chop_time, travel_time, dist, 2, time_to_food( work_time, exertion_level ) ) ) ) {
             return;
         }
         npc_ptr comp = start_mission( miss_id,
                                       work_time,
                                       true, _( "departs to clear a forest" ), false, {},
                                       skill_fabrication, 1, exertion_level );
         if( comp != nullptr ) {
             om_cutdown_trees_trunks( forest, 95 );
             om_harvest_ter_break( *comp, forest, ter_t_tree_young, 95 );
             change_cleared_terrain( forest );
         }
     }
 }
References _, camp_trip_description(), change_cleared_terrain(), companion_travel_time_calc(), forest, om_cutdown_trees_est(), om_cutdown_trees_trunks(), om_harvest_ter_break(), om_harvest_ter_est(), om_target_tile(), omt_pos, popup(), query_yn(), rl_dist(), Creature::set_fake(), skill_fabrication, start_mission(), ter_t_tree_young, time_to_food(), type, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by handle_mission().
start_combat_mission()
void basecamp::start_combat_mission (const mission_id & miss_id, float exertion_level)
Definition at line 3461 of file faction_camp.cpp.
 {
     popup( _( "Select checkpoints until you reach maximum range or select the last point again "
               "to end." ) );
     tripoint_abs_omt start = omt_pos;
     std::vector<tripoint_abs_omt> scout_points = om_companion_path( start, 90, true );
     if( scout_points.empty() ) {
         return;
     }
     int dist = scout_points.size();
     int trips = 2;
     time_duration travel_time = companion_travel_time_calc( scout_points, 0_minutes, trips );
     if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( 0_hours, 0_hours,
                    travel_time, dist, trips, time_to_food( travel_time, exertion_level ) ) ) ) {
         return;
     }
     npc_ptr comp = start_mission( miss_id, travel_time, true, _( "departs on patrol" ),
                                   false, {}, skill_survival, 3, exertion_level );
     if( comp != nullptr ) {
         comp->companion_mission_points = scout_points;
     }
 }
References _, camp_trip_description(), companion_travel_time_calc(), om_companion_path(), omt_pos, popup(), query_yn(), skill_survival, start_mission(), and time_to_food().
Referenced by handle_mission().
start_crafting()
void basecamp::start_crafting (const std::string & type, const mission_id & miss_id)
Definition at line 3490 of file faction_camp.cpp.
 {
     const std::map<recipe_id, translation> &recipes = recipe_deck( type );
     const auto it = recipes.find( recipe_id( miss_id.parameters ) );
     if( it != recipes.end() ) {
         const recipe &making = it->first.obj();
         if( !making.deduped_requirements().can_make_with_inventory(
                 _inv, making.get_component_filter() ) ) {
             popup( _( "You don't have the materials to craft that" ) );
             return;
         }
         int batch_size = 1;
         string_input_popup popup_input;
         int batch_max = recipe_batch_max( making );
         const std::string title = string_format( _( "Batch crafting %s [MAX: %d]: " ),
                                   making.result_name( /*decorated=*/true ), batch_max );
         popup_input.title( title ).edit( batch_size );
         if( popup_input.canceled() || batch_size <= 0 ) {
             return;
         }
         if( batch_size > recipe_batch_max( making ) ) {
             popup( _( "Your batch is too large!" ) );
             return;
         }
         mapgen_arguments arg;  //  Created with a default value.
         basecamp_action_components components( making, arg, batch_size, *this );
         if( !components.choose_components() ) {
             return;
         }
         time_duration work_days = base_camps::to_workdays( making.batch_duration( get_player_character(),
                                   batch_size ) );
         npc_ptr comp = start_mission( miss_id, work_days, true,
                                       _( "begins to work" ), false, {}, making.exertion_level(),
                                       making.required_skills );
         if( comp != nullptr ) {
             components.consume_components();
             for( const item &results : making.create_results( batch_size ) ) {
                 comp->companion_mission_inv.add_item( results );
             }
             for( const item &byproducts : making.create_byproducts( batch_size ) ) {
                 comp->companion_mission_inv.add_item( byproducts );
             }
         }
         return;
     }
 }
References _, _inv, recipe::batch_duration(), deduped_requirement_data::can_make_with_inventory(), string_input_popup::canceled(), basecamp_action_components::choose_components(), basecamp_action_components::consume_components(), recipe::create_byproducts(), recipe::create_results(), recipe::deduped_requirements(), string_input_popup::edit(), recipe::exertion_level(), recipe::get_component_filter(), get_player_character(), mission_id::parameters, popup(), recipe_batch_max(), recipe_deck(), recipe::required_skills, recipe::result_name(), start_mission(), string_format(), music::title, string_input_popup::title(), base_camps::to_workdays(), and type.
Referenced by handle_mission().
start_cut_logs()
void basecamp::start_cut_logs (const mission_id & miss_id, float exertion_level)
Called when a companion is sent to cut logs.
Definition at line 2563 of file faction_camp.cpp.
 {
     std::vector<std::string> log_sources = { "forest", "forest_thick", "forest_trail", "rural_road_forest", "rural_road_turn_forest", "rural_road_turn1_forest", "rural_road_3way_forest",
                                              "dirt_road_forest", "dirt_road_3way_forest", "dirt_road_turn_forest", "forest_trail_intersection", "special_forest", "special_forest_thick", "forest_trail_isolated", "forest_trail_end"
                                            };
     popup( _( "Forests are the only valid cutting locations, with forest dirt roads, forest rural roads, and trails being valid as well.  Note that it's likely both forest and field roads look exactly the same after having been cleared." ) );
     tripoint_abs_omt forest = om_target_tile( omt_pos, 1, 50, log_sources, ot_match_type::type );
     if( forest != tripoint_abs_omt( -999, -999, -999 ) ) {
         standard_npc sample_npc( "Temp" );
         sample_npc.set_fake( true );
         int tree_est = om_cutdown_trees_est( forest, 50 );
         int tree_young_est = om_harvest_ter_est( sample_npc, forest,
                              ter_t_tree_young, 50 );
         int dist = rl_dist( forest.xy(), omt_pos.xy() );
         //Very roughly what the player does + 6 hours for prep, clean up, breaks
         time_duration chop_time = 6_hours + 1_hours * tree_est + 7_minutes * tree_young_est;
         int haul_items = 2 * tree_est + 3 * tree_young_est;
         time_duration travel_time = companion_travel_time_calc( forest, omt_pos, 0_minutes,
                                     2, haul_items );
         time_duration work_time = travel_time + chop_time;
         if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( work_time,
                        chop_time, travel_time, dist, 2, time_to_food( work_time, exertion_level ) ) ) ) {
             return;
         }
         npc_ptr comp = start_mission( miss_id,
                                       work_time, true,
                                       _( "departs to cut logs" ), false, {},
                                       skill_fabrication, 2, exertion_level );
         if( comp != nullptr ) {
             om_cutdown_trees_logs( forest, 50 );
             om_harvest_ter( *comp, forest, ter_t_tree_young, 50 );
             om_harvest_itm( comp, forest, 95 );
             comp->companion_mission_time_ret = calendar::turn + work_time;
             change_cleared_terrain( forest );
         }
     }
 }
References _, camp_trip_description(), change_cleared_terrain(), companion_travel_time_calc(), forest, om_cutdown_trees_est(), om_cutdown_trees_logs(), om_harvest_itm(), om_harvest_ter(), om_harvest_ter_est(), om_target_tile(), omt_pos, popup(), query_yn(), rl_dist(), Creature::set_fake(), skill_fabrication, start_mission(), ter_t_tree_young, time_to_food(), calendar::turn, type, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by handle_mission().
start_farm_op()
void basecamp::start_farm_op (const tripoint_abs_omt & omt_tgt, const mission_id & miss_id, float exertion_level)
Definition at line 3679 of file faction_camp.cpp.
 {
     farm_ops op = farm_ops::plow;
     if( miss_id.id == Camp_Plow ) {
         op = farm_ops::plow;
     } else if( miss_id.id == Camp_Plant ) {
         op = farm_ops::plant;
     } else if( miss_id.id == Camp_Harvest ) {
         op = farm_ops::harvest;
     } else {
         debugmsg( "Farm operations called with no matching operation" );
         return;
     }
     std::pair<size_t, std::string> farm_data = farm_action( omt_tgt, op );
     size_t plots_cnt = farm_data.first;
     if( !plots_cnt ) {
         return;
     }
     time_duration work = 0_minutes;
     switch( op ) {
         case farm_ops::harvest:
             work += 3_minutes * plots_cnt;
             start_mission( miss_id, work, true,
                            _( "begins to harvest the field" ), false, {}, skill_survival, 1, exertion_level );
             break;
         case farm_ops::plant: {
             inventory_filter_preset seed_filter( []( const item_location & loc ) {
                 return loc->is_seed() && loc->typeId() != itype_marloss_seed && loc->typeId() != itype_fungal_seeds;
             } );
             drop_locations seed_selection = give_basecamp_equipment( seed_filter,
                                             _( "Which seeds do you wish to have planted?" ), _( "Selected seeds" ),
                                             _( "You have no additional seeds to give your companions" ) );
             if( seed_selection.empty() ) {
                 return;
             }
             size_t seed_cnt = 0;
             std::vector<item *> to_plant;
             for( std::pair<item_location, int> &seeds : seed_selection ) {
                 size_t num_seeds = seeds.second;
                 item_location seed = seeds.first;
                 seed.overflow();
                 if( seed->count_by_charges() ) {
                     seed->charges = num_seeds;
                 }
                 to_plant.push_back( &*seed );
                 seed_cnt += num_seeds;
             }
             if( !seed_cnt ) {
                 return;
             }
             work += 1_minutes * seed_cnt;
             start_mission( miss_id, work, true,
                            _( "begins planting the field" ), false, to_plant,
                            skill_survival, 1, exertion_level );
             break;
         }
         case farm_ops::plow:
             work += 5_minutes * plots_cnt;
             start_mission( miss_id, work, true, _( "begins plowing the field" ), false, {}, exertion_level );
             break;
         default:
             debugmsg( "Farm operations called with no operation" );
     }
 }
References _, Camp_Harvest, Camp_Plant, Camp_Plow, debugmsg, farm_action(), give_basecamp_equipment(), harvest, mission_id::id, item::is_seed(), itype_fungal_seeds, itype_marloss_seed, plant, plow, iuse::seed(), skill_survival, start_mission(), and item::typeId().
Referenced by handle_mission().
start_fortifications()
void basecamp::start_fortifications (const mission_id & miss_id, float exertion_level)
Called when a companion is sent to start fortifications.
Definition at line 2811 of file faction_camp.cpp.
 {
     std::vector<std::string> allowed_locations = {
         "forest", "forest_thick", "forest_water", "forest_trail", "field"
     };
     popup( _( "Select a start and end point.  Line must be straight.  Fields, forests, and "
               "swamps are valid fortification locations.  In addition to existing fortification "
               "constructions." ) );
     tripoint_abs_omt start = om_target_tile( omt_pos, 2, 90, allowed_locations, ot_match_type::type );
     popup( _( "Select an end point." ) );
     tripoint_abs_omt stop = om_target_tile( omt_pos, 2, 90, allowed_locations, ot_match_type::type,
                                             true, false, start );
     if( start != tripoint_abs_omt( -999, -999, -999 ) &&
         stop != tripoint_abs_omt( -999, -999, -999 ) ) {
         const recipe &making = recipe_id( miss_id.parameters ).obj();
         bool change_x = start.x() != stop.x();
         bool change_y = start.y() != stop.y();
         if( change_x && change_y ) {
             popup( _( "Construction line must be straight!" ) );
             return;
         }
         if( miss_id.parameters == faction_wall_level_n_1_string ) {
             std::vector<tripoint_abs_omt> tmp_line = line_to( stop, start );
             int line_count = tmp_line.size();
             int yes_count = 0;
             for( tripoint_abs_omt &elem : tmp_line ) {
                 if( std::find( fortifications.begin(), fortifications.end(), elem ) != fortifications.end() ) {
                     yes_count += 1;
                 }
             }
             if( yes_count < line_count ) {
                 popup( _( "Spiked pits must be built over existing trenches!" ) );
                 return;
             }
         }
         std::vector<tripoint_abs_omt> fortify_om;
         if( ( change_x && stop.x() < start.x() ) || ( change_y && stop.y() < start.y() ) ) {
             //line_to doesn't include the origin point
             fortify_om.push_back( stop );
             std::vector<tripoint_abs_omt> tmp_line = line_to( stop, start );
             fortify_om.insert( fortify_om.end(), tmp_line.begin(), tmp_line.end() );
         } else {
             fortify_om.push_back( start );
             std::vector<tripoint_abs_omt> tmp_line = line_to( start, stop );
             fortify_om.insert( fortify_om.end(), tmp_line.begin(), tmp_line.end() );
         }
         int trips = 0;
         time_duration build_time = 0_hours;
         time_duration travel_time = 0_hours;
         int dist = 0;
         for( tripoint_abs_omt &fort_om : fortify_om ) {
             bool valid = false;
             const oter_id &omt_ref = overmap_buffer.ter( fort_om );
             for( const std::string &pos_om : allowed_locations ) {
                 if( omt_ref.id().c_str() == pos_om ) {
                     valid = true;
                     break;
                 }
             }
             if( !valid ) {
                 popup( _( "Invalid terrain in construction path." ) );
                 return;
             }
             trips += 2;
             build_time += making.batch_duration( get_player_character() );
             dist += rl_dist( fort_om.xy(), omt_pos.xy() );
             travel_time += companion_travel_time_calc( fort_om, omt_pos, 0_minutes, 2 );
         }
         time_duration total_time = base_camps::to_workdays( travel_time + build_time );
         int need_food = time_to_food( total_time, exertion_level );
         if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( total_time, build_time,
                        travel_time, dist, trips, need_food ) ) ) {
             return;
         } else if( !making.deduped_requirements().can_make_with_inventory( _inv,
                    making.get_component_filter(), ( fortify_om.size() * 2 ) - 2 ) ) {
             popup( _( "You don't have the material to build the fortification." ) );
             return;
         }
         const int batch_size = fortify_om.size() * 2 - 2;
         mapgen_arguments arg;  //  Created with a default value.
         basecamp_action_components components( making, arg, batch_size, *this );
         if( !components.choose_components() ) {
             return;
         }
         npc_ptr comp = start_mission(
                            miss_id, total_time, true,
                            _( "begins constructing fortifications" ), false, {},
                            exertion_level, making.required_skills );
         if( comp != nullptr ) {
             components.consume_components();
             for( tripoint_abs_omt &pt : fortify_om ) {
                 comp->companion_mission_points.push_back( pt );
             }
             apply_fortifications( miss_id, &comp, true );
         }
     }
 }
References _, _inv, apply_fortifications(), recipe::batch_duration(), string_id< T >::c_str(), camp_trip_description(), deduped_requirement_data::can_make_with_inventory(), basecamp_action_components::choose_components(), companion_travel_time_calc(), basecamp_action_components::consume_components(), recipe::deduped_requirements(), faction_wall_level_n_1_string, fortifications, recipe::get_component_filter(), get_player_character(), int_id< T >::id(), line_to(), need_food, string_id< T >::obj(), om_target_tile(), omt_pos, overmap_buffer, mission_id::parameters, popup(), query_yn(), recipe::required_skills, rl_dist(), start_mission(), overmapbuffer::ter(), time_to_food(), base_camps::to_workdays(), type, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by handle_mission().
start_menial_labor()
void basecamp::start_menial_labor ()
Definition at line 2468 of file faction_camp.cpp.
 {
     if( fac()->food_supply.kcal() < time_to_food( 3_hours ) ) {
         popup( _( "You don't have enough food stored to feed your companion." ) );
         return;
     }
     shared_ptr_fast<npc> comp = talk_function::companion_choose();
     if( comp == nullptr ) {
         return;
     }
     validate_sort_points();
     comp->assign_activity( ACT_MOVE_LOOT );
     popup( _( "%s goes off to clean toilets and sort loot." ), comp->disp_name() );
 }
References _, ACT_MOVE_LOOT, talk_function::companion_choose(), fac(), popup(), time_to_food(), and validate_sort_points().
Referenced by handle_mission().
start_mission() [1/2]
npc_ptr basecamp::start_mission (const mission_id & miss_id, time_duration duration, bool must_feed, const std::string & desc, bool group, const std::vector< item * > & equipment, const skill_id & skill_tested, int skill_level, float exertion_level)
generic mission start function that wraps individual mission
Definition at line 1964 of file faction_camp.cpp.
 {
     std::map<skill_id, int> required_skills;
     required_skills[ skill_tested ] = skill_level;
     return start_mission( miss_id, duration, must_feed, desc, false, equipment, exertion_level,
                           required_skills );
 }
Referenced by handle_mission(), start_clearcut(), start_combat_mission(), start_crafting(), start_cut_logs(), start_farm_op(), start_fortifications(), start_relay_hide_site(), and start_setup_hide_site().
start_mission() [2/2]
npc_ptr basecamp::start_mission (const mission_id & miss_id, time_duration duration, bool must_feed, const std::string & desc, bool group, const std::vector< item * > & equipment, float exertion_level, const std::map< skill_id, int > & required_skills = {})
Definition at line 1975 of file faction_camp.cpp.
 {
     if( must_feed && fac()->food_supply.kcal() < time_to_food( duration, exertion_level ) ) {
         popup( _( "You don't have enough food stored to feed your companion." ) );
         return nullptr;
     }
     npc_ptr comp = talk_function::individual_mission( omt_pos, base_camps::id, desc, miss_id,
                    false, equipment, required_skills );
     if( comp != nullptr ) {
         comp->companion_mission_time_ret = calendar::turn + duration;
         if( must_feed ) {
             feed_workers( *comp.get()->as_character(), camp_food_supply( duration, exertion_level ) );
         }
         if( !equipment.empty() ) {
             map &target_map = get_camp_map();
             std::vector<tripoint> src_set_pt;
             src_set_pt.resize( src_set.size() );
             for( const tripoint_abs_ms &p : src_set ) {
                 src_set_pt.emplace_back( target_map.getlocal( p ) );
             }
             for( item *i : equipment ) {
                 int count = i->count();
                 if( i->count_by_charges() ) {
                     target_map.use_charges( src_set_pt, i->typeId(), count );
                 } else {
                     target_map.use_amount( src_set_pt, i->typeId(), count );
                 }
             }
             target_map.save();
         }
     }
     return comp;
 }
References _, camp_food_supply(), fac(), feed_workers(), get_camp_map(), map::getlocal(), base_camps::id, talk_function::individual_mission(), omt_pos, popup(), map::save(), src_set, time_to_food(), calendar::turn, map::use_amount(), and map::use_charges().
start_multi_mission() [1/2]
comp_list basecamp::start_multi_mission (const mission_id & miss_id, bool must_feed, const std::string & desc, const skill_id & skill_tested, int skill_level)
Definition at line 2012 of file faction_camp.cpp.
 {
     std::map<skill_id, int> required_skills;
     required_skills[skill_tested] = skill_level;
     return start_multi_mission( miss_id, must_feed, desc, required_skills );
 }
Referenced by common_salt_water_pipe_construction(), and start_upgrade().
start_multi_mission() [2/2]
comp_list basecamp::start_multi_mission (const mission_id & miss_id, bool must_feed, const std::string & desc, const std::map< skill_id, int > & required_skills = {})
Definition at line 2022 of file faction_camp.cpp.
 {
     const recipe &making = *recipe_id( miss_id.parameters );
     auto req_it = making.blueprint_build_reqs().reqs_by_parameters.find( miss_id.mapgen_args );
     cata_assert( req_it != making.blueprint_build_reqs().reqs_by_parameters.end() );
     const build_reqs &bld_reqs = req_it->second;
     time_duration base_time = time_duration::from_moves( bld_reqs.time );
     comp_list result;
     time_duration work_days;
     while( true ) { //  We'll break out of the loop when all the workers have been assigned
         work_days = base_camps::to_workdays( base_time / ( result.size() + 1 ) );
         if( must_feed &&
             fac()->food_supply.kcal() < time_to_food( work_days * ( result.size() + 1 ),
                     making.exertion_level() ) ) {
             if( result.empty() ) {
                 popup( _( "You don't have enough food stored to feed your companion for this task." ) );
                 return result;
             } else {
                 popup( _( "You don't have enough food stored to feed a larger work crew." ) );
                 break;
             }
         }
         //  We should allocate the full set of tools to each companion sent off on a mission,
         //  but currently recipes only provides a function to check for the full set of requirement,
         //  with no access to the tool subset, so no tools are actually assigned.
         npc_ptr comp = talk_function::individual_mission( omt_pos, base_camps::id, desc, miss_id,
                        false, {}, required_skills, !result.empty() );
         if( comp == nullptr ) {
             break;
         } else {
             result.push_back( comp );
         }
     }
     if( result.empty() ) {
         return result;
     } else {
         work_days = base_camps::to_workdays( base_time / result.size() );
         for( npc_ptr &comp : result ) {
             comp->companion_mission_time_ret = calendar::turn + work_days;
         }
         if( must_feed ) {
             std::vector<std::reference_wrapper <Character>> work_party;
             for( npc_ptr &comp : result ) {
                 work_party.emplace_back( *comp.get()->as_character() );
             }
             feed_workers( work_party, camp_food_supply( work_days * result.size(), making.exertion_level() ) );
         }
         return result;
     }
 }
References _, Character::as_character(), recipe::blueprint_build_reqs(), camp_food_supply(), cata_assert, npc::companion_mission_time_ret, recipe::exertion_level(), fac(), feed_workers(), time_duration::from_moves(), base_camps::id, talk_function::individual_mission(), mission_id::mapgen_args, omt_pos, mission_id::parameters, popup(), parameterized_build_reqs::reqs_by_parameters, build_reqs::time, time_to_food(), base_camps::to_workdays(), and calendar::turn.
start_relay_hide_site()
void basecamp::start_relay_hide_site (const mission_id & miss_id, float exertion_level)
Definition at line 2686 of file faction_camp.cpp.
 {
     std::vector<std::string> hide_locations = { faction_hide_site_0_string };
     popup( _( "You must select an existing hide site." ) );
     tripoint_abs_omt forest = om_target_tile( omt_pos, 10, 90, hide_locations, ot_match_type::exact,
                               true, true, omt_pos, true );
     if( forest != tripoint_abs_omt( -999, -999, -999 ) ) {
         int dist = rl_dist( forest.xy(), omt_pos.xy() );
         Character *pc = &get_player_character();
         const inventory_filter_preset preset( []( const item_location & location ) {
             return !location->can_revive() && !location->will_spill();
         } );
         units::volume total_export_volume;
         units::mass total_export_mass;
         drop_locations losing_equipment = give_equipment( pc, preset,
                                           _( "These are the items you've selected so far." ), _( "Select items to send" ),
                                           total_export_volume, total_export_mass );
         //Check items in improvised shelters at hide site
         tinymap target_bay;
         target_bay.load( forest, false );
         units::volume total_import_volume;
         units::mass total_import_mass;
         drop_locations gaining_equipment = get_equipment( &target_bay, relay_site_stash, pc, preset,
                                            _( "These are the items you've selected so far." ), _( "Select items to bring back" ),
                                            total_import_volume, total_import_mass );
         if( !losing_equipment.empty() || !gaining_equipment.empty() ) {
             //Only get charged the greater trips since return is free for both
             int trips = std::max( om_carry_weight_to_trips( total_import_mass, total_import_volume, nullptr ),
                                   om_carry_weight_to_trips( total_export_mass, total_export_volume, nullptr ) );
             int haulage = trips <= 2 ? 0 : std::max( gaining_equipment.size(),
                           losing_equipment.size() );
             time_duration build_time =
                 5_minutes;  //  We're not actually constructing anything, just loading/unloading/performing very light maintenance
             time_duration travel_time = companion_travel_time_calc( forest, omt_pos, 0_minutes,
                                         trips, haulage );
             time_duration work_time = travel_time + build_time;
             if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( work_time, build_time,
                            travel_time, dist, trips, time_to_food( work_time, exertion_level ) ) ) ) {
                 return;
             }
             npc_ptr comp = start_mission( miss_id,
                                           work_time, true,
                                           _( "departs for the hide site" ), false, {},
                                           skill_survival, 3, exertion_level );
             if( comp != nullptr ) {
                 // recalculate trips based on actual load
                 trips = std::max( om_carry_weight_to_trips( total_import_mass, total_import_volume, comp ),
                                   om_carry_weight_to_trips( total_export_mass, total_export_volume, comp ) );
                 int haulage = trips <= 2 ? 0 : std::max( gaining_equipment.size(),
                               losing_equipment.size() );
                 work_time = companion_travel_time_calc( forest, omt_pos, 0_minutes, trips,
                                                         haulage ) + build_time;
                 comp->companion_mission_time_ret = calendar::turn + work_time;
                 om_set_hide_site( *comp, forest, losing_equipment, gaining_equipment );
             }
         } else {
             popup( _( "You need equipment to transport between the hide site" ) );
         }
     }
 }
References _, camp_trip_description(), companion_travel_time_calc(), exact, faction_hide_site_0_string, forest, get_equipment(), get_player_character(), give_equipment(), tinymap::load(), location, max(), om_carry_weight_to_trips(), om_set_hide_site(), om_target_tile(), omt_pos, popup(), query_yn(), relay_site_stash, rl_dist(), skill_survival, start_mission(), time_to_food(), calendar::turn, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by handle_mission().
start_salt_water_pipe()
void basecamp::start_salt_water_pipe (const mission_id & miss_id)
Definition at line 3239 of file faction_camp.cpp.
 {
     const point dir = miss_id.dir.value();  //  Will always have a value
     const recipe &making = recipe_id( miss_id.parameters ).obj();
     point connection_dir = connection_direction_of( dir, making );
     if( connection_dir.x == -999 && connection_dir.y == -999 ) {
         return;
     }
     expansion_salt_water_pipe *pipe = nullptr;
     bool pipe_is_new = true;
     for( expansion_salt_water_pipe *element : salt_water_pipes ) {
         if( element->expansion == dir ) {
             if( element->segments[0].finished ) {
                 debugmsg( "Trying to start construction of a salt water pipe that's already been constructed" );
                 return;
             }
             //  Assume we've started the construction but it has been cancelled.
             pipe = element;
             pipe_is_new = false;
             break;
         }
     }
     if( pipe_is_new ) {
         pipe = new expansion_salt_water_pipe;
         pipe->expansion = dir;
         pipe->connection_direction = connection_dir;
         std::string allowed_start_location =
             "forest_water";  //  That's what a swamp is called, for some reason.
         std::vector<std::string> allowed_locations = {
             "forest", "forest_thick", "forest_trail", "field", "road"
         };
         PathMap path_map;
         for( int i = -max_salt_water_pipe_distance; i <= max_salt_water_pipe_distance; i++ ) {
             for( int k = -max_salt_water_pipe_distance; k <= max_salt_water_pipe_distance; k++ ) {
                 tripoint_abs_omt tile = tripoint_abs_omt( omt_pos.x() + dir.x + connection_dir.x + i,
                                         omt_pos.y() + dir.y + connection_dir.y + k, omt_pos.z() );
                 const oter_id &omt_ref = overmap_buffer.ter( tile );
                 bool match = false;
                 for( const std::string &pos_om : allowed_locations ) {
                     if( omt_ref->get_type_id() == oter_type_str_id( pos_om ) ) {
                         match = true;
                         break;
                     }
                 }
                 if( match ) {
                     path_map[max_salt_water_pipe_distance + i][max_salt_water_pipe_distance + k] = salt_pipe_legal;
                 } else if( omt_ref->get_type_id() == oter_type_str_id( allowed_start_location ) ) {
                     path_map[max_salt_water_pipe_distance + i][max_salt_water_pipe_distance + k] = salt_pipe_swamp;
                 } else {
                     path_map[max_salt_water_pipe_distance + i][max_salt_water_pipe_distance + k] = salt_pipe_illegal;
                 }
                 //  if this is an expansion tile, forbid it. Only allocated ones have their type changed.
                 if( i >= -dir.x - connection_dir.x - 1 && i <= -dir.x - connection_dir.x + 1 &&
                     k >= -dir.y - connection_dir.y - 1 && k <= -dir.y - connection_dir.y + 1 ) {
                     path_map[max_salt_water_pipe_distance + i][max_salt_water_pipe_distance + k] = salt_pipe_illegal;
                 }
             }
         }
         if( path_map[max_salt_water_pipe_distance][max_salt_water_pipe_distance] == salt_pipe_illegal ) {
             auto e = expansions.find( dir );
             basecamp::update_provides( miss_id.parameters, e->second );
             popup( _( "This functionality cannot be constructed as the tile directly adjacent to "
                       "this expansion is not of a type a pipe can be constructed through.  Supported "
                       "terrain is forest, field, road, and swamp.  This recipe will now be "
                       "removed from the set of available recipes and won't show up again." ) );
             return;
         }
         point destination;
         double destination_cost = -10000.0;
         bool path_found = false;
         if( path_map[max_salt_water_pipe_distance][max_salt_water_pipe_distance] ==
             salt_pipe_swamp ) { //  The connection_dir tile is a swamp tile
             destination = point_zero;
             path_found = true;
         } else {
             path_map[max_salt_water_pipe_distance][max_salt_water_pipe_distance] =
                 1.0;  //  Always an orthogonal connection to the connection tile.
             for( int distance = 1; distance <= max_salt_water_pipe_length; distance++ ) {
                 int dist = distance > max_salt_water_pipe_distance ? max_salt_water_pipe_distance : distance;
                 for( int i = -dist; i <= dist; i++ ) { //  No path that can be extended can reach further than dist.
                     for( int k = -dist; k <= dist; k++ ) {
                         if( path_map[max_salt_water_pipe_distance + i][max_salt_water_pipe_distance + k] >
                             0.0 ) { // Tile has been assigned a distance and isn't a swamp
                             point temp = check_salt_pipe_neighbors( path_map, { i, k } );
                             if( temp != point( -999, -999 ) ) {
                                 if( path_map[max_salt_water_pipe_distance + temp.x][max_salt_water_pipe_distance + temp.y] >
                                     destination_cost ) {
                                     destination_cost = path_map[max_salt_water_pipe_distance + temp.x][max_salt_water_pipe_distance +
                                                        temp.y];
                                     destination = temp;
                                     path_found = true;
                                 }
                             }
                         }
                     }
                 }
             }
         }
         if( !path_found ) {
             auto e = expansions.find( dir );
             basecamp::update_provides( miss_id.parameters, e->second );
             popup( _( "This functionality cannot be constructed as no valid path to a swamp has "
                       "been found with a maximum length (20 tiles) at a maximum range of 10 tiles.  "
                       "Supported terrain is forest, field, and road.  This recipe will now be "
                       "removed from the set of available recipes and won't show up again." ) );
             return;
         };
         point candidate;
         //  Flip the sign of the starting swamp tile to fit the logic expecting positive values rather than check that it isn't the first one every time.
         path_map[max_salt_water_pipe_distance + destination.x][max_salt_water_pipe_distance + destination.y]
             = -path_map[max_salt_water_pipe_distance + destination.x][max_salt_water_pipe_distance +
                     destination.y];
         while( destination != point_zero ) {
             pipe->segments.push_back( { tripoint_abs_omt( omt_pos.x() + dir.x + connection_dir.x + destination.x, omt_pos.y() + dir.y + connection_dir.y + destination.y, omt_pos.z() ), false, false } );
             path_found = false;  //  Reuse of existing variable after its original usability has been passed.
             for( int i = -1; i <= 1; i++ ) {
                 for( int k = -1; k <= 1; k++ ) {
                     if( destination.x + i > -max_salt_water_pipe_distance &&
                         destination.x + i < max_salt_water_pipe_distance &&
                         destination.y + k > -max_salt_water_pipe_distance &&
                         destination.y + k < max_salt_water_pipe_distance ) {
                         if( path_map[max_salt_water_pipe_distance + destination.x + i][max_salt_water_pipe_distance +
                                 destination.y + k] > 0.0 &&
                             path_map[max_salt_water_pipe_distance + destination.x + i][max_salt_water_pipe_distance +
                                     destination.y + k] < path_map[max_salt_water_pipe_distance +
                                             destination.x][max_salt_water_pipe_distance + destination.y] ) {
                             if( path_found ) {
                                 if( path_map [max_salt_water_pipe_distance + candidate.x][max_salt_water_pipe_distance +
                                         candidate.y] >
                                     path_map[max_salt_water_pipe_distance + destination.x + i][max_salt_water_pipe_distance +
                                             destination.y + k] ) {
                                     candidate = destination + point( i, k );
                                 }
                             } else {
                                 candidate = destination +  point( i, k );
                                 path_found = true;
                             }
                         }
                     }
                 }
             }
             destination = candidate;
         }
         pipe->segments.push_back( { tripoint_abs_omt( omt_pos.x() + dir.x + connection_dir.x, omt_pos.y() + dir.y + connection_dir.y, omt_pos.z() ), false, false } );
     }
     if( common_salt_water_pipe_construction( miss_id, pipe, 0 ) ) {
         if( pipe_is_new ) {
             pipe->segments[0].started = true;
             salt_water_pipes.push_back( pipe );
             //  Provide "salt_water_pipe_*_scheduled" for all the segments needed.
             //  The guts of basecamp::update_provides modified to feed it generated tokens rather than
             //  those actually in the recipe, as the tokens needed can't be determined by the recipe.
             //  Shouldn't need to check that the tokens don't exist previously, so could just set them to 1.
             auto e = expansions.find( dir );
             for( size_t i = 1; i < pipe->segments.size(); i++ ) {
                 std::string token = salt_water_pipe_string_base;
                 token += std::to_string( i );
                 token += salt_water_pipe_string_suffix;
                 if( e->second.provides.find( token ) == e->second.provides.end() ) {
                     e->second.provides[token] = 0;
                 }
                 e->second.provides[token]++;
             }
         }
     } else if( pipe_is_new ) {
         delete pipe;
     }
 }
References _, check_salt_pipe_neighbors(), common_salt_water_pipe_construction(), expansion_salt_water_pipe::connection_direction, connection_direction_of(), debugmsg, mission_id::dir, expansion_salt_water_pipe::expansion, expansions, oter_t::get_type_id(), max_salt_water_pipe_distance, max_salt_water_pipe_length, string_id< T >::obj(), omt_pos, overmap_buffer, mission_id::parameters, point, point_zero, popup(), salt_pipe_illegal, salt_pipe_legal, salt_pipe_swamp, salt_water_pipe_string_base, salt_water_pipe_string_suffix, salt_water_pipes, expansion_salt_water_pipe::segments, temp, overmapbuffer::ter(), to_string(), update_provides(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), point::x, coords::coord_point_mut< Point, Subpoint, InBounds >::y(), point::y, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by start_upgrade().
start_setup_hide_site()
void basecamp::start_setup_hide_site (const mission_id & miss_id, float exertion_level)
Definition at line 2637 of file faction_camp.cpp.
 {
     std::vector<std::string> hide_locations = { "forest", "forest_thick", "forest_water", "forest_trail"
                                                 "field"
                                               };
     popup( _( "Forests, swamps, and fields are valid hide site locations." ) );
     tripoint_abs_omt forest = om_target_tile( omt_pos, 10, 90, hide_locations, ot_match_type::type,
                               true, true, omt_pos, true );
     if( forest != tripoint_abs_omt( -999, -999, -999 ) ) {
         int dist = rl_dist( forest.xy(), omt_pos.xy() );
         Character *pc = &get_player_character();
         const inventory_filter_preset preset( []( const item_location & location ) {
             return !location->can_revive() && !location->will_spill();
         } );
         units::volume total_volume;
         units::mass total_mass;
         drop_locations losing_equipment = give_equipment( pc, preset,
                                           _( "These are the items you've selected so far." ), _( "Select items to send" ), total_volume,
                                           total_mass );
         int trips = om_carry_weight_to_trips( total_mass, total_volume, nullptr );
         int haulage = trips <= 2 ? 0 : losing_equipment.size();
         time_duration build_time = 6_hours;
         time_duration travel_time = companion_travel_time_calc( forest, omt_pos, 0_minutes,
                                     2, haulage );
         time_duration work_time = travel_time + build_time;
         if( !query_yn( _( "Trip Estimate:\n%s" ), camp_trip_description( work_time,
                        build_time, travel_time, dist, trips, time_to_food( work_time, exertion_level ) ) ) ) {
             return;
         }
         npc_ptr comp = start_mission( miss_id,
                                       work_time, true,
                                       _( "departs to build a hide site" ), false, {},
                                       skill_survival, 3, exertion_level );
         if( comp != nullptr ) {
             trips = om_carry_weight_to_trips( total_mass, total_volume, comp );
             haulage = trips <= 2 ? 0 : losing_equipment.size();
             work_time = companion_travel_time_calc( forest, omt_pos, 0_minutes, 2, haulage ) +
                         build_time;
             comp->companion_mission_time_ret = calendar::turn + work_time;
             om_set_hide_site( *comp, forest, losing_equipment );
         }
     }
 }
References _, camp_trip_description(), companion_travel_time_calc(), forest, get_player_character(), give_equipment(), location, om_carry_weight_to_trips(), om_set_hide_site(), om_target_tile(), omt_pos, popup(), query_yn(), rl_dist(), skill_survival, start_mission(), time_to_food(), calendar::turn, type, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by handle_mission().
start_upgrade()
void basecamp::start_upgrade (const mission_id & miss_id)
Definition at line 2084 of file faction_camp.cpp.
 {
     const recipe &making = *recipe_id( miss_id.parameters );
     if( making.get_blueprint().str() == faction_expansion_salt_water_pipe_swamp_N ) {
         start_salt_water_pipe( miss_id );
         return;
     } else if( making.get_blueprint().str() == faction_expansion_salt_water_pipe_N ) {
         continue_salt_water_pipe( miss_id );
         return;
     }
     auto req_it = making.blueprint_build_reqs().reqs_by_parameters.find( miss_id.mapgen_args );
     cata_assert( req_it != making.blueprint_build_reqs().reqs_by_parameters.end() );
     const build_reqs &bld_reqs = req_it->second;
     const requirement_data &reqs = bld_reqs.consolidated_reqs;
     //Stop upgrade if you don't have materials
     if( reqs.can_make_with_inventory( _inv, making.get_component_filter() ) ) {
         bool must_feed = !making.has_flag( "NO_FOOD_REQ" );
         basecamp_action_components components( making, miss_id.mapgen_args, 1, *this );
         if( !components.choose_components() ) {
             return;
         }
         comp_list comp;
         if( bld_reqs.skills.empty() ) {
             if( making.skill_used.is_valid() ) {
                 comp = start_multi_mission( miss_id, must_feed,
                                             _( "begins to upgrade the camp" ),
                                             making.skill_used, making.difficulty );
             } else {
                 comp = start_multi_mission( miss_id, must_feed,
                                             _( "begins to upgrade the camp" ) );
             }
         } else {
             comp = start_multi_mission( miss_id, must_feed, _( "begins to upgrade the camp" ),
                                         bld_reqs.skills );
         }
         if( comp.empty() ) {
             return;
         }
         components.consume_components();
         const point dir = miss_id.dir.value();  //  Will always have a value
         update_in_progress( miss_id.parameters,
                             dir );
         bool mirror_horizontal;
         bool mirror_vertical;
         int rotation;
         auto e = expansions.find( dir );
         if( e == expansions.end() ) {
             return;
         }
         const tripoint_abs_omt upos = e->second.pos;
         extract_and_check_orientation_flags( making.ident(),
                                              dir,
                                              mirror_horizontal,
                                              mirror_vertical,
                                              rotation,
                                              "%s failed to build the %s upgrade",
                                              "" );
         apply_construction_marker( making.get_blueprint(), upos,
                                    miss_id.mapgen_args, mirror_horizontal,
                                    mirror_vertical, rotation, true );
     } else {
         popup( _( "You don't have the materials for the upgrade." ) );
     }
 }
References _, _inv, apply_construction_marker(), recipe::blueprint_build_reqs(), requirement_data::can_make_with_inventory(), cata_assert, basecamp_action_components::choose_components(), build_reqs::consolidated_reqs, basecamp_action_components::consume_components(), continue_salt_water_pipe(), recipe::difficulty, mission_id::dir, expansions, extract_and_check_orientation_flags(), faction_expansion_salt_water_pipe_N, faction_expansion_salt_water_pipe_swamp_N, recipe::get_blueprint(), recipe::get_component_filter(), recipe::has_flag(), recipe::ident(), string_id< T >::is_valid(), mission_id::mapgen_args, mission_id::parameters, popup(), parameterized_build_reqs::reqs_by_parameters, recipe::skill_used, build_reqs::skills, start_multi_mission(), start_salt_water_pipe(), string_id< T >::str(), and update_in_progress().
Referenced by handle_mission().
survey_field_return()
bool basecamp::survey_field_return (const mission_id & miss_id)
Choose which expansion slot to check for field conversion.
Definition at line 4425 of file faction_camp.cpp.
 {
     const std::string abort_msg = _( "stops looking for terrain to turn into fields" );
     npc_ptr comp = companion_choose_return( miss_id, 0_hours );
     if( comp == nullptr ) {
         return false;
     }
     popup( _( "Select a tile up to %d tiles away." ), 1 );
     const tripoint_abs_omt where( ui::omap::choose_point() );
     if( where == overmap::invalid_tripoint ) {
         return false;
     }
     int dist = rl_dist( where.xy(), omt_pos.xy() );
     if( dist != 1 ) {
         popup( _( "You must select a tile within %d range of the camp" ), 1 );
         return false;
     }
     if( omt_pos.z() != where.z() ) {
         popup( _( "Expansions must be on the same level as the camp" ) );
         return false;
     }
     const point dir = talk_function::om_simple_dir( omt_pos, where );
     if( expansions.find( dir ) != expansions.end() ) {
         if( query_yn(
                 _( "You already have an expansion at that location.  Do you want to finish this mission?  If not, the mission remains active and another tile can be checked." ) ) ) {
             finish_return( *comp, true, abort_msg, skill_construction.str(), 0 );
             return true;
         } else {
             return false;
         }
     }
     if( overmap_buffer.ter_existing( where ) == oter_id( "field" ) ) {
         if( query_yn(
                 _( "This location is already a field.  Do you want to finish this mission?  If not, the mission remains active and another tile can be checked." ) ) ) {
             finish_return( *comp, true, abort_msg, skill_construction.str(), 0 );
             return true;
         } else {
             return false;
         }
     }
     tinymap target;
     target.load( where, false );
     int mismatch_tiles = 0;
     tripoint mapmin = tripoint( 0, 0, where.z() );
     tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, where.z() );
     const std::unordered_set<ter_str_id> match_terrains = { ter_t_clay, ter_t_dirt, ter_t_dirtmound, ter_t_grass, ter_t_grass_dead, ter_t_grass_golf, ter_t_grass_long, ter_t_grass_tall, ter_t_moss, ter_t_sand };
     for( const tripoint &p : target.points_in_rectangle( mapmin, mapmax ) ) {
         if( match_terrains.find( target.ter( p ).id() ) == match_terrains.end() ) {
             mismatch_tiles++;
         }
     }
     if( mismatch_tiles > 0 ) {
         if( query_yn(
                 _( "This location has %d tiles blocking it from being converted.  Do you want to finish this mission?  If not, the mission remains active and another tile can be checked." ),
                 mismatch_tiles ) ) {
             finish_return( *comp, true, abort_msg, skill_construction.str(), 0 );
             return true;
         } else {
             return false;
         }
     }
     overmap_buffer.ter_set( where, oter_id( "field" ) );
     if( query_yn(
             _( "This location has now been converted into a field!  Do you want to finish the mission?  If not, the mission remains active and another tile can be checked." ) ) ) {
         finish_return( *comp, true, abort_msg, skill_construction.str(), 0 );
         return true;
     } else {
         return false;
     }
 }
References _, ui::omap::choose_point(), companion_choose_return(), expansions, finish_return(), int_id< T >::id(), overmap::invalid_tripoint, tinymap::load(), talk_function::om_simple_dir(), omt_pos, oter_id, overmap_buffer, tinymap::points_in_rectangle(), popup(), query_yn(), rl_dist(), SEEX, SEEY, skill_construction, string_id< T >::str(), tinymap::ter(), overmapbuffer::ter_existing(), overmapbuffer::ter_set(), ter_t_clay, ter_t_dirt, ter_t_dirtmound, ter_t_grass, ter_t_grass_dead, ter_t_grass_golf, ter_t_grass_long, ter_t_grass_tall, ter_t_moss, ter_t_sand, tripoint, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by handle_mission().
survey_return()
bool basecamp::survey_return (const mission_id & miss_id)
Choose which expansion you should start, called when a survey mission is completed.
Definition at line 4502 of file faction_camp.cpp.
 {
     const std::string abort_msg = _( "gives up trying to create an expansion" );
     npc_ptr comp = companion_choose_return( miss_id, 3_hours );
     if( comp == nullptr ) {
         return false;
     }
     popup( _( "Select a tile up to %d tiles away." ), 1 );
     const tripoint_abs_omt where( ui::omap::choose_point() );
     if( where == overmap::invalid_tripoint ) {
         return false;
     }
     int dist = rl_dist( where.xy(), omt_pos.xy() );
     if( dist != 1 ) {
         popup( _( "You must select a tile within %d range of the camp" ), 1 );
         return false;
     }
     if( omt_pos.z() != where.z() ) {
         popup( _( "Expansions must be on the same level as the camp" ) );
         return false;
     }
     const point dir = talk_function::om_simple_dir( omt_pos, where );
     if( expansions.find( dir ) != expansions.end() ) {
         if( query_yn(
                 _( "You already have an expansion at that location.  Do you want to finish this mission?  If not, the mission remains active and another tile can be checked." ) ) ) {
             finish_return( *comp, true, abort_msg, skill_construction.str(), 0 );
             return true;
         } else {
             return false;
         }
     }
     const oter_id &omt_ref = overmap_buffer.ter( where );
     const std::optional<mapgen_arguments> *maybe_args = overmap_buffer.mapgen_args( where );
     const auto &pos_expansions = recipe_group::get_recipes_by_id( "all_faction_base_expansions",
                                  omt_ref, maybe_args );
     if( pos_expansions.empty() ) {
         popup( _( "You can't build any expansions in a %s." ), omt_ref.id().c_str() );
         if( query_yn(
                 _( "You can't build any expansion in a %s.  Do you want to finish this mission?  If not, the mission remains active and another tile can be checked." ),
                 omt_ref.id().c_str() ) ) {
             finish_return( *comp, true, abort_msg, skill_construction.str(), 0 );
             return true;
         } else {
             return false;
         }
     }
     const recipe_id expansion_type = base_camps::select_camp_option( pos_expansions,
                                      _( "Select an expansion:" ) );
     bool mirror_horizontal;
     bool mirror_vertical;
     int rotation;
     if( !extract_and_check_orientation_flags( expansion_type,
             dir,
             mirror_horizontal,
             mirror_vertical,
             rotation,
             "%s failed to build the %s expansion",
             comp->disp_name() ) ) {
         if( query_yn(
                 _( "Do you want to finish this mission?  If not, the mission remains active and another tile can be checked." ) ) ) {
             finish_return( *comp, true, abort_msg, skill_construction.str(), 0 );
             return true;
         } else {
             return false;
         }
     }
     if( !run_mapgen_update_func( update_mapgen_id( expansion_type.str() ), where, {}, nullptr, true,
                                  mirror_horizontal, mirror_vertical, rotation ) ) {
         popup( _( "%s failed to add the %s expansion, perhaps there is a vehicle in the way." ),
                comp->disp_name(),
                expansion_type->blueprint_name() );
         if( query_yn(
                 _( "Do you want to finish this mission?  If not, the mission remains active and another tile can be checked (e.g. after clearing away the obstacle)." ) ) ) {
             finish_return( *comp, true, abort_msg, skill_construction.str(), 0 );
             return true;
         } else {
             return false;
         }
     }
     overmap_buffer.ter_set( where, oter_id( expansion_type.str() ) );
     add_expansion( expansion_type.str(), where, dir );
     const std::string msg = _( "returns from surveying for the expansion." );
     finish_return( *comp, true, msg, skill_construction.str(), 2 );
     return true;
 }
References _, add_expansion(), recipe::blueprint_name(), string_id< T >::c_str(), ui::omap::choose_point(), companion_choose_return(), expansions, extract_and_check_orientation_flags(), finish_return(), recipe_group::get_recipes_by_id(), int_id< T >::id(), overmap::invalid_tripoint, overmapbuffer::mapgen_args(), talk_function::om_simple_dir(), omt_pos, oter_id, overmap_buffer, popup(), query_yn(), rl_dist(), run_mapgen_update_func(), base_camps::select_camp_option(), skill_construction, string_id< T >::str(), overmapbuffer::ter(), overmapbuffer::ter_set(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by handle_mission().
time_to_food()
int basecamp::time_to_food (time_duration work, float exertion_level = NO_EXERCISE) const
Returns the total charges of food time_duration work costs.
Definition at line 5644 of file faction_camp.cpp.
 {
     const int days = to_hours<int>( work ) / 24;
     const int work_time = days * work_day_hours + to_hours<int>( work ) - days * 24;
     return base_metabolic_rate * ( work_time * exertion_level + days * work_day_rest_hours * NO_EXERCISE
                                    + days * work_day_idle_hours * SLEEP_EXERCISE ) / 24;
 }
References base_metabolic_rate, NO_EXERCISE, SLEEP_EXERCISE, work_day_hours, work_day_idle_hours, and work_day_rest_hours.
Referenced by camp_food_supply(), camp_food_supply_days(), craft_description(), finish_return(), get_available_missions_by_dir(), recipe_batch_max(), start_clearcut(), start_combat_mission(), start_cut_logs(), start_fortifications(), start_menial_labor(), start_mission(), start_multi_mission(), start_relay_hide_site(), and start_setup_hide_site().
unload_camp_map()
void basecamp::unload_camp_map ()
Definition at line 802 of file basecamp.cpp.
 {
     if( camp_map.map_ ) {
         camp_map.map_.reset();
     }
 }
References camp_map, and basecamp_map::map_.
Referenced by talk_function::basecamp_mission().
update_in_progress()
void basecamp::update_in_progress (const std::string & bldg, const point & dir)
Definition at line 444 of file basecamp.cpp.
 {
     if( !recipe_id( bldg ).is_valid() ) {
         return;
     }
     auto e = expansions.find( dir );
     if( e == expansions.end() ) {
         return;
     }
     expansion_data &e_data = e->second;
     const recipe &making = recipe_id( bldg ).obj();
     for( const auto &bp_provides : making.blueprint_provides() ) {
         if( e_data.in_progress.find( bp_provides.first ) == e_data.in_progress.end() ) {
             e_data.in_progress[bp_provides.first] = 0;
         }
         e_data.in_progress[bp_provides.first] += bp_provides.second;
     }
 }
References recipe::blueprint_provides(), expansions, expansion_data::in_progress, is_valid(), and string_id< T >::obj().
Referenced by common_salt_water_pipe_construction(), and start_upgrade().
update_provides()
void basecamp::update_provides (const std::string & bldg, expansion_data & e_data)
Definition at line 429 of file basecamp.cpp.
 {
     if( !recipe_id( bldg ).is_valid() ) {
         return;
     }
     const recipe &making = recipe_id( bldg ).obj();
     for( const auto &bp_provides : making.blueprint_provides() ) {
         if( e_data.provides.find( bp_provides.first ) == e_data.provides.end() ) {
             e_data.provides[bp_provides.first] = 0;
         }
         e_data.provides[bp_provides.first] += bp_provides.second;
     }
 }
References recipe::blueprint_provides(), is_valid(), string_id< T >::obj(), and expansion_data::provides.
Referenced by add_expansion(), define_camp(), reset_camp_resources(), salt_water_pipe_return(), salt_water_pipe_swamp_return(), start_salt_water_pipe(), and upgrade_return().
update_resources()
void basecamp::update_resources (const std::string & bldg)
Definition at line 417 of file basecamp.cpp.
 {
     if( !recipe_id( bldg ).is_valid() ) {
         return;
     }
     const recipe &making = recipe_id( bldg ).obj();
     for( const itype_id &bp_resource : making.blueprint_resources() ) {
         add_resource( bp_resource );
     }
 }
References add_resource(), recipe::blueprint_resources(), is_valid(), and string_id< T >::obj().
Referenced by add_expansion(), reset_camp_resources(), salt_water_pipe_return(), salt_water_pipe_swamp_return(), and upgrade_return().
upgrade_return()
bool basecamp::upgrade_return (const mission_id & miss_id)
Called to close upgrade missions, miss is the name of the mission id and dir is the direction of the location to be upgraded.
Definition at line 3875 of file faction_camp.cpp.
 {
     const point dir = miss_id.dir.value();  //  Will always have a value
     const std::string bldg = miss_id.parameters.empty() ? next_upgrade( dir, 1 ) : miss_id.parameters;
     if( bldg == "null" ) {
         return false;
     }
     auto e = expansions.find( dir );
     if( e == expansions.end() ) {
         return false;
     }
     const tripoint_abs_omt upos = e->second.pos;
     const recipe &making = *recipe_id( bldg );
     comp_list npc_list = get_mission_workers( miss_id );
     if( npc_list.empty() ) {
         return false;
     }
     std::string companion_list;
     for( const npc_ptr &comp : npc_list ) {
         if( comp != npc_list[0] ) {
             companion_list += ", ";
         }
         companion_list += comp->disp_name();
     }
     bool mirror_horizontal;
     bool mirror_vertical;
     int rotation;
     if( !extract_and_check_orientation_flags( making.ident(),
             dir,
             mirror_horizontal,
             mirror_vertical,
             rotation,
             "%s failed to build the %s upgrade",
             companion_list ) ) {
         return false;
     }
     if( making.get_blueprint().str() == faction_expansion_salt_water_pipe_swamp_N ) {
         return salt_water_pipe_swamp_return( miss_id, npc_list );
     } else if( making.get_blueprint().str() == faction_expansion_salt_water_pipe_N ) {
         return salt_water_pipe_return( miss_id, npc_list );
     }
     if( !run_mapgen_update_func( making.get_blueprint(), upos, miss_id.mapgen_args, nullptr, true,
                                  mirror_horizontal, mirror_vertical, rotation ) ) {
         popup( _( "%s failed to build the %s upgrade, perhaps there is a vehicle in the way." ),
                companion_list,
                making.get_blueprint().str() );
         return false;
     }
     apply_construction_marker( making.get_blueprint(), upos,
                                miss_id.mapgen_args, mirror_horizontal,
                                mirror_vertical, rotation, false );
     update_provides( bldg, e->second );
     update_resources( bldg );
     if( oter_str_id( bldg ).is_valid() ) {
         overmap_buffer.ter_set( upos, oter_id( bldg ) );
     }
     const std::string msg = _( "returns from upgrading the camp having earned a bit of "
                                "experience" );
     for( const npc_ptr &comp : npc_list ) {
         finish_return( *comp, false, msg, "construction", making.difficulty );
     }
     return true;
 }
References _, apply_construction_marker(), talk_function::companion_list(), recipe::difficulty, mission_id::dir, Character::disp_name(), expansions, extract_and_check_orientation_flags(), faction_expansion_salt_water_pipe_N, faction_expansion_salt_water_pipe_swamp_N, finish_return(), recipe::get_blueprint(), get_mission_workers(), recipe::ident(), is_valid(), mission_id::mapgen_args, next_upgrade(), oter_id, overmap_buffer, mission_id::parameters, popup(), run_mapgen_update_func(), salt_water_pipe_return(), salt_water_pipe_swamp_return(), string_id< T >::str(), overmapbuffer::ter_set(), update_provides(), and update_resources().
Referenced by handle_mission().
use_charges()
std::list< item > basecamp::use_charges (const itype_id & fake_id, int & quantity)
Definition at line 645 of file basecamp.cpp.
 {
     std::list<item> ret;
     if( quantity <= 0 ) {
         return ret;
     }
     for( basecamp_resource &bcp_r : resources ) {
         if( bcp_r.fake_id == fake_id ) {
             item camp_item( bcp_r.fake_id, calendar::turn_zero );
             camp_item.charges = std::min( bcp_r.available, quantity );
             quantity -= camp_item.charges;
             bcp_r.available -= camp_item.charges;
             bcp_r.consumed += camp_item.charges;
             ret.push_back( camp_item );
             if( quantity <= 0 ) {
                 break;
             }
         }
     }
     return ret;
 }
References item::charges, min(), resources, cata::hash64_detail::ret, and calendar::turn_zero.
Referenced by map::use_charges().
validate_assignees()
void basecamp::validate_assignees ()
Definition at line 522 of file basecamp.cpp.
 {
     std::vector<npc_ptr>::iterator iter = assigned_npcs.begin();
     while( iter != assigned_npcs.end() ) {
         if( !( *iter ) || !( *iter )->assigned_camp || *( *iter )->assigned_camp != omt_pos ) {
             iter = assigned_npcs.erase( iter );
         } else {
             ++iter;
         }
     }
     for( character_id elem : g->get_follower_list() ) {
         npc_ptr npc_to_add = overmap_buffer.find_npc( elem );
         if( !npc_to_add ) {
             continue;
         }
         if( std::find( assigned_npcs.begin(), assigned_npcs.end(), npc_to_add ) != assigned_npcs.end() ) {
             continue;
         } else {
             if( npc_to_add->assigned_camp && *npc_to_add->assigned_camp == omt_pos ) {
                 assigned_npcs.push_back( npc_to_add );
             }
         }
     }
     // remove duplicates - for legacy handling.
     std::sort( assigned_npcs.begin(), assigned_npcs.end() );
     auto last = std::unique( assigned_npcs.begin(), assigned_npcs.end() );
     assigned_npcs.erase( last, assigned_npcs.end() );
 }
References assigned_npcs, overmapbuffer::find_npc(), g, last, omt_pos, and overmap_buffer.
Referenced by abandon_camp(), talk_function::assign_camp(), iexamine::bulletin_board(), finish_return(), get_available_missions(), get_npcs_assigned(), job_assignment_ui(), and worker_assignment_ui().
validate_bb_pos()
void basecamp::validate_bb_pos (const tripoint & new_abs_pos) inline
Definition at line 184 of file basecamp.h.
{
             if( bb_pos == tripoint_zero ) {
                 bb_pos = new_abs_pos;
             }
         }
References bb_pos, and tripoint_zero.
Referenced by iexamine::bulletin_board().
validate_sort_points()
bool basecamp::validate_sort_points ()
Definition at line 5288 of file faction_camp.cpp.
 {
     zone_manager &mgr = zone_manager::get_manager();
     map *here = &get_map();
     const tripoint_abs_ms abspos = get_player_character().get_location();
     if( !mgr.has_near( zone_type_CAMP_STORAGE, abspos, 60 ) ||
         !mgr.has_near( zone_type_CAMP_FOOD, abspos, 60 ) ) {
         if( query_yn( _( "You do not have sufficient sort zones.  Do you want to add them?" ) ) ) {
             return set_sort_points();
         } else {
             return false;
         }
     } else {
         form_storage_zones( *here, abspos );
     }
     return true;
 }
References _, form_storage_zones(), Creature::get_location(), zone_manager::get_manager(), get_map(), get_player_character(), zone_manager::has_near(), query_yn(), set_sort_points(), zone_type_CAMP_FOOD, and zone_type_CAMP_STORAGE.
Referenced by iexamine::bulletin_board(), distribute_food(), set_sort_points(), and start_menial_labor().
worker_assignment_ui()
void basecamp::worker_assignment_ui ()
Definition at line 2232 of file faction_camp.cpp.
 {
     int entries_per_page = 0;
     catacurses::window w_followers;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         const point term( TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0,
                           TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0 );
         w_followers = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                           point( term.y, term.x ) );
         entries_per_page = FULL_SCREEN_HEIGHT - 5;
         ui.position_from_window( w_followers );
     } );
     ui.mark_resize();
     size_t selection = 0;
     input_context ctxt( "FACTION_MANAGER" );
     ctxt.register_action( "INSPECT_NPC" );
     ctxt.register_navigate_ui_list();
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     validate_assignees();
     g->validate_npc_followers();
     std::vector<npc *> followers;
     npc *cur_npc = nullptr;
     ui.on_redraw( [&]( const ui_adaptor & ) {
         werase( w_followers );
         // entries_per_page * page number
         const size_t top_of_page = entries_per_page * ( selection / entries_per_page );
         for( int i = 0; i < FULL_SCREEN_HEIGHT - 2; i++ ) {
             mvwputch( w_followers, point( 45, i ), BORDER_COLOR, LINE_XOXO );
         }
         draw_border( w_followers );
         const nc_color col = c_white;
         const std::string no_npcs = _( "You have no companions following you." );
         if( !followers.empty() ) {
             draw_scrollbar( w_followers, selection, entries_per_page, followers.size(),
                             point( 0, 3 ) );
             for( size_t i = top_of_page; i < followers.size(); i++ ) {
                 const int y = i - top_of_page + 3;
                 trim_and_print( w_followers, point( 1, y ), 43, selection == i ? hilite( col ) : col,
                                 followers[i]->disp_name() );
             }
         } else {
             mvwprintz( w_followers, point( 1, 4 ), c_light_red, no_npcs );
         }
         mvwprintz( w_followers, point( 1, FULL_SCREEN_HEIGHT - 2 ), c_light_gray,
                    _( "Press %s to inspect this follower." ), ctxt.get_desc( "INSPECT_NPC" ) );
         mvwprintz( w_followers, point( 1, FULL_SCREEN_HEIGHT - 1 ), c_light_gray,
                    _( "Press %s to assign this follower to this camp." ), ctxt.get_desc( "CONFIRM" ) );
         wnoutrefresh( w_followers );
     } );
     while( true ) {
         // create a list of npcs stationed at this camp
         followers.clear();
         for( const character_id &elem : g->get_follower_list() ) {
             shared_ptr_fast<npc> npc_to_get = overmap_buffer.find_npc( elem );
             if( !npc_to_get || !npc_to_get->is_following() || npc_to_get->is_hallucination() ) {
                 continue;
             }
             npc *npc_to_add = npc_to_get.get();
             followers.push_back( npc_to_add );
         }
         cur_npc = nullptr;
         if( !followers.empty() ) {
             cur_npc = followers[selection];
         }
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         if( action == "INSPECT_NPC" ) {
             if( cur_npc ) {
                 cur_npc->disp_info();
             }
         } else if( navigate_ui_list( action, selection, 5, followers.size(), true ) ) {
         } else if( action == "CONFIRM" ) {
             if( !followers.empty() && cur_npc ) {
                 talk_function::assign_camp( *cur_npc );
             }
         } else if( action == "QUIT" ) {
             break;
         }
     }
 }
References _, action, talk_function::assign_camp(), BORDER_COLOR, c_light_gray, c_light_red, c_white, Character::disp_info(), draw_border(), draw_scrollbar(), overmapbuffer::find_npc(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, g, input_context::get_desc(), input_context::handle_input(), hilite(), LINE_XOXO, mvwprintz(), mvwputch(), navigate_ui_list(), catacurses::newwin(), overmap_buffer, point, ui_manager::redraw(), input_context::register_action(), input_context::register_navigate_ui_list(), TERMX, TERMY, trim_and_print(), validate_assignees(), catacurses::werase(), catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by handle_mission().
Friends And Related Function Documentation
basecamp_action_components
friend class basecamp_action_components friend
Definition at line 479 of file basecamp.h.
Member Data Documentation
_inv
inventory basecamp::_inv private
Definition at line 505 of file basecamp.h.
Referenced by add_available_recipes(), available_upgrades(), basecamp_action_components::choose_components(), craft_description(), form_crafting_inventory(), om_upgrade_description(), recipe_batch_max(), start_crafting(), start_fortifications(), and start_upgrade().
assigned_npcs
std::vector<npc_ptr> basecamp::assigned_npcs private
Definition at line 490 of file basecamp.h.
Referenced by add_assignee(), get_npcs_assigned(), remove_assignee(), and validate_assignees().
bb_pos
tripoint basecamp::bb_pos private
Definition at line 492 of file basecamp.h.
Referenced by board_x(), board_y(), form_storage_zones(), get_bb_pos(), load_data(), place_results(), set_bb_pos(), and validate_bb_pos().
by_radio
bool basecamp::by_radio = false private
Definition at line 506 of file basecamp.h.
Referenced by basecamp_action_components::choose_components(), get_available_missions(), get_camp_map(), and set_by_radio().
camp_map
basecamp_map basecamp::camp_map private
Definition at line 495 of file basecamp.h.
Referenced by get_camp_map(), and unload_camp_map().
camp_workers
comp_list basecamp::camp_workers private
Definition at line 494 of file basecamp.h.
Referenced by get_available_missions(), get_mission_workers(), and reset_camp_workers().
directions
std::vector<point> basecamp::directions
Definition at line 195 of file basecamp.h.
Referenced by add_expansion(), get_available_missions(), and recruit_evaluation().
dumping_spot
tripoint_abs_ms basecamp::dumping_spot private
Definition at line 496 of file basecamp.h.
Referenced by get_dumping_spot(), set_dumping_spot(), and set_liquid_dumping_spot().
expansions
std::map<point, expansion_data> basecamp::expansions private
Definition at line 493 of file basecamp.h.
Referenced by add_expansion(), available_upgrades(), define_camp(), expansion_tab(), form_crafting_inventory(), get_available_missions(), has_provides(), next_upgrade(), point_within_camp(), recipe_deck(), recruit_evaluation(), reset_camp_resources(), salt_water_pipe_return(), salt_water_pipe_swamp_return(), scan_pseudo_items(), start_salt_water_pipe(), start_upgrade(), survey_field_return(), survey_return(), update_in_progress(), and upgrade_return().
fortifications
std::vector<tripoint_abs_omt> basecamp::fortifications
Definition at line 197 of file basecamp.h.
Referenced by fortifications_return(), and start_fortifications().
fuel_types
std::set<itype_id> basecamp::fuel_types private
Definition at line 501 of file basecamp.h.
Referenced by add_resource(), and form_crafting_inventory().
fuels
std::vector<basecamp_fuel> basecamp::fuels private
Definition at line 502 of file basecamp.h.
Referenced by form_crafting_inventory().
hidden_missions
std::vector<std::vector<ui_mission_id> > basecamp::hidden_missions
Definition at line 196 of file basecamp.h.
Referenced by get_available_missions_by_dir(), handle_hide_mission(), handle_reveal_mission(), hide_mission(), is_hidden(), and reveal_mission().
liquid_dumping_spots
std::vector<tripoint_abs_ms> basecamp::liquid_dumping_spots private
Definition at line 498 of file basecamp.h.
Referenced by get_liquid_dumping_spot(), and set_liquid_dumping_spot().
name
std::string basecamp::name
Definition at line 199 of file basecamp.h.
Referenced by abandon_camp(), board_name(), camp_name(), is_valid(), load_data(), query_new_name(), recruit_return(), and set_name().
omt_pos
tripoint_abs_omt basecamp::omt_pos private
Definition at line 489 of file basecamp.h.
Referenced by abandon_camp(), add_assignee(), add_expansion(), camp_omt_pos(), companion_choose_return(), define_camp(), emergency_recall(), farm_return(), get_available_missions(), get_available_missions_by_dir(), get_camp_map(), handle_mission(), is_valid(), reset_camp_workers(), scan_pseudo_items(), start_clearcut(), start_combat_mission(), start_cut_logs(), start_fortifications(), start_mission(), start_multi_mission(), start_relay_hide_site(), start_salt_water_pipe(), start_setup_hide_site(), survey_field_return(), survey_return(), and validate_assignees().
owner
faction_id basecamp::owner = faction_id::NULL_ID() mutable private
Definition at line 482 of file basecamp.h.
Referenced by fac(), get_owner(), and set_owner().
resources
std::vector<basecamp_resource> basecamp::resources private
Definition at line 503 of file basecamp.h.
Referenced by add_resource(), basecamp_action_components::consume_components(), form_crafting_inventory(), and use_charges().
salt_water_pipes
std::vector<expansion_salt_water_pipe *> basecamp::salt_water_pipes
Definition at line 198 of file basecamp.h.
Referenced by continue_salt_water_pipe(), salt_water_pipe_return(), salt_water_pipe_swamp_return(), and start_salt_water_pipe().
src_set
std::unordered_set<tripoint_abs_ms> basecamp::src_set private
Definition at line 500 of file basecamp.h.
Referenced by basecamp_action_components::consume_components(), form_crafting_inventory(), form_storage_zones(), get_storage_tiles(), set_storage_tiles(), and start_mission().
storage_zones
std::vector<const zone_data *> basecamp::storage_zones private
Definition at line 499 of file basecamp.h.
Referenced by form_storage_zones(), get_storage_zone(), and set_storage_zone().
temp_ui_mission_keys
std::vector<std::vector<ui_mission_id> > basecamp::temp_ui_mission_keys private
Definition at line 504 of file basecamp.h.
Referenced by get_available_missions(), and handle_hide_mission().
The documentation for this class was generated from the following files:
src/basecamp.h
src/basecamp.cpp
src/faction.cpp
src/faction_camp.cpp
src/savegame_json.cpp