Cataclysm DDA: item_location::impl::item_in_container Class Reference
item_location::impl::item_in_container Class Reference
Public Member Functions
item_location parent_item () const override
item_pocket * parent_pocket () const override
item_in_container (const item_location &container, item *which)
void serialize (JsonOut &js) const override
item * unpack (int idx) const override
Character * carrier () const override
std::string describe (const Character *) const override
type where () const override
type where_recursive () const override
tripoint position () const override
void remove_item () override
void on_contents_changed () override
item_location obtain (Character &ch, const int qty) override
int obtain_cost (const Character &ch, int qty) const override
units::volume volume_capacity () const override
units::mass weight_capacity () const override
bool check_parent_capacity_recursive () const override
Public Member Functions inherited from item_location::impl
impl ()=default
impl (item *i)
impl (int idx)
virtual ~impl ()=default
item * target () const
virtual bool valid () const
Private Member Functions
int calc_index () const
Private Attributes
item_location container
item_pocket * container_pkt = nullptr
Additional Inherited Members
Public Attributes inherited from item_location::impl
bool should_stack = true
Detailed Description
Definition at line 570 of file item_location.cpp.
Constructor & Destructor Documentation
item_in_container()
item_location::impl::item_in_container::item_in_container (const item_location & container, item * which) inline
Definition at line 611 of file item_location.cpp.
                                                                          :
             impl( which ), container( container ) {}
Member Function Documentation
calc_index()
int item_location::impl::item_in_container::calc_index () const inline private
Definition at line 578 of file item_location.cpp.
{
             if( !container ) {
                 return -1;
             }
             int idx = 0;
             for( const item *it : container->all_items_top() ) {
                 if( target() == it ) {
                     return idx;
                 }
                 idx++;
             }
             if( container->empty() ) {
                 return -1;
             }
             return idx;
         }
References item::all_items_top(), container, item::empty(), item_location::impl::idx, and item_location::impl::target().
Referenced by serialize().
carrier()
Character* item_location::impl::item_in_container::carrier () const inline override virtual
Implements item_location::impl.
Definition at line 636 of file item_location.cpp.
{
             return container.carrier();
         }
References item_location::carrier(), and container.
check_parent_capacity_recursive()
bool item_location::impl::item_in_container::check_parent_capacity_recursive () const inline override virtual
Implements item_location::impl.
Definition at line 747 of file item_location.cpp.
{
             return volume_capacity() >= 0_ml && weight_capacity() >= 0_gram &&
                    container.check_parent_capacity_recursive();
         }
References item_location::check_parent_capacity_recursive(), container, volume_capacity(), and weight_capacity().
describe()
std::string item_location::impl::item_in_container::describe (const Character *) const inline override virtual
Implements item_location::impl.
Definition at line 640 of file item_location.cpp.
{
             if( !target() ) {
                 return std::string();
             }
             return string_format( _( "inside %s" ), container->tname() );
         }
References _, container, string_format(), item_location::impl::target(), and item::tname().
obtain()
item_location item_location::impl::item_in_container::obtain (Character & ch, const int qty) inline override virtual
Implements item_location::impl.
Definition at line 669 of file item_location.cpp.
{
             ch.mod_moves( -obtain_cost( ch, qty ) );
             on_contents_changed();
             if( container.held_by( ch ) ) {
                 // we don't need to move it in this case, it's in a pocket
                 // we just charge the obtain cost and leave it in place. otherwise
                 // it's liable to end up back in the same pocket, where shenanigans ensue
                 return item_location( container, target() );
             }
             if( target()->made_of( phase_id::LIQUID ) && container->num_item_stacks() == 1 ) {
                 item_location inv =
                     ch.i_add( *container, should_stack, nullptr, &*container, false );
                 if( inv == item_location::nowhere ) {
                     DebugLog( D_INFO, DC_ALL )
                             << "failed to add item " << target()->tname()
                             << " to character inventory while obtaining from container";
                     return {};
                 }
                 container.remove_item();
                 return item_location{ inv, &inv->only_item() };
             }
             const item obj = target()->split( qty );
             if( !obj.is_null() ) {
                 return ch.i_add( obj, should_stack,/*avoid=*/nullptr, nullptr,/*allow_drop=*/false );
             } else {
                 item_location inv = ch.i_add( *target(), should_stack,/*avoid=*/nullptr,
                                               target(), /*allow_drop=*/false );
                 if( inv == item_location::nowhere ) {
                     DebugLog( D_INFO, DC_ALL )
                             << "failed to add item " << target()->tname()
                             << " to character inventory while obtaining from container";
                     return {};
                 }
                 remove_item();
                 return inv;
             }
         }
References container, D_INFO, DC_ALL, DebugLog(), item_location::held_by(), Character::i_add(), item::is_null(), item_location::item_location(), LIQUID, Creature::mod_moves(), item_location::nowhere, item::num_item_stacks(), obtain_cost(), on_contents_changed(), item::only_item(), item_location::remove_item(), remove_item(), item_location::impl::should_stack, item::split(), item_location::impl::target(), and item::tname().
obtain_cost()
int item_location::impl::item_in_container::obtain_cost (const Character & ch, int qty) const inline override virtual
Implements item_location::impl.
Definition at line 709 of file item_location.cpp.
{
             if( !target() ) {
                 return 0;
             }
             const int container_mv = parent_pocket()->moves();
             if( container_mv == 0 ) {
                 debugmsg( "ERROR: %s does not contain %s", container->tname(), target()->tname() );
                 return 0;
             }
             int primary_cost = ch.item_handling_cost( *target(), true, container_mv, qty );
             primary_cost = ch.enchantment_cache->modify_value( enchant_vals::mod::OBTAIN_COST_MULTIPLIER,
                            primary_cost );
             int parent_obtain_cost = container.obtain_cost( ch, qty );
             if( container->get_use( "holster" ) ) {
                 if( ch.is_worn( *container ) ) {
                     primary_cost = ch.item_retrieve_cost( *target(), *container, false, container_mv );
                 } else {
                     primary_cost = ch.item_retrieve_cost( *target(), *container );
                 }
                 // for holsters, we should not include the cost of wielding the holster itself
                 parent_obtain_cost = 0;
             } else if( container.where() != item_location::type::container ) {
                 // Worn items don't need to be retrieved, just accessed.
                 parent_obtain_cost = 0;
             }
             return primary_cost + parent_obtain_cost;
         }
References container, item_location::container, debugmsg, Character::enchantment_cache, item::get_use(), Character::is_worn(), Character::item_handling_cost(), Character::item_retrieve_cost(), item_pocket::moves(), item_location::obtain_cost(), enchant_vals::OBTAIN_COST_MULTIPLIER, parent_pocket(), item_location::impl::target(), item::tname(), and item_location::where().
Referenced by obtain().
on_contents_changed()
void item_location::impl::item_in_container::on_contents_changed () inline override virtual
Implements item_location::impl.
Definition at line 664 of file item_location.cpp.
{
             target()->on_contents_changed();
             container->on_contents_changed();
         }
References container, item::on_contents_changed(), and item_location::impl::target().
Referenced by obtain().
parent_item()
item_location item_location::impl::item_in_container::parent_item () const inline override virtual
Reimplemented from item_location::impl.
Definition at line 595 of file item_location.cpp.
{
             return container;
         }
References container.
Referenced by parent_pocket().
parent_pocket()
item_pocket* item_location::impl::item_in_container::parent_pocket () const inline override virtual
Reimplemented from item_location::impl.
Definition at line 599 of file item_location.cpp.
{
             if( container_pkt == nullptr ) {
                 std::vector<item_pocket *> const pkts = parent_item()->get_all_standard_pockets();
                 if( pkts.size() == 1 ) {
                     container_pkt = pkts.front();
                 } else {
                     container_pkt = parent_item()->contained_where( *target() );
                 }
             }
             return container_pkt;
         }
References item::contained_where(), container_pkt, item_pocket::front(), item::get_all_standard_pockets(), parent_item(), and item_location::impl::target().
Referenced by obtain_cost(), volume_capacity(), and weight_capacity().
position()
tripoint item_location::impl::item_in_container::position () const inline override virtual
Implements item_location::impl.
Definition at line 655 of file item_location.cpp.
{
             return container.position();
         }
References container, and item_location::position().
remove_item()
void item_location::impl::item_in_container::remove_item () inline override virtual
Implements item_location::impl.
Definition at line 659 of file item_location.cpp.
{
             container->remove_item( *target() );
             container->on_contents_changed();
         }
References container, item::on_contents_changed(), visitable::remove_item(), and item_location::impl::target().
Referenced by obtain().
serialize()
void item_location::impl::item_in_container::serialize (JsonOut & js) const inline override virtual
Implements item_location::impl.
Definition at line 614 of file item_location.cpp.
{
             js.start_object();
             js.member( "idx", calc_index() );
             js.member( "type", "in_container" );
             js.member( "parent", container );
             js.end_object();
         }
References calc_index(), container, JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
unpack()
item* item_location::impl::item_in_container::unpack (int idx) const inline override virtual
Implements item_location::impl.
Definition at line 622 of file item_location.cpp.
{
             if( idx < 0 || static_cast<size_t>( idx ) >= target()->num_item_stacks() ) {
                 return nullptr;
             }
             std::list<const item *> all_items = container->all_items_ptr();
             auto iter = all_items.begin();
             std::advance( iter, idx );
             if( iter != all_items.end() ) {
                 return const_cast<item *>( *iter );
             } else {
                 return nullptr;
             }
         }
References item::all_items_ptr(), container, item_location::impl::idx, and item_location::impl::target().
volume_capacity()
units::volume item_location::impl::item_in_container::volume_capacity () const inline override virtual
Implements item_location::impl.
Definition at line 739 of file item_location.cpp.
{
             return parent_pocket()->remaining_volume();
         }
References parent_pocket(), and item_pocket::remaining_volume().
Referenced by check_parent_capacity_recursive().
weight_capacity()
units::mass item_location::impl::item_in_container::weight_capacity () const inline override virtual
Implements item_location::impl.
Definition at line 743 of file item_location.cpp.
{
             return parent_pocket()->remaining_weight();
         }
References parent_pocket(), and item_pocket::remaining_weight().
Referenced by check_parent_capacity_recursive().
where()
type item_location::impl::item_in_container::where () const inline override virtual
Implements item_location::impl.
Definition at line 647 of file item_location.cpp.
{
             return type::container;
         }
References item_location::container.
where_recursive()
type item_location::impl::item_in_container::where_recursive () const inline override virtual
Reimplemented from item_location::impl.
Definition at line 651 of file item_location.cpp.
{
             return container.where_recursive();
         }
References container, and item_location::where_recursive().
Member Data Documentation
container
item_location item_location::impl::item_in_container::container private
Definition at line 573 of file item_location.cpp.
Referenced by calc_index(), carrier(), check_parent_capacity_recursive(), describe(), obtain(), obtain_cost(), on_contents_changed(), parent_item(), position(), remove_item(), serialize(), unpack(), and where_recursive().
container_pkt
item_pocket* item_location::impl::item_in_container::container_pkt = nullptr mutable private
Definition at line 574 of file item_location.cpp.
Referenced by parent_pocket().
The documentation for this class was generated from the following file:
src/item_location.cpp