Cataclysm DDA: safe_reference< T > Class Template Reference
safe_reference< T > Class Template Reference
A pair of classes to provide safe references to objects.
#include <safe_reference.h>
Public Member Functions
safe_reference ()=default
T * get () const
operator bool () const
bool operator! () const
T & operator* () const
T * operator-> () const
Private Member Functions
safe_reference (const std::shared_ptr< T > &p)
Private Attributes
std::weak_ptr< T > impl
Friends
class safe_reference_anchor
Detailed Description
template<typename T>
class safe_reference< T >
A pair of classes to provide safe references to objects.
A safe_reference_anchor is made a member of some object, and a safe_reference to that object (or any other object with the same lifetime) can be obtained from the safe_reference_anchor.
When the safe_reference is destroyed or assigned-to, all safe_references derived from it are invalidated. When one attempts to fetch the referenced object from an invalidated safe_reference, it returns nullptr.
The motivating use case is to store references to items in item_locations in a way that is safe if that item is moved or destroyed.
Definition at line 24 of file safe_reference.h.
Constructor & Destructor Documentation
safe_reference() [1/2]
template<typename T > safe_reference< T >::safe_reference () default
safe_reference() [2/2]
template<typename T > safe_reference< T >::safe_reference (const std::shared_ptr< T > & p) inline explicit private
Definition at line 51 of file safe_reference.h.
 : impl( p ) {}
Member Function Documentation
get()
template<typename T > T* safe_reference< T >::get () const inline
Definition at line 29 of file safe_reference.h.
{
             return impl.lock().get();
         }
References safe_reference< T >::impl.
Referenced by item::link_to(), vehicle::merge_vehicle_parts(), safe_reference< T >::operator*(), safe_reference< T >::operator->(), operator==(), item::process_link(), process_map_items(), item::reset_link(), item_location::impl::target(), and link_up_actor::use().
operator bool()
template<typename T > safe_reference< T >::operator bool () const inline explicit
Definition at line 33 of file safe_reference.h.
{
             return !!*this;
         }
operator!()
template<typename T > bool safe_reference< T >::operator! () const inline
Definition at line 37 of file safe_reference.h.
{
             return impl.expired();
         }
References safe_reference< T >::impl.
operator*()
template<typename T > T& safe_reference< T >::operator* () const inline
Definition at line 41 of file safe_reference.h.
{
             return *get();
         }
References safe_reference< T >::get().
operator->()
template<typename T > T* safe_reference< T >::operator-> () const inline
Definition at line 45 of file safe_reference.h.
{
             return get();
         }
References safe_reference< T >::get().
Friends And Related Function Documentation
safe_reference_anchor
template<typename T > friend class safe_reference_anchor friend
Definition at line 49 of file safe_reference.h.
Member Data Documentation
impl
template<typename T > std::weak_ptr<T> safe_reference< T >::impl private
Definition at line 53 of file safe_reference.h.
Referenced by safe_reference< T >::get(), and safe_reference< T >::operator!().
The documentation for this class was generated from the following file:
src/safe_reference.h