Cataclysm DDA: weapon_category Class Reference
weapon_category Class Reference
#include <martialarts.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
void check () const
const weapon_category_id & getId () const
const translation & name () const
const std::vector< proficiency_id > & category_proficiencies () const
Static Public Member Functions
static void load_weapon_categories (const JsonObject &jo, const std::string &src)
static void verify_weapon_categories ()
static void reset ()
static const std::vector< weapon_category > & get_all ()
Private Attributes
weapon_category_id id
std::vector< std::pair< weapon_category_id, mod_id > > src
std::vector< proficiency_id > proficiencies_
bool was_loaded = false
translation name_
Friends
class generic_factory< weapon_category >
struct mod_tracker
Detailed Description
Definition at line 31 of file martialarts.h.
Member Function Documentation
category_proficiencies()
const std::vector<proficiency_id>& weapon_category::category_proficiencies () const inline
Definition at line 51 of file martialarts.h.
{
             return proficiencies_;
         }
References proficiencies_.
check()
void weapon_category::check () const
Definition at line 95 of file martialarts.cpp.
 {
     for( const proficiency_id &prof : proficiencies_ ) {
         if( !prof.is_valid() ) {
             debugmsg( "Proficiency %s does not exist in weapon category %s", prof.str(), id.str() );
         }
     }
 }
References debugmsg, and proficiencies_.
get_all()
const std::vector< weapon_category > & weapon_category::get_all () static
Definition at line 104 of file martialarts.cpp.
 {
     return weapon_category_factory.get_all();
 }
References anonymous_namespace{martialarts.cpp}::weapon_category_factory.
getId()
const weapon_category_id& weapon_category::getId () const inline
Definition at line 43 of file martialarts.h.
{
             return id;
         }
References id.
load()
void weapon_category::load (const JsonObject & jo, std::string_view src)
Definition at line 84 of file martialarts.cpp.
 {
     mandatory( jo, was_loaded, "name", name_ );
     optional( jo, was_loaded, "proficiencies", proficiencies_ );
 }
References mandatory, name_, optional(), proficiencies_, and was_loaded.
load_weapon_categories()
void weapon_category::load_weapon_categories (const JsonObject & jo, const std::string & src) static
Definition at line 74 of file martialarts.cpp.
 {
     weapon_category_factory.load( jo, src );
 }
References src, and anonymous_namespace{martialarts.cpp}::weapon_category_factory.
Referenced by DynamicDataLoader::initialize().
name()
const translation& weapon_category::name () const inline
Definition at line 47 of file martialarts.h.
{
             return name_;
         }
References name_.
reset()
void weapon_category::reset () static
Definition at line 79 of file martialarts.cpp.
 {
     weapon_category_factory.reset();
 }
References anonymous_namespace{martialarts.cpp}::weapon_category_factory.
Referenced by DynamicDataLoader::unload_data().
verify_weapon_categories()
void weapon_category::verify_weapon_categories () static
Definition at line 90 of file martialarts.cpp.
 {
     weapon_category_factory.check();
 }
References anonymous_namespace{martialarts.cpp}::weapon_category_factory.
Referenced by DynamicDataLoader::check_consistency().
Friends And Related Function Documentation
generic_factory< weapon_category >
friend class generic_factory< weapon_category > friend
Definition at line 51 of file martialarts.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 57 of file martialarts.h.
Member Data Documentation
id
weapon_category_id weapon_category::id private
Definition at line 59 of file martialarts.h.
Referenced by getId().
name_
translation weapon_category::name_ private
Definition at line 64 of file martialarts.h.
Referenced by load(), and name().
proficiencies_
std::vector<proficiency_id> weapon_category::proficiencies_ private
Definition at line 61 of file martialarts.h.
Referenced by category_proficiencies(), check(), and load().
src
std::vector<std::pair<weapon_category_id, mod_id> > weapon_category::src private
Definition at line 60 of file martialarts.h.
Referenced by load_weapon_categories().
was_loaded
bool weapon_category::was_loaded = false private
Definition at line 62 of file martialarts.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/martialarts.h
src/martialarts.cpp