Cataclysm DDA: attach_veh_tool_inventory_preset Class Reference
attach_veh_tool_inventory_preset Class Reference
Public Member Functions
attach_veh_tool_inventory_preset (const std::set< itype_id > &allowed_types)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Private Attributes
const std::set< itype_id > allowed_types
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 1965 of file game_inventory.cpp.
Constructor & Destructor Documentation
attach_veh_tool_inventory_preset()
attach_veh_tool_inventory_preset::attach_veh_tool_inventory_preset (const std::set< itype_id > & allowed_types) inline explicit
Definition at line 1968 of file game_inventory.cpp.
             : allowed_types( allowed_types ) { }
Member Function Documentation
get_denial()
std::string attach_veh_tool_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 1975 of file game_inventory.cpp.
{
             const item &it = *loc.get_item();
             if( !it.empty() || !it.toolmods().empty() ) {
                 return "item needs to be empty.";
             }
             return std::string();
         }
References item::empty(), item_location::get_item(), and item::toolmods().
is_shown()
bool attach_veh_tool_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 1971 of file game_inventory.cpp.
{
             return allowed_types.count( loc->typeId() );
         }
References allowed_types, and item::typeId().
Member Data Documentation
allowed_types
const std::set<itype_id> attach_veh_tool_inventory_preset::allowed_types private
Definition at line 1986 of file game_inventory.cpp.
Referenced by is_shown().
The documentation for this class was generated from the following file:
src/game_inventory.cpp