Cataclysm DDA: veh_menu Class Reference
veh_menu Class Reference
#include <veh_utils.h>
Public Member Functions
veh_menu (vehicle &veh, const std::string &title)
veh_menu (vehicle *veh, const std::string &title)
veh_menu_item & add (const std::string &txt)
void reset (bool keep_last_selected=true)
bool query ()
size_t get_items_size () const
std::vector< veh_menu_item > get_items () const
Static Public Member Functions
static void * operator new (size_t)=delete
static void * operator new[] (size_t)=delete
static void operator delete (void *)=delete
static void operator delete[] (void *)=delete
Public Attributes
int desc_lines_hint = 0
Private Member Functions
std::vector< uilist_entry > get_uilist_entries () const
std::vector< tripoint > get_locations () const
Private Attributes
std::vector< veh_menu_item > items
std::string title
vehicle & veh
int last_selected = 0
Detailed Description
Definition at line 59 of file veh_utils.h.
Constructor & Destructor Documentation
veh_menu() [1/2]
veh_menu::veh_menu (vehicle & veh, const std::string & title)
Definition at line 246 of file veh_utils.cpp.
                                                         : veh( veh )
 {
     this->title = title;
 }
References title.
veh_menu() [2/2]
veh_menu::veh_menu (vehicle * veh, const std::string & title)
Definition at line 251 of file veh_utils.cpp.
                                                         : veh( *veh )
 {
     this->title = title;
 }
References title.
Member Function Documentation
add()
veh_menu_item & veh_menu::add (const std::string & txt)
Definition at line 256 of file veh_utils.cpp.
 {
     veh_menu_item item;
     item._text = txt;
     this->items.push_back( item );
     return items.back();
 }
References item, and items.
Referenced by add_electronic_toggle(), vehicle::build_bike_rack_menu(), vehicle::build_electronics_menu(), vehicle::build_interact_menu(), vehicle::control_doors(), vehicle::control_engines(), and vehicle::toggle_autopilot().
get_items()
std::vector< veh_menu_item > veh_menu::get_items () const
Definition at line 269 of file veh_utils.cpp.
 {
     return items;
 }
References items.
Referenced by veh_app_interact::populate_app_actions().
get_items_size()
size_t veh_menu::get_items_size () const
Definition at line 264 of file veh_utils.cpp.
 {
     return items.size();
 }
References items.
Referenced by vehicle::control_doors().
get_locations()
std::vector< tripoint > veh_menu::get_locations () const private
Definition at line 274 of file veh_utils.cpp.
 {
     std::vector<tripoint> locations;
     for( const veh_menu_item &it : items ) {
         if( it._location.has_value() ) {
             locations.push_back( it._location.value() );
         }
     }
     return locations;
 }
References items, and anonymous_namespace{overmap_location.cpp}::locations.
Referenced by query().
get_uilist_entries()
std::vector< uilist_entry > veh_menu::get_uilist_entries () const private
Definition at line 293 of file veh_utils.cpp.
 {
     std::vector<uilist_entry> entries;
     for( size_t i = 0; i < items.size(); i++ ) {
         const veh_menu_item &it = items[i];
         uilist_entry entry( it._text, std::nullopt );
         if( it._hotkey_action.has_value() ) {
             entry = uilist_entry( it._text, veh_keybind( it._hotkey_action ) );
         } else if( it._hotkey_char.has_value() ) {
             entry = uilist_entry( it._text, it._hotkey_char.value() );
         }
         entry.retval = static_cast<int>( i );
         entry.desc = it._desc;
         entry.enabled = it._enabled;
         if( it._check_locked && veh.is_locked ) {
             entry.enabled = false;
             if( !entry.desc.empty() ) {
                 entry.desc += "\n";
             }
             entry.desc += _( "Vehicle is locked." );
         }
         entries.push_back( entry );
     }
     return entries;
 }
References _, veh_menu_item::_check_locked, veh_menu_item::_desc, veh_menu_item::_enabled, veh_menu_item::_hotkey_action, veh_menu_item::_hotkey_char, veh_menu_item::_text, uilist_entry::desc, uilist_entry::enabled, vehicle::is_locked, items, uilist_entry::retval, veh, and veh_keybind().
Referenced by query().
operator delete()
static void veh_menu::operator delete (void *) static delete
operator delete[]()
static void veh_menu::operator delete[] (void *) static delete
operator new()
static void* veh_menu::operator new (size_t) static delete
operator new[]()
static void* veh_menu::operator new[] (size_t) static delete
query()
bool veh_menu::query ()
Definition at line 324 of file veh_utils.cpp.
 {
     if( items.empty() ) {
         debugmsg( "veh_menu::query() called with empty items" );
         return false;
     }
     uilist menu;
     menu.input_category = "VEHICLE";
     for( const veh_menu_item &it : items ) {
         if( it._hotkey_action.has_value() ) {
             menu.additional_actions.emplace_back( it._hotkey_action.value(), translation() );
         }
     }
     menu.title = title;
     menu.entries = get_uilist_entries();
     menu.desc_lines_hint = desc_lines_hint;
     menu.desc_enabled = std::any_of( menu.entries.begin(), menu.entries.end(),
     []( const uilist_entry & it ) {
         return !it.desc.empty();
     } );
     menu.hilight_disabled = true;
     const std::vector<tripoint> locations = get_locations();
     pointmenu_cb callback( locations );
     if( locations.size() == items.size() ) { // all items have valid location attached
         menu.callback = &callback;
         menu.w_x_setup = 4; // move menu to the left so more space around vehicle is visible
     } else {
         menu.callback = nullptr;
     }
     menu.selected = last_selected;
     menu.query();
     last_selected = menu.selected;
     const size_t index = static_cast<size_t>( menu.ret );
     if( index >= items.size() ) {
         return false;
     }
     const veh_menu_item &chosen = items[index];
     if( chosen._check_theft && !veh.handle_potential_theft( get_player_character() ) ) {
         return false;
     }
     if( !chosen._on_submit ) {
         debugmsg( "selected veh_menu_item has no attached std::function" );
         return false;
     }
     chosen._on_submit();
     veh.refresh();
     map &m = get_map();
     m.invalidate_map_cache( m.get_abs_sub().z() );
     return chosen._keep_menu_open;
 }
References veh_menu_item::_check_theft, veh_menu_item::_keep_menu_open, veh_menu_item::_on_submit, uilist::additional_actions, uilist::callback, debugmsg, uilist::desc_enabled, uilist::desc_lines_hint, desc_lines_hint, uilist::entries, map::get_abs_sub(), get_locations(), get_map(), get_player_character(), get_uilist_entries(), vehicle::handle_potential_theft(), uilist::hilight_disabled, uilist::input_category, map::invalidate_map_cache(), items, last_selected, anonymous_namespace{overmap_location.cpp}::locations, uilist::query(), vehicle::refresh(), uilist::ret, uilist::selected, uilist::title, title, veh, uilist::w_x_setup, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by vehicle::control_doors(), vehicle::control_engines(), debug_menu::debug_menu_spawn_vehicle(), vehicle::interact_with(), and vehicle::toggle_autopilot().
reset()
void veh_menu::reset (bool keep_last_selected = true)
Definition at line 287 of file veh_utils.cpp.
 {
     last_selected = keep_last_selected ? last_selected : 0;
     items.clear();
 }
References items, and last_selected.
Referenced by vehicle::control_doors(), vehicle::control_engines(), and vehicle::interact_with().
Member Data Documentation
desc_lines_hint
int veh_menu::desc_lines_hint = 0
Definition at line 71 of file veh_utils.h.
Referenced by vehicle::build_bike_rack_menu(), and query().
items
std::vector<veh_menu_item> veh_menu::items private
Definition at line 80 of file veh_utils.h.
Referenced by add(), get_items(), get_items_size(), get_locations(), get_uilist_entries(), query(), and reset().
last_selected
int veh_menu::last_selected = 0 private
Definition at line 87 of file veh_utils.h.
Referenced by query(), and reset().
title
std::string veh_menu::title private
Definition at line 81 of file veh_utils.h.
Referenced by query(), and veh_menu().
veh
vehicle& veh_menu::veh private
Definition at line 82 of file veh_utils.h.
Referenced by get_uilist_entries(), and query().
The documentation for this class was generated from the following files:
src/veh_utils.h
src/veh_utils.cpp