Cataclysm DDA: smart_controller_ui Class Reference
smart_controller_ui Class Reference
#include <smart_controller_ui.h>
Public Member Functions
smart_controller_ui (smart_controller_settings initial_settings)
void control ()
Static Public Attributes
static const int WIDTH = 52
static const int HEIGHT = 36
Private Member Functions
void refresh ()
Private Attributes
catacurses::window win
input_context ctxt
const smart_controller_settings settings
int selection = smart_controller_ui_selection::init
int slider = 0
Static Private Attributes
static const int LEFT_MARGIN = 6
static const int MENU_ITEM_HEIGHT = 5
static const int MENU_ITEMS_N = smart_controller_ui_selection::length
static const int SLIDER_W = 40
Detailed Description
Definition at line 32 of file smart_controller_ui.h.
Constructor & Destructor Documentation
smart_controller_ui()
smart_controller_ui::smart_controller_ui (smart_controller_settings initial_settings) explicit
Definition at line 29 of file smart_controller_ui.cpp.
                                                                                      :
     win( init_window() ), ctxt( "SMART_ENGINE_CONTROLLER" ), settings( initial_settings )
 {
     ctxt.register_directions();
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "NEXT_TAB" );
 }
References ctxt, input_context::register_action(), and input_context::register_directions().
Member Function Documentation
control()
void smart_controller_ui::control ()
Definition at line 133 of file smart_controller_ui.cpp.
 {
     ui_adaptor ui;
     ui.on_screen_resize( [this]( ui_adaptor & ui ) {
         win = init_window();
         ui.position_from_window( win );
     } );
     ui.mark_resize();
     ui.on_redraw( [this]( const ui_adaptor & ) {
         refresh();
     } );
     std::string action;
     do {
         ui_manager::redraw();
         action = ctxt.handle_input();
         if( action == "CONFIRM" || ( action == "NEXT_TAB" &&
                                      selection == smart_controller_ui_selection::lo_and_hi_slider ) ) {
             switch( selection ) {
                 case smart_controller_ui_selection::enabled:
                     settings.enabled = !settings.enabled;
                     break;
                 case smart_controller_ui_selection::lo_and_hi_slider:
                     slider = 1 - slider;
                     break;
                 case smart_controller_ui_selection::manual:
                     const translation manual =
                         SNIPPET.random_from_category( "smart_engine_controller_manual" ).value_or( translation() );
                     scrollable_text( [&] {
                         //note: ui.on_screen_resize will be called first and reinit `win`
                         return win;
                     }, _( "Smart Engine Controller ® User Manual" ), manual.translated() );
                     break;
             }
         } else if( action == "UP" || action == "DOWN" ) {
             selection = inc_clamp_wrap( selection, action == "DOWN", MENU_ITEMS_N );
         } else if( selection == smart_controller_ui_selection::lo_and_hi_slider && ( action == "LEFT" ||
                    action == "RIGHT" ) ) {
             const int dx = action == "RIGHT" ? 1 : -1;
             if( slider == 0 ) {
                 settings.battery_lo = clamp( ( settings.battery_lo / 5 + dx ) * 5, 5, 90 );
                 // keep the min space of 5 between this and other slider
                 settings.battery_hi = std::max( settings.battery_lo + 5, settings.battery_hi );
             } else {
                 settings.battery_hi = clamp( ( settings.battery_hi / 5 + dx ) * 5, 10, 95 );
                 // keep the min space of 5 between this and other slider
                 settings.battery_lo = std::min( settings.battery_hi - 5, settings.battery_lo );
             }
         }
     } while( action != "QUIT" );
 }
References _, action, smart_controller_settings::battery_hi, smart_controller_settings::battery_lo, clamp(), ctxt, smart_controller_settings::enabled, enabled, input_context::handle_input(), inc_clamp_wrap(), init_window(), lo_and_hi_slider, manual, max(), MENU_ITEMS_N, min(), snippet_library::random_from_category(), ui_manager::redraw(), refresh(), scrollable_text(), selection, settings, slider, SNIPPET, and win.
Referenced by vehicle::build_interact_menu().
refresh()
void smart_controller_ui::refresh () private
Definition at line 38 of file smart_controller_ui.cpp.
 {
     werase( win );
     draw_border( win );
     const nc_color gray = c_light_gray;
     const nc_color white = c_white;
     const nc_color lgreen = c_light_green;
     const nc_color red = c_red;
     // header
     const std::string title =  _( "Smart Engine Controller ® Interface" );
     mvwprintz( win, point( ( WIDTH - title.length() ) / 2, 1 ), white, title );
     mvwhline( win, point( 1, 2 ), LINE_OXOX, WIDTH - 2 );
     // for menu items, y points to the center of the menu item vertical space
     int y = 3 + MENU_ITEM_HEIGHT / 2;
     // enabled flag
     mvwprintz( win, point( LEFT_MARGIN, y ), gray,  "[ ]" );
     if( settings.enabled ) {
         mvwprintz( win, point( LEFT_MARGIN + 1, y ), white, "X" );
     }
     mvwprintz( win, point( LEFT_MARGIN + 4, y ),
                selection == smart_controller_ui_selection::enabled ? hilite( white ) : gray,
                _( "Enabled" ) );
     // battery % slider
     y += MENU_ITEM_HEIGHT;
     mvwprintz( win, point( LEFT_MARGIN, y - 1 ),
                selection == smart_controller_ui_selection::lo_and_hi_slider ? white : gray,
                _( "Electric motor use (%% battery)" ) );
     int lo_slider_x = settings.battery_lo * SLIDER_W / 100;
     int hi_slider_x = settings.battery_hi * SLIDER_W / 100 ;
     // print selected % numbers
     std::string battery_low_text = string_format( "%d%%", settings.battery_lo );
     mvwprintz( win, point( LEFT_MARGIN + lo_slider_x - battery_low_text.length() + 1, y + 2 ),
                selection == smart_controller_ui_selection::lo_and_hi_slider &&
                slider == 0 ? hilite( white ) : red, battery_low_text );
     mvwprintz( win, point( LEFT_MARGIN + hi_slider_x, y + 2 ),
                selection == smart_controller_ui_selection::lo_and_hi_slider &&
                slider == 1 ? hilite( white ) : lgreen, "%d%%", settings.battery_hi );
     // draw slider horizontal line
     for( int i = 0; i < SLIDER_W; ++i ) {
         nc_color col = selection == smart_controller_ui_selection::lo_and_hi_slider ? white : gray;
         mvwprintz( win, point( LEFT_MARGIN + i, y + 1 ), col, "-" );
     }
     // print LO and HI on the slider line
     //~ abbreviation for the "LOW" battery zone displayed on the Smart Controller UI slider. Keep it short (2-3 chars)
     std::string lo_text = _( "LO" );
     mvwprintz( win, point( LEFT_MARGIN + ( lo_slider_x - lo_text.length() ) / 2, y + 1 ), red,
                lo_text );
     //~ abbreviation for the "HIGH" battery zone displayed on the Smart Controller UI slider. Keep it short (2-3 chars)
     std::string hi_text = _( "HI" );
     int hi_text_l = hi_text.length();
     mvwprintz( win, point( LEFT_MARGIN + hi_slider_x + std::max( ( SLIDER_W - hi_slider_x -
                            hi_text_l ) / 2, 1 ), y + 1 ), lgreen, hi_text );
     // print bars on the slider
     mvwprintz( win, point( LEFT_MARGIN + lo_slider_x, y + 1 ),
                selection == smart_controller_ui_selection::lo_and_hi_slider &&
                slider == 0 ? hilite( white ) : red, "|" );
     mvwprintz( win, point( LEFT_MARGIN + hi_slider_x, y + 1 ),
                selection == smart_controller_ui_selection::lo_and_hi_slider &&
                slider == 1 ? hilite( white ) : lgreen, "|" );
     // user manual
     y += MENU_ITEM_HEIGHT;
     mvwprintz( win, point( LEFT_MARGIN, y ),
                selection == smart_controller_ui_selection::manual ? hilite( white ) : gray,
                _( "User manual" ) );
     // key descriptions
     std::string keys_text = string_format(
                                 _( "Use [<color_yellow>%s</color> and <color_yellow>%s</color>] to select option.\n"
                                    "Use [<color_yellow>%s</color>] to change value.\n"
                                    "Use [<color_yellow>%s</color> or <color_yellow>%s</color>] to switch between sliders.\n"
                                    "Use [<color_yellow>%s</color> and <color_yellow>%s</color>] to move sliders."
                                    "Use [<color_yellow>%s</color>] to apply changes and quit." ),
                                 ctxt.get_desc( "UP" ),
                                 ctxt.get_desc( "DOWN" ),
                                 ctxt.get_desc( "CONFIRM" ),
                                 ctxt.get_desc( "NEXT_TAB" ),
                                 ctxt.get_desc( "CONFIRM" ),
                                 ctxt.get_desc( "LEFT" ),
                                 ctxt.get_desc( "RIGHT" ),
                                 ctxt.get_desc( "QUIT" ) );
     int keys_text_w =  WIDTH - 2;
     int keys_text_lines_n = foldstring( keys_text, keys_text_w ).size();
     fold_and_print( win, point( 1, HEIGHT - 1 - keys_text_lines_n ), keys_text_w, gray, keys_text );
     wnoutrefresh( win );
 }
References _, smart_controller_settings::battery_hi, smart_controller_settings::battery_lo, c_light_gray, c_light_green, c_red, c_white, ctxt, draw_border(), smart_controller_settings::enabled, enabled, fold_and_print(), foldstring(), input_context::get_desc(), HEIGHT, hilite(), LEFT_MARGIN, LINE_OXOX, lo_and_hi_slider, manual, max(), MENU_ITEM_HEIGHT, catacurses::mvwhline(), mvwprintz(), point, catacurses::red, selection, settings, slider, SLIDER_W, string_format(), music::title, catacurses::werase(), catacurses::white, WIDTH, win, and catacurses::wnoutrefresh().
Referenced by control().
Member Data Documentation
ctxt
input_context smart_controller_ui::ctxt private
Definition at line 54 of file smart_controller_ui.h.
Referenced by control(), refresh(), and smart_controller_ui().
HEIGHT
const int smart_controller_ui::HEIGHT = 36 static
Definition at line 36 of file smart_controller_ui.h.
Referenced by init_window(), and refresh().
LEFT_MARGIN
const int smart_controller_ui::LEFT_MARGIN = 6 static private
Definition at line 45 of file smart_controller_ui.h.
Referenced by refresh().
MENU_ITEM_HEIGHT
const int smart_controller_ui::MENU_ITEM_HEIGHT = 5 static private
Definition at line 47 of file smart_controller_ui.h.
Referenced by refresh().
MENU_ITEMS_N
const int smart_controller_ui::MENU_ITEMS_N = smart_controller_ui_selection::length static private
Definition at line 48 of file smart_controller_ui.h.
Referenced by control().
selection
int smart_controller_ui::selection = smart_controller_ui_selection::init private
Definition at line 59 of file smart_controller_ui.h.
Referenced by control(), and refresh().
settings
const smart_controller_settings smart_controller_ui::settings private
Definition at line 56 of file smart_controller_ui.h.
Referenced by control(), and refresh().
slider
int smart_controller_ui::slider = 0 private
Definition at line 61 of file smart_controller_ui.h.
Referenced by control(), and refresh().
SLIDER_W
const int smart_controller_ui::SLIDER_W = 40 static private
Definition at line 50 of file smart_controller_ui.h.
Referenced by refresh().
WIDTH
const int smart_controller_ui::WIDTH = 52 static
Definition at line 35 of file smart_controller_ui.h.
Referenced by init_window(), and refresh().
win
catacurses::window smart_controller_ui::win private
Definition at line 53 of file smart_controller_ui.h.
Referenced by control(), and refresh().
The documentation for this class was generated from the following files:
src/smart_controller_ui.h
src/smart_controller_ui.cpp