Cataclysm DDA: ma_buff_reader Class Reference
ma_buff_reader Class Reference
Public Member Functions
mabuff_id get_next (const JsonValue &jin) const
Public Member Functions inherited from generic_typed_reader< ma_buff_reader >
void insert_values_from (const JsonObject &jo, const std::string_view member_name, C &container) const
void insert_next (JsonValue &jv, C &container) const
void erase_values_from (const JsonObject &jo, const std::string_view member_name, C &container) const
void erase_next (JsonValue &jv, C &container) const
bool operator() (const JsonObject &jo, const std::string_view member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string_view member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string_view name, C &) const
bool do_relative (const JsonObject &jo, const std::string_view name, C &member) const
bool read_normal (const JsonObject &jo, const std::string_view name, C &member) const
Detailed Description
Definition at line 345 of file martialarts.cpp.
Member Function Documentation
get_next()
mabuff_id ma_buff_reader::get_next (const JsonValue & jin) const inline
Definition at line 348 of file martialarts.cpp.
{
             if( jin.test_string() ) {
                 return mabuff_id( jin.get_string() );
             }
             JsonObject jsobj = jin.get_object();
             ma_buffs.load( jsobj, "" );
             return mabuff_id( jsobj.get_string( "id" ) );
         }
References JsonValue::get_object(), JsonValue::get_string(), JsonObject::get_string(), anonymous_namespace{martialarts.cpp}::ma_buffs, and JsonValue::test_string().
The documentation for this class was generated from the following file:
src/martialarts.cpp