Cataclysm DDA: craft_command Class Reference
craft_command Class Reference
Class that describes a crafting job.
#include <craft_command.h>
Public Member Functions
craft_command ()=default
Instantiates an empty craft_command, which can't be executed.
craft_command (const recipe *to_make, int batch_size, bool is_long, Character *crafter, const std::optional< tripoint > &loc)
void execute (const std::optional< tripoint > &new_loc)
Selects components to use for the craft, then assigns the crafting activity to 'crafter'.
void execute (bool only_cache_comps=false)
Executes with saved location, NOT the same as execute(std::nullopt)!
item create_in_progress_craft ()
Consumes the selected components and returns the resulting in progress craft item.
bool is_long () const
bool has_cached_selections () const
bool empty () const
skill_id get_skill_id ()
bool continue_prompt_liquids (const std::function< bool(const item &)> &filter, bool no_prompt=false)
Static Public Member Functions
static bool safe_to_unload_comp (const item &it)
Private Member Functions
std::vector< comp_selection< item_comp > > check_item_components_missing (const read_only_visitable &map_inv) const
Checks if tools we selected in a previous call to execute() are still available.
std::vector< comp_selection< tool_comp > > check_tool_components_missing (const read_only_visitable &map_inv) const
Checks if items we selected in a previous call to execute() are still available.
bool query_continue (const std::vector< comp_selection< item_comp >> &missing_items, const std::vector< comp_selection< tool_comp >> &missing_tools)
Creates a continue pop up asking to continue crafting and listing the missing components.
Private Attributes
const recipe * rec = nullptr
int batch_size = 0
bool longcraft = false
Indicates whether the player has initiated a one off craft or wishes to craft as long as possible.
Character * crafter
recipe_filter_flags flags = recipe_filter_flags::none
std::optional< tripoint > loc
std::vector< comp_selection< item_comp > > item_selections
std::vector< comp_selection< tool_comp > > tool_selections
Detailed Description
Class that describes a crafting job.
The class has functions to execute the crafting job.
Definition at line 62 of file craft_command.h.
Constructor & Destructor Documentation
craft_command() [1/2]
craft_command::craft_command () default
Instantiates an empty craft_command, which can't be executed.
craft_command() [2/2]
craft_command::craft_command (const recipe * to_make, int batch_size, bool is_long, Character * crafter, const std::optional< tripoint > & loc) inline
Definition at line 67 of file craft_command.h.
                                                           :
             rec( to_make ), batch_size( batch_size ), longcraft( is_long ), crafter( crafter ), loc( loc ) {}
Member Function Documentation
check_item_components_missing()
std::vector< comp_selection< item_comp > > craft_command::check_item_components_missing (const read_only_visitable & map_inv) const private
Checks if tools we selected in a previous call to execute() are still available.
Definition at line 504 of file craft_command.cpp.
 {
     std::vector<comp_selection<item_comp>> missing;
     const auto filter = rec->get_component_filter( flags );
     for( const auto &item_sel : item_selections ) {
         itype_id type = item_sel.comp.type;
         const item_comp component = item_sel.comp;
         const int count = component.count > 0 ? component.count * batch_size : std::abs( component.count );
         if( item::count_by_charges( type ) && count > 0 ) {
             switch( item_sel.use_from ) {
                 case usage_from::player:
                     if( !crafter->has_charges( type, count, filter ) ) {
                         missing.push_back( item_sel );
                     }
                     break;
                 case usage_from::map:
                     if( !map_inv.has_charges( type, count, filter ) ) {
                         missing.push_back( item_sel );
                     }
                     break;
                 case usage_from::both:
                     if( !( crafter->charges_of( type, INT_MAX, filter ) +
                            map_inv.charges_of( type, INT_MAX, filter ) >= count ) ) {
                         missing.push_back( item_sel );
                     }
                     break;
                 case usage_from::none:
                 case usage_from::cancel:
                 case usage_from::num_usages_from:
                     break;
             }
         } else {
             // Counting by units, not charges.
             switch( item_sel.use_from ) {
                 case usage_from::player:
                     if( !crafter->has_amount( type, count, false, filter ) ) {
                         missing.push_back( item_sel );
                     }
                     break;
                 case usage_from::map:
                     if( !map_inv.has_components( type, count, filter ) ) {
                         missing.push_back( item_sel );
                     }
                     break;
                 case usage_from::both:
                     if( !( crafter->amount_of( type, false, std::numeric_limits<int>::max(), filter ) +
                            map_inv.amount_of( type, false, std::numeric_limits<int>::max(), filter ) >= count ) ) {
                         missing.push_back( item_sel );
                     }
                     break;
                 case usage_from::none:
                 case usage_from::cancel:
                 case usage_from::num_usages_from:
                     break;
             }
         }
     }
     return missing;
 }
References abs(), read_only_visitable::amount_of(), Character::amount_of(), batch_size, both, cancel, read_only_visitable::charges_of(), Character::charges_of(), component::count, item::count_by_charges(), crafter, filter, flags, recipe::get_component_filter(), visitable::has_amount(), read_only_visitable::has_charges(), Character::has_charges(), read_only_visitable::has_components(), item_selections, map, max(), none, num_usages_from, player, rec, and type.
Referenced by create_in_progress_craft(), and execute().
check_tool_components_missing()
std::vector< comp_selection< tool_comp > > craft_command::check_tool_components_missing (const read_only_visitable & map_inv) const private
Checks if items we selected in a previous call to execute() are still available.
Definition at line 569 of file craft_command.cpp.
 {
     std::vector<comp_selection<tool_comp>> missing;
     for( const auto &tool_sel : tool_selections ) {
         itype_id type = tool_sel.comp.type;
         if( tool_sel.comp.count > 0 ) {
             const int count = tool_sel.comp.count * batch_size;
             switch( tool_sel.use_from ) {
                 case usage_from::player:
                     if( !crafter->has_charges( type, count ) ) {
                         missing.push_back( tool_sel );
                     }
                     break;
                 case usage_from::map:
                     if( !map_inv.has_charges( type, count ) ) {
                         missing.push_back( tool_sel );
                     }
                     break;
                 case usage_from::both:
                 case usage_from::none:
                 case usage_from::cancel:
                 case usage_from::num_usages_from:
                     break;
             }
         } else if( !crafter->has_amount( type, 1 ) && !map_inv.has_tools( type, 1 ) ) {
             missing.push_back( tool_sel );
         }
     }
     return missing;
 }
References batch_size, both, cancel, crafter, visitable::has_amount(), read_only_visitable::has_charges(), Character::has_charges(), read_only_visitable::has_tools(), map, none, num_usages_from, player, tool_selections, and type.
Referenced by execute().
continue_prompt_liquids()
bool craft_command::continue_prompt_liquids (const std::function< bool(const item &)> & filter, bool no_prompt = false)
Definition at line 262 of file craft_command.cpp.
 {
     map &m = get_map();
     for( const auto &it : item_selections ) {
         const std::vector<pocket_data> it_pkt = it.comp.type->pockets;
         if( ( item::count_by_charges( it.comp.type ) && it.comp.count > 0 ) ||
         !std::any_of( it_pkt.begin(), it_pkt.end(), []( const pocket_data & p ) {
         return p.type == pocket_type::CONTAINER && p.watertight;
     } ) ) {
             continue;
         }
         // Everything below only occurs for item components that are liquid containers
         std::function<bool( const item & )> empty_filter = [&filter]( const item & it ) {
             return it.empty_container() && filter( it );
         };
         const char *liq_cont_msg = _( "%1$s is not empty.  Continue anyway?" );
         std::vector<std::pair<const tripoint, item>> map_items;
         std::vector<std::pair<const vpart_reference, item>> veh_items;
         std::vector<item> inv_items;
         auto reset_items = [&]() {
             for( auto &mit : map_items ) {
                 m.add_item_or_charges( mit.first, mit.second );
             }
             for( item &iit : inv_items ) {
                 crafter->i_add_or_drop( iit );
             }
             for( auto &vit : veh_items ) {
                 vit.first.vehicle().add_item( vit.first.part(), vit.second );
             }
         };
         int real_count = ( it.comp.count > 0 ) ? it.comp.count * batch_size : std::abs( it.comp.count );
         for( int i = 0; i < 2 && real_count > 0; i++ ) {
             if( it.use_from & usage_from::map ) {
                 const tripoint &loc = crafter->pos();
                 for( int radius = 0; radius <= PICKUP_RANGE && real_count > 0; radius++ ) {
                     for( const tripoint &p : m.points_in_radius( loc, radius ) ) {
                         if( rl_dist( loc, p ) >= radius ) {
                             // "Simulate" consuming items and put them back
                             // not very efficient but should be rare enough not to matter
                             std::list<item> tmp = m.use_amount_square( p, it.comp.type, real_count,
                                                   i == 0 ? empty_filter : filter );
                             bool cont_not_empty = false;
                             std::string iname;
                             for( item &tmp_i : tmp ) {
                                 if( !tmp_i.empty_container() ) {
                                     cont_not_empty = true;
                                     iname = tmp_i.tname( 1U, true );
                                 }
                                 if( const std::optional<vpart_reference> vp = m.veh_at( p ).cargo() ) {
                                     veh_items.emplace_back( vp.value(), tmp_i );
                                 } else {
                                     map_items.emplace_back( p, tmp_i );
                                 }
                             }
                             if( cont_not_empty && ( no_prompt || !query_yn( liq_cont_msg, iname ) ) ) {
                                 reset_items();
                                 return false;
                             }
                         }
                     }
                 }
             }
             if( it.use_from & usage_from::player && real_count > 0 ) {
                 // "Simulate" consuming items and put them back
                 // not very efficient but should be rare enough not to matter
                 std::list<item> tmp = crafter->use_amount( it.comp.type, real_count,
                                       i == 0 ? empty_filter : filter );
                 real_count -= tmp.size();
                 bool cont_not_empty = false;
                 std::string iname;
                 for( item &tmp_i : tmp ) {
                     if( !tmp_i.empty_container() ) {
                         cont_not_empty = true;
                         iname = tmp_i.tname( 1U, true );
                     }
                     inv_items.emplace_back( tmp_i );
                 }
                 if( cont_not_empty && ( no_prompt || !query_yn( liq_cont_msg, iname ) ) ) {
                     reset_items();
                     return false;
                 }
             }
         }
         reset_items();
     }
     return true;
 }
References _, abs(), map::add_item_or_charges(), batch_size, optional_vpart_position::cargo(), item::count_by_charges(), crafter, filter, get_map(), Character::i_add_or_drop(), item_selections, loc, map, player, map::points_in_radius(), Creature::pos(), query_yn(), rl_dist(), pocket_data::type, Character::use_amount(), map::use_amount_square(), and map::veh_at().
Referenced by create_in_progress_craft().
create_in_progress_craft()
item craft_command::create_in_progress_craft ()
Consumes the selected components and returns the resulting in progress craft item.
Must be called after execute().
Definition at line 428 of file craft_command.cpp.
 {
     // Use up the components and tools
     item_components used;
     std::vector<item_comp> comps_used;
     if( crafter->has_trait( trait_DEBUG_HS ) ) {
         return item( rec, batch_size, used, comps_used );
     }
     if( empty() ) {
         debugmsg( "Warning: attempted to consume items from an empty craft_command" );
         return item();
     }
     inventory map_inv;
     map_inv.form_from_map( crafter->pos(), PICKUP_RANGE, crafter );
     if( !check_item_components_missing( map_inv ).empty() ) {
         debugmsg( "Aborting crafting: couldn't find cached components" );
         return item();
     }
     const auto filter = rec->get_component_filter( flags );
     if( crafter->is_avatar() &&
         !continue_prompt_liquids( filter ) ) {
         // player cancelled when prompted to unload liquid
         return item();
     }
     for( const auto &it : item_selections ) {
         std::list<item> tmp = sane_consume_items( it, crafter, batch_size, filter );
         for( item &tmp_it : tmp ) {
             if( safe_to_unload_comp( tmp_it ) ) {
                 item_location tmp_loc( *crafter, &tmp_it );
                 unload_activity_actor::unload( *crafter, tmp_loc );
             }
         }
         for( item &it : tmp ) {
             used.add( it );
         }
     }
     for( const comp_selection<item_comp> &selection : item_selections ) {
         item_comp comp_used = selection.comp;
         comp_used.count *= batch_size;
         //Handle duplicate component requirement
         auto found_it = std::find_if( comps_used.begin(),
         comps_used.end(), [&comp_used]( const item_comp & c ) {
             return c.type == comp_used.type;
         } );
         if( found_it != comps_used.end() ) {
             item_comp &found_comp = *found_it;
             found_comp.count += comp_used.count;
         } else {
             comps_used.emplace_back( comp_used );
         }
     }
     item new_craft( rec, batch_size, used, comps_used );
     new_craft.set_cached_tool_selections( tool_selections );
     new_craft.set_tools_to_continue( true );
     // Pass true to indicate that we are starting the craft and the remainder should be consumed as well
     crafter->craft_consume_tools( new_craft, 1, true );
     new_craft.set_next_failure_point( *crafter );
     return new_craft;
 }
References item_components::add(), batch_size, c, check_item_components_missing(), continue_prompt_liquids(), component::count, Character::craft_consume_tools(), crafter, debugmsg, empty(), filter, flags, inventory::form_from_map(), recipe::get_component_filter(), Character::has_trait(), Creature::is_avatar(), item, item_selections, PICKUP_RANGE, Creature::pos(), rec, safe_to_unload_comp(), sane_consume_items(), item::set_cached_tool_selections(), item::set_next_failure_point(), item::set_tools_to_continue(), tool_selections, trait_DEBUG_HS, and unload_activity_actor::unload().
Referenced by Character::start_craft().
empty()
bool craft_command::empty () const inline
Definition at line 93 of file craft_command.h.
{
             return rec == nullptr;
         }
References rec.
Referenced by create_in_progress_craft(), execute(), and Character::start_craft().
execute() [1/2]
void craft_command::execute (bool only_cache_comps = false)
Executes with saved location, NOT the same as execute(std::nullopt)!
Definition at line 123 of file craft_command.cpp.
 {
     if( empty() ) {
         return;
     }
     bool need_selections = true;
     inventory map_inv;
     map_inv.form_from_map( crafter->pos(), PICKUP_RANGE, crafter );
     if( has_cached_selections() ) {
         std::vector<comp_selection<item_comp>> missing_items = check_item_components_missing( map_inv );
         std::vector<comp_selection<tool_comp>> missing_tools = check_tool_components_missing( map_inv );
         if( missing_items.empty() && missing_tools.empty() ) {
             // All items we used previously are still there, so we don't need to do selection.
             need_selections = false;
         } else if( !only_cache_comps && !query_continue( missing_items, missing_tools ) ) {
             return;
         }
     }
     if( need_selections ) {
         if( !crafter->can_make( rec, batch_size ) ) {
             if( crafter->can_start_craft( rec, recipe_filter_flags::none, batch_size ) ) {
                 if( !query_yn( _( "You don't have enough charges to complete the %s.\n"
                                   "Start crafting anyway?" ), rec->result_name() ) ) {
                     return;
                 }
             } else if( !rec->character_has_required_proficiencies( *crafter ) ) {
                 popup( _( "You don't have the required proficiencies to craft this!" ) );
                 return;
             } else {
                 debugmsg( "Tried to start craft without sufficient charges" );
                 return;
             }
         }
         flags = recipe_filter_flags::no_rotten;
         if( !crafter->can_start_craft( rec, flags, batch_size ) ) {
             if( !query_yn( _( "This craft will use rotten components.\n"
                               "Start crafting anyway?" ) ) ) {
                 return;
             }
             flags = recipe_filter_flags::none;
         }
         flags |= recipe_filter_flags::no_favorite;
         if( !crafter->can_start_craft( rec, flags, batch_size ) ) {
             if( !query_yn( _( "This craft will use favorited components.\n"
                               "Start crafting anyway?" ) ) ) {
                 return;
             }
             flags = flags & recipe_filter_flags::no_rotten ? recipe_filter_flags::no_rotten :
                     recipe_filter_flags::none;
         }
         item_selections.clear();
         const auto filter = rec->get_component_filter( flags );
         const requirement_data *needs = rec->deduped_requirements().select_alternative(
                                             *crafter, filter, batch_size, craft_flags::start_only );
         if( !needs ) {
             return;
         }
         for( const auto &it : needs->get_components() ) {
             comp_selection<item_comp> is =
                 crafter->select_item_component( it, batch_size, map_inv, true, filter, true, true, rec );
             if( is.use_from == usage_from::cancel ) {
                 return;
             }
             item_selections.push_back( is );
         }
         tool_selections.clear();
         for( const auto &it : needs->get_tools() ) {
             comp_selection<tool_comp> ts = crafter->select_tool_component(
             it, batch_size, map_inv, true, true, true, []( int charges ) {
                 return charges / 20 + charges % 20;
             } );
             if( ts.use_from == usage_from::cancel ) {
                 return;
             }
             tool_selections.push_back( ts );
         }
     }
     if( only_cache_comps ) {
         return;
     }
     crafter->start_craft( *this, loc );
     crafter->last_batch = batch_size;
     crafter->lastrecipe = rec->ident();
     const auto iter = std::find( uistate.recent_recipes.begin(), uistate.recent_recipes.end(),
                                  rec->ident() );
     if( iter != uistate.recent_recipes.end() ) {
         uistate.recent_recipes.erase( iter );
     }
     uistate.recent_recipes.push_back( rec->ident() );
     if( uistate.recent_recipes.size() > 20 ) {
         uistate.recent_recipes.erase( uistate.recent_recipes.begin() );
     }
 }
References _, batch_size, Character::can_make(), Character::can_start_craft(), cancel, recipe::character_has_required_proficiencies(), check_item_components_missing(), check_tool_components_missing(), crafter, debugmsg, recipe::deduped_requirements(), empty(), filter, flags, inventory::form_from_map(), recipe::get_component_filter(), requirement_data::get_components(), requirement_data::get_tools(), has_cached_selections(), recipe::ident(), item_selections, Character::last_batch, Character::lastrecipe, loc, no_favorite, no_rotten, none, PICKUP_RANGE, popup(), Creature::pos(), query_continue(), query_yn(), rec, uistatedata::recent_recipes, recipe::result_name(), deduped_requirement_data::select_alternative(), Character::select_item_component(), Character::select_tool_component(), Character::start_craft(), start_only, tool_selections, uistate, and comp_selection< CompType >::use_from.
execute() [2/2]
void craft_command::execute (const std::optional< tripoint > & new_loc)
Selects components to use for the craft, then assigns the crafting activity to 'crafter'.
Executes with supplied location, std::nullopt means crafting from inventory.
Definition at line 116 of file craft_command.cpp.
 {
     loc = new_loc;
     execute();
 }
References loc.
get_skill_id()
skill_id craft_command::get_skill_id ()
Definition at line 499 of file craft_command.cpp.
 {
     return rec->skill_used;
 }
References rec, and recipe::skill_used.
Referenced by Character::start_craft().
has_cached_selections()
bool craft_command::has_cached_selections () const inline
Definition at line 89 of file craft_command.h.
{
             return !item_selections.empty() || !tool_selections.empty();
         }
References item_selections, and tool_selections.
Referenced by execute().
is_long()
bool craft_command::is_long () const inline
Definition at line 85 of file craft_command.h.
{
             return longcraft;
         }
References longcraft.
Referenced by Character::start_craft().
query_continue()
bool craft_command::query_continue (const std::vector< comp_selection< item_comp >> & missing_items, const std::vector< comp_selection< tool_comp >> & missing_tools) private
Creates a continue pop up asking to continue crafting and listing the missing components.
Definition at line 242 of file craft_command.cpp.
 {
     std::string ss = _( "Some components used previously are missing.  Continue?" );
     if( !missing_items.empty() ) {
         ss += "\n";
         ss += _( "Item(s): " );
         ss += component_list_string( missing_items );
     }
     if( !missing_tools.empty() ) {
         ss += "\n";
         ss += _( "Tool(s): " );
         ss += component_list_string( missing_tools );
     }
     return query_yn( ss );
 }
References _, component_list_string(), and query_yn().
Referenced by execute().
safe_to_unload_comp()
bool craft_command::safe_to_unload_comp (const item & it) static
Definition at line 398 of file craft_command.cpp.
 {
     // Candle wax from candles should be consumed with the candle
     if( it.is_container_empty() || it.typeId() == itype_candle ) {
         return false;
     }
     // Return true if item contains anything "real"
     const std::function<bool( const item &i )> filter = []( const item & i ) {
         return !i.has_flag( flag_ZERO_WEIGHT ) && !i.has_flag( flag_NO_DROP );
     };
     const bool valid = it.get_contents().has_any_with( filter, pocket_type::CONTAINER ) ||
                        it.get_contents().has_any_with( filter, pocket_type::MAGAZINE ) ||
                        it.get_contents().has_any_with( filter, pocket_type::MAGAZINE_WELL );
     if( valid ) {
         return true;
     }
     // Don't try to unload items that shouldn't be outside their container
     itype_id ammo = it.loaded_ammo().typeId();
     if( ammo.is_null() ) {
         return !it.empty_container();
     } else if( ammo->has_flag( flag_ZERO_WEIGHT ) ||
                ammo->has_flag( flag_NO_DROP ) ) {
         return false;
     }
     return true;
 }
References CONTAINER, item::empty_container(), filter, flag_NO_DROP, flag_ZERO_WEIGHT, item::get_contents(), item_contents::has_any_with(), item::has_flag(), itype::has_flag(), item::is_container_empty(), string_id< T >::is_null(), itype_candle, item::loaded_ammo(), MAGAZINE, MAGAZINE_WELL, and item::typeId().
Referenced by create_in_progress_craft().
Member Data Documentation
batch_size
int craft_command::batch_size = 0 private
Definition at line 104 of file craft_command.h.
Referenced by check_item_components_missing(), check_tool_components_missing(), continue_prompt_liquids(), create_in_progress_craft(), and execute().
crafter
Character* craft_command::crafter private
Definition at line 111 of file craft_command.h.
Referenced by check_item_components_missing(), check_tool_components_missing(), continue_prompt_liquids(), create_in_progress_craft(), and execute().
flags
recipe_filter_flags craft_command::flags = recipe_filter_flags::none private
Definition at line 113 of file craft_command.h.
Referenced by check_item_components_missing(), create_in_progress_craft(), and execute().
item_selections
std::vector<comp_selection<item_comp> > craft_command::item_selections private
Definition at line 119 of file craft_command.h.
Referenced by check_item_components_missing(), continue_prompt_liquids(), create_in_progress_craft(), execute(), and has_cached_selections().
loc
std::optional<tripoint> craft_command::loc private
Definition at line 117 of file craft_command.h.
Referenced by continue_prompt_liquids(), and execute().
longcraft
bool craft_command::longcraft = false private
Indicates whether the player has initiated a one off craft or wishes to craft as long as possible.
Definition at line 109 of file craft_command.h.
Referenced by is_long().
rec
const recipe* craft_command::rec = nullptr private
Definition at line 103 of file craft_command.h.
Referenced by check_item_components_missing(), create_in_progress_craft(), empty(), execute(), and get_skill_id().
tool_selections
std::vector<comp_selection<tool_comp> > craft_command::tool_selections private
Definition at line 120 of file craft_command.h.
Referenced by check_tool_components_missing(), create_in_progress_craft(), execute(), and has_cached_selections().
The documentation for this class was generated from the following files:
src/craft_command.h
src/craft_command.cpp