Cataclysm DDA: panel_manager Class Reference
panel_manager Class Reference
#include <panels.h>
Public Member Functions
panel_manager ()
~panel_manager ()=default
panel_manager (panel_manager &&)=default
panel_manager (const panel_manager &)=default
panel_manager & operator= (panel_manager &&)=default
panel_manager & operator= (const panel_manager &)=default
panel_layout & get_current_layout ()
widget * get_current_sidebar ()
widget * get_sidebar (const std::string &name)
std::string get_current_layout_id () const
int get_width_right () const
int get_width_left () const
void show_adm ()
void init ()
Static Public Member Functions
static panel_manager & get_manager ()
Private Member Functions
bool save ()
bool load ()
void serialize (JsonOut &json)
void deserialize (const JsonArray &ja)
void update_offsets (int x)
Private Attributes
int width_right = 0
int width_left = 0
std::string current_layout_id
std::map< std::string, panel_layout > layouts
friend widget
Detailed Description
Definition at line 122 of file panels.h.
Constructor & Destructor Documentation
panel_manager() [1/3]
panel_manager::panel_manager ()
Definition at line 348 of file panels.cpp.
 {
     current_layout_id = "legacy_labels_sidebar";
     // Set empty layouts; these will be populated by load()
     layouts = std::map<std::string, panel_layout>();
 }
References current_layout_id, and layouts.
~panel_manager()
panel_manager::~panel_manager () default
panel_manager() [2/3]
panel_manager::panel_manager (panel_manager &&) default
panel_manager() [3/3]
panel_manager::panel_manager (const panel_manager &) default
Member Function Documentation
deserialize()
void panel_manager::deserialize (const JsonArray & ja) private
Definition at line 475 of file panels.cpp.
 {
     JsonObject joLayouts = ja.get_object( 0 );
     current_layout_id = joLayouts.get_string( "current_layout_id" );
     if( layouts.find( current_layout_id ) == layouts.end() ) {
         // Layout id updated between loads.
         // Shouldn't happen unless custom sidebar id's were modified or removed.
         joLayouts.allow_omitted_members();
         current_layout_id = "labels";
         return;
     }
     for( JsonObject joLayout : joLayouts.get_array( "layouts" ) ) {
         std::string layout_id = joLayout.get_string( "layout_id" );
         const auto &cur_layout = layouts.find( layout_id );
         if( cur_layout == layouts.end() ) {
             joLayout.allow_omitted_members();
             continue;
         }
         auto &layout = cur_layout->second.panels();
         auto it = layout.begin();
         for( JsonObject joPanel : joLayout.get_array( "panels" ) ) {
             std::string id = joPanel.get_string( "name" );
             bool toggle = joPanel.get_bool( "toggle" );
             for( auto it2 = layout.begin() + std::distance( layout.begin(), it ); it2 != layout.end(); ++it2 ) {
                 if( it2->get_id() == id ) {
                     if( it->get_id() != id ) {
                         window_panel panel = *it2;
                         layout.erase( it2 );
                         it = layout.insert( it, panel );
                     }
                     it->toggle = toggle;
                     ++it;
                     break;
                 }
             }
         }
     }
     if( ja.size() > 1 ) {
         ja.throw_error( "panel_manager expects one object" );
     }
 }
References JsonObject::allow_omitted_members(), current_layout_id, JsonObject::get_array(), JsonArray::get_object(), JsonObject::get_string(), layouts, JsonArray::size(), JsonArray::throw_error(), and window_panel::toggle.
Referenced by load().
get_current_layout()
panel_layout & panel_manager::get_current_layout ()
Definition at line 355 of file panels.cpp.
 {
     auto kv = layouts.find( current_layout_id );
     if( kv != layouts.end() ) {
         return kv->second;
     }
     debugmsg( "Invalid current panel layout, defaulting to classic" );
     current_layout_id = "legacy_classic_sidebar";
     return get_current_layout();
 }
References current_layout_id, debugmsg, and layouts.
Referenced by game::draw_panels(), get_current_sidebar(), init(), game::look_around(), and show_adm().
get_current_layout_id()
std::string panel_manager::get_current_layout_id () const
Definition at line 385 of file panels.cpp.
 {
     return current_layout_id;
 }
References current_layout_id.
Referenced by target_ui::init_window_and_input(), and print_ranged_chance().
get_current_sidebar()
widget * panel_manager::get_current_sidebar ()
Definition at line 366 of file panels.cpp.
 {
     panel_layout layout = get_current_layout();
     const std::string name = layout.name();
     return get_sidebar( name );
 }
References get_current_layout(), get_sidebar(), panel_layout::name(), and om_direction::name().
Referenced by init(), and show_adm().
get_manager()
static panel_manager& panel_manager::get_manager () inline static
Definition at line 132 of file panels.h.
{
             static panel_manager single_instance;
             return single_instance;
         }
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), advanced_inventory::display(), game::do_regular_action(), game::draw_panels(), Messages::dialog::init(), target_ui::init_window_and_input(), game::look_around(), print_ranged_chance(), game::setup(), live_view::show(), and show_adm().
get_sidebar()
widget * panel_manager::get_sidebar (const std::string & name)
Definition at line 373 of file panels.cpp.
 {
     widget *w = nullptr;
     for( const widget &wgt : widget::get_all() ) {
         if( wgt._style == "sidebar" && wgt._label.translated() == name ) {
             w = const_cast<widget *>( &wgt );
             break;
         }
     }
     return w;
 }
References widget::get_all(), and om_direction::name().
Referenced by get_current_sidebar(), and show_adm().
get_width_left()
int panel_manager::get_width_left () const
Definition at line 398 of file panels.cpp.
 {
     if( get_option<std::string>( "SIDEBAR_POSITION" ) == "left" ) {
         return width_right;
     }
     return width_left;
 }
References width_left, and width_right.
Referenced by game::create_or_get_main_ui_adaptor(), Messages::dialog::init(), game::look_around(), and live_view::show().
get_width_right()
int panel_manager::get_width_right () const
Definition at line 390 of file panels.cpp.
 {
     if( get_option<std::string>( "SIDEBAR_POSITION" ) == "left" ) {
         return width_left;
     }
     return width_right;
 }
References width_left, and width_right.
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), Messages::dialog::init(), and live_view::show().
init()
void panel_manager::init ()
Definition at line 406 of file panels.cpp.
 {
     layouts = initialize_default_panel_layouts();
     load();
     update_offsets( get_current_layout().panels().begin()->get_width() );
     if( get_current_sidebar() != nullptr ) {
         widget::finalize_inherited_fields_recursive( get_current_sidebar()->getId(),
                 get_current_sidebar()->_separator, get_current_sidebar()->_padding );
     }
 }
References widget::finalize_inherited_fields_recursive(), get_current_layout(), get_current_sidebar(), initialize_default_panel_layouts(), layouts, load(), and update_offsets().
Referenced by game::setup().
load()
bool panel_manager::load () private
Definition at line 431 of file panels.cpp.
 {
     return read_from_file_optional_json( PATH_INFO::panel_options(), [&]( const JsonArray & jsin ) {
         deserialize( jsin );
     } );
 }
References deserialize(), PATH_INFO::panel_options(), and read_from_file_optional_json().
Referenced by init().
operator=() [1/2]
panel_manager& panel_manager::operator= (const panel_manager &) default
operator=() [2/2]
panel_manager& panel_manager::operator= (panel_manager &&) default
save()
bool panel_manager::save () private
Definition at line 423 of file panels.cpp.
 {
     return write_to_file( PATH_INFO::panel_options(), [&]( std::ostream & fout ) {
         JsonOut jout( fout, true );
         serialize( jout );
     }, _( "panel options" ) );
 }
References _, PATH_INFO::panel_options(), serialize(), and write_to_file().
Referenced by show_adm().
serialize()
void panel_manager::serialize (JsonOut & json) private
Definition at line 438 of file panels.cpp.
 {
     json.start_array();
     json.start_object();
     json.member( "current_layout_id", current_layout_id );
     json.member( "layouts" );
     json.start_array();
     for( const auto &kv : layouts ) {
         json.start_object();
         json.member( "layout_id", kv.first );
         json.member( "panels" );
         json.start_array();
         for( const window_panel &panel : kv.second.panels() ) {
             json.start_object();
             json.member( "name", panel.get_id() );
             json.member( "toggle", panel.toggle );
             json.end_object();
         }
         json.end_array();
         json.end_object();
     }
     json.end_array();
     json.end_object();
     json.end_array();
 }
References current_layout_id, JsonOut::end_array(), JsonOut::end_object(), layouts, JsonOut::member(), JsonOut::start_array(), and JsonOut::start_object().
Referenced by save().
show_adm()
void panel_manager::show_adm ()
Definition at line 642 of file panels.cpp.
 {
     input_context ctxt( "PANEL_MGMT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "UP" );
     ctxt.register_action( "DOWN" );
     ctxt.register_action( "LEFT" );
     ctxt.register_action( "RIGHT" );
     ctxt.register_action( "MOVE_PANEL" );
     ctxt.register_action( "TOGGLE_PANEL" );
     const std::vector<int> column_widths = { 25, 37, 17 };
     size_t current_col = 0;
     size_t current_row = 0;
     bool swapping = false;
     size_t source_row = 0;
     size_t source_index = 0;
     size_t start = 0;
     bool recalc = true;
     bool exit = false;
     // map of row the panel is on vs index
     // panels not renderable due to game configuration will not be in this map
     std::map<size_t, size_t> row_indices;
     g->show_panel_adm = true;
     g->invalidate_main_ui_adaptor();
     catacurses::window w_border;
     catacurses::window w_left;
     catacurses::window w_center;
     catacurses::window w_right;
     const int popup_height = 24;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         const point uipos( ( TERMX / 2 ) - 38, ( TERMY / 2 ) - 10 );
         w_border = catacurses::newwin( popup_height, 83, uipos );
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         w_left = catacurses::newwin( popup_height - 2, column_widths[0], uipos + point( 1, 1 ) );
         w_center = catacurses::newwin( popup_height - 2, column_widths[1],
                                        uipos + point( 2 + column_widths[0], 1 ) );
         w_right = catacurses::newwin( popup_height - 2, column_widths[2],
                                       uipos + point( 3 + column_widths[0] + column_widths[1], 1 ) );
         ui.position_from_window( w_border );
     } );
     ui.mark_resize();
     ui.on_redraw( [&]( const ui_adaptor & ) {
         draw_border_win( w_border, column_widths, popup_height );
         draw_right_win( w_right, layouts, current_layout_id, current_row, current_col == 2 );
         auto &panels = get_current_layout().panels();
         draw_left_win( w_left, row_indices, panels, source_index, current_row, source_row, current_col == 0,
                        swapping, column_widths[0], popup_height - 2, start );
         widget *sidebar = nullptr;
         if( current_col == 0 ) {
             sidebar = get_current_sidebar();
         } else {
             auto it = layouts.begin();
             std::advance( it, current_row );
             panel_layout layout = it->second;
             sidebar = get_sidebar( layout.name() );
         }
         draw_center_win( w_center, column_widths[1], ctxt, *sidebar, row_indices, panels, current_row,
                          current_col == 0 );
     } );
     while( !exit ) {
         auto &panels = get_current_layout().panels();
         if( recalc ) {
             recalc = false;
             row_indices.clear();
             if( get_current_sidebar() != nullptr ) {
                 widget::finalize_inherited_fields_recursive( get_current_sidebar()->getId(),
                         get_current_sidebar()->_separator, get_current_sidebar()->_padding );
             }
             for( size_t i = 0, row = 0; i < panels.size(); i++ ) {
                 if( panels[i].render() ) {
                     row_indices.emplace( row, i );
                     row++;
                 }
             }
         }
         const size_t num_rows = current_col == 0 ? row_indices.size() : layouts.size();
         current_row = clamp<size_t>( current_row, 0, num_rows - 1 );
         if( current_row < start ) {
             start = current_row > popup_height - 3 ? current_row - ( popup_height - 3 ) : 0;
         }
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         if( action == "UP" ) {
             if( current_row > 0 ) {
                 current_row -= 1;
                 if( current_row < start ) {
                     start = current_row;
                 }
             } else {
                 current_row = num_rows - 1;
                 if( current_row > popup_height - 3 ) {
                     start = current_row - ( popup_height - 3 );
                 }
             }
         } else if( action == "DOWN" ) {
             if( current_row + 1 < num_rows ) {
                 current_row += 1;
                 if( current_row > start + popup_height - 3 ) {
                     start = current_row - ( popup_height - 3 );
                 }
             } else {
                 current_row = 0;
                 start = 0;
             }
         } else if( action == "MOVE_PANEL" && current_col == 0 ) {
             swapping = !swapping;
             if( swapping ) {
                 // source window from the swap
                 // saving win1 index
                 source_row = current_row;
                 source_index = row_indices[current_row];
             } else {
                 // dest window for the swap
                 // saving win2 index
                 const size_t target_index = row_indices[current_row];
                 int distance = target_index - source_index;
                 size_t step_dir = distance > 0 ? 1 : -1;
                 for( size_t i = source_index; i != target_index; i += step_dir ) {
                     std::swap( panels[i], panels[i + step_dir] );
                 }
                 g->invalidate_main_ui_adaptor();
                 recalc = true;
             }
         } else if( !swapping && action == "MOVE_PANEL" && current_col == 2 ) {
             auto iter = std::next( layouts.begin(), current_row );
             current_layout_id = iter->first;
             int width = panel_manager::get_manager().get_current_layout().panels().begin()->get_width();
             update_offsets( width );
             int h; // to_map_font_dimension needs a second input
             to_map_font_dimension( width, h );
             // tell the game that the main screen might have a different size now.
             g->mark_main_ui_adaptor_resize();
             // run a dummy render to set the initial height of each widget
             dummy_wgt_render( widget_id( current_layout_id ), width_right );
             recalc = true;
         } else if( !swapping && ( action == "RIGHT" || action == "LEFT" ) ) {
             // there are only two columns
             if( current_col == 0 ) {
                 current_col = 2;
             } else {
                 current_col = 0;
             }
         } else if( !swapping && action == "TOGGLE_PANEL" && current_col == 0 ) {
             panels[row_indices[current_row]].toggle = !panels[row_indices[current_row]].toggle;
             g->invalidate_main_ui_adaptor();
         } else if( action == "QUIT" ) {
             exit = true;
             save();
         }
     }
     g->show_panel_adm = false;
     g->invalidate_main_ui_adaptor();
 }
References action, current_layout_id, draw_border_win(), draw_center_win(), draw_left_win(), draw_right_win(), dummy_wgt_render(), widget::finalize_inherited_fields_recursive(), g, get_current_layout(), get_current_sidebar(), get_manager(), get_sidebar(), input_context::handle_input(), layouts, panel_layout::name(), catacurses::newwin(), panel_layout::panels(), point, ui_manager::redraw(), input_context::register_action(), save(), cata::swap(), TERMX, TERMY, to_map_font_dimension(), update_offsets(), widget_id, and width_right.
Referenced by game::do_regular_action().
update_offsets()
void panel_manager::update_offsets (int x) private
Definition at line 417 of file panels.cpp.
 {
     width_right = x;
     width_left = 0;
 }
References width_left, and width_right.
Referenced by init(), and show_adm().
Member Data Documentation
current_layout_id
std::string panel_manager::current_layout_id private
Definition at line 159 of file panels.h.
Referenced by deserialize(), get_current_layout(), get_current_layout_id(), panel_manager(), serialize(), and show_adm().
layouts
std::map<std::string, panel_layout> panel_manager::layouts private
Definition at line 160 of file panels.h.
Referenced by deserialize(), get_current_layout(), init(), panel_manager(), serialize(), and show_adm().
widget
friend panel_manager::widget private
Definition at line 162 of file panels.h.
width_left
int panel_manager::width_left = 0 private
Definition at line 158 of file panels.h.
Referenced by get_width_left(), get_width_right(), and update_offsets().
width_right
int panel_manager::width_right = 0 private
Definition at line 157 of file panels.h.
Referenced by get_width_left(), get_width_right(), show_adm(), and update_offsets().
The documentation for this class was generated from the following files:
src/panels.h
src/panels.cpp