Cataclysm DDA: npc_attack_melee Class Reference
npc_attack_melee Class Reference
#include <npc_attack.h>
Public Member Functions
npc_attack_melee (item &weapon)
npc_attack_rating evaluate (const npc &source, const Creature *target) const override
Parameters: source - the npc making the attack target - the desired target of the npc.
std::vector< npc_attack_rating > all_evaluations (const npc &source, const Creature *target) const override
For debug information.
void use (npc &source, const tripoint &location) const override
Public Member Functions inherited from npc_attack
virtual ~npc_attack ()=default
Private Member Functions
tripoint_range< tripoint > targetable_points (const npc &source) const
bool can_use (const npc &source) const
int base_time_penalty (const npc &source) const
npc_attack_rating evaluate_critter (const npc &source, const Creature *target, Creature *critter) const
Private Attributes
item & weapon
Detailed Description
Definition at line 79 of file npc_attack.h.
Constructor & Destructor Documentation
npc_attack_melee()
npc_attack_melee::npc_attack_melee (item & weapon) inline explicit
Definition at line 83 of file npc_attack.h.
 : weapon( weapon ) {}
Member Function Documentation
all_evaluations()
std::vector< npc_attack_rating > npc_attack_melee::all_evaluations (const npc & source, const Creature * target) const override virtual
For debug information.
returns all evaluated effectivenesses. This is abstracted out in evaluate() as it's faster to not use a container
Implements npc_attack.
Definition at line 357 of file npc_attack.cpp.
 {
     std::vector<npc_attack_rating> effectiveness;
     if( !can_use( source ) ) {
         return effectiveness;
     }
     const int time_penalty = base_time_penalty( source );
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &targetable_point : targetable_points( source ) ) {
         if( Creature *critter = creatures.creature_at( targetable_point ) ) {
             if( source.attitude_to( *critter ) != Creature::Attitude::HOSTILE ) {
                 // no point in swinging a sword at a friendly!
                 continue;
             }
             npc_attack_rating effectiveness_at_point = evaluate_critter( source, target, critter );
             effectiveness_at_point -= time_penalty;
             effectiveness.push_back( effectiveness_at_point );
         }
     }
     return effectiveness;
 }
References npc::attitude_to(), base_time_penalty(), can_use(), creature_tracker::creature_at(), evaluate_critter(), get_creature_tracker(), Creature::HOSTILE, and targetable_points().
base_time_penalty()
int npc_attack_melee::base_time_penalty (const npc & source) const private
Definition at line 386 of file npc_attack.cpp.
 {
     return source.is_wielding( weapon ) ? 0 : npc_attack_constants::base_time_penalty;
 }
References npc_attack_constants::base_time_penalty, Character::is_wielding(), and weapon.
Referenced by all_evaluations(), and evaluate().
can_use()
bool npc_attack_melee::can_use (const npc & source) const private
Definition at line 380 of file npc_attack.cpp.
 {
     // can't attack with something you can't wield
     return source.is_wielding( weapon ) || source.can_wield( weapon ).success();
 }
References Character::can_wield(), Character::is_wielding(), ret_val_common::success(), and weapon.
Referenced by all_evaluations(), and evaluate().
evaluate()
npc_attack_rating npc_attack_melee::evaluate (const npc & source, const Creature * target) const override virtual
Parameters: source - the npc making the attack target - the desired target of the npc.
valued at 100%
Implements npc_attack.
Definition at line 332 of file npc_attack.cpp.
 {
     npc_attack_rating effectiveness( std::nullopt, source.pos() );
     if( !can_use( source ) ) {
         return effectiveness;
     }
     const int time_penalty = base_time_penalty( source );
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &targetable_point : targetable_points( source ) ) {
         if( Creature *critter = creatures.creature_at( targetable_point ) ) {
             if( source.attitude_to( *critter ) != Creature::Attitude::HOSTILE ) {
                 // no point in swinging a sword at a friendly!
                 continue;
             }
             npc_attack_rating effectiveness_at_point = evaluate_critter( source, target, critter );
             effectiveness_at_point -= time_penalty;
             if( effectiveness_at_point > effectiveness ) {
                 effectiveness = effectiveness_at_point;
             }
         }
     }
     return effectiveness;
 }
References npc::attitude_to(), base_time_penalty(), can_use(), creature_tracker::creature_at(), evaluate_critter(), get_creature_tracker(), Creature::HOSTILE, Creature::pos(), and targetable_points().
evaluate_critter()
npc_attack_rating npc_attack_melee::evaluate_critter (const npc & source, const Creature * target, Creature * critter) const private
Definition at line 391 of file npc_attack.cpp.
 {
     if( !critter ) {
         return npc_attack_rating{};
     }
     // TODO: Give bashing weapons a better
     // rating against armored targets
     double damage{ weapon.base_damage_melee().total_damage() };
     damage *= 100.0 / weapon.attack_time( source );
     const int reach_range{ weapon.reach_range( source ) };
     const int distance_to_me = clamp( rl_dist( source.pos(), critter->pos() ) - reach_range, 0, 10 );
     // Multiplier of 0.5f to 1.5f based on distance
     const float distance_multiplier = 1.5f - distance_to_me * 0.1f;
     double potential = damage * distance_multiplier;
     if( damage >= critter->get_hp() ) {
         potential *= npc_attack_constants::kill_modifier;
     }
     if( target && target->pos() == critter->pos() ) {
         potential *= npc_attack_constants::target_modifier;
     }
     return npc_attack_rating( static_cast<int>( std::round( potential ) ), critter->pos() );
 }
References item::attack_time(), item::base_damage_melee(), clamp(), Creature::get_hp(), npc_attack_constants::kill_modifier, Creature::pos(), item::reach_range(), rl_dist(), round(), npc_attack_constants::target_modifier, damage_instance::total_damage(), and weapon.
Referenced by all_evaluations(), and evaluate().
targetable_points()
tripoint_range< tripoint > npc_attack_melee::targetable_points (const npc & source) const private
Definition at line 327 of file npc_attack.cpp.
 {
     return get_map().points_in_radius( source.pos(), 8 );
 }
References get_map(), map::points_in_radius(), and Creature::pos().
Referenced by all_evaluations(), and evaluate().
use()
void npc_attack_melee::use (npc & source, const tripoint & location) const override virtual
Implements npc_attack.
Definition at line 232 of file npc_attack.cpp.
 {
     if( !source.is_wielding( weapon ) ) {
         if( !source.wield( weapon ) ) {
             debugmsg( "ERROR: npc tried to equip a weapon it couldn't wield" );
         }
         return;
     }
     Creature *critter = get_creature_tracker().creature_at( location );
     if( !critter ) {
         debugmsg( "ERROR: npc tried to attack null critter" );
         return;
     }
     int target_distance = rl_dist( source.pos(), location );
     if( !source.is_adjacent( critter, true ) ) {
         if( target_distance <= weapon.reach_range( source ) ) {
             add_msg_debug( debugmode::debug_filter::DF_NPC, "%s is attempting a reach attack",
                            source.disp_name() );
             // check for friendlies in the line of fire
             std::vector<tripoint> path = line_to( source.pos(), location );
             path.pop_back(); // Last point is the target
             bool can_attack = true;
             for( const tripoint &path_point : path ) {
                 Creature *inter = get_creature_tracker().creature_at( path_point );
                 if( inter != nullptr && source.attitude_to( *inter ) == Creature::Attitude::FRIENDLY ) {
                     add_msg_debug( debugmode::debug_filter::DF_NPC, "%s aborted a reach attack; ally in the way",
                                    source.disp_name() );
                     can_attack = false;
                     break;
                 }
             }
             if( can_attack ) {
                 source.reach_attack( location );
             } else if( can_move_melee( source ) ) {
                 source.avoid_friendly_fire();
             } else {
                 source.look_for_player( get_player_character() );
             }
         } else {
             source.update_path( location );
             if( source.path.size() > 1 ) {
                 bool clear_path = can_move_melee( source );
                 if( clear_path && source.mem_combat.formation_distance == -1 ) {
                     source.move_to_next();
                     add_msg_debug( debugmode::DF_NPC_MOVEAI,
                                    "<color_light_gray>%s has no nearby ranged allies.  Going for attack.</color>", source.name );
                 } else if( clear_path && source.mem_combat.formation_distance > target_distance ) {
                     source.move_to_next();
                     add_msg_debug( debugmode::DF_NPC_MOVEAI,
                                    "<color_light_gray>%s is at least %i away from ranged allies, enemy within %i.  Going for attack.</color>",
                                    source.name, source.mem_combat.formation_distance, target_distance );
                 } else if( clear_path &&
                            source.mem_combat.formation_distance > source.closest_enemy_to_friendly_distance() ) {
                     source.move_to_next();
                     //add_msg_debug( debugmode::DF_NPC_MOVEAI,
                     //               "<color_light_gray>%s is at least %i away from allies, enemy within %i of ally.  Going for attack.</color>",
                     //               source.name, source.mem_combat.formation_distance, source.closest_enemy_to_friendly_distance() );
                 } else if( source.mem_combat.formation_distance <= source.mem_combat.engagement_distance ) {
                     add_msg_debug( debugmode::DF_NPC_MOVEAI,
                                    "<color_light_gray>%s can't path to melee target, and is staying close to ranged allies.  Stay in place.</color>",
                                    source.name );
                     source.move_pause();
                 } else {
                     add_msg_debug( debugmode::DF_NPC_MOVEAI,
                                    "<color_light_gray>%s can't path to melee target, and is not staying close to ranged allies.  Get close to player.</color>",
                                    source.name );
                     source.look_for_player( get_player_character() );
                 }
             } else if( source.path.size() == 1 ) {
                 if( critter != nullptr ) {
                     if( source.can_use_offensive_cbm() ) {
                         source.activate_bionic_by_id( bio_hydraulics );
                     }
                     add_msg_debug( debugmode::debug_filter::DF_NPC, "%s is attempting a melee attack",
                                    source.disp_name() );
                     source.melee_attack( *critter, true );
                 }
             } else {
                 source.look_for_player( get_player_character() );
             }
         }
     } else if( source.mem_combat.formation_distance != -1 &&
                source.mem_combat.formation_distance <= target_distance &&
                rng( -10, 10 ) > source.personality.aggression ) {
         add_msg_debug( debugmode::DF_NPC_MOVEAI,
                        "<color_light_gray>%s decided to fall back to formation with allies.</color>", source.name );
         source.look_for_player( get_player_character() );
     } else {
         // may wish to add a break here to see if target is out of formation with allies, and consider running back.
         add_msg_debug( debugmode::debug_filter::DF_NPC, "%s is attempting a melee attack",
                        source.disp_name() );
         source.melee_attack( *critter, true );
     }
 }
References npc::activate_bionic_by_id(), add_msg_debug, npc_personality::aggression, npc::attitude_to(), npc::avoid_friendly_fire(), bio_hydraulics, can_move_melee(), npc::can_use_offensive_cbm(), npc::closest_enemy_to_friendly_distance(), creature_tracker::creature_at(), debugmsg, debugmode::DF_NPC, debugmode::DF_NPC_MOVEAI, Character::disp_name(), npc_combat_memory_cache::engagement_distance, npc_combat_memory_cache::formation_distance, Creature::FRIENDLY, get_creature_tracker(), get_player_character(), Creature::is_adjacent(), Character::is_wielding(), line_to(), location, npc::look_for_player(), Character::melee_attack(), npc::mem_combat, npc::move_pause(), npc::move_to_next(), Character::name, npc::path, npc::personality, Creature::pos(), Character::reach_attack(), item::reach_range(), rl_dist(), rng(), npc::update_path(), weapon, and npc::wield().
Member Data Documentation
weapon
item& npc_attack_melee::weapon private
Definition at line 81 of file npc_attack.h.
Referenced by base_time_penalty(), can_use(), evaluate_critter(), and use().
The documentation for this class was generated from the following files:
src/npc_attack.h
src/npc_attack.cpp