Cataclysm DDA: reload_activity_actor Class Reference
reload_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
reload_activity_actor (item::reload_option &&opt, int extra_moves=0)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &act, Character &) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
reload_activity_actor ()=default
bool can_reload () const
Static Private Member Functions
static void make_reload_sound (Character &who, item &reloadable)
Private Attributes
int moves_total = 0
int quantity = 0
item_location target_loc
item_location ammo_loc
Detailed Description
Definition at line 1155 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
reload_activity_actor() [1/2]
reload_activity_actor::reload_activity_actor (item::reload_option && opt, int extra_moves = 0) explicit
Definition at line 4738 of file activity_actor.cpp.
 {
     moves_total = opt.moves() + extra_moves;
     quantity = opt.qty();
     target_loc = std::move( opt.target );
     ammo_loc = std::move( opt.ammo );
 }
References ammo_loc, moves_total, quantity, and target_loc.
reload_activity_actor() [2/2]
reload_activity_actor::reload_activity_actor () explicit private default
Member Function Documentation
can_reload()
bool reload_activity_actor::can_reload () const private
Definition at line 4746 of file activity_actor.cpp.
 {
     if( quantity <= 0 ) {
         debugmsg( "invalid arguments to ACT_RELOAD" );
         return false;
     }
     if( !target_loc ) {
         debugmsg( "reload target is null, failed to reload" );
         return false;
     }
     if( !ammo_loc ) {
         debugmsg( "ammo target is null, failed to reload" );
         return false;
     }
     return true;
 }
References ammo_loc, debugmsg, quantity, and target_loc.
Referenced by finish().
canceled()
void reload_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 4875 of file activity_actor.cpp.
 {
     act.moves_total = 0;
     act.moves_left = 0;
 }
References act.
clone()
std::unique_ptr<activity_actor> reload_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1169 of file activity_actor_definitions.h.
{
             return std::make_unique<reload_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > reload_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 4893 of file activity_actor.cpp.
 {
     reload_activity_actor actor;
     JsonObject data = jsin.get_object();
     data.read( "moves_total", actor.moves_total );
     data.read( "qty", actor.quantity );
     data.read( "target_loc", actor.target_loc );
     data.read( "ammo_loc", actor.ammo_loc );
     return actor.clone();
 }
References ammo_loc, clone(), JsonValue::get_object(), moves_total, quantity, JsonObject::read(), and target_loc.
do_turn()
void reload_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1165 of file activity_actor_definitions.h.
 {}
finish()
void reload_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 4782 of file activity_actor.cpp.
 {
     act.set_to_null();
     if( !can_reload() ) {
         return;
     }
     item &reloadable = *target_loc;
     item &ammo = *ammo_loc;
     const std::string reloadable_name = reloadable.tname();
     // cache check results because reloading deletes the ammo item
     const std::string ammo_name = ammo.tname();
     const bool ammo_is_filthy = ammo.is_filthy();
     const bool ammo_uses_speedloader = ammo.has_flag( flag_SPEEDLOADER );
     const bool ammo_uses_speedloader_clip = ammo.has_flag( flag_SPEEDLOADER_CLIP );
     if( !reloadable.reload( who, std::move( ammo_loc ), quantity ) ) {
         add_msg( m_info, _( "Can't reload the %s." ), reloadable_name );
         return;
     }
     if( ammo_is_filthy ) {
         reloadable.set_flag( flag_FILTHY );
     }
     if( reloadable.get_var( "dirt", 0 ) > 7800 ) {
         add_msg( m_neutral, _( "You manage to loosen some debris and make your %s somewhat operational." ),
                  reloadable_name );
         reloadable.set_var( "dirt", ( reloadable.get_var( "dirt", 0 ) - rng( 790, 2750 ) ) );
     }
     if( reloadable.is_gun() ) {
         if( reloadable.has_flag( flag_RELOAD_ONE ) && !ammo_uses_speedloader &&
             !ammo_uses_speedloader_clip ) {
             add_msg( m_neutral, _( "You insert %dx %s into the %s." ), quantity, ammo_name, reloadable_name );
         }
         make_reload_sound( who, reloadable );
     } else if( reloadable.is_watertight_container() ) {
         add_msg( m_neutral, _( "You refill the %s." ), reloadable_name );
     } else {
         add_msg( m_neutral, _( "You reload the %1$s with %2$s." ), reloadable_name, ammo_name );
     }
     who.recoil = MAX_RECOIL;
     item_location loc = target_loc;
     // Reload may have caused the item to increase in size more than the pocket/location can contain.
     // We want to avoid this because items will be deleted on a save/load.
     if( loc.check_parent_capacity_recursive() ) {
         return;
     }
     // Attempt to put item in another pocket before prompting
     if( who.try_add( reloadable, nullptr, nullptr, false ) != item_location::nowhere ) {
         // try_add copied the old item, so remove it now.
         loc.remove_item();
         return;
     }
     // Build prompt
     uilist reload_query;
     const bool wield_check = who.can_wield( reloadable ).success();
     reload_query.text = string_format( _( "The %s no longer fits in your inventory" ),
                                        reloadable_name );
     if( who.has_wield_conflicts( reloadable ) ) {
         reload_query.addentry( 1, wield_check, 'w',
                                _( "Dispose of %s and wield %s" ), who.get_wielded_item()->display_name(),
                                reloadable_name );
     } else {
         reload_query.addentry( 1, wield_check, 'w', _( "Wield %s" ), reloadable_name );
     }
     reload_query.addentry( 2, true, 'd', _( "Drop %s" ), reloadable_name );
     reload_query.query();
     switch( reload_query.ret ) {
         case 1:
             // This case is only reachable if wield_check is true
             who.wield( reloadable );
             add_msg( m_neutral, _( "The %s no longer fits in your inventory so you wield it instead." ),
                      reloadable_name );
             break;
         case 2:
         default:
             // In player inventory and player is wielding something.
             loc.carrier()->add_msg_if_player( m_neutral,
                                               _( "The %s no longer fits in your inventory so you drop it instead." ),
                                               reloadable_name );
             get_map().add_item_or_charges( loc.position(), reloadable );
             loc.remove_item();
             break;
     }
 }
References _, act, map::add_item_or_charges(), add_msg(), Character::add_msg_if_player(), uilist::addentry(), ammo_loc, can_reload(), Character::can_wield(), item_location::carrier(), item_location::check_parent_capacity_recursive(), item::display_name(), flag_FILTHY, flag_RELOAD_ONE, flag_SPEEDLOADER, flag_SPEEDLOADER_CLIP, get_map(), item::get_var(), Character::get_wielded_item(), item::has_flag(), Character::has_wield_conflicts(), item::is_filthy(), item::is_gun(), item::is_watertight_container(), m_info, m_neutral, make_reload_sound(), MAX_RECOIL, item_location::nowhere, item_location::position(), quantity, uilist::query(), Character::recoil, item::reload(), item_location::remove_item(), uilist::ret, rng(), item::set_flag(), item::set_var(), string_format(), ret_val_common::success(), target_loc, uilist::text, item::tname(), Character::try_add(), and Character::wield().
get_type()
activity_id reload_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1160 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_RELOAD" );
         }
References activity_id.
make_reload_sound()
void reload_activity_actor::make_reload_sound (Character & who, item & reloadable) static private
Definition at line 4772 of file activity_actor.cpp.
 {
     if( reloadable.type->gun->reload_noise_volume > 0 ) {
         sfx::play_variant_sound( "reload", reloadable.typeId().str(),
                                  sfx::get_heard_volume( who.pos() ) );
         sounds::ambient_sound( who.pos(), reloadable.type->gun->reload_noise_volume,
                                sounds::sound_t::activity, reloadable.type->gun->reload_noise.translated() );
     }
 }
References sounds::activity, sounds::ambient_sound(), sfx::get_heard_volume(), itype::gun, sfx::play_variant_sound(), Creature::pos(), string_id< T >::str(), item::type, and item::typeId().
Referenced by finish().
serialize()
void reload_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 4881 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves_total", moves_total );
     jsout.member( "qty", quantity );
     jsout.member( "target_loc", target_loc );
     jsout.member( "ammo_loc", ammo_loc );
     jsout.end_object();
 }
References ammo_loc, JsonOut::end_object(), JsonOut::member(), moves_total, quantity, JsonOut::start_object(), and target_loc.
start()
void reload_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 4766 of file activity_actor.cpp.
 {
     act.moves_total = moves_total;
     act.moves_left = moves_total;
 }
References act, and moves_total.
Member Data Documentation
ammo_loc
item_location reload_activity_actor::ammo_loc private
Definition at line 1181 of file activity_actor_definitions.h.
Referenced by can_reload(), deserialize(), finish(), reload_activity_actor(), and serialize().
moves_total
int reload_activity_actor::moves_total = 0 private
Definition at line 1178 of file activity_actor_definitions.h.
Referenced by deserialize(), reload_activity_actor(), serialize(), and start().
quantity
int reload_activity_actor::quantity = 0 private
Definition at line 1179 of file activity_actor_definitions.h.
Referenced by can_reload(), deserialize(), finish(), reload_activity_actor(), and serialize().
target_loc
item_location reload_activity_actor::target_loc private
Definition at line 1180 of file activity_actor_definitions.h.
Referenced by can_reload(), deserialize(), finish(), reload_activity_actor(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp