Cataclysm DDA: hotwire_car_activity_actor Class Reference
hotwire_car_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
hotwire_car_activity_actor (int moves_total, const tripoint &target)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
Private Attributes
int moves_total
tripoint target
Position of first vehicle part; used to identify the vehicle TODO: find something more reliable (to cover cases when vehicle is moved/damaged)
Detailed Description
Definition at line 317 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
hotwire_car_activity_actor()
hotwire_car_activity_actor::hotwire_car_activity_actor (int moves_total, const tripoint & target) inline
Definition at line 334 of file activity_actor_definitions.h.
                                                                              : moves_total( moves_total ),
             target( target ) {}
Member Function Documentation
can_resume_with_internal()
bool hotwire_car_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override private virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 328 of file activity_actor_definitions.h.
{
             const hotwire_car_activity_actor &a = static_cast<const hotwire_car_activity_actor &>( other );
             return target == a.target && moves_total == a.moves_total;
         }
References a, moves_total, other, and target.
clone()
std::unique_ptr<activity_actor> hotwire_car_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 345 of file activity_actor_definitions.h.
{
             return std::make_unique<hotwire_car_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > hotwire_car_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 1243 of file activity_actor.cpp.
 {
     hotwire_car_activity_actor actor( 0, tripoint_zero );
     JsonObject data = jsin.get_object();
     data.read( "target", actor.target );
     data.read( "moves_total", actor.moves_total );
     return actor.clone();
 }
References clone(), JsonValue::get_object(), moves_total, JsonObject::read(), target, and tripoint_zero.
do_turn()
void hotwire_car_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1184 of file activity_actor.cpp.
 {
     map &here = get_map();
     if( calendar::once_every( 1_minutes ) ) {
         bool lost = !here.veh_at( here.getlocal( target ) ).has_value();
         if( lost ) {
             act.set_to_null();
             debugmsg( "Lost ACT_HOTWIRE_CAR target vehicle" );
         }
         if( calendar::once_every( 5_minutes ) ) {
             who.practice( skill_mechanics, 1, 2, true );
         }
     }
 }
References act, debugmsg, get_map(), map::getlocal(), calendar::once_every(), Character::practice(), skill_mechanics, target, and map::veh_at().
finish()
void hotwire_car_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1199 of file activity_actor.cpp.
 {
     act.set_to_null();
     map &here = get_map();
     const optional_vpart_position vp = here.veh_at( here.getlocal( target ) );
     if( !vp ) {
         debugmsg( "Lost ACT_HOTWIRE_CAR target vehicle" );
         return;
     }
     vehicle &veh = vp->vehicle();
     int skill = round( who.get_average_skill_level( skill_mechanics ) );
     if( skill > rng( 1, 6 ) ) {
         // Success
         who.add_msg_if_player( _( "You found the wire that starts the engine." ) );
         veh.is_locked = false;
     } else if( skill > rng( 0, 4 ) ) {
         // Soft fail
         who.add_msg_if_player( _( "You found a wire that looks like the right one." ) );
         veh.is_alarm_on = veh.has_security_working();
         veh.is_locked = false;
     } else if( !veh.is_alarm_on ) {
         // Hard fail
         who.add_msg_if_player( _( "The red wire always starts the engine, doesn't it?" ) );
         veh.is_alarm_on = veh.has_security_working();
     } else {
         // Already failed
         who.add_msg_if_player(
             _( "By process of elimination, you found the wire that starts the engine." ) );
         veh.is_locked = false;
     }
 }
References _, act, Character::add_msg_if_player(), debugmsg, Character::get_average_skill_level(), get_map(), map::getlocal(), vehicle::has_security_working(), vehicle::is_alarm_on, vehicle::is_locked, rng(), round(), skill_mechanics, target, and map::veh_at().
get_type()
activity_id hotwire_car_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 337 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_HOTWIRE_CAR" );
         }
References activity_id.
serialize()
void hotwire_car_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 1233 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target", target );
     jsout.member( "moves_total", moves_total );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves_total, JsonOut::start_object(), and target.
start()
void hotwire_car_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1178 of file activity_actor.cpp.
 {
     act.moves_total = moves_total;
     act.moves_left = moves_total;
 }
References act, and moves_total.
Member Data Documentation
moves_total
int hotwire_car_activity_actor::moves_total private
Definition at line 320 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), serialize(), and start().
target
tripoint hotwire_car_activity_actor::target private
Position of first vehicle part; used to identify the vehicle TODO: find something more reliable (to cover cases when vehicle is moved/damaged)
Definition at line 326 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), do_turn(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp