Cataclysm DDA: spellbook_callback Class Reference
spellbook_callback Class Reference
#include <magic.h>
Public Member Functions
void add_spell (const spell_id &sp)
void refresh (uilist *menu) override
Public Member Functions inherited from uilist_callback
virtual void select (uilist *)
After a new item is selected, call this once.
virtual bool key (const input_context &, const input_event &, int, uilist *)
virtual ~uilist_callback ()=default
Private Attributes
std::vector< spell_type > spells
Detailed Description
Definition at line 859 of file magic.h.
Member Function Documentation
add_spell()
void spellbook_callback::add_spell (const spell_id & sp)
Definition at line 2841 of file magic.cpp.
 {
     spells.emplace_back( sp.obj() );
 }
References string_id< T >::obj(), and spells.
Referenced by learn_spell_actor::use().
refresh()
void spellbook_callback::refresh (uilist * menu) override virtual
Reimplemented from uilist_callback.
Definition at line 2968 of file magic.cpp.
 {
     mvwputch( menu->window, point( menu->pad_left, 0 ), c_magenta, LINE_OXXX );
     mvwputch( menu->window, point( menu->pad_left, menu->w_height - 1 ), c_magenta, LINE_XXOX );
     for( int i = 1; i < menu->w_height - 1; i++ ) {
         mvwputch( menu->window, point( menu->pad_left, i ), c_magenta, LINE_XOXO );
     }
     if( menu->selected >= 0 && static_cast<size_t>( menu->selected ) < spells.size() ) {
         draw_spellbook_info( spells[menu->selected], menu );
     }
     wnoutrefresh( menu->window );
 }
References c_magenta, draw_spellbook_info(), LINE_OXXX, LINE_XOXO, LINE_XXOX, mvwputch(), uilist::pad_left, uilist::selected, spells, uilist::w_height, uilist::window, and catacurses::wnoutrefresh().
Member Data Documentation
spells
std::vector<spell_type> spellbook_callback::spells private
Definition at line 862 of file magic.h.
Referenced by add_spell(), and refresh().
The documentation for this class was generated from the following files:
src/magic.h
src/magic.cpp