Cataclysm DDA: body_part_set Class Reference
body_part_set Class Reference
#include <body_part_set.h>
Public Member Functions
body_part_set ()=default
body_part_set (std::initializer_list< bodypart_str_id > bps)
body_part_set unify_set (const body_part_set &rhs)
body_part_set intersect_set (const body_part_set &rhs)
body_part_set make_intersection (const body_part_set &rhs) const
body_part_set substract_set (const body_part_set &rhs)
void fill (const std::vector< bodypart_id > &bps)
bool test (const bodypart_str_id &bp) const
void set (const bodypart_str_id &bp)
void reset (const bodypart_str_id &bp)
bool any () const
bool none () const
size_t count () const
cata::flat_set< bodypart_str_id >::iterator begin () const
cata::flat_set< bodypart_str_id >::iterator end () const
void clear ()
void serialize (JsonOut &s) const
void deserialize (const JsonValue &s)
Private Member Functions
body_part_set (const cata::flat_set< bodypart_str_id > &other)
Private Attributes
cata::flat_set< bodypart_str_id > parts
Detailed Description
Definition at line 11 of file body_part_set.h.
Constructor & Destructor Documentation
body_part_set() [1/3]
body_part_set::body_part_set (const cata::flat_set< bodypart_str_id > & other) inline explicit private
Definition at line 17 of file body_part_set.h.
 : parts( other ) {}
body_part_set() [2/3]
body_part_set::body_part_set () default
body_part_set() [3/3]
body_part_set::body_part_set (std::initializer_list< bodypart_str_id > bps) inline
Definition at line 21 of file body_part_set.h.
{
             for( const bodypart_str_id &bp : bps ) {
                 set( bp );
             }
         }
References bp, and set().
Member Function Documentation
any()
bool body_part_set::any () const inline
Definition at line 43 of file body_part_set.h.
{
             return !parts.empty();
         }
References parts.
Referenced by item::armor_info(), item::covers_overlaps(), player_morale::on_worn_item_washed(), and player_morale::set_worn().
begin()
cata::flat_set<bodypart_str_id>::iterator body_part_set::begin () const inline
Definition at line 53 of file body_part_set.h.
{
             return parts.begin();
         }
References parts.
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_properties(), anonymous_namespace{armor_layers.cpp}::clothing_protection(), and outfit::is_worn_item_visible().
clear()
void body_part_set::clear () inline
Definition at line 61 of file body_part_set.h.
                      {
             parts.clear();
         }
References parts.
Referenced by intersect_set().
count()
size_t body_part_set::count () const inline
Definition at line 49 of file body_part_set.h.
{
             return parts.size();
         }
References parts.
Referenced by item::damage_armor_durability().
deserialize()
void body_part_set::deserialize (const JsonValue & s)
Definition at line 874 of file bodypart.cpp.
 {
     s.read( parts );
 }
References parts, and JsonValue::read().
end()
cata::flat_set<bodypart_str_id>::iterator body_part_set::end () const inline
Definition at line 57 of file body_part_set.h.
{
             return parts.end();
         }
References parts.
Referenced by outfit::is_worn_item_visible().
fill()
void body_part_set::fill (const std::vector< bodypart_id > & bps)
Definition at line 862 of file bodypart.cpp.
 {
     for( const bodypart_id &bp : bps ) {
         parts.insert( bp.id() );
     }
 }
References bp, int_id< T >::id(), and parts.
Referenced by Creature::get_drenching_body_parts().
intersect_set()
body_part_set body_part_set::intersect_set (const body_part_set & rhs)
Definition at line 832 of file bodypart.cpp.
 {
     body_part_set temp;
     for( const bodypart_str_id &j : rhs ) {
         if( test( j ) ) {
             temp.set( j );
         }
     }
     clear();
     unify_set( temp );
     return *this;
 }
References clear(), temp, test(), and unify_set().
Referenced by item::covers_overlaps(), and make_intersection().
make_intersection()
body_part_set body_part_set::make_intersection (const body_part_set & rhs) const
Definition at line 855 of file bodypart.cpp.
 {
     body_part_set new_intersection;
     new_intersection.unify_set( *this );
     return new_intersection.intersect_set( rhs );
 }
References intersect_set(), and unify_set().
none()
bool body_part_set::none () const inline
Definition at line 46 of file body_part_set.h.
{
             return parts.empty();
         }
References parts.
Referenced by outfit::covered_with_flag(), Character::covered_with_flag(), outfit::power_armor_conflicts(), and spell_type::serialize().
reset()
void body_part_set::reset (const bodypart_str_id & bp) inline
Definition at line 40 of file body_part_set.h.
{
             parts.erase( bp );
         }
References bp, and parts.
Referenced by enchantment::modify_bodyparts(), and substract_set().
serialize()
void body_part_set::serialize (JsonOut & s) const
Definition at line 869 of file bodypart.cpp.
 {
     s.write( parts );
 }
References parts, and JsonOut::write().
set()
void body_part_set::set (const bodypart_str_id & bp) inline
Definition at line 37 of file body_part_set.h.
{
             parts.insert( bp );
         }
References bp, and parts.
Referenced by assign_coverage_from_json(), body_part_set(), Item_factory::finalize_post_armor(), item::get_covered_body_parts(), enchantment::modify_bodyparts(), Character::recalculate_bodyparts(), and unify_set().
substract_set()
body_part_set body_part_set::substract_set (const body_part_set & rhs)
Definition at line 845 of file bodypart.cpp.
 {
     for( const bodypart_str_id &j : rhs ) {
         if( test( j ) ) {
             reset( j );
         }
     }
     return *this;
 }
References reset(), and test().
Referenced by outfit::covered_with_flag(), and outfit::exclusive_flag_coverage().
test()
bool body_part_set::test (const bodypart_str_id & bp) const inline
Definition at line 34 of file body_part_set.h.
{
             return parts.count( bp ) > 0;
         }
References bp, and parts.
Referenced by outfit::adjust_worn(), Character::apply_wetness_morale(), outfit::bodypart_exposure(), spell::bp_is_affected(), Character::drench(), intersect_set(), layer_item(), Character::mutation_attacks(), player_morale::on_worn_item_washed(), Character::recalculate_bodyparts(), player_morale::set_worn(), substract_set(), Character::swim_speed(), and unify_set().
unify_set()
body_part_set body_part_set::unify_set (const body_part_set & rhs)
Definition at line 822 of file bodypart.cpp.
 {
     for( const bodypart_str_id &i : rhs ) {
         if( !test( i ) ) {
             set( i );
         }
     }
     return *this;
 }
References set(), and test().
Referenced by item::covers_overlaps(), intersect_set(), and make_intersection().
Member Data Documentation
parts
cata::flat_set<bodypart_str_id> body_part_set::parts private
Definition at line 15 of file body_part_set.h.
Referenced by any(), begin(), clear(), count(), deserialize(), end(), fill(), none(), reset(), serialize(), set(), and test().
The documentation for this class was generated from the following files:
src/body_part_set.h
src/bodypart.cpp