Cataclysm DDA: base_watcher Class Reference
base_watcher Class Reference
#include <stats_tracker.h>
Public Member Functions
base_watcher ()=default
base_watcher (const base_watcher &)=delete
base_watcher & operator= (const base_watcher &)=delete
Protected Member Functions
virtual ~base_watcher ()
Private Member Functions
void on_subscribe (stats_tracker *)
void on_unsubscribe (stats_tracker *)
Private Attributes
stats_tracker * subscribed_to = nullptr
Friends
class stats_tracker
Detailed Description
Definition at line 107 of file stats_tracker.h.
Constructor & Destructor Documentation
base_watcher() [1/2]
base_watcher::base_watcher () default
base_watcher() [2/2]
base_watcher::base_watcher (const base_watcher &) delete
~base_watcher()
base_watcher::~base_watcher () protected virtual
Definition at line 196 of file stats_tracker.cpp.
 {
     if( subscribed_to ) {
         subscribed_to->unwatch( this );
     }
 }
References subscribed_to, and stats_tracker::unwatch().
Member Function Documentation
on_subscribe()
void base_watcher::on_subscribe (stats_tracker * s) private
Definition at line 203 of file stats_tracker.cpp.
 {
     if( subscribed_to ) {
         debugmsg( "Subscribing a single base_watcher multiple times is not supported" );
     }
     subscribed_to = s;
 }
References debugmsg, and subscribed_to.
Referenced by stats_tracker::add_watcher().
on_unsubscribe()
void base_watcher::on_unsubscribe (stats_tracker * s) private
Definition at line 211 of file stats_tracker.cpp.
 {
     if( subscribed_to != s ) {
         debugmsg( "Unexpected notification of unsubscription from wrong stats_tracker" );
     } else {
         subscribed_to = nullptr;
     }
 }
References debugmsg, and subscribed_to.
Referenced by stats_tracker::unwatch_all().
operator=()
base_watcher& base_watcher::operator= (const base_watcher &) delete
Friends And Related Function Documentation
stats_tracker
friend class stats_tracker friend
Definition at line 116 of file stats_tracker.h.
Member Data Documentation
subscribed_to
stats_tracker* base_watcher::subscribed_to = nullptr private
Definition at line 119 of file stats_tracker.h.
Referenced by on_subscribe(), on_unsubscribe(), and ~base_watcher().
The documentation for this class was generated from the following files:
src/stats_tracker.h
src/stats_tracker.cpp