Cataclysm DDA: vpart_position Class Reference
vpart_position Class Reference
Reference to a position (a point) of the vehicle.
#include <vpart_position.h>
Public Member Functions
vpart_position (::vehicle &v, const size_t part)
::vehicle & vehicle () const
size_t part_index () const
bool is_inside () const
void set_label (const std::string &text) const
Sets the label at this part of the vehicle.
std::optional< std::string > get_label () const
std::optional< vpart_reference > cargo () const
std::optional< vpart_reference > part_with_feature (const std::string &f, bool unbroken) const
std::optional< vpart_reference > part_with_feature (vpart_bitflags f, bool unbroken) const
std::optional< vpart_reference > avail_part_with_feature (const std::string &f) const
std::optional< vpart_reference > avail_part_with_feature (vpart_bitflags f) const
std::optional< vpart_reference > obstacle_at_part () const
Returns the obstacle that exists at this point of the vehicle (if any).
std::optional< vpart_reference > part_displayed () const
Returns the part displayed at this point of the vehicle.
std::optional< vpart_reference > part_with_tool (const itype_id &tool_type) const
std::map< item, int > get_tools () const
void form_inventory (inventory &inv) const
tripoint_bub_ms pos_bub () const
Returns the position of this part in the coordinates system that game::m uses.
tripoint pos () const
point mount () const
Returns the mount point: the point in the vehicles own coordinate system.
bool operator< (const vpart_position &other) const
Private Attributes
std::reference_wrapper<::vehicle > vehicle_
size_t part_index_
Detailed Description
Reference to a position (a point) of the vehicle.
It does not refer to a specific vehicle part, but to a mount point of a vehicle that contains one or more vehicle parts.
It's supposed to be the basic vehicle interface for the map. Another class shall be used to get a reference to a specific part of the vehicle.
Note that it must be created with a valid vehicle reference and a valid part index. An instance can become invalid when the referenced vehicle is changed (parts added / removed or whole vehicle removed). There is no way to detect this (it behaves like C++ references).
Definition at line 43 of file vpart_position.h.
Constructor & Destructor Documentation
vpart_position()
vpart_position::vpart_position (::vehicle & v, const size_t part) inline
Definition at line 50 of file vpart_position.h.
 : vehicle_( v ), part_index_( part ) { }
Member Function Documentation
avail_part_with_feature() [1/2]
std::optional< vpart_reference > vpart_position::avail_part_with_feature (const std::string & f) const
See also
vehicle::part_with_feature
Definition at line 2685 of file vehicle.cpp.
 {
     const int i = vehicle().avail_part_with_feature( mount(), f );
     return i >= 0 ? vpart_reference( vehicle(), i ) : std::optional<vpart_reference>();
 }
References vehicle::avail_part_with_feature(), mount(), and vehicle().
Referenced by vehicle::build_interact_menu().
avail_part_with_feature() [2/2]
std::optional< vpart_reference > vpart_position::avail_part_with_feature (vpart_bitflags f) const
See also
vehicle::part_with_feature
Definition at line 2692 of file vehicle.cpp.
 {
     const int i = vehicle().avail_part_with_feature( part_index(), f );
     return i >= 0 ? vpart_reference( vehicle(), i ) : std::optional<vpart_reference>();
 }
References vehicle::avail_part_with_feature(), part_index(), and vehicle().
cargo()
std::optional< vpart_reference > vpart_position::cargo () const
Definition at line 2660 of file vehicle.cpp.
 {
     return part_with_feature( VPFLAG_CARGO, true );
 }
References part_with_feature(), and VPFLAG_CARGO.
Referenced by item_location::impl::item_on_vehicle::describe(), and vehicle::use_charges().
form_inventory()
void vpart_position::form_inventory (inventory & inv) const
Definition at line 1696 of file vehicle_use.cpp.
 {
     if( const std::optional<vpart_reference> vp_cargo = part_with_feature( VPFLAG_CARGO, true ) ) {
         for( const item &it : vp_cargo->items() ) {
             if( it.empty_container() && it.is_watertight_container() ) {
                 const int count = it.count_by_charges() ? it.charges : 1;
                 inv.update_liq_container_count( it.typeId(), count );
             }
             inv.add_item( it );
         }
     }
     // HACK: water_faucet pseudo tool gives access to liquids in tanks
     const std::optional<vpart_reference> vp_faucet = part_with_tool( itype_water_faucet );
     if( vp_faucet && inv.provide_pseudo_item( itype_water_faucet ) != nullptr ) {
         for( const item *it : vehicle().fuel_items_left() ) {
             if( it->made_of( phase_id::LIQUID ) ) {
                 item fuel( *it );
                 inv.add_item( fuel );
             }
         }
     }
     for( const auto&[tool_item, discard_] : get_tools() ) {
         inv.provide_pseudo_item( tool_item );
     }
 }
References inventory::add_item(), get_tools(), itype_water_faucet, LIQUID, part_with_feature(), part_with_tool(), inventory::provide_pseudo_item(), inventory::update_liq_container_count(), vehicle(), and VPFLAG_CARGO.
get_label()
std::optional< std::string > vpart_position::get_label () const
Returns
The label at this part of the vehicle, if there is any.
Definition at line 2902 of file vehicle.cpp.
 {
     const auto it = vehicle().labels.find( label( mount() ) );
     if( it == vehicle().labels.end() ) {
         return std::nullopt;
     }
     if( it->text.empty() ) {
         // legacy support TODO: change labels into a map and keep track of deleted labels
         return std::nullopt;
     }
     return it->text;
 }
References anonymous_namespace{item_tname.cpp}::label(), vehicle::labels, mount(), and vehicle().
Referenced by item_location::impl::item_on_vehicle::describe(), veh_interact::do_relabel(), and vehicle::print_part_list().
get_tools()
std::map< item, int > vpart_position::get_tools () const
Definition at line 2645 of file vehicle.cpp.
 {
     std::map<item, int> res;
     for( const int part_idx : this->vehicle().parts_at_relative( this->mount(), false ) ) {
         const vehicle_part &vp = this->vehicle().part( part_idx );
         if( vp.is_broken() ) {
             continue;
         }
         for( const auto &[tool_item, hk] : this->vehicle().prepare_tools( vp ) ) {
             res[tool_item] = hk;
         }
     }
     return res;
 }
References vehicle_part::is_broken(), mount(), vehicle::part(), and vehicle().
Referenced by vehicle::build_interact_menu(), and form_inventory().
is_inside()
bool vpart_position::is_inside () const
Definition at line 7125 of file vehicle.cpp.
 {
     // TODO: this is a bit of a hack as refresh_insides has side effects
     // this should be called elsewhere and not in a function that intends to just query
     // it's also a no-op if the insides are up to date.
     vehicle().refresh_insides();
     return vehicle().part( part_index() ).inside;
 }
References vehicle_part::inside, vehicle::part(), part_index(), vehicle::refresh_insides(), and vehicle().
Referenced by vehicle_caching_internal(), and vehicle::would_repair_prevent_flyable().
mount()
point vpart_position::mount () const
Returns the mount point: the point in the vehicles own coordinate system.
This system is independent of movement / rotation.
Definition at line 7808 of file vehicle.cpp.
 {
     return vehicle().part( part_index() ).mount;
 }
References vehicle_part::mount, vehicle::part(), part_index(), and vehicle().
Referenced by avail_part_with_feature(), vehicle::build_interact_menu(), vehicle::calc_mass_center(), map::draw_from_above(), get_label(), get_tools(), part_displayed(), part_with_feature(), part_with_tool(), map::process_items_in_vehicle(), and set_label().
obstacle_at_part()
std::optional< vpart_reference > vpart_position::obstacle_at_part () const
Returns the obstacle that exists at this point of the vehicle (if any).
Open doors don't count as obstacles, but closed one do. Broken parts are also never obstacles.
Definition at line 2604 of file vehicle.cpp.
 {
     std::optional<vpart_reference> part = part_with_feature( VPFLAG_OBSTACLE, true );
     if( !part ) {
         return std::nullopt; // No obstacle here
     }
     if( part->has_feature( VPFLAG_OPENABLE ) && part->part().open ) {
         return std::nullopt; // Open door here
     }
     return part;
 }
References part_with_feature(), VPFLAG_OBSTACLE, and VPFLAG_OPENABLE.
Referenced by map::draw_from_above(), map::move_cost_internal(), and map::route().
operator<()
bool vpart_position::operator< (const vpart_position & other) const
Definition at line 7801 of file vehicle.cpp.
 {
     const ::vehicle *const v1 = &vehicle();
     const ::vehicle *const v2 = &other.vehicle();
     return std::make_pair( v1, part_index_ ) < std::make_pair( v2, other.part_index_ );
 }
References other, part_index_, and vehicle().
part_displayed()
std::optional< vpart_reference > vpart_position::part_displayed () const
Returns the part displayed at this point of the vehicle.
Definition at line 2618 of file vehicle.cpp.
 {
     int part_id = vehicle().part_displayed_at( mount(), true );
     if( part_id == -1 ) {
         return std::nullopt;
     }
     return vpart_reference( vehicle(), part_id );
 }
References mount(), vehicle::part_displayed_at(), and vehicle().
part_index()
size_t vpart_position::part_index () const inline
Definition at line 56 of file vpart_position.h.
{
             return part_index_;
         }
References part_index_.
Referenced by avail_part_with_feature(), vehicle::build_interact_menu(), vehicle::calc_mass_center(), vpart_reference::get_passenger(), is_inside(), mount(), vpart_reference::part(), part_with_feature(), pos(), serialize_liquid_target(), and vehicle_caching_internal().
part_with_feature() [1/2]
std::optional< vpart_reference > vpart_position::part_with_feature (const std::string & f, bool unbroken) const
See also
vehicle::part_with_feature
Definition at line 2665 of file vehicle.cpp.
 {
     const int i = vehicle().part_with_feature( mount(), f, unbroken );
     if( i < 0 ) {
         return std::nullopt;
     }
     return vpart_reference( vehicle(), i );
 }
References mount(), vehicle::part_with_feature(), and vehicle().
Referenced by cargo(), form_inventory(), map::move_cost_internal(), and obstacle_at_part().
part_with_feature() [2/2]
std::optional< vpart_reference > vpart_position::part_with_feature (vpart_bitflags f, bool unbroken) const
See also
vehicle::part_with_feature
Definition at line 2675 of file vehicle.cpp.
 {
     const int i = vehicle().part_with_feature( part_index(), f, unbroken );
     if( i < 0 ) {
         return std::nullopt;
     }
     return vpart_reference( vehicle(), i );
 }
References part_index(), vehicle::part_with_feature(), and vehicle().
part_with_tool()
std::optional< vpart_reference > vpart_position::part_with_tool (const itype_id & tool_type) const
Definition at line 2627 of file vehicle.cpp.
 {
     for( const int idx : vehicle().parts_at_relative( mount(), false ) ) {
         const vpart_reference vp( vehicle(), idx );
         if( vp.part().is_broken() ) {
             continue;
         }
         const std::map<item, int> tools = vehicle().prepare_tools( vp.part() );
         if( std::find_if( tools.begin(), tools.end(),
         [&tool_type]( const std::pair<const item, int> &pair ) {
         return pair.first.typeId() == tool_type;
         } ) != tools.end() ) {
             return vp;
         }
     }
     return std::optional<vpart_reference>();
 }
References vehicle_part::is_broken(), mount(), vpart_reference::part(), vehicle::prepare_tools(), and vehicle().
Referenced by form_inventory(), vehicle::update_time(), and vehicle::use_charges().
pos()
tripoint vpart_position::pos () const
Definition at line 7817 of file vehicle.cpp.
 {
     return vehicle().global_part_pos3( part_index() );
 }
References vehicle::global_part_pos3(), part_index(), and vehicle().
Referenced by vehicle::build_interact_menu(), item_location::impl::item_on_vehicle::describe(), pos_bub(), and vehicle::use_charges().
pos_bub()
tripoint_bub_ms vpart_position::pos_bub () const
Returns the position of this part in the coordinates system that game::m uses.
Postcondition (if the vehicle cache of the map is correct and if there are un-removed parts at this positions): g->m.veh_at(this->pos()) (there is a vehicle there) g->m.veh_at(this->pos())->vehicle() == this->vehicle() (it's this one)
Definition at line 7813 of file vehicle.cpp.
 {
     return tripoint_bub_ms( pos() );
 }
References pos().
set_label()
void vpart_position::set_label (const std::string & text) const
Sets the label at this part of the vehicle.
Removes the label if text is empty.
Definition at line 2915 of file vehicle.cpp.
 {
     std::set<label> &labels = vehicle().labels;
     const auto it = labels.find( label( mount() ) );
     // TODO: empty text should remove the label instead of just storing an empty string, see get_label
     if( it == labels.end() ) {
         labels.insert( label( mount(), text ) );
     } else {
         // labels should really be a map
         labels.insert( labels.erase( it ), label( mount(), text ) );
     }
 }
References anonymous_namespace{item_tname.cpp}::label(), vehicle::labels, mount(), and vehicle().
Referenced by veh_interact::do_relabel().
vehicle()
::vehicle& vpart_position::vehicle () const inline
Definition at line 52 of file vpart_position.h.
{
             return vehicle_.get();
         }
References vehicle_.
Referenced by avail_part_with_feature(), form_inventory(), get_label(), get_tools(), is_inside(), mount(), operator<(), part_displayed(), part_with_feature(), part_with_tool(), pos(), and set_label().
Member Data Documentation
part_index_
size_t vpart_position::part_index_ private
Definition at line 47 of file vpart_position.h.
Referenced by operator<(), and part_index().
vehicle_
std::reference_wrapper<::vehicle> vpart_position::vehicle_ private
Definition at line 46 of file vpart_position.h.
Referenced by vehicle().
The documentation for this class was generated from the following files:
src/vpart_position.h
src/vehicle.cpp
src/vehicle_use.cpp