Cataclysm DDA: saw_stock_actor Class Reference
saw_stock_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
saw_stock_actor (const std::string &type="saw_stock")
void load (const JsonObject &jo) override
std::optional< int > use (Character *p, item &it, const tripoint &pnt) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
ret_val< void > can_use_on (const Character &you, const item &it, const item &target) const
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Additional Inherited Members
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1001 of file iuse_actor.h.
Constructor & Destructor Documentation
saw_stock_actor()
saw_stock_actor::saw_stock_actor (const std::string & type = "saw_stock") inline explicit
Definition at line 1004 of file iuse_actor.h.
 : iuse_actor( type ) {}
Member Function Documentation
can_use_on()
ret_val< void > saw_stock_actor::can_use_on (const Character & you, const item & it, const item & target) const
Definition at line 4064 of file iuse_actor.cpp.
 {
     if( !target.is_gun() ) {
         return ret_val<void>::make_failure( _( "It's not a gun." ) );
     }
     if( target.gunmod_find( itype_stock_none ) ) {
         return ret_val<void>::make_failure( _( "The stock is already sawn-off." ) );
     }
     if( target.gun_type() == gun_type_type( "pistol" ) ) {
         return ret_val<void>::make_failure( _( "This gun doesn't have a stock." ) );
     }
     const auto gunmods = target.gunmods();
     const bool modified_stock = std::any_of( gunmods.begin(), gunmods.end(),
     []( const item * mod ) {
         return mod->type->gunmod->location == gunmod_location( "stock" );
     } );
     const bool accessorized_stock = std::any_of( gunmods.begin(), gunmods.end(),
     []( const item * mod ) {
         return mod->type->gunmod->location == gunmod_location( "stock accessory" );
     } );
     if( target.get_free_mod_locations( gunmod_location( "stock mount" ) ) < 1 ) {
         return ret_val<void>::make_failure(
                    _( "Can't cut off modern composite stocks (must have an empty stock mount)." ) );
     }
     if( modified_stock ) {
         return ret_val<void>::make_failure( _( "Can't cut off modified stocks." ) );
     }
     if( accessorized_stock ) {
         return ret_val<void>::make_failure( _( "Can't cut off accessorized stocks." ) );
     }
     return ret_val<void>::make_success();
 }
References _, item::get_free_mod_locations(), item::gun_type(), item::gunmod_find(), item::gunmods(), item::is_gun(), itype_stock_none, ret_val< T >::make_failure(), and ret_val< T >::make_success().
Referenced by saw_stock_inventory_preset::get_denial().
clone()
std::unique_ptr< iuse_actor > saw_stock_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4106 of file iuse_actor.cpp.
 {
     return std::make_unique<saw_stock_actor>( *this );
 }
load()
void saw_stock_actor::load (const JsonObject & jo) override virtual
Implements iuse_actor.
Definition at line 4036 of file iuse_actor.cpp.
 {
     assign( jo, "cost", cost );
 }
References assign(), and iuse_actor::cost.
use()
std::optional< int > saw_stock_actor::use (Character * p, item & it, const tripoint & pnt) const override virtual
Implements iuse_actor.
Definition at line 4042 of file iuse_actor.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action saw_stock that requires character but no character is present",
                   it.typeId().str() );
         return std::nullopt;
     }
     item_location loc = game_menus::inv::saw_stock( *p, it );
     if( !loc ) {
         p->add_msg_if_player( _( "Never mind." ) );
         return std::nullopt;
     }
     item &obj = *loc.obtain( *p );
     p->add_msg_if_player( _( "You saw down the stock of your %s." ), obj.tname() );
     obj.put_in( item( "stock_none", calendar::turn ), pocket_type::MOD );
     return 0;
 }
References _, Character::add_msg_if_player(), debugmsg, item, MOD, item_location::obtain(), item::put_in(), game_menus::inv::saw_stock(), string_id< T >::str(), item::tname(), calendar::turn, and item::typeId().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp