Cataclysm DDA: int_distribution Class Reference
int_distribution Class Reference
#include <distribution.h>
Public Member Functions
int_distribution ()
int_distribution (int value)
int minimum () const
int sample () const
std::string description () const
void deserialize (const JsonValue &)
Private Attributes
shared_ptr_fast< int_distribution_impl > impl_
Detailed Description
Definition at line 15 of file distribution.h.
Constructor & Destructor Documentation
int_distribution() [1/2]
int_distribution::int_distribution ()
Definition at line 114 of file distribution.cpp.
     : impl_( make_shared_fast<fixed_distribution>( 0 ) )
 {}
int_distribution() [2/2]
int_distribution::int_distribution (int value) explicit
Definition at line 118 of file distribution.cpp.
     : impl_( make_shared_fast<fixed_distribution>( v ) )
 {}
Member Function Documentation
description()
std::string int_distribution::description () const
Definition at line 132 of file distribution.cpp.
 {
     return impl_->description();
 }
References impl_.
deserialize()
void int_distribution::deserialize (const JsonValue & jin)
Definition at line 137 of file distribution.cpp.
 {
     int lo = 0;
     int hi = INT_MAX;
     if( jin.test_int() ) {
         int v = jin.get_int();
         impl_ = make_shared_fast<fixed_distribution>( v );
     } else if( jin.test_array() ) {
         JsonArray jarr = jin.get_array();
         if( jarr.size() != 2 ) {
             jarr.throw_error( "uniform array has wrong number of elements, should be [ lo, hi ]" );
         }
         lo = jarr.get_int( 0 );
         hi = jarr.get_int( 1 );
         if( lo >= hi ) {
             jarr.throw_error( "uniform array should be in order [ lo, hi ]" );
         }
         if( lo < 0 || hi < 0 ) {
             jarr.throw_error( "both elements must be 0 or greater" );
         }
         impl_ = make_shared_fast<uniform_distribution>( lo, hi );
     } else if( jin.test_object() ) {
         JsonObject jo = jin.get_object();
         if( jo.has_member( "bounds" ) ) {
             if( jo.get_array( "bounds" ).size() != 2 ) {
                 jo.throw_error( "bounds array has wrong number of elements, should be [ lo, hi ]" );
             }
             lo = jo.get_array( "bounds" ).get_int( 0 );
             hi = jo.get_array( "bounds" ).get_int( 1 );
             if( hi < 0 ) {
                 hi = INT_MAX;
             }
             if( lo < 0 ) {
                 lo = 0;
             }
             if( lo >= hi ) {
                 jo.throw_error( "bounds array should be in order [ lo, hi ]" );
             }
         }
         if( jo.has_member( "poisson" ) ) {
             if( jo.has_member( "binomial" ) ) {
                 jo.throw_error( "can't use multiple distribution types" );
             }
             double mean = jo.get_float( "poisson", 1.0 );
             if( mean <= 0.0 ) {
                 jo.throw_error( "poisson mean must be greater than 0.0" );
             }
             impl_ = make_shared_fast<poisson_distribution>( lo, hi, mean );
         } else if( jo.has_member( "binomial" ) ) {
             JsonArray arr = jo.get_array( "binomial" );
             if( jo.get_array( "binomial" ).size() != 2 ) {
                 jo.throw_error( "binomial array has wrong number of elements, should be [ t, p ]" );
             }
             int t = jo.get_array( "binomial" ).get_int( 0 );
             double p = jo.get_array( "binomial" ).get_float( 1 );
             if( t < 0 ) {
                 jo.throw_error( "t trials must be 0 or greater" );
             }
             if( p < 0.0 || p > 1.0 ) {
                 jo.throw_error( "success probability must be between 0.0 and 1.0" );
             }
             impl_ =  make_shared_fast<binomial_distribution>( lo, hi, t, p );
         } else {
             jo.throw_error( R"(Expected "poisson" or "binomial" member)" );
         }
     } else {
         jin.throw_error( "expected integer, array or object" );
     }
 }
References JsonValue::get_array(), JsonObject::get_array(), JsonArray::get_float(), JsonObject::get_float(), JsonValue::get_int(), JsonArray::get_int(), JsonValue::get_object(), JsonObject::has_member(), impl_, cata::hash64_detail::lo, JsonArray::size(), JsonValue::test_array(), JsonValue::test_int(), JsonValue::test_object(), JsonObject::throw_error(), JsonValue::throw_error(), and JsonArray::throw_error().
minimum()
int int_distribution::minimum () const
Definition at line 122 of file distribution.cpp.
 {
     return impl_->minimum();
 }
References impl_.
Referenced by mutable_overmap_placement_rule::check().
sample()
int int_distribution::sample () const
Definition at line 127 of file distribution.cpp.
 {
     return impl_->sample();
 }
References impl_.
Referenced by mutable_overmap_placement_rule::realise().
Member Data Documentation
impl_
shared_ptr_fast<int_distribution_impl> int_distribution::impl_ private
Definition at line 26 of file distribution.h.
Referenced by description(), deserialize(), minimum(), and sample().
The documentation for this class was generated from the following files:
src/distribution.h
src/distribution.cpp