Cataclysm DDA: disassemble_inventory_preset Class Reference
disassemble_inventory_preset Class Reference
Public Member Functions
disassemble_inventory_preset (const Character &you, const inventory &inv)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Protected Member Functions
const recipe & get_recipe (const item_location &loc) const
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Private Attributes
const Character & you
const inventory & inv
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 586 of file game_inventory.cpp.
Constructor & Destructor Documentation
disassemble_inventory_preset()
disassemble_inventory_preset::disassemble_inventory_preset (const Character & you, const inventory & inv) inline
Definition at line 589 of file game_inventory.cpp.
                                                                                    : you( you ),
             inv( inv ) {
             check_components = true;
             append_cell( [ this ]( const item_location & loc ) {
                 const requirement_data &req = get_recipe( loc ).disassembly_requirements();
                 if( req.is_empty() ) {
                     return std::string();
                 }
                 const item *i = loc.get_item();
                 std::vector<item_comp> components = i->get_uncraft_components();
                 std::sort( components.begin(), components.end() );
                 auto it = components.begin();
                 while( ( it = std::adjacent_find( it, components.end() ) ) != components.end() ) {
                     ++( it->count );
                     components.erase( std::next( it ) );
                 }
                 return enumerate_as_string( components.begin(), components.end(),
                 []( const decltype( components )::value_type & comps ) {
                     return comps.to_string();
                 } );
             }, _( "YIELD" ) );
             append_cell( [ this ]( const item_location & loc ) {
                 return to_string_clipped( get_recipe( loc ).time_to_craft( get_player_character(),
                                           recipe_time_flag::ignore_proficiencies ) );
             }, _( "TIME" ) );
         }
References _, inventory_selector_preset::append_cell(), inventory_selector_preset::check_components, recipe::disassembly_requirements(), enumerate_as_string(), item_location::get_item(), get_player_character(), get_recipe(), item::get_uncraft_components(), ignore_proficiencies, requirement_data::is_empty(), and to_string_clipped().
Member Function Documentation
get_denial()
std::string disassemble_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 623 of file game_inventory.cpp.
{
             const auto ret = you.can_disassemble( *loc, inv );
             if( !ret.success() ) {
                 return ret.str();
             }
             return std::string();
         }
References Character::can_disassemble(), inv, cata::hash64_detail::ret, and you.
get_recipe()
const recipe& disassemble_inventory_preset::get_recipe (const item_location & loc) const inline protected
Definition at line 632 of file game_inventory.cpp.
{
             return recipe_dictionary::get_uncraft( loc->typeId() );
         }
References recipe_dictionary::get_uncraft(), and item::typeId().
Referenced by disassemble_inventory_preset(), and is_shown().
is_shown()
bool disassemble_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 619 of file game_inventory.cpp.
{
             return !get_recipe( loc ).is_null();
         }
References get_recipe(), and recipe::is_null().
Member Data Documentation
inv
const inventory& disassemble_inventory_preset::inv private
Definition at line 638 of file game_inventory.cpp.
Referenced by get_denial().
you
const Character& disassemble_inventory_preset::you private
Definition at line 637 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp