Cataclysm DDA: mapgen_palette Class Reference
mapgen_palette Class Reference
#include <mapgen.h>
Classes
struct add_palette_context
Public Types
using placing_map = std::unordered_map< map_key, std::vector< shared_ptr_fast< const jmapgen_piece > >>
The mapping from character (key) to a list of things that should be placed.
Public Member Functions
template<typename PieceType >
void load_place_mapings (const JsonObject &jo, const std::string &member_name, placing_map &format_placings, const std::string &context)
Load (append to format_placings) the places that should be put there.
void check () const
const mapgen_parameters & get_parameters () const
Static Public Member Functions
static mapgen_palette load_temp (const JsonObject &jo, std::string_view src, const std::string &context)
Loads a palette object and returns it.
static void load (const JsonObject &jo, std::string_view src)
Load a palette object and adds it to the global set of palettes.
static const mapgen_palette & get (const palette_id &id)
Returns a palette with given id.
static void check_definitions ()
static void reset ()
Public Attributes
palette_id id
std::unordered_set< map_key > keys_with_terrain
placing_map format_placings
Private Member Functions
void add (const mapgen_value< std::string > &rh, const add_palette_context &)
Adds a palette to this one.
void add (const palette_id &rh, const add_palette_context &)
void add (const mapgen_palette &rh, const add_palette_context &)
Static Private Member Functions
static mapgen_palette load_internal (const JsonObject &jo, std::string_view src, const std::string &context, bool require_id, bool allow_recur)
Private Attributes
mapgen_parameters parameters
std::vector< mapgen_value< std::string > > palettes_used
Detailed Description
Definition at line 306 of file mapgen.h.
Member Typedef Documentation
placing_map
using mapgen_palette::placing_map = std::unordered_map<map_key, std::vector< shared_ptr_fast<const jmapgen_piece> >>
The mapping from character (key) to a list of things that should be placed.
This is similar to objects, but it uses key to get the actual position where to place things out of the json "bitmap" (which is used to paint the terrain/furniture).
Definition at line 316 of file mapgen.h.
Member Function Documentation
add() [1/3]
void mapgen_palette::add (const mapgen_palette & rh, const add_palette_context & context) private
Definition at line 4280 of file mapgen.cpp.
 {
     std::string actual_context = id.is_empty() ? context.context : "palette " + id.str();
     if( !rh.id.is_empty() ) {
         const std::vector<palette_id> &ancestors = context.ancestors;
         auto loop_start = std::find( ancestors.begin(), ancestors.end(), rh.id );
         if( loop_start != ancestors.end() ) {
             std::string loop_ids = enumerate_as_string( loop_start, ancestors.end(),
             []( const palette_id & i ) {
                 return i.str();
             }, enumeration_conjunction::arrow );
             debugmsg( "loop in palette references: %s", loop_ids );
             return;
         }
     }
     add_palette_context new_context = context;
     new_context.ancestors.push_back( rh.id );
     new_context.current_parameters = &rh.parameters;
     for( const mapgen_value<std::string> &recursive_palette : rh.palettes_used ) {
         add( recursive_palette, new_context );
     }
     for( const auto &placing : rh.format_placings ) {
         const std::vector<mapgen_constraint<palette_id>> &constraints = context.constraints;
         std::vector<shared_ptr_fast<const jmapgen_piece>> constrained_placings = placing.second;
         if( !constraints.empty() ) {
             for( shared_ptr_fast<const jmapgen_piece> &piece : constrained_placings ) {
                 piece = make_shared_fast<jmapgen_constrained<palette_id>>(
                             std::move( piece ), constraints );
             }
         }
         std::vector<shared_ptr_fast<const jmapgen_piece>> &these_placings =
                     format_placings[placing.first];
         these_placings.insert( these_placings.end(),
                                constrained_placings.begin(), constrained_placings.end() );
     }
     for( const map_key &placing : rh.keys_with_terrain ) {
         keys_with_terrain.insert( placing );
     }
     parameters.check_and_merge( rh.parameters, actual_context );
 }
References add(), mapgen_palette::add_palette_context::ancestors, arrow, mapgen_parameters::check_and_merge(), context, mapgen_palette::add_palette_context::current_parameters, debugmsg, enumerate_as_string(), format_placings, id, string_id< T >::is_empty(), keys_with_terrain, palettes_used, and parameters.
add() [2/3]
void mapgen_palette::add (const mapgen_value< std::string > & rh, const add_palette_context & context) private
Adds a palette to this one.
New values take preference over the old ones.
The ancestors parameter is a set of ids from all the palettes currently being added, when this addition is triggered by the addition of another palette which includes rh. This allows for detection of loops in palette references.
Definition at line 4240 of file mapgen.cpp.
 {
     std::vector<std::string> possible_values =
         rh.all_possible_results( *context.current_parameters );
     if( possible_values.empty() ) {
         if( const std::string *param_name = rh.get_name_if_parameter() ) {
             debugmsg( "Parameter %s used for palette id in %s but has no possible values",
                       *param_name, context.context );
         } else {
             debugmsg( "Mapgen value for used for palette id in %s has no possible values",
                       context.context );
         }
     } else if( possible_values.size() == 1 ) {
         add( palette_id( possible_values.front() ), context );
     } else {
         std::string param_name;
         if( const std::string *name = rh.get_name_if_parameter() ) {
             param_name = *name;
         } else {
             const auto param_it =
                 context.top_level_parameters->add_unique_parameter(
                     "palette_choice_", rh, cata_variant_type::palette_id,
                     mapgen_parameter_scope::overmap_special );
             param_name = param_it->first;
         }
         add_palette_context context_with_extra_constraint( context );
         for( const std::string &value : possible_values ) {
             palette_id val_id( value );
             context_with_extra_constraint.constraints.emplace_back( param_name, val_id );
             add( val_id, context_with_extra_constraint );
             context_with_extra_constraint.constraints.pop_back();
         }
     }
 }
References mapgen_value< Id >::all_possible_results(), mapgen_palette::add_palette_context::constraints, context, debugmsg, mapgen_value< Id >::get_name_if_parameter(), om_direction::name(), overmap_special, and palette_id.
Referenced by add(), and load_internal().
add() [3/3]
void mapgen_palette::add (const palette_id & rh, const add_palette_context & context) private
Definition at line 4275 of file mapgen.cpp.
 {
     add( get( rh ), context );
 }
References add(), context, and get().
check()
void mapgen_palette::check () const
Definition at line 4183 of file mapgen.cpp.
 {
     std::string context = "palette " + id.str();
     jmapgen_int fake_coord( -1 );
     mapgen_parameters no_parameters;
     for( const std::pair<const std::string, mapgen_parameter> &param : parameters.map ) {
         std::string this_context = string_format( "parameter %s in %s", param.first, context );
         param.second.check( no_parameters, this_context );
     }
     for( const std::pair<const map_key, std::vector<shared_ptr_fast<const jmapgen_piece>>> &p :
          format_placings ) {
         for( const shared_ptr_fast<const jmapgen_piece> &j : p.second ) {
             j->check( context, parameters, fake_coord, fake_coord, fake_coord );
         }
     }
 }
References context, format_placings, mapgen_parameters::map, parameters, and string_format().
check_definitions()
void mapgen_palette::check_definitions () static
Definition at line 4228 of file mapgen.cpp.
 {
     for( const auto &p : palettes ) {
         p.second.check();
     }
 }
References palettes.
Referenced by DynamicDataLoader::check_consistency().
get()
const mapgen_palette & mapgen_palette::get (const palette_id & id) static
Returns a palette with given id.
If not found, debugmsg and returns a dummy.
Definition at line 4216 of file mapgen.cpp.
 {
     const auto iter = palettes.find( id );
     if( iter != palettes.end() ) {
         return iter->second;
     }
     debugmsg( "Requested palette with unknown id %s", id.c_str() );
     static mapgen_palette dummy;
     return dummy;
 }
References debugmsg, and palettes.
Referenced by add(), jmapgen_setmap::apply(), and jmapgen_setmap::has_vehicle_collision().
get_parameters()
const mapgen_parameters& mapgen_palette::get_parameters () const inline
Definition at line 332 of file mapgen.h.
{
             return parameters;
         }
References parameters.
Referenced by mapgen_function_json_base::setup_common().
load()
void mapgen_palette::load (const JsonObject & jo, std::string_view src) static
Load a palette object and adds it to the global set of palettes.
If "palette" field is specified, those palettes will be loaded recursively.
Definition at line 4206 of file mapgen.cpp.
 {
     mapgen_palette ret = load_internal( jo, src, "", true, false );
     if( ret.id.is_empty() ) {
         jo.throw_error( "Named palette needs an id" );
     }
     palettes[ ret.id ] = ret;
 }
References load_internal(), palettes, cata::hash64_detail::ret, and JsonObject::throw_error().
Referenced by DynamicDataLoader::initialize().
load_internal()
mapgen_palette mapgen_palette::load_internal (const JsonObject & jo, std::string_view src, const std::string & context, bool require_id, bool allow_recur) static private
Definition at line 4323 of file mapgen.cpp.
 {
     mapgen_palette new_pal;
     mapgen_palette::placing_map &format_placings = new_pal.format_placings;
     auto &keys_with_terrain = new_pal.keys_with_terrain;
     if( require_id ) {
         new_pal.id = palette_id( jo.get_string( "id" ) );
     }
     jo.read( "parameters", new_pal.parameters.map );
     if( jo.has_array( "palettes" ) ) {
         jo.read( "palettes", new_pal.palettes_used );
         if( allow_recur ) {
             // allow_recur means that it's safe to assume all the palettes have
             // been defined and we can inline now.  Otherwise we just leave the
             // list in our palettes_used array and it will be consumed
             // recursively by calls to add which add this palette.
             add_palette_context add_context{ context, &new_pal.parameters };
             for( auto &p : new_pal.palettes_used ) {
                 new_pal.add( p, add_context );
             }
             new_pal.palettes_used.clear();
         }
     }
     // mandatory: every character in rows must have matching entry, unless fill_ter is set
     // "terrain": { "a": "t_grass", "b": "t_lava" }.  To help enforce this we
     // keep track of everything in the "terrain" object
     if( jo.has_member( "terrain" ) ) {
         for( const JsonMember member : jo.get_object( "terrain" ) ) {
             keys_with_terrain.insert( map_key( member ) );
         }
     }
     std::string c = "palette " + new_pal.id.str();
     new_pal.load_place_mapings<jmapgen_terrain>( jo, "terrain", format_placings, c );
     new_pal.load_place_mapings<jmapgen_furniture>( jo, "furniture", format_placings, c );
     new_pal.load_place_mapings<jmapgen_field>( jo, "fields", format_placings, c );
     new_pal.load_place_mapings<jmapgen_npc>( jo, "npcs", format_placings, c );
     new_pal.load_place_mapings<jmapgen_sign>( jo, "signs", format_placings, c );
     new_pal.load_place_mapings<jmapgen_vending_machine>( jo, "vendingmachines", format_placings, c );
     new_pal.load_place_mapings<jmapgen_toilet>( jo, "toilets", format_placings, c );
     new_pal.load_place_mapings<jmapgen_gaspump>( jo, "gaspumps", format_placings, c );
     new_pal.load_place_mapings<jmapgen_item_group>( jo, "items", format_placings, c );
     new_pal.load_place_mapings<jmapgen_monster_group>( jo, "monsters", format_placings, c );
     new_pal.load_place_mapings<jmapgen_vehicle>( jo, "vehicles", format_placings, c );
     // json member name is not optimal, it should be plural like all the others above, but that conflicts
     // with the items entry which refers to item groups.
     new_pal.load_place_mapings<jmapgen_spawn_item>( jo, "item", format_placings, c );
     new_pal.load_place_mapings<jmapgen_remove_vehicles>( jo, "remove_vehicles", format_placings, c );
     new_pal.load_place_mapings<jmapgen_remove_all>( jo, "remove_all", format_placings, c );
     new_pal.load_place_mapings<jmapgen_trap>( jo, "traps", format_placings, c );
     new_pal.load_place_mapings<jmapgen_monster>( jo, "monster", format_placings, c );
     new_pal.load_place_mapings<jmapgen_make_rubble>( jo, "rubble", format_placings, c );
     new_pal.load_place_mapings<jmapgen_computer>( jo, "computers", format_placings, c );
     new_pal.load_place_mapings<jmapgen_sealed_item>( jo, "sealed_item", format_placings, c );
     new_pal.load_place_mapings<jmapgen_nested>( jo, "nested", format_placings, c );
     new_pal.load_place_mapings<jmapgen_liquid_item>( jo, "liquids", format_placings, c );
     new_pal.load_place_mapings<jmapgen_corpse>( jo, "corpses", format_placings, c );
     new_pal.load_place_mapings<jmapgen_graffiti>( jo, "graffiti", format_placings, c );
     new_pal.load_place_mapings<jmapgen_zone>( jo, "zones", format_placings, c );
     new_pal.load_place_mapings<jmapgen_ter_furn_transform>( jo, "ter_furn_transforms",
             format_placings, c );
     new_pal.load_place_mapings<jmapgen_faction>( jo, "faction_owner_character", format_placings, c );
     for( mapgen_palette::placing_map::value_type &p : format_placings ) {
         p.second.erase(
             std::remove_if(
                 p.second.begin(), p.second.end(),
         []( const shared_ptr_fast<const jmapgen_piece> &placing ) {
             return placing->is_nop();
         } ), p.second.end() );
     }
     return new_pal;
 }
References add(), c, context, format_placings, JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_member(), id, keys_with_terrain, load_place_mapings(), mapgen_parameters::map, member, palette_id, palettes_used, parameters, JsonObject::read(), and string_id< T >::str().
Referenced by load(), and load_temp().
load_place_mapings()
template<typename PieceType > void mapgen_palette::load_place_mapings (const JsonObject & jo, const std::string & member_name, placing_map & format_placings, const std::string & context)
Load (append to format_placings) the places that should be put there.
member_name is the name of an optional object / array in the json object jsi.
Definition at line 4134 of file mapgen.cpp.
 {
     if( jo.has_object( "mapping" ) ) {
         for( const JsonMember member : jo.get_object( "mapping" ) ) {
             const map_key key( member );
             JsonObject sub = member.get_object();
             sub.allow_omitted_members();
             if( !sub.has_member( member_name ) ) {
                 continue;
             }
             auto &vect = format_placings[ key ];
             // NOLINTNEXTLINE(cata-translate-string-literal)
             std::string this_context = string_format( "%s in mapping in %s", member_name, context );
             ::load_place_mapings<PieceType>( sub.get_member( member_name ), vect, this_context );
         }
     }
     if( !jo.has_object( member_name ) ) {
         return;
     }
     for( const JsonMember member : jo.get_object( member_name ) ) {
         const map_key key( member );
         auto &vect = format_placings[ key ];
         std::string this_context =
             // NOLINTNEXTLINE(cata-translate-string-literal)
             string_format( "%s %s in %s", member_name, member.name(), context );
         ::load_place_mapings<PieceType>( member, vect, this_context );
     }
 }
References context, format_placings, JsonObject::get_object(), JsonObject::has_object(), member, string_format(), and math_opers::sub().
Referenced by load_internal().
load_temp()
mapgen_palette mapgen_palette::load_temp (const JsonObject & jo, std::string_view src, const std::string & context) static
Loads a palette object and returns it.
Doesn't save it anywhere.
Definition at line 4200 of file mapgen.cpp.
 {
     return load_internal( jo, src, context, false, true );
 }
References context, and load_internal().
Referenced by mapgen_function_json_base::setup_common().
reset()
void mapgen_palette::reset () static
Definition at line 4235 of file mapgen.cpp.
 {
     palettes.clear();
 }
References palettes.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
format_placings
placing_map mapgen_palette::format_placings
Definition at line 320 of file mapgen.h.
Referenced by add(), check(), load_internal(), load_place_mapings(), and mapgen_function_json_base::setup_common().
id
palette_id mapgen_palette::id
Definition at line 309 of file mapgen.h.
Referenced by add(), mapgen_function_json_base::check_common(), and load_internal().
keys_with_terrain
std::unordered_set<map_key> mapgen_palette::keys_with_terrain
Definition at line 319 of file mapgen.h.
Referenced by add(), load_internal(), and mapgen_function_json_base::setup_common().
palettes_used
std::vector<mapgen_value<std::string> > mapgen_palette::palettes_used private
Definition at line 361 of file mapgen.h.
Referenced by add(), and load_internal().
parameters
mapgen_parameters mapgen_palette::parameters private
Definition at line 356 of file mapgen.h.
Referenced by add(), check(), jmapgen_objects::check(), mapgen_function_json_base::check_common(), mapgen_function_json::get_mapgen_params(), get_parameters(), load_internal(), and mapgen_function_json_base::setup_common().
The documentation for this class was generated from the following files:
src/mapgen.h
src/mapgen.cpp