Cataclysm DDA: jmapgen_variable Class Reference
jmapgen_variable Class Reference
Place a variable.
Public Member Functions
jmapgen_variable (const JsonObject &jsi, const std::string_view &)
mapgen_phase phase () const override
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
std::string name
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a variable.
Definition at line 3399 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_variable()
jmapgen_variable::jmapgen_variable (const JsonObject & jsi, const std::string_view &) inline
Definition at line 3403 of file mapgen.cpp.
{
             name = jsi.get_string( "name" );
         }
References JsonObject::get_string(), mapgen_defer::jsi, and name.
Member Function Documentation
apply()
void jmapgen_variable::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 3409 of file mapgen.cpp.
{
             queued_points[name] = dat.m.getglobal( tripoint( x.val, y.val,
                                                    dat.zlevel() + z.get() ) );
         }
References jmapgen_int::get(), map::getglobal(), mapgendata::m, name, queued_points, tripoint, jmapgen_int::val, and mapgendata::zlevel().
phase()
mapgen_phase jmapgen_variable::phase () const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 3406 of file mapgen.cpp.
{
             return mapgen_phase::zones;
         }
References zones.
Member Data Documentation
name
std::string jmapgen_variable::name
Definition at line 3402 of file mapgen.cpp.
Referenced by apply(), and jmapgen_variable().
The documentation for this class was generated from the following file:
src/mapgen.cpp