Cataclysm DDA: move_items_activity_actor Class Reference
move_items_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
move_items_activity_actor (std::vector< item_location > target_items, std::vector< int > quantities, bool to_vehicle, tripoint relative_destination, bool hauling_mode=false)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
std::vector< item_location > target_items
std::vector< int > quantities
bool to_vehicle
tripoint relative_destination
bool hauling_mode
Detailed Description
Definition at line 494 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
move_items_activity_actor()
move_items_activity_actor::move_items_activity_actor (std::vector< item_location > target_items, std::vector< int > quantities, bool to_vehicle, tripoint relative_destination, bool hauling_mode = false) inline
Definition at line 504 of file activity_actor_definitions.h.
                                                                                                                :
             target_items( std::move( target_items ) ), quantities( std::move( quantities ) ),
             to_vehicle( to_vehicle ),
             relative_destination( relative_destination ),
             hauling_mode( hauling_mode ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> move_items_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 519 of file activity_actor_definitions.h.
{
             return std::make_unique<move_items_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > move_items_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 2422 of file activity_actor.cpp.
 {
     move_items_activity_actor actor( {}, {}, false, tripoint_zero );
     JsonObject data = jsin.get_object();
     data.read( "target_items", actor.target_items );
     data.read( "quantities", actor.quantities );
     data.read( "to_vehicle", actor.to_vehicle );
     data.read( "relative_destination", actor.relative_destination );
     data.read( "hauling_mode", actor.hauling_mode );
     return actor.clone();
 }
References JsonValue::get_object(), JsonObject::read(), and tripoint_zero.
do_turn()
void move_items_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 2330 of file activity_actor.cpp.
 {
     const tripoint_bub_ms dest = relative_destination + who.pos_bub();
     while( who.get_moves() > 0 && !target_items.empty() ) {
         item_location target = std::move( target_items.back() );
         const int quantity = quantities.back();
         target_items.pop_back();
         quantities.pop_back();
         if( !target ) {
             debugmsg( "Lost target item of ACT_MOVE_ITEMS" );
             continue;
         }
         // Check that we can pick it up.
         if( target->made_of_from_type( phase_id::SOLID ) ) {
             // Spill out any invalid contents first
             target.overflow();
             item &leftovers = *target;
             // Make a copy to be put in the destination location
             item newit = leftovers;
             if( newit.is_owned_by( who, true ) ) {
                 newit.set_owner( who );
             } else {
                 continue;
             }
             // Handle charges, quantity == 0 means move all
             if( quantity != 0 && newit.count_by_charges() ) {
                 newit.charges = std::min( newit.charges, quantity );
                 leftovers.charges -= quantity;
             } else {
                 leftovers.charges = 0;
             }
             // This is for hauling across zlevels, remove when going up and down stairs
             // is no longer teleportation
             const tripoint_bub_ms src = target.pos_bub();
             const int distance = src.z() == dest.z() ? std::max( rl_dist( src, dest ), 1 ) : 1;
             // Yuck, I'm sticking weariness scaling based on activity level here
             const float weary_mult = who.exertion_adjusted_move_multiplier( exertion_level() );
             who.mod_moves( -Pickup::cost_to_move_item( who, newit ) * distance * weary_mult );
             if( to_vehicle ) {
                 put_into_vehicle_or_drop( who, item_drop_reason::deliberate, { newit }, dest );
             } else {
                 std::vector<item_location> dropped_items = drop_on_map( who, item_drop_reason::deliberate, { newit },
                         dest );
                 if( hauling_mode ) {
                     who.haul_list.insert( who.haul_list.end(), dropped_items.begin(), dropped_items.end() );
                 }
             }
             // If we picked up a whole stack, remove the leftover item
             if( leftovers.charges <= 0 ) {
                 target.remove_item();
             }
         }
     }
     if( target_items.empty() ) {
         // Nuke the current activity, leaving the backlog alone.
         act.set_to_null();
         if( hauling_mode ) {
             std::vector<item_location> haulable_items = get_map().get_haulable_items( who.pos() );
             bool overflow = who.trim_haul_list( haulable_items );
             if( who.is_hauling() && haulable_items.empty() ) {
                 who.stop_hauling();
             }
             if( overflow ) {
                 add_msg( m_warning,
                          _( "You lose track of some hauled items as they didn't fit on the current tile." ) );
             }
         }
     }
 }
References _, act, add_msg(), item::charges, Pickup::cost_to_move_item(), item::count_by_charges(), debugmsg, deliberate, drop_on_map(), Character::exertion_adjusted_move_multiplier(), activity_actor::exertion_level(), map::get_haulable_items(), get_map(), Creature::get_moves(), Character::haul_list, hauling_mode, Character::is_hauling(), item::is_owned_by(), m_warning, item::made_of_from_type(), max(), min(), Creature::mod_moves(), item_location::overflow(), Creature::pos(), Creature::pos_bub(), item_location::pos_bub(), put_into_vehicle_or_drop(), quantities, relative_destination, item_location::remove_item(), rl_dist(), item::set_owner(), SOLID, Character::stop_hauling(), target_items, to_vehicle, Character::trim_haul_list(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
finish()
void move_items_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 517 of file activity_actor_definitions.h.
 {}
get_progress_message()
std::string move_items_activity_actor::get_progress_message (const player_activity & act) const inline override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 523 of file activity_actor_definitions.h.
{
             return std::string();
         }
get_type()
activity_id move_items_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 511 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_MOVE_ITEMS" );
         }
References activity_id.
serialize()
void move_items_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 2409 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target_items", target_items );
     jsout.member( "quantities", quantities );
     jsout.member( "to_vehicle", to_vehicle );
     jsout.member( "relative_destination", relative_destination );
     jsout.member( "hauling_mode", hauling_mode );
     jsout.end_object();
 }
References JsonOut::end_object(), hauling_mode, JsonOut::member(), quantities, relative_destination, JsonOut::start_object(), target_items, and to_vehicle.
start()
void move_items_activity_actor::start (player_activity & act, Character & who) inline override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 515 of file activity_actor_definitions.h.
 {}
Member Data Documentation
hauling_mode
bool move_items_activity_actor::hauling_mode private
Definition at line 501 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
quantities
std::vector<int> move_items_activity_actor::quantities private
Definition at line 498 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
relative_destination
tripoint move_items_activity_actor::relative_destination private
Definition at line 500 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
target_items
std::vector<item_location> move_items_activity_actor::target_items private
Definition at line 497 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
to_vehicle
bool move_items_activity_actor::to_vehicle private
Definition at line 499 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp