Cataclysm DDA: chop_planks_activity_actor Class Reference
chop_planks_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
chop_planks_activity_actor ()=default
chop_planks_activity_actor (int moves)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves
Detailed Description
Definition at line 1835 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
chop_planks_activity_actor() [1/2]
chop_planks_activity_actor::chop_planks_activity_actor () default
chop_planks_activity_actor() [2/2]
chop_planks_activity_actor::chop_planks_activity_actor (int moves) inline explicit
Definition at line 1839 of file activity_actor_definitions.h.
 : moves( moves ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> chop_planks_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1849 of file activity_actor_definitions.h.
{
             return std::make_unique<chop_planks_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > chop_planks_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6358 of file activity_actor.cpp.
 {
     chop_planks_activity_actor actor( {} );
     JsonObject data = jsin.get_object();
     data.read( "moves", actor.moves );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void chop_planks_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 6317 of file activity_actor.cpp.
 {
     chop_single_do_turn( act );
 }
References act, and chop_single_do_turn().
finish()
void chop_planks_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Fabrication increases number of planks cut from a log
Implements activity_actor.
Definition at line 6322 of file activity_actor.cpp.
 {
     const int max_planks = 10;
     /** @EFFECT_FABRICATION increases number of planks cut from a log */
     int planks = normal_roll( 2 + who.get_skill_level( skill_fabrication ), 1 );
     int wasted_planks = max_planks - planks;
     int scraps = rng( wasted_planks, wasted_planks * 3 );
     planks = std::min( planks, max_planks );
     map &here = get_map();
     if( planks > 0 ) {
         here.spawn_item( here.getlocal( act.placement ), itype_2x4, planks, 0, calendar::turn );
         who.add_msg_if_player( m_good, n_gettext( "You produce %d plank.", "You produce %d planks.",
                                planks ), planks );
     }
     if( scraps > 0 ) {
         here.spawn_item( here.getlocal( act.placement ), itype_splinter, scraps, 0, calendar::turn );
         who.add_msg_if_player( m_good, n_gettext( "You produce %d splinter.", "You produce %d splinters.",
                                scraps ), scraps );
     }
     if( planks < max_planks / 2 ) {
         who.add_msg_if_player( m_bad, _( "You waste a lot of the wood." ) );
     }
     act.set_to_null();
     activity_handlers::resume_for_multi_activities( who );
 }
References _, act, Character::add_msg_if_player(), get_map(), Character::get_skill_level(), map::getlocal(), itype_2x4, itype_splinter, m_bad, m_good, min(), n_gettext, normal_roll(), activity_handlers::resume_for_multi_activities(), rng(), skill_fabrication, map::spawn_item(), and calendar::turn.
get_type()
activity_id chop_planks_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1841 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_CHOP_PLANKS" );
         }
References activity_id.
serialize()
void chop_planks_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6349 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves", moves );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves, and JsonOut::start_object().
start()
void chop_planks_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 6311 of file activity_actor.cpp.
 {
     act.moves_total = moves;
     act.moves_left = moves;
 }
References act, and moves.
Member Data Documentation
moves
int chop_planks_activity_actor::moves private
Definition at line 1857 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp