Cataclysm DDA: iuse_actor Class Reference
iuse_actor Class Reference abstract
#include <iuse.h>
Public Member Functions
virtual ~iuse_actor ()=default
virtual void load (const JsonObject &jo)=0
virtual std::optional< int > use (Character *, item &, const tripoint &) const =0
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual std::unique_ptr< iuse_actor > clone () const =0
Returns a deep copy of this object.
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Protected Member Functions
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 252 of file iuse.h.
Constructor & Destructor Documentation
iuse_actor()
iuse_actor::iuse_actor (const std::string & type, int cost = -1) inline explicit protected
Definition at line 255 of file iuse.h.
 : type( type ), cost( cost ) {}
~iuse_actor()
virtual iuse_actor::~iuse_actor () virtual default
Member Function Documentation
can_use()
ret_val< void > iuse_actor::can_use (const Character & , const item & , const tripoint &) const virtual
Reimplemented in modify_gunmods_actor, detach_gunmods_actor, install_bionic_actor, musical_instrument_actor, play_instrument_iuse, manualnoise_actor, fireweapon_off_actor, firestarter_actor, and iuse_transform.
Definition at line 392 of file item_action.cpp.
 {
     return ret_val<void>::make_success();
 }
References ret_val< T >::make_success().
clone()
virtual std::unique_ptr<iuse_actor> iuse_actor::clone () const pure virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implemented in effect_on_conditons_actor, sew_advanced_actor, weigh_self_actor, deploy_tent_actor, link_up_actor, modify_gunmods_actor, detach_gunmods_actor, install_bionic_actor, molle_detach_actor, molle_attach_actor, saw_stock_actor, saw_barrel_actor, emit_actor, place_trap_actor, heal_actor, repair_item_actor, ammobelt_actor, holster_actor, cast_spell_actor, learn_spell_actor, musical_instrument_actor, play_instrument_iuse, manualnoise_actor, fireweapon_on_actor, fireweapon_off_actor, inscribe_actor, salvage_actor, firestarter_actor, reveal_map_actor, deploy_appliance_actor, deploy_furn_actor, place_npc_iuse, change_scent_iuse, place_monster_iuse, delayed_transform_iuse, consume_drug_iuse, explosion_iuse, sound_iuse, message_iuse, unpack_actor, iuse_transform, iuse_function_wrapper_with_info, and iuse_function_wrapper.
finalize()
virtual void iuse_actor::finalize (const itype_id &) inline virtual
Finalizes the actor.
Must be called after all items are loaded.
Reimplemented in modify_gunmods_actor, detach_gunmods_actor, install_bionic_actor, emit_actor, and iuse_transform.
Definition at line 299 of file iuse.h.
 { }
Referenced by Item_factory::finalize_pre().
get_description()
std::string iuse_actor::get_description () const virtual
Returns the translated description of the action.
It is used for the item action menu.
Reimplemented in repair_item_actor.
Definition at line 407 of file item_action.cpp.
 {
     return std::string();
 }
Referenced by use_function::get_description().
get_name()
std::string iuse_actor::get_name () const virtual
Returns the translated name of the action.
It is used for the item action menu.
Reimplemented in effect_on_conditons_actor, link_up_actor, repair_item_actor, cast_spell_actor, sound_iuse, message_iuse, and iuse_transform.
Definition at line 402 of file item_action.cpp.
 {
     return item_action_generator::generator().get_action_name( type );
 }
References item_action_generator::generator(), item_action_generator::get_action_name(), and type.
Referenced by use_function::get_name(), iuse_transform::get_name(), message_iuse::get_name(), sound_iuse::get_name(), link_up_actor::get_name(), effect_on_conditons_actor::get_name(), and modify_gunmods_actor::use().
info()
virtual void iuse_actor::info (const item & , std::vector< iteminfo > &) const inline virtual
Reimplemented in iuse_function_wrapper_with_info, unpack_actor, effect_on_conditons_actor, weigh_self_actor, link_up_actor, heal_actor, ammobelt_actor, holster_actor, cast_spell_actor, learn_spell_actor, deploy_appliance_actor, deploy_furn_actor, consume_drug_iuse, explosion_iuse, and iuse_transform.
Definition at line 271 of file iuse.h.
 {}
Referenced by iuse_transform::info().
is_valid()
bool iuse_actor::is_valid () const virtual
Returns whether the actor is valid (exists in the generator).
Definition at line 397 of file item_action.cpp.
 {
     return item_action_generator::generator().action_exists( type );
 }
References item_action_generator::action_exists(), item_action_generator::generator(), and type.
Referenced by Item_factory::check_definitions().
load()
virtual void iuse_actor::load (const JsonObject & jo) pure virtual
Implemented in effect_on_conditons_actor, sew_advanced_actor, deploy_tent_actor, emit_actor, place_trap_actor, heal_actor, repair_item_actor, ammobelt_actor, holster_actor, cast_spell_actor, learn_spell_actor, musical_instrument_actor, play_instrument_iuse, manualnoise_actor, fireweapon_on_actor, fireweapon_off_actor, inscribe_actor, salvage_actor, firestarter_actor, reveal_map_actor, deploy_appliance_actor, deploy_furn_actor, place_npc_iuse, change_scent_iuse, place_monster_iuse, delayed_transform_iuse, consume_drug_iuse, explosion_iuse, sound_iuse, message_iuse, unpack_actor, iuse_transform, weigh_self_actor, link_up_actor, molle_detach_actor, molle_attach_actor, saw_stock_actor, saw_barrel_actor, modify_gunmods_actor, detach_gunmods_actor, install_bionic_actor, and iuse_function_wrapper.
Referenced by Item_factory::usage_from_object().
use()
virtual std::optional<int> iuse_actor::use (Character * , item & , const tripoint &) const pure virtual
Implemented in iuse_function_wrapper, link_up_actor, modify_gunmods_actor, detach_gunmods_actor, install_bionic_actor, molle_detach_actor, molle_attach_actor, saw_stock_actor, saw_barrel_actor, effect_on_conditons_actor, cast_spell_actor, unpack_actor, weigh_self_actor, learn_spell_actor, sew_advanced_actor, deploy_tent_actor, emit_actor, place_trap_actor, heal_actor, repair_item_actor, ammobelt_actor, holster_actor, musical_instrument_actor, play_instrument_iuse, manualnoise_actor, fireweapon_on_actor, fireweapon_off_actor, inscribe_actor, salvage_actor, firestarter_actor, reveal_map_actor, deploy_appliance_actor, deploy_furn_actor, place_npc_iuse, change_scent_iuse, place_monster_iuse, delayed_transform_iuse, consume_drug_iuse, explosion_iuse, sound_iuse, message_iuse, and iuse_transform.
Member Data Documentation
cost
int iuse_actor::cost
Units of ammo required per invocation (or use value from base item if negative)
Definition at line 265 of file iuse.h.
Referenced by saw_barrel_actor::load(), saw_stock_actor::load(), salvage_actor::load(), inscribe_actor::load(), salvage_actor::try_to_cut_up(), inscribe_actor::use(), and heal_actor::use().
type
const std::string iuse_actor::type
The type of the action.
It's not translated. Different iuse_actor instances may have the same type, but different data.
Definition at line 262 of file iuse.h.
Referenced by Item_factory::check_definitions(), salvage_actor::cut_up(), get_name(), use_function::get_type(), is_valid(), iuse_transform::use(), and repair_item_actor::use().
The documentation for this class was generated from the following files:
src/iuse.h
src/item_action.cpp