Cataclysm DDA: cardreader_examine_actor Class Reference
cardreader_examine_actor Class Reference
#include <iexamine_actors.h>
Public Member Functions
cardreader_examine_actor (const std::string &type="cardreader")
void load (const JsonObject &jo) override
void call (Character &you, const tripoint &examp) const override
Use id/hack reader.
void finalize () const override
std::unique_ptr< iexamine_actor > clone () const override
Public Member Functions inherited from iexamine_actor
iexamine_actor (const std::string &type)
virtual ~iexamine_actor ()=default
Private Member Functions
void consume_card (const std::vector< item_location > &cards) const
std::vector< item_location > get_cards (Character &you, const tripoint &examp) const
bool apply (const tripoint &examp) const
Private Attributes
std::vector< flag_id > allowed_flags
bool consume = true
bool allow_hacking = true
bool despawn_monsters = true
int radius = 3
std::map< ter_str_id, ter_str_id > terrain_changes
std::map< furn_str_id, furn_str_id > furn_changes
update_mapgen_id mapgen_id
std::optional< int > omt_allowed_radius
bool map_regen = false
bool query = true
std::string query_msg
std::string success_msg
std::string redundant_msg
Additional Inherited Members
Public Attributes inherited from iexamine_actor
const std::string type
Detailed Description
Definition at line 30 of file iexamine_actors.h.
Constructor & Destructor Documentation
cardreader_examine_actor()
cardreader_examine_actor::cardreader_examine_actor (const std::string & type = "cardreader") inline explicit
Definition at line 60 of file iexamine_actors.h.
             : iexamine_actor( type ) {}
Member Function Documentation
apply()
bool cardreader_examine_actor::apply (const tripoint & examp) const private
Definition at line 127 of file iexamine_actors.cpp.
 {
     bool open = true;
     map &here = get_map();
     if( map_regen ) {
         tripoint_abs_omt omt_pos( ms_to_omt_copy( here.getabs( examp ) ) );
         if( !run_mapgen_update_func( mapgen_id, omt_pos, {}, nullptr, false ) ) {
             debugmsg( "Failed to apply magen function %s", mapgen_id.str() );
         }
         set_queued_points();
         here.set_seen_cache_dirty( examp );
         here.set_transparency_cache_dirty( examp.z );
     } else {
         open = false;
         const tripoint_range<tripoint> points = here.points_in_radius( examp, radius );
         for( const tripoint &tmp : points ) {
             const auto ter_iter = terrain_changes.find( here.ter( tmp ).id() );
             const auto furn_iter = furn_changes.find( here.furn( tmp ).id() );
             if( ter_iter != terrain_changes.end() ) {
                 here.ter_set( tmp, ter_iter->second );
                 open = true;
             }
             if( furn_iter != furn_changes.end() ) {
                 here.furn_set( tmp, furn_iter->second );
                 open = true;
             }
         }
     }
     return open;
 }
References debugmsg, map::furn(), furn_changes, map::furn_set(), get_map(), map::getabs(), int_id< T >::id(), map_regen, mapgen_id, ms_to_omt_copy(), open(), map::points_in_radius(), radius, run_mapgen_update_func(), set_queued_points(), map::set_seen_cache_dirty(), map::set_transparency_cache_dirty(), string_id< T >::str(), map::ter(), map::ter_set(), terrain_changes, and tripoint::z.
Referenced by call().
call()
void cardreader_examine_actor::call (Character & you, const tripoint & examp) const override virtual
Use id/hack reader.
Using an id despawns turrets.
Implements iexamine_actor.
Definition at line 163 of file iexamine_actors.cpp.
 {
     bool open = false;
     map &here = get_map();
     std::vector<item_location> cards = get_cards( you, examp );
     if( !cards.empty() && query_yn( _( query_msg ) ) ) {
         you.mod_moves( -to_moves<int>( 1_seconds ) );
         open = apply( examp );
         for( monster &critter : g->all_monsters() ) {
             if( !despawn_monsters ) {
                 break;
             }
             // Check 1) same overmap coords, 2) turret, 3) hostile
             if( ms_to_omt_copy( here.getabs( critter.pos() ) ) == ms_to_omt_copy( here.getabs( examp ) ) &&
                 critter.has_flag( mon_flag_ID_CARD_DESPAWN ) &&
                 critter.attitude_to( you ) == Creature::Attitude::HOSTILE ) {
                 g->remove_zombie( critter );
             }
         }
         if( open ) {
             add_msg( _( success_msg ) );
             consume_card( cards );
         } else {
             add_msg( _( redundant_msg ) );
         }
     } else if( allow_hacking && iexamine::can_hack( you ) &&
                query_yn( _( "Attempt to hack this card-reader?" ) ) ) {
         iexamine::try_start_hacking( you, examp );
     }
 }
References _, add_msg(), allow_hacking, apply(), iexamine::can_hack(), consume_card(), despawn_monsters, g, get_cards(), get_map(), map::getabs(), Creature::HOSTILE, Creature::mod_moves(), mon_flag_ID_CARD_DESPAWN, ms_to_omt_copy(), open(), query_msg, query_yn(), redundant_msg, success_msg, and iexamine::try_start_hacking().
clone()
std::unique_ptr< iexamine_actor > cardreader_examine_actor::clone () const override virtual
Implements iexamine_actor.
Definition at line 245 of file iexamine_actors.cpp.
 {
     return std::make_unique<cardreader_examine_actor>( *this );
 }
consume_card()
void cardreader_examine_actor::consume_card (const std::vector< item_location > & cards) const private
Definition at line 65 of file iexamine_actors.cpp.
 {
     if( !consume ) {
         return;
     }
     std::vector<item_location> opts;
     for( const item_location &it : cards ) {
         const auto stacks = [&it]( const item_location & compare ) {
             return it->stacks_with( *compare );
         };
         if( std::any_of( opts.begin(), opts.end(), stacks ) ) {
             continue;
         }
         opts.push_back( it );
     }
     if( opts.size() == 1 ) {
         opts[0].remove_item();
         return;
     }
     uilist query;
     query.text = _( "Use which item?" );
     query.allow_cancel = false;
     for( size_t i = 0; i < opts.size(); ++i ) {
         query.entries.emplace_back( static_cast<int>( i ), true, -1, opts[i]->tname() );
     }
     query.query();
     opts[query.ret].remove_item();
 }
References _, game_menus::inv::compare(), consume, and query.
Referenced by call().
finalize()
void cardreader_examine_actor::finalize () const override virtual
Implements iexamine_actor.
Definition at line 218 of file iexamine_actors.cpp.
 {
     if( allowed_flags.empty() ) {
         debugmsg( "Cardreader examine actor has no allowed card flags." );
     }
     for( const flag_id &flag : allowed_flags ) {
         if( !flag.is_valid() ) {
             debugmsg( "Cardreader uses flag %s that does not exist!", flag.str() );
         }
     }
     if( terrain_changes.empty() && furn_changes.empty() && mapgen_id.is_empty() ) {
         debugmsg( "Cardreader examine actor does not change either terrain or furniture" );
     }
     if( query && query_msg.empty() ) {
         debugmsg( "Cardreader is told to query, yet does not have a query message defined." );
     }
     if( allow_hacking && ( !furn_changes.empty() || terrain_changes.size() != 1 ||
                            terrain_changes.count( ter_t_door_metal_locked ) != 1 ||
                            terrain_changes.at( ter_t_door_metal_locked ) != ter_t_door_metal_c ) ) {
         debugmsg( "Cardreader allows hacking, but activities different that if hacked." );
     }
 }
References allow_hacking, allowed_flags, debugmsg, furn_changes, string_id< T >::is_empty(), mapgen_id, query, query_msg, ter_t_door_metal_c, ter_t_door_metal_locked, and terrain_changes.
get_cards()
std::vector< item_location > cardreader_examine_actor::get_cards (Character & you, const tripoint & examp) const private
Definition at line 96 of file iexamine_actors.cpp.
 {
     std::vector<item_location> ret;
     for( const item_location &it : you.all_items_loc() ) {
         const auto has_card_flag = [&it]( const flag_id & flag ) {
             return it->has_flag( flag );
         };
         if( std::none_of( allowed_flags.begin(), allowed_flags.end(), has_card_flag ) ) {
             continue;
         }
         if( omt_allowed_radius ) {
             tripoint cardloc = it->get_var( "spawn_location_omt", tripoint_min );
             // Cards without a location are treated as valid
             if( cardloc == tripoint_min ) {
                 ret.push_back( it );
                 continue;
             }
             int dist = rl_dist( cardloc.xy(), ms_to_omt_copy( get_map().getabs( examp ) ).xy() );
             if( dist > *omt_allowed_radius ) {
                 continue;
             }
         }
         ret.push_back( it );
     }
     return ret;
 }
References Character::all_items_loc(), allowed_flags, get_map(), ms_to_omt_copy(), omt_allowed_radius, cata::hash64_detail::ret, rl_dist(), tripoint_min, and tripoint::xy().
Referenced by call().
load()
void cardreader_examine_actor::load (const JsonObject & jo) override virtual
Implements iexamine_actor.
Definition at line 196 of file iexamine_actors.cpp.
 {
     mandatory( jo, false, "flags", allowed_flags );
     optional( jo, false, "consume_card", consume, true );
     optional( jo, false, "allow_hacking", allow_hacking, true );
     optional( jo, false, "despawn_monsters", despawn_monsters, true );
     optional( jo, false, "omt_allowed_radius", omt_allowed_radius );
     if( jo.has_string( "mapgen_id" ) ) {
         optional( jo, false, "mapgen_id", mapgen_id );
         map_regen = true;
     } else {
         optional( jo, false, "radius", radius, 3 );
         optional( jo, false, "terrain_changes", terrain_changes );
         optional( jo, false, "furn_changes", furn_changes );
     }
     optional( jo, false, "query", query, true );
     optional( jo, false, "query_msg", query_msg );
     mandatory( jo, false, "success_msg", success_msg );
     mandatory( jo, false, "redundant_msg", redundant_msg );
 }
References allow_hacking, allowed_flags, consume, despawn_monsters, furn_changes, JsonObject::has_string(), mandatory, map_regen, mapgen_id, omt_allowed_radius, optional(), query, query_msg, radius, redundant_msg, success_msg, and terrain_changes.
Member Data Documentation
allow_hacking
bool cardreader_examine_actor::allow_hacking = true private
Definition at line 35 of file iexamine_actors.h.
Referenced by call(), finalize(), and load().
allowed_flags
std::vector<flag_id> cardreader_examine_actor::allowed_flags private
Definition at line 33 of file iexamine_actors.h.
Referenced by finalize(), get_cards(), and load().
consume
bool cardreader_examine_actor::consume = true private
Definition at line 34 of file iexamine_actors.h.
Referenced by consume_card(), and load().
despawn_monsters
bool cardreader_examine_actor::despawn_monsters = true private
Definition at line 36 of file iexamine_actors.h.
Referenced by call(), and load().
furn_changes
std::map<furn_str_id, furn_str_id> cardreader_examine_actor::furn_changes private
Definition at line 41 of file iexamine_actors.h.
Referenced by apply(), finalize(), and load().
map_regen
bool cardreader_examine_actor::map_regen = false private
Definition at line 47 of file iexamine_actors.h.
Referenced by apply(), and load().
mapgen_id
update_mapgen_id cardreader_examine_actor::mapgen_id private
Definition at line 43 of file iexamine_actors.h.
Referenced by apply(), finalize(), and load().
omt_allowed_radius
std::optional<int> cardreader_examine_actor::omt_allowed_radius private
Definition at line 45 of file iexamine_actors.h.
Referenced by get_cards(), and load().
query
bool cardreader_examine_actor::query = true private
Definition at line 49 of file iexamine_actors.h.
Referenced by consume_card(), finalize(), and load().
query_msg
std::string cardreader_examine_actor::query_msg private
Definition at line 50 of file iexamine_actors.h.
Referenced by call(), finalize(), and load().
radius
int cardreader_examine_actor::radius = 3 private
Definition at line 39 of file iexamine_actors.h.
Referenced by apply(), and load().
redundant_msg
std::string cardreader_examine_actor::redundant_msg private
Definition at line 53 of file iexamine_actors.h.
Referenced by call(), and load().
success_msg
std::string cardreader_examine_actor::success_msg private
Definition at line 52 of file iexamine_actors.h.
Referenced by call(), and load().
terrain_changes
std::map<ter_str_id, ter_str_id> cardreader_examine_actor::terrain_changes private
Definition at line 40 of file iexamine_actors.h.
Referenced by apply(), finalize(), and load().
The documentation for this class was generated from the following files:
src/iexamine_actors.h
src/iexamine_actors.cpp