Cataclysm DDA: overmap_connection Class Reference
overmap_connection Class Reference
#include <overmap_connection.h>
Classes
struct cache
class subtype
Public Member Functions
const subtype * pick_subtype_for (const int_id< oter_t > &ground) const
bool has (const int_id< oter_t > &oter) const
void load (const JsonObject &jo, std::string_view src)
void check () const
void finalize ()
Public Attributes
string_id< overmap_connection > id
std::vector< std::pair< string_id< overmap_connection >, mod_id > > src
bool was_loaded = false
Private Attributes
std::list< subtype > subtypes
std::vector< cache > cached_subtypes
Detailed Description
Definition at line 17 of file overmap_connection.h.
Member Function Documentation
check()
void overmap_connection::check () const
Definition at line 106 of file overmap_connection.cpp.
 {
     if( subtypes.empty() ) {
         debugmsg( "Overmap connection \"%s\" doesn't have subtypes.", id.c_str() );
     }
     for( const overmap_connection::subtype &subtype : subtypes ) {
         if( !subtype.terrain.is_valid() ) {
             debugmsg( "In overmap connection \"%s\", terrain \"%s\" is invalid.", id.c_str(),
                       subtype.terrain.c_str() );
         }
         for( const auto &location : subtype.locations ) {
             if( !location.is_valid() ) {
                 debugmsg( "In overmap connection \"%s\", location \"%s\" is invalid.", id.c_str(),
                           location.c_str() );
             }
         }
     }
 }
References string_id< T >::c_str(), debugmsg, string_id< T >::is_valid(), location, overmap_connection::subtype::locations, subtypes, and overmap_connection::subtype::terrain.
finalize()
void overmap_connection::finalize ()
Definition at line 125 of file overmap_connection.cpp.
 {
     cached_subtypes.resize( overmap_terrains::get_all().size() );
 }
References cached_subtypes, overmap_terrains::get_all(), and om_direction::size.
Referenced by overmap_connections::finalize().
has()
bool overmap_connection::has (const int_id< oter_t > & oter) const
Definition at line 94 of file overmap_connection.cpp.
 {
     return std::find_if( subtypes.cbegin(), subtypes.cend(), [&oter]( const subtype & elem ) {
         return oter->type_is( elem.terrain );
     } ) != subtypes.cend();
 }
References subtypes.
Referenced by overmap::build_connection(), overmap::lay_out_connection(), and overmap::lay_out_street().
load()
void overmap_connection::load (const JsonObject & jo, std::string_view src)
Definition at line 101 of file overmap_connection.cpp.
 {
     mandatory( jo, false, "subtypes", subtypes );
 }
References mandatory, and subtypes.
Referenced by overmap_connection::subtype::deserialize().
pick_subtype_for()
const overmap_connection::subtype * overmap_connection::pick_subtype_for (const int_id< oter_t > & ground) const
Definition at line 67 of file overmap_connection.cpp.
 {
     if( !ground ) {
         return nullptr;
     }
     const size_t cache_index = ground.to_i();
     cata_assert( cache_index < cached_subtypes.size() );
     if( cached_subtypes[cache_index] ) {
         return cached_subtypes[cache_index].value;
     }
     const auto iter = std::find_if( subtypes.cbegin(),
     subtypes.cend(), [&ground]( const subtype & elem ) {
         return elem.allows_terrain( ground );
     } );
     const overmap_connection::subtype *result = iter != subtypes.cend() ? &*iter : nullptr;
     cached_subtypes[cache_index].value = result;
     cached_subtypes[cache_index].assigned = true;
     return result;
 }
References cached_subtypes, cata_assert, ground, and subtypes.
Referenced by overmap::build_connection(), overmap::lay_out_connection(), and overmap::lay_out_street().
Member Data Documentation
cached_subtypes
std::vector<cache> overmap_connection::cached_subtypes mutable private
Definition at line 69 of file overmap_connection.h.
Referenced by finalize(), and pick_subtype_for().
id
string_id<overmap_connection> overmap_connection::id
Definition at line 55 of file overmap_connection.h.
Referenced by overmap::build_connection().
src
std::vector<std::pair<string_id<overmap_connection>, mod_id> > overmap_connection::src
Definition at line 56 of file overmap_connection.h.
Referenced by overmap_connections::load().
subtypes
std::list<subtype> overmap_connection::subtypes private
Definition at line 68 of file overmap_connection.h.
Referenced by check(), has(), load(), and pick_subtype_for().
was_loaded
bool overmap_connection::was_loaded = false
Definition at line 57 of file overmap_connection.h.
The documentation for this class was generated from the following files:
src/overmap_connection.h
src/overmap_connection.cpp