Cataclysm DDA: play_with_pet_activity_actor Class Reference
play_with_pet_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
play_with_pet_activity_actor ()=default
play_with_pet_activity_actor (const std::string &pet_name)
play_with_pet_activity_actor (const std::string &pet_name, const std::string &playstr)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
std::string pet_name
std::string playstr
Detailed Description
Definition at line 1436 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
play_with_pet_activity_actor() [1/3]
play_with_pet_activity_actor::play_with_pet_activity_actor () default
Referenced by deserialize().
play_with_pet_activity_actor() [2/3]
play_with_pet_activity_actor::play_with_pet_activity_actor (const std::string & pet_name) inline explicit
Definition at line 1443 of file activity_actor_definitions.h.
                                                                            :
             pet_name( pet_name ) {};
play_with_pet_activity_actor() [3/3]
play_with_pet_activity_actor::play_with_pet_activity_actor (const std::string & pet_name, const std::string & playstr) inline explicit
Definition at line 1445 of file activity_actor_definitions.h.
                                                                                                      :
             pet_name( pet_name ), playstr( playstr ) {};
Member Function Documentation
clone()
std::unique_ptr<activity_actor> play_with_pet_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1455 of file activity_actor_definitions.h.
{
             return std::make_unique<play_with_pet_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > play_with_pet_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 5620 of file activity_actor.cpp.
 {
     play_with_pet_activity_actor actor = play_with_pet_activity_actor();
     JsonObject data = jsin.get_object();
     data.read( "pet_name", actor.pet_name );
     data.read( "playstr", actor.playstr );
     return actor.clone();
 }
References clone(), JsonValue::get_object(), pet_name, play_with_pet_activity_actor(), playstr, and JsonObject::read().
do_turn()
void play_with_pet_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1452 of file activity_actor_definitions.h.
 {}
finish()
void play_with_pet_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 5599 of file activity_actor.cpp.
 {
     who.add_morale( MORALE_PLAY_WITH_PET, rng( 3, 10 ), 10, 5_hours, 25_minutes );
     if( !playstr.empty() ) {
         who.add_msg_if_player( m_good, playstr, pet_name );
     }
     who.add_msg_if_player( m_good, _( "Playing with your %s has lifted your spirits a bit." ),
                            pet_name );
     act.set_to_null();
 }
References _, act, Character::add_morale(), Character::add_msg_if_player(), m_good, MORALE_PLAY_WITH_PET, pet_name, playstr, and rng().
get_type()
activity_id play_with_pet_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1447 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_PLAY_WITH_PET" );
         }
References activity_id.
serialize()
void play_with_pet_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 5612 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "pet_name", pet_name );
     jsout.member( "playstr", playstr );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), pet_name, playstr, and JsonOut::start_object().
start()
void play_with_pet_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 5593 of file activity_actor.cpp.
 {
     act.moves_total = rng( 50, 125 ) * 100;
     act.moves_left = act.moves_total;
 }
References act, and rng().
Member Data Documentation
pet_name
std::string play_with_pet_activity_actor::pet_name private
Definition at line 1439 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
playstr
std::string play_with_pet_activity_actor::playstr private
Definition at line 1440 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp