Cataclysm DDA: monfaction Class Reference
monfaction Class Reference
#include <monfaction.h>
Public Member Functions
mf_attitude attitude (const mfaction_id &other) const
bool is_root () const
Public Attributes
mfaction_str_id id = mfaction_str_id::NULL_ID()
std::vector< std::pair< mfaction_str_id, mod_id > > src
mfaction_str_id base_faction = mfaction_str_id::NULL_ID()
Private Member Functions
std::optional< mf_attitude > attitude_rec (const mfaction_str_id &other) const
bool detect_base_faction_cycle () const
void inherit_parent_attitude_rec (std::set< mfaction_str_id > &processed, std::map< mfaction_str_id, mf_attitude > &child_attitudes) const
void populate_attitude_vec () const
void load (const JsonObject &jo, std::string_view src)
Load from JSON.
Private Attributes
bool was_loaded = false
mfaction_att_map attitude_map
std::set< mfaction_str_id > _att_by_mood
std::set< mfaction_str_id > _att_neutral
std::set< mfaction_str_id > _att_friendly
std::set< mfaction_str_id > _att_hate
mfaction_att_vec attitude_vec
Friends
class generic_factory< monfaction >
void monfactions::finalize ()
Detailed Description
Definition at line 48 of file monfaction.h.
Member Function Documentation
attitude()
mf_attitude monfaction::attitude (const mfaction_id & other) const
Definition at line 62 of file monfaction.cpp.
 {
     int idx = other.to_i();
     if( idx < 0 || idx >= static_cast<int>( attitude_vec.size() ) ) {
         debugmsg( "Invalid mfaction_id in the attitude check: %d", idx );
         return MFA_FRIENDLY;
     }
     return static_cast<mf_attitude>( attitude_vec[other.to_i()] );
 }
References attitude_vec, debugmsg, MFA_FRIENDLY, and other.
Referenced by attitude_rec(), populate_attitude_vec(), and monster::process_effects().
attitude_rec()
std::optional< mf_attitude > monfaction::attitude_rec (const mfaction_str_id & other) const private
Definition at line 72 of file monfaction.cpp.
 {
     const auto &found = attitude_map.find( other );
     if( found != attitude_map.end() ) {
         return found->second;
     }
     if( !other->is_root() ) {
         return attitude( other->base_faction );
     }
     return std::nullopt;
 }
References attitude(), attitude_map, and other.
Referenced by populate_attitude_vec().
detect_base_faction_cycle()
bool monfaction::detect_base_faction_cycle () const private
Definition at line 96 of file monfaction.cpp.
 {
     std::list<mfaction_str_id> parents_path;
     std::set<mfaction_str_id> parents;
     mfaction_str_id cur = id;
     while( !cur->is_root() ) {
         parents_path.push_back( cur );
         // cycle detected!
         if( parents.count( cur ) ) {
             debugmsg( "In MONSTER_FACTION '%s': detected a cycle in base_faction relations: %s",
             this -> id.str(), debug_menu::iterable_to_string( parents_path, " -> ", []( const auto & el ) {
                 return el.str();
             } ) );
             return true;
         }
         parents.insert( cur );
         cur = cur->base_faction;
     }
     return false;
 }
References base_faction, debugmsg, id, is_root(), and debug_menu::iterable_to_string().
inherit_parent_attitude_rec()
void monfaction::inherit_parent_attitude_rec (std::set< mfaction_str_id > & processed, std::map< mfaction_str_id, mf_attitude > & child_attitudes) const private
Definition at line 118 of file monfaction.cpp.
 {
     // already processed, just populate the return list and exit
     if( !processed.count( id ) ) {
         if( !is_root() ) {
             base_faction->inherit_parent_attitude_rec( processed, child_attitudes );
         }
         // wish we had 'map::merge'
         for( const auto &ci : child_attitudes ) {
             attitude_map.emplace( ci.first, ci.second );
         }
     }
     for( const auto &att : attitude_map ) {
         // child attitude settings overwrite those of a parent
         child_attitudes[att.first] = att.second;
     }
     processed.insert( id );
 }
References attitude_map, base_faction, inherit_parent_attitude_rec(), and is_root().
Referenced by inherit_parent_attitude_rec().
is_root()
bool monfaction::is_root () const
Definition at line 57 of file monfaction.cpp.
 {
     return id == base_faction;
 }
References base_faction.
Referenced by detect_base_faction_cycle(), and inherit_parent_attitude_rec().
load()
void monfaction::load (const JsonObject & jo, std::string_view src) private
Load from JSON.
Definition at line 185 of file monfaction.cpp.
 {
     optional( jo, was_loaded, "base_faction", base_faction, mfaction_str_id() );
     optional( jo, was_loaded, "by_mood", _att_by_mood, string_id_reader<monfaction>() );
     optional( jo, was_loaded, "neutral", _att_neutral, string_id_reader<monfaction>() );
     optional( jo, was_loaded, "friendly", _att_friendly, string_id_reader<monfaction>() );
     optional( jo, was_loaded, "hate", _att_hate, string_id_reader<monfaction>() );
     attitude_map.clear();
     for( const mfaction_str_id &mfac : _att_by_mood ) {
         attitude_map[mfac] = MFA_BY_MOOD;
     }
     for( const mfaction_str_id &mfac : _att_neutral ) {
         attitude_map[mfac] = MFA_NEUTRAL;
     }
     for( const mfaction_str_id &mfac : _att_friendly ) {
         attitude_map[mfac] = MFA_FRIENDLY;
     }
     for( const mfaction_str_id &mfac : _att_hate ) {
         attitude_map[mfac] = MFA_HATE;
     }
     // by default faction is friendly to itself (don't overwrite if explicitly specified)
     attitude_map.emplace( id, MFA_FRIENDLY );
 }
References _att_by_mood, _att_friendly, _att_hate, _att_neutral, attitude_map, base_faction, MFA_BY_MOOD, MFA_FRIENDLY, MFA_HATE, MFA_NEUTRAL, optional(), and was_loaded.
populate_attitude_vec()
void monfaction::populate_attitude_vec () const private
Definition at line 139 of file monfaction.cpp.
 {
     attitude_vec.clear();
     for( const monfaction &f : faction_factory.get_all() ) {
         const std::optional<mf_attitude> &attitude = attitude_rec( f.id );
         if( !attitude ) {
             debugmsg( "Invalid faction relations (no relation found): %s -> %s",
                       id.c_str(), f.id.c_str() );
         }
         attitude_vec.push_back( attitude.value_or( MFA_FRIENDLY ) );
     }
     attitude_vec.shrink_to_fit();
 }
References attitude(), attitude_rec(), attitude_vec, debugmsg, faction_factory, and MFA_FRIENDLY.
Friends And Related Function Documentation
generic_factory< monfaction >
friend class generic_factory< monfaction > friend
Definition at line 96 of file monfaction.h.
monfactions::finalize
void monfactions::finalize () friend
Member Data Documentation
_att_by_mood
std::set<mfaction_str_id> monfaction::_att_by_mood private
Definition at line 69 of file monfaction.h.
Referenced by load().
_att_friendly
std::set<mfaction_str_id> monfaction::_att_friendly private
Definition at line 71 of file monfaction.h.
Referenced by load().
_att_hate
std::set<mfaction_str_id> monfaction::_att_hate private
Definition at line 72 of file monfaction.h.
Referenced by load().
_att_neutral
std::set<mfaction_str_id> monfaction::_att_neutral private
Definition at line 70 of file monfaction.h.
Referenced by load().
attitude_map
mfaction_att_map monfaction::attitude_map mutable private
Definition at line 68 of file monfaction.h.
Referenced by attitude_rec(), inherit_parent_attitude_rec(), and load().
attitude_vec
mfaction_att_vec monfaction::attitude_vec mutable private
Definition at line 77 of file monfaction.h.
Referenced by attitude(), and populate_attitude_vec().
base_faction
mfaction_str_id monfaction::base_faction = mfaction_str_id::NULL_ID()
Definition at line 61 of file monfaction.h.
Referenced by detect_base_faction_cycle(), inherit_parent_attitude_rec(), is_root(), and load().
id
mfaction_str_id monfaction::id = mfaction_str_id::NULL_ID()
Definition at line 59 of file monfaction.h.
Referenced by detect_base_faction_cycle().
src
std::vector<std::pair<mfaction_str_id, mod_id> > monfaction::src
Definition at line 60 of file monfaction.h.
was_loaded
bool monfaction::was_loaded = false private
Definition at line 65 of file monfaction.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/monfaction.h
src/monfaction.cpp