Cataclysm DDA: panel_layout Class Reference
panel_layout Class Reference
#include <panels.h>
Public Member Functions
panel_layout (const translation &_name, const std::vector< window_panel > &_panels)
std::string name () const
const std::vector< window_panel > & panels () const
std::vector< window_panel > & panels ()
Private Attributes
translation _name
std::vector< window_panel > _panels
Detailed Description
Definition at line 105 of file panels.h.
Constructor & Destructor Documentation
panel_layout()
panel_layout::panel_layout (const translation & _name, const std::vector< window_panel > & _panels)
Definition at line 143 of file panels.cpp.
     : _name( _name ), _panels( _panels )
 {
 }
Member Function Documentation
name()
std::string panel_layout::name () const
Definition at line 148 of file panels.cpp.
 {
     return _name.translated();
 }
References _name, and translation::translated().
Referenced by panel_manager::get_current_sidebar(), and panel_manager::show_adm().
panels() [1/2]
std::vector< window_panel > & panel_layout::panels ()
Definition at line 158 of file panels.cpp.
 {
     return _panels;
 }
References _panels.
panels() [2/2]
const std::vector< window_panel > & panel_layout::panels () const
Definition at line 153 of file panels.cpp.
 {
     return _panels;
 }
References _panels.
Referenced by game::draw_panels(), game::look_around(), and panel_manager::show_adm().
Member Data Documentation
_name
translation panel_layout::_name private
Definition at line 115 of file panels.h.
Referenced by name().
_panels
std::vector<window_panel> panel_layout::_panels private
Definition at line 116 of file panels.h.
Referenced by panels().
The documentation for this class was generated from the following files:
src/panels.h
src/panels.cpp