Cataclysm DDA: json_loader Class Reference
json_loader Class Reference
#include <json_loader.h>
Static Public Member Functions
static JsonValue from_path (const cata_path &source_file) noexcept(false)
static JsonValue from_path_at_offset (const cata_path &source_file, size_t offset=0) noexcept(false)
static std::optional< JsonValue > from_path_opt (const cata_path &source_file) noexcept(false)
static std::optional< JsonValue > from_path_at_offset_opt (const cata_path &source_file, size_t offset=0) noexcept(false)
static JsonValue from_string (std::string const &data) noexcept(false)
static std::optional< JsonValue > from_string_opt (std::string const &data) noexcept(false)
Detailed Description
Definition at line 10 of file json_loader.h.
Member Function Documentation
from_path()
JsonValue json_loader::from_path (const cata_path & source_file) static noexcept
Definition at line 149 of file json_loader.cpp.
 {
     return from_path_at_offset( source_file, 0 );
 }
Referenced by past_achievements_info::load(), safemode::load(), color_loader< ColorType >::load_colorfile(), DynamicDataLoader::load_data_from_path(), worldfactory::load_last_world_info(), item_pocket::load_presets(), and read_from_file_json().
from_path_at_offset()
JsonValue json_loader::from_path_at_offset (const cata_path & source_file, size_t offset = 0) static noexcept
Definition at line 133 of file json_loader.cpp.
 {
     fs::path unrelative_path = source_file.get_unrelative_path();
     if( !file_exist( unrelative_path ) ) {
         throw JsonError( unrelative_path.generic_u8string() + " does not exist." );
     }
     auto obj = from_path_at_offset_opt_impl( source_file, offset );
     if( !obj ) {
         throw JsonError( "Json file " + unrelative_path.generic_u8string() +
                          " did not contain valid json" );
     }
     return std::move( *obj );
 }
References file_exist(), anonymous_namespace{json_loader.cpp}::from_path_at_offset_opt_impl(), and int_id< T >::obj().
Referenced by npc::import_and_clean(), overmap::unserialize(), game::unserialize(), game::unserialize_master(), and overmap::unserialize_view().
from_path_at_offset_opt()
std::optional< JsonValue > json_loader::from_path_at_offset_opt (const cata_path & source_file, size_t offset = 0) static noexcept
Definition at line 118 of file json_loader.cpp.
 {
     if( !file_exist( source_file.get_unrelative_path() ) ) {
         return std::nullopt;
     }
     return from_path_at_offset_opt_impl( source_file, offset );
 }
References file_exist(), and anonymous_namespace{json_loader.cpp}::from_path_at_offset_opt_impl().
from_path_opt()
std::optional< JsonValue > json_loader::from_path_opt (const cata_path & source_file) static noexcept
Definition at line 127 of file json_loader.cpp.
 {
     return from_path_at_offset_opt( source_file, 0 );
 }
Referenced by input_manager::load().
from_string()
JsonValue json_loader::from_string (std::string const & data) static noexcept
Definition at line 154 of file json_loader.cpp.
 {
     std::shared_ptr<parsed_flexbuffer> buffer = flexbuffer_cache::parse_buffer( data );
     if( !buffer ) {
         throw JsonError( "Failed to parse string into json" );
     }
     flexbuffers::Reference buffer_root = flexbuffer_root_from_storage( buffer->get_storage() );
     return JsonValue( std::move( buffer ), buffer_root, nullptr, 0 );
 }
References flexbuffer_root_from_storage(), and flexbuffer_cache::parse_buffer().
Referenced by deserialize_wrapper(), memorial_logger::load(), and vehicle::restore_folded_parts().
from_string_opt()
std::optional< JsonValue > json_loader::from_string_opt (std::string const & data) static noexcept
Definition at line 165 of file json_loader.cpp.
 {
     std::optional<JsonValue> ret;
     try {
         ret = from_string( data );
     } catch( JsonError &e ) {
         ret = std::nullopt;
     }
     return ret;
 }
References cata::hash64_detail::ret.
Referenced by item::read_extended_photos().
The documentation for this class was generated from the following files:
src/json_loader.h
src/json_loader.cpp