Cataclysm DDA: window_panel Class Reference
window_panel Class Reference
#include <panels.h>
Public Member Functions
window_panel (const std::function< void(const draw_args &)> &draw_func, const std::string &id, const translation &nm, int ht, int wd, bool default_toggle_, const std::function< bool()> &render_func=default_render, bool force_draw=false)
window_panel (const std::string &id, const translation &nm, int ht, int wd, bool default_toggle_, const std::function< bool()> &render_func=default_render, bool force_draw=false)
int get_height () const
int get_width () const
const std::string & get_id () const
std::string get_name () const
void set_widget (const widget_id &w)
const widget_id & get_widget () const
void set_draw_func (const std::function< int(const draw_args &)> &draw_func)
Public Attributes
std::function< int(const draw_args &)> draw
std::function< bool()> render
bool toggle
bool always_draw
Private Attributes
int height
int width
widget_id wgt
std::string id
translation name
Detailed Description
Definition at line 70 of file panels.h.
Constructor & Destructor Documentation
window_panel() [1/2]
window_panel::window_panel (const std::function< void(const draw_args &)> & draw_func, const std::string & id, const translation & nm, int ht, int wd, bool default_toggle_, const std::function< bool()> & render_func = default_render, bool force_draw = false)
Definition at line 49 of file panels.cpp.
     : draw( [draw_func]( const draw_args & d ) -> int { draw_func( d ); return 0; } ),
       render( render_func ), toggle( default_toggle_ ), always_draw( force_draw ),
       height( ht ), width( wd ), id( id ), name( nm )
 {
     wgt = widget_id::NULL_ID();
 }
window_panel() [2/2]
window_panel::window_panel (const std::string & id, const translation & nm, int ht, int wd, bool default_toggle_, const std::function< bool()> & render_func = default_render, bool force_draw = false)
Definition at line 61 of file panels.cpp.
     : draw( []( const draw_args & ) -> int { return 0; } ),
       render( render_func ), toggle( default_toggle_ ), always_draw( force_draw ),
       height( ht ), width( wd ), id( id ), name( nm )
 {
     wgt = widget_id::NULL_ID();
 }
Member Function Documentation
get_height()
int window_panel::get_height () const
Definition at line 96 of file panels.cpp.
 {
     if( height == -1 ) {
         if( pixel_minimap_option ) {
             return  get_option<int>( "PIXEL_MINIMAP_HEIGHT" ) > 0 ?
                     get_option<int>( "PIXEL_MINIMAP_HEIGHT" ) :
                     width / 2;
         } else {
             return 0;
         }
     }
     if( wgt.is_valid() ) {
         return get_wgt_height( wgt );
     }
     return height;
 }
References get_wgt_height(), height, string_id< T >::is_valid(), pixel_minimap_option, wgt, and width.
get_id()
const std::string & window_panel::get_id () const
Definition at line 118 of file panels.cpp.
 {
     return id;
 }
References id.
get_name()
std::string window_panel::get_name () const
Definition at line 123 of file panels.cpp.
 {
     return name.translated();
 }
References name, and translation::translated().
get_widget()
const widget_id & window_panel::get_widget () const
Definition at line 133 of file panels.cpp.
 {
     return wgt;
 }
References wgt.
get_width()
int window_panel::get_width () const
Definition at line 113 of file panels.cpp.
 {
     return width;
 }
References width.
set_draw_func()
void window_panel::set_draw_func (const std::function< int(const draw_args &)> & draw_func)
Definition at line 138 of file panels.cpp.
 {
     draw = draw_func;
 }
References draw.
Referenced by widget::get_window_panel().
set_widget()
void window_panel::set_widget (const widget_id & w)
Definition at line 128 of file panels.cpp.
 {
     wgt = w;
 }
References wgt.
Referenced by widget::get_window_panel().
Member Data Documentation
always_draw
bool window_panel::always_draw
Definition at line 93 of file panels.h.
draw
std::function<int(const draw_args &)> window_panel::draw
Definition at line 82 of file panels.h.
Referenced by set_draw_func().
height
int window_panel::height private
Definition at line 96 of file panels.h.
Referenced by get_height().
id
std::string window_panel::id private
Definition at line 99 of file panels.h.
Referenced by get_id().
name
translation window_panel::name private
Definition at line 100 of file panels.h.
Referenced by get_name().
render
std::function<bool()> window_panel::render
Definition at line 83 of file panels.h.
toggle
bool window_panel::toggle
Definition at line 92 of file panels.h.
Referenced by panel_manager::deserialize().
wgt
widget_id window_panel::wgt private
Definition at line 98 of file panels.h.
Referenced by get_height(), get_widget(), and set_widget().
width
int window_panel::width private
Definition at line 97 of file panels.h.
Referenced by get_height(), and get_width().
The documentation for this class was generated from the following files:
src/panels.h
src/panels.cpp