Cataclysm DDA: haircut_activity_actor Class Reference
haircut_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
haircut_activity_actor ()=default
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &)
Detailed Description
Definition at line 1586 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
haircut_activity_actor()
haircut_activity_actor::haircut_activity_actor () default
Referenced by deserialize().
Member Function Documentation
clone()
std::unique_ptr<activity_actor> haircut_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1598 of file activity_actor_definitions.h.
{
             return std::make_unique<haircut_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > haircut_activity_actor::deserialize (JsonValue &) static
Definition at line 5999 of file activity_actor.cpp.
 {
     return haircut_activity_actor().clone();
 }
References haircut_activity_actor().
do_turn()
void haircut_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1595 of file activity_actor_definitions.h.
 {}
finish()
void haircut_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 5974 of file activity_actor.cpp.
 {
     who.add_msg_if_player( _( "You give your hair a trim." ) );
     who.add_morale( MORALE_HAIRCUT, 3, 3, 480_minutes, 3_minutes );
     if( who.is_avatar() ) {
         uilist amenu;
         amenu.title = _( "Change what?" );
         amenu.addentry( 0, true, MENU_AUTOASSIGN, _( "Change hairstyle" ) );
         amenu.addentry( 1, true, MENU_AUTOASSIGN, _( "Change facial hairstyle" ) );
         amenu.query();
         if( amenu.ret == 0 ) {
             who.customize_appearance( customize_appearance_choice::HAIR );
         } else if( amenu.ret == 1 ) {
             who.customize_appearance( customize_appearance_choice::HAIR_F );
         }
     }
     act.set_to_null();
 }
References _, act, Character::add_morale(), Character::add_msg_if_player(), uilist::addentry(), Character::customize_appearance(), HAIR, HAIR_F, Creature::is_avatar(), MENU_AUTOASSIGN, MORALE_HAIRCUT, uilist::query(), uilist::ret, and uilist::title.
get_type()
activity_id haircut_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1590 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_HAIRCUT" );
         }
References activity_id.
serialize()
void haircut_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 5994 of file activity_actor.cpp.
 {
     jsout.write_null();
 }
References JsonOut::write_null().
start()
void haircut_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 5968 of file activity_actor.cpp.
 {
     act.moves_total = to_moves<int>( 30_minutes );
     act.moves_left = act.moves_total;
 }
References act.
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp