Cataclysm DDA: enchant_cache Class Reference
enchant_cache Class Reference
#include <magic_enchantment.h>
Public Member Functions
double modify_value (enchant_vals::mod mod_val, double value) const
double modify_value (const skill_id &mod_val, double value) const
units::energy modify_value (enchant_vals::mod mod_val, units::energy value) const
units::mass modify_value (enchant_vals::mod mod_val, units::mass value) const
units::volume modify_value (enchant_vals::mod mod_val, units::volume value) const
units::temperature_delta modify_value (enchant_vals::mod mod_val, units::temperature_delta value) const
time_duration modify_value (enchant_vals::mod mod_val, time_duration value) const
void force_add (const enchantment &rhs, const Character &guy)
void force_add (const enchantment &rhs, const monster &mon)
void force_add (const enchantment &rhs)
void force_add (const enchant_cache &rhs)
void activate_passive (Character &guy) const
double get_value_add (enchant_vals::mod value) const
double get_value_multiply (enchant_vals::mod value) const
int mult_bonus (enchant_vals::mod value_type, int base_value) const
int get_skill_value_add (const skill_id &value) const
double get_skill_value_multiply (const skill_id &value) const
int skill_mult_bonus (const skill_id &value_type, int base_value) const
bool add (const enchantment &rhs, Character &you)
bool add (const enchant_cache &rhs)
bool stacks_with (const enchantment &rhs) const
void cast_enchantment_spell (Character &caster, const Creature *target, const fake_spell &sp) const
void clear ()
void cast_hit_you (Character &caster, const Creature &target) const
void cast_hit_me (Character &caster, const Creature *target) const
void serialize (JsonOut &jsout) const
void add_value_add (enchant_vals::mod value, int add_value)
void set_has (enchantment::has value)
void add_value_mult (enchant_vals::mod value, float mult_value)
void add_hit_you (const fake_spell &sp)
void add_hit_me (const fake_spell &sp)
void load (const JsonObject &jo, std::string_view src={}, const std::optional< std::string > &inline_id=std::nullopt)
bool operator== (const enchant_cache &rhs) const
Public Member Functions inherited from enchantment
void load (const JsonObject &jo, std::string_view src={}, const std::optional< std::string > &inline_id=std::nullopt, bool is_child=false)
bool is_active (const Character &guy, const item &parent) const
bool is_active (const Character &guy, bool active) const
bool is_active (const monster &mon) const
bool is_monster_relevant () const
bool active_wield () const
const std::set< trait_id > & get_mutations () const
double get_value_add (enchant_vals::mod value, const Character &guy) const
double get_value_multiply (enchant_vals::mod value, const Character &guy) const
body_part_set modify_bodyparts (const body_part_set &unmodified) const
bool modifies_bodyparts () const
void add_activation (const time_duration &dur, const fake_spell &fake)
Public Attributes
std::vector< std::pair< std::string, std::string > > details
Public Attributes inherited from enchantment
enchantment_id id
std::vector< std::pair< enchantment_id, mod_id > > src
bool was_loaded = false
std::vector< bodypart_changes > modified_bodyparts
std::set< trait_id > mutations
std::optional< emit_id > emitter
std::map< efftype_id, int > ench_effects
translation name
translation description
std::map< enchant_vals::mod, dbl_or_var > values_add
std::map< enchant_vals::mod, dbl_or_var > values_multiply
std::map< skill_id, dbl_or_var > skill_values_add
std::map< skill_id, dbl_or_var > skill_values_multiply
std::vector< fake_spell > hit_me_effect
std::vector< fake_spell > hit_you_effect
std::map< time_duration, std::vector< fake_spell > > intermittent_activation
std::pair< has, condition > active_conditions
std::function< bool(dialogue &)> dialog_condition
Private Attributes
std::map< enchant_vals::mod, double > values_add
std::map< enchant_vals::mod, double > values_multiply
std::map< skill_id, int > skill_values_add
std::map< skill_id, int > skill_values_multiply
Additional Inherited Members
Public Types inherited from enchantment
enum has { WIELD , WORN , HELD , NUM_HAS }
enum condition {
ALWAYS , ACTIVE , INACTIVE , DIALOG_CONDITION ,
NUM_CONDITION
}
Static Public Member Functions inherited from enchantment
static void load_enchantment (const JsonObject &jo, const std::string &src)
static void reset ()
static enchantment_id load_inline_enchantment (const JsonValue &jv, std::string_view src, std::string &inline_id)
Detailed Description
Definition at line 280 of file magic_enchantment.h.
Member Function Documentation
activate_passive()
void enchant_cache::activate_passive (Character & guy) const
Definition at line 999 of file magic_enchantment.cpp.
 {
     // since it's a modifier, need to remove original value from the math
     guy.mod_str_bonus( modify_value( enchant_vals::mod::STRENGTH,
                                      guy.get_str_base() ) - guy.get_str_base() );
     guy.mod_dex_bonus( modify_value( enchant_vals::mod::DEXTERITY,
                                      guy.get_dex_base() ) - guy.get_dex_base() );
     guy.mod_per_bonus( modify_value( enchant_vals::mod::PERCEPTION,
                                      guy.get_per_base() ) - guy.get_per_base() );
     guy.mod_int_bonus( modify_value( enchant_vals::mod::INTELLIGENCE,
                                      guy.get_int_base() ) - guy.get_int_base() );
     guy.mod_num_dodges_bonus( modify_value( enchant_vals::mod::BONUS_DODGE,
                                             guy.get_num_dodges_base() ) - guy.get_num_dodges_base() );
     guy.mod_num_blocks_bonus( modify_value( enchant_vals::mod::BONUS_BLOCK,
                                             guy.get_num_blocks_base() ) - guy.get_num_blocks_base() );
     if( emitter ) {
         get_map().emit_field( guy.pos(), *emitter );
     }
     for( const std::pair<efftype_id, int> eff : ench_effects ) {
         guy.add_effect( eff.first, 1_seconds, false, eff.second );
     }
     for( const std::pair<const time_duration, std::vector<fake_spell>> &activation :
          intermittent_activation ) {
         // a random approximation!
         if( one_in( to_seconds<int>( activation.first ) ) ) {
             for( const fake_spell &fake : activation.second ) {
                 fake.get_spell( guy, 0 ).cast_all_effects( guy, guy.pos() );
             }
         }
     }
 }
References Creature::add_effect(), enchant_vals::BONUS_BLOCK, enchant_vals::BONUS_DODGE, spell::cast_all_effects(), enchant_vals::DEXTERITY, map::emit_field(), enchantment::emitter, enchantment::ench_effects, Character::get_dex_base(), Character::get_int_base(), get_map(), Creature::get_num_blocks_base(), Creature::get_num_dodges_base(), Character::get_per_base(), fake_spell::get_spell(), Character::get_str_base(), enchant_vals::INTELLIGENCE, enchantment::intermittent_activation, Character::mod_dex_bonus(), Character::mod_int_bonus(), Creature::mod_num_blocks_bonus(), Creature::mod_num_dodges_bonus(), Character::mod_per_bonus(), Character::mod_str_bonus(), one_in(), enchant_vals::PERCEPTION, Creature::pos(), and enchant_vals::STRENGTH.
add() [1/2]
bool enchant_cache::add (const enchant_cache & rhs)
Definition at line 619 of file magic_enchantment.cpp.
 {
     if( !stacks_with( rhs ) ) {
         return false;
     }
     force_add( rhs );
     return true;
 }
add() [2/2]
bool enchant_cache::add (const enchantment & rhs, Character & you)
Definition at line 610 of file magic_enchantment.cpp.
 {
     if( !stacks_with( rhs ) ) {
         return false;
     }
     force_add( rhs, you );
     return true;
 }
add_hit_me()
void enchant_cache::add_hit_me (const fake_spell & sp)
Definition at line 850 of file magic_enchantment.cpp.
 {
     hit_me_effect.push_back( sp );
 }
References enchantment::hit_me_effect.
Referenced by relic_procgen_data::generate().
add_hit_you()
void enchant_cache::add_hit_you (const fake_spell & sp)
Definition at line 855 of file magic_enchantment.cpp.
 {
     hit_you_effect.push_back( sp );
 }
References enchantment::hit_you_effect.
Referenced by relic_procgen_data::generate().
add_value_add()
void enchant_cache::add_value_add (enchant_vals::mod value, int add_value)
Definition at line 840 of file magic_enchantment.cpp.
 {
     values_add[value] = add_value;
 }
References enchantment::values_add.
Referenced by relic_procgen_data::generate().
add_value_mult()
void enchant_cache::add_value_mult (enchant_vals::mod value, float mult_value)
Definition at line 845 of file magic_enchantment.cpp.
 {
     values_multiply[value] = mult_value;
 }
References enchantment::values_multiply.
Referenced by relic_procgen_data::generate().
cast_enchantment_spell()
void enchant_cache::cast_enchantment_spell (Character & caster, const Creature * target, const fake_spell & sp) const
Definition at line 1051 of file magic_enchantment.cpp.
 {
     // check the chances
     if( !one_in( sp.trigger_once_in ) ) {
         return;
     }
     if( sp.self ) {
         caster.add_msg_player_or_npc( m_good,
                                       sp.trigger_message,
                                       sp.npc_trigger_message,
                                       caster.get_name() );
         sp.get_spell( caster, sp.level ).cast_all_effects( caster, caster.pos() );
     } else  if( target != nullptr ) {
         const Creature &trg_crtr = *target;
         const spell &spell_lvl = sp.get_spell( caster, sp.level );
         if( !spell_lvl.is_valid_target( caster, trg_crtr.pos() ) ||
             !spell_lvl.is_target_in_range( caster, trg_crtr.pos() ) ) {
             return;
         }
         caster.add_msg_player_or_npc( m_good,
                                       sp.trigger_message,
                                       sp.npc_trigger_message,
                                       caster.get_name(), trg_crtr.disp_name() );
         spell_lvl.cast_all_effects( caster, trg_crtr.pos() );
     }
 }
References Character::add_msg_player_or_npc(), spell::cast_all_effects(), Creature::disp_name(), Character::get_name(), fake_spell::get_spell(), spell::is_target_in_range(), spell::is_valid_target(), fake_spell::level, m_good, fake_spell::npc_trigger_message, one_in(), Creature::pos(), fake_spell::self, fake_spell::trigger_message, and fake_spell::trigger_once_in.
cast_hit_me()
void enchant_cache::cast_hit_me (Character & caster, const Creature * target) const
Definition at line 1044 of file magic_enchantment.cpp.
 {
     for( const fake_spell &sp : hit_me_effect ) {
         cast_enchantment_spell( caster, target, sp );
     }
 }
References enchantment::hit_me_effect.
cast_hit_you()
void enchant_cache::cast_hit_you (Character & caster, const Creature & target) const
Definition at line 1037 of file magic_enchantment.cpp.
 {
     for( const fake_spell &sp : hit_you_effect ) {
         cast_enchantment_spell( caster, &target, sp );
     }
 }
References enchantment::hit_you_effect.
clear()
void enchant_cache::clear ()
Definition at line 1082 of file magic_enchantment.cpp.
 {
     //I'm trusting all of these vectors and maps to have clear functions that avoid memory leaks.
     //Fingers crossed!
     values_add.clear();
     values_multiply.clear();
     skill_values_add.clear();
     skill_values_multiply.clear();
     hit_me_effect.clear();
     hit_you_effect.clear();
     ench_effects.clear();
 }
References enchantment::ench_effects, enchantment::hit_me_effect, enchantment::hit_you_effect, enchantment::skill_values_add, enchantment::skill_values_multiply, enchantment::values_add, and enchantment::values_multiply.
force_add() [1/4]
void enchant_cache::force_add (const enchant_cache & rhs)
Definition at line 628 of file magic_enchantment.cpp.
 {
     for( const std::pair<const enchant_vals::mod, double> &pair_values :
          rhs.values_add ) {
         values_add[pair_values.first] += pair_values.second;
     }
     for( const std::pair<const enchant_vals::mod, double> &pair_values : rhs.values_multiply ) {
         // values do not multiply against each other, they add.
         // so +10% and -10% will add to 0%
         values_multiply[pair_values.first] += pair_values.second;
     }
     for( const std::pair<const skill_id, int> &pair_values :
          rhs.skill_values_add ) {
         skill_values_add[pair_values.first] += pair_values.second;
     }
     for( const std::pair<const skill_id, int> &pair_values :
          rhs.skill_values_multiply ) {
         // values do not multiply against each other, they add.
         // so +10% and -10% will add to 0%
         skill_values_multiply[pair_values.first] += pair_values.second;
     }
     hit_me_effect.insert( hit_me_effect.end(), rhs.hit_me_effect.begin(), rhs.hit_me_effect.end() );
     hit_you_effect.insert( hit_you_effect.end(), rhs.hit_you_effect.begin(), rhs.hit_you_effect.end() );
     ench_effects.insert( rhs.ench_effects.begin(), rhs.ench_effects.end() );
     if( rhs.emitter ) {
         emitter = rhs.emitter;
     }
     for( const bodypart_changes &bp : rhs.modified_bodyparts ) {
         modified_bodyparts.emplace_back( bp );
     }
     for( const trait_id &branch : rhs.mutations ) {
         mutations.emplace( branch );
     }
     for( const std::pair<const time_duration, std::vector<fake_spell>> &act_pair :
          rhs.intermittent_activation ) {
         for( const fake_spell &fake : act_pair.second ) {
             intermittent_activation[act_pair.first].emplace_back( fake );
         }
     }
 }
References bp, enchantment::emitter, enchantment::ench_effects, enchantment::hit_me_effect, enchantment::hit_you_effect, enchantment::intermittent_activation, enchantment::modified_bodyparts, enchantment::mutations, enchantment::skill_values_add, skill_values_add, enchantment::skill_values_multiply, skill_values_multiply, enchantment::values_add, values_add, enchantment::values_multiply, and values_multiply.
force_add() [2/4]
void enchant_cache::force_add (const enchantment & rhs)
Definition at line 783 of file magic_enchantment.cpp.
 {
     for( const std::pair<const enchant_vals::mod, dbl_or_var> &pair_values :
          rhs.values_add ) {
         values_add[pair_values.first] += pair_values.second.constant();
     }
     for( const std::pair<const enchant_vals::mod, dbl_or_var> &pair_values :
          rhs.values_multiply ) {
         // values do not multiply against each other, they add.
         // so +10% and -10% will add to 0%
         values_multiply[pair_values.first] += pair_values.second.constant();
     }
     for( const std::pair<const skill_id, dbl_or_var> &pair_values :
          rhs.skill_values_add ) {
         skill_values_add[pair_values.first] += pair_values.second.constant();
     }
     for( const std::pair<const skill_id, dbl_or_var> &pair_values :
          rhs.skill_values_multiply ) {
         // values do not multiply against each other, they add.
         // so +10% and -10% will add to 0%
         skill_values_multiply[pair_values.first] += pair_values.second.constant();
     }
     hit_me_effect.insert( hit_me_effect.end(), rhs.hit_me_effect.begin(), rhs.hit_me_effect.end() );
     hit_you_effect.insert( hit_you_effect.end(), rhs.hit_you_effect.begin(), rhs.hit_you_effect.end() );
     ench_effects.insert( rhs.ench_effects.begin(), rhs.ench_effects.end() );
     if( rhs.emitter ) {
         emitter = rhs.emitter;
     }
     for( const bodypart_changes &bp : rhs.modified_bodyparts ) {
         modified_bodyparts.emplace_back( bp );
     }
     for( const trait_id &branch : rhs.mutations ) {
         mutations.emplace( branch );
     }
     for( const std::pair<const time_duration, std::vector<fake_spell>> &act_pair :
          rhs.intermittent_activation ) {
         for( const fake_spell &fake : act_pair.second ) {
             intermittent_activation[act_pair.first].emplace_back( fake );
         }
     }
     details.emplace_back( rhs.name.translated(), rhs.description.translated() );
 }
References bp, enchantment::description, enchantment::emitter, enchantment::ench_effects, enchantment::hit_me_effect, enchantment::hit_you_effect, enchantment::intermittent_activation, enchantment::modified_bodyparts, enchantment::mutations, enchantment::name, enchantment::skill_values_add, enchantment::skill_values_multiply, translation::translated(), enchantment::values_add, and enchantment::values_multiply.
force_add() [3/4]
void enchant_cache::force_add (const enchantment & rhs, const Character & guy)
Definition at line 677 of file magic_enchantment.cpp.
 {
     dialogue d( get_talker_for( guy ), nullptr );
     for( const std::pair<const enchant_vals::mod, dbl_or_var> &pair_values :
          rhs.values_add ) {
         values_add[pair_values.first] += pair_values.second.evaluate( d );
     }
     for( const std::pair<const enchant_vals::mod, dbl_or_var> &pair_values :
          rhs.values_multiply ) {
         // values do not multiply against each other, they add.
         // so +10% and -10% will add to 0%
         values_multiply[pair_values.first] += pair_values.second.evaluate( d );
     }
     for( const std::pair<const skill_id, dbl_or_var> &pair_values :
          rhs.skill_values_add ) {
         skill_values_add[pair_values.first] += pair_values.second.evaluate( d );
     }
     for( const std::pair<const skill_id, dbl_or_var> &pair_values :
          rhs.skill_values_multiply ) {
         // values do not multiply against each other, they add.
         // so +10% and -10% will add to 0%
         skill_values_multiply[pair_values.first] += pair_values.second.evaluate( d );
     }
     hit_me_effect.insert( hit_me_effect.end(), rhs.hit_me_effect.begin(), rhs.hit_me_effect.end() );
     hit_you_effect.insert( hit_you_effect.end(), rhs.hit_you_effect.begin(), rhs.hit_you_effect.end() );
     ench_effects.insert( rhs.ench_effects.begin(), rhs.ench_effects.end() );
     if( rhs.emitter ) {
         emitter = rhs.emitter;
     }
     for( const bodypart_changes &bp : rhs.modified_bodyparts ) {
         modified_bodyparts.emplace_back( bp );
     }
     for( const trait_id &branch : rhs.mutations ) {
         mutations.emplace( branch );
     }
     for( const std::pair<const time_duration, std::vector<fake_spell>> &act_pair :
          rhs.intermittent_activation ) {
         for( const fake_spell &fake : act_pair.second ) {
             intermittent_activation[act_pair.first].emplace_back( fake );
         }
     }
     details.emplace_back( rhs.name.translated(), rhs.description.translated() );
 }
References bp, enchantment::description, enchantment::emitter, enchantment::ench_effects, get_talker_for(), enchantment::hit_me_effect, enchantment::hit_you_effect, enchantment::intermittent_activation, enchantment::modified_bodyparts, enchantment::mutations, enchantment::name, enchantment::skill_values_add, enchantment::skill_values_multiply, translation::translated(), enchantment::values_add, and enchantment::values_multiply.
Referenced by inventory::get_active_enchantment_cache().
force_add() [4/4]
void enchant_cache::force_add (const enchantment & rhs, const monster & mon)
Definition at line 730 of file magic_enchantment.cpp.
 {
     dialogue d( get_talker_for( mon ), nullptr );
     for( const std::pair<const enchant_vals::mod, dbl_or_var> &pair_values :
          rhs.values_add ) {
         values_add[pair_values.first] += pair_values.second.evaluate( d );
     }
     for( const std::pair<const enchant_vals::mod, dbl_or_var> &pair_values :
          rhs.values_multiply ) {
         // values do not multiply against each other, they add.
         // so +10% and -10% will add to 0%
         values_multiply[pair_values.first] += pair_values.second.evaluate( d );
     }
     for( const std::pair<const skill_id, dbl_or_var> &pair_values :
          rhs.skill_values_add ) {
         skill_values_add[pair_values.first] += pair_values.second.evaluate( d );
     }
     for( const std::pair<const skill_id, dbl_or_var> &pair_values :
          rhs.skill_values_multiply ) {
         // values do not multiply against each other, they add.
         // so +10% and -10% will add to 0%
         skill_values_multiply[pair_values.first] += pair_values.second.evaluate( d );
     }
     hit_me_effect.insert( hit_me_effect.end(), rhs.hit_me_effect.begin(), rhs.hit_me_effect.end() );
     hit_you_effect.insert( hit_you_effect.end(), rhs.hit_you_effect.begin(), rhs.hit_you_effect.end() );
     ench_effects.insert( rhs.ench_effects.begin(), rhs.ench_effects.end() );
     if( rhs.emitter ) {
         emitter = rhs.emitter;
     }
     for( const bodypart_changes &bp : rhs.modified_bodyparts ) {
         modified_bodyparts.emplace_back( bp );
     }
     for( const trait_id &branch : rhs.mutations ) {
         mutations.emplace( branch );
     }
     for( const std::pair<const time_duration, std::vector<fake_spell>> &act_pair :
          rhs.intermittent_activation ) {
         for( const fake_spell &fake : act_pair.second ) {
             intermittent_activation[act_pair.first].emplace_back( fake );
         }
     }
     details.emplace_back( rhs.name.translated(), rhs.description.translated() );
 }
References bp, enchantment::description, enchantment::emitter, enchantment::ench_effects, get_talker_for(), enchantment::hit_me_effect, enchantment::hit_you_effect, enchantment::intermittent_activation, enchantment::modified_bodyparts, enchantment::mutations, enchantment::name, enchantment::skill_values_add, enchantment::skill_values_multiply, translation::translated(), enchantment::values_add, and enchantment::values_multiply.
get_skill_value_add()
int enchant_cache::get_skill_value_add (const skill_id & value) const
Definition at line 889 of file magic_enchantment.cpp.
 {
     const auto found = skill_values_add.find( value );
     if( found == skill_values_add.cend() ) {
         return 0;
     }
     return found->second;
 }
References enchantment::skill_values_add.
get_skill_value_multiply()
double enchant_cache::get_skill_value_multiply (const skill_id & value) const
Definition at line 907 of file magic_enchantment.cpp.
 {
     const auto found = skill_values_multiply.find( value );
     if( found == skill_values_multiply.cend() ) {
         return 0;
     }
     return found->second;
 }
References enchantment::skill_values_multiply.
get_value_add()
double enchant_cache::get_value_add (enchant_vals::mod value) const
Definition at line 880 of file magic_enchantment.cpp.
 {
     const auto found = values_add.find( value );
     if( found == values_add.cend() ) {
         return 0;
     }
     return found->second;
 }
References enchantment::values_add.
Referenced by relic_procgen_data::power_level().
get_value_multiply()
double enchant_cache::get_value_multiply (enchant_vals::mod value) const
Definition at line 898 of file magic_enchantment.cpp.
 {
     const auto found = values_multiply.find( value );
     if( found == values_multiply.cend() ) {
         return 0;
     }
     return found->second;
 }
References enchantment::values_multiply.
Referenced by relic_procgen_data::power_level().
load()
void enchant_cache::load (const JsonObject & jo, std::string_view src = {}, const std::optional< std::string > & inline_id = std::nullopt)
Definition at line 478 of file magic_enchantment.cpp.
 {
     enchantment::load( jo, "", inline_id, true );
     if( jo.has_array( "values" ) ) {
         for( const JsonObject value_obj : jo.get_array( "values" ) ) {
             try {
                 const enchant_vals::mod value = io::string_to_enum<enchant_vals::mod>
                                                 ( value_obj.get_string( "value" ) );
                 const int add = value_obj.has_int( "add" ) ? value_obj.get_int( "add", 0 ) : 0;
                 const double mult = value_obj.has_float( "multiply" ) ? value_obj.get_float( "multiply",
                                     0.0 ) : 0.0;
                 if( add != 0 ) {
                     values_add.emplace( value, add );
                 }
                 if( mult != 0.0 ) {
                     values_multiply.emplace( value, mult );
                 }
             } catch( ... ) {
                 debugmsg( "A relic attempted to load invalid enchantment %s.  If you updated versions this may be a removed enchantment and will fix itself.",
                           value_obj.get_string( "value", "" ) );
             }
         }
     }
     if( jo.has_array( "skills" ) ) {
         for( const JsonObject value_obj : jo.get_array( "skills" ) ) {
             const skill_id value = skill_id( value_obj.get_string( "value" ) );
             const int add = value_obj.get_int( "add", 0 );
             const double mult = value_obj.get_float( "multiply", 0.0 );
             if( add != 0 ) {
                 skill_values_add.emplace( value, add );
             }
             if( mult != 0.0 ) {
                 skill_values_multiply.emplace( value, static_cast<int>( mult ) );
             }
         }
     }
 }
References add, debugmsg, JsonObject::get_array(), JsonObject::has_array(), enchantment::load(), skill_id, enchantment::skill_values_add, enchantment::skill_values_multiply, enchantment::values_add, and enchantment::values_multiply.
Referenced by relic::load().
modify_value() [1/7]
double enchant_cache::modify_value (const skill_id & mod_val, double value) const
Definition at line 923 of file magic_enchantment.cpp.
 {
     value += get_skill_value_add( mod_val );
     value *= 1.0 + get_skill_value_multiply( mod_val );
     return value;
 }
modify_value() [2/7]
double enchant_cache::modify_value (enchant_vals::mod mod_val, double value) const
Definition at line 916 of file magic_enchantment.cpp.
 {
     value += get_value_add( mod_val );
     value *= 1.0 + get_value_multiply( mod_val );
     return value;
 }
References enchantment::get_value_add(), and enchantment::get_value_multiply().
modify_value() [3/7]
time_duration enchant_cache::modify_value (enchant_vals::mod mod_val, time_duration value) const
Definition at line 962 of file magic_enchantment.cpp.
 {
     value += time_duration::from_seconds<double>( get_value_add( mod_val ) );
     value *= 1.0 + get_value_multiply( mod_val );
     return value;
 }
References enchantment::get_value_add(), and enchantment::get_value_multiply().
modify_value() [4/7]
units::mass enchant_cache::modify_value (enchant_vals::mod mod_val, units::energy value) const
Definition at line 930 of file magic_enchantment.cpp.
 {
     value += units::from_millijoule<double>( get_value_add( mod_val ) );
     value *= 1.0 + get_value_multiply( mod_val );
     return value;
 }
References enchantment::get_value_add(), and enchantment::get_value_multiply().
modify_value() [5/7]
units::mass enchant_cache::modify_value (enchant_vals::mod mod_val, units::mass value) const
modify_value() [6/7]
units::temperature_delta enchant_cache::modify_value (enchant_vals::mod mod_val, units::temperature_delta value) const
Definition at line 954 of file magic_enchantment.cpp.
 {
     value += units::from_celsius_delta<double>( get_value_add( mod_val ) );
     value *= 1 + get_value_multiply( mod_val );
     return value;
 }
References enchantment::get_value_add(), and enchantment::get_value_multiply().
modify_value() [7/7]
units::volume enchant_cache::modify_value (enchant_vals::mod mod_val, units::volume value) const
Definition at line 946 of file magic_enchantment.cpp.
 {
     value += units::from_milliliter<double>( get_value_add( mod_val ) );
     value *= 1.0 + get_value_multiply( mod_val );
     return value;
 }
References enchantment::get_value_add(), and enchantment::get_value_multiply().
mult_bonus()
int enchant_cache::mult_bonus (enchant_vals::mod value_type, int base_value) const
Definition at line 970 of file magic_enchantment.cpp.
 {
     return get_value_multiply( value_type ) * base_value;
 }
References enchantment::get_value_multiply().
operator==()
bool enchant_cache::operator== (const enchant_cache & rhs) const
Definition at line 1095 of file magic_enchantment.cpp.
 {
     if( this->values_add.size() != rhs.values_add.size() ||
         this->values_multiply.size() != rhs.values_multiply.size() ) {
         return false;
     }
     auto iter_add = this->values_add.cbegin();
     auto iter_add2 = rhs.values_add.cbegin();
     while( iter_add != this->values_add.cend() && iter_add2 != rhs.values_add.cend() ) {
         if( iter_add->second != iter_add2->second || iter_add->first != iter_add2->first ) {
             return false;
         }
         iter_add++;
         iter_add2++;
     }
     auto iter_mult = this->values_multiply.cbegin();
     auto iter_mult2 = rhs.values_multiply.cbegin();
     while( iter_mult != this->values_multiply.cend() && iter_mult2 != rhs.values_multiply.cend() ) {
         if( iter_mult->second != iter_mult2->second || iter_mult->first != iter_mult2->first ) {
             return false;
         }
         iter_mult++;
         iter_mult2++;
     }
     return this->id == rhs.id &&
            this->get_mutations() == rhs.get_mutations();
 }
References enchantment::get_mutations(), enchantment::id, enchantment::values_add, values_add, enchantment::values_multiply, and values_multiply.
serialize()
void enchant_cache::serialize (JsonOut & jsout) const
Definition at line 518 of file magic_enchantment.cpp.
 {
     jsout.start_object();
     jsout.member( "has", io::enum_to_string<enchantment::has>( active_conditions.first ) );
     jsout.member( "condition", io::enum_to_string<enchantment::condition>( active_conditions.second ) );
     if( emitter ) {
         jsout.member( "emitter", emitter );
     }
     if( !hit_you_effect.empty() ) {
         jsout.member( "hit_you_effect", hit_you_effect );
     }
     if( !hit_me_effect.empty() ) {
         jsout.member( "hit_me_effect", hit_me_effect );
     }
     if( !intermittent_activation.empty() ) {
         jsout.member( "intermittent_activation" );
         jsout.start_object();
         jsout.member( "effects" );
         jsout.start_array();
         for( const std::pair<const time_duration, std::vector<fake_spell>> &pair :
              intermittent_activation ) {
             jsout.start_object();
             jsout.member( "frequency", to_string_writable( pair.first ) );
             jsout.member( "spell_effects", pair.second );
             jsout.end_object();
         }
         jsout.end_array();
         jsout.end_object();
     }
     if( !ench_effects.empty() ) {
         jsout.member( "ench_effects" );
         jsout.start_array();
         for( const std::pair<const efftype_id, int> &eff : ench_effects ) {
             jsout.start_object();
             jsout.member( "effect", eff.first );
             jsout.member( "intensity", eff.second );
             jsout.end_object();
         }
         jsout.end_array();
     }
     jsout.member( "modified_bodyparts", modified_bodyparts );
     jsout.member( "mutations", mutations );
     jsout.member( "values" );
     jsout.start_array();
     for( int value = 0; value < static_cast<int>( enchant_vals::mod::NUM_MOD ); value++ ) {
         enchant_vals::mod enum_value = static_cast<enchant_vals::mod>( value );
         jsout.start_object();
         jsout.member( "value", io::enum_to_string<enchant_vals::mod>( enum_value ) );
         if( get_value_add( enum_value ) != 0 ) {
             jsout.member( "add", get_value_add( enum_value ) );
         }
         if( get_value_multiply( enum_value ) != 0 ) {
             jsout.member( "multiply", get_value_multiply( enum_value ) );
         }
         jsout.end_object();
     }
     jsout.end_array();
     jsout.member( "skills" );
     jsout.start_array();
     const auto skill_f = []( const Skill & lhs, const Skill & rhs ) {
         return lhs.ident() < rhs.ident();
     };
     for( const Skill *sk : Skill::get_skills_sorted_by( skill_f ) ) {
         skill_id skid = sk->ident();
         jsout.start_object();
         jsout.member( "value", skid );
         if( get_skill_value_add( skid ) != 0 ) {
             jsout.member( "add", get_skill_value_add( skid ) );
         }
         if( get_skill_value_multiply( skid ) != 0 ) {
             jsout.member( "multiply", get_skill_value_multiply( skid ) );
         }
         jsout.end_object();
     }
     jsout.end_array();
     jsout.end_object();
 }
References enchantment::active_conditions, enchantment::emitter, enchantment::ench_effects, JsonOut::end_array(), JsonOut::end_object(), Skill::get_skills_sorted_by(), enchantment::get_value_add(), enchantment::get_value_multiply(), enchantment::hit_me_effect, enchantment::hit_you_effect, Skill::ident(), enchantment::intermittent_activation, JsonOut::member(), enchantment::modified_bodyparts, enchantment::mutations, enchant_vals::NUM_MOD, JsonOut::start_array(), JsonOut::start_object(), and to_string_writable().
set_has()
void enchant_cache::set_has (enchantment::has value)
Definition at line 835 of file magic_enchantment.cpp.
 {
     active_conditions.first = value;
 }
References enchantment::active_conditions.
Referenced by relic_procgen_data::generate().
skill_mult_bonus()
int enchant_cache::skill_mult_bonus (const skill_id & value_type, int base_value) const
Definition at line 975 of file magic_enchantment.cpp.
 {
     return get_skill_value_multiply( value_type ) * base_value;
 }
stacks_with()
bool enchant_cache::stacks_with (const enchantment & rhs) const
Definition at line 605 of file magic_enchantment.cpp.
 {
     return active_conditions == rhs.active_conditions;
 }
References enchantment::active_conditions.
Member Data Documentation
details
std::vector<std::pair<std::string, std::string> > enchant_cache::details
Definition at line 335 of file magic_enchantment.h.
skill_values_add
std::map<skill_id, int> enchant_cache::skill_values_add private
Definition at line 344 of file magic_enchantment.h.
Referenced by force_add().
skill_values_multiply
std::map<skill_id, int> enchant_cache::skill_values_multiply private
Definition at line 345 of file magic_enchantment.h.
Referenced by force_add().
values_add
std::map<enchant_vals::mod, double> enchant_cache::values_add private
Definition at line 338 of file magic_enchantment.h.
Referenced by force_add(), and operator==().
values_multiply
std::map<enchant_vals::mod, double> enchant_cache::values_multiply private
Definition at line 341 of file magic_enchantment.h.
Referenced by force_add(), and operator==().
The documentation for this class was generated from the following files:
src/magic_enchantment.h
src/magic_enchantment.cpp