Cataclysm DDA: jmapgen_loot Class Reference
jmapgen_loot Class Reference
Place items from an item group.
Public Member Functions
jmapgen_loot (const JsonObject &jsi)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Private Attributes
friend jmapgen_objects
Item_group result_group
int chance
Additional Inherited Members
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place items from an item group.
Definition at line 2304 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_loot()
jmapgen_loot::jmapgen_loot (const JsonObject & jsi) inline explicit
Definition at line 2309 of file mapgen.cpp.
                                                        :
             result_group( Item_group::Type::G_COLLECTION, 100, jsi.get_int( "ammo", 0 ),
                           jsi.get_int( "magazine", 0 ), "mapgen loot entry" )
             , chance( jsi.get_int( "chance", 100 ) ) {
             const item_group_id group( jsi.get_string( "group", std::string() ) );
             itype_id ity;
             jsi.read( "item", ity );
             if( group.is_empty() == ity.is_empty() ) {
                 jsi.throw_error( "must provide either item or group" );
             }
             if( !group.is_empty() && !item_group::group_is_defined( group ) ) {
                 set_mapgen_defer( jsi, "group", "no such item group" );
             }
             if( !ity.is_empty() && !item::type_is_defined( ity ) ) {
                 set_mapgen_defer( jsi, "item", "no such item type '" + ity.str() + "'" );
             }
             // All the probabilities are 100 because we do the roll in @ref apply.
             if( group.is_empty() ) {
                 // Migrations are applied to item *groups* on load, but single item spawns must be
                 // migrated individually
                 std::string variant;
                 if( jsi.has_string( "variant" ) ) {
                     variant = jsi.get_string( "variant" );
                 }
                 result_group.add_item_entry( item_controller->migrate_id( ity ), 100, variant );
             } else {
                 result_group.add_group_entry( group, 100 );
             }
             result_group.finalize( itype_id::NULL_ID() );
         }
References Item_group::add_group_entry(), Item_group::add_item_entry(), Item_group::finalize(), JsonObject::get_string(), item_group::group_is_defined(), JsonObject::has_string(), string_id< T >::is_empty(), item_controller, mapgen_defer::jsi, string_id< itype >::NULL_ID(), JsonObject::read(), result_group, set_mapgen_defer(), string_id< T >::str(), JsonObject::throw_error(), and item::type_is_defined().
Member Function Documentation
apply()
void jmapgen_loot::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2342 of file mapgen.cpp.
{
             if( rng( 0, 99 ) < chance ) {
                 const Item_spawn_data *const isd = &result_group;
                 std::vector<item> spawn;
                 spawn.reserve( 20 );
                 isd->create( spawn, calendar::start_of_cataclysm,
                              spawn_flags::use_spawn_rate );
                 dat.m.spawn_items( tripoint( rng( x.val, x.valmax ), rng( y.val, y.valmax ),
                                              dat.zlevel() + z.get() ), spawn );
             }
         }
References chance, Item_spawn_data::create(), jmapgen_int::get(), mapgendata::m, result_group, rng(), map::spawn_items(), calendar::start_of_cataclysm, tripoint, use_spawn_rate, jmapgen_int::val, jmapgen_int::valmax, and mapgendata::zlevel().
Member Data Documentation
chance
int jmapgen_loot::chance private
Definition at line 2357 of file mapgen.cpp.
Referenced by apply().
jmapgen_objects
friend jmapgen_loot::jmapgen_objects private
Definition at line 2306 of file mapgen.cpp.
result_group
Item_group jmapgen_loot::result_group private
Definition at line 2356 of file mapgen.cpp.
Referenced by apply(), and jmapgen_loot().
The documentation for this class was generated from the following file:
src/mapgen.cpp