Cataclysm DDA: npc_attack_gun Class Reference
npc_attack_gun Class Reference
#include <npc_attack.h>
Public Member Functions
npc_attack_gun (item &gun, const gun_mode &gunmode)
npc_attack_rating evaluate (const npc &source, const Creature *target) const override
Parameters: source - the npc making the attack target - the desired target of the npc.
std::vector< npc_attack_rating > all_evaluations (const npc &source, const Creature *target) const override
For debug information.
void use (npc &source, const tripoint &location) const override
Public Member Functions inherited from npc_attack
virtual ~npc_attack ()=default
Private Member Functions
tripoint_range< tripoint > targetable_points (const npc &source) const
bool can_use (const npc &source) const
int base_time_penalty (const npc &source) const
npc_attack_rating evaluate_tripoint (const npc &source, const Creature *target, const tripoint &location) const
Private Attributes
const gun_mode gunmode
item & gun
Detailed Description
Definition at line 96 of file npc_attack.h.
Constructor & Destructor Documentation
npc_attack_gun()
npc_attack_gun::npc_attack_gun (item & gun, const gun_mode & gunmode) inline explicit
Definition at line 101 of file npc_attack.h.
 : gunmode( gunmode ), gun( gun ) {}
Member Function Documentation
all_evaluations()
std::vector< npc_attack_rating > npc_attack_gun::all_evaluations (const npc & source, const Creature * target) const override virtual
For debug information.
returns all evaluated effectivenesses. This is abstracted out in evaluate() as it's faster to not use a container
Implements npc_attack.
Definition at line 522 of file npc_attack.cpp.
 {
     std::vector<npc_attack_rating> effectiveness;
     if( !can_use( source ) ) {
         return effectiveness;
     }
     const int time_penalty = base_time_penalty( source );
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &targetable_point : targetable_points( source ) ) {
         if( creatures.creature_at( targetable_point ) ) {
             npc_attack_rating effectiveness_at_point = evaluate_tripoint( source, target,
                     targetable_point );
             effectiveness_at_point -= time_penalty;
             effectiveness.push_back( effectiveness_at_point );
         }
     }
     return effectiveness;
 }
References base_time_penalty(), can_use(), creature_tracker::creature_at(), evaluate_tripoint(), get_creature_tracker(), and targetable_points().
base_time_penalty()
int npc_attack_gun::base_time_penalty (const npc & source) const private
Definition at line 473 of file npc_attack.cpp.
 {
     const item &weapon = *gunmode;
     int time_penalty = 0;
     if( source.is_wielding( weapon ) ) {
         time_penalty += npc_attack_constants::base_time_penalty;
     }
     // we want the need to reload a gun cumulative with needing to wield the gun
     if( !weapon.ammo_sufficient( &source ) ) {
         time_penalty += npc_attack_constants::base_time_penalty;
     }
     int recoil_penalty = 0;
     if( source.is_wielding( weapon ) ) {
         recoil_penalty = source.recoil;
     } else {
         recoil_penalty = MAX_RECOIL;
     }
     recoil_penalty /= 100;
     return time_penalty + recoil_penalty;
 }
References item::ammo_sufficient(), npc_attack_constants::base_time_penalty, gunmode, Character::is_wielding(), MAX_RECOIL, and Character::recoil.
Referenced by all_evaluations(), and evaluate().
can_use()
bool npc_attack_gun::can_use (const npc & source) const private
Definition at line 467 of file npc_attack.cpp.
 {
     // can't attack with something you can't wield
     return source.is_wielding( *gunmode ) || source.can_wield( *gunmode ).success();
 }
References Character::can_wield(), gunmode, Character::is_wielding(), and ret_val_common::success().
Referenced by all_evaluations(), and evaluate().
evaluate()
npc_attack_rating npc_attack_gun::evaluate (const npc & source, const Creature * target) const override virtual
Parameters: source - the npc making the attack target - the desired target of the npc.
valued at 100%
Implements npc_attack.
Definition at line 500 of file npc_attack.cpp.
 {
     npc_attack_rating effectiveness( std::nullopt, source.pos() );
     if( !can_use( source ) ) {
         return effectiveness;
     }
     const int time_penalty = base_time_penalty( source );
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &targetable_point : targetable_points( source ) ) {
         if( creatures.creature_at( targetable_point ) ) {
             npc_attack_rating effectiveness_at_point = evaluate_tripoint( source, target,
                     targetable_point );
             effectiveness_at_point -= time_penalty;
             if( effectiveness_at_point > effectiveness ) {
                 effectiveness = effectiveness_at_point;
             }
         }
     }
     return effectiveness;
 }
References base_time_penalty(), can_use(), creature_tracker::creature_at(), evaluate_tripoint(), get_creature_tracker(), Creature::pos(), and targetable_points().
evaluate_tripoint()
npc_attack_rating npc_attack_gun::evaluate_tripoint (const npc & source, const Creature * target, const tripoint & location) const private
Definition at line 542 of file npc_attack.cpp.
 {
     const item &gun = *gunmode.target;
     const int damage = gun.gun_damage().total_damage() * gunmode.qty;
     double potential = damage;
     const Creature *critter = get_creature_tracker().creature_at( location );
     if( !critter ) {
         // TODO: AOE ammo effects
         return npc_attack_rating( std::nullopt, location );
     }
     const Creature::Attitude att = source.attitude_to( *critter );
     if( att != Creature::Attitude::HOSTILE ) {
         // No point in attacking neutral/friendly targets
         return npc_attack_rating( std::nullopt, location );
     }
     const bool avoids_friendly_fire = source.rules.has_flag( ally_rule::avoid_friendly_fire );
     const int distance_to_me = rl_dist( location, source.pos() );
     // Make attacks that involve moving to find clear LOS slightly less likely
     if( has_obstruction( source.pos(), location, avoids_friendly_fire ) ) {
         potential *= 0.9f;
     } else if( avoids_friendly_fire && !source.wont_hit_friend( location, gun, false ) ) {
         potential *= 0.95f;
     }
     // Prefer targets not directly next to you
     potential *= distance_to_me > 2 ? 1.15f : 0.85f;
     if( damage >= critter->get_hp() ) {
         potential *= npc_attack_constants::kill_modifier;
     }
     if( target && target->pos() == critter->pos() ) {
         potential *= npc_attack_constants::target_modifier;
     }
     return npc_attack_rating( static_cast<int>( std::round( potential ) ), location );
 }
References npc::attitude_to(), avoid_friendly_fire, creature_tracker::creature_at(), get_creature_tracker(), Creature::get_hp(), gun, item::gun_damage(), gunmode, npc_follower_rules::has_flag(), has_obstruction(), Creature::HOSTILE, npc_attack_constants::kill_modifier, location, Creature::pos(), gun_mode::qty, rl_dist(), round(), npc::rules, gun_mode::target, npc_attack_constants::target_modifier, damage_instance::total_damage(), and npc::wont_hit_friend().
Referenced by all_evaluations(), and evaluate().
targetable_points()
tripoint_range< tripoint > npc_attack_gun::targetable_points (const npc & source) const private
Definition at line 494 of file npc_attack.cpp.
 {
     const item &weapon = *gunmode;
     return get_map().points_in_radius( source.pos(), weapon.gun_range() );
 }
References get_map(), item::gun_range(), gunmode, map::points_in_radius(), and Creature::pos().
Referenced by all_evaluations(), and evaluate().
use()
void npc_attack_gun::use (npc & source, const tripoint & location) const override virtual
Implements npc_attack.
Definition at line 418 of file npc_attack.cpp.
 {
     if( !source.is_wielding( gun ) ) {
         if( !source.wield( gun ) ) {
             debugmsg( "ERROR: npc tried to equip a weapon it couldn't wield" );
         }
         return;
     }
     if( !gun.ammo_sufficient( &source ) ) {
         // todo: make gun an item_location instead of getting wielded item here
         // but since wielding is required before this, it should be fine
         source.do_reload( source.get_wielded_item() );
         add_msg_debug( debugmode::debug_filter::DF_NPC, "%s is reloading %s", source.disp_name(),
                        gun.display_name() );
         return;
     }
     if( has_obstruction( source.pos(), location, false ) ||
         ( source.rules.has_flag( ally_rule::avoid_friendly_fire ) &&
           !source.wont_hit_friend( location, gun, false ) ) ) {
         if( can_move( source ) ) {
             source.avoid_friendly_fire();
         } else {
             source.move_pause();
         }
         return;
     }
     const int dist = rl_dist( source.pos(), location );
     // Only aim if we aren't in risk of being hit
     // TODO: Get distance to closest enemy
     if( dist > 1 && source.aim_per_move( gun, source.recoil ) > 0 &&
         source.confident_gun_mode_range( gunmode, source.recoil ) < dist ) {
         add_msg_debug( debugmode::debug_filter::DF_NPC, "%s is aiming", source.disp_name() );
         source.aim( Target_attributes( source.pos(), location ) );
     } else {
         if( source.is_hallucination() ) {
             gun_mode mode = source.get_wielded_item()->gun_current_mode();
             source.pretend_fire( &source, mode.qty, *mode );
         } else {
             source.fire_gun( location );
         }
         add_msg_debug( debugmode::debug_filter::DF_NPC, "%s fires %s", source.disp_name(),
                        gun.display_name() );
     }
 }
References add_msg_debug, npc::aim(), Character::aim_per_move(), item::ammo_sufficient(), avoid_friendly_fire, npc::avoid_friendly_fire(), can_move(), npc::confident_gun_mode_range(), debugmsg, debugmode::DF_NPC, Character::disp_name(), item::display_name(), npc::do_reload(), Character::fire_gun(), Character::get_wielded_item(), gun, item::gun_current_mode(), gunmode, npc_follower_rules::has_flag(), has_obstruction(), npc::is_hallucination(), Character::is_wielding(), location, npc::move_pause(), Creature::pos(), npc::pretend_fire(), gun_mode::qty, Character::recoil, rl_dist(), npc::rules, npc::wield(), and npc::wont_hit_friend().
Member Data Documentation
gun
item& npc_attack_gun::gun private
Definition at line 99 of file npc_attack.h.
Referenced by evaluate_tripoint(), and use().
gunmode
const gun_mode npc_attack_gun::gunmode private
Definition at line 98 of file npc_attack.h.
Referenced by base_time_penalty(), can_use(), evaluate_tripoint(), targetable_points(), and use().
The documentation for this class was generated from the following files:
src/npc_attack.h
src/npc_attack.cpp