Cataclysm DDA: io::JsonObjectInputArchive Class Reference
io::JsonObjectInputArchive Class Reference
Input archive reading data from a Json object.
#include <cata_io.h>
Public Types
using is_input = std::true_type
Public Member Functions
JsonObjectInputArchive (const JsonObject &jo)
JsonObjectInputArchive (JsonArray &)
Create archive from next object in the given Json array.
JsonObjectInputArchive (const JsonObject &, std::string_view key)
Create archive from named member object in the given Json object.
Deserialization
The io functions read a value from the archive and store it in the reference parameter.
Exceptions
JsonError (via the Json classes) if the value in the archive is of an incompatible type (e.g. reading a string, but the member is a Json object).
Returns
false if the archive did not contain the requested member, otherwise true.
template<typename T >
bool io (const std::string &name, T &value)
If the archive does not have the requested member, the value is not changed at all.
template<typename T >
bool io (const std::string &name, T &value, const T &default_value)
If the archive does not have the requested member, the given default value is assigned.
template<typename T >
bool io (const std::string &name, T &value, default_tag)
Like the other io function, this uses a default constructed default value: Roughly equivalent to.
template<typename T >
bool io (const std::string &name, T &value, empty_default_tag)
If the archive does not have the requested member, the function clear is called on the value, this may be used for containers (e.g.
template<typename T >
bool io (const std::string &name, T *&pointer, const std::function< void(const std::string &)> &load, const std::function< std::string(const T &)> &save, bool required=false)
Special function to load pointers.
template<typename T , typename LoadFunc , typename SaveFunc >
bool io (const std::string &name, T &pointer, const LoadFunc &load, const SaveFunc &save, bool required=false)
The 'I-give-up' template for gun variant data.
template<typename T >
bool io (const std::string &name, T *&pointer, const std::function< void(const std::string &)> &load, const std::function< std::string(const T &)> &save, required_tag)
Public Member Functions inherited from JsonObject
JsonObject ()
JsonObject (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath &&path)
JsonObject (const JsonObject &rhs)
JsonObject & operator= (const JsonObject &rhs)
JsonObject (JsonObject &&rhs) noexcept
JsonObject & operator= (JsonObject &&rhs) noexcept
~JsonObject ()
size_t size () const
std::string get_string (const std::string &key) const
std::string get_string (const char *key) const
template<typename T , typename std::enable_if_t< std::is_convertible_v< T, std::string >> * = nullptr>
std::string get_string (const std::string &key, T &&fallback) const
template<typename T , typename std::enable_if_t< std::is_convertible_v< T, std::string >> * = nullptr>
std::string get_string (const char *key, T &&fallback) const
bool get_bool (std::string_view key) const
int get_int (std::string_view key) const
double get_float (std::string_view key) const
JsonArray get_array (std::string_view key) const
JsonObject get_object (std::string_view key) const
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value (const std::string &name) const
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value (const char *name) const
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value (const std::string &name, E fallback) const
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value (const char *name, E fallback) const
std::vector< int > get_int_array (std::string_view name) const
std::vector< std::string > get_string_array (std::string_view name) const
std::vector< std::string > get_as_string_array (const std::string &name) const
bool has_member (std::string_view key) const
bool has_null (std::string_view key) const
bool has_string (std::string_view key) const
bool has_bool (std::string_view key) const
bool has_number (std::string_view key) const
bool has_int (std::string_view key) const
bool has_float (std::string_view key) const
bool has_array (std::string_view key) const
bool has_object (std::string_view key) const
bool get_bool (std::string_view key, bool fallback) const
int get_int (std::string_view key, int fallback) const
double get_float (std::string_view key, double fallback) const
std::optional< JsonValue > get_member_opt (std::string_view key) const
JsonValue get_member (std::string_view key) const
JsonValue operator[] (std::string_view key) const
template<typename T >
bool read (std::string_view name, T &t, bool throw_on_error=true) const
template<typename T = std::string, typename Res = std::set<T>>
Res get_tags (std::string_view name) const
void throw_error (const std::string &err) const
void throw_error_at (std::string_view member, const std::string &err) const
void allow_omitted_members () const
void copy_visited_members (const JsonObject &rhs) const
const_iterator begin () const
const_iterator end () const
std::string str () const
Additional Inherited Members
Public Attributes inherited from JsonObject
friend const_iterator
Static Protected Member Functions inherited from JsonObject
static const auto & empty_object_ ()
Protected Attributes inherited from JsonObject
flexbuffers::TypedVector keys_ = flexbuffers::TypedVector::EmptyTypedVector()
flexbuffers::Vector values_ = flexbuffers::Vector::EmptyVector()
tiny_bitset visited_fields_bitset_
Detailed Description
Input archive reading data from a Json object.
Data can be loaded from this archive using the name of the member as key.
Definition at line 192 of file cata_io.h.
Member Typedef Documentation
is_input
using io::JsonObjectInputArchive::is_input = std::true_type
Definition at line 195 of file cata_io.h.
Constructor & Destructor Documentation
JsonObjectInputArchive() [1/3]
io::JsonObjectInputArchive::JsonObjectInputArchive (const JsonObject & jo) inline explicit
Definition at line 197 of file cata_io.h.
             : JsonObject( jo ) {
         }
JsonObjectInputArchive() [2/3]
io::JsonObjectInputArchive::JsonObjectInputArchive (JsonArray & arr) inline explicit
Create archive from next object in the given Json array.
Definition at line 365 of file cata_io.h.
     : JsonObject( arr.next_object() ) { }
JsonObjectInputArchive() [3/3]
io::JsonObjectInputArchive::JsonObjectInputArchive (const JsonObject & obj, std::string_view key) inline
Create archive from named member object in the given Json object.
Definition at line 367 of file cata_io.h.
     : JsonObject( obj.get_object( key ) ) { }
Member Function Documentation
io() [1/7]
template<typename T , typename LoadFunc , typename SaveFunc > bool io::JsonObjectInputArchive::io (const std::string & name, T & pointer, const LoadFunc & load, const SaveFunc & save, bool required = false) inline
The 'I-give-up' template for gun variant data.
Definition at line 307 of file cata_io.h.
{
             // Only used by the matching function in the output archive classes.
             ( void ) save;
             std::string ident;
             if( !io( name, ident ) ) {
                 if( required ) {
                     JsonObject::throw_error( std::string( "required member is missing: " ) + name );
                 }
                 pointer = nullptr;
                 return false;
             }
             load( ident );
             return true;
         }
References io(), ammo_effects::load(), om_direction::name(), and JsonObject::throw_error().
io() [2/7]
template<typename T > bool io::JsonObjectInputArchive::io (const std::string & name, T & value) inline
If the archive does not have the requested member, the value is not changed at all.
Definition at line 219 of file cata_io.h.
{
             return io::detail::has_archive_tag<T>::read( *this, name, value );
         }
References om_direction::name(), and io::detail::has_archive_tag< T, E >::read().
Referenced by io().
io() [3/7]
template<typename T > bool io::JsonObjectInputArchive::io (const std::string & name, T & value, const T & default_value) inline
If the archive does not have the requested member, the given default value is assigned.
The function still returns false if the default value had been used.
Definition at line 227 of file cata_io.h.
{
             if( io( name, value ) ) {
                 return true;
             }
             value = default_value;
             return false;
         }
References io(), and om_direction::name().
io() [4/7]
template<typename T > bool io::JsonObjectInputArchive::io (const std::string & name, T & value, default_tag) inline
Like the other io function, this uses a default constructed default value: Roughly equivalent to.
io<T>(name, value, T());
Definition at line 239 of file cata_io.h.
{
             static const T default_value = T();
             return io( name, value, default_value );
         }
References io(), and om_direction::name().
io() [5/7]
template<typename T > bool io::JsonObjectInputArchive::io (const std::string & name, T & value, empty_default_tag) inline
If the archive does not have the requested member, the function clear is called on the value, this may be used for containers (e.g.
std::map).
Definition at line 248 of file cata_io.h.
{
             if( io( name, value ) ) {
                 return true;
             }
             value.clear();
             return false;
         }
References io(), and om_direction::name().
io() [6/7]
template<typename T > bool io::JsonObjectInputArchive::io (const std::string & name, T *& pointer, const std::function< void(const std::string &)> & load, const std::function< std::string(const T &)> & save, bool required = false) inline
Special function to load pointers.
If the archive does not have the requested member, nullptr is assigned to the pointer. Otherwise the value is loaded (which must be a std::string) and the load function is called.
Example:
class Dummy {
    int *pointer;
    template<typename A> void io( A& ar ) {
        ar.io( "ptr", pointer,
            [this](const std::string&s) {
                pointer = new int( atoi( s.c_str() ) );
            },
            [](const int &v) {
                return std::to_string( v );
            }
        );
    }
};
Parameters
name Name of requested member
pointer
load The function gets the string that was loaded from JSON and should set the pointer in the object accordingly. One would usually use a lambda for this function.
save The inverse of the load function, it converts the pointer to a string which is later stored in the JSON.
required If true, an error will be raised if the requested member does not exist in the JSON data. JsonOutputArchive, so it can be used when the archive type is a template parameter.
Definition at line 287 of file cata_io.h.
{
             // Only used by the matching function in the output archive classes.
             ( void ) save;
             std::string ident;
             if( !io( name, ident ) ) {
                 if( required ) {
                     JsonObject::throw_error( std::string( "required member is missing: " ) + name );
                 }
                 pointer = nullptr;
                 return false;
             }
             load( ident );
             return true;
         }
References io(), ammo_effects::load(), om_direction::name(), and JsonObject::throw_error().
io() [7/7]
template<typename T > bool io::JsonObjectInputArchive::io (const std::string & name, T *& pointer, const std::function< void(const std::string &)> & load, const std::function< std::string(const T &)> & save, required_tag) inline
Definition at line 324 of file cata_io.h.
{
             return io<T>( name, pointer, load, save, true );
         }
References ammo_effects::load(), and om_direction::name().
The documentation for this class was generated from the following file:
src/cata_io.h