Cataclysm DDA: forage_activity_actor Class Reference
forage_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
forage_activity_actor ()=default
forage_activity_actor (int moves)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves
Detailed Description
Definition at line 1998 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
forage_activity_actor() [1/2]
forage_activity_actor::forage_activity_actor () default
forage_activity_actor() [2/2]
forage_activity_actor::forage_activity_actor (int moves) inline explicit
Definition at line 2002 of file activity_actor_definitions.h.
 : moves( moves ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> forage_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 2012 of file activity_actor_definitions.h.
{
             return std::make_unique<forage_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > forage_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6764 of file activity_actor.cpp.
 {
     forage_activity_actor actor( {} );
     JsonObject data = jsin.get_object();
     data.read( "moves", actor.moves );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void forage_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 2009 of file activity_actor_definitions.h.
 {};
finish()
void forage_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Perception slightly increases forage success chance \EFFECT_SURVIVAL increases forage success chance
Implements activity_actor.
Definition at line 6652 of file activity_actor.cpp.
 {
     // Don't forage if we aren't next to the bush - otherwise we get weird bugs
     bool next_to_bush = false;
     map &here = get_map();
     for( const tripoint &pnt : here.points_in_radius( who.pos(), 1 ) ) {
         // TODO: fix point types
         if( here.getglobal( pnt ) == act.placement ) {
             next_to_bush = true;
             break;
         }
     }
     if( !next_to_bush ) {
         act.set_to_null();
         return;
     }
     const int veggy_chance = rng( 1, 100 );
     bool found_something = false;
     item_group_id group_id;
     ter_str_id next_ter;
     switch( season_of_year( calendar::turn ) ) {
         case SPRING:
             group_id = Item_spawn_data_forage_spring;
             next_ter = ter_t_underbrush_harvested_spring;
             break;
         case SUMMER:
             group_id = Item_spawn_data_forage_summer;
             next_ter = ter_t_underbrush_harvested_summer;
             break;
         case AUTUMN:
             group_id = Item_spawn_data_forage_autumn;
             next_ter = ter_t_underbrush_harvested_autumn;
             break;
         case WINTER:
             group_id = Item_spawn_data_forage_winter;
             next_ter = ter_t_underbrush_harvested_winter;
             break;
         default:
             debugmsg( "Invalid season" );
     }
     const tripoint bush_pos = here.getlocal( act.placement );
     here.ter_set( bush_pos, next_ter );
     // Survival gives a bigger boost, and Perception is leveled a bit.
     // Both survival and perception affect time to forage
     ///\EFFECT_PER slightly increases forage success chance
     ///\EFFECT_SURVIVAL increases forage success chance
     if( veggy_chance < round( who.get_skill_level( skill_survival ) * 3 + who.per_cur - 2 ) ) {
         const std::vector<item *> dropped =
             here.put_items_from_loc( group_id, who.pos(), calendar::turn );
         // map::put_items_from_loc can create multiple items and merge them into one stack.
         // That stack will then appear multiple times in the vector.
         // Remember and check the already handled items to prevent rolling
         // poison/hallucinogen multiple times and print misleading messages.
         std::vector<item *> handled;
         for( item *it : dropped ) {
             if( std::find( handled.rbegin(), handled.rend(), it ) != handled.rend() )  {
                 continue;
             }
             handled.push_back( it );
             found_something = true;
             if( it->has_flag( flag_FORAGE_POISON ) && one_in( 10 ) ) {
                 it->set_flag( flag_HIDDEN_POISON );
                 it->poison = rng( 2, 7 );
             } else if( it->has_flag( flag_FORAGE_HALLU ) && one_in( 10 ) ) {
                 it->set_flag( flag_HIDDEN_HALLU );
             }
             add_msg( m_good, _( "You found: %s!" ), it->display_name() );
         }
     }
     // 10% to drop a item/items from this group.
     if( one_in( 10 ) ) {
         const std::vector<item *> dropped =
             here.put_items_from_loc( Item_spawn_data_trash_forest, who.pos(), calendar::turn );
         // same as above
         std::vector<item *> handled;
         for( item * const &it : dropped ) {
             if( std::find( handled.rbegin(), handled.rend(), it ) != handled.rend() ) {
                 continue;
             }
             handled.push_back( it );
             add_msg( m_good, _( "You found: %s!" ), it->display_name() );
             found_something = true;
         }
     }
     if( !found_something ) {
         add_msg( _( "You didn't find anything." ) );
     }
     iexamine::practice_survival_while_foraging( who );
     act.set_to_null();
     here.maybe_trigger_trap( bush_pos, who, true );
 }
References _, act, add_msg(), AUTUMN, debugmsg, flag_FORAGE_HALLU, flag_FORAGE_POISON, flag_HIDDEN_HALLU, flag_HIDDEN_POISON, get_map(), Character::get_skill_level(), map::getglobal(), map::getlocal(), Item_spawn_data_forage_autumn, Item_spawn_data_forage_spring, Item_spawn_data_forage_summer, Item_spawn_data_forage_winter, Item_spawn_data_trash_forest, m_good, map::maybe_trigger_trap(), one_in(), Character::per_cur, map::points_in_radius(), Creature::pos(), iexamine::practice_survival_while_foraging(), map::put_items_from_loc(), rng(), round(), season_of_year(), skill_survival, SPRING, SUMMER, map::ter_set(), ter_t_underbrush_harvested_autumn, ter_t_underbrush_harvested_spring, ter_t_underbrush_harvested_summer, ter_t_underbrush_harvested_winter, calendar::turn, and WINTER.
get_type()
activity_id forage_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 2004 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_FORAGE" );
         }
References activity_id.
serialize()
void forage_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6755 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves", moves );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves, and JsonOut::start_object().
start()
void forage_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 6646 of file activity_actor.cpp.
 {
     act.moves_total = moves;
     act.moves_left = moves;
 }
References act, and moves.
Member Data Documentation
moves
int forage_activity_actor::moves private
Definition at line 2020 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp