Cataclysm DDA: cataimgui::client Class Reference
cataimgui::client Class Reference
#include <cata_imgui.h>
Public Member Functions
client ()
~client ()
void new_frame ()
void end_frame ()
void process_input (void *input)
void process_cata_input (const input_event &event)
void upload_color_pair (int p, int f, int b)
void set_alloced_pair_count (short count)
bool auto_size_frame_active ()
bool any_window_shown ()
Detailed Description
Definition at line 44 of file cata_imgui.h.
Constructor & Destructor Documentation
client()
cataimgui::client::client ()
Definition at line 40 of file cata_imgui.cpp.
 {
     load_colors();
     IMGUI_CHECKVERSION();
     ImGui::CreateContext();
     ImTui_ImplNcurses_Init();
     ImTui_ImplText_Init();
     ImGui::GetIO().ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
     ImGui::GetIO().IniFilename = nullptr;
     ImGui::GetIO().LogFilename = nullptr;
 }
References cataimgui::load_colors().
~client()
cataimgui::client::~client ()
Definition at line 55 of file cata_imgui.cpp.
 {
     ImTui_ImplNcurses_Shutdown();
     ImTui_ImplText_Shutdown();
     ImGui::Shutdown();
 }
Member Function Documentation
any_window_shown()
bool cataimgui::client::any_window_shown ()
Definition at line 286 of file cata_imgui.cpp.
 {
     bool any_window_shown = false;
     for( const ImGuiWindow *window : GImGui->Windows ) {
         if( window->Active && !window->Hidden ) {
             any_window_shown = true;
             break;
         }
     }
     return any_window_shown;
 }
auto_size_frame_active()
bool cataimgui::client::auto_size_frame_active ()
Definition at line 275 of file cata_imgui.cpp.
 {
     for( const ImGuiWindow *window : GImGui->Windows ) {
         if( ( window->ContentSize.x == 0 || window->ContentSize.y == 0 ) && ( window->AutoFitFramesX > 0 ||
                 window->AutoFitFramesY > 0 ) ) {
             return true;
         }
     }
     return false;
 }
end_frame()
void cataimgui::client::end_frame ()
Definition at line 71 of file cata_imgui.cpp.
 {
     ImGui::Render();
     ImTui_ImplText_RenderDrawData( ImGui::GetDrawData() );
     ImTui_ImplNcurses_DrawScreen();
 }
new_frame()
void cataimgui::client::new_frame ()
Definition at line 62 of file cata_imgui.cpp.
 {
     ImTui_ImplNcurses_NewFrame( imtui_events );
     imtui_events.clear();
     ImTui_ImplText_NewFrame();
     ImGui::NewFrame();
 }
References imtui_events.
process_cata_input()
void cataimgui::client::process_cata_input (const input_event & event)
Definition at line 325 of file cata_imgui.cpp.
 {
     if( event.type == input_event_t::keyboard_code || event.type == input_event_t::keyboard_char ) {
         int code = event.get_first_input();
         ImGuiIO &io = ImGui::GetIO();
         io.AddKeyEvent( cata_key_to_imgui( code ), true );
         io.AddKeyEvent( cata_key_to_imgui( code ), false );
     }
 }
References cata_key_to_imgui(), keyboard_char, keyboard_code, and input_event::type.
process_input()
void cataimgui::client::process_input (void * input)
Definition at line 90 of file cata_imgui.cpp.
 {
     if( !any_window_shown() ) {
         return;
     }
     if( input ) {
         input_event *curses_input = static_cast<input_event *>( input );
         ImTui::mouse_event new_mouse_event = ImTui::mouse_event();
         if( curses_input->type == input_event_t::mouse ) {
             new_mouse_event.x = curses_input->mouse_pos.x;
             new_mouse_event.y = curses_input->mouse_pos.y;
             new_mouse_event.bstate = 0;
             for( int input_raw_key : curses_input->sequence ) {
                 switch( static_cast<MouseInput>( input_raw_key ) ) {
                     case MouseInput::LeftButtonPressed:
                         new_mouse_event.bstate |= BUTTON1_PRESSED;
                         break;
                     case MouseInput::LeftButtonReleased:
                         new_mouse_event.bstate |= BUTTON1_RELEASED;
                         break;
                     case MouseInput::RightButtonPressed:
                         new_mouse_event.bstate |= BUTTON3_PRESSED;
                         break;
                     case MouseInput::RightButtonReleased:
                         new_mouse_event.bstate |= BUTTON3_RELEASED;
                         break;
 #if defined(BUTTON5_PRESSED) /* If curses version is prepared for a 5-button mouse, enable mousewheel */
                     case MouseInput::ScrollWheelUp:
                         new_mouse_event.bstate |= BUTTON4_PRESSED;
                         break;
                     case MouseInput::ScrollWheelDown:
                         new_mouse_event.bstate |= BUTTON5_PRESSED;
                         break;
 #endif
                     default:
                         break;
                 }
             }
             imtui_events.push_back( std::pair<int, ImTui::mouse_event>( KEY_MOUSE, new_mouse_event ) );
         } else {
             int ch = curses_input->get_first_input();
             if( ch != UNKNOWN_UNICODE ) {
                 imtui_events.push_back( std::pair<int, ImTui::mouse_event>( ch, new_mouse_event ) );
             }
         }
     }
 }
References input_event::get_first_input(), imtui_events, LeftButtonPressed, LeftButtonReleased, mouse, input_event::mouse_pos, RightButtonPressed, RightButtonReleased, ScrollWheelDown, ScrollWheelUp, input_event::sequence, input_event::type, UNKNOWN_UNICODE, point::x, and point::y.
set_alloced_pair_count()
void cataimgui::client::set_alloced_pair_count (short count)
Definition at line 85 of file cata_imgui.cpp.
 {
     ImTui_ImplNcurses_SetAllocedPairCount( count );
 }
upload_color_pair()
void cataimgui::client::upload_color_pair (int p, int f, int b)
Definition at line 79 of file cata_imgui.cpp.
 {
     ImTui_ImplNcurses_UploadColorPair( p, static_cast<short>( f ), static_cast<short>( b ) );
     cataimgui::init_pair( p, f, b );
 }
References b, and cataimgui::init_pair().
The documentation for this class was generated from the following files:
src/cata_imgui.h
src/cata_imgui.cpp