Cataclysm DDA: query_popup_impl Class Reference
query_popup_impl Class Reference
Public Member Functions
query_popup_impl (query_popup *parent)
void on_resized () override
int get_mouse_selected_option () const
Public Member Functions inherited from cataimgui::window
window (const std::string &id_, int window_flags=0)
virtual ~window ()
void draw_colored_text (std::string const &text, const nc_color &color, float wrap_width=0.0F, bool *is_selected=nullptr, bool *is_focused=nullptr, bool *is_hovered=nullptr)
void draw_colored_text (std::string const &text, nc_color &color, float wrap_width=0.0F, bool *is_selected=nullptr, bool *is_focused=nullptr, bool *is_hovered=nullptr)
bool action_button (const std::string &action, const std::string &text)
A button tied to a string action.
bool has_button_action ()
std::string get_button_action ()
void draw_header (std::string const &text)
bool get_is_open () const
virtual void draw ()
bool is_bounds_changed ()
size_t get_text_width (const std::string &text)
size_t get_text_height (const char *text)
size_t str_width_to_pixels (size_t len)
size_t str_height_to_pixels (size_t len)
std::string get_filter ()
void clear_filter ()
void mark_resized ()
Public Attributes
short keyboard_selected_option
Protected Member Functions
void draw_controls () override
cataimgui::bounds get_bounds () override
Protected Member Functions inherited from cataimgui::window
window (int window_flags=0)
void draw_filter (const input_context &ctxt, bool filtering_active)
Private Member Functions
std::vector< std::vector< std::string > > fold_query (const std::string &category, keyboard_mode pref_kbd_mode, const std::vector< query_popup::query_option > &options, int max_width, int horz_padding)
Private Attributes
short mouse_selected_option
size_t msg_width
nc_color default_text_color
query_popup * parent
short last_keyboard_selected_option
Additional Inherited Members
Protected Attributes inherited from cataimgui::window
bool force_to_back = false
bool is_open
std::string id
int window_flags
std::string button_action
Detailed Description
Definition at line 18 of file popup.cpp.
Constructor & Destructor Documentation
query_popup_impl()
query_popup_impl::query_popup_impl (query_popup * parent) inline explicit
Definition at line 34 of file popup.cpp.
                                                          : cataimgui::window( "QUERY_POPUP",
                     ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_AlwaysAutoResize ),
             default_text_color( c_white ) {
             msg_width = 400;
             this->parent = parent;
             keyboard_selected_option = 0;
             last_keyboard_selected_option = -1;
             mouse_selected_option = -1;
         }
References keyboard_selected_option, last_keyboard_selected_option, mouse_selected_option, msg_width, and parent.
Member Function Documentation
draw_controls()
void query_popup_impl::draw_controls () override protected virtual
Implements cataimgui::window.
Definition at line 56 of file popup.cpp.
 {
     mouse_selected_option = -1;
     for( const std::string &line : parent->folded_msg ) {
         nc_color col = parent->default_text_color;
         draw_colored_text( line, col, float( msg_width ) );
     }
     if( !parent->buttons.empty() ) {
         int current_line = 0;
         for( size_t ind = 0; ind < parent->buttons.size(); ++ind ) {
             if( ind != 0 && current_line == parent->buttons[ind].pos.y ) {
                 ImGui::SameLine();
             }
             ImGui::SetCursorPosX( float( parent->buttons[ind].pos.x ) );
             ImGui::Button( remove_color_tags( parent->buttons[ind].text ).c_str() );
             if( ImGui::IsItemHovered() ) {
                 mouse_selected_option = ind;
             }
             if( keyboard_selected_option != last_keyboard_selected_option &&
                 keyboard_selected_option == short( ind ) && ImGui::IsWindowFocused() ) {
                 ImGui::SetKeyboardFocusHere( -1 );
             }
             current_line = parent->buttons[ind].pos.y;
         }
     }
 }
References query_popup::buttons, query_popup::default_text_color, cataimgui::window::draw_colored_text(), query_popup::folded_msg, keyboard_selected_option, last_keyboard_selected_option, line, mouse_selected_option, msg_width, parent, and remove_color_tags().
fold_query()
std::vector< std::vector< std::string > > query_popup_impl::fold_query (const std::string & category, keyboard_mode pref_kbd_mode, const std::vector< query_popup::query_option > & options, int max_width, int horz_padding) private
Definition at line 229 of file popup.cpp.
 {
     input_context ctxt( category, pref_kbd_mode );
     std::vector<std::vector<std::string>> folded_query;
     folded_query.emplace_back();
     int query_cnt = 0;
     int query_width = 0;
     for( const query_popup::query_option &opt : options ) {
         const std::string &name = ctxt.get_action_name( opt.action );
         const std::string &desc = ctxt.get_desc( opt.action, name, opt.filter );
         const int this_query_width = get_text_width( remove_color_tags( desc ) ) + horz_padding;
         ++query_cnt;
         query_width += this_query_width;
         if( query_width > max_width + horz_padding ) {
             if( query_cnt == 1 ) {
                 // Each line has at least one query, so keep this query in the current line
                 folded_query.back().emplace_back( desc );
                 folded_query.emplace_back();
                 query_cnt = 0;
                 query_width = 0;
             } else {
                 // Wrap this query to the next line
                 folded_query.emplace_back();
                 folded_query.back().emplace_back( desc );
                 query_cnt = 1;
                 query_width = this_query_width;
             }
         } else {
             folded_query.back().emplace_back( desc );
         }
     }
     if( folded_query.back().empty() ) {
         folded_query.pop_back();
     }
     return folded_query;
 }
References anonymous_namespace{item_tname.cpp}::category(), input_context::get_action_name(), input_context::get_desc(), cataimgui::window::get_text_width(), om_direction::name(), PATH_INFO::options(), and remove_color_tags().
Referenced by on_resized().
get_bounds()
cataimgui::bounds query_popup_impl::get_bounds () inline override protected virtual
Reimplemented from cataimgui::window.
Definition at line 51 of file popup.cpp.
{
             return { -1.f, parent->ontop ? 0 : -1.f, -1.f, -1.f};
         }
References query_popup::ontop, and parent.
get_mouse_selected_option()
int query_popup_impl::get_mouse_selected_option () const inline
Definition at line 46 of file popup.cpp.
{
             return mouse_selected_option;
         }
References mouse_selected_option.
on_resized()
void query_popup_impl::on_resized () override virtual
Reimplemented from cataimgui::window.
Definition at line 85 of file popup.cpp.
 {
     size_t frame_padding = size_t( ImGui::GetStyle().FramePadding.x * 2 );
     size_t item_padding = size_t( ImGui::GetStyle().ItemSpacing.x );
     // constexpr size_t vert_padding = 1;
     size_t max_line_width = str_width_to_pixels( FULL_SCREEN_WIDTH );
     // Fold message text
     parent->folded_msg = foldstring( parent->text, max_line_width );
     // Fold query buttons
     const auto &folded_query = fold_query( parent->category, parent->pref_kbd_mode,
                                            parent->options, max_line_width,
                                            frame_padding + item_padding );
     // Calculate size of message part
     msg_width = 0;
     for( const auto &line : parent->folded_msg ) {
         msg_width = std::max( msg_width,
                               get_text_width( remove_color_tags( line ) ) ); //utf8_width( line, true ) );
     }
     auto btn_padding = [&frame_padding, &item_padding]( size_t num_buttons ) {
         return ( frame_padding * ( num_buttons - 1 ) ) + ( item_padding * ( num_buttons - 1 ) );
     };
     // Calculate width with query buttons
     for( const auto &line : folded_query ) {
         if( !line.empty() ) {
             int button_width = 0;
             for( const auto &opt : line ) {
                 button_width += get_text_width( remove_color_tags( opt ) );
             }
             // extra item padding needed here to account for space left at the beginning of the window by ImGui
             msg_width = std::max( msg_width, button_width + btn_padding( line.size() ) + item_padding );
         }
     }
     msg_width = std::min( msg_width, max_line_width );
     // Calculate height with query buttons & button positions
     parent->buttons.clear();
     size_t line_idx = 0;
     if( !folded_query.empty() ) {
         for( const auto &line : folded_query ) {
             if( !line.empty() ) {
                 int button_width = 0;
                 for( const auto &opt : line ) {
                     button_width += get_text_width( remove_color_tags( opt ) );
                 }
                 button_width += btn_padding( line.size() );
                 // Right align.
                 // TODO: multi-line buttons
                 size_t button_x = button_width > int( msg_width ) ? size_t( 0 ) :
                                   size_t( msg_width - button_width );
                 for( const auto &opt : line ) {
                     parent->buttons.emplace_back( opt, point( button_x, line_idx ) );
                     button_x += get_text_width( remove_color_tags( opt ) ) + frame_padding + item_padding;
                 }
             }
             line_idx++;
         }
     }
 }
References query_popup::buttons, query_popup::category, fold_query(), query_popup::folded_msg, foldstring(), FULL_SCREEN_WIDTH, cataimgui::window::get_text_width(), line, max(), min(), msg_width, query_popup::options, parent, point, query_popup::pref_kbd_mode, remove_color_tags(), cataimgui::window::str_width_to_pixels(), and query_popup::text.
Member Data Documentation
default_text_color
nc_color query_popup_impl::default_text_color private
Definition at line 22 of file popup.cpp.
keyboard_selected_option
short query_popup_impl::keyboard_selected_option
Definition at line 32 of file popup.cpp.
Referenced by draw_controls(), and query_popup_impl().
last_keyboard_selected_option
short query_popup_impl::last_keyboard_selected_option private
Definition at line 24 of file popup.cpp.
Referenced by draw_controls(), and query_popup_impl().
mouse_selected_option
short query_popup_impl::mouse_selected_option private
Definition at line 20 of file popup.cpp.
Referenced by draw_controls(), get_mouse_selected_option(), and query_popup_impl().
msg_width
size_t query_popup_impl::msg_width private
Definition at line 21 of file popup.cpp.
Referenced by draw_controls(), on_resized(), and query_popup_impl().
parent
query_popup* query_popup_impl::parent private
Definition at line 23 of file popup.cpp.
Referenced by draw_controls(), get_bounds(), on_resized(), and query_popup_impl().
The documentation for this class was generated from the following file:
src/popup.cpp