Cataclysm DDA: workout_activity_actor Class Reference
workout_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
workout_activity_actor (const tripoint &loc)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &, Character &) override
Called just before Character::cancel_activity() executes.
bool query_keep_training (player_activity &act, Character &who)
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
bool disable_query = false
bool rest_mode = false
time_duration duration
tripoint location
time_point stop_time
activity_id act_id = activity_id("ACT_WORKOUT_LIGHT")
int intensity_modifier = 1
int elapsed = 0
Detailed Description
Definition at line 974 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
workout_activity_actor()
workout_activity_actor::workout_activity_actor (const tripoint & loc) inline explicit
Definition at line 987 of file activity_actor_definitions.h.
 : location( loc ) {}
Referenced by deserialize().
Member Function Documentation
can_resume_with_internal()
bool workout_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 994 of file activity_actor_definitions.h.
{
             const workout_activity_actor &w_actor = static_cast<const workout_activity_actor &>( other );
             return ( location == w_actor.location && calendar::turn - stop_time <= 10_minutes );
         }
References location, other, stop_time, and calendar::turn.
canceled()
void workout_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 3981 of file activity_actor.cpp.
 {
     stop_time = calendar::turn;
 }
References stop_time, and calendar::turn.
clone()
std::unique_ptr<activity_actor> workout_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1006 of file activity_actor_definitions.h.
{
             return std::make_unique<workout_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > workout_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 4043 of file activity_actor.cpp.
 {
     workout_activity_actor actor = workout_activity_actor( tripoint_zero );
     JsonObject data = jsin.get_object();
     data.read( "disable_query", actor.disable_query );
     data.read( "act_id", actor.act_id );
     data.read( "duration", actor.duration );
     data.read( "location", actor.location );
     data.read( "stop_time", actor.stop_time );
     data.read( "elapsed", actor.elapsed );
     data.read( "intensity_modifier", actor.intensity_modifier );
     data.read( "rest_mode", actor.rest_mode );
     return actor.clone();
 }
References act_id, clone(), disable_query, duration, elapsed, JsonValue::get_object(), intensity_modifier, location, JsonObject::read(), rest_mode, stop_time, tripoint_zero, and workout_activity_actor().
do_turn()
void workout_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 3931 of file activity_actor.cpp.
 {
     if( who.get_sleepiness() > sleepiness_levels::DEAD_TIRED ) {
         who.add_msg_if_player( _( "You are exhausted so you finish your workout early." ) );
         act.set_to_null();
         return;
     }
     if( who.get_thirst() > 240 ) {
         who.add_msg_if_player( _( "You are dehydrated so you finish your workout early." ) );
         act.set_to_null();
         return;
     }
     if( !rest_mode && who.get_stamina() > who.get_stamina_max() / 3 ) {
         who.mod_stamina( -25 - intensity_modifier );
         if( one_in( 180 / intensity_modifier ) ) {
             who.mod_sleepiness( 1 );
             who.mod_thirst( 1 );
         }
         if( calendar::once_every( 16_minutes / intensity_modifier ) ) {
             //~ heavy breathing when exercising
             std::string huff = _( "yourself huffing and puffing!" );
             sounds::sound( location + tripoint_east, 2 * intensity_modifier, sounds::sound_t::speech, huff,
                            true );
         }
         // morale bonus kicks in gradually after 5 minutes of exercise
         if( calendar::once_every( 2_minutes ) &&
             ( ( elapsed + act.moves_total - act.moves_left ) / 100 * 1_turns ) > 5_minutes ) {
             who.add_morale( MORALE_FEELING_GOOD, intensity_modifier, 20, 6_hours, 30_minutes );
         }
         if( calendar::once_every( 2_minutes ) ) {
             add_msg_debug_if( who.is_avatar(), debugmode::DF_ACT_WORKOUT, who.activity_level_str() );
             add_msg_debug_if( who.is_avatar(), debugmode::DF_ACT_WORKOUT, act.id().c_str() );
         }
     } else if( !rest_mode ) {
         rest_mode = true;
         who.add_msg_if_player( _( "You catch your breath for few moments." ) );
     } else if( who.get_stamina() >= who.get_stamina_max() ) {
         rest_mode = false;
         who.add_msg_if_player( _( "You get back to your training." ) );
     }
 }
References _, act, Character::activity_level_str(), Character::add_morale(), add_msg_debug_if, Character::add_msg_if_player(), DEAD_TIRED, debugmode::DF_ACT_WORKOUT, elapsed, Character::get_sleepiness(), Character::get_stamina(), Character::get_stamina_max(), Character::get_thirst(), string_id< T >::id(), intensity_modifier, Creature::is_avatar(), location, Character::mod_sleepiness(), Character::mod_stamina(), Character::mod_thirst(), MORALE_FEELING_GOOD, calendar::once_every(), one_in(), rest_mode, sounds::sound(), sounds::speech, and tripoint_east.
finish()
void workout_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 3973 of file activity_actor.cpp.
 {
     if( !query_keep_training( act, who ) ) {
         act.set_to_null();
         who.add_msg_if_player( _( "You finish your workout session." ) );
     }
 }
References _, act, Character::add_msg_if_player(), and query_keep_training().
get_progress_message()
std::string workout_activity_actor::get_progress_message (const player_activity & act) const inline override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 1010 of file activity_actor_definitions.h.
{
             return std::string();
         }
get_type()
activity_id workout_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 990 of file activity_actor_definitions.h.
{
             return act_id;
         }
References act_id.
query_keep_training()
bool workout_activity_actor::query_keep_training (player_activity & act, Character & who)
Definition at line 3986 of file activity_actor.cpp.
 {
     if( disable_query || !who.is_avatar() ) {
         elapsed += act.moves_total - act.moves_left;
         act.moves_total = to_moves<int>( 60_minutes );
         act.moves_left = act.moves_total;
         return true;
     }
     int length;
     uilist workout_query;
     workout_query.text = _( "You have finished your training cycle, keep training?" );
     workout_query.addentry( 1, true, 'S', _( "Stop training." ) );
     workout_query.addentry( 2, true, 'c', _( "Continue training." ) );
     workout_query.addentry( 3, true, 'C', _( "Continue training and don't ask again." ) );
     workout_query.query();
     switch( workout_query.ret ) {
         case UILIST_CANCEL:
         case 1:
             act_id = activity_id::NULL_ID();
             act.set_to_null();
             return false;
         case 3:
             disable_query = true;
             elapsed += act.moves_total - act.moves_left;
             act.moves_total = to_moves<int>( 60_minutes );
             act.moves_left = act.moves_total;
             return true;
         case 2:
         default:
             query_int( length, _( "Train for how long (minutes): " ) );
             elapsed += act.moves_total - act.moves_left;
             duration = 0_minutes;
             if( length > 0 ) {
                 duration = length * 1_minutes;
             }
             act.moves_total = to_moves<int>( duration );
             act.moves_left = act.moves_total;
             return true;
     }
 }
References _, act, act_id, uilist::addentry(), disable_query, duration, elapsed, Creature::is_avatar(), length, string_id< activity_type >::NULL_ID(), uilist::query(), query_int(), uilist::ret, uilist::text, and UILIST_CANCEL.
Referenced by finish().
serialize()
void workout_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 4027 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "disable_query", disable_query );
     jsout.member( "act_id", act_id );
     jsout.member( "duration", duration );
     jsout.member( "location", location );
     jsout.member( "stop_time", stop_time );
     jsout.member( "elapsed", elapsed );
     jsout.member( "intensity_modifier", intensity_modifier );
     jsout.member( "rest_mode", rest_mode );
     jsout.end_object();
 }
References act_id, disable_query, duration, elapsed, JsonOut::end_object(), intensity_modifier, location, JsonOut::member(), rest_mode, JsonOut::start_object(), and stop_time.
start()
void workout_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 3824 of file activity_actor.cpp.
 {
     if( who.get_sleepiness() > sleepiness_levels::DEAD_TIRED ) {
         who.add_msg_if_player( _( "You are too tired to exercise." ) );
         act_id = activity_id::NULL_ID();
         act.set_to_null();
         return;
     }
     if( who.get_thirst() > 240 ) {
         who.add_msg_if_player( _( "You are too dehydrated to exercise." ) );
         act_id = activity_id::NULL_ID();
         act.set_to_null();
         return;
     }
     if( who.is_armed() ) {
         who.add_msg_if_player( _( "Empty your hands first." ) );
         act_id = activity_id::NULL_ID();
         act.set_to_null();
         return;
     }
     map &here = get_map();
     // free training requires all limbs intact, but specialized workout machines
     // train upper or lower parts of body only and may permit workout with
     // broken limbs as long as they are not involved by the machine
     bool hand_equipment = here.has_flag_furn( ter_furn_flag::TFLAG_WORKOUT_ARMS, location );
     bool leg_equipment = here.has_flag_furn( ter_furn_flag::TFLAG_WORKOUT_LEGS, location );
     if( hand_equipment && ( who.is_limb_broken( body_part_arm_l ) ||
                             who.is_limb_broken( body_part_arm_r ) ) ) {
         who.add_msg_if_player( _( "You cannot train here with a broken arm." ) );
         act_id = activity_id::NULL_ID();
         act.set_to_null();
         return;
     }
     if( leg_equipment && ( who.is_limb_broken( body_part_leg_l ) ||
                            who.is_limb_broken( body_part_leg_r ) ) ) {
         who.add_msg_if_player( _( "You cannot train here with a broken leg." ) );
         act_id = activity_id::NULL_ID();
         act.set_to_null();
         return;
     }
     if( !hand_equipment && !leg_equipment &&
         ( who.is_limb_broken( body_part_arm_l ) ||
           who.is_limb_broken( body_part_arm_r ) ||
           who.is_limb_broken( body_part_leg_l ) ||
           who.is_limb_broken( body_part_leg_r ) ) ) {
         who.add_msg_if_player( _( "You cannot train freely with a broken limb." ) );
         act_id = activity_id::NULL_ID();
         act.set_to_null();
         return;
     }
     uilist workout_query;
     workout_query.desc_enabled = true;
     workout_query.text =
         _( "Physical effort determines workout efficiency, but also rate of exhaustion." );
     workout_query.title = _( "Choose training intensity:" );
     workout_query.addentry_desc( 1, true, 'l', pgettext( "training intensity", "Light" ),
                                  _( "Light exercise comparable in intensity to walking, but more focused and methodical." ) );
     workout_query.addentry_desc( 2, true, 'm', pgettext( "training intensity", "Moderate" ),
                                  _( "Moderate exercise without excessive exertion, but with enough effort to break a sweat." ) );
     workout_query.addentry_desc( 3, true, 'a', pgettext( "training intensity", "Active" ),
                                  _( "Active exercise with full involvement.  Strenuous, but in a controlled manner." ) );
     workout_query.addentry_desc( 4, true, 'h', pgettext( "training intensity", "High" ),
                                  _( "High intensity exercise with maximum effort and full power.  Exhausting in the long run." ) );
     workout_query.query();
     switch( workout_query.ret ) {
         case UILIST_CANCEL:
             act.set_to_null();
             act_id = activity_id::NULL_ID();
             return;
         case 4:
             act_id = ACT_WORKOUT_HARD;
             intensity_modifier = 4;
             break;
         case 3:
             act_id = ACT_WORKOUT_ACTIVE;
             intensity_modifier = 3;
             break;
         case 2:
             act_id = ACT_WORKOUT_MODERATE;
             intensity_modifier = 2;
             break;
         case 1:
         default:
             act_id = ACT_WORKOUT_LIGHT;
             intensity_modifier = 1;
             break;
     }
     int length;
     query_int( length, _( "Train for how long (minutes): " ) );
     if( length > 0 ) {
         duration = length * 1_minutes;
     } else {
         act_id = activity_id::NULL_ID();
         act.set_to_null();
         return;
     }
     act.moves_total = to_moves<int>( duration );
     act.moves_left = act.moves_total;
     if( who.male ) {
         sfx::play_activity_sound( "plmove", "sleepiness_m_med", sfx::get_heard_volume( location ) );
     } else {
         sfx::play_activity_sound( "plmove", "sleepiness_f_med", sfx::get_heard_volume( location ) );
     }
     who.add_msg_if_player( _( "You start your workout session." ) );
 }
References _, act, act_id, ACT_WORKOUT_ACTIVE, ACT_WORKOUT_HARD, ACT_WORKOUT_LIGHT, ACT_WORKOUT_MODERATE, Character::add_msg_if_player(), uilist::addentry_desc(), body_part_arm_l, body_part_arm_r, body_part_leg_l, body_part_leg_r, DEAD_TIRED, uilist::desc_enabled, duration, sfx::get_heard_volume(), get_map(), Character::get_sleepiness(), Character::get_thirst(), map::has_flag_furn(), intensity_modifier, Character::is_armed(), Character::is_limb_broken(), length, location, Character::male, string_id< activity_type >::NULL_ID(), pgettext, sfx::play_activity_sound(), uilist::query(), query_int(), uilist::ret, uilist::text, TFLAG_WORKOUT_ARMS, TFLAG_WORKOUT_LEGS, uilist::title, and UILIST_CANCEL.
Member Data Documentation
act_id
activity_id workout_activity_actor::act_id = activity_id("ACT_WORKOUT_LIGHT") private
Definition at line 982 of file activity_actor_definitions.h.
Referenced by deserialize(), get_type(), query_keep_training(), serialize(), and start().
disable_query
bool workout_activity_actor::disable_query = false private
Definition at line 977 of file activity_actor_definitions.h.
Referenced by deserialize(), query_keep_training(), and serialize().
duration
time_duration workout_activity_actor::duration private
Definition at line 979 of file activity_actor_definitions.h.
Referenced by deserialize(), query_keep_training(), serialize(), and start().
elapsed
int workout_activity_actor::elapsed = 0 private
Definition at line 984 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), query_keep_training(), and serialize().
intensity_modifier
int workout_activity_actor::intensity_modifier = 1 private
Definition at line 983 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), serialize(), and start().
location
tripoint workout_activity_actor::location private
Definition at line 980 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), do_turn(), serialize(), and start().
rest_mode
bool workout_activity_actor::rest_mode = false private
Definition at line 978 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
stop_time
time_point workout_activity_actor::stop_time private
Definition at line 981 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), canceled(), deserialize(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp