Cataclysm DDA: shearing_activity_actor Class Reference
shearing_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
shearing_activity_actor (const tripoint &mon_coords, bool shearing_tie=true)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &, Character &) override
Called just before Character::cancel_activity() executes.
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
tripoint mon_coords
bool shearing_tie
Detailed Description
Definition at line 1218 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
shearing_activity_actor()
shearing_activity_actor::shearing_activity_actor (const tripoint & mon_coords, bool shearing_tie = true) inline explicit
Definition at line 1225 of file activity_actor_definitions.h.
             : mon_coords( mon_coords ), shearing_tie( shearing_tie ) {};
Referenced by deserialize().
Member Function Documentation
can_resume_with_internal()
bool shearing_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 1238 of file activity_actor_definitions.h.
{
             const shearing_activity_actor &actor = static_cast<const shearing_activity_actor &>
                                                    ( other );
             return actor.mon_coords == mon_coords;
         }
References mon_coords, and other.
canceled()
void shearing_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 5117 of file activity_actor.cpp.
 {
     monster *mon = get_creature_tracker().creature_at<monster>( mon_coords );
     if( !mon ) {
         return;
     }
     if( shearing_tie ) {
         // free the poor critter
         mon->remove_effect( effect_tied );
     }
 }
References creature_tracker::creature_at(), effect_tied, get_creature_tracker(), mon_coords, Creature::remove_effect(), and shearing_tie.
clone()
std::unique_ptr<activity_actor> shearing_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1245 of file activity_actor_definitions.h.
{
             return std::make_unique<shearing_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > shearing_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 5138 of file activity_actor.cpp.
 {
     shearing_activity_actor actor = shearing_activity_actor( {} );
     JsonObject data = jsin.get_object();
     data.read( "mon_coords", actor.mon_coords );
     data.read( "shearing_tie", actor.shearing_tie );
     return actor.clone();
 }
References clone(), JsonValue::get_object(), mon_coords, JsonObject::read(), shearing_activity_actor(), and shearing_tie.
do_turn()
void shearing_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 5046 of file activity_actor.cpp.
 {
     if( !who.has_quality( qual_SHEAR ) ) {
         if( who.is_avatar() ) {
             add_msg(
                 m_bad,
                 _( "%1$s don't have a shearing tool anymore." ),
                 who.disp_name( false, true ) );
         } else {
             add_msg_if_player_sees(
                 who,
                 _( "%1$s doesn't have a shearing tool anymore." ),
                 who.disp_name() );
         }
         who.cancel_activity();
     }
 }
References _, add_msg(), add_msg_if_player_sees(), Character::cancel_activity(), Character::disp_name(), Character::has_quality(), Creature::is_avatar(), m_bad, and qual_SHEAR.
finish()
void shearing_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 5064 of file activity_actor.cpp.
 {
     monster *mon = get_creature_tracker().creature_at<monster>( mon_coords );
     if( !mon ) {
         debugmsg( "shearing monster at position disappeared" );
         act.set_to_null();
         return;
     }
     const shearing_data &shear_data = mon->type->shearing;
     if( !shear_data.valid() ) {
         debugmsg( "shearing monster does not have shearing_data" );
         if( shearing_tie ) {
             mon->remove_effect( effect_tied );
         }
         act.set_to_null();
         return;
     }
     map &mp = get_map();
     add_msg_if_player_sees( who,
                             string_format(
                                 _( "%1$s finished shearing %2$s and got:" ),
                                 who.disp_name( false, true ),
                                 mon->unique_name.empty() ? mon->disp_name() : mon->unique_name ) );
     const std::vector<shearing_roll> shear_roll = shear_data.roll_all( *mon );
     for( const shearing_roll &roll : shear_roll ) {
         if( roll.result->count_by_charges() ) {
             item shear_item( roll.result, calendar::turn, roll.amount );
             mp.add_item_or_charges( who.pos(), shear_item );
             add_msg_if_player_sees( who, shear_item.display_name() );
         } else {
             item shear_item( roll.result, calendar::turn );
             for( int i = 0; i < roll.amount; ++i ) {
                 mp.add_item_or_charges( who.pos(), shear_item );
             }
             add_msg_if_player_sees( who,
                                     //~ %1$s - item, %2$d - amount
                                     string_format( _( "%1$s x%2$d" ),
                                                    shear_item.display_name(), roll.amount ) );
         }
     }
     mon->add_effect( effect_sheared, calendar::season_length() );
     if( shearing_tie ) {
         mon->remove_effect( effect_tied );
     }
     act.set_to_null();
 }
References _, act, Creature::add_effect(), map::add_item_or_charges(), add_msg_if_player_sees(), creature_tracker::creature_at(), debugmsg, Character::disp_name(), monster::disp_name(), item::display_name(), effect_sheared, effect_tied, get_creature_tracker(), get_map(), mon_coords, Creature::pos(), Creature::remove_effect(), shearing_data::roll_all(), calendar::season_length(), mtype::shearing, shearing_tie, string_format(), calendar::turn, monster::type, monster::unique_name, and shearing_data::valid().
get_type()
activity_id shearing_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1229 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_SHEARING" );
         }
References activity_id.
serialize()
void shearing_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 5130 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "mon_coords", mon_coords );
     jsout.member( "shearing_tie", shearing_tie );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), mon_coords, shearing_tie, and JsonOut::start_object().
start()
void shearing_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 4992 of file activity_actor.cpp.
 {
     monster *mon = get_creature_tracker().creature_at<monster>( mon_coords );
     if( !mon ) {
         debugmsg( "shearing lost monster when starting" );
         act.set_to_null();
         return;
     }
     std::string pet_name_capitalized = mon->unique_name.empty() ? mon->disp_name( false,
                                        true ) : mon->unique_name;
     if( !mon->shearable() ) {
         add_msg( _( "%1$s has nothing %2$s could shear." ), pet_name_capitalized, who.disp_name() );
         if( shearing_tie ) {
             mon->remove_effect( effect_tied );
         }
         act.set_to_null();
         return;
     }
     const int shearing_quality = who.max_quality( qual_SHEAR );
     if( !( shearing_quality > 0 ) ) {
         if( who.is_avatar() ) {
             add_msg( m_info, _( "%1$s don't have a shearing tool." ), who.disp_name( false, true ) );
         } else { // who.is_npc
             // npcs can't shear monsters yet, this is for when they are able to
             add_msg_if_player_sees( who, _( "%1$s doesn't have a shearing tool." ), who.disp_name(),
                                     mon->disp_name() );
         }
         if( shearing_tie ) {
             mon->remove_effect( effect_tied );
         }
         act.set_to_null();
         return;
     }
     const time_duration shearing_time = 30_minutes / shearing_quality;
     add_msg_debug( debugmode::DF_ACT_SHEARING, "shearing_time time = %s",
                    to_string_writable( shearing_time ) );
     if( who.is_avatar() ) {
         add_msg( m_info,
                  _( "%1$s start shearing %2$s." ), who.disp_name( false, true ), mon->disp_name() );
     } else { // who.is_npc
         // npcs can't shear monsters yet, this is for when they are able to
         add_msg_if_player_sees( who, _( "%1$s starts shearing %2$s." ), who.disp_name(),
                                 mon->disp_name() );
     }
     act.moves_total = to_moves<int>( shearing_time );
     act.moves_left = act.moves_total;
 }
References _, act, add_msg(), add_msg_debug, add_msg_if_player_sees(), creature_tracker::creature_at(), debugmsg, debugmode::DF_ACT_SHEARING, Character::disp_name(), monster::disp_name(), effect_tied, get_creature_tracker(), Creature::is_avatar(), m_info, Character::max_quality(), mon_coords, qual_SHEAR, Creature::remove_effect(), monster::shearable(), shearing_tie, to_string_writable(), and monster::unique_name.
Member Data Documentation
mon_coords
tripoint shearing_activity_actor::mon_coords private
Definition at line 1221 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), canceled(), deserialize(), finish(), serialize(), and start().
shearing_tie
bool shearing_activity_actor::shearing_tie private
Definition at line 1222 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), finish(), serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp