Cataclysm DDA: stomach_contents Class Reference
stomach_contents Class Reference
#include <stomach.h>
Public Member Functions
stomach_contents ()
stomach_contents (units::volume max_volume, bool is_stomach)
Construct a new stomach contents object Stomachs always process their food in a few hours.
void ingest (const food_summary &ingested)
Directly adds food to stomach contents.
food_summary digest (const Character &owner, const needs_rates &metabolic_rates, int five_mins, int half_hours)
Processes food and outputs nutrients that are finished processing Metabolic rates are required because they determine the rate of absorption of nutrients into the body.
void empty ()
units::volume capacity (const Character &owner) const
Calculates the capacity of this stomach.
units::volume stomach_remaining (const Character &owner) const
units::volume contains () const
int get_calories () const
units::volume get_water () const
void mod_calories (int kcal)
void mod_nutr (int nutr)
void mod_water (const units::volume &h2o)
void mod_quench (int quench)
void mod_contents (const units::volume &vol)
time_duration time_since_ate () const
void ate ()
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
Private Member Functions
stomach_digest_rates get_digest_rates (const needs_rates &metabolic_rates, const Character &owner) const
Private Attributes
bool stomach = false
nutrients nutr
units::volume water = 0_ml
units::volume max_volume = 0_ml
this is the maximum volume without modifiers such as mutations in order to get the maximum volume with all modifiers properly, call stomach_capacity()
units::volume contents = 0_ml
time_point last_ate = calendar::turn_zero
Detailed Description
Definition at line 119 of file stomach.h.
Constructor & Destructor Documentation
stomach_contents() [1/2]
stomach_contents::stomach_contents () default
stomach_contents() [2/2]
stomach_contents::stomach_contents (units::volume max_volume, bool is_stomach)
Construct a new stomach contents object Stomachs always process their food in a few hours.
Guts take significantly longer, and their rate is dependent on the metabolic rate of their owner.
Parameters
max_volume Base capacity, subject to modification, i.e. by traits
is_stomach If true, treated as stomach, if false, treated as guts
Definition at line 242 of file stomach.cpp.
 {
     max_volume = max_vol;
     stomach = is_stomach;
     last_ate = calendar::before_time_starts;
 }
References calendar::before_time_starts, last_ate, max_volume, and stomach.
Member Function Documentation
ate()
void stomach_contents::ate ()
Definition at line 452 of file stomach.cpp.
 {
     last_ate = calendar::turn;
 }
References last_ate, and calendar::turn.
Referenced by ingest().
capacity()
units::volume stomach_contents::capacity (const Character & owner) const
Calculates the capacity of this stomach.
This function needs a ref to the stomach's owner so it can account for relevant mutations. TODO: JSONize stomach capacity multipliers.
Parameters
owner This stomach's owner
Returns
This stomach's capacity, in units::volume
Definition at line 305 of file stomach.cpp.
 {
     return owner.enchantment_cache->modify_value( enchant_vals::mod::STOMACH_SIZE_MULTIPLIER,
             max_volume );
 }
References Character::enchantment_cache, max_volume, and enchant_vals::STOMACH_SIZE_MULTIPLIER.
Referenced by Character::check_needs_extremes(), npc::consume_food_from_camp(), debug_menu::debug_menu_game_state(), player_activity::do_turn(), eat(), get_digest_rates(), marloss_common(), stomach_remaining(), and Character::update_stomach().
contains()
units::volume stomach_contents::contains () const
Definition at line 316 of file stomach.cpp.
 {
     return contents + water;
 }
References contents, and water.
Referenced by debug_menu::character_edit_needs_menu(), Character::check_needs_extremes(), npc::consume_food_from_camp(), debug_menu::debug_menu_game_state(), player_activity::do_turn(), eat(), suffer::from_radiation(), marloss_common(), Character::update_stomach(), avatar::vomit(), Character::vomit(), and Character::vomit_mod().
deserialize()
void stomach_contents::deserialize (const JsonObject & jo)
Definition at line 271 of file stomach.cpp.
 {
     std::map<vitamin_id, int> vitamins;
     jo.read( "vitamins", vitamins );
     for( const std::pair<const vitamin_id, int> &vit : vitamins ) {
         nutr.set_vitamin( vit.first, vit.second );
     }
     jo.read( "calories", nutr.calories );
     std::string str;
     jo.read( "water", str );
     water = string_to_ml( str );
     jo.read( "max_volume", str );
     max_volume = string_to_ml( str );
     jo.read( "contents", str );
     contents = string_to_ml( str );
     jo.read( "last_ate", last_ate );
     // the next chunk deletes obsoleted vitamins
     const auto predicate = []( const std::pair<vitamin_id, int> &pair ) {
         if( !pair.first.is_valid() ) {
             DebugLog( D_WARNING, DC_ALL )
                     << "deleted '" << pair.first.str() << "' from stomach_contents::nutrients::vitamins";
             return true;
         }
         return false;
     };
     std::map<vitamin_id, int> vit = nutr.vitamins();
     for( const std::pair<const vitamin_id, int> &pair : vit ) {
         if( predicate( pair ) ) {
             nutr.remove_vitamin( pair.first );
         }
     }
 }
References nutrients::calories, contents, D_WARNING, DC_ALL, DebugLog(), last_ate, max_volume, nutr, JsonObject::read(), nutrients::remove_vitamin(), nutrients::set_vitamin(), string_to_ml(), nutrients::vitamins(), and water.
digest()
food_summary stomach_contents::digest (const Character & owner, const needs_rates & metabolic_rates, int five_mins, int half_hours)
Processes food and outputs nutrients that are finished processing Metabolic rates are required because they determine the rate of absorption of nutrients into the body.
All returned values are >= 0, with the exception of water, which can be negative in some circumstances (i.e. after eating dry/salty food). TODO: Update stomach capacity upon mutation changes, instead of calculating every time we need it, so we can get rid of 'owner' parameter here.
Parameters
owner The owner of this stomach
metabolic_rates The metabolic rates of the owner of this stomach
five_mins Five-minute intervals passed since this method was last called
half_hours Half-hour intervals passed since this method was last called
Returns
nutrients that are done processing in this stomach
Definition at line 329 of file stomach.cpp.
 {
     food_summary digested;
     stomach_digest_rates rates = get_digest_rates( metabolic_rates, owner );
     // Digest water, but no more than in stomach.
     digested.water = std::min( water, rates.water * five_mins );
     water -= digested.water;
     // If no half-hour intervals have passed, we only process water, so bail out early.
     if( half_hours == 0 ) {
         return digested;
     }
     // Digest solids, but no more than in stomach.
     digested.solids = std::min( contents, rates.solids * half_hours );
     contents -= digested.solids;
     // Digest kCal -- use min_kcal by default, but no more than what's in stomach,
     // and no less than percentage_kcal of what's in stomach.
     int kcal_fraction = std::lround( nutr.kcal() * rates.percent_kcal );
     digested.nutr.calories = half_hours * clamp<int64_t>( rates.min_calories, kcal_fraction * 1000,
                              nutr.calories );
     // Digest vitamins just like we did kCal, but we need to do one at a time.
     for( const std::pair<const vitamin_id, int> &vit : nutr.vitamins() ) {
         if( vit.first->type() != vitamin_type::DRUG ) {
             int vit_fraction = std::lround( vit.second * rates.percent_vitamin );
             digested.nutr.set_vitamin( vit.first, half_hours * clamp( rates.min_vitamin, vit_fraction,
                                        vit.second ) );
         }
         // drug vitamins are absorbed to the blood instantly after the first stomach step.
         // this makes the drug vitamins easier to balance (no need to account for slow trickle-ing in of the drug)
         else if( vit.first->type() == vitamin_type::DRUG && stomach ) {
             digested.nutr.set_vitamin( vit.first, vit.second );
         }
     }
     nutr -= digested.nutr;
     return digested;
 }
References nutrients::calories, clamp(), contents, DRUG, get_digest_rates(), nutrients::kcal(), min(), stomach_digest_rates::min_calories, stomach_digest_rates::min_vitamin, food_summary::nutr, nutr, stomach_digest_rates::percent_kcal, stomach_digest_rates::percent_vitamin, nutrients::set_vitamin(), food_summary::solids, stomach_digest_rates::solids, stomach, nutrients::vitamins(), food_summary::water, stomach_digest_rates::water, and water.
Referenced by Character::update_stomach().
empty()
void stomach_contents::empty ()
Definition at line 372 of file stomach.cpp.
 {
     nutr = nutrients{};
     water = 0_ml;
     contents = 0_ml;
 }
References contents, nutr, and water.
Referenced by debug_menu::character_edit_needs_menu(), tutorial_game::per_turn(), player_difficulty::reset_npc(), and Character::vomit().
get_calories()
int stomach_contents::get_calories () const
Definition at line 442 of file stomach.cpp.
 {
     return nutr.kcal();
 }
References nutrients::kcal(), and nutr.
Referenced by npc::address_needs(), debug_menu::character_edit_needs_menu(), npc::consume_food_from_camp(), debug_menu::debug_menu_game_state(), Character::update_stomach(), and npc::value().
get_digest_rates()
stomach_digest_rates stomach_contents::get_digest_rates (const needs_rates & metabolic_rates, const Character & owner) const private
Definition at line 379 of file stomach.cpp.
 {
     stomach_digest_rates rates;
     if( stomach ) {
         // The stomach is focused on passing material on to the guts.
         // 3 hours to empty in 30 minute increments
         rates.solids = capacity( owner ) / 6;
         rates.water = 250_ml; // Water is special, passes very quickly, in 5 minute intervals
         rates.min_vitamin = 1;
         rates.percent_vitamin = 1.0f / 6.0f;
         rates.min_calories = 5000;
         rates.percent_kcal = 1.0f / 6.0f;
     } else {
         // The guts are focused on absorption into the body, we don't care about passing rates.
         // Solids rate doesn't do anything impactful here so just make it big enough to avoid overflow.
         rates.solids = 250_ml;
         rates.water = 250_ml;
         // Explicitly floor it, because casting it to an int will do so anyways
         rates.min_calories = std::floor( metabolic_rates.kcal / 24.0 * metabolic_rates.hunger * 1000 );
         rates.percent_kcal = 0.05f * metabolic_rates.hunger;
         rates.min_vitamin = std::round( 100.0 / 24.0 * metabolic_rates.hunger );
         rates.percent_vitamin = 0.05f * metabolic_rates.hunger;
     }
     return rates;
 }
References capacity(), floor(), needs_rates::hunger, needs_rates::kcal, stomach_digest_rates::min_calories, stomach_digest_rates::min_vitamin, stomach_digest_rates::percent_kcal, stomach_digest_rates::percent_vitamin, round(), stomach_digest_rates::solids, stomach, and stomach_digest_rates::water.
Referenced by digest().
get_water()
units::volume stomach_contents::get_water () const
Definition at line 447 of file stomach.cpp.
 {
     return water;
 }
References water.
Referenced by debug_menu::character_edit_needs_menu(), Character::check_needs_extremes(), Character::consume_effects(), debug_menu::debug_menu_game_state(), Character::get_instant_thirst(), and npc::get_thirst().
ingest()
void stomach_contents::ingest (const food_summary & ingested)
Directly adds food to stomach contents.
Will still add contents if past maximum volume. Also updates last_ate to current turn.
Parameters
ingested The food to be ingested
Definition at line 321 of file stomach.cpp.
 {
     contents += ingested.solids;
     water += ingested.water;
     nutr += ingested.nutr;
     ate();
 }
References ate(), contents, food_summary::nutr, nutr, food_summary::solids, food_summary::water, and water.
Referenced by Character::consume_effects(), npc::consume_food_from_camp(), and Character::update_stomach().
mod_calories()
void stomach_contents::mod_calories (int kcal)
Definition at line 406 of file stomach.cpp.
 {
     if( -kcal >= nutr.kcal() ) {
         nutr.calories = 0;
         return;
     }
     nutr.calories += kcal * 1000;
 }
References nutrients::calories, nutrients::kcal(), and nutr.
Referenced by debug_menu::character_edit_needs_menu(), Character::initialize_stomach_contents(), marloss_common(), and mod_nutr().
mod_contents()
void stomach_contents::mod_contents (const units::volume & vol)
Definition at line 433 of file stomach.cpp.
 {
     if( -vol >= contents ) {
         contents = 0_ml;
         return;
     }
     contents += vol;
 }
References contents.
Referenced by Character::initialize_stomach_contents(), and marloss_common().
mod_nutr()
void stomach_contents::mod_nutr (int nutr)
Definition at line 415 of file stomach.cpp.
 {
     // nutr is legacy type code, this function simply converts old nutrition to new kcal
     mod_calories( -1 * std::round( nutr * base_metabolic_rate / ( 12 * 24 ) ) );
 }
References base_metabolic_rate, mod_calories(), nutr, and round().
Referenced by alcohol(), iuse::antiparasitic(), iuse::blech(), and iuse::plantblech().
mod_quench()
void stomach_contents::mod_quench (int quench)
Definition at line 428 of file stomach.cpp.
 {
     mod_water( 5_ml * quench );
 }
References mod_water().
Referenced by iuse::blech().
mod_water()
void stomach_contents::mod_water (const units::volume & h2o)
Definition at line 421 of file stomach.cpp.
 {
     if( h2o > 0_ml ) {
         water += h2o;
     }
 }
References water.
Referenced by mod_quench().
serialize()
void stomach_contents::serialize (JsonOut & json) const
Definition at line 254 of file stomach.cpp.
 {
     json.start_object();
     json.member( "vitamins", nutr.vitamins() );
     json.member( "calories", nutr.calories );
     json.member( "water", ml_to_string( water ) );
     json.member( "max_volume", ml_to_string( max_volume ) );
     json.member( "contents", ml_to_string( contents ) );
     json.member( "last_ate", last_ate );
     json.end_object();
 }
References nutrients::calories, contents, JsonOut::end_object(), last_ate, max_volume, JsonOut::member(), ml_to_string(), nutr, JsonOut::start_object(), nutrients::vitamins(), and water.
stomach_remaining()
units::volume stomach_contents::stomach_remaining (const Character & owner) const
Definition at line 311 of file stomach.cpp.
 {
     return capacity( owner ) - contents - water;
 }
References capacity(), contents, and water.
Referenced by eat(), and Character::will_eat().
time_since_ate()
time_duration stomach_contents::time_since_ate () const
Definition at line 457 of file stomach.cpp.
 {
     return calendar::turn - last_ate;
 }
References last_ate, and calendar::turn.
Referenced by Character::update_stomach().
Member Data Documentation
contents
units::volume stomach_contents::contents = 0_ml private
Definition at line 214 of file stomach.h.
Referenced by contains(), deserialize(), digest(), empty(), ingest(), mod_contents(), serialize(), and stomach_remaining().
last_ate
time_point stomach_contents::last_ate = calendar::turn_zero private
Definition at line 216 of file stomach.h.
Referenced by ate(), deserialize(), serialize(), stomach_contents(), and time_since_ate().
max_volume
units::volume stomach_contents::max_volume = 0_ml private
this is the maximum volume without modifiers such as mutations in order to get the maximum volume with all modifiers properly, call stomach_capacity()
Definition at line 212 of file stomach.h.
Referenced by capacity(), deserialize(), serialize(), and stomach_contents().
nutr
nutrients stomach_contents::nutr private
Definition at line 204 of file stomach.h.
Referenced by deserialize(), digest(), empty(), get_calories(), ingest(), mod_calories(), mod_nutr(), and serialize().
stomach
bool stomach_contents::stomach = false private
Definition at line 201 of file stomach.h.
Referenced by digest(), get_digest_rates(), and stomach_contents().
water
units::volume stomach_contents::water = 0_ml private
Definition at line 206 of file stomach.h.
Referenced by contains(), deserialize(), digest(), empty(), get_water(), ingest(), mod_water(), serialize(), and stomach_remaining().
The documentation for this class was generated from the following files:
src/stomach.h
src/stomach.cpp