Cataclysm DDA: inventory_insert_selector Class Reference
inventory_insert_selector Class Reference
#include <inventory_ui.h>
Public Member Functions
inventory_insert_selector (Character &p, const inventory_holster_preset &preset, const std::string &selection_column_title=_("ITEMS TO INSERT"), bool warn_liquid=true)
Public Member Functions inherited from inventory_drop_selector
inventory_drop_selector (Character &p, const inventory_selector_preset &preset=default_preset, const std::string &selection_column_title=_("ITEMS TO DROP"), bool warn_liquid=true)
drop_locations execute ()
Public Member Functions inherited from inventory_multiselector
inventory_multiselector (Character &p, const inventory_selector_preset &preset=default_preset, const std::string &selection_column_title="", const GetStats &={}, bool allow_select_contained=false)
drop_locations execute (bool allow_empty=false)
void toggle_entry (inventory_entry &entry, size_t count)
Public Member Functions inherited from inventory_selector
inventory_selector (Character &u, const inventory_selector_preset &preset=default_preset)
virtual ~inventory_selector ()
bool add_contained_items (item_location &container)
These functions add items from map / vehicles.
bool add_contained_items (item_location &container, inventory_column &column, const item_category *custom_category=nullptr, item_location const &topmost_parent={}, int indent=0)
void add_contained_gunmods (Character &you, item &gun)
void add_contained_ebooks (item_location &container)
void add_character_items (Character &character)
void add_map_items (const tripoint &target)
void add_vehicle_items (const tripoint &target)
void add_nearby_items (int radius=1)
void add_remote_map_items (tinymap *remote_map, const tripoint &target)
void add_basecamp_items (const basecamp &camp)
void clear_items ()
Remove all items.
void set_title (const std::string &title)
Assigns a title that will be shown on top of the menu.
void set_hint (const std::string &hint)
Assigns a hint.
void set_display_stats (bool display_stats)
Specify whether the header should show stats (weight and volume).
bool empty () const
bool has_available_choices () const
uint64_t item_entry_count () const
drop_location get_only_choice () const
void set_filter (const std::string &str)
Apply filter string to all columns.
std::string get_filter () const
Get last filter string set by set_filter or entered by player.
void set_invlet_type (selector_invlet_type type)
Set the letter group to use for automatic inventory letters.
selector_invlet_type invlet_type ()
void show_invlet (bool show)
Set whether to show inventory letters.
bool showing_invlet () const
void categorize_map_items (bool toggle)
bool highlight (const item_location &loc, bool hidden=false, bool front_only=false)
Highlight a location.
const inventory_entry & get_highlighted () const
item_location get_collation_next () const
void highlight_position (std::pair< size_t, size_t > position)
bool highlight_one_of (const std::vector< item_location > &locations, bool hidden=false)
std::pair< size_t, size_t > get_highlighted_position () const
inventory_column & get_column (size_t index) const
inventory_column & get_active_column () const
void toggle_categorize_contained ()
void set_active_column (size_t index)
void toggle_skip_unselectable ()
std::string action_bound_to_key (char key) const
Protected Member Functions
stats get_raw_stats () const override
Get stats to display in top right.
Protected Member Functions inherited from inventory_multiselector
void rearrange_columns (size_t client_width) override
Tackles screen overflow.
void set_chosen_count (inventory_entry &entry, size_t count)
void deselect_contained_items ()
void toggle_entries (int &count, toggle_mode mode=toggle_mode::SELECTED)
virtual void on_toggle ()
void on_input (const inventory_input &input)
void toggle_categorize_contained ()
Protected Member Functions inherited from inventory_selector
const item_category * naturalize_category (const item_category &category, const tripoint &pos)
inventory_entry * add_entry (inventory_column &target_column, std::vector< item_location > &&locations, const item_category *custom_category=nullptr, size_t chosen_count=0, item_location const &topmost_parent={}, bool chevron=false)
bool add_entry_rec (inventory_column &entry_column, inventory_column &children_column, item_location &loc, item_category const *entry_category=nullptr, item_category const *children_category=nullptr, item_location const &topmost_parent={}, int indent=0)
bool drag_drop_item (item *sourceItem, item *destItem)
inventory_input get_input ()
inventory_input process_input (const std::string &action, int ch)
void on_input (const inventory_input &input)
Given an action from the input_context, try to act according to it.
void on_change (const inventory_entry &entry)
Entry has been changed.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
size_t get_layout_width () const
size_t get_layout_height () const
std::pair< bool, std::string > query_string (const std::string &val, bool end_with_toggle=false)
Query user for a string and return it.
void query_set_filter ()
Query the user for a filter and apply it.
int query_count (char init=0, bool end_with_toggle=false)
Query the user for count and return it.
std::vector< std::string > get_stats () const
std::pair< std::string, nc_color > get_footer (navigation_mode m) const
size_t get_header_height () const
size_t get_header_min_width () const
size_t get_footer_min_width () const
inventory_entry * find_entry_by_invlet (int invlet) const
inventory_entry * find_entry_by_coordinate (const point &coordinate) const
inventory_entry * find_entry_by_location (item_location &loc) const
const std::vector< inventory_column * > & get_all_columns () const
std::vector< inventory_column * > get_visible_columns () const
void highlight ()
Highlight parent and contents of highlighted item.
void action_examine (const item_location &sitem)
Show detailed item information for the selected item.
virtual void reassign_custom_invlets ()
size_t get_columns_width (const std::vector< inventory_column * > &columns) const
double get_columns_occupancy_ratio (size_t client_width) const
bool are_columns_centered (size_t client_width) const
bool is_overflown (size_t client_width) const
bool is_active_column (const inventory_column &column) const
void append_column (inventory_column &column)
void toggle_active_column (scroll_direction dir)
Activates either previous or next column.
void refresh_active_column ()
void toggle_navigation_mode ()
const navigation_mode_data & get_navigation_data (navigation_mode m) const
Additional Inherited Members
Public Types inherited from inventory_multiselector
using GetStats = std::function< stats(const std::vector< std::pair< item_location, int > >)>
Public Types inherited from inventory_selector
enum selector_invlet_type { SELECTOR_INVLET_DEFAULT , SELECTOR_INVLET_NUMERIC , SELECTOR_INVLET_ALPHA }
enum class uimode : int { categories = 0 , hierarchy , last }
using stat = std::array< std::string, 4 >
using stats = std::array< stat, 3 >
Static Protected Member Functions inherited from inventory_selector
static stat get_weight_and_length_stat (units::mass weight_carried, units::mass weight_capacity, const units::length &longest_length)
static stat get_volume_stat (const units::volume &volume_carried, const units::volume &volume_capacity, const units::volume &largest_free_volume)
static stat get_holster_stat (const units::volume &holster_volume, int used_holsters, int total_holsters)
static stats get_weight_and_volume_and_holster_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume &volume_carried, const units::volume &volume_capacity, const units::length &longest_length, const units::volume &largest_free_volume, const units::volume &holster_volume, int used_holsters, int total_holsters)
Protected Attributes inherited from inventory_multiselector
size_t max_chosen_count
std::vector< std::pair< item_location, int > > to_use
std::vector< item_location > usable_locs
bool allow_select_contained
int count = 0
Protected Attributes inherited from inventory_selector
Character & u
const inventory_selector_preset & preset
input_context ctxt
The input context for navigation, already contains some actions for movement.
std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * > > rect_entry_map
std::vector< inventory_column * > columns
point _fixed_origin { -1, -1 }
point _fixed_size { -1, -1 }
bool _categorize_map_items = false
bool force_single_column = false
Detailed Description
Definition at line 1032 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_insert_selector()
inventory_insert_selector::inventory_insert_selector (Character & p, const inventory_holster_preset & preset, const std::string & selection_column_title = _("ITEMS TO INSERT"), bool warn_liquid = true) explicit
Definition at line 3831 of file inventory_ui.cpp.
                                  :
     inventory_drop_selector( p, preset, selection_column_title, warn_liquid )
 {
 #if defined(__ANDROID__)
     // allow user to type a drop number without dismissing virtual keyboard after each keypress
     ctxt.allow_text_entry = true;
 #endif
 }
References inventory_selector::ctxt.
Member Function Documentation
get_raw_stats()
inventory_selector::stats inventory_insert_selector::get_raw_stats () const override protected virtual
Get stats to display in top right.
By default, computes volume/weight numbers for u
Reimplemented from inventory_drop_selector.
Definition at line 4057 of file inventory_ui.cpp.
 {
     units::mass selected_weight = units::mass();
     units::volume selected_volume = units::volume();
     const item_location &holster = static_cast<const inventory_holster_preset &>
                                    ( preset ).get_holster();
     const std::vector<inventory_column *> &columns = get_all_columns();
     int holstered_items = 0;
     units::volume holster_volume = units::volume();
     units::mass holster_weight = units::mass();
     std::vector<const item_pocket *> used_pockets = std::vector<const item_pocket *>();
     for( const inventory_column *c : columns ) {
         if( c == nullptr ) {
             continue;
         }
         if( c->allows_selecting() ) {
             const inventory_column::get_entries_t entries = c->get_entries( always_yes );
             for( const inventory_entry *e : entries ) {
                 if( e == nullptr ) {
                     continue;
                 }
                 if( e->chosen_count == 0 ) {
                     continue;
                 }
                 const item *item_to_insert = e->any_item().get_item();
                 if( item_to_insert == nullptr ) {
                     continue;
                 }
                 units::mass w = item_to_insert->weight();
                 units::volume v = item_to_insert->volume();
                 int overflow_counter = e->chosen_count;
                 for( const item_pocket *p : holster.get_item()->get_all_contained_pockets() ) {
                     bool pocket_already_used = false;
                     for( const item_pocket *used_pocket : used_pockets ) {
                         if( p == used_pocket ) {
                             pocket_already_used = true;
                             break;
                         }
                     }
                     if( !pocket_already_used && p->is_holster() && !p->holster_full() ) {
                         ret_val<item_pocket::contain_code> contain = p->can_contain( *item_to_insert );
                         if( contain.success() ) {
                             bool has_better_pocket = false;
                             for( const item_pocket *other_pocket : holster.get_item()->get_all_contained_pockets() ) {
                                 if( p == other_pocket ) {
                                     continue;
                                 }
                                 if( p->better_pocket( *other_pocket, *item_to_insert, false ) ) {
                                     has_better_pocket = true;
                                 }
                             }
                             if( has_better_pocket ) {
                                 continue;
                             }
                             holstered_items += 1;
                             holster_weight += w;
                             holster_volume += v;
                             used_pockets.push_back( p );
                             overflow_counter -= 1;
                             if( overflow_counter <= 0 ) {
                                 break;
                             }
                         }
                     }
                 }
                 selected_weight += w * overflow_counter;
                 selected_volume += v * overflow_counter;
             }
         }
     }
     units::mass contained_weight = holster->get_total_contained_weight() + selected_weight +
                                    holster_weight +
                                    holster->get_used_holster_weight();
     units::mass total_weight = holster->get_total_weight_capacity() + holster_weight;
     units::volume contained_volume = holster->get_total_contained_volume() + selected_volume +
                                      holster_volume;
     units::volume total_volume = holster->get_total_capacity();
     return get_weight_and_volume_and_holster_stats( contained_weight,
             total_weight,
             contained_volume,
             total_volume,
             holster->max_containable_length(),
             holster->max_containable_volume(),
             holster->get_total_holster_volume() - ( holster->get_used_holster_volume() + holster_volume ),
             holster->get_used_holsters() + holstered_items,
             holster->get_total_holsters() );
 }
References anonymous_namespace{inventory_ui.cpp}::always_yes(), c, inventory_selector::columns, inventory_selector::get_all_columns(), inventory_selector::get_weight_and_volume_and_holster_stats(), game_menus::inv::holster(), inventory_selector::preset, ret_val_common::success(), item::volume(), and item::weight().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp