Cataclysm DDA: insert_item_activity_actor Class Reference
insert_item_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
insert_item_activity_actor ()=default
insert_item_activity_actor (const item_location &holster, const drop_locations &holstered_list, bool reopen_menu=false)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &, Character &who) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
item_location holster
drop_locations items
contents_change_handler handler
bool all_pockets_rigid
bool reopen_menu
Detailed Description
Definition at line 1312 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
insert_item_activity_actor() [1/2]
insert_item_activity_actor::insert_item_activity_actor () default
insert_item_activity_actor() [2/2]
insert_item_activity_actor::insert_item_activity_actor (const item_location & holster, const drop_locations & holstered_list, bool reopen_menu = false) inline
Definition at line 1324 of file activity_actor_definitions.h.
                                                                : holster( holster ), items( holstered_list ),
             reopen_menu( reopen_menu ) {}
Member Function Documentation
canceled()
void insert_item_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 4705 of file activity_actor.cpp.
 {
     handler.handle_by( who );
 }
References contents_change_handler::handle_by(), and handler.
clone()
std::unique_ptr<activity_actor> insert_item_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1337 of file activity_actor_definitions.h.
{
             return std::make_unique<insert_item_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > insert_item_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 4723 of file activity_actor.cpp.
 {
     insert_item_activity_actor actor;
     JsonObject data = jsin.get_object();
     data.read( "holster", actor.holster );
     data.read( "items", actor.items );
     data.read( "handler", actor.handler );
     data.read( "all_pockets_rigid", actor.all_pockets_rigid );
     data.read( "reopen_menu", actor.reopen_menu );
     return actor.clone();
 }
References all_pockets_rigid, clone(), JsonValue::get_object(), handler, holster, items, JsonObject::read(), and reopen_menu.
do_turn()
void insert_item_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1333 of file activity_actor_definitions.h.
 {};
finish()
void insert_item_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 4621 of file activity_actor.cpp.
 {
     bool success = false;
     bool bulk_load = false;
     Character *carrier = holster.carrier();
     drop_location &holstered_item = items.front();
     if( holstered_item.first ) {
         success = true;
         item &it = *holstered_item.first;
         // Check if next is bulk load before moving item.
         auto itr = std::next( items.begin() );
         if( itr != items.end() && itr->first ) {
             bulk_load = is_bulk_load( holstered_item.first, itr->first );
         }
         ret_val<void> ret = ret_val<void>::make_failure( _( "item can't be stored there" ) );
         if( !it.count_by_charges() ) {
             ret = try_insert( holster, holstered_item, nullptr, carrier );
             if( ret.success() ) {
                 //~ %1$s: item to put in the container, %2$s: container to put item in
                 who.add_msg_if_player( string_format( _( "You put your %1$s into the %2$s." ),
                                                       holstered_item.first->display_name(), holster->type->nname( 1 ) ) );
                 handler.add_unsealed( holster );
                 handler.unseal_pocket_containing( holstered_item.first );
                 holstered_item.first.remove_item();
             }
         } else {
             int charges_added = 0;
             ret = try_insert( holster, holstered_item, &charges_added, carrier );
             if( ret.success() ) {
                 item copy( it );
                 copy.charges = charges_added;
                 //~ %1$s: item to put in the container, %2$s: container to put item in
                 who.add_msg_if_player( string_format( _( "You put your %1$s into the %2$s." ),
                                                       copy.display_name(), holster->type->nname( 1 ) ) );
                 handler.add_unsealed( holster );
                 handler.unseal_pocket_containing( holstered_item.first );
                 it.charges -= charges_added;
                 if( it.charges == 0 ) {
                     holstered_item.first.remove_item();
                 }
             }
         }
         if( !ret.success() ) {
             success = false;
             std::string error = ret.str().empty() ?
                                 //~ %1$s: item we failed to put in the container, %2$s: container to put item in
                                 string_format( _( "Could not put %1$s into %2$s." ),
                                                it.tname(), holster->tname() ) :
                                 //~ %1$s: item we failed to put in the container, %2$s: container to put item in, %3$s: reason it failed
                                 string_format( _( "Could not put %1$s into %2$s, %3$s." ),
                                                it.tname(), holster->tname(), ret.str() );
             who.add_msg_if_player( error );
         }
     } else {
         // item was lost, so just go to next item
         success = true;
     }
     drop_locations items_remain;
     if( who.is_avatar() && reopen_menu && !success ) {
         items_remain.insert( items_remain.end(), items.begin(), items.end() );
     }
     items.pop_front();
     if( items.empty() || !success || items.front().first == item_location::nowhere ) {
         holster.make_active();
         handler.handle_by( who );
         act.set_to_null();
         if( !items_remain.empty() ) {
             g->insert_item( items_remain );
         }
         return;
     }
     // Restart the activity
     const int total_moves = item_move_cost( who, items.front().first, bulk_load );
     act.moves_left = total_moves;
     act.moves_total = total_moves;
 }
References _, act, Character::add_msg_if_player(), contents_change_handler::add_unsealed(), item_location::carrier(), item::charges, item::count_by_charges(), item::display_name(), error, g, contents_change_handler::handle_by(), handler, holster, Creature::is_avatar(), is_bulk_load(), item_move_cost(), items, item_location::make_active(), ret_val< T >::make_failure(), itype::nname(), item_location::nowhere, reopen_menu, cata::hash64_detail::ret, string_format(), item::tname(), try_insert(), item::type, and contents_change_handler::unseal_pocket_containing().
get_type()
activity_id insert_item_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1328 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_INSERT_ITEM" );
         }
References activity_id.
serialize()
void insert_item_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 4710 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "holster", holster );
     jsout.member( "items", items );
     jsout.member( "handler", handler );
     jsout.member( "all_pockets_rigid", all_pockets_rigid );
     jsout.member( "reopen_menu", reopen_menu );
     jsout.end_object();
 }
References all_pockets_rigid, JsonOut::end_object(), handler, holster, items, JsonOut::member(), reopen_menu, and JsonOut::start_object().
start()
void insert_item_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 4562 of file activity_actor.cpp.
 {
     if( items.empty() ) {
         debugmsg( "ACT_INSERT_ITEM was passed an empty list" );
         act.set_to_null();
     }
     all_pockets_rigid = holster->all_pockets_rigid();
     const int total_moves = item_move_cost( who, items.front().first, false );
     act.moves_left = total_moves;
     act.moves_total = total_moves;
 }
References act, all_pockets_rigid, item::all_pockets_rigid(), debugmsg, holster, item_move_cost(), and items.
Member Data Documentation
all_pockets_rigid
bool insert_item_activity_actor::all_pockets_rigid private
Definition at line 1318 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), and start().
handler
contents_change_handler insert_item_activity_actor::handler private
Definition at line 1317 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), finish(), and serialize().
holster
item_location insert_item_activity_actor::holster private
Definition at line 1315 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), serialize(), and start().
items
drop_locations insert_item_activity_actor::items private
Definition at line 1316 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), serialize(), and start().
reopen_menu
bool insert_item_activity_actor::reopen_menu private
Definition at line 1319 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp