Cataclysm DDA: SkillLevelMap Class Reference
SkillLevelMap Class Reference
#include <skill.h>
Public Member Functions
const SkillLevel & get_skill_level_object (const skill_id &ident) const
SkillLevel & get_skill_level_object (const skill_id &ident)
void mod_skill_level (const skill_id &ident, int delta)
int get_skill_level (const skill_id &ident) const
int get_skill_level (const skill_id &ident, const item &context) const
float get_progress_level (const skill_id &ident) const
float get_progress_level (const skill_id &ident, const item &context) const
void mod_knowledge_level (const skill_id &ident, int delta)
int get_knowledge_level (const skill_id &ident) const
int get_knowledge_level (const skill_id &ident, const item &context) const
float get_knowledge_progress_level (const skill_id &ident) const
float get_knowledge_progress_level (const skill_id &ident, const item &context) const
bool meets_skill_requirements (const std::map< skill_id, int > &req) const
bool meets_skill_requirements (const std::map< skill_id, int > &req, const item &context) const
std::map< skill_id, int > compare_skill_requirements (const std::map< skill_id, int > &req, const item &context) const
Calculates skill difference.
std::map< skill_id, int > compare_skill_requirements (const std::map< skill_id, int > &req) const
int exceeds_recipe_requirements (const recipe &rec) const
bool theoretical_recipe_requirements (const recipe &rec) const
bool has_recipe_requirements (const recipe &rec) const
bool has_same_levels_as (const SkillLevelMap &other) const
Detailed Description
Definition at line 244 of file skill.h.
Member Function Documentation
compare_skill_requirements() [1/2]
std::map< skill_id, int > SkillLevelMap::compare_skill_requirements (const std::map< skill_id, int > & req) const
Definition at line 553 of file skill.cpp.
 {
     return compare_skill_requirements( req, item() );
 }
References compare_skill_requirements(), and item.
compare_skill_requirements() [2/2]
std::map< skill_id, int > SkillLevelMap::compare_skill_requirements (const std::map< skill_id, int > & req, const item & context) const
Calculates skill difference.
Parameters
req Required skills to be compared with.
context An item to provide context for contextual skills. Can be null.
Returns
Difference in skills. Positive numbers - exceeds; negative - lacks; empty map - no difference.
Definition at line 559 of file skill.cpp.
 {
     std::map<skill_id, int> res;
     for( const auto &elem : req ) {
         const int diff = get_skill_level( elem.first, context ) - elem.second;
         if( diff != 0 ) {
             res[elem.first] = diff;
         }
     }
     return res;
 }
References context, and get_skill_level().
Referenced by compare_skill_requirements(), and exceeds_recipe_requirements().
exceeds_recipe_requirements()
int SkillLevelMap::exceeds_recipe_requirements (const recipe & rec) const
Definition at line 574 of file skill.cpp.
 {
     int over = rec.skill_used ? get_skill_level( rec.skill_used ) - rec.difficulty : 0;
     for( const auto &elem : compare_skill_requirements( rec.required_skills ) ) {
         over = std::min( over, elem.second );
     }
     return over;
 }
References compare_skill_requirements(), recipe::difficulty, get_skill_level(), min(), recipe::required_skills, and recipe::skill_used.
Referenced by Character::exceeds_recipe_requirements(), and has_recipe_requirements().
get_knowledge_level() [1/2]
int SkillLevelMap::get_knowledge_level (const skill_id & ident) const
Definition at line 514 of file skill.cpp.
 {
     return get_skill_level_object( ident ).knowledgeLevel();
 }
References get_skill_level_object(), and SkillLevel::knowledgeLevel().
Referenced by get_knowledge_level(), and theoretical_recipe_requirements().
get_knowledge_level() [2/2]
int SkillLevelMap::get_knowledge_level (const skill_id & ident, const item & context) const
Definition at line 519 of file skill.cpp.
 {
     const skill_id id = context.is_null() ? ident : context.contextualize_skill( ident );
     return get_knowledge_level( id );
 }
References context, and get_knowledge_level().
get_knowledge_progress_level() [1/2]
float SkillLevelMap::get_knowledge_progress_level (const skill_id & ident) const
Definition at line 525 of file skill.cpp.
 {
     return static_cast<float>( get_skill_level_object( ident ).knowledgeExperience() ) / 100.0f;
 }
References get_skill_level_object(), and SkillLevel::knowledgeExperience().
get_knowledge_progress_level() [2/2]
float SkillLevelMap::get_knowledge_progress_level (const skill_id & ident, const item & context) const
Definition at line 530 of file skill.cpp.
 {
     const skill_id id = context.is_null() ? ident : context.contextualize_skill( ident );
     return get_progress_level( id );
 }
References context, and get_progress_level().
get_progress_level() [1/2]
float SkillLevelMap::get_progress_level (const skill_id & ident) const
Definition at line 503 of file skill.cpp.
 {
     return static_cast<float>( get_skill_level_object( ident ).exercise() ) / 100.0f;
 }
References SkillLevel::exercise(), and get_skill_level_object().
Referenced by get_knowledge_progress_level(), and get_progress_level().
get_progress_level() [2/2]
float SkillLevelMap::get_progress_level (const skill_id & ident, const item & context) const
Definition at line 508 of file skill.cpp.
 {
     const skill_id id = context.is_null() ? ident : context.contextualize_skill( ident );
     return get_progress_level( id );
 }
References context, and get_progress_level().
get_skill_level() [1/2]
int SkillLevelMap::get_skill_level (const skill_id & ident) const
Definition at line 492 of file skill.cpp.
 {
     return get_skill_level_object( ident ).level();
 }
References get_skill_level_object(), and SkillLevel::level().
Referenced by compare_skill_requirements(), exceeds_recipe_requirements(), recipe::get_difficulty(), get_skill_level(), and practice_recipe_description().
get_skill_level() [2/2]
int SkillLevelMap::get_skill_level (const skill_id & ident, const item & context) const
Definition at line 497 of file skill.cpp.
 {
     const skill_id id = context.is_null() ? ident : context.contextualize_skill( ident );
     return get_skill_level( id );
 }
References context, and get_skill_level().
get_skill_level_object() [1/2]
SkillLevel & SkillLevelMap::get_skill_level_object (const skill_id & ident)
Definition at line 468 of file skill.cpp.
 {
     static SkillLevel null_skill;
     if( ident && ident->is_contextual_skill() ) {
         debugmsg( "Skill \"%s\" is context-dependent.  It cannot be assigned.", ident.str() );
         return null_skill;
     }
     return ( *this )[ident];
 }
References debugmsg, Skill::is_contextual_skill(), and string_id< T >::str().
get_skill_level_object() [2/2]
const SkillLevel & SkillLevelMap::get_skill_level_object (const skill_id & ident) const
Definition at line 450 of file skill.cpp.
 {
     static const SkillLevel null_skill{};
     if( ident && ident->is_contextual_skill() ) {
         debugmsg( "Skill \"%s\" is context-dependent.  It cannot be assigned.", ident.str() );
         return null_skill;
     }
     const auto iter = find( ident );
     if( iter != end() ) {
         return iter->second;
     }
     return null_skill;
 }
References debugmsg, keycode::end, Skill::is_contextual_skill(), and string_id< T >::str().
Referenced by get_knowledge_level(), get_knowledge_progress_level(), get_progress_level(), get_skill_level(), mod_knowledge_level(), and mod_skill_level().
has_recipe_requirements()
bool SkillLevelMap::has_recipe_requirements (const recipe & rec) const
Definition at line 597 of file skill.cpp.
 {
     return exceeds_recipe_requirements( rec ) >= 0 || theoretical_recipe_requirements( rec );
 }
References exceeds_recipe_requirements(), and theoretical_recipe_requirements().
Referenced by assemble_skill_details(), and Character::has_recipe_requirements().
has_same_levels_as()
bool SkillLevelMap::has_same_levels_as (const SkillLevelMap & other) const
Definition at line 602 of file skill.cpp.
 {
     if( this->size() != other.size() ) {
         return false;
     }
     for( const auto &entry : *this ) {
         const SkillLevel &this_level = entry.second;
         if( other.count( entry.first ) == 0 ) {
             return false;
         }
         const SkillLevel &other_level = other.get_skill_level_object( entry.first );
         if( this_level.level() != other_level.level() ||
             this_level.knowledgeLevel() != other_level.knowledgeLevel() ) {
             return false;
         }
     }
     return true;
 }
References SkillLevel::knowledgeLevel(), SkillLevel::level(), other, and om_direction::size.
meets_skill_requirements() [1/2]
bool SkillLevelMap::meets_skill_requirements (const std::map< skill_id, int > & req) const
Definition at line 537 of file skill.cpp.
 {
     return meets_skill_requirements( req, item() );
 }
References item.
Referenced by assemble_skill_details().
meets_skill_requirements() [2/2]
bool SkillLevelMap::meets_skill_requirements (const std::map< skill_id, int > & req, const item & context) const
Definition at line 542 of file skill.cpp.
 {
     return std::all_of( req.begin(), req.end(),
     [this, &context]( const std::pair<skill_id, int> &pr ) {
         // Whether or not you meet skill requirements should be based on your level of theory training,
         // not practical experience.
         return get_knowledge_level( pr.first, context ) >= pr.second;
     } );
 }
References context.
mod_knowledge_level()
void SkillLevelMap::mod_knowledge_level (const skill_id & ident, int delta)
Definition at line 486 of file skill.cpp.
 {
     SkillLevel &obj = get_skill_level_object( ident );
     obj.knowledgeLevel( obj.knowledgeLevel() + delta );
 }
References get_skill_level_object(), and SkillLevel::knowledgeLevel().
mod_skill_level()
void SkillLevelMap::mod_skill_level (const skill_id & ident, int delta)
Definition at line 480 of file skill.cpp.
 {
     SkillLevel &obj = get_skill_level_object( ident );
     obj.level( obj.level() + delta );
 }
References get_skill_level_object(), and SkillLevel::level().
Referenced by assemble_skill_details().
theoretical_recipe_requirements()
bool SkillLevelMap::theoretical_recipe_requirements (const recipe & rec) const
Definition at line 583 of file skill.cpp.
 {
     // Regardless of your current practical skill, do you know the theory of how to make this thing?
     if( rec.skill_used && get_knowledge_level( rec.skill_used ) < rec.difficulty ) {
         return false;
     }
     for( const std::pair<const skill_id, int> &elem : rec.required_skills ) {
         if( get_knowledge_level( elem.first ) < elem.second ) {
             return false;
         }
     }
     return true;
 }
References recipe::difficulty, get_knowledge_level(), recipe::required_skills, and recipe::skill_used.
Referenced by has_recipe_requirements().
The documentation for this class was generated from the following files:
src/skill.h
src/skill.cpp