Cataclysm DDA: kill_tracker Class Reference
kill_tracker Class Reference
#include <kill_tracker.h>
Public Member Functions
kill_tracker ()=default
void reset (const std::map< mtype_id, int > &kills, const std::vector< std::string > &npc_kills)
int kill_count (const mtype_id &) const
Returns the number of kills of the given mon_id by the player.
int kill_count (const species_id &) const
Returns the number of kills of the given monster species by the player.
int guilt_kill_count (const mtype_id &) const
Returns the number of of kills of the given mfaction_id.
int monster_kill_count () const
int npc_kill_count () const
int legacy_kill_xp () const
std::string get_kills_text () const
void clear ()
void notify (const cata::event &) override
void serialize (JsonOut &) const
void deserialize (const JsonObject &data)
virtual void notify (const cata::event &)=0
virtual void notify (const cata::event &, std::unique_ptr< talker >, std::unique_ptr< talker >)
Public Member Functions inherited from event_subscriber
event_subscriber ()=default
event_subscriber (const event_subscriber &)=delete
event_subscriber & operator= (const event_subscriber &)=delete
virtual ~event_subscriber ()
virtual void notify (const cata::event &, std::unique_ptr< talker >, std::unique_ptr< talker >)
Private Attributes
std::map< mtype_id, int > kills
std::vector< std::string > npc_kills
Friends
class diary
to keep track of new kills, need to access private member (kills, npc_kills), may include getter for thows and remove frend class diary.
Detailed Description
Definition at line 20 of file kill_tracker.h.
Constructor & Destructor Documentation
kill_tracker()
kill_tracker::kill_tracker () default
Member Function Documentation
clear()
void kill_tracker::clear ()
Definition at line 141 of file kill_tracker.cpp.
 {
     kills.clear();
     npc_kills.clear();
 }
References kills, and npc_kills.
deserialize()
void kill_tracker::deserialize (const JsonObject & data)
Definition at line 4478 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     for( const JsonMember member : data.get_object( "kills" ) ) {
         kills[mtype_id( member.name() )] = member.get_int();
     }
     for( const std::string npc_name : data.get_array( "npc_kills" ) ) {
         npc_kills.push_back( npc_name );
     }
 }
References item_pocket::data, member, and mtype_id.
get_kills_text()
std::string kill_tracker::get_kills_text () const
Definition at line 97 of file kill_tracker.cpp.
 {
     std::vector<std::string> data;
     int totalkills = 0;
     std::map<std::tuple<std::string, std::string, nc_color>, int> kill_counts;
     // map <name, sym, color> to kill count
     for( const std::pair<const mtype_id, int> &elem : kills ) {
         const mtype &m = elem.first.obj();
         auto key = std::make_tuple( m.nname(), m.sym, m.color );
         kill_counts[key] += elem.second;
         totalkills += elem.second;
     }
     for( const auto &entry : kill_counts ) {
         const int num_kills = entry.second;
         const std::string &mname = std::get<0>( entry.first );
         const std::string &symbol = std::get<1>( entry.first );
         const nc_color color = std::get<2>( entry.first );
         data.push_back( string_format( "%4d ", num_kills ) + colorize( symbol,
                         color ) + " " + colorize( mname, c_light_gray ) );
     }
     for( const auto &npc_name : npc_kills ) {
         totalkills += 1;
         data.push_back( string_format( "%4d ", 1 ) + colorize( "@ " + npc_name, c_magenta ) );
     }
     std::string buffer;
     if( data.empty() ) {
         buffer = _( "You haven't killed any monsters yet!" );
     } else {
         buffer = string_format( _( "KILL COUNT: %d" ), totalkills );
         if( get_option<bool>( "STATS_THROUGH_KILLS" ) ) {
             buffer += string_format( _( "\nExperience: %d (%d points available)" ), get_avatar().kill_xp,
                                      get_avatar().free_upgrade_points() );
         }
         buffer += "\n";
     }
     for( const std::string &line : data ) {
         buffer += "\n" + line;
     }
     return buffer;
 }
References _, c_light_gray, c_magenta, color(), mtype::color, colorize(), get_avatar(), kills, line, mtype::nname(), npc_kills, string_format(), mtype::sym, and symbol().
Referenced by show_scores_ui().
guilt_kill_count()
int kill_tracker::guilt_kill_count (const mtype_id & mon) const
Returns the number of of kills of the given mfaction_id.
Not to be confused with species. Used for death_guilt.
Definition at line 47 of file kill_tracker.cpp.
 {
     int count = 0;
     mon_flag_id flag;
     if( mon->has_flag( mon_flag_GUILT_ANIMAL ) ) {
         flag = mon_flag_GUILT_ANIMAL;
     } else if( mon->has_flag( mon_flag_GUILT_CHILD ) ) {
         flag = mon_flag_GUILT_CHILD;
     } else if( mon->has_flag( mon_flag_GUILT_HUMAN ) ) {
         flag = mon_flag_GUILT_HUMAN;
     } else if( mon->has_flag( mon_flag_GUILT_OTHERS ) ) {
         flag = mon_flag_GUILT_OTHERS;
     } else { // worst case scenario when no guilt flags are found
         auto noflag = kills.find( mon );
         if( noflag != kills.end() ) {
             return noflag->second;
         }
     }
     for( const auto &it : kills ) {
         if( it.first->has_flag( flag ) ) {
             count += it.second;
         }
     }
     return count;
 }
References mtype::has_flag(), kills, mon_flag_GUILT_ANIMAL, mon_flag_GUILT_CHILD, mon_flag_GUILT_HUMAN, and mon_flag_GUILT_OTHERS.
kill_count() [1/2]
int kill_tracker::kill_count (const mtype_id & mon) const
Returns the number of kills of the given mon_id by the player.
Definition at line 27 of file kill_tracker.cpp.
 {
     auto it = kills.find( mon );
     if( it != kills.end() ) {
         return it->second;
     }
     return 0;
 }
References kills.
Referenced by mission::assign(), and memorial_logger::write_text_memorial().
kill_count() [2/2]
int kill_tracker::kill_count (const species_id & spec) const
Returns the number of kills of the given monster species by the player.
Definition at line 36 of file kill_tracker.cpp.
 {
     int result = 0;
     for( const auto &pair : kills ) {
         if( pair.first->in_species( spec ) ) {
             result += pair.second;
         }
     }
     return result;
 }
References kills.
legacy_kill_xp()
int kill_tracker::legacy_kill_xp () const
Definition at line 87 of file kill_tracker.cpp.
 {
     int ret = 0;
     for( const std::pair<const mtype_id, int> &pair : kills ) {
         ret += ( pair.first->difficulty + pair.first->difficulty_base ) * pair.second;
     }
     ret += npc_kills.size() * 10;
     return ret;
 }
References kills, npc_kills, and cata::hash64_detail::ret.
monster_kill_count()
int kill_tracker::monster_kill_count () const
Definition at line 73 of file kill_tracker.cpp.
 {
     int result = 0;
     for( const auto &pair : kills ) {
         result += pair.second;
     }
     return result;
 }
References kills.
notify() [1/3]
void kill_tracker::notify (const cata::event & e) override virtual
Implements event_subscriber.
Definition at line 161 of file kill_tracker.cpp.
 {
     switch( e.type() ) {
         case event_type::character_kills_monster: {
             const character_id killer_id = e.get<character_id>( "killer" );
             if( Character *killer = get_avatar_or_follower( killer_id ) ) {
                 const mtype_id victim_type = e.get<mtype_id>( "victim_type" );
                 kills[victim_type]++;
                 killer->kill_xp += e.get<int>( "exp" );
                 victim_type.obj().families.practice_kill( *killer );
             }
             break;
         }
         case event_type::character_kills_character: {
             const character_id killer_id = e.get<character_id>( "killer" );
             if( Character *killer = get_avatar_or_follower( killer_id ) ) {
                 const std::string victim_name = e.get<cata_variant_type::string>( "victim_name" );
                 npc_kills.push_back( victim_name );
                 killer->kill_xp += npc_kill_xp;
             }
             break;
         }
         default:
             break;
     }
 }
References character_kills_character, character_kills_monster, mtype::families, cata::event::get(), get_avatar_or_follower(), kills, npc_kill_xp, npc_kills, string_id< T >::obj(), weakpoint_families::practice_kill(), string, and cata::event::type().
notify() [2/3]
virtual void event_subscriber::notify
notify() [3/3]
void event_subscriber::notify
Definition at line 22 of file event_bus.cpp.
 {
     notify( e );
 }
npc_kill_count()
int kill_tracker::npc_kill_count () const
Definition at line 82 of file kill_tracker.cpp.
 {
     return npc_kills.size();
 }
References npc_kills.
reset()
void kill_tracker::reset (const std::map< mtype_id, int > & kills, const std::vector< std::string > & npc_kills)
Definition at line 20 of file kill_tracker.cpp.
 {
     kills = kills_;
     npc_kills = npc_kills_;
 }
References kills, and npc_kills.
serialize()
void kill_tracker::serialize (JsonOut & jsout) const
Definition at line 4459 of file savegame_json.cpp.
 {
     jsout.start_object();
     jsout.member( "kills" );
     jsout.start_object();
     for( const auto &elem : kills ) {
         jsout.member( elem.first.str(), elem.second );
     }
     jsout.end_object();
     jsout.member( "npc_kills" );
     jsout.start_array();
     for( const auto &elem : npc_kills ) {
         jsout.write( elem );
     }
     jsout.end_array();
     jsout.end_object();
 }
References JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), JsonOut::start_array(), JsonOut::start_object(), and JsonOut::write().
Friends And Related Function Documentation
diary
friend class diary friend
to keep track of new kills, need to access private member (kills, npc_kills), may include getter for thows and remove frend class diary.
Definition at line 23 of file kill_tracker.h.
Member Data Documentation
kills
std::map<mtype_id, int> kill_tracker::kills private
Definition at line 48 of file kill_tracker.h.
Referenced by clear(), get_kills_text(), guilt_kill_count(), kill_count(), legacy_kill_xp(), monster_kill_count(), notify(), and reset().
npc_kills
std::vector<std::string> kill_tracker::npc_kills private
Definition at line 49 of file kill_tracker.h.
Referenced by clear(), get_kills_text(), legacy_kill_xp(), notify(), npc_kill_count(), and reset().
The documentation for this class was generated from the following files:
src/kill_tracker.h
src/kill_tracker.cpp
src/savegame_json.cpp