Cataclysm DDA: faction Class Reference
faction Class Reference
#include <faction.h>
Public Member Functions
faction ()=default
faction (const faction_template &templ)
void deserialize (const JsonObject &jo)
void serialize (JsonOut &json) const
void faction_display (const catacurses::window &fac_w, int width) const
std::string describe () const
std::vector< std::string > epilogue () const
std::string food_supply_text ()
nc_color food_supply_color ()
std::pair< nc_color, std::string > vitamin_stores (vitamin_type vit)
faction_price_rule const * get_price_rules (item const &it, npc const &guy) const
bool has_relationship (const faction_id &guy_id, npc_factions::relationship flag) const
void add_to_membership (const character_id &guy_id, const std::string &guy_name, bool known)
void remove_member (const character_id &guy_id)
Public Attributes
std::vector< int > opinion_of
bool validated = false
std::map< character_id, std::pair< std::string, bool > > members
Public Attributes inherited from faction_template
std::string name
int likes_u
int respects_u
int trusts_u
bool known_by_u
faction_id id
translation desc
int size
int power
nutrients food_supply
int wealth
bool lone_wolf_faction
itype_id currency
std::vector< faction_price_rule > price_rules
std::map< std::string, std::bitset< npc_factions::rel_types > > relations
mfaction_str_id mon_faction
std::set< std::tuple< int, int, snippet_id > > epilogue_data
Additional Inherited Members
Static Public Member Functions inherited from faction_template
static void load (const JsonObject &jsobj)
static void check_consistency ()
static void reset ()
Protected Member Functions inherited from faction_template
faction_template ()
void load_relations (const JsonObject &jsobj)
Detailed Description
Definition at line 126 of file faction.h.
Constructor & Destructor Documentation
faction() [1/2]
faction::faction () default
faction() [2/2]
faction::faction (const faction_template & templ) explicit
Definition at line 71 of file faction.cpp.
 {
     id = templ.id;
     // first init *all* members, than copy those from the template
     static_cast<faction_template &>( *this ) = templ;
 }
References faction_template::id.
Member Function Documentation
add_to_membership()
void faction::add_to_membership (const character_id & guy_id, const std::string & guy_name, bool known)
Definition at line 170 of file faction.cpp.
 {
     members[guy_id] = std::make_pair( guy_name, known );
 }
References members.
Referenced by npc::set_fac(), and npc::set_known_to_u().
describe()
std::string faction::describe () const
Definition at line 153 of file faction.cpp.
 {
     std::string ret = desc.translated();
     return ret;
 }
References faction_template::desc, cata::hash64_detail::ret, and translation::translated().
Referenced by debug_menu::faction_edit_menu().
deserialize()
void faction::deserialize (const JsonObject & jo)
Definition at line 3668 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     jo.read( "id", id );
     jo.read( "name", name );
     jo.read( "likes_u", likes_u );
     jo.read( "respects_u", respects_u );
     jo.read( "trusts_u", trusts_u );
     jo.read( "known_by_u", known_by_u );
     jo.read( "size", size );
     jo.read( "power", power );
     if( jo.has_int( "food_supply" ) ) {
         // Legacy kcal value found, migrate to calories
         jo.read( "food_supply", food_supply.calories );
         food_supply.calories *= 1000;
     } else {
         jo.read( "fac_food_supply", food_supply );
     }
     if( !jo.read( "wealth", wealth ) ) {
         wealth = 100;
     }
     if( jo.has_array( "opinion_of" ) ) {
         opinion_of = jo.get_int_array( "opinion_of" );
     }
     load_relations( jo );
 }
References JsonObject::allow_omitted_members(), JsonObject::get_int_array(), JsonObject::has_array(), JsonObject::has_int(), om_direction::name(), JsonObject::read(), and item_pocket::size().
epilogue()
std::vector< std::string > faction::epilogue () const
Definition at line 159 of file faction.cpp.
 {
     std::vector<std::string> ret;
     for( const std::tuple<int, int, snippet_id> &epilogue_entry : epilogue_data ) {
         if( power >= std::get<0>( epilogue_entry ) && power < std::get<1>( epilogue_entry ) ) {
             ret.emplace_back( std::get<2>( epilogue_entry )->translated() );
         }
     }
     return ret;
 }
References faction_template::epilogue_data, faction_template::power, and cata::hash64_detail::ret.
faction_display()
void faction::faction_display (const catacurses::window & fac_w, int width) const
Definition at line 587 of file faction.cpp.
 {
     int y = 2;
     mvwprintz( fac_w, point( width, ++y ), c_light_gray, _( "Attitude to you:           %s" ),
                fac_ranking_text( likes_u ) );
     fold_and_print( fac_w, point( width, ++y ), getmaxx( fac_w ) - width - 2, c_light_gray,
                     "%s", desc );
 }
References _, c_light_gray, faction_template::desc, fac_ranking_text(), fold_and_print(), catacurses::getmaxx(), faction_template::likes_u, mvwprintz(), and point.
Referenced by faction_manager::display().
food_supply_color()
nc_color faction::food_supply_color ()
Definition at line 342 of file faction.cpp.
 {
     int val = food_supply.kcal() / ( size * 288 );
     if( val >= 30 ) {
         return c_green;
     } else if( val >= 14 ) {
         return c_light_green;
     } else if( val >= 6 ) {
         return c_yellow;
     } else if( val >= 3 ) {
         return c_light_red;
     } else {
         return c_red;
     }
 }
References c_green, c_light_green, c_light_red, c_red, c_yellow, faction_template::food_supply, nutrients::kcal(), and faction_template::size.
Referenced by basecamp::faction_display().
food_supply_text()
std::string faction::food_supply_text ()
Definition at line 323 of file faction.cpp.
 {
     //Convert to how many days you can support the population
     int val = food_supply.kcal() / ( size * 288 );
     if( val >= 30 ) {
         return pgettext( "Faction food", "Overflowing" );
     }
     if( val >= 14 ) {
         return pgettext( "Faction food", "Well-Stocked" );
     }
     if( val >= 6 ) {
         return pgettext( "Faction food", "Scrapping By" );
     }
     if( val >= 3 ) {
         return pgettext( "Faction food", "Malnourished" );
     }
     return pgettext( "Faction food", "Starving" );
 }
References faction_template::food_supply, nutrients::kcal(), pgettext, and faction_template::size.
Referenced by basecamp::faction_display().
get_price_rules()
faction_price_rule const * faction::get_price_rules (item const & it, npc const & guy) const
Definition at line 407 of file faction.cpp.
 {
     auto const el = std::find_if(
     price_rules.crbegin(), price_rules.crend(), [&it, &guy]( faction_price_rule const & fc ) {
         return fc.matches( it, guy );
     } );
     if( el != price_rules.crend() ) {
         return &*el;
     }
     return nullptr;
 }
References faction_template::price_rules.
Referenced by npc::get_price_rules().
has_relationship()
bool faction::has_relationship (const faction_id & guy_id, npc_factions::relationship flag) const
Definition at line 419 of file faction.cpp.
 {
     for( const auto &rel_data : relations ) {
         if( rel_data.first == guy_id.c_str() ) {
             return rel_data.second.test( flag );
         }
     }
     return false;
 }
References string_id< T >::c_str(), and faction_template::relations.
Referenced by npc::has_faction_relationship().
remove_member()
void faction::remove_member (const character_id & guy_id)
Definition at line 176 of file faction.cpp.
 {
     for( auto it = members.cbegin(), next_it = it; it != members.cend(); it = next_it ) {
         ++next_it;
         if( guy_id == it->first ) {
             members.erase( it );
             break;
         }
     }
     if( members.empty() ) {
         for( const faction_template &elem : npc_factions::all_templates ) {
             // This is a templated base faction - don't delete it, just leave it as zero members for now.
             // Only want to delete dynamically created factions.
             if( elem.id == id ) {
                 return;
             }
         }
         g->faction_manager_ptr->remove_faction( id );
     }
 }
References npc_factions::all_templates, g, and members.
Referenced by npc::die(), and npc::set_fac().
serialize()
void faction::serialize (JsonOut & json) const
Definition at line 3696 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "id", id );
     json.member( "name", name );
     json.member( "likes_u", likes_u );
     json.member( "respects_u", respects_u );
     json.member( "trusts_u", trusts_u );
     json.member( "known_by_u", known_by_u );
     json.member( "size", size );
     json.member( "power", power );
     json.member( "fac_food_supply", food_supply );
     json.member( "wealth", wealth );
     json.member( "opinion_of", opinion_of );
     json.member( "relations" );
     json.start_object();
     for( const auto &rel_data : relations ) {
         json.member( rel_data.first );
         json.start_object();
         for( const auto &rel_flag : npc_factions::relation_strs ) {
             json.member( rel_flag.first, rel_data.second.test( rel_flag.second ) );
         }
         json.end_object();
     }
     json.end_object();
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), om_direction::name(), npc_factions::relation_strs, item_pocket::size(), and JsonOut::start_object().
vitamin_stores()
std::pair< nc_color, std::string > faction::vitamin_stores (vitamin_type vit)
Definition at line 358 of file faction.cpp.
 {
     bool is_toxin = vit_type == vitamin_type::TOXIN;
     const double days_of_food = food_supply.kcal() / 3000.0;
     std::map<vitamin_id, int> stored_vits = food_supply.vitamins();
     // First, pare down our search to only the relevant type
     for( auto it = stored_vits.cbegin(); it != stored_vits.cend(); ) {
         if( it->first->type() != vit_type ) {
             it = stored_vits.erase( it );
         } else {
             ++it;
         }
     }
     if( stored_vits.empty() ) {
         return std::pair<nc_color, std::string>( !is_toxin ? c_red : c_green, _( "None present (NONE)" ) );
     }
     std::vector<std::pair<vitamin_id, double>> vitamins;
     // Iterate the map's content into a sortable container...
     for( auto &vit : stored_vits ) {
         int units_per_day = vit.first.obj().units_absorption_per_day();
         double relative_intake = static_cast<double>( vit.second ) / static_cast<double>
                                  ( units_per_day ) / days_of_food;
         // We use the inverse value for toxins, since they are bad.
         if( is_toxin ) {
             relative_intake = 1 / relative_intake;
         }
         vitamins.emplace_back( vit.first, relative_intake );
     }
     // Sort to find the worst-case scenario, lowest relative_intake is first
     std::sort( vitamins.begin(), vitamins.end(), []( const auto & x, const auto & y ) {
         return x.second > y.second;
     } );
     const double worst_intake = vitamins.at( 0 ).second;
     std::string vit_name = vitamins.at( 0 ).first.obj().name();
     std::string msg = is_toxin ? _( "(TRACE)" ) : _( "(PLENTY)" );
     if( worst_intake <= 0.3 ) {
         msg = is_toxin ? _( "(POISON)" ) : _( "(LACK)" );
         return std::pair<nc_color, std::string>( c_red, string_format( _( "%1$s %2$s" ), vit_name,
                 msg ) );
     }
     if( worst_intake <= 1.0 ) {
         msg = is_toxin ? _( "(DANGER)" ) : _( "(MEAGER)" );
         return std::pair<nc_color, std::string>( c_yellow, string_format( _( "%1$s %2$s" ), vit_name,
                 msg ) );
     }
     return std::pair<nc_color, std::string>( c_green, string_format( _( "%1$s %2$s" ), vit_name,
             msg ) );
 }
References _, c_green, c_red, c_yellow, faction_template::food_supply, nutrients::kcal(), string_format(), TOXIN, and nutrients::vitamins().
Referenced by basecamp::faction_display().
Member Data Documentation
members
std::map<character_id, std::pair<std::string, bool> > faction::members
Definition at line 151 of file faction.h.
Referenced by add_to_membership(), npc::die(), and remove_member().
opinion_of
std::vector<int> faction::opinion_of
Definition at line 149 of file faction.h.
validated
bool faction::validated = false
Definition at line 150 of file faction.h.
The documentation for this class was generated from the following files:
src/faction.h
src/faction.cpp
src/savegame_json.cpp