Cataclysm DDA: trade_ui Class Reference
trade_ui Class Reference
#include <trade_ui.h>
Classes
struct trade_result_t
Public Types
enum class event { TRADECANCEL = 0 , TRADEOK = 1 , SWITCH = 2 , NEVENTS = 3 }
using pane_t = trade_selector
using party_t = Character
using entry_t = trade_selector::entry_t
using select_t = trade_selector::select_t
using currency_t = int
Public Member Functions
trade_ui (party_t &you, npc &trader, currency_t cost=0, std::string title=_("Trade"))
void pushevent (event const &ev)
trade_result_t perform_trade ()
void recalc_values_cpane ()
void autobalance ()
void bank_balance ()
void resize ()
Static Public Attributes
constexpr static int header_size = 5
Private Types
using panecont_t = std::array< std::unique_ptr< pane_t >, npanes >
using values_t = std::array< currency_t, npanes >
using parties_t = std::array< party_t *, npanes >
Private Member Functions
void _process (event const &ev)
bool _confirm_trade () const
void _draw_header ()
Private Attributes
trade_preset _upreset
trade_preset _tpreset
panecont_t _panes
values_t _trade_values {}
parties_t _parties
std::queue< event > _queue
panecont_t::size_type _cpane = 0
bool _exit = true
bool _traded = false
currency_t _cost = 0
currency_t _balance = 0
currency_t _bank = 0
currency_t _delta_bank = 0
std::string const _title
catacurses::window _header_w
ui_adaptor _header_ui
Static Private Attributes
constexpr static std::size_t npanes = 2
constexpr static panecont_t::size_type _trader = 0
constexpr static panecont_t::size_type _you = 1
Detailed Description
Definition at line 67 of file trade_ui.h.
Member Typedef Documentation
currency_t
using trade_ui::currency_t = int
Definition at line 74 of file trade_ui.h.
entry_t
using trade_ui::entry_t = trade_selector::entry_t
Definition at line 72 of file trade_ui.h.
pane_t
using trade_ui::pane_t = trade_selector
Definition at line 70 of file trade_ui.h.
panecont_t
using trade_ui::panecont_t = std::array<std::unique_ptr<pane_t>, npanes> private
Definition at line 101 of file trade_ui.h.
parties_t
using trade_ui::parties_t = std::array<party_t *, npanes> private
Definition at line 103 of file trade_ui.h.
party_t
using trade_ui::party_t = Character
Definition at line 71 of file trade_ui.h.
select_t
using trade_ui::select_t = trade_selector::select_t
Definition at line 73 of file trade_ui.h.
values_t
using trade_ui::values_t = std::array<currency_t, npanes> private
Definition at line 102 of file trade_ui.h.
Member Enumeration Documentation
event
enum trade_ui::event strong
Enumerator
TRADECANCEL
TRADEOK
SWITCH
NEVENTS
Definition at line 85 of file trade_ui.h.
 { TRADECANCEL = 0, TRADEOK = 1, SWITCH = 2, NEVENTS = 3 };
Constructor & Destructor Documentation
trade_ui()
trade_ui::trade_ui (party_t & you, npc & trader, currency_t cost = 0, std::string title = _("Trade"))
Definition at line 105 of file trade_ui.cpp.
     : _upreset{ you, trader }, _tpreset{ trader, you },
       _panes{ std::make_unique<pane_t>( this, trader, _tpreset, std::string(), _pane_size(),
                                         _pane_orig( -1 ) ),
               std::make_unique<pane_t>( this, you, _upreset, std::string(), _pane_size(),
                                         _pane_orig( 1 ) ) },
       _parties{ &trader, &you }, _title( std::move( title ) )
 {
     _panes[_you]->add_character_items( you );
     _panes[_you]->add_nearby_items( 1 );
     _panes[_trader]->add_character_items( trader );
     if( trader.is_shopkeeper() ) {
         _panes[_trader]->categorize_map_items( true );
         add_fallback_zone( trader );
         zone_manager &zmgr = zone_manager::get_manager();
         // FIXME: migration for traders in old saves - remove after 0.G
         zone_data const *const fallback =
             zmgr.get_zone_at( trader.get_location(), true, trader.get_fac_id() );
         bool const legacy = fallback != nullptr && fallback->get_name() == fallback_name;
         if( legacy ) {
             _panes[_trader]->add_nearby_items( PICKUP_RANGE );
         } else {
             std::unordered_set<tripoint> const src =
                 zmgr.get_point_set_loot( trader.get_location(), PICKUP_RANGE, trader.get_fac_id() );
             for( tripoint const &pt : src ) {
                 _panes[_trader]->add_map_items( pt );
                 _panes[_trader]->add_vehicle_items( pt );
             }
         }
     } else if( !trader.is_player_ally() ) {
         _panes[_trader]->add_nearby_items( 1 );
     }
     if( trader.will_exchange_items_freely() ) {
         _cost = 0;
     } else {
         _cost = trader.op_of_u.owed - cost;
     }
     _balance = _cost;
     _bank = you.cash;
     _delta_bank = 0;
     _panes[_you]->get_active_column().on_deactivate();
     _header_ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         _header_w = catacurses::newwin( header_size, TERMX, point_zero );
         ui.position_from_window( _header_w );
         ui.invalidate_ui();
         resize();
     } );
     _header_ui.mark_resize();
     _header_ui.on_redraw( [this]( ui_adaptor const & /* ui */ ) {
         werase( _header_w );
         _draw_header();
         wnoutrefresh( _header_w );
     } );
 }
References _balance, _bank, _cost, _delta_bank, _draw_header(), _header_ui, _header_w, _panes, _trader, _you, add_fallback_zone(), Character::cash, fallback_name, npc::get_fac_id(), Creature::get_location(), zone_manager::get_manager(), zone_data::get_name(), zone_manager::get_point_set_loot(), zone_manager::get_zone_at(), header_size, npc::is_player_ally(), npc::is_shopkeeper(), ui_adaptor::mark_resize(), catacurses::newwin(), ui_adaptor::on_redraw(), ui_adaptor::on_screen_resize(), npc::op_of_u, npc_opinion::owed, PICKUP_RANGE, point_zero, resize(), string, TERMX, catacurses::werase(), npc::will_exchange_items_freely(), and catacurses::wnoutrefresh().
Member Function Documentation
_confirm_trade()
bool trade_ui::_confirm_trade () const private
Definition at line 277 of file trade_ui.cpp.
 {
     npc const &np = *_parties[_trader]->as_npc();
     if( !npc_trading::npc_will_accept_trade( np, _balance ) ) {
         if( np.max_credit_extended() == 0 ) {
             popup( _( "You'll need to offer me more than that." ) );
         } else {
             popup( _( "Sorry, I'm only willing to extend you %s in credit." ),
                    format_money( np.max_credit_extended() ) );
         }
     } else if( !np.is_shopkeeper() &&
                !npc_trading::npc_can_fit_items( np, _panes[_you]->to_trade() ) ) {
         popup( _( "%s doesn't have the appropriate pockets to accept that." ), np.get_name() );
     } else if( npc_trading::calc_npc_owes_you( np, _balance ) < _balance ) {
         // NPC is happy with the trade, but isn't willing to remember the whole debt.
         return query_yn(
                    _( "I'm never going to be able to pay you back for all that.  The most I'm "
                       "willing to owe you is %s.\n\nContinue with trade?" ),
                    format_money( np.max_willing_to_owe() ) );
     } else {
         return query_yn( _( "Looks like a deal!  Accept this trade?" ) );
     }
     return false;
 }
References _, _balance, _panes, _parties, _trader, _you, npc_trading::calc_npc_owes_you(), format_money(), Character::get_name(), npc::is_shopkeeper(), npc::max_credit_extended(), npc::max_willing_to_owe(), npc_trading::npc_can_fit_items(), npc_trading::npc_will_accept_trade(), popup(), and query_yn().
Referenced by _process().
_draw_header()
void trade_ui::_draw_header () private
Definition at line 305 of file trade_ui.cpp.
 {
     draw_border( _header_w, c_light_gray );
     center_print( _header_w, 1, c_white, _title );
     npc const &np = *_parties[_trader]->as_npc();
     nc_color const trade_color =
         npc_trading::npc_will_accept_trade( np, _balance ) ? c_green : c_red;
     std::string cost_str = _( "Exchange" );
     if( !np.will_exchange_items_freely() ) {
         cost_str = string_format( _balance >= 0 ? _( "Credit %s" ) : _( "Debt %s" ),
                                   format_money( std::abs( _balance ) ) );
     }
     center_print( _header_w, 2, trade_color, cost_str );
     mvwprintz( _header_w, { 1, 3 }, c_white, _parties[_trader]->get_name() );
     right_print( _header_w, 3, 1, c_white, _( "You" ) );
     center_print( _header_w, header_size - 1, c_white,
                   string_format( _( "%s to switch panes" ),
                                  colorize( _panes[_you]->get_ctxt()->get_desc(
                                          trade_selector::ACTION_SWITCH_PANES ),
                                            c_yellow ) ) );
     center_print( _header_w, header_size - 2, c_white,
                   string_format( _( "%s to auto balance with highlighted item" ),
                                  colorize( _panes[_you]->get_ctxt()->get_desc(
                                          trade_selector::ACTION_AUTOBALANCE ),
                                            c_yellow ) ) );
     if( get_option<bool>( "CAPITALISM" ) ) {
         right_print( _header_w, 2, 1, c_white, string_format( _( "Bank Balance: %s" ),
                      format_money( _bank ) ) );
         right_print( _header_w, 1, 1, c_white,
                      string_format( _( "%s to balance trade with bank account balance" ),
                                     colorize( _panes[_you]->get_ctxt()->get_desc(
                                             trade_selector::ACTION_BANKBALANCE ),
                                               c_yellow ) ) );
     }
 }
References _, _balance, _bank, _header_w, _panes, _parties, _title, _trader, _you, abs(), trade_selector::ACTION_AUTOBALANCE, trade_selector::ACTION_BANKBALANCE, trade_selector::ACTION_SWITCH_PANES, c_green, c_light_gray, c_red, c_white, c_yellow, center_print(), colorize(), draw_border(), format_money(), header_size, mvwprintz(), npc_trading::npc_will_accept_trade(), right_print(), string_format(), and npc::will_exchange_items_freely().
Referenced by trade_ui().
_process()
void trade_ui::_process (event const & ev) private
Definition at line 253 of file trade_ui.cpp.
 {
     switch( ev ) {
         case event::TRADECANCEL: {
             _traded = false;
             _exit = true;
             break;
         }
         case event::TRADEOK: {
             _traded = _confirm_trade();
             _exit = _traded;
             break;
         }
         case event::SWITCH: {
             _panes[_cpane]->get_ui()->invalidate_ui();
             _cpane = -_cpane + 1;
             break;
         }
         case event::NEVENTS: {
             break;
         }
     }
 }
References _confirm_trade(), _cpane, _exit, _panes, _traded, NEVENTS, SWITCH, TRADECANCEL, and TRADEOK.
Referenced by perform_trade().
autobalance()
void trade_ui::autobalance ()
Definition at line 216 of file trade_ui.cpp.
 {
     int const sign = _cpane == _you ? -1 : 1;
     if( ( sign < 0 && _balance < 0 ) || ( sign > 0 && _balance > 0 ) ) {
         inventory_entry &entry = _panes[_cpane]->get_active_column().get_highlighted();
         size_t const avail = entry.get_available_count() - entry.chosen_count;
         double const price = npc_trading::trading_price( *_parties[-_cpane + 1], *_parties[_cpane],
                              entry_t{ entry.any_item(), 1 } ) * sign;
         double const num = _balance / price;
         double const extra = sign < 0 ? std::ceil( num ) : std::floor( num );
         _panes[_cpane]->toggle_entry( entry, entry.chosen_count +
                                       std::min( static_cast<size_t>( extra ), avail ) );
     }
 }
References _balance, _cpane, _panes, _parties, _you, inventory_entry::any_item(), ceil(), inventory_entry::chosen_count, floor(), inventory_entry::get_available_count(), min(), iexamine::sign(), and npc_trading::trading_price().
Referenced by trade_selector::execute().
bank_balance()
void trade_ui::bank_balance ()
Definition at line 231 of file trade_ui.cpp.
 {
     if( !get_option<bool>( "CAPITALISM" ) ) {
         popup( _( "Your promises of digital payment mean nothing here." ) );
         return;
     }
     _bank += _delta_bank;
     _delta_bank = -( _balance - _delta_bank );
     if( _delta_bank > 0 ) { // a withdrawal
         _delta_bank = std::min( _delta_bank, _bank );
         _delta_bank = std::max( _delta_bank, 0 );
     }
     _bank -= _delta_bank;
     recalc_values_cpane();
 }
References _, _balance, _bank, _delta_bank, max(), min(), popup(), and recalc_values_cpane().
Referenced by trade_selector::execute().
perform_trade()
trade_ui::trade_result_t trade_ui::perform_trade ()
Definition at line 173 of file trade_ui.cpp.
 {
     _exit = false;
     _traded = false;
     while( !_exit ) {
         _panes[_cpane]->execute();
         while( !_queue.empty() ) {
             event const ev = _queue.front();
             _queue.pop();
             _process( ev );
         }
     }
     if( _traded ) {
         return { _traded,
                  _balance,
                  _delta_bank,
                  _trade_values[_you],
                  _trade_values[_trader],
                  _panes[_you]->to_trade(),
                  _panes[_trader]->to_trade() };
     }
     return { false, 0, 0, 0, 0, {}, {} };
 }
References _balance, _cpane, _delta_bank, _exit, _panes, _process(), _queue, _trade_values, _traded, _trader, and _you.
pushevent()
void trade_ui::pushevent (event const & ev)
Definition at line 168 of file trade_ui.cpp.
 {
     _queue.emplace( ev );
 }
References _queue.
Referenced by trade_selector::execute().
recalc_values_cpane()
void trade_ui::recalc_values_cpane ()
Definition at line 201 of file trade_ui.cpp.
 {
     _trade_values[_cpane] = 0;
     for( entry_t const &it : _panes[_cpane]->to_trade() ) {
         // FIXME: cache trading_price
         _trade_values[_cpane] +=
             npc_trading::trading_price( *_parties[-_cpane + 1], *_parties[_cpane], it );
     }
     if( !_parties[_trader]->as_npc()->will_exchange_items_freely() ) {
         _balance = _cost + _trade_values[_you] - _trade_values[_trader] + _delta_bank;
     }
     _header_ui.invalidate_ui();
 }
References _balance, _cost, _cpane, _delta_bank, _header_ui, _panes, _parties, _trade_values, _trader, _you, ui_adaptor::invalidate_ui(), and npc_trading::trading_price().
Referenced by bank_balance(), and trade_selector::on_toggle().
resize()
void trade_ui::resize ()
Definition at line 247 of file trade_ui.cpp.
 {
     _panes[_you]->resize( _pane_size(), _pane_orig( 1 ) );
     _panes[_trader]->resize( _pane_size(), _pane_orig( -1 ) );
 }
References anonymous_namespace{trade_ui.cpp}::_pane_orig(), anonymous_namespace{trade_ui.cpp}::_pane_size(), _panes, _trader, and _you.
Referenced by trade_ui().
Member Data Documentation
_balance
currency_t trade_ui::_balance = 0 private
Definition at line 117 of file trade_ui.h.
Referenced by _confirm_trade(), _draw_header(), autobalance(), bank_balance(), perform_trade(), recalc_values_cpane(), and trade_ui().
_bank
currency_t trade_ui::_bank = 0 private
Definition at line 118 of file trade_ui.h.
Referenced by _draw_header(), bank_balance(), and trade_ui().
_cost
currency_t trade_ui::_cost = 0 private
Definition at line 116 of file trade_ui.h.
Referenced by recalc_values_cpane(), and trade_ui().
_cpane
panecont_t::size_type trade_ui::_cpane = 0 private
Definition at line 113 of file trade_ui.h.
Referenced by _process(), autobalance(), perform_trade(), and recalc_values_cpane().
_delta_bank
currency_t trade_ui::_delta_bank = 0 private
Definition at line 119 of file trade_ui.h.
Referenced by bank_balance(), perform_trade(), recalc_values_cpane(), and trade_ui().
_exit
bool trade_ui::_exit = true private
Definition at line 114 of file trade_ui.h.
Referenced by _process(), and perform_trade().
_header_ui
ui_adaptor trade_ui::_header_ui private
Definition at line 122 of file trade_ui.h.
Referenced by recalc_values_cpane(), and trade_ui().
_header_w
catacurses::window trade_ui::_header_w private
Definition at line 121 of file trade_ui.h.
Referenced by _draw_header(), and trade_ui().
_panes
panecont_t trade_ui::_panes private
Definition at line 109 of file trade_ui.h.
Referenced by _confirm_trade(), _draw_header(), _process(), autobalance(), perform_trade(), recalc_values_cpane(), resize(), and trade_ui().
_parties
parties_t trade_ui::_parties private
Definition at line 111 of file trade_ui.h.
Referenced by _confirm_trade(), _draw_header(), autobalance(), and recalc_values_cpane().
_queue
std::queue<event> trade_ui::_queue private
Definition at line 112 of file trade_ui.h.
Referenced by perform_trade(), and pushevent().
_title
std::string const trade_ui::_title private
Definition at line 120 of file trade_ui.h.
Referenced by _draw_header().
_tpreset
trade_preset trade_ui::_tpreset private
Definition at line 108 of file trade_ui.h.
_trade_values
values_t trade_ui::_trade_values {} private
Definition at line 110 of file trade_ui.h.
Referenced by perform_trade(), and recalc_values_cpane().
_traded
bool trade_ui::_traded = false private
Definition at line 115 of file trade_ui.h.
Referenced by _process(), and perform_trade().
_trader
constexpr static panecont_t::size_type trade_ui::_trader = 0 static constexpr private
Definition at line 105 of file trade_ui.h.
Referenced by _confirm_trade(), _draw_header(), perform_trade(), recalc_values_cpane(), resize(), and trade_ui().
_upreset
trade_preset trade_ui::_upreset private
Definition at line 108 of file trade_ui.h.
_you
constexpr static panecont_t::size_type trade_ui::_you = 1 static constexpr private
Definition at line 106 of file trade_ui.h.
Referenced by _confirm_trade(), _draw_header(), autobalance(), perform_trade(), recalc_values_cpane(), resize(), and trade_ui().
header_size
constexpr static int trade_ui::header_size = 5 static constexpr
Definition at line 97 of file trade_ui.h.
Referenced by _draw_header(), anonymous_namespace{trade_ui.cpp}::_pane_orig(), and trade_ui().
npanes
constexpr static std::size_t trade_ui::npanes = 2 static constexpr private
Definition at line 100 of file trade_ui.h.
The documentation for this class was generated from the following files:
src/trade_ui.h
src/trade_ui.cpp