Cataclysm DDA: effect Class Reference
effect Class Reference
#include <effect.h>
Public Member Functions
effect ()
effect (const effect_type *peff_type)
effect (const effect_source &source, const effect_type *peff_type, const time_duration &dur, bodypart_str_id part, bool perm, int nintensity, const time_point &nstart_time)
effect (const effect &)=default
effect & operator= (const effect &)=default
bool is_null () const
Returns true if the effect is the result of effect(), ie.
std::string disp_name () const
Returns the name displayed in the player status window.
std::string disp_desc (bool reduced=false) const
Returns the description displayed in the player status window.
std::string disp_short_desc (bool reduced=false) const
Returns the short description as set in json.
bool use_part_descs () const
Returns true if a description will be formatted as "Your" + body_part + description.
const effect_type * get_effect_type () const
Returns the effect's matching effect_type.
void decay (std::vector< efftype_id > &rem_ids, std::vector< bodypart_id > &rem_bps, const time_point &time, bool player, const effects_map &eff_map=effects_map())
Decays effect durations, pushing their id and bp's back to rem_ids and rem_bps for removal later if their duration is <= 0.
time_duration get_duration () const
Returns the remaining duration of an effect.
time_duration get_max_duration () const
Returns the maximum duration of an effect.
void set_duration (const time_duration &dur, bool alert=false)
Sets the duration, capping at max duration.
void mod_duration (const time_duration &dur, bool alert=false)
Mods the duration, capping at max_duration.
void mult_duration (double dur, bool alert=false)
Multiplies the duration, capping at max_duration.
std::vector< vitamin_applied_effect > vit_effects (bool reduced) const
time_point get_start_time () const
Returns the turn the effect was applied.
bodypart_id get_bp () const
Returns the targeted body_part of the effect.
void set_bp (const bodypart_str_id &part)
Sets the targeted body_part of an effect.
bool is_permanent () const
Returns true if an effect is permanent, i.e.
void pause_effect ()
Makes an effect permanent.
void unpause_effect ()
Makes an effect not permanent.
int get_intensity () const
Returns the intensity of an effect.
int get_max_intensity () const
Returns the maximum intensity of an effect.
int get_max_effective_intensity () const
Returns the maximum effective intensity of an effect.
int get_effective_intensity () const
Returns the current effect intensity, capped to max_effective_intensity.
int set_intensity (int val, bool alert=false)
Sets intensity of effect capped by range [1..max_intensity].
int mod_intensity (int mod, bool alert=false)
Modify intensity of effect capped by range [1..max_intensity].
const std::vector< trait_id > & get_resist_traits () const
Returns the string id of the resist trait to be used in has_trait("id").
const std::vector< efftype_id > & get_resist_effects () const
Returns the string id of the resist effect to be used in has_effect("id").
const std::vector< efftype_id > & get_removes_effects () const
Returns the string ids of the effects removed by this effect to be used in remove_effect("id").
std::vector< efftype_id > get_blocks_effects () const
Returns the string ids of the effects blocked by this effect to be used in add_effect("id").
int get_mod (const std::string &arg, bool reduced=false) const
Returns the matching modifier type from an effect, used for getting actual effect effects.
int get_avg_mod (const std::string &arg, bool reduced=false) const
Returns the average return of get_mod for a modifier type.
int get_amount (const std::string &arg, bool reduced=false) const
Returns the amount of a modifier type applied when a new effect is first added.
int get_min_val (const std::string &arg, bool reduced=false) const
Returns the minimum value of a modifier type that get_mod() and get_amount() will push the player to.
int get_max_val (const std::string &arg, bool reduced=false) const
Returns the maximum value of a modifier type that get_mod() and get_amount() will push the player to.
bool get_sizing (const std::string &arg) const
Returns true if the given modifier type's trigger chance is affected by size mutations.
double get_percentage (const std::string &arg, int val, bool reduced=false) const
Returns the approximate percentage chance of a modifier type activating on any given tick, used for descriptions.
bool activated (const time_point &when, const std::string &arg, int val, bool reduced=false, double mod=1) const
Checks to see if a given modifier type can activate, and performs any rolls required to do so.
bool has_flag (const flag_id &flag) const
Check if the effect has the specified flag.
std::vector< limb_score_effect > get_limb_score_data () const
std::vector< effect_dur_mod > get_effect_dur_scaling () const
bool kill_roll (bool reduced) const
std::string get_death_message () const
event_type death_event () const
double get_addict_mod (const std::string &arg, int addict_level) const
Returns the modifier caused by addictions.
bool get_harmful_cough () const
Returns true if the coughs caused by an effect can harm the player directly.
int get_dur_add_perc () const
Returns the percentage value by further applications of existing effects' duration is multiplied by.
time_duration get_int_dur_factor () const
Returns the number of turns it takes for the intensity to fall by 1 or 0 if intensity isn't based on duration.
int get_int_add_val () const
Returns the amount an already existing effect intensity is modified by further applications of the same effect.
int get_int_decay_step () const
Returns the step of intensity decay.
int get_int_decay_tick () const
Returns the number of ticks between intensity changes.
bool get_int_decay_remove () const
Returns if the effect is not protected from intensity decay-based removal.
const std::vector< std::pair< translation, int > > & get_miss_msgs () const
Returns a vector of the miss message messages and chances for use in add_miss_reason() while the effect is in effect.
std::string get_speed_name () const
Returns the value used for display on the speed modifier window in the player status menu.
bool impairs_movement () const
Returns if the effect is supposed to be handed in Creature::movement.
float get_limb_score_mod (const limb_score_id &score, bool reduced=false) const
const efftype_id & get_id () const
Returns the effect's matching effect_type id.
const effect_source & get_source () const
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
Static Public Attributes
static effect null_effect
Dummy used for "reference to effect()".
Protected Attributes
const effect_type * eff_type
time_duration duration
bodypart_str_id bp
bool permanent
int intensity
time_point start_time
effect_source source
Detailed Description
Definition at line 260 of file effect.h.
Constructor & Destructor Documentation
effect() [1/4]
effect::effect () inline
Definition at line 263 of file effect.h.
                  : eff_type( nullptr ), duration( 0_turns ), bp( bodypart_str_id::NULL_ID() ),
             permanent( false ), intensity( 1 ), start_time( calendar::turn_zero ),
             source( effect_source::empty() ) {
         }
effect() [2/4]
effect::effect (const effect_type * peff_type) inline explicit
Definition at line 267 of file effect.h.
                                                         : eff_type( peff_type ), duration( 0_turns ),
             bp( bodypart_str_id::NULL_ID() ),
             permanent( false ), intensity( 1 ), start_time( calendar::turn_zero ),
             source( effect_source::empty() ) {
         }
effect() [3/4]
effect::effect (const effect_source & source, const effect_type * peff_type, const time_duration & dur, bodypart_str_id part, bool perm, int nintensity, const time_point & nstart_time) inline
Definition at line 272 of file effect.h.
                                                                                                  :
             eff_type( peff_type ), duration( dur ), bp( part ),
             permanent( perm ), intensity( nintensity ), start_time( nstart_time ),
             source( source ) {
         }
effect() [4/4]
effect::effect (const effect &) default
Member Function Documentation
activated()
bool effect::activated (const time_point & when, const std::string & arg, int val, bool reduced = false, double mod = 1) const
Checks to see if a given modifier type can activate, and performs any rolls required to do so.
mod is a direct multiplier on the overall chance of a modifier type activating.
Definition at line 1355 of file effect.cpp.
 {
     int top = eff_type->get_mod_value( arg, mod_action::CHANCE_TOP, reduced, intensity );
     // Check chances if value is 0 (so we can check valueless effects like vomiting)
     // Else a nonzero value overrides a 0 chance for default purposes
     if( val == 0 && top <= 0 ) {
         return false;
     }
     int tick = eff_type->get_mod_value( arg, mod_action::TICK, reduced, intensity );
     // Tick is the exception where tick = 0 means tick = 1
     if( tick == 0 ) {
         tick = 1;
     } else if( tick < 0 ) {
         return false;
     }
     int bot = eff_type->get_mod_value( arg, mod_action::CHANCE_BOT, reduced, intensity );
     // Check if tick allows for triggering.
     if( ( when - calendar::turn_zero ) % time_duration::from_turns( tick ) != 0_turns ) {
         return false;
     }
     // If bot value is zero the formula is x_in_y(1, top) i.e. one_in(top),
     // else the formula is x_in_y(top, bot).
     // mod multiplies the overall percentage chances
     if( !bot ) {
         return x_in_y( mod, top );
     } else {
         return x_in_y( top * mod, bot );
     }
 }
References CHANCE_BOT, CHANCE_TOP, eff_type, time_duration::from_turns(), effect_type::get_mod_value(), intensity, TICK, calendar::turn_zero, and x_in_y().
Referenced by Character::process_one_effect(), and monster::process_one_effect().
death_event()
event_type effect::death_event () const
Definition at line 1646 of file effect.cpp.
 {
     if( eff_type->death_event.has_value() ) {
         return *eff_type->death_event;
     }
     debugmsg( "Asked for death event from effect of type %s, but it lacks one!", eff_type->id.str() );
     return event_type::num_event_types;
 }
References effect_type::death_event, debugmsg, eff_type, effect_type::id, num_event_types, and string_id< T >::str().
Referenced by Creature::process_effects().
decay()
void effect::decay (std::vector< efftype_id > & rem_ids, std::vector< bodypart_id > & rem_bps, const time_point & time, bool player, const effects_map & eff_map = effects_map())
Decays effect durations, pushing their id and bp's back to rem_ids and rem_bps for removal later if their duration is <= 0.
This is called in the middle of a loop through all effects, which is why we aren't allowed to remove the effects here.
Definition at line 1037 of file effect.cpp.
 {
     // Decay intensity if supposed to do so, removing effects at zero intensity
     if( intensity > 0 && eff_type->int_decay_tick != 0 &&
         to_turn<int>( time ) % eff_type->int_decay_tick == 0 &&
         get_max_duration() > get_duration() ) {
         if( eff_type->int_decay_step <= 0 || !effect_is_blocked( eff_type->id, eff_map ) ) {
             set_intensity( intensity + eff_type->int_decay_step, player );
         }
         if( intensity <= 0 ) {
             rem_ids.push_back( get_id() );
             rem_bps.push_back( bp.id() );
         }
     }
     // Add to removal list if duration is <= 0
     // Decay duration if not permanent
     if( duration <= 0_turns ) {
         rem_ids.push_back( get_id() );
         rem_bps.push_back( bp.id() );
     } else if( !is_permanent() ) {
         mod_duration( -1_turns, player );
     }
 }
References bp, duration, eff_type, effect_is_blocked(), get_duration(), get_id(), get_max_duration(), effect_type::id, string_id< T >::id(), effect_type::int_decay_step, effect_type::int_decay_tick, intensity, is_permanent(), mod_duration(), player, and set_intensity().
Referenced by Creature::process_effects().
deserialize()
void effect::deserialize (const JsonObject & jo)
Definition at line 1694 of file effect.cpp.
 {
     efftype_id id;
     jo.read( "eff_type", id );
     eff_type = &id.obj();
     jo.read( "duration", duration );
     // TEMPORARY until 0.F
     if( jo.has_int( "bp" ) ) {
         bp = convert_bp( static_cast<body_part>( jo.get_int( "bp" ) ) );
     } else {
         jo.read( "bp", bp );
     }
     jo.read( "permanent", permanent );
     jo.read( "intensity", intensity );
     start_time = calendar::turn_zero;
     jo.read( "start_turn", start_time );
     jo.read( "source", source );
 }
References bp, convert_bp(), duration, eff_type, JsonObject::get_int(), JsonObject::has_int(), base_camps::id, intensity, permanent, JsonObject::read(), source, start_time, and calendar::turn_zero.
disp_desc()
std::string effect::disp_desc (bool reduced = false) const
Returns the description displayed in the player status window.
Definition at line 819 of file effect.cpp.
 {
     std::string ret;
     std::string timestr;
     time_duration effect_dur_elapsed = calendar::turn - start_time;
     if( to_turns<int>( effect_dur_elapsed ) == 0 ) {
         timestr = _( "just now" );
     } else {
         timestr = string_format( _( "%s ago" ),
                                  debug_mode ? to_string( effect_dur_elapsed ) : to_string_clipped( effect_dur_elapsed ) );
     }
     ret += string_format( _( "Effect started: <color_white>%s</color>" ), timestr );
     if( debug_mode ) {
         ret += string_format( _( "Effect ends in: <color_white>%s</color>" ), to_string( duration ) );
     }
     //Newline if necessary
     if( !ret.empty() && ret.back() != '\n' ) {
         ret += "\n";
     }
     // First print stat changes, adding + if value is positive
     int tmp = get_avg_mod( "STR", reduced );
     if( tmp > 0 ) {
         ret += string_format( _( "Strength <color_white>+%d</color>; " ), tmp );
     } else if( tmp < 0 ) {
         ret += string_format( _( "Strength <color_white>%d</color>; " ), tmp );
     }
     tmp = get_avg_mod( "DEX", reduced );
     if( tmp > 0 ) {
         ret += string_format( _( "Dexterity <color_white>+%d</color>; " ), tmp );
     } else if( tmp < 0 ) {
         ret += string_format( _( "Dexterity <color_white>%d</color>; " ), tmp );
     }
     tmp = get_avg_mod( "PER", reduced );
     if( tmp > 0 ) {
         ret += string_format( _( "Perception <color_white>+%d</color>; " ), tmp );
     } else if( tmp < 0 ) {
         ret += string_format( _( "Perception <color_white>%d</color>; " ), tmp );
     }
     tmp = get_avg_mod( "INT", reduced );
     if( tmp > 0 ) {
         ret += string_format( _( "Intelligence <color_white>+%d</color>; " ), tmp );
     } else if( tmp < 0 ) {
         ret += string_format( _( "Intelligence <color_white>%d</color>; " ), tmp );
     }
     tmp = get_avg_mod( "SPEED", reduced );
     if( tmp > 0 ) {
         ret += string_format( _( "Speed <color_white>+%d</color>; " ), tmp );
     } else if( tmp < 0 ) {
         ret += string_format( _( "Speed <color_white>%d</color>; " ), tmp );
     }
     // Newline if necessary
     if( !ret.empty() && ret.back() != '\n' ) {
         ret += "\n";
     }
     // Handle limb score modifiers if we have any
     if( has_flag( flag_EFFECT_LIMB_SCORE_MOD_LOCAL ) || has_flag( flag_EFFECT_LIMB_SCORE_MOD ) ) {
         const std::string global = has_flag( flag_EFFECT_LIMB_SCORE_MOD ) ? _( "Global" ) : _( "Local" );
         for( limb_score_effect &effect : get_limb_score_data() ) {
             // Only print modifiers if they are global or if the limb has the score in the first place
             if( bp->has_limb_score( effect.score_id ) || has_flag( flag_EFFECT_LIMB_SCORE_MOD ) ) {
                 ret += string_format( _( "%s %s modifier: x%.1f\n" ), global, effect.score_id->name().translated(),
                                       get_limb_score_mod( effect.score_id, reduced ) );
             }
         }
     }
     // Then print pain/damage/coughing/vomiting, we don't display pkill, health, or radiation
     std::vector<std::string> constant;
     std::vector<std::string> frequent;
     std::vector<std::string> uncommon;
     std::vector<std::string> rare;
     std::vector<desc_freq> values;
     // Add various desc_freq structs to values. If more effects wish to be placed in the descriptions this is the
     // place to add them.
     int val = 0;
     val = get_avg_mod( "PAIN", reduced );
     values.emplace_back( get_percentage( "PAIN", val, reduced ), val, _( "pain" ),
                          _( "pain" ) );
     val = get_avg_mod( "HURT", reduced );
     values.emplace_back( get_percentage( "HURT", val, reduced ), val, _( "damage" ),
                          _( "damage" ) );
     val = get_avg_mod( "STAMINA", reduced );
     values.emplace_back( get_percentage( "STAMINA", val, reduced ), val,
                          _( "stamina recovery" ), _( "sleepiness" ) );
     val = get_avg_mod( "THIRST", reduced );
     values.emplace_back( get_percentage( "THIRST", val, reduced ), val, _( "thirst" ),
                          _( "quench" ) );
     val = get_avg_mod( "HUNGER", reduced );
     values.emplace_back( get_percentage( "HUNGER", val, reduced ), val, _( "hunger" ),
                          _( "sate" ) );
     val = get_avg_mod( "SLEEPINESS", reduced );
     values.emplace_back( get_percentage( "SLEEPINESS", val, reduced ), val, _( "sleepiness" ),
                          _( "rest" ) );
     val = get_avg_mod( "COUGH", reduced );
     values.emplace_back( get_percentage( "COUGH", val, reduced ), val, _( "coughing" ),
                          _( "coughing" ) );
     val = get_avg_mod( "VOMIT", reduced );
     values.emplace_back( get_percentage( "VOMIT", val, reduced ), val, _( "vomiting" ),
                          _( "vomiting" ) );
     val = get_avg_mod( "SLEEP", reduced );
     values.emplace_back( get_percentage( "SLEEP", val, reduced ), val, _( "blackouts" ),
                          _( "blackouts" ) );
     for( desc_freq &i : values ) {
         if( i.val > 0 ) {
             // +50% chance, every other step
             if( i.chance >= 50.0 ) {
                 constant.push_back( i.pos_string );
                 // +1% chance, every 100 steps
             } else if( i.chance >= 1.0 ) {
                 frequent.push_back( i.pos_string );
                 // +.4% chance, every 250 steps
             } else if( i.chance >= .4 ) {
                 uncommon.push_back( i.pos_string );
                 // <.4% chance
             } else if( i.chance > 0 ) {
                 rare.push_back( i.pos_string );
             }
         } else if( i.val < 0 ) {
             // +50% chance, every other step
             if( i.chance >= 50.0 ) {
                 constant.push_back( i.neg_string );
                 // +1% chance, every 100 steps
             } else if( i.chance >= 1.0 ) {
                 frequent.push_back( i.neg_string );
                 // +.4% chance, every 250 steps
             } else if( i.chance >= .4 ) {
                 uncommon.push_back( i.neg_string );
                 // <.4% chance
             } else if( i.chance > 0 ) {
                 rare.push_back( i.neg_string );
             }
         }
     }
     if( !constant.empty() ) {
         ret += _( "Const: " ) + enumerate_as_string( constant ) + " ";
     }
     if( !frequent.empty() ) {
         ret += _( "Freq: " ) + enumerate_as_string( frequent ) + " ";
     }
     if( !uncommon.empty() ) {
         ret += _( "Unfreq: " ) + enumerate_as_string( uncommon ) + " ";
     }
     if( !rare.empty() ) {
         ret += _( "Rare: " ) + enumerate_as_string( rare ); // No space needed at the end
     }
     // Newline if necessary
     if( !ret.empty() && ret.back() != '\n' ) {
         ret += "\n";
     }
     std::string tmp_str;
     if( eff_type->use_desc_ints( reduced ) ) {
         if( reduced ) {
             tmp_str = eff_type->reduced_desc[intensity - 1].translated();
         } else {
             tmp_str = eff_type->desc[intensity - 1].translated();
         }
     } else {
         if( reduced ) {
             tmp_str = eff_type->reduced_desc[0].translated();
         } else {
             tmp_str = eff_type->desc[0].translated();
         }
     }
     // Then print the effect description
     if( use_part_descs() ) {
         ret += string_format( tmp_str, body_part_name( bp.id() ) );
     } else {
         if( !tmp_str.empty() ) {
             ret += tmp_str;
         }
     }
     if( debug_mode ) {
         ret += string_format(
                    _( "\nDEBUG: ID: <color_white>%s</color> Intensity: <color_white>%d</color>" ),
                    eff_type->id.c_str(), intensity );
     }
     return ret;
 }
References _, body_part_name(), bp, string_id< T >::c_str(), constant, debug_mode, effect_type::desc, duration, eff_type, enumerate_as_string(), flag_EFFECT_LIMB_SCORE_MOD, flag_EFFECT_LIMB_SCORE_MOD_LOCAL, get_avg_mod(), get_limb_score_data(), get_limb_score_mod(), get_percentage(), global, has_flag(), body_part_type::has_limb_score(), effect_type::id, string_id< T >::id(), intensity, effect_type::reduced_desc, cata::hash64_detail::ret, start_time, string_format(), to_string(), to_string_clipped(), calendar::turn, effect_type::use_desc_ints(), and use_part_descs().
disp_name()
std::string effect::disp_name () const
Returns the name displayed in the player status window.
Definition at line 772 of file effect.cpp.
 {
     if( eff_type->name.empty() ) {
         debugmsg( "No names for effect type, ID: %s", eff_type->id.c_str() );
         return "";
     }
     // End result should look like "name (l. arm)" or "name [intensity] (l. arm)"
     std::string ret;
     if( eff_type->use_name_ints() ) {
         const translation &d_name = eff_type->name[ std::min<size_t>( intensity,
                                                       eff_type->name.size() ) - 1 ];
         if( d_name.empty() ) {
             return std::string();
         }
         ret += d_name.translated();
     } else {
         if( eff_type->name[0].empty() ) {
             return std::string();
         }
         ret += eff_type->name[0].translated();
         if( intensity > 1 && eff_type->show_intensity ) {
             if( eff_type->id == effect_bandaged || eff_type->id == effect_disinfected ) {
                 ret += string_format( " [%s]", texitify_healing_power( intensity ) );
             } else {
                 ret += string_format( " [%d]", intensity );
             }
         }
     }
     if( bp != bodypart_str_id::NULL_ID() ) {
         ret += string_format( " (%s)", body_part_name( bp.id() ) );
     }
     return ret;
 }
References body_part_name(), bp, string_id< T >::c_str(), debugmsg, eff_type, effect_bandaged, effect_disinfected, translation::empty(), effect_type::id, string_id< T >::id(), intensity, effect_type::name, string_id< body_part_type >::NULL_ID(), cata::hash64_detail::ret, effect_type::show_intensity, string_format(), texitify_healing_power(), translation::translated(), and effect_type::use_name_ints().
Referenced by get_limb_score_mod(), and bodygraph_display::prepare_infotext().
disp_short_desc()
std::string effect::disp_short_desc (bool reduced = false) const
Returns the short description as set in json.
Definition at line 1006 of file effect.cpp.
 {
     if( eff_type->use_desc_ints( reduced ) ) {
         if( reduced ) {
             return eff_type->reduced_desc[intensity - 1].translated();
         } else {
             return eff_type->desc[intensity - 1].translated();
         }
     } else {
         if( reduced ) {
             return eff_type->reduced_desc[0].translated();
         } else {
             return eff_type->desc[0].translated();
         }
     }
 }
References effect_type::desc, eff_type, intensity, effect_type::reduced_desc, and effect_type::use_desc_ints().
Referenced by draw_health_summary().
get_addict_mod()
double effect::get_addict_mod (const std::string & arg, int addict_level) const
Returns the modifier caused by addictions.
Currently only handles painkiller addictions.
Definition at line 1392 of file effect.cpp.
 {
     // TODO: convert this to JSON id's and values once we have JSON'ed addictions
     if( arg == "PKILL" ) {
         if( eff_type->pkill_addict_reduces ) {
             return 1.0 / std::max( static_cast<double>( addict_level ) * 2.0, 1.0 );
         } else {
             return 1.0;
         }
     } else {
         return 1.0;
     }
 }
References eff_type, max(), and effect_type::pkill_addict_reduces.
Referenced by Character::process_one_effect().
get_amount()
int effect::get_amount (const std::string & arg, bool reduced = false) const
Returns the amount of a modifier type applied when a new effect is first added.
Definition at line 1293 of file effect.cpp.
 {
     return static_cast<int>( eff_type->get_mod_value( arg, mod_action::AMOUNT, reduced,
                              get_effective_intensity() ) );
 }
References AMOUNT, eff_type, get_effective_intensity(), and effect_type::get_mod_value().
Referenced by Character::healing_rate_medicine(), Character::process_one_effect(), and monster::process_one_effect().
get_avg_mod()
int effect::get_avg_mod (const std::string & arg, bool reduced = false) const
Returns the average return of get_mod for a modifier type.
Used in effect description displays.
Definition at line 1279 of file effect.cpp.
 {
     double min = eff_type->get_mod_value( arg, mod_action::MIN, reduced, get_effective_intensity() );
     double max = eff_type->get_mod_value( arg, mod_action::MAX, reduced, get_effective_intensity() );
     if( static_cast<int>( max ) != 0 ) {
         // Return an average of min and max
         return static_cast<int>( ( min + max ) / 2 );
     } else {
         // Else return the minimum value
         return min;
     }
 }
References eff_type, get_effective_intensity(), effect_type::get_mod_value(), MAX, max(), MIN, and min().
Referenced by disp_desc().
get_blocks_effects()
std::vector< efftype_id > effect::get_blocks_effects () const
Returns the string ids of the effects blocked by this effect to be used in add_effect("id").
Definition at line 1258 of file effect.cpp.
 {
     std::vector<efftype_id> ret = eff_type->removes_effects;
     ret.insert( ret.end(), eff_type->blocks_effects.begin(), eff_type->blocks_effects.end() );
     return ret;
 }
References effect_type::blocks_effects, eff_type, effect_type::removes_effects, and cata::hash64_detail::ret.
get_bp()
bodypart_id effect::get_bp () const
Returns the targeted body_part of the effect.
This is bp_null for untargeted effects.
Definition at line 1166 of file effect.cpp.
 {
     return bp.id();
 }
References bp, and string_id< T >::id().
Referenced by Creature::add_effect(), Character::check_and_recover_morale(), Creature::clear_effects(), map::creature_in_field(), eff_fun_bleed(), eff_fun_cold(), eff_fun_frostbite(), eff_fun_hot(), eff_fun_onfire(), Character::hardcoded_effects(), Creature::process_effects(), Character::process_one_effect(), and Creature::schedule_effect().
get_death_message()
std::string effect::get_death_message () const
Definition at line 1641 of file effect.cpp.
 {
     return eff_type->death_msg.translated();
 }
References effect_type::death_msg, eff_type, and translation::translated().
Referenced by Creature::process_effects().
get_dur_add_perc()
int effect::get_dur_add_perc () const
Returns the percentage value by further applications of existing effects' duration is multiplied by.
Definition at line 1410 of file effect.cpp.
 {
     return eff_type->dur_add_perc;
 }
References effect_type::dur_add_perc, and eff_type.
Referenced by Creature::add_effect().
get_duration()
time_duration effect::get_duration () const
Returns the remaining duration of an effect.
Definition at line 1068 of file effect.cpp.
 {
     return duration;
 }
References duration.
Referenced by Creature::add_effect(), iexamine::autodoc(), Character::body_window(), map::creature_in_field(), decay(), draw_health_summary(), eff_fun_bleed(), eff_fun_datura(), eff_fun_hallu(), eff_fun_rat(), eff_fun_sleep(), eff_fun_teleglow(), heal_actor::finish_using(), Creature::get_effect_dur(), Character::hardcoded_effects(), mattack::kamikaze(), Character::mend(), Character::on_damage_of_type(), npc::on_load(), Character::pause(), Creature::process_effects(), sounds::process_sound_markers(), avatar::reset_stats(), Creature::schedule_effect(), and debug_menu::wisheffect().
get_effect_dur_scaling()
std::vector< effect_dur_mod > effect::get_effect_dur_scaling () const
Definition at line 1623 of file effect.cpp.
 {
     return eff_type->effect_dur_scaling;
 }
References eff_type, and effect_type::effect_dur_scaling.
get_effect_type()
const effect_type * effect::get_effect_type () const
Returns the effect's matching effect_type.
Definition at line 1485 of file effect.cpp.
 {
     return eff_type;
 }
References eff_type.
Referenced by ma_buff::from_effect().
get_effective_intensity()
int effect::get_effective_intensity () const
Returns the current effect intensity, capped to max_effective_intensity.
Definition at line 1200 of file effect.cpp.
 {
     if( eff_type->max_effective_intensity > 0 ) {
         return std::min( eff_type->max_effective_intensity, intensity );
     } else {
         return intensity;
     }
 }
References eff_type, intensity, effect_type::max_effective_intensity, and min().
Referenced by get_amount(), get_avg_mod(), and get_mod().
get_harmful_cough()
bool effect::get_harmful_cough () const
Returns true if the coughs caused by an effect can harm the player directly.
Definition at line 1406 of file effect.cpp.
 {
     return eff_type->harmful_cough;
 }
References eff_type, and effect_type::harmful_cough.
Referenced by Character::process_one_effect().
get_id()
const efftype_id& effect::get_id () const inline
Returns the effect's matching effect_type id.
Definition at line 427 of file effect.h.
{
             return eff_type->id;
         }
References eff_type, and effect_type::id.
Referenced by Creature::add_effect(), Character::check_and_recover_morale(), Creature::clear_effects(), map::creature_in_field(), decay(), eff_fun_datura(), Character::hardcoded_effects(), bodygraph_display::prepare_infotext(), Creature::process_effects(), monster::process_one_effect(), Creature::schedule_effect(), set_duration(), set_intensity(), Character::vomit(), and debug_menu::wisheffect().
get_int_add_val()
int effect::get_int_add_val () const
Returns the amount an already existing effect intensity is modified by further applications of the same effect.
Definition at line 1418 of file effect.cpp.
 {
     return eff_type->int_add_val;
 }
References eff_type, and effect_type::int_add_val.
Referenced by Creature::add_effect().
get_int_decay_remove()
bool effect::get_int_decay_remove () const
Returns if the effect is not protected from intensity decay-based removal.
Definition at line 1433 of file effect.cpp.
 {
     return eff_type->int_decay_remove;
 }
References eff_type, and effect_type::int_decay_remove.
get_int_decay_step()
int effect::get_int_decay_step () const
Returns the step of intensity decay.
Definition at line 1423 of file effect.cpp.
 {
     return eff_type->int_decay_step;
 }
References eff_type, and effect_type::int_decay_step.
get_int_decay_tick()
int effect::get_int_decay_tick () const
Returns the number of ticks between intensity changes.
Definition at line 1428 of file effect.cpp.
 {
     return eff_type->int_decay_tick;
 }
References eff_type, and effect_type::int_decay_tick.
get_int_dur_factor()
time_duration effect::get_int_dur_factor () const
Returns the number of turns it takes for the intensity to fall by 1 or 0 if intensity isn't based on duration.
Definition at line 1414 of file effect.cpp.
 {
     return eff_type->int_dur_factor;
 }
References eff_type, and effect_type::int_dur_factor.
Referenced by Creature::add_effect(), iexamine::autodoc(), heal_actor::finish_using(), monster::process_one_effect(), mattack::slimespring(), and Character::vomit().
get_intensity()
int effect::get_intensity () const
Returns the intensity of an effect.
Definition at line 1188 of file effect.cpp.
 {
     return intensity;
 }
References intensity.
Referenced by Creature::add_effect(), bp_affected(), Character::can_wear(), Character::check_and_recover_morale(), npc::complain(), map::creature_in_field(), eff_fun_bleed(), eff_fun_cold(), eff_fun_frostbite(), eff_fun_fungus(), eff_fun_hot(), eff_fun_hypovolemia(), eff_fun_onfire(), eff_fun_redcells_anemia(), eff_fun_sleep(), eff_fun_spores(), anonymous_namespace{math_parser_diag.cpp}::effect_intensity_eval(), npc::evaluate_character(), npc::evaluate_self(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_effect(), Creature::get_effect_int(), Character::hardcoded_effects(), Creature::load(), Character::mabuff_armor_bonus(), Character::mabuff_arpen_bonus(), Character::mabuff_attack_cost_mult(), Character::mabuff_attack_cost_penalty(), Character::mabuff_block_bonus(), Character::mabuff_block_effectiveness_bonus(), Character::mabuff_critical_hit_chance_bonus(), Character::mabuff_damage_bonus(), Character::mabuff_damage_mult(), Character::mabuff_dodge_bonus(), Character::mabuff_speed_bonus(), Character::on_damage_of_type(), mattack::photograph(), bodygraph_display::prepare_infotext(), Creature::process_effects(), monster::process_one_effect(), Character::reduce_healing_effect(), Creature::remove_effect(), Creature::schedule_effect(), avatar::try_break_relax_gas(), and mattack::zombie_fuse().
get_limb_score_data()
std::vector< limb_score_effect > effect::get_limb_score_data () const
Definition at line 1618 of file effect.cpp.
 {
     return eff_type->limb_score_data;
 }
References eff_type, and effect_type::limb_score_data.
Referenced by disp_desc().
get_limb_score_mod()
float effect::get_limb_score_mod (const limb_score_id & score, bool reduced = false) const
Definition at line 1462 of file effect.cpp.
 {
     float ret = 1.0f;
     for( const limb_score_effect &effect : eff_type->limb_score_data ) {
         float temp = 1.0f;
         if( score == effect.score_id ) {
             if( !reduced ) {
                 temp = effect.mod + effect.scaling * ( intensity - 1 );
             } else {
                 temp = effect.red_mod + effect.red_scaling * ( intensity - 1 );
             }
             ret *= std::max( 0.0f, temp );
         }
     }
     if( ret != 1.0f ) {
         add_msg_debug( debugmode::DF_CHARACTER,
                        "Limb score modifier %s for limb score %s found\nIntensity %d\nResistance %s\nFinal effect multiplier %.1f",
                        disp_name(),
                        score.c_str(), intensity, reduced ? "true" : "false", ret );
     }
     return ret;
 }
References add_msg_debug, debugmode::DF_CHARACTER, disp_name(), eff_type, intensity, effect_type::limb_score_data, max(), cata::hash64_detail::ret, and temp.
Referenced by disp_desc().
get_max_duration()
time_duration effect::get_max_duration () const
Returns the maximum duration of an effect.
Definition at line 1072 of file effect.cpp.
 {
     return eff_type->max_duration;
 }
References eff_type, and effect_type::max_duration.
Referenced by Creature::add_effect(), Character::apply_damage(), iexamine::autodoc(), Character::body_window(), decay(), draw_health_summary(), Character::mend(), and Character::vomit().
get_max_effective_intensity()
int effect::get_max_effective_intensity () const
Returns the maximum effective intensity of an effect.
Definition at line 1196 of file effect.cpp.
 {
     return eff_type->max_effective_intensity;
 }
References eff_type, and effect_type::max_effective_intensity.
get_max_intensity()
int effect::get_max_intensity () const
Returns the maximum intensity of an effect.
Definition at line 1192 of file effect.cpp.
 {
     return eff_type->max_intensity;
 }
References eff_type, and effect_type::max_intensity.
Referenced by Creature::add_effect(), Character::body_window(), Character::can_wear(), eff_fun_hypovolemia(), mattack::photograph(), monster::process_one_effect(), and mattack::zombie_fuse().
get_max_val()
int effect::get_max_val (const std::string & arg, bool reduced = false) const
Returns the maximum value of a modifier type that get_mod() and get_amount() will push the player to.
Definition at line 1304 of file effect.cpp.
 {
     return static_cast<int>( eff_type->get_mod_value( arg, mod_action::MAX_VAL, reduced, intensity ) );
 }
References eff_type, effect_type::get_mod_value(), intensity, and MAX_VAL.
Referenced by Character::process_one_effect().
get_min_val()
int effect::get_min_val (const std::string & arg, bool reduced = false) const
Returns the minimum value of a modifier type that get_mod() and get_amount() will push the player to.
Definition at line 1299 of file effect.cpp.
 {
     return static_cast<int>( eff_type->get_mod_value( arg, mod_action::MIN_VAL, reduced, intensity ) );
 }
References eff_type, effect_type::get_mod_value(), intensity, and MIN_VAL.
Referenced by Character::process_one_effect().
get_miss_msgs()
const std::vector< std::pair< translation, int > > & effect::get_miss_msgs () const
Returns a vector of the miss message messages and chances for use in add_miss_reason() while the effect is in effect.
Definition at line 1438 of file effect.cpp.
 {
     return eff_type->miss_msgs;
 }
References eff_type, and effect_type::miss_msgs.
Referenced by Character::process_one_effect().
get_mod()
int effect::get_mod (const std::string & arg, bool reduced = false) const
Returns the matching modifier type from an effect, used for getting actual effect effects.
Definition at line 1265 of file effect.cpp.
 {
     double min = eff_type->get_mod_value( arg, mod_action::MIN, reduced, get_effective_intensity() );
     double max = eff_type->get_mod_value( arg, mod_action::MAX, reduced, get_effective_intensity() );
     if( static_cast<int>( max ) != 0 ) {
         // Return a random value between [min, max]
         return static_cast<int>( rng( min, max ) );
     } else {
         // Else return the minimum value
         return min;
     }
 }
References eff_type, get_effective_intensity(), effect_type::get_mod_value(), MAX, max(), MIN, min(), and rng().
Referenced by Character::disp_info(), Character::process_one_effect(), monster::process_one_effect(), and avatar::reset_stats().
get_percentage()
double effect::get_percentage (const std::string & arg, int val, bool reduced = false) const
Returns the approximate percentage chance of a modifier type activating on any given tick, used for descriptions.
Definition at line 1319 of file effect.cpp.
 {
     int top = eff_type->get_mod_value( arg, mod_action::CHANCE_TOP, reduced, intensity );
     // Check chances if value is 0 (so we can check valueless effects like vomiting)
     // Else a nonzero value overrides a 0 chance for default purposes
     if( val == 0 && top <= 0 ) {
         return 0;
     }
     int bot = eff_type->get_mod_value( arg, mod_action::CHANCE_BOT, reduced, intensity );
     int tick = eff_type->get_mod_value( arg, mod_action::TICK, reduced, intensity );
     // Tick is the exception where tick = 0 means tick = 1
     if( tick == 0 ) {
         tick = 1;
     }
     // Start with 100%
     double ret = 100;
     // If bot is zero the formula is one_in(top), else the formula is x_in_y(top, bot)
     if( bot ) {
         // Cast to double here to allow for partial percentages
         ret *= static_cast<double>( top ) / static_cast<double>( bot );
     } else {
         // Cast to double here to allow for partial percentages
         ret /= static_cast<double>( top );
     }
     // Divide by ticks between rolls
     if( tick > 1 ) {
         ret /= tick;
     }
     return ret;
 }
References CHANCE_BOT, CHANCE_TOP, eff_type, effect_type::get_mod_value(), intensity, cata::hash64_detail::ret, and TICK.
Referenced by disp_desc().
get_removes_effects()
const std::vector< efftype_id > & effect::get_removes_effects () const
Returns the string ids of the effects removed by this effect to be used in remove_effect("id").
Definition at line 1254 of file effect.cpp.
 {
     return eff_type->removes_effects;
 }
References eff_type, and effect_type::removes_effects.
get_resist_effects()
const std::vector< efftype_id > & effect::get_resist_effects () const
Returns the string id of the resist effect to be used in has_effect("id").
Definition at line 1250 of file effect.cpp.
 {
     return eff_type->resist_effects;
 }
References eff_type, and effect_type::resist_effects.
Referenced by Creature::resists_effect().
get_resist_traits()
const std::vector< trait_id > & effect::get_resist_traits () const
Returns the string id of the resist trait to be used in has_trait("id").
Definition at line 1246 of file effect.cpp.
 {
     return eff_type->resist_traits;
 }
References eff_type, and effect_type::resist_traits.
Referenced by Creature::resists_effect().
get_sizing()
bool effect::get_sizing (const std::string & arg) const
Returns true if the given modifier type's trigger chance is affected by size mutations.
Definition at line 1309 of file effect.cpp.
 {
     if( arg == "PAIN" ) {
         return eff_type->pain_sizing;
     } else if( arg == "HURT" ) {
         return eff_type->hurt_sizing;
     }
     return false;
 }
References eff_type, effect_type::hurt_sizing, and effect_type::pain_sizing.
Referenced by Character::process_one_effect().
get_source()
const effect_source & effect::get_source () const
Definition at line 1676 of file effect.cpp.
 {
     return this->source;
 }
References source.
Referenced by Creature::process_effects(), and monster::process_one_effect().
get_speed_name()
std::string effect::get_speed_name () const
Returns the value used for display on the speed modifier window in the player status menu.
Definition at line 1442 of file effect.cpp.
 {
     // USes the speed_mod_name if one exists, else defaults to the first entry in "name".
     // But make sure the name for this intensity actually exists!
     if( !eff_type->speed_mod_name.empty() ) {
         return eff_type->speed_mod_name.translated();
     } else if( eff_type->use_name_ints() ) {
         return eff_type->name[ std::min<size_t>( intensity, eff_type->name.size() ) - 1 ].translated();
     } else if( !eff_type->name.empty() ) {
         return eff_type->name[0].translated();
     } else {
         return "";
     }
 }
References eff_type, translation::empty(), intensity, effect_type::name, effect_type::speed_mod_name, translation::translated(), and effect_type::use_name_ints().
Referenced by Character::disp_info(), and draw_health_summary().
get_start_time()
time_point effect::get_start_time () const
Returns the turn the effect was applied.
Definition at line 1161 of file effect.cpp.
 {
     return start_time;
 }
References start_time.
has_flag()
bool effect::has_flag (const flag_id & flag) const
Check if the effect has the specified flag.
Definition at line 1613 of file effect.cpp.
 {
     return eff_type->has_flag( flag );
 }
References eff_type, and effect_type::has_flag().
Referenced by disp_desc().
impairs_movement()
bool effect::impairs_movement () const
Returns if the effect is supposed to be handed in Creature::movement.
Definition at line 1457 of file effect.cpp.
 {
     return eff_type->impairs_movement;
 }
References eff_type, and effect_type::impairs_movement.
Referenced by monster::process_one_effect().
is_null()
bool effect::is_null () const
Returns true if the effect is the result of effect(), ie.
an effect that doesn't exist.
Definition at line 767 of file effect.cpp.
 {
     return !eff_type;
 }
References eff_type.
Referenced by iexamine::autodoc(), Character::body_window(), bp_affected(), Character::can_wear(), draw_health_summary(), anonymous_namespace{math_parser_diag.cpp}::effect_intensity_eval(), npc::evaluate_character(), npc::evaluate_self(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_effect(), Creature::get_effect_dur(), Creature::get_effect_int(), Character::mend(), Character::pause(), mattack::photograph(), avatar::reset_stats(), avatar::try_break_relax_gas(), and debug_menu::wisheffect().
is_permanent()
bool effect::is_permanent () const
Returns true if an effect is permanent, i.e.
it's duration does not decrease over time.
Definition at line 1175 of file effect.cpp.
 {
     return permanent;
 }
References permanent.
Referenced by Creature::add_effect(), map::creature_in_field(), decay(), Creature::schedule_effect(), and debug_menu::wisheffect().
kill_roll()
bool effect::kill_roll (bool reduced) const
Definition at line 1628 of file effect.cpp.
 {
     const std::vector<std::pair<int, int>> &chances = reduced ? eff_type->red_kill_chance :
                                         eff_type->kill_chance;
     if( chances.empty() ) {
         return false;
     }
     const int idx = cap_to_size( chances.size(), intensity );
     const std::pair<int, int> &chance = chances[idx];
     return x_in_y( chance.first, chance.second );
 }
References cap_to_size(), eff_type, intensity, effect_type::kill_chance, effect_type::red_kill_chance, and x_in_y().
Referenced by Creature::process_effects().
mod_duration()
void effect::mod_duration (const time_duration & dur, bool alert = false)
Mods the duration, capping at max_duration.
Definition at line 1093 of file effect.cpp.
 {
     set_duration( duration + dur, alert );
 }
References dur, duration, and set_duration().
Referenced by Creature::add_effect(), Character::apply_damage(), decay(), eff_fun_fungus(), eff_fun_rat(), Character::hardcoded_effects(), Character::pause(), Character::process_bionic(), monster::process_one_effect(), Character::reduce_healing_effect(), mattack::slimespring(), and Character::vomit().
mod_intensity()
int effect::mod_intensity (int mod, bool alert = false)
Modify intensity of effect capped by range [1..max_intensity].
Parameters
mod Amount to increase current intensity by
alert whether decay messages should be displayed
Returns
new intensity of the effect after modification and capping
Definition at line 1241 of file effect.cpp.
 {
     return set_intensity( intensity + mod, alert );
 }
References intensity, and set_intensity().
Referenced by Creature::add_effect(), and eff_fun_sleep().
mult_duration()
void effect::mult_duration (double dur, bool alert = false)
Multiplies the duration, capping at max_duration.
Definition at line 1097 of file effect.cpp.
 {
     set_duration( duration * dur, alert );
 }
References dur, duration, and set_duration().
Referenced by eff_fun_rat(), and Character::hardcoded_effects().
operator=()
effect& effect::operator= (const effect &) default
pause_effect()
void effect::pause_effect ()
Makes an effect permanent.
Note: This pauses the duration, but does not otherwise change it.
Definition at line 1179 of file effect.cpp.
 {
     permanent = true;
 }
References permanent.
Referenced by Creature::add_effect().
serialize()
void effect::serialize (JsonOut & json) const
Definition at line 1681 of file effect.cpp.
 {
     json.start_object();
     json.member( "eff_type", eff_type != nullptr ? eff_type->id.str() : "" );
     json.member( "duration", duration );
     json.member( "bp", bp.c_str() );
     json.member( "permanent", permanent );
     json.member( "intensity", intensity );
     json.member( "start_turn", start_time );
     json.member( "source", source );
     json.end_object();
 }
References bp, string_id< T >::c_str(), duration, eff_type, JsonOut::end_object(), effect_type::id, intensity, JsonOut::member(), permanent, source, JsonOut::start_object(), start_time, and string_id< T >::str().
set_bp()
void effect::set_bp (const bodypart_str_id & part)
Sets the targeted body_part of an effect.
Definition at line 1170 of file effect.cpp.
 {
     bp = part;
 }
References bp.
set_duration()
void effect::set_duration (const time_duration & dur, bool alert = false)
Sets the duration, capping at max duration.
Definition at line 1076 of file effect.cpp.
 {
     duration = dur;
     // Cap to max_duration
     if( duration > eff_type->max_duration ) {
         duration = eff_type->max_duration;
     }
     // Force intensity if it is duration based
     if( eff_type->int_dur_factor != 0_turns ) {
         // + 1 here so that the lowest is intensity 1, not 0
         set_intensity( duration / eff_type->int_dur_factor + 1, alert );
     }
     add_msg_debug( debugmode::DF_EFFECT, "ID: %s, Duration %s", get_id().c_str(),
                    to_string_writable( duration ) );
 }
References add_msg_debug, debugmode::DF_EFFECT, dur, duration, eff_type, get_id(), effect_type::int_dur_factor, effect_type::max_duration, set_intensity(), and to_string_writable().
Referenced by Creature::add_effect(), iexamine::autodoc(), eff_fun_sleep(), eff_fun_teleglow(), heal_actor::finish_using(), Character::hardcoded_effects(), Character::mend(), mod_duration(), mult_duration(), npc::on_load(), monster::process_one_effect(), sounds::process_sound_markers(), avatar::reset_stats(), Character::wake_up(), and debug_menu::wisheffect().
set_intensity()
int effect::set_intensity (int val, bool alert = false)
Sets intensity of effect capped by range [1..max_intensity].
Parameters
val Value to set intensity to
alert whether decay messages should be displayed
Returns
new intensity of the effect after val subjected to above cap
Definition at line 1209 of file effect.cpp.
 {
     if( intensity < 1 ) {
         // Fix bad intensity
         add_msg_debug( debugmode::DF_EFFECT, "Bad intensity, ID: %s", get_id().c_str() );
         intensity = 1;
     }
     val = std::max( std::min( val, eff_type->max_intensity ), 0 );
     if( val == intensity ) {
         // Nothing to change
         return intensity;
     }
     // Filter out intensity falling to zero (the effect will be removed later)
     if( alert && val < intensity &&  val != 0 &&
         val - 1 < static_cast<int>( eff_type->decay_msgs.size() ) ) {
         add_msg( eff_type->decay_msgs[ val - 1 ].second,
                  eff_type->decay_msgs[ val - 1 ].first.translated() );
     } else if( alert && val != 0 ) {
         eff_type->add_apply_msg( val );
     }
     if( val == 0 && !eff_type->int_decay_remove ) {
         val = 1;
     }
     intensity = val;
     return intensity;
 }
References effect_type::add_apply_msg(), add_msg(), add_msg_debug, effect_type::decay_msgs, debugmode::DF_EFFECT, eff_type, get_id(), effect_type::int_decay_remove, intensity, max(), effect_type::max_intensity, and min().
Referenced by Creature::add_effect(), decay(), eff_fun_rat(), eff_fun_sleep(), mod_intensity(), set_duration(), and Character::update_vitamins().
unpause_effect()
void effect::unpause_effect ()
Makes an effect not permanent.
Note: This un-pauses the duration, but does not otherwise change it.
Definition at line 1183 of file effect.cpp.
 {
     permanent = false;
 }
References permanent.
Referenced by Character::hardcoded_effects().
use_part_descs()
bool effect::use_part_descs () const
Returns true if a description will be formatted as "Your" + body_part + description.
Definition at line 1063 of file effect.cpp.
 {
     return eff_type->part_descs;
 }
References eff_type, and effect_type::part_descs.
Referenced by disp_desc().
vit_effects()
std::vector< vitamin_applied_effect > effect::vit_effects (bool reduced) const
Definition at line 1150 of file effect.cpp.
 {
     std::vector<vitamin_applied_effect> ret;
     ret.reserve( eff_type->vitamin_data.size() );
     for( const vitamin_rate_effect &vreff : eff_type->vitamin_data ) {
         ret.push_back( applied_from_rate( reduced, intensity, vreff ) );
     }
     return ret;
 }
References applied_from_rate(), eff_type, intensity, cata::hash64_detail::ret, and effect_type::vitamin_data.
Referenced by Character::process_one_effect().
Member Data Documentation
bp
bodypart_str_id effect::bp protected
Definition at line 439 of file effect.h.
Referenced by decay(), deserialize(), disp_desc(), disp_name(), get_bp(), Character::process_effects(), serialize(), and set_bp().
duration
time_duration effect::duration protected
Definition at line 438 of file effect.h.
Referenced by decay(), deserialize(), disp_desc(), get_duration(), mod_duration(), mult_duration(), serialize(), and set_duration().
eff_type
const effect_type* effect::eff_type protected
Definition at line 437 of file effect.h.
Referenced by activated(), death_event(), decay(), deserialize(), disp_desc(), disp_name(), disp_short_desc(), get_addict_mod(), get_amount(), get_avg_mod(), get_blocks_effects(), get_death_message(), get_dur_add_perc(), get_effect_dur_scaling(), get_effect_type(), get_effective_intensity(), get_harmful_cough(), get_id(), get_int_add_val(), get_int_decay_remove(), get_int_decay_step(), get_int_decay_tick(), get_int_dur_factor(), get_limb_score_data(), get_limb_score_mod(), get_max_duration(), get_max_effective_intensity(), get_max_intensity(), get_max_val(), get_min_val(), get_miss_msgs(), get_mod(), get_percentage(), get_removes_effects(), get_resist_effects(), get_resist_traits(), get_sizing(), get_speed_name(), has_flag(), impairs_movement(), is_null(), kill_roll(), serialize(), set_duration(), set_intensity(), use_part_descs(), and vit_effects().
intensity
int effect::intensity protected
Definition at line 441 of file effect.h.
Referenced by activated(), decay(), deserialize(), disp_desc(), disp_name(), disp_short_desc(), get_effective_intensity(), get_intensity(), get_limb_score_mod(), get_max_val(), get_min_val(), get_percentage(), get_speed_name(), kill_roll(), mod_intensity(), Character::process_effects(), serialize(), set_intensity(), and vit_effects().
null_effect
effect effect::null_effect static
Dummy used for "reference to effect()".
Definition at line 285 of file effect.h.
Referenced by talker::get_effect(), and Creature::get_effect().
permanent
bool effect::permanent protected
Definition at line 440 of file effect.h.
Referenced by deserialize(), is_permanent(), pause_effect(), Character::process_effects(), serialize(), and unpause_effect().
source
effect_source effect::source protected
Definition at line 443 of file effect.h.
Referenced by deserialize(), get_source(), and serialize().
start_time
time_point effect::start_time protected
Definition at line 442 of file effect.h.
Referenced by deserialize(), disp_desc(), get_start_time(), and serialize().
The documentation for this class was generated from the following files:
src/effect.h
src/effect.cpp