Cataclysm DDA: jmapgen_trap Class Reference
jmapgen_trap Class Reference
Place a trap.
Public Member Functions
jmapgen_trap (const JsonObject &jsi, const std::string_view)
jmapgen_trap (const JsonValue &tid)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
Public Attributes
mapgen_value< trap_id > id
bool remove = false
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Private Member Functions
void init (const JsonValue &jsi)
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a trap.
"trap": id of the trap.
Definition at line 2820 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_trap() [1/2]
jmapgen_trap::jmapgen_trap (const JsonObject & jsi, const std::string_view) inline
Definition at line 2826 of file mapgen.cpp.
{
             init( jsi.get_member( "trap" ) );
             remove = jsi.get_bool( "remove", false );
         }
References JsonObject::get_bool(), JsonObject::get_member(), init(), mapgen_defer::jsi, and remove.
jmapgen_trap() [2/2]
jmapgen_trap::jmapgen_trap (const JsonValue & tid) inline explicit
Definition at line 2831 of file mapgen.cpp.
{
             if( tid.test_object() ) {
                 JsonObject jo = tid.get_object();
                 remove = jo.get_bool( "remove", false );
                 if( jo.has_member( "trap" ) ) {
                     init( jo.get_member( "trap" ) );
                     return;
                 }
             }
             init( tid );
         }
References JsonObject::get_bool(), JsonObject::get_member(), JsonValue::get_object(), JsonObject::has_member(), init(), remove, and JsonValue::test_object().
Member Function Documentation
apply()
void jmapgen_trap::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2842 of file mapgen.cpp.
{
             trap_id chosen_id = id.get( dat );
             if( chosen_id.id().is_null() ) {
                 return;
             }
             const tripoint actual_loc = tripoint( x.get(), y.get(), dat.zlevel() + z.get() );
             if( remove ) {
                 dat.m.remove_trap( actual_loc );
             } else {
                 dat.m.trap_set( actual_loc, chosen_id );
             }
         }
References jmapgen_int::get(), int_id< T >::id(), string_id< T >::is_null(), mapgendata::m, remove, map::remove_trap(), map::trap_set(), tripoint, and mapgendata::zlevel().
check()
void jmapgen_trap::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 2859 of file mapgen.cpp.
{
             id.check( oter_name, parameters );
         }
has_vehicle_collision()
bool jmapgen_trap::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2855 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint_bub_ms( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
init()
void jmapgen_trap::init (const JsonValue & jsi) inline private
Definition at line 2865 of file mapgen.cpp.
{
             id = mapgen_value<trap_id>( jsi );
         }
References mapgen_defer::jsi.
Referenced by jmapgen_trap().
Member Data Documentation
id
mapgen_value<trap_id> jmapgen_trap::id
Definition at line 2823 of file mapgen.cpp.
remove
bool jmapgen_trap::remove = false
Definition at line 2824 of file mapgen.cpp.
Referenced by apply(), and jmapgen_trap().
The documentation for this class was generated from the following file:
src/mapgen.cpp