Cataclysm DDA: Item_spawn_data Class Reference
Item_spawn_data Class Reference abstract
Base interface for item spawn.
#include <item_group.h>
Classes
struct relic_generator
Public Types
enum class overflow_behaviour { none , spill , discard , last }
using ItemList = std::vector< item >
using RecursionList = std::vector< item_group_id >
Public Member Functions
Item_spawn_data (int _probability, const std::string &context, holiday _event=holiday::none)
virtual ~Item_spawn_data ()=default
virtual std::size_t create (ItemList &list, const time_point &birthday, RecursionList &rec, spawn_flags=spawn_flags::none) const =0
Create a list of items.
virtual void finalize (const itype_id &)=0
Instead of calculating at run-time, give a step to finalize those item_groups that has count-min but not count-max.
std::size_t create (ItemList &list, const time_point &birthday, spawn_flags=spawn_flags::none) const
virtual item create_single (const time_point &birthday, RecursionList &rec) const =0
The same as create, but create a single item only.
item create_single (const time_point &birthday) const
virtual void check_consistency (bool actually_spawn) const
Check item / spawn settings for consistency.
virtual bool remove_item (const itype_id &itemid)=0
For item blacklisted, remove the given item from this and all linked groups.
virtual void replace_items (const std::unordered_map< itype_id, itype_id > &replacements)=0
virtual bool has_item (const itype_id &itemid) const =0
virtual std::set< const itype * > every_item () const =0
const std::string & context () const
int get_probability (bool skip_event_check) const
void set_probablility (int prob)
bool is_event_based () const
Public Attributes
std::optional< itype_id > container_item
The group spawns contained in this item.
std::optional< std::string > container_item_variant
overflow_behaviour on_overflow = overflow_behaviour::none
std::optional< std::vector< itype_id > > components_items
These item(s) are spawned as components.
bool sealed = true
cata::value_ptr< relic_generator > artifact
Protected Attributes
int probability
probability, used by the parent object.
std::string context_
holiday event = holiday::none
Detailed Description
Base interface for item spawn.
Used to generate a list of items.
Definition at line 125 of file item_group.h.
Member Typedef Documentation
ItemList
using Item_spawn_data::ItemList = std::vector<item>
Definition at line 128 of file item_group.h.
RecursionList
using Item_spawn_data::RecursionList = std::vector<item_group_id>
Definition at line 129 of file item_group.h.
Member Enumeration Documentation
overflow_behaviour
enum Item_spawn_data::overflow_behaviour strong
Enumerator
none
spill
discard
last
Definition at line 131 of file item_group.h.
{
             none,
             spill,
             discard,
             last
         };
Constructor & Destructor Documentation
Item_spawn_data()
Item_spawn_data::Item_spawn_data (int _probability, const std::string & context, holiday _event = holiday::none) inline
Definition at line 138 of file item_group.h.
                                                                                                     :
             probability( _probability ), context_( context ), event( _event ) { }
~Item_spawn_data()
virtual Item_spawn_data::~Item_spawn_data () virtual default
Member Function Documentation
check_consistency()
void Item_spawn_data::check_consistency (bool actually_spawn) const virtual
Check item / spawn settings for consistency.
Includes checking for valid item types and valid settings.
Reimplemented in Item_group, and Single_item_creator.
Definition at line 49 of file item_group.cpp.
 {
     if( on_overflow != overflow_behaviour::none && !container_item ) {
         debugmsg( "item group %s specifies overflow behaviour but not container", context() );
     }
     // Spawn ourselves with all possible items being definitely spawned, so as
     // to verify e.g. that if a container item was specified it can actually
     // contain what was wanted.
     if( actually_spawn ) {
         ItemList dummy_list;
         dummy_list.reserve( 20 );
         create( dummy_list, calendar::turn_zero, spawn_flags::maximized );
     }
 }
References container_item, context(), create(), debugmsg, maximized, none, on_overflow, and calendar::turn_zero.
Referenced by Single_item_creator::check_consistency(), and Item_group::check_consistency().
context()
const std::string& Item_spawn_data::context () const inline
Definition at line 180 of file item_group.h.
{
             return context_;
         }
References context_.
Referenced by Item_group::add_item_entry(), check_consistency(), Single_item_creator::check_consistency(), Single_item_creator::create(), Item_group::create(), Single_item_creator::create_single_without_container(), Item_factory::load_item_group(), Item_factory::load_item_group_data(), Item_factory::load_sub_ref(), and put_into_container().
create() [1/2]
virtual std::size_t Item_spawn_data::create (ItemList & list, const time_point & birthday, RecursionList & rec, spawn_flags = spawn_flags::none) const pure virtual
Create a list of items.
The create list might be empty. No item of it will be the null item.
Parameters
[out] list New items are appended to the list
[in] birthday All items have that value as birthday.
[out] rec Recursion list, output goes here.
[in] spawn_flags Extra information to change how items are spawned.
Returns
The number of new items appended to the list
Implemented in Item_group, and Single_item_creator.
Referenced by jmapgen_loot::apply(), check_consistency(), Single_item_creator::create(), and create().
create() [2/2]
std::size_t Item_spawn_data::create (ItemList & list, const time_point & birthday, spawn_flags flags = spawn_flags::none) const
Definition at line 36 of file item_group.cpp.
 {
     RecursionList rec;
     return create( list, birthday, rec, flags );
 }
References create().
create_single() [1/2]
item Item_spawn_data::create_single (const time_point & birthday) const
Definition at line 43 of file item_group.cpp.
 {
     RecursionList rec;
     return create_single( birthday, rec );
 }
References create_single().
create_single() [2/2]
virtual item Item_spawn_data::create_single (const time_point & birthday, RecursionList & rec) const pure virtual
The same as create, but create a single item only.
The returned item might be a null item!
Implemented in Item_group, and Single_item_creator.
Referenced by create_single(), and Single_item_creator::create_single_without_container().
every_item()
virtual std::set<const itype *> Item_spawn_data::every_item () const pure virtual
Implemented in Item_group, and Single_item_creator.
Referenced by Single_item_creator::every_item().
finalize()
virtual void Item_spawn_data::finalize (const itype_id &) pure virtual
Instead of calculating at run-time, give a step to finalize those item_groups that has count-min but not count-max.
The reason is
Implemented in Item_group, and Single_item_creator.
get_probability()
int Item_spawn_data::get_probability (bool skip_event_check) const
Definition at line 917 of file item_group.cpp.
 {
     // Use probability as normal
     if( skip_event_check || event == holiday::none ) {
         return probability;
     }
     // Item spawn is event-based, but option is disabled
     std::string opt = get_option<std::string>( "EVENT_SPAWNS" );
     if( opt != "items" && opt != "both" ) {
         return 0;
     }
     // Use probability if the current holiday matches the item's spawn event
     if( event == get_holiday_from_time() ) {
         return probability;
     }
     // Not currently the item's holiday
     return 0;
 }
References event, get_holiday_from_time(), none, and probability.
has_item()
virtual bool Item_spawn_data::has_item (const itype_id & itemid) const pure virtual
Implemented in Item_group, and Single_item_creator.
Referenced by Single_item_creator::has_item().
is_event_based()
bool Item_spawn_data::is_event_based () const inline
Definition at line 188 of file item_group.h.
{
             return event != holiday::none;
         }
References none.
remove_item()
virtual bool Item_spawn_data::remove_item (const itype_id & itemid) pure virtual
For item blacklisted, remove the given item from this and all linked groups.
Implemented in Item_group, and Single_item_creator.
replace_items()
virtual void Item_spawn_data::replace_items (const std::unordered_map< itype_id, itype_id > & replacements) pure virtual
Implemented in Item_group, and Single_item_creator.
set_probablility()
void Item_spawn_data::set_probablility (int prob) inline
Definition at line 185 of file item_group.h.
{
             probability = prob;
         }
References probability.
Member Data Documentation
artifact
cata::value_ptr<relic_generator> Item_spawn_data::artifact
Definition at line 214 of file item_group.h.
Referenced by Single_item_creator::create(), and Single_item_creator::create_single_without_container().
components_items
std::optional<std::vector<itype_id> > Item_spawn_data::components_items
These item(s) are spawned as components.
Definition at line 201 of file item_group.h.
Referenced by Single_item_creator::create_single_without_container().
container_item
std::optional<itype_id> Item_spawn_data::container_item
The group spawns contained in this item.
Definition at line 195 of file item_group.h.
Referenced by check_consistency(), Single_item_creator::check_consistency(), Item_group::check_consistency(), Single_item_creator::create(), Item_group::create(), Single_item_creator::create_single(), Single_item_creator::finalize(), Item_group::finalize(), and Item_factory::load_item_group().
container_item_variant
std::optional<std::string> Item_spawn_data::container_item_variant
Definition at line 196 of file item_group.h.
Referenced by Single_item_creator::create(), Item_group::create(), Single_item_creator::create_single(), and Item_factory::load_item_group().
context_
std::string Item_spawn_data::context_ protected
Definition at line 221 of file item_group.h.
Referenced by context().
event
holiday Item_spawn_data::event = holiday::none protected
Definition at line 223 of file item_group.h.
Referenced by get_probability().
on_overflow
overflow_behaviour Item_spawn_data::on_overflow = overflow_behaviour::none
Definition at line 197 of file item_group.h.
Referenced by check_consistency(), Single_item_creator::create(), Item_group::create(), Item_factory::load_item_group(), and put_into_container().
probability
int Item_spawn_data::probability protected
probability, used by the parent object.
Definition at line 218 of file item_group.h.
Referenced by Item_group::add_group_entry(), Item_group::add_item_entry(), get_probability(), Item_group::Item_group(), and set_probablility().
sealed
bool Item_spawn_data::sealed = true
Definition at line 202 of file item_group.h.
Referenced by Single_item_creator::create(), Item_group::create(), Single_item_creator::create_single(), Item_factory::load_item_group(), and put_into_container().
The documentation for this class was generated from the following files:
src/item_group.h
src/item_group.cpp