Cataclysm DDA: json_talk_topic Class Reference
json_talk_topic Class Reference
Talk topic definitions load from json.
#include <dialogue.h>
Public Member Functions
json_talk_topic ()=default
void load (const JsonObject &jo)
Load data from json.
std::string get_dynamic_line (dialogue &d) const
std::vector< json_dynamic_line_effect > get_speaker_effects () const
void check_consistency () const
bool gen_responses (dialogue &d) const
Callback from dialogue::gen_responses, it should add the response from here into the list of possible responses (that will be presented to the player).
cata::flat_set< std::string > get_directly_reachable_topics (bool only_unconditional) const
Private Attributes
bool replace_built_in_responses = false
std::vector< json_talk_response > responses
dynamic_line_t dynamic_line
std::vector< json_dynamic_line_effect > speaker_effects
std::vector< json_talk_repeat_response > repeat_responses
Detailed Description
Talk topic definitions load from json.
Definition at line 419 of file dialogue.h.
Constructor & Destructor Documentation
json_talk_topic()
json_talk_topic::json_talk_topic () default
Member Function Documentation
check_consistency()
void json_talk_topic::check_consistency () const
Definition at line 7136 of file npctalk.cpp.
 {
     // TODO: check that all referenced topic actually exist. This is currently not possible
     // as they only exist as built in strings, not in the json_talk_topics map.
 }
gen_responses()
bool json_talk_topic::gen_responses (dialogue & d) const
Callback from dialogue::gen_responses, it should add the response from here into the list of possible responses (that will be presented to the player).
It may add an arbitrary number of responses (including none at all).
Returns
true if built in response should excluded (not added). If false, built in responses will be added (behind those added here).
Definition at line 7069 of file npctalk.cpp.
 {
     d.responses.reserve( responses.size() ); // A wild guess, can actually be more or less
     bool switch_done = false;
     for( const json_talk_response &r : responses ) {
         switch_done |= r.gen_responses( d, switch_done );
     }
     for( const json_talk_repeat_response &repeat : repeat_responses ) {
         talker *actor =  d.actor( repeat.is_npc );
         std::function<bool( const item & )> filter = return_true<item>;
         for( const itype_id &item_id : repeat.for_item ) {
             if( actor->charges_of( item_id ) > 0 || actor->has_amount( item_id, 1 ) ) {
                 switch_done |= repeat.response.gen_repeat_response( d, item_id, switch_done );
             }
         }
         for( const item_category_id &category_id : repeat.for_category ) {
             const bool include_containers = repeat.include_containers;
             const auto items_with = actor->items_with( [category_id,
             include_containers]( const item & it ) {
                 if( include_containers ) {
                     return it.get_category_of_contents().get_id() == category_id;
                 }
                 return it.type && it.type->category_force == category_id;
             } );
             for( item * const &it : items_with ) {
                 switch_done |= repeat.response.gen_repeat_response( d, it->typeId(), switch_done );
             }
         }
     }
     return replace_built_in_responses;
 }
References dialogue::actor(), itype::category_force, talker::charges_of(), filter, item::get_category_of_contents(), std::this_thread::get_id(), talker::has_amount(), talker::items_with(), repeat_responses, replace_built_in_responses, dialogue::responses, responses, item::type, and item::typeId().
Referenced by dialogue::gen_responses().
get_directly_reachable_topics()
cata::flat_set< std::string > json_talk_topic::get_directly_reachable_topics (bool only_unconditional) const
Definition at line 7103 of file npctalk.cpp.
 {
     std::vector<std::string> result;
     auto add_reachable_for_response = [&]( const json_talk_response & json_response ) {
         const talk_response &response = json_response.get_actual_response();
         if( !only_unconditional || !json_response.has_condition() ) {
             result.push_back( response.success.next_topic.id );
             result.push_back( response.failure.next_topic.id );
         }
     };
     for( const json_talk_response &r : responses ) {
         add_reachable_for_response( r );
     }
     for( const json_talk_repeat_response &r : repeat_responses ) {
         add_reachable_for_response( r.response );
     }
     return cata::flat_set<std::string>( result.begin(), result.end() );
 }
References talk_response::failure, talk_topic::id, talk_effect_t::next_topic, repeat_responses, responses, and talk_response::success.
get_dynamic_line()
std::string json_talk_topic::get_dynamic_line (dialogue & d) const
Definition at line 7126 of file npctalk.cpp.
 {
     return dynamic_line( d );
 }
References dynamic_line.
get_speaker_effects()
std::vector< json_dynamic_line_effect > json_talk_topic::get_speaker_effects () const
Definition at line 7131 of file npctalk.cpp.
 {
     return speaker_effects;
 }
References speaker_effects.
load()
void json_talk_topic::load (const JsonObject & jo)
Load data from json.
This will append responses (not change existing ones). It will override dynamic_line and replace_built_in_responses if those entries exist in the input, otherwise they will not be changed at all.
Definition at line 7012 of file npctalk.cpp.
 {
     if( jo.has_member( "dynamic_line" ) ) {
         dynamic_line = dynamic_line_t::from_member( jo, "dynamic_line" );
     }
     if( jo.has_member( "speaker_effect" ) ) {
         std::string id = "no_id";
         if( jo.has_string( "id" ) ) {
             id = jo.get_string( "id" );
         } else if( jo.has_array( "id" ) ) {
             id = jo.get_array( "id" ).next_string();
         }
         if( jo.has_object( "speaker_effect" ) ) {
             JsonObject speaker_effect = jo.get_object( "speaker_effect" );
             speaker_effects.emplace_back( speaker_effect, id );
         } else if( jo.has_array( "speaker_effect" ) ) {
             for( JsonObject speaker_effect : jo.get_array( "speaker_effect" ) ) {
                 speaker_effects.emplace_back( speaker_effect, id );
             }
         }
     }
     bool insert_above_bottom = false;
     if( jo.has_bool( "insert_before_standard_exits" ) ) {
         insert_above_bottom = jo.get_bool( "insert_before_standard_exits" );
     }
     if( !insert_above_bottom || responses.empty() ) {
         for( JsonObject response : jo.get_array( "responses" ) ) {
             responses.emplace_back( response );
         }
     } else {
         int dec_count = 0;
         if( !responses.empty() &&
             responses.back().get_actual_response().success.next_topic.id == "TALK_DONE" ) {
             dec_count = 1;
         }
         if( responses.size() >= 2 &&
             responses[ responses.size() - 2].get_actual_response().success.next_topic.id == "TALK_NONE" ) {
             dec_count = 2;
         }
         for( JsonObject response : jo.get_array( "responses" ) ) {
             responses.emplace( responses.end() - dec_count, response );
         }
     }
     if( jo.has_object( "repeat_responses" ) ) {
         repeat_responses.emplace_back( jo.get_object( "repeat_responses" ) );
     } else if( jo.has_array( "repeat_responses" ) ) {
         for( JsonObject elem : jo.get_array( "repeat_responses" ) ) {
             repeat_responses.emplace_back( elem );
         }
     }
     if( responses.empty() ) {
         jo.throw_error_at( "responses", "no responses for talk topic defined" );
     }
     replace_built_in_responses = jo.get_bool( "replace_built_in_responses",
                                  replace_built_in_responses );
 }
References dynamic_line, dynamic_line_t::from_member(), JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_bool(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), JsonArray::next_string(), repeat_responses, replace_built_in_responses, responses, speaker_effects, and JsonObject::throw_error_at().
Member Data Documentation
dynamic_line
dynamic_line_t json_talk_topic::dynamic_line private
Definition at line 424 of file dialogue.h.
Referenced by get_dynamic_line(), and load().
repeat_responses
std::vector<json_talk_repeat_response> json_talk_topic::repeat_responses private
Definition at line 426 of file dialogue.h.
Referenced by gen_responses(), get_directly_reachable_topics(), and load().
replace_built_in_responses
bool json_talk_topic::replace_built_in_responses = false private
Definition at line 422 of file dialogue.h.
Referenced by gen_responses(), and load().
responses
std::vector<json_talk_response> json_talk_topic::responses private
Definition at line 423 of file dialogue.h.
Referenced by gen_responses(), get_directly_reachable_topics(), and load().
speaker_effects
std::vector<json_dynamic_line_effect> json_talk_topic::speaker_effects private
Definition at line 425 of file dialogue.h.
Referenced by get_speaker_effects(), and load().
The documentation for this class was generated from the following files:
src/dialogue.h
src/npctalk.cpp