Cataclysm DDA: read_only_visitable Class Reference
read_only_visitable Class Reference abstract
Read-only interface for the "container of items".
#include <visitable.h>
Public Member Functions
virtual VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const =0
Traverses this object and any child items contained using a visitor pattern.
item * find_parent (const item &it) const
Determine the immediate parent container (if any) for an item.
std::vector< item * > parents (const item &it) const
Returns vector of parent containers (if any) starting with the innermost.
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
virtual bool has_quality (const quality_id &qual, int level=1, int qty=1) const
Returns true if instance has amount (or more) items of at least quality level.
virtual int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
std::pair< int, int > kcal_range (const itype_id &id, const std::function< bool(const item &)> &filter, Character &player_character) const
virtual int charges_of (const itype_id &what, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >, const std::function< void(int)> &visitor=nullptr, bool in_tools=false) const
Count maximum available charges from this instance and any contained items.
virtual int amount_of (const itype_id &what, bool pseudo=true, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
virtual ~read_only_visitable ()=default
bool has_tools (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
bool has_components (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
virtual bool has_charges (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
Detailed Description
Read-only interface for the "container of items".
Provides API for the traversal and querying of the items hierarchy.
Definition at line 26 of file visitable.h.
Constructor & Destructor Documentation
~read_only_visitable()
virtual read_only_visitable::~read_only_visitable () virtual default
Member Function Documentation
amount_of()
virtual int read_only_visitable::amount_of (const itype_id & what, bool pseudo = true, int limit = INT_MAX, const std::function< bool(const item &)> & filter = return_true< item >) const virtual
Count items matching id including both this instance and any contained items.
Parameters
what ID of items to count. "any" will count all items (usually used with a filter)
pseudo whether pseudo-items (from map/vehicle tiles, bionics etc) are considered
limit stop searching after this many matches
filter only count items that match the filter
Note
items must be empty to be considered a match
Reimplemented in inventory, Character, and visitable.
Referenced by craft_command::check_item_components_missing(), requirement_data::get_folded_list(), visitable::has_amount(), and Character::select_item_component().
charges_of()
virtual int read_only_visitable::charges_of (const itype_id & what, int limit = INT_MAX, const std::function< bool(const item &)> & filter = return_true< item >, const std::function< void(int)> & visitor = nullptr, bool in_tools = false) const virtual
Count maximum available charges from this instance and any contained items.
Parameters
what ID of item to count charges of
limit stop searching after this many charges have been found
filter only count charges of items that match the filter
visitor is called when UPS charge is used (parameter is the charge itself)
Reimplemented in inventory, Character, and visitable.
Referenced by craft_command::check_item_components_missing(), requirement_data::get_folded_list(), tool_comp::has(), has_charges(), requirement_data::has_comps(), Character::select_item_component(), and Character::select_tool_component().
find_parent()
item* read_only_visitable::find_parent (const item & it) const
Determine the immediate parent container (if any) for an item.
Parameters
it item to search for which must be contained (at any depth) by this object
Returns
parent container or nullptr if the item is not within a container
Referenced by visitable::parents().
has_amount()
bool read_only_visitable::has_amount (const itype_id & what, int qty, bool pseudo = true, const std::function< bool(const item &)> & filter = return_true< item >) const
Check instance provides at least qty of an item (.
See also
amount_of)
Referenced by has_components(), and has_tools().
has_charges()
bool read_only_visitable::has_charges (const itype_id & it, int quantity, const std::function< bool(const item &)> & filter = return_true<item>) const virtual
Reimplemented in Character.
Definition at line 223 of file visitable.cpp.
 {
     return ( charges_of( it, INT_MAX, filter ) >= quantity );
 }
References charges_of(), and filter.
Referenced by craft_command::check_item_components_missing(), craft_command::check_tool_components_missing(), Character::craft_consume_tools(), wash_activity_actor::finish(), suffer::from_asthma(), repair_item_actor::handle_components(), item_comp::has(), repair_inventory_preset::repair_inventory_preset(), repair_item_finish(), Character::select_tool_component(), vehicle::use_dishwasher(), vehicle::use_washing_machine(), and iuse::wash_items().
has_components()
bool read_only_visitable::has_components (const itype_id & it, int quantity, const std::function< bool(const item &)> & filter = return_true<item>) const
Definition at line 217 of file visitable.cpp.
 {
     return has_amount( it, quantity, false, filter );
 }
References filter, and has_amount().
Referenced by craft_command::check_item_components_missing(), item_comp::has(), and Character::select_item_component().
has_item()
bool read_only_visitable::has_item (const item & it) const
Returns true if this visitable instance contains the item.
has_item_with()
bool read_only_visitable::has_item_with (const std::function< bool(const item &)> & filter) const
Returns true if any item (including those within a container) matches the filter.
has_quality()
bool read_only_visitable::has_quality (const quality_id & qual, int level = 1, int qty = 1) const virtual
Returns true if instance has amount (or more) items of at least quality level.
Reimplemented in vehicle_selector, vehicle_cursor, inventory, Character, and visitable.
Definition at line 147 of file visitable.cpp.
 {
     return has_quality_internal( *this, qual, level, qty ) == qty;
 }
References has_quality_internal().
Referenced by requirement_data::check_enough_materials(), and quality_requirement::has().
has_tools()
bool read_only_visitable::has_tools (const itype_id & it, int quantity, const std::function< bool(const item &)> & filter = return_true<item>) const
Definition at line 211 of file visitable.cpp.
 {
     return has_amount( it, quantity, true, filter );
 }
References filter, and has_amount().
Referenced by craft_command::check_tool_components_missing(), Character::craft_consume_tools(), vehicle_folding_activity_actor::fold_vehicle(), tool_comp::has(), iuse::multicooker(), Character::select_tool_component(), and vehicle_unfolding_activity_actor::unfold_vehicle().
items_with() [1/2]
std::vector<item *> read_only_visitable::items_with (const std::function< bool(const item &)> & filter)
Returns all items (including those within a container) matching the filter.
items_with() [2/2]
std::vector<const item *> read_only_visitable::items_with (const std::function< bool(const item &)> & filter) const
kcal_range()
std::pair< int, int > read_only_visitable::kcal_range (const itype_id & id, const std::function< bool(const item &)> & filter, Character & player_character) const
Definition at line 876 of file visitable.cpp.
 {
     return kcal_range_of_internal( *this, id, filter, player_character );
 }
References filter, and kcal_range_of_internal().
max_quality()
int read_only_visitable::max_quality (const quality_id & qual) const virtual
Return maximum tool quality level provided by instance or INT_MIN if not found.
Reimplemented in vehicle_selector, vehicle_cursor, Character, and visitable.
Definition at line 262 of file visitable.cpp.
 {
     return max_quality_internal( *this, qual );
 }
References max_quality_internal().
parents()
std::vector<item *> read_only_visitable::parents (const item & it) const
Returns vector of parent containers (if any) starting with the innermost.
Parameters
it item to search for which must be contained (at any depth) by this object
visit_items()
virtual VisitResponse read_only_visitable::visit_items (const std::function< VisitResponse(item *, item *)> & func) const pure virtual
Traverses this object and any child items contained using a visitor pattern.
Note
Implement for each class that will implement the visitable interface. Other visit_items variants rely on this function.
Parameters
func visitor function called for each node which controls whether traversal continues. The first argument is the node and the second is the parent node (if any) The visitor function should return VisitResponse::Next to recursively process child items, VisitResponse::Skip to ignore children of the current node or VisitResponse::Abort to skip all remaining nodes
Returns
This method itself only ever returns VisitResponse::Next or VisitResponse::Abort.
Implemented in vehicle_selector, vehicle_cursor, temp_crafting_inventory, map_selector, map_cursor, item, inventory, Character, and visitable.
Referenced by temp_crafting_inventory::add_all_ref(), visitable::find_parent(), visitable::has_item(), and visitable::has_item_with().
The documentation for this class was generated from the following files:
src/visitable.h
src/visitable.cpp