Cataclysm DDA: user_turn Class Reference
user_turn Class Reference
Public Member Functions
user_turn ()
bool has_timeout_elapsed ()
int moves_elapsed ()
bool async_anim_timeout ()
bool blink_timeout ()
Public Attributes
std::chrono::steady_clock::time_point last_blink_transition = std::chrono::steady_clock::now()
Private Attributes
std::chrono::time_point< std::chrono::steady_clock > user_turn_start
Detailed Description
Definition at line 185 of file handle_action.cpp.
Constructor & Destructor Documentation
user_turn()
user_turn::user_turn () inline
Definition at line 191 of file handle_action.cpp.
                     {
             user_turn_start = std::chrono::steady_clock::now();
         }
References user_turn_start.
Member Function Documentation
async_anim_timeout()
bool user_turn::async_anim_timeout () inline
Definition at line 215 of file handle_action.cpp.
{
             std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now();
             std::chrono::milliseconds elapsed_ms =
                 std::chrono::duration_cast<std::chrono::milliseconds>( now - user_turn_start );
             return elapsed_ms.count() > get_option<int>( "ANIMATION_DELAY" );
         }
References user_turn_start.
Referenced by game::get_player_input().
blink_timeout()
bool user_turn::blink_timeout () inline
Definition at line 223 of file handle_action.cpp.
{
             std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now();
             std::chrono::milliseconds elapsed_ms =
                 std::chrono::duration_cast<std::chrono::milliseconds>( now - last_blink_transition );
             if( elapsed_ms.count() > get_option<int>( "BLINK_SPEED" ) ) {
                 last_blink_transition = now;
                 return true;
             }
             return false;
         }
References last_blink_transition.
Referenced by game::get_player_input().
has_timeout_elapsed()
bool user_turn::has_timeout_elapsed () inline
Definition at line 195 of file handle_action.cpp.
{
             return moves_elapsed() > 100;
         }
References moves_elapsed().
Referenced by game::get_player_input().
moves_elapsed()
int user_turn::moves_elapsed () inline
Definition at line 199 of file handle_action.cpp.
{
             const float turn_duration = get_option<float>( "TURN_DURATION" );
             // Magic number 0.005 chosen due to option menu's 2 digit precision and
             // the option menu UI rounding <= 0.005 down to "0.00" in the display.
             // This conditional will catch values (e.g. 0.003) that the options menu
             // would round down to "0.00" in the options menu display. This prevents
             // the user from being surprised by floating point rounding near zero.
             if( turn_duration <= 0.005 ) {
                 return 0;
             }
             std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now();
             std::chrono::milliseconds elapsed_ms =
                 std::chrono::duration_cast<std::chrono::milliseconds>( now - user_turn_start );
             return elapsed_ms.count() / ( 10.0 * turn_duration );
         }
References user_turn_start.
Referenced by game::handle_action(), and has_timeout_elapsed().
Member Data Documentation
last_blink_transition
std::chrono::steady_clock::time_point user_turn::last_blink_transition = std::chrono::steady_clock::now()
Definition at line 222 of file handle_action.cpp.
Referenced by blink_timeout().
user_turn_start
std::chrono::time_point<std::chrono::steady_clock> user_turn::user_turn_start private
Definition at line 189 of file handle_action.cpp.
Referenced by async_anim_timeout(), moves_elapsed(), and user_turn().
The documentation for this class was generated from the following file:
src/handle_action.cpp