Cataclysm DDA: addiction Class Reference
addiction Class Reference
#include <addiction.h>
Public Member Functions
addiction ()=default
addiction (const addiction_id &t, const int i=1)
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
bool run_effect (Character &u)
Runs one update of this addiction's effects.
Public Attributes
addiction_id type
int intensity = 0
time_duration sated = 1_hours
Detailed Description
Definition at line 58 of file addiction.h.
Constructor & Destructor Documentation
addiction() [1/2]
addiction::addiction () default
addiction() [2/2]
addiction::addiction (const addiction_id & t, const int i = 1) inline explicit
Definition at line 66 of file addiction.h.
 : type {t}, intensity {i} { }
Member Function Documentation
deserialize()
void addiction::deserialize (const JsonObject & jo)
Definition at line 4122 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     // legacy
     if( jo.has_int( "type_enum" ) ) {
         enum class add_type_legacy : int {
             NONE,
             CAFFEINE,
             ALCOHOL,
             SLEEP,
             PKILLER,
             SPEED,
             CIG,
             COKE,
             CRACK,
             MUTAGEN,
             DIAZEPAM,
             MARLOSS_R,
             MARLOSS_B,
             MARLOSS_Y,
             NUM_ADD_TYPES
         };
         switch( static_cast<add_type_legacy>( jo.get_int( "type_enum" ) ) ) {
             case add_type_legacy::CAFFEINE:
                 type = STATIC( addiction_id( "caffeine" ) );
                 break;
             case add_type_legacy::ALCOHOL:
                 type = STATIC( addiction_id( "alcohol" ) );
                 break;
             case add_type_legacy::SLEEP:
                 type = STATIC( addiction_id( "sleeping pill" ) );
                 break;
             case add_type_legacy::PKILLER:
                 type = STATIC( addiction_id( "opiate" ) );
                 break;
             case add_type_legacy::SPEED:
                 type = STATIC( addiction_id( "amphetamine" ) );
                 break;
             case add_type_legacy::CIG:
                 type = STATIC( addiction_id( "nicotine" ) );
                 break;
             case add_type_legacy::COKE:
                 type = STATIC( addiction_id( "cocaine" ) );
                 break;
             case add_type_legacy::CRACK:
                 type = STATIC( addiction_id( "crack" ) );
                 break;
             case add_type_legacy::MUTAGEN:
                 type = STATIC( addiction_id( "mutagen" ) );
                 break;
             case add_type_legacy::DIAZEPAM:
                 type = STATIC( addiction_id( "diazepam" ) );
                 break;
             case add_type_legacy::MARLOSS_R:
                 type = STATIC( addiction_id( "marloss_r" ) );
                 break;
             case add_type_legacy::MARLOSS_B:
                 type = STATIC( addiction_id( "marloss_b" ) );
                 break;
             case add_type_legacy::MARLOSS_Y:
                 type = STATIC( addiction_id( "marloss_y" ) );
                 break;
             case add_type_legacy::NONE:
             case add_type_legacy::NUM_ADD_TYPES:
             default:
                 type = addiction_id::NULL_ID();
                 break;
         }
     } else {
         jo.read( "type", type );
     }
     intensity = jo.get_int( "intensity" );
     jo.read( "sated", sated );
 }
References addiction_id, JsonObject::allow_omitted_members(), JsonObject::get_int(), JsonObject::has_int(), intensity, NONE, string_id< add_type >::NULL_ID(), JsonObject::read(), SPEED, STATIC, and type.
run_effect()
bool addiction::run_effect (Character & u)
Runs one update of this addiction's effects.
Definition at line 340 of file addiction.cpp.
 {
     bool ret = false;
     if( !type->get_effect().is_null() ) {
         dialogue d( get_talker_for( u ), nullptr );
         ret = type->get_effect()->activate( d );
     } else {
         auto iter = builtin_map.find( type->get_builtin() );
         if( iter != builtin_map.end() ) {
             ret = iter->second.operator()( u, *this );
         } else {
             debugmsg( "invalid builtin \"%s\" for addiction_type \"%s\"", type->get_builtin(), type.c_str() );
         }
     }
     return ret;
 }
References effect_on_condition::activate(), builtin_map, string_id< T >::c_str(), debugmsg, add_type::get_builtin(), add_type::get_effect(), get_talker_for(), string_id< T >::is_null(), cata::hash64_detail::ret, type, and u.
Referenced by suffer::from_addictions().
serialize()
void addiction::serialize (JsonOut & json) const
Definition at line 4113 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "type", type );
     json.member( "intensity", intensity );
     json.member( "sated", sated );
     json.end_object();
 }
References JsonOut::end_object(), intensity, JsonOut::member(), JsonOut::start_object(), and type.
Member Data Documentation
intensity
int addiction::intensity = 0
Definition at line 62 of file addiction.h.
Referenced by draw_effects_summary(), and suffer::from_addictions().
sated
time_duration addiction::sated = 1_hours
Definition at line 63 of file addiction.h.
Referenced by draw_effects_summary(), and suffer::from_addictions().
type
addiction_id addiction::type
Definition at line 61 of file addiction.h.
Referenced by draw_effects_summary(), addiction_reader::erase_next(), suffer::from_addictions(), and run_effect().
The documentation for this class was generated from the following files:
src/addiction.h
src/addiction.cpp
src/savegame_json.cpp