Cataclysm DDA: vpart_variant Class Reference
vpart_variant Class Reference
#include <veh_type.h>
Public Member Functions
std::string get_label () const
char32_t get_symbol (units::angle direction, bool is_broken) const
int get_symbol_curses (units::angle direction, bool is_broken) const
Static Public Member Functions
static int get_symbol_curses (char32_t sym)
Public Attributes
std::string id
std::array< char32_t, 8 > symbols
std::array< char32_t, 8 > symbols_broken
Private Member Functions
void load (const JsonObject &jo, bool was_loaded)
Private Attributes
std::string label_
Friends
class vpart_info
Detailed Description
Definition at line 209 of file veh_type.h.
Member Function Documentation
get_label()
std::string vpart_variant::get_label () const
Definition at line 1162 of file veh_type.cpp.
 {
     return to_translation( "vpart_variants", label_ ).translated();
 }
References label_, to_translation(), and translation::translated().
get_symbol()
char32_t vpart_variant::get_symbol (units::angle direction, bool is_broken) const
Definition at line 1167 of file veh_type.cpp.
 {
     const int dir8 = angle_to_dir8( direction );
     return is_broken ? symbols_broken[dir8] : symbols[dir8];
 }
References angle_to_dir8(), symbols, and symbols_broken.
Referenced by vehicle::get_display_of_tile(), and get_symbol_curses().
get_symbol_curses() [1/2]
int vpart_variant::get_symbol_curses (char32_t sym) static
Definition at line 1196 of file veh_type.cpp.
 {
     return utf32_to_ncurses_ACS( sym );
 }
References utf32_to_ncurses_ACS().
get_symbol_curses() [2/2]
int vpart_variant::get_symbol_curses (units::angle direction, bool is_broken) const
Definition at line 1191 of file veh_type.cpp.
 {
     return get_symbol_curses( get_symbol( direction, is_broken ) );
 }
References get_symbol().
Referenced by veh_interact::display_list(), and vehicle::get_display_of_tile().
load()
void vpart_variant::load (const JsonObject & jo, bool was_loaded) private
Definition at line 1201 of file veh_type.cpp.
 {
     optional( jo, was_loaded, "id", id, "" );
     optional( jo, was_loaded, "label", label_ );
     const auto symbol_read = [&]( std::array<char32_t, 8> &dst, const std::string & member ) {
         if( jo.has_string( member ) ) {
             const std::vector<std::string> symbols = utf8_display_split( jo.get_string( member ) );
             if( symbols.size() == 1 ) {
                 dst.fill( UTF8_getch( jo.get_string( member ) ) );
             } else if( symbols.size() == 8 ) {
                 for( size_t i = 0; i < 8; i++ ) {
                     dst[i] = UTF8_getch( symbols[i] );
                 }
                 return;
             } else {
                 dst.fill( '?' );
                 jo.throw_error_at( "symbols",
                                    string_format( "'%s' must be string with 1 or 8 characters", member ) );
             }
         } else {
             dst.fill( '?' );
             jo.throw_error( string_format( "'%s' is missing", member ) );
         }
     };
     symbol_read( symbols, "symbols" );
     symbol_read( symbols_broken, "symbols_broken" );
 }
References JsonObject::get_string(), JsonObject::has_string(), label_, member, optional(), string_format(), symbols, symbols_broken, JsonObject::throw_error(), JsonObject::throw_error_at(), utf8_display_split(), and UTF8_getch().
Referenced by vpart_info::load().
Friends And Related Function Documentation
vpart_info
friend class vpart_info friend
Definition at line 235 of file veh_type.h.
Member Data Documentation
id
std::string vpart_variant::id
Definition at line 212 of file veh_type.h.
Referenced by vpart_info::finalize(), vpart_display::get_tileset_id(), and vpart_info::load().
label_
std::string vpart_variant::label_ private
Definition at line 234 of file veh_type.h.
Referenced by vpart_info::finalize(), get_label(), and load().
symbols
std::array<char32_t, 8> vpart_variant::symbols
Definition at line 213 of file veh_type.h.
Referenced by vpart_info::finalize(), get_symbol(), and load().
symbols_broken
std::array<char32_t, 8> vpart_variant::symbols_broken
Definition at line 214 of file veh_type.h.
Referenced by vpart_info::finalize(), get_symbol(), and load().
The documentation for this class was generated from the following files:
src/veh_type.h
src/veh_type.cpp