Cataclysm DDA: ignorable_options Class Reference
ignorable_options Class Reference
#include <clzones.h>
Public Member Functions
bool get_ignore_contents () const
bool has_options () const override
bool query_at_creation () override
bool query () override
std::vector< std::pair< std::string, std::string > > get_descriptions () const override
void serialize (JsonOut &json) const override
void deserialize (const JsonObject &jo_zone) override
Public Member Functions inherited from zone_options
virtual ~zone_options ()=default
virtual std::string get_zone_name_suggestion () const
Private Types
enum query_ignorable_result { canceled , successful , changed }
Private Member Functions
query_ignorable_result query_ignorable ()
Private Attributes
bool ignore_contents
Additional Inherited Members
Static Public Member Functions inherited from zone_options
static shared_ptr_fast< zone_options > create (const zone_type_id &type)
static bool is_valid (const zone_type_id &type, const zone_options &options)
Detailed Description
Definition at line 213 of file clzones.h.
Member Enumeration Documentation
query_ignorable_result
enum ignorable_options::query_ignorable_result private
Enumerator
canceled
successful
changed
Definition at line 218 of file clzones.h.
{
             canceled,
             successful,
             changed,
         };
Member Function Documentation
deserialize()
void ignorable_options::deserialize (const JsonObject & jo_zone) override virtual
Reimplemented from zone_options.
Definition at line 524 of file clzones.cpp.
 {
     jo_zone.read( "ignore_contents", ignore_contents );
 }
References ignore_contents, and JsonObject::read().
get_descriptions()
std::vector< std::pair< std::string, std::string > > ignorable_options::get_descriptions () const override virtual
Reimplemented from zone_options.
Definition at line 460 of file clzones.cpp.
 {
     std::vector<std::pair<std::string, std::string>> options;
     options.emplace_back( _( "Ignore contents: " ),
                           string_format( "%s", ignore_contents ? _( "True" ) : _( "False" ) ) );
     return options;
 }
References _, ignore_contents, PATH_INFO::options(), and string_format().
get_ignore_contents()
bool ignorable_options::get_ignore_contents () const inline
Definition at line 227 of file clzones.h.
{
             return ignore_contents;
         }
References ignore_contents.
has_options()
bool ignorable_options::has_options () const inline override virtual
Reimplemented from zone_options.
Definition at line 230 of file clzones.h.
{
             return true;
         }
query()
bool ignorable_options::query () override virtual
Reimplemented from zone_options.
Definition at line 388 of file clzones.cpp.
 {
     return query_ignorable() == changed;
 }
References changed, and query_ignorable().
query_at_creation()
bool ignorable_options::query_at_creation () override virtual
Reimplemented from zone_options.
Definition at line 363 of file clzones.cpp.
 {
     return query_ignorable() != canceled;
 }
References canceled, and query_ignorable().
query_ignorable()
ignorable_options::query_ignorable_result ignorable_options::query_ignorable () private
Definition at line 260 of file clzones.cpp.
 {
     ignore_contents = query_yn( _( "Ignore items in this area when sorting?" ) );
     return changed;
 }
References _, changed, ignore_contents, and query_yn().
Referenced by query(), and query_at_creation().
serialize()
void ignorable_options::serialize (JsonOut & json) const override virtual
Reimplemented from zone_options.
Definition at line 519 of file clzones.cpp.
 {
     json.member( "ignore_contents", ignore_contents );
 }
References ignore_contents, and JsonOut::member().
Member Data Documentation
ignore_contents
bool ignorable_options::ignore_contents private
Definition at line 216 of file clzones.h.
Referenced by deserialize(), get_descriptions(), get_ignore_contents(), query_ignorable(), and serialize().
The documentation for this class was generated from the following files:
src/clzones.h
src/clzones.cpp