Cataclysm DDA: field_entry Class Reference
field_entry Class Reference
An active or passive effect existing on a tile.
#include <field.h>
Public Member Functions
field_entry ()
field_entry (const field_type_id &t, const int i, const time_duration &a)
nc_color color () const
std::string symbol () const
const field_intensity_level & get_intensity_level () const
field_type_id get_field_type () const
field_type_id set_field_type (const field_type_id &new_type)
int get_max_field_intensity () const
int get_field_intensity () const
int set_field_intensity (int new_intensity)
void mod_field_intensity (int mod)
time_duration get_field_age () const
time_duration set_field_age (const time_duration &new_age)
Sets age to the given value.
time_duration mod_field_age (const time_duration &mod_age)
Adds given value to age.
bool is_dangerous () const
bool is_mopsafe () const
std::string name () const
bool is_field_alive () const
bool gas_can_spread () const
void initialize_decay ()
void do_decay ()
std::vector< field_effect > field_effects () const
Private Attributes
field_type_id type
int intensity
time_duration age
time_point decay_time
bool is_alive
Detailed Description
An active or passive effect existing on a tile.
Each effect can vary in intensity and age (usually used as a time to live).
Definition at line 20 of file field.h.
Constructor & Destructor Documentation
field_entry() [1/2]
field_entry::field_entry () inline
Definition at line 23 of file field.h.
                       : type( fd_null.id_or( INVALID_FIELD_TYPE_ID ) ), intensity( 1 ), age( 0_turns ),
             is_alive( false ) { }
field_entry() [2/2]
field_entry::field_entry (const field_type_id & t, const int i, const time_duration & a) inline
Definition at line 25 of file field.h.
                                                                                    : type( t ),
             intensity( i ), age( a ), is_alive( true ) { }
Member Function Documentation
color()
nc_color field_entry::color () const
Definition at line 17 of file field.cpp.
 {
     return get_intensity_level().color;
 }
References field_intensity_level::color, and get_intensity_level().
Referenced by colorized_field_description_at(), editmap_hilight::draw(), editmap::draw_main_ui_overlay(), map::draw_maptile(), game::print_fields_info(), and editmap::update_view_with_help().
do_decay()
void field_entry::do_decay ()
Definition at line 89 of file field.cpp.
 {
     // Bypass set_field_age() so we don't reset decay_time;
     age += 1_turns;
     if( type.obj().half_life > 0_turns && get_field_age() > 0_turns ) {
         // Legacy handling for fire because it's weird and complicated.
         if( type == STATIC( field_type_str_id( "fd_fire" ) ) ) {
             if( to_turns<int>( type->half_life ) < dice( 2, to_turns<int>( age ) ) ) {
                 set_field_age( 0_turns );
                 set_field_intensity( get_field_intensity() - 1 );
             }
             return;
         }
         if( decay_time == calendar::turn_zero ) {
             initialize_decay();
         }
         if( decay_time <= calendar::turn ) {
             set_field_age( 0_turns );
             set_field_intensity( get_field_intensity() - 1 );
         }
     }
 }
References age, decay_time, dice(), field_type_str_id, get_field_age(), get_field_intensity(), field_type::half_life, initialize_decay(), int_id< T >::obj(), set_field_age(), set_field_intensity(), STATIC, calendar::turn, calendar::turn_zero, and type.
Referenced by map::process_fields_in_submap().
field_effects()
std::vector< field_effect > field_entry::field_effects () const
Definition at line 266 of file field.cpp.
 {
     return type->get_intensity_level( intensity - 1 ).field_effects;
 }
References field_intensity_level::field_effects, field_type::get_intensity_level(), intensity, and type.
gas_can_spread()
bool field_entry::gas_can_spread () const inline
Definition at line 76 of file field.h.
{
             return is_field_alive() && type.obj().phase == phase_id::GAS && type.obj().percent_spread > 0;
         }
References GAS, is_field_alive(), int_id< T >::obj(), field_type::percent_spread, field_type::phase, and type.
get_field_age()
time_duration field_entry::get_field_age () const
Returns
age.
Definition at line 70 of file field.cpp.
 {
     return age;
 }
References age.
Referenced by map::decay_cosmetic_fields(), map::decay_fields_and_scent(), do_decay(), map::drop_fields(), field_processor_fd_acid(), field_processor_fd_acid_vent(), field_processor_fd_electricity(), field_processor_fd_last_known(), map::gas_spread_to(), map::get_field_age(), mod_field_age(), map::process_fields_in_submap(), map::spread_gas(), submap::store(), and editmap::update_view_with_help().
get_field_intensity()
int field_entry::get_field_intensity () const
Definition at line 53 of file field.cpp.
 {
     return intensity;
 }
References intensity.
Referenced by map::burn_body_part(), map::decay_cosmetic_fields(), do_decay(), map::drop_fields(), editmap::edit_fld(), field_processor_apply_slime(), field_processor_fd_acid(), field_processor_fd_acid_vent(), field_processor_fd_electricity(), field_processor_fd_extinguisher(), field_processor_fd_fungal_haze(), field_processor_fd_fungicidal_gas(), field_processor_fd_shock_vent(), anonymous_namespace{math_parser_diag.cpp}::field_strength_eval(), map::gas_can_spread_to(), map::gas_spread_to(), map::get_field_intensity(), maptile_field_intensity(), mod_field_intensity(), map::monster_in_field(), map::player_in_field(), map::process_fields_in_submap(), map::set_field_intensity(), map::spread_gas(), submap::store(), symbol(), editmap::update_fmenu_entry(), and editmap::update_view_with_help().
get_field_type()
field_type_id field_entry::get_field_type () const
Definition at line 37 of file field.cpp.
 {
     return type;
 }
References type.
Referenced by map::creature_in_field(), map::decay_cosmetic_fields(), map::decay_fields_and_scent(), map::drop_fields(), map::gas_can_spread_to(), map::gas_spread_to(), iuse::gasmask(), get_intensity_level(), Creature::is_dangerous_field(), is_mopsafe(), map::monster_in_field(), map::player_in_field(), map::process_fields_in_submap(), map::spread_gas(), submap::store(), symbol(), and editmap::update_view_with_help().
get_intensity_level()
const field_intensity_level & field_entry::get_intensity_level () const
Definition at line 22 of file field.cpp.
 {
     return get_field_type()->get_intensity_level( intensity - 1 );
 }
References get_field_type(), field_type::get_intensity_level(), and intensity.
Referenced by color(), map::creature_in_field(), field_processor_extra_radiation(), field_processor_monster_spawn(), field_processor_upgrade_intensity(), iuse::gasmask(), map::generate_lightmap(), is_dangerous(), is_mopsafe(), and map::player_in_field().
get_max_field_intensity()
int field_entry::get_max_field_intensity () const
Definition at line 48 of file field.cpp.
 {
     return type.obj().get_max_intensity();
 }
References field_type::get_max_intensity(), int_id< T >::obj(), and type.
Referenced by set_field_intensity().
initialize_decay()
void field_entry::initialize_decay ()
Definition at line 81 of file field.cpp.
 {
     std::exponential_distribution<> d( 1.0f / ( M_LOG2E * to_turns<float>
                                        ( type.obj().half_life ) ) );
     const time_duration decay_delay = time_duration::from_turns( d( rng_get_engine() ) );
     decay_time = calendar::turn - age + decay_delay;
 }
References age, decay_time, time_duration::from_turns(), field_type::half_life, M_LOG2E, int_id< T >::obj(), rng_get_engine(), calendar::turn, and type.
Referenced by do_decay().
is_dangerous()
bool field_entry::is_dangerous () const
Definition at line 27 of file field.cpp.
 {
     return get_intensity_level().dangerous;
 }
References field_intensity_level::dangerous, and get_intensity_level().
Referenced by Character::adjacent_tile(), map::dangerous_field_at(), advanced_inv_area::init(), Creature::is_dangerous_field(), and map::update_pathfinding_cache().
is_field_alive()
bool field_entry::is_field_alive () const inline
Definition at line 72 of file field.h.
{
             return intensity > 0 && is_alive;
         }
References intensity, and is_alive.
Referenced by map::creature_in_field(), gas_can_spread(), map::monster_in_field(), map::player_in_field(), map::process_fields_in_submap(), and map::set_field_intensity().
is_mopsafe()
bool field_entry::is_mopsafe () const
Definition at line 32 of file field.cpp.
 {
     return !get_intensity_level().dangerous || get_field_type()->mopsafe;
 }
References field_intensity_level::dangerous, get_field_type(), get_intensity_level(), and field_type::mopsafe.
Referenced by map::mopsafe_field_at().
mod_field_age()
time_duration field_entry::mod_field_age (const time_duration & mod_age) inline
Adds given value to age.
Returns
New value of age.
Definition at line 58 of file field.h.
{
             return set_field_age( get_field_age() + mod_age );
         }
References get_field_age(), and set_field_age().
Referenced by map::decay_cosmetic_fields(), and field_processor_underwater_dissipation().
mod_field_intensity()
void field_entry::mod_field_intensity (int mod)
Definition at line 65 of file field.cpp.
 {
     set_field_intensity( get_field_intensity() + mod );
 }
References get_field_intensity(), and set_field_intensity().
Referenced by field_processor_fd_extinguisher(), and field_processor_upgrade_intensity().
name()
std::string field_entry::name () const inline
Definition at line 67 of file field.h.
{
             return type.obj().get_name( intensity - 1 );
         }
References field_type::get_name(), intensity, int_id< T >::obj(), and type.
Referenced by colorized_field_description_at(), map::player_in_field(), game::print_fields_info(), and editmap::update_view_with_help().
set_field_age()
time_duration field_entry::set_field_age (const time_duration & new_age)
Sets age to the given value.
Returns
New value of age.
Definition at line 75 of file field.cpp.
 {
     decay_time = time_point();
     return age = new_age;
 }
References age, and decay_time.
Referenced by map::decay_fields_and_scent(), do_decay(), field_processor_fd_acid(), field_processor_fd_acid_vent(), map::gas_spread_to(), mod_field_age(), and map::spread_gas().
set_field_intensity()
int field_entry::set_field_intensity (int new_intensity)
Definition at line 58 of file field.cpp.
 {
     is_alive = new_intensity > 0;
     return intensity = std::max( std::min( new_intensity, get_max_field_intensity() ), 1 );
 }
References get_max_field_intensity(), intensity, is_alive, max(), and min().
Referenced by map::decay_cosmetic_fields(), do_decay(), field_processor_fd_acid(), field_processor_fd_acid_vent(), field_processor_fd_electricity(), field_processor_fd_last_known(), field_processor_fd_shock_vent(), map::gas_spread_to(), mod_field_intensity(), map::monster_in_field(), map::player_in_field(), and map::set_field_intensity().
set_field_type()
field_type_id field_entry::set_field_type (const field_type_id & new_type)
Definition at line 42 of file field.cpp.
 {
     type = new_type;
     return type;
 }
References type.
symbol()
std::string field_entry::symbol () const
Definition at line 12 of file field.cpp.
 {
     return get_field_type()->get_symbol( get_field_intensity() - 1 );
 }
References get_field_intensity(), get_field_type(), and field_type::get_symbol().
Referenced by editmap_hilight::draw(), and editmap::draw_main_ui_overlay().
Member Data Documentation
age
time_duration field_entry::age private
Definition at line 91 of file field.h.
Referenced by do_decay(), get_field_age(), initialize_decay(), and set_field_age().
decay_time
time_point field_entry::decay_time private
Definition at line 93 of file field.h.
Referenced by do_decay(), initialize_decay(), and set_field_age().
intensity
int field_entry::intensity private
Definition at line 89 of file field.h.
Referenced by field_effects(), get_field_intensity(), get_intensity_level(), is_field_alive(), name(), and set_field_intensity().
is_alive
bool field_entry::is_alive private
Definition at line 95 of file field.h.
Referenced by is_field_alive(), and set_field_intensity().
type
field_type_id field_entry::type private
Definition at line 87 of file field.h.
Referenced by do_decay(), field_effects(), gas_can_spread(), get_field_type(), get_max_field_intensity(), initialize_decay(), name(), and set_field_type().
The documentation for this class was generated from the following files:
src/field.h
src/field.cpp