Cataclysm DDA: item_components Class Reference
item_components Class Reference
#include <item_components.h>
Public Types
using type_vector_pair = std::pair< const itype_id, std::vector< item > >
Public Member Functions
comp_iterator begin ()
comp_iterator end ()
const_comp_iterator begin () const
const_comp_iterator end () const
bool empty ()
bool empty () const
void clear ()
std::vector< item > operator[] (itype_id it_id)
item only_item ()
item only_item () const
size_t size () const
void add (item &new_it)
ret_val< item > remove (itype_id it_id)
item get_and_remove_random_entry ()
item_components split (int batch_size, size_t offset, bool is_cooked=false)
void serialize (JsonOut &jsout) const
void deserialize (const JsonValue &jv)
Private Types
using comp_iterator = std::map< itype_id, std::vector< item > >::iterator
using const_comp_iterator = std::map< itype_id, std::vector< item > >::const_iterator
Private Attributes
cata::heap< std::map< itype_id, std::vector< item > > > comps
Detailed Description
Definition at line 19 of file item_components.h.
Member Typedef Documentation
comp_iterator
using item_components::comp_iterator = std::map<itype_id, std::vector<item> >::iterator private
Definition at line 23 of file item_components.h.
const_comp_iterator
using item_components::const_comp_iterator = std::map<itype_id, std::vector<item> >::const_iterator private
Definition at line 24 of file item_components.h.
type_vector_pair
using item_components::type_vector_pair = std::pair<const itype_id, std::vector<item> >
Definition at line 27 of file item_components.h.
Member Function Documentation
add()
void item_components::add (item & new_it)
Definition at line 72 of file item_components.cpp.
 {
     comp_iterator it = comps.find( new_it.typeId() );
     if( it != comps.end() ) {
         if( it->first->count_by_charges() ) {
             it->second.front().charges += new_it.charges;
         } else {
             it->second.push_back( new_it );
         }
     } else {
         comps[new_it.typeId()] = { new_it };
     }
 }
References item::charges, comps, and item::typeId().
Referenced by Character::complete_disassemble(), craft_command::create_in_progress_craft(), Single_item_creator::create_single_without_container(), deserialize(), item::item(), iexamine::mill_finalize(), smoker_finalize(), and iexamine::stook_full().
begin() [1/2]
item_components::comp_iterator item_components::begin ()
Definition at line 13 of file item_components.cpp.
 {
     return comps.begin();
 }
References comps.
begin() [2/2]
item_components::const_comp_iterator item_components::begin () const
Definition at line 21 of file item_components.cpp.
 {
     return comps.begin();
 }
References comps.
clear()
void item_components::clear ()
Definition at line 40 of file item_components.cpp.
 {
     comps.clear();
 }
References comps.
deserialize()
void item_components::deserialize (const JsonValue & jv)
Definition at line 170 of file item_components.cpp.
 {
     comps.clear();
     // read legacy arrays
     if( jv.test_array() ) {
         std::list<item> temp;
         jv.read( temp );
         for( item &it : temp ) {
             add( it );
         }
     } else {
         jv.read( comps );
     }
 }
References add(), comps, JsonValue::read(), temp, and JsonValue::test_array().
empty() [1/2]
bool item_components::empty ()
Definition at line 30 of file item_components.cpp.
 {
     return comps.empty();
 }
References comps.
Referenced by anonymous_namespace{item.cpp}::_stacks_components(), Character::complete_disassemble(), item::component_info(), Character::compute_effective_nutrients(), item::disassembly_info(), item::get_uncraft_components(), and item::handle_craft_failure().
empty() [2/2]
bool item_components::empty () const
Definition at line 35 of file item_components.cpp.
 {
     return comps.empty();
 }
References comps.
end() [1/2]
item_components::comp_iterator item_components::end ()
Definition at line 17 of file item_components.cpp.
 {
     return comps.end();
 }
References comps.
end() [2/2]
item_components::const_comp_iterator item_components::end () const
Definition at line 25 of file item_components.cpp.
 {
     return comps.end();
 }
References comps.
get_and_remove_random_entry()
item item_components::get_and_remove_random_entry ()
Definition at line 100 of file item_components.cpp.
 {
     comp_iterator iter = comps.begin();
     std::advance( iter, rng( 0, comps.size() - 1 ) );
     item ret = random_entry_removed( iter->second );
     if( iter->second.empty() ) {
         comps.erase( iter );
     }
     return ret;
 }
References comps, random_entry_removed(), cata::hash64_detail::ret, and rng().
only_item() [1/2]
item item_components::only_item ()
Definition at line 45 of file item_components.cpp.
 {
     if( comps.size() != 1 || comps.begin()->second.size() != 1 ) {
         debugmsg( "item_components::only_item called but components don't contain exactly one item" );
         return item();
     }
     return *comps.begin()->second.begin();
 }
References comps, debugmsg, and item.
Referenced by Character::can_disassemble(), and Character::complete_disassemble().
only_item() [2/2]
item item_components::only_item () const
Definition at line 54 of file item_components.cpp.
 {
     if( comps.size() != 1 || comps.begin()->second.size() != 1 ) {
         debugmsg( "item_components::only_item called but components don't contain exactly one item" );
         return item();
     }
     return *comps.begin()->second.begin();
 }
References comps, debugmsg, and item.
operator[]()
std::vector< item > item_components::operator[] (itype_id it_id)
Definition at line 8 of file item_components.cpp.
 {
     return comps[it_id];
 }
References comps.
remove()
ret_val< item > item_components::remove (itype_id it_id)
Definition at line 86 of file item_components.cpp.
 {
     comp_iterator it = comps.find( it_id );
     if( it == comps.end() ) {
         return ret_val<item>::make_failure( item() );
     }
     item itm = *it->second.begin();
     it->second.erase( it->second.begin() );
     if( it->second.empty() ) {
         comps.erase( it );
     }
     return ret_val<item>::make_success( itm );
 }
References comps, item, ret_val< T >::make_failure(), and ret_val< T >::make_success().
Referenced by Character::complete_disassemble().
serialize()
void item_components::serialize (JsonOut & jsout) const
Definition at line 165 of file item_components.cpp.
 {
     jsout.write( comps );
 }
References comps, and JsonOut::write().
size()
size_t item_components::size () const
Definition at line 63 of file item_components.cpp.
 {
     size_t ret = 0;
     for( const type_vector_pair &tvp : comps ) {
         ret += tvp.second.size();
     }
     return ret;
 }
References comps, and cata::hash64_detail::ret.
Referenced by item::handle_craft_failure().
split()
item_components item_components::split (int batch_size, size_t offset, bool is_cooked = false)
Definition at line 124 of file item_components.cpp.
 {
     item_components ret;
     for( item_components::type_vector_pair &tvp : comps ) {
         if( tvp.first->count_by_charges() ) {
             if( tvp.second.size() != 1 ) {
                 debugmsg( "count by charges component %s wasn't merged properly, can't distribute components to resulting items",
                           tvp.first.str() );
                 return item_components();
             }
             item new_comp( tvp.second.front() );
             if( new_comp.charges % batch_size != 0 ) {
                 debugmsg( "component %s can't be evenly distributed to resulting items", tvp.first.str() );
                 return item_components();
             }
             adjust_new_comp( new_comp, is_cooked );
             new_comp.charges /= batch_size;
             ret.add( new_comp );
         } else {
             if( tvp.second.size() % batch_size != 0 ) {
                 debugmsg( "component %s can't be evenly distributed to resulting items", tvp.first.str() );
                 return item_components();
             }
             for( size_t i = offset; i < tvp.second.size(); i += batch_size ) {
                 item new_comp( tvp.second[i] );
                 adjust_new_comp( new_comp, is_cooked );
                 ret.add( new_comp );
             }
         }
     }
     return ret;
 }
References adjust_new_comp(), item::charges, comps, debugmsg, and cata::hash64_detail::ret.
Referenced by recipe::create_results(), and set_new_comps().
Member Data Documentation
comps
cata::heap<std::map<itype_id, std::vector<item> > > item_components::comps private
Definition at line 22 of file item_components.h.
Referenced by add(), begin(), clear(), deserialize(), empty(), end(), get_and_remove_random_entry(), only_item(), operator[](), remove(), serialize(), size(), and split().
The documentation for this class was generated from the following files:
src/item_components.h
src/item_components.cpp