Cataclysm DDA: zone_data Class Reference
zone_data Class Reference
These are zones the player can designate.
#include <clzones.h>
Public Member Functions
zone_data ()
zone_data (const std::string &_name, const zone_type_id &_type, const faction_id &_faction, bool _invert, const bool _enabled, const tripoint &_start, const tripoint &_end, const shared_ptr_fast< zone_options > &_options=nullptr, bool personal=false, bool _is_displayed=false)
bool set_name ()
bool set_type ()
void set_position (const std::pair< tripoint, tripoint > &position, bool manual=true, bool update_avatar=true, bool skip_cache_update=false)
void set_enabled (bool enabled_arg)
void set_temporary_disabled (bool enabled_arg)
void refresh_display () const
void toggle_display ()
void set_is_vehicle (bool is_vehicle_arg)
std::string get_name () const
const faction_id & get_faction () const
std::string get_type_hash () const
const zone_type_id & get_type () const
bool get_invert () const
bool get_enabled () const
bool get_temporarily_disabled () const
bool get_is_displayed () const
bool get_is_vehicle () const
bool get_is_personal () const
tripoint_abs_ms get_start_point () const
tripoint_abs_ms get_end_point () const
void update_cached_shift (const tripoint_abs_ms &player_loc)
tripoint_abs_ms get_center_point () const
bool has_options () const
const zone_options & get_options () const
zone_options & get_options ()
bool has_inside (const tripoint_abs_ms &p) const
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
Static Public Member Functions
static std::string make_type_hash (const zone_type_id &_type, const faction_id &_fac)
static zone_type_id unhash_type (const std::string_view hash_type)
static faction_id unhash_fac (const std::string_view hash_type)
Private Attributes
std::string name
zone_type_id type
faction_id faction
bool invert
bool enabled
bool temporarily_disabled
bool is_vehicle
tripoint start
tripoint end
bool is_personal
tripoint_abs_ms cached_shift
shared_ptr_fast< zone_options > options
bool is_displayed
Detailed Description
These are zones the player can designate.
Definition at line 348 of file clzones.h.
Constructor & Destructor Documentation
zone_data() [1/2]
zone_data::zone_data () inline
Definition at line 369 of file clzones.h.
                     {
             type = zone_type_id( "" );
             invert = false;
             enabled = false;
             temporarily_disabled = false;
             is_vehicle = false;
             is_personal = false;
             start = tripoint_zero;
             end = tripoint_zero;
             cached_shift = {};
             options = nullptr;
             is_displayed = false;
         }
References cached_shift, enabled, end, invert, is_displayed, is_personal, is_vehicle, options, start, temporarily_disabled, tripoint_zero, type, and zone_type_id.
zone_data() [2/2]
zone_data::zone_data (const std::string & _name, const zone_type_id & _type, const faction_id & _faction, bool _invert, const bool _enabled, const tripoint & _start, const tripoint & _end, const shared_ptr_fast< zone_options > & _options = nullptr, bool personal = false, bool _is_displayed = false) inline
Definition at line 383 of file clzones.h.
{
             name = _name;
             type = _type;
             faction = _faction;
             invert = _invert;
             enabled = _enabled;
             is_vehicle = false;
             is_personal = personal;
             start = _start;
             end = _end;
             is_displayed = _is_displayed;
             // ensure that supplied options is of correct class
             if( _options == nullptr || !zone_options::is_valid( type, *_options ) ) {
                 options = zone_options::create( type );
             } else {
                 options = _options;
             }
         }
References zone_options::create(), enabled, end, invert, is_displayed, is_personal, zone_options::is_valid(), is_vehicle, name, options, start, and type.
Member Function Documentation
deserialize()
void zone_data::deserialize (const JsonObject & data)
Definition at line 1627 of file clzones.cpp.
 {
     data.allow_omitted_members();
     data.read( "name", name );
     // handle legacy zone types
     zone_type_id temp_type;
     data.read( "type", temp_type );
     const auto find_result = legacy_zone_types.find( temp_type.str() );
     if( find_result != legacy_zone_types.end() ) {
         type =  find_result->second;
     } else {
         type = temp_type;
     }
     if( data.has_member( "faction" ) ) {
         data.read( "faction", faction );
     } else {
         faction = your_fac;
     }
     data.read( "invert", invert );
     data.read( "enabled", enabled );
     //Legacy support
     if( data.has_member( "is_vehicle" ) ) {
         data.read( "is_vehicle", is_vehicle );
     } else {
         is_vehicle = false;
     }
     if( data.has_member( "is_personal" ) ) {
         data.read( "is_personal", is_personal );
         data.read( "cached_shift", cached_shift );
     } else {
         is_personal = false;
         cached_shift = tripoint_abs_ms{};
     }
     //Legacy support
     if( data.has_member( "start_x" ) ) {
         tripoint s;
         tripoint e;
         data.read( "start_x", s.x );
         data.read( "start_y", s.y );
         data.read( "start_z", s.z );
         data.read( "end_x", e.x );
         data.read( "end_y", e.y );
         data.read( "end_z", e.z );
         start = s;
         end = e;
     } else {
         data.read( "start", start );
         data.read( "end", end );
     }
     if( data.has_member( "is_displayed" ) ) {
         data.read( "is_displayed", is_displayed );
     } else {
         is_displayed = false;
     }
     auto new_options = zone_options::create( type );
     new_options->deserialize( data );
     options = new_options;
 }
References JsonObject::allow_omitted_members(), cached_shift, zone_options::create(), enabled, end, JsonObject::has_member(), invert, is_displayed, is_personal, is_vehicle, legacy_zone_types, name, options, JsonObject::read(), start, string_id< T >::str(), type, tripoint::x, tripoint::y, your_fac(), and tripoint::z.
get_center_point()
tripoint_abs_ms zone_data::get_center_point () const
Definition at line 828 of file clzones.cpp.
 {
     return midpoint( get_start_point(), get_end_point() );
 }
References get_end_point(), get_start_point(), and midpoint().
Referenced by overmap_ui::draw_ascii(), start_location::place_player(), and game::zones_manager().
get_enabled()
bool zone_data::get_enabled () const inline
Definition at line 454 of file clzones.h.
{
             return enabled;
         }
References enabled.
Referenced by loot(), and game::zones_manager().
get_end_point()
tripoint_abs_ms zone_data::get_end_point () const inline
Definition at line 477 of file clzones.h.
{
             if( is_personal ) {
                 return end + cached_shift;
             }
             return tripoint_abs_ms{ end };
         }
References cached_shift, end, and is_personal.
Referenced by anonymous_namespace{clzones.cpp}::_rotate_zone(), get_center_point(), refresh_display(), and game::zones_manager().
get_faction()
const faction_id& zone_data::get_faction () const inline
Definition at line 442 of file clzones.h.
{
             return faction;
         }
References faction.
Referenced by zone_manager::get_bottom_zone().
get_invert()
bool zone_data::get_invert () const inline
Definition at line 451 of file clzones.h.
{
             return invert;
         }
References invert.
get_is_displayed()
bool zone_data::get_is_displayed () const inline
Definition at line 461 of file clzones.h.
{
             return is_displayed;
         }
References is_displayed.
Referenced by zone_manager::remove().
get_is_personal()
bool zone_data::get_is_personal () const inline
Definition at line 468 of file clzones.h.
{
             return is_personal;
         }
References is_personal.
Referenced by loot(), and game::zones_manager().
get_is_vehicle()
bool zone_data::get_is_vehicle () const inline
Definition at line 465 of file clzones.h.
{
             return is_vehicle;
         }
References is_vehicle.
Referenced by zone_manager::zone_edited(), and game::zones_manager().
get_name()
std::string zone_data::get_name () const inline
Definition at line 439 of file clzones.h.
{
             return name;
         }
References name.
Referenced by overmap_ui::draw_ascii(), generic_multi_activity_check_requirement(), trade_ui::trade_ui(), and game::zones_manager().
get_options() [1/2]
zone_options& zone_data::get_options () inline
Definition at line 493 of file clzones.h.
{
             return *options;
         }
References options.
get_options() [2/2]
const zone_options& zone_data::get_options () const inline
Definition at line 490 of file clzones.h.
{
             return *options;
         }
References options.
Referenced by generic_multi_activity_check_requirement(), generic_multi_activity_do(), and game::zones_manager().
get_start_point()
tripoint_abs_ms zone_data::get_start_point () const inline
Definition at line 471 of file clzones.h.
{
             if( is_personal ) {
                 return start + cached_shift;
             }
             return tripoint_abs_ms{ start };
         }
References cached_shift, is_personal, and start.
Referenced by anonymous_namespace{clzones.cpp}::_rotate_zone(), map::deregister_vehicle_zone(), get_center_point(), refresh_display(), and game::zones_manager().
get_temporarily_disabled()
bool zone_data::get_temporarily_disabled () const inline
Definition at line 457 of file clzones.h.
{
             return temporarily_disabled;
         }
References temporarily_disabled.
get_type()
const zone_type_id& zone_data::get_type () const inline
Definition at line 448 of file clzones.h.
{
             return type;
         }
References type.
Referenced by get_zone_for_act(), start_location::place_player(), refresh_display(), and game::zones_manager().
get_type_hash()
std::string zone_data::get_type_hash () const inline
Definition at line 445 of file clzones.h.
{
             return make_type_hash( type, faction );
         }
References make_type_hash(), and type.
has_inside()
bool zone_data::has_inside (const tripoint_abs_ms & p) const inline
Definition at line 500 of file clzones.h.
{
             // if it is personal then the zone is local
             if( is_personal ) {
                 return inclusive_cuboid<tripoint_abs_ms>(
                            start + cached_shift, end + cached_shift ).contains( p );
             }
             return inclusive_cuboid<tripoint>( start, end ).contains( p.raw() );
         }
References cached_shift, inclusive_cuboid< Tripoint, >::contains(), end, is_personal, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and start.
Referenced by zone_manager::get_bottom_zone().
has_options()
bool zone_data::has_options () const inline
Definition at line 487 of file clzones.h.
{
             return options->has_options();
         }
References options.
Referenced by game::zones_manager().
make_type_hash()
static std::string zone_data::make_type_hash (const zone_type_id & _type, const faction_id & _fac) inline static
Definition at line 422 of file clzones.h.
{
             return _type.c_str() + type_fac_hash_str + _fac.c_str();
         }
References string_id< T >::c_str(), and type_fac_hash_str.
Referenced by zone_manager::get_point_set(), get_type_hash(), zone_manager::get_vzone_set(), and zone_manager::has_defined().
refresh_display()
void zone_data::refresh_display () const
Definition at line 715 of file clzones.cpp.
 {
     if( this->is_vehicle ) {
         popup( colorize( _( "Zones tied to vehicles cannot be displayed" ), c_magenta ) );
         return;
     }
     std::unique_ptr<tinymap> p_update_tmap = std::make_unique<tinymap>();
     tinymap &update_tmap = *p_update_tmap;
     std::pair<tripoint_abs_ms, tripoint_abs_ms> bounds = get_corners( get_start_point(),
             get_end_point() );
     const tripoint_abs_ms start = bounds.first;
     const tripoint_abs_ms end = bounds.second;
     const tripoint_abs_omt omt_start_pos = coords::project_to<coords::omt>( start );
     const tripoint_abs_omt omt_end_pos = coords::project_to<coords::omt>( end );
     const tripoint_omt_ms start_remainder = tripoint_omt_ms( ( get_start_point() - coords::project_to
                                             < coords::ms >
                                             ( omt_start_pos ) ).raw() );
     const tripoint_omt_ms end_remainder = tripoint_omt_ms( ( get_end_point() - coords::project_to
                                           < coords::ms >
                                           ( omt_end_pos ) ).raw() );
     zone_type_id type = this->get_type();
     field_type_str_id field = fd_null;
     static const std::vector<zone_type> &all_zone_types = zone_type::get_all();
     for( const zone_type &zone : all_zone_types ) {
         if( zone.id == type ) {
             field = zone.get_field();
             break;
         }
     }
     if( field != fd_null ) {
         tripoint_omt_ms start_ms;
         tripoint_omt_ms end_ms;
         for( int i = omt_start_pos.x(); i <= omt_end_pos.x(); i++ ) {
             for( int k = omt_start_pos.y(); k <= omt_end_pos.y(); k++ ) {
                 //  We assume the Z coordinate will remain fixed
                 update_tmap.load( tripoint_abs_omt{ i, k, omt_start_pos.z() }, false );
                 start_ms = tripoint_omt_ms( i > omt_start_pos.x() ? 0 : start_remainder.x(),
                                             k > omt_start_pos.y() ? 0 : start_remainder.y(), start_remainder.z() );
                 end_ms = tripoint_omt_ms( i < omt_end_pos.x() ? SEEX * 2 - 1 : end_remainder.x(),
                                           k < omt_end_pos.y() ? SEEY * 2 - 1 : end_remainder.y(), end_remainder.z() );
                 for( tripoint_omt_ms pt : update_tmap.points_in_rectangle( start_ms, end_ms ) ) {
                     if( is_displayed ) {
                         update_tmap.add_field( pt, field, 1, time_duration::from_turns( 0 ), false );
                     } else {
                         update_tmap.delete_field( pt, field );
                     }
                 }
             }
         }
     }
 }
References _, tinymap::add_field(), c_magenta, colorize(), tinymap::delete_field(), end, fd_null, time_duration::from_turns(), zone_type::get_all(), get_corners(), get_end_point(), get_start_point(), get_type(), is_displayed, is_vehicle, tinymap::load(), coords::ms, tinymap::points_in_rectangle(), popup(), coords::project_to(), SEEX, SEEY, start, type, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by toggle_display().
serialize()
void zone_data::serialize (JsonOut & json) const
Definition at line 1609 of file clzones.cpp.
 {
     json.start_object();
     json.member( "name", name );
     json.member( "type", type );
     json.member( "faction", faction );
     json.member( "invert", invert );
     json.member( "enabled", enabled );
     json.member( "is_vehicle", is_vehicle );
     json.member( "is_personal", is_personal );
     json.member( "cached_shift", cached_shift );
     json.member( "start", start );
     json.member( "end", end );
     json.member( "is_displayed", is_displayed );
     options->serialize( json );
     json.end_object();
 }
References cached_shift, enabled, end, JsonOut::end_object(), invert, is_displayed, is_personal, is_vehicle, JsonOut::member(), name, options, start, JsonOut::start_object(), and type.
set_enabled()
void zone_data::set_enabled (bool enabled_arg)
Definition at line 693 of file clzones.cpp.
 {
     zone_manager::get_manager().zone_edited( *this );
     enabled = enabled_arg;
 }
References enabled, zone_manager::get_manager(), and zone_manager::zone_edited().
Referenced by loot(), and game::zones_manager().
set_is_vehicle()
void zone_data::set_is_vehicle (bool is_vehicle_arg)
Definition at line 823 of file clzones.cpp.
 {
     is_vehicle = is_vehicle_arg;
 }
References is_vehicle.
Referenced by zone_manager::create_vehicle_loot_zone().
set_name()
bool zone_data::set_name ()
Definition at line 633 of file clzones.cpp.
 {
     const auto maybe_name = zone_manager::get_manager().query_name( name );
     if( maybe_name.has_value() ) {
         auto new_name = maybe_name.value();
         if( new_name.empty() ) {
             new_name = _( "<no name>" );
         }
         if( name != new_name ) {
             zone_manager::get_manager().zone_edited( *this );
             name = new_name;
             return true;
         }
     }
     return false;
 }
References _, zone_manager::get_manager(), name, zone_manager::query_name(), and zone_manager::zone_edited().
Referenced by game::zones_manager().
set_position()
void zone_data::set_position (const std::pair< tripoint, tripoint > & position, bool manual = true, bool update_avatar = true, bool skip_cache_update = false)
Definition at line 668 of file clzones.cpp.
 {
     if( is_vehicle && manual ) {
         debugmsg( "Tried moving a lootzone bound to a vehicle part" );
         return;
     }
     bool displayed = is_displayed;
     if( displayed ) {
         toggle_display();
     }
     start = position.first;
     end = position.second;
     if( displayed ) {
         toggle_display();
     }
     if( !skip_cache_update ) {
         zone_manager::get_manager().cache_data( update_avatar );
     }
 }
References zone_manager::cache_data(), debugmsg, end, zone_manager::get_manager(), is_displayed, is_vehicle, manual, start, and toggle_display().
Referenced by anonymous_namespace{clzones.cpp}::_rotate_zone(), vehicle::refresh_zones(), and game::zones_manager().
set_temporary_disabled()
void zone_data::set_temporary_disabled (bool enabled_arg)
Definition at line 699 of file clzones.cpp.
 {
     temporarily_disabled = enabled_arg;
 }
References temporarily_disabled.
Referenced by loot().
set_type()
bool zone_data::set_type ()
Definition at line 650 of file clzones.cpp.
 {
     const auto maybe_type = zone_manager::get_manager().query_type( is_personal );
     if( maybe_type.has_value() && maybe_type.value() != type ) {
         shared_ptr_fast<zone_options> new_options = zone_options::create( maybe_type.value() );
         if( new_options->query_at_creation() ) {
             zone_manager::get_manager().zone_edited( *this );
             type = maybe_type.value();
             options = new_options;
             zone_manager::get_manager().cache_data();
             return true;
         }
     }
     // False positive from memory leak detection on shared_ptr_fast
     // NOLINTNEXTLINE(clang-analyzer-cplusplus.NewDeleteLeaks)
     return false;
 }
References zone_manager::cache_data(), zone_options::create(), zone_manager::get_manager(), is_personal, options, zone_manager::query_type(), type, and zone_manager::zone_edited().
Referenced by game::zones_manager().
toggle_display()
void zone_data::toggle_display ()
Definition at line 776 of file clzones.cpp.
 {
     if( this->is_vehicle ) {
         popup( colorize( _( "Zones tied to vehicles cannot be displayed" ), c_magenta ) );
         return;
     }
     is_displayed = !is_displayed;
     this->refresh_display();
     // Take care of the situation where parts of overlapping zones were erased by the toggling.
     if( !is_displayed ) {
         const point_abs_ms start = point_abs_ms( std::min( this->start.x, this->end.x ),
                                    std::min( this->start.y, this->end.y ) );
         const point_abs_ms end = point_abs_ms( std::max( this->start.x, this->end.x ),
                                                std::max( this->start.y, this->end.y ) );
         const inclusive_rectangle<point_abs_ms> zone_rectangle( start, end );
         for( zone_manager::ref_zone_data zone : zone_manager::get_manager().get_zones() ) {
             // Assumes zones are a single Z level only. Also, inclusive_cuboid doesn't have an overlap function...
             if( zone.get().get_is_displayed() && zone.get().get_type() == this->get_type() &&
                 this->start.z == zone.get().get_start_point().z() ) {
                 const point_abs_ms candidate_begin = zone.get().get_start_point().xy();
                 const point_abs_ms candidate_stop = zone.get().get_end_point().xy();
                 const point_abs_ms candidate_start = point_abs_ms( std::min( candidate_begin.x(),
                                                      candidate_stop.x() ),
                                                      std::min( candidate_begin.y(), candidate_stop.y() ) );
                 const point_abs_ms candidate_end = point_abs_ms( std::max( candidate_begin.x(),
                                                    candidate_stop.x() ),
                                                    std::max( candidate_begin.y(), candidate_stop.y() ) );
                 const inclusive_rectangle<point_abs_ms> candidate_rectangle( candidate_start, candidate_end );
                 if( zone_rectangle.overlaps( candidate_rectangle ) ) {
                     zone.get().refresh_display();
                 }
             }
         }
     }
 }
References _, c_magenta, colorize(), end, zone_manager::get_manager(), is_displayed, is_vehicle, max(), min(), inclusive_rectangle< Point, >::overlaps(), popup(), refresh_display(), start, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by zone_manager::remove(), and set_position().
unhash_fac()
static faction_id zone_data::unhash_fac (const std::string_view hash_type) inline static
Definition at line 432 of file clzones.h.
{
             size_t start = hash_type.find( type_fac_hash_str ) + type_fac_hash_str.size();
             if( start != std::string::npos ) {
                 return faction_id( hash_type.substr( start ) );
             }
             return faction_id( "" );
         }
References faction_id, start, and type_fac_hash_str.
Referenced by zone_manager::get_point_set_loot().
unhash_type()
static zone_type_id zone_data::unhash_type (const std::string_view hash_type) inline static
Definition at line 425 of file clzones.h.
{
             size_t end = hash_type.find( type_fac_hash_str );
             if( end != std::string::npos && end < hash_type.size() ) {
                 return zone_type_id( hash_type.substr( 0, end ) );
             }
             return zone_type_id( "" );
         }
References end, type_fac_hash_str, and zone_type_id.
Referenced by zone_manager::get_point_set_loot().
update_cached_shift()
void zone_data::update_cached_shift (const tripoint_abs_ms & player_loc) inline
Definition at line 483 of file clzones.h.
{
             cached_shift = player_loc;
         }
References cached_shift.
Member Data Documentation
cached_shift
tripoint_abs_ms zone_data::cached_shift private
Definition at line 364 of file clzones.h.
Referenced by deserialize(), get_end_point(), get_start_point(), has_inside(), serialize(), update_cached_shift(), and zone_data().
enabled
bool zone_data::enabled private
Definition at line 355 of file clzones.h.
Referenced by deserialize(), get_enabled(), serialize(), set_enabled(), and zone_data().
end
tripoint zone_data::end private
Definition at line 360 of file clzones.h.
Referenced by deserialize(), get_end_point(), has_inside(), refresh_display(), serialize(), set_position(), toggle_display(), unhash_type(), and zone_data().
faction
faction_id zone_data::faction private
Definition at line 353 of file clzones.h.
Referenced by get_faction().
invert
bool zone_data::invert private
Definition at line 354 of file clzones.h.
Referenced by deserialize(), get_invert(), serialize(), and zone_data().
is_displayed
bool zone_data::is_displayed private
Definition at line 366 of file clzones.h.
Referenced by deserialize(), get_is_displayed(), refresh_display(), serialize(), set_position(), toggle_display(), and zone_data().
is_personal
bool zone_data::is_personal private
Definition at line 362 of file clzones.h.
Referenced by deserialize(), get_end_point(), get_is_personal(), get_start_point(), has_inside(), serialize(), set_type(), and zone_data().
is_vehicle
bool zone_data::is_vehicle private
Definition at line 358 of file clzones.h.
Referenced by deserialize(), get_is_vehicle(), refresh_display(), serialize(), set_is_vehicle(), set_position(), toggle_display(), and zone_data().
name
std::string zone_data::name private
Definition at line 351 of file clzones.h.
Referenced by deserialize(), get_name(), serialize(), set_name(), and zone_data().
options
shared_ptr_fast<zone_options> zone_data::options private
Definition at line 365 of file clzones.h.
Referenced by deserialize(), get_options(), has_options(), serialize(), set_type(), and zone_data().
start
tripoint zone_data::start private
Definition at line 359 of file clzones.h.
Referenced by deserialize(), get_start_point(), has_inside(), refresh_display(), serialize(), set_position(), toggle_display(), unhash_fac(), and zone_data().
temporarily_disabled
bool zone_data::temporarily_disabled private
Definition at line 357 of file clzones.h.
Referenced by get_temporarily_disabled(), set_temporary_disabled(), and zone_data().
type
zone_type_id zone_data::type private
Definition at line 352 of file clzones.h.
Referenced by deserialize(), get_type(), get_type_hash(), refresh_display(), serialize(), set_type(), and zone_data().
The documentation for this class was generated from the following files:
src/clzones.h
src/clzones.cpp