Cataclysm DDA: leap_actor Class Reference
leap_actor Class Reference
#include <mattack_actors.h>
Public Member Functions
leap_actor ()=default
~leap_actor () override=default
void load_internal (const JsonObject &obj, const std::string &src) override
bool call (monster &) const override
std::unique_ptr< mattack_actor > clone () const override
Public Member Functions inherited from mattack_actor
mattack_actor (const mattack_id &new_id)
void load (const JsonObject &jo, const std::string &src)
virtual ~mattack_actor ()=default
Public Attributes
float max_range = 0.0f
float min_range = 0.0f
bool allow_no_target = false
bool prefer_leap = false
bool random_leap = false
bool ignore_dest_terrain = false
bool ignore_dest_danger = false
int move_cost = 0
float min_consider_range = 0.0f
float max_consider_range = 0.0f
std::vector< mon_effect_data > self_effects
translation message
Public Attributes inherited from mattack_actor
mattack_id id
bool was_loaded = false
int cooldown = 0
int attack_chance = 100
std::function< bool(dialogue &)> condition
bool has_condition = false
Additional Inherited Members
Protected Member Functions inherited from mattack_actor
mattack_actor ()=default
Detailed Description
Definition at line 24 of file mattack_actors.h.
Constructor & Destructor Documentation
leap_actor()
leap_actor::leap_actor () default
~leap_actor()
leap_actor::~leap_actor () override default
Member Function Documentation
call()
bool leap_actor::call (monster & z) const override virtual
Implements mattack_actor.
Definition at line 110 of file mattack_actors.cpp.
 {
     if( !z.has_dest() || !z.can_act() || !z.move_effects( false ) ) {
         add_msg_debug( debugmode::DF_MATTACK, "Monster has no destination or can't act" );
         return false;
     }
     if( has_condition ) {
         dialogue d( get_talker_for( &z ), nullptr );
         if( !condition( d ) ) {
             add_msg_debug( debugmode::DF_MATTACK, "Attack conditionals failed" );
             return false;
         }
     }
     std::vector<tripoint> options;
     const tripoint_abs_ms target_abs = z.get_dest();
     // Calculate distance to target
     const float best_float = rl_dist( z.get_location(), target_abs );
     add_msg_debug( debugmode::DF_MATTACK, "Target distance %.1f", best_float );
     if( best_float < min_consider_range || best_float > max_consider_range ) {
         add_msg_debug( debugmode::DF_MATTACK, "Best float outside of considered range" );
         return false;
     }
     // We wanted the float for range check
     // int here will make the jumps more random
     int best = std::numeric_limits<int>::max();
     if( !allow_no_target && z.attack_target() == nullptr ) {
         add_msg_debug( debugmode::DF_MATTACK, "Leaping without a target disabled" );
         return false;
     }
     map &here = get_map();
     const tripoint target = here.getlocal( target_abs );
     add_msg_debug( debugmode::DF_MATTACK, "Target at coordinates %d,%d,%d",
                    target.x, target.y, target.z );
     std::multimap<int, tripoint> candidates;
     for( const tripoint &candidate : here.points_in_radius( z.pos(), max_range ) ) {
         if( candidate == z.pos() ) {
             add_msg_debug( debugmode::DF_MATTACK, "Monster at coordinates %d,%d,%d",
                            candidate.x, candidate.y, candidate.z );
             continue;
         }
         float leap_dist = trigdist ? trig_dist( z.pos(), candidate ) :
                           square_dist( z.pos(), candidate );
         add_msg_debug( debugmode::DF_MATTACK,
                        "Candidate coordinates %d,%d,%d, distance %.1f, min range %.1f, max range %.1f",
                        candidate.x, candidate.y, candidate.z, leap_dist, min_range, max_range );
         if( leap_dist > max_range || leap_dist < min_range ) {
             add_msg_debug( debugmode::DF_MATTACK,
                            "Candidate outside of allowed range, discarded" );
             continue;
         }
         int candidate_dist = rl_dist( candidate, target );
         if( candidate_dist >= best_float && !( prefer_leap || random_leap ) ) {
             add_msg_debug( debugmode::DF_MATTACK,
                            "Candidate farther from target than optimal path, discarded" );
             continue;
         }
         if( !ignore_dest_terrain && !z.will_move_to( candidate ) ) {
             add_msg_debug( debugmode::DF_MATTACK,
                            "Candidate place it can't enter, discarded" );
             continue;
         }
         if( !ignore_dest_danger && !z.know_danger_at( candidate ) ) {
             add_msg_debug( debugmode::DF_MATTACK,
                            "Candidate with dangerous conditions, discarded" );
             continue;
         }
         candidates.emplace( candidate_dist, candidate );
     }
     for( const auto &candidate : candidates ) {
         const int &cur_dist = candidate.first;
         const tripoint &dest = candidate.second;
         if( cur_dist > best && !random_leap ) {
             add_msg_debug( debugmode::DF_MATTACK,
                            "Distance %d larger than previous best %d, candidate discarded", cur_dist, best );
             break;
         }
         if( !z.sees( dest ) ) {
             add_msg_debug( debugmode::DF_MATTACK, "Can't see destination, candidate discarded" );
             continue;
         }
         if( !g->is_empty( dest ) ) {
             continue;
         }
         bool blocked_path = false;
         // check if monster has a clear path to the proposed point
         std::vector<tripoint> line = here.find_clear_path( z.pos(), dest );
         for( tripoint &i : line ) {
             if( here.impassable( i ) ) {
                 add_msg_debug( debugmode::DF_MATTACK, "Path blocked, candidate discarded" );
                 blocked_path = true;
                 break;
             } else if( here.has_flag_ter( ter_furn_flag::TFLAG_SMALL_PASSAGE, i ) &&
                        z.get_size() > creature_size::medium ) {
                 add_msg_debug( debugmode::DF_MATTACK, "Small passage can't pass, candidate discarded" );
                 blocked_path = true;
                 break;
             }
         }
         if( blocked_path ) {
             continue;
         }
         options.push_back( dest );
         best = cur_dist;
     }
     if( options.empty() ) {
         add_msg_debug( debugmode::DF_MATTACK, "No acceptable leap candidates" );
         return false;    // Nowhere to leap!
     }
     z.mod_moves( -move_cost );
     viewer &player_view = get_player_view();
     const tripoint chosen = random_entry( options );
     bool seen = player_view.sees( z ); // We can see them jump...
     z.setpos( chosen );
     seen |= player_view.sees( z ); // ... or we can see them land
     if( seen && get_option<bool>( "LOG_MONSTER_MOVEMENT" ) ) {
         add_msg( message, z.name() );
     }
     for( const mon_effect_data &eff : self_effects ) {
         if( x_in_y( eff.chance, 100 ) ) {
             z.add_effect( eff.id, time_duration::from_turns( rng( eff.duration.first, eff.duration.second ) ),
                           eff.permanent,
                           rng( eff.intensity.first, eff.intensity.second ) );
         }
     }
     return true;
 }
References Creature::add_effect(), add_msg(), add_msg_debug, allow_no_target, monster::attack_target(), monster::can_act(), mattack_actor::condition, debugmode::DF_MATTACK, cata_path::empty(), map::find_clear_path(), time_duration::from_turns(), g, monster::get_dest(), Creature::get_location(), get_map(), get_player_view(), monster::get_size(), get_talker_for(), map::getlocal(), mattack_actor::has_condition, monster::has_dest(), map::has_flag_ter(), ignore_dest_danger, ignore_dest_terrain, map::impassable(), monster::know_danger_at(), line, max(), max_consider_range, max_range, medium, message, min_range, Creature::mod_moves(), move_cost, monster::move_effects(), monster::name(), PATH_INFO::options(), map::points_in_radius(), Creature::pos(), prefer_leap, random_entry(), random_leap, rl_dist(), rng(), Creature::sees(), viewer::sees(), self_effects, Creature::setpos(), square_dist(), TFLAG_SMALL_PASSAGE, trig_dist(), trigdist, monster::will_move_to(), tripoint::x, x_in_y(), tripoint::y, and tripoint::z.
clone()
std::unique_ptr< mattack_actor > leap_actor::clone () const override virtual
Implements mattack_actor.
Definition at line 105 of file mattack_actors.cpp.
 {
     return std::make_unique<leap_actor>( *this );
 }
load_internal()
void leap_actor::load_internal (const JsonObject & obj, const std::string & src) override virtual
Implements mattack_actor.
Definition at line 73 of file mattack_actors.cpp.
 {
     // Mandatory:
     max_range = obj.get_float( "max_range" );
     // Optional:
     min_range = obj.get_float( "min_range", 1.0f );
     allow_no_target = obj.get_bool( "allow_no_target", false );
     optional( obj, was_loaded, "attack_chance", attack_chance, 100 );
     optional( obj, was_loaded, "prefer_leap", prefer_leap, false );
     optional( obj, was_loaded, "random_leap", random_leap, false );
     optional( obj, was_loaded, "ignore_dest_terrain", ignore_dest_terrain, false );
     optional( obj, was_loaded, "ignore_dest_danger", ignore_dest_danger, false );
     move_cost = obj.get_int( "move_cost", 150 );
     min_consider_range = obj.get_float( "min_consider_range", 0.0f );
     max_consider_range = obj.get_float( "max_consider_range", 200.0f );
     optional( obj, was_loaded, "message", message,
               to_translation( "The %s leaps!" ) );
     if( obj.has_member( "condition" ) ) {
         read_condition( obj, "condition", condition, false );
         has_condition = true;
     }
     if( obj.has_array( "self_effects" ) ) {
         for( JsonObject eff : obj.get_array( "self_effects" ) ) {
             mon_effect_data effect;
             effect.load( eff );
             self_effects.push_back( std::move( effect ) );
         }
     }
 }
References allow_no_target, mattack_actor::attack_chance, mattack_actor::condition, JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::has_array(), mattack_actor::has_condition, JsonObject::has_member(), ignore_dest_danger, ignore_dest_terrain, max_consider_range, max_range, message, min_consider_range, min_range, move_cost, optional(), prefer_leap, random_leap, read_condition(), self_effects, to_translation(), and mattack_actor::was_loaded.
Member Data Documentation
allow_no_target
bool leap_actor::allow_no_target = false
Definition at line 31 of file mattack_actors.h.
Referenced by call(), and load_internal().
ignore_dest_danger
bool leap_actor::ignore_dest_danger = false
Definition at line 41 of file mattack_actors.h.
Referenced by call(), and load_internal().
ignore_dest_terrain
bool leap_actor::ignore_dest_terrain = false
Definition at line 38 of file mattack_actors.h.
Referenced by call(), and load_internal().
max_consider_range
float leap_actor::max_consider_range = 0.0f
Definition at line 46 of file mattack_actors.h.
Referenced by call(), and load_internal().
max_range
float leap_actor::max_range = 0.0f
Definition at line 27 of file mattack_actors.h.
Referenced by call(), and load_internal().
message
translation leap_actor::message
Definition at line 50 of file mattack_actors.h.
Referenced by call(), and load_internal().
min_consider_range
float leap_actor::min_consider_range = 0.0f
Definition at line 44 of file mattack_actors.h.
Referenced by load_internal().
min_range
float leap_actor::min_range = 0.0f
Definition at line 29 of file mattack_actors.h.
Referenced by call(), and load_internal().
move_cost
int leap_actor::move_cost = 0
Definition at line 42 of file mattack_actors.h.
Referenced by call(), and load_internal().
prefer_leap
bool leap_actor::prefer_leap = false
Definition at line 33 of file mattack_actors.h.
Referenced by call(), and load_internal().
random_leap
bool leap_actor::random_leap = false
Definition at line 35 of file mattack_actors.h.
Referenced by call(), and load_internal().
self_effects
std::vector<mon_effect_data> leap_actor::self_effects
Definition at line 48 of file mattack_actors.h.
Referenced by call(), and load_internal().
The documentation for this class was generated from the following files:
src/mattack_actors.h
src/mattack_actors.cpp