Cataclysm DDA: skill_boost Class Reference
skill_boost Class Reference
#include <skill_boost.h>
Public Member Functions
skill_boost ()=default
std::string stat () const
const std::vector< std::string > & skills () const
float calc_bonus (int skill_total) const
Static Public Member Functions
static void load_boost (const JsonObject &jo, const std::string &src)
static void reset ()
static const std::vector< skill_boost > & get_all ()
static std::optional< skill_boost > get (const std::string &stat_str)
Private Member Functions
void load (const JsonObject &jo, std::string_view src)
Private Attributes
string_id< skill_boost > id
std::vector< std::pair< string_id< skill_boost >, mod_id > > src
bool was_loaded = false
std::vector< std::string > _skills
int _offset = 0
float _power = 0.0f
Friends
class generic_factory< skill_boost >
struct mod_tracker
Detailed Description
Definition at line 16 of file skill_boost.h.
Constructor & Destructor Documentation
skill_boost()
skill_boost::skill_boost () default
Member Function Documentation
calc_bonus()
float skill_boost::calc_bonus (int skill_total) const
Definition at line 59 of file skill_boost.cpp.
 {
     if( skill_total + _offset <= 0 ) {
         return 0.0;
     }
     return std::max( 0.0, std::floor( std::pow( skill_total + _offset, _power ) ) );
 }
References _offset, _power, floor(), and max().
get()
std::optional< skill_boost > skill_boost::get (const std::string & stat_str) static
Definition at line 22 of file skill_boost.cpp.
 {
     for( const skill_boost &boost : get_all() ) {
         if( boost.stat() == stat_str ) {
             return std::optional<skill_boost>( boost );
         }
     }
     return std::nullopt;
 }
References get_all(), and stat_str.
Referenced by Character::recalc_hp().
get_all()
const std::vector< skill_boost > & skill_boost::get_all () static
Definition at line 17 of file skill_boost.cpp.
 {
     return all_skill_boosts.get_all();
 }
References anonymous_namespace{skill_boost.cpp}::all_skill_boosts.
Referenced by Character::apply_skill_boost(), and get().
load()
void skill_boost::load (const JsonObject & jo, std::string_view src) private
Definition at line 37 of file skill_boost.cpp.
 {
     mandatory( jo, was_loaded, "skills", _skills );
     mandatory( jo, was_loaded, "skill_offset", _offset );
     mandatory( jo, was_loaded, "scaling_power", _power );
 }
References _offset, _power, _skills, mandatory, and was_loaded.
load_boost()
void skill_boost::load_boost (const JsonObject & jo, const std::string & src) static
Definition at line 32 of file skill_boost.cpp.
 {
     all_skill_boosts.load( jo, src );
 }
References anonymous_namespace{skill_boost.cpp}::all_skill_boosts, and src.
Referenced by DynamicDataLoader::initialize().
reset()
void skill_boost::reset () static
Definition at line 44 of file skill_boost.cpp.
 {
     all_skill_boosts.reset();
 }
References anonymous_namespace{skill_boost.cpp}::all_skill_boosts.
Referenced by DynamicDataLoader::unload_data().
skills()
const std::vector< std::string > & skill_boost::skills () const
Definition at line 54 of file skill_boost.cpp.
 {
     return _skills;
 }
References _skills.
stat()
std::string skill_boost::stat () const
Definition at line 49 of file skill_boost.cpp.
 {
     return id.str();
 }
Friends And Related Function Documentation
generic_factory< skill_boost >
friend class generic_factory< skill_boost > friend
Definition at line 29 of file skill_boost.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 33 of file skill_boost.h.
Member Data Documentation
_offset
int skill_boost::_offset = 0 private
Definition at line 38 of file skill_boost.h.
Referenced by calc_bonus(), and load().
_power
float skill_boost::_power = 0.0f private
Definition at line 39 of file skill_boost.h.
Referenced by calc_bonus(), and load().
_skills
std::vector<std::string> skill_boost::_skills private
Definition at line 37 of file skill_boost.h.
Referenced by load(), and skills().
id
string_id<skill_boost> skill_boost::id private
Definition at line 34 of file skill_boost.h.
src
std::vector<std::pair<string_id<skill_boost>, mod_id> > skill_boost::src private
Definition at line 35 of file skill_boost.h.
Referenced by load_boost().
was_loaded
bool skill_boost::was_loaded = false private
Definition at line 36 of file skill_boost.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/skill_boost.h
src/skill_boost.cpp