Cataclysm DDA: climbing_aid::fall_scan Class Reference
climbing_aid::fall_scan Class Reference
Scans downwards from a tile to assess what lies between it and solid ground.
#include <climbing.h>
Public Member Functions
fall_scan (const tripoint &examp)
operator bool () const
tripoint pos_top () const
tripoint pos_bottom () const
tripoint pos_just_below () const
tripoint pos_furniture_or_floor () const
bool furn_just_below () const
bool furn_below () const
bool veh_just_below () const
bool veh_below () const
bool crea_just_below () const
bool crea_below () const
Public Attributes
tripoint examp
int height
int height_until_creature
int height_until_furniture
int height_until_vehicle
Detailed Description
Scans downwards from a tile to assess what lies between it and solid ground.
Definition at line 88 of file climbing.h.
Constructor & Destructor Documentation
fall_scan()
climbing_aid::fall_scan::fall_scan (const tripoint & examp) explicit
Definition at line 368 of file climbing.cpp.
 {
     map &here = get_map();
     creature_tracker &creatures = get_creature_tracker();
     this->examp = examp;
     height = 0;
     height_until_furniture = 0;
     height_until_creature = 0;
     height_until_vehicle = 0;
     // Get coordinates just below and at ground level.
     // Also detect if furniture would block our tools/abilities.
     tripoint bottom = examp;
     tripoint just_below = examp;
     just_below.z--;
     int hit_furn = false;
     int hit_crea = false;
     int hit_veh = false;
     for( tripoint lower = just_below; here.valid_move( bottom, lower, false, true ); ) {
         if( !hit_furn ) {
             if( here.has_furn( lower ) ) {
                 hit_furn = true;
             } else {
                 ++height_until_furniture;
             }
         }
         if( !hit_veh ) {
             if( here.veh_at( lower ) ) {
                 hit_veh = true;
             } else {
                 ++height_until_vehicle;
             }
         }
         if( !hit_crea ) {
             ++height_until_creature;
             if( creatures.creature_at( lower, false ) ) {
                 hit_crea = true;
             } else {
                 ++height_until_creature;
             }
         }
         ++height;
         bottom.z--;
         lower.z--;
     }
 }
References creature_tracker::creature_at(), get_creature_tracker(), get_map(), map::has_furn(), map::valid_move(), map::veh_at(), and tripoint::z.
Member Function Documentation
crea_below()
bool climbing_aid::fall_scan::crea_below () const inline
Definition at line 138 of file climbing.h.
{
                     return height > 0 && height_until_creature != height;
                 }
crea_just_below()
bool climbing_aid::fall_scan::crea_just_below () const inline
Definition at line 135 of file climbing.h.
{
                     return height > 0 && height_until_creature == 0;
                 }
furn_below()
bool climbing_aid::fall_scan::furn_below () const inline
Definition at line 126 of file climbing.h.
{
                     return height > 0 && height_until_furniture != height;
                 }
furn_just_below()
bool climbing_aid::fall_scan::furn_just_below () const inline
Definition at line 123 of file climbing.h.
{
                     return height > 0 && height_until_furniture == 0;
                 }
operator bool()
climbing_aid::fall_scan::operator bool () const inline explicit
Definition at line 100 of file climbing.h.
{
                     return height != 0;
                 }
pos_bottom()
tripoint climbing_aid::fall_scan::pos_bottom () const inline
Definition at line 107 of file climbing.h.
{
                     tripoint ret = examp;
                     ret.z -= height;
                     return ret;
                 }
References cata::hash64_detail::ret.
Referenced by game::climb_down_using().
pos_furniture_or_floor()
tripoint climbing_aid::fall_scan::pos_furniture_or_floor () const inline
Definition at line 117 of file climbing.h.
{
                     tripoint ret = examp;
                     ret.z -= std::min( height, height_until_furniture + 1 );
                     return ret;
                 }
References min(), and cata::hash64_detail::ret.
Referenced by game::climb_down_menu_gen(), game::climb_down_using(), and climbing_aid::detect_conditions().
pos_just_below()
tripoint climbing_aid::fall_scan::pos_just_below () const inline
Definition at line 112 of file climbing.h.
{
                     tripoint ret = examp;
                     ret.z -= 1;
                     return ret;
                 }
References cata::hash64_detail::ret.
pos_top()
tripoint climbing_aid::fall_scan::pos_top () const inline
Definition at line 104 of file climbing.h.
{
                     return examp;
                 }
Referenced by climbing_aid::detect_conditions().
veh_below()
bool climbing_aid::fall_scan::veh_below () const inline
Definition at line 132 of file climbing.h.
{
                     return height > 0 && height_until_vehicle != height;
                 }
veh_just_below()
bool climbing_aid::fall_scan::veh_just_below () const inline
Definition at line 129 of file climbing.h.
{
                     return height > 0 && height_until_vehicle == 0;
                 }
Referenced by climbing_aid::detect_conditions().
Member Data Documentation
examp
tripoint climbing_aid::fall_scan::examp
Definition at line 93 of file climbing.h.
height
int climbing_aid::fall_scan::height
Definition at line 94 of file climbing.h.
Referenced by game::climb_down_menu_gen(), and game::climb_down_using().
height_until_creature
int climbing_aid::fall_scan::height_until_creature
Definition at line 95 of file climbing.h.
Referenced by game::climb_down_menu_gen().
height_until_furniture
int climbing_aid::fall_scan::height_until_furniture
Definition at line 96 of file climbing.h.
Referenced by game::climb_down_menu_gen().
height_until_vehicle
int climbing_aid::fall_scan::height_until_vehicle
Definition at line 97 of file climbing.h.
The documentation for this class was generated from the following files:
src/climbing.h
src/climbing.cpp