Cataclysm DDA: pickup_activity_actor Class Reference
pickup_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
pickup_activity_actor (const std::vector< item_location > &target_items, const std::vector< int > &quantities, const std::optional< tripoint > &starting_pos, bool autopickup)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
bool do_drop_invalid_inventory () const override
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Public Attributes
bool stash_successful
Used to check at the end of a pickup activity if the character was able to stash everything.
bool autopickup
Private Attributes
std::vector< item_location > target_items
Target items and the quantities thereof.
std::vector< int > quantities
Pickup::pick_info info
std::optional< tripoint > starting_pos
Position of the character when the activity is started.
Detailed Description
Definition at line 531 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
pickup_activity_actor()
pickup_activity_actor::pickup_activity_actor (const std::vector< item_location > & target_items, const std::vector< int > & quantities, const std::optional< tripoint > & starting_pos, bool autopickup) inline
Definition at line 548 of file activity_actor_definitions.h.
                                                  : target_items( target_items ),
             quantities( quantities ), starting_pos( starting_pos ), stash_successful( true ),
             autopickup( autopickup ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> pickup_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 570 of file activity_actor_definitions.h.
{
             return std::make_unique<pickup_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > pickup_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 2502 of file activity_actor.cpp.
 {
     pickup_activity_actor actor( {}, {}, std::nullopt, false );
     JsonObject data = jsin.get_object();
     data.read( "target_items", actor.target_items );
     data.read( "quantities", actor.quantities );
     data.read( "starting_pos", actor.starting_pos );
     data.read( "stash_successful", actor.stash_successful );
     data.read( "autopickup", actor.autopickup );
     data.read( "info", actor.info );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_drop_invalid_inventory()
bool pickup_activity_actor::do_drop_invalid_inventory () const inline override virtual
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Reimplemented from activity_actor.
Definition at line 578 of file activity_actor_definitions.h.
{
             return false;
         }
do_turn()
void pickup_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 2446 of file activity_actor.cpp.
 {
     // If we don't have target items bail out
     if( target_items.empty() ) {
         cancel_pickup( who );
         return;
     }
     // If the player moves while picking up (i.e.: in a moving vehicle) cancel
     // the activity, only populate starting_pos when grabbing from the ground
     if( starting_pos && *starting_pos != who.pos() ) {
         who.add_msg_if_player( _( "Moving canceled auto-pickup." ) );
         cancel_pickup( who );
         return;
     }
     // False indicates that the player canceled pickup when met with some prompt
     const bool keep_going = Pickup::do_pickup( target_items, quantities, autopickup,
                             stash_successful, info );
     // If there are items left we ran out of moves, so continue the activity
     // Otherwise, we are done.
     if( !keep_going || target_items.empty() ) {
         if( !stash_successful && !autopickup ) {
             add_msg( m_bad, _( "Some items were not picked up!" ) );
         }
         cancel_pickup( who );
         if( who.get_value( "THIEF_MODE_KEEP" ) != "YES" ) {
             who.set_value( "THIEF_MODE", "THIEF_ASK" );
         }
         if( !keep_going ) {
             // The user canceled the activity, so we're done
             // AIM might have more pickup activities pending, also cancel them.
             // TODO: Move this to advanced inventory instead of hacking it in here
             cancel_aim_processing();
         }
     }
 }
References _, add_msg(), Character::add_msg_if_player(), autopickup, cancel_aim_processing(), cancel_pickup(), Pickup::do_pickup(), Creature::get_value(), info, m_bad, Creature::pos(), quantities, Creature::set_value(), starting_pos, stash_successful, and target_items.
finish()
void pickup_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 568 of file activity_actor_definitions.h.
 {}
get_progress_message()
std::string pickup_activity_actor::get_progress_message (const player_activity & act) const inline override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 574 of file activity_actor_definitions.h.
{
             return std::string();
         }
get_type()
activity_id pickup_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 562 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_PICKUP" );
         }
References activity_id.
serialize()
void pickup_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 2488 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target_items", target_items );
     jsout.member( "quantities", quantities );
     jsout.member( "starting_pos", starting_pos );
     jsout.member( "stash_successful", stash_successful );
     jsout.member( "autopickup", autopickup );
     jsout.member( "info", info );
     jsout.end_object();
 }
References autopickup, JsonOut::end_object(), info, JsonOut::member(), quantities, JsonOut::start_object(), starting_pos, stash_successful, and target_items.
start()
void pickup_activity_actor::start (player_activity & act, Character & who) inline override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 566 of file activity_actor_definitions.h.
 {}
Member Data Documentation
autopickup
bool pickup_activity_actor::autopickup
Definition at line 560 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
info
Pickup::pick_info pickup_activity_actor::info private
Definition at line 537 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
quantities
std::vector<int> pickup_activity_actor::quantities private
Definition at line 536 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
starting_pos
std::optional<tripoint> pickup_activity_actor::starting_pos private
Position of the character when the activity is started.
This is stored so that we can cancel the activity if the player moves (e.g. if the player is in a moving vehicle). This should be null if not grabbing from the ground.
Definition at line 545 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
stash_successful
bool pickup_activity_actor::stash_successful
Used to check at the end of a pickup activity if the character was able to stash everything.
If not, a message is displayed to clarify.
Definition at line 559 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
target_items
std::vector<item_location> pickup_activity_actor::target_items private
Target items and the quantities thereof.
Definition at line 535 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp