Cataclysm DDA: jmapgen_vending_machine Class Reference
jmapgen_vending_machine Class Reference
Place a vending machine with content.
Public Member Functions
jmapgen_vending_machine (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
Public Attributes
bool reinforced
mapgen_value< item_group_id > group_id
bool lootable
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a vending machine with content.
"item_group": the item group that is used to generate the content of the vending machine.
Definition at line 2065 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_vending_machine()
jmapgen_vending_machine::jmapgen_vending_machine (const JsonObject & jsi, const std::string_view) inline
Definition at line 2071 of file mapgen.cpp.
                                                                                 :
             reinforced( jsi.get_bool( "reinforced", false ) )
             , lootable( jsi.get_bool( "lootable", false ) ) {
             if( jsi.has_member( "item_group" ) ) {
                 group_id = mapgen_value<item_group_id>( jsi.get_member( "item_group" ) );
             } else {
                 group_id = mapgen_value<item_group_id>( "default_vending_machine" );
             }
         }
References JsonObject::get_member(), group_id, JsonObject::has_member(), and mapgen_defer::jsi.
Member Function Documentation
apply()
void jmapgen_vending_machine::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2080 of file mapgen.cpp.
{
             const tripoint_bub_ms r( x.get(), y.get(), dat.zlevel() + z.get() );
             dat.m.furn_set( r, furn_str_id::NULL_ID() );
             item_group_id chosen_id = group_id.get( dat );
             if( chosen_id.is_null() ) {
                 return;
             }
             dat.m.place_vending( r, chosen_id, reinforced, lootable );
         }
References map::furn_set(), jmapgen_int::get(), group_id, string_id< T >::is_null(), lootable, mapgendata::m, string_id< furn_t >::NULL_ID(), map::place_vending(), reinforced, and mapgendata::zlevel().
check()
void jmapgen_vending_machine::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 2094 of file mapgen.cpp.
{
             group_id.check( oter_name, parameters );
         }
References group_id.
has_vehicle_collision()
bool jmapgen_vending_machine::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2090 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint_bub_ms( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
Member Data Documentation
group_id
mapgen_value<item_group_id> jmapgen_vending_machine::group_id
Definition at line 2069 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_vending_machine().
lootable
bool jmapgen_vending_machine::lootable
Definition at line 2070 of file mapgen.cpp.
Referenced by apply().
reinforced
bool jmapgen_vending_machine::reinforced
Definition at line 2068 of file mapgen.cpp.
Referenced by apply().
The documentation for this class was generated from the following file:
src/mapgen.cpp