Cataclysm DDA: targeting_graph< T, Wrapper > Class Template Reference
targeting_graph< T, Wrapper > Class Template Reference
#include <ballistics.h>
Classes
struct node
Public Member Functions
void generate (const T &center, const std::vector< T > &parts)
T select (const double range_min, const double range_max, double value) const
Private Member Functions
const node & add_node (const T &val)
void add (const T &from, const T &to)
Private Attributes
std::map< T, node > graph
T root
Detailed Description
template<typename T, typename Wrapper>
class targeting_graph< T, Wrapper >
Definition at line 67 of file ballistics.h.
Member Function Documentation
add()
template<typename T , typename Wrapper > void targeting_graph< T, Wrapper >::add (const T & from, const T & to) inline private
Definition at line 84 of file ballistics.h.
{
             graph[from].connections.emplace_back( &add_node( to ) );
         }
References targeting_graph< T, Wrapper >::add_node(), and targeting_graph< T, Wrapper >::graph.
Referenced by targeting_graph< T, Wrapper >::generate().
add_node()
template<typename T , typename Wrapper > const node& targeting_graph< T, Wrapper >::add_node (const T & val) inline private
Definition at line 77 of file ballistics.h.
{
             node added;
             added.val = val;
             added.weight = Wrapper::weight( val );
             return graph.emplace( val, added ).first->second;
         }
References targeting_graph< T, Wrapper >::graph, targeting_graph< T, Wrapper >::node::val, and targeting_graph< T, Wrapper >::node::weight.
Referenced by targeting_graph< T, Wrapper >::add(), and targeting_graph< T, Wrapper >::generate().
generate()
template<typename T , typename Wrapper > void targeting_graph< T, Wrapper >::generate (const T & center, const std::vector< T > & parts) inline
Definition at line 89 of file ballistics.h.
{
             add_node( center );
             root = center;
             // First, enumerate all of the connections
             std::map<T, std::set<T>> connects_to;
             for( const T &cursor : parts ) {
                 // The root part connects to itself - don't add that
                 if( Wrapper::connection( cursor ) == cursor ) {
                     continue;
                 }
                 // Add the connection to the map, if it's not there already
                 auto result = connects_to.emplace( Wrapper::connection( cursor ), std::set<T>() );
                 // And then add the connected to the vector stored there
                 result.first->second.emplace( cursor );
             }
             std::list<T> next;
             next.push_back( center );
             while( !next.empty() ) {
                 const T current = next.front();
                 next.pop_front();
                 // Look for what connects to me
                 const auto connected_iter = connects_to.find( current );
                 if( connected_iter != connects_to.end() ) {
                     for( const T &cursor : connected_iter->second ) {
                         add( current, cursor );
                         next.push_back( cursor );
                     }
                     connects_to.erase( connected_iter );
                 }
                 // Look for what I connect to
                 for( std::pair<const T, std::set<T>> &entry : connects_to ) {
                     if( entry.second.find( current ) == entry.second.end() ) {
                         continue;
                     }
                     next.push_back( entry.first );
                     add( current, entry.first );
                     entry.second.erase( current );
                 }
             }
         }
References targeting_graph< T, Wrapper >::add(), targeting_graph< T, Wrapper >::add_node(), center, connects_to(), and targeting_graph< T, Wrapper >::root.
Referenced by anatomy::select_body_part_projectile_attack().
select()
template<typename T , typename Wrapper > T targeting_graph< T, Wrapper >::select (const double range_min, const double range_max, double value) const inline
Definition at line 132 of file ballistics.h.
{
             // First, find the path we will follow
             // That is, what body parts we will hit with less and less accurate shots
             std::list<const node *> path;
             // Of course, start with the center of mass
             path.push_back( &graph.at( root ) );
             // While there's still a body part to hit with less accurate shots
             while( !path.back()->connections.empty() ) {
                 // Select the next body part to hit based on the relative size of the options
                 weighted_float_list<size_t> next;
                 const std::vector<const node *> &connections = path.back()->connections;
                 for( size_t i = 0; i < connections.size(); ++i ) {
                     next.add( i, connections[i]->weight );
                 }
                 path.push_back( connections[*next.pick()] );
             }
             // This will make the lowest possible value of 'value' 0,
             // and the highest possible value 'range_max' - 'range_min'
             // Or, if range_min is -0.5, range_max is 1.5, this will put value into the range 0-2
             // And below, we'll have a scale factor of 2 / total_weight
             value -= range_min;
             // Now, find the total weight along our path
             double total_weight = 0.0;
             for( const node *nd : path ) {
                 total_weight += nd->weight;
             }
             // And using this, and the min/max ranges of our target value,
             // find how to appropriate scale the weight of each node in our path
             double scale_factor = ( range_max - range_min ) / total_weight;
             // Then, just walk along the path
             double accumulated_weight = 0.0;
             for( const node *nd : path ) {
                 accumulated_weight += nd->weight * scale_factor;
                 // And quit when we've gone far enough that we can't make it to the next part
                 if( accumulated_weight > value ) {
                     return nd->val;
                 }
             }
             // And if we made it all the way here, we (somehow) hit with a very inaccurate shot
             return path.back()->val;
         }
References weighted_list< W, T >::add(), anonymous_namespace{overmap_connection.cpp}::connections, targeting_graph< T, Wrapper >::graph, weighted_list< W, T >::pick(), and targeting_graph< T, Wrapper >::root.
Referenced by anatomy::select_body_part_projectile_attack().
Member Data Documentation
graph
template<typename T , typename Wrapper > std::map<T, node> targeting_graph< T, Wrapper >::graph private
Definition at line 74 of file ballistics.h.
Referenced by targeting_graph< T, Wrapper >::add(), targeting_graph< T, Wrapper >::add_node(), and targeting_graph< T, Wrapper >::select().
root
template<typename T , typename Wrapper > T targeting_graph< T, Wrapper >::root private
Definition at line 75 of file ballistics.h.
Referenced by targeting_graph< T, Wrapper >::generate(), and targeting_graph< T, Wrapper >::select().
The documentation for this class was generated from the following file:
src/ballistics.h