Cataclysm DDA: ret_val< T > Class Template Reference
ret_val< T > Class Template Reference
The class represents a composite return value of an arbitrary function (result).
#include <ret_val.h>
Classes
struct default_failure
struct default_success
Public Member Functions
ret_val ()=delete
T value () const
Public Member Functions inherited from ret_val_common
bool success () const
const std::string & str () const
const char * c_str () const
Static Public Member Functions
static ret_val make_success (T val=default_success::value)
static ret_val make_failure (T val=default_failure::value)
template<class... A, typename S = std::string, typename = is_convertible_to_string<S>>
static ret_val make_success (T val, const S &msg, A &&... args)
template<class... A, typename S = std::string, typename = is_convertible_to_string<S>>
static ret_val make_failure (T val, const S &msg, A &&... args)
template<class... A, typename S = std::string, typename = is_convertible_to_string<S>>
static ret_val make_success (const S &msg, A &&... args)
template<class... A, typename S = std::string, typename = is_convertible_to_string<S>>
static ret_val make_failure (const S &msg, A &&... args)
Private Member Functions
ret_val (const std::string &msg, T val, bool succ)
Private Attributes
T val
Additional Inherited Members
Protected Types inherited from ret_val_common
template<typename S >
using is_convertible_to_string = std::enable_if_t< !std::is_same_v< S, std::nullptr_t > &&std::is_convertible_v< S, std::string > >
Protected Member Functions inherited from ret_val_common
ret_val_common (const std::string &msg, bool succ)
Detailed Description
template<typename T>
class ret_val< T >
The class represents a composite return value of an arbitrary function (result).
'Composite' means that apart from the value itself, the result also contains:
a boolean flag which indicates the binary state of the result: success/failure.
an arbitrary string which additionally describes the result (may be empty).
Template parameter T specifies the type of the value.
Definition at line 48 of file ret_val.h.
Constructor & Destructor Documentation
ret_val() [1/2]
template<typename T > ret_val< T >::ret_val () delete
Referenced by ret_val< void >::make_failure(), ret_val< T >::make_failure(), ret_val< void >::make_success(), and ret_val< T >::make_success().
ret_val() [2/2]
template<typename T > ret_val< T >::ret_val (const std::string & msg, T val, bool succ) inline private
Definition at line 96 of file ret_val.h.
             : ret_val_common( msg, succ ), val( val ) {}
Member Function Documentation
make_failure() [1/3]
template<typename T > template<class... A, typename S = std::string, typename = is_convertible_to_string<S>> static ret_val ret_val< T >::make_failure (const S & msg, A &&... args) inline static
Definition at line 87 of file ret_val.h.
{
             return make_failure( default_failure::value, msg, std::forward<A>( args )... );
         }
References ret_val< T >::make_failure(), and ret_val_common::msg.
make_failure() [2/3]
template<typename T > template<class... A, typename S = std::string, typename = is_convertible_to_string<S>> static ret_val ret_val< T >::make_failure (T val, const S & msg, A &&... args) inline static
Definition at line 77 of file ret_val.h.
{
             return ret_val( string_format( msg, std::forward<A>( args )... ), val, false );
         }
References ret_val_common::msg, ret_val< T >::ret_val(), string_format(), and ret_val< T >::val.
make_failure() [3/3]
template<typename T > static ret_val ret_val< T >::make_failure (T val = default_failure::value) inline static
Definition at line 67 of file ret_val.h.
{
             return make_failure( val, std::string() );
         }
References ret_val< T >::val.
Referenced by item_pocket::_can_contain(), profession::can_afford(), scenario::can_afford(), use_function::can_call(), item_contents::can_contain(), item::can_contain(), item_contents::can_contain_rigid(), Character::can_crush_frozen_liquid(), Character::can_deactivate_bionic(), Character::can_disassemble(), Character::can_drop(), Character::can_eat(), iexamine::can_fertilize(), vehicle::can_mount(), profession::can_pick(), scenario::can_pick(), Character::can_takeoff(), Character::can_try_doge(), vehicle::can_unmount(), Character::can_unwield(), iuse_transform::can_use(), firestarter_actor::can_use(), fireweapon_off_actor::can_use(), manualnoise_actor::can_use(), musical_instrument_actor::can_use(), install_bionic_actor::can_use(), detach_gunmods_actor::can_use(), modify_gunmods_actor::can_use(), saw_barrel_actor::can_use_on(), saw_stock_actor::can_use_on(), Character::can_wear(), Character::can_wield(), check_deploy_square(), item_contents::item_contents_helper::find_pocket_for(), insert_item_activity_actor::finish(), Character::i_add_or_fill(), item_pocket::insert_item(), item_contents::insert_item(), item::is_compatible(), item_contents::is_compatible(), item_pocket::is_compatible(), item::is_gunmod_compatible(), Character::is_installable(), item::link_to(), ret_val< void >::make_failure(), ret_val< T >::make_failure(), item_location::max_charges_by_parent_recursive(), item_location::parents_can_contain_recursive(), outfit::power_armor_conflicts(), item::put_in(), item_components::remove(), rigid_test(), test_only_one_conflicts(), try_insert(), try_parse_integer(), npc::wants_to_buy(), and npc::wants_to_sell().
make_success() [1/3]
template<typename T > template<class... A, typename S = std::string, typename = is_convertible_to_string<S>> static ret_val ret_val< T >::make_success (const S & msg, A &&... args) inline static
Definition at line 82 of file ret_val.h.
{
             return make_success( default_success::value, msg, std::forward<A>( args )... );
         }
References ret_val< T >::make_success(), and ret_val_common::msg.
make_success() [2/3]
template<typename T > template<class... A, typename S = std::string, typename = is_convertible_to_string<S>> static ret_val ret_val< T >::make_success (T val, const S & msg, A &&... args) inline static
Definition at line 72 of file ret_val.h.
{
             return ret_val( string_format( msg, std::forward<A>( args )... ), val, true );
         }
References ret_val_common::msg, ret_val< T >::ret_val(), string_format(), and ret_val< T >::val.
make_success() [3/3]
template<typename T > static ret_val ret_val< T >::make_success (T val = default_success::value) inline static
Definition at line 63 of file ret_val.h.
{
             return make_success( val, std::string() );
         }
References ret_val< T >::val.
Referenced by item_pocket::_can_contain(), profession::can_afford(), scenario::can_afford(), item_contents::can_contain(), item::can_contain(), item_contents::can_contain_rigid(), Character::can_crush_frozen_liquid(), Character::can_deactivate_bionic(), Character::can_disassemble(), Character::can_drop(), Character::can_eat(), iexamine::can_fertilize(), vehicle::can_mount(), profession::can_pick(), scenario::can_pick(), Character::can_takeoff(), Character::can_try_doge(), vehicle::can_unmount(), Character::can_unwield(), iuse_actor::can_use(), iuse_transform::can_use(), firestarter_actor::can_use(), fireweapon_off_actor::can_use(), manualnoise_actor::can_use(), play_instrument_iuse::can_use(), musical_instrument_actor::can_use(), install_bionic_actor::can_use(), detach_gunmods_actor::can_use(), modify_gunmods_actor::can_use(), saw_barrel_actor::can_use_on(), saw_stock_actor::can_use_on(), Character::can_wear(), Character::can_wield(), check_deploy_square(), outfit::check_rigid_conflicts(), item_contents::item_contents_helper::find_pocket_for(), comestible_inventory_preset::get_denial(), Character::i_add_or_fill(), item_pocket::insert_item(), item_contents::is_compatible(), item_pocket::is_compatible(), item::is_gunmod_compatible(), Character::is_installable(), item::link_to(), ret_val< void >::make_success(), ret_val< T >::make_success(), item_location::max_charges_by_parent_recursive(), outfit::only_one_conflicts(), item_location::parents_can_contain_recursive(), outfit::power_armor_conflicts(), item::put_in(), item_components::remove(), rigid_test(), test_only_one_conflicts(), try_parse_integer(), npc::wants_to_buy(), npc::wants_to_sell(), and Character::will_eat().
value()
template<typename T > T ret_val< T >::value () const inline
Definition at line 91 of file ret_val.h.
{
             return val;
         }
References ret_val< T >::val.
Referenced by item::ammo_info(), item::color_in_inventory(), Character::complete_disassemble(), Character::crush_frozen_liquid(), edit_integer(), basecamp::feed_workers(), item_pocket::fill_with(), item::fill_with(), Item_factory::finalize_pre(), get_quality_from_string(), item::get_var(), getGasDiscountCardQuality(), item_contents::insert_cost(), item_contents::insert_item(), item::put_in(), query_int_impl(), options_manager::cOpt::setValue(), Character::store(), debug_menu::teleport_overmap(), try_insert(), deploy_furn_actor::use(), and deploy_appliance_actor::use().
Member Data Documentation
val
template<typename T > T ret_val< T >::val private
Definition at line 99 of file ret_val.h.
Referenced by get_str_translation_or_var(), ret_val< T >::make_failure(), ret_val< T >::make_success(), and ret_val< T >::value().
The documentation for this class was generated from the following files:
src/item.h
src/ret_val.h