Cataclysm DDA: place_npc_iuse Class Reference
place_npc_iuse Class Reference
This iuse contains the logic to summon an npc on the map.
#include <iuse_actor.h>
Public Member Functions
place_npc_iuse ()
~place_npc_iuse () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
string_id< npc_template > npc_class_id
bool place_randomly = false
int radius = 1
int moves = 100
translation summon_msg
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
This iuse contains the logic to summon an npc on the map.
Definition at line 371 of file iuse_actor.h.
Constructor & Destructor Documentation
place_npc_iuse()
place_npc_iuse::place_npc_iuse () inline
Definition at line 380 of file iuse_actor.h.
 : iuse_actor( "place_npc" ) { }
~place_npc_iuse()
place_npc_iuse::~place_npc_iuse () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > place_npc_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 983 of file iuse_actor.cpp.
 {
     return std::make_unique<place_npc_iuse>( *this );
 }
load()
void place_npc_iuse::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 988 of file iuse_actor.cpp.
 {
     npc_class_id = string_id<npc_template>( obj.get_string( "npc_class_id" ) );
     obj.read( "summon_msg", summon_msg );
     obj.read( "moves", moves );
     obj.read( "place_randomly", place_randomly );
 }
References JsonObject::get_string(), moves, place_randomly, JsonObject::read(), and summon_msg.
use()
std::optional< int > place_npc_iuse::use (Character * p, item & , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 996 of file iuse_actor.cpp.
 {
     map &here = get_map();
     const tripoint_range<tripoint> target_range = place_randomly ?
             points_in_radius( p->pos(), radius ) :
             points_in_radius( choose_adjacent( _( "Place NPC where?" ) ).value_or( p->pos() ), 0 );
     const std::optional<tripoint> target_pos =
     random_point( target_range, [&here]( const tripoint & t ) {
         return here.passable( t ) && here.has_floor_or_support( t ) &&
                !get_creature_tracker().creature_at( t );
     } );
     if( !target_pos.has_value() ) {
         p->add_msg_if_player( m_info, _( "There is no square to spawn NPC in!" ) );
         return std::nullopt;
     }
     here.place_npc( target_pos.value().xy(), npc_class_id );
     p->mod_moves( -moves );
     p->add_msg_if_player( m_info, "%s", summon_msg );
     return 1;
 }
References _, Character::add_msg_if_player(), choose_adjacent(), get_creature_tracker(), get_map(), map::has_floor_or_support(), m_info, Creature::mod_moves(), moves, map::passable(), map::place_npc(), place_randomly, points_in_radius(), Creature::pos(), radius, random_point(), and summon_msg.
Member Data Documentation
moves
int place_npc_iuse::moves = 100
Definition at line 377 of file iuse_actor.h.
Referenced by load(), and use().
npc_class_id
string_id<npc_template> place_npc_iuse::npc_class_id
Definition at line 374 of file iuse_actor.h.
place_randomly
bool place_npc_iuse::place_randomly = false
Definition at line 375 of file iuse_actor.h.
Referenced by load(), and use().
radius
int place_npc_iuse::radius = 1
Definition at line 376 of file iuse_actor.h.
Referenced by use().
summon_msg
translation place_npc_iuse::summon_msg
Definition at line 378 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp