Cataclysm DDA: stats_tracker Class Reference
stats_tracker Class Reference
#include <stats_tracker.h>
Public Member Functions
~stats_tracker () override
event_multiset & get_events (event_type)
event_multiset get_events (const string_id< event_transformation > &)
cata_variant value_of (const string_id< event_statistic > &)
void add_watcher (event_type, event_multiset_watcher *)
void add_watcher (const string_id< event_transformation > &, event_multiset_watcher *)
const cata_variant & add_watcher (const string_id< event_statistic > &, stat_watcher *)
void unwatch (base_watcher *)
void transformed_set_changed (const string_id< event_transformation > &, const cata::event &new_element)
void transformed_set_changed (const string_id< event_transformation > &, const event_multiset &new_value)
void stat_value_changed (const string_id< event_statistic > &, const cata_variant &new_value)
std::vector< const score * > valid_scores () const
void clear ()
void notify (const cata::event &) override
void serialize (JsonOut &) const
void deserialize (const JsonObject &jo)
virtual void notify (const cata::event &)=0
virtual void notify (const cata::event &, std::unique_ptr< talker >, std::unique_ptr< talker >)
Public Member Functions inherited from event_subscriber
event_subscriber ()=default
event_subscriber (const event_subscriber &)=delete
event_subscriber & operator= (const event_subscriber &)=delete
virtual ~event_subscriber ()
virtual void notify (const cata::event &, std::unique_ptr< talker >, std::unique_ptr< talker >)
Private Member Functions
void unwatch_all ()
Private Attributes
std::unordered_map< event_type, event_multiset > data
std::unordered_map< event_type, watcher_set< event_multiset_watcher > > event_type_watchers
std::unordered_map< string_id< event_transformation >, watcher_set< event_multiset_watcher > > event_transformation_watchers
std::unordered_map< string_id< event_statistic >, watcher_set< stat_watcher > > stat_watchers
std::unordered_map< string_id< event_transformation >, std::unique_ptr< stats_tracker_state > > event_transformation_states
std::unordered_map< string_id< event_statistic >, std::unique_ptr< stats_tracker_state > > stat_states
std::unordered_set< string_id< score > > initial_scores
Detailed Description
Definition at line 187 of file stats_tracker.h.
Constructor & Destructor Documentation
~stats_tracker()
stats_tracker::~stats_tracker () override
Definition at line 227 of file stats_tracker.cpp.
 {
     unwatch_all();
 }
References unwatch_all().
Member Function Documentation
add_watcher() [1/3]
const cata_variant & stats_tracker::add_watcher (const string_id< event_statistic > & id, stat_watcher * watcher)
Definition at line 265 of file stats_tracker.cpp.
 {
     stat_watchers[id].insert( watcher );
     watcher->on_subscribe( this );
     std::unique_ptr<stats_tracker_state> &state = stat_states[ id ];
     if( !state ) {
         state = id->watch( *this );
     }
     return state->get_value();
 }
References base_camps::id, base_watcher::on_subscribe(), stat_states, and stat_watchers.
add_watcher() [2/3]
void stats_tracker::add_watcher (const string_id< event_transformation > & id, event_multiset_watcher * watcher)
Definition at line 254 of file stats_tracker.cpp.
 {
     event_transformation_watchers[id].insert( watcher );
     watcher->on_subscribe( this );
     std::unique_ptr<stats_tracker_state> &state = event_transformation_states[ id ];
     if( !state ) {
         state = id->watch( *this );
     }
 }
References event_transformation_states, event_transformation_watchers, base_camps::id, and base_watcher::on_subscribe().
add_watcher() [3/3]
void stats_tracker::add_watcher (event_type type, event_multiset_watcher * watcher)
Definition at line 248 of file stats_tracker.cpp.
 {
     event_type_watchers[type].insert( watcher );
     watcher->on_subscribe( this );
 }
References event_type_watchers, base_watcher::on_subscribe(), and type.
clear()
void stats_tracker::clear ()
Definition at line 337 of file stats_tracker.cpp.
 {
     unwatch_all();
     data.clear();
     event_transformation_states.clear();
     stat_states.clear();
     initial_scores.clear();
 }
References data, event_transformation_states, initial_scores, stat_states, and unwatch_all().
Referenced by game::setup().
deserialize()
void stats_tracker::deserialize (const JsonObject & jo)
Definition at line 4557 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     jo.read( "data", data );
     for( std::pair<const event_type, event_multiset> &d : data ) {
         d.second.set_type( d.first );
     }
     jo.read( "initial_scores", initial_scores );
     // TODO: remove after 0.H
     // migration for saves made before addition of event_type::game_avatar_new
     event_multiset gan_evts = get_events( event_type::game_avatar_new );
     if( !gan_evts.count() ) {
         event_multiset gs_evts = get_events( event_type::game_start );
         avatar &u = get_avatar();
         // check if character ID set, if loadsave, the ID will not be -1
         // if it's an old save without event_type::game_avatar_new, the event need to be done
         // this function is invoked when load memorial, on this situation start a new game, below shouldn't be invoked.
         if( u.getID() != character_id( -1 ) ) {
             if( gs_evts.count() ) {
                 auto gs_evt = gs_evts.first().value();
                 cata::event::data_type gs_data = gs_evt.first;
                 // retroactively insert starting avatar
                 cata::event::data_type gan_data( gs_data );
                 gan_data["is_new_game"] = cata_variant::make<cata_variant_type::bool_>( true );
                 gan_data["is_debug"] = cata_variant::make<cata_variant_type::bool_>( false );
                 gan_data.erase( "game_version" );
                 get_event_bus().send( cata::event( event_type::game_avatar_new, calendar::start_of_game,
                                                    std::move( gan_data ) ) );
                 // retroactively insert current avatar, if different from starting avatar
                 // we don't know when they took over, so just use current time point
                 if( u.getID() != gs_data["avatar_id"].get<cata_variant_type::character_id>() ) {
                     profession_id prof_id = u.prof ? u.prof->ident() : profession::generic()->ident();
                     get_event_bus().send( cata::event::make<event_type::game_avatar_new>( false, false,
                                           u.getID(), u.name, u.male, prof_id, u.custom_profession ) );
                 }
             } else {
                 // last ditch effort for really old saves that don't even have event_type::game_start
                 // treat current avatar as the starting avatar; abuse is_new_game=false to flag such cases
                 profession_id prof_id = u.prof ? u.prof->ident() : profession::generic()->ident();
                 std::swap( calendar::turn, calendar::start_of_game );
                 get_event_bus().send( cata::event::make<event_type::game_avatar_new>( false, false,
                                       u.getID(), u.name, u.male, prof_id, u.custom_profession ) );
                 std::swap( calendar::turn, calendar::start_of_game );
             }
         }
     }
 }
References JsonObject::allow_omitted_members(), character_id, event_multiset::count(), item_pocket::data, event_multiset::first(), game_avatar_new, game_start, profession::generic(), get_avatar(), get_event_bus(), profession::ident(), JsonObject::read(), event_bus::send(), calendar::start_of_game, cata::swap(), calendar::turn, and u.
get_events() [1/2]
event_multiset stats_tracker::get_events (const string_id< event_transformation > & transform_id)
Definition at line 237 of file stats_tracker.cpp.
 {
     return transform_id->value( *this );
 }
References event_transformation::value().
get_events() [2/2]
event_multiset & stats_tracker::get_events (event_type type)
Definition at line 232 of file stats_tracker.cpp.
 {
     return data.emplace( type, event_multiset( type ) ).first->second;
 }
References data, and type.
Referenced by game::load(), and notify().
notify() [1/3]
void stats_tracker::notify (const cata::event & e) override virtual
Implements event_subscriber.
Definition at line 360 of file stats_tracker.cpp.
 {
     const event_type type = e.type();
     get_events( type ).add( e );
     auto it = event_type_watchers.find( type );
     if( it != event_type_watchers.end() ) {
         it->second.send_to_all( &event_multiset_watcher::event_added, e, *this );
     }
     if( e.type() == event_type::game_start ) {
         cata_assert( initial_scores.empty() );
         for( const score &scr : score::get_all() ) {
             initial_scores.insert( scr.id );
         }
     }
 }
References event_multiset::add(), cata_assert, event_multiset_watcher::event_added(), event_type_watchers, game_start, score::get_all(), get_events(), initial_scores, type, and cata::event::type().
notify() [2/3]
virtual void event_subscriber::notify
notify() [3/3]
void event_subscriber::notify
Definition at line 22 of file event_bus.cpp.
 {
     notify( e );
 }
serialize()
void stats_tracker::serialize (JsonOut & jsout) const
Definition at line 4549 of file savegame_json.cpp.
 {
     jsout.start_object();
     jsout.member( "data", data );
     jsout.member( "initial_scores", initial_scores );
     jsout.end_object();
 }
References item_pocket::data, JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
stat_value_changed()
void stats_tracker::stat_value_changed (const string_id< event_statistic > & id, const cata_variant & new_value)
Definition at line 317 of file stats_tracker.cpp.
 {
     auto it = stat_watchers.find( id );
     if( it != stat_watchers.end() ) {
         it->second.send_to_all( &stat_watcher::new_value, new_value, *this );
     }
 }
References stat_watcher::new_value(), and stat_watchers.
transformed_set_changed() [1/2]
void stats_tracker::transformed_set_changed (const string_id< event_transformation > & id, const cata::event & new_element)
Definition at line 299 of file stats_tracker.cpp.
 {
     auto it = event_transformation_watchers.find( id );
     if( it != event_transformation_watchers.end() ) {
         it->second.send_to_all( &event_multiset_watcher::event_added, new_element, *this );
     }
 }
References event_multiset_watcher::event_added(), and event_transformation_watchers.
transformed_set_changed() [2/2]
void stats_tracker::transformed_set_changed (const string_id< event_transformation > & id, const event_multiset & new_value)
Definition at line 308 of file stats_tracker.cpp.
 {
     auto it = event_transformation_watchers.find( id );
     if( it != event_transformation_watchers.end() ) {
         it->second.send_to_all( &event_multiset_watcher::events_reset, new_value, *this );
     }
 }
References event_transformation_watchers, and event_multiset_watcher::events_reset().
unwatch()
void stats_tracker::unwatch (base_watcher * watcher)
Definition at line 277 of file stats_tracker.cpp.
 {
     // Use a slow O(n) approach for now; if it proves problematic we can build
     // an index, but that seems over-complex.
     auto erase_from = [watcher]( auto & map_of_watcher_sets ) {
         for( auto &p : map_of_watcher_sets ) {
             auto &set = p.second;
             if( set.erase( watcher ) ) {
                 return true;
             }
         }
         return false;
     };
     if( erase_from( event_type_watchers ) ||
         erase_from( event_transformation_watchers ) ||
         erase_from( stat_watchers ) ) {
         return;
     }
     debugmsg( "unwatch for a watcher not found" );
 }
References debugmsg, event_transformation_watchers, event_type_watchers, and stat_watchers.
Referenced by base_watcher::~base_watcher().
unwatch_all()
void stats_tracker::unwatch_all () private
Definition at line 346 of file stats_tracker.cpp.
 {
     auto unsub_all = [&]( auto & map_of_watcher_sets ) {
         for( auto const &p : map_of_watcher_sets ) {
             const auto &set = p.second;
             set.send_to_all( &base_watcher::on_unsubscribe, this );
         }
         map_of_watcher_sets.clear();
     };
     unsub_all( event_type_watchers );
     unsub_all( event_transformation_watchers );
     unsub_all( stat_watchers );
 }
References event_transformation_watchers, event_type_watchers, base_watcher::on_unsubscribe(), and stat_watchers.
Referenced by clear(), and ~stats_tracker().
valid_scores()
std::vector< const score * > stats_tracker::valid_scores () const
Definition at line 326 of file stats_tracker.cpp.
 {
     std::vector<const score *> result;
     for( const score &scr : score::get_all() ) {
         if( initial_scores.count( scr.id ) ) {
             result.push_back( &scr );
         }
     }
     return result;
 }
References score::get_all(), and initial_scores.
value_of()
cata_variant stats_tracker::value_of (const string_id< event_statistic > & stat)
Definition at line 243 of file stats_tracker.cpp.
 {
     return stat->value( *this );
 }
References event_statistic::value().
Member Data Documentation
data
std::unordered_map<event_type, event_multiset> stats_tracker::data private
Definition at line 223 of file stats_tracker.h.
Referenced by clear(), and get_events().
event_transformation_states
std::unordered_map<string_id<event_transformation>, std::unique_ptr<stats_tracker_state> > stats_tracker::event_transformation_states private
Definition at line 232 of file stats_tracker.h.
Referenced by add_watcher(), and clear().
event_transformation_watchers
std::unordered_map<string_id<event_transformation>, watcher_set<event_multiset_watcher> > stats_tracker::event_transformation_watchers private
Definition at line 228 of file stats_tracker.h.
Referenced by add_watcher(), transformed_set_changed(), unwatch(), and unwatch_all().
event_type_watchers
std::unordered_map<event_type, watcher_set<event_multiset_watcher> > stats_tracker::event_type_watchers private
Definition at line 226 of file stats_tracker.h.
Referenced by add_watcher(), notify(), unwatch(), and unwatch_all().
initial_scores
std::unordered_set<string_id<score> > stats_tracker::initial_scores private
Definition at line 236 of file stats_tracker.h.
Referenced by clear(), notify(), and valid_scores().
stat_states
std::unordered_map<string_id<event_statistic>, std::unique_ptr<stats_tracker_state> > stats_tracker::stat_states private
Definition at line 234 of file stats_tracker.h.
Referenced by add_watcher(), and clear().
stat_watchers
std::unordered_map<string_id<event_statistic>, watcher_set<stat_watcher> > stats_tracker::stat_watchers private
Definition at line 230 of file stats_tracker.h.
Referenced by add_watcher(), stat_value_changed(), unwatch(), and unwatch_all().
The documentation for this class was generated from the following files:
src/stats_tracker.h
src/savegame_json.cpp
src/stats_tracker.cpp