Cataclysm DDA: damage_over_time_data Class Reference
damage_over_time_data Class Reference
#include <damage.h>
Public Member Functions
void load (const JsonObject &obj)
void serialize (JsonOut &jsout) const
void deserialize (const JsonObject &jo)
Public Attributes
damage_type_id type
time_duration duration
std::vector< bodypart_str_id > bps
int amount = 0
bool was_loaded = false
Detailed Description
Definition at line 177 of file damage.h.
Member Function Documentation
deserialize()
void damage_over_time_data::deserialize (const JsonObject & jo)
Definition at line 865 of file damage.cpp.
 {
     std::string tmp_string = jo.get_string( "damage_type" );
     // Remove after 0.F, migrating DT_TRUE to DT_PURE
     if( tmp_string == "true" ) {
         tmp_string = "pure";
     }
     type = damage_type_id( tmp_string );
     jo.read( "amount", amount );
     jo.read( "duration", duration );
     jo.read( "bodyparts", bps );
 }
References amount, bps, duration, JsonObject::get_string(), JsonObject::read(), and type.
load()
void damage_over_time_data::load (const JsonObject & obj)
Definition at line 841 of file damage.cpp.
 {
     mandatory( obj, was_loaded, "damage_type", type );
     mandatory( obj, was_loaded, "amount", amount );
     mandatory( obj, was_loaded, "bodyparts", bps );
     if( obj.has_string( "duration" ) ) {
         duration = read_from_json_string<time_duration>( obj.get_member( "duration" ),
                    time_duration::units );
     } else {
         duration = time_duration::from_turns( obj.get_int( "duration", 0 ) );
     }
 }
References amount, bps, duration, time_duration::from_turns(), JsonObject::get_int(), JsonObject::get_member(), JsonObject::has_string(), mandatory, type, time_duration::units, and was_loaded.
serialize()
void damage_over_time_data::serialize (JsonOut & jsout) const
Definition at line 855 of file damage.cpp.
 {
     jsout.start_object();
     jsout.member( "damage_type", type );
     jsout.member( "duration", duration );
     jsout.member( "amount", amount );
     jsout.member( "bodyparts", bps );
     jsout.end_object();
 }
References amount, bps, duration, JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and type.
Member Data Documentation
amount
int damage_over_time_data::amount = 0
Definition at line 183 of file damage.h.
Referenced by deserialize(), load(), and serialize().
bps
std::vector<bodypart_str_id> damage_over_time_data::bps
Definition at line 182 of file damage.h.
Referenced by deserialize(), load(), and serialize().
duration
time_duration damage_over_time_data::duration
Definition at line 181 of file damage.h.
Referenced by deserialize(), load(), and serialize().
type
damage_type_id damage_over_time_data::type
Definition at line 180 of file damage.h.
Referenced by deserialize(), load(), and serialize().
was_loaded
bool damage_over_time_data::was_loaded = false
Definition at line 185 of file damage.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/damage.h
src/damage.cpp