Cataclysm DDA: global_variables Class Reference
global_variables Class Reference
#include <global_vars.h>
Public Member Functions
void set_global_value (const std::string &key, const std::string &value)
void remove_global_value (const std::string &key)
std::optional< std::string > maybe_get_global_value (const std::string &key) const
std::string get_global_value (const std::string &key) const
std::unordered_map< std::string, std::string > get_global_values () const
void clear_global_values ()
void set_global_values (std::unordered_map< std::string, std::string > input)
void unserialize (JsonObject &jo)
void serialize (JsonOut &jsout) const
Static Public Member Functions
static void load_migrations (const JsonObject &jo, const std::string_view &src)
Public Attributes
std::map< std::string, std::string > migrations
Private Attributes
std::unordered_map< std::string, std::string > global_values
Detailed Description
Definition at line 19 of file global_vars.h.
Member Function Documentation
clear_global_values()
void global_variables::clear_global_values () inline
Definition at line 44 of file global_vars.h.
{
             global_values.clear();
         }
References global_values.
Referenced by game::setup().
get_global_value()
std::string global_variables::get_global_value (const std::string & key) const inline
Definition at line 36 of file global_vars.h.
{
             return maybe_get_global_value( key ).value_or( std::string{} );
         }
References maybe_get_global_value().
Referenced by parse_tags().
get_global_values()
std::unordered_map<std::string, std::string> global_variables::get_global_values () const inline
Definition at line 40 of file global_vars.h.
{
             return global_values;
         }
References global_values.
Referenced by debug_menu::write_global_vars().
load_migrations()
void global_variables::load_migrations (const JsonObject & jo, const std::string_view & src) static
Definition at line 1600 of file savegame.cpp.
 {
     const std::string from( jo.get_string( "from" ) );
     const std::string to = jo.has_string( "to" )
                            ? jo.get_string( "to" )
                            : "NULL_VALUE";
     get_globals().migrations.emplace( from, to );
 }
References get_globals(), JsonObject::get_string(), JsonObject::has_string(), and migrations.
Referenced by DynamicDataLoader::initialize().
maybe_get_global_value()
std::optional<std::string> global_variables::maybe_get_global_value (const std::string & key) const inline
Definition at line 31 of file global_vars.h.
{
             auto it = global_values.find( key );
             return it == global_values.end() ? std::nullopt : std::optional<std::string> { it->second };
         }
References global_values.
Referenced by get_global_value(), and maybe_read_var_value().
remove_global_value()
void global_variables::remove_global_value (const std::string & key) inline
Definition at line 27 of file global_vars.h.
{
             global_values.erase( key );
         }
References global_values.
serialize()
void global_variables::serialize (JsonOut & jsout) const
Definition at line 1595 of file savegame.cpp.
 {
     jsout.member( "global_vals", global_values );
 }
References global_values, and JsonOut::member().
Referenced by game::serialize().
set_global_value()
void global_variables::set_global_value (const std::string & key, const std::string & value) inline
Definition at line 23 of file global_vars.h.
{
             global_values[ key ] = value;
         }
References global_values.
Referenced by debug_menu::edit_global_vars(), set_queued_points(), and write_var_value().
set_global_values()
void global_variables::set_global_values (std::unordered_map< std::string, std::string > input) inline
Definition at line 48 of file global_vars.h.
{
             global_values = std::move( input );
         }
References global_values.
unserialize()
void global_variables::unserialize (JsonObject & jo)
Definition at line 1491 of file savegame.cpp.
 {
     jo.read( "global_vals", global_values );
     // potentially migrate some variable names
     for( std::pair<std::string, std::string> migration : migrations ) {
         if( global_values.count( migration.first ) != 0 ) {
             auto extracted = global_values.extract( migration.first );
             extracted.key() = migration.second;
             global_values.insert( std::move( extracted ) );
         }
     }
 }
References global_values, migrations, and JsonObject::read().
Referenced by game::unserialize().
Member Data Documentation
global_values
std::unordered_map<std::string, std::string> global_variables::global_values private
Definition at line 58 of file global_vars.h.
Referenced by clear_global_values(), get_global_values(), maybe_get_global_value(), remove_global_value(), serialize(), set_global_value(), set_global_values(), and unserialize().
migrations
std::map<std::string, std::string> global_variables::migrations
Definition at line 54 of file global_vars.h.
Referenced by load_migrations(), and unserialize().
The documentation for this class was generated from the following files:
src/global_vars.h
src/savegame.cpp