Cataclysm DDA: faction_manager Class Reference
faction_manager Class Reference
#include <faction.h>
Public Member Functions
void deserialize (const JsonValue &jv)
void serialize (JsonOut &jsout) const
void clear ()
void create_if_needed ()
void display () const
faction * add_new_faction (const std::string &name_new, const faction_id &id_new, const faction_id &template_id)
void remove_faction (const faction_id &id)
const std::map< faction_id, faction > & all () const
faction * get (const faction_id &id, bool complain=true)
Private Attributes
std::map< faction_id, faction > factions
Detailed Description
Definition at line 154 of file faction.h.
Member Function Documentation
add_new_faction()
faction * faction_manager::add_new_faction (const std::string & name_new, const faction_id & id_new, const faction_id & template_id)
Definition at line 492 of file faction.cpp.
 {
     for( const faction_template &fac_temp : npc_factions::all_templates ) {
         if( template_id == fac_temp.id ) {
             faction fac( fac_temp );
             fac.name = name_new;
             fac.id = id_new;
             factions[fac.id] = fac;
             return &factions[fac.id];
         }
     }
     return nullptr;
 }
References npc_factions::all_templates, factions, faction_template::id, string_id< T >::id(), and faction_template::name.
all()
const std::map<faction_id, faction>& faction_manager::all () const inline
Definition at line 169 of file faction.h.
{
             return factions;
         }
References factions.
clear()
void faction_manager::clear ()
Definition at line 463 of file faction.cpp.
 {
     factions.clear();
 }
References factions.
create_if_needed()
void faction_manager::create_if_needed ()
Definition at line 482 of file faction.cpp.
 {
     if( !factions.empty() ) {
         return;
     }
     for( const faction_template &fac_temp : npc_factions::all_templates ) {
         factions[fac_temp.id] = faction( fac_temp );
     }
 }
References npc_factions::all_templates, faction, and factions.
deserialize()
void faction_manager::deserialize (const JsonValue & jv)
Definition at line 1646 of file savegame.cpp.
 {
     if( jv.test_object() ) {
         // whoops - this recovers factions saved under the wrong format.
         JsonObject jo = jv;
         for( JsonMember jm : jo ) {
             faction add_fac;
             add_fac.id = faction_id( jm.name() );
             jm.read( add_fac );
             faction *old_fac = get( add_fac.id, false );
             if( old_fac ) {
                 *old_fac = add_fac;
                 // force a revalidation of add_fac
                 get( add_fac.id, false );
             } else {
                 factions[add_fac.id] = add_fac;
             }
         }
     } else if( jv.test_array() ) {
         // how it should have been serialized.
         JsonArray ja = jv;
         for( JsonValue jav : ja ) {
             faction add_fac;
             jav.read( add_fac );
             faction *old_fac = get( add_fac.id, false );
             if( old_fac ) {
                 *old_fac = add_fac;
                 // force a revalidation of add_fac
                 get( add_fac.id, false );
             } else {
                 factions[add_fac.id] = add_fac;
             }
         }
     }
 }
References faction_id, factions, get(), faction_template::id, JsonValue::test_array(), and JsonValue::test_object().
display()
void faction_manager::display () const
Definition at line 818 of file faction.cpp.
 {
     catacurses::window w_missions;
     int entries_per_page = 0;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         const point term( TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0,
                           TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0 );
         w_missions = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                          point( term.y, term.x ) );
         entries_per_page = FULL_SCREEN_HEIGHT - 4;
         ui.position_from_window( w_missions );
     } );
     ui.mark_resize();
     enum class tab_mode : int {
         TAB_MYFACTION = 0,
         TAB_FOLLOWERS,
         TAB_OTHERFACTIONS,
         TAB_LORE,
         TAB_CREATURES,
         NUM_TABS,
         FIRST_TAB = 0,
         LAST_TAB = NUM_TABS - 1
     };
     g->validate_camps();
     g->validate_npc_followers();
     tab_mode tab = tab_mode::FIRST_TAB;
     size_t selection = 0;
     input_context ctxt( "FACTION_MANAGER" );
     ctxt.register_action( "ANY_INPUT" );
     ctxt.register_navigate_ui_list();
     ctxt.register_leftright();
     ctxt.register_action( "NEXT_TAB" );
     ctxt.register_action( "PREV_TAB" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     std::vector<npc *> followers;
     std::vector<const faction *> valfac; // Factions that we know of.
     npc *guy = nullptr;
     const faction *cur_fac = nullptr;
     bool interactable = false;
     bool radio_interactable = false;
     basecamp *camp = nullptr;
     std::vector<basecamp *> camps;
     size_t active_vec_size = 0;
     std::vector<std::pair<snippet_id, std::string>> lore; // Lore we have seen
     std::pair<snippet_id, std::string> *snippet = nullptr;
     std::vector<mtype_id> creatures; // Creatures we've recorded
     mtype_id cur_creature = mtype_id::NULL_ID();
     ui.on_redraw( [&]( const ui_adaptor & ) {
         werase( w_missions );
         for( int i = 3; i < FULL_SCREEN_HEIGHT - 1; i++ ) {
             mvwputch( w_missions, point( 30, i ), BORDER_COLOR, LINE_XOXO );
         }
         const std::vector<std::pair<tab_mode, std::string>> tabs = {
             { tab_mode::TAB_MYFACTION, _( "YOUR FACTION" ) },
             { tab_mode::TAB_FOLLOWERS, _( "YOUR FOLLOWERS" ) },
             { tab_mode::TAB_OTHERFACTIONS, _( "OTHER FACTIONS" ) },
             { tab_mode::TAB_LORE, _( "LORE" ) },
             { tab_mode::TAB_CREATURES, _( "CREATURES" ) },
         };
         draw_tabs( w_missions, tabs, tab );
         draw_border_below_tabs( w_missions );
         mvwputch( w_missions, point( 30, 2 ), BORDER_COLOR,
                   tab == tab_mode::TAB_FOLLOWERS ? ' ' : LINE_OXXX ); // ^|^
         mvwputch( w_missions, point( 30, FULL_SCREEN_HEIGHT - 1 ), BORDER_COLOR, LINE_XXOX ); // _|_
         const nc_color col = c_white;
         // entries_per_page * page number
         const size_t top_of_page = entries_per_page * ( selection / entries_per_page );
         switch( tab ) {
             case tab_mode::TAB_MYFACTION: {
                 const std::string no_camp = _( "You have no camps" );
                 if( active_vec_size > 0 ) {
                     draw_scrollbar( w_missions, selection, entries_per_page, active_vec_size,
                                     point( 0, 3 ) );
                     for( size_t i = top_of_page; i < active_vec_size && i < top_of_page + entries_per_page; i++ ) {
                         const int y = i - top_of_page + 3;
                         trim_and_print( w_missions, point( 1, y ), 28, selection == i ? hilite( col ) : col,
                                         camps[i]->camp_name() );
                     }
                     if( camp ) {
                         camp->faction_display( w_missions, 31 );
                     } else {
                         mvwprintz( w_missions, point( 31, 4 ), c_light_red, no_camp );
                     }
                     break;
                 } else {
                     mvwprintz( w_missions, point( 31, 4 ), c_light_red, no_camp );
                 }
             }
             break;
             case tab_mode::TAB_FOLLOWERS: {
                 const std::string no_ally = _( "You have no followers" );
                 if( !followers.empty() ) {
                     draw_scrollbar( w_missions, selection, entries_per_page, active_vec_size,
                                     point( 0, 3 ) );
                     for( size_t i = top_of_page; i < active_vec_size && i < top_of_page + entries_per_page; i++ ) {
                         const int y = i - top_of_page + 3;
                         trim_and_print( w_missions, point( 1, y ), 28, selection == i ? hilite( col ) : col,
                                         followers[i]->disp_name() );
                     }
                     if( guy ) {
                         int retval = guy->faction_display( w_missions, 31 );
                         if( retval == 2 ) {
                             radio_interactable = true;
                         } else if( retval == 1 ) {
                             interactable = true;
                         }
                     } else {
                         mvwprintz( w_missions, point( 31, 4 ), c_light_red, no_ally );
                     }
                     break;
                 } else {
                     mvwprintz( w_missions, point( 31, 4 ), c_light_red, no_ally );
                 }
             }
             break;
             case tab_mode::TAB_OTHERFACTIONS: {
                 const std::string no_fac = _( "You don't know of any factions." );
                 if( active_vec_size > 0 ) {
                     draw_scrollbar( w_missions, selection, entries_per_page, active_vec_size,
                                     point( 0, 3 ) );
                     for( size_t i = top_of_page; i < active_vec_size && i < top_of_page + entries_per_page; i++ ) {
                         const int y = i - top_of_page + 3;
                         trim_and_print( w_missions, point( 1, y ), 28, selection == i ? hilite( col ) : col,
                                         _( valfac[i]->name ) );
                     }
                     if( cur_fac ) {
                         cur_fac->faction_display( w_missions, 31 );
                     } else {
                         mvwprintz( w_missions, point( 31, 4 ), c_light_red, no_fac );
                     }
                     break;
                 } else {
                     mvwprintz( w_missions, point( 31, 4 ), c_light_red, no_fac );
                 }
             }
             break;
             case tab_mode::TAB_LORE: {
                 const std::string no_lore = _( "You haven't learned anything about the world." );
                 if( active_vec_size > 0 ) {
                     draw_scrollbar( w_missions, selection, entries_per_page, active_vec_size,
                                     point( 0, 3 ) );
                     for( size_t i = top_of_page; i < active_vec_size && i < top_of_page + entries_per_page; i++ ) {
                         const int y = i - top_of_page + 3;
                         trim_and_print( w_missions, point( 1, y ), 28, selection == i ? hilite( col ) : col,
                                         _( lore[i].second ) );
                     }
                     if( snippet != nullptr ) {
                         int y = 2;
                         fold_and_print( w_missions, point( 31, ++y ), getmaxx( w_missions ) - 31 - 2, c_light_gray,
                                         SNIPPET.get_snippet_by_id( snippet->first ).value().translated() );
                     } else {
                         mvwprintz( w_missions, point( 31, 4 ), c_light_red, no_lore );
                     }
                     break;
                 } else {
                     mvwprintz( w_missions, point( 31, 4 ), c_light_red, no_lore );
                 }
             }
             break;
             case tab_mode::TAB_CREATURES: {
                 const std::string no_creatures =
                     _( "You haven't recorded sightings of any creatures.  Taking photos can be a good way to keep track of them." );
                 const int w = getmaxx( w_missions ) - 31 - 2;
                 if( active_vec_size > 0 ) {
                     draw_scrollbar( w_missions, selection, entries_per_page, active_vec_size,
                                     point( 0, 3 ) );
                     for( size_t i = top_of_page; i < active_vec_size && i < top_of_page + entries_per_page; i++ ) {
                         const int y = i - top_of_page + 3;
                         trim_and_print( w_missions, point( 1, y ), 28, selection == i ? hilite( col ) : col,
                                         string_format( "%s  %s", colorize( creatures[i]->sym,
                                                        selection == i ? hilite( creatures[i]->color ) : creatures[i]->color ),
                                                        creatures[i]->nname() ) );
                     }
                     if( !cur_creature.is_null() ) {
                         cur_creature->faction_display( w_missions, point( 31, 3 ), w );
                     } else {
                         fold_and_print( w_missions, point( 31, 4 ), w, c_light_red, no_creatures );
                     }
                     break;
                 } else {
                     fold_and_print( w_missions, point( 31, 4 ), w, c_light_red, no_creatures );
                 }
             }
             default:
                 break;
         }
         wnoutrefresh( w_missions );
     } );
     avatar &player_character = get_avatar();
     while( true ) {
         // create a list of NPCs, visible and the ones on overmapbuffer
         followers.clear();
         for( const character_id &elem : g->get_follower_list() ) {
             shared_ptr_fast<npc> npc_to_get = overmap_buffer.find_npc( elem );
             if( !npc_to_get ) {
                 continue;
             }
             npc *npc_to_add = npc_to_get.get();
             followers.push_back( npc_to_add );
         }
         valfac.clear();
         for( const auto &elem : g->faction_manager_ptr->all() ) {
             if( elem.second.known_by_u && elem.second.id != faction_your_followers ) {
                 valfac.push_back( &elem.second );
             }
         }
         guy = nullptr;
         cur_fac = nullptr;
         snippet = nullptr;
         cur_creature = mtype_id::NULL_ID();
         interactable = false;
         radio_interactable = false;
         camp = nullptr;
         // create a list of faction camps
         camps.clear();
         for( tripoint_abs_omt elem : player_character.camps ) {
             std::optional<basecamp *> p = overmap_buffer.find_camp( elem.xy() );
             if( !p ) {
                 continue;
             }
             basecamp *temp_camp = *p;
             camps.push_back( temp_camp );
         }
         lore.clear();
         for( const auto &elem : player_character.get_snippets() ) {
             std::optional<translation> name = SNIPPET.get_name_by_id( elem );
             if( name.has_value() ) {
                 if( !name->empty() ) {
                     lore.emplace_back( elem, name->translated() );
                 } else {
                     lore.emplace_back( elem, elem.str() );
                 }
             }
         }
         auto compare_second =
             []( const std::pair<snippet_id, std::string> &a,
         const std::pair<snippet_id, std::string> &b ) {
             return localized_compare( a.second, b.second );
         };
         std::sort( lore.begin(), lore.end(), compare_second );
         if( tab < tab_mode::FIRST_TAB || tab >= tab_mode::NUM_TABS ) {
             debugmsg( "The sanity check failed because tab=%d", static_cast<int>( tab ) );
             tab = tab_mode::FIRST_TAB;
         }
         creatures.clear();
         creatures.reserve( player_character.get_known_monsters().size() );
         creatures.insert( creatures.end(), player_character.get_known_monsters().begin(),
                           player_character.get_known_monsters().end() );
         std::sort( creatures.begin(), creatures.end(), []( const mtype_id & a, const mtype_id & b ) {
             return localized_compare( a->nname(), b->nname() );
         } );
         active_vec_size = camps.size();
         if( tab == tab_mode::TAB_FOLLOWERS ) {
             if( selection < followers.size() ) {
                 guy = followers[selection];
             }
             active_vec_size = followers.size();
         } else if( tab == tab_mode::TAB_MYFACTION ) {
             if( selection < camps.size() ) {
                 camp = camps[selection];
             }
             active_vec_size = camps.size();
         } else if( tab == tab_mode::TAB_OTHERFACTIONS ) {
             if( selection < valfac.size() ) {
                 cur_fac = valfac[selection];
             }
             active_vec_size = valfac.size();
         } else if( tab == tab_mode::TAB_LORE ) {
             if( selection < lore.size() ) {
                 snippet = &lore[selection];
             }
             active_vec_size = lore.size();
         } else if( tab == tab_mode::TAB_CREATURES ) {
             if( selection < creatures.size() ) {
                 cur_creature = creatures[selection];
             }
             active_vec_size = creatures.size();
         }
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         if( action == "LEFT" || action == "PREV_TAB" || action == "RIGHT" || action == "NEXT_TAB" ) {
             // necessary to use inc_clamp_wrap
             static_assert( static_cast<int>( tab_mode::FIRST_TAB ) == 0 );
             tab = inc_clamp_wrap( tab, action == "RIGHT" || action == "NEXT_TAB", tab_mode::NUM_TABS );
             selection = 0;
         } else if( navigate_ui_list( action, selection, 10, active_vec_size, true ) ) {
         } else if( action == "CONFIRM" ) {
             if( tab == tab_mode::TAB_FOLLOWERS && guy ) {
                 if( guy->has_companion_mission() ) {
                     talk_function::basecamp_mission( *guy );
                 } else if( interactable || radio_interactable ) {
                     player_character.talk_to( get_talker_for( *guy ), radio_interactable );
                 }
             } else if( tab == tab_mode::TAB_MYFACTION && camp ) {
                 camp->query_new_name();
             }
         } else if( action == "QUIT" ) {
             break;
         }
     }
 }
References _, a, action, b, talk_function::basecamp_mission(), BORDER_COLOR, c_light_gray, c_light_red, c_white, Character::camps, color(), colorize(), debugmsg, draw_border_below_tabs(), draw_scrollbar(), draw_tabs(), mtype::faction_display(), basecamp::faction_display(), faction::faction_display(), npc::faction_display(), faction_your_followers, overmapbuffer::find_camp(), overmapbuffer::find_npc(), fold_and_print(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, g, get_avatar(), Character::get_known_monsters(), snippet_library::get_name_by_id(), snippet_library::get_snippet_by_id(), avatar::get_snippets(), get_talker_for(), catacurses::getmaxx(), input_context::handle_input(), npc::has_companion_mission(), hilite(), inc_clamp_wrap(), string_id< T >::is_null(), LINE_OXXX, LINE_XOXO, LINE_XXOX, localized_compare, mvwprintz(), mvwputch(), om_direction::name(), navigate_ui_list(), catacurses::newwin(), string_id< mtype >::NULL_ID(), overmap_buffer, point, basecamp::query_new_name(), ui_manager::redraw(), input_context::register_action(), input_context::register_leftright(), input_context::register_navigate_ui_list(), second, faction_template::size, SNIPPET, string_format(), keycode::tab, avatar::talk_to(), TERMX, TERMY, trim_and_print(), catacurses::werase(), catacurses::wnoutrefresh(), point::x, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and point::y.
get()
faction * faction_manager::get (const faction_id & id, bool complain = true)
Definition at line 507 of file faction.cpp.
 {
     if( id.is_null() ) {
         return get( faction_no_faction );
     }
     for( auto &elem : factions ) {
         if( elem.first == id ) {
             if( !elem.second.validated ) {
                 for( const faction_template &fac_temp : npc_factions::all_templates ) {
                     if( fac_temp.id == id ) {
                         elem.second.currency = fac_temp.currency;
                         elem.second.price_rules = fac_temp.price_rules;
                         elem.second.lone_wolf_faction = fac_temp.lone_wolf_faction;
                         elem.second.name = fac_temp.name;
                         elem.second.desc = fac_temp.desc;
                         elem.second.mon_faction = fac_temp.mon_faction;
                         elem.second.epilogue_data = fac_temp.epilogue_data;
                         for( const auto &rel_data : fac_temp.relations ) {
                             if( elem.second.relations.find( rel_data.first ) == elem.second.relations.end() ) {
                                 elem.second.relations[rel_data.first] = rel_data.second;
                             }
                         }
                         break;
                     }
                 }
                 elem.second.validated = true;
             }
             return &elem.second;
         }
     }
     for( const faction_template &elem : npc_factions::all_templates ) {
         // id isn't already in factions map, so load in the template.
         if( elem.id == id ) {
             factions[elem.id] = faction( elem );
             if( !factions.empty() ) {
                 factions[elem.id].validated = true;
             }
             return &factions[elem.id];
         }
     }
     // Sometimes we add new IDs to the map, sometimes we want to check if its already there.
     if( complain ) {
         debugmsg( "Requested non-existing faction '%s'", id.str() );
     }
     return nullptr;
 }
References npc_factions::all_templates, debugmsg, faction, faction_no_faction, and factions.
Referenced by deserialize().
remove_faction()
void faction_manager::remove_faction (const faction_id & id)
Definition at line 468 of file faction.cpp.
 {
     if( id.str().empty() || id == faction_no_faction ) {
         return;
     }
     for( auto it = factions.cbegin(), next_it = it; it != factions.cend(); it = next_it ) {
         ++next_it;
         if( id == it->first ) {
             factions.erase( it );
             break;
         }
     }
 }
References faction_no_faction, and factions.
serialize()
void faction_manager::serialize (JsonOut & jsout) const
Definition at line 1585 of file savegame.cpp.
 {
     std::vector<faction> local_facs;
     local_facs.reserve( factions.size() );
     for( const auto &elem : factions ) {
         local_facs.push_back( elem.second );
     }
     jsout.write( local_facs );
 }
References factions, and JsonOut::write().
Member Data Documentation
factions
std::map<faction_id, faction> faction_manager::factions private
Definition at line 157 of file faction.h.
Referenced by add_new_faction(), all(), clear(), create_if_needed(), deserialize(), get(), remove_faction(), and serialize().
The documentation for this class was generated from the following files:
src/faction.h
src/faction.cpp
src/savegame.cpp