Cataclysm DDA: ma_buff Class Reference
ma_buff Class Reference
#include <martialarts.h>
Public Member Functions
ma_buff ()
void apply_buff (Character &u) const
bool is_valid_character (const Character &u) const
void apply_character (Character &u) const
int block_effectiveness_bonus (const Character &u) const
int hit_bonus (const Character &u) const
int critical_hit_chance_bonus (const Character &u) const
int dodge_bonus (const Character &u) const
int speed_bonus (const Character &u) const
int block_bonus (const Character &u) const
int arpen_bonus (const Character &u, const damage_type_id &dt) const
int armor_bonus (const Character &guy, const damage_type_id &dt) const
float damage_bonus (const Character &u, const damage_type_id &dt) const
float damage_mult (const Character &u, const damage_type_id &dt) const
bool is_melee_bash_damage_cap_bonus () const
bool is_quiet () const
bool can_melee () const
bool is_stealthy () const
bool has_flag (const json_character_flag &flag) const
efftype_id get_effect_id () const
std::string get_description (bool passive=false) const
void load (const JsonObject &jo, std::string_view src)
Static Public Member Functions
static const ma_buff * from_effect (const effect &eff)
Public Attributes
mabuff_id id
std::vector< std::pair< mabuff_id, mod_id > > src
bool was_loaded = false
translation name
translation description
ma_requirements reqs
cata::flat_set< json_character_flag > flags
time_duration buff_duration = 0_turns
int max_stacks = 0
bool persists = false
int dodges_bonus = 0
int blocks_bonus = 0
bonus_container bonuses
All kinds of bonuses by types to damage, hit, armor etc.
bool quiet = false
bool melee_allowed = false
bool melee_bash_damage_cap_bonus = false
bool strictly_melee = false
bool stealthy = false
Detailed Description
Definition at line 218 of file martialarts.h.
Constructor & Destructor Documentation
ma_buff()
ma_buff::ma_buff ()
Definition at line 861 of file martialarts.cpp.
     : buff_duration( 1_turns )
 {
     max_stacks = 1; // total number of stacks this buff can have
     dodges_bonus = 0; // extra dodges, like karate
     blocks_bonus = 0; // extra blocks, like karate
 }
References blocks_bonus, dodges_bonus, and max_stacks.
Member Function Documentation
apply_buff()
void ma_buff::apply_buff (Character & u) const
Definition at line 886 of file martialarts.cpp.
 {
     u.add_effect( get_effect_id(), time_duration::from_turns( buff_duration ) );
 }
References buff_duration, time_duration::from_turns(), get_effect_id(), and u.
Referenced by simultaneous_add().
apply_character()
void ma_buff::apply_character (Character & u) const
Definition at line 896 of file martialarts.cpp.
 {
     u.mod_num_dodges_bonus( dodges_bonus );
     u.set_num_blocks_bonus( u.get_num_blocks_bonus() + blocks_bonus );
 }
References blocks_bonus, dodges_bonus, and u.
armor_bonus()
int ma_buff::armor_bonus (const Character & guy, const damage_type_id & dt) const
Definition at line 930 of file martialarts.cpp.
 {
     return bonuses.get_flat( guy, affected_stat::ARMOR, dt );
 }
References ARMOR, bonuses, and bonus_container::get_flat().
arpen_bonus()
int ma_buff::arpen_bonus (const Character & u, const damage_type_id & dt) const
Definition at line 918 of file martialarts.cpp.
 {
     return bonuses.get_flat( u, affected_stat::ARMOR_PENETRATION, dt );
 }
References ARMOR_PENETRATION, bonuses, bonus_container::get_flat(), and u.
block_bonus()
int ma_buff::block_bonus (const Character & u) const
Definition at line 914 of file martialarts.cpp.
 {
     return bonuses.get_flat( u, affected_stat::BLOCK );
 }
References BLOCK, bonuses, bonus_container::get_flat(), and u.
block_effectiveness_bonus()
int ma_buff::block_effectiveness_bonus (const Character & u) const
Definition at line 922 of file martialarts.cpp.
 {
     return bonuses.get_flat( u, affected_stat::BLOCK_EFFECTIVENESS );
 }
References BLOCK_EFFECTIVENESS, bonuses, bonus_container::get_flat(), and u.
can_melee()
bool ma_buff::can_melee () const
Definition at line 965 of file martialarts.cpp.
 {
     return melee_allowed;
 }
References melee_allowed.
critical_hit_chance_bonus()
int ma_buff::critical_hit_chance_bonus (const Character & u) const
Definition at line 906 of file martialarts.cpp.
 {
     return bonuses.get_flat( u, affected_stat::CRITICAL_HIT_CHANCE );
 }
References bonuses, CRITICAL_HIT_CHANCE, bonus_container::get_flat(), and u.
damage_bonus()
float ma_buff::damage_bonus (const Character & u, const damage_type_id & dt) const
Definition at line 934 of file martialarts.cpp.
 {
     return bonuses.get_flat( u, affected_stat::DAMAGE, dt );
 }
References bonuses, DAMAGE, bonus_container::get_flat(), and u.
damage_mult()
float ma_buff::damage_mult (const Character & u, const damage_type_id & dt) const
Definition at line 938 of file martialarts.cpp.
 {
     return bonuses.get_mult( u, affected_stat::DAMAGE, dt );
 }
References bonuses, DAMAGE, bonus_container::get_mult(), and u.
dodge_bonus()
int ma_buff::dodge_bonus (const Character & u) const
Definition at line 910 of file martialarts.cpp.
 {
     return bonuses.get_flat( u, affected_stat::DODGE );
 }
References bonuses, DODGE, bonus_container::get_flat(), and u.
from_effect()
const ma_buff * ma_buff::from_effect (const effect & eff) static
Definition at line 876 of file martialarts.cpp.
 {
     const std::string &id = eff.get_effect_type()->id.str();
     // Same as in get_effect_id!
     if( id.compare( 0, 7, "mabuff:" ) != 0 ) {
         return nullptr;
     }
     return &mabuff_id( id.substr( 7 ) ).obj();
 }
References game_menus::inv::compare(), effect::get_effect_type(), effect_type::id, string_id< T >::obj(), and string_id< T >::str().
Referenced by accumulate_ma_buff_effects(), Character::hardcoded_effects(), and search_ma_buff_effect().
get_description()
std::string ma_buff::get_description (bool passive = false) const
Definition at line 970 of file martialarts.cpp.
 {
     std::string dump;
     dump += string_format( _( "<bold>Buff technique:</bold> %s" ), name ) + "\n";
     std::string temp = bonuses.get_description();
     if( !temp.empty() ) {
         dump += std::string( npgettext( "martial arts buff desc", "<bold>Bonus:</bold> ",
                                         "<bold>Bonus/stack:</bold> ", max_stacks ) ) + "\n" + temp;
     }
     dump += reqs.get_description( true );
     if( max_stacks > 1 ) {
         dump += string_format( _( "* Will <info>stack</info> up to <stat>%d</stat> times" ),
                                max_stacks ) + "\n";
     }
     const int turns = to_turns<int>( buff_duration );
     if( !passive && turns ) {
         dump += string_format( n_gettext( "* Will <info>last</info> for <stat>%d turn</stat>",
                                           "* Will <info>last</info> for <stat>%d turns</stat>",
                                           turns ),
                                turns ) + "\n";
     }
     if( dodges_bonus > 0 ) {
         dump += string_format(
                     n_gettext( "* Will give a <good>+%s</good> bonus to <info>dodge</info> for the stack",
                                "* Will give a <good>+%s</good> bonus to <info>dodge</info> per stack",
                                max_stacks ),
                     dodges_bonus ) + "\n";
     } else if( dodges_bonus < 0 ) {
         dump += string_format(
                     n_gettext( "* Will give a <bad>%s</bad> penalty to <info>dodge</info> for the stack",
                                "* Will give a <bad>%s</bad> penalty to <info>dodge</info> per stack",
                                max_stacks ),
                     dodges_bonus ) + "\n";
     }
     if( blocks_bonus > 0 ) {
         dump += string_format(
                     n_gettext( "* Will give a <good>+%s</good> bonus to <info>block</info> for the stack",
                                "* Will give a <good>+%s</good> bonus to <info>block</info> per stack",
                                max_stacks ),
                     blocks_bonus ) + "\n";
     } else if( blocks_bonus < 0 ) {
         dump += string_format(
                     n_gettext( "* Will give a <bad>%s</bad> penalty to <info>block</info> for the stack",
                                "* Will give a <bad>%s</bad> penalty to <info>block</info> per stack",
                                max_stacks ),
                     blocks_bonus ) + "\n";
     }
     if( quiet ) {
         dump += _( "* Attacks will be completely <info>silent</info>" ) + std::string( "\n" );
     }
     if( stealthy ) {
         dump += _( "* Movement will make <info>less noise</info>" ) + std::string( "\n" );
     }
     return dump;
 }
References _, blocks_bonus, bonuses, buff_duration, dodges_bonus, bonus_container::get_description(), ma_requirements::get_description(), max_stacks, n_gettext, name, npgettext, passive, quiet, reqs, stealthy, string_format(), and temp.
get_effect_id()
efftype_id ma_buff::get_effect_id () const
Definition at line 871 of file martialarts.cpp.
 {
     return efftype_id( std::string( "mabuff:" ) + id.str() );
 }
References efftype_id.
Referenced by apply_buff(), and ma_buff_effect_type::ma_buff_effect_type().
has_flag()
bool ma_buff::has_flag (const json_character_flag & flag) const
Definition at line 955 of file martialarts.cpp.
 {
     for( const json_character_flag &q : flags ) {
         if( q == flag ) {
             return true;
         }
     }
     return false;
 }
References flags.
hit_bonus()
int ma_buff::hit_bonus (const Character & u) const
Definition at line 902 of file martialarts.cpp.
 {
     return bonuses.get_flat( u, affected_stat::HIT );
 }
References bonuses, bonus_container::get_flat(), HIT, and u.
is_melee_bash_damage_cap_bonus()
bool ma_buff::is_melee_bash_damage_cap_bonus () const
Definition at line 942 of file martialarts.cpp.
 {
     return melee_bash_damage_cap_bonus;
 }
References melee_bash_damage_cap_bonus.
is_quiet()
bool ma_buff::is_quiet () const
Definition at line 946 of file martialarts.cpp.
 {
     return quiet;
 }
References quiet.
is_stealthy()
bool ma_buff::is_stealthy () const
Definition at line 950 of file martialarts.cpp.
 {
     return stealthy;
 }
References stealthy.
is_valid_character()
bool ma_buff::is_valid_character (const Character & u) const
Definition at line 891 of file martialarts.cpp.
 {
     return reqs.is_valid_character( u );
 }
References ma_requirements::is_valid_character(), reqs, and u.
Referenced by simultaneous_add().
load()
void ma_buff::load (const JsonObject & jo, std::string_view src)
Definition at line 301 of file martialarts.cpp.
 {
     mandatory( jo, was_loaded, "name", name );
     mandatory( jo, was_loaded, "description", description );
     optional( jo, was_loaded, "buff_duration", buff_duration, 2_turns );
     optional( jo, was_loaded, "max_stacks", max_stacks, 1 );
     optional( jo, was_loaded, "persists", persists, false );
     optional( jo, was_loaded, "bonus_dodges", dodges_bonus, 0 );
     optional( jo, was_loaded, "bonus_blocks", blocks_bonus, 0 );
     optional( jo, was_loaded, "quiet", quiet, false );
     optional( jo, was_loaded, "stealthy", stealthy, false );
     optional( jo, was_loaded, "melee_bash_damage_cap_bonus", melee_bash_damage_cap_bonus, false );
     optional( jo, was_loaded, "flags", flags );
     reqs.load( jo, src );
     bonuses.load( jo );
 }
References blocks_bonus, bonuses, buff_duration, description, dodges_bonus, flags, bonus_container::load(), ma_requirements::load(), mandatory, max_stacks, melee_bash_damage_cap_bonus, name, optional(), persists, quiet, reqs, src, stealthy, and was_loaded.
speed_bonus()
int ma_buff::speed_bonus (const Character & u) const
Definition at line 926 of file martialarts.cpp.
 {
     return bonuses.get_flat( u, affected_stat::SPEED );
 }
References bonuses, bonus_container::get_flat(), SPEED, and u.
Member Data Documentation
blocks_bonus
int ma_buff::blocks_bonus = 0
Definition at line 282 of file martialarts.h.
Referenced by apply_character(), get_description(), load(), and ma_buff().
bonuses
bonus_container ma_buff::bonuses
All kinds of bonuses by types to damage, hit, armor etc.
Definition at line 285 of file martialarts.h.
Referenced by armor_bonus(), arpen_bonus(), block_bonus(), block_effectiveness_bonus(), critical_hit_chance_bonus(), damage_bonus(), damage_mult(), dodge_bonus(), get_description(), hit_bonus(), load(), and speed_bonus().
buff_duration
time_duration ma_buff::buff_duration = 0_turns
Definition at line 277 of file martialarts.h.
Referenced by apply_buff(), get_description(), load(), and ma_buff_effect_type::ma_buff_effect_type().
description
translation ma_buff::description
Definition at line 268 of file martialarts.h.
Referenced by load(), and ma_buff_effect_type::ma_buff_effect_type().
dodges_bonus
int ma_buff::dodges_bonus = 0
Definition at line 281 of file martialarts.h.
Referenced by apply_character(), get_description(), load(), and ma_buff().
flags
cata::flat_set<json_character_flag> ma_buff::flags
Definition at line 273 of file martialarts.h.
Referenced by has_flag(), and load().
id
mabuff_id ma_buff::id
Definition at line 264 of file martialarts.h.
max_stacks
int ma_buff::max_stacks = 0
Definition at line 278 of file martialarts.h.
Referenced by get_description(), load(), ma_buff(), and ma_buff_effect_type::ma_buff_effect_type().
melee_allowed
bool ma_buff::melee_allowed = false
Definition at line 288 of file martialarts.h.
Referenced by can_melee().
melee_bash_damage_cap_bonus
bool ma_buff::melee_bash_damage_cap_bonus = false
Definition at line 289 of file martialarts.h.
Referenced by is_melee_bash_damage_cap_bonus(), and load().
name
translation ma_buff::name
Definition at line 267 of file martialarts.h.
Referenced by get_description(), load(), and ma_buff_effect_type::ma_buff_effect_type().
persists
bool ma_buff::persists = false
Definition at line 279 of file martialarts.h.
Referenced by load().
quiet
bool ma_buff::quiet = false
Definition at line 287 of file martialarts.h.
Referenced by get_description(), is_quiet(), and load().
reqs
ma_requirements ma_buff::reqs
Definition at line 271 of file martialarts.h.
Referenced by get_description(), is_valid_character(), and load().
src
std::vector<std::pair<mabuff_id, mod_id> > ma_buff::src
Definition at line 265 of file martialarts.h.
Referenced by load().
stealthy
bool ma_buff::stealthy = false
Definition at line 291 of file martialarts.h.
Referenced by get_description(), is_stealthy(), and load().
strictly_melee
bool ma_buff::strictly_melee = false
Definition at line 290 of file martialarts.h.
was_loaded
bool ma_buff::was_loaded = false
Definition at line 266 of file martialarts.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/martialarts.h
src/martialarts.cpp