Cataclysm DDA: npc_attack_spell Class Reference
npc_attack_spell Class Reference
The type of npc_attack that is a spell.
#include <npc_attack.h>
Public Member Functions
npc_attack_spell (const spell_id &attack_spell_id)
npc_attack_rating evaluate (const npc &source, const Creature *target) const override
Parameters: source - the npc making the attack target - the desired target of the npc.
std::vector< npc_attack_rating > all_evaluations (const npc &source, const Creature *target) const override
For debug information.
void use (npc &source, const tripoint &location) const override
Public Member Functions inherited from npc_attack
virtual ~npc_attack ()=default
Private Member Functions
bool can_use (const npc &source) const
int base_time_penalty (const npc &source) const
npc_attack_rating evaluate_tripoint (const npc &source, const Creature *target, const tripoint &location) const
Private Attributes
const spell_id attack_spell_id
Detailed Description
The type of npc_attack that is a spell.
Assumption: if we made it this far, the npc is able to cast the spell.
Definition at line 63 of file npc_attack.h.
Constructor & Destructor Documentation
npc_attack_spell()
npc_attack_spell::npc_attack_spell (const spell_id & attack_spell_id) inline explicit
Definition at line 67 of file npc_attack.h.
 : attack_spell_id( attack_spell_id ) {}
Member Function Documentation
all_evaluations()
std::vector< npc_attack_rating > npc_attack_spell::all_evaluations (const npc & source, const Creature * target) const override virtual
For debug information.
returns all evaluated effectivenesses. This is abstracted out in evaluate() as it's faster to not use a container
Implements npc_attack.
Definition at line 132 of file npc_attack.cpp.
 {
     const spell &attack_spell = source.magic->get_spell( attack_spell_id );
     std::vector<npc_attack_rating> effectiveness;
     if( !can_use( source ) ) {
         return effectiveness;
     }
     int time_penalty = this->base_time_penalty( source );
     const std::vector<tripoint> targetable_points = attack_spell.targetable_locations( source );
     for( const tripoint &targetable_point : targetable_points ) {
         npc_attack_rating effectiveness_at_point = evaluate_tripoint(
                     source, target, targetable_point );
         effectiveness_at_point -= time_penalty;
         effectiveness.push_back( effectiveness_at_point );
     }
     return effectiveness;
 }
References attack_spell_id, base_time_penalty(), can_use(), evaluate_tripoint(), Character::magic, and spell::targetable_locations().
base_time_penalty()
int npc_attack_spell::base_time_penalty (const npc & source) const private
Definition at line 160 of file npc_attack.cpp.
 {
     const spell &attack_spell = source.magic->get_spell( attack_spell_id );
     int time_penalty = 0;
     if( source.has_weapon() && !source.get_wielded_item()->has_flag( flag_MAGIC_FOCUS ) &&
         !attack_spell.has_flag( spell_flag::NO_HANDS ) && !source.has_flag( json_flag_SUBTLE_SPELL ) ) {
         time_penalty += npc_attack_constants::base_time_penalty;
     }
     // costs a point per second spent.
     time_penalty += std::round( attack_spell.casting_time( source ) * source.speed_rating() ) / 100.0f;
     return time_penalty;
 }
References attack_spell_id, npc_attack_constants::base_time_penalty, spell::casting_time(), flag_MAGIC_FOCUS, Character::get_wielded_item(), item::has_flag(), Character::has_flag(), spell::has_flag(), Character::has_weapon(), json_flag_SUBTLE_SPELL, Character::magic, NO_HANDS, round(), and npc::speed_rating().
Referenced by all_evaluations(), and evaluate().
can_use()
bool npc_attack_spell::can_use (const npc & source) const private
Definition at line 151 of file npc_attack.cpp.
 {
     const spell &attack_spell = source.magic->get_spell( attack_spell_id );
     // missing components or energy or something
     return attack_spell.can_cast( source ) &&
            // use the same rules as silent guns
            !( source.rules.has_flag( ally_rule::use_silent ) && attack_spell.sound_volume( source ) >= 5 );
 }
References attack_spell_id, spell::can_cast(), npc_follower_rules::has_flag(), Character::magic, npc::rules, spell::sound_volume(), and use_silent.
Referenced by all_evaluations(), and evaluate().
evaluate()
npc_attack_rating npc_attack_spell::evaluate (const npc & source, const Creature * target) const override virtual
Parameters: source - the npc making the attack target - the desired target of the npc.
valued at 100%
Implements npc_attack.
Definition at line 111 of file npc_attack.cpp.
 {
     const spell &attack_spell = source.magic->get_spell( attack_spell_id );
     npc_attack_rating effectiveness;
     if( !can_use( source ) ) {
         return effectiveness;
     }
     const int time_penalty = base_time_penalty( source );
     const std::vector<tripoint> targetable_points = attack_spell.targetable_locations( source );
     for( const tripoint &targetable_point : targetable_points ) {
         npc_attack_rating effectiveness_at_point = evaluate_tripoint(
                     source, target, targetable_point );
         effectiveness_at_point -= time_penalty;
         if( effectiveness_at_point > effectiveness ) {
             effectiveness = effectiveness_at_point;
         }
     }
     return effectiveness;
 }
References attack_spell_id, base_time_penalty(), can_use(), evaluate_tripoint(), Character::magic, and spell::targetable_locations().
Referenced by spell::select_target().
evaluate_tripoint()
npc_attack_rating npc_attack_spell::evaluate_tripoint (const npc & source, const Creature * target, const tripoint & location) const private
Definition at line 173 of file npc_attack.cpp.
 {
     const spell &attack_spell = source.magic->get_spell( attack_spell_id );
     double total_potential = 0;
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &potential_target : calculate_spell_effect_area( attack_spell, location,
             source ) ) {
         Creature *critter = creatures.creature_at( potential_target );
         if( !critter ) {
             // no critter? no damage! however, we assume fields are worth something
             if( attack_spell_id->field ) {
                 dialogue d( get_talker_for( source ), nullptr );
                 total_potential += static_cast<double>( attack_spell.field_intensity( source ) ) /
                                    static_cast<double>( attack_spell_id->field_chance.evaluate( d ) ) / 2.0;
             }
             continue;
         }
         const Creature::Attitude att = source.attitude_to( *critter );
         int damage = 0;
         if( source.sees( *critter ) ) {
             damage = attack_spell.dps( source, *critter );
         }
         const int distance_to_me = rl_dist( source.pos(), potential_target );
         const bool friendly_fire = att == Creature::Attitude::FRIENDLY &&
                                    !source.rules.has_flag( ally_rule::avoid_friendly_fire );
         int attitude_mult = 3;
         if( att == Creature::Attitude::FRIENDLY ) {
             attitude_mult = -10;
         } else if( att == Creature::Attitude::NEUTRAL || friendly_fire ) {
             // hitting a neutral creature isn't exactly desired, but it's a lot less than a friendly.
             // if friendly fire is on, we don't care too much, though if an available hit doesn't damage them it would be better.
             attitude_mult = -1;
         }
         int potential = damage * attitude_mult - distance_to_me + 1;
         if( target && critter == target ) {
             potential *= npc_attack_constants::target_modifier;
         }
         if( damage >= critter->get_hp() ) {
             potential *= npc_attack_constants::kill_modifier;
             if( att == Creature::Attitude::NEUTRAL ) {
                 // we don't care if we kill a neutral creature in one hit
                 potential = std::abs( potential );
             }
             const Creature *source_ptr = &source;
             if( att == Creature::Attitude::FRIENDLY || critter == source_ptr ) {
                 // however we under no circumstances want to kill an ally (or ourselves!)
                 return npc_attack_rating( std::nullopt, location );
             }
         }
         total_potential += potential;
     }
     return npc_attack_rating( static_cast<int>( std::round( total_potential ) ), location );
 }
References abs(), attack_spell_id, npc::attitude_to(), avoid_friendly_fire, calculate_spell_effect_area(), creature_tracker::creature_at(), spell::dps(), dbl_or_var::evaluate(), spell_type::field, spell_type::field_chance, spell::field_intensity(), Creature::FRIENDLY, get_creature_tracker(), Creature::get_hp(), get_talker_for(), npc_follower_rules::has_flag(), npc_attack_constants::kill_modifier, location, Character::magic, Creature::NEUTRAL, Creature::pos(), rl_dist(), round(), npc::rules, Character::sees(), and npc_attack_constants::target_modifier.
Referenced by all_evaluations(), and evaluate().
use()
void npc_attack_spell::use (npc & source, const tripoint & location) const override virtual
Implements npc_attack.
Definition at line 100 of file npc_attack.cpp.
 {
     spell &sp = source.magic->get_spell( attack_spell_id );
     if( source.has_weapon() && !source.get_wielded_item()->has_flag( flag_MAGIC_FOCUS ) &&
         !sp.has_flag( spell_flag::NO_HANDS ) && !source.has_flag( json_flag_SUBTLE_SPELL ) ) {
         source.unwield();
     }
     add_msg_debug( debugmode::debug_filter::DF_NPC, "%s is casting %s", source.disp_name(), sp.name() );
     source.cast_spell( sp, false, location );
 }
References add_msg_debug, attack_spell_id, Character::cast_spell(), debugmode::DF_NPC, Character::disp_name(), flag_MAGIC_FOCUS, Character::get_wielded_item(), item::has_flag(), Character::has_flag(), spell::has_flag(), Character::has_weapon(), json_flag_SUBTLE_SPELL, location, Character::magic, spell::name(), NO_HANDS, and Character::unwield().
Member Data Documentation
attack_spell_id
const spell_id npc_attack_spell::attack_spell_id private
Definition at line 65 of file npc_attack.h.
Referenced by all_evaluations(), base_time_penalty(), can_use(), evaluate(), evaluate_tripoint(), and use().
The documentation for this class was generated from the following files:
src/npc_attack.h
src/npc_attack.cpp