Cataclysm DDA: tab_manager Class Reference
tab_manager Class Reference
Public Member Functions
tab_manager (std::vector< std::string > &tab_names)
void draw (const catacurses::window &w)
bool handle_input (const std::string &action, const input_context &ctxt)
void set_up_tab_navigation (input_context &ctxt)
Public Attributes
bool complete = false
bool quit = false
tab_list position
Private Attributes
std::vector< std::string > & tab_names
std::map< size_t, inclusive_rectangle< point > > tab_map
point window_pos
Detailed Description
Definition at line 131 of file newcharacter.cpp.
Constructor & Destructor Documentation
tab_manager()
tab_manager::tab_manager (std::vector< std::string > & tab_names) inline explicit
Definition at line 141 of file newcharacter.cpp.
                                                                 : tab_names( tab_names ),
             position( tab_names ) {
         }
Member Function Documentation
draw()
void tab_manager::draw (const catacurses::window & w)
Definition at line 150 of file newcharacter.cpp.
 {
     std::pair<std::vector<std::string>, size_t> fitted_tabs = fit_tabs_to_width( getmaxx( w ),
             position.cur_index(), tab_names );
     tab_map = draw_tabs( w, fitted_tabs.first, position.cur_index() - fitted_tabs.second,
                          fitted_tabs.second );
     window_pos = point( getbegx( w ), getbegy( w ) );
     draw_border_below_tabs( w );
     for( int i = 1; i < TERMX - 1; i++ ) {
         mvwputch( w, point( i, 5 ), BORDER_COLOR, LINE_OXOX );
     }
     mvwputch( w, point( 0, 5 ), BORDER_COLOR, LINE_XXXO ); // |-
     mvwputch( w, point( TERMX - 1, 5 ), BORDER_COLOR, LINE_XOXX ); // -|
 }
References BORDER_COLOR, tab_list::cur_index(), draw_border_below_tabs(), draw_tabs(), fit_tabs_to_width(), catacurses::getbegx(), catacurses::getbegy(), catacurses::getmaxx(), LINE_OXOX, LINE_XOXX, LINE_XXXO, mvwputch(), point, position, tab_map, tab_names, TERMX, and window_pos.
Referenced by set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), and set_traits().
handle_input()
bool tab_manager::handle_input (const std::string & action, const input_context & ctxt)
Definition at line 166 of file newcharacter.cpp.
 {
     if( action == "QUIT" && query_yn( _( "Return to main menu?" ) ) ) {
         quit = true;
     } else if( action == "PREV_TAB" ) {
         position.prev();
     } else if( action == "NEXT_TAB" ) {
         position.next();
     } else if( action == "SELECT" ) {
         std::optional<point> coord = ctxt.get_coordinates_text( catacurses::stdscr );
         if( coord.has_value() ) {
             point local_coord = coord.value() + window_pos;
             for( const auto &entry : tab_map ) {
                 if( entry.second.contains( local_coord ) ) {
                     position.set_index( entry.first );
                     return true;
                 }
             }
         }
         return false;
     } else {
         return false;
     }
     return true;
 }
References _, action, input_context::get_coordinates_text(), tab_list::next(), position, tab_list::prev(), query_yn(), quit, tab_list::set_index(), catacurses::stdscr, tab_map, and window_pos.
Referenced by set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), and set_traits().
set_up_tab_navigation()
void tab_manager::set_up_tab_navigation (input_context & ctxt)
Definition at line 192 of file newcharacter.cpp.
 {
     ctxt.register_action( "PREV_TAB" );
     ctxt.register_action( "NEXT_TAB" );
     ctxt.register_action( "SELECT" );
     ctxt.register_action( "QUIT" );
 }
References input_context::register_action().
Referenced by set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_stats(), and set_traits().
Member Data Documentation
complete
bool tab_manager::complete = false
Definition at line 137 of file newcharacter.cpp.
Referenced by avatar::create(), and set_description().
position
tab_list tab_manager::position
Definition at line 139 of file newcharacter.cpp.
Referenced by avatar::create(), draw(), and handle_input().
quit
bool tab_manager::quit = false
Definition at line 138 of file newcharacter.cpp.
Referenced by avatar::create(), and handle_input().
tab_map
std::map<size_t, inclusive_rectangle<point> > tab_manager::tab_map private
Definition at line 134 of file newcharacter.cpp.
Referenced by draw(), and handle_input().
tab_names
std::vector<std::string>& tab_manager::tab_names private
Definition at line 133 of file newcharacter.cpp.
Referenced by draw().
window_pos
point tab_manager::window_pos private
Definition at line 135 of file newcharacter.cpp.
Referenced by draw(), and handle_input().
The documentation for this class was generated from the following file:
src/newcharacter.cpp