Cataclysm DDA: ammunition_type Class Reference
ammunition_type Class Reference
#include <ammo.h>
Public Member Functions
ammunition_type ()
std::string name () const
const itype_id & default_ammotype () const
Static Private Member Functions
static void load_ammunition_type (const JsonObject &jsobj)
static void reset ()
static void check_consistency ()
Private Attributes
translation name_
itype_id default_ammotype_
Friends
class DynamicDataLoader
Detailed Description
Definition at line 12 of file ammo.h.
Constructor & Destructor Documentation
ammunition_type()
ammunition_type::ammunition_type ()
Definition at line 25 of file ammo.cpp.
                                  : name_( no_translation( "null" ) )
 {
 }
Member Function Documentation
check_consistency()
void ammunition_type::check_consistency () static private
Definition at line 64 of file ammo.cpp.
 {
     for( const auto &ammo : all_ammunition_types() ) {
         const auto &id = ammo.first;
         const itype_id &at = ammo.second.default_ammotype_;
         // TODO: these ammo types should probably not have default ammo at all.
         if( at.str() == "components" || at.str() == "thrown" ) {
             continue;
         }
         if( !at.is_empty() && !item::type_is_defined( at ) ) {
             debugmsg( "ammo type %s has invalid default ammo %s", id.c_str(), at.c_str() );
         }
     }
 }
References anonymous_namespace{ammo.cpp}::all_ammunition_types(), string_id< T >::c_str(), debugmsg, string_id< T >::is_empty(), string_id< T >::str(), and item::type_is_defined().
Referenced by DynamicDataLoader::check_consistency().
default_ammotype()
const itype_id& ammunition_type::default_ammotype () const inline
Definition at line 20 of file ammo.h.
{
             return default_ammotype_;
         }
References default_ammotype_.
Referenced by vehicle_part::ammo_capacity(), item::ammo_default(), pocket_data::check_definition(), furn_t::crafting_ammo_item_types(), Item_factory::finalize_pre(), vehicles::finalize_prototypes(), gun_uses_liquid_ammo(), and itype::tool_slot_first_ammo().
load_ammunition_type()
void ammunition_type::load_ammunition_type (const JsonObject & jsobj) static private
Definition at line 29 of file ammo.cpp.
 {
     ammunition_type &res = all_ammunition_types()[ ammotype( jsobj.get_string( "id" ) ) ];
     jsobj.read( "name", res.name_ );
     jsobj.read( "default", res.default_ammotype_, true );
 }
References anonymous_namespace{ammo.cpp}::all_ammunition_types(), default_ammotype_, JsonObject::get_string(), name_, and JsonObject::read().
Referenced by DynamicDataLoader::initialize().
name()
std::string ammunition_type::name () const
Definition at line 81 of file ammo.cpp.
 {
     return name_.translated();
 }
References name_, and translation::translated().
Referenced by item::ammo_sort_name(), item::display_name(), item::gun_info(), and item::gunmod_info().
reset()
void ammunition_type::reset () static private
Definition at line 59 of file ammo.cpp.
 {
     all_ammunition_types().clear();
 }
References anonymous_namespace{ammo.cpp}::all_ammunition_types().
Referenced by DynamicDataLoader::unload_data().
Friends And Related Function Documentation
DynamicDataLoader
friend class DynamicDataLoader friend
Definition at line 14 of file ammo.h.
Member Data Documentation
default_ammotype_
itype_id ammunition_type::default_ammotype_ private
Definition at line 26 of file ammo.h.
Referenced by default_ammotype(), and load_ammunition_type().
name_
translation ammunition_type::name_ private
Definition at line 25 of file ammo.h.
Referenced by load_ammunition_type(), and name().
The documentation for this class was generated from the following files:
src/ammo.h
src/ammo.cpp