Cataclysm DDA: selection_column Class Reference
selection_column Class Reference
#include <inventory_ui.h>
Public Member Functions
selection_column (const std::string &id, const std::string &name)
~selection_column () override
bool activatable () const override
Can this column be activated?
bool allows_selecting () const override
Does this column allow selecting? "Cosmetic" columns (list of selected items) can explicitly prohibit selecting.
void reset_width (const std::vector< inventory_column * > &all_columns) override
Resets width to original (unchanged).
void prepare_paging (const std::string &filter="") override
Reorder entries, repopulate titles, adjust to the new height.
void on_change (const inventory_entry &entry) override
The entry has been changed.
void on_mode_change (navigation_mode) override
Selection mode has been changed.
void set_filter (const std::string &filter) override
void cycle_hide_override () override
Public Member Functions inherited from inventory_column
inventory_column (const inventory_selector_preset &preset=default_preset)
virtual ~inventory_column ()=default
bool empty () const
bool visible () const
Is this column visible?
size_t page_index () const
size_t pages_count () const
bool has_available_choices () const
bool is_selected (const inventory_entry &entry) const
bool is_highlighted (const inventory_entry &entry) const
bool is_selected_by_category (const inventory_entry &entry) const
Does this entry belong to the selected category? When navigation_mode::ITEM is used it's equivalent to is_selected().
const inventory_entry & get_highlighted () const
inventory_entry & get_highlighted ()
std::vector< inventory_entry * > get_all_selected () const
get_entries_t get_entries (const ffilter_t &filter_func, bool include_hidden=false) const
void order_by_parent ()
inventory_entry * find_by_invlet (int invlet) const
inventory_entry * find_by_location (item_location const &loc, bool hidden=false) const
void draw (const catacurses::window &win, const point &p, std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * >> &rect_entry_map)
inventory_entry * add_entry (const inventory_entry &entry)
void move_entries_to (inventory_column &dest)
void clear ()
void set_stack_favorite (inventory_entry &entry, bool favorite)
void set_collapsed (inventory_entry &entry, bool collapse)
bool highlight (const item_location &loc, bool front_only=false)
Highlights the specified location.
void highlight (size_t new_index, scroll_direction dir)
Change the highlight.
size_t get_highlighted_index () const
void set_multiselect (bool multiselect)
void set_visibility (bool visibility)
void set_width (size_t new_width)
void set_height (size_t new_height)
size_t get_width () const
size_t get_height () const
void expand_to_fit (inventory_entry &entry, bool with_denial=true)
Expands the column to fit the new entry.
int reassign_custom_invlets (const Character &p, int min_invlet, int max_invlet)
Returns next custom inventory letter.
int reassign_custom_invlets (int cur_idx, std::string_view pickup_chars)
virtual void on_input (const inventory_input &input)
Event handlers.
virtual void on_activate ()
The column has been activated.
virtual void on_deactivate ()
The column has been deactivated.
bool indent_entries () const
bool collate_entries () const
void set_indent_entries_override (bool entry_override)
void clear_indent_entries_override ()
void invalidate_paging ()
void toggle_skip_unselectable (bool skip)
Toggle being able to highlight unselectable entries.
void collate ()
void uncollate ()
Private Attributes
const pimpl< item_category > selected_cat
inventory_entry last_changed
Additional Inherited Members
Public Types inherited from inventory_column
using get_entries_t = std::vector< inventory_entry * >
using ffilter_t = std::function< bool(const inventory_entry &entry)>
Protected Types inherited from inventory_column
using entries_t = std::vector< inventory_entry >
Protected Member Functions inherited from inventory_column
void move_selection (scroll_direction dir)
Move the selection.
void move_selection_page (scroll_direction dir)
void scroll_selection_page (scroll_direction dir)
size_t next_highlightable_index (size_t index, scroll_direction dir) const
size_t page_of (size_t index) const
size_t page_of (const inventory_entry &entry) const
bool sort_compare (inventory_entry const &lhs, inventory_entry const &rhs)
bool indented_sort_compare (inventory_entry const &lhs, inventory_entry const &rhs)
bool collated_sort_compare (inventory_entry const &lhs, inventory_entry const &rhs)
size_t get_entry_indent (const inventory_entry &entry) const
Indentation of the entry.
size_t get_entry_cell_width (const inventory_entry &entry, size_t cell_index) const
Overall cell width.
size_t get_cells_width () const
Sum of the cell widths.
Protected Attributes inherited from inventory_column
const inventory_selector_preset & preset
entries_t entries
entries_t entries_hidden
navigation_mode mode = navigation_mode::ITEM
bool active = false
bool multiselect = false
bool paging_is_valid = false
bool visibility = true
size_t highlighted_index = std::numeric_limits<size_t>::max()
size_t page_offset = 0
size_t entries_per_page = std::numeric_limits<size_t>::max()
size_t height = std::numeric_limits<size_t>::max()
size_t reserved_width = 0
std::optional< bool > hide_entries_override = std::nullopt
Detailed Description
Definition at line 573 of file inventory_ui.h.
Constructor & Destructor Documentation
selection_column()
selection_column::selection_column (const std::string & id, const std::string & name)
Definition at line 1799 of file inventory_ui.cpp.
                                                                                :
     inventory_column( selection_preset ),
     selected_cat( id, no_translation( name ), translation(), 0 )
 {
     hide_entries_override = { false };
 }
References inventory_column::hide_entries_override.
~selection_column()
selection_column::~selection_column () override default
Member Function Documentation
activatable()
bool selection_column::activatable () const inline override virtual
Can this column be activated?
Returns
Whether the column contains selectable entries. Note: independent from 'allows_selecting'
Reimplemented from inventory_column.
Definition at line 579 of file inventory_ui.h.
{
             return inventory_column::activatable() && pages_count() > 1;
         }
References inventory_column::activatable(), and inventory_column::pages_count().
allows_selecting()
bool selection_column::allows_selecting () const inline override virtual
Does this column allow selecting? "Cosmetic" columns (list of selected items) can explicitly prohibit selecting.
Note: independent from 'activatable'
Reimplemented from inventory_column.
Definition at line 583 of file inventory_ui.h.
{
             return false;
         }
cycle_hide_override()
void selection_column::cycle_hide_override () override virtual
Reimplemented from inventory_column.
Definition at line 2979 of file inventory_ui.cpp.
 {
     // never hide entries
 }
on_change()
void selection_column::on_change (const inventory_entry & entry) override virtual
The entry has been changed.
Reimplemented from inventory_column.
Definition at line 1842 of file inventory_ui.cpp.
 {
     inventory_entry my_entry( entry, &*selected_cat );
     auto iter = std::find( entries.begin(), entries.end(), my_entry );
     if( iter == entries.end() ) {
         if( my_entry.chosen_count == 0 ) {
             return; // Not interested.
         }
         add_entry( my_entry )->make_entry_cell_cache( preset );
         paging_is_valid = false;
         last_changed = my_entry;
     } else if( iter->chosen_count != my_entry.chosen_count ) {
         if( my_entry.chosen_count > 0 ) {
             iter->chosen_count = my_entry.chosen_count;
             iter->make_entry_cell_cache( preset );
         } else {
             iter = entries.erase( iter );
         }
         paging_is_valid = false;
         if( iter != entries.end() ) {
             last_changed = *iter;
         }
     }
 }
References inventory_column::add_entry(), inventory_entry::chosen_count, inventory_column::entries, last_changed, inventory_entry::make_entry_cell_cache(), inventory_column::paging_is_valid, inventory_column::preset, and selected_cat.
on_mode_change()
void selection_column::on_mode_change (navigation_mode mode) inline override virtual
Selection mode has been changed.
Reimplemented from inventory_column.
Definition at line 592 of file inventory_ui.h.
{
             // Intentionally ignore mode change.
         }
prepare_paging()
void selection_column::prepare_paging (const std::string & filter = "") override virtual
Reorder entries, repopulate titles, adjust to the new height.
Reimplemented from inventory_column.
Definition at line 1823 of file inventory_ui.cpp.
 {
     // always show all selected items
     inventory_column::prepare_paging( std::string() );
     if( entries.empty() ) { // Category must always persist
         entries.emplace_back( &*selected_cat );
         expand_to_fit( entries.back(), false );
     }
     if( !last_changed.is_null() ) {
         const auto iter = std::find( entries.begin(), entries.end(), last_changed );
         if( iter != entries.end() ) {
             highlight( std::distance( entries.begin(), iter ), scroll_direction::FORWARD );
         }
         last_changed = inventory_entry();
     }
 }
References inventory_column::entries, inventory_column::expand_to_fit(), FORWARD, inventory_column::highlight(), inventory_entry::is_null(), last_changed, inventory_column::prepare_paging(), and selected_cat.
reset_width()
void selection_column::reset_width (const std::vector< inventory_column * > & all_columns) override virtual
Resets width to original (unchanged).
Reimplemented from inventory_column.
Definition at line 1808 of file inventory_ui.cpp.
 {
     inventory_column::reset_width( all_columns );
     for( const inventory_column *const col : all_columns ) {
         if( col && !dynamic_cast<const selection_column *>( col ) ) {
             for( inventory_entry *const ent : col->get_entries( always_yes ) ) {
                 if( ent ) {
                     expand_to_fit( *ent, false );
                 }
             }
         }
     }
 }
References anonymous_namespace{inventory_ui.cpp}::always_yes(), inventory_column::expand_to_fit(), and inventory_column::reset_width().
set_filter()
void selection_column::set_filter (const std::string & filter) override virtual
Reimplemented from inventory_column.
Definition at line 989 of file inventory_ui.cpp.
 {
     // always show all selected items
     inventory_column::set_filter( std::string() );
 }
References inventory_column::set_filter().
Member Data Documentation
last_changed
inventory_entry selection_column::last_changed private
Definition at line 601 of file inventory_ui.h.
Referenced by on_change(), and prepare_paging().
selected_cat
const pimpl<item_category> selection_column::selected_cat private
Definition at line 600 of file inventory_ui.h.
Referenced by on_change(), and prepare_paging().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp