Cataclysm DDA: repair_inventory_preset Class Reference
repair_inventory_preset Class Reference
Public Member Functions
repair_inventory_preset (const repair_item_actor *actor, const item *main_tool, Character &you)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual std::string get_denial (const item_location &) const
The reason why this entry cannot be selected.
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Private Attributes
const repair_item_actor * actor
const item * main_tool
Character & character
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 2016 of file game_inventory.cpp.
Constructor & Destructor Documentation
repair_inventory_preset()
repair_inventory_preset::repair_inventory_preset (const repair_item_actor * actor, const item * main_tool, Character & you) inline
Definition at line 2019 of file game_inventory.cpp.
                                                                                                          :
             actor( actor ), main_tool( main_tool ), character( you ) {
             _indent_entries = false;
             append_cell( [actor, &you]( const item_location & loc ) {
                 const int comp_needed = std::max<int>( 1,
                                                        std::ceil( loc->base_volume() / 250_ml * actor->cost_scaling ) );
                 const inventory &crafting_inv = you.crafting_inventory();
                 std::function<bool( const item & )> filter;
                 if( loc->is_filthy() ) {
                     filter = []( const item & component ) {
                         return component.allow_crafting_component();
                     };
                 } else {
                     filter = is_crafting_component;
                 }
                 std::vector<std::string> material_list;
                 for( const itype_id &component_id : actor->get_valid_repair_materials( *loc ) ) {
                     if( item::count_by_charges( component_id ) ) {
                         if( crafting_inv.has_charges( component_id, 1 ) ) {
                             const int num_comp = crafting_inv.charges_of( component_id );
                             material_list.push_back( colorize( string_format( _( "%s (%d)" ), item::nname( component_id ),
                                                                num_comp ), num_comp < comp_needed ? c_red : c_unset ) );
                         }
                     } else if( crafting_inv.has_amount( component_id, 1, false, filter ) ) {
                         const int num_comp = crafting_inv.amount_of( component_id, false );
                         material_list.push_back( colorize( string_format( _( "%s (%d)" ), item::nname( component_id ),
                                                            num_comp ), num_comp < comp_needed ? c_red : c_unset ) );
                     }
                 }
                 std::string ret = string_join( material_list, ", " );
                 if( ret.empty() ) {
                     ret = _( "<color_red>NONE</color>" );
                 }
                 return ret;
             },
             _( "MATERIALS AVAILABLE" ) );
             append_cell( [actor, &you]( const item_location & loc ) {
                 const int level = you.get_skill_level( actor->used_skill );
                 const repair_item_actor::repair_type action_type = actor->default_action( *loc, level );
                 const std::pair<float, float> chance = actor->repair_chance( you, *loc, action_type );
                 return colorize( string_format( "%0.1f%%", 100.0f * chance.first ),
                                  chance.first == 0 ? c_yellow : ( chance.second == 0 ? c_light_green : c_unset ) );
             },
             _( "SUCCESS CHANCE" ) );
             append_cell( [actor, &you]( const item_location & loc ) {
                 const int level = you.get_skill_level( actor->used_skill );
                 const repair_item_actor::repair_type action_type = actor->default_action( *loc, level );
                 const std::pair<float, float> chance = actor->repair_chance( you, *loc, action_type );
                 return colorize( string_format( "%0.1f%%", 100.0f * chance.second ),
                                  chance.second > chance.first ? c_yellow : ( chance.second == 0 &&
                                          chance.first > 0 ? c_light_green : c_unset ) );
             },
             _( "DAMAGE CHANCE" ) );
             append_cell( [actor, &you]( const item_location & loc ) {
                 const int difficulty = actor->repair_recipe_difficulty( *loc );
                 return colorize( string_format( "%d", difficulty ),
                                  difficulty > you.get_skill_level( actor->used_skill ) ? c_red : c_unset );
             },
             _( "DIFFICULTY" ) );
         }
References _, inventory_selector_preset::_indent_entries, actor, inventory::amount_of(), inventory_selector_preset::append_cell(), item::base_volume(), c_light_green, c_red, c_unset, c_yellow, ceil(), inventory::charges_of(), colorize(), repair_item_actor::cost_scaling, item::count_by_charges(), Character::crafting_inventory(), repair_item_actor::default_action(), filter, Character::get_skill_level(), repair_item_actor::get_valid_repair_materials(), visitable::has_amount(), read_only_visitable::has_charges(), is_crafting_component(), item::is_filthy(), item::nname(), repair_item_actor::repair_chance(), repair_item_actor::repair_recipe_difficulty(), cata::hash64_detail::ret, string_format(), string_join(), and repair_item_actor::used_skill.
Member Function Documentation
is_shown()
bool repair_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 2085 of file game_inventory.cpp.
{
             return actor->can_repair_target( character, *loc, false, false ) && ( &*loc != main_tool );
         }
References actor, repair_item_actor::can_repair_target(), character, and main_tool.
Member Data Documentation
actor
const repair_item_actor* repair_inventory_preset::actor private
Definition at line 2090 of file game_inventory.cpp.
Referenced by is_shown(), and repair_inventory_preset().
character
Character& repair_inventory_preset::character private
Definition at line 2092 of file game_inventory.cpp.
Referenced by is_shown().
main_tool
const item* repair_inventory_preset::main_tool private
Definition at line 2091 of file game_inventory.cpp.
Referenced by is_shown().
The documentation for this class was generated from the following file:
src/game_inventory.cpp