Cataclysm DDA: auto_notes::auto_note_settings Class Reference
auto_notes::auto_note_settings Class Reference
A class storing auto note settings for all map features for a given player.
#include <auto_note.h>
Public Member Functions
bool has_auto_note_enabled (const map_extra_id &mapExtId, bool bCharacter) const
void set_auto_note_status (const map_extra_id &mapExtId, bool enabled, bool bCharacter)
void set_discovered (const map_extra_id &mapExtId)
bool was_discovered (const map_extra_id &mapExtId) const
std::optional< custom_symbol > get_custom_symbol (const map_extra_id &mapExtId) const
void set_custom_symbol (const map_extra_id &mapExtId, const custom_symbol &symbol, bool bCharacter)
void clear_all_custom_symbols (bool bCharacter)
void load (bool bCharacter)
bool save (bool bCharacter)
void clear ()
void show_gui ()
void default_initialize ()
Perform default initialization.
Private Member Functions
cata_path build_save_path () const
Build string containing path to the auto notes save file for the active player.
Private Attributes
std::unordered_set< map_extra_id > character_autoNoteEnabled
This set contains the ID strings of all map extras that have auto note enabled for a character.
std::unordered_set< map_extra_id > global_autoNoteDisabled
This set contains the ID strings of all map extras that have auto note disabled globally.
std::unordered_set< map_extra_id > discovered
This set contains the ID strings of all map extras that were already encountered by the player.
std::unordered_map< map_extra_id, custom_symbol > character_custom_symbols
User-defined symbols and colors for the auto notes for this character.
std::unordered_map< map_extra_id, custom_symbol > global_custom_symbols
User-defined symbols and colors for the auto notes globably.
Friends
class auto_note_manager_gui
Detailed Description
A class storing auto note settings for all map features for a given player.
Since auto note is something that is very dependent on in which stage of the game a player is (f.e., dead college kids are useful in the early game, but not so much in the late game), the settings are only available tied to a specific game save, meaning there is no global setting like with the auto-pickup manager.
Definition at line 108 of file auto_note.h.
Member Function Documentation
build_save_path()
cata_path auto_notes::auto_note_settings::build_save_path () const private
Build string containing path to the auto notes save file for the active player.
Definition at line 32 of file auto_note.cpp.
 {
     return PATH_INFO::player_base_save_path_path() + ".ano.json";
 }
References PATH_INFO::player_base_save_path_path().
Referenced by load(), and save().
clear()
void auto_notes::auto_note_settings::clear ()
Definition at line 37 of file auto_note.cpp.
 {
     character_autoNoteEnabled.clear();
     discovered.clear();
 }
References character_autoNoteEnabled, and discovered.
Referenced by clear_all_custom_symbols(), default_initialize(), load(), and game::start_game().
clear_all_custom_symbols()
void auto_notes::auto_note_settings::clear_all_custom_symbols (bool bCharacter)
Definition at line 236 of file auto_note.cpp.
 {
     ( bCharacter ?  character_custom_symbols : global_custom_symbols ).clear();
 }
References character_custom_symbols, clear(), and global_custom_symbols.
Referenced by auto_notes::auto_note_manager_gui::show().
default_initialize()
void auto_notes::auto_note_settings::default_initialize ()
Perform default initialization.
This will use the auto note property of registered map extras in order to determine their enable status.
Definition at line 160 of file auto_note.cpp.
 {
     clear();
     load( false );
     for( const map_extra &extra : MapExtras::mapExtraFactory().get_all() ) {
         if( has_auto_note_enabled( extra.id, false ) && extra.autonote ) {
             character_autoNoteEnabled.insert( extra.id );
         }
     }
     character_custom_symbols = global_custom_symbols;
 }
References character_autoNoteEnabled, character_custom_symbols, clear(), ammo_effects::get_all(), global_custom_symbols, has_auto_note_enabled(), load(), and MapExtras::mapExtraFactory().
Referenced by load(), and game::start_game().
get_custom_symbol()
std::optional< custom_symbol > auto_notes::auto_note_settings::get_custom_symbol (const map_extra_id & mapExtId) const
Definition at line 222 of file auto_note.cpp.
 {
     auto entry = character_custom_symbols.find( mapExtId );
     return entry == character_custom_symbols.end() ? std::nullopt
            : std::optional<custom_symbol>( entry->second );
 }
References character_custom_symbols.
Referenced by overmap::add_extra_note().
has_auto_note_enabled()
bool auto_notes::auto_note_settings::has_auto_note_enabled (const map_extra_id & mapExtId, bool bCharacter) const
Definition at line 196 of file auto_note.cpp.
 {
     if( bCharacter ) {
         return character_autoNoteEnabled.count( mapExtId ) != 0;
     } else {
         return global_autoNoteDisabled.count( mapExtId ) == 0;
     }
 }
References character_autoNoteEnabled, and global_autoNoteDisabled.
Referenced by overmap::add_extra_note(), auto_notes::auto_note_manager_gui::auto_note_manager_gui(), default_initialize(), and set_auto_note_status().
load()
void auto_notes::auto_note_settings::load (bool bCharacter)
Definition at line 108 of file auto_note.cpp.
 {
     clear();
     const auto parseJson = [ &, bCharacter ]( const JsonValue & jv ) {
         JsonObject jo = jv;
         for( JsonMember member : jo ) {
             const std::string name = member.name();
             if( name == "enabled" ) {
                 JsonArray enabled_notes = member;
                 for( std::string entry : enabled_notes ) {
                     character_autoNoteEnabled.insert( map_extra_id{ entry } );
                 }
             } else if( name == "disabled" ) {
                 JsonArray disabled_notes = member;
                 for( std::string entry : disabled_notes ) {
                     global_autoNoteDisabled.insert( map_extra_id{ entry } );
                 }
             } else if( name == "discovered" ) {
                 JsonArray discovered_array = member;
                 for( std::string entry : discovered_array ) {
                     discovered.insert( map_extra_id {std::move( entry )} );
                 }
             } else if( name == "custom_symbols" ) {
                 JsonArray symbols_json = member;
                 for( JsonObject joSymbols : symbols_json ) {
                     const std::string entry = joSymbols.get_string( "map_extra" );
                     const std::string custom_symbol_str = joSymbols.get_string( "symbol" );
                     const std::string custom_color = joSymbols.get_string( "color" );
                     custom_symbol sym;
                     sym.set_symbol( custom_symbol_str );
                     sym.set_color( custom_color );
                     ( bCharacter ? character_custom_symbols : global_custom_symbols ).insert( std::make_pair(
                                 map_extra_id {entry}, sym ) );
                 }
             }
         }
     };
     if( bCharacter ) {
         if( !read_from_file_optional_json( build_save_path(), parseJson ) ) {
             default_initialize();
             save( true );
         }
     } else {
         cata_path sGlobalFile = PATH_INFO::autonote();
         read_from_file_optional_json( sGlobalFile, parseJson );
     }
 }
References PATH_INFO::autonote(), build_save_path(), character_autoNoteEnabled, character_custom_symbols, clear(), default_initialize(), discovered, global_autoNoteDisabled, global_custom_symbols, member, om_direction::name(), read_from_file_optional_json(), save(), auto_notes::custom_symbol::set_color(), and auto_notes::custom_symbol::set_symbol().
Referenced by default_initialize(), game::load(), and game::load_static_data().
save()
bool auto_notes::auto_note_settings::save (bool bCharacter)
Definition at line 43 of file auto_note.cpp.
 {
     if( bCharacter && !file_exist( PATH_INFO::player_base_save_path() + ".sav" ) ) {
         return true;
     }
     cata_path sGlobalFile = PATH_INFO::autonote();
     return write_to_file( bCharacter ? build_save_path() : sGlobalFile, [ &,
     bCharacter]( std::ostream & fstr ) {
         JsonOut jout{ fstr, true };
         jout.start_object();
         if( bCharacter ) {
             jout.member( "enabled" );
             jout.start_array();
             for( const map_extra_id &entry : character_autoNoteEnabled ) {
                 jout.write( entry.str() );
             }
             jout.end_array();
             jout.member( "discovered" );
             jout.start_array();
             for( const map_extra_id &entry : discovered ) {
                 jout.write( entry.str() );
             }
             jout.end_array();
         } else {
             jout.member( "disabled" );
             jout.start_array();
             for( const map_extra_id &entry : global_autoNoteDisabled ) {
                 jout.write( entry.str() );
             }
             jout.end_array();
         }
         if( !( bCharacter ?  character_custom_symbols : global_custom_symbols ).empty() ) {
             jout.member( "custom_symbols" );
             jout.start_array();
             for( const std::pair<const map_extra_id &, const auto_notes::custom_symbol &> symbol_entry :
                  bCharacter ?  character_custom_symbols : global_custom_symbols ) {
                 jout.start_object();
                 jout.member( "map_extra" );
                 jout.write( symbol_entry.first.str() );
                 jout.member( "symbol" );
                 jout.write( symbol_entry.second.get_symbol_string() );
                 jout.member( "color" );
                 jout.write( symbol_entry.second.get_color_string() );
                 jout.end_object();
             }
             jout.end_array();
         }
         jout.end_object();
     }, _( "auto notes configuration" ) );
 }
References _, PATH_INFO::autonote(), build_save_path(), character_autoNoteEnabled, character_custom_symbols, discovered, file_exist(), global_autoNoteDisabled, global_custom_symbols, PATH_INFO::player_base_save_path(), JsonOut::start_object(), and write_to_file().
Referenced by load(), game::save(), and show_gui().
set_auto_note_status()
void auto_notes::auto_note_settings::set_auto_note_status (const map_extra_id & mapExtId, bool enabled, bool bCharacter)
Definition at line 206 of file auto_note.cpp.
 {
     if( enabled && bCharacter ) {
         character_autoNoteEnabled.insert( mapExtId );
     } else if( enabled && !bCharacter ) {
         global_autoNoteDisabled.erase( mapExtId );
     } else if( has_auto_note_enabled( mapExtId, bCharacter ) ) {
         if( bCharacter ) {
             character_autoNoteEnabled.erase( mapExtId );
         } else {
             global_autoNoteDisabled.insert( mapExtId );
         }
     }
 }
References character_autoNoteEnabled, enabled, global_autoNoteDisabled, and has_auto_note_enabled().
Referenced by auto_notes::auto_note_manager_gui::show().
set_custom_symbol()
void auto_notes::auto_note_settings::set_custom_symbol (const map_extra_id & mapExtId, const custom_symbol & symbol, bool bCharacter)
Definition at line 230 of file auto_note.cpp.
 {
     ( bCharacter ?  character_custom_symbols : global_custom_symbols ).emplace( mapExtId, symbol );
 }
References character_custom_symbols, global_custom_symbols, and symbol().
Referenced by auto_notes::auto_note_manager_gui::show().
set_discovered()
void auto_notes::auto_note_settings::set_discovered (const map_extra_id & mapExtId)
Definition at line 173 of file auto_note.cpp.
 {
     discovered.insert( mapExtId );
 }
References discovered.
Referenced by overmap::add_extra_note().
show_gui()
void auto_notes::auto_note_settings::show_gui ()
Definition at line 183 of file auto_note.cpp.
 {
     auto_note_manager_gui gui{ };
     gui.show();
     if( gui.was_changed( true ) ) {
         save( true );
     }
     if( gui.was_changed( false ) ) {
         save( false );
     }
 }
References save(), and auto_notes::auto_note_manager_gui::show().
Referenced by game::do_regular_action().
was_discovered()
bool auto_notes::auto_note_settings::was_discovered (const map_extra_id & mapExtId) const
Definition at line 178 of file auto_note.cpp.
 {
     return discovered.count( mapExtId ) != 0;
 }
References discovered.
Referenced by auto_notes::auto_note_manager_gui::auto_note_manager_gui().
Friends And Related Function Documentation
auto_note_manager_gui
friend class auto_note_manager_gui friend
Definition at line 111 of file auto_note.h.
Member Data Documentation
character_autoNoteEnabled
std::unordered_set<map_extra_id> auto_notes::auto_note_settings::character_autoNoteEnabled private
This set contains the ID strings of all map extras that have auto note enabled for a character.
Definition at line 146 of file auto_note.h.
Referenced by clear(), default_initialize(), has_auto_note_enabled(), load(), save(), and set_auto_note_status().
character_custom_symbols
std::unordered_map<map_extra_id, custom_symbol> auto_notes::auto_note_settings::character_custom_symbols private
User-defined symbols and colors for the auto notes for this character.
Definition at line 156 of file auto_note.h.
Referenced by clear_all_custom_symbols(), default_initialize(), auto_notes::auto_note_manager_gui::fill_custom_symbols_cache(), get_custom_symbol(), load(), save(), and set_custom_symbol().
discovered
std::unordered_set<map_extra_id> auto_notes::auto_note_settings::discovered private
This set contains the ID strings of all map extras that were already encountered by the player.
This is used in order to avoid spoilers in the GUI.
Definition at line 153 of file auto_note.h.
Referenced by clear(), load(), save(), set_discovered(), and was_discovered().
global_autoNoteDisabled
std::unordered_set<map_extra_id> auto_notes::auto_note_settings::global_autoNoteDisabled private
This set contains the ID strings of all map extras that have auto note disabled globally.
Definition at line 149 of file auto_note.h.
Referenced by has_auto_note_enabled(), load(), save(), and set_auto_note_status().
global_custom_symbols
std::unordered_map<map_extra_id, custom_symbol> auto_notes::auto_note_settings::global_custom_symbols private
User-defined symbols and colors for the auto notes globably.
Definition at line 159 of file auto_note.h.
Referenced by clear_all_custom_symbols(), default_initialize(), auto_notes::auto_note_manager_gui::fill_custom_symbols_cache(), load(), save(), and set_custom_symbol().
The documentation for this class was generated from the following files:
src/auto_note.h
src/auto_note.cpp