Cataclysm DDA: holster_actor Class Reference
holster_actor Class Reference
Holster a weapon.
#include <iuse_actor.h>
Public Member Functions
bool can_holster (const item &holster, const item &obj) const
Check if obj could be stored in the holster.
bool store (Character &you, item &holster, item &obj) const
Store an object in the holster.
holster_actor (const std::string &type="holster")
~holster_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
translation holster_prompt
Prompt to use when selecting an item.
translation holster_msg
Message to show when holstering an item.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Holster a weapon.
Definition at line 733 of file iuse_actor.h.
Constructor & Destructor Documentation
holster_actor()
holster_actor::holster_actor (const std::string & type = "holster") inline explicit
Definition at line 747 of file iuse_actor.h.
 : iuse_actor( type ) {}
~holster_actor()
holster_actor::~holster_actor () override default
Member Function Documentation
can_holster()
bool holster_actor::can_holster (const item & holster, const item & obj) const
Check if obj could be stored in the holster.
Definition at line 2483 of file iuse_actor.cpp.
 {
     return obj.active ? false : holster.can_contain( obj ).success();
 }
References item::active, and game_menus::inv::holster().
Referenced by item::can_holster(), and holster_inventory_preset::is_shown().
clone()
std::unique_ptr< iuse_actor > holster_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2472 of file iuse_actor.cpp.
 {
     return std::make_unique<holster_actor>( *this );
 }
info()
void holster_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 2620 of file iuse_actor.cpp.
 {
     std::string message = _( "Can be activated to store suitable items." );
     dump.emplace_back( "DESCRIPTION", message );
 }
References _, and mapgen_defer::message.
load()
void holster_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2477 of file iuse_actor.cpp.
 {
     obj.read( "holster_prompt", holster_prompt );
     obj.read( "holster_msg", holster_msg );
 }
References holster_msg, holster_prompt, and JsonObject::read().
store()
bool holster_actor::store (Character & you, item & holster, item & obj) const
Store an object in the holster.
Definition at line 2488 of file iuse_actor.cpp.
 {
     if( obj.is_null() || holster.is_null() ) {
         debugmsg( "Null item was passed to holster_actor" );
         return false;
     }
     const ret_val<void> contain = holster.can_contain( obj );
     if( !contain.success() ) {
         you.add_msg_if_player( m_bad, contain.str(), holster.tname(), obj.tname() );
     }
     if( obj.active ) {
         you.add_msg_if_player( m_info, _( "You don't think putting your %1$s in your %2$s is a good idea" ),
                                obj.tname(), holster.tname() );
         return false;
     }
     you.add_msg_if_player( holster_msg.empty() ? _( "You holster your %s" ) : holster_msg.translated(),
                            obj.tname(), holster.tname() );
     // holsters ignore penalty effects (e.g. GRABBED) when determining number of moves to consume
     you.as_character()->store( holster, obj, false, holster.obtain_cost( obj ),
                                pocket_type::CONTAINER, true );
     return true;
 }
References _, item::active, Character::add_msg_if_player(), Character::as_character(), CONTAINER, debugmsg, translation::empty(), game_menus::inv::holster(), holster_msg, item::is_null(), m_bad, m_info, Character::store(), ret_val_common::str(), ret_val_common::success(), item::tname(), and translation::translated().
use()
std::optional< int > holster_actor::use (Character * you, item & it, const tripoint & p) const override virtual
Implements iuse_actor.
Definition at line 2547 of file iuse_actor.cpp.
 {
     if( you->is_wielding( it ) ) {
         you->add_msg_if_player( _( "You need to unwield your %s before using it." ), it.tname() );
         return std::nullopt;
     }
     int pos = 0;
     std::vector<std::string> opts;
     std::string prompt = holster_prompt.empty() ? _( "Holster item" ) : holster_prompt.translated();
     opts.push_back( prompt );
     pos = -1;
     std::list<item *> all_items = it.all_items_top(
                                       pocket_type::CONTAINER );
     std::transform( all_items.begin(), all_items.end(), std::back_inserter( opts ),
     []( const item * elem ) {
         return string_format( _( "Draw %s" ), elem->display_name() );
     } );
     item *internal_item = nullptr;
     if( opts.size() > 1 ) {
         int ret = uilist( string_format( _( "Use %s" ), it.tname() ), opts );
         if( ret < 0 ) {
             pos = -2;
         } else {
             pos += ret;
             if( opts.size() != it.num_item_stacks() ) {
                 ret--;
             }
             auto iter = std::next( all_items.begin(), ret );
             internal_item = *iter;
         }
     } else {
         if( !all_items.empty() ) {
             internal_item = all_items.front();
         }
     }
     if( pos < -1 ) {
         you->add_msg_if_player( _( "Never mind." ) );
         return std::nullopt;
     }
     if( pos >= 0 ) {
         item_location weapon =  you->get_wielded_item();
         if( weapon && weapon.get_item()->has_flag( flag_NO_UNWIELD ) ) {
             std::optional<bionic *> bio_opt = you->find_bionic_by_uid( you->get_weapon_bionic_uid() );
             if( !bio_opt || !you->deactivate_bionic( **bio_opt ) ) {
                 you->add_msg_if_player( m_bad, _( "You can't unwield your %s." ), weapon.get_item()->tname() );
                 return std::nullopt;
             }
         }
         // worn holsters ignore penalty effects (e.g. GRABBED) when determining number of moves to consume
         if( you->is_worn( it ) ) {
             you->wield_contents( it, internal_item, false, it.obtain_cost( *internal_item ) );
         } else {
             you->wield_contents( it, internal_item );
         }
     } else {
         if( you->as_avatar() == nullptr ) {
             return std::nullopt;
         }
         // iuse_actor really needs to work with item_location
         item_location item_loc = form_loc( *you, p, it );
         game_menus::inv::insert_items( *you->as_avatar(), item_loc );
     }
     return 0;
 }
References _, Character::add_msg_if_player(), item::all_items_top(), Creature::as_avatar(), CONTAINER, Character::deactivate_bionic(), translation::empty(), Character::find_bionic_by_uid(), flag_NO_UNWIELD, form_loc(), item_location::get_item(), Character::get_weapon_bionic_uid(), Character::get_wielded_item(), item::has_flag(), holster_prompt, game_menus::inv::insert_items(), Character::is_wielding(), Character::is_worn(), m_bad, item::num_item_stacks(), item::obtain_cost(), math_opers::pos(), Pickup::prompt, cata::hash64_detail::ret, string_format(), item::tname(), translation::translated(), and Character::wield_contents().
Member Data Documentation
holster_msg
translation holster_actor::holster_msg
Message to show when holstering an item.
Definition at line 739 of file iuse_actor.h.
Referenced by load(), and store().
holster_prompt
translation holster_actor::holster_prompt
Prompt to use when selecting an item.
Definition at line 737 of file iuse_actor.h.
Referenced by game_menus::inv::holster(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp