Cataclysm DDA: climbing_aid Class Reference
climbing_aid Class Reference
A "Climbing Aid" as defined here is any one trait, mutation, tool, furniture terrain, technique or any other affordance that facilitates movement up, down or across the environment.
#include <climbing.h>
Classes
struct climb_cost
struct condition
struct down_t
class fall_scan
Scans downwards from a tile to assess what lies between it and solid ground.
Public Types
enum class category {
special = 0 , ter_furn , veh , item ,
character , trait , last
}
using lookup = std::vector< std::unordered_multimap< std::string, const climbing_aid * > >
using condition_list = std::vector< condition >
using aid_list = std::vector< const climbing_aid * >
Public Member Functions
void load (const JsonObject &jo, std::string_view)
Static Public Member Functions
static void load_climbing_aid (const JsonObject &jo, const std::string &src)
static void finalize ()
static void check_consistency ()
static void reset ()
static const std::vector< climbing_aid > & get_all ()
static condition_list detect_conditions (Character &you, const tripoint &examp)
static aid_list list (const condition_list &cond)
static aid_list list_all (const condition_list &cond)
static const climbing_aid & get_default ()
static const climbing_aid & get_safest (const condition_list &cond, bool no_deploy=true)
Public Attributes
bool was_loaded = false
climbing_aid_id id
std::vector< std::pair< climbing_aid_id, mod_id > > src
condition base_condition
int slip_chance_mod = 0
struct climbing_aid::down_t down
Detailed Description
A "Climbing Aid" as defined here is any one trait, mutation, tool, furniture terrain, technique or any other affordance that facilitates movement up, down or across the environment.
Availability of climbing aids is subject to various conditions; exactly one is used at a time.
Definition at line 25 of file climbing.h.
Member Typedef Documentation
aid_list
using climbing_aid::aid_list = std::vector<const climbing_aid *>
Definition at line 68 of file climbing.h.
condition_list
using climbing_aid::condition_list = std::vector<condition>
Definition at line 66 of file climbing.h.
lookup
using climbing_aid::lookup = std::vector<std::unordered_multimap<std::string, const climbing_aid *> >
Definition at line 65 of file climbing.h.
Member Enumeration Documentation
category
enum climbing_aid::category strong
Enumerator
special
ter_furn
veh
item
character
trait
last
Definition at line 28 of file climbing.h.
{
             special = 0,
             ter_furn,
             veh,
             item,
             character,
             trait,
             last
         };
Member Function Documentation
check_consistency()
void climbing_aid::check_consistency () static
Definition at line 120 of file climbing.cpp.
 {
     if( !climbing_aid_default || !climbing_aid_default->was_loaded ) {
         debugmsg( "Default climbing aid was not defined." );
     }
 }
References climbing_aid_default, debugmsg, and was_loaded.
Referenced by DynamicDataLoader::check_consistency().
detect_conditions()
climbing_aid::condition_list climbing_aid::detect_conditions (Character & you, const tripoint & examp) static
Definition at line 329 of file climbing.cpp.
 {
     condition_list list;
     map &here = get_map();
     fall_scan fall( examp );
     auto detect_you_character_flag = [&you]( condition & cond ) {
         return you.has_flag( json_character_flag( cond.flag ) );
     };
     auto detect_you_trait = [&you]( condition & cond ) {
         return you.has_trait( trait_id( cond.flag ) );
     };
     auto detect_item = [&you]( condition & cond ) {
         cond.uses_item = you.amount_of( itype_id( cond.flag ) );
         return cond.uses_item > 0;
     };
     auto detect_ter_furn_flag = [&here, &fall]( condition & cond ) {
         tripoint pos = fall.pos_furniture_or_floor();
         cond.range = fall.pos_top().z - pos.z;
         return here.has_flag( cond.flag, pos );
     };
     auto detect_vehicle = [&fall]( condition & cond ) {
         // TODO implement flags and range?
         cond.range = 1;
         return fall.veh_just_below();
     };
     detect_conditions_sub( list, category::character, detect_you_character_flag );
     detect_conditions_sub( list, category::trait, detect_you_trait );
     detect_conditions_sub( list, category::item, detect_item );
     detect_conditions_sub( list, category::ter_furn, detect_ter_furn_flag );
     detect_conditions_sub( list, category::veh, detect_vehicle );
     return list;
 }
References Character::amount_of(), character, detect_conditions_sub(), get_map(), Character::has_flag(), map::has_flag(), Character::has_trait(), item, itype_id, list(), math_opers::pos(), climbing_aid::fall_scan::pos_furniture_or_floor(), climbing_aid::fall_scan::pos_top(), ter_furn, trait, trait_id, veh, climbing_aid::fall_scan::veh_just_below(), and tripoint::z.
Referenced by game::climb_down_menu_gen().
finalize()
void climbing_aid::finalize () static
Definition at line 84 of file climbing.cpp.
 {
     // Build the climbing aids by condition lookup table
     climbing_aid_default_ptr = nullptr;
     climbing_lookup.clear();
     climbing_lookup.resize( int( category::last ) );
     for( const climbing_aid &aid : get_all() ) {
         int category_index = int( aid.base_condition.cat );
         if( category_index >= int( climbing_lookup.size() ) ) {
             debugmsg( "Climbing aid %s has invalid condition type.", aid.id.str() );
             continue;
         }
         climbing_lookup[ category_index ].emplace( aid.base_condition.flag, &aid );
         if( aid.id.str() == "default" ) {
             climbing_aid_default_ptr = &aid;
         }
     }
     if( !climbing_aid_default_ptr ) {
         // Force-generate the default climbing aid.
         static climbing_aid def;
         def.id = climbing_aid_default;
         def.slip_chance_mod = 0;
         def.base_condition.cat = category::special;
         def.down.menu_text = to_translation( "Climb down by lowering yourself from the ledge." );
         def.down.menu_hotkey = 'c';
         def.down.confirm_text = to_translation( "Climb down the ledge?" );
         def.down.msg_after = to_translation( "You lower yourself from the ledge." );
         def.down.max_height = 1;
         def.was_loaded = false;
         def.down.was_loaded = true;
     }
 }
References base_condition, climbing_aid::condition::cat, climbing_aid_default, climbing_aid_default_ptr, climbing_lookup, climbing_aid::down_t::confirm_text, debugmsg, down, get_all(), id, last, climbing_aid::down_t::max_height, climbing_aid::down_t::menu_hotkey, climbing_aid::down_t::menu_text, climbing_aid::down_t::msg_after, slip_chance_mod, special, to_translation(), was_loaded, and climbing_aid::down_t::was_loaded.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< climbing_aid > & climbing_aid::get_all () static
Definition at line 74 of file climbing.cpp.
 {
     return climbing_aid_factory.get_all();
 }
References anonymous_namespace{climbing.cpp}::climbing_aid_factory.
Referenced by finalize().
get_default()
const climbing_aid & climbing_aid::get_default () static
Definition at line 303 of file climbing.cpp.
 {
     return *climbing_aid_default_ptr;
 }
References climbing_aid_default_ptr.
get_safest()
const climbing_aid & climbing_aid::get_safest (const condition_list & cond, bool no_deploy = true) static
Definition at line 286 of file climbing.cpp.
 {
     const climbing_aid *choice = climbing_aid_default_ptr;
     const auto choose_safest = [&choice, no_deploy]( const condition &, const climbing_aid & aid ) {
         if( !no_deploy || aid.down.deploy_furn.is_empty() ) {
             if( aid.slip_chance_mod < choice->slip_chance_mod ) {
                 choice = &aid;
             }
         }
     };
     for_each_aid_condition( conditions, choose_safest );
     return *choice;
 }
References climbing_aid_default_ptr, for_each_aid_condition(), and slip_chance_mod.
Referenced by list().
list()
climbing_aid::aid_list climbing_aid::list (const condition_list & cond) static
Definition at line 254 of file climbing.cpp.
 {
     std::vector<const climbing_aid *> list;
     const auto add_deployables = [&list]( const condition &, const climbing_aid & aid ) {
         if( aid.down.deploys_furniture() ) {
             list.push_back( &aid );
         }
     };
     for_each_aid_condition( conditions, add_deployables );
     list.push_back( &get_safest( conditions, true ) );
     return list;
 }
References for_each_aid_condition(), and get_safest().
Referenced by game::climb_down_menu_gen(), detect_conditions(), detect_conditions_sub(), and list_all().
list_all()
climbing_aid::aid_list climbing_aid::list_all (const condition_list & cond) static
Definition at line 271 of file climbing.cpp.
 {
     std::vector<const climbing_aid *> list;
     const auto add_climbing_aids = [&list]( const condition &, const climbing_aid & aid ) {
         list.push_back( &aid );
     };
     for_each_aid_condition( conditions, add_climbing_aids );
     list.push_back( climbing_aid_default_ptr );
     return list;
 }
References climbing_aid_default_ptr, for_each_aid_condition(), and list().
Referenced by game::climb_down_menu_gen().
load()
void climbing_aid::load (const JsonObject & jo, std::string_view)
Definition at line 134 of file climbing.cpp.
 {
     optional( jo, was_loaded, "slip_chance_mod", slip_chance_mod );
     mandatory( jo, was_loaded, "down", down );
     mandatory( jo, was_loaded, "condition", base_condition );
     was_loaded = true;
 }
References base_condition, down, mandatory, optional(), slip_chance_mod, and was_loaded.
load_climbing_aid()
void climbing_aid::load_climbing_aid (const JsonObject & jo, const std::string & src) static
Definition at line 79 of file climbing.cpp.
 {
     climbing_aid_factory.load( jo, src );
 }
References anonymous_namespace{climbing.cpp}::climbing_aid_factory, and src.
Referenced by DynamicDataLoader::initialize().
reset()
void climbing_aid::reset () static
Definition at line 127 of file climbing.cpp.
 {
     climbing_aid_factory.reset();
     climbing_lookup.clear();
     climbing_aid_default_ptr = nullptr;
 }
References climbing_aid_default_ptr, anonymous_namespace{climbing.cpp}::climbing_aid_factory, and climbing_lookup.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
base_condition
condition climbing_aid::base_condition
Definition at line 149 of file climbing.h.
Referenced by game::climb_down_using(), finalize(), and load().
down
struct climbing_aid::down_t climbing_aid::down
Referenced by game::climb_down_using(), finalize(), and load().
id
climbing_aid_id climbing_aid::id
Definition at line 145 of file climbing.h.
Referenced by finalize().
slip_chance_mod
int climbing_aid::slip_chance_mod = 0
Definition at line 152 of file climbing.h.
Referenced by finalize(), get_safest(), load(), and game::slip_down_chance().
src
std::vector<std::pair<climbing_aid_id, mod_id> > climbing_aid::src
Definition at line 146 of file climbing.h.
Referenced by load_climbing_aid().
was_loaded
bool climbing_aid::was_loaded = false
Definition at line 73 of file climbing.h.
Referenced by check_consistency(), climbing_aid::down_t::deserialize(), finalize(), and load().
The documentation for this class was generated from the following files:
src/climbing.h
src/climbing.cpp