Cataclysm DDA: mod_manager Class Reference
mod_manager Class Reference
#include <mod_manager.h>
Public Types
using t_mod_list = std::vector< mod_id >
Public Member Functions
mod_manager ()
~mod_manager ()
void refresh_mod_list ()
Reload the map of available mods (mod_map).
std::vector< mod_id > all_mods () const
dependency_tree & get_tree ()
Returns the dependency tree for the loaded mods.
void clear ()
Clear mod_map and delete dependency_tree.
bool copy_mod_contents (const t_mod_list &mods_to_copy, const cata_path &output_base_path)
Copy the json files of the listed mods into the given folder (output_base_path)
void save_mods_list (const WORLD *world) const
Save list of mods that are active in that world to the world folder.
void load_mods_list (WORLD *world) const
Load list of mods that should be active in that world.
const t_mod_list & get_default_mods () const
bool set_default_mods (const t_mod_list &mods)
const std::vector< mod_id > & get_usable_mods () const
Private Member Functions
void load_mods_from (const cata_path &path)
Load all modinfo.json files (recursively) from the given root.
void load_mod_info (const cata_path &info_file_path)
Load all mod information from a json file.
void load_modfile (const JsonObject &jo, const cata_path &path)
Load mod info from a json object.
bool set_default_mods (const mod_id &ident)
void remove_mod (const mod_id &ident)
void remove_invalid_mods (std::vector< mod_id > &mods) const
void load_replacement_mods (const cata_path &path)
void set_usable_mods ()
Static Private Member Functions
static cata_path get_mods_list_file (const WORLD *world)
Private Attributes
friend mod_id
pimpl< dependency_tree > tree
std::map< mod_id, MOD_INFORMATION > mod_map
The map of known mods, key is the mod ident.
t_mod_list default_mods
std::map< mod_id, mod_id > mod_replacements
Second field is optional replacement mod.
std::vector< mod_id > usable_mods
Friends
class mod_ui
class worldfactory
Detailed Description
Definition at line 65 of file mod_manager.h.
Member Typedef Documentation
t_mod_list
using mod_manager::t_mod_list = std::vector<mod_id>
Definition at line 68 of file mod_manager.h.
Constructor & Destructor Documentation
mod_manager()
mod_manager::mod_manager ()
Definition at line 112 of file mod_manager.cpp.
 {
     load_replacement_mods( PATH_INFO::mods_replacements() );
     refresh_mod_list();
     set_usable_mods();
 }
References load_replacement_mods(), PATH_INFO::mods_replacements(), refresh_mod_list(), and set_usable_mods().
~mod_manager()
mod_manager::~mod_manager () default
Member Function Documentation
all_mods()
std::vector< mod_id > mod_manager::all_mods () const
Definition at line 121 of file mod_manager.cpp.
 {
     std::vector<mod_id> result;
     std::transform( mod_map.begin(), mod_map.end(),
     std::back_inserter( result ), []( const decltype( mod_manager::mod_map )::value_type & pair ) {
         return pair.first;
     } );
     return result;
 }
References mod_map.
clear()
void mod_manager::clear ()
Clear mod_map and delete dependency_tree.
Definition at line 136 of file mod_manager.cpp.
 {
     tree->clear();
     mod_map.clear();
     default_mods.clear();
 }
References default_mods, mod_map, and tree.
Referenced by refresh_mod_list().
copy_mod_contents()
bool mod_manager::copy_mod_contents (const t_mod_list & mods_to_copy, const cata_path & output_base_path)
Copy the json files of the listed mods into the given folder (output_base_path)
Parameters
mods_to_copy A list (of idents) of mods whose json data should be copied.
output_base_path The folder where to put the copies. The function creates a sub folder for each mod and puts the files there. The original folder structure is retained.
Definition at line 293 of file mod_manager.cpp.
 {
     if( mods_to_copy.empty() ) {
         // nothing to copy, so technically we succeeded already!
         return true;
     }
     std::vector<std::string> search_extensions;
     search_extensions.emplace_back( ".json" );
     DebugLog( D_INFO, DC_ALL ) << "Copying mod contents into directory: " << output_base_path;
     if( !assure_dir_exist( output_base_path ) ) {
         DebugLog( D_ERROR, DC_ALL ) << "Unable to create or open mod directory at [" << output_base_path <<
                                     "] for saving";
         return false;
     }
     for( size_t i = 0; i < mods_to_copy.size(); ++i ) {
         const MOD_INFORMATION &mod = *mods_to_copy[i];
         // now to get all of the json files inside of the mod and get them ready to copy
         auto input_files = get_files_from_path( ".json", mod.path, true, true );
         auto input_dirs  = get_directories_with( search_extensions, mod.path, true );
         cata_path mod_base_path = mod.path;
         if( input_files.empty() && mod.path.get_relative_path().filename().u8string() == MOD_SEARCH_FILE ) {
             // Self contained mod, all data is inside the modinfo.json file
             input_files.push_back( mod.path );
             mod_base_path = mod.path.parent_path();
         }
         if( input_files.empty() ) {
             continue;
         }
         // create needed directories
         // NOLINTNEXTLINE(cata-translate-string-literal)
         const cata_path cur_mod_dir = output_base_path / string_format( "mod_%05d", i + 1 );
         std::queue<cata_path> dir_to_make;
         dir_to_make.push( cur_mod_dir );
         for( cata_path &input_dir : input_dirs ) {
             dir_to_make.push( cur_mod_dir / input_dir.get_relative_path().lexically_relative(
                                   mod_base_path.get_relative_path() ) );
         }
         while( !dir_to_make.empty() ) {
             if( !assure_dir_exist( dir_to_make.front() ) ) {
                 DebugLog( D_ERROR, DC_ALL ) << "Unable to create or open mod directory at [" <<
                                             dir_to_make.front() << "] for saving";
             }
             dir_to_make.pop();
         }
         // trim file paths from full length down to just /data forward
         for( cata_path &input_file : input_files ) {
             cata_path output_path = cur_mod_dir / ( input_file.get_relative_path().lexically_relative(
                     mod_base_path.get_relative_path() ) );
             copy_file( input_file, output_path );
         }
     }
     return true;
 }
References assure_dir_exist(), copy_file(), D_ERROR, D_INFO, DC_ALL, DebugLog(), get_directories_with(), get_files_from_path(), cata_path::get_relative_path(), MOD_SEARCH_FILE(), and string_format().
get_default_mods()
const mod_manager::t_mod_list & mod_manager::get_default_mods () const
Definition at line 434 of file mod_manager.cpp.
 {
     return default_mods;
 }
References default_mods.
get_mods_list_file()
cata_path mod_manager::get_mods_list_file (const WORLD * world) static private
Returns
path of a file in the world folder that contains the list of mods that should be loaded for this world.
Definition at line 380 of file mod_manager.cpp.
 {
     return world->folder_path_path() / "mods.json";
 }
References WORLD::folder_path_path().
Referenced by load_mods_list(), and save_mods_list().
get_tree()
dependency_tree & mod_manager::get_tree ()
Returns the dependency tree for the loaded mods.
Returns
dependency_tree
Definition at line 131 of file mod_manager.cpp.
 {
     return *tree;
 }
References tree.
get_usable_mods()
const std::vector<mod_id>& mod_manager::get_usable_mods () const inline
Definition at line 113 of file mod_manager.h.
{
             return usable_mods;
         }
References usable_mods.
load_mod_info()
void mod_manager::load_mod_info (const cata_path & info_file_path) private
Load all mod information from a json file.
(
See also
load_modfile)
Definition at line 360 of file mod_manager.cpp.
 {
     const cata_path main_path = info_file_path.parent_path();
     read_from_file_optional_json( info_file_path, [&]( const JsonValue & jsin ) {
         if( jsin.test_object() ) {
             // find type and dispatch single object
             JsonObject jo = jsin.get_object();
             load_modfile( jo, main_path );
         } else if( jsin.test_array() ) {
             // find type and dispatch each object until array close
             for( JsonObject jo : jsin.get_array() ) {
                 load_modfile( jo, main_path );
             }
         } else {
             // not an object or an array?
             jsin.throw_error( "expected array or object" );
         }
     } );
 }
References cata_path::parent_path(), read_from_file_optional_json(), JsonValue::test_array(), JsonValue::test_object(), and JsonValue::throw_error().
Referenced by load_mods_from(), and refresh_mod_list().
load_modfile()
void mod_manager::load_modfile (const JsonObject & jo, const cata_path & path) private
Load mod info from a json object.
Put the loaded modinfo directly into mod_map.
Exceptions
JsonError on all kind of errors.
Definition at line 210 of file mod_manager.cpp.
 {
     if( !jo.has_string( "type" ) || jo.get_string( "type" ) != "MOD_INFO" ) {
         // Ignore anything that is not a mod-info
         jo.allow_omitted_members();
         return;
     }
     // TEMPORARY until 0.G: Remove "ident" support
     const mod_id m_ident( jo.has_string( "ident" ) ? jo.get_string( "ident" ) : jo.get_string( "id" ) );
     // can't use string_id::is_valid as the global mod_manger instance does not exist yet
     if( mod_map.count( m_ident ) > 0 ) {
         // TODO: change this to make unique ident for the mod
         // (instead of discarding it?)
         debugmsg( "there is already a mod with ident %s", m_ident.c_str() );
         return;
     }
     translation m_name;
     jo.read( "name", m_name );
     std::string m_cat = jo.get_string( "category", "" );
     std::pair<int, translation> p_cat = {-1, translation()};
     bool bCatFound = false;
     do {
         for( size_t i = 0; i < get_mod_list_categories().size(); ++i ) {
             if( get_mod_list_categories()[i].first == m_cat ) {
                 p_cat = { static_cast<int>( i ), get_mod_list_categories()[i].second };
                 bCatFound = true;
                 break;
             }
         }
         if( !bCatFound && !m_cat.empty() ) {
             m_cat.clear();
         } else {
             break;
         }
     } while( !bCatFound );
     MOD_INFORMATION modfile;
     modfile.ident = m_ident;
     modfile.name_ = m_name;
     modfile.category = p_cat;
     std::string mod_json_path;
     if( assign( jo, "path", mod_json_path ) ) {
         modfile.path = path / mod_json_path;
     } else {
         modfile.path = path;
     }
     assign( jo, "authors", modfile.authors );
     assign( jo, "maintainers", modfile.maintainers );
     assign( jo, "description", modfile.description );
     assign( jo, "version", modfile.version );
     assign( jo, "dependencies", modfile.dependencies );
     assign( jo, "core", modfile.core );
     assign( jo, "obsolete", modfile.obsolete );
     if( std::find( modfile.dependencies.begin(), modfile.dependencies.end(),
                    modfile.ident ) != modfile.dependencies.end() ) {
         jo.throw_error_at( "dependencies", "mod specifies self as a dependency" );
     }
     mod_map[modfile.ident] = std::move( modfile );
 }
References JsonObject::allow_omitted_members(), assign(), MOD_INFORMATION::authors, string_id< T >::c_str(), MOD_INFORMATION::category, MOD_INFORMATION::core, debugmsg, MOD_INFORMATION::dependencies, MOD_INFORMATION::description, get_mod_list_categories(), JsonObject::get_string(), JsonObject::has_string(), MOD_INFORMATION::ident, MOD_INFORMATION::maintainers, mod_map, MOD_INFORMATION::name_, MOD_INFORMATION::obsolete, MOD_INFORMATION::path, JsonObject::read(), JsonObject::throw_error_at(), and MOD_INFORMATION::version.
load_mods_from()
void mod_manager::load_mods_from (const cata_path & path) private
Load all modinfo.json files (recursively) from the given root.
Parameters
path The root folder from which the modinfo files are searched.
Definition at line 200 of file mod_manager.cpp.
 {
     if( !dir_exist( path.get_unrelative_path() ) ) {
         return; // don't try to enumerate non-existing directories
     }
     for( cata_path &mod_file : get_files_from_path( MOD_SEARCH_FILE, path, true ) ) {
         load_mod_info( mod_file );
     }
 }
References dir_exist(), get_files_from_path(), cata_path::get_unrelative_path(), load_mod_info(), and MOD_SEARCH_FILE().
Referenced by refresh_mod_list().
load_mods_list()
void mod_manager::load_mods_list (WORLD * world) const
Load list of mods that should be active in that world.
Definition at line 403 of file mod_manager.cpp.
 {
     if( world == nullptr ) {
         return;
     }
     std::vector<mod_id> &amo = world->active_mod_order;
     amo.clear();
     bool obsolete_mod_found = false;
     read_from_file_optional_json( get_mods_list_file( world ), [&]( const JsonArray & jsin ) {
         for( const std::string line : jsin ) {
             const mod_id mod( line );
             if( std::find( amo.begin(), amo.end(), mod ) != amo.end() ) {
                 continue;
             }
             const auto iter = mod_replacements.find( mod );
             if( iter != mod_replacements.end() ) {
                 if( !iter->second.is_empty() ) {
                     amo.push_back( iter->second );
                 }
                 obsolete_mod_found = true;
                 continue;
             }
             amo.push_back( mod );
         }
     } );
     if( obsolete_mod_found ) {
         // If we found an obsolete mod, overwrite the mod list without the obsolete one.
         save_mods_list( world );
     }
 }
References WORLD::active_mod_order, get_mods_list_file(), line, mod_replacements, read_from_file_optional_json(), and save_mods_list().
load_replacement_mods()
void mod_manager::load_replacement_mods (const cata_path & path) private
Definition at line 102 of file mod_manager.cpp.
 {
     read_from_file_optional_json( path, [&]( const JsonArray & jsin ) {
         for( JsonArray arr : jsin ) {
             mod_replacements.emplace( mod_id( arr.get_string( 0 ) ),
                                       mod_id( arr.size() > 1 ? arr.get_string( 1 ) : "" ) );
         }
     } );
 }
References mod_id, mod_replacements, and read_from_file_optional_json().
Referenced by mod_manager().
refresh_mod_list()
void mod_manager::refresh_mod_list ()
Reload the map of available mods (mod_map).
This also reloads the dependency tree.
Definition at line 143 of file mod_manager.cpp.
 {
     clear();
     std::map<mod_id, std::vector<mod_id>> mod_dependency_map;
     load_mods_from( PATH_INFO::moddir() );
     load_mods_from( PATH_INFO::user_moddir_path() );
     if( file_exist( PATH_INFO::mods_dev_default() ) ) {
         load_mod_info( PATH_INFO::mods_dev_default() );
     }
     if( file_exist( PATH_INFO::mods_user_default() ) ) {
         load_mod_info( PATH_INFO::mods_user_default() );
     }
     if( !set_default_mods( MOD_INFORMATION_user_default ) ) {
         set_default_mods( MOD_INFORMATION_dev_default );
     }
     // remove these mods from the list, so they do not appear to the user
     remove_mod( MOD_INFORMATION_user_default );
     remove_mod( MOD_INFORMATION_dev_default );
     for( auto &elem : mod_map ) {
         const auto &deps = elem.second.dependencies;
         mod_dependency_map[elem.second.ident] = std::vector<mod_id>( deps.begin(), deps.end() );
     }
     tree->init( mod_dependency_map );
 }
References clear(), file_exist(), load_mod_info(), load_mods_from(), MOD_INFORMATION_dev_default, MOD_INFORMATION_user_default, mod_map, PATH_INFO::moddir(), PATH_INFO::mods_dev_default(), PATH_INFO::mods_user_default(), remove_mod(), set_default_mods(), tree, and PATH_INFO::user_moddir_path().
Referenced by mod_manager().
remove_invalid_mods()
void mod_manager::remove_invalid_mods (std::vector< mod_id > & mods) const private
Definition at line 179 of file mod_manager.cpp.
 {
     mods.erase( std::remove_if( mods.begin(), mods.end(), [this]( const mod_id & mod ) {
         return mod_map.count( mod ) == 0;
     } ), mods.end() );
 }
References anonymous_namespace{item_tname.cpp}::mods().
Referenced by set_default_mods().
remove_mod()
void mod_manager::remove_mod (const mod_id & ident) private
Definition at line 171 of file mod_manager.cpp.
 {
     const auto a = mod_map.find( ident );
     if( a != mod_map.end() ) {
         mod_map.erase( a );
     }
 }
References a, and mod_map.
Referenced by refresh_mod_list().
save_mods_list()
void mod_manager::save_mods_list (const WORLD * world) const
Save list of mods that are active in that world to the world folder.
Definition at line 385 of file mod_manager.cpp.
 {
     if( world == nullptr ) {
         return;
     }
     const cata_path path = get_mods_list_file( world );
     if( world->active_mod_order.empty() ) {
         // If we were called from load_mods_list to prune the list,
         // and it's empty now, delete the file.
         remove_file( path.get_unrelative_path() );
         return;
     }
     write_to_file( path, [&]( std::ostream & fout ) {
         JsonOut json( fout, true ); // pretty-print
         json.write( world->active_mod_order );
     }, _( "list of mods" ) );
 }
References _, WORLD::active_mod_order, get_mods_list_file(), cata_path::get_unrelative_path(), remove_file(), JsonOut::write(), and write_to_file().
Referenced by load_mods_list().
set_default_mods() [1/2]
bool mod_manager::set_default_mods (const mod_id & ident) private
Definition at line 186 of file mod_manager.cpp.
 {
     // can't use string_id::is_valid as the global mod_manger instance does not exist yet
     const auto iter = mod_map.find( ident );
     if( iter == mod_map.end() ) {
         return false;
     }
     const MOD_INFORMATION &mod = iter->second;
     auto deps = std::vector<mod_id>( mod.dependencies.begin(), mod.dependencies.end() );
     remove_invalid_mods( deps );
     default_mods = deps;
     return true;
 }
References default_mods, mod_map, and remove_invalid_mods().
set_default_mods() [2/2]
bool mod_manager::set_default_mods (const t_mod_list & mods)
Definition at line 279 of file mod_manager.cpp.
 {
     default_mods = mods;
     return write_to_file( PATH_INFO::mods_user_default(), [&]( std::ostream & fout ) {
         JsonOut json( fout, true ); // pretty-print
         json.start_object();
         json.member( "type", "MOD_INFO" );
         json.member( "id", "user:default" );
         json.member( "dependencies" );
         json.write( mods );
         json.end_object();
     }, _( "list of default mods" ) );
 }
References _, default_mods, JsonOut::end_object(), JsonOut::member(), anonymous_namespace{item_tname.cpp}::mods(), PATH_INFO::mods_user_default(), JsonOut::start_object(), JsonOut::write(), and write_to_file().
Referenced by refresh_mod_list().
set_usable_mods()
void mod_manager::set_usable_mods () private
Definition at line 446 of file mod_manager.cpp.
 {
     std::vector<mod_id> available_cores;
     std::vector<mod_id> available_supplementals;
     std::vector<mod_id> ordered_mods;
     std::vector<const MOD_INFORMATION *> mods;
     for( const auto &pair : mod_map ) {
         if( !pair.second.obsolete ) {
             mods.push_back( &pair.second );
         }
     }
     std::sort( mods.begin(), mods.end(), &compare_mod_by_name_and_category );
     for( const MOD_INFORMATION *const modinfo : mods ) {
         if( modinfo->core ) {
             available_cores.push_back( modinfo->ident );
         } else {
             available_supplementals.push_back( modinfo->ident );
         }
     }
     ordered_mods.insert( ordered_mods.begin(), available_supplementals.begin(),
                          available_supplementals.end() );
     ordered_mods.insert( ordered_mods.begin(), available_cores.begin(), available_cores.end() );
     usable_mods = ordered_mods;
 }
References compare_mod_by_name_and_category(), mod_map, anonymous_namespace{item_tname.cpp}::mods(), and usable_mods.
Referenced by mod_manager().
Friends And Related Function Documentation
mod_ui
friend class mod_ui friend
Definition at line 119 of file mod_manager.h.
worldfactory
friend class worldfactory friend
Definition at line 120 of file mod_manager.h.
Member Data Documentation
default_mods
t_mod_list mod_manager::default_mods private
Definition at line 157 of file mod_manager.h.
Referenced by clear(), get_default_mods(), and set_default_mods().
mod_id
friend mod_manager::mod_id private
Definition at line 121 of file mod_manager.h.
Referenced by load_replacement_mods().
mod_map
std::map<mod_id, MOD_INFORMATION> mod_manager::mod_map private
The map of known mods, key is the mod ident.
Definition at line 156 of file mod_manager.h.
Referenced by all_mods(), clear(), load_modfile(), refresh_mod_list(), remove_mod(), set_default_mods(), and set_usable_mods().
mod_replacements
std::map<mod_id, mod_id> mod_manager::mod_replacements private
Second field is optional replacement mod.
Definition at line 159 of file mod_manager.h.
Referenced by load_mods_list(), and load_replacement_mods().
tree
pimpl<dependency_tree> mod_manager::tree private
Definition at line 151 of file mod_manager.h.
Referenced by clear(), get_tree(), and refresh_mod_list().
usable_mods
std::vector<mod_id> mod_manager::usable_mods private
Definition at line 161 of file mod_manager.h.
Referenced by get_usable_mods(), and set_usable_mods().
The documentation for this class was generated from the following files:
src/mod_manager.h
src/mod_manager.cpp