Cataclysm DDA: scrollingcombattext::cSCT Class Reference
scrollingcombattext::cSCT Class Reference
#include <output.h>
Public Member Functions
cSCT (const point &pos, direction p_oDir, const std::string &p_sText, game_message_type p_gmt, const std::string &p_sText2="", game_message_type p_gmt2=m_neutral, const std::string &p_sType="")
int getStep () const
int getStepOffset () const
int advanceStep ()
int advanceStepOffset ()
int getPosX () const
int getPosY () const
direction getDirection () const
int getInitPosX () const
int getInitPosY () const
std::string getType () const
std::string getText (const std::string &type="full") const
game_message_type getMsgType (const std::string &type="first") const
Private Attributes
point pos
direction oDir
direction oUp
direction oUpRight
direction oRight
direction oDownRight
direction oDown
direction oDownLeft
direction oLeft
direction oUpLeft
point dir
int iStep
int iStepOffset
std::string sText
game_message_type gmt
std::string sText2
game_message_type gmt2
std::string sType
bool iso_mode
Detailed Description
Definition at line 1061 of file output.h.
Constructor & Destructor Documentation
cSCT()
scrollingcombattext::cSCT::cSCT (const point & pos, direction p_oDir, const std::string & p_sText, game_message_type p_gmt, const std::string & p_sText2 = "", game_message_type p_gmt2 = m_neutral, const std::string & p_sType = "")
Definition at line 2881 of file output.cpp.
 {
     pos = p_pos;
     sType = p_sType;
     oDir = p_oDir;
     iso_mode = g->is_tileset_isometric();
     // translate from player relative to screen relative direction
     oUp = iso_mode ? direction::NORTHEAST : direction::NORTH;
     oUpRight = iso_mode ? direction::EAST : direction::NORTHEAST;
     oRight = iso_mode ? direction::SOUTHEAST : direction::EAST;
     oDownRight = iso_mode ? direction::SOUTH : direction::SOUTHEAST;
     oDown = iso_mode ? direction::SOUTHWEST : direction::SOUTH;
     oDownLeft = iso_mode ? direction::WEST : direction::SOUTHWEST;
     oLeft = iso_mode ? direction::NORTHWEST : direction::WEST;
     oUpLeft = iso_mode ? direction::NORTH : direction::NORTHWEST;
     point pairDirXY = displace_XY( oDir );
     dir = pairDirXY;
     if( dir == point_zero ) {
         // This would cause infinite loop otherwise
         oDir = direction::WEST;
         dir.x = -1;
     }
     iStep = 0;
     iStepOffset = 0;
     sText = p_sText;
     gmt = p_gmt;
     sText2 = p_sText2;
     gmt2 = p_gmt2;
 }
References displace_XY(), EAST, g, NORTH, NORTHEAST, NORTHWEST, point_zero, math_opers::pos(), SOUTH, SOUTHEAST, SOUTHWEST, and WEST.
Member Function Documentation
advanceStep()
int scrollingcombattext::cSCT::advanceStep () inline
Definition at line 1096 of file output.h.
{
                     return ++iStep;
                 }
References iStep.
advanceStepOffset()
int scrollingcombattext::cSCT::advanceStepOffset () inline
Definition at line 1099 of file output.h.
{
                     return ++iStepOffset;
                 }
References iStepOffset.
getDirection()
direction scrollingcombattext::cSCT::getDirection () const inline
Definition at line 1104 of file output.h.
{
                     return oDir;
                 }
References oDir.
getInitPosX()
int scrollingcombattext::cSCT::getInitPosX () const inline
Definition at line 1107 of file output.h.
{
                     return pos.x;
                 }
References pos, and point::x.
getInitPosY()
int scrollingcombattext::cSCT::getInitPosY () const inline
Definition at line 1110 of file output.h.
{
                     return pos.y;
                 }
References pos, and point::y.
getMsgType()
game_message_type scrollingcombattext::cSCT::getMsgType (const std::string & type = "first") const
Definition at line 3019 of file output.cpp.
 {
     if( !sText2.empty() ) {
         if( oDir == oUpLeft || oDir == oDownLeft || oDir == oLeft ) {
             if( type == "first" ) {
                 return gmt2;
             }
         } else {
             if( type == "second" ) {
                 return gmt2;
             }
         }
     }
     return gmt;
 }
Referenced by anonymous_namespace{animation.cpp}::draw_sct_curses().
getPosX()
int scrollingcombattext::cSCT::getPosX () const
Definition at line 3036 of file output.cpp.
 {
     if( getStep() > 0 ) {
         int iDirOffset = ( oDir == oRight ) ? 1 : ( ( oDir == oLeft ) ? -1 : 0 );
         if( oDir == oUp || oDir == oDown ) {
             if( iso_mode ) {
                 iDirOffset = ( oDir == oUp ) ? 1 : -1;
             }
             //Center text
             iDirOffset -= utf8_width( getText() ) / 2;
         } else if( oDir == oLeft || oDir == oDownLeft || oDir == oUpLeft ) {
             //Right align text
             iDirOffset -= utf8_width( getText() ) - 1;
         }
         return pos.x + iDirOffset + ( dir.x * ( ( sType == "hp" ) ? ( getStepOffset() + 1 ) :
                                                 ( getStepOffset() * ( iso_mode ? 2 : 1 ) + getStep() ) ) );
     }
     return 0;
 }
References math_opers::pos(), and utf8_width().
Referenced by anonymous_namespace{animation.cpp}::draw_sct_curses().
getPosY()
int scrollingcombattext::cSCT::getPosY () const
Definition at line 3062 of file output.cpp.
 {
     if( getStep() > 0 ) {
         int iDirOffset = ( oDir == oDown ) ? 1 : ( ( oDir == oUp ) ? -1 : 0 );
         if( iso_mode ) {
             if( oDir == oLeft || oDir == oRight ) {
                 iDirOffset = ( oDir == oRight ) ? 1 : -1;
             }
             if( oDir == oUp || oDir == oDown ) {
                 //Center text
                 iDirOffset -= utf8_width( getText() ) / 2;
             } else if( oDir == oLeft || oDir == oDownLeft || oDir == oUpLeft ) {
                 //Right align text
                 iDirOffset -= utf8_width( getText() ) - 1;
             }
         }
         return pos.y + iDirOffset + ( dir.y * ( ( iso_mode && sType == "hp" ) ? ( getStepOffset() + 1 ) :
                                                 ( getStepOffset() * ( iso_mode ? 2 : 1 ) + getStep() ) ) );
     }
     return 0;
 }
References math_opers::pos(), and utf8_width().
Referenced by anonymous_namespace{animation.cpp}::draw_sct_curses().
getStep()
int scrollingcombattext::cSCT::getStep () const inline
Definition at line 1090 of file output.h.
{
                     return iStep;
                 }
References iStep.
Referenced by anonymous_namespace{animation.cpp}::draw_sct_curses().
getStepOffset()
int scrollingcombattext::cSCT::getStepOffset () const inline
Definition at line 1093 of file output.h.
{
                     return iStepOffset;
                 }
References iStepOffset.
getText()
std::string scrollingcombattext::cSCT::getText (const std::string & type = "full") const
Definition at line 2995 of file output.cpp.
 {
     if( !sText2.empty() ) {
         if( oDir == oUpLeft || oDir == oDownLeft || oDir == oLeft ) {
             if( type == "first" ) {
                 return sText2 + " ";
             } else if( type == "full" ) {
                 return sText2 + " " + sText;
             }
         } else {
             if( type == "second" ) {
                 return " " + sText2;
             } else if( type == "full" ) {
                 return sText + " " + sText2;
             }
         }
     } else if( type == "second" ) {
         return {};
     }
     return sText;
 }
Referenced by anonymous_namespace{animation.cpp}::draw_sct_curses().
getType()
std::string scrollingcombattext::cSCT::getType () const inline
Definition at line 1113 of file output.h.
{
                     return sType;
                 }
References sType.
Member Data Documentation
dir
point scrollingcombattext::cSCT::dir private
Definition at line 1074 of file output.h.
gmt
game_message_type scrollingcombattext::cSCT::gmt private
Definition at line 1078 of file output.h.
gmt2
game_message_type scrollingcombattext::cSCT::gmt2 private
Definition at line 1080 of file output.h.
iso_mode
bool scrollingcombattext::cSCT::iso_mode private
Definition at line 1082 of file output.h.
iStep
int scrollingcombattext::cSCT::iStep private
Definition at line 1075 of file output.h.
Referenced by advanceStep(), and getStep().
iStepOffset
int scrollingcombattext::cSCT::iStepOffset private
Definition at line 1076 of file output.h.
Referenced by advanceStepOffset(), and getStepOffset().
oDir
direction scrollingcombattext::cSCT::oDir private
Definition at line 1065 of file output.h.
Referenced by getDirection().
oDown
direction scrollingcombattext::cSCT::oDown private
Definition at line 1070 of file output.h.
oDownLeft
direction scrollingcombattext::cSCT::oDownLeft private
Definition at line 1071 of file output.h.
oDownRight
direction scrollingcombattext::cSCT::oDownRight private
Definition at line 1069 of file output.h.
oLeft
direction scrollingcombattext::cSCT::oLeft private
Definition at line 1072 of file output.h.
oRight
direction scrollingcombattext::cSCT::oRight private
Definition at line 1068 of file output.h.
oUp
direction scrollingcombattext::cSCT::oUp private
Definition at line 1066 of file output.h.
oUpLeft
direction scrollingcombattext::cSCT::oUpLeft private
Definition at line 1073 of file output.h.
oUpRight
direction scrollingcombattext::cSCT::oUpRight private
Definition at line 1067 of file output.h.
pos
point scrollingcombattext::cSCT::pos private
Definition at line 1064 of file output.h.
Referenced by getInitPosX(), and getInitPosY().
sText
std::string scrollingcombattext::cSCT::sText private
Definition at line 1077 of file output.h.
sText2
std::string scrollingcombattext::cSCT::sText2 private
Definition at line 1079 of file output.h.
sType
std::string scrollingcombattext::cSCT::sType private
Definition at line 1081 of file output.h.
Referenced by getType().
The documentation for this class was generated from the following files:
src/output.h
src/output.cpp