Cataclysm DDA: weapon_inventory_preset Class Reference
weapon_inventory_preset Class Reference
Public Member Functions
weapon_inventory_preset (const Character &you)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Private Member Functions
bool deals_melee_damage (const item &it) const
std::string get_damage_string (float damage, bool display_zeroes=false) const
Private Attributes
const Character & you
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 1667 of file game_inventory.cpp.
Constructor & Destructor Documentation
weapon_inventory_preset()
weapon_inventory_preset::weapon_inventory_preset (const Character & you) inline explicit
Definition at line 1670 of file game_inventory.cpp.
                                                                  : you( you ) {
             append_cell( [ this ]( const item_location & loc ) {
                 if( !loc->is_gun() ) {
                     return std::string();
                 }
                 const int total_damage = loc->gun_damage( true ).total_damage();
                 if( loc->ammo_data() && loc->ammo_remaining() ) {
                     const int basic_damage = loc->gun_damage( false ).total_damage();
                     const damage_instance &damage = loc->ammo_data()->ammo->damage;
                     if( !damage.empty() ) {
                         const float ammo_mult = damage.damage_units.front().unconditional_damage_mult;
                         if( ammo_mult != 1.0f ) {
                             return string_format( "%s<color_light_gray>*</color>%s <color_light_gray>=</color> %s",
                                                   get_damage_string( basic_damage, true ),
                                                   get_damage_string( ammo_mult, true ),
                                                   get_damage_string( total_damage, true )
                                                 );
                         }
                     }
                     const int ammo_damage = damage.total_damage();
                     return string_format( "%s<color_light_gray>+</color>%s <color_light_gray>=</color> %s",
                                           get_damage_string( basic_damage, true ),
                                           get_damage_string( ammo_damage, true ),
                                           get_damage_string( total_damage, true )
                                         );
                 } else {
                     return get_damage_string( total_damage );
                 }
             }, pgettext( "Shot as damage", "SHOT" ) );
             for( const damage_type &dt : damage_type::get_all() ) {
                 if( !dt.melee_only ) {
                     continue;
                 }
                 const damage_type_id &dtid = dt.id;
                 append_cell( [ this, dtid ]( const item_location & loc ) {
                     return get_damage_string( loc->damage_melee( dtid ) );
                 }, to_upper_case( dt.name.translated() ) );
             }
             append_cell( [ this ]( const item_location & loc ) {
                 if( deals_melee_damage( *loc ) ) {
                     return good_bad_none( loc->type->m_to_hit );
                 }
                 return std::string();
             }, _( "MELEE" ) );
             append_cell( [ this ]( const item_location & loc ) {
                 if( deals_melee_damage( *loc ) ) {
                     return string_format( "<color_yellow>%d</color>", this->you.attack_speed( *loc ) );
                 }
                 return std::string();
             }, _( "MOVES" ) );
             append_cell( [this]( const item_location & loc ) {
                 return string_format( "<color_yellow>%d</color>",
                                       loc.obtain_cost( this->you ) + ( this->you.is_wielding( *loc.get_item() ) ? 0 :
                                               ( *loc.get_item() ).on_wield_cost( this->you ) ) );
             }, _( "WIELD COST" ) );
         }
References item::ammo_data(), item::ammo_remaining(), inventory_selector_preset::append_cell(), get_damage_string(), item::gun_damage(), item::is_gun(), string_format(), and damage_instance::total_damage().
Member Function Documentation
deals_melee_damage()
bool weapon_inventory_preset::deals_melee_damage (const item & it) const inline private
Definition at line 1749 of file game_inventory.cpp.
{
             for( const damage_type &dt : damage_type::get_all() ) {
                 if( it.damage_melee( dt.id ) ) {
                     return true;
                 }
             }
             return false;
         }
References item::damage_melee(), and damage_type::get_all().
get_damage_string()
std::string weapon_inventory_preset::get_damage_string (float damage, bool display_zeroes = false) const inline private
Definition at line 1758 of file game_inventory.cpp.
{
             return ( damage || display_zeroes ) ?
                    string_format( "<color_yellow>%g</color>", damage ) : std::string();
         }
References string_format().
Referenced by weapon_inventory_preset().
get_denial()
std::string weapon_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Reimplemented in saw_stock_inventory_preset, and saw_barrel_inventory_preset.
Definition at line 1738 of file game_inventory.cpp.
{
             const auto ret = you.can_wield( *loc );
             if( !ret.success() ) {
                 return trim_trailing_punctuations( ret.str() );
             }
             return std::string();
         }
References Character::can_wield(), cata::hash64_detail::ret, and trim_trailing_punctuations().
is_shown()
bool weapon_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Reimplemented in saw_stock_inventory_preset, saw_barrel_inventory_preset, and holster_inventory_preset.
Definition at line 1734 of file game_inventory.cpp.
{
             return loc->made_of( phase_id::SOLID );
         }
References item::made_of(), and SOLID.
Member Data Documentation
you
const Character& weapon_inventory_preset::you private
Definition at line 1763 of file game_inventory.cpp.
The documentation for this class was generated from the following file:
src/game_inventory.cpp