Cataclysm DDA: faction_price_rules_reader Class Reference
faction_price_rules_reader Class Reference
#include <faction.h>
Static Public Member Functions
static faction_price_rule get_next (JsonValue &jv)
Additional Inherited Members
Public Member Functions inherited from generic_typed_reader< faction_price_rules_reader >
void insert_values_from (const JsonObject &jo, const std::string_view member_name, C &container) const
void insert_next (JsonValue &jv, C &container) const
void erase_values_from (const JsonObject &jo, const std::string_view member_name, C &container) const
void erase_next (JsonValue &jv, C &container) const
bool operator() (const JsonObject &jo, const std::string_view member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string_view member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string_view name, C &) const
bool do_relative (const JsonObject &jo, const std::string_view name, C &member) const
bool read_normal (const JsonObject &jo, const std::string_view name, C &member) const
Detailed Description
Definition at line 87 of file faction.h.
Member Function Documentation
get_next()
faction_price_rule faction_price_rules_reader::get_next (JsonValue & jv) static
Definition at line 111 of file faction.cpp.
 {
     JsonObject jo = jv.get_object();
     faction_price_rule ret( icg_entry_reader::_part_get_next( jo ) );
     optional( jo, false, "markup", ret.markup, 1.0 );
     optional( jo, false, "premium", ret.premium, 1.0 );
     optional( jo, false, "fixed_adj", ret.fixed_adj, std::nullopt );
     optional( jo, false, "price", ret.price, std::nullopt );
     return ret;
 }
References icg_entry_reader::_part_get_next(), JsonValue::get_object(), optional(), and cata::hash64_detail::ret.
The documentation for this class was generated from the following files:
src/faction.h
src/faction.cpp