Cataclysm DDA: string_id< T > Class Template Reference
string_id< T > Class Template Reference
#include <string_id.h>
Public Types
using value_type = T
using This = string_id< T >
using Identity = std::conditional_t< string_id_params< T >::dynamic, string_identity_dynamic, string_identity_static >
using LexCmp = lexicographic< T >
Public Member Functions
template<typename S , class = std::enable_if_t<std::is_convertible_v<S, std::string>>>
string_id (S &&id)
Forwarding constructor, forwards any parameter to the std::string constructor to create the id string.
string_id (const std::string_view id)
string_id ()
Default constructor constructs an empty id string.
bool operator< (const This &rhs) const
Comparison, only useful when the id is used in std::map or std::set as key.
bool operator== (const This &rhs) const
The usual comparator, compares the string id as usual.
bool operator!= (const This &rhs) const
The usual comparator, compares the string id as usual.
const char * c_str () const
Interface to the plain C-string of the id.
const std::string & str () const
Returns the identifier as plain std::string.
operator std::string () const
int_id< T > id () const
Translate the string based it to the matching integer based id.
int_id< T > id_or (const int_id< T > &fallback) const
Translate the string based it to the matching integer based id.
const T & obj () const
Returns the actual object this id refers to.
const T & operator* () const
const T * operator-> () const
bool is_valid () const
Returns whether this id is valid, that means whether it refers to an existing object.
bool is_empty () const
Returns whether this id is empty.
bool is_null () const
Returns whether this represents the id of the null-object (in which case it's the null-id).
operator bool () const
Same as !is_null, basically one can use it to check for the id referring to an actual object.
bool is_valid () const
const nested_mapgen & obj () const
const VehiclePlacement & obj () const
bool is_valid () const
const VehicleSpawn & obj () const
bool is_valid () const
Static Public Member Functions
static const string_id< T > & NULL_ID ()
Returns a null id whose string_id<T>::is_null() must always return true.
Private Member Functions
void set_cid_version (int cid, int64_t version) const
Private Attributes
int64_t _version = INVALID_VERSION
int _cid = INVALID_CID
Identity _id
Friends
class generic_factory< T >
struct std::hash< string_id< T > >
std::ostream & operator<< (std::ostream &os, const string_id &s)
Related Functions
(Note that these are not member functions.)
template<>
bool is_valid () const
template<>
bool is_valid () const
template<>
const ammo_effect & obj () const
template<>
int_id< ammo_effect > id () const
template<>
bodypart_id id () const
template<>
const character_modifier & obj () const
template<>
bool is_valid () const
template<>
bool is_valid () const
template<>
const clothing_mod & obj () const
template<>
bool is_valid () const
template<>
const construction_group & obj () const
template<>
const damage_type & obj () const
template<>
bool is_valid () const
template<>
bool is_valid () const
template<>
const field_type & obj () const
template<>
int_id< field_type > id () const
template<>
const ter_t & obj () const
template<>
bool is_valid () const
template<>
bool is_valid () const
template<>
const furn_t & obj () const
template<>
int_id< furn_t > id () const
template<>
int_id< monfaction > id () const
template<>
const monfaction & obj () const
template<>
const mon_flag & obj () const
template<>
bool is_valid () const
template<>
int_id< oter_type_t > id () const
template<>
const oter_type_t & obj () const
template<>
const profession & obj () const
template<>
bool is_valid () const
template<>
sub_bodypart_id id () const
template<>
bool is_valid () const
template<>
int_id< trap > id () const
template<>
int_id (const string_id< trap > &id)
template<>
const trap & obj () const
template<>
bool is_valid () const
Detailed Description
template<typename T>
class string_id< T >
Definition at line 197 of file string_id.h.
Member Typedef Documentation
Identity
template<typename T > using string_id< T >::Identity = std::conditional_t<string_id_params<T>::dynamic, string_identity_dynamic, string_identity_static>
Definition at line 203 of file string_id.h.
LexCmp
template<typename T > using string_id< T >::LexCmp = lexicographic<T>
Definition at line 206 of file string_id.h.
This
template<typename T > using string_id< T >::This = string_id<T>
Definition at line 201 of file string_id.h.
value_type
template<typename T > using string_id< T >::value_type = T
Definition at line 200 of file string_id.h.
Constructor & Destructor Documentation
string_id() [1/3]
template<typename T > template<typename S , class = std::enable_if_t<std::is_convertible_v<S, std::string>>> string_id< T >::string_id (S && id) inline explicit
Forwarding constructor, forwards any parameter to the std::string constructor to create the id string.
This allows plain C-strings, and std::strings to be used.
Definition at line 216 of file string_id.h.
 : _id( std::forward<S>( id ) ) {}
string_id() [2/3]
template<typename T > string_id< T >::string_id (const std::string_view id) inline explicit
Definition at line 220 of file string_id.h.
 : string_id( std::string( id ) ) {}
string_id() [3/3]
template<typename T > string_id< T >::string_id () inline
Default constructor constructs an empty id string.
Note that this id class does not enforce empty id strings (or any specific string at all) to be special. Every string (including the empty one) may be a valid id.
Definition at line 226 of file string_id.h.
 : _id() {} // NOLINT(clang-analyzer-optin.cplusplus.UninitializedObject)
Member Function Documentation
c_str()
template<typename T > const char* string_id< T >::c_str () const inline
Interface to the plain C-string of the id.
This function mimics the std::string object. Ids are often used in debug messages, where they are forwarded as C-strings to be included in the format string, e.g. debugmsg("invalid id: %s", id.c_str())
Definition at line 252 of file string_id.h.
{
         return _id.str().c_str();
     }
References string_id< T >::_id.
Referenced by monster::absorb_hit(), building_bin::add(), Creature::add_effect(), weakpoints::add_from_set(), Item_factory::add_item_type(), construct::add_roof(), item::ammo_set(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), iexamine::autoclave_empty(), iexamine::autoclave_full(), Character::bionics_install_failure(), overmap::build_connection(), butchery_drops_harvest(), iexamine::can_fertilize(), spell::cast_all_effects(), Character::cast_spell(), change_cleared_terrain(), body_part_type::check(), anonymous_namespace{gates.cpp}::gate_data::check(), material_type::check(), overmap_connection::check(), ter_t::check(), furn_t::check(), check(), fixed_overmap_special_data::check(), Item_factory::check_ammo_type(), check_bash_items(), bionic_data::check_bionic_consistency(), ammunition_type::check_consistency(), body_part_type::check_consistency(), mutation_branch::check_consistency(), mutation_category_trait::check_consistency(), npc_template::check_consistency(), npc_class::check_consistency(), component::check_consistency(), quality_requirement::check_consistency(), check_consistency(), check_decon_items(), profession::check_definition(), scenario::check_definition(), Item_factory::check_definitions(), disease_type::check_disease_consistency(), MonsterGroupManager::check_group_definitions(), check_has_cyclic_dependency(), MonsterGenerator::check_monster_definitions(), profession_group::check_profession_group_consistency(), scent_type::check_scent_consistency(), check_traits(), companion_travel_time_calc(), veh_interact::complete_vehicle(), debug_menu::damage_self(), basecamp::define_camp(), weakpoints::del_from_set(), deserialize(), mission::dialogue_for_topic(), effect::disp_desc(), effect::disp_name(), map::draw_map(), debug_menu::mission_debug::edit_npc(), debug_menu::mission_debug::edit_player(), spell_effect::effect_on_condition(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), debug_menu::faction_edit_menu(), field_type::finalize(), overmap_lake_settings::finalize(), region_terrain_and_furniture_settings::finalize(), vpart_info::finalize(), iuse_transform::finalize(), emit_actor::finalize(), install_bionic_actor::finalize(), detach_gunmods_actor::finalize(), modify_gunmods_actor::finalize(), Item_factory::finalize_item_blacklist(), Item_factory::finalize_pre(), vehicles::finalize_prototypes(), Character::fire_gun(), generic_multi_activity_check_requirement(), generic_multi_activity_locations(), recipe::get_consistency_error(), Character::get_cost_timer(), overmapbuffer::get_extras(), map::get_roof(), good_fishing_spot(), talker_item_const::has_flag(), talker_monster_const::has_flag(), monster::has_flag(), faction::has_relationship(), talker_character_const::has_species(), talker_monster_const::has_species(), talk_function::hospital_raid_return(), item::in_container(), inline_requirements(), is_ot_match(), item::item(), jmapgen_item_group::jmapgen_item_group(), iexamine::kiln_empty(), iexamine::kiln_full(), item::link_to(), avatar::load(), activity_type::load(), map_bash_info::load(), submap::load(), Item_factory::load_basic_info(), mod_manager::load_modfile(), load_nested_mapgen(), npc::load_npc_template(), game::load_packs(), load_update_mapgen(), zone_data::make_type_hash(), mill_activate(), iexamine::mill_finalize(), Item_modifier::modify(), spell_effect::morale(), Character::mutate(), Character::mutate_category(), Character::mutate_towards(), MOD_INFORMATION::name(), talk_function::om_building_region(), om_target_tile(), avatar::on_mission_finished(), activity_handlers::operation_do_turn(), oter_get_rotation(), oter_get_rotation_string(), Character::perform_uninstall(), iuse::pick_lock(), map::place_items(), map::place_spawns(), overmap_ui::place_ter_or_special(), item::process_corpse(), monster::process_turn(), effect_type::register_ma_buff_effect(), oter_type_t::register_terrain(), avatar::remove_active_mission(), Character::remove_mutation(), item::resist(), Character::roll_bad_mutation(), addiction::run_effect(), talk_function::scavenging_raid_return(), effect::serialize(), avatar::set_active_mission(), Character::set_cost_timer(), dealt_damage_instance::set_damage(), smoker_activate(), smoker_finalize(), hacksaw_activity_actor::start(), basecamp::start_fortifications(), npc::starting_weapon(), iexamine::stook_empty(), iexamine::stook_full(), basecamp::survey_return(), Character::test_crossing_threshold(), mod_ui::try_add(), Character::unset_mutation(), editmap::update_fmenu_entry(), change_scent_iuse::use(), heal_actor::use(), cast_spell_actor::use(), MonsterGenerator::validate_species_ids(), vpart_appliance_from_item(), vpart_from_item(), debug_menu::wishmutate(), and mission::wrap_up().
id()
template<typename T > int_id< ammo_effect > id () const
Translate the string based it to the matching integer based id.
This may issue a debug message if the string is not a valid id.
Definition at line 54 of file ammo_effect.cpp.
 {
     return get_all_ammo_effects().convert( *this, AE_NULL );
 }
References AE_NULL, and get_all_ammo_effects().
Referenced by anatomy::add_body_part(), faction_manager::add_new_faction(), map::add_roofs(), encumbrance_data::add_sub_location(), jmapgen_terrain::apply(), apply< furn_t >(), apply< ter_t >(), item::armor_full_protection_info(), armor_inventory_preset::armor_inventory_preset(), assign_multi_activity(), iexamine::autodoc(), overmap::build_city_street(), overmap::build_lab(), debug_menu::change_spells(), bionic_data::check_bionic_consistency(), mutation_branch::check_consistency(), overmap_specials::check_consistency(), complete_construction(), body_part_type::consolidate(), effect::decay(), effect_source::deserialize(), blueprint_options::deserialize(), effect::disp_desc(), effect::disp_name(), workout_activity_actor::do_turn(), overmap_ui::draw_ascii(), draw_health_summary(), groundcover_extra::finalize(), forest_biome_component::finalize(), forest_biome_terrain_dependent_furniture::finalize(), forest_biome::finalize(), overmap_lake_settings::finalize(), region_terrain_and_furniture_settings::finalize(), trap::finalize(), overmap::find_extras(), consume_activity_actor::finish(), overmap::generate_over(), overmap::generate_sub(), generic_multi_activity_handler(), get_alt_ter(), get_best_fire(), effect::get_bp(), get_heat_radiation(), avatar::get_monster_faction(), npc::get_monster_faction(), Creature::get_random_body_part(), map::get_ter_transforms_into(), overmap::good_river(), mapgendata::groundcover(), vehicle::handle_trap(), Character::install_bionics(), item::link_to(), list_and_combine_bps(), Character::load(), submap::load(), magical_polymorph(), mapgen_lake_shore(), mapgen_ocean_shore(), monster::melee_attack(), Character::modify_damage_dealt_with_enchantments(), overmap_ui::place_ter_or_special(), bodygraph_display::prepare_infolist(), anatomy::random_body_part(), oter_type_t::register_terrain(), DefaultRemovePartHandler::removed(), anatomy::select_blocking_part(), anatomy::select_body_part(), anatomy::select_body_part_projectile_attack(), set_description(), mapgen_function_json::setup_internal(), mapgen_function_json_base::setup_setmap(), mattack::slimespring(), boltcutting_activity_actor::start(), hacksaw_activity_actor::start(), oxytorch_activity_actor::start(), prying_activity_actor::start(), map::ter(), oter_t::type_is(), Character::uninstall_bionic(), vehicle::use_vehicle_tool(), vpart_appliance_from_item(), and vpart_from_item().
id_or()
template<typename T > int_id<T> string_id< T >::id_or (const int_id< T > & fallback) const
Translate the string based it to the matching integer based id.
If this string_id is not valid, returns fallback. Does not produce debug message.
Referenced by string_id< T >::id().
is_empty()
template<typename T > bool string_id< T >::is_empty () const inline
Returns whether this id is empty.
An empty id can still be valid, and emptiness does not mean that it's null. Named is_empty() to keep consistency with the rest is_.. functions
Definition at line 303 of file string_id.h.
{
         return _id.is_empty();
     }
References string_id< T >::_id.
Referenced by Character::activate_mutation(), mapgen_palette::add(), iexamine::aggie_plant(), item::ammo_default(), jmapgen_nested::apply(), butchery_drops_harvest(), spell::can_cast(), disable_activity_actor::can_disable_or_reprogram(), install_bionic_actor::can_use(), ter_t::check(), item_search_data::check(), check_bash_items(), bionic_data::check_bionic_consistency(), ammunition_type::check_consistency(), mutation_category_trait::check_consistency(), recipe_dictionary::check_consistency(), check_decon_items(), profession::check_definition(), spell::check_if_component_in_hand(), MonsterGenerator::check_monster_definitions(), item::common_ammo_default(), construction_menu(), furn_t::crafting_pseudo_item_type(), climbing_aid::down_t::deploys_furniture(), game::disable_robot(), Character::dismount(), iuse_transform::do_transform(), monster::drop_items_on_death(), explosion_handler::emp_blast(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), activity_handlers::fertilize_plot_do_turn(), recipe::finalize(), cardreader_examine_actor::finalize(), iuse_transform::finalize(), MonsterGenerator::finalize_mtypes(), Item_factory::finalize_pre(), gunmod_add_activity_actor::finish(), heal_actor::finish_using(), iexamine::fireplace(), monster::generate_inventory(), plot_options::get_descriptions(), bionic::get_quality(), item::get_saved_recipes(), plot_options::get_zone_name_suggestion(), gunmode_checks_weapon(), spell::has_components(), map_data_common_t::has_curtains(), Character::has_installation_requirement(), bionic::has_weapon(), iuse_transform::info(), bionic::initialize_pseudo_items(), recipe::is_blueprint(), is_mounted(), item::item(), jmapgen_loot::jmapgen_loot(), relic::load(), recipe::load(), trap::load(), iuse_transform::load(), Item_factory::load_definition(), magical_polymorph(), monster::make_fungus(), icg_entry::matches(), Item_modifier::modify(), monster::monster(), Character::mount_creature(), Character::mutation_attacks(), mission_start::place_npc_software(), game::print_furniture_info(), item::process_corpse(), plot_options::query_seed(), repair_item_actor::repair_recipe_difficulty(), monster::scent_move(), npc::shop_restock(), iuse::solarpack(), monster::spawn_dissectables_on_death(), Character::test_crossing_threshold(), monster::to_item(), monster::try_upgrade(), link_up_actor::use(), spell::use_components(), and vehicle::vehicle().
is_null()
template<typename T > bool string_id< T >::is_null () const inline
Returns whether this represents the id of the null-object (in which case it's the null-id).
Note that not all types assigned to T may have a null-object. As such, there won't be a definition of NULL_ID and if you use any of the related functions, you'll get errors during the linking.
Example: "mon_null" is the id of the null-object of monster type.
Note: per definition the null-id shall be valid. This allows to use it in places that require a (valid) id, but it can still represent a "don't use it" value.
Definition at line 322 of file string_id.h.
{
         return operator==( NULL_ID() );
     }
References string_id< T >::NULL_ID(), and string_id< T >::operator==().
Referenced by explosion_handler::_make_explosion(), target_ui::action_switch_mode(), creature_tracker::add(), dialogue::add_response(), turret_data::ammo_data(), turret_data::ammo_options(), item::ammo_set(), jmapgen_faction::apply(), jmapgen_field::apply(), jmapgen_npc::apply(), jmapgen_vending_machine::apply(), jmapgen_gaspump::apply(), jmapgen_liquid_item::apply(), jmapgen_monster_group::apply(), jmapgen_monster::apply(), jmapgen_vehicle::apply(), jmapgen_spawn_item::apply(), jmapgen_trap::apply(), jmapgen_ter_furn_transform::apply(), jmapgen_make_rubble::apply(), jmapgen_furniture::apply(), jmapgen_terrain::apply(), jmapgen_nested::apply(), anonymous_namespace{crafting_gui.cpp}::availability::availability(), cata_event_dispatch::avatar_moves(), item::basic_info(), item::burn(), butchery_drops_harvest(), veh_interact::calc_overview(), npc::chat_snippets(), body_part_type::check(), Item_factory::check_ammo_type(), Item_factory::check_and_create_magazine_pockets(), overmap_specials::check_consistency(), display::colorized_bodygraph_text(), colorized_ter_name_flags_at(), Character::complete_craft(), item::debug_info(), bodygraph_display::display(), faction_manager::display(), veh_interact::display_details(), iuse_transform::do_transform(), player_activity::do_turn(), map::draw_lab(), dummy_wgt_render(), dialogue::dynamic_line(), eff_fun_sleep(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), recipe::finalize(), vpart_info::finalize(), vehicles::finalize_prototypes(), find_uncraft_recipe(), consume_activity_actor::finish(), lockpick_activity_actor::finish(), Character::fire_gun(), vpart_info::format_description(), vehicle_part::fuel_current(), recipe::get_consistency_error(), bonus_container::get_description(), overmapbuffer::get_extras(), map_data_common_t::get_harvest_names(), vehicle::get_printable_fuel_types(), npc_class::get_shopkeeper_blacklist(), npc_class::get_shopkeeper_cons_rates(), talker_character_const::get_spell_count(), talker_character_const::get_spell_sum(), draw_args::get_widget(), item::gun_info(), Character::gun_value(), item::handle_pickup_ownership(), map_data_common_t::has_curtains(), mission::has_follow_up(), scenario::has_map_extra(), vehicle::has_old_owner(), vehicle::has_owner(), bionic::has_weapon(), item::in_container(), mission::is_complete(), vehicle::is_engine_type(), map::is_harvestable(), Character::is_immune_damage(), player_activity::is_interruptible(), player_activity::is_interruptible_with_kb(), player_activity::is_null(), requirement_data::is_null(), vehicle::is_old_owner(), vehicle::is_owned_by(), item::item(), pocket_favorite_callback::key(), item::link_to(), load_construction(), item::magazine_default(), Character::mod_power_level(), Character::mod_stamina(), Item_modifier::modify(), display::morale_face_color(), player_activity::operator bool(), string_id< T >::operator bool(), avatar::power_mutations(), vehicle::print_part_list(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item(), remove_ammo(), repair_item_finish(), item::resist(), map::rotten_item_spawn(), addiction::run_effect(), craft_command::safe_to_unload_comp(), gun_actor::shoot(), game::slip_down_chance(), game::spawn_hallucination(), map::spawn_item(), monster::speed_description(), player_activity::start_or_resume(), starting_inv(), npc::starting_weapon(), vehicle::tool_ammo_available(), item::type_name(), overmap::unserialize(), vehicle::use_charges(), map::valid_move(), item::validate_ownership(), wishitem_produce(), and mission::wrap_up().
is_valid() [1/4]
bool is_valid () const
Definition at line 534 of file mapgen.cpp.
 {
     return str() == "null" || nested_mapgens.find( *this ) != nested_mapgens.end();
 }
References nested_mapgens.
is_valid() [2/4]
template<typename T > bool is_valid () const
Returns whether this id is valid, that means whether it refers to an existing object.
Definition at line 78 of file achievement.cpp.
 {
     return achievement_factory.is_valid( *this );
 }
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by math_exp::math_exp_impl::_parse(), Creature::add_effect(), weakpoints::add_from_set(), item::ascii_art_info(), basic_item_filter(), build_behavior_tree(), item::burn(), butchery_dissect_skill_level(), Character::cache_has_item_with(), game::chat(), vpart_migration::check(), body_part_type::check(), score::check(), anonymous_namespace{gates.cpp}::gate_data::check(), overmap_connection::check(), vpart_info::check(), ter_t::check(), furn_t::check(), achievement_requirement::check(), check(), mutable_special_connection::check(), mutable_overmap_terrain::check(), fixed_overmap_special_data::check(), jmapgen_item_group::check(), Item_factory::check_ammo_type(), check_bash_items(), bionic_data::check_bionic_consistency(), anatomy::check_consistency(), body_part_type::check_consistency(), fault_fix::check_consistency(), spell_type::check_consistency(), mutation_branch::check_consistency(), mutation_category_trait::check_consistency(), npc_template::check_consistency(), weather_types::check_consistency(), quality_requirement::check_consistency(), check_constructions(), check_decon_items(), pocket_data::check_definition(), profession::check_definition(), scenario::check_definition(), disease_type::check_disease_consistency(), MonsterGroupManager::check_group_definitions(), MonsterGenerator::check_monster_definitions(), profession_group::check_profession_group_consistency(), scent_type::check_scent_consistency(), display::colorized_bodygraph_text(), weakpoints::del_from_set(), Character::trait_data::deserialize(), effect_source::deserialize(), vehicle_part::deserialize(), item::craft_data::deserialize(), deserialize(), distribute_items_to_npc_zones(), data_handling_activity_actor::do_turn(), worldfactory::draw_mod_list(), dummy_wgt_render(), map::emit_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_test_eoc(), fault_fix::finalize(), field_type::finalize(), building_bin::finalize(), groundcover_extra::finalize(), forest_biome_component::finalize(), forest_biome_terrain_dependent_furniture::finalize(), forest_biome::finalize(), overmap_lake_settings::finalize(), region_terrain_and_furniture_settings::finalize(), vpart_info::finalize(), appliance_convert_examine_actor::finalize(), fixed_overmap_special_data::finalize_mapgen_parameters(), MonsterGenerator::finalize_mtypes(), Item_factory::finalize_pre(), vehicles::finalize_prototypes(), Item_factory::find_template(), hacksaw_activity_actor::finish(), boltcutting_activity_actor::finish(), oxytorch_activity_actor::finish(), foamcrete_build(), dialogue::gen_responses(), json_flag::get(), get_alt_ter(), item::get_category_shallow(), recipe::get_consistency_error(), window_panel::get_height(), npc::get_monster_faction(), item::get_saved_recipes(), get_unique_trait_group_id(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), item::has_flag(), monster::has_flag(), profession::has_initialized(), Character::heat_emission(), learn_spell_actor::info(), bionic::initialize_pseudo_items(), inline_requirements(), item::io(), spell::is_valid(), avatar::load(), Character::load(), monster::load(), mutation_branch::load(), repair_item_actor::load(), submap::load(), Item_factory::load_basic_info(), game::load_packs(), iuse::ma_manual(), magic_train(), magical_polymorph(), activity_handlers::mend_item_finish(), overmap::migrate_oter_ids(), spell_effect::morale(), gun_type_type::name(), activity_handlers::operation_do_turn(), vehicle::place_spawn_items(), vehicle::place_zones(), monster::print_info(), process_new_eocs(), inventory::provide_pseudo_item(), npc::randomize(), rate_action_view_recipe(), effect_type::register_ma_buff_effect(), oter_type_t::register_terrain(), item::resist(), basecamp::scan_pseudo_items(), Character::sees(), select_crafter_and_crafting_recipe(), dealt_damage_instance::set_damage(), item::set_flag(), mapgen_function_json_base::setup_setmap(), monster::speed_description(), basecamp::start_upgrade(), activity_handlers::teach_finish(), mod_ui::try_add(), map::update_visibility_cache(), vehicle::vehicle(), Character::vitamin_mod(), and wishitem_produce().
is_valid() [3/4]
bool string_id< VehiclePlacement >::is_valid () const
Definition at line 66 of file vehicle_group.cpp.
 {
     return vplacements.count( *this ) > 0;
 }
References vplacements.
is_valid() [4/4]
bool is_valid () const
Definition at line 179 of file vehicle_group.cpp.
 {
     return vspawns.count( *this ) > 0;
 }
References vspawns.
NULL_ID()
template<typename T > static const string_id<T>& string_id< T >::NULL_ID () static
Returns a null id whose string_id<T>::is_null() must always return true.
See is_null. Specializations are defined in string_id_null_ids.cpp to avoid instantiation ordering issues.
Referenced by overmap_connections::guess_for(), string_id< T >::is_null(), mission::mission(), npc::npc(), make_null_helper< string_id< T > >::operator()(), and make_null_helper< int_id< T > >::operator()().
obj() [1/4]
const monfaction & obj () const
Definition at line 540 of file mapgen.cpp.
 {
     auto it = nested_mapgens.find( *this );
     if( it == nested_mapgens.end() ) {
         debugmsg( "Using invalid nested_mapgen_id %s", str() );
         static const nested_mapgen null_mapgen;
         return null_mapgen;
     }
     return it->second;
 }
References debugmsg, and nested_mapgens.
obj() [2/4]
template<typename T > const ammo_effect & obj () const
Returns the actual object this id refers to.
May show a debug message if the id is invalid.
Definition at line 71 of file achievement.cpp.
 {
     return achievement_factory.obj( *this );
 }
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by Character::activate_mutation(), anatomy::add_body_part(), inventory_selector::add_character_items(), inventory_selector::add_contained_items(), Creature::add_effect(), weakpoints::add_from_set(), spellbook_callback::add_spell(), iuse::afs_translocator(), apply_migration(), are_requirements_nearby(), mongroup::avg_speed(), diary::bionic_changes(), item::book_info(), build_bionic_poweronly_string(), item::burn(), butcher_submenu(), veh_interact::calc_lift_requirements(), character_martial_arts::can_arm_block(), Character::can_autolearn(), known_magic::can_learn_spell(), character_martial_arts::can_leg_block(), character_martial_arts::can_nonstandard_block(), character_martial_arts::can_use_attack_vector(), debug_menu::character_edit_menu(), body_part_type::check(), anonymous_namespace{crafting_gui.cpp}::availability::check_can_craft_nested(), mutation_branch::check_consistency(), spell::check_if_component_in_hand(), check_nested_has_recipes(), choose_ma_style(), game::climb_down_using(), basecamp::common_salt_water_pipe_construction(), talk_function::companion_choose(), Character::complete_disassemble(), veh_interact::complete_vehicle(), spell::components(), construction_menu(), basecamp::continue_salt_water_pipe(), basecamp::craft_description(), overmap_specials::create_building_from(), vehicle::damage_direct(), Character::deactivate_mutation(), weakpoints::del_from_set(), npc::describe_mission(), vehicle_part::deserialize(), mission::deserialize(), item::craft_data::deserialize(), deserialize(), overmap_ui::draw_ascii(), char_creation::draw_location(), overmap_ui::draw_om_sidebar(), dummy_wgt_render(), map_data_common_t::extended_description(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_achievment(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_visible_trait(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_know_recipe(), debug_menu::faction_edit_menu(), map_extras::filtered_by(), behavior::finalize(), vehicles::finalize_prototypes(), Item_factory::find_template(), harvest_activity_actor::finish(), ma_buff::from_effect(), dialogue::gen_responses(), item_pocket::general_info(), profession::generic(), scenario::generic(), character_martial_arts::get_all_techniques(), item::get_base_material(), harvest_list::get_butchery_requirements(), item::get_category_of_contents(), item::get_category_shallow(), npc::get_current_activity(), overmapbuffer::get_description_at(), Character::get_instability_per_category(), player_morale::morale_point::get_name(), overmap_ui::get_overmap_neighbors(), player_activity::get_progress_message(), read_activity_actor::get_progress_message(), get_repair_hint(), npc_class::get_shopkeeper_blacklist(), npc_class::get_shopkeeper_cons_rates(), repair_item_actor::get_valid_repair_materials(), get_valid_technique(), MonsterGroupManager::GetRandomMonsterFromGroup(), MonsterGroupManager::GetUpgradedMonsterGroup(), gun_battery_mags_drain(), item::gun_info(), gun_uses_liquid_ammo(), jmapgen_nested::has_vehicle_collision(), avatar::identify(), deploy_furn_actor::info(), initialize_default_custom_panels(), inline_requirements(), vehicle::install_part(), place_trap_actor::is_allowed(), MonsterGroupManager::is_animal(), Character::is_category_allowed(), Character::is_installable(), mongroup::is_safe(), item::item(), map::item_category_spawn_rate(), ma_style_callback::key(), widget::layout(), known_magic::learn_spell(), list_nested(), avatar::load(), monster::load(), character_martial_arts::martialart_use_message(), Character::melee_attack_abstract(), item::melee_combat_info(), MonsterGroupManager::monster_is_blacklisted(), display::morale_face_color(), iuse::multicooker(), Character::mutate_towards(), Character::mutation_effect(), Character::mutation_height(), Character::mutation_loss_effect(), kill_tracker::notify(), read_activity_actor::npc_read(), basecamp::om_upgrade_description(), open(), string_id< T >::operator*(), string_id< T >::operator->(), Character::perform_install(), Character::perform_uninstall(), place_appliance(), player_difficulty::player_difficulty(), read_activity_actor::player_read(), avatar::power_bionics(), avatar::power_mutations(), monster::process_one_effect(), Character::process_turn(), diary::prof_changes(), avatar::randomize(), npc::randomize(), avatar::read(), Creature::remove_effect(), Character::remove_mutation(), repair_item_finish(), repair_item_actor::repair_recipe_difficulty(), requirements_map(), mattack::riotbot(), rod_fish(), basecamp::salt_water_pipe_return(), basecamp::scan_pseudo_items(), Character::set_mutation_unsafe(), set_traits(), talker_character_const::skill_seminar_text(), talker_character_const::skill_training_text(), game::slip_down_chance(), talk_function::start_camp(), basecamp::start_fortifications(), game::start_game(), basecamp::start_salt_water_pipe(), Character::store(), talker_character_const::style_training_text(), Character::test_crossing_threshold(), quality_requirement::to_colored_string(), quality_requirement::to_string(), Character::toggle_trait_deps(), debug_menu::unlock_all(), basecamp::update_in_progress(), veh_interact::update_part_requirements(), basecamp::update_provides(), basecamp::update_resources(), Character::update_vitamins(), place_trap_actor::use(), learn_spell_actor::use(), vehicle::use_charges(), spell::use_components(), Character::vitamin_rate(), Character::vomit(), scenario::weighted_random_profession(), anonymous_namespace{inventory_ui.cpp}::wielded_worn_category(), and debug_menu::wishmutate().
obj() [3/4]
const VehiclePlacement & string_id< VehiclePlacement >::obj () const
Definition at line 54 of file vehicle_group.cpp.
 {
     const auto iter = vplacements.find( *this );
     if( iter == vplacements.end() ) {
         debugmsg( "invalid vehicle placement id %s", c_str() );
         static const VehiclePlacement dummy{};
         return dummy;
     }
     return iter->second;
 }
References debugmsg, and vplacements.
obj() [4/4]
const weakpoints & obj () const
Definition at line 167 of file vehicle_group.cpp.
 {
     const auto iter = vspawns.find( *this );
     if( iter == vspawns.end() ) {
         debugmsg( "invalid vehicle spawn id %s", c_str() );
         static const VehicleSpawn dummy{};
         return dummy;
     }
     return iter->second;
 }
References debugmsg, and vspawns.
operator bool()
template<typename T > string_id< T >::operator bool () const inline explicit
Same as !is_null, basically one can use it to check for the id referring to an actual object.
This avoids explicitly comparing it with NULL_ID. The id may still be invalid, but that should have been checked when the world data was loaded.
string_id<X> id = ...;
if(id) {
    apply_id( id );
} else {
    // was the null-id, ignore it.
}
Definition at line 338 of file string_id.h.
{
         return !is_null();
     }
References string_id< T >::is_null().
operator std::string()
template<typename T > string_id< T >::operator std::string () const inline explicit
Definition at line 264 of file string_id.h.
{
         return _id.str();
     }
References string_id< T >::_id.
operator!=()
template<typename T > bool string_id< T >::operator!= (const This & rhs) const inline
The usual comparator, compares the string id as usual.
Definition at line 244 of file string_id.h.
{
         return ! operator==( rhs );
     }
References string_id< T >::operator==().
operator*()
template<typename T > const T& string_id< T >::operator* () const inline
Definition at line 286 of file string_id.h.
{
         return obj();
     }
References string_id< T >::obj().
operator->()
template<typename T > const T* string_id< T >::operator-> () const inline
Definition at line 290 of file string_id.h.
{
         return &obj();
     }
References string_id< T >::obj().
operator<()
template<typename T > bool string_id< T >::operator< (const This & rhs) const inline
Comparison, only useful when the id is used in std::map or std::set as key.
Guarantees total order, but DOESN'T guarantee the same order after process restart! To have a predictable lexicographic order, use LexCmp (much slower!)
Definition at line 232 of file string_id.h.
{
         return _id._id < rhs._id._id;
     }
References string_id< T >::_id.
operator==()
template<typename T > bool string_id< T >::operator== (const This & rhs) const inline
The usual comparator, compares the string id as usual.
Definition at line 238 of file string_id.h.
{
         return _id._id == rhs._id._id;
     }
References string_id< T >::_id.
Referenced by string_id< T >::is_null(), and string_id< T >::operator!=().
set_cid_version()
template<typename T > void string_id< T >::set_cid_version (int cid, int64_t version) const inline private
Definition at line 355 of file string_id.h.
{
         _cid = cid;
         _version = version;
     }
str()
template<typename T > const std::string& string_id< T >::str () const inline
Returns the identifier as plain std::string.
Use with care, the plain string does not have any information as what type of object it refers to (the T template parameter of the class).
Definition at line 260 of file string_id.h.
{
         return _id.str();
     }
References string_id< T >::_id.
Referenced by basecamp::abandon_camp(), Character::activate_bionic(), Character::activate_mutation(), anonymous_namespace{item_tname.cpp}::active(), Item_group::add_group_entry(), Item_group::add_item_entry(), Character::add_known_trap(), construct::add_matching_down_above(), add_summoned_mon(), map::add_vehicle_to_map(), item::ammo_set(), jmapgen_terrain::apply(), jmapgen_nested::apply(), cardreader_examine_actor::apply(), item::armor_info(), assemble_hobby_details(), talk_function::assign_mission(), basecamp::available_upgrades(), map::bash_ter_furn(), mdeath::broken(), overmap::build_lab(), MapExtras::burned_ground_parser(), activity_handlers::butcher_finish(), Character::cache_get_items_with(), Character::cache_has_item_with(), Character::cache_has_item_with_flag(), Character::cache_visit_items_with(), iuse::camera(), change_armor_sprite(), debug_menu::change_spells(), debug_menu::character_edit_menu(), vpart_migration::check(), anatomy::check(), score::check(), vpart_info::check(), achievement_requirement::check(), mutable_special_connection::check(), mutable_overmap_terrain::check(), fixed_overmap_special_data::check(), jmapgen_item_group::check(), jmapgen_vehicle::check(), jmapgen_sealed_item::check(), jmapgen_nested::check(), Item_factory::check_and_create_magazine_pockets(), ammunition_type::check_consistency(), fault_fix::check_consistency(), fault::check_consistency(), mutation_branch::check_consistency(), overmap_specials::check_consistency(), recipe_dictionary::check_consistency(), trap::check_consistency(), mapgen_function_json::check_consistent_with(), pocket_data::check_definition(), scenario::check_definition(), Item_factory::check_definitions(), check_furn(), construct::check_matching_down_above(), npc::check_or_use_weapon_cbm(), iuse::chop_logs(), iuse::chop_tree(), iuse::clear_rubble(), map::close_door(), basecamp::combat_mission_return(), Character::compute_nutrient_range(), mattack::copbot(), overmap_specials::create_building_from(), Character::deactivate_mutation(), effect::death_event(), debug_menu::debug(), event_transformation_event_source::debug_description(), item::debug_info(), debug_menu::mission_debug::describe(), zone_data::deserialize(), vehicle_part::deserialize(), deserialize(), iuse::dig(), iuse::dig_channel(), iuse::dive_tank_activate(), npc::do_reload(), data_handling_activity_actor::do_turn(), construct::done_deconstruct(), worldfactory::draw_mod_list(), overmap_ui::draw_om_sidebar(), iuse::ebookread(), iuse::ebooksave(), iuse::electricstorage(), basecamp::emergency_recall(), item_reader::erase_next(), npc::evaluate_weapon(), monster::extended_description(), extract_and_check_orientation_flags(), conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), basecamp::farm_return(), activity_handlers::fertilize_plot_do_turn(), iuse::fill_pit(), item::fill_with(), fault_fix::finalize(), recipe_dictionary::finalize(), vehicles::parts::finalize(), vpart_info::finalize(), appliance_convert_examine_actor::finalize(), Single_item_creator::finalize(), Item_factory::finalize_item_blacklist(), MonsterGenerator::finalize_mtypes(), Item_factory::finalize_post_armor(), Item_factory::finalize_pre(), vehicles::finalize_prototypes(), bookbinder_copy_activity_actor::finish(), hacksaw_activity_actor::finish(), boltcutting_activity_actor::finish(), oxytorch_activity_actor::finish(), basecamp::fortifications_return(), mattack::frag(), ma_buff::from_effect(), map::furn_set(), map::generate(), MonsterGenerator::generate_fake_pseudo_dormant_monster(), generate_uniform_omt(), generic_multi_activity_check_requirement(), get_alt_ter(), vehicle::get_display_of_tile(), requirement_data::get_folded_list(), weldrig_hack::get_item(), oter_t::get_mapgen_id(), plot_options::get_mark(), Character::get_overlay_ids(), get_recipe_result_item(), Character::get_recipe_weighted_skill_average(), recipe_group::get_recipes_by_id(), item::get_saved_recipes(), SkillLevelMap::get_skill_level_object(), talker_npc::give_item_to(), iuse::granade_act(), map::grow_plant(), item::gun_info(), item::gun_set_mode(), Character::gun_value(), Character::gunmod_installation_odds(), iuse::hacksaw(), vpart_info::handle_inheritance(), basecamp::handle_mission(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), Character::has_enough_anesth(), item::has_flag(), Single_item_creator::has_item(), activity_handlers::heat_item_finish(), Character::install_bionics(), vehicle::install_part(), game::inventory_item_menu(), item::io(), mission::is_complete(), is_ot_match(), item::item(), inscribe_actor::item_inscription(), item_save_monsters(), jmapgen_loot::jmapgen_loot(), ma_style_callback::key(), widget::layout(), spell::list_ignored_species_names(), spell::list_targeted_species_names(), Character::load(), monster::load(), fault_fix::load(), connect_group::load(), recipe::load(), vpart_info::load(), recipe_dictionary::load(), Item_factory::load_basic_info(), load_construction(), mapgen_palette::load_internal(), Item_factory::load_item_group(), load_nested_mapgen(), Skill::load_skill(), mutation_branch::load_trait_migration(), load_update_mapgen(), MonsterGroupManager::LoadMonsterGroup(), iuse::lumber(), make_group_or_throw(), reload_activity_actor::make_reload_sound(), iuse::makemound(), editmap::mapgen_preview(), mapgendata::mapgendata(), iuse::meditate(), Character::melee_attack_abstract(), Character::melee_value(), activity_handlers::mend_item_finish(), basecamp::menial_return(), migrate_bionic_id(), Character::migrate_items_to_storage(), overmap::migrate_oter_ids(), anonymous_namespace{monexamine.cpp}::milk_source(), Item_modifier::modify(), MonsterGroupManager::monster_is_blacklisted(), display::morale_emotion(), iuse::multicooker(), suffer::mutation_power(), map::open_door(), lexicographic< T >::operator()(), component::operator<(), oter_no_dir(), iuse::pack_item(), mattack::photograph(), pick_plant(), mutable_overmap_special_data::place(), iexamine::portable_structure(), vehicle::prepare_tool(), monster::print_info(), anonymous_namespace{math_parser_diag.cpp}::proficiency_ass(), item::put_in(), Character::recraft(), basecamp::recruit_return(), veh_app_interact::refill(), wish_mutate_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), veh_app_interact::remove(), Single_item_creator::remove_item(), vehicle::remove_part(), DefaultRemovePartHandler::removed(), mattack::riotbot(), vehicle_prototype::save_vehicle_as_prototype(), scent_map::serialize(), effect::serialize(), target_ui::set_cursor_pos(), item::set_flag(), npc::set_omt_destination(), item_pricing::set_values(), iuse::shocktonfa_off(), iuse::shocktonfa_on(), iuse::solarpack(), iuse::solarpack_off(), debug_menu::spell_description(), spell_effect_area(), boltcutting_activity_actor::start(), hacksaw_activity_actor::start(), oxytorch_activity_actor::start(), prying_activity_actor::start(), talk_function::start_camp(), vehicle::start_engine(), talk_function::start_training_gen(), basecamp::start_upgrade(), vehicle::stop_engines(), monster::store(), basecamp::survey_field_return(), basecamp::survey_return(), iuse::talking_doll(), map::ter_set(), Character::toggle_trait(), iuse::towel_common(), map::trap_set(), Character::uninstall_bionic(), vitamin::units_from_mass(), iuse::unpack_item(), mapbuffer::unserialize_submaps(), editmap::update_view_with_help(), basecamp::upgrade_return(), iuse_transform::use(), firestarter_actor::use(), salvage_actor::use(), inscribe_actor::use(), fireweapon_off_actor::use(), musical_instrument_actor::use(), sew_advanced_actor::use(), effect_on_conditons_actor::use(), saw_barrel_actor::use(), saw_stock_actor::use(), molle_attach_actor::use(), link_up_actor::use(), vehicle::use_charges(), vehicle::use_vehicle_tool(), vehicle::vehicle(), vehicle_activity(), Character::vitamin_mod(), game::walk_move(), Character::weapon_value(), npc::wield_better_weapon(), debug_menu::wisheffect(), JsonOut::write(), and game::zones_manager().
Friends And Related Function Documentation
generic_factory< T >
template<typename T > friend class generic_factory< T > friend
Definition at line 355 of file string_id.h.
id() [1/8]
bodypart_id id () const related
Definition at line 54 of file ammo_effect.cpp.
 {
     return get_all_ammo_effects().convert( *this, AE_NULL );
 }
id() [2/8]
int_id< field_type > id () const related
Definition at line 208 of file bodypart.cpp.
 {
     return body_part_factory.convert( *this, bodypart_id( 0 ) );
 }
References anonymous_namespace{bodypart.cpp}::body_part_factory.
id() [3/8]
int_id< furn_t > id () const related
Definition at line 159 of file field_type.cpp.
 {
     return get_all_field_types().convert( *this, fd_null.id_or( int_id<field_type>() ) );
 }
References fd_null, get_all_field_types(), and string_id< T >::id_or().
id() [4/8]
int_id< monfaction > id () const related
Definition at line 126 of file mapdata.cpp.
 {
     return furniture_data.convert( *this, f_null );
 }
References f_null, and anonymous_namespace{mapdata.cpp}::furniture_data.
id() [5/8]
int_id< oter_type_t > id () const related
Definition at line 34 of file monfaction.cpp.
 {
     return faction_factory.convert( *this, mfaction_id( 0 ) );
 }
References faction_factory.
id() [6/8]
sub_bodypart_id id () const related
Definition at line 359 of file overmap.cpp.
 {
     return terrain_types.convert( *this, int_id<oter_type_t>( 0 ) );
 }
References anonymous_namespace{overmap.cpp}::terrain_types.
id() [7/8]
int_id< trap > id () const related
Definition at line 60 of file subbodypart.cpp.
 {
     return sub_body_part_factory.convert( *this, sub_bodypart_id( 0 ) );
 }
References anonymous_namespace{subbodypart.cpp}::sub_body_part_factory.
id() [8/8]
int_id< trap > id () const related
Definition at line 88 of file trap.cpp.
 {
     return trap_factory.convert( *this, tr_null );
 }
References tr_null, and anonymous_namespace{trap.cpp}::trap_factory.
int_id()
int_id (const string_id< trap > & id) related
Definition at line 95 of file trap.cpp.
                                                 : _id( id.id() )
 {
 }
is_valid() [1/13]
bool is_valid () const related
Definition at line 78 of file achievement.cpp.
 {
     return achievement_factory.is_valid( *this );
 }
Referenced by monfactions::finalize(), base_camps::max_upgrade_by_type(), pools_to_string(), Character::setID(), and debug_menu::wishitem().
is_valid() [2/13]
bool is_valid () const related
Definition at line 40 of file ammo_effect.cpp.
 {
     return get_all_ammo_effects().is_valid( *this );
 }
References get_all_ammo_effects().
is_valid() [3/13]
bool is_valid () const related
Definition at line 52 of file character_modifier.cpp.
 {
     return character_modifier_factory.is_valid( *this );
 }
References anonymous_namespace{character_modifier.cpp}::character_modifier_factory.
is_valid() [4/13]
bool is_valid () const related
Definition at line 29 of file clothing_mod.cpp.
 {
     return all_clothing_mods.is_valid( *this );
 }
References anonymous_namespace{clothing_mod.cpp}::all_clothing_mods.
is_valid() [5/13]
bool is_valid () const related
Definition at line 20 of file construction_group.cpp.
 {
     return all_construction_groups.is_valid( *this );
 }
References anonymous_namespace{construction_group.cpp}::all_construction_groups.
is_valid() [6/13]
bool is_valid () const related
Definition at line 49 of file damage.cpp.
 {
     return damage_type_factory.is_valid( *this );
 }
References anonymous_namespace{damage.cpp}::damage_type_factory.
is_valid() [7/13]
bool is_valid () const related
Definition at line 136 of file field_type.cpp.
 {
     return get_all_field_types().is_valid( *this );
 }
References get_all_field_types().
is_valid() [8/13]
bool is_valid () const related
Definition at line 84 of file mapdata.cpp.
 {
     return terrain_data.is_valid( *this );
 }
References anonymous_namespace{mapdata.cpp}::terrain_data.
is_valid() [9/13]
bool is_valid () const related
Definition at line 112 of file mapdata.cpp.
 {
     return furniture_data.is_valid( *this );
 }
References anonymous_namespace{mapdata.cpp}::furniture_data.
is_valid() [10/13]
bool is_valid () const related
Definition at line 175 of file monstergenerator.cpp.
 {
     return mon_flags.is_valid( *this );
 }
References anonymous_namespace{monstergenerator.cpp}::mon_flags.
is_valid() [11/13]
bool is_valid () const related
Definition at line 81 of file profession.cpp.
 {
     return all_profs.is_valid( *this );
 }
References anonymous_namespace{profession.cpp}::all_profs.
is_valid() [12/13]
bool is_valid () const related
Definition at line 67 of file trap.cpp.
 {
     return trap_factory.is_valid( *this );
 }
References anonymous_namespace{trap.cpp}::trap_factory.
is_valid() [13/13]
bool is_valid () const related
Definition at line 153 of file veh_type.cpp.
 {
     return vpart_info_factory.is_valid( *this );
 }
References anonymous_namespace{veh_type.cpp}::vpart_info_factory.
obj() [1/13]
const character_modifier & obj () const related
Definition at line 47 of file ammo_effect.cpp.
 {
     return get_all_ammo_effects().obj( *this );
 }
References get_all_ammo_effects().
obj() [2/13]
const clothing_mod & obj () const related
Definition at line 45 of file character_modifier.cpp.
 {
     return character_modifier_factory.obj( *this );
 }
References anonymous_namespace{character_modifier.cpp}::character_modifier_factory.
obj() [3/13]
const construction_group & obj () const related
Definition at line 36 of file clothing_mod.cpp.
 {
     return all_clothing_mods.obj( *this );
 }
References anonymous_namespace{clothing_mod.cpp}::all_clothing_mods.
obj() [4/13]
const damage_type & obj () const related
Definition at line 27 of file construction_group.cpp.
 {
     return all_construction_groups.obj( *this );
 }
References anonymous_namespace{construction_group.cpp}::all_construction_groups.
obj() [5/13]
const field_type & obj () const related
Definition at line 42 of file damage.cpp.
 {
     return damage_type_factory.obj( *this );
 }
References anonymous_namespace{damage.cpp}::damage_type_factory.
obj() [6/13]
const ter_t & obj () const related
Definition at line 143 of file field_type.cpp.
 {
     return get_all_field_types().obj( *this );
 }
References get_all_field_types().
obj() [7/13]
const furn_t & obj () const related
Definition at line 77 of file mapdata.cpp.
 {
     return terrain_data.obj( *this );
 }
References anonymous_namespace{mapdata.cpp}::terrain_data.
obj() [8/13]
const furn_t & obj () const related
Definition at line 119 of file mapdata.cpp.
 {
     return furniture_data.obj( *this );
 }
References anonymous_namespace{mapdata.cpp}::furniture_data.
obj() [9/13]
const mon_flag & obj () const related
Definition at line 41 of file monfaction.cpp.
 {
     return faction_factory.obj( *this );
 }
References faction_factory.
obj() [10/13]
const oter_type_t & obj () const related
Definition at line 168 of file monstergenerator.cpp.
 {
     return mon_flags.obj( *this );
 }
References anonymous_namespace{monstergenerator.cpp}::mon_flags.
obj() [11/13]
const profession & obj () const related
Definition at line 376 of file overmap.cpp.
 {
     return terrain_types.obj( *this );
 }
References anonymous_namespace{overmap.cpp}::terrain_types.
obj() [12/13]
const trap & obj () const related
Definition at line 74 of file profession.cpp.
 {
     return all_profs.obj( *this );
 }
References anonymous_namespace{profession.cpp}::all_profs.
obj() [13/13]
const VehicleGroup & obj () const related
Definition at line 101 of file trap.cpp.
 {
     return trap_factory.obj( *this );
 }
References anonymous_namespace{trap.cpp}::trap_factory.
operator<<
template<typename T > std::ostream& operator<< (std::ostream & os, const string_id< T > & s) friend
Definition at line 342 of file string_id.h.
{
         os << s.str();
         return os;
     }
std::hash< string_id< T > >
template<typename T > friend struct std::hash< string_id< T > > friend
Definition at line 355 of file string_id.h.
Member Data Documentation
_cid
template<typename T > int string_id< T >::_cid = INVALID_CID mutable private
Definition at line 351 of file string_id.h.
_id
template<typename T > Identity string_id< T >::_id private
Definition at line 353 of file string_id.h.
Referenced by string_id< T >::c_str(), string_id< T >::is_empty(), string_id< T >::operator std::string(), string_id< T >::operator<(), string_id< T >::operator==(), and string_id< T >::str().
_version
template<typename T > int64_t string_id< T >::_version = INVALID_VERSION mutable private
Definition at line 349 of file string_id.h.
The documentation for this class was generated from the following files:
src/int_id.h
src/string_id.h
src/achievement.cpp
src/activity_type.cpp
src/activity_type.h
src/addiction.cpp
src/ammo.cpp
src/ammo_effect.cpp
src/behavior.cpp
src/bionics.cpp
src/bodygraph.cpp
src/bodypart.cpp
src/character_modifier.cpp
src/city.cpp
src/clothing_mod.cpp
src/construction_category.cpp
src/construction_group.cpp
src/damage.cpp
src/effect.cpp
src/effect.h
src/effect_on_condition.cpp
src/emit.cpp
src/faction_camp.cpp
src/fault.cpp
src/field_type.cpp
src/flag.cpp
src/harvest.cpp
src/item_factory.cpp
src/map_extras.cpp
src/mapdata.cpp
src/martialarts.cpp
src/material.cpp
src/math_parser_jmath.cpp
src/missiondef.cpp
src/monfaction.cpp
src/mongroup.cpp
src/monstergenerator.cpp
src/mood_face.cpp
src/npc_class.cpp
src/options.cpp
src/overmap.cpp
src/profession.cpp
src/requirements.cpp
src/scenario.cpp
src/shop_cons_rate.cpp
src/skill.cpp
src/speed_description.cpp
src/start_location.cpp
src/subbodypart.cpp
src/trap.cpp
src/veh_type.cpp
src/vehicle_group.cpp
src/vitamin.cpp
src/weakpoint.cpp
src/weather_type.cpp