Cataclysm DDA: tinymap Class Reference
tinymap Class Reference
Tinymap is a small version of the map which covers a single overmap terrain (OMT) tile, which corresponds to 2 * 2 submaps, or 24 * 24 map tiles.
#include <map.h>
Public Member Functions
tinymap ()
bool inbounds (const tripoint &p) const
bool inbounds (const tripoint_omt_ms &p) const
map * cast_to_map ()
void load (const tripoint_abs_omt &w, bool update_vehicles, bool pump_events=false)
void place_spawns (const mongroup_id &group, int chance, const point_omt_ms &p1, const point_omt_ms &p2, const int z_level, float density, bool individual=false, bool friendly=false, const std::optional< std::string > &name=std::nullopt, int mission_id=-1)
void add_spawn (const mtype_id &type, int count, const tripoint_omt_ms &p, bool friendly=false, int faction_id=-1, int mission_id=-1, const std::optional< std::string > &name=std::nullopt)
ter_id ter (const tripoint &p) const
ter_id ter (const tripoint_omt_ms &p) const
bool ter_set (const tripoint &p, const ter_id &new_terrain, bool avoid_creatures=false)
bool has_flag_ter (ter_furn_flag flag, const tripoint &p) const
bool has_flag_ter (ter_furn_flag flag, const tripoint_omt_ms &p) const
void draw_line_ter (const ter_id &type, const point &p1, const point &p2, bool avoid_creature=false)
bool is_last_ter_wall (bool no_furn, const point &p, const point &max, direction dir) const
furn_id furn (const point &p) const
furn_id furn (const tripoint &p) const
furn_id furn (const tripoint_omt_ms &p) const
bool has_furn (const tripoint &p) const
void set (const tripoint &p, const ter_id &new_terrain, const furn_id &new_furniture)
bool furn_set (const point &p, const furn_id &new_furniture, bool avoid_creatures=false)
bool furn_set (const tripoint &p, const furn_id &new_furniture, bool furn_reset=false, bool avoid_creatures=false)
void draw_line_furn (const furn_id &type, const point &p1, const point &p2, bool avoid_creatures=false)
void draw_square_furn (const furn_id &type, const point &p1, const point &p2, bool avoid_creatures=false)
bool has_flag_furn (ter_furn_flag flag, const tripoint &p) const
computer * add_computer (const tripoint &p, const std::string &name, int security)
std::string name (const tripoint &p)
bool impassable (const tripoint &p) const
tripoint_range< tripoint > points_on_zlevel () const
tripoint_range< tripoint > points_on_zlevel (int z) const
tripoint_range< tripoint > points_in_rectangle (const tripoint &from, const tripoint &to) const
tripoint_range< tripoint_omt_ms > points_in_rectangle (const tripoint_omt_ms &from, const tripoint_omt_ms &to) const
tripoint_range< tripoint > points_in_radius (const tripoint &center, size_t radius, size_t radiusz=0) const
tripoint_range< tripoint_omt_ms > points_in_radius (const tripoint_omt_ms &center, size_t radius, size_t radiusz=0) const
map_stack i_at (const tripoint &p)
void spawn_item (const tripoint &p, const itype_id &type_id, unsigned quantity=1, int charges=0, const time_point &birthday=calendar::start_of_cataclysm, int damlevel=0, const std::set< flag_id > &flags={}, const std::string &variant="", const std::string &faction="")
void spawn_item (const tripoint &p, const std::string &type_id, unsigned quantity=1, int charges=0, const time_point &birthday=calendar::start_of_cataclysm, int damlevel=0, const std::set< flag_id > &flags={}, const std::string &variant="", const std::string &faction="")
std::vector< item * > spawn_items (const tripoint &p, const std::vector< item > &new_items)
item & add_item (const tripoint &p, item new_item)
item & add_item_or_charges (const point &p, const item &obj, bool overflow=true)
std::vector< item * > put_items_from_loc (const item_group_id &group_id, const tripoint &p, const time_point &turn=calendar::start_of_cataclysm)
item & add_item_or_charges (const tripoint &pos, item obj, bool overflow=true)
std::vector< item * > place_items (const item_group_id &group_id, int chance, const tripoint &p1, const tripoint &p2, bool ongrass, const time_point &turn, int magazine=0, int ammo=0, const std::string &faction="")
void add_corpse (const tripoint &p)
void i_rem (const tripoint &p, item *it)
void i_clear (const tripoint &p)
bool add_field (const tripoint &p, const field_type_id &type_id, int intensity=INT_MAX, const time_duration &age=0_turns, bool hit_player=true)
bool add_field (const tripoint_omt_ms &p, const field_type_id &type_id, int intensity=INT_MAX, const time_duration &age=0_turns, bool hit_player=true)
void delete_field (const tripoint &p, const field_type_id &field_to_remove)
void delete_field (const tripoint_omt_ms &p, const field_type_id &field_to_remove)
bool has_flag (ter_furn_flag flag, const tripoint &p) const
bool has_flag (ter_furn_flag flag, const point &p) const
void destroy (const tripoint &p, bool silent=false)
const trap & tr_at (const tripoint &p) const
const trap & tr_at (const tripoint_omt_ms &p) const
void trap_set (const tripoint &p, const trap_id &type)
void trap_set (const tripoint_omt_ms &p, const trap_id &type)
void set_signage (const tripoint &p, const std::string &message)
void delete_signage (const tripoint &p)
VehicleList get_vehicles ()
optional_vpart_position veh_at (const tripoint &p) const
optional_vpart_position veh_at (const tripoint_omt_ms &p) const
vehicle * add_vehicle (const vproto_id &type, const tripoint &p, const units::angle &dir, int init_veh_fuel=-1, int init_veh_status=-1, bool merge_wrecks=true)
void add_splatter_trail (const field_type_id &type, const tripoint &from, const tripoint &to)
void collapse_at (const tripoint &p, bool silent, bool was_supporting=false, bool destroy_pos=true)
tripoint getlocal (const tripoint &p) const
tripoint_abs_sm get_abs_sub () const
tripoint getabs (const tripoint &p) const
tripoint getlocal (const tripoint_abs_ms &p) const
bool is_outside (const tripoint &p) const
void save ()
Add currently loaded submaps (in grid) to the mapbuffer.
bool is_main_cleanup_queued () const
void main_cleanup_override (bool over)
void generate (const tripoint_abs_omt &p, const time_point &when)
void translate (const ter_id &from, const ter_id &to)
void rotate (int turns, bool setpos_safe=false)
Rotates this map, and all of its contents, by the specified multiple of 90 degrees.
void mirror (bool mirror_horizontal, bool mirror_vertical)
Mirrors this map, and all of its contents along with all its contents in the directions specified.
void build_outside_cache (int zlev)
Protected Member Functions
tinymap (int mapsize, bool zlev)
void cut_down_tree (tripoint_omt_ms p, point dir)
int get_my_MAPSIZE ()
void set_abs_sub (const tripoint_abs_sm &p)
Sets abs_sub, see there.
void setsubmap (size_t grididx, submap *smap)
Set the submap pointer in grid at the give index.
size_t get_nonant (const tripoint &gridp) const
Get the index of a submap pointer in the grid given by grid coordinates.
size_t get_nonant (const point &gridp) const
Friends
class editmap
Additional Inherited Members
Private Member Functions inherited from map
map ()
virtual ~map ()
map & operator= (const map &)=delete
map & operator= (map &&)
void set_transparency_cache_dirty (int zlev)
Sets a dirty flag on the a given cache.
void set_transparency_cache_dirty (const tripoint &p, bool field=false)
void set_seen_cache_dirty (const tripoint &change_location)
void set_seen_cache_dirty (int zlevel)
void set_outside_cache_dirty (int zlev)
void set_floor_cache_dirty (int zlev)
void set_pathfinding_cache_dirty (int zlev)
void set_pathfinding_cache_dirty (const tripoint &p)
void invalidate_map_cache (int zlev)
bool memory_cache_dec_is_dirty (const tripoint &p) const
bool memory_cache_ter_is_dirty (const tripoint &p) const
void memory_cache_dec_set_dirty (const tripoint &p, bool value) const
void memory_cache_ter_set_dirty (const tripoint &p, bool value) const
void memory_clear_vehicle_points (const vehicle &veh) const
bool has_potential_los (const tripoint &from, const tripoint &to) const
A pre-filter for bresenham LOS.
void on_vehicle_moved (int smz)
Callback invoked when a vehicle has moved.
lit_level apparent_light_at (const tripoint &p, const visibility_variables &cache) const
Determine the visible light level for a tile, based on light_at for the tile, vision distance, etc.
visibility_type get_visibility (lit_level ll, const visibility_variables &cache) const
std::tuple< maptile, maptile, maptile > get_wind_blockers (const int &winddirection, const tripoint &pos)
void draw (const catacurses::window &w, const tripoint &center)
Draw a visible part of the map into w.
void drawsq (const catacurses::window &w, const tripoint &p, const drawsq_params &params) const
Draw the map tile at the given coordinate.
void drawsq (const catacurses::window &w, const tripoint_bub_ms &p, const drawsq_params &params) const
void save ()
Add currently loaded submaps (in grid) to the mapbuffer.
void load (const tripoint_abs_sm &w, bool update_vehicles, bool pump_events=false)
Load submaps into grid.
void shift (const point &s)
Shift the map along the vector s.
void vertical_shift (int newz)
Moves the map vertically to (not by!) newz.
void clear_spawns ()
void clear_traps ()
const_maptile maptile_at (const tripoint &p) const
const_maptile maptile_at (const tripoint_bub_ms &p) const
maptile maptile_at (const tripoint &p)
maptile maptile_at (const tripoint_bub_ms &p)
int move_cost (const tripoint &p, const vehicle *ignored_vehicle=nullptr) const
Calculate the cost to move past the tile at p.
int move_cost (const tripoint_bub_ms &p, const vehicle *ignored_vehicle=nullptr) const
int move_cost (const point &p, const vehicle *ignored_vehicle=nullptr) const
bool impassable (const tripoint &p) const
bool impassable (const tripoint_bub_ms &p) const
bool impassable (const point &p) const
bool impassable (const point_bub_ms &p) const
bool passable (const tripoint &p) const
bool passable (const tripoint_bub_ms &p) const
bool passable (const point &p) const
bool is_wall_adjacent (const tripoint &center) const
bool is_open_air (const tripoint &) const
int move_cost_ter_furn (const tripoint &p) const
Similar behavior to move_cost(), but ignores vehicles.
int move_cost_ter_furn (const point &p) const
bool impassable_ter_furn (const tripoint &p) const
bool passable_ter_furn (const tripoint &p) const
int combined_movecost (const tripoint &from, const tripoint &to, const vehicle *ignored_vehicle=nullptr, int modifier=0, bool flying=false, bool via_ramp=false) const
Cost to move out of one tile and into the next.
bool valid_move (const tripoint &from, const tripoint &to, bool bash=false, bool flying=false, bool via_ramp=false) const
Returns true if a creature could walk from from to to in one step.
double ranged_target_size (const tripoint &p) const
Size of map objects at p for purposes of ranged combat.
bool sees (const tripoint &F, const tripoint &T, int range, bool with_fields=true) const
Returns whether F sees T with a view range of range.
int obstacle_coverage (const tripoint &loc1, const tripoint &loc2) const
Returns coverage of target in relation to the observer.
int ledge_coverage (const Creature &viewer, const tripoint &target_p) const
int ledge_coverage (const tripoint &viewer_p, const tripoint &target_p, const float &eye_level=1.0f) const
int coverage (const tripoint &p) const
Returns coverage value of the tile.
bool clear_path (const tripoint &f, const tripoint &t, int range, int cost_min, int cost_max) const
Check whether there's a direct line of sight between F and T with the additional movecost restraints.
bool clear_path (const tripoint_bub_ms &f, const tripoint_bub_ms &t, int range, int cost_min, int cost_max) const
void reachable_flood_steps (std::vector< tripoint > &reachable_pts, const tripoint &f, int range, int cost_min, int cost_max) const
Populates a vector of points that are reachable within a number of steps from a point.
std::vector< tripoint > find_clear_path (const tripoint &source, const tripoint &destination) const
Iteratively tries Bresenham lines with different biases until it finds a clear line or decides there isn't one.
bool accessible_items (const tripoint &t) const
Check whether the player can access the items located .
bool accessible_items (const tripoint_bub_ms &t) const
std::vector< tripoint > get_dir_circle (const tripoint &f, const tripoint &t) const
Calculate next search points surrounding the current position.
std::vector< tripoint > route (const tripoint &f, const tripoint &t, const pathfinding_settings &settings, const std::unordered_set< tripoint > &pre_closed={{ }}) const
Calculate the best path using A*.
std::vector< tripoint_bub_ms > route (const tripoint_bub_ms &f, const tripoint_bub_ms &t, const pathfinding_settings &settings, const std::unordered_set< tripoint > &pre_closed={{ }}) const
std::vector< tripoint > straight_route (const tripoint &f, const tripoint &t) const
VehicleList get_vehicles ()
void add_vehicle_to_cache (vehicle *)
void clear_vehicle_point_from_cache (vehicle *veh, const tripoint &pt)
void clear_vehicle_level_caches ()
void remove_vehicle_from_cache (vehicle *veh, int zmin=-OVERMAP_DEPTH, int zmax=OVERMAP_HEIGHT)
void reset_vehicles_sm_pos ()
void rebuild_vehicle_level_caches ()
void clear_vehicle_list (int zlev)
void update_vehicle_list (const submap *to, int zlev)
bool check_vehicle_zones (int zlev)
std::vector< zone_data * > get_vehicle_zones (int zlev)
void register_vehicle_zone (vehicle *, int zlev)
bool deregister_vehicle_zone (zone_data &zone) const
std::set< tripoint_bub_ms > get_moving_vehicle_targets (const Creature &z, int max_range)
std::unique_ptr< vehicle > detach_vehicle (vehicle *veh)
void destroy_vehicle (vehicle *veh)
void vehmove ()
bool vehproceed (VehicleList &vehicle_list)
VehicleList get_vehicles (const tripoint &start, const tripoint &end)
optional_vpart_position veh_at (const tripoint &p) const
Checks if tile is occupied by vehicle and by which part.
optional_vpart_position veh_at (const tripoint_abs_ms &p) const
optional_vpart_position veh_at (const tripoint_bub_ms &p) const
vehicle * veh_at_internal (const tripoint &p, int &part_num)
const vehicle * veh_at_internal (const tripoint &p, int &part_num) const
void board_vehicle (const tripoint &p, Character *pl)
void unboard_vehicle (const vpart_reference &, Character *passenger, bool dead_passenger=false)
void unboard_vehicle (const tripoint &p, bool dead_passenger=false)
bool displace_vehicle (vehicle &veh, const tripoint &dp, bool adjust_pos=true, const std::set< int > &parts_to_move={})
void level_vehicle (vehicle &veh)
bool displace_water (const tripoint &dp)
float vehicle_wheel_traction (const vehicle &veh, bool ignore_movement_modifiers=false) const
float vehicle_vehicle_collision (vehicle &veh, vehicle &veh2, const std::vector< veh_collision > &collisions)
units::angle shake_vehicle (vehicle &veh, int velocity_before, const units::angle &direction)
vehicle * move_vehicle (vehicle &veh, const tripoint &dp, const tileray &facing)
void set (const tripoint &p, const ter_id &new_terrain, const furn_id &new_furniture)
void set (const point &p, const ter_id &new_terrain, const furn_id &new_furniture)
std::string name (const tripoint &p)
std::string name (const tripoint_bub_ms &p)
std::string name (const point &p)
std::string disp_name (const tripoint &p)
std::string obstacle_name (const tripoint &p)
Returns the name of the obstacle at p that might be blocking movement/projectiles/etc.
std::string obstacle_name (const tripoint_bub_ms &p)
bool has_furn (const tripoint &p) const
bool has_furn (const tripoint_bub_ms &p) const
bool has_furn (const point &p) const
furn_id furn (const tripoint &p) const
furn_id furn (const tripoint_bub_ms &p) const
furn_id furn (const point &p) const
bool furn_set (const tripoint &p, const furn_id &new_furniture, bool furn_reset=false, bool avoid_creatures=false)
furn_reset should be true if new_furniture is being set to f_null when the player is grab-moving furniture
bool furn_set (const tripoint_bub_ms &p, const furn_id &new_furniture, bool furn_reset=false, bool avoid_creatures=false)
bool furn_set (const point &p, const furn_id &new_furniture, bool avoid_creatures=false)
bool furn_set (const point_bub_ms &p, const furn_id &new_furniture, bool avoid_creatures=false)
void furn_clear (const tripoint &p)
void furn_clear (const point &p)
std::string furnname (const tripoint &p)
std::string furnname (const tripoint_bub_ms &p)
std::string furnname (const point &p)
bool can_move_furniture (const tripoint &pos, Character *you=nullptr) const
ter_id ter (const tripoint &p) const
ter_id ter (const tripoint_bub_ms &p) const
ter_id ter (const point &p) const
int get_map_damage (const tripoint_bub_ms &p) const
void set_map_damage (const tripoint_bub_ms &p, int dmg)
uint8_t get_known_connections (const tripoint &p, const std::bitset< NUM_TERCONN > &connect_group, const std::map< tripoint, ter_id > &override={}) const
uint8_t get_known_connections_f (const tripoint &p, const std::bitset< NUM_TERCONN > &connect_group, const std::map< tripoint, furn_id > &override={}) const
uint8_t get_known_rotates_to (const tripoint &p, const std::bitset< NUM_TERCONN > &rotate_to_group, const std::map< tripoint, ter_id > &override={}) const
uint8_t get_known_rotates_to_f (const tripoint &p, const std::bitset< NUM_TERCONN > &rotate_to_group, const std::map< tripoint, ter_id > &override={}, const std::map< tripoint, furn_id > &override_f={}) const
const harvest_id & get_harvest (const tripoint &p) const
Returns the full harvest list, for spawning.
const std::set< std::string > & get_harvest_names (const tripoint &p) const
Returns names of the items that would be dropped.
ter_id get_ter_transforms_into (const tripoint &p) const
bool ter_set (const tripoint &p, const ter_id &new_terrain, bool avoid_creatures=false)
bool ter_set (const tripoint_bub_ms &, const ter_id &new_terrain, bool avoid_creatures=false)
bool ter_set (const point &p, const ter_id &new_terrain, bool avoid_creatures=false)
bool ter_set (const point_bub_ms &p, const ter_id &new_terrain, bool avoid_creatures=false)
std::string tername (const tripoint &p) const
std::string tername (const point &p) const
bool has_nearby_fire (const tripoint &p, int radius=1) const
bool has_nearby_table (const tripoint_bub_ms &p, int radius=1) const
Check whether a table/workbench/vehicle kitchen or other flat surface is nearby that could be used for crafting or eating.
bool has_nearby_chair (const tripoint &p, int radius=1) const
Check whether a chair or vehicle seat is nearby.
bool has_nearby_ter (const tripoint &p, const ter_id &type, int radius=1) const
Checks whether a specific terrain is nearby.
bool sees_some_items (const tripoint &p, const Creature &who) const
Check if creature can see some items at p.
bool sees_some_items (const tripoint &p, const tripoint &from) const
bool could_see_items (const tripoint &p, const Creature &who) const
Check if the creature could see items at p if there were any items.
bool could_see_items (const tripoint &p, const tripoint &from) const
bool has_items (const tripoint &p) const
Checks for existence of items.
bool has_items (const tripoint_bub_ms &p) const
bool only_liquid_in_liquidcont (const tripoint &p)
void examine (Character &you, const tripoint &pos) const
Calls the examine function of furniture or terrain at given tile, for given character.
bool is_harvestable (const tripoint &pos) const
Returns true if point at pos is harvestable right now, with no extra tools.
std::string features (const tripoint &p) const
std::string features (const point &p)
bool has_flag (const std::string &flag, const tripoint &p) const
bool has_flag (const std::string &flag, const tripoint_bub_ms &p) const
bool has_flag (const std::string &flag, const point &p) const
bool can_put_items (const tripoint &p) const
bool can_put_items (const tripoint_bub_ms &p) const
bool can_put_items (const point &p) const
bool can_put_items_ter_furn (const tripoint &p) const
bool can_put_items_ter_furn (const tripoint_bub_ms &p) const
bool can_put_items_ter_furn (const point &p) const
bool has_flag_ter (const std::string &flag, const tripoint &p) const
bool has_flag_ter (const std::string &flag, const point &p) const
bool has_flag_furn (const std::string &flag, const tripoint &p) const
bool has_flag_furn (const std::string &flag, const tripoint_bub_ms &p) const
bool has_flag_furn (const std::string &flag, const point &p) const
bool has_flag_ter_or_furn (const std::string &flag, const tripoint &p) const
bool has_flag_ter_or_furn (const std::string &flag, const point &p) const
bool has_flag (ter_furn_flag flag, const tripoint &p) const
bool has_flag (ter_furn_flag flag, const tripoint_bub_ms &p) const
bool has_flag (ter_furn_flag flag, const point &p) const
bool has_flag_ter (ter_furn_flag flag, const tripoint &p) const
bool has_flag_ter (ter_furn_flag flag, const tripoint_bub_ms &p) const
bool has_flag_ter (ter_furn_flag flag, const point &p) const
bool has_flag_ter (ter_furn_flag flag, const point_bub_ms &p) const
bool has_flag_furn (ter_furn_flag flag, const tripoint &p) const
bool has_flag_furn (ter_furn_flag flag, const tripoint_bub_ms &p) const
bool has_flag_furn (ter_furn_flag flag, const point &p) const
bool has_flag_ter_or_furn (ter_furn_flag flag, const tripoint &p) const
bool has_flag_ter_or_furn (ter_furn_flag flag, const tripoint_bub_ms &p) const
bool has_flag_ter_or_furn (ter_furn_flag flag, const point &p) const
bool is_bashable (const tripoint &p, bool allow_floor=false) const
Returns true if there is a bashable vehicle part or the furn/terrain is bashable at p.
bool is_bashable (const point &p) const
bool is_bashable_ter (const tripoint &p, bool allow_floor=false) const
Returns true if the terrain at p is bashable.
bool is_bashable_ter (const point &p) const
bool is_bashable_furn (const tripoint &p) const
Returns true if the furniture at p is bashable.
bool is_bashable_furn (const point &p) const
bool is_bashable_ter_furn (const tripoint &p, bool allow_floor=false) const
Returns true if the furniture or terrain at p is bashable.
bool is_bashable_ter_furn (const point &p) const
int bash_strength (const tripoint &p, bool allow_floor=false) const
Returns max_str of the furniture or terrain at p.
int bash_strength (const point &p) const
int bash_resistance (const tripoint &p, bool allow_floor=false) const
Returns min_str of the furniture or terrain at p.
int bash_resistance (const point &p) const
int bash_rating (int str, const tripoint &p, bool allow_floor=false) const
Returns a success rating from -1 to 10 for a given tile based on a set strength, used for AI movement planning Values roughly correspond to 10% increment chances of success on a given bash, rounded down.
int bash_rating (const int str, const point &p) const
void make_rubble (const tripoint &p, const furn_id &rubble_type, bool items, const ter_id &floor_type, bool overwrite=false)
Generates rubble at the given location, if overwrite is true it just writes on top of what currently exists floor_type is only used if there is a non-bashable wall at the location or with overwrite = true.
void make_rubble (const tripoint &p, const furn_id &rubble_type, bool items)
void make_rubble (const tripoint &p)
bool is_outside (const tripoint &p) const
bool is_outside (const point &p) const
bool is_divable (const tripoint &p) const
Returns whether or not the terrain at the given location can be dived into (by monsters that can swim or are aquatic or non-breathing).
bool is_divable (const point &p) const
bool is_water_shallow_current (const tripoint &p) const
bool is_water_shallow_current (const point &p) const
bool is_last_ter_wall (bool no_furn, const point &p, const point &max, direction dir) const
Check if the last terrain is wall in direction NORTH, SOUTH, WEST or EAST.
bool tinder_at (const tripoint &p)
Checks if there are any tinder flagged items on the tile.
bool flammable_items_at (const tripoint &p, int threshold=0)
Checks if there are any flammable items on the tile.
bool flammable_items_at (const tripoint_bub_ms &p, int threshold=0)
bool is_flammable (const tripoint &p)
Returns true if there is a flammable item or field or the furn/terrain is flammable at p.
bool is_flammable (const tripoint_bub_ms &p)
point random_outdoor_tile () const
void draw_line_ter (const ter_id &type, const point &p1, const point &p2, int z, bool avoid_creature=false)
void draw_line_furn (const furn_id &type, const point &p1, const point &p2, int z, bool avoid_creatures=false)
void draw_fill_background (const ter_id &type)
void draw_fill_background (ter_id(*f)())
void draw_fill_background (const weighted_int_list< ter_id > &f)
void draw_square_ter (const ter_id &type, const point &p1, const point &p2, int z, bool avoid_creature=false)
void draw_square_furn (const furn_id &type, const point &p1, const point &p2, int z, bool avoid_creatures=false)
void draw_square_ter (ter_id(*f)(), const point &p1, const point &p2, bool avoid_creatures=false)
void draw_square_ter (const weighted_int_list< ter_id > &f, const point &p1, const point &p2, bool avoid_creatures=false)
void draw_rough_circle_ter (const ter_id &type, const point &p, int rad)
void draw_rough_circle_furn (const furn_id &type, const point &p, int rad)
void draw_circle_ter (const ter_id &type, const rl_vec2d &p, double rad)
void draw_circle_ter (const ter_id &type, const point &p, int rad)
void draw_circle_furn (const furn_id &type, const point &p, int rad)
void add_corpse (const tripoint &p)
void translate (const ter_id &from, const ter_id &to)
void translate_radius (const ter_id &from, const ter_id &to, float radi, const tripoint &p, bool same_submap=false, bool toggle_between=false)
void transform_radius (const ter_furn_transform_id &transform, int radi, const tripoint_abs_ms &p)
void transform_line (const ter_furn_transform_id &transform, const tripoint_abs_ms &first, const tripoint_abs_ms &second)
bool close_door (const tripoint &p, bool inside, bool check_only)
bool close_door (const tripoint_bub_ms &p, bool inside, bool check_only)
bool open_door (Creature const &u, const tripoint &p, bool inside, bool check_only=false)
void batter (const tripoint &p, int power, int tries=1, bool silent=false)
bash a square for a set number of times at set power.
void destroy (const tripoint &p, bool silent=false)
Keeps bashing a square until it can't be bashed anymore.
void destroy_furn (const tripoint &p, bool silent=false)
Keeps bashing a square until there is no more furniture.
void destroy_furn (const tripoint_bub_ms &, bool silent=false)
void crush (const tripoint &p)
void shoot (const tripoint &p, projectile &proj, bool hit_items)
int collapse_check (const tripoint &p) const
Checks if a square should collapse, returns the X for the one_in(X) collapse chance.
void collapse_at (const tripoint &p, bool silent, bool was_supporting=false, bool destroy_pos=true)
Causes a collapse at p, such as from destroying a wall.
void smash_items (const tripoint &p, int power, const std::string &cause_message)
Tries to smash the items at the given tripoint.
bash_params bash (const tripoint &p, int str, bool silent=false, bool destroy=false, bool bash_floor=false, const vehicle *bashing_vehicle=nullptr)
Returns a pair where first is whether anything was smashed and second is if it was destroyed.
bool hit_with_acid (const tripoint &p)
bool hit_with_fire (const tripoint &p)
bool has_adjacent_furniture_with (const tripoint &p, const std::function< bool(const furn_t &)> &filter) const
Returns true if there is furniture for which filter returns true in a 1 tile radius of p.
bool terrain_moppable (const tripoint_bub_ms &p)
Check for moppable fields/items at this location.
bool mop_spills (const tripoint_bub_ms &p)
Remove moppable fields/items at this location.
void decay_fields_and_scent (const time_duration &amount)
Moved here from weather.cpp for speed.
std::string get_signage (const tripoint &p) const
void set_signage (const tripoint &p, const std::string &message)
void delete_signage (const tripoint &p)
void delete_signage (const tripoint_bub_ms &p)
int get_radiation (const tripoint &p) const
void set_radiation (const tripoint &p, int value)
void set_radiation (const point &p, const int value)
void adjust_radiation (const tripoint &p, int delta)
Increment the radiation in the given tile by the given delta (decrement it if delta is negative)
void adjust_radiation (const point &p, const int delta)
units::temperature_delta get_temperature_mod (const tripoint &p) const
void set_temperature_mod (const tripoint &p, units::temperature_delta temperature_mod)
void set_temperature_mod (const point &p, units::temperature_delta new_temperature_mod)
void check_submap_active_item_consistency ()
map_stack i_at (const tripoint &p)
map_stack i_at (const tripoint_bub_ms &p)
map_stack i_at (const point &p)
item water_from (const tripoint &p)
void i_clear (const tripoint &p)
void i_clear (const tripoint_bub_ms &p)
void i_clear (const point &p)
map_stack::iterator i_rem (const tripoint &p, const map_stack::const_iterator &it)
map_stack::iterator i_rem (const point &location, const map_stack::const_iterator &it)
void i_rem (const tripoint &p, item *it)
void i_rem (const tripoint_bub_ms &p, item *it)
void i_rem (const point &p, item *it)
void spawn_artifact (const tripoint &p, const relic_procgen_id &id, int max_attributes=5, int power_level=1000, int max_negative_power=-2000, bool is_resonant=false)
void spawn_artifact (const tripoint_bub_ms &p, const relic_procgen_id &id, int max_attributes=5, int power_level=1000, int max_negative_power=-2000, bool is_resonant=false)
void spawn_item (const tripoint &p, const itype_id &type_id, unsigned quantity=1, int charges=0, const time_point &birthday=calendar::start_of_cataclysm, int damlevel=0, const std::set< flag_id > &flags={}, const std::string &variant="", const std::string &faction="")
void spawn_item (const point &p, const itype_id &type_id, unsigned quantity=1, int charges=0, const time_point &birthday=calendar::start_of_cataclysm, int damlevel=0, const std::set< flag_id > &flags={}, const std::string &variant="", const std::string &faction="")
void spawn_item (const tripoint &p, const std::string &type_id, unsigned quantity=1, int charges=0, const time_point &birthday=calendar::start_of_cataclysm, int damlevel=0, const std::set< flag_id > &flags={}, const std::string &variant="", const std::string &faction="")
void spawn_item (const point &p, const std::string &type_id, unsigned quantity=1, int charges=0, const time_point &birthday=calendar::start_of_cataclysm, int damlevel=0, const std::set< flag_id > &flags={}, const std::string &variant="", const std::string &faction="")
units::volume max_volume (const tripoint &p)
units::volume free_volume (const tripoint &p)
units::volume free_volume (const tripoint_bub_ms &p)
units::volume stored_volume (const tripoint &p)
item_location add_item_ret_loc (const tripoint &pos, item obj, bool overflow=true)
Adds an item to map tile or stacks charges.
item & add_item_or_charges (const tripoint &pos, item obj, bool overflow=true)
item & add_item_or_charges (const tripoint &pos, item obj, int &copies_remaining, bool overflow=true)
item & add_item_or_charges (const tripoint_bub_ms &pos, item obj, bool overflow=true)
item & add_item_or_charges (const tripoint_bub_ms &pos, item obj, int &copies_remaining, bool overflow=true)
item & add_item_or_charges (const point &p, const item &obj, bool overflow=true)
float item_category_spawn_rate (const item &itm)
Gets spawn_rate value for item category of 'itm'.
item & add_item (const tripoint &p, item new_item, int copies)
Place an item on the map, despite the parameter name, this is not necessarily a new item.
item & add_item (const tripoint &p, item new_item)
void add_item (const point &p, const item &new_item)
void make_active (item_location &loc)
Update an item's active status, for example when adding hot or perishable liquid to a container.
void make_active (tripoint_abs_sm const &loc)
void update_lum (item_location &loc, bool add)
Update luminosity before and after item's transformation.
std::list< item > use_amount_square (const tripoint &p, const itype_id &type, int &quantity, const std::function< bool(const item &)> &filter=return_true< item >)
std::list< item > use_amount (const tripoint &origin, int range, const itype_id &type, int &quantity, const std::function< bool(const item &)> &filter=return_true< item >, bool select_ind=false)
std::list< item > use_amount (const std::vector< tripoint > &reachable_pts, const itype_id &type, int &quantity, const std::function< bool(const item &)> &filter=return_true< item >, bool select_ind=false)
std::list< item > use_charges (const tripoint &origin, int range, const itype_id &type, int &quantity, const std::function< bool(const item &)> &filter=return_true< item >, basecamp *bcp=nullptr, bool in_tools=false)
std::list< item > use_charges (const std::vector< tripoint > &reachable_pts, const itype_id &type, int &quantity, const std::function< bool(const item &)> &filter=return_true< item >, basecamp *bcp=nullptr, bool in_tools=false)
std::list< item_location > items_with (const tripoint &p, const std::function< bool(const item &)> &filter)
Find items located at point p (on map or in vehicles) that pass the filter.
units::energy consume_ups (const std::vector< tripoint > &reachable_pts, units::energy qty)
Consume UPS from UPS sources from area centered at origin.
units::energy consume_ups (const tripoint &origin, int range, units::energy qty)
std::list< std::pair< tripoint, item * > > get_rc_items (const tripoint &p={ -1, -1, -1 })
std::vector< item * > place_items (const item_group_id &group_id, int chance, const tripoint &p1, const tripoint &p2, bool ongrass, const time_point &turn, int magazine=0, int ammo=0, const std::string &faction="")
Place items from item group in the rectangle f - t.
std::vector< item * > place_items (const item_group_id &group_id, int chance, const tripoint_bub_ms &p1, const tripoint_bub_ms &p2, bool ongrass, const time_point &turn, int magazine=0, int ammo=0, const std::string &faction="")
std::vector< item * > place_items (const item_group_id &group_id, int chance, const point &p1, const point &p2, const int z_level, bool ongrass, const time_point &turn, int magazine=0, int ammo=0, const std::string &faction="")
std::vector< item * > put_items_from_loc (const item_group_id &group_id, const tripoint &p, const time_point &turn=calendar::start_of_cataclysm)
Place items from an item group at p.
std::vector< item * > spawn_items (const tripoint &p, const std::vector< item > &new_items)
std::vector< item * > spawn_items (const tripoint_bub_ms &p, const std::vector< item > &new_items)
void spawn_items (const point &p, const std::vector< item > &new_items)
void create_anomaly (const tripoint &p, artifact_natural_property prop, bool create_rubble=true)
void create_anomaly (const tripoint_bub_ms &p, artifact_natural_property prop, bool create_rubble=true)
void create_anomaly (const point &cp, artifact_natural_property prop, bool create_rubble=true)
void partial_con_set (const tripoint_bub_ms &p, const partial_con &con)
void partial_con_remove (const tripoint_bub_ms &p)
partial_con * partial_con_at (const tripoint_bub_ms &p)
void trap_set (const tripoint &p, const trap_id &type)
void trap_set (const tripoint_bub_ms &p, const trap_id &type)
const trap & tr_at (const tripoint &p) const
const trap & tr_at (const tripoint_abs_ms &p) const
const trap & tr_at (const tripoint_bub_ms &p) const
bool can_see_trap_at (const tripoint &p, const Character &c) const
See trap::can_see, which is called for the trap here.
void remove_trap (const tripoint &p)
void remove_trap (const tripoint_bub_ms &p)
const std::vector< tripoint > & get_furn_field_locations () const
const std::vector< tripoint > & get_ter_field_locations () const
const std::vector< tripoint > & trap_locations (const trap_id &type) const
void maybe_trigger_trap (const tripoint &pos, Creature &c, bool may_avoid) const
Handles activating a trap.
void maybe_trigger_trap (const tripoint_bub_ms &pos, Creature &c, bool may_avoid) const
void maybe_trigger_prox_trap (const tripoint &pos, Creature &c, bool may_avoid) const
void create_burnproducts (const tripoint &p, const item &fuel, const units::mass &burned_mass)
void process_fields ()
void process_fields_in_submap (submap *current_submap, const tripoint &submap_pos)
void creature_in_field (Creature &critter)
Apply field effects to the creature when it's on a square with fields.
void creature_on_trap (Creature &critter, bool may_avoid=true) const
Apply trap effects to the creature, similar to creature_in_field.
const field & field_at (const tripoint &p) const
Get the fields that are here.
field & field_at (const tripoint &p)
Gets fields that are here.
field & field_at (const tripoint_bub_ms &p)
time_duration get_field_age (const tripoint &p, const field_type_id &type) const
Get the age of a field entry (field_entry::age), if there is no field of that type, returns -1_turns.
time_duration get_field_age (const tripoint_bub_ms &p, const field_type_id &type) const
int get_field_intensity (const tripoint &p, const field_type_id &type) const
Get the intensity of a field entry (field_entry::intensity), if there is no field of that type, returns 0.
int get_field_intensity (const tripoint_bub_ms &p, const field_type_id &type) const
time_duration mod_field_age (const tripoint &p, const field_type_id &type, const time_duration &offset)
Increment/decrement age of field entry at point.
int mod_field_intensity (const tripoint &p, const field_type_id &type, int offset)
Increment/decrement intensity of field entry at point, creating if not present, removing if intensity becomes 0.
time_duration set_field_age (const tripoint &p, const field_type_id &type, const time_duration &age, bool isoffset=false)
Set age of field entry at point.
int set_field_intensity (const tripoint &p, const field_type_id &type, int new_intensity, bool isoffset=false)
Set intensity of field entry at point, creating if not present, removing if intensity becomes 0.
bool has_field_at (const tripoint &p, bool check_bounds=true) const
bool has_field_at (const tripoint &p, const field_type_id &type) const
field_entry * get_field (const tripoint &p, const field_type_id &type)
Get field of specific type at point.
field_entry * get_field (const tripoint_bub_ms &p, const field_type_id &type)
const field_entry * get_field (const tripoint &p, const field_type_id &type) const
const field_entry * get_field (const tripoint_bub_ms &p, const field_type_id &type) const
bool dangerous_field_at (const tripoint &p)
bool dangerous_field_at (const tripoint_bub_ms &p)
bool mopsafe_field_at (const tripoint &p)
bool add_field (const tripoint &p, const field_type_id &type_id, int intensity=INT_MAX, const time_duration &age=0_turns, bool hit_player=true)
Add field entry at point, or set intensity if present.
bool add_field (const tripoint_bub_ms &p, const field_type_id &type_id, int intensity=INT_MAX, const time_duration &age=0_turns, bool hit_player=true)
void remove_field (const tripoint &p, const field_type_id &field_to_remove)
Remove field entry at xy, ignored if the field entry is not present.
void remove_field (const tripoint_bub_ms &p, const field_type_id &field_to_remove)
void delete_field (const tripoint &p, const field_type_id &field_to_remove)
Deletes the field without regard for any possible need for cleanup.
void clear_fields (const tripoint &p)
Remove all field entries at location.
const field_type_str_id & get_applicable_electricity_field (const tripoint &p) const
Get applicable fd_electricity field type for a given point.
void add_splatter (const field_type_id &type, const tripoint &where, int intensity=1)
void add_splatter_trail (const field_type_id &type, const tripoint &from, const tripoint &to)
void add_splash (const field_type_id &type, const tripoint &center, int radius, int intensity)
void propagate_field (const tripoint &center, const field_type_id &type, int amount, int max_intensity=0)
void emit_field (const tripoint &pos, const emit_id &src, float mul=1.0f)
Runs one cycle of emission src which may result in propagation of fields.
void scent_blockers (std::array< std::array< bool, MAPSIZE_X >, MAPSIZE_Y > &blocks_scent, std::array< std::array< bool, MAPSIZE_X >, MAPSIZE_Y > &reduces_scent, const point &min, const point &max)
Build the map of scent-resistant tiles.
computer * computer_at (const tripoint &p)
computer * add_computer (const tripoint &p, const std::string &name, int security)
void add_camp (const tripoint_abs_omt &omt_pos, const std::string &name)
void remove_submap_camp (const tripoint &)
basecamp hoist_submap_camp (const tripoint &p)
bool point_within_camp (const tripoint &point_check) const
bool has_graffiti_at (const tripoint &p) const
const std::string & graffiti_at (const tripoint &p) const
void set_graffiti (const tripoint &p, const std::string &contents)
void delete_graffiti (const tripoint &p)
int climb_difficulty (const tripoint &p) const
Checks 3x3 block centered on p for terrain to climb.
bool has_floor (const tripoint &p) const
bool has_floor_or_water (const tripoint &p) const
bool supports_above (const tripoint &p) const
Does this tile support vehicles and furniture above it.
bool has_floor_or_support (const tripoint &p) const
bool has_vehicle_floor (const tripoint &p) const
bool has_vehicle_floor (const tripoint_bub_ms &p) const
void drop_everything (const tripoint &p)
Handles map objects of given type (not creatures) falling down.
void drop_furniture (const tripoint &p)
void drop_items (const tripoint &p)
void drop_vehicle (const tripoint &p)
void drop_fields (const tripoint &p)
void process_falling ()
Invoked drop_everything on cached dirty tiles.
bool is_cornerfloor (const tripoint &p) const
void generate (const tripoint_abs_omt &p, const time_point &when)
void place_spawns (const mongroup_id &group, int chance, const point_bub_ms &p1, const point_bub_ms &p2, int z_level, float density, bool individual=false, bool friendly=false, const std::optional< std::string > &name=std::nullopt, int mission_id=-1)
void place_gas_pump (const tripoint_bub_ms &p, int charges, const itype_id &fuel_type)
void place_gas_pump (const tripoint_bub_ms &p, int charges)
void place_toilet (const tripoint_bub_ms &p, int charges=6 *4)
void place_vending (const tripoint_bub_ms &p, const item_group_id &type, bool reinforced=false, bool lootable=false)
character_id place_npc (const point &p, const string_id< npc_template > &type)
void apply_faction_ownership (const point &p1, const point &p2, const faction_id &id)
void add_spawn (const mtype_id &type, int count, const tripoint_bub_ms &p, bool friendly=false, int faction_id=-1, int mission_id=-1, const std::optional< std::string > &name=std::nullopt)
void add_spawn (const mtype_id &type, int count, const tripoint_bub_ms &p, bool friendly, int faction_id, int mission_id, const std::optional< std::string > &name, const spawn_data &data)
void add_spawn (const MonsterGroupResult &spawn_details, const tripoint_bub_ms &p)
void do_vehicle_caching (int z)
void build_map_cache (int zlev, bool skip_lightmap=false)
void build_obstacle_cache (const tripoint &start, const tripoint &end, cata::mdarray< fragment_cloud, point_bub_ms > &obstacle_cache)
vehicle * add_vehicle (const vproto_id &type, const tripoint &p, const units::angle &dir, int init_veh_fuel=-1, int init_veh_status=-1, bool merge_wrecks=true)
float light_transparency (const tripoint &p) const
lit_level light_at (const tripoint &p) const
float ambient_light_at (const tripoint &p) const
bool is_transparent (const tripoint &p) const
Returns whether the tile at p is transparent(you can look past it).
bool is_transparent_wo_fields (const tripoint &p) const
bool pl_sees (const tripoint &t, int max_range) const
Whether the player character (g->u) can see the given square (local map coordinates).
tripoint_abs_sm get_abs_sub () const
return abs_sub
tripoint getabs (const tripoint &p) const
Translates local (to this map) coordinates of a square to global absolute coordinates.
tripoint getabs (const tripoint_bub_ms &p) const
tripoint_abs_ms getglobal (const tripoint &p) const
tripoint_abs_ms getglobal (const tripoint_bub_ms &p) const
point getabs (const point &p) const
tripoint getlocal (const tripoint &p) const
Inverse of getabs.
tripoint getlocal (const tripoint_abs_ms &p) const
point getlocal (const point &p) const
tripoint_bub_ms bub_from_abs (const tripoint &p) const
tripoint_bub_ms bub_from_abs (const tripoint_abs_ms &p) const
bool inbounds (const tripoint &p) const
bool inbounds (const tripoint_bub_ms &p) const
bool inbounds (const tripoint_abs_ms &p) const
bool inbounds (const tripoint_abs_sm &p) const
bool inbounds (const tripoint_abs_omt &p) const
bool inbounds (const point &p) const
bool inbounds_z (const int z) const
void clip_to_bounds (tripoint &p) const
Clips the coordinates of p to fit the map bounds.
void clip_to_bounds (int &x, int &y) const
void clip_to_bounds (int &x, int &y, int &z) const
int getmapsize () const
void rotate (int turns, bool setpos_safe=false)
Rotates this map, and all of its contents, by the specified multiple of 90 degrees.
void mirror (bool mirror_horizontal, bool mirror_vertical)
Mirrors this map, and all of its contents along with all its contents in the directions specified.
void spawn_monsters (bool ignore_sight, bool spawn_nonlocal=false)
Spawn monsters from submap spawn points and from the overmap.
void rotten_item_spawn (const item &item, const tripoint &p)
Checks to see if the item that is rotting away generates a creature when it does.
void cut_down_tree (tripoint_bub_ms p, point dir)
Removes the tree at 'p' and produces a trunk_yield length line of trunks in the 'dir' direction from 'p', leaving a stump behind at 'p'.
void build_outside_cache (int zlev)
std::bitset< OVERMAP_LAYERS > get_inter_level_visibility (int origin_zlevel) const
bool build_floor_cache (int zlev)
void build_floor_caches ()
void seen_cache_process_ledges (array_of_grids_of< float > &seen_caches, const array_of_grids_of< const bool > &floor_caches, const std::optional< tripoint > &override_p) const
void process_items ()
int supports_zlevels () const
void queue_main_cleanup ()
bool is_main_cleanup_queued () const
void main_cleanup_override (bool over)
const level_cache & get_cache_ref (int zlev) const
const pathfinding_cache & get_pathfinding_cache_ref (int zlev) const
void update_pathfinding_cache (const tripoint &p) const
void update_pathfinding_cache (int zlev) const
void update_visibility_cache (int zlev)
void invalidate_visibility_cache ()
const visibility_variables & get_visibility_variables_cache () const
void update_submaps_with_active_items ()
const std::set< tripoint_abs_sm > & get_submaps_with_active_items () const
tripoint_range< tripoint > points_in_rectangle (const tripoint &from, const tripoint &to) const
tripoint_range< tripoint > points_in_radius (const tripoint &center, size_t radius, size_t radiusz=0) const
tripoint_range< tripoint_bub_ms > points_in_radius (const tripoint_bub_ms &center, size_t radius, size_t radiusz=0) const
tripoint_range< tripoint > points_on_zlevel () const
Yields a range of all points that are contained in the map and have the z-level of this map (abs_sub).
tripoint_range< tripoint > points_on_zlevel (int z) const
Same as above, but uses the specific z-level.
std::list< item_location > get_active_items_in_radius (const tripoint &center, int radius)
std::list< item_location > get_active_items_in_radius (const tripoint &center, int radius, special_item_type type)
std::list< tripoint > find_furnitures_with_flag_in_radius (const tripoint &center, size_t radius, const std::string &flag, size_t radiusz=0) const
returns positions of furnitures with matching flag in the specified radius
std::list< tripoint > find_furnitures_with_flag_in_radius (const tripoint &center, size_t radius, ter_furn_flag flag, size_t radiusz=0) const
returns positions of furnitures with matching flag in the specified radius
std::list< Creature * > get_creatures_in_radius (const tripoint &center, size_t radius, size_t radiusz=0) const
returns creatures in specified radius
level_cache & access_cache (int zlev)
const level_cache & access_cache (int zlev) const
bool dont_draw_lower_floor (const tripoint &p) const
bool has_haulable_items (const tripoint &pos)
std::vector< item_location > get_haulable_items (const tripoint &pos)
map (int mapsize, bool zlev)
void saven (const tripoint &grid)
void loadn (const tripoint &grid, bool update_vehicles)
void loadn (const point &grid, bool update_vehicles)
void actualize (const tripoint &grid)
Fast forward a submap that has just been loading into this map.
void add_roofs (const tripoint &grid)
Hacks in missing roofs.
void fill_funnels (const tripoint &p, const time_point &since)
Try to fill funnel based items here.
void grow_plant (const tripoint &p)
Try to grow a harvestable plant to the next stage(s).
void restock_fruits (const tripoint &p, const time_duration &time_since_last_actualize)
Try to grow fruits on static plants (not planted by the player)
void produce_sap (const tripoint &p, const time_duration &time_since_last_actualize)
Produce sap on tapped maple trees.
void rad_scorch (const tripoint &p, const time_duration &time_since_last_actualize)
Radiation-related plant (and fungus?) death.
void decay_cosmetic_fields (const tripoint &p, const time_duration &time_since_last_actualize)
void player_in_field (Character &you)
void monster_in_field (monster &z)
void shift_traps (const tripoint &shift)
As part of the map shifting, this shifts the trap locations stored in traplocs.
void copy_grid (const tripoint &to, const tripoint &from)
void draw_map (mapgendata &dat)
void draw_lab (mapgendata &dat)
void draw_slimepit (const mapgendata &dat)
bool build_transparency_cache (int zlev)
bool build_vision_transparency_cache (int zlev)
void build_sunlight_cache (int pzlev)
void generate_lightmap (int zlev)
void build_seen_cache (const tripoint &origin, int target_z, int extension_range=60, bool cumulative=false, bool camera=false, int penalty=0)
Calculates the Field Of View for the provided map from the given x, y coordinates.
void apply_character_light (Character &p)
void set_abs_sub (const tripoint_abs_sm &p)
Sets abs_sub, see there.
size_t get_nonant (const tripoint &gridp) const
Get the index of a submap pointer in the grid given by grid coordinates.
size_t get_nonant (const point &gridp) const
void setsubmap (size_t grididx, submap *smap)
Set the submap pointer in grid at the give index.
Static Private Member Functions inherited from map
static apparent_light_info apparent_light_helper (const level_cache &map_cache, const tripoint &p)
Helper function for light calculation; exposed here for map editor.
Private Attributes inherited from map
std::set< vehicle * > dirty_vehicle_list
int my_MAPSIZE
int my_HALF_MAPSIZE
bool zlevels
tripoint_abs_sm abs_sub
Absolute coordinates of first submap (get_submap_at(0,0)) This is in submap coordinates (see overmapbuffer for explanation).
Detailed Description
Tinymap is a small version of the map which covers a single overmap terrain (OMT) tile, which corresponds to 2 * 2 submaps, or 24 * 24 map tiles.
In addition to being smaller than the map, it's also limited to a single Z level (defined the the tripoint_abs_omt parameter to the 'load' operation, so it's not tied to the Z = 0 level). The tinymap's natural relative reference system is the tripoint_omt_ms one.
Definition at line 2422 of file map.h.
Constructor & Destructor Documentation
tinymap() [1/2]
tinymap::tinymap (int mapsize, bool zlev) inline protected
Definition at line 2426 of file map.h.
 : map( mapsize, zlev ) {};
tinymap() [2/2]
tinymap::tinymap () inline
Definition at line 2434 of file map.h.
 : map( 2, false ) {}
Member Function Documentation
add_computer()
computer* tinymap::add_computer (const tripoint & p, const std::string & name, int security) inline
Definition at line 2529 of file map.h.
{
             return map::add_computer( p, name, security );    // TODO: Make it typed
         }
References map::add_computer(), and name().
Referenced by create_lab_consoles(), and mission_start::place_npc_software().
add_corpse()
void tinymap::add_corpse (const tripoint & p) inline
Definition at line 2591 of file map.h.
{
             map::add_corpse( p );
         }
References map::add_corpse().
Referenced by MapExtras::mx_minefield().
add_field() [1/2]
bool tinymap::add_field (const tripoint & p, const field_type_id & type_id, int intensity = INT_MAX, const time_duration & age = 0_turns, bool hit_player = true) inline
Definition at line 2600 of file map.h.
{
             return map::add_field( p, type_id, intensity, age, hit_player ); // TODO: Make it typed
         }
References map::add_field(), and intensity.
Referenced by apply_construction_marker(), start_location::burn(), MapExtras::mx_minefield(), and zone_data::refresh_display().
add_field() [2/2]
bool tinymap::add_field (const tripoint_omt_ms & p, const field_type_id & type_id, int intensity = INT_MAX, const time_duration & age = 0_turns, bool hit_player = true) inline
Definition at line 2604 of file map.h.
{
             return map::add_field( p.raw(), type_id, intensity, age, hit_player );
         }
References map::add_field(), intensity, and coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
add_item()
item& tinymap::add_item (const tripoint & p, item new_item) inline
Definition at line 2570 of file map.h.
{
             return map::add_item( p, std::move( new_item ) );  // TODO: Make it typed
         }
References map::add_item().
Referenced by explosion_handler::nuke().
add_item_or_charges() [1/2]
item& tinymap::add_item_or_charges (const point & p, const item & obj, bool overflow = true) inline
Definition at line 2573 of file map.h.
                                                           { // TODO: Make it typed
             return map::add_item_or_charges( tripoint( p, abs_sub.z() ), obj, overflow );
         }
References map::abs_sub, map::add_item_or_charges(), tripoint, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by farm_action(), talk_function::field_plant(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::map_add_item(), MapExtras::mx_minefield(), om_set_hide_site(), and Character::place_corpse().
add_item_or_charges() [2/2]
item& tinymap::add_item_or_charges (const tripoint & pos, item obj, bool overflow = true) inline
Definition at line 2582 of file map.h.
{
             return map::add_item_or_charges( pos, std::move( obj ), overflow );  // TODO: Make it typed
         }
References map::add_item_or_charges(), and math_opers::pos().
add_spawn()
void tinymap::add_spawn (const mtype_id & type, int count, const tripoint_omt_ms & p, bool friendly = false, int faction_id = -1, int mission_id = -1, const std::optional< std::string > & name = std::nullopt) inline
Definition at line 2464 of file map.h.
{
             map::add_spawn( type, count, rebase_bub( p ), friendly, faction_id, mission_id, name );
         }
References map::add_spawn(), friendly, name(), rebase_bub(), and type.
add_splatter_trail()
void tinymap::add_splatter_trail (const field_type_id & type, const tripoint & from, const tripoint & to) inline
Definition at line 2655 of file map.h.
{
             return map::add_splatter_trail( type, from, to );    // TODO: Make it typed
         }
References map::add_splatter_trail(), and type.
Referenced by MapExtras::mx_minefield().
add_vehicle()
vehicle* tinymap::add_vehicle (const vproto_id & type, const tripoint & p, const units::angle & dir, int init_veh_fuel = -1, int init_veh_status = -1, bool merge_wrecks = true) inline
Definition at line 2650 of file map.h.
{
             return map::add_vehicle( type, p, dir, init_veh_fuel, init_veh_status,
                                      merge_wrecks ); // TODO: Make it typed
         }
References map::add_vehicle(), and type.
Referenced by MapExtras::mx_minefield(), and game::place_vehicle_nearby().
build_outside_cache()
void map::build_outside_cache
Definition at line 2028 of file map.cpp.
 {
     auto *ch_lazy = get_cache_lazy( zlev );
     if( !ch_lazy || !ch_lazy->outside_cache_dirty ) {
         return;
     }
     level_cache &ch = *ch_lazy;
     // Make a bigger cache to avoid bounds checking
     // We will later copy it to our regular cache
     const size_t padded_w = MAPSIZE_X + 2;
     const size_t padded_h = MAPSIZE_Y + 2;
     cata::mdarray<bool, point_bub_ms, padded_w, padded_h> padded_cache;
     auto &outside_cache = ch.outside_cache;
     if( zlev < 0 ) {
         std::uninitialized_fill_n(
             &outside_cache[0][0], MAPSIZE_X * MAPSIZE_Y, false );
         return;
     }
     padded_cache.fill( true );
     for( int smx = 0; smx < my_MAPSIZE; ++smx ) {
         for( int smy = 0; smy < my_MAPSIZE; ++smy ) {
             const submap *cur_submap = get_submap_at_grid( { smx, smy, zlev } );
             if( cur_submap == nullptr ) {
                 debugmsg( "Tried to build outside cache at (%d,%d,%d) but the submap is not loaded", smx, smy,
                           zlev );
                 continue;
             }
             for( int sx = 0; sx < SEEX; ++sx ) {
                 for( int sy = 0; sy < SEEY; ++sy ) {
                     point sp( sx, sy );
                     if( cur_submap->get_ter( sp ).obj().has_flag( ter_furn_flag::TFLAG_INDOORS ) ||
                         cur_submap->get_furn( sp ).obj().has_flag( ter_furn_flag::TFLAG_INDOORS ) ) {
                         const point p( sx + smx * SEEX, sy + smy * SEEY );
                         // Add 1 to both coordinates, because we're operating on the padded cache
                         for( int dx = 0; dx <= 2; dx++ ) {
                             for( int dy = 0; dy <= 2; dy++ ) {
                                 padded_cache[p.x + dx][p.y + dy] = false;
                             }
                         }
                     }
                 }
             }
         }
     }
     // Copy the padded cache back to the proper one, but with no padding
     for( int x = 0; x < SEEX * my_MAPSIZE; x++ ) {
         std::copy_n( &padded_cache[x + 1][1], SEEX * my_MAPSIZE, &outside_cache[x][0] );
     }
     ch.outside_cache_dirty = false;
 }
Referenced by start_location::burn(), and start_location::prepare_map().
cast_to_map()
map* tinymap::cast_to_map () inline
Definition at line 2442 of file map.h.
{
             return this;
         }
Referenced by apply_construction_marker(), MapExtras::apply_function(), get_changed_ids_from_update(), and update_mapgen_function_json::update_map().
collapse_at()
void tinymap::collapse_at (const tripoint & p, bool silent, bool was_supporting = false, bool destroy_pos = true) inline
Definition at line 2658 of file map.h.
{
             map::collapse_at( p, silent, was_supporting, destroy_pos );
         }
References map::collapse_at(), and silent.
Referenced by talk_function::loot_building(), and om_cutdown_trees().
cut_down_tree()
void tinymap::cut_down_tree (tripoint_omt_ms p, point dir) inline protected
Definition at line 2429 of file map.h.
{
             map::cut_down_tree( tripoint_bub_ms( p.raw() ), dir );
         };
References map::cut_down_tree(), and coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by smallmap::cut_down_tree().
delete_field() [1/2]
void tinymap::delete_field (const tripoint & p, const field_type_id & field_to_remove) inline
Definition at line 2608 of file map.h.
{
             return map::delete_field( p, field_to_remove );    // TODO: Make it typed
         }
References map::delete_field().
Referenced by apply_construction_marker(), and zone_data::refresh_display().
delete_field() [2/2]
void tinymap::delete_field (const tripoint_omt_ms & p, const field_type_id & field_to_remove) inline
Definition at line 2611 of file map.h.
{
             return map::delete_field( p.raw(), field_to_remove );
         }
References map::delete_field(), and coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
delete_signage()
void tinymap::delete_signage (const tripoint & p) inline
Definition at line 2638 of file map.h.
{
             map::delete_signage( p );    // TODO: Make it typed
         }
References map::delete_signage().
Referenced by talk_function::loot_building().
destroy()
void tinymap::destroy (const tripoint & p, bool silent = false) inline
Definition at line 2620 of file map.h.
{
             return map::destroy( p, silent );    // TODO: Make it typed
         }
References map::destroy(), and silent.
draw_line_furn()
void tinymap::draw_line_furn (const furn_id & type, const point & p1, const point & p2, bool avoid_creatures = false) inline
Definition at line 2518 of file map.h.
{
             map::draw_line_furn( type, p1, p2, avoid_creatures );
         }
References avoid_creatures, map::draw_line_furn(), and type.
Referenced by line_furn().
draw_line_ter()
void tinymap::draw_line_ter (const ter_id & type, const point & p1, const point & p2, bool avoid_creature = false) inline
Definition at line 2487 of file map.h.
{
             map::draw_line_ter( type, p1, p2, avoid_creature );
         }
References map::draw_line_ter(), and type.
Referenced by line().
draw_square_furn()
void tinymap::draw_square_furn (const furn_id & type, const point & p1, const point & p2, bool avoid_creatures = false) inline
Definition at line 2522 of file map.h.
{
             map::draw_square_furn( type, p1, p2, avoid_creatures );
         }
References avoid_creatures, map::draw_square_furn(), and type.
Referenced by square_furn().
furn() [1/3]
furn_id tinymap::furn (const point & p) const inline
Definition at line 2495 of file map.h.
{
             return map::furn( p );    // TODO: Make it typed
         }
References map::furn().
Referenced by board_up(), editmap::draw_main_ui_overlay(), farm_action(), talk_function::field_harvest(), find_potential_computer_point(), get_changed_ids_from_update(), talk_function::loot_building(), MapExtras::mx_city_trap(), Character::place_corpse(), and basecamp::scan_pseudo_items().
furn() [2/3]
furn_id tinymap::furn (const tripoint & p) const inline
Definition at line 2498 of file map.h.
{
             return map::furn( p );    // TODO: Make it typed
         }
References map::furn().
furn() [3/3]
furn_id tinymap::furn (const tripoint_omt_ms & p) const inline
Definition at line 2501 of file map.h.
{
             return map::furn( p.raw() );
         }
References map::furn(), and coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
furn_set() [1/2]
bool tinymap::furn_set (const point & p, const furn_id & new_furniture, bool avoid_creatures = false) inline
Definition at line 2510 of file map.h.
                                                       { // TODO: Make it typed
             return furn_set( tripoint( p, abs_sub.z() ), new_furniture, false, avoid_creatures );
         }
References map::abs_sub, avoid_creatures, tripoint, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by board_up(), farm_action(), talk_function::field_harvest(), talk_function::loot_building(), MapExtras::mx_minefield(), and mission_start::place_npc_software().
furn_set() [2/2]
bool tinymap::furn_set (const tripoint & p, const furn_id & new_furniture, bool furn_reset = false, bool avoid_creatures = false) inline
Definition at line 2514 of file map.h.
{
             return map::furn_set( p, new_furniture, furn_reset, avoid_creatures ); // TODO: Make it typed
         }
References avoid_creatures, and map::furn_set().
generate()
void map::generate
Definition at line 1789 of file mapgen.cpp.
 {
     dbg( D_INFO ) << "map::generate( g[" << g.get() << "], p[" << p << "], "
                   "when[" << to_string( when ) << "] )";
     const tripoint_abs_sm p_sm = project_to<coords::sm>( p );
     set_abs_sub( p_sm );
     // First we have to create new submaps and initialize them to 0 all over
     // We create all the submaps, even if we're not a tinymap, so that map
     //  generation which overflows won't cause a crash.  At the bottom of this
     //  function, we save the upper-left 4 submaps, and delete the rest.
     // Mapgen is not z-level aware yet. Only actually initialize current z-level
     //  because other submaps won't be touched.
     for( int gridx = 0; gridx < my_MAPSIZE; gridx++ ) {
         for( int gridy = 0; gridy < my_MAPSIZE; gridy++ ) {
             const size_t grid_pos = get_nonant( { gridx, gridy, p_sm.z()} );
             if( getsubmap( grid_pos ) ) {
                 debugmsg( "Submap already exists at (%d, %d, %d)", gridx, gridy, p_sm.z() );
                 continue;
             }
             setsubmap( grid_pos, new submap() );
             // TODO: memory leak if the code below throws before the submaps get stored/deleted!
         }
     }
     oter_id terrain_type = overmap_buffer.ter( p );
     // This attempts to scale density of zombies inversely with distance from the nearest city.
     // In other words, make city centers dense and perimeters sparse.
     float density = 0.0f;
     for( int i = -MON_RADIUS; i <= MON_RADIUS; i++ ) {
         for( int j = -MON_RADIUS; j <= MON_RADIUS; j++ ) {
             density += overmap_buffer.ter( p + point( i, j ) )->get_mondensity();
         }
     }
     density = density / 100;
     mapgendata dat( p, *this, density, when, nullptr );
     draw_map( dat );
     // At some point, we should add region information so we can grab the appropriate extras
     map_extras &this_ex = region_settings_map["default"].region_extras[terrain_type->get_extras()];
     map_extras ex = this_ex.filtered_by( dat );
     if( this_ex.chance > 0 && ex.values.empty() && !this_ex.values.empty() ) {
         DebugLog( D_WARNING, D_MAP_GEN ) << "Overmap terrain " << terrain_type->get_type_id().str() <<
                                          " (extra type \"" << terrain_type->get_extras() <<
                                          "\") zlevel = " << p.z() <<
                                          " is out of range of all assigned map extras.  Skipping map extra generation.";
     } else if( ex.chance > 0 && one_in( ex.chance ) ) {
         map_extra_id *extra = ex.values.pick();
         if( extra == nullptr ) {
             debugmsg( "failed to pick extra for type %s (ter = %s)", terrain_type->get_extras(),
                       terrain_type->get_type_id().str() );
         } else {
             MapExtras::apply_function( *ex.values.pick(), *this, tripoint_abs_sm( abs_sub ) );
         }
     }
     const overmap_static_spawns &spawns = terrain_type->get_static_spawns();
     float spawn_density = 1.0f;
     if( MonsterGroupManager::is_animal( spawns.group ) ) {
         spawn_density = get_option< float >( "SPAWN_ANIMAL_DENSITY" );
     } else {
         spawn_density = get_option< float >( "SPAWN_DENSITY" );
     }
     // Apply a multiplier to the number of monsters for really high densities.
     float odds_after_density = spawns.chance * spawn_density;
     const float max_odds = 100 - ( 100 - spawns.chance ) / 2.0f;
     float density_multiplier = 1.0f;
     if( odds_after_density > max_odds ) {
         density_multiplier = 1.0f * odds_after_density / max_odds;
         odds_after_density = max_odds;
     }
     const int spawn_count = roll_remainder( density_multiplier );
     if( spawns.group && x_in_y( odds_after_density, 100 ) ) {
         int pop = spawn_count * rng( spawns.population.min, spawns.population.max );
         for( ; pop > 0; pop-- ) {
             std::vector<MonsterGroupResult> spawn_details =
                 MonsterGroupManager::GetResultFromGroup( spawns.group, &pop );
             for( const MonsterGroupResult &mgr : spawn_details ) {
                 if( !mgr.name ) {
                     continue;
                 }
                 if( const std::optional<tripoint> pt =
                 random_point( *this, [this]( const tripoint & n ) {
                 return passable( n );
                 } ) ) {
                     const tripoint_bub_ms pnt = tripoint_bub_ms( pt.value() );
                     add_spawn( mgr, pnt );
                 }
             }
         }
     }
     // Okay, we know who our neighbors are.  Let's draw!
     // And finally save used submaps and delete the rest.
     for( int i = 0; i < my_MAPSIZE; i++ ) {
         for( int j = 0; j < my_MAPSIZE; j++ ) {
             dbg( D_INFO ) << "map::generate: submap (" << i << "," << j << ")";
             const tripoint pos( i, j, p_sm.z() );
             if( i <= 1 && j <= 1 ) {
                 saven( pos );
             } else {
                 const size_t grid_pos = get_nonant( pos );
                 delete getsubmap( grid_pos );
                 setsubmap( grid_pos, nullptr );
             }
         }
     }
 }
Referenced by map::loadn(), and editmap::mapgen_preview().
get_abs_sub()
tripoint_abs_sm tinymap::get_abs_sub () const inline
Definition at line 2666 of file map.h.
{
             return map::get_abs_sub();    // TODO: Convert to tripoint_abs_omt
         }
References map::get_abs_sub().
Referenced by start_location::burn(), find_potential_computer_point(), mtrap_set(), MapExtras::place_trap_if_clear(), and start_location::prepare_map().
get_my_MAPSIZE()
int tinymap::get_my_MAPSIZE () inline protected
Definition at line 2688 of file map.h.
{
             return my_MAPSIZE;
         }
References map::my_MAPSIZE.
Referenced by fake_map::fake_map().
get_nonant() [1/2]
size_t map::get_nonant inline protected
Definition at line 2163 of file map.h.
{
             return get_nonant( { gridp, abs_sub.z() } );
         }
get_nonant() [2/2]
size_t map::get_nonant protected
Get the index of a submap pointer in the grid given by grid coordinates.
The grid coordinates must be valid: 0 <= x < my_MAPSIZE, same for y. Version with z-levels checks for z between -OVERMAP_DEPTH and OVERMAP_HEIGHT
Definition at line 2162 of file map.cpp.
 {
     if( gridp.x < 0 || gridp.x >= my_MAPSIZE ||
         gridp.y < 0 || gridp.y >= my_MAPSIZE ||
         gridp.z < -OVERMAP_DEPTH || gridp.z > OVERMAP_HEIGHT ) {
         debugmsg( "Tried to access invalid map position at grid (%d,%d,%d)", gridp.x, gridp.y, gridp.z );
         return 0;
     }
     if( zlevels ) {
         const int indexz = gridp.z + OVERMAP_HEIGHT; // Can't be lower than 0
         return indexz + ( gridp.x + gridp.y * my_MAPSIZE ) * OVERMAP_LAYERS;
     } else {
         return gridp.x + gridp.y * my_MAPSIZE;
     }
 }
References harvest.
Referenced by fake_map::fake_map().
get_vehicles()
VehicleList tinymap::get_vehicles () inline
Definition at line 2641 of file map.h.
{
             return map::get_vehicles();
         }
References map::get_vehicles().
getabs()
tripoint tinymap::getabs (const tripoint & p) const inline
Definition at line 2669 of file map.h.
{
             return map::getabs( p );    // TODO: Make it typed
         }
References map::getabs().
Referenced by find_valid_teleporters_omt(), mtrap_set(), and game::place_vehicle_nearby().
getlocal() [1/2]
tripoint tinymap::getlocal (const tripoint & p) const inline
Definition at line 2663 of file map.h.
{
             return map::getlocal( p );    // TODO: Make it typed
         }
References map::getlocal().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::map_add_item(), and teleporter_list::place_avatar_overmap().
getlocal() [2/2]
tripoint tinymap::getlocal (const tripoint_abs_ms & p) const inline
Definition at line 2672 of file map.h.
{
             return map::getlocal( p );
         }; // TODO: Make it typed (return type)
References map::getlocal().
has_flag() [1/2]
bool tinymap::has_flag (ter_furn_flag flag, const point & p) const inline
Definition at line 2617 of file map.h.
                                                                   { // TODO: Make it typed
             return map::has_flag( flag, p );
         }
References map::has_flag().
has_flag() [2/2]
bool tinymap::has_flag (ter_furn_flag flag, const tripoint & p) const inline
Definition at line 2614 of file map.h.
{
             return map::has_flag( flag, p );    // TODO: Make it typed
         }
References map::has_flag().
Referenced by start_location::burn(), and MapExtras::mx_minefield().
has_flag_furn()
bool tinymap::has_flag_furn (ter_furn_flag flag, const tripoint & p) const inline
Definition at line 2526 of file map.h.
{
             return map::has_flag_furn( flag, p );    // TODO: Make it typed
         }
References map::has_flag_furn().
Referenced by find_valid_teleporters_omt().
has_flag_ter() [1/2]
bool tinymap::has_flag_ter (ter_furn_flag flag, const tripoint & p) const inline
Definition at line 2480 of file map.h.
                                                      { // TODO: remove when usages converted
             return map::has_flag_ter( flag, p );
         }
References map::has_flag_ter().
Referenced by start_location::burn(), and find_potential_computer_point().
has_flag_ter() [2/2]
bool tinymap::has_flag_ter (ter_furn_flag flag, const tripoint_omt_ms & p) const inline
Definition at line 2484 of file map.h.
{
             return map::has_flag_ter( flag, p.raw() );
         }
References map::has_flag_ter(), and coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
has_furn()
bool tinymap::has_furn (const tripoint & p) const inline
Definition at line 2504 of file map.h.
{
             return map::has_furn( p );    // TODO: Make it typed
         }
References map::has_furn().
Referenced by add_boardable(), apply_construction_marker(), board_up(), get_changed_ids_from_update(), and talk_function::loot_building().
i_at()
map_stack tinymap::i_at (const tripoint & p) inline
Definition at line 2549 of file map.h.
{
             return map::i_at( p );    // TODO: Make it typed
         }
References map::i_at().
Referenced by inventory_selector::add_remote_map_items(), board_up(), farm_action(), talk_function::field_harvest(), talk_function::loot_building(), and om_harvest_itm().
i_clear()
void tinymap::i_clear (const tripoint & p) inline
Definition at line 2597 of file map.h.
{
             return map::i_clear( p );    //TODO: Make it typed
         }
References map::i_clear().
Referenced by board_up(), farm_action(), talk_function::field_harvest(), om_harvest_itm(), and mission_start::place_npc_software().
i_rem()
void tinymap::i_rem (const tripoint & p, item * it) inline
Definition at line 2594 of file map.h.
{
             map::i_rem( p, it );    // TODO: Make it typed
         }
References map::i_rem().
Referenced by om_set_hide_site().
impassable()
bool tinymap::impassable (const tripoint & p) const inline
Definition at line 2535 of file map.h.
{
             return map::impassable( p );    // TODO: Make it typed
         }
References map::impassable().
inbounds() [1/2]
bool tinymap::inbounds (const tripoint & p) const inline
Definition at line 2435 of file map.h.
{
             return map::inbounds( p );
         }
References map::inbounds().
inbounds() [2/2]
bool tinymap::inbounds (const tripoint_omt_ms & p) const inline
Definition at line 2438 of file map.h.
{
             return map::inbounds( p.raw() );
         }
References map::inbounds(), and coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
is_last_ter_wall()
bool tinymap::is_last_ter_wall (bool no_furn, const point & p, const point & max, direction dir) const inline
Definition at line 2491 of file map.h.
{
             return map::is_last_ter_wall( no_furn, p, max, dir );
         }
References map::is_last_ter_wall(), and max().
Referenced by find_potential_computer_point().
is_main_cleanup_queued()
bool map::is_main_cleanup_queued
Definition at line 2333 of file map.cpp.
 {
     return _main_requires_cleanup;
 }
Referenced by map::loadn().
is_outside()
bool tinymap::is_outside (const tripoint & p) const inline
Definition at line 2675 of file map.h.
{
             return map::is_outside( p );    // TODO: Make it typed
         }
References map::is_outside().
Referenced by add_boardable(), board_up(), and start_location::burn().
load()
void tinymap::load (const tripoint_abs_omt & w, bool update_vehicles, bool pump_events = false) inline
Definition at line 2447 of file map.h.
{
             map::load( project_to<coords::sm>( w ), update_vehicles, pump_events );
         };
References map::load().
Referenced by timed_event::actualize(), start_location::add_map_extra(), add_monsters(), apply_construction_marker(), start_location::burn(), create_lab_consoles(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), farm_action(), talk_function::field_harvest(), talk_function::field_plant(), find_valid_teleporters_omt(), talk_function::loot_building(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::map_add_item(), debug_menu::map_extra(), editmap::mapgen_veh_destroy(), editmap::mapgen_veh_query(), MapExtras::mx_city_trap(), MapExtras::mx_minefield(), explosion_handler::nuke(), om_cutdown_trees(), om_harvest_itm(), om_harvest_ter(), om_set_hide_site(), teleporter_list::place_avatar_overmap(), Character::place_corpse(), mission_start::place_deposit_box(), mission_start::place_npc_software(), game::place_vehicle_nearby(), start_location::prepare_map(), zone_data::refresh_display(), basecamp::scan_pseudo_items(), basecamp::start_relay_hide_site(), basecamp::survey_field_return(), and update_mapgen_function_json::update_map().
main_cleanup_override()
void map::main_cleanup_override
Definition at line 2334 of file map.cpp.
 {
     _main_cleanup_override = over;
 }
Referenced by map::loadn().
mirror()
void map::mirror
Mirrors this map, and all of its contents along with all its contents in the directions specified.
Definition at line 1933 of file mapgen.cpp.
 {
     if( !mirror_horizontal && !mirror_vertical ) {
         return;
     }
     real_coords rc;
     const tripoint_abs_sm &abs_sub = get_abs_sub();
     // TODO: fix point types
     rc.fromabs( project_to<coords::ms>( abs_sub.xy() ).raw() );
     for( int z_level = zlevels ? -OVERMAP_DEPTH : abs_sub.z();
          z_level <= ( zlevels ? OVERMAP_HEIGHT : abs_sub.z() ); z_level++ ) {
         submap *pz = get_submap_at_grid( tripoint( point_zero, z_level ) );
         submap *pse = get_submap_at_grid( tripoint( point_south_east, z_level ) );
         submap *pe = get_submap_at_grid( tripoint( point_east, z_level ) );
         submap *ps = get_submap_at_grid( tripoint( point_south, z_level ) );
         if( pz == nullptr || pse == nullptr || pe == nullptr || ps == nullptr ) {
             debugmsg( "Tried to mirror map at (%d, %d, %d) but the submap is not loaded", point_zero.x,
                       point_zero.y, z_level );
             return;
         }
         // Move the submaps around. Note that the order doesn't matter as the outcome is the same.
         if( mirror_horizontal ) {
             std::swap( *pz, *pe );
             std::swap( *ps, *pse );
         }
         if( mirror_vertical ) {
             std::swap( *pz, *ps );
             std::swap( *pe, *pse );
         }
         // Then mirror them.
         for( int j = 0; j < 2; ++j ) {
             for( int i = 0; i < 2; ++i ) {
                 point p( i, j );
                 submap *sm = get_submap_at_grid( tripoint( p, z_level ) );
                 if( sm == nullptr ) {
                     debugmsg( "Tried to mirror map at (%d, %d, %d) but the submap is not loaded", p.x, p.y, z_level );
                     continue;
                 }
                 if( mirror_horizontal ) {
                     sm->mirror( true );
                 }
                 if( mirror_vertical ) {
                     sm->mirror( false );
                 }
             }
         }
     }
 }
Referenced by apply_construction_marker(), and update_mapgen_function_json::update_map().
name()
std::string tinymap::name (const tripoint & p) inline
Definition at line 2532 of file map.h.
{
             return map::name( p );    // TODO: Make it typed
         }
References map::name().
Referenced by add_computer(), inventory_selector::add_remote_map_items(), add_spawn(), and place_spawns().
place_items()
std::vector<item *> tinymap::place_items (const item_group_id & group_id, int chance, const tripoint & p1, const tripoint & p2, bool ongrass, const time_point & turn, int magazine = 0, int ammo = 0, const std::string & faction = "") inline
Definition at line 2585 of file map.h.
{
             return map::place_items( group_id, chance, p1, p2, ongrass, turn, magazine, ammo, faction );
         }
References map::place_items(), and calendar::turn.
Referenced by MapExtras::mx_minefield().
place_spawns()
void tinymap::place_spawns (const mongroup_id & group, int chance, const point_omt_ms & p1, const point_omt_ms & p2, const int z_level, float density, bool individual = false, bool friendly = false, const std::optional< std::string > & name = std::nullopt, int mission_id = -1) inline
Definition at line 2455 of file map.h.
{
             map::place_spawns( group, chance, rebase_bub( p1 ), rebase_bub( p2 ), z_level, density, individual,
                                friendly,
                                name, mission_id );
         }
References friendly, name(), map::place_spawns(), and rebase_bub().
Referenced by add_monsters(), and MapExtras::mx_city_trap().
points_in_radius() [1/2]
tripoint_range< tripoint > tinymap::points_in_radius (const tripoint & center, size_t radius, size_t radiusz = 0) const
Definition at line 9114 of file map.cpp.
 {
     return map::points_in_radius( center, radius, radiusz );
 }
References center, and map::points_in_radius().
Referenced by find_potential_computer_point(), MapExtras::mx_minefield(), and mission_start::place_deposit_box().
points_in_radius() [2/2]
tripoint_range< tripoint_omt_ms > tinymap::points_in_radius (const tripoint_omt_ms & center, size_t radius, size_t radiusz = 0) const
Definition at line 9120 of file map.cpp.
 {
     const tripoint_range<tripoint> preliminary_result = map::points_in_radius( center.raw(), radius,
             radiusz );
     return tripoint_range<tripoint_omt_ms>( tripoint_omt_ms( preliminary_result.min() ),
                                             tripoint_omt_ms( preliminary_result.max() ) );
 }
References center, tripoint_range< Tripoint >::max(), tripoint_range< Tripoint >::min(), and map::points_in_radius().
points_in_rectangle() [1/2]
tripoint_range< tripoint > tinymap::points_in_rectangle (const tripoint & from, const tripoint & to) const
Definition at line 9099 of file map.cpp.
 {
     return map::points_in_rectangle( from, to );
 }
References map::points_in_rectangle().
Referenced by farm_action(), om_cutdown_trees(), om_harvest_itm(), om_harvest_ter(), zone_data::refresh_display(), basecamp::scan_pseudo_items(), and basecamp::survey_field_return().
points_in_rectangle() [2/2]
tripoint_range< tripoint_omt_ms > tinymap::points_in_rectangle (const tripoint_omt_ms & from, const tripoint_omt_ms & to) const
Definition at line 9105 of file map.cpp.
 {
     const tripoint_range<tripoint> preliminary_result = map::points_in_rectangle( from.raw(),
             to.raw() );
     return tripoint_range<tripoint_omt_ms>( tripoint_omt_ms( preliminary_result.min() ),
                                             tripoint_omt_ms( preliminary_result.max() ) );
 }
References tripoint_range< Tripoint >::max(), tripoint_range< Tripoint >::min(), map::points_in_rectangle(), and coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
points_on_zlevel() [1/2]
tripoint_range< tripoint > tinymap::points_on_zlevel () const
Definition at line 9089 of file map.cpp.
 {
     return map::points_on_zlevel();
 }
References map::points_on_zlevel().
Referenced by apply_construction_marker(), start_location::burn(), editmap::draw_main_ui_overlay(), talk_function::field_harvest(), talk_function::field_plant(), find_potential_computer_point(), find_valid_teleporters_omt(), get_changed_ids_from_update(), talk_function::loot_building(), Character::place_corpse(), mission_start::place_deposit_box(), and start_location::prepare_map().
points_on_zlevel() [2/2]
tripoint_range< tripoint > tinymap::points_on_zlevel (int z) const
Definition at line 9094 of file map.cpp.
 {
     return map::points_on_zlevel( z );
 }
References map::points_on_zlevel().
put_items_from_loc()
std::vector<item *> tinymap::put_items_from_loc (const item_group_id & group_id, const tripoint & p, const time_point & turn = calendar::start_of_cataclysm) inline
Definition at line 2577 of file map.h.
{
             return map::put_items_from_loc( group_id, p, turn ); // TODO: Make it typed
         }
References map::put_items_from_loc(), and calendar::turn.
Referenced by MapExtras::mx_minefield().
rotate()
void map::rotate
Rotates this map, and all of its contents, by the specified multiple of 90 degrees.
Parameters
turns How many 90-degree turns to rotate the map.
Definition at line 1920 of file mapgen.cpp.
 {
     //Handle anything outside the 1-3 range gracefully; rotate(0) is a no-op.
     turns = turns % 4;
     if( turns == 0 ) {
         return;
     }
     real_coords rc;
     const tripoint_abs_sm &abs_sub = get_abs_sub();
     // TODO: fix point types
     rc.fromabs( project_to<coords::ms>( abs_sub.xy() ).raw() );
     // TODO: This radius can be smaller - how small?
     const int radius = HALF_MAPSIZE + 3;
     // uses submap coordinates
     const std::vector<shared_ptr_fast<npc>> npcs = overmap_buffer.get_npcs_near( abs_sub, radius );
     for( const shared_ptr_fast<npc> &i : npcs ) {
         npc &np = *i;
         const tripoint sq = np.get_location().raw();
         real_coords np_rc;
         np_rc.fromabs( sq.xy() );
         // Note: We are rotating the entire overmap square (2x2 of submaps)
         if( np_rc.om_pos != rc.om_pos || ( sq.z != abs_sub.z() && !zlevels ) ) {
             continue;
         }
         // OK, this is ugly: we remove the NPC from the whole map
         // Then we place it back from scratch
         // It could be rewritten to utilize the fact that rotation shouldn't cross overmaps
         point old( np_rc.sub_pos );
         if( np_rc.om_sub.x % 2 != 0 ) {
             old.x += SEEX;
         }
         if( np_rc.om_sub.y % 2 != 0 ) {
             old.y += SEEY;
         }
         const point new_pos = old.rotate( turns, { SEEX * 2, SEEY * 2 } );
         if( setpos_safe ) {
             const point local_sq = getlocal( sq ).xy();
             // setpos can't be used during mapgen, but spawn_at_precise clips position
             // to be between 0-11,0-11 and teleports NPCs when used inside of update_mapgen
             // calls
             const tripoint new_global_sq = sq - local_sq + new_pos;
             np.setpos( get_map().getlocal( new_global_sq ) );
         } else {
             // OK, this is ugly: we remove the NPC from the whole map
             // Then we place it back from scratch
             // It could be rewritten to utilize the fact that rotation shouldn't cross overmaps
             shared_ptr_fast<npc> npc_ptr = overmap_buffer.remove_npc( np.getID() );
             np.spawn_at_precise( tripoint_abs_ms( getabs( tripoint( new_pos, abs_sub.z() ) ) ) );
             overmap_buffer.insert_npc( npc_ptr );
         }
     }
     clear_vehicle_level_caches();
     // rotate zones
     zone_manager &mgr = zone_manager::get_manager();
     mgr.rotate_zones( *this, turns );
     const int bottom_level = zlevels ? -OVERMAP_DEPTH : abs_sub.z();
     const int top_level = zlevels ? OVERMAP_HEIGHT : abs_sub.z();
     for( int z_level = bottom_level; z_level <= top_level; z_level++ ) {
         clear_vehicle_list( z_level );
         submap *pz = get_submap_at_grid( tripoint( point_zero, z_level ) );
         submap *pse = get_submap_at_grid( tripoint( point_south_east, z_level ) );
         submap *pe = get_submap_at_grid( tripoint( point_east, z_level ) );
         submap *ps = get_submap_at_grid( tripoint( point_south, z_level ) );
         if( pz == nullptr || pse == nullptr || pe == nullptr || ps == nullptr ) {
             debugmsg( "Tried to rotate map at (%d,%d) but the submap is not loaded", point_zero.x,
                       point_zero.y );
             return;
         }
         // Move the submaps around.
         if( turns == 2 ) {
             std::swap( *pz, *pse );
             std::swap( *pe, *ps );
         } else {
             point p;
             submap tmp;
             std::swap( *pse, tmp );
             for( int k = 0; k < 4; ++k ) {
                 p = p.rotate( turns, { 2, 2 } );
                 point tmpp = point_south_east - p;
                 submap *psep = get_submap_at_grid( tripoint( tmpp, z_level ) );
                 if( psep == nullptr ) {
                     debugmsg( "Tried to rotate map at (%d,%d) but the submap is not loaded", tmpp.x, tmpp.y );
                     continue;
                 }
                 std::swap( *psep, tmp );
             }
         }
         // Then rotate them and recalculate vehicle positions.
         for( int j = 0; j < 2; ++j ) {
             for( int i = 0; i < 2; ++i ) {
                 point p( i, j );
                 submap *sm = get_submap_at_grid( tripoint( p, z_level ) );
                 if( sm == nullptr ) {
                     debugmsg( "Tried to rotate map at (%d,%d) but the submap is not loaded", p.x, p.y );
                     continue;
                 }
                 sm->rotate( turns );
                 for( auto &veh : sm->vehicles ) {
                     veh->sm_pos = tripoint( p, z_level );
                 }
                 update_vehicle_list( sm, z_level );
             }
         }
         rebuild_vehicle_level_caches();
         std::unordered_map<std::string, tripoint_abs_ms> temp_points = queued_points;
         queued_points.clear();
         for( std::pair<const std::string, tripoint_abs_ms> &queued_point : temp_points ) {
             //This is all just a copy of the section rotating NPCs above
             real_coords np_rc;
             np_rc.fromabs( queued_point.second.xy().raw() );
             // Note: We are rotating the entire overmap square (2x2 of submaps)
             if( np_rc.om_pos != rc.om_pos || ( queued_point.second.z() != abs_sub.z() && !zlevels ) ) {
                 continue;
             }
             point old( np_rc.sub_pos );
             if( np_rc.om_sub.x % 2 != 0 ) {
                 old.x += SEEX;
             }
             if( np_rc.om_sub.y % 2 != 0 ) {
                 old.y += SEEY;
             }
             const point new_pos = old.rotate( turns, { SEEX * 2, SEEY * 2 } );
             queued_points[queued_point.first] = tripoint_abs_ms( getabs( tripoint( new_pos,
                                                 z_level ) ) );
         }
     }
 }
Referenced by apply_construction_marker(), editmap::mapgen_preview(), and update_mapgen_function_json::update_map().
save()
void map::save
Add currently loaded submaps (in grid) to the mapbuffer.
They will than be stored by that class and can be loaded from that class. This can be called several times, the mapbuffer takes care of adding the same submap several times. It should only be called after the map has been loaded. Submaps that have been loaded from the mapbuffer (and not generated) are already stored in the mapbuffer. TODO: determine if this is really needed? Submaps are already in the mapbuffer if they have been loaded from disc and the are added by map::generate, too. So when do they not appear in the mapbuffer?
Definition at line 485 of file map.cpp.
 {
     for( int gridx = 0; gridx < my_MAPSIZE; gridx++ ) {
         for( int gridy = 0; gridy < my_MAPSIZE; gridy++ ) {
             if( zlevels ) {
                 for( int gridz = -OVERMAP_DEPTH; gridz <= OVERMAP_HEIGHT; gridz++ ) {
                     saven( tripoint( gridx, gridy, gridz ) );
                 }
             } else {
                 saven( tripoint( gridx, gridy, abs_sub.z() ) );
             }
         }
     }
 }
Referenced by start_location::add_map_extra(), add_monsters(), start_location::burn(), create_lab_consoles(), farm_action(), talk_function::field_harvest(), talk_function::field_plant(), talk_function::loot_building(), explosion_handler::nuke(), om_cutdown_trees(), om_harvest_itm(), om_harvest_ter(), om_set_hide_site(), mission_start::place_deposit_box(), mission_start::place_npc_software(), game::place_vehicle_nearby(), and start_location::prepare_map().
set()
void tinymap::set (const tripoint & p, const ter_id & new_terrain, const furn_id & new_furniture) inline
Definition at line 2507 of file map.h.
{
             map::set( p, new_terrain, new_furniture );    // TODO: Make it typed
         }
References map::set().
Referenced by farm_action(), and talk_function::field_plant().
set_abs_sub()
void map::set_abs_sub protected
Sets abs_sub, see there.
Uses the same coordinate system as abs_sub.
Definition at line 2063 of file map.cpp.
 {
     abs_sub = p;
 }
Referenced by fake_map::fake_map().
set_signage()
void tinymap::set_signage (const tripoint & p, const std::string & message) inline
Definition at line 2635 of file map.h.
{
             map::set_signage( p, message );    // TODO: Make it typed
         }
References mapgen_defer::message, and map::set_signage().
Referenced by MapExtras::mx_minefield().
setsubmap()
void map::setsubmap protected
Set the submap pointer in grid at the give index.
This is the inverse of getsubmap, any existing pointer is overwritten. The index must be valid. The given submap pointer must not be null.
Definition at line 2171 of file map.cpp.
 {
     if( grididx >= grid.size() ) {
         debugmsg( "Tried to access invalid grid index %d", grididx );
         return;
     } else if( smap == nullptr ) {
         debugmsg( "Tried to set NULL submap pointer at index %d", grididx );
         return;
     }
     grid[grididx] = smap;
 }
Referenced by fake_map::fake_map().
spawn_item() [1/2]
void tinymap::spawn_item (const tripoint & p, const itype_id & type_id, unsigned quantity = 1, int charges = 0, const time_point & birthday = calendar::start_of_cataclysm, int damlevel = 0, const std::set< flag_id > & flags = {}, const std::string & variant = "", const std::string & faction = "") inline
Definition at line 2552 of file map.h.
                                                         {}, const std::string &variant = "",
                          const std::string &faction = "" ) {
             map::spawn_item( p, type_id, quantity, charges, birthday, damlevel, flags, variant,
                              faction ); // TODO: Make it typed
         }
Referenced by MapExtras::mx_minefield(), om_cutdown_trees(), and mission_start::place_deposit_box().
spawn_item() [2/2]
void tinymap::spawn_item (const tripoint & p, const std::string & type_id, unsigned quantity = 1, int charges = 0, const time_point & birthday = calendar::start_of_cataclysm, int damlevel = 0, const std::set< flag_id > & flags = {}, const std::string & variant = "", const std::string & faction = "") inline
Definition at line 2560 of file map.h.
                                                         {}, const std::string &variant = "",
                          const std::string &faction = "" ) {
             map::spawn_item( p, type_id, quantity, charges, birthday, damlevel, flags, variant, faction );
         }
spawn_items()
std::vector<item *> tinymap::spawn_items (const tripoint & p, const std::vector< item > & new_items) inline
Definition at line 2567 of file map.h.
{
             return map::spawn_items( p, new_items );    // TODO: Make it typed
         }
References map::spawn_items().
Referenced by talk_function::loot_building().
ter() [1/2]
ter_id tinymap::ter (const tripoint & p) const inline
Definition at line 2471 of file map.h.
{
             return map::ter( p );    // TODO: Make it typed
         }
References map::ter().
Referenced by add_boardable(), apply_construction_marker(), board_up(), editmap::draw_main_ui_overlay(), talk_function::field_plant(), find_potential_computer_point(), get_changed_ids_from_update(), talk_function::loot_building(), MapExtras::mx_city_trap(), om_cutdown_trees(), om_harvest_ter(), mission_start::place_deposit_box(), MapExtras::place_trap_if_clear(), and basecamp::survey_field_return().
ter() [2/2]
ter_id tinymap::ter (const tripoint_omt_ms & p) const inline
Definition at line 2474 of file map.h.
{
             return map::ter( p.raw() );
         }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and map::ter().
ter_set()
bool tinymap::ter_set (const tripoint & p, const ter_id & new_terrain, bool avoid_creatures = false) inline
Definition at line 2477 of file map.h.
{
             return map::ter_set( p, new_terrain, avoid_creatures );    // TODO: Make it typed
         }
References avoid_creatures, and map::ter_set().
Referenced by board_up(), farm_action(), talk_function::field_harvest(), talk_function::loot_building(), om_cutdown_trees(), om_harvest_ter(), and om_set_hide_site().
tr_at() [1/2]
const trap& tinymap::tr_at (const tripoint & p) const inline
Definition at line 2623 of file map.h.
{
             return map::tr_at( p );    // TODO: Make it typed
         }
References map::tr_at().
Referenced by editmap::draw_main_ui_overlay(), MapExtras::mx_city_trap(), and MapExtras::mx_minefield().
tr_at() [2/2]
const trap& tinymap::tr_at (const tripoint_omt_ms & p) const inline
Definition at line 2626 of file map.h.
{
             return map::tr_at( p.raw() );
         }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and map::tr_at().
translate()
void map::translate
Definition at line 1180 of file map.cpp.
 {
     if( from == to ) {
         debugmsg( "map::translate %s => %s",
                   from.obj().name(),
                   from.obj().name() );
         return;
     }
     for( const tripoint &p : points_on_zlevel() ) {
         if( ter( p ) == from ) {
             ter_set( p, to );
         }
     }
 }
Referenced by start_location::prepare_map().
trap_set() [1/2]
void tinymap::trap_set (const tripoint & p, const trap_id & type) inline
Definition at line 2629 of file map.h.
{
             map::trap_set( p, type );    // TODO: Make it typed
         }
References map::trap_set(), and type.
Referenced by mtrap_set(), and MapExtras::mx_city_trap().
trap_set() [2/2]
void tinymap::trap_set (const tripoint_omt_ms & p, const trap_id & type) inline
Definition at line 2632 of file map.h.
{
             map::trap_set( p.raw(), type );
         }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), map::trap_set(), and type.
veh_at() [1/2]
optional_vpart_position tinymap::veh_at (const tripoint & p) const inline
Definition at line 2644 of file map.h.
{
             return map::veh_at( p );    // TODO: Make it typed
         }
References map::veh_at().
Referenced by editmap::draw_main_ui_overlay(), MapExtras::mx_city_trap(), and basecamp::scan_pseudo_items().
veh_at() [2/2]
optional_vpart_position tinymap::veh_at (const tripoint_omt_ms & p) const inline
Definition at line 2647 of file map.h.
{
             return map::veh_at( p.raw() );
         }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and map::veh_at().
Friends And Related Function Documentation
editmap
friend class editmap friend
Definition at line 2424 of file map.h.
The documentation for this class was generated from the following files:
src/map.h
src/map.cpp