Cataclysm DDA: flexbuffer_disk_cache Class Reference
flexbuffer_disk_cache Class Reference
Classes
struct disk_cache_entry
Public Member Functions
bool has_cached_flexbuffer_for_json (const fs::path &json_source_path)
fs::file_time_type cached_mtime_for_json (const fs::path &json_source_path)
std::shared_ptr< flexbuffer_mmap_storage > load_flexbuffer_if_not_stale (const fs::path &lexically_normal_json_source_path)
bool save_to_disk (const fs::path &lexically_normal_json_source_path, const std::vector< uint8_t > &flexbuffer_binary)
Static Public Member Functions
static std::unique_ptr< flexbuffer_disk_cache > init_from_folder (const fs::path &cache_path, const fs::path &root_path)
Private Member Functions
flexbuffer_disk_cache (fs::path cache_path, fs::path root_path)
Private Attributes
fs::path cache_path_
fs::path root_path_
std::unordered_map< std::string, disk_cache_entry > cached_flexbuffers_
Detailed Description
Definition at line 231 of file flexbuffer_cache.cpp.
Constructor & Destructor Documentation
flexbuffer_disk_cache()
flexbuffer_disk_cache::flexbuffer_disk_cache (fs::path cache_path, fs::path root_path) inline explicit private
Definition at line 377 of file flexbuffer_cache.cpp.
                                                                               : cache_path_{ std::move( cache_path ) },
             root_path_{ std::move( root_path ) } {}
Referenced by init_from_folder().
Member Function Documentation
cached_mtime_for_json()
fs::file_time_type flexbuffer_disk_cache::cached_mtime_for_json (const fs::path & json_source_path) inline
Definition at line 292 of file flexbuffer_cache.cpp.
{
             auto it = cached_flexbuffers_.find( json_source_path.u8string() );
             if( it != cached_flexbuffers_.end() ) {
                 return it->second.mtime;
             }
             return {};
         }
References cached_flexbuffers_.
has_cached_flexbuffer_for_json()
bool flexbuffer_disk_cache::has_cached_flexbuffer_for_json (const fs::path & json_source_path) inline
Definition at line 288 of file flexbuffer_cache.cpp.
{
             return cached_flexbuffers_.count( json_source_path.u8string() ) > 0;
         }
References cached_flexbuffers_.
init_from_folder()
static std::unique_ptr<flexbuffer_disk_cache> flexbuffer_disk_cache::init_from_folder (const fs::path & cache_path, const fs::path & root_path) inline static
Definition at line 234 of file flexbuffer_cache.cpp.
{
             // Private constructor, make_unique doesn't have access.
             std::unique_ptr<flexbuffer_disk_cache> cache{ new flexbuffer_disk_cache( cache_path, root_path ) };
             std::string cache_path_string = cache_path.u8string();
             std::vector<std::string> all_cached_flexbuffers = get_files_from_path(
                         ".fb",
                         cache_path_string,
                         true,
                         true );
             for( const std::string &cached_flexbuffer : all_cached_flexbuffers ) {
                 // The file path format is <input file>.<mtime>.fb
                 // So find the second-to-last-dot
                 fs::path cached_flexbuffer_path = fs::u8path( cached_flexbuffer );
                 fs::path json_with_mtime = cached_flexbuffer_path.stem();
                 std::string mtime_str = json_with_mtime.extension().u8string();
                 fs::path original_json_file_name = json_with_mtime.stem();
                 if( mtime_str.empty() || original_json_file_name.empty() ) {
                     // Not a recognized flexbuffer filename.
                     remove_file( cached_flexbuffer );
                     continue;
                 }
                 // Explicit constructor from milliseconds to file_time_type.
                 fs::file_time_type cached_mtime = fs::file_time_type( std::chrono::milliseconds( std::strtoull(
                                                       // extension() returns a string with the leading .
                                                       mtime_str.c_str() + 1,
                                                       nullptr, 0 ) ) );
                 fs::path root_relative_json_path = cached_flexbuffer_path.parent_path().lexically_relative(
                                                        cache_path ) / original_json_file_name;
                 std::string root_relative_json_path_string = root_relative_json_path.u8string();
                 // Don't just blindly insert, we may end up in a situation with multiple flexbuffers for the same input json
                 auto old_entry = cache->cached_flexbuffers_.find( root_relative_json_path_string );
                 if( old_entry != cache->cached_flexbuffers_.end() ) {
                     if( old_entry->second.mtime < cached_mtime ) {
                         // Lets only keep the newest.
                         remove_file( old_entry->second.flexbuffer_path.u8string() );
                         old_entry->second = disk_cache_entry{ cached_flexbuffer_path, cached_mtime };
                     } else {
                         // The file we're iterating is older than the cached entry.
                         remove_file( cached_flexbuffer );
                     }
                 } else {
                     cache->cached_flexbuffers_.emplace( root_relative_json_path_string, disk_cache_entry{ cached_flexbuffer_path, cached_mtime } );
                 }
             }
             return cache;
         }
References flexbuffer_disk_cache(), get_files_from_path(), and remove_file().
Referenced by flexbuffer_cache::flexbuffer_cache().
load_flexbuffer_if_not_stale()
std::shared_ptr<flexbuffer_mmap_storage> flexbuffer_disk_cache::load_flexbuffer_if_not_stale (const fs::path & lexically_normal_json_source_path) inline
Definition at line 300 of file flexbuffer_cache.cpp.
{
             std::shared_ptr<flexbuffer_mmap_storage> storage;
             fs::path root_relative_source_path = lexically_normal_json_source_path.lexically_relative(
                     root_path_ ).lexically_normal();
             // Is there even a potential cached flexbuffer for this file.
             auto disk_entry = cached_flexbuffers_.find( root_relative_source_path.u8string() );
             if( disk_entry == cached_flexbuffers_.end() ) {
                 return storage;
             }
             std::error_code ec;
             fs::file_time_type source_mtime = get_file_mtime_millis( lexically_normal_json_source_path, ec );
             if( ec ) {
                 return storage;
             }
             // Does the source file's mtime match what we cached previously
             if( source_mtime != disk_entry->second.mtime ) {
                 // Cached flexbuffer on disk is out of date, remove it.
                 remove_file( disk_entry->second.flexbuffer_path.u8string() );
                 cached_flexbuffers_.erase( disk_entry );
                 return storage;
             }
             // Try to mmap the cached flexbuffer
             std::shared_ptr<mmap_file> mmap_handle = mmap_file::map_file(
                         disk_entry->second.flexbuffer_path.u8string() );
             if( !mmap_handle ) {
                 return storage;
             }
             storage = std::make_shared<flexbuffer_mmap_storage>( mmap_handle );
             return storage;
         }
References cached_flexbuffers_, anonymous_namespace{flexbuffer_cache.cpp}::get_file_mtime_millis(), mmap_file::map_file(), remove_file(), and root_path_.
save_to_disk()
bool flexbuffer_disk_cache::save_to_disk (const fs::path & lexically_normal_json_source_path, const std::vector< uint8_t > & flexbuffer_binary) inline
Definition at line 339 of file flexbuffer_cache.cpp.
{
             std::error_code ec;
             std::string json_source_path_string = lexically_normal_json_source_path.u8string();
             fs::file_time_type mtime = get_file_mtime_millis( lexically_normal_json_source_path, ec );
             if( ec ) {
                 return false;
             }
             int64_t mtime_ms = std::chrono::duration_cast<std::chrono::milliseconds>
                                ( mtime.time_since_epoch() ).count();
             // Doing some variable reuse to avoid copies.
             fs::path flexbuffer_path = ( cache_path_ / lexically_normal_json_source_path.lexically_relative(
                                              root_path_ ) ).remove_filename();
             assure_dir_exist( flexbuffer_path );
             fs::path flexbuffer_filename = lexically_normal_json_source_path.filename();
             flexbuffer_filename += fs::u8path( "." + std::to_string( mtime_ms ) + ".fb" );
             flexbuffer_path /= flexbuffer_filename;
             std::ofstream fb( flexbuffer_path, std::ofstream::binary );
             if( !fb.good() ) {
                 return false;
             }
             fb.write( reinterpret_cast<const char *>( flexbuffer_binary.data() ), flexbuffer_binary.size() );
             if( !fb.good() ) {
                 return false;
             }
             fb.close();
             cached_flexbuffers_[json_source_path_string] = disk_cache_entry{ flexbuffer_path, mtime };
             return true;
         }
References assure_dir_exist(), cache_path_, cached_flexbuffers_, anonymous_namespace{flexbuffer_cache.cpp}::get_file_mtime_millis(), root_path_, and to_string().
Member Data Documentation
cache_path_
fs::path flexbuffer_disk_cache::cache_path_ private
Definition at line 380 of file flexbuffer_cache.cpp.
Referenced by save_to_disk().
cached_flexbuffers_
std::unordered_map<std::string, disk_cache_entry> flexbuffer_disk_cache::cached_flexbuffers_ private
Definition at line 388 of file flexbuffer_cache.cpp.
Referenced by cached_mtime_for_json(), has_cached_flexbuffer_for_json(), load_flexbuffer_if_not_stale(), and save_to_disk().
root_path_
fs::path flexbuffer_disk_cache::root_path_ private
Definition at line 381 of file flexbuffer_cache.cpp.
Referenced by load_flexbuffer_if_not_stale(), and save_to_disk().
The documentation for this class was generated from the following file:
src/flexbuffer_cache.cpp