Cataclysm DDA: timed_event_manager Class Reference
timed_event_manager Class Reference
#include <timed_event.h>
Public Member Functions
void add (timed_event_type type, const time_point &when, int faction_id=-1, int strength=-1, const std::string &key="")
Add an entry to the event queue.
void add (timed_event_type type, const time_point &when, int faction_id, const tripoint_abs_ms &where, int strength=-1, const std::string &key="")
Add an entry to the event queue.
void add (timed_event_type type, const time_point &when, int faction_id, const tripoint_abs_ms &where, int strength, const std::string &string_id, const std::string &key="")
void add (timed_event_type type, const time_point &when, int faction_id, const tripoint_abs_ms &where, int strength, const std::string &string_id, submap sr, const std::string &key="")
bool queued (timed_event_type type) const
timed_event * get (timed_event_type type)
timed_event * get (timed_event_type type, const std::string &key)
std::list< timed_event > const & get_all () const
void set_all (const std::string &key, time_duration time_in_future)
void process ()
Process all queued events, potentially altering the game state and modifying the event queue.
Static Public Member Functions
static void serialize_all (JsonOut &jsout)
static void unserialize_all (const JsonArray &ja)
Private Attributes
std::list< timed_event > events
Detailed Description
Definition at line 65 of file timed_event.h.
Member Function Documentation
add() [1/4]
void timed_event_manager::add (timed_event_type type, const time_point & when, int faction_id, const tripoint_abs_ms & where, int strength, const std::string & string_id, const std::string & key = "")
Definition at line 402 of file timed_event.cpp.
 {
     events.emplace_back( type, when, faction_id, where, strength, string_id, key );
 }
References events, strength, and type.
add() [2/4]
void timed_event_manager::add (timed_event_type type, const time_point & when, int faction_id, const tripoint_abs_ms & where, int strength, const std::string & string_id, submap sr, const std::string & key = "")
Definition at line 411 of file timed_event.cpp.
 {
     events.emplace_back( type, when, faction_id, where, strength, string_id, std::move( sr ), key );
 }
References events, strength, and type.
add() [3/4]
void timed_event_manager::add (timed_event_type type, const time_point & when, int faction_id, const tripoint_abs_ms & where, int strength = -1, const std::string & key = "")
Add an entry to the event queue.
Parameters are basically passed through to timed_event::timed_event.
Definition at line 394 of file timed_event.cpp.
 {
     events.emplace_back( type, when, faction_id, where, strength, key );
 }
References events, strength, and type.
add() [4/4]
void timed_event_manager::add (timed_event_type type, const time_point & when, int faction_id = -1, int strength = -1, const std::string & key = "")
Add an entry to the event queue.
Parameters are basically passed through to timed_event::timed_event.
Definition at line 388 of file timed_event.cpp.
 {
     add( type, when, faction_id, get_player_character().get_location(), strength, "", key );
 }
References get_player_character(), strength, and type.
Referenced by computer_session::action_amigara_log(), computer_session::action_amigara_start(), timed_event::actualize(), mattack::dsa_drone_scan(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), computer_session::failure_amigara(), iexamine::fswitch(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), mattack::photograph(), trapfunc::temple_flood(), spell_effect::timed_event(), and unserialize_all().
get() [1/2]
timed_event * timed_event_manager::get (timed_event_type type)
Returns
One of the queued events of the given type, or nullptr if no event of that type is queued.
Definition at line 425 of file timed_event.cpp.
 {
     for( timed_event &e : events ) {
         if( e.type == type ) {
             return &e;
         }
     }
     return nullptr;
 }
References events, and type.
Referenced by game::natural_light_level(), and queued().
get() [2/2]
timed_event * timed_event_manager::get (timed_event_type type, const std::string & key)
Definition at line 435 of file timed_event.cpp.
 {
     for( timed_event &e : events ) {
         if( e.type == type && e.key == key ) {
             return &e;
         }
     }
     return nullptr;
 }
References events, and type.
get_all()
std::list< timed_event > const & timed_event_manager::get_all () const
Definition at line 445 of file timed_event.cpp.
 {
     return events;
 }
References events.
process()
void timed_event_manager::process ()
Process all queued events, potentially altering the game state and modifying the event queue.
Definition at line 375 of file timed_event.cpp.
 {
     for( auto it = events.begin(); it != events.end(); ) {
         it->per_turn();
         if( it->when <= calendar::turn ) {
             it->actualize();
             it = events.erase( it );
         } else {
             it++;
         }
     }
 }
References events, and calendar::turn.
queued()
bool timed_event_manager::queued (timed_event_type type) const
Returns
Whether at least one element of the given type is queued.
Definition at line 420 of file timed_event.cpp.
 {
     return const_cast<timed_event_manager &>( *this ).get( type ) != nullptr;
 }
References get(), and type.
Referenced by game::natural_light_level().
serialize_all()
void timed_event_manager::serialize_all (JsonOut & jsout) static
Definition at line 1609 of file savegame.cpp.
 {
     jsout.start_array();
     for( const timed_event &elem : get_timed_events().events ) {
         jsout.start_object();
         jsout.member( "faction", elem.faction_id );
         jsout.member( "map_point", elem.map_point );
         jsout.member( "map_square", elem.map_square );
         jsout.member( "strength", elem.strength );
         jsout.member( "string_id", elem.string_id );
         jsout.member( "type", elem.type );
         jsout.member( "when", elem.when );
         jsout.member( "key", elem.key );
         if( elem.revert.is_uniform() ) {
             jsout.member( "revert", elem.revert.get_ter( point_zero ) );
         } else {
             jsout.member( "revert" );
             jsout.start_array();
             for( int y = 0; y < SEEY; y++ ) {
                 for( int x = 0; x < SEEX; x++ ) {
                     jsout.start_object();
                     point pt( x, y );
                     jsout.member( "point", pt );
                     jsout.member( "furn", elem.revert.get_furn( pt ) );
                     jsout.member( "ter", elem.revert.get_ter( pt ) );
                     jsout.member( "trap", elem.revert.get_trap( pt ) );
                     jsout.member( "items", elem.revert.get_items( pt ) );
                     jsout.end_object();
                 }
             }
             jsout.end_array();
         }
         jsout.end_object();
     }
     jsout.end_array();
 }
References JsonOut::end_array(), JsonOut::end_object(), events, get_timed_events(), JsonOut::member(), point_zero, SEEX, SEEY, JsonOut::start_array(), and JsonOut::start_object().
Referenced by game::serialize_master().
set_all()
void timed_event_manager::set_all (const std::string & key, time_duration time_in_future)
Definition at line 450 of file timed_event.cpp.
 {
     for( timed_event &e : events ) {
         if( e.key == key ) {
             e.when = calendar::turn + time_in_future;
         }
     }
 }
References events, and calendar::turn.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_alter_timed_events().
unserialize_all()
void timed_event_manager::unserialize_all (const JsonArray & ja) static
Definition at line 1504 of file savegame.cpp.
 {
     for( JsonObject jo : ja ) {
         int type;
         time_point when;
         int faction_id;
         int strength;
         tripoint_abs_ms map_square;
         tripoint_abs_sm map_point;
         std::string string_id;
         std::string key;
         submap revert;
         jo.read( "faction", faction_id );
         jo.read( "map_point", map_point );
         jo.read( "map_square", map_square, false );
         jo.read( "strength", strength );
         jo.read( "string_id", string_id );
         jo.read( "type", type );
         jo.read( "when", when );
         jo.read( "key", key );
         point pt;
         if( jo.has_string( "revert" ) ) {
             revert.set_all_ter( ter_id( jo.get_string( "revert" ) ), true );
         } else {
             for( JsonObject jp : jo.get_array( "revert" ) ) {
                 if( jp.has_member( "point" ) ) {
                     jp.get_member( "point" ).read( pt, false );
                 }
                 revert.set_furn( pt, furn_id( jp.get_string( "furn" ) ) );
                 revert.set_ter( pt, ter_id( jp.get_string( "ter" ) ) );
                 revert.set_trap( pt, trap_id( jp.get_string( "trap" ) ) );
                 if( jp.has_member( "items" ) ) {
                     cata::colony<item> itm;
                     jp.get_member( "items" ).read( itm, false );
                     revert.get_items( pt ) = std::move( itm );
                 }
                 // We didn't always save the point, this is the original logic, it doesn't work right but for older saves at least they won't crash
                 if( !jp.has_member( "point" ) ) {
                     if( pt.x++ < SEEX ) {
                         pt.x = 0;
                         pt.y++;
                     }
                 }
             }
         }
         get_timed_events().add( static_cast<timed_event_type>( type ), when, faction_id, map_square,
                                 strength,
                                 string_id, std::move( revert ), key );
     }
 }
References add(), faction_id, furn_id, JsonObject::get_array(), submap::get_items(), get_timed_events(), SEEX, submap::set_all_ter(), submap::set_furn(), submap::set_ter(), submap::set_trap(), strength, ter_id, trap_id, type, point::x, and point::y.
Referenced by game::unserialize_master().
Member Data Documentation
events
std::list<timed_event> timed_event_manager::events private
Definition at line 68 of file timed_event.h.
Referenced by add(), get(), get_all(), process(), serialize_all(), and set_all().
The documentation for this class was generated from the following files:
src/timed_event.h
src/savegame.cpp
src/timed_event.cpp