Cataclysm DDA: eoc_events Class Reference
eoc_events Class Reference
#include <effect_on_condition.h>
Public Member Functions
void notify (const cata::event &e) override
void notify (const cata::event &, std::unique_ptr< talker >, std::unique_ptr< talker >) override
void clear ()
Public Member Functions inherited from event_subscriber
event_subscriber ()=default
event_subscriber (const event_subscriber &)=delete
event_subscriber & operator= (const event_subscriber &)=delete
virtual ~event_subscriber ()
Private Attributes
std::map< event_type, std::vector< effect_on_condition > > event_EOCs
bool has_cached = false
Detailed Description
Definition at line 41 of file effect_on_condition.h.
Member Function Documentation
clear()
void eoc_events::clear ()
Definition at line 512 of file effect_on_condition.cpp.
 {
     has_cached = false;
     event_EOCs.clear();
 }
References event_EOCs, and has_cached.
notify() [1/2]
void eoc_events::notify (const cata::event & e, std::unique_ptr< talker > alpha, std::unique_ptr< talker > beta) override virtual
Reimplemented from event_subscriber.
Definition at line 523 of file effect_on_condition.cpp.
 {
     if( !has_cached ) {
         // initialize all events to an empty vector
         for( event_type et = static_cast<event_type>( 0 ); et < event_type::num_event_types;
              et = static_cast<event_type>( static_cast<size_t>( et ) + 1 ) ) {
             event_EOCs[et] = std::vector<effect_on_condition>();
         }
         //create a cache for the specific types of EOC's so they aren't constantly all itterated through
         for( const effect_on_condition &eoc : effect_on_conditions::get_all() ) {
             if( eoc.type == eoc_type::EVENT ) {
                 event_EOCs[eoc.required_event].emplace_back( eoc );
             }
         }
         has_cached = true;
     }
     for( const effect_on_condition &eoc : event_EOCs[e.type()] ) {
         if( !alpha ) {
             // try to assign a character for the EOC
             // TODO: refactor event_spec to take consistent inputs
             npc *alpha_talker = nullptr;
             const std::vector<std::string> potential_alphas = { "avatar_id", "character", "attacker", "killer", "npc" };
             for( const std::string &potential_key : potential_alphas ) {
                 cata_variant cv = e.get_variant_or_void( potential_key );
                 if( cv != cata_variant() ) {
                     character_id potential_id = cv.get<cata_variant_type::character_id>();
                     if( potential_id.is_valid() ) {
                         alpha_talker = g->find_npc( potential_id );
                         // if we find a successful entry exit early
                         break;
                     }
                 }
             }
             if( alpha_talker ) {
                 alpha = get_talker_for( alpha_talker );
             } else {
                 alpha = get_talker_for( get_avatar() );
             }
         }
         dialogue d;
         std::unordered_map<std::string, std::string> context;
         for( const auto &val : e.data() ) {
             context["npctalk_var_" + val.first] = val.second.get_string();
         }
         // if we have an NPC to trigger this event for, do so,
         // otherwise fallback to having it effect the player
         d = dialogue( alpha->clone(), beta ? beta->clone() : nullptr, {}, context );
         eoc.activate( d );
     }
 }
References character_id, context, cata::event::data(), eoc, EVENT, event_EOCs, g, cata_variant::get(), effect_on_conditions::get_all(), get_avatar(), get_talker_for(), cata::event::get_variant_or_void(), has_cached, character_id::is_valid(), num_event_types, and cata::event::type().
notify() [2/2]
void eoc_events::notify (const cata::event & e) override virtual
Implements event_subscriber.
Definition at line 518 of file effect_on_condition.cpp.
 {
     notify( e, nullptr, nullptr );
 }
Member Data Documentation
event_EOCs
std::map<event_type, std::vector<effect_on_condition> > eoc_events::event_EOCs private
Definition at line 49 of file effect_on_condition.h.
Referenced by clear(), and notify().
has_cached
bool eoc_events::has_cached = false private
Definition at line 50 of file effect_on_condition.h.
Referenced by clear(), and notify().
The documentation for this class was generated from the following files:
src/effect_on_condition.h
src/effect_on_condition.cpp