Cataclysm DDA: trade_preset Class Reference
trade_preset Class Reference
#include <trade_ui.h>
Public Member Functions
trade_preset (Character const &you, Character const &trader)
bool is_shown (item_location const &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const override
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Private Attributes
Character const & _u
Character const & _trader
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 54 of file trade_ui.h.
Constructor & Destructor Documentation
trade_preset()
trade_preset::trade_preset (Character const & you, Character const & trader) explicit
Definition at line 42 of file trade_ui.cpp.
     : _u( you ), _trader( trader )
 {
     save_state = &inventory_ui_default_state;
     append_cell(
     [&]( item_location const & loc ) {
         return format_money( npc_trading::trading_price( _trader, _u, { loc, 1 } ) );
     },
     _( "Unit price" ) );
 }
References _, _trader, _u, inventory_selector_preset::append_cell(), format_money(), inventory_ui_default_state, inventory_selector_preset::save_state, and npc_trading::trading_price().
Member Function Documentation
cat_sort_compare()
bool trade_preset::cat_sort_compare (const inventory_entry & lhs, const inventory_entry & rhs) const override virtual
Reimplemented from inventory_selector_preset.
Definition at line 94 of file trade_ui.cpp.
 {
     // sort worn and held categories last we likely don't want to trade them
     auto const fudge_rank = []( inventory_entry const & e ) -> int {
         item_category_id const cat = e.get_category_ptr()->get_id();
         int const rank = e.get_category_ptr()->sort_rank();
         return cat != item_category_ITEMS_WORN && cat != item_category_WEAPON_HELD ? rank : rank + 10000;
     };
     return fudge_rank( lhs ) < fudge_rank( rhs );
 }
References item_category::get_id(), item_category_ITEMS_WORN, item_category_WEAPON_HELD, and item_category::sort_rank().
get_denial()
std::string trade_preset::get_denial (const item_location &) const override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 60 of file trade_ui.cpp.
 {
     int const price = npc_trading::trading_price( _trader, _u, { loc, 1 } );
     if( _u.is_npc() ) {
         npc const &np = *_u.as_npc();
         ret_val<void> const ret = np.wants_to_sell( loc, price );
         if( !ret.success() ) {
             if( ret.str().empty() ) {
                 return string_format( _( "%s does not want to sell this" ), np.get_name() );
             }
             return np.replace_with_npc_name( ret.str() );
         }
     } else if( _trader.is_npc() ) {
         npc const &np = *_trader.as_npc();
         ret_val<void> const ret = np.wants_to_buy( *loc, price );
         if( !ret.success() ) {
             if( ret.str().empty() ) {
                 return string_format( _( "%s does not want to buy this" ), np.get_name() );
             }
             return np.replace_with_npc_name( ret.str() );
         }
     }
     if( _u.is_worn( *loc ) ) {
         ret_val<void> const ret = const_cast<Character &>( _u ).can_takeoff( *loc );
         if( !ret.success() ) {
             return _u.replace_with_npc_name( ret.str() );
         }
     }
     return inventory_selector_preset::get_denial( loc );
 }
References _, _trader, _u, Creature::as_npc(), inventory_selector_preset::get_denial(), Character::get_name(), Character::is_npc(), Character::is_worn(), Creature::replace_with_npc_name(), cata::hash64_detail::ret, string_format(), npc_trading::trading_price(), npc::wants_to_buy(), and npc::wants_to_sell().
is_shown()
bool trade_preset::is_shown (item_location const &) const override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 53 of file trade_ui.cpp.
 {
     return !loc->has_var( VAR_TRADE_IGNORE ) && inventory_selector_preset::is_shown( loc ) &&
            loc->is_owned_by( _u ) && loc->made_of( phase_id::SOLID ) && !loc->is_frozen_liquid() &&
            ( !_u.is_wielding( *loc ) || !loc->has_flag( json_flag_NO_UNWIELD ) );
 }
References _u, item::has_flag(), item::has_var(), item::is_frozen_liquid(), item::is_owned_by(), inventory_selector_preset::is_shown(), Character::is_wielding(), json_flag_NO_UNWIELD, item::made_of(), SOLID, and VAR_TRADE_IGNORE.
Member Data Documentation
_trader
Character const & trade_preset::_trader private
Definition at line 64 of file trade_ui.h.
Referenced by get_denial(), and trade_preset().
_u
Character const& trade_preset::_u private
Definition at line 64 of file trade_ui.h.
Referenced by get_denial(), is_shown(), and trade_preset().
The documentation for this class was generated from the following files:
src/trade_ui.h
src/trade_ui.cpp