Cataclysm DDA: jmapgen_computer Class Reference
jmapgen_computer Class Reference
Place a computer (console) with given stats and effects.
Public Member Functions
jmapgen_computer (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
Public Attributes
translation name
translation access_denied
int security
std::vector< computer_option > options
std::vector< computer_failure > failures
std::vector< std::string > chat_topics
std::vector< effect_on_condition_id > eocs
bool target
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a computer (console) with given stats and effects.
Parameters
options Array of computer_option
failures Array of failure effects (see computer_failure)
Definition at line 3150 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_computer()
jmapgen_computer::jmapgen_computer (const JsonObject & jsi, const std::string_view) inline
Definition at line 3161 of file mapgen.cpp.
{
             jsi.read( "name", name );
             jsi.read( "access_denied", access_denied );
             security = jsi.get_int( "security", 0 );
             target = jsi.get_bool( "target", false );
             if( jsi.has_array( "options" ) ) {
                 for( JsonObject jo : jsi.get_array( "options" ) ) {
                     options.emplace_back( computer_option::from_json( jo ) );
                 }
             }
             if( jsi.has_array( "failures" ) ) {
                 for( JsonObject jo : jsi.get_array( "failures" ) ) {
                     failures.emplace_back( computer_failure::from_json( jo ) );
                 }
             }
             if( jsi.has_array( "eocs" ) ) {
                 for( const std::string &eoc : jsi.get_string_array( "eocs" ) ) {
                     eocs.emplace_back( eoc );
                 }
             }
             if( jsi.has_array( "chat_topics" ) ) {
                 for( const std::string &topic : jsi.get_string_array( "chat_topics" ) ) {
                     chat_topics.emplace_back( topic );
                 }
             }
         }
References access_denied, chat_topics, eoc, eocs, failures, computer_option::from_json(), computer_failure::from_json(), JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_string_array(), JsonObject::has_array(), mapgen_defer::jsi, name, options, JsonObject::read(), security, and target.
Member Function Documentation
apply()
void jmapgen_computer::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 3187 of file mapgen.cpp.
{
             const tripoint_bub_ms r( x.get(), y.get(), dat.zlevel() + z.get() );
             dat.m.furn_set( r, furn_f_console );
             computer *cpu =
                 dat.m.add_computer( r.raw(), name.translated(),
                                     security );
             for( const computer_option &opt : options ) {
                 cpu->add_option( opt );
             }
             for( const computer_failure &opt : failures ) {
                 cpu->add_failure( opt );
             }
             if( target && dat.mission() ) {
                 cpu->set_mission( dat.mission()->get_id() );
             }
             for( const effect_on_condition_id &eoc : eocs ) {
                 cpu->add_eoc( eoc );
             }
             for( const std::string &chat_topic : chat_topics ) {
                 cpu->add_chat_topic( chat_topic );
             }
             // The default access denied message is defined in computer's constructor
             if( !access_denied.empty() ) {
                 cpu->set_access_denied_msg( access_denied.translated() );
             }
         }
References access_denied, computer::add_chat_topic(), map::add_computer(), computer::add_eoc(), computer::add_failure(), computer::add_option(), chat_topics, translation::empty(), eoc, eocs, failures, furn_f_console, map::furn_set(), jmapgen_int::get(), mission::get_id(), mapgendata::m, mapgendata::mission(), name, options, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), security, computer::set_access_denied_msg(), computer::set_mission(), target, translation::translated(), and mapgendata::zlevel().
has_vehicle_collision()
bool jmapgen_computer::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 3214 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint_bub_ms( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
Member Data Documentation
access_denied
translation jmapgen_computer::access_denied
Definition at line 3154 of file mapgen.cpp.
Referenced by apply(), and jmapgen_computer().
chat_topics
std::vector<std::string> jmapgen_computer::chat_topics
Definition at line 3158 of file mapgen.cpp.
Referenced by apply(), and jmapgen_computer().
eocs
std::vector<effect_on_condition_id> jmapgen_computer::eocs
Definition at line 3159 of file mapgen.cpp.
Referenced by apply(), and jmapgen_computer().
failures
std::vector<computer_failure> jmapgen_computer::failures
Definition at line 3157 of file mapgen.cpp.
Referenced by apply(), and jmapgen_computer().
name
translation jmapgen_computer::name
Definition at line 3153 of file mapgen.cpp.
Referenced by apply(), and jmapgen_computer().
options
std::vector<computer_option> jmapgen_computer::options
Definition at line 3156 of file mapgen.cpp.
Referenced by apply(), and jmapgen_computer().
security
int jmapgen_computer::security
Definition at line 3155 of file mapgen.cpp.
Referenced by apply(), and jmapgen_computer().
target
bool jmapgen_computer::target
Definition at line 3160 of file mapgen.cpp.
Referenced by apply(), and jmapgen_computer().
The documentation for this class was generated from the following file:
src/mapgen.cpp