Cataclysm DDA: jmapgen_sign Class Reference
jmapgen_sign Class Reference
Place a sign with some text.
Public Member Functions
jmapgen_sign (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
std::string apply_all_tags (std::string signtext, const std::string &cityname) const
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
Public Attributes
translation signage
std::string snippet
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Private Attributes
furn_id sign_furniture
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a sign with some text.
"signage": the text on the sign.
Definition at line 1961 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_sign()
jmapgen_sign::jmapgen_sign (const JsonObject & jsi, const std::string_view) inline
Definition at line 1968 of file mapgen.cpp.
                                                                      :
             snippet( jsi.get_string( "snippet", "" ) ) {
             jsi.read( "signage", signage );
             optional( jsi, false, "furniture", sign_furniture, furn_f_sign );
             if( signage.empty() && snippet.empty() ) {
                 jsi.throw_error( "jmapgen_sign: needs either signage or snippet" );
             }
             if( !sign_furniture->has_flag( ter_furn_flag::TFLAG_SIGN ) ) {
                 jsi.throw_error( "jmapgen_sign: specified furniture needs SIGN flag" );
             }
         }
References translation::empty(), furn_f_sign, map_data_common_t::has_flag(), mapgen_defer::jsi, optional(), JsonObject::read(), sign_furniture, signage, snippet, TFLAG_SIGN, and JsonObject::throw_error().
Member Function Documentation
apply()
void jmapgen_sign::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1979 of file mapgen.cpp.
{
             const tripoint_bub_ms r( x.get(), y.get(), z.get() );
             dat.m.furn_set( r, furn_str_id::NULL_ID() );
             dat.m.furn_set( r, sign_furniture );
             std::string signtext;
             if( !snippet.empty() ) {
                 // select a snippet from the category
                 signtext = SNIPPET.random_from_category( snippet ).value_or( translation() ).translated();
             } else if( !signage.empty() ) {
                 signtext = signage.translated();
             }
             if( !signtext.empty() ) {
                 // replace tags
                 std::string cityname = "illegible city name";
                 tripoint_abs_sm abs_sub = dat.m.get_abs_sub();
                 const city *c = overmap_buffer.closest_city( abs_sub ).city;
                 if( c != nullptr ) {
                     cityname = c->name;
                 }
                 signtext = apply_all_tags( signtext, cityname );
             }
             dat.m.set_signage( r.raw(), signtext );
         }
References apply_all_tags(), c, city_reference::city, overmapbuffer::closest_city(), translation::empty(), map::furn_set(), jmapgen_int::get(), map::get_abs_sub(), mapgendata::m, string_id< furn_t >::NULL_ID(), overmap_buffer, snippet_library::random_from_category(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), map::set_signage(), sign_furniture, signage, snippet, SNIPPET, and translation::translated().
apply_all_tags()
std::string jmapgen_sign::apply_all_tags (std::string signtext, const std::string & cityname) const inline
Definition at line 2005 of file mapgen.cpp.
{
             signtext = SNIPPET.expand( signtext );
             replace_city_tag( signtext, cityname );
             return signtext;
         }
References snippet_library::expand(), replace_city_tag(), and SNIPPET.
Referenced by apply().
has_vehicle_collision()
bool jmapgen_sign::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2010 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint_bub_ms( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
Member Data Documentation
sign_furniture
furn_id jmapgen_sign::sign_furniture private
Definition at line 1964 of file mapgen.cpp.
Referenced by apply(), and jmapgen_sign().
signage
translation jmapgen_sign::signage
Definition at line 1966 of file mapgen.cpp.
Referenced by apply(), and jmapgen_sign().
snippet
std::string jmapgen_sign::snippet
Definition at line 1967 of file mapgen.cpp.
Referenced by apply(), and jmapgen_sign().
The documentation for this class was generated from the following file:
src/mapgen.cpp