Cataclysm DDA: item_location::impl::item_on_map Class Reference
item_location::impl::item_on_map Class Reference
Public Member Functions
item_on_map (const map_cursor &cur, item *which)
item_on_map (const map_cursor &cur, int idx)
void serialize (JsonOut &js) const override
item * unpack (int idx) const override
type where () const override
tripoint position () const override
Character * carrier () const override
std::string describe (const Character *ch) const override
item_location obtain (Character &ch, int qty) override
int obtain_cost (const Character &ch, int qty) const override
void remove_item () override
void on_contents_changed () override
units::volume volume_capacity () const override
units::mass weight_capacity () const override
bool check_parent_capacity_recursive () const override
Public Member Functions inherited from item_location::impl
impl ()=default
impl (item *i)
impl (int idx)
virtual ~impl ()=default
virtual type where_recursive () const
virtual item_location parent_item () const
virtual item_pocket * parent_pocket () const
item * target () const
virtual bool valid () const
Private Attributes
map_cursor cur
Additional Inherited Members
Public Attributes inherited from item_location::impl
bool should_stack = true
Detailed Description
Definition at line 197 of file item_location.cpp.
Constructor & Destructor Documentation
item_on_map() [1/2]
item_location::impl::item_on_map::item_on_map (const map_cursor & cur, item * which) inline
Definition at line 203 of file item_location.cpp.
 : impl( which ), cur( cur ) {}
item_on_map() [2/2]
item_location::impl::item_on_map::item_on_map (const map_cursor & cur, int idx) inline
Definition at line 204 of file item_location.cpp.
 : impl( idx ), cur( cur ) {}
Member Function Documentation
carrier()
Character* item_location::impl::item_on_map::carrier () const inline override virtual
Implements item_location::impl.
Definition at line 226 of file item_location.cpp.
{
             return nullptr;
         }
check_parent_capacity_recursive()
bool item_location::impl::item_on_map::check_parent_capacity_recursive () const inline override virtual
Implements item_location::impl.
Definition at line 291 of file item_location.cpp.
{
             return volume_capacity() >= 0_ml && weight_capacity() >= 0_gram;
         }
References volume_capacity(), and weight_capacity().
describe()
std::string item_location::impl::item_on_map::describe (const Character * ch) const inline override virtual
Implements item_location::impl.
Definition at line 230 of file item_location.cpp.
{
             std::string res = get_map().name( cur.pos() );
             if( ch ) {
                 res += std::string( " " ) += direction_suffix( ch->pos(), cur.pos() );
             }
             return res;
         }
References cur, direction_suffix(), get_map(), map::name(), Creature::pos(), and map_cursor::pos().
obtain()
item_location item_location::impl::item_on_map::obtain (Character & ch, int qty) inline override virtual
Implements item_location::impl.
Definition at line 238 of file item_location.cpp.
{
             ch.mod_moves( -obtain_cost( ch, qty ) );
             on_contents_changed();
             item obj = target()->split( qty );
             const auto get_local_location = []( Character & ch, item_location it ) {
                 if( ch.has_item( *it ) ) {
                     return item_location( ch, &*it );
                 } else {
                     return item_location{};
                 }
             };
             if( !obj.is_null() ) {
                 return get_local_location( ch, ch.i_add( obj, should_stack ) );
             } else {
                 item_location inv = ch.i_add( *target(), should_stack, nullptr, target() );
                 remove_item();
                 return get_local_location( ch, inv );
             }
         }
References visitable::has_item(), Character::i_add(), item::is_null(), item_location::item_location(), Creature::mod_moves(), obtain_cost(), on_contents_changed(), remove_item(), item_location::impl::should_stack, item::split(), and item_location::impl::target().
obtain_cost()
int item_location::impl::item_on_map::obtain_cost (const Character & ch, int qty) const inline override virtual
Implements item_location::impl.
Definition at line 259 of file item_location.cpp.
{
             if( !target() ) {
                 return 0;
             }
             item *obj = target();
             int mv = ch.item_handling_cost( *obj, true, MAP_HANDLING_PENALTY, qty );
             mv += 100 * rl_dist( ch.pos(), cur.pos() );
             // TODO: handle unpacking costs
             return mv;
         }
References cur, Character::item_handling_cost(), MAP_HANDLING_PENALTY, Creature::pos(), map_cursor::pos(), rl_dist(), and item_location::impl::target().
Referenced by obtain().
on_contents_changed()
void item_location::impl::item_on_map::on_contents_changed () inline override virtual
Implements item_location::impl.
Definition at line 278 of file item_location.cpp.
{
             target()->on_contents_changed();
         }
References item::on_contents_changed(), and item_location::impl::target().
Referenced by obtain(), and remove_item().
position()
tripoint item_location::impl::item_on_map::position () const inline override virtual
Implements item_location::impl.
Definition at line 222 of file item_location.cpp.
{
             return cur.pos();
         }
References cur, and map_cursor::pos().
Referenced by serialize().
remove_item()
void item_location::impl::item_on_map::remove_item () inline override virtual
Implements item_location::impl.
Definition at line 273 of file item_location.cpp.
{
             on_contents_changed();
             cur.remove_item( *what );
         }
References cur, on_contents_changed(), visitable::remove_item(), and item_location::impl::what.
Referenced by obtain().
serialize()
void item_location::impl::item_on_map::serialize (JsonOut & js) const inline override virtual
Implements item_location::impl.
Definition at line 206 of file item_location.cpp.
{
             js.start_object();
             js.member( "type", "map" );
             js.member( "pos", position() );
             js.member( "idx", find_index( cur, target() ) );
             js.end_object();
         }
References cur, JsonOut::end_object(), find_index(), JsonOut::member(), position(), JsonOut::start_object(), and item_location::impl::target().
unpack()
item* item_location::impl::item_on_map::unpack (int idx) const inline override virtual
Implements item_location::impl.
Definition at line 214 of file item_location.cpp.
{
             return retrieve_index( cur, idx );
         }
References cur, item_location::impl::idx, and retrieve_index().
volume_capacity()
units::volume item_location::impl::item_on_map::volume_capacity () const inline override virtual
Implements item_location::impl.
Definition at line 282 of file item_location.cpp.
{
             map_stack stack = get_map().i_at( cur.pos() );
             return stack.free_volume();
         }
References cur, item_stack::free_volume(), get_map(), map::i_at(), and map_cursor::pos().
Referenced by check_parent_capacity_recursive().
weight_capacity()
units::mass item_location::impl::item_on_map::weight_capacity () const inline override virtual
Implements item_location::impl.
Definition at line 287 of file item_location.cpp.
{
             return units::mass_max;
         }
References units::mass_max.
Referenced by check_parent_capacity_recursive().
where()
type item_location::impl::item_on_map::where () const inline override virtual
Implements item_location::impl.
Definition at line 218 of file item_location.cpp.
{
             return type::map;
         }
References item_location::map.
Member Data Documentation
cur
map_cursor item_location::impl::item_on_map::cur private
Definition at line 200 of file item_location.cpp.
Referenced by describe(), obtain_cost(), position(), remove_item(), serialize(), unpack(), and volume_capacity().
The documentation for this class was generated from the following file:
src/item_location.cpp