Cataclysm DDA: jmapgen_terrain Class Reference
jmapgen_terrain Class Reference
Place terrain.
Public Member Functions
jmapgen_terrain (const JsonObject &jsi, const std::string_view)
jmapgen_terrain (const JsonValue &tid)
bool is_nop () const override
mapgen_phase phase () const override
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &context) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
Public Attributes
mapgen_value< ter_id > id
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Private Types
enum apply_action { act_unknown , act_ignore , act_dismantle , act_erase }
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place terrain.
"ter": id of the terrain.
Definition at line 2907 of file mapgen.cpp.
Member Enumeration Documentation
apply_action
enum jmapgen_terrain::apply_action private
Enumerator
act_unknown
act_ignore
act_dismantle
act_erase
Definition at line 2910 of file mapgen.cpp.
{
             act_unknown, act_ignore, act_dismantle, act_erase
         };
Constructor & Destructor Documentation
jmapgen_terrain() [1/2]
jmapgen_terrain::jmapgen_terrain (const JsonObject & jsi, const std::string_view) inline
Definition at line 2915 of file mapgen.cpp.
                                                                         :
             jmapgen_terrain( jsi.get_member( "ter" ) ) {}
jmapgen_terrain() [2/2]
jmapgen_terrain::jmapgen_terrain (const JsonValue & tid) inline explicit
Definition at line 2917 of file mapgen.cpp.
 : id( mapgen_value<ter_id>( tid ) ) {}
Member Function Documentation
apply()
void jmapgen_terrain::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2926 of file mapgen.cpp.
{
             ter_id chosen_id = id.get( dat );
             if( chosen_id.id().is_null() ) {
                 return;
             }
             tripoint p( x.get(), y.get(), dat.zlevel() + z.get() );
             ter_id terrain_here = dat.m.ter( p );
             const ter_t &chosen_ter = *chosen_id;
             const bool is_wall = chosen_ter.has_flag( ter_furn_flag::TFLAG_WALL );
             const bool place_item = chosen_ter.has_flag( ter_furn_flag::TFLAG_PLACE_ITEM );
             const bool is_boring_wall = is_wall && !place_item;
             apply_action act_furn = apply_action::act_unknown;
             apply_action act_trap = apply_action::act_unknown;
             apply_action act_item = apply_action::act_unknown;
             // shorthand flags
             if( dat.has_flag( jmapgen_flags::allow_terrain_under_other_data ) ) {
                 act_furn = apply_action::act_ignore;
                 act_trap = apply_action::act_ignore;
                 act_item = apply_action::act_ignore;
             } else if( dat.has_flag( jmapgen_flags::dismantle_all_before_placing_terrain ) ) {
                 act_furn = apply_action::act_dismantle;
                 act_trap = apply_action::act_dismantle;
                 act_item = apply_action::act_ignore;
             } else if( dat.has_flag( jmapgen_flags::erase_all_before_placing_terrain ) ) {
                 act_furn = apply_action::act_erase;
                 act_trap = apply_action::act_erase;
                 act_item = apply_action::act_erase;
             }
             // specific flags override shorthand flags
             if( dat.has_flag( jmapgen_flags::allow_terrain_under_furniture ) ) {
                 act_furn = apply_action::act_ignore;
             } else if( dat.has_flag( jmapgen_flags::dismantle_furniture_before_placing_terrain ) ) {
                 act_furn = apply_action::act_dismantle;
             } else if( dat.has_flag( jmapgen_flags::erase_furniture_before_placing_terrain ) ) {
                 act_furn = apply_action::act_erase;
             }
             if( dat.has_flag( jmapgen_flags::allow_terrain_under_trap ) ) {
                 act_trap = apply_action::act_ignore;
             } else if( dat.has_flag( jmapgen_flags::dismantle_trap_before_placing_terrain ) ) {
                 act_trap = apply_action::act_dismantle;
             } else if( dat.has_flag( jmapgen_flags::erase_trap_before_placing_terrain ) ) {
                 act_trap = apply_action::act_erase;
             }
             if( dat.has_flag( jmapgen_flags::allow_terrain_under_items ) ) {
                 act_item = apply_action::act_ignore;
             } else if( dat.has_flag( jmapgen_flags::erase_items_before_placing_terrain ) ) {
                 act_item = apply_action::act_erase;
             }
             if( act_item == apply_action::act_erase &&
                 ( act_furn == apply_action::act_dismantle || act_trap == apply_action::act_dismantle ) ) {
                 debugmsg( "In %s on %s, the mapgen is configured to dismantle preexisting furniture "
                           "and/or traps, but will also erase preexisting items.  This is probably a "
                           "mistake, as any dismantle outputs will not be preserved.",
                           context, dat.terrain_type().id().str() );
             }
             if( is_boring_wall || act_furn == apply_action::act_erase ) {
                 dat.m.furn_clear( p );
                 // remove sign writing data from the submap
                 dat.m.delete_signage( p );
             } else if( act_furn == apply_action::act_dismantle ) {
                 int max_recurse = 10; // insurance against infinite looping
                 std::string initial_furn = dat.m.furn( p ) != furn_str_id::NULL_ID() ? dat.m.furn(
                                                p ).id().str() : "";
                 while( dat.m.has_furn( p ) && max_recurse-- > 0 ) {
                     const furn_t &f = dat.m.furn( p ).obj();
                     if( f.deconstruct.can_do ) {
                         if( f.deconstruct.furn_set.str().empty() ) {
                             dat.m.furn_clear( p );
                         } else {
                             dat.m.furn_set( p, f.deconstruct.furn_set );
                         }
                         dat.m.spawn_items( p, item_group::items_from( f.deconstruct.drop_group, calendar::turn ) );
                     } else {
                         if( f.bash.furn_set.str().empty() ) {
                             dat.m.furn_clear( p );
                         } else {
                             dat.m.furn_set( p, f.bash.furn_set );
                         }
                         dat.m.spawn_items( p, item_group::items_from( f.bash.drop_group, calendar::turn ) );
                     }
                 }
                 if( !max_recurse ) {
                     dat.m.furn_clear( p );
                     debugmsg( "In %s on %s, the mapgen failed to arrive at an empty tile after "
                               "dismantling preexisting furniture %s at %s 10 times in succession.",
                               context, dat.terrain_type().id().str(), initial_furn, p.to_string() );
                 }
                 // remove sign writing data from the submap
                 dat.m.delete_signage( p );
             }
             if( is_boring_wall || act_trap == apply_action::act_erase ) {
                 dat.m.remove_trap( p );
             } else if( act_trap == apply_action::act_dismantle ) {
                 dat.m.tr_at( p ).on_disarmed( dat.m, p );
             }
             if( is_boring_wall || act_item == apply_action::act_erase ) {
                 dat.m.i_clear( p );
             }
             if( chosen_id != terrain_here ) {
                 std::string error;
                 trap_str_id trap_here = dat.m.tr_at( p ).id;
                 if( act_furn != apply_action::act_ignore && dat.m.furn( p ) != furn_str_id::NULL_ID() ) {
                     // NOLINTNEXTLINE(cata-translate-string-literal)
                     error = string_format( "furniture was %s", dat.m.furn( p ).id().str() );
                 } else if( act_trap != apply_action::act_ignore && !trap_here.is_null() &&
                            trap_here.id() != terrain_here->trap ) {
                     // NOLINTNEXTLINE(cata-translate-string-literal)
                     error = string_format( "trap %s existed", trap_here.str() );
                 } else if( act_item != apply_action::act_ignore && !dat.m.i_at( p ).empty() ) {
                     // NOLINTNEXTLINE(cata-translate-string-literal)
                     error = string_format( "item %s existed",
                                            dat.m.i_at( p ).begin()->typeId().str() );
                 }
                 if( !error.empty() ) {
                     debugmsg( "In %s on %s, setting terrain to %s (from %s) at %s when %s.  "
                               "Resolve this either by removing the terrain from this mapgen, "
                               "adding suitable removal commands to the mapgen, or by adding an "
                               "appropriate clearing flag to the innermost layered mapgen.  "
                               "Consult the \"mapgen flags\" section in MAPGEN.md for options.",
                               context, dat.terrain_type().id().str(), chosen_id.id().str(),
                               terrain_here.id().str(), p.to_string(), error );
                 }
             }
             dat.m.ter_set( p, chosen_id );
         }
References allow_terrain_under_furniture, allow_terrain_under_items, allow_terrain_under_other_data, allow_terrain_under_trap, map_data_common_t::bash, item_stack::begin(), map_deconstruct_info::can_do, context, debugmsg, map_data_common_t::deconstruct, map::delete_signage(), dismantle_all_before_placing_terrain, dismantle_furniture_before_placing_terrain, dismantle_trap_before_placing_terrain, map_bash_info::drop_group, map_deconstruct_info::drop_group, item_stack::empty(), erase_all_before_placing_terrain, erase_furniture_before_placing_terrain, erase_items_before_placing_terrain, erase_trap_before_placing_terrain, error, map::furn(), map::furn_clear(), map::furn_set(), map_bash_info::furn_set, map_deconstruct_info::furn_set, jmapgen_int::get(), map_data_common_t::has_flag(), mapgendata::has_flag(), map::has_furn(), map::i_at(), map::i_clear(), int_id< T >::id(), string_id< T >::id(), trap::id, string_id< T >::is_null(), item_group::items_from(), mapgendata::m, string_id< furn_t >::NULL_ID(), int_id< T >::obj(), trap::on_disarmed(), map::remove_trap(), map::spawn_items(), string_id< T >::str(), string_format(), map::ter(), map::ter_set(), mapgendata::terrain_type(), TFLAG_PLACE_ITEM, TFLAG_WALL, tripoint::to_string(), map::tr_at(), ter_t::trap, calendar::turn, and mapgendata::zlevel().
check()
void jmapgen_terrain::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 3065 of file mapgen.cpp.
{
             id.check( oter_name, parameters );
         }
has_vehicle_collision()
bool jmapgen_terrain::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 3061 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint_bub_ms( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
is_nop()
bool jmapgen_terrain::is_nop () const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2919 of file mapgen.cpp.
{
             return id.is_null();
         }
phase()
mapgen_phase jmapgen_terrain::phase () const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2922 of file mapgen.cpp.
{
             return mapgen_phase::terrain;
         }
References terrain.
Member Data Documentation
id
mapgen_value<ter_id> jmapgen_terrain::id
Definition at line 2914 of file mapgen.cpp.
The documentation for this class was generated from the following file:
src/mapgen.cpp