Cataclysm DDA: inventory_selector Class Reference
inventory_selector Class Reference
#include <inventory_ui.h>
Public Types
enum selector_invlet_type { SELECTOR_INVLET_DEFAULT , SELECTOR_INVLET_NUMERIC , SELECTOR_INVLET_ALPHA }
enum class uimode : int { categories = 0 , hierarchy , last }
using stat = std::array< std::string, 4 >
using stats = std::array< stat, 3 >
Public Member Functions
inventory_selector (Character &u, const inventory_selector_preset &preset=default_preset)
virtual ~inventory_selector ()
bool add_contained_items (item_location &container)
These functions add items from map / vehicles.
bool add_contained_items (item_location &container, inventory_column &column, const item_category *custom_category=nullptr, item_location const &topmost_parent={}, int indent=0)
void add_contained_gunmods (Character &you, item &gun)
void add_contained_ebooks (item_location &container)
void add_character_items (Character &character)
void add_map_items (const tripoint &target)
void add_vehicle_items (const tripoint &target)
void add_nearby_items (int radius=1)
void add_remote_map_items (tinymap *remote_map, const tripoint &target)
void add_basecamp_items (const basecamp &camp)
void clear_items ()
Remove all items.
void set_title (const std::string &title)
Assigns a title that will be shown on top of the menu.
void set_hint (const std::string &hint)
Assigns a hint.
void set_display_stats (bool display_stats)
Specify whether the header should show stats (weight and volume).
bool empty () const
bool has_available_choices () const
uint64_t item_entry_count () const
drop_location get_only_choice () const
void set_filter (const std::string &str)
Apply filter string to all columns.
std::string get_filter () const
Get last filter string set by set_filter or entered by player.
void set_invlet_type (selector_invlet_type type)
Set the letter group to use for automatic inventory letters.
selector_invlet_type invlet_type ()
void show_invlet (bool show)
Set whether to show inventory letters.
bool showing_invlet () const
void categorize_map_items (bool toggle)
bool highlight (const item_location &loc, bool hidden=false, bool front_only=false)
Highlight a location.
const inventory_entry & get_highlighted () const
item_location get_collation_next () const
void highlight_position (std::pair< size_t, size_t > position)
bool highlight_one_of (const std::vector< item_location > &locations, bool hidden=false)
std::pair< size_t, size_t > get_highlighted_position () const
inventory_column & get_column (size_t index) const
inventory_column & get_active_column () const
void toggle_categorize_contained ()
void set_active_column (size_t index)
void toggle_skip_unselectable ()
std::string action_bound_to_key (char key) const
Protected Member Functions
const item_category * naturalize_category (const item_category &category, const tripoint &pos)
inventory_entry * add_entry (inventory_column &target_column, std::vector< item_location > &&locations, const item_category *custom_category=nullptr, size_t chosen_count=0, item_location const &topmost_parent={}, bool chevron=false)
bool add_entry_rec (inventory_column &entry_column, inventory_column &children_column, item_location &loc, item_category const *entry_category=nullptr, item_category const *children_category=nullptr, item_location const &topmost_parent={}, int indent=0)
bool drag_drop_item (item *sourceItem, item *destItem)
inventory_input get_input ()
inventory_input process_input (const std::string &action, int ch)
void on_input (const inventory_input &input)
Given an action from the input_context, try to act according to it.
void on_change (const inventory_entry &entry)
Entry has been changed.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
size_t get_layout_width () const
size_t get_layout_height () const
std::pair< bool, std::string > query_string (const std::string &val, bool end_with_toggle=false)
Query user for a string and return it.
void query_set_filter ()
Query the user for a filter and apply it.
int query_count (char init=0, bool end_with_toggle=false)
Query the user for count and return it.
virtual void rearrange_columns (size_t client_width)
Tackles screen overflow.
virtual stats get_raw_stats () const
Get stats to display in top right.
std::vector< std::string > get_stats () const
std::pair< std::string, nc_color > get_footer (navigation_mode m) const
size_t get_header_height () const
size_t get_header_min_width () const
size_t get_footer_min_width () const
inventory_entry * find_entry_by_invlet (int invlet) const
inventory_entry * find_entry_by_coordinate (const point &coordinate) const
inventory_entry * find_entry_by_location (item_location &loc) const
const std::vector< inventory_column * > & get_all_columns () const
std::vector< inventory_column * > get_visible_columns () const
void highlight ()
Highlight parent and contents of highlighted item.
void action_examine (const item_location &sitem)
Show detailed item information for the selected item.
virtual void reassign_custom_invlets ()
size_t get_columns_width (const std::vector< inventory_column * > &columns) const
double get_columns_occupancy_ratio (size_t client_width) const
bool are_columns_centered (size_t client_width) const
bool is_overflown (size_t client_width) const
bool is_active_column (const inventory_column &column) const
void append_column (inventory_column &column)
void toggle_active_column (scroll_direction dir)
Activates either previous or next column.
void refresh_active_column ()
void toggle_navigation_mode ()
const navigation_mode_data & get_navigation_data (navigation_mode m) const
Static Protected Member Functions
static stat get_weight_and_length_stat (units::mass weight_carried, units::mass weight_capacity, const units::length &longest_length)
static stat get_volume_stat (const units::volume &volume_carried, const units::volume &volume_capacity, const units::volume &largest_free_volume)
static stat get_holster_stat (const units::volume &holster_volume, int used_holsters, int total_holsters)
static stats get_weight_and_volume_and_holster_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume &volume_carried, const units::volume &volume_capacity, const units::length &longest_length, const units::volume &largest_free_volume, const units::volume &holster_volume, int used_holsters, int total_holsters)
Protected Attributes
Character & u
const inventory_selector_preset & preset
input_context ctxt
The input context for navigation, already contains some actions for movement.
std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * > > rect_entry_map
std::vector< inventory_column * > columns
point _fixed_origin { -1, -1 }
point _fixed_size { -1, -1 }
bool _categorize_map_items = false
bool force_single_column = false
Private Member Functions
void prepare_layout (size_t client_width, size_t client_height)
void prepare_layout ()
void resize_window (int width, int height)
void refresh_window ()
void draw_header (const catacurses::window &w) const
void draw_footer (const catacurses::window &w) const
void draw_columns (const catacurses::window &w)
void draw_frame (const catacurses::window &w) const
void _add_map_items (tripoint const &target, item_category const &cat, item_stack &items, std::function< item_location(item &)> const &floc)
void _categorize (inventory_column &col)
void _uncategorize (inventory_column &col)
Private Attributes
catacurses::window w_inv
weak_ptr_fast< ui_adaptor > ui
std::unique_ptr< string_input_popup > spopup
std::string title
std::string hint
size_t active_column_index
std::list< item_category > categories
navigation_mode mode
inventory_column own_inv_column
inventory_column own_gear_column
inventory_column map_column
const int border = 1
std::string filter
bool is_empty = true
bool display_stats = true
bool use_invlet = true
selector_invlet_type invlet_type_ = SELECTOR_INVLET_DEFAULT
size_t entry_generation_number = 0
uimode _uimode = uimode::categories
Static Private Attributes
static bool skip_unselectable = false
Detailed Description
Definition at line 604 of file inventory_ui.h.
Member Typedef Documentation
stat
using inventory_selector::stat = std::array<std::string, 4>
Definition at line 674 of file inventory_ui.h.
stats
using inventory_selector::stats = std::array<stat, 3>
Definition at line 675 of file inventory_ui.h.
Member Enumeration Documentation
selector_invlet_type
enum inventory_selector::selector_invlet_type
Enumerator
SELECTOR_INVLET_DEFAULT
SELECTOR_INVLET_NUMERIC
SELECTOR_INVLET_ALPHA
Definition at line 649 of file inventory_ui.h.
{
             SELECTOR_INVLET_DEFAULT,
             SELECTOR_INVLET_NUMERIC,
             SELECTOR_INVLET_ALPHA
         };
uimode
enum inventory_selector::uimode : int strong
Enumerator
categories
hierarchy
last
Definition at line 840 of file inventory_ui.h.
                           : int {
             categories = 0,
             hierarchy,
             last,
         };
Constructor & Destructor Documentation
inventory_selector()
inventory_selector::inventory_selector (Character & u, const inventory_selector_preset & preset = default_preset) explicit
Definition at line 2817 of file inventory_ui.cpp.
     : u( u )
     , preset( preset )
     , ctxt( "INVENTORY", keyboard_mode::keychar )
     , active_column_index( 0 )
     , mode( navigation_mode::ITEM )
     , own_inv_column( preset )
     , own_gear_column( preset )
     , map_column( preset )
     , _uimode( preset.save_state == nullptr ? inventory_sel_default_state.uimode :
                preset.save_state->uimode )
 {
     item_name_cache_users++;
     tp_start =
         std::chrono::time_point_cast<std::chrono::milliseconds>( std::chrono::steady_clock::now() );
     ctxt.register_action( "COORDINATE" );
     ctxt.register_action( "MOUSE_MOVE" );
     ctxt.register_action( "DOWN", to_translation( "Next item" ) );
     ctxt.register_action( "UP", to_translation( "Previous item" ) );
     ctxt.register_action( "SCROLL_UP", to_translation( "Move cursor up" ) );
     ctxt.register_action( "SCROLL_DOWN", to_translation( "Move cursor down" ) );
     ctxt.register_action( "PAGE_DOWN", to_translation( "Page down" ) );
     ctxt.register_action( "PAGE_UP", to_translation( "Page up" ) );
     ctxt.register_action( "NEXT_COLUMN", to_translation( "Next column" ) );
     ctxt.register_action( "PREV_COLUMN", to_translation( "Previous column" ) );
     ctxt.register_action( "CONFIRM", to_translation( "Confirm your selection" ) );
     ctxt.register_action( "QUIT", to_translation( "Cancel" ) );
     ctxt.register_action( "CATEGORY_SELECTION", to_translation( "Switch category selection mode" ) );
     ctxt.register_action( "TOGGLE_FAVORITE", to_translation( "Toggle favorite" ) );
     ctxt.register_action( "HOME", to_translation( "Home" ) );
     ctxt.register_action( "END", to_translation( "End" ) );
     ctxt.register_action( "CLICK_AND_DRAG" );
     ctxt.register_action( "SELECT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "VIEW_CATEGORY_MODE" );
     ctxt.register_action( "TOGGLE_NUMPAD_NAVIGATION" );
     ctxt.register_action( "ANY_INPUT" ); // For invlets
     ctxt.register_action( "INVENTORY_FILTER" );
     ctxt.register_action( "RESET_FILTER" );
     ctxt.register_action( "EXAMINE" );
     ctxt.register_action( "SHOW_HIDE_CONTENTS", to_translation( "Show/hide contents" ) );
     ctxt.register_action( "SHOW_HIDE_CONTENTS_ALL" );
     ctxt.register_action( "EXAMINE_CONTENTS" );
     ctxt.register_action( "TOGGLE_SKIP_UNSELECTABLE" );
     ctxt.register_action( "ORGANIZE_MENU" );
     append_column( own_inv_column );
     append_column( map_column );
     append_column( own_gear_column );
     for( inventory_column *column : columns ) {
         column->toggle_skip_unselectable( skip_unselectable );
     }
 }
References append_column(), columns, ctxt, ITEM, anonymous_namespace{inventory_ui.cpp}::item_name_cache_users, keychar, map_column, own_gear_column, own_inv_column, input_context::register_action(), skip_unselectable, to_translation(), anonymous_namespace{inventory_ui.cpp}::tp_start, and u.
~inventory_selector()
inventory_selector::~inventory_selector () virtual
Definition at line 2872 of file inventory_ui.cpp.
 {
     item_name_cache_users--;
     if( item_name_cache_users <= 0 ) {
         item_name_cache.clear();
     }
     if( preset.save_state == nullptr ) {
         inventory_sel_default_state.uimode = _uimode;
     } else {
         preset.save_state->uimode = _uimode;
     }
 }
References _uimode, inventory_sel_default_state, anonymous_namespace{inventory_ui.cpp}::item_name_cache, anonymous_namespace{inventory_ui.cpp}::item_name_cache_users, preset, inventory_selector_preset::save_state, and inventory_selector_save_state::uimode.
Member Function Documentation
_add_map_items()
void inventory_selector::_add_map_items (tripoint const & target, item_category const & cat, item_stack & items, std::function< item_location(item &)> const & floc) private
Definition at line 2127 of file inventory_ui.cpp.
 {
     bool const hierarchy = _uimode == uimode::hierarchy;
     item_category const *const custom_cat = hierarchy ? naturalize_category( cat, target ) : nullptr;
     inventory_column *const col = _categorize_map_items ? &own_inv_column : &map_column;
     inventory_column temp( preset );
     inventory_column temp_cont( preset );
     for( item &it : items ) {
         item_location loc = floc( it );
         add_entry_rec( temp, temp_cont, loc, custom_cat, custom_cat );
     }
     temp.move_entries_to( *col );
     temp_cont.move_entries_to( *col );
     if( !hierarchy ) {
         col->set_indent_entries_override( false );
     }
 }
References _categorize_map_items, _uimode, add_entry_rec(), hierarchy, map_column, inventory_column::move_entries_to(), naturalize_category(), own_inv_column, preset, inventory_column::set_indent_entries_override(), and temp.
Referenced by add_map_items(), add_remote_map_items(), and add_vehicle_items().
_categorize()
void inventory_selector::_categorize (inventory_column & col) private
Definition at line 3130 of file inventory_ui.cpp.
 {
     // Remove custom category and allow entries to categorize by their item's category
     for( inventory_entry *entry : col.get_entries( return_item, true ) ) {
         const item_location loc = entry->any_item();
         // ensure top-level equipped entries don't lose their special categories
         const item_category *custom_category = wielded_worn_category( loc, u );
         entry->set_custom_category( custom_category );
     }
     col.set_indent_entries_override( false );
     col.invalidate_paging();
     col.uncollate();
 }
References inventory_column::get_entries(), inventory_column::invalidate_paging(), anonymous_namespace{inventory_ui.cpp}::return_item(), inventory_column::set_indent_entries_override(), u, inventory_column::uncollate(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
Referenced by toggle_categorize_contained().
_uncategorize()
void inventory_selector::_uncategorize (inventory_column & col) private
Definition at line 3145 of file inventory_ui.cpp.
 {
     for( inventory_entry *entry : col.get_entries( return_item, true ) ) {
         // find the topmost parent of the entry's item and categorize it by that
         // to form the hierarchy
         item_location ancestor = entry->any_item();
         while( ancestor.has_parent() ) {
             ancestor = ancestor.parent_item();
         }
         const item_category *custom_category = nullptr;
         if( ancestor.where() != item_location::type::character ) {
             const std::string name = to_upper_case( remove_color_tags( ancestor.describe() ) );
             const item_category map_cat( name, no_translation( name ), translation(), 100 );
             custom_category = naturalize_category( map_cat, ancestor.position() );
         } else {
             custom_category = wielded_worn_category( ancestor, u );
         }
         entry->set_custom_category( custom_category );
     }
     col.clear_indent_entries_override();
     col.invalidate_paging();
     col.uncollate();
 }
References item_location::character, inventory_column::clear_indent_entries_override(), item_location::describe(), inventory_column::get_entries(), item_location::has_parent(), inventory_column::invalidate_paging(), om_direction::name(), naturalize_category(), no_translation(), item_location::parent_item(), item_location::position(), remove_color_tags(), anonymous_namespace{inventory_ui.cpp}::return_item(), to_upper_case(), u, inventory_column::uncollate(), item_location::where(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
Referenced by toggle_categorize_contained().
action_bound_to_key()
std::string inventory_selector::action_bound_to_key (char key) const
Definition at line 3272 of file inventory_ui.cpp.
 {
     return ctxt.input_to_action( input_event( key, input_event_t::keyboard_char ) );
 }
References ctxt, input_context::input_to_action(), and keyboard_char.
Referenced by inventory::assign_empty_invlet().
action_examine()
void inventory_selector::action_examine (const item_location & sitem) protected
Show detailed item information for the selected item.
Called from on_input() after user input of EXAMINE action. Also called from on_input() on action EXAMINE_CONTENTS if sitem has no contents
Parameters
sitem the item to examine
Definition at line 3457 of file inventory_ui.cpp.
 {
     // Code below pulled from the action_examine function in advanced_inv.cpp
     std::vector<iteminfo> vThisItem;
     std::vector<iteminfo> vDummy;
     sitem->info( true, vThisItem );
     vThisItem.insert( vThisItem.begin(),
     { {}, string_format( _( "Location: %s" ), sitem.describe( &u ) ) } );
     item_info_data data( sitem->tname(), sitem->type_name(), vThisItem, vDummy );
     data.handle_scrolling = true;
     draw_item_info( [&]() -> catacurses::window {
         int maxwidth = std::max( FULL_SCREEN_WIDTH, TERMX );
         int width = std::min( 80, maxwidth );
         return catacurses::newwin( 0, width, point( maxwidth / 2 - width / 2, 0 ) ); },
     data ).get_first_input();
 }
References _, item_location::describe(), item::info(), string_format(), and u.
Referenced by on_input().
add_basecamp_items()
void inventory_selector::add_basecamp_items (const basecamp & camp)
Definition at line 2174 of file inventory_ui.cpp.
 {
     std::unordered_set<tripoint_abs_ms> tiles = camp.get_storage_tiles();
     map &here = get_map();
     for( tripoint_abs_ms tile : tiles ) {
         add_map_items( here.bub_from_abs( tile ).raw() );
     }
 }
References add_map_items(), map::bub_from_abs(), get_map(), basecamp::get_storage_tiles(), and coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by basecamp::give_basecamp_equipment().
add_character_items()
void inventory_selector::add_character_items (Character & character)
Definition at line 2079 of file inventory_ui.cpp.
 {
     item_location weapon = character.get_wielded_item();
     bool const hierarchy = _uimode == uimode::hierarchy;
     if( weapon ) {
         add_entry_rec( own_gear_column, hierarchy ? own_gear_column : own_inv_column, weapon,
                        &item_category_WEAPON_HELD.obj(),
                        hierarchy ? &item_category_WEAPON_HELD.obj() : nullptr );
     }
     for( item_location &worn_item : character.top_items_loc() ) {
         item_category const *const custom_cat = wielded_worn_category( worn_item, u );
         add_entry_rec( own_gear_column, hierarchy ? own_gear_column : own_inv_column, worn_item,
                        custom_cat, hierarchy ? custom_cat : nullptr );
     }
     if( !hierarchy ) {
         own_inv_column.set_indent_entries_override( false );
     }
 }
References _uimode, add_entry_rec(), Character::get_wielded_item(), hierarchy, item_category_WEAPON_HELD, string_id< T >::obj(), own_gear_column, own_inv_column, inventory_column::set_indent_entries_override(), Character::top_items_loc(), u, and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
Referenced by autodoc_internal(), game_menus::inv::common(), game_menus::inv::compare(), compare_recipe_with_item(), game_menus::inv::ebooksave(), inventory_pick_selector::execute(), unload_selector::execute(), basecamp::give_equipment(), game_menus::inv::holster(), inv_internal(), inv_internal_multi(), game_menus::inv::select_ammo(), game_menus::inv::smoke_food(), game_menus::inv::swap_letters(), game_menus::inv::unload_container(), and iuse::wash_items().
add_contained_ebooks()
void inventory_selector::add_contained_ebooks (item_location & container)
Definition at line 2067 of file inventory_ui.cpp.
 {
     if( !container->is_ebook_storage() ) {
         return;
     }
     for( item *it : container->get_contents().ebooks() ) {
         item_location child( container, it );
         add_entry( own_inv_column, std::vector<item_location>( 1, child ) );
     }
 }
References add_entry(), item_contents::ebooks(), item::get_contents(), item::is_ebook_storage(), and own_inv_column.
Referenced by game_menus::inv::ebookread().
add_contained_gunmods()
void inventory_selector::add_contained_gunmods (Character & you, item & gun)
Definition at line 2045 of file inventory_ui.cpp.
 {
     auto filter_irremovable = []( std::vector<item *> &gunmods ) {
         gunmods.erase(
             std::remove_if(
         gunmods.begin(), gunmods.end(), []( const item * i ) {
             return i->is_irremovable();
         } ),
         gunmods.end() );
     };
     std::vector<item *> mods = gun.gunmods();
     item_location gun_item_location( you, &gun );
     filter_irremovable( mods );
     for( item *mod : mods ) {
         item_location gunmod_item_location( gun_item_location, mod );
         add_entry( own_inv_column, std::vector<item_location>( 1, gunmod_item_location ) );
     }
 }
References add_entry(), gun, anonymous_namespace{item_tname.cpp}::mods(), and own_inv_column.
Referenced by game_menus::inv::gunmod_to_remove().
add_contained_items() [1/2]
bool inventory_selector::add_contained_items (item_location & container)
These functions add items from map / vehicles.
Definition at line 2012 of file inventory_ui.cpp.
 {
     return add_contained_items( container, own_inv_column );
 }
References own_inv_column.
Referenced by add_entry_rec(), game_menus::inv::common(), advanced_inventory::display(), inv_internal(), inv_internal_multi(), and on_input().
add_contained_items() [2/2]
bool inventory_selector::add_contained_items (item_location & container, inventory_column & column, const item_category * custom_category = nullptr, item_location const & topmost_parent = {}, int indent = 0)
Definition at line 2017 of file inventory_ui.cpp.
 {
     if( container->has_flag( STATIC( flag_id( "NO_UNLOAD" ) ) ) ) {
         return false;
     }
     std::list<item *> const items = preset.get_pocket_type() == pocket_type::LAST
                                     ? container->all_items_top()
                                     : container->all_items_top( preset.get_pocket_type() );
     bool vis_top = false;
     inventory_column temp( preset );
     for( item *it : items ) {
         item_location child( container, it );
         item_category const *hacked_cat = custom_category;
         inventory_column *hacked_col = &column;
         if( is_worn_ablative( container, child ) ) {
             hacked_cat = &item_category_ITEMS_WORN.obj();
             hacked_col = &own_gear_column;
         }
         vis_top |= add_entry_rec( *hacked_col, temp, child, hacked_cat, custom_category,
                                   topmost_parent, indent );
     }
     temp.move_entries_to( column );
     return vis_top;
 }
References add_entry_rec(), item::all_items_top(), flag_id, inventory_selector_preset::get_pocket_type(), item::has_flag(), is_worn_ablative(), item_category_ITEMS_WORN, LAST, string_id< T >::obj(), own_gear_column, preset, STATIC, and temp.
add_entry()
inventory_entry * inventory_selector::add_entry (inventory_column & target_column, std::vector< item_location > && locations, const item_category * custom_category = nullptr, size_t chosen_count = 0, item_location const & topmost_parent = {}, bool chevron = false) protected
Definition at line 1908 of file inventory_ui.cpp.
 {
     if( !preset.is_shown( locations.front() ) ) {
         return nullptr;
     }
     is_empty = false;
     inventory_entry entry( locations, custom_category,
                            true, chosen_count,
                            entry_generation_number++, topmost_parent, chevron );
     entry.collapsed = locations.front()->is_collapsed();
     inventory_entry *const ret = target_column.add_entry( entry );
     shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
     if( current_ui ) {
         current_ui->mark_resize();
     }
     return ret;
 }
References inventory_column::add_entry(), inventory_entry::collapsed, entry_generation_number, is_empty, inventory_selector_preset::is_shown(), anonymous_namespace{overmap_location.cpp}::locations, preset, and cata::hash64_detail::ret.
Referenced by add_contained_ebooks(), add_contained_gunmods(), and add_entry_rec().
add_entry_rec()
bool inventory_selector::add_entry_rec (inventory_column & entry_column, inventory_column & children_column, item_location & loc, item_category const * entry_category = nullptr, item_category const * children_category = nullptr, item_location const & topmost_parent = {}, int indent = 0) protected
Definition at line 1934 of file inventory_ui.cpp.
 {
     inventory_column temp_children( preset );
     bool vis_contents =
         add_contained_items( loc, temp_children, children_category,
                              get_topmost_parent( topmost_parent, loc, preset ),
                              preset.is_shown( loc ) ? indent + 2 : indent );
     inventory_entry *const nentry = add_entry( entry_column, std::vector<item_location>( 1, loc ),
                                     entry_category, 0, topmost_parent );
     if( nentry != nullptr ) {
         nentry->chevron = vis_contents;
         nentry->indent = indent;
         vis_contents = true;
     }
     temp_children.move_entries_to( children_column );
     return vis_contents;
 }
References add_contained_items(), add_entry(), inventory_entry::chevron, anonymous_namespace{inventory_ui.cpp}::get_topmost_parent(), inventory_entry::indent, inventory_selector_preset::is_shown(), inventory_column::move_entries_to(), and preset.
Referenced by _add_map_items(), add_character_items(), and add_contained_items().
add_map_items()
void inventory_selector::add_map_items (const tripoint & target)
Definition at line 2098 of file inventory_ui.cpp.
 {
     map &here = get_map();
     if( here.accessible_items( target ) ) {
         map_stack items = here.i_at( target );
         const std::string name = to_upper_case( here.name( target ) );
         const item_category map_cat( name, no_translation( name ), translation(), 100 );
         _add_map_items( target, map_cat, items, [target]( item & it ) {
             return item_location( map_cursor( target ), &it );
         } );
     }
 }
References _add_map_items(), map::accessible_items(), get_map(), map::i_at(), map::name(), om_direction::name(), no_translation(), and to_upper_case().
Referenced by add_basecamp_items(), add_nearby_items(), game_menus::inv::compare(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), haul(), and game_menus::inv::pickup().
add_nearby_items()
void inventory_selector::add_nearby_items (int radius = 1)
Definition at line 2149 of file inventory_ui.cpp.
 {
     if( radius >= 0 ) {
         map &here = get_map();
         for( const tripoint &pos : closest_points_first( u.pos(), radius ) ) {
             // can not reach this -> can not access its contents
             if( u.pos() != pos && !here.clear_path( u.pos(), pos, rl_dist( u.pos(), pos ), 1, 100 ) ) {
                 continue;
             }
             add_map_items( pos );
             add_vehicle_items( pos );
         }
     }
 }
References add_map_items(), add_vehicle_items(), map::clear_path(), closest_points_first(), get_map(), Creature::pos(), math_opers::pos(), rl_dist(), and u.
Referenced by autodoc_internal(), game_menus::inv::compare(), game_menus::inv::ebooksave(), basecamp::give_equipment(), game_menus::inv::holster(), inv_internal(), inv_internal_multi(), game_menus::inv::pickup(), game_menus::inv::select_ammo(), game_menus::inv::smoke_food(), game_menus::inv::unload_container(), and iuse::wash_items().
add_remote_map_items()
void inventory_selector::add_remote_map_items (tinymap * remote_map, const tripoint & target)
Definition at line 2164 of file inventory_ui.cpp.
 {
     map_stack items = remote_map->i_at( target );
     const std::string name = to_upper_case( remote_map->name( target ) );
     const item_category map_cat( name, no_translation( name ), translation(), 100 );
     _add_map_items( target, map_cat, items, [target]( item & it ) {
         return item_location( map_cursor( target ), &it );
     } );
 }
References _add_map_items(), tinymap::i_at(), tinymap::name(), om_direction::name(), no_translation(), and to_upper_case().
Referenced by basecamp::get_equipment().
add_vehicle_items()
void inventory_selector::add_vehicle_items (const tripoint & target)
Definition at line 2111 of file inventory_ui.cpp.
 {
     const std::optional<vpart_reference> ovp = get_map().veh_at( target ).cargo();
     if( !ovp ) {
         return;
     }
     vehicle_part &vp = ovp->part();
     vehicle_stack items = ovp->items();
     const std::string name = to_upper_case( remove_color_tags( vp.name() ) );
     const item_category vehicle_cat( name, no_translation( name ), translation(), 200 );
     const vehicle_cursor cursor( ovp->vehicle(), ovp->part_index() );
     _add_map_items( target, vehicle_cat, items, [&cursor]( item & it ) {
         return item_location( cursor, &it );
     } );
 }
References _add_map_items(), optional_vpart_position::cargo(), get_map(), item_stack::items, vehicle_part::name(), om_direction::name(), no_translation(), remove_color_tags(), to_upper_case(), and map::veh_at().
Referenced by add_nearby_items(), game_menus::inv::compare(), and game_menus::inv::pickup().
append_column()
void inventory_selector::append_column (inventory_column & column) protected
Definition at line 3251 of file inventory_ui.cpp.
 {
     column.on_mode_change( mode );
     if( columns.empty() ) {
         column.on_activate();
     }
     columns.push_back( &column );
 }
References columns, mode, inventory_column::on_activate(), and inventory_column::on_mode_change().
Referenced by inventory_multiselector::inventory_multiselector(), and inventory_selector().
are_columns_centered()
bool inventory_selector::are_columns_centered (size_t client_width) const protected
Returns
Do the visible columns need to be center-aligned
Definition at line 3120 of file inventory_ui.cpp.
 {
     return get_columns_occupancy_ratio( client_width ) >= min_ratio_to_center;
 }
References get_columns_occupancy_ratio(), and min_ratio_to_center.
Referenced by draw_columns(), and prepare_layout().
categorize_map_items()
void inventory_selector::categorize_map_items (bool toggle)
Definition at line 4594 of file inventory_ui.cpp.
 {
     _categorize_map_items = toggle;
 }
References _categorize_map_items.
clear_items()
void inventory_selector::clear_items ()
Remove all items.
Definition at line 2183 of file inventory_ui.cpp.
 {
     is_empty = true;
     for( inventory_column *&column : columns ) {
         column->clear();
     }
     own_inv_column.clear();
     own_gear_column.clear();
     map_column.clear();
 }
References inventory_column::clear(), columns, is_empty, map_column, own_gear_column, and own_inv_column.
Referenced by autodoc_internal(), game_menus::inv::common(), game_menus::inv::ebookread(), inventory_pick_selector::execute(), unload_selector::execute(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), game_menus::inv::gunmod_to_remove(), inv_internal(), inv_internal_multi(), and game_menus::inv::select_ammo().
create_or_get_ui_adaptor()
shared_ptr_fast< ui_adaptor > inventory_selector::create_or_get_ui_adaptor () protected
Definition at line 2413 of file inventory_ui.cpp.
 {
     shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
     if( !current_ui ) {
         ui = current_ui = make_shared_fast<ui_adaptor>();
         current_ui->on_screen_resize( [this]( ui_adaptor & ) {
             prepare_layout();
         } );
         current_ui->mark_resize();
         current_ui->on_redraw( [this]( const ui_adaptor & ) {
             refresh_window();
         } );
     }
     return current_ui;
 }
References prepare_layout(), and refresh_window().
Referenced by inventory_pick_selector::execute(), ammo_inventory_selector::execute(), inventory_compare_selector::execute(), inventory_drop_selector::execute(), pickup_selector::execute(), unload_selector::execute(), inventory_examiner::execute(), inventory_multiselector::execute(), and trade_selector::trade_selector().
drag_drop_item()
bool inventory_selector::drag_drop_item (item * sourceItem, item * destItem) protected
Definition at line 1957 of file inventory_ui.cpp.
 {
     if( sourceItem == destItem ) {
         return false;
     }
     auto pockets = destItem->get_all_contained_pockets();
     if( pockets.empty() ) {
         popup( _( "Destination has no pockets." ) );
         return false;
     }
     int base_move_cost = 0;
     auto parentContainers = u.parents( *sourceItem );
     for( item *parent : parentContainers ) {
         base_move_cost += parent->obtain_cost( *sourceItem );
     }
     std::vector<item_pocket *> containable_pockets;
     uilist action_menu;
     action_menu.text = _( "Select pocket" );
     int index = 0;
     bool any_containable = false;
     for( item_pocket *pocket : pockets ) {
         std::string pocket_text = string_format( _( "%s - %s/%s | %d moves" ),
                                   pocket->get_description().translated(), vol_to_info( "", "", pocket->contains_volume() ).sValue,
                                   vol_to_info( "", "", pocket->max_contains_volume() ).sValue, pocket->moves() + base_move_cost );
         action_menu.addentry( index++, true, std::optional<input_event>(), pocket_text );
         ret_val<item_pocket::contain_code> contain = pocket->can_contain( *sourceItem );
         if( contain.success() ) {
             any_containable = true;
         } else {
             action_menu.entries.back().enabled = false;
         }
     }
     if( !any_containable ) {
         tname::segment_bitset segs( tname::unprefixed_tname );
         segs.set( tname::segments::CONTENTS, false );
         popup( string_format( _( "%s contains no pockets that can contain item." ),
                               destItem->tname( 1, segs ) ) );
         return false;
     }
     action_menu.query();
     if( action_menu.ret >= 0 && static_cast<size_t>( action_menu.ret ) < pockets.size() ) {
         ret_val<item_pocket::contain_code> contain = pockets[action_menu.ret]->can_contain( *sourceItem );
         if( contain.success() ) {
             // storage should mimick character inserting
             u.store( pockets[action_menu.ret], *sourceItem, true, base_move_cost );
             return true;
         } else {
             popup( _( "Cannot put item in pocket: %s" ), contain.str() );
             return false;
         }
     }
     return false;
 }
References _, uilist::addentry(), tname::CONTENTS, uilist::entries, item::get_all_contained_pockets(), visitable::parents(), popup(), uilist::query(), uilist::ret, enum_bitset< E >::set(), Character::store(), ret_val_common::str(), string_format(), ret_val_common::success(), iteminfo::sValue, uilist::text, item::tname(), u, tname::unprefixed_tname(), and vol_to_info().
Referenced by inventory_pick_selector::execute(), and unload_selector::execute().
draw_columns()
void inventory_selector::draw_columns (const catacurses::window & w) private
Definition at line 2722 of file inventory_ui.cpp.
 {
     const auto columns = get_visible_columns();
     const int screen_width = getmaxx( w ) - 2 * ( border + 1 );
     const bool centered = are_columns_centered( screen_width );
     const int free_space = screen_width - get_columns_width( columns );
     const int max_gap = ( columns.size() > 1 ) ? free_space / ( static_cast<int>
                         ( columns.size() ) - 1 ) :
                         free_space;
     const int gap = centered ? max_gap : std::min<int>( max_gap, normal_column_gap );
     const int gap_rounding_error = centered && columns.size() > 1
                                    ? free_space % ( columns.size() - 1 ) : 0;
     size_t x = border + 1;
     size_t y = get_header_height() + border + 1;
     size_t active_x = 0;
     rect_entry_map.clear();
     for( inventory_column * const &elem : columns ) {
         if( &elem == &columns.back() ) {
             x += gap_rounding_error;
         }
         if( !is_active_column( *elem ) ) {
             elem->draw( w, point( x, y ), rect_entry_map );
         } else {
             active_x = x;
         }
         x += elem->get_width() + gap;
     }
     get_active_column().draw( w, point( active_x, y ), rect_entry_map );
     if( empty() ) {
         center_print( w, getmaxy( w ) / 2, c_dark_gray, _( "Your inventory is empty." ) );
     }
 }
References _, are_columns_centered(), border, c_dark_gray, center_print(), columns, inventory_column::draw(), empty(), get_active_column(), get_columns_width(), get_header_height(), get_visible_columns(), catacurses::getmaxx(), catacurses::getmaxy(), is_active_column(), normal_column_gap, point, and rect_entry_map.
Referenced by refresh_window().
draw_footer()
void inventory_selector::draw_footer (const catacurses::window & w) const private
Definition at line 2778 of file inventory_ui.cpp.
 {
     if( spopup ) {
         mvwprintz( w_inv, point( 2, getmaxy( w_inv ) - 1 ), c_cyan, "< " );
         mvwprintz( w_inv, point( ( getmaxx( w_inv ) / 2 ) - 4, getmaxy( w_inv ) - 1 ), c_cyan, " >" );
         spopup->query_string( /*loop=*/false, /*draw_only=*/true );
     } else {
         int filter_offset = 0;
         if( has_available_choices() || !filter.empty() ) {
             std::string text = string_format( filter.empty() ? _( "[%s] Filter" ) : _( "[%s] Filter: " ),
                                               ctxt.get_desc( "INVENTORY_FILTER" ) );
             filter_offset = utf8_width( text + filter ) + 6;
             mvwprintz( w, point( 2, getmaxy( w ) - border ), c_light_gray, "< " );
             wprintz( w, c_light_gray, text );
             wprintz( w, c_white, filter );
             wprintz( w, c_light_gray, " >" );
         }
         right_print( w, getmaxy( w ) - border, border + 1, c_light_gray,
                      string_format( "< [%s] %s >", ctxt.get_desc( "VIEW_CATEGORY_MODE" ),
                                     io::enum_to_string( _uimode ) ) );
         const auto footer = get_footer( mode );
         if( !footer.first.empty() ) {
             const int string_width = utf8_width( footer.first );
             const int x1 = filter_offset + std::max( getmaxx( w ) - string_width - filter_offset, 0 ) / 2;
             const int x2 = x1 + string_width - 1;
             const int y = getmaxy( w ) - border;
             mvwprintz( w, point( x1, y ), footer.second, footer.first );
             mvwputch( w, point( x1 - 1, y ), c_light_gray, ' ' );
             mvwputch( w, point( x2 + 1, y ), c_light_gray, ' ' );
             mvwputch( w, point( x1 - 2, y ), c_light_gray, LINE_XOXX );
             mvwputch( w, point( x2 + 2, y ), c_light_gray, LINE_XXXO );
         }
     }
 }
References _, _uimode, border, c_cyan, c_light_gray, c_white, ctxt, io::enum_to_string(), filter, input_context::get_desc(), get_footer(), catacurses::getmaxx(), catacurses::getmaxy(), has_available_choices(), LINE_XOXX, LINE_XXXO, max(), mode, mvwprintz(), mvwputch(), point, right_print(), spopup, string_format(), utf8_width(), w_inv, and wprintz().
Referenced by refresh_window().
draw_frame()
void inventory_selector::draw_frame (const catacurses::window & w) const private
Definition at line 2760 of file inventory_ui.cpp.
 {
     draw_border( w );
     const int y = border + get_header_height();
     mvwhline( w, point( 0, y ), LINE_XXXO, 1 );
     mvwhline( w, point( getmaxx( w ) - border, y ), LINE_XOXX, 1 );
 }
References border, draw_border(), get_header_height(), catacurses::getmaxx(), LINE_XOXX, LINE_XXXO, catacurses::mvwhline(), and point.
Referenced by refresh_window().
draw_header()
void inventory_selector::draw_header (const catacurses::window & w) const private
Definition at line 2489 of file inventory_ui.cpp.
 {
     trim_and_print( w, point( border + 1, border ), getmaxx( w ) - 2 * ( border + 1 ), c_white, title );
     fold_and_print( w, point( border + 1, border + 1 ), getmaxx( w ) - 2 * ( border + 1 ), c_dark_gray,
                     hint );
     int const bottom = border + get_header_height();
     mvwhline( w, point( border, bottom ), LINE_OXOX, getmaxx( w ) - 2 * border );
     if( display_stats ) {
         size_t y = border;
         for( const std::string &elem : get_stats() ) {
             right_print( w, y++, border + 1, c_dark_gray, elem );
         }
     }
     if( uistate.numpad_navigation ) {
         right_print( w, bottom, border + 1, c_dark_gray, _( "Numpad ON" ) );
     }
 }
References _, border, c_dark_gray, c_white, display_stats, fold_and_print(), get_header_height(), get_stats(), catacurses::getmaxx(), hint, LINE_OXOX, catacurses::mvwhline(), uistatedata::numpad_navigation, point, right_print(), title, trim_and_print(), and uistate.
Referenced by refresh_window().
empty()
bool inventory_selector::empty () const
Returns
true when the selector is empty.
Definition at line 2885 of file inventory_ui.cpp.
 {
     return is_empty;
 }
References is_empty.
Referenced by autodoc_internal(), inventory_examiner::check_parent_item(), game_menus::inv::compare(), compare_recipe_with_item(), draw_columns(), game_menus::inv::ebookread(), game_menus::inv::ebooksave(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), basecamp::get_equipment(), basecamp::give_basecamp_equipment(), basecamp::give_equipment(), game_menus::inv::gunmod_to_remove(), inv_internal(), inv_internal_multi(), game_menus::inv::pickup(), game_menus::inv::select_ammo(), game_menus::inv::smoke_food(), game_menus::inv::swap_letters(), and iuse::wash_items().
find_entry_by_coordinate()
inventory_entry * inventory_selector::find_entry_by_coordinate (const point & coordinate) const protected
Definition at line 2274 of file inventory_ui.cpp.
 {
     for( auto pair : rect_entry_map ) {
         if( pair.first.contains( coordinate ) ) {
             return pair.second;
         }
     }
     return nullptr;
 }
References rect_entry_map.
Referenced by process_input().
find_entry_by_invlet()
inventory_entry * inventory_selector::find_entry_by_invlet (int invlet) const protected
Returns
an entry from all entries by its invlet
Definition at line 2263 of file inventory_ui.cpp.
 {
     for( const inventory_column *elem : columns ) {
         inventory_entry *const res = elem->find_by_invlet( invlet );
         if( res != nullptr ) {
             return res;
         }
     }
     return nullptr;
 }
References columns.
Referenced by process_input().
find_entry_by_location()
inventory_entry * inventory_selector::find_entry_by_location (item_location & loc) const protected
Definition at line 2284 of file inventory_ui.cpp.
 {
     for( const inventory_column *elem : columns ) {
         if( elem->allows_selecting() ) {
             inventory_entry *const res = elem->find_by_location( loc );
             if( res != nullptr ) {
                 return res;
             }
         }
     }
     return nullptr;
 }
References columns.
Referenced by pickup_selector::apply_selection(), and inventory_haul_selector::apply_selection().
get_active_column()
inventory_column& inventory_selector::get_active_column () const inline
Definition at line 832 of file inventory_ui.h.
{
             return get_column( active_column_index );
         }
References active_column_index, and get_column().
Referenced by draw_columns(), inventory_pick_selector::execute(), ammo_inventory_selector::execute(), inventory_compare_selector::execute(), unload_selector::execute(), inventory_examiner::execute(), trade_selector::execute(), get_collation_next(), get_highlighted(), get_highlighted_position(), highlight(), highlight_position(), is_active_column(), on_input(), inventory_multiselector::on_input(), prepare_layout(), refresh_active_column(), set_active_column(), inventory_multiselector::toggle_entries(), pickup_selector::wear(), and pickup_selector::wield().
get_all_columns()
const std::vector<inventory_column *>& inventory_selector::get_all_columns () const inline protected
Definition at line 759 of file inventory_ui.h.
{
             return columns;
         }
References columns.
Referenced by inventory_multiselector::deselect_contained_items(), inventory_insert_selector::get_raw_stats(), highlight(), inventory_multiselector::inventory_multiselector(), and inventory_multiselector::toggle_categorize_contained().
get_collation_next()
item_location inventory_selector::get_collation_next () const
Definition at line 2230 of file inventory_ui.cpp.
 {
     inventory_column &col = get_active_column();
     inventory_entry &ent = col.get_highlighted();
     if( !ent.is_collated() ) {
         return {};
     }
     if( ent.is_collation_header() ) {
         return ent.locations.front();
     }
     item_location const &loc_cur = ent.locations.front();
     inventory_entry const &p_ent = *col.find_by_location( ent.collation_meta->tip );
     auto iter = std::find( p_ent.locations.begin(), p_ent.locations.end(), loc_cur );
     if( iter == --p_ent.locations.end() ) {
         return *--iter;
     }
     return *++iter;
 }
References inventory_entry::collation_meta, inventory_column::find_by_location(), get_active_column(), inventory_column::get_highlighted(), inventory_entry::is_collated(), inventory_entry::is_collation_header(), and inventory_entry::locations.
Referenced by inv_internal().
get_column()
inventory_column & inventory_selector::get_column (size_t index) const
Definition at line 3078 of file inventory_ui.cpp.
 {
     if( index >= columns.size() ) {
         static inventory_column dummy( preset );
         return dummy;
     }
     return *columns[index];
 }
References columns, and preset.
Referenced by get_active_column(), set_active_column(), and toggle_active_column().
get_columns_occupancy_ratio()
double inventory_selector::get_columns_occupancy_ratio (size_t client_width) const protected
Returns
Percentage of the window occupied by columns
Definition at line 3112 of file inventory_ui.cpp.
 {
     const auto visible_columns = get_visible_columns();
     const int free_width = client_width - get_columns_width( visible_columns )
                            - min_column_gap * std::max( static_cast<int>( visible_columns.size() ) - 1, 0 );
     return 1.0 - static_cast<double>( free_width ) / client_width;
 }
References get_columns_width(), get_visible_columns(), max(), and min_column_gap.
Referenced by are_columns_centered(), and is_overflown().
get_columns_width()
size_t inventory_selector::get_columns_width (const std::vector< inventory_column * > & columns) const protected
Definition at line 3104 of file inventory_ui.cpp.
 {
     return std::accumulate( columns.begin(), columns.end(), static_cast< size_t >( 0 ),
     []( const size_t &lhs, const inventory_column * column ) {
         return lhs + column->get_width();
     } );
 }
References columns.
Referenced by draw_columns(), get_columns_occupancy_ratio(), and get_layout_width().
get_filter()
std::string inventory_selector::get_filter () const
Get last filter string set by set_filter or entered by player.
Definition at line 2717 of file inventory_ui.cpp.
 {
     return filter;
 }
References filter.
Referenced by game_menus::inv::common(), and inv_internal().
get_footer()
std::pair< std::string, nc_color > inventory_selector::get_footer (navigation_mode m) const protected
Definition at line 2769 of file inventory_ui.cpp.
 {
     if( has_available_choices() ) {
         return std::make_pair( get_navigation_data( m ).name.translated(),
                                get_navigation_data( m ).color );
     }
     return std::make_pair( _( "There are no available choices" ), i_red );
 }
References _, color(), get_navigation_data(), has_available_choices(), i_red, and om_direction::name().
Referenced by draw_footer(), and get_footer_min_width().
get_footer_min_width()
size_t inventory_selector::get_footer_min_width () const protected
Definition at line 2475 of file inventory_ui.cpp.
 {
     size_t result = 0;
     navigation_mode m = mode;
     do {
         result = std::max( static_cast<size_t>( utf8_width( get_footer( m ).first, true ) ) + 2 + 4,
                            result );
         m = get_navigation_data( m ).next_mode;
     } while( m != mode );
     return result;
 }
References get_footer(), get_navigation_data(), max(), mode, navigation_mode_data::next_mode, and utf8_width().
Referenced by get_layout_width().
get_header_height()
size_t inventory_selector::get_header_height () const protected
Definition at line 2452 of file inventory_ui.cpp.
 {
     return display_stats || !hint.empty()
            ? std::max<size_t>( 3, 2 + std::count( hint.begin(), hint.end(), '\n' ) )
            : 1;
 }
References display_stats, and hint.
Referenced by draw_columns(), draw_frame(), draw_header(), and prepare_layout().
get_header_min_width()
size_t inventory_selector::get_header_min_width () const protected
Definition at line 2459 of file inventory_ui.cpp.
 {
     const size_t titles_width = std::max( utf8_width( title, true ),
                                           utf8_width( hint, true ) );
     if( !display_stats ) {
         return titles_width;
     }
     size_t stats_width = 0;
     for( const std::string &elem : get_stats() ) {
         stats_width = std::max( static_cast<size_t>( utf8_width( elem, true ) ), stats_width );
     }
     return titles_width + stats_width + ( stats_width != 0 ? 3 : 0 );
 }
References display_stats, get_stats(), hint, max(), title, and utf8_width().
Referenced by get_layout_width().
get_highlighted()
const inventory_entry& inventory_selector::get_highlighted () const inline
Definition at line 810 of file inventory_ui.h.
{
             return get_active_column().get_highlighted();
         }
References get_active_column(), and inventory_column::get_highlighted().
Referenced by inv_internal(), on_input(), rearrange_columns(), and toggle_categorize_contained().
get_highlighted_position()
std::pair<size_t, size_t> inventory_selector::get_highlighted_position () const inline
Definition at line 824 of file inventory_ui.h.
{
             std::pair<size_t, size_t> position;
             position.first = active_column_index;
             position.second = get_active_column().get_highlighted_index();
             return position;
         }
References active_column_index, get_active_column(), and inventory_column::get_highlighted_index().
Referenced by inv_internal().
get_holster_stat()
inventory_selector::stat inventory_selector::get_holster_stat (const units::volume & holster_volume, int used_holsters, int total_holsters) static protected
Definition at line 2544 of file inventory_ui.cpp.
 {
     std::string holster_caption = string_format( _( "Free Holster Volume (%s): %s Used Holsters:" ),
                                   volume_units_abbr(),
                                   colorize( format_volume( holster_volume ), c_light_gray ) );
     return display_stat( holster_caption, used_holsters, total_holsters, []( int v ) {
         return string_format( "%d", v );
     } );
 }
References _, c_light_gray, colorize(), display_stat(), format_volume(), string_format(), and volume_units_abbr().
Referenced by get_weight_and_volume_and_holster_stats().
get_input()
inventory_input inventory_selector::get_input () protected
Definition at line 2924 of file inventory_ui.cpp.
 {
     std::string const &action = ctxt.handle_input();
     int const ch = ctxt.get_raw_input().get_first_input();
     return process_input( action, ch );
 }
References action, ctxt, input_event::get_first_input(), input_context::get_raw_input(), input_context::handle_input(), and process_input().
Referenced by inventory_pick_selector::execute(), ammo_inventory_selector::execute(), inventory_compare_selector::execute(), inventory_drop_selector::execute(), pickup_selector::execute(), unload_selector::execute(), inventory_examiner::execute(), and inventory_multiselector::execute().
get_layout_height()
size_t inventory_selector::get_layout_height () const protected
Definition at line 2440 of file inventory_ui.cpp.
 {
     const auto visible_columns = get_visible_columns();
     // Find and return the highest column's height.
     const auto iter = std::max_element( visible_columns.begin(), visible_columns.end(),
     []( const inventory_column * lhs, const inventory_column * rhs ) {
         return lhs->get_height() < rhs->get_height();
     } );
     return iter != visible_columns.end() ? ( *iter )->get_height() : 1;
 }
References get_visible_columns().
Referenced by prepare_layout().
get_layout_width()
size_t inventory_selector::get_layout_width () const protected
Definition at line 2430 of file inventory_ui.cpp.
 {
     const size_t min_hud_width = std::max( get_header_min_width(), get_footer_min_width() );
     const auto visible_columns = get_visible_columns();
     const size_t gaps = visible_columns.size() > 1 ? normal_column_gap * ( visible_columns.size() - 1 )
                         : 0;
     return std::max( get_columns_width( visible_columns ) + gaps, min_hud_width );
 }
References get_columns_width(), get_footer_min_width(), get_header_min_width(), get_visible_columns(), max(), and normal_column_gap.
Referenced by prepare_layout().
get_navigation_data()
const navigation_mode_data & inventory_selector::get_navigation_data (navigation_mode m) const protected
Definition at line 3262 of file inventory_ui.cpp.
 {
     static const std::map<navigation_mode, navigation_mode_data> mode_data = {
         { navigation_mode::ITEM,     { navigation_mode::CATEGORY, translation(),                               c_light_gray } },
         { navigation_mode::CATEGORY, { navigation_mode::ITEM,     to_translation( "Category selection mode" ), h_white  } }
     };
     return mode_data.at( m );
 }
References c_light_gray, CATEGORY, h_white, ITEM, and to_translation().
Referenced by get_footer(), get_footer_min_width(), and toggle_navigation_mode().
get_only_choice()
drop_location inventory_selector::get_only_choice () const
Definition at line 2907 of file inventory_ui.cpp.
 {
     if( item_entry_count() != 1 ) {
         debugmsg( "inventory_selector::get_only_choice called with more that one choice" );
         return drop_location();
     }
     for( const inventory_column *col : columns ) {
         const std::vector<inventory_entry *> ent = col->get_entries( return_item, true );
         if( !ent.empty() ) {
             return { ent.front()->any_item(), static_cast<int>( ent.front()->get_available_count() ) };
         }
     }
     return drop_location();
 }
References columns, debugmsg, item_entry_count(), and anonymous_namespace{inventory_ui.cpp}::return_item().
Referenced by game_menus::inv::select_ammo().
get_raw_stats()
inventory_selector::stats inventory_selector::get_raw_stats () const protected virtual
Get stats to display in top right.
By default, computes volume/weight numbers for u
Reimplemented in pickup_selector, inventory_insert_selector, inventory_drop_selector, inventory_multiselector, and container_inventory_selector.
Definition at line 2571 of file inventory_ui.cpp.
 {
     return get_weight_and_volume_and_holster_stats( u.weight_carried(), u.weight_capacity(),
             u.volume_carried(), u.volume_capacity(),
             u.max_single_item_length(), u.max_single_item_volume(),
             u.free_holster_volume(), u.used_holsters(), u.total_holsters() );
 }
References Character::free_holster_volume(), get_weight_and_volume_and_holster_stats(), Character::max_single_item_length(), Character::max_single_item_volume(), Character::total_holsters(), u, Character::used_holsters(), Character::volume_capacity(), Character::volume_carried(), Character::weight_capacity(), and Character::weight_carried().
Referenced by get_stats().
get_stats()
std::vector< std::string > inventory_selector::get_stats () const protected
Definition at line 2579 of file inventory_ui.cpp.
 {
     // Stats consist of arrays of cells.
     const size_t num_stats = 3;
     const std::array<stat, num_stats> stats = get_raw_stats();
     // Streams for every stat.
     std::array<std::string, num_stats> lines;
     std::array<size_t, num_stats> widths;
     // Add first cells and spaces after them.
     for( size_t i = 0; i < stats.size(); ++i ) {
         lines[i] += string_format( "%s", stats[i][0] ) + " ";
     }
     // Now add the rest of the cells and align them to the right.
     for( size_t j = 1; j < stats.front().size(); ++j ) {
         // Calculate actual cell width for each stat.
         std::transform( stats.begin(), stats.end(), widths.begin(),
         [j]( const stat & elem ) {
             return utf8_width( elem[j], true );
         } );
         // Determine the max width.
         const size_t max_w = *std::max_element( widths.begin(), widths.end() );
         // Align all stats in this cell with spaces.
         for( size_t i = 0; i < stats.size(); ++i ) {
             if( max_w > widths[i] ) {
                 lines[i] += std::string( max_w - widths[i], ' ' );
             }
             lines[i] += string_format( "%s", stats[i][j] );
         }
     }
     // Construct the final result.
     return std::vector<std::string>( lines.begin(), lines.end() );
 }
References get_raw_stats(), om_direction::size, and string_format().
Referenced by draw_header(), and get_header_min_width().
get_visible_columns()
std::vector< inventory_column * > inventory_selector::get_visible_columns () const protected
Definition at line 3067 of file inventory_ui.cpp.
 {
     std::vector<inventory_column *> res( columns.size() );
     const auto iter = std::copy_if( columns.begin(), columns.end(), res.begin(),
     []( const inventory_column * e ) {
         return e->visible();
     } );
     res.resize( std::distance( res.begin(), iter ) );
     return res;
 }
References columns.
Referenced by draw_columns(), get_columns_occupancy_ratio(), get_layout_height(), get_layout_width(), and prepare_layout().
get_volume_stat()
inventory_selector::stat inventory_selector::get_volume_stat (const units::volume & volume_carried, const units::volume & volume_capacity, const units::volume & largest_free_volume) static protected
Definition at line 2532 of file inventory_ui.cpp.
 {
     std::string volume_caption = string_format( _( "Free Volume (%s): %s Volume (%s):" ),
                                  volume_units_abbr(),
                                  colorize( format_volume( largest_free_volume ), c_light_gray ),
                                  volume_units_abbr() );
     return display_stat( volume_caption, units::to_milliliter( volume_carried ),
     units::to_milliliter( volume_capacity ), []( int v ) {
         return format_volume( units::from_milliliter( v ) );
     } );
 }
References _, c_light_gray, colorize(), display_stat(), format_volume(), units::from_milliliter(), string_format(), units::to_milliliter(), and volume_units_abbr().
Referenced by get_weight_and_volume_and_holster_stats().
get_weight_and_length_stat()
inventory_selector::stat inventory_selector::get_weight_and_length_stat (units::mass weight_carried, units::mass weight_capacity, const units::length & longest_length) static protected
Definition at line 2520 of file inventory_ui.cpp.
 {
     std::string length_weight_caption = string_format( _( "Longest Length (%s): %s Weight (%s):" ),
                                         length_units( longest_length ), colorize( std::to_string( convert_length( longest_length ) ),
                                                 c_light_gray ), weight_units() );
     return display_stat( length_weight_caption, to_gram( weight_carried ),
     to_gram( weight_capacity ), []( int w ) {
         return string_format( "%.1f", round_up( convert_weight( units::from_gram( w ) ), 1 ) );
     } );
 }
References _, c_light_gray, colorize(), convert_length(), convert_weight(), display_stat(), units::from_gram(), units::length_units, round_up(), string_format(), units::to_gram(), to_string(), and weight_units().
Referenced by get_weight_and_volume_and_holster_stats().
get_weight_and_volume_and_holster_stats()
inventory_selector::stats inventory_selector::get_weight_and_volume_and_holster_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume & volume_carried, const units::volume & volume_capacity, const units::length & longest_length, const units::volume & largest_free_volume, const units::volume & holster_volume, int used_holsters, int total_holsters) static protected
Definition at line 2557 of file inventory_ui.cpp.
 {
     return { {
             get_weight_and_length_stat( weight_carried, weight_capacity, longest_length ),
             get_volume_stat( volume_carried, volume_capacity, largest_free_volume ),
             get_holster_stat( holster_volume, used_holsters, total_holsters )
         }
     };
 }
References get_holster_stat(), get_volume_stat(), and get_weight_and_length_stat().
Referenced by get_raw_stats(), container_inventory_selector::get_raw_stats(), inventory_drop_selector::get_raw_stats(), inventory_insert_selector::get_raw_stats(), and pickup_selector::get_raw_stats().
has_available_choices()
bool inventory_selector::has_available_choices () const
Returns
true when there are enabled entries to select.
Definition at line 2890 of file inventory_ui.cpp.
 {
     return std::any_of( columns.begin(), columns.end(), []( const inventory_column * element ) {
         return element->has_available_choices();
     } );
 }
References columns.
Referenced by draw_footer(), and get_footer().
highlight() [1/2]
void inventory_selector::highlight () protected
Highlight parent and contents of highlighted item.
Definition at line 3476 of file inventory_ui.cpp.
 {
     const inventory_entry &selected = get_active_column().get_highlighted();
     if( !selected.is_item() ) {
         return;
     }
     item_location parent = item_location::nowhere;
     bool selected_has_parent = false;
     if( selected.is_item() && selected.any_item().has_parent() ) {
         parent = selected.any_item().parent_item();
         selected_has_parent = true;
     }
     for( const inventory_column *column : get_all_columns() ) {
         for( inventory_entry *entry : column->get_entries( return_item ) ) {
             // Find parent of selected.
             if( selected_has_parent ) {
                 // Check if parent is in a stack.
                 for( const item_location &test_loc : entry->locations ) {
                     if( test_loc == parent ) {
                         entry->highlight_as_parent = true;
                         break;
                     }
                 }
             }
             // Find contents of selected.
             if( !entry->any_item().has_parent() ) {
                 continue;
             }
             // More than one item can be highlighted when selected container is stacked.
             for( const item_location &location : selected.locations ) {
                 if( entry->any_item().parent_item() == location ) {
                     entry->highlight_as_child = true;
                 }
             }
         }
     }
 }
References inventory_entry::any_item(), get_active_column(), get_all_columns(), inventory_column::get_highlighted(), item_location::has_parent(), inventory_entry::is_item(), location, inventory_entry::locations, item_location::nowhere, item_location::parent_item(), and anonymous_namespace{inventory_ui.cpp}::return_item().
Referenced by inventory_pick_selector::execute(), ammo_inventory_selector::execute(), inventory_compare_selector::execute(), unload_selector::execute(), inventory_examiner::execute(), highlight_one_of(), inventory_multiselector::on_input(), rearrange_columns(), and refresh_window().
highlight() [2/2]
bool inventory_selector::highlight (const item_location & loc, bool hidden = false, bool front_only = false)
Highlight a location.
Parameters
loc Location to highlight
Returns
true on success.
Definition at line 2194 of file inventory_ui.cpp.
 {
     bool res = false;
     for( size_t i = 0; i < columns.size(); ++i ) {
         inventory_column *elem = columns[i];
         if( !elem->visible() ) {
             continue;
         }
         bool found = false;
         if( hidden ) {
             if( inventory_entry *ent = elem->find_by_location( loc, true ) ) {
                 item_location const &parent = ent->is_collation_entry() ? ent->collation_meta->tip :
                                               ent->topmost_parent;
                 if( !parent ) {
                     continue;
                 }
                 inventory_entry *pent = elem->find_by_location( parent );
                 if( elem != nullptr ) {
                     elem->set_collapsed( *pent, false );
                     prepare_layout();
                     found = elem->highlight( loc, true );
                 }
             }
         } else {
             found = elem->highlight( loc, front_only );
         }
         if( found && !res && elem->activatable() ) {
             set_active_column( i );
             res = true;
         }
     }
     return res;
 }
References inventory_column::activatable(), columns, inventory_column::find_by_location(), inventory_column::highlight(), prepare_layout(), set_active_column(), inventory_column::set_collapsed(), and inventory_column::visible().
highlight_one_of()
bool inventory_selector::highlight_one_of (const std::vector< item_location > & locations, bool hidden = false)
Definition at line 2251 of file inventory_ui.cpp.
 {
     prepare_layout();
     for( const item_location &loc : locations ) {
         if( loc && highlight( loc, hidden ) ) {
             return true;
         }
     }
     return false;
 }
References highlight(), anonymous_namespace{overmap_location.cpp}::locations, and prepare_layout().
Referenced by game_menus::inv::common(), inv_internal(), on_input(), and toggle_categorize_contained().
highlight_position()
void inventory_selector::highlight_position (std::pair< size_t, size_t > position) inline
Definition at line 816 of file inventory_ui.h.
{
             prepare_layout();
             set_active_column( position.first );
             get_active_column().highlight( position.second, scroll_direction::BACKWARD );
         }
References BACKWARD, get_active_column(), inventory_column::highlight(), prepare_layout(), and set_active_column().
Referenced by inv_internal().
invlet_type()
selector_invlet_type inventory_selector::invlet_type () inline
Returns
the letter group to use for automatic inventory letters
Definition at line 659 of file inventory_ui.h.
{
             return this->invlet_type_;
         }
References invlet_type_.
Referenced by pickup_selector::reassign_custom_invlets().
is_active_column()
bool inventory_selector::is_active_column (const inventory_column & column) const inline protected
Definition at line 855 of file inventory_ui.h.
{
             return &column == &get_active_column();
         }
References get_active_column().
Referenced by draw_columns().
is_overflown()
bool inventory_selector::is_overflown (size_t client_width) const protected
Returns
Are visible columns wider than available width
Definition at line 3125 of file inventory_ui.cpp.
 {
     return get_columns_occupancy_ratio( client_width ) > 1.0;
 }
References get_columns_occupancy_ratio().
Referenced by rearrange_columns(), and inventory_multiselector::rearrange_columns().
item_entry_count()
uint64_t inventory_selector::item_entry_count () const
Definition at line 2897 of file inventory_ui.cpp.
 {
     uint64_t count = 0;
     for( const inventory_column *col : columns ) {
         count += col->get_entries( return_item, true ).size();
     }
     return count;
 }
References columns, and anonymous_namespace{inventory_ui.cpp}::return_item().
Referenced by get_only_choice(), and game_menus::inv::select_ammo().
naturalize_category()
const item_category * inventory_selector::naturalize_category (const item_category & category, const tripoint & pos) protected
Definition at line 1868 of file inventory_ui.cpp.
 {
     const auto find_cat_by_id = [ this ]( const item_category_id & id ) {
         const auto iter = std::find_if( categories.begin(),
         categories.end(), [ &id ]( const item_category & cat ) {
             return cat.get_id() == id;
         } );
         return iter != categories.end() ? &*iter : nullptr;
     };
     const int dist = rl_dist( u.pos(), pos );
     if( dist != 0 ) {
         const std::string suffix = direction_suffix( u.pos(), pos );
         const item_category_id id = item_category_id( string_format( "%s_%s", category.get_id().c_str(),
                                     suffix.c_str() ) );
         const auto *existing = find_cat_by_id( id );
         if( existing != nullptr ) {
             return existing;
         }
         const std::string name = string_format( "%s %s", category.name_header(), suffix.c_str() );
         const int sort_rank = category.sort_rank() + dist;
         const item_category new_category( id, no_translation( name ), translation(), sort_rank );
         categories.push_back( new_category );
     } else {
         const item_category *const existing = find_cat_by_id( category.get_id() );
         if( existing != nullptr ) {
             return existing;
         }
         categories.push_back( category );
     }
     return &categories.back();
 }
References categories, anonymous_namespace{item_tname.cpp}::category(), direction_suffix(), base_camps::id, om_direction::name(), no_translation(), Creature::pos(), math_opers::pos(), rl_dist(), string_format(), and u.
Referenced by _add_map_items(), and _uncategorize().
on_change()
void inventory_selector::on_change (const inventory_entry & entry) protected
Entry has been changed.
Definition at line 3059 of file inventory_ui.cpp.
 {
     for( inventory_column *&elem : columns ) {
         elem->on_change( entry );
     }
     refresh_active_column(); // Columns can react to changes by losing their activation capacity
 }
References columns, and refresh_active_column().
Referenced by ammo_inventory_selector::mod_chosen_count(), inventory_multiselector::set_chosen_count(), and inventory_compare_selector::toggle_entry().
on_input()
void inventory_selector::on_input (const inventory_input & input) protected
Given an action from the input_context, try to act according to it.
Should handle all actions standard to derived classes.
Definition at line 2984 of file inventory_ui.cpp.
 {
     if( input.action == "CATEGORY_SELECTION" ) {
         toggle_navigation_mode();
     } else if( input.action == "PREV_COLUMN" ) {
         toggle_active_column( scroll_direction::BACKWARD );
     } else if( input.action == "NEXT_COLUMN" ) {
         toggle_active_column( scroll_direction::FORWARD );
     } else if( input.action == "VIEW_CATEGORY_MODE" ) {
         toggle_categorize_contained();
     } else if( input.action == "TOGGLE_NUMPAD_NAVIGATION" ) {
         uistate.numpad_navigation = !uistate.numpad_navigation;
         reassign_custom_invlets();
     } else if( input.action == "EXAMINE_CONTENTS" ) {
         const inventory_entry &selected = get_active_column().get_highlighted();
         if( selected ) {
             //TODO: Should probably be any_item() rather than direct front() access, but that seems to lock us into const item_location, which various functions are unprepared for
             item_location sitem = selected.locations.front();
             inventory_examiner examine_contents( u, sitem );
             examine_contents.add_contained_items( sitem );
             int examine_result = examine_contents.execute();
             if( examine_result == EXAMINED_CONTENTS_WITH_CHANGES ) {
                 //The user changed something while examining, so rebuild paging
                 for( inventory_column *elem : columns ) {
                     elem->invalidate_paging();
                 }
             } else if( examine_result == NO_CONTENTS_TO_EXAMINE ) {
                 action_examine( sitem );
             }
         }
     } else if( input.action == "EXAMINE" ) {
         const inventory_entry &selected = get_active_column().get_highlighted();
         if( selected ) {
             const item_location &sitem = selected.any_item();
             action_examine( sitem );
         }
     } else if( input.action == "INVENTORY_FILTER" ) {
         query_set_filter();
         ui.lock()->mark_resize();
     } else if( input.action == "RESET_FILTER" ) {
         set_filter( "" );
         ui.lock()->mark_resize();
     } else if( input.action == "TOGGLE_SKIP_UNSELECTABLE" ) {
         toggle_skip_unselectable();
     } else {
         for( inventory_column *elem : columns ) {
             elem->on_input( input );
         }
         refresh_active_column(); // Columns can react to actions by losing their activation capacity
         if( input.action == "TOGGLE_FAVORITE" ) {
             // Favoriting items changes item name length which may require resizing
             shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
             if( current_ui ) {
                 current_ui->mark_resize();
             }
         }
         if( input.action == "SHOW_HIDE_CONTENTS_ALL" ) {
             for( inventory_column *col : columns ) {
                 col->cycle_hide_override();
             }
         }
         if( input.action == "SHOW_HIDE_CONTENTS" || input.action == "SHOW_HIDE_CONTENTS_ALL" ) {
             shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
             for( inventory_column * const &col : columns ) {
                 col->invalidate_paging();
             }
             if( current_ui ) {
                 std::vector<item_location> inv = get_highlighted().locations;
                 current_ui->mark_resize();
                 highlight_one_of( inv );
             }
         }
     }
 }
References inventory_input::action, action_examine(), add_contained_items(), inventory_entry::any_item(), BACKWARD, columns, EXAMINED_CONTENTS_WITH_CHANGES, inventory_examiner::execute(), FORWARD, get_active_column(), inventory_column::get_highlighted(), get_highlighted(), highlight_one_of(), inventory_entry::locations, NO_CONTENTS_TO_EXAMINE, uistatedata::numpad_navigation, query_set_filter(), reassign_custom_invlets(), refresh_active_column(), set_filter(), toggle_active_column(), toggle_categorize_contained(), toggle_navigation_mode(), toggle_skip_unselectable(), u, and uistate.
Referenced by inventory_pick_selector::execute(), ammo_inventory_selector::execute(), inventory_compare_selector::execute(), unload_selector::execute(), inventory_examiner::execute(), and inventory_multiselector::on_input().
prepare_layout() [1/2]
void inventory_selector::prepare_layout () private
Definition at line 2385 of file inventory_ui.cpp.
 {
     startup_timer const tp_prep =
         std::chrono::time_point_cast<std::chrono::milliseconds>( std::chrono::steady_clock::now() );
     const auto snap = []( size_t cur_dim, size_t max_dim ) {
         return cur_dim + 2 * max_win_snap_distance >= max_dim ? max_dim : cur_dim;
     };
     const int nc_width = 2 * ( 1 + border );
     const int nc_height = get_header_height() + 1 + 2 * border;
     prepare_layout( TERMX - nc_width, TERMY - nc_height );
     int const win_width =
         _fixed_size.x < 0 ? snap( get_layout_width() + nc_width, TERMX ) : _fixed_size.x;
     int const win_height =
         _fixed_size.y < 0
         ? snap( std::max<int>( get_layout_height() + nc_height, FULL_SCREEN_HEIGHT ), TERMY )
         : _fixed_size.y;
     prepare_layout( win_width - nc_width, win_height - nc_height );
     resize_window( win_width, win_height );
     debug_print_timer( tp_prep, "prepare_layout took" );
 }
References _fixed_size, border, anonymous_namespace{inventory_ui.cpp}::debug_print_timer(), FULL_SCREEN_HEIGHT, get_header_height(), get_layout_height(), get_layout_width(), max_win_snap_distance, resize_window(), TERMX, TERMY, win_width, point::x, and point::y.
Referenced by create_or_get_ui_adaptor(), highlight(), highlight_one_of(), highlight_position(), and toggle_categorize_contained().
prepare_layout() [2/2]
void inventory_selector::prepare_layout (size_t client_width, size_t client_height) private
Definition at line 2324 of file inventory_ui.cpp.
 {
     // This block adds categories and should go before any width evaluations
     const bool initial = get_active_column().get_highlighted_index() == static_cast<size_t>( -1 );
     for( inventory_column *&elem : columns ) {
         elem->set_height( client_height );
         elem->prepare_paging( filter );
         elem->reset_width( columns );
     }
     // Handle screen overflow
     rearrange_columns( client_width );
     if( initial ) {
         get_active_column().highlight( 0, scroll_direction::FORWARD );
     }
     // If we have a single column and it occupies more than a half of
     // the available with -> expand it
     auto visible_columns = get_visible_columns();
     if( visible_columns.size() == 1 && are_columns_centered( client_width ) ) {
         visible_columns.front()->set_width( client_width );
     }
     reassign_custom_invlets();
     refresh_active_column();
 }
References are_columns_centered(), columns, filter, FORWARD, get_active_column(), inventory_column::get_highlighted_index(), get_visible_columns(), inventory_column::highlight(), rearrange_columns(), reassign_custom_invlets(), and refresh_active_column().
process_input()
inventory_input inventory_selector::process_input (const std::string & action, int ch) protected
Definition at line 2931 of file inventory_ui.cpp.
 {
     inventory_input res{ action, ch, nullptr };
     if( res.action == "SELECT" || res.action == "COORDINATE" || res.action == "MOUSE_MOVE" ||
         res.action == "CLICK_AND_DRAG" ) {
         std::optional<point> o_p = ctxt.get_coordinates_text( w_inv );
         if( o_p ) {
             point p = o_p.value();
             if( window_contains_point_relative( w_inv, p ) ) {
                 res.entry = find_entry_by_coordinate( p );
                 if( res.entry != nullptr && res.entry->is_selectable() ) {
                     return res;
                 }
                 if( res.entry == nullptr && res.action == "SELECT" ) {
                     p.x++;
                     res.entry = find_entry_by_coordinate( p );
                     // if the user has clicked the coordinate just to the left of a pocket, they are clicking the pocket's expander icon
                     if( res.entry != nullptr && res.entry->is_selectable() && res.entry->chevron ) {
                         res.action = "SHOW_HIDE_CONTENTS";
                         return res;
                     }
                 }
             }
         }
     }
     res.entry = find_entry_by_invlet( res.ch );
     if( res.entry != nullptr && !res.entry->is_selectable() ) {
         res.entry = nullptr;
     }
     return res;
 }
References action, ctxt, find_entry_by_coordinate(), find_entry_by_invlet(), input_context::get_coordinates_text(), w_inv, window_contains_point_relative(), and point::x.
Referenced by trade_selector::execute(), and get_input().
query_count()
int inventory_selector::query_count (char init = 0, bool end_with_toggle = false) protected
Query the user for count and return it.
Definition at line 2690 of file inventory_ui.cpp.
 {
     std::string sinit = init != 0 ? std::string( 1, init ) : std::string();
     std::pair< bool, std::string > query = query_string( sinit, end_with_toggle );
     int ret = -1;
     if( query.first ) {
         try {
             ret = std::stoi( query.second );
         } catch( const std::invalid_argument &e ) {
             // TODO Tell User they did a bad
             ret = -1;
         } catch( const std::out_of_range &e ) {
             ret = INT_MAX;
         }
     }
     return ret;
 }
References init, query_string(), and cata::hash64_detail::ret.
Referenced by inventory_multiselector::on_input().
query_set_filter()
void inventory_selector::query_set_filter () protected
Query the user for a filter and apply it.
Definition at line 2682 of file inventory_ui.cpp.
 {
     std::pair< bool, std::string > query = query_string( filter );
     if( query.first ) {
         set_filter( query.second );
     }
 }
References filter, query_string(), and set_filter().
Referenced by on_input().
query_string()
std::pair< bool, std::string > inventory_selector::query_string (const std::string & val, bool end_with_toggle = false) protected
Query user for a string and return it.
Parameters
val The default value to have set in the query prompt.
Returns
A tuple of a bool and string, bool is true if user confirmed.
Definition at line 2646 of file inventory_ui.cpp.
 {
     spopup = std::make_unique<string_input_popup>();
     spopup->max_length( 256 )
     .text( val );
     spopup->identifier( "item_filter" ).hist_use_uilist( false );
     if( end_with_toggle ) {
         for( input_event const &iev : inp_mngr.get_input_for_action( "TOGGLE_ENTRY", "INVENTORY" ) ) {
             spopup->add_callback( iev.get_first_input(), [this]() {
                 spopup->confirm();
                 return true;
             } );
         }
     };
     shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
     if( current_ui ) {
         current_ui->mark_resize();
     }
     do {
         ui_manager::redraw();
         spopup->query_string( /*loop=*/false );
     } while( !spopup->confirmed() && !spopup->canceled() );
     std::string rval;
     bool confirmed = spopup->confirmed();
     if( confirmed ) {
         rval = spopup->text();
     }
     spopup.reset();
     return std::make_pair( confirmed, rval );
 }
References input_manager::get_input_for_action(), inp_mngr, ui_manager::redraw(), and spopup.
Referenced by query_count(), and query_set_filter().
rearrange_columns()
void inventory_selector::rearrange_columns (size_t client_width) protected virtual
Tackles screen overflow.
Reimplemented in inventory_multiselector.
Definition at line 2299 of file inventory_ui.cpp.
 {
     const inventory_entry &prev_entry = get_highlighted();
     const item_location prev_selection = prev_entry.is_item() ?
                                          prev_entry.any_item() : item_location::nowhere;
     bool const front_only = prev_entry.is_collation_entry();
     if( ( is_overflown( client_width ) || force_single_column ) && !own_gear_column.empty() ) {
         if( own_inv_column.empty() ) {
             own_inv_column.set_indent_entries_override( own_gear_column.indent_entries() );
         }
         own_gear_column.move_entries_to( own_inv_column );
         own_inv_column.reset_width( {} );
     }
     if( ( is_overflown( client_width ) || force_single_column ) && !map_column.empty() ) {
         if( own_inv_column.empty() ) {
             own_inv_column.set_indent_entries_override( map_column.indent_entries() );
         }
         map_column.move_entries_to( own_inv_column );
         own_inv_column.reset_width( {} );
     }
     if( prev_selection ) {
         highlight( prev_selection, false, front_only );
     }
 }
References inventory_entry::any_item(), inventory_column::empty(), force_single_column, get_highlighted(), highlight(), inventory_column::indent_entries(), inventory_entry::is_collation_entry(), inventory_entry::is_item(), is_overflown(), map_column, inventory_column::move_entries_to(), item_location::nowhere, own_gear_column, own_inv_column, inventory_column::reset_width(), and inventory_column::set_indent_entries_override().
Referenced by prepare_layout(), and inventory_multiselector::rearrange_columns().
reassign_custom_invlets()
void inventory_selector::reassign_custom_invlets () protected virtual
Reimplemented in pickup_selector.
Definition at line 2351 of file inventory_ui.cpp.
 {
     if( invlet_type_ == SELECTOR_INVLET_DEFAULT || invlet_type_ == SELECTOR_INVLET_NUMERIC ) {
         bool use_num_invlet = uistate.numpad_navigation ? false : use_invlet;
         int min_invlet = static_cast<uint8_t>( use_num_invlet ? '0' : '\0' );
         for( inventory_column *elem : columns ) {
             elem->prepare_paging();
             min_invlet = elem->reassign_custom_invlets( u, min_invlet, use_num_invlet ? '9' : '\0' );
         }
     } else if( invlet_type_ == SELECTOR_INVLET_ALPHA ) {
         const std::string all_pickup_chars = use_invlet ?
                                              "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:;" : "";
         std::string pickup_chars = ctxt.get_available_single_char_hotkeys( all_pickup_chars );
         int cur_idx = 0;
         auto elemfilter = []( const inventory_entry & e ) {
             return e.is_item() && e.any_item()->invlet > '\0';
         };
         // First pass -> remove letters taken by user-set invlets
         for( inventory_column *elem : columns ) {
             for( inventory_entry *e : elem->get_entries( elemfilter ) ) {
                 const char c = e->any_item()->invlet;
                 if( pickup_chars.find_first_of( c ) != std::string::npos ) {
                     pickup_chars.erase( std::remove( pickup_chars.begin(), pickup_chars.end(), c ),
                                         pickup_chars.end() );
                 }
             }
         }
         for( inventory_column *elem : columns ) {
             elem->prepare_paging();
             cur_idx = elem->reassign_custom_invlets( cur_idx, pickup_chars );
         }
     }
 }
References c, columns, ctxt, input_context::get_available_single_char_hotkeys(), invlet_type_, uistatedata::numpad_navigation, SELECTOR_INVLET_ALPHA, SELECTOR_INVLET_DEFAULT, SELECTOR_INVLET_NUMERIC, u, uistate, and use_invlet.
Referenced by on_input(), prepare_layout(), and pickup_selector::reassign_custom_invlets().
refresh_active_column()
void inventory_selector::refresh_active_column () inline protected
Definition at line 867 of file inventory_ui.h.
{
             if( !get_active_column().activatable() ) {
                 toggle_active_column( scroll_direction::FORWARD );
             }
         }
References FORWARD, get_active_column(), and toggle_active_column().
Referenced by on_change(), on_input(), and prepare_layout().
refresh_window()
void inventory_selector::refresh_window () private
Definition at line 2628 of file inventory_ui.cpp.
 {
     cata_assert( w_inv );
     if( get_option<std::string>( "INVENTORY_HIGHLIGHT" ) != "disable" ) {
         highlight();
     }
     werase( w_inv );
     draw_frame( w_inv );
     draw_header( w_inv );
     draw_columns( w_inv );
     draw_footer( w_inv );
     wnoutrefresh( w_inv );
 }
References cata_assert, draw_columns(), draw_footer(), draw_frame(), draw_header(), highlight(), w_inv, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by create_or_get_ui_adaptor().
resize_window()
void inventory_selector::resize_window (int width, int height) private
Definition at line 2612 of file inventory_ui.cpp.
 {
     point origin = _fixed_origin;
     if( origin.x < 0 || origin.y < 0 ) {
         origin = { ( TERMX - width ) / 2, ( TERMY - height ) / 2 };
     }
     w_inv = catacurses::newwin( height, width, origin );
     if( spopup ) {
         spopup->window( w_inv, point( 4, getmaxy( w_inv ) - 1 ), ( getmaxx( w_inv ) / 2 ) - 4 );
     }
     shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
     if( current_ui ) {
         current_ui->position_from_window( w_inv );
     }
 }
References _fixed_origin, catacurses::getmaxx(), catacurses::getmaxy(), catacurses::newwin(), point, spopup, TERMX, TERMY, and w_inv.
Referenced by prepare_layout().
set_active_column()
void inventory_selector::set_active_column (size_t index)
Definition at line 3087 of file inventory_ui.cpp.
 {
     if( index < columns.size() && index != active_column_index && get_column( index ).activatable() ) {
         get_active_column().on_deactivate();
         active_column_index = index;
         get_active_column().on_activate();
     }
 }
References active_column_index, columns, get_active_column(), get_column(), inventory_column::on_activate(), and inventory_column::on_deactivate().
Referenced by highlight(), highlight_position(), and toggle_active_column().
set_display_stats()
void inventory_selector::set_display_stats (bool display_stats) inline
Specify whether the header should show stats (weight and volume).
Definition at line 634 of file inventory_ui.h.
{
             this->display_stats = display_stats;
         }
References display_stats.
Referenced by autodoc_internal(), game_menus::inv::ebookread(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), game_menus::inv::gunmod_to_remove(), game_menus::inv::holster(), inv_internal(), inv_internal_multi(), inventory_examiner::inventory_examiner(), game_menus::inv::select_ammo(), game_menus::inv::swap_letters(), and game_menus::inv::unload_container().
set_filter()
void inventory_selector::set_filter (const std::string & str)
Apply filter string to all columns.
Definition at line 2709 of file inventory_ui.cpp.
 {
     filter = str;
     for( inventory_column *const elem : columns ) {
         elem->set_filter( filter );
     }
 }
References columns, and filter.
Referenced by game_menus::inv::common(), inv_internal(), on_input(), and query_set_filter().
set_hint()
void inventory_selector::set_hint (const std::string & hint) inline
Assigns a hint.
Definition at line 630 of file inventory_ui.h.
{
             this->hint = hint;
         }
References hint.
Referenced by autodoc_internal(), game_menus::inv::common(), game_menus::inv::compare(), compare_recipe_with_item(), unload_selector::execute(), basecamp::get_equipment(), basecamp::give_equipment(), haul(), game_menus::inv::holster(), inv_internal(), inv_internal_multi(), pickup_selector::pickup_selector(), game_menus::inv::select_ammo(), game_menus::inv::smoke_food(), game_menus::inv::swap_letters(), unload_selector::unload_selector(), and iuse::wash_items().
set_invlet_type()
void inventory_selector::set_invlet_type (selector_invlet_type type) inline
Set the letter group to use for automatic inventory letters.
Definition at line 655 of file inventory_ui.h.
{
             this->invlet_type_ = type;
         }
References invlet_type_, and type.
Referenced by inventory_multiselector::inventory_multiselector(), pickup_selector::reassign_custom_invlets(), and game_menus::inv::smoke_food().
set_title()
void inventory_selector::set_title (const std::string & title) inline
Assigns a title that will be shown on top of the menu.
Definition at line 626 of file inventory_ui.h.
{
             this->title = title;
         }
References title.
Referenced by autodoc_internal(), game_menus::inv::common(), game_menus::inv::compare(), compare_recipe_with_item(), game_menus::inv::ebookread(), game_menus::inv::ebooksave(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), basecamp::get_equipment(), basecamp::give_basecamp_equipment(), basecamp::give_equipment(), game_menus::inv::gunmod_to_remove(), haul(), game_menus::inv::holster(), inv_internal(), inv_internal_multi(), game_menus::inv::pickup(), game_menus::inv::select_ammo(), inventory_examiner::setup(), game_menus::inv::smoke_food(), game_menus::inv::swap_letters(), game_menus::inv::unload_container(), and iuse::wash_items().
show_invlet()
void inventory_selector::show_invlet (bool show) inline
Set whether to show inventory letters.
Definition at line 663 of file inventory_ui.h.
{
             this->use_invlet = show;
         }
References show, and use_invlet.
showing_invlet()
bool inventory_selector::showing_invlet () const inline
Returns
true if invlets should be used on this menu
Definition at line 667 of file inventory_ui.h.
{
             return this->use_invlet;
         }
References use_invlet.
toggle_active_column()
void inventory_selector::toggle_active_column (scroll_direction dir) protected
Activates either previous or next column.
Parameters
dir Forward - next column, backward - previous.
Definition at line 3221 of file inventory_ui.cpp.
 {
     if( columns.empty() ) {
         return;
     }
     size_t index = active_column_index;
     do {
         switch( dir ) {
             case scroll_direction::FORWARD:
                 index = index + 1 < columns.size() ? index + 1 : 0;
                 break;
             case scroll_direction::BACKWARD:
                 index = index > 0 ? index - 1 : columns.size() - 1;
                 break;
         }
     } while( index != active_column_index && !get_column( index ).activatable() );
     set_active_column( index );
 }
References active_column_index, BACKWARD, columns, FORWARD, get_column(), and set_active_column().
Referenced by on_input(), and refresh_active_column().
toggle_categorize_contained()
void inventory_selector::toggle_categorize_contained ()
Definition at line 3171 of file inventory_ui.cpp.
 {
     std::vector<item_location> highlighted;
     if( get_highlighted().is_item() ) {
         highlighted = get_highlighted().locations;
     }
     if( _uimode == uimode::hierarchy ) {
         inventory_column replacement_column;
         // split entries into either worn/held gear or contained items
         for( inventory_entry *entry : own_gear_column.get_entries( return_item, true ) ) {
             const item_location loc = entry->any_item();
             inventory_column *col = is_container( loc ) && !is_worn_ablative( loc.parent_item(), loc ) ?
                                     &own_inv_column : &replacement_column;
             col->add_entry( *entry );
         }
         own_gear_column.clear();
         replacement_column.move_entries_to( own_gear_column );
         for( inventory_column *col : columns ) {
             _categorize( *col );
         }
         _uimode = uimode::categories;
     } else {
         // move all entries into one big gear column and turn into hierarchy
         own_inv_column.move_entries_to( own_gear_column );
         for( inventory_column *col : columns ) {
             _uncategorize( *col );
         }
         _uimode = uimode::hierarchy;
     }
     if( !highlighted.empty() ) {
         highlight_one_of( highlighted );
     }
     // needs to be called now so that new invlets can be assigned
     // and subclasses w/ selection columns can then re-populate entries
     // using the new invlets
     prepare_layout();
     // invalidate, but dont mark resize, to avoid re-calling prepare_layout()
     // and as a consequence reassign_custom_invlets()
     shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
     if( current_ui ) {
         current_ui->invalidate_ui();
     }
 }
References _categorize(), _uimode, _uncategorize(), inventory_column::add_entry(), categories, inventory_column::clear(), columns, inventory_column::get_entries(), get_highlighted(), hierarchy, highlight_one_of(), anonymous_namespace{inventory_ui.cpp}::is_container(), is_worn_ablative(), inventory_entry::locations, inventory_column::move_entries_to(), own_gear_column, own_inv_column, item_location::parent_item(), prepare_layout(), and anonymous_namespace{inventory_ui.cpp}::return_item().
Referenced by on_input(), and inventory_multiselector::toggle_categorize_contained().
toggle_navigation_mode()
void inventory_selector::toggle_navigation_mode () protected
Definition at line 3243 of file inventory_ui.cpp.
 {
     mode = get_navigation_data( mode ).next_mode;
     for( inventory_column *&elem : columns ) {
         elem->on_mode_change( mode );
     }
 }
References columns, get_navigation_data(), mode, and navigation_mode_data::next_mode.
Referenced by on_input().
toggle_skip_unselectable()
void inventory_selector::toggle_skip_unselectable ()
Definition at line 3096 of file inventory_ui.cpp.
 {
     skip_unselectable = !skip_unselectable;
     for( inventory_column *col : columns ) {
         col->toggle_skip_unselectable( skip_unselectable );
     }
 }
References columns, and skip_unselectable.
Referenced by on_input().
Member Data Documentation
_categorize_map_items
bool inventory_selector::_categorize_map_items = false protected
Definition at line 783 of file inventory_ui.h.
Referenced by _add_map_items(), and categorize_map_items().
_fixed_origin
point inventory_selector::_fixed_origin { -1, -1 } protected
Definition at line 782 of file inventory_ui.h.
Referenced by inventory_examiner::force_max_window_size(), trade_selector::resize(), and resize_window().
_fixed_size
point inventory_selector::_fixed_size { -1, -1 } protected
Definition at line 782 of file inventory_ui.h.
Referenced by inventory_examiner::execute(), inventory_examiner::force_max_window_size(), prepare_layout(), and trade_selector::resize().
_uimode
uimode inventory_selector::_uimode = uimode::categories private
Definition at line 904 of file inventory_ui.h.
Referenced by _add_map_items(), add_character_items(), draw_footer(), toggle_categorize_contained(), and ~inventory_selector().
active_column_index
size_t inventory_selector::active_column_index private
Definition at line 885 of file inventory_ui.h.
Referenced by get_active_column(), get_highlighted_position(), set_active_column(), and toggle_active_column().
border
const int inventory_selector::border = 1 private
Definition at line 893 of file inventory_ui.h.
Referenced by draw_columns(), draw_footer(), draw_frame(), draw_header(), and prepare_layout().
categories
std::list<item_category> inventory_selector::categories private
Definition at line 886 of file inventory_ui.h.
Referenced by naturalize_category().
columns
std::vector<inventory_column *> inventory_selector::columns protected
Definition at line 779 of file inventory_ui.h.
Referenced by append_column(), clear_items(), draw_columns(), find_entry_by_invlet(), find_entry_by_location(), get_all_columns(), get_column(), get_columns_width(), get_only_choice(), inventory_insert_selector::get_raw_stats(), get_visible_columns(), has_available_choices(), highlight(), inventory_selector(), item_entry_count(), on_change(), on_input(), prepare_layout(), reassign_custom_invlets(), set_active_column(), ammo_inventory_selector::set_all_entries_chosen_count(), set_filter(), toggle_active_column(), toggle_categorize_contained(), toggle_navigation_mode(), and toggle_skip_unselectable().
ctxt
input_context inventory_selector::ctxt protected
The input context for navigation, already contains some actions for movement.
Definition at line 684 of file inventory_ui.h.
Referenced by action_bound_to_key(), ammo_inventory_selector::ammo_inventory_selector(), draw_footer(), inventory_compare_selector::execute(), inventory_drop_selector::execute(), pickup_selector::execute(), trade_selector::execute(), inventory_multiselector::execute(), get_input(), unload_selector::hint_string(), inventory_drop_selector::inventory_drop_selector(), inventory_insert_selector::inventory_insert_selector(), inventory_multiselector::inventory_multiselector(), inventory_selector(), pickup_selector::pickup_selector(), process_input(), reassign_custom_invlets(), trade_selector::trade_selector(), and unload_selector::unload_selector().
display_stats
bool inventory_selector::display_stats = true private
Definition at line 897 of file inventory_ui.h.
Referenced by draw_header(), get_header_height(), get_header_min_width(), and set_display_stats().
entry_generation_number
size_t inventory_selector::entry_generation_number = 0 private
Definition at line 900 of file inventory_ui.h.
Referenced by add_entry().
filter
std::string inventory_selector::filter private
Definition at line 894 of file inventory_ui.h.
Referenced by draw_footer(), get_filter(), prepare_layout(), query_set_filter(), and set_filter().
force_single_column
bool inventory_selector::force_single_column = false protected
Definition at line 784 of file inventory_ui.h.
Referenced by ammo_inventory_selector::ammo_inventory_selector(), and rearrange_columns().
hint
std::string inventory_selector::hint private
Definition at line 884 of file inventory_ui.h.
Referenced by draw_header(), get_header_height(), get_header_min_width(), and set_hint().
invlet_type_
selector_invlet_type inventory_selector::invlet_type_ = SELECTOR_INVLET_DEFAULT private
Definition at line 899 of file inventory_ui.h.
Referenced by invlet_type(), reassign_custom_invlets(), and set_invlet_type().
is_empty
bool inventory_selector::is_empty = true private
Definition at line 896 of file inventory_ui.h.
Referenced by add_entry(), clear_items(), and empty().
map_column
inventory_column inventory_selector::map_column private
Definition at line 891 of file inventory_ui.h.
Referenced by _add_map_items(), clear_items(), inventory_selector(), and rearrange_columns().
mode
navigation_mode inventory_selector::mode private
Definition at line 887 of file inventory_ui.h.
Referenced by append_column(), draw_footer(), get_footer_min_width(), unload_selector::hint_string(), inventory_multiselector::toggle_entries(), and toggle_navigation_mode().
own_gear_column
inventory_column inventory_selector::own_gear_column private
Definition at line 890 of file inventory_ui.h.
Referenced by add_character_items(), add_contained_items(), clear_items(), inventory_selector(), rearrange_columns(), and toggle_categorize_contained().
own_inv_column
inventory_column inventory_selector::own_inv_column private
Definition at line 889 of file inventory_ui.h.
Referenced by _add_map_items(), add_character_items(), add_contained_ebooks(), add_contained_gunmods(), add_contained_items(), clear_items(), inventory_selector(), rearrange_columns(), and toggle_categorize_contained().
preset
const inventory_selector_preset& inventory_selector::preset protected
Definition at line 679 of file inventory_ui.h.
Referenced by _add_map_items(), add_contained_items(), add_entry(), add_entry_rec(), get_column(), inventory_insert_selector::get_raw_stats(), ammo_inventory_selector::mod_chosen_count(), and ~inventory_selector().
rect_entry_map
std::vector< std::pair<inclusive_rectangle<point>, inventory_entry *> > inventory_selector::rect_entry_map protected
Definition at line 764 of file inventory_ui.h.
Referenced by draw_columns(), and find_entry_by_coordinate().
skip_unselectable
bool inventory_selector::skip_unselectable = false static private
Definition at line 902 of file inventory_ui.h.
Referenced by inventory_selector(), and toggle_skip_unselectable().
spopup
std::unique_ptr<string_input_popup> inventory_selector::spopup private
Definition at line 881 of file inventory_ui.h.
Referenced by draw_footer(), query_string(), and resize_window().
title
std::string inventory_selector::title private
Definition at line 883 of file inventory_ui.h.
Referenced by draw_header(), get_header_min_width(), and set_title().
u
Character& inventory_selector::u protected
Definition at line 678 of file inventory_ui.h.
Referenced by _categorize(), _uncategorize(), action_examine(), add_character_items(), add_nearby_items(), pickup_selector::add_reopen_activity(), drag_drop_item(), inventory_pick_selector::execute(), unload_selector::execute(), get_raw_stats(), inventory_drop_selector::get_raw_stats(), pickup_selector::get_raw_stats(), ammo_inventory_selector::mod_chosen_count(), naturalize_category(), on_input(), reassign_custom_invlets(), ammo_inventory_selector::set_all_entries_chosen_count(), inventory_multiselector::toggle_entries(), pickup_selector::wear(), and pickup_selector::wield().
ui
weak_ptr_fast<ui_adaptor> inventory_selector::ui private
Definition at line 879 of file inventory_ui.h.
use_invlet
bool inventory_selector::use_invlet = true private
Definition at line 898 of file inventory_ui.h.
Referenced by reassign_custom_invlets(), show_invlet(), and showing_invlet().
w_inv
catacurses::window inventory_selector::w_inv private
Definition at line 877 of file inventory_ui.h.
Referenced by draw_footer(), process_input(), refresh_window(), and resize_window().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp