Cataclysm DDA: modify_gunmods_actor Class Reference
modify_gunmods_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
modify_gunmods_actor (const std::string &type="modify_gunmods")
void load (const JsonObject &) override
std::optional< int > use (Character *p, item &it, const tripoint &pnt) const override
ret_val< void > can_use (const Character &, const item &it, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void finalize (const itype_id &my_item_type) override
Finalizes the actor.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
Additional Inherited Members
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1064 of file iuse_actor.h.
Constructor & Destructor Documentation
modify_gunmods_actor()
modify_gunmods_actor::modify_gunmods_actor (const std::string & type = "modify_gunmods") inline explicit
Definition at line 1067 of file iuse_actor.h.
 : iuse_actor( type ) {}
Member Function Documentation
can_use()
ret_val< void > modify_gunmods_actor::can_use (const Character & p, const item & it, const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 4380 of file iuse_actor.cpp.
 {
     if( !p.is_wielding( it ) ) {
         return ret_val<void>::make_failure( _( "Need to be wielding." ) );
     }
     const std::vector<const item *> mods = it.gunmods();
     if( mods.empty() ) {
         return ret_val<void>::make_failure( _( "Doesn't appear to be modded." ) );
     }
     const bool modifiables = std::any_of( mods.begin(), mods.end(),
     []( const item * mod ) {
         return mod->is_transformable();
     } );
     if( !modifiables ) {
         return ret_val<void>::make_failure( _( "None of the mods can be modified." ) );
     }
     if( p.is_worn(
             it ) ) { // I don't know if modifying really needs this but its for future proofing.
         return ret_val<void>::make_failure( _( "Has to be taken off first." ) );
     }
     return ret_val<void>::make_success();
 }
References _, item::gunmods(), Character::is_wielding(), Character::is_worn(), ret_val< T >::make_failure(), ret_val< T >::make_success(), and anonymous_namespace{item_tname.cpp}::mods().
clone()
std::unique_ptr<iuse_actor> modify_gunmods_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
finalize()
void modify_gunmods_actor::finalize (const itype_id &) override virtual
Finalizes the actor.
Must be called after all items are loaded.
Reimplemented from iuse_actor.
Definition at line 4414 of file iuse_actor.cpp.
 {
     if( !item::find_type( my_item_type )->gun ) {
         debugmsg( "Item %s has modify_gunmods_actor actor, but it's a gun.", my_item_type.c_str() );
     }
 }
References string_id< T >::c_str(), debugmsg, item::find_type(), and gun.
load()
void modify_gunmods_actor::load (const JsonObject &) inline override virtual
Implements iuse_actor.
Definition at line 1069 of file iuse_actor.h.
 {}
use()
std::optional< int > modify_gunmods_actor::use (Character * p, item & it, const tripoint & pnt) const override virtual
Implements iuse_actor.
Definition at line 4347 of file iuse_actor.cpp.
 {
     std::vector<item *> mods;
     for( item *mod : it.gunmods() ) {
         if( mod->is_transformable() ) {
             mods.push_back( mod );
         }
     }
     uilist prompt;
     prompt.text = _( "Modify which part" );
     for( size_t i = 0; i != mods.size(); ++i ) {
         prompt.addentry( i, true, -1, string_format( "%s: %s", mods[i]->tname(),
                          mods[i]->get_use( "transform" )->get_name() ) );
     }
     prompt.query();
     if( prompt.ret >= 0 ) {
         // set gun to default in case this changes anything
         it.gun_set_mode( gun_mode_DEFAULT );
         p->invoke_item( mods[prompt.ret], "transform", pnt );
         it.on_contents_changed();
         return 0;
     }
     p->add_msg_if_player( _( "Never mind." ) );
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), iuse_actor::get_name(), gun_mode_DEFAULT, item::gun_set_mode(), item::gunmods(), Character::invoke_item(), anonymous_namespace{item_tname.cpp}::mods(), item::on_contents_changed(), Pickup::prompt, and string_format().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp