Cataclysm DDA: activity_actor Class Reference
activity_actor Class Reference abstract
#include <activity_actor.h>
Public Member Functions
virtual ~activity_actor ()=default
virtual activity_id get_type () const =0
Should return the activity id of the corresponding activity.
virtual void start (player_activity &act, Character &who)=0
Called once at the start of the activity.
virtual void do_turn (player_activity &act, Character &who)=0
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
virtual void finish (player_activity &act, Character &who)=0
Called when the activity runs out of moves, assuming that it has not already been set to null.
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
virtual std::unique_ptr< activity_actor > clone () const =0
Returns a deep copy of this object.
virtual void serialize (JsonOut &jsout) const =0
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Private Member Functions
virtual bool can_resume_with_internal (const activity_actor &, const Character &) const
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
Detailed Description
Definition at line 18 of file activity_actor.h.
Constructor & Destructor Documentation
~activity_actor()
virtual activity_actor::~activity_actor () virtual default
Member Function Documentation
can_resume_with()
bool activity_actor::can_resume_with (const activity_actor & other, const Character & who) const inline
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
Checks that other has the same type as this so that can_resume_with_internal can safely static_cast other.
Definition at line 74 of file activity_actor.h.
{
             if( other.get_type() == get_type() ) {
                 return can_resume_with_internal( other, who );
             }
             return false;
         }
References can_resume_with_internal(), get_type(), and other.
Referenced by player_activity::can_resume_with().
can_resume_with_internal()
virtual bool activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline private virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented in reel_cable_activity_actor, prying_activity_actor, oxytorch_activity_actor, shearing_activity_actor, harvest_activity_actor, workout_activity_actor, unload_activity_actor, safecracking_activity_actor, consume_activity_actor, open_gate_activity_actor, boltcutting_activity_actor, read_activity_actor, hotwire_car_activity_actor, bookbinder_copy_activity_actor, hacksaw_activity_actor, and data_handling_activity_actor.
Definition at line 29 of file activity_actor.h.
{
             return false;
         }
Referenced by can_resume_with().
canceled()
virtual void activity_actor::canceled (player_activity & , Character &) inline virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented in move_furniture_activity_actor, disassemble_activity_actor, stash_activity_actor, drop_activity_actor, ebooksave_activity_actor, aim_activity_actor, vehicle_unfolding_activity_actor, reload_activity_actor, insert_item_activity_actor, try_sleep_activity_actor, tent_placement_activity_actor, shearing_activity_actor, milk_activity_actor, workout_activity_actor, craft_activity_actor, data_handling_activity_actor, and autodrive_activity_actor.
Definition at line 65 of file activity_actor.h.
 {}
Referenced by player_activity::canceled().
clone()
virtual std::unique_ptr<activity_actor> activity_actor::clone () const pure virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implemented in unload_loot_activity_actor, mop_activity_actor, longsalvage_activity_actor, gunmod_add_activity_actor, forage_activity_actor, firstaid_activity_actor, disable_activity_actor, clear_rubble_activity_actor, churn_activity_actor, chop_tree_activity_actor, chop_planks_activity_actor, chop_logs_activity_actor, pickup_menu_activity_actor, invoke_item_activity_actor, wield_activity_actor, wear_activity_actor, wash_activity_actor, vehicle_unfolding_activity_actor, vehicle_folding_activity_actor, haircut_activity_actor, shave_activity_actor, reel_cable_activity_actor, tent_deconstruct_activity_actor, prying_activity_actor, play_with_pet_activity_actor, meditate_activity_actor, oxytorch_activity_actor, tent_placement_activity_actor, insert_item_activity_actor, move_furniture_activity_actor, disassemble_activity_actor, shearing_activity_actor, milk_activity_actor, reload_activity_actor, harvest_activity_actor, stash_activity_actor, drop_activity_actor, workout_activity_actor, craft_activity_actor, unload_activity_actor, safecracking_activity_actor, try_sleep_activity_actor, consume_activity_actor, open_gate_activity_actor, migration_cancel_activity_actor, ebooksave_activity_actor, lockpick_activity_actor, boltcutting_activity_actor, pickup_activity_actor, move_items_activity_actor, read_activity_actor, bikerack_unracking_activity_actor, bikerack_racking_activity_actor, glide_activity_actor, hotwire_car_activity_actor, data_handling_activity_actor, bookbinder_copy_activity_actor, hacking_activity_actor, hacksaw_activity_actor, gunmod_remove_activity_actor, autodrive_activity_actor, and aim_activity_actor.
do_drop_invalid_inventory()
virtual bool activity_actor::do_drop_invalid_inventory () const inline virtual
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Reimplemented in pickup_activity_actor.
Definition at line 102 of file activity_actor.h.
{
             return true;
         }
Referenced by player_activity::do_drop_invalid_inventory().
do_turn()
virtual void activity_actor::do_turn (player_activity & act, Character & who) pure virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implemented in unload_loot_activity_actor, glide_activity_actor, stash_activity_actor, drop_activity_actor, workout_activity_actor, safecracking_activity_actor, try_sleep_activity_actor, migration_cancel_activity_actor, ebooksave_activity_actor, pickup_activity_actor, move_items_activity_actor, read_activity_actor, aim_activity_actor, vehicle_unfolding_activity_actor, vehicle_folding_activity_actor, craft_activity_actor, disable_activity_actor, pickup_menu_activity_actor, invoke_item_activity_actor, wield_activity_actor, wear_activity_actor, prying_activity_actor, oxytorch_activity_actor, shearing_activity_actor, boltcutting_activity_actor, hacksaw_activity_actor, bookbinder_copy_activity_actor, mop_activity_actor, longsalvage_activity_actor, gunmod_add_activity_actor, forage_activity_actor, firstaid_activity_actor, clear_rubble_activity_actor, churn_activity_actor, chop_tree_activity_actor, chop_planks_activity_actor, chop_logs_activity_actor, wash_activity_actor, haircut_activity_actor, shave_activity_actor, reel_cable_activity_actor, tent_deconstruct_activity_actor, play_with_pet_activity_actor, meditate_activity_actor, tent_placement_activity_actor, insert_item_activity_actor, move_furniture_activity_actor, disassemble_activity_actor, milk_activity_actor, reload_activity_actor, harvest_activity_actor, unload_activity_actor, consume_activity_actor, open_gate_activity_actor, lockpick_activity_actor, bikerack_unracking_activity_actor, bikerack_racking_activity_actor, hotwire_car_activity_actor, data_handling_activity_actor, hacking_activity_actor, gunmod_remove_activity_actor, and autodrive_activity_actor.
Referenced by player_activity::do_turn().
exertion_level()
virtual float activity_actor::exertion_level () const inline virtual
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
Reimplemented in disassemble_activity_actor, and craft_activity_actor.
Definition at line 92 of file activity_actor.h.
{
             return get_type()->exertion_level();
         }
References activity_type::exertion_level(), and get_type().
Referenced by move_items_activity_actor::do_turn(), and player_activity::exertion_level().
finish()
virtual void activity_actor::finish (player_activity & act, Character & who) pure virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implemented in glide_activity_actor, mop_activity_actor, longsalvage_activity_actor, gunmod_add_activity_actor, forage_activity_actor, firstaid_activity_actor, disable_activity_actor, clear_rubble_activity_actor, churn_activity_actor, chop_tree_activity_actor, chop_planks_activity_actor, chop_logs_activity_actor, haircut_activity_actor, shave_activity_actor, reel_cable_activity_actor, prying_activity_actor, play_with_pet_activity_actor, meditate_activity_actor, oxytorch_activity_actor, insert_item_activity_actor, move_furniture_activity_actor, disassemble_activity_actor, shearing_activity_actor, milk_activity_actor, reload_activity_actor, harvest_activity_actor, workout_activity_actor, unload_activity_actor, safecracking_activity_actor, try_sleep_activity_actor, ebooksave_activity_actor, lockpick_activity_actor, boltcutting_activity_actor, read_activity_actor, hotwire_car_activity_actor, hacking_activity_actor, hacksaw_activity_actor, gunmod_remove_activity_actor, aim_activity_actor, wash_activity_actor, vehicle_unfolding_activity_actor, vehicle_folding_activity_actor, tent_placement_activity_actor, bookbinder_copy_activity_actor, craft_activity_actor, tent_deconstruct_activity_actor, consume_activity_actor, open_gate_activity_actor, bikerack_unracking_activity_actor, bikerack_racking_activity_actor, autodrive_activity_actor, unload_loot_activity_actor, pickup_menu_activity_actor, invoke_item_activity_actor, wield_activity_actor, wear_activity_actor, stash_activity_actor, drop_activity_actor, migration_cancel_activity_actor, pickup_activity_actor, move_items_activity_actor, and data_handling_activity_actor.
Referenced by player_activity::do_turn().
get_progress_message()
std::string activity_actor::get_progress_message (const player_activity & act) const virtual
Used to generate the progress display at the top of the screen.
Reimplemented in disassemble_activity_actor, stash_activity_actor, drop_activity_actor, workout_activity_actor, craft_activity_actor, try_sleep_activity_actor, migration_cancel_activity_actor, pickup_activity_actor, move_items_activity_actor, read_activity_actor, hacking_activity_actor, and aim_activity_actor.
Definition at line 274 of file activity_actor.cpp.
 {
     if( act.moves_total > 0 ) {
         const int pct = ( ( act.moves_total - act.moves_left ) * 100 ) / act.moves_total;
         return string_format( "%d%%", pct );
     } else {
         return std::string();
     }
 }
References act, and string_format().
Referenced by player_activity::get_progress_message().
get_type()
virtual activity_id activity_actor::get_type () const pure virtual
Should return the activity id of the corresponding activity.
Implemented in unload_loot_activity_actor, mop_activity_actor, longsalvage_activity_actor, gunmod_add_activity_actor, forage_activity_actor, firstaid_activity_actor, disable_activity_actor, clear_rubble_activity_actor, churn_activity_actor, chop_tree_activity_actor, chop_planks_activity_actor, chop_logs_activity_actor, pickup_menu_activity_actor, invoke_item_activity_actor, wield_activity_actor, wear_activity_actor, wash_activity_actor, vehicle_unfolding_activity_actor, vehicle_folding_activity_actor, haircut_activity_actor, shave_activity_actor, reel_cable_activity_actor, tent_deconstruct_activity_actor, prying_activity_actor, play_with_pet_activity_actor, meditate_activity_actor, oxytorch_activity_actor, tent_placement_activity_actor, insert_item_activity_actor, move_furniture_activity_actor, disassemble_activity_actor, shearing_activity_actor, milk_activity_actor, reload_activity_actor, harvest_activity_actor, stash_activity_actor, drop_activity_actor, workout_activity_actor, craft_activity_actor, unload_activity_actor, safecracking_activity_actor, try_sleep_activity_actor, consume_activity_actor, open_gate_activity_actor, migration_cancel_activity_actor, ebooksave_activity_actor, lockpick_activity_actor, boltcutting_activity_actor, pickup_activity_actor, move_items_activity_actor, read_activity_actor, bikerack_unracking_activity_actor, bikerack_racking_activity_actor, glide_activity_actor, hotwire_car_activity_actor, data_handling_activity_actor, bookbinder_copy_activity_actor, hacking_activity_actor, hacksaw_activity_actor, gunmod_remove_activity_actor, autodrive_activity_actor, and aim_activity_actor.
Referenced by can_resume_with(), player_activity::do_turn(), exertion_level(), serialize(), and player_activity::synchronize_type_with_actor().
serialize()
virtual void activity_actor::serialize (JsonOut & jsout) const pure virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implemented in unload_loot_activity_actor, mop_activity_actor, longsalvage_activity_actor, gunmod_add_activity_actor, forage_activity_actor, firstaid_activity_actor, disable_activity_actor, clear_rubble_activity_actor, churn_activity_actor, chop_tree_activity_actor, chop_planks_activity_actor, chop_logs_activity_actor, wash_activity_actor, vehicle_unfolding_activity_actor, vehicle_folding_activity_actor, reel_cable_activity_actor, tent_deconstruct_activity_actor, prying_activity_actor, play_with_pet_activity_actor, oxytorch_activity_actor, tent_placement_activity_actor, insert_item_activity_actor, move_furniture_activity_actor, disassemble_activity_actor, shearing_activity_actor, milk_activity_actor, reload_activity_actor, harvest_activity_actor, stash_activity_actor, drop_activity_actor, workout_activity_actor, craft_activity_actor, unload_activity_actor, safecracking_activity_actor, try_sleep_activity_actor, consume_activity_actor, open_gate_activity_actor, migration_cancel_activity_actor, ebooksave_activity_actor, lockpick_activity_actor, boltcutting_activity_actor, pickup_activity_actor, move_items_activity_actor, read_activity_actor, bikerack_unracking_activity_actor, bikerack_racking_activity_actor, glide_activity_actor, hotwire_car_activity_actor, bookbinder_copy_activity_actor, hacking_activity_actor, hacksaw_activity_actor, gunmod_remove_activity_actor, autodrive_activity_actor, aim_activity_actor, pickup_menu_activity_actor, invoke_item_activity_actor, wield_activity_actor, wear_activity_actor, haircut_activity_actor, shave_activity_actor, meditate_activity_actor, and data_handling_activity_actor.
start()
virtual void activity_actor::start (player_activity & act, Character & who) pure virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implemented in unload_loot_activity_actor, mop_activity_actor, longsalvage_activity_actor, gunmod_add_activity_actor, forage_activity_actor, firstaid_activity_actor, disable_activity_actor, clear_rubble_activity_actor, churn_activity_actor, chop_tree_activity_actor, chop_planks_activity_actor, chop_logs_activity_actor, prying_activity_actor, oxytorch_activity_actor, insert_item_activity_actor, shearing_activity_actor, workout_activity_actor, safecracking_activity_actor, try_sleep_activity_actor, read_activity_actor, hacking_activity_actor, hacksaw_activity_actor, aim_activity_actor, vehicle_unfolding_activity_actor, vehicle_folding_activity_actor, consume_activity_actor, craft_activity_actor, wash_activity_actor, haircut_activity_actor, shave_activity_actor, reel_cable_activity_actor, tent_deconstruct_activity_actor, play_with_pet_activity_actor, meditate_activity_actor, tent_placement_activity_actor, move_furniture_activity_actor, disassemble_activity_actor, milk_activity_actor, unload_activity_actor, open_gate_activity_actor, ebooksave_activity_actor, lockpick_activity_actor, boltcutting_activity_actor, bikerack_unracking_activity_actor, bikerack_racking_activity_actor, glide_activity_actor, hotwire_car_activity_actor, bookbinder_copy_activity_actor, gunmod_remove_activity_actor, pickup_menu_activity_actor, invoke_item_activity_actor, wield_activity_actor, wear_activity_actor, reload_activity_actor, harvest_activity_actor, stash_activity_actor, drop_activity_actor, migration_cancel_activity_actor, pickup_activity_actor, move_items_activity_actor, data_handling_activity_actor, and autodrive_activity_actor.
Referenced by player_activity::start_or_resume().
The documentation for this class was generated from the following files:
src/activity_actor.h
src/activity_actor.cpp