Cataclysm DDA: io::JsonObjectOutputArchive Class Reference
io::JsonObjectOutputArchive Class Reference
Output archive matching the input archive JsonObjectInputArchive.
#include <cata_io.h>
Public Types
using is_input = std::false_type
Public Member Functions
JsonObjectOutputArchive (JsonOut &stream)
~JsonObjectOutputArchive ()
Serialization
The io functions store a value (given as parameter) in the archive.
Exceptions
JsonError (via the Json classes) on any kind of error.
Returns
All functions return false. Their signature should be compatible with the functions in JsonObjectInputArchive, so they can be used when the archive type is a template parameter.
template<typename T >
bool io (const std::string_view name, const T &value)
template<typename T >
bool io (const std::string &name, const T &value, const T &default_value)
template<typename T >
bool io (const std::string &name, const T &value, default_tag)
template<typename T >
bool io (const std::string &name, const T &value, empty_default_tag)
template<typename T >
bool io (const std::string &name, const T *pointer, const std::function< void(const std::string &)> &, const std::function< std::string(const T &)> &save, bool required=false)
Special function to store pointers.
template<typename T , typename LoadFunc , typename SaveFunc >
bool io (const std::string &name, const T &pointer, const LoadFunc &, const SaveFunc &save, bool required=false)
The I-give-up load function for gun variants.
template<typename T >
bool io (const std::string &name, const T *pointer, const std::function< void(const std::string &)> &load, const std::function< std::string(const T &)> &save, required_tag)
template<typename T >
bool read (const std::string_view, T &)
For compatibility with the input archive.
Public Attributes
JsonOut & stream
Detailed Description
Output archive matching the input archive JsonObjectInputArchive.
It has the same function as the input archive, they do the exact inverse.
The class creates a valid JSON value in the output stream (that means it adds the initial '{' and '}' to the stream).
Definition at line 379 of file cata_io.h.
Member Typedef Documentation
is_input
using io::JsonObjectOutputArchive::is_input = std::false_type
Definition at line 382 of file cata_io.h.
Constructor & Destructor Documentation
JsonObjectOutputArchive()
io::JsonObjectOutputArchive::JsonObjectOutputArchive (JsonOut & stream) inline explicit
Definition at line 386 of file cata_io.h.
             : stream( stream ) {
             stream.start_object();
         }
References JsonOut::start_object(), and stream.
~JsonObjectOutputArchive()
io::JsonObjectOutputArchive::~JsonObjectOutputArchive () inline
Definition at line 390 of file cata_io.h.
{
             stream.end_object();
         }
References JsonOut::end_object(), and stream.
Member Function Documentation
io() [1/7]
template<typename T , typename LoadFunc , typename SaveFunc > bool io::JsonObjectOutputArchive::io (const std::string & name, const T & pointer, const LoadFunc & , const SaveFunc & save, bool required = false) inline
The I-give-up load function for gun variants.
Definition at line 457 of file cata_io.h.
{
             if( pointer == nullptr ) {
                 if( required ) {
                     throw JsonError( "a required member is null: " + name );
                 }
                 return false;
             }
             return io( name, save( pointer ) );
         }
References io(), and om_direction::name().
io() [2/7]
template<typename T > bool io::JsonObjectOutputArchive::io (const std::string & name, const T & value, const T & default_value) inline
Definition at line 413 of file cata_io.h.
{
             if( value == default_value ) {
                 return false;
             }
             return io( name, value );
         }
References io(), and om_direction::name().
io() [3/7]
template<typename T > bool io::JsonObjectOutputArchive::io (const std::string & name, const T & value, default_tag) inline
Definition at line 420 of file cata_io.h.
{
             static const T default_value = T();
             return io<T>( name, value, default_value );
         }
References om_direction::name().
io() [4/7]
template<typename T > bool io::JsonObjectOutputArchive::io (const std::string & name, const T & value, empty_default_tag) inline
Definition at line 425 of file cata_io.h.
{
             if( !value.empty() ) {
                 io<T>( name, value );
             }
             return false;
         }
References om_direction::name().
io() [5/7]
template<typename T > bool io::JsonObjectOutputArchive::io (const std::string & name, const T * pointer, const std::function< void(const std::string &)> & , const std::function< std::string(const T &)> & save, bool required = false) inline
Special function to store pointers.
If the pointer is nullptr, it will not be stored at all (nullptr is the default value). Otherwise the save function is called to translate the pointer into a string (which can be the id of the pointed to object or similar). The returned string is stored in the archive.
The function signature is compatible with the similar function in the JsonObjectInputArchive, so it can be used when the archive type is a template parameter.
Definition at line 442 of file cata_io.h.
{
             if( pointer == nullptr ) {
                 if( required ) {
                     throw JsonError( "a required member is null: " + name );
                 }
                 return false;
             }
             return io( name, save( *pointer ) );
         }
References io(), and om_direction::name().
io() [6/7]
template<typename T > bool io::JsonObjectOutputArchive::io (const std::string & name, const T * pointer, const std::function< void(const std::string &)> & load, const std::function< std::string(const T &)> & save, required_tag) inline
Definition at line 469 of file cata_io.h.
{
             return io<T>( name, pointer, load, save, true );
         }
References ammo_effects::load(), and om_direction::name().
io() [7/7]
template<typename T > bool io::JsonObjectOutputArchive::io (const std::string_view name, const T & value) inline
Definition at line 407 of file cata_io.h.
{
             stream.member( name );
             io::detail::has_archive_tag<T>::write( stream, value );
             return false;
         }
References JsonOut::member(), om_direction::name(), stream, and io::detail::has_archive_tag< T, E >::write().
Referenced by io().
read()
template<typename T > bool io::JsonObjectOutputArchive::read (const std::string_view , T &) inline
For compatibility with the input archive.
Output archives obliviously never read anything and always return false.
Definition at line 480 of file cata_io.h.
{
             return false;
         }
Member Data Documentation
stream
JsonOut& io::JsonObjectOutputArchive::stream
Definition at line 384 of file cata_io.h.
Referenced by io(), JsonObjectOutputArchive(), and ~JsonObjectOutputArchive().
The documentation for this class was generated from the following file:
src/cata_io.h