Cataclysm DDA: color_manager Class Reference
color_manager Class Reference
#include <color.h>
Classes
struct color_struct
Public Member Functions
color_manager ()=default
nc_color get (color_id id) const
nc_color get_invert (const nc_color &color) const
nc_color get_highlight (const nc_color &color, hl_enum bg) const
nc_color get_random () const
color_id color_to_id (const nc_color &color) const
color_id name_to_id (const std::string &name, report_color_error color_error=report_color_error::yes) const
std::string get_name (const nc_color &color) const
std::string id_to_name (color_id id) const
nc_color name_to_color (const std::string &name, report_color_error color_error=report_color_error::yes) const
nc_color highlight_from_names (const std::string &name, const std::string &bg_name) const
void load_default ()
void load_custom (const cata_path &sPath)
void show_gui ()
void serialize (JsonOut &json) const
void deserialize (const JsonArray &ja)
Private Member Functions
void add_color (color_id col, const std::string &name, const nc_color &color_pair, color_id inv_id)
void clear ()
void finalize ()
bool save_custom () const
Private Attributes
std::array< color_struct, num_colors > color_array
std::unordered_map< nc_color, color_id > inverted_map
std::unordered_map< std::string, color_id > name_map
Detailed Description
Definition at line 413 of file color.h.
Constructor & Destructor Documentation
color_manager()
color_manager::color_manager () default
Member Function Documentation
add_color()
void color_manager::add_color (color_id col, const std::string & name, const nc_color & color_pair, color_id inv_id) private
Definition at line 178 of file color.cpp.
 {
     color_struct st = {color_pair, nc_color(), nc_color(), nc_color(), {{nc_color(), nc_color(), nc_color(), nc_color(), nc_color(), nc_color(), nc_color()}}, col, inv_id, name, "", "" };
     color_array[col] = st;
     inverted_map[color_pair] = col;
     name_map[name] = col;
 }
References color_array, inverted_map, om_direction::name(), and name_map.
Referenced by load_default().
clear()
void color_manager::clear () private
Definition at line 793 of file color.cpp.
 {
     name_map.clear();
     inverted_map.clear();
     for( color_manager::color_struct &entry : color_array ) {
         entry.name.clear();
         entry.name_custom.clear();
         entry.name_invert_custom.clear();
     }
 }
References color_array, inverted_map, and name_map.
Referenced by show_gui().
color_to_id()
color_id color_manager::color_to_id (const nc_color & color) const
Definition at line 128 of file color.cpp.
 {
     auto iter = inverted_map.find( color );
     if( iter != inverted_map.end() ) {
         return iter->second;
     }
     // Optimally this shouldn't happen, but allow for now
     for( const color_manager::color_struct &entry : color_array ) {
         if( entry.color == color ) {
             debugmsg( "Couldn't find color %d", color.operator int() );
             return entry.col_id;
         }
     }
     debugmsg( "Couldn't find color %d", color.operator int() );
     return def_c_unset;
 }
References color(), color_array, debugmsg, def_c_unset, and inverted_map.
Referenced by get_highlight(), get_invert(), and get_name().
deserialize()
void color_manager::deserialize (const JsonArray & ja)
Definition at line 1163 of file color.cpp.
 {
     for( JsonObject joColors : ja ) {
         const std::string name = joColors.get_string( "name" );
         const std::string name_custom = joColors.get_string( "custom" );
         const std::string name_invert_custom = joColors.get_string( "invertcustom" );
         color_id id = name_to_id( name );
         auto &entry = color_array[id];
         if( !name_custom.empty() ) {
             entry.name_custom = name_custom;
         }
         if( !name_invert_custom.empty() ) {
             entry.name_invert_custom = name_invert_custom;
         }
     }
 }
References color_array, base_camps::id, om_direction::name(), and name_to_id().
Referenced by load_custom().
finalize()
void color_manager::finalize () private
Definition at line 51 of file color.cpp.
 {
     static const std::array<std::string, NUM_HL> hilights = {{
             "",
             "red",
             "white",
             "green",
             "yellow",
             "magenta",
             "cyan"
         }
     };
     for( color_manager::color_struct &entry : color_array ) {
         entry.invert = get( entry.invert_id );
         if( !entry.name_custom.empty() ) {
             // Not using name_to_color because we want default color of this name
             const color_id id = name_to_id( entry.name_custom );
             auto &other = color_array[id];
             entry.custom = other.color;
         }
         if( !entry.name_invert_custom.empty() ) {
             const color_id id = name_to_id( entry.name_invert_custom );
             auto &other = color_array[id];
             entry.invert_custom = other.color;
         }
         inverted_map[entry.color] = entry.col_id;
         inverted_map[entry.invert] = entry.invert_id;
     }
     // Highlights in a next run, to make sure custom colors are set
     for( color_manager::color_struct &entry : color_array ) {
         const std::string my_name = get_name( entry.color );
         const std::string root = my_name.substr( 2, my_name.length() - 2 );
         const size_t underscore_num = std::count( root.begin(), root.end(), '_' ) -
                                       ( root.find( "light_" ) != std::string::npos ) -
                                       ( root.find( "dark_" ) != std::string::npos );
         // do not try to highlight color pairs, highlighted, background, and invalid colors
         if( my_name.substr( 0, 2 ) == "c_" && root != "unset" && underscore_num < 1 ) {
             for( size_t j = 0; j < NUM_HL; j++ ) {
                 entry.highlight[j] = highlight_from_names( my_name, hilights[j] );
             }
         }
     }
 }
References color_array, get(), get_name(), highlight_from_names(), base_camps::id, inverted_map, name_to_id(), NUM_HL, and other.
Referenced by load_custom(), and show_gui().
get()
nc_color color_manager::get (color_id id) const
Definition at line 147 of file color.cpp.
 {
     if( id >= num_colors ) {
         debugmsg( "Invalid color index: %d. Color array size: %zd", id, color_array.size() );
         return nc_color();
     }
     const auto &entry = color_array[id];
     return entry.custom.to_int() > 0 ? entry.custom : entry.color;
 }
References color_array, debugmsg, base_camps::id, and num_colors.
Referenced by finalize(), and overmap_ui::get_scent_glyph().
get_highlight()
nc_color color_manager::get_highlight (const nc_color & color, hl_enum bg) const
Definition at line 187 of file color.cpp.
 {
     const color_id id = color_to_id( color );
     const color_struct &st = color_array[id];
     const auto &hl = st.highlight;
     return hl[bg];
 }
References color(), color_array, color_to_id(), color_manager::color_struct::highlight, and base_camps::id.
get_invert()
nc_color color_manager::get_invert (const nc_color & color) const
Definition at line 165 of file color.cpp.
 {
     const color_id id = color_to_id( color );
     const color_struct &entry = color_array[id];
     return entry.invert_custom.to_int() > 0 ? entry.invert_custom : entry.invert;
 }
References color(), color_array, color_to_id(), base_camps::id, color_manager::color_struct::invert, color_manager::color_struct::invert_custom, and nc_color::to_int().
get_name()
std::string color_manager::get_name (const nc_color & color) const
Definition at line 159 of file color.cpp.
 {
     color_id id = color_to_id( color );
     return id_to_name( id );
 }
References color(), color_to_id(), and id_to_name().
Referenced by colorize_symbols(), Messages::dialog::filter_help_text(), finalize(), auto_notes::custom_symbol::get_color_string(), and replace_colors().
get_random()
nc_color color_manager::get_random () const
Definition at line 173 of file color.cpp.
 {
     return random_entry( color_array ).color;
 }
References color_array, and random_entry().
highlight_from_names()
nc_color color_manager::highlight_from_names (const std::string & name, const std::string & bg_name) const
Definition at line 195 of file color.cpp.
 {
     /*
     //            Base Name      Highlight      Red BG              White BG            Green BG            Yellow BG
     add_highlight("c_black",     "h_black",     "",                 "c_black_white",    "c_black_green",    "c_black_yellow",   "c_black_magenta",      "c_black_cyan");
     add_highlight("c_white",     "h_white",     "c_white_red",      "c_white_white",    "c_white_green",    "c_white_yellow",   "c_white_magenta",      "c_white_cyan");
     etc.
     */
     std::string hi_name;
     if( bg_name.empty() ) {  //c_black -> h_black
         hi_name = "h_" + name.substr( 2, name.length() - 2 );
     } else {
         hi_name = name + "_" + bg_name;
     }
     color_id id = name_to_id( hi_name );
     return color_array[id].color;
 }
References color_array, base_camps::id, om_direction::name(), and name_to_id().
Referenced by finalize().
id_to_name()
std::string color_manager::id_to_name (color_id id) const
Definition at line 123 of file color.cpp.
 {
     return color_array[id].name;
 }
References color_array, and base_camps::id.
Referenced by get_name(), and serialize().
load_custom()
void color_manager::load_custom (const cata_path & sPath)
Definition at line 1135 of file color.cpp.
 {
     const cata_path file = sPath.empty() ? PATH_INFO::custom_colors() : sPath;
     read_from_file_optional_json( file, [this]( const JsonArray & jsonin ) {
         deserialize( jsonin );
     } );
     finalize(); // Need to finalize regardless of success
 }
References PATH_INFO::custom_colors(), deserialize(), cata_path::empty(), file, finalize(), and read_from_file_optional_json().
Referenced by show_gui().
load_default()
void color_manager::load_default ()
Definition at line 217 of file color.cpp.
 {
     static const auto color_pair = []( const int n ) {
         return nc_color::from_color_pair_index( n );
     };
     //        Color         Name      Color Pair      Invert
     add_color( def_c_black, "c_black", color_pair( 30 ), def_i_black );
     add_color( def_c_white, "c_white", color_pair( 1 ).bold(), def_i_white );
     add_color( def_c_light_gray, "c_light_gray", color_pair( 1 ), def_i_light_gray );
     add_color( def_c_red, "c_red", color_pair( 2 ), def_i_red );
     add_color( def_c_green, "c_green", color_pair( 3 ), def_i_green );
     add_color( def_c_blue, "c_blue", color_pair( 4 ), def_i_blue );
     add_color( def_c_cyan, "c_cyan", color_pair( 5 ), def_i_cyan );
     add_color( def_c_magenta, "c_magenta", color_pair( 6 ), def_i_magenta );
     add_color( def_c_brown, "c_brown", color_pair( 7 ), def_i_brown );
     add_color( def_c_light_red, "c_light_red", color_pair( 2 ).bold(), def_i_light_red );
     add_color( def_c_light_green, "c_light_green", color_pair( 3 ).bold(), def_i_light_green );
     add_color( def_c_light_blue, "c_light_blue", color_pair( 4 ).bold(), def_i_light_blue );
     add_color( def_c_light_cyan, "c_light_cyan", color_pair( 5 ).bold(), def_i_light_cyan );
     add_color( def_c_pink, "c_pink", color_pair( 6 ).bold(), def_i_pink );
     add_color( def_c_yellow, "c_yellow", color_pair( 7 ).bold(), def_i_yellow );
     add_color( def_h_black, "h_black", color_pair( 20 ), def_c_blue );
     add_color( def_h_white, "h_white", color_pair( 15 ).bold(), def_c_light_blue_white );
     add_color( def_h_light_gray, "h_light_gray", color_pair( 15 ), def_c_blue_white );
     add_color( def_h_red, "h_red", color_pair( 16 ), def_c_blue_red );
     add_color( def_h_green, "h_green", color_pair( 17 ), def_c_blue_green );
     add_color( def_h_blue, "h_blue", color_pair( 20 ), def_h_blue );
     add_color( def_h_cyan, "h_cyan", color_pair( 19 ), def_c_blue_cyan );
     add_color( def_h_magenta, "h_magenta", color_pair( 21 ), def_c_blue_magenta );
     add_color( def_h_brown, "h_brown", color_pair( 22 ), def_c_blue_yellow );
     add_color( def_h_light_red, "h_light_red", color_pair( 16 ).bold(), def_c_light_blue_red );
     add_color( def_h_light_green, "h_light_green", color_pair( 17 ).bold(), def_c_light_blue_green );
     add_color( def_h_light_blue, "h_light_blue", color_pair( 18 ).bold(), def_h_light_blue );
     add_color( def_h_light_cyan, "h_light_cyan", color_pair( 19 ).bold(), def_c_light_blue_cyan );
     add_color( def_h_pink, "h_pink", color_pair( 21 ).bold(), def_c_light_blue_magenta );
     add_color( def_h_yellow, "h_yellow", color_pair( 22 ).bold(), def_c_light_blue_yellow );
     add_color( def_i_black, "i_black", color_pair( 32 ), def_c_black );
     add_color( def_i_white, "i_white", color_pair( 8 ).blink(), def_c_white );
     add_color( def_i_light_gray, "i_light_gray", color_pair( 8 ), def_c_light_gray );
     add_color( def_i_red, "i_red", color_pair( 9 ), def_c_red );
     add_color( def_i_green, "i_green", color_pair( 10 ), def_c_green );
     add_color( def_i_blue, "i_blue", color_pair( 11 ), def_c_blue );
     add_color( def_i_cyan, "i_cyan", color_pair( 12 ), def_c_cyan );
     add_color( def_i_magenta, "i_magenta", color_pair( 13 ), def_c_magenta );
     add_color( def_i_brown, "i_brown", color_pair( 14 ), def_c_brown );
     add_color( def_i_light_red, "i_light_red", color_pair( 9 ).blink(), def_c_light_red );
     add_color( def_i_light_green, "i_light_green", color_pair( 10 ).blink(), def_c_light_green );
     add_color( def_i_light_blue, "i_light_blue", color_pair( 11 ).blink(), def_c_light_blue );
     add_color( def_i_light_cyan, "i_light_cyan", color_pair( 12 ).blink(), def_c_light_cyan );
     add_color( def_i_pink, "i_pink", color_pair( 13 ).blink(), def_c_pink );
     add_color( def_i_yellow, "i_yellow", color_pair( 14 ).blink(), def_c_yellow );
     add_color( def_c_black_red, "c_black_red", color_pair( 9 ).bold(), def_c_red );
     add_color( def_c_white_red, "c_white_red", color_pair( 23 ).bold(), def_c_red_white );
     add_color( def_c_light_gray_red, "c_light_gray_red", color_pair( 23 ), def_c_light_red_white );
     add_color( def_c_red_red, "c_red_red", color_pair( 9 ), def_c_red_red );
     add_color( def_c_green_red, "c_green_red", color_pair( 25 ), def_c_red_green );
     add_color( def_c_blue_red, "c_blue_red", color_pair( 26 ), def_h_red );
     add_color( def_c_cyan_red, "c_cyan_red", color_pair( 27 ), def_c_red_cyan );
     add_color( def_c_magenta_red, "c_magenta_red", color_pair( 28 ), def_c_red_magenta );
     add_color( def_c_brown_red, "c_brown_red", color_pair( 29 ), def_c_red_yellow );
     add_color( def_c_light_red_red, "c_light_red_red", color_pair( 24 ).bold(), def_c_red_red );
     add_color( def_c_light_green_red, "c_light_green_red", color_pair( 25 ).bold(),
                def_c_light_red_green );
     add_color( def_c_light_blue_red, "c_light_blue_red", color_pair( 26 ).bold(), def_h_light_red );
     add_color( def_c_light_cyan_red, "c_light_cyan_red", color_pair( 27 ).bold(),
                def_c_light_red_cyan );
     add_color( def_c_pink_red, "c_pink_red", color_pair( 28 ).bold(), def_c_light_red_magenta );
     add_color( def_c_yellow_red, "c_yellow_red", color_pair( 29 ).bold(), def_c_red_yellow );
     add_color( def_c_unset, "c_unset", color_pair( 31 ), def_c_unset );
     add_color( def_c_black_white, "c_black_white", color_pair( 32 ), def_c_light_gray );
     add_color( def_c_light_gray_white, "c_light_gray_white", color_pair( 33 ), def_c_light_gray_white );
     add_color( def_c_white_white, "c_white_white", color_pair( 33 ).bold(), def_c_white_white );
     add_color( def_c_red_white, "c_red_white", color_pair( 34 ), def_c_white_red );
     add_color( def_c_light_red_white, "c_light_red_white", color_pair( 34 ).bold(),
                def_c_light_gray_red );
     add_color( def_c_green_white, "c_green_white", color_pair( 35 ), def_c_light_gray_green );
     add_color( def_c_light_green_white, "c_light_green_white", color_pair( 35 ).bold(),
                def_c_white_green );
     add_color( def_c_brown_white, "c_brown_white", color_pair( 36 ), def_c_light_gray_yellow );
     add_color( def_c_yellow_white, "c_yellow_white", color_pair( 36 ).bold(), def_c_white_yellow );
     add_color( def_c_blue_white, "c_blue_white", color_pair( 37 ), def_h_light_gray );
     add_color( def_c_light_blue_white, "c_light_blue_white", color_pair( 37 ).bold(), def_h_white );
     add_color( def_c_magenta_white, "c_magenta_white", color_pair( 38 ), def_c_light_gray_magenta );
     add_color( def_c_pink_white, "c_pink_white", color_pair( 38 ).bold(), def_c_white_magenta );
     add_color( def_c_cyan_white, "c_cyan_white", color_pair( 39 ), def_c_light_gray_cyan );
     add_color( def_c_light_cyan_white, "c_light_cyan_white", color_pair( 39 ).bold(),
                def_c_white_cyan );
     add_color( def_c_black_green, "c_black_green", color_pair( 40 ), def_c_green );
     add_color( def_c_light_gray_green, "c_light_gray_green", color_pair( 41 ), def_c_green_white );
     add_color( def_c_white_green, "c_white_green", color_pair( 41 ).bold(), def_c_light_green_white );
     add_color( def_c_red_green, "c_red_green", color_pair( 42 ), def_c_green_red );
     add_color( def_c_light_red_green, "c_light_red_green", color_pair( 42 ).bold(),
                def_c_light_green_red );
     add_color( def_c_green_green, "c_green_green", color_pair( 43 ), def_c_green_green );
     add_color( def_c_light_green_green, "c_light_green_green", color_pair( 43 ).bold(),
                def_c_light_green_green );
     add_color( def_c_brown_green, "c_brown_green", color_pair( 44 ), def_c_green_yellow );
     add_color( def_c_yellow_green, "c_yellow_green", color_pair( 44 ).bold(),
                def_c_light_green_yellow );
     add_color( def_c_blue_green, "c_blue_green", color_pair( 45 ), def_h_green );
     add_color( def_c_light_blue_green, "c_light_blue_green", color_pair( 45 ).bold(),
                def_h_light_green );
     add_color( def_c_magenta_green, "c_magenta_green", color_pair( 46 ), def_c_green_magenta );
     add_color( def_c_pink_green, "c_pink_green", color_pair( 46 ).bold(), def_c_light_green_magenta );
     add_color( def_c_cyan_green, "c_cyan_green", color_pair( 47 ), def_c_green_cyan );
     add_color( def_c_light_cyan_green, "c_light_cyan_green", color_pair( 47 ).bold(),
                def_c_light_green_cyan );
     add_color( def_c_black_yellow, "c_black_yellow", color_pair( 48 ), def_c_brown );
     add_color( def_c_light_gray_yellow, "c_light_gray_yellow", color_pair( 49 ), def_c_brown_white );
     add_color( def_c_white_yellow, "c_white_yellow", color_pair( 49 ).bold(), def_c_yellow_white );
     add_color( def_c_red_yellow, "c_red_yellow", color_pair( 50 ), def_c_yellow_red );
     add_color( def_c_light_red_yellow, "c_light_red_yellow", color_pair( 50 ).bold(),
                def_c_yellow_red );
     add_color( def_c_green_yellow, "c_green_yellow", color_pair( 51 ), def_c_brown_green );
     add_color( def_c_light_green_yellow, "c_light_green_yellow", color_pair( 51 ).bold(),
                def_c_yellow_green );
     add_color( def_c_brown_yellow, "c_brown_yellow", color_pair( 52 ), def_c_brown_yellow );
     add_color( def_c_yellow_yellow, "c_yellow_yellow", color_pair( 52 ).bold(), def_c_yellow_yellow );
     add_color( def_c_blue_yellow, "c_blue_yellow", color_pair( 53 ), def_h_brown );
     add_color( def_c_light_blue_yellow, "c_light_blue_yellow", color_pair( 53 ).bold(), def_h_yellow );
     add_color( def_c_magenta_yellow, "c_magenta_yellow", color_pair( 54 ), def_c_brown_magenta );
     add_color( def_c_pink_yellow, "c_pink_yellow", color_pair( 54 ).bold(), def_c_yellow_magenta );
     add_color( def_c_cyan_yellow, "c_cyan_yellow", color_pair( 55 ), def_c_brown_cyan );
     add_color( def_c_light_cyan_yellow, "c_light_cyan_yellow", color_pair( 55 ).bold(),
                def_c_yellow_cyan );
     add_color( def_c_black_magenta, "c_black_magenta", color_pair( 56 ), def_c_magenta );
     add_color( def_c_light_gray_magenta, "c_light_gray_magenta", color_pair( 57 ),
                def_c_magenta_white );
     add_color( def_c_white_magenta, "c_white_magenta", color_pair( 57 ).bold(), def_c_pink_white );
     add_color( def_c_red_magenta, "c_red_magenta", color_pair( 58 ), def_c_magenta_red );
     add_color( def_c_light_red_magenta, "c_light_red_magenta", color_pair( 58 ).bold(),
                def_c_pink_red );
     add_color( def_c_green_magenta, "c_green_magenta", color_pair( 59 ), def_c_magenta_green );
     add_color( def_c_light_green_magenta, "c_light_green_magenta", color_pair( 59 ).bold(),
                def_c_pink_green );
     add_color( def_c_brown_magenta, "c_brown_magenta", color_pair( 60 ), def_c_magenta_yellow );
     add_color( def_c_yellow_magenta, "c_yellow_magenta", color_pair( 60 ).bold(), def_c_pink_yellow );
     add_color( def_c_blue_magenta, "c_blue_magenta", color_pair( 61 ), def_h_magenta );
     add_color( def_c_light_blue_magenta, "c_light_blue_magenta", color_pair( 61 ).bold(), def_h_pink );
     add_color( def_c_magenta_magenta, "c_magenta_magenta", color_pair( 62 ), def_c_magenta_magenta );
     add_color( def_c_pink_magenta, "c_pink_magenta", color_pair( 62 ).bold(), def_c_pink_magenta );
     add_color( def_c_cyan_magenta, "c_cyan_magenta", color_pair( 63 ), def_c_magenta_cyan );
     add_color( def_c_light_cyan_magenta, "c_light_cyan_magenta", color_pair( 63 ).bold(),
                def_c_pink_cyan );
     add_color( def_c_black_cyan, "c_black_cyan", color_pair( 64 ), def_c_cyan );
     add_color( def_c_light_gray_cyan, "c_light_gray_cyan", color_pair( 65 ), def_c_cyan_white );
     add_color( def_c_white_cyan, "c_white_cyan", color_pair( 65 ).bold(), def_c_light_cyan_white );
     add_color( def_c_red_cyan, "c_red_cyan", color_pair( 66 ), def_c_cyan_red );
     add_color( def_c_light_red_cyan, "c_light_red_cyan", color_pair( 66 ).bold(),
                def_c_light_cyan_red );
     add_color( def_c_green_cyan, "c_green_cyan", color_pair( 67 ), def_c_cyan_green );
     add_color( def_c_light_green_cyan, "c_light_green_cyan", color_pair( 67 ).bold(),
                def_c_light_cyan_green );
     add_color( def_c_brown_cyan, "c_brown_cyan", color_pair( 68 ), def_c_cyan_yellow );
     add_color( def_c_yellow_cyan, "c_yellow_cyan", color_pair( 68 ).bold(), def_c_light_cyan_yellow );
     add_color( def_c_blue_cyan, "c_blue_cyan", color_pair( 69 ), def_h_cyan );
     add_color( def_c_light_blue_cyan, "c_light_blue_cyan", color_pair( 69 ).bold(), def_h_light_cyan );
     add_color( def_c_magenta_cyan, "c_magenta_cyan", color_pair( 70 ), def_c_cyan_magenta );
     add_color( def_c_pink_cyan, "c_pink_cyan", color_pair( 70 ).bold(), def_c_light_cyan_magenta );
     add_color( def_c_cyan_cyan, "c_cyan_cyan", color_pair( 71 ), def_c_cyan_cyan );
     add_color( def_c_light_cyan_cyan, "c_light_cyan_cyan", color_pair( 71 ).bold(),
                def_c_light_cyan_cyan );
     // Allow real dark gray for terminals that support it
     if( catacurses::supports_256_colors() ) {
         add_color( def_c_dark_gray, "c_dark_gray", color_pair( 72 ), def_i_dark_gray );
         add_color( def_h_dark_gray, "h_dark_gray", color_pair( 75 ), def_c_light_blue );
         add_color( def_i_dark_gray, "i_dark_gray", color_pair( 79 ).blink(), def_c_dark_gray );
         add_color( def_c_dark_gray_red, "c_dark_gray_red", color_pair( 73 ), def_c_dark_gray_red );
         add_color( def_c_dark_gray_white, "c_dark_gray_white", color_pair( 79 ), def_c_white );
         add_color( def_c_dark_gray_green, "c_dark_gray_green", color_pair( 74 ), def_c_light_green );
         add_color( def_c_dark_gray_yellow, "c_dark_gray_yellow", color_pair( 78 ), def_c_yellow );
         add_color( def_c_dark_gray_magenta, "c_dark_gray_magenta", color_pair( 77 ), def_c_pink );
         add_color( def_c_dark_gray_cyan, "c_dark_gray_cyan", color_pair( 76 ), def_c_light_cyan );
 #if !(defined(TILES) || defined(WIN32))
         imclient->set_alloced_pair_count( 79 );
 #endif
     } else {
         add_color( def_c_dark_gray, "c_dark_gray", color_pair( 30 ).bold(), def_i_dark_gray );
         add_color( def_h_dark_gray, "h_dark_gray", color_pair( 20 ).bold(), def_c_light_blue );
         add_color( def_i_dark_gray, "i_dark_gray", color_pair( 32 ).blink(), def_c_dark_gray );
         add_color( def_c_dark_gray_red, "c_dark_gray_red", color_pair( 9 ).bold(), def_c_dark_gray_red );
         add_color( def_c_dark_gray_white, "c_dark_gray_white", color_pair( 32 ).bold(), def_c_white );
         add_color( def_c_dark_gray_green, "c_dark_gray_green", color_pair( 40 ).bold(), def_c_light_green );
         add_color( def_c_dark_gray_yellow, "c_dark_gray_yellow", color_pair( 48 ).bold(), def_c_yellow );
         add_color( def_c_dark_gray_magenta, "c_dark_gray_magenta", color_pair( 56 ).bold(), def_c_pink );
         add_color( def_c_dark_gray_cyan, "c_dark_gray_cyan", color_pair( 64 ).bold(), def_c_light_cyan );
 #if !(defined(TILES) || defined(WIN32))
         imclient->set_alloced_pair_count( 71 );
 #endif
     }
 }
References add_color(), def_c_black, def_c_black_cyan, def_c_black_green, def_c_black_magenta, def_c_black_red, def_c_black_white, def_c_black_yellow, def_c_blue, def_c_blue_cyan, def_c_blue_green, def_c_blue_magenta, def_c_blue_red, def_c_blue_white, def_c_blue_yellow, def_c_brown, def_c_brown_cyan, def_c_brown_green, def_c_brown_magenta, def_c_brown_red, def_c_brown_white, def_c_brown_yellow, def_c_cyan, def_c_cyan_cyan, def_c_cyan_green, def_c_cyan_magenta, def_c_cyan_red, def_c_cyan_white, def_c_cyan_yellow, def_c_dark_gray, def_c_dark_gray_cyan, def_c_dark_gray_green, def_c_dark_gray_magenta, def_c_dark_gray_red, def_c_dark_gray_white, def_c_dark_gray_yellow, def_c_green, def_c_green_cyan, def_c_green_green, def_c_green_magenta, def_c_green_red, def_c_green_white, def_c_green_yellow, def_c_light_blue, def_c_light_blue_cyan, def_c_light_blue_green, def_c_light_blue_magenta, def_c_light_blue_red, def_c_light_blue_white, def_c_light_blue_yellow, def_c_light_cyan, def_c_light_cyan_cyan, def_c_light_cyan_green, def_c_light_cyan_magenta, def_c_light_cyan_red, def_c_light_cyan_white, def_c_light_cyan_yellow, def_c_light_gray, def_c_light_gray_cyan, def_c_light_gray_green, def_c_light_gray_magenta, def_c_light_gray_red, def_c_light_gray_white, def_c_light_gray_yellow, def_c_light_green, def_c_light_green_cyan, def_c_light_green_green, def_c_light_green_magenta, def_c_light_green_red, def_c_light_green_white, def_c_light_green_yellow, def_c_light_red, def_c_light_red_cyan, def_c_light_red_green, def_c_light_red_magenta, def_c_light_red_red, def_c_light_red_white, def_c_light_red_yellow, def_c_magenta, def_c_magenta_cyan, def_c_magenta_green, def_c_magenta_magenta, def_c_magenta_red, def_c_magenta_white, def_c_magenta_yellow, def_c_pink, def_c_pink_cyan, def_c_pink_green, def_c_pink_magenta, def_c_pink_red, def_c_pink_white, def_c_pink_yellow, def_c_red, def_c_red_cyan, def_c_red_green, def_c_red_magenta, def_c_red_red, def_c_red_white, def_c_red_yellow, def_c_unset, def_c_white, def_c_white_cyan, def_c_white_green, def_c_white_magenta, def_c_white_red, def_c_white_white, def_c_white_yellow, def_c_yellow, def_c_yellow_cyan, def_c_yellow_green, def_c_yellow_magenta, def_c_yellow_red, def_c_yellow_white, def_c_yellow_yellow, def_h_black, def_h_blue, def_h_brown, def_h_cyan, def_h_dark_gray, def_h_green, def_h_light_blue, def_h_light_cyan, def_h_light_gray, def_h_light_green, def_h_light_red, def_h_magenta, def_h_pink, def_h_red, def_h_white, def_h_yellow, def_i_black, def_i_blue, def_i_brown, def_i_cyan, def_i_dark_gray, def_i_green, def_i_light_blue, def_i_light_cyan, def_i_light_gray, def_i_light_green, def_i_light_red, def_i_magenta, def_i_pink, def_i_red, def_i_white, def_i_yellow, nc_color::from_color_pair_index(), imclient, and catacurses::supports_256_colors().
Referenced by show_gui().
name_to_color()
nc_color color_manager::name_to_color (const std::string & name, report_color_error color_error = report_color_error::yes) const
Definition at line 100 of file color.cpp.
 {
     const color_id id = name_to_id( name, color_error );
     const color_struct &entry = color_array[id];
     return entry.custom.to_int() > 0 ? entry.custom : entry.color;
 }
References color_manager::color_struct::color, color_array, color_manager::color_struct::custom, base_camps::id, om_direction::name(), name_to_id(), and nc_color::to_int().
Referenced by auto_notes::custom_symbol::set_color().
name_to_id()
color_id color_manager::name_to_id (const std::string & name, report_color_error color_error = report_color_error::yes) const
Definition at line 109 of file color.cpp.
 {
     auto iter = name_map.find( name );
     if( iter == name_map.end() ) {
         if( color_error == report_color_error::yes ) {
             debugmsg( "couldn't parse color: %s", name );
         }
         return def_c_unset;
     }
     return iter->second;
 }
References debugmsg, def_c_unset, om_direction::name(), name_map, and yes.
Referenced by deserialize(), finalize(), highlight_from_names(), name_to_color(), and show_gui().
save_custom()
bool color_manager::save_custom () const private
Definition at line 1124 of file color.cpp.
 {
     const cata_path savefile = PATH_INFO::custom_colors();
     return write_to_file( savefile.generic_u8string(), [&](
     std::ostream & fout ) {
         JsonOut jsout( fout );
         serialize( jsout );
     }, _( "custom colors" ) );
 }
References _, PATH_INFO::custom_colors(), cata_path::generic_u8string(), and write_to_file().
Referenced by show_gui().
serialize()
void color_manager::serialize (JsonOut & json) const
Definition at line 1145 of file color.cpp.
 {
     json.start_array();
     for( const color_struct &entry : color_array ) {
         if( !entry.name_custom.empty() || !entry.name_invert_custom.empty() ) {
             json.start_object();
             json.member( "name", id_to_name( entry.col_id ) );
             json.member( "custom", entry.name_custom );
             json.member( "invertcustom", entry.name_invert_custom );
             json.end_object();
         }
     }
     json.end_array();
 }
References color_array, JsonOut::end_array(), JsonOut::end_object(), id_to_name(), JsonOut::member(), JsonOut::start_array(), and JsonOut::start_object().
show_gui()
void color_manager::show_gui ()
Definition at line 830 of file color.cpp.
 {
     const int iHeaderHeight = 4;
     int iContentHeight = 0;
     point iOffset;
     std::vector<int> vLines;
     vLines.push_back( -1 );
     vLines.push_back( 48 );
     const int iTotalCols = vLines.size();
     catacurses::window w_colors_border;
     catacurses::window w_colors_header;
     catacurses::window w_colors;
     const auto calc_offset_y = []() -> int {
         return TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0;
     };
     ui_adaptor ui;
     const auto init_windows = [&]( ui_adaptor & ui ) {
         iContentHeight = FULL_SCREEN_HEIGHT - 2 - iHeaderHeight;
         iOffset.x = TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0;
         iOffset.y = calc_offset_y();
         w_colors_border = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                               iOffset );
         w_colors_header = catacurses::newwin( iHeaderHeight, FULL_SCREEN_WIDTH - 2,
                                               iOffset + point_south_east );
         w_colors = catacurses::newwin( iContentHeight, FULL_SCREEN_WIDTH - 2,
                                        iOffset + point( 1, iHeaderHeight + 1 ) );
         ui.position_from_window( w_colors_border );
     };
     init_windows( ui );
     ui.on_screen_resize( init_windows );
     int iCurrentLine = 0;
     int iCurrentCol = 1;
     int iStartPos = 0;
     const int iMaxColors = color_array.size();
     bool bStuffChanged = false;
     input_context ctxt( "COLORS" );
     ctxt.register_navigate_ui_list();
     ctxt.register_leftright();
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "REMOVE_CUSTOM" );
     ctxt.register_action( "LOAD_TEMPLATE" );
     ctxt.register_action( "LOAD_BASE_COLORS" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     std::map<std::string, color_struct> name_color_map;
     for( const auto &pr : name_map ) {
         name_color_map[pr.first] = color_array[pr.second];
     }
     ui.on_redraw( [&]( const ui_adaptor & ) {
         draw_border( w_colors_border, BORDER_COLOR, _( "Color manager" ) );
         mvwputch( w_colors_border, point( 0, 3 ), BORDER_COLOR, LINE_XXXO ); // |-
         mvwputch( w_colors_border, point( getmaxx( w_colors_border ) - 1, 3 ), BORDER_COLOR,
                   LINE_XOXX ); // -|
         for( int &iCol : vLines ) {
             if( iCol > -1 ) {
                 mvwputch( w_colors_border, point( iCol + 1, FULL_SCREEN_HEIGHT - 1 ), BORDER_COLOR,
                           LINE_XXOX ); // _|_
                 mvwputch( w_colors_header, point( iCol, 3 ), BORDER_COLOR, LINE_XOXO );
             }
         }
         wnoutrefresh( w_colors_border );
         draw_header( w_colors_header );
         // Clear all lines
         for( int i = 0; i < iContentHeight; i++ ) {
             for( int j = 0; j < 79; j++ ) {
                 mvwputch( w_colors, point( j, i ), c_black, ' ' );
                 for( int &iCol : vLines ) {
                     if( iCol == j ) {
                         mvwputch( w_colors, point( j, i ), BORDER_COLOR, LINE_XOXO );
                     }
                 }
             }
         }
         calcStartPos( iStartPos, iCurrentLine, iContentHeight, iMaxColors );
         draw_scrollbar( w_colors_border, iCurrentLine, iContentHeight, iMaxColors, point( 0, 5 ) );
         wnoutrefresh( w_colors_border );
         auto iter = name_color_map.begin();
         std::advance( iter, iStartPos );
         // display color manager
         for( int i = iStartPos; iter != name_color_map.end(); ++iter, ++i ) {
             if( i >= iStartPos &&
                 i < iStartPos + std::min( iContentHeight, iMaxColors ) ) {
                 color_manager::color_struct &entry = iter->second;
                 if( iCurrentLine == i ) {
                     mvwprintz( w_colors, point( vLines[iCurrentCol - 1] + 2, i - iStartPos ), c_yellow, ">" );
                 }
                 mvwprintz( w_colors, point( 3, i - iStartPos ), c_white, iter->first ); //color name
                 mvwprintz( w_colors, point( 21, i - iStartPos ), entry.color, _( "default" ) ); //default color
                 if( !entry.name_custom.empty() ) {
                     mvwprintz( w_colors, point( 30, i - iStartPos ), name_color_map[entry.name_custom].color,
                                entry.name_custom ); //custom color
                 }
                 mvwprintz( w_colors, point( 52, i - iStartPos ), entry.invert,
                            _( "default" ) ); //invert default color
                 if( !entry.name_invert_custom.empty() ) {
                     mvwprintz( w_colors, point( 61, i - iStartPos ), name_color_map[entry.name_invert_custom].color,
                                entry.name_invert_custom ); //invert custom color
                 }
             }
         }
         wnoutrefresh( w_colors );
     } );
     while( true ) {
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         const int recmax = iMaxColors;
         const int scroll_rate = recmax > 20 ? 10 : 3;
         if( action == "QUIT" ) {
             break;
         } else if( navigate_ui_list( action, iCurrentLine, scroll_rate, recmax, true ) ) {
         } else if( action == "LEFT" || action == "RIGHT" ) {
             iCurrentCol = inc_clamp_wrap( iCurrentCol, 1, iTotalCols );
         } else if( action == "REMOVE_CUSTOM" ) {
             color_manager::color_struct &entry = std::next( name_color_map.begin(), iCurrentLine )->second;
             if( iCurrentCol == 1 && !entry.name_custom.empty() ) {
                 bStuffChanged = true;
                 entry.name_custom.clear();
             } else if( iCurrentCol == 2 && !entry.name_invert_custom.empty() ) {
                 bStuffChanged = true;
                 entry.name_invert_custom.clear();
             }
             finalize(); // Need to recalculate caches
         } else if( action == "LOAD_TEMPLATE" ) {
             auto vFiles = get_files_from_path( ".json", PATH_INFO::color_templates(), false, true );
             if( !vFiles.empty() ) {
                 uilist ui_templates;
                 ui_templates.w_y_setup = [&]( int ) -> int {
                     return iHeaderHeight + 1 + calc_offset_y();
                 };
                 ui_templates.w_height_setup = 18;
                 ui_templates.text = _( "Color templates:" );
                 for( const cata_path &file : vFiles ) {
                     ui_templates.addentry( file.get_relative_path().filename().generic_u8string() );
                 }
                 ui_templates.query();
                 if( ui_templates.ret >= 0 && static_cast<size_t>( ui_templates.ret ) < vFiles.size() ) {
                     bStuffChanged = true;
                     clear();
                     load_default();
                     load_custom( vFiles[ui_templates.ret] );
                     name_color_map.clear();
                     for( const auto &pr : name_map ) {
                         name_color_map[pr.first] = color_array[pr.second];
                     }
                 }
             }
             finalize(); // Need to recalculate caches
         } else if( action == "LOAD_BASE_COLORS" ) {
             auto vFiles = get_files_from_path( ".json", PATH_INFO::color_themes(), false, true );
             if( !vFiles.empty() ) {
                 uilist ui_templates;
                 ui_templates.w_y_setup = [&]( int ) -> int {
                     return iHeaderHeight + 1 + calc_offset_y();
                 };
                 ui_templates.w_height_setup = 18;
                 ui_templates.text = _( "Color themes:" );
                 for( const cata_path &filename : vFiles ) {
                     ui_templates.addentry( filename.get_relative_path().filename().generic_u8string() );
                 }
                 ui_templates.query();
                 if( ui_templates.ret >= 0 && static_cast<size_t>( ui_templates.ret ) < vFiles.size() ) {
                     copy_file( vFiles[ui_templates.ret], PATH_INFO::base_colors() );
                 }
             }
         } else if( action == "CONFIRM" ) {
             uilist ui_colors;
             ui_colors.w_y_setup = [&]( int ) -> int {
                 return iHeaderHeight + 1 + calc_offset_y();
             };
             ui_colors.w_height_setup = 18;
             const color_manager::color_struct &entry = std::next( name_color_map.begin(),
                     iCurrentLine )->second;
             std::string sColorType = _( "Normal" );
             std::string sSelected = entry.name_custom;
             if( iCurrentCol == 2 ) {
                 sColorType = _( "Invert" );
                 sSelected = entry.name_invert_custom;
             }
             ui_colors.text = string_format( _( "Custom %s color:" ), sColorType );
             int i = 0;
             for( auto &iter : name_color_map ) {
                 std::string sColor = iter.first;
                 std::string sType = _( "default" );
                 std::string name_custom;
                 if( sSelected == sColor ) {
                     ui_colors.selected = i;
                 }
                 if( !iter.second.name_custom.empty() ) {
                     name_custom = " <color_" + iter.second.name_custom + ">" + iter.second.name_custom + "</color>";
                 }
                 ui_colors.addentry( string_format( "%-17s <color_%s>%s</color>%s", iter.first,
                                                    sColor, sType, name_custom ) );
                 i++;
             }
             ui_colors.query();
             if( ui_colors.ret >= 0 && static_cast<size_t>( ui_colors.ret ) < name_color_map.size() ) {
                 bStuffChanged = true;
                 auto iter = name_color_map.begin();
                 std::advance( iter, ui_colors.ret );
                 color_manager::color_struct &entry = std::next( name_color_map.begin(), iCurrentLine )->second;
                 if( iCurrentCol == 1 ) {
                     entry.name_custom = iter->first;
                 } else if( iCurrentCol == 2 ) {
                     entry.name_invert_custom = iter->first;
                 }
             }
             finalize(); // Need to recalculate caches
         }
     }
     if( bStuffChanged && query_yn( _( "Save changes?" ) ) ) {
         for( const auto &pr : name_color_map ) {
             color_id id = name_to_id( pr.first );
             color_array[id].name_custom = pr.second.name_custom;
             color_array[id].name_invert_custom = pr.second.name_invert_custom;
         }
         finalize();
         save_custom();
         clear();
         load_default();
         load_custom( {} );
     }
 }
References _, action, uilist::addentry(), PATH_INFO::base_colors(), BORDER_COLOR, c_black, c_white, c_yellow, calcStartPos(), clear(), color_manager::color_struct::color, color_array, PATH_INFO::color_templates(), PATH_INFO::color_themes(), copy_file(), draw_border(), draw_header(), draw_scrollbar(), file, finalize(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, get_files_from_path(), catacurses::getmaxx(), input_context::handle_input(), base_camps::id, inc_clamp_wrap(), color_manager::color_struct::invert, LINE_XOXO, LINE_XOXX, LINE_XXOX, LINE_XXXO, load_custom(), load_default(), min(), mvwprintz(), mvwputch(), color_manager::color_struct::name_custom, color_manager::color_struct::name_invert_custom, name_map, name_to_id(), navigate_ui_list(), catacurses::newwin(), point, point_south_east, uilist::query(), query_yn(), ui_manager::redraw(), input_context::register_action(), input_context::register_leftright(), input_context::register_navigate_ui_list(), uilist::ret, save_custom(), uilist::selected, string_format(), TERMX, TERMY, uilist::text, uilist::w_height_setup, uilist::w_y_setup, catacurses::wnoutrefresh(), point::x, and point::y.
Member Data Documentation
color_array
std::array<color_struct, num_colors> color_manager::color_array private
Definition at line 436 of file color.h.
Referenced by add_color(), clear(), color_to_id(), deserialize(), finalize(), get(), get_highlight(), get_invert(), get_random(), highlight_from_names(), id_to_name(), name_to_color(), serialize(), and show_gui().
inverted_map
std::unordered_map<nc_color, color_id> color_manager::inverted_map private
Definition at line 437 of file color.h.
Referenced by add_color(), clear(), color_to_id(), and finalize().
name_map
std::unordered_map<std::string, color_id> color_manager::name_map private
Definition at line 438 of file color.h.
Referenced by add_color(), clear(), name_to_id(), and show_gui().
The documentation for this class was generated from the following files:
src/color.h
src/color.cpp