Cataclysm DDA: jmapgen_sealed_item Class Reference
jmapgen_sealed_item Class Reference
Place an item in furniture (expected to be used with NOITEM SEALED furniture like plants).
Public Member Functions
jmapgen_sealed_item (const JsonObject &jsi, const std::string &context)
void check (const std::string &context, const mapgen_parameters &params, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z) const override
Sanity-check this piece.
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &context) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
Public Attributes
mapgen_value< furn_id > furniture
jmapgen_int chance
std::optional< jmapgen_spawn_item > item_spawner
std::optional< jmapgen_item_group > item_group_spawner
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place an item in furniture (expected to be used with NOITEM SEALED furniture like plants).
"item": item to spawn (object with usual parameters). "items": item group to spawn (object with usual parameters). "furniture": furniture to create around it.
Definition at line 3225 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_sealed_item()
jmapgen_sealed_item::jmapgen_sealed_item (const JsonObject & jsi, const std::string & context) inline
Definition at line 3232 of file mapgen.cpp.
             : furniture( jsi.get_member( "furniture" ) )
             , chance( jsi, "chance", 100, 100 ) {
             if( jsi.has_object( "item" ) ) {
                 JsonObject item_obj = jsi.get_object( "item" );
                 item_spawner = jmapgen_spawn_item( item_obj, "item for " + context );
             }
             if( jsi.has_object( "items" ) ) {
                 JsonObject items_obj = jsi.get_object( "items" );
                 item_group_spawner = jmapgen_item_group( items_obj, "items for " + context );
             }
         }
References context, JsonObject::get_object(), JsonObject::has_object(), item_group_spawner, item_spawner, and mapgen_defer::jsi.
Member Function Documentation
apply()
void jmapgen_sealed_item::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 3329 of file mapgen.cpp.
{
             const int c = chance.get();
             // 100% chance = always generate, otherwise scale by item spawn rate.
             // (except is capped at 1)
             const float spawn_rate = get_option<float>( "ITEM_SPAWNRATE" );
             if( !x_in_y( ( c == 100 ) ? 1 : c * spawn_rate / 100.0f, 1 ) ) {
                 return;
             }
             dat.m.furn_set( tripoint_bub_ms( x.get(), y.get(), dat.zlevel() + z.get() ),
                             furn_str_id::NULL_ID() );
             if( item_spawner ) {
                 item_spawner->apply( dat, x, y, z, context );
             }
             if( item_group_spawner ) {
                 item_group_spawner->apply( dat, x, y, z,  context );
             }
             furn_id chosen_furn = furniture.get( dat );
             dat.m.furn_set( tripoint_bub_ms( x.get(), y.get(), dat.zlevel() + z.get() ), chosen_furn );
         }
References c, chance, context, map::furn_set(), furniture, jmapgen_int::get(), item_group_spawner, item_spawner, mapgendata::m, string_id< furn_t >::NULL_ID(), x_in_y(), and mapgendata::zlevel().
check()
void jmapgen_sealed_item::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 3245 of file mapgen.cpp.
{
             std::string short_summary =
                 string_format( "sealed_item special in json mapgen for %s", context );
             if( !item_spawner && !item_group_spawner ) {
                 debugmsg( "%s specifies neither an item nor an item group.  "
                           "It should specify at least one.",
                           short_summary );
                 return;
             }
             for( const furn_str_id &f : furniture.all_possible_results( params ) ) {
                 std::string summary =
                     string_format( "%s using furniture %s", short_summary, f.str() );
                 if( !f.is_valid() ) {
                     debugmsg( "%s which is not valid furniture", summary );
                     return;
                 }
                 const furn_t &furn = *f;
                 if( furn.has_flag( ter_furn_flag::TFLAG_PLANT ) ) {
                     // plant furniture requires exactly one seed item within it
                     if( item_spawner && item_group_spawner ) {
                         debugmsg( "%s (with flag PLANT) specifies both an item and an item group.  "
                                   "It should specify exactly one.",
                                   summary );
                         return;
                     }
                     if( item_spawner ) {
                         item_spawner->check( context, params, x, y, z );
                         int count = item_spawner->amount.get();
                         if( count != 1 ) {
                             debugmsg( "%s (with flag PLANT) spawns %d items; it should spawn "
                                       "exactly one.", summary, count );
                             return;
                         }
                         int item_chance = item_spawner->chance.get();
                         if( item_chance != 100 ) {
                             debugmsg( "%s (with flag PLANT) spawns an item with probability %d%%; "
                                       "it should always spawn.  You can move the \"chance\" up to "
                                       "the sealed_item instead of the \"item\" within.",
                                       summary, item_chance );
                             return;
                         }
                         for( const itype_id &t :
                              item_spawner->type.all_possible_results( params ) ) {
                             const itype *spawned_type = item::find_type( t );
                             if( !spawned_type->seed ) {
                                 debugmsg( "%s (with flag PLANT) spawns item type %s which is not a "
                                           "seed.", summary, spawned_type->get_id().str() );
                                 return;
                             }
                         }
                     }
                     if( item_group_spawner ) {
                         item_group_spawner->check( context, params, x, y, z );
                         int ig_chance = item_group_spawner->chance.get();
                         if( ig_chance != 100 ) {
                             debugmsg( "%s (with flag PLANT) spawns item group %s with chance %d.  "
                                       "It should have chance 100.  You can move the \"chance\" up "
                                       "to the sealed_item instead of the \"items\" within.",
                                       summary, item_group_spawner->group_id.str(), ig_chance );
                             return;
                         }
                         item_group_id group_id = item_group_spawner->group_id;
                         for( const itype *type :
                              item_group::every_possible_item_from( group_id ) ) {
                             if( !type->seed ) {
                                 debugmsg( "%s (with flag PLANT) spawns item group %s which can "
                                           "spawn item %s which is not a seed.",
                                           summary, group_id.str(), type->get_id().str() );
                                 return;
                             }
                         }
                     }
                 }
             }
         }
References context, debugmsg, item_group::every_possible_item_from(), item::find_type(), furniture, itype::get_id(), map_data_common_t::has_flag(), item_group_spawner, item_spawner, itype::seed, string_id< T >::str(), string_format(), TFLAG_PLANT, and type.
has_vehicle_collision()
bool jmapgen_sealed_item::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 3351 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint_bub_ms( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
Member Data Documentation
chance
jmapgen_int jmapgen_sealed_item::chance
Definition at line 3229 of file mapgen.cpp.
Referenced by apply().
furniture
mapgen_value<furn_id> jmapgen_sealed_item::furniture
Definition at line 3228 of file mapgen.cpp.
Referenced by apply(), and check().
item_group_spawner
std::optional<jmapgen_item_group> jmapgen_sealed_item::item_group_spawner
Definition at line 3231 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_sealed_item().
item_spawner
std::optional<jmapgen_spawn_item> jmapgen_sealed_item::item_spawner
Definition at line 3230 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_sealed_item().
The documentation for this class was generated from the following file:
src/mapgen.cpp