Cataclysm DDA: recipe_subset Class Reference
recipe_subset Class Reference
#include <recipe_dictionary.h>
Public Types
enum class search_type : int {
name , exclude_name , skill , primary_skill ,
component , tool , quality , quality_result ,
description_result , proficiency , difficulty , activity_level
}
Public Member Functions
recipe_subset ()=default
recipe_subset (const recipe_subset &src, const std::vector< const recipe * > &recipes)
void include (const recipe *r, int custom_difficulty=-1)
Include a recipe to the subset.
void include (const recipe_subset &subset)
void remove (const recipe *r)
template<class Predicate >
void include_if (const recipe_subset &subset, Predicate pred)
Include a recipe to the subset.
bool contains (const recipe *r) const
Check if the subset contains a recipe with the specified id.
int get_custom_difficulty (const recipe *r) const
Get custom difficulty for the recipe.
bool empty_category (const std::string &cat, const std::string &subcat=std::string()) const
Check if there is any recipes in given category (optionally restricted to subcategory), index which is for nested categories.
std::vector< const recipe * > in_category (const std::string &cat, const std::string &subcat=std::string()) const
Get all recipes in given category (optionally restricted to subcategory)
const std::set< const recipe * > & of_component (const itype_id &id) const
Returns all recipes which could use component.
std::vector< const recipe * > favorite () const
Find marked favorite recipes.
std::vector< const recipe * > recent () const
Find recently used recipes.
std::vector< const recipe * > hidden () const
Find hidden recipes.
std::vector< const recipe * > expanded () const
Find expanded recipes.
std::vector< const recipe * > search (std::string_view txt, search_type key=search_type::name, const std::function< void(size_t, size_t)> &progress_callback={}) const
Find recipes matching query (left anchored partial matches are supported)
recipe_subset reduce (std::string_view txt, search_type key=search_type::name, const std::function< void(size_t, size_t)> &progress_callback={}) const
Find recipes matching query and return a new recipe_subset.
recipe_subset intersection (const recipe_subset &subset) const
Set intersection between recipe_subsets.
recipe_subset difference (const recipe_subset &subset) const
Set difference between recipe_subsets.
recipe_subset difference (const std::set< const recipe * > &recipe_set) const
std::vector< const recipe * > recipes_that_produce (const itype_id &item) const
Find recipes producing the item.
size_t size () const
void clear ()
std::set< const recipe * >::const_iterator begin () const
std::set< const recipe * >::const_iterator end () const
Private Attributes
std::set< const recipe * > recipes
std::map< const recipe *, int > difficulties
std::map< std::string, std::set< const recipe * > > category
std::map< itype_id, std::set< const recipe * > > component
Detailed Description
Definition at line 90 of file recipe_dictionary.h.
Member Enumeration Documentation
search_type
enum recipe_subset::search_type : int strong
Enumerator
name
exclude_name
skill
primary_skill
component
tool
quality
quality_result
description_result
proficiency
difficulty
activity_level
Definition at line 141 of file recipe_dictionary.h.
                                : int {
             name,
             exclude_name,
             skill,
             primary_skill,
             component,
             tool,
             quality,
             quality_result,
             description_result,
             proficiency,
             difficulty,
             activity_level
         };
Constructor & Destructor Documentation
recipe_subset() [1/2]
recipe_subset::recipe_subset () default
Referenced by difference(), intersection(), and reduce().
recipe_subset() [2/2]
recipe_subset::recipe_subset (const recipe_subset & src, const std::vector< const recipe * > & recipes)
Definition at line 301 of file recipe_dictionary.cpp.
 {
     for( const recipe *elem : recipes ) {
         include( elem, src.get_custom_difficulty( elem ) );
     }
 }
References get_custom_difficulty(), include(), and recipes.
Member Function Documentation
begin()
std::set<const recipe *>::const_iterator recipe_subset::begin () const inline
Definition at line 194 of file recipe_dictionary.h.
{
             return recipes.begin();
         }
References recipes.
Referenced by iuse::binder_add_recipe(), difference(), and intersection().
clear()
void recipe_subset::clear () inline
Definition at line 188 of file recipe_dictionary.h.
                      {
             component.clear();
             category.clear();
             recipes.clear();
         }
References category, and recipes.
Referenced by deserialize().
contains()
bool recipe_subset::contains (const recipe * r) const inline
Check if the subset contains a recipe with the specified id.
Definition at line 118 of file recipe_dictionary.h.
{
             return std::any_of( recipes.begin(), recipes.end(), [r]( const recipe * elem ) {
                 return elem->ident() == r->ident();
             } );
         }
References recipes.
Referenced by check_nested_has_recipes(), Character::has_recipe(), Character::knows_recipe(), list_nested(), rate_action_view_recipe(), recursively_expance_recipes(), and activity_handlers::view_recipe_do_turn().
difference() [1/2]
recipe_subset recipe_subset::difference (const recipe_subset & subset) const
Set difference between recipe_subsets.
Definition at line 321 of file recipe_dictionary.cpp.
 {
     return difference( subset.recipes );
 }
References recipes.
Referenced by filter_recipes().
difference() [2/2]
recipe_subset recipe_subset::difference (const std::set< const recipe * > & recipe_set) const
Definition at line 325 of file recipe_dictionary.cpp.
 {
     std::vector<const recipe *> difference_result;
     std::set_difference( this->begin(), this->end(), recipe_set.begin(), recipe_set.end(),
                          std::back_inserter( difference_result ) );
     return recipe_subset( *this, difference_result );
 }
References begin(), end(), and recipe_subset().
empty_category()
bool recipe_subset::empty_category (const std::string & cat, const std::string & subcat = std::string()) const
Check if there is any recipes in given category (optionally restricted to subcategory), index which is for nested categories.
Definition at line 344 of file recipe_dictionary.cpp.
 {
     if( subcat == "CSC_*_FAVORITE" ) {
         return uistate.favorite_recipes.empty();
     } else if( subcat == "CSC_*_RECENT" ) {
         return uistate.recent_recipes.empty();
     } else if( subcat == "CSC_*_HIDDEN" ) {
         return uistate.hidden_recipes.empty();
     } else if( cat == "CC_*" ) {
         //any other category in CC_* is populated
         return false;
     }
     auto iter = category.find( cat );
     if( iter != category.end() ) {
         if( subcat.empty() ) {
             return false;
         } else {
             for( const recipe *e : iter->second ) {
                 if( e->subcategory == subcat ) {
                     return false;
                 }
             }
         }
     }
     return true;
 }
References category, uistatedata::favorite_recipes, uistatedata::hidden_recipes, uistatedata::recent_recipes, recipe::subcategory, and uistate.
Referenced by draw_recipe_subtabs().
end()
std::set<const recipe *>::const_iterator recipe_subset::end () const inline
Definition at line 198 of file recipe_dictionary.h.
{
             return recipes.end();
         }
References recipes.
Referenced by iuse::binder_add_recipe(), difference(), intersection(), and search().
expanded()
std::vector< const recipe * > recipe_subset::expanded () const
Find expanded recipes.
Definition at line 140 of file recipe_dictionary.cpp.
 {
     std::vector<const recipe *> res;
     std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ), [&]( const recipe * r ) {
         if( !*r || r->obsolete ) {
             return false;
         }
         return uistate.expanded_recipes.find( r->ident() ) != uistate.expanded_recipes.end();
     } );
     return res;
 }
References uistatedata::expanded_recipes, recipe::ident(), recipes, and uistate.
favorite()
std::vector< const recipe * > recipe_subset::favorite () const
Find marked favorite recipes.
Definition at line 112 of file recipe_dictionary.cpp.
 {
     std::vector<const recipe *> res;
     std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ), [&]( const recipe * r ) {
         if( !*r || r->obsolete ) {
             return false;
         }
         return uistate.favorite_recipes.find( r->ident() ) != uistate.favorite_recipes.end();
     } );
     return res;
 }
References uistatedata::favorite_recipes, recipe::ident(), recipes, and uistate.
Referenced by recipes_from_cat().
get_custom_difficulty()
int recipe_subset::get_custom_difficulty (const recipe * r) const
Get custom difficulty for the recipe.
Returns
Either custom difficulty if it was specified, or recipe default difficulty.
Definition at line 781 of file recipe_dictionary.cpp.
 {
     const auto iter = difficulties.find( r );
     if( iter != difficulties.end() ) {
         return iter->second;
     }
     return r->difficulty;
 }
References difficulties, and recipe::difficulty.
Referenced by include(), and recipe_subset().
hidden()
std::vector< const recipe * > recipe_subset::hidden () const
Find hidden recipes.
Definition at line 126 of file recipe_dictionary.cpp.
 {
     std::vector<const recipe *> res;
     std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ), [&]( const recipe * r ) {
         if( !*r || r->obsolete ) {
             return false;
         }
         return uistate.hidden_recipes.find( r->ident() ) != uistate.hidden_recipes.end();
     } );
     return res;
 }
References uistatedata::hidden_recipes, recipe::ident(), recipes, and uistate.
Referenced by recipes_from_cat().
in_category()
std::vector< const recipe * > recipe_subset::in_category (const std::string & cat, const std::string & subcat = std::string()) const
Get all recipes in given category (optionally restricted to subcategory)
Definition at line 372 of file recipe_dictionary.cpp.
 {
     std::vector<const recipe *> res;
     auto iter = category.find( cat );
     if( iter != category.end() ) {
         if( subcat.empty() ) {
             std::copy_if( iter->second.begin(), iter->second.end(),
             std::back_inserter( res ), [&]( const recipe * e ) {
                 return !e->obsolete;
             } );
         } else {
             std::copy_if( iter->second.begin(), iter->second.end(),
             std::back_inserter( res ), [&subcat]( const recipe * e ) {
                 if( e->obsolete ) {
                     return false;
                 }
                 return e->subcategory == subcat;
             } );
         }
     }
     return res;
 }
References category, and recipe::subcategory.
Referenced by recipes_from_cat(), and select_crafter_and_crafting_recipe().
include() [1/2]
void recipe_subset::include (const recipe * r, int custom_difficulty = -1)
Include a recipe to the subset.
Parameters
r recipe to include
custom_difficulty If specified, it defines custom difficulty for the recipe
Definition at line 734 of file recipe_dictionary.cpp.
 {
     if( custom_difficulty < 0 ) {
         custom_difficulty = r->difficulty;
     }
     // We always prefer lower difficulty for the subset, but we save it only if it's not default
     if( recipes.count( r ) > 0 ) {
         const auto iter = difficulties.find( r );
         // See if we need to lower the difficulty of the existing recipe
         if( iter != difficulties.end() && custom_difficulty < iter->second ) {
             if( custom_difficulty != r->difficulty ) {
                 iter->second = custom_difficulty; // Added again with lower difficulty
             } else {
                 difficulties.erase( iter ); // No need to keep the default difficulty. Free some memory
             }
         } else if( custom_difficulty < r->difficulty ) {
             difficulties[r] = custom_difficulty; // Added again with lower difficulty
         }
     } else {
         // add recipe to category and component caches
         for( const auto &opts : r->simple_requirements().get_components() ) {
             for( const item_comp &comp : opts ) {
                 component[comp.type].insert( r );
             }
         }
         category[r->category].insert( r );
         // Set the difficulty is it's not the default
         if( custom_difficulty != r->difficulty ) {
             difficulties[r] = custom_difficulty;
         }
         // insert the recipe
         recipes.insert( r );
     }
 }
References recipe::category, category, difficulties, recipe::difficulty, requirement_data::get_components(), recipes, second, and recipe::simple_requirements().
Referenced by deserialize(), filter_recipes(), Character::get_available_nested(), Character::get_available_recipes(), Character::get_group_available_recipes(), Character::get_recipes_from_books(), Character::get_recipes_from_ebooks(), include(), include_if(), and recipe_subset().
include() [2/2]
void recipe_subset::include (const recipe_subset & subset)
Definition at line 774 of file recipe_dictionary.cpp.
 {
     for( const recipe * const &elem : subset ) {
         include( elem, subset.get_custom_difficulty( elem ) );
     }
 }
References get_custom_difficulty(), and include().
include_if()
template<class Predicate > void recipe_subset::include_if (const recipe_subset & subset, Predicate pred) inline
Include a recipe to the subset.
Based on the condition.
Parameters
subset Where to included the recipe
pred Unary predicate that accepts a recipe.
Definition at line 109 of file recipe_dictionary.h.
{
             for( const recipe * const &elem : subset ) {
                 if( pred( *elem ) ) {
                     include( elem );
                 }
             }
         }
References include().
Referenced by Character::get_available_recipes().
intersection()
recipe_subset recipe_subset::intersection (const recipe_subset & subset) const
Set intersection between recipe_subsets.
Definition at line 314 of file recipe_dictionary.cpp.
 {
     std::vector<const recipe *> intersection_result;
     std::set_intersection( this->begin(), this->end(), subset.begin(), subset.end(),
                            std::back_inserter( intersection_result ) );
     return recipe_subset( *this, intersection_result );
 }
References begin(), end(), and recipe_subset().
Referenced by filter_recipes().
of_component()
const std::set< const recipe * > & recipe_subset::of_component (const itype_id & id) const
Returns all recipes which could use component.
Definition at line 396 of file recipe_dictionary.cpp.
 {
     auto iter = component.find( id );
     return iter != component.end() ? iter->second : null_match;
 }
References null_match.
Referenced by item::final_info(), and peek_related_recipe().
recent()
std::vector< const recipe * > recipe_subset::recent () const
Find recently used recipes.
Definition at line 154 of file recipe_dictionary.cpp.
 {
     std::vector<const recipe *> res;
     for( auto rec_id = uistate.recent_recipes.rbegin(); rec_id != uistate.recent_recipes.rend();
          ++rec_id ) {
         std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ),
         [&rec_id]( const recipe * r ) {
             return *r && !( *rec_id != r->ident() || r->obsolete );
         } );
     }
     return res;
 }
References uistatedata::recent_recipes, recipes, and uistate.
Referenced by recipes_from_cat().
recipes_that_produce()
std::vector< const recipe * > recipe_subset::recipes_that_produce (const itype_id & item) const
Find recipes producing the item.
Definition at line 333 of file recipe_dictionary.cpp.
 {
     std::vector<const recipe *> res;
     std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ), [&]( const recipe * r ) {
         return !r->obsolete && ( item == r->result() || r->in_byproducts( item ) );
     } );
     return res;
 }
References recipes.
Referenced by filter_recipes().
reduce()
recipe_subset recipe_subset::reduce (std::string_view txt, search_type key = search_type::name, const std::function< void(size_t, size_t)> & progress_callback = {}) const
Find recipes matching query and return a new recipe_subset.
Definition at line 308 of file recipe_dictionary.cpp.
 {
     return recipe_subset( *this, search( txt, key, progress_callback ) );
 }
References recipe_subset(), and search().
Referenced by filter_recipes().
remove()
void recipe_subset::remove (const recipe * r)
Definition at line 769 of file recipe_dictionary.cpp.
 {
     recipes.erase( r );
 }
References recipes.
search()
std::vector< const recipe * > recipe_subset::search (std::string_view txt, search_type key = search_type::name, const std::function< void(size_t, size_t)> & progress_callback = {}) const
Find recipes matching query (left anchored partial matches are supported)
Definition at line 169 of file recipe_dictionary.cpp.
 {
     auto predicate = [&]( const recipe * r ) {
         if( !*r || r->obsolete ) {
             return false;
         }
         switch( key ) {
             case search_type::name:
                 return lcmatch( r->result_name(), txt );
             case search_type::exclude_name:
                 return !lcmatch( r->result_name(), txt );
             case search_type::skill: {
                 if( r->skill_used && lcmatch( r->skill_used->name(), txt ) ) {
                     return true;
                 }
                 const auto &skills = r->required_skills;
                 return std::any_of( skills.begin(), skills.end(), [&]( const std::pair<skill_id, int> &e ) {
                     return lcmatch( e.first->name(), txt );
                 } );
             }
             case search_type::primary_skill:
                 return lcmatch( r->skill_used->name(), txt );
             case search_type::component:
                 return search_reqs( r->simple_requirements().get_components(), txt );
             case search_type::tool:
                 return search_reqs( r->simple_requirements().get_tools(), txt );
             case search_type::quality:
                 return search_reqs( r->simple_requirements().get_qualities(), txt );
             case search_type::quality_result: {
                 return item::find_type( r->result() )->has_any_quality( txt );
             }
             case search_type::description_result: {
                 if( r->is_practice() ) {
                     return lcmatch( r->description.translated(), txt );
                 } else {
                     const item result( r->result() );
                     return lcmatch( remove_color_tags( result.info( true ) ), txt );
                 }
             }
             case search_type::proficiency:
                 return lcmatch( r->recipe_proficiencies_string(), txt );
             case search_type::difficulty: {
                 std::string range_start;
                 std::string range_end;
                 bool use_range = false;
                 for( const char &chr : txt ) {
                     if( std::isdigit( chr ) ) {
                         if( use_range ) {
                             range_end += chr;
                         } else {
                             range_start += chr;
                         }
                     } else if( chr == '~' ) {
                         use_range = true;
                     } else {
                         // unexpected character
                         return true;
                     }
                 }
                 int start = 0;
                 int end = INT_MAX;
                 if( use_range ) {
                     if( !range_start.empty() ) {
                         start = std::stoi( range_start );
                     }
                     if( !range_end.empty() ) {
                         end = std::stoi( range_end );
                     }
                     if( range_start.empty() && range_end.empty() ) {
                         return true;
                     }
                 } else {
                     if( !range_start.empty() ) {
                         start = std::stoi( range_start );
                     }
                     if( range_start.empty() && range_end.empty() ) {
                         return true;
                     }
                 }
                 if( use_range && start > end ) {
                     std::swap( start, end );
                 }
                 if( use_range ) {
                     // check if number is between two numbers inclusive
                     return r->difficulty == clamp( r->difficulty, start, end );
                 } else {
                     return r->difficulty == start;
                 }
             }
             case search_type::activity_level:
                 return lcmatch( display::activity_level_str( r->exertion_level() ), txt );
             default:
                 return false;
         }
     };
     std::vector<const recipe *> res;
     size_t i = 0;
     for( const recipe *r : recipes ) {
         if( progress_callback ) {
             progress_callback( i, recipes.size() );
         }
         if( predicate( r ) ) {
             res.push_back( r );
         }
         ++i;
     }
     return res;
 }
References activity_level, display::activity_level_str(), clamp(), component, description_result, difficulty, end(), exclude_name, item::find_type(), itype::has_any_quality(), item::info(), lcmatch(), name, primary_skill, proficiency, quality, quality_result, recipes, remove_color_tags(), search_reqs(), skill, cata::swap(), and tool.
Referenced by reduce().
size()
size_t recipe_subset::size () const inline
Definition at line 184 of file recipe_dictionary.h.
{
             return recipes.size();
         }
References recipes.
Member Data Documentation
category
std::map<std::string, std::set<const recipe *> > recipe_subset::category private
Definition at line 205 of file recipe_dictionary.h.
Referenced by clear(), empty_category(), in_category(), and include().
component
std::map<itype_id, std::set<const recipe *> > recipe_subset::component private
Definition at line 206 of file recipe_dictionary.h.
difficulties
std::map<const recipe *, int> recipe_subset::difficulties private
Definition at line 204 of file recipe_dictionary.h.
Referenced by get_custom_difficulty(), and include().
recipes
std::set<const recipe *> recipe_subset::recipes private
Definition at line 203 of file recipe_dictionary.h.
Referenced by begin(), clear(), contains(), difference(), end(), expanded(), favorite(), hidden(), include(), recent(), recipe_subset(), recipes_that_produce(), remove(), search(), and size().
The documentation for this class was generated from the following files:
src/recipe_dictionary.h
src/recipe_dictionary.cpp