Cataclysm DDA: shearing_data Class Reference
shearing_data Class Reference
#include <shearing.h>
Public Member Functions
shearing_data ()=default
shearing_data (std::vector< shearing_entry > &shearing_entries)
bool valid () const
const std::vector< shearing_entry > & entries () const
std::vector< shearing_roll > roll_all (const monster &mon) const
Private Attributes
bool valid_ = false
std::vector< shearing_entry > entries_
Detailed Description
Definition at line 32 of file shearing.h.
Constructor & Destructor Documentation
shearing_data() [1/2]
shearing_data::shearing_data () default
shearing_data() [2/2]
shearing_data::shearing_data (std::vector< shearing_entry > & shearing_entries) explicit
Definition at line 57 of file shearing.cpp.
 {
     if( !shearing_entries.empty() ) {
         entries_ = shearing_entries;
         valid_ = true;
     }
 }
References entries_, and valid_.
Member Function Documentation
entries()
const std::vector<shearing_entry>& shearing_data::entries () const inline
Definition at line 42 of file shearing.h.
{
             return entries_;
         }
References entries_.
roll_all()
std::vector< shearing_roll > shearing_data::roll_all (const monster & mon) const
Definition at line 65 of file shearing.cpp.
 {
     std::vector<shearing_roll> rolls;
     rolls.reserve( entries_.size() );
     for( const shearing_entry &entry : entries_ ) {
         rolls.push_back( entry.roll( mon ) );
     }
     return rolls;
 }
References entries_.
Referenced by shearing_activity_actor::finish().
valid()
bool shearing_data::valid () const inline
Definition at line 38 of file shearing.h.
{
             return valid_;
         }
References valid_.
Referenced by shearing_activity_actor::finish(), and monster::shearable().
Member Data Documentation
entries_
std::vector<shearing_entry> shearing_data::entries_ private
Definition at line 50 of file shearing.h.
Referenced by entries(), roll_all(), and shearing_data().
valid_
bool shearing_data::valid_ = false private
Definition at line 49 of file shearing.h.
Referenced by shearing_data(), and valid().
The documentation for this class was generated from the following files:
src/shearing.h
src/shearing.cpp