Cataclysm DDA: inventory Class Reference
inventory Class Reference
#include <inventory.h>
Public Member Functions
invslice slice ()
const_invslice const_slice () const
const std::list< item > & const_stack (int i) const
size_t size () const
inventory ()
inventory (inventory &&) noexcept=default
inventory (const inventory &)=default
inventory & operator= (inventory &&)=default
inventory & operator= (const inventory &)=default
inventory & operator+= (const inventory &rhs)
inventory & operator+= (const item &rhs)
inventory & operator+= (const std::list< item > &rhs)
inventory & operator+= (const item_components &rhs)
inventory & operator+= (const std::vector< item > &rhs)
inventory & operator+= (const item_stack &rhs)
inventory operator+ (const inventory &rhs)
inventory operator+ (const item &rhs)
inventory operator+ (const std::list< item > &rhs)
inventory operator+ (const item_components &rhs)
void unsort ()
void clear ()
void push_back (const std::list< item > &newits)
item & add_item (item newit, bool keep_invlet=false, bool assign_invlet=true, bool should_stack=true)
void add_item_keep_invlet (const item &newit)
void push_back (const item &newit)
item * provide_pseudo_item (const item &tool)
item * provide_pseudo_item (const itype_id &tool_type)
void restack (Character &p)
void form_from_zone (map &m, std::unordered_set< tripoint_abs_ms > &zone_pts, const Character *pl=nullptr, bool assign_invlet=true)
void form_from_map (const tripoint &origin, int range, const Character *pl=nullptr, bool assign_invlet=true, bool clear_path=true)
void form_from_map (map &m, const tripoint &origin, int range, const Character *pl=nullptr, bool assign_invlet=true, bool clear_path=true)
void form_from_map (map &m, std::vector< tripoint > pts, const Character *pl, bool assign_invlet=true)
item remove_item (const item *it)
Remove a specific item from the inventory.
item remove_item (int position)
std::list< item > remove_randomly_by_volume (const units::volume &volume)
Randomly select items until the volume quota is filled.
std::list< item > reduce_stack (int position, int quantity)
const item & find_item (int position) const
item & find_item (int position)
int position_by_item (const item *it) const
Returns the item position of the stack that contains the given item (compared by pointers).
int position_by_type (const itype_id &type) const
int invlet_to_position (char invlet) const
Return the item position of the item with given invlet, return INT_MIN if the inventory does not have such an item with that invlet.
std::list< item > use_amount (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >)
int worst_item_value (npc *p) const
bool has_enough_painkiller (int pain) const
item * most_appropriate_painkiller (int pain)
void rust_iron_items ()
units::mass weight () const
units::mass weight_without (const std::map< const item *, int > &) const
units::volume volume () const
units::volume volume_without (const std::map< const item *, int > &) const
void dump (std::vector< item * > &dest)
void dump (std::vector< const item * > &dest) const
void json_load_invcache (const JsonValue &jsin)
void json_load_items (const JsonArray &ja)
void json_save_invcache (JsonOut &json) const
void json_save_items (JsonOut &json) const
void assign_empty_invlet (item &it, const Character &p, bool force=false)
void reassign_item (item &it, char invlet, bool remove_old=true)
void update_invlet (item &it, bool assign_invlet=true, const item *ignore_invlet_collision_with=nullptr)
invlets_bitset allocated_invlets () const
const itype_bin & get_binned_items () const
Returns visitable items binned by their itype.
void update_cache_with_item (item &newit)
void copy_invlet_of (const inventory &other)
enchant_cache get_active_enchantment_cache (const Character &owner) const
int count_item (const itype_id &item_type) const
book_proficiency_bonuses get_book_proficiency_bonuses () const
bool has_quality (const quality_id &qual, int level=1, int qty=1) const override
Returns true if instance has amount (or more) items of at least quality level.
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const override
Traverses this object and any child items contained using a visitor pattern.
std::list< item > remove_items_with (const std::function< bool(const item &)> &filter, int count=INT_MAX) override
Removes items contained by this instance which match the filter.
int charges_of (const itype_id &what, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >, const std::function< void(int)> &visitor=nullptr, bool in_tools=false) const override
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo=true, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >) const override
Count items matching id including both this instance and any contained items.
std::pair< int, int > kcal_range (const itype_id &id, const std::function< bool(const item &)> &filter, Character &player_character) const
bool must_use_liq_container (const itype_id &id, int to_use) const
bool must_use_hallu_poison (const itype_id &id, int to_use) const
void update_liq_container_count (const itype_id &id, int count)
void replace_liq_container_count (const std::map< itype_id, int > &newmap, bool use_max=false)
Public Member Functions inherited from visitable
item remove_item (item &it)
Removes and returns the item which must be contained by this instance.
Public Member Functions inherited from read_only_visitable
item * find_parent (const item &it) const
Determine the immediate parent container (if any) for an item.
std::vector< item * > parents (const item &it) const
Returns vector of parent containers (if any) starting with the innermost.
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
std::pair< int, int > kcal_range (const itype_id &id, const std::function< bool(const item &)> &filter, Character &player_character) const
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
virtual ~read_only_visitable ()=default
bool has_tools (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
bool has_components (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
virtual bool has_charges (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
Public Attributes
std::map< char, itype_id > assigned_invlet
Private Member Functions
char find_usable_cached_invlet (const itype_id &item_type)
Private Attributes
invlet_favorites invlet_cache
invstack items
std::map< itype_id, int > max_empty_liq_cont
std::set< itype_id > provisioned_pseudo_tools
bool binned = false
itype_bin binned_items
Items binned by their type.
std::map< quality_query, bool > qualities_cache
Additional Inherited Members
Related Functions inherited from visitable
item * find_parent (const item &it) const
std::vector< item * > parents (const item &it) const
bool has_item (const item &it) const
bool has_item_with (const std::function< bool(const item &)> &filter) const
bool has_quality (const quality_id &qual, int level, int qty) const
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const
Traverses this object and any child items contained using a visitor pattern.
std::list< item > remove_items_with (const std::function< bool(const item &e)> &filter, int count)
int charges_of (const itype_id &what, int limit, const std::function< bool(const item &)> &filter, const std::function< void(int)> &visitor, bool in_tools) const
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo, int limit, const std::function< bool(const item &)> &filter) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo, const std::function< bool(const item &)> &filter) const
Detailed Description
Definition at line 107 of file inventory.h.
Constructor & Destructor Documentation
inventory() [1/3]
inventory::inventory () default
Referenced by operator+().
inventory() [2/3]
inventory::inventory (inventory &&) default noexcept
inventory() [3/3]
inventory::inventory (const inventory &) default
Member Function Documentation
add_item()
item & inventory::add_item (item newit, bool keep_invlet = false, bool assign_invlet = true, bool should_stack = true)
Definition at line 301 of file inventory.cpp.
 {
     binned = false;
     Character &player_character = get_player_character();
     if( should_stack ) {
         // See if we can't stack this item.
         for( auto &elem : items ) {
             std::list<item>::iterator it_ref = elem.begin();
             if( it_ref->stacks_with( newit ) ) {
                 if( it_ref->merge_charges( newit ) ) {
                     return *it_ref;
                 }
                 if( it_ref->invlet == '\0' ) {
                     if( !keep_invlet ) {
                         update_invlet( newit, assign_invlet );
                     }
                     update_cache_with_item( newit );
                     it_ref->invlet = newit.invlet;
                 } else {
                     newit.invlet = it_ref->invlet;
                 }
                 elem.emplace_back( std::move( newit ) );
                 return elem.back();
             } else if( keep_invlet && assign_invlet && it_ref->invlet == newit.invlet ) {
                 // If keep_invlet is true, we'll be forcing other items out of their current invlet.
                 assign_empty_invlet( *it_ref, player_character );
             }
         }
     }
     // Couldn't stack the item, proceed.
     if( !keep_invlet ) {
         update_invlet( newit, assign_invlet );
     }
     update_cache_with_item( newit );
     items.emplace_back( std::list<item> { std::move( newit ) } );
     return items.back().back();
 }
References assign_empty_invlet(), binned, get_player_character(), item::invlet, items, update_cache_with_item(), and update_invlet().
Referenced by add_item_keep_invlet(), basecamp::form_crafting_inventory(), form_from_map(), vpart_position::form_inventory(), om_set_hide_site(), operator+=(), provide_pseudo_item(), push_back(), and restack().
add_item_keep_invlet()
void inventory::add_item_keep_invlet (const item & newit)
Definition at line 342 of file inventory.cpp.
 {
     add_item( newit, true );
 }
References add_item().
allocated_invlets()
invlets_bitset inventory::allocated_invlets () const
Definition at line 1108 of file inventory.cpp.
 {
     invlets_bitset invlets;
     for( const auto &stack : items ) {
         const char invlet = stack.front().invlet;
         invlets.set( invlet );
     }
     invlets[0] = false;
     return invlets;
 }
References items.
amount_of()
int inventory::amount_of (const itype_id & what, bool pseudo = true, int limit = INT_MAX, const std::function< bool(const item &)> & filter = return_true< item >) const override virtual
Count items matching id including both this instance and any contained items.
Parameters
what ID of items to count. "any" will count all items (usually used with a filter)
pseudo whether pseudo-items (from map/vehicle tiles, bionics etc) are considered
limit stop searching after this many matches
filter only count items that match the filter
Note
items must be empty to be considered a match
Reimplemented from read_only_visitable.
Referenced by npc_attack_throw::evaluate(), Character::get_books_for_recipe(), repair_item_actor::handle_components(), repair_inventory_preset::repair_inventory_preset(), and repair_item_finish().
assign_empty_invlet()
void inventory::assign_empty_invlet (item & it, const Character & p, bool force = false)
Definition at line 1004 of file inventory.cpp.
 {
     const std::string auto_setting = get_option<std::string>( "AUTO_INV_ASSIGN" );
     if( auto_setting == "disabled" || ( ( auto_setting == "favorites" ) && !it.is_favorite ) ) {
         return;
     }
     invlets_bitset cur_inv = p.allocated_invlets();
     itype_id target_type = it.typeId();
     for( const auto &iter : assigned_invlet ) {
         if( iter.second == target_type && !cur_inv[iter.first] ) {
             it.invlet = iter.first;
             return;
         }
     }
     if( cur_inv.count() < inv_chars.size() ) {
         // XXX YUCK I don't know how else to get the keybindings
         // FIXME: Find a better way to get bound keys
         inventory_selector selector( get_avatar() );
         for( const char &inv_char : inv_chars ) {
             if( assigned_invlet.count( inv_char ) ) {
                 // don't overwrite assigned keys
                 continue;
             }
             if( selector.action_bound_to_key( inv_char ) != "ERROR" ) {
                 // don't auto-assign bound keys
                 continue;
             }
             if( !cur_inv[inv_char] ) {
                 it.invlet = inv_char;
                 return;
             }
         }
     }
     if( !force ) {
         it.invlet = 0;
         return;
     }
     // No free hotkey exist, re-use some of the existing ones
     for( auto &elem : items ) {
         item &o = elem.front();
         if( o.invlet != 0 ) {
             it.invlet = o.invlet;
             o.invlet = 0;
             return;
         }
     }
     debugmsg( "could not find a hotkey for %s", it.tname() );
 }
References inventory_selector::action_bound_to_key(), Character::allocated_invlets(), assigned_invlet, debugmsg, force, get_avatar(), inv_chars(), item::invlet, item::is_favorite, items, item::tname(), and item::typeId().
Referenced by add_item(), restack(), and update_invlet().
charges_of()
int inventory::charges_of (const itype_id & what, int limit = INT_MAX, const std::function< bool(const item &)> & filter = return_true< item >, const std::function< void(int)> & visitor = nullptr, bool in_tools = false) const override virtual
Count maximum available charges from this instance and any contained items.
Parameters
what ID of item to count charges of
limit stop searching after this many charges have been found
filter only count charges of items that match the filter
visitor is called when UPS charge is used (parameter is the charge itself)
Reimplemented from read_only_visitable.
Referenced by npc_attack_throw::evaluate(), repair_item_actor::handle_components(), repair_inventory_preset::repair_inventory_preset(), repair_item_finish(), iexamine::smoker_options(), and iuse::wash_items().
clear()
void inventory::clear ()
Definition at line 251 of file inventory.cpp.
 {
     items.clear();
     max_empty_liq_cont.clear();
     binned = false;
     qualities_cache.clear();
 }
References binned, items, max_empty_liq_cont, and qualities_cache.
Referenced by talk_function::companion_return(), basecamp::finish_return(), basecamp::form_crafting_inventory(), and npc::import_and_clean().
const_slice()
const_invslice inventory::const_slice () const
Definition at line 142 of file inventory.cpp.
 {
     const_invslice stacks;
     for( const auto &item : items ) {
         stacks.push_back( &item );
     }
     return stacks;
 }
References items.
Referenced by Character::get_recipes_from_books(), and Character::get_recipes_from_ebooks().
const_stack()
const std::list< item > & inventory::const_stack (int i) const
Definition at line 151 of file inventory.cpp.
 {
     if( i < 0 || i >= static_cast<int>( items.size() ) ) {
         debugmsg( "Attempted to access stack %d in an inventory (size %d)", i, items.size() );
         static const std::list<item> nullstack{};
         return nullstack;
     }
     invstack::const_iterator iter = items.begin();
     for( int j = 0; j < i; ++j ) {
         ++iter;
     }
     return *iter;
 }
References debugmsg, and items.
Referenced by talk_function::companion_return(), basecamp::finish_return(), and operator+=().
copy_invlet_of()
void inventory::copy_invlet_of (const inventory & other)
Definition at line 1142 of file inventory.cpp.
 {
     assigned_invlet = other.assigned_invlet;
     invlet_cache = other.invlet_cache;
 }
References assigned_invlet, invlet_cache, and other.
count_item()
int inventory::count_item (const itype_id & item_type) const
Definition at line 990 of file inventory.cpp.
 {
     int num = 0;
     const itype_bin bin = get_binned_items();
     if( bin.find( item_type ) == bin.end() ) {
         return num;
     }
     const std::list<const item *> items = get_binned_items().find( item_type )->second;
     for( const item *it : items ) {
         num += it->count();
     }
     return num;
 }
References get_binned_items(), and items.
Referenced by must_use_hallu_poison(), must_use_liq_container(), and recipe_info().
dump() [1/2]
void inventory::dump (std::vector< const item * > & dest) const
Definition at line 705 of file inventory.cpp.
 {
     for( const auto &elem : items ) {
         for( const item &elem_stack_iter : elem ) {
             dest.push_back( &elem_stack_iter );
         }
     }
 }
References items.
dump() [2/2]
void inventory::dump (std::vector< item * > & dest)
Definition at line 696 of file inventory.cpp.
 {
     for( auto &elem : items ) {
         for( item &elem_stack_iter : elem ) {
             dest.push_back( &elem_stack_iter );
         }
     }
 }
References items.
Referenced by mission::is_complete(), and mission::wrap_up().
find_item() [1/2]
item & inventory::find_item (int position)
Definition at line 726 of file inventory.cpp.
 {
     return const_cast<item &>( const_cast<const inventory *>( this )->find_item( position ) );
 }
References find_item().
find_item() [2/2]
const item & inventory::find_item (int position) const
Definition at line 714 of file inventory.cpp.
 {
     if( position < 0 || position >= static_cast<int>( items.size() ) ) {
         return null_item_reference();
     }
     invstack::const_iterator iter = items.begin();
     for( int j = 0; j < position; ++j ) {
         ++iter;
     }
     return iter->front();
 }
References items, and null_item_reference().
Referenced by find_item().
find_usable_cached_invlet()
char inventory::find_usable_cached_invlet (const itype_id & item_type) private
Definition at line 282 of file inventory.cpp.
 {
     Character &player_character = get_player_character();
     // Some of our preferred letters might already be used.
     for( char invlet : invlet_cache.invlets_for( item_type ) ) {
         // Don't overwrite user assignments.
         if( assigned_invlet.count( invlet ) ) {
             continue;
         }
         // Check if anything is using this invlet.
         if( player_character.invlet_to_item( invlet ) != nullptr ) {
             continue;
         }
         return invlet;
     }
     return 0;
 }
References assigned_invlet, get_player_character(), invlet_cache, Character::invlet_to_item(), and invlet_favorites::invlets_for().
Referenced by update_invlet().
form_from_map() [1/3]
void inventory::form_from_map (const tripoint & origin, int range, const Character * pl = nullptr, bool assign_invlet = true, bool clear_path = true)
Definition at line 483 of file inventory.cpp.
 {
     form_from_map( get_map(), origin, range, pl, assign_invlet, clear_path );
 }
References get_map().
Referenced by Character::can_continue_craft(), iuse_transform::can_use(), Character::consume_items(), Character::consume_tools(), Character::craft_consume_tools(), craft_command::create_in_progress_craft(), craft_command::execute(), form_from_map(), form_from_zone(), suffer::from_asthma(), veh_utils::repair_part(), and spell::use_components().
form_from_map() [2/3]
void inventory::form_from_map (map & m, const tripoint & origin, int range, const Character * pl = nullptr, bool assign_invlet = true, bool clear_path = true)
Definition at line 501 of file inventory.cpp.
 {
     // populate a grid of spots that can be reached
     std::vector<tripoint> reachable_pts = {};
     // If we need a clear path we care about the reachability of points
     if( clear_path ) {
         m.reachable_flood_steps( reachable_pts, origin, range, 1, 100 );
     } else {
         // Fill reachable points with points_in_radius
         tripoint_range<tripoint> in_radius = m.points_in_radius( origin, range );
         for( const tripoint &p : in_radius ) {
             reachable_pts.emplace_back( p );
         }
     }
     form_from_map( m, reachable_pts, pl, assign_invlet );
 }
References form_from_map(), map::points_in_radius(), and map::reachable_flood_steps().
form_from_map() [3/3]
void inventory::form_from_map (map & m, std::vector< tripoint > pts, const Character * pl, bool assign_invlet = true)
Definition at line 520 of file inventory.cpp.
 {
     items.clear();
     provisioned_pseudo_tools.clear();
     for( const tripoint &p : pts ) {
         // a temporary hack while trees are terrain
         if( m.ter( p )->has_flag( ter_furn_flag::TFLAG_TREE ) ) {
             provide_pseudo_item( itype_butchery_tree_pseudo );
         }
         // Another terrible hack, as terrain can't provide pseudo items, and construction can't do multi-step furniture
         ter_id brick_oven( "t_brick_oven" );
         if( m.ter( p ) == brick_oven ) {
             provide_pseudo_item( itype_brick_oven_pseudo );
         }
         const furn_t &f = m.furn( p ).obj();
         if( item *furn_item = provide_pseudo_item( f.crafting_pseudo_item ) ) {
             for( const itype *ammo : f.crafting_ammo_item_types() ) {
                 if( furn_item->has_pocket_type( pocket_type::MAGAZINE ) ) {
                     // NOTE: This only works if the pseudo item has a MAGAZINE pocket, not a MAGAZINE_WELL!
                     const bool using_ammotype = f.has_flag( ter_furn_flag::TFLAG_AMMOTYPE_RELOAD );
                     int amount = 0;
                     itype_id ammo_id = ammo->get_id();
                     // Some furniture can consume more than one item type.
                     // This might be redundant now that we iterate over the ammotypes.
                     if( using_ammotype ) {
                         amount = count_charges_in_list( &ammo->ammo->type, m.i_at( p ), ammo_id );
                     } else {
                         amount = count_charges_in_list( ammo, m.i_at( p ) );
                     }
                     if( amount > 0 ) {
                         item furn_ammo( ammo_id, calendar::turn, amount );
                         furn_item->put_in( furn_ammo, pocket_type::MAGAZINE );
                     }
                 }
             }
         }
         if( m.accessible_items( p ) ) {
             for( item &i : m.i_at( p ) ) {
                 // if it's *the* player requesting this from from map inventory
                 // then don't allow items owned by another faction to be factored into recipe components etc.
                 if( pl && !i.is_owned_by( *pl, true ) ) {
                     continue;
                 }
                 if( !i.made_of( phase_id::LIQUID ) ) {
                     if( i.empty_container() && i.is_watertight_container() ) {
                         const int count = i.count_by_charges() ? i.charges : 1;
                         update_liq_container_count( i.typeId(), count );
                     }
                     add_item( i, false, assign_invlet );
                 }
             }
         }
         // Kludges for now!
         if( m.has_nearby_fire( p, 0 ) ) {
             if( item *fire = provide_pseudo_item( itype_fire ) ) {
                 fire->charges = 1;
             }
         }
         // Handle any water from map sources.
         item water = m.water_from( p );
         if( !water.is_null() ) {
             add_item( water );
         }
         // keg-kludge
         if( m.furn( p )->has_examine( iexamine::keg ) ) {
             map_stack liq_contained = m.i_at( p );
             for( item &i : liq_contained ) {
                 if( i.made_of( phase_id::LIQUID ) ) {
                     add_item( i );
                 }
             }
         }
         // form from vehicle
         if( optional_vpart_position vp = m.veh_at( p ) ) {
             vp->form_inventory( *this );
         }
     }
     pts.clear();
 }
References map::accessible_items(), add_item(), itype::ammo, count_charges_in_list(), furn_t::crafting_ammo_item_types(), furn_t::crafting_pseudo_item, fire(), map::furn(), map_data_common_t::has_examine(), map_data_common_t::has_flag(), map::has_nearby_fire(), map::i_at(), items, itype_brick_oven_pseudo, itype_butchery_tree_pseudo, itype_fire, iexamine::keg(), LIQUID, MAGAZINE, int_id< T >::obj(), provide_pseudo_item(), provisioned_pseudo_tools, map::ter(), TFLAG_AMMOTYPE_RELOAD, TFLAG_TREE, calendar::turn, update_liq_container_count(), map::veh_at(), water, and map::water_from().
form_from_zone()
void inventory::form_from_zone (map & m, std::unordered_set< tripoint_abs_ms > & zone_pts, const Character * pl = nullptr, bool assign_invlet = true)
Definition at line 490 of file inventory.cpp.
 {
     std::vector<tripoint> pts;
     pts.reserve( zone_pts.size() );
     for( const tripoint_abs_ms &elem : zone_pts ) {
         pts.push_back( m.getlocal( elem ) );
     }
     form_from_map( m, pts, pl, assign_invlet );
 }
References form_from_map(), and map::getlocal().
Referenced by basecamp::form_crafting_inventory().
get_active_enchantment_cache()
enchant_cache inventory::get_active_enchantment_cache (const Character & owner) const
Definition at line 970 of file inventory.cpp.
 {
     enchant_cache temp_cache;
     for( const std::list<item> &elem : items ) {
         for( const item &check_item : elem ) {
             for( const enchant_cache &ench : check_item.get_proc_enchantments() ) {
                 if( ench.is_active( owner, check_item ) ) {
                     temp_cache.force_add( ench );
                 }
             }
             for( const enchantment &ench : check_item.get_defined_enchantments() ) {
                 if( ench.is_active( owner, check_item ) ) {
                     temp_cache.force_add( ench, owner );
                 }
             }
         }
     }
     return temp_cache;
 }
References enchant_cache::force_add(), and items.
get_binned_items()
const itype_bin & inventory::get_binned_items () const
Returns visitable items binned by their itype.
May not contain items that wouldn't be visited by visitable methods.
Definition at line 1120 of file inventory.cpp.
 {
     if( binned ) {
         return binned_items;
     }
     binned_items.clear();
     // HACK: Hack warning
     inventory *this_nonconst = const_cast<inventory *>( this );
     this_nonconst->visit_items( [ this ]( item * e, item * ) {
         binned_items[ e->typeId() ].push_back( e );
         for( const item *it : e->softwares() ) {
             binned_items[it->typeId()].push_back( it );
         }
         return VisitResponse::NEXT;
     } );
     binned = true;
     return binned_items;
 }
References binned, binned_items, NEXT, item::softwares(), item::typeId(), and visit_items().
Referenced by count_item().
get_book_proficiency_bonuses()
book_proficiency_bonuses inventory::get_book_proficiency_bonuses () const
Definition at line 380 of file inventory.cpp.
 {
     book_proficiency_bonuses ret;
     for( const std::list<item> &it : this->items ) {
         ret += it.front().get_book_proficiency_bonuses();
     }
     return ret;
 }
References items, and cata::hash64_detail::ret.
Referenced by recipe::missing_proficiencies_string(), proficiency_skill_malus(), and proficiency_time_malus().
has_enough_painkiller()
bool inventory::has_enough_painkiller (int pain) const
Definition at line 807 of file inventory.cpp.
 {
     for( const auto &elem : items ) {
         const item &it = elem.front();
         if( ( pain <= 35 && ( it.typeId() == itype_aspirin  || it.typeId() == itype_acetaminophen ||
                               it.typeId() == itype_ibuprofen ) ) ||
             ( pain >= 50 && it.typeId() == itype_oxycodone ) ||
             it.typeId() == itype_tramadol || it.typeId() == itype_codeine ) {
             return true;
         }
     }
     return false;
 }
References items, itype_acetaminophen, itype_aspirin, itype_codeine, itype_ibuprofen, itype_oxycodone, itype_tramadol, pain, and item::typeId().
has_quality()
bool inventory::has_quality (const quality_id & qual, int level = 1, int qty = 1) const override virtual
Returns true if instance has amount (or more) items of at least quality level.
Reimplemented from read_only_visitable.
Referenced by vehicle::build_interact_menu(), iuse_transform::can_use(), veh_interact::cant_do(), iexamine::harvest_plant(), iuse::multicooker(), iexamine::tree_maple(), and iexamine::tree_maple_tapped().
invlet_to_position()
int inventory::invlet_to_position (char invlet) const
Return the item position of the item with given invlet, return INT_MIN if the inventory does not have such an item with that invlet.
Don't use this on npcs inventory.
Definition at line 731 of file inventory.cpp.
 {
     int i = 0;
     for( const auto &elem : items ) {
         if( elem.begin()->invlet == invlet ) {
             return i;
         }
         ++i;
     }
     return INT_MIN;
 }
References items.
json_load_invcache()
void inventory::json_load_invcache (const JsonValue & jsin)
Definition at line 2341 of file savegame_json.cpp.
 {
     try {
         std::unordered_map<itype_id, std::string> map;
         for( JsonObject jo : jsin.get_array() ) {
             jo.allow_omitted_members();
             for( const JsonMember member : jo ) {
                 std::string invlets;
                 for( const int i : member.get_array() ) {
                     invlets.push_back( i );
                 }
                 map[itype_id( member.name() )] = invlets;
             }
         }
         invlet_cache = invlet_favorites{ map };
     } catch( const JsonError &jsonerr ) {
         debugmsg( "bad invcache json:\n%s", jsonerr.c_str() );
     }
 }
References JsonError::c_str(), debugmsg, JsonValue::get_array(), itype_id, map, and member.
json_load_items()
void inventory::json_load_items (const JsonArray & ja)
Definition at line 2375 of file savegame_json.cpp.
 {
     for( JsonObject jo : ja ) {
         item tmp;
         tmp.deserialize( jo );
         add_item( tmp, true, false );
     }
 }
References item::deserialize().
json_save_invcache()
void inventory::json_save_invcache (JsonOut & json) const
Definition at line 2322 of file savegame_json.cpp.
 {
     json.start_array();
     for( const auto &elem : invlet_cache.get_invlets_by_id() ) {
         json.start_object();
         json.member( elem.first.str() );
         json.start_array();
         for( const char &_sym : elem.second ) {
             json.write( static_cast<int>( _sym ) );
         }
         json.end_array();
         json.end_object();
     }
     json.end_array();
 }
References JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), JsonOut::start_array(), JsonOut::start_object(), and JsonOut::write().
json_save_items()
void inventory::json_save_items (JsonOut & json) const
Definition at line 2364 of file savegame_json.cpp.
 {
     json.start_array();
     for( const auto &elem : items ) {
         for( const item &elem_stack_iter : elem ) {
             elem_stack_iter.serialize( json );
         }
     }
     json.end_array();
 }
References JsonOut::end_array(), and JsonOut::start_array().
kcal_range()
std::pair< int, int > inventory::kcal_range (const itype_id & id, const std::function< bool(const item &)> & filter, Character & player_character) const
Definition at line 882 of file visitable.cpp.
 {
     return kcal_range_of_internal( *this, id, filter, player_character );
 }
References filter, and kcal_range_of_internal().
most_appropriate_painkiller()
item * inventory::most_appropriate_painkiller (int pain)
Definition at line 821 of file inventory.cpp.
 {
     int difference = 9999;
     item *ret = &null_item_reference();
     for( auto &elem : items ) {
         int diff = 9999;
         itype_id type = elem.front().typeId();
         if( type == itype_aspirin || type == itype_acetaminophen || type == itype_ibuprofen ) {
             diff = std::abs( pain - 15 );
         } else if( type == itype_codeine ) {
             diff = std::abs( pain - 30 );
         } else if( type == itype_oxycodone ) {
             diff = std::abs( pain - 60 );
         } else if( type == itype_heroin ) {
             diff = std::abs( pain - 100 );
         } else if( type == itype_tramadol ) {
             diff = std::abs( pain - 40 ) / 2; // Bonus since it's long-acting
         }
         if( diff < difference ) {
             difference = diff;
             ret = &elem.front();
         }
     }
     return ret;
 }
References abs(), items, itype_acetaminophen, itype_aspirin, itype_codeine, itype_heroin, itype_ibuprofen, itype_oxycodone, itype_tramadol, null_item_reference(), pain, cata::hash64_detail::ret, and type.
must_use_hallu_poison()
bool inventory::must_use_hallu_poison (const itype_id & id, int to_use) const
Definition at line 1164 of file inventory.cpp.
 {
     const int total = count_item( id );
     int bad = 0;
     for( const std::list<item> &item_list : items ) {
         for( const item &it : item_list ) {
             if( it.typeId() == id && ( it.has_flag( flag_HIDDEN_POISON ) ||
                                        it.has_flag( flag_HIDDEN_HALLU ) ) ) {
                 if( it.count_by_charges() ) {
                     bad += it.charges;
                 } else {
                     bad += it.count();
                 }
             }
         }
     }
     return total - bad < to_use;
 }
References character_health_category::bad, count_item(), flag_HIDDEN_HALLU, flag_HIDDEN_POISON, and items.
Referenced by item_comp::get_color().
must_use_liq_container()
bool inventory::must_use_liq_container (const itype_id & id, int to_use) const
Definition at line 1153 of file inventory.cpp.
 {
     const int total = count_item( id );
     auto iter = max_empty_liq_cont.find( id );
     if( iter == max_empty_liq_cont.end() ) {
         return total > 0;
     }
     const int leftover = iter->second - to_use;
     return leftover < 0 && leftover * -1 <= total - iter->second;
 }
References count_item(), and max_empty_liq_cont.
Referenced by item_comp::get_color().
operator+() [1/4]
inventory inventory::operator+ (const inventory & rhs)
Definition at line 221 of file inventory.cpp.
 {
     return inventory( *this ) += rhs;
 }
References inventory().
operator+() [2/4]
inventory inventory::operator+ (const item & rhs)
Definition at line 236 of file inventory.cpp.
 {
     return inventory( *this ) += rhs;
 }
References inventory().
operator+() [3/4]
inventory inventory::operator+ (const item_components & rhs)
Definition at line 231 of file inventory.cpp.
 {
     return inventory( *this ) += rhs;
 }
References inventory().
operator+() [4/4]
inventory inventory::operator+ (const std::list< item > & rhs)
Definition at line 226 of file inventory.cpp.
 {
     return inventory( *this ) += rhs;
 }
References inventory().
operator+=() [1/6]
inventory & inventory::operator+= (const inventory & rhs)
Definition at line 171 of file inventory.cpp.
 {
     for( size_t i = 0; i < rhs.size(); i++ ) {
         push_back( rhs.const_stack( i ) );
     }
     return *this;
 }
References const_stack(), push_back(), and size().
operator+=() [2/6]
inventory & inventory::operator+= (const item & rhs)
Definition at line 205 of file inventory.cpp.
 {
     add_item( rhs );
     return *this;
 }
References add_item().
operator+=() [3/6]
inventory & inventory::operator+= (const item_components & rhs)
Definition at line 187 of file inventory.cpp.
 {
     for( const item_components::type_vector_pair &tvp : rhs ) {
         for( const item &rh : tvp.second ) {
             add_item( rh, false, false );
         }
     }
     return *this;
 }
References add_item().
operator+=() [4/6]
inventory & inventory::operator+= (const item_stack & rhs)
Definition at line 211 of file inventory.cpp.
 {
     for( const item &p : rhs ) {
         if( !p.made_of( phase_id::LIQUID ) ) {
             add_item( p, true );
         }
     }
     return *this;
 }
References add_item(), and LIQUID.
operator+=() [5/6]
inventory & inventory::operator+= (const std::list< item > & rhs)
Definition at line 179 of file inventory.cpp.
 {
     for( const item &rh : rhs ) {
         add_item( rh, false, false );
     }
     return *this;
 }
References add_item().
operator+=() [6/6]
inventory & inventory::operator+= (const std::vector< item > & rhs)
Definition at line 197 of file inventory.cpp.
 {
     for( const item &rh : rhs ) {
         add_item( rh, true );
     }
     return *this;
 }
References add_item().
operator=() [1/2]
inventory& inventory::operator= (const inventory &) default
operator=() [2/2]
inventory& inventory::operator= (inventory &&) default
position_by_item()
int inventory::position_by_item (const item * it) const
Returns the item position of the stack that contains the given item (compared by pointers).
Returns INT_MIN if the item is not found. Note that this may lose some information, for example the returned position is the same when the given item points to the container and when it points to the item inside the container. All items that are part of the same stack have the same item position.
Definition at line 743 of file inventory.cpp.
 {
     int p = 0;
     for( const auto &stack : items ) {
         for( const item &e : stack ) {
             if( e.has_item( *it ) ) {
                 return p;
             }
         }
         p++;
     }
     return INT_MIN;
 }
References items.
Referenced by restack().
position_by_type()
int inventory::position_by_type (const itype_id & type) const
Definition at line 757 of file inventory.cpp.
 {
     int i = 0;
     for( const auto &elem : items ) {
         if( elem.front().typeId() == type ) {
             return i;
         }
         ++i;
     }
     return INT_MIN;
 }
References items, and type.
provide_pseudo_item() [1/2]
item * inventory::provide_pseudo_item (const item & tool)
Definition at line 356 of file inventory.cpp.
 {
     if( !provisioned_pseudo_tools.insert( tool.typeId() ).second ) {
         // already provided tool -> return existing
         for( auto &stack : items ) {
             if( stack.front().typeId() == tool.typeId() ) {
                 return &stack.front();
             }
         }
         return nullptr;
     }
     item *res = &add_item( tool );
     res->set_flag( flag_PSEUDO );
     return res;
 }
References add_item(), flag_PSEUDO, items, provisioned_pseudo_tools, item::set_flag(), and itype::tool.
Referenced by form_from_map(), vpart_position::form_inventory(), and provide_pseudo_item().
provide_pseudo_item() [2/2]
item * inventory::provide_pseudo_item (const itype_id & tool_type)
Definition at line 372 of file inventory.cpp.
 {
     if( !tool_type.is_valid() ) {
         return nullptr;
     }
     return provide_pseudo_item( item( tool_type, calendar::turn ) );
 }
References string_id< T >::is_valid(), item, provide_pseudo_item(), and calendar::turn.
push_back() [1/2]
void inventory::push_back (const item & newit)
Definition at line 347 of file inventory.cpp.
 {
     add_item( newit );
 }
References add_item().
push_back() [2/2]
void inventory::push_back (const std::list< item > & newits)
Definition at line 259 of file inventory.cpp.
 {
     for( const item &newit : newits ) {
         add_item( newit, true );
     }
 }
References add_item().
Referenced by iuse::multicooker(), om_harvest_ter(), and operator+=().
reassign_item()
void inventory::reassign_item (item & it, char invlet, bool remove_old = true)
Definition at line 1055 of file inventory.cpp.
 {
     if( it.invlet == invlet ) { // no change needed
         return;
     }
     if( remove_old && it.invlet ) {
         invlet_cache.erase( it.invlet );
     }
     it.invlet = invlet;
     update_cache_with_item( it );
 }
References invlet_favorites::erase(), item::invlet, invlet_cache, and update_cache_with_item().
reduce_stack()
std::list< item > inventory::reduce_stack (int position, int quantity)
Definition at line 604 of file inventory.cpp.
 {
     int pos = 0;
     std::list<item> ret;
     for( invstack::iterator iter = items.begin(); iter != items.end(); ++iter ) {
         if( position == pos ) {
             binned = false;
             if( quantity >= static_cast<int>( iter->size() ) || quantity < 0 ) {
                 ret = *iter;
                 items.erase( iter );
             } else {
                 for( int i = 0 ; i < quantity ; i++ ) {
                     ret.push_back( remove_item( &iter->front() ) );
                 }
             }
             break;
         }
         ++pos;
     }
     return ret;
 }
References binned, items, math_opers::pos(), remove_item(), and cata::hash64_detail::ret.
remove_item() [1/2]
item inventory::remove_item (const item * it)
Remove a specific item from the inventory.
The item is compared by pointer. Contents of the item are removed as well.
Parameters
it A pointer to the item to be removed. The item must exists in this inventory.
Returns
A copy of the removed item.
Definition at line 626 of file inventory.cpp.
 {
     auto tmp = remove_items_with( [&it]( const item & i ) {
         return &i == it;
     }, 1 );
     if( !tmp.empty() ) {
         binned = false;
         return tmp.front();
     }
     debugmsg( "Tried to remove a item not in inventory." );
     return item();
 }
References binned, debugmsg, item, and remove_items_with().
Referenced by farm_action(), and reduce_stack().
remove_item() [2/2]
item inventory::remove_item (int position)
Definition at line 639 of file inventory.cpp.
 {
     int pos = 0;
     for( invstack::iterator iter = items.begin(); iter != items.end(); ++iter ) {
         if( position == pos ) {
             binned = false;
             if( iter->size() > 1 ) {
                 std::list<item>::iterator stack_member = iter->begin();
                 char invlet = stack_member->invlet;
                 ++stack_member;
                 stack_member->invlet = invlet;
             }
             item ret = iter->front();
             iter->erase( iter->begin() );
             if( iter->empty() ) {
                 items.erase( iter );
             }
             return ret;
         }
         ++pos;
     }
     return item();
 }
References binned, item, items, math_opers::pos(), and cata::hash64_detail::ret.
remove_items_with()
std::list<item> inventory::remove_items_with (const std::function< bool(const item &)> & filter, int count = INT_MAX) override virtual
Removes items contained by this instance which match the filter.
Note
: Implement for each class that will implement the visitable interface
if this instance itself is an item it will not be considered by the filter
Parameters
filter a UnaryPredicate which should return true if the item is to be removed
count maximum number of items to if unspecified unlimited. A count of zero is a no-op
Returns
any items removed (items counted by charges are not guaranteed to be stacked)
Implements visitable.
Referenced by mill_load_food(), and remove_item().
remove_randomly_by_volume()
std::list< item > inventory::remove_randomly_by_volume (const units::volume & volume)
Randomly select items until the volume quota is filled.
Definition at line 664 of file inventory.cpp.
 {
     std::list<item> result;
     units::volume volume_dropped = 0_ml;
     while( volume_dropped < volume ) {
         units::volume cumulative_volume = 0_ml;
         auto chosen_stack = items.begin();
         auto chosen_item = chosen_stack->begin();
         for( auto stack = items.begin(); stack != items.end(); ++stack ) {
             for( auto stack_it = stack->begin(); stack_it != stack->end(); ++stack_it ) {
                 cumulative_volume += stack_it->volume();
                 if( x_in_y( stack_it->volume().value(), cumulative_volume.value() ) ) {
                     chosen_item = stack_it;
                     chosen_stack = stack;
                 }
             }
         }
         volume_dropped += chosen_item->volume();
         result.push_back( std::move( *chosen_item ) );
         chosen_item = chosen_stack->erase( chosen_item );
         if( chosen_item == chosen_stack->begin() && !chosen_stack->empty() ) {
             // preserve the invlet when removing the first item of a stack
             chosen_item->invlet = result.back().invlet;
         }
         if( chosen_stack->empty() ) {
             binned = false;
             items.erase( chosen_stack );
         }
     }
     return result;
 }
References binned, items, units::quantity< V, U >::value(), volume(), and x_in_y().
replace_liq_container_count()
void inventory::replace_liq_container_count (const std::map< itype_id, int > & newmap, bool use_max = false)
Definition at line 1183 of file inventory.cpp.
 {
     for( const auto &it : newmap ) {
         if( !use_max || max_empty_liq_cont.find( it.first ) == max_empty_liq_cont.end() ||
             max_empty_liq_cont.at( it.first ) < it.second ) {
             max_empty_liq_cont[it.first] = it.second;
         }
     }
 }
References max_empty_liq_cont.
restack()
void inventory::restack (Character & p)
Definition at line 389 of file inventory.cpp.
 {
     // tasks that the old restack seemed to do:
     // 1. reassign inventory letters
     // 2. remove items from non-matching stacks
     // 3. combine matching stacks
     binned = false;
     std::list<item> to_restack;
     int idx = 0;
     for( invstack::iterator iter = items.begin(); iter != items.end(); ++iter, ++idx ) {
         std::list<item> &stack = *iter;
         item &topmost = stack.front();
         const item *invlet_item = p.invlet_to_item( topmost.invlet );
         if( !inv_chars.valid( topmost.invlet ) || ( invlet_item != nullptr &&
                 position_by_item( invlet_item ) != idx ) ) {
             assign_empty_invlet( topmost, p );
             for( item &stack_iter : stack ) {
                 stack_iter.invlet = topmost.invlet;
             }
         }
         // remove non-matching items, stripping off end of stack so the first item keeps the invlet.
         while( stack.size() > 1 && !topmost.stacks_with( stack.back() ) ) {
             to_restack.splice( to_restack.begin(), *iter, --stack.end() );
         }
     }
     // combine matching stacks
     // separate loop to ensure that ALL stacks are homogeneous
     for( invstack::iterator iter = items.begin(); iter != items.end(); ++iter ) {
         for( invstack::iterator other = iter; other != items.end(); ++other ) {
             if( iter != other && iter->front().stacks_with( other->front() ) ) {
                 if( other->front().count_by_charges() ) {
                     iter->front().charges += other->front().charges;
                 } else {
                     iter->splice( iter->begin(), *other );
                 }
                 other = items.erase( other );
                 --other;
             }
         }
     }
     //re-add non-matching items
     for( item &elem : to_restack ) {
         add_item( elem );
     }
     //Ensure that all items in the same stack have the same invlet.
     for( std::list< item > &outer : items ) {
         for( item &inner : outer ) {
             inner.invlet = outer.front().invlet;
         }
     }
     items.sort( stack_compare );
 #if defined(__ANDROID__)
     remove_stale_inventory_quick_shortcuts();
 #endif
 }
References add_item(), assign_empty_invlet(), binned, inv_chars(), item::invlet, Character::invlet_to_item(), items, other, position_by_item(), stack_compare(), item::stacks_with(), and invlet_wrapper::valid().
rust_iron_items()
void inventory::rust_iron_items ()
Definition at line 848 of file inventory.cpp.
 {
     Character &player_character = get_player_character();
     map &here = get_map();
     for( auto &elem : items ) {
         for( item &elem_stack_iter : elem ) {
             if( elem_stack_iter.made_of( material_iron ) &&
                 !elem_stack_iter.has_flag( flag_WATERPROOF_GUN ) &&
                 !elem_stack_iter.has_flag( flag_WATERPROOF ) &&
                 elem_stack_iter.damage() < elem_stack_iter.max_damage() / 2 &&
                 //Passivation layer prevents further rusting
                 one_in( 500 ) &&
                 //Scale with volume, bigger = slower (see #24204)
                 one_in(
                     static_cast<int>(
                         14 * std::cbrt(
                             0.5 * std::max(
                                 0.05, static_cast<double>(
                                     elem_stack_iter.base_volume().value() ) / 250 ) ) ) ) &&
                 //                       ^season length   ^14/5*0.75/pi (from volume of sphere)
                 //Freshwater without oxygen rusts slower than air
                 here.water_from( player_character.pos() ).typeId() == itype_salt_water ) {
                 // rusting never completely destroys an item, so no need to handle return value
                 elem_stack_iter.inc_damage();
                 add_msg( m_bad, _( "Your %s is damaged by rust." ), elem_stack_iter.tname() );
             }
         }
     }
 }
References _, add_msg(), flag_WATERPROOF, flag_WATERPROOF_GUN, get_map(), get_player_character(), items, itype_salt_water, m_bad, material_iron, max(), one_in(), Creature::pos(), item::typeId(), and map::water_from().
size()
size_t inventory::size () const
Definition at line 166 of file inventory.cpp.
 {
     return items.size();
 }
References items.
Referenced by talk_function::companion_return(), basecamp::finish_return(), and operator+=().
slice()
invslice inventory::slice ()
Definition at line 133 of file inventory.cpp.
 {
     invslice stacks;
     for( auto &elem : items ) {
         stacks.push_back( &elem );
     }
     return stacks;
 }
References items.
unsort()
void inventory::unsort ()
Definition at line 241 of file inventory.cpp.
 {
     binned = false;
 }
References binned.
update_cache_with_item()
void inventory::update_cache_with_item (item & newit)
Definition at line 267 of file inventory.cpp.
 {
     // This function does two things:
     // 1. It adds newit's invlet to the list of favorite letters for newit's item type.
     // 2. It removes newit's invlet from the list of favorite letters for all other item types.
     // no invlet item, just return.
     // TODO: Should we instead remember that the invlet was cleared?
     if( newit.invlet == 0 ) {
         return;
     }
     invlet_cache.set( newit.invlet, newit.typeId() );
 }
References item::invlet, invlet_cache, invlet_favorites::set(), and item::typeId().
Referenced by add_item(), and reassign_item().
update_invlet()
void inventory::update_invlet (item & it, bool assign_invlet = true, const item * ignore_invlet_collision_with = nullptr)
Definition at line 1067 of file inventory.cpp.
 {
     if( newit.invlet ) {
         // Avoid letters that have been manually assigned to other things.
         if( assigned_invlet.find( newit.invlet ) != assigned_invlet.end() ) {
             if( assigned_invlet[newit.invlet] != newit.typeId() ) {
                 newit.invlet = '\0';
             }
             // Remove letters that are not in the favorites cache
         } else if( !invlet_cache.contains( newit.invlet, newit.typeId() ) ) {
             newit.invlet = '\0';
         }
     }
     Character &player_character = get_player_character();
     // Remove letters that have been assigned to other items in the inventory
     if( newit.invlet ) {
         char tmp_invlet = newit.invlet;
         newit.invlet = '\0';
         item *collidingItem = player_character.invlet_to_item( tmp_invlet );
         if( collidingItem == nullptr || collidingItem == ignore_invlet_collision_with ) {
             newit.invlet = tmp_invlet;
         }
     }
     if( assign_invlet ) {
         // Assign a cached letter to the item
         if( !newit.invlet ) {
             newit.invlet = find_usable_cached_invlet( newit.typeId() );
         }
         // Give the item an invlet if it has none
         if( !newit.invlet ) {
             assign_empty_invlet( newit, player_character );
         }
     }
 }
References assign_empty_invlet(), assigned_invlet, invlet_favorites::contains(), find_usable_cached_invlet(), get_player_character(), item::invlet, invlet_cache, Character::invlet_to_item(), and item::typeId().
Referenced by add_item().
update_liq_container_count()
void inventory::update_liq_container_count (const itype_id & id, int count)
Definition at line 1148 of file inventory.cpp.
 {
     max_empty_liq_cont[id] += count;
 }
References base_camps::id, and max_empty_liq_cont.
Referenced by form_from_map(), and vpart_position::form_inventory().
use_amount()
std::list< item > inventory::use_amount (const itype_id & it, int quantity, const std::function< bool(const item &)> & filter = return_true<item>)
Definition at line 769 of file inventory.cpp.
 {
     items.sort( stack_compare );
     std::list<item> ret;
     for( invstack::iterator iter = items.begin(); iter != items.end() && quantity > 0; /* noop */ ) {
         for( std::list<item>::iterator stack_iter = iter->begin();
              stack_iter != iter->end() && quantity > 0;
              /* noop */ ) {
             if( stack_iter->use_amount( it, quantity, ret, filter ) ) {
                 stack_iter = iter->erase( stack_iter );
             } else {
                 ++stack_iter;
             }
         }
         if( iter->empty() ) {
             binned = false;
             iter = items.erase( iter );
         } else if( iter != items.end() ) {
             ++iter;
         }
     }
     return ret;
 }
References binned, filter, items, cata::hash64_detail::ret, and stack_compare().
visit_items()
VisitResponse inventory::visit_items (const std::function< VisitResponse(item *, item *)> & func) const override virtual
Traverses this object and any child items contained using a visitor pattern.
Note
Implement for each class that will implement the visitable interface. Other visit_items variants rely on this function.
Parameters
func visitor function called for each node which controls whether traversal continues. The first argument is the node and the second is the parent node (if any) The visitor function should return VisitResponse::Next to recursively process child items, VisitResponse::Skip to ignore children of the current node or VisitResponse::Abort to skip all remaining nodes
Returns
This method itself only ever returns VisitResponse::Next or VisitResponse::Abort.
Implements read_only_visitable.
Referenced by get_binned_items().
volume()
units::volume inventory::volume () const
Definition at line 941 of file inventory.cpp.
 {
     units::volume ret = 0_ml;
     for( const auto &elem : items ) {
         for( const item &elem_stack_iter : elem ) {
             ret += elem_stack_iter.volume();
         }
     }
     return ret;
 }
References items, and cata::hash64_detail::ret.
Referenced by remove_randomly_by_volume(), and volume_without().
volume_without()
units::volume inventory::volume_without (const std::map< const item *, int > & without) const
Definition at line 952 of file inventory.cpp.
 {
     units::volume ret = volume();
     for_each_item_in_both( items, without,
     [&]( const item & i ) {
         ret -= i.volume();
     }
                          );
     if( ret < 0_ml ) {
         debugmsg( "Negative volume after removing some of inventory" );
         ret = 0_ml;
     }
     return ret;
 }
References debugmsg, for_each_item_in_both(), items, cata::hash64_detail::ret, volume(), and item::volume().
weight()
units::mass inventory::weight () const
Definition at line 878 of file inventory.cpp.
 {
     units::mass ret = 0_gram;
     for( const auto &elem : items ) {
         for( const item &elem_stack_iter : elem ) {
             ret += elem_stack_iter.weight();
         }
     }
     return ret;
 }
References items, and cata::hash64_detail::ret.
Referenced by weight_without().
weight_without()
units::mass inventory::weight_without (const std::map< const item *, int > & without) const
Definition at line 923 of file inventory.cpp.
 {
     units::mass ret = weight();
     for_each_item_in_both( items, without,
     [&]( const item & i ) {
         ret -= i.weight();
     }
                          );
     if( ret < 0_gram ) {
         debugmsg( "Negative mass after removing some of inventory" );
         ret = {};
     }
     return ret;
 }
References debugmsg, for_each_item_in_both(), items, cata::hash64_detail::ret, weight(), and item::weight().
worst_item_value()
int inventory::worst_item_value (npc * p) const
Definition at line 794 of file inventory.cpp.
 {
     int worst = 99999;
     for( const auto &elem : items ) {
         const item &it = elem.front();
         int val = p->value( it );
         if( val < worst ) {
             worst = val;
         }
     }
     return worst;
 }
References items, and npc::value().
Member Data Documentation
assigned_invlet
std::map<char, itype_id> inventory::assigned_invlet
Definition at line 116 of file inventory.h.
Referenced by assign_empty_invlet(), copy_invlet_of(), find_usable_cached_invlet(), and update_invlet().
binned
bool inventory::binned = false mutable private
Definition at line 287 of file inventory.h.
Referenced by add_item(), clear(), get_binned_items(), reduce_stack(), remove_item(), remove_randomly_by_volume(), restack(), unsort(), and use_amount().
binned_items
itype_bin inventory::binned_items mutable private
Items binned by their type.
That is, item_bin["carrot"] is a list of pointers to all carrots in inventory. mutable because this is a pure cache that doesn't affect the contained items.
Definition at line 293 of file inventory.h.
Referenced by get_binned_items().
invlet_cache
invlet_favorites inventory::invlet_cache private
Definition at line 277 of file inventory.h.
Referenced by copy_invlet_of(), find_usable_cached_invlet(), reassign_item(), update_cache_with_item(), and update_invlet().
items
invstack inventory::items private
Definition at line 280 of file inventory.h.
Referenced by add_item(), allocated_invlets(), assign_empty_invlet(), clear(), const_slice(), const_stack(), count_item(), dump(), find_item(), form_from_map(), get_active_enchantment_cache(), get_book_proficiency_bonuses(), has_enough_painkiller(), visitable::has_quality(), invlet_to_position(), most_appropriate_painkiller(), must_use_hallu_poison(), position_by_item(), position_by_type(), provide_pseudo_item(), reduce_stack(), remove_item(), remove_randomly_by_volume(), restack(), rust_iron_items(), size(), slice(), use_amount(), volume(), volume_without(), weight(), weight_without(), and worst_item_value().
max_empty_liq_cont
std::map<itype_id, int> inventory::max_empty_liq_cont private
Definition at line 282 of file inventory.h.
Referenced by clear(), must_use_liq_container(), replace_liq_container_count(), and update_liq_container_count().
provisioned_pseudo_tools
std::set<itype_id> inventory::provisioned_pseudo_tools private
Definition at line 285 of file inventory.h.
Referenced by form_from_map(), and provide_pseudo_item().
qualities_cache
std::map<quality_query, bool> inventory::qualities_cache mutable private
Definition at line 295 of file inventory.h.
Referenced by clear(), and visitable::has_quality().
The documentation for this class was generated from the following files:
src/inventory.h
src/inventory.cpp
src/savegame_json.cpp
src/visitable.cpp