Cataclysm DDA: milk_activity_actor Class Reference
milk_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
milk_activity_actor ()=default
milk_activity_actor (int moves, std::vector< tripoint > coords, std::vector< std::string > str_values)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &, Character &) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int total_moves {}
std::vector< tripoint > monster_coords {}
std::vector< std::string > string_values {}
Detailed Description
Definition at line 1188 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
milk_activity_actor() [1/2]
milk_activity_actor::milk_activity_actor () default
milk_activity_actor() [2/2]
milk_activity_actor::milk_activity_actor (int moves, std::vector< tripoint > coords, std::vector< std::string > str_values) inline
Definition at line 1192 of file activity_actor_definitions.h.
                                                                : total_moves( moves ), monster_coords( std::move( coords ) ),
             string_values( std::move( str_values ) ) {}
Member Function Documentation
canceled()
void milk_activity_actor::canceled (player_activity & , Character &) inline override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 1203 of file activity_actor_definitions.h.
 {}
clone()
std::unique_ptr<activity_actor> milk_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1205 of file activity_actor_definitions.h.
{
             return std::make_unique<milk_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > milk_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 4980 of file activity_actor.cpp.
 {
     milk_activity_actor actor;
     JsonObject data = jsin.get_object();
     data.read( "moves_total", actor.total_moves );
     data.read( "monster_coords", actor.monster_coords );
     data.read( "string_values", actor.string_values );
     return actor.clone();
 }
References clone(), JsonValue::get_object(), monster_coords, JsonObject::read(), string_values, and total_moves.
do_turn()
void milk_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 4912 of file activity_actor.cpp.
 {
     if( monster_coords.empty() ) {
         debugmsg( "milking activity with no position of monster stored" );
         act.set_to_null();
         return;
     }
     map &here = get_map();
     const tripoint source_pos = here.getlocal( monster_coords.at( 0 ) );
     monster *source_mon = get_creature_tracker().creature_at<monster>( source_pos );
     if( source_mon == nullptr ) {
         // We might end up here if the creature dies while being milked
         who.add_msg_if_player( m_bad, _( "The udders slip out of your hands." ) );
         act.set_to_null();
     }
 }
References _, act, Character::add_msg_if_player(), creature_tracker::creature_at(), debugmsg, get_creature_tracker(), get_map(), map::getlocal(), m_bad, and monster_coords.
finish()
void milk_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 4929 of file activity_actor.cpp.
 {
     act.set_to_null();
     if( monster_coords.empty() ) {
         debugmsg( "milking activity with no position of monster stored" );
         return;
     }
     map &here = get_map();
     const tripoint source_pos = here.getlocal( monster_coords.at( 0 ) );
     monster *source_mon = get_creature_tracker().creature_at<monster>( source_pos );
     if( source_mon == nullptr ) {
         debugmsg( "could not find source creature for liquid transfer" );
         return;
     }
     auto milked_item = source_mon->ammo.find( source_mon->type->starting_ammo.begin()->first );
     if( milked_item == source_mon->ammo.end() ) {
         debugmsg( "animal has no milkable ammo type" );
         return;
     }
     if( milked_item->second <= 0 ) {
         debugmsg( "started milking but udders are now empty before milking finishes" );
         return;
     }
     item milk( milked_item->first, calendar::turn, milked_item->second );
     milk.set_item_temperature( units::from_celsius( 38.6 ) );
     if( liquid_handler::handle_liquid( milk, nullptr, 1, nullptr, nullptr, -1, source_mon ) ) {
         milked_item->second = 0;
         if( milk.charges > 0 ) {
             milked_item->second = milk.charges;
         } else {
             who.add_msg_if_player( _( "The %s's udders run dry." ), source_mon->get_name() );
         }
     }
     // if the monster was not manually tied up, but needed to be fixed in place temporarily then
     // remove that now.
     if( !string_values.empty() && string_values[0] == "temp_tie" ) {
         source_mon->remove_effect( effect_tied );
     }
 }
References _, act, Character::add_msg_if_player(), monster::ammo, item::charges, creature_tracker::creature_at(), debugmsg, effect_tied, units::from_celsius(), get_creature_tracker(), get_map(), monster::get_name(), map::getlocal(), liquid_handler::handle_liquid(), monster_coords, Creature::remove_effect(), item::set_item_temperature(), mtype::starting_ammo, string_values, calendar::turn, and monster::type.
get_type()
activity_id milk_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1196 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_MILK" );
         }
References activity_id.
serialize()
void milk_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 4969 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "total_moves", total_moves );
     jsout.member( "monster_coords", monster_coords );
     jsout.member( "string_values", string_values );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), monster_coords, JsonOut::start_object(), string_values, and total_moves.
start()
void milk_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 4906 of file activity_actor.cpp.
 {
     act.moves_total = total_moves;
     act.moves_left = total_moves;
 }
References act, and total_moves.
Member Data Documentation
monster_coords
std::vector<tripoint> milk_activity_actor::monster_coords {} private
Definition at line 1214 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), finish(), and serialize().
string_values
std::vector<std::string> milk_activity_actor::string_values {} private
Definition at line 1215 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
total_moves
int milk_activity_actor::total_moves {} private
Definition at line 1213 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp