Cataclysm DDA: math_exp::math_exp_impl Class Reference
math_exp::math_exp_impl Class Reference
Classes
struct arity_t
Public Member Functions
math_exp_impl ()=default
math_exp_impl (thingie &&t)
bool parse (std::string_view str, bool assignment)
double eval (dialogue &d) const
void assign (dialogue &d, double val) const
Private Member Functions
void _parse (std::string_view str, bool assignment)
void parse_string (std::string_view token, std::string_view full)
void parse_bin_op (pbin_op const &op)
template<typename T >
void parse_diag_f (std::string_view symbol, T const &token)
void parse_comma ()
void parse_lparen (arity_t::type_t type=arity_t::type_t::parens)
void parse_rparen ()
void parse_lbracket ()
void parse_rbracket ()
void new_func ()
void new_oper ()
void new_var (std::string_view str)
void new_kwarg (thingie &lhs, thingie &rhs)
void new_ternary (thingie &lhs, thingie &rhs)
void new_array ()
void maybe_first_argument ()
void error (std::string_view str, std::string_view what)
void validate_string (std::string_view str, std::string_view label, std::string_view badlist)
Static Private Member Functions
static std::vector< diag_value > _get_diag_vals (std::vector< thingie > &params)
static diag_value _get_diag_value (thingie &param)
Private Attributes
std::stack< op_t > ops
std::stack< thingie > output
std::stack< arity_t > arity
thingie tree { 0.0 }
std::string_view last_token
parse_state state
Detailed Description
Definition at line 269 of file math_parser.cpp.
Constructor & Destructor Documentation
math_exp_impl() [1/2]
math_exp::math_exp_impl::math_exp_impl () default
math_exp_impl() [2/2]
math_exp::math_exp_impl::math_exp_impl (thingie && t) inline explicit
Definition at line 273 of file math_parser.cpp.
 : tree( t ) {}
Member Function Documentation
_get_diag_vals()
std::vector< diag_value > math_exp::math_exp_impl::_get_diag_vals (std::vector< thingie > & params) static private
Definition at line 675 of file math_parser.cpp.
 {
     std::vector<diag_value> vals( params.size() );
     for( decltype( vals )::size_type i = 0; i < params.size(); i++ ) {
         vals[i] = _get_diag_value( params[i] );
     }
     return vals;
 }
_get_diag_value()
diag_value math_exp::math_exp_impl::_get_diag_value (thingie & param) static private
Definition at line 641 of file math_parser.cpp.
 {
     diag_value val;
     std::visit( overloaded{
         [&val]( double v )
         {
             val.data.emplace<double>( v );
         },
         [&val]( std::string & v )
         {
             val.data.emplace<std::string>( std::move( v ) );
         },
         [&val]( var & v )
         {
             val.data.emplace<var_info>( std::move( v.varinfo ) );
         },
         [&val]( array & v )
         {
             diag_array arr;
             arr.reserve( v.params.size() );
             for( thingie &t : v.params ) {
                 arr.emplace_back( _get_diag_value( t ) );
             }
             val.data.emplace<diag_array>( std::move( arr ) );
         },
         [&val, &param]( auto const &/* v */ )
         {
             val.data.emplace<math_exp>( math_exp_impl{ std::move( param ) } );
         },
     },
     param.data );
     return val;
 }
References diag_value::data, and thingie::data.
_parse()
void math_exp::math_exp_impl::_parse (std::string_view str, bool assignment) private
Definition at line 373 of file math_parser.cpp.
 {
     constexpr std::string_view expression_separators = "+-*/^,()[]%':><=!?";
     state = {};
     for( std::string_view const token : tokenize( str, expression_separators ) ) {
         last_token = token;
         if( state.instring || token == "'" ) {
             parse_string( token, str );
         } else if( std::optional<double> val = get_number( token ); val ) {
             state.validate( parse_state::expect::operand );
             maybe_first_argument();
             output.emplace( *val );
             state.set( parse_state::expect::oper );
         } else if( std::optional<pmath_func> ftoken = get_function( token ); ftoken ) {
             state.validate( parse_state::expect::operand );
             maybe_first_argument();
             ops.emplace( *ftoken );
             arity.emplace( ( *ftoken )->symbol, ( *ftoken )->num_params, arity_t::type_t::func );
             state.set( parse_state::expect::lparen );
         } else if( jmath_func_id jmfid( token ); jmfid.is_valid() ) {
             state.validate( parse_state::expect::operand );
             maybe_first_argument();
             ops.emplace( jmfid );
             arity.emplace( token, jmfid->num_params, arity_t::type_t::func );
             state.set( parse_state::expect::lparen );
         } else if( std::optional<scoped_diag_eval> feval = get_dialogue_eval( token ); feval &&
                    !assignment ) {
             parse_diag_f( token, *feval );
         } else if( std::optional<scoped_diag_ass> fass = get_dialogue_ass( token ); fass &&
                    assignment ) {
             parse_diag_f( token, *fass );
         } else if( std::optional<punary_op> op = get_unary_op( token ); op && state.allows_prefix_unary ) {
             state.validate( parse_state::expect::operand );
             ops.emplace( *op );
             state.set( parse_state::expect::operand );
         } else if( std::optional<pbin_op> op = get_binary_op( token ); op ) {
             parse_bin_op( *op );
         } else if( token == "," ) {
             parse_comma();
         } else if( token == "(" ) {
             parse_lparen();
         } else if( token == ")" ) {
             parse_rparen();
         } else if( token == "[" ) {
             parse_lbracket();
         } else if( token == "]" ) {
             parse_rbracket();
         } else if( token == "=" ) {
             throw std::invalid_argument( R"(Misplaced "=".  Did you mean "=="?)" );
         } else {
             state.validate( parse_state::expect::operand );
             maybe_first_argument();
             new_var( token );
             state.set( parse_state::expect::oper );
         }
     }
     state.validate( parse_state::expect::eof );
     while( !ops.empty() ) {
         if( std::holds_alternative<paren>( ops.top() ) && std::get<paren>( ops.top() ) == paren::left ) {
             throw std::invalid_argument( "Unterminated left paranthesis" );
         }
         if( std::holds_alternative<paren>( ops.top() ) && std::get<paren>( ops.top() ) == paren::left_sq ) {
             throw std::invalid_argument( "Unterminated left bracket" );
         }
         new_oper();
     }
     if( assignment && !is_assign_target( output.top() ) ) {
         throw std::invalid_argument( "Assignment tree can only contain one variable name or dialogue assignment function" );
     }
     if( output.size() != 1 ) {
         throw std::invalid_argument( "Invalid expression.  That's all we know.  Blame andrei." );
     }
     tree = std::move( output.top() );
     output.pop();
 }
References anonymous_namespace{math_parser.cpp}::get_binary_op(), anonymous_namespace{math_parser.cpp}::get_dialogue_ass(), anonymous_namespace{math_parser.cpp}::get_dialogue_eval(), anonymous_namespace{math_parser.cpp}::get_function(), anonymous_namespace{math_parser.cpp}::get_number(), anonymous_namespace{math_parser.cpp}::get_unary_op(), anonymous_namespace{math_parser.cpp}::is_assign_target(), string_id< T >::is_valid(), left, left_sq, and tokenize().
Referenced by parse().
assign()
void math_exp::math_exp_impl::assign (dialogue & d, double val) const inline
Definition at line 299 of file math_parser.cpp.
{
             std::visit( overloaded{
                 [&d, val]( func_diag_ass const & v ) {
                     v.assign( d, val );
                 },
                 [&d, val]( var const & v ) {
                     write_var_value( v.varinfo.type, v.varinfo.name,
                                      &d, val );
                 },
                 []( auto &/* v */ ) {
                     debugmsg( "Assignment called on eval tree" );
                 },
             },
             tree.data );
         }
References thingie::data, debugmsg, tree, and write_var_value().
error()
void math_exp::math_exp_impl::error (std::string_view str, std::string_view what) private
Definition at line 799 of file math_parser.cpp.
 {
     std::ptrdiff_t offset =
         std::max<std::ptrdiff_t>( 0, last_token.data() - str.data() );
     // center the problematic token on screen if the expression is too long
     if( offset > 80 ) {
         str.remove_prefix( offset - 40 );
         offset = 40;
     }
     // NOLINTNEXTLINE(cata-translate-string-literal): debug message
     std::string mess = string_format( "Expression parsing failed: %s", what );
     if( last_token == "(" && state.expected == parse_state::expect::oper &&
         std::holds_alternative<var>( output.top().data ) ) {
         // NOLINTNEXTLINE(cata-translate-string-literal): debug message
         mess = string_format( "%s (or unknown function %s)", mess,
                               std::get<var>( output.top().data ).varinfo.name.substr( 12 ) );
     }
     offset = std::max<std::ptrdiff_t>( 0, offset - 1 );
     debugmsg( "%s\n\n%.80s\n%*s\n", mess, str, offset, " " );
 }
References debugmsg, and string_format().
Referenced by parse().
eval()
double math_exp::math_exp_impl::eval (dialogue & d) const inline
Definition at line 295 of file math_parser.cpp.
{
             return tree.eval( d );
         }
References thingie::eval(), and tree.
maybe_first_argument()
void math_exp::math_exp_impl::maybe_first_argument () private
Definition at line 366 of file math_parser.cpp.
 {
     if( !arity.empty() && arity.top().allows_comma() && arity.top().current == 0 ) {
         arity.top().current++;
     }
 }
References arity.
new_array()
void math_exp::math_exp_impl::new_array () private
Definition at line 708 of file math_parser.cpp.
 {
     std::vector<thingie>::size_type const nparams = arity.top().current;
     std::vector<thingie> params( nparams );
     for( std::vector<thingie>::size_type i = 0; i < nparams; i++ ) {
         params[nparams - i - 1] = std::move( output.top() );
         output.pop();
     }
     output.emplace( std::in_place_type_t<array>(), std::move( params ) );
 }
new_func()
void math_exp::math_exp_impl::new_func () private
Definition at line 581 of file math_parser.cpp.
 {
     if( !ops.empty() && is_function( ops.top() ) ) {
         std::vector<thingie>::size_type const nparams = arity.top().current;
         if( arity.top().expected >= 0 ) {
             if( arity.top().current < arity.top().expected ) {
                 throw std::invalid_argument(
                     string_format( "Not enough arguments for function %s()", arity.top().sym ) );
             }
             if( arity.top().current > arity.top().expected ) {
                 throw std::invalid_argument(
                     string_format( "Too many arguments for function %s()", arity.top().sym ) );
             }
         }
         std::vector<thingie> params( nparams );
         diag_kwargs kwargs;
         for( std::vector<kwarg>::size_type i = 0; i < arity.top().nkwargs; i++ ) {
             if( !std::holds_alternative<kwarg>( output.top().data ) ) {
                 throw std::invalid_argument(
                     "All positional arguments must precede keyword-value pairs" );
             }
             kwarg &kw = std::get<kwarg>( output.top().data );
             kwargs.emplace( kw.key, _get_diag_value( *kw.val ) );
             output.pop();
         }
         for( std::vector<thingie>::size_type i = 0; i < nparams; i++ ) {
             params[nparams - i - 1] = std::move( output.top() );
             output.pop();
         }
         std::visit( overloaded{
             [&params, &kwargs, this]( scoped_diag_eval const & v )
             {
                 std::vector<diag_value> const args = _get_diag_vals( params );
                 output.emplace( std::in_place_type_t<func_diag_eval>(), v.df->f( v.scope, args, kwargs ) );
             },
             [&params, &kwargs, this]( scoped_diag_ass const & v )
             {
                 std::vector<diag_value> const args = _get_diag_vals( params );
                 output.emplace( std::in_place_type_t<func_diag_ass>(), v.df->f( v.scope, args, kwargs ) );
             },
             [&params, this]( pmath_func v )
             {
                 output.emplace( std::in_place_type_t<func>(), std::move( params ), v->f );
             },
             [&params, this]( jmath_func_id const & v )
             {
                 output.emplace( std::in_place_type_t<func_jmath>(), std::move( params ), v );
             },
             []( auto /* v */ )
             {
                 throw std::invalid_argument( "Internal func error.  That's all we know." );
             },
         },
         ops.top() );
         _validate_unused_kwargs( kwargs );
         ops.pop();
     }
 }
References anonymous_namespace{math_parser.cpp}::_validate_unused_kwargs(), anonymous_namespace{math_parser.cpp}::is_function(), kwarg::key, string_format(), and kwarg::val.
new_kwarg()
void math_exp::math_exp_impl::new_kwarg (thingie & lhs, thingie & rhs) private
Definition at line 684 of file math_parser.cpp.
 {
     if( arity.top().type != arity_t::type_t::func || !arity.top().stringy ) {
         throw std::invalid_argument( "kwargs are not supported in this scope" );
     }
     if( !std::holds_alternative<std::string>( lhs.data ) ) {
         throw std::invalid_argument( "kwarg key must be a string" );
     }
     output.emplace( std::in_place_type_t<kwarg>(), std::get<std::string>( lhs.data ), rhs );
     arity.top().current--;
     arity.top().nkwargs++;
 }
References thingie::data.
new_oper()
void math_exp::math_exp_impl::new_oper () private
Definition at line 719 of file math_parser.cpp.
 {
     op_t op( ops.top() );
     ops.pop();
     std::visit( overloaded{
         [this]( pbin_op v )
         {
             cata_assert( output.size() >= 2 );
             thingie rhs = std::move( output.top() );
             output.pop();
             thingie lhs = std::move( output.top() );
             output.pop();
             if( v->symbol == "?" ) {
                 throw std::invalid_argument( "Unterminated ternary" );
             }
             if( v->symbol == ":" ) {
                 std::string_view top_sym =
                     !ops.empty() && std::holds_alternative<pbin_op>( ops.top() )
                     ? std::get<pbin_op>( ops.top() )->symbol
                     : std::string_view{};
                 if( !output.empty() && top_sym == "?" ) {
                     new_ternary( lhs, rhs );
                 } else if( !arity.empty() && arity.top().current > 0 ) {
                     new_kwarg( lhs, rhs );
                 } else {
                     throw std::invalid_argument( "Misplaced colon" );
                 }
             } else {
                 _validate_operand( lhs, v->symbol );
                 _validate_operand( rhs, v->symbol );
                 output.emplace( std::in_place_type_t<oper>(), lhs, rhs, v->f );
             }
         },
         [this]( punary_op v )
         {
             cata_assert( !output.empty() );
             thingie rhs = std::move( output.top() );
             output.pop();
             _validate_operand( rhs, v->symbol );
             output.emplace( std::in_place_type_t<oper>(), thingie { 0.0 }, rhs, v->f );
         },
         []( auto /* v */ )
         {
             // we should never get here due to paren validation
             throw std::invalid_argument( "Internal oper error.  That's all we know." );
         }
     },
     op );
 }
References anonymous_namespace{math_parser.cpp}::_validate_operand(), and cata_assert.
new_ternary()
void math_exp::math_exp_impl::new_ternary (thingie & lhs, thingie & rhs) private
Definition at line 697 of file math_parser.cpp.
 {
     _validate_operand( lhs, "?:" );
     _validate_operand( rhs, "?:" );
     ops.pop();
     thingie cond = std::move( output.top() );
     _validate_operand( cond, "?:" );
     output.pop();
     output.emplace( std::in_place_type_t<ternary>(), cond, lhs, rhs );
 }
References anonymous_namespace{math_parser.cpp}::_validate_operand().
new_var()
void math_exp::math_exp_impl::new_var (std::string_view str) private
Definition at line 772 of file math_parser.cpp.
 {
     std::string_view scoped = str;
     var_type type = var_type::global;
     if( str.size() > 2 && str[1] == '_' ) {
         scoped = scoped.substr( 2 );
         switch( str[0] ) {
             case 'u':
                 type = var_type::u;
                 break;
             case 'n':
                 type = var_type::npc;
                 break;
             case 'v':
                 type = var_type::var;
                 break;
             default:
                 debugmsg( "Unknown scope %c in variable %s", str[0], str );
         }
     } else if( str.size() > 1 && str[0] == '_' ) {
         type = var_type::context;
         scoped = scoped.substr( 1 );
     }
     validate_string( scoped, "variable", " \'" );
     output.emplace( std::in_place_type_t<var>(), type, "npctalk_var_" + std::string{ scoped } );
 }
References context, debugmsg, global, npc, type, u, and var.
parse()
bool math_exp::math_exp_impl::parse (std::string_view str, bool assignment) inline
Definition at line 275 of file math_parser.cpp.
{
             if( str.empty() ) {
                 return false;
             }
             std::locale const &oldloc = std::locale::global( std::locale::classic() );
             on_out_of_scope reset_loc( [&oldloc]() {
                 std::locale::global( oldloc );
             } );
             try {
                 _parse( str, assignment );
             } catch( std::invalid_argument const &ex ) {
                 error( str, ex.what() );
                 ops = {};
                 output = {};
                 arity = {};
                 tree = thingie { 0.0 };
                 return false;
             }
             return true;
         }
References _parse(), arity, error(), ops, output, and tree.
parse_bin_op()
void math_exp::math_exp_impl::parse_bin_op (pbin_op const & op) private
Definition at line 487 of file math_parser.cpp.
 {
     if( op->symbol == ":" && !arity.empty() && arity.top().type == arity_t::type_t::ternary ) {
         // insert a pair of parens to help resolve nested ternaries like 0?0?-1:-2:1
         parse_rparen();
     }
     state.validate( parse_state::expect::oper );
     while( !ops.empty() && ops.top() > *op ) {
         new_oper();
     }
     ops.emplace( op );
     state.set( parse_state::expect::operand, true );
     if( op->symbol == "?" ) {
         parse_lparen( arity_t::type_t::ternary );
     }
 }
parse_comma()
void math_exp::math_exp_impl::parse_comma () private
Definition at line 513 of file math_parser.cpp.
 {
     state.validate( parse_state::expect::oper );
     if( arity.empty() || !arity.top().allows_comma() ) {
         throw std::invalid_argument( "Misplaced comma" );
     }
     while( ops.top() > paren::left ) {
         new_oper();
     }
     arity.top().current++;
     state.set( parse_state::expect::operand, true );
 }
References left.
parse_diag_f()
template<typename T > void math_exp::math_exp_impl::parse_diag_f (std::string_view symbol, T const & token) private
Definition at line 505 of file math_parser.cpp.
 {
     state.validate( parse_state::expect::operand );
     ops.emplace( token );
     arity.emplace( symbol, token.df->num_params, arity_t::type_t::func, true );
     state.set( parse_state::expect::lparen, false );
 }
References symbol().
parse_lbracket()
void math_exp::math_exp_impl::parse_lbracket () private
Definition at line 553 of file math_parser.cpp.
 {
     state.validate( parse_state::expect::lbracket );
     if( arity.empty() || !arity.top().stringy ) {
         throw std::invalid_argument( "Arrays can only be used as arguments for dialogue functions" );
     }
     arity.emplace( std::string_view{}, 0, arity_t::type_t::array,
                    !arity.empty() && arity.top().stringy );
     ops.emplace( paren::left_sq );
     state.set( parse_state::expect::operand, true );
 }
References left_sq.
parse_lparen()
void math_exp::math_exp_impl::parse_lparen (arity_t::type_t type = arity_t::type_t::parens) private
Definition at line 526 of file math_parser.cpp.
 {
     state.validate( parse_state::expect::lparen );
     if( ops.empty() || !is_function( ops.top() ) ) {
         arity.emplace( std::string_view{}, 0, type, !arity.empty() && arity.top().stringy );
     }
     ops.emplace( paren::left );
     state.set( parse_state::expect::operand, true );
 }
References anonymous_namespace{math_parser.cpp}::is_function(), left, and type.
parse_rbracket()
void math_exp::math_exp_impl::parse_rbracket () private
Definition at line 565 of file math_parser.cpp.
 {
     state.validate( parse_state::expect::rbracket );
     if( arity.empty() || arity.top().type != arity_t::type_t::array ) {
         throw std::invalid_argument( "Misplaced right bracket" );
     }
     while( !ops.empty() && ops.top() > paren::left_sq ) {
         new_oper();
     }
     ops.pop();
     new_array();
     arity.pop();
     maybe_first_argument();
     state.set( parse_state::expect::oper );
 }
References left_sq.
parse_rparen()
void math_exp::math_exp_impl::parse_rparen () private
Definition at line 536 of file math_parser.cpp.
 {
     state.validate( parse_state::expect::rparen );
     while( !ops.empty() && ops.top() > paren::left ) {
         new_oper();
     }
     if( ops.empty() || !std::holds_alternative<paren>( ops.top() ) ||
         std::get<paren>( ops.top() ) != paren::left ) {
         throw std::invalid_argument( "Misplaced right parenthesis" );
     }
     ops.pop();
     new_func();
     arity.pop();
     maybe_first_argument();
     state.set( parse_state::expect::oper, false );
 }
References left.
parse_string()
void math_exp::math_exp_impl::parse_string (std::string_view token, std::string_view full) private
Definition at line 465 of file math_parser.cpp.
 {
     if( !state.instring ) {
         state.validate( parse_state::expect::operand );
         maybe_first_argument();
         if( arity.empty() || !arity.top().stringy ) {
             throw std::invalid_argument( "String arguments can only be used in dialogue functions" );
         }
         state.instring = true;
         state.strpos = token;
         state.set( parse_state::expect::string, false );
     } else if( token == "'" ) {
         // FIXME: write a better tokenizer that returns the entire quoted string as a single token
         output.emplace( std::in_place_type_t<std::string>(), full, state.strpos.data() - full.data() + 1,
                         token.data() - state.strpos.data() - 1 );
         state.instring = false;
         state.set( parse_state::expect::oper, false );
     } else {
         // skip tokens inside string
     }
 }
validate_string()
void math_exp::math_exp_impl::validate_string (std::string_view str, std::string_view label, std::string_view badlist) private
Definition at line 821 of file math_parser.cpp.
 {
     std::string_view::size_type const pos = str.find_first_of( badlist );
     if( pos != std::string_view::npos ) {
         last_token.remove_prefix( pos + ( label == "string" ? 1 : 0 ) );
         // NOLINTNEXTLINE(cata-translate-string-literal): debug message
         throw std::invalid_argument( string_format( R"(Stray " %c " inside %s operand "%s")",
                                      str[pos], label, str ) );
     }
 }
References math_opers::pos(), and string_format().
Member Data Documentation
arity
std::stack<arity_t> math_exp::math_exp_impl::arity private
Definition at line 338 of file math_parser.cpp.
Referenced by maybe_first_argument(), and parse().
last_token
std::string_view math_exp::math_exp_impl::last_token private
Definition at line 340 of file math_parser.cpp.
ops
std::stack<op_t> math_exp::math_exp_impl::ops private
Definition at line 316 of file math_parser.cpp.
Referenced by parse().
output
std::stack<thingie> math_exp::math_exp_impl::output private
Definition at line 317 of file math_parser.cpp.
Referenced by parse().
state
parse_state math_exp::math_exp_impl::state private
Definition at line 341 of file math_parser.cpp.
tree
thingie math_exp::math_exp_impl::tree { 0.0 } private
Definition at line 339 of file math_parser.cpp.
Referenced by assign(), eval(), and parse().
The documentation for this class was generated from the following file:
src/math_parser.cpp