Cataclysm DDA: deduped_requirement_data Class Reference
deduped_requirement_data Class Reference
#include <requirements.h>
Public Types
using alter_item_comp_vector = requirement_data::alter_item_comp_vector
Public Member Functions
deduped_requirement_data ()=default
deduped_requirement_data (const requirement_data &, const recipe_id &context)
std::vector< requirement_data > const & alternatives () const
std::vector< const requirement_data * > feasible_alternatives (const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1, craft_flags=craft_flags::none) const
const requirement_data * select_alternative (Character &, const std::function< bool(const item &)> &filter, int batch=1, craft_flags=craft_flags::none) const
const requirement_data * select_alternative (Character &, const read_only_visitable &, const std::function< bool(const item &)> &filter, int batch=1, craft_flags=craft_flags::none) const
bool can_make_with_inventory (const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1, craft_flags=craft_flags::none) const
bool is_too_complex () const
Private Attributes
bool is_too_complex_ = false
std::vector< requirement_data > alternatives_
Detailed Description
Definition at line 455 of file requirements.h.
Member Typedef Documentation
alter_item_comp_vector
using deduped_requirement_data::alter_item_comp_vector = requirement_data::alter_item_comp_vector
Definition at line 458 of file requirements.h.
Constructor & Destructor Documentation
deduped_requirement_data() [1/2]
deduped_requirement_data::deduped_requirement_data () default
deduped_requirement_data() [2/2]
deduped_requirement_data::deduped_requirement_data (const requirement_data & in, const recipe_id & context)
Definition at line 1572 of file requirements.cpp.
 {
     // This constructor works through a requirement_data, converting it into an
     // equivalent set of requirement_data alternatives, where each alternative
     // has the property that no item type appears more than once.
     //
     // We maintain a queue of requirement_data component info to be split.
     // Each to_check struct has a vector of component requirements, and an
     // index.  The index is the position within the vector to be checked next.
     struct to_check {
         alter_item_comp_vector components;
         size_t index;
     };
     std::stack<to_check, std::vector<to_check>> pending;
     pending.push( { in.get_components(), 0 } );
     // Make sure the tools are not duplicated.
     requirement_data::alter_tool_comp_vector tools_unique;
     for( auto tools : in.get_tools() ) {
         std::sort( tools.begin(), tools.end() );
         tools.erase( std::unique( tools.begin(), tools.end() ), tools.end() );
         tools_unique.push_back( tools );
     }
     while( !pending.empty() ) {
         to_check next = pending.top();
         pending.pop();
         if( next.index == next.components.size() ) {
             alternatives_.emplace_back( tools_unique, in.get_qualities(), next.components );
             continue;
         }
         // Build a set of all the itypes used in later stages of this set of
         // requirements.
         std::unordered_set<itype_id> later_itypes;
         for( size_t i = next.index + 1; i != next.components.size(); ++i ) {
             std::transform( next.components[i].begin(), next.components[i].end(),
                             std::inserter( later_itypes, later_itypes.end() ),
             []( const item_comp & c ) {
                 return c.type;
             } );
         }
         std::vector<item_comp> this_requirement = next.components[next.index];
         auto first_duplicated = std::stable_partition(
                                     this_requirement.begin(), this_requirement.end(),
         [&]( const item_comp & c ) {
             return !later_itypes.count( c.type );
         }
                                 );
         for( auto comp_it = first_duplicated; comp_it != this_requirement.end(); ++comp_it ) {
             // Factor this requirement out into its own separate case
             alter_item_comp_vector req_prefix( next.components.begin(),
                                                next.components.begin() + next.index );
             std::vector<alter_item_comp_vector> result;
             expand_item_in_reqs( *comp_it, req_prefix, next.components, next.index, next.index + 1,
                                  result );
             for( const alter_item_comp_vector &v : result ) {
                 // When v is smaller, that means the current requirement was
                 // deleted, in which case we don't advance index.
                 size_t index_inc = v.size() == next.components.size() ? 1 : 0;
                 pending.push( { v, next.index + index_inc } );
             }
         }
         // Deal with all the remaining, non-duplicated ones
         this_requirement.erase( first_duplicated, this_requirement.end() );
         if( !this_requirement.empty() ) {
             alter_item_comp_vector without_dupes = next.components;
             without_dupes[next.index] = this_requirement;
             pending.push( { without_dupes, next.index + 1 } );
         }
         if( alternatives_.empty() && pending.empty() ) {
             debugmsg( "Recipe definition %s somehow has no valid recipes!", context.str() );
         }
         // Because this algorithm is super-exponential in the worst case, add a
         // sanity check to prevent things getting too far out of control.
         // The worst case in the core game currently is boots_fur
         // with 104 alternatives.
         static constexpr size_t max_alternatives = 105;
         if( alternatives_.size() + pending.size() > max_alternatives ) {
             debugmsg( "Construction of deduped_requirement_data generated too many alternatives.  "
                       "The recipe %1s should be simplified.  See the Recipe section in "
                       "doc/JSON_INFO.md for more details.  It has %2s alternatives.", context.str(),
                       alternatives_.size() + pending.size() );
             is_too_complex_ = true;
             alternatives_ = { in };
             return;
         }
     }
 }
References alternatives_, c, context, debugmsg, expand_item_in_reqs(), requirement_data::get_components(), requirement_data::get_qualities(), requirement_data::get_tools(), is_too_complex_, and pending.
Member Function Documentation
alternatives()
std::vector<requirement_data> const& deduped_requirement_data::alternatives () const inline
Definition at line 463 of file requirements.h.
{
             return alternatives_;
         }
References alternatives_.
Referenced by can_make_with_inventory(), and feasible_alternatives().
can_make_with_inventory()
bool deduped_requirement_data::can_make_with_inventory (const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1, craft_flags flags = craft_flags::none) const
Definition at line 1671 of file requirements.cpp.
 {
     return std::any_of( alternatives().begin(), alternatives().end(),
     [&]( const requirement_data & alt ) {
         return alt.can_make_with_inventory( crafting_inv, filter, batch, flags );
     } );
 }
References alt, alternatives(), keycode::end, and filter.
Referenced by basecamp::add_available_recipes(), anonymous_namespace{crafting_gui.cpp}::availability::availability(), Character::can_make(), Character::can_start_craft(), choose_crafter(), basecamp::recipe_batch_max(), basecamp::start_crafting(), and basecamp::start_fortifications().
feasible_alternatives()
std::vector< const requirement_data * > deduped_requirement_data::feasible_alternatives (const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1, craft_flags flags = craft_flags::none) const
Definition at line 1681 of file requirements.cpp.
 {
     std::vector<const requirement_data *> result;
     for( const requirement_data &req : alternatives() ) {
         if( req.can_make_with_inventory( crafting_inv, filter, batch, flags ) ) {
             result.push_back( &req );
         }
     }
     return result;
 }
References alternatives(), and filter.
Referenced by select_alternative().
is_too_complex()
bool deduped_requirement_data::is_too_complex () const inline
Definition at line 483 of file requirements.h.
{
             return is_too_complex_;
         }
References is_too_complex_.
Referenced by recipe_info().
select_alternative() [1/2]
const requirement_data * deduped_requirement_data::select_alternative (Character & crafter, const read_only_visitable & inv, const std::function< bool(const item &)> & filter, int batch = 1, craft_flags flags = craft_flags::none) const
Definition at line 1701 of file requirements.cpp.
 {
     const std::vector<const requirement_data *> all_reqs =
         feasible_alternatives( inv, filter, batch, flags );
     return crafter.select_requirements( all_reqs, 1, inv, filter );
 }
References feasible_alternatives(), filter, and Character::select_requirements().
select_alternative() [2/2]
const requirement_data * deduped_requirement_data::select_alternative (Character & crafter, const std::function< bool(const item &)> & filter, int batch = 1, craft_flags flags = craft_flags::none) const
Definition at line 1694 of file requirements.cpp.
 {
     return select_alternative( crafter, crafter.crafting_inventory(), filter, batch, flags );
 }
References Character::crafting_inventory(), and filter.
Referenced by basecamp_action_components::choose_components(), craft_command::execute(), and iuse::multicooker().
Member Data Documentation
alternatives_
std::vector<requirement_data> deduped_requirement_data::alternatives_ private
Definition at line 488 of file requirements.h.
Referenced by alternatives(), and deduped_requirement_data().
is_too_complex_
bool deduped_requirement_data::is_too_complex_ = false private
Definition at line 487 of file requirements.h.
Referenced by deduped_requirement_data(), and is_too_complex().
The documentation for this class was generated from the following files:
src/requirements.h
src/requirements.cpp