Cataclysm DDA: wish_item_callback Class Reference
wish_item_callback Class Reference
Public Member Functions
wish_item_callback (const std::vector< const itype * > &ids, const std::vector< const itype_variant_data * > &variants, std::string &snippet_ids)
void select (uilist *menu) override
After a new item is selected, call this once.
bool key (const input_context &ctxt, const input_event &event, int, uilist *menu) override
void refresh (uilist *menu) override
Public Member Functions inherited from uilist_callback
virtual ~uilist_callback ()=default
Public Attributes
int examine_pos
bool incontainer
bool spawn_everything
bool renew_snippet
std::string msg
std::string flags
std::string itype_flags
std::pair< int, std::string > chosen_snippet_id
const std::vector< const itype * > & standard_itype_ids
const std::vector< const itype_variant_data * > & itype_variants
std::string & last_snippet_id
Detailed Description
Definition at line 807 of file wish.cpp.
Constructor & Destructor Documentation
wish_item_callback()
wish_item_callback::wish_item_callback (const std::vector< const itype * > & ids, const std::vector< const itype_variant_data * > & variants, std::string & snippet_ids) inline explicit
Definition at line 822 of file wish.cpp.
                                                                                                                      :
             incontainer( false ), spawn_everything( false ),
             standard_itype_ids( ids ), itype_variants( variants ),
             last_snippet_id( snippet_ids ) {
         }
Member Function Documentation
key()
bool wish_item_callback::key (const input_context & ctxt, const input_event & event, int , uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 848 of file wish.cpp.
{
             const std::string &action = ctxt.input_to_action( event );
             const int cur_key = event.get_first_input();
             if( action == "CONTAINER" ) {
                 incontainer = !incontainer;
                 return true;
             }
             if( action == "FLAG" ) {
                 std::string edit_flags;
                 if( flags.empty() ) {
                     // If this is the first time using the FLAG action on this item, start with itype flags
                     edit_flags = itype_flags;
                 } else {
                     // Otherwise, edit the existing list of user-defined instance flags
                     edit_flags = flags;
                 }
                 string_input_popup popup;
                 popup
                 .title( _( "Flags:" ) )
                 .description( _( "UPPERCASE, no quotes, separate with spaces" ) )
                 .max_length( 100 )
                 .text( edit_flags )
                 .query();
                 // Save instance flags on this item (will be reset when selecting another item)
                 if( popup.confirmed() ) {
                     flags = popup.text();
                     return true;
                 }
             }
             if( action == "EVERYTHING" ) {
                 spawn_everything = !spawn_everything;
                 return true;
             }
             if( action == "SNIPPET" ) {
                 if( menu->selected <= -1 ) {
                     return true;
                 }
                 const int entnum = menu->selected;
                 const itype &selected_itype = *standard_itype_ids[entnum];
                 if( !selected_itype.snippet_category.empty() ) {
                     const std::string cat = selected_itype.snippet_category;
                     if( SNIPPET.has_category( cat ) ) {
                         std::vector<std::pair<snippet_id, std::string>> snippes = SNIPPET.get_snippets_by_category( cat,
                                 true );
                         if( !snippes.empty() ) {
                             uilist snipp_query;
                             snipp_query.text = _( "Choose snippet type." );
                             snipp_query.desc_lines_hint = 2;
                             snipp_query.desc_enabled = true;
                             int cnt = 0;
                             for( const std::pair<snippet_id, std::string> &elem : snippes ) {
                                 std::string desc = elem.second;
                                 snipp_query.addentry_desc( cnt, true, -1, elem.first.str(), desc );
                                 cnt ++;
                             }
                             snipp_query.query();
                             switch( snipp_query.ret ) {
                                 case UILIST_CANCEL:
                                     break;
                                 default:
                                     chosen_snippet_id = { entnum, snippes[snipp_query.ret].first.str() };
                                     break;
                             }
                         }
                     }
                 }
                 return true;
             }
             if( action == "SCROLL_DESC_UP" ) {
                 examine_pos = std::max( examine_pos - 1, 0 );
             }
             if( action == "SCROLL_DESC_DOWN" ) {
                 examine_pos += 1;
             }
             if( cur_key == KEY_LEFT || cur_key == KEY_RIGHT ) {
                 // For Renew snippet_id.
                 renew_snippet = true;
                 return true;
             }
             return false;
         }
References _, action, uilist::addentry_desc(), chosen_snippet_id, uilist::desc_enabled, uilist::desc_lines_hint, examine_pos, flags, snippet_library::get_snippets_by_category(), snippet_library::has_category(), incontainer, input_context::input_to_action(), itype_flags, KEY_LEFT, KEY_RIGHT, max(), popup(), uilist::query(), renew_snippet, uilist::ret, uilist::selected, SNIPPET, itype::snippet_category, spawn_everything, standard_itype_ids, uilist::text, and UILIST_CANCEL.
refresh()
void wish_item_callback::refresh (uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 932 of file wish.cpp.
{
             const int description_height = menu->w_height - 6;
             const int starty = 3;
             const int startx = menu->w_width - menu->pad_right;
             const std::string padding( menu->pad_right, ' ' );
             for( int y = 2; y < menu->w_height - 1; y++ ) {
                 mvwprintw( menu->window, point( startx - 1, y ), padding );
             }
             mvwhline( menu->window, point( startx, 1 ), ' ', menu->pad_right - 1 );
             const int entnum = menu->selected;
             if( entnum >= 0 && static_cast<size_t>( entnum ) < standard_itype_ids.size() ) {
                 item tmp = wishitem_produce( *standard_itype_ids[entnum], flags, false );
                 const itype_variant_data *variant = itype_variants[entnum];
                 if( variant != nullptr && tmp.has_itype_variant( false ) ) {
                     // Set the variant type as shown in the selected list item.
                     std::string variant_id = variant->id;
                     tmp.set_itype_variant( variant_id );
                 }
                 if( !tmp.type->snippet_category.empty() ) {
                     if( renew_snippet ) {
                         last_snippet_id = tmp.snip_id.str();
                         renew_snippet = false;
                     } else if( chosen_snippet_id.first == entnum && !chosen_snippet_id.second.empty() ) {
                         std::string snip = chosen_snippet_id.second;
                         if( snippet_id( snip ).is_valid() || snippet_id( snip ) == snippet_id::NULL_ID() ) {
                             tmp.snip_id = snippet_id( snip );
                             last_snippet_id = snip;
                         }
                     } else {
                         tmp.snip_id = snippet_id( last_snippet_id );
                     }
                 }
                 const std::string header = string_format( "#%d: %s%s%s", entnum,
                                            standard_itype_ids[entnum]->get_id().c_str(),
                                            incontainer ? _( " (contained)" ) : "",
                                            flags.empty() ? "" : _( " (flagged)" ) );
                 mvwprintz( menu->window, point( startx + ( menu->pad_right - 1 - utf8_width( header ) ) / 2, 1 ),
                            c_cyan, header );
                 std::vector<std::string> desc = foldstring( tmp.info( true ), menu->pad_right - 1 );
                 const bool do_scroll = desc.size() > static_cast<unsigned>( description_height );
                 examine_pos = std::min( examine_pos, static_cast<int>( desc.size() - description_height ) );
                 const int first_line = do_scroll ? examine_pos : 0;
                 const int last_line = do_scroll ? ( first_line + description_height ) : desc.size();
                 draw_scrollbar( menu->window, first_line, description_height, desc.size(), point( menu->w_width - 1,
                                 starty ),
                                 c_white, true );
                 for( int i = first_line; i < last_line; i++ ) {
                     fold_and_print( menu->window, point( startx, starty + i - first_line ), menu->pad_right - 1,
                                     c_light_gray, desc[i] );
                 }
             }
             mvwprintz( menu->window, point( startx, menu->w_height - 3 ), c_green, msg );
             msg.erase();
             input_context ctxt( menu->input_category, keyboard_mode::keycode );
             mvwprintw( menu->window, point( startx, menu->w_height - 2 ),
                        _( "[%s] find, [%s] container, [%s] flag, [%s] everything, [%s] snippet, [%s] quit" ),
                        ctxt.get_desc( "FILTER" ), ctxt.get_desc( "CONTAINER" ),
                        ctxt.get_desc( "FLAG" ), ctxt.get_desc( "EVERYTHING" ),
                        ctxt.get_desc( "SNIPPET" ),
                        ctxt.get_desc( "QUIT" ) );
             wnoutrefresh( menu->window );
         }
References _, c_cyan, c_green, c_light_gray, c_white, chosen_snippet_id, draw_scrollbar(), examine_pos, flags, fold_and_print(), foldstring(), input_context::get_desc(), std::this_thread::get_id(), item::has_itype_variant(), itype_variant_data::id, incontainer, item::info(), uilist::input_category, itype_variants, keycode, last_snippet_id, min(), msg, catacurses::mvwhline(), catacurses::mvwprintw(), mvwprintz(), string_id< translation >::NULL_ID(), uilist::pad_right, renew_snippet, uilist::selected, item::set_itype_variant(), item::snip_id, itype::snippet_category, standard_itype_ids, string_id< T >::str(), string_format(), item::type, utf8_width(), uilist::w_height, uilist::w_width, uilist::window, wishitem_produce(), and catacurses::wnoutrefresh().
select()
void wish_item_callback::select (uilist *) inline override virtual
After a new item is selected, call this once.
Reimplemented from uilist_callback.
Definition at line 829 of file wish.cpp.
{
             if( menu->selected < 0 ) {
                 return;
             }
             examine_pos = 0;
             chosen_snippet_id = { -1, "" };
             renew_snippet = true;
             const itype &selected_itype = *standard_itype_ids[menu->selected];
             // Make liquids "contained" by default (toggled with CONTAINER action)
             incontainer = selected_itype.phase == phase_id::LIQUID;
             // Clear instance flags when switching items
             flags.clear();
             // Grab default flags for the itype (added with the FLAG action)
             itype_flags = debug_menu::iterable_to_string( selected_itype.get_flags(), " ",
             []( const flag_id & f ) {
                 return f.str();
             } );
         }
References chosen_snippet_id, examine_pos, flags, itype::get_flags(), incontainer, debug_menu::iterable_to_string(), itype_flags, LIQUID, itype::phase, renew_snippet, uilist::selected, and standard_itype_ids.
Member Data Documentation
chosen_snippet_id
std::pair<int, std::string> wish_item_callback::chosen_snippet_id
Definition at line 817 of file wish.cpp.
Referenced by key(), refresh(), and select().
examine_pos
int wish_item_callback::examine_pos
Definition at line 810 of file wish.cpp.
Referenced by key(), refresh(), and select().
flags
std::string wish_item_callback::flags
Definition at line 815 of file wish.cpp.
Referenced by key(), refresh(), select(), and debug_menu::wishitem().
incontainer
bool wish_item_callback::incontainer
Definition at line 811 of file wish.cpp.
Referenced by key(), refresh(), select(), and debug_menu::wishitem().
itype_flags
std::string wish_item_callback::itype_flags
Definition at line 816 of file wish.cpp.
Referenced by key(), and select().
itype_variants
const std::vector<const itype_variant_data *>& wish_item_callback::itype_variants
Definition at line 819 of file wish.cpp.
Referenced by refresh().
last_snippet_id
std::string& wish_item_callback::last_snippet_id
Definition at line 820 of file wish.cpp.
Referenced by refresh().
msg
std::string wish_item_callback::msg
Definition at line 814 of file wish.cpp.
Referenced by refresh(), and debug_menu::wishitem().
renew_snippet
bool wish_item_callback::renew_snippet
Definition at line 813 of file wish.cpp.
Referenced by key(), refresh(), and select().
spawn_everything
bool wish_item_callback::spawn_everything
Definition at line 812 of file wish.cpp.
Referenced by key(), and debug_menu::wishitem().
standard_itype_ids
const std::vector<const itype *>& wish_item_callback::standard_itype_ids
Definition at line 818 of file wish.cpp.
Referenced by key(), refresh(), and select().
The documentation for this class was generated from the following file:
src/wish.cpp