Cataclysm DDA: zone_options Class Reference
zone_options Class Reference
#include <clzones.h>
Public Member Functions
virtual ~zone_options ()=default
virtual bool has_options () const
virtual bool query_at_creation ()
virtual bool query ()
virtual std::string get_zone_name_suggestion () const
virtual std::vector< std::pair< std::string, std::string > > get_descriptions () const
virtual void serialize (JsonOut &) const
virtual void deserialize (const JsonObject &)
Static Public Member Functions
static shared_ptr_fast< zone_options > create (const zone_type_id &type)
static bool is_valid (const zone_type_id &type, const zone_options &options)
Detailed Description
Definition at line 75 of file clzones.h.
Constructor & Destructor Documentation
~zone_options()
virtual zone_options::~zone_options () virtual default
Member Function Documentation
create()
shared_ptr_fast< zone_options > zone_options::create (const zone_type_id & type) static
Definition at line 171 of file clzones.cpp.
 {
     if( type == zone_type_FARM_PLOT ) {
         return make_shared_fast<plot_options>();
     } else if( type == zone_type_CONSTRUCTION_BLUEPRINT ) {
         return make_shared_fast<blueprint_options>();
     } else if( type == zone_type_LOOT_CUSTOM || type == zone_type_LOOT_ITEM_GROUP ) {
         return make_shared_fast<loot_options>();
     } else if( type == zone_type_UNLOAD_ALL ) {
         return make_shared_fast<unload_options>();
     } else if( std::find( ignorable_zone_types.begin(), ignorable_zone_types.end(),
                           type ) != ignorable_zone_types.end() ) {
         return make_shared_fast<ignorable_options>();
     }
     return make_shared_fast<zone_options>();
 }
References ignorable_zone_types, type, zone_type_CONSTRUCTION_BLUEPRINT, zone_type_FARM_PLOT, zone_type_LOOT_CUSTOM, zone_type_LOOT_ITEM_GROUP, and zone_type_UNLOAD_ALL.
Referenced by zone_data::deserialize(), mapgen_place_zone(), zone_data::set_type(), zone_data::zone_data(), and game::zones_manager().
deserialize()
virtual void zone_options::deserialize (const JsonObject &) inline virtual
Reimplemented in unload_options, loot_options, ignorable_options, blueprint_options, and plot_options.
Definition at line 114 of file clzones.h.
 {}
get_descriptions()
virtual std::vector<std::pair<std::string, std::string> > zone_options::get_descriptions () const inline virtual
Reimplemented in unload_options, loot_options, ignorable_options, blueprint_options, and plot_options.
Definition at line 109 of file clzones.h.
{
             return std::vector<std::pair<std::string, std::string>>();
         }
Referenced by game::zones_manager().
get_zone_name_suggestion()
virtual std::string zone_options::get_zone_name_suggestion () const inline virtual
Reimplemented in unload_options, loot_options, blueprint_options, and plot_options.
Definition at line 104 of file clzones.h.
{
             return "";
         }
has_options()
virtual bool zone_options::has_options () const inline virtual
Reimplemented in unload_options, loot_options, ignorable_options, blueprint_options, and plot_options.
Definition at line 87 of file clzones.h.
{
             return false;
         }
Referenced by game::zones_manager().
is_valid()
bool zone_options::is_valid (const zone_type_id & type, const zone_options & options) static
Definition at line 189 of file clzones.cpp.
 {
     if( type == zone_type_FARM_PLOT ) {
         return dynamic_cast<const plot_options *>( &options ) != nullptr;
     } else if( type == zone_type_CONSTRUCTION_BLUEPRINT ) {
         return dynamic_cast<const blueprint_options *>( &options ) != nullptr;
     } else if( type == zone_type_LOOT_CUSTOM || type == zone_type_LOOT_ITEM_GROUP ) {
         return dynamic_cast<const loot_options *>( &options ) != nullptr;
     } else if( type == zone_type_UNLOAD_ALL ) {
         return dynamic_cast<const unload_options *>( &options ) != nullptr;
     } else if( std::find( ignorable_zone_types.begin(), ignorable_zone_types.end(),
                           type ) != ignorable_zone_types.end() ) {
         return dynamic_cast<const ignorable_options *>( &options ) != nullptr;
     }
     // ensure options is not derived class for the rest of zone types
     return !options.has_options();
 }
References ignorable_zone_types, PATH_INFO::options(), type, zone_type_CONSTRUCTION_BLUEPRINT, zone_type_FARM_PLOT, zone_type_LOOT_CUSTOM, zone_type_LOOT_ITEM_GROUP, and zone_type_UNLOAD_ALL.
Referenced by zone_data::zone_data().
query()
virtual bool zone_options::query () inline virtual
Reimplemented in unload_options, loot_options, ignorable_options, blueprint_options, and plot_options.
Definition at line 99 of file clzones.h.
{
             return false;
         }
Referenced by game::zones_manager().
query_at_creation()
virtual bool zone_options::query_at_creation () inline virtual
Reimplemented in unload_options, loot_options, ignorable_options, blueprint_options, and plot_options.
Definition at line 93 of file clzones.h.
{
             return true;
         }
serialize()
virtual void zone_options::serialize (JsonOut &) const inline virtual
Reimplemented in unload_options, loot_options, ignorable_options, blueprint_options, and plot_options.
Definition at line 113 of file clzones.h.
 {}
The documentation for this class was generated from the following files:
src/clzones.h
src/clzones.cpp