Cataclysm DDA: query_popup Class Reference
query_popup Class Reference
UI class for displaying messages or querying player input with popups.
#include <popup.h>
Classes
struct button
struct query_option
struct result
Query result returned by query_once and query.
Public Member Functions
query_popup ()
Default construction.
query_popup & context (const std::string &cat)
Specify the input context.
template<typename ... Args>
query_popup & message (const std::string &fmt, Args &&... args)
Specify the query message.
template<typename ... Args>
query_popup & message (const char *const fmt, Args &&... args)
template<typename ... Args>
query_popup & wait_message (const nc_color &bar_color, const std::string &fmt, Args &&... args)
Like query_popup::message, but with waiting symbol prepended to the text.
template<typename ... Args>
query_popup & wait_message (const nc_color &bar_color, const char *const fmt, Args &&... args)
template<typename ... Args>
query_popup & wait_message (const std::string &fmt, Args &&... args)
template<typename ... Args>
query_popup & wait_message (const char *const fmt, Args &&... args)
query_popup & option (const std::string &opt)
Specify an action as an option.
query_popup & option (const std::string &opt, const std::function< bool(const input_event &)> &filter)
Specify an action as an option, and a filter of allowed input events for this action.
query_popup & allow_anykey (bool allow)
Specify whether non-option actions can be returned.
query_popup & allow_cancel (bool allow)
Specify whether an implicit cancel option is allowed.
query_popup & on_top (bool top)
Whether to show the popup on the top of the screen.
query_popup & full_screen (bool full)
Whether to show the popup in FULL_SCREEN_HEIGHT and FULL_SCREEN_WIDTH.
query_popup & cursor (size_t pos)
Specify starting cursor position.
query_popup & default_color (const nc_color &d_color)
Specify the default message color.
query_popup & preferred_keyboard_mode (keyboard_mode mode)
Specify the desired keyboard mode.
result query_once ()
Query once and return the result.
result query ()
Query until a valid action or an error happens and return the result.
Protected Member Functions
std::shared_ptr< query_popup_impl > create_or_get_impl ()
Create or get a ui_adaptor on the UI stack to handle redrawing and resizing of the popup.
Private Member Functions
void invalidate_ui () const
Static Private Member Functions
template<typename ... Args>
static void assert_format (const std::string_view, Args &&...)
static std::string wait_text (const std::string &text, const nc_color &bar_color)
static std::string wait_text (const std::string &text)
Private Attributes
std::string category
std::string text
std::vector< query_option > options
size_t cur
nc_color default_text_color
bool anykey
bool cancel
bool ontop
bool fullscr
keyboard_mode pref_kbd_mode
std::weak_ptr< query_popup_impl > p_impl
std::vector< std::string > folded_msg
std::vector< button > buttons
Friends
class query_popup_impl
Detailed Description
UI class for displaying messages or querying player input with popups.
Example:
std::string action = query_popup() .context("YESNOQUIT") // input context to use .message("%s", _("Do you want to save before jumping into the lava?")) .option("YES") // yes, save before jumping .option("NO") // no, don't save before jumping .option("QUIT") // NOOO, I didn't mean to jump into lava! .cursor(2) // default to the third option QUIT .query() // do the query, and get the input action and event .action // retrieve the input action
Please refer to documentation of individual functions for detailed explanation.
Definition at line 35 of file popup.h.
Constructor & Destructor Documentation
query_popup()
query_popup::query_popup ()
Default construction.
Note that context and options are not set in default construction, and calling query_once or query right after default construction will return { false, "ERROR", {} }.
Definition at line 147 of file popup.cpp.
     : cur( 0 ), default_text_color( c_white ), anykey( false ), cancel( false ),
       ontop( false ), fullscr( false ), pref_kbd_mode( keyboard_mode::keycode )
 {
 }
References cancel.
Member Function Documentation
allow_anykey()
query_popup & query_popup::allow_anykey (bool allow)
Specify whether non-option actions can be returned.
Definition at line 177 of file popup.cpp.
 {
     // Change does not affect cache, do not invalidate the window
     anykey = allow;
     return *this;
 }
References anykey.
Referenced by input_context::action_add(), popup(), and avatar::power_mutations().
allow_cancel()
query_popup & query_popup::allow_cancel (bool allow)
Specify whether an implicit cancel option is allowed.
This call does not list the cancel option in the UI. Use option("QUIT") instead to explicitly list cancel in the UI.
Definition at line 184 of file popup.cpp.
 {
     // Change does not affect cache, do not invalidate the window
     cancel = allow;
     return *this;
 }
References cancel.
Referenced by popup(), avatar::power_mutations(), Pickup::query_thief(), and query_ynq().
assert_format()
template<typename ... Args> static void query_popup::assert_format (const std::string_view , Args && ...) inline static private
Definition at line 237 of file popup.h.
{
             static_assert( sizeof...( Args ) > 0,
                            "Format string should take at least one argument.  "
                            "If your message is not a format string, "
                            "use `message( \"%s\", text )` instead." );
         }
Referenced by message(), and wait_message().
context()
query_popup & query_popup::context (const std::string & cat)
Specify the input context.
In addition to being used to handle input actions, the input context will also be used to generate option text, so it should always be specified as long as at least one option is specified with option(), even if query_once or query are not called afterwards.
Definition at line 153 of file popup.cpp.
 {
     invalidate_ui();
     category = cat;
     return *this;
 }
References category, and invalidate_ui().
Referenced by game::cancel_activity_or_ignore_query(), Character::melee_attack_abstract(), main_menu::new_character_tab(), iuse::play_game(), popup(), game::portal_storm_query(), avatar::power_mutations(), Pickup::query_thief(), query_yn(), and query_ynq().
create_or_get_impl()
std::shared_ptr< query_popup_impl > query_popup::create_or_get_impl () protected
Create or get a ui_adaptor on the UI stack to handle redrawing and resizing of the popup.
Definition at line 391 of file popup.cpp.
 {
     std::shared_ptr<query_popup_impl> impl = p_impl.lock();
     if( !impl ) {
         p_impl = impl = std::make_shared<query_popup_impl>( this );
         if( impl ) {
             impl->mark_resized();
             impl->keyboard_selected_option = short( cur );
         }
     }
     return impl;
 }
References cur, and p_impl.
Referenced by query(), query_once(), and static_popup::static_popup().
cursor()
query_popup & query_popup::cursor (size_t pos)
Specify starting cursor position.
Definition at line 205 of file popup.cpp.
 {
     // Change does not affect cache, do not invalidate window
     cur = pos;
     std::shared_ptr<query_popup_impl> impl = p_impl.lock();
     if( impl ) {
         impl->keyboard_selected_option = short( cur );
     }
     return *this;
 }
References cur, p_impl, and math_opers::pos().
Referenced by main_menu::new_character_tab(), Pickup::query_thief(), query_yn(), and query_ynq().
default_color()
query_popup & query_popup::default_color (const nc_color & d_color)
Specify the default message color.
Definition at line 216 of file popup.cpp.
 {
     default_text_color = d_color;
     return *this;
 }
References default_text_color.
Referenced by main_menu::new_character_tab(), game::portal_storm_query(), query_yn(), and query_ynq().
full_screen()
query_popup & query_popup::full_screen (bool full)
Whether to show the popup in FULL_SCREEN_HEIGHT and FULL_SCREEN_WIDTH.
The name is a misnomer from legacy code, the popup is not actually full-screen.
Definition at line 198 of file popup.cpp.
 {
     invalidate_ui();
     fullscr = full;
     return *this;
 }
References fullscr, and invalidate_ui().
Referenced by popup().
invalidate_ui()
void query_popup::invalidate_ui () const private
Definition at line 274 of file popup.cpp.
 {
     std::shared_ptr<query_popup_impl> ui = p_impl.lock();
     if( ui ) {
         ui->mark_resized();
     }
 }
References p_impl.
Referenced by context(), full_screen(), message(), on_top(), option(), preferred_keyboard_mode(), and wait_message().
message() [1/2]
template<typename ... Args> query_popup& query_popup::message (const char *const fmt, Args &&... args) inline
Definition at line 96 of file popup.h.
{
             assert_format( fmt, std::forward<Args>( args )... );
             invalidate_ui();
             text = string_format( fmt, std::forward<Args>( args )... );
             return *this;
         }
References assert_format(), invalidate_ui(), string_format(), and text.
message() [2/2]
template<typename ... Args> query_popup& query_popup::message (const std::string & fmt, Args &&... args) inline
Specify the query message.
Definition at line 89 of file popup.h.
{
             assert_format( fmt, std::forward<Args>( args )... );
             invalidate_ui();
             text = string_format( fmt, std::forward<Args>( args )... );
             return *this;
         }
References assert_format(), invalidate_ui(), string_format(), and text.
Referenced by input_context::action_add(), game::cancel_activity_or_ignore_query(), Character::melee_attack_abstract(), main_menu::new_character_tab(), iuse::play_game(), popup(), game::portal_storm_query(), avatar::power_mutations(), Pickup::query_thief(), query_yn(), query_ynq(), and game::zones_manager().
on_top()
query_popup & query_popup::on_top (bool top)
Whether to show the popup on the top of the screen.
Definition at line 191 of file popup.cpp.
 {
     invalidate_ui();
     ontop = top;
     return *this;
 }
References invalidate_ui(), and ontop.
Referenced by game::display_om_pathfinding_progress(), popup(), and game::zones_manager().
option() [1/2]
query_popup & query_popup::option (const std::string & opt)
Specify an action as an option.
The action must be present in the supplied context, either locally or globally. The same applies to other option methods.
Definition at line 160 of file popup.cpp.
 {
     invalidate_ui();
     options.emplace_back( opt, []( const input_event & ) {
         return true;
     } );
     return *this;
 }
References invalidate_ui(), and options.
Referenced by game::cancel_activity_or_ignore_query(), Character::melee_attack_abstract(), main_menu::new_character_tab(), iuse::play_game(), game::portal_storm_query(), Pickup::query_thief(), query_yn(), and query_ynq().
option() [2/2]
query_popup & query_popup::option (const std::string & opt, const std::function< bool(const input_event &)> & filter)
Specify an action as an option, and a filter of allowed input events for this action.
This is for compatibility with the "FORCE_CAPITAL_YN" option. Note that even if the input event is filtered, it will still select the respective dialog option, without closing the dialog.
Definition at line 169 of file popup.cpp.
 {
     invalidate_ui();
     options.emplace_back( opt, filter );
     return *this;
 }
References filter, invalidate_ui(), and options.
preferred_keyboard_mode()
query_popup & query_popup::preferred_keyboard_mode (keyboard_mode mode)
Specify the desired keyboard mode.
Used in keybindings menu to assign actions to input events of the appropriate type of the parent UI.
Definition at line 222 of file popup.cpp.
 {
     invalidate_ui();
     pref_kbd_mode = mode;
     return *this;
 }
References invalidate_ui(), and pref_kbd_mode.
Referenced by input_context::action_add(), game::cancel_activity_or_ignore_query(), popup(), avatar::power_mutations(), Pickup::query_thief(), and query_yn().
query()
query_popup::result query_popup::query ()
Query until a valid action or an error happens and return the result.
Definition at line 403 of file popup.cpp.
 {
     std::shared_ptr<query_popup_impl> ui = create_or_get_impl();
     result res;
     do {
         res = query_once();
     } while( res.wait_input );
     return res;
 }
References create_or_get_impl(), query_once(), and query_popup::result::wait_input.
Referenced by input_context::action_add(), game::cancel_activity_or_ignore_query(), Character::melee_attack_abstract(), main_menu::new_character_tab(), iuse::play_game(), popup(), game::portal_storm_query(), avatar::power_mutations(), Pickup::query_thief(), query_yn(), and query_ynq().
query_once()
query_popup::result query_popup::query_once ()
Query once and return the result.
In order for this method to return valid results, the popup must either have at least one option, or have allow_cancel or allow_anykey set to true. Otherwise { false, "ERROR", {} } is returned. The same applies to query.
Definition at line 282 of file popup.cpp.
 {
     if( !anykey && !cancel && options.empty() ) {
         return { false, "ERROR", {} };
     }
     if( test_mode ) {
         return { false, "ERROR", {} };
     }
     std::shared_ptr<query_popup_impl> impl = create_or_get_impl();
     // ImGui doesn't like to show the window on the first drawn frame, so we do this
     ui_manager::redraw();
     input_context ctxt( category, pref_kbd_mode );
     if( cancel || !options.empty() ) {
         ctxt.register_action( "HELP_KEYBINDINGS" );
     }
     if( !options.empty() ) {
         ctxt.register_action( "CONFIRM" );
         for( const query_popup::query_option &opt : options ) {
             ctxt.register_action( opt.action );
         }
         // Mouse movement and button
         ctxt.register_action( "SELECT" );
         ctxt.register_action( "MOUSE_MOVE" );
         ctxt.register_action( "LEFT" );
         ctxt.register_action( "RIGHT" );
     }
     if( anykey ) {
         ctxt.register_action( "ANY_INPUT" );
         // Mouse movement, button, and wheel
         ctxt.register_action( "COORDINATE" );
     }
     if( cancel ) {
         ctxt.register_action( "QUIT" );
     }
 #if defined(WIN32) || defined(TILES)
     ctxt.set_timeout( 50 );
 #endif
     result res;
     // Assign outside construction of `res` to ensure execution order
     res.wait_input = !anykey;
     do {
         ui_manager::redraw();
         res.action = ctxt.handle_input();
         res.evt = ctxt.get_raw_input();
         // If we're tracking mouse movement
         if( !options.empty() && res.action == "SELECT" && impl->get_mouse_selected_option() != -1 ) {
             // Left-click to confirm selection
             res.action = "CONFIRM";
             cur = size_t( impl->get_mouse_selected_option() );
         } else if( res.action == "CONFIRM" && impl->keyboard_selected_option != -1 ) {
             cur = size_t( impl->keyboard_selected_option );
         }
     } while(
         // Always ignore mouse movement
         ( res.evt.type == input_event_t::mouse &&
           res.evt.get_first_input() == static_cast<int>( MouseInput::Move ) ) ||
         // Ignore window losing focus in SDL
         ( res.evt.type == input_event_t::keyboard_char && res.evt.sequence.empty() ) ||
         res.evt.type == input_event_t::timeout
     );
     if( cancel && res.action == "QUIT" ) {
         res.wait_input = false;
     } else if( res.action == "CONFIRM" ) {
         if( cur < options.size() ) {
             res.wait_input = false;
             res.action = options[cur].action;
         }
     } else if( res.action == "LEFT" ) {
         if( impl->keyboard_selected_option > 0 ) {
             impl->keyboard_selected_option--;
         } else {
             impl->keyboard_selected_option = short( buttons.size() - 1 );
         }
     } else if( res.action == "RIGHT" ) {
         if( impl->keyboard_selected_option < short( buttons.size() - 1 ) ) {
             impl->keyboard_selected_option++;
         } else {
             impl->keyboard_selected_option = 0;
         }
     } else if( res.action == "HELP_KEYBINDINGS" ) {
         // Keybindings may have changed, regenerate the UI
         std::shared_ptr<query_popup_impl> impl = p_impl.lock();
         if( impl ) {
             impl->on_resized();
         }
         //init();
     } else {
         for( size_t ind = 0; ind < options.size(); ++ind ) {
             if( res.action == options[ind].action ) {
                 impl->keyboard_selected_option = ind;
                 if( options[ind].filter( res.evt ) ) {
                     res.wait_input = false;
                     break;
                 }
             }
         }
     }
     return res;
 }
References query_popup::result::action, anykey, buttons, cancel, category, create_or_get_impl(), cur, query_popup::result::evt, filter, input_event::get_first_input(), input_context::get_raw_input(), input_context::handle_input(), keyboard_char, mouse, Move, options, p_impl, pref_kbd_mode, ui_manager::redraw(), input_context::register_action(), input_event::sequence, input_context::set_timeout(), test_mode, timeout, input_event::type, and query_popup::result::wait_input.
Referenced by query().
wait_message() [1/4]
template<typename ... Args> query_popup& query_popup::wait_message (const char *const fmt, Args &&... args) inline
Definition at line 127 of file popup.h.
{
             assert_format( fmt, std::forward<Args>( args )... );
             invalidate_ui();
             text = wait_text( string_format( fmt, std::forward<Args>( args )... ) );
             return *this;
         }
References assert_format(), invalidate_ui(), string_format(), text, and wait_text().
wait_message() [2/4]
template<typename ... Args> query_popup& query_popup::wait_message (const nc_color & bar_color, const char *const fmt, Args &&... args) inline
Definition at line 113 of file popup.h.
{
             assert_format( fmt, std::forward<Args>( args )... );
             invalidate_ui();
             text = wait_text( string_format( fmt, std::forward<Args>( args )... ), bar_color );
             return *this;
         }
References assert_format(), invalidate_ui(), string_format(), text, and wait_text().
wait_message() [3/4]
template<typename ... Args> query_popup& query_popup::wait_message (const nc_color & bar_color, const std::string & fmt, Args &&... args) inline
Like query_popup::message, but with waiting symbol prepended to the text.
Definition at line 106 of file popup.h.
{
             assert_format( fmt, std::forward<Args>( args )... );
             invalidate_ui();
             text = wait_text( string_format( fmt, std::forward<Args>( args )... ), bar_color );
             return *this;
         }
References assert_format(), invalidate_ui(), string_format(), text, and wait_text().
Referenced by game::display_om_pathfinding_progress().
wait_message() [4/4]
template<typename ... Args> query_popup& query_popup::wait_message (const std::string & fmt, Args &&... args) inline
Definition at line 120 of file popup.h.
{
             assert_format( fmt, std::forward<Args>( args )... );
             invalidate_ui();
             text = wait_text( string_format( fmt, std::forward<Args>( args )... ) );
             return *this;
         }
References assert_format(), invalidate_ui(), string_format(), text, and wait_text().
wait_text() [1/2]
std::string query_popup::wait_text (const std::string & text) static private
Definition at line 422 of file popup.cpp.
 {
     return wait_text( text, c_light_green );
 }
References c_light_green, text, and wait_text().
wait_text() [2/2]
std::string query_popup::wait_text (const std::string & text, const nc_color & bar_color) static private
Definition at line 414 of file popup.cpp.
 {
     static const std::array<std::string, 4> phase_icons = {{ "|", "/", "-", "\\" }};
     static size_t phase = phase_icons.size() - 1;
     phase = ( phase + 1 ) % phase_icons.size();
     return string_format( " %s %s", colorize( phase_icons[phase], bar_color ), text );
 }
References colorize(), string_format(), and text.
Referenced by wait_message(), and wait_text().
Friends And Related Function Documentation
query_popup_impl
friend class query_popup_impl friend
Definition at line 37 of file popup.h.
Member Data Documentation
anykey
bool query_popup::anykey private
Definition at line 213 of file popup.h.
Referenced by allow_anykey(), and query_once().
buttons
std::vector<button> query_popup::buttons mutable private
Definition at line 232 of file popup.h.
Referenced by query_popup_impl::draw_controls(), query_popup_impl::on_resized(), and query_once().
cancel
bool query_popup::cancel private
Definition at line 214 of file popup.h.
Referenced by allow_cancel(), and query_once().
category
std::string query_popup::category private
Definition at line 208 of file popup.h.
Referenced by context(), query_popup_impl::on_resized(), and query_once().
cur
size_t query_popup::cur private
Definition at line 211 of file popup.h.
Referenced by create_or_get_impl(), cursor(), and query_once().
default_text_color
nc_color query_popup::default_text_color private
Definition at line 212 of file popup.h.
Referenced by default_color(), and query_popup_impl::draw_controls().
folded_msg
std::vector<std::string> query_popup::folded_msg mutable private
Definition at line 231 of file popup.h.
Referenced by query_popup_impl::draw_controls(), and query_popup_impl::on_resized().
fullscr
bool query_popup::fullscr private
Definition at line 216 of file popup.h.
Referenced by full_screen().
ontop
bool query_popup::ontop private
Definition at line 215 of file popup.h.
Referenced by query_popup_impl::get_bounds(), and on_top().
options
std::vector<query_option> query_popup::options private
Definition at line 210 of file popup.h.
Referenced by query_popup_impl::on_resized(), option(), and query_once().
p_impl
std::weak_ptr<query_popup_impl> query_popup::p_impl private
Definition at line 228 of file popup.h.
Referenced by create_or_get_impl(), cursor(), invalidate_ui(), and query_once().
pref_kbd_mode
keyboard_mode query_popup::pref_kbd_mode private
Definition at line 217 of file popup.h.
Referenced by query_popup_impl::on_resized(), preferred_keyboard_mode(), and query_once().
text
std::string query_popup::text private
Definition at line 209 of file popup.h.
Referenced by message(), query_popup_impl::on_resized(), wait_message(), and wait_text().
The documentation for this class was generated from the following files:
src/popup.h
src/popup.cpp