Cataclysm DDA: update_mapgen_function_json Class Reference
update_mapgen_function_json Class Reference
#include <mapgen.h>
Public Member Functions
update_mapgen_function_json (const JsonObject &jsobj, const std::string &context)
~update_mapgen_function_json () override=default
void setup ()
bool setup_update (const JsonObject &jo)
void finalize_parameters ()
void check () const
bool update_map (const tripoint_abs_omt &omt_pos, const mapgen_arguments &, const tripoint_rel_ms &offset, mission *miss, bool verify=false, bool mirror_horizontal=false, bool mirror_vertical=false, int rotation=0) const
bool update_map (const mapgendata &md, const tripoint_rel_ms &offset=tripoint_rel_ms(tripoint_zero), bool verify=false) const
Public Member Functions inherited from mapgen_function_json_base
void merge_non_nest_parameters_into (mapgen_parameters &, const std::string &outer_context) const
bool check_inbounds (const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const JsonObject &jso) const
size_t calc_index (const point &p) const
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &offset) const
void add_placement_coords_to (std::unordered_set< point > &) const
const mapgen_parameters & get_parameters () const
Protected Member Functions
bool setup_internal (const JsonObject &) override
Protected Member Functions inherited from mapgen_function_json_base
mapgen_function_json_base (const JsonObject &jsobj, const std::string &context)
virtual ~mapgen_function_json_base ()
void setup_common ()
bool setup_common (const JsonObject &jo)
void setup_setmap (const JsonArray &parray)
virtual void setup_setmap_internal ()
void finalize_parameters_common ()
void check_common () const
mapgen_arguments get_args (const mapgendata &md, mapgen_parameter_scope) const
Protected Attributes
ter_id fill_ter
Protected Attributes inherited from mapgen_function_json_base
std::string context_
enum_bitset< jmapgen_flags > flags_
bool is_ready
point mapgensize
tripoint_rel_ms m_offset
point total_size
std::vector< jmapgen_setmap > setmap_points
jmapgen_objects objects
mapgen_parameters parameters
Detailed Description
Definition at line 516 of file mapgen.h.
Constructor & Destructor Documentation
update_mapgen_function_json()
update_mapgen_function_json::update_mapgen_function_json (const JsonObject & jsobj, const std::string & context)
Definition at line 7791 of file mapgen.cpp.
                                                         :
     mapgen_function_json_base( jsobj, context )
 {
 }
~update_mapgen_function_json()
update_mapgen_function_json::~update_mapgen_function_json () override default
Member Function Documentation
check()
void update_mapgen_function_json::check () const
Definition at line 7797 of file mapgen.cpp.
 {
     check_common();
 }
References mapgen_function_json_base::check_common().
finalize_parameters()
void update_mapgen_function_json::finalize_parameters ()
Definition at line 4484 of file mapgen.cpp.
 {
     finalize_parameters_common();
 }
setup()
void update_mapgen_function_json::setup ()
Definition at line 4469 of file mapgen.cpp.
 {
     setup_common();
 }
setup_internal()
bool update_mapgen_function_json::setup_internal (const JsonObject &) override protected virtual
Implements mapgen_function_json_base.
Definition at line 7814 of file mapgen.cpp.
 {
     fill_ter = t_null;
     /* update_mapgen doesn't care about fill_ter or rows */
     return true;
 }
References fill_ter, and t_null.
setup_update()
bool update_mapgen_function_json::setup_update (const JsonObject & jo)
Definition at line 7809 of file mapgen.cpp.
 {
     return setup_common( jo );
 }
References mapgen_function_json_base::setup_common().
update_map() [1/2]
bool update_mapgen_function_json::update_map (const mapgendata & md, const tripoint_rel_ms & offset = tripoint_rel_ms(tripoint_zero), bool verify = false) const
Definition at line 7887 of file mapgen.cpp.
 {
     mapgendata md_with_params( md, get_args( md, mapgen_parameter_scope::omt ), flags_ );
     rotation_guard rot( md_with_params );
     return apply_mapgen_in_phases( md_with_params, setmap_points, objects, offset, context_,
                                    verify );
 }
References apply_mapgen_in_phases(), mapgen_function_json_base::context_, mapgen_function_json_base::flags_, mapgen_function_json_base::get_args(), mapgen_function_json_base::objects, omt, and mapgen_function_json_base::setmap_points.
update_map() [2/2]
bool update_mapgen_function_json::update_map (const tripoint_abs_omt & omt_pos, const mapgen_arguments & args, const tripoint_rel_ms & offset, mission * miss, bool verify = false, bool mirror_horizontal = false, bool mirror_vertical = false, int rotation = 0) const
Definition at line 7821 of file mapgen.cpp.
 {
     if( omt_pos == overmap::invalid_tripoint ) {
         debugmsg( "Mapgen update function called with overmap::invalid_tripoint" );
         return false;
     }
     std::unique_ptr<smallmap> p_update_smap = std::make_unique<smallmap>();
     smallmap &update_smap = *p_update_smap;
     update_smap.load( omt_pos, true );
     update_smap.rotate( 4 - rotation );
     update_smap.mirror( mirror_horizontal, mirror_vertical );
     mapgendata md_base( omt_pos, *update_smap.cast_to_map(), 0.0f, calendar::start_of_cataclysm, miss );
     mapgendata md( md_base, args );
     bool const u = update_map( md, offset, verify );
     update_smap.mirror( mirror_horizontal, mirror_vertical );
     update_smap.rotate( rotation );
     if( get_map().inbounds( project_to<coords::ms>( omt_pos ) ) ) {
         // trigger main map cleanup
         p_update_smap.reset();
         // trigger new traps, etc
         g->place_player( get_avatar().pos(), true );
     }
     // Trigger magic to add roofs (within load) if needed.
     if( omt_pos.z() < OVERMAP_HEIGHT ) {
         std::unique_ptr<smallmap> p_roof_smap = std::make_unique<smallmap>();
         smallmap &roof_smap = *p_roof_smap;
         // The loading of the Z level above is not necessary, but looks better.
         const tripoint_abs_omt omt_above = { omt_pos.x(), omt_pos.y(), omt_pos.z() + 1 };
         roof_smap.load( omt_above, false );
     }
     return u;
 }
References tinymap::cast_to_map(), debugmsg, g, get_avatar(), get_map(), overmap::invalid_tripoint, tinymap::load(), tinymap::mirror(), OVERMAP_HEIGHT, math_opers::pos(), tinymap::rotate(), calendar::start_of_cataclysm, u, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Member Data Documentation
fill_ter
ter_id update_mapgen_function_json::fill_ter protected
Definition at line 536 of file mapgen.h.
Referenced by setup_internal().
The documentation for this class was generated from the following files:
src/mapgen.h
src/mapgen.cpp