Cataclysm DDA: pocket_favorite_callback Class Reference
pocket_favorite_callback Class Reference
Public Member Functions
pocket_favorite_callback (const std::string &uilist_text, const std::vector< item * > &to_organize, uilist &pocket_selector)
void refresh (uilist *menu) override
bool key (const input_context &, const input_event &event, int entnum, uilist *menu) override
Public Member Functions inherited from uilist_callback
virtual void select (uilist *)
After a new item is selected, call this once.
virtual ~uilist_callback ()=default
Private Member Functions
void move_item (uilist *menu, item_pocket *selected_pocket)
void refresh_columns (uilist *menu)
void add_pockets (item &i, uilist &pocket_selector, const std::string &depth)
Private Attributes
std::vector< std::tuple< item_pocket *, int, uilist_entry * > > saved_pockets
bool whitelist = true
std::pair< item *, item_pocket * > item_to_move = { nullptr, nullptr }
bool needs_to_refresh = false
std::string uilist_text
std::vector< item * > to_organize
Detailed Description
Definition at line 40 of file item_contents.cpp.
Constructor & Destructor Documentation
pocket_favorite_callback()
pocket_favorite_callback::pocket_favorite_callback (const std::string & uilist_text, const std::vector< item * > & to_organize, uilist & pocket_selector) explicit
Definition at line 122 of file item_contents.cpp.
     : uilist_text( uilist_text ), to_organize( to_organize )
 {
     for( item *i : to_organize ) {
         add_pockets( *i, pocket_selector, "" );
     }
 }
References add_pockets(), and to_organize.
Member Function Documentation
add_pockets()
void pocket_favorite_callback::add_pockets (item & i, uilist & pocket_selector, const std::string & depth) private
Definition at line 131 of file item_contents.cpp.
 {
     if( i.get_all_contained_pockets().empty() ) {
         // if it doesn't have pockets skip it
         return;
     }
     pocket_selector.addentry( -1, false, '\0', string_format( "%s%s", depth, i.display_name() ) );
     // pad list with empty entries for the items themselves
     saved_pockets.emplace_back( nullptr, 0, nullptr );
     if( ( i.is_collapsed() && to_organize.size() != 1 ) || i.all_pockets_sealed() ) {
         //is collapsed, or all pockets are sealed skip its nested pockets
         // only skip collapsed items if doing multi menu, for a single item this wouldn't make sense
         return;
     }
     uilist_entry *item_entry = &pocket_selector.entries.back();
     int pocket_num = 1;
     for( item_pocket *it_pocket : i.get_all_contained_pockets() ) {
         std::string temp = string_format( "%d -", pocket_num );
         pocket_selector.addentry( 0, true, '\0', string_format( "%s%s %s/%s",
                                   depth,
                                   temp,
                                   vol_to_info( "", "", it_pocket->contains_volume() ).sValue,
                                   vol_to_info( "", "", it_pocket->max_contains_volume() ).sValue ) );
         // pocket number is displayed from 1 stored from 0
         saved_pockets.emplace_back( it_pocket, pocket_num - 1, item_entry );
         pocket_num++;
         // display the items
         for( item *it : it_pocket->all_items_top() ) {
             // check for pockets in that pocket
             add_pockets( *it, pocket_selector, depth + "  " );
         }
     }
 }
References uilist::addentry(), item::all_items_top(), item::all_pockets_sealed(), item::display_name(), uilist::entries, item::get_all_contained_pockets(), item::is_collapsed(), saved_pockets, string_format(), iteminfo::sValue, temp, to_organize, and vol_to_info().
Referenced by pocket_favorite_callback(), and refresh_columns().
key()
bool pocket_favorite_callback::key (const input_context & ctxt, const input_event & event, int entnum, uilist * menu) override virtual
Reimplemented from uilist_callback.
Definition at line 269 of file item_contents.cpp.
 {
     item_pocket *selected_pocket = nullptr;
     int i = 0;
     int pocket_num = 0;
     for( std::tuple<item_pocket *, int, uilist_entry *> &pocket_val : saved_pockets ) {
         item_pocket *pocket = std::get<0>( pocket_val );
         if( pocket == nullptr || ( pocket->get_pocket_data()  &&
                                    !pocket->is_type( pocket_type::CONTAINER ) ) ) {
             ++i;
             continue;
         }
         if( i == menu->selected ) {
             selected_pocket = pocket;
             pocket_num = std::get<1>( pocket_val ) + 1;
             break;
         }
         ++i;
     }
     if( selected_pocket == nullptr ) {
         return false;
     }
     const std::string remove_prefix = "<color_light_red>-</color> ";
     const std::string add_prefix = "<color_green>+</color> ";
     const std::string &action = ctxt.input_to_action( event );
     if( action == "FAV_WHITELIST" ) {
         whitelist = true;
         return true;
     } else if( action == "FAV_BLACKLIST" ) {
         whitelist = false;
         return true;
     } else if( action == "FAV_PRIORITY" ) {
         string_input_popup popup;
         popup.title( string_format( _( "Enter Priority (current priority %d)" ),
                                     selected_pocket->settings.priority() ) );
         const int ret = popup.query_int();
         if( popup.confirmed() ) {
             selected_pocket->settings.set_priority( ret );
             selected_pocket->settings.set_was_edited();
         }
         return true;
     } else if( action == "FAV_AUTO_PICKUP" ) {
         selected_pocket->settings.set_disabled( !selected_pocket->settings.is_disabled() );
         selected_pocket->settings.set_was_edited();
         return true;
     } else if( action == "FAV_AUTO_UNLOAD" ) {
         selected_pocket->settings.set_unloadable( !selected_pocket->settings.is_unloadable() );
         selected_pocket->settings.set_was_edited();
         return true;
     } else if( action == "FAV_MOVE_ITEM" ) {
         move_item( menu, selected_pocket );
         selected_pocket->settings.set_was_edited();
         return true;
     } else if( action == "FAV_ITEM" ) {
         const cata::flat_set<itype_id> &listed_itypes = whitelist
                 ? selected_pocket->settings.get_item_whitelist()
                 : selected_pocket->settings.get_item_blacklist();
         cata::flat_set<itype_id> nearby_itypes;
         uilist selector_menu;
         selector_menu.title = _( "Select an item from nearby" );
         for( const std::list<item> *it_list : get_player_character().crafting_inventory().const_slice() ) {
             nearby_itypes.insert( it_list->front().typeId() );
         }
         std::vector<std::pair<itype_id, std::string>> listed_names;
         std::vector<std::pair<itype_id, std::string>> nearby_names;
         listed_names.reserve( listed_itypes.size() );
         nearby_names.reserve( nearby_itypes.size() );
         for( const itype_id &id : listed_itypes ) {
             listed_names.emplace_back( id, id->nname( 1 ) );
         }
         for( const itype_id &id : nearby_itypes ) {
             if( !listed_itypes.count( id ) && selected_pocket->is_compatible( item( id ) ).success() ) {
                 nearby_names.emplace_back( id, id->nname( 1 ) );
             }
         }
         const auto &compare_names = []( const std::pair<itype_id, std::string> &lhs,
         const std::pair<itype_id, std::string> &rhs ) {
             return localized_compare( lhs.second, rhs.second );
         };
         std::sort( listed_names.begin(), listed_names.end(), compare_names );
         std::sort( nearby_names.begin(), nearby_names.end(), compare_names );
         for( const std::pair<itype_id, std::string> &it : listed_names ) {
             selector_menu.addentry( remove_prefix + it.second );
         }
         for( const std::pair<itype_id, std::string> &it : nearby_names ) {
             selector_menu.addentry( add_prefix + it.second );
         }
         if( selector_menu.entries.empty() ) {
             popup( std::string( _( "No nearby items would fit here." ) ), PF_GET_KEY );
         } else {
             selector_menu.query();
         }
         const int selected = selector_menu.ret;
         itype_id selected_id = itype_id::NULL_ID();
         if( selected >= 0 ) {
             size_t idx = selected;
             const std::vector<std::pair<itype_id, std::string>> *names = nullptr;
             if( idx < listed_names.size() ) {
                 names = &listed_names;
             } else {
                 idx -= listed_names.size();
             }
             if( !names && idx < nearby_names.size() ) {
                 names = &nearby_names;
             }
             if( names ) {
                 selected_id = ( *names )[idx].first;
             }
         }
         if( !selected_id.is_null() ) {
             if( whitelist ) {
                 selected_pocket->settings.whitelist_item( selected_id );
             } else {
                 selected_pocket->settings.blacklist_item( selected_id );
             }
             selected_pocket->settings.set_was_edited();
         }
         return true;
     } else if( action == "FAV_CATEGORY" ) {
         // Get all categories and sort by name
         std::vector<item_category> all_cat = item_category::get_all();
         const cata::flat_set<item_category_id> &listed_cat = whitelist
                 ? selected_pocket->settings.get_category_whitelist()
                 : selected_pocket->settings.get_category_blacklist();
         std::sort( all_cat.begin(), all_cat.end(), [&]( const item_category & lhs,
         const item_category & rhs ) {
             const bool lhs_in_list = listed_cat.count( lhs.get_id() );
             const bool rhs_in_list = listed_cat.count( rhs.get_id() );
             if( lhs_in_list && !rhs_in_list ) {
                 return true;
             } else if( !lhs_in_list && rhs_in_list ) {
                 return false;
             }
             return localized_compare( lhs.name_header(), rhs.name_header() );
         } );
         uilist selector_menu;
         for( const item_category &cat : all_cat ) {
             const bool in_list = listed_cat.count( cat.get_id() );
             const std::string &prefix = in_list ? remove_prefix : add_prefix;
             selector_menu.addentry( prefix + cat.name_header() );
         }
         selector_menu.query();
         if( selector_menu.ret >= 0 ) {
             const item_category_id id( all_cat.at( selector_menu.ret ).get_id() );
             if( whitelist ) {
                 selected_pocket->settings.whitelist_category( id );
             } else {
                 selected_pocket->settings.blacklist_category( id );
             }
             selected_pocket->settings.set_was_edited();
         }
         return true;
     } else if( action == "FAV_SAVE_PRESET" ) {
         string_input_popup custom_preset_popup;
         custom_preset_popup
         .title( _( "Enter a preset name:" ) )
         .width( 25 );
         if( selected_pocket->settings.get_preset_name().has_value() ) {
             custom_preset_popup.text( selected_pocket->settings.get_preset_name().value() );
         }
         custom_preset_popup.query_string();
         if( !custom_preset_popup.canceled() ) {
             const std::string &rval = custom_preset_popup.text();
             // Check if already exists
             item_pocket::load_presets();
             if( item_pocket::has_preset( rval ) ) {
                 if( query_yn( _( "Preset already exists, overwrite?" ) ) ) {
                     item_pocket::delete_preset( item_pocket::find_preset( rval ) );
                     selected_pocket->settings.set_preset_name( rval );
                     item_pocket::add_preset( selected_pocket->settings );
                 }
             } else {
                 selected_pocket->settings.set_preset_name( rval );
                 item_pocket::add_preset( selected_pocket->settings );
             }
         }
         return true;
     } else if( action == "FAV_APPLY_PRESET" ) {
         item_pocket::load_presets();
         uilist selector_menu;
         selector_menu.title = _( "Select a preset" );
         for( const item_pocket::favorite_settings &preset : item_pocket::pocket_presets ) {
             selector_menu.addentry( preset.get_preset_name().value() );
         }
         selector_menu.query();
         if( selector_menu.ret >= 0 ) {
             selected_pocket->settings = item_pocket::pocket_presets[selector_menu.ret];
         }
         return true;
     } else if( action == "FAV_DEL_PRESET" ) {
         item_pocket::load_presets();
         uilist selector_menu;
         for( const item_pocket::favorite_settings &preset : item_pocket::pocket_presets ) {
             selector_menu.addentry( preset.get_preset_name().value() );
         }
         selector_menu.query();
         if( selector_menu.ret >= 0 ) {
             if( query_yn( _( "Are you sure you wish to delete preset %s?" ),
                           item_pocket::pocket_presets[selector_menu.ret].get_preset_name().value() ) ) {
                 item_pocket::delete_preset( item_pocket::pocket_presets.begin() + selector_menu.ret );
             }
         }
         return true;
     } else if( action == "FAV_CLEAR" ) {
         if( query_yn( _( "Are you sure you want to clear settings for pocket %d?" ), pocket_num ) ) {
             selected_pocket->settings.clear();
             selected_pocket->settings.set_was_edited();
         }
         return true;
     } else if( action == "FAV_CONTEXT_MENU" ) {
         uilist cmenu( _( "Action to take on this pocket" ), {} );
         cmenu.addentry( 0, true, inp_mngr.get_first_char_for_action( "FAV_MOVE_ITEM", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_MOVE_ITEM" ) );
         cmenu.addentry( 1, true, inp_mngr.get_first_char_for_action( "FAV_ITEM", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_ITEM" ) );
         cmenu.addentry( 2, true, inp_mngr.get_first_char_for_action( "FAV_CATEGORY", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_CATEGORY" ) );
         cmenu.addentry( 3, true, inp_mngr.get_first_char_for_action( "FAV_WHITELIST", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_WHITELIST" ) );
         cmenu.addentry( 4, true, inp_mngr.get_first_char_for_action( "FAV_BLACKLIST", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_BLACKLIST" ) );
         cmenu.addentry( 5, true, inp_mngr.get_first_char_for_action( "FAV_PRIORITY", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_PRIORITY" ) );
         cmenu.addentry( 6, true, inp_mngr.get_first_char_for_action( "FAV_AUTO_PICKUP", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_AUTO_PICKUP" ) );
         cmenu.addentry( 7, true, inp_mngr.get_first_char_for_action( "FAV_AUTO_UNLOAD", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_AUTO_UNLOAD" ) );
         cmenu.addentry( 8, true, inp_mngr.get_first_char_for_action( "FAV_SAVE_PRESET", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_SAVE_PRESET" ) );
         cmenu.addentry( 9, true, inp_mngr.get_first_char_for_action( "FAV_APPLY_PRESET", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_APPLY_PRESET" ) );
         cmenu.addentry( 10, true, inp_mngr.get_first_char_for_action( "FAV_DEL_PRESET", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_DEL_PRESET" ) );
         cmenu.addentry( 11, true, inp_mngr.get_first_char_for_action( "FAV_CLEAR", "INVENTORY" ),
                         ctxt.get_action_name( "FAV_CLEAR" ) );
         cmenu.query();
         std::string ev;
         switch( cmenu.ret ) {
             case 0:
                 ev = "FAV_MOVE_ITEM";
                 break;
             case 1:
                 ev = "FAV_ITEM";
                 break;
             case 2:
                 ev = "FAV_CATEGORY";
                 break;
             case 3:
                 ev = "FAV_WHITELIST";
                 break;
             case 4:
                 ev = "FAV_BLACKLIST";
                 break;
             case 5:
                 ev = "FAV_PRIORITY";
                 break;
             case 6:
                 ev = "FAV_AUTO_PICKUP";
                 break;
             case 7:
                 ev = "FAV_AUTO_UNLOAD";
                 break;
             case 8:
                 ev = "FAV_SAVE_PRESET";
                 break;
             case 9:
                 ev = "FAV_APPLY_PRESET";
                 break;
             case 10:
                 ev = "FAV_DEL_PRESET";
                 break;
             case 11:
                 ev = "FAV_CLEAR";
                 break;
             default:
                 break;
         }
         const std::vector<input_event> evlist = inp_mngr.get_input_for_action( ev, "INVENTORY" );
         if( cmenu.ret >= 0 && cmenu.ret <= 11 && !evlist.empty() ) {
             return key( ctxt, evlist.front(), -1, menu );
         }
         return true;
     }
     return false;
 }
References _, action, uilist::addentry(), item_pocket::favorite_settings::blacklist_category(), item_pocket::favorite_settings::blacklist_item(), CONTAINER, cata::flat_set< T, Compare, Data >::count(), uilist::entries, item_category::get_all(), item_pocket::favorite_settings::get_category_blacklist(), item_pocket::favorite_settings::get_category_whitelist(), item_pocket::favorite_settings::get_item_blacklist(), item_pocket::favorite_settings::get_item_whitelist(), get_player_character(), item_pocket::get_pocket_data(), base_camps::id, input_context::input_to_action(), cata::flat_set< T, Compare, Data >::insert(), item_pocket::is_compatible(), item_pocket::favorite_settings::is_disabled(), string_id< T >::is_null(), item_pocket::is_type(), item_pocket::favorite_settings::is_unloadable(), localized_compare, move_item(), item_category::name_header(), PATH_INFO::names(), string_id< itype >::NULL_ID(), PF_GET_KEY, popup(), prefix, item_pocket::favorite_settings::priority(), uilist::query(), cata::hash64_detail::ret, uilist::ret, saved_pockets, uilist::selected, item_pocket::favorite_settings::set_disabled(), item_pocket::favorite_settings::set_priority(), item_pocket::favorite_settings::set_unloadable(), item_pocket::favorite_settings::set_was_edited(), item_pocket::settings, string_format(), uilist::title, whitelist, item_pocket::favorite_settings::whitelist_category(), and item_pocket::favorite_settings::whitelist_item().
move_item()
void pocket_favorite_callback::move_item (uilist * menu, item_pocket * selected_pocket) private
Definition at line 183 of file item_contents.cpp.
 {
     uilist selector_menu;
     if( item_to_move.second == nullptr ) {
         selector_menu.title = _( "Select an item from the pocket" );
         std::vector<item *> item_list;
         for( item *it_in : selected_pocket->all_items_top() ) {
             item_list.emplace_back( it_in );
         }
         std::sort( item_list.begin(), item_list.end() );
         for( const item *it : item_list ) {
             selector_menu.addentry( it->display_name() );
         }
         if( selector_menu.entries.empty() ) {
             popup( std::string( _( "No items in the pocket." ) ), PF_GET_KEY );
         } else {
             selector_menu.query();
         }
         if( selected_pocket->get_pocket_data()->_no_unload ) {
             popup( std::string( _( "Can't unload that." ) ), PF_GET_KEY );
             // These make sure we exit back to the top level of the menu regardless of how the function was called.
             selector_menu.ret = -1;
             item_to_move = { nullptr, nullptr };
             refresh_columns( menu );
         }
         if( selector_menu.ret >= 0 ) {
             item_to_move = { item_list[selector_menu.ret], selected_pocket };
         }
         if( item_to_move.first != nullptr ) {
             menu->settext( string_format( "%s: %s", _( "Moving" ), item_to_move.first->display_name() ) );
             refresh_columns( menu );
             // if we have an item already selected for moving update some info
             auto itt = saved_pockets.begin();
             for( uilist_entry &entry : menu->entries ) {
                 if( entry.enabled && !std::get<0>( *itt )->can_contain( *item_to_move.first ).success() ) {
                     entry.enabled = false;
                 }
                 // make sure we dont try to put anything in itself
                 if( entry.enabled ) {
                     for( item_pocket *pocket : item_to_move.first->get_all_standard_pockets() ) {
                         if( std::get<0>( *itt ) == pocket ) {
                             entry.enabled = false;
                         }
                     }
                 }
                 // move through the pockets as you process entries
                 ++itt;
             }
         }
     } else {
         // If no pockets are enabled, uilist allows scrolling through them, so we need to recheck
         ret_val<item_pocket::contain_code> contain = selected_pocket->can_contain( *item_to_move.first );
         bool cant_reload = false;
         std::string reload_fail;
         if( selected_pocket->get_pocket_data()->_no_reload ) {
             cant_reload = true;
             reload_fail = _( "destination container can't be reloaded." );
         }
         if( contain.success() && !cant_reload ) {
             // storage should mimick character inserting
             get_avatar().as_character()->store( selected_pocket, *item_to_move.first );
         } else {
             const std::string base_string = _( "Cannot put item in pocket because %s" );
             popup( string_format( base_string, cant_reload ? reload_fail : contain.str() ) );
         }
         // reset the moved item
         item_to_move = { nullptr, nullptr };
         menu->settext( uilist_text );
         refresh_columns( menu );
     }
 }
References _, pocket_data::_no_reload, pocket_data::_no_unload, uilist::addentry(), item_pocket::all_items_top(), Character::as_character(), item_pocket::can_contain(), uilist_entry::enabled, uilist::entries, get_avatar(), item_pocket::get_pocket_data(), item_to_move, PF_GET_KEY, popup(), uilist::query(), refresh_columns(), uilist::ret, saved_pockets, uilist::settext(), Character::store(), ret_val_common::str(), string_format(), ret_val_common::success(), uilist::title, and uilist_text.
Referenced by key().
refresh()
void pocket_favorite_callback::refresh (uilist * menu) override virtual
Reimplemented from uilist_callback.
Definition at line 68 of file item_contents.cpp.
 {
     if( needs_to_refresh ) {
         refresh_columns( menu );
         needs_to_refresh = false;
     }
     item_pocket *selected_pocket = nullptr;
     int i = 0;
     int pocket_num = 0;
     for( std::tuple<item_pocket *, int, uilist_entry *> &pocket_val : saved_pockets ) {
         item_pocket *pocket = std::get<0>( pocket_val );
         if( pocket == nullptr || ( pocket->get_pocket_data()  &&
                                    !pocket->is_type( pocket_type::CONTAINER ) ) ) {
             ++i;
             continue;
         }
         if( i == menu->selected ) {
             selected_pocket = pocket;
             pocket_num = std::get<1>( pocket_val ) + 1;
             break;
         }
         ++i;
     }
     if( selected_pocket != nullptr && !selected_pocket->is_forbidden() ) {
         std::vector<iteminfo> info;
         int starty = 5;
         const int startx = menu->w_width - menu->pad_right;
         const int width = menu->pad_right - 1;
         fold_and_print( menu->window, point( 2, 2 ), width,
                         c_light_gray, string_format( _( "Currently modifying %s" ),
                                 colorize( whitelist ? _( "whitelist" ) : _( "blacklist" ), c_light_blue ) ) );
         selected_pocket->general_info( info, pocket_num, true );
         starty += fold_and_print( menu->window, point( startx, starty ), width,
                                   c_light_gray, format_item_info( info, {} ) ) + 1;
         info.clear();
         selected_pocket->favorite_info( info );
         starty += fold_and_print( menu->window, point( startx, starty ), width,
                                   c_light_gray, format_item_info( info, {} ) ) + 1;
         info.clear();
         selected_pocket->contents_info( info, pocket_num, true );
         fold_and_print( menu->window, point( startx, starty ), width,
                         c_light_gray, format_item_info( info, {} ) );
     }
     wnoutrefresh( menu->window );
 }
References _, c_light_blue, c_light_gray, colorize(), CONTAINER, item_pocket::contents_info(), item_pocket::favorite_info(), fold_and_print(), format_item_info(), item_pocket::general_info(), item_pocket::get_pocket_data(), item_pocket::is_forbidden(), item_pocket::is_type(), needs_to_refresh, uilist::pad_right, refresh_columns(), saved_pockets, uilist::selected, string_format(), uilist::w_width, whitelist, uilist::window, and catacurses::wnoutrefresh().
refresh_columns()
void pocket_favorite_callback::refresh_columns (uilist * menu) private
Definition at line 170 of file item_contents.cpp.
 {
     // rebuild the list of rows can't fully clear or the menu will close
     // clear all but one entry repopulate then delete that initial
     menu->entries.clear();
     saved_pockets.clear();
     for( item *i : to_organize ) {
         add_pockets( *i, *menu, "" );
     }
     // there might be a better way to refresh this
     menu->setup();
 }
References add_pockets(), uilist::entries, saved_pockets, uilist::setup(), and to_organize.
Referenced by move_item(), and refresh().
Member Data Documentation
item_to_move
std::pair<item *, item_pocket *> pocket_favorite_callback::item_to_move = { nullptr, nullptr } private
Definition at line 46 of file item_contents.cpp.
Referenced by move_item().
needs_to_refresh
bool pocket_favorite_callback::needs_to_refresh = false private
Definition at line 48 of file item_contents.cpp.
Referenced by refresh().
saved_pockets
std::vector<std::tuple<item_pocket *, int, uilist_entry *> > pocket_favorite_callback::saved_pockets private
Definition at line 43 of file item_contents.cpp.
Referenced by add_pockets(), key(), move_item(), refresh(), and refresh_columns().
to_organize
std::vector<item *> pocket_favorite_callback::to_organize private
Definition at line 53 of file item_contents.cpp.
Referenced by add_pockets(), pocket_favorite_callback(), and refresh_columns().
uilist_text
std::string pocket_favorite_callback::uilist_text private
Definition at line 50 of file item_contents.cpp.
Referenced by move_item().
whitelist
bool pocket_favorite_callback::whitelist = true private
Definition at line 45 of file item_contents.cpp.
Referenced by key(), and refresh().
The documentation for this class was generated from the following file:
src/item_contents.cpp