Cataclysm DDA: Json Class Reference
Json Class Reference
#include <flexbuffer_json.h>
Public Types
using flexbuffer = flexbuffers::Reference
Public Member Functions
Json ()=delete
std::string str () const
void throw_error (const JsonPath &path, int offset, const std::string &message) const
void throw_error_after (const JsonPath &path, const std::string &message) const
void string_error (const JsonPath &path, int offset, const std::string &message) const
Static Public Member Functions
static const std::string & flexbuffer_type_to_string (flexbuffers::Type t)
static bool globally_report_unvisited_members (bool do_report)
Protected Member Functions
Json (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json)
~Json () noexcept=default
Json (const Json &)=default
Json & operator= (const Json &)=default
Json (Json &&) noexcept=default
Json & operator= (Json &&) noexcept=default
Protected Attributes
std::shared_ptr< parsed_flexbuffer > root_
flexbuffer json_
Detailed Description
Definition at line 90 of file flexbuffer_json.h.
Member Typedef Documentation
flexbuffer
using Json::flexbuffer = flexbuffers::Reference
Definition at line 94 of file flexbuffer_json.h.
Constructor & Destructor Documentation
Json() [1/4]
Json::Json () delete
Json() [2/4]
Json::Json (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json) inline protected
Definition at line 108 of file flexbuffer_json.h.
                                                                        : root_{ std::move( root ) },
             json_ { json } {}
~Json()
Json::~Json () protected default noexcept
Json() [3/4]
Json::Json (const Json &) protected default
Json() [4/4]
Json::Json (Json &&) protected default noexcept
Member Function Documentation
flexbuffer_type_to_string()
const std::string & Json::flexbuffer_type_to_string (flexbuffers::Type t) static
Definition at line 22 of file flexbuffer_json.cpp.
 {
     static const std::array<std::string, 36> type_map = { {
             "null",
             "int",
             "uint",
             "float",
             "key",
             "string",
             "indirect_int",
             "indirect_uint",
             "indirect_float",
             "object",
             "array",
             "int_array",
             "uint_array",
             "float_array",
             "key_array",
             "string_array_deprecated",
             "int_tuple_array",
             "uint_tuple_array",
             "float_tuple_array",
             "int_triple_array",
             "uint_triple_array",
             "float_triple_array",
             "int_quad_array",
             "uint_quad_array",
             "float_quad_array",
             "blob",
             "bool",
             "bool_array",
         }
     };
     return type_map[static_cast<unsigned int>( t )];
 }
globally_report_unvisited_members()
bool Json::globally_report_unvisited_members (bool do_report) static
Definition at line 17 of file flexbuffer_json.cpp.
 {
     return report_unvisited_members.exchange( do_report );
 }
References anonymous_namespace{flexbuffer_json.cpp}::report_unvisited_members.
Referenced by main().
operator=() [1/2]
Json& Json::operator= (const Json &) protected default
operator=() [2/2]
Json& Json::operator= (Json &&) protected default noexcept
str()
std::string Json::str () const
Definition at line 136 of file flexbuffer_json.cpp.
 {
     std::string ret;
     json_.ToString( false, true, ret );
     return ret;
 }
References json_, and cata::hash64_detail::ret.
Referenced by mtype::load(), recipe::load(), and vpart_info::load().
string_error()
void Json::string_error (const JsonPath & path, int offset, const std::string & message) const
Definition at line 119 of file flexbuffer_json.cpp.
 {
     std::unique_ptr<std::istream> original_json = root_->get_source_stream();
     std::string source_path = [&] {
         if( root_->get_source_path().empty() )
         {
             return std::string{ "<unknown source file>" };
         }
         return root_->get_source_path().u8string();
     }();
     TextJsonIn jsin( *original_json, source_path );
     advance_jsin( &jsin, flexbuffer_root_from_storage( root_->get_storage() ), path );
     jsin.string_error( offset, message );
 }
References advance_jsin(), flexbuffer_root_from_storage(), mapgen_defer::message, root_, and TextJsonIn::string_error().
Referenced by JsonValue::string_error().
throw_error()
void Json::throw_error (const JsonPath & path, int offset, const std::string & message) const
Definition at line 84 of file flexbuffer_json.cpp.
 {
     std::unique_ptr<std::istream> original_json = root_->get_source_stream();
     std::string source_path = [&] {
         if( root_->get_source_path().empty() )
         {
             return std::string{ "<unknown source file>" };
         }
         return root_->get_source_path().u8string();
     }();
     TextJsonIn jsin( *original_json, source_path );
     advance_jsin( &jsin, flexbuffer_root_from_storage( root_->get_storage() ), path );
     jsin.error( offset, message );
 }
References root_.
Referenced by JsonWithPath::error_or_false(), JsonValue::error_or_false(), JsonObject::throw_error(), JsonWithPath::throw_error(), and JsonValue::throw_error().
throw_error_after()
void Json::throw_error_after (const JsonPath & path, const std::string & message) const
Definition at line 101 of file flexbuffer_json.cpp.
 {
     std::unique_ptr<std::istream> original_json = root_->get_source_stream();
     std::string source_path = [&] {
         if( root_->get_source_path().empty() )
         {
             return std::string{ "<unknown source file>" };
         }
         return root_->get_source_path().u8string();
     }();
     TextJsonIn jsin( *original_json, source_path );
     advance_jsin( &jsin, flexbuffer_root_from_storage( root_->get_storage() ), path );
     jsin.skip_value();
     jsin.error( message );
 }
References advance_jsin(), TextJsonIn::error(), flexbuffer_root_from_storage(), mapgen_defer::message, root_, and TextJsonIn::skip_value().
Referenced by JsonWithPath::throw_error_after(), and JsonValue::throw_error_after().
Member Data Documentation
json_
flexbuffer Json::json_ protected
Definition at line 122 of file flexbuffer_json.h.
Referenced by JsonArray::JsonArray(), JsonObject::JsonObject(), JsonArray::operator=(), JsonObject::operator=(), JsonArray::operator[](), str(), JsonValue::test_array(), JsonValue::test_bool(), JsonValue::test_float(), JsonValue::test_int(), JsonValue::test_null(), JsonValue::test_number(), JsonValue::test_object(), and JsonValue::test_string().
root_
std::shared_ptr<parsed_flexbuffer> Json::root_ protected
Definition at line 120 of file flexbuffer_json.h.
Referenced by JsonObject::error_no_member(), JsonObject::error_skipped_members(), JsonObject::get_member(), JsonObject::get_member_opt(), JsonArray::operator[](), JsonObject::operator[](), string_error(), throw_error(), and throw_error_after().
The documentation for this class was generated from the following files:
src/flexbuffer_json.h
src/flexbuffer_json.cpp