Cataclysm DDA: anonymous_namespace{iexamine.cpp}::atm_menu Class Reference
anonymous_namespace{iexamine.cpp}::atm_menu Class Reference
Implements iexamine::atm(...)
Public Types
enum options : int {
cancel , purchase_card , deposit_money , withdraw_money ,
exchange_cash , transfer_all_money
}
Public Member Functions
atm_menu ()=delete
atm_menu (atm_menu const &)=delete
atm_menu (atm_menu &&)=delete
atm_menu & operator= (atm_menu const &)=delete
atm_menu & operator= (atm_menu &&)=delete
atm_menu (Character &you)
void start ()
Private Member Functions
void add_choice (const int i, const char *const title)
void add_info (const int i, const char *const title)
options choose_option ()
void reset (const bool clear=true)
Reset and repopulate the menu; with a fair bit of work this could be more efficient.
void finish_interaction (const bool print=true)
print a bank statement for print = true;
bool do_purchase_card ()
Get a new cash card. $10.00 fine.
bool do_deposit_money ()
Deposit money from cash card into bank account.
bool do_withdraw_money ()
Move money from bank account onto cash card.
bool do_exchange_cash ()
Deposit pre-Cataclysm currency and receive equivalent amount minus fees on a card.
bool do_transfer_all_money ()
Move the money from all the cash cards in inventory to a single card.
Static Private Member Functions
static int prompt_for_amount (const char *const msg, const int max)
Prompt for an integral value clamped to [0, max].
Private Attributes
Character & you
uilist amenu
Detailed Description
Implements iexamine::atm(...)
Definition at line 675 of file iexamine.cpp.
Member Enumeration Documentation
options
enum anonymous_namespace{iexamine.cpp}::atm_menu::options : int
Enumerator
cancel
purchase_card
deposit_money
withdraw_money
exchange_cash
transfer_all_money
Definition at line 679 of file iexamine.cpp.
                      : int {
             cancel, purchase_card, deposit_money, withdraw_money, exchange_cash, transfer_all_money
         };
Constructor & Destructor Documentation
atm_menu() [1/4]
anonymous_namespace{iexamine.cpp}::atm_menu::atm_menu () delete
atm_menu() [2/4]
anonymous_namespace{iexamine.cpp}::atm_menu::atm_menu (atm_menu const &) delete
atm_menu() [3/4]
anonymous_namespace{iexamine.cpp}::atm_menu::atm_menu (atm_menu &&) delete
atm_menu() [4/4]
anonymous_namespace{iexamine.cpp}::atm_menu::atm_menu (Character & you) inline explicit
Definition at line 689 of file iexamine.cpp.
                                             : you( you ) {
             reset( false );
         }
References reset.
Member Function Documentation
add_choice()
void anonymous_namespace{iexamine.cpp}::atm_menu::add_choice (const int i, const char *const title) inline private
Definition at line 720 of file iexamine.cpp.
{
             amenu.addentry( i, true, -1, title );
         }
References music::title.
add_info()
void anonymous_namespace{iexamine.cpp}::atm_menu::add_info (const int i, const char *const title) inline private
Definition at line 723 of file iexamine.cpp.
{
             amenu.addentry( i, false, -1, title );
         }
References music::title.
choose_option()
options anonymous_namespace{iexamine.cpp}::atm_menu::choose_option () inline private
Definition at line 727 of file iexamine.cpp.
{
             if( you.activity.id() == ACT_ATM ) {
                 return static_cast<options>( you.activity.index );
             }
             amenu.query();
             uistate.iexamine_atm_selected = amenu.selected;
             return amenu.ret < 0 ? cancel : static_cast<options>( amenu.ret );
         }
References ACT_ATM, cancel, uistatedata::iexamine_atm_selected, and uistate.
do_deposit_money()
bool anonymous_namespace{iexamine.cpp}::atm_menu::do_deposit_money () inline private
Deposit money from cash card into bank account.
Definition at line 830 of file iexamine.cpp.
{
             int money = you.charges_of( itype_cash_card );
             if( !money ) {
                 popup( _( "You can only deposit money from charged cash cards!" ) );
                 return false;
             }
             const int amount = prompt_for_amount( n_gettext(
                     "Deposit how much?  Max: %d cent.  (0 to cancel) ",
                     "Deposit how much?  Max: %d cents.  (0 to cancel) ", money ), money );
             if( !amount ) {
                 return false;
             }
             add_msg( m_info, _( "You deposit %s into your account." ), format_money( amount ) );
             you.use_charges( itype_cash_card, amount );
             you.cash += amount;
             you.mod_moves( -to_moves<int>( 10_seconds ) );
             finish_interaction();
             return true;
         }
References _, add_msg(), format_money(), itype_cash_card, m_info, n_gettext, popup(), and prompt_for_amount().
do_exchange_cash()
bool anonymous_namespace{iexamine.cpp}::atm_menu::do_exchange_cash () inline private
Deposit pre-Cataclysm currency and receive equivalent amount minus fees on a card.
Definition at line 908 of file iexamine.cpp.
{
             item *dst;
             if( you.activity.id() == ACT_ATM ) {
                 dst = you.activity.targets.front().get_item();
                 you.activity.set_to_null();
                 if( dst->is_null() || dst->typeId() != itype_cash_card ) {
                     debugmsg( "do_exchange_cash lost the destination card" );
                     return false;
                 }
             } else {
                 const std::vector<item *> cash_cards = you.cache_get_items_with( "is_cash_card",
                                                        &item::is_cash_card );
                 if( cash_cards.empty() ) {
                     popup( _( "You do not have a cash card." ) );
                     return false;
                 }
                 dst = *std::max_element( cash_cards.begin(), cash_cards.end(), []( const item * a,
                 const item * b ) {
                     return a->ammo_remaining() < b->ammo_remaining();
                 } );
                 if( !query_yn( _( "Exchange all paper bills and coins in inventory?" ) ) ) {
                     return false;
                 }
             }
             item *cash_item = nullptr;
             you.visit_items( [&]( item * e, const item * ) {
                 if( e->type->has_flag( flag_OLD_CURRENCY ) ) {
                     cash_item = e;
                     return VisitResponse::ABORT;
                 }
                 return VisitResponse::NEXT;
             } );
             if( !cash_item ) {
                 return false;
             }
             // Feeding a bill into the machine takes at least one turn
             you.mod_moves( -std::max( 100, you.get_moves() ) );
             int value = units::to_cent( cash_item->type->price );
             value *= 0.99;  // subtract fee
             if( value > dst->ammo_capacity( ammo_money ) - dst->ammo_remaining() ) {
                 popup( _( "Destination card is full." ) );
                 return false;
             }
             if( cash_item->charges > 1 ) {
                 cash_item->charges--;
             } else {
                 item_location( you, cash_item ).remove_item();
             }
             dst->ammo_set( dst->ammo_default(), dst->ammo_remaining() + value );
             you.assign_activity( ACT_ATM, 0, exchange_cash );
             you.activity.targets.emplace_back( you, dst );
             return true;
         }
References _, a, ACT_ATM, item::ammo_capacity(), item::ammo_default(), ammo_money, item::ammo_remaining(), item::ammo_set(), b, item::charges, debugmsg, flag_OLD_CURRENCY, itype::has_flag(), item::is_cash_card(), item::is_null(), itype_cash_card, max(), NEXT, popup(), itype::price, query_yn(), item_location::remove_item(), units::to_cent(), item::type, item::typeId(), and item::visit_items().
do_purchase_card()
bool anonymous_namespace{iexamine.cpp}::atm_menu::do_purchase_card () inline private
Get a new cash card. $10.00 fine.
Definition at line 811 of file iexamine.cpp.
{
             const char *prompt =
                 _( "This will automatically deduct $10.00 from your bank account.  Continue?" );
             if( !query_yn( prompt ) ) {
                 return false;
             }
             item card( "cash_card", calendar::turn );
             card.ammo_set( card.ammo_default(), 0 );
             you.i_add( card );
             you.cash -= 1000;
             you.mod_moves( -to_moves<int>( 5_seconds ) );
             finish_interaction();
             return true;
         }
References _, item::ammo_default(), item::ammo_set(), Pickup::prompt, query_yn(), and calendar::turn.
do_transfer_all_money()
bool anonymous_namespace{iexamine.cpp}::atm_menu::do_transfer_all_money () inline private
Move the money from all the cash cards in inventory to a single card.
Definition at line 964 of file iexamine.cpp.
{
             item *dst;
             std::vector<item *> cash_cards_on_hand = you.cache_get_items_with( "is_cash_card",
                     &item::is_cash_card );
             if( you.activity.id() == ACT_ATM ) {
                 dst = you.activity.targets.front().get_item();
                 you.activity.set_to_null(); // stop for now, if required, it will be created again.
                 if( dst->is_null() || dst->typeId() != itype_cash_card ) {
                     debugmsg( "do_transfer_all_money lost the destination card" );
                     return false;
                 }
             } else {
                 if( cash_cards_on_hand.empty() ) {
                     return false;
                 }
                 dst = *cash_cards_on_hand.begin();
             }
             for( item *i : cash_cards_on_hand ) {
                 if( i == dst || i->ammo_remaining() <= 0 || i->typeId() != itype_cash_card ) {
                     continue;
                 }
                 if( you.get_moves() < 0 ) {
                     // Money from `*i` could be transferred, but we're out of moves, schedule it for
                     // the next turn. Putting this here makes sure there will be something to be
                     // done next turn.
                     you.assign_activity( ACT_ATM, 0, transfer_all_money );
                     you.activity.targets.emplace_back( you, dst );
                     break;
                 }
                 // should we check for max capacity here?
                 if( i->ammo_remaining() > dst->ammo_capacity( ammo_money ) - dst->ammo_remaining() ) {
                     popup( _( "Destination card is full." ) );
                     return false;
                 }
                 dst->ammo_set( dst->ammo_default(), i->ammo_remaining() + dst->ammo_remaining() );
                 i->ammo_set( i->ammo_default(), 0 );
                 you.mod_moves( -to_moves<int>( 1_seconds ) * 0.1 );
             }
             return true;
         }
References _, ACT_ATM, item::ammo_capacity(), item::ammo_default(), ammo_money, item::ammo_remaining(), item::ammo_set(), debugmsg, item::is_cash_card(), item::is_null(), itype_cash_card, popup(), and item::typeId().
do_withdraw_money()
bool anonymous_namespace{iexamine.cpp}::atm_menu::do_withdraw_money () inline private
Move money from bank account onto cash card.
Definition at line 856 of file iexamine.cpp.
{
             std::vector<item *> cash_cards_on_hand = you.cache_get_items_with( "is_cash_card",
                     &item::is_cash_card );
             if( cash_cards_on_hand.empty() ) {
                 //Just in case we run into an edge case
                 popup( _( "You do not have a cash card to withdraw money!" ) );
                 return false;
             }
             const int amount = prompt_for_amount( n_gettext(
                     "Withdraw how much?  Max: %d cent.  (0 to cancel) ",
                     "Withdraw how much?  Max: %d cents.  (0 to cancel) ", you.cash ), you.cash );
             if( !amount ) {
                 return false;
             }
             int inserted = 0;
             int remaining = amount;
             std::sort( cash_cards_on_hand.begin(), cash_cards_on_hand.end(), []( item * one, item * two ) {
                 int balance_one = one->ammo_remaining();
                 int balance_two = two->ammo_remaining();
                 return balance_one > balance_two;
             } );
             for( item * const &cc : cash_cards_on_hand ) {
                 if( inserted == amount ) {
                     break;
                 }
                 int max_cap = cc->ammo_capacity( ammo_money ) - cc->ammo_remaining();
                 int to_insert = std::min( max_cap, remaining );
                 // insert whatever there's room for + the old balance.
                 cc->ammo_set( cc->ammo_default(), to_insert + cc->ammo_remaining() );
                 inserted += to_insert;
                 remaining -= to_insert;
             }
             if( remaining ) {
                 add_msg( m_info, _( "All cash cards at maximum capacity." ) );
             }
             //dst->charges += amount;
             you.cash -= amount - remaining;
             you.mod_moves( -to_moves<int>( 10_seconds ) );
             finish_interaction();
             return true;
         }
References _, add_msg(), ammo_money, item::is_cash_card(), m_info, min(), n_gettext, popup(), and prompt_for_amount().
finish_interaction()
void anonymous_namespace{iexamine.cpp}::atm_menu::finish_interaction (const bool print = true) inline private
print a bank statement for print = true;
Definition at line 785 of file iexamine.cpp.
{
             if( print ) {
                 if( you.cash < 0 ) {
                     add_msg( m_info, _( "Your debt is now %s." ), format_money( you.cash ) );
                 } else {
                     add_msg( m_info, _( "Your account now holds %s." ), format_money( you.cash ) );
                 }
             }
             you.mod_moves( -to_moves<int>( 5_seconds ) );
         }
References _, add_msg(), format_money(), and m_info.
operator=() [1/2]
atm_menu& anonymous_namespace{iexamine.cpp}::atm_menu::operator= (atm_menu &&) delete
operator=() [2/2]
atm_menu& anonymous_namespace{iexamine.cpp}::atm_menu::operator= (atm_menu const &) delete
prompt_for_amount()
static int anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount (const char *const msg, const int max) inline static private
Prompt for an integral value clamped to [0, max].
Definition at line 798 of file iexamine.cpp.
{
             const std::string formatted = string_format( msg, max );
             const int amount = string_input_popup()
                                .title( formatted )
                                .width( 20 )
                                .text( std::to_string( max ) )
                                .only_digits( true )
                                .query_int();
             return clamp( amount, 0, max );
         }
References clamp(), max(), string_input_popup::only_digits(), string_input_popup::query_int(), string_format(), string_input_popup::text(), string_input_popup::title(), to_string(), and string_input_popup::width().
reset()
void anonymous_namespace{iexamine.cpp}::atm_menu::reset (const bool clear = true) inline private
Reset and repopulate the menu; with a fair bit of work this could be more efficient.
Definition at line 737 of file iexamine.cpp.
{
             const int card_count   = you.amount_of( itype_cash_card );
             const int charge_count = card_count ? you.charges_of( itype_cash_card ) : 0;
             if( clear ) {
                 amenu.reset();
             }
             amenu.selected = uistate.iexamine_atm_selected;
             amenu.text = string_format( _( "Welcome to the C.C.B.o.t.T. ATM.  What would you like to do?\n"
                                            "Your current balance is: %s" ),
                                         format_money( you.cash ) );
             if( you.cash >= 1000 ) {
                 add_choice( purchase_card, _( "Purchase cash card?" ) );
             } else {
                 add_info( purchase_card, _( "You need $10.00 in your account to purchase a card." ) );
             }
             if( card_count && you.cash > 0 ) {
                 add_choice( withdraw_money, _( "Withdraw Money" ) );
             } else if( you.cash > 0 ) {
                 add_info( withdraw_money, _( "You need a cash card before you can withdraw money!" ) );
             } else if( you.cash < 0 ) {
                 add_info( withdraw_money,
                           _( "You need to pay down your debt first!" ) );
             } else {
                 add_info( withdraw_money,
                           _( "You need money in your account before you can withdraw money!" ) );
             }
             if( charge_count ) {
                 add_choice( deposit_money, _( "Deposit Money" ) );
             } else {
                 add_info( deposit_money,
                           _( "You need a charged cash card before you can deposit money!" ) );
             }
             if( card_count >= 1 && you.cache_has_item_with( flag_OLD_CURRENCY ) ) {
                 add_choice( exchange_cash, _( "Exchange Cash for eCash (1%% fee)" ) );
             }
             if( card_count >= 2 && charge_count ) {
                 add_choice( transfer_all_money, _( "Transfer All Money" ) );
             }
         }
References _, clear, flag_OLD_CURRENCY, format_money(), uistatedata::iexamine_atm_selected, itype_cash_card, string_format(), and uistate.
start()
void anonymous_namespace{iexamine.cpp}::atm_menu::start () inline
Definition at line 693 of file iexamine.cpp.
                      {
             for( bool result = false; !result; ) {
                 switch( choose_option() ) {
                     case purchase_card:
                         result = do_purchase_card();
                         break;
                     case deposit_money:
                         result = do_deposit_money();
                         break;
                     case withdraw_money:
                         result = do_withdraw_money();
                         break;
                     case exchange_cash:
                         result = do_exchange_cash();
                         break;
                     case transfer_all_money:
                         result = do_transfer_all_money();
                         break;
                     default:
                         return;
                 }
                 if( !you.activity.is_null() ) {
                     break;
                 }
             }
         }
Member Data Documentation
amenu
uilist anonymous_namespace{iexamine.cpp}::atm_menu::amenu private
Definition at line 1009 of file iexamine.cpp.
you
Character& anonymous_namespace{iexamine.cpp}::atm_menu::you private
Definition at line 1008 of file iexamine.cpp.
The documentation for this class was generated from the following file:
src/iexamine.cpp