Cataclysm DDA: bonus_container Class Reference
bonus_container Class Reference
#include <bonuses.h>
Public Member Functions
bonus_container ()
void load (const JsonObject &jo)
float get_flat (const Character &u, affected_stat stat, const damage_type_id &dt) const
float get_flat (const Character &u, affected_stat stat) const
float get_mult (const Character &u, affected_stat stat, const damage_type_id &dt) const
float get_mult (const Character &u, affected_stat stat) const
std::string get_description () const
Private Types
using bonus_map = std::map< affected_type, std::vector< effect_scaling > >
Private Member Functions
void load (const JsonArray &jarr, bool mult)
Private Attributes
bonus_map bonuses_flat
All kinds of bonuses by types to damage, hit etc.
bonus_map bonuses_mult
Detailed Description
Definition at line 89 of file bonuses.h.
Member Typedef Documentation
bonus_map
using bonus_container::bonus_map = std::map<affected_type, std::vector<effect_scaling> > private
Definition at line 106 of file bonuses.h.
Constructor & Destructor Documentation
bonus_container()
bonus_container::bonus_container () default
Member Function Documentation
get_description()
std::string bonus_container::get_description () const
Definition at line 266 of file bonuses.cpp.
 {
     std::string dump;
     for( const auto &boni : bonuses_mult ) {
         std::string type = string_from_affected_stat( boni.first.get_stat() );
         if( needs_damage_type( boni.first.get_stat() ) ) {
             const damage_type_id &dt = boni.first.get_damage_type();
             //~ %1$s: damage type, %2$s: damage-related bonus name
             type = string_format( pgettext( "type of damage", "%1$s %2$s" ),
                                   dt.is_null() ? _( "none" ) : dt->name.translated(), type );
         }
         for( const effect_scaling &sf : boni.second ) {
             if( sf.stat ) {
                 //~ %1$s: bonus name, %2$d: bonus percentage, %3$s: stat name
                 dump += string_format( pgettext( "martial art bonus", "* %1$s: <stat>%2$d%%</stat> of %3$s" ),
                                        type, static_cast<int>( sf.scale * 100 ), string_from_scaling_stat( sf.stat ) );
             } else {
                 //~ %1$s: bonus name, %2$d: bonus percentage
                 dump += string_format( pgettext( "martial art bonus", "* %1$s: <stat>%2$d%%</stat>" ),
                                        type, static_cast<int>( sf.scale * 100 ) );
             }
             dump += "\n";
         }
     }
     for( const auto &boni : bonuses_flat ) {
         std::string type = string_from_affected_stat( boni.first.get_stat() );
         if( needs_damage_type( boni.first.get_stat() ) ) {
             const damage_type_id &dt = boni.first.get_damage_type();
             //~ %1$s: damage type, %2$s: damage-related bonus name
             type = string_format( pgettext( "type of damage", "%1$s %2$s" ),
                                   dt.is_null() ? _( "none" ) : dt->name.translated(), type );
         }
         for( const effect_scaling &sf : boni.second ) {
             if( sf.stat ) {
                 //~ %1$s: bonus name, %2$+d: bonus percentage, %3$s: stat name
                 dump += string_format( pgettext( "martial art bonus", "* %1$s: <stat>%2$+d%%</stat> of %3$s" ),
                                        type, static_cast<int>( sf.scale * 100 ), string_from_scaling_stat( sf.stat ) );
             } else {
                 //~ %1$s: bonus name, %2$+d: bonus value
                 dump += string_format( pgettext( "martial art bonus", "* %1$s: <stat>%2$+d</stat>" ),
                                        type, static_cast<int>( sf.scale ) );
             }
             dump += "\n";
         }
     }
     return dump;
 }
References _, bonuses_flat, bonuses_mult, string_id< T >::is_null(), damage_type::name, needs_damage_type(), pgettext, effect_scaling::scale, effect_scaling::stat, string_format(), string_from_affected_stat(), string_from_scaling_stat(), translation::translated(), and type.
Referenced by ma_technique::get_description(), and ma_buff::get_description().
get_flat() [1/2]
float bonus_container::get_flat (const Character & u, affected_stat stat) const
Definition at line 239 of file bonuses.cpp.
 {
     return get_flat( u, stat, damage_type_id() );
 }
References get_flat(), and u.
get_flat() [2/2]
float bonus_container::get_flat (const Character & u, affected_stat stat, const damage_type_id & dt) const
Definition at line 223 of file bonuses.cpp.
 {
     const affected_type type( stat, dt );
     const auto &iter = bonuses_flat.find( type );
     if( iter == bonuses_flat.end() ) {
         return 0.0f;
     }
     float ret = 0.0f;
     for( const effect_scaling &es : iter->second ) {
         ret += es.get( u );
     }
     return ret;
 }
References bonuses_flat, effect_scaling::get(), cata::hash64_detail::ret, type, and u.
Referenced by ma_buff::armor_bonus(), ma_technique::armor_penetration(), ma_buff::arpen_bonus(), ma_buff::block_bonus(), ma_buff::block_effectiveness_bonus(), ma_buff::critical_hit_chance_bonus(), ma_buff::damage_bonus(), ma_technique::damage_bonus(), ma_buff::dodge_bonus(), get_flat(), ma_buff::hit_bonus(), ma_technique::move_cost_penalty(), and ma_buff::speed_bonus().
get_mult() [1/2]
float bonus_container::get_mult (const Character & u, affected_stat stat) const
Definition at line 261 of file bonuses.cpp.
 {
     return get_mult( u, stat, damage_type_id() );
 }
References get_mult(), and u.
get_mult() [2/2]
float bonus_container::get_mult (const Character & u, affected_stat stat, const damage_type_id & dt) const
Definition at line 244 of file bonuses.cpp.
 {
     const affected_type type( stat, dt );
     const auto &iter = bonuses_mult.find( type );
     if( iter == bonuses_mult.end() ) {
         return 1.0f;
     }
     float ret = 1.0f;
     for( const effect_scaling &es : iter->second ) {
         ret *= es.get( u );
     }
     // Currently all relevant effects require non-negative values
     return std::max( 0.0f, ret );
 }
References bonuses_mult, effect_scaling::get(), max(), cata::hash64_detail::ret, type, and u.
Referenced by ma_buff::damage_mult(), ma_technique::damage_multiplier(), get_mult(), and ma_technique::move_cost_multiplier().
load() [1/2]
void bonus_container::load (const JsonArray & jarr, bool mult) private
Definition at line 175 of file bonuses.cpp.
 {
     for( const JsonObject qualifiers : jarr ) {
         const affected_stat as = affected_stat_from_string( qualifiers.get_string( "stat" ) );
         if( as == affected_stat::NONE ) {
             qualifiers.throw_error_at( "stat", "Invalid affected stat" );
         }
         damage_type_id dt;
         if( needs_damage_type( as ) ) {
             qualifiers.read( "type", dt );
             if( dt == damage_type_id::NULL_ID() ) {
                 qualifiers.throw_error_at( "type", "Invalid damage type" );
             }
         }
         const affected_type at( as, dt );
         bonus_container::bonus_map &selected = mult ? bonuses_mult : bonuses_flat;
         selected[at].emplace_back( qualifiers );
     }
 }
References affected_stat_from_string(), bonuses_flat, bonuses_mult, needs_damage_type(), NONE, and string_id< damage_type >::NULL_ID().
load() [2/2]
void bonus_container::load (const JsonObject & jo)
Definition at line 169 of file bonuses.cpp.
 {
     load( jo.get_array( "flat_bonuses" ), false );
     load( jo.get_array( "mult_bonuses" ), true );
 }
References JsonObject::get_array().
Referenced by ma_technique::load(), and ma_buff::load().
Member Data Documentation
bonuses_flat
bonus_map bonus_container::bonuses_flat private
All kinds of bonuses by types to damage, hit etc.
Definition at line 108 of file bonuses.h.
Referenced by get_description(), get_flat(), and load().
bonuses_mult
bonus_map bonus_container::bonuses_mult private
Definition at line 109 of file bonuses.h.
Referenced by get_description(), get_mult(), and load().
The documentation for this class was generated from the following files:
src/bonuses.h
src/bonuses.cpp