Cataclysm DDA: vpart_info Class Reference
vpart_info Class Reference
#include <veh_type.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
void check () const
void finalize ()
void handle_inheritance (const vpart_info &copy_from, const std::unordered_map< std::string, vpart_info > &abstracts)
std::string name () const
Translated name of a part.
const std::set< std::string > & get_flags () const
bool has_flag (const std::string &flag) const
bool has_flag (const vpart_bitflags flag) const
void set_flag (const std::string &flag)
const std::set< std::string > & get_categories () const
Gets all categories of this part.
bool has_category (const std::string &category) const
Gets whether part is in a category for display.
int format_description (std::string &msg, const nc_color &format_color, int width) const
Format the description for display.
requirement_data install_requirements () const
Installation requirements for this component.
time_duration install_time (const Character &you) const
Installation time (in moves) for this component accounting for player skills.
requirement_data removal_requirements () const
Requirements for removal of this component.
time_duration removal_time (const Character &you) const
Removal time (in moves) for this component accounting for player skills.
requirement_data repair_requirements () const
Requirements for repair of this component (per level of damage)
bool is_repairable () const
Returns whether or not the part type is repairable.
time_duration repair_time (const Character &you) const
Repair time (in moves) to fully repair this component, accounting for player skills.
std::set< std::pair< itype_id, int > > get_pseudo_tools () const
std::vector< itype_id > get_folding_tools () const
std::vector< itype_id > get_unfolding_tools () const
time_duration get_folding_time () const
time_duration get_unfolding_time () const
bool has_control_req () const
Returns whether or not the vehicle this part installed requires something to control.
Public Attributes
vpart_id id
std::optional< vpslot_workbench > workbench_info
std::optional< vpslot_toolkit > toolkit_info
std::optional< vpslot_engine > engine_info
std::optional< vpslot_wheel > wheel_info
std::optional< vpslot_rotor > rotor_info
std::optional< vpslot_terrain_transform > transform_terrain_info
std::map< std::string, vpart_variant > variants
std::string variant_default
std::vector< std::pair< std::string, std::string > > variants_bases
std::map< skill_id, int > install_skills
Required skills to install, repair, or remove this component.
std::map< skill_id, int > repair_skills
std::map< skill_id, int > removal_skills
vp_control_req control_air
vp_control_req control_land
item_group_id breaks_into_group = item_group_id("EMPTY_GROUP")
item_group this part breaks into when destroyed
std::unordered_map< damage_type_id, float > damage_reduction = {}
Flat decrease of damage of a given type.
std::map< quality_id, int > qualities
Tool qualities this vehicle part can provide when installed.
std::set< emit_id > emissions
Emissions of part.
std::set< emit_id > exhaust
Exhaust emissions of part.
nc_color color = c_light_gray
Color of part for different states.
nc_color color_broken = c_light_gray
itype_id fuel_type = itype_id::NULL_ID()
Fuel type of engine or tank.
itype_id default_ammo = itype_id::NULL_ID()
Default ammo (for turrets)
std::optional< units::volume > folded_volume = std::nullopt
Volume of a foldable part when folded.
units::volume size = 0_ml
Cargo location volume.
std::string looks_like
hint to tilesets for what tile to use if this part doesn't have one
translation description
A text description of the part as a vehicle part.
itype_id base_item
base item for this part
std::optional< itype_id > removed_item
item it should be removed as
std::string location
What slot of the vehicle tile does this part occupy?
int durability = 0
Maximum damage part can sustain before being destroyed.
int dmg_mod = 100
Damage modifier (percentage) used when damaging other entities upon collision.
units::power epower = 0_W
Electrical power, flat rate energy (per second); positive for generation, negative for consumption For electric motor consumption scaled with powertrain demand see energy_consumption instead.
units::power energy_consumption = 0_W
Energy consumed per second by engines and motors when delivering max power Includes waste.
units::power power = 0_W
For engines and motors this is maximum output (watts) For alternators is engine power consumed (negative value)
time_duration install_moves = 1_hours
Installation for component (.
time_duration repair_moves = 1_hours
Repair time to fully repair a component (.
time_duration removal_moves = -1_seconds
Removal time for component (.
int bonus = 0
int cargo_weight_modifier = 100
cargo weight modifier (percentage)
int comfort = 0
units::temperature_delta floor_bedding_warmth = 0_C_delta
units::temperature_delta bonus_fire_warmth_feet = 0.6_C_delta
int z_order = 0
int list_order = 0
Private Attributes
std::set< std::string > flags
std::set< std::string > categories
std::bitset< NUM_VPFLAGS > bitflags
std::vector< std::pair< requirement_id, int > > install_reqs
Second field is the multiplier.
std::vector< std::pair< requirement_id, int > > removal_reqs
std::vector< std::pair< requirement_id, int > > repair_reqs
std::set< std::pair< itype_id, int > > pseudo_tools
Pseudo tools this provides when installed, second is the hotkey.
std::vector< itype_id > folding_tools
std::vector< itype_id > unfolding_tools
time_duration folding_time = 10_seconds
time_duration unfolding_time = 10_seconds
translation name_
Name from vehicle part definition which if set overrides the base item name.
bool was_loaded = false
std::vector< std::pair< vpart_id, mod_id > > src
Friends
class generic_factory< vpart_info >
struct mod_tracker
Detailed Description
Definition at line 239 of file veh_type.h.
Member Function Documentation
check()
void vpart_info::check () const
Definition at line 783 of file veh_type.cpp.
 {
     if( id.str().find( vehicles::variant_separator ) != std::string::npos ) {
         debugmsg( "vehicle part '%s' uses reserved character %c", id.str(), vehicles::variant_separator );
     }
     for( const auto&[vid, vv] : variants ) {
         for( size_t i = 0; i < vv.symbols.size(); i++ ) {
             if( ( mk_wcwidth( vv.symbols[i] ) != 1 ) ||
                 ( mk_wcwidth( vv.symbols_broken[i] ) != 1 ) ) {
                 debugmsg( "vehicle part '%s' variant '%s' has symbol that is not 1 console cell wide",
                           id.str(), vid );
             }
         }
     }
     for( const auto &[skill_id, skill_level] : install_skills ) {
         if( !skill_id.is_valid() ) {
             debugmsg( "vehicle part %s has unknown install skill %s", id.str(), skill_id.str() );
         }
     }
     for( const auto &[skill_id, skill_level] : removal_skills ) {
         if( !skill_id.is_valid() ) {
             debugmsg( "vehicle part %s has unknown removal skill %s", id.str(), skill_id.str() );
         }
     }
     for( const auto &[skill_id, skill_level] : repair_skills ) {
         if( !skill_id.is_valid() ) {
             debugmsg( "vehicle part %s has unknown repair skill %s", id.str(), skill_id.str() );
         }
     }
     for( const auto &[req_id, req_amount] : install_reqs ) {
         if( !req_id.is_valid() || req_amount <= 0 ) {
             debugmsg( "vehicle part %s has unknown or incorrectly specified install requirements %s",
                       id.str(), req_id.str() );
         }
     }
     for( const auto &[req_id, req_amount] : removal_reqs ) {
         if( !( req_id.is_null() || req_id.is_valid() ) || req_amount < 0 ) {
             debugmsg( "vehicle part %s has unknown or incorrectly specified removal requirements %s",
                       id.str(), req_id.str() );
         }
     }
     for( const auto &[req_id, req_amount] : repair_reqs ) {
         if( !( req_id.is_null() || req_id.is_valid() ) || req_amount < 0 ) {
             debugmsg( "vehicle part %s has unknown or incorrectly specified repair requirements %s",
                       id.str(), req_id.str() );
         }
     }
     if( install_moves < 0_seconds ) {
         debugmsg( "vehicle part %s has negative installation time", id.str() );
     }
     if( removal_moves < 0_seconds ) {
         debugmsg( "vehicle part %s has negative removal time", id.str() );
     }
     if( !item_group::group_is_defined( breaks_into_group ) ) {
         debugmsg( "Vehicle part %s breaks into non-existent item group %s.",
                   id.str(), breaks_into_group.str() );
     }
     for( const std::string &flag : get_flags() ) {
         if( !json_flag::get( flag ) ) {
             debugmsg( "vehicle part %s has unknown flag %s", id.str(), flag );
         }
     }
     if( durability <= 0 ) {
         debugmsg( "vehicle part %s has zero or negative durability", id.str() );
     }
     if( dmg_mod < 0 ) {
         debugmsg( "vehicle part %s has negative damage modifier", id.str() );
     }
     if( folded_volume && folded_volume.value() <= 0_ml ) {
         debugmsg( "vehicle part %s has folding part with zero or negative folded volume", id.str() );
     }
     if( !default_ammo.is_valid() ) {
         debugmsg( "vehicle part %s has undefined default ammo %s", id.str(), base_item.str() );
     }
     if( size != 0_ml ) {
         if( size < 0_ml ) {
             debugmsg( "vehicle part %s has negative size", id.str() );
         }
         if( !has_flag( "CARGO" ) ) {
             debugmsg( "vehicle part %s is not CARGO and cannot define size", id.str() );
         } else if( has_flag( "FLUIDTANK" ) ) {
             debugmsg( "vehicle part %s is FLUIDTANK and cannot define size; it's defined on part's base item",
                       id.str() );
         }
     }
     if( has_flag( "CARGO" ) && has_flag( "FLUIDTANK" ) ) {
         debugmsg( "vehicle part %s can't have both CARGO and FLUIDTANK flags at the same time", id.str() );
     }
     if( !item::type_is_defined( base_item ) ) {
         debugmsg( "vehicle part %s uses undefined item %s", id.str(), base_item.str() );
     }
     if( has_flag( "TURRET" ) && !base_item->gun ) {
         debugmsg( "vehicle part %s has the TURRET flag, but is not made from a gun item", id.str() );
     }
     for( const emit_id &e : emissions ) {
         if( !e.is_valid() ) {
             debugmsg( "vehicle part %s has invalid emission %s was set", id.str(), e.str() );
         }
     }
     for( const emit_id &e : exhaust ) {
         if( !e.is_valid() ) {
             debugmsg( "vehicle part %s has invalid exhaust %s was set", id.str(), e.str() );
         }
     }
     if( has_flag( "WHEEL" ) && !base_item->wheel ) {
         debugmsg( "vehicle part %s has the WHEEL flag, but base item %s is not a wheel.  "
                   "THIS WILL CRASH!", id.str(), base_item.str() );
     }
     if( has_flag( "WHEEL" ) && !has_flag( "UNSTABLE_WHEEL" ) && !has_flag( "STABLE" ) ) {
         debugmsg( "Wheel '%s' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.", id.str() );
     }
     if( has_flag( "UNSTABLE_WHEEL" ) && has_flag( "STABLE" ) ) {
         debugmsg( "Wheel '%s' cannot be both an 'UNSTABLE_WHEEL' and 'STABLE'.", id.str() );
     }
     for( const auto &[qual_id, qual_level] : qualities ) {
         if( !qual_id.is_valid() ) {
             debugmsg( "vehicle part %s has undefined tool quality %s", id.str(), qual_id.str() );
         }
     }
     if( has_flag( VPFLAG_ENABLED_DRAINS_EPOWER ) && epower == 0_W ) {
         debugmsg( "%s is set to drain epower, but has epower == 0", id.str() );
     }
     if( has_flag( VPFLAG_ENGINE ) ) {
         if( power != 0_W && fuel_type == fuel_type_animal ) {
             debugmsg( "engine part '%s' powered by '%s' can't define non-zero 'power'",
                       id.str(), fuel_type.str() );
         } else if( power == 0_W && fuel_type != fuel_type_animal ) {
             debugmsg( "engine part '%s' powered by '%s' must define non zero 'power'",
                       id.str(), fuel_type.str() );
         }
     }
     // Parts with non-zero epower must have a flag that affects epower usage
     static const std::vector<std::string> handled = {{
             "ENABLED_DRAINS_EPOWER", "SECURITY", "ENGINE",
             "ALTERNATOR", "SOLAR_PANEL", "POWER_TRANSFER",
             "REACTOR", "WIND_TURBINE", "WATER_WHEEL"
         }
     };
     if( epower != 0_W &&
     std::none_of( handled.begin(), handled.end(), [this]( const std::string & flag ) {
     return has_flag( flag );
     } ) ) {
         const std::string warnings_are_good_docs = enumerate_as_string( handled );
         debugmsg( "%s has non-zero epower, but lacks a flag that would make it affect epower (one of %s)",
                   id.str(), warnings_are_good_docs );
     }
     if( base_item->pockets.size() > 4 ) {
         debugmsg( "Error: vehicle parts assume only one pocket.  Multiple pockets unsupported" );
     }
     for( const auto &dt : damage_reduction ) {
         if( !dt.first.is_valid() ) {
             debugmsg( "Invalid damage_reduction type \"%s\" for vehicle part %s", dt.first.c_str(),
                       id.c_str() );
         }
     }
 }
References base_item, breaks_into_group, damage_reduction, debugmsg, default_ammo, dmg_mod, durability, emissions, enumerate_as_string(), epower, exhaust, folded_volume, fuel_type, fuel_type_animal, json_flag::get(), get_flags(), item_group::group_is_defined(), itype::gun, has_flag(), install_moves, install_reqs, install_skills, string_id< T >::is_valid(), mk_wcwidth(), itype::pockets, power, qualities, removal_moves, removal_reqs, removal_skills, repair_reqs, repair_skills, size, string_id< T >::str(), item::type_is_defined(), vehicles::variant_separator, variants, VPFLAG_ENABLED_DRAINS_EPOWER, VPFLAG_ENGINE, and itype::wheel.
finalize()
void vpart_info::finalize ()
Definition at line 633 of file veh_type.cpp.
 {
     if( engine_info && engine_info->fuel_opts.empty() && fuel_type != itype_null ) {
         engine_info->fuel_opts.push_back( fuel_type );
     }
     for( const std::string &flag : get_flags() ) {
         auto b = vpart_bitflag_map.find( flag );
         if( b != vpart_bitflag_map.end() ) {
             set_flag( flag ); // refresh bitflags field
         }
     }
     if( has_flag( VPFLAG_APPLIANCE ) ) {
         // force all appliances' location field to "structure"
         // dragging code currently checks this for considering collisions
         location = "structure";
     }
     finalize_damage_map( damage_reduction );
     // Calculate and cache z-ordering based off of location
     // list_order is used when inspecting the vehicle
     if( location == "on_roof" ) {
         z_order = 9;
         list_order = 3;
     } else if( location == "on_cargo" ) {
         z_order = 8;
         list_order = 6;
     } else if( location == "center" ) {
         z_order = 7;
         list_order = 7;
     } else if( location == "under" ) {
         // Have wheels show up over frames
         z_order = 6;
         list_order = 10;
     } else if( location == "structure" ) {
         z_order = 5;
         list_order = 1;
     } else if( location == "engine_block" ) {
         // Should be hidden by frames
         z_order = 4;
         list_order = 8;
     } else if( location == "on_battery_mount" ) {
         // Should be hidden by frames
         z_order = 3;
         list_order = 10;
     } else if( location == "fuel_source" ) {
         // Should be hidden by frames
         z_order = 3;
         list_order = 9;
     } else if( location == "roof" ) {
         // Shouldn't be displayed
         z_order = -1;
         list_order = 4;
     } else if( location == "armor" ) {
         // Shouldn't be displayed (the color is used, but not the symbol)
         z_order = -2;
         list_order = 2;
     } else {
         // Everything else
         z_order = 0;
         list_order = 5;
     }
     std::set<std::pair<itype_id, int>> &pt = pseudo_tools;
     for( auto it = pt.begin(); it != pt.end(); /* blank */ ) {
         const itype_id &tool = it->first;
         if( !tool.is_valid() ) {
             debugmsg( "invalid pseudo tool itype_id '%s' on '%s'", tool.str(), id.str() );
             pt.erase( it++ );
         } else {
             ++it;
         }
     }
     if( toolkit_info.has_value() ) {
         std::set<itype_id> &pt = toolkit_info->allowed_types;
         for( auto it = pt.begin(); it != pt.end(); /* blank */ ) {
             if( !it->is_valid() ) {
                 debugmsg( "invalid itype_id '%s' on 'allowed_tools' of vpart '%s'", it->str(), id.str() );
                 pt.erase( it++ );
             } else {
                 ++it;
             }
         }
     }
     // generate variant bases (cosmetic only feature for tilesets)
     std::vector<vpart_variant> new_variants;
     for( const auto &[base_id, base_label] : variants_bases ) {
         for( const auto &[vvid, vv] : variants ) {
             vpart_variant vv_copy = vv;
             vv_copy.id = vv_copy.id.empty() ? base_id : base_id + "_" + vv_copy.id;
             vv_copy.label_ = vv_copy.label_.empty() ? base_label : base_label + " " + vv_copy.label_;
             new_variants.emplace_back( vv_copy );
         }
     }
     for( const vpart_variant &vv : new_variants ) {
         variants[vv.id] = vv;
     }
     if( variants.empty() ) {
         debugmsg( "vehicle part %s defines no variants", id.str() );
         vpart_variant vv;
         vv.id.clear();
         vv.label_ = "Default";
         vv.symbols.fill( '?' );
         vv.symbols_broken.fill( '?' );
         variants.emplace( vv.id, vv );
         variant_default = vv.id;
     }
     if( variants.count( variant_default ) == 0 ) {
         variant_default = variants.begin()->first;
     }
     // add the base item to the installation requirements
     // TODO: support multiple/alternative base items
     requirement_data ins;
     ins.components.push_back( { { { base_item, 1 } } } );
     const requirement_id ins_id( std::string( "inline_vehins_base_" ) + id.str() );
     requirement_data::save_requirement( ins, ins_id );
     install_reqs.emplace_back( ins_id, 1 );
     if( removal_moves < 0_seconds ) {
         removal_moves = install_moves / 2;
     }
     if( !item::type_is_defined( fuel_type ) ) {
         debugmsg( "vehicle part %s uses undefined fuel %s", id.c_str(), base_item.c_str() );
         fuel_type = itype_id::NULL_ID();
     }
     if( !fuel_type.is_null() ) {
         const item base_item_as_container( base_item, calendar::turn_zero );
         const item fuel_containee( fuel_type, calendar::turn_zero );
         if( !fuel_containee.is_fuel() && !base_item_as_container.can_contain( fuel_containee ).success() ) {
             // HACK: Tanks are allowed to specify non-fuel "fuel",
             // because currently legacy blazemod uses it as a hack to restrict content types
             debugmsg( "non-tank vehicle part %s uses non-fuel item %s as fuel, setting to null",
                       id.c_str(), fuel_type.c_str() );
             fuel_type = itype_id::NULL_ID();
         }
     }
 }
References b, base_item, string_id< T >::c_str(), item::can_contain(), requirement_data::components, damage_reduction, debugmsg, engine_info, finalize_damage_map(), fuel_type, get_flags(), has_flag(), vpart_variant::id, install_moves, install_reqs, item::is_fuel(), string_id< T >::is_null(), string_id< T >::is_valid(), itype_null, vpart_variant::label_, list_order, location, string_id< itype >::NULL_ID(), pseudo_tools, removal_moves, requirement_data::save_requirement(), set_flag(), string_id< T >::str(), ret_val_common::success(), vpart_variant::symbols, vpart_variant::symbols_broken, toolkit_info, calendar::turn_zero, item::type_is_defined(), variant_default, variants, variants_bases, vpart_bitflag_map, VPFLAG_APPLIANCE, and z_order.
Referenced by vehicles::parts::finalize().
format_description()
int vpart_info::format_description (std::string & msg, const nc_color & format_color, int width) const
Format the description for display.
Definition at line 977 of file veh_type.cpp.
 {
     int lines = 1;
     msg += _( "<color_white>Description</color>\n" );
     msg += "> <color_" + string_from_color( format_color ) + ">";
     std::string long_descrip;
     // handle appending text and double-whitespace
     const auto append_desc = [&long_descrip]( const std::string & text ) {
         if( text.empty() ) {
             return;
         }
         if( !long_descrip.empty() ) {
             long_descrip += _( "  " );
         }
         long_descrip += text;
     };
     append_desc( description.translated() );
     for( const std::string &flagid : flags ) {
         if( flagid == "ALARMCLOCK" || flagid == "WATCH" ) {
             continue;
         } else if( flagid == "ENABLED_DRAINS_EPOWER" ||
                    flagid == "ENGINE" ) { // ENGINEs get the same description
             if( epower < 0_W ) {
                 append_desc( string_format( json_flag::get( "ENABLED_DRAINS_EPOWER" ).info(),
                                             -units::to_watt( epower ) ) );
             }
         } else if( flagid == "ALTERNATOR" ||
                    flagid == "SOLAR_PANEL" ||
                    flagid == "WATER_WHEEL" ||
                    flagid == "WIND_TURBINE" ) {
             append_desc( string_format( json_flag::get( flagid ).info(), units::to_watt( epower ) ) );
         } else {
             append_desc( json_flag::get( flagid ).info() );
         }
     }
     if( has_flag( "TURRET" ) ) {
         class::item base( base_item );
         if( base.ammo_required() && !base.ammo_remaining() ) {
             itype_id default_ammo = base.magazine_current() ? base.common_ammo_default() : base.ammo_default();
             if( !default_ammo.is_null() ) {
                 base.ammo_set( default_ammo );
             } else if( !base.magazine_default().is_null() ) {
                 class::item tmp_mag( base.magazine_default() );
                 tmp_mag.ammo_set( tmp_mag.ammo_default() );
                 base.put_in( tmp_mag, pocket_type::MAGAZINE_WELL );
             }
         }
         long_descrip += string_format( _( "\nRange: %1$5d     Damage: %2$5.0f" ),
                                        base.gun_range( true ),
                                        base.gun_damage().total_damage() );
     }
     if( !get_pseudo_tools().empty() ) {
         append_desc( string_format( "\n%s<color_cyan>%s</color>", _( "Provides: " ),
         enumerate_as_string( get_pseudo_tools(), []( const std::pair<itype_id, int> &p ) {
             return p.first.obj().nname( 1 );
         } ) ) );
     }
     if( toolkit_info && !toolkit_info->allowed_types.empty() ) {
         append_desc( string_format( "\n%s<color_cyan>%s</color>", _( "Allows connecting: " ),
         enumerate_as_string( toolkit_info->allowed_types, []( const itype_id & it ) {
             return it->nname( 1 );
         } ) ) );
     }
     if( !long_descrip.empty() ) {
         const auto wrap_descrip = foldstring( long_descrip, width );
         msg += wrap_descrip[0];
         for( size_t i = 1; i < wrap_descrip.size(); i++ ) {
             msg += "\n  " + wrap_descrip[i];
         }
         msg += "</color>\n";
         lines += wrap_descrip.size();
     }
     // borrowed from item.cpp and adjusted
     for( const auto &qual : qualities ) {
         msg += string_format(
                    _( "Has level <color_cyan>%1$d %2$s</color> quality" ), qual.second, qual.first.obj().name );
         if( qual.first == qual_JACK || qual.first == qual_LIFT ) {
             msg += string_format( _( " and is rated at <color_cyan>%1$d %2$s</color>" ),
                                   static_cast<int>( convert_weight( lifting_quality_to_mass( qual.second ) ) ),
                                   weight_units() );
         }
         msg += ".\n";
         lines += 1;
     }
     return lines;
 }
References _, base_item, convert_weight(), default_ammo, description, enumerate_as_string(), epower, flags, foldstring(), json_flag::get(), get_pseudo_tools(), has_flag(), string_id< T >::is_null(), lifting_quality_to_mass(), MAGAZINE_WELL, qual_JACK, qual_LIFT, qualities, string_format(), string_from_color(), units::to_watt(), toolkit_info, translation::translated(), and weight_units().
Referenced by veh_interact::can_remove_part(), veh_interact::do_repair(), vehicle::print_vparts_descs(), and veh_interact::update_part_requirements().
get_categories()
const std::set< std::string > & vpart_info::get_categories () const
Gets all categories of this part.
Definition at line 452 of file veh_type.cpp.
 {
     return this->categories;
 }
References categories.
get_flags()
const std::set<std::string>& vpart_info::get_flags () const inline
Definition at line 253 of file veh_type.h.
{
             return flags;
         }
References flags.
Referenced by vehicle::break_off(), vehicle::can_mount(), vehicle::can_unmount(), check(), and finalize().
get_folding_time()
time_duration vpart_info::get_folding_time () const
Definition at line 1146 of file veh_type.cpp.
 {
     return folding_time;
 }
References folding_time.
Referenced by vehicle::folding_time().
get_folding_tools()
std::vector< itype_id > vpart_info::get_folding_tools () const
Definition at line 1136 of file veh_type.cpp.
 {
     return folding_tools;
 }
References folding_tools.
get_pseudo_tools()
std::set< std::pair< itype_id, int > > vpart_info::get_pseudo_tools () const
Definition at line 1131 of file veh_type.cpp.
 {
     return pseudo_tools;
 }
References pseudo_tools.
Referenced by vehicle::build_interact_menu(), format_description(), and vehicle::prepare_tools().
get_unfolding_time()
time_duration vpart_info::get_unfolding_time () const
Definition at line 1151 of file veh_type.cpp.
 {
     return unfolding_time;
 }
References unfolding_time.
Referenced by vehicle::unfolding_time().
get_unfolding_tools()
std::vector< itype_id > vpart_info::get_unfolding_tools () const
Definition at line 1141 of file veh_type.cpp.
 {
     return unfolding_tools;
 }
References unfolding_tools.
handle_inheritance()
void vpart_info::handle_inheritance (const vpart_info & copy_from, const std::unordered_map< std::string, vpart_info > & abstracts)
Definition at line 241 of file veh_type.cpp.
 {
     *this = copy_from; // use assignment operator, like the normal copy-from handling is done
     // vehicle parts have special treatment; the following chunk tries to massage copy-from into
     // looks_like: follows copy-from chain to find the first real part id and sets it as looks_like,
     // or sets it to the last abstract, makes up to 5 jumps.
     looks_like = copy_from.id.str();
     for( int i = 0; i < 5; i++ ) {
         if( vpart_info_factory.is_valid( vpart_id( looks_like ) ) ) {
             break; // real part
         }
         const auto abstract_it = abstracts.find( looks_like );
         if( abstract_it == abstracts.end() ) {
             break; // looks_like might invalid vpart id (but valid furniture/terrain etc tile)
         }
         if( abstract_it->second.looks_like.empty() ) {
             break; // abstract has no looks_like
         }
         looks_like = abstract_it->second.looks_like;
     }
 }
References id, looks_like, string_id< T >::str(), and anonymous_namespace{veh_type.cpp}::vpart_info_factory.
has_category()
bool vpart_info::has_category (const std::string & category) const
Gets whether part is in a category for display.
Definition at line 1126 of file veh_type.cpp.
 {
     return this->categories.find( category ) != this->categories.end();
 }
References categories.
has_control_req()
bool vpart_info::has_control_req () const
Returns whether or not the vehicle this part installed requires something to control.
Definition at line 1156 of file veh_type.cpp.
 {
     return !control_air.proficiencies.empty() || !control_air.skills.empty() ||
            !control_land.proficiencies.empty() || !control_land.skills.empty();
 }
References control_air, control_land, vp_control_req::proficiencies, and vp_control_req::skills.
Referenced by vehicle::refresh().
has_flag() [1/2]
bool vpart_info::has_flag (const std::string & flag) const inline
Definition at line 256 of file veh_type.h.
{
             return flags.count( flag ) != 0;
         }
References flags.
Referenced by vehicle::active_reactor_epower(), vehicle::avail_linkable_part(), vehicle::break_off(), map::build_seen_cache(), veh_interact::calc_lift_requirements(), veh_app_interact::can_disconnect(), vehicle::can_enable(), vehicle::can_mount(), veh_interact::can_potentially_install(), veh_interact::can_remove_part(), vehicle::can_unmount(), game::chat(), vpart_migration::check(), check(), vehicle::close(), vehicle::coeff_air_drag(), vehicle::coeff_water_drag(), vehicle::collision(), veh_interact::complete_vehicle(), vehicle::control_doors(), vehicle::damage(), vehicle::damage_all(), vehicle::damage_direct(), veh_interact::display_details(), veh_interact::do_repair(), vehicle::engine_cold_factor(), vehicle::engine_start_time(), item::final_info(), finalize(), vehicles::finalize_prototypes(), vehicle::find_lines_of_parts(), format_description(), vehicle::fuel_left(), map::generate_lightmap(), vehicle::get_connected_vehicles(), vehicle::get_display_of_tile(), get_looks_like(), vehicle::handle_trap(), vpart_reference::has_feature(), vehicle::has_security_working(), vehicle::has_structural_part(), vehicle::init_state(), vehicle::install_part(), vehicle_part::is_battery(), vehicle_part::is_cleaner_on(), vehicle::is_connected(), vehicle_part::is_engine(), vehicle::is_engine_type_combustion(), vehicle_part::is_light(), vehicle_part::is_reactor(), is_repairable(), vehicle_part::is_seat(), load(), vehicle::lock(), vehicle_part_with_feature_range< feature_type >::matches(), vehicle_stack::max_volume(), vehicle::merge_vehicle_parts(), map::move_vehicle(), name(), vehicle::next_part_to_close(), vehicle::next_part_to_lock(), vehicle::next_part_to_open(), vehicle::next_part_to_unlock(), vehicle::open(), vehicle::open_all_at(), vehicle::part_collision(), vehicle::part_has_lock(), vehicle::part_vpower_w(), vehicle::part_with_feature(), place_appliance(), veh_app_interact::populate_app_actions(), vehicle::power_parts(), vehicle::print_part_list(), map::process_items_in_vehicle(), process_vehicle_items(), vehicle::refresh(), vehicle::refresh_insides(), vehicle::remove_part(), vehicle::roof_at_part(), map::route(), vehicle::search_connected_vehicles(), map::shake_vehicle(), vehicle::shed_loose_parts(), vehicle::smash_security_system(), vehicle::split_vehicles(), vehicle::start_engine(), tell_magic_veh_stop_following(), tell_magic_veh_to_follow(), vehicle::unlink_cables(), vehicle::unlock(), vehicle::update_active_fakes(), vehicle::update_alternator_load(), veh_interact::update_part_requirements(), vehicle::use_harness(), turret_data::uses_vehicle_tanks_or_batteries(), veh_lumi(), vehicle::would_install_prevent_flyable(), vehicle::would_removal_prevent_flyable(), and vehicle::would_repair_prevent_flyable().
has_flag() [2/2]
bool vpart_info::has_flag (const vpart_bitflags flag) const inline
Definition at line 259 of file veh_type.h.
{
             return bitflags.test( flag );
         }
References bitflags.
install_requirements()
requirement_data vpart_info::install_requirements () const
Installation requirements for this component.
Definition at line 1072 of file veh_type.cpp.
 {
     return requirement_data( install_reqs );
 }
References install_reqs.
Referenced by veh_interact::can_potentially_install(), veh_interact::complete_vehicle(), veh_interact::do_repair(), vehicle_part::get_salvageable(), veh_utils::most_repairable_part(), veh_utils::repair_part(), and veh_interact::update_part_requirements().
install_time()
time_duration vpart_info::install_time (const Character & you) const
Installation time (in moves) for this component accounting for player skills.
Definition at line 1111 of file veh_type.cpp.
 {
     return scale_time( install_skills, install_moves, you );
 }
References install_moves, install_skills, and scale_time().
Referenced by veh_interact::do_repair(), and veh_interact::update_part_requirements().
is_repairable()
bool vpart_info::is_repairable () const
Returns whether or not the part type is repairable.
Definition at line 1087 of file veh_type.cpp.
 {
     return !has_flag( "NO_REPAIR" ) && !repair_requirements().is_empty();
 }
References has_flag(), requirement_data::is_empty(), and repair_requirements().
Referenced by vehicle_part::is_repairable().
load()
void vpart_info::load (const JsonObject & jo, const std::string & src)
Definition at line 265 of file veh_type.cpp.
 {
     const bool strict = src == "dda";
     assign( jo, "name", name_, strict );
     assign( jo, "item", base_item, strict );
     assign( jo, "remove_as", removed_item, strict );
     assign( jo, "location", location, strict );
     assign( jo, "durability", durability, strict );
     assign( jo, "damage_modifier", dmg_mod, strict );
     assign( jo, "energy_consumption", energy_consumption, strict );
     assign( jo, "power", power, strict );
     assign( jo, "epower", epower, strict );
     assign( jo, "emissions", emissions, strict );
     assign( jo, "exhaust", exhaust, strict );
     assign( jo, "fuel_type", fuel_type, strict );
     assign( jo, "default_ammo", default_ammo, strict );
     assign( jo, "folded_volume", folded_volume, strict );
     assign( jo, "size", size, strict );
     assign( jo, "bonus", bonus, strict );
     assign( jo, "cargo_weight_modifier", cargo_weight_modifier, strict );
     assign( jo, "categories", categories, strict );
     assign( jo, "flags", flags, strict );
     assign( jo, "description", description, strict );
     assign( jo, "color", color, strict );
     assign( jo, "broken_color", color_broken, strict );
     assign( jo, "comfort", comfort, strict );
     int legacy_floor_bedding_warmth = units::to_legacy_bodypart_temp_delta( floor_bedding_warmth );
     assign( jo, "floor_bedding_warmth", legacy_floor_bedding_warmth, strict );
     floor_bedding_warmth = units::from_legacy_bodypart_temp_delta( legacy_floor_bedding_warmth );
     int legacy_bonus_fire_warmth_feet = units::to_legacy_bodypart_temp_delta( bonus_fire_warmth_feet );
     assign( jo, "bonus_fire_warmth_feet", legacy_bonus_fire_warmth_feet, strict );
     bonus_fire_warmth_feet = units::from_legacy_bodypart_temp_delta( legacy_bonus_fire_warmth_feet );
     if( jo.has_array( "variants" ) ) {
         variants.clear();
         for( const JsonObject jo_variant : jo.get_array( "variants" ) ) {
             vpart_variant v;
             v.load( jo_variant, true );
             if( variant_default.empty() ) {
                 variant_default = v.id;
             }
             variants[v.id] = v;
         }
     }
     if( jo.has_array( "variants_bases" ) ) {
         variants_bases.clear();
         for( const JsonObject jo : jo.get_array( "variants_bases" ) ) {
             variants_bases.emplace_back( jo.get_string( "id" ), jo.get_string( "label" ) );
         }
     }
     if( jo.has_member( "requirements" ) ) {
         JsonObject reqs = jo.get_object( "requirements" );
         parse_vp_reqs( reqs, id, "install", install_reqs, install_skills, install_moves );
         parse_vp_reqs( reqs, id, "removal", removal_reqs, removal_skills, removal_moves );
         parse_vp_reqs( reqs, id, "repair",  repair_reqs,  repair_skills, repair_moves );
     }
     if( jo.has_member( "control_requirements" ) ) {
         JsonObject reqs = jo.get_object( "control_requirements" );
         parse_vp_control_reqs( reqs, id, "air", control_air );
         parse_vp_control_reqs( reqs, id, "land", control_land );
     }
     assign( jo, "looks_like", looks_like, strict );
     if( jo.has_member( "breaks_into" ) ) {
         breaks_into_group = item_group::load_item_group(
                                 jo.get_member( "breaks_into" ), "collection", "breaks_into for vpart " + id.str() );
     }
     JsonArray qual = jo.get_array( "qualities" );
     if( !qual.empty() ) {
         qualities.clear();
         for( JsonArray pair : qual ) {
             qualities[ quality_id( pair.get_string( 0 ) ) ] = pair.get_int( 1 );
         }
     }
     JsonArray tools = jo.get_array( "pseudo_tools" );
     if( !tools.empty() ) {
         pseudo_tools.clear();
         while( tools.has_more() ) {
             const JsonObject tooldef = tools.next_object();
             const itype_id tool_id( tooldef.get_string( "id" ) );
             const std::string hotkey_str = tooldef.has_string( "hotkey" ) ? tooldef.get_string( "hotkey" ) : "";
             const int hotkey = hotkey_str.empty() ? -1 : static_cast<int>( hotkey_str[0] );
             if( !pseudo_tools.insert( { tool_id, hotkey } ).second ) {
                 debugmsg( "Insert failed on %s to %s's tools, duplicate?", tool_id.str(), id.str() );
             }
         }
     }
     assign( jo, "folding_tools", folding_tools, strict );
     assign( jo, "unfolding_tools", unfolding_tools, strict );
     assign( jo, "folding_time", folding_time, strict );
     assign( jo, "unfolding_time", unfolding_time, strict );
     if( jo.has_member( "damage_reduction" ) ) {
         JsonObject dred = jo.get_object( "damage_reduction" );
         damage_reduction = load_damage_map( dred );
     }
     if( has_flag( "ENGINE" ) ) {
         if( !engine_info ) {
             engine_info.emplace();
         }
         assign( jo, "backfire_threshold", engine_info->backfire_threshold, strict );
         assign( jo, "backfire_freq", engine_info->backfire_freq, strict );
         assign( jo, "noise_factor", engine_info->noise_factor, strict );
         assign( jo, "damaged_power_factor", engine_info->damaged_power_factor, strict );
         assign( jo, "m2c", engine_info->m2c, strict );
         assign( jo, "muscle_power_factor", engine_info->muscle_power_factor, strict );
         assign( jo, "exclusions", engine_info->exclusions, strict );
         assign( jo, "fuel_options", engine_info->fuel_opts, strict );
     }
     if( has_flag( "WHEEL" ) ) {
         if( !wheel_info ) {
             wheel_info.emplace();
         }
         assign( jo, "rolling_resistance", wheel_info->rolling_resistance, strict );
         assign( jo, "contact_area", wheel_info->contact_area, strict );
         assign( jo, "wheel_offroad_rating", wheel_info->offroad_rating, strict );
         if( const std::optional<JsonValue> jo_termod = jo.get_member_opt( "wheel_terrain_modifiers" ) ) {
             wheel_info->terrain_modifiers.clear();
             for( const JsonMember jo_mod : static_cast<JsonObject>( *jo_termod ) ) {
                 const JsonArray jo_mod_values = jo_mod.get_array();
                 veh_ter_mod mod { jo_mod.name(), jo_mod_values.get_int( 0 ), jo_mod_values.get_int( 1 ) };
                 wheel_info->terrain_modifiers.emplace_back( std::move( mod ) );
             }
         }
     }
     if( has_flag( "ROTOR" ) ) {
         if( !rotor_info ) {
             rotor_info.emplace();
         }
         assign( jo, "rotor_diameter", rotor_info->rotor_diameter, strict );
     }
     if( has_flag( "WORKBENCH" ) ) {
         if( !workbench_info ) {
             workbench_info.emplace();
         }
         JsonObject wb_jo = jo.get_object( "workbench" );
         assign( wb_jo, "multiplier", workbench_info->multiplier, strict );
         assign( wb_jo, "mass", workbench_info->allowed_mass, strict );
         assign( wb_jo, "volume", workbench_info->allowed_volume, strict );
     }
     if( has_flag( "VEH_TOOLS" ) ) {
         if( !toolkit_info ) {
             toolkit_info.emplace();
         }
         assign( jo, "allowed_tools", toolkit_info->allowed_types, strict );
     }
     if( has_flag( "TRANSFORM_TERRAIN" ) || has_flag( "CRASH_TERRAIN_AROUND" ) ) {
         if( !transform_terrain_info ) {
             transform_terrain_info.emplace();
         }
         JsonObject jttd = jo.get_object( "transform_terrain" );
         vpslot_terrain_transform &vtt = *transform_terrain_info;
         optional( jttd, was_loaded, "pre_flags", vtt.pre_flags, {} );
         optional( jttd, was_loaded, "post_terrain", vtt.post_terrain, "t_null" );
         optional( jttd, was_loaded, "post_furniture", vtt.post_furniture, "f_null" );
         optional( jttd, was_loaded, "post_field", vtt.post_field, "fd_null" );
         optional( jttd, was_loaded, "post_field_intensity", vtt.post_field_intensity, 0 );
         optional( jttd, was_loaded, "post_field_age", vtt.post_field_age, 0_seconds );
     }
 }
References assign(), base_item, bonus, bonus_fire_warmth_feet, breaks_into_group, cargo_weight_modifier, categories, color, color_broken, comfort, control_air, control_land, damage_reduction, debugmsg, default_ammo, description, dmg_mod, durability, emissions, JsonArray::empty(), energy_consumption, engine_info, epower, exhaust, flags, floor_bedding_warmth, folded_volume, folding_time, folding_tools, units::from_legacy_bodypart_temp_delta(), fuel_type, JsonArray::get_array(), JsonObject::get_array(), JsonArray::get_int(), JsonObject::get_member(), JsonObject::get_member_opt(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), has_flag(), JsonObject::has_member(), JsonArray::has_more(), JsonObject::has_string(), vpart_variant::id, install_moves, install_reqs, install_skills, vpart_variant::load(), load_damage_map(), item_group::load_item_group(), location, looks_like, name_, JsonArray::next_object(), optional(), parse_vp_control_reqs(), parse_vp_reqs(), vpslot_terrain_transform::post_field, vpslot_terrain_transform::post_field_age, vpslot_terrain_transform::post_field_intensity, vpslot_terrain_transform::post_furniture, vpslot_terrain_transform::post_terrain, power, vpslot_terrain_transform::pre_flags, pseudo_tools, qualities, removal_moves, removal_reqs, removal_skills, removed_item, repair_moves, repair_reqs, repair_skills, rotor_info, size, src, Json::str(), string_id< T >::str(), strict, units::to_legacy_bodypart_temp_delta(), toolkit_info, transform_terrain_info, unfolding_time, unfolding_tools, variant_default, variants, variants_bases, was_loaded, wheel_info, and workbench_info.
name()
std::string vpart_info::name () const
Translated name of a part.
Definition at line 965 of file veh_type.cpp.
 {
     std::string res = name_.translated();
     if( res.empty() ) {
         res = item::nname( base_item ); // fallback to base item's translation
     }
     if( has_flag( "TURRET" ) ) {
         res = string_format( pgettext( "mounted turret prefix", "mounted %s" ), res );
     }
     return res;
 }
References base_item, has_flag(), name_, item::nname(), pgettext, string_format(), and translation::translated().
Referenced by can_do_activity_there(), vehicle::can_mount(), veh_interact::complete_vehicle(), veh_interact::display_details(), veh_interact::display_list(), veh_interact::do_install(), vehicle_part::name(), orient_part(), place_appliance(), put_into_vehicle(), and map::vehicle_vehicle_collision().
removal_requirements()
requirement_data vpart_info::removal_requirements () const
Requirements for removal of this component.
Definition at line 1077 of file veh_type.cpp.
 {
     return requirement_data( removal_reqs );
 }
References removal_reqs.
Referenced by can_do_activity_there(), veh_interact::can_remove_part(), veh_interact::complete_vehicle(), generic_multi_activity_check_requirement(), and veh_app_interact::remove().
removal_time()
time_duration vpart_info::removal_time (const Character & you) const
Removal time (in moves) for this component accounting for player skills.
Definition at line 1116 of file veh_type.cpp.
 {
     return scale_time( removal_skills, removal_moves, you );
 }
References removal_moves, removal_skills, and scale_time().
Referenced by veh_interact::can_remove_part(), veh_app_interact::remove(), and vehicle_activity().
repair_requirements()
requirement_data vpart_info::repair_requirements () const
Requirements for repair of this component (per level of damage)
Definition at line 1082 of file veh_type.cpp.
 {
     return requirement_data( repair_reqs );
 }
References repair_reqs.
Referenced by can_do_activity_there(), veh_interact::do_repair(), generic_multi_activity_check_requirement(), is_repairable(), veh_utils::most_repairable_part(), and veh_utils::repair_part().
repair_time()
time_duration vpart_info::repair_time (const Character & you) const
Repair time (in moves) to fully repair this component, accounting for player skills.
Definition at line 1121 of file veh_type.cpp.
 {
     return scale_time( repair_skills, repair_moves, you );
 }
References repair_moves, repair_skills, and scale_time().
Referenced by veh_interact::do_repair(), and vehicle_activity().
set_flag()
void vpart_info::set_flag (const std::string & flag)
Definition at line 443 of file veh_type.cpp.
 {
     flags.insert( flag );
     const auto iter = vpart_bitflag_map.find( flag );
     if( iter != vpart_bitflag_map.end() ) {
         bitflags.set( iter->second );
     }
 }
References bitflags, flags, and vpart_bitflag_map.
Referenced by vehicles::parts::finalize(), and finalize().
Friends And Related Function Documentation
generic_factory< vpart_info >
friend class generic_factory< vpart_info > friend
Definition at line 461 of file veh_type.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 463 of file veh_type.h.
Member Data Documentation
base_item
itype_id vpart_info::base_item
base item for this part
Definition at line 400 of file veh_type.h.
Referenced by veh_interact::calc_lift_requirements(), can_do_activity_there(), check(), veh_interact::complete_vehicle(), vehicle::damage_direct(), veh_interact::display_details(), vehicles::parts::finalize(), finalize(), vehicles::finalize_prototypes(), format_description(), load(), name(), vehicle::part_collision(), place_appliance(), map::process_items_in_vehicle(), and veh_utils::repair_part().
bitflags
std::bitset<NUM_VPFLAGS> vpart_info::bitflags private
Definition at line 320 of file veh_type.h.
Referenced by has_flag(), and set_flag().
bonus
int vpart_info::bonus = 0
Definition at line 445 of file veh_type.h.
Referenced by map::build_seen_cache(), vehicle::damage_all(), veh_interact::display_details(), map::generate_lightmap(), vehicle::get_exhaust_part(), vehicle::honk_horn(), load(), process_vehicle_items(), map::shake_vehicle(), vehicle::update_time(), and veh_lumi().
bonus_fire_warmth_feet
units::temperature_delta vpart_info::bonus_fire_warmth_feet = 0.6_C_delta
Definition at line 453 of file veh_type.h.
Referenced by load().
breaks_into_group
item_group_id vpart_info::breaks_into_group = item_group_id("EMPTY_GROUP")
item_group this part breaks into when destroyed
Definition at line 358 of file veh_type.h.
Referenced by check(), load(), and vehicle_part::pieces_for_broken_part().
cargo_weight_modifier
int vpart_info::cargo_weight_modifier = 100
cargo weight modifier (percentage)
Definition at line 448 of file veh_type.h.
Referenced by load().
categories
std::set<std::string> vpart_info::categories private
Definition at line 318 of file veh_type.h.
Referenced by get_categories(), has_category(), and load().
color
nc_color vpart_info::color = c_light_gray
Color of part for different states.
Definition at line 378 of file veh_type.h.
Referenced by veh_interact::display_list(), do_change_shape_menu(), vehicles::parts::finalize(), vehicle::get_display_of_tile(), and load().
color_broken
nc_color vpart_info::color_broken = c_light_gray
Definition at line 379 of file veh_type.h.
Referenced by vehicle::get_display_of_tile(), and load().
comfort
int vpart_info::comfort = 0
Definition at line 451 of file veh_type.h.
Referenced by load().
control_air
vp_control_req vpart_info::control_air
Definition at line 354 of file veh_type.h.
Referenced by has_control_req(), and load().
control_land
vp_control_req vpart_info::control_land
Definition at line 355 of file veh_type.h.
Referenced by has_control_req(), and load().
damage_reduction
std::unordered_map<damage_type_id, float> vpart_info::damage_reduction = {}
Flat decrease of damage of a given type.
Definition at line 361 of file veh_type.h.
Referenced by check(), vehicle::damage(), vehicle::damage_direct(), finalize(), and load().
default_ammo
itype_id vpart_info::default_ammo = itype_id::NULL_ID()
Default ammo (for turrets)
Definition at line 385 of file veh_type.h.
Referenced by turret_data::ammo_current(), check(), format_description(), and load().
description
translation vpart_info::description
A text description of the part as a vehicle part.
Definition at line 397 of file veh_type.h.
Referenced by vehicles::parts::finalize(), format_description(), and load().
dmg_mod
int vpart_info::dmg_mod = 100
Damage modifier (percentage) used when damaging other entities upon collision.
Definition at line 412 of file veh_type.h.
Referenced by check(), veh_interact::display_details(), load(), and vehicle::part_collision().
durability
int vpart_info::durability = 0
Maximum damage part can sustain before being destroyed.
Definition at line 409 of file veh_type.h.
Referenced by vehicle::break_off(), map::build_seen_cache(), check(), vehicle::damage(), vehicle::damage_direct(), veh_interact::display_details(), vehicle::handle_trap(), vehicle_part::hp(), vehicle::init_state(), load(), vehicle::mod_hp(), veh_utils::repair_part(), vehicle::set_hp(), vehicle::smash(), and vehicle::smash_security_system().
emissions
std::set<emit_id> vpart_info::emissions
Emissions of part.
Definition at line 367 of file veh_type.h.
Referenced by check(), vehicle::idle(), load(), and vehicle::refresh().
energy_consumption
units::power vpart_info::energy_consumption = 0_W
Energy consumed per second by engines and motors when delivering max power Includes waste.
Gets scaled based on powertrain demand.
Definition at line 424 of file veh_type.h.
Referenced by veh_interact::display_details(), vehicle::engine_fuel_usage(), and load().
engine_info
std::optional<vpslot_engine> vpart_info::engine_info
Definition at line 296 of file veh_type.h.
Referenced by vehicle::auto_select_fuel(), vehicle::control_engines(), finalize(), vehicle::has_engine_conflict(), load(), vehicle::noise_and_smoke(), vehicle::part_vpower_w(), vehicle::start_engine(), vehicle::stop_engines(), and vehicle::total_power().
epower
units::power vpart_info::epower = 0_W
Electrical power, flat rate energy (per second); positive for generation, negative for consumption For electric motor consumption scaled with powertrain demand see energy_consumption instead.
Definition at line 418 of file veh_type.h.
Referenced by vehicle::can_enable(), check(), veh_interact::display_details(), format_description(), load(), vehicle::part_epower(), vehicle::power_parts(), vehicle::search_connected_vehicles(), and vehicle::total_accessory_epower().
exhaust
std::set<emit_id> vpart_info::exhaust
Exhaust emissions of part.
If the vehicle has an exhaust part, it is emitted there; otherwise, it is emitted in place
Definition at line 375 of file veh_type.h.
Referenced by check(), vehicle::idle(), load(), and vehicle::refresh().
flags
std::set<std::string> vpart_info::flags private
Definition at line 316 of file veh_type.h.
Referenced by format_description(), get_flags(), has_flag(), load(), and set_flag().
floor_bedding_warmth
units::temperature_delta vpart_info::floor_bedding_warmth = 0_C_delta
Definition at line 452 of file veh_type.h.
Referenced by load().
folded_volume
std::optional<units::volume> vpart_info::folded_volume = std::nullopt
Volume of a foldable part when folded.
Definition at line 388 of file veh_type.h.
Referenced by check(), veh_interact::display_details(), veh_interact::do_install(), vehicles::parts::finalize(), and load().
folding_time
time_duration vpart_info::folding_time = 10_seconds private
Definition at line 334 of file veh_type.h.
Referenced by get_folding_time(), and load().
folding_tools
std::vector<itype_id> vpart_info::folding_tools private
Definition at line 330 of file veh_type.h.
Referenced by get_folding_tools(), and load().
fuel_type
itype_id vpart_info::fuel_type = itype_id::NULL_ID()
Fuel type of engine or tank.
Definition at line 382 of file veh_type.h.
Referenced by vehicle::activate_animal_follow(), vehicle::auto_select_fuel(), check(), veh_interact::display_details(), vehicle::explode_fuel(), finalize(), vehicle_part::fuel_current(), vehicle::fuel_left(), vehicle::get_harnessed_animal(), vehicle::install_part(), vehicle::is_perpetual_type(), load(), vehicle::part_vpower_w(), vehicle::start_engine(), vehicle::steering_effectiveness(), and vehicle::thrust().
id
vpart_id vpart_info::id
Definition at line 242 of file veh_type.h.
Referenced by vehicle::can_mount(), veh_interact::complete_vehicle(), vehicles::parts::finalize(), vehicles::finalize_prototypes(), vehicle::find_lines_of_parts(), vehicle::get_display_of_tile(), handle_inheritance(), vehicle::honk_horn(), vehicle::install_part(), vehicle::merge_vehicle_parts(), veh_app_interact::refill(), veh_app_interact::remove(), vehicle::remove_part(), DefaultRemovePartHandler::removed(), veh_utils::repair_part(), vehicle_prototype::save_vehicle_as_prototype(), vehicle::smash(), vehicle::start_engine(), vehicle::stop_engines(), and vehicle_activity().
install_moves
time_duration vpart_info::install_moves = 1_hours
Installation for component (.
See also
install_time)
Definition at line 433 of file veh_type.h.
Referenced by veh_utils::calc_xp_gain(), check(), vehicles::parts::finalize(), finalize(), install_time(), and load().
install_reqs
std::vector<std::pair<requirement_id, int> > vpart_info::install_reqs private
Second field is the multiplier.
Definition at line 323 of file veh_type.h.
Referenced by check(), finalize(), install_requirements(), and load().
install_skills
std::map<skill_id, int> vpart_info::install_skills
Required skills to install, repair, or remove this component.
Definition at line 349 of file veh_type.h.
Referenced by veh_utils::calc_xp_gain(), check(), veh_interact::complete_vehicle(), veh_interact::do_repair(), vehicles::parts::finalize(), install_time(), load(), veh_utils::most_repairable_part(), veh_utils::repair_part(), and veh_interact::update_part_requirements().
list_order
int vpart_info::list_order = 0
Definition at line 458 of file veh_type.h.
Referenced by finalize(), and vehicle::refresh().
location
std::string vpart_info::location
What slot of the vehicle tile does this part occupy?
Definition at line 406 of file veh_type.h.
Referenced by vehicle::break_off(), vehicle::can_mount(), vehicle::can_unmount(), vehicle::coeff_air_drag(), vehicle::collision(), veh_interact::complete_vehicle(), vehicle::damage(), vehicle::damage_all(), finalize(), vehicle::find_and_split_vehicles(), vehicle::has_structural_part(), vehicle::is_connected(), load(), vehicle::print_part_list(), vehicle::roof_at_part(), vehicle_prototype::save_vehicle_as_prototype(), vehicle::smash(), and vehicle::split_vehicles().
looks_like
std::string vpart_info::looks_like
hint to tilesets for what tile to use if this part doesn't have one
Definition at line 394 of file veh_type.h.
Referenced by vehicles::parts::finalize(), handle_inheritance(), and load().
name_
translation vpart_info::name_ private
Name from vehicle part definition which if set overrides the base item name.
Definition at line 339 of file veh_type.h.
Referenced by load(), and name().
power
units::power vpart_info::power = 0_W
For engines and motors this is maximum output (watts) For alternators is engine power consumed (negative value)
Definition at line 430 of file veh_type.h.
Referenced by check(), veh_interact::display_details(), load(), vehicle::part_vpower_w(), vehicle::power_parts(), and vehicle::refresh().
pseudo_tools
std::set<std::pair<itype_id, int> > vpart_info::pseudo_tools private
Pseudo tools this provides when installed, second is the hotkey.
Definition at line 328 of file veh_type.h.
Referenced by finalize(), get_pseudo_tools(), and load().
qualities
std::map<quality_id, int> vpart_info::qualities
Tool qualities this vehicle part can provide when installed.
Definition at line 364 of file veh_type.h.
Referenced by check(), format_description(), has_quality_from_vpart(), load(), and max_quality_from_vpart().
removal_moves
time_duration vpart_info::removal_moves = -1_seconds
Removal time for component (.
See also
removal_time), default is half install_moves
Definition at line 437 of file veh_type.h.
Referenced by check(), vehicles::parts::finalize(), finalize(), load(), and removal_time().
removal_reqs
std::vector<std::pair<requirement_id, int> > vpart_info::removal_reqs private
Definition at line 324 of file veh_type.h.
Referenced by check(), load(), and removal_requirements().
removal_skills
std::map<skill_id, int> vpart_info::removal_skills
Definition at line 351 of file veh_type.h.
Referenced by can_do_activity_there(), veh_interact::can_remove_part(), check(), vehicles::parts::finalize(), load(), and removal_time().
removed_item
std::optional<itype_id> vpart_info::removed_item
item it should be removed as
Definition at line 403 of file veh_type.h.
Referenced by load(), and vehicle::removed_part().
repair_moves
time_duration vpart_info::repair_moves = 1_hours
Repair time to fully repair a component (.
See also
repair_time)
Definition at line 435 of file veh_type.h.
Referenced by load(), and repair_time().
repair_reqs
std::vector<std::pair<requirement_id, int> > vpart_info::repair_reqs private
Definition at line 325 of file veh_type.h.
Referenced by check(), load(), and repair_requirements().
repair_skills
std::map<skill_id, int> vpart_info::repair_skills
Definition at line 350 of file veh_type.h.
Referenced by can_do_activity_there(), check(), veh_interact::do_repair(), load(), veh_utils::most_repairable_part(), veh_utils::repair_part(), and repair_time().
rotor_info
std::optional<vpslot_rotor> vpart_info::rotor_info
Definition at line 298 of file veh_type.h.
Referenced by vehicle::collision(), vehicle::autodrive_controller::compute_profile(), and load().
size
units::volume vpart_info::size = 0_ml
Cargo location volume.
Definition at line 391 of file veh_type.h.
Referenced by check(), veh_interact::display_details(), load(), vehicle_stack::max_volume(), and monster::process_effects().
src
std::vector<std::pair<vpart_id, mod_id> > vpart_info::src private
Definition at line 461 of file veh_type.h.
Referenced by load().
toolkit_info
std::optional<vpslot_toolkit> vpart_info::toolkit_info
Definition at line 295 of file veh_type.h.
Referenced by vehicle::build_interact_menu(), finalize(), format_description(), and load().
transform_terrain_info
std::optional<vpslot_terrain_transform> vpart_info::transform_terrain_info
Definition at line 299 of file veh_type.h.
Referenced by load().
unfolding_time
time_duration vpart_info::unfolding_time = 10_seconds private
Definition at line 336 of file veh_type.h.
Referenced by get_unfolding_time(), and load().
unfolding_tools
std::vector<itype_id> vpart_info::unfolding_tools private
Definition at line 332 of file veh_type.h.
Referenced by get_unfolding_tools(), and load().
variant_default
std::string vpart_info::variant_default
Definition at line 344 of file veh_type.h.
Referenced by veh_interact::display_list(), finalize(), load(), vehicle_prototype::save_vehicle_as_prototype(), and vehicle_part::vehicle_part().
variants
std::map<std::string, vpart_variant> vpart_info::variants
Definition at line 342 of file veh_type.h.
Referenced by vpart_migration::check(), check(), veh_interact::complete_vehicle(), veh_interact::display_list(), do_change_shape_menu(), finalize(), vehicles::finalize_prototypes(), vehicle::get_display_of_tile(), and load().
variants_bases
std::vector<std::pair<std::string, std::string> > vpart_info::variants_bases
Definition at line 346 of file veh_type.h.
Referenced by finalize(), and load().
was_loaded
bool vpart_info::was_loaded = false private
Definition at line 460 of file veh_type.h.
Referenced by load().
wheel_info
std::optional<vpslot_wheel> vpart_info::wheel_info
Definition at line 297 of file veh_type.h.
Referenced by vehicle::average_offroad_rating(), load(), map::move_vehicle(), vehicle::refresh_pivot(), and map::vehicle_wheel_traction().
workbench_info
std::optional<vpslot_workbench> vpart_info::workbench_info
Definition at line 294 of file veh_type.h.
Referenced by load(), and Character::workbench_crafting_speed_multiplier().
z_order
int vpart_info::z_order = 0
Definition at line 456 of file veh_type.h.
Referenced by finalize(), and vehicle::part_displayed_at().
The documentation for this class was generated from the following files:
src/veh_type.h
src/veh_type.cpp