Cataclysm DDA: TextJsonIn Class Reference
TextJsonIn Class Reference
#include <json.h>
Public Member Functions
TextJsonIn (std::istream &s)
TextJsonIn (std::istream &s, const std::string &path)
TextJsonIn (std::istream &s, const json_source_location &loc)
TextJsonIn (const TextJsonIn &)=delete
TextJsonIn & operator= (const TextJsonIn &)=delete
shared_ptr_fast< std::string > get_path () const
bool get_ate_separator () const
void set_ate_separator (bool s)
int tell ()
void seek (int pos)
char peek ()
bool good ()
void eat_whitespace ()
void uneat_whitespace ()
void skip_member ()
void skip_string ()
void skip_value ()
void skip_object ()
void skip_array ()
void skip_true ()
void skip_false ()
void skip_null ()
void skip_number ()
std::string get_string ()
int get_int ()
unsigned int get_uint ()
int64_t get_int64 ()
uint64_t get_uint64 ()
bool get_bool ()
double get_float ()
std::string get_member_name ()
TextJsonObject get_object ()
TextJsonArray get_array ()
TextJsonValue get_value ()
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value ()
void start_array ()
bool end_array ()
void start_object ()
bool end_object ()
bool test_null ()
bool test_bool ()
bool test_number ()
bool test_int ()
bool test_float ()
bool test_string ()
bool test_bitset ()
bool test_array ()
bool test_object ()
bool read_null (bool throw_on_error=false)
bool read (bool &b, bool throw_on_error=false)
bool read (char &c, bool throw_on_error=false)
bool read (signed char &c, bool throw_on_error=false)
bool read (unsigned char &c, bool throw_on_error=false)
bool read (short unsigned int &s, bool throw_on_error=false)
bool read (short int &s, bool throw_on_error=false)
bool read (int &i, bool throw_on_error=false)
bool read (int64_t &i, bool throw_on_error=false)
bool read (uint64_t &i, bool throw_on_error=false)
bool read (unsigned int &u, bool throw_on_error=false)
bool read (float &f, bool throw_on_error=false)
bool read (double &d, bool throw_on_error=false)
bool read (std::string &s, bool throw_on_error=false)
template<size_t N>
bool read (std::bitset< N > &b, bool throw_on_error=false)
template<typename T >
auto read (string_id< T > &thing, bool throw_on_error=false) -> bool
template<typename T >
auto read (int_id< T > &thing, bool throw_on_error=false) -> bool
template<typename T >
auto read (T &v, bool throw_on_error=false) -> decltype(deserialize(v, std::declval< const TextJsonValue & >()), true)
Overload that calls a global function deserialize(T&, const TextJsonValue&), if available.
template<typename T >
auto read (T &v, bool throw_on_error=false) -> decltype(v.deserialize(std::declval< const TextJsonValue & >()), true)
Overload that calls a member function T::deserialize(const TextJsonValue&), if available.
template<typename T , std::enable_if_t< std::is_enum_v< T >, int > = 0>
bool read (T &val, bool throw_on_error=false)
template<typename T , typename U >
bool read (std::pair< T, U > &p, bool throw_on_error=false)
Overload for std::pair.
template<typename T , typename std::enable_if_t< !std::is_same_v< void, typename T::value_type > &&!is_string_like< T >::value > * = nullptr>
auto read (T &v, bool throw_on_error=false) -> decltype(v.front(), true)
template<typename T , size_t N>
bool read (std::array< T, N > &v, bool throw_on_error=false)
template<typename T , std::enable_if_t< std::is_same_v< typename T::key_type, typename T::value_type >> * = nullptr>
bool read (T &v, bool throw_on_error=false)
template<typename T >
bool read (enum_bitset< T > &v, bool throw_on_error=false)
template<typename T , std::enable_if_t< std::is_same_v< T, item >> * = nullptr>
bool read (cata::colony< T > &v, bool throw_on_error=false)
template<typename T , std::enable_if_t< !std::is_same_v< T, item > > * = nullptr>
bool read (cata::colony< T > &v, bool throw_on_error=false)
template<typename T , std::enable_if_t< !std::is_same_v< typename T::key_type, typename T::value_type > > * = nullptr>
bool read (T &m, bool throw_on_error=true)
std::string line_number (int offset_modifier=0)
void error (const std::string &message)
void error (int offset, const std::string &message)
void string_error (int offset, const std::string &message)
bool error_or_false (bool throw_, const std::string &message)
bool error_or_false (bool throw_, int offset, const std::string &message)
void rewind (int max_lines=-1, int max_chars=-1)
std::string substr (size_t pos, size_t len=std::string::npos)
Private Member Functions
void sanity_check_stream ()
void skip_separator ()
void skip_pair_separator ()
void end_value ()
number_sci_notation get_any_number ()
number_sci_notation get_any_int ()
Private Attributes
std::istream * stream
shared_ptr_fast< std::string > path
bool ate_separator = false
Detailed Description
Definition at line 240 of file json.h.
Constructor & Destructor Documentation
TextJsonIn() [1/4]
TextJsonIn::TextJsonIn (std::istream & s) explicit
Definition at line 809 of file json.cpp.
                                       : stream( &s )
 {
     sanity_check_stream();
 }
References sanity_check_stream().
TextJsonIn() [2/4]
TextJsonIn::TextJsonIn (std::istream & s, const std::string & path)
Definition at line 814 of file json.cpp.
     : stream( &s )
     , path( make_shared_fast<std::string>( path ) )
 {
     sanity_check_stream();
 }
References sanity_check_stream(), and string.
TextJsonIn() [3/4]
TextJsonIn::TextJsonIn (std::istream & s, const json_source_location & loc)
Definition at line 821 of file json.cpp.
     : stream( &s ), path( loc.path )
 {
     seek( loc.offset );
     sanity_check_stream();
 }
References json_source_location::offset, sanity_check_stream(), and seek().
TextJsonIn() [4/4]
TextJsonIn::TextJsonIn (const TextJsonIn &) delete
Member Function Documentation
eat_whitespace()
void TextJsonIn::eat_whitespace ()
Definition at line 856 of file json.cpp.
 {
     while( is_whitespace( peek() ) ) {
         stream->get();
     }
 }
References is_whitespace(), peek(), and stream.
Referenced by end_array(), end_object(), get_any_number(), get_bool(), get_string(), skip_false(), skip_null(), skip_number(), skip_pair_separator(), skip_separator(), skip_string(), skip_true(), skip_value(), start_array(), start_object(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), and test_string().
end_array()
bool TextJsonIn::end_array ()
Definition at line 1509 of file json.cpp.
 {
     eat_whitespace();
     if( peek() == ']' ) {
         if( ate_separator ) {
             uneat_whitespace();
             error( "comma not allowed at end of array" );
         }
         stream->get();
         end_value();
         return true;
     } else {
         // not the end yet, so just return false?
         return false;
     }
 }
References ate_separator, eat_whitespace(), end_value(), error(), peek(), stream, and uneat_whitespace().
Referenced by advance_jsin(), read(), skip_array(), and TextJsonArray::TextJsonArray().
end_object()
bool TextJsonIn::end_object ()
Definition at line 1542 of file json.cpp.
 {
     eat_whitespace();
     if( peek() == '}' ) {
         if( ate_separator ) {
             uneat_whitespace();
             error( "comma not allowed at end of object" );
         }
         stream->get();
         end_value();
         return true;
     } else {
         // not the end yet, so just return false?
         return false;
     }
 }
References ate_separator, eat_whitespace(), end_value(), error(), peek(), stream, and uneat_whitespace().
Referenced by advance_jsin(), read(), skip_object(), and TextJsonObject::TextJsonObject().
end_value()
void TextJsonIn::end_value () private
Definition at line 873 of file json.cpp.
 {
     ate_separator = false;
     skip_separator();
 }
References ate_separator, and skip_separator().
Referenced by end_array(), end_object(), get_any_number(), get_bool(), get_string(), read_null(), skip_false(), skip_null(), skip_number(), skip_string(), and skip_true().
error() [1/2]
void TextJsonIn::error (const std::string & message)
Definition at line 2005 of file json.cpp.
 {
     error( 0, message );
 }
References mapgen_defer::message.
Referenced by end_array(), end_object(), error_or_false(), get_any_int(), get_any_number(), get_bool(), get_enum_value(), get_int(), get_int64(), TextJsonObject::get_source_location(), get_string(), TextJsonArray::get_tags(), TextJsonObject::get_tags(), get_uint(), get_uint64(), read(), read_null(), sanity_check_stream(), skip_false(), skip_null(), skip_pair_separator(), skip_separator(), skip_string(), skip_true(), skip_value(), start_array(), start_object(), string_error(), TextJsonObject::TextJsonObject(), TextJsonObject::throw_error(), TextJsonArray::throw_error(), TextJsonValue::throw_error(), Json::throw_error_after(), TextJsonValue::throw_error_after(), TextJsonObject::throw_error_at(), TextJsonArray::verify_index(), and TextJsonObject::verify_position().
error() [2/2]
void TextJsonIn::error (int offset, const std::string & message)
Definition at line 2010 of file json.cpp.
 {
     std::ostringstream err_header;
     switch( error_log_format ) {
         case error_log_format_t::human_readable:
             err_header << "Json error: " << line_number( offset ) << ": ";
             break;
         case error_log_format_t::github_action:
             err_header << "::error " << line_number( offset ) << "::";
             break;
     }
     std::string color_normal;
     std::string color_error;
     std::string color_highlight;
     std::string color_end;
     switch( json_error_output_colors ) {
         case json_error_output_colors_t::color_tags:
             color_normal = "<color_white>";
             color_error = "<color_light_red>";
             color_highlight = "<color_cyan>";
             color_end = "</color>";
             break;
         case json_error_output_colors_t::ansi_escapes:
             color_normal = "\033[0m";
             color_error = "\033[0;31m";
             color_highlight = "\033[0;36m";
             color_end = "\033[0m";
             break;
         case json_error_output_colors_t::unset:
             err_header << "( json_error_output_colors is unset, defaulting to no colors ) ";
             break;
         default:
             // leave color strings empty
             break;
     }
     // if we can't get more info from the stream don't try
     if( !stream->good() ) {
         throw JsonError( err_header.str() + escape_data( message ) );
     }
     // Seek to eof after throwing to avoid continue reading from the incorrect
     // location. The calling code of json error methods is supposed to restore
     // the stream location if it wishes to recover from the error.
     on_out_of_scope seek_to_eof( [this]() {
         stream->seekg( 0, std::istream::end );
     } );
     std::ostringstream err;
     err << color_normal << color_highlight << message << color_end << "\n\n";
     const int max_context_lines = 3;   // limits context length to this many lines
     const int max_context_chars = 480; // limits context length to this many chars
     stream->seekg( offset, std::istream::cur );
     // if offset points to middle of a codepoint then rewind stream to codepoint start
     // this is so utf8_width below has correct utf-8 to count length.
     // pattern of 10xxxxxx means the byte is utf-8 continuation byte.
     while( ( stream->tellg() > 0 ) && ( ( stream->peek() & 0xC0 ) == 0x80 ) ) {
         stream->seekg( -1, std::istream::cur );
     }
     // remember positions of several places to print a few lines of context
     const size_t cursor_pos = tell();               // exact position of error
     rewind( 1, max_context_chars );                 // rewind to start of line
     const size_t start_of_line = tell();            // start of error line
     rewind( max_context_lines, max_context_chars ); // rewind a couple lines to show context
     const size_t start_of_context = tell();         // start of context (couple lines above)
     size_t end_of_line;                             // end of error line (without \n)
     {
         // find end of line and store in end_of_line
         seek( cursor_pos );
         end_of_line = tell();
         while( stream->peek() != EOF ) {
             if( stream->peek() == '\n' ) {
                 break;
             }
             stream->get();
             end_of_line = tell();
         }
     }
     {
         // print context lines to start of error line
         seek( start_of_context );
         std::string buffer( start_of_line - start_of_context, '\0' );
         stream->read( buffer.data(), start_of_line - start_of_context );
         err << buffer;
     }
     {
         // print error line
         std::string buffer( end_of_line - start_of_line, '\0' );
         stream->read( buffer.data(), end_of_line - start_of_line );
         err << color_error << buffer << color_end << "\n";
     }
     {
         seek( start_of_line );
         std::string buffer( cursor_pos - start_of_line, '\0' );
         stream->read( buffer.data(), cursor_pos - start_of_line );
         // display a cursor at the position if possible, or at start of line
         if( const int padding = std::max( 0, utf8_width_raw( buffer ) - 1 ); padding > 0 ) {
             err << std::string( padding, ' ' );
         }
         err << color_highlight << "" << color_end;
     }
     seek( end_of_line );
     // print the next couple lines as well
     int line_count = 0;
     char ch = 0;
     for( int i = 0; line_count < max_context_lines && stream->good() && i < max_context_chars; ++i ) {
         stream->get( ch );
         if( !stream->good() ) {
             break;
         }
         if( ch == '\r' ) {
             ch = '\n';
             ++line_count;
             if( stream->peek() == '\n' ) {
                 stream->get( ch );
             }
         } else if( ch == '\n' ) {
             ++line_count;
         }
         err << ch;
     }
     err << color_end << "\n";
     throw JsonError( err_header.str() + escape_data( err.str() ) );
 }
References ansi_escapes, color_tags, keycode::end, error_log_format, escape_data(), github_action, human_readable, json_error_output_colors, line_number(), max(), mapgen_defer::message, rewind(), seek(), stream, tell(), unset, and utf8_width_raw().
error_or_false() [1/2]
bool TextJsonIn::error_or_false (bool throw_, const std::string & message)
Definition at line 2154 of file json.cpp.
 {
     return error_or_false( throw_, 0, message );
 }
References mapgen_defer::message.
Referenced by read(), and read_null().
error_or_false() [2/2]
bool TextJsonIn::error_or_false (bool throw_, int offset, const std::string & message)
Definition at line 2159 of file json.cpp.
 {
     if( throw_ ) {
         error( offset, message );
     }
     return false;
 }
References error(), and mapgen_defer::message.
get_any_int()
number_sci_notation TextJsonIn::get_any_int () private
Definition at line 1276 of file json.cpp.
 {
     number_sci_notation n = get_any_number();
     if( n.exp < 0 ) {
         error( "Integers cannot have a decimal point or negative order of magnitude." );
     }
     // Manually apply scientific notation, since std::pow converts to double under the hood.
     for( int64_t i = 0; i < n.exp; i++ ) {
         if( n.number > std::numeric_limits<uint64_t>::max() / 10ULL ) {
             error( "Specified order of magnitude too large -- encountered overflow applying it." );
         }
         n.number *= 10ULL;
     }
     n.exp = 0;
     return n;
 }
References error(), number_sci_notation::exp, get_any_number(), max(), and number_sci_notation::number.
Referenced by get_int(), get_int64(), get_uint(), and get_uint64().
get_any_number()
number_sci_notation TextJsonIn::get_any_number () private
Definition at line 1376 of file json.cpp.
 {
     // this could maybe be prettier?
     char ch;
     number_sci_notation ret;
     int mod_e = 0;
     eat_whitespace();
     if( !stream->get( ch ) ) {
         error( "unexpected end of input" );
     }
     if( ( ret.negative = ch == '-' ) ) {
         if( !stream->get( ch ) ) {
             error( "unexpected end of input" );
         }
     } else if( ch != '.' && ( ch < '0' || ch > '9' ) ) {
         // not a valid float
         std::stringstream err;
         err << "expecting number but found '" << ch << "'";
         error( -1, err.str() );
     }
     if( ch == '0' ) {
         // allow a single leading zero in front of a '.' or 'e'/'E'
         stream->get( ch );
         if( ch >= '0' && ch <= '9' ) {
             error( -1, "leading zeros not allowed" );
         }
     }
     while( ch >= '0' && ch <= '9' ) {
         ret.number *= 10;
         ret.number += ( ch - '0' );
         if( !stream->get( ch ) ) {
             break;
         }
     }
     if( ch == '.' ) {
         while( stream->get( ch ) && ch >= '0' && ch <= '9' ) {
             ret.number *= 10;
             ret.number += ( ch - '0' );
             mod_e -= 1;
         }
     }
     if( stream && ( ch == 'e' || ch == 'E' ) ) {
         if( !stream->get( ch ) ) {
             error( "unexpected end of input" );
         }
         bool neg;
         if( ( neg = ch == '-' ) || ch == '+' ) {
             if( !stream->get( ch ) ) {
                 error( "unexpected end of input" );
             }
         }
         while( ch >= '0' && ch <= '9' ) {
             ret.exp *= 10;
             ret.exp += ( ch - '0' );
             if( !stream->get( ch ) ) {
                 break;
             }
         }
         if( neg ) {
             ret.exp *= -1;
         }
     }
     // unget the final non-number character (probably a separator)
     if( stream ) {
         stream->unget();
     }
     end_value();
     ret.exp += mod_e;
     return ret;
 }
References eat_whitespace(), end_value(), error(), math_opers::neg(), cata::hash64_detail::ret, and stream.
Referenced by get_any_int(), and get_float().
get_array()
TextJsonArray TextJsonIn::get_array ()
Definition at line 1484 of file json.cpp.
 {
     return TextJsonArray( *this );
 }
Referenced by TextJsonValue::get_array(), TextJsonArray::get_array(), TextJsonArray::get_tags(), TextJsonObject::get_tags(), and TextJsonArray::next_array().
get_ate_separator()
bool TextJsonIn::get_ate_separator () const inline
Definition at line 263 of file json.h.
{
             return ate_separator;
         }
References ate_separator.
Referenced by TextJsonArray::TextJsonArray(), and TextJsonObject::TextJsonObject().
get_bool()
bool TextJsonIn::get_bool ()
Definition at line 1447 of file json.cpp.
 {
     char ch;
     // NOLINTNEXTLINE(modernize-avoid-c-arrays)
     char text[5];
     std::stringstream err;
     eat_whitespace();
     stream->get( ch );
     if( ch == 't' ) {
         stream->get( text, 4 );
         if( strcmp( text, "rue" ) == 0 ) {
             end_value();
             return true;
         } else {
             err << R"(not a boolean.  expected "true", but got ")";
             err << ch << text << "\"";
             error( -4, err.str() );
         }
     } else if( ch == 'f' ) {
         stream->get( text, 5 );
         if( strcmp( text, "alse" ) == 0 ) {
             end_value();
             return false;
         } else {
             err << R"(not a boolean.  expected "false", but got ")";
             err << ch << text << "\"";
             error( -5, err.str() );
         }
     }
     err << "not a boolean value!  expected 't' or 'f' but got '" << ch << "'";
     error( -1, err.str() );
 }
References eat_whitespace(), end_value(), error(), and stream.
Referenced by TextJsonValue::get_bool(), TextJsonArray::get_bool(), TextJsonObject::get_bool(), TextJsonArray::next_bool(), and read().
get_enum_value()
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>> E TextJsonIn::get_enum_value () inline
Definition at line 305 of file json.h.
{
             const int old_offset = tell();
             try {
                 return io::string_to_enum<E>( get_string() );
             } catch( const io::InvalidEnumString & ) {
                 seek( old_offset ); // so the error message points to the correct place.
                 error( "invalid enumeration value" );
             }
         }
References error(), get_string(), seek(), and tell().
Referenced by TextJsonObject::get_enum_value().
get_float()
double TextJsonIn::get_float ()
Definition at line 1370 of file json.cpp.
 {
     number_sci_notation n = get_any_number();
     return n.number * std::pow( 10.0f, n.exp ) * ( n.negative ? -1.f : 1.f );
 }
References number_sci_notation::exp, get_any_number(), number_sci_notation::negative, and number_sci_notation::number.
Referenced by TextJsonValue::get_float(), TextJsonArray::get_float(), TextJsonObject::get_float(), TextJsonArray::next_float(), and read().
get_int()
int TextJsonIn::get_int ()
Definition at line 1293 of file json.cpp.
 {
     static_assert( sizeof( int ) <= sizeof( int64_t ),
                    "TextJsonIn::get_int() assumed sizeof( int ) <= sizeof( int64_t )" );
     number_sci_notation n = get_any_int();
     if( !n.negative && n.number > static_cast<uint64_t>( std::numeric_limits<int>::max() ) ) {
         error( "Found a number greater than " + std::to_string( std::numeric_limits<int>::max() ) +
                " which is unsupported in this context." );
     } else if( n.negative && n.number > neg_INT_MIN() ) {
         error( "Found a number less than " + std::to_string( std::numeric_limits<int>::min() ) +
                " which is unsupported in this context." );
     }
     if( n.negative ) {
         static_assert( neg_INT_MIN() <= static_cast<uint64_t>( std::numeric_limits<int>::max() )
                        || neg_INT_MIN() - static_cast<uint64_t>( std::numeric_limits<int>::max() )
                        <= static_cast<uint64_t>( std::numeric_limits<int>::max() ),
                        "TextJsonIn::get_int() assumed -INT_MIN - INT_MAX <= INT_MAX" );
         if( n.number > static_cast<uint64_t>( std::numeric_limits<int>::max() ) ) {
             const uint64_t x = n.number - static_cast<uint64_t>( std::numeric_limits<int>::max() );
             return -std::numeric_limits<int>::max() - static_cast<int>( x );
         } else {
             return -static_cast<int>( n.number );
         }
     } else {
         return static_cast<int>( n.number );
     }
 }
References error(), get_any_int(), max(), min(), neg_INT_MIN(), number_sci_notation::negative, number_sci_notation::number, and to_string().
Referenced by TextJsonValue::get_int(), TextJsonArray::get_int(), TextJsonObject::get_int(), TextJsonArray::next_int(), and read().
get_int64()
int64_t TextJsonIn::get_int64 ()
Definition at line 1335 of file json.cpp.
 {
     number_sci_notation n = get_any_int();
     if( !n.negative && n.number > static_cast<uint64_t>( std::numeric_limits<int64_t>::max() ) ) {
         error( "Signed integers greater than " +
                std::to_string( std::numeric_limits<int64_t>::max() ) + " not supported." );
     } else if( n.negative && n.number > neg_INT64_MIN() ) {
         error( "Integers less than "
                + std::to_string( std::numeric_limits<int64_t>::min() ) + " not supported." );
     }
     if( n.negative ) {
         static_assert( neg_INT64_MIN() <= static_cast<uint64_t>( std::numeric_limits<int64_t>::max() )
                        || neg_INT64_MIN() - static_cast<uint64_t>( std::numeric_limits<int64_t>::max() )
                        <= static_cast<uint64_t>( std::numeric_limits<int64_t>::max() ),
                        "TextJsonIn::get_int64() assumed -INT64_MIN - INT64_MAX <= INT64_MAX" );
         if( n.number > static_cast<uint64_t>( std::numeric_limits<int64_t>::max() ) ) {
             const uint64_t x = n.number - static_cast<uint64_t>( std::numeric_limits<int64_t>::max() );
             return -std::numeric_limits<int64_t>::max() - static_cast<int64_t>( x );
         } else {
             return -static_cast<int64_t>( n.number );
         }
     } else {
         return static_cast<int64_t>( n.number );
     }
 }
References error(), get_any_int(), max(), min(), neg_INT64_MIN(), number_sci_notation::negative, number_sci_notation::number, and to_string().
get_member_name()
std::string TextJsonIn::get_member_name ()
Definition at line 1066 of file json.cpp.
 {
     std::string s = get_string();
     skip_pair_separator();
     return s;
 }
References get_string(), and skip_pair_separator().
Referenced by advance_jsin(), read(), and TextJsonObject::TextJsonObject().
get_object()
TextJsonObject TextJsonIn::get_object ()
Definition at line 1480 of file json.cpp.
 {
     return TextJsonObject( *this );
 }
Referenced by JsonObject::error_no_member(), JsonObject::error_skipped_members(), TextJsonValue::get_object(), TextJsonArray::get_object(), TextJsonObject::get_object(), and TextJsonArray::next_object().
get_path()
shared_ptr_fast<std::string> TextJsonIn::get_path () const inline
Definition at line 259 of file json.h.
{
             return path;
         }
References path.
Referenced by TextJsonObject::get_source_location().
get_string()
std::string TextJsonIn::get_string ()
Definition at line 1202 of file json.cpp.
 {
     eat_whitespace();
     std::string s;
     char ch;
     std::string err;
     bool success = false;
     do {
         // the first character had better be a '"'
         stream->get( ch );
         if( !stream->good() ) {
             err = "read operation failed";
             break;
         }
         if( ch != '"' ) {
             err = "expected string but got '" + std::string( 1, ch ) + "'";
             break;
         }
         // add chars to the string, one at a time
         do {
             ch = stream->peek();
             if( !stream->good() ) {
                 err = "read operation failed";
                 break;
             }
             if( ch == '"' ) {
                 stream->ignore();
                 success = true;
                 break;
             }
             if( !get_escaped_or_unicode( *stream, s, err ) ) {
                 break;
             }
         } while( stream->good() );
     } while( false );
     if( success ) {
         end_value();
         return s;
     }
     if( stream->eof() ) {
         error( "couldn't find end of string, reached EOF." );
     } else if( stream->fail() ) {
         error( "stream failure while reading string." );
     } else {
         error( -1, err );
     }
 }
References eat_whitespace(), end_value(), error(), get_escaped_or_unicode(), and stream.
Referenced by get_enum_value(), get_member_name(), TextJsonValue::get_string(), TextJsonArray::get_string(), TextJsonObject::get_string(), TextJsonArray::get_tags(), TextJsonObject::get_tags(), TextJsonArray::next_string(), and read().
get_uint()
unsigned int TextJsonIn::get_uint ()
Definition at line 1321 of file json.cpp.
 {
     number_sci_notation n = get_any_int();
     if( n.number > std::numeric_limits<unsigned int>::max() ) {
         error( "Found a number greater than " +
                std::to_string( std::numeric_limits<unsigned int>::max() ) +
                " which is unsupported in this context." );
     }
     if( n.negative ) {
         error( "Unsigned integers cannot have a negative sign." );
     }
     return static_cast<unsigned int>( n.number );
 }
References error(), get_any_int(), max(), number_sci_notation::negative, number_sci_notation::number, and to_string().
Referenced by read().
get_uint64()
uint64_t TextJsonIn::get_uint64 ()
Definition at line 1361 of file json.cpp.
 {
     number_sci_notation n = get_any_int();
     if( n.negative ) {
         error( "Unsigned integers cannot have a negative sign." );
     }
     return n.number;
 }
References error(), get_any_int(), number_sci_notation::negative, and number_sci_notation::number.
get_value()
TextJsonValue TextJsonIn::get_value ()
Definition at line 1488 of file json.cpp.
 {
     return TextJsonValue( *this, tell() );
 }
References tell().
Referenced by TextJsonArray::next_value(), and read().
good()
bool TextJsonIn::good ()
Definition at line 844 of file json.cpp.
 {
     return stream->good();
 }
References stream.
Referenced by TextJsonObject::finish(), and TextJsonArray::finish().
line_number()
std::string TextJsonIn::line_number (int offset_modifier = 0)
Definition at line 1845 of file json.cpp.
 {
     const std::string name = escape_property( path ? normalize_relative_path( *path )
                              : "<unknown source file>" );
     if( stream && stream->eof() ) {
         switch( error_log_format ) {
             case error_log_format_t::human_readable:
                 return name + ":EOF";
             case error_log_format_t::github_action:
                 return "file=" + name + ",line=EOF";
         }
     } else if( !stream || stream->fail() ) {
         switch( error_log_format ) {
             case error_log_format_t::human_readable:
                 return name + ":???";
             case error_log_format_t::github_action:
                 return "file=" + name + ",line=???";
         }
     } // else stream is fine
     int pos = tell();
     int line = 1;
     int offset = 1;
     char ch;
     seek( 0 );
     for( int i = 0; i < pos + offset_modifier; ++i ) {
         stream->get( ch );
         if( !stream->good() ) {
             break;
         }
         if( ch == '\r' ) {
             offset = 1;
             ++line;
             if( peek() == '\n' ) {
                 stream->get();
                 ++i;
             }
         } else if( ch == '\n' ) {
             offset = 1;
             ++line;
         } else {
             ++offset;
         }
     }
     seek( pos );
     std::stringstream ret;
     switch( error_log_format ) {
         case error_log_format_t::human_readable:
             ret << name << ":" << line << ":" << offset;
             break;
         case error_log_format_t::github_action:
             ret.imbue( std::locale::classic() );
             ret << "file=" << name << ",line=" << line << ",col=" << offset;
             break;
     }
     return ret.str();
 }
References error_log_format, escape_property(), github_action, human_readable, line, om_direction::name(), normalize_relative_path(), path, peek(), math_opers::pos(), cata::hash64_detail::ret, seek(), stream, and tell().
Referenced by error(), and TextJsonObject::line_number().
operator=()
TextJsonIn& TextJsonIn::operator= (const TextJsonIn &) delete
peek()
char TextJsonIn::peek ()
Definition at line 840 of file json.cpp.
 {
     return static_cast<char>( stream->peek() );
 }
References stream.
Referenced by eat_whitespace(), end_array(), end_object(), line_number(), rewind(), skip_separator(), skip_value(), start_array(), start_object(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), test_string(), and uneat_whitespace().
read() [1/27]
bool TextJsonIn::read (bool & b, bool throw_on_error = false)
Definition at line 1622 of file json.cpp.
 {
     if( !test_bool() ) {
         return error_or_false( throw_on_error, "Expected bool" );
     }
     b = get_bool();
     return true;
 }
References b, error_or_false(), get_bool(), and test_bool().
Referenced by TextJsonObject::read(), TextJsonArray::read(), read(), TextJsonValue::read(), and TextJsonArray::read_next().
read() [2/27]
template<typename T , std::enable_if_t< std::is_same_v< T, item >> * = nullptr> bool TextJsonIn::read (cata::colony< T > & v, bool throw_on_error = false) inline
Definition at line 578 of file json.h.
{
             if( !test_array() ) {
                 return error_or_false( throw_on_error, "Expected json array" );
             }
             try {
                 start_array();
                 v.clear();
                 while( !end_array() ) {
                     T element;
                     const int prev_pos = tell();
                     if( test_array() ) {
                         start_array();
                         int run_l;
                         if( read( element, throw_on_error ) &&
                             read( run_l, throw_on_error ) &&
                             end_array()
                           ) { // all is good
                             // first insert (run_l-1) elements
                             for( int i = 0; i < run_l - 1; i++ ) {
                                 v.insert( element );
                             }
                             // micro-optimization, move last element
                             v.insert( std::move( element ) );
                         } else { // array is malformed, skipping it entirely
                             error_or_false( throw_on_error, "Expected end of array" );
                             seek( prev_pos );
                             skip_array();
                         }
                     } else {
                         if( read( element, throw_on_error ) ) {
                             v.insert( std::move( element ) );
                         } else {
                             skip_value();
                         }
                     }
                 }
             } catch( const JsonError & ) {
                 if( throw_on_error ) {
                     throw;
                 }
                 return false;
             }
             return true;
         }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::clear(), end_array(), error_or_false(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::insert(), read(), seek(), skip_array(), skip_value(), start_array(), tell(), and test_array().
read() [3/27]
template<typename T , std::enable_if_t< !std::is_same_v< T, item > > * = nullptr> bool TextJsonIn::read (cata::colony< T > & v, bool throw_on_error = false) inline
Definition at line 628 of file json.h.
{
             if( !test_array() ) {
                 return error_or_false( throw_on_error, "Expected json array" );
             }
             try {
                 start_array();
                 v.clear();
                 while( !end_array() ) {
                     T element;
                     if( read( element, throw_on_error ) ) {
                         v.insert( std::move( element ) );
                     } else {
                         skip_value();
                     }
                 }
             } catch( const JsonError & ) {
                 if( throw_on_error ) {
                     throw;
                 }
                 return false;
             }
             return true;
         }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::clear(), end_array(), error_or_false(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::insert(), read(), skip_value(), start_array(), and test_array().
read() [4/27]
bool TextJsonIn::read (char & c, bool throw_on_error = false)
Definition at line 1631 of file json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     c = get_int();
     return true;
 }
References c, error_or_false(), get_int(), and test_number().
read() [5/27]
bool TextJsonIn::read (double & d, bool throw_on_error = false)
Definition at line 1725 of file json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     d = get_float();
     return true;
 }
References error_or_false(), get_float(), and test_number().
read() [6/27]
template<typename T > bool TextJsonIn::read (enum_bitset< T > & v, bool throw_on_error = false) inline
Definition at line 545 of file json.h.
{
             if( !test_array() ) {
                 return error_or_false( throw_on_error, "Expected json array" );
             }
             try {
                 start_array();
                 v = {};
                 while( !end_array() ) {
                     T element;
                     if( read( element, throw_on_error ) ) {
                         if( v.test( element ) ) {
                             return error_or_false(
                                        throw_on_error,
                                        "Duplicate entry in set defined by json array" );
                         }
                         v.set( element );
                     } else {
                         skip_value();
                     }
                 }
             } catch( const JsonError & ) {
                 if( throw_on_error ) {
                     throw;
                 }
                 return false;
             }
             return true;
         }
References end_array(), error_or_false(), read(), enum_bitset< E >::set(), skip_value(), start_array(), enum_bitset< E >::test(), and test_array().
read() [7/27]
bool TextJsonIn::read (float & f, bool throw_on_error = false)
Definition at line 1716 of file json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     f = get_float();
     return true;
 }
References error_or_false(), get_float(), and test_number().
read() [8/27]
bool TextJsonIn::read (int & i, bool throw_on_error = false)
Definition at line 1680 of file json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     i = get_int();
     return true;
 }
References error_or_false(), get_int(), and test_number().
read() [9/27]
bool TextJsonIn::read (int64_t & i, bool throw_on_error = false)
read() [10/27]
template<typename T > auto TextJsonIn::read (int_id< T > & thing, bool throw_on_error = false) -> bool inline
Definition at line 368 of file json.h.
{
             std::string tmp;
             if( !read( tmp, throw_on_error ) ) {
                 return false;
             }
             thing = int_id<T>( tmp );
             return true;
         }
References read().
read() [11/27]
bool TextJsonIn::read (short int & s, bool throw_on_error = false)
Definition at line 1670 of file json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     // TODO: test for overflow
     s = get_int();
     return true;
 }
References error_or_false(), get_int(), and test_number().
read() [12/27]
bool TextJsonIn::read (short unsigned int & s, bool throw_on_error = false)
Definition at line 1660 of file json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     // TODO: test for overflow
     s = get_int();
     return true;
 }
References error_or_false(), get_int(), and test_number().
read() [13/27]
bool TextJsonIn::read (signed char & c, bool throw_on_error = false)
Definition at line 1640 of file json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     // TODO: test for overflow
     c = get_int();
     return true;
 }
References c, error_or_false(), get_int(), and test_number().
read() [14/27]
template<typename T , size_t N> bool TextJsonIn::read (std::array< T, N > & v, bool throw_on_error = false) inline
Definition at line 479 of file json.h.
{
             if( !test_array() ) {
                 return error_or_false( throw_on_error, "Expected json array" );
             }
             try {
                 start_array();
                 for( size_t i = 0; i < N; ++i ) {
                     if( end_array() ) {
                         if( throw_on_error ) {
                             error( "Json array is too short" );
                         }
                         return false; // json array is too small
                     }
                     if( !read( v[i], throw_on_error ) ) {
                         return false; // invalid entry
                     }
                 }
                 bool result = end_array();
                 if( !result && throw_on_error ) {
                     error( "Array had too many elements" );
                 }
                 return result;
             } catch( const JsonError & ) {
                 if( throw_on_error ) {
                     throw;
                 }
                 return false;
             }
         }
References end_array(), error(), error_or_false(), read(), start_array(), and test_array().
read() [15/27]
template<size_t N> bool TextJsonIn::read (std::bitset< N > & b, bool throw_on_error = false)
Definition at line 1744 of file json.cpp.
 {
     if( !test_bitset() ) {
         return error_or_false( throw_on_error, "Expected bitset" );
     }
     std::string tmp_string = get_string();
     if( tmp_string.length() > N ) {
         // If the loaded string contains more bits than expected, skip the most significant bits
         tmp_string.erase( 0, tmp_string.length() - N );
     }
     b = std::bitset<N> ( tmp_string );
     return true;
 }
References b, error_or_false(), get_string(), and test_bitset().
read() [16/27]
template<typename T , typename U > bool TextJsonIn::read (std::pair< T, U > & p, bool throw_on_error = false) inline
Overload for std::pair.
Definition at line 424 of file json.h.
{
             if( !test_array() ) {
                 return error_or_false( throw_on_error, "Expected json array encoding pair" );
             }
             try {
                 start_array();
                 bool result = !end_array() &&
                               read( p.first, throw_on_error ) &&
                               !end_array() &&
                               read( p.second, throw_on_error ) &&
                               end_array();
                 if( !result && throw_on_error ) {
                     error( "Array had wrong number of elements for pair" );
                 }
                 return result;
             } catch( const JsonError & ) {
                 if( throw_on_error ) {
                     throw;
                 }
                 return false;
             }
         }
References end_array(), error(), error_or_false(), read(), start_array(), and test_array().
read() [17/27]
bool TextJsonIn::read (std::string & s, bool throw_on_error = false)
Definition at line 1734 of file json.cpp.
 {
     if( !test_string() ) {
         return error_or_false( throw_on_error, "Expected string" );
     }
     s = get_string();
     return true;
 }
References error_or_false(), get_string(), and test_string().
read() [18/27]
template<typename T > auto TextJsonIn::read (string_id< T > & thing, bool throw_on_error = false) -> bool inline
Definition at line 357 of file json.h.
{
             std::string tmp;
             if( !read( tmp, throw_on_error ) ) {
                 return false;
             }
             thing = string_id<T>( tmp );
             return true;
         }
References read().
read() [19/27]
template<typename T , std::enable_if_t< !std::is_same_v< typename T::key_type, typename T::value_type > > * = nullptr> bool TextJsonIn::read (T & m, bool throw_on_error = true) inline
Definition at line 658 of file json.h.
{
             if( !test_object() ) {
                 return error_or_false( throw_on_error, "Expected json object" );
             }
             try {
                 start_object();
                 m.clear();
                 while( !end_object() ) {
                     using key_type = typename T::key_type;
                     key_type key = key_from_json_string<key_type>()( get_member_name() );
                     typename T::mapped_type element;
                     if( read( element, throw_on_error ) ) {
                         m[std::move( key )] = std::move( element );
                     } else {
                         skip_value();
                     }
                 }
             } catch( const JsonError & ) {
                 if( throw_on_error ) {
                     throw;
                 }
                 return false;
             }
             return true;
         }
References end_object(), error_or_false(), get_member_name(), read(), skip_value(), start_object(), and test_object().
read() [20/27]
template<typename T , std::enable_if_t< std::is_same_v< typename T::key_type, typename T::value_type >> * = nullptr> bool TextJsonIn::read (T & v, bool throw_on_error = false) inline
Definition at line 514 of file json.h.
{
             if( !test_array() ) {
                 return error_or_false( throw_on_error, "Expected json array" );
             }
             try {
                 start_array();
                 v.clear();
                 while( !end_array() ) {
                     typename T::value_type element;
                     if( read( element, throw_on_error ) ) {
                         if( !v.insert( std::move( element ) ).second ) {
                             return error_or_false(
                                        throw_on_error,
                                        "Duplicate entry in set defined by json array" );
                         }
                     } else {
                         skip_value();
                     }
                 }
             } catch( const JsonError & ) {
                 if( throw_on_error ) {
                     throw;
                 }
                 return false;
             }
             return true;
         }
References end_array(), error_or_false(), read(), skip_value(), start_array(), and test_array().
read() [21/27]
template<typename T > auto TextJsonIn::read (T & v, bool throw_on_error = false) -> decltype(deserialize(v, std::declval<const TextJsonValue &>()), true) inline
Overload that calls a global function deserialize(T&, const TextJsonValue&), if available.
Definition at line 379 of file json.h.
{
             try {
                 deserialize( v, this->get_value() );
                 return true;
             } catch( const JsonError & ) {
                 if( throw_on_error ) {
                     throw;
                 }
                 return false;
             }
         }
References deserialize(), and get_value().
read() [22/27]
template<typename T > auto TextJsonIn::read (T & v, bool throw_on_error = false) -> decltype(v.deserialize(std::declval<const TextJsonValue &>()), true) inline
Overload that calls a member function T::deserialize(const TextJsonValue&), if available.
Definition at line 394 of file json.h.
{
             try {
                 v.deserialize( this->get_value() );
                 return true;
             } catch( const JsonError & ) {
                 if( throw_on_error ) {
                     throw;
                 }
                 return false;
             }
         }
References get_value().
read() [23/27]
template<typename T , typename std::enable_if_t< !std::is_same_v< void, typename T::value_type > &&!is_string_like< T >::value > * = nullptr> auto TextJsonIn::read (T & v, bool throw_on_error = false) -> decltype(v.front(), true) inline
Definition at line 452 of file json.h.
{
             if( !test_array() ) {
                 return error_or_false( throw_on_error, "Expected json array" );
             }
             try {
                 start_array();
                 v.clear();
                 while( !end_array() ) {
                     typename T::value_type element;
                     if( read( element, throw_on_error ) ) {
                         v.push_back( std::move( element ) );
                     } else {
                         skip_value();
                     }
                 }
             } catch( const JsonError & ) {
                 if( throw_on_error ) {
                     throw;
                 }
                 return false;
             }
             return true;
         }
References end_array(), error_or_false(), read(), skip_value(), start_array(), and test_array().
read() [24/27]
template<typename T , std::enable_if_t< std::is_enum_v< T >, int > = 0> bool TextJsonIn::read (T & val, bool throw_on_error = false) inline
Definition at line 408 of file json.h.
{
             int i;
             if( read( i, false ) ) {
                 val = static_cast<T>( i );
                 return true;
             }
             std::string s;
             if( read( s, throw_on_error ) ) {
                 val = io::string_to_enum<T>( s );
                 return true;
             }
             return false;
         }
References read().
read() [25/27]
bool TextJsonIn::read (uint64_t & i, bool throw_on_error = false)
read() [26/27]
bool TextJsonIn::read (unsigned char & c, bool throw_on_error = false)
Definition at line 1650 of file json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     // TODO: test for overflow
     c = get_int();
     return true;
 }
References c, error_or_false(), get_int(), and test_number().
read() [27/27]
bool TextJsonIn::read (unsigned int & u, bool throw_on_error = false)
Definition at line 1707 of file json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     u = get_uint();
     return true;
 }
References error_or_false(), get_uint(), test_number(), and u.
read_null()
bool TextJsonIn::read_null (bool throw_on_error = false)
Definition at line 1605 of file json.cpp.
 {
     if( !test_null() ) {
         return error_or_false( throw_on_error, "Expected null" );
     }
     // NOLINTNEXTLINE(modernize-avoid-c-arrays)
     char text[5];
     if( !stream->get( text, 5 ) ) {
         error( "Unexpected end of stream reading null" );
     }
     if( 0 != strcmp( text, "null" ) ) {
         error( -4, std::string( "Expected 'null', got '" ) + text + "'" );
     }
     end_value();
     return true;
 }
References end_value(), error(), error_or_false(), stream, and test_null().
rewind()
void TextJsonIn::rewind (int max_lines = -1, int max_chars = -1)
Definition at line 2167 of file json.cpp.
 {
     if( max_lines < 0 && max_chars < 0 ) {
         // just rewind to the beginning i guess
         seek( 0 );
         return;
     }
     if( tell() == 0 ) {
         return;
     }
     int lines_found = 0;
     stream->seekg( -1, std::istream::cur );
     for( int i = 0; i < max_chars; ++i ) {
         size_t tellpos = tell();
         if( peek() == '\n' ) {
             ++lines_found;
             if( tellpos > 0 ) {
                 stream->seekg( -1, std::istream::cur );
                 if( peek() != '\r' ) {
                     stream->seekg( 1, std::istream::cur );
                 } else {
                     --tellpos;
                 }
             }
         } else if( peek() == '\r' ) {
             ++lines_found;
         }
         if( lines_found == max_lines ) {
             // don't include the last \n or \r
             if( peek() == '\n' ) {
                 stream->seekg( 1, std::istream::cur );
             } else if( peek() == '\r' ) {
                 stream->seekg( 1, std::istream::cur );
                 if( peek() == '\n' ) {
                     stream->seekg( 1, std::istream::cur );
                 }
             }
             break;
         } else if( tellpos == 0 ) {
             break;
         }
         stream->seekg( -1, std::istream::cur );
     }
 }
References peek(), seek(), stream, and tell().
Referenced by error().
sanity_check_stream()
void TextJsonIn::sanity_check_stream () private
Definition at line 828 of file json.cpp.
 {
     char c = stream->peek();
     if( c == '\xef' ) {
         error( _( "This JSON file looks like it starts with a Byte Order Mark (BOM) or is otherwise corrupted.  This can happen if you edit files in Windows Notepad.  See doc/CONTRIBUTING.md for more advice." ) );
     }
 }
References _, c, error(), and stream.
Referenced by TextJsonIn().
seek()
void TextJsonIn::seek (int pos)
Definition at line 849 of file json.cpp.
 {
     stream->clear();
     stream->seekg( pos );
     ate_separator = false;
 }
References ate_separator, math_opers::pos(), and stream.
Referenced by error(), TextJsonObject::finish(), TextJsonArray::finish(), TextJsonArray::get_array(), TextJsonObject::get_array(), TextJsonArray::get_bool(), TextJsonObject::get_bool(), get_enum_value(), TextJsonObject::get_enum_value(), TextJsonArray::get_float(), TextJsonObject::get_float(), TextJsonArray::get_int(), TextJsonObject::get_int(), TextJsonArray::get_object(), TextJsonObject::get_object(), TextJsonObject::get_raw(), TextJsonObject::get_source_location(), TextJsonArray::get_string(), TextJsonObject::get_string(), TextJsonArray::get_tags(), TextJsonObject::get_tags(), TextJsonArray::has_array(), TextJsonObject::has_array(), TextJsonArray::has_bool(), TextJsonObject::has_bool(), TextJsonArray::has_null(), TextJsonObject::has_null(), TextJsonArray::has_number(), TextJsonObject::has_number(), TextJsonArray::has_object(), TextJsonObject::has_object(), TextJsonArray::has_string(), TextJsonObject::has_string(), TextJsonObject::line_number(), line_number(), TextJsonArray::next_array(), TextJsonArray::next_bool(), TextJsonArray::next_float(), TextJsonArray::next_int(), TextJsonArray::next_object(), TextJsonArray::next_string(), TextJsonArray::next_value(), read(), TextJsonObject::read(), TextJsonArray::read(), TextJsonArray::read_next(), rewind(), TextJsonValue::seek(), TextJsonArray::string_error(), TextJsonArray::test_array(), TextJsonArray::test_bitset(), TextJsonArray::test_bool(), TextJsonArray::test_null(), TextJsonArray::test_number(), TextJsonArray::test_object(), TextJsonArray::test_string(), TextJsonIn(), TextJsonArray::throw_error(), TextJsonObject::throw_error_at(), TextJsonArray::verify_index(), and TextJsonObject::verify_position().
set_ate_separator()
void TextJsonIn::set_ate_separator (bool s) inline
Definition at line 266 of file json.h.
{
             ate_separator = s;
         }
References ate_separator.
Referenced by TextJsonObject::finish(), and TextJsonArray::finish().
skip_array()
void TextJsonIn::skip_array ()
Definition at line 999 of file json.cpp.
 {
     start_array();
     while( !end_array() ) {
         skip_value();
     }
     // end_value called by end_array
 }
References end_array(), skip_value(), and start_array().
Referenced by read(), and skip_value().
skip_false()
void TextJsonIn::skip_false ()
Definition at line 1022 of file json.cpp.
 {
     // NOLINTNEXTLINE(modernize-avoid-c-arrays)
     char text[6];
     eat_whitespace();
     stream->get( text, 6 );
     if( strcmp( text, "false" ) != 0 ) {
         std::stringstream err;
         err << R"(expected "false", but found ")" << text << "\"";
         error( -5, err.str() );
     }
     end_value();
 }
References eat_whitespace(), end_value(), error(), and stream.
Referenced by skip_value().
skip_member()
void TextJsonIn::skip_member ()
Definition at line 879 of file json.cpp.
 {
     skip_string();
     skip_pair_separator();
     skip_value();
 }
References skip_pair_separator(), skip_string(), and skip_value().
Referenced by skip_object().
skip_null()
void TextJsonIn::skip_null ()
Definition at line 1036 of file json.cpp.
 {
     // NOLINTNEXTLINE(modernize-avoid-c-arrays)
     char text[5];
     eat_whitespace();
     stream->get( text, 5 );
     if( strcmp( text, "null" ) != 0 ) {
         std::stringstream err;
         err << R"(expected "null", but found ")" << text << "\"";
         error( -4, err.str() );
     }
     end_value();
 }
References eat_whitespace(), end_value(), error(), and stream.
Referenced by TextJsonValue::get_null(), and skip_value().
skip_number()
void TextJsonIn::skip_number ()
Definition at line 1050 of file json.cpp.
 {
     char ch;
     eat_whitespace();
     // skip all of (+-0123456789.eE)
     while( stream->good() ) {
         stream->get( ch );
         if( ch != '+' && ch != '-' && ( ch < '0' || ch > '9' ) &&
             ch != 'e' && ch != 'E' && ch != '.' ) {
             stream->unget();
             break;
         }
     }
     end_value();
 }
References eat_whitespace(), end_value(), and stream.
Referenced by skip_value().
skip_object()
void TextJsonIn::skip_object ()
Definition at line 990 of file json.cpp.
 {
     start_object();
     while( !end_object() ) {
         skip_member();
     }
     // end_value called by end_object
 }
References end_object(), skip_member(), and start_object().
Referenced by skip_value().
skip_pair_separator()
void TextJsonIn::skip_pair_separator () private
Definition at line 919 of file json.cpp.
 {
     char ch;
     eat_whitespace();
     stream->get( ch );
     if( ch != ':' ) {
         std::stringstream err;
         err << "expected pair separator ':', not '" << ch << "'";
         error( -1, err.str() );
     } else if( ate_separator ) {
         error( -1, "duplicate pair separator ':' not allowed" );
     }
     ate_separator = true;
 }
References ate_separator, eat_whitespace(), error(), and stream.
Referenced by get_member_name(), and skip_member().
skip_separator()
void TextJsonIn::skip_separator () private
Definition at line 886 of file json.cpp.
 {
     eat_whitespace();
     signed char ch = peek();
     if( ch == ',' ) {
         if( ate_separator ) {
             error( "duplicate comma" );
         }
         stream->get();
         ate_separator = true;
     } else if( ch == ']' || ch == '}' || ch == ':' ) {
         // okay
         if( ate_separator ) {
             std::stringstream err;
             err << "comma should not be found before '" << ch << "'";
             uneat_whitespace();
             error( err.str() );
         }
         ate_separator = false;
     } else if( ch == EOF ) {
         // that's okay too... probably
         if( ate_separator ) {
             uneat_whitespace();
             error( "comma at end of file not allowed" );
         }
         ate_separator = false;
     } else {
         // not okay >:(
         uneat_whitespace();
         error( 1, "missing comma" );
     }
 }
References ate_separator, eat_whitespace(), error(), peek(), stream, and uneat_whitespace().
Referenced by end_value().
skip_string()
void TextJsonIn::skip_string ()
Definition at line 934 of file json.cpp.
 {
     char ch;
     eat_whitespace();
     stream->get( ch );
     if( ch != '"' ) {
         std::stringstream err;
         err << "expecting string but found '" << ch << "'";
         error( -1, err.str() );
     }
     while( stream->good() ) {
         stream->get( ch );
         if( ch == '\\' ) {
             stream->get( ch );
             continue;
         } else if( ch == '"' ) {
             break;
         } else if( ch == '\r' || ch == '\n' ) {
             error( -1, "string not closed before end of line" );
         }
     }
     end_value();
 }
References eat_whitespace(), end_value(), error(), and stream.
Referenced by skip_member(), and skip_value().
skip_true()
void TextJsonIn::skip_true ()
Definition at line 1008 of file json.cpp.
 {
     // NOLINTNEXTLINE(modernize-avoid-c-arrays)
     char text[5];
     eat_whitespace();
     stream->get( text, 5 );
     if( strcmp( text, "true" ) != 0 ) {
         std::stringstream err;
         err << R"(expected "true", but found ")" << text << "\"";
         error( -4, err.str() );
     }
     end_value();
 }
References eat_whitespace(), end_value(), error(), and stream.
Referenced by skip_value().
skip_value()
void TextJsonIn::skip_value ()
Definition at line 958 of file json.cpp.
 {
     eat_whitespace();
     char ch = peek();
     // it's either a string '"'
     if( ch == '"' ) {
         skip_string();
         // or an object '{'
     } else if( ch == '{' ) {
         skip_object();
         // or an array '['
     } else if( ch == '[' ) {
         skip_array();
         // or a number (-0123456789)
     } else if( ch == '-' || ( ch >= '0' && ch <= '9' ) ) {
         skip_number();
         // or "true", "false" or "null"
     } else if( ch == 't' ) {
         skip_true();
     } else if( ch == 'f' ) {
         skip_false();
     } else if( ch == 'n' ) {
         skip_null();
         // or an error.
     } else {
         std::stringstream err;
         err << "expected JSON value but got '" << ch << "'";
         error( err.str() );
     }
     // skip_* end value automatically
 }
References eat_whitespace(), error(), peek(), skip_array(), skip_false(), skip_null(), skip_number(), skip_object(), skip_string(), and skip_true().
Referenced by advance_jsin(), read(), skip_array(), skip_member(), TextJsonArray::TextJsonArray(), TextJsonObject::TextJsonObject(), Json::throw_error_after(), and TextJsonValue::throw_error_after().
start_array()
void TextJsonIn::start_array ()
Definition at line 1493 of file json.cpp.
 {
     eat_whitespace();
     if( peek() == '[' ) {
         stream->get();
         ate_separator = false;
         return;
     } else {
         // expecting an array, so this is an error
         std::stringstream err;
         err << "tried to start array, but found '";
         err << peek() << "', not '['";
         error( err.str() );
     }
 }
References ate_separator, eat_whitespace(), error(), peek(), and stream.
Referenced by advance_jsin(), read(), skip_array(), and TextJsonArray::TextJsonArray().
start_object()
void TextJsonIn::start_object ()
Definition at line 1526 of file json.cpp.
 {
     eat_whitespace();
     if( peek() == '{' ) {
         stream->get();
         ate_separator = false; // not that we want to
         return;
     } else {
         // expecting an object, so fail loudly
         std::stringstream err;
         err << "tried to start object, but found '";
         err << peek() << "', not '{'";
         error( err.str() );
     }
 }
References ate_separator, eat_whitespace(), error(), peek(), and stream.
Referenced by advance_jsin(), read(), skip_object(), and TextJsonObject::TextJsonObject().
string_error()
void TextJsonIn::string_error (int offset, const std::string & message)
Definition at line 2138 of file json.cpp.
 {
     if( test_string() ) {
         // skip quote mark
         stream->ignore();
         std::string s;
         std::string err;
         for( int i = 0; i < offset; ++i ) {
             if( !get_escaped_or_unicode( *stream, s, err ) ) {
                 break;
             }
         }
     }
     error( -1, message );
 }
References error(), get_escaped_or_unicode(), mapgen_defer::message, stream, and test_string().
Referenced by Json::string_error(), TextJsonArray::string_error(), and TextJsonValue::string_error().
substr()
std::string TextJsonIn::substr (size_t pos, size_t len = std::string::npos)
Definition at line 2212 of file json.cpp.
 {
     std::string ret;
     if( len == std::string::npos ) {
         stream->seekg( 0, std::istream::end );
         size_t end = tell();
         len = end - pos;
     }
     ret.resize( len );
     stream->seekg( pos );
     stream->read( ret.data(), len );
     return ret;
 }
References keycode::end, math_opers::pos(), cata::hash64_detail::ret, stream, and tell().
Referenced by TextJsonArray::str(), and TextJsonObject::str().
tell()
int TextJsonIn::tell ()
Definition at line 836 of file json.cpp.
 {
     return stream->tellg();
 }
References stream.
Referenced by error(), get_enum_value(), get_value(), line_number(), read(), rewind(), substr(), TextJsonArray::TextJsonArray(), TextJsonObject::TextJsonObject(), and uneat_whitespace().
test_array()
bool TextJsonIn::test_array ()
Definition at line 1591 of file json.cpp.
 {
     eat_whitespace();
     return peek() == '[';
 }
References eat_whitespace(), and peek().
Referenced by TextJsonArray::has_array(), TextJsonObject::has_array(), read(), TextJsonValue::test_array(), and TextJsonArray::test_array().
test_bitset()
bool TextJsonIn::test_bitset ()
Definition at line 1585 of file json.cpp.
 {
     eat_whitespace();
     return peek() == '"';
 }
References eat_whitespace(), and peek().
Referenced by read(), and TextJsonArray::test_bitset().
test_bool()
bool TextJsonIn::test_bool ()
Definition at line 1565 of file json.cpp.
 {
     eat_whitespace();
     const char ch = peek();
     return ch == 't' || ch == 'f';
 }
References eat_whitespace(), and peek().
Referenced by TextJsonArray::has_bool(), TextJsonObject::has_bool(), read(), TextJsonValue::test_bool(), and TextJsonArray::test_bool().
test_float()
bool TextJsonIn::test_float () inline
Definition at line 328 of file json.h.
{
             return test_number();
         }
References test_number().
Referenced by TextJsonValue::test_float().
test_int()
bool TextJsonIn::test_int () inline
Definition at line 325 of file json.h.
{
             return test_number();
         }
References test_number().
Referenced by TextJsonValue::test_int().
test_null()
bool TextJsonIn::test_null ()
Definition at line 1559 of file json.cpp.
 {
     eat_whitespace();
     return peek() == 'n';
 }
References eat_whitespace(), and peek().
Referenced by TextJsonArray::has_null(), TextJsonObject::has_null(), read_null(), TextJsonValue::test_null(), and TextJsonArray::test_null().
test_number()
bool TextJsonIn::test_number ()
Definition at line 1572 of file json.cpp.
 {
     eat_whitespace();
     const char ch = peek();
     return ch == '-' || ch == '+' || ch == '.' || ( ch >= '0' && ch <= '9' );
 }
References eat_whitespace(), and peek().
Referenced by TextJsonArray::has_number(), TextJsonObject::has_number(), read(), test_float(), test_int(), and TextJsonArray::test_number().
test_object()
bool TextJsonIn::test_object ()
Definition at line 1597 of file json.cpp.
 {
     eat_whitespace();
     return peek() == '{';
 }
References eat_whitespace(), and peek().
Referenced by TextJsonArray::has_object(), TextJsonObject::has_object(), read(), TextJsonValue::test_object(), and TextJsonArray::test_object().
test_string()
bool TextJsonIn::test_string ()
Definition at line 1579 of file json.cpp.
 {
     eat_whitespace();
     return peek() == '"';
 }
References eat_whitespace(), and peek().
Referenced by TextJsonArray::get_tags(), TextJsonObject::get_tags(), TextJsonArray::has_string(), TextJsonObject::has_string(), read(), string_error(), TextJsonValue::test_string(), and TextJsonArray::test_string().
uneat_whitespace()
void TextJsonIn::uneat_whitespace ()
Definition at line 863 of file json.cpp.
 {
     while( tell() > 0 ) {
         stream->seekg( -1, std::istream::cur );
         if( !is_whitespace( peek() ) ) {
             break;
         }
     }
 }
References is_whitespace(), peek(), stream, and tell().
Referenced by end_array(), end_object(), and skip_separator().
Member Data Documentation
ate_separator
bool TextJsonIn::ate_separator = false private
Definition at line 245 of file json.h.
Referenced by end_array(), end_object(), end_value(), get_ate_separator(), seek(), set_ate_separator(), skip_pair_separator(), skip_separator(), start_array(), and start_object().
path
shared_ptr_fast<std::string> TextJsonIn::path private
Definition at line 244 of file json.h.
Referenced by get_path(), and line_number().
stream
std::istream* TextJsonIn::stream private
Definition at line 243 of file json.h.
Referenced by eat_whitespace(), end_array(), end_object(), error(), get_any_number(), get_bool(), get_string(), good(), line_number(), peek(), read_null(), rewind(), sanity_check_stream(), seek(), skip_false(), skip_null(), skip_number(), skip_pair_separator(), skip_separator(), skip_string(), skip_true(), start_array(), start_object(), string_error(), substr(), tell(), and uneat_whitespace().
The documentation for this class was generated from the following files:
src/json.h
src/json.cpp