Cataclysm DDA: lru_cache< Key, Value > Class Template Reference
lru_cache< Key, Value > Class Template Reference
#include <lru_cache.h>
Public Types
using Pair = std::pair< Key, Value >
Public Member Functions
Value get (const Key &, const Value &default_) const
void insert (int limit, const Key &, const Value &)
void remove (const Key &)
void clear ()
Protected Member Functions
void trim (int limit)
void touch (typename std::list< Pair >::iterator iter) const
Protected Attributes
std::list< Pair > ordered_list
std::unordered_map< Key, typename std::list< Pair >::iterator > map
Detailed Description
template<typename Key, typename Value>
class lru_cache< Key, Value >
Definition at line 10 of file lru_cache.h.
Member Typedef Documentation
Pair
template<typename Key , typename Value > using lru_cache< Key, Value >::Pair = std::pair<Key, Value>
Definition at line 13 of file lru_cache.h.
Member Function Documentation
clear()
template<typename Key , typename Value > void lru_cache< Key, Value >::clear inline
Definition at line 82 of file lru_cache.h.
 {
     map.clear();
     ordered_list.clear();
 }
Referenced by map::build_map_cache(), and npc::reboot().
get()
template<typename Key , typename Value > Value lru_cache< Key, Value >::get (const Key & pos, const Value & default_) const inline
Definition at line 28 of file lru_cache.h.
 {
     if( const auto found = this->map.find( pos ); found != this->map.end() ) {
         const auto list_iter = found->second;
         this->touch( list_iter );
         return list_iter->second;
     }
     return default_;
 }
References default_, map::map(), and math_opers::pos().
Referenced by npc::find_item(), map::has_potential_los(), and map::sees().
insert()
template<typename Key , typename Value > void lru_cache< Key, Value >::insert (int limit, const Key & pos, const Value & t) inline
Definition at line 48 of file lru_cache.h.
 {
     auto found = map.find( pos );
     if( found == map.end() ) {
         // Need new entry in map.  Make the new list entry and point to it.
         ordered_list.emplace_back( pos, t );
         map.emplace( pos, std::prev( ordered_list.end() ) );
         trim( limit );
     } else {
         // Splice existing entry to the back.  Does not invalidate the
         // iterator, so no need to change the map.
         auto list_iterator = found->second;
         touch( list_iterator );
         // Update the moved item
         list_iterator->second = t;
     }
 }
References math_opers::pos(), and trim().
Referenced by npc::find_item(), and map::sees().
remove()
template<typename Key , typename Value > void lru_cache< Key, Value >::remove (const Key & pos) inline
Definition at line 39 of file lru_cache.h.
 {
     if( const auto found = map.find( pos ); found != map.end() ) {
         ordered_list.erase( found->second );
         map.erase( found );
     }
 }
References math_opers::pos().
touch()
template<typename Key , typename Value > void lru_cache< Key, Value >::touch (typename std::list< Pair >::iterator iter) const inline protected
Definition at line 76 of file lru_cache.h.
 {
     ordered_list.splice( ordered_list.end(), ordered_list, iter );
 }
trim()
template<typename Key , typename Value > void lru_cache< Key, Value >::trim (int limit) inline protected
Definition at line 67 of file lru_cache.h.
 {
     while( map.size() > static_cast<size_t>( limit ) ) {
         map.erase( ordered_list.front().first );
         ordered_list.pop_front();
     }
 }
Member Data Documentation
map
template<typename Key , typename Value > std::unordered_map<Key, typename std::list<Pair>::iterator> lru_cache< Key, Value >::map protected
Definition at line 24 of file lru_cache.h.
ordered_list
template<typename Key , typename Value > std::list<Pair> lru_cache< Key, Value >::ordered_list mutable protected
Definition at line 23 of file lru_cache.h.
The documentation for this class was generated from the following file:
src/lru_cache.h