Cataclysm DDA: map_item_stack Class Reference
map_item_stack Class Reference
#include <map_item_stack.h>
Classes
class item_group
Public Member Functions
map_item_stack ()
map_item_stack (const item *it, const tripoint &pos)
void add_at_pos (const item *it, const tripoint &pos)
Static Public Member Functions
static bool map_item_stack_sort (const map_item_stack &lhs, const map_item_stack &rhs)
Public Attributes
const item * example
std::vector< item_group > vIG
int totalcount
Detailed Description
Definition at line 12 of file map_item_stack.h.
Constructor & Destructor Documentation
map_item_stack() [1/2]
map_item_stack::map_item_stack ()
Definition at line 22 of file map_item_stack.cpp.
                                : example( nullptr ), totalcount( 0 )
 {
     vIG.emplace_back( );
 }
References vIG.
map_item_stack() [2/2]
map_item_stack::map_item_stack (const item * it, const tripoint & pos)
Definition at line 27 of file map_item_stack.cpp.
                                                                           : example( it ),
     totalcount( it->count() )
 {
     vIG.emplace_back( pos, totalcount, it );
 }
References math_opers::pos(), totalcount, and vIG.
Member Function Documentation
add_at_pos()
void map_item_stack::add_at_pos (const item * it, const tripoint & pos)
Definition at line 33 of file map_item_stack.cpp.
 {
     const int amount = it->count();
     if( vIG.empty() || vIG.back().pos != pos ) {
         vIG.emplace_back( pos, amount, it );
     } else {
         vIG.back().count += amount;
     }
     totalcount += amount;
 }
References item::count(), math_opers::pos(), totalcount, and vIG.
map_item_stack_sort()
bool map_item_stack::map_item_stack_sort (const map_item_stack & lhs, const map_item_stack & rhs) static
Definition at line 46 of file map_item_stack.cpp.
 {
     const item_category &lhs_cat = lhs.example->get_category_of_contents();
     const item_category &rhs_cat = rhs.example->get_category_of_contents();
     if( lhs_cat == rhs_cat ) {
         return square_dist( tripoint_zero, lhs.vIG[0].pos ) <
                square_dist( tripoint_zero, rhs.vIG[0].pos );
     }
     return lhs_cat < rhs_cat;
 }
References example, item::get_category_of_contents(), square_dist(), tripoint_zero, and vIG.
Referenced by game::list_items().
Member Data Documentation
example
const item* map_item_stack::example
Definition at line 27 of file map_item_stack.h.
Referenced by game::list_items(), and map_item_stack_sort().
totalcount
int map_item_stack::totalcount
Definition at line 29 of file map_item_stack.h.
Referenced by add_at_pos(), and map_item_stack().
vIG
std::vector<item_group> map_item_stack::vIG
Definition at line 28 of file map_item_stack.h.
Referenced by add_at_pos(), game::list_items(), map_item_stack(), and map_item_stack_sort().
The documentation for this class was generated from the following files:
src/map_item_stack.h
src/map_item_stack.cpp