Cataclysm DDA: heal_actor Class Reference
heal_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
int get_heal_value (const Character &healer, bodypart_id healed) const
How much hp would healer heal using this actor on healed body part.
int get_bandaged_level (const Character &healer) const
How many intensity levels will be applied using this actor by healer.
int get_disinfected_level (const Character &healer) const
How many intensity levels will be applied using this actor by healer.
int get_stopbleed_level (const Character &healer) const
How many intensity levels of bleeding will be reduced using this actor by healer.
int finish_using (Character &healer, Character &patient, item &it, bodypart_id healed) const
Does the actual healing.
bodypart_id use_healing_item (Character &healer, Character &patient, item &it, bool force) const
heal_actor (const std::string &type="heal")
~heal_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
float limb_power = 0.0f
How much hp to restore when healing limbs?
float head_power = 0.0f
How much hp to restore when healing head?
float torso_power = 0.0f
How much hp to restore when healing torso?
float bandages_power = 0.0f
How many intensity levels will be applied when healing limbs?
float bandages_scaling = 0.0f
Extra intensity levels gained per skill level when healing limbs.
float disinfectant_power = 0.0f
How many intensity levels will be applied when healing limbs?
float disinfectant_scaling = 0.0f
Extra intensity levels gained per skill level when healing limbs.
int bleed = 0
How many levels of bleeding effect intensity can it remove (dressing efficiency).
float bite = 0.0f
Chance to remove bite effect.
float infect = 0.0f
Chance to remove infected effect.
int move_cost = 100
Cost in moves to use the item.
float limb_scaling = 0.0f
Extra hp gained per skill level when healing limbs.
float head_scaling = 0.0f
Extra hp gained per skill level when healing head.
float torso_scaling = 0.0f
Extra hp gained per skill level when healing torso.
std::vector< effect_data > effects
Effects to apply to patient on finished healing.
itype_id used_up_item_id
Item produced on finished healing.
int used_up_item_quantity = 1
int used_up_item_charges = 1
std::set< flag_id > used_up_item_flags
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 863 of file iuse_actor.h.
Constructor & Destructor Documentation
heal_actor()
heal_actor::heal_actor (const std::string & type = "heal") inline explicit
Definition at line 919 of file iuse_actor.h.
 : iuse_actor( type ) {}
~heal_actor()
heal_actor::~heal_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > heal_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 3351 of file iuse_actor.cpp.
 {
     return std::make_unique<heal_actor>( *this );
 }
finish_using()
int heal_actor::finish_using (Character & healer, Character & patient, item & it, bodypart_id healed) const
Does the actual healing.
Returns charges used.
Definition at line 3433 of file iuse_actor.cpp.
 {
     float practice_amount = limb_power * 3.0f;
     const int dam = get_heal_value( healer, healed );
     const int cur_hp = patient.get_part_hp_cur( healed );
     if( ( cur_hp >= 1 ) && ( dam > 0 ) ) { // Prevent first-aid from mending limbs
         patient.heal( healed, dam );
     } else if( ( cur_hp >= 1 ) && ( dam < 0 ) ) {
         patient.apply_damage( nullptr, healed, -dam ); //hurt takes + damage
     }
     Character &player_character = get_player_character();
     const bool u_see = healer.is_avatar() || patient.is_avatar() ||
                        player_character.sees( healer ) || player_character.sees( patient );
     const bool player_healing_player = healer.is_avatar() && patient.is_avatar();
     // Need a helper here - messages are from healer's point of view
     // but it would be cool if NPCs could use this function too
     const auto heal_msg = [&]( game_message_type msg_type,
     const char *player_player_msg, const char *other_msg ) {
         if( !u_see ) {
             return;
         }
         if( player_healing_player ) {
             add_msg( msg_type, player_player_msg );
         } else {
             add_msg( msg_type, other_msg );
         }
     };
     if( patient.has_effect( effect_bleed, healed ) ) {
         // small band-aids won't stop big arterial bleeding, but with tourniquet they just might
         int pwr = 3 * get_stopbleed_level( healer );
         if( patient.worn_with_flag( flag_TOURNIQUET,  healed ) ) {
             pwr *= 2;
         }
         if( pwr > patient.get_effect_int( effect_bleed, healed ) ) {
             effect &wound = patient.get_effect( effect_bleed, healed );
             time_duration dur = wound.get_duration() - ( get_stopbleed_level( healer ) *
                                 wound.get_int_dur_factor() );
             wound.set_duration( std::max( 0_turns, dur ) );
             if( wound.get_duration() == 0_turns ) {
                 heal_msg( m_good, _( "You stop the bleeding." ), _( "The bleeding is stopped." ) );
             } else {
                 heal_msg( m_good, _( "You reduce the bleeding, but it's not stopped yet." ),
                           _( "The bleeding is reduced, but not stopped." ) );
             }
         } else {
             heal_msg( m_warning,
                       _( "Your dressing is too ineffective for a bleeding of this extent, and you fail to stop it." ),
                       _( "The wound still bleeds." ) );
         }
         practice_amount += bleed / 3.0f;
     }
     if( patient.has_effect( effect_bite, healed ) ) {
         if( x_in_y( bite, 1.0f ) ) {
             patient.remove_effect( effect_bite, healed );
             heal_msg( m_good, _( "You clean the wound." ), _( "The wound is cleaned." ) );
         } else {
             heal_msg( m_warning, _( "Your wound still aches." ), _( "The wound still looks bad." ) );
         }
         practice_amount += bite * 3.0f;
     }
     if( patient.has_effect( effect_infected, healed ) ) {
         if( x_in_y( infect, 1.0f ) ) {
             const time_duration infected_dur = patient.get_effect_dur( effect_infected, healed );
             patient.remove_effect( effect_infected, healed );
             patient.add_effect( effect_recover, infected_dur );
             heal_msg( m_good, _( "You disinfect the wound." ), _( "The wound is disinfected." ) );
         } else {
             heal_msg( m_warning, _( "Your wound still hurts." ), _( "The wound still looks nasty." ) );
         }
         practice_amount += infect * 10.0f;
     }
     healer.add_msg_if_player( _( "You finish using the %s." ), it.tname() );
     if( u_see && !healer.is_avatar() ) {
         //~ Healing complete message. %1$s is healer name, %2$s is item name.
         add_msg( _( "%1$s finishes using the %2$s." ), healer.disp_name(), it.tname() );
     }
     for( const effect_data &eff : effects ) {
         patient.add_effect( eff.id, eff.duration, eff.bp, eff.permanent );
     }
     if( !used_up_item_id.is_empty() ) {
         // If the item is a tool, `make` it the new form
         // Otherwise it probably was consumed, so create a new one
         if( it.is_tool() ) {
             it.convert( used_up_item_id, &healer );
             for( const auto &flag : used_up_item_flags ) {
                 it.set_flag( flag );
             }
         } else {
             item used_up( used_up_item_id, it.birthday() );
             used_up.charges = used_up_item_charges;
             for( const auto &flag : used_up_item_flags ) {
                 used_up.set_flag( flag );
             }
             healer.i_add_or_drop( used_up, used_up_item_quantity );
         }
     }
     // apply healing over time effects
     if( bandages_power > 0 ) {
         int bandages_intensity = get_bandaged_level( healer );
         patient.add_effect( effect_bandaged, 1_turns, healed );
         effect &e = patient.get_effect( effect_bandaged, healed );
         e.set_duration( e.get_int_dur_factor() * ( bandages_intensity + 0.5f ) );
         patient.set_part_damage_bandaged( healed,
                                           patient.get_part_hp_max( healed ) - patient.get_part_hp_cur( healed ) );
         practice_amount += 2 * bandages_intensity;
     }
     if( disinfectant_power > 0 ) {
         int disinfectant_intensity = get_disinfected_level( healer );
         patient.add_effect( effect_disinfected, 1_turns, healed );
         effect &e = patient.get_effect( effect_disinfected, healed );
         e.set_duration( e.get_int_dur_factor() * ( disinfectant_intensity + 0.5f ) );
         patient.set_part_damage_disinfected( healed,
                                              patient.get_part_hp_max( healed ) - patient.get_part_hp_cur( healed ) );
         practice_amount += 2 * disinfectant_intensity;
     }
     practice_amount = std::max( 9.0f, practice_amount );
     healer.practice( skill_firstaid, static_cast<int>( practice_amount ) );
     healer.practice_proficiency( proficiency_prof_wound_care,
                                  time_duration::from_turns( practice_amount ) );
     healer.practice_proficiency( proficiency_prof_wound_care_expert,
                                  time_duration::from_turns( practice_amount ) );
     return 1;
 }
References _, Creature::add_effect(), add_msg(), Character::add_msg_if_player(), Character::apply_damage(), bandages_power, item::birthday(), bite, bleed, item::charges, item::convert(), disinfectant_power, Character::disp_name(), dur, effect_bandaged, effect_bite, effect_bleed, effect_disinfected, effect_infected, effect_recover, effects, flag_TOURNIQUET, time_duration::from_turns(), get_bandaged_level(), get_disinfected_level(), effect::get_duration(), Creature::get_effect(), Creature::get_effect_dur(), Creature::get_effect_int(), get_heal_value(), effect::get_int_dur_factor(), Creature::get_part_hp_cur(), Creature::get_part_hp_max(), get_player_character(), get_stopbleed_level(), Creature::has_effect(), Character::heal(), Character::i_add_or_drop(), infect, Creature::is_avatar(), string_id< T >::is_empty(), item::is_tool(), limb_power, m_good, m_warning, max(), Character::practice(), Character::practice_proficiency(), proficiency_prof_wound_care, proficiency_prof_wound_care_expert, Creature::remove_effect(), Character::sees(), effect::set_duration(), item::set_flag(), Creature::set_part_damage_bandaged(), Creature::set_part_damage_disinfected(), skill_firstaid, item::tname(), used_up_item_charges, used_up_item_flags, used_up_item_id, used_up_item_quantity, Character::worn_with_flag(), and x_in_y().
Referenced by firstaid_activity_actor::finish().
get_bandaged_level()
int heal_actor::get_bandaged_level (const Character & healer) const
How many intensity levels will be applied using this actor by healer.
Firstaid increases healing item effects
Definition at line 3379 of file iuse_actor.cpp.
 {
     if( bandages_power > 0 ) {
         float prof_bonus = healer.get_skill_level( skill_firstaid );
         prof_bonus = healer.has_proficiency( proficiency_prof_wound_care ) ?
                      prof_bonus + 1 : prof_bonus;
         prof_bonus = healer.has_proficiency( proficiency_prof_wound_care_expert ) ?
                      prof_bonus + 2 : prof_bonus;
         /** @EFFECT_FIRSTAID increases healing item effects */
         float total_bonus = bandages_power + bandages_scaling * prof_bonus;
         total_bonus = healer.enchantment_cache->modify_value( enchant_vals::mod::BANDAGE_BONUS,
                       total_bonus );
         return round( total_bonus );
     }
     return bandages_power;
 }
References enchant_vals::BANDAGE_BONUS, bandages_power, bandages_scaling, Character::enchantment_cache, Character::get_skill_level(), Character::has_proficiency(), proficiency_prof_wound_care, proficiency_prof_wound_care_expert, round(), and skill_firstaid.
Referenced by finish_using(), info(), and use_healing_item().
get_disinfected_level()
int heal_actor::get_disinfected_level (const Character & healer) const
How many intensity levels will be applied using this actor by healer.
Firstaid increases healing item effects
Definition at line 3397 of file iuse_actor.cpp.
 {
     if( disinfectant_power > 0 ) {
         /** @EFFECT_FIRSTAID increases healing item effects */
         float prof_bonus = healer.get_skill_level( skill_firstaid );
         prof_bonus = healer.has_proficiency( proficiency_prof_wound_care ) ?
                      prof_bonus + 1 : prof_bonus;
         prof_bonus = healer.has_proficiency( proficiency_prof_wound_care_expert ) ?
                      prof_bonus + 2 : prof_bonus;
         float total_bonus = disinfectant_power + disinfectant_scaling * prof_bonus;
         total_bonus = healer.enchantment_cache->modify_value( enchant_vals::mod::DISINFECTANT_BONUS,
                       total_bonus );
         return round( total_bonus );
     }
     return disinfectant_power;
 }
References enchant_vals::DISINFECTANT_BONUS, disinfectant_power, disinfectant_scaling, Character::enchantment_cache, Character::get_skill_level(), Character::has_proficiency(), proficiency_prof_wound_care, proficiency_prof_wound_care_expert, round(), and skill_firstaid.
Referenced by finish_using(), info(), and use_healing_item().
get_heal_value()
int heal_actor::get_heal_value (const Character & healer, bodypart_id healed) const
How much hp would healer heal using this actor on healed body part.
Firstaid increases healing item effects
Definition at line 3356 of file iuse_actor.cpp.
 {
     int heal_base;
     float bonus_mult;
     if( healed == bodypart_id( "head" ) ) {
         heal_base = head_power;
         bonus_mult = head_scaling;
     } else if( healed == bodypart_id( "torso" ) ) {
         heal_base = torso_power;
         bonus_mult = torso_scaling;
     } else {
         heal_base = limb_power;
         bonus_mult = limb_scaling;
     }
     if( heal_base > 0 ) {
         /** @EFFECT_FIRSTAID increases healing item effects */
         return round( heal_base + bonus_mult * healer.get_skill_level( skill_firstaid ) );
     }
     return heal_base;
 }
References Character::get_skill_level(), head_power, head_scaling, limb_power, limb_scaling, round(), skill_firstaid, torso_power, and torso_scaling.
Referenced by finish_using(), info(), and use_healing_item().
get_stopbleed_level()
int heal_actor::get_stopbleed_level (const Character & healer) const
How many intensity levels of bleeding will be reduced using this actor by healer.
Firstaid increases healing item effects
Definition at line 3415 of file iuse_actor.cpp.
 {
     if( bleed > 0 ) {
         /** @EFFECT_FIRSTAID increases healing item effects */
         float prof_bonus = healer.get_skill_level( skill_firstaid ) / 2;
         prof_bonus = healer.has_proficiency( proficiency_prof_wound_care ) ?
                      prof_bonus + 1 : prof_bonus;
         prof_bonus = healer.has_proficiency( proficiency_prof_wound_care_expert ) ?
                      prof_bonus + 2 : prof_bonus;
         float total_bonus = bleed * prof_bonus;
         total_bonus = healer.enchantment_cache->modify_value( enchant_vals::mod::BLEED_STOP_BONUS,
                       total_bonus );
         return round( total_bonus );
     }
     return bleed;
 }
References bleed, enchant_vals::BLEED_STOP_BONUS, Character::enchantment_cache, Character::get_skill_level(), Character::has_proficiency(), proficiency_prof_wound_care, proficiency_prof_wound_care_expert, round(), and skill_firstaid.
Referenced by finish_using(), info(), and use_healing_item().
info()
void heal_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 3692 of file iuse_actor.cpp.
 {
     if( head_power > 0 || torso_power > 0 || limb_power > 0 || bandages_power > 0 ||
         disinfectant_power > 0 || bleed > 0 || bite > 0.0f || infect > 0.0f ) {
         dump.emplace_back( "HEAL", _( "<bold>Healing effects</bold> " ) );
     }
     Character &player_character = get_player_character();
     if( head_power > 0 || torso_power > 0 || limb_power > 0 ) {
         dump.emplace_back( "HEAL", _( "Base healing: " ) );
         dump.emplace_back( "HEAL_BASE", _( "Head: " ), "", iteminfo::no_newline, head_power );
         dump.emplace_back( "HEAL_BASE", _( "  Torso: " ), "", iteminfo::no_newline, torso_power );
         dump.emplace_back( "HEAL_BASE", _( "  Limbs: " ), limb_power );
         if( g != nullptr ) {
             dump.emplace_back( "HEAL", _( "Actual healing: " ) );
             dump.emplace_back( "HEAL_ACT", _( "Head: " ), "", iteminfo::no_newline,
                                get_heal_value( player_character, bodypart_id( "head" ) ) );
             dump.emplace_back( "HEAL_ACT", _( "  Torso: " ), "", iteminfo::no_newline,
                                get_heal_value( player_character, bodypart_id( "torso" ) ) );
             dump.emplace_back( "HEAL_ACT", _( "  Limbs: " ), get_heal_value( player_character,
                                bodypart_id( "arm_l" ) ) );
         }
     }
     if( bandages_power > 0 ) {
         dump.emplace_back( "HEAL", _( "Base bandaging quality: " ),
                            texitify_base_healing_power( static_cast<int>( bandages_power ) ) );
         if( g != nullptr ) {
             dump.emplace_back( "HEAL", _( "Actual bandaging quality: " ),
                                texitify_healing_power( get_bandaged_level( player_character ) ) );
         }
     }
     if( disinfectant_power > 0 ) {
         dump.emplace_back( "HEAL", _( "Base disinfecting quality: " ),
                            texitify_base_healing_power( static_cast<int>( disinfectant_power ) ) );
         if( g != nullptr ) {
             dump.emplace_back( "HEAL", _( "Actual disinfecting quality: " ),
                                texitify_healing_power( get_disinfected_level( player_character ) ) );
         }
     }
     if( bleed > 0 ) {
         dump.emplace_back( "HEAL", _( "Effect on bleeding: " ), texitify_bandage_power( bleed ) );
         if( g != nullptr ) {
             dump.emplace_back( "HEAL", _( "Actual effect on bleeding: " ),
                                texitify_healing_power( get_stopbleed_level( get_player_character() ) ) );
         }
     }
     if( bite > 0.0f || infect > 0.0f ) {
         dump.emplace_back( "HEAL", _( "Chance to heal (percent): " ) );
         if( bite > 0.0f ) {
             dump.emplace_back( "HEAL", _( "* Bite: " ),
                                static_cast<int>( bite * 100 ) );
         }
         if( infect > 0.0f ) {
             dump.emplace_back( "HEAL", _( "* Infection: " ),
                                static_cast<int>( infect * 100 ) );
         }
     }
     dump.emplace_back( "HEAL", _( "Moves to use: " ), move_cost );
 }
References _, bandages_power, bite, bleed, disinfectant_power, g, get_bandaged_level(), get_disinfected_level(), get_heal_value(), get_player_character(), get_stopbleed_level(), head_power, infect, limb_power, move_cost, iteminfo::no_newline, texitify_bandage_power(), texitify_base_healing_power(), texitify_healing_power(), and torso_power.
load()
void heal_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 3257 of file iuse_actor.cpp.
 {
     // Mandatory
     move_cost = obj.get_int( "move_cost" );
     limb_power = obj.get_float( "limb_power", 0 );
     // Optional
     bandages_power = obj.get_float( "bandages_power", 0 );
     bandages_scaling = obj.get_float( "bandages_scaling", 0.25f * bandages_power );
     disinfectant_power = obj.get_float( "disinfectant_power", 0 );
     disinfectant_scaling = obj.get_float( "disinfectant_scaling", 0.25f * disinfectant_power );
     head_power = obj.get_float( "head_power", 0.8f * limb_power );
     torso_power = obj.get_float( "torso_power", 1.5f * limb_power );
     limb_scaling = obj.get_float( "limb_scaling", 0.25f * limb_power );
     double scaling_ratio = limb_power < 0.0001f ? 0.0 :
                            static_cast<double>( limb_scaling / limb_power );
     head_scaling = obj.get_float( "head_scaling", scaling_ratio * head_power );
     torso_scaling = obj.get_float( "torso_scaling", scaling_ratio * torso_power );
     bleed = obj.get_int( "bleed", 0 );
     bite = obj.get_float( "bite", 0.0f );
     infect = obj.get_float( "infect", 0.0f );
     if( obj.has_array( "effects" ) ) {
         for( const JsonObject e : obj.get_array( "effects" ) ) {
             effects.push_back( load_effect_data( e ) );
         }
     }
     if( obj.has_string( "used_up_item" ) ) {
         obj.read( "used_up_item", used_up_item_id, true );
     } else if( obj.has_object( "used_up_item" ) ) {
         JsonObject u = obj.get_object( "used_up_item" );
         u.read( "id", used_up_item_id, true );
         used_up_item_quantity = u.get_int( "quantity", used_up_item_quantity );
         used_up_item_charges = u.get_int( "charges", used_up_item_charges );
         used_up_item_flags = u.get_tags<flag_id>( "flags" );
     }
 }
References bandages_power, bandages_scaling, bite, bleed, disinfectant_power, disinfectant_scaling, effects, JsonObject::get_array(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::has_array(), JsonObject::has_object(), JsonObject::has_string(), head_power, head_scaling, infect, limb_power, limb_scaling, load_effect_data(), move_cost, JsonObject::read(), torso_power, torso_scaling, u, used_up_item_charges, used_up_item_flags, used_up_item_id, and used_up_item_quantity.
use()
std::optional< int > heal_actor::use (Character * p, item & it, const tripoint & pos) const override virtual
Implements iuse_actor.
Definition at line 3315 of file iuse_actor.cpp.
 {
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( it.is_filthy() ) {
         p->add_msg_if_player( m_info, _( "You can't use filthy items for healing." ) );
         return std::nullopt;
     }
     Character &patient = get_patient( *p, pos );
     const bodypart_str_id hpp = use_healing_item( *p, patient, it, false ).id();
     if( hpp == bodypart_str_id::NULL_ID() ) {
         return std::nullopt;
     }
     // each tier of proficiency cuts required time by half
     int cost = move_cost;
     cost = p->has_proficiency( proficiency_prof_wound_care_expert ) ? cost / 2 : cost;
     cost = p->has_proficiency( proficiency_prof_wound_care ) ? cost / 2 : cost;
     p->assign_activity( firstaid_activity_actor( cost, it.tname(), patient.getID() ) );
     // Player: Only time this item_location gets used in firstaid::finish() is when activating the item's
     // container from the inventory window, so an item_on_person impl is all that is needed.
     // Otherwise the proper item_location provided by menu selection supercedes it in consume::finish().
     // NPC: Will only use its inventory for first aid items.
     p->activity.targets.emplace_back( *p, &it );
     p->activity.str_values.emplace_back( hpp.c_str() );
     p->set_moves( 0 );
     return 0;
 }
References _, Character::activity, Character::add_msg_if_player(), Character::assign_activity(), string_id< T >::c_str(), Character::cant_do_mounted(), Creature::cant_do_underwater(), iuse_actor::cost, get_patient(), Character::getID(), Character::has_proficiency(), int_id< T >::id(), item::is_filthy(), m_info, move_cost, string_id< body_part_type >::NULL_ID(), math_opers::pos(), proficiency_prof_wound_care, proficiency_prof_wound_care_expert, Creature::set_moves(), player_activity::str_values, player_activity::targets, item::tname(), and use_healing_item().
use_healing_item()
bodypart_id heal_actor::use_healing_item (Character & healer, Character & patient, item & it, bool force) const
Definition at line 3624 of file iuse_actor.cpp.
 {
     bodypart_id healed = bodypart_id( "bp_null" );
     const int head_bonus = get_heal_value( healer, bodypart_id( "head" ) );
     const int limb_power = get_heal_value( healer, bodypart_id( "arm_l" ) );
     const int torso_bonus = get_heal_value( healer, bodypart_id( "torso" ) );
     if( !patient.can_use_heal_item( it ) ) {
         patient.add_msg_player_or_npc( m_bad,
                                        _( "Your biology is not compatible with that item." ),
                                        _( "<npcname>'s biology is not compatible with that item." ) );
         return bodypart_id( "bp_null" ); // canceled
     }
     if( healer.is_npc() ) {
         // NPCs heal whatever has sustained the most damage that they can heal but don't
         // rebandage parts unless they are bleeding significantly
         int highest_damage = 0;
         for( bodypart_id part_id : patient.get_all_body_parts( get_body_part_flags::only_main ) ) {
             int damage = 0;
             if( ( !patient.has_effect( effect_bandaged, part_id ) && bandages_power > 0 ) ||
                 ( !patient.has_effect( effect_disinfected, part_id ) && disinfectant_power > 0 ) ) {
                 damage += patient.get_part_hp_max( part_id ) - patient.get_part_hp_cur( part_id );
                 damage += infect * patient.get_effect_dur( effect_infected, part_id ) / 10_minutes;
             }
             if( patient.get_effect_int( effect_bleed, part_id ) > 5 && bleed > 0 ) {
                 damage += bleed * patient.get_effect_dur( effect_bleed, part_id ) / 5_minutes;
             }
             if( patient.has_effect( effect_bite, part_id ) && disinfectant_power > 0 ) {
                 damage += bite * patient.get_effect_dur( effect_bite, part_id ) / 1_minutes;
             }
             if( damage > highest_damage ) {
                 highest_damage = damage;
                 healed = part_id;
             }
         }
     } else if( patient.is_avatar() ) {
         // Player healing self - let player select
         if( healer.activity.id() != ACT_FIRSTAID ) {
             const std::string menu_header = _( "Select a body part for: " ) + it.tname();
             healed = pick_part_to_heal( healer, patient, menu_header, limb_power, head_bonus, torso_bonus,
                                         get_stopbleed_level( healer ), bite, infect, force, get_bandaged_level( healer ),
                                         get_disinfected_level( healer ) );
             if( healed == bodypart_id( "bp_null" ) ) {
                 add_msg( m_info, _( "Never mind." ) );
                 return bodypart_id( "bp_null" ); // canceled
             }
             return healed;
         } else {
             // Completed activity, extract body part from it.
             healed =  bodypart_id( healer.activity.str_values[0] );
         }
     } else {
         // Player healing NPC
         // TODO: Remove this hack, allow using activities on NPCs
         const std::string menu_header = string_format( pgettext( "healing",
                                         //~ %1$s: patient name, %2$s: healing item name
                                         "Select a body part of %1$s for %2$s:" ),
                                         patient.disp_name(), it.tname() );
         healed = pick_part_to_heal( healer, patient, menu_header, limb_power, head_bonus, torso_bonus,
                                     get_stopbleed_level( healer ), bite, infect, force, get_bandaged_level( healer ),
                                     get_disinfected_level( healer ) );
     }
     return healed;
 }
References _, ACT_FIRSTAID, Character::activity, add_msg(), Character::add_msg_player_or_npc(), bandages_power, bite, bleed, Character::can_use_heal_item(), disinfectant_power, Character::disp_name(), effect_bandaged, effect_bite, effect_bleed, effect_disinfected, effect_infected, force, Creature::get_all_body_parts(), get_bandaged_level(), get_disinfected_level(), Creature::get_effect_dur(), Creature::get_effect_int(), get_heal_value(), Creature::get_part_hp_cur(), Creature::get_part_hp_max(), get_stopbleed_level(), Creature::has_effect(), player_activity::id(), infect, Creature::is_avatar(), Character::is_npc(), limb_power, m_bad, m_info, only_main, pgettext, pick_part_to_heal(), player_activity::str_values, string_format(), and item::tname().
Referenced by use().
Member Data Documentation
bandages_power
float heal_actor::bandages_power = 0.0f
How many intensity levels will be applied when healing limbs?
Definition at line 873 of file iuse_actor.h.
Referenced by finish_using(), get_bandaged_level(), npc::get_healing_item(), npc::has_healing_options(), info(), load(), and use_healing_item().
bandages_scaling
float heal_actor::bandages_scaling = 0.0f
Extra intensity levels gained per skill level when healing limbs.
Definition at line 875 of file iuse_actor.h.
Referenced by get_bandaged_level(), and load().
bite
float heal_actor::bite = 0.0f
Chance to remove bite effect.
Definition at line 883 of file iuse_actor.h.
Referenced by finish_using(), npc::get_healing_item(), npc::has_healing_options(), info(), load(), and use_healing_item().
bleed
int heal_actor::bleed = 0
How many levels of bleeding effect intensity can it remove (dressing efficiency).
Definition at line 881 of file iuse_actor.h.
Referenced by finish_using(), npc::get_healing_item(), get_stopbleed_level(), npc::has_healing_options(), info(), load(), and use_healing_item().
disinfectant_power
float heal_actor::disinfectant_power = 0.0f
How many intensity levels will be applied when healing limbs?
Definition at line 877 of file iuse_actor.h.
Referenced by finish_using(), get_disinfected_level(), npc::get_healing_item(), npc::has_healing_options(), info(), load(), and use_healing_item().
disinfectant_scaling
float heal_actor::disinfectant_scaling = 0.0f
Extra intensity levels gained per skill level when healing limbs.
Definition at line 879 of file iuse_actor.h.
Referenced by get_disinfected_level(), and load().
effects
std::vector<effect_data> heal_actor::effects
Effects to apply to patient on finished healing.
Definition at line 895 of file iuse_actor.h.
Referenced by finish_using(), and load().
head_power
float heal_actor::head_power = 0.0f
How much hp to restore when healing head?
Definition at line 869 of file iuse_actor.h.
Referenced by get_heal_value(), info(), and load().
head_scaling
float heal_actor::head_scaling = 0.0f
Extra hp gained per skill level when healing head.
Definition at line 891 of file iuse_actor.h.
Referenced by get_heal_value(), and load().
infect
float heal_actor::infect = 0.0f
Chance to remove infected effect.
Definition at line 885 of file iuse_actor.h.
Referenced by finish_using(), npc::get_healing_item(), npc::has_healing_options(), info(), load(), and use_healing_item().
limb_power
float heal_actor::limb_power = 0.0f
How much hp to restore when healing limbs?
Definition at line 867 of file iuse_actor.h.
Referenced by finish_using(), get_heal_value(), info(), load(), game::npc_menu(), and use_healing_item().
limb_scaling
float heal_actor::limb_scaling = 0.0f
Extra hp gained per skill level when healing limbs.
Definition at line 889 of file iuse_actor.h.
Referenced by get_heal_value(), and load().
move_cost
int heal_actor::move_cost = 100
Cost in moves to use the item.
Definition at line 887 of file iuse_actor.h.
Referenced by Character::get_consume_time(), info(), load(), and use().
torso_power
float heal_actor::torso_power = 0.0f
How much hp to restore when healing torso?
Definition at line 871 of file iuse_actor.h.
Referenced by get_heal_value(), info(), and load().
torso_scaling
float heal_actor::torso_scaling = 0.0f
Extra hp gained per skill level when healing torso.
Definition at line 893 of file iuse_actor.h.
Referenced by get_heal_value(), and load().
used_up_item_charges
int heal_actor::used_up_item_charges = 1
Definition at line 903 of file iuse_actor.h.
Referenced by finish_using(), and load().
used_up_item_flags
std::set<flag_id> heal_actor::used_up_item_flags
Definition at line 904 of file iuse_actor.h.
Referenced by finish_using(), and load().
used_up_item_id
itype_id heal_actor::used_up_item_id
Item produced on finished healing.
For example, bloody rag. If the used item is a tool it, it will be turned into the used up item. If it is not a tool a new item with this id will be created.
Definition at line 901 of file iuse_actor.h.
Referenced by finish_using(), and load().
used_up_item_quantity
int heal_actor::used_up_item_quantity = 1
Definition at line 902 of file iuse_actor.h.
Referenced by finish_using(), and load().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp