Cataclysm DDA: tgz_archiver Class Reference
tgz_archiver Class Reference
#include <tgz_archiver.h>
Public Member Functions
tgz_archiver (std::string ofile)
~tgz_archiver ()
tgz_archiver (tgz_archiver const &)=delete
tgz_archiver (tgz_archiver &&)=delete
tgz_archiver & operator= (tgz_archiver const &)=delete
tgz_archiver & operator= (tgz_archiver &&)=delete
bool add_file (fs::path const &real_path, fs::path const &archived_path)
void finalize ()
Private Types
using tar_block_t = std::array< char, tar_block_size >
Private Member Functions
std::string _gen_tar_header (fs::path const &file_name, fs::path const &prefix, fs::path const &real_path, std::streamsize size)
Private Attributes
gzFile fd = nullptr
std::string const output
fs::file_time_type const _fsnow
std::chrono::system_clock::time_point const _sysnow
Static Private Attributes
static constexpr std::size_t tar_block_size = 512
Detailed Description
Definition at line 14 of file tgz_archiver.h.
Member Typedef Documentation
tar_block_t
using tgz_archiver::tar_block_t = std::array<char, tar_block_size> private
Definition at line 18 of file tgz_archiver.h.
Constructor & Destructor Documentation
tgz_archiver() [1/3]
tgz_archiver::tgz_archiver (std::string ofile) inline explicit
Definition at line 28 of file tgz_archiver.h.
             : output( std::move( ofile ) ), _fsnow( fs::file_time_type::clock::now() ),
               _sysnow( std::chrono::system_clock::now() ) {};
~tgz_archiver()
tgz_archiver::~tgz_archiver ()
Definition at line 16 of file tgz_archiver.cpp.
 {
     finalize();
 }
References finalize().
tgz_archiver() [2/3]
tgz_archiver::tgz_archiver (tgz_archiver const &) delete
tgz_archiver() [3/3]
tgz_archiver::tgz_archiver (tgz_archiver &&) delete
Member Function Documentation
_gen_tar_header()
std::string tgz_archiver::_gen_tar_header (fs::path const & file_name, fs::path const & prefix, fs::path const & real_path, std::streamsize size) private
Definition at line 21 of file tgz_archiver.cpp.
 {
     unsigned const type = fs::is_directory( real_path ) ? 5 : 0;
     unsigned const perms = fs::is_directory( real_path ) ? 0775 : 0664;
     // https://stackoverflow.com/a/61067330
     std::time_t const mtime = fs::exists( real_path )
                               ? std::chrono::system_clock::to_time_t(
                                   std::chrono::time_point_cast<std::chrono::system_clock::duration>(
                                       fs::last_write_time( real_path ) - _fsnow + _sysnow ) ) : std::time_t{};
     std::string buf( tar_block_size, '\0' );
     std::ostringstream ss( buf );
     ss.imbue( std::locale::classic() );
     ss << file_name.generic_u8string();
     ss.seekp( 100 );
     ss << std::oct << std::setfill( '0' );
     ss << std::setw( 7 ) << perms << '\0';
     ss << std::setw( 7 ) << '0' << '\0';
     ss << std::setw( 7 ) << '0' << '\0';
     ss << std::setw( 11 ) << size << " ";
     ss << std::setw( 11 ) << mtime << " ";
     ss << "        ";
     ss << type;
     ss.seekp( 257 );
     ss << "ustar" << '\0' << "00";
     ss.seekp( 345 );
     ss << prefix.generic_u8string();
     std::string const tmp = ss.str();
     unsigned const checksum = std::accumulate( tmp.cbegin(), tmp.cend(), 0 );
     ss.seekp( 148 );
     ss << std::setw( 6 ) << checksum << '\0' << ' ';
     return ss.str();
 }
References _fsnow, _sysnow, anonymous_namespace{filesystem.cpp}::is_directory(), prefix, om_direction::size, tar_block_size, and type.
Referenced by add_file().
add_file()
bool tgz_archiver::add_file (fs::path const & real_path, fs::path const & archived_path)
Definition at line 56 of file tgz_archiver.cpp.
 {
     if( fd == nullptr && ( fd = gzopen( output.c_str(), "wb" ), fd == nullptr ) ) {
         return false;
     }
     std::size_t const archived_path_size = archived_path.generic_u8string().size();
     std::size_t const prefix_len = archived_path_size > 100 ? archived_path_size - 100 : 0;
     if( archived_path.filename().generic_u8string().size() > 100 ||
         prefix_len > 150 ) {
         DebugLog( DebugLevel::D_WARNING, DebugClass::D_MAIN )
                 << "file skipped (path too long): " << archived_path << std::endl;
         return false;
     }
     fs::path prefix;
     fs::path file_name;
     if( prefix_len > 0 ) {
         std::size_t len = 0;
         for( fs::path const &it : archived_path ) {
             prefix /= it;
             len += it.generic_u8string().size() + 1;
             if( len >= prefix_len ) {
                 break;
             }
         }
         file_name = archived_path.lexically_relative( prefix );
     } else {
         file_name = archived_path;
     }
     std::string header( tar_block_size, '\0' );
     std::streamsize size = 0;
     std::ifstream file( real_path, std::ios::binary | std::ios::ate );
     if( fs::is_regular_file( real_path ) ) {
         size = file.tellg();
         header = _gen_tar_header( file_name, prefix, real_path, size );
         file.seekg( 0 );
         file.clear();
     } else {
         header = _gen_tar_header( file_name, prefix, real_path, 0 );
     }
     bool ret = gzwrite( fd, header.c_str(), tar_block_size ) != 0;
     if( !ret || !fs::is_regular_file( real_path ) || size == 0 ) {
         return ret;
     }
     double const buf_size = std::ceil( static_cast<double>( size ) / tar_block_size ) * tar_block_size;
     std::string buf( static_cast<std::string::size_type>( buf_size ), '\0' );
     if( file.read( buf.data(), size ) ) {
         ret &= gzwrite( fd, buf.data(), buf.size() ) != 0;
     } else {
         debugmsg( "failed to read file %s", real_path.string() );
     }
     return ret;
 }
References _gen_tar_header(), ceil(), D_MAIN, D_WARNING, DebugLog(), debugmsg, fd, file, output, prefix, base_camps::prefix_len, cata::hash64_detail::ret, om_direction::size, and tar_block_size.
finalize()
void tgz_archiver::finalize ()
Definition at line 116 of file tgz_archiver.cpp.
 {
     if( fd == nullptr ) {
         return;
     }
     std::array<char, tar_block_size * 2> const fin{};
     gzwrite( fd, fin.data(), fin.size() );
     gzclose_w( fd );
     fd = nullptr;
 }
References fd.
Referenced by anonymous_namespace{debug_menu.cpp}::write_min_archive(), and ~tgz_archiver().
operator=() [1/2]
tgz_archiver& tgz_archiver::operator= (tgz_archiver &&) delete
operator=() [2/2]
tgz_archiver& tgz_archiver::operator= (tgz_archiver const &) delete
Member Data Documentation
_fsnow
fs::file_time_type const tgz_archiver::_fsnow private
Definition at line 24 of file tgz_archiver.h.
Referenced by _gen_tar_header().
_sysnow
std::chrono::system_clock::time_point const tgz_archiver::_sysnow private
Definition at line 25 of file tgz_archiver.h.
Referenced by _gen_tar_header().
fd
gzFile tgz_archiver::fd = nullptr private
Definition at line 22 of file tgz_archiver.h.
Referenced by add_file(), and finalize().
output
std::string const tgz_archiver::output private
Definition at line 23 of file tgz_archiver.h.
Referenced by add_file().
tar_block_size
constexpr std::size_t tgz_archiver::tar_block_size = 512 static constexpr private
Definition at line 17 of file tgz_archiver.h.
Referenced by _gen_tar_header(), and add_file().
The documentation for this class was generated from the following files:
src/tgz_archiver.h
src/tgz_archiver.cpp