Cataclysm DDA: comestible_inventory_preset Class Reference
comestible_inventory_preset Class Reference
Public Member Functions
comestible_inventory_preset (const Character &you)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const override
Whether the first item is considered to go before the second.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Protected Member Functions
int get_order (const item_location &loc, const time_duration &time) const
const islot_comestible & get_edible_comestible (const item &it) const
time_duration get_time_left (const item_location &loc) const
std::string get_time_left_rounded (const item_location &loc) const
std::string get_freshness (const item_location &loc)
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Private Attributes
const Character & you
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 648 of file game_inventory.cpp.
Constructor & Destructor Documentation
comestible_inventory_preset()
comestible_inventory_preset::comestible_inventory_preset (const Character & you) inline explicit
Definition at line 651 of file game_inventory.cpp.
                                                                      : you( you ) {
             _indent_entries = false;
             _collate_entries = true;
             append_cell( [&you]( const item_location & loc ) {
                 const nutrients nutr = you.compute_effective_nutrients( *loc );
                 return good_bad_none( nutr.kcal() );
             }, _( "CALORIES" ) );
             append_cell( []( const item_location & loc ) {
                 return good_bad_none( loc->is_comestible() ? loc->get_comestible()->quench : 0 );
             }, _( "QUENCH" ) );
             append_cell( [&you]( const item_location & loc ) {
                 int joy = you.fun_for( *loc ).first;
                 std::string joy_str;
                 if( loc->has_flag( flag_MUSHY ) ) {
                     joy_str = highlight_good_bad_none( joy );
                 } else {
                     joy_str = good_bad_none( joy );
                 }
                 int max_joy = you.fun_for( *loc, true ).first;
                 // max_joy should be 3 wide for alignment of '/'
                 if( max_joy == 0 ) {
                     // this will not be an empty string when food's joy can go below 0 by consumption (very rare)
                     return joy_str;
                 } else if( max_joy == joy ) {
                     return joy_str + std::string( joy > 0 ? "<good>/  =</good>" : "<bad>/  =</bad>" );
                 } else {
                     return string_format( max_joy > 0 ? "%s/<good>%+3d</good>" : "%s/<bad>%3d</bad>",
                                           joy_str, max_joy );
                 }
             }, _( "JOY/MAX" ) );
             append_cell( []( const item_location & loc ) {
                 const int healthy = loc->is_comestible() ? loc->get_comestible()->healthy : 0;
                 return healthy_bar( healthy );
             }, _( "HEALTH" ) );
             append_cell( []( const item_location & loc ) {
                 const time_duration spoils = loc->is_comestible() ? loc->get_comestible()->spoils :
                                              calendar::INDEFINITELY_LONG_DURATION;
                 if( spoils > 0_turns ) {
                     return to_string_clipped( spoils );
                 }
                 //~ Used for permafood shelf life in the Eat menu
                 return std::string( _( "indefinite" ) );
             }, _( "SHELF LIFE" ) );
             append_cell( []( const item_location & loc ) {
                 const item &it = *loc;
                 int converted_volume_scale = 0;
                 const int charges = std::max( it.charges, 1 );
                 const double converted_volume = round_up( convert_volume( it.volume().value() / charges,
                                                 &converted_volume_scale ), 2 );
                 //~ Eat menu Volume: <num><unit>
                 return string_format( _( "%.2f%s" ), converted_volume, volume_units_abbr() );
             }, _( "VOLUME" ) );
             append_cell( [&you]( const item_location & loc ) {
                 const item &it = *loc;
                 // Quit prematurely if the item is not food.
                 if( !it.type->comestible ) {
                     return std::string();
                 }
                 const int calories_per_effective_volume = you.compute_calories_per_effective_volume( it );
                 // Show empty cell instead of 0.
                 if( calories_per_effective_volume == 0 ) {
                     return std::string();
                 }
                 return satiety_bar( calories_per_effective_volume );
             }, _( "SATIETY" ) );
             Character &player_character = get_player_character();
             append_cell( [&player_character]( const item_location & loc ) {
                 time_duration time = player_character.get_consume_time( *loc );
                 return string_format( "%s", to_string( time, true ) );
             }, _( "CONSUME TIME" ) );
             append_cell( [this, &player_character]( const item_location & loc ) {
                 std::string sealed;
                 item_location temp = loc;
                 // check if at least one parent container is sealed
                 while( temp.has_parent() ) {
                     item_pocket *pocket = temp.parent_pocket();
                     if( pocket->sealed() ) {
                         sealed = _( "sealed" );
                         break;
                     }
                     temp = temp.parent_item();
                 }
                 if( player_character.can_estimate_rot() ) {
                     if( loc->is_comestible() && loc->get_comestible()->spoils > 0_turns ) {
                         return sealed + ( sealed.empty() ? "" : " " ) + get_freshness( loc );
                     }
                     return std::string( "---" );
                 }
                 return sealed;
             }, _( "FRESHNESS" ) );
             append_cell( [ this, &player_character ]( const item_location & loc ) {
                 if( player_character.can_estimate_rot() ) {
                     if( loc->is_comestible() && loc->get_comestible()->spoils > 0_turns ) {
                         if( !loc->rotten() ) {
                             return get_time_left_rounded( loc );
                         }
                     }
                     return std::string( "---" );
                 }
                 return std::string();
             }, _( "SPOILS IN" ) );
         }
References _, inventory_selector_preset::_collate_entries, inventory_selector_preset::_indent_entries, inventory_selector_preset::append_cell(), item::charges, itype::comestible, Character::compute_calories_per_effective_volume(), Character::compute_effective_nutrients(), convert_volume(), flag_MUSHY, Character::fun_for(), item::get_comestible(), get_player_character(), anonymous_namespace{game_inventory.cpp}::good_bad_none(), item::has_flag(), healthy_bar(), calendar::INDEFINITELY_LONG_DURATION, item::is_comestible(), nutrients::kcal(), max(), round_up(), satiety_bar(), anonymous_namespace{item_tname.cpp}::sealed(), string_format(), temp, to_string(), item::type, units::quantity< V, U >::value(), item::volume(), volume_units_abbr(), and you.
Member Function Documentation
get_denial()
std::string comestible_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 774 of file game_inventory.cpp.
{
             const item &med = *loc;
             if(
                 ( loc->made_of_from_type( phase_id::LIQUID ) &&
                   loc.where() != item_location::type::container ) &&
                 !get_map().has_flag_furn( ter_furn_flag::TFLAG_LIQUIDCONT, loc.position() ) ) {
                 return _( "Can't drink spilt liquids." );
             }
             if(
                 loc->made_of_from_type( phase_id::GAS ) &&
                 loc.where() != item_location::type::container ) {
                 return _( "Can't consume spilt gasses." );
             }
             if( med.is_medication() && !you.can_use_heal_item( med ) && !med.is_craft() ) {
                 return _( "Your biology is not compatible with that item." );
             }
             const item &it = *loc;
             const ret_val<edible_rating> res =
                 it.is_medical_tool() ? ret_val<edible_rating>::make_success() : you.can_eat( it );
             if( !res.success() ) {
                 return res.str();
             }
             return inventory_selector_preset::get_denial( loc );
         }
References _, item_location::container, GAS, inventory_selector_preset::get_denial(), get_map(), item::is_craft(), item::is_medical_tool(), item::is_medication(), LIQUID, item::made_of_from_type(), ret_val< T >::make_success(), item_location::position(), ret_val_common::str(), ret_val_common::success(), TFLAG_LIQUIDCONT, and item_location::where().
get_edible_comestible()
const islot_comestible& comestible_inventory_preset::get_edible_comestible (const item & it) const inline protected
Definition at line 834 of file game_inventory.cpp.
{
             if( it.is_comestible() && you.can_eat( it ).success() ) {
                 // Ok since can_eat() returns false if is_craft() is true
                 return *it.type->comestible;
             }
             static const islot_comestible dummy {};
             return dummy;
         }
References itype::comestible, item::is_comestible(), and item::type.
get_freshness()
std::string comestible_inventory_preset::get_freshness (const item_location & loc) inline protected
Definition at line 872 of file game_inventory.cpp.
{
             const item &it = *loc;
             const double rot_progress = it.get_relative_rot();
             if( it.is_fresh() ) {
                 return _( "fresh" );
             } else if( rot_progress < 0.3 ) {
                 return _( "quite fresh" );
             } else if( rot_progress < 0.5 ) {
                 return _( "near midlife" );
             } else if( rot_progress < 0.7 ) {
                 return _( "past midlife" );
             } else if( rot_progress < 0.9 ) {
                 return _( "getting older" );
             } else if( !it.rotten() ) {
                 return _( "old" );
             } else {
                 return _( "rotten" );
             }
         }
References _, item::get_relative_rot(), item::is_fresh(), and item::rotten().
get_order()
int comestible_inventory_preset::get_order (const item_location & loc, const time_duration & time) const inline protected
Definition at line 817 of file game_inventory.cpp.
{
             if( loc->rotten() ) {
                 if( you.has_trait( trait_SAPROPHAGE ) || you.has_trait( trait_SAPROVORE ) ) {
                     return 1;
                 } else {
                     return 5;
                 }
             } else if( time == 0_turns ) {
                 return 4;
             } else if( loc.has_parent() &&
                        loc.parent_pocket()->spoil_multiplier() == 0.0f ) {
                 return 3;
             } else {
                 return 2;
             }
         }
References item_location::has_parent(), item_location::parent_pocket(), item::rotten(), item_pocket::spoil_multiplier(), trait_SAPROPHAGE, and trait_SAPROVORE.
get_time_left()
time_duration comestible_inventory_preset::get_time_left (const item_location & loc) const inline protected
Definition at line 843 of file game_inventory.cpp.
{
             time_duration time_left = 0_turns;
             const time_duration shelf_life = loc->is_comestible() ? loc->get_comestible()->spoils :
                                              calendar::INDEFINITELY_LONG_DURATION;
             if( shelf_life > 0_turns ) {
                 const item &it = *loc;
                 const double relative_rot = it.get_relative_rot();
                 time_left = shelf_life - shelf_life * relative_rot;
                 // Correct for an estimate that exceeds shelf life -- this happens especially with
                 // fresh items.
                 if( time_left > shelf_life ) {
                     time_left = shelf_life;
                 }
             }
             return time_left;
         }
References item::get_comestible(), item::get_relative_rot(), calendar::INDEFINITELY_LONG_DURATION, and item::is_comestible().
get_time_left_rounded()
std::string comestible_inventory_preset::get_time_left_rounded (const item_location & loc) const inline protected
Definition at line 862 of file game_inventory.cpp.
{
             const item &it = *loc;
             if( it.is_going_bad() ) {
                 return _( "soon!" );
             }
             time_duration time_left = get_time_left( loc );
             return to_string_approx( time_left );
         }
References _, item::is_going_bad(), and to_string_approx().
is_shown()
bool comestible_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Reimplemented in comestible_filtered_inventory_preset.
Definition at line 769 of file game_inventory.cpp.
{
             return ( loc->is_comestible() && you.can_consume_as_is( *loc ) ) ||
                    loc->is_medical_tool();
         }
References item::is_comestible(), and item::is_medical_tool().
Referenced by comestible_filtered_inventory_preset::is_shown().
sort_compare()
bool comestible_inventory_preset::sort_compare (const inventory_entry & lhs, const inventory_entry & rhs) const inline override virtual
Whether the first item is considered to go before the second.
Reimplemented from inventory_selector_preset.
Definition at line 804 of file game_inventory.cpp.
{
             time_duration time_a = get_time_left( lhs.any_item() );
             time_duration time_b = get_time_left( rhs.any_item() );
             int order_a = get_order( lhs.any_item(), time_a );
             int order_b = get_order( rhs.any_item(), time_b );
             return order_a < order_b
                    || ( order_a == order_b && time_a < time_b )
                    || ( order_a == order_b && time_a == time_b &&
                         inventory_selector_preset::sort_compare( lhs, rhs ) );
         }
References inventory_entry::any_item(), and inventory_selector_preset::sort_compare().
Member Data Documentation
you
const Character& comestible_inventory_preset::you private
Definition at line 893 of file game_inventory.cpp.
Referenced by comestible_inventory_preset().
The documentation for this class was generated from the following file:
src/game_inventory.cpp