Cataclysm DDA: fault_fix Class Reference
fault_fix Class Reference
#include <fault.h>
Public Member Functions
const requirement_data & get_requirements () const
Static Public Member Functions
static void load (const JsonObject &jo)
static const std::map< fault_fix_id, fault_fix > & all ()
static void reset ()
static void finalize ()
static void check_consistency ()
Public Attributes
fault_fix_id id_ = fault_fix_id::NULL_ID()
translation name
translation success_msg
time_duration time
std::map< std::string, std::string > set_variables
std::map< skill_id, int > skills
std::set< fault_id > faults_removed
std::set< fault_id > faults_added
int mod_damage = 0
int mod_degradation = 0
std::map< proficiency_id, float > time_save_profs
std::map< flag_id, float > time_save_flags
Private Attributes
shared_ptr_fast< requirement_data > requirements = make_shared_fast<requirement_data>()
Friends
class fault
Detailed Description
Definition at line 19 of file fault.h.
Member Function Documentation
all()
const std::map< fault_fix_id, fault_fix > & fault_fix::all () static
Definition at line 142 of file fault.cpp.
 {
     return fault_fixes_all;
 }
References fault_fixes_all.
check_consistency()
void fault_fix::check_consistency () static
Definition at line 225 of file fault.cpp.
 {
     for( const auto &[fix_id, fix] : fault_fixes_all ) {
         if( fix.time < 0_turns ) {
             debugmsg( "fault_fix '%s' has negative time", fix_id.str() );
         }
         for( const auto &[skill_id, lvl] : fix.skills ) {
             if( !skill_id.is_valid() ) {
                 debugmsg( "fault_fix %s requires unknown skill '%s'",
                           fix_id.str(), skill_id.str() );
             }
             if( lvl <= 0 ) {
                 debugmsg( "fault_fix '%s' requires negative level of skill '%s'",
                           fix_id.str(), skill_id.str() );
             }
         }
         for( const fault_id &fault_id : fix.faults_removed ) {
             if( !fault_id.is_valid() ) {
                 debugmsg( "fault_fix '%s' has invalid fault_id '%s' in 'faults_removed' field",
                           fix_id.str(), fault_id.str() );
             }
         }
         for( const fault_id &fault_id : fix.faults_added ) {
             if( !fault_id.is_valid() ) {
                 debugmsg( "fault_fix '%s' has invalid fault_id '%s' in 'faults_added' field",
                           fix_id.str(), fault_id.str() );
             }
         }
         for( const auto &[proficiency_id, mult] : fix.time_save_profs ) {
             if( !proficiency_id.is_valid() ) {
                 debugmsg( "fault_fix %s has unknown proficiency_id '%s'",
                           fix_id.str(), proficiency_id.str() );
             }
             if( mult < 0 ) {
                 debugmsg( "fault_fix '%s' has negative mend time if possessing proficiency '%s'",
                           fix_id.str(), proficiency_id.str() );
             }
         }
         for( const auto &[flag_id, mult] : fix.time_save_flags ) {
             if( !flag_id.is_valid() ) {
                 debugmsg( "fault_fix %s has unknown flag_id '%s'",
                           fix_id.str(), flag_id.str() );
             }
             if( mult < 0 ) {
                 debugmsg( "fault_fix '%s' has negative mend time if item possesses flag '%s'",
                           fix_id.str(), flag_id.str() );
             }
         }
     }
 }
References debugmsg, fault_fixes_all, string_id< T >::is_valid(), and string_id< T >::str().
Referenced by DynamicDataLoader::check_consistency().
finalize()
void fault_fix::finalize () static
Definition at line 204 of file fault.cpp.
 {
     for( auto& [fix_id, fix] : fault_fixes_all ) {
         const auto range = reqs_temp_storage.equal_range( fix_id );
         for( auto it = range.first; it != range.second; ++it ) {
             const requirement_id req_id( it->second.first );
             const int amount = it->second.second;
             if( !req_id.is_valid() ) {
                 debugmsg( "fault_fix '%s' has invalid requirement_id '%s'", fix_id.str(), req_id.str() );
                 continue;
             }
             *fix.requirements = *fix.requirements + ( *req_id ) * amount;
         }
         fix.requirements->consolidate();
         for( const fault_id &fid : fix.faults_removed ) {
             const_cast<fault &>( *fid ).fixes.emplace( fix_id );
         }
     }
     reqs_temp_storage.clear();
 }
References debugmsg, fault_fixes_all, fault::fixes, string_id< T >::is_valid(), reqs_temp_storage, and string_id< T >::str().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_requirements()
const requirement_data & fault_fix::get_requirements () const
Definition at line 152 of file fault.cpp.
 {
     return *requirements;
 }
References requirements.
Referenced by Character::mend_item(), and activity_handlers::mend_item_finish().
load()
void fault_fix::load (const JsonObject & jo) static
Definition at line 160 of file fault.cpp.
 {
     fault_fix f;
     assign( jo, "id", f.id_, true );
     assign( jo, "name", f.name, true );
     assign( jo, "success_msg", f.success_msg, true );
     assign( jo, "time", f.time, false );
     assign( jo, "set_variables", f.set_variables, true );
     assign( jo, "skills", f.skills, true );
     assign( jo, "faults_removed", f.faults_removed );
     assign( jo, "faults_added", f.faults_added );
     assign( jo, "mod_damage", f.mod_damage );
     assign( jo, "mod_degradation", f.mod_degradation );
     assign( jo, "time_save_profs", f.time_save_profs, false );
     assign( jo, "time_save_flags", f.time_save_flags, false );
     if( jo.has_array( "requirements" ) ) {
         for( const JsonValue &jv : jo.get_array( "requirements" ) ) {
             if( jv.test_array() ) {
                 // array of 2 elements filled with [requirement_id, count]
                 const JsonArray &req = static_cast<JsonArray>( jv );
                 const std::string req_id = req.get_string( 0 );
                 const int req_amount = req.get_int( 1 );
                 reqs_temp_storage.emplace( f.id_, std::make_pair( req_id, req_amount ) );
             } else if( jv.test_object() ) {
                 // defining single requirement inline
                 const JsonObject &req = static_cast<JsonObject>( jv );
                 const requirement_id req_id( "fault_fix_" + f.id_.str() + "_inline_req" );
                 requirement_data::load_requirement( req, req_id );
                 reqs_temp_storage.emplace( f.id_, std::make_pair( req_id.str(), 1 ) );
             } else {
                 debugmsg( "fault_fix '%s' has has invalid requirement element", f.id_.str() );
             }
         }
     }
     fault_fixes_all.emplace( f.id_, f );
 }
References assign(), debugmsg, fault_fixes_all, faults_added, faults_removed, JsonObject::get_array(), JsonArray::get_int(), JsonArray::get_string(), JsonObject::has_array(), id_, requirement_data::load_requirement(), mod_damage, mod_degradation, name, reqs_temp_storage, set_variables, skills, string_id< T >::str(), success_msg, time, time_save_flags, and time_save_profs.
Referenced by DynamicDataLoader::initialize().
reset()
void fault_fix::reset () static
Definition at line 199 of file fault.cpp.
 {
     fault_fixes_all.clear();
 }
References fault_fixes_all.
Referenced by DynamicDataLoader::unload_data().
Friends And Related Function Documentation
fault
friend class fault friend
Definition at line 45 of file fault.h.
Member Data Documentation
faults_added
std::set<fault_id> fault_fix::faults_added
Definition at line 29 of file fault.h.
Referenced by load(), Character::mend_item(), and activity_handlers::mend_item_finish().
faults_removed
std::set<fault_id> fault_fix::faults_removed
Definition at line 28 of file fault.h.
Referenced by load(), Character::mend_item(), and activity_handlers::mend_item_finish().
id_
fault_fix_id fault_fix::id_ = fault_fix_id::NULL_ID()
Definition at line 22 of file fault.h.
Referenced by load().
mod_damage
int fault_fix::mod_damage = 0
Definition at line 30 of file fault.h.
Referenced by load(), Character::mend_item(), and activity_handlers::mend_item_finish().
mod_degradation
int fault_fix::mod_degradation = 0
Definition at line 31 of file fault.h.
Referenced by load(), and activity_handlers::mend_item_finish().
name
translation fault_fix::name
Definition at line 23 of file fault.h.
Referenced by load().
requirements
shared_ptr_fast<requirement_data> fault_fix::requirements = make_shared_fast<requirement_data>() private
Definition at line 46 of file fault.h.
Referenced by get_requirements().
set_variables
std::map<std::string, std::string> fault_fix::set_variables
Definition at line 26 of file fault.h.
Referenced by load(), and activity_handlers::mend_item_finish().
skills
std::map<skill_id, int> fault_fix::skills
Definition at line 27 of file fault.h.
Referenced by load(), Character::mend_item(), and activity_handlers::mend_item_finish().
success_msg
translation fault_fix::success_msg
Definition at line 24 of file fault.h.
Referenced by load(), and activity_handlers::mend_item_finish().
time
time_duration fault_fix::time
Definition at line 25 of file fault.h.
Referenced by load(), Character::mend_item(), and activity_handlers::mend_item_finish().
time_save_flags
std::map<flag_id, float> fault_fix::time_save_flags
Definition at line 35 of file fault.h.
Referenced by load(), and Character::mend_item().
time_save_profs
std::map<proficiency_id, float> fault_fix::time_save_profs
Definition at line 33 of file fault.h.
Referenced by load(), Character::mend_item(), and activity_handlers::mend_item_finish().
The documentation for this class was generated from the following files:
src/fault.h
src/fault.cpp