Cataclysm DDA: tileset Class Reference
tileset Class Reference
#include <cata_tiles.h>
Classes
struct season_tile_value
Public Member Functions
void clear ()
bool is_isometric () const
int get_tile_width () const
int get_tile_height () const
const half_open_rectangle< point > & get_max_tile_extent () const
int get_zlevel_height () const
float get_tile_pixelscale () const
float get_prevent_occlusion_min_dist () const
float get_prevent_occlusion_max_dist () const
const std::string & get_tileset_id () const
const texture * get_tile (const size_t index) const
const texture * get_night_tile (const size_t index) const
const texture * get_shadow_tile (const size_t index) const
const texture * get_overexposed_tile (const size_t index) const
const texture * get_memory_tile (const size_t index) const
const std::unordered_set< std::string > & get_duplicate_ids () const
tile_type & create_tile_type (const std::string &id, tile_type &&new_tile_type)
const tile_type * find_tile_type (const std::string &id) const
std::optional< tile_lookup_res > find_tile_type_by_season (const std::string &id, season_type season) const
Looks up tile by id + season suffix AND just raw id Example: if id == "t_tree_apple" and season == SPRING will first look up "t_tree_apple_season_spring" if not found, will look up "t_tree_apple" if still nothing is found, will return std::nullopt.
Public Attributes
std::unordered_map< std::string, std::vector< layer_variant > > item_layer_data
std::unordered_map< std::string, std::vector< layer_variant > > field_layer_data
Static Private Member Functions
static const texture * get_if_available (const size_t index, const decltype(shadow_tile_values) &tiles)
Private Attributes
std::string tileset_id
bool tile_isometric = false
int tile_width = 0
int tile_height = 0
half_open_rectangle< point > max_tile_extent
int zlevel_height = 0
float prevent_occlusion_min_dist = 0.0
float prevent_occlusion_max_dist = 0.0
float tile_pixelscale = 1.0f
std::vector< texture > tile_values
std::vector< texture > shadow_tile_values
std::vector< texture > night_tile_values
std::vector< texture > overexposed_tile_values
std::vector< texture > memory_tile_values
std::unordered_set< std::string > duplicate_ids
std::unordered_map< std::string, tile_type > tile_ids
std::array< std::unordered_map< std::string, season_tile_value >, season_type::NUM_SEASONS > tile_ids_by_season
Friends
class tileset_cache
Detailed Description
Definition at line 151 of file cata_tiles.h.
Member Function Documentation
clear()
void tileset::clear ()
create_tile_type()
tile_type& tileset::create_tile_type (const std::string & id, tile_type && new_tile_type)
find_tile_type()
const tile_type* tileset::find_tile_type (const std::string & id) const
find_tile_type_by_season()
std::optional<tile_lookup_res> tileset::find_tile_type_by_season (const std::string & id, season_type season) const
Looks up tile by id + season suffix AND just raw id Example: if id == "t_tree_apple" and season == SPRING will first look up "t_tree_apple_season_spring" if not found, will look up "t_tree_apple" if still nothing is found, will return std::nullopt.
Parameters
id : "raw" tile id (without season suffix)
season : season suffix encoded as season_type enum
Returns
std::nullopt if no tile is found, std::optional with found id (e.g. "t_tree_apple_season_spring" or "t_tree_apple) and found tile.
Note: this method is guaranteed to return pointers to the keys and values stored inside the tileset::tile_ids collection. I.e. result of this method call is invalidated when the corresponding tileset is invalidated.
get_duplicate_ids()
const std::unordered_set<std::string>& tileset::get_duplicate_ids () const inline
Definition at line 248 of file cata_tiles.h.
{
             return duplicate_ids;
         }
References duplicate_ids.
get_if_available()
static const texture* tileset::get_if_available (const size_t index, const decltype(shadow_tile_values) & tiles) inline static private
Definition at line 190 of file cata_tiles.h.
{
             return index < tiles.size() ? & tiles[index] : nullptr;
         }
Referenced by get_memory_tile(), get_night_tile(), get_overexposed_tile(), get_shadow_tile(), and get_tile().
get_max_tile_extent()
const half_open_rectangle<point>& tileset::get_max_tile_extent () const inline
Definition at line 213 of file cata_tiles.h.
{
             return max_tile_extent;
         }
References max_tile_extent.
get_memory_tile()
const texture* tileset::get_memory_tile (const size_t index) const inline
Definition at line 244 of file cata_tiles.h.
{
             return get_if_available( index, memory_tile_values );
         }
References get_if_available(), and memory_tile_values.
get_night_tile()
const texture* tileset::get_night_tile (const size_t index) const inline
Definition at line 235 of file cata_tiles.h.
{
             return get_if_available( index, night_tile_values );
         }
References get_if_available(), and night_tile_values.
get_overexposed_tile()
const texture* tileset::get_overexposed_tile (const size_t index) const inline
Definition at line 241 of file cata_tiles.h.
{
             return get_if_available( index, overexposed_tile_values );
         }
References get_if_available(), and overexposed_tile_values.
get_prevent_occlusion_max_dist()
float tileset::get_prevent_occlusion_max_dist () const inline
Definition at line 225 of file cata_tiles.h.
{
             return prevent_occlusion_max_dist;
         }
References prevent_occlusion_max_dist.
get_prevent_occlusion_min_dist()
float tileset::get_prevent_occlusion_min_dist () const inline
Definition at line 222 of file cata_tiles.h.
{
             return prevent_occlusion_min_dist;
         }
References prevent_occlusion_min_dist.
get_shadow_tile()
const texture* tileset::get_shadow_tile (const size_t index) const inline
Definition at line 238 of file cata_tiles.h.
{
             return get_if_available( index, shadow_tile_values );
         }
References get_if_available(), and shadow_tile_values.
get_tile()
const texture* tileset::get_tile (const size_t index) const inline
Definition at line 232 of file cata_tiles.h.
{
             return get_if_available( index, tile_values );
         }
References get_if_available(), and tile_values.
get_tile_height()
int tileset::get_tile_height () const inline
Definition at line 210 of file cata_tiles.h.
{
             return tile_height;
         }
References tile_height.
get_tile_pixelscale()
float tileset::get_tile_pixelscale () const inline
Definition at line 219 of file cata_tiles.h.
{
             return tile_pixelscale;
         }
References tile_pixelscale.
get_tile_width()
int tileset::get_tile_width () const inline
Definition at line 207 of file cata_tiles.h.
{
             return tile_width;
         }
References tile_width.
get_tileset_id()
const std::string& tileset::get_tileset_id () const inline
Definition at line 228 of file cata_tiles.h.
{
             return tileset_id;
         }
References tileset_id.
get_zlevel_height()
int tileset::get_zlevel_height () const inline
Definition at line 216 of file cata_tiles.h.
{
             return zlevel_height;
         }
References zlevel_height.
is_isometric()
bool tileset::is_isometric () const inline
Definition at line 204 of file cata_tiles.h.
{
             return tile_isometric;
         }
References tile_isometric.
Friends And Related Function Documentation
tileset_cache
friend class tileset_cache friend
Definition at line 195 of file cata_tiles.h.
Member Data Documentation
duplicate_ids
std::unordered_set<std::string> tileset::duplicate_ids private
Definition at line 182 of file cata_tiles.h.
Referenced by get_duplicate_ids().
field_layer_data
std::unordered_map<std::string, std::vector<layer_variant> > tileset::field_layer_data
Definition at line 200 of file cata_tiles.h.
item_layer_data
std::unordered_map<std::string, std::vector<layer_variant> > tileset::item_layer_data
Definition at line 199 of file cata_tiles.h.
max_tile_extent
half_open_rectangle<point> tileset::max_tile_extent private
Definition at line 167 of file cata_tiles.h.
Referenced by get_max_tile_extent().
memory_tile_values
std::vector<texture> tileset::memory_tile_values private
Definition at line 180 of file cata_tiles.h.
Referenced by get_memory_tile().
night_tile_values
std::vector<texture> tileset::night_tile_values private
Definition at line 178 of file cata_tiles.h.
Referenced by get_night_tile().
overexposed_tile_values
std::vector<texture> tileset::overexposed_tile_values private
Definition at line 179 of file cata_tiles.h.
Referenced by get_overexposed_tile().
prevent_occlusion_max_dist
float tileset::prevent_occlusion_max_dist = 0.0 private
Definition at line 171 of file cata_tiles.h.
Referenced by get_prevent_occlusion_max_dist().
prevent_occlusion_min_dist
float tileset::prevent_occlusion_min_dist = 0.0 private
Definition at line 170 of file cata_tiles.h.
Referenced by get_prevent_occlusion_min_dist().
shadow_tile_values
std::vector<texture> tileset::shadow_tile_values private
Definition at line 177 of file cata_tiles.h.
Referenced by get_shadow_tile().
tile_height
int tileset::tile_height = 0 private
Definition at line 165 of file cata_tiles.h.
Referenced by get_tile_height().
tile_ids
std::unordered_map<std::string, tile_type> tileset::tile_ids private
Definition at line 184 of file cata_tiles.h.
tile_ids_by_season
std::array<std::unordered_map<std::string, season_tile_value>, season_type::NUM_SEASONS> tileset::tile_ids_by_season private
Definition at line 188 of file cata_tiles.h.
tile_isometric
bool tileset::tile_isometric = false private
Definition at line 161 of file cata_tiles.h.
Referenced by is_isometric().
tile_pixelscale
float tileset::tile_pixelscale = 1.0f private
Definition at line 174 of file cata_tiles.h.
Referenced by get_tile_pixelscale().
tile_values
std::vector<texture> tileset::tile_values private
Definition at line 176 of file cata_tiles.h.
Referenced by get_tile().
tile_width
int tileset::tile_width = 0 private
Definition at line 164 of file cata_tiles.h.
Referenced by get_tile_width().
tileset_id
std::string tileset::tileset_id private
Definition at line 159 of file cata_tiles.h.
Referenced by get_tileset_id().
zlevel_height
int tileset::zlevel_height = 0 private
Definition at line 168 of file cata_tiles.h.
Referenced by get_zlevel_height().
The documentation for this class was generated from the following file:
src/cata_tiles.h