Cataclysm DDA: melee_actor Class Reference
melee_actor Class Reference
#include <mattack_actors.h>
Public Member Functions
melee_actor ()
~melee_actor () override=default
virtual Creature * find_target (monster &z) const
virtual void on_damage (monster &z, Creature &target, dealt_damage_instance &dealt) const
void load_internal (const JsonObject &obj, const std::string &src) override
int do_grab (monster &, Creature *target, bodypart_id bp_id) const
bool call (monster &) const override
std::unique_ptr< mattack_actor > clone () const override
Public Member Functions inherited from mattack_actor
mattack_actor (const mattack_id &new_id)
void load (const JsonObject &jo, const std::string &src)
virtual ~mattack_actor ()=default
Public Attributes
damage_instance damage_max_instance
float min_mul = 0.5f
float max_mul = 1.0f
int move_cost = 100
int accuracy = INT_MIN
int range = 1
bool no_adjacent = false
bool dodgeable = true
bool uncanny_dodgeable = true
bool blockable = true
bool effects_require_dmg = true
bool effects_require_organic = false
int throw_strength = 0
int hitsize_min = -1
int hitsize_max = -1
bool attack_upper = true
grab grab_data
bool is_grab = false
weighted_float_list< bodypart_str_id > body_parts
If empty, regular melee roll body part selection is used.
std::vector< mon_effect_data > effects
Extra effects applied on hit.
std::vector< mon_effect_data > self_effects_always
std::vector< mon_effect_data > self_effects_onhit
std::vector< mon_effect_data > self_effects_ondmg
translation miss_msg_u
Message for missed attack against the player.
translation no_dmg_msg_u
Message for 0 damage hit against the player.
translation hit_dmg_u
Message for damaging hit against the player.
translation throw_msg_u
Message for throwing the player.
translation miss_msg_npc
Message for missed attack against a non-player.
translation no_dmg_msg_npc
Message for 0 damage hit against a non-player.
translation hit_dmg_npc
Message for damaging hit against a non-player.
translation throw_msg_npc
Message for throwing a non-player.
Public Attributes inherited from mattack_actor
mattack_id id
bool was_loaded = false
int cooldown = 0
int attack_chance = 100
std::function< bool(dialogue &)> condition
bool has_condition = false
Additional Inherited Members
Protected Member Functions inherited from mattack_actor
mattack_actor ()=default
Detailed Description
Definition at line 106 of file mattack_actors.h.
Constructor & Destructor Documentation
melee_actor()
melee_actor::melee_actor ()
Definition at line 337 of file mattack_actors.cpp.
 {
     damage_max_instance = damage_instance();
     // FIXME: Hardcoded damage type
     damage_max_instance.add_damage( damage_bash, 9 );
     min_mul = 0.5f;
     max_mul = 1.0f;
     move_cost = 100;
 }
References damage_instance::add_damage(), damage_bash, damage_max_instance, max_mul, min_mul, and move_cost.
~melee_actor()
melee_actor::~melee_actor () override default
Member Function Documentation
call()
bool melee_actor::call (monster & z) const override virtual
Implements mattack_actor.
Definition at line 673 of file mattack_actors.cpp.
 {
     Creature *target = find_target( z );
     if( target == nullptr ) {
         return false;
     }
     if( has_condition ) {
         dialogue d( get_talker_for( &z ), get_talker_for( *target ) );
         if( !condition( d ) ) {
             add_msg_debug( debugmode::DF_MATTACK, "Attack conditionals failed" );
             return false;
         }
     }
     z.mod_moves( -move_cost );
     const std::string mon_name = get_player_character().sees( z.pos() ) ?
                                  z.disp_name( false, true ) : _( "Something" );
     // Add always-applied self effects
     for( const mon_effect_data &eff : self_effects_always ) {
         if( x_in_y( eff.chance, 100 ) ) {
             z.add_effect( eff.id, time_duration::from_turns( rng( eff.duration.first, eff.duration.second ) ),
                           eff.permanent,
                           rng( eff.intensity.first, eff.intensity.second ) );
             target->add_msg_if_player( m_mixed, eff.message, mon_name );
         }
     }
     // Dodge check
     const int acc = accuracy >= 0 ? accuracy : z.type->melee_skill;
     int hitspread = target->deal_melee_attack( &z, dice( acc, 10 ) );
     // Pick body part
     bodypart_str_id bp_hit = body_parts.empty() ?
                              target->select_body_part( hitsize_min, hitsize_max, attack_upper, hitspread ).id() :
                              *body_parts.pick();
     bodypart_id bp_id = bodypart_id( bp_hit );
     game_message_type msg_type = target->is_avatar() ? m_warning : m_info;
     add_msg_debug( debugmode::DF_MATTACK, "Accuracy %d, hitspread %d, dodgeable %s", acc, hitspread,
                    dodgeable ? "true" : "false" );
     if( z.has_flag( mon_flag_HIT_AND_RUN ) ) {
         z.add_effect( effect_run, 4_turns );
     }
     if( uncanny_dodgeable && target->uncanny_dodge() ) {
         game_message_type msg_type = target->is_avatar() ? m_warning : m_info;
         sfx::play_variant_sound( "mon_bite", "bite_miss", sfx::get_heard_volume( z.pos() ),
                                  sfx::get_heard_angle( z.pos() ) );
         target->add_msg_player_or_npc( msg_type, miss_msg_u,
                                        get_option<bool>( "LOG_MONSTER_ATTACK_MONSTER" ) ? miss_msg_npc : translation(),
                                        z.name(), body_part_name_accusative( bp_id ) );
         return true;
     }
     if( dodgeable ) {
         if( hitspread < 0 ) {
             sfx::play_variant_sound( "mon_bite", "bite_miss", sfx::get_heard_volume( z.pos() ),
                                      sfx::get_heard_angle( z.pos() ) );
             target->add_msg_player_or_npc( msg_type, miss_msg_u,
                                            get_option<bool>( "LOG_MONSTER_ATTACK_MONSTER" ) ? miss_msg_npc : translation(),
                                            mon_name, body_part_name_accusative( bp_id ) );
             return true;
         }
     }
     // We need to do some calculations in the main function - we might mutate bp_hit
     // But first we need to handle exclusive grabs etc.
     std::optional<bodypart_id> grabbed_bp_id;
     if( is_grab ) {
         int eff_grab_strength = grab_data.grab_strength == -1 ? z.get_grab_strength() :
                                 grab_data.grab_strength;
         add_msg_debug( debugmode::DF_MATTACK,
                        "Grab attack targeting bp %s, grab strength %d, pull chance %d", bp_id->name,
                        eff_grab_strength, grab_data.pull_chance );
         // If we care iterate through grabs one by one, fail if we can't break one
         if( target->has_effect_with_flag( json_flag_GRAB ) && grab_data.exclusive_grab ) {
             add_msg_debug( debugmode::DF_MATTACK, "Exclusive grab, begin filtering" );
             map &here = get_map();
             const tripoint_range<tripoint> &surrounding = here.points_in_radius( target->pos(), 1, 0 );
             creature_tracker &creatures = get_creature_tracker();
             for( const effect &eff : target->get_effects_with_flag( json_flag_GRAB ) ) {
                 monster *grabber = nullptr;
                 // Iterate through the target's surroundings to find the grabber of this grab
                 for( const tripoint loc : surrounding ) {
                     monster *mon = creatures.creature_at<monster>( loc );
                     if( mon && mon->has_effect_with_flag( json_flag_GRAB_FILTER ) && mon->attack_target() == target ) {
                         if( target->is_monster() || ( !target->is_monster() &&
                                                       mon->is_grabbing( eff.get_bp().id() ) ) ) {
                             grabber = mon;
                             break;
                         }
                     }
                 }
                 // Ignore our own grab
                 if( grabber == &z ) {
                     add_msg_debug( debugmode::DF_MATTACK, "Grabber %s is the attacker, continue grab filtering",
                                    grabber->name() );
                     continue;
                 }
                 // Roll to remove anybody else's grab on our target
                 if( !x_in_y( eff_grab_strength / 2.0f, eff.get_intensity() ) ) {
                     target->add_msg_player_or_npc( msg_type,
                                                    _( "%1s tries to drag you, but something holds you in place!" ),
                                                    _( "%1s tries to drag <npcname>, but something holds them in place!" ),
                                                    z.disp_name( false, true ) );
                     return true;
                 } else {
                     target->remove_effect( eff.get_id(), eff.get_bp() );
                 }
             }
         }
         // No second grabs on monsters (exclusive grabs got rolled before this)
         if( target->is_monster() && target->has_effect_with_flag( json_flag_GRAB ) ) {
             add_msg_debug( debugmode::DF_MATTACK, "Target monster already grabbed, attack failed silently" );
             return false;
         }
         // Filter out already-grabbed bodyparts (after attempting to remove them, in any case)
         // Unless we're not actually trying to grab
         if( target->has_effect_with_flag( json_flag_GRAB, bp_id ) &&
             grab_data.grab_effect != effect_null ) {
             // Iterate through eligable targets to look for a non-grabbed one, fail if none are found
             add_msg_debug( debugmode::DF_MATTACK, "Target bodypart %s already grabbed",
                            bp_id->name );
             for( const bodypart_id bp : target->get_all_eligable_parts( hitsize_min, hitsize_max,
                     attack_upper ) ) {
                 if( target->has_effect_with_flag( json_flag_GRAB, bp ) ) {
                     add_msg_debug( debugmode::DF_MATTACK, "Alternative target bodypart %s already grabbed",
                                    bp->name );
                     continue;
                 } else {
                     bp_hit = bp.id();
                     bp_id = bp;
                     add_msg_debug( debugmode::DF_MATTACK, "Retargeted to ungrabbed %s",
                                    bp->name );
                 }
             }
             // Couldn't find an eligable limb, fail loudly
             if( target->has_effect_with_flag( json_flag_GRAB, bp_id ) ) {
                 target->add_msg_player_or_npc( msg_type, miss_msg_u, miss_msg_npc, mon_name,
                                                body_part_name_accusative( bp_id ) );
                 return true;
             }
         }
         int result = do_grab( z, target, bp_id );
         if( result < 0 ) {
             return false;
         } else if( result == 0 ) {
             return true;
         }
         grabbed_bp_id = bp_id;
     }
     // Damage instance calculation
     damage_instance damage = damage_max_instance;
     double multiplier = rng_float( min_mul, max_mul );
     add_msg_debug( debugmode::DF_MATTACK, "Damage multiplier %.1f (range %.1f - %.1f)", multiplier,
                    min_mul, max_mul );
     damage.mult_damage( multiplier );
     // Block our hit
     if( blockable ) {
         target->block_hit( &z, bp_id, damage );
     }
     // Take damage
     dealt_damage_instance dealt_damage = target->deal_damage( &z, bp_id, damage );
     dealt_damage.bp_hit = bp_id;
     // On hit effects
     target->on_hit( &z, bp_id );
     // Apply onhit self effects
     for( const mon_effect_data &eff : self_effects_onhit ) {
         if( x_in_y( eff.chance, 100 ) ) {
             z.add_effect( eff.id, time_duration::from_turns( rng( eff.duration.first, eff.duration.second ) ),
                           eff.permanent,
                           rng( eff.intensity.first, eff.intensity.second ) );
             target->add_msg_if_player( msg_type, eff.message, mon_name );
         }
     }
     int damage_total = dealt_damage.total_damage();
     add_msg_debug( debugmode::DF_MATTACK, "%s's melee_attack did %d damage", z.name(), damage_total );
     if( damage_total > 0 ) {
         on_damage( z, *target, dealt_damage );
     } else {
         sfx::play_variant_sound( "mon_bite", "bite_miss", sfx::get_heard_volume( z.pos() ),
                                  sfx::get_heard_angle( z.pos() ) );
         target->add_msg_player_or_npc( msg_type, no_dmg_msg_u,
                                        get_option<bool>( "LOG_MONSTER_ATTACK_MONSTER" ) ? no_dmg_msg_npc : translation(),
                                        mon_name, body_part_name_accusative( grabbed_bp_id.value_or( bp_id ) ) );
         if( !effects_require_dmg ) {
             for( const mon_effect_data &eff : effects ) {
                 if( x_in_y( eff.chance, 100 ) ) {
                     const bodypart_id affected_bp = eff.affect_hit_bp ? bp_id : eff.bp.id();
                     if( !( effects_require_organic && affected_bp->has_flag( json_flag_BIONIC_LIMB ) ) ) {
                         target->add_effect( eff.id, time_duration::from_turns( rng( eff.duration.first,
                                             eff.duration.second ) ), affected_bp, eff.permanent, rng( eff.intensity.first,
                                                     eff.intensity.second ) );
                     }
                 }
             }
         }
     }
     if( throw_strength > 0 ) {
         if( g->fling_creature( target, coord_to_angle( z.pos(), target->pos() ),
                                throw_strength ) ) {
             target->add_msg_player_or_npc( msg_type, throw_msg_u,
                                            get_option<bool>( "LOG_MONSTER_ATTACK_MONSTER" ) ? throw_msg_npc : translation(),
                                            mon_name );
             // Items strapped to you may fall off as you hit the ground
             // when you break out of a grab you have a chance to lose some things from your pockets
             // that are hanging off your character
             if( target->is_avatar() ) {
                 std::vector<item_pocket *> pd = target->as_character()->worn.grab_drop_pockets();
                 // if we have items that can be pulled off
                 if( !pd.empty() ) {
                     // choose an item to be ripped off
                     int index = rng( 0, pd.size() - 1 );
                     // the chance the monster knocks an item off
                     int chance = rng( 0, z.type->melee_sides * z.type->melee_dice );
                     // the chance the pocket resists
                     int sturdiness = rng( 0, pd[index]->get_pocket_data()->ripoff );
                     // the item is ripped off your character
                     if( sturdiness < chance ) {
                         float path_distance = rng_float( 0, 1.0 );
                         tripoint vector = target->pos() - z.pos();
                         vector = tripoint( vector.x * path_distance, vector.y * path_distance, vector.z * path_distance );
                         pd[index]->spill_contents( z.pos() + vector );
                         add_msg( m_bad, _( "As you hit the ground something comes loose and is knocked away from you!" ) );
                         popup( _( "As you hit the ground something comes loose and is knocked away from you!" ) );
                     }
                 }
             }
         }
     }
     return true;
 }
References _, accuracy, Creature::add_effect(), add_msg(), add_msg_debug, Creature::add_msg_if_player(), Creature::add_msg_player_or_npc(), Creature::as_character(), monster::attack_target(), attack_upper, Creature::block_hit(), blockable, body_part_name_accusative(), body_parts, bp, dealt_damage_instance::bp_hit, mattack_actor::condition, coord_to_angle(), creature_tracker::creature_at(), damage_max_instance, Creature::deal_damage(), Creature::deal_melee_attack(), debugmode::DF_MATTACK, dice(), monster::disp_name(), do_grab(), dodgeable, effect_null, effect_run, effects, effects_require_dmg, effects_require_organic, grab::exclusive_grab, find_target(), time_duration::from_turns(), g, Creature::get_all_eligable_parts(), get_creature_tracker(), Creature::get_effects_with_flag(), monster::get_grab_strength(), sfx::get_heard_angle(), sfx::get_heard_volume(), get_map(), get_player_character(), get_talker_for(), grab_data, outfit::grab_drop_pockets(), grab::grab_effect, grab::grab_strength, mattack_actor::has_condition, Creature::has_effect_with_flag(), body_part_type::has_flag(), monster::has_flag(), hitsize_max, hitsize_min, int_id< T >::id(), Creature::is_avatar(), is_grab, monster::is_grabbing(), Creature::is_monster(), json_flag_BIONIC_LIMB, json_flag_GRAB, json_flag_GRAB_FILTER, m_bad, m_info, m_mixed, m_warning, max_mul, mtype::melee_dice, mtype::melee_sides, mtype::melee_skill, min_mul, miss_msg_npc, miss_msg_u, Creature::mod_moves(), mon_flag_HIT_AND_RUN, move_cost, damage_instance::mult_damage(), body_part_type::name, monster::name(), no_dmg_msg_npc, no_dmg_msg_u, on_damage(), Creature::on_hit(), sfx::play_variant_sound(), map::points_in_radius(), popup(), Creature::pos(), grab::pull_chance, Creature::remove_effect(), rng(), rng_float(), Character::sees(), Creature::select_body_part(), self_effects_always, self_effects_onhit, throw_msg_npc, throw_msg_u, throw_strength, dealt_damage_instance::total_damage(), tripoint, monster::type, Creature::uncanny_dodge(), uncanny_dodgeable, Character::worn, tripoint::x, x_in_y(), tripoint::y, and tripoint::z.
clone()
std::unique_ptr< mattack_actor > melee_actor::clone () const override virtual
Implements mattack_actor.
Reimplemented in bite_actor.
Definition at line 962 of file mattack_actors.cpp.
 {
     return std::make_unique<melee_actor>( *this );
 }
do_grab()
int melee_actor::do_grab (monster & z, Creature * target, bodypart_id bp_id) const
Definition at line 465 of file mattack_actors.cpp.
 {
     // Something went wrong
     if( !target ) {
         return -1;
     }
     // Handle some messaging in-grab
     game_message_type msg_type = target->is_avatar() ? m_warning : m_info;
     const std::string mon_name = get_player_character().sees( z.pos() ) ?
                                  z.disp_name( false, true ) : _( "Something" );
     Character *foe = target->as_character();
     map &here = get_map();
     int eff_grab_strength = grab_data.grab_strength == -1 ? z.get_grab_strength() :
                             grab_data.grab_strength;
     add_msg_debug( debugmode::DF_MATTACK,
                    "Grab attack targeting bp %s, grab strength %d, pull chance %d", bp_id->name,
                    eff_grab_strength, grab_data.pull_chance );
     // Handle seatbelts and weight limits for pulls/drags TODO: tear you out depending on grab str?
     if( grab_data.pull_chance > -1 || grab_data.drag_distance > 0 ) {
         if( target->get_weight() > z.get_weight() * grab_data.pull_weight_ratio ) {
             target->add_msg_player_or_npc( msg_type, grab_data.pull_fail_msg_u, grab_data.pull_fail_msg_npc,
                                            mon_name );
             add_msg_debug( debugmode::DF_MATTACK, "Target weight %d g above weight limit  %.1f g, ",
                            to_gram( target->get_weight() ), to_gram( z.get_weight() ) * grab_data.pull_weight_ratio );
             return 0;
         }
         add_msg_debug( debugmode::DF_MATTACK, "Target weight %d g under weight limit  %.1f g, ",
                        to_gram( target->get_weight() ), to_gram( z.get_weight() ) * grab_data.pull_weight_ratio );
         const optional_vpart_position veh_part = here.veh_at( target->pos() );
         if( foe && foe->in_vehicle && veh_part ) {
             const std::optional<vpart_reference> vp_seatbelt = veh_part.avail_part_with_feature( "SEATBELT" );
             if( vp_seatbelt ) {
                 if( grab_data.respect_seatbelts ) {
                     z.mod_moves( -move_cost * 2 );
                     foe->add_msg_player_or_npc( msg_type, _( "%1s tries to drag you, but is stopped by your %2s!" ),
                                                 _( "%1s tries to drag <npcname>, but is stopped by their %2s!" ),
                                                 z.disp_name( false, true ), vp_seatbelt->part().name( false ) );
                     add_msg_debug( debugmode::DF_MATTACK, "Target on vehicle part with seatbelt, attack failed" );
                     return 0;
                 } else {
                     foe->add_msg_player_or_npc( msg_type, _( "%1s tears you out of your %2s!" ),
                                                 _( "%1s tears <npcname> out of their %2s!" ), z.disp_name( false, true ),
                                                 vp_seatbelt->part().name( false ) );
                     vp_seatbelt->vehicle().mod_hp( vp_seatbelt->part(), -2 );
                     add_msg_debug( debugmode::DF_MATTACK,
                                    "Target on vehicle part with seatbelt, attack does not respect seatbelts" );
                 }
             }
         }
     }
     // Check if we want to animate any of this or just teleport you over
     const bool animate = get_option<bool>( "ANIMATIONS" );
     // Let's see if we manage to pull if we are a pull in the first place
     if( grab_data.pull_chance > -1 && x_in_y( grab_data.pull_chance, 100 ) ) {
         add_msg_debug( debugmode::DF_MATTACK, "Pull chance roll succeeded" );
         int pull_range = std::min( range, rl_dist( z.pos(), target->pos() ) + 1 );
         tripoint pt = target->pos();
         while( pull_range > 0 ) {
             // Recalculate the ray each step
             // We can't depend on either the target position being constant (obviously),
             // but neither on z pos staying constant, because we may want to shift the map mid-pull
             const units::angle dir = coord_to_angle( target->pos(), z.pos() );
             tileray tdir( dir );
             tdir.advance();
             pt.x = target->posx() + tdir.dx();
             pt.y = target->posy() + tdir.dy();
             //Cancel the grab if the space is occupied by something
             if( !g->is_empty( pt ) ) {
                 break;
             }
             if( foe != nullptr ) {
                 if( foe->in_vehicle ) {
                     here.unboard_vehicle( foe->pos() );
                 }
                 if( foe->is_avatar() && ( pt.x < HALF_MAPSIZE_X || pt.y < HALF_MAPSIZE_Y ||
                                           pt.x >= HALF_MAPSIZE_X + SEEX || pt.y >= HALF_MAPSIZE_Y + SEEY ) ) {
                     g->update_map( pt.x, pt.y );
                 }
             }
             target->setpos( pt );
             pull_range--;
             if( animate ) {
                 g->invalidate_main_ui_adaptor();
                 inp_mngr.pump_events();
                 ui_manager::redraw_invalidated();
                 refresh_display();
             }
         }
         // If we're in a vehicle after being dragged, board us onto it
         // This prevents us from being run over by our own vehicle if we're dragged out of it
         if( foe != nullptr && !foe->in_vehicle &&
             here.veh_at( pt ).part_with_feature( VPFLAG_BOARDABLE, true ) ) {
             here.board_vehicle( pt, foe );
         }
         // The monster might drag a target that's not on it's z level
         // So if they leave them on open air, make them fall
         here.creature_on_trap( *target );
         target->add_msg_player_or_npc( msg_type, grab_data.pull_msg_u, grab_data.pull_msg_npc, mon_name,
                                        target->disp_name() );
     } else if( grab_data.pull_chance > -1 ) {
         // We failed the pull chance roll, return false to select a different attack
         add_msg_debug( debugmode::DF_MATTACK, "Pull chance roll failed.", grab_data.pull_chance );
         return -1;
     }
     if( grab_data.grab_effect != effect_null ) {
         if( foe ) {
             z.add_grab( bp_id.id() );
             add_msg_debug( debugmode::DF_MATTACK, "Added grabbing on %s",
                            bp_id->name );
             // Add grabbed - permanent, removal handled in try_remove_grab on move/wait
             target->add_effect( grab_data.grab_effect, 1_days, bp_id, true, eff_grab_strength );
         } else {
             // Monsters don't have limb scores, no need to target limbs
             target->add_effect( grab_data.grab_effect, 1_days, body_part_bp_null, true, eff_grab_strength );
             z.add_effect( effect_grabbing, 1_days, true, 1 );
         }
     }
     // Drag stuff
     if( grab_data.drag_distance > 0 ) {
         int distance = grab_data.drag_distance;
         while( distance > 0 ) {
             // Start with the opposite square
             tripoint opposite_square = z.pos() - ( target->pos() - z.pos() );
             // Keep track of our neighbors (no leaping)
             std::set<tripoint> neighbors;
             for( const tripoint &trp : here.points_in_radius( z.pos(), 1 ) ) {
                 if( trp != z.pos() && trp != target->pos() ) {
                     neighbors.insert( trp );
                 }
             }
             // Check where we get to consider dragging
             std::set<tripoint> candidates;
             for( const tripoint &trp : here.points_in_radius( opposite_square,
                     grab_data.drag_deviation ) ) {
                 if( trp != z.pos() && trp != target->pos() ) {
                     candidates.insert( trp );
                 }
             }
             // Select a random square from the options
             std::set<tripoint> intersect;
             std::set_intersection( neighbors.begin(), neighbors.end(), candidates.begin(), candidates.end(),
                                    std::inserter( intersect, intersect.begin() ) );
             std::set<tripoint>::iterator intersect_iter = intersect.begin();
             std::advance( intersect_iter, rng( 0, intersect.size() - 1 ) );
             tripoint target_square = random_entry<std::set<tripoint>>( intersect );
             if( z.can_move_to( target_square ) ) {
                 monster *zz = target->as_monster();
                 tripoint zpt = z.pos();
                 z.move_to( target_square, false, false, grab_data.drag_movecost_mod );
                 if( !g->is_empty( zpt ) ) { //Cancel the grab if the space is occupied by something
                     return 0;
                 }
                 if( target->is_avatar() && ( zpt.x < HALF_MAPSIZE_X ||
                                              zpt.y < HALF_MAPSIZE_Y ||
                                              zpt.x >= HALF_MAPSIZE_X + SEEX || zpt.y >= HALF_MAPSIZE_Y + SEEY ) ) {
                     g->update_map( zpt.x, zpt.y );
                 }
                 if( foe != nullptr ) {
                     if( foe->in_vehicle ) {
                         here.unboard_vehicle( foe->pos() );
                     }
                     foe->setpos( zpt );
                     if( !foe->in_vehicle && here.veh_at( zpt ).part_with_feature( VPFLAG_BOARDABLE, true ) ) {
                         here.board_vehicle( zpt, foe );
                     }
                 } else {
                     zz->setpos( zpt );
                 }
                 target->add_msg_player_or_npc( m_bad, _( "You are dragged behind the %s!" ),
                                                _( "<npcname> gets dragged behind the %s!" ), z.name() );
                 if( animate ) {
                     g->invalidate_main_ui_adaptor();
                     inp_mngr.pump_events();
                     ui_manager::redraw_invalidated();
                     refresh_display();
                 }
             } else {
                 target->add_msg_player_or_npc( m_good, _( "You resist the %s as it tries to drag you!" ),
                                                _( "<npcname> resist the %s as it tries to drag them!" ), z.name() );
                 return 0;
             }
             distance--;
             if( grab_data.drag_grab_break_distance > 0 && foe ) {
                 // Attempt to break the drag if we stepped the appropriate amount of distance
                 if( ( grab_data.drag_distance - distance ) % grab_data.drag_grab_break_distance == 0 ) {
                     if( foe->try_remove_grab() ) {
                         return 1;
                     } else {
                         target->set_moves( 0 );
                     }
                 }
             }
         }
     }
     return 1;
 }
References _, Creature::add_effect(), monster::add_grab(), add_msg_debug, Creature::add_msg_player_or_npc(), Character::add_msg_player_or_npc(), tileray::advance(), Creature::as_character(), Creature::as_monster(), optional_vpart_position::avail_part_with_feature(), map::board_vehicle(), body_part_bp_null, monster::can_move_to(), coord_to_angle(), map::creature_on_trap(), debugmode::DF_MATTACK, Creature::disp_name(), monster::disp_name(), grab::drag_deviation, grab::drag_distance, grab::drag_grab_break_distance, grab::drag_movecost_mod, tileray::dx(), tileray::dy(), effect_grabbing, effect_null, g, monster::get_grab_strength(), get_map(), get_player_character(), Creature::get_weight(), monster::get_weight(), grab_data, grab::grab_effect, grab::grab_strength, HALF_MAPSIZE_X, HALF_MAPSIZE_Y, int_id< T >::id(), Character::in_vehicle, inp_mngr, Creature::is_avatar(), m_bad, m_good, m_info, m_warning, min(), Creature::mod_moves(), move_cost, monster::move_to(), body_part_type::name, monster::name(), optional_vpart_position::part_with_feature(), map::points_in_radius(), Creature::pos(), Creature::posx(), Creature::posy(), grab::pull_chance, grab::pull_fail_msg_npc, grab::pull_fail_msg_u, grab::pull_msg_npc, grab::pull_msg_u, grab::pull_weight_ratio, input_manager::pump_events(), range, ui_manager::redraw_invalidated(), refresh_display(), grab::respect_seatbelts, rl_dist(), rng(), Character::sees(), SEEX, SEEY, Creature::set_moves(), Creature::setpos(), units::to_gram(), Character::try_remove_grab(), map::unboard_vehicle(), map::veh_at(), VPFLAG_BOARDABLE, tripoint::x, x_in_y(), and tripoint::y.
Referenced by call().
find_target()
Creature * melee_actor::find_target (monster & z) const virtual
Definition at line 440 of file mattack_actors.cpp.
 {
     if( !z.can_act() ) {
         return nullptr;
     }
     Creature *target = z.attack_target();
     if( target == nullptr || ( no_adjacent && z.is_adjacent( target, false ) ) ) {
         return nullptr;
     }
     if( range > 1 ) {
         if( !z.sees( *target ) ||
             !get_map().clear_path( z.pos(), target->pos(), range, 1, 200 ) ) {
             return nullptr;
         }
     } else if( !z.is_adjacent( target, false ) ) {
         return nullptr;
     }
     return target;
 }
References monster::attack_target(), monster::can_act(), get_map(), Creature::is_adjacent(), no_adjacent, Creature::pos(), range, and Creature::sees().
Referenced by call().
load_internal()
void melee_actor::load_internal (const JsonObject & obj, const std::string & src) override virtual
Implements mattack_actor.
Reimplemented in bite_actor.
Definition at line 347 of file mattack_actors.cpp.
 {
     // Optional:
     if( obj.has_array( "damage_max_instance" ) ) {
         damage_max_instance = load_damage_instance( obj.get_array( "damage_max_instance" ) );
     } else if( obj.has_object( "damage_max_instance" ) ) {
         damage_max_instance = load_damage_instance( obj );
     }
     optional( obj, was_loaded, "attack_chance", attack_chance, 100 );
     optional( obj, was_loaded, "accuracy", accuracy, INT_MIN );
     optional( obj, was_loaded, "min_mul", min_mul, 0.5f );
     optional( obj, was_loaded, "max_mul", max_mul, 1.0f );
     optional( obj, was_loaded, "move_cost", move_cost, 100 );
     optional( obj, was_loaded, "range", range, 1 );
     optional( obj, was_loaded, "no_adjacent", no_adjacent, false );
     optional( obj, was_loaded, "dodgeable", dodgeable, true );
     optional( obj, was_loaded, "uncanny_dodgeable", uncanny_dodgeable, dodgeable );
     optional( obj, was_loaded, "blockable", blockable, true );
     optional( obj, was_loaded, "effects_require_dmg", effects_require_dmg, true );
     optional( obj, was_loaded, "effects_require_organic", effects_require_organic, false );
     optional( obj, was_loaded, "grab", is_grab, false );
     optional( obj, was_loaded, "range", range, 1 );
     optional( obj, was_loaded, "throw_strength", throw_strength, 0 );
     optional( obj, was_loaded, "hitsize_min", hitsize_min, -1 );
     optional( obj, was_loaded, "hitsize_max", hitsize_max, -1 );
     optional( obj, was_loaded, "attack_upper", attack_upper, true );
     optional( obj, was_loaded, "miss_msg_u", miss_msg_u,
               to_translation( "%s lunges at you, but you dodge!" ) );
     optional( obj, was_loaded, "no_dmg_msg_u", no_dmg_msg_u,
               to_translation( "%1$s bites your %2$s, but fails to penetrate armor!" ) );
     optional( obj, was_loaded, "hit_dmg_u", hit_dmg_u,
               to_translation( "%1$s bites your %2$s!" ) );
     optional( obj, was_loaded, "miss_msg_npc", miss_msg_npc,
               to_translation( "%s lunges at <npcname>, but they dodge!" ) );
     optional( obj, was_loaded, "no_dmg_msg_npc", no_dmg_msg_npc,
               to_translation( "%1$s bites <npcname>'s %2$s, but fails to penetrate armor!" ) );
     optional( obj, was_loaded, "hit_dmg_npc", hit_dmg_npc,
               to_translation( "%1$s bites <npcname>'s %2$s!" ) );
     optional( obj, was_loaded, "throw_msg_u", throw_msg_u,
               to_translation( "%s hits you with such a force that it sends you flying!" ) );
     optional( obj, was_loaded, "throw_msg_npc", throw_msg_npc,
               to_translation( "%s hits <npcname> with such a force that it sends them flying!" ) );
     if( obj.has_member( "condition" ) ) {
         read_condition( obj, "condition", condition, false );
         has_condition = true;
     }
     if( is_grab ) {
         grab_data.load_grab( obj.get_object( "grab_data" ) );
     }
     if( obj.has_array( "body_parts" ) ) {
         for( JsonArray sub : obj.get_array( "body_parts" ) ) {
             const bodypart_str_id bp( sub.get_string( 0 ) );
             const float prob = sub.get_float( 1 );
             body_parts.add_or_replace( bp, prob );
         }
     }
     if( obj.has_array( "effects" ) ) {
         for( JsonObject eff : obj.get_array( "effects" ) ) {
             mon_effect_data effect;
             effect.load( eff );
             effects.push_back( std::move( effect ) );
         }
     }
     if( obj.has_array( "self_effects_always" ) ) {
         for( JsonObject eff : obj.get_array( "self_effects_always" ) ) {
             mon_effect_data effect;
             effect.load( eff );
             self_effects_always.push_back( std::move( effect ) );
         }
     }
     if( obj.has_array( "self_effects_onhit" ) ) {
         for( JsonObject eff : obj.get_array( "self_effects_onhit" ) ) {
             mon_effect_data effect;
             effect.load( eff );
             self_effects_onhit.push_back( std::move( effect ) );
         }
     }
     if( obj.has_array( "self_effects_ondmg" ) ) {
         for( JsonObject eff : obj.get_array( "self_effects_ondmg" ) ) {
             mon_effect_data effect;
             effect.load( eff );
             self_effects_ondmg.push_back( std::move( effect ) );
         }
     }
 }
References accuracy, mattack_actor::attack_chance, attack_upper, blockable, body_parts, bp, mattack_actor::condition, damage_max_instance, dodgeable, effects, effects_require_dmg, effects_require_organic, JsonObject::get_array(), JsonObject::get_object(), grab_data, JsonObject::has_array(), mattack_actor::has_condition, JsonObject::has_member(), JsonObject::has_object(), hit_dmg_npc, hit_dmg_u, hitsize_max, hitsize_min, is_grab, load_damage_instance(), grab::load_grab(), max_mul, min_mul, miss_msg_npc, miss_msg_u, move_cost, no_adjacent, no_dmg_msg_npc, no_dmg_msg_u, optional(), range, read_condition(), self_effects_always, self_effects_ondmg, self_effects_onhit, math_opers::sub(), throw_msg_npc, throw_msg_u, throw_strength, to_translation(), uncanny_dodgeable, and mattack_actor::was_loaded.
Referenced by bite_actor::load_internal().
on_damage()
void melee_actor::on_damage (monster & z, Creature & target, dealt_damage_instance & dealt) const virtual
Reimplemented in bite_actor.
Definition at line 923 of file mattack_actors.cpp.
 {
     if( target.is_avatar() ) {
         sfx::play_variant_sound( "mon_bite", "bite_hit", sfx::get_heard_volume( z.pos() ),
                                  sfx::get_heard_angle( z.pos() ) );
         sfx::do_player_death_hurt( dynamic_cast<Character &>( target ), false );
     }
     game_message_type msg_type = target.attitude_to( get_player_character() ) ==
                                  Creature::Attitude::FRIENDLY ?
                                  m_bad : m_neutral;
     const bodypart_id &bp = dealt.bp_hit ;
     const std::string mon_name = get_player_character().sees( z.pos() ) ?
                                  z.disp_name( false, true ) : _( "Something" );
     target.add_msg_player_or_npc( msg_type, hit_dmg_u,
                                   get_option<bool>( "LOG_MONSTER_ATTACK_MONSTER" ) ? hit_dmg_npc : translation(),
                                   mon_name, body_part_name_accusative( bp ) );
     for( const mon_effect_data &eff : effects ) {
         if( x_in_y( eff.chance, 100 ) ) {
             const bodypart_id affected_bp = eff.affect_hit_bp ? bp : eff.bp.id();
             if( !( effects_require_organic && affected_bp->has_flag( json_flag_BIONIC_LIMB ) ) ) {
                 target.add_effect( eff.id, time_duration::from_turns( rng( eff.duration.first,
                                    eff.duration.second ) ), affected_bp, eff.permanent, rng( eff.intensity.first,
                                            eff.intensity.second ) );
             }
         }
     }
     // Apply ondmg self effects
     for( const mon_effect_data &eff : self_effects_ondmg ) {
         if( x_in_y( eff.chance, 100 ) ) {
             z.add_effect( eff.id, time_duration::from_turns( rng( eff.duration.first, eff.duration.second ) ),
                           eff.permanent,
                           rng( eff.intensity.first, eff.intensity.second ) );
             target.add_msg_if_player( m_mixed, eff.message, mon_name );
         }
     }
 }
References _, Creature::add_effect(), Creature::add_msg_if_player(), Creature::add_msg_player_or_npc(), Creature::attitude_to(), body_part_name_accusative(), bp, dealt_damage_instance::bp_hit, monster::disp_name(), sfx::do_player_death_hurt(), effects, effects_require_organic, Creature::FRIENDLY, time_duration::from_turns(), sfx::get_heard_angle(), sfx::get_heard_volume(), get_player_character(), body_part_type::has_flag(), hit_dmg_npc, hit_dmg_u, int_id< T >::id(), Creature::is_avatar(), json_flag_BIONIC_LIMB, m_bad, m_mixed, m_neutral, sfx::play_variant_sound(), Creature::pos(), rng(), Character::sees(), self_effects_ondmg, and x_in_y().
Referenced by call(), and bite_actor::on_damage().
Member Data Documentation
accuracy
int melee_actor::accuracy = INT_MIN
Definition at line 119 of file mattack_actors.h.
Referenced by call(), and load_internal().
attack_upper
bool melee_actor::attack_upper = true
Definition at line 139 of file mattack_actors.h.
Referenced by call(), and load_internal().
blockable
bool melee_actor::blockable = true
Definition at line 129 of file mattack_actors.h.
Referenced by call(), and load_internal().
body_parts
weighted_float_list<bodypart_str_id> melee_actor::body_parts
If empty, regular melee roll body part selection is used.
If non-empty, a body part is selected from the map to be targeted, with a chance proportional to the value.
Definition at line 148 of file mattack_actors.h.
Referenced by call(), and load_internal().
damage_max_instance
damage_instance melee_actor::damage_max_instance
Definition at line 110 of file mattack_actors.h.
Referenced by call(), MonsterGenerator::check_monster_definitions(), load_internal(), and melee_actor().
dodgeable
bool melee_actor::dodgeable = true
Definition at line 125 of file mattack_actors.h.
Referenced by call(), and load_internal().
effects
std::vector<mon_effect_data> melee_actor::effects
Extra effects applied on hit.
Definition at line 151 of file mattack_actors.h.
Referenced by call(), load_internal(), and on_damage().
effects_require_dmg
bool melee_actor::effects_require_dmg = true
Definition at line 131 of file mattack_actors.h.
Referenced by call(), and load_internal().
effects_require_organic
bool melee_actor::effects_require_organic = false
Definition at line 133 of file mattack_actors.h.
Referenced by call(), load_internal(), and on_damage().
grab_data
grab melee_actor::grab_data
Definition at line 140 of file mattack_actors.h.
Referenced by call(), do_grab(), and load_internal().
hit_dmg_npc
translation melee_actor::hit_dmg_npc
Message for damaging hit against a non-player.
Definition at line 171 of file mattack_actors.h.
Referenced by load_internal(), and on_damage().
hit_dmg_u
translation melee_actor::hit_dmg_u
Message for damaging hit against the player.
Definition at line 162 of file mattack_actors.h.
Referenced by load_internal(), and on_damage().
hitsize_max
int melee_actor::hitsize_max = -1
Definition at line 138 of file mattack_actors.h.
Referenced by call(), and load_internal().
hitsize_min
int melee_actor::hitsize_min = -1
Definition at line 137 of file mattack_actors.h.
Referenced by call(), load_internal(), and bite_actor::load_internal().
is_grab
bool melee_actor::is_grab = false
Definition at line 141 of file mattack_actors.h.
Referenced by call(), and load_internal().
max_mul
float melee_actor::max_mul = 1.0f
Definition at line 114 of file mattack_actors.h.
Referenced by call(), load_internal(), and melee_actor().
min_mul
float melee_actor::min_mul = 0.5f
Definition at line 112 of file mattack_actors.h.
Referenced by call(), load_internal(), and melee_actor().
miss_msg_npc
translation melee_actor::miss_msg_npc
Message for missed attack against a non-player.
Definition at line 167 of file mattack_actors.h.
Referenced by call(), and load_internal().
miss_msg_u
translation melee_actor::miss_msg_u
Message for missed attack against the player.
Definition at line 158 of file mattack_actors.h.
Referenced by call(), and load_internal().
move_cost
int melee_actor::move_cost = 100
Definition at line 116 of file mattack_actors.h.
Referenced by call(), do_grab(), load_internal(), and melee_actor().
no_adjacent
bool melee_actor::no_adjacent = false
Definition at line 123 of file mattack_actors.h.
Referenced by find_target(), and load_internal().
no_dmg_msg_npc
translation melee_actor::no_dmg_msg_npc
Message for 0 damage hit against a non-player.
Definition at line 169 of file mattack_actors.h.
Referenced by call(), and load_internal().
no_dmg_msg_u
translation melee_actor::no_dmg_msg_u
Message for 0 damage hit against the player.
Definition at line 160 of file mattack_actors.h.
Referenced by call(), and load_internal().
range
int melee_actor::range = 1
Definition at line 121 of file mattack_actors.h.
Referenced by do_grab(), find_target(), and load_internal().
self_effects_always
std::vector<mon_effect_data> melee_actor::self_effects_always
Definition at line 153 of file mattack_actors.h.
Referenced by call(), and load_internal().
self_effects_ondmg
std::vector<mon_effect_data> melee_actor::self_effects_ondmg
Definition at line 155 of file mattack_actors.h.
Referenced by load_internal(), and on_damage().
self_effects_onhit
std::vector<mon_effect_data> melee_actor::self_effects_onhit
Definition at line 154 of file mattack_actors.h.
Referenced by call(), and load_internal().
throw_msg_npc
translation melee_actor::throw_msg_npc
Message for throwing a non-player.
Definition at line 173 of file mattack_actors.h.
Referenced by call(), and load_internal().
throw_msg_u
translation melee_actor::throw_msg_u
Message for throwing the player.
Definition at line 164 of file mattack_actors.h.
Referenced by call(), and load_internal().
throw_strength
int melee_actor::throw_strength = 0
Definition at line 135 of file mattack_actors.h.
Referenced by call(), and load_internal().
uncanny_dodgeable
bool melee_actor::uncanny_dodgeable = true
Definition at line 127 of file mattack_actors.h.
Referenced by call(), and load_internal().
The documentation for this class was generated from the following files:
src/mattack_actors.h
src/mattack_actors.cpp