Cataclysm DDA: try_sleep_activity_actor Class Reference
try_sleep_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
try_sleep_activity_actor (const time_duration &dur)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &, Character &who) override
Called just before Character::cancel_activity() executes.
void query_keep_trying (player_activity &act, Character &who)
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
bool disable_query = false
time_duration duration
Detailed Description
Definition at line 831 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
try_sleep_activity_actor()
try_sleep_activity_actor::try_sleep_activity_actor (const time_duration & dur) inline explicit
Definition at line 842 of file activity_actor_definitions.h.
 : duration( dur ) {}
Referenced by deserialize().
Member Function Documentation
canceled()
void try_sleep_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 3308 of file activity_actor.cpp.
 {
     if( who.movement_mode_is( move_mode_prone ) ) {
         who.set_movement_mode( move_mode_walk );
     }
 }
References move_mode_prone, move_mode_walk, Character::movement_mode_is(), and Character::set_movement_mode().
clone()
std::unique_ptr<activity_actor> try_sleep_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 855 of file activity_actor_definitions.h.
{
             return std::make_unique<try_sleep_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > try_sleep_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 3353 of file activity_actor.cpp.
 {
     try_sleep_activity_actor actor = try_sleep_activity_actor( 0_seconds );
     JsonObject data = jsin.get_object();
     data.read( "disable_query", actor.disable_query );
     data.read( "duration", actor.duration );
     return actor.clone();
 }
References clone(), disable_query, duration, JsonValue::get_object(), JsonObject::read(), and try_sleep_activity_actor().
do_turn()
void try_sleep_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 3277 of file activity_actor.cpp.
 {
     if( who.has_effect( effect_sleep ) ) {
         return;
     }
     if( who.can_sleep() ) {
         who.fall_asleep(); // calls act.set_to_null()
         if( !who.has_effect( effect_sleep ) ) {
             // Character can potentially have immunity for 'effect_sleep'
             who.add_msg_if_player(
                 _( "You feel you should've fallen asleep by now, but somehow you're still awake." ) );
         }
         return;
     }
     if( one_in( 1000 ) ) {
         who.add_msg_if_player( _( "You toss and turn…" ) );
     }
     if( calendar::once_every( 30_minutes ) ) {
         query_keep_trying( act, who );
     }
 }
References _, act, Character::add_msg_if_player(), Character::can_sleep(), effect_sleep, Character::fall_asleep(), Creature::has_effect(), calendar::once_every(), one_in(), and query_keep_trying().
finish()
void try_sleep_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 3299 of file activity_actor.cpp.
 {
     act.set_to_null();
     if( !who.has_effect( effect_sleep ) ) {
         who.add_msg_if_player( _( "You try to sleep, but can't." ) );
     }
     who.set_movement_mode( move_mode_walk );
 }
References _, act, Character::add_msg_if_player(), effect_sleep, Creature::has_effect(), move_mode_walk, and Character::set_movement_mode().
get_progress_message()
std::string try_sleep_activity_actor::get_progress_message (const player_activity & act) const inline override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 859 of file activity_actor_definitions.h.
{
             return std::string();
         }
get_type()
activity_id try_sleep_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 844 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_TRY_SLEEP" );
         }
References activity_id.
query_keep_trying()
void try_sleep_activity_actor::query_keep_trying (player_activity & act, Character & who)
Definition at line 3315 of file activity_actor.cpp.
 {
     if( disable_query || !who.is_avatar() ) {
         return;
     }
     uilist sleep_query;
     sleep_query.text = _( "You have trouble sleeping, keep trying?" );
     sleep_query.addentry( 1, true, 'S', _( "Stop trying to fall asleep and get up." ) );
     sleep_query.addentry( 2, true, 'c', _( "Continue trying to fall asleep." ) );
     sleep_query.addentry( 3, true, 'C',
                           _( "Continue trying to fall asleep and don't ask again." ) );
     sleep_query.query();
     switch( sleep_query.ret ) {
         case UILIST_CANCEL:
         case 1:
             act.set_to_null();
             who.set_movement_mode( move_mode_walk );
             break;
         case 3:
             disable_query = true;
             break;
         case 2:
         default:
             break;
     }
 }
References _, act, uilist::addentry(), disable_query, Creature::is_avatar(), move_mode_walk, uilist::query(), uilist::ret, Character::set_movement_mode(), uilist::text, and UILIST_CANCEL.
Referenced by do_turn().
serialize()
void try_sleep_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 3343 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "disable_query", disable_query );
     jsout.member( "duration", duration );
     jsout.end_object();
 }
References disable_query, duration, JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
start()
void try_sleep_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 3268 of file activity_actor.cpp.
 {
     act.moves_total = to_moves<int>( duration );
     act.moves_left = act.moves_total;
     get_event_bus().send<event_type::character_attempt_to_fall_asleep>( who.getID() );
     who.set_movement_mode( move_mode_prone );
     who.add_msg_if_player( _( "You lie down preparing to fall asleep." ) );
 }
References _, act, Character::add_msg_if_player(), character_attempt_to_fall_asleep, duration, get_event_bus(), Character::getID(), move_mode_prone, event_bus::send(), and Character::set_movement_mode().
Member Data Documentation
disable_query
bool try_sleep_activity_actor::disable_query = false private
Definition at line 834 of file activity_actor_definitions.h.
Referenced by deserialize(), query_keep_trying(), and serialize().
duration
time_duration try_sleep_activity_actor::duration private
Definition at line 835 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp