Cataclysm DDA: speed_description_value Class Reference
speed_description_value Class Reference
#include <speed_description.h>
Public Member Functions
void load (const JsonObject &jo)
void deserialize (const JsonObject &data)
double value () const
const std::vector< translation > & descriptions () const
Public Attributes
bool was_loaded = false
Private Attributes
double value_ = 0.00
std::vector< translation > descriptions_
Detailed Description
Definition at line 42 of file speed_description.h.
Member Function Documentation
descriptions()
const std::vector<translation>& speed_description_value::descriptions () const inline
Definition at line 54 of file speed_description.h.
{
             return descriptions_;
         }
References descriptions_.
deserialize()
void speed_description_value::deserialize (const JsonObject & data)
Definition at line 64 of file speed_description.cpp.
 {
     load( data );
 }
References load().
load()
void speed_description_value::load (const JsonObject & jo)
Definition at line 49 of file speed_description.cpp.
 {
     mandatory( jo, was_loaded, "value", value_ );
     if( value_ < 0.00 ) {
         jo.throw_error_at( "value", "value outside supported range" );
     }
     if( jo.has_array( "descriptions" ) ) {
         optional( jo, was_loaded, "descriptions", descriptions_ );
     } else if( jo.has_string( "descriptions" ) ) {
         translation description;
         optional( jo, was_loaded, "descriptions", description );
         descriptions_.emplace_back( description );
     }
 }
References descriptions_, JsonObject::has_array(), JsonObject::has_string(), mandatory, optional(), JsonObject::throw_error_at(), value_, and was_loaded.
Referenced by deserialize().
value()
double speed_description_value::value () const inline
Definition at line 50 of file speed_description.h.
{
             return value_;
         }
References value_.
Member Data Documentation
descriptions_
std::vector<translation> speed_description_value::descriptions_ private
Definition at line 60 of file speed_description.h.
Referenced by descriptions(), and load().
value_
double speed_description_value::value_ = 0.00 private
Definition at line 59 of file speed_description.h.
Referenced by load(), and value().
was_loaded
bool speed_description_value::was_loaded = false
Definition at line 46 of file speed_description.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/speed_description.h
src/speed_description.cpp