Cataclysm DDA: temp_crafting_inventory Class Reference
temp_crafting_inventory Class Reference
A transient add-only list of item references and temporary pseudo-items, that implements read_only_visitable and thus can answer crafting queries (see crafting.cpp and requirement_data::can_make_with_inventory).
#include <temp_crafting_inventory.h>
Public Member Functions
temp_crafting_inventory ()=default
temp_crafting_inventory (const read_only_visitable &)
size_t size () const
void clear ()
void add_item_ref (item &item)
Adds item reference to this container.
void add_all_ref (const read_only_visitable &v)
Adds all (top-level) items from the given visitable.
item & add_item_copy (const item &item)
Adds item copy to this container.
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const override
Traverses this object and any child items contained using a visitor pattern.
Public Member Functions inherited from read_only_visitable
item * find_parent (const item &it) const
Determine the immediate parent container (if any) for an item.
std::vector< item * > parents (const item &it) const
Returns vector of parent containers (if any) starting with the innermost.
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
virtual bool has_quality (const quality_id &qual, int level=1, int qty=1) const
Returns true if instance has amount (or more) items of at least quality level.
virtual int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
std::pair< int, int > kcal_range (const itype_id &id, const std::function< bool(const item &)> &filter, Character &player_character) const
virtual int charges_of (const itype_id &what, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >, const std::function< void(int)> &visitor=nullptr, bool in_tools=false) const
Count maximum available charges from this instance and any contained items.
virtual int amount_of (const itype_id &what, bool pseudo=true, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
virtual ~read_only_visitable ()=default
bool has_tools (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
bool has_components (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
virtual bool has_charges (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
Private Attributes
cata::colony< item * > items
cata::colony< item > temp_owned_items
Detailed Description
A transient add-only list of item references and temporary pseudo-items, that implements read_only_visitable and thus can answer crafting queries (see crafting.cpp and requirement_data::can_make_with_inventory).
Definition at line 16 of file temp_crafting_inventory.h.
Constructor & Destructor Documentation
temp_crafting_inventory() [1/2]
temp_crafting_inventory::temp_crafting_inventory () default
temp_crafting_inventory() [2/2]
temp_crafting_inventory::temp_crafting_inventory (const read_only_visitable & v) explicit
Definition at line 4 of file temp_crafting_inventory.cpp.
 {
     add_all_ref( v );
 }
References add_all_ref().
Member Function Documentation
add_all_ref()
void temp_crafting_inventory::add_all_ref (const read_only_visitable & v)
Adds all (top-level) items from the given visitable.
Note
container doesn't own the added references, meaning added items should outlive this container.
Definition at line 32 of file temp_crafting_inventory.cpp.
 {
     v.visit_items( [&]( item * it, item * ) {
         add_item_ref( *it );
         return VisitResponse::SKIP;
     } );
 }
References add_item_ref(), SKIP, and read_only_visitable::visit_items().
Referenced by temp_crafting_inventory().
add_item_copy()
item & temp_crafting_inventory::add_item_copy (const item & item)
Adds item copy to this container.
Container will own a copy of the given item.
Returns
reference to the added item within the container
Definition at line 25 of file temp_crafting_inventory.cpp.
 {
     const auto iter = temp_owned_items.insert( item );
     items.insert( &( *iter ) );
     return *iter;
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::insert(), items, and temp_owned_items.
Referenced by are_requirements_nearby().
add_item_ref()
void temp_crafting_inventory::add_item_ref (item & item)
Adds item reference to this container.
Note
container doesn't own the added reference, meaning added item should outlive this container.
Definition at line 20 of file temp_crafting_inventory.cpp.
 {
     items.insert( &item );
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::insert(), and items.
Referenced by add_all_ref(), and are_requirements_nearby().
clear()
void temp_crafting_inventory::clear ()
Definition at line 14 of file temp_crafting_inventory.cpp.
 {
     items.clear();
     temp_owned_items.clear();
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::clear(), items, and temp_owned_items.
size()
size_t temp_crafting_inventory::size () const
Definition at line 9 of file temp_crafting_inventory.cpp.
 {
     return items.size();
 }
References items, and cata::colony< element_type, element_allocator_type, element_skipfield_type >::size().
visit_items()
VisitResponse temp_crafting_inventory::visit_items (const std::function< VisitResponse(item *, item *)> & func) const override virtual
Traverses this object and any child items contained using a visitor pattern.
Note
Implement for each class that will implement the visitable interface. Other visit_items variants rely on this function.
Parameters
func visitor function called for each node which controls whether traversal continues. The first argument is the node and the second is the parent node (if any) The visitor function should return VisitResponse::Next to recursively process child items, VisitResponse::Skip to ignore children of the current node or VisitResponse::Abort to skip all remaining nodes
Returns
This method itself only ever returns VisitResponse::Next or VisitResponse::Abort.
Implements read_only_visitable.
Member Data Documentation
items
cata::colony<item *> temp_crafting_inventory::items private
Definition at line 51 of file temp_crafting_inventory.h.
Referenced by add_item_copy(), add_item_ref(), clear(), and size().
temp_owned_items
cata::colony<item> temp_crafting_inventory::temp_owned_items private
Definition at line 53 of file temp_crafting_inventory.h.
Referenced by add_item_copy(), and clear().
The documentation for this class was generated from the following files:
src/temp_crafting_inventory.h
src/temp_crafting_inventory.cpp