Cataclysm DDA: mapbuffer Class Reference
mapbuffer Class Reference
Store, buffer, save and load the entire world map.
#include <mapbuffer.h>
Public Member Functions
mapbuffer ()
~mapbuffer ()
void save (bool delete_after_save=false)
Store all submaps in this instance into savefiles.
void clear ()
Delete all buffered submaps.
void clear_outside_reality_bubble ()
Delete all buffered submaps except those inside the reality bubble.
bool add_submap (const tripoint_abs_sm &p, std::unique_ptr< submap > &sm)
Add a new submap to the buffer.
bool add_submap (const tripoint_abs_sm &p, submap *sm)
submap * lookup_submap (const tripoint_abs_sm &p)
Get a submap stored in this buffer.
submap_map_t::iterator begin ()
submap_map_t::iterator end ()
Private Types
using submap_map_t = std::map< tripoint_abs_sm, std::unique_ptr< submap > >
Private Member Functions
void remove_submap (const tripoint_abs_sm &addr)
submap * unserialize_submaps (const tripoint_abs_sm &p)
void deserialize (const JsonArray &ja)
void save_quad (const cata_path &dirname, const cata_path &filename, const tripoint_abs_omt &om_addr, std::list< tripoint_abs_sm > &submaps_to_delete, bool delete_after_save)
Private Attributes
submap_map_t submaps
Detailed Description
Store, buffer, save and load the entire world map.
Definition at line 19 of file mapbuffer.h.
Member Typedef Documentation
submap_map_t
using mapbuffer::submap_map_t = std::map<tripoint_abs_sm, std::unique_ptr<submap> > private
Definition at line 66 of file mapbuffer.h.
Constructor & Destructor Documentation
mapbuffer()
mapbuffer::mapbuffer () default
~mapbuffer()
mapbuffer::~mapbuffer () default
Member Function Documentation
add_submap() [1/2]
bool mapbuffer::add_submap (const tripoint_abs_sm & p, std::unique_ptr< submap > & sm)
Add a new submap to the buffer.
Parameters
p The absolute world position in submap coordinates. Same as the ones in lookup_submap.
sm The submap. If the submap has been added, the unique_ptr is released (set to NULL).
Returns
true if the submap has been stored here. False if there is already a submap with the specified coordinates. The submap is not stored and the given unique_ptr retains ownsership.
Definition at line 71 of file mapbuffer.cpp.
 {
     if( submaps.count( p ) ) {
         return false;
     }
     submaps[p] = std::move( sm );
     return true;
 }
References coords::sm, and submaps.
Referenced by add_submap(), deserialize(), generate_uniform(), and map::saven().
add_submap() [2/2]
bool mapbuffer::add_submap (const tripoint_abs_sm & p, submap * sm)
Definition at line 82 of file mapbuffer.cpp.
 {
     // FIXME: get rid of this overload and make submap ownership semantics sane.
     std::unique_ptr<submap> temp( sm );
     bool result = add_submap( p, temp );
     if( !result ) {
         // NOLINTNEXTLINE( bugprone-unused-return-value )
         temp.release();
     }
     return result;
 }
References add_submap(), coords::sm, and temp.
begin()
submap_map_t::iterator mapbuffer::begin () inline
Definition at line 69 of file mapbuffer.h.
{
             return submaps.begin();
         }
References submaps.
clear()
void mapbuffer::clear ()
Delete all buffered submaps.
Definition at line 53 of file mapbuffer.cpp.
 {
     submaps.clear();
 }
References submaps.
Referenced by game::check_mod_data(), main_menu::new_character_tab(), game::start_game(), and main_menu::world_tab().
clear_outside_reality_bubble()
void mapbuffer::clear_outside_reality_bubble ()
Delete all buffered submaps except those inside the reality bubble.
This exists for the sake of the tests to reduce their memory consumption; it's probably not sane to use in general gameplay.
Definition at line 58 of file mapbuffer.cpp.
 {
     map &here = get_map();
     auto it = submaps.begin();
     while( it != submaps.end() ) {
         if( here.inbounds( it->first ) ) {
             ++it;
         } else {
             it = submaps.erase( it );
         }
     }
 }
References get_map(), map::inbounds(), and submaps.
deserialize()
void mapbuffer::deserialize (const JsonArray & ja) private
Definition at line 307 of file mapbuffer.cpp.
 {
     for( JsonObject submap_json : ja ) {
         std::unique_ptr<submap> sm = std::make_unique<submap>();
         tripoint_abs_sm submap_coordinates;
         int version = 0;
         // We have to read version first because the iteration order of json members is undefined.
         if( submap_json.has_int( "version" ) ) {
             version = submap_json.get_int( "version" );
         }
         for( JsonMember submap_member : submap_json ) {
             std::string submap_member_name = submap_member.name();
             if( submap_member_name == "coordinates" ) {
                 JsonArray coords_array = submap_member;
                 tripoint_abs_sm loc{ coords_array.next_int(), coords_array.next_int(), coords_array.next_int() };
                 submap_coordinates = loc;
             } else {
                 sm->load( submap_member, submap_member_name, version );
             }
         }
         if( !add_submap( submap_coordinates, sm ) ) {
             debugmsg( "submap %s was already loaded", submap_coordinates.to_string() );
         }
     }
 }
References add_submap(), debugmsg, JsonArray::next_int(), coords::sm, and coords::coord_point_base< Point >::to_string().
Referenced by unserialize_submaps().
end()
submap_map_t::iterator mapbuffer::end () inline
Definition at line 72 of file mapbuffer.h.
{
             return submaps.end();
         }
References submaps.
lookup_submap()
submap * mapbuffer::lookup_submap (const tripoint_abs_sm & p)
Get a submap stored in this buffer.
Parameters
p The absolute world position in submap coordinates. Same as the ones in add_submap.
Returns
NULL if the submap is not in the mapbuffer and could not be loaded. The mapbuffer takes care of the returned submap object, don't delete it on your own.
Definition at line 104 of file mapbuffer.cpp.
 {
     dbg( D_INFO ) << "mapbuffer::lookup_submap( x[" << p.x() << "], y[" << p.y() << "], z["
                   << p.z() << "])";
     const auto iter = submaps.find( p );
     if( iter == submaps.end() ) {
         try {
             return unserialize_submaps( p );
         } catch( const std::exception &err ) {
             debugmsg( "Failed to load submap %s: %s", p.to_string(), err.what() );
         }
         return nullptr;
     }
     return iter->second.get();
 }
References D_INFO, dbg, debugmsg, submaps, coords::coord_point_base< Point >::to_string(), unserialize_submaps(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by timed_event::actualize(), overmap_ui::draw_ascii(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), vehicle::find_vehicle(), overmap::is_omt_generated(), is_sm_tile_outside(), is_sm_tile_over_water(), and map::loadn().
remove_submap()
void mapbuffer::remove_submap (const tripoint_abs_sm & addr) private
Definition at line 94 of file mapbuffer.cpp.
 {
     auto m_target = submaps.find( addr );
     if( m_target == submaps.end() ) {
         debugmsg( "Tried to remove non-existing submap %s", addr.to_string() );
         return;
     }
     submaps.erase( m_target );
 }
References debugmsg, submaps, and coords::coord_point_base< Point >::to_string().
Referenced by save().
save()
void mapbuffer::save (bool delete_after_save = false)
Store all submaps in this instance into savefiles.
Parameters
delete_after_save If true, the saved submaps are removed from the mapbuffer (and deleted).
Definition at line 122 of file mapbuffer.cpp.
 {
     assure_dir_exist( PATH_INFO::world_base_save_path() + "/maps" );
     int num_saved_submaps = 0;
     int num_total_submaps = submaps.size();
     map &here = get_map();
     static_popup popup;
     // A set of already-saved submaps, in global overmap coordinates.
     std::set<tripoint_abs_omt> saved_submaps;
     std::list<tripoint_abs_sm> submaps_to_delete;
     static constexpr std::chrono::milliseconds update_interval( 500 );
     std::chrono::steady_clock::time_point last_update = std::chrono::steady_clock::now();
     for( auto &elem : submaps ) {
         std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now();
         if( last_update + update_interval < now ) {
             popup.message( _( "Please wait as the map saves [%d/%d]" ),
                            num_saved_submaps, num_total_submaps );
             ui_manager::redraw();
             refresh_display();
             inp_mngr.pump_events();
             last_update = now;
         }
         // Whatever the coordinates of the current submap are,
         // we're saving a 2x2 quad of submaps at a time.
         // Submaps are generated in quads, so we know if we have one member of a quad,
         // we have the rest of it, if that assumption is broken we have REAL problems.
         const tripoint_abs_omt om_addr = project_to<coords::omt>( elem.first );
         if( saved_submaps.count( om_addr ) != 0 ) {
             // Already handled this one.
             continue;
         }
         saved_submaps.insert( om_addr );
         // A segment is a chunk of 32x32 submap quads.
         // We're breaking them into subdirectories so there aren't too many files per directory.
         // Might want to make a set for this one too so it's only checked once per save().
         const cata_path dirname = find_dirname( om_addr );
         const cata_path quad_path = find_quad_path( dirname, om_addr );
         bool inside_reality_bubble = here.inbounds( om_addr );
         // delete_on_save deletes everything, otherwise delete submaps
         // outside the current map.
         save_quad( dirname, quad_path, om_addr, submaps_to_delete,
                    delete_after_save || !inside_reality_bubble );
         num_saved_submaps += 4;
     }
     for( auto &elem : submaps_to_delete ) {
         remove_submap( elem );
     }
 }
References _, assure_dir_exist(), find_dirname(), find_quad_path(), get_map(), map::inbounds(), inp_mngr, popup(), input_manager::pump_events(), ui_manager::redraw(), refresh_display(), remove_submap(), save_quad(), submaps, and PATH_INFO::world_base_save_path().
Referenced by game::save_maps().
save_quad()
void mapbuffer::save_quad (const cata_path & dirname, const cata_path & filename, const tripoint_abs_omt & om_addr, std::list< tripoint_abs_sm > & submaps_to_delete, bool delete_after_save) private
Definition at line 178 of file mapbuffer.cpp.
 {
     std::vector<point> offsets;
     std::vector<tripoint_abs_sm> submap_addrs;
     offsets.push_back( point_zero );
     offsets.push_back( point_south );
     offsets.push_back( point_east );
     offsets.push_back( point_south_east );
     bool all_uniform = true;
     bool reverted_to_uniform = false;
     bool const file_exists = fs::exists( filename.get_unrelative_path() );
     for( point &offsets_offset : offsets ) {
         tripoint_abs_sm submap_addr = project_to<coords::sm>( om_addr );
         submap_addr += offsets_offset;
         submap_addrs.push_back( submap_addr );
         submap *sm = submaps[submap_addr].get();
         if( sm != nullptr ) {
             if( !sm->is_uniform() ) {
                 all_uniform = false;
             } else if( sm->reverted ) {
                 reverted_to_uniform = file_exists;
             }
         }
     }
     if( all_uniform ) {
         // Nothing to save - this quad will be regenerated faster than it would be re-read
         if( delete_after_save ) {
             for( auto &submap_addr : submap_addrs ) {
                 if( submaps.count( submap_addr ) > 0 && submaps[submap_addr] != nullptr ) {
                     submaps_to_delete.push_back( submap_addr );
                 }
             }
         }
         // deleting the file might fail on some platforms in some edge cases so force serialize this
         // uniform quad
         if( !reverted_to_uniform ) {
             return;
         }
     }
     // Don't create the directory if it would be empty
     assure_dir_exist( dirname );
     write_to_file( filename, [&]( std::ostream & fout ) {
         JsonOut jsout( fout );
         jsout.start_array();
         for( auto &submap_addr : submap_addrs ) {
             if( submaps.count( submap_addr ) == 0 ) {
                 continue;
             }
             submap *sm = submaps[submap_addr].get();
             if( sm == nullptr ) {
                 continue;
             }
             jsout.start_object();
             jsout.member( "version", savegame_version );
             jsout.member( "coordinates" );
             jsout.start_array();
             jsout.write( submap_addr.x() );
             jsout.write( submap_addr.y() );
             jsout.write( submap_addr.z() );
             jsout.end_array();
             sm->store( jsout );
             jsout.end_object();
             if( delete_after_save ) {
                 submaps_to_delete.push_back( submap_addr );
             }
         }
         jsout.end_array();
     } );
     if( all_uniform && reverted_to_uniform ) {
         fs::remove( filename.get_unrelative_path() );
     }
 }
References assure_dir_exist(), JsonOut::end_array(), JsonOut::end_object(), cata_path::get_unrelative_path(), JsonOut::member(), offsets, point_east, point_south, point_south_east, point_zero, savegame_version, coords::sm, JsonOut::start_array(), JsonOut::start_object(), submaps, JsonOut::write(), and write_to_file().
Referenced by save().
unserialize_submaps()
submap * mapbuffer::unserialize_submaps (const tripoint_abs_sm & p) private
Definition at line 269 of file mapbuffer.cpp.
 {
     // Map the tripoint to the submap quad that stores it.
     const tripoint_abs_omt om_addr = project_to<coords::omt>( p );
     const cata_path dirname = find_dirname( om_addr );
     cata_path quad_path = find_quad_path( dirname, om_addr );
     if( !file_exist( quad_path ) ) {
         // Fix for old saves where the path was generated using std::stringstream, which
         // did format the number using the current locale. That formatting may insert
         // thousands separators, so the resulting path is "map/1,234.7.8.map" instead
         // of "map/1234.7.8.map".
         std::ostringstream buffer;
         buffer << om_addr.x() << "." << om_addr.y() << "." << om_addr.z()
                << ".map";
         cata_path legacy_quad_path = dirname / buffer.str();
         if( file_exist( legacy_quad_path ) ) {
             quad_path = std::move( legacy_quad_path );
         }
     }
     if( !read_from_file_optional_json( quad_path, [this]( const JsonValue & jsin ) {
     deserialize( jsin );
     } ) ) {
         // If it doesn't exist, trigger generating it.
         return nullptr;
     }
     // fill in uniform submaps that were not serialized
     oter_id const oid = overmap_buffer.ter( om_addr );
     generate_uniform_omt( project_to<coords::sm>( om_addr ), oid );
     if( submaps.count( p ) == 0 ) {
         debugmsg( "file %s did not contain the expected submap %s for non-uniform terrain %s",
                   quad_path.generic_u8string(), p.to_string(), oid.id().str() );
         return nullptr;
     }
     return submaps[ p ].get();
 }
References debugmsg, deserialize(), file_exist(), find_dirname(), find_quad_path(), generate_uniform_omt(), cata_path::generic_u8string(), int_id< T >::id(), overmap_buffer, read_from_file_optional_json(), string_id< T >::str(), submaps, overmapbuffer::ter(), coords::coord_point_base< Point >::to_string(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by lookup_submap().
Member Data Documentation
submaps
submap_map_t mapbuffer::submaps private
Definition at line 86 of file mapbuffer.h.
Referenced by add_submap(), begin(), clear(), clear_outside_reality_bubble(), end(), lookup_submap(), remove_submap(), save(), save_quad(), and unserialize_submaps().
The documentation for this class was generated from the following files:
src/mapbuffer.h
src/mapbuffer.cpp