Cataclysm DDA: wish_monster_callback Class Reference
wish_monster_callback Class Reference
Public Member Functions
wish_monster_callback (const std::vector< const mtype * > &mtypes)
bool key (const input_context &, const input_event &event, int, uilist *) override
void refresh (uilist *menu) override
~wish_monster_callback () override=default
Public Member Functions inherited from uilist_callback
virtual void select (uilist *)
After a new item is selected, call this once.
virtual ~uilist_callback ()=default
Public Attributes
int lastent
std::string msg
bool friendly
bool hallucination
int group
monster tmp
const std::vector< const mtype * > & mtypes
Detailed Description
Definition at line 641 of file wish.cpp.
Constructor & Destructor Documentation
wish_monster_callback()
wish_monster_callback::wish_monster_callback (const std::vector< const mtype * > & mtypes) inline explicit
Definition at line 657 of file wish.cpp.
             : mtypes( mtypes ) {
             friendly = false;
             hallucination = false;
             group = 0;
             lastent = -2;
         }
References friendly, group, hallucination, and lastent.
~wish_monster_callback()
wish_monster_callback::~wish_monster_callback () override default
Member Function Documentation
key()
bool wish_monster_callback::key (const input_context & , const input_event & event, int , uilist *) inline override virtual
Reimplemented from uilist_callback.
Definition at line 665 of file wish.cpp.
{
             if( event.get_first_input() == 'f' ) {
                 friendly = !friendly;
                 // Force tmp monster regen
                 lastent = -2;
                 // Tell menu we handled keypress
                 return true;
             } else if( event.get_first_input() == 'i' ) {
                 group++;
                 return true;
             } else if( event.get_first_input() == 'h' ) {
                 hallucination = !hallucination;
                 return true;
             } else if( event.get_first_input() == 'd' && group != 0 ) {
                 group--;
                 return true;
             }
             return false;
         }
References friendly, input_event::get_first_input(), group, hallucination, and lastent.
refresh()
void wish_monster_callback::refresh (uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 686 of file wish.cpp.
{
             catacurses::window w_info = catacurses::newwin( menu->w_height - 2, menu->pad_right,
                                         point( menu->w_x + menu->w_width - 1 - menu->pad_right, 1 ) );
             const int entnum = menu->selected;
             const bool valid_entnum = entnum >= 0 && static_cast<size_t>( entnum ) < mtypes.size();
             if( entnum != lastent ) {
                 lastent = entnum;
                 if( valid_entnum ) {
                     tmp = monster( mtypes[ entnum ]->id );
                     if( friendly ) {
                         tmp.friendly = -1;
                     }
                 } else {
                     tmp = monster();
                 }
             }
             werase( w_info );
             if( valid_entnum ) {
                 tmp.print_info( w_info, 2, 5, 1 );
                 std::string header = string_format( "#%d: %s (%d)%s", entnum, tmp.type->id.str(),
                                                     group, hallucination ? _( " (hallucination)" ) : "" );
                 mvwprintz( w_info, point( ( getmaxx( w_info ) - utf8_width( header ) ) / 2, 0 ), c_cyan, header );
             }
             mvwprintz( w_info, point( 0, getmaxy( w_info ) - 3 ), c_green, msg );
             msg.clear();
             input_context ctxt( menu->input_category, keyboard_mode::keycode );
             mvwprintw( w_info, point( 0, getmaxy( w_info ) - 2 ),
                        _( "[%s] find, [f]riendly, [h]allucination, [i]ncrease group, [d]ecrease group, [%s] quit" ),
                        ctxt.get_desc( "FILTER" ), ctxt.get_desc( "QUIT" ) );
             wnoutrefresh( w_info );
         }
References _, c_cyan, c_green, monster::friendly, friendly, input_context::get_desc(), catacurses::getmaxx(), catacurses::getmaxy(), group, hallucination, mtype::id, uilist::input_category, keycode, lastent, msg, mtypes, catacurses::mvwprintw(), mvwprintz(), catacurses::newwin(), uilist::pad_right, point, monster::print_info(), uilist::selected, string_id< T >::str(), string_format(), tmp, monster::type, utf8_width(), uilist::w_height, uilist::w_width, uilist::w_x, catacurses::werase(), and catacurses::wnoutrefresh().
Member Data Documentation
friendly
bool wish_monster_callback::friendly
Definition at line 649 of file wish.cpp.
Referenced by key(), refresh(), wish_monster_callback(), and debug_menu::wishmonster().
group
int wish_monster_callback::group
Definition at line 652 of file wish.cpp.
Referenced by key(), refresh(), wish_monster_callback(), and debug_menu::wishmonster().
hallucination
bool wish_monster_callback::hallucination
Definition at line 650 of file wish.cpp.
Referenced by key(), refresh(), wish_monster_callback(), and debug_menu::wishmonster().
lastent
int wish_monster_callback::lastent
Definition at line 645 of file wish.cpp.
Referenced by key(), refresh(), and wish_monster_callback().
msg
std::string wish_monster_callback::msg
Definition at line 647 of file wish.cpp.
Referenced by refresh(), and debug_menu::wishmonster().
mtypes
const std::vector<const mtype *>& wish_monster_callback::mtypes
Definition at line 655 of file wish.cpp.
Referenced by refresh().
tmp
monster wish_monster_callback::tmp
Definition at line 654 of file wish.cpp.
Referenced by refresh().
The documentation for this class was generated from the following file:
src/wish.cpp