Cataclysm DDA: rotation_guard Class Reference
rotation_guard Class Reference
Public Member Functions
rotation_guard (const mapgendata &md)
~rotation_guard ()
Private Attributes
const mapgendata & md
const int rotation
Detailed Description
Definition at line 7863 of file mapgen.cpp.
Constructor & Destructor Documentation
rotation_guard()
rotation_guard::rotation_guard (const mapgendata & md) inline explicit
Definition at line 7866 of file mapgen.cpp.
             : md( md ), rotation( oter_get_rotation( md.terrain_type() ) ) {
             // If the existing map is rotated, we need to rotate it back to the north
             // orientation before applying our updates.
             if( rotation != 0 && !md.has_flag( jmapgen_flags::no_underlying_rotate ) ) {
                 md.m.rotate( rotation, true );
             }
         }
References mapgendata::has_flag(), mapgendata::m, md, no_underlying_rotate, map::rotate(), and rotation.
~rotation_guard()
rotation_guard::~rotation_guard () inline
Definition at line 7875 of file mapgen.cpp.
{
             // If we rotated the map before applying updates, we now need to rotate
             // it back to where we found it.
             if( rotation != 0 && !md.has_flag( jmapgen_flags::no_underlying_rotate ) ) {
                 md.m.rotate( 4 - rotation, true );
             }
         }
References mapgendata::has_flag(), mapgendata::m, md, no_underlying_rotate, map::rotate(), and rotation.
Member Data Documentation
md
const mapgendata& rotation_guard::md private
Definition at line 7883 of file mapgen.cpp.
Referenced by rotation_guard(), and ~rotation_guard().
rotation
const int rotation_guard::rotation private
Definition at line 7884 of file mapgen.cpp.
Referenced by rotation_guard(), and ~rotation_guard().
The documentation for this class was generated from the following file:
src/mapgen.cpp