Cataclysm DDA: selection_line Class Reference
selection_line Class Reference
Public Member Functions
selection_line ()=default
selection_line (const std::string &text, const std::string &desc_str, const int max_width)
std::string print ()
std::string description ()
void set_detail (const std::string &header, const std::string &detail)
std::pair< std::string, std::string > get_detail ()
int get_row_count () const
void set_highlight ()
bool highlighted () const
Private Attributes
std::string header_str
std::string desc_str
std::pair< std::string, std::string > detail_str
int row_count
bool highlight_line = false
Detailed Description
Definition at line 37 of file medical_ui.cpp.
Constructor & Destructor Documentation
selection_line() [1/2]
selection_line::selection_line () default
selection_line() [2/2]
selection_line::selection_line (const std::string & text, const std::string & desc_str, const int max_width) inline
Definition at line 41 of file medical_ui.cpp.
             : desc_str( desc_str ) {
             std::vector<std::string> textformatted = foldstring( text, max_width,
                     ']' );
             row_count = textformatted.size();
             if( row_count > 1 ) {
                 //If there are too many tags, display them neatly on a new line.
                 std::string print_line = string_format( "%s\n", textformatted[0] );
                 for( int i = 1; i < row_count; i++ ) {
                     if( i != row_count ) {
                         print_line += string_format( "->%s\n", textformatted[i] );
                     } else {
                         print_line += string_format( "->%s", textformatted[i] );
                     }
                 }
                 header_str = print_line;
             } else {
                 header_str = text;
             }
         }
References foldstring(), header_str, row_count, and string_format().
Member Function Documentation
description()
std::string selection_line::description () inline
Definition at line 69 of file medical_ui.cpp.
{
             return desc_str;
         }
References desc_str.
Referenced by avatar::disp_medical().
get_detail()
std::pair<std::string, std::string> selection_line::get_detail () inline
Definition at line 77 of file medical_ui.cpp.
{
             return detail_str;
         }
References detail_str.
get_row_count()
int selection_line::get_row_count () const inline
Definition at line 81 of file medical_ui.cpp.
{
             return row_count;
         }
References row_count.
highlighted()
bool selection_line::highlighted () const inline
Definition at line 89 of file medical_ui.cpp.
{
             return highlight_line;
         }
References highlight_line.
print()
std::string selection_line::print () inline
Definition at line 62 of file medical_ui.cpp.
{
             if( highlight_line ) {
                 header_str = colorize( ">", h_white ) + header_str;
             }
             return header_str;
         }
References colorize(), h_white, header_str, and highlight_line.
set_detail()
void selection_line::set_detail (const std::string & header, const std::string & detail) inline
Definition at line 73 of file medical_ui.cpp.
{
             detail_str = std::pair<std::string, std::string>( header, detail );
         }
References detail_str.
Referenced by draw_stats_summary().
set_highlight()
void selection_line::set_highlight () inline
Definition at line 85 of file medical_ui.cpp.
{
             highlight_line = true;
         }
References highlight_line.
Member Data Documentation
desc_str
std::string selection_line::desc_str private
Definition at line 95 of file medical_ui.cpp.
Referenced by description().
detail_str
std::pair<std::string, std::string> selection_line::detail_str private
Definition at line 96 of file medical_ui.cpp.
Referenced by get_detail(), and set_detail().
header_str
std::string selection_line::header_str private
Definition at line 94 of file medical_ui.cpp.
Referenced by print(), and selection_line().
highlight_line
bool selection_line::highlight_line = false private
Definition at line 98 of file medical_ui.cpp.
Referenced by highlighted(), print(), and set_highlight().
row_count
int selection_line::row_count private
Definition at line 97 of file medical_ui.cpp.
Referenced by get_row_count(), and selection_line().
The documentation for this class was generated from the following file:
src/medical_ui.cpp