Cataclysm DDA: int_id_set< T, kFastSize > Class Template Reference
int_id_set< T, kFastSize > Class Template Reference
#include <int_id.h>
Public Member Functions
template<typename... Ts>
void emplace (Ts &&... ts)
void insert (int_id< T > id)
void erase (int_id< T > id)
bool contains (int_id< T > id) const
void clear ()
Private Attributes
std::bitset< kFastSize > fast_set_
std::unordered_set< int_id< T > > slow_set_
Detailed Description
template<typename T, std::size_t kFastSize>
class int_id_set< T, kFastSize >
Definition at line 126 of file int_id.h.
Member Function Documentation
clear()
template<typename T , std::size_t kFastSize> void int_id_set< T, kFastSize >::clear () inline
Definition at line 161 of file int_id.h.
                      {
             fast_set_.reset();
             slow_set_.clear();
         }
References int_id_set< T, kFastSize >::fast_set_, and int_id_set< T, kFastSize >::slow_set_.
Referenced by MonsterGenerator::finalize_mtypes(), and MonsterGenerator::generate_fake_pseudo_dormant_monster().
contains()
template<typename T , std::size_t kFastSize> bool int_id_set< T, kFastSize >::contains (int_id< T > id) const inline
Definition at line 152 of file int_id.h.
{
             const std::size_t i = static_cast<std::size_t>( id.to_i() );
             if( i < fast_set_.size() ) {
                 return fast_set_[i];
             } else {
                 return slow_set_.count( id );
             }
         }
References int_id_set< T, kFastSize >::fast_set_, and int_id_set< T, kFastSize >::slow_set_.
Referenced by mtype::has_flag().
emplace()
template<typename T , std::size_t kFastSize> template<typename... Ts> void int_id_set< T, kFastSize >::emplace (Ts &&... ts) inline
Definition at line 130 of file int_id.h.
{
             insert( int_id<T>( std::forward<Ts>( ts )... ) );
         }
References int_id_set< T, kFastSize >::insert().
Referenced by MonsterGenerator::apply_species_attributes(), MonsterGenerator::finalize_mtypes(), MonsterGenerator::generate_fake_pseudo_dormant_monster(), and mtype::set_flag().
erase()
template<typename T , std::size_t kFastSize> void int_id_set< T, kFastSize >::erase (int_id< T > id) inline
Definition at line 143 of file int_id.h.
{
             const std::size_t i = static_cast<std::size_t>( id.to_i() );
             if( i < fast_set_.size() ) {
                 fast_set_[i] = false;
             } else {
                 slow_set_.erase( id );
             }
         }
References int_id_set< T, kFastSize >::fast_set_, and int_id_set< T, kFastSize >::slow_set_.
Referenced by mtype::set_flag().
insert()
template<typename T , std::size_t kFastSize> void int_id_set< T, kFastSize >::insert (int_id< T > id) inline
Definition at line 134 of file int_id.h.
{
             const std::size_t i = static_cast<std::size_t>( id.to_i() );
             if( i < fast_set_.size() ) {
                 fast_set_[i] = true;
             } else {
                 slow_set_.insert( id );
             }
         }
References int_id_set< T, kFastSize >::fast_set_, and int_id_set< T, kFastSize >::slow_set_.
Referenced by int_id_set< T, kFastSize >::emplace().
Member Data Documentation
fast_set_
template<typename T , std::size_t kFastSize> std::bitset<kFastSize> int_id_set< T, kFastSize >::fast_set_ private
Definition at line 167 of file int_id.h.
Referenced by int_id_set< T, kFastSize >::clear(), int_id_set< T, kFastSize >::contains(), int_id_set< T, kFastSize >::erase(), and int_id_set< T, kFastSize >::insert().
slow_set_
template<typename T , std::size_t kFastSize> std::unordered_set<int_id<T> > int_id_set< T, kFastSize >::slow_set_ private
Definition at line 168 of file int_id.h.
Referenced by int_id_set< T, kFastSize >::clear(), int_id_set< T, kFastSize >::contains(), int_id_set< T, kFastSize >::erase(), and int_id_set< T, kFastSize >::insert().
The documentation for this class was generated from the following file:
src/int_id.h