Cataclysm DDA: border_helper::border_info Class Reference
border_helper::border_info Class Reference
#include <output.h>
Public Member Functions
void set (const point &pos, const point &size)
border_info (const border_info &)=delete
border_info (border_info &&)=default
border_info & operator= (const border_info &)=delete
border_info & operator= (border_info &&)=default
Private Member Functions
border_info (border_helper &helper)
Private Attributes
point pos
point size
std::reference_wrapper< border_helper > helper
Friends
class border_helper
Detailed Description
Definition at line 382 of file output.h.
Constructor & Destructor Documentation
border_info() [1/3]
border_helper::border_info::border_info (const border_info &) delete
border_info() [2/3]
border_helper::border_info::border_info (border_info &&) default
border_info() [3/3]
border_helper::border_info::border_info (border_helper & helper) explicit private
Definition at line 715 of file output.cpp.
     : helper( helper )
 {
 }
Member Function Documentation
operator=() [1/2]
border_info& border_helper::border_info::operator= (border_info &&) default
operator=() [2/2]
border_info& border_helper::border_info::operator= (const border_info &) delete
set()
void border_helper::border_info::set (const point & pos, const point & size)
Definition at line 720 of file output.cpp.
 {
     this->pos = pos;
     this->size = size;
     helper.get().border_connection_map.reset();
 }
References math_opers::pos(), and om_direction::size.
Referenced by Character::disp_info(), and bodygraph_display::init_ui_windows().
Friends And Related Function Documentation
border_helper
friend class border_helper friend
Definition at line 393 of file output.h.
Member Data Documentation
helper
std::reference_wrapper<border_helper> border_helper::border_info::helper private
Definition at line 399 of file output.h.
pos
point border_helper::border_info::pos private
Definition at line 397 of file output.h.
size
point border_helper::border_info::size private
Definition at line 398 of file output.h.
The documentation for this class was generated from the following files:
src/output.h
src/output.cpp