Cataclysm DDA: material_type Class Reference
material_type Class Reference
#include <material.h>
Public Member Functions
material_type ()
void load (const JsonObject &jsobj, std::string_view src)
void check () const
material_id ident () const
std::string name () const
std::optional< itype_id > salvaged_into () const
itype_id repaired_with () const
float resist (const damage_type_id &dmg_type) const
bool has_dedicated_resist (const damage_type_id &dmg_type) const
std::string bash_dmg_verb () const
std::string cut_dmg_verb () const
std::string dmg_adj (int damage_level) const
int chip_resist () const
int repair_difficulty () const
float specific_heat_liquid () const
float specific_heat_solid () const
float latent_heat () const
float freeze_point () const
float density () const
bool is_conductive () const
bool is_valid_thickness (float thickness) const
float thickness_multiple () const
int breathability () const
std::optional< int > wind_resist () const
bool edible () const
bool rotting () const
bool soft () const
bool uncomfortable () const
double vitamin (const vitamin_id &id) const
fuel_data get_fuel_data () const
const mat_burn_data & burn_data (size_t intensity) const
const mat_burn_products & burn_products () const
Static Public Member Functions
static void finalize_all ()
static int breathability_to_rating (breathability_rating breathability)
Public Attributes
material_id id
std::vector< std::pair< material_id, mod_id > > src
bool was_loaded = false
Private Attributes
translation _name
std::optional< itype_id > _salvaged_into
itype_id _repaired_with = itype_id("null")
resistances _resistances
std::vector< damage_type_id > _res_was_loaded
int _chip_resist = 0
float _density = 1
breathability_rating _breathability = breathability_rating::IMPERMEABLE
std::optional< int > _wind_resist
float _specific_heat_liquid = 4.186f
float _specific_heat_solid = 2.108f
float _latent_heat = 334.0f
float _freeze_point = 0
bool _edible = false
bool _rotting = false
bool _soft = false
bool _uncomfortable = false
bool _conductive = false
float _sheet_thickness = 0.0f
int _repair_difficulty = 10
translation _bash_dmg_verb
translation _cut_dmg_verb
std::vector< translation > _dmg_adj
std::map< vitamin_id, double > _vitamins
std::vector< mat_burn_data > _burn_data
fuel_data fuel
mat_burn_products _burn_products
Detailed Description
Definition at line 70 of file material.h.
Constructor & Destructor Documentation
material_type()
material_type::material_type ()
Definition at line 62 of file material.cpp.
                              :
     id( material_id::NULL_ID() ),
     _bash_dmg_verb( to_translation( "damages" ) ),
     _cut_dmg_verb( to_translation( "damages" ) )
 {
     _dmg_adj = { to_translation( "lightly damaged" ), to_translation( "damaged" ), to_translation( "very damaged" ), to_translation( "thoroughly damaged" ) };
 }
References _dmg_adj, and to_translation().
Member Function Documentation
bash_dmg_verb()
std::string material_type::bash_dmg_verb () const
Definition at line 225 of file material.cpp.
 {
     return _bash_dmg_verb.translated();
 }
References _bash_dmg_verb, and translation::translated().
Referenced by Character::describe_damage().
breathability()
int material_type::breathability () const
Definition at line 321 of file material.cpp.
 {
     return material_type::breathability_to_rating( _breathability );
 }
References _breathability, and breathability_to_rating().
Referenced by breathability_to_rating().
breathability_to_rating()
int material_type::breathability_to_rating (breathability_rating breathability) static
Definition at line 300 of file material.cpp.
 {
     // this is where the values for each of these exist
     switch( breathability ) {
         case breathability_rating::IMPERMEABLE:
             return 0;
         case breathability_rating::POOR:
             return 30;
         case breathability_rating::AVERAGE:
             return 50;
         case breathability_rating::GOOD:
             return 80;
         case breathability_rating::MOISTURE_WICKING:
             return 110;
         case breathability_rating::SECOND_SKIN:
             return 140;
         case breathability_rating::last:
             break;
     }
     return 0;
 }
References AVERAGE, breathability(), GOOD, IMPERMEABLE, last, MOISTURE_WICKING, POOR, and SECOND_SKIN.
Referenced by breathability(), and armor_portion_data::deserialize().
burn_data()
const mat_burn_data & material_type::burn_data (size_t intensity) const
Definition at line 356 of file material.cpp.
 {
     return _burn_data[ std::min<size_t>( intensity, _burn_data.size() ) - 1 ];
 }
References _burn_data, and intensity.
burn_products()
const mat_burn_products & material_type::burn_products () const
Definition at line 361 of file material.cpp.
 {
     return _burn_products;
 }
References _burn_products.
check()
void material_type::check () const
Definition at line 154 of file material.cpp.
 {
     if( name().empty() ) {
         debugmsg( "material %s has no name.", id.c_str() );
     }
     if( _dmg_adj.size() < 4 ) {
         debugmsg( "material %s specifies insufficient damaged adjectives.", id.c_str() );
     }
     if( _salvaged_into && ( !item::type_is_defined( *_salvaged_into ) || _salvaged_into->is_null() ) ) {
         debugmsg( "invalid \"salvaged_into\" %s for %s.", _salvaged_into->c_str(), id.c_str() );
     }
     if( !item::type_is_defined( _repaired_with ) ) {
         debugmsg( "invalid \"repaired_with\" %s for %s.", _repaired_with.c_str(), id.c_str() );
     }
     if( _wind_resist && ( *_wind_resist > 100 || *_wind_resist < 0 ) ) {
         debugmsg( "Wind resistance outside of range (100%% to 0%%, is %d%%) for %s.", *_wind_resist,
                   id.str() );
     }
     if( _repair_difficulty && ( _repair_difficulty > 10 || _repair_difficulty < 0 ) ) {
         debugmsg( "Repair difficulty out of skill range (0 to 10, is %d) for %s.", _repair_difficulty,
                   id.str() );
     }
     for( const auto &dt : _resistances.resist_vals ) {
         if( !dt.first.is_valid() ) {
             debugmsg( "Invalid resistance type \"%s\" for material %s", dt.first.c_str(), id.c_str() );
         }
     }
     for( const damage_type &dt : damage_type::get_all() ) {
         bool type_defined =
             std::find( _res_was_loaded.begin(), _res_was_loaded.end(),  dt.id ) != _res_was_loaded.end();
         if( dt.material_required && !type_defined ) {
             debugmsg( "material %s is missing required resistance for \"%s\"", id.c_str(), dt.id.c_str() );
         }
     }
 }
References _dmg_adj, _repair_difficulty, _repaired_with, _res_was_loaded, _resistances, _salvaged_into, _wind_resist, string_id< T >::c_str(), debugmsg, damage_type::get_all(), name(), resistances::resist_vals, and item::type_is_defined().
chip_resist()
int material_type::chip_resist () const
Definition at line 244 of file material.cpp.
 {
     return _chip_resist;
 }
References _chip_resist.
cut_dmg_verb()
std::string material_type::cut_dmg_verb () const
Definition at line 230 of file material.cpp.
 {
     return _cut_dmg_verb.translated();
 }
References _cut_dmg_verb, and translation::translated().
Referenced by Character::describe_damage().
density()
float material_type::density () const
Definition at line 274 of file material.cpp.
 {
     return _density;
 }
References _density.
Referenced by replace_materials().
dmg_adj()
std::string material_type::dmg_adj (int damage_level) const
Definition at line 235 of file material.cpp.
 {
     if( damage_level <= 1 ) {
         return std::string(); // not damaged
     }
     const int idx = std::clamp( damage_level - 2, 0, static_cast<int>( _dmg_adj.size() ) );
     return _dmg_adj[idx].translated();
 }
References _dmg_adj, and clamp().
Referenced by Character::describe_damage().
edible()
bool material_type::edible () const
Definition at line 331 of file material.cpp.
 {
     return _edible;
 }
References _edible.
finalize_all()
void material_type::finalize_all () static
Definition at line 145 of file material.cpp.
 {
     material_data.finalize();
     for( const material_type &mtype : material_data.get_all() ) {
         material_type &mt = const_cast<material_type &>( mtype );
         finalize_damage_map( mt._resistances.resist_vals );
     }
 }
References _resistances, finalize_damage_map(), anonymous_namespace{material.cpp}::material_data, and resistances::resist_vals.
Referenced by DynamicDataLoader::finalize_loaded_data().
freeze_point()
float material_type::freeze_point () const
Definition at line 269 of file material.cpp.
 {
     return _freeze_point;
 }
References _freeze_point.
get_fuel_data()
fuel_data material_type::get_fuel_data () const
Definition at line 351 of file material.cpp.
 {
     return fuel;
 }
References fuel.
Referenced by vehicle::consumption_per_hour(), item::fuel_energy(), item::fuel_pump_terrain(), and item::get_explosion_data().
has_dedicated_resist()
bool material_type::has_dedicated_resist (const damage_type_id & dmg_type) const
Definition at line 219 of file material.cpp.
 {
     return std::find( _res_was_loaded.begin(), _res_was_loaded.end(),
                       dmg_type ) != _res_was_loaded.end();
 }
References _res_was_loaded.
ident()
material_id material_type::ident () const
Definition at line 194 of file material.cpp.
 {
     return id;
 }
References id.
is_conductive()
bool material_type::is_conductive () const
Definition at line 279 of file material.cpp.
 {
     return _conductive;
 }
References _conductive.
is_valid_thickness()
bool material_type::is_valid_thickness (float thickness) const
Definition at line 284 of file material.cpp.
 {
     // if this doesn't have an expected thickness return true
     if( _sheet_thickness == 0 ) {
         return true;
     }
     // float calcs so rounding need to be mindful of
     return std::fmod( thickness, _sheet_thickness ) < .01f;
 }
References _sheet_thickness, and units::fmod().
Referenced by Item_factory::check_definitions().
latent_heat()
float material_type::latent_heat () const
Definition at line 264 of file material.cpp.
 {
     return _latent_heat;
 }
References _latent_heat.
load()
void material_type::load (const JsonObject & jsobj, std::string_view src)
Definition at line 81 of file material.cpp.
 {
     mandatory( jsobj, was_loaded, "name", _name );
     if( jsobj.has_object( "resist" ) ) {
         _res_was_loaded.clear();
         JsonObject jo = jsobj.get_object( "resist" );
         _resistances = load_resistances_instance( jo );
         for( const JsonMember &jmemb : jo ) {
             _res_was_loaded.emplace_back( jmemb.name() );
         }
     }
     optional( jsobj, was_loaded, "conductive", _conductive );
     mandatory( jsobj, was_loaded, "chip_resist", _chip_resist );
     mandatory( jsobj, was_loaded, "density", _density );
     optional( jsobj, was_loaded, "sheet_thickness", _sheet_thickness );
     optional( jsobj, was_loaded, "repair_difficulty", _repair_difficulty );
     optional( jsobj, was_loaded, "wind_resist", _wind_resist );
     optional( jsobj, was_loaded, "specific_heat_liquid", _specific_heat_liquid );
     optional( jsobj, was_loaded, "specific_heat_solid", _specific_heat_solid );
     optional( jsobj, was_loaded, "latent_heat", _latent_heat );
     optional( jsobj, was_loaded, "freezing_point", _freeze_point );
     optional( jsobj, was_loaded, "breathability", _breathability, breathability_rating::IMPERMEABLE );
     assign( jsobj, "salvaged_into", _salvaged_into );
     optional( jsobj, was_loaded, "repaired_with", _repaired_with, itype_id::NULL_ID() );
     optional( jsobj, was_loaded, "edible", _edible, false );
     optional( jsobj, was_loaded, "rotting", _rotting, false );
     optional( jsobj, was_loaded, "soft", _soft, false );
     optional( jsobj, was_loaded, "uncomfortable", _uncomfortable, false );
     for( JsonArray pair : jsobj.get_array( "vitamins" ) ) {
         _vitamins.emplace( vitamin_id( pair.get_string( 0 ) ), pair.get_float( 1 ) );
     }
     mandatory( jsobj, was_loaded, "bash_dmg_verb", _bash_dmg_verb );
     mandatory( jsobj, was_loaded, "cut_dmg_verb", _cut_dmg_verb );
     mandatory( jsobj, was_loaded, "dmg_adj", _dmg_adj );
     if( jsobj.has_array( "burn_data" ) ) {
         for( JsonObject brn : jsobj.get_array( "burn_data" ) ) {
             _burn_data.emplace_back( load_mat_burn_data( brn ) );
         }
     }
     if( _burn_data.empty() ) {
         // If not specified, supply default
         mat_burn_data mbd;
         if( _resistances.type_resist( STATIC( damage_type_id( "heat" ) ) ) <= 0.f ) {
             mbd.burn = 1;
         }
         _burn_data.emplace_back( mbd );
     }
     optional( jsobj, was_loaded, "fuel_data", fuel );
     jsobj.read( "burn_products", _burn_products, true );
 }
References _bash_dmg_verb, _breathability, _burn_data, _burn_products, _chip_resist, _conductive, _cut_dmg_verb, _density, _dmg_adj, _edible, _freeze_point, _latent_heat, _name, _repair_difficulty, _repaired_with, _res_was_loaded, _resistances, _rotting, _salvaged_into, _sheet_thickness, _soft, _specific_heat_liquid, _specific_heat_solid, _uncomfortable, _vitamins, _wind_resist, assign(), mat_burn_data::burn, fuel, JsonObject::get_array(), JsonObject::get_object(), JsonObject::has_array(), JsonObject::has_object(), IMPERMEABLE, load_mat_burn_data(), load_resistances_instance(), mandatory, string_id< itype >::NULL_ID(), optional(), JsonObject::read(), STATIC, resistances::type_resist(), and was_loaded.
name()
std::string material_type::name () const
Definition at line 199 of file material.cpp.
 {
     return _name.translated();
 }
References _name, and translation::translated().
Referenced by item::basic_info(), check(), item_pocket::general_info(), and repair_item_actor::handle_components().
repair_difficulty()
int material_type::repair_difficulty () const
Definition at line 249 of file material.cpp.
 {
     return _repair_difficulty;
 }
References _repair_difficulty.
repaired_with()
itype_id material_type::repaired_with () const
Definition at line 209 of file material.cpp.
 {
     return _repaired_with;
 }
References _repaired_with.
Referenced by repair_item_actor::handle_components().
resist()
float material_type::resist (const damage_type_id & dmg_type) const
Definition at line 214 of file material.cpp.
 {
     return _resistances.type_resist( dmg_type );
 }
References _resistances, and resistances::type_resist().
rotting()
bool material_type::rotting () const
Definition at line 336 of file material.cpp.
 {
     return _rotting;
 }
References _rotting.
salvaged_into()
std::optional< itype_id > material_type::salvaged_into () const
Returns
An empty optional if this material can not be salvaged into any items (e.g. for powder, liquids). Or a valid id of the item type that this can be salvaged into (e.g. clothes made of material leather can be salvaged into leather patches).
Definition at line 204 of file material.cpp.
 {
     return _salvaged_into;
 }
References _salvaged_into.
soft()
bool material_type::soft () const
Definition at line 341 of file material.cpp.
 {
     return _soft;
 }
References _soft.
Referenced by Item_factory::finalize_post_armor().
specific_heat_liquid()
float material_type::specific_heat_liquid () const
Definition at line 254 of file material.cpp.
 {
     return _specific_heat_liquid;
 }
References _specific_heat_liquid.
specific_heat_solid()
float material_type::specific_heat_solid () const
Definition at line 259 of file material.cpp.
 {
     return _specific_heat_solid;
 }
References _specific_heat_solid.
thickness_multiple()
float material_type::thickness_multiple () const
Definition at line 295 of file material.cpp.
 {
     return _sheet_thickness;
 }
References _sheet_thickness.
Referenced by Item_factory::check_definitions().
uncomfortable()
bool material_type::uncomfortable () const
Definition at line 346 of file material.cpp.
 {
     return _uncomfortable;
 }
References _uncomfortable.
Referenced by Item_factory::finalize_post_armor().
vitamin()
double material_type::vitamin (const vitamin_id & id) const inline
Definition at line 164 of file material.h.
{
             const auto iter = _vitamins.find( id );
             return iter != _vitamins.end() ? iter->second : 0;
         }
References _vitamins.
wind_resist()
std::optional< int > material_type::wind_resist () const
Definition at line 326 of file material.cpp.
 {
     return _wind_resist;
 }
References _wind_resist.
Member Data Documentation
_bash_dmg_verb
translation material_type::_bash_dmg_verb private
Definition at line 105 of file material.h.
Referenced by bash_dmg_verb(), and load().
_breathability
breathability_rating material_type::_breathability = breathability_rating::IMPERMEABLE private
Definition at line 86 of file material.h.
Referenced by breathability(), and load().
_burn_data
std::vector<mat_burn_data> material_type::_burn_data private
Definition at line 111 of file material.h.
Referenced by burn_data(), and load().
_burn_products
mat_burn_products material_type::_burn_products private
Definition at line 116 of file material.h.
Referenced by burn_products(), and load().
_chip_resist
int material_type::_chip_resist = 0 private
Definition at line 83 of file material.h.
Referenced by chip_resist(), and load().
_conductive
bool material_type::_conductive = false private
Definition at line 97 of file material.h.
Referenced by is_conductive(), and load().
_cut_dmg_verb
translation material_type::_cut_dmg_verb private
Definition at line 106 of file material.h.
Referenced by cut_dmg_verb(), and load().
_density
float material_type::_density = 1 private
Definition at line 84 of file material.h.
Referenced by density(), and load().
_dmg_adj
std::vector<translation> material_type::_dmg_adj private
Definition at line 107 of file material.h.
Referenced by check(), dmg_adj(), load(), and material_type().
_edible
bool material_type::_edible = false private
Definition at line 93 of file material.h.
Referenced by edible(), and load().
_freeze_point
float material_type::_freeze_point = 0 private
Definition at line 92 of file material.h.
Referenced by freeze_point(), and load().
_latent_heat
float material_type::_latent_heat = 334.0f private
Definition at line 91 of file material.h.
Referenced by latent_heat(), and load().
_name
translation material_type::_name private
Definition at line 78 of file material.h.
Referenced by load(), and name().
_repair_difficulty
int material_type::_repair_difficulty = 10 private
Definition at line 103 of file material.h.
Referenced by check(), load(), and repair_difficulty().
_repaired_with
itype_id material_type::_repaired_with = itype_id("null") private
Definition at line 80 of file material.h.
Referenced by check(), load(), and repaired_with().
_res_was_loaded
std::vector<damage_type_id> material_type::_res_was_loaded private
Definition at line 82 of file material.h.
Referenced by check(), has_dedicated_resist(), and load().
_resistances
resistances material_type::_resistances private
Definition at line 81 of file material.h.
Referenced by check(), finalize_all(), load(), and resist().
_rotting
bool material_type::_rotting = false private
Definition at line 94 of file material.h.
Referenced by load(), and rotting().
_salvaged_into
std::optional<itype_id> material_type::_salvaged_into private
Definition at line 79 of file material.h.
Referenced by check(), load(), and salvaged_into().
_sheet_thickness
float material_type::_sheet_thickness = 0.0f private
Definition at line 100 of file material.h.
Referenced by is_valid_thickness(), load(), and thickness_multiple().
_soft
bool material_type::_soft = false private
Definition at line 95 of file material.h.
Referenced by load(), and soft().
_specific_heat_liquid
float material_type::_specific_heat_liquid = 4.186f private
Definition at line 89 of file material.h.
Referenced by load(), and specific_heat_liquid().
_specific_heat_solid
float material_type::_specific_heat_solid = 2.108f private
Definition at line 90 of file material.h.
Referenced by load(), and specific_heat_solid().
_uncomfortable
bool material_type::_uncomfortable = false private
Definition at line 96 of file material.h.
Referenced by load(), and uncomfortable().
_vitamins
std::map<vitamin_id, double> material_type::_vitamins private
Definition at line 109 of file material.h.
Referenced by load(), and vitamin().
_wind_resist
std::optional<int> material_type::_wind_resist private
Definition at line 88 of file material.h.
Referenced by check(), load(), and wind_resist().
fuel
fuel_data material_type::fuel private
Definition at line 113 of file material.h.
Referenced by get_fuel_data(), and load().
id
material_id material_type::id
Definition at line 73 of file material.h.
Referenced by ident(), and item_pocket::is_compatible().
src
std::vector<std::pair<material_id, mod_id> > material_type::src
Definition at line 74 of file material.h.
was_loaded
bool material_type::was_loaded = false
Definition at line 75 of file material.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/material.h
src/material.cpp