Cataclysm DDA: dependency_tree Class Reference
dependency_tree Class Reference
#include <dependency_tree.h>
Public Member Functions
dependency_tree ()
void init (const std::map< mod_id, std::vector< mod_id > > &key_dependency_map)
void clear ()
std::vector< mod_id > get_dependencies_of_X_as_strings (const mod_id &key)
std::vector< dependency_node * > get_dependencies_of_X_as_nodes (const mod_id &key)
std::vector< mod_id > get_dependents_of_X_as_strings (const mod_id &key)
std::vector< dependency_node * > get_dependents_of_X_as_nodes (const mod_id &key)
bool is_available (const mod_id &key)
dependency_node * get_node (const mod_id &key)
Public Attributes
std::map< mod_id, dependency_node > master_node_map
Private Member Functions
void build_node_map (const std::map< mod_id, std::vector< mod_id > > &key_dependency_map)
void build_connections (const std::map< mod_id, std::vector< mod_id > > &key_dependency_map)
void check_for_strongly_connected_components ()
void strong_connect (dependency_node *dnode)
Private Attributes
std::vector< std::vector< dependency_node * > > strongly_connected_components
std::stack< dependency_node * > connection_stack
std::vector< dependency_node * > nodes_on_stack
int open_index
Detailed Description
Definition at line 53 of file dependency_tree.h.
Constructor & Destructor Documentation
dependency_tree()
dependency_tree::dependency_tree () default
Member Function Documentation
build_connections()
void dependency_tree::build_connections (const std::map< mod_id, std::vector< mod_id > > & key_dependency_map) private
Definition at line 273 of file dependency_tree.cpp.
 {
     for( const auto &elem : key_dependency_map ) {
         const auto iter = master_node_map.find( elem.first );
         if( iter != master_node_map.end() ) {
             dependency_node *knode = &iter->second;
             // apply parents list
             std::vector<mod_id> vnode_parents = elem.second;
             for( auto &vnode_parent : vnode_parents ) {
                 const auto iter = master_node_map.find( vnode_parent );
                 if( iter != master_node_map.end() ) {
                     dependency_node *vnode = &iter->second;
                     knode->add_parent( vnode );
                     vnode->add_child( knode );
                 } else {
                     // missing dependency!
                     knode->all_errors[DEPENDENCY].push_back( "<" + vnode_parent.str() + ">" );
                 }
             }
         }
     }
     // finalize and check for circular dependencies
     check_for_strongly_connected_components();
     for( auto &elem : master_node_map ) {
         elem.second.inherit_errors();
     }
 }
References dependency_node::add_child(), dependency_node::add_parent(), dependency_node::all_errors, check_for_strongly_connected_components(), DEPENDENCY, and master_node_map.
Referenced by init().
build_node_map()
void dependency_tree::build_node_map (const std::map< mod_id, std::vector< mod_id > > & key_dependency_map) private
Definition at line 262 of file dependency_tree.cpp.
 {
     for( const auto &elem : key_dependency_map ) {
         // check to see if the master node map knows the key
         if( master_node_map.find( elem.first ) == master_node_map.end() ) {
             master_node_map.emplace( elem.first, dependency_node( elem.first ) );
         }
     }
 }
References master_node_map.
Referenced by init().
check_for_strongly_connected_components()
void dependency_tree::check_for_strongly_connected_components () private
Definition at line 365 of file dependency_tree.cpp.
 {
     strongly_connected_components = std::vector<std::vector<dependency_node * > >();
     open_index = 0;
     connection_stack = std::stack<dependency_node *>();
     for( auto &elem : master_node_map ) {
         //nodes_on_stack = std::vector<dependency_node*>();
         // clear it for the next stack to run
         if( elem.second.index < 0 ) {
             strong_connect( &elem.second );
         }
     }
     // now go through and make a set of these
     std::set<dependency_node *> in_circular_connection;
     for( auto &elem : strongly_connected_components ) {
         if( elem.size() > 1 ) {
             for( dependency_node *&elem_node : elem ) {
                 DebugLog( D_PEDANTIC_INFO, DC_ALL ) << "--" << elem_node->key.str() << "\n";
                 in_circular_connection.insert( elem_node );
             }
         }
     }
     // now go back through this and give them all the circular error code!
     for( dependency_node * const &elem : in_circular_connection ) {
         elem->all_errors[CYCLIC].emplace_back( "In Circular Dependency Cycle" );
     }
 }
References connection_stack, CYCLIC, D_PEDANTIC_INFO, DC_ALL, DebugLog(), master_node_map, open_index, strong_connect(), and strongly_connected_components.
Referenced by build_connections().
clear()
void dependency_tree::clear ()
Definition at line 350 of file dependency_tree.cpp.
 {
     master_node_map.clear();
 }
References master_node_map.
get_dependencies_of_X_as_nodes()
std::vector< dependency_node * > dependency_tree::get_dependencies_of_X_as_nodes (const mod_id & key)
Definition at line 313 of file dependency_tree.cpp.
 {
     const auto iter = master_node_map.find( key );
     if( iter != master_node_map.end() ) {
         return iter->second.get_dependencies_as_nodes();
     }
     return std::vector<dependency_node *>();
 }
References master_node_map.
get_dependencies_of_X_as_strings()
std::vector< mod_id > dependency_tree::get_dependencies_of_X_as_strings (const mod_id & key)
Definition at line 305 of file dependency_tree.cpp.
 {
     const auto iter = master_node_map.find( key );
     if( iter != master_node_map.end() ) {
         return iter->second.get_dependencies_as_strings();
     }
     return std::vector<mod_id>();
 }
References master_node_map.
Referenced by mod_ui::can_shift_up(), game::check_mod_data(), and mod_ui::try_add().
get_dependents_of_X_as_nodes()
std::vector< dependency_node * > dependency_tree::get_dependents_of_X_as_nodes (const mod_id & key)
Definition at line 331 of file dependency_tree.cpp.
 {
     const auto iter = master_node_map.find( key );
     if( iter != master_node_map.end() ) {
         return iter->second.get_dependents_as_nodes();
     }
     return std::vector<dependency_node *>();
 }
References master_node_map.
get_dependents_of_X_as_strings()
std::vector< mod_id > dependency_tree::get_dependents_of_X_as_strings (const mod_id & key)
Definition at line 322 of file dependency_tree.cpp.
 {
     const auto iter = master_node_map.find( key );
     if( iter != master_node_map.end() ) {
         return iter->second.get_dependents_as_strings();
     }
     return std::vector<mod_id>();
 }
References master_node_map.
Referenced by mod_ui::can_shift_down(), and mod_ui::try_rem().
get_node()
dependency_node * dependency_tree::get_node (const mod_id & key)
Definition at line 355 of file dependency_tree.cpp.
 {
     const auto iter = master_node_map.find( key );
     if( iter != master_node_map.end() ) {
         return &iter->second;
     }
     return nullptr;
 }
References master_node_map.
Referenced by game::check_mod_data(), and mod_ui::try_add().
init()
void dependency_tree::init (const std::map< mod_id, std::vector< mod_id > > & key_dependency_map)
Definition at line 256 of file dependency_tree.cpp.
 {
     build_node_map( key_dependency_map );
     build_connections( key_dependency_map );
 }
References build_connections(), and build_node_map().
is_available()
bool dependency_tree::is_available (const mod_id & key)
Definition at line 340 of file dependency_tree.cpp.
 {
     const auto iter = master_node_map.find( key );
     if( iter != master_node_map.end() ) {
         return iter->second.is_available();
     }
     return false;
 }
References master_node_map.
Referenced by game::check_mod_data().
strong_connect()
void dependency_tree::strong_connect (dependency_node * dnode) private
Definition at line 396 of file dependency_tree.cpp.
 {
     dnode->index = open_index;
     dnode->lowlink = open_index;
     ++open_index;
     connection_stack.push( dnode );
     dnode->on_stack = true;
     for( std::vector<dependency_node *>::iterator it = dnode->parents.begin();
          it != dnode->parents.end(); ++it ) {
         if( ( *it )->index < 0 ) {
             strong_connect( *it );
             dnode->lowlink = std::min( dnode->lowlink, ( *it )->lowlink );
         } else if( ( *it )->on_stack ) {
             dnode->lowlink = std::min( dnode->lowlink, ( *it )->index );
         }
     }
     if( dnode->lowlink == dnode->index ) {
         std::vector<dependency_node *> scc;
         dependency_node *d;
         do {
             d = connection_stack.top();
             scc.push_back( d );
             connection_stack.pop();
             d->on_stack = false;
         } while( dnode->key != d->key );
         strongly_connected_components.push_back( scc );
         dnode->on_stack = false;
     }
 }
References connection_stack, dependency_node::index, dependency_node::key, dependency_node::lowlink, min(), dependency_node::on_stack, open_index, dependency_node::parents, and strongly_connected_components.
Referenced by check_for_strongly_connected_components().
Member Data Documentation
connection_stack
std::stack<dependency_node *> dependency_tree::connection_stack private
Definition at line 90 of file dependency_tree.h.
Referenced by check_for_strongly_connected_components(), and strong_connect().
master_node_map
std::map<mod_id, dependency_node> dependency_tree::master_node_map
Definition at line 73 of file dependency_tree.h.
Referenced by build_connections(), build_node_map(), check_for_strongly_connected_components(), clear(), get_dependencies_of_X_as_nodes(), get_dependencies_of_X_as_strings(), get_dependents_of_X_as_nodes(), get_dependents_of_X_as_strings(), get_node(), and is_available().
nodes_on_stack
std::vector<dependency_node *> dependency_tree::nodes_on_stack private
Definition at line 91 of file dependency_tree.h.
open_index
int dependency_tree::open_index private
Definition at line 92 of file dependency_tree.h.
Referenced by check_for_strongly_connected_components(), and strong_connect().
strongly_connected_components
std::vector<std::vector<dependency_node * > > dependency_tree::strongly_connected_components private
Definition at line 89 of file dependency_tree.h.
Referenced by check_for_strongly_connected_components(), and strong_connect().
The documentation for this class was generated from the following files:
src/dependency_tree.h
src/dependency_tree.cpp