Cataclysm DDA: player_activity Class Reference
player_activity Class Reference
#include <player_activity.h>
Public Member Functions
player_activity ()
player_activity (activity_id, int turns=0, int Index=-1, int pos=INT_MIN, const std::string &name_in="")
player_activity (const activity_actor &actor)
Create a new activity with the given actor.
player_activity (player_activity &&) noexcept=default
player_activity (const player_activity &)=default
player_activity & operator= (player_activity &&) noexcept(list_is_noexcept)=default
player_activity & operator= (const player_activity &)=default
operator bool () const
bool is_null () const
bool is_multi_type () const
void set_to_null ()
This replaces the former usage act.type = ACT_NULL
void synchronize_type_with_actor ()
const activity_id & id () const
bool rooted () const
std::string get_stop_phrase () const
const translation & get_verb () const
int get_value (size_t index, int def=0) const
std::string get_str_value (size_t index, std::string_view def={}) const
std::optional< std::string > get_progress_message (const avatar &u) const
Helper that returns an activity specific progress message.
bool can_resume () const
If this returns true, the action can be continued without starting from scratch again (see player::backlog).
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
void deserialize_legacy_type (int legacy_type, activity_id &dest)
Convert from the old enumeration to the new string_id.
void start_or_resume (Character &who, bool resuming)
Preform necessary initialization to start or resume the activity.
void do_turn (Character &you)
Performs the activity for a single turn.
void canceled (Character &who)
Performs activity-specific cleanup when Character::cancel_activity() is called.
bool can_resume_with (const player_activity &other, const Character &who) const
Returns true if activities are similar enough that this activity can be resumed instead of starting the other activity.
bool is_interruptible () const
bool is_interruptible_with_kb () const
bool is_distraction_ignored (distraction_type) const
void ignore_distraction (distraction_type)
void allow_distractions ()
void inherit_distractions (const player_activity &)
float exertion_level () const
bool do_drop_invalid_inventory () const
std::map< distraction_type, std::string > get_distractions () const
Public Attributes
int moves_total = 0
Total number of moves required to complete the activity.
int moves_left = calendar::INDEFINITELY_LONG
The number of moves remaining in this activity before it is complete.
bool interruptable = true
Controls whether this activity can be cancelled at all.
bool interruptable_with_kb = true
Controls whether this activity can be cancelled with 'pause' action.
int index = 0
int position = 0
An activity specific value.
std::string name
std::vector< item_location > targets
std::vector< int > values
std::vector< std::string > str_values
std::vector< tripoint > coords
std::unordered_set< tripoint > coord_set
std::vector< weak_ptr_fast< monster > > monsters
tripoint_abs_ms placement
tripoint_rel_ms relative_placement
bool no_drink_nearby_for_auto_consume = false
bool no_food_nearby_for_auto_consume = false
bool auto_resume = false
If true, the activity will be auto-resumed next time the player attempts an identical activity.
bool have_fire = true
Flag that will suppress the relatively expensive fire refueling search process.
Static Public Attributes
static constexpr tripoint_abs_ms invalid_place { tripoint_min }
Private Attributes
activity_id type
cata::clone_ptr< activity_actor > actor
std::set< distraction_type > ignored_distractions
bool ignoreQuery = false
Detailed Description
Definition at line 32 of file player_activity.h.
Constructor & Destructor Documentation
player_activity() [1/5]
player_activity::player_activity ()
Definition at line 65 of file player_activity.cpp.
 : type( activity_id::NULL_ID() ) { }
Referenced by do_turn().
player_activity() [2/5]
player_activity::player_activity (activity_id t, int turns = 0, int Index = -1, int pos = INT_MIN, const std::string & name_in = "") explicit
Definition at line 67 of file player_activity.cpp.
                                                              :
     type( t ), moves_total( turns ), moves_left( turns ),
     index( Index ),
     position( pos ), name( name_in ),
     placement( tripoint_min )
 {
     if( type != ACT_NULL ) {
         for( const distraction_type dt : type->default_ignored_distractions() ) {
             ignored_distractions.emplace( dt );
         }
     }
 }
References ACT_NULL, activity_type::default_ignored_distractions(), ignored_distractions, and type.
player_activity() [3/5]
player_activity::player_activity (const activity_actor & actor) explicit
Create a new activity with the given actor.
Definition at line 81 of file player_activity.cpp.
                                                               : type( actor.get_type() ),
     actor( actor.clone() )
 {
     if( type != ACT_NULL ) {
         for( const distraction_type dt : type->default_ignored_distractions() ) {
             ignored_distractions.emplace( dt );
         }
     }
 }
References ACT_NULL, activity_type::default_ignored_distractions(), ignored_distractions, and type.
player_activity() [4/5]
player_activity::player_activity (player_activity &&) default noexcept
player_activity() [5/5]
player_activity::player_activity (const player_activity &) default
Member Function Documentation
allow_distractions()
void player_activity::allow_distractions ()
Definition at line 488 of file player_activity.cpp.
 {
     ignored_distractions.clear();
 }
References ignored_distractions.
Referenced by Character::cancel_activity(), and Character::resume_backlog_activity().
can_resume()
bool player_activity::can_resume () const
If this returns true, the action can be continued without starting from scratch again (see player::backlog).
This is only possible if the player start the very same activity (with the same parameters) again.
Definition at line 124 of file player_activity.cpp.
 {
     return type->can_resume();
 }
References activity_type::can_resume(), and type.
Referenced by Character::cancel_activity().
can_resume_with()
bool player_activity::can_resume_with (const player_activity & other, const Character & who) const
Returns true if activities are similar enough that this activity can be resumed instead of starting the other activity.
Definition at line 435 of file player_activity.cpp.
 {
     // Should be used for relative positions
     // And to forbid resuming now-invalid crafting
     if( !*this || !other || !type->can_resume() ) {
         return false;
     }
     if( id() != other.id() ) {
         return false;
     }
     // if actor XOR other.actor then id() != other.id() so
     // we will correctly return false based on final return statement
     if( actor && other.actor ) {
         return actor->can_resume_with( *other.actor, who );
     }
     if( id() == ACT_CLEAR_RUBBLE ) {
         if( other.coords.empty() || other.coords[0] != coords[0] ) {
             return false;
         }
     } else if( id() == ACT_VEHICLE ) {
         if( values != other.values || str_values != other.str_values ) {
             return false;
         }
     }
     return !auto_resume && index == other.index &&
            position == other.position && name == other.name && targets == other.targets;
 }
References ACT_CLEAR_RUBBLE, ACT_VEHICLE, actor, auto_resume, activity_type::can_resume(), activity_actor::can_resume_with(), index, name, other, position, str_values, targets, type, and values.
canceled()
void player_activity::canceled (Character & who)
Performs activity-specific cleanup when Character::cancel_activity() is called.
Definition at line 409 of file player_activity.cpp.
 {
     if( *this && actor ) {
         actor->canceled( *this, who );
     }
     get_event_bus().send<event_type::character_finished_activity>( who.getID(), type, true );
 }
References actor, activity_actor::canceled(), character_finished_activity, get_event_bus(), Character::getID(), event_bus::send(), and type.
Referenced by Character::cancel_activity(), and do_turn().
deserialize()
void player_activity::deserialize (const JsonObject & data)
Definition at line 366 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     std::string tmptype;
     int tmppos = 0;
     bool is_obsolete = false;
     std::set<std::string> obs_activities {
         "ACT_MAKE_ZLAVE" // Remove after 0.F
     };
     if( !data.read( "type", tmptype ) ) {
         // Then it's a legacy save.
         int tmp_type_legacy = data.get_int( "type" );
         deserialize_legacy_type( tmp_type_legacy, type );
     } else if( !obs_activities.count( tmptype ) ) {
         type = activity_id( tmptype );
     } else {
         is_obsolete = true;
     }
     if( type.is_null() ) {
         return;
     }
     const bool has_actor = activity_actors::deserialize_functions.find( type ) !=
                            activity_actors::deserialize_functions.end();
     // Handle migration of pre-activity_actor activities
     // ACT_MIGRATION_CANCEL will clear the backlog and reset npc state
     // this may cause inconvenience but should avoid any lasting damage to npcs
     if( is_obsolete || ( has_actor && ( data.has_null( "actor" ) || !data.has_member( "actor" ) ) ) ) {
         type = ACT_MIGRATION_CANCEL;
         actor = std::make_unique<migration_cancel_activity_actor>();
     } else {
         data.read( "actor", actor );
     }
     if( !data.read( "position", tmppos ) ) {
         tmppos = INT_MIN;  // If loading a save before position existed, hope.
     }
     data.read( "moves_total", moves_total );
     data.read( "moves_left", moves_left );
     data.read( "interruptable", interruptable );
     data.read( "interruptable_with_kb", interruptable_with_kb );
     data.read( "index", index );
     position = tmppos;
     data.read( "coords", coords );
     data.read( "coord_set", coord_set );
     data.read( "name", name );
     data.read( "targets", targets );
     data.read( "placement", placement );
     data.read( "relative_placement", relative_placement );
     values = data.get_int_array( "values" );
     str_values = data.get_string_array( "str_values" );
     data.read( "auto_resume", auto_resume );
     data.read( "monsters", monsters );
 }
References ACT_MIGRATION_CANCEL, activity_id, item_pocket::data, activity_actors::deserialize_functions, om_direction::name(), and type.
deserialize_legacy_type()
void player_activity::deserialize_legacy_type (int legacy_type, activity_id & dest)
Convert from the old enumeration to the new string_id.
Definition at line 206 of file savegame_legacy.cpp.
 {
     static const std::vector< activity_id > legacy_map = {
         activity_id::NULL_ID(),
         ACT_RELOAD,
         activity_id::NULL_ID(), // ACT_READ is an actor now
         ACT_GAME,
         ACT_WAIT,
         activity_id::NULL_ID(), // ACT_CRAFT is an actor now
         activity_id::NULL_ID(), // ACT_LONGCRAFT is deprecated
         ACT_DISASSEMBLE,
         ACT_BUTCHER,
         activity_id::NULL_ID(), // ACT_LONGSALVAGE is an actor now
         activity_id::NULL_ID(), // ACT_FORAGE is an actor now
         ACT_BUILD,
         ACT_VEHICLE,
         activity_id::NULL_ID(), // ACT_REFILL_VEHICLE is deprecated
         ACT_TRAIN,
         ACT_WAIT_WEATHER,
         activity_id::NULL_ID(), // ACT_FIRSTAID is an actor now
         ACT_FISH,
         ACT_PICKAXE,
         ACT_BURROW,
         ACT_PULP,
         ACT_VIBE,
         activity_id::NULL_ID(), // ACT_MAKE_ZLAVE is deprecated
         activity_id::NULL_ID(), // ACT_DROP is an actor now
         activity_id::NULL_ID(), // ACT_STASH is an actor now
         ACT_PICKUP,
         ACT_MOVE_ITEMS,
         ACT_ADV_INVENTORY,
         ACT_ARMOR_LAYERS,
         ACT_START_FIRE,
         ACT_OPEN_GATE,
         ACT_FILL_LIQUID,
         ACT_HOTWIRE_CAR,
         ACT_AIM,
         ACT_ATM,
         ACT_START_ENGINES,
         activity_id::NULL_ID(), // ACT_OXYTORCH is an actor now
         ACT_CRACKING,
         ACT_REPAIR_ITEM,
         ACT_MEND_ITEM,
         activity_id::NULL_ID(), // ACT_GUNMOD_ADD
         ACT_WAIT_NPC,
         activity_id::NULL_ID(), // ACT_CLEAR_RUBBLE
         ACT_MEDITATE,
         activity_id::NULL_ID() // NUM_ACTIVITIES
     };
     if( legacy_type < 0 || static_cast<size_t>( legacy_type ) >= legacy_map.size() ) {
         debugmsg( "Bad legacy activity data.  Got %d, expected something from 0 to %d", legacy_type,
                   legacy_map.size() );
         dest = activity_id::NULL_ID();
         return;
     }
     dest = legacy_map[ legacy_type ];
 }
References ACT_ADV_INVENTORY, ACT_AIM, ACT_ARMOR_LAYERS, ACT_ATM, ACT_BUILD, ACT_BURROW, ACT_BUTCHER, ACT_CRACKING, ACT_DISASSEMBLE, ACT_FILL_LIQUID, ACT_FISH, ACT_GAME, ACT_HOTWIRE_CAR, ACT_MEDITATE, ACT_MEND_ITEM, ACT_MOVE_ITEMS, ACT_OPEN_GATE, ACT_PICKAXE, ACT_PICKUP, ACT_PULP, ACT_RELOAD, ACT_REPAIR_ITEM, ACT_START_ENGINES, ACT_START_FIRE, ACT_TRAIN, ACT_VEHICLE, ACT_VIBE, ACT_WAIT, ACT_WAIT_NPC, ACT_WAIT_WEATHER, debugmsg, and string_id< activity_type >::NULL_ID().
do_drop_invalid_inventory()
bool player_activity::do_drop_invalid_inventory () const inline
Definition at line 180 of file player_activity.h.
{
             return !actor || actor->do_drop_invalid_inventory();
         }
References actor, and activity_actor::do_drop_invalid_inventory().
Referenced by Character::process_turn().
do_turn()
void player_activity::do_turn (Character & you)
Performs the activity for a single turn.
If the activity is complete at the end of the turn, do_turn also executes whatever actions, if any, are needed to conclude the activity.
Definition at line 230 of file player_activity.cpp.
 {
     // Specifically call the do turn function for the cancellation activity early
     // This is because the game can get stuck trying to fuel a fire when it's not...
     if( type == ACT_MIGRATION_CANCEL ) {
         actor->do_turn( *this, you );
         return;
     }
     // first to ensure sync with actor
     synchronize_type_with_actor();
     // Should happen before activity or it may fail due to 0 moves
     if( *this && type->will_refuel_fires() && have_fire ) {
         have_fire = try_fuel_fire( *this, you );
     }
     if( calendar::once_every( 30_minutes ) ) {
         no_food_nearby_for_auto_consume = false;
         no_drink_nearby_for_auto_consume = false;
     }
     // Only do once every two minutes to loosely simulate consume times,
     // the exact amount of time is added correctly below, here we just want to prevent eating something every second
     if( calendar::once_every( 2_minutes ) && *this && !you.is_npc() ) {
         if( type->valid_auto_needs() && !you.has_effect( effect_nausea ) ) {
             if( you.stomach.contains() <= you.stomach.capacity( you ) / 4 && you.get_kcal_percent() < 0.95f &&
                 !no_food_nearby_for_auto_consume ) {
                 int consume_moves = get_auto_consume_moves( you, true );
                 moves_left += consume_moves;
                 moves_total += consume_moves;
                 if( consume_moves == 0 ) {
                     no_food_nearby_for_auto_consume = true;
                 }
             }
             if( you.get_thirst() > 130 && !no_drink_nearby_for_auto_consume ) {
                 int consume_moves = get_auto_consume_moves( you, false );
                 moves_left += consume_moves;
                 moves_total += consume_moves;
                 if( consume_moves == 0 ) {
                     no_drink_nearby_for_auto_consume = true;
                 }
             }
         }
     }
     const float activity_mult = you.exertion_adjusted_move_multiplier( exertion_level() );
     if( type->based_on() == based_on_type::TIME ) {
         if( moves_left >= 100 ) {
             moves_left -= 100 * activity_mult;
             you.set_moves( 0 );
         } else {
             you.mod_moves( -you.get_moves() * moves_left / 100 );
             moves_left = 0;
         }
     } else if( type->based_on() == based_on_type::SPEED ) {
         if( you.get_moves() <= moves_left ) {
             moves_left -= you.get_moves() * activity_mult;
             you.set_moves( 0 );
         } else {
             you.mod_moves( -moves_left );
             moves_left = 0;
         }
     }
     int previous_stamina = you.get_stamina();
     if( you.is_npc() && you.check_outbounds_activity( *this ) ) {
         // npc might be operating at the edge of the reality bubble.
         // or just now reloaded back into it, and their activity target might
         // be still unloaded, can cause infinite loops.
         set_to_null();
         you.drop_invalid_inventory();
         return;
     }
     const bool travel_activity = id() == ACT_TRAVELLING;
     you.set_activity_level( exertion_level() );
     if( !type->do_turn_EOC.is_null() ) {
         // if we have an EOC defined in json do that
         dialogue d( get_talker_for( you ), nullptr );
         if( type->do_turn_EOC->type == eoc_type::ACTIVATION ) {
             type->do_turn_EOC->activate( d );
         } else {
             debugmsg( "Must use an activation eoc for player activities.  Otherwise, create a non-recurring effect_on_condition for this with its condition and effects, then have a recurring one queue it." );
         }
         // We may have canceled this via a message interrupt.
         if( type.is_null() ) {
             return;
         }
     }
     // This might finish the activity (set it to null)
     if( actor ) {
         actor->do_turn( *this, you );
     } else {
         // Use the legacy turn function
         type->call_do_turn( this, &you );
     }
     // Activities should never excessively drain stamina.
     // adjusted stamina because
     // autotravel doesn't reduce stamina after do_turn()
     // it just sets a destination, clears the activity, then moves afterwards
     // so set stamina -1 if that is the case
     // to simulate that the next step will surely use up some stamina anyway
     // this is to ensure that resting will occur when traveling overburdened
     const int adjusted_stamina = travel_activity ? you.get_stamina() - 1 : you.get_stamina();
     activity_id act_id = actor ? actor->get_type() : type;
     bool excluded = act_id == ACT_WORKOUT_HARD ||
                     act_id == ACT_WORKOUT_ACTIVE ||
                     act_id == ACT_WORKOUT_MODERATE ||
                     act_id == ACT_WORKOUT_LIGHT;
     if( !excluded && adjusted_stamina < previous_stamina &&
         you.get_stamina() < you.get_stamina_max() / 3 ) {
         if( one_in( 50 ) ) {
             you.add_msg_if_player( _( "You pause for a moment to catch your breath." ) );
         }
         auto_resume = true;
         player_activity new_act( ACT_WAIT_STAMINA, to_moves<int>( 5_minutes ) );
         new_act.values.push_back( you.get_stamina_max() );
         if( you.is_avatar() && !ignoreQuery ) {
             uilist tired_query;
             tired_query.text = _( "You struggle to continue.  Keep trying?" );
             tired_query.addentry( 1, true, 'c', _( "Continue after a break." ) );
             tired_query.addentry( 2, true, 'm', _( "Maybe later." ) );
             tired_query.addentry( 3, true, 'f', _( "Finish it." ) );
             tired_query.query();
             switch( tired_query.ret ) {
                 case UILIST_CANCEL:
                 case 2:
                     auto_resume = false;
                     you.cancel_activity();
                     break;
                 case 3:
                     ignoreQuery = true;
                     break;
                 default:
                     canceled( you );
                     break;
             }
         }
         if( !ignoreQuery && auto_resume ) {
             you.assign_activity( new_act );
         }
         return;
     }
     if( *this && type->rooted() ) {
         you.rooted();
         you.pause();
     }
     if( *this && moves_left <= 0 ) {
         // Note: For some activities "finish" is a misnomer; that's why we explicitly check if the
         // type is ACT_NULL below.
         if( !type->completion_EOC.is_null() ) {
             // if we have an EOC defined in json do that
             dialogue d( get_talker_for( you ), nullptr );
             if( type->completion_EOC->type == eoc_type::ACTIVATION ) {
                 type->completion_EOC->activate( d );
             } else {
                 debugmsg( "Must use an activation eoc for player activities.  Otherwise, create a non-recurring effect_on_condition for this with its condition and effects, then have a recurring one queue it." );
             }
         }
         get_event_bus().send<event_type::character_finished_activity>( you.getID(), type, false );
         if( actor ) {
             actor->finish( *this, you );
         } else {
             if( !type->call_finish( this, &you ) ) {
                 // "Finish" is never a misnomer for any activity without a finish function
                 set_to_null();
             }
         }
     }
     if( !*this ) {
         // Make sure data of previous activity is cleared
         you.activity = player_activity();
         you.resume_backlog_activity();
         // If whatever activity we were doing forced us to pick something up to
         // handle it, drop any overflow that may have caused
         you.drop_invalid_inventory();
     }
 }
References _, ACT_MIGRATION_CANCEL, ACT_TRAVELLING, ACT_WAIT_STAMINA, ACT_WORKOUT_ACTIVE, ACT_WORKOUT_HARD, ACT_WORKOUT_LIGHT, ACT_WORKOUT_MODERATE, effect_on_condition::activate(), ACTIVATION, Character::activity, actor, Character::add_msg_if_player(), uilist::addentry(), Character::assign_activity(), auto_resume, activity_type::based_on(), activity_type::call_do_turn(), activity_type::call_finish(), Character::cancel_activity(), canceled(), stomach_contents::capacity(), character_finished_activity, Character::check_outbounds_activity(), activity_type::completion_EOC, stomach_contents::contains(), debugmsg, activity_actor::do_turn(), activity_type::do_turn_EOC, Character::drop_invalid_inventory(), effect_nausea, Character::exertion_adjusted_move_multiplier(), exertion_level(), activity_actor::finish(), get_auto_consume_moves(), get_event_bus(), Character::get_kcal_percent(), Creature::get_moves(), Character::get_stamina(), Character::get_stamina_max(), get_talker_for(), Character::get_thirst(), activity_actor::get_type(), Character::getID(), Creature::has_effect(), have_fire, id(), ignoreQuery, Creature::is_avatar(), Character::is_npc(), string_id< T >::is_null(), Creature::mod_moves(), moves_left, moves_total, no_drink_nearby_for_auto_consume, no_food_nearby_for_auto_consume, calendar::once_every(), one_in(), Character::pause(), player_activity(), uilist::query(), Character::resume_backlog_activity(), uilist::ret, Character::rooted(), activity_type::rooted(), event_bus::send(), Character::set_activity_level(), Creature::set_moves(), set_to_null(), SPEED, Character::stomach, synchronize_type_with_actor(), uilist::text, TIME, try_fuel_fire(), effect_on_condition::type, type, UILIST_CANCEL, activity_type::valid_auto_needs(), values, and activity_type::will_refuel_fires().
Referenced by npc::do_player_activity(), and npc::drop().
exertion_level()
float player_activity::exertion_level () const
Definition at line 417 of file player_activity.cpp.
 {
     if( actor ) {
         return actor->exertion_level();
     }
     return type->exertion_level();
 }
References actor, activity_actor::exertion_level(), activity_type::exertion_level(), and type.
Referenced by do_turn().
get_distractions()
std::map< distraction_type, std::string > player_activity::get_distractions () const
Definition at line 500 of file player_activity.cpp.
 {
     std::map<distraction_type, std::string> res;
     if( moves_left <= 0 ) {
         return res;
     }
     if( uistate.distraction_hostile_close &&
         !is_distraction_ignored( distraction_type::hostile_spotted_near ) ) {
         if( Creature *hostile_critter = g->is_hostile_very_close( true ) ) {
             res.emplace( distraction_type::hostile_spotted_near,
                          string_format( _( "The %s is dangerously close!" ), hostile_critter->get_name() ) );
         }
     }
     if( uistate.distraction_dangerous_field &&
         !is_distraction_ignored( distraction_type::dangerous_field ) ) {
         if( field_entry *field = g->is_in_dangerous_field() ) {
             res.emplace( distraction_type::dangerous_field,
                          string_format( _( "You stand in %s!" ), field->name() ) );
         }
     }
     avatar &u = get_avatar();
     if( uistate.distraction_hunger && !is_distraction_ignored( distraction_type::hunger ) ) {
         // Starvation value of 5300 equates to about 5kCal.
         if( calendar::once_every( 2_hours ) &&
             u.get_hunger() >= 300 &&
             u.get_starvation() > 5300 ) {
             res.emplace( distraction_type::hunger, _( "You are at risk of starving!" ) );
         }
     }
     if( uistate.distraction_thirst && !is_distraction_ignored( distraction_type::thirst ) ) {
         if( u.get_thirst() > 520 ) {
             res.emplace( distraction_type::thirst, _( "You are dangerously dehydrated!" ) );
         }
     }
     if( uistate.distraction_temperature && !is_distraction_ignored( distraction_type::temperature ) ) {
         for( const bodypart_id &bp : u.get_all_body_parts() ) {
             const units::temperature bp_temp = u.get_part_temp_cur( bp );
             if( bp_temp > BODYTEMP_VERY_HOT ) {
                 res.emplace( distraction_type::temperature, _( "You are overheating!" ) );
                 break;
             } else if( bp_temp < BODYTEMP_VERY_COLD ) {
                 res.emplace( distraction_type::temperature, _( "You are freezing!" ) );
                 break;
             }
         }
     }
     return res;
 }
References _, BODYTEMP_VERY_COLD, BODYTEMP_VERY_HOT, bp, dangerous_field, uistatedata::distraction_dangerous_field, uistatedata::distraction_hostile_close, uistatedata::distraction_hunger, uistatedata::distraction_temperature, uistatedata::distraction_thirst, g, get_avatar(), hostile_spotted_near, hunger, is_distraction_ignored(), moves_left, calendar::once_every(), string_format(), temperature, thirst, u, and uistate.
get_progress_message()
std::optional< std::string > player_activity::get_progress_message (const avatar & u) const
Helper that returns an activity specific progress message.
Definition at line 139 of file player_activity.cpp.
 {
     if( type == ACT_NULL || get_verb().empty() ) {
         return std::optional<std::string>();
     }
     if( type == ACT_ADV_INVENTORY ||
         type == ACT_AIM ||
         type == ACT_ARMOR_LAYERS ||
         type == ACT_ATM ||
         type == ACT_CONSUME_DRINK_MENU ||
         type == ACT_CONSUME_FOOD_MENU ||
         type == ACT_CONSUME_MEDS_MENU ||
         type == ACT_EAT_MENU ||
         type == ACT_INVOKE_ITEM ||
         type == ACT_PICKUP_MENU ||
         type == ACT_VIEW_RECIPE ) {
         return std::nullopt;
     }
     std::string extra_info;
     if( type == ACT_READ ) {
         if( const item *book = targets.front().get_item() ) {
             if( const auto &reading = book->type->book ) {
                 const skill_id &skill = reading->skill;
                 if( skill && u.get_knowledge_level( skill ) < reading->level &&
                     u.get_skill_level_object( skill ).can_train() && u.has_identified( book->typeId() ) ) {
                     const SkillLevel &skill_level = u.get_skill_level_object( skill );
                     //~ skill_name current_skill_level -> next_skill_level (% to next level)
                     extra_info = string_format( pgettext( "reading progress", "%s %d -> %d (%d%%)" ),
                                                 skill.obj().name(),
                                                 skill_level.knowledgeLevel(),
                                                 skill_level.knowledgeLevel() + 1,
                                                 skill_level.knowledgeExperience() );
                 }
             }
         }
     } else if( moves_total > 0 ) {
         if( type == ACT_HACKSAW ||
             type == ACT_JACKHAMMER ||
             type == ACT_PICKAXE ||
             type == ACT_VEHICLE ||
             type == ACT_CHOP_TREE ||
             type == ACT_CHOP_LOGS ||
             type == ACT_CHOP_PLANKS ||
             type == ACT_HEATING
           ) {
             const int percentage = ( ( moves_total - moves_left ) * 100 ) / moves_total;
             extra_info = string_format( "%d%%", percentage );
         }
         if( type == ACT_BUILD ) {
             partial_con *pc =
                 get_map().partial_con_at( get_map().bub_from_abs( u.activity.placement ) );
             if( pc ) {
                 int counter = std::min( pc->counter, 10000000 );
                 const int percentage = counter / 100000;
                 extra_info = string_format( "%d%%", percentage );
             }
         }
         if( type == ACT_SPELLCASTING ) {
             const std::string spell_name = u.magic->get_spell( spell_id( name ) ).name();
             extra_info = string_format( "%s ", spell_name );
         }
     }
     if( actor ) {
         extra_info = actor->get_progress_message( *this );
     }
     return extra_info.empty() ? string_format( _( "%s" ),
             get_verb().translated() ) : string_format( _( "%s: %s" ),
                     get_verb().translated(), extra_info );
 }
References _, ACT_ADV_INVENTORY, ACT_AIM, ACT_ARMOR_LAYERS, ACT_ATM, ACT_BUILD, ACT_CHOP_LOGS, ACT_CHOP_PLANKS, ACT_CHOP_TREE, ACT_CONSUME_DRINK_MENU, ACT_CONSUME_FOOD_MENU, ACT_CONSUME_MEDS_MENU, ACT_EAT_MENU, ACT_HACKSAW, ACT_HEATING, ACT_INVOKE_ITEM, ACT_JACKHAMMER, ACT_NULL, ACT_PICKAXE, ACT_PICKUP_MENU, ACT_READ, ACT_SPELLCASTING, ACT_VEHICLE, ACT_VIEW_RECIPE, actor, partial_con::counter, get_map(), activity_actor::get_progress_message(), get_verb(), SkillLevel::knowledgeExperience(), SkillLevel::knowledgeLevel(), min(), moves_left, moves_total, name, Skill::name(), string_id< T >::obj(), map::partial_con_at(), pgettext, spell_id, string_format(), targets, type, and u.
get_stop_phrase()
std::string player_activity::get_stop_phrase () const
Definition at line 109 of file player_activity.cpp.
 {
     return type->stop_phrase();
 }
References activity_type::stop_phrase(), and type.
Referenced by game::cancel_activity_or_ignore_query(), and game::cancel_activity_query().
get_str_value()
std::string player_activity::get_str_value (size_t index, std::string_view def = {}) const
Definition at line 134 of file player_activity.cpp.
 {
     return std::string( index < str_values.size() ? str_values[index] : def );
 }
References index, and str_values.
get_value()
int player_activity::get_value (size_t index, int def = 0) const
Definition at line 119 of file player_activity.cpp.
 {
     return index < values.size() ? values[index] : def;
 }
References index, and values.
Referenced by Character::complete_disassemble().
get_verb()
const translation & player_activity::get_verb () const
Definition at line 114 of file player_activity.cpp.
 {
     return type->verb();
 }
References type, and activity_type::verb().
Referenced by get_progress_message(), and basecamp::job_assignment_ui().
id()
const activity_id& player_activity::id () const inline
Definition at line 114 of file player_activity.h.
{
             return type;
         }
References type.
Referenced by Character::assign_activity(), iexamine::autodoc(), Character::calc_focus_equilibrium(), game::cancel_activity_query(), Character::disassemble(), npc::do_player_activity(), do_turn(), avatar_action::eat(), Character::fall_asleep(), firstaid_activity_actor::finish(), Character::has_activity(), Character::has_distant_destination(), Character::in_sleep_state(), npc::move(), npc::set_mission(), avatar::talk_to(), activity_handlers::train_finish(), Character::update_needs(), and heal_actor::use_healing_item().
ignore_distraction()
void player_activity::ignore_distraction (distraction_type type)
Definition at line 483 of file player_activity.cpp.
 {
     ignored_distractions.emplace( type );
 }
References ignored_distractions, and type.
Referenced by game::cancel_activity_or_ignore_query(), Character::cast_spell(), inherit_distractions(), and game::portal_storm_query().
inherit_distractions()
void player_activity::inherit_distractions (const player_activity & other)
Definition at line 493 of file player_activity.cpp.
 {
     for( const distraction_type &type : other.ignored_distractions ) {
         ignore_distraction( type );
     }
 }
References ignore_distraction(), other, and type.
is_distraction_ignored()
bool player_activity::is_distraction_ignored (distraction_type distraction) const
Definition at line 478 of file player_activity.cpp.
 {
     return !is_interruptible() || ignored_distractions.count( distraction );
 }
References ignored_distractions, and is_interruptible().
Referenced by game::cancel_activity_or_ignore_query(), get_distractions(), game::portal_storm_query(), and sounds::process_sound_markers().
is_interruptible()
bool player_activity::is_interruptible () const
Definition at line 468 of file player_activity.cpp.
 {
     return ( type.is_null() || type->interruptable() ) && interruptable;
 }
References activity_type::interruptable(), interruptable, string_id< T >::is_null(), and type.
Referenced by is_distraction_ignored().
is_interruptible_with_kb()
bool player_activity::is_interruptible_with_kb () const
Definition at line 473 of file player_activity.cpp.
 {
     return ( type.is_null() || type->interruptable_with_kb() ) && interruptable_with_kb;
 }
References activity_type::interruptable_with_kb(), interruptable_with_kb, string_id< T >::is_null(), and type.
is_multi_type()
bool player_activity::is_multi_type () const
Definition at line 129 of file player_activity.cpp.
 {
     return type->multi_activity();
 }
References activity_type::multi_activity(), and type.
Referenced by npc::do_player_activity(), and activity_handlers::resume_for_multi_activities().
is_null()
bool player_activity::is_null () const inline
Definition at line 102 of file player_activity.h.
{
             return type.is_null();
         }
References string_id< T >::is_null(), and type.
Referenced by veh_app_interact::app_loop(), veh_interact::do_main_loop(), talker_character_const::has_activity(), talker_npc::has_activity(), Character::has_destination_activity(), and Character::has_distant_destination().
operator bool()
player_activity::operator bool () const inline explicit
Definition at line 99 of file player_activity.h.
{
             return !type.is_null();
         }
References string_id< T >::is_null(), and type.
operator=() [1/2]
player_activity& player_activity::operator= (const player_activity &) default
operator=() [2/2]
player_activity& player_activity::operator= (player_activity &&) default noexcept
rooted()
bool player_activity::rooted () const
Definition at line 104 of file player_activity.cpp.
 {
     return type->rooted();
 }
References activity_type::rooted(), and type.
Referenced by start_or_resume().
serialize()
void player_activity::serialize (JsonOut & json) const
Definition at line 339 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "type", type );
     if( !type.is_null() ) {
         json.member( "actor", actor );
         json.member( "moves_total", moves_total );
         json.member( "moves_left", moves_left );
         json.member( "interruptable", interruptable );
         json.member( "interruptable_with_kb", interruptable_with_kb );
         json.member( "index", index );
         json.member( "position", position );
         json.member( "coords", coords );
         json.member( "coord_set", coord_set );
         json.member( "name", name );
         json.member( "targets", targets );
         json.member( "placement", placement );
         json.member( "relative_placement", relative_placement );
         json.member( "values", values );
         json.member( "str_values", str_values );
         json.member( "auto_resume", auto_resume );
         json.member( "monsters", monsters );
     }
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), om_direction::name(), JsonOut::start_object(), and type.
set_to_null()
void player_activity::set_to_null ()
This replaces the former usage act.type = ACT_NULL
Definition at line 91 of file player_activity.cpp.
 {
     type = activity_id::NULL_ID();
     sfx::end_activity_sounds(); // kill activity sounds when activity is nullified
 }
References sfx::end_activity_sounds(), string_id< activity_type >::NULL_ID(), and type.
Referenced by activity_on_turn_move_loot(), complete_construction(), Character::complete_disassemble(), veh_interact::complete_vehicle(), do_turn(), unload_loot_activity_actor::do_turn(), construct::do_turn_exhume(), Character::fall_asleep(), activity_handlers::fill_liquid_do_turn(), Character::hardcoded_effects(), perform_zone_activity_turn(), sounds::process_sound_markers(), and player_difficulty::reset_npc().
start_or_resume()
void player_activity::start_or_resume (Character & who, bool resuming)
Preform necessary initialization to start or resume the activity.
Must be called whenever a Character starts a new activity. When resuming an activity, do not call activity_actor::start
Definition at line 217 of file player_activity.cpp.
 {
     if( actor && !resuming ) {
         actor->start( *this, who );
     }
     if( !type.is_null() && rooted() ) {
         who.rooted_message();
     }
     // last, as start function may have changed the type
     synchronize_type_with_actor();
     get_event_bus().send<event_type::character_starts_activity>( who.getID(), type, resuming );
 }
References actor, character_starts_activity, get_event_bus(), Character::getID(), string_id< T >::is_null(), rooted(), Character::rooted_message(), event_bus::send(), activity_actor::start(), synchronize_type_with_actor(), and type.
Referenced by Character::assign_activity().
synchronize_type_with_actor()
void player_activity::synchronize_type_with_actor ()
Definition at line 97 of file player_activity.cpp.
 {
     if( actor && type != activity_id::NULL_ID() ) {
         type = actor->get_type();
     }
 }
References actor, activity_actor::get_type(), string_id< activity_type >::NULL_ID(), and type.
Referenced by do_turn(), and start_or_resume().
Member Data Documentation
actor
cata::clone_ptr<activity_actor> player_activity::actor private
Definition at line 36 of file player_activity.h.
Referenced by can_resume_with(), canceled(), do_drop_invalid_inventory(), do_turn(), exertion_level(), get_progress_message(), start_or_resume(), and synchronize_type_with_actor().
auto_resume
bool player_activity::auto_resume = false
If true, the activity will be auto-resumed next time the player attempts an identical activity.
This value is set dynamically.
Definition at line 78 of file player_activity.h.
Referenced by pickup_selector::add_reopen_activity(), can_resume_with(), advanced_inventory::do_return_entry(), do_turn(), firstaid_activity_actor::finish(), game::place_player(), Character::resume_backlog_activity(), iexamine::shrub_wildveggies(), outfit::sort_armor(), and link_up_actor::use().
coord_set
std::unordered_set<tripoint> player_activity::coord_set
Definition at line 65 of file player_activity.h.
Referenced by veh_interact::complete_vehicle(), iuse::fishing_rod(), generic_multi_activity_do(), veh_app_interact::refill(), veh_app_interact::remove(), veh_interact::serialize_activity(), and vehicle_activity().
coords
std::vector<tripoint> player_activity::coords
Definition at line 64 of file player_activity.h.
Referenced by Character::cast_spell(), activity_handlers::fill_liquid_do_turn(), and generic_multi_activity_check_requirement().
have_fire
bool player_activity::have_fire = true
Flag that will suppress the relatively expensive fire refueling search process.
Initially assume there is a fire unless the activity proves not to have one.
Definition at line 82 of file player_activity.h.
Referenced by do_turn().
ignored_distractions
std::set<distraction_type> player_activity::ignored_distractions private
Definition at line 38 of file player_activity.h.
Referenced by allow_distractions(), ignore_distraction(), is_distraction_ignored(), and player_activity().
ignoreQuery
bool player_activity::ignoreQuery = false private
Definition at line 40 of file player_activity.h.
Referenced by do_turn().
index
int player_activity::index = 0
Definition at line 54 of file player_activity.h.
Referenced by can_resume_with(), game::cancel_activity_query(), Character::complete_disassemble(), veh_interact::complete_vehicle(), Character::disassemble(), Character::disassemble_all(), get_str_value(), get_value(), and avatar::talk_to().
interruptable
bool player_activity::interruptable = true
Controls whether this activity can be cancelled at all.
Definition at line 48 of file player_activity.h.
Referenced by is_interruptible().
interruptable_with_kb
bool player_activity::interruptable_with_kb = true
Controls whether this activity can be cancelled with 'pause' action.
Definition at line 50 of file player_activity.h.
Referenced by is_interruptible_with_kb().
invalid_place
constexpr tripoint_abs_ms player_activity::invalid_place { tripoint_min } static constexpr
Definition at line 67 of file player_activity.h.
Referenced by can_do_activity_there(), and Character::check_outbounds_activity().
monsters
std::vector<weak_ptr_fast<monster> > player_activity::monsters
Definition at line 66 of file player_activity.h.
moves_left
int player_activity::moves_left = calendar::INDEFINITELY_LONG
The number of moves remaining in this activity before it is complete.
Definition at line 46 of file player_activity.h.
Referenced by iexamine::autodoc(), Character::disassemble(), do_turn(), get_distractions(), get_progress_message(), outfit::sort_armor(), and learn_spell_actor::use().
moves_total
int player_activity::moves_total = 0
Total number of moves required to complete the activity.
Definition at line 44 of file player_activity.h.
Referenced by do_turn(), get_progress_message(), and learn_spell_actor::use().
name
std::string player_activity::name
Definition at line 60 of file player_activity.h.
Referenced by can_resume_with(), Character::cast_spell(), dialogue::gen_responses(), get_progress_message(), and learn_spell_actor::use().
no_drink_nearby_for_auto_consume
bool player_activity::no_drink_nearby_for_auto_consume = false
Definition at line 73 of file player_activity.h.
Referenced by do_turn().
no_food_nearby_for_auto_consume
bool player_activity::no_food_nearby_for_auto_consume = false
Definition at line 74 of file player_activity.h.
Referenced by do_turn().
placement
tripoint_abs_ms player_activity::placement
Definition at line 68 of file player_activity.h.
Referenced by npc::address_needs(), butcher_corpse_activity(), can_do_activity_there(), iuse::chop_logs(), chop_plank_activity(), iuse::chop_tree(), chop_tree_activity(), complete_construction(), construction_activity(), iuse::cut_log_into_planks(), dig_tool(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), iuse::makemound(), mine_activity(), mop_activity(), iexamine::part_con(), place_construction(), game::place_player(), iexamine::rubble(), iexamine::shrub_wildveggies(), smash(), iexamine::try_start_hacking(), firestarter_actor::use(), and vehicle_activity().
position
int player_activity::position = 0
An activity specific value.
DO NOT USE FOR ITEM INDEX
Definition at line 59 of file player_activity.h.
Referenced by can_resume_with(), Character::complete_disassemble(), Character::create_in_progress_disassembly(), Character::disassemble(), and iuse::portable_game().
relative_placement
tripoint_rel_ms player_activity::relative_placement
Definition at line 71 of file player_activity.h.
Referenced by vehicle::start_engines().
str_values
std::vector<std::string> player_activity::str_values
Definition at line 63 of file player_activity.h.
Referenced by talk_function::buy_haircut(), talk_function::buy_shave(), can_resume_with(), complete_construction(), veh_interact::complete_vehicle(), game_menus::inv::consume(), game_menus::inv::consume_drink(), game_menus::inv::consume_food(), game_menus::inv::consume_meds(), avatar_action::eat(), activity_handlers::fill_liquid_do_turn(), consume_activity_actor::finish(), generic_multi_activity_check_requirement(), generic_multi_activity_handler(), get_str_value(), talk_function::give_aid(), talk_function::give_all_aid(), Character::install_bionics(), talk_function::lesser_give_aid(), talk_function::lesser_give_all_aid(), talk_function::morale_chat_activity(), game::place_player(), veh_app_interact::refill(), veh_app_interact::remove(), veh_interact::serialize_activity(), Character::uninstall_bionic(), repair_item_actor::use(), heal_actor::use(), learn_spell_actor::use(), heal_actor::use_healing_item(), and vehicle_activity().
targets
std::vector<item_location> player_activity::targets
Definition at line 61 of file player_activity.h.
Referenced by game::butcher(), butcher_corpse_activity(), Character::calc_focus_equilibrium(), can_resume_with(), Character::complete_disassemble(), veh_interact::complete_vehicle(), dig_tool(), Character::disassemble(), avatar_action::eat(), activity_handlers::fill_liquid_do_turn(), consume_activity_actor::finish(), iuse::fishing_rod(), generic_multi_activity_do(), get_progress_message(), Character::gunmod_add(), iuse::hand_crank(), heat_item(), mine_activity(), game::place_player(), iuse::portable_game(), Character::process_turn(), veh_app_interact::refill(), repair_item_finish(), veh_interact::serialize_activity(), Character::toolmod_add(), firestarter_actor::use(), repair_item_actor::use(), heal_actor::use(), cast_spell_actor::use(), vehicle_activity(), and iuse::vibe().
type
activity_id player_activity::type private
Definition at line 35 of file player_activity.h.
Referenced by can_resume(), can_resume_with(), canceled(), do_turn(), exertion_level(), get_progress_message(), get_stop_phrase(), get_verb(), id(), ignore_distraction(), inherit_distractions(), is_interruptible(), is_interruptible_with_kb(), is_multi_type(), is_null(), operator bool(), player_activity(), rooted(), set_to_null(), start_or_resume(), and synchronize_type_with_actor().
values
std::vector<int> player_activity::values
Definition at line 62 of file player_activity.h.
Referenced by Character::activate_mutation(), can_resume_with(), game::cancel_activity_query(), Character::cast_spell(), veh_interact::complete_vehicle(), Character::disassemble(), do_turn(), avatar_action::eat(), activity_handlers::fill_liquid_do_turn(), consume_activity_actor::finish(), generic_multi_activity_check_requirement(), get_value(), Character::gunmod_add(), Character::install_bionics(), iuse::portable_game(), veh_app_interact::refill(), veh_app_interact::remove(), veh_interact::serialize_activity(), vehicle::start_engines(), talk_function::start_training_gen(), activity_handlers::train_finish(), Character::uninstall_bionic(), firestarter_actor::use(), learn_spell_actor::use(), and vehicle_activity().
The documentation for this class was generated from the following files:
src/player_activity.h
src/player_activity.cpp
src/savegame_json.cpp
src/savegame_legacy.cpp