Cataclysm DDA: item_action_generator Class Reference
item_action_generator Class Reference
#include <item_action.h>
Public Member Functions
item_action_generator ()
~item_action_generator ()
item_action_map map_actions_to_items (Character &you) const
item_action_map map_actions_to_items (Character &you, const std::vector< item * > &pseudos, bool use_player_inventory=true) const
Assigns items to actions they perform on use.
std::string get_action_name (const item_action_id &id) const
bool action_exists (const item_action_id &id) const
const item_action & get_action (const item_action_id &id) const
const action_map & get_item_action_map () const
void load_item_action (const JsonObject &jo)
void check_consistency () const
Static Public Member Functions
static item_action_generator & generator ()
Private Attributes
action_map item_actions
Detailed Description
Definition at line 28 of file item_action.h.
Constructor & Destructor Documentation
item_action_generator()
item_action_generator::item_action_generator () default
~item_action_generator()
item_action_generator::~item_action_generator () default
Member Function Documentation
action_exists()
bool item_action_generator::action_exists (const item_action_id & id) const
Definition at line 210 of file item_action.cpp.
 {
     return item_actions.find( id ) != item_actions.end();
 }
References item_actions.
Referenced by iuse_actor::is_valid().
check_consistency()
void item_action_generator::check_consistency () const
Definition at line 238 of file item_action.cpp.
 {
     for( const auto &elem : item_actions ) {
         const item_action &action = elem.second;
         if( !item_controller->has_iuse( action.id ) ) {
             debugmsg( "Item action \"%s\" isn't known to the game.  Check item action definitions in JSON.",
                       action.id.c_str() );
         }
     }
 }
References action, debugmsg, item_actions, and item_controller.
Referenced by DynamicDataLoader::check_consistency().
generator()
static item_action_generator& item_action_generator::generator () inline static
Definition at line 33 of file item_action.h.
{
             static item_action_generator generator;
             return generator;
         }
Referenced by DynamicDataLoader::check_consistency(), iuse_actor::get_name(), DynamicDataLoader::initialize(), iuse_actor::is_valid(), and game::item_action_menu().
get_action()
const item_action & item_action_generator::get_action (const item_action_id & id) const
Definition at line 215 of file item_action.cpp.
 {
     const auto &iter = item_actions.find( id );
     if( iter != item_actions.end() ) {
         return iter->second;
     }
     debugmsg( "Couldn't find item action named %s", id.c_str() );
     return nullaction;
 }
References debugmsg, item_actions, and nullaction.
Referenced by get_action_name().
get_action_name()
std::string item_action_generator::get_action_name (const item_action_id & id) const
Definition at line 200 of file item_action.cpp.
 {
     const item_action &act = get_action( id );
     if( !act.name.empty() ) {
         return act.name.translated();
     }
     return id;
 }
References act, get_action(), and base_camps::id.
Referenced by iuse_actor::get_name().
get_item_action_map()
const action_map& item_action_generator::get_item_action_map () const inline
Definition at line 63 of file item_action.h.
{
             return item_actions;
         }
References item_actions.
Referenced by game::item_action_menu().
load_item_action()
void item_action_generator::load_item_action (const JsonObject & jo)
Definition at line 226 of file item_action.cpp.
 {
     item_action ia;
     ia.id = jo.get_string( "id" );
     if( !jo.read( "name", ia.name ) || ia.name.empty() ) {
         ia.name = no_translation( ia.id );
     }
     item_actions[ia.id] = ia;
 }
References translation::empty(), JsonObject::get_string(), item_action::id, item_actions, item_action::name, no_translation(), and JsonObject::read().
Referenced by DynamicDataLoader::initialize().
map_actions_to_items() [1/2]
item_action_map item_action_generator::map_actions_to_items (Character & you) const
Definition at line 110 of file item_action.cpp.
 {
     return map_actions_to_items( you, std::vector<item *>() );
 }
Referenced by game::item_action_menu().
map_actions_to_items() [2/2]
item_action_map item_action_generator::map_actions_to_items (Character & you, const std::vector< item * > & pseudos, bool use_player_inventory = true) const
Assigns items to actions they perform on use.
Prefers items with smaller charge_per_use. "pseudos" are extra items not in player's inventory that should still be mapped.
Parameters
use_player_inventory If true then include all of player inventory.
Returns
actions mapped to items
Definition at line 115 of file item_action.cpp.
 {
     std::set< item_action_id > unmapped_actions;
     for( const auto &ia_ptr : item_actions ) { // Get ids of wanted actions
         unmapped_actions.insert( ia_ptr.first );
     }
     item_action_map candidates;
     std::vector< item * > items;
     // Default behavior
     if( use_player_inventory ) {
         items = you.inv_dump();
         items.reserve( items.size() + pseudos.size() );
         items.insert( items.end(), pseudos.begin(), pseudos.end() );
     } else {
         items = pseudos;
     }
     std::unordered_set< item_action_id > to_remove;
     for( item *i : items ) {
         if( !i->item_has_uses_recursive() ) {
             continue;
         }
         for( const item_action_id &use : unmapped_actions ) {
             // Actually used item can be different from the "outside item"
             // For example, sheathed knife
             item *actual_item = i->get_usable_item( use );
             if( actual_item == nullptr ) {
                 continue;
             }
             const use_function *func = actual_item->get_use( use );
             if( !( func && func->get_actor_ptr() &&
                    func->get_actor_ptr()->can_use( you, *actual_item, you.pos() ).success() ) ) {
                 continue;
             }
             if( !actual_item->ammo_sufficient( &you, use ) ) {
                 continue;
             }
             // Don't try to remove 'irremovable' toolmods
             if( actual_item->is_toolmod() && use == STATIC( item_action_id( "TOOLMOD_ATTACH" ) ) &&
                 actual_item->has_flag( STATIC( flag_id( "IRREMOVABLE" ) ) ) ) {
                 continue;
             }
             // Prevent drinking frozen liquids that have specific use actions (ex: ALCOHOL)
             if( actual_item->is_frozen_liquid() ) {
                 continue;
             }
             // Add to usable items if it needs less charges per use or has less charges
             auto found = candidates.find( use );
             bool better = false;
             if( found == candidates.end() ) {
                 better = true;
             } else {
                 if( actual_item->ammo_required() > found->second->ammo_required() ) {
                     continue; // Other item consumes less charges
                 }
                 if( found->second->ammo_remaining() > actual_item->ammo_remaining() ) {
                     better = true; // Items with less charges preferred
                 }
             }
             if( better ) {
                 candidates[use] = actual_item;
                 if( actual_item->ammo_required() == 0 ) {
                     to_remove.insert( use );
                 }
             }
         }
         for( const item_action_id &r : to_remove ) {
             unmapped_actions.erase( r );
         }
     }
     return candidates;
 }
References item::ammo_remaining(), item::ammo_required(), item::ammo_sufficient(), flag_id, item::get_usable_item(), item::get_use(), item::has_flag(), Character::inv_dump(), item::is_frozen_liquid(), item::is_toolmod(), item_actions, Creature::pos(), STATIC, and game_menus::inv::use().
Member Data Documentation
item_actions
action_map item_action_generator::item_actions private
Definition at line 31 of file item_action.h.
Referenced by action_exists(), check_consistency(), get_action(), get_item_action_map(), load_item_action(), and map_actions_to_items().
The documentation for this class was generated from the following files:
src/item_action.h
src/item_action.cpp