Cataclysm DDA: computer Class Reference
computer Class Reference
#include <computer.h>
Public Member Functions
computer (const std::string &new_name, int new_security, tripoint new_loc)
void set_security (int Security)
void add_option (const computer_option &opt)
void add_eoc (const effect_on_condition_id &eoc)
void add_chat_topic (const std::string &topic)
void add_option (const std::string &opt_name, computer_action action, int security)
void add_failure (const computer_failure &failure)
void add_failure (computer_failure_type failure)
void set_access_denied_msg (const std::string &new_msg)
void set_mission (int id)
void load_legacy_data (const std::string &data)
void serialize (JsonOut &jout) const
void deserialize (const JsonValue &jv)
void set_value (const std::string &key, const std::string &value)
void remove_value (const std::string &key)
std::optional< std::string > maybe_get_value (const std::string &key) const
void remove_option (computer_action action)
Public Attributes
tripoint loc
std::string name
int mission_id
int security
int alerts
time_point next_attempt
std::vector< computer_option > options
std::vector< computer_failure > failures
std::string access_denied
std::vector< std::string > chat_topics
std::vector< effect_on_condition_id > eocs
std::unordered_map< std::string, std::string > values
Friends
class computer_session
Detailed Description
Definition at line 119 of file computer.h.
Constructor & Destructor Documentation
computer()
computer::computer (const std::string & new_name, int new_security, tripoint new_loc)
Definition at line 66 of file computer.cpp.
     : name( new_name ), mission_id( -1 ), security( new_security ), alerts( 0 ),
       next_attempt( calendar::before_time_starts ),
       access_denied( _( "ERROR!  Access denied!" ) )
 {
     loc = new_loc;
 }
References loc.
Member Function Documentation
add_chat_topic()
void computer::add_chat_topic (const std::string & topic)
Definition at line 89 of file computer.cpp.
 {
     chat_topics.emplace_back( topic );
 }
References chat_topics.
Referenced by jmapgen_computer::apply().
add_eoc()
void computer::add_eoc (const effect_on_condition_id & eoc)
Definition at line 84 of file computer.cpp.
 {
     eocs.emplace_back( eoc );
 }
References eoc, and eocs.
Referenced by jmapgen_computer::apply().
add_failure() [1/2]
void computer::add_failure (computer_failure_type failure)
Definition at line 105 of file computer.cpp.
 {
     add_failure( computer_failure( failure ) );
 }
References add_failure().
add_failure() [2/2]
void computer::add_failure (const computer_failure & failure)
Definition at line 100 of file computer.cpp.
 {
     failures.emplace_back( failure );
 }
References failures.
Referenced by add_failure(), jmapgen_computer::apply(), create_lab_consoles(), map::draw_lab(), load_legacy_data(), and science_room().
add_option() [1/2]
void computer::add_option (const computer_option & opt)
Definition at line 79 of file computer.cpp.
 {
     options.emplace_back( opt );
 }
References options.
Referenced by add_option(), jmapgen_computer::apply(), create_lab_consoles(), map::draw_lab(), load_legacy_data(), mission_start::place_npc_software(), and science_room().
add_option() [2/2]
void computer::add_option (const std::string & opt_name, computer_action action, int security)
Definition at line 94 of file computer.cpp.
 {
     add_option( computer_option( opt_name, action, security ) );
 }
References action, add_option(), and security.
deserialize()
void computer::deserialize (const JsonValue & jv)
Definition at line 210 of file computer.cpp.
 {
     if( jv.test_string() ) {
         load_legacy_data( jv.get_string() );
     } else {
         const JsonObject jo = jv.get_object();
         jo.read( "name", name );
         jo.read( "mission", mission_id );
         jo.read( "security", security );
         jo.read( "alerts", alerts );
         jo.read( "next_attempt", next_attempt );
         jo.read( "options", options );
         jo.read( "failures", failures );
         jo.read( "access_denied", access_denied );
         jo.read( "eocs", eocs );
         jo.read( "chat_topics", chat_topics );
         jo.read( "values", values );
         jo.read( "loc", loc );
     }
 }
References access_denied, alerts, chat_topics, eocs, failures, JsonValue::get_object(), JsonValue::get_string(), load_legacy_data(), loc, name, next_attempt, options, JsonObject::read(), security, JsonValue::test_string(), and values.
load_legacy_data()
void computer::load_legacy_data (const std::string & data)
Definition at line 140 of file computer.cpp.
 {
     options.clear();
     failures.clear();
     std::istringstream dump( data );
     dump.imbue( std::locale::classic() );
     dump >> name >> security >> mission_id;
     name = string_replace( name, "_", " " );
     // Pull in options
     int optsize;
     dump >> optsize;
     for( int n = 0; n < optsize; n++ ) {
         std::string tmpname;
         int tmpaction;
         int tmpsec;
         dump >> tmpname >> tmpaction >> tmpsec;
         // Legacy missile launch option that got removed before `computer_action` was
         // refactored to be saved and loaded as string ids. Do not change this number:
         // `computer_action` now has different underlying values from back then!
         if( tmpaction == 15 ) {
             continue;
         }
         add_option( string_replace( tmpname, "_", " " ), computer_action_from_legacy_enum( tmpaction ),
                     tmpsec );
     }
     // Pull in failures
     int failsize;
     dump >> failsize;
     for( int n = 0; n < failsize; n++ ) {
         int tmpfail;
         dump >> tmpfail;
         add_failure( computer_failure_type_from_legacy_enum( tmpfail ) );
     }
     std::string tmp_access_denied;
     dump >> tmp_access_denied;
     // For backwards compatibility, only set the access denied message if it
     // isn't empty. This is to avoid the message becoming blank when people
     // load old saves.
     if( !tmp_access_denied.empty() ) {
         access_denied = string_replace( tmp_access_denied, "_", " " );
     }
 }
References access_denied, add_failure(), add_option(), computer_action_from_legacy_enum(), computer_failure_type_from_legacy_enum(), failures, mission_id, name, options, security, and string_replace().
Referenced by deserialize().
maybe_get_value()
std::optional< std::string > computer::maybe_get_value (const std::string & key) const
Definition at line 131 of file computer.cpp.
 {
     auto it = values.find( key );
     return it == values.end() ? std::nullopt : std::optional<std::string> { it->second };
 }
References values.
Referenced by talker_furniture::maybe_get_value().
remove_option()
void computer::remove_option (computer_action action)
Definition at line 231 of file computer.cpp.
 {
     for( auto it = options.begin(); it != options.end(); ++it ) {
         if( it->action == action ) {
             options.erase( it );
             break;
         }
     }
 }
References action, and options.
Referenced by computer_session::action_amigara_start(), computer_session::action_extract_rad_source(), computer_session::action_map_sewer(), computer_session::action_map_subway(), computer_session::action_maps(), and computer_session::failure_amigara().
remove_value()
void computer::remove_value (const std::string & key)
Definition at line 126 of file computer.cpp.
 {
     values.erase( key );
 }
References values.
Referenced by talker_furniture::remove_value().
serialize()
void computer::serialize (JsonOut & jout) const
Definition at line 192 of file computer.cpp.
 {
     jout.start_object();
     jout.member( "name", name );
     jout.member( "mission", mission_id );
     jout.member( "security", security );
     jout.member( "alerts", alerts );
     jout.member( "next_attempt", next_attempt );
     jout.member( "options", options );
     jout.member( "failures", failures );
     jout.member( "access_denied", access_denied );
     jout.member( "eocs", eocs );
     jout.member( "chat_topics", chat_topics );
     jout.member( "values", values );
     jout.member( "loc", loc );
     jout.end_object();
 }
References access_denied, alerts, chat_topics, JsonOut::end_object(), eocs, failures, loc, JsonOut::member(), name, next_attempt, options, security, JsonOut::start_object(), and values.
set_access_denied_msg()
void computer::set_access_denied_msg (const std::string & new_msg)
Definition at line 110 of file computer.cpp.
 {
     access_denied = new_msg;
 }
References access_denied.
Referenced by jmapgen_computer::apply(), map::draw_lab(), and science_room().
set_mission()
void computer::set_mission (int id)
Definition at line 115 of file computer.cpp.
 {
     mission_id = id;
 }
References base_camps::id.
Referenced by jmapgen_computer::apply(), create_lab_consoles(), and mission_start::place_npc_software().
set_security()
void computer::set_security (int Security)
Definition at line 74 of file computer.cpp.
 {
     security = Security;
 }
References security.
set_value()
void computer::set_value (const std::string & key, const std::string & value)
Definition at line 121 of file computer.cpp.
 {
     values[ key ] = value;
 }
References values.
Referenced by talker_furniture::set_value().
Friends And Related Function Documentation
computer_session
friend class computer_session friend
Definition at line 139 of file computer.h.
Member Data Documentation
access_denied
std::string computer::access_denied
Definition at line 158 of file computer.h.
Referenced by deserialize(), load_legacy_data(), serialize(), set_access_denied_msg(), and computer_session::use().
alerts
int computer::alerts
Definition at line 148 of file computer.h.
Referenced by computer_session::action_maps(), computer_session::action_radio_archive(), computer_session::action_research(), deserialize(), computer_session::hack_attempt(), serialize(), and computer_session::use().
chat_topics
std::vector<std::string> computer::chat_topics
Definition at line 159 of file computer.h.
Referenced by add_chat_topic(), deserialize(), talker_furniture::get_topics(), and serialize().
eocs
std::vector<effect_on_condition_id> computer::eocs
Definition at line 160 of file computer.h.
Referenced by add_eoc(), deserialize(), serialize(), and game::use_computer().
failures
std::vector<computer_failure> computer::failures
Definition at line 154 of file computer.h.
Referenced by computer_session::activate_random_failure(), add_failure(), deserialize(), load_legacy_data(), serialize(), and computer_session::use().
loc
tripoint computer::loc
Definition at line 140 of file computer.h.
Referenced by computer(), deserialize(), talker_furniture::global_pos(), talker_furniture::pos(), talker_furniture::posx(), talker_furniture::posy(), talker_furniture::posz(), and serialize().
mission_id
int computer::mission_id
Definition at line 144 of file computer.h.
Referenced by computer_session::action_download_software(), and load_legacy_data().
name
std::string computer::name
Definition at line 142 of file computer.h.
Referenced by deserialize(), talker_furniture::disp_name(), load_legacy_data(), serialize(), and computer_session::use().
next_attempt
time_point computer::next_attempt
Definition at line 150 of file computer.h.
Referenced by computer_session::action_toll(), computer_session::activate_random_failure(), deserialize(), serialize(), and computer_session::use().
options
std::vector<computer_option> computer::options
Definition at line 152 of file computer.h.
Referenced by computer_session::action_irradiator(), computer_session::action_miss_disarm(), computer_session::action_miss_launch(), computer_session::action_repeater_mod(), computer_session::action_srcf_seal(), add_option(), deserialize(), load_legacy_data(), remove_option(), serialize(), and computer_session::use().
security
int computer::security
Definition at line 146 of file computer.h.
Referenced by add_option(), deserialize(), computer_session::hack_attempt(), load_legacy_data(), serialize(), set_security(), and computer_session::use().
values
std::unordered_map<std::string, std::string> computer::values
Definition at line 162 of file computer.h.
Referenced by deserialize(), maybe_get_value(), remove_value(), serialize(), and set_value().
The documentation for this class was generated from the following files:
src/computer.h
src/computer.cpp