Cataclysm DDA: wash_activity_actor Class Reference
wash_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
wash_activity_actor (drop_locations to_wash, washing_requirements &requirements)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &p) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
wash_activity_actor ()=default
Private Attributes
drop_locations to_wash
washing_requirements requirements
Detailed Description
Definition at line 1673 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
wash_activity_actor() [1/2]
wash_activity_actor::wash_activity_actor () private default
wash_activity_actor() [2/2]
wash_activity_actor::wash_activity_actor (drop_locations to_wash, washing_requirements & requirements) inline
Definition at line 1678 of file activity_actor_definitions.h.
                                                                   :
             to_wash( std::move( to_wash ) ),
             requirements( requirements ) {};
Member Function Documentation
clone()
std::unique_ptr<activity_actor> wash_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1691 of file activity_actor_definitions.h.
{
             return std::make_unique<wash_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > wash_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 7679 of file activity_actor.cpp.
 {
     wash_activity_actor actor;
     JsonObject data = jsin.get_object();
     data.read( "to_wash", actor.to_wash );
     data.read( "time", actor.requirements.time );
     data.read( "water", actor.requirements.water );
     data.read( "cleanser", actor.requirements.cleanser );
     return actor.clone();
 }
References washing_requirements::cleanser, clone(), JsonValue::get_object(), JsonObject::read(), requirements, washing_requirements::time, to_wash, and washing_requirements::water.
do_turn()
void wash_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1688 of file activity_actor_definitions.h.
 {};
finish()
void wash_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 7611 of file activity_actor.cpp.
 {
     const auto is_liquid_crafting_component = []( const item & it ) {
         return is_crafting_component( it ) && ( !it.count_by_charges() || it.made_of( phase_id::LIQUID ) );
     };
     const inventory &crafting_inv = p.crafting_inventory();
     if( !crafting_inv.has_charges( itype_water, requirements.water, is_liquid_crafting_component ) &&
         !crafting_inv.has_charges( itype_water_clean, requirements.water, is_liquid_crafting_component ) ) {
         p.add_msg_if_player( _( "You need %1$i charges of water or clean water to wash these items." ),
                              requirements.water );
         act.set_to_null();
         return;
     } else if( !crafting_inv.has_charges( itype_soap, requirements.cleanser ) &&
                !crafting_inv.has_charges( itype_detergent, requirements.cleanser ) &&
                !crafting_inv.has_charges( itype_liquid_soap, requirements.cleanser,
                                           is_liquid_crafting_component ) ) {
         p.add_msg_if_player( _( "You need %1$i charges of cleansing agent to wash these items." ),
                              requirements.cleanser );
         act.set_to_null();
         return;
     }
     for( drop_location &ait : to_wash ) {
         item_location filthy_item = ait.first;
         if( filthy_item->count_by_charges() ) {
             item copy( *filthy_item );
             copy.charges = ait.second;
             copy.unset_flag( flag_FILTHY );
             filthy_item->charges -= ait.second;
             if( filthy_item->charges <= 0 ) {
                 filthy_item.remove_item();
             }
             p.i_add_or_drop( copy );
         } else {
             filthy_item->unset_flag( flag_FILTHY );
             p.on_worn_item_washed( *filthy_item );
         }
     }
     std::vector<item_comp> comps;
     comps.emplace_back( itype_water, requirements.water );
     comps.emplace_back( itype_water_clean, requirements.water );
     p.consume_items( comps, 1, is_liquid_crafting_component );
     std::vector<item_comp> comps1;
     comps1.emplace_back( itype_soap, requirements.cleanser );
     comps1.emplace_back( itype_detergent, requirements.cleanser );
     comps1.emplace_back( itype_liquid_soap, requirements.cleanser );
     p.consume_items( comps1 );
     p.add_msg_if_player( m_good, _( "You washed your items." ) );
     // Make sure newly washed components show up as available if player attempts to craft immediately
     p.invalidate_crafting_inventory();
     act.set_to_null();
 }
References _, act, Character::add_msg_if_player(), item::charges, washing_requirements::cleanser, Character::consume_items(), item::count_by_charges(), Character::crafting_inventory(), flag_FILTHY, read_only_visitable::has_charges(), Character::i_add_or_drop(), Character::invalidate_crafting_inventory(), is_crafting_component(), itype_detergent, itype_liquid_soap, itype_soap, itype_water, itype_water_clean, LIQUID, m_good, Character::on_worn_item_washed(), item_location::remove_item(), requirements, to_wash, item::unset_flag(), and washing_requirements::water.
get_type()
activity_id wash_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1683 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_WASH" );
         }
References activity_id.
serialize()
void wash_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 7669 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "to_wash", to_wash );
     jsout.member( "time", requirements.time );
     jsout.member( "water", requirements.water );
     jsout.member( "cleanser", requirements.cleanser );
     jsout.end_object();
 }
References washing_requirements::cleanser, JsonOut::end_object(), JsonOut::member(), requirements, JsonOut::start_object(), washing_requirements::time, to_wash, and washing_requirements::water.
start()
void wash_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 7605 of file activity_actor.cpp.
 {
     act.moves_total = requirements.time;
     act.moves_left = requirements.time;
 }
References act, requirements, and washing_requirements::time.
Member Data Documentation
requirements
washing_requirements wash_activity_actor::requirements private
Definition at line 1700 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), serialize(), and start().
to_wash
drop_locations wash_activity_actor::to_wash private
Definition at line 1699 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp