Cataclysm DDA: jmapgen_remove_npcs Class Reference
jmapgen_remove_npcs Class Reference
Public Member Functions
jmapgen_remove_npcs (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
std::string npc_class
std::string unique_id
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Definition at line 3450 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_remove_npcs()
jmapgen_remove_npcs::jmapgen_remove_npcs (const JsonObject & jsi, const std::string_view) inline
Definition at line 3455 of file mapgen.cpp.
{
             optional( jsi, false, "class", npc_class );
             optional( jsi, false, "unique_id", unique_id );
         }
References mapgen_defer::jsi, optional(), and unique_id.
Member Function Documentation
apply()
void jmapgen_remove_npcs::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 3459 of file mapgen.cpp.
{
             tripoint_abs_omt omt_pos = project_to<coords::omt>( dat.m.get_abs_sub() );
             omt_pos.z() += z.get();
             for( auto const &npc : overmap_buffer.get_npcs_near_omt(
                      omt_pos, 0 ) ) {
                 if( !npc->is_dead() &&
                     ( npc_class.empty() || npc->idz == string_id<npc_template>( npc_class ) ) &&
                     ( unique_id.empty() || unique_id == npc->get_unique_id() ) ) {
                     overmap_buffer.remove_npc( npc->getID() );
                     if( !unique_id.empty() ) {
                         g->unique_npc_despawn( unique_id );
                     }
                     if( get_map().inbounds( npc->get_location() ) ) {
                         g->remove_npc( npc->getID() );
                         get_avatar().get_mon_visible().remove_npc( npc.get() );
                     }
                 }
             }
         }
References g, jmapgen_int::get(), map::get_abs_sub(), get_avatar(), Creature::get_location(), get_map(), avatar::get_mon_visible(), overmapbuffer::get_npcs_near_omt(), npc::get_unique_id(), Character::getID(), npc::idz, npc::is_dead(), mapgendata::m, overmap_buffer, overmapbuffer::remove_npc(), monster_visible_info::remove_npc(), unique_id, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Member Data Documentation
npc_class
std::string jmapgen_remove_npcs::npc_class
Definition at line 3453 of file mapgen.cpp.
unique_id
std::string jmapgen_remove_npcs::unique_id
Definition at line 3454 of file mapgen.cpp.
Referenced by apply(), and jmapgen_remove_npcs().
The documentation for this class was generated from the following file:
src/mapgen.cpp