Cataclysm DDA: ofstream_wrapper Class Reference
ofstream_wrapper Class Reference
Wrapper around std::ofstream that handles error checking and throws on errors.
#include <ofstream_wrapper.h>
Public Member Functions
ofstream_wrapper (const fs::path &path, std::ios::openmode mode)
~ofstream_wrapper ()
std::ostream & stream ()
operator std::ostream & ()
void close ()
Private Member Functions
void open (std::ios::openmode mode)
Private Attributes
std::ofstream file_stream
fs::path path
fs::path temp_path
Detailed Description
Wrapper around std::ofstream that handles error checking and throws on errors.
Use like a normal ofstream: the stream is opened in the constructor and closed via close. Both functions check for success and throw std::exception upon any error (e.g. when opening failed or when the stream is in an error state when being closed). Use stream (or the implicit conversion) to access the output stream and to write to it.
Note
: The stream is closed in the destructor, but no exception is throw from it. To ensure all errors get reported correctly, you should always call close explicitly.
: This uses exclusive I/O.
Definition at line 22 of file ofstream_wrapper.h.
Constructor & Destructor Documentation
ofstream_wrapper()
ofstream_wrapper::ofstream_wrapper (const fs::path & path, std::ios::openmode mode)
Definition at line 348 of file cata_utility.cpp.
     : path( path )
 {
     open( mode );
 }
References open().
~ofstream_wrapper()
ofstream_wrapper::~ofstream_wrapper ()
Definition at line 355 of file cata_utility.cpp.
 {
     try {
         close();
     } catch( ... ) {
         // ignored in destructor
     }
 }
References close().
Member Function Documentation
close()
void ofstream_wrapper::close ()
Definition at line 145 of file mapsharing.cpp.
 {
     if( !file_stream.is_open() ) {
         return;
     }
     file_stream.flush();
     bool failed = file_stream.fail();
     file_stream.close();
     if( failed ) {
         // Remove the incomplete or otherwise faulty file (if possible).
         // Failures from it are ignored as we can't really do anything about them.
         std::error_code ec;
         fs::remove( temp_path, ec );
         throw std::runtime_error( "writing to file failed" );
     }
     std::error_code ec2;
     fs::rename( temp_path, path, ec2 );
     if( ec2 ) {
         // Leave the temp path, so the user can move it if possible.
         throw std::runtime_error( "moving temporary file \"" + temp_path.u8string() + "\" failed" );
     }
 #if defined(EMSCRIPTEN)
     EM_ASM( window.setFsNeedsSync(); );
 #endif
 }
References failed, file_stream, path, and temp_path.
Referenced by write_to_file(), and ~ofstream_wrapper().
open()
void ofstream_wrapper::open (std::ios::openmode mode) private
Definition at line 110 of file mapsharing.cpp.
 {
     // Create a *unique* temporary path. No other running program should
     // use this path. If the file exists, it must be of a *former* program
     // instance and can safely be deleted.
     temp_path = path;
     std::ostringstream suffix;
     // Some locale may insert unwanted thousands separators,
     // which may not be in utf-8 encoding, so imbue with the classic locale.
     suffix.imbue( std::locale::classic() );
 #if defined(__linux__)
     suffix << "." << getpid() << ".temp";
     temp_path += fs::u8path( suffix.str() );
 #elif defined(_WIN32)
     suffix << "." << GetCurrentProcessId() << ".temp";
     temp_path += fs::u8path( suffix.str() );
 #else
     // TODO: exclusive I/O for other systems
     temp_path += fs::u8path( ".temp" );
 #endif
     if( !is_lexically_valid( temp_path ) ) {
         throw std::runtime_error( "path has an invalid name" );
     }
     if( fs::exists( temp_path ) && !fs::is_directory( temp_path ) ) {
         std::error_code ec;
         fs::remove( temp_path, ec );
     }
     file_stream.open( temp_path, mode );
     if( !file_stream.is_open() ) {
         throw std::runtime_error( "opening file failed" );
     }
 }
References file_stream, anonymous_namespace{filesystem.cpp}::is_directory(), is_lexically_valid(), path, and temp_path.
Referenced by ofstream_wrapper().
operator std::ostream &()
ofstream_wrapper::operator std::ostream & () inline explicit
Definition at line 38 of file ofstream_wrapper.h.
{
             return file_stream;
         }
References file_stream.
stream()
std::ostream& ofstream_wrapper::stream () inline
Definition at line 35 of file ofstream_wrapper.h.
{
             return file_stream;
         }
References file_stream.
Referenced by write_to_file().
Member Data Documentation
file_stream
std::ofstream ofstream_wrapper::file_stream private
Definition at line 25 of file ofstream_wrapper.h.
Referenced by close(), open(), operator std::ostream &(), and stream().
path
fs::path ofstream_wrapper::path private
Definition at line 26 of file ofstream_wrapper.h.
Referenced by close(), and open().
temp_path
fs::path ofstream_wrapper::temp_path private
Definition at line 27 of file ofstream_wrapper.h.
Referenced by close(), and open().
The documentation for this class was generated from the following files:
src/ofstream_wrapper.h
src/cata_utility.cpp
src/mapsharing.cpp