Cataclysm DDA: job_data Class Reference
job_data Class Reference
#include <npc.h>
Public Member Functions
bool set_task_priority (const activity_id &task, int new_priority)
void clear_all_priorities ()
bool has_job () const
int get_priority_of_job (const activity_id &req_job) const
std::vector< activity_id > get_prioritised_vector () const
void serialize (JsonOut &json) const
void deserialize (const JsonValue &jv)
Public Attributes
std::unordered_map< std::string, time_point > fetch_history
Private Attributes
std::map< activity_id, int > task_priorities
Detailed Description
Definition at line 142 of file npc.h.
Member Function Documentation
clear_all_priorities()
void job_data::clear_all_priorities ()
Definition at line 177 of file npc.cpp.
 {
     for( auto &elem : task_priorities ) {
         elem.second = 0;
     }
 }
References task_priorities.
Referenced by basecamp::job_assignment_ui(), talk_function::leave(), and npc::mutiny().
deserialize()
void job_data::deserialize (const JsonValue & jv)
Definition at line 2024 of file savegame_json.cpp.
 {
     if( jv.test_object() ) {
         JsonObject jo = jv;
         jo.allow_omitted_members();
         jo.read( "task_priorities", task_priorities );
         jo.read( "fetch_history", fetch_history );
     }
 }
References JsonObject::allow_omitted_members(), JsonObject::read(), and JsonValue::test_object().
get_prioritised_vector()
std::vector< activity_id > job_data::get_prioritised_vector () const
Definition at line 202 of file npc.cpp.
 {
     std::vector<std::pair<activity_id, int>> pairs( begin( task_priorities ), end( task_priorities ) );
     std::vector<activity_id> ret;
     sort( begin( pairs ), end( pairs ), []( const std::pair<activity_id, int> &a,
     const std::pair<activity_id, int> &b ) {
         return a.second > b.second;
     } );
     ret.reserve( pairs.size() );
     for( const std::pair<activity_id, int> &elem : pairs ) {
         ret.push_back( elem.first );
     }
     return ret;
 }
References a, b, keycode::end, cata::hash64_detail::ret, and task_priorities.
Referenced by npc::find_job_to_perform(), and basecamp::job_assignment_ui().
get_priority_of_job()
int job_data::get_priority_of_job (const activity_id & req_job) const
Definition at line 192 of file npc.cpp.
 {
     auto it = task_priorities.find( req_job );
     if( it != task_priorities.end() ) {
         return it->second;
     } else {
         return 0;
     }
 }
References task_priorities.
Referenced by npc::find_job_to_perform(), and basecamp::job_assignment_ui().
has_job()
bool job_data::has_job () const
Definition at line 183 of file npc.cpp.
 {
     for( const auto &elem : task_priorities ) {
         if( elem.second > 0 ) {
             return true;
         }
     }
     return false;
 }
References task_priorities.
Referenced by npc::has_job().
serialize()
void job_data::serialize (JsonOut & json) const
Definition at line 2016 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "task_priorities", task_priorities );
     json.member( "fetch_history", fetch_history );
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
set_task_priority()
bool job_data::set_task_priority (const activity_id & task, int new_priority)
Definition at line 168 of file npc.cpp.
 {
     auto it = task_priorities.find( task );
     if( it != task_priorities.end() ) {
         task_priorities[task] = new_priority;
         return true;
     }
     return false;
 }
References task_priorities.
Referenced by basecamp::job_assignment_ui().
Member Data Documentation
fetch_history
std::unordered_map<std::string, time_point> job_data::fetch_history
Definition at line 160 of file npc.h.
Referenced by npc::find_job_to_perform(), generic_multi_activity_check_requirement(), and generic_multi_activity_handler().
task_priorities
std::map<activity_id, int> job_data::task_priorities private
Initial value:
= {
            { activity_id( "ACT_MULTIPLE_BUTCHER" ), 0 },
            { activity_id( "ACT_MULTIPLE_CONSTRUCTION" ), 0 },
            { activity_id( "ACT_VEHICLE_REPAIR" ), 0 },
            { activity_id( "ACT_VEHICLE_DECONSTRUCTION" ), 0 },
            { activity_id( "ACT_MULTIPLE_FARM" ), 0 },
            { activity_id( "ACT_MULTIPLE_CHOP_TREES" ), 0 },
            { activity_id( "ACT_MULTIPLE_CHOP_PLANKS" ), 0 },
            { activity_id( "ACT_MULTIPLE_FISH" ), 0 },
            { activity_id( "ACT_MOVE_LOOT" ), 0 },
            { activity_id( "ACT_TIDY_UP" ), 0 },
            { activity_id( "ACT_MULTIPLE_DIS" ), 0}
        }
Definition at line 145 of file npc.h.
Referenced by clear_all_priorities(), get_prioritised_vector(), get_priority_of_job(), has_job(), and set_task_priority().
The documentation for this class was generated from the following files:
src/npc.h
src/npc.cpp
src/savegame_json.cpp