Cataclysm DDA: mapgendata Class Reference
mapgendata Class Reference
Contains various information regarding the individual mapgen instance (generating a specific part of the map), used by the various mapgen functions to do their thing.
#include <mapgendata.h>
Classes
struct dummy_settings_t
Public Member Functions
mapgendata (map &, dummy_settings_t)
mapgendata (const tripoint_abs_omt &over, map &m, float density, const time_point &when, ::mission *miss)
mapgendata (const mapgendata &other, const oter_id &other_id)
Creates a copy of this mapgen data, but stores a different terrain_type.
mapgendata (const mapgendata &other, const mapgen_arguments &)
Creates a copy of this mapgendata, but stores new parameter values.
mapgendata (const mapgendata &other, const mapgen_arguments &, const enum_bitset< jmapgen_flags > &)
Creates a copy of this mapgendata, but stores new parameter values and flags.
const oter_id & terrain_type () const
float monster_density () const
const time_point & when () const
::mission * mission () const
int zlevel () const
std::vector< oter_id > get_predecessors () const
void set_dir (int dir_in, int val)
void fill (int val)
int & dir (int dir_in)
const oter_id & north () const
const oter_id & east () const
const oter_id & south () const
const oter_id & west () const
const oter_id & neast () const
const oter_id & seast () const
const oter_id & swest () const
const oter_id & nwest () const
const oter_id & above () const
const oter_id & below () const
const oter_id & neighbor_at (om_direction::type dir) const
const oter_id & neighbor_at (direction) const
void fill_groundcover () const
void square_groundcover (const point &p1, const point &p2) const
ter_id groundcover () const
bool is_groundcover (const ter_id &iid) const
bool has_flag (jmapgen_flags) const
bool has_join (cube_direction, const std::string &join_id) const
bool has_predecessor () const
const oter_id & last_predecessor () const
void pop_last_predecessor ()
template<typename Result >
Result get_arg (const std::string &name) const
template<typename Result >
Result get_arg_or (const std::string &name, const Result &fallback) const
Public Attributes
std::array< oter_id, 8 > t_nesw
int n_fac = 0
int e_fac = 0
int s_fac = 0
int w_fac = 0
int ne_fac = 0
int se_fac = 0
int sw_fac = 0
int nw_fac = 0
oter_id t_above
oter_id t_below
std::unordered_map< cube_direction, std::string > joins
const regional_settings & region
map & m
weighted_int_list< ter_id > default_groundcover
std::vector< mapgen_phase > skip
Static Public Attributes
static constexpr dummy_settings_t dummy_settings = {}
Private Attributes
oter_id terrain_type_
float density_
time_point when_
::mission * mission_
int zlevel_
mapgen_arguments mapgen_args_
enum_bitset< jmapgen_flags > mapgen_flags_
std::vector< oter_id > predecessors_
Detailed Description
Contains various information regarding the individual mapgen instance (generating a specific part of the map), used by the various mapgen functions to do their thing.
Contains for example:
the map to generate the map onto,
the overmap terrain of the area to generate and its surroundings,
regional settings to use.
An instance of this class is passed through most of the mapgen code. If any of these functions need more information, add them here.
Definition at line 101 of file mapgendata.h.
Constructor & Destructor Documentation
mapgendata() [1/5]
mapgendata::mapgendata (map & mp, dummy_settings_t)
Definition at line 39 of file mapgendata.cpp.
     : density_( 0 )
     , when_( calendar::turn )
     , mission_( nullptr )
     , zlevel_( 0 )
     , region( dummy_regional_settings )
     , m( mp )
     , default_groundcover( region.default_groundcover )
 {
     oter_id any = oter_id( "field" );
     t_above = t_below = terrain_type_ = any;
     std::fill( std::begin( t_nesw ), std::end( t_nesw ), any );
 }
References any, keycode::end, oter_id, t_above, t_below, t_nesw, and terrain_type_.
mapgendata() [2/5]
mapgendata::mapgendata (const tripoint_abs_omt & over, map & m, float density, const time_point & when, ::mission * miss)
Definition at line 53 of file mapgendata.cpp.
     : terrain_type_( overmap_buffer.ter( over ) )
     , density_( density )
     , when_( when )
     , mission_( miss )
     , zlevel_( over.z() )
     , predecessors_( overmap_buffer.predecessors( over ) )
     , t_above( overmap_buffer.ter( over + tripoint_above ) )
     , t_below( overmap_buffer.ter( over + tripoint_below ) )
     , region( overmap_buffer.get_settings( over ) )
     , m( mp )
     , default_groundcover( region.default_groundcover )
 {
     bool ignore_rotation = terrain_type_->has_flag( oter_flags::ignore_rotation_for_adjacency );
     int rotation = ignore_rotation ? 0 : terrain_type_->get_rotation();
     auto set_neighbour = [&]( int index, direction dir ) {
         t_nesw[index] =
             overmap_buffer.ter( over + displace( dir ).rotate( rotation ) );
     };
     set_neighbour( 0, direction::NORTH );
     set_neighbour( 1, direction::EAST );
     set_neighbour( 2, direction::SOUTH );
     set_neighbour( 3, direction::WEST );
     set_neighbour( 4, direction::NORTHEAST );
     set_neighbour( 5, direction::SOUTHEAST );
     set_neighbour( 6, direction::SOUTHWEST );
     set_neighbour( 7, direction::NORTHWEST );
     if( std::optional<mapgen_arguments> *maybe_args = overmap_buffer.mapgen_args( over ) ) {
         if( *maybe_args && !overmap_buffer.externally_set_args ) {
             mapgen_args_ = **maybe_args;
         } else {
             // We are the first omt from this overmap_special to be generated,
             // so now is the time to generate the arguments
             if( std::optional<overmap_special_id> s = overmap_buffer.overmap_special_at( over ) ) {
                 const overmap_special &special = **s;
                 mapgen_arguments internally_set_args = special.get_args( *this );
                 if( overmap_buffer.externally_set_args ) {
                     maybe_args->value().map.merge( internally_set_args.map );
                     overmap_buffer.externally_set_args = false;
                 } else {
                     *maybe_args = internally_set_args;
                 }
                 mapgen_args_ = **maybe_args;
             } else {
                 debugmsg( "mapgen params expected but no overmap special found for terrain %s",
                           terrain_type_.id().str() );
             }
         }
     }
     for( cube_direction dir : all_enum_values<cube_direction>() ) {
         if( std::string *join = overmap_buffer.join_used_at( { over, dir } ) ) {
             cube_direction rotated_dir = dir - rotation;
             joins.emplace( rotated_dir, *join );
         }
     }
 }
References debugmsg, dir(), displace(), EAST, overmapbuffer::externally_set_args, overmap_special::get_args(), oter_t::get_rotation(), oter_t::has_flag(), int_id< T >::id(), ignore_rotation_for_adjacency, overmapbuffer::join_used_at(), joins, mapgen_arguments::map, overmapbuffer::mapgen_args(), mapgen_args_, NORTH, NORTHEAST, NORTHWEST, overmap_buffer, overmapbuffer::overmap_special_at(), tripoint::rotate(), SOUTH, SOUTHEAST, SOUTHWEST, string_id< T >::str(), t_nesw, overmapbuffer::ter(), terrain_type_, and WEST.
mapgendata() [3/5]
mapgendata::mapgendata (const mapgendata & other, const oter_id & other_id)
Creates a copy of this mapgen data, but stores a different terrain_type.
Useful when you want to create a base map (e.g. forest/field/river), that gets refined later:
void generate_foo(mapgendata &dat) {
    mapgendata base_dat( dat, oter_id( "forest" ) );
    generate( base_dat );
    ... // refine map some more.
}
Definition at line 111 of file mapgendata.cpp.
                                                                          : mapgendata( other )
 {
     const int old_rotation = terrain_type_->has_flag(
                                  oter_flags::ignore_rotation_for_adjacency ) ? 0 : terrain_type_->get_rotation();
     const int new_rotation = other_id->has_flag( oter_flags::ignore_rotation_for_adjacency ) ? 0 :
                              other_id->get_rotation();
     terrain_type_ = other_id;
     const int rotation_delta = new_rotation - old_rotation;
     if( rotation_delta == 0 ) {
         return;
     }
     const int shift = ( rotation_delta + 4 ) % 4;
     // The array of neighbors is actually logically more like two independent arrays smashed
     // together, so we need to first rotate the cardinal directions section, and then the
     // ordinal directions section. They both rotate the same direction.
     std::rotate( t_nesw.begin(), t_nesw.begin() + shift, t_nesw.begin() + 4 );
     std::rotate( t_nesw.begin() + 4, t_nesw.begin() + 4 + shift, t_nesw.end() );
 }
References oter_t::get_rotation(), oter_t::has_flag(), ignore_rotation_for_adjacency, other, rotate(), shift, t_nesw, and terrain_type_.
mapgendata() [4/5]
mapgendata::mapgendata (const mapgendata & other, const mapgen_arguments & mapgen_args)
Creates a copy of this mapgendata, but stores new parameter values.
Definition at line 135 of file mapgendata.cpp.
                                                               :
     mapgendata( other )
 {
     mapgen_args_.merge( mapgen_args );
 }
References mapgen_args_, mapgen_arguments::merge(), and other.
mapgendata() [5/5]
mapgendata::mapgendata (const mapgendata & other, const mapgen_arguments & mapgen_args, const enum_bitset< jmapgen_flags > & flags)
Creates a copy of this mapgendata, but stores new parameter values and flags.
Definition at line 142 of file mapgendata.cpp.
                                                                   :
     mapgendata( other, mapgen_args )
 {
     mapgen_flags_ = flags;
 }
References mapgen_flags_, and other.
Member Function Documentation
above()
const oter_id& mapgendata::above () const inline
Definition at line 219 of file mapgendata.h.
{
             return t_above;
         }
Referenced by map::draw_lab(), map::draw_slimepit(), and neighbor_at().
below()
const oter_id& mapgendata::below () const inline
Definition at line 222 of file mapgendata.h.
{
             return t_below;
         }
Referenced by neighbor_at().
dir()
int & mapgendata::dir (int dir_in)
Definition at line 195 of file mapgendata.cpp.
 {
     switch( dir_in ) {
         case 0:
             return n_fac;
         case 1:
             return e_fac;
         case 2:
             return s_fac;
         case 3:
             return w_fac;
         case 4:
             return ne_fac;
         case 5:
             return se_fac;
         case 6:
             return sw_fac;
         case 7:
             return nw_fac;
         default:
             debugmsg( "Invalid direction for mapgendata::set_dir.  dir_in = %d", dir_in );
             //return something just so the compiler doesn't freak out. Not really correct, though.
             return n_fac;
     }
 }
References debugmsg, e_fac, n_fac, ne_fac, nw_fac, s_fac, se_fac, sw_fac, and w_fac.
Referenced by has_join(), mapgen_forest(), mapgen_rock_partial(), mapgendata(), and neighbor_at().
east()
const oter_id& mapgendata::east () const inline
Definition at line 198 of file mapgendata.h.
{
             return t_nesw[1];
         }
Referenced by map::draw_lab(), mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), and neighbor_at().
fill()
void mapgendata::fill (int val)
Definition at line 183 of file mapgendata.cpp.
 {
     n_fac = val;
     e_fac = val;
     s_fac = val;
     w_fac = val;
     ne_fac = val;
     se_fac = val;
     sw_fac = val;
     nw_fac = val;
 }
References e_fac, n_fac, ne_fac, nw_fac, s_fac, se_fac, sw_fac, and w_fac.
fill_groundcover()
void mapgendata::fill_groundcover () const
Definition at line 226 of file mapgendata.cpp.
 {
     m.draw_fill_background( default_groundcover );
 }
References default_groundcover, map::draw_fill_background(), and m.
Referenced by mapgen_forest(), mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), and mapgen_subway().
get_arg()
template<typename Result > Result mapgendata::get_arg (const std::string & name) const inline
Definition at line 241 of file mapgendata.h.
{
             auto it = mapgen_args_.map.find( name );
             if( it == mapgen_args_.map.end() ) {
                 debugmsg( "No such parameter \"%s\"", name );
                 return Result();
             }
             return mapgendata_detail::extract_variant_value<Result>( it->second );
         }
References debugmsg, mapgen_arguments::map, and om_direction::name().
Referenced by jmapgen_constrained< Value >::apply(), and mapgen_value< Id >::param_source::get().
get_arg_or()
template<typename Result > Result mapgendata::get_arg_or (const std::string & name, const Result & fallback) const inline
Definition at line 251 of file mapgendata.h.
{
             auto it = mapgen_args_.map.find( name );
             if( it == mapgen_args_.map.end() ) {
                 return fallback;
             }
             return mapgendata_detail::extract_variant_value<Result>( it->second );
         }
References mapgen_arguments::map, and om_direction::name().
Referenced by mapgen_value< Id >::param_source::get(), and mapgen_parameters::get_args().
get_predecessors()
std::vector<oter_id> mapgendata::get_predecessors () const inline
Definition at line 188 of file mapgendata.h.
{
             return predecessors_;
         }
Referenced by jmapgen_nested::predecessor_oter_check::test().
groundcover()
ter_id mapgendata::groundcover () const
Definition at line 247 of file mapgendata.cpp.
 {
     const ter_id *tid = default_groundcover.pick();
     return tid != nullptr ? *tid : ter_str_id::NULL_ID().id();
 }
References default_groundcover, string_id< T >::id(), and string_id< ter_t >::NULL_ID().
Referenced by mapgen_ravine_edge().
has_flag()
bool mapgendata::has_flag (jmapgen_flags f) const
Definition at line 242 of file mapgendata.cpp.
 {
     return mapgen_flags_.test( f );
 }
References mapgen_flags_, and enum_bitset< E >::test().
Referenced by jmapgen_terrain::apply(), jmapgen_setmap::apply(), rotation_guard::rotation_guard(), and rotation_guard::~rotation_guard().
has_join()
bool mapgendata::has_join (cube_direction dir, const std::string & join_id) const
Definition at line 305 of file mapgendata.cpp.
 {
     auto it = joins.find( dir );
     return it != joins.end() && it->second == join_id;
 }
References dir(), and joins.
Referenced by jmapgen_nested::neighbor_join_check::test().
has_predecessor()
bool mapgendata::has_predecessor () const
Definition at line 311 of file mapgendata.cpp.
 {
     return !predecessors_.empty();
 }
References predecessors_.
Referenced by mapgen_function_json::generate().
is_groundcover()
bool mapgendata::is_groundcover (const ter_id & iid) const
Definition at line 231 of file mapgendata.cpp.
 {
     for( const auto &pr : default_groundcover ) {
         if( pr.obj == iid ) {
             return true;
         }
     }
     return false;
 }
References default_groundcover.
last_predecessor()
const oter_id & mapgendata::last_predecessor () const
Definition at line 316 of file mapgendata.cpp.
 {
     if( predecessors_.empty() ) {
         debugmsg( "Tried to get predecessor when none available in mapgendata" );
         static const oter_id null( oter_str_id::NULL_ID() );
         return null;
     }
     return predecessors_.back();
 }
References debugmsg, string_id< oter_t >::NULL_ID(), and predecessors_.
Referenced by mapgen_function_json::generate().
mission()
::mission* mapgendata::mission () const inline
Definition at line 181 of file mapgendata.h.
{
             return mission_;
         }
Referenced by jmapgen_npc::apply(), jmapgen_monster::apply(), and jmapgen_computer::apply().
monster_density()
float mapgendata::monster_density () const inline
Definition at line 175 of file mapgendata.h.
{
             return density_;
         }
Referenced by jmapgen_monster_group::apply().
neast()
const oter_id& mapgendata::neast () const inline
Definition at line 207 of file mapgendata.h.
{
             return t_nesw[4];
         }
Referenced by mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), and neighbor_at().
neighbor_at() [1/2]
const oter_id & mapgendata::neighbor_at (direction dir) const
Definition at line 273 of file mapgendata.cpp.
 {
     // TODO: De-uglify, implement proper conversion somewhere
     switch( dir ) {
         case direction::NORTH:
             return north();
         case direction::EAST:
             return east();
         case direction::SOUTH:
             return south();
         case direction::WEST:
             return west();
         case direction::NORTHEAST:
             return neast();
         case direction::SOUTHEAST:
             return seast();
         case direction::SOUTHWEST:
             return swest();
         case direction::NORTHWEST:
             return nwest();
         case direction::ABOVECENTER:
             return above();
         case direction::BELOWCENTER:
             return below();
         default:
             break;
     }
     debugmsg( "Neighbor not supported for direction %d", io::enum_to_string( dir ) );
     return north();
 }
References above(), ABOVECENTER, below(), BELOWCENTER, debugmsg, dir(), EAST, east(), io::enum_to_string(), neast(), NORTH, north(), NORTHEAST, NORTHWEST, nwest(), seast(), SOUTH, south(), SOUTHEAST, SOUTHWEST, swest(), WEST, and west().
neighbor_at() [2/2]
const oter_id & mapgendata::neighbor_at (om_direction::type dir) const
Definition at line 253 of file mapgendata.cpp.
 {
     // TODO: De-uglify, implement proper conversion somewhere
     switch( dir ) {
         case om_direction::type::north:
             return north();
         case om_direction::type::east:
             return east();
         case om_direction::type::south:
             return south();
         case om_direction::type::west:
             return west();
         default:
             break;
     }
     debugmsg( "Tried to get neighbor from invalid direction %d", dir );
     return north();
 }
References debugmsg, dir(), east(), om_direction::east, north(), om_direction::north, south(), om_direction::south, west(), and om_direction::west.
Referenced by jmapgen_nested::neighbor_oter_check::test(), jmapgen_nested::neighbor_flag_check::test(), and jmapgen_nested::neighbor_flag_any_check::test().
north()
const oter_id& mapgendata::north () const inline
Definition at line 195 of file mapgendata.h.
{
             return t_nesw[0];
         }
Referenced by map::draw_lab(), mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), and neighbor_at().
nwest()
const oter_id& mapgendata::nwest () const inline
Definition at line 216 of file mapgendata.h.
{
             return t_nesw[7];
         }
Referenced by mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), and neighbor_at().
pop_last_predecessor()
void mapgendata::pop_last_predecessor ()
Definition at line 326 of file mapgendata.cpp.
 {
     if( predecessors_.empty() ) {
         debugmsg( "Tried to pop predecessor when none available in mapgendata" );
     }
     predecessors_.pop_back();
 }
References debugmsg, and predecessors_.
Referenced by mapgen_function_json::generate().
seast()
const oter_id& mapgendata::seast () const inline
Definition at line 210 of file mapgendata.h.
{
             return t_nesw[5];
         }
Referenced by mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), and neighbor_at().
set_dir()
void mapgendata::set_dir (int dir_in, int val)
Definition at line 150 of file mapgendata.cpp.
 {
     switch( dir_in ) {
         case 0:
             n_fac = val;
             break;
         case 1:
             e_fac = val;
             break;
         case 2:
             s_fac = val;
             break;
         case 3:
             w_fac = val;
             break;
         case 4:
             ne_fac = val;
             break;
         case 5:
             se_fac = val;
             break;
         case 6:
             sw_fac = val;
             break;
         case 7:
             nw_fac = val;
             break;
         default:
             debugmsg( "Invalid direction for mapgendata::set_dir.  dir_in = %d", dir_in );
             break;
     }
 }
References debugmsg, e_fac, n_fac, ne_fac, nw_fac, s_fac, se_fac, sw_fac, and w_fac.
south()
const oter_id& mapgendata::south () const inline
Definition at line 201 of file mapgendata.h.
{
             return t_nesw[2];
         }
Referenced by map::draw_lab(), mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), and neighbor_at().
square_groundcover()
void mapgendata::square_groundcover (const point & p1, const point & p2) const
Definition at line 221 of file mapgendata.cpp.
 {
     m.draw_square_ter( default_groundcover, p1, p2 );
 }
References default_groundcover, map::draw_square_ter(), and m.
swest()
const oter_id& mapgendata::swest () const inline
Definition at line 213 of file mapgendata.h.
{
             return t_nesw[6];
         }
Referenced by mapgen_lake_shore(), mapgen_ocean_shore(), and neighbor_at().
terrain_type()
const oter_id& mapgendata::terrain_type () const inline
Definition at line 172 of file mapgendata.h.
{
             return terrain_type_;
         }
Referenced by jmapgen_terrain::apply(), map::draw_lab(), map::draw_map(), map::draw_slimepit(), farm_action(), mapgen_function_json::generate(), mapgen_forest(), mapgen_river_curved(), mapgen_river_curved_not(), mapgen_river_straight(), and mapgen_subway().
west()
const oter_id& mapgendata::west () const inline
Definition at line 204 of file mapgendata.h.
{
             return t_nesw[3];
         }
Referenced by map::draw_lab(), mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), and neighbor_at().
when()
const time_point& mapgendata::when () const inline
Definition at line 178 of file mapgendata.h.
{
             return when_;
         }
Referenced by mapgen_forest().
zlevel()
int mapgendata::zlevel () const inline
Definition at line 184 of file mapgendata.h.
{
             // TODO: should be able to determine this from the map itself
             return zlevel_;
         }
Referenced by jmapgen_graffiti::apply(), jmapgen_vending_machine::apply(), jmapgen_toilet::apply(), jmapgen_gaspump::apply(), jmapgen_liquid_item::apply(), jmapgen_corpse::apply(), jmapgen_item_group::apply(), jmapgen_loot::apply(), jmapgen_monster_group::apply(), jmapgen_vehicle::apply(), jmapgen_spawn_item::apply(), jmapgen_trap::apply(), jmapgen_ter_furn_transform::apply(), jmapgen_make_rubble::apply(), jmapgen_computer::apply(), jmapgen_zone::apply(), jmapgen_variable::apply(), jmapgen_remove_vehicles::apply(), jmapgen_remove_all::apply(), jmapgen_furniture::apply(), jmapgen_terrain::apply(), jmapgen_sealed_item::apply(), jmapgen_setmap::apply(), map::draw_lab(), map::draw_slimepit(), jmapgen_setmap::has_vehicle_collision(), jmapgen_alternatively< PieceType >::has_vehicle_collision(), jmapgen_sign::has_vehicle_collision(), jmapgen_vending_machine::has_vehicle_collision(), jmapgen_toilet::has_vehicle_collision(), jmapgen_gaspump::has_vehicle_collision(), jmapgen_vehicle::has_vehicle_collision(), jmapgen_trap::has_vehicle_collision(), jmapgen_furniture::has_vehicle_collision(), jmapgen_terrain::has_vehicle_collision(), jmapgen_computer::has_vehicle_collision(), jmapgen_sealed_item::has_vehicle_collision(), map_extra::is_valid_for(), mapgen_forest(), mapgen_ravine_edge(), mapgen_river_curved(), mapgen_river_straight(), and jmapgen_nested::correct_z_level_check::test().
Member Data Documentation
default_groundcover
weighted_int_list<ter_id> mapgendata::default_groundcover
Definition at line 134 of file mapgendata.h.
Referenced by fill_groundcover(), groundcover(), is_groundcover(), and square_groundcover().
density_
float mapgendata::density_ private
Definition at line 105 of file mapgendata.h.
dummy_settings
constexpr dummy_settings_t mapgendata::dummy_settings = {} static constexpr
Definition at line 137 of file mapgendata.h.
Referenced by apply_construction_marker(), and get_changed_ids_from_update().
e_fac
int mapgendata::e_fac = 0
Definition at line 117 of file mapgendata.h.
Referenced by dir(), map::draw_slimepit(), fill(), mapgen_forest(), mapgen_rock_partial(), and set_dir().
joins
std::unordered_map<cube_direction, std::string> mapgendata::joins
Definition at line 128 of file mapgendata.h.
Referenced by has_join(), and mapgendata().
m
map& mapgendata::m
Definition at line 132 of file mapgendata.h.
Referenced by jmapgen_remove_npcs::apply(), jmapgen_faction::apply(), jmapgen_field::apply(), jmapgen_npc::apply(), jmapgen_sign::apply(), jmapgen_graffiti::apply(), jmapgen_vending_machine::apply(), jmapgen_toilet::apply(), jmapgen_gaspump::apply(), jmapgen_liquid_item::apply(), jmapgen_corpse::apply(), jmapgen_item_group::apply(), jmapgen_loot::apply(), jmapgen_monster_group::apply(), jmapgen_monster::apply(), jmapgen_vehicle::apply(), jmapgen_spawn_item::apply(), jmapgen_trap::apply(), jmapgen_ter_furn_transform::apply(), jmapgen_make_rubble::apply(), jmapgen_computer::apply(), jmapgen_zone::apply(), jmapgen_variable::apply(), jmapgen_remove_vehicles::apply(), jmapgen_remove_all::apply(), jmapgen_furniture::apply(), jmapgen_terrain::apply(), jmapgen_sealed_item::apply(), jmapgen_setmap::apply(), fill_groundcover(), mapgen_function_json::generate(), jmapgen_setmap::has_vehicle_collision(), jmapgen_alternatively< PieceType >::has_vehicle_collision(), jmapgen_sign::has_vehicle_collision(), jmapgen_vending_machine::has_vehicle_collision(), jmapgen_toilet::has_vehicle_collision(), jmapgen_gaspump::has_vehicle_collision(), jmapgen_vehicle::has_vehicle_collision(), jmapgen_trap::has_vehicle_collision(), jmapgen_furniture::has_vehicle_collision(), jmapgen_terrain::has_vehicle_collision(), jmapgen_computer::has_vehicle_collision(), jmapgen_sealed_item::has_vehicle_collision(), mapgen_forest(), mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), mapgen_river_center(), mapgen_river_curved(), mapgen_river_curved_not(), mapgen_river_straight(), mapgen_rock_partial(), mapgen_subway(), resolve_regional_terrain_and_furniture(), rotation_guard::rotation_guard(), square_groundcover(), and rotation_guard::~rotation_guard().
mapgen_args_
mapgen_arguments mapgendata::mapgen_args_ private
Definition at line 109 of file mapgendata.h.
Referenced by mapgendata().
mapgen_flags_
enum_bitset<jmapgen_flags> mapgendata::mapgen_flags_ private
Definition at line 110 of file mapgendata.h.
Referenced by has_flag(), and mapgendata().
mission_
::mission* mapgendata::mission_ private
Definition at line 107 of file mapgendata.h.
n_fac
int mapgendata::n_fac = 0
Definition at line 116 of file mapgendata.h.
Referenced by dir(), map::draw_slimepit(), fill(), mapgen_forest(), mapgen_rock_partial(), and set_dir().
ne_fac
int mapgendata::ne_fac = 0
Definition at line 120 of file mapgendata.h.
Referenced by dir(), fill(), and set_dir().
nw_fac
int mapgendata::nw_fac = 0
Definition at line 123 of file mapgendata.h.
Referenced by dir(), fill(), and set_dir().
predecessors_
std::vector<oter_id> mapgendata::predecessors_ private
Definition at line 111 of file mapgendata.h.
Referenced by has_predecessor(), last_predecessor(), and pop_last_predecessor().
region
const regional_settings& mapgendata::region
Definition at line 130 of file mapgendata.h.
Referenced by map_extra::is_valid_for(), mapgen_forest(), mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), and resolve_regional_terrain_and_furniture().
s_fac
int mapgendata::s_fac = 0
Definition at line 118 of file mapgendata.h.
Referenced by dir(), map::draw_slimepit(), fill(), mapgen_forest(), mapgen_rock_partial(), and set_dir().
se_fac
int mapgendata::se_fac = 0
Definition at line 121 of file mapgendata.h.
Referenced by dir(), fill(), and set_dir().
skip
std::vector<mapgen_phase> mapgendata::skip
Definition at line 144 of file mapgendata.h.
Referenced by apply_construction_marker(), apply_mapgen_in_phases(), and get_changed_ids_from_update().
sw_fac
int mapgendata::sw_fac = 0
Definition at line 122 of file mapgendata.h.
Referenced by dir(), fill(), and set_dir().
t_above
oter_id mapgendata::t_above
Definition at line 125 of file mapgendata.h.
Referenced by mapgendata().
t_below
oter_id mapgendata::t_below
Definition at line 126 of file mapgendata.h.
Referenced by mapgendata().
t_nesw
std::array<oter_id, 8> mapgendata::t_nesw
Definition at line 114 of file mapgendata.h.
Referenced by mapgen_forest(), mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_rock_partial(), mapgen_subway(), and mapgendata().
terrain_type_
oter_id mapgendata::terrain_type_ private
Definition at line 104 of file mapgendata.h.
Referenced by mapgendata().
w_fac
int mapgendata::w_fac = 0
Definition at line 119 of file mapgendata.h.
Referenced by dir(), map::draw_slimepit(), fill(), mapgen_forest(), mapgen_rock_partial(), and set_dir().
when_
time_point mapgendata::when_ private
Definition at line 106 of file mapgendata.h.
zlevel_
int mapgendata::zlevel_ private
Definition at line 108 of file mapgendata.h.
The documentation for this class was generated from the following files:
src/mapgendata.h
src/mapgendata.cpp