Cataclysm DDA: ret_val_common Class Reference
ret_val_common Class Reference
#include <ret_val.h>
Public Member Functions
bool success () const
const std::string & str () const
const char * c_str () const
Protected Types
template<typename S >
using is_convertible_to_string = std::enable_if_t< !std::is_same_v< S, std::nullptr_t > &&std::is_convertible_v< S, std::string > >
Protected Member Functions
ret_val_common (const std::string &msg, bool succ)
Private Attributes
std::string msg
bool succ
Detailed Description
Definition at line 10 of file ret_val.h.
Member Typedef Documentation
is_convertible_to_string
template<typename S > using ret_val_common::is_convertible_to_string = std::enable_if_t < !std::is_same_v<S, std::nullptr_t> &&std::is_convertible_v<S, std::string> > protected
Definition at line 26 of file ret_val.h.
Constructor & Destructor Documentation
ret_val_common()
ret_val_common::ret_val_common (const std::string & msg, bool succ) inline protected
Definition at line 30 of file ret_val.h.
             : msg( msg ), succ( succ )
         {}
Member Function Documentation
c_str()
const char* ret_val_common::c_str () const inline
Definition at line 21 of file ret_val.h.
{
             return msg.c_str();
         }
References msg.
Referenced by advanced_inventory::action_move_item(), game::inventory_item_menu(), Character::on_try_dodge(), and pickup_selector::wield().
str()
const std::string& ret_val_common::str () const inline
Definition at line 17 of file ret_val.h.
{
             return msg;
         }
References msg.
Referenced by advanced_inventory::action_move_item(), item::ammo_info(), item_contents::can_contain(), item_contents::can_contain_rigid(), veh_interact::can_remove_part(), item_contents::combine(), inventory_selector::drag_drop_item(), edit_integer(), iexamine::fertilize_plant(), item::fill_with(), item::final_info(), Item_factory::finalize_pre(), item_contents::item_contents_helper::find_pocket_for(), iexamine::fireplace(), pickup_inventory_preset::get_denial(), comestible_inventory_preset::get_denial(), bionic_install_preset::get_denial(), bionic_install_surgeon_preset::get_denial(), get_quality_from_string(), item::get_var(), getGasDiscountCardQuality(), talker_npc::give_item_to(), item_pocket::insert_item(), item_contents::insert_item(), exosuit_interact::insert_replace_activate_mod(), vehicle::install_part(), item_contents::is_compatible(), item::link_to(), link_up_actor::link_to_veh_app(), link_up_actor::link_tow_cable(), pocket_favorite_callback::move_item(), item::put_in(), query_int_impl(), set_profession(), set_scenario(), options_manager::cOpt::setValue(), holster_actor::store(), debug_menu::teleport_overmap(), try_insert(), deploy_furn_actor::use(), deploy_appliance_actor::use(), Character::use(), and wield_before_use().
success()
bool ret_val_common::success () const inline
Definition at line 13 of file ret_val.h.
{
             return succ;
         }
References succ.
Referenced by item_pocket::_can_contain(), advanced_inventory::action_move_item(), add_firestarter(), item::add_rain_to_container(), outfit::add_stash(), map::add_vehicle_to_map(), item::ammo_info(), Character::apply_damage(), apply_migration(), assemble_scenario_details(), game::butcher(), can_butcher_at(), item_contents::can_contain_rigid(), Character::can_pickVolume(), Character::can_pickVolume_partial(), veh_interact::can_remove_part(), talker_character_const::can_stash_weapon(), Character::can_unwield(), npc_attack_melee::can_use(), npc_attack_gun::can_use(), npc_attack_throw::can_use(), Character::can_wear(), behavior::character_oracle_t::can_wear_warmer_clothes(), veh_interact::cant_do(), outfit::check_rigid_change_side(), outfit::check_rigid_conflicts(), outfit::check_rigid_sidedness(), item::color_in_inventory(), item_contents::combine(), Character::complete_disassemble(), vehicle::connect(), Character::crush_frozen_liquid(), cycle_action(), Character::dispose_item(), iuse_transform::do_transform(), inventory_selector::drag_drop_item(), Character::drop(), edit_integer(), iexamine::fertilize_plant(), activity_handlers::fertilize_plot_do_turn(), advanced_inventory::fill_lists_with_pane_items(), item_pocket::fill_with(), item::fill_with(), item::final_info(), vpart_info::finalize(), Item_factory::finalize_pre(), item_contents::item_contents_helper::find_pocket_for(), reload_activity_actor::finish(), iexamine::fireplace(), pickup_inventory_preset::get_denial(), comestible_inventory_preset::get_denial(), bionic_install_preset::get_denial(), bionic_install_surgeon_preset::get_denial(), weldrig_hack::get_item(), get_quality_from_string(), inventory_insert_selector::get_raw_stats(), item::get_remaining_capacity_for_liquid(), item::get_var(), getGasDiscountCardQuality(), talker_npc::give_item_to(), iuse::gunmod_attach(), talker_character::i_add_or_drop(), item_contents::insert_cost(), item_pocket::insert_item(), item_contents::insert_item(), exosuit_interact::insert_replace_activate_mod(), vehicle::install_part(), game::inventory_item_menu(), item_contents::is_compatible(), link_up_actor::link_extend_cable(), item::link_to(), link_up_actor::link_to_veh_app(), link_up_actor::link_tow_cable(), pocket_favorite_callback::move_item(), iuse::multicooker_tick(), game_menus::inv::multidrop(), npc_trading::npc_can_fit_items(), game::npc_menu(), Character::on_try_dodge(), outfit::only_one_conflicts(), vehicle::part_to_item(), place_craft_or_disassembly(), veh_app_interact::populate_app_actions(), vehicle::prepare_tool(), item::put_in(), query_int_impl(), rate_action_disassemble(), rate_action_wear(), rate_action_wield(), link_up_actor::remove_extensions(), vehicle_prototype::save_vehicle_as_prototype(), set_hobbies(), set_profession(), set_scenario(), options_manager::cOpt::setValue(), spell_effect::spawn_ethereal_item(), spawn_items(), starting_clothes(), holster_actor::store(), debug_menu::teleport_overmap(), try_insert(), deploy_furn_actor::use(), deploy_appliance_actor::use(), Character::use(), avatar_action::use_item(), pickup_selector::wear(), scenario::weighted_random_profession(), and pickup_selector::wield().
Member Data Documentation
msg
std::string ret_val_common::msg private
Definition at line 34 of file ret_val.h.
Referenced by c_str(), ret_val< void >::make_failure(), ret_val< T >::make_failure(), ret_val< void >::make_success(), ret_val< T >::make_success(), and str().
succ
bool ret_val_common::succ private
Definition at line 35 of file ret_val.h.
Referenced by success().
The documentation for this class was generated from the following file:
src/ret_val.h