Cataclysm DDA: npc_attack_activate_item Class Reference
npc_attack_activate_item Class Reference
#include <npc_attack.h>
Public Member Functions
npc_attack_activate_item (item &activatable_item)
npc_attack_rating evaluate (const npc &source, const Creature *target) const override
Parameters: source - the npc making the attack target - the desired target of the npc.
std::vector< npc_attack_rating > all_evaluations (const npc &source, const Creature *target) const override
For debug information.
void use (npc &source, const tripoint &location) const override
Public Member Functions inherited from npc_attack
virtual ~npc_attack ()=default
Private Member Functions
bool can_use (const npc &source) const
Private Attributes
item & activatable_item
Detailed Description
Definition at line 131 of file npc_attack.h.
Constructor & Destructor Documentation
npc_attack_activate_item()
npc_attack_activate_item::npc_attack_activate_item (item & activatable_item) inline explicit
Definition at line 135 of file npc_attack.h.
                                                                     :
             activatable_item( activatable_item ) {}
Member Function Documentation
all_evaluations()
std::vector< npc_attack_rating > npc_attack_activate_item::all_evaluations (const npc & source, const Creature * target) const override virtual
For debug information.
returns all evaluated effectivenesses. This is abstracted out in evaluate() as it's faster to not use a container
Implements npc_attack.
Definition at line 614 of file npc_attack.cpp.
 {
     std::vector<npc_attack_rating> effectiveness;
     if( !can_use( source ) ) {
         return effectiveness;
     }
     // until we have better logic for grenades it's better to keep this as a last resort...
     const int emergency = source.emergency() ? 1 : 0;
     effectiveness.emplace_back( emergency, source.pos() );
     return effectiveness;
 }
References can_use(), npc::emergency(), and Creature::pos().
can_use()
bool npc_attack_activate_item::can_use (const npc & source) const private
Definition at line 592 of file npc_attack.cpp.
 {
     if( !activatable_item.has_flag( flag_NPC_ACTIVATE ) ) {
         //TODO: make this more complete. only does BOMB type items
         return false;
     }
     const bool can_use_grenades = !source.is_hallucination() && ( !source.is_player_ally() ||
                                   source.rules.has_flag( ally_rule::use_grenades ) );
     return can_use_grenades;
 }
References activatable_item, flag_NPC_ACTIVATE, npc_follower_rules::has_flag(), item::has_flag(), npc::is_hallucination(), npc::is_player_ally(), npc::rules, and use_grenades.
Referenced by all_evaluations(), and evaluate().
evaluate()
npc_attack_rating npc_attack_activate_item::evaluate (const npc & source, const Creature * target) const override virtual
Parameters: source - the npc making the attack target - the desired target of the npc.
valued at 100%
Implements npc_attack.
Definition at line 603 of file npc_attack.cpp.
 {
     if( !can_use( source ) ) {
         return npc_attack_rating( std::nullopt, source.pos() );
     }
     // until we have better logic for grenades it's better to keep this as a last resort...
     const int emergency = source.emergency() ? 1 : 0;
     return npc_attack_rating( emergency, source.pos() );
 }
References can_use(), npc::emergency(), and Creature::pos().
use()
void npc_attack_activate_item::use (npc & source, const tripoint & location) const override virtual
Implements npc_attack.
Definition at line 583 of file npc_attack.cpp.
 {
     if( !source.wield( activatable_item ) ) {
         debugmsg( "%s can't wield %s it tried to activate", source.disp_name(),
                   activatable_item.display_name() );
     }
     source.activate_item( activatable_item );
 }
References activatable_item, npc::activate_item(), debugmsg, Character::disp_name(), item::display_name(), and npc::wield().
Member Data Documentation
activatable_item
item& npc_attack_activate_item::activatable_item private
Definition at line 133 of file npc_attack.h.
Referenced by can_use(), and use().
The documentation for this class was generated from the following files:
src/npc_attack.h
src/npc_attack.cpp