Cataclysm DDA: lockpick_activity_actor Class Reference
lockpick_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static lockpick_activity_actor use_item (int moves_total, const item_location &lockpick, const tripoint &target)
Use regular lockpick.
static lockpick_activity_actor use_bionic (const tripoint &target)
Use bionic lockpick.
static std::optional< tripoint > select_location (avatar &you)
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
lockpick_activity_actor (int moves_total, const std::optional< item_location > &lockpick, const std::optional< item > &fake_lockpick, const tripoint &target)
Private Attributes
int moves_total
std::optional< item_location > lockpick
std::optional< item > fake_lockpick
tripoint target
Detailed Description
Definition at line 622 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
lockpick_activity_actor()
lockpick_activity_actor::lockpick_activity_actor (int moves_total, const std::optional< item_location > & lockpick, const std::optional< item > & fake_lockpick, const tripoint & target) inline private
Definition at line 630 of file activity_actor_definitions.h.
           : moves_total( moves_total ), lockpick( lockpick ), fake_lockpick( fake_lockpick ),
             target( target ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> lockpick_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 661 of file activity_actor_definitions.h.
{
             return std::make_unique<lockpick_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > lockpick_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 2917 of file activity_actor.cpp.
 {
     lockpick_activity_actor actor( 0, std::nullopt, std::nullopt, tripoint_zero );
     JsonObject data = jsin.get_object();
     data.read( "moves_total", actor.moves_total );
     data.read( "lockpick", actor.lockpick );
     data.read( "fake_lockpick", actor.fake_lockpick );
     data.read( "target", actor.target );
     return actor.clone();
 }
References clone(), fake_lockpick, JsonValue::get_object(), lockpick, moves_total, JsonObject::read(), target, and tripoint_zero.
do_turn()
void lockpick_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 656 of file activity_actor_definitions.h.
 {}
finish()
void lockpick_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 2706 of file activity_actor.cpp.
 {
     act.set_to_null();
     item *it;
     if( lockpick.has_value() ) {
         it = ( *lockpick ).get_item();
     } else {
         it = &*fake_lockpick;
     }
     if( !it ) {
         debugmsg( "Lost ACT_LOCKPICK item" );
         return;
     }
     map &here = get_map();
     const tripoint target = here.getlocal( this->target );
     const ter_id ter_type = here.ter( target );
     const furn_id furn_type = here.furn( target );
     optional_vpart_position const veh = here.veh_at( target );
     int locked_part = -1;
     ter_id new_ter_type;
     furn_id new_furn_type;
     std::string open_message = _( "The lock opens…" );
     if( veh ) {
         std::vector<vehicle_part *> parts_at_target = veh->vehicle().get_parts_at(
                     target, "LOCKABLE_DOOR", part_status_flag::available );
         if( !parts_at_target.empty() ) {
             locked_part = veh->vehicle().next_part_to_unlock(
                               veh->vehicle().index_of_part( parts_at_target.front() ) );
         }
     }
     if( here.has_furn( target ) ) {
         if( furn_type->lockpick_result.is_null() ) {
             who.add_msg_if_player( m_bad, _( "You can't open this lock." ) );
             return;
         }
         new_furn_type = furn_type->lockpick_result;
         if( !furn_type->lockpick_message.empty() ) {
             open_message = furn_type->lockpick_message.translated();
         }
     } else if( locked_part >= 0 ) {
         // no-op.
     } else {
         if( ter_type->lockpick_result.is_null() ) {
             who.add_msg_if_player( m_bad, _( "You can't open this lock." ) );
             return;
         }
         new_ter_type = ter_type->lockpick_result;
         if( !ter_type->lockpick_message.empty() ) {
             open_message = ter_type->lockpick_message.translated();
         }
     }
     bool perfect = it->has_flag( flag_PERFECT_LOCKPICK );
     bool destroy = false;
     // Your devices skill is the primary skill that applies to your roll. Your mechanics skill has a little input.
     const float weighted_skill_average = ( 3.0f * who.get_skill_level(
             skill_traps ) + who.get_skill_level( skill_mechanics ) ) / 4.0f;
     // Your dexterity determines most of your stat contribution, but your intelligence and perception combined are about half as much.
     const float weighted_stat_average = ( 6.0f * who.dex_cur + 2.0f * who.per_cur +
                                           who.int_cur ) / 9.0f;
     // Get a bonus from your lockpick quality if the quality is higher than 3, or a penalty if it is lower. For a bobby pin this puts you at -2, for a locksmith kit, +2.
     const float tool_effect = ( it->get_quality( qual_LOCKPICK ) - 3 ) - ( it->damage() / 2000.0 );
     // Without at least a basic lockpick proficiency, your skill level is effectively 6 levels lower.
     int proficiency_effect = -3;
     int duration_proficiency_factor = 10;
     if( who.has_proficiency( proficiency_prof_lockpicking ) ) {
         // If you have the basic lockpick prof, negate the above penalty
         proficiency_effect = 0;
         duration_proficiency_factor = 5;
     }
     if( who.has_proficiency( proficiency_prof_lockpicking_expert ) ) {
         // If you have the locksmith proficiency, your skill level is effectively 4 levels higher.
         proficiency_effect = 3;
         duration_proficiency_factor = 1;
     }
     // We get our average roll by adding the above factors together. For a person with no skill, average stats, no proficiencies, and an improvised lockpick, mean_roll will be 2.
     const float mean_roll = weighted_skill_average + ( weighted_stat_average / 4 ) + proficiency_effect
                             + tool_effect;
     // A standard deviation of 2 means that about 2/3 of rolls will come within 2 points of your mean_roll. Lockpicking
     int pick_roll = std::round( normal_roll( mean_roll, 2 ) );
     // Lock_roll should be replaced with a flat value defined by the door, soon.
     // In the meantime, let's roll 3d5-3, giving us a range of 0-12.
     int lock_roll = rng( 0, 4 ) + rng( 0, 4 ) + rng( 0, 4 );
     add_msg_debug( debugmode::DF_ACT_LOCKPICK, "Rolled %i. Mean_roll %g. Difficulty %i.",
                    pick_roll, mean_roll, lock_roll );
     // Your base skill XP gain is derived from the lock difficulty (which is currently random but shouldn't be).
     int xp_gain = 3 * lock_roll;
     if( perfect || ( pick_roll >= lock_roll ) ) {
         if( !perfect ) {
             // Increase your XP if you successfully pick the lock, unless you were using a Perfect Lockpick.
             xp_gain = xp_gain * 2;
         }
         if( here.has_furn( target ) ) {
             here.furn_set( target, new_furn_type );
         } else if( locked_part >= 0 ) {
             veh->vehicle().unlock( locked_part );
         } else {
             here.ter_set( target, new_ter_type );
         }
         who.add_msg_if_player( m_good, open_message );
     } else if( furn_type == furn_f_gunsafe_ml && lock_roll > ( 3 * pick_roll ) ) {
         who.add_msg_if_player( m_bad, _( "Your clumsy attempt jams the lock!" ) );
         here.furn_set( target, furn_f_gunsafe_mj );
     } else if( lock_roll > ( 1.5 * pick_roll ) ) {
         if( it->inc_damage() ) {
             who.add_msg_if_player( m_bad,
                                    _( "The lock stumps your efforts to pick it, and you destroy your tool." ) );
             destroy = true;
         } else {
             who.add_msg_if_player( m_bad,
                                    _( "The lock stumps your efforts to pick it, and you damage your tool." ) );
         }
     } else {
         who.add_msg_if_player( m_bad, _( "The lock stumps your efforts to pick it." ) );
     }
     if( avatar *you = dynamic_cast<avatar *>( &who ) ) {
         // Gives another boost to XP, reduced by your skill level.
         // Higher skill levels require more difficult locks to gain a meaningful amount of xp.
         // Again, we're using randomized lock_roll until a defined lock difficulty is implemented.
         if( lock_roll > round( you->get_skill_level( skill_traps ) ) ) {
             xp_gain += lock_roll + ( xp_gain / ( you->get_skill_level( skill_traps ) + 1 ) );
         } else {
             xp_gain += xp_gain / ( you->get_skill_level( skill_traps ) + 1 );
         }
         you->practice( skill_traps, xp_gain );
     }
     if( !perfect && ter_type == ter_t_door_locked_alarm && ( lock_roll + dice( 1, 30 ) ) > pick_roll ) {
         sounds::sound( who.pos(), 40, sounds::sound_t::alarm, _( "an alarm sound!" ), true, "environment",
                        "alarm" );
     }
     if( destroy && lockpick.has_value() ) {
         ( *lockpick ).remove_item();
     }
     who.practice_proficiency( proficiency_prof_lockpicking,
                               time_duration::from_moves( act.moves_total ) / duration_proficiency_factor );
     who.practice_proficiency( proficiency_prof_lockpicking_expert,
                               time_duration::from_moves( act.moves_total ) / duration_proficiency_factor );
 }
References _, act, add_msg_debug, Character::add_msg_if_player(), sounds::alarm, available, item::damage(), debugmsg, Character::dex_cur, debugmode::DF_ACT_LOCKPICK, dice(), translation::empty(), fake_lockpick, flag_PERFECT_LOCKPICK, time_duration::from_moves(), map::furn(), furn_f_gunsafe_mj, furn_f_gunsafe_ml, map::furn_set(), get_map(), item::get_quality(), Character::get_skill_level(), map::getlocal(), item::has_flag(), map::has_furn(), Character::has_proficiency(), item::inc_damage(), Character::int_cur, string_id< T >::is_null(), lockpick, ter_t::lockpick_message, furn_t::lockpick_message, ter_t::lockpick_result, furn_t::lockpick_result, m_bad, m_good, normal_roll(), Character::per_cur, Creature::pos(), Character::practice_proficiency(), proficiency_prof_lockpicking, proficiency_prof_lockpicking_expert, qual_LOCKPICK, rng(), round(), skill_mechanics, skill_traps, sounds::sound(), target, map::ter(), map::ter_set(), ter_t_door_locked_alarm, translation::translated(), and map::veh_at().
get_type()
activity_id lockpick_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 651 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_LOCKPICK" );
         }
References activity_id.
select_location()
std::optional< tripoint > lockpick_activity_actor::select_location (avatar & you) static
Definition at line 2865 of file activity_actor.cpp.
 {
     if( you.cant_do_mounted() ) {
         return std::nullopt;
     }
     const std::function<bool( const tripoint & )> is_pickable = [&you]( const tripoint & p ) {
         const map &here = get_map();
         const optional_vpart_position vpart = here.veh_at( p );
         if( p == you.pos() ) {
             return false;
         }
         return here.has_flag( ter_furn_flag::TFLAG_PICKABLE, p ) ||
                ( vpart && vpart->vehicle().next_part_to_unlock( vpart->part_index() ) >= 0 );
     };
     std::optional<tripoint> target = choose_adjacent_highlight(
                                          _( "Use your lockpick where?" ), _( "There is nothing to lockpick nearby." ), is_pickable, false );
     if( !target ) {
         return std::nullopt;
     }
     if( is_pickable( *target ) ) {
         return target;
     }
     const ter_id terr_type = get_map().ter( *target );
     if( *target == you.pos() ) {
         you.add_msg_if_player( m_info, _( "You pick your nose and your sinuses swing open." ) );
     } else if( get_creature_tracker().creature_at<npc>( *target ) ) {
         you.add_msg_if_player( m_info,
                                _( "You can pick your friends, and you can\npick your nose, but you can't pick\nyour friend's nose." ) );
     } else if( terr_type == ter_t_door_c ) {
         you.add_msg_if_player( m_info, _( "That door isn't locked." ) );
     } else {
         you.add_msg_if_player( m_info, _( "That cannot be picked." ) );
     }
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), Character::cant_do_mounted(), choose_adjacent_highlight(), get_creature_tracker(), get_map(), map::has_flag(), m_info, Creature::pos(), target, map::ter(), ter_t_door_c, TFLAG_PICKABLE, and map::veh_at().
Referenced by Character::activate_bionic(), and iuse::pick_lock().
serialize()
void lockpick_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 2905 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves_total", moves_total );
     jsout.member( "lockpick", lockpick );
     jsout.member( "fake_lockpick", fake_lockpick );
     jsout.member( "target", target );
     jsout.end_object();
 }
References JsonOut::end_object(), fake_lockpick, lockpick, JsonOut::member(), moves_total, JsonOut::start_object(), and target.
start()
void lockpick_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 2696 of file activity_actor.cpp.
 {
     act.moves_left = moves_total;
     act.moves_total = moves_total;
     const time_duration lockpicking_time = time_duration::from_moves( moves_total );
     add_msg_debug( debugmode::DF_ACT_LOCKPICK, "lockpicking time = %s",
                    to_string_writable( lockpicking_time ) );
 }
References act, add_msg_debug, debugmode::DF_ACT_LOCKPICK, time_duration::from_moves(), moves_total, and to_string_writable().
use_bionic()
lockpick_activity_actor lockpick_activity_actor::use_bionic (const tripoint & target) static
Use bionic lockpick.
'target' is in global coords
Definition at line 2684 of file activity_actor.cpp.
 {
     return lockpick_activity_actor {
         to_moves<int>( 4_seconds ),
         std::nullopt,
         item( itype_pseudo_bio_picklock ),
         target
     };
 }
References item, itype_pseudo_bio_picklock, and target.
Referenced by Character::activate_bionic(), and iexamine::locked_object_pickable().
use_item()
lockpick_activity_actor lockpick_activity_actor::use_item (int moves_total, const item_location & lockpick, const tripoint & target) static
Use regular lockpick.
'target' is in global coords
Definition at line 2670 of file activity_actor.cpp.
 {
     return lockpick_activity_actor {
         moves_total,
         lockpick,
         std::nullopt,
         target
     };
 }
References lockpick, moves_total, and target.
Referenced by iuse::pick_lock().
Member Data Documentation
fake_lockpick
std::optional<item> lockpick_activity_actor::fake_lockpick private
Definition at line 627 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
lockpick
std::optional<item_location> lockpick_activity_actor::lockpick private
Definition at line 626 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), serialize(), and use_item().
moves_total
int lockpick_activity_actor::moves_total private
Definition at line 625 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), start(), and use_item().
target
tripoint lockpick_activity_actor::target private
Definition at line 628 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), select_location(), serialize(), use_bionic(), and use_item().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp