Cataclysm DDA: text_style_check_reader Class Reference
text_style_check_reader Class Reference
Only for external use in legacy code where migrating to class translation is impractical.
#include <generic_factory.h>
Public Types
enum class allow_object : int { no , yes }
Public Member Functions
text_style_check_reader (allow_object object_allowed=allow_object::yes)
std::string get_next (const JsonValue &jv) const
Public Member Functions inherited from generic_typed_reader< text_style_check_reader >
void insert_values_from (const JsonObject &jo, const std::string_view member_name, C &container) const
void insert_next (JsonValue &jv, C &container) const
void erase_values_from (const JsonObject &jo, const std::string_view member_name, C &container) const
void erase_next (JsonValue &jv, C &container) const
bool operator() (const JsonObject &jo, const std::string_view member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string_view member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string_view name, C &) const
bool do_relative (const JsonObject &jo, const std::string_view name, C &member) const
bool read_normal (const JsonObject &jo, const std::string_view name, C &member) const
Private Attributes
allow_object object_allowed
Detailed Description
Only for external use in legacy code where migrating to class translation is impractical.
For new code load with class translation instead.
Definition at line 1344 of file generic_factory.h.
Member Enumeration Documentation
allow_object
enum text_style_check_reader::allow_object : int strong
Enumerator
no
yes
Definition at line 1347 of file generic_factory.h.
                                 : int {
             no,
             yes,
         };
Constructor & Destructor Documentation
text_style_check_reader()
text_style_check_reader::text_style_check_reader (allow_object object_allowed = allow_object::yes) explicit
Definition at line 4 of file text_style_check_reader.cpp.
     : object_allowed( object_allowed )
 {
 }
Member Function Documentation
get_next()
std::string text_style_check_reader::get_next (const JsonValue & jv) const
Definition at line 9 of file text_style_check_reader.cpp.
 {
     const JsonValue &jsin = jv;
     std::string raw;
     bool check_style = true;
     if( object_allowed == allow_object::yes && jsin.test_object() ) {
         JsonObject jsobj = jsin.get_object();
         raw = jsobj.get_string( "str" );
         if( jsobj.has_member( "//NOLINT(cata-text-style)" ) ) {
             check_style = false;
         }
     } else {
         raw = jsin.get_string();
     }
 #ifndef CATA_IN_TOOL
     if( test_mode && check_style ) {
         const auto text_style_callback =
             [&jsin]
             ( const text_style_fix type, const std::string & msg,
               const std::u32string::const_iterator & beg, const std::u32string::const_iterator & /*end*/,
               const std::u32string::const_iterator & /*at*/,
               const std::u32string::const_iterator & from, const std::u32string::const_iterator & to,
               const std::string & fix
         ) {
             std::string err;
             switch( type ) {
                 case text_style_fix::removal:
                     err = msg + "\n"
                           + "    Suggested fix: remove \"" + utf32_to_utf8( std::u32string( from, to ) ) + "\"\n"
                           + "    At the following position (marked with caret)";
                     break;
                 case text_style_fix::insertion:
                     err = msg + "\n"
                           + "    Suggested fix: insert \"" + fix + "\"\n"
                           + "    At the following position (marked with caret)";
                     break;
                 case text_style_fix::replacement:
                     err = msg + "\n"
                           + "    Suggested fix: replace \"" + utf32_to_utf8( std::u32string( from, to ) )
                           + "\" with \"" + fix + "\"\n"
                           + "    At the following position (marked with caret)";
                     break;
             }
             try {
                 jsin.string_error( std::distance( beg, to ), err );
             } catch( const JsonError &e ) {
                 debugmsg( "(json-error)\n%s", e.what() );
             }
         };
         const std::u32string raw32 = utf8_to_utf32( raw );
         text_style_check<std::u32string::const_iterator>( raw32.cbegin(), raw32.cend(),
                 fix_end_of_string_spaces::yes, escape_unicode::no, text_style_callback );
     }
 #endif
     return raw;
 }
References debugmsg, JsonValue::get_object(), JsonValue::get_string(), JsonObject::get_string(), JsonObject::has_member(), insertion, no, object_allowed, removal, replacement, JsonValue::string_error(), test_mode, JsonValue::test_object(), type, utf32_to_utf8(), utf8_to_utf32(), yes, and yes.
Referenced by translation::deserialize().
Member Data Documentation
object_allowed
allow_object text_style_check_reader::object_allowed private
Definition at line 1357 of file generic_factory.h.
Referenced by get_next().
The documentation for this class was generated from the following files:
src/generic_factory.h
src/text_style_check_reader.cpp