Cataclysm DDA: flexbuffer_cache Class Reference
flexbuffer_cache Class Reference
#include <flexbuffer_cache.h>
Public Member Functions
flexbuffer_cache (const fs::path &cache_directory, const fs::path &root_directory)
~flexbuffer_cache ()
shared_flexbuffer parse_and_cache (fs::path lexically_normal_json_source_path, size_t offset=0) noexcept(false)
Static Public Member Functions
static shared_flexbuffer parse (fs::path json_source_path, size_t offset=0) noexcept(false)
static shared_flexbuffer parse_buffer (std::string buffer) noexcept(false)
Private Types
using shared_flexbuffer = std::shared_ptr< parsed_flexbuffer >
Private Member Functions
flexbuffer_cache (flexbuffer_cache &&) noexcept=default
Private Attributes
std::unique_ptr< flexbuffer_disk_cache > disk_cache_
Detailed Description
Definition at line 50 of file flexbuffer_cache.h.
Member Typedef Documentation
shared_flexbuffer
using flexbuffer_cache::shared_flexbuffer = std::shared_ptr<parsed_flexbuffer> private
Definition at line 52 of file flexbuffer_cache.h.
Constructor & Destructor Documentation
flexbuffer_cache() [1/2]
flexbuffer_cache::flexbuffer_cache (const fs::path & cache_directory, const fs::path & root_directory) explicit
Definition at line 391 of file flexbuffer_cache.cpp.
 {
     if( !cache_directory.empty() ) {
         disk_cache_ = flexbuffer_disk_cache::init_from_folder( cache_directory, root_directory );
     }
 }
References disk_cache_, and flexbuffer_disk_cache::init_from_folder().
~flexbuffer_cache()
flexbuffer_cache::~flexbuffer_cache () default
flexbuffer_cache() [2/2]
flexbuffer_cache::flexbuffer_cache (flexbuffer_cache &&) private default noexcept
Member Function Documentation
parse()
std::shared_ptr< parsed_flexbuffer > flexbuffer_cache::parse (fs::path json_source_path, size_t offset = 0) static noexcept
Definition at line 401 of file flexbuffer_cache.cpp.
 {
     std::string json_source_path_string = json_source_path.generic_u8string();
     std::shared_ptr<mmap_file> json_source = mmap_file::map_file( json_source_path );
     if( !json_source ) {
         throw std::runtime_error( "Failed to mmap " + json_source_path_string );
     }
     const char *json_text = reinterpret_cast<const char *>( json_source->base ) + offset;
     std::vector<uint8_t> fb = parse_json_to_flexbuffer_( json_text, json_source_path_string.c_str() );
     auto storage = std::make_shared<flexbuffer_vector_storage>( std::move( fb ) );
     std::error_code ec;
     // If we got this far we can get the mtime.
     fs::file_time_type mtime = get_file_mtime_millis( json_source_path, ec );
     ( void )ec;
     return std::make_shared<file_flexbuffer>(
                std::move( storage ),
                std::move( json_source_path ),
                mtime,
                offset );
 }
References anonymous_namespace{flexbuffer_cache.cpp}::get_file_mtime_millis(), mmap_file::map_file(), and anonymous_namespace{flexbuffer_cache.cpp}::parse_json_to_flexbuffer_().
Referenced by anonymous_namespace{json_loader.cpp}::from_path_at_offset_opt_impl().
parse_and_cache()
std::shared_ptr< parsed_flexbuffer > flexbuffer_cache::parse_and_cache (fs::path lexically_normal_json_source_path, size_t offset = 0) noexcept
Definition at line 428 of file flexbuffer_cache.cpp.
 {
     // Is our cache potentially stale?
     if( disk_cache_ ) {
         std::shared_ptr<flexbuffer_mmap_storage> cached_storage = disk_cache_->load_flexbuffer_if_not_stale(
                     lexically_normal_json_source_path );
         if( cached_storage ) {
             std::error_code ec;
             fs::file_time_type mtime = get_file_mtime_millis( lexically_normal_json_source_path, ec );
             ( void )ec;
             return std::make_shared<file_flexbuffer>( std::move( cached_storage ),
                     std::move( lexically_normal_json_source_path ), mtime, offset );
         }
     }
     std::string json_source_path_string = lexically_normal_json_source_path.generic_u8string();
     std::optional<std::string> json_file_contents = read_whole_file(
                 lexically_normal_json_source_path );
     if( !json_file_contents.has_value() || json_file_contents->empty() ) {
         throw std::runtime_error( "Failed to read " + json_source_path_string );
     }
     std::string &json_source = *json_file_contents;
     const char *json_text = reinterpret_cast<const char *>( json_source.c_str() ) + offset;
     std::vector<uint8_t> fb = parse_json_to_flexbuffer_( json_text, json_source_path_string.c_str() );
     if( disk_cache_ ) {
         disk_cache_->save_to_disk( lexically_normal_json_source_path, fb );
     }
     auto storage = std::make_shared<flexbuffer_vector_storage>( std::move( fb ) );
     std::error_code ec;
     fs::file_time_type mtime = fs::last_write_time( lexically_normal_json_source_path, ec );
     if( ec ) {
         // Whatever.
     }
     return std::make_shared<file_flexbuffer>( std::move( storage ),
             std::move( lexically_normal_json_source_path ),
             mtime, offset );
 }
References disk_cache_, anonymous_namespace{flexbuffer_cache.cpp}::get_file_mtime_millis(), anonymous_namespace{flexbuffer_cache.cpp}::parse_json_to_flexbuffer_(), and read_whole_file().
Referenced by anonymous_namespace{json_loader.cpp}::from_path_at_offset_opt_impl().
parse_buffer()
std::shared_ptr< parsed_flexbuffer > flexbuffer_cache::parse_buffer (std::string buffer) static noexcept
Definition at line 474 of file flexbuffer_cache.cpp.
 {
     std::vector<uint8_t> fb = parse_json_to_flexbuffer_( buffer.c_str(), nullptr );
     auto storage = std::make_shared<flexbuffer_vector_storage>( std::move( fb ) );
     return std::make_shared<string_flexbuffer>( std::move( storage ), std::move( buffer ) );
 }
References anonymous_namespace{flexbuffer_cache.cpp}::parse_json_to_flexbuffer_().
Referenced by JsonArray::empty_array_(), JsonObject::empty_object_(), and json_loader::from_string().
Member Data Documentation
disk_cache_
std::unique_ptr<flexbuffer_disk_cache> flexbuffer_cache::disk_cache_ private
Definition at line 71 of file flexbuffer_cache.h.
Referenced by flexbuffer_cache(), and parse_and_cache().
The documentation for this class was generated from the following files:
src/flexbuffer_cache.h
src/flexbuffer_cache.cpp