Cataclysm DDA: firestarter_actor Class Reference
firestarter_actor Class Reference
Starts a fire instantly.
#include <iuse_actor.h>
Public Member Functions
float light_mod (const tripoint &pos) const
Modifier on speed - higher is better, 0 means it won't work.
int moves_cost_by_fuel (const tripoint_bub_ms &pos) const
Checks quality of fuel on the tile and interpolates move cost based on that.
firestarter_actor (const std::string &type="firestarter")
~firestarter_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
ret_val< void > can_use (const Character &, const item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Static Public Member Functions
static bool prep_firestarter_use (const Character &p, tripoint_bub_ms &pos)
static void resolve_firestarter_use (Character *p, const tripoint_bub_ms &pos)
Player here isn't const because pyromaniacs gain a mood boost from it.
Public Attributes
int moves_cost_fast = 100
Moves used at start of the action when starting fires with good fuel.
int moves_cost_slow = 1000
Total moves when starting fires with mediocre fuel.
bool need_sunlight = false
Does it need sunlight to be used.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Starts a fire instantly.
Definition at line 462 of file iuse_actor.h.
Constructor & Destructor Documentation
firestarter_actor()
firestarter_actor::firestarter_actor (const std::string & type = "firestarter") inline explicit
Definition at line 488 of file iuse_actor.h.
 : iuse_actor( type ) {}
~firestarter_actor()
firestarter_actor::~firestarter_actor () override default
Member Function Documentation
can_use()
ret_val< void > firestarter_actor::can_use (const Character & p, const item & it, const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 1357 of file iuse_actor.cpp.
 {
     if( p.is_underwater() ) {
         return ret_val<void>::make_failure( _( "You can't do that while underwater." ) );
     }
     if( !it.ammo_sufficient( &p ) ) {
         return ret_val<void>::make_failure( _( "This tool doesn't have enough charges." ) );
     }
     if( need_sunlight && light_mod( p.pos() ) <= 0.0f ) {
         return ret_val<void>::make_failure( _( "You need direct sunlight to light a fire with this." ) );
     }
     return ret_val<void>::make_success();
 }
References _, item::ammo_sufficient(), Creature::is_underwater(), light_mod(), ret_val< T >::make_failure(), ret_val< T >::make_success(), need_sunlight, and Creature::pos().
Referenced by add_firestarter(), and iexamine::fireplace().
clone()
std::unique_ptr< iuse_actor > firestarter_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 1263 of file iuse_actor.cpp.
 {
     return std::make_unique<firestarter_actor>( *this );
 }
light_mod()
float firestarter_actor::light_mod (const tripoint & pos) const
Modifier on speed - higher is better, 0 means it won't work.
Definition at line 1375 of file iuse_actor.cpp.
 {
     if( !need_sunlight ) {
         return 1.0f;
     }
     if( g->is_sheltered( pos ) ) {
         return 0.0f;
     }
     if( incident_sun_irradiance( get_weather().weather_id, calendar::turn ) > irradiance::moderate ) {
         return std::pow( g->natural_light_level( pos.z ) / 80.0f, 8 );
     }
     return 0.0f;
 }
References g, get_weather(), incident_sun_irradiance(), irradiance::moderate, need_sunlight, math_opers::pos(), and calendar::turn.
Referenced by can_use(), activity_handlers::start_fire_do_turn(), and use().
load()
void firestarter_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 1256 of file iuse_actor.cpp.
 {
     moves_cost_fast = obj.get_int( "moves", moves_cost_fast );
     moves_cost_slow = obj.get_int( "moves_slow", moves_cost_fast * 10 );
     need_sunlight = obj.get_bool( "need_sunlight", false );
 }
References JsonObject::get_bool(), JsonObject::get_int(), moves_cost_fast, moves_cost_slow, and need_sunlight.
moves_cost_by_fuel()
int firestarter_actor::moves_cost_by_fuel (const tripoint_bub_ms & pos) const
Checks quality of fuel on the tile and interpolates move cost based on that.
Definition at line 1391 of file iuse_actor.cpp.
 {
     map &here = get_map();
     if( here.flammable_items_at( pos, 100 ) ) {
         return moves_cost_fast;
     }
     if( here.flammable_items_at( pos, 10 ) ) {
         return ( moves_cost_slow + moves_cost_fast ) / 2;
     }
     return moves_cost_slow;
 }
References map::flammable_items_at(), get_map(), moves_cost_fast, moves_cost_slow, and math_opers::pos().
Referenced by use().
prep_firestarter_use()
bool firestarter_actor::prep_firestarter_use (const Character & p, tripoint_bub_ms & pos) static
Definition at line 1268 of file iuse_actor.cpp.
 {
     // checks for fuel are handled by use and the activity, not here
     if( pos == p.pos_bub() ) {
         if( const std::optional<tripoint> pnt_ = choose_adjacent( _( "Light where?" ) ) ) {
             // TODO: fix point types
             pos = tripoint_bub_ms( *pnt_ );
         } else {
             return false;
         }
     }
     if( pos == p.pos_bub() ) {
         p.add_msg_if_player( m_info, _( "You would set yourself on fire." ) );
         p.add_msg_if_player( _( "But you're already smokin' hot." ) );
         return false;
     }
     map &here = get_map();
     if( here.get_field( pos, fd_fire ) ) {
         // check if there's already a fire
         p.add_msg_if_player( m_info, _( "There is already a fire." ) );
         return false;
     }
     // check if there's a fire fuel source spot
     bool target_is_firewood = false;
     if( here.tr_at( pos ).id == tr_firewood_source ) {
         target_is_firewood = true;
     } else {
         zone_manager &mgr = zone_manager::get_manager();
         auto zones = mgr.get_zones( zone_type_SOURCE_FIREWOOD, here.getglobal( pos ) );
         if( !zones.empty() ) {
             target_is_firewood = true;
         }
     }
     if( target_is_firewood ) {
         if( !query_yn( _( "Do you really want to burn your firewood source?" ) ) ) {
             return false;
         }
     }
     // Check for an adjacent fire container
     for( const tripoint_bub_ms &query : here.points_in_radius( pos, 1 ) ) {
         // Don't ask if we're setting a fire on top of a fireplace
         // TODO: fix point types
         if( here.has_flag_furn( "FIRE_CONTAINER", pos.raw() ) ) {
             break;
         }
         // Skip the position we're trying to light on fire
         if( query == pos ) {
             continue;
         }
         // TODO: fix point types
         if( here.has_flag_furn( "FIRE_CONTAINER", query.raw() ) ) {
             if( !query_yn( _( "Are you sure you want to start fire here?  There's a fireplace adjacent." ) ) ) {
                 return false;
             } else {
                 // Don't ask multiple times if they say no and there are multiple fireplaces
                 break;
             }
         }
     }
     // Check for a brazier.
     bool has_unactivated_brazier = false;
     for( const item &i : here.i_at( pos ) ) {
         if( i.typeId() == itype_brazier ) {
             has_unactivated_brazier = true;
         }
     }
     return !has_unactivated_brazier ||
            query_yn(
                _( "There's a brazier there but you haven't set it up to contain the fire.  Continue?" ) );
 }
References _, Character::add_msg_if_player(), choose_adjacent(), fd_fire, map::get_field(), zone_manager::get_manager(), get_map(), zone_manager::get_zones(), map::getglobal(), map::has_flag_furn(), map::i_at(), trap::id, itype_brazier, m_info, map::points_in_radius(), math_opers::pos(), Creature::pos_bub(), query_yn(), map::tr_at(), tr_firewood_source, zone_type_SOURCE_FIREWOOD, and zones.
Referenced by use().
resolve_firestarter_use()
void firestarter_actor::resolve_firestarter_use (Character * p, const tripoint_bub_ms & pos) static
Player here isn't const because pyromaniacs gain a mood boost from it.
Definition at line 1339 of file iuse_actor.cpp.
 {
     if( get_map().add_field( pos, fd_fire, 1, 10_minutes ) ) {
         if( !p->has_trait( trait_PYROMANIA ) ) {
             p->add_msg_if_player( _( "You successfully light a fire." ) );
         } else {
             if( one_in( 4 ) ) {
                 p->add_msg_if_player( m_mixed,
                                       _( "You light a fire, but it isn't enough.  You need to light more." ) );
             } else {
                 p->add_msg_if_player( m_good, _( "You happily light a fire." ) );
                 p->add_morale( MORALE_PYROMANIA_STARTFIRE, 5, 10, 6_hours, 4_hours );
                 p->rem_morale( MORALE_PYROMANIA_NOFIRE );
             }
         }
     }
 }
References _, Character::add_morale(), Character::add_msg_if_player(), fd_fire, get_map(), Character::has_trait(), m_good, m_mixed, MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, one_in(), math_opers::pos(), Character::rem_morale(), and trait_PYROMANIA.
Referenced by activity_handlers::start_fire_finish(), and use().
use()
std::optional< int > firestarter_actor::use (Character * p, item & it, const tripoint & spos) const override virtual
Survival speeds up fire starting
Implements iuse_actor.
Definition at line 1405 of file iuse_actor.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action firestarter that requires character but no character is present",
                   it.typeId().str() );
         return std::nullopt;
     }
     // TODO: fix point types
     tripoint_bub_ms pos( spos );
     float light = light_mod( p->pos() );
     if( !prep_firestarter_use( *p, pos ) ) {
         return std::nullopt;
     }
     double skill_level = p->get_skill_level( skill_survival );
     /** @EFFECT_SURVIVAL speeds up fire starting */
     float moves_modifier = std::pow( 0.8, std::min( 5.0, skill_level ) );
     const int moves_base = moves_cost_by_fuel( pos );
     const double moves_per_turn = to_moves<double>( 1_turns );
     const int min_moves = std::min<int>(
                               moves_base, std::sqrt( 1 + moves_base / moves_per_turn ) * moves_per_turn );
     const int moves = std::max<int>( min_moves, moves_base * moves_modifier ) / light;
     if( moves > to_moves<int>( 1_minutes ) ) {
         // If more than 1 minute, inform the player
         const int minutes = moves / to_moves<int>( 1_minutes );
         p->add_msg_if_player( m_info, need_sunlight ?
                               n_gettext( "If the current weather holds, it will take around %d minute to light a fire.",
                                          "If the current weather holds, it will take around %d minutes to light a fire.", minutes ) :
                               n_gettext( "At your skill level, it will take around %d minute to light a fire.",
                                          "At your skill level, it will take around %d minutes to light a fire.", minutes ),
                               minutes );
     } else if( moves < to_moves<int>( 2_turns ) && get_map().is_flammable( pos ) ) {
         // If less than 2 turns, don't start a long action
         resolve_firestarter_use( p, pos );
         p->mod_moves( -moves );
         return 1;
     }
     // skill gains are handled by the activity, but stored here in the index field
     const int potential_skill_gain = moves_modifier * ( std::min( 10.0, moves_cost_fast / 100.0 ) + 2 );
     p->assign_activity( ACT_START_FIRE, moves, potential_skill_gain,
                         0, it.tname() );
     p->activity.targets.emplace_back( *p, &it );
     p->activity.values.push_back( g->natural_light_level( pos.z() ) );
     p->activity.placement = get_map().getglobal( pos );
     // charges to use are handled by the activity
     return 0;
 }
References ACT_START_FIRE, Character::activity, Character::add_msg_if_player(), Character::assign_activity(), debugmsg, g, get_map(), Character::get_skill_level(), map::getglobal(), light, light_mod(), m_info, min(), Creature::mod_moves(), moves_cost_by_fuel(), moves_cost_fast, n_gettext, need_sunlight, player_activity::placement, Creature::pos(), math_opers::pos(), prep_firestarter_use(), resolve_firestarter_use(), skill_survival, sqrt(), string_id< T >::str(), player_activity::targets, item::tname(), item::typeId(), and player_activity::values.
Referenced by iexamine::fireplace().
Member Data Documentation
moves_cost_fast
int firestarter_actor::moves_cost_fast = 100
Moves used at start of the action when starting fires with good fuel.
Definition at line 468 of file iuse_actor.h.
Referenced by add_firestarter(), load(), moves_cost_by_fuel(), and use().
moves_cost_slow
int firestarter_actor::moves_cost_slow = 1000
Total moves when starting fires with mediocre fuel.
Definition at line 473 of file iuse_actor.h.
Referenced by load(), and moves_cost_by_fuel().
need_sunlight
bool firestarter_actor::need_sunlight = false
Does it need sunlight to be used.
Definition at line 478 of file iuse_actor.h.
Referenced by can_use(), light_mod(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp