Cataclysm DDA: aim_activity_actor Class Reference
aim_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
aim_activity_actor ()
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &act, Character &who) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
item_location get_weapon ()
void restore_view () const
bool load_RAS_weapon ()
void unload_RAS_weapon ()
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static aim_activity_actor use_wielded ()
Aiming wielded gun.
static aim_activity_actor use_bionic (const item &fake_gun)
Aiming fake gun provided by a bionic.
static aim_activity_actor use_mutation (const item &fake_gun)
Aiming fake gun provided by a mutation.
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Public Attributes
bool first_turn = true
std::string action
int aif_duration = 0
bool aiming_at_critter = false
bool snap_to_target = false
bool loaded_RAS_weapon = false
Not to try to unload RELOAD_AND_SHOOT weapon if it is not loaded.
bool shifting_view = false
tripoint initial_view_offset
bool aborted = false
Target UI requested to abort aiming.
bool abort_if_no_targets = false
if true abort if no targets are available when re-entering aiming ui after shooting
bool reload_requested = false
Target UI requested to abort aiming and reload weapon Implies aborted = true.
std::vector< weak_ptr_fast< Creature > > acceptable_losses
A friendly creature may enter line of fire during aim-and-shoot, and that generates a warning to proceed/abort.
Private Attributes
std::optional< item > fake_weapon
std::vector< tripoint > fin_trajectory
Detailed Description
Definition at line 44 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
aim_activity_actor()
aim_activity_actor::aim_activity_actor ()
Definition at line 284 of file activity_actor.cpp.
 {
     initial_view_offset = get_avatar().view_offset;
 }
References get_avatar(), initial_view_offset, and Character::view_offset.
Referenced by deserialize(), use_bionic(), use_mutation(), and use_wielded().
Member Function Documentation
canceled()
void aim_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 418 of file activity_actor.cpp.
 {
     restore_view();
     unload_RAS_weapon();
 }
References restore_view(), and unload_RAS_weapon().
clone()
std::unique_ptr<activity_actor> aim_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 97 of file activity_actor_definitions.h.
{
             return std::make_unique<aim_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > aim_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 445 of file activity_actor.cpp.
 {
     aim_activity_actor actor = aim_activity_actor();
     JsonObject data = jsin.get_object();
     data.read( "fake_weapon", actor.fake_weapon );
     data.read( "fin_trajectory", actor.fin_trajectory );
     data.read( "first_turn", actor.first_turn );
     data.read( "action", actor.action );
     data.read( "aif_duration", actor.aif_duration );
     data.read( "aiming_at_critter", actor.aiming_at_critter );
     data.read( "snap_to_target", actor.snap_to_target );
     data.read( "loaded_RAS_weapon", actor.loaded_RAS_weapon );
     data.read( "shifting_view", actor.shifting_view );
     data.read( "initial_view_offset", actor.initial_view_offset );
     data.read( "aborted", actor.aborted );
     data.read( "reload_requested", actor.reload_requested );
     data.read( "abort_if_no_targets", actor.abort_if_no_targets );
     return actor.clone();
 }
References abort_if_no_targets, aborted, action, aif_duration, aim_activity_actor(), aiming_at_critter, clone(), fake_weapon, fin_trajectory, first_turn, JsonValue::get_object(), initial_view_offset, loaded_RAS_weapon, JsonObject::read(), reload_requested, shifting_view, and snap_to_target.
do_turn()
void aim_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 315 of file activity_actor.cpp.
 {
     if( !who.is_avatar() ) {
         debugmsg( "ACT_AIM not implemented for NPCs" );
         aborted = true;
         act.moves_left = 0;
         return;
     }
     avatar &you = get_avatar();
     item_location weapon = get_weapon();
     if( !weapon || !avatar_action::can_fire_weapon( you, get_map(), *weapon ) ) {
         aborted = true;
         act.moves_left = 0;
         return;
     }
     gun_mode gun = weapon->gun_current_mode();
     // We need to make sure RAS weapon is loaded/reloaded in case the aim activity was temp. suspended
     // therefore the order of evaluation matters here
     if( gun->has_flag( flag_RELOAD_AND_SHOOT ) && !gun->ammo_remaining() && !load_RAS_weapon() &&
         first_turn ) {
         aborted = true;
         act.moves_left = 0;
         return;
     }
     if( gun->has_flag( json_flag_ALWAYS_AIMED ) ) {
         you.recoil = 0;
     }
     g->temp_exit_fullscreen();
     target_handler::trajectory trajectory = target_handler::mode_fire( you, *this );
     g->reenter_fullscreen();
     if( aborted ) {
         act.moves_left = 0;
     } else {
         if( !trajectory.empty() ) {
             fin_trajectory = trajectory;
             act.moves_left = 0;
         }
         // If aborting on the first turn, keep 'first_turn' as 'true'.
         // This allows refunding moves spent on unloading RELOAD_AND_SHOOT weapons
         // to simulate avatar not loading them in the first place
         first_turn = false;
         // Allow interrupting activity only during 'aim and fire'.
         // Prevents '.' key for 'aim for 10 turns' from conflicting with '.' key for 'interrupt activity'
         // in case of high input lag (curses, sdl sometimes...), but allows to interrupt aiming
         // if a bug happens / stars align to cause an endless aiming loop.
         act.interruptable_with_kb = action != "AIM";
     }
 }
References aborted, act, action, avatar_action::can_fire_weapon(), debugmsg, fin_trajectory, first_turn, flag_RELOAD_AND_SHOOT, g, get_avatar(), get_map(), get_weapon(), gun, item::gun_current_mode(), Creature::is_avatar(), json_flag_ALWAYS_AIMED, load_RAS_weapon(), target_handler::mode_fire(), and Character::recoil.
finish()
void aim_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 370 of file activity_actor.cpp.
 {
     act.set_to_null();
     item_location weapon = get_weapon();
     if( !weapon ) {
         restore_view();
         return;
     }
     if( aborted ) {
         unload_RAS_weapon();
         if( reload_requested ) {
             // Reload the gun / select different arrows
             // May assign ACT_RELOAD
             g->reload_wielded( true );
         }
         restore_view();
         return;
     }
     gun_mode gun = weapon->gun_current_mode();
     who.fire_gun( fin_trajectory.back(), gun.qty, *gun );
     if( weapon && weapon->gun_current_mode()->has_flag( flag_RELOAD_AND_SHOOT ) ) {
         // RAS weapons are currently bugged, this is a workaround so bug impact
         // isn't amplified, once #54997 and #50571 are fixed this can be removed.
         restore_view();
         return;
     }
     if( !get_option<bool>( "AIM_AFTER_FIRING" ) ) {
         restore_view();
         return;
     }
     // re-enter aiming UI with same parameters
     aim_activity_actor aim_actor;
     aim_actor.abort_if_no_targets = true;
     aim_actor.fake_weapon = this->fake_weapon;
     aim_actor.initial_view_offset = this->initial_view_offset;
     // if invalid target or it's dead - reset it so a new one is acquired
     shared_ptr_fast<Creature> last_target = who.last_target.lock();
     if( !last_target || last_target->is_dead_state() ) {
         who.last_target.reset();
     }
     who.assign_activity( aim_actor );
 }
References abort_if_no_targets, aborted, act, Character::assign_activity(), fake_weapon, fin_trajectory, Character::fire_gun(), flag_RELOAD_AND_SHOOT, g, get_weapon(), gun, item::gun_current_mode(), item::has_flag(), initial_view_offset, Character::last_target, reload_requested, restore_view(), and unload_RAS_weapon().
get_progress_message()
std::string aim_activity_actor::get_progress_message (const player_activity & act) const inline override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 100 of file activity_actor_definitions.h.
{
             return std::string();
         }
get_type()
activity_id aim_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 88 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_AIM" );
         }
References activity_id.
get_weapon()
item_location aim_activity_actor::get_weapon ()
Definition at line 468 of file activity_actor.cpp.
 {
     if( fake_weapon.has_value() ) {
         // TODO: check if the player lost relevant bionic/mutation
         return item_location( get_player_character(), &fake_weapon.value() );
     } else {
         // Check for lost gun (e.g. yanked by zombie technician)
         // TODO: check that this is the same gun that was used to start aiming
         return get_player_character().get_wielded_item();
     }
 }
References fake_weapon, get_player_character(), and Character::get_wielded_item().
Referenced by do_turn(), finish(), load_RAS_weapon(), and unload_RAS_weapon().
load_RAS_weapon()
bool aim_activity_actor::load_RAS_weapon ()
Definition at line 492 of file activity_actor.cpp.
 {
     // TODO: use activity for fetching ammo and loading weapon
     Character &you = get_avatar();
     item_location weapon = get_weapon();
     gun_mode gun = weapon->gun_current_mode();
     // selected gun_mode might come from a gunmod
     item_location used_gun = &*gun != &*weapon ? item_location( weapon, &*gun ) : weapon;
     const auto ammo_location_is_valid = [&]() -> bool {
         if( !you.ammo_location )
         {
             return false;
         }
         if( !gun->can_reload_with( *you.ammo_location.get_item(), false ) )
         {
             return false;
         }
         if( square_dist( you.pos(), you.ammo_location.position() ) > 1 )
         {
             return false;
         }
         return true;
     };
     item::reload_option opt = ammo_location_is_valid() ? item::reload_option( &you, weapon,
                               you.ammo_location ) : you.select_ammo( used_gun );
     if( !opt ) {
         // Menu canceled
         return false;
     }
     int reload_time = 0;
     reload_time += opt.moves();
     if( !gun->reload( you, std::move( opt.ammo ), 1 ) ) {
         // Reload not allowed
         return false;
     }
     // Burn 0.6% max base stamina without cardio/BMI factored in x the strength required to fire.
     you.burn_energy_arms( gun->get_min_str() * static_cast<int>( 0.006f *
                           get_option<int>( "PLAYER_MAX_STAMINA_BASE" ) ) );
     // At low stamina levels, firing starts getting slow.
     int sta_percent = ( 100 * you.get_stamina() ) / you.get_stamina_max();
     reload_time += ( sta_percent < 25 ) ? ( ( 25 - sta_percent ) * 2 ) : 0;
     you.mod_moves( -reload_time );
     loaded_RAS_weapon = true;
     return true;
 }
References item::reload_option::ammo, Character::ammo_location, Character::burn_energy_arms(), get_avatar(), item_location::get_item(), Character::get_stamina(), Character::get_stamina_max(), get_weapon(), gun, item::gun_current_mode(), loaded_RAS_weapon, Creature::mod_moves(), item::reload_option::moves(), Creature::pos(), item_location::position(), Character::select_ammo(), and square_dist().
Referenced by do_turn().
restore_view()
void aim_activity_actor::restore_view () const
Definition at line 481 of file activity_actor.cpp.
 {
     avatar &player_character = get_avatar();
     bool changed_z = player_character.view_offset.z != initial_view_offset.z;
     player_character.view_offset = initial_view_offset;
     if( changed_z ) {
         get_map().invalidate_map_cache( player_character.view_offset.z );
         g->invalidate_main_ui_adaptor();
     }
 }
References g, get_avatar(), get_map(), initial_view_offset, map::invalidate_map_cache(), Character::view_offset, and tripoint::z.
Referenced by canceled(), and finish().
serialize()
void aim_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 424 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "fake_weapon", fake_weapon );
     jsout.member( "fin_trajectory", fin_trajectory );
     jsout.member( "first_turn", first_turn );
     jsout.member( "action", action );
     jsout.member( "aif_duration", aif_duration );
     jsout.member( "aiming_at_critter", aiming_at_critter );
     jsout.member( "snap_to_target", snap_to_target );
     jsout.member( "loaded_RAS_weapon", loaded_RAS_weapon );
     jsout.member( "shifting_view", shifting_view );
     jsout.member( "initial_view_offset", initial_view_offset );
     jsout.member( "aborted", aborted );
     jsout.member( "reload_requested", reload_requested );
     jsout.member( "abort_if_no_targets", abort_if_no_targets );
     jsout.end_object();
 }
References abort_if_no_targets, aborted, action, aif_duration, aiming_at_critter, JsonOut::end_object(), fake_weapon, fin_trajectory, first_turn, initial_view_offset, loaded_RAS_weapon, JsonOut::member(), reload_requested, shifting_view, snap_to_target, and JsonOut::start_object().
start()
void aim_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 308 of file activity_actor.cpp.
 {
     // Time spent on aiming is determined on the go by the player
     act.moves_total = 1;
     act.moves_left = 1;
 }
References act.
unload_RAS_weapon()
void aim_activity_actor::unload_RAS_weapon ()
Definition at line 540 of file activity_actor.cpp.
 {
     // Unload reload-and-shoot weapons to avoid leaving bows pre-loaded with arrows
     avatar &you = get_avatar();
     item_location weapon = get_weapon();
     if( !weapon || !loaded_RAS_weapon ) {
         return;
     }
     gun_mode gun = weapon->gun_current_mode();
     if( gun->has_flag( flag_RELOAD_AND_SHOOT ) ) {
         int moves_before_unload = you.get_moves();
         // Note: this code works only for avatar
         item_location loc = item_location( you, gun.target );
         you.unload( loc, true );
         // Give back time for unloading as essentially nothing has been done.
         if( first_turn ) {
             you.set_moves( moves_before_unload );
         }
     }
     loaded_RAS_weapon = false;
 }
References first_turn, flag_RELOAD_AND_SHOOT, get_avatar(), Creature::get_moves(), get_weapon(), gun, item::gun_current_mode(), loaded_RAS_weapon, Creature::set_moves(), and Character::unload().
Referenced by canceled(), and finish().
use_bionic()
aim_activity_actor aim_activity_actor::use_bionic (const item & fake_gun) static
Aiming fake gun provided by a bionic.
Definition at line 294 of file activity_actor.cpp.
 {
     aim_activity_actor act = aim_activity_actor();
     act.fake_weapon = fake_gun;
     return act;
 }
References act, and aim_activity_actor().
Referenced by avatar_action::fire_ranged_bionic().
use_mutation()
aim_activity_actor aim_activity_actor::use_mutation (const item & fake_gun) static
Aiming fake gun provided by a mutation.
Definition at line 301 of file activity_actor.cpp.
 {
     aim_activity_actor act = aim_activity_actor();
     act.fake_weapon = fake_gun;
     return act;
 }
References act, and aim_activity_actor().
Referenced by avatar_action::fire_ranged_mutation().
use_wielded()
aim_activity_actor aim_activity_actor::use_wielded () static
Aiming wielded gun.
Definition at line 289 of file activity_actor.cpp.
 {
     return aim_activity_actor();
 }
References aim_activity_actor().
Referenced by avatar_action::fire_wielded_weapon().
Member Data Documentation
abort_if_no_targets
bool aim_activity_actor::abort_if_no_targets = false
if true abort if no targets are available when re-entering aiming ui after shooting
Definition at line 63 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), target_ui::run(), and serialize().
aborted
bool aim_activity_actor::aborted = false
Target UI requested to abort aiming.
Definition at line 61 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), finish(), target_ui::run(), and serialize().
acceptable_losses
std::vector<weak_ptr_fast<Creature> > aim_activity_actor::acceptable_losses
A friendly creature may enter line of fire during aim-and-shoot, and that generates a warning to proceed/abort.
If player decides to proceed, that creature is saved in this vector to prevent the same warning from popping up on the following turn(s).
Definition at line 75 of file activity_actor_definitions.h.
Referenced by target_ui::prompt_friendlies_in_lof(), and target_ui::run().
action
std::string aim_activity_actor::action
Definition at line 52 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), target_ui::run(), and serialize().
aif_duration
int aim_activity_actor::aif_duration = 0
Definition at line 53 of file activity_actor_definitions.h.
Referenced by deserialize(), target_ui::run(), and serialize().
aiming_at_critter
bool aim_activity_actor::aiming_at_critter = false
Definition at line 54 of file activity_actor_definitions.h.
Referenced by deserialize(), target_ui::run(), and serialize().
fake_weapon
std::optional<item> aim_activity_actor::fake_weapon private
Definition at line 47 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), get_weapon(), and serialize().
fin_trajectory
std::vector<tripoint> aim_activity_actor::fin_trajectory private
Definition at line 48 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), finish(), and serialize().
first_turn
bool aim_activity_actor::first_turn = true
Definition at line 51 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), target_ui::run(), serialize(), and unload_RAS_weapon().
initial_view_offset
tripoint aim_activity_actor::initial_view_offset
Definition at line 59 of file activity_actor_definitions.h.
Referenced by aim_activity_actor(), deserialize(), finish(), restore_view(), and serialize().
loaded_RAS_weapon
bool aim_activity_actor::loaded_RAS_weapon = false
Not to try to unload RELOAD_AND_SHOOT weapon if it is not loaded.
Definition at line 57 of file activity_actor_definitions.h.
Referenced by deserialize(), load_RAS_weapon(), serialize(), and unload_RAS_weapon().
reload_requested
bool aim_activity_actor::reload_requested = false
Target UI requested to abort aiming and reload weapon Implies aborted = true.
Definition at line 68 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), target_ui::run(), and serialize().
shifting_view
bool aim_activity_actor::shifting_view = false
Definition at line 58 of file activity_actor_definitions.h.
Referenced by deserialize(), target_ui::run(), and serialize().
snap_to_target
bool aim_activity_actor::snap_to_target = false
Definition at line 55 of file activity_actor_definitions.h.
Referenced by deserialize(), target_ui::run(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp