Cataclysm DDA: link_up_actor Class Reference
link_up_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
std::optional< int > link_to_veh_app (Character *p, item &it, bool to_ports) const
std::optional< int > link_tow_cable (Character *p, item &it, bool to_towing) const
std::optional< int > link_extend_cable (Character *p, item &it, const tripoint &pnt) const
std::optional< int > remove_extensions (Character *p, item &it) const
link_up_actor ()
~link_up_actor () override=default
void load (const JsonObject &jo) override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
std::string get_name () const override
Returns the translated name of the action.
void info (const item &, std::vector< iteminfo > &) const override
std::optional< int > use (Character *p, item &it, const tripoint &pnt) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
int cable_length = -1
Maximum length of the cable.
units::power charge_rate = 0_W
Charge rate in watts.
float efficiency = 0.85f
(this) out of 1.0 chance to successfully add 1 charge every charge interval
int move_cost = 5
(Optional) The move cost to attach the cable.
translation menu_text
(Optional) Text displayed in the activation screen, defaults to "Plug in / Manage cables".
std::set< link_state > targets = { link_state::no_link, link_state::vehicle_port }
std::set< std::string > can_extend = {}
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1076 of file iuse_actor.h.
Constructor & Destructor Documentation
link_up_actor()
link_up_actor::link_up_actor () inline
Definition at line 1098 of file iuse_actor.h.
 : iuse_actor( "link_up" ) {}
~link_up_actor()
link_up_actor::~link_up_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > link_up_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4432 of file iuse_actor.cpp.
 {
     return std::make_unique<link_up_actor>( *this );
 }
get_name()
std::string link_up_actor::get_name () const override virtual
Returns the translated name of the action.
It is used for the item action menu.
Reimplemented from iuse_actor.
Definition at line 4437 of file iuse_actor.cpp.
 {
     if( !menu_text.empty() ) {
         return menu_text.translated();
     }
     return iuse_actor::get_name();
 }
References iuse_actor::get_name().
info()
void link_up_actor::info (const item & it, std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 4445 of file iuse_actor.cpp.
 {
     std::vector<std::string> targets_strings;
     bool appliance = false;
     if( targets.count( link_state::vehicle_port ) > 0 ) {
         targets_strings.emplace_back( _( "vehicle controls" ) );
         appliance = true;
     }
     if( targets.count( link_state::vehicle_battery ) > 0 ) {
         targets_strings.emplace_back( _( "vehicle battery" ) );
         appliance = true;
     }
     if( appliance ) {
         targets_strings.emplace_back( _( "appliance" ) );
     }
     if( targets.count( link_state::bio_cable ) > 0 ) {
         targets_strings.emplace_back( _( "bionic" ) );
     }
     if( targets.count( link_state::ups ) > 0 ) {
         targets_strings.emplace_back( _( "UPS" ) );
     }
     if( targets.count( link_state::solarpack ) > 0 ) {
         targets_strings.emplace_back( _( "solar pack" ) );
     }
     if( targets.count( link_state::vehicle_tow ) > 0 ) {
         dump.emplace_back( "TOOL", _( "<bold>Can tow a vehicle</bold>." ) );
     }
     if( !targets_strings.empty() ) {
         std::string targets_string = enumerate_as_string( targets_strings, enumeration_conjunction::or_ );
         dump.emplace_back( "TOOL",
                            string_format( _( "<bold>Can be plugged into</bold>: %s." ), targets_string ) );
     }
     const bool no_extensions = it.cables().empty();
     item dummy( it );
     dummy.update_link_traits();
     std::string length_all_info = string_format( _( "<bold>Cable length</bold>: %d" ),
                                   dummy.max_link_length() );
     std::string length_solo_info = no_extensions ? "" : string_format( _( " (%d without extensions)" ),
                                    cable_length != -1 ? cable_length : dummy.type->maximum_charges() );
     dump.emplace_back( "TOOL", length_all_info, length_solo_info );
     if( charge_rate != 0_W ) {
         //~ Power in Watts. %+4.1f is a 4 digit number with 1 decimal point (ex: 4737.3 W)
         dump.emplace_back( "TOOL", _( "<bold>Wattage</bold>: " ), string_format( _( "%+4.1f W" ),
                            units::to_milliwatt( charge_rate ) / 1000.f ) );
     }
     if( !can_extend.empty() ) {
         std::vector<std::string> cable_types;
         cable_types.reserve( can_extend.size() );
         for( const std::string &cable_type : can_extend ) {
             cable_types.emplace_back( cable_type == "ELECTRICAL_DEVICES" ? _( "electrical device cables" ) :
                                       itype_id( cable_type )->nname( 1 ) );
         }
         std::string cable_type_list = enumerate_as_string( cable_types, enumeration_conjunction::or_ );
         dump.emplace_back( "TOOL", string_format( _( "<bold>Can extend</bold>: %s" ), cable_type_list ) );
     }
 }
References _, bio_cable, item::cables(), enumerate_as_string(), itype_id, item::max_link_length(), itype::maximum_charges(), or_, solarpack, string_format(), units::to_milliwatt(), item::type, item::update_link_traits(), ups, vehicle_battery, vehicle_port, and vehicle_tow.
link_extend_cable()
std::optional< int > link_up_actor::link_extend_cable (Character * p, item & it, const tripoint & pnt) const
Definition at line 4988 of file iuse_actor.cpp.
 {
     avatar *you = p->as_avatar();
     if( !you ) {
         p->add_msg_if_player( m_info, _( "Never mind." ) );
         return std::nullopt;
     }
     const bool is_cable_item = it.has_flag( flag_CABLE_SPOOL );
     item_location selected;
     if( is_cable_item ) {
         const bool can_extend_devices = can_extend.find( "ELECTRICAL_DEVICES" ) != can_extend.end();
         const auto filter = [this, &it, &can_extend_devices]( const item & inv ) {
             if( !inv.can_link_up() || inv.link_has_state( link_state::needs_reeling ) ||
                 ( !inv.has_flag( flag_CABLE_SPOOL ) && !can_extend_devices ) ) {
                 return false;
             }
             return can_extend.find( inv.typeId().c_str() ) != can_extend.end() && &inv != &it;
         };
         selected = game_menus::inv::titled_filter_menu( filter, *you, _( "Extend which cable?" ), -1,
                    _( "You don't have a compatible cable." ) );
     } else {
         const auto filter = []( const item & inv ) {
             if( !inv.can_link_up() || inv.link_has_state( link_state::needs_reeling ) ||
                 !inv.has_flag( flag_CABLE_SPOOL ) ) {
                 return false;
             }
             const link_up_actor *actor = static_cast<const link_up_actor *>
                                          ( inv.get_use( "link_up" )->get_actor_ptr() );
             return actor->can_extend.find( "ELECTRICAL_DEVICES" ) != actor->can_extend.end();
         };
         selected = game_menus::inv::titled_filter_menu( filter, *you, _( "Extend with which cable?" ), -1,
                    _( "You don't have a compatible cable." ) );
     }
     if( !selected ) {
         p->add_msg_if_player( m_info, _( "Never mind." ) );
         return std::nullopt;
     }
     item_location extension = is_cable_item ? form_loc( *p, pnt, it ) : selected;
     item_location extended = is_cable_item ? selected : form_loc( *p, pnt, it );
     std::optional<item> extended_copy;
     // We'll make a copy of the extended item and check pocket weight/volume capacity if:
     //   1. The extended item is in a container,
     //   2. The extended item and extension cord(s) aren't in the same pocket, and
     //   3. The extended item is in a pocket without enough remaining room for the extension cord(s).
     if( extended.where() == item_location::type::container &&
         extended.parent_pocket() != extension.parent_pocket() &&
         ( extended.volume_capacity() - extension->volume() < 0_ml ||
           extended.weight_capacity() - extension->weight() < 0_gram ) ) {
         extended_copy = *extended;
     }
     item *extended_ptr = extended_copy ? &extended_copy.value() : &*extended;
     // Put the extension cable and all of its attached cables, if any, into the extended item's CABLE pocket.
     std::vector<const item *> all_cables = extension->cables();
     all_cables.emplace_back( &*extension );
     for( const item *cable : all_cables ) {
         item cable_copy( *cable );
         cable_copy.get_contents().clear_items();
         cable_copy.reset_link();
         if( !extended_ptr->put_in( cable_copy, pocket_type::CABLE ).success() ) {
             debugmsg( "Failed to put %s inside %s!", cable_copy.type_name(), extended_ptr->type_name() );
         }
     }
     if( extension->has_link_data() ) {
         extended_ptr->link() = extension->link();
     }
     extended_ptr->update_link_traits();
     extended_ptr->process( get_map(), p, p->pos() );
     if( extended_copy ) {
         // Check if there's another pocket on the same container that can hold the extended item, respecting pocket settings.
         item_location parent = extended.parent_item();
         if( parent->can_contain( *extended_ptr, false, false, false, false,
                                  item_location(), 10000000_ml, false ).success() ) {
             if( !parent->put_in( *extended_ptr, pocket_type::CONTAINER ).success() ) {
                 debugmsg( "Failed to put %s inside %s!", extended_ptr->type_name(),
                           parent->type_name() );
                 return std::nullopt;
             }
         } else {
             if( !query_yn( _( "The %1$s can't contain the %2$s with the %3$s attached.  Continue?" ),
                            parent->type_name(), extended_ptr->type_name(), extension->type_name() ) ) {
                 return std::nullopt;
             }
             // Attach the cord, even though it won't fit, and let it spill out naturally.
             extended.parent_pocket()->add( *extended_ptr );
         }
         extended.make_active();
         extended.remove_item();
     }
     p->add_msg_if_player( _( "You extend the %1$s with the %2$s." ),
                           extended_ptr->link_name(), extension->type_name() );
     extension.remove_item();
     p->invalidate_inventory_validity_cache();
     p->drop_invalid_inventory();
     p->mod_moves( -move_cost );
     return 0;
 }
References _, item_pocket::add(), Character::add_msg_if_player(), Creature::as_avatar(), CABLE, item::cables(), item::can_contain(), can_extend, item_contents::clear_items(), item_location::container, CONTAINER, debugmsg, Character::drop_invalid_inventory(), filter, flag_CABLE_SPOOL, form_loc(), item::get_contents(), get_map(), item::has_flag(), item::has_link_data(), Character::invalidate_inventory_validity_cache(), item::link(), item::link_name(), m_info, item_location::make_active(), Creature::mod_moves(), move_cost, needs_reeling, item_location::parent_item(), item_location::parent_pocket(), Creature::pos(), item::process(), item::put_in(), query_yn(), item_location::remove_item(), item::reset_link(), ret_val_common::success(), game_menus::inv::titled_filter_menu(), item::type_name(), item::update_link_traits(), item::volume(), item_location::volume_capacity(), item::weight(), item_location::weight_capacity(), and item_location::where().
link_to_veh_app()
std::optional< int > link_up_actor::link_to_veh_app (Character * p, item & it, bool to_ports) const
Definition at line 4823 of file iuse_actor.cpp.
 {
     map &here = get_map();
     // Selection: Attach electrical cable to vehicle ports / appliances, OR vehicle batteries.
     const auto can_link = [&here, &to_ports]( const tripoint & point ) {
         const optional_vpart_position ovp = here.veh_at( point );
         return ovp && ovp->vehicle().avail_linkable_part( ovp->mount(), to_ports ) != -1;
     };
     const std::optional<tripoint> pnt_ = choose_adjacent_highlight( _( "Attach the cable where?" ),
                                          "", can_link, false, false );
     if( !pnt_ ) {
         p->add_msg_if_player( _( "Never mind." ) );
         return std::nullopt;
     }
     const tripoint &selection = *pnt_;
     const optional_vpart_position sel_vp = here.veh_at( selection );
     if( !sel_vp ) {
         p->add_msg_if_player( _( "There's no vehicle there." ) );
         return std::nullopt;
     }
     // You used to be able to plug cables in anywhere on a vehicle, so there's extra effort here
     // to inform players that they can only plug them into dashboards or electrical controls now.
     if( !can_link( selection ) ) {
         if( to_ports && sel_vp && sel_vp->vehicle().has_part( "CABLE_PORTS" ) ) {
             p->add_msg_if_player( m_info,
                                   _( "You can't attach it there - try the dashboard or electronics controls." ) );
         } else if( !to_ports && sel_vp && !sel_vp->vehicle().batteries.empty() ) {
             p->add_msg_if_player( m_info,
                                   _( "You can't attach it there - try the battery." ) );
         } else {
             p->add_msg_if_player( m_info, _( "You can't attach it there." ) );
         }
         return std::nullopt;
     }
     if( !it.link_has_state( link_state::vehicle_port ) &&
         !it.link_has_state( link_state::vehicle_battery ) ) {
         // Starting a new connection to a vehicle or connecting a cable CBM to a vehicle.
         bool had_bio_link = it.link_has_state( link_state::bio_cable );
         ret_val<void> result = it.link_to( sel_vp, to_ports ? link_state::vehicle_port :
                                            link_state::vehicle_battery );
         if( !result.success() ) {
             p->add_msg_if_player( m_bad, result.str() );
             return 0;
         }
         // Get the part name for the connection message, using the vehicle name as a fallback.
         const int part_index = sel_vp->vehicle().avail_linkable_part( sel_vp->mount(), to_ports );
         const std::string sel_vp_name = part_index == -1 ? sel_vp->vehicle().name :
                                         sel_vp->vehicle().part( part_index ).name( false );
         if( had_bio_link ) {
             p->add_msg_if_player( m_good, _( "You are now plugged into the %s." ), sel_vp_name );
             it.link().source = link_state::bio_cable;
         } else {
             p->add_msg_if_player( _( "You connect the %1$s to the %2$s." ), it.type_name(), sel_vp_name );
         }
         it.process( here, p, p->pos() );
         p->mod_moves( -move_cost );
         return 0;
     } else {
         // Connecting two vehicles together.
         const bool using_power_cord = it.typeId() == itype_power_cord;
         if( using_power_cord && it.link().t_veh->is_powergrid() && sel_vp->vehicle().is_powergrid() ) {
             // If both vehicles are adjacent power grids, try to merge them together first.
             const point prev_pos = here.bub_from_abs( it.link().t_veh->coord_translate( it.link().t_mount ) +
                                    it.link().t_abs_pos ).xy().raw();
             if( selection.xy().distance( prev_pos ) <= 1.5f &&
                 it.link().t_veh->merge_appliance_into_grid( sel_vp->vehicle() ) ) {
                 it.link().t_veh->part_removal_cleanup();
                 p->add_msg_if_player( _( "You merge the two power grids." ) );
                 return 1;
             }
             // Unable to merge, so connect them with a power cord instead.
         }
         ret_val<void> result = it.link_to( sel_vp, to_ports ? link_state::vehicle_port :
                                            link_state::vehicle_battery );
         if( !result.success() ) {
             p->add_msg_if_player( m_bad, result.str() );
             return 0;
         }
         if( using_power_cord || p->has_item( it ) ) {
             p->add_msg_if_player( m_good, result.str() );
         }
         if( using_power_cord ) {
             // Remove linked_flag from attached parts - the just-added cable vehicle parts do the same thing.
             it.reset_link( true, p );
         }
         p->mod_moves( -move_cost );
         return 1; // Let the cable be destroyed.
     }
 }
References _, Character::add_msg_if_player(), bio_cable, map::bub_from_abs(), choose_adjacent_highlight(), vehicle::coord_translate(), point::distance(), get_map(), visitable::has_item(), vehicle::is_powergrid(), itype_power_cord, item::link(), item::link_has_state(), item::link_to(), m_bad, m_good, m_info, vehicle::merge_appliance_into_grid(), Creature::mod_moves(), move_cost, vehicle::part_removal_cleanup(), point, Creature::pos(), item::process(), item::reset_link(), item::link_data::source, ret_val_common::str(), ret_val_common::success(), item::link_data::t_abs_pos, item::link_data::t_mount, item::link_data::t_veh, item::type_name(), item::typeId(), map::veh_at(), vehicle_battery, vehicle_port, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and tripoint::xy().
link_tow_cable()
std::optional< int > link_up_actor::link_tow_cable (Character * p, item & it, bool to_towing) const
Definition at line 4924 of file iuse_actor.cpp.
 {
     map &here = get_map();
     const auto can_link = [&here]( const tripoint & point ) {
         const optional_vpart_position ovp = here.veh_at( point );
         return ovp && ovp->vehicle().is_external_part( point );
     };
     const std::optional<tripoint> pnt_ = choose_adjacent_highlight(
             to_towing ? _( "Attach cable to the vehicle that will do the towing." ) :
             _( "Attach cable to the vehicle that will be towed." ), "", can_link, false, false );
     if( !pnt_ ) {
         p->add_msg_if_player( _( "Never mind." ) );
         return std::nullopt;
     }
     const tripoint &selection = *pnt_;
     const optional_vpart_position sel_vp = here.veh_at( selection );
     if( !sel_vp ) {
         p->add_msg_if_player( _( "There's no vehicle there." ) );
         return std::nullopt;
     }
     if( it.has_no_links() ) {
         // Starting a new tow cable connection.
         ret_val<void> result = it.link_to( sel_vp, link_state::vehicle_tow );
         if( !result.success() ) {
             p->add_msg_if_player( m_bad, result.str() );
             return 0;
         }
         if( to_towing ) {
             it.link().source = link_state::vehicle_tow;
             it.link().target = link_state::no_link;
         } else {
             it.link().source = link_state::no_link;
             it.link().target = link_state::vehicle_tow;
         }
         p->add_msg_if_player( _( "You connect the %1$s to the %2$s." ), it.type_name(),
                               sel_vp->vehicle().name );
         it.process( here, p, p->pos() );
         p->mod_moves( -move_cost );
         return 0;
     } else {
         // Connecting two vehicles with tow cable.
         ret_val<void> result = it.link_to( sel_vp, link_state::vehicle_tow );
         if( !result.success() ) {
             p->add_msg_if_player( m_bad, result.str() );
             return 0;
         }
         if( p->has_item( it ) ) {
             p->add_msg_if_player( m_good, result.str() );
         }
         p->mod_moves( -move_cost );
         return 1; // Let the cable be destroyed.
     }
 }
References _, Character::add_msg_if_player(), choose_adjacent_highlight(), get_map(), visitable::has_item(), item::has_no_links(), item::link(), item::link_to(), m_bad, m_good, Creature::mod_moves(), move_cost, no_link, point, Creature::pos(), item::process(), item::link_data::source, ret_val_common::str(), ret_val_common::success(), item::link_data::target, item::type_name(), map::veh_at(), and vehicle_tow.
load()
void link_up_actor::load (const JsonObject & jo) override virtual
Implements iuse_actor.
Definition at line 4421 of file iuse_actor.cpp.
 {
     jo.read( "cable_length", cable_length );
     jo.read( "charge_rate", charge_rate );
     jo.read( "efficiency", efficiency );
     jo.read( "move_cost", move_cost );
     jo.read( "menu_text", menu_text );
     jo.read( "targets", targets );
     jo.read( "can_extend", can_extend );
 }
References move_cost, and JsonObject::read().
remove_extensions()
std::optional< int > link_up_actor::remove_extensions (Character * p, item & it) const
Definition at line 5094 of file iuse_actor.cpp.
 {
     std::list<item *> all_cables = it.all_items_ptr( pocket_type::CABLE );
     all_cables.remove_if( []( const item * cable ) {
         return !cable->has_flag( flag_CABLE_SPOOL ) || !cable->can_link_up();
     } );
     if( all_cables.empty() ) {
         // Delete any non-cables that somehow got into the pocket.
         it.get_contents().clear_pockets_if( []( item_pocket const & pocket ) {
             return pocket.is_type( pocket_type::CABLE );
         } );
         return 0;
     }
     item cable_main_copy( *all_cables.back() );
     all_cables.pop_back();
     if( !all_cables.empty() ) {
         for( item *cable : all_cables ) {
             item cable_copy( *cable );
             cable_copy.get_contents().clear_items();
             cable_copy.reset_link();
             if( !cable_main_copy.put_in( cable_copy, pocket_type::CABLE ).success() ) {
                 debugmsg( "Failed to put %s inside %s!", cable_copy.tname(), cable_main_copy.tname() );
             }
         }
     }
     p->add_msg_if_player( _( "You disconnect the %1$s from the %2$s." ),
                           cable_main_copy.type_name(), it.type_name() );
     it.get_contents().clear_pockets_if( []( item_pocket const & pocket ) {
         return pocket.is_type( pocket_type::CABLE );
     } );
     if( it.has_link_data() ) {
         // If the item was linked, keep the extension cables linked.
         cable_main_copy.link() = it.link();
         cable_main_copy.update_link_traits();
         cable_main_copy.process( get_map(), p, p->pos() );
         it.reset_link( true, p );
     }
     p->i_add_or_drop( cable_main_copy );
     p->mod_moves( -move_cost );
     return 0;
 }
References _, Character::add_msg_if_player(), item::all_items_ptr(), CABLE, item::can_link_up(), item_contents::clear_items(), item_contents::clear_pockets_if(), debugmsg, flag_CABLE_SPOOL, item::get_contents(), get_map(), item::has_flag(), item::has_link_data(), Character::i_add_or_drop(), item_pocket::is_type(), item::link(), Creature::mod_moves(), move_cost, Creature::pos(), item::process(), item::put_in(), item::reset_link(), ret_val_common::success(), item::tname(), item::type_name(), and item::update_link_traits().
use()
std::optional< int > link_up_actor::use (Character * p, item & it, const tripoint & pnt) const override virtual
Implements iuse_actor.
Definition at line 4506 of file iuse_actor.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action link_up that requires character but no character is present",
                   it.typeId().str() );
         return std::nullopt;
     }
     if( targets.empty() ) {
         debugmsg( "Link up action for %s doesn't have any targets!", it.tname() );
         return std::nullopt;
     }
     const bool is_cable_item = it.has_flag( flag_CABLE_SPOOL );
     const bool unspooled = it.link_length() == -1;
     const bool has_loose_end = !unspooled && is_cable_item ?
                                it.link_has_state( link_state::no_link ) : it.has_no_links();
     const int respool_time_per_square = 200;
     const bool past_respool_threshold = it.link_length() > item::LINK_RESPOOL_THRESHOLD;
     const int respool_time_total = !past_respool_threshold ? 0 :
                                    ( it.link_length() - item::LINK_RESPOOL_THRESHOLD ) * respool_time_per_square;
     vehicle *t_veh = it.has_link_data() ? it.link().t_veh.get() : nullptr;
     uilist link_menu;
     if( !is_cable_item || it.has_no_links() ) {
         // This is either a device or a cable item without any connections.
         link_menu.text = string_format( _( "What to do with the %s?%s" ), it.link_name(), t_veh ?
                                         string_format( _( "\nAttached to: %s" ), t_veh->name ) : "" );
         if( targets.count( link_state::vehicle_port ) > 0 ) {
             link_menu.addentry( 0, has_loose_end, -1, _( "Attach to vehicle controls or appliance" ) );
         }
         if( targets.count( link_state::vehicle_battery ) > 0 ) {
             link_menu.addentry( 1, has_loose_end, -1, _( "Attach to vehicle battery or appliance" ) );
         }
         if( targets.count( link_state::vehicle_tow ) > 0 ) {
             link_menu.addentry( 10, has_loose_end, -1, _( "Attach tow cable to towing vehicle" ) );
             link_menu.addentry( 11, has_loose_end, -1, _( "Attach tow cable to towed vehicle" ) );
         }
         if( targets.count( link_state::bio_cable ) > 0 ) {
             if( !p->get_remote_fueled_bionic().is_empty() ) {
                 link_menu.addentry( 20, has_loose_end, -1, _( "Attach to Cable Charger System CBM" ) );
             }
         }
         if( targets.count( link_state::ups ) > 0 && p->cache_has_item_with( flag_IS_UPS ) ) {
             link_menu.addentry( 21, has_loose_end, -1, _( "Attach to UPS" ) );
         }
         if( targets.count( link_state::solarpack ) > 0 ) {
             const bool has_solar_pack_on = p->worn_with_flag( flag_SOLARPACK_ON );
             if( has_solar_pack_on || p->worn_with_flag( flag_SOLARPACK ) ) {
                 link_menu.addentry( 22, has_loose_end && has_solar_pack_on, -1, _( "Attach to solar pack" ) );
             }
         }
         if( !is_cable_item || !can_extend.empty() ) {
             const bool has_extensions = !unspooled &&
                                         !it.all_items_top( pocket_type::CABLE ).empty();
             link_menu.addentry( 30, has_loose_end, -1,
                                 is_cable_item ? _( "Extend another cable" ) : _( "Extend with another cable" ) );
             link_menu.addentry( 31, has_extensions, -1, _( "Remove cable extensions" ) );
         }
         if( targets.count( link_state::no_link ) > 0 ) {
             if( unspooled ) {
                 link_menu.addentry( 998, true, -1, _( "Re-spool" ) );
             } else {
                 link_menu.addentry( 999, !it.has_no_links(), -1,
                                     past_respool_threshold ? _( "Detach and re-spool" ) : _( "Detach" ) );
             }
         }
     } else if( it.link_has_state( link_state::vehicle_tow ) ) {
         // Cables that started a tow can finish one or detach; nothing else.
         link_menu.text = string_format( _( "What to do with the %s?%s" ), it.link_name(), t_veh ?
                                         string_format( _( "\nAttached to: %s" ), t_veh->name ) : "" );
         link_menu.addentry( 10, has_loose_end && it.link().target == link_state::vehicle_tow, -1,
                             _( "Attach loose end to towing vehicle" ) );
         link_menu.addentry( 11, has_loose_end && it.link().source == link_state::vehicle_tow, -1,
                             _( "Attach loose end to towed vehicle" ) );
         if( targets.count( link_state::no_link ) > 0 ) {
             if( unspooled ) {
                 link_menu.addentry( 998, true, -1, _( "Re-spool" ) );
             } else {
                 link_menu.addentry( 999, true, -1,
                                     past_respool_threshold ? _( "Detach and re-spool" ) : _( "Detach" ) );
             }
         }
     } else {
         // This is a cable item with at least one connection already:
         std::string state_desc_lhs;
         std::string state_desc_rhs;
         if( it.link_has_state( link_state::no_link ) ) {
             state_desc_lhs = _( "\nAttached to " );
             if( t_veh ) {
                 state_desc_rhs = it.link().t_veh->name;
             } else if( it.link_has_state( link_state::bio_cable ) ) {
                 state_desc_rhs = _( "Cable Charger System" );
             } else if( it.link_has_state( link_state::ups ) ) {
                 state_desc_rhs = _( "Unified Power Supply" );
             } else if( it.link_has_state( link_state::solarpack ) ) {
                 state_desc_rhs = _( "solar backpack" );
             }
         } else {
             if( it.link().source ==  link_state::bio_cable ) {
                 state_desc_lhs = _( "\nConnecting Cable Charger System to " );
             } else if( it.link().source == link_state::ups ) {
                 state_desc_lhs = _( "\nConnecting UPS to " );
             } else if( it.link().source == link_state::solarpack ) {
                 state_desc_lhs = _( "\nConnecting solar backpack to " );
             }
             if( it.link().t_veh ) {
                 state_desc_rhs = it.link().t_veh->name;
             } else if( it.link().target == link_state::bio_cable ) {
                 state_desc_rhs = _( "Cable Charger System" );
             }
         }
         link_menu.text = string_format( _( "What to do with the %s?%s%s" ), it.link_name(),
                                         state_desc_lhs, state_desc_rhs );
         // TODO: Allow plugging UPSes and Solar Packs into more than just bionics.
         // There is already code to support setting up a link, but none for actual functionality.
         if( targets.count( link_state::vehicle_port ) > 0 ) {
             link_menu.addentry( 0, has_loose_end && !it.link_has_state( link_state::ups ) &&
                                 !it.link_has_state( link_state::solarpack ),
                                 -1, _( "Attach loose end to vehicle controls or appliance" ) );
         }
         if( targets.count( link_state::vehicle_battery ) > 0 ) {
             link_menu.addentry( 1, has_loose_end && !it.link_has_state( link_state::ups ) &&
                                 !it.link_has_state( link_state::solarpack ),
                                 -1, _( "Attach loose end to vehicle battery or appliance" ) );
         }
         if( targets.count( link_state::bio_cable ) > 0 && !p->get_remote_fueled_bionic().is_empty() ) {
             link_menu.addentry( 20, has_loose_end && !it.link_has_state( link_state::bio_cable ),
                                 -1, _( "Attach loose end to Cable Charger System CBM" ) );
         }
         if( targets.count( link_state::ups ) > 0 && p->cache_has_item_with( flag_IS_UPS ) ) {
             link_menu.addentry( 21, has_loose_end && it.link_has_state( link_state::bio_cable ),
                                 -1, _( "Attach loose end to UPS" ) );
         }
         if( targets.count( link_state::solarpack ) > 0 ) {
             const bool has_solar_pack_on = p->worn_with_flag( flag_SOLARPACK_ON );
             if( has_solar_pack_on || p->worn_with_flag( flag_SOLARPACK ) ) {
                 link_menu.addentry( 22, has_loose_end && has_solar_pack_on &&
                                     it.link_has_state( link_state::bio_cable ),
                                     -1, _( "Attach loose end to solar pack" ) );
             }
         }
         if( !can_extend.empty() ) {
             const bool has_extensions = !unspooled &&
                                         !it.all_items_top( pocket_type::CABLE ).empty();
             link_menu.addentry( 30, has_loose_end, -1, _( "Extend another cable" ) );
             link_menu.addentry( 31, has_extensions, -1, _( "Remove cable extensions" ) );
         }
         if( targets.count( link_state::no_link ) > 0 ) {
             if( unspooled ) {
                 link_menu.addentry( 998, true, -1, _( "Re-spool" ) );
             } else {
                 link_menu.addentry( 999, true, -1,
                                     past_respool_threshold ? _( "Detach and re-spool" ) : _( "Detach" ) );
             }
         }
     }
     int choice = -1;
     if( targets.size() == 1 ) {
         choice = link_menu.entries.begin()->retval;
     } else {
         link_menu.query();
         choice = link_menu.ret;
     }
     if( choice < 0 ) {
         // Cancelled selection.
         return std::nullopt;
     } else if( choice >= 998 ) {
         // Selection: Detach & respool.
         // Reopen the menu after respooling.
         p->assign_activity( invoke_item_activity_actor( item_location{*p, &it}, "link_up" ) );
         p->activity.auto_resume = true;
         if( t_veh ) {
             // Cancel out the linked device's power draw so the vehicle's power display will be accurate.
             int power_draw = it.charge_linked_batteries( *t_veh, 0 );
             t_veh->linked_item_epower_this_turn += units::from_milliwatt( power_draw );
         }
         it.reset_link( true, p );
         // Cables that are too long need to be manually rewound before reuse.
         if( it.link_length() == -1 ) {
             p->assign_activity( player_activity( reel_cable_activity_actor( respool_time_total, item_location{*p, &it} ) ) );
             return 0;
         } else {
             p->add_msg_if_player( m_info, string_format( is_cable_item ? _( "You detach the %s." ) :
                                   _( "You gather the %s up with it." ), it.link_name() ) );
         }
         return 0;
     }
     if( choice == 0 || choice == 1 ) {
         // Selection: Attach electrical cable to vehicle ports / appliances, OR vehicle batteries.
         return link_to_veh_app( p, it, choice == 0 );
     } else if( choice == 10 || choice == 11 ) {
         // Selection: Attach tow cable to towing/towed vehicle.
         return link_tow_cable( p, it, choice == 10 );
     } else if( choice == 30 ) {
         // Selection: Attach to another cable, resulting in a longer one.
         return link_extend_cable( p, it, pnt );
     } else if( choice == 31 ) {
         // Selection: Remove all cable extensions and give the individual cables to the player.
         return remove_extensions( p, it );
     }
     map &here = get_map();
     if( choice == 20 ) {
         // Selection: Attach electrical cable to Cable Charger System CBM.
         if( it.has_no_links() ) {
             it.link().target = link_state::bio_cable;
             p->add_msg_if_player( m_info, _( "You attach the cable to your Cable Charger System." ) );
         } else if( it.link().source == link_state::ups ) {
             it.link().target = link_state::bio_cable;
             p->add_msg_if_player( m_good, _( "You are now plugged into the UPS." ) );
         } else if( it.link().source == link_state::solarpack ) {
             it.link().target = link_state::bio_cable;
             p->add_msg_if_player( m_good, _( "You are now plugged into the solar backpack." ) );
         } else if( it.link().target == link_state::vehicle_port ||
                    it.link().target == link_state::vehicle_battery ) {
             it.link().source = link_state::bio_cable;
             p->add_msg_if_player( m_good, _( "You are now plugged into the vehicle." ) );
         }
         it.update_link_traits();
         it.process( here, p, p->pos() );
         p->mod_moves( -move_cost );
         return 0;
     } else if( choice == 21 ) {
         // Selection: Attach electrical cable to ups.
         item_location loc;
         avatar *you = p->as_avatar();
         const std::string choose_ups = _( "Choose UPS:" );
         const std::string dont_have_ups = _( "You need an active UPS." );
         auto ups_filter = [&]( const item & itm ) {
             return itm.has_flag( flag_IS_UPS );
         };
         if( you != nullptr ) {
             loc = game_menus::inv::titled_filter_menu( ups_filter, *you, choose_ups, -1, dont_have_ups );
         }
         if( !loc ) {
             p->add_msg_if_player( _( "Never mind." ) );
             return std::nullopt;
         }
         if( it.has_no_links() ) {
             p->add_msg_if_player( m_info, _( "You attach the cable to the UPS." ) );
         } else if( it.link().target == link_state::bio_cable ) {
             p->add_msg_if_player( m_good, _( "You are now plugged into the UPS." ) );
         } else if( it.link().source == link_state::solarpack ) {
             p->add_msg_if_player( m_good, _( "You link up the UPS and the solar backpack." ) );
         } else if( it.link().target == link_state::vehicle_port ||
                    it.link().target == link_state::vehicle_battery ) {
             p->add_msg_if_player( m_good, _( "You link up the UPS and the vehicle." ) );
         }
         it.link().source = link_state::ups;
         loc->set_var( "cable", "plugged_in" );
         it.update_link_traits();
         it.process( here, p, p->pos() );
         p->mod_moves( -move_cost );
         return 0;
     } else if( choice == 22 ) {
         // Selection: Attach electrical cable to solar pack.
         item_location loc;
         avatar *you = p->as_avatar();
         const std::string choose_solar = _( "Choose solar pack:" );
         const std::string dont_have_solar = _( "You need an unfolded solar pack." );
         auto solar_filter = [&]( const item & itm ) {
             return itm.has_flag( flag_SOLARPACK_ON );
         };
         if( you != nullptr ) {
             loc = game_menus::inv::titled_filter_menu( solar_filter, *you, choose_solar, -1, dont_have_solar );
         }
         if( !loc ) {
             p->add_msg_if_player( _( "Never mind." ) );
             return std::nullopt;
         }
         if( it.has_no_links() ) {
             p->add_msg_if_player( m_info, _( "You attach the cable to the solar pack." ) );
         } else if( it.link().target == link_state::bio_cable ) {
             p->add_msg_if_player( m_good, _( "You are now plugged into the solar pack." ) );
         } else if( it.link().source == link_state::ups ) {
             p->add_msg_if_player( m_good, _( "You link up the solar pack and the UPS." ) );
         } else if( it.link().target == link_state::vehicle_port ||
                    it.link().target == link_state::vehicle_battery ) {
             p->add_msg_if_player( m_good, _( "You link up the solar pack and the vehicle." ) );
         }
         it.link().source = link_state::solarpack;
         loc->set_var( "cable", "plugged_in" );
         it.update_link_traits();
         it.process( here, p, p->pos() );
         p->mod_moves( -move_cost );
         return 0;
     }
     return std::nullopt;
 }
References _, Character::activity, Character::add_msg_if_player(), uilist::addentry(), item::all_items_top(), Creature::as_avatar(), Character::assign_activity(), player_activity::auto_resume, bio_cable, CABLE, Character::cache_has_item_with(), item::charge_linked_batteries(), debugmsg, uilist::entries, flag_CABLE_SPOOL, flag_IS_UPS, flag_SOLARPACK, flag_SOLARPACK_ON, units::from_milliwatt(), safe_reference< T >::get(), get_map(), Character::get_remote_fueled_bionic(), item::has_flag(), item::has_link_data(), item::has_no_links(), string_id< T >::is_empty(), item::link(), item::link_has_state(), item::link_length(), item::link_name(), item::LINK_RESPOOL_THRESHOLD, vehicle::linked_item_epower_this_turn, m_good, m_info, Creature::mod_moves(), move_cost, vehicle::name, no_link, Creature::pos(), item::process(), uilist::query(), item::reset_link(), uilist::ret, item::set_var(), solarpack, item::link_data::source, string_id< T >::str(), string_format(), item::link_data::t_veh, item::link_data::target, uilist::text, game_menus::inv::titled_filter_menu(), item::tname(), item::typeId(), item::update_link_traits(), ups, vehicle_battery, vehicle_port, vehicle_tow, and Character::worn_with_flag().
Member Data Documentation
cable_length
int link_up_actor::cable_length = -1
Maximum length of the cable.
At -1, will use the item type's max_charges.
Definition at line 1080 of file iuse_actor.h.
Referenced by item::update_link_traits().
can_extend
std::set<std::string> link_up_actor::can_extend = {}
Definition at line 1091 of file iuse_actor.h.
Referenced by link_extend_cable().
charge_rate
units::power link_up_actor::charge_rate = 0_W
Charge rate in watts.
Definition at line 1082 of file iuse_actor.h.
Referenced by item::update_link_traits().
efficiency
float link_up_actor::efficiency = 0.85f
(this) out of 1.0 chance to successfully add 1 charge every charge interval
Definition at line 1084 of file iuse_actor.h.
Referenced by item::update_link_traits().
menu_text
translation link_up_actor::menu_text
(Optional) Text displayed in the activation screen, defaults to "Plug in / Manage cables".
Definition at line 1088 of file iuse_actor.h.
move_cost
int link_up_actor::move_cost = 5
(Optional) The move cost to attach the cable.
Definition at line 1086 of file iuse_actor.h.
targets
std::set<link_state> link_up_actor::targets = { link_state::no_link, link_state::vehicle_port }
Definition at line 1090 of file iuse_actor.h.
Referenced by item::link_to().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp