Cataclysm DDA: outfit Class Reference
outfit Class Reference
#include <character_attire.h>
Public Member Functions
outfit ()=default
outfit (const std::list< item > &items)
bool is_worn (const item &clothing) const
bool is_worn (const itype_id &clothing) const
bool is_worn_module (const item &thing) const
bool is_wearing_on_bp (const itype_id &clothing, const bodypart_id &bp) const
bool covered_with_flag (const flag_id &f, const body_part_set &parts) const
bool wearing_something_on (const bodypart_id &bp) const
bool wearing_fitting_on (const bodypart_id &bp) const
bool worn_with_flag (const flag_id &f, const bodypart_id &bp) const
bool worn_with_flag (const flag_id &f) const
bool is_worn_item_visible (std::list< item >::const_iterator worn_item, const body_part_set &worn_item_body_parts) const
bool hands_conductive () const
bool can_pickVolume (const item &it, bool ignore_pkt_settings=true, bool is_pick_up_inv=false) const
side is_wearing_shoes (const bodypart_id &bp) const
bool is_barefoot () const
item item_worn_with_flag (const flag_id &f, const bodypart_id &bp) const
item item_worn_with_flag (const flag_id &f) const
item * item_worn_with_id (const itype_id &i)
std::optional< const item * > item_worn_with_inv_let (char invlet) const
item * best_shield ()
item * current_unarmed_weapon (const std::string &attack_vector)
item_location first_item_covering_bp (Character &guy, bodypart_id bp)
void inv_dump (std::vector< item * > &ret)
void inv_dump (std::vector< const item * > &ret) const
void item_encumb (std::map< bodypart_id, encumbrance_data > &vals, const item &new_item, const Character &guy) const
Applies encumbrance from items only If new_item is not null, then calculate under the assumption that it is added to existing work items.
std::list< item > get_visible_worn_items (const Character &guy) const
int swim_modifier (int swim_skill) const
bool natural_attack_restricted_on (const bodypart_id &bp) const
bool natural_attack_restricted_on (const sub_bodypart_id &bp) const
units::mass weight_carried_with_tweaks (const std::map< const item *, int > &without) const
units::mass weight () const
units::volume holster_volume () const
int used_holsters () const
int total_holsters () const
units::volume free_holster_volume () const
units::volume contents_volume_with_tweaks (const std::map< const item *, int > &without) const
units::volume volume_capacity_with_tweaks (const std::map< const item *, int > &without) const
units::volume free_space () const
units::mass free_weight_capacity () const
units::volume max_single_item_volume () const
units::length max_single_item_length () const
units::volume volume_capacity () const
units::volume small_pocket_volume (const units::volume &threshold) const
int empty_holsters () const
int pocket_warmth () const
int hood_warmth () const
int collar_warmth () const
std::map< bodypart_id, int > warmth (const Character &guy) const
Returns warmth provided by armor, etc.
int get_env_resist (bodypart_id bp) const
int sum_filthy_cover (bool ranged, bool melee, bodypart_id bp) const
ret_val< void > power_armor_conflicts (const item &clothing) const
bool is_wearing_power_armor (bool *has_helmet=nullptr) const
bool is_wearing_active_power_armor () const
bool is_wearing_active_optcloak () const
ret_val< void > only_one_conflicts (const item &clothing) const
bool one_per_layer_change_side (item &it, const Character &guy) const
void one_per_layer_sidedness (item &clothing) const
ret_val< void > check_rigid_conflicts (const item &clothing, side s) const
ret_val< void > check_rigid_conflicts (const item &clothing) const
bool check_rigid_change_side (item &it, const Character &guy) const
void check_rigid_sidedness (item &clothing) const
int amount_worn (const itype_id &clothing) const
int worn_guns () const
int clatter_sound () const
bool adjust_worn (npc &guy)
float clothing_wetness_mult (const bodypart_id &bp) const
void damage_mitigate (const bodypart_id &bp, damage_unit &dam) const
float damage_resist (const damage_type_id &dt, const bodypart_id &bp, bool to_self=false) const
int coverage_with_flags_exclude (const bodypart_id &bp, const std::vector< flag_id > &flags) const
int get_coverage (bodypart_id bp, item::cover_type cover_type=item::cover_type::COVER_DEFAULT) const
void bodypart_exposure (std::map< bodypart_id, float > &bp_exposure, const std::vector< bodypart_id > &all_body_parts) const
void prepare_bodymap_info (bodygraph_info &info, const bodypart_id &bp, const std::set< sub_bodypart_id > &sub_parts, const Character &person) const
void get_overlay_ids (std::vector< std::pair< std::string, std::string >> &overlay_ids) const
body_part_set exclusive_flag_coverage (body_part_set bps, const flag_id &flag) const
bool check_item_encumbrance_flag (bool update_required)
void add_dependent_item (std::list< item * > &dependent, const item &it)
std::list< item > remove_worn_items_with (const std::function< bool(item &)> &filter, Character &guy)
bool takeoff (item_location loc, std::list< item > *res, Character &guy)
std::list< item > use_amount (const itype_id &it, int quantity, std::list< item > &used, const std::function< bool(const item &)> &filter, Character &wearer)
std::list< item >::iterator position_to_wear_new_item (const item &new_item)
std::optional< std::list< item >::iterator > wear_item (Character &guy, const item &to_wear, bool interactive, bool do_calc_encumbrance, bool do_sort_items=true, bool quiet=false)
void recalc_ablative_blocking (const Character *guy)
std::unordered_set< bodypart_id > where_discomfort (const Character &guy) const
Calculate and return any bodyparts that are currently uncomfortable.
void insert_item_at_index (const item &clothing, int index)
void check_and_recover_morale (player_morale &test_morale) const
void absorb_damage (Character &guy, damage_unit &elem, bodypart_id bp, std::list< item > &worn_remains, bool &armor_destroyed)
void sort_armor (Character &guy)
Draws the UI and handles player input for the armor re-ordering window.
std::vector< item_pocket * > grab_drop_pockets ()
std::vector< item_pocket * > grab_drop_pockets (const bodypart_id &bp)
std::vector< layering_item_info > items_cover_bp (const Character &c, const bodypart_id &bp)
item_penalties get_item_penalties (std::list< item >::const_iterator worn_item_it, const Character &c, const bodypart_id &_bp)
std::vector< advanced_inv_listitem > get_AIM_inventory (size_t &item_index, avatar &you, const advanced_inventory_pane &pane, advanced_inv_area &square)
void add_AIM_items_from_area (avatar &you, advanced_inv_area &square, advanced_inventory_pane &pane)
void fire_options (Character &guy, std::vector< std::string > &options, std::vector< std::function< void()>> &actions)
void best_pocket (Character &guy, const item &it, const item *avoid, std::pair< item_location, item_pocket * > &current_best, bool ignore_settings=false)
void overflow (Character &guy)
void holster_opts (std::vector< dispose_option > &opts, item_location obj, Character &guy)
void get_eligible_containers_for_crafting (std::vector< const item * > &conts) const
void on_takeoff (Character &guy)
void on_item_wear (Character &guy)
void pickup_stash (const item &newit, int &remaining_charges, bool ignore_pkt_settings=false)
void add_stash (Character &guy, const item &newit, int &remaining_charges, bool ignore_pkt_settings=false)
void set_fitted ()
std::vector< item > available_pockets () const
void write_text_memorial (std::ostream &file, const std::string &indent, const char *eol) const
std::string get_armor_display (bodypart_id bp) const
void activate_combat_items (npc &guy)
void deactivate_combat_items (npc &guy)
bool empty () const
item & front ()
size_t size () const
std::vector< item_location > top_items_loc (Character &guy)
std::vector< item_location > all_items_loc (Character &guy)
std::optional< int > get_item_position (const item &it) const
const item & i_at (int position) const
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const
std::list< item > remove_items_with (Character &guy, const std::function< bool(const item &)> &filter, int &count)
void organize_items_menu ()
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
Private Attributes
std::list< item > worn
Friends
class Character
Detailed Description
Definition at line 83 of file character_attire.h.
Constructor & Destructor Documentation
outfit() [1/2]
outfit::outfit () default
outfit() [2/2]
outfit::outfit (const std::list< item > & items) inline explicit
Definition at line 90 of file character_attire.h.
 : worn( items ) {}
Member Function Documentation
absorb_damage()
void outfit::absorb_damage (Character & guy, damage_unit & elem, bodypart_id bp, std::list< item > & worn_remains, bool & armor_destroyed)
Definition at line 1886 of file character_attire.cpp.
 {
     sub_bodypart_id sbp;
     sub_bodypart_id secondary_sbp;
     // if this body part has sub part locations roll one
     if( !bp->sub_parts.empty() ) {
         sbp = bp->random_sub_part( false );
         // the torso and legs has a second layer of hanging body parts
         secondary_sbp = bp->random_sub_part( true );
     }
     // generate a single roll for determining if hit
     int roll = rng( 1, 100 );
     // Only the outermost armor can be set on fire
     bool outermost = true;
     // The worn vector has the innermost item first, so
     // iterate reverse to damage the outermost (last in worn vector) first.
     for( auto iter = worn.rbegin(); iter != worn.rend(); ) {
         item &armor = *iter;
         if( !armor.covers( bp ) ) {
             ++iter;
             continue;
         }
         const std::string pre_damage_name = armor.tname();
         bool destroy = false;
         item_armor_enchantment_adjust( guy, elem, armor );
         // Heat damage can set armor on fire
         // Even though it doesn't cause direct physical damage to it
         // FIXME: Hardcoded damage type
         if( outermost && elem.type == STATIC( damage_type_id( "heat" ) ) && elem.amount >= 1.0f ) {
             // TODO: Different fire intensity values based on damage
             fire_data frd{ 2 };
             destroy = !armor.has_flag( flag_INTEGRATED ) && armor.burn( frd );
             int fuel = roll_remainder( frd.fuel_produced );
             if( fuel > 0 ) {
                 guy.add_effect( effect_onfire, time_duration::from_turns( fuel + 1 ), bp, false, 0, false,
                                 true );
             }
         }
         if( !destroy ) {
             // if the armor location has ablative armor apply that first
             if( armor.is_ablative() ) {
                 guy.ablative_armor_absorb( elem, armor, sbp, roll );
             }
             // if not already destroyed to an armor absorb
             destroy = guy.armor_absorb( elem, armor, bp, sbp, roll );
             // for the torso we also need to consider if it hits anything hanging off the character or their neck
             if( secondary_sbp != sub_bodypart_id() ) {
                 destroy = guy.armor_absorb( elem, armor, bp, secondary_sbp, roll );
             }
         }
         if( destroy ) {
             if( get_player_view().sees( guy ) ) {
                 SCT.add( point( guy.posx(), guy.posy() ), direction::NORTH, remove_color_tags( pre_damage_name ),
                          m_neutral, _( "destroyed" ), m_info );
             }
             destroyed_armor_msg( guy, pre_damage_name );
             armor_destroyed = true;
             armor.on_takeoff( guy );
             for( const item *it : armor.all_items_top( pocket_type::CONTAINER ) ) {
                 worn_remains.push_back( *it );
             }
             // decltype is the type name of the iterator, note that reverse_iterator::base returns the
             // iterator to the next element, not the one the revers_iterator points to.
             // http://stackoverflow.com/questions/1830158/how-to-call-erase-with-a-reverse-iterator
             iter = decltype( iter )( worn.erase( --iter.base() ) );
         } else {
             ++iter;
             outermost = false;
         }
     }
 }
References _, Character::ablative_armor_absorb(), scrollingcombattext::add(), Creature::add_effect(), item::all_items_top(), damage_unit::amount, Character::armor_absorb(), bp, item::burn(), CONTAINER, item::covers(), destroyed_armor_msg(), effect_onfire, flag_INTEGRATED, time_duration::from_turns(), get_player_view(), item::has_flag(), item::is_ablative(), item_armor_enchantment_adjust(), m_info, m_neutral, NORTH, item::on_takeoff(), point, Creature::posx(), Creature::posy(), body_part_type::random_sub_part(), remove_color_tags(), rng(), roll_remainder(), SCT, STATIC, body_part_type::sub_parts, item::tname(), damage_unit::type, and worn.
Referenced by Character::absorb_hit().
activate_combat_items()
void outfit::activate_combat_items (npc & guy)
Definition at line 2321 of file npcmove.cpp.
 {
     for( item &candidate : worn ) {
         if( candidate.has_flag( flag_COMBAT_TOGGLEABLE ) && candidate.is_transformable() &&
             !candidate.active ) {
             const iuse_transform *transform = dynamic_cast<const iuse_transform *>
                                               ( candidate.type->get_use( "transform" )->get_actor_ptr() );
             // Due to how UPS works, there can be no charges_needed for UPS items.
             // Energy consumption is thus not checked at activation.
             // To prevent "flickering", this is a hard check for UPS charges > 0.
             if( transform->target->has_flag( flag_USE_UPS ) && guy.available_ups() == 0_kJ ) {
                 continue;
             }
             if( transform->can_use( guy, candidate, tripoint_zero ).success() ) {
                 transform->use( &guy, candidate, tripoint_zero );
                 guy.add_msg_if_npc( _( "<npcname> activates their %s." ), candidate.display_name() );
             }
         }
     }
 }
References _, npc::add_msg_if_npc(), Character::available_ups(), flag_COMBAT_TOGGLEABLE, flag_USE_UPS, transform, tripoint_zero, and worn.
Referenced by npc::activate_combat_items().
add_AIM_items_from_area()
void outfit::add_AIM_items_from_area (avatar & you, advanced_inv_area & square, advanced_inventory_pane & pane)
Definition at line 179 of file advanced_inv_pane.cpp.
 {
     auto iter = worn.begin();
     for( size_t i = 0; i < worn.size(); ++i, ++iter ) {
         advanced_inv_listitem it( item_location( you, &*iter ), i + 1, 1, square.id, false );
         if( pane.is_filtered( *it.items.front() ) ) {
             continue;
         }
         square.volume += it.volume;
         square.weight += it.weight;
         pane.items.push_back( it );
     }
 }
References advanced_inventory_pane::is_filtered(), advanced_inv_listitem::items, advanced_inventory_pane::items, square(), advanced_inv_listitem::volume, advanced_inv_listitem::weight, and worn.
add_dependent_item()
void outfit::add_dependent_item (std::list< item * > & dependent, const item & it)
Definition at line 1779 of file character_attire.cpp.
 {
     // Adds dependent worn items recursively
     for( item &wit : worn ) {
         if( &wit == &it || !wit.is_worn_only_with( it ) ) {
             continue;
         }
         const auto iter = std::find_if( dependent.begin(), dependent.end(),
         [&wit]( const item * dit ) {
             return &wit == dit;
         } );
         if( iter == dependent.end() ) { // Not in the list yet
             add_dependent_item( dependent, wit );
             dependent.push_back( &wit );
         }
     }
 }
References item::is_worn_only_with(), and worn.
Referenced by Character::get_dependent_worn_items().
add_stash()
void outfit::add_stash (Character & guy, const item & newit, int & remaining_charges, bool ignore_pkt_settings = false)
Definition at line 2467 of file character_attire.cpp.
 {
     guy.invalidate_weight_carried_cache();
     if( ignore_pkt_settings ) {
         // Crawl all pockets regardless of priority
         // Crawl First : wielded item
         item_location carried_item = guy.get_wielded_item();
         if( carried_item && !carried_item->has_pocket_type( pocket_type::MAGAZINE ) &&
             carried_item->can_contain_partial( newit ).success() ) {
             int used_charges = carried_item->fill_with( newit, remaining_charges, /*unseal_pockets=*/false,
                                /*allow_sealed=*/false, /*ignore_settings=*/false, /*into_bottom*/false, &guy );
             remaining_charges -= used_charges;
         }
         // Crawl Next : worn items
         pickup_stash( newit, remaining_charges, ignore_pkt_settings );
     } else {
         //item copy for test can contain
         item temp_it = item( newit );
         temp_it.charges = 1;
         // Collect all pockets
         std::vector<pocket_data_with_parent> pockets_with_parent;
         auto const pocket_filter = [&temp_it]( item_pocket const * pck ) {
             return pck->can_contain( temp_it ).success();
         };
         const std::function<bool( const pocket_data_with_parent &a, const pocket_data_with_parent &b )>
         &sort_f = [&temp_it]( const pocket_data_with_parent & a, const pocket_data_with_parent & b ) {
             return b.pocket_ptr->better_pocket( *a.pocket_ptr, temp_it, false );
         };
         pockets_with_parent = guy.get_all_pocket_with_parent( pocket_filter, &sort_f );
         const int amount = remaining_charges;
         int num_contained = 0;
         for( const pocket_data_with_parent &pocket_data_ptr : pockets_with_parent ) {
             if( amount <= num_contained || remaining_charges <= 0 ) {
                 break;
             }
             int filled_count = 0;
             item_pocket *pocke = const_cast<item_pocket *>( pocket_data_ptr.pocket_ptr );
             if( pocke == nullptr ) {
                 continue;
             }
             int max_contain_value = pocke->remaining_capacity_for_item( newit );
             const item_location parent_data = pocket_data_ptr.parent;
             if( parent_data.has_parent() ) {
                 if( parent_data.parents_can_contain_recursive( &temp_it ).success() ) {
                     max_contain_value = parent_data.max_charges_by_parent_recursive( temp_it ).value();
                 } else {
                     max_contain_value = 0;
                 }
             }
             const int charges = std::min( max_contain_value, remaining_charges ) ;
             filled_count = pocke->fill_with( newit, guy, charges, false, false );
             num_contained += filled_count;
             remaining_charges -= filled_count;
         }
     }
 }
References a, b, item::can_contain_partial(), item::charges, item_pocket::fill_with(), item::fill_with(), Character::get_all_pocket_with_parent(), Character::get_wielded_item(), item_location::has_parent(), item::has_pocket_type(), Character::invalidate_weight_carried_cache(), item, MAGAZINE, item_location::max_charges_by_parent_recursive(), min(), item_location::parents_can_contain_recursive(), pickup_stash(), item_pocket::remaining_capacity_for_item(), and ret_val_common::success().
Referenced by Character::i_add_or_fill().
adjust_worn()
bool outfit::adjust_worn (npc & guy)
Definition at line 5410 of file npcmove.cpp.
 {
     const auto covers_broken = [&guy]( const item & it, side s ) {
         const body_part_set covered = it.get_covered_body_parts( s );
         for( const std::pair<const bodypart_str_id, bodypart> &elem : guy.get_body() ) {
             if( elem.second.get_hp_cur() <= 0 && covered.test( elem.first ) ) {
                 return true;
             }
         }
         return false;
     };
     for( item &elem : worn ) {
         if( !elem.has_flag( flag_SPLINT ) ) {
             continue;
         }
         if( !covers_broken( elem, elem.get_side() ) ) {
             const bool needs_change = covers_broken( elem, opposite_side( elem.get_side() ) );
             //create an item_location for takeoff() to handle.
             item_location loc_for_takeoff = item_location( guy, &elem );
             // Try to change side (if it makes sense), or take off.
             std::list<item> temp_list;
             if( ( needs_change && guy.change_side( elem ) ) || takeoff( loc_for_takeoff, &temp_list, guy ) ) {
                 return true;
             }
         }
     }
     return false;
 }
References Character::change_side(), flag_SPLINT, Creature::get_body(), item::get_covered_body_parts(), opposite_side(), takeoff(), body_part_set::test(), and worn.
Referenced by npc::adjust_worn().
all_items_loc()
std::vector< item_location > outfit::all_items_loc (Character & guy)
Definition at line 501 of file character_inventory.cpp.
 {
     std::vector<item_location> ret;
     for( item &worn_it : worn ) {
         item_location worn_loc( guy, &worn_it );
         std::vector<item_location> worn_internal_items;
         recur_internal_locations( worn_loc, worn_internal_items );
         ret.insert( ret.end(), worn_internal_items.begin(), worn_internal_items.end() );
     }
     return ret;
 }
References recur_internal_locations(), cata::hash64_detail::ret, and worn.
Referenced by Character::all_items_loc().
amount_worn()
int outfit::amount_worn (const itype_id & clothing) const
Definition at line 1484 of file character_attire.cpp.
 {
     int amount = 0;
     for( const item &elem : worn ) {
         if( elem.typeId() == clothing ) {
             ++amount;
         }
     }
     return amount;
 }
References worn.
Referenced by Character::amount_worn().
available_pockets()
std::vector< item > outfit::available_pockets () const
Definition at line 2170 of file character_attire.cpp.
 {
     std::vector<item> avail_pockets;
     for( const item &clothing : worn ) {
         if( clothing.is_container() || clothing.is_holster() ) {
             avail_pockets.push_back( clothing );
         }
     }
     return avail_pockets;
 }
References worn.
Referenced by npc_trading::npc_can_fit_items().
best_pocket()
void outfit::best_pocket (Character & guy, const item & it, const item * avoid, std::pair< item_location, item_pocket * > & current_best, bool ignore_settings = false)
Definition at line 2109 of file character_attire.cpp.
 {
     for( item &worn_it : worn ) {
         if( &worn_it == &it || &worn_it == avoid ) {
             continue;
         }
         item_location loc( guy, &worn_it );
         std::pair<item_location, item_pocket *> internal_pocket =
             worn_it.best_pocket( it, loc, avoid, false, ignore_settings );
         if( internal_pocket.second != nullptr &&
             ( current_best.second == nullptr ||
               current_best.second->better_pocket( *internal_pocket.second, it ) ) ) {
             current_best = internal_pocket;
         }
     }
 }
References worn.
Referenced by Character::best_pocket().
best_shield()
item * outfit::best_shield ()
Definition at line 2181 of file character_attire.cpp.
 {
     int best_val = 0;
     item *ret = nullptr;
     for( item &shield : worn ) {
         const int block = melee::blocking_ability( shield );
         if( shield.has_flag( flag_BLOCK_WHILE_WORN ) && block >= best_val ) {
             best_val = block;
             ret = &shield;
         }
     }
     return ret;
 }
References melee::blocking_ability(), flag_BLOCK_WHILE_WORN, cata::hash64_detail::ret, and worn.
Referenced by Character::best_shield().
bodypart_exposure()
void outfit::bodypart_exposure (std::map< bodypart_id, float > & bp_exposure, const std::vector< bodypart_id > & all_body_parts) const
Definition at line 2371 of file character_attire.cpp.
 {
     for( const item &it : worn ) {
         // What body parts does this item cover?
         body_part_set covered = it.get_covered_body_parts();
         for( const bodypart_id &bp : all_body_parts ) {
             if( !covered.test( bp.id() ) ) {
                 continue;
             }
             float part_exposure = ( 100 - it.get_coverage( bp ) ) / 100.0f;
             // Coverage multiplies, so two layers with 50% coverage will together give 75%
             bp_exposure[bp] *= part_exposure;
         }
     }
 }
References all_body_parts, bp, int_id< T >::id(), body_part_set::test(), and worn.
Referenced by Character::bodypart_exposure().
can_pickVolume()
bool outfit::can_pickVolume (const item & it, bool ignore_pkt_settings = true, bool is_pick_up_inv = false) const
Definition at line 1797 of file character_attire.cpp.
 {
     for( const item &w : worn ) {
         if( w.can_contain( it, false, false, ignore_pkt_settings, is_pick_up_inv ).success() ) {
             return true;
         }
     }
     return false;
 }
References worn.
Referenced by Character::can_pickVolume(), and Character::can_pickVolume_partial().
check_and_recover_morale()
void outfit::check_and_recover_morale (player_morale & test_morale) const
Definition at line 169 of file character_morale.cpp.
 {
     for( const item &wit : worn ) {
         test_morale.on_item_wear( wit );
     }
 }
References player_morale::on_item_wear(), and worn.
Referenced by Character::check_and_recover_morale().
check_item_encumbrance_flag()
bool outfit::check_item_encumbrance_flag (bool update_required)
Definition at line 1128 of file character_attire.cpp.
 {
     for( item &i : worn ) {
         if( !update_required && i.encumbrance_update_ ) {
             update_required = true;
         }
         i.encumbrance_update_ = false;
     }
     return update_required;
 }
References worn.
Referenced by Character::check_item_encumbrance_flag(), and Character::process_items().
check_rigid_change_side()
bool outfit::check_rigid_change_side (item & it, const Character & guy) const
Definition at line 742 of file character_attire.cpp.
 {
     if( !check_rigid_conflicts( it,
                                 it.get_side() == side::LEFT ? side::RIGHT : side::LEFT ).success() ) {
         const std::string player_msg = string_format(
                                            _( "Your %s conflicts with hard armor on your other side so you can't swap it." ),
                                            it.tname() );
         const std::string npc_msg = string_format(
                                         _( "<npcname>'s %s conflicts with hard armor on your other side so they can't swap it." ),
                                         it.tname() );
         guy.add_msg_player_or_npc( m_info, player_msg, npc_msg );
         return false;
     }
     return true;
 }
References _, Character::add_msg_player_or_npc(), check_rigid_conflicts(), item::get_side(), LEFT, m_info, RIGHT, string_format(), ret_val_common::success(), and item::tname().
Referenced by Character::change_side().
check_rigid_conflicts() [1/2]
ret_val< void > outfit::check_rigid_conflicts (const item & clothing) const
Definition at line 1433 of file character_attire.cpp.
 {
     if( !clothing.is_sided() ) {
         return check_rigid_conflicts( clothing, side::BOTH );
     }
     ret_val<void> ls = check_rigid_conflicts( clothing, side::LEFT );
     ret_val<void> rs = check_rigid_conflicts( clothing, side::RIGHT );
     if( !ls.success() && !rs.success() ) {
         return ls;
     }
     return ret_val<void>::make_success();
 }
References BOTH, check_rigid_conflicts(), item::is_sided(), LEFT, ret_val< T >::make_success(), RIGHT, and ret_val_common::success().
check_rigid_conflicts() [2/2]
ret_val< void > outfit::check_rigid_conflicts (const item & clothing, side s) const
Definition at line 1392 of file character_attire.cpp.
 {
     std::unordered_set<sub_bodypart_id> to_test;
     // if not overridden get the actual side of the item
     if( s == side::num_sides ) {
         s = clothing.get_side();
     }
     // if the clothing is sided and not on the side we want to test
     // create a copy that is swapped in side to test on
     if( clothing.is_sided() && clothing.get_side() != s ) {
         item swapped_item( clothing );
         swapped_item.set_side( s );
         // figure out which sublimbs need to be tested
         for( const sub_bodypart_id &sbp : swapped_item.get_covered_sub_body_parts() ) {
             if( swapped_item.is_bp_rigid( sbp ) ) {
                 to_test.emplace( sbp );
             }
         }
     } else {
         // figure out which sublimbs need to be tested
         for( const sub_bodypart_id &sbp : clothing.get_covered_sub_body_parts() ) {
             if( clothing.is_bp_rigid( sbp ) ) {
                 to_test.emplace( sbp );
             }
         }
     }
     // go through all worn and see if already wearing something rigid
     for( const item &i : worn ) {
         ret_val<void> result = rigid_test( clothing, i, to_test );
         if( !result.success() ) {
             return result;
         }
     }
     return ret_val<void>::make_success();
 }
References item::get_covered_sub_body_parts(), item::get_side(), item::is_bp_rigid(), item::is_sided(), ret_val< T >::make_success(), num_sides, rigid_test(), item::set_side(), ret_val_common::success(), and worn.
Referenced by Character::can_wear(), check_rigid_change_side(), check_rigid_conflicts(), and check_rigid_sidedness().
check_rigid_sidedness()
void outfit::check_rigid_sidedness (item & clothing) const
Definition at line 1466 of file character_attire.cpp.
 {
     if( !clothing.is_sided() ) {
         //nothing to do
         return;
     }
     bool ls = check_rigid_conflicts( clothing, side::LEFT ).success();
     bool rs = check_rigid_conflicts( clothing, side::RIGHT ).success();
     if( ls && rs ) {
         clothing.set_side( side::BOTH );
     } else if( ls ) {
         clothing.set_side( side::LEFT );
     } else {
         // this is a fallback option if it must be something
         clothing.set_side( side::RIGHT );
     }
 }
References BOTH, check_rigid_conflicts(), item::is_sided(), LEFT, RIGHT, item::set_side(), and ret_val_common::success().
Referenced by Character::wear().
clatter_sound()
int outfit::clatter_sound () const
Definition at line 2608 of file character_attire.cpp.
 {
     int max_volume = 0;
     for( const item &i : worn ) {
         // if the item has noise making pockets we should check if they have clatered
         if( i.has_noisy_pockets() ) {
             for( const item_pocket *pocket : i.get_all_contained_pockets() ) {
                 int noise_chance = pocket->get_pocket_data()->activity_noise.chance;
                 int volume = pocket->get_pocket_data()->activity_noise.volume;
                 if( noise_chance > 0 && !pocket->empty() ) {
                     // if this pocket causes more volume and it triggers noise
                     if( volume > max_volume && rng( 1, 100 ) < noise_chance ) {
                         max_volume = volume;
                     }
                 }
             }
         }
     }
     return std::round( max_volume );
 }
References pocket_data::activity_noise, pocket_noise::chance, item_pocket::empty(), item_pocket::get_pocket_data(), rng(), round(), pocket_noise::volume, and worn.
Referenced by Character::clatter_sound().
clothing_wetness_mult()
float outfit::clothing_wetness_mult (const bodypart_id & bp) const
Definition at line 2629 of file character_attire.cpp.
 {
     float clothing_mult = 1.0;
     for( const item &i : worn ) {
         if( i.covers( bp ) ) {
             const float item_coverage = static_cast<float>( i.get_coverage( bp ) ) / 100;
             const float item_breathability = static_cast<float>( i.breathability( bp ) ) / 100;
             // breathability of naked skin + breathability of item
             const float breathability = ( 1.0 - item_coverage ) + item_coverage * item_breathability;
             clothing_mult = std::min( clothing_mult, breathability );
         }
     }
     // always some evaporation even if completely covered
     // doesn't handle things that would be "air tight"
     clothing_mult = std::max( clothing_mult, .1f );
     return clothing_mult;
 }
References bp, max(), min(), and worn.
Referenced by Character::try_remove_grab(), and Character::update_body_wetness().
collar_warmth()
int outfit::collar_warmth () const
Definition at line 1753 of file character_attire.cpp.
 {
     int warmth = 0;
     for( const item &w : worn ) {
         if( w.has_flag( flag_COLLAR ) ) {
             warmth = std::max( warmth, w.get_warmth() );
         }
     }
     return warmth;
 }
References flag_COLLAR, max(), warmth(), and worn.
Referenced by Character::bonus_item_warmth().
contents_volume_with_tweaks()
units::volume outfit::contents_volume_with_tweaks (const std::map< const item *, int > & without) const
Definition at line 1210 of file character_attire.cpp.
 {
     units::volume ret = 0_ml;
     for( const item &i : worn ) {
         if( !without.count( &i ) ) {
             ret += i.get_contents_volume_with_tweaks( without );
         }
     }
     return ret;
 }
References cata::hash64_detail::ret, and worn.
Referenced by Character::volume_carried_with_tweaks().
coverage_with_flags_exclude()
int outfit::coverage_with_flags_exclude (const bodypart_id & bp, const std::vector< flag_id > & flags) const
Definition at line 1545 of file character_attire.cpp.
 {
     int coverage = 0;
     for( const item &clothing : worn ) {
         if( clothing.covers( bp ) ) {
             bool has_flag = false;
             for( const flag_id &flag : flags ) {
                 if( clothing.has_flag( flag ) ) {
                     has_flag = true;
                     break;
                 }
             }
             if( !has_flag ) {
                 coverage += clothing.get_coverage( bp );
             }
         }
     }
     return coverage;
 }
References bp, and worn.
Referenced by Character::active_light(), and Character::get_effective_efficiency().
covered_with_flag()
bool outfit::covered_with_flag (const flag_id & f, const body_part_set & parts) const
Definition at line 1599 of file character_attire.cpp.
 {
     body_part_set to_cover( parts );
     for( const item &elem : worn ) {
         if( !elem.has_flag( f ) ) {
             continue;
         }
         to_cover.substract_set( elem.get_covered_body_parts() );
         if( to_cover.none() ) {
             return true;    // Allows early exit.
         }
     }
     return to_cover.none();
 }
References body_part_set::none(), body_part_set::substract_set(), and worn.
Referenced by Character::covered_with_flag().
current_unarmed_weapon()
item * outfit::current_unarmed_weapon (const std::string & attack_vector)
Definition at line 2195 of file character_attire.cpp.
 {
     item *cur_weapon = &null_item_reference();
     for( item &worn_item : worn ) {
         bool covers = false;
         if( attack_vector == "HAND" || attack_vector == "GRAPPLE" || attack_vector == "THROW" ) {
             covers = worn_item.covers( bodypart_id( "hand_l" ) ) &&
                      worn_item.covers( bodypart_id( "hand_r" ) );
         } else if( attack_vector == "ARM" ) {
             covers = worn_item.covers( bodypart_id( "arm_l" ) ) &&
                      worn_item.covers( bodypart_id( "arm_r" ) );
         } else if( attack_vector == "ELBOW" ) {
             covers = worn_item.covers( sub_bodypart_id( "arm_elbow_l" ) ) &&
                      worn_item.covers( sub_bodypart_id( "arm_elbow_r" ) );
         } else if( attack_vector == "FINGERS" ) {
             covers = worn_item.covers( sub_bodypart_id( "hand_fingers_l" ) ) &&
                      worn_item.covers( sub_bodypart_id( "hand_fingers_r" ) );
         } else if( attack_vector == "WRIST" ) {
             covers = worn_item.covers( sub_bodypart_id( "hand_wrist_l" ) ) &&
                      worn_item.covers( sub_bodypart_id( "hand_wrist_r" ) );
         } else if( attack_vector == "PALM" ) {
             covers = worn_item.covers( sub_bodypart_id( "hand_palm_l" ) ) &&
                      worn_item.covers( sub_bodypart_id( "hand_palm_r" ) );
         } else if( attack_vector == "HAND_BACK" ) {
             covers = worn_item.covers( sub_bodypart_id( "hand_back_l" ) ) &&
                      worn_item.covers( sub_bodypart_id( "hand_back_r" ) );
         } else if( attack_vector == "SHOULDER" ) {
             covers = worn_item.covers( sub_bodypart_id( "arm_shoulder_l" ) ) &&
                      worn_item.covers( sub_bodypart_id( "arm_shoulder_r" ) );
         } else if( attack_vector == "FOOT" ) {
             covers = worn_item.covers( bodypart_id( "foot_l" ) ) &&
                      worn_item.covers( bodypart_id( "foot_r" ) );
         } else if( attack_vector == "LOWER_LEG" ) {
             covers = worn_item.covers( sub_bodypart_id( "leg_lower_l" ) ) &&
                      worn_item.covers( sub_bodypart_id( "leg_lower_r" ) );
         } else if( attack_vector == "KNEE" ) {
             covers = worn_item.covers( sub_bodypart_id( "leg_knee_l" ) ) &&
                      worn_item.covers( sub_bodypart_id( "leg_knee_r" ) );
         } else if( attack_vector == "HIP" ) {
             covers = worn_item.covers( sub_bodypart_id( "leg_hip_l" ) ) &&
                      worn_item.covers( sub_bodypart_id( "leg_hip_r" ) );
         } else if( attack_vector == "HEAD" ) {
             covers = worn_item.covers( bodypart_id( "head" ) );
         } else if( attack_vector == "TORSO" ) {
             covers = worn_item.covers( bodypart_id( "torso" ) );
         }
         // Uses enum layer_level to make distinction for top layer.
         if( covers ) {
             if( cur_weapon->is_null() || ( worn_item.get_layer() >= cur_weapon->get_layer() ) ) {
                 cur_weapon = &worn_item;
             }
         }
     }
     return cur_weapon;
 }
References item::get_layer(), item::is_null(), null_item_reference(), and worn.
Referenced by Character::melee_attack_abstract().
damage_mitigate()
void outfit::damage_mitigate (const bodypart_id & bp, damage_unit & dam) const
Definition at line 1520 of file character_attire.cpp.
 {
     for( const item &cloth : worn ) {
         if( cloth.get_coverage( bp ) == 100 && cloth.covers( bp ) ) {
             cloth.mitigate_damage( dam );
         }
     }
 }
References bp, and worn.
Referenced by Character::immune_to().
damage_resist()
float outfit::damage_resist (const damage_type_id & dt, const bodypart_id & bp, bool to_self = false) const
Definition at line 1967 of file character_attire.cpp.
 {
     float ret = 0.0f;
     for( const item &i : worn ) {
         if( i.covers( bp ) ) {
             ret += i.resist( dt, to_self, bp );
         }
     }
     return ret;
 }
References bp, cata::hash64_detail::ret, and worn.
Referenced by talker_character_const::armor_at(), Character::best_part_to_smash(), Creature::dodge_check(), and Character::get_armor_type().
deactivate_combat_items()
void outfit::deactivate_combat_items (npc & guy)
Definition at line 2349 of file npcmove.cpp.
 {
     for( item &candidate : worn ) {
         if( candidate.has_flag( flag_COMBAT_TOGGLEABLE ) && candidate.is_transformable() &&
             candidate.active ) {
             const iuse_transform *transform = dynamic_cast<const iuse_transform *>
                                               ( candidate.type->get_use( "transform" )->get_actor_ptr() );
             if( transform->can_use( guy, candidate, tripoint_zero ).success() ) {
                 transform->use( &guy, candidate, tripoint_zero );
                 guy.add_msg_if_npc( _( "<npcname> deactivates their %s." ), candidate.display_name() );
             }
         }
     }
 }
References _, npc::add_msg_if_npc(), flag_COMBAT_TOGGLEABLE, transform, tripoint_zero, and worn.
Referenced by npc::deactivate_combat_items().
deserialize()
void outfit::deserialize (const JsonObject & jo)
Definition at line 2603 of file character_attire.cpp.
 {
     jo.read( "worn", worn );
 }
References JsonObject::read(), and worn.
empty()
bool outfit::empty () const
Definition at line 1529 of file character_attire.cpp.
 {
     return worn.empty();
 }
References worn.
Referenced by npc::wear_if_wanted().
empty_holsters()
int outfit::empty_holsters () const
Definition at line 1657 of file character_attire.cpp.
 {
     int e_holsters = 0;
     for( const item &w : worn ) {
         if( w.is_holster() && w.is_container_empty() ) {
             e_holsters += 1;
         }
     }
     return e_holsters;
 }
References worn.
Referenced by Character::empty_holsters().
exclusive_flag_coverage()
body_part_set outfit::exclusive_flag_coverage (body_part_set bps, const flag_id & flag) const
Definition at line 1841 of file character_attire.cpp.
 {
     for( const item &elem : worn ) {
         if( !elem.has_flag( flag ) ) {
             // Unset the parts covered by this item
             bps.substract_set( elem.get_covered_body_parts() );
         }
     }
     return bps;
 }
References body_part_set::substract_set(), and worn.
Referenced by Character::exclusive_flag_coverage().
fire_options()
void outfit::fire_options (Character & guy, std::vector< std::string > & options, std::vector< std::function< void()>> & actions)
Definition at line 2049 of file character_attire.cpp.
 {
     for( item &clothing : worn ) {
         std::vector<item *> guns = clothing.items_with( []( const item & it ) {
             return it.is_gun();
         } );
         if( !guns.empty() && clothing.type->can_use( "holster" ) ) {
             //~ draw (first) gun contained in holster
             //~ %1$s: weapon name, %2$s: container name, %3$d: remaining ammo count
             options.push_back( string_format( pgettext( "holster", "%1$s from %2$s (%3$d)" ),
                                               guns.front()->tname(),
                                               clothing.type_name(),
                                               guns.front()->ammo_remaining() ) );
             actions.emplace_back( [&] { guy.invoke_item( &clothing, "holster" ); } );
         } else if( clothing.is_gun() && clothing.gunmod_find( itype_shoulder_strap ) ) {
             // wield item currently worn using shoulder strap
             options.push_back( clothing.display_name() );
             actions.emplace_back( [&] { guy.wield( clothing ); } );
         }
     }
 }
References Character::invoke_item(), item::is_gun(), itype_shoulder_strap, PATH_INFO::options(), pgettext, string_format(), Character::wield(), and worn.
Referenced by fire().
first_item_covering_bp()
item_location outfit::first_item_covering_bp (Character & guy, bodypart_id bp)
Definition at line 2553 of file character_attire.cpp.
 {
     for( item &clothing : worn ) {
         if( clothing.covers( bp ) ) {
             return item_location( guy, &clothing );
         }
     }
     return item_location{};
 }
References bp, and worn.
Referenced by npc::wear_if_wanted().
free_holster_volume()
units::volume outfit::free_holster_volume () const
Definition at line 1686 of file character_attire.cpp.
 {
     units::volume holster_volume = 0_ml;
     for( const item &w : worn ) {
         holster_volume += w.get_total_holster_volume() - w.get_used_holster_volume();
     }
     return holster_volume;
 }
References holster_volume(), and worn.
Referenced by Character::free_holster_volume().
free_space()
units::volume outfit::free_space () const
Definition at line 1618 of file character_attire.cpp.
 {
     units::volume volume_capacity = 0_ml;
     for( const item &w : worn ) {
         volume_capacity += w.get_total_capacity();
         for( const item_pocket *pocket : w.get_all_contained_pockets() ) {
             if( pocket->contains_phase( phase_id::SOLID ) ) {
                 for( const item *it : pocket->all_items_top() ) {
                     volume_capacity -= it->volume();
                 }
             } else if( !pocket->empty() ) {
                 volume_capacity -= pocket->volume_capacity();
             }
         }
         volume_capacity += w.check_for_free_space();
     }
     return volume_capacity;
 }
References item::all_items_top(), SOLID, volume_capacity(), and worn.
Referenced by Character::free_space().
free_weight_capacity()
units::mass outfit::free_weight_capacity () const
Definition at line 1637 of file character_attire.cpp.
 {
     units::mass weight_capacity = 0_gram;
     for( const item &w : worn ) {
         weight_capacity += w.get_remaining_weight_capacity();
     }
     return weight_capacity;
 }
References worn.
Referenced by Character::free_weight_capacity().
front()
item & outfit::front ()
Definition at line 1852 of file character_attire.cpp.
 {
     return worn.front();
 }
References worn.
get_AIM_inventory()
std::vector< advanced_inv_listitem > outfit::get_AIM_inventory (size_t & item_index, avatar & you, const advanced_inventory_pane & pane, advanced_inv_area & square)
Definition at line 134 of file advanced_inv_pane.cpp.
 {
     std::vector<advanced_inv_listitem> items;
     for( item &worn_item : worn ) {
         if( worn_item.empty() || worn_item.has_flag( flag_NO_UNLOAD ) ) {
             continue;
         }
         for( const std::vector<item_location> &it_stack : item_list_to_stack(
                  item_location( you, &worn_item ),
                  worn_item.all_items_top( pocket_type::CONTAINER ) ) ) {
             advanced_inv_listitem adv_it( it_stack, item_index++, square.id, false );
             if( !pane.is_filtered( *adv_it.items.front() ) ) {
                 square.volume += adv_it.volume;
                 square.weight += adv_it.weight;
                 items.push_back( adv_it );
             }
         }
     }
     return items;
 }
References CONTAINER, flag_NO_UNLOAD, advanced_inventory_pane::is_filtered(), item_list_to_stack(), advanced_inv_listitem::items, square(), advanced_inv_listitem::volume, advanced_inv_listitem::weight, and worn.
Referenced by avatar::get_AIM_inventory().
get_armor_display()
std::string outfit::get_armor_display (bodypart_id bp) const
Definition at line 2586 of file character_attire.cpp.
 {
     for( auto it = worn.rbegin(); it != worn.rend(); ++it ) {
         if( it->covers( bp ) ) {
             return it->tname( 1 );
         }
     }
     return "-";
 }
References bp, item::covers(), item::tname(), and worn.
Referenced by widget::color_text_function_string().
get_coverage()
int outfit::get_coverage (bodypart_id bp, item::cover_type cover_type = item::cover_type::COVER_DEFAULT) const
Definition at line 1534 of file character_attire.cpp.
 {
     int total_cover = 0;
     for( const item &it : worn ) {
         if( it.covers( bp ) ) {
             total_cover += it.get_coverage( bp, cover_type );
         }
     }
     return total_cover;
 }
References bp, and worn.
Referenced by talker_character_const::coverage_at(), and npc::get_opinion_values().
get_eligible_containers_for_crafting()
void outfit::get_eligible_containers_for_crafting (std::vector< const item * > & conts) const
Definition at line 554 of file crafting.cpp.
 {
     for( const item &it : worn ) {
         std::vector<const item *> eligible = get_eligible_containers_recursive( it, false );
         conts.insert( conts.begin(), eligible.begin(), eligible.end() );
     }
 }
References get_eligible_containers_recursive(), and worn.
Referenced by Character::get_eligible_containers_for_crafting().
get_env_resist()
int outfit::get_env_resist (bodypart_id bp) const
Definition at line 1979 of file character_attire.cpp.
 {
     int ret = 0;
     for( const item &i : worn ) {
         // Head protection works on eyes too (e.g. baseball cap)
         if( i.covers( bp ) || ( bp == body_part_eyes && i.covers( body_part_head ) ) ) {
             ret += i.get_env_resist();
         }
     }
     return ret;
 }
References body_part_eyes, body_part_head, bp, cata::hash64_detail::ret, and worn.
Referenced by Character::get_env_resist().
get_item_penalties()
item_penalties outfit::get_item_penalties (std::list< item >::const_iterator worn_item_it, const Character & c, const bodypart_id & _bp)
Definition at line 456 of file armor_layers.cpp.
 {
     std::vector<layer_level> layer = worn_item_it->get_layer();
     std::vector<bodypart_id> body_parts_with_stacking_penalty;
     std::vector<bodypart_id> body_parts_with_out_of_order_penalty;
     std::vector<std::set<std::string>> lists_of_bad_items_within;
     for( const bodypart_id &bp : c.get_all_body_parts() ) {
         if( bp != _bp && _bp != bodypart_id( "bp_null" ) ) {
             continue;
         }
         if( !worn_item_it->covers( bp ) ) {
             continue;
         }
         std::set<std::string> bad_items_within;
         // if no subparts do the old way
         if( bp->sub_parts.empty() ) {
             std::vector<layer_level> layer = worn_item_it->get_layer( bp );
             bool first_integrated = true;
             const int num_items = std::count_if( worn.begin(), worn.end(),
             [layer, bp, &first_integrated]( const item & i ) {
                 if( i.has_layer( layer, bp ) && i.covers( bp ) && !i.has_flag( flag_SEMITANGIBLE ) ) {
                     if( i.has_flag( flag_INTEGRATED ) ) {
                         if( first_integrated ) {
                             first_integrated = false;
                             return true;
                         }
                         return false;
                     }
                     return true;
                 }
                 return false;
             } );
             if( num_items > 1 ) {
                 body_parts_with_stacking_penalty.push_back( bp );
             }
             for( auto it = worn.begin(); it != worn_item_it; ++it ) {
                 if( it->get_layer( bp ) > layer && it->covers( bp ) ) {
                     bad_items_within.insert( it->type_name() );
                 }
             }
         } else {
             for( const sub_bodypart_str_id &sbp : bp->sub_parts ) {
                 if( !worn_item_it->covers( sbp ) ) {
                     continue;
                 }
                 std::vector<layer_level> layer = worn_item_it->get_layer( sbp );
                 bool first_integrated = true;
                 const int num_items = std::count_if( worn.begin(), worn.end(),
                 [layer, bp, sbp, &first_integrated]( const item & i ) {
                     if( i.has_layer( layer, sbp ) && i.covers( bp ) && !i.has_flag( flag_SEMITANGIBLE ) &&
                         i.covers( sbp ) ) {
                         if( i.has_flag( flag_INTEGRATED ) ) {
                             if( first_integrated ) {
                                 first_integrated = false;
                                 return true;
                             }
                             return false;
                         }
                         return true;
                     }
                     return false;
                 } );
                 if( num_items > 1 ) {
                     body_parts_with_stacking_penalty.push_back( bp );
                 }
                 for( auto it = worn.begin(); it != worn_item_it; ++it ) {
                     if( it->covers( sbp ) ) {
                         if( it->get_highest_layer( sbp ) > worn_item_it->get_highest_layer( sbp ) ) {
                             bad_items_within.insert( it->type_name() );
                         }
                     }
                 }
             }
         }
         if( !bad_items_within.empty() ) {
             body_parts_with_out_of_order_penalty.push_back( bp );
             lists_of_bad_items_within.push_back( bad_items_within );
         }
     }
     // We intersect all the lists_of_bad_items_within so that if there is one
     // common bad item we're wearing this one over it can be mentioned in the
     // message explaining the penalty.
     while( lists_of_bad_items_within.size() > 1 ) {
         std::set<std::string> intersection_of_first_two;
         std::set_intersection(
             lists_of_bad_items_within[0].begin(), lists_of_bad_items_within[0].end(),
             lists_of_bad_items_within[1].begin(), lists_of_bad_items_within[1].end(),
             std::inserter( intersection_of_first_two, intersection_of_first_two.begin() )
         );
         lists_of_bad_items_within.erase( lists_of_bad_items_within.begin() );
         lists_of_bad_items_within[0] = std::move( intersection_of_first_two );
     }
     if( lists_of_bad_items_within.empty() ) {
         lists_of_bad_items_within.emplace_back();
     }
     return { std::move( body_parts_with_stacking_penalty ),
              std::move( body_parts_with_out_of_order_penalty ),
              std::move( lists_of_bad_items_within[0] ) };
 }
References bp, c, body_part_type::sub_parts, and worn.
Referenced by items_cover_bp(), and sort_armor().
get_item_position()
std::optional< int > outfit::get_item_position (const item & it) const
Definition at line 2563 of file character_attire.cpp.
 {
     int pos = 0;
     for( const item &clothing : worn ) {
         if( clothing.has_item( it ) ) {
             return pos;
         }
         pos++;
     }
     return std::nullopt;
 }
References math_opers::pos(), and worn.
Referenced by Character::get_item_position().
get_overlay_ids()
void outfit::get_overlay_ids (std::vector< std::pair< std::string, std::string >> & overlay_ids) const
Definition at line 1808 of file character_attire.cpp.
 {
     // TODO: worry about correct order of clothing overlays
     for( const item &worn_item : worn ) {
         if( worn_item.has_flag( json_flag_HIDDEN ) ) {
             continue;
         }
         if( worn_item.has_var( "sprite_override" ) ) {
             overlay_ids.emplace_back( "worn_" + worn_item.get_var( "sprite_override" ),
                                       worn_item.get_var( "sprite_override_variant", "" ) );
         } else {
             const std::string variant = worn_item.has_itype_variant() ? worn_item.itype_variant().id : "";
             overlay_ids.emplace_back( "worn_" + worn_item.typeId().str(), variant );
         }
     }
 }
References json_flag_HIDDEN, and worn.
Referenced by Character::get_overlay_ids().
get_visible_worn_items()
std::list< item > outfit::get_visible_worn_items (const Character & guy) const
Definition at line 1074 of file character_attire.cpp.
 {
     std::list<item> result;
     for( auto i = worn.cbegin(), end = worn.cend(); i != end; ++i ) {
         if( guy.is_worn_item_visible( i ) ) {
             result.push_back( *i );
         }
     }
     return result;
 }
References keycode::end, Character::is_worn_item_visible(), and worn.
Referenced by Character::get_visible_worn_items().
grab_drop_pockets() [1/2]
std::vector< item_pocket * > outfit::grab_drop_pockets ()
Definition at line 2650 of file character_attire.cpp.
 {
     std::vector<item_pocket *> pd;
     for( item &i : worn ) {
         if( i.has_ripoff_pockets() ) {
             for( item_pocket *pocket : i.get_all_contained_pockets() ) {
                 if( pocket->get_pocket_data()->ripoff > 0 && !pocket->empty() ) {
                     pd.push_back( pocket );
                 }
             }
         }
     }
     return pd;
 }
References item_pocket::empty(), item_pocket::get_pocket_data(), pocket_data::ripoff, and worn.
Referenced by melee_actor::call(), and Character::try_remove_grab().
grab_drop_pockets() [2/2]
std::vector< item_pocket * > outfit::grab_drop_pockets (const bodypart_id & bp)
Definition at line 2665 of file character_attire.cpp.
 {
     std::vector<item_pocket *> pd;
     for( item &i : worn ) {
         // Check if we wear it on the grabbed limb in the first place
         if( !is_wearing_on_bp( i.typeId(), bp ) ) {
             continue;
         }
         if( i.has_ripoff_pockets() ) {
             for( item_pocket *pocket : i.get_all_contained_pockets() ) {
                 if( pocket->get_pocket_data()->ripoff > 0 && !pocket->empty() ) {
                     pd.push_back( pocket );
                 }
             }
         }
     }
     return pd;
 }
References bp, item_pocket::empty(), item_pocket::get_pocket_data(), is_wearing_on_bp(), pocket_data::ripoff, and worn.
hands_conductive()
bool outfit::hands_conductive () const
Definition at line 2541 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         if( !i.conductive()
             && ( ( i.get_coverage( bodypart_id( "hand_l" ) ) >= 95 ) ||
                  i.get_coverage( bodypart_id( "hand_r" ) ) >= 95 ) ) {
             return false;
         }
     }
     return true;
 }
References worn.
holster_opts()
void outfit::holster_opts (std::vector< dispose_option > & opts, item_location obj, Character & guy)
Definition at line 692 of file character_inventory.cpp.
 {
     for( item &e : worn ) {
         // check for attachable subpockets first (the parent item may be defined as a holster)
         if( e.get_contents().has_additional_pockets() && e.can_contain( *obj ).success() ) {
             opts.emplace_back( dispose_option{
                 string_format( _( "Store in %s" ), e.tname() ), true, e.invlet,
                 guy.item_store_cost( *obj, e, false, e.insert_cost( *obj ) ),
                 [&guy, &e, obj] {
                     item &it = *item_location( obj );
                     guy.store( e, it, false, e.insert_cost( it ), pocket_type::CONTAINER, true );
                     return !guy.has_item( it );
                 }
             } );
             int pkt_idx = 0;
             for( const item *it : e.get_contents().get_added_pockets() ) {
                 item_pocket *con = const_cast<item_pocket *>( e.get_contents().get_added_pocket( pkt_idx++ ) );
                 if( !con || !con->can_contain( *obj ).success() ) {
                     continue;
                 }
                 opts.emplace_back( dispose_option{
                     string_format( "  >%s", it->tname() ), true, it->invlet,
                     guy.item_store_cost( *obj, *it, false, it->insert_cost( *obj ) ),
                     [&guy, it, con, obj] {
                         item &i = *item_location( obj );
                         guy.store( con, i, false, it->insert_cost( i ) );
                         return !guy.has_item( i );
                     }
                 } );
             }
         } else if( e.can_holster( *obj ) ) {
             const holster_actor *ptr = dynamic_cast<const holster_actor *>
                                        ( e.type->get_use( "holster" )->get_actor_ptr() );
             opts.emplace_back( dispose_option{
                 string_format( _( "Store in %s" ), e.tname() ), true, e.invlet,
                 guy.item_store_cost( *obj, e, false, e.insert_cost( *obj ) ),
                 [&guy, ptr, &e, obj] {
                     // *obj by itself attempts to use the const version of the operator (in gcc9),
                     // so construct a new item_location which allows using the non-const version
                     return ptr->store( guy, e, *item_location( obj ) );
                 }
             } );
         }
     }
 }
References _, item_pocket::can_contain(), CONTAINER, item_contents::get_added_pockets(), item::get_contents(), visitable::has_item(), item::insert_cost(), Character::item_store_cost(), Character::store(), string_format(), and worn.
Referenced by Character::dispose_item().
holster_volume()
units::volume outfit::holster_volume () const
Definition at line 1646 of file character_attire.cpp.
 {
     units::volume ret = 0_ml;
     for( const item &w : worn ) {
         if( w.is_holster() ) {
             ret += w.get_total_capacity();
         }
     }
     return ret;
 }
References cata::hash64_detail::ret, and worn.
Referenced by free_holster_volume(), and Character::holster_volume().
hood_warmth()
int outfit::hood_warmth () const
Definition at line 1742 of file character_attire.cpp.
 {
     int warmth = 0;
     for( const item &w : worn ) {
         if( w.has_flag( flag_HOOD ) ) {
             warmth = std::max( warmth, w.get_warmth() );
         }
     }
     return warmth;
 }
References flag_HOOD, max(), warmth(), and worn.
Referenced by Character::bonus_item_warmth().
i_at()
const item & outfit::i_at (int position) const
Definition at line 2575 of file character_attire.cpp.
 {
     if( static_cast<size_t>( position ) < worn.size() ) {
         auto iter = worn.begin();
         std::advance( iter, position );
         return *iter;
     } else {
         return null_item_reference();
     }
 }
References null_item_reference(), and worn.
Referenced by Character::i_at().
insert_item_at_index()
void outfit::insert_item_at_index (const item & clothing, int index)
Definition at line 2075 of file character_attire.cpp.
 {
     if( static_cast<size_t>( index ) >= worn.size() || index == INT_MIN ) {
         index = worn.size() - 1;
     }
     auto it = worn.begin();
     std::advance( it, index );
     worn.insert( it, clothing );
 }
References worn.
Referenced by game::wield().
inv_dump() [1/2]
void outfit::inv_dump (std::vector< const item * > & ret) const
Definition at line 1592 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         ret.push_back( &i );
     }
 }
References cata::hash64_detail::ret, and worn.
inv_dump() [2/2]
void outfit::inv_dump (std::vector< item * > & ret)
Definition at line 1583 of file character_attire.cpp.
 {
     for( item &i : worn ) {
         if( !i.has_flag( flag_INTEGRATED ) ) {
             ret.push_back( &i );
         }
     }
 }
References flag_INTEGRATED, cata::hash64_detail::ret, and worn.
Referenced by Character::inv_dump().
is_barefoot()
bool outfit::is_barefoot () const
Definition at line 1106 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         if( ( i.covers( sub_body_part_foot_sole_l ) && !i.has_flag( flag_INTEGRATED ) ) ||
             ( i.covers( sub_body_part_foot_sole_r ) && !i.has_flag( flag_INTEGRATED ) ) ) {
             return false;
         }
     }
     return true;
 }
References flag_INTEGRATED, sub_body_part_foot_sole_l, sub_body_part_foot_sole_r, and worn.
Referenced by Character::is_barefoot().
is_wearing_active_optcloak()
bool outfit::is_wearing_active_optcloak () const
Definition at line 1298 of file character_attire.cpp.
 {
     for( const item &w : worn ) {
         if( w.active && w.has_flag( flag_ACTIVE_CLOAKING ) ) {
             return true;
         }
     }
     return false;
 }
References flag_ACTIVE_CLOAKING, and worn.
Referenced by Character::is_wearing_active_optcloak().
is_wearing_active_power_armor()
bool outfit::is_wearing_active_power_armor () const
Definition at line 1288 of file character_attire.cpp.
 {
     for( const item &w : worn ) {
         if( w.is_power_armor() && w.active ) {
             return true;
         }
     }
     return false;
 }
References worn.
Referenced by attempt_recharge(), and Character::is_wearing_active_power_armor().
is_wearing_on_bp()
bool outfit::is_wearing_on_bp (const itype_id & clothing, const bodypart_id & bp) const
Definition at line 998 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         if( i.typeId() == clothing && i.covers( bp ) ) {
             return true;
         }
     }
     return false;
 }
References bp, and worn.
Referenced by grab_drop_pockets(), and Character::is_wearing_on_bp().
is_wearing_power_armor()
bool outfit::is_wearing_power_armor (bool * has_helmet = nullptr) const
Definition at line 1267 of file character_attire.cpp.
 {
     bool result = false;
     for( const item &elem : worn ) {
         if( !elem.is_power_armor() ) {
             continue;
         }
         if( has_helmet == nullptr ) {
             // found power armor, helmet not requested, cancel loop
             return true;
         }
         // found power armor, continue search for helmet
         result = true;
         if( elem.covers( body_part_head ) ) {
             *has_helmet = true;
             return true;
         }
     }
     return result;
 }
References body_part_head, and worn.
Referenced by Character::is_wearing_power_armor(), and power_armor_conflicts().
is_wearing_shoes()
side outfit::is_wearing_shoes (const bodypart_id & bp) const
Definition at line 598 of file character_attire.cpp.
 {
     bool any_left_foot_is_covered = false;
     bool any_right_foot_is_covered = false;
     const auto exempt = []( const item & worn_item ) {
         return worn_item.has_flag( flag_BELTED ) ||
                worn_item.has_flag( flag_PERSONAL ) ||
                worn_item.has_flag( flag_AURA ) ||
                worn_item.has_flag( flag_SEMITANGIBLE ) ||
                worn_item.has_flag( flag_SKINTIGHT );
     };
     for( const item &worn_item : worn ) {
         // ... wearing...
         if( !worn_item.covers( bp ) ) {
             continue;
         }
         // ... a shoe?
         if( exempt( worn_item ) ) {
             continue;
         }
         any_left_foot_is_covered = bp->part_side == side::LEFT ||
                                    bp->part_side == side::BOTH ||
                                    any_left_foot_is_covered;
         any_right_foot_is_covered = bp->part_side == side::RIGHT ||
                                     bp->part_side == side::BOTH ||
                                     any_right_foot_is_covered;
     }
     if( any_left_foot_is_covered && any_right_foot_is_covered ) {
         return side::BOTH;
     } else if( any_left_foot_is_covered ) {
         return side::LEFT;
     } else if( any_right_foot_is_covered ) {
         return side::RIGHT;
     } else {
         return side::num_sides;
     }
 }
References BOTH, bp, flag_AURA, flag_BELTED, flag_PERSONAL, flag_SEMITANGIBLE, flag_SKINTIGHT, LEFT, num_sides, body_part_type::part_side, RIGHT, and worn.
Referenced by Character::is_wearing_shoes().
is_worn() [1/2]
bool outfit::is_worn (const item & clothing) const
Definition at line 970 of file character_attire.cpp.
 {
     for( const item &elem : worn ) {
         if( &clothing == &elem ) {
             return true;
         }
     }
     return false;
 }
References worn.
Referenced by Character::can_takeoff(), Character::is_wearing(), and Character::is_worn().
is_worn() [2/2]
bool outfit::is_worn (const itype_id & clothing) const
Definition at line 980 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         if( i.typeId() == clothing ) {
             return true;
         }
     }
     return false;
 }
References worn.
is_worn_item_visible()
bool outfit::is_worn_item_visible (std::list< item >::const_iterator worn_item, const body_part_set & worn_item_body_parts) const
Definition at line 1022 of file character_attire.cpp.
 {
     return std::any_of( worn_item_body_parts.begin(), worn_item_body_parts.end(),
     [this, &worn_item]( const bodypart_str_id & bp ) {
         // no need to check items that are worn under worn_item in the armor sort order
         for( auto i = std::next( worn_item ), end = worn.end(); i != end; ++i ) {
             if( i->covers( bp ) && i->has_layer( { layer_level::BELTED, layer_level::WAIST } ) &&
                 i->get_coverage( bp ) >= worn_item->get_coverage( bp ) ) {
                 return false;
             }
         }
         return true;
     } );
 }
References body_part_set::begin(), bp, and body_part_set::end().
Referenced by Character::is_worn_item_visible().
is_worn_module()
bool outfit::is_worn_module (const item & thing) const
Definition at line 989 of file character_attire.cpp.
 {
     return thing.has_flag( flag_CANT_WEAR ) &&
     std::any_of( worn.cbegin(), worn.cend(), [&thing]( item const & elem ) {
         return elem.contained_where( thing ) != nullptr;
     } );
 }
References flag_CANT_WEAR, item::has_flag(), and worn.
Referenced by Character::is_worn_module().
item_encumb()
void outfit::item_encumb (std::map< bodypart_id, encumbrance_data > & vals, const item & new_item, const Character & guy) const
Applies encumbrance from items only If new_item is not null, then calculate under the assumption that it is added to existing work items.
Definition at line 916 of file character_attire.cpp.
 {
     // reset all layer data
     vals = std::map<bodypart_id, encumbrance_data>();
     // Figure out where new_item would be worn
     std::list<item>::const_iterator new_item_position = worn.end();
     if( !new_item.is_null() ) {
         // const_cast required to work around g++-4.8 library bug
         // see the commit that added this comment to understand why
         new_item_position =
             const_cast<outfit *>( this )->position_to_wear_new_item( new_item );
     }
     // Track highest layer observed so far so we can penalize out-of-order
     // items
     std::map<sub_bodypart_id, layer_level> highest_layer_so_far;
     for( auto w_it = worn.begin(); w_it != worn.end(); ++w_it ) {
         if( w_it == new_item_position ) {
             layer_item( vals, new_item, highest_layer_so_far, guy );
         }
         layer_item( vals, *w_it, highest_layer_so_far, guy );
     }
     if( worn.end() == new_item_position && !new_item.is_null() ) {
         layer_item( vals, new_item, highest_layer_so_far, guy );
     }
     // make sure values are sane
     for( const bodypart_id &bp : guy.get_all_body_parts() ) {
         encumbrance_data &elem = vals[bp];
         for( const layer_details &cur_layer : elem.layer_penalty_details ) {
             // only apply the layers penalty to the limb if it is conflicting
             if( cur_layer.is_conflicting ) {
                 elem.layer_penalty += cur_layer.total;
             }
         }
         elem.armor_encumbrance = std::max( 0, elem.armor_encumbrance );
         // Add armor and layering penalties for the final values
         elem.encumbrance += elem.armor_encumbrance + elem.layer_penalty;
     }
 }
References encumbrance_data::armor_encumbrance, bp, encumbrance_data::encumbrance, Creature::get_all_body_parts(), layer_details::is_conflicting, item::is_null(), layer_item(), encumbrance_data::layer_penalty, encumbrance_data::layer_penalty_details, max(), position_to_wear_new_item(), layer_details::total, and worn.
Referenced by Character::calc_encumbrance().
item_worn_with_flag() [1/2]
item outfit::item_worn_with_flag (const flag_id & f) const
Definition at line 1050 of file character_attire.cpp.
 {
     item it_with_flag;
     for( const item &it : worn ) {
         if( it.has_flag( f ) ) {
             it_with_flag = it;
             break;
         }
     }
     return it_with_flag;
 }
References worn.
item_worn_with_flag() [2/2]
item outfit::item_worn_with_flag (const flag_id & f, const bodypart_id & bp) const
Definition at line 1038 of file character_attire.cpp.
 {
     item it_with_flag;
     for( const item &it : worn ) {
         if( it.has_flag( f ) && ( bp == bodypart_str_id::NULL_ID() || it.covers( bp ) ) ) {
             it_with_flag = it;
             break;
         }
     }
     return it_with_flag;
 }
References bp, string_id< body_part_type >::NULL_ID(), and worn.
Referenced by Character::item_worn_with_flag().
item_worn_with_id()
item * outfit::item_worn_with_id (const itype_id & i)
Definition at line 1062 of file character_attire.cpp.
 {
     item *it_with_id = nullptr;
     for( item &it : worn ) {
         if( it.typeId() == i ) {
             it_with_id = &it;
             break;
         }
     }
     return it_with_id;
 }
References worn.
Referenced by Character::item_worn_with_id().
item_worn_with_inv_let()
std::optional< const item * > outfit::item_worn_with_inv_let (char invlet) const
Definition at line 588 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         if( i.invlet == invlet ) {
             return &i;
         }
     }
     return std::nullopt;
 }
References worn.
items_cover_bp()
std::vector< layering_item_info > outfit::items_cover_bp (const Character & c, const bodypart_id & bp)
Definition at line 565 of file armor_layers.cpp.
 {
     std::vector<layering_item_info> s;
     for( auto elem_it = worn.begin(); elem_it != worn.end(); ++elem_it ) {
         if( elem_it->covers( bp ) ) {
             s.push_back( { get_item_penalties( elem_it, c, bp ),
                            elem_it->get_encumber( c, bp ),
                            elem_it->tname()
                          } );
         }
     }
     return s;
 }
References bp, c, get_item_penalties(), and worn.
Referenced by sort_armor().
max_single_item_length()
units::length outfit::max_single_item_length () const
Definition at line 2085 of file character_attire.cpp.
 {
     units::length ret = 0_mm;
     for( const item &worn_it : worn ) {
         units::length candidate = worn_it.max_containable_length();
         if( candidate > ret ) {
             ret = candidate;
         }
     }
     return ret;
 }
References cata::hash64_detail::ret, and worn.
Referenced by Character::max_single_item_length().
max_single_item_volume()
units::volume outfit::max_single_item_volume () const
Definition at line 2097 of file character_attire.cpp.
 {
     units::volume ret = 0_ml;
     for( const item &worn_it : worn ) {
         units::volume candidate = worn_it.max_containable_volume();
         if( candidate > ret ) {
             ret = candidate;
         }
     }
     return ret;
 }
References cata::hash64_detail::ret, and worn.
Referenced by Character::max_single_item_volume().
natural_attack_restricted_on() [1/2]
bool outfit::natural_attack_restricted_on (const bodypart_id & bp) const
Definition at line 1146 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         if( i.covers( bp ) && check_natural_attack_restricted_on_worn( i ) ) {
             return true;
         }
     }
     return false;
 }
References bp, check_natural_attack_restricted_on_worn(), and worn.
Referenced by Character::natural_attack_restricted_on().
natural_attack_restricted_on() [2/2]
bool outfit::natural_attack_restricted_on (const sub_bodypart_id & bp) const
Definition at line 1156 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         if( i.covers( bp ) && check_natural_attack_restricted_on_worn( i ) ) {
             return true;
         }
     }
     return false;
 }
References bp, check_natural_attack_restricted_on_worn(), and worn.
on_item_wear()
void outfit::on_item_wear (Character & guy)
Definition at line 2160 of file character_attire.cpp.
 {
     for( item &clothing : worn ) {
         if( clothing.relic_data && clothing.type->relic_data ) {
             clothing.relic_data = clothing.type->relic_data;
         }
         guy.on_item_wear( clothing );
     }
 }
References Character::on_item_wear(), and worn.
on_takeoff()
void outfit::on_takeoff (Character & guy)
Definition at line 2153 of file character_attire.cpp.
 {
     for( item &it : worn ) {
         it.on_takeoff( guy );
     }
 }
References worn.
Referenced by starting_clothes().
one_per_layer_change_side()
bool outfit::one_per_layer_change_side (item & it, const Character & guy) const
Definition at line 717 of file character_attire.cpp.
 {
     // test with a swapped side
     item it_copy( it );
     it_copy.swap_side();
     const bool item_one_per_layer = it_copy.has_flag( json_flag_ONE_PER_LAYER );
     for( const item &worn_item : worn ) {
         if( item_one_per_layer && worn_item.has_flag( json_flag_ONE_PER_LAYER ) ) {
             const std::optional<side> sidedness_conflict = it_copy.covers_overlaps( worn_item );
             if( sidedness_conflict ) {
                 const std::string player_msg = string_format(
                                                    _( "Your %s conflicts with %s, so you cannot swap its side." ),
                                                    it_copy.tname(), worn_item.tname() );
                 const std::string npc_msg = string_format(
                                                 _( "<npcname>'s %s conflicts with %s so they cannot swap its side." ),
                                                 it_copy.tname(), worn_item.tname() );
                 guy.add_msg_player_or_npc( m_info, player_msg, npc_msg );
                 return false;
             }
         }
     }
     return true;
 }
References _, Character::add_msg_player_or_npc(), item::covers_overlaps(), item::has_flag(), json_flag_ONE_PER_LAYER, m_info, string_format(), item::swap_side(), item::tname(), and worn.
Referenced by Character::change_side().
one_per_layer_sidedness()
void outfit::one_per_layer_sidedness (item & clothing) const
Definition at line 1449 of file character_attire.cpp.
 {
     const bool item_one_per_layer = clothing.has_flag( json_flag_ONE_PER_LAYER );
     for( const item &worn_item : worn ) {
         const std::optional<side> sidedness_conflict = clothing.covers_overlaps( worn_item );
         if( sidedness_conflict && ( item_one_per_layer ||
                                     worn_item.has_flag( json_flag_ONE_PER_LAYER ) ) ) {
             // we can assume both isn't an option because it'll be caught in can_wear
             if( *sidedness_conflict == side::LEFT ) {
                 clothing.set_side( side::RIGHT );
             } else {
                 clothing.set_side( side::LEFT );
             }
         }
     }
 }
References item::covers_overlaps(), item::has_flag(), json_flag_ONE_PER_LAYER, LEFT, RIGHT, item::set_side(), and worn.
Referenced by Character::wear().
only_one_conflicts()
ret_val< void > outfit::only_one_conflicts (const item & clothing) const
Definition at line 1342 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         ret_val<void> result = test_only_one_conflicts( clothing, i );
         if( !result.success() ) {
             return result;
         }
         if( i.is_ablative() ) {
             // if item has ablative armor we should check those too.
             for( const item *ablative_armor : i.all_ablative_armor() ) {
                 result = test_only_one_conflicts( clothing, *ablative_armor );
                 if( !result.success() ) {
                     return result;
                 }
             }
         }
     }
     return ret_val<void>::make_success();
 }
References item::all_ablative_armor(), ret_val< T >::make_success(), ret_val_common::success(), test_only_one_conflicts(), and worn.
Referenced by Character::can_wear().
organize_items_menu()
void outfit::organize_items_menu ()
Definition at line 2684 of file character_attire.cpp.
 {
     std::vector<item *> to_organize;
     for( item &i : worn ) {
         to_organize.push_back( &i );
     }
     pocket_management_menu( _( "Inventory Organization" ), to_organize );
 }
References _, pocket_management_menu(), and worn.
Referenced by inventory_pick_selector::execute().
overflow()
void outfit::overflow (Character & guy)
Definition at line 2127 of file character_attire.cpp.
 {
     for( item_location &clothing : top_items_loc( guy ) ) {
         clothing.overflow();
     }
 }
References top_items_loc().
Referenced by Character::drop_invalid_inventory().
pickup_stash()
void outfit::pickup_stash (const item & newit, int & remaining_charges, bool ignore_pkt_settings = false)
Definition at line 2388 of file character_attire.cpp.
 {
     for( item &i : worn ) {
         if( remaining_charges == 0 ) {
             break;
         }
         if( i.can_contain_partial( newit ).success() ) {
             const int used_charges =
                 i.fill_with( newit, remaining_charges, false, false, ignore_pkt_settings );
             remaining_charges -= used_charges;
         }
     }
 }
References worn.
Referenced by add_stash().
pocket_warmth()
int outfit::pocket_warmth () const
Definition at line 1731 of file character_attire.cpp.
 {
     int warmth = 0;
     for( const item &w : worn ) {
         if( w.has_flag( flag_POCKETS ) ) {
             warmth = std::max( warmth, w.get_warmth() );
         }
     }
     return warmth;
 }
References flag_POCKETS, max(), warmth(), and worn.
Referenced by Character::bonus_item_warmth().
position_to_wear_new_item()
std::list< item >::iterator outfit::position_to_wear_new_item (const item & new_item)
Definition at line 1825 of file character_attire.cpp.
 {
     // By default we put this item on after the last item on the same or any
     // lower layer. Integrated armor goes under normal armor.
     return std::find_if(
                worn.rbegin(), worn.rend(),
     [&]( const item & w ) {
         if( w.has_flag( flag_INTEGRATED ) == new_item.has_flag( flag_INTEGRATED ) ) {
             return w.get_layer() <= new_item.get_layer();
         } else {
             return w.has_flag( flag_INTEGRATED );
         }
     }
            ).base();
 }
References worn.
Referenced by item_encumb(), and wear_item().
power_armor_conflicts()
ret_val< void > outfit::power_armor_conflicts (const item & clothing) const
Definition at line 1222 of file character_attire.cpp.
 {
     if( clothing.is_power_armor() ) {
         for( const item &elem : worn ) {
             // Allow power armor with compatible parts and integrated (Subdermal CBM and mutant skin armor)
             if( elem.get_covered_body_parts().make_intersection( clothing.get_covered_body_parts() ).any() &&
                 !elem.has_flag( flag_POWERARMOR_COMPATIBLE ) && !elem.has_flag( flag_INTEGRATED ) &&
                 !elem.has_flag( flag_AURA ) ) {
                 return ret_val<void>::make_failure( _( "Can't wear power armor over other gear!" ) );
             }
         }
         if( !clothing.covers( body_part_torso ) ) {
             bool power_armor = false;
             for( const item &elem : worn ) {
                 if( elem.is_power_armor() ) {
                     power_armor = true;
                     break;
                 }
             }
             if( !power_armor ) {
                 return ret_val<void>::make_failure(
                            _( "You can only wear power armor components with power armor!" ) );
             }
         }
         for( const item &i : worn ) {
             if( i.is_power_armor() && i.typeId() == clothing.typeId() ) {
                 return ret_val<void>::make_failure( _( "Can't wear more than one %s!" ), clothing.tname() );
             }
         }
     } else {
         // You can only wear headgear or non-covering items with power armor, except other power armor components.
         // You can't wear headgear if power armor helmet is already sitting on your head.
         bool has_helmet = false;
         if( !clothing.get_covered_body_parts().none() && !clothing.has_flag( flag_POWERARMOR_COMPATIBLE ) &&
             !clothing.has_flag( flag_AURA ) &&
             ( is_wearing_power_armor( &has_helmet ) &&
               ( has_helmet || !( clothing.covers( body_part_head ) || clothing.covers( body_part_mouth ) ||
                                  clothing.covers( body_part_eyes ) ) ) ) ) {
             return ret_val<void>::make_failure( _( "Can't wear %s with power armor!" ), clothing.tname() );
         }
     }
     return ret_val<void>::make_success();
 }
References _, body_part_eyes, body_part_head, body_part_mouth, body_part_torso, item::covers(), flag_AURA, flag_INTEGRATED, flag_POWERARMOR_COMPATIBLE, item::get_covered_body_parts(), item::has_flag(), item::is_power_armor(), is_wearing_power_armor(), ret_val< T >::make_failure(), ret_val< T >::make_success(), body_part_set::none(), item::tname(), item::typeId(), and worn.
Referenced by Character::can_wear().
prepare_bodymap_info()
void outfit::prepare_bodymap_info (bodygraph_info & info, const bodypart_id & bp, const std::set< sub_bodypart_id > & sub_parts, const Character & person) const
Definition at line 2254 of file character_attire.cpp.
 {
     std::map<sub_bodypart_id, resistances> best_cases;
     std::map<sub_bodypart_id, resistances> median_cases;
     std::map<sub_bodypart_id, resistances> worst_cases;
     // general body part stats
     info.part_hp_cur = person.get_part_hp_cur( bp );
     info.part_hp_max = person.get_part_hp_max( bp );
     info.wetness = person.get_part_wetness_percentage( bp );
     info.temperature = { units::to_legacy_bodypart_temp( person.get_part_temp_conv( bp ) ), display::bodytemp_color( person, bp ) };
     std::pair<std::string, nc_color> tmp_approx = display::temp_text_color( person, bp.id() );
     info.temp_approx = colorize( tmp_approx.first, tmp_approx.second );
     info.parent_bp_name = uppercase_first_letter( bp->name.translated() );
     // body part effects
     for( const effect &eff : person.get_effects() ) {
         if( eff.get_bp() == bp ) {
             info.effects.emplace_back( eff );
         }
     }
     // go through every item and see how it handles these part(s) of the character
     for( const item &armor : worn ) {
         // check if it covers the part
         // FIXME: item::covers( const sub_bodypart_id & ) always
         // returns true if there is no sub_data (ex: hairpin),
         // so use item::get_covered_sub_body_parts() instead
         bool covered = false;
         if( sub_parts.empty() || sub_parts.size() > 1 ) {
             covered = armor.covers( bp );
         } else {
             info.specific_sublimb = true;
             const std::vector<sub_bodypart_id> splist = armor.get_covered_sub_body_parts();
             if( std::find( splist.begin(), splist.end(), *sub_parts.begin() ) != splist.end() ) {
                 covered = true;
             }
         }
         if( !covered ) {
             // some clothing flags provide warmth without providing coverage or encumberance
             // these are included in the worn list so that players aren't confused about why body parts are warm
             // but not included in the later coverage and encumberance calculations
             if( ( bp == body_part_hand_l || bp == body_part_hand_r ) && armor.has_flag( flag_POCKETS ) &&
                 person.can_use_pockets() ) {
                 //~ name of a clothing/armor item, indicating it has pockets providing hand warmth
                 info.worn_names.push_back( string_format( _( "%s (pockets)" ), armor.tname() ) );
             }
             if( bp == body_part_head && armor.has_flag( flag_HOOD ) && person.can_use_hood() ) {
                 //~ name of a clothing/armor item, indicating it has a hood providing head warmth
                 info.worn_names.push_back( string_format( _( "%s (hood)" ), armor.tname() ) );
             }
             if( bp == body_part_mouth && armor.has_flag( flag_COLLAR ) && person.can_use_collar() ) {
                 // collars don't cover or encumber, but do conditionally provide warmth
                 //~ name of a clothing/armor item, indicating it has a collar providing mouth warmth
                 info.worn_names.push_back( string_format( _( "%s (collar)" ), armor.tname() ) );
             }
             continue;
         }
         info.worn_names.push_back( armor.tname() );
         info.total_encumbrance += armor.get_encumber( person, bp );
         // need to average the coverage on each sub part based on size
         int temp_coverage = 0;
         if( sub_parts.size() == 1 ) {
             temp_coverage = armor.get_coverage( *sub_parts.begin() );
         } else {
             // bp armor already has averaged coverage
             temp_coverage = armor.get_coverage( bp );
         }
         info.avg_coverage += temp_coverage;
         // need to do each sub part seperately and then average them if need be
         for( const sub_bodypart_id &sbp : sub_parts ) {
             int coverage = armor.get_coverage( sbp );
             // get worst case armor protection
             // if it doesn't 100% cover it may not protect you
             if( coverage == 100 ) {
                 worst_cases[sbp] += resistances( armor, false, 99, sbp );
             }
             // get median case armor protection
             // if it doesn't at least 50% cover it may not protect you
             if( coverage >= 50 ) {
                 median_cases[sbp] += resistances( armor, false, 50, sbp );
             }
             // get best case armor protection
             best_cases[sbp] += resistances( armor, false, 0, sbp );
         }
     }
     // need to average the protection values on each sublimb for full limbs
     if( sub_parts.size() == 1 ) {
         info.worst_case += worst_cases[*sub_parts.begin()];
         info.median_case += median_cases[*sub_parts.begin()];
         info.best_case += best_cases[*sub_parts.begin()];
     } else {
         for( const sub_bodypart_id &sbp : sub_parts ) {
             float scale_factor = static_cast<float>( sbp->max_coverage ) / 100.0f;
             info.worst_case += worst_cases[sbp] * scale_factor;
             info.median_case += median_cases[sbp] * scale_factor;
             info.best_case += best_cases[sbp] * scale_factor;
         }
     }
     // finally average the at this point cumulative average coverage by the number of articles
     if( !info.worn_names.empty() ) {
         info.avg_coverage = info.avg_coverage / info.worn_names.size();
     }
 }
References _, bodygraph_info::avg_coverage, bodygraph_info::best_case, body_part_hand_l, body_part_hand_r, body_part_head, body_part_mouth, display::bodytemp_color(), bp, Character::can_use_collar(), Character::can_use_hood(), Character::can_use_pockets(), colorize(), bodygraph_info::effects, flag_COLLAR, flag_HOOD, flag_POCKETS, Creature::get_effects(), Creature::get_part_hp_cur(), Creature::get_part_hp_max(), Creature::get_part_temp_conv(), Creature::get_part_wetness_percentage(), int_id< T >::id(), bodygraph_info::median_case, body_part_type::name, bodygraph_info::parent_bp_name, bodygraph_info::part_hp_cur, bodygraph_info::part_hp_max, bodygraph_info::specific_sublimb, string_format(), bodygraph_info::temp_approx, display::temp_text_color(), bodygraph_info::temperature, units::to_legacy_bodypart_temp(), bodygraph_info::total_encumbrance, translation::translated(), uppercase_first_letter(), bodygraph_info::wetness, worn, bodygraph_info::worn_names, and bodygraph_info::worst_case.
Referenced by bodygraph_display::prepare_infolist().
recalc_ablative_blocking()
void outfit::recalc_ablative_blocking (const Character * guy)
Definition at line 397 of file character_attire.cpp.
 {
     std::set<sub_bodypart_id> rigid_locations;
     // get all rigid locations
     // ablative pocketed armor shouldn't block adding ablative pieces
     for( const item &w : worn ) {
         if( w.is_rigid() && !w.is_ablative() ) {
             for( const sub_bodypart_id &sbp : w.get_covered_sub_body_parts() ) {
                 if( w.is_bp_rigid( sbp ) ) {
                     rigid_locations.emplace( sbp );
                 }
             }
         }
     }
     bool should_warn = false;
     // pass that info to all the ablative pockets
     for( item &w : worn ) {
         if( w.is_ablative() ) {
             should_warn = true;
             for( item_pocket *p : w.get_all_ablative_pockets() ) {
                 p->set_no_rigid( rigid_locations );
             }
         }
     }
     if( should_warn && !rigid_locations.empty() ) {
         guy->add_msg_if_player( m_warning,
                                 _( "You are wearing rigid armor with armor that has pockets for armor.  Until hard armor is removed inserting plates on those locations will be disabled." ) );
     }
 }
References _, Character::add_msg_if_player(), m_warning, and worn.
Referenced by Character::Character(), Character::takeoff(), and wear_item().
remove_items_with()
std::list< item > outfit::remove_items_with (Character & guy, const std::function< bool(const item &)> & filter, int & count)
Definition at line 623 of file visitable.cpp.
 {
     std::list<item> res;
     for( auto iter = worn.begin(); iter != worn.end(); ) {
         if( filter( *iter ) ) {
             iter->on_takeoff( guy );
             res.splice( res.end(), worn, iter++ );
             if( --count == 0 ) {
                 return res;
             }
         } else {
             iter->remove_internal( filter, count, res );
             if( count == 0 ) {
                 return res;
             }
             ++iter;
         }
     }
     return res;
 }
References filter, and worn.
remove_worn_items_with()
std::list< item > outfit::remove_worn_items_with (const std::function< bool(item &)> & filter, Character & guy)
Definition at line 1166 of file character_attire.cpp.
 {
     std::list<item> result;
     for( auto iter = worn.begin(); iter != worn.end(); ) {
         if( filter( *iter ) ) {
             iter->on_takeoff( guy );
             result.splice( result.begin(), worn, iter++ );
         } else {
             ++iter;
         }
     }
     return result;
 }
References filter, and worn.
Referenced by Character::remove_worn_items_with().
serialize()
void outfit::serialize (JsonOut & json) const
Definition at line 2596 of file character_attire.cpp.
 {
     json.start_object();
     json.member( "worn", worn );
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and worn.
set_fitted()
void outfit::set_fitted ()
Definition at line 2144 of file character_attire.cpp.
 {
     for( item &clothing : worn ) {
         if( clothing.has_flag( flag_VARSIZE ) ) {
             clothing.set_flag( flag_FIT );
         }
     }
 }
References flag_FIT, flag_VARSIZE, and worn.
Referenced by standard_npc::standard_npc().
size()
size_t outfit::size () const
Definition at line 965 of file character_attire.cpp.
 {
     return worn.size();
 }
References worn.
Referenced by advanced_inv_area::get_item_count(), and npc::wear_if_wanted().
small_pocket_volume()
units::volume outfit::small_pocket_volume (const units::volume & threshold) const
Definition at line 1695 of file character_attire.cpp.
 {
     units::volume small_spaces = 0_ml;
     for( const item &w : worn ) {
         if( !w.is_holster() ) {
             for( const item_pocket *pocket : w.get_all_contained_pockets() ) {
                 if( pocket->volume_capacity() <= threshold ) {
                     small_spaces += pocket->volume_capacity();
                 }
             }
         }
     }
     return small_spaces;
 }
References worn.
Referenced by Character::small_pocket_volume().
sort_armor()
void outfit::sort_armor (Character & guy)
Draws the UI and handles player input for the armor re-ordering window.
Definition at line 605 of file armor_layers.cpp.
 {
     // FIXME: get_all_body_parts() doesn't return a sorted list
     //        and bodypart_id is not compatible with std::sort()
     //        so let's use a dirty hack
     cata::flat_set<bodypart_id> armor_cat;
     for( const bodypart_id &it : guy.get_all_body_parts() ) {
         armor_cat.insert( it );
     }
     armor_cat.insert( bodypart_id( "bp_null" ) );
     const int num_of_parts = guy.get_all_body_parts().size();
     int win_h = 0;
     int win_w = 0;
     point win;
     int cont_h   = 0;
     int left_w   = 0;
     int right_w  = 0;
     int middle_w = 0;
     int encumb_top = 0;
     int tabindex = 0;
     const int tabcount = num_of_parts + 1;
     int leftListIndex  = 0;
     int leftListOffset = 0;
     int selected       = -1;
     int rightListOffset = 0;
     int leftListLines = 0;
     int rightListLines = 0;
     std::vector<std::list<item>::iterator> tmp_worn;
     // Layout window
     catacurses::window w_sort_armor;
     // Subwindows (between lines)
     catacurses::window w_sort_cat;
     catacurses::window w_sort_left;
     catacurses::window w_sort_middle;
     catacurses::window w_sort_right;
     catacurses::window w_encumb;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         win_h = TERMY;
         win_w = FULL_SCREEN_WIDTH + ( TERMX - FULL_SCREEN_WIDTH ) * 3 / 4;
         win.x = TERMX / 2 - win_w / 2;
         win.y = TERMY / 2 - win_h / 2;
         cont_h = win_h - 4;
         left_w = ( win_w - 4 ) / 3;
         right_w = left_w;
         middle_w = ( win_w - 4 ) - left_w - right_w;
         leftListLines = rightListLines = cont_h - 2;
         w_sort_armor = catacurses::newwin( win_h, win_w, win );
         w_sort_cat = catacurses::newwin( 1, win_w - 4, win + point( 2, 1 ) );
         w_sort_left = catacurses::newwin( cont_h, left_w, win + point( 1, 3 ) );
         w_sort_middle = catacurses::newwin( cont_h - num_of_parts - 2, middle_w,
                                             win + point( 2 + left_w, 3 ) );
         w_sort_right = catacurses::newwin( cont_h, right_w,
                                            win + point( 3 + left_w + middle_w, 3 ) );
         encumb_top = -1 + 3 + cont_h - num_of_parts;
         w_encumb = catacurses::newwin( num_of_parts + 1, middle_w,
                                        win + point( 2 + left_w, encumb_top ) );
         ui.position_from_window( w_sort_armor );
     } );
     ui.mark_resize();
     input_context ctxt( "SORT_ARMOR" );
     ctxt.register_cardinal();
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "PREV_TAB" );
     ctxt.register_action( "NEXT_TAB" );
     ctxt.register_action( "PAGE_UP" );
     ctxt.register_action( "PAGE_DOWN" );
     ctxt.register_action( "MOVE_ARMOR" );
     ctxt.register_action( "CHANGE_SIDE" );
     ctxt.register_action( "TOGGLE_CLOTH" );
     ctxt.register_action( "ASSIGN_INVLETS" );
     ctxt.register_action( "SORT_ARMOR" );
     ctxt.register_action( "EQUIP_ARMOR" );
     ctxt.register_action( "EQUIP_ARMOR_HERE" );
     ctxt.register_action( "REMOVE_ARMOR" );
     ctxt.register_action( "USAGE_HELP" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "SCROLL_ITEM_INFO_UP" );
     ctxt.register_action( "SCROLL_ITEM_INFO_DOWN" );
     Character &player_character = get_player_character();
     auto do_return_entry = [&player_character]() {
         player_character.assign_activity( ACT_ARMOR_LAYERS, 0 );
         player_character.activity.auto_resume = true;
         player_character.activity.moves_left = INT_MAX;
     };
     int leftListSize = 0;
     int rightListSize = 0;
     mid_pane_status mid_pane;
     mid_pane.size = 0;
     mid_pane.offset = 0;
     mid_pane.header_lines = 1;
     ui.on_redraw( [&]( ui_adaptor & ui ) {
         // Create ptr list of items to display
         tmp_worn.clear();
         const bodypart_id &bp = armor_cat[ tabindex ];
         if( bp == bodypart_id( "bp_null" ) ) {
             // All
             for( auto it = worn.begin(); it != worn.end(); ++it ) {
                 tmp_worn.push_back( it );
             }
         } else {
             // bp_*
             for( auto it = worn.begin(); it != worn.end(); ++it ) {
                 if( it->covers( bp ) ) {
                     tmp_worn.push_back( it );
                 }
             }
         }
         // Ensure leftListIndex is in bounds
         int new_index_upper_bound = std::max( 0, leftListSize - 1 );
         leftListIndex = std::min( leftListIndex, new_index_upper_bound );
         draw_grid( w_sort_armor, left_w, middle_w, encumb_top );
         werase( w_sort_cat );
         werase( w_sort_left );
         werase( w_sort_middle );
         werase( w_sort_right );
         werase( w_encumb );
         // top bar
         std::string header_title = _( "Sort Armor" );
         wprintz( w_sort_cat, c_white, header_title );
         std::string temp = bp != bodypart_id( "bp_null" ) ? body_part_name_as_heading( bp, 1 ) : _( "All" );
         temp = string_format( "  << %s >>", temp );
         wprintz( w_sort_cat, c_yellow, temp );
         int keyhint_offset = utf8_width( header_title ) + utf8_width( temp ) + 1;
         right_print( w_sort_cat, 0, 0, c_white, trim_by_length( string_format(
                          _( "[<color_yellow>%s</color>] Hide sprite.  "
                             "[<color_yellow>%s</color>] Change side.  "
                             "Press [<color_yellow>%s</color>] for help.  "
                             "Press [<color_yellow>%s</color>] to change keybindings." ),
                          ctxt.get_desc( "TOGGLE_CLOTH" ),
                          ctxt.get_desc( "CHANGE_SIDE" ),
                          ctxt.get_desc( "USAGE_HELP" ),
                          ctxt.get_desc( "HELP_KEYBINDINGS" ) ), getmaxx( w_sort_cat ) - keyhint_offset ) );
         leftListSize = tmp_worn.size();
         if( leftListLines > leftListSize ) {
             leftListOffset = 0;
         } else if( leftListOffset + leftListLines > leftListSize ) {
             leftListOffset = leftListSize - leftListLines;
         }
         if( leftListOffset > leftListIndex ) {
             leftListOffset = leftListIndex;
         } else if( leftListOffset + leftListLines <= leftListIndex ) {
             leftListOffset = leftListIndex + 1 - leftListLines;
         }
         // Left header
         std:: string storage_header = string_format( _( "Storage (%s)" ), volume_units_abbr() );
         trim_and_print( w_sort_left, point_zero, left_w - utf8_width( storage_header ) - 1, c_light_gray,
                         _( "(Innermost)" ) );
         right_print( w_sort_left, 0, 0, c_light_gray, storage_header );
         // Left list
         const int max_drawindex = std::min( leftListSize - leftListOffset, leftListLines );
         int storage_character_allowance = 5; //Sufficient for " x.yz", will increase if necessary
         for( int drawindex = 0; drawindex < max_drawindex; drawindex++ ) {
             int itemindex = leftListOffset + drawindex;
             if( itemindex == leftListIndex ) {
                 mvwprintz( w_sort_left, point( 0, drawindex + 1 ), c_yellow, ">>" );
             }
             std::string worn_armor_name = tmp_worn[itemindex]->tname();
             // Get storage capacity in user's preferred units
             units::volume worn_armor_capacity = tmp_worn[itemindex]->get_total_capacity();
             double worn_armor_storage = convert_volume( units::to_milliliter( worn_armor_capacity ) );
             std::string storage_string = string_format( "%.2f", worn_armor_storage );
             const int current_character_allowance = worn_armor_storage > 0 ? utf8_width( storage_string ) : 0;
             storage_character_allowance = std::max( current_character_allowance + 1,
                                                     storage_character_allowance );
             item_penalties const penalties =
                 get_item_penalties( tmp_worn[itemindex], guy, bp );
             const int offset_x = ( itemindex == selected ) ? 4 : 3;
             // Show armor name and storage capacity (if any)
             trim_and_print( w_sort_left, point( offset_x, drawindex + 1 ),
                             left_w - offset_x - storage_character_allowance,
                             penalties.color_for_stacking_badness(), worn_armor_name );
             if( worn_armor_storage > 0 ) {
                 // two digits, accurate to 1% of preferred storage unit
                 right_print( w_sort_left, drawindex + 1, 0, c_light_gray, storage_string );
             }
             if( tmp_worn[itemindex]->has_flag( json_flag_HIDDEN ) ) {
                 //~ Hint: Letter to show which piece of armor is Hidden in the layering menu
                 mvwprintz( w_sort_left, point( offset_x - 1, drawindex + 1 ), c_cyan, _( "H" ) );
             }
         }
         if( leftListSize == 0 ) {
             // NOLINTNEXTLINE(cata-use-named-point-constants)
             trim_and_print( w_sort_left, point( 0, 1 ), left_w, c_light_blue, _( "<empty>" ) );
         }
         // Left footer
         mvwprintz( w_sort_left, point( 0, cont_h - 1 ), c_light_gray, _( "(Outermost)" ) );
         scrollbar() //Left list scrollbar at far left
         .offset_x( 0 )
         .offset_y( 4 ) //Header allowance
         .content_size( leftListSize )
         .viewport_pos( leftListOffset )
         .viewport_size( cont_h - 2 )
         .apply( w_sort_armor );
         // Items stats
         if( leftListSize > 0 ) {
             draw_mid_pane( w_sort_middle, tmp_worn[leftListIndex], guy, bp, mid_pane );
             scrollbar() //Mid pane scrollbar
             .offset_x( left_w + 1 ) //On left of mid pane
             .offset_y( 4 + mid_pane.header_lines )
             .content_size( mid_pane.size )
             .viewport_pos( mid_pane.offset )
             .viewport_size( cont_h - num_of_parts - 3 - mid_pane.header_lines )
             .apply( w_sort_armor );
         } else {
             // NOLINTNEXTLINE(cata-use-named-point-constants)
             fold_and_print( w_sort_middle, point( 1, 0 ), middle_w - 1, c_white,
                             _( "Nothing to see here!" ) );
         }
         mvwprintz( w_encumb, point_east, c_white, _( "Encumbrance and Warmth" ) );
         guy.print_encumbrance( ui, w_encumb, -1,
                                ( leftListSize > 0 ) ? &*tmp_worn[leftListIndex] : nullptr );
         // Right header
         std::string encumbrance_header = _( "Encumbrance" );
         trim_and_print( w_sort_right, point_zero, right_w - utf8_width( encumbrance_header ) - 1,
                         c_light_gray,
                         _( "(Innermost)" ) );
         right_print( w_sort_right, 0, 0, c_light_gray, encumbrance_header );
         const auto &combine_bp = [&guy]( const bodypart_id & cover ) -> bool {
             const bodypart_id opposite = cover.obj().opposite_part;
             return cover != opposite &&
             guy.worn.items_cover_bp( guy, cover ) == guy.worn.items_cover_bp( guy, opposite );
         };
         cata::flat_set<bodypart_id> rl;
         // Right list
         rightListSize = 0;
         for( const bodypart_id &cover : armor_cat ) {
             if( cover == bodypart_id( "bp_null" ) ) {
                 continue;
             }
             if( !combine_bp( cover ) || rl.count( cover.obj().opposite_part ) == 0 ) {
                 rightListSize += items_cover_bp( guy, cover ).size() + 1;
                 rl.insert( cover );
             }
         }
         if( rightListLines > rightListSize ) {
             rightListOffset = 0;
         } else if( rightListOffset + rightListLines > rightListSize ) {
             rightListOffset = rightListSize - rightListLines;
         }
         int pos = 1;
         int curr = 0;
         int encumbrance_char_allowance = 4; //Enough for " 99+", will increase if necessary
         int item_name_offset = 2;
         for( const bodypart_id &cover : rl ) {
             if( cover == bodypart_id( "bp_null" ) ) {
                 continue;
             }
             if( curr >= rightListOffset && pos <= rightListLines ) {
                 mvwprintz( w_sort_right, point( 1, pos ), ( cover == bp ? c_yellow : c_white ),
                            "%s:", body_part_name_as_heading( cover, combine_bp( cover ) ? 2 : 1 ) );
                 pos++;
             }
             curr++;
             for( layering_item_info &elem : items_cover_bp( guy, cover ) ) {
                 if( curr >= rightListOffset && pos <= rightListLines ) {
                     nc_color color = elem.penalties.color_for_stacking_badness();
                     char plus = elem.penalties.badness() > 0 ? '+' : ' ';
                     std::string encumbrance_string = string_format( "%d%c", elem.encumber, plus );
                     if( utf8_width( encumbrance_string ) + 1 > encumbrance_char_allowance ) {
                         encumbrance_char_allowance = utf8_width( encumbrance_string ) + 1;
                     }
                     trim_and_print( w_sort_right, point( item_name_offset, pos ),
                                     right_w - item_name_offset - encumbrance_char_allowance, color,
                                     elem.name );
                     right_print( w_sort_right, pos, 0, c_light_gray, encumbrance_string );
                     pos++;
                 }
                 curr++;
             }
         }
         scrollbar() //Right list scrollbar (on left side of right list)
         .offset_x( 2 + left_w + middle_w )
         .offset_y( 4 ) //Header allowance
         .content_size( rightListSize )
         .viewport_pos( rightListOffset )
         .viewport_size( cont_h - 2 )
         .apply( w_sort_armor );
         // Right footer
         mvwprintz( w_sort_right, point( 0, cont_h - 1 ), c_light_gray, _( "(Outermost)" ) );
         // F5
         wnoutrefresh( w_sort_armor ); // Required to show scrollbars
         wnoutrefresh( w_sort_cat );
         wnoutrefresh( w_sort_left );
         wnoutrefresh( w_sort_middle );
         wnoutrefresh( w_sort_right );
         wnoutrefresh( w_encumb );
     } );
     bool exit = false;
     while( !exit ) {
         if( guy.is_avatar() ) {
             // Totally hoisted this from advanced_inv
             if( player_character.get_moves() < 0 ) {
                 do_return_entry();
                 return;
             }
         } else {
             // Player is sorting NPC's armor here
             if( rl_dist( player_character.pos(), guy.pos() ) > 1 ) {
                 guy.add_msg_if_npc( m_bad, _( "%s is too far to sort armor." ), guy.get_name() );
                 return;
             }
             if( guy.attitude_to( player_character ) != Creature::Attitude::FRIENDLY ) {
                 guy.add_msg_if_npc( m_bad, _( "%s is not friendly!" ), guy.get_name() );
                 return;
             }
         }
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         if( guy.is_npc() && action == "ASSIGN_INVLETS" ) {
             // It doesn't make sense to assign invlets to NPC items
             continue;
         }
         // Helper function for moving items in the list
         auto shift_selected_item = [&]() {
             if( selected >= 0 ) {
                 std::list<item>::iterator to = tmp_worn[leftListIndex];
                 if( leftListIndex > selected ) {
                     ++to;
                 }
                 worn.splice( to, worn, tmp_worn[selected] );
                 selected = leftListIndex;
                 guy.calc_encumbrance();
             }
         };
         if( action == "UP" && leftListSize > 0 ) {
             mid_pane.offset = 0;
             if( leftListIndex > 0 ) {
                 item &item_to_check = *tmp_worn[leftListIndex - 1];
                 if( selected < 0 || !item_to_check.has_flag( flag_INTEGRATED ) ) {
                     leftListIndex--;
                     if( leftListIndex < leftListOffset ) {
                         leftListOffset = leftListIndex;
                     }
                     shift_selected_item();
                 } else {
                     popup( _( "Can't sort this under your integrated armor!" ) );
                 }
             } else {
                 leftListIndex = leftListSize - 1;
                 if( leftListLines >= leftListSize ) {
                     leftListOffset = 0;
                 } else {
                     leftListOffset = leftListSize - leftListLines;
                 }
                 shift_selected_item();
             }
         } else if( action == "DOWN" && leftListSize > 0 ) {
             mid_pane.offset = 0;
             if( leftListIndex + 1 < leftListSize ) {
                 leftListIndex++;
                 if( leftListIndex >= leftListOffset + leftListLines ) {
                     leftListOffset = leftListIndex + 1 - leftListLines;
                 }
                 shift_selected_item();
             } else {
                 item &item_to_check = *tmp_worn[0];
                 if( selected < 0 || !item_to_check.has_flag( flag_INTEGRATED ) ) {
                     leftListIndex = 0;
                     leftListOffset = 0;
                     shift_selected_item();
                 } else {
                     popup( _( "Can't sort this under your integrated armor!" ) );
                 }
             }
         } else if( action == "LEFT" || action == "PREV_TAB" || action == "RIGHT" || action == "NEXT_TAB" ) {
             mid_pane.offset = 0;
             tabindex = inc_clamp_wrap( tabindex, action == "RIGHT" || action == "NEXT_TAB", tabcount );
             leftListIndex = leftListOffset = 0;
             selected = -1;
         } else if( action == "PAGE_DOWN" ) {
             if( rightListOffset + rightListLines < rightListSize ) {
                 rightListOffset++;
             }
         } else if( action == "PAGE_UP" ) {
             if( rightListOffset > 0 ) {
                 rightListOffset--;
             }
         } else if( action == "MOVE_ARMOR" && leftListIndex < leftListSize ) {
             if( selected >= 0 ) {
                 selected = -1;
             } else {
                 item &item_to_check = *tmp_worn[leftListIndex];
                 if( !item_to_check.has_flag( flag_INTEGRATED ) ) {
                     selected = leftListIndex;
                 } else {
                     popup( _( "Can't move your integrated armor!" ) );
                 }
             }
         } else if( action == "CHANGE_SIDE" ) {
             mid_pane.offset = 0;
             if( leftListIndex < leftListSize && tmp_worn[leftListIndex]->is_sided() ) {
                 if( player_character.query_yn( _( "Swap side for %s?" ),
                                                colorize( tmp_worn[leftListIndex]->tname(),
                                                        tmp_worn[leftListIndex]->color_in_inventory() ) ) ) {
                     guy.change_side( *tmp_worn[leftListIndex] );
                 }
             }
         } else if( action == "TOGGLE_CLOTH" ) {
             if( leftListIndex < leftListSize ) {
                 if( !tmp_worn[leftListIndex]->has_flag( json_flag_HIDDEN ) ) {
                     tmp_worn[leftListIndex]->set_flag( json_flag_HIDDEN );
                 } else {
                     tmp_worn[leftListIndex]->unset_flag( json_flag_HIDDEN );
                 }
             }
         } else if( action == "SORT_ARMOR" ) {
             mid_pane.offset = 0;
             worn.sort(
             []( const item & l, const item & r ) {
                 if( l.has_flag( flag_INTEGRATED ) == r.has_flag( flag_INTEGRATED ) ) {
                     return l.get_layer() < r.get_layer();
                 } else {
                     return l.has_flag( flag_INTEGRATED );
                 }
             }
             );
             guy.calc_encumbrance();
         } else if( action == "EQUIP_ARMOR" ) {
             mid_pane.offset = 0;
             // filter inventory for all items that are armor/clothing
             item_location loc = game_menus::inv::wear( guy );
             // only equip if something valid selected!
             if( loc ) {
                 // store the item name just in case obtain() fails
                 const std::string item_name = loc->display_name();
                 item_location obtained = loc.obtain( guy );
                 if( obtained ) {
                     // wear the item
                     std::optional<std::list<item>::iterator> new_equip_it =
                         guy.wear( obtained );
                     if( new_equip_it ) {
                         const bodypart_id &bp = armor_cat[tabindex];
                         if( tabindex == num_of_parts || ( **new_equip_it ).covers( bp ) ) {
                             // Set ourselves up to be pointing at the new item
                             // TODO: This doesn't work yet because we don't save our
                             // state through other activities, but that's a thing
                             // that would be nice to do.
                             leftListIndex =
                                 std::count_if( worn.begin(), *new_equip_it,
                             [&]( const item & i ) {
                                 return tabindex == num_of_parts || i.covers( bp );
                             } );
                         }
                     } else if( guy.is_npc() ) {
                         // TODO: Pass the reason here
                         popup( _( "Can't put this on!" ) );
                     }
                 } else {
                     guy.add_msg_if_player( _( "You chose not to wear the %s." ), item_name );
                 }
             }
         } else if( action == "EQUIP_ARMOR_HERE" ) {
             mid_pane.offset = 0;
             // filter inventory for all items that are armor/clothing
             item_location loc = game_menus::inv::wear( guy, armor_cat[tabindex] );
             // only equip if something valid selected!
             if( loc ) {
                 // store the item name just in case obtain() fails
                 const std::string item_name = loc->display_name();
                 item_location obtained = loc.obtain( guy );
                 if( obtained ) {
                     // wear the item
                     std::optional<std::list<item>::iterator> new_equip_it =
                         guy.wear( obtained );
                     if( new_equip_it ) {
                         // save iterator to cursor's position
                         std::list<item>::iterator cursor_it = tmp_worn[leftListIndex];
                         item &item_to_check = *cursor_it;
                         if( item_to_check.has_flag( flag_INTEGRATED ) ) {
                             // prevent adding under integrated armor
                             popup( _( "Can't put this on under your integrated armor!" ) );
                         } else {
                             // reorder `worn` vector to place new item at cursor
                             worn.splice( cursor_it, worn, *new_equip_it );
                         }
                     } else if( guy.is_npc() ) {
                         // TODO: Pass the reason here
                         popup( _( "Can't put this on!" ) );
                     }
                 } else {
                     guy.add_msg_if_player( _( "You chose not to wear the %s." ), item_name );
                 }
             }
         } else if( action == "REMOVE_ARMOR" ) {
             mid_pane.offset = 0;
             // query (for now)
             if( leftListIndex < leftListSize ) {
                 if( player_character.query_yn( _( "Remove selected armor?" ) ) ) {
                     do_return_entry();
                     //create an item_location for player::takeoff to handle.
                     item &item_for_takeoff = *tmp_worn[leftListIndex];
                     item_location loc_for_takeoff = item_location( guy, &item_for_takeoff );
                     // remove the item, asking to drop it if necessary
                     guy.takeoff( loc_for_takeoff );
                     if( !player_character.has_activity( ACT_ARMOR_LAYERS ) ) {
                         // An activity has been created to take off the item;
                         // we must surrender control until it is done.
                         return;
                     }
                     player_character.cancel_activity();
                     selected = -1;
                     leftListIndex = std::max( 0, leftListIndex - 1 );
                 }
             }
         } else if( action == "ASSIGN_INVLETS" ) {
             // prompt first before doing this (yes, yes, more popups...)
             if( query_yn( _( "Reassign inventory letters for armor?" ) ) ) {
                 // Start with last armor (the most unimportant one?)
                 auto iiter = inv_chars.rbegin();
                 auto witer = worn.rbegin();
                 while( witer != worn.rend() && iiter != inv_chars.rend() ) {
                     const char invlet = *iiter;
                     item &w = *witer;
                     if( invlet == w.invlet ) {
                         ++witer;
                     } else if( guy.invlet_to_item( invlet ) != nullptr ) {
                         ++iiter;
                     } else {
                         guy.inv->reassign_item( w, invlet );
                         ++witer;
                         ++iiter;
                     }
                 }
             }
         } else if( action == "SCROLL_ITEM_INFO_UP" ) {
             if( mid_pane.offset > 0 ) {
                 --mid_pane.offset;
             }
         } else if( action == "SCROLL_ITEM_INFO_DOWN" ) {
             const int mid_pane_height = cont_h - num_of_parts - 2 - mid_pane.header_lines;
             if( mid_pane.offset + mid_pane_height <= static_cast<int>( mid_pane.size ) ) {
                 ++mid_pane.offset;
             }
         } else if( action == "USAGE_HELP" ) {
             const std::vector<std::string> help_strings = {
                 string_format( _( "[<color_yellow>%s</color>]/[<color_yellow>%s</color>] to scroll the left pane (list of items).\n" ),
                                ctxt.get_desc( "UP" ), ctxt.get_desc( "DOWN" ) ),
                 string_format( _( "[<color_yellow>%s</color>]/[<color_yellow>%s</color>] to scroll the middle pane (item information).\n" ),
                                ctxt.get_desc( "SCROLL_ITEM_INFO_UP" ), ctxt.get_desc( "SCROLL_ITEM_INFO_DOWN" ) ),
                 string_format( _( "[<color_yellow>%s</color>]/[<color_yellow>%s</color>] to scroll the right pane (items grouped by body part).\n" ),
                                ctxt.get_desc( "PREV_TAB" ), ctxt.get_desc( "NEXT_TAB" ) ),
                 string_format( _( "[<color_yellow>%s</color>]/[<color_yellow>%s</color>] to limit the left pane to a particular body part.\n" ),
                                ctxt.get_desc( "LEFT" ), ctxt.get_desc( "RIGHT" ) ),
                 string_format( _( "[<color_yellow>%s</color>] to select an item for reordering.\n" ),
                                ctxt.get_desc( "MOVE_ARMOR" ) ),
                 string_format( _( "[<color_yellow>%s</color>] to assign special inventory letters to clothing.\n" ),
                                ctxt.get_desc( "ASSIGN_INVLETS" ) ),
                 string_format( _( "[<color_yellow>%s</color>] to change the side on which item is worn.\n" ),
                                ctxt.get_desc( "CHANGE_SIDE" ) ),
                 string_format( _( "[<color_yellow>%s</color>] to toggle item visibility on character sprite.\n" ),
                                ctxt.get_desc( "TOGGLE_CLOTH" ) ),
                 string_format( _( "[<color_yellow>%s</color>] to sort worn items into natural layer order.\n" ),
                                ctxt.get_desc( "SORT_ARMOR" ) ),
                 string_format( _( "[<color_yellow>%s</color>] to equip a new item.\n" ),
                                ctxt.get_desc( "EQUIP_ARMOR" ) ),
                 string_format( _( "[<color_yellow>%s</color>] to equip a new item at the currently selected position.\n" ),
                                ctxt.get_desc( "EQUIP_ARMOR_HERE" ) ),
                 string_format( _( "[<color_yellow>%s</color>] to remove selected item.\n" ),
                                ctxt.get_desc( "REMOVE_ARMOR" ) ),
                 "\n",
                 _( "Encumbrance explanation:\n" ),
                 _( "<color_light_gray>The first number is the summed encumbrance from all clothing on that bodypart."
                    "The second number is an additional encumbrance penalty caused by wearing either multiple items "
                    "on one of the bodypart's layers or wearing items the wrong way (e.g. a shirt over a backpack)."
                    "The sum of these values is the effective encumbrance value your character has for that bodypart."
                    "</color>" )
             };
             std::string assembled_string;
             for( const std::string &current_line : help_strings ) {
                 assembled_string += current_line;
             }
             const auto new_win = []() {
                 return catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                            point( std::max( 0, ( TERMX - FULL_SCREEN_WIDTH ) / 2 ),
                                                   std::max( 0, ( TERMY - FULL_SCREEN_HEIGHT ) / 2 ) ) );
             };
             scrollable_text( new_win, _( "Sort armor help" ), assembled_string );
         } else if( action == "QUIT" ) {
             exit = true;
         }
     }
 }
References _, ACT_ARMOR_LAYERS, action, Character::activity, Creature::add_msg_if_npc(), Character::add_msg_if_player(), scrollbar::apply(), Character::assign_activity(), Character::attitude_to(), player_activity::auto_resume, body_part_name_as_heading(), bp, c_cyan, c_light_blue, c_light_gray, c_white, c_yellow, Character::calc_encumbrance(), Character::cancel_activity(), Character::change_side(), color(), item_penalties::color_for_stacking_badness(), colorize(), scrollbar::content_size(), convert_volume(), cata::flat_set< T, Compare, Data >::count(), item::display_name(), draw_grid(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), flag_INTEGRATED, fold_and_print(), Creature::FRIENDLY, FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, Creature::get_all_body_parts(), input_context::get_desc(), get_item_penalties(), Creature::get_moves(), Character::get_name(), get_player_character(), catacurses::getmaxx(), input_context::handle_input(), Character::has_activity(), item::has_flag(), inc_clamp_wrap(), cata::flat_set< T, Compare, Data >::insert(), Character::inv, inv_chars, item::invlet, Character::invlet_to_item(), Creature::is_avatar(), Character::is_npc(), tname::item_name(), items_cover_bp(), json_flag_HIDDEN, m_bad, max(), min(), player_activity::moves_left, mvwprintz(), catacurses::newwin(), item_location::obtain(), scrollbar::offset_x(), scrollbar::offset_y(), om_direction::opposite(), point, point_east, point_zero, popup(), Creature::pos(), math_opers::pos(), Character::print_encumbrance(), Character::query_yn(), query_yn(), ui_manager::redraw(), input_context::register_action(), input_context::register_cardinal(), right_print(), rl_dist(), scrollable_text(), string_format(), Character::takeoff(), temp, TERMX, TERMY, units::to_milliliter(), trim_and_print(), trim_by_length(), utf8_width(), scrollbar::viewport_pos(), scrollbar::viewport_size(), volume_units_abbr(), game_menus::inv::wear(), Character::wear(), catacurses::werase(), catacurses::wnoutrefresh(), Character::worn, worn, wprintz(), point::x, and point::y.
Referenced by activity_handlers::armor_layers_do_turn(), game::do_regular_action(), and game::npc_menu().
sum_filthy_cover()
int outfit::sum_filthy_cover (bool ranged, bool melee, bodypart_id bp) const
Definition at line 1566 of file character_attire.cpp.
 {
     int sum_cover = 0;
     for( const item &i : worn ) {
         if( i.covers( bp ) && i.is_filthy() ) {
             if( melee ) {
                 sum_cover += i.get_coverage( bp, item::cover_type::COVER_MELEE );
             } else if( ranged ) {
                 sum_cover += i.get_coverage( bp, item::cover_type::COVER_RANGED );
             } else {
                 sum_cover += i.get_coverage( bp );
             }
         }
     }
     return sum_cover;
 }
References bp, item::COVER_MELEE, item::COVER_RANGED, and worn.
Referenced by Character::deal_damage().
swim_modifier()
int outfit::swim_modifier (int swim_skill) const
Definition at line 1117 of file character_attire.cpp.
 {
     int ret = 0;
     if( swim_skill < 10 ) {
         for( const item &i : worn ) {
             ret += i.volume() / 125_ml * ( 10 - swim_skill );
         }
     }
     return ret;
 }
References cata::hash64_detail::ret, and worn.
Referenced by Character::swim_speed().
takeoff()
bool outfit::takeoff (item_location loc, std::list< item > * res, Character & guy)
Definition at line 1495 of file character_attire.cpp.
 {
     item &it = *loc;
     const auto ret = guy.can_takeoff( it, res );
     if( !ret.success() ) {
         add_msg( m_info, "%s", ret.c_str() );
         return false;
     }
     auto iter = std::find_if( worn.begin(), worn.end(), [&it]( const item & wit ) {
         return &it == &wit;
     } );
     it.on_takeoff( guy );
     item takeoff_copy( it );
     worn.erase( iter );
     if( res == nullptr ) {
         guy.i_add( takeoff_copy, true, &it, &it, true, !guy.has_weapon() );
     } else {
         res->push_back( takeoff_copy );
     }
     return true;
 }
References add_msg(), Character::can_takeoff(), Character::has_weapon(), Character::i_add(), m_info, item::on_takeoff(), cata::hash64_detail::ret, and worn.
Referenced by adjust_worn(), and Character::takeoff().
top_items_loc()
std::vector< item_location > outfit::top_items_loc (Character & guy)
Definition at line 525 of file character_inventory.cpp.
 {
     std::vector<item_location> ret;
     for( item &worn_it : worn ) {
         item_location worn_loc( guy, &worn_it );
         ret.push_back( worn_loc );
     }
     return ret;
 }
References cata::hash64_detail::ret, and worn.
Referenced by overflow(), and Character::top_items_loc().
total_holsters()
int outfit::total_holsters () const
Definition at line 1677 of file character_attire.cpp.
 {
     int e_holsters = 0;
     for( const item &w : worn ) {
         e_holsters += w.get_total_holsters();
     }
     return e_holsters;
 }
References worn.
Referenced by Character::total_holsters().
use_amount()
std::list< item > outfit::use_amount (const itype_id & it, int quantity, std::list< item > & used, const std::function< bool(const item &)> & filter, Character & wearer)
Definition at line 1764 of file character_attire.cpp.
 {
     for( auto a = worn.begin(); a != worn.end() && quantity > 0; ) {
         if( a->use_amount( it, quantity, used, filter ) ) {
             a->on_takeoff( wearer );
             a = worn.erase( a );
         } else {
             ++a;
         }
     }
     return used;
 }
References a, filter, and worn.
Referenced by Character::use_amount().
used_holsters()
int outfit::used_holsters () const
Definition at line 1668 of file character_attire.cpp.
 {
     int e_holsters = 0;
     for( const item &w : worn ) {
         e_holsters += w.get_used_holsters();
     }
     return e_holsters;
 }
References worn.
Referenced by Character::used_holsters().
visit_items()
VisitResponse outfit::visit_items (const std::function< VisitResponse(item *, item *)> & func) const
Definition at line 437 of file visitable.cpp.
 {
     for( const item &e : worn ) {
         if( visit_internal( func, &e ) == VisitResponse::ABORT ) {
             return VisitResponse::ABORT;
         }
     }
     return VisitResponse::NEXT;
 }
References ABORT, NEXT, visit_internal(), and worn.
volume_capacity()
units::volume outfit::volume_capacity () const
Definition at line 1710 of file character_attire.cpp.
 {
     units::volume cap = 0_ml;
     for( const item &w : worn ) {
         cap += w.get_total_capacity();
     }
     return cap;
 }
References worn.
Referenced by free_space(), and Character::volume_capacity().
volume_capacity_with_tweaks()
units::volume outfit::volume_capacity_with_tweaks (const std::map< const item *, int > & without) const
Definition at line 1719 of file character_attire.cpp.
 {
     units::volume vol = 0_ml;
     for( const item &i : worn ) {
         if( !without.count( &i ) ) {
             vol += i.get_total_capacity();
         }
     }
     return vol;
 }
References worn.
Referenced by Character::volume_capacity_with_tweaks().
warmth()
std::map< bodypart_id, int > outfit::warmth (const Character & guy) const
Returns warmth provided by armor, etc.
Definition at line 1991 of file character_attire.cpp.
 {
     std::map<bodypart_id, int> total_warmth;
     for( const bodypart_id &bp : guy.get_all_body_parts() ) {
         double warmth_val = 0.0;
         const float wetness_pct = guy.get_part_wetness_percentage( bp );
         for( const item &clothing : worn ) {
             if( !clothing.covers( bp ) ) {
                 continue;
             }
             warmth_val = clothing.get_warmth( bp );
             // Wool items do not lose their warmth due to being wet.
             // Warmth is reduced by 0 - 66% based on wetness.
             if( !clothing.made_of( material_wool ) ) {
                 warmth_val *= 1.0 - 0.66 * wetness_pct;
             }
             total_warmth[bp] += warmth_val;
         }
         total_warmth[bp] += guy.get_effect_int( effect_heating_bionic, bp );
     }
     return total_warmth;
 }
References bp, effect_heating_bionic, Creature::get_all_body_parts(), Creature::get_effect_int(), Creature::get_part_wetness_percentage(), material_wool, and worn.
Referenced by collar_warmth(), hood_warmth(), pocket_warmth(), Character::update_bodytemp(), and wet_character().
wear_item()
std::optional< std::list< item >::iterator > outfit::wear_item (Character & guy, const item & to_wear, bool interactive, bool do_calc_encumbrance, bool do_sort_items = true, bool quiet = false)
Definition at line 319 of file character_attire.cpp.
 {
     const bool was_deaf = guy.is_deaf();
     const bool supertinymouse = guy.get_size() == creature_size::tiny;
     guy.last_item = to_wear.typeId();
     std::list<item>::iterator new_item_it = worn.end();
     if( do_sort_items ) {
         std::list<item>::iterator position = position_to_wear_new_item( to_wear );
         new_item_it = worn.insert( position, to_wear );
     } else {
         // this is used for debug and putting on clothing in the wrong order
         worn.push_back( to_wear );
     }
     item_location loc = new_item_it != worn.end() ?
                         item_location( guy, &*new_item_it ) : item_location();
     cata::event e = cata::event::make<event_type::character_wears_item>( guy.getID(), guy.last_item );
     get_event_bus().send_with_talker( &guy, &loc, e );
     if( interactive ) {
         if( !quiet ) {
             guy.add_msg_player_or_npc(
                 _( "You put on your %s." ),
                 _( "<npcname> puts on their %s." ),
                 to_wear.tname() );
         }
         guy.mod_moves( -guy.item_wear_cost( to_wear ) );
         for( const bodypart_id &bp : guy.get_all_body_parts() ) {
             if( to_wear.covers( bp ) && guy.encumb( bp ) >= 40 && !quiet ) {
                 guy.add_msg_if_player( m_warning,
                                        bp == body_part_eyes ?
                                        _( "Your %s are very encumbered!  %s" ) : _( "Your %s is very encumbered!  %s" ),
                                        body_part_name( bp ), encumb_text( bp ) );
             }
         }
         if( !was_deaf && guy.is_deaf() && !quiet ) {
             guy.add_msg_if_player( m_info, _( "You're deafened!" ) );
         }
         if( supertinymouse && !to_wear.has_flag( flag_UNDERSIZE ) && !quiet ) {
             guy.add_msg_if_player( m_warning,
                                    _( "This %s is too big to wear comfortably!  Maybe it could be refitted." ),
                                    to_wear.tname() );
         } else if( !supertinymouse && to_wear.has_flag( flag_UNDERSIZE ) && !quiet ) {
             guy.add_msg_if_player( m_warning,
                                    _( "This %s is too small to wear comfortably!  Maybe it could be refitted." ),
                                    to_wear.tname() );
         }
     } else if( guy.is_npc() && get_player_view().sees( guy ) && !quiet ) {
         guy.add_msg_if_npc( _( "<npcname> puts on their %s." ), to_wear.tname() );
     }
     // skip this for unsorted items in debug mode
     if( do_sort_items ) {
         new_item_it->on_wear( guy );
         guy.inv->update_invlet( *new_item_it );
         guy.inv->update_cache_with_item( *new_item_it );
     }
     if( do_calc_encumbrance ) {
         guy.recalc_sight_limits();
         guy.calc_encumbrance();
         guy.calc_discomfort();
     }
     if( to_wear.is_rigid() || to_wear.is_ablative() ) {
         recalc_ablative_blocking( &guy );
     }
     guy.recoil = MAX_RECOIL;
     return new_item_it;
 }
References _, Creature::add_msg_if_npc(), Character::add_msg_if_player(), Character::add_msg_player_or_npc(), body_part_eyes, body_part_name(), bp, Character::calc_discomfort(), Character::calc_encumbrance(), item::covers(), Character::encumb(), encumb_text(), flag_UNDERSIZE, Creature::get_all_body_parts(), get_event_bus(), get_player_view(), Character::get_size(), Character::getID(), item::has_flag(), Character::inv, item::is_ablative(), Character::is_deaf(), Character::is_npc(), item::is_rigid(), Character::item_wear_cost(), Character::last_item, m_info, m_warning, MAX_RECOIL, Creature::mod_moves(), position_to_wear_new_item(), recalc_ablative_blocking(), Character::recalc_sight_limits(), Character::recoil, event_bus::send_with_talker(), tiny, item::tname(), item::typeId(), and worn.
Referenced by gun_actor::shoot(), starting_clothes(), and Character::wear_item().
wearing_fitting_on()
bool outfit::wearing_fitting_on (const bodypart_id & bp) const
Definition at line 1095 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         if( i.covers( bp ) && !i.has_flag( flag_INTEGRATED ) && !i.has_flag( flag_OVERSIZE ) &&
             !i.has_flag( flag_UNRESTRICTED ) ) {
             return true;
         }
     }
     return false;
 }
References bp, flag_INTEGRATED, flag_OVERSIZE, flag_UNRESTRICTED, and worn.
Referenced by Character::wearing_fitting_on().
wearing_something_on()
bool outfit::wearing_something_on (const bodypart_id & bp) const
Definition at line 1085 of file character_attire.cpp.
 {
     for( const item &i : worn ) {
         if( i.covers( bp ) && !i.has_flag( flag_INTEGRATED ) ) {
             return true;
         }
     }
     return false;
 }
References bp, flag_INTEGRATED, and worn.
Referenced by Character::wearing_something_on().
weight()
units::mass outfit::weight () const
Definition at line 1182 of file character_attire.cpp.
 {
     return std::accumulate( worn.begin(), worn.end(), 0_gram,
     []( units::mass sum, const item & itm ) {
         return sum + itm.weight();
     } );
 }
References worn.
Referenced by Character::get_weight().
weight_carried_with_tweaks()
units::mass outfit::weight_carried_with_tweaks (const std::map< const item *, int > & without) const
Definition at line 1190 of file character_attire.cpp.
 {
     units::mass ret = 0_gram;
     for( const item &i : worn ) {
         if( without.empty() ) {
             ret += i.weight();
         } else if( !without.count( &i ) ) {
             for( const item *j : i.all_items_ptr( pocket_type::CONTAINER ) ) {
                 if( j->count_by_charges() ) {
                     ret -= get_selected_stack_weight( j, without );
                 } else if( without.count( j ) ) {
                     ret -= j->weight();
                 }
             }
             ret += i.weight();
         }
     }
     return ret;
 }
References item::all_items_ptr(), CONTAINER, get_selected_stack_weight(), cata::hash64_detail::ret, and worn.
Referenced by Character::weight_carried_with_tweaks().
where_discomfort()
std::unordered_set< bodypart_id > outfit::where_discomfort (const Character & guy) const
Calculate and return any bodyparts that are currently uncomfortable.
Definition at line 2015 of file character_attire.cpp.
 {
     // get all rigid body parts to begin with
     std::unordered_set<sub_bodypart_id> covered_sbps;
     std::unordered_set<bodypart_id> uncomfortable_bps;
     for( const item &i : worn ) {
         // check each sublimb individually
         for( const sub_bodypart_id &sbp : i.get_covered_sub_body_parts() ) {
             if( i.is_bp_comfortable( sbp ) ) {
                 covered_sbps.insert( sbp );
             }
             // if the bp is uncomfortable and has yet to display as covered with something comfortable then it should cause discomfort
             // note anything selectively rigid reasonably can be assumed to support itself so we don't need to worry about this
             // items must also be somewhat heavy in order to cause discomfort
             if( !i.is_bp_rigid_selective( sbp ) && !i.is_bp_comfortable( sbp ) &&
                 i.weight() > units::from_gram( 250 ) ) {
                 // need to go through each locations under location to check if its covered, since secondary locations can cover multiple underlying locations
                 for( const sub_bodypart_str_id &under_sbp : sbp->locations_under ) {
                     if( covered_sbps.count( under_sbp ) != 1 ) {
                         guy.add_msg_if_player(
                             string_format( _( "<color_c_red>The %s rubs uncomfortably against your unpadded %s.</color>" ),
                                            i.display_name(), under_sbp->name ) );
                         uncomfortable_bps.insert( sbp->parent );
                     }
                 }
             }
         }
     }
     return uncomfortable_bps;
 }
References _, Character::add_msg_if_player(), units::from_gram(), sub_body_part_type::locations_under, sub_body_part_type::name, string_format(), and worn.
Referenced by Character::calc_discomfort().
worn_guns()
int outfit::worn_guns () const
Definition at line 2134 of file character_attire.cpp.
 {
     int ret = 0;
     for( const item &clothing : worn ) {
         // true bool casts to 1, false to 0
         ret += clothing.is_gun();
     }
     return ret;
 }
References cata::hash64_detail::ret, and worn.
Referenced by mattack::dsa_drone_scan().
worn_with_flag() [1/2]
bool outfit::worn_with_flag (const flag_id & f) const
Definition at line 1015 of file character_attire.cpp.
 {
     return std::any_of( worn.begin(), worn.end(), [&f]( const item & it ) {
         return it.has_flag( f );
     } );
 }
References worn.
worn_with_flag() [2/2]
bool outfit::worn_with_flag (const flag_id & f, const bodypart_id & bp) const
Definition at line 1008 of file character_attire.cpp.
 {
     return std::any_of( worn.begin(), worn.end(), [&f, bp]( const item & it ) {
         return it.has_flag( f ) && ( bp == bodypart_str_id::NULL_ID() || it.covers( bp ) );
     } );
 }
References bp, and worn.
Referenced by Character::worn_with_flag().
write_text_memorial()
void outfit::write_text_memorial (std::ostream & file, const std::string & indent, const char * eol) const
Definition at line 2528 of file character_attire.cpp.
 {
     for( const item &elem : worn ) {
         item next_item = elem;
         file << indent << next_item.invlet << " - " << next_item.tname( 1, false );
         if( next_item.charges > 0 ) {
             file << " (" << next_item.charges << ")";
         }
         file << eol;
     }
 }
References item::charges, cata_files::eol(), file, item::invlet, item::tname(), and worn.
Friends And Related Function Documentation
Character
friend class Character friend
Definition at line 85 of file character_attire.h.
Member Data Documentation
worn
std::list<item> outfit::worn private
Definition at line 87 of file character_attire.h.
Referenced by absorb_damage(), activate_combat_items(), add_AIM_items_from_area(), add_dependent_item(), adjust_worn(), all_items_loc(), amount_worn(), available_pockets(), best_pocket(), best_shield(), bodypart_exposure(), can_pickVolume(), check_and_recover_morale(), check_item_encumbrance_flag(), check_rigid_conflicts(), clatter_sound(), Character::clear_worn(), clothing_wetness_mult(), collar_warmth(), contents_volume_with_tweaks(), coverage_with_flags_exclude(), covered_with_flag(), current_unarmed_weapon(), damage_mitigate(), damage_resist(), deactivate_combat_items(), deserialize(), empty(), empty_holsters(), exclusive_flag_coverage(), fire_options(), first_item_covering_bp(), free_holster_volume(), free_space(), free_weight_capacity(), front(), get_AIM_inventory(), get_armor_display(), get_coverage(), get_eligible_containers_for_crafting(), get_env_resist(), get_item_penalties(), get_item_position(), get_overlay_ids(), get_visible_worn_items(), grab_drop_pockets(), hands_conductive(), holster_opts(), holster_volume(), hood_warmth(), i_at(), insert_item_at_index(), inv_dump(), is_barefoot(), is_wearing_active_optcloak(), is_wearing_active_power_armor(), is_wearing_on_bp(), is_wearing_power_armor(), is_wearing_shoes(), is_worn(), is_worn_module(), item_encumb(), item_worn_with_flag(), item_worn_with_id(), item_worn_with_inv_let(), items_cover_bp(), max_single_item_length(), max_single_item_volume(), natural_attack_restricted_on(), on_item_wear(), on_takeoff(), one_per_layer_change_side(), one_per_layer_sidedness(), only_one_conflicts(), organize_items_menu(), pickup_stash(), pocket_warmth(), position_to_wear_new_item(), power_armor_conflicts(), prepare_bodymap_info(), recalc_ablative_blocking(), remove_items_with(), remove_worn_items_with(), serialize(), set_fitted(), size(), small_pocket_volume(), sort_armor(), sum_filthy_cover(), swim_modifier(), takeoff(), top_items_loc(), total_holsters(), use_amount(), used_holsters(), visit_items(), volume_capacity(), volume_capacity_with_tweaks(), warmth(), wear_item(), wearing_fitting_on(), wearing_something_on(), weight(), weight_carried_with_tweaks(), where_discomfort(), worn_guns(), worn_with_flag(), and write_text_memorial().
The documentation for this class was generated from the following files:
src/character_attire.h
src/advanced_inv_pane.cpp
src/armor_layers.cpp
src/character_attire.cpp
src/character_inventory.cpp
src/character_morale.cpp
src/crafting.cpp
src/npcmove.cpp
src/visitable.cpp