Cataclysm DDA: item_category Class Reference
item_category Class Reference
Contains metadata for one category of items.
#include <item_category.h>
Public Member Functions
item_category ()=default
item_category (const item_category_id &id, const translation &name_header, const translation &name_noun, const int sort_rank)
item_category (const std::string &id, const translation &name_header, const translation &name_noun, const int sort_rank)
std::string name_header () const
std::string name_noun (int count) const
item_category_id get_id () const
std::optional< zone_type_id > priority_zone (const item &it) const
std::optional< zone_type_id > zone () const
int sort_rank () const
float get_spawn_rate () const
bool operator< (const item_category &rhs) const
Comparison operators.
bool operator== (const item_category &rhs) const
bool operator!= (const item_category &rhs) const
void load (const JsonObject &jo, std::string_view)
Static Public Member Functions
static const std::vector< item_category > & get_all ()
static void load_item_cat (const JsonObject &jo, const std::string &src)
static void reset ()
Public Attributes
item_category_id id
Unique ID of this category, used when loading from JSON.
std::vector< std::pair< item_category_id, mod_id > > src
bool was_loaded = false
Private Attributes
translation name_header_
Name of category for displaying to the user.
translation name_noun_
int sort_rank_ = 0
Used to sort categories when displaying.
float spawn_rate = 1.0f
Global spawn rate for items from category.
std::optional< zone_type_id > zone_
std::vector< zone_priority_data > zone_priority_
Detailed Description
Contains metadata for one category of items.
Every item belongs to a category (e.g. weapons, armor, food, etc). This class contains the info about one such category. Actual categories are normally added by class Item_factory from definitions in the JSON data files.
Definition at line 34 of file item_category.h.
Constructor & Destructor Documentation
item_category() [1/3]
item_category::item_category () default
item_category() [2/3]
item_category::item_category (const item_category_id & id, const translation & name_header, const translation & name_noun, const int sort_rank) inline
Parameters
id id_
name_header name_header_
name_noun name_noun_
sort_rank sort_rank_
Definition at line 60 of file item_category.h.
             : name_header_( name_header ), name_noun_( name_noun )
             , sort_rank_( sort_rank ), id( id ) {}
item_category() [3/3]
item_category::item_category (const std::string & id, const translation & name_header, const translation & name_noun, const int sort_rank) inline
Definition at line 64 of file item_category.h.
             : name_header_( name_header ), name_noun_( name_noun )
             , sort_rank_( sort_rank ), id( item_category_id( id ) ) {}
Member Function Documentation
get_all()
const std::vector< item_category > & item_category::get_all () static
Definition at line 38 of file item_category.cpp.
 {
     return item_category_factory.get_all();
 }
References anonymous_namespace{item_category.cpp}::item_category_factory.
Referenced by pocket_favorite_callback::key().
get_id()
item_category_id item_category::get_id () const
Definition at line 97 of file item_category.cpp.
 {
     return id;
 }
References id.
Referenced by item::aggregated_contents(), trade_preset::cat_sort_compare(), item::get_category_of_contents(), inventory_selector_preset::get_cell_text(), Character::get_consume_time(), zone_manager::get_near_zone_type_for_item(), item::is_map(), and item::stacks_with().
get_spawn_rate()
float item_category::get_spawn_rate () const
Definition at line 130 of file item_category.cpp.
 {
     return spawn_rate;
 }
References spawn_rate.
Referenced by map::item_category_spawn_rate().
load()
void item_category::load (const JsonObject & jo, std::string_view)
Definition at line 53 of file item_category.cpp.
 {
     mandatory( jo, was_loaded, "id", id );
     mandatory( jo, was_loaded, "name_header", name_header_ );
     name_noun_.make_plural();
     mandatory( jo, was_loaded, "name_noun", name_noun_ );
     mandatory( jo, was_loaded, "sort_rank", sort_rank_ );
     optional( jo, was_loaded, "priority_zones", zone_priority_ );
     optional( jo, was_loaded, "zone", zone_, std::nullopt );
     optional( jo, was_loaded, "spawn_rate", spawn_rate, 1.0f );
 }
References translation::make_plural(), mandatory, name_header_, name_noun_, optional(), sort_rank_, spawn_rate, was_loaded, zone_, and zone_priority_.
load_item_cat()
void item_category::load_item_cat (const JsonObject & jo, const std::string & src) static
Definition at line 43 of file item_category.cpp.
 {
     item_category_factory.load( jo, src );
 }
References anonymous_namespace{item_category.cpp}::item_category_factory, and src.
Referenced by DynamicDataLoader::initialize().
name_header()
std::string item_category::name_header () const
Definition at line 87 of file item_category.cpp.
 {
     return name_header_.translated();
 }
References name_header_, and translation::translated().
Referenced by item::basic_info(), inventory_selector_preset::get_cell_text(), pocket_favorite_callback::key(), and advanced_inventory::print_items().
name_noun()
std::string item_category::name_noun (int count) const
Definition at line 92 of file item_category.cpp.
 {
     return name_noun_.translated( count );
 }
References name_noun_, and translation::translated().
Referenced by anonymous_namespace{item_tname.cpp}::category().
operator!=()
bool item_category::operator!= (const item_category & rhs) const
Definition at line 82 of file item_category.cpp.
 {
     return !operator==( rhs );
 }
References operator==().
operator<()
bool item_category::operator< (const item_category & rhs) const
Comparison operators.
Used for sorting. Will result in sorting by sort_rank_, then by name_header_, then by id.
Definition at line 65 of file item_category.cpp.
 {
     if( sort_rank_ != rhs.sort_rank_ ) {
         return sort_rank_ < rhs.sort_rank_;
     }
     if( name_header_.translated_ne( rhs.name_header_ ) ) {
         return name_header_.translated_lt( rhs.name_header_ );
     }
     return id < rhs.id;
 }
References id, name_header_, sort_rank_, translation::translated_lt(), and translation::translated_ne().
operator==()
bool item_category::operator== (const item_category & rhs) const
Definition at line 76 of file item_category.cpp.
 {
     return sort_rank_ == rhs.sort_rank_ && name_header_.translated_eq( rhs.name_header_ ) &&
            id == rhs.id;
 }
References id, name_header_, sort_rank_, and translation::translated_eq().
Referenced by operator!=().
priority_zone()
std::optional< zone_type_id > item_category::priority_zone (const item & it) const
Definition at line 107 of file item_category.cpp.
 {
     for( const zone_priority_data &zone_dat : zone_priority_ ) {
         if( zone_dat.filthy ) {
             if( it.is_filthy() ) {
                 return zone_dat.id;
             } else {
                 continue;
             }
         }
         if( it.has_any_flag( zone_dat.flags ) ) {
             return zone_dat.id;
         }
     }
     return std::nullopt;
 }
References item::has_any_flag(), item::is_filthy(), and zone_priority_.
Referenced by zone_manager::get_near_zone_type_for_item().
reset()
void item_category::reset () static
Definition at line 48 of file item_category.cpp.
 {
     item_category_factory.reset();
 }
References anonymous_namespace{item_category.cpp}::item_category_factory.
Referenced by DynamicDataLoader::unload_data().
sort_rank()
int item_category::sort_rank () const
Definition at line 125 of file item_category.cpp.
 {
     return sort_rank_;
 }
References sort_rank_.
Referenced by trade_preset::cat_sort_compare().
zone()
std::optional< zone_type_id > item_category::zone () const
Definition at line 102 of file item_category.cpp.
 {
     return zone_;
 }
References zone_.
Referenced by zone_manager::get_near_zone_type_for_item().
Member Data Documentation
id
item_category_id item_category::id
Unique ID of this category, used when loading from JSON.
Definition at line 50 of file item_category.h.
Referenced by item_pocket::favorite_settings::accepts_item(), item::aggregated_contents(), item_search_data::check(), get_id(), item::info(), item::is_maybe_melee_weapon(), map::item_category_spawn_rate(), icg_entry::matches(), operator<(), and operator==().
name_header_
translation item_category::name_header_ private
Name of category for displaying to the user.
Definition at line 38 of file item_category.h.
Referenced by load(), name_header(), operator<(), and operator==().
name_noun_
translation item_category::name_noun_ private
Definition at line 39 of file item_category.h.
Referenced by load(), and name_noun().
sort_rank_
int item_category::sort_rank_ = 0 private
Used to sort categories when displaying.
Lower values are shown first.
Definition at line 41 of file item_category.h.
Referenced by load(), operator<(), operator==(), and sort_rank().
spawn_rate
float item_category::spawn_rate = 1.0f private
Global spawn rate for items from category.
Definition at line 43 of file item_category.h.
Referenced by get_spawn_rate(), and load().
src
std::vector<std::pair<item_category_id, mod_id> > item_category::src
Definition at line 51 of file item_category.h.
Referenced by load_item_cat().
was_loaded
bool item_category::was_loaded = false
Definition at line 90 of file item_category.h.
Referenced by load().
zone_
std::optional<zone_type_id> item_category::zone_ private
Definition at line 45 of file item_category.h.
Referenced by load(), and zone().
zone_priority_
std::vector<zone_priority_data> item_category::zone_priority_ private
Definition at line 46 of file item_category.h.
Referenced by load(), and priority_zone().
The documentation for this class was generated from the following files:
src/item_category.h
src/item_category.cpp