Cataclysm DDA: target_ui Class Reference
target_ui Class Reference
Classes
struct turret_with_lof
Public Types
enum class TargetMode : int {
Fire , Throw , ThrowBlind , Turrets ,
TurretManual , Reach , Spell , SelectOnly
}
enum class ExitCode : int { Abort , Fire , Timeout , Reload }
Public Member Functions
target_handler::trajectory run ()
aim_type get_selected_aim_type () const
int get_sight_dispersion () const
Public Attributes
avatar * you
TargetMode mode = TargetMode::Fire
item * relevant = nullptr
int range = 0
const itype * ammo = nullptr
turret_data * turret = nullptr
const std::vector< vehicle_part * > * vturrets = nullptr
vehicle * veh = nullptr
spell * casting = nullptr
bool no_fail = false
bool no_mana = false
aim_activity_actor * activity = nullptr
Private Types
enum class Status : int { Good , BadTarget , OutOfAmmo , OutOfRange }
Private Member Functions
void init_window_and_input ()
bool handle_cursor_movement (const std::string &action, bool &skip_redraw)
bool set_cursor_pos (const tripoint &new_pos)
void on_range_ammo_changed ()
void update_target_list ()
tripoint choose_initial_target ()
bool try_reacquire_target (bool critter, tripoint &new_dst)
Try to re-acquire target for aim-and-fire.
void update_status ()
int dist_fn (const tripoint &p)
void set_last_target ()
bool confirm_non_enemy_target ()
bool prompt_friendlies_in_lof ()
std::vector< weak_ptr_fast< Creature > > list_friendlies_in_lof ()
void toggle_snap_to_target ()
void cycle_targets (int direction)
void set_view_offset (const tripoint &new_offset) const
void update_turrets_in_range ()
void recalc_aim_turning_penalty ()
void apply_aim_turning_penalty () const
bool action_switch_mode ()
bool action_switch_ammo ()
bool action_aim ()
bool action_drop_aim ()
bool action_aim_and_shoot (const std::string &action)
void draw_terrain_overlay ()
void draw_ui_window ()
std::string uitext_title () const
std::string uitext_fire () const
void draw_window_title ()
void draw_help_notice ()
void draw_controls_list (int text_y)
void panel_cursor_info (int &text_y)
void panel_gun_info (int &text_y)
void panel_recoil (int &text_y)
void panel_spell_info (int &text_y)
void panel_target_info (int &text_y, bool fill_with_blank_if_no_target)
void panel_turret_list (int &text_y)
void on_target_accepted (bool harmful) const
Private Attributes
Status status = Status::Good
std::vector< tripoint > traj
tripoint src
tripoint dst
Creature * dst_critter = nullptr
std::vector< Creature * > targets
catacurses::window w_target
input_context ctxt
int sight_dispersion = 0
std::vector< aim_type > aim_types
std::vector< aim_type >::iterator aim_mode
double predicted_recoil = 0
std::set< tripoint > spell_aoe
std::vector< turret_with_lof > turrets_in_range
bool draw_turret_lines = false
bool snap_to_target = false
bool shifting_view = false
bool compact = false
bool tiny = false
bool narrow = false
Detailed Description
Definition at line 168 of file ranged.cpp.
Member Enumeration Documentation
ExitCode
enum target_ui::ExitCode : int strong
Enumerator
Abort
Fire
Timeout
Reload
Definition at line 209 of file ranged.cpp.
                             : int {
             Abort,
             Fire,
             Timeout,
             Reload
         };
Status
enum target_ui::Status : int strong private
Enumerator
Good
BadTarget
OutOfAmmo
OutOfRange
Definition at line 225 of file ranged.cpp.
                           : int {
             Good, // All UI elements are enabled
             BadTarget, // Bad 'dst' selected; forbid aiming/firing
             OutOfAmmo, // Selected gun mode is out of ammo; forbid moving cursor,aiming and firing
             OutOfRange // Selected target is out of range of current gun mode; forbid aiming/firing
         };
TargetMode
enum target_ui::TargetMode : int strong
Enumerator
Fire
Throw
ThrowBlind
Turrets
TurretManual
Reach
Spell
SelectOnly
Definition at line 173 of file ranged.cpp.
                               : int {
             Fire,
             Throw,
             ThrowBlind,
             Turrets,
             TurretManual,
             Reach,
             Spell,
             SelectOnly
         };
Member Function Documentation
action_aim()
bool target_ui::action_aim () private
Definition at line 3421 of file ranged.cpp.
 {
     set_last_target();
     apply_aim_turning_penalty();
     const double min_recoil = calculate_aim_cap( *you, dst );
     for( int i = 0; i < 10; ++i ) {
         do_aim( *you, *relevant, min_recoil );
     }
     // We've changed pc.recoil, update penalty
     recalc_aim_turning_penalty();
     return you->get_moves() > 0;
 }
References apply_aim_turning_penalty(), calculate_aim_cap(), do_aim(), dst, Creature::get_moves(), recalc_aim_turning_penalty(), relevant, set_last_target(), and you.
Referenced by run().
action_aim_and_shoot()
bool target_ui::action_aim_and_shoot (const std::string & action) private
Definition at line 3446 of file ranged.cpp.
 {
     std::vector<aim_type>::iterator it;
     for( it = aim_types.begin(); it != aim_types.end(); it++ ) {
         if( action == it->action ) {
             break;
         }
     }
     if( it == aim_types.end() ) {
         debugmsg( "Could not find a valid aim_type for %s", action.c_str() );
         aim_mode = aim_types.begin();
     }
     int aim_threshold = it->threshold;
     set_last_target();
     apply_aim_turning_penalty();
     const double min_recoil = calculate_aim_cap( *you, dst );
     do {
         do_aim( *you, relevant ? *relevant : null_item_reference(), min_recoil );
     } while( you->get_moves() > 0 && you->recoil > aim_threshold &&
              you->recoil - sight_dispersion > min_recoil );
     // If we made it under the aim threshold, go ahead and fire.
     // Also fire if we're at our best aim level already.
     // If no critter is at dst then sight dispersion does not apply,
     // so it would lock into an infinite loop.
     bool done_aiming = you->recoil <= aim_threshold || you->recoil - sight_dispersion <= min_recoil ||
                        ( !get_creature_tracker().creature_at( dst ) && you->recoil <= min_recoil );
     return done_aiming;
 }
References action, aim_mode, aim_types, apply_aim_turning_penalty(), calculate_aim_cap(), creature_tracker::creature_at(), debugmsg, do_aim(), dst, get_creature_tracker(), Creature::get_moves(), null_item_reference(), Character::recoil, relevant, set_last_target(), sight_dispersion, and you.
Referenced by run().
action_drop_aim()
bool target_ui::action_drop_aim () private
Definition at line 3436 of file ranged.cpp.
 {
     you->recoil = MAX_RECOIL;
     // We've changed pc.recoil, update penalty
     recalc_aim_turning_penalty();
     return true;
 }
References MAX_RECOIL, recalc_aim_turning_penalty(), Character::recoil, and you.
Referenced by run().
action_switch_ammo()
bool target_ui::action_switch_ammo () private
Definition at line 3401 of file ranged.cpp.
 {
     if( mode == TargetMode::TurretManual ) {
         // For turrets that use vehicle tanks & can fire multiple liquids
         if( turret->ammo_options().size() > 1 ) {
             const auto opts = turret->ammo_options();
             auto iter = opts.find( turret->ammo_current() );
             turret->ammo_select( ++iter != opts.end() ? *iter : *opts.begin() );
             ammo = item::find_type( turret->ammo_current() );
             range = turret->range();
         }
     } else {
         // Leave aiming UI and open reloading UI since
         // reloading annihilates our aim anyway
         return false;
     }
     on_range_ammo_changed();
     return true;
 }
References ammo, turret_data::ammo_current(), turret_data::ammo_options(), turret_data::ammo_select(), item::find_type(), mode, on_range_ammo_changed(), range, turret_data::range(), turret, and TurretManual.
Referenced by run().
action_switch_mode()
bool target_ui::action_switch_mode () private
Definition at line 3304 of file ranged.cpp.
 {
     uilist menu;
     menu.settext( _( "Select preferences" ) );
     const std::pair<int, int> aim_modes_range = std::make_pair( 0, 100 );
     const std::pair<int, int> firing_modes_range = std::make_pair( 100, 200 );
     if( !aim_types.empty() ) {
         menu.addentry( -1, false, 0, "  " + std::string( _( "Default aiming mode" ) ) );
         menu.entries.back().force_color = true;
         menu.entries.back().text_color = c_cyan;
         for( auto it = aim_types.begin(); it != aim_types.end(); ++it ) {
             const bool is_active_aim_mode = aim_mode == it;
             const std::string text = ( it->name.empty() ? _( "Immediate" ) : it->name ) +
                                      ( is_active_aim_mode ? _( " (active)" ) : "" );
             menu.addentry( aim_modes_range.first + std::distance( aim_types.begin(), it ),
                            true, MENU_AUTOASSIGN, text );
             if( is_active_aim_mode ) {
                 menu.entries.back().text_color = c_light_green;
             }
         }
     }
     const std::map<gun_mode_id, gun_mode> gun_modes = relevant->gun_all_modes();
     if( !gun_modes.empty() ) {
         menu.addentry( -1, false, 0, "  " + std::string( _( "Firing mode" ) ) );
         menu.entries.back().force_color = true;
         menu.entries.back().text_color = c_cyan;
         for( auto it = gun_modes.begin(); it != gun_modes.end(); ++it ) {
             const bool active_gun_mode = relevant->gun_get_mode_id() == it->first;
             // If gun mode is from a gunmod use gunmod's name, pay attention to the "->" on tname
             std::string text = ( it->second.target == relevant )
                                ? it->second.tname()
                                : it->second->tname() + " (" + std::to_string( it->second.qty ) + ")";
             text += ( active_gun_mode ? _( " (active)" ) : "" );
             menu.entries.emplace_back( firing_modes_range.first + static_cast<int>( std::distance(
                                            gun_modes.begin(), it ) ),
                                        true, MENU_AUTOASSIGN, text );
             if( active_gun_mode ) {
                 menu.entries.back().text_color = c_light_green;
                 if( menu.selected == 0 ) {
                     menu.selected = menu.entries.size() - 1;
                 }
             }
         }
     }
     menu.query();
     bool refresh = false;
     if( menu.ret >= firing_modes_range.first && menu.ret < firing_modes_range.second ) {
         // gun mode select
         const std::map<gun_mode_id, gun_mode> all_gun_modes = relevant->gun_all_modes();
         int skip = menu.ret - firing_modes_range.first;
         for( const std::pair<const gun_mode_id, gun_mode> &it : all_gun_modes ) {
             if( skip-- == 0 ) {
                 if( relevant->gun_current_mode().melee() ) {
                     refresh = true;
                 }
                 relevant->gun_set_mode( it.first );
                 break;
             }
         }
     } else if( menu.ret >= aim_modes_range.first && menu.ret < aim_modes_range.second ) {
         // aiming mode select
         aim_mode = aim_types.begin();
         std::advance( aim_mode, menu.ret - aim_modes_range.first );
         you->preferred_aiming_mode = aim_mode->action;
     } // else - just refresh
     if( mode == TargetMode::TurretManual ) {
         itype_id ammo_current = turret->ammo_current();
         if( ammo_current.is_null() ) {
             ammo = nullptr;
             range = 0;
         } else {
             ammo = item::find_type( ammo_current );
             range = turret->range();
         }
     } else {
         if( relevant->gun_current_mode().melee() ) {
             refresh = true;
             range = relevant->current_reach_range( *you );
         } else {
             range = relevant->gun_current_mode().target->gun_range( you );
             ammo = relevant->gun_current_mode().target->ammo_data();
         }
     }
     on_range_ammo_changed();
     return refresh;
 }
References _, uilist::addentry(), aim_mode, aim_types, ammo, turret_data::ammo_current(), item::ammo_data(), c_cyan, c_light_green, item::current_reach_range(), uilist::entries, item::find_type(), item::gun_all_modes(), item::gun_current_mode(), item::gun_get_mode_id(), item::gun_range(), item::gun_set_mode(), string_id< T >::is_null(), gun_mode::melee(), MENU_AUTOASSIGN, mode, on_range_ammo_changed(), avatar::preferred_aiming_mode, uilist::query(), range, turret_data::range(), catacurses::refresh(), relevant, uilist::ret, uilist::selected, uilist::settext(), gun_mode::target, to_string(), turret, TurretManual, and you.
Referenced by run().
apply_aim_turning_penalty()
void target_ui::apply_aim_turning_penalty () const private
Definition at line 3299 of file ranged.cpp.
 {
     you->recoil = predicted_recoil;
 }
References predicted_recoil, Character::recoil, and you.
Referenced by action_aim(), and action_aim_and_shoot().
choose_initial_target()
tripoint target_ui::choose_initial_target () private
Definition at line 3011 of file ranged.cpp.
 {
     // Try previously targeted creature
     shared_ptr_fast<Creature> cr = you->last_target.lock();
     if( cr && pl_sees( *cr ) && dist_fn( cr->pos() ) <= range ) {
         return cr->pos();
     }
     // Try closest creature
     if( !targets.empty() ) {
         return targets[0]->pos();
     }
     // Try closest practice target
     map &here = get_map();
     const std::vector<tripoint> nearby = closest_points_first( src, range );
     const auto target_spot = std::find_if( nearby.begin(), nearby.end(),
     [this, &here]( const tripoint & pt ) {
         return here.tr_at( pt ).id == tr_practice_target && this->you->sees( pt );
     } );
     if( target_spot != nearby.end() ) {
         return *target_spot;
     }
     // We've got nothing.
     return src;
 }
References closest_points_first(), dist_fn(), get_map(), Character::last_target, pl_sees(), range, src, targets, and you.
Referenced by run().
confirm_non_enemy_target()
bool target_ui::confirm_non_enemy_target () private
Definition at line 3115 of file ranged.cpp.
 {
     // Check if you are casting a spell at yourself.
     if( mode == TargetMode::Spell && ( src == dst || spell_aoe.count( src ) == 1 ) ) {
         if( !query_yn( _( "Really attack yourself?" ) ) ) {
             return false;
         }
     }
     npc *const who = dynamic_cast<npc *>( dst_critter );
     if( who && !who->guaranteed_hostile() ) {
         return query_yn( _( "Really attack %s?" ), who->get_name().c_str() );
     }
     return true;
 }
References _, dst, dst_critter, Character::get_name(), npc::guaranteed_hostile(), mode, query_yn(), Spell, spell_aoe, and src.
Referenced by run().
cycle_targets()
void target_ui::cycle_targets (int direction) private
Definition at line 3202 of file ranged.cpp.
 {
     if( targets.empty() ) {
         // Nothing to cycle
         return;
     }
     if( dst_critter ) {
         auto t = std::find( targets.begin(), targets.end(), dst_critter );
         size_t new_target = 0;
         if( t != targets.end() ) {
             size_t idx = std::distance( targets.begin(), t );
             new_target = ( idx + targets.size() + direction ) % targets.size();
             set_cursor_pos( targets[new_target]->pos() );
             return;
         }
     }
     // There is either no creature under the cursor or the player can't see it.
     // Use the closest/farthest target in this case
     if( direction == 1 ) {
         set_cursor_pos( targets.front()->pos() );
     } else {
         set_cursor_pos( targets.back()->pos() );
     }
 }
References dst_critter, math_opers::pos(), set_cursor_pos(), and targets.
Referenced by handle_cursor_movement().
dist_fn()
int target_ui::dist_fn (const tripoint & p) private
Definition at line 3097 of file ranged.cpp.
 {
     return static_cast<int>( std::round( rl_dist_exact( src, p ) ) );
 }
References rl_dist_exact(), round(), and src.
Referenced by choose_initial_target(), panel_cursor_info(), set_cursor_pos(), try_reacquire_target(), and update_status().
draw_controls_list()
void target_ui::draw_controls_list (int text_y) private
Definition at line 3662 of file ranged.cpp.
 {
     // Change UI colors for visual feedback
     // TODO: Colorize keys inside brackets to be consistent with other UI windows
     nc_color col_enabled = c_white;
     nc_color col_disabled = c_light_gray;
     nc_color col_move = ( status != Status::OutOfAmmo ? col_enabled : col_disabled );
     nc_color col_fire = ( status == Status::Good ? col_enabled : col_disabled );
     // Get first key bound to given action OR ' ' if there are none.
     const auto bound_key = [this]( const std::string & s ) {
         const std::vector<input_event> keys = this->ctxt.keys_bound_to( s, /*maximum_modifier_count=*/1 );
         return keys.empty() ? input_event() : keys.front();
     };
     const auto colored = [col_enabled]( nc_color color, const std::string & s ) {
         if( color == col_enabled ) {
             // col_enabled is the default one when printing
             return s;
         } else {
             return colorize( s, color );
         }
     };
     struct line {
         size_t order; // Lines with highest 'order' are removed first
         std::string str;
     };
     std::vector<line> lines;
     // Compile full list
     if( shifting_view ) {
         lines.push_back( {8, colored( col_move, _( "Shift view with directional keys" ) )} );
     } else {
         lines.push_back( {8, colored( col_move, _( "Move cursor with directional keys" ) )} );
     }
     if( is_mouse_enabled() ) {
         std::string move = _( "Mouse: LMB: Target, Wheel: Cycle," );
         std::string fire = _( "RMB: Fire" );
         lines.push_back( {7, colored( col_move, move ) + " " + colored( col_fire, fire )} );
     }
     {
         std::string cycle = string_format( _( "[%s] Cycle targets;" ), ctxt.get_desc( "NEXT_TARGET", 1 ) );
         std::string fire = string_format( _( "[%s] %s." ), bound_key( "FIRE" ).short_description(),
                                           uitext_fire() );
         lines.push_back( {0, colored( col_move, cycle ) + " " + colored( col_fire, fire )} );
     }
     {
         std::string text = string_format( _( "[%s] target self; [%s] toggle snap-to-target" ),
                                           bound_key( "CENTER" ).short_description(),
                                           bound_key( "TOGGLE_SNAP_TO_TARGET" ).short_description() );
         lines.push_back( {3, colored( col_enabled, text )} );
     }
     if( mode == TargetMode::Fire ) {
         std::string aim_and_fire;
         for( const aim_type &e : aim_types ) {
             if( e.has_threshold ) {
                 aim_and_fire += string_format( "[%s] ", bound_key( e.action ).short_description() );
             }
         }
         aim_and_fire += _( "to aim and fire." );
         std::string aim = string_format( _( "[%s] to steady your aim.  (10 moves)" ),
                                          bound_key( "AIM" ).short_description() );
         std::string dropaim = string_format( _( "[%s] to stop aiming." ),
                                              bound_key( "STOPAIM" ).short_description() );
         lines.push_back( {2, colored( col_fire, aim )} );
         lines.push_back( { 2, colored( col_fire, dropaim ) } );
         lines.push_back( {4, colored( col_fire, aim_and_fire )} );
     }
     if( mode == TargetMode::Fire || mode == TargetMode::TurretManual || ( mode == TargetMode::Reach &&
             relevant->is_gun() && you->get_aim_types( *relevant ).size() > 1 ) ) {
         lines.push_back( {5, colored( col_enabled, string_format( _( "[%s] to switch firing modes." ),
                                       bound_key( "SWITCH_MODE" ).short_description() ) )
                          } );
         if( mode == TargetMode::Fire || mode == TargetMode::TurretManual ) {
             lines.push_back( { 6, colored( col_enabled, string_format( _( "[%s] to reload/switch ammo." ),
                                            bound_key( "SWITCH_AMMO" ).short_description() ) )
                              } );
         }
     }
     if( mode == TargetMode::Turrets ) {
         const std::string label = draw_turret_lines
                                   ? _( "[%s] Hide lines of fire" )
                                   : _( "[%s] Show lines of fire" );
         lines.push_back( {1, colored( col_enabled, string_format( label, bound_key( "TOGGLE_TURRET_LINES" ).short_description() ) )} );
     }
     // Shrink the list until it fits
     int height = getmaxy( w_target );
     int available_lines = height - text_y - 1; // 1 for bottom border
     if( available_lines <= 0 ) {
         return;
     }
     while( lines.size() > static_cast<size_t>( available_lines ) ) {
         lines.erase( std::max_element( lines.begin(), lines.end(), []( const line & l1, const line & l2 ) {
             return l1.order < l2.order;
         } ) );
     }
     text_y = height - lines.size() - 1;
     for( const line &l : lines ) {
         nc_color col = col_enabled;
         print_colored_text( w_target, point( 1, text_y++ ), col, col, l.str );
     }
 }
References _, aim_types, c_light_gray, c_white, color(), colorize(), ctxt, draw_turret_lines, fire(), Fire, Character::get_aim_types(), input_context::get_desc(), catacurses::getmaxy(), Good, item::is_gun(), is_mouse_enabled(), input_context::keys_bound_to(), line, mode, move, OutOfAmmo, point, print_colored_text(), Reach, relevant, shifting_view, status, string_format(), TurretManual, Turrets, uitext_fire(), w_target, and you.
Referenced by draw_ui_window().
draw_help_notice()
void target_ui::draw_help_notice () private
Definition at line 3648 of file ranged.cpp.
 {
     int text_y = getmaxy( w_target ) - 1;
     int width = getmaxx( w_target );
     const std::string label_help = string_format(
                                        narrow ? _( "[%s] show help" ) : _( "[%s] show all controls" ),
                                        ctxt.get_desc( "HELP_KEYBINDINGS", 1 ) );
     int label_width = std::min( utf8_width( label_help ), width - 6 ); // 6 for borders and "< " + " >"
     int text_x = width - label_width - 6;
     mvwprintz( w_target, point( text_x + 1, text_y ), c_white, "< " );
     trim_and_print( w_target, point( text_x + 3, text_y ), label_width, c_white, label_help );
     wprintz( w_target, c_white, " >" );
 }
References _, c_white, ctxt, input_context::get_desc(), catacurses::getmaxx(), catacurses::getmaxy(), min(), mvwprintz(), narrow, point, string_format(), trim_and_print(), utf8_width(), w_target, and wprintz().
Referenced by draw_ui_window().
draw_terrain_overlay()
void target_ui::draw_terrain_overlay () private
Definition at line 3476 of file ranged.cpp.
 {
     tripoint center = you->pos() + you->view_offset;
     // Removes parts that don't belong to currently visible Z level
     const auto filter_this_z = [&center]( const std::vector<tripoint> &traj ) {
         std::vector<tripoint> this_z = traj;
         this_z.erase( std::remove_if( this_z.begin(), this_z.end(),
         [&center]( const tripoint & p ) {
             return p.z != center.z;
         } ), this_z.end() );
         return this_z;
     };
     // FIXME: TILES version of g->draw_line helpfully draws a cursor at last point.
     //        This creates a fake cursor if 'dst' is on a z-level we cannot see.
     // Draw approximate line of fire for each turret in range
     if( mode == TargetMode::Turrets && draw_turret_lines ) {
         // TODO: TILES version doesn't know how to draw more than 1 line at a time.
         //       We merge all lines together and draw them as a big malformed one
         std::set<tripoint> points;
         for( const turret_with_lof &it : turrets_in_range ) {
             std::vector<tripoint> this_z = filter_this_z( it.line );
             for( const tripoint &p : this_z ) {
                 points.insert( p );
             }
         }
         // Since "trajectory" for each turret is just a straight line,
         // we can draw it even if the player can't see some parts
         points.erase( dst ); // Workaround for fake cursor on TILES
         std::vector<tripoint> l( points.begin(), points.end() );
         if( dst.z == center.z ) {
             // Workaround for fake cursor bug on TILES
             l.push_back( dst );
         }
         g->draw_line( src, center, l, true );
     }
     // Draw trajectory
     if( mode != TargetMode::Turrets && dst != src ) {
         std::vector<tripoint> this_z = filter_this_z( traj );
         // Draw a highlighted trajectory only if we can see the endpoint.
         // Provides feedback to the player, but avoids leaking information
         // about tiles they can't see.
         g->draw_line( dst, center, this_z );
     }
     // Since draw_line does nothing if destination is not visible,
     // cursor also disappears. Draw it explicitly.
     if( dst.z == center.z ) {
         g->draw_cursor( dst );
     }
     // Draw spell AOE
     if( mode == TargetMode::Spell ) {
         drawsq_params params = drawsq_params().highlight( true ).center( center );
         for( const tripoint &tile : spell_aoe ) {
             if( tile.z != center.z ) {
                 continue;
             }
 #ifdef TILES
             if( use_tiles ) {
                 g->draw_highlight( tile );
             } else {
 #endif
                 get_map().drawsq( g->w_terrain, tile, params );
 #ifdef TILES
             }
 #endif
         }
     }
 }
References center, drawsq_params::center(), draw_turret_lines, map::drawsq(), dst, g, get_map(), drawsq_params::highlight(), mode, Creature::pos(), Spell, spell_aoe, src, traj, Turrets, turrets_in_range, use_tiles, Character::view_offset, you, and tripoint::z.
Referenced by run().
draw_ui_window()
void target_ui::draw_ui_window () private
Definition at line 3551 of file ranged.cpp.
 {
     // Clear target window and make it non-transparent.
     int width = getmaxx( w_target );
     int height = getmaxy( w_target );
     for( int y = 0; y < height; y++ ) {
         for( int x = 0; x < width; x++ ) {
             mvwputch( w_target, point( x, y ), c_white, ' ' );
         }
     }
     draw_border( w_target );
     draw_window_title();
     draw_help_notice();
     int text_y = 1; // Skip top border
     panel_cursor_info( text_y );
     text_y += compact ? 0 : 1;
     if( mode == TargetMode::Fire || mode == TargetMode::TurretManual ) {
         panel_gun_info( text_y );
         panel_recoil( text_y );
         text_y += compact ? 0 : 1;
     } else if( mode == TargetMode::Spell ) {
         panel_spell_info( text_y );
         text_y += compact ? 0 : 1;
     }
     bool fill_with_blank_if_no_target = !tiny;
     panel_target_info( text_y, fill_with_blank_if_no_target );
     text_y++;
     if( mode == TargetMode::Turrets ) {
         panel_turret_list( text_y );
     } else if( status == Status::Good ) {
         // TODO: these are old, consider refactoring
         if( mode == TargetMode::Fire ) {
             text_y = print_aim( *this, *you, w_target, text_y, ctxt, *relevant->gun_current_mode(), dst );
         } else if( mode == TargetMode::Throw || mode == TargetMode::ThrowBlind ) {
             bool blind = mode == TargetMode::ThrowBlind;
             draw_throw_aim( *this, *you, w_target, text_y, ctxt, *relevant, dst, blind );
         }
     }
     if( !narrow ) {
         draw_controls_list( text_y );
     }
     wnoutrefresh( w_target );
 }
References c_white, compact, ctxt, draw_border(), draw_controls_list(), draw_help_notice(), draw_throw_aim(), draw_window_title(), dst, Fire, catacurses::getmaxx(), catacurses::getmaxy(), Good, item::gun_current_mode(), mode, mvwputch(), narrow, panel_cursor_info(), panel_gun_info(), panel_recoil(), panel_spell_info(), panel_target_info(), panel_turret_list(), point, print_aim(), relevant, Spell, status, Throw, ThrowBlind, tiny, TurretManual, Turrets, w_target, catacurses::wnoutrefresh(), and you.
Referenced by run().
draw_window_title()
void target_ui::draw_window_title () private
Definition at line 3641 of file ranged.cpp.
 {
     mvwprintz( w_target, point( 2, 0 ), c_white, "< " );
     trim_and_print( w_target, point( 4, 0 ), getmaxx( w_target ) - 7, c_red, uitext_title() );
     wprintz( w_target, c_white, " >" );
 }
References c_red, c_white, catacurses::getmaxx(), mvwprintz(), point, trim_and_print(), uitext_title(), w_target, and wprintz().
Referenced by draw_ui_window().
get_selected_aim_type()
aim_type target_ui::get_selected_aim_type () const
Definition at line 3603 of file ranged.cpp.
 {
     return this->aim_mode != this->aim_types.cend() ? *( this->aim_mode ) : get_default_aim_type();
 }
References aim_mode, aim_types, and get_default_aim_type().
get_sight_dispersion()
int target_ui::get_sight_dispersion () const
Definition at line 3608 of file ranged.cpp.
 {
     return sight_dispersion;
 }
References sight_dispersion.
handle_cursor_movement()
bool target_ui::handle_cursor_movement (const std::string & action, bool & skip_redraw) private
Definition at line 2798 of file ranged.cpp.
 {
     std::optional<tripoint> mouse_pos;
     const auto shift_view_or_cursor = [this]( const tripoint & delta ) {
         if( this->shifting_view ) {
             this->set_view_offset( this->you->view_offset + delta );
         } else {
             this->set_cursor_pos( dst + delta );
         }
     };
     if( action == "MOUSE_MOVE" || action == "TIMEOUT" ) {
         // Shift pos and/or view via edge scrolling
         tripoint edge_scroll = g->mouse_edge_scrolling_terrain( ctxt );
         if( edge_scroll == tripoint_zero ) {
             skip_redraw = true;
         } else {
             if( action == "MOUSE_MOVE" ) {
                 edge_scroll *= 2;
             }
             if( snap_to_target ) {
                 set_cursor_pos( dst + edge_scroll );
             } else {
                 set_view_offset( you->view_offset + edge_scroll );
             }
         }
     } else if( const std::optional<tripoint> delta = ctxt.get_direction( action ) ) {
         // Shift view/cursor with directional keys
         shift_view_or_cursor( *delta );
     } else if( action == "SELECT" &&
                ( mouse_pos = ctxt.get_coordinates( g->w_terrain, g->ter_view_p.xy() ) ) ) {
         // Set pos by clicking with mouse
         mouse_pos->z = you->pos().z + you->view_offset.z;
         set_cursor_pos( *mouse_pos );
     } else if( action == "LEVEL_UP" || action == "LEVEL_DOWN" ) {
         // Shift view/cursor up/down one z level
         tripoint delta = tripoint(
                              0,
                              0,
                              action == "LEVEL_UP" ? 1 : -1
                          );
         shift_view_or_cursor( delta );
     } else if( action == "NEXT_TARGET" ) {
         cycle_targets( 1 );
     } else if( action == "PREV_TARGET" ) {
         cycle_targets( -1 );
     } else if( action == "CENTER" ) {
         if( shifting_view ) {
             set_view_offset( tripoint_zero );
         } else {
             set_cursor_pos( src );
         }
     } else {
         return false;
     }
     return true;
 }
References action, ctxt, cycle_targets(), dst, g, input_context::get_coordinates(), input_context::get_direction(), Creature::pos(), set_cursor_pos(), set_view_offset(), shifting_view, snap_to_target, src, tripoint, tripoint_zero, Character::view_offset, you, and tripoint::z.
Referenced by run().
init_window_and_input()
void target_ui::init_window_and_input () private
Definition at line 2716 of file ranged.cpp.
 {
     std::string panel_type = panel_manager::get_manager().get_current_layout_id();
     narrow = ( panel_type == "compact" || panel_type == "labels-narrow" );
     int top = 0;
     int width;
     int height;
     if( narrow ) {
         // Narrow layout removes the list of controls. This allows us
         // to have small window size and not suffer from it.
         width = 34;
         height = 24;
         compact = true;
     } else {
         width = 55;
         compact = TERMY < 41;
         tiny = TERMY < 28;
         bool use_whole_sidebar = TERMY < 32;
         if( use_whole_sidebar ) {
             // If we're extremely short on space, use the whole sidebar.
             height = TERMY;
         } else if( compact ) {
             // Cover up more low-value ui elements if we're tight on space.
             height = 28;
         } else {
             // Go all out
             height = 33;
         }
     }
     w_target = catacurses::newwin( height, width, point( TERMX - width, top ) );
     ctxt = input_context( "TARGET" );
     ctxt.set_iso( true );
     ctxt.register_directions();
     ctxt.register_action( "COORDINATE" );
     ctxt.register_action( "SELECT" );
     ctxt.register_action( "FIRE" );
     ctxt.register_action( "NEXT_TARGET" );
     ctxt.register_action( "PREV_TARGET" );
     ctxt.register_action( "CENTER" );
     ctxt.register_action( "TOGGLE_SNAP_TO_TARGET" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "MOUSE_MOVE" );
     ctxt.register_action( "zoom_out" );
     ctxt.register_action( "zoom_in" );
     ctxt.register_action( "TOGGLE_MOVE_CURSOR_VIEW" );
     if( fov_3d_z_range > 0 ) {
         ctxt.register_action( "LEVEL_UP" );
         ctxt.register_action( "LEVEL_DOWN" );
     }
     if( mode == TargetMode::Fire || mode == TargetMode::TurretManual || ( mode == TargetMode::Reach &&
             relevant->is_gun() && you->get_aim_types( *relevant ).size() > 1 ) ) {
         ctxt.register_action( "SWITCH_MODE" );
         if( mode == TargetMode::Fire || mode == TargetMode::TurretManual ) {
             ctxt.register_action( "SWITCH_AMMO" );
         }
     }
     if( mode == TargetMode::Fire ) {
         ctxt.register_action( "AIM" );
         ctxt.register_action( "STOPAIM" );
         aim_types = you->get_aim_types( *relevant );
         for( aim_type &type : aim_types ) {
             if( type.has_threshold ) {
                 ctxt.register_action( type.action );
             }
         }
         aim_mode = aim_types.begin();
         for( auto it = aim_types.begin(); it != aim_types.end(); ++it ) {
             if( you->preferred_aiming_mode == it->action ) {
                 aim_mode = it; // default to persisted mode if possible
             }
         }
     }
     if( mode == TargetMode::Turrets ) {
         ctxt.register_action( "TOGGLE_TURRET_LINES" );
     }
 }
References aim_mode, aim_types, compact, ctxt, Fire, fov_3d_z_range, Character::get_aim_types(), panel_manager::get_current_layout_id(), panel_manager::get_manager(), item::is_gun(), mode, narrow, catacurses::newwin(), point, avatar::preferred_aiming_mode, Reach, input_context::register_action(), input_context::register_directions(), relevant, input_context::set_iso(), TERMX, TERMY, tiny, TurretManual, Turrets, type, w_target, and you.
Referenced by run().
list_friendlies_in_lof()
std::vector< weak_ptr_fast< Creature > > target_ui::list_friendlies_in_lof () private
Definition at line 3166 of file ranged.cpp.
 {
     std::vector<weak_ptr_fast<Creature>> ret;
     if( mode == TargetMode::Turrets || mode == TargetMode::Spell ) {
         debugmsg( "Not implemented" );
         return ret;
     }
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &p : traj ) {
         if( p != dst && p != src ) {
             Creature *cr = creatures.creature_at( p, true );
             if( cr && you->sees( *cr ) ) {
                 Creature::Attitude a = cr->attitude_to( *this->you );
                 if(
                     ( cr->is_npc() && a != Creature::Attitude::HOSTILE ) ||
                     ( !cr->is_npc() && a == Creature::Attitude::FRIENDLY )
                 ) {
                     ret.emplace_back( g->shared_from( *cr ) );
                 }
             }
         }
     }
     return ret;
 }
References a, Creature::attitude_to(), creature_tracker::creature_at(), debugmsg, dst, Creature::FRIENDLY, g, get_creature_tracker(), Creature::HOSTILE, Creature::is_npc(), mode, cata::hash64_detail::ret, Character::sees(), Spell, src, traj, Turrets, and you.
Referenced by prompt_friendlies_in_lof(), and run().
on_range_ammo_changed()
void target_ui::on_range_ammo_changed () private
Definition at line 2991 of file ranged.cpp.
 {
     update_status();
     update_target_list();
 }
References update_status(), and update_target_list().
Referenced by action_switch_ammo(), and action_switch_mode().
on_target_accepted()
void target_ui::on_target_accepted (bool harmful) const private
Definition at line 3959 of file ranged.cpp.
 {
     // TODO: all of this should be moved into on-hit code
     const auto lt_ptr = you->last_target.lock();
     if( npc *const guy = dynamic_cast<npc *>( lt_ptr.get() ) ) {
         if( harmful ) {
             if( !guy->guaranteed_hostile() ) {
                 // TODO: get rid of this. Or combine it with effect_hit_by_player
                 guy->hit_by_player = true; // used for morale penalty
             }
         }
     } else if( monster *const mon = dynamic_cast<monster *>( lt_ptr.get() ) ) {
         mon->add_effect( effect_hit_by_player, 10_minutes );
     }
 }
References effect_hit_by_player, Character::last_target, and you.
Referenced by run().
panel_cursor_info()
void target_ui::panel_cursor_info (int & text_y) private
Definition at line 3770 of file ranged.cpp.
 {
     std::string label_range;
     if( src == dst ) {
         label_range = string_format( _( "Range: %d" ), range );
     } else {
         label_range = string_format( _( "Range: %d/%d" ), dist_fn( dst ), range );
     }
     if( status == Status::OutOfRange && mode != TargetMode::Turrets ) {
         // Since each turret has its own range, highlighting cursor
         // range with red would be misleading
         label_range = colorize( label_range, c_red );
     }
     std::vector<std::string> labels;
     labels.push_back( label_range );
     if( fov_3d_z_range > 0 ) {
         labels.push_back( string_format( _( "Elevation: %d" ), dst.z - src.z ) );
     }
     labels.push_back( string_format( _( "Targets: %d" ), targets.size() ) );
     nc_color col = c_light_gray;
     int width = getmaxx( w_target );
     int text_x = 1;
     for( const std::string &s : labels ) {
         int x_left = width - text_x - 1;
         int len = utf8_width( s, true );
         if( len > x_left ) {
             text_x = 1;
             text_y++;
         }
         print_colored_text( w_target, point( text_x, text_y ), col, col, s );
         text_x += len + 1; // 1 for space
     }
     text_y++;
 }
References _, c_light_gray, c_red, colorize(), dist_fn(), dst, fov_3d_z_range, catacurses::getmaxx(), mode, OutOfRange, point, print_colored_text(), range, src, status, string_format(), targets, Turrets, utf8_width(), w_target, and tripoint::z.
Referenced by draw_ui_window().
panel_gun_info()
void target_ui::panel_gun_info (int & text_y) private
Definition at line 3807 of file ranged.cpp.
 {
     gun_mode m = relevant->gun_current_mode();
     std::string mode_name = m.tname();
     std::string gunmod_name;
     if( m.target != relevant ) {
         // Gun mode comes from a gunmod, not base gun. Add gunmod's name
         gunmod_name = m->tname() + " ";
     }
     std::string str = string_format( _( "Firing mode: <color_cyan>%s%s (%d)</color>" ),
                                      gunmod_name, mode_name, m.qty
                                    );
     nc_color clr = c_light_gray;
     print_colored_text( w_target, point( 1, text_y++ ), clr, clr, str );
     if( status == Status::OutOfAmmo ) {
         mvwprintz( w_target, point( 1, text_y++ ), c_red, _( "OUT OF AMMO" ) );
     } else if( ammo ) {
         bool is_favorite = relevant->is_ammo_container() && relevant->first_ammo().is_favorite;
         str = string_format( m->ammo_remaining() ? _( "Ammo: %s%s (%d/%d)" ) : _( "Ammo: %s%s" ),
                              colorize( ammo->nname( std::max( m->ammo_remaining(), 1 ) ), ammo->color ),
                              colorize( is_favorite ? " *" : "", ammo->color ), m->ammo_remaining(),
                              m->ammo_capacity( ammo->ammo->type ) );
         print_colored_text( w_target, point( 1, text_y++ ), clr, clr, str );
     } else {
         // Weapon doesn't use ammunition
         text_y++;
     }
 }
References _, itype::ammo, ammo, item::ammo_capacity(), item::ammo_remaining(), c_light_gray, c_red, itype::color, colorize(), item::first_ammo(), item::gun_current_mode(), item::is_ammo_container(), item::is_favorite, max(), mvwprintz(), itype::nname(), OutOfAmmo, point, print_colored_text(), gun_mode::qty, relevant, status, string_format(), gun_mode::target, gun_mode::tname(), item::tname(), and w_target.
Referenced by draw_ui_window().
panel_recoil()
void target_ui::panel_recoil (int & text_y) private
Definition at line 3837 of file ranged.cpp.
 {
     const int val = you->recoil_total();
     const int min_recoil = relevant->sight_dispersion( *you ).second;
     const int recoil_range = MAX_RECOIL - min_recoil;
     std::string str;
     if( val >= min_recoil + ( recoil_range * 2 / 3 ) ) {
         str = pgettext( "amount of backward momentum", "<color_red>High</color>" );
     } else if( val >= min_recoil + ( recoil_range / 2 ) ) {
         str = pgettext( "amount of backward momentum", "<color_yellow>Medium</color>" );
     } else if( val >= min_recoil + ( recoil_range / 4 ) ) {
         str = pgettext( "amount of backward momentum", "<color_light_green>Low</color>" );
     } else {
         str = pgettext( "amount of backward momentum", "<color_cyan>None</color>" );
     }
     str = string_format( _( "Recoil: %s" ), str );
     nc_color clr = c_light_gray;
     print_colored_text( w_target, point( 1, text_y++ ), clr, clr, str );
 }
References _, c_light_gray, MAX_RECOIL, pgettext, point, print_colored_text(), Character::recoil_total(), relevant, item::sight_dispersion(), string_format(), w_target, and you.
Referenced by draw_ui_window().
panel_spell_info()
void target_ui::panel_spell_info (int & text_y) private
Definition at line 3857 of file ranged.cpp.
 {
     nc_color clr = c_light_gray;
     mvwprintz( w_target, point( 1, text_y++ ), c_light_green, _( "Casting: %s (Level %u)" ),
                casting->name(),
                casting->get_level() );
     if( !no_mana || casting->energy_source() == magic_energy_type::none ) {
         if( casting->energy_source() == magic_energy_type::hp ) {
             text_y += fold_and_print( w_target, point( 1, text_y ), getmaxx( w_target ) - 2,
                                       clr,
                                       _( "Cost: %s %s" ), casting->energy_cost_string( *you ), casting->energy_string() );
         } else {
             text_y += fold_and_print( w_target, point( 1, text_y ), getmaxx( w_target ) - 2,
                                       clr,
                                       _( "Cost: %s %s (Current: %s)" ), casting->energy_cost_string( *you ), casting->energy_string(),
                                       casting->energy_cur_string( *you ) );
         }
     }
     std::string fail_str;
     if( no_fail ) {
         fail_str = colorize( _( "0.0 % Failure Chance" ), c_light_green );
     } else {
         fail_str = casting->colorized_fail_percent( *you );
     }
     print_colored_text( w_target, point( 1, text_y++ ), clr, clr, fail_str );
     if( casting->aoe( get_player_character() ) > 0 ) {
         nc_color color = c_light_gray;
         const std::string fx = casting->effect();
         const std::string aoes = casting->aoe_string( get_player_character() );
         if( fx == "attack" || fx == "area_pull" || fx == "area_push" || fx == "ter_transform" ) {
             if( casting->shape() == spell_shape::cone ) {
                 text_y += fold_and_print( w_target, point( 1, text_y ), getmaxx( w_target ) - 2, color,
                                           _( "Cone Arc: %s degrees" ), aoes );
             } else if( casting->shape() == spell_shape::line ) {
                 text_y += fold_and_print( w_target, point( 1, text_y ), getmaxx( w_target ) - 2, color,
                                           _( "Line width: %s" ), aoes );
             } else {
                 text_y += fold_and_print( w_target, point( 1, text_y ), getmaxx( w_target ) - 2, color,
                                           _( "Effective Spell Radius: %s%s" ), aoes,
                                           casting->in_aoe( src, dst, get_player_character() ) ? colorize( _( " WARNING!  IN RANGE" ),
                                                   c_red ) : "" );
             }
         }
     }
     mvwprintz( w_target, point( 1, text_y++ ), c_light_red, _( "Damage: %s" ),
                casting->damage_string( get_player_character() ) );
     text_y += fold_and_print( w_target, point( 1, text_y ), getmaxx( w_target ) - 2, clr,
                               casting->description() );
 }
References _, spell::aoe(), spell::aoe_string(), c_light_gray, c_light_green, c_light_red, c_red, casting, color(), colorize(), spell::colorized_fail_percent(), cone, spell::damage_string(), spell::description(), dst, spell::effect(), spell::energy_cost_string(), spell::energy_cur_string(), spell::energy_source(), spell::energy_string(), fold_and_print(), spell::get_level(), get_player_character(), catacurses::getmaxx(), hp, spell::in_aoe(), line, mvwprintz(), spell::name(), no_fail, no_mana, none, point, print_colored_text(), spell::shape(), src, w_target, and you.
Referenced by draw_ui_window().
panel_target_info()
void target_ui::panel_target_info (int & text_y, bool fill_with_blank_if_no_target) private
Definition at line 3913 of file ranged.cpp.
 {
     int max_lines = 6;
     if( dst_critter ) {
         if( you->sees( *dst_critter ) ) {
             // FIXME: print_info doesn't really care about line limit
             //        and can always occupy up to 4 of them (or even more?).
             //        To make things consistent, we ask it for 2 lines
             //        and somewhat reliably get 4.
             int fix_for_print_info = max_lines - 2;
             dst_critter->print_info( w_target, text_y, fix_for_print_info, 1 );
             text_y += max_lines;
         } else {
             std::vector<std::string> buf;
             if( you->sees_with_infrared( *dst_critter ) ) {
                 dst_critter->describe_infrared( buf );
             } else if( you->sees_with_specials( *dst_critter ) ) {
                 dst_critter->describe_specials( buf );
             }
             for( size_t i = 0; i < static_cast<size_t>( max_lines ); i++, text_y++ ) {
                 if( i >= buf.size() ) {
                     continue;
                 }
                 mvwprintw( w_target, point( 1, text_y ), buf[i] );
             }
         }
     } else if( fill_with_blank_if_no_target ) {
         // Fill with blank lines to prevent other panels from jumping around
         // when the cursor moves.
         text_y += max_lines;
         // TODO: print info about tile?
     }
 }
References Creature::describe_infrared(), Creature::describe_specials(), dst_critter, catacurses::mvwprintw(), point, Creature::print_info(), Character::sees(), Character::sees_with_infrared(), Character::sees_with_specials(), w_target, and you.
Referenced by draw_ui_window().
panel_turret_list()
void target_ui::panel_turret_list (int & text_y) private
Definition at line 3947 of file ranged.cpp.
 {
     mvwprintw( w_target, point( 1, text_y++ ), _( "Turrets in range: %d/%d" ), turrets_in_range.size(),
                vturrets->size() );
     for( const turret_with_lof &it : turrets_in_range ) {
         std::string str = string_format( "* %s", it.turret->name() );
         nc_color clr = c_white;
         print_colored_text( w_target, point( 1, text_y++ ), clr, clr, str );
     }
 }
References _, c_white, catacurses::mvwprintw(), point, print_colored_text(), string_format(), turrets_in_range, vturrets, and w_target.
Referenced by draw_ui_window().
prompt_friendlies_in_lof()
bool target_ui::prompt_friendlies_in_lof () private
Definition at line 3130 of file ranged.cpp.
 {
     if( mode != TargetMode::Fire ) {
         debugmsg( "Not implemented" );
         return true;
     }
     std::vector<weak_ptr_fast<Creature>> in_lof = list_friendlies_in_lof();
     std::vector<Creature *> new_in_lof;
     for( const weak_ptr_fast<Creature> &cr_ptr : in_lof ) {
         bool found = false;
         Creature *cr = cr_ptr.lock().get();
         for( const weak_ptr_fast<Creature> &cr2_ptr : activity->acceptable_losses ) {
             Creature *cr2 = cr2_ptr.lock().get();
             if( cr == cr2 ) {
                 found = true;
                 break;
             }
         }
         if( !found ) {
             new_in_lof.push_back( cr );
         }
     }
     if( new_in_lof.empty() ) {
         return true;
     }
     std::string msg = _( "There are friendly creatures in line of fire:\n" );
     for( Creature *cr : new_in_lof ) {
         msg += "  " + cr->disp_name() + "\n";
     }
     msg += _( "Proceed with the attack?" );
     return query_yn( msg );
 }
References _, aim_activity_actor::acceptable_losses, activity, debugmsg, Fire, list_friendlies_in_lof(), mode, and query_yn().
Referenced by run().
recalc_aim_turning_penalty()
void target_ui::recalc_aim_turning_penalty () private
Gun increases the penalty for reorienting aim while below 5
Definition at line 3255 of file ranged.cpp.
 {
     // since we are recalcing recoil dirty the aimm cache
     you->aim_cache_dirty = true;
     if( status != Status::Good ) {
         // We don't care about invalid situations
         predicted_recoil = MAX_RECOIL;
         return;
     }
     double curr_recoil = you->recoil;
     tripoint curr_recoil_pos;
     const Creature *lt_ptr = you->last_target.lock().get();
     if( lt_ptr ) {
         curr_recoil_pos = lt_ptr->pos();
     } else if( you->last_target_pos ) {
         curr_recoil_pos = get_map().getlocal( *you->last_target_pos );
     } else {
         curr_recoil_pos = src;
     }
     if( curr_recoil_pos == dst ) {
         // We're aiming at that point right now, no penalty
         predicted_recoil = curr_recoil;
     } else if( curr_recoil_pos == src ) {
         // The player wasn't aiming anywhere, max it out
         predicted_recoil = MAX_RECOIL;
     } else {
         // Raise it proportionally to how much
         // the player has to turn from previous aiming point
         // the player loses their aim more quickly if less skilled, normalizing at 5 skill.
         /** @EFFECT_GUN increases the penalty for reorienting aim while below 5 */
         const double skill_penalty = std::max( 0.0, 5.0 - you->get_skill_level( skill_gun ) );
         const double recoil_per_degree = skill_penalty * MAX_RECOIL / 180.0;
         const units::angle angle_curr = coord_to_angle( src, curr_recoil_pos );
         const units::angle angle_desired = coord_to_angle( src, dst );
         const units::angle phi = normalize( angle_curr - angle_desired );
         const units::angle angle = std::min( phi, 360.0_degrees - phi );
         predicted_recoil =
             std::min( MAX_RECOIL, curr_recoil + to_degrees( angle ) * recoil_per_degree );
     }
 }
References avatar::aim_cache_dirty, coord_to_angle(), dst, get_map(), Character::get_skill_level(), map::getlocal(), Good, Character::last_target, Character::last_target_pos, max(), MAX_RECOIL, min(), normalize(), Creature::pos(), predicted_recoil, Character::recoil, skill_gun, src, status, units::to_degrees(), and you.
Referenced by action_aim(), action_drop_aim(), and set_cursor_pos().
run()
target_handler::trajectory target_ui::run ()
Definition at line 2463 of file ranged.cpp.
 {
     if( mode == TargetMode::Spell && !no_mana && !casting->can_cast( *you ) ) {
         you->add_msg_if_player( m_bad, _( "You don't have enough %s to cast this spell" ),
                                 casting->energy_string() );
     } else if( mode == TargetMode::Fire ) {
         sight_dispersion = you->most_accurate_aiming_method_limit( *relevant );
     }
     map &here = get_map();
     // Load settings
     snap_to_target = get_option<bool>( "SNAP_TO_TARGET" );
     if( mode == TargetMode::Turrets ) {
         // Due to how cluttered the display would become, disable it by default
         // unless aiming a single turret.
         draw_turret_lines = vturrets->size() == 1;
     }
     avatar &player_character = get_avatar();
     on_out_of_scope cleanup( [&here, &player_character]() {
         here.invalidate_map_cache( player_character.pos().z + player_character.view_offset.z );
     } );
     shared_ptr_fast<game::draw_callback_t> target_ui_cb = make_shared_fast<game::draw_callback_t>(
     [&]() {
         draw_terrain_overlay();
     } );
     g->add_draw_callback( target_ui_cb );
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         init_window_and_input();
         ui.position_from_window( w_target );
     } );
     ui.mark_resize();
     ui.on_redraw( [&]( const ui_adaptor & ) {
         draw_ui_window();
     } );
     // Handle multi-turn aiming
     std::string action;
     bool attack_was_confirmed = false;
     bool reentered = false;
     bool resume_critter = false;
     if( mode == TargetMode::Fire && !activity->first_turn ) {
         // We were in this UI during previous turn...
         reentered = true;
         std::string act_data = activity->action;
         if( act_data == "AIM" ) {
             // ...and ran out of moves while aiming.
         } else {
             // ...and selected 'aim and shoot', but ran out of moves.
             // So, skip retrieving input and go straight to the action.
             action = act_data;
             attack_was_confirmed = true;
         }
         // Load state to keep the ui consistent across turns
         snap_to_target = activity->snap_to_target;
         shifting_view = activity->shifting_view;
         resume_critter = activity->aiming_at_critter;
     }
     // Initialize cursor position
     src = you->pos();
     update_target_list();
     if( activity && activity->abort_if_no_targets && targets.empty() ) {
         // this branch is taken when already shot once and re-entered
         // aiming, if no targets are available we want to abort so
         // players don't arrive at aiming ui with nothing to shoot at.
         activity->aborted = true;
         traj.clear();
         return traj;
     }
     tripoint initial_dst = src;
     if( reentered ) {
         if( !try_reacquire_target( resume_critter, initial_dst ) ) {
             // Target lost
             action.clear();
             attack_was_confirmed = false;
         }
     } else {
         initial_dst = choose_initial_target();
     }
     set_cursor_pos( initial_dst );
     if( dst != initial_dst ) {
         // Our target moved out of range
         action.clear();
         attack_was_confirmed = false;
     }
     if( mode == TargetMode::Fire ) {
         if( activity->aif_duration > AIF_DURATION_LIMIT ) {
             // Break long (potentially infinite) aim-and-fire loop.
             // May happen if e.g. avatar tries to get 'precise' shot while being
             // attacked by multiple zombies, which triggers dodges and corresponding aim loss.
             action.clear();
             attack_was_confirmed = false;
         }
         if( !activity->first_turn && !action.empty() && !prompt_friendlies_in_lof() ) {
             // A friendly creature moved into line of fire during aim-and-shoot,
             // and player decided to stop aiming
             action.clear();
             attack_was_confirmed = false;
         }
         activity->acceptable_losses.clear();
         if( action.empty() ) {
             activity->aif_duration = 0;
         } else {
             activity->aif_duration += 1;
         }
     }
     // Event loop!
     ExitCode loop_exit_code;
     std::string timed_out_action;
     bool skip_redraw = false;
     for( ;; action.clear() ) {
         if( !skip_redraw ) {
             g->invalidate_main_ui_adaptor();
             ui_manager::redraw();
         }
         skip_redraw = false;
         // Wait for user input (or use value retrieved from activity)
         if( action.empty() ) {
             int timeout = get_option<int>( "EDGE_SCROLL" );
             action = ctxt.handle_input( timeout );
         }
         // If an aiming mode is selected, use "*_SHOT" instead of "FIRE"
         if( mode == TargetMode::Fire && action == "FIRE" && aim_mode->has_threshold ) {
             action = aim_mode->action;
         }
         // Handle received input
         if( handle_cursor_movement( action, skip_redraw ) ) {
             continue;
         } else if( action == "TOGGLE_SNAP_TO_TARGET" ) {
             toggle_snap_to_target();
         } else if( action == "TOGGLE_TURRET_LINES" ) {
             draw_turret_lines = !draw_turret_lines;
         } else if( action == "TOGGLE_MOVE_CURSOR_VIEW" ) {
             if( snap_to_target ) {
                 toggle_snap_to_target();
             }
             shifting_view = !shifting_view;
         } else if( action == "zoom_in" ) {
             g->zoom_in();
             g->mark_main_ui_adaptor_resize();
         } else if( action == "zoom_out" ) {
             g->zoom_out();
             g->mark_main_ui_adaptor_resize();
         } else if( action == "QUIT" ) {
             loop_exit_code = ExitCode::Abort;
             break;
         } else if( action == "SWITCH_MODE" ) {
             if( action_switch_mode() ) {
                 loop_exit_code = ExitCode::Abort;
                 break;
             }
         } else if( action == "SWITCH_AMMO" ) {
             if( !action_switch_ammo() ) {
                 loop_exit_code = ExitCode::Reload;
                 break;
             }
         } else if( action == "FIRE" ) {
             if( status != Status::Good ) {
                 continue;
             }
             bool can_skip_confirm = mode == TargetMode::Spell && casting->damage( player_character ) <= 0;
             if( !can_skip_confirm && !confirm_non_enemy_target() ) {
                 continue;
             }
             set_last_target();
             loop_exit_code = ExitCode::Fire;
             break;
         } else if( action == "AIM" ) {
             if( status != Status::Good ) {
                 continue;
             }
             // No confirm_non_enemy_target here because we have not initiated the firing.
             // Aiming can be stopped / aborted at any time.
             if( !action_aim() ) {
                 timed_out_action = "AIM";
                 loop_exit_code = ExitCode::Timeout;
                 break;
             }
         } else if( action == "STOPAIM" ) {
             if( status != Status::Good ) {
                 continue;
             }
             action_drop_aim();
         } else if( action == "AIMED_SHOT" || action == "CAREFUL_SHOT" || action == "PRECISE_SHOT" ) {
             if( status != Status::Good ) {
                 continue;
             }
             // This action basically means "Fire" as well; the actual firing may be delayed
             // through aiming, but there is usually no means to abort it. Therefore we query now
             if( !attack_was_confirmed && !confirm_non_enemy_target() ) {
                 continue;
             }
             if( action_aim_and_shoot( action ) ) {
                 loop_exit_code = ExitCode::Fire;
             } else {
                 timed_out_action = action;
                 loop_exit_code = ExitCode::Timeout;
             }
             break;
         }
     } // for(;;)
     switch( loop_exit_code ) {
         case ExitCode::Abort: {
             traj.clear();
             if( mode == TargetMode::Fire || ( mode == TargetMode::Reach && activity ) ) {
                 activity->aborted = true;
             }
             break;
         }
         case ExitCode::Fire: {
             if( mode != TargetMode::SelectOnly ) {
                 bool harmful = !( mode == TargetMode::Spell && casting->damage( player_character ) <= 0 );
                 on_target_accepted( harmful );
             }
             break;
         }
         case ExitCode::Timeout: {
             // We've ran out of moves, save UI state
             activity->acceptable_losses = list_friendlies_in_lof();
             traj.clear();
             activity->action = timed_out_action;
             activity->snap_to_target = snap_to_target;
             activity->shifting_view = shifting_view;
             activity->aiming_at_critter = !!dst_critter;
             break;
         }
         case ExitCode::Reload: {
             traj.clear();
             activity->aborted = true;
             activity->reload_requested = true;
             break;
         }
     }
     return traj;
 }
References _, Abort, aim_activity_actor::abort_if_no_targets, aim_activity_actor::aborted, aim_activity_actor::acceptable_losses, aim_activity_actor::action, action, action_aim(), action_aim_and_shoot(), action_drop_aim(), action_switch_ammo(), action_switch_mode(), activity, Character::add_msg_if_player(), aim_activity_actor::aif_duration, AIF_DURATION_LIMIT, aim_mode, aim_activity_actor::aiming_at_critter, spell::can_cast(), casting, choose_initial_target(), confirm_non_enemy_target(), ctxt, spell::damage(), draw_terrain_overlay(), draw_turret_lines, draw_ui_window(), dst, dst_critter, spell::energy_string(), Fire, aim_activity_actor::first_turn, g, get_avatar(), get_map(), Good, handle_cursor_movement(), input_context::handle_input(), init_window_and_input(), map::invalidate_map_cache(), list_friendlies_in_lof(), m_bad, mode, Character::most_accurate_aiming_method_limit(), no_mana, on_target_accepted(), Creature::pos(), prompt_friendlies_in_lof(), Reach, ui_manager::redraw(), relevant, Reload, aim_activity_actor::reload_requested, SelectOnly, set_cursor_pos(), set_last_target(), aim_activity_actor::shifting_view, shifting_view, sight_dispersion, aim_activity_actor::snap_to_target, snap_to_target, Spell, src, status, targets, timeout, Timeout, toggle_snap_to_target(), traj, try_reacquire_target(), Turrets, update_target_list(), Character::view_offset, vturrets, w_target, you, and tripoint::z.
set_cursor_pos()
bool target_ui::set_cursor_pos (const tripoint & new_pos) private
Definition at line 2857 of file ranged.cpp.
 {
     if( dst == new_pos ) {
         return false;
     }
     if( status == Status::OutOfAmmo && new_pos != src ) {
         // range == 0, no sense in moving cursor
         return false;
     }
     // Make sure new position is valid or find a closest valid position
     std::vector<tripoint> new_traj;
     tripoint valid_pos = new_pos;
     map &here = get_map();
     if( new_pos != src ) {
         // On Z axis, make sure we do not exceed map boundaries
         valid_pos.z = clamp( valid_pos.z, -OVERMAP_DEPTH, OVERMAP_HEIGHT );
         // Or current view range
         valid_pos.z = clamp( valid_pos.z - src.z, -fov_3d_z_range, fov_3d_z_range ) + src.z;
         new_traj = here.find_clear_path( src, valid_pos );
         if( range == 1 ) {
             // We should always be able to hit adjacent squares
             if( square_dist( src, valid_pos ) > 1 ) {
                 valid_pos = new_traj[0];
             }
         } else if( trigdist ) {
             if( dist_fn( valid_pos ) > range ) {
                 // Find the farthest point that is still in range
                 for( size_t i = new_traj.size(); i > 0; i-- ) {
                     if( dist_fn( new_traj[i - 1] ) <= range ) {
                         valid_pos = new_traj[i - 1];
                         break;
                     }
                 }
                 // FIXME: due to a bug in map::find_clear_path (#39693),
                 //        returned trajectory is invalid in some cases.
                 //        This bandaid stops us from exceeding range,
                 //        but does not fix the issue.
                 if( dist_fn( valid_pos ) > range ) {
                     debugmsg( "Exceeded allowed range!" );
                     valid_pos = src;
                 }
             }
         } else {
             tripoint delta = valid_pos - src;
             valid_pos = src + tripoint(
                             clamp( delta.x, -range, range ),
                             clamp( delta.y, -range, range ),
                             clamp( delta.z, -range, range )
                         );
         }
     } else {
         new_traj.push_back( src );
     }
     if( valid_pos == dst ) {
         // We don't need to move the cursor after all
         return false;
     } else if( new_pos == valid_pos ) {
         // We can reuse new_traj
         dst = valid_pos;
         traj = new_traj;
     } else {
         dst = valid_pos;
         traj = here.find_clear_path( src, dst );
     }
     if( snap_to_target ) {
         set_view_offset( dst - src );
     }
     // Make player's sprite flip to face the current target
     point d( dst.xy() - src.xy() );
     if( !g->is_tileset_isometric() ) {
         if( d.x > 0 ) {
             you->facing = FacingDirection::RIGHT;
         } else if( d.x < 0 ) {
             you->facing = FacingDirection::LEFT;
         }
     } else {
         if( d.x >= 0 && d.y >= 0 ) {
             you->facing = FacingDirection::RIGHT;
         }
         if( d.y <= 0 && d.x <= 0 ) {
             you->facing = FacingDirection::LEFT;
         }
     }
     // Cache creature under cursor
     if( src != dst ) {
         Creature *cr = get_creature_tracker().creature_at( dst, true );
         if( cr && pl_sees( *cr ) ) {
             dst_critter = cr;
         } else {
             dst_critter = nullptr;
         }
     } else {
         dst_critter = nullptr;
     }
     // Update mode-specific stuff
     if( mode == TargetMode::Fire ) {
         recalc_aim_turning_penalty();
     } else if( mode == TargetMode::Spell ) {
         switch( casting->shape() ) {
             case spell_shape::blast:
                 spell_aoe = spell_effect::spell_effect_blast(
                                 spell_effect::override_parameters( *casting, get_player_character() ), src, dst );
                 break;
             case spell_shape::cone:
                 spell_aoe = spell_effect::spell_effect_cone(
                                 spell_effect::override_parameters( *casting, get_player_character() ), src, dst );
                 break;
             case spell_shape::line:
                 spell_aoe = spell_effect::spell_effect_line(
                                 spell_effect::override_parameters( *casting, get_player_character() ), src, dst );
                 break;
             default:
                 spell_aoe.clear();
                 debugmsg( "%s does not have valid spell shape", casting->id().str() );
                 break;
         }
     } else if( mode == TargetMode::Turrets ) {
         update_turrets_in_range();
     }
     // Update UI controls & colors
     update_status();
     return true;
 }
References blast, casting, clamp(), cone, creature_tracker::creature_at(), debugmsg, dist_fn(), dst, dst_critter, Creature::facing, map::find_clear_path(), Fire, fov_3d_z_range, g, get_creature_tracker(), get_map(), get_player_character(), spell::id(), LEFT, line, mode, OutOfAmmo, OVERMAP_DEPTH, OVERMAP_HEIGHT, pl_sees(), range, recalc_aim_turning_penalty(), RIGHT, set_view_offset(), spell::shape(), snap_to_target, Spell, spell_aoe, spell_effect::spell_effect_blast(), spell_effect::spell_effect_cone(), spell_effect::spell_effect_line(), square_dist(), src, status, string_id< T >::str(), traj, trigdist, tripoint, Turrets, update_status(), update_turrets_in_range(), point::x, tripoint::x, tripoint::xy(), point::y, tripoint::y, you, and tripoint::z.
Referenced by cycle_targets(), handle_cursor_movement(), and run().
set_last_target()
void target_ui::set_last_target () private
Definition at line 3102 of file ranged.cpp.
 {
     if( !you->last_target_pos.has_value() || you->last_target_pos.value() != get_map().getabs( dst ) ) {
         you->aim_cache_dirty = true;
     }
     you->last_target_pos = get_map().getabs( dst );
     if( dst_critter ) {
         you->last_target = g->shared_from( *dst_critter );
     } else {
         you->last_target.reset();
     }
 }
References avatar::aim_cache_dirty, dst, dst_critter, g, get_map(), map::getabs(), Character::last_target, Character::last_target_pos, and you.
Referenced by action_aim(), action_aim_and_shoot(), and run().
set_view_offset()
void target_ui::set_view_offset (const tripoint & new_offset) const private
Definition at line 3229 of file ranged.cpp.
 {
     tripoint new_( new_offset.xy(), clamp( new_offset.z, -fov_3d_z_range, fov_3d_z_range ) );
     new_.z = clamp( new_.z + src.z, -OVERMAP_DEPTH, OVERMAP_HEIGHT ) - src.z;
     bool changed_z = you->view_offset.z != new_.z;
     you->view_offset = new_;
     if( changed_z ) {
         // We need to do a bunch of cache updates since we're
         // looking at a different z-level.
         get_map().invalidate_map_cache( new_.z );
     }
 }
References clamp(), fov_3d_z_range, get_map(), map::invalidate_map_cache(), OVERMAP_DEPTH, OVERMAP_HEIGHT, src, Character::view_offset, tripoint::xy(), you, and tripoint::z.
Referenced by handle_cursor_movement(), set_cursor_pos(), and toggle_snap_to_target().
toggle_snap_to_target()
void target_ui::toggle_snap_to_target () private
Definition at line 3191 of file ranged.cpp.
 {
     shifting_view = false;
     if( snap_to_target ) {
         // Keep current view offset
     } else {
         set_view_offset( dst - src );
     }
     snap_to_target = !snap_to_target;
 }
References dst, set_view_offset(), shifting_view, snap_to_target, and src.
Referenced by run().
try_reacquire_target()
bool target_ui::try_reacquire_target (bool critter, tripoint & new_dst) private
Try to re-acquire target for aim-and-fire.
Parameters
critter whether were aiming at a critter, or a tile
new_dst where to move aim cursor (if e.g. critter moved)
Returns
true on success
Definition at line 3039 of file ranged.cpp.
 {
     if( critter ) {
         // Try to re-acquire the creature
         shared_ptr_fast<Creature> cr = you->last_target.lock();
         if( cr && pl_sees( *cr ) && dist_fn( cr->pos() ) <= range ) {
             new_dst = cr->pos();
             return true;
         }
     }
     if( !you->last_target_pos.has_value() ) {
         // This shouldn't happen
         return false;
     }
     // Try to re-acquire target tile or tile where the target creature used to be
     tripoint local_lt = get_map().getlocal( *you->last_target_pos );
     if( dist_fn( local_lt ) <= range ) {
         new_dst = local_lt;
         // Abort aiming if a creature moved in
         return !critter && !get_creature_tracker().creature_at( local_lt, true );
     }
     // We moved out of range
     return false;
 }
References creature_tracker::creature_at(), dist_fn(), get_creature_tracker(), get_map(), map::getlocal(), Character::last_target, Character::last_target_pos, pl_sees(), range, and you.
Referenced by run().
uitext_fire()
std::string target_ui::uitext_fire () const private
Definition at line 3628 of file ranged.cpp.
 {
     if( mode == TargetMode::Throw || mode == TargetMode::ThrowBlind ) {
         return to_translation( "[Hotkey] to throw", "to throw" ).translated();
     } else if( mode == TargetMode::Reach ) {
         return to_translation( "[Hotkey] to attack", "to attack" ).translated();
     } else if( mode == TargetMode::Spell ) {
         return to_translation( "[Hotkey] to cast the spell", "to cast" ).translated();
     } else {
         return to_translation( "[Hotkey] to fire", "to fire" ).translated();
     }
 }
References mode, Reach, Spell, Throw, ThrowBlind, to_translation(), and translation::translated().
Referenced by draw_controls_list().
uitext_title()
std::string target_ui::uitext_title () const private
Definition at line 3613 of file ranged.cpp.
 {
     switch( mode ) {
         case TargetMode::Fire:
         case TargetMode::TurretManual:
             return string_format( _( "Firing %s" ), relevant->tname() );
         case TargetMode::Throw:
             return string_format( _( "Throwing %s" ), relevant->tname() );
         case TargetMode::ThrowBlind:
             return string_format( _( "Blind throwing %s" ), relevant->tname() );
         default:
             return _( "Set target" );
     }
 }
References _, Fire, mode, relevant, string_format(), Throw, ThrowBlind, item::tname(), and TurretManual.
Referenced by draw_window_title().
update_status()
void target_ui::update_status () private
Definition at line 3067 of file ranged.cpp.
 {
     std::vector<std::string> msgbuf;
     if( mode == TargetMode::Turrets && turrets_in_range.empty() ) { // NOLINT(bugprone-branch-clone)
         // None of the turrets are in range
         status = Status::OutOfRange;
     } else if( mode == TargetMode::Fire &&
                ( !gunmode_checks_common( *you, get_map(), msgbuf, relevant->gun_current_mode() ) ||
                  !gunmode_checks_weapon( *you, get_map(), msgbuf, relevant->gun_current_mode() ) )
              ) { // NOLINT(bugprone-branch-clone)
         // Selected gun mode is empty
         // TODO: it might be some other error, but that's highly unlikely to happen, so a catch-all 'Out of ammo' is fine
         status = Status::OutOfAmmo;
     } else if( mode == TargetMode::TurretManual && ( turret->query() != turret_data::status::ready ||
                !gunmode_checks_common( *you, get_map(), msgbuf, relevant->gun_current_mode() ) ) ) {
         status = Status::OutOfAmmo;
     } else if( ( src == dst ) && !( mode == TargetMode::Spell &&
                                     casting->is_valid_target( spell_target::self ) ) ) {
         // TODO: consider allowing targeting yourself with turrets
         status = Status::BadTarget;
     } else if( dist_fn( dst ) > range ) {
         // We're out of range. This can happen if we switch from long-ranged
         // gun mode to short-ranged. We can, of course, move the cursor into range automatically,
         // but that would be rude. Instead, wait for directional keys/etc. and *then* move the cursor.
         status = Status::OutOfRange;
     } else {
         status = Status::Good;
     }
 }
References BadTarget, casting, dist_fn(), dst, Fire, get_map(), Good, item::gun_current_mode(), gunmode_checks_common(), gunmode_checks_weapon(), spell::is_valid_target(), mode, OutOfAmmo, OutOfRange, turret_data::query(), range, turret_data::ready, relevant, self, Spell, src, status, turret, TurretManual, Turrets, turrets_in_range, and you.
Referenced by on_range_ammo_changed(), and set_cursor_pos().
update_target_list()
void target_ui::update_target_list () private
Definition at line 2997 of file ranged.cpp.
 {
     if( range == 0 ) {
         targets.clear();
         return;
     }
     // Get targets in range and sort them by distance (targets[0] is the closest)
     targets = you->get_targetable_creatures( range, mode == TargetMode::Reach );
     std::sort( targets.begin(), targets.end(), [&]( const Creature * lhs, const Creature * rhs ) {
         return rl_dist_exact( lhs->pos(), you->pos() ) < rl_dist_exact( rhs->pos(), you->pos() );
     } );
 }
References Character::get_targetable_creatures(), mode, range, Reach, targets, and you.
Referenced by on_range_ammo_changed(), and run().
update_turrets_in_range()
void target_ui::update_turrets_in_range () private
Definition at line 3243 of file ranged.cpp.
 {
     turrets_in_range.clear();
     for( vehicle_part *t : *vturrets ) {
         turret_data td = veh->turret_query( *t );
         if( td.in_range( dst ) ) {
             tripoint src = veh->global_part_pos3( *t );
             turrets_in_range.push_back( {t, line_to( src, dst )} );
         }
     }
 }
References dst, vehicle::global_part_pos3(), turret_data::in_range(), line_to(), src, vehicle::turret_query(), turrets_in_range, veh, and vturrets.
Referenced by set_cursor_pos().
Member Data Documentation
activity
aim_activity_actor* target_ui::activity = nullptr
Definition at line 207 of file ranged.cpp.
Referenced by prompt_friendlies_in_lof(), and run().
aim_mode
std::vector<aim_type>::iterator target_ui::aim_mode private
Definition at line 259 of file ranged.cpp.
Referenced by action_aim_and_shoot(), action_switch_mode(), get_selected_aim_type(), init_window_and_input(), and run().
aim_types
std::vector<aim_type> target_ui::aim_types private
Definition at line 257 of file ranged.cpp.
Referenced by action_aim_and_shoot(), action_switch_mode(), draw_controls_list(), get_selected_aim_type(), and init_window_and_input().
ammo
const itype* target_ui::ammo = nullptr
Definition at line 193 of file ranged.cpp.
Referenced by action_switch_ammo(), action_switch_mode(), and panel_gun_info().
casting
spell* target_ui::casting = nullptr
Definition at line 201 of file ranged.cpp.
Referenced by panel_spell_info(), run(), set_cursor_pos(), and update_status().
compact
bool target_ui::compact = false private
Definition at line 291 of file ranged.cpp.
Referenced by draw_ui_window(), and init_window_and_input().
ctxt
input_context target_ui::ctxt private
Definition at line 251 of file ranged.cpp.
Referenced by draw_controls_list(), draw_help_notice(), draw_ui_window(), handle_cursor_movement(), init_window_and_input(), and run().
draw_turret_lines
bool target_ui::draw_turret_lines = false private
Definition at line 282 of file ranged.cpp.
Referenced by draw_controls_list(), draw_terrain_overlay(), and run().
dst
tripoint target_ui::dst private
Definition at line 241 of file ranged.cpp.
Referenced by action_aim(), action_aim_and_shoot(), confirm_non_enemy_target(), draw_terrain_overlay(), draw_ui_window(), handle_cursor_movement(), list_friendlies_in_lof(), panel_cursor_info(), panel_spell_info(), recalc_aim_turning_penalty(), run(), set_cursor_pos(), set_last_target(), toggle_snap_to_target(), update_status(), and update_turrets_in_range().
dst_critter
Creature* target_ui::dst_critter = nullptr private
Definition at line 244 of file ranged.cpp.
Referenced by confirm_non_enemy_target(), cycle_targets(), panel_target_info(), run(), set_cursor_pos(), and set_last_target().
mode
TargetMode target_ui::mode = TargetMode::Fire
Definition at line 187 of file ranged.cpp.
Referenced by action_switch_ammo(), action_switch_mode(), confirm_non_enemy_target(), draw_controls_list(), draw_terrain_overlay(), draw_ui_window(), init_window_and_input(), list_friendlies_in_lof(), panel_cursor_info(), prompt_friendlies_in_lof(), run(), set_cursor_pos(), uitext_fire(), uitext_title(), update_status(), and update_target_list().
narrow
bool target_ui::narrow = false private
Definition at line 296 of file ranged.cpp.
Referenced by draw_help_notice(), draw_ui_window(), and init_window_and_input().
no_fail
bool target_ui::no_fail = false
Definition at line 203 of file ranged.cpp.
Referenced by panel_spell_info().
no_mana
bool target_ui::no_mana = false
Definition at line 205 of file ranged.cpp.
Referenced by panel_spell_info(), and run().
predicted_recoil
double target_ui::predicted_recoil = 0 private
Definition at line 265 of file ranged.cpp.
Referenced by apply_aim_turning_penalty(), and recalc_aim_turning_penalty().
range
int target_ui::range = 0
Definition at line 191 of file ranged.cpp.
Referenced by action_switch_ammo(), action_switch_mode(), choose_initial_target(), panel_cursor_info(), set_cursor_pos(), try_reacquire_target(), update_status(), and update_target_list().
relevant
item* target_ui::relevant = nullptr
Definition at line 189 of file ranged.cpp.
Referenced by action_aim(), action_aim_and_shoot(), action_switch_mode(), draw_controls_list(), draw_ui_window(), init_window_and_input(), panel_gun_info(), panel_recoil(), run(), uitext_title(), and update_status().
shifting_view
bool target_ui::shifting_view = false private
Definition at line 288 of file ranged.cpp.
Referenced by draw_controls_list(), handle_cursor_movement(), run(), and toggle_snap_to_target().
sight_dispersion
int target_ui::sight_dispersion = 0 private
Definition at line 255 of file ranged.cpp.
Referenced by action_aim_and_shoot(), get_sight_dispersion(), and run().
snap_to_target
bool target_ui::snap_to_target = false private
Definition at line 285 of file ranged.cpp.
Referenced by handle_cursor_movement(), run(), set_cursor_pos(), and toggle_snap_to_target().
spell_aoe
std::set<tripoint> target_ui::spell_aoe private
Definition at line 269 of file ranged.cpp.
Referenced by confirm_non_enemy_target(), draw_terrain_overlay(), and set_cursor_pos().
src
tripoint target_ui::src private
Definition at line 238 of file ranged.cpp.
Referenced by choose_initial_target(), confirm_non_enemy_target(), dist_fn(), draw_terrain_overlay(), handle_cursor_movement(), list_friendlies_in_lof(), panel_cursor_info(), panel_spell_info(), recalc_aim_turning_penalty(), run(), set_cursor_pos(), set_view_offset(), toggle_snap_to_target(), update_status(), and update_turrets_in_range().
status
Status target_ui::status = Status::Good private
Definition at line 233 of file ranged.cpp.
Referenced by draw_controls_list(), draw_ui_window(), panel_cursor_info(), panel_gun_info(), recalc_aim_turning_penalty(), run(), set_cursor_pos(), and update_status().
targets
std::vector<Creature *> target_ui::targets private
Definition at line 246 of file ranged.cpp.
Referenced by choose_initial_target(), cycle_targets(), panel_cursor_info(), run(), and update_target_list().
tiny
bool target_ui::tiny = false private
Definition at line 293 of file ranged.cpp.
Referenced by draw_ui_window(), and init_window_and_input().
traj
std::vector<tripoint> target_ui::traj private
Definition at line 236 of file ranged.cpp.
Referenced by draw_terrain_overlay(), list_friendlies_in_lof(), run(), and set_cursor_pos().
turret
turret_data* target_ui::turret = nullptr
Definition at line 195 of file ranged.cpp.
Referenced by action_switch_ammo(), action_switch_mode(), and update_status().
turrets_in_range
std::vector<turret_with_lof> target_ui::turrets_in_range private
Definition at line 278 of file ranged.cpp.
Referenced by draw_terrain_overlay(), panel_turret_list(), update_status(), and update_turrets_in_range().
veh
vehicle* target_ui::veh = nullptr
Definition at line 199 of file ranged.cpp.
Referenced by update_turrets_in_range().
vturrets
const std::vector<vehicle_part *>* target_ui::vturrets = nullptr
Definition at line 197 of file ranged.cpp.
Referenced by panel_turret_list(), run(), and update_turrets_in_range().
w_target
catacurses::window target_ui::w_target private
Definition at line 249 of file ranged.cpp.
Referenced by draw_controls_list(), draw_help_notice(), draw_ui_window(), draw_window_title(), init_window_and_input(), panel_cursor_info(), panel_gun_info(), panel_recoil(), panel_spell_info(), panel_target_info(), panel_turret_list(), and run().
you
avatar* target_ui::you
Definition at line 185 of file ranged.cpp.
Referenced by action_aim(), action_aim_and_shoot(), action_drop_aim(), action_switch_mode(), apply_aim_turning_penalty(), choose_initial_target(), draw_controls_list(), draw_terrain_overlay(), draw_ui_window(), handle_cursor_movement(), init_window_and_input(), list_friendlies_in_lof(), on_target_accepted(), panel_recoil(), panel_spell_info(), panel_target_info(), recalc_aim_turning_penalty(), run(), set_cursor_pos(), set_last_target(), set_view_offset(), try_reacquire_target(), update_status(), and update_target_list().
The documentation for this class was generated from the following file:
src/ranged.cpp