Cataclysm DDA: behavior::tree Class Reference
behavior::tree Class Reference
#include <behavior.h>
Public Member Functions
std::string tick (const oracle_t *subject)
std::string goal () const
void add (const node_t *new_node)
Private Attributes
const node_t * root = nullptr
const node_t * active_node = nullptr
Detailed Description
Definition at line 44 of file behavior.h.
Member Function Documentation
add()
void tree::add (const node_t * new_node)
Definition at line 100 of file behavior.cpp.
 {
     root = new_node;
 }
References root.
Referenced by monster::move().
goal()
std::string tree::goal () const
Definition at line 95 of file behavior.cpp.
 {
     return active_node == nullptr ? "idle" : active_node->goal();
 }
References active_node, and behavior::node_t::goal().
Referenced by tick().
tick()
std::string tree::tick (const oracle_t * subject)
Definition at line 88 of file behavior.cpp.
 {
     behavior_return result = root->tick( subject );
     active_node = result.result == status_t::running ? result.selection : nullptr;
     return goal();
 }
References active_node, goal(), behavior::behavior_return::result, root, behavior::running, behavior::behavior_return::selection, and behavior::node_t::tick().
Referenced by monster::move().
Member Data Documentation
active_node
const node_t* behavior::tree::active_node = nullptr private
Definition at line 55 of file behavior.h.
Referenced by goal(), and tick().
root
const node_t* behavior::tree::root = nullptr private
Definition at line 54 of file behavior.h.
Referenced by add(), and tick().
The documentation for this class was generated from the following files:
src/behavior.h
src/behavior.cpp