Cataclysm DDA: profession Class Reference
profession Class Reference
#include <profession.h>
Classes
struct itypedec
Public Types
using StartingSkill = std::pair< skill_id, int >
using StartingSkillList = std::vector< StartingSkill >
using itypedecvec = std::vector< itypedec >
Public Member Functions
profession ()
void check_definition () const
Check that item/CBM/addiction/skill definitions are valid.
const string_id< profession > & ident () const
std::string gender_appropriate_name (bool male) const
std::string description (bool male) const
signed int point_cost () const
std::list< item > items (bool male, const std::vector< trait_id > &traits) const
std::vector< addiction > addictions () const
vproto_id vehicle () const
std::vector< mtype_id > pets () const
std::vector< bionic_id > CBMs () const
std::vector< proficiency_id > proficiencies () const
std::vector< recipe_id > recipes () const
std::vector< matype_id > ma_known () const
std::vector< matype_id > ma_choices () const
bool allows_hobby (const string_id< profession > &hobby) const
StartingSkillList skills () const
const std::vector< mission_type_id > & missions () const
std::optional< achievement_id > get_requirement () const
std::map< spell_id, int > spells () const
void learn_spells (avatar &you) const
profession_id get_profession_id () const
bool has_flag (const std::string &flag) const
Check if this type of profession has a certain flag set.
ret_val< void > can_afford (const Character &you, int points) const
Check if the given player can pick this job with the given amount of points.
ret_val< void > can_pick () const
Do you have the necessary achievement state.
bool is_locked_trait (const trait_id &trait) const
bool is_forbidden_trait (const trait_id &trait) const
std::vector< trait_and_var > get_locked_traits () const
std::set< trait_id > get_forbidden_traits () const
bool is_hobby () const
bool is_blacklisted () const
Static Public Member Functions
static void load_profession (const JsonObject &jo, const std::string &src)
static void load_item_substitutions (const JsonObject &jo)
static const profession * generic ()
static const std::vector< profession > & get_all ()
static std::vector< string_id< profession > > get_all_hobbies ()
static bool has_initialized ()
static void reset ()
static void check_definitions ()
calls check_definition for each profession
Public Attributes
int ma_choice_amount
int age_lower = 21
int age_upper = 55
std::vector< std::pair< string_id< profession >, mod_id > > src
Private Member Functions
void check_item_definitions (const itypedecvec &items) const
void load (const JsonObject &jo, std::string_view src)
Private Attributes
string_id< profession > id
bool was_loaded = false
translation _name_male
translation _name_female
translation _description_male
translation _description_female
signed int _point_cost = 0
itypedecvec legacy_starting_items
itypedecvec legacy_starting_items_male
itypedecvec legacy_starting_items_female
item_group_id _starting_items = item_group_id("EMPTY_GROUP")
item_group_id _starting_items_male = item_group_id("EMPTY_GROUP")
item_group_id _starting_items_female = item_group_id("EMPTY_GROUP")
itype_id no_bonus
std::optional< achievement_id > _requirement
std::vector< addiction > _starting_addictions
std::vector< bionic_id > _starting_CBMs
std::vector< proficiency_id > _starting_proficiencies
std::vector< recipe_id > _starting_recipes
std::vector< trait_and_var > _starting_traits
std::vector< matype_id > _starting_martialarts
std::vector< matype_id > _starting_martialarts_choices
std::set< trait_id > _forbidden_traits
std::vector< mtype_id > _starting_pets
std::set< string_id< profession > > _hobby_exclusion
bool hobbies_whitelist = true
vproto_id _starting_vehicle = vproto_id::NULL_ID()
std::map< spell_id, int > _starting_spells
std::set< std::string > flags
StartingSkillList _starting_skills
std::vector< mission_type_id > _missions
std::string _subtype
Friends
class string_id< profession >
class generic_factory< profession >
struct mod_tracker
Detailed Description
Definition at line 27 of file profession.h.
Member Typedef Documentation
itypedecvec
using profession::itypedecvec = std::vector<itypedec>
Definition at line 43 of file profession.h.
StartingSkill
using profession::StartingSkill = std::pair<skill_id, int>
Definition at line 30 of file profession.h.
StartingSkillList
using profession::StartingSkillList = std::vector<StartingSkill>
Definition at line 31 of file profession.h.
Constructor & Destructor Documentation
profession()
profession::profession ()
Definition at line 137 of file profession.cpp.
     : _name_male( no_translation( "null" ) ),
       _name_female( no_translation( "null" ) ),
       _description_male( no_translation( "null" ) ),
       _description_female( no_translation( "null" ) )
 {
 }
Member Function Documentation
addictions()
std::vector< addiction > profession::addictions () const
Definition at line 605 of file profession.cpp.
 {
     return _starting_addictions;
 }
References _starting_addictions.
Referenced by Character::initialize(), and set_description().
allows_hobby()
bool profession::allows_hobby (const string_id< profession > & hobby) const
Definition at line 635 of file profession.cpp.
 {
     if( hobbies_whitelist && !_hobby_exclusion.empty() ) {
         return _hobby_exclusion.count( hobby ) == 1;
     }
     return _hobby_exclusion.count( hobby ) == 0;
 }
References _hobby_exclusion, and hobbies_whitelist.
can_afford()
ret_val< void > profession::can_afford (const Character & you, int points) const
Check if the given player can pick this job with the given amount of points.
Returns
true, if player can pick profession. Otherwise - false.
Definition at line 663 of file profession.cpp.
 {
     if( point_cost() - you.prof->point_cost() <= points ) {
         return ret_val<void>::make_success();
     }
     return ret_val<void>::make_failure( _( "You don't have enough points" ) );
 }
References _, ret_val< T >::make_failure(), ret_val< T >::make_success(), point_cost(), and Character::prof.
can_pick()
ret_val< void > profession::can_pick () const
Do you have the necessary achievement state.
Definition at line 672 of file profession.cpp.
 {
     // if meta progression is disabled then skip this
     if( get_past_achievements().is_completed( achievement_achievement_arcade_mode ) ||
         !get_option<bool>( "META_PROGRESS" ) ) {
         return ret_val<void>::make_success();
     }
     if( _requirement ) {
         const bool has_req = get_past_achievements().is_completed(
                                  _requirement.value()->id );
         if( !has_req ) {
             return ret_val<void>::make_failure(
                        _( "You must complete the achievement \"%s\" to unlock this profession." ),
                        _requirement.value()->name() );
         }
     }
     return ret_val<void>::make_success();
 }
References _, _requirement, achievement_achievement_arcade_mode, get_past_achievements(), past_achievements_info::is_completed(), ret_val< T >::make_failure(), and ret_val< T >::make_success().
Referenced by scenario::weighted_random_profession().
CBMs()
std::vector< bionic_id > profession::CBMs () const
Definition at line 610 of file profession.cpp.
 {
     return _starting_CBMs;
 }
References _starting_CBMs.
Referenced by Character::initialize(), Character::set_bionics_from_hobbies(), and set_description().
check_definition()
void profession::check_definition () const
Check that item/CBM/addiction/skill definitions are valid.
Definition at line 396 of file profession.cpp.
 {
     check_item_definitions( legacy_starting_items );
     check_item_definitions( legacy_starting_items_female );
     check_item_definitions( legacy_starting_items_male );
     if( !no_bonus.is_empty() && !item::type_is_defined( no_bonus ) ) {
         debugmsg( "no_bonus item '%s' is not an itype_id", no_bonus.c_str() );
     }
     if( !item_group::group_is_defined( _starting_items ) ) {
         debugmsg( "_starting_items group is undefined" );
     }
     if( !item_group::group_is_defined( _starting_items_male ) ) {
         debugmsg( "_starting_items_male group is undefined" );
     }
     if( !item_group::group_is_defined( _starting_items_female ) ) {
         debugmsg( "_starting_items_female group is undefined" );
     }
     if( _starting_vehicle && !_starting_vehicle.is_valid() ) {
         debugmsg( "vehicle prototype %s for profession %s does not exist", _starting_vehicle.c_str(),
                   id.c_str() );
     }
     for( const auto &a : _starting_CBMs ) {
         if( !a.is_valid() ) {
             debugmsg( "bionic %s for profession %s does not exist", a.c_str(), id.c_str() );
         }
     }
     for( const proficiency_id &pid : _starting_proficiencies ) {
         if( !pid.is_valid() ) {
             debugmsg( "proficiency %s for profession %s does not exist", pid.str(), id.str() );
         }
     }
     for( const trait_and_var &t : _starting_traits ) {
         if( !t.trait.is_valid() ) {
             debugmsg( "trait %s for profession %s does not exist", t.trait.str(), id.str() );
         }
     }
     for( const auto &elem : _starting_pets ) {
         if( !elem.is_valid() ) {
             debugmsg( "starting pet %s for profession %s does not exist", elem.c_str(), id.c_str() );
         }
     }
     for( const string_id<profession> &hobby : _hobby_exclusion ) {
         if( !hobby.is_valid() ) {
             debugmsg( "hobby %s for profession %s does not exist", hobby.str(), id.str() );
         } else if( !hobby->is_hobby() ) {
             debugmsg( "hobby %s for profession %s is a profession", hobby.str(), id.str() );
         }
     }
     for( const auto &elem : _starting_skills ) {
         if( !elem.first.is_valid() ) {
             debugmsg( "skill %s for profession %s does not exist", elem.first.c_str(), id.c_str() );
         }
     }
     for( const auto &m : _missions ) {
         if( !m.is_valid() ) {
             debugmsg( "starting mission %s for profession %s does not exist", m.c_str(), id.c_str() );
         }
         if( std::find( m->origins.begin(), m->origins.end(), ORIGIN_GAME_START ) == m->origins.end() ) {
             debugmsg( "starting mission %s for profession %s must include an origin of ORIGIN_GAME_START",
                       m.c_str(), id.c_str() );
         }
     }
 }
References _hobby_exclusion, _missions, _starting_CBMs, _starting_items, _starting_items_female, _starting_items_male, _starting_pets, _starting_proficiencies, _starting_skills, _starting_traits, _starting_vehicle, a, string_id< T >::c_str(), check_item_definitions(), debugmsg, item_group::group_is_defined(), string_id< T >::is_empty(), string_id< T >::is_valid(), legacy_starting_items, legacy_starting_items_female, legacy_starting_items_male, no_bonus, ORIGIN_GAME_START, and item::type_is_defined().
check_definitions()
void profession::check_definitions () static
calls check_definition for each profession
Definition at line 367 of file profession.cpp.
 {
     item_substitutions.check_consistency();
     for( const profession &prof : all_profs.get_all() ) {
         prof.check_definition();
     }
     prof_blacklist.check_consistency();
 }
References anonymous_namespace{profession.cpp}::all_profs, json_item_substitution::check_consistency(), profession_blacklist::check_consistency(), item_substitutions, and prof_blacklist.
Referenced by DynamicDataLoader::check_consistency().
check_item_definitions()
void profession::check_item_definitions (const itypedecvec & items) const private
Definition at line 376 of file profession.cpp.
 {
     for( const profession::itypedec &itd : items ) {
         if( !item::type_is_defined( itd.type_id ) ) {
             debugmsg( "profession %s: item %s does not exist", id.str(), itd.type_id.str() );
         } else if( !itd.snip_id.is_null() ) {
             const itype *type = item::find_type( itd.type_id );
             if( type->snippet_category.empty() ) {
                 debugmsg( "profession %s: item %s has no snippet category - no description can "
                           "be set", id.str(), itd.type_id.str() );
             } else {
                 if( !itd.snip_id.is_valid() ) {
                     debugmsg( "profession %s: there's no snippet with id %s",
                               id.str(), itd.snip_id.str() );
                 }
             }
         }
     }
 }
References debugmsg, item::find_type(), items(), type, and item::type_is_defined().
Referenced by check_definition().
description()
std::string profession::description (bool male) const
Definition at line 489 of file profession.cpp.
 {
     if( male ) {
         return _description_male.translated();
     } else {
         return _description_female.translated();
     }
 }
References _description_female, _description_male, male, and translation::translated().
gender_appropriate_name()
std::string profession::gender_appropriate_name (bool male) const
Definition at line 480 of file profession.cpp.
 {
     if( male ) {
         return _name_male.translated();
     } else {
         return _name_female.translated();
     }
 }
References _name_female, _name_male, male, and translation::translated().
Referenced by draw_tip(), set_description(), set_hobbies(), and set_traits().
generic()
const profession * profession::generic () static
Definition at line 330 of file profession.cpp.
 {
     const string_id<profession> generic_profession_id(
         get_option<std::string>( "GENERIC_PROFESSION_ID" ) );
     return &generic_profession_id.obj();
 }
References string_id< T >::obj().
Referenced by Character::Character(), avatar::control_npc(), avatar::create(), stats_tracker::deserialize(), draw_tip(), tutorial_game::init(), avatar::load(), scenario::permitted_professions(), scenario::weighted_random_profession(), and memorial_logger::write_text_memorial().
get_all()
const std::vector< profession > & profession::get_all () static
Definition at line 337 of file profession.cpp.
 {
     return all_profs.get_all();
 }
References anonymous_namespace{profession.cpp}::all_profs.
Referenced by get_all_hobbies(), and scenario::permitted_professions().
get_all_hobbies()
std::vector< string_id< profession > > profession::get_all_hobbies () static
Definition at line 342 of file profession.cpp.
 {
     std::vector<profession> all = profession::get_all();
     std::vector<profession_id> ret;
     // remove all non-hobbies from list of professions
     const auto new_end = std::remove_if( all.begin(),
     all.end(), [&]( const profession & arg ) {
         return !arg.is_hobby();
     } );
     all.erase( new_end, all.end() );
     // convert to string_id's then return
     for( const profession &p : all ) {
         ret.emplace( ret.end(), p.ident() );
     }
     return ret;
 }
References om_direction::all, get_all(), and cata::hash64_detail::ret.
Referenced by scenario::permitted_hobbies(), avatar::randomize_hobbies(), and set_hobbies().
get_forbidden_traits()
std::set< trait_id > profession::get_forbidden_traits () const
Definition at line 648 of file profession.cpp.
 {
     return _forbidden_traits;
 }
References _forbidden_traits.
Referenced by scenario::scenario_traits_conflict_with_profession_traits().
get_locked_traits()
std::vector< trait_and_var > profession::get_locked_traits () const
Definition at line 643 of file profession.cpp.
 {
     return _starting_traits;
 }
References _starting_traits.
Referenced by avatar::add_random_hobby(), Character::add_traits(), scenario::scenario_traits_conflict_with_profession_traits(), and set_hobbies().
get_profession_id()
profession_id profession::get_profession_id () const
Definition at line 911 of file profession.cpp.
 {
     return id;
 }
References base_camps::id.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_u_profession().
get_requirement()
std::optional< achievement_id > profession::get_requirement () const
Definition at line 926 of file profession.cpp.
 {
     return _requirement;
 }
has_flag()
bool profession::has_flag (const std::string & flag) const
Check if this type of profession has a certain flag set.
Current flags: none
Definition at line 658 of file profession.cpp.
 {
     return flags.count( flag ) != 0;
 }
References flags.
Referenced by items().
has_initialized()
bool profession::has_initialized () static
Definition at line 465 of file profession.cpp.
 {
     if( !g || g->new_game ) {
         return false;
     }
     const string_id<profession> generic_profession_id(
         get_option<std::string>( "GENERIC_PROFESSION_ID" ) );
     return generic_profession_id.is_valid();
 }
References g, and string_id< T >::is_valid().
Referenced by Character::Character().
ident()
const string_id< profession > & profession::ident () const
Definition at line 475 of file profession.cpp.
 {
     return id;
 }
References id.
Referenced by avatar::control_npc(), stats_tracker::deserialize(), Character::migrate_items_to_storage(), set_hobbies(), game::start_game(), and scenario::weighted_random_profession().
is_blacklisted()
bool profession::is_blacklisted () const
Definition at line 129 of file profession.cpp.
 {
     if( prof_blacklist.whitelist ) {
         return prof_blacklist.professions.count( id ) == 0;
     }
     return prof_blacklist.professions.count( id ) != 0;
 }
References prof_blacklist, profession_blacklist::professions, and profession_blacklist::whitelist.
is_forbidden_trait()
bool profession::is_forbidden_trait (const trait_id & trait) const
Definition at line 702 of file profession.cpp.
 {
     return _forbidden_traits.count( trait ) != 0;
 }
References _forbidden_traits.
is_hobby()
bool profession::is_hobby () const
Definition at line 916 of file profession.cpp.
 {
     return _subtype == "hobby";
 }
Referenced by avatar::add_profession_items(), and conditional_fun::anonymous_namespace{condition.cpp}::f_u_profession().
is_locked_trait()
bool profession::is_locked_trait (const trait_id & trait) const
Definition at line 693 of file profession.cpp.
 {
     auto pred = [&trait]( const trait_and_var & query ) {
         return query.trait == trait;
     };
     return std::find_if( _starting_traits.begin(), _starting_traits.end(),
                          pred ) != _starting_traits.end();
 }
References _starting_traits.
Referenced by set_hobbies(), set_traits(), and trait_points_used().
items()
std::list< item > profession::items (bool male, const std::vector< trait_id > & traits) const
Definition at line 516 of file profession.cpp.
 {
     std::list<item> result;
     auto add_legacy_items = [&result]( const itypedecvec & vec ) {
         for( const itypedec &elem : vec ) {
             item it( elem.type_id, advanced_spawn_time(), item::default_charges_tag {} );
             if( !elem.snip_id.is_null() ) {
                 it.set_snippet( elem.snip_id );
             }
             it = it.in_its_container();
             result.push_back( it );
         }
     };
     add_legacy_items( legacy_starting_items );
     add_legacy_items( male ? legacy_starting_items_male : legacy_starting_items_female );
     std::vector<item> group_both = item_group::items_from( _starting_items,
                                    advanced_spawn_time() );
     std::vector<item> group_gender = item_group::items_from( male ? _starting_items_male :
                                      _starting_items_female, advanced_spawn_time() );
     result.insert( result.begin(), std::make_move_iterator( group_both.begin() ),
                    std::make_move_iterator( group_both.end() ) );
     result.insert( result.begin(), std::make_move_iterator( group_gender.begin() ),
                    std::make_move_iterator( group_gender.end() ) );
     if( !has_flag( "NO_BONUS_ITEMS" ) ) {
         const std::vector<item> &items = item_substitutions.get_bonus_items( traits );
         for( const item &it : items ) {
             if( it.typeId() != no_bonus ) {
                 result.push_back( it );
             }
         }
     }
     for( auto iter = result.begin(); iter != result.end(); ) {
         const std::vector<item> sub = item_substitutions.get_substitution( *iter, traits );
         if( !sub.empty() ) {
             result.insert( result.begin(), sub.begin(), sub.end() );
             iter = result.erase( iter );
         } else {
             ++iter;
         }
     }
     for( item &it : result ) {
         it.visit_items( []( item * it, item * ) {
             clear_faults( *it );
             return VisitResponse::NEXT;
         } );
         if( it.has_flag( flag_VARSIZE ) ) {
             it.set_flag( flag_FIT );
         }
     }
     if( result.empty() ) {
         // No need to do the below stuff. Plus it would cause said below stuff to crash
         return result;
     }
     // Merge charges for items that stack with each other
     for( auto outer = result.begin(); outer != result.end(); ++outer ) {
         if( !outer->count_by_charges() ) {
             continue;
         }
         for( auto inner = std::next( outer ); inner != result.end(); ) {
             if( outer->stacks_with( *inner ) ) {
                 outer->merge_charges( *inner );
                 inner = result.erase( inner );
             } else {
                 ++inner;
             }
         }
     }
     result.sort( []( const item & first, const item & second ) {
         return first.get_layer() < second.get_layer();
     } );
     return result;
 }
References _starting_items, _starting_items_female, _starting_items_male, advanced_spawn_time(), clear_faults(), flag_FIT, flag_VARSIZE, json_item_substitution::get_bonus_items(), item::get_layer(), json_item_substitution::get_substitution(), item::has_flag(), has_flag(), item_substitutions, item_group::items_from(), legacy_starting_items, legacy_starting_items_female, legacy_starting_items_male, male, item::merge_charges(), NEXT, no_bonus, second, item::set_flag(), item::set_snippet(), and math_opers::sub().
Referenced by avatar::add_profession_items(), and check_item_definitions().
learn_spells()
void profession::learn_spells (avatar & you) const
Definition at line 712 of file profession.cpp.
 {
     for( const std::pair<spell_id, int> spell_pair : spells() ) {
         you.magic->learn_spell( spell_pair.first, you, true );
         spell &sp = you.magic->get_spell( spell_pair.first );
         while( sp.get_level() < spell_pair.second && !sp.is_max_level( you ) ) {
             sp.gain_level( you );
         }
     }
 }
References spell::gain_level(), spell::get_level(), spell::is_max_level(), Character::magic, and spells().
Referenced by avatar::initialize().
load()
void profession::load (const JsonObject & jo, std::string_view src) private
Definition at line 204 of file profession.cpp.
 {
     //If the "name" is an object then we have to deal with gender-specific titles,
     if( jo.has_object( "name" ) ) {
         JsonObject name_obj = jo.get_object( "name" );
         // Specifying translation context here to avoid adding unnecessary json code for every profession
         // NOLINTNEXTLINE(cata-json-translation-input)
         _name_male = to_translation( "profession_male", name_obj.get_string( "male" ) );
         // NOLINTNEXTLINE(cata-json-translation-input)
         _name_female = to_translation( "profession_female", name_obj.get_string( "female" ) );
     } else if( jo.has_string( "name" ) ) {
         // Same profession names for male and female in English.
         // Still need to different names in other languages.
         const std::string name = jo.get_string( "name" );
         _name_female = to_translation( "profession_female", name );
         _name_male = to_translation( "profession_male", name );
     } else if( !was_loaded ) {
         jo.throw_error( "missing mandatory member \"name\"" );
     }
     if( !was_loaded || jo.has_member( "description" ) ) {
         std::string desc;
         std::string desc_male;
         std::string desc_female;
         bool use_default_description = true;
         if( jo.has_object( "description" ) ) {
             JsonObject desc_obj = jo.get_object( "description" );
             desc_obj.allow_omitted_members();
             if( desc_obj.has_member( "male" ) && desc_obj.has_member( "female" ) ) {
                 use_default_description = false;
                 mandatory( desc_obj, false, "male", desc_male, text_style_check_reader() );
                 mandatory( desc_obj, false, "female", desc_female, text_style_check_reader() );
             }
         }
         if( use_default_description ) {
             mandatory( jo, false, "description", desc, text_style_check_reader() );
             desc_male = desc;
             desc_female = desc;
         }
         // These also may differ depending on the language settings!
         _description_male = to_translation( "prof_desc_male", desc_male );
         _description_female = to_translation( "prof_desc_female", desc_female );
     }
     optional( jo, was_loaded, "age_lower", age_lower, 16 );
     optional( jo, was_loaded, "age_upper", age_upper, 55 );
     if( jo.has_string( "vehicle" ) ) {
         _starting_vehicle = vproto_id( jo.get_string( "vehicle" ) );
     }
     if( jo.has_array( "pets" ) ) {
         for( JsonObject subobj : jo.get_array( "pets" ) ) {
             int count = subobj.get_int( "amount" );
             mtype_id mon = mtype_id( subobj.get_string( "name" ) );
             for( int start = 0; start < count; ++start ) {
                 _starting_pets.push_back( mon );
             }
         }
     }
     if( jo.has_array( "spells" ) ) {
         for( JsonObject subobj : jo.get_array( "spells" ) ) {
             int level = subobj.get_int( "level" );
             spell_id sp = spell_id( subobj.get_string( "id" ) );
             _starting_spells.emplace( sp, level );
         }
     }
     mandatory( jo, was_loaded, "points", _point_cost );
     if( !was_loaded || jo.has_member( "items" ) ) {
         std::string c = "items for profession " + id.str();
         JsonObject items_obj = jo.get_object( "items" );
         if( items_obj.has_array( "both" ) ) {
             optional( items_obj, was_loaded, "both", legacy_starting_items, item_reader {} );
         }
         if( items_obj.has_object( "both" ) ) {
             _starting_items = item_group::load_item_group(
                                   items_obj.get_member( "both" ), "collection", c );
         }
         if( items_obj.has_array( "male" ) ) {
             optional( items_obj, was_loaded, "male", legacy_starting_items_male, item_reader {} );
         }
         if( items_obj.has_object( "male" ) ) {
             _starting_items_male = item_group::load_item_group(
                                        items_obj.get_member( "male" ), "collection", c );
         }
         if( items_obj.has_array( "female" ) ) {
             optional( items_obj, was_loaded, "female",  legacy_starting_items_female, item_reader {} );
         }
         if( items_obj.has_object( "female" ) ) {
             _starting_items_female = item_group::load_item_group( items_obj.get_member( "female" ),
                                      "collection", c );
         }
     }
     optional( jo, was_loaded, "no_bonus", no_bonus );
     optional( jo, was_loaded, "requirement", _requirement );
     optional( jo, was_loaded, "skills", _starting_skills, skilllevel_reader {} );
     optional( jo, was_loaded, "addictions", _starting_addictions, addiction_reader {} );
     // TODO: use string_id<bionic_type> or so
     optional( jo, was_loaded, "CBMs", _starting_CBMs, string_id_reader<::bionic_data> {} );
     optional( jo, was_loaded, "proficiencies", _starting_proficiencies );
     optional( jo, was_loaded, "recipes", _starting_recipes );
     // TODO: use string_id<mutation_branch> or so
     optional( jo, was_loaded, "traits", _starting_traits );
     optional( jo, was_loaded, "forbidden_traits", _forbidden_traits,
               string_id_reader<::mutation_branch> {} );
     optional( jo, was_loaded, "flags", flags, auto_flags_reader<> {} );
     optional( jo, was_loaded, "hobbies", _hobby_exclusion );
     optional( jo, was_loaded, "whitelist_hobbies", hobbies_whitelist, true );
     optional( jo, was_loaded, "starting_styles", _starting_martialarts );
     optional( jo, was_loaded, "starting_styles_choices", _starting_martialarts_choices );
     optional( jo, was_loaded, "starting_styles_choices_amount", ma_choice_amount, 1 );
     // Flag which denotes if a profession is a hobby
     optional( jo, was_loaded, "subtype", _subtype, "" );
     optional( jo, was_loaded, "missions", _missions, string_id_reader<::mission_type> {} );
 }
References _description_female, _description_male, _forbidden_traits, _hobby_exclusion, _missions, _name_female, _name_male, _point_cost, _requirement, _starting_addictions, _starting_CBMs, _starting_items, _starting_items_female, _starting_items_male, _starting_martialarts, _starting_martialarts_choices, _starting_pets, _starting_proficiencies, _starting_recipes, _starting_skills, _starting_spells, _starting_traits, _starting_vehicle, _subtype, age_lower, age_upper, JsonObject::allow_omitted_members(), c, flags, JsonObject::get_array(), JsonObject::get_member(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), hobbies_whitelist, legacy_starting_items, legacy_starting_items_female, legacy_starting_items_male, item_group::load_item_group(), ma_choice_amount, mandatory, mtype_id, om_direction::name(), no_bonus, optional(), spell_id, JsonObject::throw_error(), to_translation(), and was_loaded.
load_item_substitutions()
void profession::load_item_substitutions (const JsonObject & jo) static
Definition at line 725 of file profession.cpp.
 {
     item_substitutions.load( jo );
 }
References item_substitutions, and json_item_substitution::load().
Referenced by DynamicDataLoader::initialize().
load_profession()
void profession::load_profession (const JsonObject & jo, const std::string & src) static
Definition at line 145 of file profession.cpp.
 {
     all_profs.load( jo, src );
 }
References anonymous_namespace{profession.cpp}::all_profs, and src.
Referenced by DynamicDataLoader::initialize().
ma_choices()
std::vector< matype_id > profession::ma_choices () const
Definition at line 630 of file profession.cpp.
 {
     return _starting_martialarts_choices;
 }
References _starting_martialarts_choices.
Referenced by avatar::initialize().
ma_known()
std::vector< matype_id > profession::ma_known () const
Definition at line 625 of file profession.cpp.
 {
     return _starting_martialarts;
 }
References _starting_martialarts.
Referenced by avatar::initialize().
missions()
const std::vector< mission_type_id > & profession::missions () const
Definition at line 921 of file profession.cpp.
 {
     return _missions;
 }
Referenced by game::start_game().
pets()
std::vector< mtype_id > profession::pets () const
Definition at line 600 of file profession.cpp.
 {
     return _starting_pets;
 }
References _starting_pets.
Referenced by avatar::initialize().
point_cost()
signed int profession::point_cost () const
Definition at line 503 of file profession.cpp.
 {
     return _point_cost;
 }
References _point_cost.
Referenced by can_afford(), skill_points_used(), and scenario::weighted_random_profession().
proficiencies()
std::vector< proficiency_id > profession::proficiencies () const
Definition at line 615 of file profession.cpp.
 {
     return _starting_proficiencies;
 }
References _starting_proficiencies.
Referenced by Character::initialize(), set_description(), and Character::set_proficiencies_from_hobbies().
recipes()
std::vector< recipe_id > profession::recipes () const
Definition at line 620 of file profession.cpp.
 {
     return _starting_recipes;
 }
References _starting_recipes.
Referenced by Character::initialize().
reset()
void profession::reset () static
Definition at line 361 of file profession.cpp.
 {
     all_profs.reset();
     item_substitutions.reset();
 }
References anonymous_namespace{profession.cpp}::all_profs, item_substitutions, and json_item_substitution::reset().
Referenced by DynamicDataLoader::unload_data().
skills()
profession::StartingSkillList profession::skills () const
Definition at line 653 of file profession.cpp.
 {
     return _starting_skills;
 }
References _starting_skills.
Referenced by Character::initialize(), set_description(), and Character::set_skills_from_hobbies().
spells()
std::map< spell_id, int > profession::spells () const
Definition at line 707 of file profession.cpp.
 {
     return _starting_spells;
 }
References _starting_spells.
Referenced by learn_spells().
vehicle()
vproto_id profession::vehicle () const
Definition at line 595 of file profession.cpp.
 {
     return _starting_vehicle;
 }
References _starting_vehicle.
Referenced by avatar::initialize(), and set_description().
Friends And Related Function Documentation
generic_factory< profession >
friend class generic_factory< profession > friend
Definition at line 1 of file profession.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 46 of file profession.h.
string_id< profession >
friend class string_id< profession > friend
Definition at line 1 of file profession.h.
Member Data Documentation
_description_female
translation profession::_description_female private
Definition at line 55 of file profession.h.
Referenced by description(), and load().
_description_male
translation profession::_description_male private
Definition at line 54 of file profession.h.
Referenced by description(), and load().
_forbidden_traits
std::set<trait_id> profession::_forbidden_traits private
Definition at line 77 of file profession.h.
Referenced by get_forbidden_traits(), is_forbidden_trait(), and load().
_hobby_exclusion
std::set<string_id<profession> > profession::_hobby_exclusion private
Definition at line 79 of file profession.h.
Referenced by allows_hobby(), check_definition(), and load().
_missions
std::vector<mission_type_id> profession::_missions private
Definition at line 86 of file profession.h.
Referenced by check_definition(), and load().
_name_female
translation profession::_name_female private
Definition at line 53 of file profession.h.
Referenced by gender_appropriate_name(), and load().
_name_male
translation profession::_name_male private
Definition at line 52 of file profession.h.
Referenced by gender_appropriate_name(), and load().
_point_cost
signed int profession::_point_cost = 0 private
Definition at line 56 of file profession.h.
Referenced by load(), and point_cost().
_requirement
std::optional<achievement_id> profession::_requirement private
Definition at line 68 of file profession.h.
Referenced by can_pick(), and load().
_starting_addictions
std::vector<addiction> profession::_starting_addictions private
Definition at line 70 of file profession.h.
Referenced by addictions(), and load().
_starting_CBMs
std::vector<bionic_id> profession::_starting_CBMs private
Definition at line 71 of file profession.h.
Referenced by CBMs(), check_definition(), and load().
_starting_items
item_group_id profession::_starting_items = item_group_id("EMPTY_GROUP") private
Definition at line 62 of file profession.h.
Referenced by check_definition(), items(), and load().
_starting_items_female
item_group_id profession::_starting_items_female = item_group_id("EMPTY_GROUP") private
Definition at line 64 of file profession.h.
Referenced by check_definition(), items(), and load().
_starting_items_male
item_group_id profession::_starting_items_male = item_group_id("EMPTY_GROUP") private
Definition at line 63 of file profession.h.
Referenced by check_definition(), items(), and load().
_starting_martialarts
std::vector<matype_id> profession::_starting_martialarts private
Definition at line 75 of file profession.h.
Referenced by load(), and ma_known().
_starting_martialarts_choices
std::vector<matype_id> profession::_starting_martialarts_choices private
Definition at line 76 of file profession.h.
Referenced by load(), and ma_choices().
_starting_pets
std::vector<mtype_id> profession::_starting_pets private
Definition at line 78 of file profession.h.
Referenced by check_definition(), load(), and pets().
_starting_proficiencies
std::vector<proficiency_id> profession::_starting_proficiencies private
Definition at line 72 of file profession.h.
Referenced by check_definition(), load(), and proficiencies().
_starting_recipes
std::vector<recipe_id> profession::_starting_recipes private
Definition at line 73 of file profession.h.
Referenced by load(), and recipes().
_starting_skills
StartingSkillList profession::_starting_skills private
Definition at line 85 of file profession.h.
Referenced by check_definition(), load(), and skills().
_starting_spells
std::map<spell_id, int> profession::_starting_spells private
Definition at line 83 of file profession.h.
Referenced by load(), and spells().
_starting_traits
std::vector<trait_and_var> profession::_starting_traits private
Definition at line 74 of file profession.h.
Referenced by check_definition(), get_locked_traits(), is_locked_trait(), and load().
_starting_vehicle
vproto_id profession::_starting_vehicle = vproto_id::NULL_ID() private
Definition at line 81 of file profession.h.
Referenced by check_definition(), load(), and vehicle().
_subtype
std::string profession::_subtype private
Definition at line 88 of file profession.h.
Referenced by load().
age_lower
int profession::age_lower = 21
Definition at line 131 of file profession.h.
Referenced by load(), and avatar::randomize().
age_upper
int profession::age_upper = 55
Definition at line 132 of file profession.h.
Referenced by load().
flags
std::set<std::string> profession::flags private
Definition at line 84 of file profession.h.
Referenced by has_flag(), and load().
hobbies_whitelist
bool profession::hobbies_whitelist = true private
Definition at line 80 of file profession.h.
Referenced by allows_hobby(), and load().
id
string_id<profession> profession::id private
Definition at line 49 of file profession.h.
Referenced by Character::craft_proficiency_gain(), and ident().
legacy_starting_items
itypedecvec profession::legacy_starting_items private
Definition at line 59 of file profession.h.
Referenced by check_definition(), items(), and load().
legacy_starting_items_female
itypedecvec profession::legacy_starting_items_female private
Definition at line 61 of file profession.h.
Referenced by check_definition(), items(), and load().
legacy_starting_items_male
itypedecvec profession::legacy_starting_items_male private
Definition at line 60 of file profession.h.
Referenced by check_definition(), items(), and load().
ma_choice_amount
int profession::ma_choice_amount
Definition at line 128 of file profession.h.
Referenced by avatar::initialize(), and load().
no_bonus
itype_id profession::no_bonus private
Definition at line 65 of file profession.h.
Referenced by check_definition(), items(), and load().
src
std::vector<std::pair<string_id<profession>, mod_id> > profession::src
Definition at line 134 of file profession.h.
Referenced by load_profession().
was_loaded
bool profession::was_loaded = false private
Definition at line 50 of file profession.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/profession.h
src/profession.cpp