Cataclysm DDA: anatomy Class Reference
anatomy Class Reference
A structure that contains body parts.
#include <anatomy.h>
Public Member Functions
anatomy ()=default
anatomy (const anatomy &)=default
anatomy & operator= (const anatomy &)=default
anatomy (const std::vector< bodypart_id > &parts)
bodypart_id random_body_part () const
Returns a random body_part token.
bodypart_id select_body_part (int min_hit, int max_hit, bool can_attack_high, int hit_roll) const
bodypart_id select_blocking_part (const Creature *blocker, bool arm, bool leg, bool nonstandard) const
std::vector< bodypart_id > get_all_eligable_parts (int min_hit, int max_hit, bool can_attack_high) const
bodypart_id get_max_hitsize_bodypart () const
bodypart_id select_body_part_projectile_attack (double range_min, double range_max, double value) const
std::vector< bodypart_id > get_bodyparts () const
float get_size_ratio (const anatomy_id &base) const
float get_hit_size_sum () const
float get_organic_size_sum () const
float get_base_hit_size_sum (const anatomy_id &base) const
void add_body_part (const bodypart_str_id &new_bp)
void load (const JsonObject &jo, std::string_view src)
void finalize ()
void check () const
Static Public Member Functions
static void load_anatomy (const JsonObject &jo, const std::string &src)
static void reset ()
static void finalize_all ()
static void check_consistency ()
Public Attributes
anatomy_id id
std::vector< std::pair< anatomy_id, mod_id > > src
bool was_loaded = false
Private Member Functions
bodypart_str_id get_part_with_cumulative_hit_size (float size) const
Private Attributes
std::vector< bodypart_str_id > unloaded_bps
std::vector< bodypart_id > cached_bps
float size_sum = 0.0f
Sum of chances to hit a body part randomly, without aiming.
Detailed Description
A structure that contains body parts.
Keeps caches for weighted selections.
Definition at line 23 of file anatomy.h.
Constructor & Destructor Documentation
anatomy() [1/3]
anatomy::anatomy () default
anatomy() [2/3]
anatomy::anatomy (const anatomy &) default
anatomy() [3/3]
anatomy::anatomy (const std::vector< bodypart_id > & parts) explicit
Definition at line 181 of file anatomy.cpp.
 {
     for( const bodypart_id &part : parts ) {
         add_body_part( part.id() );
         unloaded_bps.push_back( part.id() );
     }
 }
References add_body_part(), and unloaded_bps.
Member Function Documentation
add_body_part()
void anatomy::add_body_part (const bodypart_str_id & new_bp)
Definition at line 189 of file anatomy.cpp.
 {
     cached_bps.emplace_back( new_bp.id() );
     const body_part_type &bp_struct = new_bp.obj();
     size_sum += bp_struct.hit_size;
 }
References cached_bps, body_part_type::hit_size, string_id< T >::id(), string_id< T >::obj(), and size_sum.
Referenced by anatomy(), and finalize().
check()
void anatomy::check () const
Definition at line 102 of file anatomy.cpp.
 {
     if( !get_part_with_cumulative_hit_size( size_sum ).is_valid() ) {
         debugmsg( "Invalid size_sum calculation for anatomy %s", id.c_str() );
     }
     std::unordered_set<bodypart_str_id> all_parts( unloaded_bps.begin(), unloaded_bps.end() );
     std::unordered_set<bodypart_str_id> root_parts;
     for( const bodypart_str_id &bp : unloaded_bps ) {
         if( !id.is_valid() ) {
             // Error already reported in finalize
             continue;
         }
         if( !all_parts.count( bp->main_part ) ) {
             debugmsg( "Anatomy %s contains part %s whose main_part %s is not part of the anatomy",
                       id.str(), bp.str(), bp->main_part.str() );
         } else if( !all_parts.count( bp->connected_to ) ) {
             debugmsg( "Anatomy %s contains part %s with connected_to part %s which is not part of "
                       "the anatomy", id.str(), bp.str(), bp->main_part.str() );
         }
         if( bp->connected_to == bp ) {
             root_parts.insert( bp );
         }
     }
     if( root_parts.size() > 1 ) {
         debugmsg( "Anatomy %s has multiple root parts: %s", id.str(),
         enumerate_as_string( root_parts.begin(), root_parts.end(), []( const bodypart_str_id & p ) {
             return p.str();
         } ) );
     }
 }
References bp, body_part_type::connected_to, debugmsg, enumerate_as_string(), get_part_with_cumulative_hit_size(), body_part_type::main_part, size_sum, string_id< T >::str(), and unloaded_bps.
check_consistency()
void anatomy::check_consistency () static
Definition at line 94 of file anatomy.cpp.
 {
     anatomy_factory.check();
     if( !anatomy_human_anatomy.is_valid() ) {
         debugmsg( "Could not load human anatomy, expect crash" );
     }
 }
References anonymous_namespace{anatomy.cpp}::anatomy_factory, anatomy_human_anatomy, debugmsg, and string_id< T >::is_valid().
Referenced by DynamicDataLoader::check_consistency().
finalize()
void anatomy::finalize ()
Definition at line 80 of file anatomy.cpp.
 {
     size_sum = 0.0f;
     cached_bps.clear();
     for( const bodypart_str_id &id : unloaded_bps ) {
         if( id.is_valid() ) {
             add_body_part( id );
         } else {
             debugmsg( "Anatomy %s has invalid body part %s", id.c_str(), id.c_str() );
         }
     }
 }
References add_body_part(), cached_bps, debugmsg, size_sum, and unloaded_bps.
Referenced by finalize_all().
finalize_all()
void anatomy::finalize_all () static
Definition at line 71 of file anatomy.cpp.
 {
     // For some weird reason, generic_factory::finalize doesn't call finalize
     anatomy_factory.finalize();
     for( const anatomy &an : anatomy_factory.get_all() ) {
         const_cast<anatomy &>( an ).finalize();
     }
 }
References anonymous_namespace{anatomy.cpp}::anatomy_factory, and finalize().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all_eligable_parts()
std::vector< bodypart_id > anatomy::get_all_eligable_parts (int min_hit, int max_hit, bool can_attack_high) const
Definition at line 330 of file anatomy.cpp.
 {
     std::vector<bodypart_id> ret;
     for( const bodypart_id &bp : cached_bps ) {
         if( ( bp->hit_size > max_hit && max_hit > 0 ) || bp->hit_size < min_hit || ( !can_attack_high &&
                 bp->has_flag( json_flag_LIMB_UPPER ) ) ) {
             continue;
         }
         ret.emplace_back( bp );
     }
     return ret;
 }
References bp, cached_bps, body_part_type::has_flag(), body_part_type::hit_size, json_flag_LIMB_UPPER, and cata::hash64_detail::ret.
Referenced by Creature::get_all_eligable_parts().
get_base_hit_size_sum()
float anatomy::get_base_hit_size_sum (const anatomy_id & base) const
Definition at line 174 of file anatomy.cpp.
 {
     add_msg_debug( debugmode::DF_ANATOMY_BP, "Base anatomy hitsize sum %.1f",
                    base->size_sum );
     return base->size_sum;
 }
References add_msg_debug, debugmode::DF_ANATOMY_BP, and size_sum.
Referenced by get_size_ratio().
get_bodyparts()
std::vector< bodypart_id > anatomy::get_bodyparts () const
Definition at line 137 of file anatomy.cpp.
 {
     return cached_bps;
 }
References cached_bps.
Referenced by Character::recalculate_bodyparts().
get_hit_size_sum()
float anatomy::get_hit_size_sum () const
Definition at line 150 of file anatomy.cpp.
 {
     float ret = 0.0f;
     for( const bodypart_id &bp : cached_bps ) {
         ret += bp->hit_size;
     }
     add_msg_debug( debugmode::DF_ANATOMY_BP, "Current anatomy hitsize sum %.1f",
                    ret );
     return ret;
 }
References add_msg_debug, bp, cached_bps, debugmode::DF_ANATOMY_BP, body_part_type::hit_size, and cata::hash64_detail::ret.
Referenced by get_size_ratio().
get_max_hitsize_bodypart()
bodypart_id anatomy::get_max_hitsize_bodypart () const
Definition at line 344 of file anatomy.cpp.
 {
     return *std::max_element( cached_bps.begin(), cached_bps.end(),
     []( const bodypart_id & lhs, const bodypart_id & rhs ) {
         return lhs->hit_size < rhs->hit_size;
     } );
 }
References cached_bps.
Referenced by Creature::get_max_hitsize_bodypart(), and select_body_part_projectile_attack().
get_organic_size_sum()
float anatomy::get_organic_size_sum () const
Definition at line 161 of file anatomy.cpp.
 {
     float ret = 0.0f;
     for( const bodypart_id &bp : cached_bps ) {
         if( !bp->has_flag( json_flag_BIONIC_LIMB ) ) {
             ret += bp->hit_size;
         }
     }
     add_msg_debug( debugmode::DF_ANATOMY_BP, "Current organic hitsize sum %.1f",
                    ret );
     return ret;
 }
References add_msg_debug, bp, cached_bps, debugmode::DF_ANATOMY_BP, body_part_type::has_flag(), body_part_type::hit_size, json_flag_BIONIC_LIMB, and cata::hash64_detail::ret.
get_part_with_cumulative_hit_size()
bodypart_str_id anatomy::get_part_with_cumulative_hit_size (float size) const private
Definition at line 197 of file anatomy.cpp.
 {
     for( const bodypart_id &part : cached_bps ) {
         size -= part->hit_size;
         if( size <= 0.0f ) {
             return part.id();
         }
     }
     return bodypart_str_id::NULL_ID();
 }
References cached_bps, string_id< body_part_type >::NULL_ID(), and om_direction::size.
Referenced by check(), and random_body_part().
get_size_ratio()
float anatomy::get_size_ratio (const anatomy_id & base) const
Definition at line 142 of file anatomy.cpp.
 {
     float ret = get_hit_size_sum() / get_base_hit_size_sum( base );
     add_msg_debug( debugmode::DF_ANATOMY_BP, "Anatomy hitsize ratio %.3f",
                    ret );
     return ret;
 }
References add_msg_debug, debugmode::DF_ANATOMY_BP, get_base_hit_size_sum(), get_hit_size_sum(), and cata::hash64_detail::ret.
Referenced by Character::get_dodge().
load()
void anatomy::load (const JsonObject & jo, std::string_view src)
Definition at line 60 of file anatomy.cpp.
 {
     mandatory( jo, was_loaded, "id", id );
     mandatory( jo, was_loaded, "parts", unloaded_bps );
 }
References mandatory, unloaded_bps, and was_loaded.
load_anatomy()
void anatomy::load_anatomy (const JsonObject & jo, const std::string & src) static
Definition at line 55 of file anatomy.cpp.
 {
     anatomy_factory.load( jo, src );
 }
References anonymous_namespace{anatomy.cpp}::anatomy_factory, and src.
Referenced by DynamicDataLoader::initialize().
operator=()
anatomy& anatomy::operator= (const anatomy &) default
random_body_part()
bodypart_id anatomy::random_body_part () const
Returns a random body_part token.
main_parts_only will limit it to arms, legs, torso, and head.
Definition at line 209 of file anatomy.cpp.
 {
     return get_part_with_cumulative_hit_size( rng_float( 0.0f, size_sum ) ).id();
 }
References get_part_with_cumulative_hit_size(), string_id< T >::id(), rng_float(), and size_sum.
Referenced by Creature::deal_melee_hit(), Creature::get_random_body_part(), and Creature::random_body_part().
reset()
void anatomy::reset () static
Definition at line 66 of file anatomy.cpp.
 {
     anatomy_factory.reset();
 }
References anonymous_namespace{anatomy.cpp}::anatomy_factory.
Referenced by DynamicDataLoader::unload_data().
select_blocking_part()
bodypart_id anatomy::select_blocking_part (const Creature * blocker, bool arm, bool leg, bool nonstandard) const
Definition at line 264 of file anatomy.cpp.
 {
     weighted_float_list<bodypart_id> block_scores;
     for( const bodypart_id &bp : cached_bps ) {
         float block_score = bp->get_limb_score( limb_score_block );
         if( const Character *u = dynamic_cast<const Character *>( blocker ) ) {
             block_score = u->get_part( bp )->get_limb_score( limb_score_block );
             // Weigh shielded bodyparts higher
             block_score *= u->worn_with_flag( flag_BLOCK_WHILE_WORN, bp ) ? 5 : 1;
         }
         // Filter out nonblocking / broken limbs
         if( block_score == 0 ) {
             add_msg_debug( debugmode::DF_MELEE, "BP %s discarded, no blocking score",
                            body_part_name( bp ) );
             continue;
         }
         // Always blocking limbs block always (if they have a block score)
         if( bp->has_flag( json_flag_ALWAYS_BLOCK ) ) {
             block_scores.add( bp, block_score );
             add_msg_debug( debugmode::DF_MELEE, "BP %s always blocks",
                            body_part_name( bp ) );
             continue;
         }
         // Can we block with our normal boring arm?
         if( bp->has_type( body_part_type::type::arm ) && !bp->has_flag( json_flag_NONSTANDARD_BLOCK ) &&
             !arm ) {
             add_msg_debug( debugmode::DF_MELEE, "BP %s discarded, no arm blocks allowed",
                            body_part_name( bp ) );
             continue;
             // Can we block with our normal boring legs?
         } else if( bp->has_type( body_part_type::type::leg ) &&
                    !bp->has_flag( json_flag_NONSTANDARD_BLOCK ) && !leg ) {
             add_msg_debug( debugmode::DF_MELEE, "BP %s discarded, no leg blocks allowed",
                            body_part_name( bp ) );
             continue;
             // Can we block with our non-normal non-arms/non-legs?
         } else if( ( ( !bp->has_type( body_part_type::type::arm ) &&
                        !bp->has_type( body_part_type::type::leg ) ) || bp->has_flag( json_flag_NONSTANDARD_BLOCK ) ) &&
                    !nonstandard ) {
             add_msg_debug( debugmode::DF_MELEE, "BP %s discarded, no nonstandard blocks allowed",
                            body_part_name( bp ) );
             continue;
         }
         block_scores.add( bp, block_score );
     }
     // Debug for seeing weights.
     for( const weighted_object<double, bodypart_id> &pr : block_scores ) {
         add_msg_debug( debugmode::DF_MELEE, "%s = %.3f", pr.obj.obj().name, pr.weight );
     }
     const bodypart_id *ret = block_scores.pick();
     if( ret == nullptr ) {
         debugmsg( "Attempted to select body part from empty anatomy %s", id.c_str() );
         return bodypart_str_id::NULL_ID().id();
     }
     add_msg_debug( debugmode::DF_MELEE, "selected part: %s", ret->id().obj().name );
     return *ret;
 }
References weighted_list< W, T >::add(), add_msg_debug, body_part_type::arm, body_part_name(), bp, cached_bps, debugmsg, debugmode::DF_MELEE, flag_BLOCK_WHILE_WORN, body_part_type::get_limb_score(), body_part_type::has_flag(), body_part_type::has_type(), string_id< T >::id(), json_flag_ALWAYS_BLOCK, json_flag_NONSTANDARD_BLOCK, body_part_type::leg, limb_score_block, string_id< body_part_type >::NULL_ID(), weighted_list< W, T >::pick(), cata::hash64_detail::ret, and u.
Referenced by Creature::select_blocking_part().
select_body_part()
bodypart_id anatomy::select_body_part (int min_hit, int max_hit, bool can_attack_high, int hit_roll) const
Definition at line 214 of file anatomy.cpp.
 {
     weighted_float_list<bodypart_id> hit_weights;
     for( const bodypart_id &bp : cached_bps ) {
         float weight = bp->hit_size;
         //Filter out too-large or too-small bodyparts
         if( weight < min_hit || ( max_hit > -1 && weight > max_hit ) ) {
             add_msg_debug( debugmode::DF_ANATOMY_BP, "BP %s discarded - hitsize %.1f( min %d max %d )",
                            body_part_name( bp ), weight, min_hit, max_hit );
             continue;
         }
         if( !can_attack_high ) {
             if( bp->has_flag( json_flag_LIMB_UPPER ) ) {
                 add_msg_debug( debugmode::DF_ANATOMY_BP, "limb %s discarded, we can't attack upper limbs",
                                body_part_name( bp ) );
                 continue;
             }
             if( bp->has_flag( json_flag_LIMB_LOWER ) ) {
                 add_msg_debug( debugmode::DF_ANATOMY_BP,
                                "limb %s's weight tripled for short attackers",
                                body_part_name( bp ) );
                 weight *= 3;
             }
         }
         if( hit_roll > 0 ) {
             weight *= std::pow( static_cast<float>( hit_roll ), bp->hit_difficulty );
         }
         hit_weights.add( bp, weight );
     }
     // Debug for seeing weights.
     for( const weighted_object<double, bodypart_id> &pr : hit_weights ) {
         add_msg_debug( debugmode::DF_ANATOMY_BP, "%s = %.3f", pr.obj.obj().name, pr.weight );
     }
     const bodypart_id *ret = hit_weights.pick();
     if( ret == nullptr ) {
         debugmsg( "Attempted to select body part from empty anatomy %s", id.c_str() );
         return bodypart_str_id::NULL_ID().id();
     }
     add_msg_debug( debugmode::DF_ANATOMY_BP, "selected part: %s", ret->id().obj().name );
     return *ret;
 }
References weighted_list< W, T >::add(), add_msg_debug, body_part_name(), bp, cached_bps, debugmsg, debugmode::DF_ANATOMY_BP, body_part_type::has_flag(), body_part_type::hit_difficulty, body_part_type::hit_size, string_id< T >::id(), json_flag_LIMB_LOWER, json_flag_LIMB_UPPER, string_id< body_part_type >::NULL_ID(), weighted_list< W, T >::pick(), and cata::hash64_detail::ret.
Referenced by Creature::select_body_part().
select_body_part_projectile_attack()
bodypart_id anatomy::select_body_part_projectile_attack (double range_min, double range_max, double value) const
Definition at line 352 of file anatomy.cpp.
 {
     const bodypart_id biggest_bp = get_max_hitsize_bodypart();
     // A little wrapper telling the targeting graph how to connect and weight bodypart_ids
     struct bp_wrapper {
         static bodypart_id connection( const bodypart_id &id ) {
             return id->connected_to.id();
         }
         static double weight( const bodypart_id &id ) {
             return id->hit_size;
         }
     };
     // Create a graph
     targeting_graph<bodypart_id, bp_wrapper> graph;
     // Fill it in with our body parts
     graph.generate( biggest_bp, cached_bps );
     // And now, select the right body part
     return graph.select( range_min, range_max, value );
 }
References cached_bps, body_part_type::connected_to, targeting_graph< T, Wrapper >::generate(), get_max_hitsize_bodypart(), body_part_type::hit_size, string_id< T >::id(), and targeting_graph< T, Wrapper >::select().
Referenced by Creature::select_body_part_projectile_attack().
Member Data Documentation
cached_bps
std::vector<bodypart_id> anatomy::cached_bps private
Definition at line 27 of file anatomy.h.
Referenced by add_body_part(), finalize(), get_all_eligable_parts(), get_bodyparts(), get_hit_size_sum(), get_max_hitsize_bodypart(), get_organic_size_sum(), get_part_with_cumulative_hit_size(), select_blocking_part(), select_body_part(), and select_body_part_projectile_attack().
id
anatomy_id anatomy::id
Definition at line 35 of file anatomy.h.
size_sum
float anatomy::size_sum = 0.0f private
Sum of chances to hit a body part randomly, without aiming.
Definition at line 29 of file anatomy.h.
Referenced by add_body_part(), check(), finalize(), get_base_hit_size_sum(), and random_body_part().
src
std::vector<std::pair<anatomy_id, mod_id> > anatomy::src
Definition at line 36 of file anatomy.h.
Referenced by load_anatomy().
unloaded_bps
std::vector<bodypart_str_id> anatomy::unloaded_bps private
Definition at line 26 of file anatomy.h.
Referenced by anatomy(), check(), finalize(), and load().
was_loaded
bool anatomy::was_loaded = false
Definition at line 37 of file anatomy.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/anatomy.h
src/anatomy.cpp