Cataclysm DDA: jmapgen_corpse Class Reference
jmapgen_corpse Class Reference
Place a corpse of a random monster from a monster group into the map.
Public Member Functions
jmapgen_corpse (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
mongroup_id group
time_duration age
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a corpse of a random monster from a monster group into the map.
"group": id of monster group to choose from "age": age (in days) of monster's corpse
Definition at line 2241 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_corpse()
jmapgen_corpse::jmapgen_corpse (const JsonObject & jsi, const std::string_view) inline
Definition at line 2246 of file mapgen.cpp.
                                                                        :
             group( jsi.get_member( "group" ) )
             , age( time_duration::from_days( jsi.get_int( "age", 0 ) ) ) {
         }
Member Function Documentation
apply()
void jmapgen_corpse::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2251 of file mapgen.cpp.
{
             const std::vector<mtype_id> monster_group =
                 MonsterGroupManager::GetMonstersFromGroup( group, true );
             const mtype_id &corpse_type = random_entry_ref( monster_group );
             item corpse = item::make_corpse( corpse_type,
                                              std::max( calendar::turn - age, calendar::start_of_cataclysm ) );
             dat.m.add_item_or_charges( tripoint( x.get(), y.get(), dat.zlevel() + z.get() ),
                                        corpse );
         }
References map::add_item_or_charges(), age, corpse, jmapgen_int::get(), MonsterGroupManager::GetMonstersFromGroup(), group, mapgendata::m, item::make_corpse(), max(), random_entry_ref(), calendar::start_of_cataclysm, tripoint, calendar::turn, and mapgendata::zlevel().
Member Data Documentation
age
time_duration jmapgen_corpse::age
Definition at line 2245 of file mapgen.cpp.
Referenced by apply().
group
mongroup_id jmapgen_corpse::group
Definition at line 2244 of file mapgen.cpp.
Referenced by apply().
The documentation for this class was generated from the following file:
src/mapgen.cpp