Cataclysm DDA: activity_data_furn Class Reference
activity_data_furn Class Reference
#include <mapdata.h>
Public Member Functions
activity_data_furn ()=default
const furn_str_id & result () const
void load (const JsonObject &jo)
Public Member Functions inherited from activity_data_common
activity_data_common ()=default
bool valid () const
const time_duration & duration () const
const translation & message () const
const translation & sound () const
const pry_data & prying_data () const
const std::vector< activity_byproduct > & byproducts () const
void load (const JsonObject &jo)
Private Attributes
furn_str_id result_
Additional Inherited Members
Public Attributes inherited from activity_data_common
bool was_loaded = false
Protected Attributes inherited from activity_data_common
bool valid_ = false
time_duration duration_
translation message_
translation sound_
struct pry_data prying_data_
std::vector< activity_byproduct > byproducts_
Detailed Description
Definition at line 435 of file mapdata.h.
Constructor & Destructor Documentation
activity_data_furn()
activity_data_furn::activity_data_furn () default
Member Function Documentation
load()
void activity_data_furn::load (const JsonObject & jo)
Definition at line 1215 of file mapdata.cpp.
 {
     optional( jo, was_loaded, "result", result_, furn_str_id::NULL_ID() );
     activity_data_common::load( jo );
     valid_ = true;
 }
References activity_data_common::load(), string_id< furn_t >::NULL_ID(), optional(), result_, activity_data_common::valid_, and activity_data_common::was_loaded.
result()
const furn_str_id& activity_data_furn::result () const inline
Definition at line 440 of file mapdata.h.
{
             return result_;
         }
References result_.
Member Data Documentation
result_
furn_str_id activity_data_furn::result_ private
Definition at line 447 of file mapdata.h.
Referenced by load(), and result().
The documentation for this class was generated from the following files:
src/mapdata.h
src/mapdata.cpp