Cataclysm DDA: tent_deconstruct_activity_actor Class Reference
tent_deconstruct_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
tent_deconstruct_activity_actor (int moves_total, int radius, tripoint target, itype_id tent)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves_total
int radius
tripoint target
itype_id tent
Detailed Description
Definition at line 1507 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
tent_deconstruct_activity_actor()
tent_deconstruct_activity_actor::tent_deconstruct_activity_actor (int moves_total, int radius, tripoint target, itype_id tent) inline
Definition at line 1516 of file activity_actor_definitions.h.
                                                          : moves_total( moves_total ), radius( radius ), target( target ), tent( tent ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> tent_deconstruct_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1527 of file activity_actor_definitions.h.
{
             return std::make_unique<tent_deconstruct_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > tent_deconstruct_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 5524 of file activity_actor.cpp.
 {
     tent_deconstruct_activity_actor actor( 0, 0, {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "moves_total", actor.moves_total );
     data.read( "radius", actor.radius );
     data.read( "target", actor.target );
     data.read( "tent", actor.tent );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void tent_deconstruct_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1524 of file activity_actor_definitions.h.
 {}
finish()
void tent_deconstruct_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 5504 of file activity_actor.cpp.
 {
     map &here = get_map();
     for( const tripoint &pt : here.points_in_radius( target, radius ) ) {
         here.furn_set( pt, furn_str_id::NULL_ID() );
     }
     here.add_item_or_charges( target, item( tent, calendar::turn ) );
     act.set_to_null();
 }
References act, map::add_item_or_charges(), map::furn_set(), get_map(), item, string_id< furn_t >::NULL_ID(), map::points_in_radius(), radius, target, tent, and calendar::turn.
get_type()
activity_id tent_deconstruct_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1519 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_TENT_DECONSTRUCT" );
         }
References activity_id.
serialize()
void tent_deconstruct_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 5514 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves_total", moves_total );
     jsout.member( "radius", radius );
     jsout.member( "target", target );
     jsout.member( "tent", tent );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves_total, radius, JsonOut::start_object(), target, and tent.
start()
void tent_deconstruct_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 5498 of file activity_actor.cpp.
 {
     act.moves_total = moves_total;
     act.moves_left = moves_total;
 }
References act, and moves_total.
Member Data Documentation
moves_total
int tent_deconstruct_activity_actor::moves_total private
Definition at line 1510 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
radius
int tent_deconstruct_activity_actor::radius private
Definition at line 1511 of file activity_actor_definitions.h.
Referenced by finish(), and serialize().
target
tripoint tent_deconstruct_activity_actor::target private
Definition at line 1512 of file activity_actor_definitions.h.
Referenced by finish(), and serialize().
tent
itype_id tent_deconstruct_activity_actor::tent private
Definition at line 1513 of file activity_actor_definitions.h.
Referenced by finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp