Cataclysm DDA: achievement::time_bound Class Reference
achievement::time_bound Class Reference
#include <achievement.h>
Public Types
enum class epoch : int { cataclysm , game_start , last }
Public Member Functions
void deserialize (const JsonObject &jo)
void check (const achievement_id &) const
time_point target () const
achievement_completion completed () const
bool becomes_false () const
std::string ui_text (bool is_conduct) const
Private Attributes
achievement_comparison comparison_ = achievement_comparison::anything
epoch epoch_ = epoch::cataclysm
time_duration period_
Detailed Description
Definition at line 94 of file achievement.h.
Member Enumeration Documentation
epoch
enum achievement::time_bound::epoch : int strong
Enumerator
cataclysm
game_start
last
Definition at line 97 of file achievement.h.
                                  : int {
                     cataclysm,
                     game_start,
                     last
                 };
Member Function Documentation
becomes_false()
bool achievement::time_bound::becomes_false () const
Definition at line 331 of file achievement.cpp.
 {
     switch( comparison_ ) {
         case achievement_comparison::equal:
             return false;
         case achievement_comparison::less_equal:
             return true;
         case achievement_comparison::greater_equal:
             return false;
         case achievement_comparison::anything:
             return true;
         case achievement_comparison::last:
             break;
     }
     cata_fatal( "Invalid achievement_comparison" );
 }
References anything, cata_fatal, equal, greater_equal, last, and less_equal.
check()
void achievement::time_bound::check (const achievement_id & id) const
Definition at line 286 of file achievement.cpp.
 {
     if( comparison_ == achievement_comparison::anything ) {
         debugmsg( "Achievement %s has unconstrained \"anything\" time_constraint.  "
                   "Please change it to a consequential comparison.", id.str() );
     }
 }
References anything, and debugmsg.
completed()
achievement_completion achievement::time_bound::completed () const
Definition at line 299 of file achievement.cpp.
 {
     time_point now = calendar::turn;
     switch( comparison_ ) {
         case achievement_comparison::equal:
             if( now == target() ) {
                 return achievement_completion::completed;
             } else if( now > target() ) {
                 return achievement_completion::failed;
             } else {
                 return achievement_completion::pending;
             }
         case achievement_comparison::less_equal:
             if( now <= target() ) {
                 return achievement_completion::completed;
             } else {
                 return achievement_completion::failed;
             }
         case achievement_comparison::greater_equal:
             if( now >= target() ) {
                 return achievement_completion::completed;
             } else {
                 return achievement_completion::pending;
             }
         case achievement_comparison::anything:
             return achievement_completion::completed;
         case achievement_comparison::last:
             break;
     }
     cata_fatal( "Invalid achievement_comparison" );
 }
References anything, cata_fatal, completed, equal, failed, greater_equal, last, less_equal, pending, and calendar::turn.
deserialize()
void achievement::time_bound::deserialize (const JsonObject & jo)
Definition at line 277 of file achievement.cpp.
 {
     if( !( jo.read( "since", epoch_ ) &&
            jo.read( "is", comparison_ ) &&
            jo.read( "target", period_ ) ) ) {
         jo.throw_error( "Mandatory field missing for achievement time_constraint" );
     }
 }
References comparison_, epoch_, period_, JsonObject::read(), and JsonObject::throw_error().
target()
time_point achievement::time_bound::target () const
Definition at line 294 of file achievement.cpp.
 {
     return epoch_to_time_point( epoch_ ) + period_;
 }
References epoch_to_time_point().
ui_text()
std::string achievement::time_bound::ui_text (bool is_conduct) const
Definition at line 348 of file achievement.cpp.
 {
     time_point now = calendar::turn;
     achievement_completion comp = completed();
     nc_color c = color_from_completion( is_conduct, comp, false );
     auto translate_epoch = []( epoch e ) {
         switch( e ) {
             case epoch::cataclysm:
                 return _( "time of cataclysm" );
             case epoch::game_start:
                 return _( "start of game" );
             case epoch::last:
                 break;
         }
         cata_fatal( "Invalid epoch" );
     };
     std::string message = [&]() {
         switch( comp ) {
             case achievement_completion::pending:
                 return string_format( _( "At least %s from %s (%s remaining)" ),
                                       to_string( period_ ), translate_epoch( epoch_ ),
                                       to_string( target() - now ) );
             case achievement_completion::completed:
                 switch( comparison_ ) {
                     case achievement_comparison::equal:
                         return string_format( _( "Exactly %s from %s" ),
                                               to_string( period_ ), translate_epoch( epoch_ ) );
                     case achievement_comparison::less_equal:
                         return string_format( _( "Within %s of %s (%s remaining)" ),
                                               to_string( period_ ), translate_epoch( epoch_ ),
                                               to_string( target() - now ) );
                     case achievement_comparison::greater_equal:
                         return string_format( _( "At least %s from %s (passed)" ),
                                               to_string( period_ ), translate_epoch( epoch_ ) );
                     case achievement_comparison::anything:
                         return std::string();
                     case achievement_comparison::last:
                         break;
                 }
                 cata_fatal( "Invalid achievement_comparison" );
             case achievement_completion::failed:
                 return string_format( _( "Within %s of %s (passed)" ),
                                       to_string( period_ ), translate_epoch( epoch_ ) );
             case achievement_completion::last:
                 break;
         }
         cata_fatal( "Invalid achievement_completion" );
     }
     ();
     return colorize( message, c );
 }
References _, anything, c, cata_fatal, color_from_completion(), colorize(), completed, equal, failed, greater_equal, achievement::is_conduct(), last, less_equal, mapgen_defer::message, pending, string_format(), to_string(), and calendar::turn.
Member Data Documentation
comparison_
achievement_comparison achievement::time_bound::comparison_ = achievement_comparison::anything private
Definition at line 111 of file achievement.h.
Referenced by deserialize().
epoch_
epoch achievement::time_bound::epoch_ = epoch::cataclysm private
Definition at line 112 of file achievement.h.
Referenced by deserialize().
period_
time_duration achievement::time_bound::period_ private
Definition at line 113 of file achievement.h.
Referenced by deserialize().
The documentation for this class was generated from the following files:
src/achievement.h
src/achievement.cpp