Cataclysm DDA: activatable_inventory_preset Class Reference
activatable_inventory_preset Class Reference
Public Member Functions
activatable_inventory_preset (const Character &you)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from pickup_inventory_preset
pickup_inventory_preset (const Character &you, bool skip_wield_check=false, bool ignore_liquidcont=false)
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Protected Member Functions
std::string get_action_name (const item &it) const
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Private Attributes
const Character & you
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 1074 of file game_inventory.cpp.
Constructor & Destructor Documentation
activatable_inventory_preset()
activatable_inventory_preset::activatable_inventory_preset (const Character & you) inline explicit
Definition at line 1077 of file game_inventory.cpp.
                                                                       : pickup_inventory_preset( you ),
             you( you ) {
             _collate_entries = true;
             if( get_option<bool>( "INV_USE_ACTION_NAMES" ) ) {
                 append_cell( [ this ]( const item_location & loc ) {
                     return string_format( "<color_light_green>%s</color>", get_action_name( *loc ) );
                 }, _( "ACTION" ) );
             }
         }
References _, inventory_selector_preset::_collate_entries, inventory_selector_preset::append_cell(), get_action_name(), and string_format().
Member Function Documentation
get_action_name()
std::string activatable_inventory_preset::get_action_name (const item & it) const inline protected
Definition at line 1161 of file game_inventory.cpp.
{
             const auto &uses = it.type->use_methods;
             if( uses.size() == 1 ) {
                 return uses.begin()->second.get_name();
             } else if( uses.size() == 2 ) {
                 return string_format( _( "%1$s</color> <color_dark_gray>or</color> <color_light_green>%2$s" ),
                                       uses.begin()->second.get_name(), std::next( uses.begin() )->second.get_name() );
             } else if( uses.size() > 2 ) {
                 return _( "…" );
             }
             return std::string();
         }
References _, string_format(), item::type, and itype::use_methods.
Referenced by activatable_inventory_preset().
get_denial()
std::string activatable_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from pickup_inventory_preset.
Definition at line 1091 of file game_inventory.cpp.
{
             const item &it = *loc;
             const auto &uses = it.type->use_methods;
             const auto &comest = it.get_comestible();
             if( comest && !comest->tool.is_null() ) {
                 const bool has = item::count_by_charges( comest->tool )
                                  ? you.has_charges( comest->tool, 1 )
                                  : you.has_amount( comest->tool, 1 );
                 if( !has ) {
                     return string_format( _( "You need a %s to consume that!" ), item::nname( comest->tool ) );
                 }
             }
             const use_function *consume_drug = it.type->get_use( "consume_drug" );
             if( consume_drug != nullptr ) { //its a drug)
                 const consume_drug_iuse *consume_drug_use = dynamic_cast<const consume_drug_iuse *>
                         ( consume_drug->get_actor_ptr() );
                 for( const auto &tool : consume_drug_use->tools_needed ) {
                     const bool has = item::count_by_charges( tool.first )
                                      ? you.has_charges( tool.first, ( tool.second == -1 ) ? 1 : tool.second )
                                      : you.has_amount( tool.first, 1 );
                     if( !has ) {
                         return string_format( _( "You need a %s to consume that!" ), item::nname( tool.first ) );
                     }
                 }
             }
             const use_function *smoking = it.type->get_use( "SMOKING" );
             if( smoking != nullptr ) {
                 std::optional<std::string> litcig = iuse::can_smoke( you );
                 if( litcig.has_value() ) {
                     return _( litcig.value_or( "" ) );
                 }
             }
             if( uses.size() == 1 ) {
                 const auto ret = uses.begin()->second.can_call( you, it, you.pos() );
                 if( !ret.success() ) {
                     return trim_trailing_punctuations( ret.str() );
                 }
             }
             if( it.is_medication() && !you.can_use_heal_item( it ) && !it.is_craft() ) {
                 return _( "Your biology is not compatible with that item." );
             }
             if( it.is_broken() ) {
                 return string_format( _( "Your %s was broken and won't turn on." ), it.tname() );
             }
             if( uses.size() == 1 &&
                 !it.ammo_sufficient( &you, uses.begin()->first ) ) {
                 return string_format(
                            n_gettext( "Needs at least %d charge",
                                       "Needs at least %d charges", loc->ammo_required() ),
                            loc->ammo_required() );
             }
             if( it.is_frozen_liquid() && it.is_comestible() ) {
                 return _( "You can't consume frozen liquids!" );
             }
             if( !it.has_flag( flag_ALLOWS_REMOTE_USE ) ) {
                 return pickup_inventory_preset::get_denial( loc );
             }
             return std::string();
         }
References _, item::ammo_required(), item::ammo_sufficient(), iuse::can_smoke(), Character::can_use_heal_item(), item::count_by_charges(), flag_ALLOWS_REMOTE_USE, use_function::get_actor_ptr(), item::get_comestible(), pickup_inventory_preset::get_denial(), itype::get_use(), visitable::has_amount(), Character::has_charges(), item::has_flag(), item::is_broken(), item::is_comestible(), item::is_craft(), item::is_frozen_liquid(), item::is_medication(), n_gettext, item::nname(), Creature::pos(), cata::hash64_detail::ret, iuse::smoking(), string_format(), item::tname(), consume_drug_iuse::tools_needed, trim_trailing_punctuations(), item::type, itype::use_methods, and you.
is_shown()
bool activatable_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from pickup_inventory_preset.
Definition at line 1087 of file game_inventory.cpp.
{
             return loc->type->has_use() || loc->has_relic_activation();
         }
References item::has_relic_activation(), itype::has_use(), and item::type.
Member Data Documentation
you
const Character& activatable_inventory_preset::you private
Definition at line 1177 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp