Cataclysm DDA: item::reload_option Class Reference
item::reload_option Class Reference
#include <item.h>
Public Member Functions
reload_option ()=default
reload_option (const reload_option &)
reload_option & operator= (const reload_option &)
reload_option (const Character *who, const item_location &target, const item_location &ammo)
int qty () const
void qty (int val)
int moves () const
operator bool () const
Public Attributes
const Character * who = nullptr
item_location target
item_location ammo
Private Attributes
int qty_ = 0
int max_qty = INT_MAX
Detailed Description
Definition at line 550 of file item.h.
Constructor & Destructor Documentation
reload_option() [1/3]
item::reload_option::reload_option () default
reload_option() [2/3]
item::reload_option::reload_option (const reload_option &) default
reload_option() [3/3]
item::reload_option::reload_option (const Character * who, const item_location & target, const item_location & ammo)
Definition at line 11522 of file item.cpp.
                                                                 :
     who( who ), target( target ), ammo( ammo )
 {
     if( this->target->is_ammo_belt() && this->target->type->magazine->linkage ) {
         max_qty = this->who->charges_of( * this->target->type->magazine->linkage );
     }
     qty( max_qty );
 }
References Character::charges_of(), item::is_ammo_belt(), itype::magazine, max_qty, qty(), and item::type.
Member Function Documentation
moves()
int item::reload_option::moves () const
Definition at line 11532 of file item.cpp.
 {
     int mv = ammo.obtain_cost( *who, qty() ) + who->item_reload_cost( *target, *ammo, qty() );
     if( target.has_parent() ) {
         item_location parent = target.parent_item();
         if( parent->is_gun() && !target->is_gunmod() ) {
             mv += parent->get_reload_time() * 1.5;
         } else if( parent->is_tool() ) {
             mv += 100;
         }
     }
     return mv;
 }
References item::get_reload_time(), item::is_gun(), item::is_tool(), and item_location::parent_item().
Referenced by aim_activity_actor::load_RAS_weapon(), and npc::select_ammo().
operator bool()
item::reload_option::operator bool () const inline explicit
Definition at line 571 of file item.h.
{
                     return who && target && ammo && qty_ > 0;
                 }
operator=()
item::reload_option & item::reload_option::operator= (const reload_option &) default
qty() [1/2]
int item::reload_option::qty () const inline
Definition at line 564 of file item.h.
{
                     return qty_;
                 }
Referenced by ammo_inventory_selector::mod_chosen_count(), reload_furniture(), reload_option(), game_menus::inv::select_ammo(), and ammo_inventory_selector::set_all_entries_chosen_count().
qty() [2/2]
void item::reload_option::qty (int val)
Definition at line 11546 of file item.cpp.
 {
     bool ammo_in_container = ammo->is_ammo_container();
     bool ammo_in_liquid_container = ammo->is_watertight_container();
     item &ammo_obj = ( ammo_in_container || ammo_in_liquid_container ) ?
                      // this is probably not the right way to do this. there is no guarantee whatsoever that ammo_obj will be an ammo
                      *ammo->contents.all_items_top( pocket_type::CONTAINER ).front() : *ammo;
     if( ( ammo_in_container && !ammo_obj.is_ammo() ) ||
         ( ammo_in_liquid_container && !ammo_obj.made_of( phase_id::LIQUID ) ) ) {
         debugmsg( "Invalid reload option: %s", ammo_obj.tname() );
         return;
     }
     // Checking ammo capacity implicitly limits guns with removable magazines to capacity 0.
     // This gets rounded up to 1 later.
     int remaining_capacity = target->is_watertight_container() ?
                              target->get_remaining_capacity_for_liquid( ammo_obj, true ) :
                              target->remaining_ammo_capacity();
     if( target->has_flag( flag_RELOAD_ONE ) &&
         !( ammo->has_flag( flag_SPEEDLOADER ) || ammo->has_flag( flag_SPEEDLOADER_CLIP ) ) ) {
         remaining_capacity = 1;
     }
     if( ammo_obj.type->ammo ) {
         if( ammo_obj.ammo_type() == ammo_plutonium ) {
             remaining_capacity = remaining_capacity / PLUTONIUM_CHARGES +
                                  ( remaining_capacity % PLUTONIUM_CHARGES != 0 );
         }
     }
     bool ammo_by_charges = ammo_obj.is_ammo() || ammo_in_liquid_container;
     int available_ammo;
     if( ammo->has_flag( flag_SPEEDLOADER ) || ammo->has_flag( flag_SPEEDLOADER_CLIP ) ) {
         available_ammo = ammo_obj.ammo_remaining();
     } else {
         available_ammo = ammo_by_charges ? ammo_obj.charges : ammo_obj.count();
     }
     // constrain by available ammo, target capacity and other external factors (max_qty)
     // @ref max_qty is currently set when reloading ammo belts and limits to available linkages
     qty_ = std::min( { val, available_ammo, remaining_capacity, max_qty } );
     // always expect to reload at least one charge
     qty_ = std::max( qty_, 1 );
 }
References item_contents::all_items_top(), itype::ammo, ammo_plutonium, item::ammo_remaining(), item::ammo_type(), item::charges, CONTAINER, item::contents, item::count(), debugmsg, flag_RELOAD_ONE, flag_SPEEDLOADER, flag_SPEEDLOADER_CLIP, item::is_ammo(), LIQUID, item::made_of(), max(), min(), PLUTONIUM_CHARGES, item::tname(), and item::type.
Member Data Documentation
ammo
item_location item::reload_option::ammo
Definition at line 562 of file item.h.
Referenced by game::do_regular_action(), npc::do_reload(), favorite_ammo_or_select(), npc::find_reloadable(), npc::find_usable_ammo(), aim_activity_actor::load_RAS_weapon(), game::reload(), reload_furniture(), and npc::select_ammo().
max_qty
int item::reload_option::max_qty = INT_MAX private
Definition at line 576 of file item.h.
Referenced by reload_option().
qty_
int item::reload_option::qty_ = 0 private
Definition at line 575 of file item.h.
target
item_location item::reload_option::target
Definition at line 561 of file item.h.
Referenced by npc::do_reload().
who
const Character* item::reload_option::who = nullptr
Definition at line 560 of file item.h.
The documentation for this class was generated from the following files:
src/item.h
src/item.cpp