Cataclysm DDA: multiline_list Class Reference
multiline_list Class Reference
A class for handling and displaying lists of folded text Handles folding of text, figuring out what text to display in the window, printing, and standardized navigation.
#include <output.h>
Public Member Functions
multiline_list (catacurses::window &win)
void activate_entry (size_t entry_pos, bool exclusive)
template<typename T >
void create_entries (const std::vector< T > &entry_data)
void fold_entries ()
int get_entry_pos () const
int get_offset_pos () const
int get_entry_from_offset ()
int get_entry_from_offset (int offset)
int get_offset_from_entry ()
int get_offset_from_entry (int entry)
bool handle_navigation (std::string &action, input_context &ctxt)
void print_entries ()
void set_entry_pos (int entry_pos, bool looping)
void set_offset_pos (int offset_pos, bool update_selection)
void set_up_navigation (input_context &ctxt)
Private Member Functions
void add_entry (const multiline_list_entry &entry)
void create_entry_prep ()
void print_line (int entry, const point &start, const std::string &text)
Private Attributes
bool has_prefix
int entry_position
int offset_position
int mouseover_position
std::chrono::time_point< std::chrono::steady_clock > mouseover_delay_end
size_t mouseover_accel_counter = 1
std::vector< multiline_list_entry > entries
std::vector< int > entry_sizes
int total_length
std::map< size_t, inclusive_rectangle< point > > entry_map
std::unique_ptr< scrollbar > list_sb
catacurses::window & w
Detailed Description
A class for handling and displaying lists of folded text Handles folding of text, figuring out what text to display in the window, printing, and standardized navigation.
Basic usage:
Create a multiline_list(w) where the window w is only used for this list
Call create_entries() with the list data, ensuring that get_entry() is defined in the data class
Call set_up_navigation() with the local input_context to ensure all required actions are registered
Call print_entries() to display all of the folded text that fits and a scrollbar in the window
Call handle_navigation() to handle scrolling and selection of the text, including arrow keys, page up/down, home/end, mousewheel scrolling, scrolling based on mouse position, and click-and-drag of the scrollbar
Call fold_entries() when the window is resized See dialogue_win.cpp for example usage
Definition at line 952 of file output.h.
Constructor & Destructor Documentation
multiline_list()
multiline_list::multiline_list (catacurses::window & win) inline explicit
Definition at line 973 of file output.h.
                                                          : w( win ) {
             list_sb = std::make_unique<scrollbar>();
         }
References list_sb.
Member Function Documentation
activate_entry()
void multiline_list::activate_entry (size_t entry_pos, bool exclusive)
Definition at line 1867 of file output.cpp.
 {
     if( entry_pos >= entries.size() ) {
         debugmsg( "Unable to activate entry %d of %d", entry_pos, entries.size() );
         return;
     }
     const bool cur_value = entries[entry_pos].active;
     if( exclusive ) {
         for( multiline_list_entry &entry : entries ) {
             entry.active = false;
         }
     }
     entries[entry_pos].active = exclusive ? true : !cur_value;
 }
References debugmsg, and entries.
add_entry()
void multiline_list::add_entry (const multiline_list_entry & entry) private
Definition at line 1885 of file output.cpp.
 {
     entries.emplace_back( entry );
     if( !has_prefix || entry.prefix.empty() ) {
         entries.back().prefix.clear();
         has_prefix = false;
     }
 }
References entries, has_prefix, and multiline_list_entry::prefix.
Referenced by create_entries().
create_entries()
template<typename T > void multiline_list::create_entries (const std::vector< T > & entry_data) inline
Definition at line 979 of file output.h.
{
             create_entry_prep();
             for( const T &entry : entry_data ) {
                 add_entry( entry.get_entry() );
             }
             fold_entries();
         }
References add_entry(), create_entry_prep(), and fold_entries().
create_entry_prep()
void multiline_list::create_entry_prep () private
Definition at line 1894 of file output.cpp.
 {
     entries.clear();
     has_prefix = true;
 }
References entries, and has_prefix.
Referenced by create_entries().
fold_entries()
void multiline_list::fold_entries ()
Definition at line 1900 of file output.cpp.
 {
     int available_width = getmaxx( w ) - 2; // Border/scrollbar allowance
     entry_sizes.clear();
     total_length = 0;
     std::vector<std::string> folded;
     for( multiline_list_entry &entry : entries ) {
         entry.folded_text.clear();
         if( has_prefix ) {
             // Do a prefixed list (e.g. starting with a hotkey )
             const int prefix_width = utf8_width( entry.prefix, true );
             const int fold_width = available_width - prefix_width;
             folded = foldstring( entry.entry_text, fold_width );
             for( size_t j = 0; j < folded.size(); ++j ) {
                 if( j == 0 ) {
                     entry.folded_text.emplace_back( entry.prefix + folded[j] );
                 } else {
                     entry.folded_text.emplace_back( std::string( prefix_width, ' ' ).append( folded[j] ) );
                 }
             }
         } else {
             folded = foldstring( entry.entry_text, available_width );
             for( const std::string &line : folded ) {
                 entry.folded_text.emplace_back( line );
             }
         }
         entry_sizes.emplace_back( static_cast<int>( folded.size() ) );
         total_length += folded.size();
     }
     if( !entries.empty() ) {
         // Reset entry position at end, because the resulting offset depends on entry sizes
         set_entry_pos( 0, false );
     }
 }
References entries, entry_sizes, foldstring(), catacurses::getmaxx(), has_prefix, line, set_entry_pos(), total_length, utf8_width(), and w.
Referenced by create_entries().
get_entry_from_offset() [1/2]
int multiline_list::get_entry_from_offset ()
Definition at line 1936 of file output.cpp.
 {
     return get_entry_from_offset( offset_position );
 }
References offset_position.
Referenced by set_offset_pos().
get_entry_from_offset() [2/2]
int multiline_list::get_entry_from_offset (int offset)
Definition at line 1941 of file output.cpp.
 {
     int offset_for_entry = 0;
     for( int i = 0; i < static_cast<int>( entry_sizes.size() ); ++i ) {
         /* If the last entry we scroll past before the end of the list is multiple lines,
          * we need to be able to jump past it.  So, if it's a single-line entry, we can
          * return it.  Otherwise, skip past it and return the next one
          */
         if( offset_for_entry + 1 > offset ) {
             return i;
         }
         offset_for_entry += entry_sizes[i];
         if( offset_for_entry > offset ) {
             return i + 1;
         }
     }
     return static_cast<int>( entry_sizes.size() ) - 1;
 }
References entry_sizes.
get_entry_pos()
int multiline_list::get_entry_pos () const inline
Definition at line 988 of file output.h.
{
             return entry_position;
         }
References entry_position.
get_offset_from_entry() [1/2]
int multiline_list::get_offset_from_entry ()
Definition at line 1960 of file output.cpp.
 {
     return get_offset_from_entry( entry_position );
 }
References entry_position.
Referenced by handle_navigation(), set_entry_pos(), and set_offset_pos().
get_offset_from_entry() [2/2]
int multiline_list::get_offset_from_entry (int entry)
Definition at line 1965 of file output.cpp.
 {
     int target_entry = clamp( entry, 0, static_cast<int>( entry_sizes.size() ) );
     int offset = 0;
     for( int i = 0; i < target_entry; ++i ) {
         offset += entry_sizes[i];
     }
     return offset;
 }
References clamp(), and entry_sizes.
get_offset_pos()
int multiline_list::get_offset_pos () const inline
Definition at line 991 of file output.h.
{
             return offset_position;
         }
References offset_position.
handle_navigation()
bool multiline_list::handle_navigation (std::string & action, input_context & ctxt)
Definition at line 1975 of file output.cpp.
 {
     std::optional<point> coord = ctxt.get_coordinates_text( catacurses::stdscr );
     inclusive_rectangle<point> mouseover_area( point( catacurses::getbegx( w ),
             catacurses::getbegy( w ) ), point( getmaxx( w ) + catacurses::getbegx( w ),
                     getmaxy( w ) + catacurses::getbegy( w ) ) );
     bool mouse_in_window = coord.has_value() && mouseover_area.contains( coord.value() );
     mouseover_position = -1;
     std::optional<point> local_coord = ctxt.get_coordinates_text( w );
     if( local_coord.has_value() ) {
         for( const auto &entry : entry_map ) {
             if( entry.second.contains( local_coord.value() ) ) {
                 mouseover_position = entry.first;
                 break;
             }
         }
     }
     if( list_sb->handle_dragging( action, coord, offset_position ) ) {
         // No action required
     } else if( action == "HOME" ) {
         set_entry_pos( 0, false );
     } else if( action == "END" ) {
         set_entry_pos( entries.size() - 1, false );
     } else if( action == "PAGE_DOWN" ) {
         set_offset_pos( offset_position + getmaxy( w ), true );
     } else if( action == "PAGE_UP" ) {
         set_offset_pos( offset_position - getmaxy( w ), true );
     } else if( action == "UP" ) {
         set_entry_pos( entry_position - 1, true );
     } else if( action == "DOWN" ) {
         set_entry_pos( entry_position + 1, true );
     } else if( action == "SCROLL_UP" && mouse_in_window ) {
         // Scroll selection, but only adjust view as if we're scrolling offset
         set_entry_pos( entry_position - 1, false );
         set_offset_pos( get_offset_from_entry( entry_position ), false );
         mouseover_delay_end = std::chrono::steady_clock::now() + scrollwheel_delay;
     } else if( action == "SCROLL_DOWN" && mouse_in_window ) {
         set_entry_pos( entry_position + 1, false );
         set_offset_pos( get_offset_from_entry( entry_position ), false );
         mouseover_delay_end = std::chrono::steady_clock::now() + scrollwheel_delay;
     } else if( action == "SELECT" && mouse_in_window ) {
         if( mouseover_position >= 0 ) {
             set_entry_pos( mouseover_position, false );
             action = "CONFIRM";
             mouseover_delay_end = std::chrono::steady_clock::now() + base_mouse_delay;
         }
     } else if( action == "MOUSE_MOVE" && mouse_in_window && local_coord.has_value() ) {
         if( std::chrono::steady_clock::now() > mouseover_delay_end ) {
             if( mouseover_position >= 0 ) {
                 entry_position = mouseover_position;
             }
             const int mouse_scroll_up_pos = 0;
             const int mouse_scroll_down_pos = getmaxy( w ) - 1;
             if( local_coord.value().y <= mouse_scroll_up_pos ) {
                 set_offset_pos( offset_position - 1, false );
                 ++mouseover_accel_counter;
             } else if( local_coord.value().y >= mouse_scroll_down_pos ) {
                 set_offset_pos( offset_position + 1, false );
                 ++mouseover_accel_counter;
             } else {
                 mouseover_accel_counter = 1;
             }
         }
     } else {
         return false;
     }
     return true;
 }
References action, base_mouse_delay, inclusive_rectangle< Point, >::contains(), entries, entry_map, entry_position, input_context::get_coordinates_text(), get_offset_from_entry(), catacurses::getbegx(), catacurses::getbegy(), catacurses::getmaxx(), catacurses::getmaxy(), list_sb, mouse_in_window(), mouseover_accel_counter, mouseover_delay_end, mouseover_position, offset_position, point, scrollwheel_delay, set_entry_pos(), set_offset_pos(), catacurses::stdscr, and w.
print_entries()
void multiline_list::print_entries ()
Definition at line 2046 of file output.cpp.
 {
     werase( w );
     entry_map.clear();
     int ycurrent = 0;
     int current_offset = 0;
     int available_height = getmaxy( w );
     for( size_t i = 0; i < entries.size(); ++i ) {
         for( size_t j = 0; j < entries[i].folded_text.size(); ++j ) {
             if( current_offset >= offset_position && current_offset < offset_position + available_height ) {
                 print_line( i, point( 2, ycurrent ), entries[i].folded_text[j] );
                 ++ycurrent;
             }
             ++current_offset;
         }
     }
     list_sb->offset_x( 0 )
     .offset_y( 0 )
     .content_size( total_length )
     .viewport_pos( offset_position )
     .viewport_size( getmaxy( w ) )
     .apply( w );
     wnoutrefresh( w );
 }
References entries, entry_map, catacurses::getmaxy(), list_sb, offset_position, point, print_line(), total_length, w, catacurses::werase(), and catacurses::wnoutrefresh().
print_line()
void multiline_list::print_line (int entry, const point & start, const std::string & text) private
Definition at line 2074 of file output.cpp.
 {
     nc_color cur_color = c_light_gray;
     std::string output_text = text;
     if( entries[entry].active ) {
         cur_color = c_light_green;
         output_text = colorize( remove_color_tags( output_text ), cur_color );
     }
     if( entry == entry_position ) {
         output_text = hilite_string( output_text );
     }
     print_colored_text( w, start, cur_color, c_light_gray, output_text );
     entry_map.emplace( entry, inclusive_rectangle<point>( start, point( start.x +
                        utf8_width( text, true ), start.y + entry_sizes[entry] - 1 ) ) );
 }
References active, c_light_gray, c_light_green, colorize(), entries, entry_map, entry_position, entry_sizes, hilite_string(), point, print_colored_text(), remove_color_tags(), utf8_width(), w, point::x, and point::y.
Referenced by print_entries().
set_entry_pos()
void multiline_list::set_entry_pos (int entry_pos, bool looping = false)
Definition at line 2090 of file output.cpp.
 {
     if( looping && !entries.empty() ) {
         int new_position = entry_pos;
         const int list_size = static_cast<int>( entries.size() );
         if( new_position < 0 ) {
             // Ensure we have a positive position index by adding a multiple of the list_size to it
             new_position += list_size * ( ( std::abs( new_position ) / list_size ) + 1 );
         }
         entry_position = new_position % static_cast<int>( entries.size() );
     } else {
         entry_position = clamp( entry_pos, 0, static_cast<int>( entries.size() ) - 1 );
     }
     int available_space = getmaxy( w ) - entry_sizes[entry_position];
     set_offset_pos( get_offset_from_entry() - available_space / 2, false );
     mouseover_delay_end = std::chrono::steady_clock::now() + base_mouse_delay / mouseover_accel_counter;
 }
References abs(), base_mouse_delay, clamp(), entries, entry_position, entry_sizes, get_offset_from_entry(), catacurses::getmaxy(), mouseover_accel_counter, mouseover_delay_end, set_offset_pos(), and w.
Referenced by fold_entries(), handle_navigation(), and set_offset_pos().
set_offset_pos()
void multiline_list::set_offset_pos (int offset_pos, bool update_selection)
Definition at line 2108 of file output.cpp.
 {
     // Ensure offset is above 0 and below the maximum
     const int max_offset = total_length - getmaxy( w );
     if( max_offset <= 0 ) {
         // Can't scroll offset, so just scroll entry
         offset_position = 0;
         if( update_selection ) {
             if( offset_pos > offset_position ) {
                 set_entry_pos( entry_position + 5, false );
             } else {
                 set_entry_pos( entry_position - 5, false );
             }
         }
     } else {
         if( update_selection ) {
             entry_position = get_entry_from_offset( clamp( offset_pos, 0, total_length ) );
             // The offset position might be slightly offset from the actual offset from that entry, so adjust
             set_offset_pos( get_offset_from_entry(), false );
         } else {
             offset_position = clamp( offset_pos, 0, max_offset );
         }
     }
     mouseover_delay_end = std::chrono::steady_clock::now() + base_mouse_delay / mouseover_accel_counter;
 }
References base_mouse_delay, clamp(), entry_position, get_entry_from_offset(), get_offset_from_entry(), catacurses::getmaxy(), mouseover_accel_counter, mouseover_delay_end, offset_position, set_entry_pos(), total_length, and w.
Referenced by handle_navigation(), and set_entry_pos().
set_up_navigation()
void multiline_list::set_up_navigation (input_context & ctxt)
Definition at line 2134 of file output.cpp.
 {
     list_sb->set_draggable( ctxt );
     ctxt.register_updown();
     ctxt.register_action( "END" );
     ctxt.register_action( "HOME" );
     ctxt.register_action( "MOUSE_MOVE" );
     ctxt.register_action( "PAGE_DOWN" );
     ctxt.register_action( "PAGE_UP" );
     ctxt.register_action( "SCROLL_DOWN" );
     ctxt.register_action( "SCROLL_UP" );
     ctxt.register_action( "SELECT" );
 }
References list_sb, input_context::register_action(), and input_context::register_updown().
Member Data Documentation
entries
std::vector<multiline_list_entry> multiline_list::entries private
Definition at line 960 of file output.h.
Referenced by activate_entry(), add_entry(), create_entry_prep(), fold_entries(), handle_navigation(), print_entries(), print_line(), and set_entry_pos().
entry_map
std::map<size_t, inclusive_rectangle<point> > multiline_list::entry_map private
Definition at line 963 of file output.h.
Referenced by handle_navigation(), print_entries(), and print_line().
entry_position
int multiline_list::entry_position private
Definition at line 955 of file output.h.
Referenced by get_entry_pos(), get_offset_from_entry(), handle_navigation(), print_line(), set_entry_pos(), and set_offset_pos().
entry_sizes
std::vector<int> multiline_list::entry_sizes private
Definition at line 961 of file output.h.
Referenced by fold_entries(), get_entry_from_offset(), get_offset_from_entry(), print_line(), and set_entry_pos().
has_prefix
bool multiline_list::has_prefix private
Definition at line 954 of file output.h.
Referenced by add_entry(), create_entry_prep(), and fold_entries().
list_sb
std::unique_ptr<scrollbar> multiline_list::list_sb private
Definition at line 965 of file output.h.
Referenced by handle_navigation(), multiline_list(), print_entries(), and set_up_navigation().
mouseover_accel_counter
size_t multiline_list::mouseover_accel_counter = 1 private
Definition at line 959 of file output.h.
Referenced by handle_navigation(), set_entry_pos(), and set_offset_pos().
mouseover_delay_end
std::chrono::time_point<std::chrono::steady_clock> multiline_list::mouseover_delay_end private
Definition at line 958 of file output.h.
Referenced by handle_navigation(), set_entry_pos(), and set_offset_pos().
mouseover_position
int multiline_list::mouseover_position private
Definition at line 957 of file output.h.
Referenced by handle_navigation().
offset_position
int multiline_list::offset_position private
Definition at line 956 of file output.h.
Referenced by get_entry_from_offset(), get_offset_pos(), handle_navigation(), print_entries(), and set_offset_pos().
total_length
int multiline_list::total_length private
Definition at line 962 of file output.h.
Referenced by fold_entries(), print_entries(), and set_offset_pos().
w
catacurses::window& multiline_list::w private
Definition at line 966 of file output.h.
Referenced by fold_entries(), handle_navigation(), print_entries(), print_line(), set_entry_pos(), and set_offset_pos().
The documentation for this class was generated from the following files:
src/output.h
src/output.cpp