Cataclysm DDA: molle_detach_actor Class Reference
molle_detach_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
molle_detach_actor (const std::string &type="detach_molle")
void load (const JsonObject &jo) override
std::optional< int > use (Character *p, item &it, const tripoint &pnt) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
int moves
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1028 of file iuse_actor.h.
Constructor & Destructor Documentation
molle_detach_actor()
molle_detach_actor::molle_detach_actor (const std::string & type = "detach_molle") inline explicit
Definition at line 1031 of file iuse_actor.h.
 : iuse_actor( type ) {}
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > molle_detach_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4173 of file iuse_actor.cpp.
 {
     return std::make_unique<molle_detach_actor>( *this );
 }
load()
void molle_detach_actor::load (const JsonObject & jo) override virtual
Implements iuse_actor.
Definition at line 4178 of file iuse_actor.cpp.
 {
     assign( jo, "moves", moves );
 }
References assign().
use()
std::optional< int > molle_detach_actor::use (Character * p, item & it, const tripoint & pnt) const override virtual
Implements iuse_actor.
Definition at line 4149 of file iuse_actor.cpp.
 {
     std::vector<const item *> items_attached = it.get_contents().get_added_pockets();
     uilist prompt;
     prompt.text = _( "Remove which accessory?" );
     for( size_t i = 0; i != items_attached.size(); ++i ) {
         prompt.addentry( i, true, -1, items_attached[i]->tname() );
     }
     prompt.query();
     if( prompt.ret >= 0 ) {
         p->i_add( it.get_contents().remove_pocket( prompt.ret ) );
         p->add_msg_if_player( _( "You remove the item from your %s." ), it.tname() );
         return 0;
     }
     p->add_msg_if_player( _( "Never mind." ) );
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), item_contents::get_added_pockets(), item::get_contents(), Character::i_add(), Pickup::prompt, item_contents::remove_pocket(), and item::tname().
Member Data Documentation
moves
int molle_detach_actor::moves
Definition at line 1033 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp