Cataclysm DDA: MonsterGenerator Class Reference
MonsterGenerator Class Reference
#include <monstergenerator.h>
Public Member Functions
~MonsterGenerator ()
void reset ()
void load_monster (const JsonObject &jo, const std::string &src)
void load_species (const JsonObject &jo, const std::string &src)
void load_monster_attack (const JsonObject &jo, const std::string &src)
void finalize_mtypes ()
mtype generate_fake_pseudo_dormant_monster (const mtype &mon)
void check_monster_definitions () const
std::optional< mon_action_death > get_death_function (const std::string &f) const
const std::vector< mtype > & get_all_mtypes () const
mtype_id get_valid_hallucination () const
Static Public Member Functions
static MonsterGenerator & generator ()
Private Member Functions
MonsterGenerator ()
void init_phases ()
void init_attack ()
void init_defense ()
void add_hardcoded_attack (const std::string &type, mon_action_attack f)
void add_attack (std::unique_ptr< mattack_actor >)
void add_attack (const mtype_special_attack &wrapper)
mtype_special_attack create_actor (const JsonObject &obj, const std::string &src) const
Gets an actor object without saving it anywhere.
void apply_species_attributes (mtype &mon)
void validate_species_ids (mtype &mon)
void finalize_pathfinding_settings (mtype &mon)
Private Attributes
pimpl< generic_factory< mtype > > mon_templates
pimpl< generic_factory< species_type > > mon_species
std::vector< mtype_id > hallucination_monsters
std::unordered_map< std::string, phase_id > phase_map
std::map< std::string, mon_action_death > death_map
std::map< std::string, mon_action_defend > defense_map
std::map< std::string, mtype_special_attack > attack_map
Friends
struct mtype
struct species_type
class mattack_actor
class string_id< mtype >
class string_id< species_type >
class string_id< mattack_actor >
Detailed Description
Definition at line 52 of file monstergenerator.h.
Constructor & Destructor Documentation
~MonsterGenerator()
MonsterGenerator::~MonsterGenerator () default
MonsterGenerator()
MonsterGenerator::MonsterGenerator () private
Definition at line 189 of file monstergenerator.cpp.
     : mon_templates( "monster type" )
     , mon_species( "species" )
 {
     mon_templates->insert( mtype() );
     mon_species->insert( species_type() );
     init_phases();
     init_attack();
     init_defense();
 }
References init_attack(), init_defense(), init_phases(), mon_species, mon_templates, mtype, and species_type.
Member Function Documentation
add_attack() [1/2]
void MonsterGenerator::add_attack (const mtype_special_attack & wrapper) private
Definition at line 1411 of file monstergenerator.cpp.
 {
     if( attack_map.count( wrapper->id ) > 0 ) {
         if( test_mode ) {
             debugmsg( "Overwriting monster attack with id %s", wrapper->id.c_str() );
         }
         attack_map.erase( wrapper->id );
     }
     attack_map.emplace( wrapper->id, wrapper );
 }
References attack_map, debugmsg, mattack_actor::id, and test_mode.
add_attack() [2/2]
void MonsterGenerator::add_attack (std::unique_ptr< mattack_actor > ptr) private
Definition at line 1406 of file monstergenerator.cpp.
 {
     add_attack( mtype_special_attack( std::move( ptr ) ) );
 }
Referenced by add_hardcoded_attack(), and load_monster_attack().
add_hardcoded_attack()
void MonsterGenerator::add_hardcoded_attack (const std::string & type, mon_action_attack f) private
Definition at line 1401 of file monstergenerator.cpp.
 {
     add_attack( mtype_special_attack( type, f ) );
 }
References add_attack(), and type.
Referenced by init_attack().
apply_species_attributes()
void MonsterGenerator::apply_species_attributes (mtype & mon) private
Definition at line 532 of file monstergenerator.cpp.
 {
     for( const auto &spec : mon.species ) {
         if( !spec.is_valid() ) {
             continue;
         }
         const species_type &mspec = spec.obj();
         for( const mon_flag_str_id &f : mspec.flags ) {
             mon.flags.emplace( f );
             mon.pre_flags_.emplace( f );
         }
         mon.anger |= mspec.anger;
         mon.fear |= mspec.fear;
         mon.placate |= mspec.placate;
     }
 }
References species_type::anger, mtype::anger, int_id_set< T, kFastSize >::emplace(), species_type::fear, mtype::fear, species_type::flags, mtype::flags, species_type::placate, mtype::placate, mtype::pre_flags_, and mtype::species.
Referenced by finalize_mtypes().
check_monster_definitions()
void MonsterGenerator::check_monster_definitions () const
Definition at line 1612 of file monstergenerator.cpp.
 {
     for( const mtype &mon : mon_templates->get_all() ) {
         if( !mon.src.empty() && mon.src.back().second.str() == "dda" ) {
             std::string mon_id = mon.id.str();
             std::string suffix_id = mon_id.substr( 0, mon_id.find( '_' ) );
             if( suffix_id != "mon" && suffix_id != "pseudo" ) {
                 debugmsg( "monster %s is missing mon_ (or pseudo_) prefix from id", mon.id.c_str() );
             }
         }
         if( mon.harvest.is_null() && !mon.has_flag( mon_flag_ELECTRONIC ) && !mon.id.is_null() ) {
             debugmsg( "monster %s has no harvest entry", mon.id.c_str(), mon.harvest.c_str() );
         }
         if( mon.has_flag( mon_flag_MILKABLE ) && mon.starting_ammo.empty() ) {
             debugmsg( "monster %s is flagged milkable, but has no starting ammo", mon.id.c_str() );
         }
         if( mon.has_flag( mon_flag_MILKABLE ) && !mon.starting_ammo.empty() &&
             !item( mon.starting_ammo.begin()->first ).made_of( phase_id::LIQUID ) ) {
             debugmsg( "monster %s is flagged milkable, but starting ammo %s is not a liquid type",
                       mon.id.c_str(), mon.starting_ammo.begin()->first.str() );
         }
         if( mon.has_flag( mon_flag_MILKABLE ) && mon.starting_ammo.size() > 1 ) {
             debugmsg( "monster %s is flagged milkable, but has multiple starting_ammo defined",
                       mon.id.c_str() );
         }
         for( const species_id &spec : mon.species ) {
             if( !spec.is_valid() ) {
                 debugmsg( "monster %s has invalid species %s", mon.id.c_str(), spec.c_str() );
             }
         }
         if( !mon.death_drops.is_empty() && !item_group::group_is_defined( mon.death_drops ) ) {
             debugmsg( "monster %s has unknown death drop item group: %s", mon.id.c_str(),
                       mon.death_drops.c_str() );
         }
         for( const auto &m : mon.mat ) {
             if( m.first.str() == "null" || !m.first.is_valid() ) {
                 debugmsg( "monster %s has unknown material: %s", mon.id.c_str(), m.first.c_str() );
             }
         }
         if( !mon.revert_to_itype.is_empty() && !item::type_is_defined( mon.revert_to_itype ) ) {
             debugmsg( "monster %s has unknown revert_to_itype: %s", mon.id.c_str(),
                       mon.revert_to_itype.c_str() );
         }
         if( !mon.zombify_into.is_empty() && !mon.zombify_into.is_valid() ) {
             debugmsg( "monster %s has unknown zombify_into: %s", mon.id.c_str(),
                       mon.zombify_into.c_str() );
         }
         if( !mon.fungalize_into.is_empty() && !mon.fungalize_into.is_valid() ) {
             debugmsg( "monster %s has unknown fungalize_into: %s", mon.id.c_str(),
                       mon.fungalize_into.c_str() );
         }
         if( !mon.picture_id.is_empty() && !mon.picture_id.is_valid() ) {
             debugmsg( "monster %s has unknown ascii_picture: %s", mon.id.c_str(),
                       mon.picture_id.c_str() );
         }
         if( !mon.mech_weapon.is_empty() && !item::type_is_defined( mon.mech_weapon ) ) {
             debugmsg( "monster %s has unknown mech_weapon: %s", mon.id.c_str(),
                       mon.mech_weapon.c_str() );
         }
         if( !mon.mech_battery.is_empty() && !item::type_is_defined( mon.mech_battery ) ) {
             debugmsg( "monster %s has unknown mech_battery: %s", mon.id.c_str(),
                       mon.mech_battery.c_str() );
         }
         if( !mon.mount_items.tied.is_empty() && !item::type_is_defined( mon.mount_items.tied ) ) {
             debugmsg( "monster %s has unknown mount_items.tied: %s", mon.id.c_str(),
                       mon.mount_items.tied.c_str() );
         }
         if( !mon.mount_items.tack.is_empty() && !item::type_is_defined( mon.mount_items.tack ) ) {
             debugmsg( "monster %s has unknown mount_items.tack: %s", mon.id.c_str(),
                       mon.mount_items.tack.c_str() );
         }
         if( !mon.mount_items.armor.is_empty() && !item::type_is_defined( mon.mount_items.armor ) ) {
             debugmsg( "monster %s has unknown mount_items.armor: %s", mon.id.c_str(),
                       mon.mount_items.armor.c_str() );
         }
         if( !mon.mount_items.storage.is_empty() && !item::type_is_defined( mon.mount_items.storage ) ) {
             debugmsg( "monster %s has unknown mount_items.storage: %s", mon.id.c_str(),
                       mon.mount_items.storage.c_str() );
         }
         if( !mon.harvest.is_valid() ) {
             debugmsg( "monster %s has invalid harvest_entry: %s", mon.id.c_str(), mon.harvest.c_str() );
         }
         if( !mon.dissect.is_empty() && !mon.dissect.is_valid() ) {
             debugmsg( "monster %s has invalid dissection harvest_entry: %s", mon.id.c_str(),
                       mon.dissect.c_str() );
         }
         if( mon.has_flag( mon_flag_WATER_CAMOUFLAGE ) && !monster( mon.id ).can_submerge() ) {
             debugmsg( "monster %s has WATER_CAMOUFLAGE but cannot submerge", mon.id.c_str() );
         }
         for( const scenttype_id &s_id : mon.scents_tracked ) {
             if( !s_id.is_empty() && !s_id.is_valid() ) {
                 debugmsg( "monster %s has unknown scents_tracked %s", mon.id.c_str(), s_id.c_str() );
             }
         }
         for( const scenttype_id &s_id : mon.scents_ignored ) {
             if( !s_id.is_empty() && !s_id.is_valid() ) {
                 debugmsg( "monster %s has unknown scents_ignored %s", mon.id.c_str(), s_id.c_str() );
             }
         }
         for( const std::pair<const itype_id, int> &s : mon.starting_ammo ) {
             if( !item::type_is_defined( s.first ) ) {
                 debugmsg( "starting ammo %s of monster %s is unknown", s.first.c_str(), mon.id.c_str() );
             }
         }
         for( const mon_effect_data &e : mon.atk_effs ) {
             if( !e.id.is_valid() ) {
                 debugmsg( "attack effect %s of monster %s is unknown", e.id.c_str(), mon.id.c_str() );
             }
         }
         for( const std::pair<const emit_id, time_duration> &e : mon.emit_fields ) {
             const emit_id emid = e.first;
             if( !emid.is_valid() ) {
                 debugmsg( "monster %s has invalid emit source %s", mon.id.c_str(), emid.c_str() );
             }
         }
         if( mon.upgrades ) {
             if( mon.half_life < 0 && mon.age_grow < 0 ) {
                 debugmsg( "half_life %d and age_grow %d (<0) of monster %s is invalid",
                           mon.half_life, mon.age_grow, mon.id.c_str() );
             }
             if( !mon.upgrade_into && !mon.upgrade_group ) {
                 debugmsg( "no into nor into_group defined for monster %s", mon.id.c_str() );
             }
             if( mon.upgrade_into && mon.upgrade_group ) {
                 debugmsg( "both into and into_group defined for monster %s", mon.id.c_str() );
             }
             if( !mon.upgrade_into.is_valid() ) {
                 debugmsg( "upgrade_into %s of monster %s is not a valid monster id",
                           mon.upgrade_into.c_str(), mon.id.c_str() );
             }
             if( !mon.upgrade_group.is_valid() ) {
                 debugmsg( "upgrade_group %s of monster %s is not a valid monster group id",
                           mon.upgrade_group.c_str(), mon.id.c_str() );
             }
         }
         if( mon.reproduces ) {
             if( !mon.baby_timer || *mon.baby_timer <= 0_seconds ) {
                 debugmsg( "Time between reproductions (%d) is invalid for %s",
                           mon.baby_timer ? to_turns<int>( *mon.baby_timer ) : -1, mon.id.c_str() );
             }
             if( mon.baby_count < 1 ) {
                 debugmsg( "Number of children (%d) is invalid for %s",
                           mon.baby_count, mon.id.c_str() );
             }
             if( !mon.baby_monster && mon.baby_egg.is_null() ) {
                 debugmsg( "No baby or egg defined for monster %s", mon.id.c_str() );
             }
             if( mon.baby_monster && !mon.baby_egg.is_null() ) {
                 debugmsg( "Both an egg and a live birth baby are defined for %s", mon.id.c_str() );
             }
             if( !mon.baby_monster.is_valid() ) {
                 debugmsg( "baby_monster %s of monster %s is not a valid monster id",
                           mon.baby_monster.c_str(), mon.id.c_str() );
             }
             if( !item::type_is_defined( mon.baby_egg ) ) {
                 debugmsg( "item_id %s of monster %s is not a valid item id",
                           mon.baby_egg.c_str(), mon.id.c_str() );
             }
         }
         if( mon.biosignatures ) {
             if( !mon.biosig_timer || *mon.biosig_timer <= 0_seconds ) {
                 debugmsg( "Time between biosignature drops (%d) is invalid for %s",
                           mon.biosig_timer ? to_turns<int>( *mon.biosig_timer ) : -1, mon.id.c_str() );
             }
             if( mon.biosig_item.is_null() ) {
                 debugmsg( "No biosignature drop defined for monster %s", mon.id.c_str() );
             }
             if( !item::type_is_defined( mon.biosig_item ) ) {
                 debugmsg( "item_id %s of monster %s is not a valid item id",
                           mon.biosig_item.c_str(), mon.id.c_str() );
             }
         }
         for( const std::pair<const damage_type_id, float> &dt : mon.armor.resist_vals ) {
             if( !dt.first.is_valid() ) {
                 debugmsg( "Invalid armor type \"%s\" for monster %s", dt.first.c_str(), mon.id.c_str() );
             }
         }
         for( const std::pair<const std::string, mtype_special_attack> &spatk : mon.special_attacks ) {
             const melee_actor *atk = dynamic_cast<const melee_actor *>( &*spatk.second );
             if( !atk ) {
                 continue;
             }
             for( const damage_unit &dt : atk->damage_max_instance.damage_units ) {
                 if( !dt.type.is_valid() ) {
                     debugmsg( "Invalid monster attack damage type \"%s\" for monster %s", dt.type.c_str(),
                               mon.id.c_str() );
                 }
             }
         }
         mon.weakpoints.check();
     }
 }
References string_id< T >::c_str(), monster::can_submerge(), melee_actor::damage_max_instance, damage_instance::damage_units, debugmsg, item_group::group_is_defined(), mon_effect_data::id, string_id< T >::is_empty(), string_id< T >::is_valid(), LIQUID, item::made_of(), mon_flag_ELECTRONIC, mon_flag_MILKABLE, mon_flag_WATER_CAMOUFLAGE, mon_templates, damage_unit::type, and item::type_is_defined().
Referenced by DynamicDataLoader::check_consistency().
create_actor()
mtype_special_attack MonsterGenerator::create_actor (const JsonObject & obj, const std::string & src) const private
Gets an actor object without saving it anywhere.
Definition at line 1424 of file monstergenerator.cpp.
 {
     // Legacy support: tolerate attack types being specified as the type
     const std::string type = obj.get_string( "type", "monster_attack" );
     const std::string attack_type = obj.get_string( "attack_type", type );
     if( type != "monster_attack" && attack_type != type ) {
         obj.throw_error_at(
             "type",
             R"(Specifying "attack_type" is only allowed when "type" is "monster_attack" or not specified)" );
     }
     std::unique_ptr<mattack_actor> new_attack;
     if( attack_type == "monster_attack" ) {
         const std::string id = obj.get_string( "id" );
         const auto &iter = attack_map.find( id );
         if( iter == attack_map.end() ) {
             obj.throw_error_at( "type", "Monster attacks must specify type and/or id" );
         }
         new_attack = iter->second->clone();
     } else if( attack_type == "leap" ) {
         new_attack = std::make_unique<leap_actor>();
     } else if( attack_type == "melee" ) {
         new_attack = std::make_unique<melee_actor>();
     } else if( attack_type == "bite" ) {
         new_attack = std::make_unique<bite_actor>();
     } else if( attack_type == "gun" ) {
         new_attack = std::make_unique<gun_actor>();
     } else if( attack_type == "spell" ) {
         new_attack = std::make_unique<mon_spellcasting_actor>();
     } else {
         obj.throw_error_at( "attack_type", "unknown monster attack" );
     }
     new_attack->load( obj, src );
     return mtype_special_attack( std::move( new_attack ) );
 }
References attack_map, JsonObject::get_string(), JsonObject::throw_error_at(), and type.
Referenced by mtype::add_special_attack(), and load_monster_attack().
finalize_mtypes()
void MonsterGenerator::finalize_mtypes ()
Definition at line 319 of file monstergenerator.cpp.
 {
     mon_templates->finalize();
     std::vector<mtype> extra_mtypes;
     for( const mtype &elem : mon_templates->get_all() ) {
         mtype &mon = const_cast<mtype &>( elem );
         if( !mon.default_faction.is_valid() ) {
             debugmsg( "Monster type '%s' has invalid default_faction: '%s'. "
                       "Add this faction to json as MONSTER_FACTION type.",
                       mon.id.str(), mon.default_faction.str() );
         }
         mon.flags.clear();
         for( const mon_flag_str_id &mf : mon.pre_flags_ ) {
             mon.flags.emplace( mf );
         }
         apply_species_attributes( mon );
         validate_species_ids( mon );
         mon.size = volume_to_size( mon.volume );
         // adjust for worldgen difficulty parameters
         mon.speed *= get_option<int>( "MONSTER_SPEED" )      / 100.0;
         mon.hp    *= get_option<int>( "MONSTER_RESILIENCE" ) / 100.0;
         for( const monster_adjustment &adj : adjustments ) {
             adj.apply( mon );
         }
         if( mon.bash_skill < 0 ) {
             mon.bash_skill = calc_bash_skill( mon );
         }
         finalize_damage_map( mon.armor.resist_vals, true );
         if( mon.armor_proportional.has_value() ) {
             finalize_damage_map( mon.armor_proportional->resist_vals, false, 1.f );
             for( std::pair<const damage_type_id, float> &dt : mon.armor.resist_vals ) {
                 const auto iter = mon.armor_proportional->resist_vals.find( dt.first );
                 if( iter != mon.armor_proportional->resist_vals.end() ) {
                     dt.second *= iter->second;
                 }
             }
         }
         if( mon.armor_relative.has_value() ) {
             finalize_damage_map( mon.armor_relative->resist_vals, false, 0.f );
             for( std::pair<const damage_type_id, float> &dt : mon.armor.resist_vals ) {
                 const auto iter = mon.armor_relative->resist_vals.find( dt.first );
                 if( iter != mon.armor_relative->resist_vals.end() ) {
                     dt.second += iter->second;
                 }
             }
         }
         float melee_dmg_total = mon.melee_damage.total_damage();
         float armor_diff = 3.0f;
         for( const auto &dt : mon.armor.resist_vals ) {
             if( dt.first->mon_difficulty ) {
                 armor_diff += dt.second;
             }
         }
         mon.difficulty = ( mon.melee_skill + 1 ) * mon.melee_dice * ( melee_dmg_total + mon.melee_sides ) *
                          0.04 + ( mon.sk_dodge + 1 ) * armor_diff * 0.04 +
                          ( mon.difficulty_base + mon.special_attacks.size() + 8 * mon.emit_fields.size() );
         mon.difficulty *= ( mon.hp + mon.speed - mon.attack_cost + ( mon.morale + mon.agro ) * 0.1 ) * 0.01
                           + ( mon.vision_day + 2 * mon.vision_night ) * 0.01;
         if( mon.status_chance_multiplier < 0 ) {
             mon.status_chance_multiplier = 0;
         }
         // Check if trap_ids are valid
         for( trap_str_id trap_avoid_id : mon.trap_avoids ) {
             if( !trap_avoid_id.is_valid() ) {
                 debugmsg( "Invalid trap '%s'", trap_avoid_id.str() );
             }
         }
         // Lower bound for hp scaling
         mon.hp = std::max( mon.hp, 1 );
         //If the result monster is blacklisted no need to have the original monster look like it can revive
         if( !mon.zombify_into.is_empty() &&
             MonsterGroupManager::monster_is_blacklisted( mon.zombify_into ) ) {
             mon.zombify_into = mtype_id();
         }
         build_behavior_tree( mon );
         finalize_pathfinding_settings( mon );
         mon.weakpoints.clear();
         for( const weakpoints_id &wpset : mon.weakpoints_deferred ) {
             mon.weakpoints.add_from_set( wpset, true );
         }
         if( !mon.weakpoints_deferred_inline.weakpoint_list.empty() ) {
             mon.weakpoints_deferred_inline.finalize();
             mon.weakpoints.add_from_set( mon.weakpoints_deferred_inline, true );
         }
         for( const std::string &wp_del : mon.weakpoints_deferred_deleted ) {
             for( auto iter = mon.weakpoints.weakpoint_list.begin();
                  iter != mon.weakpoints.weakpoint_list.end(); ) {
                 if( iter->id == wp_del ) {
                     iter = mon.weakpoints.weakpoint_list.erase( iter );
                 } else {
                     iter++;
                 }
             }
         }
         mon.weakpoints.finalize();
         // check lastly to make extra fake monsters.
         if( mon.has_flag( mon_flag_GEN_DORMANT ) ) {
             extra_mtypes.push_back( generate_fake_pseudo_dormant_monster( mon ) );
         }
     }
     for( const mtype &mon : mon_templates->get_all() ) {
         if( !mon.has_flag( mon_flag_NOT_HALLUCINATION ) ) {
             hallucination_monsters.push_back( mon.id );
         }
     }
     // now add the fake monsters to the mon_templates
     for( mtype &mon : extra_mtypes ) {
         mon_templates->insert( mon );
     }
 }
References weakpoints::add_from_set(), adjustments, mtype::agro, apply_species_attributes(), mtype::armor, mtype::armor_proportional, mtype::armor_relative, mtype::attack_cost, mtype::bash_skill, build_behavior_tree(), calc_bash_skill(), int_id_set< T, kFastSize >::clear(), weakpoints::clear(), debugmsg, mtype::default_faction, mtype::difficulty, mtype::difficulty_base, mtype::emit_fields, int_id_set< T, kFastSize >::emplace(), weakpoints::finalize(), finalize_damage_map(), finalize_pathfinding_settings(), mtype::flags, generate_fake_pseudo_dormant_monster(), hallucination_monsters, mtype::has_flag(), mtype::hp, mtype::id, string_id< T >::is_empty(), string_id< T >::is_valid(), max(), mtype::melee_damage, mtype::melee_dice, mtype::melee_sides, mtype::melee_skill, mon_flag_GEN_DORMANT, mon_flag_NOT_HALLUCINATION, mon_templates, MonsterGroupManager::monster_is_blacklisted(), mtype::morale, mtype_id, mtype::pre_flags_, resistances::resist_vals, mtype::size, mtype::sk_dodge, mtype::special_attacks, mtype::speed, mtype::status_chance_multiplier, string_id< T >::str(), damage_instance::total_damage(), mtype::trap_avoids, validate_species_ids(), mtype::vision_day, mtype::vision_night, mtype::volume, volume_to_size(), weakpoints::weakpoint_list, mtype::weakpoints, mtype::weakpoints_deferred, mtype::weakpoints_deferred_deleted, mtype::weakpoints_deferred_inline, and mtype::zombify_into.
Referenced by DynamicDataLoader::finalize_loaded_data().
finalize_pathfinding_settings()
void MonsterGenerator::finalize_pathfinding_settings (mtype & mon) private
Definition at line 550 of file monstergenerator.cpp.
 {
     if( mon.path_settings.max_length < 0 ) {
         mon.path_settings.max_length = mon.path_settings.max_dist * 5;
     }
     if( mon.path_settings.bash_strength < 0 ) {
         mon.path_settings.bash_strength = mon.bash_skill;
     }
     if( mon.has_flag( mon_flag_CLIMBS ) ) {
         mon.path_settings.climb_cost = 3;
     }
 }
References mtype::bash_skill, pathfinding_settings::bash_strength, pathfinding_settings::climb_cost, mtype::has_flag(), pathfinding_settings::max_dist, pathfinding_settings::max_length, mon_flag_CLIMBS, and mtype::path_settings.
Referenced by finalize_mtypes().
generate_fake_pseudo_dormant_monster()
mtype MonsterGenerator::generate_fake_pseudo_dormant_monster (const mtype & mon)
Definition at line 447 of file monstergenerator.cpp.
 {
     // this is what we are trying to build. Example for mon_zombie
     //{
     //    "id": "pseudo_dormant_mon_zombie",
     //        "type" : "MONSTER",
     //        "name" : { "str": "zombie" },
     //        "description" : "Fake zombie used for spawning dormant zombies.  If you see this, open an issue on github.",
     //        "copy-from" : "mon_zombie",
     //        "looks_like" : "corpse_mon_zombie",
     //        "hp" : 5,
     //        "speed" : 1,
     //        "flags" : ["FILTHY", "REVIVES", "DORMANT", "QUIETDEATH"] ,
     //        "zombify_into" : "mon_zombie",
     //        "special_attacks" : [
     //    {
     //        "id": "pseudo_dormant_trap_setup_attk",
     //            "type" : "spell",
     //            "spell_data" : { "id": "pseudo_dormant_trap_setup", "hit_self" : true },
     //            "cooldown" : 1,
     //            "allow_no_target" : true,
     //            "monster_message" : ""
     //    }
     //        ]
     //},
     mtype fake_mon = mtype( mon );
     fake_mon.id = mtype_id( "pseudo_dormant_" + mon.id.str() );
     // allowed (optional) flags: [ "FILTHY" ],
     // delete all others.
     // then add [ "DORMANT", "QUIETDEATH", "REVIVES", "REVIVES_HEALTHY" ]
     bool has_filthy = fake_mon.has_flag( mon_flag_FILTHY );
     fake_mon.flags.clear();
     fake_mon.flags.emplace( mon_flag_DORMANT );
     fake_mon.flags.emplace( mon_flag_QUIETDEATH );
     fake_mon.flags.emplace( mon_flag_REVIVES );
     fake_mon.flags.emplace( mon_flag_REVIVES_HEALTHY );
     if( has_filthy ) {
         fake_mon.flags.emplace( mon_flag_FILTHY );
     }
     // zombify into the original mon
     fake_mon.zombify_into = mon.id;
     // looks like "corpse" + original mon
     fake_mon.looks_like = "corpse_" + mon.id.str();
     // set the hp to 5
     fake_mon.hp = 5;
     // set the speed to 1
     fake_mon.speed = 1;
     // now ensure that monster will always die instantly. Nuke all resistances and dodges.
     // before this monsters like zombie predators could periodically resist the killing effect for a while.
     // clear dodge
     fake_mon.sk_dodge = 0;
     // clear regenerate
     fake_mon.regenerates = 0;
     fake_mon.regenerates_in_dark = false;
     // clear armor
     for( const auto &dam : fake_mon.armor.resist_vals ) {
         fake_mon.armor.resist_vals[dam.first] = 0;
     }
     // add the special attack.
     // first make a new mon_spellcasting_actor actor
     std::unique_ptr<mon_spellcasting_actor> new_actor( new mon_spellcasting_actor() );
     new_actor->allow_no_target = true;
     new_actor->cooldown = 1;
     new_actor->spell_data.id = spell_pseudo_dormant_trap_setup;
     new_actor->spell_data.self = true;
     // create the special attack now using the actor
     // use this constructor
     // explicit mtype_special_attack( std::unique_ptr<mattack_actor> f ) : actor( std::move( f ) ) { }
     std::unique_ptr<mattack_actor> base_actor = std::move( new_actor );
     mtype_special_attack new_attack( std::move( base_actor ) );
     std::pair<const std::string, mtype_special_attack> new_pair{
         std::string( "pseudo_dormant_trap_setup_attk" ),
         std::move( new_attack )
     };
     fake_mon.special_attacks.emplace( std::move( new_pair ) );
     fake_mon.special_attacks_names.emplace_back( "pseudo_dormant_trap_setup_attk" );
     return fake_mon;
 }
References mtype::armor, int_id_set< T, kFastSize >::clear(), int_id_set< T, kFastSize >::emplace(), mtype::flags, mtype::has_flag(), mtype::hp, mtype::id, mtype::looks_like, mon_flag_DORMANT, mon_flag_FILTHY, mon_flag_QUIETDEATH, mon_flag_REVIVES, mon_flag_REVIVES_HEALTHY, mtype, mtype_id, mtype::regenerates, mtype::regenerates_in_dark, resistances::resist_vals, mtype::sk_dodge, mtype::special_attacks, mtype::special_attacks_names, mtype::speed, spell_pseudo_dormant_trap_setup, string_id< T >::str(), and mtype::zombify_into.
Referenced by finalize_mtypes().
generator()
static MonsterGenerator& MonsterGenerator::generator () inline static
Definition at line 55 of file monstergenerator.h.
{
             static MonsterGenerator generator;
             return generator;
         }
Referenced by safemode::add_rules(), mtype::add_special_attack(), DynamicDataLoader::check_consistency(), DynamicDataLoader::finalize_loaded_data(), DynamicDataLoader::initialize(), mtype::load(), magical_polymorph(), game::spawn_hallucination(), safemode::test_pattern(), DynamicDataLoader::unload_data(), debug_menu::wishmonster(), and memorial_logger::write_text_memorial().
get_all_mtypes()
const std::vector< mtype > & MonsterGenerator::get_all_mtypes () const
Definition at line 1358 of file monstergenerator.cpp.
 {
     return mon_templates->get_all();
 }
References mon_templates.
Referenced by magical_polymorph().
get_death_function()
std::optional< mon_action_death > MonsterGenerator::get_death_function (const std::string & f) const
Definition at line 180 of file monstergenerator.cpp.
 {
     const auto it = death_map.find( f );
     return it != death_map.cend()
            ? std::optional<mon_action_death>( it->second )
            : std::optional<mon_action_death>();
 }
References death_map.
get_valid_hallucination()
mtype_id MonsterGenerator::get_valid_hallucination () const
Definition at line 1373 of file monstergenerator.cpp.
 {
     return random_entry( hallucination_monsters );
 }
References hallucination_monsters, and random_entry().
Referenced by game::spawn_hallucination().
init_attack()
void MonsterGenerator::init_attack () private
Definition at line 574 of file monstergenerator.cpp.
 {
     add_hardcoded_attack( "NONE", mattack::none );
     add_hardcoded_attack( "ABSORB_ITEMS", mattack::absorb_items );
     add_hardcoded_attack( "SPLIT", mattack::split );
     add_hardcoded_attack( "BROWSE", mattack::browse );
     add_hardcoded_attack( "EAT_CARRION", mattack::eat_carrion );
     add_hardcoded_attack( "EAT_CROP", mattack::eat_crop );
     add_hardcoded_attack( "EAT_FOOD", mattack::eat_food );
     add_hardcoded_attack( "GRAZE", mattack::graze );
     add_hardcoded_attack( "CHECK_UP", mattack::nurse_check_up );
     add_hardcoded_attack( "ASSIST", mattack::nurse_assist );
     add_hardcoded_attack( "OPERATE", mattack::nurse_operate );
     add_hardcoded_attack( "PAID_BOT", mattack::check_money_left );
     add_hardcoded_attack( "SHRIEK", mattack::shriek );
     add_hardcoded_attack( "SHRIEK_ALERT", mattack::shriek_alert );
     add_hardcoded_attack( "SHRIEK_STUN", mattack::shriek_stun );
     add_hardcoded_attack( "RATTLE", mattack::rattle );
     add_hardcoded_attack( "HOWL", mattack::howl );
     add_hardcoded_attack( "ACID", mattack::acid );
     add_hardcoded_attack( "ACID_BARF", mattack::acid_barf );
     add_hardcoded_attack( "ACID_ACCURATE", mattack::acid_accurate );
     add_hardcoded_attack( "SHOCKSTORM", mattack::shockstorm );
     add_hardcoded_attack( "SHOCKING_REVEAL", mattack::shocking_reveal );
     add_hardcoded_attack( "PULL_METAL_WEAPON", mattack::pull_metal_weapon );
     add_hardcoded_attack( "BOOMER", mattack::boomer );
     add_hardcoded_attack( "BOOMER_GLOW", mattack::boomer_glow );
     add_hardcoded_attack( "RESURRECT", mattack::resurrect );
     add_hardcoded_attack( "SMASH", mattack::smash );
     add_hardcoded_attack( "SCIENCE", mattack::science );
     add_hardcoded_attack( "GROWPLANTS", mattack::growplants );
     add_hardcoded_attack( "GROW_VINE", mattack::grow_vine );
     add_hardcoded_attack( "VINE", mattack::vine );
     add_hardcoded_attack( "SPIT_SAP", mattack::spit_sap );
     add_hardcoded_attack( "TRIFFID_HEARTBEAT", mattack::triffid_heartbeat );
     add_hardcoded_attack( "FUNGUS", mattack::fungus );
     add_hardcoded_attack( "FUNGUS_CORPORATE", mattack::fungus_corporate );
     add_hardcoded_attack( "FUNGUS_HAZE", mattack::fungus_haze );
     add_hardcoded_attack( "FUNGUS_BIG_BLOSSOM", mattack::fungus_big_blossom );
     add_hardcoded_attack( "FUNGUS_INJECT", mattack::fungus_inject );
     add_hardcoded_attack( "FUNGUS_BRISTLE", mattack::fungus_bristle );
     add_hardcoded_attack( "FUNGUS_GROWTH", mattack::fungus_growth );
     add_hardcoded_attack( "FUNGUS_SPROUT", mattack::fungus_sprout );
     add_hardcoded_attack( "FUNGUS_FORTIFY", mattack::fungus_fortify );
     add_hardcoded_attack( "DERMATIK", mattack::dermatik );
     add_hardcoded_attack( "DERMATIK_GROWTH", mattack::dermatik_growth );
     add_hardcoded_attack( "FUNGAL_TRAIL", mattack::fungal_trail );
     add_hardcoded_attack( "PLANT", mattack::plant );
     add_hardcoded_attack( "DISAPPEAR", mattack::disappear );
     add_hardcoded_attack( "DEPART", mattack::depart );
     add_hardcoded_attack( "FORMBLOB", mattack::formblob );
     add_hardcoded_attack( "CALLBLOBS", mattack::callblobs );
     add_hardcoded_attack( "JACKSON", mattack::jackson );
     add_hardcoded_attack( "DANCE", mattack::dance );
     add_hardcoded_attack( "DOGTHING", mattack::dogthing );
     add_hardcoded_attack( "GENE_STING", mattack::gene_sting );
     add_hardcoded_attack( "PARA_STING", mattack::para_sting );
     add_hardcoded_attack( "TRIFFID_GROWTH", mattack::triffid_growth );
     add_hardcoded_attack( "PHOTOGRAPH", mattack::photograph );
     add_hardcoded_attack( "TAZER", mattack::tazer );
     add_hardcoded_attack( "SEARCHLIGHT", mattack::searchlight );
     add_hardcoded_attack( "SPEAKER", mattack::speaker );
     add_hardcoded_attack( "FLAMETHROWER", mattack::flamethrower );
     add_hardcoded_attack( "COPBOT", mattack::copbot );
     add_hardcoded_attack( "CHICKENBOT", mattack::chickenbot );
     add_hardcoded_attack( "MULTI_ROBOT", mattack::multi_robot );
     add_hardcoded_attack( "RATKING", mattack::ratking );
     add_hardcoded_attack( "GENERATOR", mattack::generator );
     add_hardcoded_attack( "UPGRADE", mattack::upgrade );
     add_hardcoded_attack( "BREATHE", mattack::breathe );
     add_hardcoded_attack( "BRANDISH", mattack::brandish );
     add_hardcoded_attack( "FLESH_GOLEM", mattack::flesh_golem );
     add_hardcoded_attack( "ABSORB_MEAT", mattack::absorb_meat );
     add_hardcoded_attack( "LUNGE", mattack::lunge );
     add_hardcoded_attack( "PARROT", mattack::parrot );
     add_hardcoded_attack( "PARROT_AT_DANGER", mattack::parrot_at_danger );
     add_hardcoded_attack( "BLOW_WHISTLE", mattack::blow_whistle );
     add_hardcoded_attack( "DARKMAN", mattack::darkman );
     add_hardcoded_attack( "SLIMESPRING", mattack::slimespring );
     add_hardcoded_attack( "EVOLVE_KILL_STRIKE", mattack::evolve_kill_strike );
     add_hardcoded_attack( "LEECH_SPAWNER", mattack::leech_spawner );
     add_hardcoded_attack( "MON_LEECH_EVOLUTION", mattack::mon_leech_evolution );
     add_hardcoded_attack( "TINDALOS_TELEPORT", mattack::tindalos_teleport );
     add_hardcoded_attack( "FLESH_TENDRIL", mattack::flesh_tendril );
     add_hardcoded_attack( "BIO_OP_BIOJUTSU", mattack::bio_op_random_biojutsu );
     add_hardcoded_attack( "BIO_OP_TAKEDOWN", mattack::bio_op_takedown );
     add_hardcoded_attack( "BIO_OP_IMPALE", mattack::bio_op_impale );
     add_hardcoded_attack( "BIO_OP_DISARM", mattack::bio_op_disarm );
     add_hardcoded_attack( "SUICIDE", mattack::suicide );
     add_hardcoded_attack( "KAMIKAZE", mattack::kamikaze );
     add_hardcoded_attack( "GRENADIER", mattack::grenadier );
     add_hardcoded_attack( "GRENADIER_ELITE", mattack::grenadier_elite );
     add_hardcoded_attack( "RIOTBOT", mattack::riotbot );
     add_hardcoded_attack( "STRETCH_ATTACK", mattack::stretch_attack );
     add_hardcoded_attack( "DOOT", mattack::doot );
     add_hardcoded_attack( "DSA_DRONE_SCAN", mattack::dsa_drone_scan );
     add_hardcoded_attack( "ZOMBIE_FUSE", mattack::zombie_fuse );
 }
References mattack::absorb_items(), mattack::absorb_meat(), mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), add_hardcoded_attack(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), mattack::blow_whistle(), mattack::boomer(), mattack::boomer_glow(), mattack::brandish(), mattack::breathe(), mattack::browse(), mattack::callblobs(), mattack::check_money_left(), mattack::chickenbot(), mattack::copbot(), mattack::dance(), mattack::darkman(), mattack::depart(), mattack::dermatik(), mattack::dermatik_growth(), mattack::disappear(), mattack::dogthing(), mattack::doot(), mattack::dsa_drone_scan(), mattack::eat_carrion(), mattack::eat_crop(), mattack::eat_food(), mattack::evolve_kill_strike(), mattack::flamethrower(), mattack::flesh_golem(), mattack::flesh_tendril(), mattack::formblob(), mattack::fungal_trail(), mattack::fungus(), mattack::fungus_big_blossom(), mattack::fungus_bristle(), mattack::fungus_corporate(), mattack::fungus_fortify(), mattack::fungus_growth(), mattack::fungus_haze(), mattack::fungus_inject(), mattack::fungus_sprout(), mattack::gene_sting(), mattack::generator(), mattack::graze(), mattack::grenadier(), mattack::grenadier_elite(), mattack::grow_vine(), mattack::growplants(), mattack::howl(), mattack::jackson(), mattack::kamikaze(), mattack::leech_spawner(), mattack::lunge(), mattack::mon_leech_evolution(), mattack::multi_robot(), mattack::none(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), mattack::para_sting(), mattack::parrot(), mattack::parrot_at_danger(), mattack::photograph(), mattack::plant(), mattack::pull_metal_weapon(), mattack::ratking(), mattack::rattle(), mattack::resurrect(), mattack::riotbot(), mattack::science(), mattack::searchlight(), mattack::shocking_reveal(), mattack::shockstorm(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), mattack::slimespring(), mattack::smash(), mattack::speaker(), mattack::spit_sap(), mattack::split(), mattack::stretch_attack(), mattack::suicide(), mattack::tazer(), mattack::tindalos_teleport(), mattack::triffid_growth(), mattack::triffid_heartbeat(), mattack::upgrade(), mattack::vine(), and mattack::zombie_fuse().
Referenced by MonsterGenerator(), and reset().
init_defense()
void MonsterGenerator::init_defense () private
Definition at line 673 of file monstergenerator.cpp.
 {
     // No special attack-back
     defense_map["NONE"] = &mdefense::none;
     // Shock attacker on hit
     defense_map["ZAPBACK"] = &mdefense::zapback;
     // Splash acid on the attacker
     defense_map["ACIDSPLASH"] = &mdefense::acidsplash;
     // Blind fire on unseen attacker
     defense_map["RETURN_FIRE"] = &mdefense::return_fire;
 }
References mdefense::acidsplash(), defense_map, mdefense::none(), mdefense::return_fire(), and mdefense::zapback().
Referenced by MonsterGenerator().
init_phases()
void MonsterGenerator::init_phases () private
Definition at line 565 of file monstergenerator.cpp.
 {
     phase_map["NULL"] = phase_id::PNULL;
     phase_map["SOLID"] = phase_id::SOLID;
     phase_map["LIQUID"] = phase_id::LIQUID;
     phase_map["GAS"] = phase_id::GAS;
     phase_map["PLASMA"] = phase_id::PLASMA;
 }
References GAS, LIQUID, phase_map, PLASMA, PNULL, and SOLID.
Referenced by MonsterGenerator().
load_monster()
void MonsterGenerator::load_monster (const JsonObject & jo, const std::string & src)
Definition at line 695 of file monstergenerator.cpp.
 {
     mon_templates->load( jo, src );
 }
References mon_templates.
Referenced by DynamicDataLoader::initialize().
load_monster_attack()
void MonsterGenerator::load_monster_attack (const JsonObject & jo, const std::string & src)
Definition at line 1483 of file monstergenerator.cpp.
 {
     add_attack( create_actor( jo, src ) );
 }
References add_attack(), and create_actor().
Referenced by DynamicDataLoader::initialize().
load_species()
void MonsterGenerator::load_species (const JsonObject & jo, const std::string & src)
Definition at line 1286 of file monstergenerator.cpp.
 {
     mon_species->load( jo, src );
 }
References mon_species.
Referenced by DynamicDataLoader::initialize().
reset()
void MonsterGenerator::reset ()
Definition at line 202 of file monstergenerator.cpp.
 {
     mon_templates->reset();
     mon_templates->insert( mtype() );
     mon_species->reset();
     mon_species->insert( species_type() );
     hallucination_monsters.clear();
     attack_map.clear();
     // Hardcode attacks need to be re-added here
     // TODO: Move initialization from constructor to init()
     init_attack();
 }
References attack_map, hallucination_monsters, init_attack(), mon_species, mon_templates, mtype, and species_type.
Referenced by DynamicDataLoader::unload_data().
validate_species_ids()
void MonsterGenerator::validate_species_ids (mtype & mon) private
Definition at line 685 of file monstergenerator.cpp.
 {
     for( const auto &s : mon.species ) {
         if( !s.is_valid() ) {
             debugmsg( "Tried to assign species %s to monster %s, but no entry for the species exists",
                       s.c_str(), mon.id.c_str() );
         }
     }
 }
References string_id< T >::c_str(), debugmsg, mtype::id, and mtype::species.
Referenced by finalize_mtypes().
Friends And Related Function Documentation
mattack_actor
friend class mattack_actor friend
Definition at line 82 of file monstergenerator.h.
mtype
friend struct mtype friend
Definition at line 80 of file monstergenerator.h.
Referenced by generate_fake_pseudo_dormant_monster(), MonsterGenerator(), and reset().
species_type
friend struct species_type friend
Definition at line 81 of file monstergenerator.h.
Referenced by MonsterGenerator(), and reset().
string_id< mattack_actor >
friend class string_id< mattack_actor > friend
Definition at line 102 of file monstergenerator.h.
string_id< mtype >
friend class string_id< mtype > friend
Definition at line 102 of file monstergenerator.h.
string_id< species_type >
friend class string_id< species_type > friend
Definition at line 102 of file monstergenerator.h.
Member Data Documentation
attack_map
std::map<std::string, mtype_special_attack> MonsterGenerator::attack_map private
Definition at line 115 of file monstergenerator.h.
Referenced by add_attack(), mtype::add_special_attack(), create_actor(), and reset().
death_map
std::map<std::string, mon_action_death> MonsterGenerator::death_map private
Definition at line 113 of file monstergenerator.h.
Referenced by get_death_function().
defense_map
std::map<std::string, mon_action_defend> MonsterGenerator::defense_map private
Definition at line 114 of file monstergenerator.h.
Referenced by init_defense(), and mtype::load().
hallucination_monsters
std::vector<mtype_id> MonsterGenerator::hallucination_monsters private
Definition at line 110 of file monstergenerator.h.
Referenced by finalize_mtypes(), get_valid_hallucination(), and reset().
mon_species
pimpl<generic_factory<species_type> > MonsterGenerator::mon_species private
Definition at line 109 of file monstergenerator.h.
Referenced by load_species(), MonsterGenerator(), and reset().
mon_templates
pimpl<generic_factory<mtype> > MonsterGenerator::mon_templates private
Definition at line 108 of file monstergenerator.h.
Referenced by check_monster_definitions(), finalize_mtypes(), get_all_mtypes(), load_monster(), MonsterGenerator(), and reset().
phase_map
std::unordered_map<std::string, phase_id> MonsterGenerator::phase_map private
Definition at line 112 of file monstergenerator.h.
Referenced by init_phases(), and mtype::load().
The documentation for this class was generated from the following files:
src/monstergenerator.h
src/monstergenerator.cpp