Cataclysm DDA: lightson_game Class Reference
lightson_game Class Reference
#include <iuse_software_lightson.h>
Public Member Functions
int start_game ()
lightson_game ()=default
Private Member Functions
void new_level ()
void reset_level ()
void generate_change_coords (int changes)
void draw_level ()
bool check_win ()
void toggle_lights ()
void toggle_lights_at (const point &pt)
bool get_value_at (const point &pt)
void set_value_at (const point &pt, bool value)
void toggle_value_at (const point &pt)
Private Attributes
catacurses::window w_border
catacurses::window w
point level_size
std::vector< bool > level
std::vector< point > change_coords
point position
bool win = false
Detailed Description
Definition at line 10 of file iuse_software_lightson.h.
Constructor & Destructor Documentation
lightson_game()
lightson_game::lightson_game () default
Member Function Documentation
check_win()
bool lightson_game::check_win () private
Definition at line 99 of file iuse_software_lightson.cpp.
 {
     return std::all_of( level.begin(), level.end(), []( bool i ) {
         return i;
     } );
 }
References level.
Referenced by start_game().
draw_level()
void lightson_game::draw_level () private
Definition at line 63 of file iuse_software_lightson.cpp.
 {
     werase( w );
     draw_border( w );
     for( int i = 0; i < level_size.y; i++ ) {
         for( int j = 0; j < level_size.x; j++ ) {
             point current = point( j, i );
             bool selected = position == current;
             bool on = get_value_at( current );
             const nc_color fg = on ? c_white : c_dark_gray;
             const char symbol = on ? '#' : '-';
             mvwputch( w, current + point_south_east, selected ? hilite( c_white ) : fg, symbol );
         }
     }
     wnoutrefresh( w );
 }
References c_dark_gray, c_white, draw_border(), get_value_at(), hilite(), level_size, mvwputch(), point, point_south_east, position, symbol(), w, catacurses::werase(), catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by start_game().
generate_change_coords()
void lightson_game::generate_change_coords (int changes) private
Definition at line 80 of file iuse_software_lightson.cpp.
 {
     change_coords.resize( changes );
     const int size = level_size.y * level_size.x;
     point candidate;
     for( int k = 0; k < changes; k++ ) {
         do {
             const int candidate_index = rng( 0, size - 1 );
             candidate.x = candidate_index % level_size.x;
             candidate.y = ( candidate_index - candidate.x ) / level_size.x;
             // not accept repeatable coordinates
         } while( !( k == 0 ||
                     std::find( change_coords.begin(), change_coords.end(), candidate ) == change_coords.end() ) );
         change_coords[k] = candidate;
     }
 }
References change_coords, level_size, rng(), om_direction::size, point::x, and point::y.
Referenced by new_level().
get_value_at()
bool lightson_game::get_value_at (const point & pt) private
Definition at line 48 of file iuse_software_lightson.cpp.
 {
     return level[pt.y * level_size.x + pt.x];
 }
References level, level_size, point::x, and point::y.
Referenced by draw_level(), and toggle_value_at().
new_level()
void lightson_game::new_level () private
Definition at line 19 of file iuse_software_lightson.cpp.
 {
     win = false;
     // level generation
     const int half_perimeter = rng( 8, 11 );
     const int lvl_width = rng( 4, 6 );
     const int lvl_height = half_perimeter - lvl_width;
     level_size = point( lvl_width, lvl_height );
     level.resize( static_cast<size_t>( lvl_height ) * static_cast<size_t>( lvl_width ) );
     const int steps_rng = half_perimeter / 2.0 + rng_float( 0.0, 2.0 );
     generate_change_coords( steps_rng );
     reset_level();
 }
References generate_change_coords(), level, level_size, point, reset_level(), rng(), rng_float(), and win.
Referenced by start_game().
reset_level()
void lightson_game::reset_level () private
Definition at line 36 of file iuse_software_lightson.cpp.
 {
     std::fill( level.begin(), level.end(), true );
     // change level
     std::for_each( change_coords.begin(), change_coords.end(), [this]( point & p ) {
         toggle_lights_at( p );
     } );
     position = point_zero;
 }
References change_coords, level, point_zero, and position.
Referenced by new_level(), and start_game().
set_value_at()
void lightson_game::set_value_at (const point & pt, bool value) private
Definition at line 53 of file iuse_software_lightson.cpp.
 {
     level[pt.y * level_size.x + pt.x] = value;
 }
References level, level_size, point::x, and point::y.
Referenced by toggle_value_at().
start_game()
int lightson_game::start_game ()
Definition at line 130 of file iuse_software_lightson.cpp.
 {
     const int w_height = 15;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         const point iOffset( TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0,
                              TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0 );
         w_border = catacurses::newwin( w_height, FULL_SCREEN_WIDTH, iOffset );
         w = catacurses::newwin( w_height - 6, FULL_SCREEN_WIDTH - 2, iOffset + point_south_east );
         ui.position_from_window( w_border );
     } );
     ui.mark_resize();
     input_context ctxt( "LIGHTSON" );
     ctxt.register_directions();
     ctxt.register_action( "TOGGLE_SPACE" );
     ctxt.register_action( "TOGGLE_5" );
     ctxt.register_action( "RESET" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ui.on_redraw( [&]( const ui_adaptor & ) {
         std::vector<std::string> shortcuts;
         shortcuts.emplace_back( _( "<spacebar or 5> toggle lights" ) );
         shortcuts.emplace_back( _( "<r>eset" ) );
         shortcuts.emplace_back( _( "<q>uit" ) );
         int iWidth = 0;
         for( auto &shortcut : shortcuts ) {
             if( iWidth > 0 ) {
                 iWidth += 1;
             }
             iWidth += utf8_width( shortcut );
         }
         werase( w_border );
         draw_border( w_border );
         int iPos = FULL_SCREEN_WIDTH - iWidth - 1;
         for( auto &shortcut : shortcuts ) {
             shortcut_print( w_border, point( iPos, 0 ), c_white, c_light_green, shortcut );
             iPos += utf8_width( shortcut ) + 1;
         }
         mvwputch( w_border, point( 2, 0 ), hilite( c_white ), _( "Lights on!" ) );
         fold_and_print( w_border, point( 2, w_height - 5 ), FULL_SCREEN_WIDTH - 4, c_light_gray,
                         "%s\n%s\n%s", _( "<color_white>Game goal:</color> Switch all the lights on." ),
                         _( "<color_white>Legend: #</color> on, <color_dark_gray>-</color> off." ),
                         _( "Toggle lights switches selected light and 4 its neighbors." ) );
         wnoutrefresh( w_border );
         draw_level();
     } );
     win = true;
     int hasWon = 0;
     do {
         if( win ) {
             new_level();
         }
         ui_manager::redraw();
         std::string action = ctxt.handle_input();
         if( const std::optional<tripoint> vec = ctxt.get_direction( action ) ) {
             position.y = clamp( position.y + vec->y, 0, level_size.y - 1 );
             position.x = clamp( position.x + vec->x, 0, level_size.x - 1 );
         } else if( action == "TOGGLE_SPACE" || action == "TOGGLE_5" ) {
             toggle_lights();
             win = check_win();
             if( win ) {
                 ui.invalidate_ui();
                 popup_top( _( "Congratulations, you won!" ) );
                 hasWon++;
             }
         } else if( action == "RESET" ) {
             reset_level();
         } else if( action == "QUIT" ) {
             break;
         }
     } while( true );
     return hasWon;
 }
References _, action, c_light_gray, c_light_green, c_white, check_win(), clamp(), draw_border(), draw_level(), fold_and_print(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, input_context::get_direction(), input_context::handle_input(), hilite(), level_size, mvwputch(), new_level(), catacurses::newwin(), point, point_south_east, popup_top(), position, ui_manager::redraw(), input_context::register_action(), input_context::register_directions(), reset_level(), shortcut_print(), TERMX, TERMY, toggle_lights(), utf8_width(), w, w_border, catacurses::werase(), win, catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by play_videogame().
toggle_lights()
void lightson_game::toggle_lights () private
Definition at line 106 of file iuse_software_lightson.cpp.
 {
     toggle_lights_at( position );
 }
References position, and toggle_lights_at().
Referenced by start_game().
toggle_lights_at()
void lightson_game::toggle_lights_at (const point & pt) private
Definition at line 111 of file iuse_software_lightson.cpp.
 {
     toggle_value_at( pt );
     if( pt.y > 0 ) {
         toggle_value_at( pt + point_north );
     }
     if( pt.y < level_size.y - 1 ) {
         toggle_value_at( pt + point_south );
     }
     if( pt.x > 0 ) {
         toggle_value_at( pt + point_west );
     }
     if( pt.x < level_size.x - 1 ) {
         toggle_value_at( pt + point_east );
     }
 }
References level_size, point_east, point_north, point_south, point_west, toggle_value_at(), point::x, and point::y.
Referenced by toggle_lights().
toggle_value_at()
void lightson_game::toggle_value_at (const point & pt) private
Definition at line 58 of file iuse_software_lightson.cpp.
 {
     set_value_at( pt, !get_value_at( pt ) );
 }
References get_value_at(), and set_value_at().
Referenced by toggle_lights_at().
Member Data Documentation
change_coords
std::vector<point> lightson_game::change_coords private
Definition at line 18 of file iuse_software_lightson.h.
Referenced by generate_change_coords(), and reset_level().
level
std::vector<bool> lightson_game::level private
Definition at line 17 of file iuse_software_lightson.h.
Referenced by check_win(), get_value_at(), new_level(), reset_level(), and set_value_at().
level_size
point lightson_game::level_size private
Definition at line 16 of file iuse_software_lightson.h.
Referenced by draw_level(), generate_change_coords(), get_value_at(), new_level(), set_value_at(), start_game(), and toggle_lights_at().
position
point lightson_game::position private
Definition at line 20 of file iuse_software_lightson.h.
Referenced by draw_level(), reset_level(), start_game(), and toggle_lights().
w
catacurses::window lightson_game::w private
Definition at line 14 of file iuse_software_lightson.h.
Referenced by draw_level(), and start_game().
w_border
catacurses::window lightson_game::w_border private
Definition at line 13 of file iuse_software_lightson.h.
Referenced by start_game().
win
bool lightson_game::win = false private
Definition at line 21 of file iuse_software_lightson.h.
Referenced by new_level(), and start_game().
The documentation for this class was generated from the following files:
src/iuse_software_lightson.h
src/iuse_software_lightson.cpp