Cataclysm DDA: harvest_activity_actor Class Reference
harvest_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
harvest_activity_actor (const tripoint &target, bool auto_forage=false)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
Private Attributes
tripoint target
bool exam_furn = false
bool nectar = false
bool auto_forage = false
Detailed Description
Definition at line 1118 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
harvest_activity_actor()
harvest_activity_actor::harvest_activity_actor (const tripoint & target, bool auto_forage = false) inline explicit
Definition at line 1121 of file activity_actor_definitions.h.
                                                                     :
             target( target ), auto_forage( auto_forage ) {};
Member Function Documentation
can_resume_with_internal()
bool harvest_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override private virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 1146 of file activity_actor_definitions.h.
{
             const harvest_activity_actor &actor = static_cast<const harvest_activity_actor &>
                                                   ( other );
             return target == actor.target && auto_forage == actor.auto_forage &&
                    exam_furn == actor.exam_furn && nectar == actor.nectar;
         }
References auto_forage, exam_furn, nectar, other, and target.
clone()
std::unique_ptr<activity_actor> harvest_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1133 of file activity_actor_definitions.h.
{
             return std::make_unique<harvest_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > harvest_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 4302 of file activity_actor.cpp.
 {
     harvest_activity_actor actor( tripoint_zero );
     JsonObject jsobj = jsin.get_object();
     jsobj.read( "target", actor.target );
     jsobj.read( "exam_furn", actor.exam_furn );
     jsobj.read( "nectar", actor.nectar );
     jsobj.read( "auto_forage", actor.auto_forage );
     return actor.clone();
 }
References auto_forage, clone(), exam_furn, JsonValue::get_object(), nectar, JsonObject::read(), target, and tripoint_zero.
do_turn()
void harvest_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1130 of file activity_actor_definitions.h.
 {};
finish()
void harvest_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 4255 of file activity_actor.cpp.
 {
     act.set_to_null();
     map &here = get_map();
     // If nothing can be harvested, neither can nectar
     // Incredibly low priority TODO: Allow separating nectar seasons
     if( nectar && iexamine_helper::drink_nectar( who ) ) {
         return;
     }
     const float survival_skill = who.get_skill_level( skill_survival );
     bool got_anything = false;
     for( const harvest_entry &entry : here.get_harvest( target ).obj() ) {
         const float min_num = entry.scale_num.first * survival_skill + entry.base_num.first;
         const float max_num = entry.scale_num.second * survival_skill + entry.base_num.second;
         const int roll = std::min<int>( entry.max, std::round( rng_float( min_num, max_num ) ) );
         got_anything = roll > 0;
         for( int i = 0; i < roll; i++ ) {
             iexamine_helper::handle_harvest( who, entry.drop, false );
         }
     }
     if( !got_anything ) {
         who.add_msg_if_player( m_bad, _( "You couldn't harvest anything." ) );
     }
     if( exam_furn ) {
         here.furn_set( target, furn_str_id::NULL_ID() );
     } else {
         here.ter_set( target, here.get_ter_transforms_into( target ) );
     }
     iexamine::practice_survival_while_foraging( who );
 }
References _, act, Character::add_msg_if_player(), iexamine_helper::drink_nectar(), Character::drop(), exam_furn, map::furn_set(), map::get_harvest(), get_map(), Character::get_skill_level(), map::get_ter_transforms_into(), iexamine_helper::handle_harvest(), m_bad, nectar, string_id< furn_t >::NULL_ID(), string_id< T >::obj(), iexamine::practice_survival_while_foraging(), rng_float(), round(), skill_survival, target, and map::ter_set().
get_type()
activity_id harvest_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1125 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_HARVEST" );
         }
References activity_id.
serialize()
void harvest_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 4292 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target", target );
     jsout.member( "exam_furn", exam_furn );
     jsout.member( "nectar", nectar );
     jsout.member( "auto_forage", auto_forage );
     jsout.end_object();
 }
References auto_forage, JsonOut::end_object(), exam_furn, JsonOut::member(), nectar, JsonOut::start_object(), and target.
start()
void harvest_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 4219 of file activity_actor.cpp.
 {
     map &here = get_map();
     if( here.has_furn( target ) ) {
         const furn_id furn = here.furn( target );
         if( furn->has_examine( iexamine::harvest_furn ) ) {
             exam_furn = true;
         } else if( furn->has_examine( iexamine::harvest_furn_nectar ) )  {
             exam_furn = true;
             nectar = true;
         }
     }
     const harvest_id harvest = here.get_harvest( target );
     if( harvest.is_null() || harvest->empty() ) {
         if( !auto_forage ) {
             who.add_msg_if_player( m_info,
                                    _( "Nothing can be harvested from this plant in the current season." ) );
         }
         if( who.manual_examine ) {
             iexamine::none( who, target );
         }
         act.set_to_null();
         return;
     }
     const time_duration forage_time = rng( 5_seconds, 15_seconds );
     add_msg_debug( debugmode::DF_ACT_HARVEST, "harvest time: %s", to_string_writable( forage_time ) );
     act.moves_total = to_moves<int>( forage_time );
     act.moves_left = act.moves_total;
 }
References _, act, add_msg_debug, Character::add_msg_if_player(), auto_forage, debugmode::DF_ACT_HARVEST, exam_furn, map::furn(), map::get_harvest(), get_map(), harvest, iexamine::harvest_furn(), iexamine::harvest_furn_nectar(), map_data_common_t::has_examine(), map::has_furn(), m_info, Character::manual_examine, nectar, iexamine::none(), rng(), target, and to_string_writable().
Member Data Documentation
auto_forage
bool harvest_activity_actor::auto_forage = false private
Definition at line 1144 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), serialize(), and start().
exam_furn
bool harvest_activity_actor::exam_furn = false private
Definition at line 1142 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), serialize(), and start().
nectar
bool harvest_activity_actor::nectar = false private
Definition at line 1143 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), serialize(), and start().
target
tripoint harvest_activity_actor::target private
Definition at line 1141 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp