Cataclysm DDA: advanced_inventory_pane Class Reference
advanced_inventory_pane Class Reference
Displayed pane, what is shown on the screen.
#include <advanced_inv_pane.h>
Public Member Functions
void set_area (const advanced_inv_area &square, bool in_vehicle_cargo=false)
void restore_area ()
aim_location get_area () const
bool prev_in_vehicle () const
bool in_vehicle () const
void save_settings () const
void load_settings (int saved_area_idx, const std::array< advanced_inv_area, NUM_AIM_LOCATIONS > &squares, bool is_re_enter)
void add_items_from_area (advanced_inv_area &square, bool vehicle_override=false)
void fix_index ()
Makes sure the index is valid (if possible).
bool is_filtered (const advanced_inv_listitem &it) const
bool is_filtered (const item &it) const
Same as the other, but checks the real item.
void scroll_by (int offset)
Scroll index, by given offset,.
void scroll_page (int linesPerPage, int offset)
Scroll index, by given offset in pages,.
void scroll_category (int offset)
Scroll index, in category mode by given offset.
void scroll_to_start ()
void scroll_to_end ()
advanced_inv_listitem * get_cur_item_ptr ()
units::volume free_volume (const advanced_inv_area &square) const
units::mass free_weight_capacity () const
void set_filter (const std::string &new_filter)
Set the filter string, disables filtering when the filter string is empty.
Public Attributes
advanced_inv_pane_save_state * save_state
int index = 0
Index of the selected item (index of items),.
advanced_inv_sortby sortby = advanced_inv_sortby::SORTBY_NONE
catacurses::window window
std::vector< advanced_inv_listitem > items
std::string filter
The current filter string.
bool recalc = false
Whether to recalculate the content of this pane.
item_location target_item_after_recalc
item_location container
The active container item in container view.
aim_location container_base_loc = NUM_AIM_LOCATIONS
The original location from which container view was entered.
int other_cont = -1
The line number of the other pane's container, if it's inside this pane's aim location.
Private Member Functions
void mod_index (int offset)
Only add offset to index, but wrap around!
Private Attributes
aim_location area = NUM_AIM_LOCATIONS
aim_location prev_area = area
bool viewing_cargo = false
bool prev_viewing_cargo = false
std::map< std::string, std::function< bool(const item &)> > filtercache
Detailed Description
Displayed pane, what is shown on the screen.
Definition at line 39 of file advanced_inv_pane.h.
Member Function Documentation
add_items_from_area()
void advanced_inventory_pane::add_items_from_area (advanced_inv_area & square, bool vehicle_override = false)
Definition at line 194 of file advanced_inv_pane.cpp.
 {
     cata_assert( square.id != AIM_ALL );
     if( !square.canputitems( container ) ) {
         return;
     }
     map &m = get_map();
     avatar &u = get_avatar();
     // Existing items are *not* cleared on purpose, this might be called
     // several times in case all surrounding squares are to be shown.
     if( square.id == AIM_INVENTORY ) {
         square.volume = 0_ml;
         square.weight = 0_gram;
         items = u.get_AIM_inventory( *this, square );
     } else if( square.id == AIM_WORN ) {
         square.volume = 0_ml;
         square.weight = 0_gram;
         item_location weapon = u.get_wielded_item();
         if( weapon ) {
             advanced_inv_listitem it( weapon, 0, 1, square.id, false );
             if( !is_filtered( *it.items.front() ) ) {
                 square.volume += it.volume;
                 square.weight += it.weight;
                 items.push_back( it );
             }
         }
         u.worn.add_AIM_items_from_area( u, square, *this );
     } else if( square.id == AIM_CONTAINER ) {
         square.volume = 0_ml;
         square.weight = 0_gram;
         if( container ) {
             if( !container->is_container_empty() ) {
                 // filtering does not make sense for liquid in container
                 size_t item_index = 0;
                 for( const std::vector<item_location> &it_stack : item_list_to_stack( container,
                         container->all_items_top() ) ) {
                     advanced_inv_listitem adv_it( it_stack, item_index++, square.id, false );
                     if( !is_filtered( *adv_it.items.front() ) ) {
                         square.volume += adv_it.volume;
                         square.weight += adv_it.weight;
                         items.push_back( adv_it );
                     }
                 }
             }
         }
     } else {
         bool is_in_vehicle = square.can_store_in_vehicle() && ( in_vehicle() || vehicle_override );
         if( is_in_vehicle ) {
             square.volume_veh = 0_ml;
             square.weight_veh = 0_gram;
         } else {
             square.volume = 0_ml;
             square.weight = 0_gram;
         }
         const advanced_inv_area::itemstack &stacks = is_in_vehicle ?
                 square.i_stacked( square.get_vehicle_stack() ) :
                 square.i_stacked( m.i_at( square.pos ) );
         map_cursor loc_cursor( square.pos );
         for( size_t x = 0; x < stacks.size(); ++x ) {
             std::vector<item_location> locs;
             locs.reserve( stacks[x].size() );
             for( item *const it : stacks[x] ) {
                 if( is_in_vehicle ) {
                     locs.emplace_back( vehicle_cursor( *square.veh, square.vstor ), it );
                 } else {
                     locs.emplace_back( loc_cursor, it );
                     if( it->is_corpse() ) {
                         for( item *loot : it->all_items_top( pocket_type::CONTAINER ) ) {
                             if( !is_filtered( *loot ) ) {
                                 advanced_inv_listitem aim_item( item_location( item_location( loc_cursor, it ), loot ),
                                                                 0, 1, square.id, is_in_vehicle );
                                 square.volume += aim_item.volume;
                                 square.weight += aim_item.weight;
                                 items.push_back( aim_item );
                             }
                         }
                     }
                 }
             }
             advanced_inv_listitem it( locs, x, square.id, is_in_vehicle );
             if( is_filtered( *it.items.front() ) ) {
                 continue;
             }
             if( is_in_vehicle ) {
                 square.volume_veh += it.volume;
                 square.weight_veh += it.weight;
             } else {
                 square.volume += it.volume;
                 square.weight += it.weight;
             }
             items.push_back( it );
         }
     }
 }
References AIM_ALL, AIM_CONTAINER, AIM_INVENTORY, AIM_WORN, item::all_items_top(), cata_assert, container, CONTAINER, get_avatar(), get_map(), map::i_at(), in_vehicle(), item::is_container_empty(), is_filtered(), item_list_to_stack(), advanced_inv_listitem::items, items, loot(), om_direction::size, square(), u, advanced_inv_listitem::volume, and advanced_inv_listitem::weight.
Referenced by advanced_inventory::recalc_pane().
fix_index()
void advanced_inventory_pane::fix_index ()
Makes sure the index is valid (if possible).
Definition at line 293 of file advanced_inv_pane.cpp.
 {
     if( items.empty() ) {
         index = 0;
         return;
     }
     if( index < 0 ) {
         index = 0;
     } else if( static_cast<size_t>( index ) >= items.size() ) {
         index = static_cast<int>( items.size() ) - 1;
     }
 }
References index, and items.
Referenced by advanced_inventory::redraw_pane().
free_volume()
units::volume advanced_inventory_pane::free_volume (const advanced_inv_area & square) const
Returns
free volume capacity of the pane's container or area
Definition at line 437 of file advanced_inv_pane.cpp.
 {
     // should be a specific location instead
     cata_assert( area != AIM_ALL );
     if( area == AIM_CONTAINER ) {
         if( !container ) {
             return 0_ml;
         }
         return container->get_remaining_capacity();
     } else if( area == AIM_INVENTORY || area == AIM_WORN ) {
         return get_player_character().free_space();
     } else if( in_vehicle() ) {
         return square.get_vehicle_stack().free_volume();
     } else {
         return get_map().free_volume( square.pos );
     }
 }
References AIM_ALL, AIM_CONTAINER, AIM_INVENTORY, AIM_WORN, area, cata_assert, container, Character::free_space(), map::free_volume(), get_map(), get_player_character(), item::get_remaining_capacity(), in_vehicle(), and square().
Referenced by advanced_inventory::move_all_items().
free_weight_capacity()
units::mass advanced_inventory_pane::free_weight_capacity () const
Returns
free weight capacity of the pane's container or area
Definition at line 455 of file advanced_inv_pane.cpp.
 {
     // should be a specific location instead
     cata_assert( area != AIM_ALL );
     if( area == AIM_CONTAINER ) {
         if( !container ) {
             return 0_gram;
         }
         return container->get_remaining_weight_capacity();
     } else if( area == AIM_INVENTORY || area == AIM_WORN ) {
         return get_player_character().free_weight_capacity();
     } else {
         return units::mass_max;
     }
 }
References AIM_ALL, AIM_CONTAINER, AIM_INVENTORY, AIM_WORN, area, cata_assert, container, Character::free_weight_capacity(), get_player_character(), item::get_remaining_weight_capacity(), and units::mass_max.
Referenced by advanced_inventory::move_all_items().
get_area()
aim_location advanced_inventory_pane::get_area () const inline
Definition at line 51 of file advanced_inv_pane.h.
{
             return area;
         }
References area.
Referenced by advanced_inventory::action_examine(), advanced_inventory::action_move_item(), advanced_inventory::change_square(), advanced_inventory::display(), advanced_inventory::fill_lists_with_pane_items(), advanced_inventory::move_all_items(), advanced_inventory::print_header(), advanced_inventory::print_items(), advanced_inventory::recalc_pane(), advanced_inventory::redraw_pane(), and save_settings().
get_cur_item_ptr()
advanced_inv_listitem * advanced_inventory_pane::get_cur_item_ptr ()
Returns
either null, if index is invalid, or the selected item in items.
Definition at line 429 of file advanced_inv_pane.cpp.
 {
     if( static_cast<size_t>( index ) >= items.size() ) {
         return nullptr;
     }
     return &items[index];
 }
References index, and items.
Referenced by advanced_inventory::change_square(), advanced_inventory::display(), advanced_inventory::print_header(), advanced_inventory::redraw_pane(), and scroll_category().
in_vehicle()
bool advanced_inventory_pane::in_vehicle () const inline
Definition at line 57 of file advanced_inv_pane.h.
{
             return viewing_cargo;
         }
References viewing_cargo.
Referenced by advanced_inventory::action_move_item(), add_items_from_area(), advanced_inventory::change_square(), advanced_inventory::display(), free_volume(), advanced_inventory::move_all_items(), advanced_inventory::print_header(), advanced_inventory::print_items(), advanced_inventory::recalc_pane(), and save_settings().
is_filtered() [1/2]
bool advanced_inventory_pane::is_filtered (const advanced_inv_listitem & it) const
Parameters
it The item to check, only the name member is examined.
Returns
Whether the item should be filtered (and not shown).
Definition at line 89 of file advanced_inv_pane.cpp.
 {
     return is_filtered( *it.items.front() );
 }
References advanced_inv_listitem::items.
Referenced by outfit::add_AIM_items_from_area(), add_items_from_area(), avatar::get_AIM_inventory(), and outfit::get_AIM_inventory().
is_filtered() [2/2]
bool advanced_inventory_pane::is_filtered (const item & it) const
Same as the other, but checks the real item.
Definition at line 94 of file advanced_inv_pane.cpp.
 {
     if( it.has_flag( STATIC( flag_id( "HIDDEN_ITEM" ) ) ) ) {
         return true;
     }
     if( filter.empty() ) {
         return false;
     }
     const std::string str = it.tname();
     if( filtercache.find( str ) == filtercache.end() ) {
         const auto filter_fn = item_filter_from_string( filter );
         filtercache[str] = filter_fn;
         return !filter_fn( it );
     }
     return !filtercache[str]( it );
 }
References filter, filtercache, flag_id, item::has_flag(), item_filter_from_string(), STATIC, and item::tname().
load_settings()
void advanced_inventory_pane::load_settings (int saved_area_idx, const std::array< advanced_inv_area, NUM_AIM_LOCATIONS > & squares, bool is_re_enter)
Definition at line 61 of file advanced_inv_pane.cpp.
 {
     const int i_location = ( get_option<bool>( "OPEN_DEFAULT_ADV_INV" ) &&
                              !is_re_enter ) ? saved_area_idx :
                            save_state->area_idx;
     const aim_location location = static_cast<aim_location>( i_location );
     const advanced_inv_area &square = squares[location];
     // determine the square's vehicle/map item presence
     bool has_veh_items = square.can_store_in_vehicle() && !square.get_vehicle_stack().empty();
     bool has_map_items = !get_map().i_at( square.pos ).empty();
     // determine based on map items and settings to show cargo
     bool show_vehicle = false;
     if( is_re_enter ) {
         show_vehicle = save_state->in_vehicle;
     } else if( has_veh_items == has_map_items ) {
         show_vehicle = save_state->in_vehicle && square.can_store_in_vehicle();
     } else {
         show_vehicle = has_veh_items;
     }
     set_area( square, show_vehicle );
     sortby = static_cast<advanced_inv_sortby>( save_state->sort_idx );
     index = save_state->selected_idx;
     filter = save_state->filter;
     container = save_state->container;
     container_base_loc = static_cast<aim_location>( save_state->container_base_loc );
 }
References advanced_inv_pane_save_state::area_idx, container, advanced_inv_pane_save_state::container, container_base_loc, advanced_inv_pane_save_state::container_base_loc, item_stack::empty(), filter, advanced_inv_pane_save_state::filter, get_map(), map::i_at(), advanced_inv_pane_save_state::in_vehicle, index, location, save_state, advanced_inv_pane_save_state::selected_idx, set_area(), advanced_inv_pane_save_state::sort_idx, sortby, square(), and squares.
mod_index()
void advanced_inventory_pane::mod_index (int offset) private
Only add offset to index, but wrap around!
Definition at line 306 of file advanced_inv_pane.cpp.
 {
     // 0 would make no sense
     cata_assert( offset != 0 );
     cata_assert( !items.empty() );
     index += offset;
     if( index < 0 ) {
         index = static_cast<int>( items.size() ) - 1;
     } else if( static_cast<size_t>( index ) >= items.size() ) {
         index = 0;
     }
 }
References cata_assert, index, and items.
Referenced by scroll_by().
prev_in_vehicle()
bool advanced_inventory_pane::prev_in_vehicle () const inline
Definition at line 54 of file advanced_inv_pane.h.
{
             return prev_viewing_cargo;
         }
References prev_viewing_cargo.
restore_area()
void advanced_inventory_pane::restore_area ()
Definition at line 44 of file advanced_inv_pane.cpp.
 {
     area = prev_area;
     viewing_cargo = prev_viewing_cargo;
 }
References area, prev_area, prev_viewing_cargo, and viewing_cargo.
Referenced by advanced_inventory::action_move_item(), and advanced_inventory::move_all_items().
save_settings()
void advanced_inventory_pane::save_settings () const
Definition at line 50 of file advanced_inv_pane.cpp.
 {
     save_state->container = container;
     save_state->container_base_loc = container_base_loc;
     save_state->in_vehicle = in_vehicle();
     save_state->area_idx = get_area();
     save_state->selected_idx = index;
     save_state->filter = filter;
     save_state->sort_idx = sortby;
 }
References advanced_inv_pane_save_state::area_idx, container, advanced_inv_pane_save_state::container, container_base_loc, advanced_inv_pane_save_state::container_base_loc, filter, advanced_inv_pane_save_state::filter, get_area(), in_vehicle(), advanced_inv_pane_save_state::in_vehicle, index, save_state, advanced_inv_pane_save_state::selected_idx, advanced_inv_pane_save_state::sort_idx, and sortby.
scroll_by()
void advanced_inventory_pane::scroll_by (int offset)
Scroll index, by given offset,.
Parameters
offset Must not be 0.
Definition at line 319 of file advanced_inv_pane.cpp.
 {
     // 0 would make no sense
     cata_assert( offset != 0 );
     if( items.empty() ) {
         return;
     }
     mod_index( offset );
 }
References cata_assert, items, and mod_index().
Referenced by advanced_inventory::action_examine(), and advanced_inventory::display().
scroll_category()
void advanced_inventory_pane::scroll_category (int offset)
Scroll index, in category mode by given offset.
Parameters
offset Must be either +1 or -1
Definition at line 388 of file advanced_inv_pane.cpp.
 {
     // only those two offsets are allowed
     cata_assert( offset == -1 || offset == +1 );
     if( items.empty() ) {
         return;
     }
     // index must already be valid!
     cata_assert( get_cur_item_ptr() != nullptr );
     const item_category *cur_cat = items[index].cat;
     if( offset > 0 ) {
         while( items[index].cat == cur_cat ) {
             index++;
             // wrap to begin, stop there.
             if( static_cast<size_t>( index ) >= items.size() ) {
                 index = 0;
                 break;
             }
         }
     } else {
         while( items[index].cat == cur_cat ) {
             index--;
             // wrap to end, stop there.
             if( index < 0 ) {
                 index = static_cast<int>( items.size() ) - 1;
                 break;
             }
         }
     }
 }
References cata_assert, get_cur_item_ptr(), index, and items.
Referenced by advanced_inventory::display().
scroll_page()
void advanced_inventory_pane::scroll_page (int linesPerPage, int offset)
Scroll index, by given offset in pages,.
Parameters
linesPerPage Amount of lines that can be displayed per page.
offset Must be either +1 or -1.
Definition at line 329 of file advanced_inv_pane.cpp.
 {
     // only those two offsets are allowed
     cata_assert( offset == -1 || offset == +1 );
     if( items.empty() ) {
         return;
     }
     const int size = static_cast<int>( items.size() );
     advanced_inventory_pagination old_pagination( linesPerPage, *this );
     for( int i = 0; i <= index; i++ ) {
         old_pagination.step( i );
     }
     // underflow
     if( old_pagination.page + offset < 0 ) {
         if( index > 0 ) {
             // scroll to top of first page
             index = 0;
         } else {
             // scroll wrap
             index = size - 1;
         }
         return;
     }
     int previous_line = -1; // matching line one up from our line
     advanced_inventory_pagination new_pagination( linesPerPage, *this );
     for( int i = 0; i < size; i++ ) {
         new_pagination.step( i );
         // right page
         if( new_pagination.page == old_pagination.page + offset ) {
             // right line
             if( new_pagination.line == old_pagination.line ) {
                 index = i;
                 return;
             }
             // one up from right line
             if( new_pagination.line == old_pagination.line - 1 ) {
                 previous_line = i;
             }
         }
     }
     // second-best matching line
     if( previous_line != -1 ) {
         index = previous_line;
         return;
     }
     // overflow
     if( index < size - 1 ) {
         // scroll to end of last page
         index = size - 1;
     } else {
         // scroll wrap
         index = 0;
     }
 }
References cata_assert, index, items, advanced_inventory_pagination::line, advanced_inventory_pagination::page, om_direction::size, and advanced_inventory_pagination::step().
Referenced by advanced_inventory::display().
scroll_to_end()
void advanced_inventory_pane::scroll_to_end ()
Definition at line 424 of file advanced_inv_pane.cpp.
 {
     index = static_cast<int>( items.size() ) - 1;
 }
References index, and items.
Referenced by advanced_inventory::display().
scroll_to_start()
void advanced_inventory_pane::scroll_to_start ()
Definition at line 419 of file advanced_inv_pane.cpp.
 {
     index = 0;
 }
References index.
Referenced by advanced_inventory::display().
set_area()
void advanced_inventory_pane::set_area (const advanced_inv_area & square, bool in_vehicle_cargo = false)
Definition at line 36 of file advanced_inv_pane.cpp.
 {
     prev_area = area;
     prev_viewing_cargo = viewing_cargo;
     area = square.id;
     viewing_cargo = square.can_store_in_vehicle() && ( in_vehicle_cargo || area == AIM_DRAGGED );
 }
References AIM_DRAGGED, area, prev_area, prev_viewing_cargo, square(), and viewing_cargo.
Referenced by advanced_inventory::change_square(), advanced_inventory::display(), load_settings(), and advanced_inventory::move_all_items().
set_filter()
void advanced_inventory_pane::set_filter (const std::string & new_filter)
Set the filter string, disables filtering when the filter string is empty.
Definition at line 471 of file advanced_inv_pane.cpp.
 {
     if( filter == new_filter ) {
         return;
     }
     filter = new_filter;
     filtercache.clear();
     recalc = true;
 }
References filter, filtercache, and recalc.
Referenced by advanced_inventory::display().
Member Data Documentation
area
aim_location advanced_inventory_pane::area = NUM_AIM_LOCATIONS private
Definition at line 42 of file advanced_inv_pane.h.
Referenced by free_volume(), free_weight_capacity(), get_area(), restore_area(), and set_area().
container
item_location advanced_inventory_pane::container
The active container item in container view.
Definition at line 84 of file advanced_inv_pane.h.
Referenced by advanced_inventory::action_examine(), advanced_inventory::action_move_item(), add_items_from_area(), advanced_inventory::change_square(), advanced_inventory::fill_lists_with_pane_items(), free_volume(), free_weight_capacity(), load_settings(), advanced_inventory::move_all_items(), advanced_inventory::print_header(), advanced_inventory::print_items(), advanced_inventory::recalc_pane(), advanced_inventory::redraw_pane(), and save_settings().
container_base_loc
aim_location advanced_inventory_pane::container_base_loc = NUM_AIM_LOCATIONS
The original location from which container view was entered.
Definition at line 88 of file advanced_inv_pane.h.
Referenced by advanced_inventory::change_square(), load_settings(), advanced_inventory::print_header(), advanced_inventory::recalc_pane(), and save_settings().
filter
std::string advanced_inventory_pane::filter
The current filter string.
Definition at line 74 of file advanced_inv_pane.h.
Referenced by advanced_inventory::display(), is_filtered(), load_settings(), advanced_inventory::redraw_pane(), save_settings(), and set_filter().
filtercache
std::map<std::string, std::function<bool(const item &)> > advanced_inventory_pane::filtercache mutable private
Definition at line 147 of file advanced_inv_pane.h.
Referenced by is_filtered(), and set_filter().
index
int advanced_inventory_pane::index = 0
Index of the selected item (index of items),.
Definition at line 67 of file advanced_inv_pane.h.
Referenced by advanced_inventory::change_square(), advanced_inventory::display(), fix_index(), get_cur_item_ptr(), load_settings(), mod_index(), advanced_inventory::print_items(), advanced_inventory::recalc_pane(), advanced_inventory::redraw_pane(), save_settings(), scroll_category(), scroll_page(), scroll_to_end(), and scroll_to_start().
items
std::vector<advanced_inv_listitem> advanced_inventory_pane::items
Definition at line 70 of file advanced_inv_pane.h.
Referenced by outfit::add_AIM_items_from_area(), add_items_from_area(), advanced_inventory::fill_lists_with_pane_items(), fix_index(), get_cur_item_ptr(), advanced_inventory_pagination::lines_needed(), mod_index(), advanced_inventory::move_all_items(), advanced_inventory::print_items(), advanced_inventory::recalc_pane(), advanced_inventory::redraw_pane(), scroll_by(), scroll_category(), scroll_page(), scroll_to_end(), and advanced_inventory_pagination::step().
other_cont
int advanced_inventory_pane::other_cont = -1
The line number of the other pane's container, if it's inside this pane's aim location.
Definition at line 92 of file advanced_inv_pane.h.
Referenced by advanced_inventory::print_items().
prev_area
aim_location advanced_inventory_pane::prev_area = area private
Definition at line 43 of file advanced_inv_pane.h.
Referenced by restore_area(), and set_area().
prev_viewing_cargo
bool advanced_inventory_pane::prev_viewing_cargo = false private
Definition at line 46 of file advanced_inv_pane.h.
Referenced by prev_in_vehicle(), restore_area(), and set_area().
recalc
bool advanced_inventory_pane::recalc = false
Whether to recalculate the content of this pane.
Definition at line 78 of file advanced_inv_pane.h.
Referenced by advanced_inventory::change_square(), advanced_inventory::display(), advanced_inventory::recalc_pane(), advanced_inventory::redraw_pane(), and set_filter().
save_state
advanced_inv_pane_save_state* advanced_inventory_pane::save_state
Definition at line 60 of file advanced_inv_pane.h.
Referenced by load_settings(), and save_settings().
sortby
advanced_inv_sortby advanced_inventory_pane::sortby = advanced_inv_sortby::SORTBY_NONE
Definition at line 68 of file advanced_inv_pane.h.
Referenced by advanced_inventory_pagination::lines_needed(), load_settings(), advanced_inventory::print_items(), advanced_inventory::recalc_pane(), advanced_inventory::redraw_pane(), save_settings(), and advanced_inventory::show_sort_menu().
target_item_after_recalc
item_location advanced_inventory_pane::target_item_after_recalc
Definition at line 79 of file advanced_inv_pane.h.
Referenced by advanced_inventory::change_square(), and advanced_inventory::recalc_pane().
viewing_cargo
bool advanced_inventory_pane::viewing_cargo = false private
Definition at line 45 of file advanced_inv_pane.h.
Referenced by in_vehicle(), restore_area(), and set_area().
window
catacurses::window advanced_inventory_pane::window
Definition at line 69 of file advanced_inv_pane.h.
Referenced by advanced_inventory::print_header(), advanced_inventory::print_items(), and advanced_inventory::redraw_pane().
The documentation for this class was generated from the following files:
src/advanced_inv_pane.h
src/advanced_inv_pane.cpp