Cataclysm DDA: effect_source Class Reference
effect_source Class Reference
#include <effect_source.h>
Public Member Functions
effect_source ()=default
effect_source (const monster *mon)
effect_source (const faction *fac)
effect_source (const Character *character)
effect_source (const Creature *creature)
std::optional< character_id > get_character_id () const
std::optional< faction_id > get_faction_id () const
std::optional< mfaction_id > get_mfaction_id () const
Creature * resolve_creature () const
void serialize (JsonOut &) const
void deserialize (const JsonObject &data)
Static Public Member Functions
static effect_source empty ()
Private Attributes
std::optional< character_id > character = character_id()
std::optional< faction_id > fac = faction_id()
std::optional< mfaction_id > mfac = mfaction_id()
Detailed Description
Definition at line 20 of file effect_source.h.
Constructor & Destructor Documentation
effect_source() [1/5]
effect_source::effect_source () default
Referenced by empty().
effect_source() [2/5]
effect_source::effect_source (const monster * mon) explicit
Definition at line 13 of file effect_source.cpp.
 {
     if( mon == nullptr ) {
         debugmsg( "effect_source constructor called with nullptr monster" );
         return;
     }
     this->mfac = std::optional<mfaction_id>( mon->faction );
 }
References debugmsg, monster::faction, and mfac.
effect_source() [3/5]
effect_source::effect_source (const faction * fac) explicit
Definition at line 22 of file effect_source.cpp.
 {
     if( fac == nullptr ) {
         debugmsg( "effect_source constructor called with nullptr faction" );
         return;
     }
     this->fac = std::optional<faction_id>( fac->id );
 }
References debugmsg, and fac.
effect_source() [4/5]
effect_source::effect_source (const Character * character) explicit
Definition at line 31 of file effect_source.cpp.
 {
     if( character == nullptr ) {
         debugmsg( "effect_source constructor called with nullptr character" );
         return;
     }
     this->character = character->getID();
     this->fac = character->get_faction() != nullptr
                 ? character->get_faction()->id : faction_id();
 }
References character, debugmsg, fac, faction_id, and Character::get_faction().
effect_source() [5/5]
effect_source::effect_source (const Creature * creature) explicit
Definition at line 42 of file effect_source.cpp.
 {
     if( creature == nullptr ) {
         // TODO: most unassigned effects will fall here with nullptrs
         // once everything is assigned this warning can be enabled
         // debugmsg( "effect_source constructor called with nullptr creature" );
         return;
     }
     const Character *const character = creature->as_character();
     if( character != nullptr ) {
         this->character = character->getID();
         this->fac = character->get_faction() != nullptr
                     ? character->get_faction()->id : faction_id();
         return;
     }
     const monster *const monster = creature->as_monster();
     if( monster != nullptr ) {
         this->mfac = monster->faction;
         return;
     } else {
         debugmsg( "effect_source constructor couldn't extract anything from provided creature" );
         return;
     }
 }
References character, creature, debugmsg, fac, monster::faction, faction_id, Character::get_faction(), and mfac.
Member Function Documentation
deserialize()
void effect_source::deserialize (const JsonObject & data)
Definition at line 521 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     data.read( "character_id", this->character );
     data.read( "faction_id", this->fac );
     const mfaction_str_id mfac_id( data.get_string( "mfaction_id", "invalid*faction" ) );
     this->mfac = mfac_id.is_valid()
                  ? std::optional<mfaction_id>( mfac_id.id() )
                  : std::optional<mfaction_id>();
 }
References item_pocket::data, string_id< T >::id(), and string_id< T >::is_valid().
empty()
effect_source effect_source::empty () static
Definition at line 69 of file effect_source.cpp.
 {
     return effect_source();
 }
References effect_source().
Referenced by Creature::add_effect(), Creature::add_env_effect(), item::effective_dps(), field_effect::get_effect(), mattack::photograph(), and Character::process_effects().
get_character_id()
std::optional< character_id > effect_source::get_character_id () const
Definition at line 74 of file effect_source.cpp.
 {
     return this->character;
 }
References character.
Referenced by resolve_creature().
get_faction_id()
std::optional< faction_id > effect_source::get_faction_id () const
Definition at line 79 of file effect_source.cpp.
 {
     return this->fac;
 }
References fac.
get_mfaction_id()
std::optional< mfaction_id > effect_source::get_mfaction_id () const
Definition at line 84 of file effect_source.cpp.
 {
     return this->mfac;
 }
References mfac.
resolve_creature()
Creature * effect_source::resolve_creature () const
Definition at line 89 of file effect_source.cpp.
 {
     // if effect has source try figuring out who to credit
     const std::optional<character_id> eff_source = get_character_id();
     Creature *source_creature;
     if( !eff_source ) {
         source_creature = nullptr;
     } else if( eff_source.value() == get_player_character().getID() ) {
         source_creature = &get_player_character();
     } else {
         source_creature = g->find_npc( eff_source.value() );
     }
     return source_creature;
 }
References g, get_character_id(), and get_player_character().
Referenced by Creature::process_effects(), and monster::process_one_effect().
serialize()
void effect_source::serialize (JsonOut & json) const
Definition at line 510 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "character_id", this->character );
     json.member( "faction_id", this->fac );
     if( this->mfac ) {
         json.member( "mfaction_id", this->mfac->id().str() );
     }
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
character
std::optional<character_id> effect_source::character = character_id() private
Definition at line 46 of file effect_source.h.
Referenced by effect_source(), and get_character_id().
fac
std::optional<faction_id> effect_source::fac = faction_id() private
Definition at line 47 of file effect_source.h.
Referenced by effect_source(), and get_faction_id().
mfac
std::optional<mfaction_id> effect_source::mfac = mfaction_id() private
Definition at line 48 of file effect_source.h.
Referenced by effect_source(), and get_mfaction_id().
The documentation for this class was generated from the following files:
src/effect_source.h
src/effect_source.cpp
src/savegame_json.cpp