Cataclysm DDA: dispersion_sources Class Reference
dispersion_sources Class Reference
#include <dispersion.h>
Public Member Functions
dispersion_sources (double normal_source=0.0)
void add_range (double new_source)
void add_multiplier (double new_multiplier)
void add_spread (double new_spread)
double roll () const
double max () const
double avg () const
Private Attributes
std::vector< double > normal_sources
std::vector< double > linear_sources
std::vector< double > multipliers
std::vector< double > spread_sources
double prev_roll = -1.0
Friends
std::ostream & operator<< (std::ostream &stream, const dispersion_sources &sources)
Detailed Description
Definition at line 8 of file dispersion.h.
Constructor & Destructor Documentation
dispersion_sources()
dispersion_sources::dispersion_sources (double normal_source = 0.0) inline explicit
Definition at line 17 of file dispersion.h.
{
             if( normal_source != 0.0 ) {
                 normal_sources.push_back( normal_source );
             }
         }
References normal_sources.
Member Function Documentation
add_multiplier()
void dispersion_sources::add_multiplier (double new_multiplier) inline
Definition at line 25 of file dispersion.h.
{
             multipliers.push_back( new_multiplier );
         }
References multipliers.
Referenced by Character::get_weapon_dispersion().
add_range()
void dispersion_sources::add_range (double new_source) inline
Definition at line 22 of file dispersion.h.
{
             linear_sources.push_back( new_source );
         }
References linear_sources.
Referenced by calculate_ranged_chances(), Character::fire_gun(), Character::get_weapon_dispersion(), and print_aim().
add_spread()
void dispersion_sources::add_spread (double new_spread) inline
Definition at line 28 of file dispersion.h.
{
             spread_sources.push_back( new_spread );
         }
References spread_sources.
Referenced by Character::fire_gun().
avg()
double dispersion_sources::avg () const
Definition at line 49 of file dispersion.cpp.
 {
     return max() / 2.0;
 }
References max().
max()
double dispersion_sources::max () const
Definition at line 31 of file dispersion.cpp.
 {
     double sum = 0.0;
     for( const double &source : linear_sources ) {
         sum += source;
     }
     for( const double &source : normal_sources ) {
         sum += source;
     }
     for( const double &source : multipliers ) {
         sum *= source;
     }
     for( const double &spread : spread_sources ) {
         sum += spread;
     }
     return sum;
 }
References linear_sources, multipliers, normal_sources, and spread_sources.
Referenced by avg(), confidence_estimate(), npc::confident_gun_mode_range(), item::gun_info(), and Character::gun_value().
roll()
double dispersion_sources::roll () const
Definition at line 5 of file dispersion.cpp.
 {
     // The roll "latches" for a given instance of a dispersion source.
     double this_roll = 0.0;
     if( prev_roll < 0.0 ) {
         for( const double &source : linear_sources ) {
             this_roll += rng_float( 0.0, source );
         }
         for( const double &source : normal_sources ) {
             this_roll += rng_normal( source );
         }
         for( const double &source : multipliers ) {
             this_roll *= source;
         }
         prev_roll = this_roll;
     } else {
         this_roll = prev_roll;
     }
     for( const double &source : spread_sources ) {
         // Normal distribution centered on 0, but flip negatives to positive.
         double sample = rng_normal( -source, source );
         this_roll += sample >= 0 ? sample : -sample;
     }
     return this_roll;
 }
References linear_sources, multipliers, normal_sources, prev_roll, rng_float(), rng_normal(), and spread_sources.
Referenced by projectile_attack_roll().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, const dispersion_sources & sources) friend
Member Data Documentation
linear_sources
std::vector<double> dispersion_sources::linear_sources private
Definition at line 12 of file dispersion.h.
Referenced by add_range(), max(), and roll().
multipliers
std::vector<double> dispersion_sources::multipliers private
Definition at line 13 of file dispersion.h.
Referenced by add_multiplier(), max(), and roll().
normal_sources
std::vector<double> dispersion_sources::normal_sources private
Definition at line 11 of file dispersion.h.
Referenced by dispersion_sources(), max(), and roll().
prev_roll
double dispersion_sources::prev_roll = -1.0 mutable private
Definition at line 15 of file dispersion.h.
Referenced by roll().
spread_sources
std::vector<double> dispersion_sources::spread_sources private
Definition at line 14 of file dispersion.h.
Referenced by add_spread(), max(), and roll().
The documentation for this class was generated from the following files:
src/dispersion.h
src/dispersion.cpp