Cataclysm DDA: folded_text Class Reference
folded_text Class Reference
Public Member Functions
folded_text (const std::string &str, int line_width)
const std::vector< folded_line > & get_lines () const
point codepoint_coordinates (int cpt_idx, bool zero_x) const
Private Attributes
std::vector< folded_line > lines
Detailed Description
Definition at line 48 of file string_editor_window.cpp.
Constructor & Destructor Documentation
folded_text()
folded_text::folded_text (const std::string & str, int line_width)
Definition at line 67 of file string_editor_window.cpp.
 {
     // string pointer, remaining bytes, total codepoints, and total display width ...
     // ... before current processed character
     const char *src = str.c_str();
     int bytes = str.length();
     int cpts = 0;
     int width = 0;
     // ... before current line start
     const char *src_start = src;
     int cpts_start = cpts;
     int width_start = width;
     // ... after the last word character
     const char *src_word = src_start;
     // ... at the last breaking position
     const char *src_break = src_start;
     int cpts_break = cpts_start;
     int width_break = width_start;
     while( bytes > 0 ) {
         // ... before current processed character
         const char *const src_curr = src;
         const int cpts_curr = cpts;
         const int width_curr = width;
         // ... after current processed character
         const uint32_t uc = UTF8_getch( &src, &bytes );
         const bool linebreak = is_linebreak( uc );
         // assuming character has non-negative width
         const int cw = linebreak ? 0 : std::max( 0, mk_wcwidth( uc ) );
         cpts += 1;
         width += cw;
         // can we break before the current character?
         if( break_before( uc ) && src_curr > src_start
             // break with at least one word character before
             && src_word > src_start ) {
             src_break = src_curr;
             cpts_break = cpts_curr;
             width_break = width_curr;
         }
         // if the characters so far do not fit in a single line
         if( width > width_start + line_width ) {
             if( src_break > src_start ) {
                 // break at the last breaking position in the line if any
                 lines.emplace_back( folded_line {
                     cpts_start, cpts_break,
                     std::string( src_start, src_break )
                 } );
                 src_start = src_break;
                 cpts_start = cpts_break;
                 width_start = width_break;
             } else if( src_curr > src_start ) {
                 // otherwise break before the current character, but ensure
                 // each line has at least one character
                 lines.emplace_back( folded_line {
                     cpts_start, cpts_curr,
                     std::string( src_start, src_curr )
                 } );
                 src_start = src_curr;
                 cpts_start = cpts_curr;
                 width_start = width_curr;
             }
         }
         // always break on line breaks
         if( linebreak ) {
             lines.emplace_back( folded_line {
                 cpts_start, cpts,
                 std::string( src_start, src )
             } );
             src_start = src;
             cpts_start = cpts;
             width_start = width;
         }
         if( is_word( uc ) ) {
             src_word = src;
         }
         // can we break after the current character?
         if( break_after( uc ) && src > src_start
             // break with at least one word character before
             && src_word > src_start ) {
             src_break = src;
             cpts_break = cpts;
             width_break = width;
         }
     }
     // remaining characters (empty line if the string is empty or the last
     // character is line break)
     lines.emplace_back( folded_line {
         cpts_start, cpts,
         std::string( src_start, src )
     } );
 }
References break_after(), break_before(), is_linebreak(), is_word(), lines, max(), mk_wcwidth(), and UTF8_getch().
Member Function Documentation
codepoint_coordinates()
point folded_text::codepoint_coordinates (int cpt_idx, bool zero_x) const
Definition at line 163 of file string_editor_window.cpp.
 {
     if( lines.empty() ) {
         return point_zero;
     }
     // find the line before the cursor position
     auto it = std::lower_bound( lines.begin(), lines.end(), cpt_idx,
     []( const folded_line & l, const int p ) {
         return l.cpts_end < p;
     } );
     if( it == lines.end() ) {
         // past the last codepoint, shouldn't happen
         return point_zero;
     }
     int y = std::distance( lines.begin(), it );
     // if zero_x is true and the line is not the last line, cursor at the end of
     // the line is moved to the start of the next line
     if( zero_x && static_cast<size_t>( y ) + 1 < lines.size()
         && cpt_idx == it->cpts_end ) {
         return point( 0, y + 1 );
     }
     // otherwise, calculate the width until cpt_idx
     int x = 0;
     const char *src = it->str.c_str();
     int bytes = it->str.length();
     for( int i = 0; bytes > 0 && i < cpt_idx - it->cpts_start; ++i ) {
         const uint32_t uc = UTF8_getch( &src, &bytes );
         if( is_linebreak( uc ) ) {
             x = 0;
             ++y;
         } else {
             x += std::max( 0, mk_wcwidth( uc ) );
         }
     }
     return point( x, y );
 }
References is_linebreak(), lines, max(), mk_wcwidth(), point, point_zero, and UTF8_getch().
get_lines()
const std::vector< folded_line > & folded_text::get_lines () const
Definition at line 158 of file string_editor_window.cpp.
 {
     return lines;
 }
References lines.
Member Data Documentation
lines
std::vector<folded_line> folded_text::lines private
Definition at line 51 of file string_editor_window.cpp.
Referenced by codepoint_coordinates(), folded_text(), and get_lines().
The documentation for this class was generated from the following file:
src/string_editor_window.cpp