Cataclysm DDA: saw_barrel_inventory_preset Class Reference
saw_barrel_inventory_preset Class Reference
Public Member Functions
saw_barrel_inventory_preset (const Character &you, const item &tool, const saw_barrel_actor &actor)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from weapon_inventory_preset
weapon_inventory_preset (const Character &you)
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Private Attributes
const Character & you
const item & tool
const saw_barrel_actor & actor
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 1882 of file game_inventory.cpp.
Constructor & Destructor Documentation
saw_barrel_inventory_preset()
saw_barrel_inventory_preset::saw_barrel_inventory_preset (const Character & you, const item & tool, const saw_barrel_actor & actor) inline
Definition at line 1885 of file game_inventory.cpp.
                                                                      :
             weapon_inventory_preset( you ), you( you ), tool( tool ), actor( actor ) {
         }
Member Function Documentation
get_denial()
std::string saw_barrel_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from weapon_inventory_preset.
Definition at line 1894 of file game_inventory.cpp.
{
             const auto ret = actor.can_use_on( you, tool, *loc );
             if( !ret.success() ) {
                 return trim_trailing_punctuations( ret.str() );
             }
             return std::string();
         }
References actor, saw_barrel_actor::can_use_on(), cata::hash64_detail::ret, tool, trim_trailing_punctuations(), and you.
is_shown()
bool saw_barrel_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from weapon_inventory_preset.
Definition at line 1890 of file game_inventory.cpp.
{
             return loc->is_gun();
         }
References item::is_gun().
Member Data Documentation
actor
const saw_barrel_actor& saw_barrel_inventory_preset::actor private
Definition at line 1907 of file game_inventory.cpp.
Referenced by get_denial().
tool
const item& saw_barrel_inventory_preset::tool private
Definition at line 1906 of file game_inventory.cpp.
Referenced by get_denial().
you
const Character& saw_barrel_inventory_preset::you private
Definition at line 1905 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp