Cataclysm DDA: options_manager::cOpt Class Reference
options_manager::cOpt Class Reference
#include <options.h>
Public Types
enum COPT_VALUE_TYPE {
CVT_UNKNOWN = 0 , CVT_BOOL = 1 , CVT_STRING = 2 , CVT_FLOAT = 3 ,
CVT_INT = 4 , CVT_VOID = 5
}
Public Member Functions
cOpt ()
bool is_hidden () const
Option should be hidden in current build.
std::string getName () const
std::string getPage () const
std::string getMenuText () const
The translated displayed option name.
std::string getTooltip () const
The translated displayed option tool tip.
std::string getType () const
std::string getValue (bool classis_locale=false) const
std::string getValueName () const
The translated currently selected option value.
std::string getDefaultText (bool bTranslated=true) const
int getItemPos (const std::string &sSearch) const
std::vector< id_and_option > getItems () const
int getIntPos (int iSearch) const
std::optional< int_and_option > findInt (int iSearch) const
int getMaxLength () const
void setNext ()
void setPrev ()
void setValue (const std::string &sSetIn)
void setValue (float fSetIn)
void setValue (int iSetIn)
template<typename T >
T value_as (bool convert=false) const
bool operator== (const cOpt &rhs) const
bool operator!= (const cOpt &rhs) const
void setPrerequisites (const std::string &sOption, const std::vector< std::string > &sAllowedValues)
void setPrerequisite (const std::string &sOption, const std::string &sAllowedValue="true")
std::string getPrerequisite () const
bool hasPrerequisite () const
bool checkPrerequisite () const
template<>
bool value_as (bool convert) const
Static Public Member Functions
static std::vector< std::string > getPrerequisiteSupportedTypes ()
Private Member Functions
template<typename T >
std::optional< T > _convert () const
Private Attributes
std::string sName
std::string sPage
translation sMenuText
translation sTooltip
std::string sType
bool verbose = false
std::string format
std::string sPrerequisite
std::vector< std::string > sPrerequisiteAllowedValues
copt_hide_t hide
COPT_VALUE_TYPE eType
std::string sSet
std::vector< id_and_option > vItems
std::string sDefault
int iMaxLength = 0
bool bSet = false
bool bDefault = false
int iSet = 0
int iMin = 0
int iMax = 0
int iDefault = 0
std::vector< int_and_option > mIntValues
float fSet = 0.0f
float fMin = 0.0f
float fMax = 0.0f
float fDefault = 0.0f
float fStep = 0.0f
Friends
class options_manager
Detailed Description
Definition at line 80 of file options.h.
Member Enumeration Documentation
COPT_VALUE_TYPE
enum options_manager::cOpt::COPT_VALUE_TYPE
Enumerator
CVT_UNKNOWN
CVT_BOOL
CVT_STRING
CVT_FLOAT
CVT_INT
CVT_VOID
Definition at line 142 of file options.h.
{
                     CVT_UNKNOWN = 0,
                     CVT_BOOL = 1,
                     CVT_STRING = 2,
                     CVT_FLOAT = 3,
                     CVT_INT = 4,
                     CVT_VOID = 5
                 };
Constructor & Destructor Documentation
cOpt()
options_manager::cOpt::cOpt ()
Definition at line 285 of file options.cpp.
 {
     sType = "VOID";
     eType = CVT_VOID;
     hide = COPT_NO_HIDE;
 }
Member Function Documentation
_convert()
template<typename T > std::optional< T > options_manager::cOpt::_convert () const private
Definition at line 773 of file options.cpp.
 {
     if constexpr( std::is_same_v<T, std::string> ) {
         return getValue( true );
     } else {
         if( eType == CVT_BOOL ) {
             return static_cast<T>( bSet );
         } else if( eType == CVT_FLOAT ) {
             return static_cast<T>( fSet );
         } else if( eType == CVT_INT ) {
             return static_cast<T>( iSet );
         }
     }
     return std::nullopt;
 }
checkPrerequisite()
bool options_manager::cOpt::checkPrerequisite () const
Definition at line 645 of file options.cpp.
 {
     if( !hasPrerequisite() ) {
         return true;
     }
     bool isPrerequisiteFulfilled = false;
     const std::string prerequisite_option_value = get_options().get_option( sPrerequisite ).getValue();
     for( const std::string &sAllowedPrerequisiteValue : sPrerequisiteAllowedValues ) {
         if( prerequisite_option_value == sAllowedPrerequisiteValue ) {
             isPrerequisiteFulfilled = true;
             break;
         }
     }
     return isPrerequisiteFulfilled;
 }
References options_manager::get_option(), get_options(), and getValue().
Referenced by options_manager::show().
findInt()
std::optional< options_manager::int_and_option > options_manager::cOpt::findInt (int iSearch) const
Definition at line 937 of file options.cpp.
 {
     int i = static_cast<int>( getIntPos( iSearch ) );
     if( i == -1 ) {
         return std::nullopt;
     }
     return mIntValues[i];
 }
Referenced by options_manager::add().
getDefaultText()
std::string options_manager::cOpt::getDefaultText (bool bTranslated = true) const
Definition at line 865 of file options.cpp.
 {
     if( sType == "string_select" ) {
         const auto iter = std::find_if( vItems.begin(), vItems.end(),
         [this]( const id_and_option & elem ) {
             return elem.first == sDefault;
         } );
         const std::string defaultName = iter == vItems.end() ? std::string() :
                                         bTranslated ? iter->second.translated() : iter->first;
         const std::string &sItems = enumerate_as_string( vItems.begin(), vItems.end(),
         [bTranslated]( const id_and_option & elem ) {
             return bTranslated ? elem.second.translated() : elem.first;
         }, enumeration_conjunction::none );
         return string_format( _( "Default: %s - Values: %s" ), defaultName, sItems );
     } else if( sType == "string_input" ) {
         return string_format( _( "Default: %s" ), sDefault );
     } else if( sType == "bool" ) {
         return bDefault ? _( "Default: True" ) : _( "Default: False" );
     } else if( sType == "int" ) {
         return string_format( _( "Default: %d - Min: %d, Max: %d" ), iDefault, iMin, iMax );
     } else if( sType == "int_map" ) {
         const std::optional<int_and_option> opt = findInt( iDefault );
         if( opt ) {
             if( verbose ) {
                 return string_format( _( "Default: %d: %s" ), iDefault, opt->second );
             } else {
                 return string_format( _( "Default: %s" ), opt->second );
             }
         }
     } else if( sType == "float" ) {
         return string_format( _( "Default: %.2f - Min: %.2f, Max: %.2f" ), fDefault, fMin, fMax );
     }
     return "";
 }
References _, enumerate_as_string(), none, and string_format().
Referenced by options_manager::PageItem::fmt_tooltip(), and options_manager::serialize().
getIntPos()
int options_manager::cOpt::getIntPos (int iSearch) const
Definition at line 924 of file options.cpp.
 {
     if( sType == "int_map" ) {
         for( size_t i = 0; i < mIntValues.size(); i++ ) {
             if( mIntValues[i].first == iSearch ) {
                 return i;
             }
         }
     }
     return -1;
 }
getItemPos()
int options_manager::cOpt::getItemPos (const std::string & sSearch) const
Definition at line 906 of file options.cpp.
 {
     if( sType == "string_select" ) {
         for( size_t i = 0; i < vItems.size(); i++ ) {
             if( vItems[i].first == sSearch ) {
                 return i;
             }
         }
     }
     return -1;
 }
Referenced by options_manager::add().
getItems()
std::vector< options_manager::id_and_option > options_manager::cOpt::getItems () const
Definition at line 919 of file options.cpp.
 {
     return vItems;
 }
Referenced by anonymous_namespace{system_locale.cpp}::matchGameLanguage().
getMaxLength()
int options_manager::cOpt::getMaxLength () const
Definition at line 947 of file options.cpp.
 {
     if( sType == "string_input" ) {
         return iMaxLength;
     }
     return 0;
 }
getMenuText()
std::string options_manager::cOpt::getMenuText () const
The translated displayed option name.
Definition at line 714 of file options.cpp.
 {
     return sMenuText.translated();
 }
Referenced by options_manager::show().
getName()
std::string options_manager::cOpt::getName () const
Definition at line 704 of file options.cpp.
 {
     return sName;
 }
Referenced by options_manager::serialize(), and options_manager::show().
getPage()
std::string options_manager::cOpt::getPage () const
Definition at line 709 of file options.cpp.
 {
     return sPage;
 }
Referenced by WORLD::load_options().
getPrerequisite()
std::string options_manager::cOpt::getPrerequisite () const
Definition at line 635 of file options.cpp.
 {
     return sPrerequisite;
 }
Referenced by options_manager::show().
getPrerequisiteSupportedTypes()
static std::vector<std::string> options_manager::cOpt::getPrerequisiteSupportedTypes () inline static
Definition at line 130 of file options.h.
{
                     return { "bool", "string", "string_select", "string_input" };
                 }
getTooltip()
std::string options_manager::cOpt::getTooltip () const
The translated displayed option tool tip.
Definition at line 719 of file options.cpp.
 {
     return sTooltip.translated();
 }
Referenced by options_manager::PageItem::fmt_tooltip(), and options_manager::serialize().
getType()
std::string options_manager::cOpt::getType () const
Definition at line 724 of file options.cpp.
 {
     return sType;
 }
Referenced by setPrerequisites(), and options_manager::show().
getValue()
std::string options_manager::cOpt::getValue (bool classis_locale = false) const
Definition at line 749 of file options.cpp.
 {
     if( sType == "string_select" || sType == "string_input" ) {
         return sSet;
     } else if( sType == "bool" ) {
         return bSet ? "true" : "false";
     } else if( sType == "int" || sType == "int_map" ) {
         return string_format( format, iSet );
     } else if( sType == "float" ) {
         std::ostringstream ssTemp;
         ssTemp.imbue( classis_locale ? std::locale::classic() : std::locale() );
         ssTemp.precision( 2 );
         ssTemp.setf( std::ios::fixed, std::ios::floatfield );
         ssTemp << fSet;
         return ssTemp.str();
     }
     return "";
 }
References string_format().
Referenced by checkPrerequisite(), options_manager::serialize(), and options_manager::show().
getValueName()
std::string options_manager::cOpt::getValueName () const
The translated currently selected option value.
Definition at line 837 of file options.cpp.
 {
     if( sType == "string_select" ) {
         const auto iter = std::find_if( vItems.begin(),
         vItems.end(), [&]( const id_and_option & e ) {
             return e.first == sSet;
         } );
         if( iter != vItems.end() ) {
             return iter->second.translated();
         }
     } else if( sType == "bool" ) {
         return bSet ? _( "True" ) : _( "False" );
     } else if( sType == "int_map" ) {
         const std::optional<int_and_option> opt = findInt( iSet );
         if( opt ) {
             if( verbose ) {
                 return string_format( _( "%d: %s" ), iSet, opt->second );
             } else {
                 return opt->second.translated();
             }
         }
     }
     return getValue();
 }
References _, and string_format().
Referenced by options_manager::show().
hasPrerequisite()
bool options_manager::cOpt::hasPrerequisite () const
Definition at line 640 of file options.cpp.
 {
     return !sPrerequisite.empty();
 }
Referenced by options_manager::show().
is_hidden()
bool options_manager::cOpt::is_hidden () const
Option should be hidden in current build.
Returns
true if option should be hidden, false if not.
Definition at line 662 of file options.cpp.
 {
     switch( hide ) {
         case COPT_NO_HIDE: // NOLINT(bugprone-branch-clone)
             return false;
         case COPT_SDL_HIDE:
 #if defined(TILES)
             return true;
 #else
             return false;
 #endif
         case COPT_CURSES_HIDE: // NOLINT(bugprone-branch-clone)
 #if !defined(TILES) // If not defined, it's the curses interface.
             return true;
 #else
             return false;
 #endif
         case COPT_POSIX_CURSES_HIDE:
             // Check if we on windows and using wincurses.
 #if defined(TILES) || defined(_WIN32)
             return false;
 #else
             return true;
 #endif
         case COPT_NO_SOUND_HIDE:
 #if !defined(SDL_SOUND) // If not defined, we have no sound support.
             return true;
 #else
             return false;
 #endif
         case COPT_ALWAYS_HIDE:
             return true;
     }
     // Make compiler happy, this is unreachable.
     return false;
 }
Referenced by options_manager::Page::removeRepeatedEmptyLines().
operator!=()
bool options_manager::cOpt::operator!= (const cOpt & rhs) const inline
Definition at line 126 of file options.h.
{
                     return !operator==( rhs );
                 }
References operator==().
operator==()
bool options_manager::cOpt::operator== (const cOpt & rhs) const
Definition at line 729 of file options.cpp.
 {
     if( sType != rhs.sType ) {
         return false;
     } else if( sType == "string_select" || sType == "string_input" ) {
         return sSet == rhs.sSet;
     } else if( sType == "bool" ) {
         return bSet == rhs.bSet;
     } else if( sType == "int" || sType == "int_map" ) {
         return iSet == rhs.iSet;
     } else if( sType == "float" ) {
         return fSet == rhs.fSet;
     } else if( sType == "VOID" ) {
         return true;
     } else {
         debugmsg( "unknown option type %s", sType );
         return false;
     }
 }
References bSet, debugmsg, fSet, iSet, sSet, and sType.
Referenced by operator!=().
setNext()
void options_manager::cOpt::setNext ()
Definition at line 957 of file options.cpp.
 {
     if( sType == "string_select" ) {
         int iNext = getItemPos( sSet ) + 1;
         if( iNext >= static_cast<int>( vItems.size() ) ) {
             iNext = 0;
         }
         sSet = vItems[iNext].first;
     } else if( sType == "string_input" ) {
         int iMenuTextLength = utf8_width( sMenuText.translated() );
         string_input_popup()
         .width( iMaxLength > 80 ? 80 : iMaxLength < iMenuTextLength ? iMenuTextLength : iMaxLength + 1 )
         .title( sMenuText.translated() )
         .max_length( iMaxLength )
         .edit( sSet );
     } else if( sType == "bool" ) {
         bSet = !bSet;
     } else if( sType == "int" ) {
         iSet++;
         if( iSet > iMax ) {
             iSet = iMin;
         }
     } else if( sType == "int_map" ) {
         unsigned int iNext = getIntPos( iSet ) + 1;
         if( iNext >= mIntValues.size() ) {
             iNext = 0;
         }
         iSet = mIntValues[iNext].first;
     } else if( sType == "float" ) {
         fSet += fStep;
         if( fSet > fMax ) {
             fSet = fMin;
         }
     }
 }
References string_input_popup::edit(), string_input_popup::max_length(), string_input_popup::title(), utf8_width(), and string_input_popup::width().
Referenced by auto_pickup::player_settings::add_rule(), safemode::add_rule(), game::do_regular_action(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), options_manager::show(), and safemode::show().
setPrerequisite()
void options_manager::cOpt::setPrerequisite (const std::string & sOption, const std::string & sAllowedValue = "true") inline
Definition at line 135 of file options.h.
{
                     setPrerequisites( sOption, { sAllowedValue } );
                 }
References setPrerequisites().
setPrerequisites()
void options_manager::cOpt::setPrerequisites (const std::string & sOption, const std::vector< std::string > & sAllowedValues)
Definition at line 607 of file options.cpp.
 {
     const bool hasOption = get_options().has_option( sOption );
     if( !hasOption ) {
         debugmsg( "setPrerequisite: unknown option %s", sType );
         return;
     }
     const cOpt &existingOption = get_options().get_option( sOption );
     const std::string &existingOptionType = existingOption.getType();
     bool isOfSupportType = false;
     for( const std::string &sSupportedType : getPrerequisiteSupportedTypes() ) {
         if( existingOptionType == sSupportedType ) {
             isOfSupportType = true;
             break;
         }
     }
     if( !isOfSupportType ) {
         debugmsg( "setPrerequisite: option %s not of supported type", sType );
         return;
     }
     sPrerequisite = sOption;
     sPrerequisiteAllowedValues = sAllowedValues;
 }
References debugmsg, options_manager::get_option(), get_options(), getType(), and options_manager::has_option().
Referenced by setPrerequisite().
setPrev()
void options_manager::cOpt::setPrev ()
Definition at line 1000 of file options.cpp.
 {
     if( sType == "string_select" ) {
         int iPrev = static_cast<int>( getItemPos( sSet ) ) - 1;
         if( iPrev < 0 ) {
             iPrev = vItems.size() - 1;
         }
         sSet = vItems[iPrev].first;
     } else if( sType == "string_input" ) {
         setNext();
     } else if( sType == "bool" ) {
         bSet = !bSet;
     } else if( sType == "int" ) {
         iSet--;
         if( iSet < iMin ) {
             iSet = iMax;
         }
     } else if( sType == "int_map" ) {
         int iPrev = static_cast<int>( getIntPos( iSet ) ) - 1;
         if( iPrev < 0 ) {
             iPrev = mIntValues.size() - 1;
         }
         iSet = mIntValues[iPrev].first;
     } else if( sType == "float" ) {
         fSet -= fStep;
         if( fSet < fMin ) {
             fSet = fMax;
         }
     }
 }
Referenced by options_manager::show().
setValue() [1/3]
void options_manager::cOpt::setValue (const std::string & sSetIn)
Definition at line 1064 of file options.cpp.
 {
     if( sType == "string_select" ) {
         if( getItemPos( sSetIn ) != -1 ) {
             sSet = sSetIn;
         }
     } else if( sType == "string_input" ) {
         sSet = iMaxLength > 0 ? sSetIn.substr( 0, iMaxLength ) : sSetIn;
     } else if( sType == "bool" ) {
         bSet = sSetIn == "True" || sSetIn == "true" || sSetIn == "T" || sSetIn == "t";
     } else if( sType == "int" ) {
         // Some integer values are stored with a '%', e.g. "100%".
         std::string without_percent = sSetIn;
         if( string_ends_with( without_percent, "%" ) ) {
             without_percent.erase( without_percent.end() - 1 );
         }
         ret_val<int> val = try_parse_integer<int>( without_percent, false );
         if( val.success() ) {
             iSet = val.value();
             if( iSet < iMin || iSet > iMax ) {
                 iSet = iDefault;
             }
         } else {
             debugmsg( "Error parsing option as integer: %s", val.str() );
             iSet = iDefault;
         }
     } else if( sType == "int_map" ) {
         ret_val<int> val = try_parse_integer<int>( sSetIn, false );
         if( val.success() ) {
             iSet = val.value();
             auto item = findInt( iSet );
             if( !item ) {
                 iSet = iDefault;
             }
         } else {
             debugmsg( "Error parsing option as integer: %s", val.str() );
             iSet = iDefault;
         }
     } else if( sType == "float" ) {
         std::istringstream ssTemp( sSetIn );
         ssTemp.imbue( std::locale::classic() );
         float tmpFloat;
         ssTemp >> tmpFloat;
         if( ssTemp ) {
             setValue( tmpFloat );
         } else {
             debugmsg( "invalid floating point option: %s", sSetIn );
         }
     }
 }
References debugmsg, ret_val_common::str(), string_ends_with(), ret_val_common::success(), try_parse_integer< int >(), and ret_val< T >::value().
Referenced by game_ui::init_ui(), load_external_option(), load_world_option(), main(), options_manager::show(), and safemode::show().
setValue() [2/3]
void options_manager::cOpt::setValue (float fSetIn)
Definition at line 1038 of file options.cpp.
 {
     if( sType != "float" ) {
         debugmsg( "tried to set a float value to a %s option", sType );
         return;
     }
     fSet = fSetIn;
     if( fSet < fMin || fSet > fMax ) {
         fSet = fDefault;
     }
 }
References debugmsg.
setValue() [3/3]
void options_manager::cOpt::setValue (int iSetIn)
Definition at line 1051 of file options.cpp.
 {
     if( sType != "int" ) {
         debugmsg( "tried to set an int value to a %s option", sType );
         return;
     }
     iSet = iSetIn;
     if( iSet < iMin || iSet > iMax ) {
         iSet = iDefault;
     }
 }
References debugmsg.
value_as() [1/2]
int options_manager::cOpt::value_as< int > (bool convert) const
Definition at line 802 of file options.cpp.
 {
     if( std::optional<bool> ret = _convert<bool>(); convert && ret ) {
         return *ret;
     }
     if( eType != CVT_BOOL ) {
         debugmsg( "%s tried to get boolean value from option of type %s", sName, sType );
     }
     return bSet;
 }
References cata::convert(), debugmsg, and cata::hash64_detail::ret.
value_as() [2/2]
template<typename T > T options_manager::cOpt::value_as (bool convert = false) const
Referenced by game::do_regular_action(), get_option(), and safemode::show().
Friends And Related Function Documentation
options_manager
friend class options_manager friend
Definition at line 82 of file options.h.
Member Data Documentation
bDefault
bool options_manager::cOpt::bDefault = false private
Definition at line 179 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
bSet
bool options_manager::cOpt::bSet = false private
Definition at line 178 of file options.h.
Referenced by options_manager::add(), options_manager::add_external(), and operator==().
eType
COPT_VALUE_TYPE options_manager::cOpt::eType private
Definition at line 168 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
fDefault
float options_manager::cOpt::fDefault = 0.0f private
Definition at line 192 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
fMax
float options_manager::cOpt::fMax = 0.0f private
Definition at line 191 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
fMin
float options_manager::cOpt::fMin = 0.0f private
Definition at line 190 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
format
std::string options_manager::cOpt::format private
Definition at line 161 of file options.h.
Referenced by options_manager::add().
fSet
float options_manager::cOpt::fSet = 0.0f private
Definition at line 189 of file options.h.
Referenced by options_manager::add(), options_manager::add_external(), and operator==().
fStep
float options_manager::cOpt::fStep = 0.0f private
Definition at line 193 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
hide
copt_hide_t options_manager::cOpt::hide private
Definition at line 166 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
iDefault
int options_manager::cOpt::iDefault = 0 private
Definition at line 185 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
iMax
int options_manager::cOpt::iMax = 0 private
Definition at line 184 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
iMaxLength
int options_manager::cOpt::iMaxLength = 0 private
Definition at line 175 of file options.h.
Referenced by options_manager::add().
iMin
int options_manager::cOpt::iMin = 0 private
Definition at line 183 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
iSet
int options_manager::cOpt::iSet = 0 private
Definition at line 182 of file options.h.
Referenced by options_manager::add(), options_manager::add_external(), and operator==().
mIntValues
std::vector<int_and_option> options_manager::cOpt::mIntValues private
Definition at line 186 of file options.h.
Referenced by options_manager::add().
sDefault
std::string options_manager::cOpt::sDefault private
Definition at line 173 of file options.h.
Referenced by options_manager::add().
sMenuText
translation options_manager::cOpt::sMenuText private
Definition at line 155 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
sName
std::string options_manager::cOpt::sName private
Definition at line 152 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
sPage
std::string options_manager::cOpt::sPage private
Definition at line 153 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
sPrerequisite
std::string options_manager::cOpt::sPrerequisite private
Definition at line 163 of file options.h.
sPrerequisiteAllowedValues
std::vector<std::string> options_manager::cOpt::sPrerequisiteAllowedValues private
Definition at line 164 of file options.h.
sSet
std::string options_manager::cOpt::sSet private
Definition at line 171 of file options.h.
Referenced by options_manager::add(), and operator==().
sTooltip
translation options_manager::cOpt::sTooltip private
Definition at line 157 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
sType
std::string options_manager::cOpt::sType private
Definition at line 158 of file options.h.
Referenced by options_manager::add(), options_manager::add_external(), and operator==().
verbose
bool options_manager::cOpt::verbose = false private
Definition at line 159 of file options.h.
Referenced by options_manager::add(), and options_manager::add_external().
vItems
std::vector<id_and_option> options_manager::cOpt::vItems private
Definition at line 172 of file options.h.
Referenced by options_manager::add().
The documentation for this class was generated from the following files:
src/options.h
src/options.cpp