Cataclysm DDA: mapgen_parameter Class Reference
mapgen_parameter Class Reference
#include <mapgen_parameter.h>
Public Member Functions
mapgen_parameter ()
mapgen_parameter (const mapgen_value< std::string > &def, cata_variant_type, mapgen_parameter_scope)
void deserialize (const JsonObject &jo)
mapgen_parameter_scope scope () const
cata_variant_type type () const
cata_variant get (const mapgendata &) const
std::vector< std::string > all_possible_values (const mapgen_parameters &) const
void check (const mapgen_parameters &, const std::string &context) const
void check_consistent_with (const mapgen_parameter &, const std::string &context) const
Private Attributes
mapgen_parameter_scope scope_
cata_variant_type type_
shared_ptr_fast< const mapgen_value< std::string > > default_
Detailed Description
Definition at line 30 of file mapgen_parameter.h.
Constructor & Destructor Documentation
mapgen_parameter() [1/2]
mapgen_parameter::mapgen_parameter () default
mapgen_parameter() [2/2]
mapgen_parameter::mapgen_parameter (const mapgen_value< std::string > & def, cata_variant_type type, mapgen_parameter_scope scope)
Definition at line 1620 of file mapgen.cpp.
     : scope_( scope )
     , type_( type )
     , default_( make_shared_fast<mapgen_value<std::string>>( def ) )
 {}
References default_, and string.
Member Function Documentation
all_possible_values()
std::vector< std::string > mapgen_parameter::all_possible_values (const mapgen_parameters & params) const
Definition at line 1644 of file mapgen.cpp.
 {
     return default_->all_possible_results( params );
 }
References default_.
Referenced by mapgen_value< Id >::param_source::all_possible_results(), check(), start_location::set_parameters(), and overmap_ui::set_special_args().
check()
void mapgen_parameter::check (const mapgen_parameters & params, const std::string & context) const
Definition at line 1650 of file mapgen.cpp.
 {
     default_->check( context, params );
     for( const std::string &value : all_possible_values( params ) ) {
         if( !cata_variant::from_string( type_, std::string( value ) ).is_valid() ) {
             debugmsg( "%s can take value %s which is not a valid value of type %s",
                       context, value, io::enum_to_string( type_ ) );
         }
     }
 }
References all_possible_values(), context, debugmsg, default_, io::enum_to_string(), cata_variant::from_string(), and type_.
check_consistent_with()
void mapgen_parameter::check_consistent_with (const mapgen_parameter & other, const std::string & context) const
Definition at line 1661 of file mapgen.cpp.
 {
     if( scope_ != other.scope_ ) {
         debugmsg( "mismatched scope for mapgen parameters %s (%s vs %s)",
                   context, io::enum_to_string( scope_ ), io::enum_to_string( other.scope_ ) );
     }
     if( type_ != other.type_ ) {
         debugmsg( "mismatched type for mapgen parameters %s (%s vs %s)",
                   context, io::enum_to_string( type_ ), io::enum_to_string( other.type_ ) );
     }
     default_->check_consistent_with( *other.default_, context );
 }
References context, debugmsg, default_, io::enum_to_string(), other, scope_, and type_.
Referenced by mapgen_parameters::check_and_merge().
deserialize()
void mapgen_parameter::deserialize (const JsonObject & jo)
Definition at line 1627 of file mapgen.cpp.
 {
     optional( jo, false, "scope", scope_, mapgen_parameter_scope::overmap_special );
     jo.read( "type", type_, true );
     default_ = make_shared_fast<mapgen_value<std::string>>( jo.get_member( "default" ) );
 }
References default_, JsonObject::get_member(), optional(), overmap_special, JsonObject::read(), scope_, and type_.
get()
cata_variant mapgen_parameter::get (const mapgendata & md) const
Definition at line 1639 of file mapgen.cpp.
 {
     return cata_variant::from_string( type_, default_->get( md ) );
 }
References default_, cata_variant::from_string(), and type_.
Referenced by mapgen_parameters::get_args().
scope()
mapgen_parameter_scope mapgen_parameter::scope () const inline
Definition at line 39 of file mapgen_parameter.h.
{
             return scope_;
         }
References scope_.
Referenced by mapgen_value< Id >::param_source::check(), mapgen_parameters::check_and_merge(), mapgen_parameters::get_args(), mapgen_parameters::params_for_scope(), and start_location::set_parameters().
type()
cata_variant_type mapgen_parameter::type () const
Definition at line 1634 of file mapgen.cpp.
 {
     return type_;
 }
References type_.
Referenced by calculate_all_blueprint_reqs(), mapgen_value< Id >::param_source::check(), start_location::set_parameters(), and overmap_ui::set_special_args().
Member Data Documentation
default_
shared_ptr_fast<const mapgen_value<std::string> > mapgen_parameter::default_ private
Definition at line 53 of file mapgen_parameter.h.
Referenced by all_possible_values(), check(), check_consistent_with(), deserialize(), and get().
scope_
mapgen_parameter_scope mapgen_parameter::scope_ private
Definition at line 49 of file mapgen_parameter.h.
Referenced by check_consistent_with(), deserialize(), and scope().
type_
cata_variant_type mapgen_parameter::type_ private
Definition at line 50 of file mapgen_parameter.h.
Referenced by check(), check_consistent_with(), deserialize(), get(), and type().
The documentation for this class was generated from the following files:
src/mapgen_parameter.h
src/mapgen.cpp