Cataclysm DDA: jmapgen_vehicle Class Reference
jmapgen_vehicle Class Reference
Place a vehicle.
Public Member Functions
jmapgen_vehicle (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
void check (const std::string &context, const mapgen_parameters &parameters, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
Public Attributes
mapgen_value< vgroup_id > type
jmapgen_int chance
std::vector< units::angle > rotation
int fuel
int status
std::string faction
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a vehicle.
"vehicle": id of the vehicle. "chance": chance of spawning the vehicle: 0...100 "rotation": rotation of the vehicle, see fuel: fuel status of the vehicle, see status: overall (damage) status of the vehicle, see vehicle::vehicle
Definition at line 2581 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_vehicle()
jmapgen_vehicle::jmapgen_vehicle (const JsonObject & jsi, const std::string_view) inline
Definition at line 2590 of file mapgen.cpp.
                                                                         :
             type( jsi.get_member( "vehicle" ) )
             , chance( jsi, "chance", 1, 1 )
             //, rotation( jsi.get_int( "rotation", 0 ) ) // unless there is a way for the json parser to
             // return a single int as a list, we have to manually check this in the constructor below
             , fuel( jsi.get_int( "fuel", -1 ) )
             , status( jsi.get_int( "status", -1 ) ) {
             if( jsi.has_array( "rotation" ) ) {
                 for( const JsonValue elt : jsi.get_array( "rotation" ) ) {
                     rotation.push_back( units::from_degrees( elt.get_int() ) );
                 }
             } else {
                 rotation.push_back( units::from_degrees( jsi.get_int( "rotation", 0 ) ) );
             }
             if( jsi.has_string( "faction" ) ) {
                 faction = jsi.get_string( "faction" );
             }
         }
References units::from_degrees(), JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), mapgen_defer::jsi, and rotation.
Member Function Documentation
apply()
void jmapgen_vehicle::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2609 of file mapgen.cpp.
{
             if( !x_in_y( chance.get(), 100 ) ) {
                 return;
             }
             vgroup_id chosen_id = type.get( dat );
             if( chosen_id.is_null() ) {
                 return;
             }
             tripoint const dst( x.get(), y.get(), dat.zlevel() + z.get() );
             vehicle *veh = dat.m.add_vehicle( chosen_id->pick(), dst, random_entry( rotation ),
                                               fuel, status );
             if( veh && !faction.empty() ) {
                 veh->set_owner( faction_id( faction ) );
             }
             if( get_map().inbounds( dat.m.getglobal( dst ) ) ) {
                 dat.m.queue_main_cleanup();
             }
         }
References map::add_vehicle(), chance, faction_id, fuel, jmapgen_int::get(), get_map(), map::getglobal(), string_id< T >::is_null(), mapgendata::m, VehicleGroup::pick(), map::queue_main_cleanup(), random_entry(), rotation, vehicle::set_owner(), status, type, x_in_y(), and mapgendata::zlevel().
check()
void jmapgen_vehicle::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 2632 of file mapgen.cpp.
{
             type.check( context, parameters );
             if( x.val == -1 ) {
                 // We are in a palette, so no need to verify that the positions
                 // are valid
                 return;
             }
             // The rest of this function is devoted to ensuring that this
             // vehicle placement does not lead to a vehicle overlapping an OMT
             // boundary, because that causes issues (e.g. if the vehicle is
             // damaged and tries to drop items during mapgen, they may drop on
             // points outside the map).
             point min( INT_MAX, INT_MAX );
             point max( INT_MIN, INT_MIN );
             vgroup_id min_x_vg;
             vproto_id min_x_vp;
             vgroup_id max_x_vg;
             vproto_id max_x_vp;
             vgroup_id min_y_vg;
             vproto_id min_y_vp;
             vgroup_id max_y_vg;
             vproto_id max_y_vp;
             for( const vgroup_id &vg_id : type.all_possible_results( parameters ) ) {
                 for( const vproto_id &vp_id : vg_id->all_possible_results() ) {
                     inclusive_rectangle<point> bounds = vehicle_bounds( *vp_id );
                     if( bounds.p_min.x < min.x ) {
                         min_x_vg = vg_id;
                         min_x_vp = vp_id;
                         min.x = bounds.p_min.x;
                     }
                     if( bounds.p_max.x > max.x ) {
                         max_x_vg = vg_id;
                         max_x_vp = vp_id;
                         max.x = bounds.p_max.x;
                     }
                     if( bounds.p_min.y < min.y ) {
                         min_y_vg = vg_id;
                         min_y_vp = vp_id;
                         min.y = bounds.p_min.y;
                     }
                     if( bounds.p_max.y > max.y ) {
                         max_y_vg = vg_id;
                         max_y_vp = vp_id;
                         max.y = bounds.p_max.y;
                     }
                 }
             }
             for( units::angle rot : rotation ) {
                 int degrees = to_degrees( rot );
                 while( degrees < 0 ) {
                     degrees += 360;
                 }
                 if( degrees % 90 != 0 ) {
                     // TODO: support non-rectilinear vehicle placement
                     continue;
                 }
                 int turns = degrees / 90;
                 point rotated_min = min.rotate( turns );
                 point rotated_max = max.rotate( turns );
                 point new_min( std::min( rotated_min.x, rotated_max.x ),
                                std::min( rotated_min.y, rotated_max.y ) );
                 point new_max( std::max( rotated_min.x, rotated_max.x ),
                                std::max( rotated_min.y, rotated_max.y ) );
                 new_min += point( x.val, y.val );
                 new_max += point( x.valmax, y.valmax );
                 cube_direction bad_rotated_direction = cube_direction::last;
                 std::string extreme_coord;
                 if( new_min.x < 0 ) {
                     bad_rotated_direction = cube_direction::west;
                     extreme_coord = string_format( "x = %d (should be at least 0)", new_min.x );
                 } else if( new_max.x >= 24 ) {
                     bad_rotated_direction = cube_direction::east;
                     extreme_coord = string_format( "x = %d (should be at most 23)", new_max.x );
                 } else if( new_min.y < 0 ) {
                     extreme_coord = string_format( "y = %d (should be at least 0)", new_min.y );
                     bad_rotated_direction = cube_direction::north;
                 } else if( new_max.y >= 24 ) {
                     bad_rotated_direction = cube_direction::south;
                     extreme_coord = string_format( "y = %d (should be at most 23)", new_max.y );
                 } else {
                     continue;
                 }
                 cube_direction bad_direction = bad_rotated_direction - turns;
                 std::string bad_vehicle;
                 auto format_option = []( const vgroup_id & vg, const vproto_id & vp ) {
                     return string_format(
                                "[vgroup_id %s; vproto_id %s]", vg.str(), vp.str() );
                 };
                 switch( bad_direction ) {
                     case cube_direction::north:
                         bad_vehicle = format_option( min_y_vg, min_y_vp );
                         break;
                     case cube_direction::south:
                         bad_vehicle = format_option( max_y_vg, max_y_vp );
                         break;
                     case cube_direction::east:
                         bad_vehicle = format_option( max_x_vg, max_x_vp );
                         break;
                     case cube_direction::west:
                         bad_vehicle = format_option( min_x_vg, min_x_vp );
                         break;
                     default:
                         cata_fatal( "Invalid bad_direction %d", bad_direction );
                 }
                 debugmsg( "In %s, vehicle placement at x:[%d,%d], y:[%d,%d]: "
                           "potential placement of vehicle out of bounds.  "
                           "At rotation %d the vehicle %s extends too far %s, "
                           "reaching coordinate %s",
                           context, x.val, x.valmax, y.val, y.valmax, degrees,
                           bad_vehicle, io::enum_to_string( bad_rotated_direction ),
                           extreme_coord );
                 // Early exit because we don't want too much error spam
                 // from the same mapgen piece
                 return;
             }
         }
References cata_fatal, context, debugmsg, east, io::enum_to_string(), last, max(), min(), north, inclusive_rectangle< Point, >::p_max, inclusive_rectangle< Point, >::p_min, point, rotation, south, string_id< T >::str(), string_format(), units::to_degrees(), type, jmapgen_int::val, jmapgen_int::valmax, vehicle_bounds(), west, point::x, and point::y.
has_vehicle_collision()
bool jmapgen_vehicle::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2628 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint_bub_ms( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
Member Data Documentation
chance
jmapgen_int jmapgen_vehicle::chance
Definition at line 2585 of file mapgen.cpp.
Referenced by apply().
faction
std::string jmapgen_vehicle::faction
Definition at line 2589 of file mapgen.cpp.
fuel
int jmapgen_vehicle::fuel
Definition at line 2587 of file mapgen.cpp.
Referenced by apply().
rotation
std::vector<units::angle> jmapgen_vehicle::rotation
Definition at line 2586 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_vehicle().
status
int jmapgen_vehicle::status
Definition at line 2588 of file mapgen.cpp.
Referenced by apply().
type
mapgen_value<vgroup_id> jmapgen_vehicle::type
Definition at line 2584 of file mapgen.cpp.
Referenced by apply(), and check().
The documentation for this class was generated from the following file:
src/mapgen.cpp