Cataclysm DDA: move_mode Class Reference
move_mode Class Reference
#include <move_mode.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
move_mode ()=default
std::string name () const
std::string change_message (bool success, steed_type steed) const
move_mode_id cycle () const
move_mode_id cycle_reverse () const
move_mode_id ident () const
float sound_mult () const
float stamina_mult () const
float exertion_level () const
float move_speed_mult () const
units::energy mech_power_use () const
int swim_speed_mod () const
nc_color panel_color () const
nc_color symbol_color () const
char panel_letter () const
char letter () const
bool stop_hauling () const
move_mode_type type () const
void set_cycle (const move_mode_id &mode) const
void set_cycle_back (const move_mode_id &mode) const
Static Public Member Functions
static void load_move_mode (const JsonObject &jo, const std::string &src)
static void finalize ()
static void reset ()
Private Attributes
bool was_loaded = false
move_mode_id id
std::vector< std::pair< move_mode_id, mod_id > > src
std::map< steed_type, translation > change_messages_success
std::map< steed_type, translation > change_messages_fail
bool _stop_hauling = false
move_mode_id cycle_to
move_mode_id cycle_back
move_mode_type _type = move_mode_type::WALKING
float _exertion_level = 0.0f
float _move_speed_mult = 0.0f
float _sound_multiplier = 0.0f
float _stamina_multiplier = 0.0f
int _mech_power_use = 0
int _swim_speed_mod = 0
nc_color _panel_color
nc_color _symbol_color
uint32_t _panel_letter
uint32_t _letter
translation _name
Friends
class generic_factory< move_mode >
struct mod_tracker
Detailed Description
Definition at line 33 of file move_mode.h.
Constructor & Destructor Documentation
move_mode()
move_mode::move_mode () default
Member Function Documentation
change_message()
std::string move_mode::change_message (bool success, steed_type steed) const
Definition at line 132 of file move_mode.cpp.
 {
     if( steed == steed_type::NUM ) {
         debugmsg( "Attempted to switch to bad movement mode!" );
         //~ This should never occur - this is the message when the character switches to
         //~ an invalid move mode or there's not a message for failing to switch to a move
         //~ mode
         return _( "You feel bugs crawl over your skin." );
     }
     if( success ) {
         return change_messages_success.at( steed ).translated();
     }
     return change_messages_fail.at( steed ).translated();
 }
References _, change_messages_fail, change_messages_success, debugmsg, and NUM.
Referenced by avatar::set_movement_mode().
cycle()
move_mode_id move_mode::cycle () const
Definition at line 149 of file move_mode.cpp.
 {
     return cycle_to;
 }
References cycle_to.
Referenced by avatar::cycle_move_mode(), and open_movement_mode_menu().
cycle_reverse()
move_mode_id move_mode::cycle_reverse () const
Definition at line 154 of file move_mode.cpp.
 {
     return cycle_back;
 }
References cycle_back.
Referenced by avatar::cycle_move_mode_reverse().
exertion_level()
float move_mode::exertion_level () const
Definition at line 174 of file move_mode.cpp.
 {
     return _exertion_level;
 }
References _exertion_level.
Referenced by avatar_action::move().
finalize()
void move_mode::finalize () static
Definition at line 93 of file move_mode.cpp.
 {
     for( const move_mode &mode : move_mode_factory.get_all() ) {
         move_modes_sorted.emplace_back( mode.ident() );
     }
     // Sort it fastest to slowest
     auto stamina_sorter = [&]( const move_mode_id & lhs, const move_mode_id & rhs ) {
         return lhs->move_speed_mult() < rhs->move_speed_mult();
     };
     std::sort( move_modes_sorted.begin(), move_modes_sorted.end(), stamina_sorter );
     // Cycle to the move mode above ours
     for( size_t i = move_modes_sorted.size(); i > 0; --i ) {
         const move_mode &curr = *move_modes_sorted[i - 1];
         if( i == move_modes_sorted.size() ) {
             curr.set_cycle( move_modes_sorted[0] );
         } else {
             curr.set_cycle( move_modes_sorted[i] );
         }
     }
     // Cycle to the move mode below ours
     for( size_t i = move_modes_sorted.size(); i > 0; --i ) {
         const move_mode &curr = *move_modes_sorted[i - 1];
         if( i == 1 ) {
             curr.set_cycle_back( move_modes_sorted.back() );
         } else {
             curr.set_cycle_back( move_modes_sorted[i - 2] );
         }
     }
 }
References anonymous_namespace{move_mode.cpp}::move_mode_factory, move_modes_sorted, move_speed_mult(), set_cycle(), and set_cycle_back().
Referenced by DynamicDataLoader::finalize_loaded_data().
ident()
move_mode_id move_mode::ident () const
Definition at line 159 of file move_mode.cpp.
 {
     return id;
 }
References id.
letter()
char move_mode::letter () const
Definition at line 209 of file move_mode.cpp.
 {
     return _letter;
 }
References _letter.
Referenced by open_movement_mode_menu().
load()
void move_mode::load (const JsonObject & jo, std::string_view src)
Definition at line 50 of file move_mode.cpp.
 {
     mandatory( jo, was_loaded, "character", _letter, unicode_codepoint_from_symbol_reader );
     mandatory( jo, was_loaded, "name",  _name );
     mandatory( jo, was_loaded, "panel_char", _panel_letter, unicode_codepoint_from_symbol_reader );
     assign( jo, "panel_color", _panel_color );
     assign( jo, "symbol_color", _symbol_color );
     std::string exert = jo.get_string( "exertion_level" );
     if( !activity_levels_map.count( exert ) ) {
         jo.throw_error_at( id.str(), "Invalid activity level for move mode " + id.str() );
     }
     _exertion_level = activity_levels_map.at( exert );
     mandatory( jo, was_loaded, "change_good_none", change_messages_success[steed_type::NONE] );
     mandatory( jo, was_loaded, "change_good_animal", change_messages_success[steed_type::ANIMAL] );
     mandatory( jo, was_loaded, "change_good_mech", change_messages_success[steed_type::MECH] );
     optional( jo, was_loaded, "change_bad_none", change_messages_fail[steed_type::NONE],
               to_translation( "You feel bugs crawl over your skin." ) );
     optional( jo, was_loaded, "change_bad_animal", change_messages_fail[steed_type::ANIMAL],
               to_translation( "You feel bugs crawl over your skin." ) );
     optional( jo, was_loaded, "change_bad_mech", change_messages_fail[steed_type::MECH],
               to_translation( "You feel bugs crawl over your skin." ) );
     mandatory( jo, was_loaded, "move_type", _type, make_flag_reader( move_types, "move type" ) );
     optional( jo, was_loaded, "stamina_multiplier", _stamina_multiplier, 1.0 );
     optional( jo, was_loaded, "sound_multiplier", _sound_multiplier, 1.0 );
     optional( jo, was_loaded, "move_speed_multiplier", _move_speed_mult, 1.0 );
     optional( jo, was_loaded, "mech_power_use", _mech_power_use, 2 );
     optional( jo, was_loaded, "swim_speed_mod", _swim_speed_mod, 0 );
     optional( jo, was_loaded, "stop_hauling", _stop_hauling );
 }
References _exertion_level, _letter, _mech_power_use, _move_speed_mult, _name, _panel_color, _panel_letter, _sound_multiplier, _stamina_multiplier, _stop_hauling, _swim_speed_mod, _symbol_color, _type, activity_levels_map, ANIMAL, assign(), change_messages_fail, change_messages_success, JsonObject::get_string(), make_flag_reader(), mandatory, MECH, move_types, NONE, optional(), JsonObject::throw_error_at(), to_translation(), unicode_codepoint_from_symbol_reader(), and was_loaded.
load_move_mode()
void move_mode::load_move_mode (const JsonObject & jo, const std::string & src) static
Definition at line 45 of file move_mode.cpp.
 {
     move_mode_factory.load( jo, src );
 }
References anonymous_namespace{move_mode.cpp}::move_mode_factory, and src.
Referenced by DynamicDataLoader::initialize().
mech_power_use()
units::energy move_mode::mech_power_use () const
Definition at line 184 of file move_mode.cpp.
 {
     return units::from_kilojoule( static_cast<std::int64_t>( _mech_power_use ) );
 }
References _mech_power_use, and units::from_kilojoule().
Referenced by game::vertical_move(), and game::walk_move().
move_speed_mult()
float move_mode::move_speed_mult () const
Definition at line 179 of file move_mode.cpp.
 {
     return _move_speed_mult;
 }
References _move_speed_mult.
Referenced by vehicle::drive_to_local_target(), and finalize().
name()
std::string move_mode::name () const
Definition at line 127 of file move_mode.cpp.
 {
     return _name.translated();
 }
References _name, and translation::translated().
Referenced by open_movement_mode_menu().
panel_color()
nc_color move_mode::panel_color () const
Definition at line 194 of file move_mode.cpp.
 {
     return _panel_color;
 }
References _panel_color.
panel_letter()
char move_mode::panel_letter () const
Definition at line 204 of file move_mode.cpp.
 {
     return _panel_letter;
 }
References _panel_letter.
reset()
void move_mode::reset () static
Definition at line 87 of file move_mode.cpp.
 {
     move_mode_factory.reset();
     move_modes_sorted.clear();
 }
References anonymous_namespace{move_mode.cpp}::move_mode_factory, and move_modes_sorted.
Referenced by DynamicDataLoader::unload_data().
set_cycle()
void move_mode::set_cycle (const move_mode_id & mode) const
Definition at line 224 of file move_mode.cpp.
 {
     cycle_to = mode;
 }
References cycle_to.
Referenced by finalize().
set_cycle_back()
void move_mode::set_cycle_back (const move_mode_id & mode) const
Definition at line 229 of file move_mode.cpp.
 {
     cycle_back = mode;
 }
References cycle_back.
Referenced by finalize().
sound_mult()
float move_mode::sound_mult () const
Definition at line 164 of file move_mode.cpp.
 {
     return _sound_multiplier;
 }
References _sound_multiplier.
Referenced by Character::footstep_sound().
stamina_mult()
float move_mode::stamina_mult () const
Definition at line 169 of file move_mode.cpp.
 {
     return _stamina_multiplier;
 }
References _stamina_multiplier.
Referenced by Character::burn_move_stamina().
stop_hauling()
bool move_mode::stop_hauling () const
Definition at line 214 of file move_mode.cpp.
 {
     return _stop_hauling;
 }
References _stop_hauling.
Referenced by avatar::set_movement_mode().
swim_speed_mod()
int move_mode::swim_speed_mod () const
Definition at line 189 of file move_mode.cpp.
 {
     return _swim_speed_mod;
 }
References _swim_speed_mod.
Referenced by Character::swim_speed().
symbol_color()
nc_color move_mode::symbol_color () const
Definition at line 199 of file move_mode.cpp.
 {
     return _symbol_color;
 }
References _symbol_color.
Referenced by avatar::basic_symbol_color().
type()
move_mode_type move_mode::type () const
Definition at line 219 of file move_mode.cpp.
 {
     return _type;
 }
References _type.
Referenced by Character::can_switch_to(), Character::is_crouching(), Character::is_prone(), Character::is_running(), and Character::is_walking().
Friends And Related Function Documentation
generic_factory< move_mode >
friend class generic_factory< move_mode > friend
Definition at line 106 of file move_mode.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 37 of file move_mode.h.
Member Data Documentation
_exertion_level
float move_mode::_exertion_level = 0.0f private
Definition at line 55 of file move_mode.h.
Referenced by exertion_level(), and load().
_letter
uint32_t move_mode::_letter private
Definition at line 66 of file move_mode.h.
Referenced by letter(), and load().
_mech_power_use
int move_mode::_mech_power_use = 0 private
Definition at line 60 of file move_mode.h.
Referenced by load(), and mech_power_use().
_move_speed_mult
float move_mode::_move_speed_mult = 0.0f private
Definition at line 56 of file move_mode.h.
Referenced by load(), and move_speed_mult().
_name
translation move_mode::_name private
Definition at line 67 of file move_mode.h.
Referenced by load(), and name().
_panel_color
nc_color move_mode::_panel_color private
Definition at line 63 of file move_mode.h.
Referenced by load(), and panel_color().
_panel_letter
uint32_t move_mode::_panel_letter private
Definition at line 65 of file move_mode.h.
Referenced by load(), and panel_letter().
_sound_multiplier
float move_mode::_sound_multiplier = 0.0f private
Definition at line 57 of file move_mode.h.
Referenced by load(), and sound_mult().
_stamina_multiplier
float move_mode::_stamina_multiplier = 0.0f private
Definition at line 58 of file move_mode.h.
Referenced by load(), and stamina_mult().
_stop_hauling
bool move_mode::_stop_hauling = false private
Definition at line 46 of file move_mode.h.
Referenced by load(), and stop_hauling().
_swim_speed_mod
int move_mode::_swim_speed_mod = 0 private
Definition at line 61 of file move_mode.h.
Referenced by load(), and swim_speed_mod().
_symbol_color
nc_color move_mode::_symbol_color private
Definition at line 64 of file move_mode.h.
Referenced by load(), and symbol_color().
_type
move_mode_type move_mode::_type = move_mode_type::WALKING private
Definition at line 53 of file move_mode.h.
Referenced by load(), and type().
change_messages_fail
std::map<steed_type, translation> move_mode::change_messages_fail private
Definition at line 44 of file move_mode.h.
Referenced by change_message(), and load().
change_messages_success
std::map<steed_type, translation> move_mode::change_messages_success private
Definition at line 43 of file move_mode.h.
Referenced by change_message(), and load().
cycle_back
move_mode_id move_mode::cycle_back mutable private
Definition at line 52 of file move_mode.h.
Referenced by cycle_reverse(), and set_cycle_back().
cycle_to
move_mode_id move_mode::cycle_to mutable private
Definition at line 51 of file move_mode.h.
Referenced by cycle(), and set_cycle().
id
move_mode_id move_mode::id private
Definition at line 40 of file move_mode.h.
Referenced by ident().
src
std::vector<std::pair<move_mode_id, mod_id> > move_mode::src private
Definition at line 41 of file move_mode.h.
Referenced by load_move_mode().
was_loaded
bool move_mode::was_loaded = false private
Definition at line 39 of file move_mode.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/move_mode.h
src/move_mode.cpp