Cataclysm DDA: repair_item_actor Class Reference
repair_item_actor Class Reference
Repair an item.
#include <iuse_actor.h>
Public Types
enum attempt_hint : int {
AS_SUCCESS = 0 , AS_RETRY , AS_FAILURE , AS_DESTROYED ,
AS_CANT , AS_CANT_USE_TOOL , AS_CANT_YET
}
enum repair_type : int {
RT_NOTHING = 0 , RT_REPAIR = 1 , RT_REFIT = 2 , RT_DOWNSIZING = 3 ,
RT_UPSIZING = 4 , RT_PRACTICE = 6 , NUM_REPAIR_TYPES = 7
}
Public Member Functions
attempt_hint repair (Character &pl, item &tool, item_location &fix, bool refit_only=false) const
Attempts to repair target item with selected tool.
bool can_repair_target (Character &pl, const item &fix, bool print_msg, bool check_consumed_available) const
Checks if repairs on target item are possible.
bool can_use_tool (const Character &p, const item &tool, bool print_msg) const
Checks if we are allowed to use the tool.
std::set< itype_id > get_valid_repair_materials (const item &fix) const
Returns a list of items that can be used to repair this item.
bool handle_components (Character &pl, const item &fix, bool print_msg, bool just_check, bool check_consumed_available) const
Returns if components are available.
std::pair< float, float > repair_chance (const Character &pl, const item &fix, repair_type action_type) const
Returns the chance to repair and to damage an item.
repair_type default_action (const item &fix, int current_skill_level) const
What are we most likely trying to do with this item?
int repair_recipe_difficulty (const item &fix) const
Calculates the difficulty to repair an item based on its materials.
repair_item_actor (const std::string &type="repair_item")
~repair_item_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
std::string get_name () const override
Returns the translated name of the action.
std::string get_description () const override
Returns the translated description of the action.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual void finalize (const itype_id &)
Finalizes the actor.
Static Public Member Functions
static std::string action_description (repair_type)
Describes members of repair_type enum.
Public Attributes
std::set< material_id > materials
Materials we are allowed to repair.
skill_id used_skill
Skill used.
int trains_skill_to = 0
Maximum skill level that can be gained by using this actor.
float cost_scaling = 1.0f
Volume of materials required (and used up) as percentage of repaired item's volume.
int tool_quality = 0
Extra value added to skill roll.
int move_cost = 0
Move cost for every attempt.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Repair an item.
Definition at line 773 of file iuse_actor.h.
Member Enumeration Documentation
attempt_hint
enum repair_item_actor::attempt_hint : int
Enumerator
AS_SUCCESS
AS_RETRY
AS_FAILURE
AS_DESTROYED
AS_CANT
AS_CANT_USE_TOOL
AS_CANT_YET
Definition at line 792 of file iuse_actor.h.
                           : int {
             AS_SUCCESS = 0,     // Success, but can retry
             AS_RETRY,           // Failed, but can retry
             AS_FAILURE,         // Failed hard, don't retry
             AS_DESTROYED,       // Failed and destroyed item
             AS_CANT,            // Couldn't attempt
             AS_CANT_USE_TOOL,   // Cannot use tool
             AS_CANT_YET         // Skill too low
         };
repair_type
enum repair_item_actor::repair_type : int
Enumerator
RT_NOTHING
RT_REPAIR
RT_REFIT
RT_DOWNSIZING
RT_UPSIZING
RT_PRACTICE
NUM_REPAIR_TYPES
Definition at line 802 of file iuse_actor.h.
                          : int {
             RT_NOTHING = 0,
             RT_REPAIR = 1,          // Just repairing damage
             RT_REFIT = 2,           // Refitting
             RT_DOWNSIZING = 3,      // When small, reduce clothing to small size
             RT_UPSIZING = 4,        // When normal, increase clothing to normal size
             // value of 5 obsoleted, previously used for reinforcing
             RT_PRACTICE = 6,        // Wanted to reinforce, but can't
             NUM_REPAIR_TYPES = 7
         };
Constructor & Destructor Documentation
repair_item_actor()
repair_item_actor::repair_item_actor (const std::string & type = "repair_item") inline explicit
Definition at line 852 of file iuse_actor.h.
 : iuse_actor( type ) {}
~repair_item_actor()
repair_item_actor::~repair_item_actor () override default
Member Function Documentation
action_description()
std::string repair_item_actor::action_description (repair_item_actor::repair_type rt) static
Describes members of repair_type enum.
Definition at line 3227 of file iuse_actor.cpp.
 {
     static const std::array<std::string, NUM_REPAIR_TYPES> arr = {{
             translate_marker( "Nothing" ),
             translate_marker( "Repairing" ),
             translate_marker( "Refitting" ),
             translate_marker( "Downsizing" ),
             translate_marker( "Upsizing" ),
             "Obsolete",
             translate_marker( "Practicing" )
         }
     };
     return _( arr[rt] );
 }
References _, and translate_marker.
Referenced by repair_item_finish().
can_repair_target()
bool repair_item_actor::can_repair_target (Character & pl, const item & fix, bool print_msg, bool check_consumed_available) const
Checks if repairs on target item are possible.
Excludes checks on tool. Doesn't just estimate - should not return true if repairs are not possible or false if they are.
Parameters
pl character performing the fix
fix item to repair
print_msg prints message to player if check fails
check_consumed_available if true check materials consumed by repair are available for pl
Returns
true if check succeeds
Definition at line 2909 of file iuse_actor.cpp.
 {
     // In some rare cases (indices getting scrambled after inventory overflow)
     //  our `fix` can be a different item.
     if( fix.is_null() ) {
         if( print_msg ) {
             pl.add_msg_if_player( m_info, _( "You do not have that item!" ) );
         }
         return false;
     }
     if( fix.is_firearm() ) {
         if( print_msg ) {
             pl.add_msg_if_player( m_info, _( "That requires gunsmithing tools." ) );
         }
         return false;
     }
     if( fix.count_by_charges() || fix.has_flag( flag_NO_REPAIR ) ) {
         if( print_msg ) {
             pl.add_msg_if_player( m_info, _( "You cannot repair this type of item." ) );
         }
         return false;
     }
     if( any_of( materials.begin(), materials.end(), [&fix]( const material_id & mat ) {
     return mat.obj()
                .repaired_with() == fix.typeId();
     } ) ) {
         if( print_msg ) {
             pl.add_msg_if_player( m_info, _( "This can be used to repair other items, not itself." ) );
         }
         return false;
     }
     if( !handle_components( pl, fix, print_msg, true, check_consumed_available ) ) {
         return false;
     }
     const bool can_be_refitted = fix.has_flag( flag_VARSIZE );
     if( can_be_refitted && !fix.has_flag( flag_FIT ) ) {
         return true;
     }
     const bool resizing_matters = fix.get_sizing( pl ) != item::sizing::ignore;
     const bool small = pl.get_size() == creature_size::tiny;
     const bool can_resize = small != fix.has_flag( flag_UNDERSIZE );
     if( can_be_refitted && resizing_matters && can_resize ) {
         return true;
     }
     if( fix.damage() > fix.degradation() ) {
         return true;
     }
     if( print_msg ) {
         pl.add_msg_if_player( m_info, _( "You cannot improve your %s any more this way." ), fix.tname() );
     }
     return false;
 }
References _, Character::add_msg_if_player(), item::count_by_charges(), item::damage(), item::degradation(), flag_FIT, flag_NO_REPAIR, flag_UNDERSIZE, flag_VARSIZE, Character::get_size(), item::get_sizing(), handle_components(), item::has_flag(), item::ignore, item::is_firearm(), item::is_null(), m_info, small, tiny, and item::tname().
Referenced by repair_inventory_preset::is_shown(), repair(), and repair_item_finish().
can_use_tool()
bool repair_item_actor::can_use_tool (const Character & p, const item & tool, bool print_msg) const
Checks if we are allowed to use the tool.
Definition at line 2685 of file iuse_actor.cpp.
 {
     if( p.has_effect( effect_incorporeal ) ) {
         if( print_msg ) {
             p.add_msg_player_or_npc( m_bad, _( "You can't do that while incorporeal." ),
                                      _( "<npcname> can't do that while incorporeal." ) );
         }
         return false;
     }
     if( p.cant_do_underwater( print_msg ) ) {
         return false;
     }
     if( p.cant_do_mounted( print_msg ) ) {
         return false;
     }
     if( p.fine_detail_vision_mod() > 4 ) {
         if( print_msg ) {
             p.add_msg_if_player( m_info, _( "You can't see to do that!" ) );
         }
         return false;
     }
     if( !tool.ammo_sufficient( &p ) ) {
         if( print_msg ) {
             p.add_msg_if_player( m_info, _( "Your tool does not have enough charges to do that." ) );
         }
         return false;
     }
     return true;
 }
References _, Character::add_msg_if_player(), Character::add_msg_player_or_npc(), item::ammo_sufficient(), Character::cant_do_mounted(), Creature::cant_do_underwater(), effect_incorporeal, Character::fine_detail_vision_mod(), Creature::has_effect(), m_bad, and m_info.
Referenced by repair(), repair_item_finish(), and use().
clone()
std::unique_ptr< iuse_actor > repair_item_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2759 of file iuse_actor.cpp.
 {
     return std::make_unique<repair_item_actor>( *this );
 }
default_action()
repair_item_actor::repair_type repair_item_actor::default_action (const item & fix, int current_skill_level) const
What are we most likely trying to do with this item?
Definition at line 3027 of file iuse_actor.cpp.
 {
     if( fix.damage() > fix.degradation() ) {
         return RT_REPAIR;
     }
     const bool can_be_refitted = fix.has_flag( flag_VARSIZE );
     const bool doesnt_fit = !fix.has_flag( flag_FIT );
     if( doesnt_fit && can_be_refitted ) {
         return RT_REFIT;
     }
     Character &player_character = get_player_character();
     const bool smol = player_character.get_size() == creature_size::tiny;
     const bool is_undersized = fix.has_flag( flag_UNDERSIZE );
     const bool is_oversized = fix.has_flag( flag_OVERSIZE );
     const bool resizing_matters = fix.get_sizing( player_character ) != item::sizing::ignore;
     const bool too_big_while_smol = smol && !is_undersized && !is_oversized;
     if( too_big_while_smol && can_be_refitted && resizing_matters ) {
         return RT_DOWNSIZING;
     }
     const bool too_small_while_big = !smol && is_undersized && !is_oversized;
     if( too_small_while_big && can_be_refitted && resizing_matters ) {
         return RT_UPSIZING;
     }
     if( current_skill_level <= trains_skill_to ) {
         return RT_PRACTICE;
     }
     return RT_NOTHING;
 }
References item::damage(), item::degradation(), flag_FIT, flag_OVERSIZE, flag_UNDERSIZE, flag_VARSIZE, get_player_character(), Character::get_size(), item::get_sizing(), item::has_flag(), item::ignore, RT_DOWNSIZING, RT_NOTHING, RT_PRACTICE, RT_REFIT, RT_REPAIR, RT_UPSIZING, tiny, and trains_skill_to.
Referenced by repair(), repair_inventory_preset::repair_inventory_preset(), and repair_item_finish().
get_description()
std::string repair_item_actor::get_description () const override virtual
Returns the translated description of the action.
It is used for the item action menu.
Reimplemented from iuse_actor.
Definition at line 3248 of file iuse_actor.cpp.
 {
     const std::string mats = enumerate_as_string( materials.begin(), materials.end(),
     []( const material_id & mid ) {
         return mid->name();
     } );
     return string_format( _( "Repair %s" ), mats );
 }
References _, enumerate_as_string(), and string_format().
get_name()
std::string repair_item_actor::get_name () const override virtual
Returns the translated name of the action.
It is used for the item action menu.
Reimplemented from iuse_actor.
Definition at line 3243 of file iuse_actor.cpp.
 {
     return _( "Repair" );
 }
References _.
get_valid_repair_materials()
std::set< itype_id > repair_item_actor::get_valid_repair_materials (const item & fix) const
Returns a list of items that can be used to repair this item.
Definition at line 2764 of file iuse_actor.cpp.
 {
     std::set<itype_id> valid_entries;
     for( const auto &mat : materials ) {
         if( fix.can_repair_with( mat ) ) {
             const itype_id &component_id = mat.obj().repaired_with();
             // Certain (different!) materials are repaired with the same components (steel, iron, hard steel use scrap metal).
             // This checks avoids adding the same component twice, which is annoying to the user.
             if( valid_entries.find( component_id ) != valid_entries.end() ) {
                 continue;
             }
             valid_entries.insert( component_id );
         }
     }
     return valid_entries;
 }
References item::can_repair_with(), and string_id< T >::obj().
Referenced by handle_components(), repair_inventory_preset::repair_inventory_preset(), and repair_item_finish().
handle_components()
bool repair_item_actor::handle_components (Character & pl, const item & fix, bool print_msg, bool just_check, bool check_consumed_available) const
Returns if components are available.
Consumes them if just_check is false.
Parameters
pl character performing the fix
fix item to repair
print_msg prints message to player if check fails
just_check only checks, doesn't consume
check_consumed_available if false skips checking if materials consumed by repair are available for pl
Returns
true if check succeeds
Definition at line 2781 of file iuse_actor.cpp.
 {
     // Entries valid for repaired items
     std::set<itype_id> valid_entries = get_valid_repair_materials( fix );
     if( valid_entries.empty() ) {
         if( print_msg ) {
             pl.add_msg_if_player( m_info, _( "Your %s is not made of any of:" ),
                                   fix.tname() );
             for( const auto &mat_name : materials ) {
                 const material_type &mat = mat_name.obj();
                 pl.add_msg_if_player( m_info, _( "%s (repaired using %s)" ), mat.name(),
                                       item::nname( mat.repaired_with(), 2 ) );
             }
         }
         return false;
     }
     const inventory &crafting_inv = pl.crafting_inventory();
     // Repairing or modifying items requires at least 1 repair item,
     //  otherwise number is related to size of item
     // Round up if checking, but roll if actually consuming
     // TODO: should 250_ml be part of the cost_scaling?
     const int items_needed = std::max<int>( 1, just_check ?
                                             std::ceil( fix.base_volume() / 250_ml * cost_scaling ) :
                                             roll_remainder( fix.base_volume() / 250_ml * cost_scaling ) );
     std::function<bool( const item & )> filter;
     if( fix.is_filthy() ) {
         filter = []( const item & component ) {
             return component.allow_crafting_component();
         };
     } else {
         filter = is_crafting_component;
     }
     // Go through all discovered repair items and see if we have any of them available
     std::vector<item_comp> comps;
     for( const itype_id &component_id : valid_entries ) {
         if( item::count_by_charges( component_id ) ) {
             if( crafting_inv.has_charges( component_id, items_needed ) ) {
                 comps.emplace_back( component_id, items_needed );
             }
         } else if( crafting_inv.has_amount( component_id, items_needed, false, filter ) ) {
             comps.emplace_back( component_id, items_needed );
         }
     }
     if( check_consumed_available && comps.empty() ) {
         if( print_msg ) {
             for( const itype_id &mat_comp : valid_entries ) {
                 pl.add_msg_if_player( m_info,
                                       _( "You don't have enough clean %s to do that.  Have: %d, need: %d" ),
                                       item::nname( mat_comp, 2 ),
                                       item::find_type( mat_comp )->count_by_charges() ?
                                       crafting_inv.charges_of( mat_comp, items_needed ) :
                                       crafting_inv.amount_of( mat_comp, false ),
                                       items_needed );
             }
         }
         return false;
     }
     if( !just_check ) {
         if( comps.empty() ) {
             // This shouldn't happen - the check in can_repair_target should prevent it
             // But report it, just in case
             debugmsg( "Attempted repair with no components" );
         }
         pl.consume_items( comps, 1, filter );
     }
     return true;
 }
References _, Character::add_msg_if_player(), inventory::amount_of(), item::base_volume(), ceil(), inventory::charges_of(), Character::consume_items(), cost_scaling, item::count_by_charges(), itype::count_by_charges(), Character::crafting_inventory(), debugmsg, filter, item::find_type(), get_valid_repair_materials(), visitable::has_amount(), read_only_visitable::has_charges(), is_crafting_component(), item::is_filthy(), m_info, material_type::name(), item::nname(), material_type::repaired_with(), roll_remainder(), and item::tname().
Referenced by can_repair_target(), and repair().
load()
void repair_item_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2663 of file iuse_actor.cpp.
 {
     // Mandatory:
     for( const std::string line : obj.get_array( "materials" ) ) {
         materials.emplace( line );
     }
     // TODO: Make skill non-mandatory while still erroring on invalid skill
     const std::string skill_string = obj.get_string( "skill" );
     used_skill = skill_id( skill_string );
     if( !used_skill.is_valid() ) {
         obj.throw_error_at( "skill", "Invalid skill" );
     }
     cost_scaling = obj.get_float( "cost_scaling" );
     // Optional
     tool_quality = obj.get_int( "tool_quality", 0 );
     move_cost    = obj.get_int( "move_cost", 500 );
     trains_skill_to = obj.get_int( "trains_skill_to", 5 ) - 1;
 }
References cost_scaling, JsonObject::get_array(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_string(), string_id< T >::is_valid(), line, move_cost, skill_id, JsonObject::throw_error_at(), tool_quality, trains_skill_to, and used_skill.
repair()
repair_item_actor::attempt_hint repair_item_actor::repair (Character & pl, item & tool, item_location & fix, bool refit_only = false) const
Attempts to repair target item with selected tool.
Definition at line 3094 of file iuse_actor.cpp.
 {
     if( !can_use_tool( pl, tool, true ) ) {
         return AS_CANT_USE_TOOL;
     }
     if( !can_repair_target( pl, *fix, true, true ) ) {
         return AS_CANT;
     }
     const int current_skill_level = pl.get_skill_level( used_skill );
     repair_item_actor::repair_type action;
     if( refit_only ) {
         if( fix->has_flag( flag_FIT ) ) {
             pl.add_msg_if_player( m_warning, _( "The %s already fits!" ), fix->tname() );
             return AS_CANT;
         } else if( !fix->has_flag( flag_VARSIZE ) ) {
             pl.add_msg_if_player( m_bad, _( "This %s cannot be refitted!" ), fix->tname() );
             return AS_CANT;
         } else {
             action = RT_REFIT;
         }
     } else {
         action = default_action( *fix, current_skill_level );
     }
     const auto chance = repair_chance( pl, *fix, action );
     int practice_amount = repair_recipe_difficulty( *fix ) / 2 + 1;
     float roll_value = rng_float( 0.0, 1.0 );
     enum roll_result {
         SUCCESS,
         FAILURE,
         NEUTRAL
     } roll;
     if( roll_value > 1.0f - chance.second ) {
         roll = FAILURE;
     } else if( roll_value < chance.first ) {
         roll = SUCCESS;
     } else {
         roll = NEUTRAL;
     }
     if( action == RT_NOTHING ) {
         pl.add_msg_if_player( m_bad, _( "You won't learn anything more by doing that." ) );
         return AS_CANT;
     }
     // If not for this if, it would spam a lot
     if( current_skill_level > trains_skill_to ) {
         practice_amount = 0;
     }
     pl.practice( used_skill, practice_amount, trains_skill_to );
     if( roll == FAILURE ) {
         if( chance.first <= 0.0f ) {
             pl.add_msg_if_player( m_bad,
                                   _( "It seems working on your %s is just beyond your current level of expertise." ),
                                   fix->tname() );
         }
         return damage_item( pl, fix ) ? AS_DESTROYED : AS_FAILURE;
     }
     if( action == RT_PRACTICE ) {
         return AS_RETRY;
     }
     if( action == RT_REPAIR ) {
         if( roll == SUCCESS ) {
             const std::string startdurability = fix->durability_indicator( true );
             handle_components( pl, *fix, false, false, true );
             fix->mod_damage( -itype::damage_scale );
             const std::string resultdurability = fix->durability_indicator( true );
             if( fix->repairable_levels() ) {
                 pl.add_msg_if_player( m_good, _( "You repair your %s!  ( %s-> %s)" ),
                                       fix->tname( 1, false ), startdurability, resultdurability );
             } else {
                 pl.add_msg_if_player( m_good, _( "You repair your %s completely!  ( %s-> %s)" ),
                                       fix->tname( 1, false ), startdurability, resultdurability );
             }
             return AS_SUCCESS;
         }
         return AS_RETRY;
     }
     if( action == RT_REFIT ) {
         if( roll == SUCCESS ) {
             if( !fix->has_flag( flag_FIT ) ) {
                 pl.add_msg_if_player( m_good, _( "You take your %s in, improving the fit." ),
                                       fix->tname() );
                 fix->set_flag( flag_FIT );
                 pl.calc_encumbrance();
             }
             handle_components( pl, *fix, false, false, true );
             return AS_SUCCESS;
         }
         return AS_RETRY;
     }
     if( action == RT_DOWNSIZING ) {
         //We don't need to check for smallness or undersize because DOWNSIZING already guarantees that
         if( roll == SUCCESS ) {
             pl.add_msg_if_player( m_good, _( "You resize the %s to accommodate your tiny build." ),
                                   fix->tname().c_str() );
             fix->set_flag( flag_UNDERSIZE );
             pl.calc_encumbrance();
             handle_components( pl, *fix, false, false, true );
             return AS_SUCCESS;
         }
         return AS_RETRY;
     }
     if( action == RT_UPSIZING ) {
         //We don't need to check for smallness or undersize because UPSIZING already guarantees that
         if( roll == SUCCESS ) {
             pl.add_msg_if_player( m_good, _( "You adjust the %s back to its normal size." ),
                                   fix->tname().c_str() );
             fix->unset_flag( flag_UNDERSIZE );
             pl.calc_encumbrance();
             handle_components( pl, *fix, false, false, true );
             return AS_SUCCESS;
         }
         return AS_RETRY;
     }
     pl.add_msg_if_player( m_info, _( "You cannot improve your %s any more this way." ), fix->tname() );
     return AS_CANT;
 }
References _, action, Character::add_msg_if_player(), AS_CANT, AS_CANT_USE_TOOL, AS_DESTROYED, AS_FAILURE, AS_RETRY, AS_SUCCESS, Character::calc_encumbrance(), can_repair_target(), can_use_tool(), damage_item(), itype::damage_scale, default_action(), item::durability_indicator(), flag_FIT, flag_UNDERSIZE, flag_VARSIZE, Character::get_skill_level(), handle_components(), item::has_flag(), m_bad, m_good, m_info, m_warning, item::mod_damage(), NEUTRAL, Character::practice(), repair_chance(), repair_recipe_difficulty(), item::repairable_levels(), rng_float(), RT_DOWNSIZING, RT_NOTHING, RT_PRACTICE, RT_REFIT, RT_REPAIR, RT_UPSIZING, item::set_flag(), SUCCESS, item::tname(), trains_skill_to, item::unset_flag(), and used_skill.
Referenced by repair_item_finish().
repair_chance()
std::pair< float, float > repair_item_actor::repair_chance (const Character & pl, const item & fix, repair_item_actor::repair_type action_type) const
Returns the chance to repair and to damage an item.
Tailor randomly improves clothing repair efforts Mechanics randomly improves metal repair efforts Dexterity reduces the chances of damaging an item when repairing
Definition at line 2969 of file iuse_actor.cpp.
 {
     /** @EFFECT_TAILOR randomly improves clothing repair efforts */
     /** @EFFECT_MECHANICS randomly improves metal repair efforts */
     const float skill = pl.get_skill_level( used_skill );
     const int material_difficulty = repair_recipe_difficulty( fix );
     int action_difficulty = 0;
     switch( action_type ) {
         case RT_NOTHING: /* fallthrough */
         case RT_DOWNSIZING: /* fallthrough */
         case RT_UPSIZING:
             break;
         case RT_REPAIR:
             action_difficulty = fix.damage_level();
             break;
         case RT_REFIT:
             // Let's make refitting as hard as recovering an almost-wrecked item
             action_difficulty = fix.max_damage() / itype::damage_scale;
             break;
         case RT_PRACTICE:
             // Skill gain scales with recipe difficulty, so practice difficulty should too
             action_difficulty = material_difficulty;
             break;
         default:
             // 5 is obsoleted reinforcing, remove after 0.H
             action_difficulty = 1'000'000; // ensure failure
             break;
     }
     const int difficulty = material_difficulty + action_difficulty;
     // Sample numbers - cotton and wool have diff 1, plastic diff 3 and kevlar diff 4:
     // This assumes that training is false, and under almost all circumstances that should be the case
     // Item     | Damage | Skill | Dex | Success | Failure
     // Hoodie   |   1    |   0   |  8  |  4.0%   |  1.4%
     // Hoodie   | Refit  |   0   |  8  |  2.0%   |  2.4%
     // Hoodie   | Refit  |   2   |  8  |  6.0%   |  0.4%
     // Hoodie   | Refit  |   2   |  12 |  6.0%   |  0.0%
     // Hoodie   | Refit  |   4   |  8  |  10.0%  |  0.0%
     // Socks    |   3    |   0   |  8  |  2.0%   |  2.4%
     // Boots    |   1    |   0   |  8  |  0.0%   |  3.4%
     // Raincoat | Refit  |   2   |  8  |  2.0%   |  2.4%
     // Raincoat | Refit  |   2   |  12 |  2.0%   |  1.6%
     // Ski mask | Refit  |   2   |  8  |  4.0%   |  1.4%
     // Raincoat | Refit  |   2   |  8  |  4.0%   |  1.4%
     // Turnout  | Refit  |   2   |  8  |  0.0%   |  4.4%
     // Turnout  | Refit  |   4   |  8  |  2.0%   |  2.4%
     float success_chance = ( 10 + 2 * skill - 2 * difficulty + tool_quality / 5.0f ) / 100.0f;
     /** @EFFECT_DEX reduces the chances of damaging an item when repairing */
     float damage_chance = ( difficulty - skill - ( tool_quality + pl.dex_cur ) / 5.0f ) / 100.0f;
     damage_chance = std::max( 0.0f, std::min( 1.0f, damage_chance ) );
     success_chance = std::max( 0.0f, std::min( 1.0f - damage_chance, success_chance ) );
     return std::make_pair( success_chance, damage_chance );
 }
References item::damage_level(), itype::damage_scale, Character::dex_cur, Character::get_skill_level(), max(), item::max_damage(), min(), repair_recipe_difficulty(), RT_DOWNSIZING, RT_NOTHING, RT_PRACTICE, RT_REFIT, RT_REPAIR, RT_UPSIZING, tool_quality, and used_skill.
Referenced by repair(), repair_inventory_preset::repair_inventory_preset(), and repair_item_finish().
repair_recipe_difficulty()
int repair_item_actor::repair_recipe_difficulty (const item & fix) const
Calculates the difficulty to repair an item based on its materials.
Normally the difficulty to repair is that of the most difficult material. If the item has a repairs_like, use the materials of that item instead.
Definition at line 2885 of file iuse_actor.cpp.
 {
     std::pair<int, bool> ret;
     ret = find_repair_difficulty( *fix.type );
     int diff = ret.first;
     bool defined = ret.second;
     // See if there's a repairs_like that has a defined difficulty
     if( !defined && !fix.type->repairs_like.is_empty() ) {
         ret = find_repair_difficulty( fix.type->repairs_like.obj() );
         if( ret.second ) {
             diff = ret.first;
             defined = true;
         }
     }
     // If we still don't find a difficulty, difficulty is 10
     if( !defined ) {
         diff = 10;
     }
     return diff;
 }
References find_repair_difficulty(), string_id< T >::is_empty(), string_id< T >::obj(), itype::repairs_like, cata::hash64_detail::ret, and item::type.
Referenced by repair(), repair_chance(), and repair_inventory_preset::repair_inventory_preset().
use()
std::optional< int > repair_item_actor::use (Character * p, item & it, const tripoint & position) const override virtual
Implements iuse_actor.
Definition at line 2743 of file iuse_actor.cpp.
 {
     if( !can_use_tool( *p, it, true ) ) {
         return std::nullopt;
     }
     p->assign_activity( ACT_REPAIR_ITEM, 0, p->get_item_position( &it ), INT_MIN );
     // We also need to store the repair actor subtype in the activity
     p->activity.str_values.push_back( type );
     // storing of item_location to support repairs by tools on the ground
     p->activity.targets.emplace_back( get_item_location( *p, it, position ) );
     // All repairs are done in the activity, including charge cost and target item selection
     return 0;
 }
References ACT_REPAIR_ITEM, Character::activity, Character::assign_activity(), can_use_tool(), get_item_location(), Character::get_item_position(), player_activity::str_values, player_activity::targets, and iuse_actor::type.
Member Data Documentation
cost_scaling
float repair_item_actor::cost_scaling = 1.0f
Volume of materials required (and used up) as percentage of repaired item's volume.
Set to 0 to always use just 1 component.
Definition at line 786 of file iuse_actor.h.
Referenced by handle_components(), load(), and repair_inventory_preset::repair_inventory_preset().
materials
std::set<material_id> repair_item_actor::materials
Materials we are allowed to repair.
Definition at line 777 of file iuse_actor.h.
move_cost
int repair_item_actor::move_cost = 0
Move cost for every attempt.
Definition at line 790 of file iuse_actor.h.
Referenced by load(), and repair_item_finish().
tool_quality
int repair_item_actor::tool_quality = 0
Extra value added to skill roll.
Definition at line 788 of file iuse_actor.h.
Referenced by load(), and repair_chance().
trains_skill_to
int repair_item_actor::trains_skill_to = 0
Maximum skill level that can be gained by using this actor.
Definition at line 781 of file iuse_actor.h.
Referenced by default_action(), load(), and repair().
used_skill
skill_id repair_item_actor::used_skill
Skill used.
Definition at line 779 of file iuse_actor.h.
Referenced by get_repair_hint(), load(), repair(), repair_chance(), repair_inventory_preset::repair_inventory_preset(), and repair_item_finish().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp