Cataclysm DDA: field Class Reference
field Class Reference
A variable sized collection of field entries on a given map square.
#include <field.h>
Public Member Functions
field ()
field_entry * find_field (const field_type_id &field_type_to_find, bool alive_only=true)
Returns a field entry corresponding to the field_type_id parameter passed in.
const field_entry * find_field (const field_type_id &field_type_to_find, bool alive_only=true) const
Returns a field entry corresponding to the field_type_id parameter passed in.
bool add_field (const field_type_id &field_type_to_add, int new_intensity=1, const time_duration &new_age=0_turns)
Inserts the given field_type_id into the field list for a given tile if it does not already exist.
bool remove_field (const field_type_id &field_to_remove)
Removes the field entry with a type equal to the field_type_id parameter.
void remove_field (std::map< field_type_id, field_entry >::iterator)
Make sure to decrement the field counter in the submap.
void clear ()
Removes all fields.
unsigned int field_count () const
field_type_id displayed_field_type () const
Returns field type that should be drawn.
int displayed_intensity () const
Returns the intensity of the drawn tile.
description_affix displayed_description_affix () const
std::map< field_type_id, field_entry >::iterator begin ()
std::map< field_type_id, field_entry >::const_iterator begin () const
std::map< field_type_id, field_entry >::iterator end ()
std::map< field_type_id, field_entry >::const_iterator end () const
int total_move_cost () const
Returns the total move cost from all fields.
Private Attributes
lazy< std::map< field_type_id, field_entry > > _field_type_list
field_type_id _displayed_field_type
Detailed Description
A variable sized collection of field entries on a given map square.
It contains one (at most) entry of each field type (e. g. one smoke entry and one fire entry, but not two fire entries). Use find_field to get the field entry of a specific type, or iterate over all entries via begin and end (allows range based iteration). There is displayed_field_type to specific which field should be drawn on the map.
Definition at line 106 of file field.h.
Constructor & Destructor Documentation
field()
field::field ()
Definition at line 112 of file field.cpp.
     : _displayed_field_type( fd_null.id_or( INVALID_FIELD_TYPE_ID ) )
 {
 }
Member Function Documentation
add_field()
bool field::add_field (const field_type_id & field_type_to_add, int new_intensity = 1, const time_duration & new_age = 0_turns)
Inserts the given field_type_id into the field list for a given tile if it does not already exist.
If you wish to modify an already existing field use find_field and modify the result. Intensity defaults to 1, and age to 0 (permanent) if not specified. The intensity is added to an existing field entry, but the age is only used for newly added entries.
Returns
false if the field_type_id already exists, true otherwise.
Definition at line 155 of file field.cpp.
 {
     // sanity check, we don't want to store fd_null
     if( !field_type_to_add ) {
         return false;
     }
     auto it = _field_type_list->find( field_type_to_add );
     if( it != _field_type_list->end() ) {
         //Already exists, but lets update it. This is tentative.
         int prev_intensity = it->second.get_field_intensity();
         if( !it->second.is_field_alive() ) {
             it->second.set_field_age( new_age );
             prev_intensity = 0;
         }
         it->second.set_field_intensity( prev_intensity + new_intensity );
         return false;
     }
     if( !_displayed_field_type ||
         field_type_to_add.obj().priority >= _displayed_field_type.obj().priority ) {
         _displayed_field_type = field_type_to_add;
     }
     _field_type_list[field_type_to_add] = field_entry( field_type_to_add, new_intensity, new_age );
     return true;
 }
References _displayed_field_type, _field_type_list, int_id< T >::obj(), and field_type::priority.
Referenced by map::add_field().
begin() [1/2]
std::map< field_type_id, field_entry >::iterator field::begin ()
Definition at line 217 of file field.cpp.
 {
     return _field_type_list->begin();
 }
References _field_type_list.
Referenced by map::delete_field(), editmap::edit_fld(), game::print_fields_info(), and map::process_fields_in_submap().
begin() [2/2]
std::map< field_type_id, field_entry >::const_iterator field::begin () const
Definition at line 222 of file field.cpp.
 {
     return _field_type_list->begin();
 }
References _field_type_list.
clear()
void field::clear ()
Removes all fields.
Don't forget to update field count in submap!
Definition at line 202 of file field.cpp.
 {
     _field_type_list->clear();
     _displayed_field_type = fd_null;
 }
References _displayed_field_type, _field_type_list, and fd_null.
Referenced by submap::clear_fields().
displayed_description_affix()
description_affix field::displayed_description_affix () const
Definition at line 246 of file field.cpp.
 {
     return _displayed_field_type.obj().desc_affix;
 }
References _displayed_field_type, field_type::desc_affix, and int_id< T >::obj().
Referenced by colorized_field_description_at().
displayed_field_type()
field_type_id field::displayed_field_type () const
Returns field type that should be drawn.
Definition at line 241 of file field.cpp.
 {
     return _displayed_field_type;
 }
References _displayed_field_type.
Referenced by colorized_field_description_at(), map::delete_field(), editmap_hilight::draw(), editmap::draw_main_ui_overlay(), map::draw_maptile(), and map::process_fields_in_submap().
displayed_intensity()
int field::displayed_intensity () const
Returns the intensity of the drawn tile.
Definition at line 251 of file field.cpp.
 {
     auto it = _field_type_list->find( _displayed_field_type );
     return it->second.get_field_intensity();
 }
References _displayed_field_type, and _field_type_list.
end() [1/2]
std::map< field_type_id, field_entry >::iterator field::end ()
Definition at line 227 of file field.cpp.
 {
     return _field_type_list->end();
 }
References _field_type_list.
Referenced by map::delete_field(), game::print_fields_info(), and map::process_fields_in_submap().
end() [2/2]
std::map< field_type_id, field_entry >::const_iterator field::end () const
Definition at line 232 of file field.cpp.
 {
     return _field_type_list->end();
 }
References _field_type_list.
field_count()
unsigned int field::field_count () const
Definition at line 212 of file field.cpp.
 {
     return _field_type_list->size();
 }
References _field_type_list.
Referenced by submap::clear_fields(), map::decay_fields_and_scent(), editmap_hilight::draw(), editmap::draw_main_ui_overlay(), map::draw_maptile(), map::drop_fields(), editmap::edit_fld(), and map::shoot().
find_field() [1/2]
field_entry * field::find_field (const field_type_id & field_type_to_find, bool alive_only = true)
Returns a field entry corresponding to the field_type_id parameter passed in.
If no fields are found then nullptr is returned.
Parameters
alive_only if true, returns non-null result only if field is alive
Definition at line 122 of file field.cpp.
 {
     if( !_displayed_field_type ) {
         return nullptr;
     }
     const auto it = _field_type_list->find( field_type_to_find );
     if( it != _field_type_list->end() && ( !alive_only || it->second.is_field_alive() ) ) {
         return &it->second;
     }
     return nullptr;
 }
References _displayed_field_type, and _field_type_list.
Referenced by colorized_field_description_at(), npc::could_move_onto(), editmap_hilight::draw(), editmap::draw_main_ui_overlay(), map::draw_maptile(), editmap::edit_fld(), anonymous_namespace{math_parser_diag.cpp}::field_strength_eval(), map::gas_can_spread_to(), game::get_dangerous_tile(), map::get_field_age(), monster::know_danger_at(), and editmap::update_fmenu_entry().
find_field() [2/2]
const field_entry * field::find_field (const field_type_id & field_type_to_find, bool alive_only = true) const
Returns a field entry corresponding to the field_type_id parameter passed in.
If no fields are found then nullptr is returned.
Parameters
alive_only if true, returns non-null result only if field is alive
Definition at line 134 of file field.cpp.
 {
     if( !_displayed_field_type ) {
         return nullptr;
     }
     const auto it = _field_type_list->find( field_type_to_find );
     if( it != _field_type_list->end() && ( !alive_only || it->second.is_field_alive() ) ) {
         return &it->second;
     }
     return nullptr;
 }
References _displayed_field_type, and _field_type_list.
remove_field() [1/2]
bool field::remove_field (const field_type_id & field_to_remove)
Removes the field entry with a type equal to the field_type_id parameter.
Make sure to decrement the field counter in the submap if (and only if) the function returns true.
Returns
True if the field was removed, false if it did not exist in the first place.
Definition at line 181 of file field.cpp.
 {
     const auto it = _field_type_list->find( field_to_remove );
     if( it == _field_type_list->end() ) {
         return false;
     }
     remove_field( it );
     return true;
 }
References _field_type_list.
Referenced by map::delete_field(), and map::process_fields_in_submap().
remove_field() [2/2]
void field::remove_field (std::map< field_type_id, field_entry >::iterator it)
Make sure to decrement the field counter in the submap.
Removes the field entry, the iterator must point into _field_type_list and must be valid.
Definition at line 191 of file field.cpp.
 {
     _field_type_list->erase( it );
     _displayed_field_type = fd_null;
     for( auto &fld : *_field_type_list ) {
         if( !_displayed_field_type || fld.first.obj().priority >= _displayed_field_type.obj().priority ) {
             _displayed_field_type = fld.first;
         }
     }
 }
References _displayed_field_type, _field_type_list, fd_null, int_id< T >::obj(), and field_type::priority.
total_move_cost()
int field::total_move_cost () const
Returns the total move cost from all fields.
Definition at line 257 of file field.cpp.
 {
     int current_cost = 0;
     for( const auto &fld : *_field_type_list ) {
         current_cost += fld.second.get_intensity_level().move_cost;
     }
     return current_cost;
 }
References _field_type_list.
Referenced by map::move_cost_internal().
Member Data Documentation
_displayed_field_type
field_type_id field::_displayed_field_type private
Definition at line 186 of file field.h.
Referenced by add_field(), clear(), displayed_description_affix(), displayed_field_type(), displayed_intensity(), find_field(), and remove_field().
_field_type_list
lazy<std::map<field_type_id, field_entry> > field::_field_type_list private
Definition at line 184 of file field.h.
Referenced by add_field(), begin(), clear(), displayed_intensity(), end(), field_count(), find_field(), remove_field(), and total_move_cost().
The documentation for this class was generated from the following files:
src/field.h
src/field.cpp