Cataclysm DDA: bite_actor Class Reference
bite_actor Class Reference
#include <mattack_actors.h>
Public Member Functions
bite_actor ()
~bite_actor () override=default
void on_damage (monster &z, Creature &target, dealt_damage_instance &dealt) const override
void load_internal (const JsonObject &obj, const std::string &src) override
std::unique_ptr< mattack_actor > clone () const override
Public Member Functions inherited from melee_actor
melee_actor ()
~melee_actor () override=default
virtual Creature * find_target (monster &z) const
int do_grab (monster &, Creature *target, bodypart_id bp_id) const
bool call (monster &) const override
Public Member Functions inherited from mattack_actor
mattack_actor (const mattack_id &new_id)
void load (const JsonObject &jo, const std::string &src)
virtual ~mattack_actor ()=default
Public Attributes
int infection_chance = 0
Public Attributes inherited from melee_actor
damage_instance damage_max_instance
float min_mul = 0.5f
float max_mul = 1.0f
int move_cost = 100
int accuracy = INT_MIN
int range = 1
bool no_adjacent = false
bool dodgeable = true
bool uncanny_dodgeable = true
bool blockable = true
bool effects_require_dmg = true
bool effects_require_organic = false
int throw_strength = 0
int hitsize_min = -1
int hitsize_max = -1
bool attack_upper = true
grab grab_data
bool is_grab = false
weighted_float_list< bodypart_str_id > body_parts
If empty, regular melee roll body part selection is used.
std::vector< mon_effect_data > effects
Extra effects applied on hit.
std::vector< mon_effect_data > self_effects_always
std::vector< mon_effect_data > self_effects_onhit
std::vector< mon_effect_data > self_effects_ondmg
translation miss_msg_u
Message for missed attack against the player.
translation no_dmg_msg_u
Message for 0 damage hit against the player.
translation hit_dmg_u
Message for damaging hit against the player.
translation throw_msg_u
Message for throwing the player.
translation miss_msg_npc
Message for missed attack against a non-player.
translation no_dmg_msg_npc
Message for 0 damage hit against a non-player.
translation hit_dmg_npc
Message for damaging hit against a non-player.
translation throw_msg_npc
Message for throwing a non-player.
Public Attributes inherited from mattack_actor
mattack_id id
bool was_loaded = false
int cooldown = 0
int attack_chance = 100
std::function< bool(dialogue &)> condition
bool has_condition = false
Additional Inherited Members
Protected Member Functions inherited from mattack_actor
mattack_actor ()=default
Detailed Description
Definition at line 189 of file mattack_actors.h.
Constructor & Destructor Documentation
bite_actor()
bite_actor::bite_actor () default
~bite_actor()
bite_actor::~bite_actor () override default
Member Function Documentation
clone()
std::unique_ptr< mattack_actor > bite_actor::clone () const override virtual
Reimplemented from melee_actor.
Definition at line 1018 of file mattack_actors.cpp.
 {
     return std::make_unique<bite_actor>( *this );
 }
load_internal()
void bite_actor::load_internal (const JsonObject & obj, const std::string & src) override virtual
Reimplemented from melee_actor.
Definition at line 969 of file mattack_actors.cpp.
 {
     // Infection chance is a % (i.e. 5/100)
     melee_actor::load_internal( obj, src );
     // If min hitsize is undefined restrict it to not biting eyes/mouths
     // Hands are fair game, though
     if( hitsize_min == -1 ) {
         hitsize_min = 1;
     }
     optional( obj, was_loaded, "infection_chance", infection_chance, 5 );
 }
References melee_actor::hitsize_min, infection_chance, melee_actor::load_internal(), optional(), and mattack_actor::was_loaded.
on_damage()
void bite_actor::on_damage (monster & z, Creature & target, dealt_damage_instance & dealt) const override virtual
Reimplemented from melee_actor.
Definition at line 981 of file mattack_actors.cpp.
 {
     melee_actor::on_damage( z, target, dealt );
     add_msg_debug( debugmode::DF_MATTACK, "Bite-type attack, infection chance %d", infection_chance );
     const bodypart_id &hit = dealt.bp_hit;
     // only do bitey things if the limb is fleshy
     if( !hit->has_flag( json_flag_BIONIC_LIMB ) ) {
         // first, do regular zombie infections
         if( x_in_y( infection_chance, 100 ) ) {
             if( target.has_effect( effect_bite, hit.id() ) ) {
                 add_msg_debug( debugmode::DF_MATTACK, "Incrementing bitten effect on %s", hit->name );
                 target.add_effect( effect_bite, 40_minutes, hit, true );
             } else if( target.has_effect( effect_infected, hit.id() ) ) {
                 add_msg_debug( debugmode::DF_MATTACK, "Incrementing infected effect on %s", hit->name );
                 target.add_effect( effect_infected, 25_minutes, hit, true );
             } else {
                 add_msg_debug( debugmode::DF_MATTACK, "Added bitten effect to %s", hit->name );
                 target.add_effect( effect_bite, 1_turns, hit, true );
             }
         }
         // Flag only set for zombies in the deadly_bites mod
         if( x_in_y( infection_chance, 20 ) ) {
             if( z.has_flag( mon_flag_DEADLY_VIRUS ) && !target.has_effect( effect_zombie_virus ) ) {
                 target.add_effect( effect_zombie_virus, 1_turns, bodypart_str_id::NULL_ID(), true );
             } else if( z.has_flag( mon_flag_VAMP_VIRUS ) && !target.has_trait( trait_VAMPIRE ) ) {
                 target.add_effect( effect_vampire_virus, 1_turns, bodypart_str_id::NULL_ID(), true );
             }
         }
         // lastly, poison it if we're yucky
         if( target.has_trait( trait_TOXICFLESH ) ) {
             z.add_effect( effect_poison, 5_minutes );
             z.add_effect( effect_badpoison, 5_minutes );
         }
     }
 }
References Creature::add_effect(), add_msg_debug, dealt_damage_instance::bp_hit, debugmode::DF_MATTACK, effect_badpoison, effect_bite, effect_infected, effect_poison, effect_vampire_virus, effect_zombie_virus, Creature::has_effect(), body_part_type::has_flag(), monster::has_flag(), Creature::has_trait(), int_id< T >::id(), infection_chance, json_flag_BIONIC_LIMB, mon_flag_DEADLY_VIRUS, mon_flag_VAMP_VIRUS, body_part_type::name, string_id< body_part_type >::NULL_ID(), melee_actor::on_damage(), trait_TOXICFLESH, trait_VAMPIRE, and x_in_y().
Member Data Documentation
infection_chance
int bite_actor::infection_chance = 0
Definition at line 194 of file mattack_actors.h.
Referenced by load_internal(), and on_damage().
The documentation for this class was generated from the following files:
src/mattack_actors.h
src/mattack_actors.cpp