Cataclysm DDA: consume_activity_actor Class Reference
consume_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
consume_activity_actor (const item_location &consume_location, std::vector< int > consume_menu_selections, const std::vector< item_location > &consume_menu_selected_items, const std::string &consume_menu_filter, activity_id type)
consume_activity_actor (const item_location &consume_location)
consume_activity_actor (const item &consume_item)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &guy) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Private Attributes
item_location consume_location
item consume_item
std::vector< int > consume_menu_selections
std::vector< item_location > consume_menu_selected_items
std::string consume_menu_filter
bool canceled = false
activity_id type
Detailed Description
Definition at line 780 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
consume_activity_actor() [1/3]
consume_activity_actor::consume_activity_actor (const item_location & consume_location, std::vector< int > consume_menu_selections, const std::vector< item_location > & consume_menu_selected_items, const std::string & consume_menu_filter, activity_id type) inline
Definition at line 799 of file activity_actor_definitions.h.
                                                                                          :
             consume_location( consume_location ),
             consume_menu_selections( std::move( consume_menu_selections ) ),
             consume_menu_selected_items( consume_menu_selected_items ),
             consume_menu_filter( consume_menu_filter ),
             type( type ) {}
consume_activity_actor() [2/3]
consume_activity_actor::consume_activity_actor (const item_location & consume_location) inline explicit
Definition at line 809 of file activity_actor_definitions.h.
                                                                                  :
             consume_location( consume_location ) {}
consume_activity_actor() [3/3]
consume_activity_actor::consume_activity_actor (const item & consume_item) inline explicit
Definition at line 812 of file activity_actor_definitions.h.
                                                                     :
             consume_item( consume_item ) {}
Member Function Documentation
can_resume_with_internal()
bool consume_activity_actor::can_resume_with_internal (const activity_actor & other, const Character &) const inline override private virtual
Precondition
other is a consume_activity_actor
Reimplemented from activity_actor.
Definition at line 793 of file activity_actor_definitions.h.
{
             const consume_activity_actor &c_actor = static_cast<const consume_activity_actor &>( other );
             return consume_location == c_actor.consume_location &&
                    canceled == c_actor.canceled && &consume_item == &c_actor.consume_item;
         }
References canceled, consume_item, consume_location, and other.
clone()
std::unique_ptr<activity_actor> consume_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 823 of file activity_actor_definitions.h.
{
             return std::make_unique<consume_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > consume_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 3250 of file activity_actor.cpp.
 {
     item_location null;
     consume_activity_actor actor( null );
     JsonObject data = jsin.get_object();
     data.read( "consume_location", actor.consume_location );
     data.read( "consume_item", actor.consume_item );
     data.read( "consume_menu_selections", actor.consume_menu_selections );
     data.read( "consume_menu_selected_items", actor.consume_menu_selected_items );
     data.read( "consume_menu_filter", actor.consume_menu_filter );
     data.read( "canceled", actor.canceled );
     data.read( "type", actor.type );
     return actor.clone();
 }
References canceled, clone(), consume_item, consume_location, consume_menu_filter, consume_menu_selected_items, consume_menu_selections, JsonValue::get_object(), JsonObject::read(), and type.
do_turn()
void consume_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 820 of file activity_actor_definitions.h.
 {}
finish()
void consume_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 3178 of file activity_actor.cpp.
 {
     // Prevent interruptions from this point onwards, so that e.g. pain from
     // injecting serum doesn't pop up messages about cancelling consuming (it's
     // too late; we've already consumed).
     act.interruptable = false;
     // Consuming an item may cause various effects, including cancelling our activity.
     // Back up these values since this activity actor might be destroyed.
     std::vector<int> temp_selections = consume_menu_selections;
     const std::vector<item_location> temp_selected_items = consume_menu_selected_items;
     const std::string temp_filter = consume_menu_filter;
     item_location consume_loc = consume_location;
     activity_id new_act = type;
     avatar &player_character = get_avatar();
     if( !canceled ) {
         if( consume_loc ) {
             player_character.consume( consume_loc, /*force=*/true );
         } else if( !consume_item.is_null() ) {
             player_character.consume( consume_item, /*force=*/true );
         } else {
             debugmsg( "Item location/name to be consumed should not be null." );
         }
         if( player_character.get_value( "THIEF_MODE_KEEP" ) != "YES" ) {
             player_character.set_value( "THIEF_MODE", "THIEF_ASK" );
         }
     }
     if( act.id() == ACT_CONSUME ) {
         act.set_to_null();
     }
     if( act.id() == ACT_FIRSTAID && consume_loc ) {
         act.targets.clear();
         act.targets.push_back( consume_loc );
     }
     if( !temp_selections.empty() || !temp_selected_items.empty() || !temp_filter.empty() ) {
         if( act.is_null() ) {
             player_character.assign_activity( new_act );
             player_character.activity.values = temp_selections;
             player_character.activity.targets = temp_selected_items;
             player_character.activity.str_values = { temp_filter, "true" };
         } else {
             // Warning: this can add a redundant menu activity to the backlog.
             // It will prevent deleting the smart pointer of the selected item_location
             // if the backlog is not sanitized.
             player_activity eat_menu( new_act );
             eat_menu.values = temp_selections;
             eat_menu.targets = temp_selected_items;
             eat_menu.str_values = { temp_filter, "true" };
             player_character.backlog.push_back( eat_menu );
         }
     }
 }
References act, ACT_CONSUME, ACT_FIRSTAID, Character::activity, Character::assign_activity(), Character::backlog, canceled, Character::consume(), consume_item, consume_location, consume_menu_filter, consume_menu_selected_items, consume_menu_selections, debugmsg, get_avatar(), Creature::get_value(), string_id< T >::id(), item::is_null(), string_id< T >::is_null(), Creature::set_value(), player_activity::str_values, player_activity::targets, type, and player_activity::values.
get_type()
activity_id consume_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 815 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_CONSUME" );
         }
References activity_id.
serialize()
void consume_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 3235 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "consume_location", consume_location );
     jsout.member( "consume_item", consume_item );
     jsout.member( "consume_menu_selections", consume_menu_selections );
     jsout.member( "consume_menu_selected_items", consume_menu_selected_items );
     jsout.member( "consume_menu_filter", consume_menu_filter );
     jsout.member( "canceled", canceled );
     jsout.member( "type", type );
     jsout.end_object();
 }
References canceled, consume_item, consume_location, consume_menu_filter, consume_menu_selected_items, consume_menu_selections, JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and type.
start()
void consume_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 3145 of file activity_actor.cpp.
 {
     int moves = 0;
     Character &player_character = get_player_character();
     if( consume_location ) {
         ret_val<edible_rating> ret = player_character.will_eat( *consume_location, true );
         if( !ret.success() ) {
             canceled = true;
             consume_menu_selections = std::vector<int>();
             consume_menu_selected_items.clear();
             consume_menu_filter.clear();
         } else {
             moves = to_moves<int>( guy.get_consume_time( *consume_location ) );
         }
     } else if( !consume_item.is_null() ) {
         ret_val<edible_rating> ret = player_character.will_eat( consume_item, true );
         if( !ret.success() ) {
             canceled = true;
             consume_menu_selections = std::vector<int>();
             consume_menu_selected_items.clear();
             consume_menu_filter.clear();
         } else {
             moves = to_moves<int>( guy.get_consume_time( consume_item ) );
         }
     } else {
         debugmsg( "Item/location to be consumed should not be null." );
         canceled = true;
     }
     act.moves_total = moves;
     act.moves_left = moves;
 }
References act, canceled, consume_item, consume_location, consume_menu_filter, consume_menu_selected_items, consume_menu_selections, debugmsg, Character::get_consume_time(), get_player_character(), item::is_null(), cata::hash64_detail::ret, and Character::will_eat().
Member Data Documentation
canceled
bool consume_activity_actor::canceled = false private
Definition at line 788 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), serialize(), and start().
consume_item
item consume_activity_actor::consume_item private
Definition at line 784 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), serialize(), and start().
consume_location
item_location consume_activity_actor::consume_location private
Definition at line 783 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), serialize(), and start().
consume_menu_filter
std::string consume_activity_actor::consume_menu_filter private
Definition at line 787 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), serialize(), and start().
consume_menu_selected_items
std::vector<item_location> consume_activity_actor::consume_menu_selected_items private
Definition at line 786 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), serialize(), and start().
consume_menu_selections
std::vector<int> consume_activity_actor::consume_menu_selections private
Definition at line 785 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), serialize(), and start().
type
activity_id consume_activity_actor::type private
Definition at line 789 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp