Cataclysm DDA: detach_gunmods_actor Class Reference
detach_gunmods_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
detach_gunmods_actor (const std::string &type="detach_gunmods")
void load (const JsonObject &) override
std::optional< int > use (Character *p, item &it, const tripoint &pnt) const override
ret_val< void > can_use (const Character &, const item &it, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void finalize (const itype_id &my_item_type) override
Finalizes the actor.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
Additional Inherited Members
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1052 of file iuse_actor.h.
Constructor & Destructor Documentation
detach_gunmods_actor()
detach_gunmods_actor::detach_gunmods_actor (const std::string & type = "detach_gunmods") inline explicit
Definition at line 1055 of file iuse_actor.h.
 : iuse_actor( type ) {}
Member Function Documentation
can_use()
ret_val< void > detach_gunmods_actor::can_use (const Character & p, const item & it, const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 4308 of file iuse_actor.cpp.
 {
     const std::vector<const item *> mods = it.gunmods();
     if( mods.empty() ) {
         return ret_val<void>::make_failure( _( "Doesn't appear to be modded." ) );
     }
     const bool no_removables =
         std::all_of( mods.begin(), mods.end(),
     []( const item * mod ) {
         return mod->is_irremovable();
     } );
     if( no_removables ) {
         return ret_val<void>::make_failure( _( "None of the mods can be removed." ) );
     }
     if( p.is_worn(
             it ) ) { // Prevent removal of shoulder straps and thereby making the gun un-wearable again.
         return ret_val<void>::make_failure( _( "Has to be taken off first." ) );
     }
     return ret_val<void>::make_success();
 }
References _, item::gunmods(), Character::is_worn(), ret_val< T >::make_failure(), ret_val< T >::make_success(), and anonymous_namespace{item_tname.cpp}::mods().
clone()
std::unique_ptr<iuse_actor> detach_gunmods_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
finalize()
void detach_gunmods_actor::finalize (const itype_id &) override virtual
Finalizes the actor.
Must be called after all items are loaded.
Reimplemented from iuse_actor.
Definition at line 4340 of file iuse_actor.cpp.
 {
     if( !item::find_type( my_item_type )->gun ) {
         debugmsg( "Item %s has detach_gunmods_actor actor, but it's a gun.", my_item_type.c_str() );
     }
 }
References string_id< T >::c_str(), debugmsg, item::find_type(), and gun.
load()
void detach_gunmods_actor::load (const JsonObject &) inline override virtual
Implements iuse_actor.
Definition at line 1057 of file iuse_actor.h.
 {}
use()
std::optional< int > detach_gunmods_actor::use (Character * p, item & it, const tripoint & pnt) const override virtual
Implements iuse_actor.
Definition at line 4255 of file iuse_actor.cpp.
 {
     auto filter_irremovable = []( std::vector<item *> &gunmods ) {
         gunmods.erase(
             std::remove_if(
         gunmods.begin(), gunmods.end(), []( const item * i ) {
             return i->is_irremovable();
         } ),
         gunmods.end() );
     };
     item gun_copy = item( it );
     std::vector<item *> mods = it.gunmods();
     std::vector<item *> mods_copy = gun_copy.gunmods();
     filter_irremovable( mods );
     filter_irremovable( mods_copy );
     item_location mod_loc = game_menus::inv::gunmod_to_remove( *p, it );
     if( !mod_loc ) {
         p->add_msg_if_player( _( "Never mind." ) );
         return std::nullopt;
     }
     // Find the index of the mod to be removed
     // used in identifying the mod in mods and mods_copy
     int mod_index = -1;
     for( size_t i = 0; i != mods.size(); ++i ) {
         if( mods[ i ] == mod_loc.get_item() ) {
             mod_index = i;
             break;
         }
     }
     if( mod_index >= 0 ) {
         gun_copy.remove_item( *mods_copy[mod_index] );
         if( p->meets_requirements( *mods[mod_index], gun_copy ) ||
             query_yn( _( "Are you sure?  You may be lacking the skills needed to reattach this modification." ) ) ) {
             if( game_menus::inv::compare_items( it, gun_copy, _( "Remove modification?" ) ) ) {
                 p->gunmod_remove( it, *mods[mod_index] );
                 return 0;
             }
         }
     }
     p->add_msg_if_player( _( "Never mind." ) );
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), game_menus::inv::compare_items(), item_location::get_item(), Character::gunmod_remove(), game_menus::inv::gunmod_to_remove(), item::gunmods(), item, Character::meets_requirements(), anonymous_namespace{item_tname.cpp}::mods(), query_yn(), and visitable::remove_item().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp