Cataclysm DDA: anonymous_namespace{messages.cpp}::messages_impl Class Reference
anonymous_namespace{messages.cpp}::messages_impl Class Reference
Public Member Functions
bool has_undisplayed_messages () const
const game_message & history (const int i) const
bool coalesce_messages (const game_message &m)
void add_msg_string (std::string &&msg)
void add_msg_string (std::string &&msg, const game_message_params &params)
void add_msg_string (std::string &&msg, game_message_type const type, const game_message_flags flags)
void hide_message_in_cooldown (game_message &message)
Check if the current message needs to be prevented (hidden) or not from being displayed in the side bar.
void modify_msg_with_exclamations (std::string &msg, game_message_type const type)
std::vector< std::pair< std::string, std::string > > recent_messages (size_t count) const
void refresh_cooldown (const game_message &message, const game_message_flags flags)
Refresh the cooldown timers, removing elapsed ones and making new ones if needed.
Public Attributes
std::deque< game_message > messages
std::vector< game_message > cooldown_templates
time_point curmes = calendar::turn_zero
bool active = true
Detailed Description
Definition at line 115 of file messages.cpp.
Member Function Documentation
add_msg_string() [1/3]
void anonymous_namespace{messages.cpp}::messages_impl::add_msg_string (std::string && msg) inline
Definition at line 164 of file messages.cpp.
{
             add_msg_string( std::move( msg ), m_neutral, gmf_none );
         }
References gmf_none, and m_neutral.
Referenced by Messages::add_msg().
add_msg_string() [2/3]
void anonymous_namespace{messages.cpp}::messages_impl::add_msg_string (std::string && msg, const game_message_params & params) inline
Definition at line 168 of file messages.cpp.
{
             add_msg_string( std::move( msg ), params.type, params.flags );
         }
References game_message_params::flags, and game_message_params::type.
add_msg_string() [3/3]
void anonymous_namespace{messages.cpp}::messages_impl::add_msg_string (std::string && msg, game_message_type const type, const game_message_flags flags) inline
Definition at line 172 of file messages.cpp.
{
             if( msg.empty() || !active ) {
                 return;
             }
             if( type == m_debug && !debug_mode ) {
                 return;
             }
             modify_msg_with_exclamations( msg, type );
             game_message m = game_message( std::move( msg ), type );
             refresh_cooldown( m, flags );
             hide_message_in_cooldown( m );
             if( coalesce_messages( m ) ) {
                 return;
             }
             unsigned int message_limit = get_option<int>( "MESSAGE_LIMIT" );
             while( messages.size() > message_limit ) {
                 messages.pop_front();
             }
             messages.emplace_back( m );
         }
References active, debug_mode, m_debug, modify_msg_with_exclamations(), and type.
coalesce_messages()
bool anonymous_namespace{messages.cpp}::messages_impl::coalesce_messages (const game_message & m) inline
Definition at line 132 of file messages.cpp.
{
             if( messages.empty() ) {
                 return false;
             }
             auto &last_msg = messages.back();
             if( last_msg.turn() + 3_turns < calendar::turn ) {
                 return false;
             }
             if( m.type != last_msg.type || m.message != last_msg.message ) {
                 return false;
             }
             // update the cooldown message timer due to coalescing
             const auto cooldown_it = std::find_if( cooldown_templates.begin(), cooldown_templates.end(),
             [&m]( game_message & am ) -> bool {
                 return m.message == am.message;
             } );
             if( cooldown_it != cooldown_templates.end() ) {
                 cooldown_it->timestamp_in_turns = calendar::turn;
             }
             // coalesce messages
             last_msg.count++;
             last_msg.timestamp_in_turns = calendar::turn;
             last_msg.timestamp_in_user_actions = g->get_user_action_counter();
             last_msg.type = m.type;
             return true;
         }
References g, anonymous_namespace{messages.cpp}::game_message::message, calendar::turn, and anonymous_namespace{messages.cpp}::game_message::type.
has_undisplayed_messages()
bool anonymous_namespace{messages.cpp}::messages_impl::has_undisplayed_messages () const inline
Definition at line 123 of file messages.cpp.
{
             return !messages.empty() && messages.back().turn() > curmes;
         }
Referenced by Messages::has_undisplayed_messages().
hide_message_in_cooldown()
void anonymous_namespace{messages.cpp}::messages_impl::hide_message_in_cooldown (game_message & message) inline
Check if the current message needs to be prevented (hidden) or not from being displayed in the side bar.
Parameters
message The message to be checked.
Definition at line 204 of file messages.cpp.
{
             message.cooldown_hidden = false;
             if( message_cooldown <= 0 || message.turn() <= calendar::turn_zero ) {
                 return;
             }
             // We look for **exactly the same** message string in the cooldown templates
             // If there is one, this means the same message was already displayed.
             const auto cooldown_it = std::find_if( cooldown_templates.begin(), cooldown_templates.end(),
             [&message]( game_message & m_cooldown ) -> bool {
                 return m_cooldown.message == message.message;
             } );
             if( cooldown_it == cooldown_templates.end() ) {
                 // nothing found, not in cooldown.
                 return;
             }
             // note: from this point the current message (`message`) has the same string than one of the active cooldown template messages (`cooldown_it`).
             // check how much times this message has been seen during its cooldown.
             // If it's only one time, then no need to hide it.
             if( cooldown_it->cooldown_seen == 1 ) {
                 return;
             }
             // check if it's the message that started the cooldown timer.
             if( message.turn() == cooldown_it->turn() ) {
                 return;
             }
             // current message turn.
             const int cm_turn = to_turn<int>( message.turn() );
             // maximum range of the cooldown timer.
             const int max_cooldown_range = to_turn<int>( cooldown_it->turn() ) + message_cooldown;
             // If the current message is in the cooldown range then hide it.
             if( cm_turn <= max_cooldown_range ) {
                 message.cooldown_hidden = true;
             }
         }
References mapgen_defer::message, message_cooldown, and calendar::turn_zero.
history()
const game_message& anonymous_namespace{messages.cpp}::messages_impl::history (const int i) const inline
Definition at line 127 of file messages.cpp.
{
             return messages[messages.size() - i - 1];
         }
Referenced by Messages::dialog::do_filter(), Messages::dialog::init(), and Messages::dialog::show().
modify_msg_with_exclamations()
void anonymous_namespace{messages.cpp}::messages_impl::modify_msg_with_exclamations (std::string & msg, game_message_type const type) inline
Definition at line 245 of file messages.cpp.
{
             // add smileys to messages if the player is high on weed
             Character *p_char = &get_player_character();
             if( !p_char->has_effect( effect_weed_high ) ) {
                 return;
             }
             const time_duration weed_dur = p_char->get_effect_dur( effect_weed_high );
             const float in_minutes = to_minutes<float>( weed_dur );
             // we will now calculate how often smiley faces should appear in messages.
             // Slowly rises. 0 at 0, 1 at 22.5, 2 at 45 mins. Asymptote at 3.
             const float max_per_msg = 3 - 3 / ( 1 + 0.001 * in_minutes * in_minutes );
             //possible values for smiles_for_this_msg are 0,1,2,3.
             int smiles_for_this_msg = static_cast<int>( round( rng_normal( 0, max_per_msg ) ) );
             // now insert the smiley face somewhere in the msg string. We want to avoid breaking up words, so we will only replace spaces.
             // find all suitable locations for smiley. That is, end of message + all spaces (except after certain words)
             std::vector<size_t> smiley_locations;
             // we also need to track space locations to extract words properly. Annoying but necessary.
             std::vector<size_t> space_locations;
             // end of msg
             smiley_locations.push_back( msg.size() );
             // now all spaces
             for( size_t j = 0; j < msg.size(); j++ ) {
                 if( msg[j] == ' ' ) {
                     bool wordskip = false;
                     // fancy logic. It's weird if the smiley comes after "to" or "that" or "a". Let's try and skip words like those.
                     // We skip all short words (<=3 letters), and all words in the forbidden_words array.
                     if( !space_locations.empty() ) {
                         const size_t prev_space = space_locations.back();
                         // if prev_space is the previous char, skip
                         if( prev_space == j - 1 ) {
                             wordskip = true;
                         }
                         // check that smiley_locations.back() did not return none
                         if( prev_space != std::string::npos ) {
                             const std::string word = msg.substr( prev_space, j - prev_space );
                             const std::array<std::string, 6> forbidden_words = { " that", " with", " this", " over", " your", " onto" };
                             for( const std::string &forbidden_word : forbidden_words ) {
                                 if( word == forbidden_word ) {
                                     wordskip = true;
                                     break;
                                 }
                             }
                             if( word.size() > 1 && word.size() <= 4 ) {
                                 wordskip = true;
                             }
                         }
                     } else {
                         // skip very first word
                         wordskip = true;
                     }
                     space_locations.push_back( j );
                     if( !wordskip ) {
                         smiley_locations.push_back( j );
                     }
                 }
             }
             // first, check if smiles_for_this_msg == len(smiley_locations)
             if( smiles_for_this_msg >= static_cast<int>( smiley_locations.size() ) ) {
                 smiles_for_this_msg = static_cast<int>( smiley_locations.size() ) - 1;
             }
             // then pick one at random
             for( int i = 0; i < smiles_for_this_msg; i++ ) {
                 const size_t smiley_location = random_entry_removed( smiley_locations );
                 std::string smiley_string = " :)";
                 if( type == m_good || type == m_critical ) {
                     if( one_in( 5 ) ) {
                         smiley_string = " :D";
                     }
                 }
                 msg.insert( smiley_location, smiley_string );
                 //for( size_t j = 0; j < smiley_locations.size(); j++ ) {
                 // modernize-loop-convert. Use range-based for loop instead.
                 for( size_t &smil_loc : smiley_locations ) {
                     if( smil_loc > smiley_location ) {
                         // we increment to account for the insertion of the smiley string
                         smil_loc += 3;
                     }
                 }
             }
             // if we are *very* high, there will be a chance to finish a long message with an exclamation
             if( smiles_for_this_msg > 1 ) {
                 int woah_chance = static_cast<int>( 10 / smiles_for_this_msg );
                 if( msg.size() > 16 && one_in( woah_chance ) ) {
                     std::vector<std::string> exclamations = {
                         "Woah.", "Dude."
                     };
                     std::vector<std::string> good_exclamations = {
                         "Cool!", "Wicked!", "Awesome!"
                     };
                     std::vector<std::string> bad_exclamations = {
                         "Not cool.", "Oof.", "Bummer."
                     };
                     if( type == m_good || type == m_critical || type == m_headshot ) {
                         msg += " " + random_entry( good_exclamations );
                     } else if( type == m_bad || type == m_grazing ) {
                         msg += " " + random_entry( bad_exclamations );
                     } else {
                         msg += " " + random_entry( exclamations );
                     }
                 }
             }
         }
References effect_weed_high, Creature::get_effect_dur(), get_player_character(), Creature::has_effect(), m_bad, m_critical, m_good, m_grazing, m_headshot, one_in(), random_entry(), random_entry_removed(), rng_normal(), round(), and type.
recent_messages()
std::vector<std::pair<std::string, std::string> > anonymous_namespace{messages.cpp}::messages_impl::recent_messages (size_t count) const inline
Definition at line 352 of file messages.cpp.
{
             count = std::min( count, messages.size() );
             std::vector<std::pair<std::string, std::string>> result;
             result.reserve( count );
             const int offset = static_cast<std::ptrdiff_t>( messages.size() - count );
             std::transform( begin( messages ) + offset, end( messages ), back_inserter( result ),
             []( const game_message & msg ) {
                 return std::make_pair( to_string_time_of_day( msg.timestamp_in_turns ),
                                        msg.get_with_count() );
             } );
             return result;
         }
References keycode::end, anonymous_namespace{messages.cpp}::game_message::get_with_count(), min(), anonymous_namespace{messages.cpp}::game_message::timestamp_in_turns, and to_string_time_of_day().
Referenced by Messages::recent_messages().
refresh_cooldown()
void anonymous_namespace{messages.cpp}::messages_impl::refresh_cooldown (const game_message & message, const game_message_flags flags) inline
Refresh the cooldown timers, removing elapsed ones and making new ones if needed.
Parameters
message The current message that needs to be checked.
flags Flags pertaining to the message.
Definition at line 373 of file messages.cpp.
{
             // is cooldown used? (also checks for messages arriving here at game initialization: we don't care about them).
             if( message_cooldown <= 0 || message.turn() <= calendar::turn_zero ) {
                 return;
             }
             // housekeeping: remove any cooldown message with an expired cooldown time from the cooldown queue.
             const time_point now = calendar::turn;
             for( auto it = cooldown_templates.begin(); it != cooldown_templates.end(); ) {
                 // number of turns elapsed since the cooldown started.
                 const int turns = to_turns<int>( now - it->turn() );
                 if( turns >= message_cooldown ) {
                     // time elapsed! remove it.
                     it = cooldown_templates.erase( it );
                 } else {
                     ++it;
                 }
             }
             // do not hide messages which bypasses cooldown.
             if( ( flags & gmf_bypass_cooldown ) != 0 ) {
                 return;
             }
             // Is the message string already in the cooldown queue?
             // If it's not we must put it in the cooldown queue now, otherwise just increment the number of times we have seen it.
             const auto cooldown_message_it = std::find_if( cooldown_templates.begin(),
             cooldown_templates.end(), [&message]( game_message & cooldown_message ) -> bool {
                 return cooldown_message.message == message.message;
             } );
             if( cooldown_message_it == cooldown_templates.end() ) {
                 // push current message to cooldown message templates.
                 cooldown_templates.emplace_back( message );
             } else {
                 // increment the number of time we have seen this message.
                 cooldown_message_it->cooldown_seen++;
             }
         }
References gmf_bypass_cooldown, mapgen_defer::message, message_cooldown, calendar::turn, and calendar::turn_zero.
Member Data Documentation
active
bool anonymous_namespace{messages.cpp}::messages_impl::active = true
Definition at line 121 of file messages.cpp.
Referenced by Messages::clear_messages(), and Messages::deactivate().
cooldown_templates
std::vector<game_message> anonymous_namespace{messages.cpp}::messages_impl::cooldown_templates
Definition at line 119 of file messages.cpp.
curmes
time_point anonymous_namespace{messages.cpp}::messages_impl::curmes = calendar::turn_zero
Definition at line 120 of file messages.cpp.
Referenced by Messages::deserialize(), Messages::display_messages(), and Messages::serialize().
messages
std::deque<game_message> anonymous_namespace{messages.cpp}::messages_impl::messages
Definition at line 118 of file messages.cpp.
Referenced by Messages::clear_messages(), Messages::deserialize(), Messages::display_messages(), Messages::serialize(), and Messages::size().
The documentation for this class was generated from the following file:
src/messages.cpp