Cataclysm DDA: prying_activity_actor Class Reference
prying_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
prying_activity_actor (const tripoint &target, const item_location &tool)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static time_duration prying_time (const activity_data_common &data, const item_location &tool, const Character &who)
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Public Attributes
bool testing = false
Private Member Functions
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
void handle_prying (Character &who)
void handle_prying_nails (Character &who)
Private Attributes
tripoint target
item_location tool
bool prying_nails = false
Detailed Description
Definition at line 1463 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
prying_activity_actor()
prying_activity_actor::prying_activity_actor (const tripoint & target, const item_location & tool) inline explicit
Definition at line 1466 of file activity_actor_definitions.h.
                                                                     : target( target ), tool( tool ) {};
Member Function Documentation
can_resume_with_internal()
bool prying_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override private virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 1494 of file activity_actor_definitions.h.
{
             const prying_activity_actor &actor = static_cast<const prying_activity_actor &>
                                                  ( other );
             return actor.target == target;
         }
References other, and target.
clone()
std::unique_ptr<activity_actor> prying_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1480 of file activity_actor_definitions.h.
{
             return std::make_unique<prying_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > prying_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 5935 of file activity_actor.cpp.
 {
     prying_activity_actor actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "target", actor.target );
     data.read( "tool", actor.tool );
     data.read( "prying_nails", actor.prying_nails );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void prying_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 5692 of file activity_actor.cpp.
 {
     std::string method = "CROWBAR";
     if( tool->ammo_sufficient( &who, method ) ) {
         int ammo_consumed = tool->ammo_required();
         std::map<std::string, int>::const_iterator iter = tool->type->ammo_scale.find( method );
         if( iter != tool->type->ammo_scale.end() ) {
             ammo_consumed *= iter->second;
         }
         tool->ammo_consume( ammo_consumed, tool.position(), &who );
         if( prying_nails ) {
             sfx::play_activity_sound( "tool", "hammer", sfx::get_heard_volume( target ) );
         }
     } else {
         if( who.is_avatar() ) {
             who.add_msg_if_player( m_bad, _( "Your %1$s ran out of charges." ), tool->tname() );
         } else { // who.is_npc()
             add_msg_if_player_sees( who.pos(), _( "%1$s %2$s ran out of charges." ), who.disp_name( false,
                                     true ), tool->tname() );
         }
         who.cancel_activity();
     }
 }
References _, Character::add_msg_if_player(), add_msg_if_player_sees(), item::ammo_consume(), item::ammo_required(), itype::ammo_scale, item::ammo_sufficient(), Character::cancel_activity(), Character::disp_name(), sfx::get_heard_volume(), Creature::is_avatar(), m_bad, sfx::play_activity_sound(), Creature::pos(), item_location::position(), prying_nails, target, item::tname(), tool, and item::type.
finish()
void prying_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 5915 of file activity_actor.cpp.
 {
     act.set_to_null();
     if( prying_nails ) {
         handle_prying_nails( who );
     } else {
         handle_prying( who );
     }
 }
References act, handle_prying(), handle_prying_nails(), and prying_nails.
get_type()
activity_id prying_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1469 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_PRYING" );
         }
References activity_id.
handle_prying()
void prying_activity_actor::handle_prying (Character & who) private
@ARM_STR increases chance of prying success
Mechanics reduces chance of breaking when prying
@ARM_STR reduces chance of breaking when prying
Definition at line 5717 of file activity_actor.cpp.
 {
     map &here = get_map();
     const activity_data_common *data;
     // check if Character passed the difficulty check
     auto difficulty_check = [&]( const activity_data_common & data ) -> bool {
         const pry_data &pdata = data.prying_data();
         int difficulty = pdata.difficulty;
         difficulty -= tool->get_quality( qual_PRY ) - pdata.prying_level;
         /** @ARM_STR increases chance of prying success */
         const int dice_str = dice( 4, who.get_arm_str() );
         return dice( 4, difficulty ) < dice_str;
     };
     auto handle_failure = [&]( const pry_data & pdata ) -> void {
         if( !pdata.breakable )
         {
             return;
         }
         int difficulty = pdata.difficulty;
         difficulty -= tool->get_quality( qual_PRY ) - pdata.prying_level;
         /** @EFFECT_MECHANICS reduces chance of breaking when prying */
         const int dice_mech = dice( 2, static_cast<int>( round( who.get_skill_level( skill_mechanics ) ) ) );
         /** @ARM_STR reduces chance of breaking when prying */
         const int dice_str = dice( 2, who.get_arm_str() );
         if( dice( 4, difficulty ) > dice_mech + dice_str )
         {
             // bash will always succeed
             here.bash( target, 0, false, true );
         }
         if( !data->prying_data().failure.empty() )
         {
             who.add_msg_if_player( m_info, data->prying_data().failure.translated() );
         }
     };
     if( here.has_furn( target ) ) {
         const furn_id furn_type = here.furn( target );
         if( !furn_type->prying->valid() ) {
             if( !testing ) {
                 debugmsg( "%s prying is invalid", furn_type.id().str() );
             }
             return;
         }
         data = static_cast<const activity_data_common *>( &*furn_type->prying );
         if( !difficulty_check( *furn_type->prying ) ) {
             handle_failure( furn_type->prying->prying_data() );
             return;
         }
         const furn_str_id new_furn = furn_type->prying->result();
         if( !new_furn.is_valid() ) {
             if( !testing ) {
                 debugmsg( "prying furniture: %s invalid furniture", new_furn.str() );
             }
             return;
         }
         here.furn_set( target, new_furn );
     } else if( !here.ter( target )->is_null() ) {
         const ter_id ter_type = here.ter( target );
         if( !ter_type->prying->valid() ) {
             if( !testing ) {
                 debugmsg( "%s prying is invalid", ter_type.id().str() );
             }
             return;
         }
         data = static_cast<const activity_data_common *>( &*ter_type->prying );
         if( !difficulty_check( *ter_type->prying ) ) {
             handle_failure( ter_type->prying->prying_data() );
             return;
         }
         const ter_str_id new_ter = ter_type->prying->result();
         if( !new_ter.is_valid() ) {
             if( !testing ) {
                 debugmsg( "prying terrain: %s invalid terrain", new_ter.str() );
             }
             return;
         }
         here.ter_set( target, new_ter );
     } else {
         if( !testing ) {
             debugmsg( "prying activity finished on invalid terrain" );
         }
         return;
     }
     for( const activity_byproduct &byproduct : data->byproducts() ) {
         const int amount = byproduct.roll();
         if( byproduct.item->count_by_charges() ) {
             item byproduct_item( byproduct.item, calendar::turn, amount );
             here.add_item_or_charges( target, byproduct_item );
         } else {
             item byproduct_item( byproduct.item, calendar::turn );
             for( int i = 0; i < amount; ++i ) {
                 here.add_item_or_charges( target, byproduct_item );
             }
         }
     }
     const pry_data &pdata = data->prying_data();
     if( pdata.noisy ) {
         sounds::sound( target, 12, sounds::sound_t::combat, _( "crunch!" ), true, "tool", "crowbar" );
     }
     if( pdata.alarm ) {
         get_event_bus().send<event_type::triggers_alarm>( who.getID() );
         sounds::sound( who.pos(), 40, sounds::sound_t::alarm, _( "an alarm sound!" ), true, "environment",
                        "alarm" );
     }
     if( !data->message().empty() ) {
         who.add_msg_if_player( m_info, data->message().translated() );
     }
 }
References _, map::add_item_or_charges(), Character::add_msg_if_player(), pry_data::alarm, sounds::alarm, map::bash(), activity_data_common::byproducts(), sounds::combat, debugmsg, dice(), pry_data::difficulty, translation::empty(), pry_data::failure, map::furn(), map::furn_set(), Character::get_arm_str(), get_event_bus(), get_map(), item::get_quality(), Character::get_skill_level(), Character::getID(), map::has_furn(), int_id< T >::id(), ter_t::is_null(), string_id< T >::is_valid(), m_info, activity_data_common::message(), pry_data::noisy, Creature::pos(), ter_t::prying, furn_t::prying, activity_data_common::prying_data(), pry_data::prying_level, qual_PRY, round(), event_bus::send(), skill_mechanics, sounds::sound(), string_id< T >::str(), target, map::ter(), map::ter_set(), testing, tool, translation::translated(), triggers_alarm, and calendar::turn.
Referenced by finish().
handle_prying_nails()
void prying_activity_actor::handle_prying_nails (Character & who) private
Definition at line 5845 of file activity_actor.cpp.
 {
     map &here = get_map();
     const activity_data_common *data;
     if( here.has_furn( target ) ) {
         const furn_id furn_type = here.furn( target );
         if( !furn_type->prying->valid() ) {
             if( !testing ) {
                 debugmsg( "%s prying is invalid", furn_type.id().str() );
             }
             return;
         }
         const furn_str_id new_furn = furn_type->prying->result();
         if( !new_furn.is_valid() ) {
             if( !testing ) {
                 debugmsg( "prying furniture: %s invalid furniture", new_furn.str() );
             }
             return;
         }
         data = static_cast<const activity_data_common *>( &*furn_type->prying );
         here.furn_set( target, new_furn );
     } else if( !here.ter( target )->is_null() ) {
         const ter_id ter_type = here.ter( target );
         if( !ter_type->prying->valid() ) {
             if( !testing ) {
                 debugmsg( "%s prying is invalid", ter_type.id().str() );
             }
             return;
         }
         const ter_str_id new_ter = ter_type->prying->result();
         if( !new_ter.is_valid() ) {
             if( !testing ) {
                 debugmsg( "prying terrain: %s invalid terrain", new_ter.str() );
             }
             return;
         }
         data = static_cast<const activity_data_common *>( &*ter_type->prying );
         here.ter_set( target, new_ter );
     } else {
         if( !testing ) {
             debugmsg( "prying nails activity finished on invalid terrain" );
         }
         return;
     }
     for( const activity_byproduct &byproduct : data->byproducts() ) {
         const int amount = byproduct.roll();
         if( byproduct.item->count_by_charges() ) {
             item byproduct_item( byproduct.item, calendar::turn, amount );
             here.add_item_or_charges( target, byproduct_item );
         } else {
             item byproduct_item( byproduct.item, calendar::turn );
             for( int i = 0; i < amount; ++i ) {
                 here.add_item_or_charges( target, byproduct_item );
             }
         }
     }
     if( !data->message().empty() ) {
         who.add_msg_if_player( m_info, data->message().translated() );
     }
     who.practice( skill_fabrication, 1, 1 );
 }
References map::add_item_or_charges(), Character::add_msg_if_player(), activity_data_common::byproducts(), debugmsg, translation::empty(), map::furn(), map::furn_set(), get_map(), map::has_furn(), int_id< T >::id(), ter_t::is_null(), string_id< T >::is_valid(), m_info, activity_data_common::message(), Character::practice(), ter_t::prying, furn_t::prying, skill_fabrication, string_id< T >::str(), target, map::ter(), map::ter_set(), testing, translation::translated(), and calendar::turn.
Referenced by finish().
prying_time()
time_duration prying_activity_actor::prying_time (const activity_data_common & data, const item_location & tool, const Character & who) static
@ARM_STR speeds up crowbar prying attempts
Definition at line 5629 of file activity_actor.cpp.
 {
     const pry_data &pdata = data.prying_data();
     if( pdata.prying_nails ) {
         return data.duration();
     }
     int difficulty = pdata.difficulty;
     difficulty -= tool->get_quality( qual_PRY ) - pdata.prying_level;
     return time_duration::from_seconds(
                /** @ARM_STR speeds up crowbar prying attempts */
                std::max( 5, 2 * ( 4 * difficulty - who.get_arm_str() ) ) );
 }
References pry_data::difficulty, activity_data_common::duration(), time_duration::from_seconds(), Character::get_arm_str(), item::get_quality(), max(), activity_data_common::prying_data(), pry_data::prying_level, pry_data::prying_nails, qual_PRY, and tool.
Referenced by start().
serialize()
void prying_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 5926 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target", target );
     jsout.member( "tool", tool );
     jsout.member( "prying_nails", prying_nails );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), prying_nails, JsonOut::start_object(), target, and tool.
start()
void prying_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 5644 of file activity_actor.cpp.
 {
     const map &here = get_map();
     if( here.has_furn( target ) ) {
         const furn_id furn_type = here.furn( target );
         if( !furn_type->prying->valid() ) {
             if( !testing ) {
                 debugmsg( "%s prying is invalid", furn_type.id().str() );
             }
             act.set_to_null();
             return;
         }
         prying_nails = furn_type->prying->prying_data().prying_nails;
         act.moves_total = to_moves<int>(
                               prying_time( *furn_type->prying, tool, who ) );
     } else if( !here.ter( target )->is_null() ) {
         const ter_id ter_type = here.ter( target );
         if( !ter_type->prying->valid() ) {
             if( !testing ) {
                 debugmsg( "%s prying is invalid", ter_type.id().str() );
             }
             act.set_to_null();
             return;
         }
         prying_nails = ter_type->prying->prying_data().prying_nails;
         act.moves_total = to_moves<int>(
                               prying_time( *ter_type->prying, tool, who ) );
     } else {
         if( !testing ) {
             debugmsg( "prying activity called on invalid terrain" );
         }
         act.set_to_null();
         return;
     }
     if( prying_nails && !tool->has_quality( qual_PRYING_NAIL ) ) {
         who.add_msg_if_player( _( "You can't use your %1$s to pry up the nails." ), tool->tname() );
         act.set_to_null();
         return;
     }
     add_msg_debug( debugmode::DF_ACTIVITY, "%s moves_total: %d", act.id().str(), act.moves_total );
     act.moves_left = act.moves_total;
 }
References _, act, add_msg_debug, Character::add_msg_if_player(), debugmsg, debugmode::DF_ACTIVITY, map::furn(), get_map(), map::has_furn(), visitable::has_quality(), int_id< T >::id(), string_id< T >::id(), ter_t::is_null(), ter_t::prying, furn_t::prying, prying_nails, prying_time(), qual_PRYING_NAIL, string_id< T >::str(), target, map::ter(), testing, item::tname(), and tool.
Member Data Documentation
prying_nails
bool prying_activity_actor::prying_nails = false private
Definition at line 1492 of file activity_actor_definitions.h.
Referenced by do_turn(), finish(), serialize(), and start().
target
tripoint prying_activity_actor::target private
Definition at line 1490 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), do_turn(), handle_prying(), handle_prying_nails(), serialize(), and start().
testing
bool prying_activity_actor::testing = false
Definition at line 1488 of file activity_actor_definitions.h.
Referenced by handle_prying(), handle_prying_nails(), and start().
tool
item_location prying_activity_actor::tool private
Definition at line 1491 of file activity_actor_definitions.h.
Referenced by do_turn(), handle_prying(), prying_time(), serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp