Cataclysm DDA: cata::clone_ptr< T > Class Template Reference
cata::clone_ptr< T > Class Template Reference
#include <clone_ptr.h>
Public Member Functions
clone_ptr ()=default
clone_ptr (std::nullptr_t)
clone_ptr (const clone_ptr &other)
clone_ptr (clone_ptr &&) noexcept=default
clone_ptr & operator= (const clone_ptr &other)
clone_ptr & operator= (clone_ptr &&) noexcept=default
template<typename U >
clone_ptr (std::unique_ptr< U > p)
T & operator* ()
const T & operator* () const
T * operator-> ()
const T * operator-> () const
T * get ()
const T * get () const
operator bool () const
bool operator! () const
Private Attributes
std::unique_ptr< T > p_
Friends
bool operator== (const clone_ptr &l, const clone_ptr &r)
bool operator!= (const clone_ptr &l, const clone_ptr &r)
Detailed Description
template<typename T>
class cata::clone_ptr< T >
Definition at line 11 of file clone_ptr.h.
Constructor & Destructor Documentation
clone_ptr() [1/5]
template<typename T > cata::clone_ptr< T >::clone_ptr () default
clone_ptr() [2/5]
template<typename T > cata::clone_ptr< T >::clone_ptr (std::nullptr_t) inline
Definition at line 16 of file clone_ptr.h.
 {}
clone_ptr() [3/5]
template<typename T > cata::clone_ptr< T >::clone_ptr (const clone_ptr< T > & other) inline
Definition at line 18 of file clone_ptr.h.
 : p_( other.p_ ? other.p_->clone() : nullptr ) {}
References other.
clone_ptr() [4/5]
template<typename T > cata::clone_ptr< T >::clone_ptr (clone_ptr< T > &&) default noexcept
clone_ptr() [5/5]
template<typename T > template<typename U > cata::clone_ptr< T >::clone_ptr (std::unique_ptr< U > p) inline
Definition at line 29 of file clone_ptr.h.
 : p_( std::move( p ) ) {}
Member Function Documentation
get() [1/2]
template<typename T > T* cata::clone_ptr< T >::get () inline
Definition at line 43 of file clone_ptr.h.
                  {
             return p_.get();
         }
References cata::clone_ptr< T >::p_.
Referenced by mtype_special_attack::get(), use_function::get_actor_ptr(), and mtype_special_attack::operator->().
get() [2/2]
template<typename T > const T* cata::clone_ptr< T >::get () const inline
Definition at line 46 of file clone_ptr.h.
{
             return p_.get();
         }
References cata::clone_ptr< T >::p_.
operator bool()
template<typename T > cata::clone_ptr< T >::operator bool () const inline explicit
Definition at line 50 of file clone_ptr.h.
{
             return !!*this;
         }
operator!()
template<typename T > bool cata::clone_ptr< T >::operator! () const inline
Definition at line 53 of file clone_ptr.h.
{
             return !p_;
         }
References cata::clone_ptr< T >::p_.
operator*() [1/2]
template<typename T > T& cata::clone_ptr< T >::operator* () inline
Definition at line 31 of file clone_ptr.h.
{
             return *p_;
         }
References cata::clone_ptr< T >::p_.
operator*() [2/2]
template<typename T > const T& cata::clone_ptr< T >::operator* () const inline
Definition at line 34 of file clone_ptr.h.
{
             return *p_;
         }
References cata::clone_ptr< T >::p_.
operator->() [1/2]
template<typename T > T* cata::clone_ptr< T >::operator-> () inline
Definition at line 37 of file clone_ptr.h.
{
             return p_.get();
         }
References cata::clone_ptr< T >::p_.
operator->() [2/2]
template<typename T > const T* cata::clone_ptr< T >::operator-> () const inline
Definition at line 40 of file clone_ptr.h.
{
             return p_.get();
         }
References cata::clone_ptr< T >::p_.
operator=() [1/2]
template<typename T > clone_ptr& cata::clone_ptr< T >::operator= (clone_ptr< T > &&) default noexcept
operator=() [2/2]
template<typename T > clone_ptr& cata::clone_ptr< T >::operator= (const clone_ptr< T > & other) inline
Definition at line 20 of file clone_ptr.h.
{
             p_ = other.p_ ? other.p_->clone() : nullptr;
             return *this;
         }
References other, and cata::clone_ptr< T >::p_.
Friends And Related Function Documentation
operator!=
template<typename T > bool operator!= (const clone_ptr< T > & l, const clone_ptr< T > & r) friend
Definition at line 60 of file clone_ptr.h.
{
             return l.p_ != r.p_;
         }
operator==
template<typename T > bool operator== (const clone_ptr< T > & l, const clone_ptr< T > & r) friend
Definition at line 57 of file clone_ptr.h.
{
             return l.p_ == r.p_;
         }
Member Data Documentation
p_
template<typename T > std::unique_ptr<T> cata::clone_ptr< T >::p_ private
Definition at line 64 of file clone_ptr.h.
Referenced by cata::clone_ptr< T >::get(), cata::clone_ptr< T >::operator!(), cata::clone_ptr< T >::operator*(), cata::clone_ptr< T >::operator->(), and cata::clone_ptr< T >::operator=().
The documentation for this class was generated from the following file:
src/clone_ptr.h