Cataclysm DDA: pickup_menu_activity_actor Class Reference
pickup_menu_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
pickup_menu_activity_actor (std::optional< tripoint > where, std::vector< drop_location > selection)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &)
Private Attributes
std::optional< tripoint > where
std::vector< drop_location > selection
Detailed Description
Definition at line 1783 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
pickup_menu_activity_actor()
pickup_menu_activity_actor::pickup_menu_activity_actor (std::optional< tripoint > where, std::vector< drop_location > selection) inline
Definition at line 1786 of file activity_actor_definitions.h.
                                                                          : where( where ),
             selection( std::move( selection ) ) {};
Member Function Documentation
clone()
std::unique_ptr<activity_actor> pickup_menu_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1797 of file activity_actor_definitions.h.
{
             return std::make_unique<pickup_menu_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > pickup_menu_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6214 of file activity_actor.cpp.
 {
     pickup_menu_activity_actor actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "where", actor.where );
     data.read( "selection", actor.selection );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void pickup_menu_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 6196 of file activity_actor.cpp.
 {
     std::optional<tripoint> p( where );
     std::vector<drop_location> s( selection );
     who.cancel_activity();
     who.pick_up( game_menus::inv::pickup( *who.as_avatar(), p, s ) );
 }
References Creature::as_avatar(), Character::cancel_activity(), Character::pick_up(), game_menus::inv::pickup(), selection, and where.
finish()
void pickup_menu_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1795 of file activity_actor_definitions.h.
 {};
get_type()
activity_id pickup_menu_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1789 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_PICKUP_MENU" );
         }
References activity_id.
serialize()
void pickup_menu_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6204 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "where", where );
     jsout.member( "selection", selection );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), selection, JsonOut::start_object(), and where.
start()
void pickup_menu_activity_actor::start (player_activity & act, Character & who) inline override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1793 of file activity_actor_definitions.h.
 {};
Member Data Documentation
selection
std::vector<drop_location> pickup_menu_activity_actor::selection private
Definition at line 1806 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
where
std::optional<tripoint> pickup_menu_activity_actor::where private
Definition at line 1805 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp