Cataclysm DDA: vehicle::autodrive_controller Class Reference
vehicle::autodrive_controller Class Reference
Public Member Functions
autodrive_controller (const vehicle &driven_veh, const Character &driver)
const Character & get_driver ()
const auto_navigation_data & get_data ()
void check_safe_speed ()
std::optional< navigation_step > compute_next_step ()
collision_check_result check_collision_zone (orientation turn_dir)
void reduce_speed ()
Private Member Functions
void compute_coordinates ()
bool check_drivable (const tripoint_bub_ms &pt) const
void compute_obstacles ()
void enqueue_if_ramp (point_queue &ramp_points, const map &here, const tripoint_bub_ms &p) const
void compute_obstacles_from_enqueued_ramp_points (point_queue &ramp_points, const map &here)
vehicle_profile compute_profile (orientation facing) const
void compute_valid_positions ()
void compute_goal_zone ()
void precompute_data ()
scored_address compute_node_score (const node_address &addr, const navigation_node &node) const
void compute_next_nodes (const node_address &addr, const navigation_node &node, int target_speed_tps, std::vector< std::pair< node_address, navigation_node >> &next_nodes) const
std::optional< std::vector< navigation_step > > compute_path (int speed_tps) const
Private Attributes
const vehicle & driven_veh
const Character & driver
auto_navigation_data data
Detailed Description
Definition at line 366 of file vehicle_autodrive.cpp.
Constructor & Destructor Documentation
autodrive_controller()
vehicle::autodrive_controller::autodrive_controller (const vehicle & driven_veh, const Character & driver) explicit
Definition at line 1125 of file vehicle_autodrive.cpp.
                                   : driven_veh( driven_veh ), driver( driver )
 {
     data.clear();
 }
References auto_navigation_data::clear(), and data.
Member Function Documentation
check_collision_zone()
collision_check_result vehicle::autodrive_controller::check_collision_zone (orientation turn_dir)
Definition at line 1143 of file vehicle_autodrive.cpp.
 {
     const tripoint_bub_ms veh_pos = driven_veh.pos_bub();
     // first check if we have any visibility in front, to prevent blind driving
     tileray face_dir = driven_veh.face;
     face_dir.advance();
     const point forward_offset( face_dir.dx(), face_dir.dy() );
     bool changed_zlevel = false;
     bool blind = true;
     for( const point &p : data.profile( to_orientation( face_dir.dir() ) ).collision_points ) {
         const tripoint_bub_ms next = data.adjust_z( veh_pos + forward_offset + p );
         if( driver.sees( next ) ) {
             blind = false;
         }
         // Known quirk: the player does not always see points above or below when driving
         // up or down ramps, which makes this check think that we should stop pathfinding.
         // So here we allow having no visibility in case the path changes zlevel.
         // Checks further down below in this method will make sure that we instead slow down.
         changed_zlevel |= ( next.z() != veh_pos.z() );
     }
     if( blind && !changed_zlevel ) {
         return collision_check_result::no_visibility;
     }
     // now check the area we're about to move into in 1 step, anything there
     // should force us to stop
     const vehicle_profile &profile = data.profile( turn_dir );
     tileray tdir = driven_veh.face;
     if( turn_dir != to_orientation( tdir.dir() ) ) {
         tdir = profile.tdir;
     }
     const int speed = std::min( driven_veh.velocity + driven_veh.current_acceleration(),
                                 driven_veh.cruise_velocity );
     const int speed_tps = speed / VMIPH_PER_TPS;
     std::unordered_set<point> collision_zone;
     tdir.advance();
     point offset( tdir.dx(), tdir.dy() );
     for( const point &p : profile.occupied_zone ) {
         collision_zone.insert( p + offset );
     }
     for( const point &p : collision_zone ) {
         if( !check_drivable( data.adjust_z( veh_pos + p ) ) ) {
             return collision_check_result::close_obstacle;
         }
     }
     // finally check the area further ahead; we can still avoid those collisions by reducing speed
     collision_zone.clear();
     for( int i = 1; i < speed_tps; i++ ) {
         tdir.advance();
         offset += point( tdir.dx(), tdir.dy() );
         for( const point &p : profile.collision_points ) {
             collision_zone.insert( p + offset );
         }
     }
     for( const point &p : collision_zone ) {
         const tripoint_bub_ms next = data.adjust_z( veh_pos + p );
         if( !driver.sees( next ) ) {
             return collision_check_result::slow_down;
         }
         if( !check_drivable( next ) ) {
             return collision_check_result::slow_down;
         }
     }
     return collision_check_result::ok;
 }
References tileray::advance(), close_obstacle, vehicle_profile::collision_points, tileray::dir(), tileray::dx(), tileray::dy(), min(), no_visibility, vehicle_profile::occupied_zone, ok, point, slow_down, speed, vehicle_profile::tdir, to_orientation(), vehicle::turn_dir, VMIPH_PER_TPS, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
check_drivable()
bool vehicle::autodrive_controller::check_drivable (const tripoint_bub_ms & pt) const private
Definition at line 695 of file vehicle_autodrive.cpp.
 {
     const map &here = get_map();
     // check if another vehicle is there; tiles occupied by the current
     // vehicle are evidently drivable
     const optional_vpart_position ovp = here.veh_at( pt );
     if( ovp ) {
         // Known corner case: some furniture can be driven over, but will collide with
         // wheel parts; if the vehicle starts over such a furniture we'll mark that tile
         // as safe and may collide with it by turning; however if we mark it unsafe
         // we'll have no viable paths away from the starting point.
         return &ovp->vehicle() == &driven_veh;
     }
     const tripoint_abs_ms pt_abs = here.getglobal( pt );
     const tripoint_abs_omt pt_omt = project_to<coords::omt>( pt_abs );
     // only check visibility for the current OMT, we'll check other OMTs when
     // we reach them
     if( pt_omt == data.current_omt ) {
         // driver must see the tile or have seen it before in order to plan a route over it
         if( !driver.sees( pt ) ) {
             if( !driver.is_avatar() ) {
                 return false;
             }
             const avatar &avatar = *driver.as_avatar();
             if( !avatar.is_map_memory_valid() ) {
                 debugmsg( "autodrive querying uninitialized map memory at %s", pt_abs.to_string() );
                 return false;
             }
             if( avatar.get_memorized_tile( pt_abs ) == mm_submap::default_tile ) {
                 // apparently open air doesn't get memorized, so pretend it is or else
                 // we can't fly helicopters due to the many unseen tiles behind the driver
                 if( !( data.air_ok && here.ter( pt ) == ter_t_open_air ) ) {
                     return false;
                 }
             }
         }
     }
     // check for creatures
     // TODO: padding around monsters
     Creature *critter = get_creature_tracker().creature_at( pt, true );
     if( critter && driver.sees( *critter ) ) {
         return false;
     }
     // don't drive over visible traps
     if( here.can_see_trap_at( pt.raw(), driver ) ) {
         return false;
     }
     // check for furniture that hinders movement; furniture with 0 move cost
     // can be driven on
     const furn_id furniture = here.furn( pt );
     if( furniture != furn_str_id::NULL_ID() && furniture.obj().movecost != 0 ) {
         return false;
     }
     const ter_id terrain = here.ter( pt );
     if( terrain == ter_str_id::NULL_ID() ) {
         return false;
     }
     // open air is an obstacle to non-flying vehicles; it is drivable
     // for flying vehicles
     if( terrain == ter_t_open_air ) {
         return data.air_ok;
     }
     const ter_t &terrain_type = terrain.obj();
     // watercraft can drive on water
     if( data.water_ok && terrain_type.has_flag( ter_furn_flag::TFLAG_SWIMMABLE ) ) {
         return true;
     }
     // remaining checks are for land-based navigation
     if( !data.land_ok ) {
         return false;
     }
     // NOLINTNEXTLINE(bugprone-branch-clone)
     if( terrain_type.movecost <= 0 ) {
         // walls and other impassable terrain
         return false;
     } else if( terrain_type.movecost == 2 || terrain_type.has_flag( ter_furn_flag::TFLAG_NOCOLLIDE ) ) {
         // terrain with neutral move cost or tagged with NOCOLLIDE will never cause
         // collisions
         return true;
     } else if( terrain_type.bash.str_max >= 0 && !terrain_type.bash.bash_below ) {
         // bashable terrain (but not bashable floors) will cause collisions
         return false;
     } else if( terrain_type.has_flag( ter_furn_flag::TFLAG_LIQUID ) ) {
         // water and lava
         return false;
     }
     return true;
 }
References avatar::as_avatar(), map_data_common_t::bash, map_bash_info::bash_below, map::can_see_trap_at(), creature_tracker::creature_at(), debugmsg, mm_submap::default_tile, map::furn(), furniture, get_creature_tracker(), get_map(), avatar::get_memorized_tile(), map::getglobal(), map_data_common_t::has_flag(), avatar::is_map_memory_valid(), map_data_common_t::movecost, string_id< ter_t >::NULL_ID(), string_id< furn_t >::NULL_ID(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), Creature::sees(), map_bash_info::str_max, map::ter(), ter_t_open_air, terrain, TFLAG_LIQUID, TFLAG_NOCOLLIDE, TFLAG_SWIMMABLE, coords::coord_point_base< Point >::to_string(), and map::veh_at().
check_safe_speed()
void vehicle::autodrive_controller::check_safe_speed ()
Definition at line 1131 of file vehicle_autodrive.cpp.
 {
     // We normally drive at or below the vehicle's "safe speed" (beyond which the engine starts
     // taking damage). We normally determine this at the beginning of path planning and cache it.
     // However, sometimes the vehicle's safe speed may drop (e.g. amphibious vehicle entering
     // water), so this extra check is needed to adjust our max speed.
     int safe_speed_tps = driven_veh.safe_velocity() / VMIPH_PER_TPS;
     if( data.max_speed_tps > safe_speed_tps ) {
         data.max_speed_tps = safe_speed_tps;
     }
 }
References VMIPH_PER_TPS.
compute_coordinates()
void vehicle::autodrive_controller::compute_coordinates () private
Definition at line 616 of file vehicle_autodrive.cpp.
 {
     data.view_bounds = { point_zero, {NAV_VIEW_SIZE_X, NAV_VIEW_SIZE_Y} };
     data.nav_bounds = { point_zero, {NAV_MAP_SIZE_X, NAV_MAP_SIZE_Y} };
     data.next_omt_bounds = { {OMT_SIZE, 0}, {OMT_SIZE * 2, OMT_SIZE} };
     const tripoint_rel_omt omt_diff = data.next_omt - data.current_omt;
     quad_rotation next_dir = to_quad_rotation( omt_diff.raw().xy() );
     point mid_omt( OMT_SIZE / 2, OMT_SIZE / 2 );
     const tripoint_abs_ms abs_mid_omt = project_to<coords::ms>( data.current_omt ) + mid_omt;
     data.nav_to_view = { point_zero, quad_rotation::d0, {NAV_VIEW_PADDING, NAV_VIEW_PADDING} } ;
     data.nav_to_map = { mid_omt, next_dir, abs_mid_omt.raw().xy() };
     data.view_to_map = data.nav_to_map;
     data.view_to_map.pre_offset += data.nav_to_view.post_offset;
 }
References auto_navigation_data::current_omt, d0, data, auto_navigation_data::nav_bounds, NAV_MAP_SIZE_X, NAV_MAP_SIZE_Y, auto_navigation_data::nav_to_map, auto_navigation_data::nav_to_view, NAV_VIEW_PADDING, NAV_VIEW_SIZE_X, NAV_VIEW_SIZE_Y, auto_navigation_data::next_omt, auto_navigation_data::next_omt_bounds, OMT_SIZE, point_zero, coord_transformation::post_offset, coord_transformation::pre_offset, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), to_quad_rotation(), auto_navigation_data::view_bounds, and auto_navigation_data::view_to_map.
compute_goal_zone()
void vehicle::autodrive_controller::compute_goal_zone () private
Definition at line 881 of file vehicle_autodrive.cpp.
 {
     data.goal_zone.clear();
     coord_transformation goal_transform;
     if( data.next_next_omt.xy() != data.next_omt.xy() ) {
         // set the goal at the edge of next_omt and next_next_omt (in next_omt
         // space, pointing towards next_next_omt)
         const point next_omt_middle( OMT_SIZE + OMT_SIZE / 2, OMT_SIZE / 2 );
         const tripoint_rel_omt omt_diff = data.next_next_omt - data.next_omt;
         const quad_rotation rotation = to_quad_rotation( omt_diff.raw().xy() ) - data.nav_to_map.rotation;
         goal_transform = {next_omt_middle, rotation, next_omt_middle};
     } else {
         // set the goal at the edge of cur_omt and next_omt (in next_omt space,
         // pointing away from cur_omt)
         goal_transform = { point( OMT_SIZE - 1, 0 ), quad_rotation::d0, point_zero };
     }
     constexpr int max_turns = NUM_ORIENTATIONS / 8 + 1;
     const int x = 2 * OMT_SIZE - 1;
     for( int turns = -max_turns; turns <= max_turns; turns++ ) {
         const orientation dir = orientation::d0 + turns;
         static_assert( NAV_MAP_SIZE_Y == OMT_SIZE, "Unexpected nav map size" );
         for( int y = 0; y < OMT_SIZE; y++ ) {
             const point pt( x, y );
             const node_address addr = goal_transform.transform( pt, dir );
             if( data.valid_position( addr ) ) {
                 data.goal_zone.insert( addr );
             }
         }
     }
     data.goal_points[0] = point( OMT_SIZE, OMT_SIZE / 2 - 1 );
     data.goal_points[1] = goal_transform.transform( point( x, OMT_SIZE / 2 - 1 ) );
 }
References d0, NAV_MAP_SIZE_Y, NUM_ORIENTATIONS, OMT_SIZE, point, point_zero, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), to_quad_rotation(), and coord_transformation::transform().
compute_next_nodes()
void vehicle::autodrive_controller::compute_next_nodes (const node_address & addr, const navigation_node & node, int target_speed_tps, std::vector< std::pair< node_address, navigation_node >> & next_nodes) const private
Definition at line 1000 of file vehicle_autodrive.cpp.
 {
     constexpr int move_cost = 10;
     constexpr int steering_cost = 1;
     const int sign = target_speed_tps > 0 ? 1 : -1;
     const int target_speed = target_speed_tps * VMIPH_PER_TPS;
     const int cur_omt = addr.x / OMT_SIZE;
     int next_speed = target_speed;
     int num_tiles_to_move = std::abs( target_speed_tps );
     if( target_speed_tps > 1 && node.speed < target_speed ) {
         const int cur_tps = std::min( std::max( node.speed / VMIPH_PER_TPS, 0 ), data.max_speed_tps - 1 );
         next_speed = std::min( std::max<int>( node.speed, 0 ) + data.acceleration[cur_tps], target_speed );
         num_tiles_to_move = next_speed / VMIPH_PER_TPS;
     }
     for( int steer = -data.max_steer; steer <= data.max_steer; steer++ ) {
         node_address next_addr = addr;
         next_addr.facing_dir = addr.facing_dir + steer;
         tileray tdir = data.profile( next_addr.facing_dir ).tdir;
         if( steer == 0 ) {
             tdir.advance( node.tileray_steps );
         }
         bool ok = true;
         bool goal_found = false;
         for( int i = 0; i < num_tiles_to_move && ok; i++ ) {
             tdir.advance( sign );
             next_addr.x += tdir.dx();
             next_addr.y += tdir.dy();
             if( !data.nav_bounds.contains( next_addr.get_point() ) ) {
                 // it's ok to go out of bounds only from the "next" omt and only
                 // after crossing the goal zone
                 if( cur_omt == 0 || !goal_found ) {
                     ok = false;
                 }
             } else if( !data.valid_position( next_addr ) ) {
                 ok = false;
             } else if( !goal_found && data.goal_zone.find( next_addr ) != data.goal_zone.end() ) {
                 goal_found = true;
             }
         }
         if( !ok ) {
             continue;
         }
         const int next_omt = next_addr.x / OMT_SIZE;
         if( next_omt < cur_omt ) {
             // no going back to a previous omt
             continue;
         }
         navigation_node next_node;
         next_node.prev = addr;
         next_node.tileray_steps = num_tiles_to_move + ( !steer ? node.tileray_steps : 0 );
         // TODO: improve this
         next_node.cost = node.cost + move_cost * num_tiles_to_move + ( steer ? steering_cost : 0 );
         next_node.speed = next_speed;
         next_node.target_speed_tps = target_speed_tps;
         next_node.is_goal = goal_found;
         next_nodes.emplace_back( next_addr, next_node );
     }
 }
References abs(), tileray::advance(), navigation_node::cost, tileray::dx(), tileray::dy(), node_address::facing_dir, node_address::get_point(), navigation_node::is_goal, max(), min(), move_cost, ok, OMT_SIZE, navigation_node::prev, iexamine::sign(), navigation_node::speed, navigation_node::target_speed_tps, navigation_node::tileray_steps, VMIPH_PER_TPS, node_address::x, and node_address::y.
compute_next_step()
std::optional< navigation_step > vehicle::autodrive_controller::compute_next_step ()
Definition at line 1216 of file vehicle_autodrive.cpp.
 {
     precompute_data();
     const tripoint_abs_ms veh_pos = driven_veh.global_square_location();
     const bool had_cached_path = !data.path.empty();
     const bool two_steps = data.path.size() > 2;
     const navigation_step first_step = two_steps ? data.path.back() : navigation_step();
     const navigation_step second_step = two_steps ? data.path.at( data.path.size() - 2 ) :
                                         navigation_step();
     bool maintain_speed = false;
     // If vehicle did not move as far as planned and direction is the same
     // then it is still accelerating. If the vehicle moved more than expected
     // then we likely underestimated the acceleration when planning the path.
     // If either of these happen, we should maintain speed but compute a new path.
     if( two_steps && square_dist( first_step.pos.xy().raw(), second_step.pos.xy().raw() ) !=
         square_dist( first_step.pos.xy().raw(), veh_pos.xy().raw() ) &&
         first_step.steering_dir == second_step.steering_dir ) {
         data.path.pop_back();
         maintain_speed = true;
         data.path.clear();
     } else {
         while( !data.path.empty() && data.path.back().pos != veh_pos ) {
             data.path.pop_back();
         }
     }
     if( !data.path.empty() && data.path.back().target_speed_tps > data.max_speed_tps ) {
         data.path.clear();
         maintain_speed = false;
     }
     if( data.path.empty() ) {
         // if we're just starting out or we've gone off-course use the lowest speed
         if( ( had_cached_path && !maintain_speed ) || driven_veh.velocity == 0 ) {
             data.max_speed_tps = MIN_SPEED_TPS;
         }
         auto new_path = compute_path( data.max_speed_tps );
         while( !new_path && data.max_speed_tps > MIN_SPEED_TPS ) {
             // high speed didn't work, try a lower speed
             data.max_speed_tps /= 2;
             new_path = compute_path( data.max_speed_tps );
         }
         if( !new_path ) {
             return std::nullopt;
         }
         data.path.swap( *new_path );
     }
     return data.path.back();
 }
References MIN_SPEED_TPS, navigation_step::pos, square_dist(), navigation_step::steering_dir, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
compute_node_score()
scored_address vehicle::autodrive_controller::compute_node_score (const node_address & addr, const navigation_node & node) const private
Definition at line 964 of file vehicle_autodrive.cpp.
 {
     // TODO: tweak this
     constexpr int cost_mult = 1;
     constexpr int forward_dist_mult = 10;
     constexpr int side_dist_mult = 8;
     constexpr int angle_mult = 2;
     constexpr int nearness_penalty = 15;
     scored_address ret{ addr, 0 };
     ret.score += cost_mult * node.cost;
     if( node.is_goal ) {
         return ret;
     }
     static constexpr std::array<point, 4> neighbor_deltas = {
         point_east, point_south, point_west, point_north
     };
     for( const point &neighbor_delta : neighbor_deltas ) {
         const point p = addr.get_point() + neighbor_delta;
         if( !data.nav_bounds.contains( p ) || !data.valid_position( addr.facing_dir, p ) ) {
             ret.score += nearness_penalty;
         }
     }
     const int omt_index = std::min( std::max( addr.x / OMT_SIZE, 0 ),
                                     static_cast<int>( data.goal_points.size() ) - 1 );
     const point waypoint_delta = data.goal_points[omt_index] - addr.get_point();
     const point goal_delta = data.goal_points.back() - addr.get_point();
     const orientation waypoint_dir = approx_orientation( waypoint_delta.x, waypoint_delta.y );
     ret.score += forward_dist_mult * std::abs( goal_delta.x );
     ret.score += side_dist_mult * std::abs( goal_delta.y );
     if( waypoint_delta.x > OMT_SIZE / 4 ) {
         ret.score += angle_mult * std::abs( orientation_diff( addr.facing_dir, waypoint_dir ) );
     }
     return ret;
 }
References abs(), approx_orientation(), navigation_node::cost, node_address::facing_dir, node_address::get_point(), navigation_node::is_goal, max(), min(), OMT_SIZE, orientation_diff(), point_east, point_north, point_south, point_west, cata::hash64_detail::ret, point::x, node_address::x, and point::y.
compute_obstacles()
void vehicle::autodrive_controller::compute_obstacles () private
Definition at line 790 of file vehicle_autodrive.cpp.
 {
     const map &here = get_map();
     const int z = data.current_omt.z();
     point_queue ramp_points;
     for( int dx = 0; dx < NAV_VIEW_SIZE_X; dx++ ) {
         for( int dy = 0; dy < NAV_VIEW_SIZE_Y; dy++ ) {
             const tripoint abs_map_pt = data.view_to_map.transform( point( dx, dy ), z );
             const tripoint_bub_ms p = here.bub_from_abs( abs_map_pt );
             data.is_obstacle[dx][dy] = !check_drivable( p );
             data.ground_z[dx][dy] = z;
             enqueue_if_ramp( ramp_points, here, p );
         }
     }
     compute_obstacles_from_enqueued_ramp_points( ramp_points, here );
 }
References map::bub_from_abs(), get_map(), NAV_VIEW_SIZE_X, NAV_VIEW_SIZE_Y, and point.
compute_obstacles_from_enqueued_ramp_points()
void vehicle::autodrive_controller::compute_obstacles_from_enqueued_ramp_points (point_queue & ramp_points, const map & here) private
Definition at line 827 of file vehicle_autodrive.cpp.
 {
     auto is_drivable = [this, &here]( const tripoint_bub_ms & p ) {
         return here.inbounds( p ) && check_drivable( p );
     };
     while( !ramp_points.to_check.empty() ) {
         const tripoint_bub_ms ramp_point = ramp_points.to_check.front();
         ramp_points.to_check.pop();
         for( const tripoint_bub_ms &p : ff::point_flood_fill_4_connected( ramp_point, ramp_points.visited,
                 is_drivable ) ) {
             const point pt_view = data.to_view( p );
             if( !data.view_bounds.contains( pt_view ) ) {
                 continue;
             }
             // We now know that point p is drivable (and not an obstacle) on this zlevel, since
             // it passed the is_drivable check.
             if( data.is_obstacle[pt_view] ) {
                 // We have examined this point previously on a different zlevel but conluded
                 // that it was an obstacle at that zlevel. But on this zlevel it is apparently
                 // not an obstacle, so this must be our groundlevel.
                 data.ground_z[pt_view] = p.z();
             } else {
                 data.ground_z[pt_view] = std::min( data.ground_z[pt_view], p.z() );
             }
             data.is_obstacle[pt_view] = false;
             enqueue_if_ramp( ramp_points, here, p );
         }
     };
 }
References map::inbounds(), min(), ff::point_flood_fill_4_connected(), point_queue::to_check, and point_queue::visited.
compute_path()
std::optional< std::vector< navigation_step > > vehicle::autodrive_controller::compute_path (int speed_tps) const private
Definition at line 1062 of file vehicle_autodrive.cpp.
 {
     if( speed_tps == 0 || speed_tps < -1 ) {
         return std::nullopt;
     }
     // TODO: tweak this
     constexpr int max_search_count = 10000;
     std::vector<navigation_step> ret;
     // TODO: check simple reachability first and bail out or set upper bound on node score
     std::unordered_map<node_address, navigation_node, node_address_hasher> known_nodes;
     std::priority_queue<scored_address, std::vector<scored_address>, std::greater<>>
             open_set;
     const tripoint_abs_ms veh_pos = driven_veh.global_square_location();
     const node_address start = data.nav_to_map.inverse().transform(
                                    veh_pos.raw().xy(), to_orientation( driven_veh.face.dir() ) );
     known_nodes.emplace( start, make_start_node( start, driven_veh ) );
     open_set.push( scored_address{ start, 0 } );
     std::vector<std::pair<node_address, navigation_node>> next_nodes;
     while( !open_set.empty() ) {
         const node_address cur_addr = open_set.top().addr;
         open_set.pop();
         const navigation_node &cur_node = known_nodes[cur_addr];
         if( cur_node.is_goal ) {
             node_address addr = cur_addr;
             while( !( addr == start ) ) {
                 const navigation_node &node = known_nodes.at( addr );
                 const node_address &prev = node.prev;
                 const tripoint_abs_ms prev_loc( data.nav_to_map.transform( prev.get_point(),
                                                 data.current_omt.z() ) );
                 ret.emplace_back( navigation_step{
                     data.adjust_z( prev_loc ),
                     data.nav_to_map.transform( addr.facing_dir ),
                     node.target_speed_tps
                 } );
                 addr = prev;
             }
             return ret;
         }
         next_nodes.clear();
         compute_next_nodes( cur_addr, cur_node, speed_tps, next_nodes );
         for( const auto &next : next_nodes ) {
             const node_address &next_addr = next.first;
             const navigation_node &next_node = next.second;
             auto iter = known_nodes.find( next_addr );
             if( iter != known_nodes.end() ) {
                 const navigation_node &other_node = iter->second;
                 if( next_node.cost < other_node.cost ) {
                     const bool same_dir = cur_addr.facing_dir == next_addr.facing_dir;
                     const bool dir_multiple_45 = static_cast<int>( next_addr.facing_dir ) % 3 == 0;
                     if( ( !same_dir && next_node.tileray_steps == 1 ) || dir_multiple_45 ) {
                         iter->second = next_node;
                     }
                 }
             } else if( known_nodes.size() < max_search_count ) {
                 known_nodes[next_addr] = next_node;
                 open_set.push( compute_node_score( next_addr, next_node ) );
             }
         }
     }
     return std::nullopt;
 }
References navigation_node::cost, node_address::facing_dir, node_address::get_point(), navigation_node::is_goal, make_start_node(), navigation_node::prev, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), cata::hash64_detail::ret, navigation_node::target_speed_tps, navigation_node::tileray_steps, and to_orientation().
compute_profile()
vehicle_profile vehicle::autodrive_controller::compute_profile (orientation facing) const private
Definition at line 633 of file vehicle_autodrive.cpp.
 {
     vehicle_profile ret;
     tileray tdir( to_angle( facing ) );
     ret.tdir = tdir;
     std::map<int, std::pair<int, int>> extent_map;
     const point pivot = driven_veh.pivot_point();
     for( const vehicle_part &part : driven_veh.parts ) {
         if( part.removed ) {
             continue;
         }
         tripoint pos;
         driven_veh.coord_translate( tdir, pivot, part.mount, pos );
         if( extent_map.find( pos.y ) == extent_map.end() ) {
             extent_map[pos.y] = { pos.x, pos.x };
         } else {
             auto &extent = extent_map[pos.y];
             extent.first = std::min( extent.first, pos.x );
             extent.second = std::max( extent.second, pos.x );
         }
     }
     for( const auto &extent : extent_map ) {
         const int y = extent.first;
         const int x_min = extent.second.first;
         const int x_max = extent.second.second;
         for( int x = x_min; x <= x_max; x++ ) {
             ret.occupied_zone.emplace_back( x, y );
         }
     }
     for( int part_num : driven_veh.rotors ) {
         const vehicle_part &part = driven_veh.part( part_num );
         const int diameter = part.info().rotor_info->rotor_diameter;
         const int radius = ( diameter + 1 ) / 2;
         if( radius > 0 ) {
             tripoint pos;
             driven_veh.coord_translate( tdir, pivot, part.mount, pos );
             for( tripoint pt : points_in_radius( pos, radius ) ) {
                 ret.occupied_zone.emplace_back( pt.xy() );
             }
         }
     }
     // figure out the maximum amount of displacement that can happen from advancing the
     // tileray a single step by advancing it a bunch of times and reducing the x and y
     // components of the displacement to at most 1
     constexpr int far_advance = 100;
     tdir.advance( far_advance );
     const point increment( signum( tdir.dx() ), signum( tdir.dy() ) );
     // compute the subset of vehicle points that would move to previously unoccupied spots
     // (a.k.a. "moving first") when the vehicle moves one step; these are the only points
     // we need to check for collision when the vehicle is moving in this direction
     const std::unordered_set<point> occupied_set( ret.occupied_zone.begin(), ret.occupied_zone.end() );
     for( const point &pt : ret.occupied_zone ) {
         if( occupied_set.find( pt + increment ) == occupied_set.end() ) {
             ret.collision_points.emplace_back( pt );
         }
     }
     return ret;
 }
References tileray::advance(), tileray::dx(), tileray::dy(), vehicle_part::info(), max(), min(), vehicle_part::mount, vehicle::part(), points_in_radius(), vehicle::pos, vehicle_part::removed, cata::hash64_detail::ret, vpart_info::rotor_info, signum(), to_angle(), point::x, and point::y.
compute_valid_positions()
void vehicle::autodrive_controller::compute_valid_positions () private
Definition at line 858 of file vehicle_autodrive.cpp.
 {
     const coord_transformation veh_rot = {point_zero, -data.nav_to_map.rotation, point_zero};
     for( orientation facing : all_orientations() ) {
         const vehicle_profile &profile = data.profile( data.nav_to_map.transform( facing ) );
         for( int mx = 0; mx < NAV_MAP_SIZE_X; mx++ ) {
             for( int my = 0; my < NAV_MAP_SIZE_Y; my++ ) {
                 const point nav_pt( mx, my );
                 bool valid = true;
                 for( const point &veh_pt : profile.occupied_zone ) {
                     const point view_pt = data.nav_to_view.transform( nav_pt ) + veh_rot.transform(
                                               veh_pt ) - veh_rot.transform( point_zero );
                     if( !data.view_bounds.contains( view_pt ) || data.is_obstacle[view_pt.x][view_pt.y] ) {
                         valid = false;
                         break;
                     }
                 }
                 data.valid_position( facing, nav_pt ) = valid;
             }
         }
     }
 }
References all_orientations(), NAV_MAP_SIZE_X, NAV_MAP_SIZE_Y, vehicle_profile::occupied_zone, point_zero, coord_transformation::transform(), point::x, and point::y.
enqueue_if_ramp()
void vehicle::autodrive_controller::enqueue_if_ramp (point_queue & ramp_points, const map & here, const tripoint_bub_ms & p) const private
Definition at line 809 of file vehicle_autodrive.cpp.
 {
     if( !data.land_ok ) {
         return;
     }
     ramp_points.visited.emplace( p );
     if( p.z() < OVERMAP_HEIGHT && here.has_flag( ter_furn_flag::TFLAG_RAMP_UP, p ) ) {
         ramp_points.enqueue( p + tripoint_above );
     }
     if( p.z() > -OVERMAP_DEPTH && here.has_flag( ter_furn_flag::TFLAG_RAMP_DOWN, p ) ) {
         ramp_points.enqueue( p + tripoint_below );
     }
 }
References point_queue::enqueue(), map::has_flag(), OVERMAP_DEPTH, OVERMAP_HEIGHT, TFLAG_RAMP_DOWN, TFLAG_RAMP_UP, tripoint_above, tripoint_below, point_queue::visited, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
get_data()
const auto_navigation_data& vehicle::autodrive_controller::get_data () inline
Definition at line 373 of file vehicle_autodrive.cpp.
{
             return data;
         }
References data.
get_driver()
const Character& vehicle::autodrive_controller::get_driver () inline
Definition at line 370 of file vehicle_autodrive.cpp.
{
             return driver;
         }
References driver.
precompute_data()
void vehicle::autodrive_controller::precompute_data () private
Definition at line 914 of file vehicle_autodrive.cpp.
 {
     const tripoint_abs_omt current_omt = driven_veh.global_omt_location();
     const tripoint_abs_omt next_omt = driver.omt_path.back();
     const tripoint_abs_omt next_next_omt = driver.omt_path.size() >= 2 ?
                                            driver.omt_path[driver.omt_path.size() - 2] : next_omt;
     if( current_omt != data.current_omt || next_omt != data.next_omt ||
         next_next_omt != data.next_next_omt ) {
         data.current_omt = current_omt;
         data.next_omt = next_omt;
         data.next_next_omt = next_next_omt;
         // initialize car and driver properties
         data.land_ok = driven_veh.valid_wheel_config();
         data.water_ok = driven_veh.can_float();
         data.air_ok = driven_veh.has_sufficient_rotorlift();
         data.max_speed_tps = std::min( MAX_SPEED_TPS, driven_veh.safe_velocity() / VMIPH_PER_TPS );
         data.acceleration.resize( data.max_speed_tps );
         for( int speed_tps = 0; speed_tps < data.max_speed_tps; speed_tps++ ) {
             data.acceleration[speed_tps] = driven_veh.acceleration( true, speed_tps * VMIPH_PER_TPS );
         }
         // TODO: compute from driver's skill and speed stat
         // TODO: change it during simulation based on vehicle speed and terrain
         // or maybe just keep track of player moves?
         data.max_steer = 1;
         for( orientation dir : all_orientations() ) {
             data.profile( dir ) = compute_profile( dir );
         }
         // initialize navigation data
         compute_coordinates();
         compute_obstacles();
         compute_valid_positions();
         compute_goal_zone();
         data.path.clear();
     }
 }
References all_orientations(), MAX_SPEED_TPS, min(), and VMIPH_PER_TPS.
reduce_speed()
void vehicle::autodrive_controller::reduce_speed ()
Definition at line 1211 of file vehicle_autodrive.cpp.
 {
     data.max_speed_tps = MIN_SPEED_TPS;
 }
References MIN_SPEED_TPS.
Member Data Documentation
data
auto_navigation_data vehicle::autodrive_controller::data private
Definition at line 384 of file vehicle_autodrive.cpp.
Referenced by autodrive_controller(), compute_coordinates(), and get_data().
driven_veh
const vehicle& vehicle::autodrive_controller::driven_veh private
Definition at line 382 of file vehicle_autodrive.cpp.
driver
const Character& vehicle::autodrive_controller::driver private
Definition at line 383 of file vehicle_autodrive.cpp.
Referenced by get_driver().
The documentation for this class was generated from the following file:
src/vehicle_autodrive.cpp