Cataclysm DDA: submap Class Reference
submap Class Reference
#include <submap.h>
Classes
struct cosmetic_t
struct tile_data
Public Member Functions
submap ()=default
submap (submap &&) noexcept(map_is_noexcept)
~submap ()
submap & operator= (submap &&) noexcept
void ensure_nonuniform ()
void revert_submap (submap &sr)
submap get_revert_submap () const
trap_id get_trap (const point &p) const
void set_trap (const point &p, trap_id trap)
void set_all_traps (const trap_id &trap)
furn_id get_furn (const point &p) const
void set_furn (const point &p, furn_id furn)
void set_all_furn (const furn_id &furn)
int get_map_damage (const point_sm_ms &p) const
void set_map_damage (const point_sm_ms &p, int dmg)
ter_id get_ter (const point &p) const
void set_ter (const point &p, ter_id terr)
void set_all_ter (const ter_id &terr, bool uniform_ok=false)
int get_radiation (const point &p) const
void set_radiation (const point &p, const int radiation)
uint8_t get_lum (const point &p) const
void set_lum (const point &p, uint8_t luminance)
void update_lum_add (const point &p, const item &i)
void update_lum_rem (const point &p, const item &i)
cata::colony< item > & get_items (const point &p)
const cata::colony< item > & get_items (const point &p) const
field & get_field (const point &p)
const field & get_field (const point &p) const
void clear_fields (const point &p)
void insert_cosmetic (const point &p, const std::string &type, const std::string &str)
units::temperature_delta get_temperature_mod () const
void set_temperature_mod (units::temperature_delta new_temperature_mod)
bool has_graffiti (const point &p) const
const std::string & get_graffiti (const point &p) const
void set_graffiti (const point &p, const std::string &new_graffiti)
void delete_graffiti (const point &p)
bool has_signage (const point &p) const
std::string get_signage (const point &p) const
void set_signage (const point &p, const std::string &s)
void delete_signage (const point &p)
bool has_computer (const point &p) const
const computer * get_computer (const point &p) const
computer * get_computer (const point &p)
void set_computer (const point &p, const computer &c)
void delete_computer (const point &p)
bool contains_vehicle (vehicle *)
bool is_open_air (const point &) const
void rotate (int turns)
void mirror (bool horizontally)
void store (JsonOut &jsout) const
void load (const JsonValue &jv, const std::string &member_name, int version)
bool is_uniform () const
Public Attributes
std::vector< cosmetic_t > cosmetics
active_item_cache active_items
int field_count = 0
time_point last_touched = calendar::turn_zero
bool reverted = false
std::vector< spawn_point > spawns
std::vector< std::unique_ptr< vehicle > > vehicles
Vehicles on this submap (their (0,0) point is on this submap).
std::map< tripoint_sm_ms, partial_con > partial_constructions
std::unique_ptr< basecamp > camp
Private Attributes
std::map< point_sm_ms, tile_data > ephemeral_data
std::map< point, computer > computers
std::unique_ptr< maptile_soa > m
ter_id uniform_ter = t_null
int temperature_mod = 0
Static Private Attributes
static constexpr size_t elements = SEEX * SEEY
Detailed Description
Definition at line 69 of file submap.h.
Constructor & Destructor Documentation
submap() [1/2]
submap::submap () default
submap() [2/2]
submap::submap (submap &&) default noexcept
~submap()
submap::~submap () default
Member Function Documentation
clear_fields()
void submap::clear_fields (const point & p)
Definition at line 32 of file submap.cpp.
 {
     field &f = get_field( p );
     field_count -= f.field_count();
     f.clear();
 }
References field::clear(), and field::field_count().
Referenced by map::clear_fields().
contains_vehicle()
bool submap::contains_vehicle (vehicle * veh)
Definition at line 181 of file submap.cpp.
 {
     const auto match = std::find_if(
                            begin( vehicles ), end( vehicles ),
     [veh]( const std::unique_ptr<vehicle> &v ) {
         return v.get() == veh;
     } );
     return match != vehicles.end();
 }
References keycode::end.
Referenced by map::process_items_in_vehicle(), and map::process_items_in_vehicles().
delete_computer()
void submap::delete_computer (const point & p)
Definition at line 176 of file submap.cpp.
 {
     computers.erase( p );
 }
References computers.
delete_graffiti()
void submap::delete_graffiti (const point & p)
Definition at line 92 of file submap.cpp.
 {
     const cosmetic_find_result fresult = find_cosmetic( cosmetics, p, COSMETICS_GRAFFITI );
     if( fresult.result ) {
         ensure_nonuniform();
         cosmetics[ fresult.ndx ] = cosmetics.back();
         cosmetics.pop_back();
     }
 }
References cosmetics, COSMETICS_GRAFFITI(), ensure_nonuniform(), find_cosmetic(), cosmetic_find_result::ndx, and cosmetic_find_result::result.
Referenced by map::delete_graffiti().
delete_signage()
void submap::delete_signage (const point & p)
Definition at line 131 of file submap.cpp.
 {
     const cosmetic_find_result fresult = find_cosmetic( cosmetics, p, COSMETICS_SIGNAGE );
     if( fresult.result ) {
         ensure_nonuniform();
         cosmetics[ fresult.ndx ] = cosmetics.back();
         cosmetics.pop_back();
     }
 }
References cosmetics, COSMETICS_SIGNAGE(), ensure_nonuniform(), find_cosmetic(), cosmetic_find_result::ndx, and cosmetic_find_result::result.
Referenced by map::delete_signage().
ensure_nonuniform()
void submap::ensure_nonuniform () inline
Definition at line 78 of file submap.h.
{
             if( is_uniform() ) {
                 m = std::make_unique<maptile_soa>();
                 std::uninitialized_fill_n( &m->ter[0][0], elements, uniform_ter );
                 std::uninitialized_fill_n( &m->frn[0][0], elements, furn_str_id::NULL_ID() );
                 std::uninitialized_fill_n( &m->lum[0][0], elements, 0 );
                 std::uninitialized_fill_n( &m->trp[0][0], elements, tr_null );
                 std::uninitialized_fill_n( &m->rad[0][0], elements, 0 );
             }
         }
References elements, is_uniform(), m, string_id< furn_t >::NULL_ID(), tr_null, and uniform_ter.
Referenced by map::add_field(), map::add_item(), map::add_vehicle(), delete_graffiti(), delete_signage(), map::displace_vehicle(), revert_submap(), set_all_furn(), set_all_ter(), set_all_traps(), set_furn(), set_graffiti(), set_lum(), set_radiation(), set_signage(), set_ter(), set_trap(), update_lum_add(), and update_lum_rem().
get_computer() [1/2]
computer * submap::get_computer (const point & p)
Definition at line 157 of file submap.cpp.
 {
     const auto it = computers.find( p );
     if( it != computers.end() ) {
         return &it->second;
     }
     return nullptr;
 }
References computers.
get_computer() [2/2]
const computer * submap::get_computer (const point & p) const
Definition at line 146 of file submap.cpp.
 {
     // the returned object will not get modified (should not, at least), so we
     // don't yet need to update to std::map
     const auto it = computers.find( p );
     if( it != computers.end() ) {
         return &it->second;
     }
     return nullptr;
 }
References computers.
Referenced by map::add_computer().
get_field() [1/2]
field& submap::get_field (const point & p) inline
Definition at line 212 of file submap.h.
{
             if( is_uniform() ) {
                 field static nofield;
                 return nofield;
             }
             return m->fld[p.x][p.y];
         }
References is_uniform(), m, point::x, and point::y.
Referenced by map::add_field(), map::build_transparency_cache(), map::decay_fields_and_scent(), map::field_at(), map::generate_lightmap(), map::move_cost(), and map::process_fields_in_submap().
get_field() [2/2]
const field& submap::get_field (const point & p) const inline
Definition at line 220 of file submap.h.
{
             if( is_uniform() ) {
                 field static nofield;
                 return nofield;
             }
             return m->fld[p.x][p.y];
         }
References is_uniform(), m, point::x, and point::y.
get_furn()
furn_id submap::get_furn (const point & p) const inline
Definition at line 110 of file submap.h.
{
             if( is_uniform() ) {
                 return furn_str_id::NULL_ID();
             }
             return m->frn[p.x][p.y];
         }
References is_uniform(), m, string_id< furn_t >::NULL_ID(), point::x, and point::y.
Referenced by map::build_obstacle_cache(), map::build_outside_cache(), map::build_transparency_cache(), map::furn(), map::furn_set(), map::generate_lightmap(), map::has_flag_ter_or_furn(), map::move_cost(), map::move_cost_ter_furn(), revert_submap(), and map::ter_set().
get_graffiti()
const std::string & submap::get_graffiti (const point & p) const
Definition at line 71 of file submap.cpp.
 {
     const cosmetic_find_result fresult = find_cosmetic( cosmetics, p, COSMETICS_GRAFFITI );
     if( fresult.result ) {
         return cosmetics[ fresult.ndx ].str;
     }
     return STRING_EMPTY;
 }
References cosmetics, COSMETICS_GRAFFITI(), find_cosmetic(), cosmetic_find_result::ndx, cosmetic_find_result::result, and STRING_EMPTY.
Referenced by map::graffiti_at().
get_items() [1/2]
cata::colony<item>& submap::get_items (const point & p) inline
Definition at line 195 of file submap.h.
{
             if( is_uniform() ) {
                 cata::colony<item> static noitems;
                 return noitems;
             }
             return m->itm[p.x][p.y];
         }
References is_uniform(), m, point::x, and point::y.
Referenced by map::add_item(), map::has_items(), map::i_at(), map::i_clear(), map::i_rem(), map::make_active(), revert_submap(), and timed_event_manager::unserialize_all().
get_items() [2/2]
const cata::colony<item>& submap::get_items (const point & p) const inline
Definition at line 203 of file submap.h.
{
             if( is_uniform() ) {
                 cata::colony<item> static noitems;
                 return noitems;
             }
             return m->itm[p.x][p.y];
         }
References is_uniform(), m, point::x, and point::y.
get_lum()
uint8_t submap::get_lum (const point & p) const inline
Definition at line 173 of file submap.h.
{
             if( is_uniform() ) {
                 return 0;
             }
             return m->lum[p.x][p.y];
         }
References is_uniform(), m, point::x, and point::y.
Referenced by map::generate_lightmap().
get_map_damage()
int submap::get_map_damage (const point_sm_ms & p) const inline
Definition at line 126 of file submap.h.
{
             auto it = ephemeral_data.find( p );
             if( it != ephemeral_data.end() ) {
                 return it->second.damage;
             }
             return 0;
         }
References ephemeral_data.
Referenced by map::get_map_damage().
get_radiation()
int submap::get_radiation (const point & p) const inline
Definition at line 161 of file submap.h.
{
             if( is_uniform() ) {
                 return 0;
             }
             return m->rad[p.x][p.y];
         }
References is_uniform(), m, point::x, and point::y.
Referenced by map::adjust_radiation(), and map::get_radiation().
get_revert_submap()
submap submap::get_revert_submap () const
Definition at line 345 of file submap.cpp.
 {
     submap ret;
     ret.uniform_ter = uniform_ter;
     if( !is_uniform() ) {
         ret.m = std::make_unique<maptile_soa>( *m );
     }
     return ret;
 }
References is_uniform(), m, cata::hash64_detail::ret, and uniform_ter.
get_signage()
std::string submap::get_signage (const point & p) const
Definition at line 109 of file submap.cpp.
 {
     if( !is_uniform() && m->frn[p.x][p.y].obj().has_flag( ter_furn_flag::TFLAG_SIGN ) ) {
         const cosmetic_find_result fresult = find_cosmetic( cosmetics, p, COSMETICS_SIGNAGE );
         if( fresult.result ) {
             return cosmetics[ fresult.ndx ].str;
         }
     }
     return STRING_EMPTY;
 }
References cosmetics, COSMETICS_SIGNAGE(), find_cosmetic(), is_uniform(), m, cosmetic_find_result::ndx, cosmetic_find_result::result, STRING_EMPTY, TFLAG_SIGN, point::x, and point::y.
Referenced by map::get_signage().
get_temperature_mod()
units::temperature_delta submap::get_temperature_mod () const inline
Definition at line 246 of file submap.h.
{
             return units::from_fahrenheit_delta( temperature_mod );
         }
References units::from_fahrenheit_delta(), and temperature_mod.
Referenced by map::get_temperature_mod().
get_ter()
ter_id submap::get_ter (const point & p) const inline
Definition at line 138 of file submap.h.
{
             if( is_uniform() ) {
                 return uniform_ter;
             }
             return m->ter[p.x][p.y];
         }
References is_uniform(), m, uniform_ter, point::x, and point::y.
Referenced by map::actualize(), map::add_roofs(), map::build_floor_cache(), map::build_obstacle_cache(), map::build_outside_cache(), map::build_transparency_cache(), map::furn_set(), map::generate_lightmap(), map::has_flag_ter_or_furn(), is_open_air(), map::move_cost(), map::move_cost_ter_furn(), revert_submap(), map::saven(), map::ter(), map::ter_set(), map::tr_at(), and map::trap_set().
get_trap()
trap_id submap::get_trap (const point & p) const inline
Definition at line 93 of file submap.h.
{
             if( is_uniform() ) {
                 return tr_null;
             }
             return m->trp[p.x][p.y];
         }
References is_uniform(), m, tr_null, point::x, and point::y.
Referenced by map::actualize(), map::remove_trap(), revert_submap(), map::tr_at(), and map::trap_set().
has_computer()
bool submap::has_computer (const point & p) const
Definition at line 141 of file submap.cpp.
 {
     return !is_uniform() && computers.find( p ) != computers.end();
 }
References computers, and is_uniform().
has_graffiti()
bool submap::has_graffiti (const point & p) const
Definition at line 66 of file submap.cpp.
 {
     return find_cosmetic( cosmetics, p, COSMETICS_GRAFFITI ).result;
 }
References cosmetics, COSMETICS_GRAFFITI(), find_cosmetic(), and cosmetic_find_result::result.
Referenced by map::has_graffiti_at().
has_signage()
bool submap::has_signage (const point & p) const
Definition at line 101 of file submap.cpp.
 {
     if( !is_uniform() && m->frn[p.x][p.y].obj().has_flag( ter_furn_flag::TFLAG_SIGN ) ) {
         return find_cosmetic( cosmetics, p, COSMETICS_SIGNAGE ).result;
     }
     return false;
 }
References cosmetics, COSMETICS_SIGNAGE(), find_cosmetic(), is_uniform(), m, cosmetic_find_result::result, TFLAG_SIGN, point::x, and point::y.
insert_cosmetic()
void submap::insert_cosmetic (const point & p, const std::string & type, const std::string & str) inline
Definition at line 236 of file submap.h.
{
             cosmetic_t ins;
             ins.pos = p;
             ins.type = type;
             ins.str = str;
             cosmetics.push_back( ins );
         }
References cosmetics, submap::cosmetic_t::pos, submap::cosmetic_t::str, type, and submap::cosmetic_t::type.
Referenced by set_graffiti(), and set_signage().
is_open_air()
bool submap::is_open_air (const point & p) const
Definition at line 191 of file submap.cpp.
 {
     ter_id t = get_ter( p );
     return t->trap == tr_ledge;
 }
References get_ter(), tr_ledge, and ter_t::trap.
Referenced by map::furn_set(), map::is_open_air(), and map::ter_set().
is_uniform()
bool submap::is_uniform () const inline
Definition at line 288 of file submap.h.
{
             return !static_cast<bool>( m );
         }
References m.
Referenced by map::build_transparency_cache(), ensure_nonuniform(), get_field(), get_furn(), get_items(), get_lum(), get_radiation(), get_revert_submap(), get_signage(), get_ter(), get_trap(), has_computer(), has_signage(), mirror(), revert_submap(), rotate(), set_all_ter(), and map::spawn_monsters_submap_group().
load()
void submap::load (const JsonValue & jv, const std::string & member_name, int version)
Definition at line 4894 of file savegame_json.cpp.
 {
     ensure_nonuniform();
     bool rubpow_update = version < 22;
     if( member_name == "turn_last_touched" ) {
         last_touched = time_point( jv.get_int() );
     } else if( member_name == "temperature" ) {
         temperature_mod = jv.get_int();
     } else if( member_name == "terrain" ) {
         // TODO: try block around this to error out if we come up short?
         JsonArray terrain_json = jv;
         // Small duplication here so that the update check is only performed once
         if( rubpow_update ) {
             item rock = item( "rock", calendar::turn_zero );
             item chunk = item( "steel_chunk", calendar::turn_zero );
             for( int j = 0; j < SEEY; j++ ) {
                 for( int i = 0; i < SEEX; i++ ) {
                     const ter_str_id tid( terrain_json.next_string() );
                     if( tid == ter_t_rubble ) {
                         m->ter[i][j] = ter_t_dirt;
                         m->frn[i][j] = furn_id( "f_rubble" );
                         m->itm[i][j].insert( rock );
                         m->itm[i][j].insert( rock );
                     } else if( tid == ter_t_wreckage ) {
                         m->ter[i][j] = ter_t_dirt;
                         m->frn[i][j] = furn_id( "f_wreckage" );
                         m->itm[i][j].insert( chunk );
                         m->itm[i][j].insert( chunk );
                     } else if( tid == ter_t_ash ) {
                         m->ter[i][j] = ter_t_dirt;
                         m->frn[i][j] = furn_id( "f_ash" );
                     } else if( tid == ter_t_pwr_sb_support_l ) {
                         m->ter[i][j] = ter_t_support_l;
                     } else if( tid == ter_t_pwr_sb_switchgear_l ) {
                         m->ter[i][j] = ter_t_switchgear_l;
                     } else if( tid == ter_t_pwr_sb_switchgear_s ) {
                         m->ter[i][j] = ter_t_switchgear_s;
                     } else {
                         m->ter[i][j] = tid.id();
                     }
                 }
             }
         } else {
             // terrain is encoded using simple RLE
             int remaining = 0;
             int_id<ter_t> iid_ter;
             int_id<furn_t> iid_furn;
             for( int j = 0; j < SEEY; j++ ) {
                 // NOLINTNEXTLINE(modernize-loop-convert)
                 for( int i = 0; i < SEEX; i++ ) {
                     if( !remaining ) {
                         JsonValue terrain_entry = terrain_json.next_value();
                         auto migrate_terstr = [&]( ter_str_id terstr ) {
                             if( auto it = ter_migrations.find( terstr ); it != ter_migrations.end() ) {
                                 terstr = it->second.first;
                                 if( it->second.second != furn_str_id::NULL_ID() ) {
                                     iid_furn = it->second.second.id();
                                 }
                             }
                             if( terstr.is_valid() ) {
                                 iid_ter = terstr.id();
                             } else {
                                 debugmsg( "invalid ter_str_id '%s'", terstr.c_str() );
                                 iid_ter = ter_t_dirt;
                             }
                         };
                         if( terrain_entry.test_string() ) {
                             migrate_terstr( ter_str_id( terrain_entry.get_string() ) );
                         } else if( terrain_entry.test_array() ) {
                             JsonArray terrain_rle = terrain_entry;
                             migrate_terstr( ter_str_id( terrain_rle.next_string() ) );
                             remaining = terrain_rle.next_int() - 1;
                             if( terrain_rle.size() > 2 ) {
                                 terrain_rle.throw_error( "Too many values for terrain RLE" );
                             }
                         } else {
                             debugmsg( "Mapbuffer terrain data is corrupt, expected string or array." );
                         }
                     } else {
                         --remaining;
                     }
                     m->ter[i][j] = iid_ter;
                     if( iid_furn ) {
                         m->frn[i][j] = iid_furn;
                     }
                 }
             }
             if( remaining ) {
                 debugmsg( "Mapbuffer terrain data is corrupt, tile data remaining." );
             }
         }
     } else if( member_name == "radiation" ) {
         int rad_cell = 0;
         JsonArray radiation_rle = jv;
         while( radiation_rle.has_more() ) {
             int rad_strength = radiation_rle.next_int();
             int rad_num = radiation_rle.next_int();
             for( int i = 0; i < rad_num; ++i ) {
                 if( rad_cell < SEEX * SEEY ) {
                     set_radiation( { rad_cell % SEEX, rad_cell / SEEX }, rad_strength );
                     rad_cell++;
                 }
             }
         }
     } else if( member_name == "furniture" ) {
         int_id<ter_t> iid_ter;
         int_id<furn_t> iid_furn;
         JsonArray furniture_json = jv;
         for( JsonArray furniture_entry : furniture_json ) {
             int i = furniture_entry.next_int();
             int j = furniture_entry.next_int();
             furn_str_id furnstr( furniture_entry.next_string() );
             if( auto it = furn_migrations.find( furnstr ); it != furn_migrations.end() ) {
                 furnstr = it->second.second;
                 if( it->second.first != ter_str_id::NULL_ID() ) {
                     m->ter[i][j] = it->second.first.id();
                 }
             }
             if( furnstr.is_valid() ) {
                 iid_furn = furnstr.id();
             } else {
                 debugmsg( "invalid furn_str_id '%s'", furnstr.c_str() );
                 iid_furn = furn_str_id::NULL_ID().id();
             }
             m->frn[i][j] = iid_furn;
             if( furniture_entry.size() > 3 ) {
                 furniture_entry.throw_error( "Too many values for furniture entry." );
             }
         }
     } else if( member_name == "items" ) {
         JsonArray items_json = jv;
         while( items_json.has_more() ) {
             int i = items_json.next_int();
             int j = items_json.next_int();
             const point p( i, j );
             if( !items_json.next_value().read( m->itm[p.x][p.y], false ) ) {
                 debugmsg( "Items array is corrupt in submap at: %s, skipping", p.to_string() );
             }
             // some portion could've been read even if error occurred
             for( item &it : m->itm[p.x][p.y] ) {
                 if( it.is_emissive() ) {
                     update_lum_add( p, it );
                 }
                 active_items.add( it, p );
             }
         }
     } else if( member_name == "traps" ) {
         JsonArray traps_json = jv;
         for( JsonArray trap_entry : traps_json ) {
             int i = trap_entry.next_int();
             int j = trap_entry.next_int();
             const point p( i, j );
             // TODO: jsin should support returning an id like jsin.get_id<trap>()
             const trap_str_id trid( trap_entry.next_string() );
             m->trp[p.x][p.y] = trid.id();
             if( trap_entry.size() > 3 ) {
                 trap_entry.throw_error( "Too many values for trap entry" );
             }
         }
     } else if( member_name == "fields" ) {
         JsonArray fields_json = jv;
         while( fields_json.has_more() ) {
             // Coordinates loop
             int i = fields_json.next_int();
             int j = fields_json.next_int();
             JsonArray field_json = fields_json.next_array();
             while( field_json.has_more() ) {
                 // TODO: Check enum->string migration below
                 int type_int = 0;
                 std::string type_str;
                 JsonValue type_value = field_json.next_value();
                 if( type_value.test_int() ) {
                     type_int = type_value.get_int();
                 } else {
                     type_str = type_value.get_string();
                 }
                 int intensity = field_json.next_int();
                 int age = field_json.next_int();
                 field_type_id ft;
                 if( !type_str.empty() ) {
                     ft = field_type_id( type_str );
                 } else {
                     ft = field_types::get_field_type_by_legacy_enum( type_int ).id;
                 }
                 if( m->fld[i][j].add_field( ft, intensity, time_duration::from_turns( age ) ) ) {
                     field_count++;
                 }
             }
         }
     } else if( member_name == "graffiti" ) {
         JsonArray graffiti_json = jv;
         for( JsonArray graffiti_entry : graffiti_json ) {
             int i = graffiti_entry.next_int();
             int j = graffiti_entry.next_int();
             const point p( i, j );
             set_graffiti( p, graffiti_entry.next_string() );
             if( graffiti_entry.size() > 3 ) {
                 graffiti_entry.throw_error( "Too many values for graffiti" );
             }
         }
     } else if( member_name == "cosmetics" ) {
         JsonArray cosmetics_json = jv;
         std::map<std::string, std::string> tcosmetics;
         for( JsonArray cosmetic_entry : cosmetics_json ) {
             int i = cosmetic_entry.next_int();
             int j = cosmetic_entry.next_int();
             const point p( i, j );
             std::string type;
             std::string str;
             JsonValue cosmetic_value = cosmetic_entry.next_value();
             // Try to read as current format
             if( cosmetic_value.test_string() ) {
                 type = cosmetic_value.get_string();
                 str = cosmetic_entry.next_string();
                 insert_cosmetic( p, type, str );
             } else {
                 // Otherwise read as most recent old format
                 cosmetic_value.read( tcosmetics );
                 for( auto &cosm : tcosmetics ) {
                     insert_cosmetic( p, cosm.first, cosm.second );
                 }
                 tcosmetics.clear();
             }
             if( cosmetic_entry.has_more() ) {
                 cosmetic_entry.throw_error( "Too many values for cosmetics" );
             }
         }
     } else if( member_name == "spawns" ) {
         JsonArray spawns_json = jv;
         for( JsonArray spawn_entry : spawns_json ) {
             // TODO: json should know how to read an string_id
             const mtype_id type = mtype_id( spawn_entry.next_string() );
             int count = spawn_entry.next_int();
             int i = spawn_entry.next_int();
             int j = spawn_entry.next_int();
             const point p( i, j );
             int faction_id = spawn_entry.next_int();
             int mission_id = spawn_entry.next_int();
             bool friendly = spawn_entry.next_bool();
             std::optional<std::string> name = std::nullopt;
             spawn_entry.read_next( name );
             if( spawn_entry.has_more() ) {
                 spawn_entry.throw_error( "Too many values for spawn" );
             }
             spawn_point tmp( type, count, p, faction_id, mission_id, friendly, name );
             spawns.push_back( tmp );
         }
     } else if( member_name == "vehicles" ) {
         JsonArray vehicles_json = jv;
         for( JsonValue vehicle_json : vehicles_json ) {
             try {
                 std::unique_ptr<vehicle> veh = std::make_unique<vehicle>( vproto_id() );
                 veh->deserialize( vehicle_json );
                 vehicles.emplace_back( std::move( veh ) );
             } catch( const JsonError &err ) {
                 debugmsg( err.what() );
             }
         }
     } else if( member_name == "partial_constructions" ) {
         JsonArray partial_constructions_json = jv;
         while( partial_constructions_json.has_more() ) {
             partial_con pc;
             int i = partial_constructions_json.next_int();
             int j = partial_constructions_json.next_int();
             int k = partial_constructions_json.next_int();
             tripoint_sm_ms pt( i, j, k );
             pc.counter = partial_constructions_json.next_int();
             JsonValue construction_id_value = partial_constructions_json.next_value();
             if( construction_id_value.test_int() ) {
                 // Oops, int id incorrectly saved by legacy code, just load it and hope for the best
                 pc.id = construction_id( construction_id_value.get_int() );
             } else {
                 pc.id = construction_str_id( construction_id_value.get_string() ).id();
             }
             JsonArray components_json = partial_constructions_json.next_array();
             for( JsonObject component_json : components_json ) {
                 item tmp;
                 tmp.deserialize( component_json );
                 pc.components.push_back( tmp );
             }
             partial_constructions[pt] = pc;
         }
     } else if( member_name == "computers" ) {
         if( jv.test_array() ) {
             JsonArray computers_json = jv;
             while( computers_json.has_more() ) {
                 point loc;
                 computers_json.next_value().read( loc );
                 auto new_comp_it = computers.emplace( loc, computer( "BUGGED_COMPUTER", -100,
                                                       tripoint_zero ) ).first;
                 computers_json.next_value().read( new_comp_it->second );
             }
         }
     } else if( member_name == "camp" ) {
         camp = std::make_unique<basecamp>();
         camp->deserialize( jv );
     }
 }
References string_id< T >::c_str(), partial_con::components, partial_con::counter, debugmsg, item::deserialize(), field_type_id, friendly, time_duration::from_turns(), furn_id, furn_migrations, field_types::get_field_type_by_legacy_enum(), JsonValue::get_int(), JsonValue::get_string(), JsonArray::has_more(), partial_con::id, field_type::id, int_id< T >::id(), furn_t::id, string_id< T >::id(), intensity, item::is_emissive(), string_id< T >::is_valid(), item, mtype_id, om_direction::name(), JsonArray::next_array(), JsonArray::next_int(), JsonArray::next_string(), JsonArray::next_value(), string_id< furn_t >::NULL_ID(), string_id< ter_t >::NULL_ID(), JsonValue::read(), SEEX, SEEY, JsonArray::size(), ter_migrations, ter_str_id, ter_t_ash, ter_t_dirt, ter_t_pwr_sb_support_l, ter_t_pwr_sb_switchgear_l, ter_t_pwr_sb_switchgear_s, ter_t_rubble, ter_t_support_l, ter_t_switchgear_l, ter_t_switchgear_s, ter_t_wreckage, JsonValue::test_array(), JsonValue::test_int(), JsonValue::test_string(), JsonArray::throw_error(), point::to_string(), tripoint_zero, calendar::turn_zero, type, point::x, and point::y.
mirror()
void submap::mirror (bool horizontally)
Definition at line 274 of file submap.cpp.
 {
     if( is_uniform() ) {
         return;
     }
     std::map<point, computer> mirror_comp;
     if( horizontally ) {
         for( int i = 0, ie = SEEX / 2; i < ie; i++ ) {
             for( int k = 0; k < SEEY; k++ ) {
                 m->swap_soa_tile( { i, k }, { SEEX - 1 - i, k } );
             }
         }
         for( submap::cosmetic_t &elem : cosmetics ) {
             elem.pos = point( -elem.pos.x, elem.pos.y ) + point( SEEX - 1, 0 );
         }
         active_items.mirror( { SEEX, SEEY }, true );
         for( auto &elem : computers ) {
             mirror_comp.emplace( point( -elem.first.x, elem.first.y ) + point( SEEX - 1, 0 ), elem.second );
         }
         computers = mirror_comp;
     } else {
         for( int k = 0, ke = SEEY / 2; k < ke; k++ ) {
             for( int i = 0; i < SEEX; i++ ) {
                 m->swap_soa_tile( { i, k }, { i, SEEY - 1 - k } );
             }
         }
         for( submap::cosmetic_t &elem : cosmetics ) {
             elem.pos = point( elem.pos.x, -elem.pos.y ) + point( 0, SEEY - 1 );
         }
         active_items.mirror( { SEEX, SEEY }, false );
         for( auto &elem : computers ) {
             mirror_comp.emplace( point( elem.first.x, -elem.first.y ) + point( 0, SEEY - 1 ), elem.second );
         }
         computers = mirror_comp;
     }
 }
References active_items, computers, cosmetics, is_uniform(), m, active_item_cache::mirror(), point, SEEX, and SEEY.
operator=()
submap & submap::operator= (submap &&) default noexcept
revert_submap()
void submap::revert_submap (submap & sr)
Definition at line 318 of file submap.cpp.
 {
     reverted = true;
     if( sr.is_uniform() ) {
         m.reset();
         set_all_ter( sr.get_ter( point_zero ), true );
         return;
     }
     ensure_nonuniform();
     for( int x = 0; x < SEEX; x++ ) {
         for( int y = 0; y < SEEY; y++ ) {
             point pt( x, y );
             m->frn[x][y] = sr.get_furn( pt );
             m->ter[x][y] = sr.get_ter( pt );
             m->trp[x][y] = sr.get_trap( pt );
             m->itm[x][y] = sr.get_items( pt );
             for( item &itm : m->itm[x][y] ) {
                 if( itm.is_emissive() ) {
                     this->update_lum_add( pt, itm );
                 }
                 active_items.add( itm, pt );
             }
         }
     }
 }
References active_items, active_item_cache::add(), ensure_nonuniform(), get_furn(), get_items(), get_ter(), get_trap(), is_uniform(), m, point_zero, reverted, SEEX, SEEY, set_all_ter(), and update_lum_add().
rotate()
void submap::rotate (int turns)
Definition at line 197 of file submap.cpp.
 {
     if( is_uniform() ) {
         return;
     }
     turns = turns % 4;
     if( turns == 0 ) {
         return;
     }
     const auto rotate_point = [turns]( const point & p ) {
         return p.rotate( turns, { SEEX, SEEY } );
     };
     const auto rotate_point_ccw = [turns]( const point & p ) {
         return p.rotate( 4 - turns, { SEEX, SEEY } );
     };
     if( turns == 2 ) {
         // Swap horizontal stripes.
         for( int j = 0, je = SEEY / 2; j < je; ++j ) {
             for( int i = j, ie = SEEX - j; i < ie; ++i ) {
                 m->swap_soa_tile( { i, j }, rotate_point( { i, j } ) );
             }
         }
         // Swap vertical stripes so that they don't overlap with
         // the already swapped horizontals.
         for( int i = 0, ie = SEEX / 2; i < ie; ++i ) {
             for( int j = i + 1, je = SEEY - i - 1; j < je; ++j ) {
                 m->swap_soa_tile( { i, j }, rotate_point( { i, j } ) );
             }
         }
     } else {
         for( int j = 0, je = SEEY / 2; j < je; ++j ) {
             for( int i = j, ie = SEEX - j - 1; i < ie; ++i ) {
                 point p = point{ i, j };
                 point pp = p;
                 // three swaps are enough to perform the circular shift of four elements:
                 // 0123 -> 3120 -> 3102 -> 3012
                 for( int k = 0; k < 3; ++k ) {
                     p = pp;
                     pp = rotate_point_ccw( pp );
                     m->swap_soa_tile( p, pp );
                 }
             }
         }
     }
     active_items.rotate_locations( turns, { SEEX, SEEY } );
     for( submap::cosmetic_t &elem : cosmetics ) {
         elem.pos = rotate_point( elem.pos );
     }
     for( spawn_point &elem : spawns ) {
         elem.pos = rotate_point( elem.pos );
     }
     for( auto &elem : vehicles ) {
         const point new_pos = rotate_point( elem->pos );
         elem->pos = new_pos;
         // turn the steering wheel, vehicle::turn does not actually
         // move the vehicle.
         elem->turn( turns * 90_degrees );
         // The facing direction and recalculate the positions of the parts
         elem->face = tileray( elem->turn_dir );
         elem->precalc_mounts( 0, elem->turn_dir, elem->pivot_anchor[0] );
     }
     std::map<point, computer> rot_comp;
     for( auto &elem : computers ) {
         rot_comp.emplace( rotate_point( elem.first ), elem.second );
     }
     computers = rot_comp;
 }
References active_items, computers, cosmetics, is_uniform(), m, tripoint::rotate(), active_item_cache::rotate_locations(), rotate_point(), SEEX, SEEY, and spawns.
set_all_furn()
void submap::set_all_furn (const furn_id & furn) inline
Definition at line 122 of file submap.h.
{
             ensure_nonuniform();
             std::uninitialized_fill_n( &m->frn[0][0], elements, furn );
         }
References elements, ensure_nonuniform(), and m.
set_all_ter()
void submap::set_all_ter (const ter_id & terr, bool uniform_ok = false) inline
Definition at line 150 of file submap.h.
{
             if( !uniform_ok ) {
                 ensure_nonuniform();
             }
             if( is_uniform() ) {
                 uniform_ter = terr;
             } else {
                 std::uninitialized_fill_n( &m->ter[0][0], elements, terr );
             }
         }
References elements, ensure_nonuniform(), is_uniform(), m, and uniform_ter.
Referenced by revert_submap(), and timed_event_manager::unserialize_all().
set_all_traps()
void submap::set_all_traps (const trap_id & trap) inline
Definition at line 105 of file submap.h.
{
             ensure_nonuniform();
             std::uninitialized_fill_n( &m->trp[0][0], elements, trap );
         }
References elements, ensure_nonuniform(), and m.
set_computer()
void submap::set_computer (const point & p, const computer & c)
Definition at line 166 of file submap.cpp.
 {
     const auto it = computers.find( p );
     if( it != computers.end() ) {
         it->second = c;
     } else {
         computers.emplace( p, c );
     }
 }
References c, and computers.
Referenced by map::add_computer().
set_furn()
void submap::set_furn (const point & p, furn_id furn) inline
Definition at line 117 of file submap.h.
{
             ensure_nonuniform();
             m->frn[p.x][p.y] = furn;
         }
References ensure_nonuniform(), m, point::x, and point::y.
Referenced by map::furn_set(), and timed_event_manager::unserialize_all().
set_graffiti()
void submap::set_graffiti (const point & p, const std::string & new_graffiti)
Definition at line 80 of file submap.cpp.
 {
     ensure_nonuniform();
     // Find signage at p if available
     const cosmetic_find_result fresult = find_cosmetic( cosmetics, p, COSMETICS_GRAFFITI );
     if( fresult.result ) {
         cosmetics[ fresult.ndx ].str = new_graffiti;
     } else {
         insert_cosmetic( p, COSMETICS_GRAFFITI, new_graffiti );
     }
 }
References cosmetics, COSMETICS_GRAFFITI(), ensure_nonuniform(), find_cosmetic(), insert_cosmetic(), cosmetic_find_result::ndx, and cosmetic_find_result::result.
Referenced by map::set_graffiti().
set_lum()
void submap::set_lum (const point & p, uint8_t luminance) inline
Definition at line 180 of file submap.h.
{
             ensure_nonuniform();
             m->lum[p.x][p.y] = luminance;
         }
References ensure_nonuniform(), m, point::x, and point::y.
Referenced by map::i_clear().
set_map_damage()
void submap::set_map_damage (const point_sm_ms & p, int dmg) inline
Definition at line 134 of file submap.h.
{
             ephemeral_data[p] = { dmg };
         }
References ephemeral_data.
Referenced by map::furn_set(), map::set_map_damage(), and map::ter_set().
set_radiation()
void submap::set_radiation (const point & p, const int radiation) inline
Definition at line 168 of file submap.h.
{
             ensure_nonuniform();
             m->rad[p.x][p.y] = radiation;
         }
References ensure_nonuniform(), m, point::x, and point::y.
Referenced by map::adjust_radiation(), and map::set_radiation().
set_signage()
void submap::set_signage (const point & p, const std::string & s)
Definition at line 120 of file submap.cpp.
 {
     ensure_nonuniform();
     // Find signage at p if available
     const cosmetic_find_result fresult = find_cosmetic( cosmetics, p, COSMETICS_SIGNAGE );
     if( fresult.result ) {
         cosmetics[ fresult.ndx ].str = s;
     } else {
         insert_cosmetic( p, COSMETICS_SIGNAGE, s );
     }
 }
References cosmetics, COSMETICS_SIGNAGE(), ensure_nonuniform(), find_cosmetic(), insert_cosmetic(), cosmetic_find_result::ndx, and cosmetic_find_result::result.
Referenced by map::set_signage().
set_temperature_mod()
void submap::set_temperature_mod (units::temperature_delta new_temperature_mod) inline
Definition at line 250 of file submap.h.
{
             temperature_mod = units::to_fahrenheit_delta( new_temperature_mod );
         }
References temperature_mod, and units::to_fahrenheit_delta().
Referenced by map::set_temperature_mod().
set_ter()
void submap::set_ter (const point & p, ter_id terr) inline
Definition at line 145 of file submap.h.
{
             ensure_nonuniform();
             m->ter[p.x][p.y] = terr;
         }
References ensure_nonuniform(), m, point::x, and point::y.
Referenced by map::add_roofs(), map::ter_set(), and timed_event_manager::unserialize_all().
set_trap()
void submap::set_trap (const point & p, trap_id trap) inline
Definition at line 100 of file submap.h.
{
             ensure_nonuniform();
             m->trp[p.x][p.y] = trap;
         }
References ensure_nonuniform(), m, point::x, and point::y.
Referenced by map::remove_trap(), map::trap_set(), and timed_event_manager::unserialize_all().
store()
void submap::store (JsonOut & jsout) const
Definition at line 4677 of file savegame_json.cpp.
 {
     jsout.member( "turn_last_touched", last_touched );
     jsout.member( "temperature", temperature_mod );
     // Terrain is saved using a simple RLE scheme.  Legacy saves don't have
     // this feature but the algorithm is backward compatible.
     jsout.member( "terrain" );
     jsout.start_array();
     if( is_uniform() ) {
         _write_rle_terrain( jsout, uniform_ter.id().str(), SEEX * SEEY );
         jsout.end_array();
         return;
     }
     std::string last_id;
     int num_same = 1;
     for( int j = 0; j < SEEY; j++ ) {
         // NOLINTNEXTLINE(modernize-loop-convert)
         for( int i = 0; i < SEEX; i++ ) {
             const std::string this_id = m->ter[i][j].obj().id.str();
             if( !last_id.empty() ) {
                 if( this_id == last_id ) {
                     num_same++;
                 } else {
                     if( num_same == 1 ) {
                         // if there's only one element don't write as an array
                         jsout.write( last_id );
                     } else {
                         _write_rle_terrain( jsout, last_id, num_same );
                         num_same = 1;
                     }
                     last_id = this_id;
                 }
             } else {
                 last_id = this_id;
             }
         }
     }
     // Because of the RLE scheme we have to do one last pass
     if( num_same == 1 ) {
         jsout.write( last_id );
     } else {
         jsout.start_array();
         jsout.write( last_id );
         jsout.write( num_same );
         jsout.end_array();
     }
     jsout.end_array();
     // Write out the radiation array in a simple RLE scheme.
     // written in intensity, count pairs
     jsout.member( "radiation" );
     jsout.start_array();
     int lastrad = -1;
     int count = 0;
     for( int j = 0; j < SEEY; j++ ) {
         for( int i = 0; i < SEEX; i++ ) {
             const point p( i, j );
             // Save radiation, re-examine this because it doesn't look like it works right
             int r = get_radiation( p );
             if( r == lastrad ) {
                 count++;
             } else {
                 if( count ) {
                     jsout.write( count );
                 }
                 jsout.write( r );
                 lastrad = r;
                 count = 1;
             }
         }
     }
     jsout.write( count );
     jsout.end_array();
     jsout.member( "furniture" );
     jsout.start_array();
     for( int j = 0; j < SEEY; j++ ) {
         for( int i = 0; i < SEEX; i++ ) {
             const point p( i, j );
             // Save furniture
             if( get_furn( p ) ) {
                 jsout.start_array();
                 jsout.write( p.x );
                 jsout.write( p.y );
                 jsout.write( get_furn( p ).obj().id );
                 jsout.end_array();
             }
         }
     }
     jsout.end_array();
     jsout.member( "items" );
     jsout.start_array();
     for( int j = 0; j < SEEY; j++ ) {
         for( int i = 0; i < SEEX; i++ ) {
             if( m->itm[i][j].empty() ) {
                 continue;
             }
             jsout.write( i );
             jsout.write( j );
             jsout.write( m->itm[i][j] );
         }
     }
     jsout.end_array();
     jsout.member( "traps" );
     jsout.start_array();
     for( int j = 0; j < SEEY; j++ ) {
         for( int i = 0; i < SEEX; i++ ) {
             const point p( i, j );
             // Save traps
             if( get_trap( p ) ) {
                 jsout.start_array();
                 jsout.write( p.x );
                 jsout.write( p.y );
                 // TODO: jsout should support writing an id like jsout.write( trap_id )
                 jsout.write( get_trap( p ).id().str() );
                 jsout.end_array();
             }
         }
     }
     jsout.end_array();
     jsout.member( "fields" );
     jsout.start_array();
     for( int j = 0; j < SEEY; j++ ) {
         for( int i = 0; i < SEEX; i++ ) {
             // Save fields
             if( m->fld[i][j].field_count() > 0 ) {
                 jsout.write( i );
                 jsout.write( j );
                 jsout.start_array();
                 for( const auto &elem : m->fld[i][j] ) {
                     const field_entry &cur = elem.second;
                     jsout.write( cur.get_field_type().id() );
                     jsout.write( cur.get_field_intensity() );
                     jsout.write( cur.get_field_age() );
                 }
                 jsout.end_array();
             }
         }
     }
     jsout.end_array();
     // Write out as array of arrays of single entries
     jsout.member( "cosmetics" );
     jsout.start_array();
     for( const submap::cosmetic_t &cosm : cosmetics ) {
         jsout.start_array();
         jsout.write( cosm.pos.x );
         jsout.write( cosm.pos.y );
         jsout.write( cosm.type );
         jsout.write( cosm.str );
         jsout.end_array();
     }
     jsout.end_array();
     // Output the spawn points
     jsout.member( "spawns" );
     jsout.start_array();
     for( const spawn_point &elem : spawns ) {
         jsout.start_array();
         // TODO: json should know how to write string_ids
         jsout.write( elem.type.str() );
         jsout.write( elem.count );
         jsout.write( elem.pos.x );
         jsout.write( elem.pos.y );
         jsout.write( elem.faction_id );
         jsout.write( elem.mission_id );
         jsout.write( elem.friendly );
         jsout.write( elem.name );
         jsout.end_array();
     }
     jsout.end_array();
     jsout.member( "vehicles" );
     jsout.start_array();
     for( const auto &elem : vehicles ) {
         // json lib doesn't know how to turn a vehicle * into a vehicle,
         // so we have to iterate manually.
         jsout.write( *elem );
     }
     jsout.end_array();
     jsout.member( "partial_constructions" );
     jsout.start_array();
     for( const auto &elem : partial_constructions ) {
         jsout.write( elem.first.x() );
         jsout.write( elem.first.y() );
         jsout.write( elem.first.z() );
         jsout.write( elem.second.counter );
         jsout.write( elem.second.id.id() );
         jsout.start_array();
         for( const item &it : elem.second.components ) {
             jsout.write( it );
         }
         jsout.end_array();
     }
     jsout.end_array();
     if( !computers.empty() ) {
         jsout.member( "computers" );
         jsout.start_array();
         for( const auto &elem : computers ) {
             jsout.write( elem.first );
             jsout.write( elem.second );
         }
         jsout.end_array();
     }
     // Output base camp if any
     if( camp ) {
         jsout.member( "camp", *camp );
     }
 }
References anonymous_namespace{savegame_json.cpp}::_write_rle_terrain(), item::components, JsonOut::end_array(), field_entry::get_field_age(), field_entry::get_field_intensity(), field_entry::get_field_type(), int_id< T >::id(), JsonOut::member(), SEEX, SEEY, JsonOut::start_array(), JsonOut::write(), point::x, and point::y.
update_lum_add()
void submap::update_lum_add (const point & p, const item & i) inline
Definition at line 185 of file submap.h.
{
             ensure_nonuniform();
             if( i.is_emissive() && m->lum[p.x][p.y] < 255 ) {
                 m->lum[p.x][p.y]++;
             }
         }
References ensure_nonuniform(), item::is_emissive(), m, point::x, and point::y.
Referenced by map::add_item(), revert_submap(), and map::update_lum().
update_lum_rem()
void submap::update_lum_rem (const point & p, const item & i)
Definition at line 356 of file submap.cpp.
 {
     ensure_nonuniform();
     if( !i.is_emissive() ) {
         return;
     } else if( m->lum[p.x][p.y] && m->lum[p.x][p.y] < 255 ) {
         m->lum[p.x][p.y]--;
         return;
     }
     // Have to scan through all items to be sure removing i will actually lower
     // the count below 255.
     int count = 0;
     for( const item &it : m->itm[p.x][p.y] ) {
         if( it.is_emissive() ) {
             count++;
         }
     }
     if( count <= 256 ) {
         m->lum[p.x][p.y] = static_cast<uint8_t>( count - 1 );
     }
 }
References ensure_nonuniform(), item::is_emissive(), m, point::x, and point::y.
Referenced by map::i_rem(), and map::update_lum().
Member Data Documentation
active_items
active_item_cache submap::active_items
Definition at line 294 of file submap.h.
Referenced by map::add_item(), map::loadn(), map::make_active(), mirror(), map::process_items(), map::process_items_in_submap(), revert_submap(), and rotate().
camp
std::unique_ptr<basecamp> submap::camp
Definition at line 307 of file submap.h.
Referenced by map::hoist_submap_camp(), and map::remove_submap_camp().
computers
std::map<point, computer> submap::computers private
Definition at line 315 of file submap.h.
Referenced by delete_computer(), get_computer(), has_computer(), mirror(), rotate(), and set_computer().
cosmetics
std::vector<cosmetic_t> submap::cosmetics
Definition at line 292 of file submap.h.
Referenced by delete_graffiti(), delete_signage(), get_graffiti(), get_signage(), has_graffiti(), has_signage(), insert_cosmetic(), mirror(), rotate(), set_graffiti(), and set_signage().
elements
constexpr size_t submap::elements = SEEX * SEEY static constexpr private
Definition at line 320 of file submap.h.
Referenced by ensure_nonuniform(), set_all_furn(), set_all_ter(), and set_all_traps().
ephemeral_data
std::map<point_sm_ms, tile_data> submap::ephemeral_data private
Definition at line 314 of file submap.h.
Referenced by get_map_damage(), and set_map_damage().
field_count
int submap::field_count = 0
Definition at line 296 of file submap.h.
Referenced by map::add_field(), map::decay_fields_and_scent(), map::delete_field(), map::loadn(), map::process_fields(), and map::process_fields_in_submap().
last_touched
time_point submap::last_touched = calendar::turn_zero
Definition at line 297 of file submap.h.
Referenced by map::actualize(), and map::saven().
m
std::unique_ptr<maptile_soa> submap::m private
Definition at line 316 of file submap.h.
Referenced by ensure_nonuniform(), get_field(), get_furn(), get_items(), get_lum(), get_radiation(), get_revert_submap(), get_signage(), get_ter(), get_trap(), has_signage(), is_uniform(), mirror(), revert_submap(), rotate(), set_all_furn(), set_all_ter(), set_all_traps(), set_furn(), set_lum(), set_radiation(), set_ter(), set_trap(), update_lum_add(), and update_lum_rem().
partial_constructions
std::map<tripoint_sm_ms, partial_con> submap::partial_constructions
Definition at line 306 of file submap.h.
Referenced by map::partial_con_at(), map::partial_con_remove(), and map::partial_con_set().
reverted
bool submap::reverted = false
Definition at line 298 of file submap.h.
Referenced by revert_submap().
spawns
std::vector<spawn_point> submap::spawns
Definition at line 299 of file submap.h.
Referenced by map::add_spawn(), editmap::mapgen_preview(), rotate(), and map::spawn_monsters_submap().
temperature_mod
int submap::temperature_mod = 0 private
Definition at line 318 of file submap.h.
Referenced by get_temperature_mod(), and set_temperature_mod().
uniform_ter
ter_id submap::uniform_ter = t_null private
Definition at line 317 of file submap.h.
Referenced by ensure_nonuniform(), get_revert_submap(), get_ter(), and set_all_ter().
vehicles
std::vector<std::unique_ptr<vehicle> > submap::vehicles
Vehicles on this submap (their (0,0) point is on this submap).
This vehicle objects are deleted by this submap when it gets deleted.
Definition at line 305 of file submap.h.
Referenced by map::actualize(), map::add_vehicle(), map::copy_grid(), map::detach_vehicle(), map::displace_vehicle(), map::get_vehicles(), map::loadn(), editmap::mapgen_preview(), editmap::mapgen_veh_destroy(), editmap::mapgen_veh_query(), map::process_items_in_vehicles(), and map::update_vehicle_list().
The documentation for this class was generated from the following files:
src/submap.h
src/savegame_json.cpp
src/submap.cpp