Cataclysm DDA: item_stack Class Reference
item_stack Class Reference abstract
#include <item_stack.h>
Public Types
using iterator = cata::colony< item >::iterator
using const_iterator = cata::colony< item >::const_iterator
using reverse_iterator = cata::colony< item >::reverse_iterator
using const_reverse_iterator = cata::colony< item >::const_reverse_iterator
Public Member Functions
item_stack (cata::colony< item > *items)
virtual ~item_stack ()=default
size_t size () const
bool empty () const
virtual void insert (const item &newitem)=0
virtual iterator erase (const_iterator it)=0
virtual void clear ()
item & only_item ()
iterator get_iterator_from_pointer (item *it)
iterator get_iterator_from_index (size_t idx)
size_t get_index_from_iterator (const const_iterator &it)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
virtual int count_limit () const =0
Maximum number of items allowed here.
virtual units::volume max_volume () const =0
Maximum volume allowed here.
units::volume stored_volume () const
Total volume of the items here.
units::volume free_volume () const
int amount_can_fit (const item &it) const
Returns how many of the specified item (or how many charges if it's counted by charges) could be added without violating either the volume or itemcount limits.
item * stacks_with (const item &it)
Return the item (or nullptr) that stacks with the argument.
const item * stacks_with (const item &it) const
std::list< item > use_charges (const itype_id &type, int &quantity, const tripoint &pos, const std::function< bool(const item &)> &filter, bool in_tools=false)
Consumes specified charges (or fewer) from the stack.
Protected Attributes
cata::colony< item > * items
Detailed Description
Definition at line 24 of file item_stack.h.
Member Typedef Documentation
const_iterator
using item_stack::const_iterator = cata::colony<item>::const_iterator
Definition at line 31 of file item_stack.h.
const_reverse_iterator
using item_stack::const_reverse_iterator = cata::colony<item>::const_reverse_iterator
Definition at line 33 of file item_stack.h.
iterator
using item_stack::iterator = cata::colony<item>::iterator
Definition at line 30 of file item_stack.h.
reverse_iterator
using item_stack::reverse_iterator = cata::colony<item>::reverse_iterator
Definition at line 32 of file item_stack.h.
Constructor & Destructor Documentation
item_stack()
item_stack::item_stack (cata::colony< item > * items) inline explicit
Definition at line 35 of file item_stack.h.
 : items( items ) { }
~item_stack()
virtual item_stack::~item_stack () virtual default
Member Function Documentation
amount_can_fit()
int item_stack::amount_can_fit (const item & it) const
Returns how many of the specified item (or how many charges if it's counted by charges) could be added without violating either the volume or itemcount limits.
Returns
Value of zero or greater for all items. For items counted by charges, it is always at most it.charges.
Definition at line 111 of file item_stack.cpp.
 {
     // Without stacking charges, would we violate the count limit?
     const bool violates_count = size() >= static_cast<size_t>( count_limit() );
     const item *here = it.count_by_charges() ? stacks_with( it ) : nullptr;
     if( violates_count && !here ) {
         return 0;
     }
     // Call max because a tile may have been overfilled to begin with (e.g. #14115)
     const int ret = std::max( 0, it.charges_per_volume( free_volume() ) );
     return it.count_by_charges() ? std::min( ret, it.charges ) : ret;
 }
References item::charges, item::charges_per_volume(), item::count_by_charges(), count_limit(), free_volume(), max(), min(), cata::hash64_detail::ret, size(), and stacks_with().
Referenced by vehicle::add_charges(), and vehicle::add_item().
begin() [1/2]
item_stack::iterator item_stack::begin ()
Definition at line 32 of file item_stack.cpp.
 {
     return items->begin();
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::begin(), and items.
Referenced by computer_session::action_irradiator(), Character::activate_bionic(), iexamine::aggie_plant(), jmapgen_terrain::apply(), iexamine::arcfurnace_full(), iexamine::autoclave_empty(), iexamine::autoclave_full(), Pickup::autopickup(), map::bash_items(), MapExtras::burned_ground_parser(), game::butcher(), can_do_activity_there(), clear(), doors::close_door(), complete_construction(), iexamine::compost_empty(), iexamine::compost_full(), Character::consume_charges(), displace_items_except_one_liquid(), basecamp::distribute_food(), farm_action(), iexamine::fertilize_plant(), fetch_activity(), talk_function::field_harvest(), field_processor_fd_push_items(), map::fill_funnels(), fill_funnels(), activity_handlers::fill_liquid_do_turn(), iexamine::finite_water_source(), game::forced_door_closing(), fromPumpFuel(), map::furnname(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), game::grabbed_furn_move(), game::grabbed_furn_move_time(), map::grow_plant(), iexamine::harvest_plant(), iexamine::harvest_plant_ex(), Character::is_snuggling(), iexamine::keg(), iexamine::kiln_full(), talk_function::loot_building(), map::mop_spills(), only_item(), vehicle::operate_planter(), vehicle::operate_reaper(), iexamine::quern_examine(), vehicle::refresh_active_item_cache(), reload_furniture(), serialize_liquid_source(), map::smash_items(), iexamine::smoker_options(), fungal_effects::spread_fungus_one_tile(), iexamine::stook_full(), map::terrain_moppable(), iexamine::toPumpFuel(), editmap::update_view_with_help(), vehicle::use_autoclave(), use_charges(), use_charges_from_furn(), vehicle::use_dishwasher(), and vehicle::use_washing_machine().
begin() [2/2]
item_stack::const_iterator item_stack::begin () const
Definition at line 42 of file item_stack.cpp.
 {
     return items->cbegin();
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::cbegin(), and items.
clear()
void item_stack::clear () virtual
Definition at line 24 of file item_stack.cpp.
 {
     // An acceptable implementation for list; would be bad for vector
     while( !empty() ) {
         erase( begin() );
     }
 }
References begin(), empty(), and erase().
Referenced by MapExtras::delete_items_at_mount(), vehicle::do_remove_part_actual(), vehicle_folding_activity_actor::fold_vehicle(), and game::start_game().
count_limit()
virtual int item_stack::count_limit () const pure virtual
Maximum number of items allowed here.
Implemented in vehicle_stack, and map_stack.
Referenced by amount_can_fit().
empty()
bool item_stack::empty () const
Definition at line 19 of file item_stack.cpp.
 {
     return items->empty();
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::empty(), and items.
Referenced by computer_session::action_blood_anal(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_irradiator(), activity_on_turn_move_loot(), jmapgen_terrain::apply(), iexamine::arcfurnace_full(), iexamine::autoclave_empty(), iexamine::autoclave_full(), Pickup::autopickup(), can_butcher_at(), advanced_inventory::change_square(), construct::check_empty(), construct::check_empty_lite(), construct::check_support_below(), clear(), doors::close_door(), iexamine::compost_full(), iexamine::dirtmound(), unload_loot_activity_actor::do_turn(), game::examine(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), talk_function::field_harvest(), activity_handlers::fill_liquid_do_turn(), iexamine::fvat_full(), iexamine::kiln_full(), advanced_inventory_pane::load_settings(), iexamine::mill_finalize(), only_item(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), tutorial_game::per_turn(), game::place_player(), basecamp::place_results(), iexamine::pour_into_keg(), iexamine::quern_examine(), vehicle_prototype::save_vehicle_as_prototype(), iexamine::shrub_wildveggies(), smoker_finalize(), iexamine::smoker_options(), iexamine::stook_full(), vehicle::use_autoclave(), vehicle::use_dishwasher(), vehicle::use_washing_machine(), iexamine::vending(), and iexamine::workbench_internal().
end() [1/2]
item_stack::iterator item_stack::end ()
Definition at line 37 of file item_stack.cpp.
 {
     return items->end();
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::end(), and items.
Referenced by computer_session::action_irradiator(), Character::activate_bionic(), iexamine::aggie_plant(), iexamine::arcfurnace_full(), iexamine::autoclave_empty(), iexamine::autoclave_full(), Pickup::autopickup(), map::bash_items(), MapExtras::burned_ground_parser(), game::butcher(), can_do_activity_there(), doors::close_door(), complete_construction(), iexamine::compost_empty(), iexamine::compost_full(), Character::consume_charges(), displace_items_except_one_liquid(), basecamp::distribute_food(), farm_action(), iexamine::fertilize_plant(), fetch_activity(), talk_function::field_harvest(), field_processor_fd_push_items(), map::fill_funnels(), fill_funnels(), iexamine::finite_water_source(), game::forced_door_closing(), fromPumpFuel(), map::furnname(), iexamine::fvat_empty(), iexamine::gaspump(), game::grabbed_furn_move(), game::grabbed_furn_move_time(), map::grow_plant(), iexamine::harvest_plant(), iexamine::harvest_plant_ex(), map::i_rem(), Character::is_snuggling(), iexamine::kiln_full(), talk_function::loot_building(), map::mop_spills(), only_item(), vehicle::operate_planter(), vehicle::operate_reaper(), iexamine::quern_examine(), vehicle::refresh_active_item_cache(), reload_furniture(), serialize_liquid_source(), map::smash_items(), iexamine::smoker_options(), fungal_effects::spread_fungus_one_tile(), map::terrain_moppable(), iexamine::toPumpFuel(), vehicle::use_autoclave(), use_charges(), use_charges_from_furn(), vehicle::use_dishwasher(), and vehicle::use_washing_machine().
end() [2/2]
item_stack::const_iterator item_stack::end () const
Definition at line 47 of file item_stack.cpp.
 {
     return items->cend();
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::cend(), and items.
erase()
virtual iterator item_stack::erase (const_iterator it) pure virtual
Implemented in vehicle_stack, and map_stack.
Referenced by clear(), item_list_to_stack(), process_map_items(), and use_charges().
free_volume()
units::volume item_stack::free_volume () const
Definition at line 163 of file item_stack.cpp.
 {
     return max_volume() - stored_volume();
 }
References max_volume(), and stored_volume().
Referenced by amount_can_fit(), veh_interact::display_stats(), map::free_volume(), item_location::impl::item_on_map::volume_capacity(), and item_location::impl::item_on_vehicle::volume_capacity().
get_index_from_iterator()
size_t item_stack::get_index_from_iterator (const const_iterator & it)
Definition at line 82 of file item_stack.cpp.
 {
     return items->get_index_from_iterator( it );
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::get_index_from_iterator(), and items.
get_iterator_from_index()
item_stack::iterator item_stack::get_iterator_from_index (size_t idx)
Definition at line 77 of file item_stack.cpp.
 {
     return items->get_iterator_from_index( idx );
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::get_iterator_from_index(), and items.
Referenced by editmap::edit_itm().
get_iterator_from_pointer()
item_stack::iterator item_stack::get_iterator_from_pointer (item * it)
Definition at line 72 of file item_stack.cpp.
 {
     return items->get_iterator_from_pointer( it );
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::get_iterator_from_pointer(), and items.
Referenced by vehicle::add_item(), map::i_rem(), map::make_active(), and process_map_items().
insert()
virtual void item_stack::insert (const item & newitem) pure virtual
Implemented in vehicle_stack, and map_stack.
max_volume()
virtual units::volume item_stack::max_volume () const pure virtual
Maximum volume allowed here.
Implemented in vehicle_stack, and map_stack.
Referenced by free_volume().
only_item()
item & item_stack::only_item ()
Definition at line 87 of file item_stack.cpp.
 {
     if( empty() ) {
         debugmsg( "Missing item at target location" );
         return null_item_reference();
     } else if( size() > 1 ) {
         debugmsg( "More than one item at target location: %s", enumerate_as_string( begin(),
         end(), []( const item & it ) {
             return it.typeId();
         } ) );
         return null_item_reference();
     }
     return *items->begin();
 }
References begin(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::begin(), debugmsg, empty(), end(), enumerate_as_string(), items, null_item_reference(), size(), and item::typeId().
Referenced by computer_session::action_blood_anal(), computer_session::action_data_anal(), iexamine::arcfurnace_full(), doors::close_door(), iexamine::compost_empty(), construct::done_deconstruct(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), iexamine::fvat_empty(), iexamine::keg(), iexamine::kiln_full(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), and iexamine::pour_into_keg().
rbegin() [1/2]
item_stack::reverse_iterator item_stack::rbegin ()
Definition at line 52 of file item_stack.cpp.
 {
     return items->rbegin();
 }
References items, and cata::colony< element_type, element_allocator_type, element_skipfield_type >::rbegin().
rbegin() [2/2]
item_stack::const_reverse_iterator item_stack::rbegin () const
Definition at line 62 of file item_stack.cpp.
 {
     return items->crbegin();
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::crbegin(), and items.
rend() [1/2]
item_stack::reverse_iterator item_stack::rend ()
Definition at line 57 of file item_stack.cpp.
 {
     return items->rend();
 }
References items, and cata::colony< element_type, element_allocator_type, element_skipfield_type >::rend().
rend() [2/2]
item_stack::const_reverse_iterator item_stack::rend () const
Definition at line 67 of file item_stack.cpp.
 {
     return items->crend();
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::crend(), and items.
size()
size_t item_stack::size () const
Definition at line 14 of file item_stack.cpp.
 {
     return items->size();
 }
References items, and cata::colony< element_type, element_allocator_type, element_skipfield_type >::size().
Referenced by computer_session::action_blood_anal(), computer_session::action_data_anal(), activity_on_turn_move_loot(), iexamine::aggie_plant(), amount_can_fit(), game::butcher(), iexamine::can_fertilize(), doors::close_door(), construct::done_deconstruct(), editmap::edit_itm(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), activity_handlers::fill_liquid_do_turn(), npc::find_item(), map::get_haulable_items(), advanced_inv_area::get_item_count(), game::grabbed_furn_move(), game::grabbed_furn_move_time(), only_item(), iexamine::quern_examine(), iexamine::smoker_options(), and editmap::update_view_with_help().
stacks_with() [1/2]
item * item_stack::stacks_with (const item & it)
Return the item (or nullptr) that stacks with the argument.
Definition at line 125 of file item_stack.cpp.
 {
     for( item &here : *items ) {
         if( here.stacks_with( it ) ) {
             return &here;
         }
     }
     return nullptr;
 }
References items.
Referenced by vehicle::add_item(), and amount_can_fit().
stacks_with() [2/2]
const item * item_stack::stacks_with (const item & it) const
Definition at line 135 of file item_stack.cpp.
 {
     for( const item &here : *items ) {
         if( here.stacks_with( it ) ) {
             return &here;
         }
     }
     return nullptr;
 }
References items.
stored_volume()
units::volume item_stack::stored_volume () const
Total volume of the items here.
Definition at line 102 of file item_stack.cpp.
 {
     units::volume ret = 0_ml;
     for( const item &it : *items ) {
         ret += it.volume();
     }
     return ret;
 }
References items, and cata::hash64_detail::ret.
Referenced by doors::close_door(), free_volume(), vehicle::print_part_list(), and map::stored_volume().
use_charges()
std::list< item > item_stack::use_charges (const itype_id & type, int & quantity, const tripoint & pos, const std::function< bool(const item &)> & filter, bool in_tools = false)
Consumes specified charges (or fewer) from the stack.
Parameters
what specific type of charge required, e.g. 'battery'
qty maximum charges to consume. On return set to number of charges not found (or zero)
pos position at which the charges are being consumed
filter Must return true for use to occur.
Returns
Duplicates of each item that provided consumed charges
Definition at line 145 of file item_stack.cpp.
 {
     std::list<item> ret;
     for( auto a = this->begin(); a != this->end() && quantity > 0; ) {
         // Liquid items on the ground could only be used if they're stored on terrain or furniture with LIQUIDCONT flag
         if( ( !a->made_of( phase_id::LIQUID ) ||
               ( a->made_of( phase_id::LIQUID ) &&
                 get_map().has_flag( ter_furn_flag::TFLAG_LIQUIDCONT, pos ) ) ) &&
             a->use_charges( type, quantity, ret, pos, filter, nullptr, in_tools ) ) {
             a = this->erase( a );
         } else {
             ++a;
         }
     }
     return ret;
 }
References a, begin(), end(), erase(), filter, get_map(), LIQUID, math_opers::pos(), cata::hash64_detail::ret, TFLAG_LIQUIDCONT, and type.
Referenced by map::use_charges().
Member Data Documentation
items
cata::colony<item>* item_stack::items protected
Definition at line 27 of file item_stack.h.
Referenced by inventory_selector::add_vehicle_items(), begin(), veh_interact::display_stats(), empty(), end(), vehicle_folding_activity_actor::fold_vehicle(), get_index_from_iterator(), get_iterator_from_index(), get_iterator_from_pointer(), Character::is_snuggling(), only_item(), rbegin(), vehicle::refresh_active_item_cache(), rend(), size(), stacks_with(), stored_volume(), and tidy_activity().
The documentation for this class was generated from the following files:
src/item_stack.h
src/item_stack.cpp