Cataclysm DDA: anonymous_namespace{animation.cpp}::basic_animation Class Reference
anonymous_namespace{animation.cpp}::basic_animation Class Reference
Public Member Functions
basic_animation (const int scale)
void draw () const
void progress () const
Private Attributes
int_least64_t delay
Detailed Description
Definition at line 49 of file animation.cpp.
Constructor & Destructor Documentation
basic_animation()
anonymous_namespace{animation.cpp}::basic_animation::basic_animation (const int scale) inline explicit
Definition at line 52 of file animation.cpp.
                                                     :
             delay( get_option<int>( "ANIMATION_DELAY" ) * scale * 1'000'000L ) {
         }
Member Function Documentation
draw()
void anonymous_namespace{animation.cpp}::basic_animation::draw () const inline
Definition at line 56 of file animation.cpp.
{
             static_popup popup;
             popup
             .wait_message( "%s", _( "Hang on a bit…" ) )
             .on_top( true );
             g->invalidate_main_ui_adaptor();
             ui_manager::redraw_invalidated();
             refresh_display();
         }
References _, g, popup(), ui_manager::redraw_invalidated(), and refresh_display().
progress()
void anonymous_namespace{animation.cpp}::basic_animation::progress () const inline
Definition at line 67 of file animation.cpp.
{
             draw();
             const auto sleep_till = std::chrono::steady_clock::now() + std::chrono::nanoseconds( delay );
             do {
                 const auto sleep_for = std::min( sleep_till - std::chrono::steady_clock::now(),
                                                  // Pump events every 100 ms
                                                  std::chrono::nanoseconds( 100'000'000 ) );
                 if( sleep_for > std::chrono::nanoseconds( 0 ) ) {
                     std::this_thread::sleep_for( sleep_for );
                     inp_mngr.pump_events();
                 } else {
                     break;
                 }
             } while( true );
         }
References overmap_ui::draw(), inp_mngr, min(), input_manager::pump_events(), and std::this_thread::sleep_for().
Referenced by anonymous_namespace{animation.cpp}::draw_bullet_curses(), and anonymous_namespace{animation.cpp}::draw_explosion_curses().
Member Data Documentation
delay
int_least64_t anonymous_namespace{animation.cpp}::basic_animation::delay private
Definition at line 85 of file animation.cpp.
The documentation for this class was generated from the following file:
src/animation.cpp