Cataclysm DDA: score Class Reference
score Class Reference
#include <event_statistics.h>
Public Member Functions
score ()=default
std::string description (stats_tracker &) const
cata_variant value (stats_tracker &) const
void load (const JsonObject &, std::string_view)
void check () const
Static Public Member Functions
static void load_score (const JsonObject &, const std::string &)
static void check_consistency ()
static const std::vector< score > & get_all ()
static void reset ()
Public Attributes
string_id< score > id
std::vector< std::pair< string_id< score >, mod_id > > src
bool was_loaded = false
Private Attributes
translation description_
string_id< event_statistic > stat_
Detailed Description
Definition at line 101 of file event_statistics.h.
Constructor & Destructor Documentation
score()
score::score () default
Member Function Documentation
check()
void score::check () const
Definition at line 1306 of file event_statistics.cpp.
 {
     if( !stat_.is_valid() ) {
         debugmsg( "score %s refers to invalid statistic %s", id.str(), stat_.str() );
     }
 }
References debugmsg, string_id< T >::is_valid(), stat_, and string_id< T >::str().
check_consistency()
void score::check_consistency () static
Definition at line 136 of file event_statistics.cpp.
 {
     score_factory.check();
 }
References anonymous_namespace{event_statistics.cpp}::score_factory.
Referenced by DynamicDataLoader::check_consistency().
description()
std::string score::description (stats_tracker & stats) const
Definition at line 1277 of file event_statistics.cpp.
 {
     cata_variant val = value( stats );
     std::string value_string = value( stats ).get_string();
     std::string desc;
     if( val.type() == cata_variant_type::int_ ) {
         desc = stat_->description().translated( val.get<int>() );
     } else {
         desc = stat_->description().translated();
     }
     if( description_.empty() ) {
         //~ Default format for scores.  %1$s is statistic description; %2$s is value.
         return string_format( _( "%2$s %1$s" ), desc, value_string );
     } else {
         return string_format( desc, value_string );
     }
 }
References _, event_statistic::description(), description_, translation::empty(), cata_variant::get(), cata_variant::get_string(), int_, stat_, string_format(), translation::translated(), cata_variant::type(), and value().
get_all()
const std::vector< score > & score::get_all () static
Definition at line 141 of file event_statistics.cpp.
 {
     return score_factory.get_all();
 }
References anonymous_namespace{event_statistics.cpp}::score_factory.
Referenced by stats_tracker::notify(), and stats_tracker::valid_scores().
load()
void score::load (const JsonObject & jo, std::string_view)
Definition at line 1300 of file event_statistics.cpp.
 {
     optional( jo, was_loaded, "description", description_ );
     mandatory( jo, was_loaded, "statistic", stat_ );
 }
References description_, mandatory, optional(), stat_, and was_loaded.
load_score()
void score::load_score (const JsonObject & jo, const std::string & src) static
Definition at line 131 of file event_statistics.cpp.
 {
     score_factory.load( jo, src );
 }
References anonymous_namespace{event_statistics.cpp}::score_factory, and src.
Referenced by DynamicDataLoader::initialize().
reset()
void score::reset () static
Definition at line 146 of file event_statistics.cpp.
 {
     score_factory.reset();
 }
References anonymous_namespace{event_statistics.cpp}::score_factory.
Referenced by DynamicDataLoader::unload_data().
value()
cata_variant score::value (stats_tracker & stats) const
Definition at line 1295 of file event_statistics.cpp.
 {
     return stats.value_of( stat_ );
 }
References stat_.
Referenced by description().
Member Data Documentation
description_
translation score::description_ private
Definition at line 120 of file event_statistics.h.
Referenced by description(), and load().
id
string_id<score> score::id
Definition at line 116 of file event_statistics.h.
src
std::vector<std::pair<string_id<score>, mod_id> > score::src
Definition at line 117 of file event_statistics.h.
Referenced by load_score().
stat_
string_id<event_statistic> score::stat_ private
Definition at line 121 of file event_statistics.h.
Referenced by check(), description(), load(), and value().
was_loaded
bool score::was_loaded = false
Definition at line 118 of file event_statistics.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/event_statistics.h
src/event_statistics.cpp