Cataclysm DDA: cata::list< element_type, element_allocator_type >::group_vector Class Reference
cata::list< element_type, element_allocator_type >::group_vector Class Reference
Classes
struct ebco_pair
struct ebco_pair2
Public Member Functions
group_vector () noexcept
LIST_FORCE_INLINE void blank () noexcept
group_vector (group_vector &&source) noexcept
group_vector & operator= (group_vector &&source) noexcept
~group_vector () noexcept=default
void destroy_all_data (const node_pointer_type last_endpoint_node) noexcept
void clear (const node_pointer_type last_endpoint_node) noexcept
void expand_capacity (const size_type new_capacity)
void add_new (const group_size_type group_size)
void initialize (const group_size_type group_size)
void remove (group_pointer_type const group_to_erase) noexcept
void move_to_back (group_pointer_type const group_to_erase)
group_pointer_type get_nearest_freelist_group (const node_pointer_type location_node) noexcept
void swap (group_vector &source) LIST_NOEXCEPT_SWAP(group_allocator_type)
void trim_trailing_groups () noexcept
void append (group_vector &source)
Public Attributes
group_pointer_type last_endpoint_group
group_pointer_type block_pointer
group_pointer_type last_searched_group
size_type size
cata::list::group_vector::ebco_pair2 element_allocator_pair
cata::list::group_vector::ebco_pair group_allocator_pair
Detailed Description
template<class element_type, class element_allocator_type = std::allocator<element_type>>
class cata::list< element_type, element_allocator_type >::group_vector
Definition at line 200 of file list.h.
Constructor & Destructor Documentation
group_vector() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::group_vector::group_vector () inline noexcept
Definition at line 218 of file list.h.
                                        :
                     node_pointer_allocator_type( node_pointer_allocator_type() ),
                     last_endpoint_group( nullptr ),
                     block_pointer( nullptr ),
                     last_searched_group( nullptr ),
                     size( 0 ),
                     element_allocator_pair( 0 ),
                     group_allocator_pair( 0 )
                 {}
group_vector() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::group_vector::group_vector (group_vector && source) inline noexcept
Definition at line 241 of file list.h.
                                                               :
                     last_endpoint_group( std::move( source.last_endpoint_group ) ),
                     block_pointer( std::move( source.block_pointer ) ),
                     last_searched_group( std::move( source.last_searched_group ) ),
                     size( source.size ),
                     element_allocator_pair( source.element_allocator_pair.capacity ),
                     group_allocator_pair( source.group_allocator_pair.capacity ) {
                     source.blank();
                 }
~group_vector()
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::group_vector::~group_vector () default noexcept
Member Function Documentation
add_new()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_vector::add_new (const group_size_type group_size) inline
Definition at line 403 of file list.h.
{
                     if( group_allocator_pair.capacity == size ) {
                         expand_capacity( group_allocator_pair.capacity * 2 );
                     }
                     last_endpoint_group = block_pointer + size - 1;
                     LIST_CONSTRUCT( group_allocator_type, group_allocator_pair, last_endpoint_group + 1, group_size,
                                     last_endpoint_group->nodes );
                     ++last_endpoint_group; // Doing this here instead of pre-construct to avoid need for a try-catch block
                     element_allocator_pair.capacity += group_size;
                     ++size;
                 }
References LIST_CONSTRUCT, and om_direction::size.
Referenced by cata::list< element_type, element_allocator_type >::emplace(), cata::list< element_type, element_allocator_type >::insert(), and cata::list< element_type, element_allocator_type >::reserve().
append()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_vector::append (group_vector & source) inline
Definition at line 695 of file list.h.
{
                     source.trim_trailing_groups();
                     trim_trailing_groups();
                     if( size + source.size > group_allocator_pair.capacity ) {
                         expand_capacity( size + source.size );
                     }
                     if LIST_CONSTEXPR( std::is_trivially_copyable<node_pointer_type>::value &&
                                        std::is_trivially_destructible<node_pointer_type>::value ) {
                         // &* in order to deal with smart pointer situations ie. obtaining the raw pointer from the smart pointer
                         std::memcpy( static_cast<void *>( &*block_pointer + size ),
                                      static_cast<void *>( &*source.block_pointer ), sizeof( group ) * source.size );
                     } else if LIST_CONSTEXPR( std::is_move_constructible<node_pointer_type>::value ) {
                         std::uninitialized_copy( std::make_move_iterator( source.block_pointer ),
                                                  std::make_move_iterator( source.block_pointer + source.size ), block_pointer + size );
                     } else {
                         group_pointer_type current_new_group = block_pointer + size;
                         const group_pointer_type beyond_end_source = source.block_pointer + source.size;
                         for( group_pointer_type current_group = source.block_pointer; current_group != beyond_end_source;
                              ++current_group ) {
                             *( current_new_group++ ) = *current_group;
                             current_group->nodes = nullptr;
                             current_group->beyond_end = nullptr;
                             LIST_DESTROY( group_allocator_type, source.group_allocator_pair, current_group );
                         }
                     }
                     LIST_DEALLOCATE( group_allocator_type, source.group_allocator_pair, source.block_pointer,
                                      source.group_allocator_pair.capacity );
                     size += source.size;
                     last_endpoint_group = block_pointer + size - 1;
                     element_allocator_pair.capacity += source.element_allocator_pair.capacity;
                     source.blank();
                 }
References cata::list< element_type, element_allocator_type >::group_vector::blank(), cata::list< element_type, element_allocator_type >::group_vector::block_pointer, cata::list< element_type, element_allocator_type >::group_vector::ebco_pair2::capacity, cata::list< element_type, element_allocator_type >::group_vector::ebco_pair::capacity, cata::list< element_type, element_allocator_type >::group_vector::element_allocator_pair, cata::list< element_type, element_allocator_type >::group_vector::group_allocator_pair, LIST_CONSTEXPR, LIST_DEALLOCATE, LIST_DESTROY, cata::list< element_type, element_allocator_type >::group_vector::size, om_direction::size, and cata::list< element_type, element_allocator_type >::group_vector::trim_trailing_groups().
Referenced by cata::list< element_type, element_allocator_type >::append_process().
blank()
template<class element_type , class element_allocator_type = std::allocator<element_type>> LIST_FORCE_INLINE void cata::list< element_type, element_allocator_type >::group_vector::blank () inline noexcept
Definition at line 228 of file list.h.
{
                     if LIST_CONSTEXPR( std::is_trivial<group_pointer_type>::value ) {
                         std::memset( static_cast<void *>( this ), 0, sizeof( group_vector ) );
                     } else {
                         last_endpoint_group = nullptr;
                         block_pointer = nullptr;
                         last_searched_group = nullptr;
                         size = 0;
                         element_allocator_pair.capacity = 0;
                         group_allocator_pair.capacity = 0;
                     }
                 }
References LIST_CONSTEXPR, and om_direction::size.
Referenced by cata::list< element_type, element_allocator_type >::group_vector::append().
clear()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_vector::clear (const node_pointer_type last_endpoint_node) inline noexcept
Definition at line 291 of file list.h.
{
                     for( group_pointer_type current_group = block_pointer; current_group != last_endpoint_group;
                          ++current_group ) {
                         if LIST_CONSTEXPR( !std::is_trivially_destructible<element_type>::value ||
                                            !std::is_trivially_destructible<node_pointer_type>::value ) {
                             const node_pointer_type end = current_group->beyond_end;
                             if( ( end - current_group->nodes ) != current_group->number_of_elements ) {
                                 // If there are erased nodes present in the group
                                 for( node_pointer_type current_node = current_group->nodes; current_node != end; ++current_node ) {
                                     if LIST_CONSTEXPR( !std::is_trivially_destructible<element_type>::value ) {
                                         if( current_node->next != nullptr ) { // ie. is not part of free list
                                             LIST_DESTROY( element_allocator_type, element_allocator_pair, &( current_node->element ) );
                                         }
                                     }
                                     if LIST_CONSTEXPR( !std::is_trivially_destructible<node_pointer_type>::value ) {
                                         LIST_DESTROY( node_pointer_allocator_type, ( *this ), &( current_node->next ) );
                                         LIST_DESTROY( node_pointer_allocator_type, ( *this ), &( current_node->previous ) );
                                     }
                                 }
                             } else {
                                 for( node_pointer_type current_node = current_group->nodes; current_node != end; ++current_node ) {
                                     if LIST_CONSTEXPR( !std::is_trivially_destructible<element_type>::value ) {
                                         LIST_DESTROY( element_allocator_type, element_allocator_pair, &( current_node->element ) );
                                     }
                                     if LIST_CONSTEXPR( !std::is_trivially_destructible<node_pointer_type>::value ) {
                                         LIST_DESTROY( node_pointer_allocator_type, ( *this ), &( current_node->next ) );
                                         LIST_DESTROY( node_pointer_allocator_type, ( *this ), &( current_node->previous ) );
                                     }
                                 }
                             }
                         }
                         current_group->free_list_head = nullptr;
                         current_group->number_of_elements = 0;
                     }
                     if LIST_CONSTEXPR( !std::is_trivially_destructible<element_type>::value ||
                                        !std::is_trivially_destructible<node_pointer_type>::value ) {
                         if( ( last_endpoint_node - last_endpoint_group->nodes ) !=
                             last_endpoint_group->number_of_elements ) {
                             // If there are erased nodes present in the group
                             for( node_pointer_type current_node = last_endpoint_group->nodes;
                                  current_node != last_endpoint_node; ++current_node ) {
                                 if LIST_CONSTEXPR( !std::is_trivially_destructible<element_type>::value ) {
                                     if( current_node->next != nullptr ) {
                                         // is not part of free list ie. element has not already had it's destructor called
                                         LIST_DESTROY( element_allocator_type, element_allocator_pair, &( current_node->element ) );
                                     }
                                 }
                                 if LIST_CONSTEXPR( !std::is_trivially_destructible<node_pointer_type>::value ) {
                                     LIST_DESTROY( node_pointer_allocator_type, ( *this ), &( current_node->next ) );
                                     LIST_DESTROY( node_pointer_allocator_type, ( *this ), &( current_node->previous ) );
                                 }
                             }
                         } else {
                             for( node_pointer_type current_node = last_endpoint_group->nodes;
                                  current_node != last_endpoint_node; ++current_node ) {
                                 if LIST_CONSTEXPR( !std::is_trivially_destructible<element_type>::value ) {
                                     LIST_DESTROY( element_allocator_type, element_allocator_pair, &( current_node->element ) );
                                 }
                                 if LIST_CONSTEXPR( !std::is_trivially_destructible<node_pointer_type>::value ) {
                                     LIST_DESTROY( node_pointer_allocator_type, ( *this ), &( current_node->next ) );
                                     LIST_DESTROY( node_pointer_allocator_type, ( *this ), &( current_node->previous ) );
                                 }
                             }
                         }
                     }
                     last_endpoint_group->free_list_head = nullptr;
                     last_endpoint_group->number_of_elements = 0;
                     last_searched_group = last_endpoint_group = block_pointer;
                 }
References keycode::end, LIST_CONSTEXPR, and LIST_DESTROY.
Referenced by cata::list< element_type, element_allocator_type >::clear().
destroy_all_data()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_vector::destroy_all_data (const node_pointer_type last_endpoint_node) inline noexcept
Definition at line 270 of file list.h.
{
                     if( block_pointer == nullptr ) {
                         return;
                     }
                     if LIST_CONSTEXPR( !std::is_trivially_destructible<element_type>::value ||
                                        !std::is_trivially_destructible<node_pointer_type>::value ) {
                         clear( last_endpoint_node ); // If clear has already been called, last_endpoint_node will already be == block_pointer->nodes, so no work will occur
                     }
                     const group_pointer_type end_group = block_pointer + size;
                     for( group_pointer_type current_group = block_pointer; current_group != end_group;
                          ++current_group ) {
                         LIST_DESTROY( group_allocator_type, group_allocator_pair, current_group );
                     }
                     LIST_DEALLOCATE( group_allocator_type, group_allocator_pair, block_pointer,
                                      group_allocator_pair.capacity );
                     blank();
                 }
References clear, LIST_CONSTEXPR, LIST_DEALLOCATE, LIST_DESTROY, and om_direction::size.
Referenced by cata::list< element_type, element_allocator_type >::operator=(), cata::list< element_type, element_allocator_type >::reset(), and cata::list< element_type, element_allocator_type >::~list().
expand_capacity()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_vector::expand_capacity (const size_type new_capacity) inline
Definition at line 369 of file list.h.
                                                                      { // used by add_new and append
                     group_pointer_type const old_block = block_pointer;
                     block_pointer = LIST_ALLOCATE( group_allocator_type, group_allocator_pair, new_capacity, nullptr );
                     if LIST_CONSTEXPR( std::is_trivially_copyable<node_pointer_type>::value &&
                                        std::is_trivially_destructible<node_pointer_type>::value ) {
                         // Dereferencing here in order to deal with smart pointer situations i.e. obtaining the raw pointer from the smart pointer
                         // reinterpret_cast necessary to deal with GCC 8 warnings
                         std::memcpy( static_cast<void *>( &*block_pointer ), static_cast<void *>( &*old_block ),
                                      sizeof( group ) * size );
                     } else if LIST_CONSTEXPR( std::is_move_constructible<node_pointer_type>::value ) {
                         std::uninitialized_copy( std::make_move_iterator( old_block ),
                                                  std::make_move_iterator( old_block + size ), block_pointer );
                     } else {
                         // If allocator supplies non-trivial pointers it becomes necessary to destroy the group. uninitialized_copy will not work in this context as the copy constructor for "group" is overridden in C++03/98. The = operator for "group" has been overridden to make the following work:
                         const group_pointer_type beyond_end = old_block + size;
                         group_pointer_type current_new_group = block_pointer;
                         for( group_pointer_type current_group = old_block; current_group != beyond_end; ++current_group ) {
                             *( current_new_group++ ) = *current_group;
                             current_group->nodes = nullptr;
                             current_group->beyond_end = nullptr;
                             LIST_DESTROY( group_allocator_type, group_allocator_pair, current_group );
                         }
                     }
                     // correct pointer post-reallocation
                     last_searched_group = block_pointer + ( last_searched_group - old_block );
                     LIST_DEALLOCATE( group_allocator_type, group_allocator_pair, old_block,
                                      group_allocator_pair.capacity );
                     group_allocator_pair.capacity = new_capacity;
                 }
References LIST_ALLOCATE, LIST_CONSTEXPR, LIST_DEALLOCATE, LIST_DESTROY, and om_direction::size.
get_nearest_freelist_group()
template<class element_type , class element_allocator_type = std::allocator<element_type>> group_pointer_type cata::list< element_type, element_allocator_type >::group_vector::get_nearest_freelist_group (const node_pointer_type location_node) inline noexcept
Definition at line 496 of file list.h.
{
                     const group_pointer_type beyond_end_group = last_endpoint_group + 1;
                     group_pointer_type left = last_searched_group - 1;
                     group_pointer_type right = last_searched_group + 1;
                     group_pointer_type freelist_group = nullptr;
                     bool right_not_beyond_back = right < beyond_end_group;
                     bool left_not_beyond_front = left >= block_pointer;
                     // ie. location is within last_search_group
                     if( location_node >= last_searched_group->nodes &&
                         location_node < last_searched_group->beyond_end ) {
                         // if last_searched_group has previously-erased nodes
                         if( last_searched_group->free_list_head != nullptr ) {
                             return last_searched_group;
                         }
                     } else { // search for the node group which location_node is located within, using last_searched_group as a starting point and searching left and right. Try and find the closest node group with reusable erased-element locations along the way:
                         group_pointer_type closest_freelist_left = ( last_searched_group->free_list_head == nullptr ) ?
                                 nullptr :
                                 last_searched_group;
                         group_pointer_type closest_freelist_right = ( last_searched_group->free_list_head == nullptr ) ?
                                 nullptr : last_searched_group;
                         while( true ) {
                             if( right_not_beyond_back ) {
                                 // location_node's group is found
                                 if( ( location_node < right->beyond_end ) && ( location_node >= right->nodes ) ) {
                                     // group has erased nodes, reuse them:
                                     if( right->free_list_head != nullptr ) {
                                         last_searched_group = right;
                                         return right;
                                     }
                                     difference_type left_distance;
                                     if( closest_freelist_right != nullptr ) {
                                         last_searched_group = right;
                                         left_distance = right - closest_freelist_right;
                                         if( left_distance <= 2 ) { // ie. this group is close enough to location_node's group
                                             return closest_freelist_right;
                                         }
                                         freelist_group = closest_freelist_right;
                                     } else {
                                         last_searched_group = right;
                                         left_distance = right - left;
                                     }
                                     // Otherwise find closest group with freelist - check an equal distance on the right to the distance we've checked on the left:
                                     const group_pointer_type end_group = ( ( right + left_distance ) > beyond_end_group ) ?
                                                                          beyond_end_group : ( right + left_distance - 1 );
                                     while( ++right != end_group ) {
                                         if( right->free_list_head != nullptr ) {
                                             return right;
                                         }
                                     }
                                     if( freelist_group != nullptr ) {
                                         return freelist_group;
                                     }
                                     right_not_beyond_back = ( right < beyond_end_group );
                                     break; // group with reusable erased nodes not found yet, continue searching in loop below
                                 }
                                 // location_node's group not found, but a reusable location found
                                 if( right->free_list_head != nullptr ) {
                                     if( ( closest_freelist_right == nullptr ) & ( closest_freelist_left == nullptr ) ) {
                                         closest_freelist_left = right;
                                     }
                                     closest_freelist_right = right;
                                 }
                                 right_not_beyond_back = ( ++right < beyond_end_group );
                             }
                             if( left_not_beyond_front ) {
                                 if( ( location_node >= left->nodes ) && ( location_node < left->beyond_end ) ) {
                                     if( left->free_list_head != nullptr ) {
                                         last_searched_group = left;
                                         return left;
                                     }
                                     difference_type right_distance;
                                     if( closest_freelist_left != nullptr ) {
                                         last_searched_group = left;
                                         right_distance = closest_freelist_left - left;
                                         if( right_distance <= 2 ) {
                                             return closest_freelist_left;
                                         }
                                         freelist_group = closest_freelist_left;
                                     } else {
                                         last_searched_group = left;
                                         right_distance = right - left;
                                     }
                                     // Otherwise find closest group with freelist:
                                     const group_pointer_type end_group = ( ( left - right_distance ) < block_pointer ) ? block_pointer
                                                                          - 1 : ( left - right_distance ) + 1;
                                     while( --left != end_group ) {
                                         if( left->free_list_head != nullptr ) {
                                             return left;
                                         }
                                     }
                                     if( freelist_group != nullptr ) {
                                         return freelist_group;
                                     }
                                     left_not_beyond_front = ( left >= block_pointer );
                                     break;
                                 }
                                 if( left->free_list_head != nullptr ) {
                                     if( ( closest_freelist_left == nullptr ) & ( closest_freelist_right == nullptr ) ) {
                                         closest_freelist_right = left;
                                     }
                                     closest_freelist_left = left;
                                 }
                                 left_not_beyond_front = ( --left >= block_pointer );
                             }
                         }
                     }
                     // The node group which location_node is located within, is known at this point. Continue searching outwards from this group until a group is found with a reusable location:
                     while( true ) {
                         if( right_not_beyond_back ) {
                             if( right->free_list_head != nullptr ) {
                                 return right;
                             }
                             right_not_beyond_back = ( ++right < beyond_end_group );
                         }
                         if( left_not_beyond_front ) {
                             if( left->free_list_head != nullptr ) {
                                 return left;
                             }
                             left_not_beyond_front = ( --left >= block_pointer );
                         }
                     }
                     // Will never reach here on functioning implementations
                 }
Referenced by cata::list< element_type, element_allocator_type >::emplace(), and cata::list< element_type, element_allocator_type >::insert().
initialize()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_vector::initialize (const group_size_type group_size) inline
Definition at line 419 of file list.h.
{
                     last_endpoint_group = block_pointer = last_searched_group = LIST_ALLOCATE( group_allocator_type,
                                                           group_allocator_pair, 1, nullptr );
                     group_allocator_pair.capacity = 1;
                     LIST_CONSTRUCT( group_allocator_type, group_allocator_pair, last_endpoint_group, group_size );
                     size = 1; // Doing these here instead of pre-construct to avoid need for a try-catch block
                     element_allocator_pair.capacity = group_size;
                 }
References LIST_ALLOCATE, LIST_CONSTRUCT, and om_direction::size.
Referenced by cata::list< element_type, element_allocator_type >::emplace(), cata::list< element_type, element_allocator_type >::insert(), and cata::list< element_type, element_allocator_type >::reserve().
move_to_back()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_vector::move_to_back (group_pointer_type const group_to_erase) inline
Definition at line 457 of file list.h.
{
                     if( last_searched_group >= group_to_erase && last_searched_group != block_pointer ) {
                         --last_searched_group;
                     }
                     group *temp_group = LIST_ALLOCATE( group_allocator_type, group_allocator_pair, 1, nullptr );
                     if LIST_CONSTEXPR( std::is_trivially_copyable<node_pointer_type>::value &&
                                        std::is_trivially_destructible<node_pointer_type>::value ) {
                         std::memcpy( static_cast<void *>( &*temp_group ), static_cast<void *>( &*group_to_erase ),
                                      sizeof( group ) );
                         std::memmove( static_cast<void *>( &*group_to_erase ), static_cast<void *>( &*group_to_erase + 1 ),
                                       sizeof( group ) * ( ( size - 1 ) - static_cast<size_type>( &*group_to_erase - &*block_pointer ) ) );
                         std::memcpy( static_cast<void *>( &*( block_pointer + size - 1 ) ),
                                      static_cast<void *>( &*temp_group ), sizeof( group ) );
                     } else if LIST_CONSTEXPR( std::is_move_constructible<node_pointer_type>::value ) {
                         LIST_CONSTRUCT( group_allocator_type, group_allocator_pair, temp_group,
                                         std::move( *group_to_erase ) );
                         std::move( group_to_erase + 1, block_pointer + size, group_to_erase );
                         *( block_pointer + size - 1 ) = std::move( *temp_group );
                         if LIST_CONSTEXPR( !std::is_trivially_destructible<node_pointer_type>::value ) {
                             LIST_DESTROY( group_allocator_type, group_allocator_pair, temp_group );
                         }
                     } else {
                         LIST_CONSTRUCT( group_allocator_type, group_allocator_pair, temp_group, group() );
                         *temp_group = *group_to_erase;
                         std::copy( group_to_erase + 1, block_pointer + size, group_to_erase );
                         *( block_pointer + --size ) = *temp_group;
                         temp_group->nodes = nullptr;
                         LIST_DESTROY( group_allocator_type, group_allocator_pair, temp_group );
                     }
                     LIST_DEALLOCATE( group_allocator_type, group_allocator_pair, temp_group, 1 );
                 }
References LIST_ALLOCATE, LIST_CONSTEXPR, LIST_CONSTRUCT, LIST_DEALLOCATE, LIST_DESTROY, cata::list< element_type, element_allocator_type >::group::nodes, and om_direction::size.
Referenced by cata::list< element_type, element_allocator_type >::erase().
operator=()
template<class element_type , class element_allocator_type = std::allocator<element_type>> group_vector& cata::list< element_type, element_allocator_type >::group_vector::operator= (group_vector && source) inline noexcept
Definition at line 251 of file list.h.
{
                     if LIST_CONSTEXPR( std::is_trivial<group_pointer_type>::value ) {
                         // NOLINTNEXTLINE(bugprone-undefined-memory-manipulation)
                         std::memcpy( static_cast<void *>( this ), &source, sizeof( group_vector ) );
                     } else {
                         last_endpoint_group = std::move( source.last_endpoint_group );
                         block_pointer = std::move( source.block_pointer );
                         last_searched_group = std::move( source.last_searched_group );
                         size = source.size;
                         element_allocator_pair.capacity = source.element_allocator_pair.capacity;
                         group_allocator_pair.capacity = source.group_allocator_pair.capacity;
                     }
                     source.blank();
                     return *this;
                 }
References LIST_CONSTEXPR, and om_direction::size.
remove()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_vector::remove (group_pointer_type const group_to_erase) inline noexcept
Definition at line 430 of file list.h.
{
                     if( last_searched_group >= group_to_erase && last_searched_group != block_pointer ) {
                         --last_searched_group;
                     }
                     element_allocator_pair.capacity -= static_cast<size_type>( group_to_erase->beyond_end -
                                                        group_to_erase->nodes );
                     LIST_DESTROY( group_allocator_type, group_allocator_pair, group_to_erase );
                     if LIST_CONSTEXPR( std::is_trivially_copyable<node_pointer_type>::value &&
                                        std::is_trivially_destructible<node_pointer_type>::value ) {
                         // Dereferencing here in order to deal with smart pointer situations ie. obtaining the raw pointer from the smart pointer
                         std::memmove( static_cast<void *>( &*group_to_erase ), static_cast<void *>( &*group_to_erase + 1 ),
                                       sizeof( group ) * ( --size - static_cast<size_type>( &*group_to_erase - &*block_pointer ) ) );
                     } else if LIST_CONSTEXPR( std::is_move_constructible<node_pointer_type>::value ) {
                         std::move( group_to_erase + 1, block_pointer + size--, group_to_erase );
                     } else {
                         group_pointer_type back = block_pointer + size--;
                         std::copy( group_to_erase + 1, back--, group_to_erase );
                         back->nodes = nullptr;
                         back->beyond_end = nullptr;
                         LIST_DESTROY( group_allocator_type, group_allocator_pair, back );
                     }
                 }
References LIST_CONSTEXPR, LIST_DESTROY, and om_direction::size.
Referenced by cata::list< element_type, element_allocator_type >::erase(), and cata::list< element_type, element_allocator_type >::reserve().
swap()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_vector::swap (group_vector & source) inline
Definition at line 650 of file list.h.
{
                     if LIST_CONSTEXPR(
                         std::is_trivial<group_pointer_type>::value ) { // if all pointer types are trivial we can just copy using memcpy - faster - avoids constructors/destructors etc
                         // NOLINTNEXTLINE(modernize-avoid-c-arrays)
                         char temp[sizeof( group_vector )];
                         std::memcpy( static_cast<void *>( &temp ), static_cast<void *>( this ), sizeof( group_vector ) );
                         std::memcpy( static_cast<void *>( this ), static_cast<void *>( &source ), sizeof( group_vector ) );
                         std::memcpy( static_cast<void *>( &source ), static_cast<void *>( &temp ), sizeof( group_vector ) );
                     } else {
                         const group_pointer_type swap_last_endpoint_group = last_endpoint_group;
                         const group_pointer_type swap_block_pointer = block_pointer;
                         const group_pointer_type swap_last_searched_group = last_searched_group;
                         const size_type swap_size = size;
                         const size_type swap_element_capacity = element_allocator_pair.capacity;
                         const size_type swap_capacity = group_allocator_pair.capacity;
                         last_endpoint_group = source.last_endpoint_group;
                         block_pointer = source.block_pointer;
                         last_searched_group = source.last_searched_group;
                         size = source.size;
                         element_allocator_pair.capacity = source.element_allocator_pair.capacity;
                         group_allocator_pair.capacity = source.group_allocator_pair.capacity;
                         source.last_endpoint_group = swap_last_endpoint_group;
                         source.block_pointer = swap_block_pointer;
                         source.last_searched_group = swap_last_searched_group;
                         source.size = swap_size;
                         source.element_allocator_pair.capacity = swap_element_capacity;
                         source.group_allocator_pair.capacity = swap_capacity;
                     }
                 }
References LIST_CONSTEXPR, om_direction::size, and temp.
trim_trailing_groups()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_vector::trim_trailing_groups () inline noexcept
Definition at line 682 of file list.h.
{
                     const group_pointer_type beyond_last = block_pointer + size;
                     for( group_pointer_type current_group = last_endpoint_group + 1; current_group != beyond_last;
                          ++current_group ) {
                         element_allocator_pair.capacity -= static_cast<size_type>( current_group->beyond_end -
                                                            current_group->nodes );
                         LIST_DESTROY( group_allocator_type, group_allocator_pair, current_group );
                     }
                     size -= static_cast<size_type>( beyond_last - ( last_endpoint_group + 1 ) );
                 }
References LIST_DESTROY, and om_direction::size.
Referenced by cata::list< element_type, element_allocator_type >::group_vector::append(), cata::list< element_type, element_allocator_type >::assign(), cata::list< element_type, element_allocator_type >::free_unused_memory(), and cata::list< element_type, element_allocator_type >::shrink_to_fit().
Member Data Documentation
block_pointer
template<class element_type , class element_allocator_type = std::allocator<element_type>> group_pointer_type cata::list< element_type, element_allocator_type >::group_vector::block_pointer
Definition at line 204 of file list.h.
Referenced by cata::list< element_type, element_allocator_type >::group_vector::append(), cata::list< element_type, element_allocator_type >::clear(), cata::list< element_type, element_allocator_type >::emplace(), cata::list< element_type, element_allocator_type >::erase(), cata::list< element_type, element_allocator_type >::insert(), cata::list< element_type, element_allocator_type >::remove_if(), cata::list< element_type, element_allocator_type >::reserve(), cata::list< element_type, element_allocator_type >::reverse(), and cata::list< element_type, element_allocator_type >::sort().
element_allocator_pair
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list::group_vector::ebco_pair2 cata::list< element_type, element_allocator_type >::group_vector::element_allocator_pair
Referenced by cata::list< element_type, element_allocator_type >::group_vector::append(), cata::list< element_type, element_allocator_type >::approximate_memory_use(), cata::list< element_type, element_allocator_type >::capacity(), cata::list< element_type, element_allocator_type >::reserve(), and cata::list< element_type, element_allocator_type >::shrink_to_fit().
group_allocator_pair
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list::group_vector::ebco_pair cata::list< element_type, element_allocator_type >::group_vector::group_allocator_pair
Referenced by cata::list< element_type, element_allocator_type >::group_vector::append(), and cata::list< element_type, element_allocator_type >::approximate_memory_use().
last_endpoint_group
template<class element_type , class element_allocator_type = std::allocator<element_type>> group_pointer_type cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group
Definition at line 204 of file list.h.
Referenced by cata::list< element_type, element_allocator_type >::append_process(), cata::list< element_type, element_allocator_type >::emplace(), cata::list< element_type, element_allocator_type >::erase(), cata::list< element_type, element_allocator_type >::group_fill_position(), cata::list< element_type, element_allocator_type >::insert(), cata::list< element_type, element_allocator_type >::remove_if(), cata::list< element_type, element_allocator_type >::reserve(), cata::list< element_type, element_allocator_type >::reverse(), cata::list< element_type, element_allocator_type >::shrink_to_fit(), and cata::list< element_type, element_allocator_type >::sort().
last_searched_group
template<class element_type , class element_allocator_type = std::allocator<element_type>> group_pointer_type cata::list< element_type, element_allocator_type >::group_vector::last_searched_group
Definition at line 204 of file list.h.
Referenced by cata::list< element_type, element_allocator_type >::erase().
size
template<class element_type , class element_allocator_type = std::allocator<element_type>> size_type cata::list< element_type, element_allocator_type >::group_vector::size
Definition at line 205 of file list.h.
Referenced by cata::list< element_type, element_allocator_type >::group_vector::append(), cata::list< element_type, element_allocator_type >::emplace(), cata::list< element_type, element_allocator_type >::insert(), and cata::list< element_type, element_allocator_type >::reserve().
The documentation for this class was generated from the following file:
src/list.h