Cataclysm DDA: Item_modifier Class Reference
Item_modifier Class Reference
Creates a single item, but can change various aspects of the created item.
#include <item_group.h>
Public Member Functions
Item_modifier ()
Item_modifier (Item_modifier &&)=default
void modify (item &new_item, const std::string &context) const
void check_consistency (const std::string &context) const
bool remove_item (const itype_id &itemid)
void replace_items (const std::unordered_map< itype_id, itype_id > &replacements) const
Public Attributes
std::pair< int, int > damage
std::pair< int, int > count
std::pair< int, int > dirt
Charges to spawn the item with, if this turns out to be negative, the default charges are used.
std::pair< int, int > charges
std::unique_ptr< Item_spawn_data > ammo
Ammo for guns.
std::unique_ptr< Item_spawn_data > container
Item should spawn inside this container, can be NULL, if item should not spawn in a container.
std::unique_ptr< Item_spawn_data > contents
This is used to create the contents of an item.
bool sealed = true
std::vector< flag_id > custom_flags
Custom flags to be added to the item.
std::string variant
gun variant id, for guns with variants
std::vector< snippet_id > snippets
Custom sub set of snippets to be randomly chosen from and then applied to the item.
int with_ammo
Chance [0-100%] for items to spawn with ammo (plus default magazine if necessary)
int with_magazine
Chance [0-100%] for items to spawn with their default magazine (if any)
Detailed Description
Creates a single item, but can change various aspects of the created item.
This is basically a wrapper around Single_item_creator that adds item properties.
Definition at line 238 of file item_group.h.
Constructor & Destructor Documentation
Item_modifier() [1/2]
Item_modifier::Item_modifier ()
Definition at line 502 of file item_group.cpp.
     : damage( 0, 0 )
     , count( -1, -1 )
       // Dirt in guns is capped unless overwritten in the itemgroup
       // most guns should not be very dirty or dirty at all
     , dirt( 0, 500 )
     , charges( -1, -1 )
     , with_ammo( 0 )
     , with_magazine( 0 )
 {
 }
Item_modifier() [2/2]
Item_modifier::Item_modifier (Item_modifier &&) default
Member Function Documentation
check_consistency()
void Item_modifier::check_consistency (const std::string & context) const
Definition at line 729 of file item_group.cpp.
 {
     if( ammo != nullptr ) {
         ammo->check_consistency( true );
     }
     if( container != nullptr ) {
         container->check_consistency( true );
     }
     if( with_ammo < 0 || with_ammo > 100 ) {
         debugmsg( "in %s: Item modifier's ammo chance %d is out of range", context, with_ammo );
     }
     if( with_magazine < 0 || with_magazine > 100 ) {
         debugmsg( "in %s: Item modifier's magazine chance %d is out of range",
                   context, with_magazine );
     }
 }
References ammo, container, context, debugmsg, with_ammo, and with_magazine.
modify()
void Item_modifier::modify (item & new_item, const std::string & context) const
Definition at line 514 of file item_group.cpp.
 {
     if( new_item.is_null() ) {
         return;
     }
     new_item.set_damage( rng( damage.first, damage.second ) );
     new_item.rand_degradation();
     // no need for dirt if it's a bow
     if( new_item.is_gun() && !new_item.has_flag( flag_PRIMITIVE_RANGED_WEAPON ) &&
         !new_item.has_flag( flag_NON_FOULING ) ) {
         int random_dirt = rng( dirt.first, dirt.second );
         // if gun RNG is dirty, must add dirt fault to allow cleaning
         if( random_dirt > 0 ) {
             new_item.set_var( "dirt", random_dirt );
             new_item.faults.emplace( "fault_gun_dirt" );
             // chance to be unlubed, but only if it's not a laser or something
         } else if( one_in( 10 ) && !new_item.has_flag( flag_NEEDS_NO_LUBE ) ) {
             new_item.faults.emplace( "fault_gun_unlubricated" );
         }
     }
     new_item.set_itype_variant( variant );
     {
         // create container here from modifier or from default to get max charges later
         std::optional<item> cont;
         if( container != nullptr ) {
             cont = container->create_single( new_item.birthday() );
         } else if( new_item.type->default_container.has_value() &&
                    !new_item.type->default_container->is_null() ) {
             cont = item( *new_item.type->default_container, new_item.birthday() );
             if( new_item.type->default_container_variant.has_value() ) {
                 cont->set_itype_variant( *new_item.type->default_container_variant );
             }
         }
         int max_capacity = -1;
         if( charges.first != -1 && charges.second == -1 && ( new_item.is_magazine() ||
                 new_item.uses_magazine() ) ) {
             int max_ammo = 0;
             if( new_item.is_magazine() ) {
                 // Get the ammo capacity of the new item itself
                 max_ammo = new_item.ammo_capacity( item_controller->find_template(
                                                        new_item.ammo_default() )->ammo->type );
             } else if( !new_item.magazine_default().is_null() ) {
                 // Get the capacity of the item's default magazine
                 max_ammo = item_controller->find_template( new_item.magazine_default() )->magazine->capacity;
             }
             // Don't change the ammo capacity from 0 if the item isn't a magazine
             // and doesn't have a default magazine with a capacity
             if( max_ammo > 0 ) {
                 max_capacity = max_ammo;
             }
         }
         if( max_capacity == -1 && cont.has_value() && !cont->is_null() &&
             ( new_item.made_of( phase_id::LIQUID ) ||
               ( !new_item.is_tool() && !new_item.is_gun() && !new_item.is_magazine() ) ) ) {
             if( new_item.type->weight == 0_gram ) {
                 max_capacity = new_item.charges_per_volume( cont->get_total_capacity() );
             } else {
                 max_capacity = std::min( new_item.charges_per_volume( cont->get_total_capacity() ),
                                          new_item.charges_per_weight( cont->get_total_weight_capacity() ) );
             }
         }
         const bool charges_not_set = charges.first == -1 && charges.second == -1;
         int ch = -1;
         if( !charges_not_set ) {
             int charges_min = charges.first == -1 ? 0 : charges.first;
             int charges_max = charges.second == -1 ? max_capacity : charges.second;
             if( charges_min == -1 && charges_max != -1 ) {
                 charges_min = 0;
             }
             if( max_capacity != -1 && ( charges_max > max_capacity || ( charges_min != 1 &&
                                         charges_max == -1 ) ) ) {
                 charges_max = max_capacity;
             }
             if( charges_min > charges_max ) {
                 charges_min = charges_max;
             }
             ch = charges_min == charges_max ? charges_min : rng( charges_min,
                     charges_max );
         } else if( cont.has_value() && !cont->is_null() && new_item.made_of( phase_id::LIQUID ) ) {
             new_item.charges = std::max( 1, max_capacity );
         }
         if( ch != -1 ) {
             if( new_item.count_by_charges() || new_item.made_of( phase_id::LIQUID ) ) {
                 // food, ammo
                 // count_by_charges requires that charges is at least 1. It makes no sense to
                 // spawn a "water (0)" item.
                 new_item.charges = std::max( 1, ch );
             } else if( new_item.is_tool() ) {
                 if( !new_item.magazine_current() && !new_item.magazine_default().is_null() ) {
                     item mag( new_item.magazine_default() );
                     if( !mag.ammo_default().is_null() ) {
                         mag.ammo_set( mag.ammo_default(), ch );
                     }
                     new_item.put_in( mag, pocket_type::MAGAZINE_WELL );
                 } else if( new_item.is_magazine() ) {
                     new_item.ammo_set( new_item.ammo_default(), ch );
                 } else if( new_item.magazine_current() ) {
                     new_item.ammo_set( new_item.magazine_current()->ammo_default(), ch );
                 } else {
                     debugmsg( "in %s: tried to set ammo for %s which does not have ammo or a magazine",
                               context, new_item.typeId().str() );
                 }
             } else if( new_item.type->can_have_charges() ) {
                 new_item.charges = ch;
             }
         }
         if( ch > 0 && ( new_item.is_gun() || new_item.is_magazine() ) ) {
             itype_id ammo_id;
             if( ammo ) {
                 ammo_id = ammo->create_single( new_item.birthday() ).typeId();
             } else if( new_item.ammo_default() ) {
                 ammo_id = new_item.ammo_default();
             } else if( new_item.magazine_default() && new_item.magazine_default()->magazine->default_ammo ) {
                 ammo_id = new_item.magazine_default()->magazine->default_ammo;
             }
             if( ammo_id && !ammo_id.is_empty() ) {
                 new_item.ammo_set( ammo_id, ch );
             } else {
                 debugmsg( "tried to set ammo for %s which does not have ammo or a magazine",
                           new_item.typeId().c_str() );
             }
             // Make sure the item is in valid state
             if( new_item.magazine_integral() ) {
                 new_item.charges = std::min( new_item.charges,
                                              new_item.ammo_capacity( item_controller->find_template( new_item.ammo_default() )->ammo->type ) );
             } else {
                 new_item.charges = 0;
             }
         }
         if( new_item.is_magazine() ||
             new_item.has_pocket_type( pocket_type::MAGAZINE_WELL ) ) {
             bool spawn_ammo = rng( 0, 99 ) < with_ammo && new_item.ammo_remaining() == 0 && ch == -1 &&
                               ( !new_item.is_tool() || new_item.type->tool->rand_charges.empty() );
             bool spawn_mag = rng( 0, 99 ) < with_magazine && !new_item.magazine_integral() &&
                              !new_item.magazine_current();
             if( spawn_mag ) {
                 item mag( new_item.magazine_default(), new_item.birthday() );
                 if( spawn_ammo && !mag.ammo_default().is_null() ) {
                     mag.ammo_set( mag.ammo_default() );
                 }
                 new_item.put_in( mag, pocket_type::MAGAZINE_WELL );
             } else if( spawn_ammo && !new_item.ammo_default().is_null() ) {
                 if( ammo ) {
                     const item am = ammo->create_single( new_item.birthday() );
                     new_item.ammo_set( am.typeId() );
                 } else {
                     new_item.ammo_set( new_item.ammo_default() );
                 }
             }
         }
         if( cont.has_value() && !cont->is_null() ) {
             const pocket_type pk_type = guess_pocket_for( *cont, new_item );
             cont->put_in( new_item, pk_type );
             cont->add_automatic_whitelist();
             new_item = std::move( *cont );
             if( sealed ) {
                 new_item.seal();
             }
         }
     }
     if( contents != nullptr ) {
         Item_spawn_data::ItemList contentitems;
         contents->create( contentitems, new_item.birthday() );
         for( const item &it : contentitems ) {
             // custom code for directly attaching pockets to MOLLE vests
             const use_function *action = new_item.get_use( "attach_molle" );
             if( action && it.can_attach_as_pocket() ) {
                 const molle_attach_actor *actor = dynamic_cast<const molle_attach_actor *>
                                                   ( action->get_actor_ptr() );
                 const int vacancies = actor->size - new_item.get_contents().get_additional_space_used();
                 // intentionally might lose items here if they don't fit this is because it's
                 // impossible to know in a spawn group how much stuff could end up in it
                 // if you roll 3, 3 size items in a 3 slot vest you shouldn't get an error
                 // but you should get a vest with at least the first one
                 if( it.get_pocket_size() <= vacancies ) {
                     new_item.get_contents().add_pocket( it );
                 }
             } else {
                 const pocket_type pk_type = guess_pocket_for( new_item, it );
                 new_item.put_in( it, pk_type );
             }
         }
         if( sealed ) {
             new_item.seal();
         }
     }
     for( const flag_id &flag : custom_flags ) {
         new_item.set_flag( flag );
     }
     if( !snippets.empty() ) {
         new_item.snip_id = random_entry( snippets );
     }
 }
References action, item_contents::add_pocket(), ammo, item::ammo_capacity(), item::ammo_default(), item::ammo_remaining(), item::ammo_set(), item::birthday(), string_id< T >::c_str(), itype::can_have_charges(), item::charges, charges, item::charges_per_volume(), item::charges_per_weight(), container, contents, context, item::count_by_charges(), custom_flags, damage, debugmsg, itype::default_container, itype::default_container_variant, dirt, item::faults, flag_NEEDS_NO_LUBE, flag_NON_FOULING, flag_PRIMITIVE_RANGED_WEAPON, item_contents::get_additional_space_used(), item::get_contents(), item::get_use(), guess_pocket_for(), item::has_flag(), item::has_pocket_type(), string_id< T >::is_empty(), item::is_gun(), item::is_magazine(), item::is_null(), string_id< T >::is_null(), item::is_tool(), item, item_controller, LIQUID, item::made_of(), itype::magazine, item::magazine_current(), item::magazine_default(), item::magazine_integral(), MAGAZINE_WELL, max(), min(), one_in(), item::put_in(), item::rand_degradation(), random_entry(), rng(), item::seal(), sealed, item::set_damage(), item::set_flag(), item::set_itype_variant(), item::set_var(), molle_attach_actor::size, item::snip_id, snippets, string_id< T >::str(), itype::tool, item::type, item::typeId(), item::uses_magazine(), variant, itype::weight, with_ammo, and with_magazine.
remove_item()
bool Item_modifier::remove_item (const itype_id & itemid)
Definition at line 746 of file item_group.cpp.
 {
     if( ammo != nullptr ) {
         if( ammo->remove_item( itemid ) ) {
             ammo.reset();
         }
     }
     if( container != nullptr ) {
         if( container->remove_item( itemid ) ) {
             container.reset();
             return true;
         }
     }
     return false;
 }
References ammo, and container.
replace_items()
void Item_modifier::replace_items (const std::unordered_map< itype_id, itype_id > & replacements) const
Definition at line 762 of file item_group.cpp.
 {
     if( ammo ) {
         ammo->replace_items( replacements );
     }
     if( container ) {
         container->replace_items( replacements );
     }
     if( contents ) {
         contents->replace_items( replacements );
     }
 }
References ammo, container, and contents.
Member Data Documentation
ammo
std::unique_ptr<Item_spawn_data> Item_modifier::ammo
Ammo for guns.
If NULL the gun spawns without ammo. This takes charges and with_ammo into account.
Definition at line 253 of file item_group.h.
Referenced by Item_factory::add_entry(), check_consistency(), modify(), remove_item(), and replace_items().
charges
std::pair<int, int> Item_modifier::charges
Definition at line 248 of file item_group.h.
Referenced by Item_factory::add_entry(), and modify().
container
std::unique_ptr<Item_spawn_data> Item_modifier::container
Item should spawn inside this container, can be NULL, if item should not spawn in a container.
If the created item is a liquid and it uses the default charges, it will expand/shrink to fill the container completely. If it is created with to much charges, they are reduced. If it is created with the non-default charges, but it still fits it is not changed.
Definition at line 263 of file item_group.h.
Referenced by Item_factory::add_entry(), check_consistency(), modify(), remove_item(), and replace_items().
contents
std::unique_ptr<Item_spawn_data> Item_modifier::contents
This is used to create the contents of an item.
Definition at line 267 of file item_group.h.
Referenced by Item_factory::add_entry(), modify(), and replace_items().
count
std::pair<int, int> Item_modifier::count
Definition at line 242 of file item_group.h.
Referenced by Item_factory::add_entry().
custom_flags
std::vector<flag_id> Item_modifier::custom_flags
Custom flags to be added to the item.
Definition at line 272 of file item_group.h.
Referenced by Item_factory::add_entry(), and modify().
damage
std::pair<int, int> Item_modifier::damage
Definition at line 241 of file item_group.h.
Referenced by Item_factory::add_entry(), and modify().
dirt
std::pair<int, int> Item_modifier::dirt
Charges to spawn the item with, if this turns out to be negative, the default charges are used.
Definition at line 247 of file item_group.h.
Referenced by Item_factory::add_entry(), and modify().
sealed
bool Item_modifier::sealed = true
Definition at line 268 of file item_group.h.
Referenced by Item_factory::add_entry(), and modify().
snippets
std::vector<snippet_id> Item_modifier::snippets
Custom sub set of snippets to be randomly chosen from and then applied to the item.
Definition at line 282 of file item_group.h.
Referenced by Item_factory::add_entry(), and modify().
variant
std::string Item_modifier::variant
gun variant id, for guns with variants
Definition at line 277 of file item_group.h.
Referenced by Item_factory::add_entry(), and modify().
with_ammo
int Item_modifier::with_ammo
Chance [0-100%] for items to spawn with ammo (plus default magazine if necessary)
Definition at line 295 of file item_group.h.
Referenced by check_consistency(), and modify().
with_magazine
int Item_modifier::with_magazine
Chance [0-100%] for items to spawn with their default magazine (if any)
Definition at line 297 of file item_group.h.
Referenced by check_consistency(), and modify().
The documentation for this class was generated from the following files:
src/item_group.h
src/item_group.cpp