Cataclysm DDA: vehicle_selector Class Reference
vehicle_selector Class Reference
#include <vehicle_selector.h>
Public Types
using value_type = vehicle_cursor
using size_type = std::vector< value_type >::size_type
using iterator = std::vector< value_type >::iterator
using const_iterator = std::vector< value_type >::const_iterator
using reference = std::vector< value_type >::reference
using const_reference = std::vector< value_type >::const_reference
Public Member Functions
vehicle_selector (const tripoint &pos, int radius=0, bool accessible=true, bool visibility_only=false)
Constructs vehicle_selector used for querying items located on vehicle tiles.
vehicle_selector (const tripoint &pos, int radius, bool accessible, const vehicle &ignore)
Constructs vehicle_selector used for querying items located on vehicle tiles.
vehicle_selector (const vehicle_selector &that)=delete
vehicle_selector & operator= (const vehicle_selector &)=delete
vehicle_selector (vehicle_selector &&)=default
size_type size () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
bool has_quality (const quality_id &qual, int level=1, int qty=1) const override
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const override
Return maximum tool quality level provided by instance or INT_MIN if not found.
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const override
Traverses this object and any child items contained using a visitor pattern.
std::list< item > remove_items_with (const std::function< bool(const item &)> &filter, int count=INT_MAX) override
Removes items contained by this instance which match the filter.
Public Member Functions inherited from visitable
item remove_item (item &it)
Removes and returns the item which must be contained by this instance.
Public Member Functions inherited from read_only_visitable
item * find_parent (const item &it) const
Determine the immediate parent container (if any) for an item.
std::vector< item * > parents (const item &it) const
Returns vector of parent containers (if any) starting with the innermost.
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
std::pair< int, int > kcal_range (const itype_id &id, const std::function< bool(const item &)> &filter, Character &player_character) const
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
virtual ~read_only_visitable ()=default
bool has_tools (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
bool has_components (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
virtual bool has_charges (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
Private Attributes
std::vector< value_type > data
Additional Inherited Members
Related Functions inherited from visitable
item * find_parent (const item &it) const
std::vector< item * > parents (const item &it) const
bool has_item (const item &it) const
bool has_item_with (const std::function< bool(const item &)> &filter) const
bool has_quality (const quality_id &qual, int level, int qty) const
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const
Traverses this object and any child items contained using a visitor pattern.
std::list< item > remove_items_with (const std::function< bool(const item &e)> &filter, int count)
int charges_of (const itype_id &what, int limit, const std::function< bool(const item &)> &filter, const std::function< void(int)> &visitor, bool in_tools) const
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo, int limit, const std::function< bool(const item &)> &filter) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo, const std::function< bool(const item &)> &filter) const
Detailed Description
Definition at line 36 of file vehicle_selector.h.
Member Typedef Documentation
const_iterator
using vehicle_selector::const_iterator = std::vector<value_type>::const_iterator
Definition at line 42 of file vehicle_selector.h.
const_reference
using vehicle_selector::const_reference = std::vector<value_type>::const_reference
Definition at line 44 of file vehicle_selector.h.
iterator
using vehicle_selector::iterator = std::vector<value_type>::iterator
Definition at line 41 of file vehicle_selector.h.
reference
using vehicle_selector::reference = std::vector<value_type>::reference
Definition at line 43 of file vehicle_selector.h.
size_type
using vehicle_selector::size_type = std::vector<value_type>::size_type
Definition at line 40 of file vehicle_selector.h.
value_type
using vehicle_selector::value_type = vehicle_cursor
Definition at line 39 of file vehicle_selector.h.
Constructor & Destructor Documentation
vehicle_selector() [1/4]
vehicle_selector::vehicle_selector (const tripoint & pos, int radius = 0, bool accessible = true, bool visibility_only = false) explicit
Constructs vehicle_selector used for querying items located on vehicle tiles.
Parameters
pos map position at which to start each query which may or may not contain vehicle
radius number of adjacent tiles to include (searching from pos outwards)
accessible whether found items must be accessible from pos to be considered
visibility_only accessibility based on line of sight, not walkability
Definition at line 9 of file vehicle_selector.cpp.
 {
     map &here = get_map();
     for( const tripoint &e : closest_points_first( pos, radius ) ) {
         if( !accessible ||
             ( visibility_only ? here.sees( pos, e, radius ) : here.clear_path( pos, e, radius, 1, 100 ) ) ) {
             if( const optional_vpart_position vp = here.veh_at( e ) ) {
                 data.emplace_back( vp->vehicle(), vp->part_index() );
             }
         }
     }
 }
References map::clear_path(), closest_points_first(), data, get_map(), math_opers::pos(), map::sees(), and map::veh_at().
vehicle_selector() [2/4]
vehicle_selector::vehicle_selector (const tripoint & pos, int radius, bool accessible, const vehicle & ignore)
Constructs vehicle_selector used for querying items located on vehicle tiles.
Parameters
pos map position at which to start each query which may or may not contain vehicle
radius number of adjacent tiles to include (searching from pos outwards)
accessible whether found items must be accessible from pos to be considered
ignore don't include this vehicle as part of the selection
Definition at line 23 of file vehicle_selector.cpp.
 {
     map &here = get_map();
     for( const tripoint &e : closest_points_first( pos, radius ) ) {
         if( !accessible || here.clear_path( pos, e, radius, 1, 100 ) ) {
             if( const optional_vpart_position vp = here.veh_at( e ) ) {
                 data.emplace_back( vp->vehicle(), vp->part_index(), &vp->vehicle() == &ignore );
             }
         }
     }
 }
References map::clear_path(), closest_points_first(), data, get_map(), math_opers::pos(), and map::veh_at().
vehicle_selector() [3/4]
vehicle_selector::vehicle_selector (const vehicle_selector & that) delete
vehicle_selector() [4/4]
vehicle_selector::vehicle_selector (vehicle_selector &&) default
Member Function Documentation
back() [1/2]
reference vehicle_selector::back () inline
Definition at line 97 of file vehicle_selector.h.
{
             return data.back();
         }
References data.
back() [2/2]
const_reference vehicle_selector::back () const inline
Definition at line 100 of file vehicle_selector.h.
{
             return data.back();
         }
References data.
begin() [1/2]
iterator vehicle_selector::begin () inline
Definition at line 73 of file vehicle_selector.h.
{
             return data.begin();
         }
References data.
begin() [2/2]
const_iterator vehicle_selector::begin () const inline
Definition at line 79 of file vehicle_selector.h.
{
             return data.cbegin();
         }
References data.
cbegin()
const_iterator vehicle_selector::cbegin () const inline
Definition at line 85 of file vehicle_selector.h.
{
             return data.cbegin();
         }
References data.
cend()
const_iterator vehicle_selector::cend () const inline
Definition at line 88 of file vehicle_selector.h.
{
             return data.cend();
         }
References data.
end() [1/2]
iterator vehicle_selector::end () inline
Definition at line 76 of file vehicle_selector.h.
{
             return data.end();
         }
References data.
end() [2/2]
const_iterator vehicle_selector::end () const inline
Definition at line 82 of file vehicle_selector.h.
{
             return data.cend();
         }
References data.
front() [1/2]
reference vehicle_selector::front () inline
Definition at line 91 of file vehicle_selector.h.
{
             return data.front();
         }
References data.
front() [2/2]
const_reference vehicle_selector::front () const inline
Definition at line 94 of file vehicle_selector.h.
{
             return data.front();
         }
References data.
has_quality()
bool vehicle_selector::has_quality (const quality_id & qual, int level = 1, int qty = 1) const override virtual
Returns true if instance has amount (or more) items of at least quality level.
Reimplemented from read_only_visitable.
max_quality()
int vehicle_selector::max_quality (const quality_id & qual) const override virtual
Return maximum tool quality level provided by instance or INT_MIN if not found.
Reimplemented from read_only_visitable.
Referenced by Character::best_nearby_lifting_assist(), and veh_interact::cache_tool_availability().
operator=()
vehicle_selector& vehicle_selector::operator= (const vehicle_selector &) delete
remove_items_with()
std::list<item> vehicle_selector::remove_items_with (const std::function< bool(const item &)> & filter, int count = INT_MAX) override virtual
Removes items contained by this instance which match the filter.
Note
: Implement for each class that will implement the visitable interface
if this instance itself is an item it will not be considered by the filter
Parameters
filter a UnaryPredicate which should return true if the item is to be removed
count maximum number of items to if unspecified unlimited. A count of zero is a no-op
Returns
any items removed (items counted by charges are not guaranteed to be stacked)
Implements visitable.
size()
size_type vehicle_selector::size () const inline
Definition at line 70 of file vehicle_selector.h.
{
             return data.size();
         }
References data.
visit_items()
VisitResponse vehicle_selector::visit_items (const std::function< VisitResponse(item *, item *)> & func) const override virtual
Traverses this object and any child items contained using a visitor pattern.
Note
Implement for each class that will implement the visitable interface. Other visit_items variants rely on this function.
Parameters
func visitor function called for each node which controls whether traversal continues. The first argument is the node and the second is the parent node (if any) The visitor function should return VisitResponse::Next to recursively process child items, VisitResponse::Skip to ignore children of the current node or VisitResponse::Abort to skip all remaining nodes
Returns
This method itself only ever returns VisitResponse::Next or VisitResponse::Abort.
Implements read_only_visitable.
Member Data Documentation
data
std::vector<value_type> vehicle_selector::data private
Definition at line 113 of file vehicle_selector.h.
Referenced by back(), begin(), cbegin(), cend(), end(), front(), size(), and vehicle_selector().
The documentation for this class was generated from the following files:
src/vehicle_selector.h
src/vehicle_selector.cpp