Cataclysm DDA: unload_loot_activity_actor Class Reference
unload_loot_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
unload_loot_activity_actor ()=default
unload_loot_activity_actor (int moves)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &you) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves
int num_processed
int stage
std::unordered_set< tripoint > coord_set
tripoint placement
Detailed Description
Definition at line 2100 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
unload_loot_activity_actor() [1/2]
unload_loot_activity_actor::unload_loot_activity_actor () default
unload_loot_activity_actor() [2/2]
unload_loot_activity_actor::unload_loot_activity_actor (int moves) inline explicit
Definition at line 2104 of file activity_actor_definitions.h.
 : moves( moves ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> unload_loot_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 2114 of file activity_actor_definitions.h.
{
             return std::make_unique<unload_loot_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > unload_loot_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6975 of file activity_actor.cpp.
 {
     unload_loot_activity_actor actor( {} );
     JsonObject data = jsin.get_object();
     data.read( "moves", actor.moves );
     data.read( "num_processed", actor.num_processed );
     data.read( "stage", actor.stage );
     data.read( "coord_set", actor.coord_set );
     data.read( "placement", actor.placement );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void unload_loot_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 7039 of file activity_actor.cpp.
 {
     enum activity_stage : int {
         //Initial stage
         INIT = 0,
         //Think about what to do first: choose destination
         THINK,
         //Do activity
         DO,
     };
     faction const *fac = you.get_faction();
     faction_id fac_id = fac == nullptr ? faction_id() : fac->id;
     map &here = get_map();
     const tripoint_abs_ms abspos = you.get_location();
     zone_manager &mgr = zone_manager::get_manager();
     if( here.check_vehicle_zones( here.get_abs_sub().z() ) ) {
         mgr.cache_vzones();
     }
     if( stage == INIT ) {
         // TODO: fix point types
         coord_set.clear();
         for( const tripoint_abs_ms &p :
              mgr.get_near( zone_type_UNLOAD_ALL, abspos, ACTIVITY_SEARCH_DISTANCE, nullptr,
                            fac_id ) ) {
             coord_set.insert( p.raw() );
         }
         for( const tripoint_abs_ms &p :
              mgr.get_near( zone_type_STRIP_CORPSES, abspos, ACTIVITY_SEARCH_DISTANCE, nullptr,
                            fac_id ) ) {
             coord_set.insert( p.raw() );
         }
         stage = THINK;
     }
     if( stage == THINK ) {
         //initialize num_processed
         num_processed = 0;
         // TODO: fix point types
         std::vector<tripoint_abs_ms> src_set;
         src_set.reserve( coord_set.size() );
         for( const tripoint &p : coord_set ) {
             src_set.emplace_back( p );
         }
         // sort source tiles by distance
         const auto &src_sorted = get_sorted_tiles_by_distance( abspos, src_set );
         for( const tripoint_abs_ms &src : src_sorted ) {
             // TODO: fix point types
             placement = src.raw();
             coord_set.erase( src.raw() );
             const tripoint_bub_ms &src_loc = here.bub_from_abs( src );
             if( !here.inbounds( src_loc ) ) {
                 if( !here.inbounds( you.pos() ) ) {
                     // p is implicitly an NPC that has been moved off the map, so reset the activity
                     // and unload them
                     you.cancel_activity();
                     you.assign_activity( ACT_UNLOAD_LOOT );
                     you.set_moves( 0 );
                     g->reload_npcs();
                     return;
                 }
                 std::vector<tripoint_bub_ms> route;
                 route = here.route( you.pos_bub(), src_loc, you.get_pathfinding_settings(),
                                     you.get_path_avoid() );
                 if( route.empty() ) {
                     // can't get there, can't do anything, skip it
                     continue;
                 }
                 stage = DO;
                 you.set_destination( route, act );
                 you.activity.set_to_null();
                 return;
             }
             // skip tiles in IGNORE zone and tiles on fire
             // (to prevent taking out wood off the lit brazier)
             // and inaccessible furniture, like filled charcoal kiln
             if( mgr.has( zone_type_LOOT_IGNORE, src, fac_id ) ||
                 here.get_field( src_loc, fd_fire ) != nullptr ||
                 !here.can_put_items_ter_furn( src_loc ) ) {
                 continue;
             }
             //nothing to sort?
             const std::optional<vpart_reference> ovp = here.veh_at( src_loc ).cargo();
             if( ( !ovp || ovp->items().empty() ) && here.i_at( src_loc ).empty() ) {
                 continue;
             }
             bool is_adjacent_or_closer = square_dist( you.pos_bub(), src_loc ) <= 1;
             // before we unload any item, check if player is at or
             // adjacent to the loot source tile
             if( !is_adjacent_or_closer ) {
                 std::vector<tripoint_bub_ms> route;
                 bool adjacent = false;
                 // get either direct route or route to nearest adjacent tile if
                 // source tile is impassable
                 if( here.passable( src_loc ) ) {
                     route = here.route( you.pos_bub(), src_loc, you.get_pathfinding_settings(),
                                         you.get_path_avoid() );
                 } else {
                     // impassable source tile (locker etc.),
                     // get route to nearest adjacent tile instead
                     route = route_adjacent( you, src_loc );
                     adjacent = true;
                 }
                 // check if we found path to source / adjacent tile
                 if( route.empty() ) {
                     add_msg( m_info, _( "%s can't reach the source tile." ),
                              you.disp_name() );
                     continue;
                 }
                 // shorten the route to adjacent tile, if necessary
                 if( !adjacent ) {
                     route.pop_back();
                 }
                 // set the destination and restart activity after player arrives there
                 // we don't need to check for safe mode,
                 // activity will be restarted only if
                 // player arrives on destination tile
                 stage = DO;
                 you.set_destination( route, act );
                 you.activity.set_to_null();
                 return;
             }
             stage = DO;
             break;
         }
     }
     if( stage == DO ) {
         // TODO: fix point types
         const tripoint_abs_ms src( placement );
         const tripoint_bub_ms src_loc = here.bub_from_abs( src );
         bool is_adjacent_or_closer = square_dist( you.pos_bub(), src_loc ) <= 1;
         // before we move any item, check if player is at or
         // adjacent to the loot source tile
         if( !is_adjacent_or_closer ) {
             stage = THINK;
             return;
         }
         // the boolean in this pair being true indicates the item is from a vehicle storage space
         auto items = std::vector<std::pair<item *, bool>>();
         vehicle *src_veh;
         int src_part;
         //Check source for cargo part
         //map_stack and vehicle_stack are different types but inherit from item_stack
         // TODO: use one for loop
         if( const std::optional<vpart_reference> ovp = here.veh_at( src_loc ).cargo() ) {
             src_veh = &ovp->vehicle();
             src_part = ovp->part_index();
             for( item &it : ovp->items() ) {
                 items.emplace_back( &it, true );
             }
         } else {
             src_veh = nullptr;
             src_part = -1;
         }
         for( item &it : here.i_at( src_loc ) ) {
             items.emplace_back( &it, false );
         }
         bool unload_mods = false;
         bool unload_molle = false;
         bool unload_sparse_only = false;
         int unload_sparse_threshold = 20;
         std::vector<zone_data const *> const zones = mgr.get_zones_at( src, zone_type_UNLOAD_ALL,
                 fac_id );
         // get most open rules out of all stacked zones
         for( zone_data const *zone : zones ) {
             unload_options const &options = dynamic_cast<const unload_options &>( zone->get_options() );
             unload_molle |= options.unload_molle();
             unload_mods |= options.unload_mods();
             unload_sparse_only |= options.unload_sparse_only();
             unload_sparse_threshold |= options.unload_sparse_threshold();
         }
         //Skip items that have already been processed
         for( auto it = items.begin() + num_processed; it < items.end(); ++it ) {
             item &thisitem = *it->first;
             // skip unpickable liquid
             if( thisitem.made_of_from_type( phase_id::LIQUID ) ) {
                 ++num_processed;
                 continue;
             }
             // skip favorite items in ignore favorite zones
             if( thisitem.is_favorite && mgr.has( zone_type_LOOT_IGNORE_FAVORITES, src, fac_id ) ) {
                 ++num_processed;
                 continue;
             }
             // Only if it's from a vehicle do we use the vehicle source location information.
             vehicle *this_veh = it->second ? src_veh : nullptr;
             const int this_part = it->second ? src_part : -1;
             // if this item isn't going anywhere and its not sealed
             // check if it is in a unload zone or a strip corpse zone
             // then we should unload it and see what is inside
             if( mgr.has_near( zone_type_UNLOAD_ALL, abspos, 1, fac_id ) ||
                 ( mgr.has_near( zone_type_STRIP_CORPSES, abspos, 1, fac_id ) && it->first->is_corpse() ) ) {
                 if( you.rate_action_unload( *it->first ) == hint_rating::good &&
                     !it->first->any_pockets_sealed() ) {
                     std::unordered_map<itype_id, int> item_counts;
                     if( unload_sparse_only ) {
                         for( item *contained : it->first->all_items_top( pocket_type::CONTAINER ) ) {
                             if( !contained->made_of( phase_id::LIQUID ) && !contained->made_of( phase_id::GAS ) ) {
                                 item_counts[contained->typeId()]++;
                             }
                         }
                     }
                     for( item *contained : it->first->all_items_top( pocket_type::CONTAINER ) ) {
                         // no liquids don't want to spill stuff
                         if( !contained->made_of( phase_id::LIQUID ) && !contained->made_of( phase_id::GAS ) ) {
                             if( unload_sparse_only &&
                                 item_counts[contained->typeId()] > unload_sparse_threshold ) {
                                 continue;
                             }
                             move_item( you, *contained, contained->count(), src_loc, src_loc, this_veh, this_part );
                             it->first->remove_item( *contained );
                         }
                         if( you.get_moves() <= 0 ) {
                             return;
                         }
                     }
                     for( item *contained : it->first->all_items_top( pocket_type::MAGAZINE ) ) {
                         // no liquids don't want to spill stuff
                         if( !contained->made_of( phase_id::LIQUID ) && !contained->made_of( phase_id::GAS ) ) {
                             if( it->first->is_ammo_belt() ) {
                                 if( it->first->type->magazine->linkage ) {
                                     item link( *it->first->type->magazine->linkage, calendar::turn, contained->count() );
                                     if( this_veh != nullptr ) {
                                         vehicle_part &vp_this = this_veh->part( this_part );
                                         this_veh->add_item( vp_this, link );
                                     } else {
                                         here.add_item_or_charges( src_loc, link );
                                     }
                                 }
                             }
                             move_item( you, *contained, contained->count(), src_loc, src_loc, this_veh, this_part );
                             it->first->remove_item( *contained );
                             if( it->first->has_flag( flag_MAG_DESTROY ) && it->first->ammo_remaining() == 0 ) {
                                 if( this_veh != nullptr ) {
                                     vehicle_part &vp_this = this_veh->part( this_part );
                                     this_veh->remove_item( vp_this, it->first );
                                 } else {
                                     here.i_rem( src_loc, it->first );
                                 }
                             }
                         }
                         if( you.get_moves() <= 0 ) {
                             return;
                         }
                     }
                     for( item *contained : it->first->all_items_top( pocket_type::MAGAZINE_WELL ) ) {
                         // no liquids don't want to spill stuff
                         if( !contained->made_of( phase_id::LIQUID ) && !contained->made_of( phase_id::GAS ) ) {
                             move_item( you, *contained, contained->count(), src_loc, src_loc, this_veh, this_part );
                             it->first->remove_item( *contained );
                         }
                         if( you.get_moves() <= 0 ) {
                             return;
                         }
                     }
                 }
                 // if unloading mods
                 if( unload_mods ) {
                     // remove each mod, skip irremovable
                     for( item *mod : it->first->gunmods() ) {
                         if( mod->is_irremovable() ) {
                             continue;
                         }
                         you.gunmod_remove( *it->first, *mod );
                         if( you.get_moves() <= 0 ) {
                             return;
                         }
                     }
                 }
                 // if unloading molle
                 if( unload_molle ) {
                     while( !it->first->get_contents().get_added_pockets().empty() ) {
                         item removed = it->first->get_contents().remove_pocket( 0 );
                         move_item( you, removed, 1, src_loc, src_loc, this_veh, this_part );
                         if( you.get_moves() <= 0 ) {
                             return;
                         }
                     }
                 }
                 // after dumping items go back to start of activity loop
                 // so that can re-assess the items in the tile
                 ++num_processed;
                 return;
             }
             if( you.get_moves() <= 0 ) {
                 return;
             }
         }
         //this location is sorted
         stage = THINK;
         return;
     }
     // If we got here without restarting the activity, it means we're done
     add_msg( m_info, _( "%s sorted out every item possible." ), you.disp_name( false, true ) );
     if( you.is_npc() ) {
         npc *guy = dynamic_cast<npc *>( &you );
         guy->revert_after_activity();
     }
     act.set_to_null();
 }
References _, act, ACT_UNLOAD_LOOT, Character::activity, ACTIVITY_SEARCH_DISTANCE, vehicle::add_item(), map::add_item_or_charges(), add_msg(), item::all_items_top(), Character::assign_activity(), map::bub_from_abs(), zone_manager::cache_vzones(), map::can_put_items_ter_furn(), Character::cancel_activity(), optional_vpart_position::cargo(), map::check_vehicle_zones(), CONTAINER, coord_set, Character::disp_name(), item_stack::empty(), faction_id, fd_fire, flag_MAG_DESTROY, g, GAS, map::get_abs_sub(), item::get_contents(), Character::get_faction(), map::get_field(), Creature::get_location(), zone_manager::get_manager(), get_map(), Creature::get_moves(), zone_manager::get_near(), Character::get_path_avoid(), Character::get_pathfinding_settings(), get_sorted_tiles_by_distance(), zone_manager::get_zones_at(), good, Character::gunmod_remove(), zone_manager::has(), zone_manager::has_near(), map::i_at(), map::i_rem(), faction_template::id, map::inbounds(), INIT, item::is_favorite, Character::is_npc(), LIQUID, m_info, item::made_of_from_type(), MAGAZINE, MAGAZINE_WELL, move_item(), num_processed, PATH_INFO::options(), vehicle::part(), map::passable(), placement, Creature::pos(), Creature::pos_bub(), Character::rate_action_unload(), vehicle::remove_item(), item_contents::remove_pocket(), npc::revert_after_activity(), map::route(), route_adjacent(), Character::set_destination(), Creature::set_moves(), player_activity::set_to_null(), square_dist(), stage, calendar::turn, map::veh_at(), vehicle::vehicle(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), zone_type_LOOT_IGNORE, zone_type_LOOT_IGNORE_FAVORITES, zone_type_STRIP_CORPSES, zone_type_UNLOAD_ALL, and zones.
finish()
void unload_loot_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 2112 of file activity_actor_definitions.h.
 {};
get_type()
activity_id unload_loot_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 2106 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_UNLOAD_LOOT" );
         }
References activity_id.
serialize()
void unload_loot_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6962 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves", moves );
     jsout.member( "num_processed", num_processed );
     jsout.member( "stage", stage );
     jsout.member( "coord_set", coord_set );
     jsout.member( "placement", placement );
     jsout.end_object();
 }
References coord_set, JsonOut::end_object(), JsonOut::member(), moves, num_processed, placement, stage, and JsonOut::start_object().
start()
void unload_loot_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 6990 of file activity_actor.cpp.
 {
     act.moves_total = moves;
     act.moves_left = moves;
 }
References act, and moves.
Member Data Documentation
coord_set
std::unordered_set<tripoint> unload_loot_activity_actor::coord_set private
Definition at line 2125 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
moves
int unload_loot_activity_actor::moves private
Definition at line 2122 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
num_processed
int unload_loot_activity_actor::num_processed private
Definition at line 2123 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
placement
tripoint unload_loot_activity_actor::placement private
Definition at line 2126 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
stage
int unload_loot_activity_actor::stage private
Definition at line 2124 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp