Cataclysm DDA: talker_npc Class Reference
talker_npc Class Reference
#include <talker_npc.h>
Public Member Functions
talker_npc (npc *new_me)
~talker_npc () override=default
npc * get_npc () override
npc * get_npc () const override
std::string distance_to_goal () const override
bool will_talk_to_u (const Character &you, bool force) override
std::vector< std::string > get_topics (bool radio_contact) override
void check_missions () override
void update_missions (const std::vector< mission * > &missions_assigned) override
bool check_hostile_response (int anger) const override
int parse_mod (const std::string &attribute, int factor) const override
int trial_chance_mod (const std::string &trial_type) const override
void store_chosen_training (const skill_id &c_skill, const matype_id &c_style, const spell_id &c_spell, const proficiency_id &c_proficiency) override
int debt () const override
void add_debt (int cost) override
int sold () const override
void add_sold (int value) override
int cash_to_favor (int value) const override
std::string give_item_to (bool to_use) override
bool buy_from (int amount) override
int value (const item &it) const override
std::vector< mission * > available_missions () const override
std::vector< mission * > assigned_missions () const override
mission * selected_mission () const override
void select_mission (mission *selected) override
void add_mission (const mission_type_id &mission_id) override
void set_companion_mission (const std::string &role_id) override
void set_fac (const faction_id &new_fac_name) override
void add_faction_rep (int rep_change) override
bool is_following () const override
bool is_friendly (const Character &guy) const override
bool is_enemy () const override
bool is_player_ally () const override
bool turned_hostile () const override
void make_angry () override
bool has_ai_rule (const std::string &type, const std::string &rule) const override
void toggle_ai_rule (const std::string &type, const std::string &rule) override
void set_ai_rule (const std::string &type, const std::string &rule) override
void clear_ai_rule (const std::string &type, const std::string &rule) override
std::string get_job_description () const override
std::string view_personality_traits () const override
std::string evaluation_by (const talker &alpha) const override
bool has_activity () const override
bool is_myclass (const npc_class_id &class_to_check) const override
void set_class (const npc_class_id &new_class) override
void say (const std::string &speech) override
std::string opinion_text () const override
void add_opinion (const npc_opinion &op) override
bool enslave_mind () override
void set_first_topic (const std::string &chat_topic) override
bool is_safe () const override
void die () override
void set_npc_trust (int trust) override
int get_npc_trust () const override
void set_npc_fear (int fear) override
int get_npc_fear () const override
void set_npc_value (int value) override
int get_npc_value () const override
void set_npc_anger (int anger) override
int get_npc_anger () const override
Public Member Functions inherited from talker_cloner< talker_npc, talker_character >
std::unique_ptr< talker > clone () const override
Public Member Functions inherited from talker_character
talker_character (Character *new_me)
~talker_character () override=default
Character * get_character () override
const Character * get_character () const override
Creature * get_creature () override
const Creature * get_creature () const override
void set_pos (tripoint new_pos) override
void set_str_max (int value) override
void set_dex_max (int value) override
void set_int_max (int value) override
void set_per_max (int value) override
void set_str_bonus (int value) override
void set_dex_bonus (int value) override
void set_int_bonus (int value) override
void set_per_bonus (int value) override
void set_power_cur (units::energy value) override
void set_mana_cur (int value) override
void set_spell_level (const spell_id &, int) override
void set_spell_exp (const spell_id &, int) override
void set_proficiency_practiced_time (const proficiency_id &prof, int turns) override
void train_proficiency_for (const proficiency_id &prof, int turns) override
void mutate (const int &highest_cat_chance, const bool &use_vitamins) override
void mutate_category (const mutation_category_id &mut_cat, const bool &use_vitamins) override
void mutate_towards (const trait_id &trait, const mutation_category_id &mut_cat, const bool &use_vitamins) override
void set_mutation (const trait_id &new_trait, const mutation_variant *=nullptr) override
void unset_mutation (const trait_id &old_trait) override
void activate_mutation (const trait_id &trait) override
void deactivate_mutation (const trait_id &trait) override
void set_skill_level (const skill_id &skill, int value) override
void set_skill_exp (const skill_id &skill, int value, bool raw=false) override
void learn_recipe (const recipe_id &recipe_to_learn) override
void forget_recipe (const recipe_id &recipe_to_forget) override
void add_effect (const efftype_id &new_effect, const time_duration &dur, const std::string &bp, bool permanent, bool force, int intensity) override
void remove_effect (const efftype_id &old_effect, const std::string &bp) override
void set_value (const std::string &var_name, const std::string &value) override
void remove_value (const std::string &var_name) override
std::vector< item * > items_with (const std::function< bool(const item &)> &filter) const override
std::list< item > use_charges (const itype_id &item_name, int count) override
std::list< item > use_charges (const itype_id &item_name, int count, bool in_tools) override
std::list< item > use_amount (const itype_id &item_name, int count) override
void i_add (const item &new_item) override
void i_add_or_drop (item &new_item, bool force_equip=false) override
void remove_items_with (const std::function< bool(const item &)> &filter) override
void set_stored_kcal (int value) override
void set_thirst (int value) override
void shout (const std::string &speech="", bool order=false) override
void set_sleepiness (int amount) override
void mod_pain (int amount) override
void set_pain (int amount) override
void mod_daily_health (int, int) override
void add_morale (const morale_type &new_morale, int bonus, int max_bonus, time_duration duration, time_duration decay_started, bool capped) override
void remove_morale (const morale_type &old_morale) override
void set_addiction_turns (const addiction_id &add_id, int amount) override
void mod_focus (int) override
void set_rad (int) override
void set_stim (int) override
void set_pkill (int) override
void set_stamina (int) override
void set_sleep_deprivation (int) override
void set_kill_xp (int) override
void set_age (int) override
void set_height (int) override
void add_bionic (const bionic_id &new_bionic) override
void remove_bionic (const bionic_id &old_bionic) override
std::vector< bodypart_id > get_all_body_parts (get_body_part_flags flags) const override
int get_part_hp_cur (const bodypart_id &id) const override
int get_part_hp_max (const bodypart_id &id) const override
void set_all_parts_hp_cur (int) const override
void set_part_hp_cur (const bodypart_id &id, int set) const override
bool get_is_alive () const override
void attack_target (Creature &t, bool allow_special, const matec_id &force_technique, bool allow_unarmed, int forced_movecost) override
matec_id get_random_technique (Creature &t, bool crit, bool dodge_counter, bool block_counter, const std::vector< matec_id > &blacklist={}) const override
void learn_martial_art (const matype_id &id) const override
void forget_martial_art (const matype_id &id) const override
Public Member Functions inherited from talker_character_const
talker_character_const (const Character *new_me)
~talker_character_const () override=default
std::string disp_name () const override
std::string get_name () const override
character_id getID () const override
bool is_male () const override
std::vector< std::string > get_grammatical_genders () const override
int posx () const override
int posy () const override
int posz () const override
tripoint pos () const override
tripoint_abs_ms global_pos () const override
tripoint_abs_omt global_omt_location () const override
int get_cur_hp (const bodypart_id &bp) const override
int get_hp_max (const bodypart_id &bp) const override
units::temperature get_cur_part_temp (const bodypart_id &bp) const override
int str_cur () const override
int dex_cur () const override
int int_cur () const override
int per_cur () const override
int attack_speed () const override
int pain_cur () const override
int perceived_pain_cur () const override
double armor_at (damage_type_id &dt, bodypart_id &bp) const override
int coverage_at (bodypart_id &) const override
int encumbrance_at (bodypart_id &) const override
int get_str_max () const override
int get_dex_max () const override
int get_int_max () const override
int get_per_max () const override
int get_str_bonus () const override
int get_dex_bonus () const override
int get_int_bonus () const override
int get_per_bonus () const override
units::energy power_cur () const override
units::energy power_max () const override
int mana_cur () const override
int mana_max () const override
bool has_trait (const trait_id &trait_to_check) const override
bool has_recipe (const recipe_id &recipe_to_check) const override
bool has_flag (const json_character_flag &trait_flag_to_check) const override
bool has_species (const species_id &species) const override
bool bodytype (const bodytype_id &bt) const override
bool crossed_threshold () const override
int num_bionics () const override
bool has_max_power () const override
bool has_bionic (const bionic_id &bionics_id) const override
bool knows_spell (const spell_id &sp) const override
int get_skill_level (const skill_id &) const override
int get_skill_exp (const skill_id &skill, bool raw=false) const override
int get_spell_level (const trait_id &) const override
int get_spell_level (const spell_id &) const override
int get_spell_exp (const spell_id &) const override
int get_highest_spell_level () const override
int get_spell_count (const trait_id &) const override
int get_spell_sum (const trait_id &school, int min_level) const override
bool knows_proficiency (const proficiency_id &proficiency) const override
time_duration proficiency_practiced_time (const proficiency_id &) const override
bool has_effect (const efftype_id &effect_id, const bodypart_id &bp) const override
effect get_effect (const efftype_id &effect_id, const bodypart_id &bp) const override
bool is_deaf () const override
bool is_mute () const override
std::optional< std::string > maybe_get_value (const std::string &var_name) const override
std::vector< skill_id > skills_teacheable () const override
std::vector< skill_id > skills_offered_to (const talker &student) const override
std::string skill_seminar_text (const skill_id &s) const override
std::string skill_training_text (const talker &, const skill_id &) const override
std::vector< proficiency_id > proficiencies_teacheable () const override
std::vector< proficiency_id > proficiencies_offered_to (const talker &student) const override
std::string proficiency_seminar_text (const proficiency_id &) const override
std::string proficiency_training_text (const talker &student, const proficiency_id &proficiency) const override
std::vector< matype_id > styles_teacheable () const override
std::vector< matype_id > styles_offered_to (const talker &student) const override
std::string style_seminar_text (const matype_id &) const override
std::string style_training_text (const talker &, const matype_id &) const override
std::vector< spell_id > spells_teacheable () const override
std::vector< spell_id > spells_offered_to (talker &student) const override
std::string spell_seminar_text (const spell_id &) const override
std::string spell_training_text (talker &, const spell_id &) const override
bool is_wearing (const itype_id &item_id) const override
int charges_of (const itype_id &item_id) const override
bool has_charges (const itype_id &item_id, int count) const override
bool has_charges (const itype_id &item_id, int count, bool in_tools) const override
bool has_amount (const itype_id &item_id, int count) const override
int get_amount (const itype_id &item_id) const override
int cash () const override
std::vector< const item * > const_items_with (const std::function< bool(const item &)> &filter) const override
bool unarmed_attack () const override
bool can_stash_weapon () const override
bool has_stolen_item (const talker &guy) const override
faction * get_faction () const override
std::string short_description () const override
bool is_mounted () const override
int get_activity_level () const override
int get_sleepiness () const override
int get_hunger () const override
int get_thirst () const override
int get_instant_thirst () const override
int get_stored_kcal () const override
int get_healthy_kcal () const override
int get_size () const override
bool is_in_control_of (const vehicle &veh) const override
bool worn_with_flag (const flag_id &flag, const bodypart_id &bp) const override
bool wielded_with_flag (const flag_id &flag) const override
bool wielded_with_weapon_category (const weapon_category_id &w_cat) const override
bool has_item_with_flag (const flag_id &flag) const override
int item_rads (const flag_id &flag, aggregate_type agg_func) const override
bool can_see () const override
bool can_see_location (const tripoint &pos) const override
int morale_cur () const override
int focus_cur () const override
int get_rad () const override
int get_stim () const override
int get_addiction_intensity (const addiction_id &add_id) const override
int get_addiction_turns (const addiction_id &add_id) const override
int get_pkill () const override
int get_stamina () const override
int get_sleep_deprivation () const override
int get_kill_xp () const override
int get_age () const override
int get_height () const override
int get_bmi_permil () const override
int get_weight () const override
const move_mode_id & get_move_mode () const override
int get_fine_detail_vision_mod () const override
int get_health () const override
units::temperature get_body_temp () const override
units::temperature_delta get_body_temp_delta () const override
bool knows_martial_art (const matype_id &id) const override
bool using_martial_art (const matype_id &id) const override
int climate_control_str_heat () const override
int climate_control_str_chill () const override
Public Member Functions inherited from talker
virtual ~talker ()=default
virtual item_location * get_item ()
virtual item_location * get_item () const
virtual monster * get_monster ()
virtual const monster * get_monster () const
virtual computer * get_computer ()
virtual const computer * get_computer () const
virtual int get_count () const
virtual int get_grab_strength () const
virtual std::string get_value (const std::string &key) const
virtual bool buy_monster (talker &, const mtype_id &, int, int, bool, const translation &)
virtual int get_anger () const
virtual void set_anger (int)
virtual void set_morale (int)
virtual int get_friendly () const
virtual void set_friendly (int)
virtual int get_volume () const
Protected Attributes
npc * me_npc
Protected Attributes inherited from talker_character
Character * me_chr
Protected Attributes inherited from talker_character_const
const Character * me_chr_const
Additional Inherited Members
Protected Member Functions inherited from talker_character
talker_character ()=default
Protected Member Functions inherited from talker_character_const
talker_character_const ()=default
Detailed Description
Definition at line 20 of file talker_npc.h.
Constructor & Destructor Documentation
talker_npc()
talker_npc::talker_npc (npc * new_me) explicit
Definition at line 61 of file talker_npc.cpp.
 {
     me_npc = new_me;
     me_chr = new_me;
     me_chr_const = new_me;
 }
References talker_character::me_chr, talker_character_const::me_chr_const, and me_npc.
~talker_npc()
talker_npc::~talker_npc () override default
Member Function Documentation
add_debt()
void talker_npc::add_debt (int cost) override virtual
Reimplemented from talker.
Definition at line 301 of file talker_npc.cpp.
 {
     me_npc->op_of_u.owed += cost;
 }
References me_npc, npc::op_of_u, and npc_opinion::owed.
add_faction_rep()
void talker_npc::add_faction_rep (int rep_change) override virtual
Reimplemented from talker.
Definition at line 563 of file talker_npc.cpp.
 {
     if( me_npc->get_faction()-> id != faction_no_faction ) {
         me_npc->get_faction()->likes_u += rep_change;
         me_npc->get_faction()->respects_u += rep_change;
         me_npc->get_faction()->trusts_u += rep_change;
     }
 }
References faction_no_faction, npc::get_faction(), faction_template::likes_u, me_npc, faction_template::respects_u, and faction_template::trusts_u.
add_mission()
void talker_npc::add_mission (const mission_type_id & mission_id) override virtual
Reimplemented from talker.
Definition at line 545 of file talker_npc.cpp.
 {
     mission *miss = mission::reserve_new( mission_id, me_npc->getID() );
     miss->assign( get_avatar() );
     me_npc->chatbin.missions_assigned.push_back( miss );
 }
References mission::assign(), npc::chatbin, get_avatar(), Character::getID(), me_npc, dialogue_chatbin::missions_assigned, and mission::reserve_new().
add_opinion()
void talker_npc::add_opinion (const npc_opinion & op) override virtual
Reimplemented from talker.
Definition at line 841 of file talker_npc.cpp.
 {
     me_npc->op_of_u += op;
 }
References me_npc, and npc::op_of_u.
add_sold()
void talker_npc::add_sold (int value) override virtual
Reimplemented from talker.
Definition at line 311 of file talker_npc.cpp.
 {
     me_npc->op_of_u.sold += value;
 }
References me_npc, npc::op_of_u, npc_opinion::sold, and value().
assigned_missions()
std::vector< mission * > talker_npc::assigned_missions () const override virtual
Reimplemented from talker.
Definition at line 530 of file talker_npc.cpp.
 {
     return me_npc->chatbin.missions_assigned;
 }
References npc::chatbin, me_npc, and dialogue_chatbin::missions_assigned.
available_missions()
std::vector< mission * > talker_npc::available_missions () const override virtual
Reimplemented from talker.
Definition at line 525 of file talker_npc.cpp.
 {
     return me_npc->chatbin.missions;
 }
References npc::chatbin, me_npc, and dialogue_chatbin::missions.
buy_from()
bool talker_npc::buy_from (int amount) override virtual
Reimplemented from talker.
Definition at line 520 of file talker_npc.cpp.
 {
     return npc_trading::pay_npc( *me_npc, amount );
 }
References me_npc, and npc_trading::pay_npc().
cash_to_favor()
int talker_npc::cash_to_favor (int value) const override virtual
Reimplemented from talker.
Definition at line 316 of file talker_npc.cpp.
 {
     return npc_trading::cash_to_favor( *me_npc, value );
 }
References npc_trading::cash_to_favor(), me_npc, and value().
check_hostile_response()
bool talker_npc::check_hostile_response (int anger) const override virtual
Reimplemented from talker.
Definition at line 234 of file talker_npc.cpp.
 {
     return me_npc->op_of_u.anger + anger > me_npc->hostile_anger_level();
 }
References npc_opinion::anger, npc::hostile_anger_level(), me_npc, and npc::op_of_u.
check_missions()
void talker_npc::check_missions () override virtual
Reimplemented from talker.
Definition at line 217 of file talker_npc.cpp.
 {
     me_npc->chatbin.check_missions();
 }
References npc::chatbin, dialogue_chatbin::check_missions(), and me_npc.
clear_ai_rule()
void talker_npc::clear_ai_rule (const std::string & type, const std::string & rule) override virtual
Reimplemented from talker.
Definition at line 691 of file talker_npc.cpp.
 {
     auto toggle = ally_rule_strs.find( rule );
     if( toggle == ally_rule_strs.end() ) {
         return;
     }
     me_npc->rules.clear_flag( toggle->second.rule );
     me_npc->invalidate_range_cache();
     me_npc->wield_better_weapon();
 }
References ally_rule_strs, npc_follower_rules::clear_flag(), npc::invalidate_range_cache(), me_npc, npc::rules, and npc::wield_better_weapon().
debt()
int talker_npc::debt () const override virtual
Reimplemented from talker.
Definition at line 296 of file talker_npc.cpp.
 {
     return me_npc->op_of_u.owed;
 }
References me_npc, npc::op_of_u, and npc_opinion::owed.
die()
void talker_npc::die () override virtual
Reimplemented from talker_character.
Definition at line 864 of file talker_npc.cpp.
 {
     me_npc->die( nullptr );
     const shared_ptr_fast<npc> guy = overmap_buffer.find_npc( me_npc->getID() );
     if( guy && !guy->is_dead() ) {
         guy->marked_for_death = true;
     }
 }
References npc::die(), overmapbuffer::find_npc(), Character::getID(), me_npc, and overmap_buffer.
distance_to_goal()
std::string talker_npc::distance_to_goal () const override virtual
Reimplemented from talker.
Definition at line 68 of file talker_npc.cpp.
 {
     // TODO: this ignores the z-component
     int dist = rl_dist( me_npc->global_omt_location(), me_npc->goal );
     std::string response;
     dist *= 100;
     if( dist >= 1300 ) {
         int miles = dist / 25; // *100, e.g. quarter mile is "25"
         miles -= miles % 25; // Round to nearest quarter-mile
         int fullmiles = ( miles - miles % 100 ) / 100; // Left of the decimal point
         if( fullmiles < 0 ) {
             fullmiles = 0;
         }
         response = string_format( _( "%d.%d miles." ), fullmiles, miles );
     } else {
         response = string_format( n_gettext( "%d foot.", "%d feet.", dist ), dist );
     }
     return response;
 }
References _, Creature::global_omt_location(), npc::goal, me_npc, n_gettext, rl_dist(), and string_format().
enslave_mind()
bool talker_npc::enslave_mind () override virtual
Reimplemented from talker.
Definition at line 846 of file talker_npc.cpp.
 {
     bool not_following = g->get_follower_list().count( me_npc->getID() ) == 0;
     me_npc->companion_mission_role_id.clear();
     talk_function::follow( *me_npc );
     return not_following;
 }
References npc::companion_mission_role_id, talk_function::follow(), g, Character::getID(), and me_npc.
evaluation_by()
std::string talker_npc::evaluation_by (const talker & alpha) const override virtual
Perception affects whether player can size up NPCs Intelligence slightly affects whether player can size up NPCs
Reimplemented from talker.
Definition at line 735 of file talker_npc.cpp.
 {
     if( !alpha.can_see() ) {
         return _( "&You're blind and can't make anything out." );
     }
     ///\EFFECT_PER affects whether player can size up NPCs
     ///\EFFECT_INT slightly affects whether player can size up NPCs
     int ability = alpha.per_cur() * 3 + alpha.int_cur();
     if( ability <= 10 ) {
         return _( "&You can't make anything out." );
     }
     if( is_player_ally() || ability > 100 ) {
         ability = 100;
     }
     std::string info = "&";
     int str_range = static_cast<int>( 100 / ability );
     int str_min = static_cast<int>( me_npc->str_max / str_range ) * str_range;
     info += string_format( _( "Str %d - %d" ), str_min, str_min + str_range );
     if( ability >= 40 ) {
         int dex_range = static_cast<int>( 160 / ability );
         int dex_min = static_cast<int>( me_npc->dex_max / dex_range ) * dex_range;
         info += string_format( _( "  Dex %d - %d" ), dex_min, dex_min + dex_range );
     }
     if( ability >= 50 ) {
         int int_range = static_cast<int>( 200 / ability );
         int int_min = static_cast<int>( me_npc->int_max / int_range ) * int_range;
         info += string_format( _( "  Int %d - %d" ), int_min, int_min + int_range );
     }
     if( ability >= 60 ) {
         int per_range = static_cast<int>( 240 / ability );
         int per_min = static_cast<int>( me_npc->per_max / per_range ) * per_range;
         info += string_format( _( "  Per %d - %d" ), per_min, per_min + per_range );
     }
     needs_rates rates = me_npc->calc_needs_rates();
     if( ability >= 100 - ( get_sleepiness() / 10 ) ) {
         std::string how_tired;
         if( get_sleepiness() > sleepiness_levels::EXHAUSTED ) {
             how_tired = _( "Exhausted" );
         } else if( get_sleepiness() > sleepiness_levels::DEAD_TIRED ) {
             how_tired = _( "Dead tired" );
         } else if( get_sleepiness() > sleepiness_levels::TIRED ) {
             how_tired = _( "Tired" );
         } else {
             how_tired = _( "Not tired" );
             if( ability >= 100 ) {
                 time_duration sleep_at = 5_minutes * ( sleepiness_levels::TIRED -
                                                        get_sleepiness() ) / rates.sleepiness;
                 how_tired += _( ".  Will need sleep in " ) + to_string_approx( sleep_at );
             }
         }
         info += "\n" + how_tired;
     }
     if( ability >= 100 ) {
         if( get_thirst() < 100 ) {
             time_duration thirst_at = 5_minutes * ( 100 - get_thirst() ) / rates.thirst;
             if( thirst_at > 1_hours ) {
                 info += _( "\nWill need water in " ) + to_string_approx( thirst_at );
             }
         } else {
             info += _( "\nThirsty" );
         }
         if( get_hunger() < 100 ) {
             time_duration hunger_at = 5_minutes * ( 100 - get_hunger() ) / rates.hunger;
             if( hunger_at > 1_hours ) {
                 info += _( "\nWill need food in " ) + to_string_approx( hunger_at );
             }
         } else {
             info += _( "\nHungry" );
         }
     }
     return info;
 }
References _, Character::calc_needs_rates(), talker::can_see(), DEAD_TIRED, Character::dex_max, EXHAUSTED, talker_character_const::get_hunger(), talker_character_const::get_sleepiness(), talker_character_const::get_thirst(), needs_rates::hunger, talker::int_cur(), Character::int_max, is_player_ally(), me_npc, talker::per_cur(), Character::per_max, needs_rates::sleepiness, Character::str_max, string_format(), needs_rates::thirst, TIRED, and to_string_approx().
get_job_description()
std::string talker_npc::get_job_description () const override virtual
Reimplemented from talker.
Definition at line 702 of file talker_npc.cpp.
 {
     return me_npc->describe_mission();
 }
References npc::describe_mission(), and me_npc.
get_npc() [1/2]
npc* talker_npc::get_npc () const inline override virtual
Reimplemented from talker.
Definition at line 29 of file talker_npc.h.
{
             return me_npc;
         }
References me_npc.
get_npc() [2/2]
npc* talker_npc::get_npc () inline override virtual
Reimplemented from talker.
Definition at line 26 of file talker_npc.h.
{
             return me_npc;
         }
References me_npc.
get_npc_anger()
int talker_npc::get_npc_anger () const override virtual
Reimplemented from talker.
Definition at line 908 of file talker_npc.cpp.
 {
     return me_npc->op_of_u.anger;
 }
References npc_opinion::anger, me_npc, and npc::op_of_u.
get_npc_fear()
int talker_npc::get_npc_fear () const override virtual
Reimplemented from talker.
Definition at line 888 of file talker_npc.cpp.
 {
     return me_npc->op_of_u.fear;
 }
References npc_opinion::fear, me_npc, and npc::op_of_u.
get_npc_trust()
int talker_npc::get_npc_trust () const override virtual
Reimplemented from talker.
Definition at line 878 of file talker_npc.cpp.
 {
     return me_npc->op_of_u.trust;
 }
References me_npc, npc::op_of_u, and npc_opinion::trust.
get_npc_value()
int talker_npc::get_npc_value () const override virtual
Reimplemented from talker.
Definition at line 898 of file talker_npc.cpp.
 {
     return me_npc->op_of_u.value;
 }
References me_npc, npc::op_of_u, and npc_opinion::value.
get_topics()
std::vector< std::string > talker_npc::get_topics (bool radio_contact) override virtual
Reimplemented from talker.
Definition at line 114 of file talker_npc.cpp.
 {
     avatar &player_character = get_avatar();
     std::vector<std::string> add_topics;
     // For each active mission we have, let the mission know we talked to this NPC.
     for( mission *&mission : player_character.get_active_missions() ) {
         mission->on_talk_with_npc( me_npc->getID() );
     }
     add_topics.push_back( me_npc->chatbin.first_topic );
     if( radio_contact ) {
         add_topics.emplace_back( me_npc->chatbin.talk_radio );
     } else if( me_npc->is_leader() ) {
         add_topics.emplace_back( me_npc->chatbin.talk_leader );
     } else if( me_npc->is_player_ally() && ( me_npc->is_walking_with() || me_npc->has_activity() ) ) {
         add_topics.emplace_back( me_npc->chatbin.talk_friend );
     } else if( me_npc->get_attitude() == NPCATT_RECOVER_GOODS ) {
         add_topics.emplace_back( me_npc->chatbin.talk_stole_item );
     }
     int most_difficult_mission = 0;
     for( mission *&mission : me_npc->chatbin.missions ) {
         const mission_type &type = mission->get_type();
         if( type.urgent && type.difficulty > most_difficult_mission ) {
             add_topics.emplace_back( "TALK_MISSION_DESCRIBE_URGENT" );
             me_npc->chatbin.mission_selected = mission;
             most_difficult_mission = type.difficulty;
         }
     }
     most_difficult_mission = 0;
     bool chosen_urgent = false;
     for( mission *&mission : me_npc->chatbin.missions_assigned ) {
         if( mission->get_assigned_player_id() != player_character.getID() ) {
             // Not assigned to the player that is currently talking to the npc
             continue;
         }
         const mission_type &type = mission->get_type();
         if( ( type.urgent && !chosen_urgent ) || ( type.difficulty > most_difficult_mission &&
                 ( type.urgent || !chosen_urgent ) ) ) {
             chosen_urgent = type.urgent;
             add_topics.emplace_back( "TALK_MISSION_INQUIRE" );
             me_npc->chatbin.mission_selected = mission;
             most_difficult_mission = type.difficulty;
         }
     }
     // Needs
     if( me_npc->has_effect( effect_npc_suspend ) ) {
         add_topics.emplace_back( "TALK_REBOOT" );
     }
     if( me_npc->has_effect( effect_sleep ) || me_npc->has_effect( effect_lying_down ) ) {
         if( me_npc->has_effect( effect_narcosis ) ) {
             add_topics.emplace_back( "TALK_SEDATED" );
         } else {
             add_topics.emplace_back( me_npc->chatbin.talk_wake_up );
         }
     }
     if( add_topics.back() == "TALK_NONE" ) {
         add_topics.back() = me_npc->pick_talk_topic( player_character );
     }
     me_npc->mod_moves( -to_moves<int>( 1_seconds ) );
     if( player_character.is_deaf() ) {
         if( add_topics.back() == me_npc->chatbin.talk_mug ||
             add_topics.back() == me_npc->chatbin.talk_stranger_aggressive ) {
             me_npc->make_angry();
             add_topics.emplace_back( "TALK_DEAF_ANGRY" );
         } else {
             add_topics.emplace_back( "TALK_DEAF" );
         }
     }
     if( player_character.is_mute() ) {
         if( add_topics.back() == me_npc->chatbin.talk_mug ||
             add_topics.back() == me_npc->chatbin.talk_stranger_aggressive ) {
             me_npc->make_angry();
             add_topics.emplace_back( "TALK_MUTE_ANGRY" );
         } else {
             add_topics.emplace_back( "TALK_MUTE" );
         }
     }
     if( player_character.has_trait( trait_PROF_CHURL ) ) {
         if( add_topics.back() == me_npc->chatbin.talk_mug ||
             add_topics.back() == me_npc->chatbin.talk_stranger_aggressive ) {
             me_npc->make_angry();
             add_topics.emplace_back( "TALK_CHURL_ANGRY" );
         } else if( ( me_npc->op_of_u.trust >= 0 ) && ( me_npc->op_of_u.anger <= 0 ) &&
                    ( me_npc->int_cur >= 9 ) ) {
             add_topics.emplace_back( "TALK_CHURL_TRADE" );
         } else {
             add_topics.emplace_back( "TALK_CHURL" );
         }
     }
     if( me_npc->has_trait( trait_PROF_FOODP ) &&
         !( me_npc->is_wearing( itype_foodperson_mask_on ) ||
            me_npc->is_wearing( itype_foodperson_mask ) ) ) {
         add_topics.emplace_back( "TALK_NPC_NOFACE" );
     }
     me_npc->decide_needs();
     return add_topics;
 }
References npc_opinion::anger, npc::chatbin, npc::decide_needs(), effect_lying_down, effect_narcosis, effect_npc_suspend, effect_sleep, dialogue_chatbin::first_topic, avatar::get_active_missions(), mission::get_assigned_player_id(), npc::get_attitude(), get_avatar(), mission::get_type(), Character::getID(), npc::has_activity(), Creature::has_effect(), Character::has_trait(), Character::int_cur, Character::is_deaf(), npc::is_leader(), Character::is_mute(), npc::is_player_ally(), npc::is_walking_with(), Character::is_wearing(), itype_foodperson_mask, itype_foodperson_mask_on, npc::make_angry(), me_npc, dialogue_chatbin::mission_selected, dialogue_chatbin::missions, dialogue_chatbin::missions_assigned, Creature::mod_moves(), NPCATT_RECOVER_GOODS, mission::on_talk_with_npc(), npc::op_of_u, npc::pick_talk_topic(), dialogue_chatbin::talk_friend, dialogue_chatbin::talk_leader, dialogue_chatbin::talk_mug, dialogue_chatbin::talk_radio, dialogue_chatbin::talk_stole_item, dialogue_chatbin::talk_stranger_aggressive, dialogue_chatbin::talk_wake_up, trait_PROF_CHURL, trait_PROF_FOODP, npc_opinion::trust, and type.
give_item_to()
std::string talker_npc::give_item_to (bool to_use) override virtual
Reimplemented from talker.
Definition at line 411 of file talker_npc.cpp.
 {
     avatar &player_character = get_avatar();
     if( me_npc->is_hallucination() ) {
         return me_npc->chat_snippets().snip_give_to_hallucination.translated();
     }
     item_location loc = game_menus::inv::titled_menu( player_character, _( "Offer what?" ),
                         _( "You have no items to offer." ) );
     if( !loc ) {
         return me_npc->chat_snippets().snip_give_cancel.translated();
     }
     item &given = *loc;
     if( ( loc == player_character.get_wielded_item() &&
           given.has_flag( STATIC( flag_id( "NO_UNWIELD" ) ) ) ) ||
         ( player_character.is_worn( given ) &&
           ( given.has_flag( STATIC( flag_id( "NO_TAKEOFF" ) ) ) ||
             given.has_flag( STATIC( flag_id( "INTEGRATED" ) ) ) ) ) ) {
         // Integrated item or shackles
         return _( "How?" );
     }
     if( given.is_dangerous() && !player_character.has_trait( trait_DEBUG_MIND_CONTROL ) ) {
         return me_npc->chat_snippets().snip_give_dangerous.translated();
     }
     bool taken = false;
     std::string reason = me_npc->chat_snippets().snip_give_nope.translated();
     const item_location weapon = me_npc->get_wielded_item();
     int our_ammo = me_npc->ammo_count_for( weapon );
     int new_ammo = me_npc->ammo_count_for( loc );
     const double new_weapon_value = me_npc->weapon_value( given, new_ammo );
     const item &weap = weapon ? *weapon : null_item_reference();
     const double cur_weapon_value = me_npc->weapon_value( weap, our_ammo );
     add_msg_debug( debugmode::DF_TALKER, "NPC evaluates own %s (%d ammo): %0.1f",
                    weap.typeId().str(), our_ammo, cur_weapon_value );
     add_msg_debug( debugmode::DF_TALKER, "NPC evaluates your %s (%d ammo): %0.1f",
                    given.typeId().str(), new_ammo, new_weapon_value );
     if( to_use ) {
         // Eating first, to avoid evaluating bread as a weapon
         const consumption_result consume_res = try_consume( *me_npc, given, reason );
         if( consume_res != REFUSED ) {
             player_character.mod_moves( -to_moves<int>( 1_seconds ) );
             if( consume_res == CONSUMED_ALL ) {
                 player_character.i_rem( &given );
             } else if( given.is_container() ) {
                 given.on_contents_changed();
             }
         }// wield it if its a weapon
         else if( new_weapon_value > cur_weapon_value ) {
             me_npc->wield( given );
             reason = me_npc->chat_snippets().snip_give_wield.translated();
             taken = true;
         }// HACK: is_gun here is a hack to prevent NPCs wearing guns if they don't want to use them
         else if( !given.is_gun() && given.is_armor() ) {
             //if it is impossible to wear return why
             ret_val<void> can_wear = me_npc->can_wear( given, true );
             if( !can_wear.success() ) {
                 reason = can_wear.str();
             } else {
                 //if we can wear it with equip changes prompt first
                 can_wear = me_npc->can_wear( given );
                 if( ( can_wear.success() ||
                       query_yn( can_wear.str() + _( " Should I take something off?" ) ) )
                     && me_npc->wear_if_wanted( given, reason ) ) {
                     taken = true;
                 } else {
                     reason = can_wear.str();
                 }
             }
         } else {
             reason += " " + string_format( me_npc->chat_snippets().snip_give_weapon_weak.translated() +
                                            _( "(new weapon value: %.1f vs %.1f)." ), new_weapon_value, cur_weapon_value );
         }
     } else {//allow_use is false so try to carry instead
         if( me_npc->can_pickVolume( given ) && me_npc->can_pickWeight( given ) ) {
             reason = me_npc->chat_snippets().snip_give_carry.translated();
             // set the item given to be favorited so it's not dropped automatically
             given.set_favorite( true );
             taken = true;
             me_npc->i_add( given );
         } else {
             if( !me_npc->can_pickVolume( given ) ) {
                 const units::volume free_space = me_npc->volume_capacity() -
                                                  me_npc->volume_carried();
                 reason += " " + std::string( me_npc->chat_snippets().snip_give_carry_cant.translated() ) + " ";
                 if( free_space > 0_ml ) {
                     std::string talktag = me_npc->chat_snippets().snip_give_carry_cant_few_space.translated();
                     parse_tags( talktag, get_player_character(), *me_npc );
                     reason += string_format( _( talktag ), format_volume( free_space ), volume_units_long() );
                 } else {
                     reason += me_npc->chat_snippets().snip_give_carry_cant_no_space.translated();
                 }
             }
             if( !me_npc->can_pickWeight( given ) ) {
                 reason += std::string( " " ) + me_npc->chat_snippets().snip_give_carry_too_heavy.translated();
             }
         }
     }
     if( taken ) {
         player_character.i_rem( &given );
         player_character.mod_moves( -to_moves<int>( 1_seconds ) );
         me_npc->has_new_items = true;
     }
     return reason;
 }
References _, add_msg_debug, Character::ammo_count_for(), Character::can_pickVolume(), Character::can_pickWeight(), Character::can_wear(), npc::chat_snippets(), CONSUMED_ALL, debugmode::DF_TALKER, flag_id, format_volume(), get_avatar(), get_player_character(), Character::get_wielded_item(), item::has_flag(), npc::has_new_items, Character::has_trait(), Character::i_add(), Character::i_rem(), item::is_armor(), item::is_container(), item::is_dangerous(), item::is_gun(), npc::is_hallucination(), Character::is_worn(), me_npc, Creature::mod_moves(), null_item_reference(), item::on_contents_changed(), parse_tags(), query_yn(), REFUSED, item::set_favorite(), dialogue_chatbin_snippets::snip_give_cancel, dialogue_chatbin_snippets::snip_give_carry, dialogue_chatbin_snippets::snip_give_carry_cant, dialogue_chatbin_snippets::snip_give_carry_cant_few_space, dialogue_chatbin_snippets::snip_give_carry_cant_no_space, dialogue_chatbin_snippets::snip_give_carry_too_heavy, dialogue_chatbin_snippets::snip_give_dangerous, dialogue_chatbin_snippets::snip_give_nope, dialogue_chatbin_snippets::snip_give_to_hallucination, dialogue_chatbin_snippets::snip_give_weapon_weak, dialogue_chatbin_snippets::snip_give_wield, STATIC, ret_val_common::str(), string_id< T >::str(), string_format(), ret_val_common::success(), game_menus::inv::titled_menu(), trait_DEBUG_MIND_CONTROL, translation::translated(), try_consume(), item::typeId(), Character::volume_capacity(), Character::volume_carried(), volume_units_long(), Character::weapon_value(), npc::wear_if_wanted(), and npc::wield().
has_activity()
bool talker_npc::has_activity () const override virtual
Reimplemented from talker_character_const.
Definition at line 816 of file talker_npc.cpp.
 {
     return !me_npc->activity.is_null();
 }
References Character::activity, player_activity::is_null(), and me_npc.
has_ai_rule()
bool talker_npc::has_ai_rule (const std::string & type, const std::string & rule) const override virtual
Reimplemented from talker.
Definition at line 602 of file talker_npc.cpp.
 {
     if( type == "aim_rule" ) {
         auto rule_val = aim_rule_strs.find( rule );
         if( rule_val != aim_rule_strs.end() ) {
             return me_npc->rules.aim == rule_val->second;
         }
     } else if( type == "engagement_rule" ) {
         auto rule_val = combat_engagement_strs.find( rule );
         if( rule_val != combat_engagement_strs.end() ) {
             return me_npc->rules.engagement == rule_val->second;
         }
     } else if( type == "cbm_reserve_rule" ) {
         auto rule_val = cbm_reserve_strs.find( rule );
         if( rule_val != cbm_reserve_strs.end() ) {
             return me_npc->rules.cbm_reserve == rule_val->second;
         }
     } else if( type == "cbm_recharge_rule" ) {
         auto rule_val = cbm_recharge_strs.find( rule );
         if( rule_val != cbm_recharge_strs.end() ) {
             return me_npc->rules.cbm_recharge == rule_val->second;
         }
     } else if( type == "ally_rule" ) {
         auto rule_val = ally_rule_strs.find( rule );
         if( rule_val != ally_rule_strs.end() ) {
             return me_npc->rules.has_flag( rule_val->second.rule );
         }
     } else if( type == "ally_override" ) {
         auto rule_val = ally_rule_strs.find( rule );
         if( rule_val != ally_rule_strs.end() ) {
             return me_npc->rules.has_override_enable( rule_val->second.rule );
         }
     } else if( type == "pickup_rule" ) {
         if( rule == "any" ) {
             return !me_npc->rules.pickup_whitelist->empty();
         }
     }
     return false;
 }
References npc_follower_rules::aim, aim_rule_strs, ally_rule_strs, npc_follower_rules::cbm_recharge, cbm_recharge_strs, npc_follower_rules::cbm_reserve, cbm_reserve_strs, combat_engagement_strs, npc_follower_rules::engagement, npc_follower_rules::has_flag(), npc_follower_rules::has_override_enable(), me_npc, npc_follower_rules::pickup_whitelist, npc::rules, and type.
is_enemy()
bool talker_npc::is_enemy () const override virtual
Reimplemented from talker.
Definition at line 582 of file talker_npc.cpp.
 {
     return me_npc->is_enemy();
 }
References npc::is_enemy(), and me_npc.
is_following()
bool talker_npc::is_following () const override virtual
Reimplemented from talker.
Definition at line 572 of file talker_npc.cpp.
 {
     return me_npc->is_following();
 }
References npc::is_following(), and me_npc.
is_friendly()
bool talker_npc::is_friendly (const Character & guy) const override virtual
Reimplemented from talker.
Definition at line 577 of file talker_npc.cpp.
 {
     return me_npc->is_friendly( guy );
 }
References npc::is_friendly(), and me_npc.
is_myclass()
bool talker_npc::is_myclass (const npc_class_id & class_to_check) const override virtual
Reimplemented from talker.
Definition at line 821 of file talker_npc.cpp.
 {
     return me_npc->myclass == class_to_check;
 }
References me_npc, and npc::myclass.
is_player_ally()
bool talker_npc::is_player_ally () const override virtual
Reimplemented from talker.
Definition at line 587 of file talker_npc.cpp.
 {
     return me_npc->is_player_ally();
 }
References npc::is_player_ally(), and me_npc.
Referenced by evaluation_by().
is_safe()
bool talker_npc::is_safe () const override virtual
Reimplemented from talker.
Definition at line 859 of file talker_npc.cpp.
 {
     return me_npc->is_safe();
 }
References npc::is_safe(), and me_npc.
make_angry()
void talker_npc::make_angry () override virtual
Reimplemented from talker.
Definition at line 597 of file talker_npc.cpp.
 {
     me_npc->make_angry();
 }
References npc::make_angry(), and me_npc.
opinion_text()
std::string talker_npc::opinion_text () const override virtual
Reimplemented from talker.
Definition at line 836 of file talker_npc.cpp.
 {
     return me_npc->opinion_text();
 }
References me_npc, and npc::opinion_text().
parse_mod()
int talker_npc::parse_mod (const std::string & attribute, int factor) const override virtual
Reimplemented from talker.
Definition at line 241 of file talker_npc.cpp.
 {
     int modifier = 0;
     if( attribute == "ANGER" ) {
         modifier = me_npc->op_of_u.anger;
     } else if( attribute == "FEAR" ) {
         modifier = me_npc->op_of_u.fear;
     } else if( attribute == "TRUST" ) {
         modifier = me_npc->op_of_u.trust;
     } else if( attribute == "VALUE" ) {
         modifier = me_npc->op_of_u.value;
     } else if( attribute == "POS_FEAR" ) {
         modifier = std::max( 0, me_npc->op_of_u.fear );
     } else if( attribute == "AGGRESSION" ) {
         // NOLINTNEXTLINE(bugprone-signed-char-misuse,cert-str34-c)
         modifier = me_npc->personality.aggression;
     } else if( attribute == "ALTRUISM" ) {
         // NOLINTNEXTLINE(bugprone-signed-char-misuse,cert-str34-c)
         modifier = me_npc->personality.altruism;
     } else if( attribute == "BRAVERY" ) {
         // NOLINTNEXTLINE(bugprone-signed-char-misuse,cert-str34-c)
         modifier = me_npc->personality.bravery;
     } else if( attribute == "COLLECTOR" ) {
         // NOLINTNEXTLINE(bugprone-signed-char-misuse,cert-str34-c)
         modifier = me_npc->personality.collector;
     } else if( attribute == "MISSIONS" ) {
         modifier = me_npc->assigned_missions_value() / OWED_VAL;
     } else if( attribute == "NPC_INTIMIDATE" ) {
         modifier = me_npc->intimidation();
     }
     modifier *= factor;
     return modifier;
 }
References npc_personality::aggression, npc_personality::altruism, npc_opinion::anger, npc::assigned_missions_value(), npc_personality::bravery, npc_personality::collector, npc_opinion::fear, Character::intimidation(), max(), me_npc, npc::op_of_u, OWED_VAL, npc::personality, npc_opinion::trust, and npc_opinion::value.
say()
void talker_npc::say (const std::string & speech) override virtual
Reimplemented from talker.
Definition at line 831 of file talker_npc.cpp.
 {
     me_npc->say( speech );
 }
References me_npc, npc::say(), and speech.
select_mission()
void talker_npc::select_mission (mission * selected) override virtual
Reimplemented from talker.
Definition at line 540 of file talker_npc.cpp.
 {
     me_npc->chatbin.mission_selected = selected;
 }
References npc::chatbin, me_npc, and dialogue_chatbin::mission_selected.
selected_mission()
mission * talker_npc::selected_mission () const override virtual
Reimplemented from talker.
Definition at line 535 of file talker_npc.cpp.
 {
     return me_npc->chatbin.mission_selected;
 }
References npc::chatbin, me_npc, and dialogue_chatbin::mission_selected.
set_ai_rule()
void talker_npc::set_ai_rule (const std::string & type, const std::string & rule) override virtual
Reimplemented from talker.
Definition at line 655 of file talker_npc.cpp.
 {
     if( type == "aim_rule" ) {
         auto rule_val = aim_rule_strs.find( rule );
         if( rule_val != aim_rule_strs.end() ) {
             me_npc->rules.aim = rule_val->second;
             me_npc->invalidate_range_cache();
         }
     } else if( type == "engagement_rule" ) {
         auto rule_val = combat_engagement_strs.find( rule );
         if( rule_val != combat_engagement_strs.end() ) {
             me_npc->rules.engagement = rule_val->second;
             me_npc->invalidate_range_cache();
             me_npc->wield_better_weapon();
         }
     } else if( type == "cbm_reserve_rule" ) {
         auto rule_val = cbm_reserve_strs.find( rule );
         if( rule_val != cbm_reserve_strs.end() ) {
             me_npc->rules.cbm_reserve = rule_val->second;
         }
     } else if( type == "cbm_recharge_rule" ) {
         auto rule_val = cbm_recharge_strs.find( rule );
         if( rule_val != cbm_recharge_strs.end() ) {
             me_npc->rules.cbm_recharge = rule_val->second;
         }
     } else if( type == "ally_rule" ) {
         auto toggle = ally_rule_strs.find( rule );
         if( toggle == ally_rule_strs.end() ) {
             return;
         }
         me_npc->rules.set_flag( toggle->second.rule );
         me_npc->invalidate_range_cache();
         me_npc->wield_better_weapon();
     }
 }
References npc_follower_rules::aim, aim_rule_strs, ally_rule_strs, npc_follower_rules::cbm_recharge, cbm_recharge_strs, npc_follower_rules::cbm_reserve, cbm_reserve_strs, combat_engagement_strs, npc_follower_rules::engagement, npc::invalidate_range_cache(), me_npc, npc::rules, npc_follower_rules::set_flag(), type, and npc::wield_better_weapon().
set_class()
void talker_npc::set_class (const npc_class_id & new_class) override virtual
Reimplemented from talker.
Definition at line 826 of file talker_npc.cpp.
 {
     me_npc->myclass = new_class;
 }
References me_npc, and npc::myclass.
set_companion_mission()
void talker_npc::set_companion_mission (const std::string & role_id) override virtual
Reimplemented from talker.
Definition at line 552 of file talker_npc.cpp.
 {
     me_npc->companion_mission_role_id = role_id;
     talk_function::companion_mission( *me_npc );
 }
References talk_function::companion_mission(), npc::companion_mission_role_id, and me_npc.
set_fac()
void talker_npc::set_fac (const faction_id & new_fac_name) override virtual
Reimplemented from talker.
Definition at line 558 of file talker_npc.cpp.
 {
     me_npc->set_fac( new_fac_name );
 }
References me_npc, and npc::set_fac().
set_first_topic()
void talker_npc::set_first_topic (const std::string & chat_topic) override virtual
Reimplemented from talker.
Definition at line 854 of file talker_npc.cpp.
 {
     me_npc->chatbin.first_topic = chat_topic;
 }
References npc::chatbin, dialogue_chatbin::first_topic, and me_npc.
set_npc_anger()
void talker_npc::set_npc_anger (int anger) override virtual
Reimplemented from talker.
Definition at line 903 of file talker_npc.cpp.
 {
     me_npc->op_of_u.anger = anger;
 }
References npc_opinion::anger, me_npc, and npc::op_of_u.
set_npc_fear()
void talker_npc::set_npc_fear (int fear) override virtual
Reimplemented from talker.
Definition at line 883 of file talker_npc.cpp.
 {
     me_npc->op_of_u.fear = fear;
 }
References npc_opinion::fear, me_npc, and npc::op_of_u.
set_npc_trust()
void talker_npc::set_npc_trust (int trust) override virtual
Reimplemented from talker.
Definition at line 873 of file talker_npc.cpp.
 {
     me_npc->op_of_u.trust = trust;
 }
References me_npc, npc::op_of_u, and npc_opinion::trust.
set_npc_value()
void talker_npc::set_npc_value (int value) override virtual
Reimplemented from talker.
Definition at line 893 of file talker_npc.cpp.
 {
     me_npc->op_of_u.value = value;
 }
References me_npc, npc::op_of_u, npc_opinion::value, and value().
sold()
int talker_npc::sold () const override virtual
Reimplemented from talker.
Definition at line 306 of file talker_npc.cpp.
 {
     return me_npc->op_of_u.sold;
 }
References me_npc, npc::op_of_u, and npc_opinion::sold.
store_chosen_training()
void talker_npc::store_chosen_training (const skill_id & c_skill, const matype_id & c_style, const spell_id & c_spell, const proficiency_id & c_proficiency) override virtual
Reimplemented from talker.
Definition at line 290 of file talker_npc.cpp.
 {
     me_npc->chatbin.store_chosen_training( c_skill, c_style, c_spell, c_proficiency );
 }
References npc::chatbin, me_npc, and dialogue_chatbin::store_chosen_training().
toggle_ai_rule()
void talker_npc::toggle_ai_rule (const std::string & type, const std::string & rule) override virtual
Reimplemented from talker.
Definition at line 644 of file talker_npc.cpp.
 {
     auto toggle = ally_rule_strs.find( rule );
     if( toggle == ally_rule_strs.end() ) {
         return;
     }
     me_npc->rules.toggle_flag( toggle->second.rule );
     me_npc->invalidate_range_cache();
     me_npc->wield_better_weapon();
 }
References ally_rule_strs, npc::invalidate_range_cache(), me_npc, npc::rules, npc_follower_rules::toggle_flag(), and npc::wield_better_weapon().
trial_chance_mod()
int talker_npc::trial_chance_mod (const std::string & trial_type) const override virtual
Reimplemented from talker.
Definition at line 275 of file talker_npc.cpp.
 {
     int chance = 0;
     if( trial_type == "lie" ) {
         chance += - me_npc->lie_skill() + me_npc->op_of_u.trust * 3;
     } else if( trial_type == "persuade" ) {
         chance += - static_cast<int>( me_npc->persuade_skill() * 0.5 ) +
                   me_npc->op_of_u.trust * 2 + me_npc->op_of_u.value;
     } else if( trial_type == "intimidate" ) {
         chance += - me_npc->intimidation() + me_npc->op_of_u.fear * 2 -
                   me_npc->personality.bravery * 2;
     }
     return chance;
 }
References npc_personality::bravery, npc_opinion::fear, Character::intimidation(), Character::lie_skill(), me_npc, npc::op_of_u, npc::personality, Character::persuade_skill(), npc_opinion::trust, and npc_opinion::value.
turned_hostile()
bool talker_npc::turned_hostile () const override virtual
Reimplemented from talker.
Definition at line 592 of file talker_npc.cpp.
 {
     return me_npc->turned_hostile();
 }
References me_npc, and npc::turned_hostile().
update_missions()
void talker_npc::update_missions (const std::vector< mission * > & missions_assigned) override virtual
Reimplemented from talker.
Definition at line 222 of file talker_npc.cpp.
 {
     if( me_npc->chatbin.mission_selected == nullptr ) {
         // if possible, select a mission to talk about
         if( !me_npc->chatbin.missions.empty() ) {
             me_npc->chatbin.mission_selected = me_npc->chatbin.missions.front();
         } else if( !missions_assigned.empty() ) {
             me_npc->chatbin.mission_selected = missions_assigned.front();
         }
     }
 }
References npc::chatbin, me_npc, dialogue_chatbin::mission_selected, and dialogue_chatbin::missions.
value()
int talker_npc::value (const item & it) const override virtual
Reimplemented from talker.
Definition at line 321 of file talker_npc.cpp.
 {
     return me_npc->value( it );
 }
References me_npc, and npc::value().
Referenced by add_sold(), cash_to_favor(), and set_npc_value().
view_personality_traits()
std::string talker_npc::view_personality_traits () const override virtual
Reimplemented from talker.
Definition at line 707 of file talker_npc.cpp.
 {
     // Special starting char so it doesn't appear as though the NPC is talking to us
     std::string assessment = "&";
     assessment += _( "<npc_name> seems to be:" );
     bool found_personality_trait = false;
     for( const auto &trait_data_pairs : me_npc->my_mutations ) {
         const mutation_branch &mdata = trait_data_pairs.first.obj();
         if( mdata.personality_score ) {
             found_personality_trait = true;
             assessment += "\n";
             assessment += me_npc->mutation_name( mdata.id );
             assessment += " - ";
             assessment += me_npc->mutation_desc( mdata.id );
             // Example output:
             // John Doe seems to be:
             // Coward - John Doe flinches at the thought of fighting, whether it be other people or the undead.
             // Nice - John Doe has a higher than average altruism.
             // TRAIT NAME - TRAIT DESCRIPTION
         }
     }
     // Fallback
     if( !found_personality_trait ) {
         assessment += _( "\nNormal person - <npc_name> seems to be pretty normal." );
     }
     return assessment;
 }
References _, mutation_branch::id, me_npc, Character::mutation_desc(), Character::mutation_name(), Character::my_mutations, and mutation_branch::personality_score.
will_talk_to_u()
bool talker_npc::will_talk_to_u (const Character & you, bool force) override virtual
Reimplemented from talker.
Definition at line 88 of file talker_npc.cpp.
 {
     if( you.is_dead_state() ) {
         me_npc->set_attitude( NPCATT_NULL );
         return false;
     }
     if( get_player_character().getID() == you.getID() ) {
         if( me_npc->get_faction() ) {
             me_npc->get_faction()->known_by_u = true;
         }
         me_npc->set_known_to_u( true );
     }
     // This is necessary so that we don't bug the player over and over
     if( me_npc->get_attitude() == NPCATT_TALK ) {
         me_npc->set_attitude( NPCATT_NULL );
     } else if( !force && ( me_npc->get_attitude() == NPCATT_FLEE ||
                            me_npc-> get_attitude() == NPCATT_FLEE_TEMP ) ) {
         add_msg( _( "%s is fleeing from you!" ), disp_name() );
         return false;
     } else if( !force && me_npc->get_attitude() == NPCATT_KILL ) {
         add_msg( _( "%s is hostile!" ), disp_name() );
         return false;
     }
     return true;
 }
References _, add_msg(), talker_character_const::disp_name(), force, npc::get_attitude(), npc::get_faction(), get_player_character(), Character::getID(), talker_character_const::getID(), Character::is_dead_state(), faction_template::known_by_u, me_npc, NPCATT_FLEE, NPCATT_FLEE_TEMP, NPCATT_KILL, NPCATT_NULL, NPCATT_TALK, npc::set_attitude(), and npc::set_known_to_u().
Member Data Documentation
me_npc
npc* talker_npc::me_npc protected
Definition at line 111 of file talker_npc.h.
Referenced by add_debt(), add_faction_rep(), add_mission(), add_opinion(), add_sold(), assigned_missions(), available_missions(), buy_from(), cash_to_favor(), check_hostile_response(), check_missions(), clear_ai_rule(), debt(), die(), distance_to_goal(), enslave_mind(), evaluation_by(), get_job_description(), get_npc(), get_npc_anger(), get_npc_fear(), get_npc_trust(), get_npc_value(), get_topics(), give_item_to(), has_activity(), has_ai_rule(), is_enemy(), is_following(), is_friendly(), is_myclass(), is_player_ally(), is_safe(), make_angry(), opinion_text(), parse_mod(), say(), select_mission(), selected_mission(), set_ai_rule(), set_class(), set_companion_mission(), set_fac(), set_first_topic(), set_npc_anger(), set_npc_fear(), set_npc_trust(), set_npc_value(), sold(), store_chosen_training(), talker_npc(), toggle_ai_rule(), trial_chance_mod(), turned_hostile(), update_missions(), value(), view_personality_traits(), and will_talk_to_u().
The documentation for this class was generated from the following files:
src/talker_npc.h
src/talker_npc.cpp