Cataclysm DDA: recipe_dictionary Class Reference
recipe_dictionary Class Reference
#include <recipe_dictionary.h>
Public Member Functions
const std::set< const recipe * > & all_autolearn () const
Returns all recipes that can be automatically learned.
const std::set< const recipe * > & all_nested () const
Returns all recipes that are nested categories.
const std::set< const recipe * > & all_blueprints () const
Returns all blueprints.
std::map< recipe_id, const recipe * > find_obsoletes (const itype_id &item_id) const
size_t size () const
std::map< recipe_id, recipe >::const_iterator begin () const
std::map< recipe_id, recipe >::const_iterator end () const
bool is_item_on_loop (const itype_id &) const
Static Public Member Functions
static const recipe & get_uncraft (const itype_id &id)
Returns disassembly recipe (or null recipe if no match)
static const recipe & get_craft (const itype_id &id)
Returns crafting recipe (or null recipe if no match)
static void load_recipe (const JsonObject &jo, const std::string &src)
static void load_uncraft (const JsonObject &jo, const std::string &src)
static void load_practice (const JsonObject &jo, const std::string &src)
static void load_nested_category (const JsonObject &jo, const std::string &src)
static void finalize ()
static void check_consistency ()
static void reset ()
Static Protected Member Functions
static void delete_if (const std::function< bool(const recipe &)> &pred)
Remove all recipes matching the predicate.
static recipe & load (const JsonObject &jo, const std::string &src, std::map< recipe_id, recipe > &out)
Private Member Functions
void find_items_on_loops ()
Static Private Member Functions
static void finalize_internal (std::map< recipe_id, recipe > &obj)
Private Attributes
friend recipe_id
std::map< recipe_id, recipe > recipes
std::map< recipe_id, recipe > uncraft
std::set< const recipe * > autolearn
std::set< const recipe * > nested
std::set< const recipe * > blueprints
std::map< const itype_id, const recipe * > obsoletes
std::unordered_set< itype_id > items_on_loops
Friends
class Item_factory
Detailed Description
Definition at line 22 of file recipe_dictionary.h.
Member Function Documentation
all_autolearn()
const std::set<const recipe *>& recipe_dictionary::all_autolearn () const inline
Returns all recipes that can be automatically learned.
Definition at line 29 of file recipe_dictionary.h.
{
             return autolearn;
         }
References autolearn.
Referenced by assemble_skill_details(), and Character::get_learned_recipes().
all_blueprints()
const std::set<const recipe *>& recipe_dictionary::all_blueprints () const inline
Returns all blueprints.
Definition at line 39 of file recipe_dictionary.h.
{
             return blueprints;
         }
References blueprints.
Referenced by basecamp::available_upgrades().
all_nested()
const std::set<const recipe *>& recipe_dictionary::all_nested () const inline
Returns all recipes that are nested categories.
Definition at line 34 of file recipe_dictionary.h.
{
             return nested;
         }
References nested.
Referenced by filter_recipes(), and Character::get_available_nested().
begin()
std::map< recipe_id, recipe >::const_iterator recipe_dictionary::begin () const
Definition at line 477 of file recipe_dictionary.cpp.
 {
     return recipes.begin();
 }
References recipes.
Referenced by find_uncraft_recipe().
check_consistency()
void recipe_dictionary::check_consistency () static
Definition at line 674 of file recipe_dictionary.cpp.
 {
     for( const auto &e : recipe_dict.recipes ) {
         const recipe &r = e.second;
         if( r.category.empty() ) {
             if( !r.subcategory.empty() ) {
                 debugmsg( "recipe %s has subcategory but no category", r.ident().str() );
             }
             continue;
         }
         const std::vector<std::string> *subcategories = subcategories_for_category( r.category );
         if( !subcategories ) {
             debugmsg( "recipe %s has invalid category %s", r.ident().str(), r.category );
             continue;
         }
         if( !r.subcategory.empty() ) {
             auto it = std::find( subcategories->begin(), subcategories->end(), r.subcategory );
             if( it == subcategories->end() ) {
                 debugmsg(
                     "recipe %s has subcategory %s which is invalid or doesn't match category %s",
                     r.ident().str(), r.subcategory, r.category );
             }
         }
     }
     for( const auto &e : recipe_dict.recipes ) {
         const recipe &r = e.second;
         if( !r.blueprint.is_empty() && !has_update_mapgen_for( r.blueprint ) ) {
             debugmsg( "recipe %s specifies invalid construction_blueprint %s; that should be a "
                       "defined update_mapgen_id but is not", r.ident().str(), r.blueprint.str() );
         }
     }
 }
References recipe::blueprint, recipe::category, debugmsg, has_update_mapgen_for(), recipe::ident(), string_id< T >::is_empty(), recipe_dict, recipes, string_id< T >::str(), subcategories_for_category(), and recipe::subcategory.
Referenced by DynamicDataLoader::check_consistency().
delete_if()
void recipe_dictionary::delete_if (const std::function< bool(const recipe &)> & pred) static protected
Remove all recipes matching the predicate.
Warning
must not be called after finalize()
Definition at line 728 of file recipe_dictionary.cpp.
 {
     ::delete_if( recipe_dict.recipes, pred );
     ::delete_if( recipe_dict.uncraft, pred );
 }
References recipe_dict, recipes, and uncraft.
Referenced by finalize(), finalize_internal(), and Item_factory::finalize_item_blacklist().
end()
std::map< recipe_id, recipe >::const_iterator recipe_dictionary::end () const
Definition at line 482 of file recipe_dictionary.cpp.
 {
     return recipes.end();
 }
References recipes.
Referenced by find_uncraft_recipe().
finalize()
void recipe_dictionary::finalize () static
Definition at line 576 of file recipe_dictionary.cpp.
 {
     DynamicDataLoader::get_instance().load_deferred( deferred );
     // remove abstract recipes
     delete_if( []( const recipe & element ) {
         return element.abstract;
     } );
     finalize_internal( recipe_dict.recipes );
     finalize_internal( recipe_dict.uncraft );
     for( const auto &e : recipe_dict.recipes ) {
         const recipe &r = e.second;
         if( r.obsolete ) {
             continue;
         }
         for( const auto &bk : r.booksets ) {
             const itype *booktype = item::find_type( bk.first );
             int req = bk.second.skill_req > 0 ? bk.second.skill_req : std::max( booktype->book->req,
                       r.difficulty );
             islot_book::recipe_with_description_t desc{ &r, req, bk.second.alt_name, bk.second.hidden };
             const_cast<islot_book &>( *booktype->book ).recipes.insert( desc );
         }
         // if reversible and no specific uncraft recipe exists use this recipe
         const string_id<recipe> uncraft_id = recipe_id( r.result().str() );
         if( r.is_reversible() && !recipe_dict.uncraft.count( uncraft_id ) ) {
             recipe_dict.uncraft[ uncraft_id ] = r;
             if( r.uncraft_time > 0 ) {
                 // If a specified uncraft time has been given, use that in the uncraft
                 // recipe rather than the original.
                 recipe_dict.uncraft[ uncraft_id ].time = r.uncraft_time;
             }
         }
     }
     // add pseudo uncrafting recipes
     for( const itype *e : item_controller->all() ) {
         const itype_id id = e->get_id();
         const recipe_id rid = recipe_id( id.str() );
         // books that don't already have an uncrafting recipe
         if( e->book && !recipe_dict.uncraft.count( rid ) && e->volume > 0_ml ) {
             int pages = e->volume / 12.5_ml;
             recipe &bk = recipe_dict.uncraft[rid];
             bk.id = rid;
             bk.result_ = id;
             bk.reversible = true;
             bk.requirements_ = *requirement_data_uncraft_book * pages;
             // TODO: allow specifying time in requirement_data
             bk.time = pages * 10;
         }
     }
     // Check for nested items without a category to make sure nothing is getting lost
     for( const auto &rec : recipe_dict.recipes ) {
         if( rec.second.subcategory == "CSC_*_NESTED" ) {
             bool found = false;
             for( const auto &nest : recipe_dict.recipes ) {
                 if( nest.second.is_nested() ) {
                     if( find( nest.second.nested_category_data.begin(), nest.second.nested_category_data.end(),
                               rec.first ) != nest.second.nested_category_data.end() ) {
                         found = true;
                         break;
                     }
                 }
             }
             if( !found ) {
                 debugmsg( "recipe %s is nested but isn't in a nested group.  It will be impossible to path to by the player.",
                           rec.first.str() );
             }
         }
     }
     // Cache auto-learn recipes and blueprints
     for( const auto &e : recipe_dict.recipes ) {
         if( e.second.obsolete ) {
             recipe_dict.obsoletes.emplace( e.second.result(), &e.second );
         }
         if( e.second.autolearn ) {
             recipe_dict.autolearn.insert( &e.second );
         }
         if( e.second.is_nested() ) {
             recipe_dict.nested.insert( &e.second );
         }
         if( e.second.is_blueprint() ) {
             recipe_dict.blueprints.insert( &e.second );
         }
     }
     recipe_dict.find_items_on_loops();
 }
References autolearn, blueprints, itype::book, recipe::booksets, debugmsg, deferred, delete_if(), recipe::difficulty, finalize_internal(), find_items_on_loops(), item::find_type(), itype::get_id(), DynamicDataLoader::get_instance(), base_camps::id, recipe::id, recipe::is_reversible(), item_controller, DynamicDataLoader::load_deferred(), max(), nest, nested, recipe::obsolete, obsoletes, recipe_dict, recipe_id, recipes, requirement_data_uncraft_book, recipe::requirements_, recipe::result(), recipe::result_, recipe::reversible, string_id< T >::str(), recipe::time, uncraft, and recipe::uncraft_time.
Referenced by DynamicDataLoader::finalize_loaded_data().
finalize_internal()
void recipe_dictionary::finalize_internal (std::map< recipe_id, recipe > & obj) static private
Definition at line 504 of file recipe_dictionary.cpp.
 {
     for( auto &elem : obj ) {
         erase_if( elem.second.nested_category_data, [&]( const recipe_id & nest ) {
             return !nest.is_valid() || nest->will_be_blacklisted();
         } );
         elem.second.finalize();
         inp_mngr.pump_events();
     }
     // remove any blacklisted or invalid recipes...
     delete_if( []( const recipe & elem ) {
         if( elem.is_blacklisted() ) {
             return true;
         }
         if( elem.obsolete ) {
             return false;
         }
         const std::string error = elem.get_consistency_error();
         if( !error.empty() ) {
             debugmsg( "Recipe %s %s.", elem.ident().c_str(), error.c_str() );
         }
         return !error.empty();
     } );
 }
References delete_if(), erase_if(), error, recipe::get_consistency_error(), inp_mngr, recipe::is_blacklisted(), nest, recipe::obsolete, and input_manager::pump_events().
Referenced by finalize().
find_items_on_loops()
void recipe_dictionary::find_items_on_loops () private
Definition at line 533 of file recipe_dictionary.cpp.
 {
     // Check for infinite recipe loops in food (which are problematic for
     // nutrient calculations).
     //
     // Start by building a directed graph of itypes to potential components of
     // those itypes.
     items_on_loops.clear();
     std::unordered_map<itype_id, std::vector<itype_id>> potential_components_of;
     for( const itype *i : item_controller->all() ) {
         if( !i->comestible || i->has_flag( STATIC( flag_id( "NUTRIENT_OVERRIDE" ) ) ) ) {
             continue;
         }
         std::vector<itype_id> &potential_components = potential_components_of[i->get_id()];
         for( const recipe_id &rec : i->recipes ) {
             const requirement_data requirements = rec->simple_requirements();
             const requirement_data::alter_item_comp_vector &component_requirements =
                 requirements.get_components();
             for( const std::vector<item_comp> &component_options : component_requirements ) {
                 for( const item_comp &component_option : component_options ) {
                     potential_components.push_back( component_option.type );
                 }
             }
         }
     }
     // Now check that graph for loops
     std::vector<std::vector<itype_id>> loops = cata::find_cycles( potential_components_of );
     for( const std::vector<itype_id> &loop : loops ) {
         std::string error_message =
             "loop in comestible recipes detected: " + loop.back().str();
         for( const itype_id &i : loop ) {
             error_message += " -> " + i.str();
             items_on_loops.insert( i );
         }
         error_message += ".  Such loops can be broken by either removing or altering "
                          "recipes or marking one of the items involved with the NUTRIENT_OVERRIDE "
                          "flag";
         debugmsg( error_message );
     }
 }
References debugmsg, cata::find_cycles(), flag_id, requirement_data::get_components(), item_controller, items_on_loops, recipe::simple_requirements(), and STATIC.
Referenced by finalize().
find_obsoletes()
std::map< recipe_id, const recipe * > recipe_dictionary::find_obsoletes (const itype_id & item_id) const
Definition at line 487 of file recipe_dictionary.cpp.
 {
     std::map<recipe_id, const recipe *> ret;
     auto p = obsoletes.equal_range( item_id );
     for( auto it = p.first; it != p.second; ++it ) {
         const recipe *r = it->second;
         ret.emplace( r->ident(), r );
     }
     return ret;
 }
References recipe::ident(), obsoletes, and cata::hash64_detail::ret.
get_craft()
const recipe & recipe_dictionary::get_craft (const itype_id & id) static
Returns crafting recipe (or null recipe if no match)
Definition at line 83 of file recipe_dictionary.cpp.
 {
     auto iter = recipe_dict.recipes.find( recipe_id( id.str() ) );
     return iter != recipe_dict.recipes.end() ? iter->second : null_recipe;
 }
References null_recipe, recipe_dict, recipe_id, and recipes.
Referenced by Character::initialize().
get_uncraft()
const recipe & recipe_dictionary::get_uncraft (const itype_id & id) static
Returns disassembly recipe (or null recipe if no match)
Definition at line 77 of file recipe_dictionary.cpp.
 {
     auto iter = recipe_dict.uncraft.find( recipe_id( id.str() ) );
     return iter != recipe_dict.uncraft.end() ? iter->second : null_recipe;
 }
References null_recipe, recipe_dict, recipe_id, and uncraft.
Referenced by add_disassemblables(), game::butcher(), Character::can_disassemble(), can_do_activity_there(), Character::complete_disassemble(), Character::create_in_progress_disassembly(), recipe::create_results(), item::craft_data::deserialize(), Character::disassemble(), item::disassembly_info(), find_uncraft_recipe(), generic_multi_activity_do(), disassemble_inventory_preset::get_recipe(), item::get_recursive_disassemble_moves(), item::get_uncraft_components(), and item::is_disassemblable().
is_item_on_loop()
bool recipe_dictionary::is_item_on_loop (const itype_id & i) const
Definition at line 499 of file recipe_dictionary.cpp.
 {
     return items_on_loops.count( i );
 }
References items_on_loops.
Referenced by Character::compute_nutrient_range(), and item::food_info().
load()
recipe & recipe_dictionary::load (const JsonObject & jo, const std::string & src, std::map< recipe_id, recipe > & out) static protected
Definition at line 422 of file recipe_dictionary.cpp.
 {
     recipe r;
     // defer entries dependent upon as-yet unparsed definitions
     if( jo.has_string( "copy-from" ) ) {
         recipe_id base = recipe_id( jo.get_string( "copy-from" ) );
         if( !out.count( base ) ) {
             deferred.emplace_back( jo, src );
             jo.allow_omitted_members();
             return null_recipe;
         }
         r = out[ base ];
     }
     r.load( jo, src );
     mod_tracker::assign_src( r, src );
     r.was_loaded = true;
     // Check for duplicate recipe_ids before assigning it to the map
     if( out.find( r.ident() ) != out.end() ) {
         const std::string new_mod_src = enumerate_as_string( r.src, [](
         const std::pair<recipe_id, mod_id> &source ) {
             return string_format( "'%s'", source.second->name() );
         }, enumeration_conjunction::arrow );
         const std::string old_mod_src = enumerate_as_string( out[ r.ident() ].src, [](
         const std::pair<recipe_id, mod_id> &source ) {
             return string_format( "'%s'", source.second->name() );
         }, enumeration_conjunction::arrow );
         const std::string base_json = string_format( "'%s'", _( "Dark Days Ahead" ) );
         if( old_mod_src == base_json && new_mod_src != base_json ) {
             // Assume the mod developer knows what they're doing
         } else if( old_mod_src == new_mod_src ) {
             // Conflict within a single source. Throw an error:
             debugmsg( "Unable to load recipe_id %1$s. A recipe with that id already exists.\nExisting recipe source: %2$s\nNew recipe source: %3$s",
                       r.ident().str(), old_mod_src, new_mod_src );
         } else {
             // Conflict between mods, leave a warning for debugging
             DebugLog( DebugLevel::D_WARNING,
                       DC_ALL ) <<
                                string_format( "Recipe_id conflict: %1$s is included in both %2$s and %3$s.  Only the latter recipe will be loaded",
                                               r.ident().str(), old_mod_src, new_mod_src );
         }
     }
     return out[ r.ident() ] = std::move( r );
 }
References _, JsonObject::allow_omitted_members(), arrow, mod_tracker::assign_src(), D_WARNING, DC_ALL, DebugLog(), debugmsg, deferred, enumerate_as_string(), JsonObject::get_string(), JsonObject::has_string(), recipe::ident(), recipe::load(), null_recipe, recipe_id, recipe::src, string_id< T >::str(), string_format(), and recipe::was_loaded.
Referenced by load_nested_category(), load_practice(), load_recipe(), and load_uncraft().
load_nested_category()
void recipe_dictionary::load_nested_category (const JsonObject & jo, const std::string & src) static
Definition at line 417 of file recipe_dictionary.cpp.
 {
     load( jo, src, recipe_dict.recipes );
 }
References load(), recipe_dict, and recipes.
Referenced by DynamicDataLoader::initialize().
load_practice()
void recipe_dictionary::load_practice (const JsonObject & jo, const std::string & src) static
Definition at line 412 of file recipe_dictionary.cpp.
 {
     load( jo, src, recipe_dict.recipes );
 }
References load(), recipe_dict, and recipes.
Referenced by DynamicDataLoader::initialize().
load_recipe()
void recipe_dictionary::load_recipe (const JsonObject & jo, const std::string & src) static
Definition at line 402 of file recipe_dictionary.cpp.
 {
     load( jo, src, recipe_dict.recipes );
 }
References load(), recipe_dict, and recipes.
Referenced by DynamicDataLoader::initialize().
load_uncraft()
void recipe_dictionary::load_uncraft (const JsonObject & jo, const std::string & src) static
Definition at line 407 of file recipe_dictionary.cpp.
 {
     load( jo, src, recipe_dict.uncraft );
 }
References load(), recipe_dict, and uncraft.
Referenced by DynamicDataLoader::initialize().
reset()
void recipe_dictionary::reset () static
Definition at line 713 of file recipe_dictionary.cpp.
 {
     recipe_dict.blueprints.clear();
     recipe_dict.autolearn.clear();
     recipe_dict.nested.clear();
     recipe_dict.obsoletes.clear();
     recipe_dict.recipes.clear();
     recipe_dict.uncraft.clear();
     recipe_dict.items_on_loops.clear();
     for( std::pair<JsonObject, std::string> &deferred_json : deferred ) {
         deferred_json.first.allow_omitted_members();
     }
     deferred.clear();
 }
References autolearn, blueprints, deferred, items_on_loops, nested, obsoletes, recipe_dict, recipes, and uncraft.
Referenced by DynamicDataLoader::unload_data().
size()
size_t recipe_dictionary::size () const
Definition at line 472 of file recipe_dictionary.cpp.
 {
     return recipes.size();
 }
References recipes.
Friends And Related Function Documentation
Item_factory
friend class Item_factory friend
Definition at line 24 of file recipe_dictionary.h.
Member Data Documentation
autolearn
std::set<const recipe *> recipe_dictionary::autolearn private
Definition at line 78 of file recipe_dictionary.h.
Referenced by all_autolearn(), finalize(), and reset().
blueprints
std::set<const recipe *> recipe_dictionary::blueprints private
Definition at line 80 of file recipe_dictionary.h.
Referenced by all_blueprints(), finalize(), and reset().
items_on_loops
std::unordered_set<itype_id> recipe_dictionary::items_on_loops private
Definition at line 82 of file recipe_dictionary.h.
Referenced by find_items_on_loops(), is_item_on_loop(), and reset().
nested
std::set<const recipe *> recipe_dictionary::nested private
Definition at line 79 of file recipe_dictionary.h.
Referenced by all_nested(), finalize(), and reset().
obsoletes
std::map<const itype_id, const recipe *> recipe_dictionary::obsoletes private
Definition at line 81 of file recipe_dictionary.h.
Referenced by finalize(), find_obsoletes(), and reset().
recipe_id
friend recipe_dictionary::recipe_id private
Definition at line 25 of file recipe_dictionary.h.
Referenced by finalize(), get_craft(), get_uncraft(), and load().
recipes
std::map<recipe_id, recipe> recipe_dictionary::recipes private
Definition at line 76 of file recipe_dictionary.h.
Referenced by begin(), check_consistency(), delete_if(), end(), finalize(), get_craft(), load_nested_category(), load_practice(), load_recipe(), reset(), and size().
uncraft
std::map<recipe_id, recipe> recipe_dictionary::uncraft private
Definition at line 77 of file recipe_dictionary.h.
Referenced by delete_if(), finalize(), get_uncraft(), load_uncraft(), and reset().
The documentation for this class was generated from the following files:
src/recipe_dictionary.h
src/recipe_dictionary.cpp