Cataclysm DDA: past_games_info Class Reference
past_games_info Class Reference
#include <past_games_info.h>
Public Member Functions
past_games_info ()
void ensure_loaded ()
void clear ()
const achievement_completion_info * legacy_achievement (const achievement_id &) const
Private Attributes
bool loaded_ = false
std::unordered_map< achievement_id, achievement_completion_info > legacy_achievements_
std::vector< past_game_info > info_
Detailed Description
Definition at line 52 of file past_games_info.h.
Constructor & Destructor Documentation
past_games_info()
past_games_info::past_games_info () default
Referenced by clear().
Member Function Documentation
clear()
void past_games_info::clear ()
Definition at line 87 of file past_games_info.cpp.
 {
     *this = past_games_info();
 }
References past_games_info().
Referenced by clear_past_games().
ensure_loaded()
void past_games_info::ensure_loaded ()
Definition at line 99 of file past_games_info.cpp.
 {
     if( loaded_ ) {
         return;
     }
     loaded_ = true;
     static_popup popup;
     popup.message( "%s", _( "Please wait while past game data loads…" ) );
     ui_manager::redraw();
     refresh_display();
     const cata_path &memorial_dir = PATH_INFO::memorialdir_path();
     assure_dir_exist( memorial_dir );
     std::vector<cata_path> filenames = get_files_from_path( ".json", memorial_dir, true, true );
     // Sort the files by the date & time encoded in the filename
     std::vector<std::pair<std::string, cata_path>> sortable_filenames;
     for( const cata_path &filename : filenames ) {
         std::vector<std::string> components = string_split(
                 filename.get_unrelative_path().generic_u8string(), '-' );
         if( components.size() < 7 ) {
             debugmsg( "Unexpected memorial filename %s", filename.generic_u8string() );
             continue;
         }
         components.erase( components.begin(), components.end() - 6 );
         sortable_filenames.emplace_back( string_join( components, "-" ), filename );
     }
     std::sort( sortable_filenames.begin(),
                sortable_filenames.end(), []( const std::pair<std::string, cata_path> &l,
     const std::pair<std::string, cata_path> &r ) {
         // Manually replicating std::pair<T,U>::operator < to avoid implementing operator< on cata_path.
         // NOLINTNEXTLINE(cata-use-localized-sorting)
         if( l.first < r.first ) {
             return true;
         }
         // NOLINTNEXTLINE(cata-use-localized-sorting)
         if( l.first > r.first ) {
             return false;
         }
         return l.second.get_unrelative_path() < r.second.get_unrelative_path();
     } );
     for( const std::pair<std::string, cata_path> &filename_pair : sortable_filenames ) {
         const cata_path &filename = filename_pair.second;
         try {
             JsonValue jsin = json_loader::from_path( filename );
             info_.emplace_back( jsin.get_object() );
         } catch( const JsonError &err ) {
             debugmsg( "Error reading memorial file %s: %s", filename.generic_u8string(), err.what() );
         } catch( const too_old_memorial_file_error & ) {
             // do nothing
         }
     }
     for( past_game_info &game : info_ ) {
         stats_tracker &stats = game.stats();
         event_multiset &events = stats.get_events( event_type::player_gets_achievement );
         const event_multiset::summaries_type &counts = events.counts();
         for( const std::pair<const cata::event::data_type, event_summary> &p : counts ) {
             const cata::event::data_type &event_data = p.first;
             auto ach_it = event_data.find( "achievement" );
             auto enabled_it = event_data.find( "achievements_enabled" );
             if( ach_it == event_data.end() || enabled_it == event_data.end() ) {
                 debugmsg( "Missing field in memorial achievement data" );
                 continue;
             }
             if( !enabled_it->second.get<bool>() ) {
                 continue;
             }
             if( game.is_legacy_achievements() ) {
                 const achievement_id ach = ach_it->second.get<achievement_id>();
                 legacy_achievements_[ach].games_completed.push_back( &game );
             }
         }
         inp_mngr.pump_events();
     }
 }
References _, assure_dir_exist(), debugmsg, get_files_from_path(), loaded_, PATH_INFO::memorialdir_path(), popup(), ui_manager::redraw(), refresh_display(), string_join(), and string_split().
Referenced by get_past_games().
legacy_achievement()
const achievement_completion_info * past_games_info::legacy_achievement (const achievement_id & ach) const
Definition at line 92 of file past_games_info.cpp.
 {
     auto ach_it = legacy_achievements_.find( ach );
     return ach_it == legacy_achievements_.end() ? nullptr : &ach_it->second;
 }
References legacy_achievements_.
Referenced by past_achievements_info::avatars_completed().
Member Data Documentation
info_
std::vector<past_game_info> past_games_info::info_ private
Definition at line 67 of file past_games_info.h.
legacy_achievements_
std::unordered_map<achievement_id, achievement_completion_info> past_games_info::legacy_achievements_ private
Definition at line 66 of file past_games_info.h.
Referenced by legacy_achievement().
loaded_
bool past_games_info::loaded_ = false private
Definition at line 64 of file past_games_info.h.
Referenced by ensure_loaded().
The documentation for this class was generated from the following files:
src/past_games_info.h
src/past_games_info.cpp