Cataclysm DDA: morale_type_data Class Reference
morale_type_data Class Reference
#include <morale_types.h>
Public Member Functions
std::string describe (const itype *it=nullptr) const
Describes this morale type, with item type to replace wildcard with.
bool is_permanent () const
void load (const JsonObject &jo, std::string_view src)
void check () const
Static Public Member Functions
static void load_type (const JsonObject &jo, const std::string &src)
static void check_all ()
static void reset ()
static const morale_type & convert_legacy (int lmt)
Public Attributes
morale_type id
std::vector< std::pair< morale_type, mod_id > > src
bool was_loaded = false
Private Attributes
bool permanent = false
translation text
Detailed Description
Definition at line 14 of file morale_types.h.
Member Function Documentation
check()
void morale_type_data::check () const
Definition at line 316 of file morale_types.cpp.
 {
 }
check_all()
void morale_type_data::check_all () static
Definition at line 298 of file morale_types.cpp.
 {
     morale_data.check();
 }
References anonymous_namespace{morale_types.cpp}::morale_data.
convert_legacy()
const morale_type & morale_type_data::convert_legacy (int lmt) static
Definition at line 171 of file morale_types.cpp.
 {
     static const std::vector<morale_type> legacy_morale_types = {{
             morale_null,
             morale_food_good,
             morale_food_hot,
             morale_ate_with_table,
             morale_ate_without_table,
             morale_music,
             morale_honey,
             morale_game,
             morale_marloss,
             morale_mutagen,
             morale_feeling_good,
             morale_support,
             morale_photos,
             morale_craving_nicotine,
             morale_craving_caffeine,
             morale_craving_alcohol,
             morale_craving_opiate,
             morale_craving_speed,
             morale_craving_cocaine,
             morale_craving_crack,
             morale_craving_mutagen,
             morale_craving_diazepam,
             morale_craving_marloss,
             morale_food_bad,
             morale_cannibal,
             morale_vegetarian,
             morale_meatarian,
             morale_antifruit,
             morale_lactose,
             morale_antijunk,
             morale_antiwheat,
             morale_sweettooth,
             morale_no_digest,
             morale_wet,
             morale_dried_off,
             morale_cold,
             morale_hot,
             morale_feeling_bad,
             morale_killed_innocent,
             morale_killed_friend,
             morale_killed_monster,
             morale_mutilate_corpse,
             morale_mutagen_elf,
             morale_mutagen_chimera,
             morale_mutagen_mutation,
             morale_moodswing,
             morale_book,
             morale_comfy,
             morale_scream,
             morale_perm_masochist,
             morale_perm_hoarder,
             morale_perm_fancy,
             morale_perm_optimist,
             morale_perm_badtemper,
             morale_perm_constrained,
             morale_perm_nomad,
             morale_game_found_kitten,
             morale_haircut,
             morale_shave,
             morale_chat,
             morale_vomited,
             morale_play_with_pet,
             morale_pyromania_startfire,
             morale_pyromania_nearfire,
             morale_pyromania_nofire,
             morale_killer_has_killed,
             morale_killer_need_to_kill,
             morale_perm_filthy,
             morale_butcher,
             morale_gravedigger,
             morale_funeral,
             morale_accomplishment,
             morale_failure,
             morale_perm_numb,
             morale_null
         }
     };
     if( lmt >= 0 && static_cast<size_t>( lmt ) <= legacy_morale_types.size() ) {
         return legacy_morale_types[ lmt ];
     }
     debugmsg( "Requested invalid legacy morale type %d", lmt );
     return legacy_morale_types.front();
 }
References debugmsg, morale_accomplishment, morale_antifruit, morale_antijunk, morale_antiwheat, morale_ate_with_table, morale_ate_without_table, morale_book, morale_butcher, morale_cannibal, morale_chat, morale_cold, morale_comfy, morale_craving_alcohol, morale_craving_caffeine, morale_craving_cocaine, morale_craving_crack, morale_craving_diazepam, morale_craving_marloss, morale_craving_mutagen, morale_craving_nicotine, morale_craving_opiate, morale_craving_speed, morale_dried_off, morale_failure, morale_feeling_bad, morale_feeling_good, morale_food_bad, morale_food_good, morale_food_hot, morale_funeral, morale_game, morale_game_found_kitten, morale_gravedigger, morale_haircut, morale_honey, morale_hot, morale_killed_friend, morale_killed_innocent, morale_killed_monster, morale_killer_has_killed, morale_killer_need_to_kill, morale_lactose, morale_marloss, morale_meatarian, morale_moodswing, morale_music, morale_mutagen, morale_mutagen_chimera, morale_mutagen_elf, morale_mutagen_mutation, morale_mutilate_corpse, morale_no_digest, morale_null, morale_perm_badtemper, morale_perm_constrained, morale_perm_fancy, morale_perm_filthy, morale_perm_hoarder, morale_perm_masochist, morale_perm_nomad, morale_perm_numb, morale_perm_optimist, morale_photos, morale_play_with_pet, morale_pyromania_nearfire, morale_pyromania_nofire, morale_pyromania_startfire, morale_scream, morale_shave, morale_support, morale_sweettooth, morale_vegetarian, morale_vomited, and morale_wet.
Referenced by player_morale::morale_point::deserialize().
describe()
std::string morale_type_data::describe (const itype * it = nullptr) const
Describes this morale type, with item type to replace wildcard with.
Definition at line 320 of file morale_types.cpp.
 {
     if( it ) {
         return string_format( text, it->nname( 1 ) );
     } else {
         // if `msg` contains conversion specification (e.g. %s) but `it` is nullptr,
         // `string_format` will return an error message
         return string_format( text );
     }
 }
References itype::nname(), string_format(), and text.
Referenced by player_morale::morale_point::get_name().
is_permanent()
bool morale_type_data::is_permanent () const inline
Definition at line 27 of file morale_types.h.
{
             return permanent;
         }
References permanent.
load()
void morale_type_data::load (const JsonObject & jo, std::string_view src)
Definition at line 308 of file morale_types.cpp.
 {
     mandatory( jo, was_loaded, "id", id );
     mandatory( jo, was_loaded, "text", text );
     optional( jo, was_loaded, "permanent", permanent, false );
 }
References mandatory, optional(), permanent, text, and was_loaded.
load_type()
void morale_type_data::load_type (const JsonObject & jo, const std::string & src) static
Definition at line 293 of file morale_types.cpp.
 {
     morale_data.load( jo, src );
 }
References anonymous_namespace{morale_types.cpp}::morale_data, and src.
Referenced by DynamicDataLoader::initialize().
reset()
void morale_type_data::reset () static
Definition at line 303 of file morale_types.cpp.
 {
     morale_data.reset();
 }
References anonymous_namespace{morale_types.cpp}::morale_data.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
id
morale_type morale_type_data::id
Definition at line 21 of file morale_types.h.
permanent
bool morale_type_data::permanent = false private
Definition at line 17 of file morale_types.h.
Referenced by is_permanent(), and load().
src
std::vector<std::pair<morale_type, mod_id> > morale_type_data::src
Definition at line 22 of file morale_types.h.
Referenced by load_type().
text
translation morale_type_data::text private
Definition at line 19 of file morale_types.h.
Referenced by describe(), and load().
was_loaded
bool morale_type_data::was_loaded = false
Definition at line 23 of file morale_types.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/morale_types.h
src/morale_types.cpp