Cataclysm DDA: item_pocket::favorite_settings Class Reference
item_pocket::favorite_settings Class Reference
#include <item_pocket.h>
Public Member Functions
void clear ()
void set_priority (int priority)
int priority () const
bool is_null () const
void whitelist_item (const itype_id &id)
void blacklist_item (const itype_id &id)
void clear_item (const itype_id &id)
const cata::flat_set< itype_id > & get_item_whitelist () const
const cata::flat_set< itype_id > & get_item_blacklist () const
const cata::flat_set< item_category_id > & get_category_whitelist () const
const cata::flat_set< item_category_id > & get_category_blacklist () const
void whitelist_category (const item_category_id &id)
void blacklist_category (const item_category_id &id)
void clear_category (const item_category_id &id)
bool accepts_item (const item &it) const
Whether an item passes the current whitelist and blacklist filters.
bool is_collapsed () const
Are pocket contents hidden?
void set_collapse (bool)
Flag to show or hide the pocket contents in 'i'nventory screen.
bool is_disabled () const
void set_disabled (bool)
bool is_unloadable () const
void set_unloadable (bool)
const std::optional< std::string > & get_preset_name () const
void set_preset_name (const std::string &)
void set_was_edited ()
bool was_edited () const
void info (std::vector< iteminfo > &info) const
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
Private Attributes
std::optional< std::string > preset_name
int priority_rating = 0
cata::flat_set< itype_id > item_whitelist
cata::flat_set< itype_id > item_blacklist
cata::flat_set< item_category_id > category_whitelist
cata::flat_set< item_category_id > category_blacklist
bool collapsed = false
bool disabled = false
bool unload = true
bool player_edited = false
Detailed Description
Definition at line 63 of file item_pocket.h.
Member Function Documentation
accepts_item()
bool item_pocket::favorite_settings::accepts_item (const item & it) const
Whether an item passes the current whitelist and blacklist filters.
Check to see if the given item is accepted by this pocket based on player configured rules.
The rules are defined in two list:
whitelist - when one or more items are on the list then only those items are accepted.
blacklist - those items listed here are never accepted.
When a whitelist is empty and the item is not blacklisted then it will be accepted. Container items will be accepted only when all items inside are accepted.
Note that the rules take into account both item id and category which have to be accepted by the rules outlined above for an item to be accepted.
Parameters
it item to check.
Returns
true if the item is accepted by this pocket, false otherwise.
See also
item_pocket::favorite_settings::accepts_container(const item&)
Definition at line 2620 of file item_pocket.cpp.
 {
     // if this pocket is disabled it accepts nothing
     if( disabled ) {
         return false;
     }
     const itype_id &id = it.typeId();
     const item_category_id &cat = category_blacklist.empty() && category_whitelist.empty()
                                   ? item_category_id{} :
                                   it.get_category_of_contents().id;
     // if the item is explicitly listed in either of the lists, then it's clear what to do with it
     if( item_blacklist.count( id ) ) {
         return false;
     }
     if( item_whitelist.count( id ) ) {
         return true;
     }
     // otherwise check the category, the same way
     if( category_blacklist.count( cat ) ) {
         return false;
     }
     if( category_whitelist.count( cat ) ) {
         return true;
     }
     // when the item is container then we are actually checking if pocket accepts
     // container content and not the container itself unless container is blacklisted
     if( it.is_container() && !it.empty_container() ) {
         const std::list<const item *> items = it.all_items_top();
         return std::all_of( items.begin(), items.end(), [this]( const item * it ) {
             return accepts_item( *it );
         } );
     }
     // finally, if no match was found, see if there were any filters at all,
     // and either allow or deny everything that's fallen through to here.
     if( !category_whitelist.empty() ) {
         return false;  // we've whitelisted only some categories, and this item is not out of those.
     }
     if( !item_whitelist.empty() && category_blacklist.empty() ) {
         // whitelisting only certain items, and not as a means to tweak blacklist.
         return false;
     }
     // no whitelist - everything goes.
     return true;
 }
References item::all_items_top(), item::empty_container(), item::get_category_of_contents(), item_category::id, item::is_container(), item_blacklist, and item::typeId().
Referenced by item_pocket::best_pocket_in_contents(), item_pocket::better_pocket(), and item_pocket::fill_with().
blacklist_category()
void item_pocket::favorite_settings::blacklist_category (const item_category_id & id)
Definition at line 2582 of file item_pocket.cpp.
 {
     // blacklisting twice removes the category from the list
     if( category_blacklist.count( id ) ) {
         category_blacklist.erase( id );
         return;
     }
     // remove the category from the whitelist if listed
     if( category_whitelist.count( id ) ) {
         category_whitelist.erase( id );
     }
     category_blacklist.insert( id );
 }
Referenced by pocket_favorite_callback::key().
blacklist_item()
void item_pocket::favorite_settings::blacklist_item (const itype_id & id)
Definition at line 2526 of file item_pocket.cpp.
 {
     // blacklisting twice removes the item from the list
     if( item_blacklist.count( id ) ) {
         item_blacklist.erase( id );
         return;
     }
     // remove the item from the whitelist if listed
     if( item_whitelist.count( id ) ) {
         item_whitelist.erase( id );
     }
     item_blacklist.insert( id );
 }
References item_blacklist.
Referenced by pocket_favorite_callback::key().
clear()
void item_pocket::favorite_settings::clear ()
Definition at line 2490 of file item_pocket.cpp.
 {
     preset_name = std::nullopt;
     priority_rating = 0;
     item_whitelist.clear();
     item_blacklist.clear();
     category_whitelist.clear();
     category_blacklist.clear();
 }
References category_blacklist, category_whitelist, item_blacklist, item_whitelist, preset_name, and priority_rating.
Referenced by item_pocket::deserialize().
clear_category()
void item_pocket::favorite_settings::clear_category (const item_category_id & id)
Definition at line 2596 of file item_pocket.cpp.
 {
     category_blacklist.erase( id );
     category_whitelist.erase( id );
 }
clear_item()
void item_pocket::favorite_settings::clear_item (const itype_id & id)
Definition at line 2540 of file item_pocket.cpp.
 {
     item_whitelist.erase( id );
     item_blacklist.erase( id );
 }
References item_blacklist.
deserialize()
void item_pocket::favorite_settings::deserialize (const JsonObject & data)
Definition at line 291 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     if( data.has_member( "name" ) ) {
         data.read( "name", preset_name );
     }
     data.read( "priority", priority_rating );
     data.read( "item_whitelist", item_whitelist );
     data.read( "item_blacklist", item_blacklist );
     data.read( "category_whitelist", category_whitelist );
     data.read( "category_blacklist", category_blacklist );
     if( data.has_member( "collapsed" ) ) {
         data.read( "collapsed", collapsed );
     }
     if( data.has_member( "disabled" ) ) {
         data.read( "disabled", disabled );
     }
     if( data.has_member( "unload" ) ) {
         data.read( "unload", unload );
     }
     if( data.has_member( "player_edited" ) ) {
         data.read( "player_edited", player_edited );
     } else {
         player_edited = true;
     }
 }
References item_pocket::data, item_blacklist, and avatar_action::unload().
Referenced by item_pocket::deserialize_presets().
get_category_blacklist()
const cata::flat_set< item_category_id > & item_pocket::favorite_settings::get_category_blacklist () const
Definition at line 2563 of file item_pocket.cpp.
 {
     return category_blacklist;
 }
Referenced by pocket_favorite_callback::key().
get_category_whitelist()
const cata::flat_set< item_category_id > & item_pocket::favorite_settings::get_category_whitelist () const
Definition at line 2557 of file item_pocket.cpp.
 {
     return category_whitelist;
 }
Referenced by item_pocket::better_pocket(), and pocket_favorite_callback::key().
get_item_blacklist()
const cata::flat_set< itype_id > & item_pocket::favorite_settings::get_item_blacklist () const
Definition at line 2551 of file item_pocket.cpp.
 {
     return item_blacklist;
 }
References item_blacklist.
Referenced by pocket_favorite_callback::key().
get_item_whitelist()
const cata::flat_set< itype_id > & item_pocket::favorite_settings::get_item_whitelist () const
Definition at line 2546 of file item_pocket.cpp.
 {
     return item_whitelist;
 }
Referenced by item_pocket::better_pocket(), and pocket_favorite_callback::key().
get_preset_name()
const std::optional< std::string > & item_pocket::favorite_settings::get_preset_name () const
Definition at line 2713 of file item_pocket.cpp.
 {
     return preset_name;
 }
info()
void item_pocket::favorite_settings::info (std::vector< iteminfo > & info) const
Definition at line 2728 of file item_pocket.cpp.
 {
     if( disabled ) {
         info.emplace_back( "BASE", string_format(
                                _( "Items <bad>won't be inserted</bad> into this pocket unless you manually insert them." ) ) );
     }
     if( !unload ) {
         info.emplace_back( "BASE", string_format(
                                _( "Items in this pocket <bad>won't be unloaded</bad> unless you manually drop them." ) ) );
     }
     if( preset_name.has_value() ) {
         info.emplace_back( "BASE", string_format( _( "Preset Name: %s" ), preset_name.value() ) );
     }
     info.emplace_back( "BASE", string_format( "%s %d", _( "Priority:" ), priority_rating ) );
     info.emplace_back( "BASE", string_format( _( "Item Whitelist: %s" ),
                        item_whitelist.empty() ? _( "(empty)" ) :
     enumerate_as_string( item_whitelist.begin(), item_whitelist.end(), []( const itype_id & id ) {
         return id->nname( 1 );
     } ) ) );
     info.emplace_back( "BASE", string_format( _( "Item Blacklist: %s" ),
                        item_blacklist.empty() ? _( "(empty)" ) :
     enumerate_as_string( item_blacklist.begin(), item_blacklist.end(), []( const itype_id & id ) {
         return id->nname( 1 );
     } ) ) );
     info.emplace_back( "BASE", string_format( _( "Category Whitelist: %s" ),
                        category_whitelist.empty() ? _( "(empty)" ) : enumerate( category_whitelist ) ) );
     info.emplace_back( "BASE", string_format( _( "Category Blacklist: %s" ),
                        category_blacklist.empty() ? _( "(empty)" ) : enumerate( category_blacklist ) ) );
 }
References _, enumerate(), enumerate_as_string(), item_blacklist, string_format(), and avatar_action::unload().
Referenced by item_pocket::favorite_info().
is_collapsed()
bool item_pocket::favorite_settings::is_collapsed () const
Are pocket contents hidden?
Definition at line 2668 of file item_pocket.cpp.
 {
     return collapsed;
 }
Referenced by item::is_collapsed().
is_disabled()
bool item_pocket::favorite_settings::is_disabled () const
Definition at line 2678 of file item_pocket.cpp.
 {
     return disabled;
 }
Referenced by pocket_favorite_callback::key().
is_null()
bool item_pocket::favorite_settings::is_null () const
Definition at line 2505 of file item_pocket.cpp.
 {
     return item_whitelist.empty() && item_blacklist.empty() &&
            category_whitelist.empty() && category_blacklist.empty() &&
            priority() == 0 && !collapsed && !disabled && unload;
 }
References item_blacklist, and avatar_action::unload().
Referenced by item_pocket::is_default_state(), and item_pocket::serialize().
is_unloadable()
bool item_pocket::favorite_settings::is_unloadable () const
Definition at line 2688 of file item_pocket.cpp.
 {
     return unload;
 }
References avatar_action::unload().
Referenced by item_contents::all_items_top(), and pocket_favorite_callback::key().
priority()
int item_pocket::favorite_settings::priority () const inline
Definition at line 69 of file item_pocket.h.
{
                     return priority_rating;
                 }
References priority_rating.
Referenced by item_pocket::best_pocket_in_contents(), item_pocket::better_pocket(), and pocket_favorite_callback::key().
serialize()
void item_pocket::favorite_settings::serialize (JsonOut & json) const
Definition at line 275 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "name", preset_name );
     json.member( "priority", priority_rating );
     json.member( "item_whitelist", item_whitelist );
     json.member( "item_blacklist", item_blacklist );
     json.member( "category_whitelist", category_whitelist );
     json.member( "category_blacklist", category_blacklist );
     json.member( "collapsed", collapsed );
     json.member( "disabled", disabled );
     json.member( "unload", unload );
     json.member( "player_edited", player_edited );
     json.end_object();
 }
References category_blacklist, category_whitelist, collapsed, disabled, JsonOut::end_object(), item_blacklist, item_whitelist, JsonOut::member(), player_edited, preset_name, priority_rating, JsonOut::start_object(), and unload.
set_collapse()
void item_pocket::favorite_settings::set_collapse (bool flag)
Flag to show or hide the pocket contents in 'i'nventory screen.
Definition at line 2673 of file item_pocket.cpp.
 {
     collapsed = flag;
 }
set_disabled()
void item_pocket::favorite_settings::set_disabled (bool flag)
Definition at line 2683 of file item_pocket.cpp.
 {
     disabled = flag;
 }
Referenced by pocket_favorite_callback::key().
set_preset_name()
void item_pocket::favorite_settings::set_preset_name (const std::string & s)
Definition at line 2698 of file item_pocket.cpp.
 {
     preset_name = s;
 }
set_priority()
void item_pocket::favorite_settings::set_priority (int priority)
Definition at line 2500 of file item_pocket.cpp.
 {
     priority_rating = priority;
 }
Referenced by pocket_favorite_callback::key().
set_unloadable()
void item_pocket::favorite_settings::set_unloadable (bool flag)
Definition at line 2693 of file item_pocket.cpp.
 {
     unload = flag;
 }
References avatar_action::unload().
Referenced by pocket_favorite_callback::key().
set_was_edited()
void item_pocket::favorite_settings::set_was_edited ()
Definition at line 2703 of file item_pocket.cpp.
 {
     player_edited = true;
 }
Referenced by pocket_favorite_callback::key().
was_edited()
bool item_pocket::favorite_settings::was_edited () const
Definition at line 2708 of file item_pocket.cpp.
 {
     return player_edited;
 }
whitelist_category()
void item_pocket::favorite_settings::whitelist_category (const item_category_id & id)
Definition at line 2568 of file item_pocket.cpp.
 {
     // whitelisting twice removes the category from the list
     if( category_whitelist.count( id ) ) {
         category_whitelist.erase( id );
         return;
     }
     // remove the category from the blacklist if listed
     if( category_blacklist.count( id ) ) {
         category_blacklist.erase( id );
     }
     category_whitelist.insert( id );
 }
Referenced by pocket_favorite_callback::key().
whitelist_item()
void item_pocket::favorite_settings::whitelist_item (const itype_id & id)
Definition at line 2512 of file item_pocket.cpp.
 {
     // whitelisting twice removes the item from the list
     if( item_whitelist.count( id ) ) {
         item_whitelist.erase( id );
         return;
     }
     // remove the item from the blacklist if listed
     if( item_blacklist.count( id ) ) {
         item_blacklist.erase( id );
     }
     item_whitelist.insert( id );
 }
References item_blacklist.
Referenced by pocket_favorite_callback::key().
Member Data Documentation
category_blacklist
cata::flat_set<item_category_id> item_pocket::favorite_settings::category_blacklist private
Definition at line 121 of file item_pocket.h.
Referenced by clear(), and serialize().
category_whitelist
cata::flat_set<item_category_id> item_pocket::favorite_settings::category_whitelist private
Definition at line 120 of file item_pocket.h.
Referenced by clear(), and serialize().
collapsed
bool item_pocket::favorite_settings::collapsed = false private
Definition at line 122 of file item_pocket.h.
Referenced by serialize().
disabled
bool item_pocket::favorite_settings::disabled = false private
Definition at line 123 of file item_pocket.h.
Referenced by serialize().
item_blacklist
cata::flat_set<itype_id> item_pocket::favorite_settings::item_blacklist private
Definition at line 119 of file item_pocket.h.
Referenced by clear(), and serialize().
item_whitelist
cata::flat_set<itype_id> item_pocket::favorite_settings::item_whitelist private
Definition at line 118 of file item_pocket.h.
Referenced by clear(), and serialize().
player_edited
bool item_pocket::favorite_settings::player_edited = false private
Definition at line 125 of file item_pocket.h.
Referenced by serialize().
preset_name
std::optional<std::string> item_pocket::favorite_settings::preset_name private
Definition at line 116 of file item_pocket.h.
Referenced by clear(), and serialize().
priority_rating
int item_pocket::favorite_settings::priority_rating = 0 private
Definition at line 117 of file item_pocket.h.
Referenced by clear(), priority(), and serialize().
unload
bool item_pocket::favorite_settings::unload = true private
Definition at line 124 of file item_pocket.h.
Referenced by serialize().
The documentation for this class was generated from the following files:
src/item_pocket.h
src/item_pocket.cpp
src/savegame_json.cpp