Cataclysm DDA: clear_rubble_activity_actor Class Reference
clear_rubble_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
clear_rubble_activity_actor ()=default
clear_rubble_activity_actor (int moves)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves
Detailed Description
Definition at line 1912 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
clear_rubble_activity_actor() [1/2]
clear_rubble_activity_actor::clear_rubble_activity_actor () default
clear_rubble_activity_actor() [2/2]
clear_rubble_activity_actor::clear_rubble_activity_actor (int moves) inline explicit
Definition at line 1916 of file activity_actor_definitions.h.
 : moves( moves ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> clear_rubble_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1926 of file activity_actor_definitions.h.
{
             return std::make_unique<clear_rubble_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > clear_rubble_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6537 of file activity_actor.cpp.
 {
     clear_rubble_activity_actor actor( {} );
     JsonObject data = jsin.get_object();
     data.read( "moves", actor.moves );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void clear_rubble_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1923 of file activity_actor_definitions.h.
 {}
finish()
void clear_rubble_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 6516 of file activity_actor.cpp.
 {
     map &here = get_map();
     const tripoint_bub_ms &pos = here.bub_from_abs( act.placement );
     who.add_msg_if_player( m_info, _( "You clear up the %s." ), here.furnname( pos ) );
     here.furn_set( pos, furn_str_id::NULL_ID() );
     act.set_to_null();
     here.maybe_trigger_trap( pos, who, true );
 }
References _, act, Character::add_msg_if_player(), map::bub_from_abs(), map::furn_set(), map::furnname(), get_map(), m_info, map::maybe_trigger_trap(), string_id< furn_t >::NULL_ID(), and math_opers::pos().
get_type()
activity_id clear_rubble_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1918 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_CLEAR_RUBBLE" );
         }
References activity_id.
serialize()
void clear_rubble_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6528 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves", moves );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves, and JsonOut::start_object().
start()
void clear_rubble_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 6510 of file activity_actor.cpp.
 {
     act.moves_total = moves;
     act.moves_left = moves;
 }
References act, and moves.
Member Data Documentation
moves
int clear_rubble_activity_actor::moves private
Definition at line 1934 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp