Cataclysm DDA: recipe_result_info_cache Class Reference
recipe_result_info_cache Class Reference
Public Member Functions
recipe_result_info_cache (Character &_crafter)
item_info_data get_result_data (const recipe *rec, int batch_size, int &scroll_pos, const catacurses::window &window)
Private Member Functions
void get_byproducts_data (const recipe *rec, std::vector< iteminfo > &summary_info, std::vector< iteminfo > &details_info)
void get_item_details (item &dummy_item, int quantity_per_batch, std::vector< iteminfo > &details_info, const std::string &classification, bool uses_charges, const std::string &description=std::string())
void get_item_header (item &dummy_item, int quantity_per_batch, std::vector< iteminfo > &info, const std::string &classification, bool uses_charges, const std::string &description=std::string())
void insert_iteminfo_block_separator (std::vector< iteminfo > &info_vec, const std::string &title) const
Private Attributes
Character & crafter
std::vector< iteminfo > info
const recipe * last_recipe = nullptr
int last_terminal_width = 0
int panel_width
int cached_batch_size = 1
int lang_version = 0
Detailed Description
Definition at line 626 of file crafting_gui.cpp.
Constructor & Destructor Documentation
recipe_result_info_cache()
recipe_result_info_cache::recipe_result_info_cache (Character & _crafter) inline explicit
Definition at line 647 of file crafting_gui.cpp.
 : crafter( _crafter ) {};
Member Function Documentation
get_byproducts_data()
void recipe_result_info_cache::get_byproducts_data (const recipe * rec, std::vector< iteminfo > & summary_info, std::vector< iteminfo > & details_info) private
Definition at line 652 of file crafting_gui.cpp.
 {
     const std::string byproduct_string = _( "Byproduct" );
     for( const std::pair<const itype_id, int> &bp : rec->get_byproducts() ) {
         insert_iteminfo_block_separator( details_info, byproduct_string );
         item dummy_item = item( bp.first );
         bool uses_charges = dummy_item.count_by_charges();
         get_item_header( dummy_item, bp.second, summary_info, _( "With byproduct" ), uses_charges );
         get_item_details( dummy_item, bp.second, details_info, byproduct_string, uses_charges );
     }
 }
References _, bp, item::count_by_charges(), recipe::get_byproducts(), get_item_details(), get_item_header(), insert_iteminfo_block_separator(), and item.
Referenced by get_result_data().
get_item_details()
void recipe_result_info_cache::get_item_details (item & dummy_item, int quantity_per_batch, std::vector< iteminfo > & details_info, const std::string & classification, bool uses_charges, const std::string & description = std::string()) private
Definition at line 666 of file crafting_gui.cpp.
 {
     std::vector<iteminfo> temp_info;
     int total_quantity = quantity_per_batch * cached_batch_size;
     get_item_header( dummy_item, quantity_per_batch, details_info, classification, uses_charges,
                      description );
     if( uses_charges ) {
         dummy_item.charges *= total_quantity;
         dummy_item.info( true, temp_info );
         dummy_item.charges /= total_quantity;
     } else {
         dummy_item.info( true, temp_info, total_quantity );
     }
     details_info.insert( std::end( details_info ), std::begin( temp_info ), std::end( temp_info ) );
 }
References cached_batch_size, item::charges, keycode::end, get_item_header(), and item::info().
Referenced by get_byproducts_data(), and get_result_data().
get_item_header()
void recipe_result_info_cache::get_item_header (item & dummy_item, int quantity_per_batch, std::vector< iteminfo > & info, const std::string & classification, bool uses_charges, const std::string & description = std::string()) private
Definition at line 684 of file crafting_gui.cpp.
 {
     int total_quantity = quantity_per_batch * cached_batch_size;
     //Handle multiple charges and multiple discrete items separately
     if( uses_charges ) {
         std::string display_name = ( description.empty() ? dummy_item.display_name() : description );
         dummy_item.charges = total_quantity;
         info.emplace_back( "DESCRIPTION",
                            "<bold>" + classification + ": </bold>" + display_name );
         //Reset charges so that multiple calls to this function don't produce unexpected results
         dummy_item.charges /= total_quantity;
     } else {
         std::string display_name = ( description.empty() ? dummy_item.display_name(
                                          total_quantity ) : description );
         //Add summary line.  Don't need to indicate count if there's only 1
         info.emplace_back( "DESCRIPTION",
                            "<bold>" + classification + ": </bold>" + display_name +
                            ( total_quantity == 1 ? "" : string_format( " (%d)", total_quantity ) ) );
     }
     if( dummy_item.has_flag( flag_VARSIZE ) &&
         dummy_item.has_flag( flag_FIT ) ) {
         /* Resulting item can be (poor fit).  Check if it can actually be crafted as poor fit
          * Currently, that means: can it have poorly-fitted components?*/
         std::vector<std::vector<item_comp> > item_component_reqs =
             last_recipe->simple_requirements().get_components();
         bool has_varsize_components = false;
         for( const std::vector<item_comp> &component_options : item_component_reqs ) {
             for( const item_comp &component : component_options ) {
                 const itype *type = item::find_type( component.type );
                 if( type->has_flag( flag_VARSIZE ) ) {
                     has_varsize_components = true;
                     break;
                 }
             }
             if( has_varsize_components ) {
                 break;
             }
         }
         if( has_varsize_components ) {
             info.emplace_back( "DESCRIPTION",
                                _( "<bold>Note:</bold> If crafted from poorly-fitting components, the resulting item may also be poorly-fitted." ) );
         }
     }
 }
References _, cached_batch_size, item::charges, item::display_name(), item::find_type(), flag_FIT, flag_VARSIZE, requirement_data::get_components(), item::has_flag(), info, last_recipe, recipe::simple_requirements(), string_format(), type, and component::type.
Referenced by get_byproducts_data(), get_item_details(), and get_result_data().
get_result_data()
item_info_data recipe_result_info_cache::get_result_data (const recipe * rec, int batch_size, int & scroll_pos, const catacurses::window & window)
Definition at line 755 of file crafting_gui.cpp.
 {
     //lang check here is needed to rebuild cache when using "Toggle language to English" option
     if( lang_version == detail::get_current_language_version() ) {
         /* If the recipe has not changed, return the cached version in info.
            Unfortunately, the separator lines are baked into info at a specific width, so if the terminal width
            has changed, the info needs to be regenerated */
         if( rec == last_recipe
             && rec != nullptr
             && TERMX == last_terminal_width
             && batch_size == cached_batch_size
           ) {
             item_info_data data( "", "", info, {}, scroll_pos );
             return data;
         }
     } else {
         lang_version = detail::get_current_language_version();
     }
     cached_batch_size = batch_size;
     last_recipe = rec;
     scroll_pos = 0;
     last_terminal_width = TERMX;
     panel_width = getmaxx( window );
     info.clear(); //New recipe, new info
     /*We need to do some calculations to put together the results summary and very similar calculations to
       put together the details, so, have a separate vector specifically for the details, to be appended later */
     std::vector<iteminfo> details_info;
     //Make a temporary item for the result.  NOTE: If the result would normally be in a container, this is not.
     item dummy_result = get_recipe_result_item( *rec, crafter );
     std::string result_description;
     if( dummy_result.is_null() ) {
         result_description = rec->description.translated();
     }
     bool result_uses_charges = dummy_result.count_by_charges();
     int const makes_amount = rec->makes_amount();
     item dummy_container;
     //Several terms are used repeatedly in headers/descriptions, list them here for a single entry/translation point
     const std::string result_string = _( "Result" );
     const std::string recipe_output_string = _( "Recipe Outputs" );
     const std::string recipe_result_string = _( "Recipe Result" );
     const std::string container_string = _( "Container" );
     // Every learnable recipe in a container is sealed.
     const std::string in_container_string = _( "In sealed container" );
     const std::string container_info_string = _( "Container Information" );
     //Set up summary at top so people know they can look further to learn about byproducts and such
     //First, see if we need it at all:
     if( rec->container_id() == itype_id::NULL_ID() && !rec->has_byproducts() ) {
         //We don't need a summary for a single item, just give us the details
         insert_iteminfo_block_separator( details_info, recipe_result_string );
         get_item_details( dummy_result, makes_amount, details_info, result_string, result_uses_charges,
                           result_description );
     } else { //We do need a summary
         //Top of the header
         insert_iteminfo_block_separator( info, recipe_output_string );
         //If the primary result uses charges and is in a container, need to calculate number of charges
         //If it's in a container, focus on the contents
         if( rec->container_id() != itype_id::NULL_ID() ) {
             dummy_container = item( rec->container_id(), calendar::turn, item::default_charges_tag{} );
             //Put together the summary in info:
             get_item_header( dummy_result, makes_amount, info, recipe_result_string, result_uses_charges );
             get_item_header( dummy_container, 1, info, in_container_string,
                              false ); //Seems reasonable to assume a container won't use charges
             //Put together the details in details_info:
             insert_iteminfo_block_separator( details_info, recipe_result_string );
             get_item_details( dummy_result, makes_amount, details_info, recipe_result_string,
                               result_uses_charges );
             insert_iteminfo_block_separator( details_info, container_info_string );
             get_item_details( dummy_container, 1, details_info, container_string, false );
         } else { //If it's not in a container, just tell us about the item
             //Add a line to the summary:
             get_item_header( dummy_result, makes_amount, info, recipe_result_string, result_uses_charges );
             //Add the details 'header'
             insert_iteminfo_block_separator( details_info, recipe_result_string );
             //Get the item details:
             get_item_details( dummy_result, makes_amount, details_info, recipe_result_string,
                               result_uses_charges );
         }
         if( rec->has_byproducts() ) {
             get_byproducts_data( rec, info, details_info );
         }
         info.emplace_back( "DESCRIPTION", "  " );  //Blank line for formatting
     }
     //Merge summary and details
     info.insert( std::end( info ), std::begin( details_info ), std::end( details_info ) );
     item_info_data data( "", "", info, {}, scroll_pos );
     return data;
 }
References _, cached_batch_size, recipe::container_id(), item::count_by_charges(), crafter, recipe::description, keycode::end, get_byproducts_data(), detail::get_current_language_version(), get_item_details(), get_item_header(), get_recipe_result_item(), catacurses::getmaxx(), recipe::has_byproducts(), info, insert_iteminfo_block_separator(), item::is_null(), item, lang_version, last_recipe, last_terminal_width, recipe::makes_amount(), string_id< itype >::NULL_ID(), panel_width, TERMX, translation::translated(), and calendar::turn.
Referenced by select_crafter_and_crafting_recipe().
insert_iteminfo_block_separator()
void recipe_result_info_cache::insert_iteminfo_block_separator (std::vector< iteminfo > & info_vec, const std::string & title) const private
Definition at line 852 of file crafting_gui.cpp.
 {
     info_vec.emplace_back( "DESCRIPTION", "--" );
     info_vec.emplace_back( "DESCRIPTION", std::string( center_text_pos( title, 0,
                            panel_width ), ' ' ) +
                            "<bold>" + title + "</bold>" );
     info_vec.emplace_back( "DESCRIPTION", "--" );
 }
References center_text_pos(), panel_width, and music::title.
Referenced by get_byproducts_data(), and get_result_data().
Member Data Documentation
cached_batch_size
int recipe_result_info_cache::cached_batch_size = 1 private
Definition at line 633 of file crafting_gui.cpp.
Referenced by get_item_details(), get_item_header(), and get_result_data().
crafter
Character& recipe_result_info_cache::crafter private
Definition at line 628 of file crafting_gui.cpp.
Referenced by get_result_data().
info
std::vector<iteminfo> recipe_result_info_cache::info private
Definition at line 629 of file crafting_gui.cpp.
Referenced by get_item_header(), and get_result_data().
lang_version
int recipe_result_info_cache::lang_version = 0 private
Definition at line 634 of file crafting_gui.cpp.
Referenced by get_result_data().
last_recipe
const recipe* recipe_result_info_cache::last_recipe = nullptr private
Definition at line 630 of file crafting_gui.cpp.
Referenced by get_item_header(), and get_result_data().
last_terminal_width
int recipe_result_info_cache::last_terminal_width = 0 private
Definition at line 631 of file crafting_gui.cpp.
Referenced by get_result_data().
panel_width
int recipe_result_info_cache::panel_width private
Definition at line 632 of file crafting_gui.cpp.
Referenced by get_result_data(), and insert_iteminfo_block_separator().
The documentation for this class was generated from the following file:
src/crafting_gui.cpp