Cataclysm DDA: jmapgen_furniture Class Reference
jmapgen_furniture Class Reference
Place a furniture.
Public Member Functions
jmapgen_furniture (const JsonObject &jsi, const std::string_view)
jmapgen_furniture (const JsonValue &fid)
mapgen_phase phase () const override
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &context) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
Public Attributes
mapgen_value< furn_id > id
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a furniture.
"furn": id of the furniture.
Definition at line 2873 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_furniture() [1/2]
jmapgen_furniture::jmapgen_furniture (const JsonObject & jsi, const std::string_view) inline
Definition at line 2877 of file mapgen.cpp.
                                                                           :
             jmapgen_furniture( jsi.get_member( "furn" ) ) {}
jmapgen_furniture() [2/2]
jmapgen_furniture::jmapgen_furniture (const JsonValue & fid) inline explicit
Definition at line 2879 of file mapgen.cpp.
 : id( fid ) {}
Member Function Documentation
apply()
void jmapgen_furniture::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2883 of file mapgen.cpp.
{
             furn_id chosen_id = id.get( dat );
             if( chosen_id.id().is_null() ) {
                 return;
             }
             if( !dat.m.furn_set( tripoint( x.get(), y.get(), dat.zlevel() + z.get() ), chosen_id ) ) {
                 debugmsg( "Problem setting furniture in %s", context );
             }
         }
References context, debugmsg, map::furn_set(), jmapgen_int::get(), int_id< T >::id(), string_id< T >::is_null(), mapgendata::m, and mapgendata::zlevel().
check()
void jmapgen_furniture::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 2897 of file mapgen.cpp.
{
             id.check( oter_name, parameters );
         }
has_vehicle_collision()
bool jmapgen_furniture::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2893 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint_bub_ms( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
phase()
mapgen_phase jmapgen_furniture::phase () const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2880 of file mapgen.cpp.
{
             return mapgen_phase::furniture;
         }
References furniture.
Member Data Documentation
id
mapgen_value<furn_id> jmapgen_furniture::id
Definition at line 2876 of file mapgen.cpp.
The documentation for this class was generated from the following file:
src/mapgen.cpp