Cataclysm DDA: input_manager Class Reference
input_manager Class Reference
Manages the translation from action IDs to associated input.
#include <input.h>
Public Member Functions
const std::vector< input_event > & get_input_for_action (const std::string &action_descriptor, const std::string &context="default", bool *overwrites_default=nullptr)
Get the input events associated with an action ID in a given context.
int get_first_char_for_action (const std::string &action_descriptor, const std::string &context="default")
Return first char associated with an action ID in a given context.
void init ()
Initializes the input manager, aka loads the input mapping configuration JSON.
void save ()
Opposite of init, save the data that has been loaded by init, and possibly been modified.
int get_previously_pressed_key () const
Return the previously pressed key, or 0 if there is no previous input or the previous input wasn't a key.
int get_keycode (input_event_t inp_type, const std::string &name) const
Get the keycode associated with the given key name.
std::string get_keyname (int ch, input_event_t inp_type, bool portable=false) const
Get the key name associated with the given keyboard keycode.
input_event get_input_event (keyboard_mode preferred_keyboard_mode=keyboard_mode::keycode)
curses getch() replacement.
void pump_events ()
Resize & refresh if necessary, process all pending window events, and ignore keypresses.
void wait_for_any_key ()
Wait until the user presses a key.
void set_timeout (int delay)
Sets global input polling timeout in milliseconds as appropriate for the current interface system.
void reset_timeout ()
int get_timeout () const
Static Public Member Functions
static keyboard_mode actual_keyboard_mode (keyboard_mode preferred_keyboard_mode)
Private Types
using t_input_event_list = std::vector< input_event >
using t_actions = std::map< std::string, action_attributes >
using t_action_contexts = std::map< std::string, t_actions >
using t_key_to_name_map = std::map< int, std::string >
using t_name_to_key_map = std::map< std::string, int >
Private Member Functions
void init_keycode_mapping ()
void add_keyboard_char_keycode_pair (int ch, const std::string &name)
void add_keyboard_code_keycode_pair (int ch, const std::string &name)
void add_gamepad_keycode_pair (int ch, const std::string &name)
void add_mouse_keycode_pair (MouseInput mouse_input, const std::string &name)
void load (const cata_path &file_name, bool is_user_preferences)
Load keybindings from a json file, override existing bindings.
t_input_event_list & get_or_create_event_list (const std::string &action_descriptor, const std::string &context)
bool remove_input_for_action (const std::string &action_descriptor, const std::string &context)
void add_input_for_action (const std::string &action_descriptor, const std::string &context, const input_event &event)
const action_attributes & get_action_attributes (const std::string &action_id, const std::string &context="default", bool *overwrites_default=nullptr, bool use_basic_action_contexts=false)
Get the attributes of the action associated with an action ID by searching the given context and the default context.
translation get_default_action_name (const std::string &action_id) const
Get a value to be used as the default name for a newly created action.
Private Attributes
t_action_contexts action_contexts
t_action_contexts basic_action_contexts
called basic rather than default to not confuse default context basic means default keybindings (without user changes)
t_key_to_name_map keyboard_char_keycode_to_keyname
t_key_to_name_map keyboard_code_keycode_to_keyname
t_key_to_name_map gamepad_keycode_to_keyname
t_key_to_name_map mouse_keycode_to_keyname
t_name_to_key_map keyboard_char_keyname_to_keycode
t_name_to_key_map keyboard_code_keyname_to_keycode
t_name_to_key_map gamepad_keyname_to_keycode
t_name_to_key_map mouse_keyname_to_keycode
int previously_pressed_key
int input_timeout
Friends
class keybindings_ui
class input_context
Detailed Description
Manages the translation from action IDs to associated input.
Planned methods of input:
Single key press: a
Multi-key combination: `a
Gamepad button: A
Definition at line 201 of file input.h.
Member Typedef Documentation
t_action_contexts
using input_manager::t_action_contexts = std::map<std::string, t_actions> private
Definition at line 293 of file input.h.
t_actions
using input_manager::t_actions = std::map<std::string, action_attributes> private
Definition at line 292 of file input.h.
t_input_event_list
using input_manager::t_input_event_list = std::vector<input_event> private
Definition at line 291 of file input.h.
t_key_to_name_map
using input_manager::t_key_to_name_map = std::map<int, std::string> private
Definition at line 301 of file input.h.
t_name_to_key_map
using input_manager::t_name_to_key_map = std::map<std::string, int> private
Definition at line 306 of file input.h.
Member Function Documentation
actual_keyboard_mode()
keyboard_mode input_manager::actual_keyboard_mode (keyboard_mode preferred_keyboard_mode) static
Definition at line 916 of file input.cpp.
 {
     switch( preferred_keyboard_mode ) {
         case keyboard_mode::keycode:
             return is_keycode_mode_supported() ? keyboard_mode::keycode : keyboard_mode::keychar;
         case keyboard_mode::keychar:
             return keyboard_mode::keychar;
     }
     return keyboard_mode::keychar;
 }
References is_keycode_mode_supported(), keychar, and keycode.
Referenced by hotkey_from_char(), and input_context::is_event_type_enabled().
add_gamepad_keycode_pair()
void input_manager::add_gamepad_keycode_pair (int ch, const std::string & name) private
Definition at line 476 of file input.cpp.
 {
     gamepad_keycode_to_keyname[ch] = name;
     gamepad_keyname_to_keycode[name] = ch;
 }
References gamepad_keycode_to_keyname, gamepad_keyname_to_keycode, and om_direction::name().
Referenced by init_keycode_mapping().
add_input_for_action()
void input_manager::add_input_for_action (const std::string & action_descriptor, const std::string & context, const input_event & event) private
Definition at line 876 of file input.cpp.
 {
     t_input_event_list &events = get_or_create_event_list( action_descriptor, context );
     for( input_event &events_a : events ) {
         if( events_a == event ) {
             return;
         }
     }
     events.push_back( event );
 }
References context, and get_or_create_event_list().
Referenced by input_context::action_add(), input_context::action_reset(), and init().
add_keyboard_char_keycode_pair()
void input_manager::add_keyboard_char_keycode_pair (int ch, const std::string & name) private
Definition at line 464 of file input.cpp.
 {
     keyboard_char_keycode_to_keyname[ch] = name;
     keyboard_char_keyname_to_keycode[name] = ch;
 }
References keyboard_char_keycode_to_keyname, keyboard_char_keyname_to_keycode, and om_direction::name().
Referenced by init_keycode_mapping().
add_keyboard_code_keycode_pair()
void input_manager::add_keyboard_code_keycode_pair (int ch, const std::string & name) private
Definition at line 470 of file input.cpp.
 {
     keyboard_code_keycode_to_keyname[ch] = name;
     keyboard_code_keyname_to_keycode[name] = ch;
 }
References keyboard_code_keycode_to_keyname, keyboard_code_keyname_to_keycode, and om_direction::name().
Referenced by init_keycode_mapping().
add_mouse_keycode_pair()
void input_manager::add_mouse_keycode_pair (MouseInput mouse_input, const std::string & name) private
Definition at line 482 of file input.cpp.
 {
     mouse_keycode_to_keyname[static_cast<int>( mouse_input )] = name;
     mouse_keyname_to_keycode[name] = static_cast<int>( mouse_input );
 }
References mouse_keycode_to_keyname, mouse_keyname_to_keycode, and om_direction::name().
Referenced by init_keycode_mapping().
get_action_attributes()
const action_attributes & input_manager::get_action_attributes (const std::string & action_id, const std::string & context = "default", bool * overwrites_default = nullptr, bool use_basic_action_contexts = false) private
Get the attributes of the action associated with an action ID by searching the given context and the default context.
Parameters
action_id The action ID of the action to find.
context The context in which to get the action. If not found, the "default" context will additionally be checked. Defaults to "default".
overwrites_default If this is non-NULL, this will be used as a return parameter. It will be set to true if the found action was not in the default context. It will be set to false if the found action was in the default context.
use_basic_action_contexts If true, use non-customized keybindings.
Definition at line 771 of file input.cpp.
 {
     t_action_contexts &action_contexts_ref = use_basic_action_contexts
             ? basic_action_contexts
             : action_contexts;
     if( context != default_context_id ) {
         // Check if the action exists in the provided context
         const t_action_contexts::const_iterator action_context = action_contexts_ref.find( context );
         if( action_context != action_contexts_ref.end() ) {
             const t_actions::const_iterator action = action_context->second.find( action_id );
             if( action != action_context->second.end() ) {
                 if( overwrites_default ) {
                     *overwrites_default = true;
                 }
                 return action->second;
             }
         }
     }
     // If not, we use the default binding.
     if( overwrites_default ) {
         *overwrites_default = false;
     }
     t_actions &default_action_context = action_contexts_ref[default_context_id];
     const t_actions::const_iterator default_action = default_action_context.find( action_id );
     if( default_action == default_action_context.end() ) {
         // A new action is created in the event that the requested action is
         // not in the keybindings configuration e.g. the entry is missing.
         default_action_context[action_id].name = get_default_action_name( action_id );
     }
     return default_action_context[action_id];
 }
References action, action_contexts, basic_action_contexts, context, default_context_id(), and get_default_action_name().
Referenced by input_context::action_uses_input(), input_context::display_menu(), keybindings_ui::draw_controls(), input_context::get_action_name(), and get_input_for_action().
get_default_action_name()
translation input_manager::get_default_action_name (const std::string & action_id) const private
Get a value to be used as the default name for a newly created action.
This name should be used as a fallback in cases where it is necessary to create a new action.
Parameters
action_id The action ID of the action.
Returns
If the action ID exists in the default context, the name of that action's name is returned. Otherwise, no_translation(action_id) is returned.
Definition at line 812 of file input.cpp.
 {
     const t_action_contexts::const_iterator default_action_context = action_contexts.find(
                 default_context_id );
     if( default_action_context == action_contexts.end() ) {
         return no_translation( action_id );
     }
     const t_actions::const_iterator default_action = default_action_context->second.find( action_id );
     if( default_action != default_action_context->second.end() ) {
         return default_action->second.name;
     } else {
         return no_translation( action_id );
     }
 }
References action_contexts, default_context_id(), and no_translation().
Referenced by get_action_attributes(), and get_or_create_event_list().
get_first_char_for_action()
int input_manager::get_first_char_for_action (const std::string & action_descriptor, const std::string & context = "default")
Return first char associated with an action ID in a given context.
Definition at line 764 of file input.cpp.
 {
     std::vector<input_event> input_events = get_input_for_action( action_descriptor, context );
     return input_events.empty() ? 0 : input_events[0].get_first_input();
 }
References context, and get_input_for_action().
get_input_event()
input_event input_manager::get_input_event (keyboard_mode preferred_keyboard_mode = keyboard_mode::keycode)
curses getch() replacement.
Defined in the respective platform wrapper, e.g. sdlcurse.cpp
Definition at line 383 of file ncurses_def.cpp.
 {
     if( test_mode ) {
         // input should be skipped in caller's code
         throw std::runtime_error( "input_manager::get_input_event called in test mode" );
     }
     int key = ERR;
     input_event rval;
     do {
         previously_pressed_key = 0;
         // flush any output
         catacurses::doupdate();
         key = getch();
         if( key != ERR ) {
             int newch;
             // Clear the buffer of characters that match the one we're going to act on.
             const int prev_timeout = input_timeout;
             set_timeout( 0 );
             do {
                 newch = wgetch( stdscr );
             } while( newch != ERR && newch == key );
             set_timeout( prev_timeout );
             // If we read a different character than the one we're going to act on, re-queue it.
             if( newch != ERR && newch != key ) {
                 ungetch( newch );
             }
         }
         rval = input_event();
         if( key == ERR ) {
             if( input_timeout > 0 ) {
                 rval.type = input_event_t::timeout;
             } else {
                 rval.type = input_event_t::error;
             }
             // ncurses mouse handling
         } else if( key == KEY_RESIZE ) {
             catacurses::resizeterm();
         } else if( key == KEY_MOUSE ) {
             MEVENT event;
             if( getmouse( &event ) == OK ) {
                 rval.type = input_event_t::mouse;
                 rval.mouse_pos = point( event.x, event.y );
                 if( event.bstate & BUTTON1_CLICKED || event.bstate & BUTTON1_RELEASED ) {
                     rval.add_input( MouseInput::LeftButtonReleased );
                 } else if( event.bstate & BUTTON1_PRESSED ) {
                     rval.add_input( MouseInput::LeftButtonPressed );
                 } else if( event.bstate & BUTTON3_CLICKED || event.bstate & BUTTON3_RELEASED ) {
                     rval.add_input( MouseInput::RightButtonReleased );
                     // If curses version is prepared for a 5-button mouse, enable mousewheel
 #if defined(BUTTON5_PRESSED)
                 } else if( event.bstate & BUTTON4_PRESSED ) {
                     rval.add_input( MouseInput::ScrollWheelUp );
                 } else if( event.bstate & BUTTON5_PRESSED ) {
                     rval.add_input( MouseInput::ScrollWheelDown );
 #endif
                 } else {
                     rval.add_input( MouseInput::Move );
                     if( input_timeout > 0 ) {
                         // Mouse movement seems to clear ncurses timeout
                         set_timeout( input_timeout );
                     }
                 }
             } else {
                 rval.type = input_event_t::error;
             }
         } else {
             if( key == 127 ) { // == Unicode DELETE
                 previously_pressed_key = KEY_BACKSPACE;
                 return input_event( KEY_BACKSPACE, input_event_t::keyboard_char );
             }
             rval.type = input_event_t::keyboard_char;
             rval.text.append( 1, static_cast<char>( key ) );
             // Read the UTF-8 sequence (if any)
             if( key < 127 ) {
                 // Single byte sequence
             } else if( 194 <= key && key <= 223 ) {
                 rval.text.append( 1, static_cast<char>( getch() ) );
             } else if( 224 <= key && key <= 239 ) {
                 rval.text.append( 1, static_cast<char>( getch() ) );
                 rval.text.append( 1, static_cast<char>( getch() ) );
             } else if( 240 <= key && key <= 244 ) {
                 rval.text.append( 1, static_cast<char>( getch() ) );
                 rval.text.append( 1, static_cast<char>( getch() ) );
                 rval.text.append( 1, static_cast<char>( getch() ) );
             } else {
                 // Other control character, etc. - no text at all, return an event
                 // without the text property
                 previously_pressed_key = key;
                 input_event tmp_event( key, input_event_t::keyboard_char );
                 imclient->process_input( &tmp_event );
                 return tmp_event;
             }
             // Now we have loaded an UTF-8 sequence (possibly several bytes)
             // but we should only return *one* key, so return the code point of it.
             const uint32_t cp = UTF8_getch( rval.text );
             if( cp == UNKNOWN_UNICODE ) {
                 // Invalid UTF-8 sequence, this should never happen, what now?
                 // Maybe return any error instead?
                 previously_pressed_key = key;
                 return input_event( key, input_event_t::keyboard_char );
             }
             previously_pressed_key = cp;
             // for compatibility only add the first byte, not the code point
             // as it would  conflict with the special keys defined by ncurses
             rval.add_input( key );
         }
         imclient->process_input( &rval );
     } while( key == KEY_RESIZE );
     return rval;
 }
References input_event::add_input(), catacurses::doupdate(), error, imclient, input_timeout, KEY_BACKSPACE, keyboard_char, LeftButtonPressed, LeftButtonReleased, mouse, input_event::mouse_pos, Move, point, previously_pressed_key, catacurses::resizeterm(), RightButtonReleased, ScrollWheelDown, ScrollWheelUp, set_timeout(), catacurses::stdscr, test_mode, input_event::text, timeout, input_event::type, UNKNOWN_UNICODE, and UTF8_getch().
Referenced by debug_error_prompt(), input_context::handle_input(), anonymous_namespace{animation.cpp}::hit_animation(), and wait_for_any_key().
get_input_for_action()
const std::vector< input_event > & input_manager::get_input_for_action (const std::string & action_descriptor, const std::string & context = "default", bool * overwrites_default = nullptr)
Get the input events associated with an action ID in a given context.
Parameters
action_descriptor The action ID to get the input events for.
context The context in which to get the input events. Defaults to "default".
overwrites_default If this is non-NULL, this will be used as return parameter and will be set to true if the default keybinding is overridden by something else in the given context.
Definition at line 756 of file input.cpp.
 {
     const action_attributes &attributes = get_action_attributes( action_descriptor, context,
                                           overwrites_default );
     return attributes.input_events;
 }
References context, get_action_attributes(), and action_attributes::input_events.
Referenced by input_context::get_available_single_char_hotkeys(), input_context::get_button_text(), input_context::get_desc(), get_first_char_for_action(), input_context::input_to_action(), input_context::keys_bound_to(), input_context::press_x(), and inventory_selector::query_string().
get_keycode()
int input_manager::get_keycode (input_event_t inp_type, const std::string & name) const
Get the keycode associated with the given key name.
Definition at line 662 of file input.cpp.
 {
     const t_name_to_key_map *map = nullptr;
     switch( inp_type ) {
         default:
             break;
         case input_event_t::keyboard_char:
             map = &keyboard_char_keyname_to_keycode;
             break;
         case input_event_t::keyboard_code:
             map = &keyboard_code_keyname_to_keycode;
             break;
         case input_event_t::gamepad:
             map = &gamepad_keyname_to_keycode;
             break;
         case input_event_t::mouse:
             map = &mouse_keyname_to_keycode;
             break;
     }
     if( map ) {
         const auto it = map->find( name );
         if( it != map->end() ) {
             return it->second;
         }
     }
     // Not found in map, try to parse as int
     if( name.compare( 0, 8, "UNKNOWN_" ) == 0 ) {
         return str_to_int( name.substr( 8 ) );
     }
     return 0;
 }
References gamepad, gamepad_keyname_to_keycode, keyboard_char, keyboard_char_keyname_to_keycode, keyboard_code, keyboard_code_keyname_to_keycode, mouse, mouse_keyname_to_keycode, om_direction::name(), and str_to_int().
Referenced by load().
get_keyname()
std::string input_manager::get_keyname (int ch, input_event_t inp_type, bool portable = false) const
Get the key name associated with the given keyboard keycode.
Parameters
ch Character code.
inp_type Whether the keycode is a gamepad or a keyboard code.
portable If true, return a language independent and portable name of the key. This acts as the inverse to get_keyname: get_keyname(get_keycode(a), , true) == a
Definition at line 694 of file input.cpp.
 {
     const t_key_to_name_map *map = nullptr;
     switch( inp_type ) {
         default:
             break;
         case input_event_t::keyboard_char:
             map = &keyboard_char_keycode_to_keyname;
             break;
         case input_event_t::keyboard_code:
             map = &keyboard_code_keycode_to_keyname;
             break;
         case input_event_t::gamepad:
             map = &gamepad_keycode_to_keyname;
             break;
         case input_event_t::mouse:
             map = &mouse_keycode_to_keyname;
             break;
     }
     if( map ) {
         const auto it = map->find( ch );
         if( it != map->end() ) {
             switch( inp_type ) {
                 case input_event_t::keyboard_char:
                     if( IS_F_KEY( ch ) ) {
                         // special case it since F<num> key names are generated using loop
                         // and not marked individually for translation
                         if( portable ) {
                             return it->second;
                         } else {
                             return string_format( pgettext( "function key name", "F%d" ), F_KEY_NUM( ch ) );
                         }
                     } else if( IS_CTRL_CHAR( ch ) && !IS_NAMED_CTRL_CHAR( ch ) ) {
                         if( portable ) {
                             return it->second;
                         } else {
                             return string_format( pgettext( "control key name", "CTRL+%c" ), ch + 64 );
                         }
                     } else if( ch >= char_key_beg && ch <= char_key_end && ch != ' ' ) {
                         // character keys except space need no translation
                         return it->second;
                     }
                     break;
                 case input_event_t::keyboard_code:
                     if( ch >= char_key_beg && ch < char_key_end && ch != ' ' ) {
                         // character keys except space need no translation
                         return it->second;
                     }
                     break;
                 default:
                     break;
             }
             return portable ? it->second : pgettext( "key name", it->second.c_str() );
         }
     }
     if( portable ) {
         return std::string( "UNKNOWN_" ) + int_to_str( ch );
     } else {
         return string_format( _( "unknown key %ld" ), ch );
     }
 }
References _, char_key_beg, char_key_end, F_KEY_NUM(), gamepad, gamepad_keycode_to_keyname, int_to_str(), IS_CTRL_CHAR(), IS_F_KEY(), IS_NAMED_CTRL_CHAR(), keyboard_char, keyboard_char_keycode_to_keyname, keyboard_code, keyboard_code_keycode_to_keyname, mouse, mouse_keycode_to_keyname, pgettext, and string_format().
Referenced by input_event::long_description(), save(), and input_event::short_description().
get_or_create_event_list()
input_manager::t_input_event_list & input_manager::get_or_create_event_list (const std::string & action_descriptor, const std::string & context) private
Definition at line 828 of file input.cpp.
 {
     // A new context is created in the event that the user creates a local
     // keymapping in a context that doesn't yet exist e.g. a context without
     // any pre-existing keybindings.
     t_actions &actions = action_contexts[context];
     // A new action is created in the event that the user creates a local
     // keymapping that masks a global one.
     if( actions.find( action_descriptor ) == actions.end() ) {
         action_attributes &attributes = actions[action_descriptor];
         attributes.name = get_default_action_name( action_descriptor );
         attributes.is_user_created = true;
     }
     return actions[action_descriptor].input_events;
 }
References action_contexts, context, get_default_action_name(), action_attributes::is_user_created, and action_attributes::name.
Referenced by input_context::action_remove(), and add_input_for_action().
get_previously_pressed_key()
int input_manager::get_previously_pressed_key () const
Return the previously pressed key, or 0 if there is no previous input or the previous input wasn't a key.
Definition at line 888 of file input.cpp.
 {
     return previously_pressed_key;
 }
References previously_pressed_key.
get_timeout()
int input_manager::get_timeout () const inline
Definition at line 282 of file input.h.
{
             return input_timeout;
         }
References input_timeout.
Referenced by anonymous_namespace{main.cpp}::exit_handler(), and input_context::handle_input().
init()
void input_manager::init ()
Initializes the input manager, aka loads the input mapping configuration JSON.
Definition at line 163 of file input.cpp.
 {
     std::map<char, action_id> keymap;
     std::string keymap_file_loaded_from;
     std::set<action_id> unbound_keymap;
     load_keyboard_settings( keymap, keymap_file_loaded_from, unbound_keymap );
     init_keycode_mapping();
     reset_timeout();
     try {
         load( PATH_INFO::keybindings(), false );
     } catch( const JsonError &err ) {
         throw std::runtime_error( err.what() );
     }
     try {
         load( PATH_INFO::keybindings_vehicle(), false );
     } catch( const JsonError &err ) {
         throw std::runtime_error( err.what() );
     }
     // save non customized keybindings
     basic_action_contexts = action_contexts;
     try {
         load( PATH_INFO::user_keybindings(), true );
     } catch( const JsonError &err ) {
         throw std::runtime_error( err.what() );
     }
     if( keymap_file_loaded_from.empty() || ( keymap.empty() && unbound_keymap.empty() ) ) {
         // No keymap file was loaded, or the file has no mappings and no unmappings,
         // we can skip the remaining part of the function, especially the save function
         return;
     }
     t_actions &actions = action_contexts["DEFAULTMODE"];
     std::set<action_id> touched;
     for( const std::pair<const char, action_id> &a : keymap ) {
         const std::string action_id = action_ident( a.second );
         // Put the binding from keymap either into the global context
         // (if an action with that ident already exists there - think movement keys)
         // or otherwise to the DEFAULTMODE context.
         std::string context = "DEFAULTMODE";
         if( action_contexts[default_context_id].count( action_id ) > 0 ) {
             context = default_context_id;
         } else if( touched.count( a.second ) == 0 ) {
             // Note: movement keys are somehow special as the default in keymap
             // does not contain the arrow keys, so we don't clear existing keybindings
             // for them.
             // If the keymap contains a binding for this action, erase all the
             // previously (default!) existing bindings, to only keep the bindings,
             // the user is used to
             action_contexts[action_id].clear();
             touched.insert( a.second );
         }
         add_input_for_action( action_id, context, input_event( a.first, input_event_t::keyboard_char ) );
     }
     // Unmap actions that are explicitly not mapped
     for( const action_id &elem : unbound_keymap ) {
         const std::string action_id = action_ident( elem );
         actions[action_id].input_events.clear();
     }
     // Imported old bindings from old keymap file, save those to the new
     // keybindings.json file.
     try {
         save();
     } catch( std::exception &err ) {
         debugmsg( "Could not write imported keybindings: %s", err.what() );
         return;
     }
     // Finally if we did import a file, and saved it to the new keybindings
     // file, delete the old keymap file to prevent re-importing it.
     if( !keymap_file_loaded_from.empty() ) {
         remove_file( keymap_file_loaded_from );
     }
 }
References a, action_contexts, action_ident(), add_input_for_action(), basic_action_contexts, context, debugmsg, default_context_id(), init_keycode_mapping(), PATH_INFO::keybindings(), PATH_INFO::keybindings_vehicle(), keyboard_char, PATH_INFO::keymap(), load(), load_keyboard_settings(), remove_file(), reset_timeout(), save(), and PATH_INFO::user_keybindings().
Referenced by game::load_static_data().
init_keycode_mapping()
void input_manager::init_keycode_mapping () private
Definition at line 491 of file input.cpp.
 {
     // Between space and tilde, all keys more or less map
     // to themselves(see ASCII table)
     for( char c = char_key_beg; c <= char_key_end; c++ ) {
         std::string name( 1, c );
         add_keyboard_char_keycode_pair( c, name );
         add_keyboard_code_keycode_pair( c, name );
     }
     add_keyboard_char_keycode_pair( '\t',          translate_marker_context( "key name", "TAB" ) );
     add_keyboard_char_keycode_pair( KEY_BTAB,      translate_marker_context( "key name", "BACKTAB" ) );
     add_keyboard_char_keycode_pair( ' ',           translate_marker_context( "key name", "SPACE" ) );
     add_keyboard_char_keycode_pair( KEY_UP,        translate_marker_context( "key name", "UP" ) );
     add_keyboard_char_keycode_pair( KEY_DOWN,      translate_marker_context( "key name", "DOWN" ) );
     add_keyboard_char_keycode_pair( KEY_LEFT,      translate_marker_context( "key name", "LEFT" ) );
     add_keyboard_char_keycode_pair( KEY_RIGHT,     translate_marker_context( "key name", "RIGHT" ) );
     add_keyboard_char_keycode_pair( KEY_NPAGE,     translate_marker_context( "key name", "NPAGE" ) );
     add_keyboard_char_keycode_pair( KEY_PPAGE,     translate_marker_context( "key name", "PPAGE" ) );
     add_keyboard_char_keycode_pair( KEY_ESCAPE,    translate_marker_context( "key name", "ESC" ) );
     add_keyboard_char_keycode_pair( KEY_BACKSPACE,
                                     translate_marker_context( "key name", "BACKSPACE" ) );
     add_keyboard_char_keycode_pair( KEY_DC,        translate_marker_context( "key name", "DELETE" ) );
     add_keyboard_char_keycode_pair( KEY_HOME,      translate_marker_context( "key name", "HOME" ) );
     add_keyboard_char_keycode_pair( KEY_BREAK,     translate_marker_context( "key name", "BREAK" ) );
     add_keyboard_char_keycode_pair( KEY_END,       translate_marker_context( "key name", "END" ) );
     add_keyboard_char_keycode_pair( '\n',          translate_marker_context( "key name", "RETURN" ) );
     add_keyboard_char_keycode_pair( KEY_ENTER,
                                     translate_marker_context( "key name", "KEYPAD_ENTER" ) );
     for( int c = 0; IS_CTRL_CHAR( c ); c++ ) {
         // Some codes fall into this range but have more common names we'd prefer to use.
         if( !IS_NAMED_CTRL_CHAR( c ) ) {
             // These are directly translated in `get_keyname()`
             // NOLINTNEXTLINE(cata-translate-string-literal)
             add_keyboard_char_keycode_pair( c, string_format( "CTRL+%c", c + 64 ) );
         }
     }
     // function keys, as defined by ncurses
     for( int i = F_KEY_NUM_BEG; i <= F_KEY_NUM_END; i++ ) {
         // These are directly translated in `get_keyname()`
         // NOLINTNEXTLINE(cata-translate-string-literal)
         add_keyboard_char_keycode_pair( KEY_F( i ), string_format( "F%d", i ) );
     }
     static const std::vector<std::pair<int, std::string>> keyboard_code_keycode_pair = {
         { keycode::backspace, translate_marker_context( "key name", "BACKSPACE" ) },
         { keycode::tab,       translate_marker_context( "key name", "TAB" ) },
         { keycode::return_,   translate_marker_context( "key name", "RETURN" ) },
         { keycode::escape,    translate_marker_context( "key name", "ESC" ) },
         { keycode::space,     translate_marker_context( "key name", "SPACE" ) },
         { keycode::f1,        translate_marker_context( "key name", "F1" ) },
         { keycode::f2,        translate_marker_context( "key name", "F2" ) },
         { keycode::f3,        translate_marker_context( "key name", "F3" ) },
         { keycode::f4,        translate_marker_context( "key name", "F4" ) },
         { keycode::f5,        translate_marker_context( "key name", "F5" ) },
         { keycode::f6,        translate_marker_context( "key name", "F6" ) },
         { keycode::f7,        translate_marker_context( "key name", "F7" ) },
         { keycode::f8,        translate_marker_context( "key name", "F8" ) },
         { keycode::f9,        translate_marker_context( "key name", "F9" ) },
         { keycode::f10,       translate_marker_context( "key name", "F10" ) },
         { keycode::f11,       translate_marker_context( "key name", "F11" ) },
         { keycode::f12,       translate_marker_context( "key name", "F12" ) },
         { keycode::ppage,     translate_marker_context( "key name", "PPAGE" ) },
         { keycode::home,      translate_marker_context( "key name", "HOME" ) },
         { keycode::end,       translate_marker_context( "key name", "END" ) },
         { keycode::npage,     translate_marker_context( "key name", "NPAGE" ) },
         { keycode::right,     translate_marker_context( "key name", "RIGHT" ) },
         { keycode::left,      translate_marker_context( "key name", "LEFT" ) },
         { keycode::down,      translate_marker_context( "key name", "DOWN" ) },
         { keycode::up,        translate_marker_context( "key name", "UP" ) },
         { keycode::kp_divide, translate_marker_context( "key name", "KEYPAD_DIVIDE" ) },
         { keycode::kp_multiply, translate_marker_context( "key name", "KEYPAD_MULTIPLY" ) },
         { keycode::kp_minus,  translate_marker_context( "key name", "KEYPAD_MINUS" ) },
         { keycode::kp_plus,   translate_marker_context( "key name", "KEYPAD_PLUS" ) },
         { keycode::kp_enter,  translate_marker_context( "key name", "KEYPAD_ENTER" ) },
         { keycode::kp_1,      translate_marker_context( "key name", "KEYPAD_1" ) },
         { keycode::kp_2,      translate_marker_context( "key name", "KEYPAD_2" ) },
         { keycode::kp_3,      translate_marker_context( "key name", "KEYPAD_3" ) },
         { keycode::kp_4,      translate_marker_context( "key name", "KEYPAD_4" ) },
         { keycode::kp_5,      translate_marker_context( "key name", "KEYPAD_5" ) },
         { keycode::kp_6,      translate_marker_context( "key name", "KEYPAD_6" ) },
         { keycode::kp_7,      translate_marker_context( "key name", "KEYPAD_7" ) },
         { keycode::kp_8,      translate_marker_context( "key name", "KEYPAD_8" ) },
         { keycode::kp_9,      translate_marker_context( "key name", "KEYPAD_9" ) },
         { keycode::kp_0,      translate_marker_context( "key name", "KEYPAD_0" ) },
         { keycode::kp_period, translate_marker_context( "key name", "KEYPAD_PERIOD" ) },
         { keycode::f13,       translate_marker_context( "key name", "F13" ) },
         { keycode::f14,       translate_marker_context( "key name", "F14" ) },
         { keycode::f15,       translate_marker_context( "key name", "F15" ) },
         { keycode::f16,       translate_marker_context( "key name", "F16" ) },
         { keycode::f17,       translate_marker_context( "key name", "F17" ) },
         { keycode::f18,       translate_marker_context( "key name", "F18" ) },
         { keycode::f19,       translate_marker_context( "key name", "F19" ) },
         { keycode::f20,       translate_marker_context( "key name", "F20" ) },
         { keycode::f21,       translate_marker_context( "key name", "F21" ) },
         { keycode::f22,       translate_marker_context( "key name", "F22" ) },
         { keycode::f23,       translate_marker_context( "key name", "F23" ) },
         { keycode::f24,       translate_marker_context( "key name", "F24" ) },
     };
     for( const auto &v : keyboard_code_keycode_pair ) {
         add_keyboard_code_keycode_pair( v.first, v.second );
     }
     add_gamepad_keycode_pair( JOY_LEFT,      translate_marker_context( "key name", "JOY_LEFT" ) );
     add_gamepad_keycode_pair( JOY_RIGHT,     translate_marker_context( "key name", "JOY_RIGHT" ) );
     add_gamepad_keycode_pair( JOY_UP,        translate_marker_context( "key name", "JOY_UP" ) );
     add_gamepad_keycode_pair( JOY_DOWN,      translate_marker_context( "key name", "JOY_DOWN" ) );
     add_gamepad_keycode_pair( JOY_LEFTUP,    translate_marker_context( "key name", "JOY_LEFTUP" ) );
     add_gamepad_keycode_pair( JOY_LEFTDOWN,  translate_marker_context( "key name", "JOY_LEFTDOWN" ) );
     add_gamepad_keycode_pair( JOY_RIGHTUP,   translate_marker_context( "key name", "JOY_RIGHTUP" ) );
     add_gamepad_keycode_pair( JOY_RIGHTDOWN, translate_marker_context( "key name", "JOY_RIGHTDOWN" ) );
     add_gamepad_keycode_pair( JOY_0,         translate_marker_context( "key name", "JOY_0" ) );
     add_gamepad_keycode_pair( JOY_1,         translate_marker_context( "key name", "JOY_1" ) );
     add_gamepad_keycode_pair( JOY_2,         translate_marker_context( "key name", "JOY_2" ) );
     add_gamepad_keycode_pair( JOY_3,         translate_marker_context( "key name", "JOY_3" ) );
     add_gamepad_keycode_pair( JOY_4,         translate_marker_context( "key name", "JOY_4" ) );
     add_gamepad_keycode_pair( JOY_5,         translate_marker_context( "key name", "JOY_5" ) );
     add_gamepad_keycode_pair( JOY_6,         translate_marker_context( "key name", "JOY_6" ) );
     add_gamepad_keycode_pair( JOY_7,         translate_marker_context( "key name", "JOY_7" ) );
     add_gamepad_keycode_pair( JOY_8,         translate_marker_context( "key name", "JOY_8" ) );
     add_gamepad_keycode_pair( JOY_9,         translate_marker_context( "key name", "JOY_9" ) );
     add_gamepad_keycode_pair( JOY_10,        translate_marker_context( "key name", "JOY_10" ) );
     add_gamepad_keycode_pair( JOY_11,        translate_marker_context( "key name", "JOY_11" ) );
     add_gamepad_keycode_pair( JOY_12,        translate_marker_context( "key name", "JOY_12" ) );
     add_gamepad_keycode_pair( JOY_13,        translate_marker_context( "key name", "JOY_13" ) );
     add_gamepad_keycode_pair( JOY_14,        translate_marker_context( "key name", "JOY_14" ) );
     add_gamepad_keycode_pair( JOY_15,        translate_marker_context( "key name", "JOY_15" ) );
     add_gamepad_keycode_pair( JOY_16,        translate_marker_context( "key name", "JOY_16" ) );
     add_gamepad_keycode_pair( JOY_17,        translate_marker_context( "key name", "JOY_17" ) );
     add_gamepad_keycode_pair( JOY_18,        translate_marker_context( "key name", "JOY_18" ) );
     add_gamepad_keycode_pair( JOY_19,        translate_marker_context( "key name", "JOY_19" ) );
     add_gamepad_keycode_pair( JOY_20,        translate_marker_context( "key name", "JOY_20" ) );
     add_gamepad_keycode_pair( JOY_21,        translate_marker_context( "key name", "JOY_21" ) );
     add_gamepad_keycode_pair( JOY_22,        translate_marker_context( "key name", "JOY_22" ) );
     add_gamepad_keycode_pair( JOY_23,        translate_marker_context( "key name", "JOY_23" ) );
     add_gamepad_keycode_pair( JOY_24,        translate_marker_context( "key name", "JOY_24" ) );
     add_gamepad_keycode_pair( JOY_25,        translate_marker_context( "key name", "JOY_25" ) );
     add_gamepad_keycode_pair( JOY_26,        translate_marker_context( "key name", "JOY_26" ) );
     add_gamepad_keycode_pair( JOY_27,        translate_marker_context( "key name", "JOY_27" ) );
     add_gamepad_keycode_pair( JOY_28,        translate_marker_context( "key name", "JOY_28" ) );
     add_gamepad_keycode_pair( JOY_29,        translate_marker_context( "key name", "JOY_29" ) );
     add_gamepad_keycode_pair( JOY_30,        translate_marker_context( "key name", "JOY_30" ) );
     add_mouse_keycode_pair( MouseInput::LeftButtonPressed,
                             translate_marker_context( "key name", "MOUSE_LEFT_PRESSED" ) );
     add_mouse_keycode_pair( MouseInput::LeftButtonReleased,
                             translate_marker_context( "key name", "MOUSE_LEFT" ) );
     add_mouse_keycode_pair( MouseInput::RightButtonPressed,
                             translate_marker_context( "key name", "MOUSE_RIGHT_PRESSED" ) );
     add_mouse_keycode_pair( MouseInput::RightButtonReleased,
                             translate_marker_context( "key name", "MOUSE_RIGHT" ) );
     add_mouse_keycode_pair( MouseInput::ScrollWheelUp,
                             translate_marker_context( "key name", "SCROLL_UP" ) );
     add_mouse_keycode_pair( MouseInput::ScrollWheelDown,
                             translate_marker_context( "key name", "SCROLL_DOWN" ) );
     add_mouse_keycode_pair( MouseInput::Move,
                             translate_marker_context( "key name", "MOUSE_MOVE" ) );
     add_mouse_keycode_pair( MouseInput::X1ButtonPressed,
                             translate_marker_context( "key name", "MOUSE_BACK_PRESSED" ) );
     add_mouse_keycode_pair( MouseInput::X1ButtonReleased,
                             translate_marker_context( "key name", "MOUSE_BACK" ) );
     add_mouse_keycode_pair( MouseInput::X2ButtonPressed,
                             translate_marker_context( "key name", "MOUSE_FORWARD_PRESSED" ) );
     add_mouse_keycode_pair( MouseInput::X2ButtonReleased,
                             translate_marker_context( "key name", "MOUSE_FORWARD" ) );
 }
References add_gamepad_keycode_pair(), add_keyboard_char_keycode_pair(), add_keyboard_code_keycode_pair(), add_mouse_keycode_pair(), keycode::backspace, c, char_key_beg, char_key_end, keycode::down, keycode::end, keycode::escape, keycode::f1, keycode::f10, keycode::f11, keycode::f12, keycode::f13, keycode::f14, keycode::f15, keycode::f16, keycode::f17, keycode::f18, keycode::f19, keycode::f2, keycode::f20, keycode::f21, keycode::f22, keycode::f23, keycode::f24, keycode::f3, keycode::f4, keycode::f5, keycode::f6, keycode::f7, keycode::f8, keycode::f9, F_KEY_NUM_BEG, F_KEY_NUM_END, keycode::home, IS_CTRL_CHAR(), IS_NAMED_CTRL_CHAR(), JOY_0, JOY_1, JOY_10, JOY_11, JOY_12, JOY_13, JOY_14, JOY_15, JOY_16, JOY_17, JOY_18, JOY_19, JOY_2, JOY_20, JOY_21, JOY_22, JOY_23, JOY_24, JOY_25, JOY_26, JOY_27, JOY_28, JOY_29, JOY_3, JOY_30, JOY_4, JOY_5, JOY_6, JOY_7, JOY_8, JOY_9, JOY_DOWN, JOY_LEFT, JOY_LEFTDOWN, JOY_LEFTUP, JOY_RIGHT, JOY_RIGHTDOWN, JOY_RIGHTUP, JOY_UP, KEY_BACKSPACE, KEY_BREAK, KEY_BTAB, KEY_DC, KEY_DOWN, KEY_END, KEY_ENTER, KEY_ESCAPE, KEY_F(), KEY_HOME, KEY_LEFT, KEY_NPAGE, KEY_PPAGE, KEY_RIGHT, KEY_UP, keycode::kp_0, keycode::kp_1, keycode::kp_2, keycode::kp_3, keycode::kp_4, keycode::kp_5, keycode::kp_6, keycode::kp_7, keycode::kp_8, keycode::kp_9, keycode::kp_divide, keycode::kp_enter, keycode::kp_minus, keycode::kp_multiply, keycode::kp_period, keycode::kp_plus, keycode::left, LeftButtonPressed, LeftButtonReleased, Move, om_direction::name(), keycode::npage, keycode::ppage, keycode::return_, keycode::right, RightButtonPressed, RightButtonReleased, ScrollWheelDown, ScrollWheelUp, keycode::space, string_format(), keycode::tab, translate_marker_context, keycode::up, X1ButtonPressed, X1ButtonReleased, X2ButtonPressed, and X2ButtonReleased.
Referenced by init().
load()
void input_manager::load (const cata_path & file_name, bool is_user_preferences) private
Load keybindings from a json file, override existing bindings.
Throws std::string on errors
Definition at line 239 of file input.cpp.
 {
     std::optional<JsonValue> jsin_opt = json_loader::from_path_opt( file_name );
     if( !jsin_opt.has_value() ) {
         // Only throw if this is the first file to load, that file _must_ exist,
         // otherwise the keybindings can not be read at all.
         if( action_contexts.empty() ) {
             throw std::runtime_error( std::string( "Could not read " ) + file_name.generic_u8string() );
         }
         return;
     }
     JsonArray actions_json = *jsin_opt;
     //Crawl through once and create an entry for every definition
     for( JsonObject action : actions_json ) {
         // JSON object representing the action
         int version = current_keybinding_version;
         if( is_user_preferences ) {
             // if there isn't a "version" value it means the object was written before
             // introduction of keybinding version, which is denoted by version 0.
             version = action.get_int( "version", 0 );
         }
         const std::string type = action.get_string( "type", "keybinding" );
         if( type != "keybinding" ) {
             debugmsg( "Only objects of type 'keybinding' (not %s) should appear in the "
                       "keybindings file '%s'", type, file_name.generic_u8string() );
             continue;
         }
         const std::string action_id = action.get_string( "id" );
         const std::string context = action.get_string( "category", default_context_id );
         t_actions &actions = action_contexts[context];
         if( action.has_member( "name" ) ) {
             action.read( "name", actions[action_id].name );
         }
         t_input_event_list events;
         for( const JsonObject keybinding : action.get_array( "bindings" ) ) {
             std::string input_method = keybinding.get_string( "input_method" );
             std::vector<input_event> new_events( 1 );
             if( input_method == "keyboard_any" ) {
                 new_events.resize( 2 );
                 new_events[0].type = input_event_t::keyboard_char;
                 new_events[1].type = input_event_t::keyboard_code;
             } else if( input_method == "keyboard_char" || input_method == "keyboard" ) {
                 new_events[0].type = input_event_t::keyboard_char;
             } else if( input_method == "keyboard_code" ) {
                 new_events[0].type = input_event_t::keyboard_code;
             } else if( input_method == "gamepad" ) {
                 new_events[0].type = input_event_t::gamepad;
             } else if( input_method == "mouse" ) {
                 new_events[0].type = input_event_t::mouse;
             } else {
                 keybinding.throw_error_at( "input_method", "unknown input_method" );
             }
             if( keybinding.has_member( "mod" ) ) {
                 for( const JsonValue val : keybinding.get_array( "mod" ) ) {
                     const std::string str = val;
                     keymod_t mod = keymod_t::ctrl;
                     if( str == "ctrl" ) {
                         mod = keymod_t::ctrl;
                     } else if( str == "alt" ) {
                         mod = keymod_t::alt;
                     } else if( str == "shift" ) {
                         mod = keymod_t::shift;
                     } else {
                         val.throw_error( "unknown modifier name" );
                     }
                     for( input_event &new_event : new_events ) {
                         new_event.modifiers.emplace( mod );
                     }
                 }
             }
             if( keybinding.has_array( "key" ) ) {
                 for( const std::string line : keybinding.get_array( "key" ) ) {
                     for( input_event &new_event : new_events ) {
                         new_event.sequence.push_back( get_keycode( new_event.type, line ) );
                     }
                 }
             } else { // assume string if not array, and throw if not string
                 for( input_event &new_event : new_events ) {
                     new_event.sequence.push_back(
                         get_keycode( new_event.type, keybinding.get_string( "key" ) )
                     );
                 }
             }
             for( const input_event &evt : new_events ) {
                 if( std::find( events.begin(), events.end(), evt ) == events.end() ) {
                     events.emplace_back( evt );
                 }
             }
             if( is_user_preferences && version <= 1 ) {
                 // Add keypad enter to old keybindings with return key
                 for( const input_event &evt : new_events ) {
                     input_event new_evt = evt;
                     bool has_return = false;
                     // As of version 2 the key sequence actually only supports
                     // one key, so we just replace all return with enter
                     if( new_evt.type == input_event_t::keyboard_char ) {
                         for( int &key : new_evt.sequence ) {
                             if( key == '\n' ) {
                                 key = KEY_ENTER;
                                 has_return = true;
                             }
                         }
                     }
                     if( has_return && std::find( events.begin(), events.end(), new_evt ) == events.end() ) {
                         events.emplace_back( new_evt );
                     }
                 }
             }
         }
         // In case this is the second file containing user preferences,
         // this replaces the default bindings with the user's preferences.
         action_attributes &attributes = actions[action_id];
         if( is_user_preferences && version == 0 ) {
             // version 0 means the keybinding was written prior to the division
             // of `input_event_t::keyboard_char` and `input_event_t::keyboard_code`,
             // so we copy any `input_event_t::keyboard_code` event from the default
             // keybindings to be compatible with old user keybinding files.
             for( const input_event &evt : attributes.input_events ) {
                 if( evt.type == input_event_t::keyboard_code ) {
                     events.emplace_back( evt );
                 }
             }
         }
         attributes.input_events = events;
         if( action.has_member( "is_user_created" ) ) {
             attributes.is_user_created = action.get_bool( "is_user_created" );
         }
     }
 }
References action, action_contexts, alt, context, ctrl, current_keybinding_version, debugmsg, default_context_id(), json_loader::from_path_opt(), gamepad, cata_path::generic_u8string(), JsonValue::get_array(), get_keycode(), action_attributes::input_events, action_attributes::is_user_created, KEY_ENTER, keyboard_char, keyboard_code, line, mouse, om_direction::name(), input_event::sequence, shift, type, and input_event::type.
Referenced by init().
pump_events()
void input_manager::pump_events ()
Resize & refresh if necessary, process all pending window events, and ignore keypresses.
Definition at line 356 of file ncurses_def.cpp.
 {
     if( test_mode ) {
         return;
     }
     // Handle all events, but ignore any keypress
     int key = ERR;
     bool resize = false;
     const int prev_timeout = input_timeout;
     set_timeout( 0 );
     do {
         key = getch();
         if( key == KEY_RESIZE ) {
             resize = true;
         }
     } while( key != ERR );
     set_timeout( prev_timeout );
     if( resize ) {
         catacurses::resizeterm();
     }
     previously_pressed_key = 0;
 }
References input_timeout, previously_pressed_key, catacurses::resizeterm(), set_timeout(), and test_mode.
Referenced by calculate_mapgen_weights(), Item_factory::check_definitions(), game::display_om_pathfinding_progress(), melee_actor::do_grab(), debug_menu::draw_benchmark(), eff_fun_sleep(), finalize_constructions(), recipe_dictionary::finalize_internal(), game::fling_creature(), handle_key_blocking_activity(), map::load(), DynamicDataLoader::load_all_from_json(), DynamicDataLoader::load_deferred(), robot_finds_kitten::process_input(), anonymous_namespace{animation.cpp}::basic_animation::progress(), mapbuffer::save(), mapgen_factory::setup(), loading_ui::show(), and game::unserialize().
remove_input_for_action()
bool input_manager::remove_input_for_action (const std::string & action_descriptor, const std::string & context) private
Returns
true if remove_input_for_action uncovers potentially new global keys. These could cause conflicts.
Definition at line 847 of file input.cpp.
 {
     const t_action_contexts::iterator action_context = action_contexts.find( context );
     if( action_context == action_contexts.end() ) {
         return false;
     }
     t_actions &actions = action_context->second;
     t_actions::iterator action = actions.find( action_descriptor );
     if( action == actions.end() ) {
         return false;
     }
     if( action->second.is_user_created ) {
         // Since this is a user created hotkey, remove it so that the
         // user will fallback to the hotkey in the default context.
         actions.erase( action );
         return true;
     }
     // If a context no longer has any keybindings remaining for an action but
     // there's an attempt to remove bindings anyway, presumably the user wants
     // to fully remove the binding from that context.
     if( action->second.input_events.empty() ) {
         actions.erase( action );
         return true;
     }
     action->second.input_events.clear();
     return false;
 }
References action, action_contexts, and context.
Referenced by input_context::action_remove(), and input_context::action_reset().
reset_timeout()
void input_manager::reset_timeout () inline
Definition at line 279 of file input.h.
{
             set_timeout( -1 );
         }
References set_timeout().
Referenced by anonymous_namespace{main.cpp}::exit_handler(), input_context::handle_input(), anonymous_namespace{animation.cpp}::hit_animation(), and init().
save()
void input_manager::save ()
Opposite of init, save the data that has been loaded by init, and possibly been modified.
Definition at line 381 of file input.cpp.
 {
     write_to_file( PATH_INFO::user_keybindings(), [&]( std::ostream & data_file ) {
         JsonOut jsout( data_file, true );
         jsout.start_array();
         for( const auto &a : action_contexts ) {
             const t_actions &actions = a.second;
             for( const auto &action : actions ) {
                 const t_input_event_list &events = action.second.input_events;
                 jsout.start_object();
                 jsout.member( "id", action.first );
                 jsout.member( "version", current_keybinding_version );
                 jsout.member( "category", a.first );
                 bool is_user_created = action.second.is_user_created;
                 if( is_user_created ) {
                     jsout.member( "is_user_created", is_user_created );
                 }
                 // optimization: no writing if empty
                 if( !events.empty() ) {
                     jsout.member( "bindings" );
                     jsout.start_array();
                     for( const input_event &event : events ) {
                         jsout.start_object();
                         switch( event.type ) {
                             case input_event_t::keyboard_char:
                                 jsout.member( "input_method", "keyboard_char" );
                                 break;
                             case input_event_t::keyboard_code:
                                 jsout.member( "input_method", "keyboard_code" );
                                 break;
                             case input_event_t::gamepad:
                                 jsout.member( "input_method", "gamepad" );
                                 break;
                             case input_event_t::mouse:
                                 jsout.member( "input_method", "mouse" );
                                 break;
                             default:
                                 throw std::runtime_error( "unknown input_event_t" );
                         }
                         // optimization: no writing if empty
                         if( !event.modifiers.empty() ) {
                             jsout.member( "mod" );
                             jsout.start_array();
                             for( const keymod_t mod : event.modifiers ) {
                                 switch( mod ) {
                                     case keymod_t::ctrl:
                                         jsout.write( "ctrl" );
                                         break;
                                     case keymod_t::alt:
                                         jsout.write( "alt" );
                                         break;
                                     case keymod_t::shift:
                                         jsout.write( "shift" );
                                         break;
                                     default:
                                         throw std::runtime_error( "unknown keymod_t" );
                                 }
                             }
                             jsout.end_array();
                         }
                         jsout.member( "key" );
                         jsout.start_array();
                         for( size_t i = 0; i < event.sequence.size(); i++ ) {
                             jsout.write( get_keyname( event.sequence[i], event.type, true ) );
                         }
                         jsout.end_array();
                         jsout.end_object();
                     }
                     jsout.end_array();
                 }
                 jsout.end_object();
             }
         }
         jsout.end_array();
     }, _( "key bindings configuration" ) );
 }
References _, a, action, action_contexts, alt, ctrl, current_keybinding_version, JsonOut::end_array(), JsonOut::end_object(), gamepad, get_keyname(), keyboard_char, keyboard_code, JsonOut::member(), mouse, shift, JsonOut::start_array(), JsonOut::start_object(), PATH_INFO::user_keybindings(), JsonOut::write(), and write_to_file().
Referenced by input_context::display_menu(), and init().
set_timeout()
void input_manager::set_timeout (int delay)
Sets global input polling timeout in milliseconds as appropriate for the current interface system.
Use input_context::(re)set_timeout() when possible so timeout will be properly reset when entering a new input context.
Definition at line 496 of file ncurses_def.cpp.
 {
     timeout( delay );
     // Use this to determine when curses should return a input_event_t::timeout event.
     input_timeout = delay;
 }
References input_timeout, and timeout.
Referenced by anonymous_namespace{main.cpp}::exit_handler(), get_input_event(), input_context::handle_input(), anonymous_namespace{animation.cpp}::hit_animation(), pump_events(), and reset_timeout().
wait_for_any_key()
void input_manager::wait_for_any_key ()
Wait until the user presses a key.
Mouse and similar input is ignored, only input events from the keyboard are considered.
Definition at line 893 of file input.cpp.
 {
 #if defined(__ANDROID__)
     input_context ctxt( "WAIT_FOR_ANY_KEY", keyboard_mode::keycode );
 #endif
     while( true ) {
         const input_event evt = inp_mngr.get_input_event();
         switch( evt.type ) {
             case input_event_t::keyboard_char:
                 if( !evt.sequence.empty() ) {
                     return;
                 }
                 break;
             case input_event_t::keyboard_code:
             // errors are accepted as well to avoid an infinite loop
             case input_event_t::error:
                 return;
             default:
                 break;
         }
     }
 }
References error, get_input_event(), inp_mngr, keyboard_char, keyboard_code, keycode, input_event::sequence, and input_event::type.
Referenced by game::display_scent(), computer_session::query_any(), and debug_menu::show_sound().
Friends And Related Function Documentation
input_context
friend class input_context friend
Definition at line 289 of file input.h.
keybindings_ui
friend class keybindings_ui friend
Definition at line 203 of file input.h.
Member Data Documentation
action_contexts
t_action_contexts input_manager::action_contexts private
Definition at line 294 of file input.h.
Referenced by input_context::action_remove(), input_context::action_reset(), input_context::clear_conflicting_keybindings(), input_context::display_menu(), get_action_attributes(), get_default_action_name(), get_or_create_event_list(), init(), load(), remove_input_for_action(), and save().
basic_action_contexts
t_action_contexts input_manager::basic_action_contexts private
called basic rather than default to not confuse default context basic means default keybindings (without user changes)
Definition at line 299 of file input.h.
Referenced by input_context::action_reset(), get_action_attributes(), and init().
gamepad_keycode_to_keyname
t_key_to_name_map input_manager::gamepad_keycode_to_keyname private
Definition at line 304 of file input.h.
Referenced by add_gamepad_keycode_pair(), and get_keyname().
gamepad_keyname_to_keycode
t_name_to_key_map input_manager::gamepad_keyname_to_keycode private
Definition at line 309 of file input.h.
Referenced by add_gamepad_keycode_pair(), and get_keycode().
input_timeout
int input_manager::input_timeout private
Definition at line 328 of file input.h.
Referenced by get_input_event(), get_timeout(), pump_events(), and set_timeout().
keyboard_char_keycode_to_keyname
t_key_to_name_map input_manager::keyboard_char_keycode_to_keyname private
Definition at line 302 of file input.h.
Referenced by add_keyboard_char_keycode_pair(), and get_keyname().
keyboard_char_keyname_to_keycode
t_name_to_key_map input_manager::keyboard_char_keyname_to_keycode private
Definition at line 307 of file input.h.
Referenced by add_keyboard_char_keycode_pair(), and get_keycode().
keyboard_code_keycode_to_keyname
t_key_to_name_map input_manager::keyboard_code_keycode_to_keyname private
Definition at line 303 of file input.h.
Referenced by add_keyboard_code_keycode_pair(), and get_keyname().
keyboard_code_keyname_to_keycode
t_name_to_key_map input_manager::keyboard_code_keyname_to_keycode private
Definition at line 308 of file input.h.
Referenced by add_keyboard_code_keycode_pair(), and get_keycode().
mouse_keycode_to_keyname
t_key_to_name_map input_manager::mouse_keycode_to_keyname private
Definition at line 305 of file input.h.
Referenced by add_mouse_keycode_pair(), and get_keyname().
mouse_keyname_to_keycode
t_name_to_key_map input_manager::mouse_keyname_to_keycode private
Definition at line 310 of file input.h.
Referenced by add_mouse_keycode_pair(), and get_keycode().
previously_pressed_key
int input_manager::previously_pressed_key private
Definition at line 313 of file input.h.
Referenced by get_input_event(), get_previously_pressed_key(), and pump_events().
The documentation for this class was generated from the following files:
src/input.h
src/input.cpp
src/ncurses_def.cpp