Cataclysm DDA: jmapgen_piece Class Reference
jmapgen_piece Class Reference abstract
Basic mapgen object.
#include <mapgen.h>
Public Member Functions
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &context) const =0
Place something on the map from mapgendata &dat, at (x,y).
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
jmapgen_int repeat
Protected Member Functions
jmapgen_piece ()
Detailed Description
Basic mapgen object.
It is supposed to place or do something on a specific square on the map. Inherit from this class and implement the apply function.
Instructions for adding more mapgen things:
create a new class inheriting from jmapgen_piece.
It should have a constructor that a accepts a JsonObject and initializes all it local members from it. On errors / invalid data, call JsonObject::throw_error or similar.
Implement the apply function to do the actual change on the map.
Go into mapgen_function_json::setup and look for the lines with load_objects, add a new line with your own class there. It should look like
load_objects<your_own_class_from_step_1>(jo, "place_something");
Use a descriptive name for "something", preferably matching the name of your class.
Go into mapgen_function_json::setup and look for the lines with load_place_mapings, add a new line with your class there. It should look like
load_place_mapings<your_own_class_from_step_1>(jo, "something", format_placings);
Using the same "something" as in step 2 is preferred.
For actual examples look at the commits that introduced the load_objects/load_place_mapings lines (ignore the changes to the json files).
Definition at line 223 of file mapgen.h.
Constructor & Destructor Documentation
jmapgen_piece()
jmapgen_piece::jmapgen_piece () inline protected
Definition at line 226 of file mapgen.h.
 : repeat( 1, 1 ) { }
~jmapgen_piece()
virtual jmapgen_piece::~jmapgen_piece () virtual default
Member Function Documentation
apply()
virtual void jmapgen_piece::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const pure virtual
Place something on the map from mapgendata &dat, at (x,y).
Implemented in jmapgen_nested, jmapgen_sealed_item, jmapgen_terrain, jmapgen_furniture, jmapgen_constrained< Value >, jmapgen_alternatively< PieceType >, jmapgen_remove_all, jmapgen_remove_vehicles, jmapgen_variable, jmapgen_zone, jmapgen_computer, jmapgen_make_rubble, jmapgen_ter_furn_transform, jmapgen_trap, jmapgen_spawn_item, jmapgen_vehicle, jmapgen_monster, jmapgen_monster_group, jmapgen_loot, jmapgen_item_group, jmapgen_corpse, jmapgen_liquid_item, jmapgen_gaspump, jmapgen_toilet, jmapgen_vending_machine, jmapgen_graffiti, jmapgen_sign, jmapgen_npc, jmapgen_field, jmapgen_faction, and jmapgen_remove_npcs.
Referenced by jmapgen_objects::apply().
check()
virtual void jmapgen_piece::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline virtual
Sanity-check this piece.
Reimplemented in jmapgen_nested, jmapgen_zone, jmapgen_make_rubble, jmapgen_ter_furn_transform, jmapgen_terrain, jmapgen_furniture, jmapgen_trap, jmapgen_spawn_item, jmapgen_monster, jmapgen_monster_group, jmapgen_liquid_item, jmapgen_gaspump, jmapgen_vending_machine, jmapgen_faction, jmapgen_npc, jmapgen_field, jmapgen_sealed_item, jmapgen_constrained< Value >, jmapgen_alternatively< PieceType >, jmapgen_vehicle, and jmapgen_item_group.
Definition at line 235 of file mapgen.h.
                                                                                                      { }
Referenced by jmapgen_objects::check().
has_vehicle_collision()
virtual bool jmapgen_piece::has_vehicle_collision (const mapgendata & , const tripoint_rel_ms &) const inline virtual
Reimplemented in jmapgen_nested, jmapgen_sealed_item, jmapgen_computer, jmapgen_terrain, jmapgen_furniture, jmapgen_trap, jmapgen_vehicle, jmapgen_gaspump, jmapgen_toilet, jmapgen_vending_machine, jmapgen_sign, and jmapgen_alternatively< PieceType >.
Definition at line 247 of file mapgen.h.
{
             return false;
         }
is_nop()
virtual bool jmapgen_piece::is_nop () const inline virtual
Reimplemented in jmapgen_terrain.
Definition at line 228 of file mapgen.h.
{
             return false;
         }
merge_parameters_into()
virtual void jmapgen_piece::merge_parameters_into (mapgen_parameters & , const std::string &) const inline virtual
Reimplemented in jmapgen_nested, jmapgen_constrained< Value >, and jmapgen_alternatively< PieceType >.
Definition at line 238 of file mapgen.h.
                                                                        {}
phase()
virtual mapgen_phase jmapgen_piece::phase () const inline virtual
Reimplemented in jmapgen_nested, jmapgen_remove_all, jmapgen_remove_vehicles, jmapgen_variable, jmapgen_zone, jmapgen_terrain, jmapgen_furniture, jmapgen_toilet, jmapgen_faction, jmapgen_constrained< Value >, and jmapgen_alternatively< PieceType >.
Definition at line 231 of file mapgen.h.
{
             return mapgen_phase::default_;
         }
References default_.
Referenced by jmapgen_objects::apply().
Member Data Documentation
repeat
jmapgen_int jmapgen_piece::repeat
Definition at line 246 of file mapgen.h.
Referenced by jmapgen_objects::apply(), jmapgen_item_group::jmapgen_item_group(), and jmapgen_spawn_item::jmapgen_spawn_item().
The documentation for this class was generated from the following file:
src/mapgen.h