Cataclysm DDA: Single_item_creator Class Reference
Single_item_creator Class Reference
Basic item creator.
#include <item_group.h>
Public Types
enum Type { S_ITEM_GROUP , S_ITEM , S_NONE }
Public Types inherited from Item_spawn_data
enum class overflow_behaviour { none , spill , discard , last }
using ItemList = std::vector< item >
using RecursionList = std::vector< item_group_id >
Public Member Functions
Single_item_creator (const std::string &id, Type type, int probability, const std::string &context, holiday event=holiday::none)
~Single_item_creator () override=default
void inherit_ammo_mag_chances (int ammo, int mag)
std::size_t create (ItemList &list, const time_point &birthday, RecursionList &rec, spawn_flags) const override
Create a list of items.
void finalize (const itype_id &container=itype_id::NULL_ID()) override
Instead of calculating at run-time, give a step to finalize those item_groups that has count-min but not count-max.
item create_single (const time_point &birthday, RecursionList &rec) const override
The same as create, but create a single item only.
item create_single_without_container (const time_point &birthday, RecursionList &rec) const
void check_consistency (bool actually_spawn) const override
Check item / spawn settings for consistency.
bool remove_item (const itype_id &itemid) override
For item blacklisted, remove the given item from this and all linked groups.
void replace_items (const std::unordered_map< itype_id, itype_id > &replacements) override
bool has_item (const itype_id &itemid) const override
std::set< const itype * > every_item () const override
Public Member Functions inherited from Item_spawn_data
Item_spawn_data (int _probability, const std::string &context, holiday _event=holiday::none)
virtual ~Item_spawn_data ()=default
std::size_t create (ItemList &list, const time_point &birthday, spawn_flags=spawn_flags::none) const
item create_single (const time_point &birthday) const
const std::string & context () const
int get_probability (bool skip_event_check) const
void set_probablility (int prob)
bool is_event_based () const
Public Attributes
std::string id
Id of the item group or id of the item.
Type type
std::optional< Item_modifier > modifier
Public Attributes inherited from Item_spawn_data
std::optional< itype_id > container_item
The group spawns contained in this item.
std::optional< std::string > container_item_variant
overflow_behaviour on_overflow = overflow_behaviour::none
std::optional< std::vector< itype_id > > components_items
These item(s) are spawned as components.
bool sealed = true
cata::value_ptr< relic_generator > artifact
Additional Inherited Members
Protected Attributes inherited from Item_spawn_data
int probability
probability, used by the parent object.
std::string context_
holiday event = holiday::none
Detailed Description
Basic item creator.
It contains either the item id directly, or a name of a group that it queries for it. It can spawn a single item and a item list. Creates a single item, with its standard properties (charges, no damage, ...). As it inherits from Item_spawn_data it can also wrap that created item into a list. That list will always contain a single item (or no item at all). Note that the return single item my be a null item. The returned item list will (according to the definition in Item_spawn_data) never contain null items, that's why it might be empty.
Definition at line 313 of file item_group.h.
Member Enumeration Documentation
Type
enum Single_item_creator::Type
Enumerator
S_ITEM_GROUP
S_ITEM
S_NONE
Definition at line 316 of file item_group.h.
                   {
             S_ITEM_GROUP,
             S_ITEM,
             S_NONE,
         };
Constructor & Destructor Documentation
Single_item_creator()
Single_item_creator::Single_item_creator (const std::string & id, Type type, int probability, const std::string & context, holiday event = holiday::none)
Definition at line 172 of file item_group.cpp.
     : Item_spawn_data( _probability, context, event )
     , id( _id )
     , type( _type )
 {
 }
~Single_item_creator()
Single_item_creator::~Single_item_creator () override default
Member Function Documentation
check_consistency()
void Single_item_creator::check_consistency (bool actually_spawn) const override virtual
Check item / spawn settings for consistency.
Includes checking for valid item types and valid settings.
Reimplemented from Item_spawn_data.
Definition at line 392 of file item_group.cpp.
 {
     if( type == S_ITEM ) {
         if( !item::type_is_defined( itype_id( id ) ) ) {
             debugmsg( "item id %s is unknown (in %s)", id, context() );
         }
     } else if( type == S_ITEM_GROUP ) {
         if( !item_group::group_is_defined( item_group_id( id ) ) ) {
             debugmsg( "item group id %s is unknown (in %s)", id, context() );
         }
     } else if( type == S_NONE ) {
         // this is okay, it will be ignored
     } else {
         debugmsg( "Unknown type of Single_item_creator: %d", static_cast<int>( type ) );
     }
     if( modifier ) {
         modifier->check_consistency( context() );
     }
     // If this is to create a group and there's no container to restrain it, no need to actually create it,
     // since groups are processed separately.
     Item_spawn_data::check_consistency( ( type == S_ITEM_GROUP &&
                                           !container_item ) ? false : actually_spawn );
 }
References Item_spawn_data::check_consistency(), Item_spawn_data::container_item, Item_spawn_data::context(), debugmsg, item_group::group_is_defined(), item_group_id, itype_id, modifier, S_ITEM, S_ITEM_GROUP, S_NONE, type, and item::type_is_defined().
create()
std::size_t Single_item_creator::create (ItemList & list, const time_point & birthday, RecursionList & rec, spawn_flags) const override virtual
Create a list of items.
The create list might be empty. No item of it will be the null item.
Parameters
[out] list New items are appended to the list
[in] birthday All items have that value as birthday.
[out] rec Recursion list, output goes here.
[in] spawn_flags Extra information to change how items are spawned.
Returns
The number of new items appended to the list
Implements Item_spawn_data.
Definition at line 262 of file item_group.cpp.
 {
     std::size_t prev_list_size = list.size();
     int cnt = 1;
     if( modifier ) {
         auto modifier_count = modifier->count;
         if( flags & spawn_flags::maximized ) {
             cnt = modifier_count.second;
         } else {
             cnt = ( modifier_count.first == modifier_count.second ) ? modifier_count.first : rng(
                       modifier_count.first, modifier_count.second );
         }
     }
     float spawn_rate = get_option<float>( "ITEM_SPAWNRATE" );
     for( ; cnt > 0; cnt-- ) {
         if( type == S_ITEM ) {
             item itm = create_single_without_container( birthday, rec );
             if( flags & spawn_flags::use_spawn_rate && !itm.has_flag( STATIC( flag_id( "MISSION_ITEM" ) ) ) &&
                 rng_float( 0, 1 ) > spawn_rate ) {
                 continue;
             }
             if( !itm.is_null() ) {
                 list.emplace_back( std::move( itm ) );
             }
         } else {
             item_group_id group_id( id );
             if( std::find( rec.begin(), rec.end(), group_id ) != rec.end() ) {
                 debugmsg( "recursion in item spawn list %s", id.c_str() );
                 return list.size() - prev_list_size;
             }
             rec.push_back( group_id );
             Item_spawn_data *isd = item_controller->get_group( group_id );
             if( isd == nullptr ) {
                 debugmsg( "unknown item spawn list %s", id.c_str() );
                 return list.size() - prev_list_size;
             }
             std::size_t tmp_list_size = isd->create( list, birthday, rec, flags );
             cata_assert( list.size() >= tmp_list_size );
             rec.pop_back();
             if( modifier ) {
                 for( auto it = list.end() - tmp_list_size; it != list.end(); ++it ) {
                     modifier->modify( *it, "modifier for " + context() );
                 }
             }
         }
     }
     if( artifact ) {
         for( auto it = list.begin() + prev_list_size; it != list.end(); ++it ) {
             it->overwrite_relic( artifact->generate_relic( it->typeId() ) );
         }
     }
     const std::size_t items_created = list.size() - prev_list_size;
     put_into_container( list, items_created, container_item, container_item_variant, sealed, birthday,
                         on_overflow, context() );
     return list.size() - prev_list_size;
 }
References Item_spawn_data::artifact, cata_assert, Item_spawn_data::container_item, Item_spawn_data::container_item_variant, Item_spawn_data::context(), Item_spawn_data::create(), create_single_without_container(), debugmsg, flag_id, item::has_flag(), item::is_null(), item_controller, maximized, modifier, Item_spawn_data::on_overflow, put_into_container(), rng(), rng_float(), S_ITEM, Item_spawn_data::sealed, STATIC, type, and use_spawn_rate.
create_single()
item Single_item_creator::create_single (const time_point & birthday, RecursionList & rec) const override virtual
The same as create, but create a single item only.
The returned item might be a null item!
Implements Item_spawn_data.
Definition at line 179 of file item_group.cpp.
 {
     item tmp = create_single_without_container( birthday, rec );
     if( container_item ) {
         tmp = tmp.in_container( *container_item, tmp.count(), sealed,
                                 container_item_variant.value_or( "" ) );
     }
     return tmp;
 }
References Item_spawn_data::container_item, Item_spawn_data::container_item_variant, item::count(), create_single_without_container(), item::in_container(), and Item_spawn_data::sealed.
create_single_without_container()
item Single_item_creator::create_single_without_container (const time_point & birthday, RecursionList & rec) const
Definition at line 189 of file item_group.cpp.
 {
     // Check direct return conditions first.
     if( type == S_NONE ) {
         return item( null_item_id, birthday );
     }
     Item_spawn_data *isd = nullptr;
     if( type == S_ITEM_GROUP ) {
         item_group_id group_id( id );
         if( std::find( rec.begin(), rec.end(), group_id ) != rec.end() ) {
             debugmsg( "recursion in item spawn list %s", id.c_str() );
             return item( null_item_id, birthday );
         }
         rec.push_back( group_id );
         isd = item_controller->get_group( group_id );
         if( isd == nullptr ) {
             debugmsg( "unknown item spawn list %s", id.c_str() );
             return item( null_item_id, birthday );
         }
     }
     item tmp = ( [&]() -> item {
         if( isd )
         {
             on_out_of_scope scope{
                 [&]{
                     rec.erase( rec.end() - 1 );
                 }} ;
             return isd->create_single( birthday, rec );
         } else
         {
             cata_assert( type == S_ITEM );
             if( id == "corpse" ) {
                 return item::make_corpse( mtype_id::NULL_ID(), birthday );
             } else {
                 return item( id, birthday );
             }
         }
     } )();
     if( one_in( 3 ) && tmp.has_flag( flag_VARSIZE ) ) {
         tmp.set_flag( flag_FIT );
     }
     if( components_items ) {
         for( itype_id component_id : *components_items ) {
             if( !component_id.is_valid() ) {
                 debugmsg( "Invalid components item %s in %s (could not find matching itype id)",
                           component_id.c_str(), context() );
                 continue;
             }
             item component = item( component_id, calendar::turn );
             tmp.components.add( component );
         }
     }
     if( modifier ) {
         modifier->modify( tmp, "modifier for " + context() );
     } else {
         int qty = tmp.count();
         if( modifier ) {
             qty = rng( modifier->charges.first, modifier->charges.second );
         } else if( tmp.made_of_from_type( phase_id::LIQUID ) ) {
             qty = item::INFINITE_CHARGES;
         }
         // TODO: change the spawn lists to contain proper references to containers
         tmp = tmp.in_its_container( qty );
     }
     if( artifact ) {
         tmp.overwrite_relic( artifact->generate_relic( tmp.typeId() ) );
     }
     return tmp;
 }
References item_components::add(), Item_spawn_data::artifact, cata_assert, item::components, Item_spawn_data::components_items, Item_spawn_data::context(), item::count(), Item_spawn_data::create_single(), debugmsg, flag_FIT, flag_VARSIZE, item::has_flag(), item::in_its_container(), item::INFINITE_CHARGES, item, item_controller, LIQUID, item::made_of_from_type(), item::make_corpse(), modifier, string_id< mtype >::NULL_ID(), null_item_id(), one_in(), item::overwrite_relic(), rng(), S_ITEM, S_ITEM_GROUP, S_NONE, item::set_flag(), calendar::turn, type, and item::typeId().
Referenced by create(), and create_single().
every_item()
std::set< const itype * > Single_item_creator::every_item () const override virtual
Implements Item_spawn_data.
Definition at line 471 of file item_group.cpp.
 {
     switch( type ) {
         case S_ITEM:
             return { item::find_type( itype_id( id ) ) };
         case S_ITEM_GROUP: {
             Item_spawn_data *isd = item_controller->get_group( item_group_id( id ) );
             if( isd != nullptr ) {
                 return isd->every_item();
             }
             return {};
         }
         case S_NONE:
             return {};
     }
     // NOLINTNEXTLINE(misc-static-assert,cert-dcl03-c)
     cata_fatal( "Unexpected type" );
     return {};
 }
References cata_fatal, Item_spawn_data::every_item(), item::find_type(), item_controller, item_group_id, itype_id, S_ITEM, S_ITEM_GROUP, S_NONE, and type.
finalize()
void Single_item_creator::finalize (const itype_id & = itype_id::NULL_ID()) override virtual
Instead of calculating at run-time, give a step to finalize those item_groups that has count-min but not count-max.
The reason is
Implements Item_spawn_data.
Definition at line 320 of file item_group.cpp.
 {
     auto sanitize_count = [this]() {
         if( modifier->count.first == -1 ) {
             modifier->count.first = 1;
         }
         if( modifier->count.second == -1 ) {
             modifier->count.second = 1;
         }
     };
     itype_id cont;
     if( container_item.has_value() ) {
         cont = container_item.value();
     } else {
         cont = container_ex;
     }
     if( modifier.has_value() ) {
         std::unique_ptr<item> content_final;
         if( modifier->charges.first != -1 || modifier->charges.second != -1 ) {
             if( type == S_ITEM ) {
                 content_final = std::make_unique<item>( itype_id( id ), calendar::turn_zero );
                 if( !modifier->ammo && !content_final->type->can_have_charges() && !content_final->is_tool() &&
                     !content_final->is_gun() && !content_final->is_magazine() ) {
                     debugmsg( "itemgroup entry for spawning item %s defined charges but can't have any", id );
                     sanitize_count();
                     return;
                 }
             }
         }
         if( modifier->count.first != -1 && modifier->count.second == -1 ) {
             if( type != S_ITEM ) {
                 debugmsg( "cannot auto derive count-max for spawning itemgroup %s", id );
                 sanitize_count();
                 return;
             } else {
                 auto &count = modifier->count;
                 int max_capacity = -1;
                 if( !content_final ) {
                     content_final = std::make_unique<item>( itype_id( id ), calendar::turn_zero );
                 }
                 item container_final( cont, calendar::turn_zero );
                 if( container_final.is_null() ) {
                     debugmsg( "cannot auto derive count-max for itemgroup entry of spawning %s inside null container-item.",
                               id, container_ex.str() );
                     sanitize_count();
                     return;
                 }
                 if( content_final->is_gun() || content_final->is_magazine() || content_final->is_tool() ) {
                     debugmsg( "cannot auto derive count-max for itemgroup entry of spawning %s.", id );
                     sanitize_count();
                     return;
                 }
                 if( modifier->container && !modifier->container->has_item( itype_corpse ) &&
                     !modifier->container->has_item( itype_id::NULL_ID() ) ) {
                     debugmsg( "cannot auto derive count-max for itemgroup entry of spawning %s with container-item defined in entry.",
                               id );
                     sanitize_count();
                     return;
                 }
                 if( content_final->type->weight == 0_gram ) {
                     max_capacity = content_final->charges_per_volume( container_final.get_total_capacity() );
                 } else {
                     max_capacity = std::min( content_final->charges_per_volume( container_final.get_total_capacity() ),
                                              content_final->charges_per_weight( container_final.get_total_weight_capacity() ) );
                 }
                 count.second = std::max( count.first, max_capacity );
             }
         }
         sanitize_count();
     }
 }
References Item_spawn_data::container_item, debugmsg, item::get_total_capacity(), item::get_total_weight_capacity(), item::is_null(), itype_corpse, itype_id, max(), min(), modifier, string_id< itype >::NULL_ID(), S_ITEM, string_id< T >::str(), calendar::turn_zero, and type.
has_item()
bool Single_item_creator::has_item (const itype_id & itemid) const override virtual
Implements Item_spawn_data.
Definition at line 453 of file item_group.cpp.
 {
     switch( type ) {
         case S_ITEM:
             return itemid.str() == id;
         case S_ITEM_GROUP: {
             Item_spawn_data *isd = item_controller->get_group( item_group_id( id ) );
             if( isd != nullptr ) {
                 return isd->has_item( itemid );
             }
             return false;
         }
         case S_NONE:
             return false;
     }
     return false;
 }
References Item_spawn_data::has_item(), id, item_controller, item_group_id, S_ITEM, S_ITEM_GROUP, S_NONE, string_id< T >::str(), and type.
inherit_ammo_mag_chances()
void Single_item_creator::inherit_ammo_mag_chances (int ammo, int mag)
Definition at line 491 of file item_group.cpp.
 {
     if( ammo != 0 || mag != 0 ) {
         if( !modifier ) {
             modifier.emplace();
         }
         modifier->with_ammo = ammo;
         modifier->with_magazine = mag;
     }
 }
References modifier.
Referenced by Item_group::add_entry(), and Item_factory::load_sub_ref().
remove_item()
bool Single_item_creator::remove_item (const itype_id & itemid) override virtual
For item blacklisted, remove the given item from this and all linked groups.
Implements Item_spawn_data.
Definition at line 416 of file item_group.cpp.
 {
     if( modifier ) {
         if( modifier->remove_item( itemid ) ) {
             type = S_NONE;
             return true;
         }
     }
     if( type == S_ITEM ) {
         if( itemid.str() == id ) {
             type = S_NONE;
             return true;
         }
     }
     // This part of code is currently only used in Item_factory::finalize_item_blacklist(), not during the game.
     // Else if type == S_ITEM_GROUP, the group must have been indexed in m_template_groups,
     // and finalize_item_blacklist() will deal with it, so no need to find it and call its remove_item().
     return type == S_NONE;
 }
References modifier, S_ITEM, S_NONE, string_id< T >::str(), and type.
replace_items()
void Single_item_creator::replace_items (const std::unordered_map< itype_id, itype_id > & replacements) override virtual
Implements Item_spawn_data.
Definition at line 436 of file item_group.cpp.
 {
     if( modifier ) {
         modifier->replace_items( replacements );
     }
     if( type == S_ITEM ) {
         auto it = replacements.find( itype_id( id ) );
         if( it != replacements.end() ) {
             id = it->second.str();
         }
     }
     // This part of code is currently only used in Item_factory::finalize_item_blacklist(), not during the game.
     // Else if type == S_ITEM_GROUP, the group must have been indexed in m_template_groups,
     // and finalize_item_blacklist() will deal with it, so no need to find it and call its replace_items().
 }
References itype_id, modifier, S_ITEM, and type.
Member Data Documentation
id
std::string Single_item_creator::id
Id of the item group or id of the item.
Definition at line 329 of file item_group.h.
Referenced by has_item().
modifier
std::optional<Item_modifier> Single_item_creator::modifier
Definition at line 331 of file item_group.h.
Referenced by check_consistency(), create(), create_single_without_container(), finalize(), inherit_ammo_mag_chances(), remove_item(), and replace_items().
type
Type Single_item_creator::type
Definition at line 330 of file item_group.h.
Referenced by check_consistency(), create(), create_single_without_container(), every_item(), finalize(), has_item(), remove_item(), and replace_items().
The documentation for this class was generated from the following files:
src/item_group.h
src/item_group.cpp