Cataclysm DDA: install_bionic_actor Class Reference
install_bionic_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
install_bionic_actor (const std::string &type="install_bionic")
void load (const JsonObject &) override
std::optional< int > use (Character *p, item &it, const tripoint &pnt) const override
ret_val< void > can_use (const Character &, const item &it, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void finalize (const itype_id &my_item_type) override
Finalizes the actor.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
Additional Inherited Members
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1040 of file iuse_actor.h.
Constructor & Destructor Documentation
install_bionic_actor()
install_bionic_actor::install_bionic_actor (const std::string & type = "install_bionic") inline explicit
Definition at line 1043 of file iuse_actor.h.
 : iuse_actor( type ) {}
Member Function Documentation
can_use()
ret_val< void > install_bionic_actor::can_use (const Character & p, const item & it, const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 4198 of file iuse_actor.cpp.
 {
     if( !it.is_bionic() ) {
         return ret_val<void>::make_failure();
     }
     const bionic_id &bid = it.type->bionic->id;
     if( p.is_mounted() ) {
         return ret_val<void>::make_failure( _( "You can't install bionics while mounted." ) );
     }
     if( !p.has_trait( trait_DEBUG_BIONICS ) ) {
         if( bid->installation_requirement.is_empty() && !p.has_flag( json_flag_MANUAL_CBM_INSTALLATION ) ) {
             return ret_val<void>::make_failure( _( "You can't self-install this CBM." ) );
         } else  if( it.has_flag( flag_FILTHY ) ) {
             return ret_val<void>::make_failure( _( "You can't install a filthy CBM!" ) );
         } else if( it.has_flag( flag_NO_STERILE ) ) {
             return ret_val<void>::make_failure( _( "This CBM is not sterile, you can't install it." ) );
         } else if( it.has_fault( fault_bionic_salvaged ) ) {
             return ret_val<void>::make_failure(
                        _( "This CBM is already deployed.  You need to reset it to factory state." ) );
         } else if( units::energy( std::numeric_limits<int>::max(), units::energy::unit_type{} ) -
                    p.get_max_power_level() < bid->capacity ) {
             return ret_val<void>::make_failure( _( "Max power capacity already reached" ) );
         }
     }
     if( p.has_bionic( bid ) && !bid->dupes_allowed ) {
         return ret_val<void>::make_failure( _( "You have already installed this bionic." ) );
     } else if( bid->upgraded_bionic && !p.has_bionic( bid->upgraded_bionic ) ) {
         return ret_val<void>::make_failure( _( "There is nothing to upgrade." ) );
     } else {
         const bool downgrade =
             std::any_of( bid->available_upgrades.begin(), bid->available_upgrades.end(),
         [&p]( const bionic_id & b ) {
             return p.has_bionic( b );
         } );
         if( downgrade ) {
             return ret_val<void>::make_failure( _( "You have a superior version installed." ) );
         }
     }
     return ret_val<void>::make_success();
 }
References _, bionic_data::available_upgrades, b, itype::bionic, bionic_data::capacity, bionic_data::dupes_allowed, fault_bionic_salvaged, flag_FILTHY, flag_NO_STERILE, Character::get_max_power_level(), Character::has_bionic(), item::has_fault(), item::has_flag(), Character::has_flag(), Character::has_trait(), bionic_data::installation_requirement, item::is_bionic(), string_id< T >::is_empty(), Character::is_mounted(), json_flag_MANUAL_CBM_INSTALLATION, ret_val< T >::make_failure(), ret_val< T >::make_success(), max(), trait_DEBUG_BIONICS, item::type, and bionic_data::upgraded_bionic.
clone()
std::unique_ptr< iuse_actor > install_bionic_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4243 of file iuse_actor.cpp.
 {
     return std::make_unique<install_bionic_actor>( *this );
 }
finalize()
void install_bionic_actor::finalize (const itype_id &) override virtual
Finalizes the actor.
Must be called after all items are loaded.
Reimplemented from iuse_actor.
Definition at line 4248 of file iuse_actor.cpp.
 {
     if( !item::find_type( my_item_type )->bionic ) {
         debugmsg( "Item %s has install_bionic actor, but it's not a bionic.", my_item_type.c_str() );
     }
 }
References string_id< T >::c_str(), debugmsg, and item::find_type().
load()
void install_bionic_actor::load (const JsonObject &) inline override virtual
Implements iuse_actor.
Definition at line 1045 of file iuse_actor.h.
 {}
use()
std::optional< int > install_bionic_actor::use (Character * p, item & it, const tripoint & pnt) const override virtual
Implements iuse_actor.
Definition at line 4183 of file iuse_actor.cpp.
 {
     if( p->can_install_bionics( *it.type, *p, false ) ) {
         if( !p->has_trait( trait_DEBUG_BIONICS ) && !p->has_flag( json_flag_MANUAL_CBM_INSTALLATION ) ) {
             p->consume_installation_requirement( it.type->bionic->id );
             p->consume_anesth_requirement( *it.type, *p );
         }
         if( p->install_bionics( *it.type, *p, false ) ) {
             return 1;
         }
     }
     return std::nullopt;
 }
References itype::bionic, Character::can_install_bionics(), Character::consume_anesth_requirement(), Character::consume_installation_requirement(), Character::has_flag(), Character::has_trait(), Character::install_bionics(), json_flag_MANUAL_CBM_INSTALLATION, trait_DEBUG_BIONICS, and item::type.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp