Cataclysm DDA: vitamin Class Reference
vitamin Class Reference
#include <vitamin.h>
Public Member Functions
vitamin ()
const vitamin_id & id () const
const vitamin_type & type () const
bool is_null () const
std::string name () const
bool has_flag (const std::string &flag) const
const efftype_id & deficiency () const
Disease effect with increasing intensity proportional to vitamin deficiency.
const efftype_id & excess () const
Disease effect with increasing intensity proportional to vitamin excess.
int min () const
Lower bound for deficiency of this vitamin.
int max () const
Upper bound for any accumulation of this vitamin.
time_duration rate () const
Usage rate of vitamin (time to consume unit) Lower bound is zero whereby vitamin is not required (but may still accumulate)
std::vector< std::pair< vitamin_id, int > > decays_into () const
An array of the other vitamins that this vitamin decays into, and their proportions.
int severity (int qty) const
Get intensity of deficiency or zero if not deficient for specified qty.
float RDA_to_default (int percent) const
Convert standard RDA to units a character can ingest This is the default RDA for an average human, before any modifiers.
int units_absorption_per_day () const
Returns how many of this vitamin (in units) can be absorbed in one day.
int units_from_mass (vitamin_units::mass val) const
std::pair< std::string, std::string > mass_str_from_units (int units) const
Static Public Member Functions
static void load_vitamin (const JsonObject &jo)
Load vitamin from JSON definition.
static const std::map< vitamin_id, vitamin > & all ()
Get all currently loaded vitamins.
static void check_consistency ()
Check consistency of all loaded vitamins.
static void reset ()
Clear all loaded vitamins (invalidating any pointers)
Private Attributes
vitamin_id id_
vitamin_type type_ = vitamin_type::num_vitamin_types
translation name_
std::optional< vitamin_units::mass > weight_per_unit
efftype_id deficiency_
efftype_id excess_
int min_ = 0
int max_ = 0
time_duration rate_ = 0_turns
std::vector< std::pair< int, int > > disease_
std::vector< std::pair< int, int > > disease_excess_
std::vector< std::pair< vitamin_id, int > > decays_into_
std::set< std::string > flags_
Detailed Description
Definition at line 34 of file vitamin.h.
Constructor & Destructor Documentation
vitamin()
vitamin::vitamin () inline
Definition at line 37 of file vitamin.h.
 : id_( vitamin_id( "null" ) ), rate_( 1_hours ) {}
Member Function Documentation
all()
const std::map< vitamin_id, vitamin > & vitamin::all () static
Get all currently loaded vitamins.
Definition at line 101 of file vitamin.cpp.
 {
     return vitamins_all;
 }
References vitamins_all.
Referenced by Character::Character(), debug_menu::character_edit_needs_menu(), Character::clear_vitamins(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), debug_menu::faction_edit_larder_menu(), Item_factory::finalize_pre(), get_consume_needs_hint(), Character::load(), nutrients::max_in_place(), nutrients::min_in_place(), nutrients::operator==(), and Character::update_body().
check_consistency()
void vitamin::check_consistency () static
Check consistency of all loaded vitamins.
Definition at line 106 of file vitamin.cpp.
 {
     for( const auto &v : vitamins_all ) {
         if( !( v.second.deficiency_.is_null() || v.second.deficiency_.is_valid() ) ) {
             debugmsg( "vitamin %s has unknown deficiency %s", v.second.id_.c_str(),
                       v.second.deficiency_.c_str() );
         }
         if( !( v.second.excess_.is_null() || v.second.excess_.is_valid() ) ) {
             debugmsg( "vitamin %s has unknown excess %s", v.second.id_.c_str(), v.second.excess_.c_str() );
         }
     }
 }
References debugmsg, and vitamins_all.
Referenced by DynamicDataLoader::check_consistency().
decays_into()
std::vector<std::pair<vitamin_id, int> > vitamin::decays_into () const inline
An array of the other vitamins that this vitamin decays into, and their proportions.
Definition at line 88 of file vitamin.h.
{
             return decays_into_;
         }
References decays_into_.
Referenced by Character::vitamin_mod().
deficiency()
const efftype_id& vitamin::deficiency () const inline
Disease effect with increasing intensity proportional to vitamin deficiency.
Definition at line 60 of file vitamin.h.
{
             return deficiency_;
         }
References deficiency_.
Referenced by Character::update_vitamins().
excess()
const efftype_id& vitamin::excess () const inline
Disease effect with increasing intensity proportional to vitamin excess.
Definition at line 65 of file vitamin.h.
{
             return excess_;
         }
References excess_.
Referenced by Character::update_vitamins().
has_flag()
bool vitamin::has_flag (const std::string & flag) const inline
Definition at line 55 of file vitamin.h.
{
             return flags_.count( flag ) > 0;
         }
References flags_.
id()
const vitamin_id& vitamin::id () const inline
Definition at line 39 of file vitamin.h.
{
             return id_;
         }
References id_.
is_null()
bool vitamin::is_null () const inline
Definition at line 47 of file vitamin.h.
{
             return id_ == vitamin_id( "null" );
         }
References id_.
Referenced by Character::mutate_category().
load_vitamin()
void vitamin::load_vitamin (const JsonObject & jo) static
Load vitamin from JSON definition.
Definition at line 54 of file vitamin.cpp.
 {
     vitamin vit;
     vit.id_ = vitamin_id( jo.get_string( "id" ) );
     jo.read( "name", vit.name_ );
     vit.deficiency_ = efftype_id::NULL_ID();
     jo.read( "deficiency", vit.deficiency_ );
     vit.excess_ = efftype_id::NULL_ID();
     jo.read( "excess", vit.excess_ );
     vit.min_ = jo.get_int( "min" );
     vit.max_ = jo.get_int( "max", 0 );
     vit.rate_ = read_from_json_string<time_duration>( jo.get_member( "rate" ), time_duration::units );
     if( jo.has_string( "weight_per_unit" ) ) {
         vit.weight_per_unit = read_from_json_string( jo.get_member( "weight_per_unit" ),
                               vitamin_units::mass_units );
     }
     if( !jo.has_string( "vit_type" ) ) {
         jo.throw_error_at( "vit_type", "vitamin must have a vitamin type" );
     }
     vit.type_ = jo.get_enum_value<vitamin_type>( "vit_type" );
     for( JsonArray e : jo.get_array( "disease" ) ) {
         vit.disease_.emplace_back( e.get_int( 0 ), e.get_int( 1 ) );
     }
     for( JsonArray e : jo.get_array( "disease_excess" ) ) {
         vit.disease_excess_.emplace_back( e.get_int( 0 ), e.get_int( 1 ) );
     }
     for( JsonArray e : jo.get_array( "decays_into" ) ) {
         vit.decays_into_.emplace_back( vitamin_id( e.get_string( 0 ) ), e.get_int( 1 ) );
     }
     for( std::string e : jo.get_array( "flags" ) ) {
         vit.flags_.insert( e );
     }
     if( vitamins_all.find( vit.id_ ) != vitamins_all.end() ) {
         jo.throw_error_at( "id", "parsed vitamin overwrites existing definition" );
     } else {
         vitamins_all[ vit.id_ ] = vit;
     }
 }
References decays_into_, deficiency_, disease_, disease_excess_, excess_, flags_, JsonObject::get_array(), JsonObject::get_enum_value(), JsonObject::get_int(), JsonObject::get_member(), JsonObject::get_string(), JsonObject::has_string(), id_, vitamin_units::mass_units, max_, min_, name_, string_id< effect_type >::NULL_ID(), rate_, JsonObject::read(), read_from_json_string(), JsonObject::throw_error_at(), type_, time_duration::units, vitamins_all, and weight_per_unit.
Referenced by DynamicDataLoader::initialize().
mass_str_from_units()
std::pair< std::string, std::string > vitamin::mass_str_from_units (int units) const
Definition at line 148 of file vitamin.cpp.
 {
     if( !weight_per_unit.has_value() || !get_option<bool>( "SHOW_VITAMIN_MASS" ) ) {
         return {"", ""};
     }
     return weight_to_string( units * *weight_per_unit );
 }
References weight_per_unit, and weight_to_string().
max()
int vitamin::max () const inline
Upper bound for any accumulation of this vitamin.
Definition at line 75 of file vitamin.h.
{
             return max_;
         }
References max_.
Referenced by Character::vitamin_mod().
min()
int vitamin::min () const inline
Lower bound for deficiency of this vitamin.
Definition at line 70 of file vitamin.h.
{
             return min_;
         }
References min_.
Referenced by iuse::blood_draw(), eff_fun_hypovolemia(), eff_fun_redcells_anemia(), Character::update_bloodvol_index(), and Character::vitamin_mod().
name()
std::string vitamin::name () const inline
Definition at line 51 of file vitamin.h.
{
             return name_.translated();
         }
References name_, and translation::translated().
rate()
time_duration vitamin::rate () const inline
Usage rate of vitamin (time to consume unit) Lower bound is zero whereby vitamin is not required (but may still accumulate)
Definition at line 83 of file vitamin.h.
{
             return rate_;
         }
References rate_.
Referenced by Character::vitamin_rate().
RDA_to_default()
float vitamin::RDA_to_default (int percent) const
Convert standard RDA to units a character can ingest This is the default RDA for an average human, before any modifiers.
Definition at line 124 of file vitamin.cpp.
 {
     // if not a vitamin it's in Units and doesn't need conversion
     if( type_ != vitamin_type::VITAMIN ) {
         return percent;
     }
     return ( 24_hours / rate_ ) * ( static_cast<float>( percent ) / 100.0f );
 }
References rate_, type_, and VITAMIN.
reset()
void vitamin::reset () static
Clear all loaded vitamins (invalidating any pointers)
Definition at line 119 of file vitamin.cpp.
 {
     vitamins_all.clear();
 }
References vitamins_all.
Referenced by DynamicDataLoader::unload_data().
severity()
int vitamin::severity (int qty) const
Get intensity of deficiency or zero if not deficient for specified qty.
Definition at line 37 of file vitamin.cpp.
 {
     for( int i = 0; i != static_cast<int>( disease_.size() ); ++i ) {
         if( ( qty >= disease_[ i ].first && qty <= disease_[ i ].second ) ||
             ( qty <= disease_[ i ].first && qty >= disease_[ i ].second ) ) {
             return i + 1;
         }
     }
     for( int i = 0; i != static_cast<int>( disease_excess_.size() ); ++i ) {
         if( ( qty >= disease_excess_[ i ].first && qty <= disease_excess_[ i ].second ) ||
             ( qty <= disease_excess_[ i ].first && qty >= disease_excess_[ i ].second ) ) {
             return -i - 1;
         }
     }
     return 0;
 }
References disease_, disease_excess_, and second.
Referenced by Character::update_vitamins().
type()
const vitamin_type& vitamin::type () const inline
Definition at line 43 of file vitamin.h.
{
             return type_;
         }
References type_.
Referenced by Character::get_daily_vitamin(), Character::reset_daily_vitamin(), Character::update_stomach(), and Character::vitamin_get().
units_absorption_per_day()
int vitamin::units_absorption_per_day () const
Returns how many of this vitamin (in units) can be absorbed in one day.
Definition at line 133 of file vitamin.cpp.
 {
     return ( 24_hours / rate_ );
 }
References rate_.
units_from_mass()
int vitamin::units_from_mass (vitamin_units::mass val) const
Definition at line 138 of file vitamin.cpp.
 {
     if( !weight_per_unit.has_value() ) {
         debugmsg( "Tried to convert vitamin in mass to units, but %s doesn't support mass for vitamins",
                   id_.str() );
         return 1;
     }
     return val / *weight_per_unit;
 }
References debugmsg, id_, string_id< T >::str(), and weight_per_unit.
Referenced by nutrients::add_vitamin(), and nutrients::set_vitamin().
Member Data Documentation
decays_into_
std::vector<std::pair<vitamin_id, int> > vitamin::decays_into_ private
Definition at line 132 of file vitamin.h.
Referenced by decays_into(), and load_vitamin().
deficiency_
efftype_id vitamin::deficiency_ private
Definition at line 125 of file vitamin.h.
Referenced by deficiency(), and load_vitamin().
disease_
std::vector<std::pair<int, int> > vitamin::disease_ private
Definition at line 130 of file vitamin.h.
Referenced by load_vitamin(), and severity().
disease_excess_
std::vector<std::pair<int, int> > vitamin::disease_excess_ private
Definition at line 131 of file vitamin.h.
Referenced by load_vitamin(), and severity().
excess_
efftype_id vitamin::excess_ private
Definition at line 126 of file vitamin.h.
Referenced by excess(), and load_vitamin().
flags_
std::set<std::string> vitamin::flags_ private
Definition at line 133 of file vitamin.h.
Referenced by has_flag(), and load_vitamin().
id_
vitamin_id vitamin::id_ private
Definition at line 121 of file vitamin.h.
Referenced by id(), is_null(), load_vitamin(), and units_from_mass().
max_
int vitamin::max_ = 0 private
Definition at line 128 of file vitamin.h.
Referenced by load_vitamin(), and max().
min_
int vitamin::min_ = 0 private
Definition at line 127 of file vitamin.h.
Referenced by load_vitamin(), and min().
name_
translation vitamin::name_ private
Definition at line 123 of file vitamin.h.
Referenced by load_vitamin(), and name().
rate_
time_duration vitamin::rate_ = 0_turns private
Definition at line 129 of file vitamin.h.
Referenced by load_vitamin(), rate(), RDA_to_default(), and units_absorption_per_day().
type_
vitamin_type vitamin::type_ = vitamin_type::num_vitamin_types private
Definition at line 122 of file vitamin.h.
Referenced by load_vitamin(), RDA_to_default(), and type().
weight_per_unit
std::optional<vitamin_units::mass> vitamin::weight_per_unit private
Definition at line 124 of file vitamin.h.
Referenced by load_vitamin(), mass_str_from_units(), and units_from_mass().
The documentation for this class was generated from the following files:
src/vitamin.h
src/vitamin.cpp