Cataclysm DDA: computer_session Class Reference
computer_session Class Reference
#include <computer_session.h>
Public Member Functions
computer_session (computer &comp)
void use ()
Handles player use of a computer.
Private Types
enum class ynq : int { yes , no , quit }
Private Member Functions
bool hack_attempt (Character &you, int Security=-1) const
Returns true if the player successfully hacks the computer.
bool can_activate (computer_action action)
Checks whether the specified action can be activated (has any effect)
void activate_function (computer_action action)
void activate_failure (computer_failure_type fail)
void activate_random_failure ()
void reset_terminal ()
void refresh ()
void print_newline ()
template<typename ... Args>
void print_indented_line (int indent, int text_width, const std::string &text, Args &&... args)
void print_gibberish_line ()
template<typename ... Args>
void print_line (const std::string &text, Args &&... args)
template<typename ... Args>
void print_error (const std::string &text, Args &&... args)
template<typename ... Args>
void print_text (const std::string &text, Args &&... args)
template<typename ... Args>
ynq query_ynq (const std::string &text, Args &&... args)
template<typename ... Args>
bool query_bool (const std::string &text, Args &&... args)
template<typename ... Args>
bool query_any (const std::string &text, Args &&... args)
bool query_any ()
void action_amigara_log ()
void action_amigara_start ()
void action_blood_anal ()
void action_cascade ()
void action_complete_disable_external_power ()
void action_conveyor ()
void action_data_anal ()
void action_deactivate_shock_vent ()
void action_disconnect ()
void action_download_software ()
void action_elevator_on ()
void action_emerg_mess ()
void action_emerg_ref_center ()
void action_extract_rad_source ()
void action_geiger ()
void action_irradiator ()
void action_list_bionics ()
void action_list_mutations ()
void action_lock ()
void action_map_sewer ()
void action_map_subway ()
void action_maps ()
void action_miss_disarm ()
void action_miss_launch ()
void action_open ()
void action_open_gate ()
void action_close_gate ()
void action_open_disarm ()
void action_portal ()
void action_radio_archive ()
void action_release ()
void action_release_bionics ()
void action_release_disarm ()
void action_repeater_mod ()
void action_research ()
void action_sample ()
void action_shutters ()
void action_sr1_mess ()
void action_sr2_mess ()
void action_sr3_mess ()
void action_sr4_mess ()
void action_srcf_1_mess ()
void action_srcf_2_mess ()
void action_srcf_3_mess ()
void action_srcf_elevator ()
void action_srcf_seal ()
void action_srcf_seal_order ()
void action_terminate ()
void action_toll ()
void action_tower_unresponsive ()
void action_unlock ()
void action_unlock_disarm ()
void failure_alarm ()
void failure_amigara ()
void failure_damage ()
void failure_destroy_blood ()
void failure_destroy_data ()
void failure_manhacks ()
void failure_pump_explode ()
void failure_pump_leak ()
void failure_secubots ()
void failure_shutdown ()
Private Attributes
computer & comp
catacurses::window win
const int left
const int top
const int width
const int height
std::vector< std::pair< int, std::string > > lines
Static Private Attributes
static const std::map< computer_action, void(computer_session::*)()> computer_action_functions
static const std::map< computer_failure_type, void(computer_session::*)()> computer_failure_functions
Detailed Description
Definition at line 15 of file computer_session.h.
Member Enumeration Documentation
ynq
enum computer_session::ynq : int strong private
Enumerator
yes
no
quit
Definition at line 72 of file computer_session.h.
                        : int {
             yes,
             no,
             quit,
         };
Constructor & Destructor Documentation
computer_session()
computer_session::computer_session (computer & comp) explicit
Definition at line 149 of file computer_session.cpp.
                                                    : comp( comp ),
     win( init_window() ), left( 1 ), top( 1 ), width( getmaxx( win ) - 2 ),
     height( getmaxy( win ) - 2 )
 {
 }
Member Function Documentation
action_amigara_log()
void computer_session::action_amigara_log () private
Definition at line 895 of file computer_session.cpp.
 {
     get_timed_events().add( timed_event_type::AMIGARA_WHISPERS, calendar::turn + 5_minutes );
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     reset_terminal();
     point_abs_sm abs_sub = get_map().get_abs_sub().xy();
     print_line( _( "NEPower Mine%s Log" ), abs_sub.to_string() );
     print_text( "%s", SNIPPET.random_from_category( "amigara1" ).value_or( translation() ) );
     if( !query_bool( _( "Continue reading?" ) ) ) {
         return;
     }
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     reset_terminal();
     print_line( _( "NEPower Mine%s Log" ), abs_sub.to_string() );
     print_text( "%s", SNIPPET.random_from_category( "amigara2" ).value_or( translation() ) );
     if( !query_bool( _( "Continue reading?" ) ) ) {
         return;
     }
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     reset_terminal();
     print_line( _( "NEPower Mine%s Log" ), abs_sub.to_string() );
     print_text( "%s", SNIPPET.random_from_category( "amigara3" ).value_or( translation() ) );
     if( !query_bool( _( "Continue reading?" ) ) ) {
         return;
     }
     reset_terminal();
     for( int i = 0; i < 10; i++ ) {
         print_gibberish_line();
     }
     print_newline();
     print_newline();
     print_newline();
     print_line( _( "AMIGARA PROJECT" ) );
     print_newline();
     print_newline();
     if( !query_bool( _( "Continue reading?" ) ) ) {
         return;
     }
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     reset_terminal();
     tripoint_abs_sm abs_loc = get_map().get_abs_sub();
     print_line( _( "SITE %d%d%d\n"
                    "PERTINENT FOREMAN LOGS WILL BE PREPENDED TO NOTES" ),
                 abs_loc.x(), abs_loc.y(), std::abs( abs_loc.z() ) );
     print_text( "%s", SNIPPET.random_from_category( "amigara4" ).value_or( translation() ) );
     print_gibberish_line();
     print_gibberish_line();
     print_newline();
     print_error( _( "FILE CORRUPTED, PRESS ANY KEY" ) );
     query_any();
     reset_terminal();
 }
References _, abs(), timed_event_manager::add(), AMIGARA_WHISPERS, map::get_abs_sub(), get_map(), get_player_character(), get_timed_events(), Creature::mod_moves(), print_error(), print_gibberish_line(), print_line(), print_newline(), print_text(), query_any(), query_bool(), snippet_library::random_from_category(), reset_terminal(), SNIPPET, coords::coord_point_base< Point >::to_string(), calendar::turn, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
action_amigara_start()
void computer_session::action_amigara_start () private
Definition at line 953 of file computer_session.cpp.
 {
     get_timed_events().add( timed_event_type::AMIGARA, calendar::turn + 10_seconds );
     // Disable this action to prevent further amigara events, which would lead to
     // further amigara monster, which would lead to further artifacts.
     comp.remove_option( COMPACT_AMIGARA_START );
 }
References timed_event_manager::add(), AMIGARA, comp, COMPACT_AMIGARA_START, get_timed_events(), computer::remove_option(), and calendar::turn.
action_blood_anal()
void computer_session::action_blood_anal () private
Definition at line 1040 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.7 );
     map &here = get_map();
     for( const tripoint &dest : here.points_in_radius( player_character.pos(), 2 ) ) {
         if( here.furn( dest ) == furn_f_centrifuge ) {
             map_stack items = here.i_at( dest );
             if( items.empty() ) {
                 print_error( _( "ERROR: Please place sample in centrifuge." ) );
             } else if( items.size() > 1 ) {
                 print_error( _( "ERROR: Please remove all but one sample from centrifuge." ) );
             } else if( items.only_item().empty() ) {
                 print_error( _( "ERROR: Please only use container with blood sample." ) );
             } else if( items.only_item().legacy_front().typeId() != itype_blood &&
                        items.only_item().legacy_front().typeId() != itype_blood_tainted ) {
                 print_error( _( "ERROR: Please only use blood samples." ) );
             } else { // Success!
                 const item &blood = items.only_item().legacy_front();
                 const mtype *mt = blood.get_mtype();
                 if( mt == nullptr || mt->id == mtype_id::NULL_ID() ) {
                     print_line( _( "Result: Human blood, no pathogens found." ) );
                 } else if( mt->in_species( species_ZOMBIE ) ) {
                     if( mt->in_species( species_HUMAN ) ) {
                         print_line( _( "Result: Human blood.  Unknown pathogen found." ) );
                     } else {
                         print_line( _( "Result: Unknown blood type.  Unknown pathogen found." ) );
                     }
                     print_line( _( "Pathogen bonded to erythrocytes and leukocytes." ) );
                     if( query_bool( _( "Download data?" ) ) ) {
                         if( item *const usb = pick_usb() ) {
                             item software( "software_blood_data", calendar::turn_zero );
                             usb->clear_items();
                             usb->put_in( software, pocket_type::SOFTWARE );
                             print_line( _( "Software downloaded." ) );
                         } else {
                             print_error( _( "USB drive required!" ) );
                         }
                     }
                 } else {
                     print_line( _( "Result: Unknown blood type.  Test non-conclusive." ) );
                 }
             }
         }
     }
     query_any( _( "Press any key" ) );
 }
References _, item::empty(), item_stack::empty(), map::furn(), furn_f_centrifuge, get_map(), item::get_mtype(), get_player_character(), map::i_at(), mtype::id, mtype::in_species(), itype_blood, itype_blood_tainted, item::legacy_front(), Creature::mod_moves(), string_id< mtype >::NULL_ID(), item_stack::only_item(), pick_usb(), map::points_in_radius(), Creature::pos(), print_error(), print_line(), query_any(), query_bool(), item_stack::size(), SOFTWARE, species_HUMAN, species_ZOMBIE, calendar::turn_zero, and item::typeId().
action_cascade()
void computer_session::action_cascade () private
Definition at line 608 of file computer_session.cpp.
 {
     if( !query_bool( _( "WARNING: Resonance cascade carries severe risk!  Continue?" ) ) ) {
         return;
     }
     get_event_bus().send<event_type::causes_resonance_cascade>();
     tripoint player_pos = get_player_character().pos();
     map &here = get_map();
     std::vector<tripoint> cascade_points;
     for( const tripoint &dest : here.points_in_radius( player_pos, 10 ) ) {
         if( here.ter( dest ) == ter_t_radio_tower ) {
             cascade_points.push_back( dest );
         }
     }
     explosion_handler::resonance_cascade( random_entry( cascade_points, player_pos ) );
 }
References _, causes_resonance_cascade, get_event_bus(), get_map(), get_player_character(), map::points_in_radius(), Creature::pos(), query_bool(), random_entry(), explosion_handler::resonance_cascade(), event_bus::send(), map::ter(), and ter_t_radio_tower.
action_close_gate()
void computer_session::action_close_gate () private
Definition at line 452 of file computer_session.cpp.
 {
     get_map().translate_radius( ter_t_metal_floor, ter_t_wall_metal, 8.0, get_player_character().pos(),
                                 true );
     query_any( _( "Gates closed.  Press any key" ) );
 }
References _, get_map(), get_player_character(), math_opers::pos(), query_any(), ter_t_metal_floor, ter_t_wall_metal, and map::translate_radius().
action_complete_disable_external_power()
void computer_session::action_complete_disable_external_power () private
Definition at line 961 of file computer_session.cpp.
 {
     for( mission *miss : get_avatar().get_active_missions() ) {
         static const mission_type_id commo_2 = mission_MISSION_OLD_GUARD_NEC_COMMO_2;
         if( miss->mission_id() == commo_2 ) {
             print_error( _( "--ACCESS GRANTED--" ) );
             print_error( _( "Mission Complete!" ) );
             miss->step_complete( 1 );
             query_any();
             return;
         }
     }
     print_error( _( "ACCESS DENIED" ) );
     query_any();
 }
References _, get_avatar(), mission_MISSION_OLD_GUARD_NEC_COMMO_2, print_error(), and query_any().
action_conveyor()
void computer_session::action_conveyor () private
Definition at line 1438 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 3_seconds ) );
     tripoint loading; // red tile = loading bay
     tripoint unloading; // green tile = unloading bay
     tripoint platform; // radiation platform = middle point
     bool l_exists = false;
     bool u_exists = false;
     bool p_exists = false;
     map &here = get_map();
     for( const tripoint &dest : here.points_in_radius( player_character.pos(), 10 ) ) {
         if( here.ter( dest ) == ter_t_rad_platform ) {
             platform = dest;
             p_exists = true;
         } else if( here.ter( dest ) == ter_t_floor_red ) {
             loading = dest;
             l_exists = true;
         } else if( here.ter( dest ) == ter_t_floor_green ) {
             unloading = dest;
             u_exists = true;
         }
     }
     if( !l_exists || !p_exists || !u_exists ) {
         print_error( _( "Conveyor belt malfunction.  Consult maintenance team." ) );
         query_any( _( "Press any key" ) );
         return;
     }
     map_stack items = here.i_at( platform );
     if( !items.empty() ) {
         print_line( _( "Moving items: PLATFORM --> UNLOADING BAY." ) );
     } else {
         print_line( _( "No items detected at: PLATFORM." ) );
     }
     for( const item &it : items ) {
         here.add_item_or_charges( unloading, it );
     }
     here.i_clear( platform );
     items = here.i_at( loading );
     if( !items.empty() ) {
         print_line( _( "Moving items: LOADING BAY --> PLATFORM." ) );
     } else {
         print_line( _( "No items detected at: LOADING BAY." ) );
     }
     for( const item &it : items ) {
         if( !it.made_of_from_type( phase_id::LIQUID ) ) {
             here.add_item_or_charges( platform, it );
         }
     }
     here.i_clear( loading );
     query_any( _( "Conveyor belt cycle complete.  Press any key" ) );
 }
References _, map::add_item_or_charges(), item_stack::empty(), get_map(), get_player_character(), map::i_at(), map::i_clear(), LIQUID, Creature::mod_moves(), map::points_in_radius(), Creature::pos(), print_error(), print_line(), query_any(), map::ter(), ter_t_floor_green, ter_t_floor_red, and ter_t_rad_platform.
action_data_anal()
void computer_session::action_data_anal () private
Definition at line 1088 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     map &here = get_map();
     for( const tripoint &dest : here.points_in_radius( player_character.pos(), 2 ) ) {
         if( here.ter( dest ) == ter_t_floor_blue ) {
             print_error( _( "PROCESSING DATA" ) );
             map_stack items = here.i_at( dest );
             if( items.empty() ) {
                 print_error( _( "ERROR: Please place memory bank in scan area." ) );
             } else if( items.size() > 1 ) {
                 print_error( _( "ERROR: Please only scan one item at a time." ) );
             } else if( items.only_item().typeId() != itype_usb_drive &&
                        items.only_item().typeId() != itype_black_box ) {
                 print_error( _( "ERROR: Memory bank destroyed or not present." ) );
             } else if( items.only_item().typeId() == itype_usb_drive &&
                        items.only_item().empty() ) {
                 print_error( _( "ERROR: Memory bank is empty." ) );
             } else { // Success!
                 if( items.only_item().typeId() == itype_black_box ) {
                     print_line( _( "Memory Bank: Military Hexron Encryption\nPrinting Transcript\n" ) );
                     item transcript( "black_box_transcript", calendar::turn );
                     here.add_item_or_charges( player_character.pos(), transcript );
                 } else {
                     print_line( _( "Memory Bank: Unencrypted\nNothing of interest.\n" ) );
                 }
             }
         }
     }
     query_any( _( "Press any key" ) );
 }
References _, map::add_item_or_charges(), item::empty(), item_stack::empty(), get_map(), get_player_character(), map::i_at(), itype_black_box, itype_usb_drive, Creature::mod_moves(), item_stack::only_item(), map::points_in_radius(), Creature::pos(), print_error(), print_line(), query_any(), item_stack::size(), map::ter(), ter_t_floor_blue, calendar::turn, and item::typeId().
action_deactivate_shock_vent()
void computer_session::action_deactivate_shock_vent () private
Definition at line 1531 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     bool has_vent = false;
     map &here = get_map();
     for( const tripoint &dest : here.points_in_radius( player_character.pos(), 10 ) ) {
         if( here.get_field( dest, fd_shock_vent ) != nullptr ) {
             has_vent = true;
         }
         here.remove_field( dest, fd_shock_vent );
     }
     print_line( _( "Initiating POWER-DIAG ver.2.34" ) );
     if( has_vent ) {
         print_error( _( "Short circuit detected!" ) );
         print_error( _( "Short circuit rerouted." ) );
         print_error( _( "Fuse reset." ) );
         print_error( _( "Ground re-enabled." ) );
     } else {
         print_line( _( "Internal power lines status: 85%% OFFLINE.  Reason: DAMAGED." ) );
     }
     print_line(
         _( "External power lines status: 100%% OFFLINE.  Reason: NO EXTERNAL POWER DETECTED." ) );
     print_line( _( "Backup power status: STANDBY MODE." ) );
     query_any( _( "Press any key" ) );
 }
References _, fd_shock_vent, map::get_field(), get_map(), get_player_character(), Creature::mod_moves(), map::points_in_radius(), Creature::pos(), print_error(), print_line(), query_any(), and map::remove_field().
action_disconnect()
void computer_session::action_disconnect () private
Definition at line 1121 of file computer_session.cpp.
 {
     reset_terminal();
     print_line( _( "\n"
                    "ERROR: NETWORK DISCONNECT\n"
                    "UNABLE TO REACH NETWORK ROUTER OR PROXY.  PLEASE CONTACT YOUR\n"
                    "SYSTEM ADMINISTRATOR TO RESOLVE THIS ISSUE.\n"
                    "  \n" ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_line(), query_any(), and reset_terminal().
action_download_software()
void computer_session::action_download_software () private
Definition at line 1020 of file computer_session.cpp.
 {
     if( item *const usb = pick_usb() ) {
         mission *miss = mission::find( comp.mission_id );
         if( miss == nullptr ) {
             debugmsg( _( "Computer couldn't find its mission!" ) );
             return;
         }
         get_player_character().mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
         item software( miss->get_item_id(), calendar::turn_zero );
         software.mission_id = comp.mission_id;
         usb->clear_items();
         usb->put_in( software, pocket_type::SOFTWARE );
         print_line( _( "Software downloaded." ) );
     } else {
         print_error( _( "USB drive required!" ) );
     }
     query_any();
 }
References _, comp, debugmsg, mission::find(), mission::get_item_id(), get_player_character(), computer::mission_id, item::mission_id, Creature::mod_moves(), pick_usb(), print_error(), print_line(), query_any(), SOFTWARE, and calendar::turn_zero.
action_elevator_on()
void computer_session::action_elevator_on () private
Definition at line 884 of file computer_session.cpp.
 {
     map &here = get_map();
     for( const tripoint &p : here.points_on_zlevel() ) {
         if( here.ter( p ) == ter_t_elevator_control_off ) {
             here.ter_set( p, ter_t_elevator_control );
         }
     }
     query_any( _( "Elevator activated.  Press any key" ) );
 }
References _, get_map(), map::points_on_zlevel(), query_any(), map::ter(), map::ter_set(), ter_t_elevator_control, and ter_t_elevator_control_off.
action_emerg_mess()
void computer_session::action_emerg_mess () private
Definition at line 1132 of file computer_session.cpp.
 {
     print_line( _( "GREETINGS CITIZEN.  A BIOLOGICAL ATTACK HAS TAKEN PLACE AND A STATE OF\n"
                    "EMERGENCY HAS BEEN DECLARED.  EMERGENCY PERSONNEL WILL BE AIDING YOU\n"
                    "SHORTLY.  TO ENSURE YOUR SAFETY PLEASE FOLLOW THE STEPS BELOW.\n"
                    "\n"
                    "1. DO NOT PANIC.\n"
                    "2. REMAIN INSIDE THE BUILDING.\n"
                    "3. SEEK SHELTER IN THE BASEMENT.\n"
                    "4. USE PROVIDED GAS MASKS.\n"
                    "5. AWAIT FURTHER INSTRUCTIONS.\n"
                    "\n"
                    "  \n" ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_line(), and query_any().
action_emerg_ref_center()
void computer_session::action_emerg_ref_center () private
Definition at line 1761 of file computer_session.cpp.
 {
     reset_terminal();
     print_line( _( "SEARCHING FOR NEAREST REFUGEE CENTER, PLEASE WAIT" ) );
     tripoint_abs_omt mission_target;
     avatar &player_character = get_avatar();
     // Check completed missions too, so people can't repeatedly get the mission.
     const std::vector<mission *> completed_missions = player_character.get_completed_missions();
     std::vector<mission *> missions = player_character.get_active_missions();
     missions.insert( missions.end(), completed_missions.begin(), completed_missions.end() );
     auto is_refugee_mission = [ &mission_target ]( mission * mission ) {
         if( mission->get_type().id == mission_MISSION_REACH_REFUGEE_CENTER ) {
             mission_target = mission->get_target();
             return true;
         }
         return false;
     };
     const bool has_mission = std::any_of( missions.begin(), missions.end(), is_refugee_mission );
     if( !has_mission ) {
         mission *new_mission =
             mission::reserve_new( mission_MISSION_REACH_REFUGEE_CENTER, character_id() );
         new_mission->assign( player_character );
         mission_target = new_mission->get_target();
     }
     //~555-0164 is a fake phone number in the US, please replace it with a number that will not cause issues in your locale if possible.
     print_line( _( "\nREFUGEE CENTER FOUND!  LOCATION: %d %s\n\n"
                    "IF YOU HAVE ANY FEEDBACK CONCERNING YOUR VISIT PLEASE CONTACT\n"
                    "THE DEPARTMENT OF EMERGENCY MANAGEMENT PUBLIC AFFAIRS OFFICE.\n"
                    "THE LOCAL OFFICE CAN BE REACHED BETWEEN THE HOURS OF 9AM AND\n"
                    "4PM AT 555-0164.\n"
                    "\n"
                    "IF YOU WOULD LIKE TO SPEAK WITH SOMEONE IN PERSON OR WOULD LIKE\n"
                    "TO WRITE US A LETTER PLEASE SEND IT TO\n" ),
                 rl_dist( player_character.global_omt_location(), mission_target ),
                 direction_name_short(
                     direction_from( player_character.global_omt_location(), mission_target ) ) );
     query_any( _( "Press any key to continue" ) );
     reset_terminal();
 }
References _, mission::assign(), character_id, direction_from(), direction_name_short(), avatar::get_active_missions(), get_avatar(), avatar::get_completed_missions(), mission::get_target(), mission::get_type(), Creature::global_omt_location(), mission_type::id, mission_MISSION_REACH_REFUGEE_CENTER, print_line(), query_any(), mission::reserve_new(), reset_terminal(), and rl_dist().
action_extract_rad_source()
void computer_session::action_extract_rad_source () private
Definition at line 1504 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     if( query_yn( _( "Operation irreversible.  Extract radioactive material?" ) ) ) {
         player_character.mod_moves( -to_moves<int>( 3_seconds ) );
         tripoint platform;
         bool p_exists = false;
         map &here = get_map();
         for( const tripoint &dest : here.points_in_radius( player_character.pos(), 10 ) ) {
             if( here.ter( dest ) == ter_t_rad_platform ) {
                 platform = dest;
                 p_exists = true;
             }
         }
         if( p_exists ) {
             here.spawn_item( platform, itype_cobalt_60, rng( 8, 15 ) );
             here.translate_radius( ter_t_rad_platform, ter_t_concrete, 8.0, player_character.pos(), true );
             comp.remove_option( COMPACT_IRRADIATOR );
             comp.remove_option( COMPACT_EXTRACT_RAD_SOURCE );
             query_any( _( "Extraction sequence complete  Press any key." ) );
         } else {
             query_any( _( "ERROR!  Radiation platform unresponsive  Press any key." ) );
         }
     }
 }
References _, comp, COMPACT_EXTRACT_RAD_SOURCE, COMPACT_IRRADIATOR, get_map(), get_player_character(), itype_cobalt_60, Creature::mod_moves(), map::points_in_radius(), Creature::pos(), query_any(), query_yn(), computer::remove_option(), rng(), map::spawn_item(), map::ter(), ter_t_concrete, ter_t_rad_platform, and map::translate_radius().
action_geiger()
void computer_session::action_geiger () private
Definition at line 1395 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     tripoint platform;
     bool source_exists = false;
     int sum_rads = 0;
     int peak_rad = 0;
     int tiles_counted = 0;
     map &here = get_map();
     print_error( _( "RADIATION MEASUREMENTS:" ) );
     for( const tripoint &dest : here.points_in_radius( player_character.pos(), 10 ) ) {
         if( here.ter( dest ) == ter_t_rad_platform ) {
             source_exists = true;
             platform = dest;
         }
     }
     if( source_exists ) {
         for( const tripoint &dest : here.points_in_radius( platform, 3 ) ) {
             sum_rads += here.get_radiation( dest );
             tiles_counted ++;
             if( here.get_radiation( dest ) > peak_rad ) {
                 peak_rad = here.get_radiation( dest );
             }
             sum_rads += here.get_radiation( platform );
             tiles_counted ++;
             if( here.get_radiation( platform ) > peak_rad ) {
                 peak_rad = here.get_radiation( platform );
             }
         }
         print_error( _( "GEIGER COUNTER @ ZONE: AVG %s mSv/h." ), sum_rads / tiles_counted );
         print_error( _( "GEIGER COUNTER @ ZONE: MAX %s mSv/h." ), peak_rad );
         print_newline();
     }
     print_error( _( "GEIGER COUNTER @ CONSOLE: %s mSv/h." ),
                  here.get_radiation( player_character.pos() ) );
     print_error( _( "PERSONAL DOSIMETRY: %s mSv." ), player_character.get_rad() );
     print_newline();
     query_any( _( "Press any key" ) );
 }
References _, get_map(), get_player_character(), Character::get_rad(), map::get_radiation(), Creature::mod_moves(), map::points_in_radius(), Creature::pos(), print_error(), print_newline(), query_any(), map::ter(), and ter_t_rad_platform.
action_irradiator()
void computer_session::action_irradiator () private
Definition at line 1316 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     bool error = false;
     bool platform_exists = false;
     map &here = get_map();
     for( const tripoint &dest : here.points_in_radius( player_character.pos(), 10 ) ) {
         if( here.ter( dest ) == ter_t_rad_platform ) {
             platform_exists = true;
             if( here.i_at( dest ).empty() ) {
                 print_error( _( "ERROR: Processing platform empty." ) );
             } else {
                 player_character.mod_moves( -to_moves<int>( 3_seconds ) );
                 for( auto it = here.i_at( dest ).begin(); it != here.i_at( dest ).end(); ++it ) {
                     // actual food processing
                     if( !it->rotten() ) {
                         it->set_flag( flag_IRRADIATED );
                     }
                     // critical failure - radiation spike sets off electronic detonators
                     if( it->typeId() == itype_mininuke || it->typeId() == itype_mininuke_act ||
                         it->typeId() == itype_c4 ) {
                         explosion_handler::explosion( &get_player_character(), dest, 40 );
                         reset_terminal();
                         print_error( _( "WARNING [409]: Primary sensors offline!" ) );
                         print_error( _( "  >> Initialize secondary sensors: Geiger profiling" ) );
                         print_error( _( "  >> Radiation spike detected!\n" ) );
                         print_error( _( "WARNING [912]: Catastrophic malfunction!  Contamination detected!" ) );
                         print_error( _( "EMERGENCY PROCEDURE [1]:  Evacuate.  Evacuate.  Evacuate.\n" ) );
                         sounds::sound( player_character.pos(), 30, sounds::sound_t::alarm, _( "an alarm sound!" ), false,
                                        "environment",
                                        "alarm" );
                         here.i_rem( dest, it );
                         here.make_rubble( dest );
                         here.propagate_field( dest, fd_nuke_gas, 100, 3 );
                         here.translate_radius( ter_t_water_pool, ter_t_sewage, 8.0, dest, true );
                         here.adjust_radiation( dest, rng( 50, 500 ) );
                         for( const tripoint &radorigin : here.points_in_radius( dest, 5 ) ) {
                             here.adjust_radiation( radorigin, rng( 50, 500 ) / ( rl_dist( radorigin,
                                                    dest ) > 0 ? rl_dist( radorigin, dest ) : 1 ) );
                         }
                         if( here.pl_sees( dest, 10 ) ) {
                             player_character.irradiate( rng_float( 50, 250 ) / rl_dist( player_character.pos(), dest ) );
                         } else {
                             player_character.irradiate( rng_float( 20, 100 ) / rl_dist( player_character.pos(), dest ) );
                         }
                         query_any( _( "EMERGENCY SHUTDOWN!  Press any key" ) );
                         error = true;
                         comp.options.clear(); // Disable the terminal.
                         activate_failure( COMPFAIL_SHUTDOWN );
                         break;
                     }
                     here.adjust_radiation( dest, rng( 20, 50 ) );
                     for( const tripoint &radorigin : here.points_in_radius( dest, 5 ) ) {
                         here.adjust_radiation( radorigin, rng( 20, 50 ) / ( rl_dist( radorigin,
                                                dest ) > 0 ? rl_dist( radorigin, dest ) : 1 ) );
                     }
                     // if unshielded, rad source irradiates player directly, reduced by distance to source
                     if( here.pl_sees( dest, 10 ) ) {
                         player_character.irradiate( rng_float( 5, 25 ) / rl_dist( player_character.pos(), dest ) );
                     }
                 }
                 if( !error && platform_exists ) {
                     print_error( _( "PROCESSING  CYCLE COMPLETE." ) );
                     print_error( _( "GEIGER COUNTER @ PLATFORM: %s mSv/h." ), here.get_radiation( dest ) );
                 }
             }
         }
     }
     if( !platform_exists ) {
         print_error(
             _( "CRITICAL ERROR  RADIATION PLATFORM UNRESPONSIVE.  COMPLY TO PROCEDURE RP_M_01_rev.03." ) );
     }
     if( !error ) {
         query_any( _( "Press any key" ) );
     }
 }
References _, activate_failure(), map::adjust_radiation(), sounds::alarm, item_stack::begin(), comp, COMPFAIL_SHUTDOWN, item_stack::empty(), item_stack::end(), error, explosion_handler::explosion(), fd_nuke_gas, flag_IRRADIATED, get_map(), get_player_character(), map::get_radiation(), map::i_at(), map::i_rem(), Character::irradiate(), itype_c4, itype_mininuke, itype_mininuke_act, map::make_rubble(), Creature::mod_moves(), computer::options, map::pl_sees(), map::points_in_radius(), Creature::pos(), print_error(), map::propagate_field(), query_any(), reset_terminal(), rl_dist(), rng(), rng_float(), sounds::sound(), map::ter(), ter_t_rad_platform, ter_t_sewage, ter_t_water_pool, and map::translate_radius().
action_list_bionics()
void computer_session::action_list_bionics () private
Definition at line 791 of file computer_session.cpp.
 {
     get_player_character().mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     std::vector<std::string> names;
     int more = 0;
     map &here = get_map();
     for( const tripoint &p : here.points_on_zlevel() ) {
         for( item &elem : here.i_at( p ) ) {
             if( elem.is_bionic() ) {
                 if( static_cast<int>( names.size() ) < TERMY - 8 ) {
                     names.push_back( elem.type_name() );
                 } else {
                     more++;
                 }
             }
         }
     }
     reset_terminal();
     print_newline();
     print_line( _( "Bionic access - Manifest:" ) );
     print_newline();
     for( auto &name : names ) {
         print_line( "%s", name );
     }
     if( more > 0 ) {
         print_line( n_gettext( "%d OTHER FOUND", "%d OTHERS FOUND", more ), more );
     }
     print_newline();
     query_any( _( "Press any key" ) );
 }
References _, get_map(), get_player_character(), map::i_at(), Creature::mod_moves(), n_gettext, om_direction::name(), PATH_INFO::names(), map::points_on_zlevel(), print_line(), print_newline(), query_any(), reset_terminal(), and TERMY.
action_list_mutations()
void computer_session::action_list_mutations () private
Definition at line 826 of file computer_session.cpp.
 {
     uilist ssmenu;
     std::vector<std::pair<std::string, mutation_category_id>> mutation_categories_list;
     mutation_categories_list.reserve( mutations_category.size() );
     for( const std::pair<const mutation_category_id, std::vector<trait_id> > &mut_cat :
          mutations_category ) {
         mutation_categories_list.emplace_back( mut_cat.first.c_str(), mut_cat.first );
     }
     ssmenu.text = _( "Choose mutation category" );
     std::sort( mutation_categories_list.begin(), mutation_categories_list.end(), localized_compare );
     int menu_ind = 0;
     for( const std::pair<std::string, mutation_category_id> &mut_cat : mutation_categories_list ) {
         ssmenu.addentry( menu_ind, true, MENU_AUTOASSIGN, mut_cat.first );
         ++menu_ind;
     }
     ssmenu.query();
     if( ssmenu.ret >= 0 && ssmenu.ret < static_cast< int >( mutation_categories_list.size() ) ) {
         const mutation_category_trait &category = mutation_category_trait::get_category(
                     mutation_categories_list[ssmenu.ret].second );
         const std::vector<trait_id> category_mutations = mutations_category[category.id];
         uilist wmenu;
         wmenu.w_x_setup = 30;
         for( const trait_id &traits_iter : category_mutations ) {
             wmenu.addentry( -1, true, -2, traits_iter.obj().name() );
         }
         do {
             wmenu.query();
             if( wmenu.ret >= 0 && wmenu.ret < static_cast< int >( category_mutations.size() ) ) {
                 const mutation_branch &mdata = category_mutations[wmenu.ret].obj();
                 reset_terminal();
                 print_text( _( "Description: %s" ), colorize( mdata.desc(), c_white ) );
                 if( !mdata.replacements.empty() ) {
                     print_indented_line( 1, width - 2, _( "Changes to:" ) );
                     for( const trait_id &replacement : mdata.replacements ) {
                         print_indented_line( 1, width - 2, _( "%s" ), colorize( replacement->name(), c_white ) );
                     }
                     print_newline();
                 }
                 if( !mdata.cancels.empty() ) {
                     print_indented_line( 1, width - 2, _( "Cancels:" ) );
                     for( const trait_id &cancel : mdata.cancels ) {
                         print_indented_line( 1, width - 2, _( "%s" ), colorize( cancel->name(), c_white ) );
                     }
                 }
             }
         } while( wmenu.ret >= 0 );
     }
 }
References _, uilist::addentry(), c_white, cancel, mutation_branch::cancels, anonymous_namespace{item_tname.cpp}::category(), colorize(), mutation_branch::desc(), mutation_category_trait::get_category(), localized_compare, MENU_AUTOASSIGN, mutations_category, print_indented_line(), print_newline(), print_text(), uilist::query(), replacement, mutation_branch::replacements, reset_terminal(), uilist::ret, uilist::text, uilist::w_x_setup, and width.
action_lock()
void computer_session::action_lock () private
Definition at line 464 of file computer_session.cpp.
 {
     get_map().translate_radius( ter_t_door_metal_c, ter_t_door_metal_locked, 8.0,
                                 get_player_character().pos(),
                                 true );
     query_any( _( "Lock enabled.  Press any key" ) );
 }
References _, get_map(), get_player_character(), math_opers::pos(), query_any(), ter_t_door_metal_c, ter_t_door_metal_locked, and map::translate_radius().
action_map_sewer()
void computer_session::action_map_sewer () private
Definition at line 680 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     const tripoint_abs_omt center = player_character.global_omt_location();
     for( int i = -60; i <= 60; i++ ) {
         for( int j = -60; j <= 60; j++ ) {
             point offset( i, j );
             const oter_id &oter = overmap_buffer.ter( center + offset );
             if( ( oter->get_type_id() == oter_type_sewer ) ||
                 is_ot_match( "sewage", oter, ot_match_type::prefix ) ) {
                 overmap_buffer.set_seen( center + offset, true );
             }
         }
     }
     query_any( _( "Sewage map data downloaded.  Press any key" ) );
     comp.remove_option( COMPACT_MAP_SEWER );
 }
References _, center, comp, COMPACT_MAP_SEWER, get_player_character(), oter_t::get_type_id(), Creature::global_omt_location(), is_ot_match(), Creature::mod_moves(), oter_type_sewer, overmap_buffer, prefix, query_any(), computer::remove_option(), overmapbuffer::set_seen(), and overmapbuffer::ter().
action_map_subway()
void computer_session::action_map_subway () private
Definition at line 699 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     const tripoint_abs_omt center = player_character.global_omt_location();
     for( int i = -60; i <= 60; i++ ) {
         for( int j = -60; j <= 60; j++ ) {
             point offset( i, j );
             const oter_id &oter = overmap_buffer.ter( center + offset );
             if( ( oter->get_type_id() == oter_type_subway ) ||
                 is_ot_match( "lab_train_depot", oter, ot_match_type::contains ) ) {
                 overmap_buffer.set_seen( center + offset, true );
             }
         }
     }
     query_any( _( "Subway map data downloaded.  Press any key" ) );
     comp.remove_option( COMPACT_MAP_SUBWAY );
 }
References _, center, comp, COMPACT_MAP_SUBWAY, contains, get_player_character(), oter_t::get_type_id(), Creature::global_omt_location(), is_ot_match(), Creature::mod_moves(), oter_type_subway, overmap_buffer, query_any(), computer::remove_option(), overmapbuffer::set_seen(), and overmapbuffer::ter().
action_maps()
void computer_session::action_maps () private
Definition at line 668 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     const tripoint_abs_omt center = player_character.global_omt_location();
     overmap_buffer.reveal( center.xy(), 40, 0 );
     query_any(
         _( "Surface map data downloaded.  Local anomalous-access error logged.  Press any key" ) );
     comp.remove_option( COMPACT_MAPS );
     comp.alerts ++;
 }
References _, computer::alerts, center, comp, COMPACT_MAPS, get_player_character(), Creature::global_omt_location(), Creature::mod_moves(), overmap_buffer, query_any(), computer::remove_option(), and overmapbuffer::reveal().
action_miss_disarm()
void computer_session::action_miss_disarm () private
Definition at line 718 of file computer_session.cpp.
 {
     // TODO: stop the nuke from creating radioactive clouds.
     if( query_yn( _( "Disarm missile." ) ) ) {
         get_event_bus().send<event_type::disarms_nuke>();
         add_msg( m_info, _( "Nuclear missile disarmed!" ) );
         //disable missile.
         comp.options.clear();
         activate_failure( COMPFAIL_SHUTDOWN );
     } else {
         add_msg( m_neutral, _( "Nuclear missile remains active." ) );
         return;
     }
 }
References _, activate_failure(), add_msg(), comp, COMPFAIL_SHUTDOWN, disarms_nuke, get_event_bus(), m_info, m_neutral, computer::options, query_yn(), and event_bus::send().
action_miss_launch()
void computer_session::action_miss_launch () private
Definition at line 733 of file computer_session.cpp.
 {
     // Target Acquisition.
     const tripoint_abs_omt target( ui::omap::choose_point( 0 ) );
     if( target == overmap::invalid_tripoint ) {
         add_msg( m_info, _( "Target acquisition canceled." ) );
         return;
     }
     if( query_yn( _( "Confirm nuclear missile launch." ) ) ) {
         add_msg( m_info, _( "Nuclear missile launched!" ) );
         //Remove the option to fire another missile.
         comp.options.clear();
     } else {
         add_msg( m_info, _( "Nuclear missile launch aborted." ) );
         return;
     }
     //Put some smoke gas and explosions at the nuke location.
     const tripoint nuke_location = { get_player_character().pos() - point( 12, 0 ) };
     for( const tripoint &loc : get_map().points_in_radius( nuke_location, 5, 0 ) ) {
         if( one_in( 4 ) ) {
             get_map().add_field( loc, fd_smoke, rng( 1, 9 ) );
         }
     }
     //Only explode once. But make it large.
     explosion_handler::explosion( &get_player_character(), nuke_location, 2000, 0.7, true );
     //...ERASE MISSILE, OPEN SILO, DISABLE COMPUTER
     // For each level between here and the surface, remove the missile
     for( int level = get_map().get_abs_sub().z(); level <= 0; level++ ) {
         map tmpmap;
         tmpmap.load( tripoint_abs_sm( get_map().get_abs_sub().xy(), level ),
                      false );
         if( level < 0 ) {
             tmpmap.translate( ter_t_missile, ter_t_hole );
         } else {
             tmpmap.translate( ter_t_metal_floor, ter_t_hole );
         }
         tmpmap.save();
     }
     for( const tripoint_abs_omt &p : points_in_radius( target, 2 ) ) {
         // give it a nice rounded shape
         if( !( p.x() == target.x() - 2 && p.y() == target.y() - 2 ) &&
             !( p.x() == target.x() - 2 && p.y() == target.y() + 2 ) &&
             !( p.x() == target.x() + 2 && p.y() == target.y() - 2 ) &&
             !( p.x() == target.x() + 2 && p.y() == target.y() + 2 ) ) {
             overmap_buffer.ter_set( p, oter_id( "field" ) );
         }
     }
     explosion_handler::nuke( target );
     activate_failure( COMPFAIL_SHUTDOWN );
 }
References _, activate_failure(), map::add_field(), add_msg(), ui::omap::choose_point(), comp, COMPFAIL_SHUTDOWN, explosion_handler::explosion(), fd_smoke, get_map(), get_player_character(), overmap::invalid_tripoint, map::load(), m_info, explosion_handler::nuke(), one_in(), computer::options, oter_id, overmap_buffer, point, points_in_radius(), Creature::pos(), query_yn(), rng(), map::save(), overmapbuffer::ter_set(), ter_t_hole, ter_t_metal_floor, ter_t_missile, map::translate(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
action_open()
void computer_session::action_open () private
Definition at line 437 of file computer_session.cpp.
 {
     get_map().translate_radius( ter_t_door_metal_locked, ter_t_floor, 25.0,
                                 get_player_character().pos(),
                                 true );
     query_any( _( "Doors opened.  Press any key" ) );
 }
References _, get_map(), get_player_character(), math_opers::pos(), query_any(), ter_t_door_metal_locked, ter_t_floor, and map::translate_radius().
Referenced by action_open_disarm().
action_open_disarm()
void computer_session::action_open_disarm () private
Definition at line 431 of file computer_session.cpp.
 {
     remove_submap_turrets();
     action_open();
 }
References action_open(), and remove_submap_turrets().
action_open_gate()
void computer_session::action_open_gate () private
Definition at line 445 of file computer_session.cpp.
 {
     get_map().translate_radius( ter_t_wall_metal, ter_t_metal_floor, 8.0, get_player_character().pos(),
                                 true );
     query_any( _( "Gates opened.  Press any key" ) );
 }
References _, get_map(), get_player_character(), math_opers::pos(), query_any(), ter_t_metal_floor, ter_t_wall_metal, and map::translate_radius().
action_portal()
void computer_session::action_portal () private
Definition at line 587 of file computer_session.cpp.
 {
     get_event_bus().send<event_type::opens_portal>();
     map &here = get_map();
     for( const tripoint &tmp : here.points_on_zlevel() ) {
         int numtowers = 0;
         for( const tripoint &tmp2 : here.points_in_radius( tmp, 2 ) ) {
             if( here.ter( tmp2 ) == ter_t_radio_tower ) {
                 numtowers++;
             }
         }
         if( numtowers >= 4 ) {
             if( here.tr_at( tmp ).id == tr_portal ) {
                 here.remove_trap( tmp );
             } else {
                 here.trap_set( tmp, tr_portal );
             }
         }
     }
 }
References get_event_bus(), get_map(), opens_portal, event_bus::send(), ter_t_radio_tower, and tr_portal.
action_radio_archive()
void computer_session::action_radio_archive () private
Definition at line 651 of file computer_session.cpp.
 {
     get_player_character().mod_moves( -to_moves<int>( 3_seconds ) );
     sfx::fade_audio_channel( sfx::channel::radio, 100 );
     sfx::play_ambient_variant_sound( "radio", "inaudible_chatter", 100, sfx::channel::radio,
                                      2000 );
     print_text( "Accessing archive.  Playing audio recording nr %d.\n%s", rng( 1, 9999 ),
                 SNIPPET.random_from_category( "radio_archive" ).value_or( translation() ) );
     if( one_in( 3 ) ) {
         query_any( _( "Warning: restricted data access.  Attempt logged.  Press any key" ) );
         comp.alerts ++;
     } else {
         query_any( _( "Press any key" ) );
     }
     sfx::fade_audio_channel( sfx::channel::radio, 100 );
 }
References _, computer::alerts, comp, sfx::fade_audio_channel(), get_player_character(), Creature::mod_moves(), one_in(), sfx::play_ambient_variant_sound(), print_text(), query_any(), sfx::radio, snippet_library::random_from_category(), rng(), and SNIPPET.
action_release()
void computer_session::action_release () private
Definition at line 536 of file computer_session.cpp.
 {
     get_event_bus().send<event_type::releases_subspace_specimens>();
     Character &player_character = get_player_character();
     sounds::sound( player_character.pos(), 40, sounds::sound_t::alarm, _( "an alarm sound!" ), false,
                    "environment",
                    "alarm" );
     get_map().translate_radius( ter_t_reinforced_glass, ter_t_thconc_floor, 25.0,
                                 player_character.pos(),
                                 true );
     query_any( _( "Containment shields opened.  Press any key" ) );
 }
References _, sounds::alarm, get_event_bus(), get_map(), get_player_character(), query_any(), releases_subspace_specimens, event_bus::send(), sounds::sound(), ter_t_reinforced_glass, ter_t_thconc_floor, and map::translate_radius().
action_release_bionics()
void computer_session::action_release_bionics () private
Definition at line 555 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     sounds::sound( player_character.pos(), 40, sounds::sound_t::alarm, _( "an alarm sound!" ), false,
                    "environment",
                    "alarm" );
     get_map().translate_radius( ter_t_reinforced_glass, ter_t_thconc_floor, 3.0, player_character.pos(),
                                 true );
     query_any( _( "Containment shields opened.  Press any key" ) );
 }
References _, sounds::alarm, get_map(), get_player_character(), Creature::pos(), query_any(), sounds::sound(), ter_t_reinforced_glass, ter_t_thconc_floor, and map::translate_radius().
Referenced by action_release_disarm().
action_release_disarm()
void computer_session::action_release_disarm () private
Definition at line 549 of file computer_session.cpp.
 {
     remove_submap_turrets();
     action_release_bionics();
 }
References action_release_bionics(), and remove_submap_turrets().
action_repeater_mod()
void computer_session::action_repeater_mod () private
Definition at line 977 of file computer_session.cpp.
 {
     avatar &pc = get_avatar();
     static const mission_type_id commo_3 = mission_MISSION_OLD_GUARD_NEC_COMMO_3;
     static const mission_type_id commo_4 = mission_MISSION_OLD_GUARD_NEC_COMMO_4;
     static const mission_type_id repeat = mission_MISSION_OLD_GUARD_REPEATER;
     static const mission_type_id repeatb = mission_MISSION_OLD_GUARD_REPEATER_BEGIN;
     if( pc.has_amount( itype_radio_repeater_mod, 1 ) ) {
         if( !( pc.has_mission_id( commo_3 ) || pc.has_mission_id( commo_4 ) ||
                pc.has_mission_id( repeat ) || pc.has_mission_id( repeatb ) ) ) {
             print_error( _( "You wouldn't gain anything from installing this repeater.  "
                             "However, someone else in the wasteland might reward you "
                             "for doing so." ) );
             query_any();
         }
         for( mission *miss : pc.get_active_missions() ) {
             if( miss->mission_id() == commo_3 || miss->mission_id() == commo_4 ) {
                 miss->step_complete( 1 );
                 print_line( _( "Repeater mod installed" ) );
                 print_line( _( "Mission Complete!" ) );
                 pc.use_amount( itype_radio_repeater_mod, 1 );
                 query_any();
                 comp.options.clear();
                 activate_failure( COMPFAIL_SHUTDOWN );
                 break;
             } else if( miss->mission_id() == repeat || miss->mission_id() == repeatb ) {
                 miss->step_complete( 1 );
                 print_line( _( "Repeater mod installed" ) );
                 print_line( _( "Mission Complete!" ) );
                 pc.use_amount( itype_radio_repeater_mod, 1 );
                 query_any();
                 comp.options.clear();
                 activate_failure( COMPFAIL_SHUTDOWN );
                 break;
             }
         }
     } else {
         print_error( _( "You do not have a repeater mod to install" ) );
         query_any();
     }
 }
References _, activate_failure(), comp, COMPFAIL_SHUTDOWN, avatar::get_active_missions(), get_avatar(), visitable::has_amount(), avatar::has_mission_id(), itype_radio_repeater_mod, mission_MISSION_OLD_GUARD_NEC_COMMO_3, mission_MISSION_OLD_GUARD_NEC_COMMO_4, mission_MISSION_OLD_GUARD_REPEATER, mission_MISSION_OLD_GUARD_REPEATER_BEGIN, computer::options, print_error(), print_line(), query_any(), and Character::use_amount().
action_research()
void computer_session::action_research () private
Definition at line 625 of file computer_session.cpp.
 {
     map &here = get_map();
     // TODO: seed should probably be a member of the computer, or better: of the computer action.
     // It is here to ensure one computer reporting the same text on each invocation.
     const int seed = std::hash<tripoint_abs_sm> {}( here.get_abs_sub() ) + comp.alerts;
     std::optional<translation> log = SNIPPET.random_from_category( "lab_notes", seed );
     if( !log.has_value() ) {
         log = to_translation( "No data found." );
     } else {
         get_player_character().mod_moves( -to_moves<int>( 1_seconds ) * 0.7 );
     }
     print_text( "%s", log.value() );
     // One's an anomaly
     if( comp.alerts == 0 ) {
         query_any( _( "Local data-access error logged, alerting helpdesk.  Press any key" ) );
         comp.alerts ++;
     } else {
         // Two's a trend.
         query_any(
             _( "Warning: anomalous archive-access activity detected at this node.  Press any key" ) );
         comp.alerts ++;
     }
 }
References _, computer::alerts, comp, map::get_abs_sub(), get_map(), get_player_character(), log(), Creature::mod_moves(), print_text(), query_any(), snippet_library::random_from_category(), iuse::seed(), SNIPPET, and to_translation().
action_sample()
void computer_session::action_sample () private
Definition at line 503 of file computer_session.cpp.
 {
     get_player_character().mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     map &here = get_map();
     for( const tripoint &p : here.points_on_zlevel() ) {
         if( here.ter( p ) != ter_t_sewage_pump ) {
             continue;
         }
         for( const tripoint &n : here.points_in_radius( p, 1 ) ) {
             if( here.furn( n ) != furn_f_counter ) {
                 continue;
             }
             bool found_item = false;
             item sewage( itype_sewage, calendar::turn );
             for( item &elem : here.i_at( n ) ) {
                 int capa = elem.get_remaining_capacity_for_liquid( sewage );
                 if( capa <= 0 ) {
                     continue;
                 }
                 sewage.charges = std::min( sewage.charges, capa );
                 if( elem.can_contain( sewage ).success() ) {
                     elem.put_in( sewage, pocket_type::CONTAINER );
                 }
                 found_item = true;
                 break;
             }
             if( !found_item ) {
                 here.add_item_or_charges( n, sewage );
             }
         }
     }
 }
References map::add_item_or_charges(), CONTAINER, map::furn(), furn_f_counter, get_map(), get_player_character(), map::i_at(), itype_sewage, min(), Creature::mod_moves(), map::points_in_radius(), map::points_on_zlevel(), iuse::sewage(), map::ter(), ter_t_sewage_pump, and calendar::turn.
action_shutters()
void computer_session::action_shutters () private
Definition at line 1492 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 3_seconds ) );
     get_map().translate_radius( ter_t_reinforced_glass_shutter_open, ter_t_reinforced_glass_shutter,
                                 8.0,
                                 player_character.pos(),
                                 true, true );
     query_any( _( "Toggling shutters.  Press any key" ) );
 }
References _, get_map(), get_player_character(), Creature::mod_moves(), Creature::pos(), query_any(), ter_t_reinforced_glass_shutter, ter_t_reinforced_glass_shutter_open, and map::translate_radius().
action_sr1_mess()
void computer_session::action_sr1_mess () private
Definition at line 1160 of file computer_session.cpp.
 {
     reset_terminal();
     print_text( "%s", SNIPPET.random_from_category( "sr1_mess" ).value_or( translation() ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_text(), query_any(), snippet_library::random_from_category(), reset_terminal(), and SNIPPET.
action_sr2_mess()
void computer_session::action_sr2_mess () private
Definition at line 1167 of file computer_session.cpp.
 {
     reset_terminal();
     print_text( "%s", SNIPPET.random_from_category( "sr2_mess" ).value_or( translation() ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_text(), query_any(), snippet_library::random_from_category(), reset_terminal(), and SNIPPET.
action_sr3_mess()
void computer_session::action_sr3_mess () private
Definition at line 1174 of file computer_session.cpp.
 {
     reset_terminal();
     print_text( "%s", SNIPPET.random_from_category( "sr3_mess" ).value_or( translation() ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_text(), query_any(), snippet_library::random_from_category(), reset_terminal(), and SNIPPET.
action_sr4_mess()
void computer_session::action_sr4_mess () private
Definition at line 1181 of file computer_session.cpp.
 {
     reset_terminal();
     print_text( "%s", SNIPPET.random_from_category( "sr4_mess" ).value_or( translation() ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_text(), query_any(), snippet_library::random_from_category(), reset_terminal(), and SNIPPET.
action_srcf_1_mess()
void computer_session::action_srcf_1_mess () private
Definition at line 1188 of file computer_session.cpp.
 {
     reset_terminal();
     print_text( "%s", SNIPPET.random_from_category( "scrf_1_mess" ).value_or( translation() ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_text(), query_any(), snippet_library::random_from_category(), reset_terminal(), and SNIPPET.
action_srcf_2_mess()
void computer_session::action_srcf_2_mess () private
Definition at line 1195 of file computer_session.cpp.
 {
     reset_terminal();
     print_text( "%s", SNIPPET.random_from_category( "scrf_2_1_mess" ).value_or( translation() ) );
     query_any( _( "Press any key to continue" ) );
     reset_terminal();
     print_text( "%s", SNIPPET.random_from_category( "scrf_2_2_mess" ).value_or( translation() ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_text(), query_any(), snippet_library::random_from_category(), reset_terminal(), and SNIPPET.
action_srcf_3_mess()
void computer_session::action_srcf_3_mess () private
Definition at line 1205 of file computer_session.cpp.
 {
     reset_terminal();
     print_text( "%s", SNIPPET.random_from_category( "scrf_3_mess" ).value_or( translation() ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_text(), query_any(), snippet_library::random_from_category(), reset_terminal(), and SNIPPET.
action_srcf_elevator()
void computer_session::action_srcf_elevator () private
Definition at line 1248 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     map &here = get_map();
     tripoint surface_elevator;
     tripoint underground_elevator;
     bool is_surface_elevator_on = false;
     bool is_surface_elevator_exist = false;
     bool is_underground_elevator_on = false;
     bool is_underground_elevator_exist = false;
     for( const tripoint &p : here.points_on_zlevel( 0 ) ) {
         if( here.ter( p ) == ter_t_elevator_control_off || here.ter( p ) == ter_t_elevator_control ) {
             surface_elevator = p;
             is_surface_elevator_on = here.ter( p ) == ter_t_elevator_control;
             is_surface_elevator_exist = true;
         }
     }
     for( const tripoint &p : here.points_on_zlevel( -2 ) ) {
         if( here.ter( p ) == ter_t_elevator_control_off || here.ter( p ) == ter_t_elevator_control ) {
             underground_elevator = p;
             is_underground_elevator_on = here.ter( p ) == ter_t_elevator_control;
             is_underground_elevator_exist = true;
         }
     }
     //If some are destroyed
     if( !is_surface_elevator_exist || !is_underground_elevator_exist ) {
         reset_terminal();
         print_error(
             _( "\nElevator control network unreachable!\n\n" ) );
     }
     //If both are disabled try to enable
     else if( !is_surface_elevator_on && !is_underground_elevator_on ) {
         if( !player_character.has_amount( itype_sarcophagus_access_code, 1 ) ) {
             print_error( _( "Access code required!\n\n" ) );
         } else {
             player_character.use_amount( itype_sarcophagus_access_code, 1 );
             here.ter_set( surface_elevator, ter_t_elevator_control );
             is_surface_elevator_on = true;
             here.ter_set( underground_elevator, ter_t_elevator_control );
             is_underground_elevator_on = true;
         }
     }
     //If only one is enabled, enable the other one. Fix for before this change
     else if( is_surface_elevator_on && !is_underground_elevator_on && is_underground_elevator_exist ) {
         here.ter_set( underground_elevator, ter_t_elevator_control );
         is_underground_elevator_on = true;
     }
     else if( is_underground_elevator_on && !is_surface_elevator_on && is_surface_elevator_exist ) {
         here.ter_set( surface_elevator, ter_t_elevator_control );
         is_surface_elevator_on = true;
     }
     //If the elevator is working
     if( is_surface_elevator_on && is_underground_elevator_on ) {
         reset_terminal();
         print_line(
             _( "\nPower:         Backup Only\nRadiation Level:  Very Dangerous\nOperational:   Overridden\n\n" ) );
     }
     query_any( _( "Press any key" ) );
 }
References _, get_map(), get_player_character(), visitable::has_amount(), itype_sarcophagus_access_code, map::points_on_zlevel(), print_error(), print_line(), query_any(), reset_terminal(), map::ter(), map::ter_set(), ter_t_elevator_control, ter_t_elevator_control_off, and Character::use_amount().
action_srcf_seal()
void computer_session::action_srcf_seal () private
Definition at line 1219 of file computer_session.cpp.
 {
     get_event_bus().send<event_type::seals_hazardous_material_sarcophagus>();
     print_line( _( "Charges Detonated" ) );
     print_line( _( "Backup Generator Power Failing" ) );
     print_line( _( "Evacuate Immediately" ) );
     add_msg( m_warning, _( "Evacuate Immediately!" ) );
     map &here = get_map();
     for( const tripoint &p : here.points_on_zlevel() ) {
         if( here.ter( p ) == ter_t_elevator || here.ter( p ) == ter_t_vat ) {
             here.make_rubble( p, furn_f_rubble_rock, true );
             explosion_handler::explosion( &get_player_character(), p, 40, 0.7, true );
         }
         if( here.ter( p ) == ter_t_wall_glass ) {
             here.make_rubble( p, furn_f_rubble_rock, true );
         }
         if( here.ter( p ) == ter_t_sewage_pipe || here.ter( p ) == ter_t_sewage ||
             here.ter( p ) == ter_t_grate ) {
             here.make_rubble( p, furn_f_rubble_rock, true );
         }
         if( here.ter( p ) == ter_t_sewage_pump ) {
             here.make_rubble( p, furn_f_rubble_rock, true );
             explosion_handler::explosion( &get_player_character(), p, 50, 0.7, true );
         }
     }
     comp.options.clear(); // Disable the terminal.
     activate_failure( COMPFAIL_SHUTDOWN );
 }
References _, activate_failure(), add_msg(), comp, COMPFAIL_SHUTDOWN, explosion_handler::explosion(), furn_f_rubble_rock, get_event_bus(), get_map(), get_player_character(), m_warning, map::make_rubble(), computer::options, map::points_on_zlevel(), print_line(), seals_hazardous_material_sarcophagus, event_bus::send(), map::ter(), ter_t_elevator, ter_t_grate, ter_t_sewage, ter_t_sewage_pipe, ter_t_sewage_pump, ter_t_vat, and ter_t_wall_glass.
action_srcf_seal_order()
void computer_session::action_srcf_seal_order () private
Definition at line 1212 of file computer_session.cpp.
 {
     reset_terminal();
     print_text( "%s", SNIPPET.random_from_category( "scrf_seal_order" ).value_or( translation() ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_text(), query_any(), snippet_library::random_from_category(), reset_terminal(), and SNIPPET.
action_terminate()
void computer_session::action_terminate () private
Definition at line 566 of file computer_session.cpp.
 {
     get_event_bus().send<event_type::terminates_subspace_specimens>();
     Character &player_character = get_player_character();
     map &here = get_map();
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &p : here.points_on_zlevel() ) {
         monster *const mon = creatures.creature_at<monster>( p );
         if( !mon ) {
             continue;
         }
         if( ( here.ter( p + tripoint_north ) == ter_t_reinforced_glass &&
               here.ter( p + tripoint_south ) == ter_t_concrete_wall ) ||
             ( here.ter( p + tripoint_south ) == ter_t_reinforced_glass &&
               here.ter( p + tripoint_north ) == ter_t_concrete_wall ) ) {
             mon->die( &player_character );
         }
     }
     query_any( _( "Subjects terminated.  Press any key" ) );
 }
References _, creature_tracker::creature_at(), monster::die(), get_creature_tracker(), get_event_bus(), get_map(), get_player_character(), map::points_on_zlevel(), query_any(), event_bus::send(), map::ter(), ter_t_concrete_wall, ter_t_reinforced_glass, terminates_subspace_specimens, tripoint_north, and tripoint_south.
action_toll()
void computer_session::action_toll () private
Definition at line 487 of file computer_session.cpp.
 {
     if( calendar::turn < comp.next_attempt ) {
         print_error( _( "[Bellsystem 1.2] is currently in use." ) );
         query_any( _( "Please wait for at least one minute." ) );
         reset_terminal();
     } else {
         comp.next_attempt = calendar::turn + 1_minutes;
         sounds::sound( get_player_character().pos(), 120, sounds::sound_t::music,
                        //~ the sound of a church bell ringing
                        _( "Bohm  Bohm  Bohm" ), true, "environment", "church_bells" );
         query_any( _( "[Bellsystem 1.2] activated.  Have a nice day." ) );
     }
 }
References _, comp, get_player_character(), sounds::music, computer::next_attempt, math_opers::pos(), print_error(), query_any(), reset_terminal(), sounds::sound(), and calendar::turn.
action_tower_unresponsive()
void computer_session::action_tower_unresponsive () private
Definition at line 1148 of file computer_session.cpp.
 {
     print_line( _( "  WARNING, RADIO TOWER IS UNRESPONSIVE.\n"
                    "  \n"
                    "  BACKUP POWER INSUFFICIENT TO MEET BROADCASTING REQUIREMENTS.\n"
                    "  IN THE EVENT OF AN EMERGENCY, CONTACT LOCAL NATIONAL GUARD\n"
                    "  UNITS TO RECEIVE PRIORITY WHEN GENERATORS ARE BEING DEPLOYED.\n"
                    "  \n"
                    "  \n" ) );
     query_any( _( "Press any key to continue" ) );
 }
References _, print_line(), and query_any().
action_unlock()
void computer_session::action_unlock () private
Definition at line 478 of file computer_session.cpp.
 {
     get_map().translate_radius( ter_t_door_metal_locked, ter_t_door_metal_c, 8.0,
                                 get_player_character().pos(),
                                 true );
     query_any( _( "Lock disabled.  Press any key" ) );
 }
References _, get_map(), get_player_character(), math_opers::pos(), query_any(), ter_t_door_metal_c, ter_t_door_metal_locked, and map::translate_radius().
Referenced by action_unlock_disarm().
action_unlock_disarm()
void computer_session::action_unlock_disarm () private
Definition at line 472 of file computer_session.cpp.
 {
     remove_submap_turrets();
     action_unlock();
 }
References action_unlock(), and remove_submap_turrets().
activate_failure()
void computer_session::activate_failure (computer_failure_type fail) private
Definition at line 1580 of file computer_session.cpp.
 {
     const auto it = computer_failure_functions.find( fail );
     if( it != computer_failure_functions.end() ) {
         ( this->*( it->second ) )();
     }
 }
References computer_failure_functions.
Referenced by action_irradiator(), action_miss_disarm(), action_miss_launch(), action_repeater_mod(), action_srcf_seal(), and activate_random_failure().
activate_function()
void computer_session::activate_function (computer_action action) private
Definition at line 421 of file computer_session.cpp.
 {
     const auto it = computer_action_functions.find( action );
     if( it != computer_action_functions.end() ) {
         // Token move cost for any action, if an action takes longer decrement moves further.
         get_player_character().mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
         ( this->*( it->second ) )();
     }
 }
References action, computer_action_functions, get_player_character(), and Creature::mod_moves().
Referenced by use().
activate_random_failure()
void computer_session::activate_random_failure () private
Definition at line 1558 of file computer_session.cpp.
 {
     comp.next_attempt = calendar::turn + 45_minutes;
     static const computer_failure default_failure( COMPFAIL_SHUTDOWN );
     const computer_failure &fail = random_entry( comp.failures, default_failure );
     activate_failure( fail.type );
 }
References activate_failure(), comp, COMPFAIL_SHUTDOWN, computer::failures, computer::next_attempt, random_entry(), calendar::turn, and computer_failure::type.
Referenced by use().
can_activate()
bool computer_session::can_activate (computer_action action) private
Checks whether the specified action can be activated (has any effect)
Returns
True for actions that either have an effect or require no special conditions, otherwise false (e.g. false for COMPACT_UNLOCK if no locked doors are in range).
Definition at line 381 of file computer_session.cpp.
 {
     switch( action ) {
         case COMPACT_LOCK:
             return get_map().has_nearby_ter( get_player_character().pos(), ter_t_door_metal_c, 8 );
         case COMPACT_RELEASE:
         case COMPACT_RELEASE_DISARM:
             return get_map().has_nearby_ter( get_player_character().pos(), ter_t_reinforced_glass, 25 );
         case COMPACT_RELEASE_BIONICS:
             return get_map().has_nearby_ter( get_player_character().pos(), ter_t_reinforced_glass, 3 );
         case COMPACT_TERMINATE: {
             map &here = get_map();
             creature_tracker &creatures = get_creature_tracker();
             for( const tripoint &p : here.points_on_zlevel() ) {
                 monster *const mon = creatures.creature_at<monster>( p );
                 if( !mon ) {
                     continue;
                 }
                 if( ( here.ter( p + tripoint_north ) == ter_t_reinforced_glass &&
                       here.ter( p + tripoint_south ) == ter_t_concrete_wall ) ||
                     ( here.ter( p + tripoint_south ) == ter_t_reinforced_glass &&
                       here.ter( p + tripoint_north ) == ter_t_concrete_wall ) ) {
                     return true;
                 }
             }
             return false;
         }
         case COMPACT_UNLOCK:
         case COMPACT_UNLOCK_DISARM:
             return get_map().has_nearby_ter( get_player_character().pos(), ter_t_door_metal_locked, 8 );
         default:
             return true;
     }
 }
References action, COMPACT_LOCK, COMPACT_RELEASE, COMPACT_RELEASE_BIONICS, COMPACT_RELEASE_DISARM, COMPACT_TERMINATE, COMPACT_UNLOCK, COMPACT_UNLOCK_DISARM, creature_tracker::creature_at(), get_creature_tracker(), get_map(), get_player_character(), map::has_nearby_ter(), map::points_on_zlevel(), math_opers::pos(), map::ter(), ter_t_concrete_wall, ter_t_door_metal_c, ter_t_door_metal_locked, ter_t_reinforced_glass, tripoint_north, and tripoint_south.
Referenced by use().
failure_alarm()
void computer_session::failure_alarm () private
Definition at line 1610 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     get_event_bus().send<event_type::triggers_alarm>( player_character.getID() );
     sounds::sound( player_character.pos(), 60, sounds::sound_t::alarm, _( "an alarm sound!" ), false,
                    "environment",
                    "alarm" );
 }
References _, sounds::alarm, get_event_bus(), get_player_character(), Character::getID(), Creature::pos(), event_bus::send(), sounds::sound(), and triggers_alarm.
failure_amigara()
void computer_session::failure_amigara () private
Definition at line 1698 of file computer_session.cpp.
 {
     get_timed_events().add( timed_event_type::AMIGARA, calendar::turn + 30_seconds );
     get_player_character().add_effect( effect_amigara, 2_minutes );
     map &here = get_map();
     explosion_handler::explosion( &get_player_character(),
                                   tripoint( rng( 0, MAPSIZE_X ), rng( 0, MAPSIZE_Y ), here.get_abs_sub().z() ), 10, 0.7, false, 10 );
     explosion_handler::explosion( &get_player_character(),
                                   tripoint( rng( 0, MAPSIZE_X ), rng( 0, MAPSIZE_Y ), here.get_abs_sub().z() ), 10, 0.7, false, 10 );
     comp.remove_option( COMPACT_AMIGARA_START );
 }
References timed_event_manager::add(), Creature::add_effect(), AMIGARA, comp, COMPACT_AMIGARA_START, effect_amigara, explosion_handler::explosion(), map::get_abs_sub(), get_map(), get_player_character(), get_timed_events(), MAPSIZE_X, MAPSIZE_Y, computer::remove_option(), rng(), tripoint, calendar::turn, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
failure_damage()
void computer_session::failure_damage () private
Definition at line 1643 of file computer_session.cpp.
 {
     add_msg( m_neutral, _( "The console shocks you." ) );
     Character &player_character = get_player_character();
     if( player_character.is_elec_immune() ) {
         add_msg( m_good, _( "You're protected from electric shocks." ) );
     } else {
         add_msg( m_bad, _( "Your body is damaged by the electric shock!" ) );
         player_character.hurtall( rng( 1, 10 ), nullptr );
     }
 }
References _, add_msg(), get_player_character(), Character::hurtall(), Character::is_elec_immune(), m_bad, m_good, m_neutral, and rng().
failure_destroy_blood()
void computer_session::failure_destroy_blood () private
Definition at line 1710 of file computer_session.cpp.
 {
     print_error( _( "ERROR: Disruptive Spin" ) );
     map &here = get_map();
     for( const tripoint &dest : here.points_in_radius( get_player_character().pos(), 2 ) ) {
         if( here.furn( dest ) == furn_f_centrifuge ) {
             map_stack items = here.i_at( dest );
             if( items.empty() ) {
                 print_error( _( "ERROR: Please place sample in centrifuge." ) );
             } else if( items.size() > 1 ) {
                 print_error( _( "ERROR: Please remove all but one sample from centrifuge." ) );
             } else if( items.only_item().typeId() != itype_vacutainer ) {
                 print_error( _( "ERROR: Please use blood-contained samples." ) );
             } else if( items.only_item().empty() ) {
                 print_error( _( "ERROR: Blood draw kit, empty." ) );
             } else if( items.only_item().legacy_front().typeId() != itype_blood &&
                        items.only_item().legacy_front().typeId() != itype_blood_tainted ) {
                 print_error( _( "ERROR: Please only use blood samples." ) );
             } else {
                 print_error( _( "ERROR: Blood sample destroyed." ) );
                 here.i_clear( dest );
             }
         }
     }
     query_any();
 }
References _, item::empty(), item_stack::empty(), map::furn(), furn_f_centrifuge, get_map(), get_player_character(), map::i_at(), map::i_clear(), itype_blood, itype_blood_tainted, itype_vacutainer, item::legacy_front(), item_stack::only_item(), map::points_in_radius(), math_opers::pos(), print_error(), query_any(), item_stack::size(), and item::typeId().
failure_destroy_data()
void computer_session::failure_destroy_data () private
Definition at line 1737 of file computer_session.cpp.
 {
     print_error( _( "ERROR: ACCESSING DATA MALFUNCTION" ) );
     map &here = get_map();
     for( const tripoint &p : here.points_in_radius( get_player_character().pos(), 2 ) ) {
         if( here.ter( p ) == ter_t_floor_blue ) {
             map_stack items = here.i_at( p );
             if( items.empty() ) {
                 print_error( _( "ERROR: Please place memory bank in scan area." ) );
             } else if( items.size() > 1 ) {
                 print_error( _( "ERROR: Please only scan one item at a time." ) );
             } else if( items.only_item().typeId() != itype_usb_drive ) {
                 print_error( _( "ERROR: Memory bank destroyed or not present." ) );
             } else if( items.only_item().empty() ) {
                 print_error( _( "ERROR: Memory bank is empty." ) );
             } else {
                 print_error( _( "ERROR: Data bank destroyed." ) );
                 here.i_clear( p );
             }
         }
     }
     query_any();
 }
References _, item::empty(), item_stack::empty(), get_map(), get_player_character(), map::i_at(), map::i_clear(), itype_usb_drive, item_stack::only_item(), map::points_in_radius(), math_opers::pos(), print_error(), query_any(), item_stack::size(), map::ter(), ter_t_floor_blue, and item::typeId().
failure_manhacks()
void computer_session::failure_manhacks () private
Definition at line 1619 of file computer_session.cpp.
 {
     int num_robots = rng( 4, 8 );
     const tripoint_range<tripoint> range =
         get_map().points_in_radius( get_player_character().pos(), 3 );
     for( int i = 0; i < num_robots; i++ ) {
         if( g->place_critter_within( mon_manhack, range ) ) {
             add_msg( m_warning, _( "Manhacks drop from compartments in the ceiling." ) );
         }
     }
 }
References _, add_msg(), g, get_map(), get_player_character(), m_warning, mon_manhack, map::points_in_radius(), math_opers::pos(), and rng().
failure_pump_explode()
void computer_session::failure_pump_explode () private
Definition at line 1655 of file computer_session.cpp.
 {
     add_msg( m_warning, _( "The pump explodes!" ) );
     map &here = get_map();
     for( const tripoint &p : here.points_on_zlevel() ) {
         if( here.ter( p ) == ter_t_sewage_pump ) {
             here.make_rubble( p );
             explosion_handler::explosion( &get_player_character(), p, 10 );
         }
     }
 }
References _, add_msg(), explosion_handler::explosion(), get_map(), get_player_character(), m_warning, map::make_rubble(), map::points_on_zlevel(), map::ter(), and ter_t_sewage_pump.
failure_pump_leak()
void computer_session::failure_pump_leak () private
Definition at line 1667 of file computer_session.cpp.
 {
     add_msg( m_warning, _( "Sewage leaks!" ) );
     map &here = get_map();
     for( const tripoint &p : here.points_on_zlevel() ) {
         if( here.ter( p ) != ter_t_sewage_pump ) {
             continue;
         }
         const int leak_size = rng( 4, 10 );
         for( int i = 0; i < leak_size; i++ ) {
             std::vector<tripoint> next_move;
             if( here.passable( p + point_north ) ) {
                 next_move.push_back( p + point_north );
             }
             if( here.passable( p + point_east ) ) {
                 next_move.push_back( p + point_east );
             }
             if( here.passable( p + point_south ) ) {
                 next_move.push_back( p + point_south );
             }
             if( here.passable( p + point_west ) ) {
                 next_move.push_back( p + point_west );
             }
             if( next_move.empty() ) {
                 break;
             }
             here.ter_set( random_entry( next_move ), ter_t_sewage );
         }
     }
 }
References _, add_msg(), get_map(), m_warning, map::passable(), point_east, point_north, point_south, point_west, map::points_on_zlevel(), random_entry(), rng(), map::ter(), map::ter_set(), ter_t_sewage, and ter_t_sewage_pump.
failure_secubots()
void computer_session::failure_secubots () private
Definition at line 1631 of file computer_session.cpp.
 {
     int num_robots = 1;
     const tripoint_range<tripoint> range =
         get_map().points_in_radius( get_player_character().pos(), 3 );
     for( int i = 0; i < num_robots; i++ ) {
         if( g->place_critter_within( mon_secubot, range ) ) {
             add_msg( m_warning, _( "Secubots emerge from compartments in the floor." ) );
         }
     }
 }
References _, add_msg(), g, get_map(), get_player_character(), m_warning, mon_secubot, map::points_in_radius(), and math_opers::pos().
failure_shutdown()
void computer_session::failure_shutdown () private
Definition at line 1588 of file computer_session.cpp.
 {
     bool found_tile = false;
     map &here = get_map();
     for( const tripoint &p : here.points_in_radius( get_player_character().pos(), 1 ) ) {
         if( here.has_flag( ter_furn_flag::TFLAG_CONSOLE, p ) ) {
             here.furn_set( p, furn_f_console_broken );
             add_msg( m_bad, _( "The console shuts down." ) );
             found_tile = true;
         }
     }
     if( found_tile ) {
         return;
     }
     for( const tripoint &p : here.points_on_zlevel() ) {
         if( here.has_flag( ter_furn_flag::TFLAG_CONSOLE, p ) ) {
             here.furn_set( p, furn_f_console_broken );
             add_msg( m_bad, _( "The console shuts down." ) );
         }
     }
 }
References _, add_msg(), furn_f_console_broken, map::furn_set(), get_map(), get_player_character(), map::has_flag(), m_bad, map::points_in_radius(), map::points_on_zlevel(), math_opers::pos(), and TFLAG_CONSOLE.
hack_attempt()
bool computer_session::hack_attempt (Character & you, int Security = -1) const private
Returns true if the player successfully hacks the computer.
Security = -1 defaults to the main system security.
Intelligence <8 randomly penalizes hack attempts, 50% of the time Intelligence >8 randomly benefits hack attempts, 33% of the time Computer increases chance of successful hack attempt, vs Security level
Definition at line 264 of file computer_session.cpp.
 {
     if( Security == -1 ) {
         Security = comp.security;    // Set to main system security if no value passed
     }
     const int hack_skill = round( you.get_skill_level( skill_computer ) );
     // Every time you dig for lab notes, (or, in future, do other suspicious stuff?)
     // +2 dice to the system's hack-resistance
     // So practical max files from a given terminal = 5, at 10 Computer
     if( comp.alerts > 0 ) {
         Security += ( comp.alerts * 2 );
     }
     you.mod_moves( -( 10 * ( 5 + Security * 2 ) / std::max( 1, hack_skill + 1 ) ) );
     int player_roll = round( you.get_greater_skill_or_knowledge_level(
                                  skill_computer ) ); //this relates to the success of the roll for hacking - the practical skill covers the time.
     ///\EFFECT_INT <8 randomly penalizes hack attempts, 50% of the time
     if( you.int_cur < 8 && one_in( 2 ) ) {
         player_roll -= rng( 0, 8 - you.int_cur );
         ///\EFFECT_INT >8 randomly benefits hack attempts, 33% of the time
     } else if( you.int_cur > 8 && one_in( 3 ) ) {
         player_roll += rng( 0, you.int_cur - 8 );
     }
     ///\EFFECT_COMPUTER increases chance of successful hack attempt, vs Security level
     bool successful_attempt = dice( player_roll, 6 ) >= dice( Security, 6 );
     you.practice( skill_computer, successful_attempt ? ( 15 + Security * 3 ) : 7 );
     return successful_attempt;
 }
References computer::alerts, comp, dice(), Character::get_greater_skill_or_knowledge_level(), Character::get_skill_level(), Character::int_cur, max(), Creature::mod_moves(), one_in(), Character::practice(), rng(), round(), computer::security, and skill_computer.
Referenced by use().
print_error()
template<typename ... Args> void computer_session::print_error (const std::string & text, Args &&... args) private
Definition at line 1906 of file computer_session.cpp.
 {
     const std::string formatted_text = string_format( text, std::forward<Args>( args )... );
     print_indented_line( 0, width, "%s", colorize( formatted_text, c_red ) );
 }
References c_red, colorize(), print_indented_line(), string_format(), and width.
Referenced by action_amigara_log(), action_blood_anal(), action_complete_disable_external_power(), action_conveyor(), action_data_anal(), action_deactivate_shock_vent(), action_download_software(), action_geiger(), action_irradiator(), action_repeater_mod(), action_srcf_elevator(), action_toll(), failure_destroy_blood(), failure_destroy_data(), and use().
print_gibberish_line()
void computer_session::print_gibberish_line () private
Definition at line 1919 of file computer_session.cpp.
 {
     std::string gibberish;
     int length = rng( 50, 70 );
     for( int i = 0; i < length; i++ ) {
         switch( rng( 0, 4 ) ) {
             case 0:
                 gibberish += static_cast<char>( '0' + rng( 0, 9 ) );
                 break;
             case 1:
             case 2:
                 gibberish += static_cast<char>( 'a' + rng( 0, 25 ) );
                 break;
             case 3:
             case 4:
                 gibberish += static_cast<char>( 'A' + rng( 0, 25 ) );
                 break;
         }
     }
     print_indented_line( 0, width, "%s", colorize( gibberish, c_yellow ) );
 }
References c_yellow, colorize(), length, print_indented_line(), rng(), and width.
Referenced by action_amigara_log().
print_indented_line()
template<typename ... Args> void computer_session::print_indented_line (int indent, int text_width, const std::string & text, Args &&... args) private
Definition at line 1878 of file computer_session.cpp.
 {
     if( text_width <= 0 || height <= 0 ) {
         return;
     }
     const size_t uheight = static_cast<size_t>( height );
     const std::string formatted_text = string_format( text, std::forward<Args>( args )... );
     std::vector<std::string> folded = foldstring( formatted_text, text_width );
     if( folded.size() >= uheight ) {
         lines.clear();
     } else if( lines.size() + folded.size() > uheight ) {
         lines.erase( lines.begin(), lines.begin() + ( lines.size() + folded.size() - uheight ) );
     }
     lines.reserve( uheight );
     for( auto it = folded.size() >= uheight ? folded.end() - uheight : folded.begin();
          it < folded.end(); ++it ) {
         lines.emplace_back( indent, *it );
     }
 }
References foldstring(), height, lines, and string_format().
Referenced by action_list_mutations(), print_error(), print_gibberish_line(), print_line(), print_text(), query_any(), and query_ynq().
print_line()
template<typename ... Args> void computer_session::print_line (const std::string & text, Args &&... args) private
Definition at line 1900 of file computer_session.cpp.
 {
     print_indented_line( 0, width, text, std::forward<Args>( args )... );
 }
References print_indented_line(), and width.
Referenced by action_amigara_log(), action_blood_anal(), action_conveyor(), action_data_anal(), action_deactivate_shock_vent(), action_disconnect(), action_download_software(), action_emerg_mess(), action_emerg_ref_center(), action_list_bionics(), action_repeater_mod(), action_srcf_elevator(), action_srcf_seal(), action_tower_unresponsive(), and use().
print_newline()
void computer_session::print_newline () private
Definition at line 1946 of file computer_session.cpp.
 {
     if( height <= 0 ) {
         return;
     }
     const size_t uheight = static_cast<size_t>( height );
     if( lines.size() >= uheight ) {
         lines.erase( lines.begin(), lines.end() - ( uheight - 1 ) );
     }
     lines.emplace_back();
 }
References height, and lines.
Referenced by action_amigara_log(), action_geiger(), action_list_bionics(), action_list_mutations(), and print_text().
print_text()
template<typename ... Args> void computer_session::print_text (const std::string & text, Args &&... args) private
Definition at line 1913 of file computer_session.cpp.
 {
     print_indented_line( 1, width - 2, text, std::forward<Args>( args )... );
     print_newline();
 }
References print_indented_line(), print_newline(), and width.
Referenced by action_amigara_log(), action_list_mutations(), action_radio_archive(), action_research(), action_sr1_mess(), action_sr2_mess(), action_sr3_mess(), action_sr4_mess(), action_srcf_1_mess(), action_srcf_2_mess(), action_srcf_3_mess(), and action_srcf_seal_order().
query_any() [1/2]
bool computer_session::query_any () private
Definition at line 1821 of file computer_session.cpp.
 {
     ui_manager::redraw();
     inp_mngr.wait_for_any_key();
     return true;
 }
References inp_mngr, ui_manager::redraw(), and input_manager::wait_for_any_key().
Referenced by action_amigara_log(), action_blood_anal(), action_close_gate(), action_complete_disable_external_power(), action_conveyor(), action_data_anal(), action_deactivate_shock_vent(), action_disconnect(), action_download_software(), action_elevator_on(), action_emerg_mess(), action_emerg_ref_center(), action_extract_rad_source(), action_geiger(), action_irradiator(), action_list_bionics(), action_lock(), action_map_sewer(), action_map_subway(), action_maps(), action_open(), action_open_gate(), action_radio_archive(), action_release(), action_release_bionics(), action_repeater_mod(), action_research(), action_shutters(), action_sr1_mess(), action_sr2_mess(), action_sr3_mess(), action_sr4_mess(), action_srcf_1_mess(), action_srcf_2_mess(), action_srcf_3_mess(), action_srcf_elevator(), action_srcf_seal_order(), action_terminate(), action_toll(), action_tower_unresponsive(), action_unlock(), failure_destroy_blood(), failure_destroy_data(), query_any(), and use().
query_any() [2/2]
template<typename ... Args> bool computer_session::query_any (const std::string & text, Args &&... args) private
Definition at line 1815 of file computer_session.cpp.
 {
     print_indented_line( 0, width, text, std::forward<Args>( args )... );
     return query_any();
 }
References print_indented_line(), query_any(), and width.
query_bool()
template<typename ... Args> bool computer_session::query_bool (const std::string & text, Args &&... args) private
Definition at line 1809 of file computer_session.cpp.
 {
     return query_ynq( text, std::forward<Args>( args )... ) == ynq::yes;
 }
References query_ynq(), and yes.
Referenced by action_amigara_log(), action_blood_anal(), action_cascade(), and use().
query_ynq()
template<typename ... Args> computer_session::ynq computer_session::query_ynq (const std::string & text, Args &&... args) private
Definition at line 1829 of file computer_session.cpp.
 {
     const std::string formatted_text = string_format( text, std::forward<Args>( args )... );
     const bool force_uc = get_option<bool>( "FORCE_CAPITAL_YN" );
     const auto &allow_key = force_uc ? input_context::disallow_lower_case_or_non_modified_letters
                             : input_context::allow_all_keys;
     input_context ctxt( "YESNOQUIT", keyboard_mode::keycode );
     ctxt.register_action( "YES" );
     ctxt.register_action( "NO" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     print_indented_line( 0, width, force_uc && !is_keycode_mode_supported()
                          //~ 1st: query string, 2nd-4th: keybinding descriptions
                          ? pgettext( "query_ynq", "%s %s, %s, %s (Case sensitive)" )
                          //~ 1st: query string, 2nd-4th: keybinding descriptions
                          : pgettext( "query_ynq", "%s %s, %s, %s" ),
                          formatted_text,
                          ctxt.describe_key_and_name( "YES", allow_key ),
                          ctxt.describe_key_and_name( "NO", allow_key ),
                          ctxt.describe_key_and_name( "QUIT", allow_key ) );
     do {
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         if( allow_key( ctxt.get_raw_input() ) ) {
             if( action == "YES" ) {
                 return ynq::yes;
             } else if( action == "NO" ) {
                 return ynq::no;
             } else if( action == "QUIT" ) {
                 return ynq::quit;
             }
         }
     } while( true );
 }
References action, input_context::allow_all_keys(), input_context::describe_key_and_name(), input_context::disallow_lower_case_or_non_modified_letters(), input_context::get_raw_input(), input_context::handle_input(), is_keycode_mode_supported(), keycode, no, pgettext, print_indented_line(), quit, ui_manager::redraw(), input_context::register_action(), string_format(), width, and yes.
Referenced by query_bool(), and use().
refresh()
void computer_session::refresh () private
Definition at line 1865 of file computer_session.cpp.
 {
     werase( win );
     draw_border( win );
     for( size_t i = 0; i < lines.size(); ++i ) {
         nc_color dummy = c_green;
         print_colored_text( win, point( left + lines[i].first, top + static_cast<int>( i ) ),
                             dummy, dummy, lines[i].second );
     }
     wnoutrefresh( win );
 }
References c_green, draw_border(), left, lines, point, print_colored_text(), second, top, catacurses::werase(), win, and catacurses::wnoutrefresh().
Referenced by use().
reset_terminal()
void computer_session::reset_terminal () private
Definition at line 1941 of file computer_session.cpp.
 {
     lines.clear();
 }
References lines.
Referenced by action_amigara_log(), action_disconnect(), action_emerg_ref_center(), action_irradiator(), action_list_bionics(), action_list_mutations(), action_sr1_mess(), action_sr2_mess(), action_sr3_mess(), action_sr4_mess(), action_srcf_1_mess(), action_srcf_2_mess(), action_srcf_3_mess(), action_srcf_elevator(), action_srcf_seal_order(), action_toll(), and use().
use()
void computer_session::use ()
Handles player use of a computer.
Definition at line 155 of file computer_session.cpp.
 {
     ui_adaptor ui;
     ui.on_screen_resize( [this]( ui_adaptor & ui ) {
         const int width = getmaxx( win );
         const int height = getmaxy( win );
         const point p( std::max( 0, ( TERMX - width ) / 2 ), std::max( 0, ( TERMY - height ) / 2 ) );
         win = catacurses::newwin( height, width, p );
         ui.position_from_window( win );
     } );
     ui.mark_resize();
     ui.on_redraw( [this]( const ui_adaptor & ) {
         refresh();
     } );
     avatar &player_character = get_avatar();
     // Login
     print_line( _( "Logging into %s" ), comp.name );
     if( comp.security > 0 ) {
         if( calendar::turn < comp.next_attempt ) {
             print_error( _( "Access is temporary blocked for security purposes." ) );
             query_any( _( "Please contact the system administrator." ) );
             reset_terminal();
             return;
         }
         print_error( "%s", comp.access_denied );
         switch( query_ynq( _( "Bypass security?" ) ) ) {
             case ynq::quit:
                 reset_terminal();
                 return;
             case ynq::no:
                 query_any( _( "Shutting down press any key." ) );
                 reset_terminal();
                 return;
             case ynq::yes:
                 if( !hack_attempt( player_character ) ) {
                     if( comp.failures.empty() ) {
                         query_any( _( "Maximum login attempts exceeded.  Press any key" ) );
                         reset_terminal();
                         return;
                     }
                     activate_random_failure();
                     reset_terminal();
                     return;
                 } else { // Successful hack attempt
                     comp.security = 0;
                     query_any( _( "Login successful.  Press any key" ) );
                     reset_terminal();
                 }
         }
     } else { // No security
         query_any( _( "Login successful.  Press any key" ) );
         reset_terminal();
     }
     // Main computer loop
     int sel = 0;
     while( true ) {
         size_t options_size = comp.options.size();
         uilist computer_menu;
         computer_menu.text = string_format( _( "%s - Root Menu" ), comp.name );
         computer_menu.selected = sel;
         computer_menu.fselected = sel;
         for( size_t i = 0; i < options_size; i++ ) {
             bool activatable = can_activate( comp.options[i].action );
             std::string action_name = comp.options[i].name;
             if( !activatable ) {
                 action_name = string_format( _( "%s (UNAVAILABLE)" ), action_name );
             }
             computer_menu.addentry( i, activatable, MENU_AUTOASSIGN, action_name );
         }
         ui_manager::redraw();
         computer_menu.query();
         if( computer_menu.ret < 0 || static_cast<size_t>( computer_menu.ret ) >= comp.options.size() ) {
             break;
         }
         sel = computer_menu.ret;
         computer_option current = comp.options[sel];
         reset_terminal();
         // Once you trip the security, you have to roll every time you want to do something
         if( current.security + comp.alerts > 0 ) {
             print_error( _( "Password required." ) );
             if( query_bool( _( "Hack into system?" ) ) ) {
                 if( !hack_attempt( player_character, current.security ) ) {
                     activate_random_failure();
                     reset_terminal();
                     return;
                 } else {
                     // Successfully hacked function
                     comp.options[sel].security = 0;
                     activate_function( current.action );
                 }
             }
         } else { // No need to hack, just activate
             activate_function( current.action );
         }
         reset_terminal();
         // Done processing a selected option.
     }
     reset_terminal(); // This should have been done by now, but just in case.
 }
References _, computer::access_denied, computer_option::action, activate_function(), activate_random_failure(), uilist::addentry(), computer::alerts, can_activate(), comp, computer::failures, uilist::fselected, get_avatar(), catacurses::getmaxx(), catacurses::getmaxy(), hack_attempt(), height, max(), MENU_AUTOASSIGN, computer::name, catacurses::newwin(), computer::next_attempt, no, computer::options, print_error(), print_line(), uilist::query(), query_any(), query_bool(), query_ynq(), quit, ui_manager::redraw(), refresh(), reset_terminal(), uilist::ret, computer_option::security, computer::security, uilist::selected, string_format(), TERMX, TERMY, uilist::text, calendar::turn, width, win, and yes.
Referenced by game::use_computer().
Member Data Documentation
comp
computer& computer_session::comp private
Definition at line 24 of file computer_session.h.
Referenced by action_amigara_start(), action_download_software(), action_extract_rad_source(), action_irradiator(), action_map_sewer(), action_map_subway(), action_maps(), action_miss_disarm(), action_miss_launch(), action_radio_archive(), action_repeater_mod(), action_research(), action_srcf_seal(), action_toll(), activate_random_failure(), failure_amigara(), hack_attempt(), and use().
computer_action_functions
const std::map< computer_action, void(computer_session::*)()> computer_session::computer_action_functions static private
Definition at line 140 of file computer_session.h.
Referenced by activate_function().
computer_failure_functions
const std::map< computer_failure_type, void(computer_session::*)()> computer_session::computer_failure_functions static private
Initial value:
= {
    { COMPFAIL_ALARM, &computer_session::failure_alarm },
    { COMPFAIL_AMIGARA, &computer_session::failure_amigara },
    { COMPFAIL_DAMAGE, &computer_session::failure_damage },
    { COMPFAIL_DESTROY_BLOOD, &computer_session::failure_destroy_blood },
    { COMPFAIL_DESTROY_DATA, &computer_session::failure_destroy_data },
    { COMPFAIL_MANHACKS, &computer_session::failure_manhacks },
    { COMPFAIL_PUMP_EXPLODE, &computer_session::failure_pump_explode },
    { COMPFAIL_PUMP_LEAK, &computer_session::failure_pump_leak },
    { COMPFAIL_SECUBOTS, &computer_session::failure_secubots },
    { COMPFAIL_SHUTDOWN, &computer_session::failure_shutdown },
}
Definition at line 153 of file computer_session.h.
Referenced by activate_failure().
height
const int computer_session::height private
Definition at line 30 of file computer_session.h.
Referenced by print_indented_line(), print_newline(), and use().
left
const int computer_session::left private
Definition at line 27 of file computer_session.h.
Referenced by refresh().
lines
std::vector<std::pair<int, std::string> > computer_session::lines private
Definition at line 31 of file computer_session.h.
Referenced by print_indented_line(), print_newline(), refresh(), and reset_terminal().
top
const int computer_session::top private
Definition at line 28 of file computer_session.h.
Referenced by refresh().
width
const int computer_session::width private
Definition at line 29 of file computer_session.h.
Referenced by action_list_mutations(), print_error(), print_gibberish_line(), print_line(), print_text(), query_any(), query_ynq(), and use().
win
catacurses::window computer_session::win private
Definition at line 26 of file computer_session.h.
Referenced by refresh(), and use().
The documentation for this class was generated from the following files:
src/computer_session.h
src/computer_session.cpp