Cataclysm DDA: cata::mdarray_impl_2d< T, Point, DimX, DimY > Class Template Reference
cata::mdarray_impl_2d< T, Point, DimX, DimY > Class Template Reference
#include <mdarray.h>
Public Types
using value_type = T
using column_type = std::array< T, DimY >
Public Member Functions
constexpr mdarray_impl_2d ()=default
constexpr mdarray_impl_2d (const std::initializer_list< std::initializer_list< T >> &arr)
column_type & operator[] (size_t x)
const column_type & operator[] (size_t x) const
value_type & operator[] (const Point &p)
const value_type & operator[] (const Point &p) const
void fill (const T &t_all)
template<typename F >
void fill_from_callable (const F &f)
Static Public Attributes
static constexpr size_t size_x = DimX
static constexpr size_t size_y = DimY
Private Types
using Traits = point_traits< Point >
Private Attributes
column_type data_ [DimX]
Detailed Description
template<typename T, typename Point, size_t DimX, size_t DimY>
class cata::mdarray_impl_2d< T, Point, DimX, DimY >
Definition at line 38 of file mdarray.h.
Member Typedef Documentation
column_type
template<typename T , typename Point , size_t DimX, size_t DimY> using cata::mdarray_impl_2d< T, Point, DimX, DimY >::column_type = std::array<T, DimY>
Definition at line 45 of file mdarray.h.
Traits
template<typename T , typename Point , size_t DimX, size_t DimY> using cata::mdarray_impl_2d< T, Point, DimX, DimY >::Traits = point_traits<Point> private
Definition at line 42 of file mdarray.h.
value_type
template<typename T , typename Point , size_t DimX, size_t DimY> using cata::mdarray_impl_2d< T, Point, DimX, DimY >::value_type = T
Definition at line 44 of file mdarray.h.
Constructor & Destructor Documentation
mdarray_impl_2d() [1/2]
template<typename T , typename Point , size_t DimX, size_t DimY> constexpr cata::mdarray_impl_2d< T, Point, DimX, DimY >::mdarray_impl_2d () constexpr default
mdarray_impl_2d() [2/2]
template<typename T , typename Point , size_t DimX, size_t DimY> constexpr cata::mdarray_impl_2d< T, Point, DimX, DimY >::mdarray_impl_2d (const std::initializer_list< std::initializer_list< T >> & arr) inline constexpr
Definition at line 52 of file mdarray.h.
             : data_{} {
             cata_assert( arr.size() == DimX );
             for( size_t i = 0; i != DimX; ++i ) {
                 const std::initializer_list<T> &col = arr.begin()[i];
                 cata_assert( col.size() == DimY );
                 for( size_t j = 0; j != DimY; ++j ) {
                     data_[i][j] = col.begin()[j];
                 }
             }
         }
References cata_assert, and cata::mdarray_impl_2d< T, Point, DimX, DimY >::data_.
Member Function Documentation
fill()
template<typename T , typename Point , size_t DimX, size_t DimY> void cata::mdarray_impl_2d< T, Point, DimX, DimY >::fill (const T & t_all) inline
Definition at line 80 of file mdarray.h.
{
             for( column_type &col : data_ ) {
                 for( T &t : col ) {
                     t = t_all;
                 }
             }
         }
References cata::mdarray_impl_2d< T, Point, DimX, DimY >::data_.
fill_from_callable()
template<typename T , typename Point , size_t DimX, size_t DimY> template<typename F > void cata::mdarray_impl_2d< T, Point, DimX, DimY >::fill_from_callable (const F & f) inline
Definition at line 89 of file mdarray.h.
{
             for( column_type &col : data_ ) {
                 for( T &t : col ) {
                     t = f();
                 }
             }
         }
References cata::mdarray_impl_2d< T, Point, DimX, DimY >::data_.
operator[]() [1/4]
template<typename T , typename Point , size_t DimX, size_t DimY> value_type& cata::mdarray_impl_2d< T, Point, DimX, DimY >::operator[] (const Point & p) inline
Definition at line 72 of file mdarray.h.
{
             return data_[Traits::x( p )][Traits::y( p )];
         }
References cata::mdarray_impl_2d< T, Point, DimX, DimY >::data_, point_traits< Point, typename >::x(), and point_traits< Point, typename >::y().
operator[]() [2/4]
template<typename T , typename Point , size_t DimX, size_t DimY> const value_type& cata::mdarray_impl_2d< T, Point, DimX, DimY >::operator[] (const Point & p) const inline
Definition at line 76 of file mdarray.h.
{
             return data_[Traits::x( p )][Traits::y( p )];
         }
References cata::mdarray_impl_2d< T, Point, DimX, DimY >::data_, point_traits< Point, typename >::x(), and point_traits< Point, typename >::y().
operator[]() [3/4]
template<typename T , typename Point , size_t DimX, size_t DimY> column_type& cata::mdarray_impl_2d< T, Point, DimX, DimY >::operator[] (size_t x) inline
Definition at line 64 of file mdarray.h.
{
             return data_[x];
         }
References cata::mdarray_impl_2d< T, Point, DimX, DimY >::data_.
operator[]() [4/4]
template<typename T , typename Point , size_t DimX, size_t DimY> const column_type& cata::mdarray_impl_2d< T, Point, DimX, DimY >::operator[] (size_t x) const inline
Definition at line 68 of file mdarray.h.
{
             return data_[x];
         }
References cata::mdarray_impl_2d< T, Point, DimX, DimY >::data_.
Member Data Documentation
data_
template<typename T , typename Point , size_t DimX, size_t DimY> column_type cata::mdarray_impl_2d< T, Point, DimX, DimY >::data_[DimX] private
Definition at line 100 of file mdarray.h.
Referenced by cata::mdarray_impl_2d< T, Point, DimX, DimY >::fill(), cata::mdarray_impl_2d< T, Point, DimX, DimY >::fill_from_callable(), cata::mdarray_impl_2d< T, Point, DimX, DimY >::mdarray_impl_2d(), and cata::mdarray_impl_2d< T, Point, DimX, DimY >::operator[]().
size_x
template<typename T , typename Point , size_t DimX, size_t DimY> constexpr size_t cata::mdarray_impl_2d< T, Point, DimX, DimY >::size_x = DimX static constexpr
Definition at line 47 of file mdarray.h.
size_y
template<typename T , typename Point , size_t DimX, size_t DimY> constexpr size_t cata::mdarray_impl_2d< T, Point, DimX, DimY >::size_y = DimY static constexpr
Definition at line 48 of file mdarray.h.
The documentation for this class was generated from the following file:
src/mdarray.h