Cataclysm DDA: deploy_tent_actor Class Reference
deploy_tent_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
deploy_tent_actor ()
~deploy_tent_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
bool check_intact (const tripoint &center) const
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
string_id< furn_t > wall
string_id< furn_t > floor
std::optional< string_id< furn_t > > floor_center
string_id< furn_t > door_opened
string_id< furn_t > door_closed
int radius = 1
std::optional< itype_id > broken_type
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1108 of file iuse_actor.h.
Constructor & Destructor Documentation
deploy_tent_actor()
deploy_tent_actor::deploy_tent_actor () inline
Definition at line 1119 of file iuse_actor.h.
 : iuse_actor( "deploy_tent" ) {}
~deploy_tent_actor()
deploy_tent_actor::~deploy_tent_actor () override default
Member Function Documentation
check_intact()
bool deploy_tent_actor::check_intact (const tripoint & center) const
Definition at line 5205 of file iuse_actor.cpp.
 {
     map &here = get_map();
     for( const tripoint &dest : here.points_in_radius( center, radius ) ) {
         const furn_id fid = here.furn( dest );
         if( dest == center && floor_center ) {
             if( fid != *floor_center ) {
                 return false;
             }
         } else if( square_dist( dest, center ) < radius ) {
             // So we are inside the tent
             if( fid != floor ) {
                 return false;
             }
         } else {
             // We are on the border of the tent
             if( fid != wall && fid != door_opened && fid != door_closed ) {
                 return false;
             }
         }
     }
     return true;
 }
References center, floor(), map::furn(), get_map(), map::points_in_radius(), and square_dist().
Referenced by iexamine::portable_structure().
clone()
std::unique_ptr< iuse_actor > deploy_tent_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 5141 of file iuse_actor.cpp.
 {
     return std::make_unique<deploy_tent_actor>( *this );
 }
load()
void deploy_tent_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 5146 of file iuse_actor.cpp.
 {
     assign( obj, "radius", radius );
     assign( obj, "wall", wall );
     assign( obj, "floor", floor );
     assign( obj, "floor_center", floor_center );
     assign( obj, "door_opened", door_opened );
     assign( obj, "door_closed", door_closed );
     assign( obj, "broken_type", broken_type );
 }
References assign(), and floor().
use()
std::optional< int > deploy_tent_actor::use (Character * p, item & it, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 5157 of file iuse_actor.cpp.
 {
     int diam = 2 * radius + 1;
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     const std::optional<tripoint> dir = choose_direction( string_format(
                                             _( "Put up the %s where (%dx%d clear area)?" ), it.tname(), diam, diam ) );
     if( !dir ) {
         return std::nullopt;
     }
     const tripoint direction = *dir;
     map &here = get_map();
     // We place the center of the structure (radius + 1)
     // spaces away from the player.
     // First check there's enough room.
     const tripoint center = p->pos() + tripoint( ( radius + 1 ) * direction.x,
                             ( radius + 1 ) * direction.y, 0 );
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &dest : here.points_in_radius( center, radius ) ) {
         if( const optional_vpart_position vp = here.veh_at( dest ) ) {
             add_msg( m_info, _( "The %s is in the way." ), vp->vehicle().name );
             return std::nullopt;
         }
         if( const Creature *const c = creatures.creature_at( dest ) ) {
             add_msg( m_info, _( "The %s is in the way." ), c->disp_name() );
             return std::nullopt;
         }
         if( here.impassable( dest ) || !here.has_flag( ter_furn_flag::TFLAG_FLAT, dest ) ) {
             add_msg( m_info, _( "The %s in that direction isn't suitable for placing the %s." ),
                      here.name( dest ), it.tname() );
             return std::nullopt;
         }
         if( here.has_furn( dest ) ) {
             add_msg( m_info, _( "There is already furniture (%s) there." ), here.furnname( dest ) );
             return std::nullopt;
         }
     }
     //checks done start activity:
     tent_placement_activity_actor actor( to_moves<int>( 20_minutes ), direction, radius, it, wall,
                                          floor, floor_center, door_closed );
     get_player_character().assign_activity( actor );
     p->i_rem( &it );
     return 0;
 }
References _, add_msg(), Character::assign_activity(), c, Character::cant_do_mounted(), center, choose_direction(), creature_tracker::creature_at(), floor(), map::furnname(), get_creature_tracker(), get_map(), get_player_character(), map::has_flag(), map::has_furn(), Character::i_rem(), map::impassable(), m_info, map::name(), map::points_in_radius(), Creature::pos(), string_format(), TFLAG_FLAT, item::tname(), tripoint, and map::veh_at().
Member Data Documentation
broken_type
std::optional<itype_id> deploy_tent_actor::broken_type
Definition at line 1117 of file iuse_actor.h.
Referenced by iexamine::portable_structure().
door_closed
string_id<furn_t> deploy_tent_actor::door_closed
Definition at line 1115 of file iuse_actor.h.
door_opened
string_id<furn_t> deploy_tent_actor::door_opened
Definition at line 1114 of file iuse_actor.h.
floor
string_id<furn_t> deploy_tent_actor::floor
Definition at line 1112 of file iuse_actor.h.
Referenced by find_tent_itype().
floor_center
std::optional<string_id<furn_t> > deploy_tent_actor::floor_center
Definition at line 1113 of file iuse_actor.h.
Referenced by find_tent_itype().
radius
int deploy_tent_actor::radius = 1
Definition at line 1116 of file iuse_actor.h.
Referenced by iexamine::portable_structure().
wall
string_id<furn_t> deploy_tent_actor::wall
Definition at line 1111 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp