Cataclysm DDA: read_activity_actor Class Reference
read_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Types
enum class book_type : int { normal , martial_art }
Public Member Functions
read_activity_actor ()=default
read_activity_actor (time_duration read_time, item_location &book, item_location &ereader, bool continuous=false, int learner_id=-1)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static void read_book (Character &learner, const cata::value_ptr< islot_book > &islotbook, SkillLevel &skill_level, double penalty)
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
bool player_read (avatar &you)
bool player_readma (avatar &you)
bool npc_read (npc &learner)
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
Private Attributes
int moves_total
item_location book
std::optional< book_type > bktype
item_location ereader
bool using_ereader = false
bool continuous = false
int learner_id = -1
Detailed Description
Definition at line 439 of file activity_actor_definitions.h.
Member Enumeration Documentation
book_type
enum read_activity_actor::book_type : int strong
Enumerator
normal
martial_art
Definition at line 442 of file activity_actor_definitions.h.
 : int { normal, martial_art };
Constructor & Destructor Documentation
read_activity_actor() [1/2]
read_activity_actor::read_activity_actor () default
read_activity_actor() [2/2]
read_activity_actor::read_activity_actor (time_duration read_time, item_location & book, item_location & ereader, bool continuous = false, int learner_id = -1) inline explicit
Definition at line 446 of file activity_actor_definitions.h.
             : moves_total( to_moves<int>( read_time ) ), book( book ), ereader( ereader ),
               continuous( continuous ), learner_id( learner_id ) {};
Member Function Documentation
can_resume_with_internal()
bool read_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const override private virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 2254 of file activity_actor.cpp.
 {
     const read_activity_actor &actor = static_cast<const read_activity_actor &>( other );
     // The ereader gets transformed into the _on version
     // which means the item_location of the book changes
     // this check is to prevent a segmentation fault
     if( !is_valid_book( book ) || !is_valid_book( actor.book ) ) {
         return false;
     }
     return continuous == actor.continuous &&
            learner_id == actor.learner_id &&
            book->typeId() == actor.book->typeId();
 }
References book, continuous, is_valid_book(), learner_id, other, and item::typeId().
clone()
std::unique_ptr<activity_actor> read_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 465 of file activity_actor_definitions.h.
{
             return std::make_unique<read_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > read_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 2315 of file activity_actor.cpp.
 {
     read_activity_actor actor;
     JsonObject data = jsin.get_object();
     data.read( "moves_total", actor.moves_total );
     data.read( "book", actor.book );
     data.read( "ereader", actor.ereader );
     data.read( "using_ereader", actor.using_ereader );
     data.read( "continuous", actor.continuous );
     data.read( "learner_id", actor.learner_id );
     return actor.clone();
 }
References book, clone(), continuous, ereader, JsonValue::get_object(), learner_id, moves_total, JsonObject::read(), and using_ereader.
do_turn()
void read_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Expected battery life while reading with common ereaders: integrated_ar - implant = potentially infinite ar_glasses_advanced - max 300 charges from disposable light battery = 25 hours of reading eink_tablet_pc - max 300 charges from disposable light battery = 25 hours of reading laptop - max 1200 charges from disposable medium battery = 100 hours of reading smart_phone - 120 UPS charges = 10 hours of reading
Implements activity_actor.
Definition at line 1824 of file activity_actor.cpp.
 {
     if( cancel_if_book_invalid( act, book, who ) ) {
         return;
     }
     if( !bktype.has_value() ) {
         bktype = book->type->use_methods.count( "MA_MANUAL" ) ?
                  book_type::martial_art : book_type::normal;
     }
     if( who.fine_detail_vision_mod() > 4 ) {
         // It got too dark during the process of reading, bail out.
         act.set_to_null();
         who.add_msg_if_player( m_bad, _( "It's too dark to read!" ) );
         return;
     }
     if( bktype.value() == book_type::martial_art && one_in( 3 ) ) {
         who.burn_energy_all( -1 );
     }
     // do not spam the message log
     if( calendar::once_every( 5_minutes ) ) {
         add_msg_debug( debugmode::DF_ACT_READ, "%s reading time = %s",
                        who.name, to_string_writable( time_duration::from_moves( act.moves_left ) ) );
     }
     if( using_ereader && !ereader ) {
         who.add_msg_player_or_npc(
             _( "You no longer have the e-book!" ),
             _( "<npcname> no longer has the e-book!" ) );
         who.cancel_activity();
         return;
     }
     if( using_ereader && !ereader->ammo_sufficient( &who ) ) {
         add_msg_if_player_sees(
             who,
             _( "%1$s %2$s ran out of batteries." ),
             who.disp_name( true, true ),
             item::nname( ereader->typeId() ) );
         who.cancel_activity();
         return;
     }
     if( using_ereader && calendar::once_every( 5_minutes ) ) {
         /** Expected battery life while reading with common ereaders:
                 integrated_ar       - implant                                         = potentially infinite
                 ar_glasses_advanced - max 300 charges from disposable light battery   = 25 hours of reading
                 eink_tablet_pc      - max 300 charges from disposable light battery   = 25 hours of reading
                 laptop              - max 1200 charges from disposable medium battery = 100 hours of reading
                 smart_phone         - 120 UPS charges                                 = 10 hours of reading
         */
         ereader->ammo_consume( ereader->ammo_required(), who.pos(), &who );
     }
 }
References _, act, add_msg_debug, Character::add_msg_if_player(), add_msg_if_player_sees(), Character::add_msg_player_or_npc(), item::ammo_consume(), item::ammo_required(), item::ammo_sufficient(), bktype, book, Character::burn_energy_all(), Character::cancel_activity(), cancel_if_book_invalid(), debugmode::DF_ACT_READ, Character::disp_name(), ereader, Character::fine_detail_vision_mod(), time_duration::from_moves(), m_bad, martial_art, Character::name, item::nname(), normal, calendar::once_every(), one_in(), Creature::pos(), to_string_writable(), item::type, item::typeId(), itype::use_methods, and using_ereader.
finish()
void read_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 2183 of file activity_actor.cpp.
 {
     if( cancel_if_book_invalid( act, book, who ) ) {
         return;
     }
     const bool is_mabook = bktype.value() == book_type::martial_art;
     if( who.is_avatar() ) {
         get_event_bus().send<event_type::reads_book>( who.getID(), book->typeId() );
         const bool should_null = is_mabook ?
                                  player_readma( *who.as_avatar() ) : player_read( *who.as_avatar() );
         if( should_null ) {
             act.set_to_null();
             return;
         }
     } else { // who.is_npc()
         // npcs can't read martial arts books yet
         if( is_mabook ) {
             act.set_to_null();
             return;
         }
         if( npc_read( static_cast<npc &>( who ) ) ) {
             act.set_to_null();
             return;
         }
     }
     if( continuous ) {
         time_duration time_taken;
         // caller should check if npc can read first
         if( who.is_npc() ) {
             npc &n = static_cast<npc &>( who );
             time_taken = n.time_to_read( *book, n );
         } else {    // who.is_avatar()
             // check if there can still be a reader before restarting
             // because npcs can move while reading for the player
             std::vector<std::string> fail_messages;
             const Character *reader = who.as_avatar()->get_book_reader( *book, fail_messages );
             if( reader == nullptr ) {
                 // We can't read, and neither can our followers
                 for( const std::string &reason : fail_messages ) {
                     add_msg( m_bad, reason );
                 }
                 act.set_to_null();
                 return;
             }
             time_taken = who.as_avatar()->time_to_read( *book, *reader );
             add_msg_debug( debugmode::DF_ACT_READ, "reading time = %s",
                            to_string_writable( time_taken ) );
         }
         // restart the activity
         moves_total = to_moves<int>( time_taken );
         act.moves_total = to_moves<int>( time_taken );
         act.moves_left = to_moves<int>( time_taken );
         return;
     } else  {
         who.add_msg_if_player( m_info, _( "You finish reading." ) );
     }
     act.set_to_null();
 }
References _, act, add_msg(), add_msg_debug, Character::add_msg_if_player(), Creature::as_avatar(), bktype, book, cancel_if_book_invalid(), continuous, debugmode::DF_ACT_READ, Character::get_book_reader(), get_event_bus(), Character::getID(), Creature::is_avatar(), Character::is_npc(), m_bad, m_info, martial_art, moves_total, npc_read(), player_read(), player_readma(), reads_book, event_bus::send(), npc::time_to_read(), Character::time_to_read(), to_string_writable(), and item::typeId().
get_progress_message()
std::string read_activity_actor::get_progress_message (const player_activity & act) const override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 2271 of file activity_actor.cpp.
 {
     if( !is_valid_book( book ) ) {
         return std::string();
     }
     Character &you = get_player_character();
     const cata::value_ptr<islot_book> &islotbook = book->type->book;
     const skill_id &skill = islotbook->skill;
     if( skill &&
         you.get_knowledge_level( skill ) < islotbook->level &&
         you.get_skill_level_object( skill ).can_train() &&
         you.has_identified( book->typeId() ) ) {
         const SkillLevel &skill_level = you.get_skill_level_object( skill );
         //~ skill_name current_skill_level -> next_skill_level (% to next level)
         return string_format( pgettext( "reading progress", "%1$s %2$d -> %3$d (%4$d%%)" ),
                               skill.obj().name(),
                               skill_level.knowledgeLevel(),
                               skill_level.knowledgeLevel() + 1,
                               skill_level.knowledgeExperience() );
     }
     return std::string();
 }
References book, itype::book, SkillLevel::can_train(), Character::get_knowledge_level(), get_player_character(), Character::get_skill_level_object(), Character::has_identified(), is_valid_book(), SkillLevel::knowledgeExperience(), SkillLevel::knowledgeLevel(), Skill::name(), string_id< T >::obj(), pgettext, string_format(), item::type, and item::typeId().
get_type()
activity_id read_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 452 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_READ" );
         }
References activity_id.
npc_read()
bool read_activity_actor::npc_read (npc & learner) private
Definition at line 2115 of file activity_actor.cpp.
 {
     const cata::value_ptr<islot_book> &islotbook = book->type->book;
     const skill_id &skill = islotbook->skill;
     // NPCs don't need to identify the book or learn recipes yet.
     // NPCs don't read to other NPCs yet.
     const bool display_messages = learner.get_fac_id() == faction_your_followers &&
                                   get_player_character().sees( learner );
     const int book_fun = learner.book_fun_for( *book, learner );
     if( book_fun != 0 ) {
         // Fun bonus is no longer calculated here.
         learner.add_morale( MORALE_BOOK,
                             book_fun * 5, book_fun * 15,
                             1_hours, 30_minutes, true,
                             book->type );
     }
     book->mark_chapter_as_read( learner );
     if( skill &&
         learner.get_knowledge_level( skill ) < islotbook->level &&
         learner.get_skill_level_object( skill ).can_train() ) {
         SkillLevel &skill_level = learner.get_skill_level_object( skill );
         std::string skill_name = skill.obj().name();
         const int originalSkillLevel = skill_level.knowledgeLevel();
         read_book( learner, islotbook, skill_level, 1.0 );
         const int newSkillLevel = skill_level.knowledgeLevel();
         if( newSkillLevel != originalSkillLevel ) {
             get_event_bus().send<event_type::gains_skill_level>(
                 learner.getID(), skill, skill_level.knowledgeLevel() );
             if( display_messages ) {
                 add_msg( m_good, _( "%s increases their %s level." ), learner.disp_name(),
                          skill_name );
             }
             continuous = false;
         } else if( display_messages ) {
             add_msg( m_info, _( "%s learns a little about %s!" ), learner.disp_name(),
                      skill_name );
         }
         if( display_messages &&
             ( ( skill_level == islotbook->level || !skill_level.can_train() ) ||
               ( learner.has_trait( trait_SCHIZOPHRENIC ) && !learner.has_effect( effect_took_thorazine ) &&
                 one_in( 25 ) ) ) ) {
             add_msg( m_info, _( "%s can no longer learn from %s." ), learner.disp_name(),
                      book->type_name() );
         }
     } else if( display_messages && skill ) {
         add_msg( m_info, _( "%s can no longer learn from %s." ), learner.disp_name(),
                  book->type_name() );
         continuous = false;
         // read non-skill books only once
     } else if( !skill ) {
         continuous = false;
     }
     return false;
 }
References _, Character::add_morale(), add_msg(), book, itype::book, Character::book_fun_for(), SkillLevel::can_train(), continuous, Character::disp_name(), Messages::display_messages(), effect_took_thorazine, faction_your_followers, gains_skill_level, get_event_bus(), npc::get_fac_id(), Character::get_knowledge_level(), get_player_character(), Character::get_skill_level_object(), Character::getID(), Creature::has_effect(), Character::has_trait(), SkillLevel::knowledgeLevel(), m_good, m_info, item::mark_chapter_as_read(), MORALE_BOOK, Skill::name(), string_id< T >::obj(), one_in(), read_book(), Character::sees(), event_bus::send(), trait_SCHIZOPHRENIC, item::type, and item::type_name().
Referenced by finish().
player_read()
bool read_activity_actor::player_read (avatar & you) private
Definition at line 1913 of file activity_actor.cpp.
 {
     if( !you.has_identified( book->typeId() ) ) {
         you.identify( *book );
         return true;
     }
     std::vector<std::string> fail_messages;
     const Character *reader = you.get_book_reader( *book, fail_messages );
     if( reader == nullptr ) {
         // We can't read, and neither can our followers
         for( const std::string &reason : fail_messages ) {
             add_msg( m_bad, reason );
         }
         return true;
     }
     const cata::value_ptr<islot_book> &islotbook = book->type->book;
     const skill_id &skill = islotbook->skill;
     std::vector<std::string> little_learned;
     std::vector<std::string> cant_learn;
     std::vector<Character *> learners;
     for( Character *learner : you.get_crafting_helpers() ) {
         const book_mastery mastery = learner->get_book_mastery( *book );
         const bool morale_req = learner->fun_to_read( *book ) || learner->has_morale_to_read();
         if( learner->is_deaf() && learner != reader ) {
             continue;
         }
         if( // fun readers
             ( mastery == book_mastery::MASTERED && learner->fun_to_read( *book ) )
             // reading for experience
             || ( mastery == book_mastery::LEARNING && morale_req )
         ) {
             learners.push_back( learner );
         }
     }
     // caller should check if player
     // can understand the book
     learners.push_back( you.as_character() );
     // Characters can move while learning from a book
     // Check ID of all learners to avoid
     // getting stuck in an infinite loop
     bool learner_left = true;
     for( Character *learner : learners ) {
         double penalty = 1.0;
         const bool reading_for_skill =
             learner->get_book_mastery( *book ) == book_mastery::LEARNING;
         const int book_fun = learner->book_fun_for( *book, *learner );
         if( book_fun != 0 ) {
             // Fun bonus is no longer calculated here.
             learner->add_morale( MORALE_BOOK,
                                  book_fun * 5, book_fun * 15,
                                  1_hours, 30_minutes, true,
                                  book->type );
         }
         book->mark_chapter_as_read( *learner );
         if( reading_for_skill ) {
             if( !learner->is_avatar() ) {
                 const time_duration read_time = you.time_to_read( *book, *reader, learner );
                 penalty = static_cast<double>( moves_total ) / to_moves<int>( read_time );
             }
         } else {
             continue;   // reading for fun
         }
         if( skill &&
             learner->get_knowledge_level( skill ) < islotbook->level &&
             learner->get_skill_level_object( skill ).can_train() ) {
             SkillLevel &skill_level = learner->get_skill_level_object( skill );
             std::string skill_name = skill.obj().name();
             const int originalSkillLevel = skill_level.knowledgeLevel();
             read_book( *learner, islotbook, skill_level, penalty );
             const int newSkillLevel = skill_level.knowledgeLevel();
             // levels up the skill
             if( newSkillLevel != originalSkillLevel ) {
                 get_event_bus().send<event_type::gains_skill_level>(
                     learner->getID(), skill, skill_level.knowledgeLevel() );
                 if( learner->is_avatar() ) {
                     add_msg( m_good, _( "Your theoretical knowledge of %s increases to level %d." ), skill.obj().name(),
                              originalSkillLevel + 1 );
                 } else {
                     add_msg( m_good, _( "%s increases their %s knowledge." ), learner->disp_name(),
                              skill.obj().name() );
                 }
                 if( learner->getID().get_value() == learner_id ) {
                     continuous = false;
                 }
             } else {
                 if( learner->is_avatar() ) {
                     add_msg( m_info, _( "You learn a little about %s!  (%d%%)" ), skill_name,
                              skill_level.knowledgeExperience() );
                 } else {
                     little_learned.push_back( learner->disp_name() );
                 }
             }
             if( ( skill_level == islotbook->level || !skill_level.can_train() ) ||
                 ( learner->has_trait( trait_SCHIZOPHRENIC ) && !learner->has_effect( effect_took_thorazine ) &&
                   one_in( 25 ) ) ) {
                 if( learner->is_avatar() ) {
                     add_msg( m_info, _( "You can no longer learn from %s." ), book->type_name() );
                 } else {
                     cant_learn.push_back( learner->disp_name() );
                 }
             }
         }
         if( learner_left && learner->getID().get_value() == learner_id ) {
             learner_left = false;
         }
     }   // end for all learners
     if( little_learned.size() == 1 ) {
         add_msg( m_info, _( "%s learns a little about %s!" ), little_learned.begin()->c_str(),
                  skill.obj().name() );
     } else if( !little_learned.empty() ) {
         const std::string little_learned_msg = enumerate_as_string( little_learned );
         add_msg( m_info, _( "%s learn a little about %s!" ), little_learned_msg, skill.obj().name() );
     }
     if( !cant_learn.empty() ) {
         const std::string names = enumerate_as_string( cant_learn );
         add_msg( m_info, _( "%s can no longer learn from %s." ), names, book->type_name() );
     }
     // read non-skill books only once
     if( learner_left || !skill ) {
         continuous = false;
     }
     return false;
 }
References _, add_msg(), Character::as_character(), book, itype::book, SkillLevel::can_train(), continuous, effect_took_thorazine, enumerate_as_string(), gains_skill_level, Character::get_book_reader(), Character::get_crafting_helpers(), get_event_bus(), avatar::has_identified(), avatar::identify(), SkillLevel::knowledgeExperience(), SkillLevel::knowledgeLevel(), learner_id, LEARNING, m_bad, m_good, m_info, item::mark_chapter_as_read(), MASTERED, MORALE_BOOK, moves_total, Skill::name(), PATH_INFO::names(), string_id< T >::obj(), one_in(), read_book(), event_bus::send(), Character::time_to_read(), trait_SCHIZOPHRENIC, item::type, item::type_name(), and item::typeId().
Referenced by finish().
player_readma()
bool read_activity_actor::player_readma (avatar & you) private
Definition at line 2063 of file activity_actor.cpp.
 {
     // NPCs can't learn martial arts from manuals (yet).
     if( !you.has_identified( book->typeId() ) ) {
         you.identify( *book );
         return true;
     }
     // std::map<std::string, use_function>::const_iterator
     auto mart_iter = book->type->use_methods.find( "MA_MANUAL" );
     if( mart_iter == book->type->use_methods.end() ) {
         debugmsg( "ACT_READ MARTIAL ARTS BOOK HAS NO MARTIAL ART" );
         return true;
     }
     const matype_id style_to_learn = martial_art_learned_from( *book->type );
     skill_id skill_used = style_to_learn->primary_skill;
     int difficulty = std::max( 1, style_to_learn->learn_difficulty );
     difficulty = std::max( 1, 20 + difficulty * 2 - you.get_knowledge_level( skill_used ) * 2 );
     add_msg_debug( debugmode::DF_ACT_READ, "Chance to learn one in: %d", difficulty );
     if( one_in( difficulty ) ) {
         // learn martial art
         mart_iter->second.call( &you, *book, you.pos() );
         return true;
     } else if( continuous ) {
         switch( rng( 1, 5 ) ) {
             case 1:
                 add_msg( m_info,
                          _( "You train the moves according to the book, but can't get a grasp of the style, so you start from the beginning." ) );
                 break;
             case 2:
                 add_msg( m_info,
                          _( "This martial art is not easy to grasp.  You start training the moves from the beginning." ) );
                 break;
             case 3:
                 add_msg( m_info,
                          _( "You decide to read the manual and train even more.  In martial arts, patience leads to mastery." ) );
                 break;
             case 4: // intentionally empty
             case 5:
                 add_msg( m_info, _( "You try again.  This training will finally pay off." ) );
                 break;
         }
     } else {
         add_msg( m_info, _( "You train for a while." ) );
     }
     return false;
 }
References _, add_msg(), add_msg_debug, book, continuous, debugmsg, debugmode::DF_ACT_READ, Character::get_knowledge_level(), avatar::has_identified(), avatar::identify(), martialart::learn_difficulty, m_info, martial_art_learned_from(), max(), one_in(), Creature::pos(), martialart::primary_skill, rng(), item::type, item::typeId(), and itype::use_methods.
Referenced by finish().
read_book()
void read_activity_actor::read_book (Character & learner, const cata::value_ptr< islot_book > & islotbook, SkillLevel & skill_level, double penalty) static
Intelligence increases reading comprehension
Definition at line 1882 of file activity_actor.cpp.
 {
     const int originalSkillLevel = skill_level.knowledgeLevel();
     // Calculate experience gained
     /** @EFFECT_INT increases reading comprehension */
     // Enhanced Memory Banks modestly boosts experience
     int min_ex = std::max( 1, to_minutes<int>( islotbook->time ) / 10 + learner.get_int() / 4 );
     int max_ex = to_minutes<int>( islotbook->time ) / 5 + learner.get_int() / 2 - originalSkillLevel;
     min_ex = learner.enchantment_cache->modify_value( enchant_vals::mod::READING_EXP, min_ex );
     min_ex = std::lround( learner.adjust_for_focus( min_ex ) );
     max_ex = std::lround( learner.adjust_for_focus( max_ex ) );
     max_ex = clamp( max_ex, 2, 10 );
     max_ex = std::max( min_ex, max_ex );
     min_ex *= ( originalSkillLevel + 1 ) * penalty;
     min_ex = std::max( min_ex, 1 );
     max_ex *= ( originalSkillLevel + 1 ) * penalty;
     max_ex = std::max( min_ex, max_ex );
     add_msg_debug( debugmode::DF_ACT_READ, "%s read exp: min_ex %d; max_ex %d",
                    learner.disp_name(), min_ex, max_ex );
     skill_level.readBook( min_ex, max_ex, islotbook->level );
 }
References add_msg_debug, Character::adjust_for_focus(), clamp(), debugmode::DF_ACT_READ, Character::disp_name(), Character::enchantment_cache, Character::get_int(), SkillLevel::knowledgeLevel(), max(), SkillLevel::readBook(), and enchant_vals::READING_EXP.
Referenced by npc_read(), and player_read().
serialize()
void read_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 2297 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves_total", moves_total );
     if( is_valid_book( book ) ) {
         jsout.member( "book", book );
     }
     if( ereader ) {
         jsout.member( "ereader", ereader );
     }
     jsout.member( "using_ereader", using_ereader );
     jsout.member( "continuous", continuous );
     jsout.member( "learner_id", learner_id );
     jsout.end_object();
 }
References book, continuous, JsonOut::end_object(), ereader, is_valid_book(), learner_id, JsonOut::member(), moves_total, JsonOut::start_object(), and using_ereader.
start()
void read_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1791 of file activity_actor.cpp.
 {
     if( cancel_if_book_invalid( act, book, who ) ) {
         return;
     }
     // book item_location must be of type character
     // or else there will be item_location errors while loading
     if( book.where() != item_location::type::character ) {
         book = item_location( who, book.get_item() );
     }
     using_ereader = !!ereader;
     bktype = book->type->use_methods.count( "MA_MANUAL" ) ?
              book_type::martial_art : book_type::normal;
     // push copy of book for focus calculation
     // avatar::update_mental_focus and avatar::calc_focus_equilibrium
     act.targets.push_back( book );
     add_msg_debug( debugmode::DF_ACT_READ, "reading time = %s",
                    to_string_writable( time_duration::from_moves( moves_total ) ) );
     // starting the activity should cost a charge to boot up the ebook app
     if( using_ereader ) {
         ereader->ammo_consume( ereader->ammo_required(), who.pos(), &who );
     }
     act.moves_total = moves_total;
     act.moves_left = moves_total;
 }
References act, add_msg_debug, item::ammo_consume(), item::ammo_required(), bktype, book, cancel_if_book_invalid(), item_location::character, debugmode::DF_ACT_READ, ereader, time_duration::from_moves(), item_location::get_item(), martial_art, moves_total, normal, Creature::pos(), to_string_writable(), item::type, itype::use_methods, using_ereader, and item_location::where().
Member Data Documentation
bktype
std::optional<book_type> read_activity_actor::bktype private
Definition at line 475 of file activity_actor_definitions.h.
Referenced by do_turn(), finish(), and start().
book
item_location read_activity_actor::book private
Definition at line 474 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), do_turn(), finish(), get_progress_message(), npc_read(), player_read(), player_readma(), serialize(), and start().
continuous
bool read_activity_actor::continuous = false private
Definition at line 482 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), npc_read(), player_read(), player_readma(), and serialize().
ereader
item_location read_activity_actor::ereader private
Definition at line 478 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), serialize(), and start().
learner_id
int read_activity_actor::learner_id = -1 private
Definition at line 483 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), player_read(), and serialize().
moves_total
int read_activity_actor::moves_total private
Definition at line 473 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), player_read(), serialize(), and start().
using_ereader
bool read_activity_actor::using_ereader = false private
Definition at line 479 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp