Cataclysm DDA: snippet_library Class Reference
snippet_library Class Reference
#include <text_snippets.h>
Classes
struct category_snippets
struct weighted_id
struct weighted_translation
Public Member Functions
void load_snippet (const JsonObject &jsobj)
Load snippet from the standalone entry, used by the DynamicDataLoader.
void add_snippets_from_json (const std::string &category, const JsonArray &jarr)
Load all snippet definitions in the json array into given category.
void add_snippet_from_json (const std::string &category, const JsonObject &jo)
Load a single snippet text from the json object.
void reload_names (const cata_path &path)
Load name list from name.h/cpp.
void clear_snippets ()
bool has_category (const std::string &category) const
std::optional< translation > get_snippet_by_id (const snippet_id &id) const
Returns the snippet referenced by the id, or std::nullopt if there is no snippet with such id.
std::optional< talk_effect_t > get_EOC_by_id (const snippet_id &id) const
Returns the EOC connected with the snippet referenced by the id, or std::nullopt if there is no snippet with such id.
std::optional< translation > get_name_by_id (const snippet_id &id) const
Returns the name connected with the snippet referenced by the id, or std::nullopt if there is no snippet with such id.
const translation & get_snippet_ref_by_id (const snippet_id &id) const
Returns a reference to the snippet with the id, or a reference to an empty translation object if no such snippet exist.
bool has_snippet_with_id (const snippet_id &id) const
Returns true if there exists a snippet with the id.
std::string expand (const std::string &str) const
Expand the string by recursively replacing tags in angle brackets (<>) with random snippets from the tags' respective category.
snippet_id random_id_from_category (const std::string &cat) const
Returns the id of a random snippet out of the given category.
std::optional< translation > random_from_category (const std::string &cat) const
Returns a random snippet out of the given category.
std::optional< translation > random_from_category (const std::string &cat, unsigned int seed) const
Use the given seed to select a random snippet from the category.
snippet_id migrate_hash_to_id (int hash)
Used only for legacy compatibility.
std::vector< std::pair< snippet_id, std::string > > get_snippets_by_category (const std::string &cat, bool add_null_id=false)
Private Attributes
std::unordered_map< snippet_id, translation > snippets_by_id
std::unordered_map< snippet_id, translation > name_by_id
std::unordered_map< snippet_id, talk_effect_t > EOC_by_id
std::unordered_map< std::string, category_snippets > snippets_by_category
std::optional< std::map< int, snippet_id > > hash_to_id_migration
Detailed Description
Definition at line 20 of file text_snippets.h.
Member Function Documentation
add_snippet_from_json()
void snippet_library::add_snippet_from_json (const std::string & category, const JsonObject & jo)
Load a single snippet text from the json object.
The object should have a "text" member with the text of the snippet. A "id" member is optional and if present gives the snippet text a id, stored in snippets_by_id.
Definition at line 53 of file text_snippets.cpp.
 {
     if( hash_to_id_migration.has_value() ) {
         debugmsg( "snippet_library::add_snippet_from_json called after snippet_library::migrate_hash_to_id." );
     }
     hash_to_id_migration = std::nullopt;
     uint64_t weight = 1;
     translation text;
     mandatory( jo, false, "text", text );
     optional( jo, false, "weight", weight, 1 );
     if( jo.has_member( "id" ) ) {
         snippet_id id;
         jo.read( "id", id );
         if( id.is_null() ) {
             jo.throw_error_at( "id", "Null snippet id specified" );
         }
         if( snippets_by_id.find( id ) != snippets_by_id.end() ) {
             jo.throw_error_at( "id", "Duplicate snippet id" );
         }
         std::vector<weighted_id> &ids = snippets_by_category[category].ids;
         const uint64_t weight_acc = ids.empty() ? weight : ids.back().weight_acc + weight;
         ids.emplace_back( weighted_id{ weight_acc, id } );
         snippets_by_id[id] = text;
         if( jo.has_member( "effect_on_examine" ) ) {
             EOC_by_id[id] = talk_effect_t( jo, "effect_on_examine" );
         }
         translation name;
         optional( jo, false, "name", name );
         name_by_id[id] = name;
     } else {
         std::vector<weighted_translation> &no_id = snippets_by_category[category].no_id;
         const uint64_t weight_acc = no_id.empty() ? weight : no_id.back().weight_acc + weight;
         no_id.emplace_back( weighted_translation{ weight_acc, text } );
     }
 }
References anonymous_namespace{item_tname.cpp}::category(), debugmsg, EOC_by_id, JsonObject::has_member(), hash_to_id_migration, base_camps::id, mandatory, om_direction::name(), name_by_id, optional(), JsonObject::read(), snippets_by_category, snippets_by_id, and JsonObject::throw_error_at().
Referenced by add_snippets_from_json(), and load_snippet().
add_snippets_from_json()
void snippet_library::add_snippets_from_json (const std::string & category, const JsonArray & jarr)
Load all snippet definitions in the json array into given category.
Entries in the array can be simple strings, or json objects (for the later see add_snippet_from_json).
Definition at line 31 of file text_snippets.cpp.
 {
     if( hash_to_id_migration.has_value() ) {
         debugmsg( "snippet_library::add_snippets_from_json called after snippet_library::migrate_hash_to_id." );
     }
     hash_to_id_migration = std::nullopt;
     for( const JsonValue entry : jarr ) {
         if( entry.test_string() ) {
             translation text;
             if( !entry.read( text ) ) {
                 entry.throw_error( "Error reading snippet from JSON array" );
             }
             std::vector<weighted_translation> &no_id = snippets_by_category[category].no_id;
             const uint64_t weight_acc = no_id.empty() ? 1 : no_id.back().weight_acc + 1;
             no_id.emplace_back( weighted_translation{ weight_acc, text } );
         } else {
             JsonObject jo = entry.get_object();
             add_snippet_from_json( category, jo );
         }
     }
 }
References add_snippet_from_json(), anonymous_namespace{item_tname.cpp}::category(), debugmsg, JsonObject::get_object(), hash_to_id_migration, and snippets_by_category.
Referenced by Item_factory::load_basic_info(), and load_snippet().
clear_snippets()
void snippet_library::clear_snippets ()
Definition at line 179 of file text_snippets.cpp.
 {
     hash_to_id_migration = std::nullopt;
     snippets_by_category.clear();
     snippets_by_id.clear();
     // Needed by world creation etc
     reload_names( PATH_INFO::names() );
 }
References hash_to_id_migration, PATH_INFO::names(), reload_names(), snippets_by_category, and snippets_by_id.
Referenced by DynamicDataLoader::unload_data().
expand()
std::string snippet_library::expand (const std::string & str) const
Expand the string by recursively replacing tags in angle brackets (<>) with random snippets from the tags' respective category.
For example, if the string is "<okay><punc>", the function then replaces "<okay>" with a snippet from the "<okay>" category, and "<punc>" with a snippet from the "<punc>" category, and returns, for example, "okay!". If a tag does not have a corresponding category, it is copied to the final string, for example, "drop <yrwp>, <okay>?" may expand to "drop <yrwp>, okay?" because "<yrwp>" is a special tag that does not have a category defined in the JSON files.
Definition at line 235 of file text_snippets.cpp.
 {
     size_t tag_begin = str.find( '<' );
     if( tag_begin == std::string::npos ) {
         return str;
     }
     size_t tag_end = str.find( '>', tag_begin + 1 );
     if( tag_end == std::string::npos ) {
         return str;
     }
     std::string symbol = str.substr( tag_begin, tag_end - tag_begin + 1 );
     std::optional<translation> replacement = random_from_category( symbol );
     if( !replacement.has_value() ) {
         return str.substr( 0, tag_end + 1 )
                + expand( str.substr( tag_end + 1 ) );
     }
     return str.substr( 0, tag_begin )
            + expand( replacement.value().translated() )
            + expand( str.substr( tag_end + 1 ) );
 }
References random_from_category(), replacement, and symbol().
Referenced by jmapgen_monster::apply(), jmapgen_graffiti::apply_all_tags(), jmapgen_sign::apply_all_tags(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), city::finalize(), get_music_description(), get_next_valid_worldname(), item::item(), npc::load_npc_template(), harvest_list::message(), mattack::nurse_assist(), parse_tags(), mattack::photograph(), Character::pick_name(), overmap::place_radios(), and item::set_itype_variant().
get_EOC_by_id()
std::optional< talk_effect_t > snippet_library::get_EOC_by_id (const snippet_id & id) const
Returns the EOC connected with the snippet referenced by the id, or std::nullopt if there is no snippet with such id.
Definition at line 202 of file text_snippets.cpp.
 {
     const auto it = EOC_by_id.find( id );
     if( it == EOC_by_id.end() ) {
         return std::nullopt;
     }
     return it->second;
 }
References EOC_by_id.
Referenced by item::basic_info().
get_name_by_id()
std::optional< translation > snippet_library::get_name_by_id (const snippet_id & id) const
Returns the name connected with the snippet referenced by the id, or std::nullopt if there is no snippet with such id.
Definition at line 211 of file text_snippets.cpp.
 {
     const auto it = name_by_id.find( id );
     if( it == name_by_id.end() ) {
         return std::nullopt;
     }
     return it->second;
 }
References name_by_id.
Referenced by faction_manager::display().
get_snippet_by_id()
std::optional< translation > snippet_library::get_snippet_by_id (const snippet_id & id) const
Returns the snippet referenced by the id, or std::nullopt if there is no snippet with such id.
The tags in the snippet are not automatically expanded - you need to call expand() to do that.
Definition at line 193 of file text_snippets.cpp.
 {
     const auto it = snippets_by_id.find( id );
     if( it == snippets_by_id.end() ) {
         return std::nullopt;
     }
     return it->second;
 }
References snippets_by_id.
Referenced by tutorial_game::add_message(), item::basic_info(), faction_manager::display(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), and random_from_category().
get_snippet_ref_by_id()
const translation & snippet_library::get_snippet_ref_by_id (const snippet_id & id) const
Returns a reference to the snippet with the id, or a reference to an empty translation object if no such snippet exist.
Definition at line 220 of file text_snippets.cpp.
 {
     const auto it = snippets_by_id.find( id );
     if( it == snippets_by_id.end() ) {
         static const translation empty_translation;
         return empty_translation;
     }
     return it->second;
 }
References snippets_by_id.
Referenced by get_snippets_by_category().
get_snippets_by_category()
std::vector< std::pair< snippet_id, std::string > > snippet_library::get_snippets_by_category (const std::string & cat, bool add_null_id = false)
Definition at line 348 of file text_snippets.cpp.
 {
     std::vector<std::pair<snippet_id, std::string>> ret;
     if( !has_category( cat ) ) {
         return ret;
     }
     std::unordered_map<std::string, category_snippets>::iterator snipp_cat = snippets_by_category.find(
                 cat );
     if( snipp_cat != snippets_by_category.end() ) {
         category_snippets snipps = snipp_cat->second;
         if( add_null_id && !snipps.ids.empty() ) {
             ret.emplace_back( snippet_id::NULL_ID(), "" );
         }
         for( weighted_id id : snipps.ids ) {
             std::string desc = get_snippet_ref_by_id( id.value ).translated();
             ret.emplace_back( id.value, desc );
         }
     }
     return ret;
 }
References get_snippet_ref_by_id(), has_category(), snippet_library::category_snippets::ids, string_id< translation >::NULL_ID(), cata::hash64_detail::ret, snippets_by_category, and translation::translated().
Referenced by wish_item_callback::key().
has_category()
bool snippet_library::has_category (const std::string & category) const
Definition at line 188 of file text_snippets.cpp.
 {
     return snippets_by_category.find( category ) != snippets_by_category.end();
 }
References anonymous_namespace{item_tname.cpp}::category(), and snippets_by_category.
Referenced by Item_factory::check_definitions(), get_snippets_by_category(), and wish_item_callback::key().
has_snippet_with_id()
bool snippet_library::has_snippet_with_id (const snippet_id & id) const
Returns true if there exists a snippet with the id.
Definition at line 230 of file text_snippets.cpp.
 {
     return snippets_by_id.find( id ) != snippets_by_id.end();
 }
References snippets_by_id.
load_snippet()
void snippet_library::load_snippet (const JsonObject & jsobj)
Load snippet from the standalone entry, used by the DynamicDataLoader.
Definition at line 17 of file text_snippets.cpp.
 {
     if( hash_to_id_migration.has_value() ) {
         debugmsg( "snippet_library::load_snippet called after snippet_library::migrate_hash_to_id." );
     }
     hash_to_id_migration = std::nullopt;
     const std::string category = jsobj.get_string( "category" );
     if( jsobj.has_array( "text" ) ) {
         add_snippets_from_json( category, jsobj.get_array( "text" ) );
     } else {
         add_snippet_from_json( category, jsobj );
     }
 }
References add_snippet_from_json(), add_snippets_from_json(), anonymous_namespace{item_tname.cpp}::category(), debugmsg, JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), and hash_to_id_migration.
Referenced by DynamicDataLoader::initialize().
migrate_hash_to_id()
snippet_id snippet_library::migrate_hash_to_id (int hash)
Used only for legacy compatibility.
hash_to_id_migration will be initialized if it hasn't been yet, and the snippet with the given hash is looked up and returned. If there's no longer any snippet with the given hash, snippet_id::NULL_ID() is returned instead.
Definition at line 330 of file text_snippets.cpp.
 {
     if( !hash_to_id_migration.has_value() ) {
         hash_to_id_migration.emplace();
         for( const auto &id_and_text : snippets_by_id ) {
             std::optional<int> hash = id_and_text.second.legacy_hash();
             if( hash ) {
                 hash_to_id_migration->emplace( hash.value(), id_and_text.first );
             }
         }
     }
     const auto it = hash_to_id_migration->find( old_hash );
     if( it == hash_to_id_migration->end() ) {
         return snippet_id::NULL_ID();
     }
     return it->second;
 }
References hash_to_id_migration, string_id< translation >::NULL_ID(), and snippets_by_id.
Referenced by item::io().
random_from_category() [1/2]
std::optional< translation > snippet_library::random_from_category (const std::string & cat) const
Returns a random snippet out of the given category.
Both snippets with or without an id may be returned. If there isn't any snippet in the category, std::nullopt is returned. The tags in the snippet are not automatically expanded - you need to call expand() to do that.
Definition at line 286 of file text_snippets.cpp.
 {
     return random_from_category( cat, rng_bits() );
 }
References rng_bits().
Referenced by computer_session::action_amigara_log(), computer_session::action_radio_archive(), computer_session::action_research(), computer_session::action_sr1_mess(), computer_session::action_sr2_mess(), computer_session::action_sr3_mess(), computer_session::action_sr4_mess(), computer_session::action_srcf_1_mess(), computer_session::action_srcf_2_mess(), computer_session::action_srcf_3_mess(), computer_session::action_srcf_seal_order(), Character::activate_mutation(), alcohol_diazepam_add(), amphetamine_effect(), jmapgen_sign::apply(), jmapgen_graffiti::apply(), activity_handlers::butcher_finish(), harvest_drop_type::butcher_msg(), Character::check_needs_extremes(), smart_controller_ui::control(), crack_coke_add(), monster::die(), harvest_drop_type::dissect_msg(), iuse::dog_whistle(), iuse::einktabletpc(), expand(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), harvest_drop_type::field_dress_msg(), suffer::from_other_mutations(), npc::get_epilogue(), get_hint(), get_music_description(), main_menu::init_strings(), iuse::magic_8_ball(), Character::modify_stimulation(), talk_function::morale_chat_activity(), nicotine_effect(), game::npc_menu(), opiate_effect(), timed_event::per_turn(), overmap::place_radios(), iuse::radio_on(), robot_finds_kitten::robot_finds_kitten(), mattack::shocking_reveal(), mattack::slimespring(), mattack::speaker(), activity_handlers::tree_communion_do_turn(), and weed_msg().
random_from_category() [2/2]
std::optional< translation > snippet_library::random_from_category (const std::string & cat, unsigned int seed) const
Use the given seed to select a random snippet from the category.
For the same seed, the returned snippet stays the same in a single game session, but may change after reloading or restarting a game, due to layout changes in the JSON files, for example. If there isn't any snippet in the category, std::nullopt is returned. The tags in the snippet are not automatically expanded - you need to call expand() to do that.
TODO: make the result stay the same through different game sessions
Definition at line 291 of file text_snippets.cpp.
 {
     const auto it = snippets_by_category.find( cat );
     if( it == snippets_by_category.end() ) {
         return std::nullopt;
     }
     const uint64_t ids_weighted_sum =
         it->second.ids.empty() ? 0 : it->second.ids.back().weight_acc;
     const uint64_t weight_sum = ids_weighted_sum +
                                 ( it->second.no_id.empty() ? 0 : it->second.no_id.back().weight_acc );
     if( weight_sum == 0 ) {
         return std::nullopt;
     }
     // uniform_int_distribution always returns zero when the random engine is
     // cata_default_random_engine aka std::minstd_rand0 and the seed is small,
     // so std::mt19937 is used instead. This engine is deterministically seeded,
     // so acceptable.
     // NOLINTNEXTLINE(cata-determinism)
     std::mt19937 generator( seed );
     std::uniform_int_distribution<uint64_t> dis( 0, weight_sum - 1 );
     const uint64_t loc = dis( generator );
     if( loc < ids_weighted_sum ) {
         const auto sit = std::upper_bound(
                              it->second.ids.begin(), it->second.ids.end(), loc,
         []( const uint64_t loc, const weighted_id & wid ) {
             return loc < wid.weight_acc;
         } );
         return get_snippet_by_id( sit->value );
     } else {
         const auto sit = std::upper_bound(
                              it->second.no_id.begin(), it->second.no_id.end(), loc - ids_weighted_sum,
         []( const uint64_t loc, const weighted_translation & wt ) {
             return loc < wt.weight_acc;
         } );
         return sit->value;
     }
 }
References mattack::generator(), get_snippet_by_id(), iuse::seed(), and snippets_by_category.
random_id_from_category()
snippet_id snippet_library::random_id_from_category (const std::string & cat) const
Returns the id of a random snippet out of the given category.
Snippets without an id will NOT be returned by this function. If there isn't any snippet in the category, or if none of the snippets in the category has an id, snippet_id::NULL_ID() is returned.
Definition at line 257 of file text_snippets.cpp.
 {
     const auto it = snippets_by_category.find( cat );
     if( it == snippets_by_category.end() ) {
         return snippet_id::NULL_ID();
     }
     if( !it->second.no_id.empty() ) {
         debugmsg( "ids are required, but not specified for some snippets in category %s", cat );
     }
     const uint64_t weight_sum =
         it->second.ids.empty() ? 0 : it->second.ids.back().weight_acc;
     if( weight_sum == 0 ) {
         return snippet_id::NULL_ID();
     }
     // uniform_int_distribution always returns zero when the random engine is
     // cata_default_random_engine aka std::minstd_rand0 and the seed is small,
     // so std::mt19937 is used instead. This engine is deterministically seeded,
     // so acceptable.
     // NOLINTNEXTLINE(cata-determinism)
     std::mt19937 generator( rng_bits() );
     std::uniform_int_distribution<uint64_t> dis( 0, weight_sum - 1 );
     const auto sit = std::upper_bound(
                          it->second.ids.begin(), it->second.ids.end(), dis( generator ),
     []( const uint64_t loc, const weighted_id & wid ) {
         return loc < wid.weight_acc;
     } );
     return sit->value;
 }
References debugmsg, mattack::generator(), string_id< translation >::NULL_ID(), rng_bits(), snippets_by_category, and snippet_library::weighted_id::weight_acc.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), and item::item().
reload_names()
void snippet_library::reload_names (const cata_path & path)
Load name list from name.h/cpp.
Definition at line 89 of file text_snippets.cpp.
 {
     read_from_file_json( path, [this]( const JsonArray & names_json ) {
         struct usage_info {
             bool gendered;
             category_snippets *cat;
             category_snippets *male_cat;
             category_snippets *female_cat;
         };
         const std::unordered_map<std::string, usage_info> usages = {
             { "backer", { true, nullptr, &snippets_by_category["<male_backer_name>"], &snippets_by_category["<female_backer_name>"] } },
             { "given", { true, nullptr, &snippets_by_category["<male_given_name>"], &snippets_by_category["<female_given_name>"] } },
             { "family", { false, &snippets_by_category["<family_name>"], nullptr, nullptr } },
             { "nick", { false, &snippets_by_category["<nick_name>"], nullptr, nullptr } },
             { "city", { false, &snippets_by_category["<city_name>"], nullptr, nullptr } },
             { "world", { false, &snippets_by_category["<world_name>"], nullptr, nullptr } },
         };
         // First clear previously loaded names
         for( const std::pair<const std::string, usage_info> &kv : usages ) {
             const usage_info &use = kv.second;
             if( use.gendered ) {
                 use.male_cat->no_id.clear();
                 use.female_cat->no_id.clear();
             } else {
                 use.cat->no_id.clear();
             }
         }
         for( JsonObject jo : names_json ) {
             const std::string usage = jo.get_string( "usage" );
             const auto it = usages.find( usage );
             if( it == usages.end() ) {
                 debugmsg( "Unknown name usage %s.", usage );
                 continue;
             }
             const usage_info &info = it->second;
             std::vector<category_snippets *> cats;
             if( info.gendered ) {
                 const std::string gender = jo.get_string( "gender" );
                 if( gender == "unisex" ) {
                     cats.emplace_back( info.male_cat );
                     cats.emplace_back( info.female_cat );
                 } else if( gender == "male" ) {
                     cats.emplace_back( info.male_cat );
                 } else if( gender == "female" ) {
                     cats.emplace_back( info.female_cat );
                 } else {
                     debugmsg( "Unknown name gender %s.", gender );
                     continue;
                 }
             } else {
                 cats.emplace_back( info.cat );
             }
             if( jo.has_array( "name" ) ) {
                 for( const std::string n : jo.get_array( "name" ) ) {
                     for( category_snippets *const cat : cats ) {
                         const uint64_t weight_acc = cat->no_id.empty() ? 1 : cat->no_id.back().weight_acc + 1;
                         cat->no_id.emplace_back( weighted_translation{ weight_acc, no_translation( n ) } );
                     }
                 }
             } else {
                 const std::string n = jo.get_string( "name" );
                 for( category_snippets *const cat : cats ) {
                     const uint64_t weight_acc = cat->no_id.empty() ? 1 : cat->no_id.back().weight_acc + 1;
                     cat->no_id.emplace_back( weighted_translation{ weight_acc, no_translation( n ) } );
                 }
             }
         }
         // Add fallback in case no name was loaded
         for( const std::pair<const std::string, usage_info> &kv : usages ) {
             const usage_info &use = kv.second;
             if( use.gendered ) {
                 if( use.male_cat->no_id.empty() ) {
                     use.male_cat->no_id.emplace_back( weighted_translation{ 1, to_translation( "Tom" ) } );
                 }
                 if( use.female_cat->no_id.empty() ) {
                     use.female_cat->no_id.emplace_back( weighted_translation{ 1, to_translation( "Tom" ) } );
                 }
             } else {
                 if( use.cat->no_id.empty() ) {
                     use.cat->no_id.emplace_back( weighted_translation{ 1, to_translation( "Tom" ) } );
                 }
             }
         }
     } );
 }
References item::empty(), read_from_file_json(), snippets_by_category, and game_menus::inv::use().
Referenced by clear_snippets(), and set_language().
Member Data Documentation
EOC_by_id
std::unordered_map<snippet_id, talk_effect_t> snippet_library::EOC_by_id private
Definition at line 127 of file text_snippets.h.
Referenced by add_snippet_from_json(), and get_EOC_by_id().
hash_to_id_migration
std::optional<std::map<int, snippet_id> > snippet_library::hash_to_id_migration private
Definition at line 147 of file text_snippets.h.
Referenced by add_snippet_from_json(), add_snippets_from_json(), clear_snippets(), load_snippet(), and migrate_hash_to_id().
name_by_id
std::unordered_map<snippet_id, translation> snippet_library::name_by_id private
Definition at line 126 of file text_snippets.h.
Referenced by add_snippet_from_json(), and get_name_by_id().
snippets_by_category
std::unordered_map<std::string, category_snippets> snippet_library::snippets_by_category private
Definition at line 145 of file text_snippets.h.
Referenced by add_snippet_from_json(), add_snippets_from_json(), clear_snippets(), get_snippets_by_category(), has_category(), random_from_category(), random_id_from_category(), and reload_names().
snippets_by_id
std::unordered_map<snippet_id, translation> snippet_library::snippets_by_id private
Definition at line 124 of file text_snippets.h.
Referenced by add_snippet_from_json(), clear_snippets(), get_snippet_by_id(), get_snippet_ref_by_id(), has_snippet_with_id(), and migrate_hash_to_id().
The documentation for this class was generated from the following files:
src/text_snippets.h
src/text_snippets.cpp