Cataclysm DDA: active_item_cache Class Reference
active_item_cache Class Reference
#include <active_item_cache.h>
Public Member Functions
bool add (item &it, point location, item *parent=nullptr, std::vector< item_pocket const * > const &pocket_chain={})
Adds the reference to the cache.
bool empty () const
Returns true if the cache is empty.
std::vector< item_reference > get ()
Returns a vector of all cached active item references.
std::vector< item_reference > get_for_processing ()
Returns the first size() / processing_speed() elements of each list, rounded up.
std::vector< item_reference > get_special (special_item_type type)
Returns the currently tracked list of special active items.
void subtract_locations (const point &delta)
Subtract delta from every item_reference's location.
void rotate_locations (int turns, const point &dim)
void mirror (const point &dim, bool horizontally)
Private Attributes
std::unordered_map< int, std::list< item_reference > > active_items
std::unordered_map< special_item_type, std::list< item_reference > > special_items
std::unordered_map< int, std::unordered_map< item *, safe_reference< item > > > active_items_index
Detailed Description
Definition at line 50 of file active_item_cache.h.
Member Function Documentation
add()
bool active_item_cache::add (item & it, point location, item * parent = nullptr, std::vector< item_pocket const * > const & pocket_chain = {})
Adds the reference to the cache.
Does nothing if the reference is already in the cache. Relies on the fact that item::processing_speed() is a constant.
Definition at line 20 of file active_item_cache.cpp.
 {
     std::vector<item_pocket const *> pockets = pocket_chain;
     bool ret = false;
     for( item_pocket *pk : it.get_all_standard_pockets() ) {
         pockets.emplace_back( pk );
         for( item *pkit : pk->all_items_top() ) {
             ret |= add( *pkit, location, &it, pockets );
         }
     }
     int speed = it.processing_speed();
     if( speed == item::NO_PROCESSING ) {
         return ret;
     }
     std::unordered_map<item *, safe_reference<item>> &target_index = active_items_index[speed];
     std::list<item_reference> &target_list = active_items[speed];
     if( target_index.empty() && !target_index.empty() ) {
         // If the index has been cleared, rebuild it first.
         for( item_reference &iter : target_list ) {
             // Omit those expired references
             if( iter.item_ref ) {
                 target_index.emplace( iter.item_ref.get(), iter.item_ref );
             }
         }
     }
     // If the item is already in the cache for some reason, don't add a second reference
     auto iter = target_index.find( &it );
     if( iter != target_index.end() ) {
         // Ensure it's really what we want, and hasn't expired
         if( iter->second && iter->second.get() == &it ) {
             return true;
         }
     }
     item_reference ref{ location, it.get_safe_reference(), parent, pocket_chain };
     if( it.can_revive() ) {
         special_items[special_item_type::corpse].emplace_back( ref );
     }
     if( it.get_use( "explosion" ) ) {
         special_items[special_item_type::explosive].emplace_back( ref );
     }
     target_list.emplace_back( std::move( ref ) );
     target_index.emplace( &it, it.get_safe_reference() );
     return true;
 }
References active_items, active_items_index, item::all_items_top(), item::can_revive(), corpse, explosive, item::get_all_standard_pockets(), item::get_safe_reference(), item::get_use(), location, item::NO_PROCESSING, item::processing_speed(), cata::hash64_detail::ret, special_items, and speed.
Referenced by map::add_item(), vehicle::add_item(), map::make_active(), vehicle::make_active(), vehicle::refresh_active_item_cache(), and submap::revert_submap().
empty()
bool active_item_cache::empty () const
Returns true if the cache is empty.
Definition at line 66 of file active_item_cache.cpp.
 {
     return std::all_of( active_items.begin(), active_items.end(), []( const auto & active_queue ) {
         return active_queue.second.empty();
     } );
 }
References active_items.
Referenced by map::loadn(), and map::process_items().
get()
std::vector< item_reference > active_item_cache::get ()
Returns a vector of all cached active item references.
Broken references are removed from the cache.
Definition at line 73 of file active_item_cache.cpp.
 {
     std::vector<item_reference> all_cached_items;
     for( std::pair<const int, std::list<item_reference>> &kv : active_items ) {
         for( std::list<item_reference>::iterator it = kv.second.begin(); it != kv.second.end(); ) {
             if( it->item_ref ) {
                 all_cached_items.emplace_back( *it );
                 ++it;
             } else {
                 active_items_index[kv.first].clear();
                 it = kv.second.erase( it );
             }
         }
     }
     return all_cached_items;
 }
References active_items, and active_items_index.
get_for_processing()
std::vector< item_reference > active_item_cache::get_for_processing ()
Returns the first size() / processing_speed() elements of each list, rounded up.
Items returned are rotated to the back of their respective lists, otherwise only the first n items will ever be processed. Broken references encountered when collecting the items to be processed are removed from the cache. Relies on the fact that item::processing_speed() is a constant.
Definition at line 90 of file active_item_cache.cpp.
 {
     std::vector<item_reference> items_to_process;
     items_to_process.reserve( std::accumulate( active_items.begin(), active_items.end(), std::size_t{ 0 },
     []( size_t prev, const auto & kv ) {
         return prev + kv.second.size() / static_cast<size_t>( kv.first );
     } ) );
     for( std::pair<const int, std::list<item_reference>> &kv : active_items ) {
         // Rely on iteration logic to make sure the number is sane.
         int num_to_process = kv.second.size() / kv.first;
         std::list<item_reference>::iterator it = kv.second.begin();
         for( ; it != kv.second.end() && num_to_process >= 0; ) {
             if( it->item_ref ) {
                 items_to_process.push_back( *it );
                 --num_to_process;
                 ++it;
             } else {
                 // The item has been destroyed, so remove the reference from the cache
                 active_items_index[kv.first].clear();
                 it = kv.second.erase( it );
             }
         }
         // Rotate the returned items to the end of their list so that the items that weren't
         // returned this time will be first in line on the next call
         kv.second.splice( kv.second.end(), kv.second, kv.second.begin(), it );
     }
     return items_to_process;
 }
References active_items, and active_items_index.
Referenced by map::process_items_in_submap(), and map::process_items_in_vehicle().
get_special()
std::vector< item_reference > active_item_cache::get_special (special_item_type type)
Returns the currently tracked list of special active items.
Definition at line 119 of file active_item_cache.cpp.
 {
     std::vector<item_reference> matching_items;
     std::list<item_reference> &items = special_items[type];
     for( auto it = items.begin(); it != items.end(); ) {
         if( it->item_ref ) {
             matching_items.push_back( *it );
             ++it;
         } else {
             it = items.erase( it );
         }
     }
     return matching_items;
 }
References special_items, and type.
mirror()
void active_item_cache::mirror (const point & dim, bool horizontally)
Definition at line 152 of file active_item_cache.cpp.
 {
     for( std::pair<const int, std::list<item_reference>> &pair : active_items ) {
         for( item_reference &ir : pair.second ) {
             if( horizontally ) {
                 ir.location.x = dim.x - 1 - ir.location.x;
             } else {
                 ir.location.y = dim.y - 1 - ir.location.y;
             }
         }
     }
 }
References active_items, item_reference::location, point::x, and point::y.
Referenced by submap::mirror().
rotate_locations()
void active_item_cache::rotate_locations (int turns, const point & dim)
Definition at line 143 of file active_item_cache.cpp.
 {
     for( std::pair<const int, std::list<item_reference>> &pair : active_items ) {
         for( item_reference &ir : pair.second ) {
             ir.location = ir.location.rotate( turns, dim );
         }
     }
 }
References active_items, item_reference::location, and point::rotate().
Referenced by submap::rotate().
subtract_locations()
void active_item_cache::subtract_locations (const point & delta)
Subtract delta from every item_reference's location.
Definition at line 134 of file active_item_cache.cpp.
 {
     for( std::pair<const int, std::list<item_reference>> &pair : active_items ) {
         for( item_reference &ir : pair.second ) {
             ir.location -= delta;
         }
     }
 }
References active_items, and item_reference::location.
Referenced by vehicle::shift_parts().
Member Data Documentation
active_items
std::unordered_map<int, std::list<item_reference> > active_item_cache::active_items private
Definition at line 53 of file active_item_cache.h.
Referenced by add(), empty(), get(), get_for_processing(), mirror(), rotate_locations(), and subtract_locations().
active_items_index
std::unordered_map<int, std::unordered_map<item *, safe_reference<item> > > active_item_cache::active_items_index private
Definition at line 55 of file active_item_cache.h.
Referenced by add(), get(), and get_for_processing().
special_items
std::unordered_map<special_item_type, std::list<item_reference> > active_item_cache::special_items private
Definition at line 54 of file active_item_cache.h.
Referenced by add(), and get_special().
The documentation for this class was generated from the following files:
src/active_item_cache.h
src/active_item_cache.cpp