Cataclysm DDA: overmap_special Class Reference
overmap_special Class Reference
#include <omdata.h>
Public Member Functions
overmap_special ()=default
overmap_special (const overmap_special_id &, const overmap_special_terrain &)
overmap_special_subtype get_subtype () const
const overmap_special_placement_constraints & get_constraints () const
bool is_rotatable () const
bool has_eoc () const
effect_on_condition_id get_eoc () const
bool can_spawn () const
const overmap_special_terrain & get_terrain_at (const tripoint &p) const
Returns terrain at the given point.
bool requires_city () const
bool can_belong_to_city (const tripoint_om_omt &p, const city &cit) const
const cata::flat_set< std::string > & get_flags () const
bool has_flag (const std::string &) const
int get_priority () const
int longest_side () const
std::vector< overmap_special_terrain > preview_terrains () const
std::vector< overmap_special_locations > required_locations () const
int score_rotation_at (const overmap &om, const tripoint_om_omt &p, om_direction::type r) const
special_placement_result place (overmap &om, const tripoint_om_omt &origin, om_direction::type dir, const city &cit, bool must_be_unexplored) const
const overmap_special_spawns & get_monster_spawns () const
void force_one_occurrence ()
const mapgen_parameters & get_params () const
mapgen_arguments get_args (const mapgendata &) const
void load (const JsonObject &jo, const std::string &src)
void finalize ()
void finalize_mapgen_parameters ()
void check () const
Public Attributes
overmap_special_id id
bool was_loaded = false
Private Attributes
overmap_special_subtype subtype_
overmap_special_placement_constraints constraints_
shared_ptr_fast< const overmap_special_data > data_
effect_on_condition_id eoc
bool has_eoc_ = false
bool rotatable_ = true
overmap_special_spawns monster_spawns_
cata::flat_set< std::string > flags_
int priority_ = 0
cata::flat_set< string_id< overmap_location > > default_locations_
mapgen_parameters mapgen_params_
Detailed Description
Definition at line 545 of file omdata.h.
Constructor & Destructor Documentation
overmap_special() [1/2]
overmap_special::overmap_special () default
overmap_special() [2/2]
overmap_special::overmap_special (const overmap_special_id & i, const overmap_special_terrain & ter)
Definition at line 2641 of file overmap.cpp.
     : id( i )
     , subtype_( overmap_special_subtype::fixed )
     , data_{ make_shared_fast<fixed_overmap_special_data>( ter ) }
 {}
References fixed.
Member Function Documentation
can_belong_to_city()
bool overmap_special::can_belong_to_city (const tripoint_om_omt & p, const city & cit) const
Returns
whether the special at specified tripoint can belong to the specified city.
Definition at line 2663 of file overmap.cpp.
 {
     if( !requires_city() ) {
         return true;
     }
     if( !cit || !constraints_.city_size.contains( cit.size ) ) {
         return false;
     }
     return constraints_.city_distance.contains( cit.get_distance_from( p ) - ( cit.size ) );
 }
References overmap_special_placement_constraints::city_distance, overmap_special_placement_constraints::city_size, constraints_, numeric_interval< T, typename >::contains(), city::get_distance_from(), requires_city(), and city::size.
Referenced by overmap::place_special_attempt().
can_spawn()
bool overmap_special::can_spawn () const
Definition at line 2647 of file overmap.cpp.
 {
     if( get_constraints().occurrences.empty() ) {
         return false;
     }
     const int city_size = get_option<int>( "CITY_SIZE" );
     return city_size != 0 || get_constraints().city_size.min <= city_size;
 }
References overmap_special_placement_constraints::city_size, get_constraints(), and numeric_interval< T, typename >::min.
check()
void overmap_special::check () const
Definition at line 2840 of file overmap.cpp.
 {
     data_->check( string_format( "overmap special %s", id.str() ) );
 }
References data_, and string_format().
finalize()
void overmap_special::finalize ()
Definition at line 2826 of file overmap.cpp.
 {
     const_cast<overmap_special_data &>( *data_ ).finalize(
         "overmap special " + id.str(), default_locations_ );
 }
References default_locations_, and overmap_special_data::finalize().
finalize_mapgen_parameters()
void overmap_special::finalize_mapgen_parameters ()
Definition at line 2832 of file overmap.cpp.
 {
     // Extract all the map_special-scoped params from the constituent terrains
     // and put them here
     std::string context = string_format( "overmap_special %s", id.str() );
     data_->finalize_mapgen_parameters( mapgen_params_, context );
 }
References context, data_, mapgen_params_, and string_format().
force_one_occurrence()
void overmap_special::force_one_occurrence ()
Definition at line 2727 of file overmap.cpp.
 {
     constraints_.occurrences.min = 1;
     constraints_.occurrences.max = 1;
 }
References constraints_, numeric_interval< T, typename >::max, numeric_interval< T, typename >::min, and overmap_special_placement_constraints::occurrences.
Referenced by overmapbuffer::place_special().
get_args()
mapgen_arguments overmap_special::get_args (const mapgendata & md) const
Definition at line 2733 of file overmap.cpp.
 {
     return mapgen_params_.get_args( md, mapgen_parameter_scope::overmap_special );
 }
References mapgen_parameters::get_args(), mapgen_params_, and overmap_special.
Referenced by mapgendata::mapgendata().
get_constraints()
const overmap_special_placement_constraints& overmap_special::get_constraints () const inline
Definition at line 553 of file omdata.h.
{
             return constraints_;
         }
References constraints_.
Referenced by can_spawn(), and overmap::place_special_attempt().
get_eoc()
effect_on_condition_id overmap_special::get_eoc () const inline
Definition at line 562 of file omdata.h.
{
             return eoc;
         }
References eoc.
Referenced by overmap::can_place_special(), and place().
get_flags()
const cata::flat_set<std::string>& overmap_special::get_flags () const inline
Definition at line 572 of file omdata.h.
{
             return flags_;
         }
References flags_.
get_monster_spawns()
const overmap_special_spawns& overmap_special::get_monster_spawns () const inline
Definition at line 587 of file omdata.h.
{
             return monster_spawns_;
         }
References monster_spawns_.
Referenced by overmap::place_special().
get_params()
const mapgen_parameters& overmap_special::get_params () const inline
Definition at line 593 of file omdata.h.
{
             return mapgen_params_;
         }
References mapgen_params_.
Referenced by start_location::set_parameters(), and overmap_ui::set_special_args().
get_priority()
int overmap_special::get_priority () const inline
Definition at line 576 of file omdata.h.
{
             return priority_;
         }
References priority_.
Referenced by overmap::place_special_attempt().
get_subtype()
overmap_special_subtype overmap_special::get_subtype () const inline
Definition at line 550 of file omdata.h.
{
             return subtype_;
         }
References subtype_.
get_terrain_at()
const overmap_special_terrain& overmap_special::get_terrain_at (const tripoint & p) const
Returns terrain at the given point.
has_eoc()
bool overmap_special::has_eoc () const inline
Definition at line 559 of file omdata.h.
{
             return has_eoc_;
         }
References has_eoc_.
Referenced by overmap::can_place_special(), and place().
has_flag()
bool overmap_special::has_flag (const std::string & flag) const
Definition at line 2674 of file overmap.cpp.
 {
     return flags_.count( flag );
 }
References cata::flat_set< T, Compare, Data >::count(), and flags_.
Referenced by overmap::can_place_special(), place(), overmap::place_special(), and overmap::unserialize().
is_rotatable()
bool overmap_special::is_rotatable () const inline
Definition at line 556 of file omdata.h.
{
             return rotatable_;
         }
References rotatable_.
Referenced by overmap_ui::place_ter_or_special(), and overmap::random_special_rotation().
load()
void overmap_special::load (const JsonObject & jo, const std::string & src)
Definition at line 2738 of file overmap.cpp.
 {
     const bool strict = src == "dda";
     // city_building is just an alias of overmap_special
     // TODO: This comparison is a hack. Separate them properly.
     const bool is_special = jo.get_string( "type", "" ) == "overmap_special";
     optional( jo, was_loaded, "subtype", subtype_, overmap_special_subtype::fixed );
     optional( jo, was_loaded, "locations", default_locations_ );
     if( jo.has_member( "eoc" ) ) {
         eoc = effect_on_conditions::load_inline_eoc( jo.get_member( "eoc" ), src );
         has_eoc_ = true;
     }
     switch( subtype_ ) {
         case overmap_special_subtype::fixed: {
             shared_ptr_fast<fixed_overmap_special_data> fixed_data =
                 make_shared_fast<fixed_overmap_special_data>();
             optional( jo, was_loaded, "overmaps", fixed_data->terrains );
             if( is_special ) {
                 optional( jo, was_loaded, "connections", fixed_data->connections );
             }
             data_ = std::move( fixed_data );
             break;
         }
         case overmap_special_subtype::mutable_: {
             shared_ptr_fast<mutable_overmap_special_data> mutable_data =
                 make_shared_fast<mutable_overmap_special_data>( id );
             std::vector<overmap_special_locations> check_for_locations_merged_data;
             optional( jo, was_loaded, "check_for_locations", check_for_locations_merged_data );
             if( jo.has_array( "check_for_locations_area" ) ) {
                 JsonArray jar = jo.get_array( "check_for_locations_area" );
                 while( jar.has_more() ) {
                     JsonObject joc = jar.next_object();
                     cata::flat_set<string_id<overmap_location>> type;
                     tripoint from;
                     tripoint to;
                     mandatory( joc, was_loaded, "type", type );
                     mandatory( joc, was_loaded, "from", from );
                     mandatory( joc, was_loaded, "to", to );
                     if( from.x > to.x ) {
                         std::swap( from.x, to.x );
                     }
                     if( from.y > to.y ) {
                         std::swap( from.y, to.y );
                     }
                     if( from.z > to.z ) {
                         std::swap( from.z, to.z );
                     }
                     for( int x = from.x; x <= to.x; x++ ) {
                         for( int y = from.y; y <= to.y; y++ ) {
                             for( int z = from.z; z <= to.z; z++ ) {
                                 overmap_special_locations loc;
                                 loc.p = tripoint( x, y, z );
                                 loc.locations = type;
                                 check_for_locations_merged_data.push_back( loc );
                             }
                         }
                     }
                 }
             }
             mutable_data->check_for_locations = check_for_locations_merged_data;
             mandatory( jo, was_loaded, "joins", mutable_data->joins_vec );
             mandatory( jo, was_loaded, "overmaps", mutable_data->overmaps );
             mandatory( jo, was_loaded, "root", mutable_data->root );
             mandatory( jo, was_loaded, "phases", mutable_data->phases );
             data_ = std::move( mutable_data );
             break;
         }
         default:
             jo.throw_error( string_format( "subtype %s not implemented",
                                            io::enum_to_string( subtype_ ) ) );
     }
     assign( jo, "city_sizes", constraints_.city_size, strict );
     if( is_special ) {
         mandatory( jo, was_loaded, "occurrences", constraints_.occurrences );
         assign( jo, "city_distance", constraints_.city_distance, strict );
         assign( jo, "priority", priority_, strict );
     }
     assign( jo, "spawns", monster_spawns_, strict );
     assign( jo, "rotate", rotatable_, strict );
     assign( jo, "flags", flags_, strict );
 }
References assign(), overmap_special_placement_constraints::city_distance, overmap_special_placement_constraints::city_size, constraints_, data_, default_locations_, io::enum_to_string(), eoc, fixed, flags_, JsonObject::get_array(), JsonObject::get_member(), JsonObject::get_string(), JsonObject::has_array(), has_eoc_, JsonObject::has_member(), JsonArray::has_more(), effect_on_conditions::load_inline_eoc(), overmap_special_locations::locations, mandatory, monster_spawns_, mutable_, JsonArray::next_object(), overmap_special_placement_constraints::occurrences, optional(), overmap_special_locations::p, priority_, rotatable_, strict, string_format(), subtype_, cata::swap(), JsonObject::throw_error(), tripoint, type, was_loaded, tripoint::x, tripoint::y, and tripoint::z.
longest_side()
int overmap_special::longest_side () const
Definition at line 2679 of file overmap.cpp.
 {
     // Figure out the longest side of the special for purposes of determining our sector size
     // when attempting placements.
     std::vector<overmap_special_locations> req_locations = required_locations();
     auto min_max_x = std::minmax_element( req_locations.begin(), req_locations.end(),
     []( const overmap_special_locations & lhs, const overmap_special_locations & rhs ) {
         return lhs.p.x < rhs.p.x;
     } );
     auto min_max_y = std::minmax_element( req_locations.begin(), req_locations.end(),
     []( const overmap_special_locations & lhs, const overmap_special_locations & rhs ) {
         return lhs.p.y < rhs.p.y;
     } );
     const int width = min_max_x.second->p.x - min_max_x.first->p.x;
     const int height = min_max_y.second->p.y - min_max_y.first->p.y;
     return std::max( width, height ) + 1;
 }
References max(), and required_locations().
Referenced by overmapbuffer::place_special().
place()
special_placement_result overmap_special::place (overmap & om, const tripoint_om_omt & origin, om_direction::type dir, const city & cit, bool must_be_unexplored) const
Definition at line 2715 of file overmap.cpp.
 {
     if( has_eoc() ) {
         dialogue d( get_talker_for( get_avatar() ), nullptr );
         get_eoc()->apply_true_effects( d );
     }
     const bool blob = has_flag( "BLOB" );
     return data_->place( om, origin, dir, blob, cit, must_be_unexplored );
 }
References effect_on_condition::apply_true_effects(), data_, get_avatar(), get_eoc(), get_talker_for(), has_eoc(), has_flag(), and coords::om.
Referenced by overmap::place_special().
preview_terrains()
std::vector< overmap_special_terrain > overmap_special::preview_terrains () const
Definition at line 2699 of file overmap.cpp.
 {
     return data_->preview_terrains();
 }
References data_.
Referenced by overmap_ui::draw_ascii().
required_locations()
std::vector< overmap_special_locations > overmap_special::required_locations () const
Definition at line 2704 of file overmap.cpp.
 {
     return data_->required_locations();
 }
References data_.
Referenced by overmap::can_place_special(), and longest_side().
requires_city()
bool overmap_special::requires_city () const
Returns
true if this special requires a city
Definition at line 2657 of file overmap.cpp.
 {
     return constraints_.city_size.min > 0 ||
            constraints_.city_distance.max < std::max( OMAPX, OMAPY );
 }
References overmap_special_placement_constraints::city_distance, overmap_special_placement_constraints::city_size, constraints_, numeric_interval< T, typename >::max, max(), numeric_interval< T, typename >::min, OMAPX, and OMAPY.
Referenced by can_belong_to_city().
score_rotation_at()
int overmap_special::score_rotation_at (const overmap & om, const tripoint_om_omt & p, om_direction::type r) const
Definition at line 2709 of file overmap.cpp.
 {
     return data_->score_rotation_at( om, p, r );
 }
References data_, and coords::om.
Referenced by overmap::random_special_rotation().
Member Data Documentation
constraints_
overmap_special_placement_constraints overmap_special::constraints_ private
Definition at line 613 of file omdata.h.
Referenced by can_belong_to_city(), force_one_occurrence(), get_constraints(), load(), and requires_city().
data_
shared_ptr_fast<const overmap_special_data> overmap_special::data_ private
Definition at line 614 of file omdata.h.
Referenced by check(), finalize_mapgen_parameters(), load(), place(), preview_terrains(), required_locations(), and score_rotation_at().
default_locations_
cata::flat_set<string_id<overmap_location> > overmap_special::default_locations_ private
Definition at line 623 of file omdata.h.
Referenced by finalize(), and load().
eoc
effect_on_condition_id overmap_special::eoc private
Definition at line 615 of file omdata.h.
Referenced by get_eoc(), and load().
flags_
cata::flat_set<std::string> overmap_special::flags_ private
Definition at line 619 of file omdata.h.
Referenced by get_flags(), has_flag(), and load().
has_eoc_
bool overmap_special::has_eoc_ = false private
Definition at line 616 of file omdata.h.
Referenced by has_eoc(), and load().
id
overmap_special_id overmap_special::id
Definition at line 598 of file omdata.h.
Referenced by overmap::can_place_special(), city_settings::pick_house(), city_settings::pick_park(), city_settings::pick_shop(), overmap::place_special(), overmap::place_specials(), and overmap_ui::place_ter_or_special().
mapgen_params_
mapgen_parameters overmap_special::mapgen_params_ private
Definition at line 624 of file omdata.h.
Referenced by finalize_mapgen_parameters(), get_args(), and get_params().
monster_spawns_
overmap_special_spawns overmap_special::monster_spawns_ private
Definition at line 618 of file omdata.h.
Referenced by get_monster_spawns(), and load().
priority_
int overmap_special::priority_ = 0 private
Definition at line 620 of file omdata.h.
Referenced by get_priority(), and load().
rotatable_
bool overmap_special::rotatable_ = true private
Definition at line 617 of file omdata.h.
Referenced by is_rotatable(), and load().
subtype_
overmap_special_subtype overmap_special::subtype_ private
Definition at line 612 of file omdata.h.
Referenced by get_subtype(), and load().
was_loaded
bool overmap_special::was_loaded = false
Definition at line 606 of file omdata.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/omdata.h
src/overmap.cpp