Cataclysm DDA: character_martial_arts Class Reference
character_martial_arts Class Reference
#include <character_martial_arts.h>
Public Member Functions
character_martial_arts ()
character_martial_arts (const std::vector< matype_id > &styles, const matype_id &style_selected, bool keep_hands_free)
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
void reset_style ()
void clear_style (const matype_id &id)
void selected_style_check ()
bool pick_style (const Character &you)
Creates the UI and handles player input for picking martial arts styles.
bool knows_selected_style () const
bool selected_strictly_melee () const
bool selected_allow_all_weapons () const
bool selected_has_weapon (const itype_id &weap) const
bool selected_force_unarmed () const
bool selected_prevent_weapon_blocking () const
bool selected_is_none () const
bool has_martialart (const matype_id &ma_id) const
Returns true if the player has access to the entered martial art.
void add_martialart (const matype_id &ma_id)
Adds the entered martial art to the player's list.
void learn_current_style_CQB (bool is_avatar)
void learn_style (const matype_id &mastyle, bool is_avatar)
void set_style (const matype_id &mastyle, bool force=false)
void clear_styles ()
void martialart_use_message (const Character &owner) const
Displays a message if the player can or cannot use the martial art.
void clear_all_effects (Character &owner)
Removes all martial arts events.
void ma_static_effects (Character &owner)
Fires all non-triggered martial arts events.
void ma_onmove_effects (Character &owner)
Fires all move-triggered martial arts events.
void ma_onpause_effects (Character &owner)
Fires all pause-triggered martial arts events.
void ma_onhit_effects (Character &owner)
Fires all hit-triggered martial arts events.
void ma_onattack_effects (Character &owner)
Fires all attack-triggered martial arts events.
void ma_ondodge_effects (Character &owner)
Fires all dodge-triggered martial arts events.
void ma_onblock_effects (Character &owner)
Fires all block-triggered martial arts events.
void ma_ongethit_effects (Character &owner)
Fires all get hit-triggered martial arts events.
void ma_onmiss_effects (Character &owner)
Fires all miss-triggered martial arts events.
void ma_oncrit_effects (Character &owner)
Fires all crit-triggered martial arts events.
void ma_onkill_effects (Character &owner)
Fires all kill-triggered martial arts events.
std::string get_valid_attack_vector (const Character &user, const std::vector< std::string > &attack_vectors) const
Returns an attack vector that the player can use.
bool can_use_attack_vector (const Character &user, const std::string &av) const
Returns true if the player is able to use the given attack vector.
bool can_leg_block (const Character &owner) const
Returns true if the player has the leg block technique available.
bool can_arm_block (const Character &owner) const
Returns true if the player has the arm block technique available.
bool can_nonstandard_block (const Character &owner) const
Returns true if you can block with nonstandard limbs.
bool is_force_unarmed () const
Returns true if the current style forces unarmed attack techniques.
bool can_weapon_block () const
Returns true if the current style allows blocking with weapons.
std::vector< matec_id > get_all_techniques (const item_location &weap, const Character &u) const
std::vector< matype_id > get_unknown_styles (const character_martial_arts &from, bool teachable_only) const
std::vector< matype_id > get_known_styles (bool teachable_only) const
bool has_technique (const Character &guy, const matec_id &id, const item &weap) const
Returns true if the player has a weapon or martial arts skill available with the entered technique.
ma_technique get_grab_break (const Character &owner) const
Returns the first valid grab break technique.
ma_technique get_miss_recovery (const Character &owner) const
Returns the first valid miss recovery technique.
std::string enumerate_known_styles (const itype_id &weap) const
std::string selected_style_name (const Character &owner) const
const matype_id & selected_style () const
Public Attributes
bool keep_hands_free = false
Private Attributes
std::vector< matype_id > ma_styles
matype_id style_selected = matype_id("style_none")
Detailed Description
Definition at line 17 of file character_martial_arts.h.
Constructor & Destructor Documentation
character_martial_arts() [1/2]
character_martial_arts::character_martial_arts ()
Definition at line 22 of file character_martial_arts.cpp.
 {
     keep_hands_free = false;
     style_selected = style_none;
     ma_styles = { {
             style_none, style_kicks
         }
     };
 }
References keep_hands_free, ma_styles, style_kicks, style_none, and style_selected.
character_martial_arts() [2/2]
character_martial_arts::character_martial_arts (const std::vector< matype_id > & styles, const matype_id & style_selected, bool keep_hands_free) inline
Definition at line 24 of file character_martial_arts.h.
             : ma_styles( styles ), style_selected( style_selected ), keep_hands_free( keep_hands_free ) {}
Member Function Documentation
add_martialart()
void character_martial_arts::add_martialart (const matype_id & ma_id)
Adds the entered martial art to the player's list.
Definition at line 1775 of file martialarts.cpp.
 {
     if( has_martialart( ma_id ) ) {
         return;
     }
     ma_styles.emplace_back( ma_id );
 }
References has_martialart(), and ma_styles.
Referenced by learn_current_style_CQB(), and learn_style().
can_arm_block()
bool character_martial_arts::can_arm_block (const Character & owner) const
Returns true if the player has the arm block technique available.
Unarmed increases ability to perform arm block
Definition at line 1445 of file martialarts.cpp.
 {
     const martialart &ma = style_selected.obj();
     ///\EFFECT_UNARMED increases ability to perform arm block
     const int unarmed_skill = owner.has_active_bionic( bio_cqb ) ? 5 : owner.get_skill_level(
                                   skill_unarmed );
     // before we check our arms, can you block at all?
     const bool block_with_skill = unarmed_skill >= ma.arm_block;
     const bool block_with_bio_armor = ma.arm_block_with_bio_armor_arms &&
                                       owner.has_bionic( bio_armor_arms );
     if( !( block_with_skill || block_with_bio_armor ) ) {
         return false;
     }
     // Success conditions.
     // Do we have boring human anatomy? Use the basic calculation
     if( !owner.has_flag( json_flag_NONSTANDARD_BLOCK ) ) {
         return owner.get_limb_score( limb_score_block, body_part_type::type::arm ) >= 0.5f;
     } else {
         // Check all standard arms for the score threshold
         for( const bodypart_id &bp : owner.get_all_body_parts_of_type( body_part_type::type::arm ) ) {
             if( !bp->has_flag( json_flag_NONSTANDARD_BLOCK ) &&
                 owner.get_part( bp )->get_limb_score( limb_score_block ) * bp->limbtypes.at(
                     body_part_type::type::arm ) >= 0.25f ) {
                 return true;
             }
         }
     }
     // if not above, can't block.
     return false;
 }
References body_part_type::arm, martialart::arm_block, martialart::arm_block_with_bio_armor_arms, bio_armor_arms, bio_cqb, bp, Creature::get_all_body_parts_of_type(), Character::get_limb_score(), bodypart::get_limb_score(), Creature::get_part(), Character::get_skill_level(), Character::has_active_bionic(), Character::has_bionic(), body_part_type::has_flag(), Character::has_flag(), json_flag_NONSTANDARD_BLOCK, limb_score_block, body_part_type::limbtypes, string_id< T >::obj(), skill_unarmed, and style_selected.
can_leg_block()
bool character_martial_arts::can_leg_block (const Character & owner) const
Returns true if the player has the leg block technique available.
Unarmed increases ability to perform leg block
Definition at line 1410 of file martialarts.cpp.
 {
     const martialart &ma = style_selected.obj();
     ///\EFFECT_UNARMED increases ability to perform leg block
     const int unarmed_skill = owner.has_active_bionic( bio_cqb ) ? 5 : owner.get_skill_level(
                                   skill_unarmed );
     // Before we check our legs, can you block at all?
     const bool block_with_skill = unarmed_skill >= ma.leg_block;
     const bool block_with_bio_armor = ma.leg_block_with_bio_armor_legs &&
                                       owner.has_bionic( bio_armor_legs );
     if( !( block_with_skill || block_with_bio_armor ) ) {
         return false;
     }
     // Success conditions.
     // Do we have boring human anatomy? Use the basic calculation
     // Legs are harder to block with, so the score thresholds stay the same
     if( !owner.has_flag( json_flag_NONSTANDARD_BLOCK ) ) {
         return owner.get_limb_score( limb_score_block, body_part_type::type::leg ) >= 0.5f;
     } else {
         // Check all standard legs for the score threshold
         for( const bodypart_id &bp : owner.get_all_body_parts_of_type( body_part_type::type::leg ) ) {
             if( !bp->has_flag( json_flag_NONSTANDARD_BLOCK ) &&
                 owner.get_part( bp )->get_limb_score( limb_score_block ) * bp->limbtypes.at(
                     body_part_type::type::leg ) >= 0.25f ) {
                 return true;
             }
         }
     }
     // if not above, can't block.
     return false;
 }
References bio_armor_legs, bio_cqb, bp, Creature::get_all_body_parts_of_type(), Character::get_limb_score(), bodypart::get_limb_score(), Creature::get_part(), Character::get_skill_level(), Character::has_active_bionic(), Character::has_bionic(), body_part_type::has_flag(), Character::has_flag(), json_flag_NONSTANDARD_BLOCK, body_part_type::leg, martialart::leg_block, martialart::leg_block_with_bio_armor_legs, limb_score_block, body_part_type::limbtypes, string_id< T >::obj(), skill_unarmed, and style_selected.
can_nonstandard_block()
bool character_martial_arts::can_nonstandard_block (const Character & owner) const
Returns true if you can block with nonstandard limbs.
Definition at line 1478 of file martialarts.cpp.
 {
     // No nonstandard limb that blocks
     if( !owner.has_flag( json_flag_NONSTANDARD_BLOCK ) && !owner.has_flag( json_flag_ALWAYS_BLOCK ) ) {
         return false;
     }
     const martialart &ma = style_selected.obj();
     // Bionic combatives won't help with nonstandard anatomy
     const int unarmed_skill = owner.get_skill_level(
                                   skill_unarmed );
     const bool block_with_skill = unarmed_skill >= ma.nonstandard_block;
     // Filter out the case where the flagged BP is overencumbered/broken but blocking score is contributed by arms/legs
     // Success conditions
     // Return true if the limbs which would always block can block
     if( owner.has_flag( json_flag_ALWAYS_BLOCK ) ) {
         for( const bodypart_id &bp : owner.get_all_body_parts_with_flag( json_flag_ALWAYS_BLOCK ) ) {
             if( owner.get_part( bp )->get_limb_score( limb_score_block ) >= 0.25f ) {
                 return true;
             }
         }
     }
     // Return true if we're skilled enough to block and we have at least one limb ready to block
     if( block_with_skill ) {
         for( const bodypart_id &bp : owner.get_all_body_parts_with_flag( json_flag_NONSTANDARD_BLOCK ) ) {
             if( owner.get_part( bp )->get_limb_score( limb_score_block ) >= 0.25f ) {
                 return true;
             }
         }
     }
     return false;
 }
References bp, Creature::get_all_body_parts_with_flag(), bodypart::get_limb_score(), Creature::get_part(), Character::get_skill_level(), Character::has_flag(), json_flag_ALWAYS_BLOCK, json_flag_NONSTANDARD_BLOCK, limb_score_block, martialart::nonstandard_block, string_id< T >::obj(), skill_unarmed, and style_selected.
can_use_attack_vector()
bool character_martial_arts::can_use_attack_vector (const Character & user, const std::string & av) const
Returns true if the player is able to use the given attack vector.
Definition at line 1387 of file martialarts.cpp.
 {
     martialart ma = style_selected.obj();
     bool valid_weapon = ma.weapon_valid( user.get_wielded_item() );
     int arm_r_hp = user.get_part_hp_cur( bodypart_id( "arm_r" ) );
     int arm_l_hp = user.get_part_hp_cur( bodypart_id( "arm_l" ) );
     int leg_r_hp = user.get_part_hp_cur( bodypart_id( "leg_r" ) );
     int leg_l_hp = user.get_part_hp_cur( bodypart_id( "leg_l" ) );
     bool healthy_arm = arm_r_hp > 0 || arm_l_hp > 0;
     bool healthy_arms = arm_r_hp > 0 && arm_l_hp > 0;
     bool healthy_legs = leg_r_hp > 0 && leg_l_hp > 0;
     bool mouth_ok = ( av == "MOUTH" ) && !user.natural_attack_restricted_on( bodypart_id( "mouth" ) );
     bool always_ok = av == "HEAD" || av == "TORSO";
     bool weapon_ok = av == "WEAPON" && valid_weapon && healthy_arm;
     bool arm_ok = ( av == "HAND" || av == "FINGER" || av == "WRIST" || av == "ARM" || av == "ELBOW" ||
                     av == "HAND_BACK" || av == "PALM" || av == "SHOULDER" ) && healthy_arm;
     bool arms_ok = ( av == "GRAPPLE" || av == "THROW" ) && healthy_arms;
     bool legs_ok = ( av == "FOOT" || av == "LOWER_LEG" || av == "KNEE" || av == "HIP" ) && healthy_legs;
     return always_ok || weapon_ok || mouth_ok || arm_ok || arms_ok || legs_ok;
 }
References Creature::get_part_hp_cur(), Character::get_wielded_item(), Character::natural_attack_restricted_on(), string_id< T >::obj(), style_selected, and martialart::weapon_valid().
Referenced by get_valid_attack_vector().
can_weapon_block()
bool character_martial_arts::can_weapon_block () const
Returns true if the current style allows blocking with weapons.
Definition at line 1519 of file martialarts.cpp.
 {
     return !style_selected->prevent_weapon_blocking;
 }
References martialart::prevent_weapon_blocking, and style_selected.
clear_all_effects()
void character_martial_arts::clear_all_effects (Character & owner)
Removes all martial arts events.
Definition at line 1524 of file martialarts.cpp.
 {
     style_selected->remove_all_buffs( owner );
 }
References martialart::remove_all_buffs(), and style_selected.
clear_style()
void character_martial_arts::clear_style (const matype_id & id)
Definition at line 103 of file character_martial_arts.cpp.
 {
     ma_styles.erase( std::remove( ma_styles.begin(), ma_styles.end(), id ), ma_styles.end() );
     selected_style_check();
 }
References ma_styles, and selected_style_check().
clear_styles()
void character_martial_arts::clear_styles ()
Definition at line 109 of file character_martial_arts.cpp.
 {
     keep_hands_free = false;
     ma_styles = { {
             style_none, style_kicks
         }
     };
     reset_style();
 }
References keep_hands_free, ma_styles, reset_style(), style_kicks, and style_none.
deserialize()
void character_martial_arts::deserialize (const JsonObject & data)
Definition at line 190 of file character_martial_arts.cpp.
 {
     data.read( "ma_styles", ma_styles );
     data.read( "keep_hands_free", keep_hands_free );
     data.read( "style_selected", style_selected );
 }
References keep_hands_free, ma_styles, JsonObject::read(), and style_selected.
enumerate_known_styles()
std::string character_martial_arts::enumerate_known_styles (const itype_id & weap) const
Definition at line 136 of file character_martial_arts.cpp.
 {
     return enumerate_as_string( ma_styles.begin(), ma_styles.end(),
     [weap]( const matype_id & mid ) {
         return mid->has_weapon( weap ) ? colorize( mid->name.translated(), c_cyan ) : std::string();
     } );
 }
References enumerate_as_string(), and ma_styles.
get_all_techniques()
std::vector< matec_id > character_martial_arts::get_all_techniques (const item_location & weap, const Character & u) const
Definition at line 1320 of file martialarts.cpp.
 {
     std::vector<matec_id> tecs;
     const martialart &style = style_selected.obj();
     // Grab individual item techniques if the style allows them
     if( weap && !style.force_unarmed ) {
         const auto &weapon_techs = weap->get_techniques();
         tecs.insert( tecs.end(), weapon_techs.begin(), weapon_techs.end() );
     }
     // If we have any items that also provide techniques
     const std::vector<const item *> tech_providing_items = u.cache_get_items_with(
                 json_flag_PROVIDES_TECHNIQUES );
     for( const item *it : tech_providing_items ) {
         const std::set<matec_id> &item_techs = it->get_techniques();
         tecs.insert( tecs.end(), item_techs.begin(), item_techs.end() );
     }
     // and martial art techniques
     tecs.insert( tecs.end(), style.techniques.begin(), style.techniques.end() );
     // And limb techniques
     const auto &limb_techs = u.get_limb_techs();
     tecs.insert( tecs.end(), limb_techs.begin(), limb_techs.end() );
     return tecs;
 }
References martialart::force_unarmed, item::get_techniques(), json_flag_PROVIDES_TECHNIQUES, string_id< T >::obj(), style_selected, martialart::techniques, and u.
get_grab_break()
ma_technique character_martial_arts::get_grab_break (const Character & owner) const
Returns the first valid grab break technique.
Definition at line 1365 of file martialarts.cpp.
 {
     return get_valid_technique( owner, &ma_technique::grab_break );
 }
References get_valid_technique(), and ma_technique::grab_break.
get_known_styles()
std::vector< matype_id > character_martial_arts::get_known_styles (bool teachable_only) const
Definition at line 167 of file character_martial_arts.cpp.
 {
     if( !teachable_only ) {
         return ma_styles;
     }
     std::vector<matype_id> ret;
     for( const matype_id &i : ma_styles ) {
         if( i->teachable ) {
             ret.push_back( i );
         }
     }
     return ret;
 }
References ma_styles, and cata::hash64_detail::ret.
get_miss_recovery()
ma_technique character_martial_arts::get_miss_recovery (const Character & owner) const
Returns the first valid miss recovery technique.
Definition at line 1370 of file martialarts.cpp.
 {
     return get_valid_technique( owner, &ma_technique::miss_recovery );
 }
References get_valid_technique(), and ma_technique::miss_recovery.
get_unknown_styles()
std::vector< matype_id > character_martial_arts::get_unknown_styles (const character_martial_arts & from, bool teachable_only) const
Definition at line 155 of file character_martial_arts.cpp.
 {
     std::vector<matype_id> ret;
     for( const matype_id &i : from.ma_styles ) {
         if( ( !teachable_only || i->teachable ) && !has_martialart( i ) ) {
             ret.push_back( i );
         }
     }
     return ret;
 }
References has_martialart(), ma_styles, cata::hash64_detail::ret, and martialart::teachable.
get_valid_attack_vector()
std::string character_martial_arts::get_valid_attack_vector (const Character & user, const std::vector< std::string > & attack_vectors) const
Returns an attack vector that the player can use.
Definition at line 1375 of file martialarts.cpp.
 {
     for( auto av : attack_vectors ) {
         if( can_use_attack_vector( user, av ) ) {
             return av;
         }
     }
     return "NONE";
 }
References can_use_attack_vector().
has_martialart()
bool character_martial_arts::has_martialart (const matype_id & ma_id) const
Returns true if the player has access to the entered martial art.
Definition at line 1770 of file martialarts.cpp.
 {
     return std::find( ma_styles.begin(), ma_styles.end(), ma ) != ma_styles.end();
 }
References ma_styles.
Referenced by add_martialart(), get_unknown_styles(), knows_selected_style(), and set_style().
has_technique()
bool character_martial_arts::has_technique (const Character & guy, const matec_id & id, const item & weap) const
Returns true if the player has a weapon or martial arts skill available with the entered technique.
Definition at line 1765 of file melee.cpp.
 {
     return weap.has_technique( id ) ||
            style_selected->has_technique( guy, id );
 }
References martialart::has_technique(), item::has_technique(), and style_selected.
is_force_unarmed()
bool character_martial_arts::is_force_unarmed () const
Returns true if the current style forces unarmed attack techniques.
Definition at line 1514 of file martialarts.cpp.
 {
     return style_selected->force_unarmed;
 }
References martialart::force_unarmed, and style_selected.
knows_selected_style()
bool character_martial_arts::knows_selected_style () const
Definition at line 60 of file character_martial_arts.cpp.
 {
     return has_martialart( style_selected );
 }
References has_martialart(), and style_selected.
learn_current_style_CQB()
void character_martial_arts::learn_current_style_CQB (bool is_avatar)
Definition at line 70 of file character_martial_arts.cpp.
 {
     add_martialart( style_selected );
     if( is_avatar ) {
         add_msg( m_good, _( "You have learned %s from extensive practice with the CQB Bionic." ),
                  style_selected->name );
     }
 }
References _, add_martialart(), add_msg(), m_good, martialart::name, and style_selected.
learn_style()
void character_martial_arts::learn_style (const matype_id & mastyle, bool is_avatar)
Definition at line 79 of file character_martial_arts.cpp.
 {
     add_martialart( mastyle );
     if( is_avatar ) {
         add_msg( m_good, _( "You learn %s." ),
                  mastyle->name );
         add_msg( m_info, _( "%s to select martial arts style." ),
                  press_x( ACTION_PICK_STYLE ) );
     }
 }
References _, ACTION_PICK_STYLE, add_martialart(), add_msg(), m_good, m_info, martialart::name, and press_x().
ma_onattack_effects()
void character_martial_arts::ma_onattack_effects (Character & owner)
Fires all attack-triggered martial arts events.
Definition at line 1550 of file martialarts.cpp.
 {
     style_selected->apply_onattack_buffs( owner );
     style_selected->apply_onattack_eocs( owner );
 }
References martialart::apply_onattack_buffs(), martialart::apply_onattack_eocs(), and style_selected.
ma_onblock_effects()
void character_martial_arts::ma_onblock_effects (Character & owner)
Fires all block-triggered martial arts events.
Definition at line 1560 of file martialarts.cpp.
 {
     style_selected->apply_onblock_buffs( owner );
     style_selected->apply_onblock_eocs( owner );
 }
References martialart::apply_onblock_buffs(), martialart::apply_onblock_eocs(), and style_selected.
ma_oncrit_effects()
void character_martial_arts::ma_oncrit_effects (Character & owner)
Fires all crit-triggered martial arts events.
Definition at line 1575 of file martialarts.cpp.
 {
     style_selected->apply_oncrit_buffs( owner );
     style_selected->apply_oncrit_eocs( owner );
 }
References martialart::apply_oncrit_buffs(), martialart::apply_oncrit_eocs(), and style_selected.
ma_ondodge_effects()
void character_martial_arts::ma_ondodge_effects (Character & owner)
Fires all dodge-triggered martial arts events.
Definition at line 1555 of file martialarts.cpp.
 {
     style_selected->apply_ondodge_buffs( owner );
     style_selected->apply_ondodge_eocs( owner );
 }
References martialart::apply_ondodge_buffs(), martialart::apply_ondodge_eocs(), and style_selected.
ma_ongethit_effects()
void character_martial_arts::ma_ongethit_effects (Character & owner)
Fires all get hit-triggered martial arts events.
Definition at line 1565 of file martialarts.cpp.
 {
     style_selected->apply_ongethit_buffs( owner );
     style_selected->apply_ongethit_eocs( owner );
 }
References martialart::apply_ongethit_buffs(), martialart::apply_ongethit_eocs(), and style_selected.
ma_onhit_effects()
void character_martial_arts::ma_onhit_effects (Character & owner)
Fires all hit-triggered martial arts events.
Definition at line 1545 of file martialarts.cpp.
 {
     style_selected->apply_onhit_buffs( owner );
     style_selected->apply_onhit_eocs( owner );
 }
References martialart::apply_onhit_buffs(), martialart::apply_onhit_eocs(), and style_selected.
ma_onkill_effects()
void character_martial_arts::ma_onkill_effects (Character & owner)
Fires all kill-triggered martial arts events.
Definition at line 1580 of file martialarts.cpp.
 {
     style_selected->apply_onkill_buffs( owner );
     style_selected->apply_onkill_eocs( owner );
 }
References martialart::apply_onkill_buffs(), martialart::apply_onkill_eocs(), and style_selected.
ma_onmiss_effects()
void character_martial_arts::ma_onmiss_effects (Character & owner)
Fires all miss-triggered martial arts events.
Definition at line 1570 of file martialarts.cpp.
 {
     style_selected->apply_onmiss_buffs( owner );
     style_selected->apply_onmiss_eocs( owner );
 }
References martialart::apply_onmiss_buffs(), martialart::apply_onmiss_eocs(), and style_selected.
ma_onmove_effects()
void character_martial_arts::ma_onmove_effects (Character & owner)
Fires all move-triggered martial arts events.
Definition at line 1535 of file martialarts.cpp.
 {
     style_selected->apply_onmove_buffs( owner );
     style_selected->apply_onmove_eocs( owner );
 }
References martialart::apply_onmove_buffs(), martialart::apply_onmove_eocs(), and style_selected.
ma_onpause_effects()
void character_martial_arts::ma_onpause_effects (Character & owner)
Fires all pause-triggered martial arts events.
Definition at line 1540 of file martialarts.cpp.
 {
     style_selected->apply_onpause_buffs( owner );
     style_selected->apply_onpause_eocs( owner );
 }
References martialart::apply_onpause_buffs(), martialart::apply_onpause_eocs(), and style_selected.
ma_static_effects()
void character_martial_arts::ma_static_effects (Character & owner)
Fires all non-triggered martial arts events.
Definition at line 1530 of file martialarts.cpp.
 {
     style_selected->apply_static_buffs( owner );
     style_selected->apply_static_eocs( owner );
 }
References martialart::apply_static_buffs(), martialart::apply_static_eocs(), and style_selected.
Referenced by pick_style().
martialart_use_message()
void character_martial_arts::martialart_use_message (const Character & owner) const
Displays a message if the player can or cannot use the martial art.
Definition at line 1801 of file martialarts.cpp.
 {
     martialart ma = style_selected.obj();
     if( ma.force_unarmed || ma.weapon_valid( owner.get_wielded_item() ) ) {
         owner.add_msg_if_player( m_info, "%s", ma.get_initiate_avatar_message() );
     } else if( ma.strictly_melee && !owner.is_armed() ) {
         owner.add_msg_if_player( m_bad, _( "%s cannot be used unarmed." ), ma.name );
     } else if( ma.strictly_unarmed && owner.is_armed() ) {
         owner.add_msg_if_player( m_bad, _( "%s cannot be used with weapons." ), ma.name );
     } else {
         owner.add_msg_if_player( m_bad, _( "The %1$s is not a valid %2$s weapon." ),
                                  owner.get_wielded_item()->tname( 1, false ), ma.name );
     }
 }
References _, Character::add_msg_if_player(), martialart::force_unarmed, martialart::get_initiate_avatar_message(), Character::get_wielded_item(), Character::is_armed(), m_bad, m_info, martialart::name, string_id< T >::obj(), martialart::strictly_melee, martialart::strictly_unarmed, style_selected, item::tname(), and martialart::weapon_valid().
Referenced by pick_style().
pick_style()
bool character_martial_arts::pick_style (const Character & you)
Creates the UI and handles player input for picking martial arts styles.
Definition at line 13350 of file character.cpp.
 {
     enum style_selection {
         KEEP_HANDS_FREE = 0,
         STYLE_OFFSET
     };
     // Check for martial art styles known from active bionics
     std::set<matype_id> bio_styles;
     for( const bionic &bio : *you.my_bionics ) {
         const std::vector<matype_id> &bio_ma_list = bio.id->ma_styles;
         if( !bio_ma_list.empty() && you.has_active_bionic( bio.id ) ) {
             bio_styles.insert( bio_ma_list.begin(), bio_ma_list.end() );
         }
     }
     std::vector<matype_id> selectable_styles;
     if( bio_styles.empty() ) {
         selectable_styles = ma_styles;
     } else {
         selectable_styles.insert( selectable_styles.begin(), bio_styles.begin(), bio_styles.end() );
     }
     // If there are style already, cursor starts there
     // if no selected styles, cursor starts from no-style
     // Any other keys quit the menu
     input_context ctxt( "MELEE_STYLE_PICKER", keyboard_mode::keycode );
     ctxt.register_action( "SHOW_DESCRIPTION" );
     uilist kmenu;
     kmenu.text = string_format( _( "Select a style.\n"
                                    "\n"
                                    "STR: <color_white>%d</color>, DEX: <color_white>%d</color>, "
                                    "PER: <color_white>%d</color>, INT: <color_white>%d</color>\n"
                                    "Press [<color_yellow>%s</color>] for technique details and compatible weapons.\n" ),
                                 you.get_str(), you.get_dex(), you.get_per(), you.get_int(),
                                 ctxt.get_desc( "SHOW_DESCRIPTION" ) );
     ma_style_callback callback( static_cast<size_t>( STYLE_OFFSET ), selectable_styles );
     kmenu.callback = &callback;
     kmenu.input_category = "MELEE_STYLE_PICKER";
     kmenu.additional_actions.emplace_back( "SHOW_DESCRIPTION", translation() );
     kmenu.desc_enabled = true;
     kmenu.addentry_desc( KEEP_HANDS_FREE, true, 'h',
                          keep_hands_free ? _( "Keep hands free (on)" ) : _( "Keep hands free (off)" ),
                          _( "When this is enabled, player won't wield things unless explicitly told to." ) );
     kmenu.selected = STYLE_OFFSET;
     // +1 to keep "No Style" at top
     std::sort( selectable_styles.begin() + 1, selectable_styles.end(),
     []( const matype_id & a, const matype_id & b ) {
         return localized_compare( a->name.translated(), b->name.translated() );
     } );
     for( size_t i = 0; i < selectable_styles.size(); i++ ) {
         const martialart &style = selectable_styles[i].obj();
         //Check if this style is currently selected
         const bool selected = selectable_styles[i] == style_selected;
         std::string entry_text = style.name.translated();
         if( selected ) {
             kmenu.selected = i + STYLE_OFFSET;
             entry_text = colorize( entry_text, c_pink );
         }
         kmenu.addentry_desc( i + STYLE_OFFSET, true, -1, entry_text, style.description.translated() );
     }
     kmenu.query();
     int selection = kmenu.ret;
     if( selection >= STYLE_OFFSET ) {
         // If the currect style is selected, do not change styles
         Character &u = const_cast<Character &>( you );
         style_selected->remove_all_buffs( u );
         style_selected = selectable_styles[selection - STYLE_OFFSET];
         ma_static_effects( u );
         martialart_use_message( you );
     } else if( selection == KEEP_HANDS_FREE ) {
         keep_hands_free = !keep_hands_free;
     } else {
         return false;
     }
     return true;
 }
References _, a, uilist::addentry_desc(), uilist::additional_actions, b, c_pink, uilist::callback, colorize(), uilist::desc_enabled, martialart::description, input_context::get_desc(), Character::get_dex(), Character::get_int(), Character::get_per(), Character::get_str(), Character::has_active_bionic(), bionic::id, uilist::input_category, keep_hands_free, keycode, ma_static_effects(), bionic_data::ma_styles, ma_styles, martialart_use_message(), Character::my_bionics, martialart::name, uilist::query(), input_context::register_action(), martialart::remove_all_buffs(), uilist::ret, uilist::selected, string_format(), style_selected, uilist::text, translation::translated(), and u.
reset_style()
void character_martial_arts::reset_style ()
Definition at line 98 of file character_martial_arts.cpp.
 {
     style_selected = style_none;
 }
References style_none, and style_selected.
Referenced by clear_styles(), and selected_style_check().
selected_allow_all_weapons()
bool character_martial_arts::selected_allow_all_weapons () const
Definition at line 35 of file character_martial_arts.cpp.
 {
     return style_selected->allow_all_weapons;
 }
References martialart::allow_all_weapons, and style_selected.
selected_force_unarmed()
bool character_martial_arts::selected_force_unarmed () const
Definition at line 50 of file character_martial_arts.cpp.
 {
     return style_selected->force_unarmed;
 }
References martialart::force_unarmed, and style_selected.
selected_has_weapon()
bool character_martial_arts::selected_has_weapon (const itype_id & weap) const
Definition at line 45 of file character_martial_arts.cpp.
 {
     return style_selected->has_weapon( weap );
 }
References martialart::has_weapon(), and style_selected.
selected_is_none()
bool character_martial_arts::selected_is_none () const
Definition at line 65 of file character_martial_arts.cpp.
 {
     return style_selected == style_none;
 }
References style_none, and style_selected.
selected_prevent_weapon_blocking()
bool character_martial_arts::selected_prevent_weapon_blocking () const
Definition at line 55 of file character_martial_arts.cpp.
 {
     return style_selected->prevent_weapon_blocking;
 }
References martialart::prevent_weapon_blocking, and style_selected.
selected_strictly_melee()
bool character_martial_arts::selected_strictly_melee () const
Definition at line 40 of file character_martial_arts.cpp.
 {
     return style_selected->strictly_melee;
 }
References martialart::strictly_melee, and style_selected.
selected_style()
const matype_id& character_martial_arts::selected_style () const inline
Definition at line 112 of file character_martial_arts.h.
{
             return style_selected;
         }
References style_selected.
selected_style_check()
void character_martial_arts::selected_style_check ()
Definition at line 120 of file character_martial_arts.cpp.
 {
     // check if player knows current style naturally, otherwise drop them back to style_none
     if( style_selected != style_none && style_selected != style_kicks ) {
         bool has_style = false;
         for( const matype_id &elem : ma_styles ) {
             if( elem == style_selected ) {
                 has_style = true;
             }
         }
         if( !has_style ) {
             reset_style();
         }
     }
 }
References ma_styles, reset_style(), style_kicks, style_none, and style_selected.
Referenced by clear_style().
selected_style_name()
std::string character_martial_arts::selected_style_name (const Character & owner) const
Definition at line 144 of file character_martial_arts.cpp.
 {
     if( style_selected->force_unarmed || style_selected->weapon_valid( owner.get_wielded_item() ) ) {
         return style_selected->name.translated();
     } else if( owner.is_armed() ) {
         return _( "Normal" );
     } else {
         return _( "No Style" );
     }
 }
References _, martialart::force_unarmed, Character::get_wielded_item(), Character::is_armed(), martialart::name, style_selected, translation::translated(), and martialart::weapon_valid().
serialize()
void character_martial_arts::serialize (JsonOut & json) const
Definition at line 181 of file character_martial_arts.cpp.
 {
     json.start_object();
     json.member( "ma_styles", ma_styles );
     json.member( "keep_hands_free", keep_hands_free );
     json.member( "style_selected", style_selected );
     json.end_object();
 }
References JsonOut::end_object(), keep_hands_free, ma_styles, JsonOut::member(), JsonOut::start_object(), and style_selected.
set_style()
void character_martial_arts::set_style (const matype_id & mastyle, bool force = false)
Definition at line 91 of file character_martial_arts.cpp.
 {
     if( force || has_martialart( mastyle ) ) {
         style_selected = mastyle;
     }
 }
References force, has_martialart(), and style_selected.
Member Data Documentation
keep_hands_free
bool character_martial_arts::keep_hands_free = false
Definition at line 35 of file character_martial_arts.h.
Referenced by character_martial_arts(), clear_styles(), deserialize(), pick_style(), and serialize().
ma_styles
std::vector<matype_id> character_martial_arts::ma_styles private
Definition at line 20 of file character_martial_arts.h.
Referenced by add_martialart(), character_martial_arts(), clear_style(), clear_styles(), deserialize(), enumerate_known_styles(), get_known_styles(), get_unknown_styles(), has_martialart(), pick_style(), selected_style_check(), and serialize().
style_selected
matype_id character_martial_arts::style_selected = matype_id("style_none") private
Definition at line 21 of file character_martial_arts.h.
Referenced by can_arm_block(), can_leg_block(), can_nonstandard_block(), can_use_attack_vector(), can_weapon_block(), character_martial_arts(), clear_all_effects(), deserialize(), get_all_techniques(), has_technique(), is_force_unarmed(), knows_selected_style(), learn_current_style_CQB(), ma_onattack_effects(), ma_onblock_effects(), ma_oncrit_effects(), ma_ondodge_effects(), ma_ongethit_effects(), ma_onhit_effects(), ma_onkill_effects(), ma_onmiss_effects(), ma_onmove_effects(), ma_onpause_effects(), ma_static_effects(), martialart_use_message(), pick_style(), reset_style(), selected_allow_all_weapons(), selected_force_unarmed(), selected_has_weapon(), selected_is_none(), selected_prevent_weapon_blocking(), selected_strictly_melee(), selected_style(), selected_style_check(), selected_style_name(), serialize(), and set_style().
The documentation for this class was generated from the following files:
src/character_martial_arts.h
src/character.cpp
src/character_martial_arts.cpp
src/martialarts.cpp
src/melee.cpp