Cataclysm DDA: Creature Class Reference
Creature Class Reference abstract
#include <creature.h>
Public Types
enum class Attitude : int { HOSTILE , NEUTRAL , FRIENDLY , ANY }
Simplified attitude towards any creature: hostile - hate, want to kill, etc.
Public Member Functions
~Creature () override
virtual std::string get_name () const =0
virtual std::string disp_name (bool possessive=false, bool capitalize_first=false) const =0
virtual std::string skin_name () const =0
virtual std::vector< std::string > get_grammatical_genders () const
virtual bool is_avatar () const
virtual bool is_npc () const
virtual bool is_monster () const
virtual Character * as_character ()
virtual const Character * as_character () const
virtual avatar * as_avatar ()
virtual const avatar * as_avatar () const
virtual npc * as_npc ()
virtual const npc * as_npc () const
virtual monster * as_monster ()
virtual const monster * as_monster () const
virtual mfaction_id get_monster_faction () const =0
virtual void witness_thievery (item *it)=0
virtual bool is_fake () const
Returns true for non-real Creatures used temporarily; i.e.
virtual void set_fake (bool fake_value)
Sets a Creature's fake boolean.
tripoint pos () const
tripoint_bub_ms pos_bub () const
int posx () const
int posy () const
int posz () const
void setpos (const tripoint &p)
void move_to (const tripoint_abs_ms &loc)
Moves the creature to the given location and calls the on_move() handler.
virtual void normalize ()
Recreates the Creature from scratch.
virtual void process_turn ()
Processes effects and bonuses and allocates move points based on speed.
virtual void reset_bonuses ()
Resets the value of all bonus fields to 0.
virtual void reset_stats ()=0
Resets stats, and applies effects in an idempotent manner.
virtual void reset ()
Handles stat and bonus reset.
virtual void bleed () const
Adds an appropriate blood splatter.
virtual void die (Creature *killer)=0
Empty function.
virtual float hit_roll () const =0
Should always be overwritten by the appropriate player/NPC/monster version.
virtual float dodge_roll () const =0
virtual float stability_roll () const =0
virtual bool can_attack_high () const =0
virtual Attitude attitude_to (const Creature &other) const =0
Attitude (of this creature) towards another creature.
virtual bool avoid_trap (const tripoint &pos, const trap &tr) const =0
Called when a creature triggers a trap, returns true if they don't set it off.
bool sees (const Creature &critter) const override
The functions check whether this creature can see the target.
bool sees (const tripoint &t, bool is_avatar=false, int range_mod=0) const override
bool sees (const tripoint_bub_ms &t, bool is_avatar=false, int range_mod=0) const override
virtual int sight_range (float light_level) const =0
How far the creature sees under the given light.
virtual float power_rating () const =0
Returns an approximation of the creature's strength.
virtual float speed_rating () const =0
Returns an approximate number of tiles this creature can travel per turn.
Creature * auto_find_hostile_target (int range, int &boo_hoo, int area=0)
For fake-players (turrets, mounted turrets) this functions chooses a target.
double ranged_target_size () const
Size of the target this creature presents to ranged weapons.
virtual bool block_hit (Creature *source, bodypart_id &bp_hit, damage_instance &dam)=0
virtual const weakpoint * absorb_hit (const weakpoint_attack &attack, const bodypart_id &bp, damage_instance &dam)=0
void knock_back_from (const tripoint &p)
virtual void knock_back_to (const tripoint &to)=0
float get_crit_factor (const bodypart_id &bp) const
int size_melee_penalty () const
virtual int deal_melee_attack (Creature *source, int hitroll)
bool is_adjacent (const Creature *target, bool allow_z_levels) const
virtual damage_instance modify_damage_dealt_with_enchantments (const damage_instance &dam) const
virtual void deal_melee_hit (Creature *source, int hit_spread, bool critical_hit, damage_instance dam, dealt_damage_instance &dealt_dam, const weakpoint_attack &attack=weakpoint_attack(), const bodypart_id *bp=nullptr)
virtual void deal_projectile_attack (Creature *source, dealt_projectile_attack &attack, bool print_messages=true, const weakpoint_attack &wp_attack=weakpoint_attack())
Attempts to harm a creature with a projectile.
virtual dealt_damage_instance deal_damage (Creature *source, bodypart_id bp, const damage_instance &dam, const weakpoint_attack &attack=weakpoint_attack())
Deals the damage via an attack.
virtual void deal_damage_handle_type (const effect_source &source, const damage_unit &du, bodypart_id bp, int &damage, int &pain)
virtual void apply_damage (Creature *source, bodypart_id bp, int amount, bool bypass_med=false)=0
virtual void heal_bp (bodypart_id bp, int dam)
void longpull (const std::string &name, const tripoint &p)
Attempts to pull the target at point p towards this creature.
bool dodge_check (float hit_roll, bool force_try=false, float training_level=0.0f)
If training_level is anything but 0, the check will only train target's skill to that level.
bool dodge_check (monster *z, float training_level=0.0f)
bool dodge_check (monster *z, bodypart_id bp, const damage_instance &dam_inst, float training_level=0.0f)
bool stumble_invis (const Creature &player, bool stumblemsg=true)
bool attack_air (const tripoint &p)
virtual void on_dodge (Creature *source, float difficulty, float training_level=0.0f)=0
This creature just dodged an attack - possibly special/ranged attack - from source.
virtual void on_try_dodge ()=0
Invoked when the creature attempts to dodge, regardless of success or failure.
virtual void on_hit (Creature *source, bodypart_id bp_hit, float difficulty=INT_MIN, dealt_projectile_attack const *proj=nullptr)=0
This creature just got hit by an attack - possibly special/ranged attack - from source.
virtual bool is_ranged_attacker () const
Returns true if this monster has a gun-type attack or the RANGED_ATTACKER flag.
virtual bool digging () const
virtual bool is_on_ground () const =0
bool cant_do_underwater (bool msg=true) const
virtual bool is_underwater () const
bool is_likely_underwater () const
virtual bool is_warm () const
virtual bool in_species (const species_id &) const
virtual bool has_weapon () const =0
virtual bool is_hallucination () const =0
virtual bool is_electrical () const =0
virtual bool is_fae () const =0
virtual bool is_nether () const =0
virtual bool has_mind () const =0
virtual bool is_dead_state () const =0
virtual bool is_elec_immune () const =0
virtual bool is_immune_effect (const efftype_id &type) const =0
virtual bool is_immune_damage (const damage_type_id &type) const =0
bool is_dangerous_fields (const field &fld) const
Returns true if there is a field in the field set that is dangerous to us.
bool is_dangerous_field (const field_entry &entry) const
Returns true if the given field entry is dangerous to us.
virtual bool is_immune_field (const field_type_id &) const
Returns true if we are immune to the field type with the given fid.
virtual bool check_immunity_data (const field_immunity_data &) const
virtual float fall_damage_mod () const =0
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
virtual int impact (int force, const tripoint &pos)=0
Deals falling/collision damage with terrain/creature at pos.
void check_dead_state ()
This function checks the creatures is_dead_state and (if true) calls die.
virtual bool move_effects (bool attacking)=0
Processes move stopping effects.
void add_effect (const effect &eff, bool force=false, bool deferred=false)
void add_effect (const efftype_id &eff_id, const time_duration &dur, bodypart_id bp, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void add_effect (const efftype_id &eff_id, const time_duration &dur, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void add_effect (const effect_source &source, const effect &eff, bool force=false, bool deferred=false)
void add_effect (const effect_source &source, const efftype_id &eff_id, const time_duration &dur, bodypart_id bp, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
Adds or modifies an effect.
void add_effect (const effect_source &source, const efftype_id &eff_id, const time_duration &dur, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void schedule_effect (const effect &eff, bool force=false, bool deferred=false)
Schedules a new effect to be applied.
void schedule_effect (const efftype_id &eff_id, const time_duration &dur, bodypart_id bp, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void schedule_effect (const efftype_id &eff_id, const time_duration &dur, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
bool add_env_effect (const efftype_id &eff_id, const bodypart_id &vector, int strength, const time_duration &dur, const bodypart_id &bp, bool permanent=false, int intensity=1, bool force=false)
Gives chance to save via environmental resist, returns false if resistance was successful.
bool add_env_effect (const efftype_id &eff_id, const bodypart_id &vector, int strength, const time_duration &dur, bool permanent=false, int intensity=1, bool force=false)
bool remove_effect (const efftype_id &eff_id, const bodypart_id &bp)
Removes a listed effect.
bool remove_effect (const efftype_id &eff_id)
void schedule_effect_removal (const efftype_id &eff_id, const bodypart_id &bp)
Schedule effect removal.
void schedule_effect_removal (const efftype_id &eff_id)
void clear_effects ()
Remove all effects.
bool has_effect (const efftype_id &eff_id, const bodypart_id &bp) const
Check if creature has the matching effect.
bool has_effect (const efftype_id &eff_id) const
bool has_effect_with_flag (const flag_id &flag, const bodypart_id &bp) const
Check if creature has any effect with the given flag.
bool has_effect_with_flag (const flag_id &flag) const
std::vector< std::reference_wrapper< const effect > > get_effects_with_flag (const flag_id &flag) const
std::vector< std::reference_wrapper< const effect > > get_effects_from_bp (const bodypart_id &bp) const
std::vector< std::reference_wrapper< const effect > > get_effects () const
const effect & get_effect (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Return the effect that matches the given arguments exactly.
effect & get_effect (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID())
time_duration get_effect_dur (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Returns the duration of the matching effect.
int get_effect_int (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Returns the intensity of the matching effect.
bool resists_effect (const effect &e) const
Returns true if the creature resists an effect.
void set_value (const std::string &key, const std::string &value)
void remove_value (const std::string &key)
std::string get_value (const std::string &key) const
std::optional< std::string > maybe_get_value (const std::string &key) const
void clear_values ()
virtual units::mass get_weight () const =0
virtual void process_effects ()
Processes through all the effects on the Creature.
virtual bool has_trait (const trait_id &flag) const
Returns true if the player has the entered trait, returns false for non-humans.
virtual void mod_pain (int npain)
virtual void mod_pain_noresist (int npain)
virtual void set_pain (int npain)
virtual int get_pain () const
virtual int get_perceived_pain () const
int get_moves () const
void mod_moves (int nmoves)
void set_moves (int nmoves)
virtual bool in_sleep_state () const
virtual Creature * get_killer () const
virtual int get_num_blocks () const
virtual int get_num_dodges () const
virtual int get_num_blocks_bonus () const
virtual int get_num_dodges_bonus () const
virtual int get_num_dodges_base () const
virtual int get_num_blocks_base () const
virtual int get_env_resist (bodypart_id bp) const
virtual int get_armor_res (const damage_type_id &dt, bodypart_id bp) const
virtual int get_armor_res_base (const damage_type_id &dt, bodypart_id bp) const
virtual int get_armor_res_bonus (const damage_type_id &dt) const
virtual int get_spell_resist () const
virtual int get_armor_type (const damage_type_id &dt, bodypart_id bp) const =0
virtual float get_dodge () const
virtual float get_melee () const =0
virtual float get_hit () const
virtual int get_speed () const
virtual int get_eff_per () const
virtual creature_size get_size () const =0
virtual int get_hp (const bodypart_id &bp) const
virtual int get_hp () const
virtual int get_hp_max (const bodypart_id &bp) const
virtual int get_hp_max () const
virtual int hp_percentage () const =0
virtual bool made_of (const material_id &m) const =0
virtual bool made_of_any (const std::set< material_id > &ms) const =0
virtual field_type_id bloodType () const =0
virtual field_type_id gibType () const =0
virtual bool has_flag (const mon_flag_id &) const
virtual bool uncanny_dodge ()
virtual bool check_avoid_friendly_fire () const
void set_reachable_zone (int zone)
int get_reachable_zone () const
anatomy_id get_anatomy () const
void set_anatomy (const anatomy_id &anat)
bodypart_id get_random_body_part (bool main=false) const
std::vector< bodypart_id > get_all_body_parts (get_body_part_flags=get_body_part_flags::none) const
Returns body parts this creature have.
std::vector< bodypart_id > get_all_body_parts_of_type (body_part_type::type part_type, get_body_part_flags flags=get_body_part_flags::none) const
bodypart_id get_random_body_part_of_type (body_part_type::type part_type) const
bodypart_id get_root_body_part () const
std::vector< bodypart_id > get_all_body_parts_with_flag (const json_character_flag &flag) const
body_part_set get_drenching_body_parts (bool upper=true, bool mid=true, bool lower=true) const
int get_num_body_parts_of_type (body_part_type::type part_type) const
int get_num_broken_body_parts_of_type (body_part_type::type part_type) const
const std::map< bodypart_str_id, bodypart > & get_body () const
void set_body ()
bool has_part (const bodypart_id &id, body_part_filter filter=body_part_filter::strict) const
bodypart * get_part (const bodypart_id &id)
const bodypart * get_part (const bodypart_id &id) const
bodypart_id get_part_id (const bodypart_id &id, body_part_filter filter=body_part_filter::next_best, bool suppress_debugmsg=false) const
int get_part_hp_cur (const bodypart_id &id) const
int get_part_hp_max (const bodypart_id &id) const
int get_part_healed_total (const bodypart_id &id) const
int get_part_damage_disinfected (const bodypart_id &id) const
int get_part_damage_bandaged (const bodypart_id &id) const
int get_part_drench_capacity (const bodypart_id &id) const
int get_part_wetness (const bodypart_id &id) const
units::temperature get_part_temp_cur (const bodypart_id &id) const
units::temperature get_part_temp_conv (const bodypart_id &id) const
int get_part_frostbite_timer (const bodypart_id &id) const
std::array< int, NUM_WATER_TOLERANCE > get_part_mut_drench (const bodypart_id &id) const
float get_part_wetness_percentage (const bodypart_id &id) const
const encumbrance_data & get_part_encumbrance_data (const bodypart_id &id) const
virtual void set_part_hp_cur (const bodypart_id &id, int set)
void set_part_hp_max (const bodypart_id &id, int set)
void set_part_healed_total (const bodypart_id &id, int set)
void set_part_damage_disinfected (const bodypart_id &id, int set)
void set_part_damage_bandaged (const bodypart_id &id, int set)
void set_part_encumbrance_data (const bodypart_id &id, const encumbrance_data &set)
void set_part_wetness (const bodypart_id &id, int set)
void set_part_temp_cur (const bodypart_id &id, units::temperature set)
void set_part_temp_conv (const bodypart_id &id, units::temperature set)
void set_part_frostbite_timer (const bodypart_id &id, int set)
void set_part_mut_drench (const bodypart_id &id, std::pair< water_tolerance, int > set)
virtual void mod_part_hp_cur (const bodypart_id &id, int mod)
void mod_part_hp_max (const bodypart_id &id, int mod)
void mod_part_healed_total (const bodypart_id &id, int mod)
void mod_part_damage_disinfected (const bodypart_id &id, int mod)
void mod_part_damage_bandaged (const bodypart_id &id, int mod)
void mod_part_wetness (const bodypart_id &id, int mod)
void mod_part_temp_cur (const bodypart_id &id, units::temperature_delta mod)
void mod_part_temp_conv (const bodypart_id &id, units::temperature_delta mod)
void mod_part_frostbite_timer (const bodypart_id &id, int mod)
void set_all_parts_temp_cur (units::temperature set)
void set_all_parts_temp_conv (units::temperature set)
void set_all_parts_wetness (int set)
void set_all_parts_hp_cur (int set)
void set_all_parts_hp_to_max ()
bool has_atleast_one_wet_part () const
bool is_part_at_max_hp (const bodypart_id &id) const
virtual int get_speed_base () const
virtual int get_speed_bonus () const
virtual int get_block_bonus () const
virtual int get_bash_bonus () const
virtual int get_cut_bonus () const
virtual float get_dodge_base () const =0
virtual float get_hit_base () const =0
virtual float get_dodge_bonus () const
virtual float get_hit_bonus () const
virtual float get_bash_mult () const
virtual float get_cut_mult () const
virtual bool get_melee_quiet () const
virtual bool has_grab_break_tec () const =0
virtual int get_throw_resist () const
virtual void mod_stat (const std::string &stat, float modifier)
virtual void set_num_blocks_bonus (int nblocks)
virtual void mod_num_blocks_bonus (int nblocks)
virtual void mod_num_dodges_bonus (int ndodges)
virtual void set_armor_res_bonus (int narm, const damage_type_id &dt)
virtual void set_speed_base (int nspeed)
virtual void set_speed_bonus (int nspeed)
virtual void set_block_bonus (int nblock)
virtual void set_bash_bonus (int nbash)
virtual void set_cut_bonus (int ncut)
virtual void mod_speed_bonus (int nspeed)
virtual void mod_block_bonus (int nblock)
virtual void mod_bash_bonus (int nbash)
virtual void mod_cut_bonus (int ncut)
virtual void mod_size_bonus (int nsize)
virtual void set_dodge_bonus (float ndodge)
virtual void set_hit_bonus (float nhit)
virtual void mod_dodge_bonus (float ndodge)
virtual void mod_hit_bonus (float nhit)
virtual void set_bash_mult (float nbashmult)
virtual void set_cut_mult (float ncutmult)
virtual void set_melee_quiet (bool nquiet)
virtual void set_throw_resist (int nthrowres)
virtual units::mass weight_capacity () const
virtual const pathfinding_settings & get_pathfinding_settings () const =0
Returns settings for pathfinding.
virtual std::unordered_set< tripoint > get_path_avoid () const =0
Returns a set of points we do not want to path through.
void draw (const catacurses::window &w, const point &origin, bool inverted) const
void draw (const catacurses::window &w, const tripoint &origin, bool inverted) const
virtual int print_info (const catacurses::window &w, int vStart, int vLines, int column) const =0
Write information about this creature.
void describe_infrared (std::vector< std::string > &buf) const
Describe this creature as seen by the avatar via infrared vision.
void describe_specials (std::vector< std::string > &buf) const
Describe this creature as detected by the avatar's special senses.
virtual void add_msg_if_player (const std::string &) const
virtual void add_msg_if_player (const game_message_params &, const std::string &) const
void add_msg_if_player (const translation &) const
void add_msg_if_player (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_player (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const translation &msg, Args &&... args) const
virtual void add_msg_if_npc (const std::string &) const
virtual void add_msg_if_npc (const game_message_params &, const std::string &) const
void add_msg_if_npc (const translation &) const
void add_msg_if_npc (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_npc (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const translation &msg, Args &&... args) const
virtual void add_msg_player_or_npc (const std::string &, const std::string &) const
virtual void add_msg_player_or_npc (const game_message_params &, const std::string &, const std::string &) const
void add_msg_player_or_npc (const translation &, const translation &) const
void add_msg_player_or_npc (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const translation &player_msg, const translation &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const translation &player_msg, const translation &npc_msg, Args &&... args) const
virtual void add_msg_player_or_say (const std::string &, const std::string &) const
virtual void add_msg_player_or_say (const game_message_params &, const std::string &, const std::string &) const
void add_msg_player_or_say (const translation &, const translation &) const
void add_msg_player_or_say (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_say (const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const translation &player_msg, const translation &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const translation &player_msg, const translation &npc_speech, Args &&... args) const
virtual std::string extended_description () const =0
virtual nc_color symbol_color () const =0
Creature symbol background color.
virtual nc_color basic_symbol_color () const =0
Creature symbol color.
virtual const std::string & symbol () const =0
Creature symbol.
virtual bool is_symbol_highlighted () const
std::unordered_map< std::string, std::string > & get_values ()
void clear_killer ()
void set_summon_time (const time_duration &length)
void decrement_summon_timer ()
void set_summoner (Creature *summoner)
void set_summoner (character_id summoner)
Creature * get_summoner () const
bodypart_id get_max_hitsize_bodypart () const
bodypart_id select_body_part (int min_hit, int max_hit, bool can_attack_high, int hit_roll) const
bodypart_id select_blocking_part (bool arm, bool leg, bool nonstandard) const
bodypart_id random_body_part (bool main_parts_only=false) const
std::vector< bodypart_id > get_all_eligable_parts (int min_hit, int max_hit, bool can_attack_high) const
void add_damage_over_time (const damage_over_time_data &DoT)
void process_damage_over_time ()
std::string replace_with_npc_name (std::string input) const
This function replaces the "<npcname>" substring with the disp_name of this creature.
tripoint_abs_ms get_location () const
Returns the location of the creature in map square coordinates (the most detailed coordinate system), relative to a fixed global point of origin.
tripoint_abs_sm global_sm_location () const
Returns the location of the creature in global submap coordinates.
tripoint_abs_omt global_omt_location () const
Returns the location of the creature in global overmap terrain coordinates.
Public Member Functions inherited from viewer
virtual ~viewer ()=default
Static Public Member Functions
static std::string attitude_raw_string (Attitude att)
Simplified attitude string for unlocalized needs.
static const std::pair< translation, nc_color > & get_attitude_ui_data (Attitude att)
Creature Attitude as String and color.
static void load_hit_range (const JsonObject &)
Public Attributes
FacingDirection facing = FacingDirection::RIGHT
return the direction the creature is facing, for sdl horizontal flip
bool underwater
int archery_aim_counter = 0
Static Public Attributes
static const std::map< std::string, creature_size > size_map
static const std::set< material_id > cmat_flesh
static const std::set< material_id > cmat_fleshnveg
static const std::set< material_id > cmat_flammable
static const std::set< material_id > cmat_flameres
static std::vector< int > dispersion_for_even_chance_of_good_hit
Protected Member Functions
void set_pos_only (const tripoint &p)
void set_location (const tripoint_abs_ms &loc)
virtual void on_move (const tripoint_abs_ms &old_pos)
void set_killer (Creature *killer)
virtual void process_one_effect (effect &e, bool is_new)=0
Processes one effect on the Creature.
Creature ()
Creature (const Creature &)
Creature (Creature &&) noexcept(map_is_noexcept)
Creature & operator= (const Creature &)
Creature & operator= (Creature &&) noexcept
virtual void on_stat_change (const std::string &, int)
virtual void on_effect_int_change (const efftype_id &, int, const bodypart_id &)
virtual void on_damage_of_type (const effect_source &, int, const damage_type_id &, const bodypart_id &)
void store (JsonOut &jsout) const
These two functions are responsible for storing and loading the members of this class to/from json data.
void load (const JsonObject &jsin)
Protected Attributes
anatomy_id creature_anatomy = anatomy_id("default_anatomy")
anatomy is the plan of the creature's body
std::map< bodypart_str_id, bodypart > body
this is the actual body of the creature
int moves
Creature * killer
std::optional< time_point > lifespan_end = std::nullopt
std::optional< character_id > summoner = std::nullopt
pimpl< effects_map > effects
std::queue< scheduled_effect, std::list< scheduled_effect > > scheduled_effects
std::queue< terminating_effect, std::list< terminating_effect > > terminating_effects
std::vector< damage_over_time_data > damage_over_time_map
std::unordered_map< std::string, std::string > values
int num_blocks = 0
int num_dodges = 0
int num_blocks_bonus = 0
int num_dodges_bonus = 0
std::map< damage_type_id, float > armor_bonus
int speed_base = 0
int speed_bonus = 0
float dodge_bonus = 0.0f
int block_bonus = 0
float hit_bonus = 0.0f
int bash_bonus = 0
int cut_bonus = 0
int size_bonus = 0
float bash_mult = 0.0f
float cut_mult = 0.0f
bool melee_quiet = false
int throw_resist = 0
time_point last_updated
bool fake = false
Private Member Functions
double accuracy_projectile_attack (dealt_projectile_attack &attack) const
projectile_attack_results select_body_part_projectile_attack (const projectile &proj, double goodhit, double missed_by) const
void messaging_projectile_attack (const Creature *source, const projectile_attack_results &hit_selection, int total_damage) const
Private Attributes
int reachable_zone = 0
This number establishes a partition of zones on the map that have shared reachability/visibility.
tripoint_abs_ms location
The creature's position in absolute coordinates.
int pain
Detailed Description
Definition at line 250 of file creature.h.
Member Enumeration Documentation
Attitude
enum Creature::Attitude : int strong
Simplified attitude towards any creature: hostile - hate, want to kill, etc.
neutral - anything between. friendly - avoid harming it, maybe even help. any - any of the above, used in safemode_ui
Enumerator
HOSTILE
NEUTRAL
FRIENDLY
ANY
Definition at line 352 of file creature.h.
                             : int {
             HOSTILE,
             NEUTRAL,
             FRIENDLY,
             ANY
         };
Constructor & Destructor Documentation
~Creature()
Creature::~Creature () override default
Creature() [1/3]
Creature::Creature () protected
Definition at line 157 of file creature.cpp.
 {
     moves = 0;
     pain = 0;
     killer = nullptr;
     speed_base = 100;
     underwater = false;
     location = tripoint_abs_ms( 20, 10, -500 ); // Some arbitrary position that will cause debugmsgs
     Creature::reset_bonuses();
     fake = false;
 }
References fake, killer, location, moves, pain, reset_bonuses(), speed_base, and underwater.
Creature() [2/3]
Creature::Creature (const Creature &) protected default
Creature() [3/3]
Creature::Creature (Creature &&) protected default noexcept
Member Function Documentation
absorb_hit()
virtual const weakpoint* Creature::absorb_hit (const weakpoint_attack & attack, const bodypart_id & bp, damage_instance & dam) pure virtual
Implemented in monster, and Character.
Referenced by deal_damage().
accuracy_projectile_attack()
double Creature::accuracy_projectile_attack (dealt_projectile_attack & attack) const private
Definition at line 835 of file creature.cpp.
 {
     const int avoid_roll = dodge_roll();
     // Do dice(10, speed) instead of dice(speed, 10) because speed could potentially be > 10000
     const int diff_roll = dice( 10, attack.proj.speed );
     // Partial dodge, capped at [0.0, 1.0], added to missed_by
     const double dodge_rescaled = avoid_roll / static_cast<double>( diff_roll );
     return attack.missed_by + std::max( 0.0, std::min( 1.0, dodge_rescaled ) );
 }
References spell_effect::attack(), dice(), dodge_roll(), max(), and min().
Referenced by Character::add_msg_player_or_say().
add_damage_over_time()
void Creature::add_damage_over_time (const damage_over_time_data & DoT)
Definition at line 3042 of file creature.cpp.
 {
     damage_over_time_map.emplace_back( DoT );
 }
References damage_over_time_map.
Referenced by damage_targets(), and consume_drug_iuse::use().
add_effect() [1/6]
void Creature::add_effect (const effect & eff, bool force = false, bool deferred = false) inline
Definition at line 604 of file creature.h.
{
             add_effect( effect_source::empty(), eff, force, deferred );
         }
References deferred, effect_source::empty(), and force.
Referenced by outfit::absorb_damage(), npc::act_on_danger_assessment(), enchant_cache::activate_passive(), anonymous_namespace{monexamine.cpp}::add_armor(), add_effect(), talker_character::add_effect(), talker_monster::add_effect(), add_effect_to_target(), add_env_effect(), monster::add_grab(), anonymous_namespace{monexamine.cpp}::add_leash(), npc::address_player(), iuse::adrenaline_injector(), alcohol(), iuse::antibiotic(), iuse::anticonvulsant(), iuse::antifungal(), map::apply_character_light(), projectile::apply_effects_damage(), projectile::apply_effects_nodamage(), weakpoint_effect::apply_to(), apply_weariness(), npc::assess_danger(), anonymous_namespace{monexamine.cpp}::attach_bag_to(), anonymous_namespace{monexamine.cpp}::attach_saddle_to(), iexamine::autodoc(), trapfunc::beartrap(), mattack::bio_op_impale(), mattack::bio_op_takedown(), iuse::blech(), debug_menu::bleed_self(), blobify(), trapfunc::board(), talker_avatar::buy_monster(), Character::calc_discomfort(), leap_actor::call(), melee_actor::call(), trapfunc::caltrops(), Character::check_needs_extremes(), iuse::coke(), Character::cough(), map::creature_in_field(), map::crush(), mattack::darkman(), iuse::datura(), Character::deal_damage(), deal_damage_handle_type(), monster::deal_projectile_attack(), talk_function::deny_equipment(), talk_function::deny_follow(), talk_function::deny_lead(), talk_function::deny_personal_info(), talk_function::deny_train(), mattack::dermatik(), monster::digest_food(), iuse::directional_hologram(), Character::dismount(), melee_actor::do_grab(), disable_activity_actor::do_turn(), glide_activity_actor::do_turn(), eat(), iuse::ecig(), explosion_handler::emp_blast(), npc::execute_action(), Character::expose_to_disease(), iuse::extinguisher(), computer_session::failure_amigara(), Character::fall_asleep(), activity_handlers::find_mount_do_turn(), shearing_activity_actor::finish(), disable_activity_actor::finish(), heal_actor::finish_using(), mattack::flame(), explosion_handler::flashbang(), mattack::flesh_golem(), iexamine::flower_marloss(), iexamine::flower_poppy(), iuse::flu_vaccine(), iuse::flumed(), iuse::flusleep(), Character::forced_dismount(), mattack::formblob(), mattack::frag(), suffer::from_artifact_resonance(), suffer::from_asthma(), suffer::from_nyctophobia(), suffer::from_other_mutations(), suffer::from_stimulants(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), talk_function::give_aid(), talk_function::give_all_aid(), talk_function::give_equipment_allowance(), anonymous_namespace{monexamine.cpp}::give_items_to(), glare(), glide_activity_actor::glide_activity_actor(), start_location::handle_heli_crash(), handle_remove_fd_reality_tear_field(), Character::heat_emission(), Character::impact(), monster::impact(), iuse::inhaler(), Character::install_bionics(), Character::introduce_into_anesthesia(), iuse::jet_injector(), mattack::kamikaze(), Character::knock_back_to(), monster::knock_back_to(), game::knockback(), iexamine::ledge(), talk_function::lesser_give_aid(), talk_function::lesser_give_all_aid(), mattack::lunge(), iuse::mace(), monster::make_bleed(), monexamine::mech_hack(), iuse::melatonin_tablet(), monster::melee_attack(), Character::melee_attack_abstract(), Character::mend(), iuse::meth(), anonymous_namespace{monexamine.cpp}::milk_source(), Character::mod_power_level(), Character::mod_speed_bonus(), Character::mod_stamina(), Character::modify_stimulation(), game::mon_info_update(), monster::monster(), map::monster_in_field(), monster::monster_move_in_vehicle(), talk_function::morale_chat_activity(), Character::mount_creature(), monster::move_to(), npc::move_to(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), melee_actor::on_damage(), bite_actor::on_damage(), Character::on_damage_of_type(), Character::on_hit(), Character::on_hurt(), npc::on_load(), game::on_move_effects(), activity_handlers::operation_do_turn(), mattack::para_sting(), vehicle::part_collision(), Character::pause(), monexamine::pay_bot(), Character::perform_technique(), mattack::photograph(), trapfunc::pit_glass(), trapfunc::pit_spikes(), teleporter_list::place_avatar_overmap(), game::place_player(), iuse::play_music(), map::player_in_field(), iuse::poison(), turret_data::prepare_fire(), Character::process_effects(), monster::process_effects(), item::process_litcig(), sounds::process_sound_markers(), monster::process_turn(), projectile_attack(), iuse::prozac(), monster::push_to(), mattack::ratking(), npc::reboot(), monster::remove_grab(), avatar::reset_stats(), explosion_handler::resonance_cascade(), mattack::resurrect(), game::revive_corpse(), mattack::rifle(), npc::set_attitude(), anonymous_namespace{monexamine.cpp}::shear_animal(), mattack::shriek_alert(), mattack::shriek_stun(), sleep(), map::spawn_monsters_submap(), disable_activity_actor::start(), anonymous_namespace{monexamine.cpp}::start_leading(), talk_function::start_training_gen(), iuse::stimpack(), iuse::strong_antibiotic(), stumble_invis(), Character::suffer(), anonymous_namespace{monexamine.cpp}::swap(), mattack::tankgun(), teleport::teleport_to_point(), iuse::thorazine(), anonymous_namespace{monexamine.cpp}::tie_pet(), activity_handlers::tree_communion_do_turn(), gun_actor::try_target(), Character::uninstall_bionic(), anonymous_namespace{monexamine.cpp}::untie_pet(), Character::update_body_wetness(), Character::update_bodytemp(), Character::update_frostbite(), Character::update_stomach(), Character::update_vitamins(), consume_drug_iuse::use(), place_monster_iuse::use(), change_scent_iuse::use(), musical_instrument_actor::use(), vehicle::use_harness(), game::validate_mounted_npcs(), Character::vomit(), wait(), iuse::weak_antibiotic(), iuse::weed_cake(), suffer::while_awake(), debug_menu::wisheffect(), debug_menu::wishmonster(), suffer::without_sleep(), iuse::xanax(), and mattack::zombie_fuse().
add_effect() [2/6]
void Creature::add_effect (const effect_source & source, const effect & eff, bool force = false, bool deferred = false)
Definition at line 1528 of file creature.cpp.
 {
     add_effect( source, eff.get_id(), eff.get_duration(), eff.get_bp(), eff.is_permanent(),
                 eff.get_intensity(), force, deferred );
 }
References add_effect(), deferred, force, effect::get_bp(), effect::get_duration(), effect::get_id(), effect::get_intensity(), and effect::is_permanent().
add_effect() [3/6]
void Creature::add_effect (const effect_source & source, const efftype_id & eff_id, const time_duration & dur, bodypart_id bp, bool permanent = false, int intensity = 0, bool force = false, bool deferred = false)
Adds or modifies an effect.
If intensity is given it will set the effect intensity to the given value, or as close as max_intensity values permit.
Definition at line 1535 of file creature.cpp.
 {
     // Check our innate immunity
     if( !force && is_immune_effect( eff_id ) ) {
         return;
     }
     if( eff_id == effect_knockdown && ( has_effect( effect_ridden ) ||
                                         has_effect( effect_riding ) ) ) {
         monster *mons = dynamic_cast<monster *>( this );
         if( mons && mons->mounted_player ) {
             mons->mounted_player->forced_dismount();
         }
     }
     if( !eff_id.is_valid() ) {
         debugmsg( "Invalid effect, ID: %s", eff_id.c_str() );
         return;
     }
     const effect_type &type = eff_id.obj();
     // Mutate to a main (HP'd) body_part if necessary.
     if( type.get_main_parts() ) {
         bp = bp->main_part;
     }
     // Filter out bodypart immunity
     for( json_character_flag flag : eff_id->immune_bp_flags ) {
         if( bp->has_flag( flag ) ) {
             return;
         }
     }
     // Then check if the effect is blocked by another
     for( auto &elem : *effects ) {
         for( auto &_effect_it : elem.second ) {
             for( const auto &blocked_effect : _effect_it.second.get_blocks_effects() ) {
                 if( blocked_effect == eff_id ) {
                     // The effect is blocked by another, return
                     return;
                 }
             }
         }
     }
     bool found = false;
     // Check if we already have it
     auto matching_map = effects->find( eff_id );
     if( matching_map != effects->end() ) {
         auto &bodyparts = matching_map->second;
         auto found_effect = bodyparts.find( bp );
         if( found_effect != bodyparts.end() ) {
             found = true;
             effect &e = found_effect->second;
             const int prev_int = e.get_intensity();
             // If we do, mod the duration, factoring in the mod value
             e.mod_duration( dur * e.get_dur_add_perc() / 100 );
             // Limit to max duration
             if( e.get_duration() > e.get_max_duration() ) {
                 e.set_duration( e.get_max_duration() );
             }
             // Adding a permanent effect makes it permanent
             if( e.is_permanent() ) {
                 e.pause_effect();
             }
             // int_dur_factor overrides all other intensity settings
             // ...but it's handled in set_duration, so explicitly do nothing here
             if( e.get_int_dur_factor() > 0_turns ) {
                 // Set intensity if value is given
             } else if( intensity > 0 ) {
                 e.set_intensity( intensity, is_avatar() );
                 // Else intensity uses the type'd step size if it already exists
             } else if( e.get_int_add_val() != 0 ) {
                 e.mod_intensity( e.get_int_add_val(), is_avatar() );
             }
             // Bound intensity by [1, max intensity]
             if( e.get_intensity() < 1 ) {
                 add_msg_debug( debugmode::DF_CREATURE, "Bad intensity, ID: %s", e.get_id().c_str() );
                 e.set_intensity( 1 );
             } else if( e.get_intensity() > e.get_max_intensity() ) {
                 e.set_intensity( e.get_max_intensity() );
             }
             if( e.get_intensity() != prev_int ) {
                 on_effect_int_change( eff_id, e.get_intensity(), bp );
             }
         }
     }
     if( !found ) {
         // If we don't already have it then add a new one
         // Now we can make the new effect for application
         effect e( effect_source( source ), &type, dur, bp.id(), permanent, intensity, calendar::turn );
         // Bound to max duration
         if( e.get_duration() > e.get_max_duration() ) {
             e.set_duration( e.get_max_duration() );
         }
         // Force intensity if it is duration based
         if( e.get_int_dur_factor() != 0_turns ) {
             // + 1 here so that the lowest is intensity 1, not 0
             e.set_intensity( e.get_duration() / e.get_int_dur_factor() + 1 );
         }
         // Bound new effect intensity by [1, max intensity]
         if( e.get_intensity() < 1 ) {
             add_msg_debug( debugmode::DF_CREATURE, "Bad intensity, ID: %s", e.get_id().c_str() );
             e.set_intensity( 1 );
         } else if( e.get_intensity() > e.get_max_intensity() ) {
             e.set_intensity( e.get_max_intensity() );
         }
         ( *effects )[eff_id][bp] = e;
         if( Character *ch = as_character() ) {
             get_event_bus().send<event_type::character_gains_effect>( ch->getID(), bp.id(), eff_id );
             if( is_avatar() ) {
                 eff_id->add_apply_msg( e.get_intensity() );
             }
         }
         on_effect_int_change( eff_id, e.get_intensity(), bp );
         // Perform any effect addition effects.
         // only when not deferred
         if( !deferred ) {
             process_one_effect( e, true );
         }
     }
 }
References effect_type::add_apply_msg(), add_msg_debug, as_character(), bp, string_id< T >::c_str(), character_gains_effect, debugmsg, deferred, debugmode::DF_CREATURE, dur, effect_knockdown, effect_ridden, effect_riding, effects, force, Character::forced_dismount(), effect::get_dur_add_perc(), effect::get_duration(), get_event_bus(), effect::get_id(), effect::get_int_add_val(), effect::get_int_dur_factor(), effect::get_intensity(), effect::get_max_duration(), effect::get_max_intensity(), has_effect(), body_part_type::has_flag(), int_id< T >::id(), effect_type::immune_bp_flags, intensity, is_avatar(), is_immune_effect(), effect::is_permanent(), string_id< T >::is_valid(), body_part_type::main_part, effect::mod_duration(), effect::mod_intensity(), monster::mounted_player, string_id< T >::obj(), on_effect_int_change(), effect::pause_effect(), permanent, process_one_effect(), event_bus::send(), effect::set_duration(), effect::set_intensity(), calendar::turn, and type.
add_effect() [4/6]
void Creature::add_effect (const effect_source & source, const efftype_id & eff_id, const time_duration & dur, bool permanent = false, int intensity = 0, bool force = false, bool deferred = false)
Definition at line 1661 of file creature.cpp.
 {
     add_effect( source, eff_id, dur, bodypart_str_id::NULL_ID(), permanent, intensity, force,
                 deferred );
 }
References add_effect(), deferred, dur, force, intensity, string_id< body_part_type >::NULL_ID(), and permanent.
add_effect() [5/6]
void Creature::add_effect (const efftype_id & eff_id, const time_duration & dur, bodypart_id bp, bool permanent = false, int intensity = 0, bool force = false, bool deferred = false) inline
Definition at line 607 of file creature.h.
{
             add_effect( effect_source::empty(), eff_id, dur, bp, permanent, intensity, force, deferred );
         }
References add_effect(), bp, deferred, dur, effect_source::empty(), force, intensity, and permanent.
add_effect() [6/6]
void Creature::add_effect (const efftype_id & eff_id, const time_duration & dur, bool permanent = false, int intensity = 0, bool force = false, bool deferred = false) inline
Definition at line 611 of file creature.h.
{
             add_effect( effect_source::empty(), eff_id, dur, permanent, intensity, force, deferred );
         }
References add_effect(), deferred, dur, effect_source::empty(), force, intensity, and permanent.
add_env_effect() [1/2]
bool Creature::add_env_effect (const efftype_id & eff_id, const bodypart_id & vector, int strength, const time_duration & dur, bool permanent = false, int intensity = 1, bool force = false)
Definition at line 1705 of file creature.cpp.
 {
     return add_env_effect( eff_id, vector, strength, dur, bodypart_str_id::NULL_ID(), permanent,
                            intensity, force );
 }
References add_env_effect(), dur, force, intensity, string_id< body_part_type >::NULL_ID(), permanent, and strength.
add_env_effect() [2/2]
bool Creature::add_env_effect (const efftype_id & eff_id, const bodypart_id & vector, int strength, const time_duration & dur, const bodypart_id & bp, bool permanent = false, int intensity = 1, bool force = false)
Gives chance to save via environmental resist, returns false if resistance was successful.
Definition at line 1689 of file creature.cpp.
 {
     if( !force && is_immune_effect( eff_id ) ) {
         return false;
     }
     if( dice( strength, 3 ) > dice( get_env_resist( vector ), 3 ) ) {
         // Only add the effect if we fail the resist roll
         // Don't check immunity (force == true), because we did check above
         add_effect( effect_source::empty(), eff_id, dur, bp, permanent, intensity, true );
         return true;
     } else {
         return false;
     }
 }
References add_effect(), bp, dice(), dur, effect_source::empty(), force, get_env_resist(), intensity, is_immune_effect(), permanent, and strength.
Referenced by mattack::acid_barf(), add_env_effect(), mattack::boomer(), mattack::boomer_glow(), map::burn_body_part(), map::creature_in_field(), explosion_handler::flashbang(), fungal_effects::fungalize(), trapfunc::goo(), and map::player_in_field().
add_msg_if_npc() [1/10]
template<typename ... Args> void Creature::add_msg_if_npc (const char *const msg, Args &&... args) const inline
Definition at line 1024 of file creature.h.
{
             return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_npc(), and string_format().
add_msg_if_npc() [2/10]
virtual void Creature::add_msg_if_npc (const game_message_params & , const std::string &) const inline virtual
Reimplemented in npc, and monster.
Definition at line 1019 of file creature.h.
                                                                 {}
add_msg_if_npc() [3/10]
void Creature::add_msg_if_npc (const game_message_params & params, const translation & msg) const
Definition at line 3155 of file creature.cpp.
 {
     return add_msg_if_npc( params, msg.translated() );
 }
References add_msg_if_npc(), and translation::translated().
add_msg_if_npc() [4/10]
template<typename ... Args> void Creature::add_msg_if_npc (const game_message_params & params, const char *const msg, Args &&... args) const inline
Definition at line 1036 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_npc() [5/10]
template<typename ... Args> void Creature::add_msg_if_npc (const game_message_params & params, const std::string & msg, Args &&... args) const inline
Definition at line 1044 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_npc() [6/10]
template<typename ... Args> void Creature::add_msg_if_npc (const game_message_params & params, const translation & msg, Args &&... args) const inline
Definition at line 1052 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_npc() [7/10]
virtual void Creature::add_msg_if_npc (const std::string &) const inline virtual
Reimplemented in npc, and monster.
Definition at line 1018 of file creature.h.
 {}
Referenced by add_msg_if_npc(), Character::can_continue_craft(), Character::deactivate_bionic(), basecamp::feed_workers(), activity_handlers::generic_game_finish(), Character::making_would_work(), Character::melee_attack_abstract(), Character::melee_special_effects(), Character::move_in_vehicle(), multi_projectile_hit_message(), Character::perform_technique(), outfit::sort_armor(), and outfit::wear_item().
add_msg_if_npc() [8/10]
template<typename ... Args> void Creature::add_msg_if_npc (const std::string & msg, Args &&... args) const inline
Definition at line 1028 of file creature.h.
{
             return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_npc(), and string_format().
add_msg_if_npc() [9/10]
void Creature::add_msg_if_npc (const translation & msg) const
Definition at line 3150 of file creature.cpp.
 {
     return add_msg_if_npc( msg.translated() );
 }
References add_msg_if_npc(), and translation::translated().
add_msg_if_npc() [10/10]
template<typename ... Args> void Creature::add_msg_if_npc (const translation & msg, Args &&... args) const inline
Definition at line 1032 of file creature.h.
{
             return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_npc(), and string_format().
add_msg_if_player() [1/10]
template<typename ... Args> void Creature::add_msg_if_player (const char *const msg, Args &&... args) const inline
Definition at line 982 of file creature.h.
{
             return add_msg_if_player( string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_player(), and string_format().
add_msg_if_player() [2/10]
virtual void Creature::add_msg_if_player (const game_message_params & , const std::string &) const inline virtual
Reimplemented in Character, and npc.
Definition at line 977 of file creature.h.
                                                                    {}
add_msg_if_player() [3/10]
void Creature::add_msg_if_player (const game_message_params & params, const translation & msg) const
Definition at line 3145 of file creature.cpp.
 {
     return add_msg_if_player( params, msg.translated() );
 }
References add_msg_if_player(), and translation::translated().
add_msg_if_player() [4/10]
template<typename ... Args> void Creature::add_msg_if_player (const game_message_params & params, const char *const msg, Args &&... args) const inline
Definition at line 994 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_if_player( params, string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_player(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_player() [5/10]
template<typename ... Args> void Creature::add_msg_if_player (const game_message_params & params, const std::string & msg, Args &&... args) const inline
Definition at line 1002 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_if_player( params, string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_player(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_player() [6/10]
template<typename ... Args> void Creature::add_msg_if_player (const game_message_params & params, const translation & msg, Args &&... args) const inline
Definition at line 1010 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_if_player( params, string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_player(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_player() [7/10]
virtual void Creature::add_msg_if_player (const std::string &) const inline virtual
Reimplemented in Character, and npc.
Definition at line 976 of file creature.h.
 {}
Referenced by mdefense::acidsplash(), relic::activate(), add_msg_if_player(), Character::add_msg_player_or_say(), spell_effect::banishment(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), melee_actor::call(), spell::cast_all_effects(), doors::close_door(), mattack::dermatik(), dodge_check(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), mattack::flesh_golem(), mattack::fungus_bristle(), handle_remove_fd_reality_tear_field(), doors::lock_door(), longpull(), monster::melee_attack(), melee_actor::on_damage(), mattack::para_sting(), Character::perform_technique(), process_effects(), spell_effect::recharge_vehicle(), spell_effect::remove_field(), mattack::science(), spell::select_target(), spell_effect::spawn_summoned_vehicle(), sting_shoot(), mattack::tankgun(), spell_effect::targeted_polymorph(), mattack::taze(), gun_actor::try_target(), and doors::unlock_door().
add_msg_if_player() [8/10]
template<typename ... Args> void Creature::add_msg_if_player (const std::string & msg, Args &&... args) const inline
Definition at line 986 of file creature.h.
{
             return add_msg_if_player( string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_player(), and string_format().
add_msg_if_player() [9/10]
void Creature::add_msg_if_player (const translation & msg) const
Definition at line 3140 of file creature.cpp.
 {
     return add_msg_if_player( msg.translated() );
 }
References add_msg_if_player(), and translation::translated().
add_msg_if_player() [10/10]
template<typename ... Args> void Creature::add_msg_if_player (const translation & msg, Args &&... args) const inline
Definition at line 990 of file creature.h.
{
             return add_msg_if_player( string_format( msg, std::forward<Args>( args )... ) );
         }
References add_msg_if_player(), and string_format().
add_msg_player_or_npc() [1/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const inline
Definition at line 1071 of file creature.h.
{
             return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_npc(), and string_format().
add_msg_player_or_npc() [2/10]
virtual void Creature::add_msg_player_or_npc (const game_message_params & , const std::string & , const std::string &) const inline virtual
Reimplemented in npc, monster, and Character.
Definition at line 1062 of file creature.h.
                                                                        {}
add_msg_player_or_npc() [3/10]
void Creature::add_msg_player_or_npc (const game_message_params & params, const translation & pc, const translation & npc) const
Definition at line 3165 of file creature.cpp.
 {
     return add_msg_player_or_npc( params, pc.translated(), npc.translated() );
 }
References add_msg_player_or_npc(), and translation::translated().
add_msg_player_or_npc() [4/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const game_message_params & params, const char *const player_msg, const char *const npc_msg, Args &&... args) const inline
Definition at line 1089 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_npc() [5/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const game_message_params & params, const std::string & player_msg, const std::string & npc_msg, Args &&... args) const inline
Definition at line 1098 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_npc() [6/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const game_message_params & params, const translation & player_msg, const translation & npc_msg, Args &&... args) const inline
Definition at line 1107 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_npc(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_npc() [7/10]
virtual void Creature::add_msg_player_or_npc (const std::string & , const std::string &) const inline virtual
Reimplemented in Character, npc, and monster.
Definition at line 1060 of file creature.h.
                                                                        {}
Referenced by mattack::acid_barf(), add_msg_player_or_npc(), Character::add_msg_player_or_say(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), melee_actor::call(), cant_do_underwater(), map::creature_in_field(), monster::die(), melee_actor::do_grab(), map::drop_furniture(), mattack::evolve_kill_strike(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::growplants(), mattack::lunge(), melee_actor::on_damage(), mattack::pull_metal_weapon(), mattack::science(), mattack::smash(), mattack::stretch_attack(), mattack::taze(), and mattack::vine().
add_msg_player_or_npc() [8/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const std::string & player_msg, const std::string & npc_msg, Args &&... args) const inline
Definition at line 1077 of file creature.h.
{
             return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_npc(), and string_format().
add_msg_player_or_npc() [9/10]
void Creature::add_msg_player_or_npc (const translation & pc, const translation & npc) const
Definition at line 3160 of file creature.cpp.
 {
     return add_msg_player_or_npc( pc.translated(), npc.translated() );
 }
References add_msg_player_or_npc(), and translation::translated().
add_msg_player_or_npc() [10/10]
template<typename ... Args> void Creature::add_msg_player_or_npc (const translation & player_msg, const translation & npc_msg, Args &&... args) const inline
Definition at line 1083 of file creature.h.
{
             return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_npc(), and string_format().
add_msg_player_or_say() [1/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const char *const player_msg, const char *const npc_speech, Args &&... args) const inline
Definition at line 1127 of file creature.h.
{
             return add_msg_player_or_say( string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_speech, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_say(), and string_format().
add_msg_player_or_say() [2/10]
virtual void Creature::add_msg_player_or_say (const game_message_params & , const std::string & , const std::string &) const inline virtual
Reimplemented in npc, and Character.
Definition at line 1118 of file creature.h.
                                                                        {}
add_msg_player_or_say() [3/10]
void Creature::add_msg_player_or_say (const game_message_params & params, const translation & pc, const translation & npc) const
Definition at line 3176 of file creature.cpp.
 {
     return add_msg_player_or_say( params, pc.translated(), npc.translated() );
 }
References add_msg_player_or_say(), and translation::translated().
add_msg_player_or_say() [4/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const game_message_params & params, const char *const player_msg, const char *const npc_speech, Args &&... args) const inline
Definition at line 1145 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_player_or_say( params, string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_speech, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_say(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_say() [5/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const game_message_params & params, const std::string & player_msg, const std::string & npc_speech, Args &&... args) const inline
Definition at line 1154 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_player_or_say( params, string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_speech, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_say(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_say() [6/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const game_message_params & params, const translation & player_msg, const translation & npc_speech, Args &&... args) const inline
Definition at line 1163 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_player_or_say( params, string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_speech, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_say(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_player_or_say() [7/10]
virtual void Creature::add_msg_player_or_say (const std::string & , const std::string &) const inline virtual
Reimplemented in npc, and Character.
Definition at line 1116 of file creature.h.
                                                                        {}
Referenced by add_msg_player_or_say().
add_msg_player_or_say() [8/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const std::string & player_msg, const std::string & npc_speech, Args &&... args) const inline
Definition at line 1133 of file creature.h.
{
             return add_msg_player_or_say( string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_speech, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_say(), and string_format().
add_msg_player_or_say() [9/10]
void Creature::add_msg_player_or_say (const translation & pc, const translation & npc) const
Definition at line 3171 of file creature.cpp.
 {
     return add_msg_player_or_say( pc.translated(), npc.translated() );
 }
References add_msg_player_or_say(), and translation::translated().
add_msg_player_or_say() [10/10]
template<typename ... Args> void Creature::add_msg_player_or_say (const translation & player_msg, const translation & npc_speech, Args &&... args) const inline
Definition at line 1139 of file creature.h.
{
             return add_msg_player_or_say( string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_speech, std::forward<Args>( args )... ) );
         }
References add_msg_player_or_say(), and string_format().
apply_damage()
virtual void Creature::apply_damage (Creature * source, bodypart_id bp, int amount, bool bypass_med = false) pure virtual
Implemented in Character, and monster.
Referenced by deal_damage(), explosion_handler::do_blast(), vehicle::part_collision(), and teleport::teleport_to_point().
as_avatar() [1/2]
virtual avatar* Creature::as_avatar () inline virtual
Reimplemented in avatar.
Definition at line 280 of file creature.h.
{
             return nullptr;
         }
Referenced by Character::activate_bionic(), activate_consume_eocs(), map::board_vehicle(), iuse::calories_intake_tracker(), iuse::camera(), change_armor_sprite(), spell_effect::dash(), pickup_menu_activity_actor::do_turn(), iuse::ebookread(), iuse::electricstorage(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), read_activity_actor::finish(), Character::fire_gun(), iuse::fitness_check(), get_consume_needs_hint(), get_free_invlet(), get_talker_for(), handle_player_display_action(), iexamine::ledge(), link_up_actor::link_extend_cable(), iuse::lumber(), spell_effect::map(), Character::on_mutation_gain(), Character::on_mutation_loss(), activity_handlers::pull_creature_finish(), iuse::radio_mod(), iuse::radiocar(), spell::select_target(), vehicle_folding_activity_actor::start(), spell_effect::translocate(), Character::update_body(), holster_actor::use(), sew_advanced_actor::use(), effect_on_conditons_actor::use(), link_up_actor::use(), and Character::use().
as_avatar() [2/2]
virtual const avatar* Creature::as_avatar () const inline virtual
Reimplemented in avatar.
Definition at line 283 of file creature.h.
{
             return nullptr;
         }
as_character() [1/2]
virtual Character* Creature::as_character () inline virtual
Reimplemented in Character.
Definition at line 274 of file creature.h.
{
             return nullptr;
         }
Referenced by add_effect(), attack_air(), melee_actor::call(), spell::cast_spell_effect(), doors::close_door(), weakpoint_attack::compute_wp_skill(), map::creature_in_field(), deal_damage_handle_type(), monster::die(), explosion_handler::do_blast(), melee_actor::do_grab(), dodge_check(), map::drop_furniture(), get_talker_for(), vehicle::handle_potential_theft(), handle_remove_fd_reality_tear_field(), doors::lock_door(), longpull(), magical_polymorph(), Character::melee_attack_abstract(), mod_part_hp_cur(), monster::on_hit(), spell_effect::pain_split(), Character::perform_technique(), process_effects(), projectile_attack(), ranged_target_size(), remove_effect(), sees(), select_body_part(), set_part_hp_cur(), spell_effect::spawn_summoned_vehicle(), teleport::teleport_to_point(), and doors::unlock_door().
as_character() [2/2]
virtual const Character* Creature::as_character () const inline virtual
Reimplemented in Character.
Definition at line 277 of file creature.h.
{
             return nullptr;
         }
as_monster() [1/2]
virtual monster* Creature::as_monster () inline virtual
Reimplemented in monster.
Definition at line 292 of file creature.h.
{
             return nullptr;
         }
Referenced by anonymous_namespace{math_parser_diag.cpp}::_matches_attitude_filter(), Character::add_msg_player_or_say(), projectile::apply_effects_damage(), attack_air(), game::chat(), weakpoint_attack::compute_wp_skill(), deal_damage_handle_type(), melee_actor::do_grab(), map::drop_furniture(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), get_talker_for(), spell_effect::guilt(), item::handle_pickup_ownership(), is_ranged_attacker(), longpull(), magical_polymorph(), Character::melee_attack_abstract(), anonymous_namespace{math_parser_diag.cpp}::mon_check_group(), anonymous_namespace{math_parser_diag.cpp}::mon_check_id(), anonymous_namespace{math_parser_diag.cpp}::mon_check_species(), Character::on_hit(), Character::perform_technique(), sees(), and mission::wrap_up().
as_monster() [2/2]
virtual const monster* Creature::as_monster () const inline virtual
Reimplemented in monster.
Definition at line 295 of file creature.h.
{
             return nullptr;
         }
as_npc() [1/2]
virtual npc* Creature::as_npc () inline virtual
Reimplemented in npc.
Definition at line 286 of file creature.h.
{
             return nullptr;
         }
Referenced by anonymous_namespace{math_parser_diag.cpp}::_friend_match_filter_character(), anonymous_namespace{npctrade.cpp}::_trading_price(), activate_consume_eocs(), npc_trading::adjusted_price(), monster::anger_hostile_seen(), Character::calc_spell_training_cost(), can_do_activity_there(), game::chat(), basecamp::feed_workers(), friendly_teacher(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_handler(), bionic_install_surgeon_preset::get_denial(), trade_preset::get_denial(), get_talker_for(), item::handle_pickup_ownership(), vehicle::handle_potential_theft(), Character::on_hit(), Character::process_effects(), projectile_attack(), Character::reach_attack(), spell::select_target(), talker_character_const::spell_training_text(), talker_character_const::style_training_text(), npc_trading::transfer_items(), and effect_on_conditons_actor::use().
as_npc() [2/2]
virtual const npc* Creature::as_npc () const inline virtual
Reimplemented in npc.
Definition at line 289 of file creature.h.
{
             return nullptr;
         }
attack_air()
bool Creature::attack_air (const tripoint & p)
Definition at line 1415 of file creature.cpp.
 {
     // Calculate move cost differently for monsters and npcs
     int move_cost = 100;
     if( is_monster() ) {
         move_cost = as_monster()->type->attack_cost;
     } else if( is_npc() ) {
         // Simplified moves calculation from Character::melee_attack_abstract
         item_location cur_weapon = as_character()->used_weapon();
         item cur_weap = cur_weapon ? *cur_weapon : null_item_reference();
         move_cost = as_character()->attack_speed( cur_weap ) * ( 1 /
                     as_character()->exertion_adjusted_move_multiplier( EXTRA_EXERCISE ) );
     }
     mod_moves( -move_cost );
     // Attack animation
     if( get_option<bool>( "ANIMATIONS" ) ) {
         std::map<tripoint, nc_color> area_color;
         area_color[p] = c_black;
         explosion_handler::draw_custom_explosion( p, area_color, "animation_hit" );
     }
     // Chance to remove last known location
     if( one_in( 2 ) ) {
         get_map().set_field_intensity( p, field_fd_last_known, 0 );
     }
     add_msg_if_player_sees( *this, _( "%s attacks, but there is nothing there!" ),
                             disp_name( false, true ) );
     return true;
 }
References _, add_msg_if_player_sees(), as_character(), as_monster(), mtype::attack_cost, Character::attack_speed(), c_black, disp_name(), explosion_handler::draw_custom_explosion(), Character::exertion_adjusted_move_multiplier(), EXTRA_EXERCISE, field_fd_last_known, get_map(), is_monster(), is_npc(), mod_moves(), move_cost, null_item_reference(), one_in(), map::set_field_intensity(), monster::type, and Character::used_weapon().
Referenced by monster::attack_at(), and npc::move_to().
attitude_raw_string()
std::string Creature::attitude_raw_string (Attitude att) static
Simplified attitude string for unlocalized needs.
Definition at line 3074 of file creature.cpp.
 {
     switch( att ) {
         case Attitude::HOSTILE:
             return "hostile";
         case Attitude::NEUTRAL:
             return "neutral";
         case Attitude::FRIENDLY:
             return "friendly";
         default:
             return "other";
     }
 }
References FRIENDLY, HOSTILE, and NEUTRAL.
attitude_to()
virtual Attitude Creature::attitude_to (const Creature & other) const pure virtual
Attitude (of this creature) towards another creature.
This might not be symmetric.
Implemented in npc, monster, and Character.
Referenced by spell_effect::directed_push(), Character::get_hostile_creatures(), target_ui::list_friendlies_in_lof(), melee_actor::on_damage(), projectile_attack(), and mattack::taze().
auto_find_hostile_target()
Creature * Creature::auto_find_hostile_target (int range, int & boo_hoo, int area = 0)
For fake-players (turrets, mounted turrets) this functions chooses a target.
This is for creatures that are friendly towards the player and therefore choose a target that is hostile to the player.
Parameters
range The maximal range to look for monsters, anything outside of that range is ignored.
boo_hoo The number of targets that have been skipped because the player is in the way.
area The area of effect of the projectile aimed.
Definition at line 554 of file creature.cpp.
 {
     Creature *target = nullptr;
     Character &player_character = get_player_character();
     tripoint player_pos = player_character.pos();
     constexpr int hostile_adj = 2; // Priority bonus for hostile targets
     const int iff_dist = ( range + area ) * 3 / 2 + 6; // iff check triggers at this distance
     // iff safety margin (degrees). less accuracy, more paranoia
     units::angle iff_hangle = units::from_degrees( 15 + area );
     float best_target_rating = -1.0f; // bigger is better
     units::angle u_angle = {};         // player angle relative to turret
     boo_hoo = 0;         // how many targets were passed due to IFF. Tragically.
     bool self_area_iff = false; // Need to check if the target is near the vehicle we're a part of
     bool area_iff = false;      // Need to check distance from target to player
     bool angle_iff = sees( player_character ); // Need to check if player is in cone to target
     int pldist = rl_dist( pos(), player_pos );
     map &here = get_map();
     vehicle *in_veh = is_fake() ? veh_pointer_or_null( here.veh_at( pos() ) ) : nullptr;
     if( pldist < iff_dist && angle_iff ) {
         area_iff = area > 0;
         // Player inside vehicle won't be hit by shots from the roof,
         // so we can fire "through" them just fine.
         const optional_vpart_position vp = here.veh_at( player_pos );
         if( in_veh && veh_pointer_or_null( vp ) == in_veh && vp->is_inside() ) {
             angle_iff = false; // No angle IFF, but possibly area IFF
         } else if( pldist < 3 ) {
             // granularity increases with proximity
             iff_hangle = ( pldist == 2 ? 30_degrees : 60_degrees );
         }
         u_angle = coord_to_angle( pos(), player_pos );
     }
     if( area > 0 && in_veh != nullptr ) {
         self_area_iff = true;
     }
     std::vector<Creature *> targets = g->get_creatures_if( [&]( const Creature & critter ) {
         if( critter.is_monster() ) {
             // friendly to the player, not a target for us
             return static_cast<const monster *>( &critter )->attitude( &player_character ) == MATT_ATTACK;
         }
         if( critter.is_npc() ) {
             // friendly to the player, not a target for us
             return static_cast<const npc *>( &critter )->get_attitude() == NPCATT_KILL;
         }
         // TODO: what about g->u?
         return false;
     } );
     for( Creature *&m : targets ) {
         if( !sees( *m ) ) {
             // can't see nor sense it
             if( is_fake() && in_veh ) {
                 // If turret in the vehicle then
                 // Hack: trying yo avoid turret LOS blocking by frames bug by trying to see target from vehicle boundary
                 // Or turret wallhack for turret's car
                 // TODO: to visibility checking another way, probably using 3D FOV
                 std::vector<tripoint> path_to_target = line_to( pos(), m->pos() );
                 path_to_target.insert( path_to_target.begin(), pos() );
                 // Getting point on vehicle boundaries and on line between target and turret
                 bool continueFlag = true;
                 do {
                     const optional_vpart_position vp = here.veh_at( path_to_target.back() );
                     vehicle *const veh = vp ? &vp->vehicle() : nullptr;
                     if( in_veh == veh ) {
                         continueFlag = false;
                     } else {
                         path_to_target.pop_back();
                     }
                 } while( continueFlag );
                 tripoint oldPos = pos();
                 setpos( path_to_target.back() ); //Temporary moving targeting npc on vehicle boundary position
                 bool seesFromVehBound = sees( *m ); // And look from there
                 setpos( oldPos );
                 if( !seesFromVehBound ) {
                     continue;
                 }
             } else {
                 continue;
             }
         }
         int dist = rl_dist( pos(), m->pos() ) + 1; // rl_dist can be 0
         if( dist > range + 1 || dist < area ) {
             // Too near or too far
             continue;
         }
         // Prioritize big, armed and hostile stuff
         float mon_rating = m->power_rating();
         float target_rating = mon_rating / dist;
         if( mon_rating + hostile_adj <= 0 ) {
             // We wouldn't attack it even if it was hostile
             continue;
         }
         if( in_veh != nullptr && veh_pointer_or_null( here.veh_at( m->pos() ) ) == in_veh ) {
             // No shooting stuff on vehicle we're a part of
             continue;
         }
         if( area_iff && rl_dist( player_pos, m->pos() ) <= area ) {
             // Player in AoE
             boo_hoo++;
             continue;
         }
         // Hostility check can be expensive, but we need to inform the player of boo_hoo
         // only when the target is actually "hostile enough"
         bool maybe_boo = false;
         if( angle_iff ) {
             units::angle tangle = coord_to_angle( pos(), m->pos() );
             units::angle diff = units::fabs( u_angle - tangle );
             // Player is in the angle and not too far behind the target
             if( ( diff + iff_hangle > 360_degrees || diff < iff_hangle ) &&
                 ( dist * 3 / 2 + 6 > pldist ) ) {
                 maybe_boo = true;
             }
         }
         if( !maybe_boo && ( ( mon_rating + hostile_adj ) / dist <= best_target_rating ) ) {
             // "Would we skip the target even if it was hostile?"
             // Helps avoid (possibly expensive) attitude calculation
             continue;
         }
         if( m->attitude_to( player_character ) == Attitude::HOSTILE ) {
             target_rating = ( mon_rating + hostile_adj ) / dist;
             if( maybe_boo ) {
                 boo_hoo++;
                 continue;
             }
         }
         if( target_rating <= best_target_rating || target_rating <= 0 ) {
             continue; // Handle this late so that boo_hoo++ can happen
         }
         // Expensive check for proximity to vehicle
         if( self_area_iff && overlaps_vehicle( in_veh->get_points(), m->pos(), area ) ) {
             continue;
         }
         target = m;
         best_target_rating = target_rating;
     }
     return target;
 }
References coord_to_angle(), units::fabs(), units::from_degrees(), g, get_map(), get_player_character(), vehicle::get_points(), HOSTILE, is_fake(), is_monster(), is_npc(), line_to(), overlaps_vehicle(), pos(), rl_dist(), sees(), setpos(), map::veh_at(), and veh_pointer_or_null().
Referenced by vehicle::automatic_fire_turret(), gun_actor::call(), mattack::chickenbot(), mattack::flamethrower(), and mattack::multi_robot().
avoid_trap()
virtual bool Creature::avoid_trap (const tripoint & pos, const trap & tr) const pure virtual
Called when a creature triggers a trap, returns true if they don't set it off.
Parameters
tr is the trap that was triggered.
pos is the location of the trap (not necessarily of the creature) in the main map.
Implemented in monster, and Character.
basic_symbol_color()
virtual nc_color Creature::basic_symbol_color () const pure virtual
Creature symbol color.
Implemented in npc, monster, and avatar.
Referenced by draw(), game::list_monsters(), and Character::symbol_color().
bleed()
void Creature::bleed () const virtual
Adds an appropriate blood splatter.
Definition at line 230 of file creature.cpp.
 {
     get_map().add_splatter( bloodType(), pos() );
 }
References map::add_splatter(), bloodType(), get_map(), and pos().
Referenced by Character::body_window(), mdeath::normal(), vehicle::part_collision(), and monster::process_one_effect().
block_hit()
virtual bool Creature::block_hit (Creature * source, bodypart_id & bp_hit, damage_instance & dam) pure virtual
Implemented in Character, and monster.
Referenced by mattack::acid_barf(), melee_actor::call(), deal_melee_hit(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::lunge(), and mattack::stretch_attack().
bloodType()
virtual field_type_id Creature::bloodType () const pure virtual
Implemented in monster, and Character.
Referenced by bleed(), and projectile_attack().
can_attack_high()
virtual bool Creature::can_attack_high () const pure virtual
Implemented in monster, and Character.
Referenced by deal_melee_hit(), get_all_eligable_parts(), and select_body_part().
cant_do_underwater()
bool Creature::cant_do_underwater (bool msg = true) const
Definition at line 280 of file creature.cpp.
 {
     if( is_underwater() ) {
         if( msg ) {
             add_msg_player_or_npc( m_info, _( "You can't do that while underwater." ),
                                    _( "<npcname> can't do that while underwater." ) );
         }
         return true;
     }
     return false;
 }
References _, add_msg_player_or_npc(), is_underwater(), and m_info.
Referenced by iuse::antifungal(), iuse::antiparasitic(), repair_item_actor::can_use_tool(), Character::consume(), dig_tool(), iuse::dog_whistle(), iuse::einktabletpc(), iuse::eyedrops(), iuse::firecracker(), iuse::firecracker_pack(), iuse::fish_trap(), iuse::fungicide(), iuse::gun_repair(), iuse::multicooker(), iuse::pack_item(), iuse::portable_game(), vehicle_unfolding_activity_actor::unfold_vehicle(), iuse::unpack_item(), iuse_transform::use(), heal_actor::use(), place_trap_actor::use(), and sew_advanced_actor::use().
check_avoid_friendly_fire()
virtual bool Creature::check_avoid_friendly_fire () const inline virtual
Reimplemented in Character.
Definition at line 758 of file creature.h.
{
             return false;
         }
check_dead_state()
void Creature::check_dead_state ()
This function checks the creatures is_dead_state and (if true) calls die.
You can either call this function after hitting this creature, or let the game call it during game::cleanup_dead. As die has many side effects (messages, on-death-triggers, ...), you should be careful when calling this and expect that at least a "The monster dies!" message might have been printed. If you want to print any message relating to the attack (e.g. how much damage has been dealt, how the attack was performed, what has been blocked...), do it before calling this function.
Definition at line 3067 of file creature.cpp.
 {
     if( is_dead_state() ) {
         die( killer );
     }
 }
References die(), is_dead_state(), and killer.
Referenced by Character::add_msg_player_or_say(), mattack::bio_op_impale(), mattack::bio_op_takedown(), map::crush(), mattack::dermatik(), trapfunc::dissector(), explosion_handler::do_blast(), explosion_handler::emp_blast(), field_processor_fd_push_items(), game::fling_creature(), Character::forced_dismount(), game::forced_door_closing(), mattack::fungus_fortify(), mattack::fungus_inject(), trapfunc::goo(), monster::knock_back_to(), game::knockback(), mattack::lunge(), monster::melee_attack(), Character::melee_attack_abstract(), map::monster_in_field(), Character::on_hit(), monster::on_hit(), map::player_in_field(), smash(), mattack::stretch_attack(), mattack::taze(), teleport::teleport_to_point(), mattack::vine(), and mdefense::zapback().
check_immunity_data()
virtual bool Creature::check_immunity_data (const field_immunity_data &) const inline virtual
Reimplemented in Character.
Definition at line 578 of file creature.h.
{
             return false;
         }
Referenced by map::creature_in_field().
clear_effects()
void Creature::clear_effects ()
Remove all effects.
Definition at line 1712 of file creature.cpp.
 {
     for( auto &elem : *effects ) {
         for( auto &_effect_it : elem.second ) {
             const effect &e = _effect_it.second;
             on_effect_int_change( e.get_id(), 0, e.get_bp() );
         }
     }
     effects->clear();
 }
References effects, effect::get_bp(), effect::get_id(), and on_effect_int_change().
Referenced by iuse::granade_act(), and player_difficulty::reset_npc().
clear_killer()
void Creature::clear_killer ()
Definition at line 2040 of file creature.cpp.
 {
     killer = nullptr;
 }
References killer.
Referenced by effect_on_conditions::prevent_death().
clear_values()
void Creature::clear_values ()
Definition at line 1970 of file creature.cpp.
 {
     values.clear();
 }
References values.
deal_damage()
dealt_damage_instance Creature::deal_damage (Creature * source, bodypart_id bp, const damage_instance & dam, const weakpoint_attack & attack = weakpoint_attack()) virtual
Deals the damage via an attack.
Allows armor mitigation etc.
Most sources of external damage should use deal_damage Mutates the damage_instance& object passed in to reflect the post-mitigation object. Does nothing if this creature is already dead. Does not call check_dead_state.
Parameters
source The attacking creature, can be null.
bp The attacked body part
dam The damage dealt
Reimplemented in Character.
Definition at line 1221 of file creature.cpp.
 {
     if( is_dead_state() ) {
         return dealt_damage_instance();
     }
     int total_damage = 0;
     int total_base_damage = 0;
     int total_pain = 0;
     damage_instance d = dam; // copy, since we will mutate in absorb_hit
     weakpoint_attack attack_copy = attack;
     attack_copy.source = source;
     attack_copy.target = this;
     attack_copy.compute_wp_skill();
     dealt_damage_instance dealt_dams;
     const weakpoint *wp = absorb_hit( attack_copy, bp, d );
     dealt_dams.wp_hit = wp == nullptr ? "" : wp->get_name();
     // Add up all the damage units dealt
     for( const damage_unit &it : d.damage_units ) {
         int cur_damage = 0;
         deal_damage_handle_type( effect_source( source ), it, bp, cur_damage, total_pain );
         total_base_damage += std::max( 0.0f, it.amount * it.unconditional_damage_mult );
         if( cur_damage > 0 ) {
             dealt_dams.dealt_dams[it.type] += cur_damage;
             total_damage += cur_damage;
         }
     }
     // get eocs for all damage effects
     d.ondamage_effects( source, this, dam, bp.id() );
     if( total_base_damage < total_damage ) {
         // Only deal more HP than remains if damage not including crit multipliers is higher.
         total_damage = clamp( get_hp( bp ), total_base_damage, total_damage );
     }
     if( !bp->has_flag( json_flag_BIONIC_LIMB ) ) {
         mod_pain( total_pain );
     }
     apply_damage( source, bp, total_damage );
     if( wp != nullptr ) {
         wp->apply_effects( *this, total_damage, attack_copy );
     }
     return dealt_dams;
 }
References absorb_hit(), damage_unit::amount, apply_damage(), weakpoint::apply_effects(), spell_effect::attack(), bp, clamp(), weakpoint_attack::compute_wp_skill(), damage_instance::damage_units, deal_damage_handle_type(), dealt_damage_instance::dealt_dams, get_hp(), weakpoint::get_name(), body_part_type::has_flag(), int_id< T >::id(), is_dead_state(), json_flag_BIONIC_LIMB, max(), mod_pain(), damage_instance::ondamage_effects(), weakpoint_attack::source, weakpoint_attack::target, damage_unit::type, damage_unit::unconditional_damage_mult, and dealt_damage_instance::wp_hit.
Referenced by mattack::acid_barf(), mdefense::acidsplash(), Character::add_msg_player_or_say(), mattack::bio_op_impale(), mattack::bio_op_takedown(), trapfunc::board(), melee_actor::call(), trapfunc::caltrops(), trapfunc::caltrops_glass(), trapfunc::crossbow(), Character::deal_damage(), deal_melee_hit(), trapfunc::drain(), map::drop_items(), mattack::evolve_kill_strike(), mattack::flesh_golem(), mattack::fungus_bristle(), trapfunc::glow(), mattack::growplants(), trapfunc::lava(), mattack::lunge(), map::monster_in_field(), Character::on_hit(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), process_damage_over_time(), trapfunc::shotgun(), trapfunc::snare_heavy(), mattack::stretch_attack(), mattack::taze(), trapfunc::tripwire(), mattack::vine(), and mdefense::zapback().
deal_damage_handle_type()
void Creature::deal_damage_handle_type (const effect_source & source, const damage_unit & du, bodypart_id bp, int & damage, int & pain) virtual
Reimplemented in monster.
Definition at line 1270 of file creature.cpp.
 {
     // Handles ACIDPROOF, electric immunity etc.
     if( is_immune_damage( du.type ) ) {
         return;
     }
     // Apply damage multiplier from skill, critical hits or grazes after all other modifications.
     const int adjusted_damage = du.amount * du.damage_multiplier * du.unconditional_damage_mult;
     if( adjusted_damage <= 0 ) {
         return;
     }
     float div = 4.0f;
     // FIXME: Hardcoded damage types
     if( du.type == damage_bash ) {
         // Bashing damage is less painful
         div = 5.0f;
     } else if( du.type == damage_heat ) {
         // heat damage sets us on fire sometimes
         if( rng( 0, 100 ) < adjusted_damage ) {
             add_effect( source, effect_onfire, rng( 1_turns, 3_turns ), bp );
             Character &player_character = get_player_character();
             if( player_character.has_trait( trait_PYROMANIA ) &&
                 !player_character.has_morale( MORALE_PYROMANIA_STARTFIRE ) && player_character.sees( *this ) ) {
                 player_character.add_msg_if_player( m_good,
                                                     _( "You feel a surge of euphoria as flame engulfs %s!" ), this->get_name() );
                 player_character.add_morale( MORALE_PYROMANIA_STARTFIRE, 15, 15, 8_hours, 6_hours );
                 player_character.rem_morale( MORALE_PYROMANIA_NOFIRE );
             }
         }
     } else if( du.type == damage_electric ) {
         // Electrical damage adds a major speed/dex debuff
         double multiplier = 1.0;
         if( monster *mon = as_monster() ) {
             multiplier = mon->type->status_chance_multiplier;
         }
         const int chance = std::log10( ( adjusted_damage + 2 ) * 0.5 ) * 100 * multiplier;
         if( x_in_y( chance, 100 ) ) {
             const int duration = std::max( adjusted_damage / 10.0 * multiplier, 2.0 );
             add_effect( source, effect_zapped, 1_turns * duration );
         }
         if( Character *ch = as_character() ) {
             const double pain_mult = ch->calculate_by_enchantment( 1.0, enchant_vals::mod::EXTRA_ELEC_PAIN );
             div /= pain_mult;
             if( pain_mult > 1.0 ) {
                 ch->add_msg_player_or_npc( m_bad, _( "You're painfully electrocuted!" ),
                                            _( "<npcname> is shocked!" ) );
             }
         }
     } else if( du.type == damage_acid ) {
         // Acid damage and acid burns are more painful
         div = 3.0f;
     }
     on_damage_of_type( source, adjusted_damage, du.type, bp );
     damage += adjusted_damage;
     pain += roll_remainder( adjusted_damage / div );
 }
References _, add_effect(), Character::add_morale(), Character::add_msg_if_player(), damage_unit::amount, as_character(), as_monster(), bp, damage_acid, damage_bash, damage_electric, damage_heat, damage_unit::damage_multiplier, math_opers::div(), effect_onfire, effect_zapped, enchant_vals::EXTRA_ELEC_PAIN, get_name(), get_player_character(), Character::has_morale(), Character::has_trait(), is_immune_damage(), m_bad, m_good, max(), MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, on_damage_of_type(), pain, Character::rem_morale(), rng(), roll_remainder(), Character::sees(), trait_PYROMANIA, damage_unit::type, damage_unit::unconditional_damage_mult, and x_in_y().
Referenced by deal_damage(), monster::deal_damage_handle_type(), and item::effective_dps().
deal_melee_attack()
int Creature::deal_melee_attack (Creature * source, int hitroll) virtual
Definition at line 767 of file creature.cpp.
 {
     const float dodge = dodge_roll();
     on_try_dodge();
     int hit_spread = hitroll - dodge - size_melee_penalty();
     add_msg_debug( debugmode::DF_CREATURE, "Base hitroll %d",
                    hitroll );
     add_msg_debug( debugmode::DF_CREATURE, "Dodge roll %.1f",
                    dodge );
     if( has_flag( mon_flag_IMMOBILE ) ) {
         // Under normal circumstances, even a clumsy person would
         // not miss a turret.  It should, however, be possible to
         // miss a smaller target, especially when wielding a
         // clumsy weapon or when severely encumbered.
         hit_spread += 40;
     }
     // If attacker missed call targets on_dodge event
     if( dodge > 0.0 && hit_spread <= 0 && source != nullptr && !source->is_hallucination() ) {
         on_dodge( source, source->get_melee() );
     }
     add_msg_debug( debugmode::DF_CREATURE, "Final hitspread %d",
                    hit_spread );
     return hit_spread;
 }
References add_msg_debug, debugmode::DF_CREATURE, dodge_roll(), get_melee(), has_flag(), is_hallucination(), mon_flag_IMMOBILE, on_dodge(), on_try_dodge(), and size_melee_penalty().
Referenced by melee_actor::call(), avatar::disarm(), monster::melee_attack(), Character::melee_attack_abstract(), and Character::perform_special_attacks().
deal_melee_hit()
void Creature::deal_melee_hit (Creature * source, int hit_spread, bool critical_hit, damage_instance dam, dealt_damage_instance & dealt_dam, const weakpoint_attack & attack = weakpoint_attack(), const bodypart_id * bp = nullptr) virtual
Definition at line 797 of file creature.cpp.
 {
     if( source == nullptr || source->is_hallucination() ) {
         dealt_dam.bp_hit = anatomy_human_anatomy->random_body_part();
         return;
     }
     dam = source->modify_damage_dealt_with_enchantments( dam );
     // If carrying a rider, there is a chance the hits may hit rider instead.
     // melee attack will start off as targeted at mount
     if( has_effect( effect_ridden ) ) {
         monster *mons = dynamic_cast<monster *>( this );
         if( mons && mons->mounted_player ) {
             if( !mons->has_flag( mon_flag_MECH_DEFENSIVE ) &&
                 one_in( std::max( 2, mons->get_size() - mons->mounted_player->get_size() ) ) ) {
                 mons->mounted_player->deal_melee_hit( source, hit_spread, critical_hit, dam, dealt_dam, attack );
                 return;
             }
         }
     }
     damage_instance d = dam; // copy, since we will mutate in block_hit
     bodypart_id bp_hit = bp == nullptr ? select_body_part( -1, -1, source->can_attack_high(),
                          hit_spread ) : *bp;
     block_hit( source, bp_hit, d );
     weakpoint_attack attack_copy = attack;
     attack_copy.is_crit = critical_hit;
     attack_copy.type = weakpoint_attack::type_of_melee_attack( d );
     on_hit( source, bp_hit ); // trigger on-gethit events
     dam.onhit_effects( source, this ); // on-hit effects for inflicted damage types
     dealt_dam = deal_damage( source, bp_hit, d, attack_copy );
     dealt_dam.bp_hit = bp_hit;
 }
References anatomy_human_anatomy, spell_effect::attack(), block_hit(), bp, dealt_damage_instance::bp_hit, can_attack_high(), deal_damage(), deal_melee_hit(), effect_ridden, Character::get_size(), monster::get_size(), has_effect(), monster::has_flag(), weakpoint_attack::is_crit, is_hallucination(), max(), modify_damage_dealt_with_enchantments(), mon_flag_MECH_DEFENSIVE, monster::mounted_player, on_hit(), one_in(), damage_instance::onhit_effects(), anatomy::random_body_part(), select_body_part(), weakpoint_attack::type, and weakpoint_attack::type_of_melee_attack().
Referenced by deal_melee_hit(), monster::melee_attack(), Character::melee_attack_abstract(), and Character::perform_special_attacks().
deal_projectile_attack()
void Creature::deal_projectile_attack (Creature * source, dealt_projectile_attack & attack, bool print_messages = true, const weakpoint_attack & wp_attack = weakpoint_attack()) virtual
Attempts to harm a creature with a projectile.
Parameters
source Pointer to the creature who shot the projectile.
attack A structure describing the attack and its results.
print_messages enables message printing by default.
Reimplemented in monster.
Definition at line 1121 of file creature.cpp.
 {
     const bool magic = attack.proj.proj_effects.count( "MAGIC" ) > 0;
     const double missed_by = attack.missed_by;
     if( missed_by >= 1.0 && !magic ) {
         // Total miss
         return;
     }
     // If carrying a rider, there is a chance the hits may hit rider instead.
     if( has_effect( effect_ridden ) ) {
         monster *mons = as_monster();
         if( mons && mons->mounted_player ) {
             if( !mons->has_flag( mon_flag_MECH_DEFENSIVE ) &&
                 one_in( std::max( 2, mons->get_size() - mons->mounted_player->get_size() ) ) ) {
                 mons->mounted_player->deal_projectile_attack( source, attack, print_messages, wp_attack );
                 return;
             }
         }
     }
     const projectile &proj = attack.proj;
     dealt_damage_instance &dealt_dam = attack.dealt_dam;
     const auto &proj_effects = proj.proj_effects;
     viewer &player_view = get_player_view();
     const bool u_see_this = player_view.sees( *this );
     const double goodhit = accuracy_projectile_attack( attack );
     on_try_dodge(); // There's a doge roll in accuracy_projectile_attack()
     if( goodhit >= 1.0 && !magic ) {
         attack.missed_by = 1.0; // Arbitrary value
         if( !print_messages ) {
             return;
         }
         // "Avoid" rather than "dodge", because it includes removing self from the line of fire
         //  rather than just Matrix-style bullet dodging
         if( source != nullptr && player_view.sees( *source ) ) {
             add_msg_player_or_npc(
                 m_warning,
                 _( "You avoid %s projectile!" ),
                 get_option<bool>( "LOG_MONSTER_ATTACK_MONSTER" ) ? _( "<npcname> avoids %s projectile." ) : "",
                 source->disp_name( true ) );
         } else {
             add_msg_player_or_npc(
                 m_warning,
                 _( "You avoid an incoming projectile!" ),
                 get_option<bool>( "LOG_MONSTER_ATTACK_MONSTER" ) ? _( "<npcname> avoids an incoming projectile." ) :
                 "" );
         }
         return;
     }
     proj.apply_effects_nodamage( *this, source );
     projectile_attack_results hit_selection = select_body_part_projectile_attack( proj, goodhit,
             missed_by );
     // Create a copy that records whether the attack is a crit.
     weakpoint_attack wp_attack_copy = wp_attack;
     wp_attack_copy.is_crit = hit_selection.is_crit;
     wp_attack_copy.type = weakpoint_attack::attack_type::PROJECTILE;
     if( print_messages && source != nullptr && !hit_selection.message.empty() && u_see_this ) {
         source->add_msg_if_player( m_good, hit_selection.message );
     }
     attack.missed_by = goodhit;
     // copy it, since we're mutating.
     damage_instance impact = proj.impact;
     if( hit_selection.damage_mult > 0.0f && proj_effects.count( "NO_DAMAGE_SCALING" ) ) {
         hit_selection.damage_mult = 1.0f;
     }
     impact.mult_damage( hit_selection.damage_mult );
     if( proj_effects.count( "NOGIB" ) > 0 ) {
         float dmg_ratio = static_cast<float>( impact.total_damage() ) / get_hp_max( hit_selection.bp_hit );
         if( dmg_ratio > 1.25f ) {
             impact.mult_damage( 1.0f / dmg_ratio );
         }
     }
     dealt_dam = deal_damage( source, hit_selection.bp_hit, impact, wp_attack_copy );
     // Force damage instance to match the selected body point
     dealt_dam.bp_hit = hit_selection.bp_hit;
     // Retrieve the selected weakpoint from the damage instance.
     hit_selection.wp_hit = dealt_dam.wp_hit;
     proj.apply_effects_damage( *this, source, dealt_dam, goodhit < accuracy_critical );
     if( print_messages ) {
         messaging_projectile_attack( source, hit_selection, dealt_dam.total_damage() );
     }
     check_dead_state();
     attack.hit_critter = this;
     attack.missed_by = goodhit;
 }
Referenced by Character::add_msg_player_or_say(), damage_targets(), monster::deal_projectile_attack(), projectile_attack(), and explosion_handler::shrapnel().
decrement_summon_timer()
void Creature::decrement_summon_timer ()
Definition at line 2050 of file creature.cpp.
 {
     if( !lifespan_end ) {
         return;
     }
     if( lifespan_end.value() <= calendar::turn ) {
         die( nullptr );
     }
 }
References die(), lifespan_end, and calendar::turn.
Referenced by process_turn().
describe_infrared()
void Creature::describe_infrared (std::vector< std::string > & buf) const
Describe this creature as seen by the avatar via infrared vision.
Definition at line 3199 of file creature.cpp.
 {
     std::string size_str;
     switch( get_size() ) {
         case creature_size::tiny:
             size_str = pgettext( "infrared size", "tiny" );
             break;
         case creature_size::small:
             size_str = pgettext( "infrared size", "small" );
             break;
         case creature_size::medium:
             size_str = pgettext( "infrared size", "medium" );
             break;
         case creature_size::large:
             size_str = pgettext( "infrared size", "large" );
             break;
         case creature_size::huge:
             size_str = pgettext( "infrared size", "huge" );
             break;
         case creature_size::num_sizes:
             debugmsg( "Creature has invalid size class." );
             size_str = "invalid";
             break;
     }
     buf.emplace_back( _( "You see a figure radiating heat." ) );
     buf.push_back( string_format( _( "It is %s in size." ), size_str ) );
 }
References _, debugmsg, get_size(), huge, large, medium, num_sizes, pgettext, small, string_format(), and tiny.
Referenced by target_ui::panel_target_info().
describe_specials()
void Creature::describe_specials (std::vector< std::string > & buf) const
Describe this creature as detected by the avatar's special senses.
Definition at line 3227 of file creature.cpp.
 {
     buf.emplace_back( _( "You sense a creature here." ) );
 }
References _.
Referenced by target_ui::panel_target_info().
die()
virtual void Creature::die (Creature * killer) pure virtual
Empty function.
Should always be overwritten by the appropriate player/NPC/monster version.
Implemented in Character, npc, and monster.
Referenced by jmapgen_setmap::apply(), check_dead_state(), decrement_summon_timer(), debug_menu::kill_area(), knock_back_from(), talk_function::loot_building(), process_effects(), and monster::push_to().
digging()
bool Creature::digging () const virtual
Reimplemented in monster.
Definition at line 329 of file creature.cpp.
 {
     return false;
 }
Referenced by sees(), and Character::sees_with_specials().
disp_name()
virtual std::string Creature::disp_name (bool possessive = false, bool capitalize_first = false) const pure virtual
Implemented in monster, and Character.
Referenced by Character::add_msg_player_or_say(), attack_air(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), game::butcher(), gun_actor::call(), vehicle::can_close(), enchant_cache::cast_enchantment_spell(), doors::close_door(), damage_targets(), Character::deal_damage(), explosion_handler::do_blast(), melee_actor::do_grab(), glide_activity_actor::do_turn(), map::drop_items(), eff_fun_sleep(), spell_effect::effect_on_condition(), mattack::evolve_kill_strike(), mattack::flesh_golem(), mattack::fungus_bristle(), Character::impact(), trapfunc::ledge(), game::list_monsters(), longpull(), mattack::lunge(), monster::melee_attack(), Character::melee_attack_abstract(), Character::melee_special_effects(), messaging_projectile_attack(), Character::mod_speed_bonus(), npc::move(), multi_projectile_hit_message(), Character::mutation_attacks(), Character::on_hit(), Character::on_hurt(), vehicle::part_collision(), Character::perform_technique(), monster::plan(), player_hit_message(), replace_with_npc_name(), mattack::science(), mattack::shockstorm(), explosion_handler::shrapnel(), mattack::smash(), spell_effect::spawn_ethereal_item(), stumble_invis(), iuse::tazer(), teleport::teleport_to_point(), gun_actor::try_target(), and mdefense::zapback().
dodge_check() [1/3]
bool Creature::dodge_check (float hit_roll, bool force_try = false, float training_level = 0.0f)
If training_level is anything but 0, the check will only train target's skill to that level.
Definition at line 1447 of file creature.cpp.
 {
     // If successfully uncanny dodged, no need to calculate dodge chance
     if( uncanny_dodge() ) {
         return true;
     }
     const float dodge_ability = dodge_roll();
     // center is 5 - 0 / 2
     // stddev is 5 - 0 / 4
     const float dodge_chance = 1 - normal_roll_chance( 2.5f, 1.25f, dodge_ability - hit_roll );
     if( dodge_chance >= 0.8f || force_try ) {
         on_try_dodge();
         float attack_roll = hit_roll + rng_normal( 0, 5 );
         return dodge_ability > attack_roll;
     }
     add_msg_if_player( m_warning,
                        _( "You don't think you could dodge this attack, and decide to conserve stamina." ) );
     return false;
 }
References _, add_msg_if_player(), dodge_roll(), hit_roll(), m_warning, normal_roll_chance(), on_try_dodge(), rng_normal(), and uncanny_dodge().
Referenced by mattack::acid_barf(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), damage_targets(), mattack::dermatik(), glide_activity_actor::do_turn(), dodge_check(), mattack::evolve_kill_strike(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::lunge(), mattack::smash(), mattack::stretch_attack(), mattack::taze(), and iuse::tazer().
dodge_check() [2/3]
bool Creature::dodge_check (monster * z, bodypart_id bp, const damage_instance & dam_inst, float training_level = 0.0f)
Definition at line 1474 of file creature.cpp.
 {
     if( is_monster() ) {
         return dodge_check( z );
     }
     Character *guy_target = as_character();
     float potential_damage = 0.0f;
     for( const damage_unit &dmg : dam_inst.damage_units ) {
         potential_damage += dmg.amount - guy_target->worn.damage_resist( dmg.type, bp );
     }
     int part_hp = guy_target->get_part_hp_cur( bp );
     float dmg_ratio = 0.0f; // if the part is already destroyed it can't take more damage
     if( part_hp > 0 ) {
         dmg_ratio = potential_damage / part_hp;
     }
     //If attack might remove more than half of the part's hp, dodge no matter the odds
     if( dmg_ratio >= 0.5f ) {
         return dodge_check( z->get_hit(), true, training_level );
     } else if( dmg_ratio > 0.0f ) { // else apply usual rules
         return dodge_check( z->get_hit(), training_level );
     }
     return false;
 }
References damage_unit::amount, as_character(), bp, outfit::damage_resist(), damage_instance::damage_units, dodge_check(), get_hit(), get_part_hp_cur(), is_monster(), damage_unit::type, and Character::worn.
dodge_check() [3/3]
bool Creature::dodge_check (monster * z, float training_level = 0.0f)
Definition at line 1469 of file creature.cpp.
 {
     return dodge_check( z->get_hit(), training_level );
 }
References dodge_check(), and get_hit().
dodge_roll()
virtual float Creature::dodge_roll () const pure virtual
Implemented in monster, and Character.
Referenced by accuracy_projectile_attack(), deal_melee_attack(), dodge_check(), map::drop_items(), and Character::melee_attack_abstract().
draw() [1/2]
void Creature::draw (const catacurses::window & w, const point & origin, bool inverted) const
Definition at line 2977 of file creature.cpp.
 {
     draw( w, tripoint( origin, posz() ), inverted );
 }
References posz(), and tripoint.
Referenced by draw(), game::draw_critter(), anonymous_namespace{animation.cpp}::draw_line_curses(), editmap::draw_main_ui_overlay(), advanced_inventory::draw_minimap(), and editmap::uber_draw_ter().
draw() [2/2]
void Creature::draw (const catacurses::window & w, const tripoint & origin, bool inverted) const
Definition at line 2982 of file creature.cpp.
 {
     if( is_draw_tiles_mode() ) {
         return;
     }
     point draw( -origin.xy() + point( getmaxx( w ) / 2 + posx(), getmaxy( w ) / 2 + posy() ) );
     if( inverted ) {
         mvwputch_inv( w, draw, basic_symbol_color(), symbol() );
     } else if( is_symbol_highlighted() ) {
         mvwputch_hi( w, draw, basic_symbol_color(), symbol() );
     } else {
         mvwputch( w, draw, symbol_color(), symbol() );
     }
 }
References basic_symbol_color(), draw(), catacurses::getmaxx(), catacurses::getmaxy(), is_draw_tiles_mode(), is_symbol_highlighted(), mvwputch(), mvwputch_hi(), mvwputch_inv(), posx(), posy(), symbol(), and symbol_color().
extended_description()
virtual std::string Creature::extended_description () const pure virtual
Implemented in npc, monster, and Character.
Referenced by game::extended_description().
fall_damage_mod()
virtual float Creature::fall_damage_mod () const pure virtual
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
Implemented in monster, and Character.
get_all_body_parts()
std::vector< bodypart_id > Creature::get_all_body_parts (get_body_part_flags flags = get_body_part_flags::none) const
Returns body parts this creature have.
Parameters
only_main If true, only displays parts that can have hit points
Definition at line 2627 of file creature.cpp.
 {
     bool only_main( flags & get_body_part_flags::only_main );
     bool only_minor( flags & get_body_part_flags::only_minor );
     std::vector<bodypart_id> all_bps;
     all_bps.reserve( body.size() );
     for( const std::pair<const bodypart_str_id, bodypart> &elem : body ) {
         if( ( only_main && elem.first->main_part != elem.first ) || ( only_minor &&
                 elem.first->main_part == elem.first ) ) {
             continue;
         }
         all_bps.emplace_back( elem.first );
     }
     if( flags & get_body_part_flags::sorted ) {
         sort_body_parts( all_bps, this );
     }
     return  all_bps;
 }
References body, only_main, only_minor, sort_body_parts(), and sorted.
Referenced by npc::adjust_worn(), Character::apply_wetness_morale(), iexamine::autodoc(), spell_effect::banishment(), iexamine::bars(), Character::best_part_to_smash(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), blood_magic(), Character::body_window(), Character::bodypart_exposure(), Character::bonus_item_warmth(), bp_affected(), Character::calc_sleep_recovery_rate(), Character::can_wear(), debug_menu::character_edit_hp_menu(), Character::count_bodypart_with_flag(), debug_menu::damage_self(), Character::drench(), Character::drench_mut_calc(), Character::enough_working_legs(), npc::estimate_armour(), npc::evaluate_character(), npc::evaluate_self(), Character::exclusive_flag_coverage(), Character::extended_description(), suffer::from_other_mutations(), suffer::from_tourniquet(), Character::get_all_armor_type(), talker_character::get_all_body_parts(), get_all_eligable_parts(), Character::get_dodge(), get_drenching_body_parts(), Character::get_limb_techs(), get_max_hitsize_bodypart(), npc::get_opinion_values(), get_root_body_part(), Character::get_wind_resistance(), Character::get_working_leg_count(), talk_function::give_aid(), iuse::granade_act(), start_location::handle_heli_crash(), Character::healall(), Character::hitall(), Character::hurtall(), Character::impact(), Character::is_dead_state(), Character::is_wearing_shoes(), outfit::item_encumb(), talk_function::lesser_give_aid(), list_and_combine_bps(), Character::mend(), Character::mod_power_level(), Character::mod_stamina(), Character::most_staunchable_bp(), behavior::character_oracle_t::needs_warmth_badly(), item::on_wear(), Character::pause(), map::player_in_field(), avatar::power_bionics(), Character::prevent_death(), Character::process_bionic(), Character::regen(), Character::roll_damage(), select_blocking_part(), select_body_part(), mattack::slimespring(), outfit::sort_armor(), Character::suffer(), Character::tally_organic_size(), Character::update_body_wetness(), Character::update_bodytemp(), heal_actor::use_healing_item(), outfit::warmth(), npc::wear_if_wanted(), outfit::wear_item(), wet_character(), and debug_menu::wisheffect().
get_all_body_parts_of_type()
std::vector< bodypart_id > Creature::get_all_body_parts_of_type (body_part_type::type part_type, get_body_part_flags flags = get_body_part_flags::none) const
Definition at line 2659 of file creature.cpp.
 {
     const bool only_main( flags & get_body_part_flags::only_main );
     const bool primary( flags & get_body_part_flags::primary_type );
     std::vector<bodypart_id> bodyparts;
     for( const std::pair<const bodypart_str_id, bodypart> &elem : body ) {
         if( only_main && elem.first->main_part != elem.first ) {
             continue;
         }
         if( primary ) {
             if( elem.first->primary_limb_type() == part_type ) {
                 bodyparts.emplace_back( elem.first );
             }
         } else if( elem.first->has_type( part_type ) ) {
             bodyparts.emplace_back( elem.first );
         }
     }
     if( flags & get_body_part_flags::sorted ) {
         sort_body_parts( bodyparts, this );
     }
     return bodyparts;
 }
References body, only_main, primary_type, sort_body_parts(), and sorted.
Referenced by Character::avg_encumb_of_limb_type(), character_martial_arts::can_arm_block(), character_martial_arts::can_leg_block(), Character::check_immunity_data(), get_num_body_parts_of_type(), get_num_broken_body_parts_of_type(), get_random_body_part_of_type(), Character::get_working_arm_count(), glare(), Character::item_handling_cost(), Character::recalc_limb_energy_usage(), and game::slip_down_chance().
get_all_body_parts_with_flag()
std::vector< bodypart_id > Creature::get_all_body_parts_with_flag (const json_character_flag & flag) const
Definition at line 2691 of file creature.cpp.
 {
     std::vector<bodypart_id> bodyparts;
     for( const std::pair<const bodypart_str_id, bodypart> &elem : body ) {
         if( elem.first->has_flag( flag ) ) {
             bodyparts.emplace_back( elem.first );
         }
     }
     return bodyparts;
 }
References body.
Referenced by character_martial_arts::can_nonstandard_block(), and get_drenching_body_parts().
get_all_eligable_parts()
std::vector< bodypart_id > Creature::get_all_eligable_parts (int min_hit, int max_hit, bool can_attack_high) const
Definition at line 3036 of file creature.cpp.
 {
     return anatomy( get_all_body_parts() ).get_all_eligable_parts( min_hit, max_hit, can_attack_high );
 }
References can_attack_high(), get_all_body_parts(), and anatomy::get_all_eligable_parts().
Referenced by melee_actor::call().
get_anatomy()
anatomy_id Creature::get_anatomy () const
Definition at line 2157 of file creature.cpp.
 {
     return creature_anatomy;
 }
References creature_anatomy.
Referenced by get_random_body_part(), random_body_part(), select_body_part_projectile_attack(), and set_body().
get_armor_res()
int Creature::get_armor_res (const damage_type_id & dt, bodypart_id bp) const virtual
Definition at line 2118 of file creature.cpp.
 {
     return get_armor_res_bonus( dt );
 }
References get_armor_res_bonus().
get_armor_res_base()
int Creature::get_armor_res_base (const damage_type_id & dt, bodypart_id bp) const virtual
Definition at line 2122 of file creature.cpp.
 {
     return get_armor_res_bonus( dt );
 }
References get_armor_res_bonus().
get_armor_res_bonus()
int Creature::get_armor_res_bonus (const damage_type_id & dt) const virtual
Definition at line 2126 of file creature.cpp.
 {
     auto iter = armor_bonus.find( dt );
     return iter == armor_bonus.end() ? 0 : std::round( iter->second );
 }
References armor_bonus, and round().
Referenced by get_armor_res(), get_armor_res_base(), and monster::get_armor_type().
get_armor_type()
virtual int Creature::get_armor_type (const damage_type_id & dt, bodypart_id bp) const pure virtual
Implemented in monster, and Character.
Referenced by explosion_handler::do_blast(), vehicle::part_collision(), mattack::taze(), and iuse::tazer().
get_attitude_ui_data()
const std::pair< translation, nc_color > & Creature::get_attitude_ui_data (Attitude att) static
Creature Attitude as String and color.
Definition at line 3088 of file creature.cpp.
 {
     using pair_t = std::pair<translation, nc_color>;
     static const std::array<pair_t, 5> strings {
         {
             pair_t {to_translation( "Hostile" ), c_red},
             pair_t {to_translation( "Neutral" ), h_white},
             pair_t {to_translation( "Friendly" ), c_green},
             pair_t {to_translation( "Any" ), c_yellow},
             pair_t {to_translation( "BUG: Behavior unnamed.  (Creature::get_attitude_ui_data)" ), h_red}
         }
     };
     if( static_cast<int>( att ) < 0 || static_cast<int>( att ) >= static_cast<int>( strings.size() ) ) {
         return strings.back();
     }
     return strings[static_cast<int>( att )];
 }
References c_green, c_red, c_yellow, h_red, h_white, and to_translation().
Referenced by game::list_monsters(), npc::print_info(), and safemode::show().
get_bash_bonus()
int Creature::get_bash_bonus () const virtual
Definition at line 2802 of file creature.cpp.
 {
     return bash_bonus;
 }
References bash_bonus.
get_bash_mult()
float Creature::get_bash_mult () const virtual
Definition at line 2811 of file creature.cpp.
 {
     return bash_mult;
 }
References bash_mult.
get_block_bonus()
int Creature::get_block_bonus () const virtual
Definition at line 2794 of file creature.cpp.
 {
     return block_bonus; //base is 0
 }
References block_bonus.
Referenced by damage_targets().
get_body()
const std::map< bodypart_str_id, bodypart > & Creature::get_body () const
Definition at line 2167 of file creature.cpp.
 {
     return body;
 }
References body.
Referenced by outfit::adjust_worn(), Character::calc_bmi_encumb(), get_hp(), get_hp_max(), Character::get_lowest_hp(), npc::get_opinion_values(), Character::has_bodypart_with_flag(), known_magic::has_enough_energy(), Character::hp_percentage(), spell_effect::pain_split(), Character::process_bionic(), and suffer::water_damage().
get_crit_factor()
float Creature::get_crit_factor (const bodypart_id & bp) const
Definition at line 754 of file creature.cpp.
 {
     float crit_mod = 1.f;
     const Character *c = as_character();
     if( c != nullptr ) {
         const int total_cover = clamp<int>( c->worn.get_coverage( bp, item::cover_type::COVER_VITALS ), 0,
                                             100 );
         crit_mod = 1.f - total_cover / 100.f;
     }
     // TODO: as_monster()
     return crit_mod;
 }
Referenced by Character::roll_all_damage(), and select_body_part_projectile_attack().
get_cut_bonus()
int Creature::get_cut_bonus () const virtual
Definition at line 2806 of file creature.cpp.
 {
     return cut_bonus;
 }
References cut_bonus.
get_cut_mult()
float Creature::get_cut_mult () const virtual
Definition at line 2815 of file creature.cpp.
 {
     return cut_mult;
 }
References cut_mult.
get_dodge()
float Creature::get_dodge () const virtual
Reimplemented in monster, and Character.
Definition at line 2148 of file creature.cpp.
 {
     return get_dodge_base() + get_dodge_bonus();
 }
References get_dodge_base(), and get_dodge_bonus().
Referenced by damage_targets(), item::effective_dps(), Character::get_dodge(), monster::get_dodge(), and Character::throwing_dispersion().
get_dodge_base()
virtual float Creature::get_dodge_base () const pure virtual
Implemented in monster, and Character.
Referenced by get_dodge().
get_dodge_bonus()
float Creature::get_dodge_bonus () const virtual
Definition at line 2790 of file creature.cpp.
 {
     return dodge_bonus;
 }
References dodge_bonus.
Referenced by get_dodge().
get_drenching_body_parts()
body_part_set Creature::get_drenching_body_parts (bool upper = true, bool mid = true, bool lower = true) const
Definition at line 2704 of file creature.cpp.
 {
     body_part_set ret;
     // Need to exclude stuff - start full and reduce?
     ret.fill( get_all_body_parts() );
     // Diving
     if( upper && mid && lower ) {
         return ret;
     }
     body_part_set upper_limbs;
     body_part_set lower_limbs;
     upper_limbs.fill( get_all_body_parts_with_flag( json_flag_LIMB_UPPER ) );
     lower_limbs.fill( get_all_body_parts_with_flag( json_flag_LIMB_LOWER ) );
     // Rain?
     if( upper && mid ) {
         ret.substract_set( lower_limbs );
     }
     // Swimming with your head out
     if( !upper ) {
         ret.substract_set( upper_limbs );
     }
     // Wading in water
     if( !upper && !mid && lower ) {
         ret = lower_limbs;
     }
     return ret;
 }
References body_part_set::fill(), get_all_body_parts(), get_all_body_parts_with_flag(), json_flag_LIMB_LOWER, json_flag_LIMB_UPPER, and cata::hash64_detail::ret.
Referenced by Character::pause(), game::place_player(), avatar_action::swim(), and wet_character().
get_eff_per()
int Creature::get_eff_per () const virtual
Reimplemented in monster, and Character.
Definition at line 2143 of file creature.cpp.
 {
     return 0;
 }
Referenced by sees().
get_effect() [1/2]
effect & Creature::get_effect (const efftype_id & eff_id, const bodypart_id & bp = bodypart_str_id::NULL_ID())
Definition at line 1847 of file creature.cpp.
 {
     return const_cast<effect &>( const_cast<const Creature *>( this )->get_effect( eff_id, bp ) );
 }
References bp, and get_effect().
get_effect() [2/2]
const effect & Creature::get_effect (const efftype_id & eff_id, const bodypart_id & bp = bodypart_str_id::NULL_ID()) const
Return the effect that matches the given arguments exactly.
Definition at line 1852 of file creature.cpp.
 {
     auto got_outer = effects->find( eff_id );
     if( got_outer != effects->end() ) {
         auto got_inner = got_outer->second.find( bp );
         if( got_inner != got_outer->second.end() ) {
             return got_inner->second;
         }
     }
     return effect::null_effect;
 }
References bp, effects, and effect::null_effect.
Referenced by Character::apply_damage(), iexamine::autodoc(), Character::body_window(), bp_affected(), Character::calc_needs_rates(), Character::calc_sleep_recovery_rate(), Character::can_wear(), npc::complain(), npc::evaluate_character(), npc::evaluate_self(), heal_actor::finish_using(), get_effect(), talker_character_const::get_effect(), talker_monster_const::get_effect(), get_effect_dur(), get_effect_int(), mattack::kamikaze(), Character::mend(), Character::on_damage_of_type(), Character::pause(), mattack::photograph(), Character::process_bionic(), Character::process_one_effect(), monster::process_one_effect(), sounds::process_sound_markers(), Character::react_to_felt_pain(), Character::reduce_healing_effect(), remove_effect(), avatar::reset_stats(), mattack::slimespring(), avatar::try_break_relax_gas(), Character::update_needs(), Character::update_vitamins(), Character::wake_up(), debug_menu::wisheffect(), and mattack::zombie_fuse().
get_effect_dur()
time_duration Creature::get_effect_dur (const efftype_id & eff_id, const bodypart_id & bp = bodypart_str_id::NULL_ID()) const
Returns the duration of the matching effect.
Returns 0 if effect doesn't exist.
Definition at line 1863 of file creature.cpp.
 {
     const effect &eff = get_effect( eff_id, bp );
     if( !eff.is_null() ) {
         return eff.get_duration();
     }
     return 0_turns;
 }
References bp, effect::get_duration(), get_effect(), and effect::is_null().
Referenced by iuse::adrenaline_injector(), mattack::check_money_left(), Character::check_needs_extremes(), iuse::ecig(), Character::estimate_effect_dur(), heal_actor::finish_using(), Character::hardcoded_effects(), Character::hearing_ability(), Character::introduce_into_anesthesia(), iuse::jet_injector(), anonymous_namespace{messages.cpp}::messages_impl::modify_msg_with_exclamations(), monster::nursebot_operate(), activity_handlers::operation_do_turn(), monexamine::pay_bot(), iuse::prozac(), iuse::smoking(), iuse::thorazine(), Character::update_heartrate_index(), heal_actor::use_healing_item(), weed_msg(), and debug_menu::wisheffect().
get_effect_int()
int Creature::get_effect_int (const efftype_id & eff_id, const bodypart_id & bp = bodypart_str_id::NULL_ID()) const
Returns the intensity of the matching effect.
Returns 0 if effect doesn't exist.
Definition at line 1872 of file creature.cpp.
 {
     const effect &eff = get_effect( eff_id, bp );
     if( !eff.is_null() ) {
         return eff.get_intensity();
     }
     return 0;
 }
References bp, get_effect(), effect::get_intensity(), and effect::is_null().
Referenced by npc::address_player(), mattack::bio_op_takedown(), Character::bionics_adjusted_skill(), Character::body_window(), Character::check_needs_extremes(), heal_actor::finish_using(), Character::get_perceived_pain(), Character::is_deaf(), Character::is_mute(), game::mon_info_update(), Character::most_staunchable_bp(), monster::move_effects(), Character::process_turn(), mattack::resurrect(), Character::try_remove_grab(), Character::try_remove_impeding_effect(), Character::try_remove_webs(), Character::update_bodytemp(), Character::update_frostbite(), Character::update_heartrate_index(), musical_instrument_actor::use(), heal_actor::use_healing_item(), Character::vomit_mod(), and outfit::warmth().
get_effects()
std::vector< std::reference_wrapper< const effect > > Creature::get_effects () const
Definition at line 1823 of file creature.cpp.
 {
     std::vector<std::reference_wrapper<const effect>> effs;
     for( auto &elem : *effects ) {
         for( const std::pair<const bodypart_id, effect> &_it : elem.second ) {
             effs.emplace_back( _it.second );
         }
     }
     return effs;
 }
References effects.
Referenced by Character::on_damage_of_type(), and outfit::prepare_bodymap_info().
get_effects_from_bp()
std::vector< std::reference_wrapper< const effect > > Creature::get_effects_from_bp (const bodypart_id & bp) const
Definition at line 1834 of file creature.cpp.
 {
     std::vector<std::reference_wrapper<const effect>> effs;
     for( auto &elem : *effects ) {
         const auto iter = elem.second.find( bp );
         if( iter != elem.second.end() ) {
             effs.emplace_back( iter->second );
         }
     }
     return effs;
 }
References bp, and effects.
Referenced by Character::count_bodypart_with_flag(), get_encumbrance_description(), Character::get_limb_score(), Character::has_bodypart_with_flag(), and Character::manipulator_score().
get_effects_with_flag()
std::vector< std::reference_wrapper< const effect > > Creature::get_effects_with_flag (const flag_id & flag) const
Definition at line 1808 of file creature.cpp.
 {
     std::vector<std::reference_wrapper<const effect>> effs;
     for( auto &elem : *effects ) {
         if( !elem.first->has_flag( flag ) ) {
             continue;
         }
         for( const std::pair<const bodypart_id, effect> &_it : elem.second ) {
             effs.emplace_back( _it.second );
         }
     }
     return effs;
 }
References effects.
Referenced by melee_actor::call(), monster::die(), get_encumbrance_description(), Character::get_limb_score(), Character::item_handling_cost(), monster::move_effects(), monster::nursebot_operate(), Character::perform_technique(), monster::process_turn(), teleport::teleport_to_point(), Character::try_remove_grab(), and Character::try_remove_impeding_effect().
get_env_resist()
int Creature::get_env_resist (bodypart_id bp) const virtual
Reimplemented in Character.
Definition at line 2114 of file creature.cpp.
 {
     return 0;
 }
Referenced by add_env_effect().
get_grammatical_genders()
std::vector< std::string > Creature::get_grammatical_genders () const virtual
Reimplemented in Character.
Definition at line 214 of file creature.cpp.
 {
     // Returning empty list means we use the language-specified default
     return {};
 }
get_hit()
float Creature::get_hit () const virtual
Definition at line 2152 of file creature.cpp.
 {
     return get_hit_base() + get_hit_bonus();
 }
References get_hit_base(), and get_hit_bonus().
Referenced by dodge_check(), monster::hit_roll(), and monster::melee_attack().
get_hit_base()
virtual float Creature::get_hit_base () const pure virtual
Implemented in monster, and Character.
Referenced by get_hit().
get_hit_bonus()
float Creature::get_hit_bonus () const virtual
Definition at line 2798 of file creature.cpp.
 {
     return hit_bonus; //base is 0
 }
References hit_bonus.
Referenced by get_hit().
get_hp() [1/2]
int Creature::get_hp () const virtual
Reimplemented in monster.
Definition at line 2760 of file creature.cpp.
 {
     return get_hp( bodypart_str_id::NULL_ID() );
 }
References string_id< body_part_type >::NULL_ID().
Referenced by deal_damage().
get_hp() [2/2]
int Creature::get_hp (const bodypart_id & bp) const virtual
Reimplemented in monster.
Definition at line 2748 of file creature.cpp.
 {
     if( bp != bodypart_str_id::NULL_ID() ) {
         return get_part_hp_cur( bp );
     }
     int hp_total = 0;
     for( const std::pair<const bodypart_str_id, bodypart> &elem : get_body() ) {
         hp_total += elem.second.get_hp_cur();
     }
     return hp_total;
 }
References bp, get_body(), get_part_hp_cur(), and string_id< body_part_type >::NULL_ID().
Referenced by damage_targets(), npc_attack_melee::evaluate_critter(), npc_attack_spell::evaluate_tripoint(), npc_attack_gun::evaluate_tripoint(), npc_attack_throw::evaluate_tripoint(), talker_character_const::get_cur_hp(), game::list_monsters(), game::place_player(), and player_hit_message().
get_hp_max() [1/2]
int Creature::get_hp_max () const virtual
Reimplemented in monster.
Definition at line 2777 of file creature.cpp.
 {
     return get_hp_max( bodypart_str_id::NULL_ID() );
 }
References string_id< body_part_type >::NULL_ID().
Referenced by Character::add_msg_player_or_say(), Character::deal_damage(), and select_body_part_projectile_attack().
get_hp_max() [2/2]
int Creature::get_hp_max (const bodypart_id & bp) const virtual
Reimplemented in monster.
Definition at line 2765 of file creature.cpp.
 {
     if( bp != bodypart_str_id::NULL_ID() ) {
         return get_part_hp_max( bp );
     }
     int hp_total = 0;
     for( const std::pair<const bodypart_str_id, bodypart> &elem : get_body() ) {
         hp_total += elem.second.get_hp_max();
     }
     return hp_total;
 }
References bp, get_body(), get_part_hp_max(), and string_id< body_part_type >::NULL_ID().
Referenced by weakpoint_effect::apply_to(), spell::energy_cost_string(), talker_character_const::get_hp_max(), start_location::handle_heli_crash(), game::list_monsters(), and player_hit_message().
get_killer()
Creature * Creature::get_killer () const virtual
Definition at line 2026 of file creature.cpp.
 {
     return killer;
 }
References killer.
Referenced by effect_on_conditions::avatar_death(), monster::die(), and spell_effect::guilt().
get_location()
tripoint_abs_ms Creature::get_location () const
Returns the location of the creature in map square coordinates (the most detailed coordinate system), relative to a fixed global point of origin.
Definition at line 3232 of file creature.cpp.
 {
     return location;
 }
References location.
Referenced by anonymous_namespace{math_parser_diag.cpp}::_filter_character(), anonymous_namespace{math_parser_diag.cpp}::_filter_monster(), Character::activate_bionic(), activity_on_turn_move_loot(), creature_tracker::add(), add_fallback_zone(), jmapgen_remove_npcs::apply(), monster::attitude(), talk_function::basecamp_mission(), map::build_map_cache(), Character::burn_fuel(), zone_manager::cache_avatar_location(), zone_manager::cache_data(), leap_actor::call(), mattack::callblobs(), npc::can_do_pulp(), consume_items_in_zones(), game::create_starting_npcs(), creature_tracker::creature_at(), iuse::directional_hologram(), distribute_items_to_npc_zones(), glide_activity_actor::do_turn(), unload_loot_activity_actor::do_turn(), mattack::dsa_drone_scan(), iexamine::elevator(), npc::execute_action(), npc::find_corpse_to_pulp(), npc::find_item(), iexamine::flower_poppy(), Character::get_active_moncams(), monster::get_dest(), talker_character_const::global_pos(), talker_monster_const::global_pos(), npc::go_to_omt_destination(), npc::good_escape_direction(), mattack::grow_vine(), npc::guard_current_pos(), npc::handle_sound(), monster::hear_sound(), npc::import_and_clean(), mattack::jackson(), creature_tracker::kill_marked_for_death(), monster::know_danger_at(), longpull(), monster::move(), npc::move(), move_to(), mattack::nurse_operate(), monster::nursebot_operate(), npc::on_move(), game::peek(), perform_zone_activity_turn(), mattack::photograph(), map::pl_sees(), monster::plan(), posz(), npc::reach_omt_destination(), basecamp::recruit_return(), npc::regen_ai_cache(), creature_tracker::remove_from_location_map(), requirements_map(), map::rotate(), npc::set_unique_id(), setpos(), mattack::smash_specific(), debug_menu::spawn_npc(), game::start_game(), creature_tracker::swap_positions(), trade_ui::trade_ui(), editmap::uber_draw_ter(), Character::update_bodytemp(), weather_manager::update_weather(), basecamp::validate_sort_points(), game::vertical_move(), game::vertical_shift(), mattack::vine(), iuse::weather_tool(), monster::will_reach(), npc::worker_downtime(), and game::zones_manager().
get_max_hitsize_bodypart()
bodypart_id Creature::get_max_hitsize_bodypart () const
Definition at line 3008 of file creature.cpp.
 {
     return anatomy( get_all_body_parts() ).get_max_hitsize_bodypart();
 }
References get_all_body_parts(), and anatomy::get_max_hitsize_bodypart().
Referenced by damage_targets().
get_melee()
virtual float Creature::get_melee () const pure virtual
Implemented in monster, and Character.
Referenced by deal_melee_attack().
get_melee_quiet()
bool Creature::get_melee_quiet () const virtual
Definition at line 2820 of file creature.cpp.
 {
     return melee_quiet;
 }
References melee_quiet.
get_monster_faction()
virtual mfaction_id Creature::get_monster_faction () const pure virtual
Implemented in npc, monster, and avatar.
get_moves()
int Creature::get_moves () const
Definition at line 2004 of file creature.cpp.
 {
     return moves;
 }
References moves.
Referenced by mattack::absorb_items(), target_ui::action_aim(), target_ui::action_aim_and_shoot(), activity_on_turn_move_loot(), activity_handlers::build_do_turn(), spell_effect::dash(), advanced_inventory::display(), do_aim(), vehicle::do_autodrive(), Pickup::do_pickup(), player_activity::do_turn(), autodrive_activity_actor::do_turn(), disassemble_activity_actor::do_turn(), wear_activity_actor::do_turn(), wield_activity_actor::do_turn(), craft_activity_actor::do_turn(), move_items_activity_actor::do_turn(), unload_loot_activity_actor::do_turn(), Character::evaluate_techniques(), generic_multi_activity_handler(), widget::get_var_value(), game::handle_action(), avatar::invoke_item(), obtain_activity_items(), perform_zone_activity_turn(), vehicle::pldrive(), activity_handlers::pulp_do_turn(), activity_handlers::repair_item_do_turn(), mattack::resurrect(), outfit::sort_armor(), mattack::split(), activity_handlers::start_fire_do_turn(), vehicle::turrets_aim(), aim_activity_actor::unload_RAS_weapon(), Character::use(), avatar_action::use_item(), and game::walk_move().
get_name()
virtual std::string Creature::get_name () const pure virtual
Implemented in monster, and Character.
Referenced by projectile::apply_effects_damage(), weakpoint_effect::apply_to(), vehicle::can_close(), doors::close_door(), deal_damage_handle_type(), get_part(), get_part_id(), get_talker_for(), Character::perform_technique(), monster::process_turn(), and projectile_attack().
get_num_blocks()
int Creature::get_num_blocks () const virtual
Definition at line 2083 of file creature.cpp.
 {
     return num_blocks + num_blocks_bonus;
 }
References num_blocks, and num_blocks_bonus.
Referenced by Character::process_turn().
get_num_blocks_base()
int Creature::get_num_blocks_base () const virtual
Definition at line 2103 of file creature.cpp.
 {
     return num_blocks;
 }
References num_blocks.
Referenced by enchant_cache::activate_passive().
get_num_blocks_bonus()
int Creature::get_num_blocks_bonus () const virtual
Definition at line 2093 of file creature.cpp.
 {
     return num_blocks_bonus;
 }
References num_blocks_bonus.
get_num_body_parts_of_type()
int Creature::get_num_body_parts_of_type (body_part_type::type part_type) const
Definition at line 2732 of file creature.cpp.
 {
     return static_cast<int>( get_all_body_parts_of_type( part_type ).size() );
 }
References get_all_body_parts_of_type().
Referenced by Character::most_staunchable_bp().
get_num_broken_body_parts_of_type()
int Creature::get_num_broken_body_parts_of_type (body_part_type::type part_type) const
Definition at line 2737 of file creature.cpp.
 {
     int ret = 0;
     for( const bodypart_id &bp : get_all_body_parts_of_type( part_type ) ) {
         if( get_part_hp_cur( bp ) == 0 ) {
             ret++;
         }
     }
     return ret;
 }
References bp, get_all_body_parts_of_type(), get_part_hp_cur(), and cata::hash64_detail::ret.
Referenced by Character::most_staunchable_bp(), and Character::pause().
get_num_dodges()
int Creature::get_num_dodges () const virtual
Definition at line 2088 of file creature.cpp.
 {
     return num_dodges + num_dodges_bonus;
 }
References num_dodges, and num_dodges_bonus.
Referenced by Character::process_turn().
get_num_dodges_base()
int Creature::get_num_dodges_base () const virtual
Definition at line 2108 of file creature.cpp.
 {
     return num_dodges;
 }
References num_dodges.
Referenced by enchant_cache::activate_passive().
get_num_dodges_bonus()
int Creature::get_num_dodges_bonus () const virtual
Definition at line 2098 of file creature.cpp.
 {
     return num_dodges_bonus;
 }
References num_dodges_bonus.
get_pain()
int Creature::get_pain () const virtual
Definition at line 1994 of file creature.cpp.
 {
     return pain;
 }
References pain.
Referenced by npc::act_on_danger_assessment(), Character::burn_move_stamina(), Character::check_and_recover_morale(), npc::evaluate_self(), suffer::from_other_mutations(), get_perceived_pain(), Character::get_perceived_pain(), npc::has_painkiller(), talker_character_const::pain_cur(), talker_monster_const::pain_cur(), tutorial_game::per_turn(), Character::process_bionic(), Character::process_one_effect(), sounds::process_sound_markers(), npc::process_turn(), Character::regen(), and npc::use_painkiller().
get_part() [1/2]
bodypart * Creature::get_part (const bodypart_id & id)
Definition at line 2185 of file creature.cpp.
 {
     auto found = body.find( get_part_id( id ).id() );
     if( found == body.end() ) {
         debugmsg( "Could not find bodypart %s in %s's body", id.id().c_str(), get_name() );
         return nullptr;
     }
     return &found->second;
 }
References body, debugmsg, get_name(), and get_part_id().
Referenced by Character::block_hit(), character_martial_arts::can_arm_block(), character_martial_arts::can_leg_block(), character_martial_arts::can_nonstandard_block(), Character::count_bodypart_with_flag(), get_encumbrance_description(), Character::get_limb_techs(), Character::get_working_arm_count(), Character::on_damage_of_type(), and game::slip_down_chance().
get_part() [2/2]
const bodypart * Creature::get_part (const bodypart_id & id) const
Definition at line 2195 of file creature.cpp.
 {
     auto found = body.find( get_part_id( id ).id() );
     if( found == body.end() ) {
         debugmsg( "Could not find bodypart %s in %s's body", id.id().c_str(), get_name() );
         return nullptr;
     }
     return &found->second;
 }
References body, debugmsg, get_name(), and get_part_id().
get_part_damage_bandaged()
int Creature::get_part_damage_bandaged (const bodypart_id & id) const
Definition at line 2297 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_damage_bandaged );
 }
References bodypart::get_damage_bandaged(), and get_part_helper().
Referenced by Character::regen().
get_part_damage_disinfected()
int Creature::get_part_damage_disinfected (const bodypart_id & id) const
Definition at line 2292 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_damage_disinfected );
 }
References bodypart::get_damage_disinfected(), and get_part_helper().
Referenced by Character::regen().
get_part_drench_capacity()
int Creature::get_part_drench_capacity (const bodypart_id & id) const
Definition at line 2307 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_drench_capacity );
 }
References bodypart::get_drench_capacity(), and get_part_helper().
Referenced by Character::drench(), Character::process_one_effect(), and Character::update_body_wetness().
get_part_encumbrance_data()
const encumbrance_data & Creature::get_part_encumbrance_data (const bodypart_id & id) const
Definition at line 2302 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_encumbrance_data );
 }
References bodypart::get_encumbrance_data(), and get_part_helper().
Referenced by Character::encumb(), widget::get_var_value(), item::on_wear(), Character::print_encumbrance(), and should_combine_bps().
get_part_frostbite_timer()
int Creature::get_part_frostbite_timer (const bodypart_id & id) const
Definition at line 2327 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_frostbite_timer );
 }
References bodypart::get_frostbite_timer(), and get_part_helper().
Referenced by Character::update_bodytemp(), and Character::update_frostbite().
get_part_healed_total()
int Creature::get_part_healed_total (const bodypart_id & id) const
Definition at line 2287 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_healed_total );
 }
References bodypart::get_healed_total(), and get_part_helper().
get_part_hp_cur()
int Creature::get_part_hp_cur (const bodypart_id & id) const
Definition at line 2277 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_hp_cur );
 }
References bodypart::get_hp_cur(), and get_part_helper().
Referenced by Character::apply_damage(), iexamine::autodoc(), spell_effect::banishment(), blood_magic(), Character::body_window(), character_martial_arts::can_use_attack_vector(), debug_menu::character_edit_hp_menu(), debug_menu::damage_self(), dodge_check(), Character::extended_description(), heal_actor::finish_using(), get_hp(), get_num_broken_body_parts_of_type(), talker_character::get_part_hp_cur(), widget::get_var_value(), iuse::granade_act(), Character::heal(), Character::hp_percentage(), Character::hurtall(), Character::is_dead_state(), Character::is_limb_broken(), Character::mod_part_hp_cur(), Character::on_damage_of_type(), Character::on_hurt(), pick_part_to_heal(), outfit::prepare_bodymap_info(), Character::prevent_death(), Character::roll_critical_bionics_failure(), Character::set_part_hp_cur(), should_combine_bps(), and heal_actor::use_healing_item().
get_part_hp_max()
int Creature::get_part_hp_max (const bodypart_id & id) const
Definition at line 2282 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_hp_max );
 }
References bodypart::get_hp_max(), and get_part_helper().
Referenced by iexamine::autodoc(), blood_magic(), Character::body_window(), draw_stats_info(), Character::extended_description(), heal_actor::finish_using(), get_hp_max(), talker_character::get_part_hp_max(), iuse::granade_act(), Character::heal(), Character::hp_percentage(), pick_part_to_heal(), outfit::prepare_bodymap_info(), widget::set_default_var_range(), and heal_actor::use_healing_item().
get_part_id()
bodypart_id Creature::get_part_id (const bodypart_id & id, body_part_filter filter = body_part_filter::next_best, bool suppress_debugmsg = false) const
Definition at line 2240 of file creature.cpp.
 {
     auto found = body.find( id.id() );
     if( found != body.end() ) {
         return found->first;
     }
     // try to find an equivalent part in the body map
     if( filter >= body_part_filter::equivalent ) {
         for( const std::pair<const bodypart_str_id, bodypart> &bp : body ) {
             if( id->part_side == bp.first->part_side &&
                 id->primary_limb_type() == bp.first->primary_limb_type() ) {
                 return bp.first;
             }
         }
     }
     // try to find the next best thing
     std::pair<bodypart_id, float> best = { body_part_bp_null, 0.0f };
     if( filter >= body_part_filter::next_best ) {
         for( const std::pair<const bodypart_str_id, bodypart> &bp : body ) {
             for( const std::pair<const body_part_type::type, float> &mp : bp.first->limbtypes ) {
                 // if the secondary limb type matches and is better than the current
                 if( mp.first == id->primary_limb_type() && mp.second > best.second ) {
                     // give an inflated bonus if the part sides match
                     float bonus = id->part_side == bp.first->part_side ? 1.0f : 0.0f;
                     best = { bp.first, mp.second + bonus };
                 }
             }
         }
     }
     if( best.first == body_part_bp_null && !suppress_debugmsg ) {
         debugmsg( "Could not find equivalent bodypart id %s in %s's body", id.id().c_str(), get_name() );
     }
     return best.first;
 }
References body, body_part_bp_null, bp, debugmsg, equivalent, filter, get_name(), base_camps::id, body_part_type::limbtypes, next_best, body_part_type::part_side, and body_part_type::primary_limb_type().
Referenced by get_part(), and has_part().
get_part_mut_drench()
std::array< int, NUM_WATER_TOLERANCE > Creature::get_part_mut_drench (const bodypart_id & id) const
Definition at line 2332 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_mut_drench );
 }
References bodypart::get_mut_drench(), and get_part_helper().
Referenced by Character::apply_wetness_morale().
get_part_temp_conv()
units::temperature Creature::get_part_temp_conv (const bodypart_id & id) const
Definition at line 2322 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_temp_conv );
 }
References get_part_helper(), and bodypart::get_temp_conv().
Referenced by talker_character_const::get_body_temp_delta(), talker_character_const::get_cur_part_temp(), behavior::character_oracle_t::needs_warmth_badly(), outfit::prepare_bodymap_info(), Character::print_encumbrance(), should_combine_bps(), Character::update_body_wetness(), and Character::update_bodytemp().
get_part_temp_cur()
units::temperature Creature::get_part_temp_cur (const bodypart_id & id) const
Definition at line 2317 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_temp_cur );
 }
References get_part_helper(), and bodypart::get_temp_cur().
Referenced by Character::apply_wetness_morale(), Character::calc_sleep_recovery_rate(), talker_character_const::get_body_temp(), talker_character_const::get_body_temp_delta(), widget::get_var_value(), Character::temp_equalizer(), Character::update_bodytemp(), and Character::update_frostbite().
get_part_wetness()
int Creature::get_part_wetness (const bodypart_id & id) const
Definition at line 2312 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_wetness );
 }
References get_part_helper(), and bodypart::get_wetness().
Referenced by Character::apply_wetness_morale(), Character::drench(), widget::get_var_value(), Character::process_one_effect(), game::slip_down_chance(), and Character::update_body_wetness().
get_part_wetness_percentage()
float Creature::get_part_wetness_percentage (const bodypart_id & id) const
Definition at line 2337 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::get_wetness_percentage );
 }
References get_part_helper(), and bodypart::get_wetness_percentage().
Referenced by outfit::prepare_bodymap_info(), Character::update_body_wetness(), Character::update_frostbite(), outfit::warmth(), and wet_character().
get_path_avoid()
virtual std::unordered_set<tripoint> Creature::get_path_avoid () const pure virtual
Returns a set of points we do not want to path through.
Implemented in npc, monster, and Character.
get_pathfinding_settings()
virtual const pathfinding_settings& Creature::get_pathfinding_settings () const pure virtual
Returns settings for pathfinding.
Implemented in npc, monster, and Character.
get_perceived_pain()
int Creature::get_perceived_pain () const virtual
Reimplemented in Character.
Definition at line 1999 of file creature.cpp.
 {
     return get_pain();
 }
References get_pain().
Referenced by talker_monster_const::perceived_pain_cur().
get_random_body_part()
bodypart_id Creature::get_random_body_part (bool main = false) const
Definition at line 2506 of file creature.cpp.
 {
     // TODO: Refuse broken limbs, adjust for mutations
     const bodypart_id &part = get_anatomy()->random_body_part();
     return main ? part->main_part.id() : part;
 }
References get_anatomy(), string_id< T >::id(), main(), body_part_type::main_part, and anatomy::random_body_part().
Referenced by mattack::acid_barf(), mattack::bio_op_impale(), mattack::dermatik(), field_processor_fd_push_items(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::lunge(), game::place_player(), mattack::stretch_attack(), and mattack::vine().
get_random_body_part_of_type()
bodypart_id Creature::get_random_body_part_of_type (body_part_type::type part_type) const
Definition at line 2686 of file creature.cpp.
 {
     return random_entry( get_all_body_parts_of_type( part_type ) );
 }
References get_all_body_parts_of_type(), and random_entry().
Referenced by mattack::bio_op_impale(), map::drop_items(), vehicle::part_collision(), and suffer::while_grabbed().
get_reachable_zone()
int Creature::get_reachable_zone () const inline
Definition at line 764 of file creature.h.
{
             return reachable_zone;
         }
References reachable_zone.
Referenced by creature_tracker::swap_positions().
get_root_body_part()
bodypart_id Creature::get_root_body_part () const
Definition at line 2648 of file creature.cpp.
 {
     for( const bodypart_id &part : get_all_body_parts() ) {
         if( part->connected_to == part->id ) {
             return part;
         }
     }
     debugmsg( "ERROR: character has no root part" );
     return body_part_head;
 }
References body_part_head, debugmsg, and get_all_body_parts().
Referenced by draw_stats_info(), and wet_character().
get_size()
virtual creature_size Creature::get_size () const pure virtual
Implemented in monster, and Character.
Referenced by describe_infrared(), glide_activity_actor::do_turn(), map::drop_items(), Character::echo_pulse(), mod_size_bonus(), ranged_target_size(), Character::reach_attack(), sees(), size_melee_penalty(), iuse::tazer(), and weight_capacity().
get_speed()
int Creature::get_speed () const virtual
Reimplemented in Character.
Definition at line 2138 of file creature.cpp.
 {
     return get_speed_base() + get_speed_bonus();
 }
References get_speed_base(), and get_speed_bonus().
Referenced by monster::bash_at(), trapfunc::board(), trapfunc::caltrops(), trapfunc::caltrops_glass(), iuse::can_goo(), monster::extended_description(), Character::get_speed(), trapfunc::glass(), trapfunc::goo(), mattack::kamikaze(), mattack::lunge(), monster::move(), overmap::move_hordes(), monster::move_to(), process_turn(), monster::speed_rating(), vehicle::thrust(), trapfunc::tripwire(), and monster::turns_to_reach().
get_speed_base()
int Creature::get_speed_base () const virtual
Definition at line 2782 of file creature.cpp.
 {
     return speed_base;
 }
References speed_base.
Referenced by blobify(), iuse::can_goo(), iuse::extinguisher(), mattack::formblob(), get_speed(), Character::get_speed(), trapfunc::glow(), trapfunc::goo(), iuse::granade_act(), monster::init_from_item(), monster::on_load(), poly_keep_speed(), monster::process_effects(), monster::process_one_effect(), Character::recalc_speed_bonus(), mattack::resurrect(), widget::set_default_var_range(), and spell_effect::slime_split_on_death().
get_speed_bonus()
int Creature::get_speed_bonus () const virtual
Definition at line 2786 of file creature.cpp.
 {
     return speed_bonus;
 }
References speed_bonus.
Referenced by get_speed(), Character::get_speed(), monster::process_effects(), and Character::recalc_speed_bonus().
get_spell_resist()
int Creature::get_spell_resist () const virtual
Reimplemented in Character.
Definition at line 2132 of file creature.cpp.
 {
     // TODO: add spell resistance to monsters, then make this pure virtual
     return 0;
 }
Referenced by damage_targets().
get_summoner()
Creature * Creature::get_summoner () const
Definition at line 2060 of file creature.cpp.
 {
     if( !summoner ) {
         return nullptr;
     } else if( summoner.value() == get_player_character().getID() ) {
         return &get_player_character();
     } else {
         return g->find_npc( summoner.value() );
     }
 }
References g, get_player_character(), and summoner.
Referenced by monster::die().
get_throw_resist()
int Creature::get_throw_resist () const virtual
Definition at line 2825 of file creature.cpp.
 {
     return throw_resist;
 }
References throw_resist.
Referenced by Character::perform_technique().
get_value()
std::string Creature::get_value (const std::string & key) const
Definition at line 1959 of file creature.cpp.
 {
     return maybe_get_value( key ).value_or( std::string{} );
 }
References maybe_get_value().
Referenced by Character::activate_bionic(), check_stealing(), talk_function::companion_mission(), Character::deactivate_bionic(), npc::do_npc_read(), game::do_regular_action(), pickup_activity_actor::do_turn(), Character::drench(), mattack::dsa_drone_scan(), talk_function::field_harvest(), consume_activity_actor::finish(), vehicle::get_next_shifted_index(), Character::mod_stamina(), pick_one_up(), Character::process_bionic(), query_consume_ownership(), iuse::radiocontrol_tick(), rcdrive(), avatar::read(), game::remoteveh(), Character::restore_scent(), and Character::update_body().
get_values()
std::unordered_map< std::string, std::string > & Creature::get_values ()
Definition at line 3003 of file creature.cpp.
 {
     return values;
 }
References values.
get_weight()
virtual units::mass Creature::get_weight () const pure virtual
Implemented in monster, and Character.
Referenced by melee_actor::do_grab(), and vehicle::part_collision().
gibType()
virtual field_type_id Creature::gibType () const pure virtual
Implemented in monster, and Character.
global_omt_location()
tripoint_abs_omt Creature::global_omt_location () const
Returns the location of the creature in global overmap terrain coordinates.
Definition at line 3242 of file creature.cpp.
 {
     return project_to<coords::omt>( location );
 }
References location.
Referenced by talk_function::abandon_camp(), computer_session::action_emerg_ref_center(), computer_session::action_map_sewer(), computer_session::action_map_subway(), computer_session::action_maps(), Character::activate_bionic(), Character::activate_mutation(), mission_data::add(), memorial_logger::add(), Character::apply_persistent_morale(), talk_function::assign_camp(), talk_function::basecamp_mission(), Character::burn_fuel(), talk_function::caravan_dist(), ui::omap::choose_point(), widget::color_text_function_string(), talk_function::companion_choose(), talk_function::companion_choose_return(), talk_function::companion_list(), talk_function::companion_mission(), npc::consume_food_from_camp(), mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), mission_start::create_lab_console(), debug_menu::debug_menu_game_state(), overmapbuffer::despawn_monster(), game::disp_NPCs(), item::display_name(), ui::omap::display_visible_weather(), ui::omap::display_weather(), talker_npc::distance_to_goal(), overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_notes(), mission_ui_impl::draw_selected_description(), drop_on_map(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal(), basecamp::faction_display(), npc::faction_display(), talk_function::field_harvest(), talk_function::field_plant(), mission_start::find_safety(), overmapbuffer::fix_npcs(), get_basecamp(), get_mission_om_origin(), overmapbuffer::get_npcs_near_omt(), overmap_ui::get_overmap_path_to(), talker_character_const::global_omt_location(), talker_furniture::global_omt_location(), talker_item_const::global_omt_location(), talker_monster_const::global_omt_location(), npc::go_to_omt_destination(), talk_function::goto_location(), npc::guard_current_pos(), talk_function::hospital_raid_return(), talk_function::individual_mission(), mission::is_complete(), mission_start::kill_nemesis(), spell_effect::map(), trapfunc::map_regen(), display::mission_arrow_offset(), npc::move(), Character::overmap_los(), game::perhaps_add_random_npc(), mission_start::place_deposit_box(), mission_start::place_npc_software(), Character::process_turn(), mission_util::random_house_in_closest_city(), npc::reach_omt_destination(), teleporter_callback::refresh(), npc::regen_ai_cache(), game::reset_npc_dispositions(), reveal_destination(), mission_util::reveal_om_ter(), reveal_route(), talk_function::scavenging_raid_return(), npc::set_companion_mission(), npc::set_omt_destination(), monster::set_patrol_route(), mission::set_target_to_mission_giver(), Character::signal_nemesis(), talk_function::start_camp(), game::start_game(), mission_util::target_om_ter_random(), debug_menu::teleport_overmap(), activity_handlers::travel_do_turn(), npc::travel_overmap(), activity_handlers::tree_communion_do_turn(), Character::update_bodytemp(), game::update_overmap_seen(), reveal_map_actor::use(), game::vertical_notes(), iuse::weather_tool(), npc::within_boundaries_of_camp(), and game::zones_manager().
global_sm_location()
tripoint_abs_sm Creature::global_sm_location () const
Returns the location of the creature in global submap coordinates.
Definition at line 3237 of file creature.cpp.
 {
     return project_to<coords::sm>( location );
 }
References location.
Referenced by timed_event::actualize(), overmapbuffer::despawn_monster(), iuse::directional_antenna(), npc::faction_display(), overmapbuffer::find_all_radio_stations(), overmapbuffer::find_radio_station(), overmapbuffer::get_npcs_near(), overmapbuffer::move_hordes(), overmapbuffer::process_mongroups(), and mission_util::random_house_in_closest_city().
has_atleast_one_wet_part()
bool Creature::has_atleast_one_wet_part () const
Definition at line 2491 of file creature.cpp.
 {
     for( const std::pair<const bodypart_str_id, bodypart> &elem : body ) {
         if( elem.second.get_wetness() > 0 ) {
             return true;
         }
     }
     return false;
 }
References body.
Referenced by Character::apply_wetness_morale(), and iuse::towel_common().
has_effect() [1/2]
bool Creature::has_effect (const efftype_id & eff_id) const
Definition at line 1787 of file creature.cpp.
 {
     return has_effect( eff_id, bodypart_str_id::NULL_ID() );
 }
References has_effect(), and string_id< body_part_type >::NULL_ID().
has_effect() [2/2]
bool Creature::has_effect (const efftype_id & eff_id, const bodypart_id & bp) const
Check if creature has the matching effect.
If the bodypart is not specified check if the Creature has any effect of the matching type, targeted or untargeted.
Definition at line 1770 of file creature.cpp.
 {
     // bp_null means anything targeted or not
     if( bp.id() == bodypart_str_id::NULL_ID() ) {
         return effects->count( eff_id );
     } else {
         auto got_outer = effects->find( eff_id );
         if( got_outer != effects->end() ) {
             auto got_inner = got_outer->second.find( bp.id() );
             if( got_inner != got_outer->second.end() ) {
                 return true;
             }
         }
         return false;
     }
 }
References bp, effects, int_id< T >::id(), and string_id< body_part_type >::NULL_ID().
Referenced by npc::act_on_danger_assessment(), vehicle::activate_animal_follow(), Character::active_light(), add_effect(), anonymous_namespace{monexamine.cpp}::add_leash(), Character::add_msg_player_or_say(), iuse::adrenaline_injector(), iuse::antibiotic(), iuse::anticonvulsant(), iuse::antifungal(), iuse::antiparasitic(), map::apply_character_light(), Character::apply_damage(), npc::assess_danger(), anonymous_namespace{monexamine.cpp}::attach_saddle_to(), monster::attack_at(), Character::attack_speed(), monster::attitude(), iexamine::autodoc(), Character::base_comfort_value(), avatar::basic_symbol_color(), best_installer(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), Character::block_hit(), trapfunc::board(), Character::body_window(), mattack::boomer_glow(), map::build_vision_transparency_cache(), trapfunc::caltrops(), monster::can_act(), disable_activity_actor::can_disable_or_reprogram(), Character::can_eat(), Character::can_fly(), monster::can_hear(), Character::can_mount(), Character::can_run(), Character::can_sleep(), Character::can_try_doge(), Character::can_use(), repair_item_actor::can_use_tool(), Character::can_wear(), Character::can_wield(), Character::cast_spell(), game::chat(), mattack::check_money_left(), Character::check_needs_extremes(), Character::check_read_condition(), game::check_safe_mode_allowed(), check_water_affect_items(), monster::color_with_effects(), npc::complain(), Character::consume_effects(), vehicle::consume_fuel(), Character::cough(), map::creature_on_trap(), vehicle::damage_direct(), Character::deal_damage(), deal_melee_hit(), monster::die(), Character::die(), monster::digest_food(), game::disable_robot(), trapfunc::dissector(), game::do_regular_action(), player_activity::do_turn(), try_sleep_activity_actor::do_turn(), stash_activity_actor::do_turn(), Character::drench(), eat(), avatar_action::eat_here(), iuse::ebookread(), iuse::ebooksave(), Character::echo_pulse(), iuse::einktabletpc(), iuse::electricstorage(), explosion_handler::emp_blast(), npc::evaluate_character(), npc::evaluate_self(), game::examine(), npc::execute_action(), iuse::eyedrops(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), monster::find_dragged_foe(), activity_handlers::find_mount_do_turn(), game::find_or_make_stairs(), Character::fine_detail_vision_mod(), try_sleep_activity_actor::finish(), disable_activity_actor::finish(), heal_actor::finish_using(), Character::fire_gun(), mattack::frag(), suffer::from_asthma(), suffer::from_bad_bionics(), suffer::from_chemimbalance(), suffer::from_item_dropping(), suffer::from_nyctophobia(), suffer::from_other_mutations(), suffer::from_stimulants(), suffer::from_sunburn(), Character::fun_for(), iuse::fungicide(), Character::get_dodge(), monster::get_dodge(), vehicle::get_harnessed_animal(), Character::get_miss_reason(), npc::get_opinion_values(), Character::get_recipe_weighted_skill_average(), Character::get_sick(), talker_npc::get_topics(), Character::get_total_melee_stamina_cost(), monster::get_worn_armor_val(), talk_function::give_aid(), glare(), trapfunc::glow(), trapfunc::goo(), Character::hardcoded_effects(), has_effect(), talker_character_const::has_effect(), talker_monster_const::has_effect(), monster::has_weapon(), npc::heal_self(), Character::healing_rate_medicine(), Character::hearing_ability(), Character::hit_roll(), monster::hit_roll(), Character::hoarder_morale_penalty(), Character::hurtall(), Character::immune_to(), in_sleep_state(), suffer::in_sunlight(), npc::indoor_voice(), Character::intimidation(), Character::introduce_into_anesthesia(), Character::irradiate(), Character::is_deaf(), monster::is_grabbing(), Character::is_hibernating(), Character::is_immune_field(), Character::is_mounted(), Character::is_on_ground(), monster::is_pet(), npc::is_stationary(), iuse::jet_injector(), mattack::kamikaze(), game::knockback(), trapfunc::lava(), trapfunc::ledge(), talk_function::lesser_give_aid(), make_mon_corpse(), iuse::melatonin_tablet(), Character::melee_attack(), monster::melee_attack(), Character::melee_attack_abstract(), Character::mend(), iuse::meth(), anonymous_namespace{monexamine.cpp}::milk_source(), mine_activity(), Character::mod_pain(), anonymous_namespace{messages.cpp}::messages_impl::modify_msg_with_exclamations(), game::mon_info_update(), monster_plan::monster_plan(), talk_function::morale_chat_activity(), Character::mount_creature(), monster::move(), npc::move(), avatar_action::move(), Character::move_effects(), monster::move_effects(), Character::move_in_vehicle(), npc::move_pause(), monster::move_to(), npc::move_to(), iuse::multicooker(), monster::name_with_armor(), npc::npc_dismount(), read_activity_actor::npc_read(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), bite_actor::on_damage(), Character::on_hit(), Character::on_hurt(), npc::on_load(), item::on_wear(), activity_handlers::operation_do_turn(), iuse::oxygen_bottle(), mattack::parrot(), vehicle::part_vpower_w(), Character::pause(), Character::perform_technique(), monexamine::pet_menu(), photo_def_for_camera_point(), pick_part_to_heal(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), game::place_player(), monster::plan(), avatar_action::plthrow(), monster::print_info(), game::print_items_info(), Character::process_bionic(), Character::process_effects(), monster::process_effects(), item::process_litcig(), Character::process_one_effect(), sounds::process_sound_markers(), process_turn(), Character::process_turn(), monster::process_turn(), game::prompt_dangerous_tile(), iuse::prozac(), monster::push_to(), Character::reach_attack(), Character::react_to_felt_pain(), Character::recalc_sight_limits(), monster::refill_udders(), Character::regen(), npc::regen_ai_cache(), remove_effect(), anonymous_namespace{monexamine.cpp}::remove_leash(), anonymous_namespace{monexamine.cpp}::remove_saddle_from(), avatar::reset_stats(), resists_effect(), Character::rest_quality(), mattack::resurrect(), mattack::rifle(), iuse::robotcontrol(), Character::run_cost_effects(), iexamine::safe(), Character::search_surroundings(), sees(), npc::set_attitude(), anonymous_namespace{monexamine.cpp}::shear_animal(), gun_actor::shoot(), mattack::shriek_alert(), mattack::shriek_stun(), Character::sight_impaired(), trapfunc::sinkhole(), mattack::slimespring(), mdeath::splatter(), monster::stability_roll(), anonymous_namespace{monexamine.cpp}::start_leading(), anonymous_namespace{monexamine.cpp}::stop_leading(), iuse::strong_antibiotic(), anonymous_namespace{monexamine.cpp}::swap(), avatar_action::swim(), Character::symbol_color(), mattack::tankgun(), iuse::thorazine(), throwing_skill_adjusted(), vehicle::thrust(), anonymous_namespace{monexamine.cpp}::tie_pet(), npc::took_painkiller(), iuse::towel_common(), activity_handlers::tree_communion_do_turn(), trapfunc::tripwire(), monster::try_biosignature(), monster::try_reproduce(), try_set_alarm(), gun_actor::try_target(), Character::uninstall_bionic(), anonymous_namespace{monexamine.cpp}::untie_pet(), Character::update_body(), Character::update_bodytemp(), Character::update_frostbite(), Character::update_heartrate_index(), Character::update_needs(), Character::update_stamina(), Character::update_stomach(), map::update_visibility_cache(), Character::update_vitamins(), musical_instrument_actor::use(), Character::use(), game::use_computer(), vehicle::use_harness(), heal_actor::use_healing_item(), avatar_action::use_item(), game::vertical_move(), Character::vomit(), Character::vomit_mod(), wait(), Character::wait_effects(), Character::wake_up(), avatar::wake_up(), game::walk_move(), iuse::weak_antibiotic(), npc::wear_if_wanted(), weather_sound(), suffer::while_awake(), Character::will_eat(), suffer::without_sleep(), iexamine::workbench_internal(), and mattack::zombie_fuse().
has_effect_with_flag() [1/2]
bool Creature::has_effect_with_flag (const flag_id & flag) const
Definition at line 1800 of file creature.cpp.
 {
     return std::any_of( effects->begin(), effects->end(), [&]( const auto & elem ) {
         // effect::has_flag currently delegates to effect_type::has_flag
         return elem.first->has_flag( flag );
     } );
 }
References effects.
has_effect_with_flag() [2/2]
bool Creature::has_effect_with_flag (const flag_id & flag, const bodypart_id & bp) const
Check if creature has any effect with the given flag.
Definition at line 1792 of file creature.cpp.
 {
     return std::any_of( effects->begin(), effects->end(), [&]( const auto & elem ) {
         // effect::has_flag currently delegates to effect_type::has_flag
         return elem.first->has_flag( flag ) && elem.second.count( bp );
     } );
 }
References effects.
Referenced by melee_actor::call(), Character::can_recover_oxygen(), Character::count_bodypart_with_flag(), Character::count_flag(), monster::die(), monster::flies(), game::get_dangerous_tile(), Character::gravity_check(), Character::has_bodypart_with_flag(), Character::has_flag(), monster::has_flag(), iexamine::ledge(), Character::move_effects(), monster::move_effects(), Character::perform_technique(), monster::process_turn(), teleport::teleport_to_point(), Character::try_remove_grab(), and Character::wait_effects().
has_flag()
virtual bool Creature::has_flag (const mon_flag_id &) const inline virtual
Reimplemented in monster.
Definition at line 752 of file creature.h.
{
             return false;
         }
Referenced by deal_melee_attack(), Character::echo_pulse(), is_likely_underwater(), is_ranged_attacker(), monster::move(), Character::perform_technique(), ranged_target_size(), sees(), mattack::smash(), and Character::throw_item().
has_grab_break_tec()
virtual bool Creature::has_grab_break_tec () const pure virtual
Implemented in monster, and Character.
Referenced by mattack::bio_op_takedown().
has_mind()
bool Creature::has_mind () const pure virtual
Implemented in monster, and Character.
Definition at line 304 of file creature.cpp.
 {
     return false;
 }
Referenced by Character::sees_with_specials().
has_part()
bool Creature::has_part (const bodypart_id & id, body_part_filter filter = body_part_filter::strict) const
Definition at line 2180 of file creature.cpp.
 {
     return get_part_id( id, filter, true ) != body_part_bp_null;
 }
References body_part_bp_null, filter, and get_part_id().
Referenced by Character::encumb(), widget::get_var_value(), bodygraph_display::prepare_partlist(), and widget::set_default_var_range().
has_trait()
bool Creature::has_trait (const trait_id & flag) const virtual
Returns true if the player has the entered trait, returns false for non-humans.
Reimplemented in Character.
Definition at line 1943 of file creature.cpp.
 {
     return false;
 }
Referenced by bite_actor::on_damage(), and resists_effect().
has_weapon()
virtual bool Creature::has_weapon () const pure virtual
Implemented in monster, and Character.
Referenced by Character::evaluate_techniques(), and Character::on_hit().
heal_bp()
void Creature::heal_bp (bodypart_id bp, int dam) virtual
Reimplemented in monster, and Character.
Definition at line 1335 of file creature.cpp.
 {
 }
Referenced by process_damage_over_time().
hit_roll()
virtual float Creature::hit_roll () const pure virtual
Should always be overwritten by the appropriate player/NPC/monster version.
Implemented in monster, and Character.
Referenced by dodge_check(), and select_body_part().
hp_percentage()
virtual int Creature::hp_percentage () const pure virtual
Implemented in monster, and Character.
Referenced by monster::plan().
impact()
virtual int Creature::impact (int force, const tripoint & pos) pure virtual
Deals falling/collision damage with terrain/creature at pos.
Implemented in monster, and Character.
Referenced by Character::add_msg_player_or_say().
in_sleep_state()
bool Creature::in_sleep_state () const virtual
Reimplemented in Character.
Definition at line 2017 of file creature.cpp.
 {
     return has_effect( effect_sleep ) || has_effect( effect_lying_down ) ||
            has_effect( effect_npc_suspend );
 }
References effect_lying_down, effect_npc_suspend, effect_sleep, and has_effect().
Referenced by Character::in_sleep_state(), and monster::melee_attack().
in_species()
bool Creature::in_species (const species_id &) const virtual
Reimplemented in monster, and Character.
Definition at line 1513 of file creature.cpp.
 {
     return false;
 }
Referenced by glide_activity_actor::do_turn(), and Character::mod_speed_bonus().
is_adjacent()
bool Creature::is_adjacent (const Creature * target, bool allow_z_levels) const
Definition at line 722 of file creature.cpp.
 {
     if( target == nullptr ) {
         return false;
     }
     if( rl_dist( pos(), target->pos() ) != 1 ) {
         return false;
     }
     map &here = get_map();
     if( posz() == target->posz() ) {
         return
             /* either target or attacker are underwater and separated by vehicle tiles */
             !( underwater != target->underwater &&
                here.veh_at( pos() ) && here.veh_at( target->pos() ) );
     }
     if( !allow_z_levels ) {
         return false;
     }
     // The square above must have no floor.
     // The square below must have no ceiling (i.e. no floor on the tile above it).
     const bool target_above = target->posz() > posz();
     const tripoint up = target_above ? target->pos() : pos();
     const tripoint down = target_above ? pos() : target->pos();
     const tripoint above{ down.xy(), up.z };
     return ( !here.has_floor( up ) || here.ter( up )->has_flag( ter_furn_flag::TFLAG_GOES_DOWN ) ) &&
            ( !here.has_floor( above ) || here.ter( above )->has_flag( ter_furn_flag::TFLAG_GOES_DOWN ) );
 }
References above, keycode::down, get_map(), map_data_common_t::has_flag(), map::has_floor(), pos(), posz(), rl_dist(), map::ter(), TFLAG_GOES_DOWN, underwater, keycode::up, and map::veh_at().
Referenced by mattack::acid_barf(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), mattack::copbot(), mattack::dermatik(), mattack::evolve_kill_strike(), melee_actor::find_target(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::lunge(), Character::melee_attack(), monster::melee_attack(), Character::perform_special_attacks(), mattack::riotbot(), mattack::smash(), mattack::smash_specific(), stumble_invis(), mattack::tazer(), and npc_attack_melee::use().
is_avatar()
virtual bool Creature::is_avatar () const inline virtual
Reimplemented in npc, and avatar.
Definition at line 265 of file creature.h.
{
             return false;
         }
Referenced by anonymous_namespace{math_parser_diag.cpp}::_friend_match_filter_character(), Character::ablative_armor_absorb(), mattack::acid_barf(), Character::activate_bionic(), bionic::activate_spell(), Character::add_bionic(), add_effect(), Character::add_faction_warning(), monster::anger_hostile_seen(), jmapgen_setmap::apply(), projectile::apply_effects_damage(), Character::bionics_uninstall_failure(), map::board_vehicle(), Character::body_window(), Character::calc_needs_rates(), melee_actor::call(), vehicle::can_close(), Character::can_continue_craft(), Character::can_install_bionics(), Character::can_wear(), ebooksave_activity_actor::canceled(), iexamine::chainfence(), iuse::change_eyes(), iuse::change_skin(), debug_menu::character_edit_desc_menu(), doors::close_door(), complete_construction(), Character::complete_craft(), Character::complete_disassemble(), ebooksave_activity_actor::completed_scanning_current_book(), Character::consume(), Character::consume_effects(), Character::craft_skill_gain(), crafting_allowed(), craft_command::create_in_progress_craft(), Character::deal_damage(), mattack::dermatik(), Character::describe_damage(), destroyed_armor_msg(), monster::die(), Character::dismount(), Character::disp_name(), map::displace_vehicle(), melee_actor::do_grab(), player_activity::do_turn(), hacksaw_activity_actor::do_turn(), boltcutting_activity_actor::do_turn(), shearing_activity_actor::do_turn(), oxytorch_activity_actor::do_turn(), prying_activity_actor::do_turn(), aim_activity_actor::do_turn(), workout_activity_actor::do_turn(), glide_activity_actor::do_turn(), iuse::dog_whistle(), Character::drop(), drop_or_handle(), eat(), activity_handlers::eat_menu_do_turn(), game_menus::inv::ebookread(), debug_menu::mission_debug::edit(), iuse::einktabletpc(), npc::enough_time_to_reload(), npc::evaluate_character(), mattack::evolve_kill_strike(), Character::extended_description(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), conditional_fun::anonymous_namespace{condition.cpp}::f_query(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control(), Character::fall_asleep(), field_processor_fd_last_known(), activity_handlers::find_mount_do_turn(), Character::fine_detail_vision_mod(), read_activity_actor::finish(), ebooksave_activity_actor::finish(), insert_item_activity_actor::finish(), haircut_activity_actor::finish(), heal_actor::finish_using(), Character::fire_gun(), spell_effect::flashbang(), Character::forced_dismount(), game::forced_door_closing(), mattack::formblob(), mattack::frag(), friendly_teacher(), mattack::fungus_bristle(), spell::gain_exp(), mattack::gene_sting(), activity_handlers::generic_game_turn_handler(), Character::get_book_reader(), get_talker_for(), handle_player_display_action(), Character::handle_skill_warning(), Character::healing_rate(), Character::impact(), npc::is_ally(), npc::is_friendly(), npc::is_obeying(), debug_menu::kill_area(), known_magic::learn_spell(), trapfunc::ledge(), effect_on_conditions::load_existing_character(), effect_on_conditions::load_new_character(), mattack::lunge(), iuse::ma_manual(), Character::making_would_work(), iuse::manage_exosuit(), marloss_common(), monster::melee_attack(), Character::melee_attack_abstract(), Character::melee_special_effects(), messaging_projectile_attack(), mod_part_hp_cur(), Character::mod_speed_bonus(), Character::mount_creature(), monster::move(), npc::move_to(), multi_projectile_hit_message(), mattack::multi_robot(), Character::mutate(), Character::mutate_category(), Character::mutate_towards(), Character::mutation_attacks(), mattack::nurse_check_up(), npc::on_attacked(), melee_actor::on_damage(), Character::on_hit(), Character::on_item_acquire(), Character::on_mutation_gain(), Character::on_mutation_loss(), Character::perform_technique(), pick_plant(), activity_handlers::pickaxe_finish(), iuse::play_game(), player_hit_message(), map::player_in_field(), popup_player_or_npc(), Character::practice(), print_data_handling_tally(), effect_on_conditions::process_effect_on_conditions(), process_effects(), sounds::process_sound_markers(), projectile_attack(), activity_handlers::pull_creature_finish(), mattack::pull_metal_weapon(), query_for_item(), workout_activity_actor::query_keep_training(), try_sleep_activity_actor::query_keep_trying(), query_pick(), Character::react_to_felt_pain(), game_menus::inv::read(), Character::recalc_sight_limits(), recipe_info(), remove_effect(), Character::remove_mutation(), mattack::rifle(), mattack::riotbot(), mattack::science(), sees(), Character::sees(), Character::select_requirements(), spell::select_target(), set_part_hp_cur(), known_magic::set_spell_exp(), set_up_butchery(), mattack::shockstorm(), Character::shout(), sinkhole_safety_roll(), outfit::sort_armor(), spell_effect::spawn_ethereal_item(), Character::stagger(), safecracking_activity_actor::start(), shearing_activity_actor::start(), Character::start_craft(), talk_function::start_training_gen(), mattack::stretch_attack(), game::swap_critters(), activity_handlers::teach_finish(), teleport::teleport_to_point(), teleporter_list::translocate(), iexamine::tree_hickory(), Character::try_remove_bear_trap(), Character::try_remove_grab(), gun_actor::try_target(), Character::uncanny_dodge(), vehicle_unfolding_activity_actor::unfold_vehicle(), Character::uninstall_bionic(), Character::update_body(), Character::update_needs(), Character::update_vitamins(), musical_instrument_actor::use(), heal_actor::use_healing_item(), game::vertical_move(), activity_handlers::view_recipe_do_turn(), suffer::while_grabbed(), and mdefense::zapback().
is_dangerous_field()
bool Creature::is_dangerous_field (const field_entry & entry) const
Returns true if the given field entry is dangerous to us.
Definition at line 346 of file creature.cpp.
 {
     // If it's dangerous and we're not immune return true, else return false
     return entry.is_dangerous() && !is_immune_field( entry.get_field_type() );
 }
References field_entry::get_field_type(), field_entry::is_dangerous(), and is_immune_field().
Referenced by npc::could_move_onto(), npc::find_corpse_to_pulp(), game::get_dangerous_tile(), npc::good_escape_direction(), is_dangerous_fields(), and game::is_in_dangerous_field().
is_dangerous_fields()
bool Creature::is_dangerous_fields (const field & fld) const
Returns true if there is a field in the field set that is dangerous to us.
Definition at line 334 of file creature.cpp.
 {
     // Else check each field to see if it's dangerous to us
     for( const auto &dfield : fld ) {
         if( is_dangerous_field( dfield.second ) && !is_immune_field( dfield.first ) ) {
             return true;
         }
     }
     // No fields were found to be dangerous, so the field set isn't dangerous
     return false;
 }
References is_dangerous_field(), and is_immune_field().
Referenced by monster::know_danger_at(), Character::pause(), and npc::sees_dangerous_field().
is_dead_state()
virtual bool Creature::is_dead_state () const pure virtual
Implemented in monster, and Character.
Referenced by check_dead_state(), deal_damage(), mattack::evolve_kill_strike(), spell_effect::guilt(), Character::melee_attack_abstract(), vehicle::part_collision(), Character::perform_special_attacks(), process_turn(), and explosion_handler::shrapnel().
is_elec_immune()
virtual bool Creature::is_elec_immune () const pure virtual
Implemented in monster, and Character.
Referenced by mdefense::zapback().
is_electrical()
virtual bool Creature::is_electrical () const pure virtual
Implemented in npc, monster, and Character.
Referenced by iuse::emf_passive_on(), and Character::sees_with_specials().
is_fae()
virtual bool Creature::is_fae () const pure virtual
Implemented in monster, and Character.
Referenced by Character::sees_with_specials().
is_fake()
bool Creature::is_fake () const virtual
Returns true for non-real Creatures used temporarily; i.e.
fake NPC's used for turret fire.
Definition at line 1518 of file creature.cpp.
 {
     return fake;
 }
References fake.
Referenced by monster::apply_damage(), auto_find_hostile_target(), monster::die(), npc::die(), enchantment::is_active(), monster::on_hit(), npc::on_move(), item::on_pickup(), npc::set_attitude(), npc::set_fac(), set_killer(), and npc::travel_overmap().
is_hallucination()
virtual bool Creature::is_hallucination () const pure virtual
Implemented in npc, monster, and Character.
Referenced by Character::apply_damage(), monster::attack_target(), Character::block_hit(), deal_melee_attack(), deal_melee_hit(), knock_back_from(), monster::melee_attack(), Character::melee_attack_abstract(), monster::move(), mission::on_creature_death(), mission::on_creature_fusion(), vehicle::part_collision(), monster::push_to(), and sees().
is_immune_damage()
virtual bool Creature::is_immune_damage (const damage_type_id & type) const pure virtual
Implemented in monster, and Character.
Referenced by deal_damage_handle_type(), and damage_instance::ondamage_effects().
is_immune_effect()
virtual bool Creature::is_immune_effect (const efftype_id & type) const pure virtual
Implemented in monster, and Character.
Referenced by add_effect(), add_env_effect(), projectile::apply_effects_damage(), mattack::bio_op_takedown(), map::creature_in_field(), Character::melee_attack_abstract(), and mattack::shriek_stun().
is_immune_field()
virtual bool Creature::is_immune_field (const field_type_id &) const inline virtual
Returns true if we are immune to the field type with the given fid.
Can handle intensity if field intensity data is specified for the effect , so this function should only be called through is_dangerous_field().
Reimplemented in monster, and Character.
Definition at line 573 of file creature.h.
{
             return false;
         }
Referenced by map::creature_in_field(), is_dangerous_field(), is_dangerous_fields(), Character::is_immune_field(), and monster::is_immune_field().
is_likely_underwater()
bool Creature::is_likely_underwater () const
Definition at line 297 of file creature.cpp.
 {
     return is_underwater() ||
            ( has_flag( mon_flag_AQUATIC ) && get_map().has_flag( ter_furn_flag::TFLAG_SWIMMABLE, pos() ) );
 }
References get_map(), has_flag(), map::has_flag(), is_underwater(), mon_flag_AQUATIC, pos(), and TFLAG_SWIMMABLE.
Referenced by sees().
is_monster()
virtual bool Creature::is_monster () const inline virtual
Reimplemented in monster.
Definition at line 271 of file creature.h.
{
             return false;
         }
Referenced by anonymous_namespace{math_parser_diag.cpp}::_filter_monster(), monster::apply_damage(), projectile::apply_effects_damage(), attack_air(), auto_find_hostile_target(), melee_actor::call(), gun_actor::call(), vehicle::can_close(), game::chat(), doors::close_door(), map::creature_in_field(), monster::die(), dodge_check(), map::drop_items(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), get_talker_for(), spell_effect::guilt(), trapfunc::ledge(), Character::melee_attack_abstract(), messaging_projectile_attack(), Character::on_hit(), monster::on_hit(), Character::perform_technique(), select_body_part(), game::swap_critters(), gun_actor::try_target(), and game::non_dead_range< T >::iterator::valid().
is_nether()
virtual bool Creature::is_nether () const pure virtual
Implemented in monster, and Character.
Referenced by Character::sees_with_specials().
is_npc()
virtual bool Creature::is_npc () const inline virtual
Reimplemented in npc, and Character.
Definition at line 268 of file creature.h.
{
             return false;
         }
Referenced by projectile::apply_effects_damage(), attack_air(), auto_find_hostile_target(), game::chat(), monster::die(), npc::enough_time_to_reload(), mattack::formblob(), mattack::gene_sting(), get_talker_for(), target_ui::list_friendlies_in_lof(), monster::melee_attack(), monster::move(), multi_projectile_hit_message(), projectile_attack(), Character::reach_attack(), spell::select_target(), gun_actor::try_target(), and game::non_dead_range< T >::iterator::valid().
is_on_ground()
virtual bool Creature::is_on_ground () const pure virtual
Implemented in monster, and Character.
is_part_at_max_hp()
bool Creature::is_part_at_max_hp (const bodypart_id & id) const
Definition at line 2501 of file creature.cpp.
 {
     return get_part_helper( *this, id, &bodypart::is_at_max_hp );
 }
References get_part_helper(), and bodypart::is_at_max_hp().
Referenced by Character::regen().
is_ranged_attacker()
bool Creature::is_ranged_attacker () const virtual
Returns true if this monster has a gun-type attack or the RANGED_ATTACKER flag.
Definition at line 309 of file creature.cpp.
 {
     if( has_flag( mon_flag_RANGED_ATTACKER ) ) {
         return true;
     }
     const monster *mon = as_monster();
     if( mon ) {
         for( const std::pair<const std::string, mtype_special_attack> &attack :
              mon->type->special_attacks ) {
             if( attack.second->id == "gun" ) {
                 return true;
             }
         }
     }
     //TODO Potentially add check for this as npc wielding ranged weapon
     return false;
 }
References as_monster(), spell_effect::attack(), has_flag(), mon_flag_RANGED_ATTACKER, mtype::special_attacks, and monster::type.
Referenced by monster::power_rating().
is_symbol_highlighted()
bool Creature::is_symbol_highlighted () const virtual
Reimplemented in monster.
Definition at line 2998 of file creature.cpp.
 {
     return false;
 }
Referenced by draw().
is_underwater()
bool Creature::is_underwater () const virtual
Reimplemented in monster.
Definition at line 292 of file creature.cpp.
 {
     return underwater;
 }
References underwater.
Referenced by Character::activate_bionic(), cata_event_dispatch::avatar_moves(), iuse::binder_add_recipe(), iuse::binder_manage_recipe(), Character::can_eat(), can_move_vertical_at(), Character::can_recover_oxygen(), firestarter_actor::can_use(), fireweapon_off_actor::can_use(), musical_instrument_actor::can_use(), cant_do_underwater(), iuse::dive_tank(), map::draw_maptile(), iuse::ebookread(), iuse::ebooksave(), Character::echo_pulse(), iuse::electricstorage(), Character::get_weapon_dispersion(), iuse::hand_crank(), Character::handle_gun_damage(), is_likely_underwater(), mine_activity(), avatar_action::move(), Character::process_bionic(), Character::search_surroundings(), avatar_action::swim(), Character::update_body_wetness(), fireweapon_off_actor::use(), fireweapon_on_actor::use(), musical_instrument_actor::use(), game::vertical_move(), and iuse::vibe().
is_warm()
bool Creature::is_warm () const virtual
Reimplemented in monster, and Character.
Definition at line 1508 of file creature.cpp.
 {
     return true;
 }
Referenced by Character::melee_special_effects(), and Character::sees_with_infrared().
knock_back_from()
void Creature::knock_back_from (const tripoint & p)
Definition at line 3114 of file creature.cpp.
 {
     if( p == pos() ) {
         return; // No effect
     }
     if( is_hallucination() ) {
         die( nullptr );
         return;
     }
     tripoint to = pos();
     if( p.x < posx() ) {
         to.x++;
     }
     if( p.x > posx() ) {
         to.x--;
     }
     if( p.y < posy() ) {
         to.y++;
     }
     if( p.y > posy() ) {
         to.y--;
     }
     knock_back_to( to );
 }
References die(), is_hallucination(), knock_back_to(), pos(), posx(), posy(), tripoint::x, and tripoint::y.
Referenced by Character::perform_technique().
knock_back_to()
virtual void Creature::knock_back_to (const tripoint & to) pure virtual
Implemented in monster, and Character.
Referenced by knock_back_from(), and spell_move().
load()
void Creature::load (const JsonObject & jsin) protected
Definition at line 3772 of file savegame_json.cpp.
 {
     jsin.allow_omitted_members();
     jsin.read( "location", location );
     jsin.read( "moves", moves );
     jsin.read( "pain", pain );
     killer = nullptr; // see Creature::load
     // TEMPORARY until 0.F
     if( savegame_loading_version < 31 ) {
         if( jsin.has_object( "effects" ) ) {
             // Because JSON requires string keys we need to convert back to our bp keys
             std::unordered_map<std::string, std::unordered_map<std::string, effect>> tmp_map;
             jsin.read( "effects", tmp_map );
             int key_num = 0;
             for( const auto &maps : tmp_map ) {
                 const efftype_id id( maps.first );
                 if( !id.is_valid() ) {
                     debugmsg( "Invalid effect: %s", id.c_str() );
                     continue;
                 }
                 for( const auto &i : maps.second ) {
                     if( !( std::istringstream( i.first ) >> key_num ) ) {
                         key_num = 0;
                     }
                     const bodypart_str_id &bp = convert_bp( static_cast<body_part>( key_num ) );
                     const effect &e = i.second;
                     ( *effects )[id][bp] = e;
                     on_effect_int_change( id, e.get_intensity(), bp );
                 }
             }
         }
     } else {
         jsin.read( "effects", *effects );
     }
     jsin.read( "values", values );
     // potentially migrate some values
     for( std::pair<std::string, std::string> migration : get_globals().migrations ) {
         if( values.count( migration.first ) != 0 ) {
             auto extracted = values.extract( migration.first );
             extracted.key() = migration.second;
             values.insert( std::move( extracted ) );
         }
     }
     jsin.read( "damage_over_time_map", damage_over_time_map );
     jsin.read( "blocks_left", num_blocks );
     jsin.read( "dodges_left", num_dodges );
     jsin.read( "num_blocks_bonus", num_blocks_bonus );
     jsin.read( "num_dodges_bonus", num_dodges_bonus );
     if( jsin.has_object( "armor_bonus" ) ) {
         jsin.read( "armor_bonus", armor_bonus );
     } else {
         // Legacy load conversion, remove after 0.H releases
         float bash_bonus = 0;
         float cut_bonus = 0;
         float bullet_bonus = 0;
         jsin.read( "armor_bash_bonus", bash_bonus );
         jsin.read( "armor_cut_bonus", cut_bonus );
         jsin.read( "armor_bullet_bonus", bullet_bonus );
         armor_bonus.clear();
         armor_bonus.emplace( STATIC( damage_type_id( "bash" ) ), bash_bonus );
         armor_bonus.emplace( STATIC( damage_type_id( "cut" ) ), cut_bonus );
         armor_bonus.emplace( STATIC( damage_type_id( "bullet" ) ), bullet_bonus );
     }
     jsin.read( "speed", speed_base );
     jsin.read( "speed_bonus", speed_bonus );
     jsin.read( "dodge_bonus", dodge_bonus );
     jsin.read( "block_bonus", block_bonus );
     jsin.read( "hit_bonus", hit_bonus );
     jsin.read( "bash_bonus", bash_bonus );
     jsin.read( "cut_bonus", cut_bonus );
     jsin.read( "bash_mult", bash_mult );
     jsin.read( "cut_mult", cut_mult );
     jsin.read( "melee_quiet", melee_quiet );
     jsin.read( "throw_resist", throw_resist );
     jsin.read( "archery_aim_counter", archery_aim_counter );
     if( !jsin.read( "last_updated", last_updated ) ) {
         last_updated = calendar::turn;
     }
     jsin.read( "underwater", underwater );
     jsin.read( "body", body );
     fake = false; // see Creature::load
     jsin.read( "lifespan_end", lifespan_end );
     on_stat_change( "pain", pain );
 }
References JsonObject::allow_omitted_members(), bp, convert_bp(), debugmsg, get_globals(), effect::get_intensity(), JsonObject::has_object(), base_camps::id, item_pocket::is_valid(), location, anonymous_namespace{overmap.cpp}::migrations, item_pocket::moves(), pain, JsonObject::read(), savegame_loading_version, STATIC, and calendar::turn.
Referenced by Character::load(), and monster::load().
load_hit_range()
void Creature::load_hit_range (const JsonObject & jo) static
Definition at line 3192 of file creature.cpp.
 {
     if( jo.has_array( "even_good" ) ) {
         jo.read( "even_good", dispersion_for_even_chance_of_good_hit );
     }
 }
References dispersion_for_even_chance_of_good_hit, JsonObject::has_array(), and JsonObject::read().
Referenced by DynamicDataLoader::initialize().
longpull()
void Creature::longpull (const std::string & name, const tripoint & p)
Attempts to pull the target at point p towards this creature.
Parameters
name Name of the implement used to pull the target.
p Position of the target creature.
Definition at line 1339 of file creature.cpp.
 {
     if( pos() == p ) {
         add_msg_if_player( _( "You try to pull yourself together." ) );
         return;
     }
     std::vector<tripoint> path = line_to( pos(), p, 0, 0 );
     Creature *c = nullptr;
     for( const tripoint &path_p : path ) {
         c = get_creature_tracker().creature_at( path_p );
         if( c == nullptr && get_map().impassable( path_p ) ) {
             add_msg_if_player( m_warning, _( "There's an obstacle in the way!" ) );
             return;
         }
         if( c != nullptr ) {
             break;
         }
     }
     if( c == nullptr || !sees( *c ) ) {
         // TODO: Latch onto objects?
         add_msg_if_player( m_warning, _( "There's nothing here to latch onto with your %s!" ),
                            name );
         return;
     }
     // Pull creature
     const Character *ch = as_character();
     const monster *mon = as_monster();
     const int str = ch != nullptr ? ch->get_str() : mon != nullptr ? mon->get_grab_strength() : 10;
     const int odds = units::to_kilogram( c->get_weight() ) / ( str * 3 );
     if( one_in( clamp<int>( odds * odds, 1, 1000 ) ) ) {
         add_msg_if_player( m_good, _( "You pull %1$s towards you with your %2$s!" ), c->disp_name(),
                            name );
         if( c->is_avatar() ) {
             add_msg( m_warning, _( "%1$s pulls you in with their %2$s!" ), disp_name( false, true ), name );
         }
         c->move_to( tripoint_abs_ms( line_to( get_location().raw(), c->get_location().raw(), 0,
                                               0 ).front() ) );
         c->add_effect( effect_stunned, 1_seconds );
         sounds::sound( c->pos(), 5, sounds::sound_t::combat, _( "Shhhk!" ) );
     } else {
         add_msg_if_player( m_bad, _( "%s weight makes it difficult to pull towards you." ),
                            c->disp_name( true, true ) );
         if( c->is_avatar() ) {
             add_msg( m_info, _( "%1s tries to pull you in, but you resist!" ), disp_name( false, true ) );
         }
     }
 }
References _, add_msg(), add_msg_if_player(), as_character(), as_monster(), c, sounds::combat, creature_tracker::creature_at(), disp_name(), effect_stunned, get_creature_tracker(), monster::get_grab_strength(), get_location(), get_map(), Character::get_str(), impassable, line_to(), m_bad, m_good, m_info, m_warning, om_direction::name(), one_in(), pos(), sees(), sounds::sound(), and units::to_kilogram().
Referenced by avatar::longpull(), activity_handlers::pull_creature_finish(), and spell_effect::pull_to_caster().
made_of()
virtual bool Creature::made_of (const material_id & m) const pure virtual
Implemented in monster, and Character.
Referenced by projectile::apply_effects_damage().
made_of_any()
virtual bool Creature::made_of_any (const std::set< material_id > & ms) const pure virtual
Implemented in monster, and Character.
Referenced by projectile::apply_effects_damage(), and mattack::evolve_kill_strike().
maybe_get_value()
std::optional< std::string > Creature::maybe_get_value (const std::string & key) const
Definition at line 1964 of file creature.cpp.
 {
     auto it = values.find( key );
     return it == values.end() ? std::nullopt : std::optional<std::string> { it->second };
 }
References values.
Referenced by get_value(), talker_character_const::maybe_get_value(), and talker_monster_const::maybe_get_value().
messaging_projectile_attack()
void Creature::messaging_projectile_attack (const Creature * source, const projectile_attack_results & hit_selection, int total_damage) const private
Definition at line 1044 of file creature.cpp.
 {
     const viewer &player_view = get_player_view();
     const bool u_see_this = player_view.sees( *this );
     if( u_see_this ) {
         if( hit_selection.damage_mult == 0 ) {
             if( source != nullptr ) {
                 add_msg( source->is_avatar() ? _( "You miss!" ) : _( "The shot misses!" ) );
             }
         } else if( total_damage == 0 ) {
             if( hit_selection.wp_hit.empty() ) {
                 //~ 1$ - monster name, 2$ - character's bodypart or monster's skin/armor
                 add_msg( _( "The shot reflects off %1$s %2$s!" ), disp_name( true ),
                          is_monster() ?
                          skin_name() :
                          body_part_name_accusative( hit_selection.bp_hit ) );
             } else {
                 //~ %1$s: creature name, %2$s: weakpoint hit
                 add_msg( _( "The shot hits %1$s in %2$s but deals no damage." ),
                          disp_name(), hit_selection.wp_hit );
             }
         } else if( is_avatar() ) {
             //monster hits player ranged
             //~ Hit message. 1$s is bodypart name in accusative. 2$d is damage value.
             add_msg_if_player( m_bad, _( "You were hit in the %1$s for %2$d damage." ),
                                body_part_name_accusative( hit_selection.bp_hit ),
                                total_damage );
         } else if( source != nullptr ) {
             if( source->is_avatar() ) {
                 //player hits monster ranged
                 SCT.add( point( posx(), posy() ),
                          direction_from( point_zero, point( posx() - source->posx(), posy() - source->posy() ) ),
                          get_hp_bar( total_damage, get_hp_max(), true ).first,
                          m_good, hit_selection.message, hit_selection.gmtSCTcolor );
                 if( get_hp() > 0 ) {
                     SCT.add( point( posx(), posy() ),
                              direction_from( point_zero, point( posx() - source->posx(), posy() - source->posy() ) ),
                              get_hp_bar( get_hp(), get_hp_max(), true ).first, m_good,
                              //~ "hit points", used in scrolling combat text
                              _( "HP" ), m_neutral, "hp" );
                 } else {
                     SCT.removeCreatureHP();
                 }
                 if( hit_selection.wp_hit.empty() ) {
                     //~ %1$s: creature name, %2$d: damage value
                     add_msg( m_good, _( "You hit %1$s for %2$d damage." ),
                              disp_name(), total_damage );
                 } else {
                     //~ %1$s: creature name, %2$s: weakpoint hit, %3$d: damage value
                     add_msg( m_good, _( "You hit %1$s in %2$s for %3$d damage." ),
                              disp_name(), hit_selection.wp_hit, total_damage );
                 }
             } else if( source != this ) {
                 if( hit_selection.wp_hit.empty() ) {
                     //~ 1$ - shooter, 2$ - target
                     add_msg( _( "%1$s shoots %2$s." ),
                              source->disp_name(), disp_name() );
                 } else {
                     //~ 1$ - shooter, 2$ - target, 3$ - weakpoint
                     add_msg( _( "%1$s shoots %2$s in %3$s." ),
                              source->disp_name(), disp_name(), hit_selection.wp_hit );
                 }
             }
         }
     }
 }
References _, add_msg(), body_part_name_accusative(), projectile_attack_results::bp_hit, projectile_attack_results::damage_mult, disp_name(), get_player_view(), is_avatar(), is_monster(), viewer::sees(), skin_name(), and projectile_attack_results::wp_hit.
Referenced by Character::add_msg_player_or_say().
mod_bash_bonus()
void Creature::mod_bash_bonus (int nbash) virtual
Definition at line 2918 of file creature.cpp.
 {
     bash_bonus += nbash;
 }
References bash_bonus.
Referenced by mod_stat(), and monster::process_one_effect().
mod_block_bonus()
void Creature::mod_block_bonus (int nblock) virtual
Definition at line 2910 of file creature.cpp.
 {
     block_bonus += nblock;
 }
References block_bonus.
Referenced by mod_stat().
mod_cut_bonus()
void Creature::mod_cut_bonus (int ncut) virtual
Definition at line 2922 of file creature.cpp.
 {
     cut_bonus += ncut;
 }
References cut_bonus.
Referenced by mod_stat(), and monster::process_one_effect().
mod_dodge_bonus()
void Creature::mod_dodge_bonus (float ndodge) virtual
Definition at line 2906 of file creature.cpp.
 {
     dodge_bonus += ndodge;
 }
References dodge_bonus.
Referenced by mod_stat(), monster::process_one_effect(), avatar::reset_stats(), and Character::reset_stats().
mod_hit_bonus()
void Creature::mod_hit_bonus (float nhit) virtual
Definition at line 2914 of file creature.cpp.
 {
     hit_bonus += nhit;
 }
References hit_bonus.
Referenced by mod_stat(), and monster::process_one_effect().
mod_moves()
void Creature::mod_moves (int nmoves)
Definition at line 2008 of file creature.cpp.
 {
     moves += nmoves;
 }
References moves.
Referenced by mattack::absorb_items(), mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), computer_session::action_amigara_log(), computer_session::action_blood_anal(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_deactivate_shock_vent(), computer_session::action_download_software(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), computer_session::action_irradiator(), computer_session::action_list_bionics(), computer_session::action_map_sewer(), computer_session::action_map_subway(), computer_session::action_maps(), computer_session::action_radio_archive(), computer_session::action_research(), computer_session::action_sample(), computer_session::action_shutters(), relic::activate(), Character::activate_bionic(), computer_session::activate_function(), Character::activate_mutation(), anonymous_namespace{monexamine.cpp}::add_armor(), iuse::adrenaline_injector(), iuse::afs_translocator(), anonymous_namespace{monexamine.cpp}::attach_bag_to(), attack_air(), iexamine::autodoc(), iexamine::bars(), monster::bash_at(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), iuse::blood_draw(), trapfunc::board(), mattack::boomer(), mattack::boomer_glow(), iuse::break_stick(), mattack::breathe(), cardreader_examine_actor::call(), leap_actor::call(), mon_spellcasting_actor::call(), melee_actor::call(), trapfunc::caltrops(), trapfunc::caltrops_glass(), iuse::camera(), iuse::capture_monster_act(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), iexamine::chainfence(), Character::change_side(), game::chat(), check_deploy_square(), game::climb_down_using(), doors::close_door(), iexamine::compost_empty(), iexamine::compost_full(), npc::consume_food(), Character::cough(), iuse::crowbar(), iexamine::curtains(), salvage_actor::cut_up(), iexamine::cvdmachine(), mattack::darkman(), Character::deactivate_mutation(), mattack::dermatik(), iuse::directional_hologram(), avatar::disarm(), Character::dismount(), Character::dispose_item(), do_aim(), melee_actor::do_grab(), npc::do_player_activity(), game::do_regular_action(), npc::do_reload(), player_activity::do_turn(), move_items_activity_actor::do_turn(), glide_activity_actor::do_turn(), mattack::doot(), mattack::dsa_drone_scan(), anonymous_namespace{monexamine.cpp}::dump_items(), iuse::einktabletpc(), iuse::electricstorage(), mattack::evolve_kill_strike(), iuse::extinguisher(), iuse::eyedrops(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_turn_cost(), iexamine::fertilize_plant(), Character::fire_gun(), iexamine::fireplace(), mattack::flame(), mattack::flesh_golem(), mattack::flesh_tendril(), iexamine::flower_marloss(), iexamine::flower_poppy(), Character::forced_dismount(), mattack::frag(), suffer::from_asthma(), suffer::from_bad_bionics(), suffer::from_chemimbalance(), suffer::from_stimulants(), iexamine::fswitch(), iexamine::fungus(), mattack::fungus(), mattack::fungus_big_blossom(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_haze(), mattack::fungus_inject(), iexamine::fvat_empty(), iexamine::fvat_full(), iuse::geiger(), mattack::gene_sting(), talker_npc::get_topics(), talker_npc::give_item_to(), trapfunc::glass(), game::grabbed_veh_move(), grenade_helper(), mattack::grow_vine(), gun_repair(), computer_session::hack_attempt(), hackveh(), game::handle_action(), iuse::handle_ground_graffiti(), Character::hardcoded_effects(), mattack::howl(), iexamine::keg(), iexamine::ledge(), link_up_actor::link_extend_cable(), link_up_actor::link_to_veh_app(), link_up_actor::link_tow_cable(), aim_activity_actor::load_RAS_weapon(), doors::lock_door(), mattack::lunge(), iuse::mace(), iuse::manage_exosuit(), iuse::measure_resonance(), monexamine::mech_hack(), monster::melee_attack(), Character::melee_attack_abstract(), mill_activate(), spell_effect::mod_moves(), mod_stat(), map::monster_in_field(), iuse::mop(), Character::mount_creature(), monster::move(), avatar_action::move(), move_item(), monster::move_to(), npc::move_to(), game::moving_vehicle_dismount(), iuse::mp3(), iuse::mp3_deactivate(), npc::mug_player(), iuse::multicooker(), multicooker_hallu(), npc::npc_dismount(), game::npc_menu(), item_location::impl::item_in_container::obtain(), item_location::impl::item_on_map::obtain(), item_location::impl::item_on_person::obtain(), item_location::impl::item_on_vehicle::obtain(), obtain_activity_items(), npc::on_load(), item::on_wield(), open(), iuse::oxygen_bottle(), iuse::pack_item(), mattack::para_sting(), mattack::parrot(), iexamine::pay_gas(), game::peek(), liquid_handler::perform_liquid_transfer(), iuse::petfood(), game::phasing_move(), mattack::photograph(), pick_one_up(), npc::pick_up_item(), iexamine::pit(), iexamine::pit_covered(), mattack::plant(), map::player_in_field(), vehicle::pldrive(), npc::pretend_fire(), npc::pretend_heal(), item::process_litcig(), mattack::pull_metal_weapon(), activity_handlers::pulp_do_turn(), anonymous_namespace{monexamine.cpp}::push(), monster::push_to(), iexamine::quern_examine(), iuse::radiocar(), avatar_action::ramp_move(), mattack::rattle(), rcdrive(), Character::reach_attack(), avatar::read(), reload_furniture(), anonymous_namespace{monexamine.cpp}::remove_armor(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), link_up_actor::remove_extensions(), activity_handlers::repair_item_do_turn(), mattack::resurrect(), mattack::rifle(), mattack::riotbot(), iuse::robotcontrol(), iexamine::safe(), mattack::science(), mattack::shockstorm(), gun_actor::shoot(), monster::shove_vehicle(), mattack::shriek(), mattack::shriek_alert(), iexamine::sign(), smash(), mattack::smash(), smoker_activate(), smoker_load_food(), iexamine::smoker_options(), mattack::spit_sap(), mattack::split(), Character::stagger(), activity_handlers::start_fire_do_turn(), avatar::steal(), Character::store(), npc::stow_item(), mattack::stretch_attack(), anonymous_namespace{monexamine.cpp}::swap(), avatar_action::swim(), mattack::tankgun(), mattack::taze(), iuse::tazer(), iuse::teleport(), Character::throw_item(), mattack::tindalos_teleport(), iuse::towel_common(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), mattack::triffid_heartbeat(), trapfunc::tripwire(), avatar::try_break_relax_gas(), try_consume(), gun_actor::try_target(), Character::unload(), doors::unlock_door(), iuse::unpack_item(), mattack::upgrade(), iuse_transform::use(), consume_drug_iuse::use(), place_monster_iuse::use(), change_scent_iuse::use(), place_npc_iuse::use(), deploy_furn_actor::use(), deploy_appliance_actor::use(), firestarter_actor::use(), fireweapon_off_actor::use(), manualnoise_actor::use(), place_trap_actor::use(), sew_advanced_actor::use(), link_up_actor::use(), Character::use(), avatar_action::use_item(), npc::use_painkiller(), iexamine::vending(), game::vertical_move(), mattack::vine(), Character::vomit(), iuse::vortex(), game::walk_move(), iuse::water_purifier(), outfit::wear_item(), iuse::weed_cake(), npc::wield(), avatar::wield(), Character::wield_contents(), suffer::without_sleep(), and mattack::zombie_fuse().
mod_num_blocks_bonus()
void Creature::mod_num_blocks_bonus (int nblocks) virtual
Definition at line 2858 of file creature.cpp.
 {
     num_blocks_bonus += nblocks;
 }
References num_blocks_bonus.
Referenced by enchant_cache::activate_passive().
mod_num_dodges_bonus()
void Creature::mod_num_dodges_bonus (int ndodges) virtual
Definition at line 2863 of file creature.cpp.
 {
     num_dodges_bonus += ndodges;
 }
References num_dodges_bonus.
Referenced by enchant_cache::activate_passive().
mod_pain()
void Creature::mod_pain (int npain) virtual
Reimplemented in Character.
Definition at line 1975 of file creature.cpp.
 {
     mod_pain_noresist( npain );
 }
References mod_pain_noresist().
Referenced by deal_damage(), talker_monster::mod_pain(), Character::mod_pain(), and mod_stat().
mod_pain_noresist()
void Creature::mod_pain_noresist (int npain) virtual
Definition at line 1980 of file creature.cpp.
 {
     set_pain( pain + npain );
 }
References pain, and set_pain().
Referenced by mod_pain(), and spell_effect::recover_energy().
mod_part_damage_bandaged()
void Creature::mod_part_damage_bandaged (const bodypart_id & id, int mod)
Definition at line 2425 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::mod_damage_bandaged, mod );
 }
References bodypart::mod_damage_bandaged(), and set_part_helper().
Referenced by Character::regen().
mod_part_damage_disinfected()
void Creature::mod_part_damage_disinfected (const bodypart_id & id, int mod)
Definition at line 2420 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::mod_damage_disinfected, mod );
 }
References bodypart::mod_damage_disinfected(), and set_part_helper().
Referenced by Character::regen().
mod_part_frostbite_timer()
void Creature::mod_part_frostbite_timer (const bodypart_id & id, int mod)
Definition at line 2445 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::mod_frostbite_timer, mod );
 }
References bodypart::mod_frostbite_timer(), and set_part_helper().
Referenced by Character::update_bodytemp(), and Character::update_frostbite().
mod_part_healed_total()
void Creature::mod_part_healed_total (const bodypart_id & id, int mod)
Definition at line 2415 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::mod_healed_total, mod );
 }
References bodypart::mod_healed_total(), and set_part_helper().
Referenced by Character::healall(), and Character::regen().
mod_part_hp_cur()
void Creature::mod_part_hp_cur (const bodypart_id & id, int mod) virtual
Reimplemented in Character.
Definition at line 2401 of file creature.cpp.
 {
     bool was_broken = is_avatar() && as_character()->is_limb_broken( id );
     set_part_helper( *this, id, &bodypart::mod_hp_cur, mod );
     if( !was_broken && is_avatar() && as_character()->is_limb_broken( id ) ) {
         get_event_bus().send<event_type::broken_bone>( as_character()->getID(), id );
     }
 }
References as_character(), broken_bone, get_event_bus(), Character::getID(), base_camps::id, is_avatar(), Character::is_limb_broken(), bodypart::mod_hp_cur(), event_bus::send(), and set_part_helper().
Referenced by spell_effect::banishment().
mod_part_hp_max()
void Creature::mod_part_hp_max (const bodypart_id & id, int mod)
Definition at line 2410 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::mod_hp_max, mod );
 }
References bodypart::mod_hp_max(), and set_part_helper().
mod_part_temp_conv()
void Creature::mod_part_temp_conv (const bodypart_id & id, units::temperature_delta mod)
Definition at line 2440 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::mod_temp_conv, mod );
 }
References bodypart::mod_temp_conv(), and set_part_helper().
Referenced by Character::update_bodytemp().
mod_part_temp_cur()
void Creature::mod_part_temp_cur (const bodypart_id & id, units::temperature_delta mod)
Definition at line 2435 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::mod_temp_cur, mod );
 }
References bodypart::mod_temp_cur(), and set_part_helper().
Referenced by Character::temp_equalizer(), and Character::update_body_wetness().
mod_part_wetness()
void Creature::mod_part_wetness (const bodypart_id & id, int mod)
Definition at line 2430 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::mod_wetness, mod );
 }
References bodypart::mod_wetness(), and set_part_helper().
Referenced by Character::process_one_effect(), and Character::update_body_wetness().
mod_size_bonus()
void Creature::mod_size_bonus (int nsize) virtual
Definition at line 2926 of file creature.cpp.
 {
     nsize = clamp( nsize, creature_size::tiny - get_size(), creature_size::huge - get_size() );
     size_bonus += nsize;
 }
References clamp(), get_size(), huge, size_bonus, and tiny.
Referenced by monster::process_one_effect().
mod_speed_bonus()
void Creature::mod_speed_bonus (int nspeed) virtual
Definition at line 2902 of file creature.cpp.
 {
     speed_bonus += nspeed;
 }
References speed_bonus.
Referenced by mod_stat(), and monster::process_one_effect().
mod_stat()
void Creature::mod_stat (const std::string & stat, float modifier) virtual
Reimplemented in Character.
Definition at line 2830 of file creature.cpp.
 {
     if( stat == "speed" ) {
         mod_speed_bonus( modifier );
     } else if( stat == "dodge" ) {
         mod_dodge_bonus( modifier );
     } else if( stat == "block" ) {
         mod_block_bonus( modifier );
     } else if( stat == "hit" ) {
         mod_hit_bonus( modifier );
     } else if( stat == "bash" ) {
         mod_bash_bonus( modifier );
     } else if( stat == "cut" ) {
         mod_cut_bonus( modifier );
     } else if( stat == "pain" ) {
         mod_pain( modifier );
     } else if( stat == "moves" ) {
         mod_moves( modifier );
     } else {
         debugmsg( "Tried to modify a nonexistent stat %s.", stat.c_str() );
     }
 }
References debugmsg, mod_bash_bonus(), mod_block_bonus(), mod_cut_bonus(), mod_dodge_bonus(), mod_hit_bonus(), mod_moves(), mod_pain(), and mod_speed_bonus().
Referenced by Character::mod_stat().
modify_damage_dealt_with_enchantments()
damage_instance Creature::modify_damage_dealt_with_enchantments (const damage_instance & dam) const virtual
Reimplemented in Character.
Definition at line 497 of file melee.cpp.
 {
     return dam;
 }
Referenced by deal_melee_hit().
move_effects()
virtual bool Creature::move_effects (bool attacking) pure virtual
Processes move stopping effects.
Returns false if movement is stopped.
Implemented in monster, and Character.
move_to()
void Creature::move_to (const tripoint_abs_ms & loc)
Moves the creature to the given location and calls the on_move() handler.
Definition at line 195 of file creature.cpp.
 {
     const tripoint_abs_ms old_loc = get_location();
     set_location( loc );
     on_move( old_loc );
 }
References get_location(), on_move(), and set_location().
Referenced by glide_activity_actor::do_turn(), tutorial_game::init(), monster::move(), monster::nursebot_operate(), game::peek(), start_location::place_player(), teleport::teleport_to_point(), and game::vertical_shift().
normalize()
void Creature::normalize () virtual
Recreates the Creature from scratch.
Reimplemented in Character.
Definition at line 220 of file creature.cpp.
 {
 }
Referenced by Character::normalize().
on_damage_of_type()
virtual void Creature::on_damage_of_type (const effect_source & , int , const damage_type_id & , const bodypart_id &) inline protected virtual
Reimplemented in Character.
Definition at line 1249 of file creature.h.
                                                               {}
Referenced by deal_damage_handle_type().
on_dodge()
virtual void Creature::on_dodge (Creature * source, float difficulty, float training_level = 0.0f) pure virtual
This creature just dodged an attack - possibly special/ranged attack - from source.
Players should train dodge, monsters may use some special defenses.
Implemented in Character, and monster.
Referenced by mattack::acid_barf(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), deal_melee_attack(), mattack::dermatik(), mattack::evolve_kill_strike(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::lunge(), mattack::smash(), and mattack::stretch_attack().
on_effect_int_change()
virtual void Creature::on_effect_int_change (const efftype_id & , int , const bodypart_id &) inline protected virtual
Reimplemented in Character.
Definition at line 1248 of file creature.h.
 {}
Referenced by add_effect(), clear_effects(), process_effects(), and remove_effect().
on_hit()
virtual void Creature::on_hit (Creature * source, bodypart_id bp_hit, float difficulty = INT_MIN, dealt_projectile_attack const * proj = nullptr) pure virtual
This creature just got hit by an attack - possibly special/ranged attack - from source.
Players should train dodge, possibly counter-attack somehow.
Implemented in monster, and Character.
Referenced by mattack::acid_barf(), mattack::bio_op_impale(), mattack::bio_op_takedown(), melee_actor::call(), deal_melee_hit(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::lunge(), and mattack::stretch_attack().
on_move()
void Creature::on_move (const tripoint_abs_ms & old_pos) protected virtual
Reimplemented in npc, monster, and Character.
Definition at line 212 of file creature.cpp.
 {}
Referenced by move_to(), Character::on_move(), monster::on_move(), and setpos().
on_stat_change()
virtual void Creature::on_stat_change (const std::string & , int) inline protected virtual
Reimplemented in Character.
Definition at line 1247 of file creature.h.
 {}
Referenced by set_pain().
on_try_dodge()
virtual void Creature::on_try_dodge () pure virtual
Invoked when the creature attempts to dodge, regardless of success or failure.
Implemented in monster, and Character.
Referenced by Character::add_msg_player_or_say(), deal_melee_attack(), and dodge_check().
operator=() [1/2]
Creature & Creature::operator= (const Creature &) protected default
operator=() [2/2]
Creature & Creature::operator= (Creature &&) protected default noexcept
pos()
tripoint Creature::pos () const
Definition at line 178 of file creature.cpp.
 {
     return get_map().getlocal( location );
 }
References get_map(), map::getlocal(), and location.
Referenced by Character::absorb_hit(), mattack::absorb_items(), mattack::absorb_meat(), mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), mdefense::acidsplash(), npc::act_on_danger_assessment(), computer_session::action_blood_anal(), computer_session::action_cascade(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_deactivate_shock_vent(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), computer_session::action_irradiator(), computer_session::action_miss_launch(), computer_session::action_release_bionics(), computer_session::action_shutters(), Character::activate_bionic(), npc::activate_item(), Character::activate_mutation(), enchant_cache::activate_passive(), activity_on_turn_move_loot(), timed_event::actualize(), map::add_field(), Character::add_known_trap(), inventory_selector::add_nearby_items(), npc::address_player(), behavior::monster_oracle_t::adjacent_plants(), Character::adjacent_tile(), Character::aim_factor_from_length(), npc_attack_activate_item::all_evaluations(), npc::alt_attack(), map::apparent_light_at(), map::apply_character_light(), Character::apply_persistent_morale(), spell_effect::area_pull(), spell_effect::area_push(), Character::armor_absorb(), npc::assess_danger(), Character::assign_activity(), activity_handlers::atm_do_turn(), monster::attack_at(), auto_find_hostile_target(), vehicle::automatic_fire_turret(), cata_event_dispatch::avatar_moves(), npc::avoid_friendly_fire(), Character::avoid_trap(), iuse::bell(), Character::best_nearby_lifting_assist(), mattack::bio_op_disarm(), bleed(), Character::blossoms(), mattack::blow_whistle(), iuse::boltcutters(), mattack::boomer(), mattack::boomer_glow(), iuse::break_stick(), mattack::breathe(), mdeath::broken(), mattack::browse(), map::build_vision_transparency_cache(), start_location::burn(), Character::burn_fuel(), Character::burn_move_stamina(), game::butcher(), activity_handlers::butcher_finish(), butchery_drops_harvest(), butchery_quarter(), talker_avatar::buy_monster(), veh_interact::cache_tool_availability(), Character::calc_needs_rates(), calculate_aim_cap(), calculate_spell_effect_area(), leap_actor::call(), mon_spellcasting_actor::call(), melee_actor::call(), gun_actor::call(), iuse::call_of_tindalos(), iuse::camera(), spell::can_cast(), Character::can_continue_craft(), Character::can_hear(), can_interact_at(), doors::can_lock_door(), Character::can_mount(), game::can_move_furniture(), npc::can_move_to(), monster::can_reach_to(), doors::can_unlock_door(), iuse_transform::can_use(), firestarter_actor::can_use(), cancel_pickup(), tent_placement_activity_actor::canceled(), vehicle_unfolding_activity_actor::canceled(), iuse::capture_monster_act(), iexamine::cardreader_foodplace(), spell::cast_all_effects(), enchant_cache::cast_enchantment_spell(), spell::cast_extra_spell_effects(), trapfunc::cast_spell(), drawsq_params::center(), iexamine::chainfence(), debug_menu::character_edit_menu(), character_push_effects(), game::chat(), check_deploy_square(), Character::check_eligible_containers_for_crafting(), mattack::check_money_left(), Character::check_mount_is_spooked(), Character::check_mount_will_move(), npc::check_or_use_weapon_cbm(), Character::check_outbounds_activity(), Character::check_read_condition(), game::check_safe_mode_allowed(), mattack::chickenbot(), iuse::chop_tree(), Character::climate_control_strength(), game::climb_down_menu_gen(), game::climb_down_using(), doors::close_door(), talk_function::companion_choose(), talk_function::companion_return(), game_menus::inv::compare(), complete_construction(), Character::complete_craft(), iexamine::compost_full(), Character::consume_charges(), Character::consume_effects(), Character::consume_items(), consume_med(), Character::consume_tools(), Character::consume_ups(), craft_command::continue_prompt_liquids(), vehicle::control_doors(), game::control_vehicle(), mattack::copbot(), Character::cough(), npc::could_move_onto(), map::could_see_items(), Character::craft_consume_tools(), Character::craft_skill_gain(), crafting_allowed(), Character::crafting_inventory(), craft_command::create_in_progress_craft(), Character::create_in_progress_disassembly(), map::creature_in_field(), iuse::crowbar(), iexamine::curtains(), iuse::cut_log_into_planks(), damage_targets(), mattack::darkman(), spell_effect::dash(), Character::deactivate_bionic(), Character::deal_damage(), debug_menu::debug(), debug_menu::debug_menu_spawn_vehicle(), Character::defer_move(), mattack::depart(), iexamine::deployed_furniture(), item_location::impl::item_on_map::describe(), item_location::impl::item_on_vehicle::describe(), trap::detect_trap(), monster::die(), npc::die(), dig_tool(), spell_effect::directed_push(), iuse::directional_antenna(), iuse::directional_hologram(), mdeath::disappear(), avatar::disarm(), Character::disassemble(), Character::disassemble_all(), Character::disp_info(), game::disp_NPCs(), map::displace_vehicle(), game::display_scent(), explosion_handler::do_blast(), melee_actor::do_grab(), npc::do_npc_read(), game::do_regular_action(), npc::do_reload(), data_handling_activity_actor::do_turn(), hacksaw_activity_actor::do_turn(), boltcutting_activity_actor::do_turn(), oxytorch_activity_actor::do_turn(), prying_activity_actor::do_turn(), read_activity_actor::do_turn(), move_items_activity_actor::do_turn(), pickup_activity_actor::do_turn(), ebooksave_activity_actor::do_turn(), stash_activity_actor::do_turn(), glide_activity_actor::do_turn(), unload_loot_activity_actor::do_turn(), editmap::do_ui_invalidation(), mattack::dogthing(), construct::done_window_curtains(), iexamine::door_peephole(), mattack::doot(), game::draw(), anonymous_namespace{animation.cpp}::draw_bullet_curses(), game::draw_critter(), explosion_handler::draw_custom_explosion(), anonymous_namespace{animation.cpp}::draw_custom_explosion_curses(), anonymous_namespace{animation.cpp}::draw_hit_player_curses(), game::draw_look_around_cursor(), editmap::draw_main_ui_overlay(), map::draw_maptile(), advanced_inventory::draw_minimap(), game::draw_ter(), target_ui::draw_terrain_overlay(), draw_throw_aim(), draw_trail(), game::draw_trail_to_square(), vehicle::drive_to_local_target(), Character::drop(), Character::drop_invalid_inventory(), map::drop_items(), monster::drop_items_on_death(), talk_function::drop_stolen_item(), talk_function::drop_weapon(), mattack::dsa_drone_scan(), anonymous_namespace{monexamine.cpp}::dump_items(), eat(), mattack::eat_carrion(), mattack::eat_crop(), mattack::eat_food(), avatar_action::eat_here(), iuse::ebookread(), Character::echo_pulse(), editmap::edit(), eff_fun_fake_common_cold(), eff_fun_fake_flu(), editmap::eget_direction(), iuse::einktabletpc(), iexamine::elevator(), npc::enough_time_to_reload(), Character::env_surgery_bonus(), npc_attack_melee::evaluate(), npc_attack_gun::evaluate(), npc_attack_throw::evaluate(), npc_attack_activate_item::evaluate(), npc::evaluate_character(), npc_attack_melee::evaluate_critter(), Character::evaluate_techniques(), npc_attack_spell::evaluate_tripoint(), npc_attack_gun::evaluate_tripoint(), npc_attack_throw::evaluate_tripoint(), mattack::evolve_kill_strike(), game::examine(), craft_command::execute(), npc::execute_action(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_role_nearby(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), npc::faction_display(), computer_session::failure_alarm(), farm_action(), talk_function::field_plant(), field_processor_fd_push_items(), activity_handlers::fill_liquid_do_turn(), Character::find_ammo(), npc::find_corpse_to_pulp(), npc::find_dangerous_explosives(), npc::find_item(), activity_handlers::find_mount_do_turn(), game::find_nearby_items(), game::find_or_make_stairs(), melee_actor::find_target(), Character::fine_detail_vision_mod(), tent_placement_activity_actor::finish(), hacking_activity_actor::finish(), lockpick_activity_actor::finish(), shearing_activity_actor::finish(), move_furniture_activity_actor::finish(), chop_tree_activity_actor::finish(), forage_activity_actor::finish(), longsalvage_activity_actor::finish(), fire(), Character::fire_gun(), iexamine::fireplace(), iuse::fishing_rod(), mattack::flame(), explosion_handler::flashbang(), mattack::flesh_golem(), mattack::flesh_tendril(), game::fling_creature(), Character::floor_bedding_warmth(), Character::floor_item_warmth(), Character::floor_warmth(), iexamine::flower_marloss(), npc::follow_distance(), monster::footsteps(), Character::forced_dismount(), mattack::formblob(), mattack::frag(), suffer::from_artifact_resonance(), suffer::from_asthma(), suffer::from_nyctophobia(), suffer::from_other_mutations(), suffer::from_radiation(), vehicle::fuel_left(), mattack::fungal_trail(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus(), mattack::fungus_big_blossom(), mattack::fungus_corporate(), mattack::fungus_fortify(), mattack::fungus_haze(), mattack::fungus_inject(), mattack::fungus_sprout(), map::furn_set(), iexamine::fvat_full(), iexamine::gaspump(), iuse::geiger(), mattack::generator(), generic_multi_activity_check_requirement(), generic_multi_activity_handler(), get_auto_consume_moves(), get_best_fire(), Character::get_crafting_group(), Character::get_crafting_helpers(), game::get_dangerous_tile(), activatable_inventory_preset::get_denial(), Character::get_eligible_containers_for_crafting(), get_heat_radiation(), Character::get_hostile_creatures(), Character::get_item_position(), liquid_handler::get_liquid_target(), map::get_moving_vehicle_targets(), Character::get_mutation_visibility_cap(), overmap_ui::get_overmap_path_to(), monster::get_path_avoid(), npc::get_path_avoid(), get_patient(), Character::get_targetable_creatures(), game::get_veh_dir_indicator_location(), Character::get_visible_creatures(), talk_function::give_all_aid(), anonymous_namespace{monexamine.cpp}::give_items_to(), glare(), npc::go_to_omt_destination(), npc::good_escape_direction(), grab(), avatar::grab(), game::grabbed_furn_move(), game::grabbed_furn_move_time(), game::grabbed_veh_move(), iuse::granade_act(), Character::gravity_check(), mattack::graze(), monster::group_bash_skill(), mattack::grow_vine(), mattack::growplants(), gun_repair(), gunmode_checks_common(), gunmode_checks_weapon(), iuse::hacksaw(), handbrake(), handle_action_menu(), Character::handle_contents_changed(), target_ui::handle_cursor_movement(), Character::handle_gun_overheat(), iexamine_helper::handle_harvest(), item_pocket::handle_liquid_or_spill(), Character::handle_melee_wear(), vehicle::handle_potential_theft(), prying_activity_actor::handle_prying(), npc::handle_sound(), vehicle::handle_trap(), Character::hardcoded_effects(), iexamine::harvest_plant(), Character::has_alarm_clock(), Character::has_destination_activity(), Character::has_fire(), has_vehicle_control(), Character::has_watch(), haul(), npc::heal_player(), npc::heal_self(), monster::hear_sound(), Character::heat_emission(), iuse::heat_food(), iuse::honeycomb(), mattack::howl(), Character::i_add(), Character::i_add_or_drop(), Character::i_add_or_fill(), Character::i_drop_at(), Character::i_rem_keep_contents(), vehicle::idle(), Character::impact(), suffer::in_sunlight(), npc::indoor_voice(), advanced_inv_area::init(), Character::install_bionics(), iexamine::intercom(), game::inventory_item_menu(), Character::invoke_item(), npc::is_active(), is_adjacent(), place_trap_actor::is_allowed(), Character::is_deaf(), Character::is_driving(), monster::is_fleeing(), game::is_game_over(), game::is_hostile_within(), game::is_in_dangerous_field(), game::is_in_viewport(), is_likely_underwater(), Character::is_snuggling(), spell::is_target_in_range(), spell::is_valid_target(), Character::is_visible_in_range(), behavior::monster_oracle_t::items_available(), mattack::kamikaze(), debug_menu::kill_area(), knock_back_from(), Character::knock_back_to(), monster::knock_back_to(), game::knockback(), Character::knows_trap(), Character::leak_items(), trapfunc::ledge(), mattack::leech_spawner(), talk_function::lesser_give_all_aid(), link_up_actor::link_extend_cable(), link_up_actor::link_to_veh_app(), link_up_actor::link_tow_cable(), game::list_items(), game::list_monsters(), game::load(), avatar::load_map_memory(), aim_activity_actor::load_RAS_weapon(), doors::lock_door(), longpull(), game::look_around(), npc::look_for_player(), loot(), iuse::lumber(), mattack::lunge(), Character::make_clatter_sound(), make_fake_npc(), Character::make_footstep_noise(), monster::make_fungus(), make_gun_sound_effect(), make_mon_corpse(), reload_activity_actor::make_reload_sound(), iuse::makemound(), item_action_generator::map_actions_to_items(), marloss_common(), monster::melee_attack(), Character::melee_attack_abstract(), Character::melee_special_effects(), vehicle::merge_appliance_into_grid(), anonymous_namespace{monexamine.cpp}::milk_source(), mill_activate(), target_handler::mode_turrets(), Character::modify_morale(), game::mon_info_update(), mattack::mon_leech_evolution(), map::monster_in_field(), Character::mount_creature(), monster::move(), npc::move(), avatar_action::move(), advanced_inventory::move_all_items(), npc::move_away_from(), activity_handlers::move_cost(), monster::move_effects(), monster::move_to(), npc::move_to(), npc::move_to_next(), map::move_vehicle(), game::moving_vehicle_dismount(), npc::mug_player(), mattack::multi_robot(), multicooker_hallu(), npc::mutiny(), iuse::mycus(), inventory_selector::naturalize_category(), Character::nearby(), mdeath::normal(), npc::npc_dismount(), game::npc_menu(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), item_location::impl::item_on_map::obtain_cost(), item_location::impl::item_on_vehicle::obtain_cost(), melee_actor::on_damage(), Character::on_dodge(), Character::on_hit(), monster::on_hit(), npc::on_load(), open(), activity_handlers::operation_do_turn(), activity_handlers::operation_finish(), operator_present(), orient_part(), anonymous_namespace{do_turn.cpp}::overmap_npc_move(), Character::overmap_sight_range(), iuse::oxytorch(), spell_effect::pain_split(), mattack::parrot(), vehicle::part_collision(), iexamine::part_con(), Character::pause(), iexamine::pay_gas(), game::peek(), tutorial_game::per_turn(), Character::perform_technique(), Character::perform_uninstall(), game::phasing_move(), mattack::photograph(), iuse::pick_lock(), pick_plant(), Character::pick_up(), npc::pick_up_item(), iexamine::pit_covered(), map::pl_sees(), Character::place_corpse(), place_craft_or_disassembly(), npc::place_on_map(), start_location::place_player(), game::place_player(), game::place_player_overmap(), monster::plan(), mattack::plant(), iuse::play_game(), vehicle::play_music(), iuse::play_music(), vehicle::player_in_control(), map::player_in_field(), player_on_couch(), read_activity_actor::player_readma(), pldrive(), avatar_action::plthrow(), game::point_selection_menu(), iuse::portable_game(), talker_character_const::pos(), talker_monster_const::pos(), item_location::impl::item_on_person::position(), posx(), posy(), vehicle::precollision_check(), npc::pretend_fire(), print_aim(), Character::process_bionic(), Character::process_effects(), monster::process_effects(), Character::process_items(), monster::process_one_effect(), sounds::process_sound_markers(), monster::process_triggers(), Character::process_turn(), monster::process_turn(), projectile_attack(), mattack::pull_metal_weapon(), monster::push_to(), iexamine::quern_examine(), query_consume_ownership(), plot_options::query_seed(), avatar_action::ramp_move(), monster::rate_target(), mattack::ratking(), mattack::rattle(), Character::reach_attack(), npc::reach_omt_destination(), read(), avatar::read(), avatar::rebuild_aim_cache(), target_ui::recalc_aim_turning_penalty(), Character::recalc_sight_limits(), Character::recalc_speed_bonus(), Character::recoil_vehicle(), spell_effect::recover_energy(), reload_furniture(), vehicle::remote_controlled(), anonymous_namespace{monexamine.cpp}::remove_armor(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), link_up_actor::remove_extensions(), spell_effect::remove_field(), remove_submap_turrets(), DefaultRemovePartHandler::removed(), veh_utils::repair_part(), explosion_handler::resonance_cascade(), Character::rest_quality(), mattack::resurrect(), mdefense::return_fire(), mattack::rifle(), mattack::riotbot(), iuse::robotcontrol(), iuse::robotcontrol_can_target(), rod_fish(), Character::rooted(), Character::rooted_message(), target_ui::run(), Character::run_cost_effects(), inventory::rust_iron_items(), sane_consume_items(), avatar::save_map_memory(), npc::say(), scatter_chunks(), monster::scent_move(), mattack::science(), Character::search_surroundings(), mattack::searchlight(), npc::see_item_say_smth(), map::seen_cache_process_ledges(), sees(), Character::sees(), map::sees_some_items(), Character::sees_with_infrared(), Character::sees_with_specials(), pointmenu_cb::impl_t::select(), lockpick_activity_actor::select_location(), spell::select_target(), Character::select_tool_component(), sendRadioSignal(), debug_menu::set_automove(), advanced_inv_area::set_container_position(), avatar::set_movement_mode(), set_up_butchery(), map::shake_vehicle(), anonymous_namespace{monexamine.cpp}::shear_animal(), mattack::shocking_reveal(), mattack::shockstorm(), explosion_handler::shockwave(), gun_actor::shoot(), Character::shout(), monster::shove_vehicle(), explosion_handler::shrapnel(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), iexamine::shrub_marloss(), Character::sight_impaired(), Character::sight_range(), sinkhole_safety_roll(), iuse::siphon(), sleep(), spell_effect::slime_split_on_death(), mattack::slimespring(), smash(), mattack::smash(), smoker_activate(), iexamine::smoker_options(), outfit::sort_armor(), spawn_animal(), monster::spawn_dissectables_on_death(), spell_effect::spawn_ethereal_item(), spawn_items(), map::spawn_monsters_submap_group(), spawn_spores(), mattack::speaker(), spellcasting_callback::spell_info_text(), activity_handlers::spellcasting_finish(), mattack::spit_sap(), mdeath::splatter(), mattack::split(), Character::spores(), Character::stagger(), standard_npc::standard_npc(), read_activity_actor::start(), advanced_inventory::start_activity(), vehicle::start_engine(), activity_handlers::start_fire_do_turn(), activity_handlers::start_fire_finish(), game::start_game(), talk_function::start_training_seminar(), stash_on_pet(), sting_get_target(), sting_shoot(), npc::stow_item(), mattack::stretch_attack(), monster::stumble(), game::swap_critters(), swap_pos(), avatar_action::swim(), Character::symbol_color(), Character::takeoff(), iuse::talking_doll(), mattack::tankgun(), spell::targetable_locations(), npc_attack_melee::targetable_points(), npc_attack_gun::targetable_points(), npc_attack_throw::targetable_points(), iuse::tazer(), teleport::teleport(), debug_menu::teleport_short(), teleport::teleport_to_point(), Character::throw_item(), Character::throwing_dispersion(), spell_effect::timed_event(), mattack::tindalos_teleport(), Character::toggle_hauling(), npc::travel_overmap(), iexamine::tree_hickory(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), mattack::triffid_heartbeat(), trapfunc::tripwire(), monster::try_biosignature(), try_consume(), game::try_get_right_click_action(), Character::try_remove_grab(), Character::try_remove_heavysnare(), monster::try_reproduce(), gun_actor::try_target(), avatar::try_to_sleep(), monster::try_upgrade(), monster::turns_to_reach(), Character::uncanny_dodge(), vehicle_unfolding_activity_actor::unfold_vehicle(), Character::uninstall_bionic(), Character::unload(), doors::unlock_door(), unroll_digging(), Character::update_bodytemp(), Character::update_frostbite(), Character::update_heartrate_index(), npc::update_path(), autodrive_activity_actor::update_player_vehicle(), editmap::update_view_with_help(), map::update_visibility_cache(), weather_manager::update_weather(), place_monster_iuse::use(), place_npc_iuse::use(), firestarter_actor::use(), fireweapon_off_actor::use(), manualnoise_actor::use(), musical_instrument_actor::use(), deploy_tent_actor::use(), unpack_actor::use(), link_up_actor::use(), npc_attack_melee::use(), npc_attack_gun::use(), npc_attack_throw::use(), Character::use_charges(), spell::use_components(), Character::use_fire(), monster::use_mech_power(), Character::valid_aoe_technique(), game::validate_camps(), map::vehmove(), game::vertical_move(), activity_handlers::vibe_do_turn(), mattack::vine(), iuse::vortex(), wait(), game::walk_move(), npc::warn_about(), game::water_affect_items(), Character::wear(), iuse::weather_tool(), suffer::while_grabbed(), suffer::while_underwater(), npc::wield(), avatar::wield_contents(), monster::will_join_horde(), monster::will_move_to(), monster::will_reach(), debug_menu::wishbionics(), within_target_range(), within_visual_range(), npc::wont_hit_friend(), npc::worker_downtime(), mdefense::zapback(), mattack::zombie_fuse(), and game::zones_manager().
pos_bub()
tripoint_bub_ms Creature::pos_bub () const
Definition at line 183 of file creature.cpp.
 {
     return get_map().bub_from_abs( location );
 }
References map::bub_from_abs(), get_map(), and location.
Referenced by activity_on_turn_move_loot(), add_fallback_zone(), butchery_drops_harvest(), can_construct(), can_do_activity_there(), Character::can_sleep(), craft_activity_actor::check_if_craft_okay(), Character::defer_move(), game::do_regular_action(), move_items_activity_actor::do_turn(), drop_activity_actor::do_turn(), glide_activity_actor::do_turn(), unload_loot_activity_actor::do_turn(), game::draw_ter(), npc::execute_action(), generic_multi_activity_handler(), generic_multi_activity_locations(), get_auto_consume_moves(), Character::get_next_auto_move_direction(), npc::good_escape_direction(), has_pre_terrain(), Character::i_add(), game::list_items(), game::look_around(), iuse::meth(), Character::modify_morale(), iuse::mop(), monster::move(), npc::move_to(), npc::on_load(), Character::on_move(), perform_zone_activity_turn(), place_construction(), talk_function::player_weapon_drop(), firestarter_actor::prep_firestarter_use(), put_into_vehicle_or_drop(), advanced_inventory::recalc_pane(), route_adjacent(), route_best_workbench(), game::safe_route_to(), debug_menu::set_automove(), vehicle_folding_activity_actor::start(), vehicle::start_engines(), activity_handlers::start_engines_finish(), activity_handlers::travel_do_turn(), try_fuel_fire(), game::try_get_right_click_action(), monster::try_reproduce(), Character::update_needs(), and consume_drug_iuse::use().
posx()
int Creature::posx () const inline
Definition at line 311 of file creature.h.
{
             return pos().x;
         }
References pos(), and tripoint::x.
Referenced by Character::ablative_armor_absorb(), outfit::absorb_damage(), timed_event::actualize(), iuse::blood_draw(), iuse::can_goo(), create_zone_callback(), Character::deal_damage(), debug_menu::debug_menu_game_state(), Character::describe_damage(), map::displace_vehicle(), melee_actor::do_grab(), draw(), game::draw_async_anim_curses(), game::draw_blink_curses(), game::draw_critter(), game::draw_ter(), draw_trail(), explosion_handler::emp_blast(), iuse::extinguisher(), game::get_player_input(), Character::hardcoded_effects(), is_creature_outside(), knock_back_from(), game::knockback(), iexamine::ledge(), monster::move(), avatar_action::move(), monster::move_to(), npc::move_to(), game::moving_vehicle_dismount(), tutorial_game::per_turn(), Character::perform_technique(), game::phasing_move(), npc::pick_up_item(), npc::place_on_map(), player_hit_message(), iuse::portal(), talker_character_const::posx(), talker_monster_const::posx(), anonymous_namespace{monexamine.cpp}::push(), avatar_action::ramp_move(), avatar::rebuild_aim_cache(), mattack::riotbot(), mattack::searchlight(), sees(), map::shake_vehicle(), mattack::shockstorm(), debug_menu::show_sound(), Character::stagger(), monster::stumble(), avatar_action::swim(), mattack::triffid_heartbeat(), Character::uncanny_dodge(), game::update_map(), npc::update_path(), map::update_visibility_cache(), place_trap_actor::use(), Character::valid_aoe_technique(), npc::vehicle_danger(), game::vertical_move(), game::walk_move(), and game::zones_manager().
posy()
int Creature::posy () const inline
Definition at line 314 of file creature.h.
{
             return pos().y;
         }
References pos(), and tripoint::y.
Referenced by Character::ablative_armor_absorb(), outfit::absorb_damage(), timed_event::actualize(), iuse::blood_draw(), iuse::can_goo(), create_zone_callback(), Character::deal_damage(), debug_menu::debug_menu_game_state(), Character::describe_damage(), map::displace_vehicle(), melee_actor::do_grab(), draw(), game::draw_async_anim_curses(), game::draw_blink_curses(), game::draw_critter(), game::draw_ter(), draw_trail(), explosion_handler::emp_blast(), iuse::extinguisher(), game::find_nearby_items(), game::get_player_input(), Character::hardcoded_effects(), is_creature_outside(), knock_back_from(), game::knockback(), iexamine::ledge(), monster::move(), avatar_action::move(), monster::move_to(), npc::move_to(), game::moving_vehicle_dismount(), tutorial_game::per_turn(), Character::perform_technique(), game::phasing_move(), npc::pick_up_item(), npc::place_on_map(), player_hit_message(), iuse::portal(), talker_character_const::posy(), talker_monster_const::posy(), anonymous_namespace{monexamine.cpp}::push(), avatar_action::ramp_move(), avatar::rebuild_aim_cache(), mattack::riotbot(), mattack::searchlight(), sees(), map::shake_vehicle(), mattack::shockstorm(), debug_menu::show_sound(), Character::stagger(), monster::stumble(), avatar_action::swim(), mattack::triffid_heartbeat(), Character::uncanny_dodge(), game::update_map(), npc::update_path(), map::update_visibility_cache(), place_trap_actor::use(), Character::valid_aoe_technique(), npc::vehicle_danger(), game::vertical_move(), game::walk_move(), and game::zones_manager().
posz()
int Creature::posz () const inline
Definition at line 317 of file creature.h.
{
             return get_location().z();
         }
References get_location(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by npc::address_needs(), monster::bash_at(), game::calc_driving_offset(), npc::can_do_pulp(), iuse::can_goo(), game::chat(), talk_function::companion_choose(), veh_interact::complete_vehicle(), avatar::control_npc(), monster::die(), map::displace_vehicle(), draw(), overmap_ui::draw_ascii(), game::draw_async_anim_curses(), game::draw_blink_curses(), game::draw_critter(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), mattack::dsa_drone_scan(), explosion_handler::emp_blast(), npc::execute_action(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lightning(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_role_nearby(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), mattack::flame(), game::get_player_input(), Character::hardcoded_effects(), monster::hear_sound(), is_adjacent(), iexamine::ledge(), game::look_around(), monster::move(), npc::move(), avatar_action::move(), npc::move_to(), monster::on_hit(), main_menu::opening_screen(), Character::overmap_sight_range(), tutorial_game::per_turn(), Character::perform_technique(), game::phasing_move(), npc::pick_up_item(), npc::place_on_map(), start_location::place_player(), monster::plan(), iuse::portal(), talker_character_const::posz(), talker_monster_const::posz(), sounds::process_sound_markers(), anonymous_namespace{monexamine.cpp}::push(), avatar_action::ramp_move(), mattack::ratking(), Character::recalc_speed_bonus(), DefaultRemovePartHandler::removed(), mattack::riotbot(), monster::scent_move(), mattack::searchlight(), sees(), map::shake_vehicle(), mattack::shockstorm(), mattack::shriek_stun(), smash(), map::spawn_monsters_submap_group(), Character::stagger(), monster::stumble(), swap_pos(), mattack::triffid_heartbeat(), game::try_get_right_click_action(), monster::turns_to_reach(), game::update_overmap_seen(), npc::update_path(), editmap::update_view_with_help(), map::update_visibility_cache(), npc::vehicle_danger(), activity_handlers::vehicle_finish(), game::vertical_move(), game::vertical_shift(), game::walk_move(), monster::will_reach(), and game::zones_manager().
power_rating()
virtual float Creature::power_rating () const pure virtual
Returns an approximation of the creature's strength.
Implemented in monster, and Character.
Referenced by mattack::chickenbot(), and mattack::multi_robot().
print_info()
virtual int Creature::print_info (const catacurses::window & w, int vStart, int vLines, int column) const pure virtual
Write information about this creature.
Parameters
w the window to print the text into.
vStart vertical start to print, that means the first line to print.
vLines number of lines to print at most (printing less is fine).
column horizontal start to print (column), horizontal end is one character before the right border of the window (to keep the border).
Returns
The line just behind the last printed line, that means multiple calls to this can be stacked, the return value is acceptable as vStart for the next call without creating empty lines or overwriting lines.
Implemented in monster, avatar, and npc.
Referenced by game::list_monsters(), target_ui::panel_target_info(), and editmap::update_view_with_help().
process_damage_over_time()
void Creature::process_damage_over_time ()
Definition at line 3047 of file creature.cpp.
 {
     for( auto DoT = damage_over_time_map.begin(); DoT != damage_over_time_map.end(); ) {
         if( DoT->duration > 0_turns ) {
             for( const bodypart_str_id &bp : DoT->bps ) {
                 const int dmg_amount = DoT->amount;
                 if( dmg_amount < 0 ) {
                     heal_bp( bp.id(), -dmg_amount );
                 } else if( dmg_amount > 0 ) {
                     deal_damage( nullptr, bp.id(), damage_instance( DoT->type, dmg_amount ) );
                 }
             }
             DoT->duration -= 1_turns;
             ++DoT;
         } else {
             DoT = damage_over_time_map.erase( DoT );
         }
     }
 }
References bp, damage_over_time_map, deal_damage(), heal_bp(), and int_id< T >::id().
Referenced by process_turn().
process_effects()
void Creature::process_effects () virtual
Processes through all the effects on the Creature.
Reimplemented in monster, and Character.
Definition at line 1881 of file creature.cpp.
 {
     // id's and body_part's of all effects to be removed. If we ever get player or
     // monster specific removals these will need to be moved down to that level and then
     // passed in to this function.
     std::vector<efftype_id> rem_ids;
     std::vector<bodypart_id> rem_bps;
     // Decay/removal of effects
     for( auto &elem : *effects ) {
         for( auto &_it : elem.second ) {
             // Add any effects that others remove to the removal list
             for( const auto &removed_effect : _it.second.get_removes_effects() ) {
                 rem_ids.push_back( removed_effect );
                 rem_bps.emplace_back( bodypart_str_id::NULL_ID() );
             }
             effect &e = _it.second;
             const int prev_int = e.get_intensity();
             // Run decay effects, marking effects for removal as necessary.
             e.decay( rem_ids, rem_bps, calendar::turn, is_avatar(), *effects );
             if( e.get_intensity() != prev_int && e.get_duration() > 0_turns ) {
                 on_effect_int_change( e.get_id(), e.get_intensity(), e.get_bp() );
             }
             const bool reduced = resists_effect( e );
             if( e.kill_roll( reduced ) ) {
                 add_msg_if_player( m_bad, e.get_death_message() );
                 if( is_avatar() ) {
                     std::map<std::string, cata_variant> event_data;
                     std::pair<std::string, cata_variant> data_obj( "character",
                             cata_variant::make<cata_variant_type::character_id>( as_character()->getID() ) );
                     event_data.insert( data_obj );
                     cata::event sent( e.death_event(), calendar::turn, std::move( event_data ) );
                     get_event_bus().send( sent );
                 }
                 die( e.get_source().resolve_creature() );
             }
         }
     }
     // Actually remove effects. This should be the last thing done in process_effects().
     for( size_t i = 0; i < rem_ids.size(); ++i ) {
         remove_effect( rem_ids[i], rem_bps[i] );
     }
 }
References add_msg_if_player(), as_character(), effect::death_event(), effect::decay(), die(), effects, effect::get_bp(), effect::get_death_message(), effect::get_duration(), get_event_bus(), effect::get_id(), effect::get_intensity(), effect::get_source(), is_avatar(), effect::kill_roll(), m_bad, string_id< body_part_type >::NULL_ID(), on_effect_int_change(), remove_effect(), resists_effect(), effect_source::resolve_creature(), event_bus::send(), and calendar::turn.
Referenced by Character::process_effects(), monster::process_effects(), and process_turn().
process_one_effect()
virtual void Creature::process_one_effect (effect & e, bool is_new) protected pure virtual
Processes one effect on the Creature.
Must not remove the effect, but can set it up for removal.
Implemented in monster, and Character.
Referenced by add_effect().
process_turn()
void Creature::process_turn () virtual
Processes effects and bonuses and allocates move points based on speed.
Reimplemented in npc, monster, and Character.
Definition at line 259 of file creature.cpp.
 {
     decrement_summon_timer();
     if( is_dead_state() ) {
         return;
     }
     reset_bonuses();
     process_effects();
     process_damage_over_time();
     // Call this in case any effects have changed our stats
     reset_stats();
     // add an appropriate number of moves
     if( !has_effect( effect_ridden ) ) {
         moves += get_speed();
     }
 }
References decrement_summon_timer(), effect_ridden, get_speed(), has_effect(), is_dead_state(), moves, process_damage_over_time(), process_effects(), reset_bonuses(), and reset_stats().
Referenced by Character::process_turn(), and monster::process_turn().
random_body_part()
bodypart_id Creature::random_body_part (bool main_parts_only = false) const
Definition at line 3030 of file creature.cpp.
 {
     const bodypart_id &bp = get_anatomy()->random_body_part();
     return  main_parts_only ? bp->main_part : bp ;
 }
References bp, get_anatomy(), body_part_type::main_part, and anatomy::random_body_part().
Referenced by talker_character::add_effect(), mattack::boomer_glow(), Character::hardcoded_effects(), talker_character::remove_effect(), and talker_monster::remove_effect().
ranged_target_size()
double Creature::ranged_target_size () const
Size of the target this creature presents to ranged weapons.
0.0 means unhittable, 1.0 means all projectiles going through this creature's tile will hit it.
Definition at line 547 of file ranged.cpp.
 {
     double stance_factor = 1.0;
     if( const Character *character = this->as_character() ) {
         if( character->is_crouching() || ( character->has_effect( effect_quadruped_full ) &&
                                            character->is_running() ) ) {
             stance_factor = 0.6;
         } else if( character->is_prone() ) {
             stance_factor = 0.25;
         }
     }
     if( has_flag( mon_flag_HARDTOSHOOT ) ) {
         switch( get_size() ) {
             case creature_size::tiny:
             case creature_size::small:
                 return stance_factor * occupied_tile_fraction( creature_size::tiny );
             case creature_size::medium:
                 return stance_factor * occupied_tile_fraction( creature_size::small );
             case creature_size::large:
                 return stance_factor * occupied_tile_fraction( creature_size::medium );
             case creature_size::huge:
                 return stance_factor * occupied_tile_fraction( creature_size::large );
             case creature_size::num_sizes:
                 debugmsg( "ERROR: Invalid Creature size class." );
                 break;
         }
     }
     return stance_factor * occupied_tile_fraction( get_size() );
 }
References as_character(), debugmsg, effect_quadruped_full, get_size(), has_flag(), huge, large, medium, mon_flag_HARDTOSHOOT, num_sizes, occupied_tile_fraction(), small, and tiny.
Referenced by npc::confident_throw_range(), draw_throw_aim(), projectile_attack(), explosion_handler::shrapnel(), and Target_attributes::Target_attributes().
remove_effect() [1/2]
bool Creature::remove_effect (const efftype_id & eff_id)
Definition at line 1756 of file creature.cpp.
 {
     return remove_effect( eff_id, bodypart_str_id::NULL_ID() );
 }
References string_id< body_part_type >::NULL_ID(), and remove_effect().
remove_effect() [2/2]
bool Creature::remove_effect (const efftype_id & eff_id, const bodypart_id & bp)
Removes a listed effect.
If the bodypart is not specified remove all effects of a given type, targeted or untargeted. Returns true if anything was removed.
Definition at line 1722 of file creature.cpp.
 {
     if( !has_effect( eff_id, bp.id() ) ) {
         //Effect doesn't exist, so do nothing
         return false;
     }
     const effect_type &type = eff_id.obj();
     if( Character *ch = as_character() ) {
         if( is_avatar() ) {
             if( !type.get_remove_message().empty() ) {
                 add_msg( type.lose_game_message_type( get_effect( eff_id, bp.id() ).get_intensity() ),
                          type.get_remove_message() );
             }
         }
         get_event_bus().send<event_type::character_loses_effect>( ch->getID(), bp.id(), eff_id );
     }
     // bp_null means remove all of a given effect id
     if( bp == bodypart_str_id::NULL_ID() ) {
         for( auto &it : ( *effects )[eff_id] ) {
             on_effect_int_change( eff_id, 0, it.first );
         }
         effects->erase( eff_id );
     } else {
         ( *effects )[eff_id].erase( bp.id() );
         on_effect_int_change( eff_id, 0, bp );
         // If there are no more effects of a given type remove the type map
         if( ( *effects )[eff_id].empty() ) {
             effects->erase( eff_id );
         }
     }
     return true;
 }
References add_msg(), as_character(), bp, character_loses_effect, effects, get_effect(), get_event_bus(), effect::get_intensity(), has_effect(), int_id< T >::id(), is_avatar(), string_id< body_part_type >::NULL_ID(), string_id< T >::obj(), on_effect_int_change(), event_bus::send(), and type.
Referenced by npc::act_on_danger_assessment(), iuse::antibiotic(), iuse::anticonvulsant(), iuse::antiparasitic(), apply_weariness(), iexamine::autodoc(), Character::calc_discomfort(), melee_actor::call(), game::cancel_activity_query(), shearing_activity_actor::canceled(), mattack::check_money_left(), vehicle::damage_direct(), monster::die(), npc::die(), Character::dismount(), game::do_regular_action(), glide_activity_actor::do_turn(), Character::drench(), iuse::eyedrops(), monster::find_dragged_foe(), activity_handlers::find_mount_do_turn(), milk_activity_actor::finish(), shearing_activity_actor::finish(), disable_activity_actor::finish(), glide_activity_actor::finish(), heal_actor::finish_using(), Character::forced_dismount(), iuse::fungicide(), talk_function::give_aid(), iuse::inhaler(), iexamine::ledge(), talk_function::lesser_give_aid(), Character::mend(), Character::mount_creature(), monster::move(), Character::move_effects(), monster::move_effects(), monster::move_to(), npc::move_to(), npc::npc_dismount(), mattack::nurse_check_up(), monster::nursebot_operate(), npc::on_load(), activity_handlers::operation_do_turn(), activity_handlers::operation_finish(), iuse::oxygen_bottle(), Character::perform_technique(), game::place_player(), game::place_player_overmap(), monster::plan(), turret_data::post_fire(), Character::process_bionic(), process_effects(), Character::process_effects(), monster::process_effects(), monster::process_turn(), Character::regen(), anonymous_namespace{monexamine.cpp}::remove_armor(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), remove_effect(), talker_character::remove_effect(), talker_monster::remove_effect(), anonymous_namespace{monexamine.cpp}::remove_harness(), anonymous_namespace{monexamine.cpp}::remove_leash(), anonymous_namespace{monexamine.cpp}::remove_saddle_from(), monster::reset_digestion(), avatar::reset_stats(), Character::restore_scent(), mattack::resurrect(), mattack::slimespring(), mattack::smash(), shearing_activity_actor::start(), anonymous_namespace{monexamine.cpp}::stop_leading(), anonymous_namespace{monexamine.cpp}::swap(), avatar_action::swim(), teleport::teleport_to_point(), iuse::thorazine(), iuse::towel_common(), activity_handlers::tree_communion_do_turn(), Character::try_remove_bear_trap(), Character::try_remove_crushed(), Character::try_remove_downed(), Character::try_remove_grab(), Character::try_remove_heavysnare(), Character::try_remove_impeding_effect(), Character::try_remove_lightsnare(), Character::try_remove_webs(), anonymous_namespace{monexamine.cpp}::untie_pet(), Character::update_body_wetness(), Character::update_bodytemp(), Character::update_frostbite(), Character::update_stomach(), Character::update_vitamins(), vehicle::use_harness(), Character::vomit(), wait(), Character::wake_up(), talk_function::wake_up(), debug_menu::wisheffect(), and mission::wrap_up().
remove_value()
void Creature::remove_value (const std::string & key)
Definition at line 1954 of file creature.cpp.
 {
     values.erase( key );
 }
References values.
Referenced by iuse::radiocontrol(), iuse::radiocontrol_tick(), rcdrive(), talker_character::remove_value(), talker_monster::remove_value(), Character::restore_scent(), game::setremoteveh(), and Character::update_body().
replace_with_npc_name()
std::string Creature::replace_with_npc_name (std::string input) const
This function replaces the "<npcname>" substring with the disp_name of this creature.
Its purpose is to avoid repeated code and improve source readability / maintainability.
Definition at line 3108 of file creature.cpp.
 {
     replace_substring( input, "<npcname>", disp_name(), true );
     return input;
 }
References disp_name(), and replace_substring().
Referenced by monster::add_msg_if_npc(), npc::add_msg_if_npc(), monster::add_msg_player_or_npc(), npc::add_msg_player_or_npc(), bionic_install_surgeon_preset::get_denial(), trade_preset::get_denial(), and popup_player_or_npc().
reset()
void Creature::reset () virtual
Handles stat and bonus reset.
Reimplemented in Character.
Definition at line 224 of file creature.cpp.
 {
     reset_bonuses();
     reset_stats();
 }
References reset_bonuses(), and reset_stats().
reset_bonuses()
void Creature::reset_bonuses () virtual
Resets the value of all bonus fields to 0.
Reimplemented in monster, and Character.
Definition at line 235 of file creature.cpp.
 {
     num_blocks = 1;
     num_dodges = 1;
     num_blocks_bonus = 0;
     num_dodges_bonus = 0;
     armor_bonus.clear();
     speed_bonus = 0;
     dodge_bonus = 0;
     block_bonus = 0;
     hit_bonus = 0;
     bash_bonus = 0;
     cut_bonus = 0;
     size_bonus = 0;
     bash_mult = 1.0f;
     cut_mult = 1.0f;
     melee_quiet = false;
     throw_resist = 0;
 }
References armor_bonus, bash_bonus, bash_mult, block_bonus, cut_bonus, cut_mult, dodge_bonus, hit_bonus, melee_quiet, num_blocks, num_blocks_bonus, num_dodges, num_dodges_bonus, size_bonus, speed_bonus, and throw_resist.
Referenced by Creature(), process_turn(), reset(), Character::reset_bonuses(), and monster::reset_bonuses().
reset_stats()
virtual void Creature::reset_stats () pure virtual
Resets stats, and applies effects in an idempotent manner.
Implemented in monster, Character, and avatar.
Referenced by process_turn(), and reset().
resists_effect()
bool Creature::resists_effect (const effect & e) const
Returns true if the creature resists an effect.
Definition at line 1928 of file creature.cpp.
 {
     for( const efftype_id &i : e.get_resist_effects() ) {
         if( has_effect( i ) ) {
             return true;
         }
     }
     for( const string_id<mutation_branch> &i : e.get_resist_traits() ) {
         if( has_trait( i ) ) {
             return true;
         }
     }
     return false;
 }
References effect::get_resist_effects(), effect::get_resist_traits(), has_effect(), and has_trait().
Referenced by Character::disp_info(), Character::effect_vitamin_mod(), get_encumbrance_description(), Character::get_limb_score(), Character::manipulator_score(), process_effects(), Character::process_one_effect(), monster::process_one_effect(), Character::recalc_speed_bonus(), and avatar::reset_stats().
schedule_effect() [1/3]
void Creature::schedule_effect (const effect & eff, bool force = false, bool deferred = false)
Schedules a new effect to be applied.
Used during effect processing to avoid invalidating current effects map.
Definition at line 1668 of file creature.cpp.
 {
     scheduled_effects.push( scheduled_effect{eff.get_id(), eff.get_duration(), eff.get_bp(),
                             eff.is_permanent(), eff.get_intensity(), force,
                             deferred} );
 }
References deferred, force, effect::get_bp(), effect::get_duration(), effect::get_id(), effect::get_intensity(), effect::is_permanent(), and scheduled_effects.
Referenced by Character::hardcoded_effects().
schedule_effect() [2/3]
void Creature::schedule_effect (const efftype_id & eff_id, const time_duration & dur, bodypart_id bp, bool permanent = false, int intensity = 0, bool force = false, bool deferred = false)
Definition at line 1674 of file creature.cpp.
 {
     scheduled_effects.push( scheduled_effect{eff_id, dur, bp,
                             permanent, intensity, force,
                             deferred} );
 }
References bp, deferred, dur, force, intensity, permanent, and scheduled_effects.
schedule_effect() [3/3]
void Creature::schedule_effect (const efftype_id & eff_id, const time_duration & dur, bool permanent = false, int intensity = 0, bool force = false, bool deferred = false)
Definition at line 1681 of file creature.cpp.
 {
     scheduled_effects.push( scheduled_effect{eff_id, dur, bodypart_str_id::NULL_ID(),
                             permanent, intensity, force, deferred} );
 }
References deferred, dur, force, intensity, string_id< body_part_type >::NULL_ID(), permanent, and scheduled_effects.
schedule_effect_removal() [1/2]
void Creature::schedule_effect_removal (const efftype_id & eff_id)
Definition at line 1765 of file creature.cpp.
 {
     return schedule_effect_removal( eff_id, bodypart_str_id::NULL_ID() );
 }
References string_id< body_part_type >::NULL_ID(), and schedule_effect_removal().
schedule_effect_removal() [2/2]
void Creature::schedule_effect_removal (const efftype_id & eff_id, const bodypart_id & bp)
Schedule effect removal.
Definition at line 1761 of file creature.cpp.
 {
     terminating_effects.push( terminating_effect{eff_id, bp} );
 }
References bp, and terminating_effects.
Referenced by Character::hardcoded_effects(), and schedule_effect_removal().
sees() [1/3]
bool Creature::sees (const Creature & critter) const override virtual
The functions check whether this creature can see the target.
The target may either be another creature (critter), or a specific point on the map.
The function that take another creature as input should check visibility of that creature (e.g. not digging, or otherwise invisible). They must than check whether the location of the other monster is visible.
Implements viewer.
Definition at line 358 of file creature.cpp.
 {
     // Creatures always see themselves (simplifies drawing).
     if( &critter == this ) {
         return true;
     }
     if( std::abs( posz() - critter.posz() ) > fov_3d_z_range ) {
         return false;
     }
     map &here = get_map();
     const int target_range = rl_dist( pos(), critter.pos() );
     if( target_range > MAX_VIEW_DISTANCE ) {
         return false;
     }
     if( critter.has_flag( mon_flag_ALWAYS_VISIBLE ) || ( has_flag( mon_flag_ALWAYS_SEES_YOU ) &&
             critter.is_avatar() ) ) {
         return true;
     }
     if( this->has_flag( mon_flag_ALL_SEEING ) ) {
         const monster *m = this->as_monster();
         return target_range <= std::max( m->type->vision_day, m->type->vision_night );
     }
     if( critter.is_hallucination() && !is_avatar() ) {
         // hallucinations are imaginations of the player character, npcs or monsters don't hallucinate.
         return false;
     }
     // Creature has stumbled into an invisible player and is now aware of them
     if( has_effect( effect_stumbled_into_invisible ) &&
         here.has_field_at( critter.pos(), field_fd_last_known ) && critter.is_avatar() ) {
         return true;
     }
     // This check is ridiculously expensive so defer it to after everything else.
     auto visible = []( const Character * ch ) {
         return ch == nullptr || !ch->is_invisible();
     };
     const Character *ch = critter.as_character();
     // Can always see adjacent monsters on the same level.
     // We also bypass lighting for vertically adjacent monsters, but still check for floors.
     if( target_range <= 1 ) {
         return ( posz() == critter.posz() || here.sees( pos(), critter.pos(), 1 ) ) && visible( ch );
     }
     // If we cannot see without any of the penalties below, bail now.
     if( !sees( critter.pos(), critter.is_avatar() ) ) {
         return false;
     }
     // Used with the Mind over Matter power Obscurity, to telepathically erase yourself from a target's perceptions
     if( has_effect( effect_telepathic_ignorance ) &&
         critter.has_effect( effect_telepathic_ignorance_self ) ) {
         return false;
     }
     if( ( target_range > 2 && critter.digging() &&
           here.has_flag( ter_furn_flag::TFLAG_DIGGABLE, critter.pos() ) ) ||
         ( critter.has_flag( mon_flag_CAMOUFLAGE ) && target_range > this->get_eff_per() ) ||
         ( critter.has_flag( mon_flag_WATER_CAMOUFLAGE ) &&
           target_range > this->get_eff_per() &&
           ( critter.is_likely_underwater() ||
             here.has_flag( ter_furn_flag::TFLAG_DEEP_WATER, critter.pos() ) ||
             ( here.has_flag( ter_furn_flag::TFLAG_SHALLOW_WATER, critter.pos() ) &&
               critter.get_size() < creature_size::medium ) ) ) ||
         ( critter.has_flag( mon_flag_NIGHT_INVISIBILITY ) &&
           here.light_at( critter.pos() ) <= lit_level::LOW ) ||
         critter.has_effect( effect_invisibility ) ||
         ( !is_likely_underwater() && critter.is_likely_underwater() &&
           majority_rule( critter.has_flag( mon_flag_WATER_CAMOUFLAGE ),
                          here.has_flag( ter_furn_flag::TFLAG_DEEP_WATER, critter.pos() ),
                          posz() != critter.posz() ) ) ||
         ( here.has_flag_ter_or_furn( ter_furn_flag::TFLAG_HIDE_PLACE, critter.pos() ) &&
           !( std::abs( posx() - critter.posx() ) <= 1 && std::abs( posy() - critter.posy() ) <= 1 &&
              std::abs( posz() - critter.posz() ) <= 1 ) ) ||
         ( here.has_flag_ter_or_furn( ter_furn_flag::TFLAG_SMALL_HIDE, critter.pos() ) &&
           critter.has_flag( mon_flag_SMALL_HIDER ) &&
           !( std::abs( posx() - critter.posx() ) <= 1 && std::abs( posy() - critter.posy() ) <= 1 &&
              std::abs( posz() - critter.posz() ) <= 1 ) ) ) {
         return false;
     }
     if( ch != nullptr ) {
         if( ch->is_crouching() || ch->has_effect( effect_all_fours ) || ch->is_prone() ||
             pos().z != critter.pos().z ) {
             const int coverage = std::max( here.obstacle_coverage( pos(), critter.pos() ),
                                            here.ledge_coverage( *this, critter.pos() ) );
             if( coverage < 30 ) {
                 return visible( ch );
             }
             float size_modifier = 1.0f;
             switch( ch->get_size() ) {
                 case creature_size::tiny:
                     size_modifier = 2.0f;
                     break;
                 case creature_size::small:
                     size_modifier = 1.4f;
                     break;
                 case creature_size::medium:
                     break;
                 case creature_size::large:
                     size_modifier = 0.6f;
                     break;
                 case creature_size::huge:
                     size_modifier = 0.15f;
                     break;
                 case creature_size::num_sizes:
                     debugmsg( "ERROR: Creature has invalid size class." );
                     break;
             }
             int profile = 120 / size_modifier;
             if( ch->is_crouching() || ch->has_effect( effect_all_fours ) ) {
                 profile *= 0.5;
             } else if( ch->is_prone() ) {
                 profile *= 0.275;
             }
             if( coverage < profile ) {
                 const int vision_modifier = std::max( 30 * ( 1 - coverage / profile ), 1 );
                 return target_range <= vision_modifier && visible( ch );
             }
             return false;
         }
     }
     return visible( ch );
 }
References abs(), as_character(), as_monster(), debugmsg, digging(), effect_all_fours, effect_invisibility, effect_stumbled_into_invisible, effect_telepathic_ignorance, effect_telepathic_ignorance_self, field_fd_last_known, fov_3d_z_range, get_eff_per(), get_map(), get_size(), Character::get_size(), has_effect(), map::has_field_at(), has_flag(), map::has_flag(), map::has_flag_ter_or_furn(), huge, is_avatar(), Character::is_crouching(), is_hallucination(), is_likely_underwater(), Character::is_prone(), large, map::ledge_coverage(), map::light_at(), LOW, majority_rule(), max(), MAX_VIEW_DISTANCE, medium, mon_flag_ALL_SEEING, mon_flag_ALWAYS_SEES_YOU, mon_flag_ALWAYS_VISIBLE, mon_flag_CAMOUFLAGE, mon_flag_NIGHT_INVISIBILITY, mon_flag_SMALL_HIDER, mon_flag_WATER_CAMOUFLAGE, num_sizes, map::obstacle_coverage(), pos(), posx(), posy(), posz(), rl_dist(), map::sees(), small, TFLAG_DEEP_WATER, TFLAG_DIGGABLE, TFLAG_HIDE_PLACE, TFLAG_SHALLOW_WATER, TFLAG_SMALL_HIDE, tiny, monster::type, mtype::vision_day, mtype::vision_night, and tripoint::z.
Referenced by mattack::acid(), monster::attack_at(), monster::attack_target(), auto_find_hostile_target(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), mattack::blow_whistle(), mattack::boomer(), mattack::boomer_glow(), mattack::brandish(), leap_actor::call(), gun_actor::call(), talker_monster_const::can_see_location(), vehicle::autodrive_controller::check_drivable(), mattack::copbot(), mattack::darkman(), mattack::dermatik(), mattack::dsa_drone_scan(), mattack::evolve_kill_strike(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), melee_actor::find_target(), mattack::flesh_golem(), mattack::flesh_tendril(), mattack::fungus_bristle(), map::get_moving_vehicle_targets(), handle_remove_fd_reality_tear_field(), mattack::howl(), game::list_monsters(), longpull(), mattack::lunge(), monster::melee_attack(), game::mon_info_update(), monster::move(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::plan(), monster::print_info(), mattack::pull_metal_weapon(), monster::rate_target(), mattack::rattle(), mdefense::return_fire(), mattack::science(), mattack::searchlight(), Character::sees(), sees(), mattack::shockstorm(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), mattack::slimespring(), mattack::spit_sap(), sting_get_target(), mattack::stretch_attack(), Target_attributes::Target_attributes(), mattack::tindalos_teleport(), monster::will_reach(), within_target_range(), and within_visual_range().
sees() [2/3]
bool Creature::sees (const tripoint & t, bool is_avatar = false, int range_mod = 0) const override virtual
Implements viewer.
Definition at line 492 of file creature.cpp.
 {
     if( std::abs( posz() - t.z ) > fov_3d_z_range ) {
         return false;
     }
     map &here = get_map();
     const int range_cur = sight_range( here.ambient_light_at( t ) );
     const int range_day = sight_range( default_daylight_level() );
     const int range_night = sight_range( 0 );
     const int range_max = std::max( range_day, range_night );
     const int range_min = std::min( range_cur, range_max );
     const int wanted_range = rl_dist( pos(), t );
     if( wanted_range <= range_min ||
         ( wanted_range <= range_max &&
           here.ambient_light_at( t ) > here.get_cache_ref( t.z ).natural_light_level_cache ) ) {
         int range = 0;
         if( here.ambient_light_at( t ) > here.get_cache_ref( t.z ).natural_light_level_cache ) {
             range = MAX_VIEW_DISTANCE;
         } else {
             range = range_min;
         }
         if( has_effect( effect_no_sight ) ) {
             range = 1;
         }
         if( range_mod > 0 ) {
             range = std::min( range, range_mod );
         }
         if( is_avatar ) {
             // Special case monster -> player visibility, forcing it to be symmetric with player vision.
             const float player_visibility_factor = get_player_character().visibility() / 100.0f;
             int adj_range = std::floor( range * player_visibility_factor );
             return adj_range >= wanted_range &&
                    here.get_cache_ref( pos().z ).seen_cache[pos().x][pos().y] > LIGHT_TRANSPARENCY_SOLID;
         } else {
             return here.sees( pos(), t, range );
         }
     } else {
         return false;
     }
 }
References abs(), map::ambient_light_at(), default_daylight_level(), effect_no_sight, floor(), fov_3d_z_range, map::get_cache_ref(), get_map(), get_player_character(), has_effect(), is_avatar(), LIGHT_TRANSPARENCY_SOLID, max(), MAX_VIEW_DISTANCE, min(), level_cache::natural_light_level_cache, pos(), posz(), rl_dist(), level_cache::seen_cache, map::sees(), sight_range(), Character::visibility(), tripoint::x, tripoint::y, and tripoint::z.
sees() [3/3]
bool Creature::sees (const tripoint_bub_ms & t, bool is_avatar = false, int range_mod = 0) const override virtual
Implements viewer.
Definition at line 534 of file creature.cpp.
 {
     return sees( t.raw(), is_avatar, range_mod );
 }
References is_avatar(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and sees().
select_blocking_part()
bodypart_id Creature::select_blocking_part (bool arm, bool leg, bool nonstandard) const
Definition at line 3025 of file creature.cpp.
 {
     return anatomy( get_all_body_parts() ).select_blocking_part( this, arm, leg, nonstandard );
 }
References get_all_body_parts(), and anatomy::select_blocking_part().
Referenced by Character::block_hit().
select_body_part()
bodypart_id Creature::select_body_part (int min_hit, int max_hit, bool can_attack_high, int hit_roll) const
Definition at line 3013 of file creature.cpp.
 {
     add_msg_debug( debugmode::DF_CREATURE, "hit roll = %d", hit_roll );
     if( !is_monster() && !can_attack_high ) {
         can_attack_high = as_character()->is_on_ground();
     }
     return anatomy( get_all_body_parts() ).select_body_part( min_hit, max_hit, can_attack_high,
             hit_roll );
 }
References add_msg_debug, as_character(), can_attack_high(), debugmode::DF_CREATURE, get_all_body_parts(), hit_roll(), is_monster(), Character::is_on_ground(), and anatomy::select_body_part().
Referenced by melee_actor::call(), deal_melee_hit(), and Character::melee_attack_abstract().
select_body_part_projectile_attack()
projectile_attack_results Creature::select_body_part_projectile_attack (const projectile & proj, double goodhit, double missed_by) const private
Definition at line 994 of file creature.cpp.
 {
     projectile_attack_results ret( proj );
     const bool magic = proj.proj_effects.count( "MAGIC" ) > 0;
     double hit_value = missed_by + rng_float( -0.5, 0.5 );
     if( magic ) {
         // Best possible hit
         hit_value = -0.5;
     }
     // Range is -0.5 to 1.5 -> missed_by will be [1, 0], so the rng addition to it
     // will push it to at most 1.5 and at least -0.5
     ret.bp_hit = get_anatomy()->select_body_part_projectile_attack( -0.5, 1.5, hit_value );
     float crit_mod = get_crit_factor( ret.bp_hit );
     const float crit_multiplier = proj.critical_multiplier;
     const float std_hit_mult = std::sqrt( 2.0 * crit_multiplier );
     if( magic ) {
         // do nothing special, no damage mults, nothing
     } else if( goodhit < accuracy_headshot &&
                ret.max_damage * crit_multiplier > get_hp_max( ret.bp_hit ) ) {
         ret.message = _( "Critical!!" );
         ret.gmtSCTcolor = m_headshot;
         ret.damage_mult *= rng_float( 0.5 + 0.45 * crit_mod, 0.75 + 0.3 * crit_mod ); // ( 0.95, 1.05 )
         ret.damage_mult *= std_hit_mult + ( crit_multiplier - std_hit_mult ) * crit_mod;
         ret.is_crit = true;
     } else if( goodhit < accuracy_critical &&
                ret.max_damage * crit_multiplier > get_hp_max( ret.bp_hit ) ) {
         ret.message = _( "Critical!" );
         ret.gmtSCTcolor = m_critical;
         ret.damage_mult *= rng_float( 0.5 + 0.25 * crit_mod, 0.75 + 0.25 * crit_mod ); // ( 0.75, 1.0 )
         ret.damage_mult *= std_hit_mult + ( crit_multiplier - std_hit_mult ) * crit_mod;
         ret.is_crit = true;
     } else if( goodhit < accuracy_goodhit ) {
         ret.message = _( "Good hit!" );
         ret.gmtSCTcolor = m_good;
         ret.damage_mult *= rng_float( 0.5, 0.75 );
         ret.damage_mult *= std_hit_mult;
     } else if( goodhit < accuracy_standard ) {
         ret.damage_mult *= rng_float( 0.5, 1 );
     } else if( goodhit < accuracy_grazing ) {
         ret.message = _( "Grazing hit." );
         ret.gmtSCTcolor = m_grazing;
         ret.damage_mult *= rng_float( 0, .25 );
     }
     return ret;
 }
References _, accuracy_critical, accuracy_headshot, projectile::critical_multiplier, get_anatomy(), get_crit_factor(), get_hp_max(), m_headshot, projectile::proj_effects, cata::hash64_detail::ret, rng_float(), anatomy::select_body_part_projectile_attack(), and sqrt().
Referenced by Character::add_msg_player_or_say().
set_all_parts_hp_cur()
void Creature::set_all_parts_hp_cur (int set)
Definition at line 2477 of file creature.cpp.
 {
     for( std::pair<const bodypart_str_id, bodypart> &elem : body ) {
         elem.second.set_hp_cur( set );
     }
 }
References body.
Referenced by Character::die(), Character::hardcoded_effects(), spell_effect::pain_split(), and talker_character::set_all_parts_hp_cur().
set_all_parts_hp_to_max()
void Creature::set_all_parts_hp_to_max ()
Definition at line 2484 of file creature.cpp.
 {
     for( std::pair<const bodypart_str_id, bodypart> &elem : body ) {
         elem.second.set_hp_to_max();
     }
 }
References body.
Referenced by Character::environmental_revert_effect(), and tutorial_game::init().
set_all_parts_temp_conv()
void Creature::set_all_parts_temp_conv (units::temperature set)
Definition at line 2460 of file creature.cpp.
 {
     for( std::pair<const bodypart_str_id, bodypart> &elem : body ) {
         if( elem.first->has_flag( json_flag_IGNORE_TEMP ) ) {
             continue;
         }
         elem.second.set_temp_conv( set );
     }
 }
References body, and json_flag_IGNORE_TEMP.
Referenced by Character::normalize(), and Character::update_bodytemp().
set_all_parts_temp_cur()
void Creature::set_all_parts_temp_cur (units::temperature set)
Definition at line 2450 of file creature.cpp.
 {
     for( std::pair<const bodypart_str_id, bodypart> &elem : body ) {
         if( elem.first->has_flag( json_flag_IGNORE_TEMP ) ) {
             continue;
         }
         elem.second.set_temp_cur( set );
     }
 }
References body, and json_flag_IGNORE_TEMP.
Referenced by suffer::from_chemimbalance(), and Character::update_bodytemp().
set_all_parts_wetness()
void Creature::set_all_parts_wetness (int set)
Definition at line 2470 of file creature.cpp.
 {
     for( std::pair<const bodypart_str_id, bodypart> &elem : body ) {
         elem.second.set_wetness( set );
     }
 }
References body.
Referenced by iuse::towel_common().
set_anatomy()
void Creature::set_anatomy (const anatomy_id & anat)
Definition at line 2162 of file creature.cpp.
 {
     creature_anatomy = anat;
 }
References creature_anatomy.
Referenced by Character::Character(), and monster::monster().
set_armor_res_bonus()
void Creature::set_armor_res_bonus (int narm, const damage_type_id & dt) virtual
Definition at line 2868 of file creature.cpp.
 {
     armor_bonus[dt] = narm;
 }
References armor_bonus.
set_bash_bonus()
void Creature::set_bash_bonus (int nbash) virtual
Definition at line 2894 of file creature.cpp.
 {
     bash_bonus = nbash;
 }
References bash_bonus.
set_bash_mult()
void Creature::set_bash_mult (float nbashmult) virtual
Definition at line 2932 of file creature.cpp.
 {
     bash_mult = nbashmult;
 }
References bash_mult.
set_block_bonus()
void Creature::set_block_bonus (int nblock) virtual
Definition at line 2886 of file creature.cpp.
 {
     block_bonus = nblock;
 }
References block_bonus.
set_body()
void Creature::set_body ()
Definition at line 2172 of file creature.cpp.
 {
     body.clear();
     for( const bodypart_id &bp : get_anatomy()->get_bodyparts() ) {
         body.emplace( bp.id(), bodypart( bp.id() ) );
     }
 }
References body, bp, get_anatomy(), and int_id< T >::id().
Referenced by avatar::create(), vehicle_part::get_targeting_npc(), monster::monster(), Character::normalize(), avatar::randomize(), npc::randomize(), player_difficulty::reset_npc(), and standard_npc::standard_npc().
set_cut_bonus()
void Creature::set_cut_bonus (int ncut) virtual
Definition at line 2898 of file creature.cpp.
 {
     cut_bonus = ncut;
 }
References cut_bonus.
set_cut_mult()
void Creature::set_cut_mult (float ncutmult) virtual
Definition at line 2936 of file creature.cpp.
 {
     cut_mult = ncutmult;
 }
References cut_mult.
set_dodge_bonus()
void Creature::set_dodge_bonus (float ndodge) virtual
Definition at line 2881 of file creature.cpp.
 {
     dodge_bonus = ndodge;
 }
References dodge_bonus.
set_fake()
void Creature::set_fake (bool fake_value) virtual
Sets a Creature's fake boolean.
Definition at line 1523 of file creature.cpp.
 {
     fake = fake_value;
 }
References fake.
Referenced by vehicle_part::get_targeting_npc(), make_fake_npc(), gun_actor::shoot(), basecamp::start_clearcut(), and basecamp::start_cut_logs().
set_hit_bonus()
void Creature::set_hit_bonus (float nhit) virtual
Definition at line 2890 of file creature.cpp.
 {
     hit_bonus = nhit;
 }
References hit_bonus.
set_killer()
void Creature::set_killer (Creature * killer) protected
Definition at line 2031 of file creature.cpp.
 {
     // Only the first killer will be stored, calling set_killer again with a different
     // killer would mean it's called on a dead creature and therefore ignored.
     if( killer != nullptr && !killer->is_fake() && this->killer == nullptr ) {
         this->killer = killer;
     }
 }
References is_fake(), and killer.
Referenced by monster::apply_damage(), monster::die(), Character::die(), and Character::on_hurt().
set_location()
void Creature::set_location (const tripoint_abs_ms & loc) protected
Definition at line 207 of file creature.cpp.
 {
     location = loc;
 }
References location.
Referenced by npc::import_and_clean(), move_to(), avatar::set_location(), monster::spawn(), and npc::spawn_at_precise().
set_melee_quiet()
void Creature::set_melee_quiet (bool nquiet) virtual
Definition at line 2941 of file creature.cpp.
 {
     melee_quiet = nquiet;
 }
References melee_quiet.
set_moves()
void Creature::set_moves (int nmoves)
Definition at line 2012 of file creature.cpp.
 {
     moves = nmoves;
 }
References moves.
Referenced by activity_on_turn_move_loot(), activity_handlers::build_do_turn(), game::climb_down_using(), complete_construction(), spell_effect::dash(), debug_menu::debug(), do_aim(), melee_actor::do_grab(), npc::do_player_activity(), game::do_regular_action(), player_activity::do_turn(), autodrive_activity_actor::do_turn(), disassemble_activity_actor::do_turn(), craft_activity_actor::do_turn(), unload_loot_activity_actor::do_turn(), game::exam_appliance(), game::exam_vehicle(), npc::execute_action(), fetch_activity(), mattack::formblob(), generic_multi_activity_handler(), handbrake(), Character::hardcoded_effects(), Character::invoke_item(), game::is_game_over(), npc::move(), avatar_action::move(), npc::move_to(), npc::mug_player(), Character::pause(), vehicle::pldrive(), activity_handlers::pulp_do_turn(), game::quickload(), activity_handlers::repair_item_do_turn(), sleep(), game::start_game(), vehicle::turrets_aim(), aim_activity_actor::unload_RAS_weapon(), heal_actor::use(), Character::use(), and game::vertical_move().
set_num_blocks_bonus()
void Creature::set_num_blocks_bonus (int nblocks) virtual
Definition at line 2853 of file creature.cpp.
 {
     num_blocks_bonus = nblocks;
 }
References num_blocks_bonus.
set_pain()
void Creature::set_pain (int npain) virtual
Reimplemented in Character.
Definition at line 1985 of file creature.cpp.
 {
     npain = std::max( npain, 0 );
     if( pain != npain ) {
         pain = npain;
         on_stat_change( "pain", pain );
     }
 }
References max(), on_stat_change(), and pain.
Referenced by mod_pain_noresist(), and Character::set_pain().
set_part_damage_bandaged()
void Creature::set_part_damage_bandaged (const bodypart_id & id, int set)
Definition at line 2366 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::set_damage_bandaged, set );
 }
References bodypart::set_damage_bandaged(), and set_part_helper().
Referenced by heal_actor::finish_using(), and Character::regen().
set_part_damage_disinfected()
void Creature::set_part_damage_disinfected (const bodypart_id & id, int set)
Definition at line 2361 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::set_damage_disinfected, set );
 }
References bodypart::set_damage_disinfected(), and set_part_helper().
Referenced by iexamine::autodoc(), heal_actor::finish_using(), and Character::regen().
set_part_encumbrance_data()
void Creature::set_part_encumbrance_data (const bodypart_id & id, const encumbrance_data & set)
Definition at line 2371 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::set_encumbrance_data, set );
 }
References bodypart::set_encumbrance_data(), and set_part_helper().
Referenced by Character::calc_encumbrance().
set_part_frostbite_timer()
void Creature::set_part_frostbite_timer (const bodypart_id & id, int set)
Definition at line 2391 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::set_frostbite_timer, set );
 }
References bodypart::set_frostbite_timer(), and set_part_helper().
Referenced by Character::update_frostbite().
set_part_healed_total()
void Creature::set_part_healed_total (const bodypart_id & id, int set)
Definition at line 2356 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::set_healed_total, set );
 }
References bodypart::set_healed_total(), and set_part_helper().
set_part_hp_cur()
void Creature::set_part_hp_cur (const bodypart_id & id, int set) virtual
Reimplemented in Character.
Definition at line 2342 of file creature.cpp.
 {
     bool was_broken = is_avatar() && as_character()->is_limb_broken( id );
     set_part_helper( *this, id, &bodypart::set_hp_cur, set );
     if( !was_broken && is_avatar() && as_character()->is_limb_broken( id ) ) {
         get_event_bus().send<event_type::broken_bone>( as_character()->getID(), id );
     }
 }
References as_character(), broken_bone, get_event_bus(), Character::getID(), base_camps::id, is_avatar(), Character::is_limb_broken(), event_bus::send(), bodypart::set_hp_cur(), and set_part_helper().
Referenced by Character::set_part_hp_cur().
set_part_hp_max()
void Creature::set_part_hp_max (const bodypart_id & id, int set)
Definition at line 2351 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::set_hp_max, set );
 }
References bodypart::set_hp_max(), and set_part_helper().
set_part_mut_drench()
void Creature::set_part_mut_drench (const bodypart_id & id, std::pair< water_tolerance, int > set)
Definition at line 2396 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::set_mut_drench, set );
 }
References bodypart::set_mut_drench(), and set_part_helper().
Referenced by Character::drench_mut_calc().
set_part_temp_conv()
void Creature::set_part_temp_conv (const bodypart_id & id, units::temperature set)
Definition at line 2386 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::set_temp_conv, set );
 }
References set_part_helper(), and bodypart::set_temp_conv().
Referenced by Character::update_bodytemp().
set_part_temp_cur()
void Creature::set_part_temp_cur (const bodypart_id & id, units::temperature set)
Definition at line 2381 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::set_temp_cur, set );
 }
References set_part_helper(), and bodypart::set_temp_cur().
Referenced by Character::update_bodytemp().
set_part_wetness()
void Creature::set_part_wetness (const bodypart_id & id, int set)
Definition at line 2376 of file creature.cpp.
 {
     set_part_helper( *this, id, &bodypart::set_wetness, set );
 }
References set_part_helper(), and bodypart::set_wetness().
Referenced by Character::drench(), and Character::update_body_wetness().
set_pos_only()
void Creature::set_pos_only (const tripoint & p) protected
Definition at line 202 of file creature.cpp.
 {
     location = get_map().getglobal( p );
 }
References get_map(), map::getglobal(), and location.
Referenced by monster::monster(), setpos(), monster::spawn(), standard_npc::standard_npc(), and Character::uncanny_dodge().
set_reachable_zone()
void Creature::set_reachable_zone (int zone) inline
Definition at line 761 of file creature.h.
{
             reachable_zone = zone;
         }
set_speed_base()
void Creature::set_speed_base (int nspeed) virtual
Definition at line 2873 of file creature.cpp.
 {
     speed_base = nspeed;
 }
References speed_base.
Referenced by blobify(), iuse::can_goo(), iuse::extinguisher(), mattack::formblob(), trapfunc::glow(), trapfunc::goo(), iuse::granade_act(), monster::init_from_item(), monster::monster(), monster::on_load(), monster::poly(), poly_keep_speed(), monster::process_one_effect(), player_difficulty::reset_npc(), and mattack::resurrect().
set_speed_bonus()
void Creature::set_speed_bonus (int nspeed) virtual
Definition at line 2877 of file creature.cpp.
 {
     speed_bonus = nspeed;
 }
References speed_bonus.
Referenced by monster::process_effects(), and player_difficulty::reset_npc().
set_summon_time()
void Creature::set_summon_time (const time_duration & length)
Definition at line 2045 of file creature.cpp.
 {
     lifespan_end = calendar::turn + length;
 }
References length, lifespan_end, and calendar::turn.
Referenced by add_summoned_mon(), iuse::directional_hologram(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster().
set_summoner() [1/2]
void Creature::set_summoner (character_id summoner)
Definition at line 2078 of file creature.cpp.
 {
     this->summoner = summoner;
 }
References summoner.
set_summoner() [2/2]
void Creature::set_summoner (Creature * summoner)
Definition at line 2071 of file creature.cpp.
 {
     if( summoner->as_character() != nullptr ) {
         this->summoner = summoner->as_character()->getID();
     }
 }
References summoner.
Referenced by add_summoned_mon().
set_throw_resist()
void Creature::set_throw_resist (int nthrowres) virtual
Definition at line 2945 of file creature.cpp.
 {
     throw_resist = nthrowres;
 }
References throw_resist.
set_value()
void Creature::set_value (const std::string & key, const std::string & value)
Definition at line 1949 of file creature.cpp.
 {
     values[ key ] = value;
 }
References values.
Referenced by can_do_activity_there(), Character::Character(), check_stealing(), basecamp::choose_new_leader(), Character::deactivate_bionic(), game::do_regular_action(), pickup_activity_actor::do_turn(), mattack::dsa_drone_scan(), consume_activity_actor::finish(), talk_function::handle_outpost_mission(), talk_function::hospital_raid_return(), Character::mod_stamina(), iuse::radiocontrol(), rcdrive(), talker_character::set_value(), talker_monster::set_value(), game::setremoteveh(), Character::update_body(), and change_scent_iuse::use().
setpos()
void Creature::setpos (const tripoint & p)
Definition at line 188 of file creature.cpp.
 {
     const tripoint_abs_ms old_loc = get_location();
     set_pos_only( p );
     on_move( old_loc );
 }
References get_location(), on_move(), and set_pos_only().
Referenced by auto_find_hostile_target(), iexamine::bars(), map::board_vehicle(), leap_actor::call(), iexamine::chainfence(), character_push_effects(), game::climb_down_using(), spell_effect::directed_push(), Character::dismount(), map::displace_vehicle(), melee_actor::do_grab(), mattack::evolve_kill_strike(), game::fling_creature(), Character::forced_dismount(), game::grabbed_veh_move(), Character::knock_back_to(), monster::knock_back_to(), game::knockback(), iexamine::ledge(), trapfunc::ledge(), make_fake_npc(), Character::mount_creature(), monster::move_to(), npc::move_to(), npc::npc_dismount(), vehicle::part_collision(), game::peek(), Character::perform_technique(), game::phasing_move(), npc::place_on_map(), start_location::place_player(), game::place_player(), avatar_action::plthrow(), monster::push_to(), map::rotate(), talker_character::set_pos(), sinkhole_safety_roll(), Character::stagger(), game::start_game(), game::swap_critters(), swap_pos(), avatar_action::swim(), mattack::tindalos_teleport(), trapfunc::tripwire(), game::update_map(), vehicle::use_harness(), game::validate_mounted_npcs(), and game::vertical_move().
sight_range()
virtual int Creature::sight_range (float light_level) const pure virtual
How far the creature sees under the given light.
Creature cannot see places outside this range.
Parameters
light_level See game::light_level.
Implemented in monster, and Character.
Referenced by sees().
size_melee_penalty()
int Creature::size_melee_penalty () const
Definition at line 700 of file creature.cpp.
 {
     switch( get_size() ) {
         case creature_size::tiny:
             return 30;
         case creature_size::small:
             return 15;
         case creature_size::medium:
             return 0;
         case creature_size::large:
             return -10;
         case creature_size::huge:
             return -20;
         case creature_size::num_sizes:
             debugmsg( "ERROR: Creature has invalid size class." );
             return 0;
     }
     debugmsg( "Invalid target size %d", get_size() );
     return 0;
 }
References debugmsg, get_size(), huge, large, medium, num_sizes, small, and tiny.
Referenced by deal_melee_attack(), and item::effective_dps().
skin_name()
virtual std::string Creature::skin_name () const pure virtual
Implemented in monster, and Character.
Referenced by monster::melee_attack(), and messaging_projectile_attack().
speed_rating()
virtual float Creature::speed_rating () const pure virtual
Returns an approximate number of tiles this creature can travel per turn.
Implemented in npc, monster, and Character.
Referenced by npc::enough_time_to_reload().
stability_roll()
virtual float Creature::stability_roll () const pure virtual
Implemented in monster, and Character.
store()
void Creature::store (JsonOut & jsout) const protected
These two functions are responsible for storing and loading the members of this class to/from json data.
All classes that inherit from this class should implement their own version of these functions. They are not virtual on purpose, as it's not needed. Every implementation of those functions should a) call the same function with the same parameters of the super class and b) store/load their own members, but not members of any sub or super class.
The functions are (on purpose) not part of the json serialize/deserialize system (defined in json.h). The Creature class is incomplete, there won't be any instance of that class alone, but there will be instances of sub classes (e.g. player, monster). Those (complete) classes implement the deserialize/serialize interface of json. That way only one json object per npc/player/monster instance is created (inside of the serialize function). E.g. player::serialize() looks like this: json.start_object();store(json);json.end_object() player::store than stores the members of the player class, and it calls Character::store, which stores the members of the Character class and calls Creature::store, which stores the members of the Creature class. All data goes into the single json object created in player::serialize.
Definition at line 3726 of file savegame_json.cpp.
 {
     jsout.member( "location", location );
     jsout.member( "moves", moves );
     jsout.member( "pain", pain );
     // killer is not stored, it's temporary anyway, any creature that has a non-null
     // killer is dead (as per definition) and should not be stored.
     jsout.member( "effects", *effects );
     jsout.member( "damage_over_time_map", damage_over_time_map );
     jsout.member( "values", values );
     jsout.member( "blocks_left", num_blocks );
     jsout.member( "dodges_left", num_dodges );
     jsout.member( "num_blocks_bonus", num_blocks_bonus );
     jsout.member( "num_dodges_bonus", num_dodges_bonus );
     jsout.member( "armor_bonus", armor_bonus );
     jsout.member( "speed", speed_base );
     jsout.member( "speed_bonus", speed_bonus );
     jsout.member( "dodge_bonus", dodge_bonus );
     jsout.member( "block_bonus", block_bonus );
     jsout.member( "hit_bonus", hit_bonus );
     jsout.member( "bash_bonus", bash_bonus );
     jsout.member( "cut_bonus", cut_bonus );
     jsout.member( "bash_mult", bash_mult );
     jsout.member( "cut_mult", cut_mult );
     jsout.member( "melee_quiet", melee_quiet );
     jsout.member( "throw_resist", throw_resist );
     jsout.member( "archery_aim_counter", archery_aim_counter );
     jsout.member( "last_updated", last_updated );
     jsout.member( "body", body );
     jsout.member( "lifespan_end", lifespan_end );
     // fake is not stored, it's temporary anyway, only used to fire with a gun.
 }
References location, JsonOut::member(), item_pocket::moves(), and pain.
Referenced by Character::store(), and monster::store().
stumble_invis()
bool Creature::stumble_invis (const Creature & player, bool stumblemsg = true)
Definition at line 1389 of file creature.cpp.
 {
     // DEBUG insivibility can't be seen through
     if( player.has_trait( trait_DEBUG_CLOAK ) ) {
         return false;
     }
     if( this == &player || !is_adjacent( &player, true ) ) {
         return false;
     }
     if( stumblemsg ) {
         const bool player_sees = player.sees( *this );
         add_msg( m_bad, _( "%s stumbles into you!" ), player_sees ? this->disp_name( false,
                  true ) : _( "Something" ) );
     }
     add_effect( effect_stumbled_into_invisible, 6_seconds );
     map &here = get_map();
     // Mark last known location, or extend duration if exists
     if( here.has_field_at( player.pos(), field_fd_last_known ) ) {
         here.set_field_age( player.pos(), field_fd_last_known, 0_seconds );
     } else {
         here.add_field( player.pos(), field_fd_last_known );
     }
     moves = 0;
     return true;
 }
References _, add_effect(), map::add_field(), add_msg(), disp_name(), effect_stumbled_into_invisible, field_fd_last_known, get_map(), map::has_field_at(), is_adjacent(), m_bad, moves, player, map::set_field_age(), and trait_DEBUG_CLOAK.
Referenced by monster::attack_at(), npc::move_to(), and Character::on_hit().
symbol()
virtual const std::string& Creature::symbol () const pure virtual
Creature symbol.
Implemented in monster, and Character.
Referenced by draw().
symbol_color()
virtual nc_color Creature::symbol_color () const pure virtual
Creature symbol background color.
Implemented in monster, and Character.
Referenced by draw().
uncanny_dodge()
virtual bool Creature::uncanny_dodge () inline virtual
Reimplemented in Character.
Definition at line 755 of file creature.h.
{
             return false;
         }
Referenced by melee_actor::call(), dodge_check(), mattack::flame(), mattack::fungus_fortify(), mattack::growplants(), sting_shoot(), mattack::taze(), and mattack::vine().
weight_capacity()
units::mass Creature::weight_capacity () const virtual
Reimplemented in monster, and Character.
Definition at line 2950 of file creature.cpp.
 {
     units::mass base_carry = 13_kilogram;
     switch( get_size() ) {
         case creature_size::tiny:
             base_carry /= 4;
             break;
         case creature_size::small:
             base_carry /= 2;
             break;
         case creature_size::medium:
         default:
             break;
         case creature_size::large:
             base_carry *= 2;
             break;
         case creature_size::huge:
             base_carry *= 4;
             break;
     }
     return base_carry;
 }
References get_size(), huge, large, medium, small, and tiny.
Referenced by Character::weight_capacity().
witness_thievery()
virtual void Creature::witness_thievery (item * it) pure virtual
Implemented in npc, monster, and avatar.
Member Data Documentation
archery_aim_counter
int Creature::archery_aim_counter = 0
Definition at line 1255 of file creature.h.
Referenced by practice_archery_proficiency().
armor_bonus
std::map<damage_type_id, float> Creature::armor_bonus protected
Definition at line 1221 of file creature.h.
Referenced by get_armor_res_bonus(), Character::get_armor_type(), reset_bonuses(), and set_armor_res_bonus().
bash_bonus
int Creature::bash_bonus = 0 protected
Definition at line 1228 of file creature.h.
Referenced by get_bash_bonus(), mod_bash_bonus(), reset_bonuses(), and set_bash_bonus().
bash_mult
float Creature::bash_mult = 0.0f protected
Definition at line 1232 of file creature.h.
Referenced by get_bash_mult(), reset_bonuses(), and set_bash_mult().
block_bonus
int Creature::block_bonus = 0 protected
Definition at line 1226 of file creature.h.
Referenced by Character::block_hit(), get_block_bonus(), mod_block_bonus(), reset_bonuses(), and set_block_bonus().
body
std::map<bodypart_str_id, bodypart> Creature::body protected
this is the actual body of the creature
Definition at line 787 of file creature.h.
Referenced by Character::calc_all_parts_hp(), get_all_body_parts(), get_all_body_parts_of_type(), get_all_body_parts_with_flag(), get_body(), Character::get_limb_score(), get_part(), get_part_id(), has_atleast_one_wet_part(), Character::manipulator_score(), Character::place_corpse(), Character::recalculate_bodyparts(), set_all_parts_hp_cur(), set_all_parts_hp_to_max(), set_all_parts_temp_conv(), set_all_parts_temp_cur(), set_all_parts_wetness(), and set_body().
cmat_flameres
const std::set< material_id > Creature::cmat_flameres static
Initial value:
{
    material_stone, material_kevlar, material_steel
}
Definition at line 748 of file creature.h.
Referenced by map::monster_in_field().
cmat_flammable
const std::set< material_id > Creature::cmat_flammable static
Initial value:
{
    material_paper, material_powder, material_wood,
    material_cotton, material_wool
}
Definition at line 747 of file creature.h.
Referenced by projectile::apply_effects_damage(), trapfunc::lava(), and map::monster_in_field().
cmat_flesh
const std::set< material_id > Creature::cmat_flesh static
Initial value:
{
    material_flesh, material_iflesh
}
Definition at line 745 of file creature.h.
Referenced by projectile::apply_effects_damage(), mattack::evolve_kill_strike(), monster::is_immune_effect(), trapfunc::lava(), and map::monster_in_field().
cmat_fleshnveg
const std::set< material_id > Creature::cmat_fleshnveg static
Initial value:
{
    material_flesh,  material_iflesh, material_veggy
}
Definition at line 746 of file creature.h.
Referenced by map::monster_in_field().
creature_anatomy
anatomy_id Creature::creature_anatomy = anatomy_id("default_anatomy") protected
anatomy is the plan of the creature's body
Definition at line 785 of file creature.h.
Referenced by get_anatomy(), Character::recalculate_bodyparts(), and set_anatomy().
cut_bonus
int Creature::cut_bonus = 0 protected
Definition at line 1229 of file creature.h.
Referenced by get_cut_bonus(), mod_cut_bonus(), reset_bonuses(), and set_cut_bonus().
cut_mult
float Creature::cut_mult = 0.0f protected
Definition at line 1233 of file creature.h.
Referenced by get_cut_mult(), reset_bonuses(), and set_cut_mult().
damage_over_time_map
std::vector<damage_over_time_data> Creature::damage_over_time_map protected
Definition at line 1208 of file creature.h.
Referenced by add_damage_over_time(), and process_damage_over_time().
dispersion_for_even_chance_of_good_hit
std::vector< int > Creature::dispersion_for_even_chance_of_good_hit static
Initial value:
= { {
        1731, 859, 573, 421, 341, 286, 245, 214, 191, 175,
        151, 143, 129, 118, 114, 107, 101, 94, 90, 78,
        78, 78, 74, 71, 68, 66, 62, 61, 59, 57,
        46, 46, 46, 46, 46, 46, 45, 45, 44, 42,
        41, 41, 39, 39, 38, 37, 36, 35, 34, 34,
        33, 33, 32, 30, 30, 30, 30, 29, 28
    }
}
Definition at line 1271 of file creature.h.
Referenced by load_hit_range(), and range_with_even_chance_of_good_hit().
dodge_bonus
float Creature::dodge_bonus = 0.0f protected
Definition at line 1225 of file creature.h.
Referenced by get_dodge_bonus(), mod_dodge_bonus(), reset_bonuses(), and set_dodge_bonus().
effects
pimpl<effects_map> Creature::effects protected
Definition at line 1204 of file creature.h.
Referenced by add_effect(), monster::can_act(), Character::can_melee(), Character::check_and_recover_morale(), clear_effects(), Character::conduct_blood_analysis(), Character::count_mabuff_flag(), monster::deal_projectile_attack(), Character::disp_info(), Character::effect_vitamin_mod(), get_effect(), monster::get_effect_status(), get_effects(), get_effects_from_bp(), get_effects_with_flag(), Character::get_overlay_ids(), Character::get_overlay_ids_when_override_look(), has_effect(), has_effect_with_flag(), Character::has_mabuff(), Character::has_mabuff_flag(), Character::healing_rate_medicine(), npc::import_and_clean(), Character::is_melee_bash_damage_cap_bonus(), Character::is_quiet(), Character::is_stealthy(), Character::mabuff_armor_bonus(), Character::mabuff_arpen_bonus(), Character::mabuff_attack_cost_mult(), Character::mabuff_attack_cost_penalty(), Character::mabuff_block_bonus(), Character::mabuff_block_effectiveness_bonus(), Character::mabuff_critical_hit_chance_bonus(), Character::mabuff_damage_bonus(), Character::mabuff_damage_mult(), Character::mabuff_dodge_bonus(), Character::mabuff_speed_bonus(), Character::mabuff_tohit_bonus(), npc::on_load(), process_effects(), Character::process_effects(), monster::process_effects(), monster::process_one_effect(), Character::recalc_speed_bonus(), remove_effect(), avatar::reset_stats(), Character::run_cost_effects(), and Character::vomit().
facing
FacingDirection Creature::facing = FacingDirection::RIGHT
return the direction the creature is facing, for sdl horizontal flip
Definition at line 303 of file creature.h.
Referenced by choose_direction(), choose_direction_rel_ms(), Character::mount_creature(), monster::move(), avatar_action::move(), npc::move_to(), target_ui::set_cursor_pos(), and npc::vehicle_danger().
fake
bool Creature::fake = false protected
Definition at line 1240 of file creature.h.
Referenced by Creature(), is_fake(), vehicle_prototype::save_vehicle_as_prototype(), and set_fake().
hit_bonus
float Creature::hit_bonus = 0.0f protected
Definition at line 1227 of file creature.h.
Referenced by get_hit_bonus(), mod_hit_bonus(), reset_bonuses(), and set_hit_bonus().
killer
Creature* Creature::killer protected
Definition at line 1194 of file creature.h.
Referenced by check_dead_state(), clear_killer(), Creature(), monster::die(), npc::die(), get_killer(), and set_killer().
last_updated
time_point Creature::last_updated protected
Definition at line 1238 of file creature.h.
Referenced by npc::import_and_clean(), monster::monster(), npc::npc(), npc::npc_update_body(), monster::on_load(), npc::on_load(), monster::on_unload(), and Character::update_body().
lifespan_end
std::optional<time_point> Creature::lifespan_end = std::nullopt protected
Definition at line 1196 of file creature.h.
Referenced by decrement_summon_timer(), npc::die(), monster::extended_description(), npc::import_and_clean(), and set_summon_time().
location
tripoint_abs_ms Creature::location private
The creature's position in absolute coordinates.
Definition at line 776 of file creature.h.
Referenced by Creature(), npc::find_corpse_to_pulp(), get_location(), global_omt_location(), global_sm_location(), pos_bub(), set_location(), and set_pos_only().
melee_quiet
bool Creature::melee_quiet = false protected
Definition at line 1234 of file creature.h.
Referenced by get_melee_quiet(), reset_bonuses(), and set_melee_quiet().
moves
int Creature::moves protected
Definition at line 1193 of file creature.h.
Referenced by npc::activate_item(), npc::aim(), Character::assign_activity(), Character::burn_move_stamina(), monster::can_act(), Character::Character(), Character::complete_disassemble(), Character::crafting_inventory(), Creature(), npc::do_player_activity(), npc::execute_action(), get_moves(), Character::gunmod_add(), Character::gunmod_remove(), mod_moves(), monster::monster(), monster::move(), npc::move_pause(), npc::npc(), Character::perform_technique(), monster::poly(), avatar::power_bionics(), process_turn(), Character::process_turn(), npc::randomize(), set_moves(), stumble_invis(), and Character::unload().
num_blocks
int Creature::num_blocks = 0 protected
Definition at line 1216 of file creature.h.
Referenced by get_num_blocks(), get_num_blocks_base(), and reset_bonuses().
num_blocks_bonus
int Creature::num_blocks_bonus = 0 protected
Definition at line 1218 of file creature.h.
Referenced by get_num_blocks(), get_num_blocks_bonus(), mod_num_blocks_bonus(), reset_bonuses(), and set_num_blocks_bonus().
num_dodges
int Creature::num_dodges = 0 protected
Definition at line 1217 of file creature.h.
Referenced by get_num_dodges(), get_num_dodges_base(), and reset_bonuses().
num_dodges_bonus
int Creature::num_dodges_bonus = 0 protected
Definition at line 1219 of file creature.h.
Referenced by get_num_dodges(), get_num_dodges_bonus(), mod_num_dodges_bonus(), and reset_bonuses().
pain
int Creature::pain private
Definition at line 1324 of file creature.h.
Referenced by Creature(), deal_damage_handle_type(), monster::deal_damage_handle_type(), get_pain(), Character::get_pain_penalty(), mod_pain_noresist(), Character::process_bionic(), and set_pain().
reachable_zone
int Creature::reachable_zone = 0 private
This number establishes a partition of zones on the map that have shared reachability/visibility.
In short, if you aren't in the same zone as some other monster, you can ignore them since you won't be able to reach them by any combination of regular movement and vision.
Definition at line 773 of file creature.h.
Referenced by npc::add_msg_player_or_say(), and get_reachable_zone().
scheduled_effects
std::queue<scheduled_effect, std::list<scheduled_effect> > Creature::scheduled_effects protected
Definition at line 1205 of file creature.h.
Referenced by Character::process_effects(), and schedule_effect().
size_bonus
int Creature::size_bonus = 0 protected
Definition at line 1230 of file creature.h.
Referenced by monster::get_size(), mod_size_bonus(), monster::print_info(), reset_bonuses(), and monster::stability_roll().
size_map
const std::map< std::string, creature_size > Creature::size_map static
Initial value:
= {
    {"TINY",   creature_size::tiny},
    {"SMALL",  creature_size::small},
    {"MEDIUM", creature_size::medium},
    {"LARGE",  creature_size::large},
    {"HUGE",   creature_size::huge}
}
Definition at line 255 of file creature.h.
Referenced by iuse::capture_monster_act().
speed_base
int Creature::speed_base = 0 protected
Definition at line 1222 of file creature.h.
Referenced by Creature(), get_speed_base(), monster::init_from_item(), and set_speed_base().
speed_bonus
int Creature::speed_bonus = 0 protected
Definition at line 1224 of file creature.h.
Referenced by get_speed_bonus(), mod_speed_bonus(), Character::mod_speed_bonus(), reset_bonuses(), and set_speed_bonus().
summoner
std::optional<character_id> Creature::summoner = std::nullopt protected
Definition at line 1197 of file creature.h.
Referenced by get_summoner(), and set_summoner().
terminating_effects
std::queue<terminating_effect, std::list<terminating_effect> > Creature::terminating_effects protected
Definition at line 1206 of file creature.h.
Referenced by Character::process_effects(), and schedule_effect_removal().
throw_resist
int Creature::throw_resist = 0 protected
Definition at line 1236 of file creature.h.
Referenced by get_throw_resist(), reset_bonuses(), and set_throw_resist().
underwater
bool Creature::underwater
Definition at line 941 of file creature.h.
Referenced by avatar::basic_symbol_color(), Creature(), monster::digging(), suffer::from_asthma(), Character::get_shout_volume(), is_adjacent(), is_underwater(), monster::is_underwater(), monster::move_to(), Character::pause(), Character::recalc_sight_limits(), Character::set_underwater(), Character::shout(), Character::sight_impaired(), monster::sight_range(), Character::suffer(), Character::swim_speed(), and avatar::try_to_sleep().
values
std::unordered_map<std::string, std::string> Creature::values protected
Definition at line 1211 of file creature.h.
Referenced by clear_values(), get_values(), maybe_get_value(), remove_value(), and set_value().
The documentation for this class was generated from the following files:
src/creature.h
src/creature.cpp
src/melee.cpp
src/ranged.cpp
src/savegame_json.cpp