Cataclysm DDA: basecamp_action_components Class Reference
basecamp_action_components Class Reference
#include <basecamp.h>
Public Member Functions
basecamp_action_components (const recipe &making, const mapgen_arguments &, int batch_size, basecamp &)
bool choose_components ()
void consume_components ()
Private Attributes
const recipe & making_
const mapgen_arguments & args_
int batch_size_
basecamp & base_
std::vector< comp_selection< item_comp > > item_selections_
std::vector< comp_selection< tool_comp > > tool_selections_
Detailed Description
Definition at line 509 of file basecamp.h.
Constructor & Destructor Documentation
basecamp_action_components()
basecamp_action_components::basecamp_action_components (const recipe & making, const mapgen_arguments & args, int batch_size, basecamp & base)
Definition at line 868 of file basecamp.cpp.
                                                                                          :
     making_( making ),
     args_( args ),
     batch_size_( batch_size ),
     base_( base )
 {
 }
Member Function Documentation
choose_components()
bool basecamp_action_components::choose_components ()
Definition at line 877 of file basecamp.cpp.
 {
     const auto filter = is_crafting_component;
     avatar &player_character = get_avatar();
     const requirement_data *req;
     if( making_.is_blueprint() ) {
         const std::unordered_map<mapgen_arguments, build_reqs> &reqs_map =
             making_.blueprint_build_reqs().reqs_by_parameters;
         auto req_it = reqs_map.find( args_ );
         if( req_it == reqs_map.end() ) {
             debugmsg( "invalid argument selection for recipe" );
             return false;
         }
         req = &req_it->second.consolidated_reqs;
     } else {
         req = making_.deduped_requirements().select_alternative(
                   player_character, base_._inv, filter, batch_size_ );
     }
     if( !req ) {
         return false;
     }
     if( !item_selections_.empty() || !tool_selections_.empty() ) {
         debugmsg( "Reused basecamp_action_components" );
         return false;
     }
     for( const auto &it : req->get_components() ) {
         comp_selection<item_comp> is =
             player_character.select_item_component( it, batch_size_, base_._inv, true, filter,
                     !base_.by_radio );
         if( is.use_from == usage_from::cancel ) {
             return false;
         }
         item_selections_.push_back( is );
     }
     // this may consume pseudo-resources from fake items
     for( const auto &it : req->get_tools() ) {
         comp_selection<tool_comp> ts =
             player_character.select_tool_component( it, batch_size_, base_._inv, true,
                     !base_.by_radio );
         if( ts.use_from == usage_from::cancel ) {
             return false;
         }
         tool_selections_.push_back( ts );
     }
     return true;
 }
References basecamp::_inv, args_, base_, batch_size_, recipe::blueprint_build_reqs(), basecamp::by_radio, cancel, debugmsg, recipe::deduped_requirements(), filter, get_avatar(), requirement_data::get_components(), requirement_data::get_tools(), recipe::is_blueprint(), is_crafting_component(), item_selections_, making_, parameterized_build_reqs::reqs_by_parameters, deduped_requirement_data::select_alternative(), Character::select_item_component(), Character::select_tool_component(), tool_selections_, and comp_selection< CompType >::use_from.
Referenced by basecamp::common_salt_water_pipe_construction(), basecamp::start_crafting(), basecamp::start_fortifications(), and basecamp::start_upgrade().
consume_components()
void basecamp_action_components::consume_components ()
Definition at line 924 of file basecamp.cpp.
 {
     map &target_map = base_.get_camp_map();
     avatar &player_character = get_avatar();
     std::vector<tripoint> src;
     src.resize( base_.src_set.size() );
     for( const tripoint_abs_ms &p : base_.src_set ) {
         src.emplace_back( target_map.getlocal( p ) );
     }
     for( const comp_selection<item_comp> &sel : item_selections_ ) {
         std::list<item> empty_consumed = player_character.consume_items( target_map, sel, batch_size_,
                                          is_crafting_component, src );
     }
     // this may consume pseudo-resources from fake items
     for( const comp_selection<tool_comp> &sel : tool_selections_ ) {
         player_character.consume_tools( target_map, sel, batch_size_, src, &base_ );
     }
     // go back and consume the actual resources
     for( basecamp_resource &bcp_r : base_.resources ) {
         if( bcp_r.consumed > 0 ) {
             target_map.use_charges( src, bcp_r.ammo_id, bcp_r.consumed );
         }
     }
     target_map.save();
 }
References basecamp_resource::ammo_id, base_, batch_size_, Character::consume_items(), Character::consume_tools(), basecamp_resource::consumed, get_avatar(), basecamp::get_camp_map(), map::getlocal(), is_crafting_component(), item_selections_, basecamp::resources, map::save(), basecamp::src_set, tool_selections_, and map::use_charges().
Referenced by basecamp::common_salt_water_pipe_construction(), basecamp::start_crafting(), basecamp::start_fortifications(), and basecamp::start_upgrade().
Member Data Documentation
args_
const mapgen_arguments& basecamp_action_components::args_ private
Definition at line 520 of file basecamp.h.
Referenced by choose_components().
base_
basecamp& basecamp_action_components::base_ private
Definition at line 522 of file basecamp.h.
Referenced by choose_components(), and consume_components().
batch_size_
int basecamp_action_components::batch_size_ private
Definition at line 521 of file basecamp.h.
Referenced by choose_components(), and consume_components().
item_selections_
std::vector<comp_selection<item_comp> > basecamp_action_components::item_selections_ private
Definition at line 523 of file basecamp.h.
Referenced by choose_components(), and consume_components().
making_
const recipe& basecamp_action_components::making_ private
Definition at line 519 of file basecamp.h.
Referenced by choose_components().
tool_selections_
std::vector<comp_selection<tool_comp> > basecamp_action_components::tool_selections_ private
Definition at line 524 of file basecamp.h.
Referenced by choose_components(), and consume_components().
The documentation for this class was generated from the following files:
src/basecamp.h
src/basecamp.cpp