Cataclysm DDA: ereader_inventory_preset Class Reference
ereader_inventory_preset Class Reference
Public Member Functions
ereader_inventory_preset (const Character &you)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from pickup_inventory_preset
pickup_inventory_preset (const Character &you, bool skip_wield_check=false, bool ignore_liquidcont=false)
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Protected Member Functions
std::string get_action_name (const item &it) const
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Private Attributes
const Character & you
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 1331 of file game_inventory.cpp.
Constructor & Destructor Documentation
ereader_inventory_preset()
ereader_inventory_preset::ereader_inventory_preset (const Character & you) inline explicit
Definition at line 1334 of file game_inventory.cpp.
                                                                   : pickup_inventory_preset( you ),
             you( you ) {
             _collate_entries = true;
             if( get_option<bool>( "INV_USE_ACTION_NAMES" ) ) {
                 append_cell( [ this ]( const item_location & loc ) {
                     return string_format( "<color_light_green>%s</color>", get_action_name( *loc ) );
                 }, _( "ACTION" ) );
             }
         }
References _, inventory_selector_preset::_collate_entries, inventory_selector_preset::append_cell(), get_action_name(), and string_format().
Member Function Documentation
get_action_name()
std::string ereader_inventory_preset::get_action_name (const item & it) const inline protected
Definition at line 1370 of file game_inventory.cpp.
{
             return string_format( "Read on %s.", it.tname() );
         }
References string_format(), and item::tname().
Referenced by ereader_inventory_preset().
get_denial()
std::string ereader_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from pickup_inventory_preset.
Definition at line 1348 of file game_inventory.cpp.
{
             const item &it = *loc;
             if( it.is_broken() ) {
                 return _( "E-reader is broken and won't turn on." );
             }
             if( !it.ammo_sufficient( &you, "EBOOKREAD" ) ) {
                 return string_format(
                            n_gettext( "Needs at least %d charge.",
                                       "Needs at least %d charges.", loc->ammo_required() ),
                            loc->ammo_required() );
             }
             if( !it.has_flag( flag_ALLOWS_REMOTE_USE ) ) {
                 return pickup_inventory_preset::get_denial( loc );
             }
             return std::string();
         }
References _, item::ammo_required(), item::ammo_sufficient(), flag_ALLOWS_REMOTE_USE, pickup_inventory_preset::get_denial(), item::has_flag(), item::is_broken(), n_gettext, string_format(), and you.
is_shown()
bool ereader_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from pickup_inventory_preset.
Definition at line 1344 of file game_inventory.cpp.
{
             return loc->is_ebook_storage();
         }
References item::is_ebook_storage().
Member Data Documentation
you
const Character& ereader_inventory_preset::you private
Definition at line 1374 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp