Cataclysm DDA: consume_drug_iuse Class Reference
consume_drug_iuse Class Reference
This iuse encapsulates the effects of taking a drug.
#include <iuse_actor.h>
Public Member Functions
consume_drug_iuse (const std::string &type="consume_drug")
~consume_drug_iuse () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
translation activation_message
Message to display when drug is consumed.
std::map< std::string, int > fields_produced
Fields to produce when you take the drug, mostly intended for various kinds of smoke.
std::map< itype_id, int > charges_needed
Tool charges needed to take the drug, e.g.
std::map< itype_id, int > tools_needed
Tools needed, but not consumed, e.g.
std::vector< effect_data > effects
An effect or effects (conditions) to give the player for the stated duration.
std::map< std::string, int > stat_adjustments
A list of stats and adjustments to them.
std::map< vitamin_id, std::pair< int, int > > vitamins
Modify player vitamin_levels by random amount between min (first) and max (second)
std::vector< damage_over_time_data > damage_over_time
List of damage over time applied by this drug, negative damage heals.
int moves = 100
How many move points this action takes.
std::string used_up_item
Item produced after using drugs.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
This iuse encapsulates the effects of taking a drug.
Definition at line 239 of file iuse_actor.h.
Constructor & Destructor Documentation
consume_drug_iuse()
consume_drug_iuse::consume_drug_iuse (const std::string & type = "consume_drug") inline explicit
Definition at line 264 of file iuse_actor.h.
 : iuse_actor( type ) {}
~consume_drug_iuse()
consume_drug_iuse::~consume_drug_iuse () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > consume_drug_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 699 of file iuse_actor.cpp.
 {
     return std::make_unique<consume_drug_iuse>( *this );
 }
info()
void consume_drug_iuse::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 742 of file iuse_actor.cpp.
 {
     const std::string vits = enumerate_as_string( vitamins.begin(), vitamins.end(),
     []( const decltype( vitamins )::value_type & v ) {
         const time_duration rate = get_player_character().vitamin_rate( v.first );
         if( rate <= 0_turns ) {
             return std::string();
         }
         const int lo = v.second.first;
         const int hi = v.second.second;
         if( v.first->type() == vitamin_type::VITAMIN ) {
             return string_format( lo == hi ? "%s (%i%%)" : "%s (%i-%i%%)", v.first.obj().name(), lo, hi );
         }
         return string_format( lo == hi ? "%s (%i U)" : "%s (%i-%i U)", v.first.obj().name(), lo, hi );
     } );
     if( !vits.empty() ) {
         dump.emplace_back( "TOOL", _( "Vitamins (RDA) and Compounds (U): " ), vits );
     }
     if( tools_needed.count( itype_syringe ) ) {
         dump.emplace_back( "TOOL", _( "You need a <info>syringe</info> to inject this drug." ) );
     }
 }
References _, enumerate_as_string(), get_player_character(), itype_syringe, cata::hash64_detail::lo, string_format(), tools_needed, VITAMIN, Character::vitamin_rate(), and vitamins.
load()
void consume_drug_iuse::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 716 of file iuse_actor.cpp.
 {
     obj.read( "activation_message", activation_message );
     obj.read( "charges_needed", charges_needed );
     obj.read( "tools_needed", tools_needed );
     if( obj.has_array( "effects" ) ) {
         for( const JsonObject e : obj.get_array( "effects" ) ) {
             effects.push_back( load_effect_data( e ) );
         }
     }
     optional( obj, false, "damage_over_time", damage_over_time );
     obj.read( "stat_adjustments", stat_adjustments );
     obj.read( "fields_produced", fields_produced );
     obj.read( "moves", moves );
     for( JsonArray vit : obj.get_array( "vitamins" ) ) {
         int lo = vit.get_int( 1 );
         int hi = vit.size() >= 3 ? vit.get_int( 2 ) : lo;
         vitamins.emplace( vitamin_id( vit.get_string( 0 ) ), std::make_pair( lo, hi ) );
     }
     used_up_item = obj.get_string( "used_up_item", used_up_item );
 }
References activation_message, charges_needed, damage_over_time, effects, fields_produced, JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), cata::hash64_detail::lo, load_effect_data(), moves, optional(), JsonObject::read(), stat_adjustments, tools_needed, used_up_item, and vitamins.
use()
std::optional< int > consume_drug_iuse::use (Character * p, item & it, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 769 of file iuse_actor.cpp.
 {
     auto need_these = tools_needed;
     // Check prerequisites first.
     for( const auto &tool : need_these ) {
         if( !p->has_amount( tool.first, 1 ) ) {
             p->add_msg_player_or_say( _( "You need %1$s to consume %2$s!" ),
                                       _( "I need a %1$s to consume %2$s!" ),
                                       item::nname( tool.first ),
                                       it.type_name( 1 ) );
             return std::nullopt;
         }
     }
     for( const auto &consumable : charges_needed ) {
         // Amount == -1 means need one, but don't consume it.
         if( !p->has_charges( consumable.first, ( consumable.second == -1 ) ?
                              1 : consumable.second ) ) {
             p->add_msg_player_or_say( _( "You need %1$s to consume %2$s!" ),
                                       _( "I need a %1$s to consume %2$s!" ),
                                       item::nname( consumable.first ),
                                       it.type_name( 1 ) );
             return std::nullopt;
         }
     }
     // Apply the various effects.
     for( const effect_data &eff : effects ) {
         time_duration dur = eff.duration;
         if( p->has_trait( trait_TOLERANCE ) ) {
             dur *= .8;
         } else if( p->has_trait( trait_LIGHTWEIGHT ) ) {
             dur *= 1.2;
         }
         p->add_effect( eff.id, dur, eff.bp, eff.permanent );
     }
     //Apply the various damage_over_time
     for( const damage_over_time_data &Dot : damage_over_time ) {
         p->add_damage_over_time( Dot );
     }
     for( const auto &stat_adjustment : stat_adjustments ) {
         p->mod_stat( stat_adjustment.first, stat_adjustment.second );
     }
     map &here = get_map();
     for( const auto &field : fields_produced ) {
         const field_type_id fid = field_type_id( field.first );
         for( int i = 0; i < 3; i++ ) {
             point offset( rng( -2, 2 ), rng( -2, 2 ) );
             here.add_field( p->pos_bub() + offset, fid, field.second );
         }
     }
     for( const auto &v : vitamins ) {
         const int lo = v.first->RDA_to_default( v.second.first );
         const int high = v.first->RDA_to_default( v.second.second );
         // have to update the daily estimate with the vitamins from the drug as well
         p->daily_vitamins[v.first].first += lo;
         p->vitamin_mod( v.first, rng( lo, high ) );
     }
     // Output message.
     p->add_msg_if_player( activation_message.translated(), it.type_name( 1 ) );
     // Consume charges.
     for( const auto &consumable : charges_needed ) {
         if( consumable.second != -1 ) {
             p->use_charges( consumable.first, consumable.second );
         }
     }
     if( !used_up_item.empty() ) {
         item used_up( used_up_item, it.birthday() );
         p->i_add_or_drop( used_up );
     }
     // Uses the moves specified by iuse_actor's definition
     p->mod_moves( -moves );
     return 1;
 }
References _, activation_message, Creature::add_damage_over_time(), Creature::add_effect(), map::add_field(), Character::add_msg_if_player(), Character::add_msg_player_or_say(), item::birthday(), charges_needed, Character::daily_vitamins, damage_over_time, dur, effects, field_type_id, fields_produced, get_map(), visitable::has_amount(), Character::has_charges(), Character::has_trait(), irradiance::high, Character::i_add_or_drop(), cata::hash64_detail::lo, Creature::mod_moves(), Character::mod_stat(), moves, item::nname(), Creature::pos_bub(), rng(), stat_adjustments, tools_needed, trait_LIGHTWEIGHT, trait_TOLERANCE, translation::translated(), item::type_name(), Character::use_charges(), used_up_item, Character::vitamin_mod(), and vitamins.
Member Data Documentation
activation_message
translation consume_drug_iuse::activation_message
Message to display when drug is consumed.
Definition at line 243 of file iuse_actor.h.
Referenced by load(), and use().
charges_needed
std::map<itype_id, int> consume_drug_iuse::charges_needed
Tool charges needed to take the drug, e.g.
fire.
Definition at line 247 of file iuse_actor.h.
Referenced by load(), and use().
damage_over_time
std::vector<damage_over_time_data> consume_drug_iuse::damage_over_time
List of damage over time applied by this drug, negative damage heals.
Definition at line 259 of file iuse_actor.h.
Referenced by load(), and use().
effects
std::vector<effect_data> consume_drug_iuse::effects
An effect or effects (conditions) to give the player for the stated duration.
Definition at line 251 of file iuse_actor.h.
Referenced by load(), and use().
fields_produced
std::map<std::string, int> consume_drug_iuse::fields_produced
Fields to produce when you take the drug, mostly intended for various kinds of smoke.
Definition at line 245 of file iuse_actor.h.
Referenced by load(), and use().
moves
int consume_drug_iuse::moves = 100
How many move points this action takes.
Definition at line 262 of file iuse_actor.h.
Referenced by load(), and use().
stat_adjustments
std::map<std::string, int> consume_drug_iuse::stat_adjustments
A list of stats and adjustments to them.
Definition at line 253 of file iuse_actor.h.
Referenced by load(), and use().
tools_needed
std::map<itype_id, int> consume_drug_iuse::tools_needed
Tools needed, but not consumed, e.g.
"smoking apparatus".
Definition at line 249 of file iuse_actor.h.
Referenced by Character::can_eat(), Character::get_consume_time(), activatable_inventory_preset::get_denial(), info(), load(), and use().
used_up_item
std::string consume_drug_iuse::used_up_item
Item produced after using drugs.
Definition at line 273 of file iuse_actor.h.
Referenced by load(), and use().
vitamins
std::map<vitamin_id, std::pair<int, int> > consume_drug_iuse::vitamins
Modify player vitamin_levels by random amount between min (first) and max (second)
Definition at line 256 of file iuse_actor.h.
Referenced by info(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp