Cataclysm DDA: past_achievements_info Class Reference
past_achievements_info Class Reference
#include <past_achievements_info.h>
Public Member Functions
past_achievements_info ()
void load ()
void clear ()
bool is_completed (const achievement_id &) const
std::vector< std::string > avatars_completed (const achievement_id &) const
Private Attributes
bool loaded_ = false
std::map< achievement_id, std::vector< std::string > > completed_achievements_
Detailed Description
Definition at line 9 of file past_achievements_info.h.
Constructor & Destructor Documentation
past_achievements_info()
past_achievements_info::past_achievements_info () default
Referenced by clear().
Member Function Documentation
avatars_completed()
std::vector< std::string > past_achievements_info::avatars_completed (const achievement_id & ach) const
Definition at line 19 of file past_achievements_info.cpp.
 {
     std::vector<std::string> completed;
     const auto it = completed_achievements_.find( ach );
     if( it != completed_achievements_.end() ) {
         completed = it->second;
     }
     // Legacy data from memorials
     const achievement_completion_info *legacy = get_past_games().legacy_achievement( ach );
     if( legacy ) {
         for( const past_game_info *const info : legacy->games_completed ) {
             if( info ) {
                 completed.emplace_back( info->avatar_name() );
             }
         }
     }
     return completed;
 }
References past_game_info::avatar_name(), completed, completed_achievements_, achievement_completion_info::games_completed, get_past_games(), and past_games_info::legacy_achievement().
Referenced by is_completed(), and achievement_tracker::ui_text().
clear()
void past_achievements_info::clear ()
Definition at line 9 of file past_achievements_info.cpp.
 {
     *this = past_achievements_info();
 }
References past_achievements_info().
Referenced by clear_past_achievements().
is_completed()
bool past_achievements_info::is_completed (const achievement_id & ach) const
Definition at line 14 of file past_achievements_info.cpp.
 {
     return !avatars_completed( ach ).empty();
 }
References avatars_completed().
Referenced by achievement_attained(), profession::can_pick(), and scenario::can_pick().
load()
void past_achievements_info::load ()
Definition at line 39 of file past_achievements_info.cpp.
 {
     if( loaded_ ) {
         return;
     }
     loaded_ = true;
     const cata_path &achievement_dir = PATH_INFO::achievementdir_path();
     assure_dir_exist( achievement_dir );
     std::vector<cata_path> filenames = get_files_from_path( ".json", achievement_dir, true, true );
     for( const cata_path &filename : filenames ) {
         int version;
         std::vector<achievement_id> achievements;
         std::string avatar_name;
         JsonValue jsin = json_loader::from_path( filename );
         JsonObject jo = jsin.get_object();
         jo.read( "achievement_version", version );
         if( version == 0 ) {
             // version 0 has no `avatar_name` member, skip them
             continue;
         } else if( version != 1 ) {
             throw JsonError( string_format( "unexpected past achievements version %d", version ) );
         }
         jo.read( "achievements", achievements );
         jo.read( "avatar_name", avatar_name );
         for( const achievement_id &id : achievements ) {
             completed_achievements_[id].emplace_back( avatar_name );
         }
     }
     // Ensure memorial data are also loaded for legacy dead character achievements
     get_past_games();
 }
References PATH_INFO::achievementdir_path(), assure_dir_exist(), completed_achievements_, json_loader::from_path(), get_files_from_path(), JsonValue::get_object(), get_past_games(), base_camps::id, loaded_, JsonObject::read(), and string_format().
Referenced by get_past_achievements().
Member Data Documentation
completed_achievements_
std::map<achievement_id, std::vector<std::string> > past_achievements_info::completed_achievements_ private
Definition at line 21 of file past_achievements_info.h.
Referenced by avatars_completed(), and load().
loaded_
bool past_achievements_info::loaded_ = false private
Definition at line 20 of file past_achievements_info.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/past_achievements_info.h
src/past_achievements_info.cpp