Cataclysm DDA: mattack_actor Class Reference
mattack_actor Class Reference abstract
#include <mattack_common.h>
Public Member Functions
mattack_actor (const mattack_id &new_id)
void load (const JsonObject &jo, const std::string &src)
virtual ~mattack_actor ()=default
virtual bool call (monster &) const =0
virtual std::unique_ptr< mattack_actor > clone () const =0
virtual void load_internal (const JsonObject &jo, const std::string &src)=0
Public Attributes
mattack_id id
bool was_loaded = false
int cooldown = 0
int attack_chance = 100
std::function< bool(dialogue &)> condition
bool has_condition = false
Protected Member Functions
mattack_actor ()=default
Detailed Description
Definition at line 21 of file mattack_common.h.
Constructor & Destructor Documentation
mattack_actor() [1/2]
mattack_actor::mattack_actor () protected default
mattack_actor() [2/2]
mattack_actor::mattack_actor (const mattack_id & new_id) inline explicit
Definition at line 26 of file mattack_common.h.
 : id( new_id ) { }
~mattack_actor()
virtual mattack_actor::~mattack_actor () virtual default
Member Function Documentation
call()
virtual bool mattack_actor::call (monster &) const pure virtual
Implemented in mattack_hardcoded_wrapper, gun_actor, melee_actor, mon_spellcasting_actor, and leap_actor.
clone()
virtual std::unique_ptr<mattack_actor> mattack_actor::clone () const pure virtual
Implemented in mattack_hardcoded_wrapper, gun_actor, bite_actor, melee_actor, mon_spellcasting_actor, and leap_actor.
load()
void mattack_actor::load (const JsonObject & jo, const std::string & src)
Definition at line 1464 of file monstergenerator.cpp.
 {
     bool strict = src == "dda";
     // Legacy support
     if( !jo.has_string( "id" ) ) {
         id = jo.get_string( "type" );
     } else {
         // Loading ids can't be strict at the moment, since it has to match the stored version
         assign( jo, "id", id, false );
     }
     assign( jo, "cooldown", cooldown, strict );
     load_internal( jo, src );
     // Set was_loaded manually because we don't have generic_factory to do it for us
     was_loaded = true;
 }
References assign(), cooldown, JsonObject::get_string(), JsonObject::has_string(), load_internal(), strict, and was_loaded.
load_internal()
virtual void mattack_actor::load_internal (const JsonObject & jo, const std::string & src) pure virtual
Implemented in gun_actor, bite_actor, melee_actor, mon_spellcasting_actor, leap_actor, and mattack_hardcoded_wrapper.
Referenced by load().
Member Data Documentation
attack_chance
int mattack_actor::attack_chance = 100
Definition at line 33 of file mattack_common.h.
Referenced by leap_actor::load_internal(), mon_spellcasting_actor::load_internal(), and melee_actor::load_internal().
condition
std::function<bool(dialogue &)> mattack_actor::condition
Definition at line 36 of file mattack_common.h.
Referenced by leap_actor::call(), mon_spellcasting_actor::call(), melee_actor::call(), gun_actor::call(), leap_actor::load_internal(), mon_spellcasting_actor::load_internal(), melee_actor::load_internal(), and gun_actor::load_internal().
cooldown
int mattack_actor::cooldown = 0
Definition at line 31 of file mattack_common.h.
Referenced by mtype::add_special_attack(), and load().
has_condition
bool mattack_actor::has_condition = false
Definition at line 37 of file mattack_common.h.
Referenced by leap_actor::call(), mon_spellcasting_actor::call(), melee_actor::call(), gun_actor::call(), leap_actor::load_internal(), mon_spellcasting_actor::load_internal(), melee_actor::load_internal(), and gun_actor::load_internal().
id
mattack_id mattack_actor::id
Definition at line 28 of file mattack_common.h.
Referenced by MonsterGenerator::add_attack(), and mtype::add_special_attack().
was_loaded
bool mattack_actor::was_loaded = false
Definition at line 29 of file mattack_common.h.
Referenced by load(), leap_actor::load_internal(), mon_spellcasting_actor::load_internal(), melee_actor::load_internal(), bite_actor::load_internal(), and gun_actor::load_internal().
The documentation for this class was generated from the following files:
src/mattack_common.h
src/monstergenerator.cpp