Cataclysm DDA: behavior::monster_oracle_t Class Reference
behavior::monster_oracle_t Class Reference
#include <monster_oracle.h>
Public Member Functions
monster_oracle_t (const monster *subject)
status_t not_hallucination (std::string_view) const
Predicates used by AI to determine goals.
status_t items_available (std::string_view) const
status_t adjacent_plants (std::string_view) const
status_t special_available (std::string_view special_name) const
status_t split_possible (std::string_view) const
Private Attributes
const monster * subject
Detailed Description
Definition at line 15 of file monster_oracle.h.
Constructor & Destructor Documentation
monster_oracle_t()
behavior::monster_oracle_t::monster_oracle_t (const monster * subject) inline explicit
Definition at line 18 of file monster_oracle.h.
{
             this->subject = subject;
         }
Member Function Documentation
adjacent_plants()
status_t behavior::monster_oracle_t::adjacent_plants (std::string_view) const
Definition at line 87 of file monster_oracle.cpp.
 {
     for( const tripoint &p : get_map().points_in_radius( subject->pos(), 1 ) ) {
         if( get_map().has_flag( ter_furn_flag::TFLAG_PLANT, p ) ) {
             return status_t::running;
         }
     }
     return status_t::failure;
 }
References behavior::failure, get_map(), points_in_radius(), Creature::pos(), behavior::running, subject, and TFLAG_PLANT.
items_available()
status_t behavior::monster_oracle_t::items_available (std::string_view) const
Definition at line 27 of file monster_oracle.cpp.
 {
     if( !get_map().has_flag( ter_furn_flag::TFLAG_SEALED, subject->pos() ) &&
         get_map().has_items( subject->pos() ) ) {
         std::vector<material_id> absorb_material = subject->get_absorb_material();
         std::vector<material_id> no_absorb_material = subject->get_no_absorb_material();
         // base case: there are no specified conditions for what it can eat
         if( absorb_material.empty() && no_absorb_material.empty() ) {
             return status_t::running;
         }
         // case 2: no whitelist specified (it is approved for everything) but a blacklist specified
         if( absorb_material.empty() && !no_absorb_material.empty() ) {
             bool found = false;
             for( item &it : get_map().i_at( subject->pos() ) ) {
                 for( const material_type *mat_type : it.made_of_types() ) {
                     if( !( std::find( no_absorb_material.begin(), no_absorb_material.end(),
                                       mat_type->id ) != no_absorb_material.end() ) ) {
                         //we found something that wasn't on the blacklist
                         found = true;
                     }
                 }
             }
             if( found ) {
                 return status_t::running;
             } else {
                 return status_t::failure;
             }
         }
         // Case 3: there is a whitelist but no blacklist, so only allow the whitelisted ones
         if( !absorb_material.empty() && no_absorb_material.empty() ) {
             for( item &it : get_map().i_at( subject->pos() ) ) {
                 for( const material_type *mat_type : it.made_of_types() ) {
                     if( std::find( absorb_material.begin(), absorb_material.end(),
                                    mat_type->id ) != absorb_material.end() ) {
                         return status_t::running;
                     }
                 }
             }
         }
         // case 4: no whitelist specified (it is approved for everything) but a blacklist specified
         if( !absorb_material.empty() && !no_absorb_material.empty() ) {
             for( item &it : get_map().i_at( subject->pos() ) ) {
                 for( const material_type *mat_type : it.made_of_types() ) {
                     if( !( std::find( no_absorb_material.begin(), no_absorb_material.end(),
                                       mat_type->id ) != no_absorb_material.end() ) ) {
                         //we found something that wasn't on the blacklist, so now check the whitelist
                         if( std::find( absorb_material.begin(), absorb_material.end(),
                                        mat_type->id ) != absorb_material.end() ) {
                             return status_t::running;
                         }
                     }
                 }
             }
         }
     }
     return status_t::failure;
 }
References behavior::failure, monster::get_absorb_material(), get_map(), monster::get_no_absorb_material(), Creature::pos(), behavior::running, subject, and TFLAG_SEALED.
not_hallucination()
status_t behavior::monster_oracle_t::not_hallucination (std::string_view) const
Predicates used by AI to determine goals.
Definition at line 13 of file monster_oracle.cpp.
 {
     return subject->is_hallucination() ? status_t::failure : status_t::running;
 }
References behavior::failure, monster::is_hallucination(), behavior::running, and subject.
special_available()
status_t behavior::monster_oracle_t::special_available (std::string_view special_name) const
Definition at line 97 of file monster_oracle.cpp.
 {
     bool only_if_present = false;
     std::string mspecial_name;
     if( special_name.rfind( '!', 0 ) != std::string::npos ) {
         only_if_present = true;
         mspecial_name = special_name.substr( 1 );
     } else {
         mspecial_name = special_name;
     }
     bool has_special = only_if_present ? subject->has_special( mspecial_name ) : true;
     return ( !has_special && only_if_present ) || ( has_special &&
             subject->special_available( mspecial_name ) ) ? status_t::running : status_t::failure;
 }
References behavior::failure, monster::has_special(), behavior::running, monster::special_available(), and subject.
split_possible()
status_t behavior::monster_oracle_t::split_possible (std::string_view) const
Definition at line 18 of file monster_oracle.cpp.
 {
     // check if subject has split to support inverting this predicate for absorb monsters without split
     if( subject->has_special( "SPLIT" ) && ( subject->get_hp() / 2 ) > subject->get_hp_max() ) {
         return status_t::running;
     }
     return status_t::failure;
 }
References behavior::failure, monster::get_hp(), monster::get_hp_max(), monster::has_special(), behavior::running, and subject.
Member Data Documentation
subject
const monster* behavior::monster_oracle_t::subject private
Definition at line 30 of file monster_oracle.h.
Referenced by adjacent_plants(), items_available(), not_hallucination(), special_available(), and split_possible().
The documentation for this class was generated from the following files:
src/monster_oracle.h
src/monster_oracle.cpp