Cataclysm DDA: zone_manager Class Reference
zone_manager Class Reference
#include <clzones.h>
Public Types
using ref_zone_data = std::reference_wrapper< zone_data >
using ref_const_zone_data = std::reference_wrapper< const zone_data >
Public Member Functions
zone_manager ()
~zone_manager ()=default
zone_manager (zone_manager &&)=default
zone_manager (const zone_manager &)=default
zone_manager & operator= (zone_manager &&)=default
zone_manager & operator= (const zone_manager &)=default
void clear ()
void add (const std::string &name, const zone_type_id &type, const faction_id &faction, bool invert, bool enabled, const tripoint &start, const tripoint &end, const shared_ptr_fast< zone_options > &options=nullptr, bool personal=false, bool silent=false, map *pmap=nullptr)
const zone_data * get_zone_at (const tripoint_abs_ms &where, const zone_type_id &type, const faction_id &fac=your_fac) const
std::vector< zone_data const * > get_zones_at (const tripoint_abs_ms &where, const zone_type_id &type, const faction_id &fac=your_fac) const
void create_vehicle_loot_zone (class vehicle &vehicle, const point &mount_point, zone_data &new_zone, map *pmap=nullptr)
bool remove (zone_data &zone)
unsigned int size () const
const std::map< zone_type_id, zone_type > & get_types () const
std::string get_name_from_type (const zone_type_id &type) const
bool has_type (const zone_type_id &type) const
bool has_defined (const zone_type_id &type, const faction_id &fac=your_fac) const
void cache_data (bool update_avatar=true)
void reset_disabled ()
void cache_avatar_location ()
void cache_vzones (map *pmap=nullptr)
bool has (const zone_type_id &type, const tripoint_abs_ms &where, const faction_id &fac=your_fac) const
bool has_near (const zone_type_id &type, const tripoint_abs_ms &where, int range=MAX_DISTANCE, const faction_id &fac=your_fac) const
bool has_loot_dest_near (const tripoint_abs_ms &where) const
bool custom_loot_has (const tripoint_abs_ms &where, const item *it, const zone_type_id &ztype, const faction_id &fac=your_fac) const
std::vector< zone_data const * > get_near_zones (const zone_type_id &type, const tripoint_abs_ms &where, int range, const faction_id &fac=your_fac) const
std::unordered_set< tripoint_abs_ms > get_near (const zone_type_id &type, const tripoint_abs_ms &where, int range=MAX_DISTANCE, const item *it=nullptr, const faction_id &fac=your_fac) const
std::optional< tripoint_abs_ms > get_nearest (const zone_type_id &type, const tripoint_abs_ms &where, int range=MAX_DISTANCE, const faction_id &fac=your_fac) const
zone_type_id get_near_zone_type_for_item (const item &it, const tripoint_abs_ms &where, int range=MAX_DISTANCE, const faction_id &fac=your_fac) const
std::vector< zone_data > get_zones (const zone_type_id &type, const tripoint_abs_ms &where, const faction_id &fac=your_fac) const
const zone_data * get_zone_at (const tripoint_abs_ms &where, bool loot_only=false, const faction_id &fac=your_fac) const
const zone_data * get_bottom_zone (const tripoint_abs_ms &where, const faction_id &fac=your_fac) const
std::optional< std::string > query_name (const std::string &default_name="") const
std::optional< zone_type_id > query_type (bool personal=false) const
void swap (zone_data &a, zone_data &b)
void rotate_zones (map &target_map, int turns)
std::unordered_set< tripoint > get_point_set_loot (const tripoint_abs_ms &where, int radius, const faction_id &fac=your_fac) const
std::unordered_set< tripoint > get_point_set_loot (const tripoint_abs_ms &where, int radius, bool npc_search, const faction_id &fac=your_fac) const
std::vector< ref_zone_data > get_zones (const faction_id &fac=your_fac)
std::vector< ref_const_zone_data > get_zones (const faction_id &fac=your_fac) const
bool has_personal_zones () const
bool save_zones (std::string const &suffix={})
bool save_world_zones (std::string const &suffix={})
void load_zones (std::string const &suffix={})
void load_world_zones (std::string const &suffix={})
void zone_edited (zone_data &zone)
void revert_vzones ()
void serialize (JsonOut &json) const
void deserialize (const JsonValue &jv)
Static Public Member Functions
static zone_manager & get_manager ()
Private Member Functions
std::unordered_set< tripoint_abs_ms > get_point_set (const zone_type_id &type, const faction_id &fac=your_fac) const
std::unordered_set< tripoint_abs_ms > get_vzone_set (const zone_type_id &type, const faction_id &fac=your_fac) const
Private Attributes
std::vector< zone_data > zones
std::vector< zone_data * > added_vzones
std::vector< std::pair< zone_data, zone_data * > > changed_vzones
std::vector< zone_data > removed_vzones
std::map< zone_type_id, zone_type > types
int num_personal_zones = 0
std::unordered_map< std::string, std::unordered_set< tripoint_abs_ms > > area_cache
std::unordered_map< std::string, std::unordered_set< tripoint_abs_ms > > vzone_cache
Static Private Attributes
static const int MAX_DISTANCE = ACTIVITY_SEARCH_DISTANCE
Detailed Description
Definition at line 512 of file clzones.h.
Member Typedef Documentation
ref_const_zone_data
using zone_manager::ref_const_zone_data = std::reference_wrapper<const zone_data>
Definition at line 516 of file clzones.h.
ref_zone_data
using zone_manager::ref_zone_data = std::reference_wrapper<zone_data>
Definition at line 515 of file clzones.h.
Constructor & Destructor Documentation
zone_manager() [1/3]
zone_manager::zone_manager ()
Definition at line 96 of file clzones.cpp.
 {
     for( const zone_type &zone : zone_type::get_all() ) {
         types.emplace( zone.id, zone );
     }
 }
References zone_type::get_all(), and types.
~zone_manager()
zone_manager::~zone_manager () default
zone_manager() [2/3]
zone_manager::zone_manager (zone_manager &&) default
zone_manager() [3/3]
zone_manager::zone_manager (const zone_manager &) default
Member Function Documentation
add()
void zone_manager::add (const std::string & name, const zone_type_id & type, const faction_id & faction, bool invert, bool enabled, const tripoint & start, const tripoint & end, const shared_ptr_fast< zone_options > & options = nullptr, bool personal = false, bool silent = false, map * pmap = nullptr)
Definition at line 1385 of file clzones.cpp.
 {
     map &here = pmap == nullptr ? get_map() : *pmap;
     zone_data new_zone = zone_data( name, type, fac, invert, enabled, start, end, options, personal );
     // only non personal zones can be vehicle zones
     if( !personal ) {
         optional_vpart_position const vp = here.veh_at( here.getlocal( start ) );
         if( vp && vp->vehicle().get_owner() == fac && vp.cargo() ) {
             // TODO:Allow for loot zones on vehicles to be larger than 1x1
             if( start == end &&
                 ( silent || query_yn( _( "Bind this zone to the cargo part here?" ) ) ) ) {
                 // TODO: refactor zone options for proper validation code
                 if( !silent &&
                     ( type == zone_type_FARM_PLOT || type == zone_type_CONSTRUCTION_BLUEPRINT ) ) {
                     popup( _( "You cannot add that type of zone to a vehicle." ), PF_NONE );
                     return;
                 }
                 create_vehicle_loot_zone( vp->vehicle(), vp->mount(), new_zone, pmap );
                 return;
             }
         }
     }
     //Create a regular zone
     zones.push_back( new_zone );
     if( personal ) {
         num_personal_zones++;
     }
     cache_data();
 }
References _, cache_data(), optional_vpart_position::cargo(), create_vehicle_loot_zone(), enabled, keycode::end, get_map(), map::getlocal(), om_direction::name(), num_personal_zones, PATH_INFO::options(), PF_NONE, popup(), query_yn(), silent, type, map::veh_at(), zone_type_CONSTRUCTION_BLUEPRINT, zone_type_FARM_PLOT, and zones.
Referenced by add_fallback_zone(), mapgen_place_zone(), and game::zones_manager().
cache_avatar_location()
void zone_manager::cache_avatar_location ()
Definition at line 897 of file clzones.cpp.
 {
     avatar &player_character = get_avatar();
     tripoint_abs_ms cached_shift = player_character.get_location();
     for( zone_data &elem : zones ) {
         // update the current cached locations for each personal zone
         if( elem.get_is_personal() ) {
             elem.update_cached_shift( cached_shift );
         }
     }
 }
References get_avatar(), Creature::get_location(), and zones.
Referenced by game::zones_manager().
cache_data()
void zone_manager::cache_data (bool update_avatar = true)
Definition at line 854 of file clzones.cpp.
 {
     area_cache.clear();
     avatar &player_character = get_avatar();
     tripoint_abs_ms cached_shift = player_character.get_location();
     for( zone_data &elem : zones ) {
         if( !elem.get_enabled() ) {
             continue;
         }
         // update the current cached locations for each personal zone
         // if we are flagged to update the locations with this cache
         if( elem.get_is_personal() && update_avatar ) {
             elem.update_cached_shift( cached_shift );
         }
         const std::string &type_hash = elem.get_type_hash();
         auto &cache = area_cache[type_hash];
         // Draw marked area
         for( const tripoint_abs_ms &p : tripoint_range<tripoint_abs_ms>(
                  elem.get_start_point(), elem.get_end_point() ) ) {
             cache.insert( p );
         }
     }
 }
References area_cache, get_avatar(), Creature::get_location(), and zones.
Referenced by add(), load_zones(), loot(), vehicle::refresh_zones(), reset_disabled(), zone_data::set_position(), and zone_data::set_type().
cache_vzones()
void zone_manager::cache_vzones (map * pmap = nullptr)
Definition at line 909 of file clzones.cpp.
 {
     vzone_cache.clear();
     map &here = pmap == nullptr ? get_map() : *pmap;
     auto vzones = here.get_vehicle_zones( here.get_abs_sub().z() );
     for( zone_data *elem : vzones ) {
         if( !elem->get_enabled() ) {
             continue;
         }
         const std::string &type_hash = elem->get_type_hash();
         auto &cache = vzone_cache[type_hash];
         // TODO: looks very similar to the above cache_data - maybe merge it?
         // Draw marked area
         for( const tripoint_abs_ms &p : tripoint_range<tripoint_abs_ms>(
                  elem->get_start_point(), elem->get_end_point() ) ) {
             cache.insert( p );
         }
     }
 }
References map::get_abs_sub(), get_map(), map::get_vehicle_zones(), vzone_cache, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by activity_on_turn_move_loot(), create_vehicle_loot_zone(), basecamp::distribute_food(), unload_loot_activity_actor::do_turn(), basecamp::form_crafting_inventory(), basecamp::form_storage_zones(), map::get_vehicle_zones(), load_zones(), loot(), remove(), revert_vzones(), and map::vehmove().
clear()
void zone_manager::clear ()
Definition at line 103 of file clzones.cpp.
 {
     zones.clear();
     added_vzones.clear();
     changed_vzones.clear();
     removed_vzones.clear();
     // Do not clear types since it is needed for the next games.
     area_cache.clear();
     vzone_cache.clear();
 }
References added_vzones, area_cache, changed_vzones, removed_vzones, vzone_cache, and zones.
create_vehicle_loot_zone()
void zone_manager::create_vehicle_loot_zone (class vehicle & vehicle, const point & mount_point, zone_data & new_zone, map * pmap = nullptr)
Definition at line 1373 of file clzones.cpp.
 {
     //create a vehicle loot zone
     new_zone.set_is_vehicle( true );
     auto nz = vehicle.loot_zones.emplace( mount_point, new_zone );
     map &here = pmap == nullptr ? get_map() : *pmap;
     here.register_vehicle_zone( &vehicle, here.get_abs_sub().z() );
     added_vzones.push_back( &nz->second );
     cache_vzones( pmap );
 }
References added_vzones, cache_vzones(), map::get_abs_sub(), get_map(), vehicle::loot_zones, map::register_vehicle_zone(), zone_data::set_is_vehicle(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by add(), vehicle::merge_rackable_vehicle(), and vehicle::split_vehicles().
custom_loot_has()
bool zone_manager::custom_loot_has (const tripoint_abs_ms & where, const item * it, const zone_type_id & ztype, const faction_id & fac = your_fac) const
Definition at line 1104 of file clzones.cpp.
 {
     std::vector<zone_data const *> const zones = get_zones_at( where, ztype, fac );
     if( zones.empty() || !it ) {
         return false;
     }
     item const *const check_it = it->this_or_single_content();
     for( zone_data const *zone : zones ) {
         loot_options const &options = dynamic_cast<const loot_options &>( zone->get_options() );
         std::string const filter_string = options.get_mark();
         bool has = false;
         if( ztype == zone_type_LOOT_CUSTOM ) {
             auto const z = item_filter_from_string( filter_string );
             has = z( *check_it ) || ( check_it != it && z( *it ) );
         } else if( ztype == zone_type_LOOT_ITEM_GROUP ) {
             has = item_group::group_contains_item( item_group_id( filter_string ),
                                                    check_it->typeId() ) ||
                   ( check_it != it &&
                     item_group::group_contains_item( item_group_id( filter_string ),
                             it->typeId() ) );
         }
         if( has ) {
             return true;
         }
     }
     return false;
 }
References get_zones_at(), item_group::group_contains_item(), has(), item_filter_from_string(), item_group_id, PATH_INFO::options(), item::this_or_single_content(), item::typeId(), zone_type_LOOT_CUSTOM, zone_type_LOOT_ITEM_GROUP, and zones.
Referenced by activity_on_turn_move_loot(), and get_near().
deserialize()
void zone_manager::deserialize (const JsonValue & jv)
Definition at line 1588 of file clzones.cpp.
 {
     jv.read( zones );
     for( auto it = zones.begin(); it != zones.end(); ) {
         // need to keep track of number of personal zones on reload
         if( it->get_is_personal() ) {
             num_personal_zones++;
         }
         const zone_type_id zone_type = it->get_type();
         if( !has_type( zone_type ) ) {
             it = zones.erase( it );
             debugmsg( "Invalid zone type: %s", zone_type.c_str() );
         } else  if( it->get_faction() != faction_your_followers ) {
             it = zones.erase( it );
         } else {
             it++;
         }
     }
 }
References debugmsg, faction_your_followers, has_type(), num_personal_zones, JsonValue::read(), and zones.
Referenced by load_zones().
get_bottom_zone()
const zone_data * zone_manager::get_bottom_zone (const tripoint_abs_ms & where, const faction_id & fac = your_fac) const
Definition at line 1340 of file clzones.cpp.
 {
     for( auto it = zones.rbegin(); it != zones.rend(); ++it ) {
         const zone_data &zone = *it;
         if( zone.get_faction() != fac ) {
             continue;
         }
         if( zone.has_inside( where ) ) {
             return &zone;
         }
     }
     map &here = get_map();
     auto vzones = here.get_vehicle_zones( here.get_abs_sub().z() );
     for( auto it = vzones.rbegin(); it != vzones.rend(); ++it ) {
         const zone_data *zone = *it;
         if( zone->get_faction() != fac ) {
             continue;
         }
         if( zone->has_inside( where ) ) {
             return zone;
         }
     }
     return nullptr;
 }
References map::get_abs_sub(), zone_data::get_faction(), get_map(), map::get_vehicle_zones(), zone_data::has_inside(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and zones.
get_manager()
static zone_manager& zone_manager::get_manager () inline static
Definition at line 550 of file clzones.h.
{
             static zone_manager manager;
             return manager;
         }
Referenced by activity_on_turn_move_loot(), add_fallback_zone(), are_requirements_nearby(), vehicle::autopilot_patrol(), vehicle::autopilot_patrol_check(), can_do_activity_there(), game::check_near_zone(), game::check_zone(), consume_items_in_zones(), basecamp::distribute_food(), distribute_items_to_npc_zones(), unload_loot_activity_actor::do_turn(), overmap_ui::draw_ascii(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), find_refuel_spot_zone(), basecamp::form_crafting_inventory(), basecamp::form_storage_zones(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_locations(), get_auto_consume_moves(), map::get_vehicle_zones(), npc::good_escape_direction(), npc::handle_sound(), has_loot_dest_near(), game::load(), loot(), mapgen_place_zone(), vehicle::merge_rackable_vehicle(), perform_zone_activity_turn(), start_location::place_player(), firestarter_actor::prep_firestarter_use(), plot_options::query_seed(), query_type(), vehicle::refresh_zones(), requirements_map(), map::rotate(), game::save(), zone_data::set_enabled(), zone_data::set_name(), zone_data::set_position(), zone_data::set_type(), vehicle::split_vehicles(), tidy_activity(), zone_data::toggle_display(), trade_ui::trade_ui(), basecamp::validate_sort_points(), map::vehmove(), and game::zones_manager().
get_name_from_type()
std::string zone_manager::get_name_from_type (const zone_type_id & type) const
Definition at line 833 of file clzones.cpp.
 {
     const auto &iter = types.find( type );
     if( iter != types.end() ) {
         return iter->second.name();
     }
     return "Unknown Type";
 }
References type, and types.
Referenced by loot(), and game::zones_manager().
get_near()
std::unordered_set< tripoint_abs_ms > zone_manager::get_near (const zone_type_id & type, const tripoint_abs_ms & where, int range = MAX_DISTANCE, const item * it = nullptr, const faction_id & fac = your_fac) const
Definition at line 1134 of file clzones.cpp.
 {
     const auto &point_set = get_point_set( type, fac );
     std::unordered_set<tripoint_abs_ms> near_point_set;
     for( const tripoint_abs_ms &point : point_set ) {
         if( square_dist( point, where ) <= range ) {
             if( ( type != zone_type_LOOT_CUSTOM && type != zone_type_LOOT_ITEM_GROUP ) ||
                 ( it != nullptr && custom_loot_has( point, it, type, fac ) ) ) {
                 near_point_set.insert( point );
             }
         }
     }
     const auto &vzone_set = get_vzone_set( type, fac );
     for( const tripoint_abs_ms &point : vzone_set ) {
         if( point.z() == where.z() ) {
             if( square_dist( point, where ) <= range ) {
                 if( ( type != zone_type_LOOT_CUSTOM && type != zone_type_LOOT_ITEM_GROUP ) ||
                     ( it != nullptr && custom_loot_has( point, it, type, fac ) ) ) {
                     near_point_set.insert( point );
                 }
             }
         }
     }
     return near_point_set;
 }
References custom_loot_has(), get_point_set(), get_vzone_set(), square_dist(), type, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), zone_type_LOOT_CUSTOM, and zone_type_LOOT_ITEM_GROUP.
Referenced by activity_on_turn_move_loot(), add_basecamp_storage_to_loot_zone_list(), vehicle::autopilot_patrol(), basecamp::distribute_food(), distribute_items_to_npc_zones(), unload_loot_activity_actor::do_turn(), find_refuel_spot_zone(), generic_multi_activity_locations(), get_auto_consume_moves(), get_near_zone_type_for_item(), perform_zone_activity_turn(), plot_options::query_seed(), and tidy_activity().
get_near_zone_type_for_item()
zone_type_id zone_manager::get_near_zone_type_for_item (const item & it, const tripoint_abs_ms & where, int range = MAX_DISTANCE, const faction_id & fac = your_fac) const
Definition at line 1202 of file clzones.cpp.
 {
     const item_category &cat = it.get_category_of_contents();
     if( has_near( zone_type_LOOT_CUSTOM, where, range, fac ) ) {
         if( !get_near( zone_type_LOOT_CUSTOM, where, range, &it, fac ).empty() ) {
             return zone_type_LOOT_CUSTOM;
         }
     }
     if( has_near( zone_type_LOOT_ITEM_GROUP, where, range, fac ) ) {
         if( !get_near( zone_type_LOOT_ITEM_GROUP, where, range, &it, fac ).empty() ) {
             return zone_type_LOOT_ITEM_GROUP;
         }
     }
     if( it.has_flag( STATIC( flag_id( "FIREWOOD" ) ) ) ) {
         if( has_near( zone_type_LOOT_WOOD, where, range, fac ) ) {
             return zone_type_LOOT_WOOD;
         }
     }
     if( it.is_corpse() ) {
         if( has_near( zone_type_LOOT_CORPSE, where, range, fac ) ) {
             return zone_type_LOOT_CORPSE;
         }
     }
     if( it.typeId() == itype_disassembly ) {
         if( has_near( zone_type_DISASSEMBLE, where, range, fac ) ) {
             return zone_type_DISASSEMBLE;
         }
     }
     std::optional<zone_type_id> zone_check_first = cat.priority_zone( it );
     if( zone_check_first && has_near( *zone_check_first, where, range, fac ) ) {
         return *zone_check_first;
     }
     std::optional<zone_type_id> zone_cat = cat.zone();
     if( zone_cat && has_near( *zone_cat, where, range, fac ) ) {
         return *cat.zone();
     }
     if( cat.get_id() == item_category_food ) {
         const item *it_food = nullptr;
         bool perishable = false;
         // Look for food, and whether any contents which will spoil if left out.
         // Food crafts and food without comestible, like MREs, will fall down to LOOT_FOOD.
         it.visit_items( [&it_food, &perishable]( const item * node, const item * parent ) {
             if( node && node->is_food() ) {
                 it_food = node;
                 if( node->goes_bad() ) {
                     float spoil_multiplier = 1.0f;
                     if( parent ) {
                         const item_pocket *parent_pocket = parent->contained_where( *node );
                         if( parent_pocket ) {
                             spoil_multiplier = parent_pocket->spoil_multiplier();
                         }
                     }
                     if( spoil_multiplier > 0.0f ) {
                         perishable = true;
                     }
                 }
             }
             return VisitResponse::NEXT;
         } );
         if( it_food != nullptr ) {
             if( it_food->get_comestible()->comesttype == "DRINK" ) {
                 if( perishable && has_near( zone_type_LOOT_PDRINK, where, range, fac ) ) {
                     if( !get_near( zone_type_LOOT_PDRINK, where, range, &it, fac ).empty() ) {
                         return zone_type_LOOT_PDRINK;
                     }
                 } else if( has_near( zone_type_LOOT_DRINK, where, range, fac ) ) {
                     if( !get_near( zone_type_LOOT_DRINK, where, range, &it, fac ).empty() ) {
                         return zone_type_LOOT_DRINK;
                     }
                 }
             }
             if( perishable && has_near( zone_type_LOOT_PFOOD, where, range, fac ) ) {
                 if( !get_near( zone_type_LOOT_PFOOD, where, range, &it, fac ).empty() ) {
                     return zone_type_LOOT_PFOOD;
                 }
             }
         }
         if( !get_near( zone_type_LOOT_FOOD, where, range, &it, fac ).empty() ) {
             return zone_type_LOOT_FOOD;
         }
     }
     if( has_near( zone_type_LOOT_DEFAULT, where, range, fac ) ) {
         if( !get_near( zone_type_LOOT_DEFAULT, where, range, &it, fac ).empty() ) {
             return zone_type_LOOT_DEFAULT;
         }
     }
     return zone_type_id();
 }
References flag_id, item::get_category_of_contents(), item_category::get_id(), get_near(), item::has_flag(), has_near(), item::is_corpse(), item::is_food(), item_category_food, itype_disassembly, NEXT, item_category::priority_zone(), STATIC, item::typeId(), item::visit_items(), item_category::zone(), zone_type_DISASSEMBLE, zone_type_LOOT_CORPSE, zone_type_LOOT_CUSTOM, zone_type_LOOT_DRINK, zone_type_LOOT_FOOD, zone_type_LOOT_ITEM_GROUP, zone_type_LOOT_PDRINK, zone_type_LOOT_PFOOD, and zone_type_LOOT_WOOD.
Referenced by activity_on_turn_move_loot(), and distribute_items_to_npc_zones().
get_near_zones()
std::vector< zone_data const * > zone_manager::get_near_zones (const zone_type_id & type, const tripoint_abs_ms & where, int range, const faction_id & fac = your_fac) const
Definition at line 1033 of file clzones.cpp.
 {
     std::vector<zone_data const *> ret;
     for( const zone_data &zone : zones ) {
         if( square_dist( zone.get_center_point(), where ) <= range && zone.get_type() == type &&
             zone.get_faction() == fac ) {
             ret.emplace_back( &zone );
         }
     }
     map &here = get_map();
     auto vzones = here.get_vehicle_zones( here.get_abs_sub().z() );
     for( const zone_data *zone : vzones ) {
         if( square_dist( zone->get_center_point(), where ) <= range && zone->get_type() == type &&
             zone->get_faction() == fac ) {
             ret.emplace_back( zone );
         }
     }
     return ret;
 }
References map::get_abs_sub(), get_map(), map::get_vehicle_zones(), cata::hash64_detail::ret, square_dist(), type, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and zones.
Referenced by basecamp::form_storage_zones().
get_nearest()
std::optional< tripoint_abs_ms > zone_manager::get_nearest (const zone_type_id & type, const tripoint_abs_ms & where, int range = MAX_DISTANCE, const faction_id & fac = your_fac) const
Definition at line 1164 of file clzones.cpp.
 {
     if( range < 0 ) {
         return std::nullopt;
     }
     tripoint_abs_ms nearest_pos( INT_MIN, INT_MIN, INT_MIN );
     int nearest_dist = range + 1;
     const std::unordered_set<tripoint_abs_ms> &point_set = get_point_set( type, fac );
     for( const tripoint_abs_ms &p : point_set ) {
         int cur_dist = square_dist( p, where );
         if( cur_dist < nearest_dist ) {
             nearest_dist = cur_dist;
             nearest_pos = p;
             if( nearest_dist == 0 ) {
                 return nearest_pos;
             }
         }
     }
     const std::unordered_set<tripoint_abs_ms> &vzone_set = get_vzone_set( type, fac );
     for( const tripoint_abs_ms &p : vzone_set ) {
         int cur_dist = square_dist( p, where );
         if( cur_dist < nearest_dist ) {
             nearest_dist = cur_dist;
             nearest_pos = p;
             if( nearest_dist == 0 ) {
                 return nearest_pos;
             }
         }
     }
     if( nearest_dist > range ) {
         return std::nullopt;
     }
     return nearest_pos;
 }
References get_point_set(), get_vzone_set(), square_dist(), and type.
Referenced by npc::good_escape_direction().
get_point_set()
std::unordered_set< tripoint_abs_ms > zone_manager::get_point_set (const zone_type_id & type, const faction_id & fac = your_fac) const private
Definition at line 932 of file clzones.cpp.
 {
     const auto &type_iter = area_cache.find( zone_data::make_type_hash( type, fac ) );
     if( type_iter == area_cache.end() ) {
         return std::unordered_set<tripoint_abs_ms>();
     }
     return type_iter->second;
 }
References area_cache, zone_data::make_type_hash(), and type.
Referenced by get_near(), get_nearest(), has(), and has_near().
get_point_set_loot() [1/2]
std::unordered_set< tripoint > zone_manager::get_point_set_loot (const tripoint_abs_ms & where, int radius, bool npc_search, const faction_id & fac = your_fac) const
Definition at line 949 of file clzones.cpp.
 {
     std::unordered_set<tripoint> res;
     map &here = get_map();
     for( const std::pair<std::string, std::unordered_set<tripoint_abs_ms>> cache : area_cache ) {
         zone_type_id type = zone_data::unhash_type( cache.first );
         faction_id z_fac = zone_data::unhash_fac( cache.first );
         if( fac == z_fac && type.str().substr( 0, 4 ) == "LOOT" ) {
             for( tripoint_abs_ms point : cache.second ) {
                 if( square_dist( where, point ) <= radius ) {
                     res.emplace( here.getlocal( point ) );
                 }
             }
         }
     }
     for( const std::pair<std::string, std::unordered_set<tripoint_abs_ms>> cache : vzone_cache ) {
         zone_type_id type = zone_data::unhash_type( cache.first );
         faction_id z_fac = zone_data::unhash_fac( cache.first );
         if( fac == z_fac && type.str().substr( 0, 4 ) == "LOOT" ) {
             for( tripoint_abs_ms point : cache.second ) {
                 if( square_dist( where, point ) <= radius ) {
                     res.emplace( here.getlocal( point ) );
                 }
             }
         }
     }
     if( npc_search ) {
         for( const std::pair<std::string, std::unordered_set<tripoint_abs_ms>> cache : vzone_cache ) {
             zone_type_id type = zone_data::unhash_type( cache.first );
             if( type == zone_type_NO_NPC_PICKUP ) {
                 for( tripoint_abs_ms point : cache.second ) {
                     res.erase( here.getlocal( point ) );
                 }
             }
         }
     }
     return res;
 }
References area_cache, get_map(), map::getlocal(), square_dist(), type, zone_data::unhash_fac(), zone_data::unhash_type(), vzone_cache, and zone_type_NO_NPC_PICKUP.
get_point_set_loot() [2/2]
std::unordered_set< tripoint > zone_manager::get_point_set_loot (const tripoint_abs_ms & where, int radius, const faction_id & fac = your_fac) const
Definition at line 943 of file clzones.cpp.
 {
     return get_point_set_loot( where, radius, false, fac );
 }
Referenced by consume_items_in_zones(), generic_multi_activity_check_requirement(), requirements_map(), and trade_ui::trade_ui().
get_types()
const std::map<zone_type_id, zone_type>& zone_manager::get_types () const inline
Definition at line 576 of file clzones.h.
{
             return types;
         }
References types.
Referenced by has_loot_dest_near(), and query_type().
get_vzone_set()
std::unordered_set< tripoint_abs_ms > zone_manager::get_vzone_set (const zone_type_id & type, const faction_id & fac = your_fac) const private
Definition at line 991 of file clzones.cpp.
 {
     //Only regenerate the vehicle zone cache if any vehicles have moved
     const auto &type_iter = vzone_cache.find( zone_data::make_type_hash( type, fac ) );
     if( type_iter == vzone_cache.end() ) {
         return std::unordered_set<tripoint_abs_ms>();
     }
     return type_iter->second;
 }
References zone_data::make_type_hash(), type, and vzone_cache.
Referenced by get_near(), get_nearest(), has(), and has_near().
get_zone_at() [1/2]
const zone_data * zone_manager::get_zone_at (const tripoint_abs_ms & where, bool loot_only = false, const faction_id & fac = your_fac) const
Definition at line 1318 of file clzones.cpp.
 {
     auto const check = [&fac, loot_only, &where]( zone_data const & z ) {
         return z.get_faction() == fac &&
                ( !loot_only || z.get_type().str().substr( 0, 4 ) == "LOOT" ) &&
                z.has_inside( where );
     };
     for( auto it = zones.rbegin(); it != zones.rend(); ++it ) {
         if( check( *it ) ) {
             return &*it;
         }
     }
     auto const vzones = get_map().get_vehicle_zones( get_map().get_abs_sub().z() );
     for( zone_data *it : vzones ) {
         if( check( *it ) ) {
             return &*it;
         }
     }
     return nullptr;
 }
References check(), get_map(), map::get_vehicle_zones(), and zones.
get_zone_at() [2/2]
const zone_data * zone_manager::get_zone_at (const tripoint_abs_ms & where, const zone_type_id & type, const faction_id & fac = your_fac) const
Definition at line 1074 of file clzones.cpp.
 {
     std::vector<zone_data const *> ret = get_zones_at( where, type, fac );
     if( !ret.empty() ) {
         return ret.front();
     }
     return nullptr;
 }
References get_zones_at(), cata::hash64_detail::ret, and type.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), get_zone_for_act(), and trade_ui::trade_ui().
get_zones() [1/3]
std::vector< zone_manager::ref_zone_data > zone_manager::get_zones (const faction_id & fac = your_fac)
Definition at line 1532 of file clzones.cpp.
 {
     auto zones = std::vector<ref_zone_data>();
     for( zone_data &zone : this->zones ) {
         if( zone.get_faction() == fac ) {
             zones.emplace_back( zone );
         }
     }
     map &here = get_map();
     auto vzones = here.get_vehicle_zones( here.get_abs_sub().z() );
     for( zone_data *zone : vzones ) {
         if( zone->get_faction() == fac ) {
             zones.emplace_back( *zone );
         }
     }
     return zones;
 }
References map::get_abs_sub(), get_map(), map::get_vehicle_zones(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and zones.
get_zones() [2/3]
std::vector< zone_manager::ref_const_zone_data > zone_manager::get_zones (const faction_id & fac = your_fac) const
Definition at line 1554 of file clzones.cpp.
 {
     auto zones = std::vector<ref_const_zone_data>();
     for( const zone_data &zone : this->zones ) {
         if( zone.get_faction() == fac ) {
             zones.emplace_back( zone );
         }
     }
     map &here = get_map();
     auto vzones = here.get_vehicle_zones( here.get_abs_sub().z() );
     for( zone_data *zone : vzones ) {
         if( zone->get_faction() == fac ) {
             zones.emplace_back( *zone );
         }
     }
     return zones;
 }
References map::get_abs_sub(), get_map(), map::get_vehicle_zones(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and zones.
get_zones() [3/3]
std::vector< zone_data > zone_manager::get_zones (const zone_type_id & type, const tripoint_abs_ms & where, const faction_id & fac = your_fac) const
Definition at line 1302 of file clzones.cpp.
 {
     auto zones = std::vector<zone_data>();
     for( const zone_data &zone : this->zones ) {
         if( zone.get_type() == type && zone.get_faction() == fac ) {
             if( zone.has_inside( where ) ) {
                 zones.emplace_back( zone );
             }
         }
     }
     return zones;
 }
References type, and zones.
Referenced by can_do_activity_there(), generic_multi_activity_do(), loot(), start_location::place_player(), firestarter_actor::prep_firestarter_use(), and game::zones_manager().
get_zones_at()
std::vector< zone_data const * > zone_manager::get_zones_at (const tripoint_abs_ms & where, const zone_type_id & type, const faction_id & fac = your_fac) const
Definition at line 1085 of file clzones.cpp.
 {
     std::vector<zone_data const *> ret;
     for( const zone_data &zone : zones ) {
         if( zone.has_inside( where ) && zone.get_type() == type && zone.get_faction() == fac ) {
             ret.emplace_back( &zone );
         }
     }
     map &here = get_map();
     auto vzones = here.get_vehicle_zones( here.get_abs_sub().z() );
     for( const zone_data *zone : vzones ) {
         if( zone->has_inside( where ) && zone->get_type() == type && zone->get_faction() == fac ) {
             ret.emplace_back( zone );
         }
     }
     return ret;
 }
References map::get_abs_sub(), get_map(), map::get_vehicle_zones(), cata::hash64_detail::ret, type, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and zones.
Referenced by activity_on_turn_move_loot(), custom_loot_has(), unload_loot_activity_actor::do_turn(), and get_zone_at().
has()
bool zone_manager::has (const zone_type_id & type, const tripoint_abs_ms & where, const faction_id & fac = your_fac) const
Definition at line 1003 of file clzones.cpp.
 {
     const auto &point_set = get_point_set( type, fac );
     const auto &vzone_set = get_vzone_set( type, fac );
     return point_set.find( where ) != point_set.end() || vzone_set.find( where ) != vzone_set.end();
 }
References get_point_set(), get_vzone_set(), and type.
Referenced by activity_on_turn_move_loot(), are_requirements_nearby(), game::check_zone(), custom_loot_has(), unload_loot_activity_actor::do_turn(), npc::handle_sound(), and tidy_activity().
has_defined()
bool zone_manager::has_defined (const zone_type_id & type, const faction_id & fac = your_fac) const
Definition at line 848 of file clzones.cpp.
 {
     const auto &type_iter = area_cache.find( zone_data::make_type_hash( type, fac ) );
     return type_iter != area_cache.end();
 }
References area_cache, zone_data::make_type_hash(), and type.
has_loot_dest_near()
bool zone_manager::has_loot_dest_near (const tripoint_abs_ms & where) const
Definition at line 1057 of file clzones.cpp.
 {
     for( const auto &ztype : get_manager().get_types() ) {
         const zone_type_id &type = ztype.first;
         if( type == zone_type_CAMP_FOOD || type == zone_type_FARM_PLOT ||
             type == zone_type_LOOT_UNSORTED || type == zone_type_LOOT_IGNORE ||
             type == zone_type_CONSTRUCTION_BLUEPRINT ||
             type == zone_type_NO_AUTO_PICKUP || type == zone_type_NO_NPC_PICKUP ) {
             continue;
         }
         if( has_near( type, where ) ) {
             return true;
         }
     }
     return false;
 }
References get_manager(), get_types(), has_near(), type, zone_type_CAMP_FOOD, zone_type_CONSTRUCTION_BLUEPRINT, zone_type_FARM_PLOT, zone_type_LOOT_IGNORE, zone_type_LOOT_UNSORTED, zone_type_NO_AUTO_PICKUP, and zone_type_NO_NPC_PICKUP.
has_near()
bool zone_manager::has_near (const zone_type_id & type, const tripoint_abs_ms & where, int range = MAX_DISTANCE, const faction_id & fac = your_fac) const
Definition at line 1011 of file clzones.cpp.
 {
     const auto &point_set = get_point_set( type, fac );
     for( const tripoint_abs_ms &point : point_set ) {
         if( square_dist( point, where ) <= range ) {
             return true;
         }
     }
     const auto &vzone_set = get_vzone_set( type, fac );
     for( const tripoint_abs_ms &point : vzone_set ) {
         if( point.z() == where.z() ) {
             if( square_dist( point, where ) <= range ) {
                 return true;
             }
         }
     }
     return false;
 }
References get_point_set(), get_vzone_set(), square_dist(), type, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by activity_on_turn_move_loot(), add_basecamp_storage_to_loot_zone_list(), add_fallback_zone(), vehicle::autopilot_patrol_check(), can_do_activity_there(), game::check_near_zone(), unload_loot_activity_actor::do_turn(), basecamp::form_storage_zones(), get_near_zone_type_for_item(), has_loot_dest_near(), and basecamp::validate_sort_points().
has_personal_zones()
bool zone_manager::has_personal_zones () const
Definition at line 1577 of file clzones.cpp.
 {
     // if there are more than 0 personal zones
     return num_personal_zones > 0;
 }
References num_personal_zones.
Referenced by loot(), and game::zones_manager().
has_type()
bool zone_manager::has_type (const zone_type_id & type) const
Definition at line 843 of file clzones.cpp.
 {
     return types.count( type ) > 0;
 }
References type, and types.
Referenced by deserialize().
load_world_zones()
void zone_manager::load_world_zones (std::string const & suffix = {})
Definition at line 1746 of file clzones.cpp.
 {
     cata_path const savefile = _savefile( suffix, false );
     std::vector<zone_data> tmp;
     read_from_file_optional_json( savefile, [&]( const JsonValue & jsin ) {
         jsin.read( tmp );
         for( auto it = tmp.begin(); it != tmp.end(); ) {
             const zone_type_id zone_type = it->get_type();
             if( !has_type( zone_type ) ) {
                 it = tmp.erase( it );
                 debugmsg( "Invalid zone type: %s", zone_type.c_str() );
             } else if( it->get_faction() == faction_your_followers ) {
                 it = tmp.erase( it );
             } else {
                 ++it;
             }
         }
         std::copy( tmp.begin(), tmp.end(), std::back_inserter( zones ) );
     } );
 }
References anonymous_namespace{clzones.cpp}::_savefile(), faction_your_followers, JsonValue::read(), read_from_file_optional_json(), and zones.
Referenced by load_zones().
load_zones()
void zone_manager::load_zones (std::string const & suffix = {})
Definition at line 1712 of file clzones.cpp.
 {
     cata_path const savefile = _savefile( suffix, true );
     const auto reader = [this]( const JsonValue & jv ) {
         deserialize( jv );
     };
     if( !read_from_file_optional_json( savefile, reader ) ) {
         // If no such file or failed to load, clear zones.
         zones.clear();
     }
     load_world_zones( suffix );
     revert_vzones();
     added_vzones.clear();
     changed_vzones.clear();
     removed_vzones.clear();
     cache_data();
     cache_vzones();
 }
References anonymous_namespace{clzones.cpp}::_savefile(), added_vzones, cache_data(), cache_vzones(), changed_vzones, deserialize(), load_world_zones(), read_from_file_optional_json(), removed_vzones, revert_vzones(), and zones.
Referenced by game::load().
operator=() [1/2]
zone_manager& zone_manager::operator= (const zone_manager &) default
operator=() [2/2]
zone_manager& zone_manager::operator= (zone_manager &&) default
query_name()
std::optional< std::string > zone_manager::query_name (const std::string & default_name = "") const
Definition at line 571 of file clzones.cpp.
 {
     string_input_popup popup;
     popup
     .title( _( "Zone name:" ) )
     .width( 55 )
     .text( default_name )
     .query();
     if( popup.canceled() ) {
         return {};
     } else {
         return popup.text();
     }
 }
References _, and popup().
Referenced by zone_data::set_name(), and game::zones_manager().
query_type()
std::optional< zone_type_id > zone_manager::query_type (bool personal = false) const
Definition at line 586 of file clzones.cpp.
 {
     const auto &types = get_manager().get_types();
     // Copy zone types into an array and sort by name
     std::vector<std::pair<zone_type_id, zone_type>> types_vec;
     // only add personal functioning zones for personal
     if( personal ) {
         for( const auto &tmp : types ) {
             if( tmp.second.can_be_personal ) {
                 types_vec.emplace_back( tmp );
             }
         }
     } else {
         std::copy_if( types.begin(), types.end(), std::back_inserter( types_vec ),
         []( std::pair<zone_type_id, zone_type> const & it ) {
             return !it.first.is_valid() || !it.first->hidden;
         } );
     }
     std::sort( types_vec.begin(), types_vec.end(),
     []( const std::pair<zone_type_id, zone_type> &lhs, const std::pair<zone_type_id, zone_type> &rhs ) {
         return localized_compare( lhs.second.name(), rhs.second.name() );
     } );
     uilist as_m;
     as_m.desc_enabled = true;
     as_m.text = _( "Select zone type:" );
     size_t i = 0;
     for( const auto &pair : types_vec ) {
         const zone_type &type = pair.second;
         as_m.addentry_desc( i++, true, MENU_AUTOASSIGN, type.name(), type.desc() );
     }
     as_m.query();
     if( as_m.ret < 0 ) {
         return {};
     }
     size_t index = as_m.ret;
     auto iter = types_vec.begin();
     std::advance( iter, index );
     return iter->first;
 }
References _, uilist::addentry_desc(), uilist::desc_enabled, get_manager(), get_types(), MENU_AUTOASSIGN, uilist::query(), uilist::ret, uilist::text, type, and types.
Referenced by zone_data::set_type(), and game::zones_manager().
remove()
bool zone_manager::remove (zone_data & zone)
Definition at line 1421 of file clzones.cpp.
 {
     for( auto it = zones.begin(); it != zones.end(); ++it ) {
         if( &zone == &*it ) {
             if( zone.get_is_displayed() ) {
                 zone.toggle_display();
             }
             // if removing a personal zone reduce the number of counted personal zones
             if( it->get_is_personal() ) {
                 num_personal_zones--;
             }
             zones.erase( it );
             return true;
         }
     }
     zone_data old_zone = zone_data( zone );
     //If the zone was previously edited this session
     //Move original data out of changed
     for( auto it = changed_vzones.begin(); it != changed_vzones.end(); ++it ) {
         if( it->second == &zone ) {
             old_zone = zone_data( it->first );
             changed_vzones.erase( it );
             break;
         }
     }
     bool added = false;
     //If the zone was added this session
     //remove from added, and don't add to removed
     for( auto it = added_vzones.begin(); it != added_vzones.end(); ++it ) {
         if( *it == &zone ) {
             added = true;
             added_vzones.erase( it );
             break;
         }
     }
     if( !added ) {
         removed_vzones.push_back( old_zone );
     }
     if( !get_map().deregister_vehicle_zone( zone ) ) {
         debugmsg( "Tried to remove a zone from an unloaded vehicle" );
         return false;
     }
     cache_vzones();
     return true;
 }
References added_vzones, cache_vzones(), changed_vzones, debugmsg, zone_data::get_is_displayed(), get_map(), num_personal_zones, removed_vzones, zone_data::toggle_display(), and zones.
Referenced by revert_vzones(), and game::zones_manager().
reset_disabled()
void zone_manager::reset_disabled ()
Definition at line 881 of file clzones.cpp.
 {
     bool changed = false;
     for( zone_data &elem : zones ) {
         if( elem.get_temporarily_disabled() ) {
             elem.set_enabled( true );
             elem.set_temporary_disabled( false );
             changed = true;
         }
     }
     if( changed ) {
         cache_data();
     }
 }
References cache_data(), and zones.
Referenced by loot(), and game::zones_manager().
revert_vzones()
void zone_manager::revert_vzones ()
Definition at line 1781 of file clzones.cpp.
 {
     map &here = get_map();
     for( zone_data zone : removed_vzones ) {
         //Code is copied from add() to avoid yn query
         const tripoint pos = here.getlocal( zone.get_start_point() );
         if( const std::optional<vpart_reference> vp = here.veh_at( pos ).cargo() ) {
             zone.set_is_vehicle( true );
             vp->vehicle().loot_zones.emplace( vp->mount(), zone );
             here.register_vehicle_zone( &vp->vehicle(), here.get_abs_sub().z() );
             cache_vzones();
         }
     }
     for( const auto &zpair : changed_vzones ) {
         *( zpair.second ) = zpair.first;
     }
     for( zone_data *zone : added_vzones ) {
         remove( *zone );
     }
 }
References added_vzones, cache_vzones(), optional_vpart_position::cargo(), changed_vzones, map::get_abs_sub(), get_map(), map::getlocal(), math_opers::pos(), map::register_vehicle_zone(), remove(), removed_vzones, map::veh_at(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by load_zones().
rotate_zones()
void zone_manager::rotate_zones (map & target_map, int turns)
Definition at line 1511 of file clzones.cpp.
 {
     if( turns == 0 ) {
         return;
     }
     for( zone_data &zone : zones ) {
         if( !zone.get_is_personal() && target_map.inbounds_z( zone.get_center_point().z() ) ) {
             _rotate_zone( target_map, zone, turns );
         }
     }
     for( int z_level = target_map.supports_zlevels() ? -OVERMAP_DEPTH : target_map.get_abs_sub().z();
          z_level <= ( target_map.supports_zlevels() ? OVERMAP_HEIGHT : target_map.get_abs_sub().z() );
          z_level++ ) {
         for( zone_data *zone : target_map.get_vehicle_zones( z_level ) ) {
             _rotate_zone( target_map, *zone, turns );
         }
     }
 }
References anonymous_namespace{clzones.cpp}::_rotate_zone(), map::get_abs_sub(), map::get_vehicle_zones(), map::inbounds_z(), OVERMAP_DEPTH, OVERMAP_HEIGHT, map::supports_zlevels(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and zones.
Referenced by map::rotate().
save_world_zones()
bool zone_manager::save_world_zones (std::string const & suffix = {})
Definition at line 1733 of file clzones.cpp.
 {
     cata_path const savefile = _savefile( suffix, false );
     std::vector<zone_data> tmp;
     std::copy_if( zones.begin(), zones.end(), std::back_inserter( tmp ), []( const zone_data & z ) {
         return z.get_faction() != faction_your_followers;
     } );
     return write_to_file( savefile, [&]( std::ostream & fout ) {
         JsonOut jsout( fout );
         jsout.write( tmp );
     }, _( "zones date" ) );
 }
References _, anonymous_namespace{clzones.cpp}::_savefile(), JsonOut::write(), write_to_file(), and zones.
Referenced by save_zones().
save_zones()
bool zone_manager::save_zones (std::string const & suffix = {})
Definition at line 1698 of file clzones.cpp.
 {
     cata_path const savefile = _savefile( suffix, true );
     added_vzones.clear();
     changed_vzones.clear();
     removed_vzones.clear();
     save_world_zones( suffix );
     return write_to_file( savefile, [&]( std::ostream & fout ) {
         JsonOut jsout( fout );
         serialize( jsout );
     }, _( "zones date" ) );
 }
References _, anonymous_namespace{clzones.cpp}::_savefile(), added_vzones, changed_vzones, removed_vzones, save_world_zones(), serialize(), and write_to_file().
Referenced by game::save(), and game::zones_manager().
serialize()
void zone_manager::serialize (JsonOut & json) const
Definition at line 1583 of file clzones.cpp.
 {
     json.write( zones );
 }
References JsonOut::write(), and zones.
Referenced by save_zones().
size()
unsigned int zone_manager::size () const inline
Definition at line 573 of file clzones.h.
{
             return zones.size();
         }
References zones.
swap()
void zone_manager::swap (zone_data & a, zone_data & b)
Definition at line 1468 of file clzones.cpp.
 {
     if( a.get_is_vehicle() || b.get_is_vehicle() ) {
         //Current swap mechanic will change which vehicle the zone is on
         // TODO: track and update vehicle zone priorities?
         popup( _( "You cannot change the order of vehicle loot zones." ), PF_NONE );
         return;
     }
     std::swap( a, b );
 }
References _, a, b, PF_NONE, popup(), and cata::swap().
Referenced by game::zones_manager().
zone_edited()
void zone_manager::zone_edited (zone_data & zone)
Definition at line 1767 of file clzones.cpp.
 {
     if( zone.get_is_vehicle() ) {
         //Check if this zone has already been stored
         for( auto &changed_vzone : changed_vzones ) {
             if( &zone == changed_vzone.second ) {
                 return;
             }
         }
         //Add it to the list of changed zones
         changed_vzones.emplace_back( zone_data( zone ), &zone );
     }
 }
References changed_vzones, and zone_data::get_is_vehicle().
Referenced by zone_data::set_enabled(), zone_data::set_name(), and zone_data::set_type().
Member Data Documentation
added_vzones
std::vector<zone_data *> zone_manager::added_vzones private
Definition at line 523 of file clzones.h.
Referenced by clear(), create_vehicle_loot_zone(), load_zones(), remove(), revert_vzones(), and save_zones().
area_cache
std::unordered_map<std::string, std::unordered_set<tripoint_abs_ms> > zone_manager::area_cache private
Definition at line 535 of file clzones.h.
Referenced by cache_data(), clear(), get_point_set(), get_point_set_loot(), and has_defined().
changed_vzones
std::vector<std::pair<zone_data, zone_data *> > zone_manager::changed_vzones private
Definition at line 525 of file clzones.h.
Referenced by clear(), load_zones(), remove(), revert_vzones(), save_zones(), and zone_edited().
MAX_DISTANCE
const int zone_manager::MAX_DISTANCE = ACTIVITY_SEARCH_DISTANCE static private
Definition at line 519 of file clzones.h.
num_personal_zones
int zone_manager::num_personal_zones = 0 private
Definition at line 532 of file clzones.h.
Referenced by add(), deserialize(), has_personal_zones(), and remove().
removed_vzones
std::vector<zone_data> zone_manager::removed_vzones private
Definition at line 527 of file clzones.h.
Referenced by clear(), load_zones(), remove(), revert_vzones(), and save_zones().
types
std::map<zone_type_id, zone_type> zone_manager::types private
Definition at line 529 of file clzones.h.
Referenced by get_name_from_type(), get_types(), has_type(), query_type(), and zone_manager().
vzone_cache
std::unordered_map<std::string, std::unordered_set<tripoint_abs_ms> > zone_manager::vzone_cache private
Definition at line 537 of file clzones.h.
Referenced by cache_vzones(), clear(), get_point_set_loot(), and get_vzone_set().
zones
std::vector<zone_data> zone_manager::zones private
Definition at line 520 of file clzones.h.
Referenced by add(), cache_avatar_location(), cache_data(), clear(), custom_loot_has(), deserialize(), get_bottom_zone(), get_near_zones(), get_zone_at(), get_zones(), get_zones_at(), load_world_zones(), load_zones(), remove(), reset_disabled(), rotate_zones(), save_world_zones(), serialize(), and size().
The documentation for this class was generated from the following files:
src/clzones.h
src/clzones.cpp