Cataclysm DDA: wield_activity_actor Class Reference
wield_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
wield_activity_actor (item_location target_item, int quantity)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &)
Private Attributes
item_location target_item
int quantity
contents_change_handler handler
Detailed Description
Definition at line 1730 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
wield_activity_actor()
wield_activity_actor::wield_activity_actor (item_location target_item, int quantity) inline
Definition at line 1733 of file activity_actor_definitions.h.
                                                                         :
             target_item( std::move( target_item ) ),
             quantity( quantity ) {};
Member Function Documentation
clone()
std::unique_ptr<activity_actor> wield_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1744 of file activity_actor_definitions.h.
{
             return std::make_unique<wield_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > wield_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6075 of file activity_actor.cpp.
 {
     wield_activity_actor actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "target_items", actor.target_item );
     data.read( "quantities", actor.quantity );
     data.read( "handler", actor.handler );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void wield_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 6027 of file activity_actor.cpp.
 {
     if( who.get_moves() > 0 ) {
         if( target_item ) {
             // Make copies so the original remains untouched if wielding fails
             item newit = *target_item;
             item leftovers = newit;
             // Handle charges, quantity == 0 means move all
             if( quantity != 0 && newit.count_by_charges() ) {
                 leftovers.charges = newit.charges - quantity;
                 if( leftovers.charges > 0 ) {
                     newit.charges = quantity;
                 }
             } else {
                 leftovers.charges = 0;
             }
             if( check_stealing( who, newit ) ) {
                 handler.unseal_pocket_containing( target_item );
                 if( who.wield( newit ) ) {
                     // If we wielded up a whole stack, remove the original item
                     // Otherwise, replace the item with the leftovers
                     if( leftovers.charges > 0 ) {
                         *target_item = std::move( leftovers );
                     } else {
                         target_item.remove_item();
                     }
                 }
                 handler.handle_by( who );
             }
         }
         who.cancel_activity();
     }
 }
References Character::cancel_activity(), item::charges, check_stealing(), item::count_by_charges(), Creature::get_moves(), contents_change_handler::handle_by(), handler, quantity, item_location::remove_item(), target_item, contents_change_handler::unseal_pocket_containing(), and Character::wield().
finish()
void wield_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1742 of file activity_actor_definitions.h.
 {};
get_type()
activity_id wield_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1736 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_WIELD" );
         }
References activity_id.
serialize()
void wield_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6064 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target_items", target_item );
     jsout.member( "quantities", quantity );
     jsout.member( "handler", handler );
     jsout.end_object();
 }
References JsonOut::end_object(), handler, JsonOut::member(), quantity, JsonOut::start_object(), and target_item.
start()
void wield_activity_actor::start (player_activity & act, Character & who) inline override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1740 of file activity_actor_definitions.h.
 {};
Member Data Documentation
handler
contents_change_handler wield_activity_actor::handler private
Definition at line 1754 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
quantity
int wield_activity_actor::quantity private
Definition at line 1753 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
target_item
item_location wield_activity_actor::target_item private
Definition at line 1752 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp