Cataclysm DDA: event_transformation Class Reference
event_transformation Class Reference
#include <event_statistics.h>
Classes
class impl
Public Member Functions
event_multiset value (stats_tracker &) const
std::unique_ptr< stats_tracker_state > watch (stats_tracker &) const
void load (const JsonObject &, std::string_view)
void check () const
event_fields_type fields () const
monotonically monotonicity () const
Static Public Member Functions
static void load_transformation (const JsonObject &, const std::string &)
static void check_consistency ()
static void reset ()
Public Attributes
string_id< event_transformation > id
std::vector< std::pair< string_id< event_transformation >, mod_id > > src
bool was_loaded = false
Private Attributes
cata::clone_ptr< impl > impl_
Detailed Description
Definition at line 45 of file event_statistics.h.
Member Function Documentation
check()
void event_transformation::check () const
Definition at line 721 of file event_statistics.cpp.
 {
     impl_->check( id.str() );
 }
References impl_.
check_consistency()
void event_transformation::check_consistency () static
Definition at line 82 of file event_statistics.cpp.
 {
     event_transformation_factory.check();
 }
References anonymous_namespace{event_statistics.cpp}::event_transformation_factory.
Referenced by DynamicDataLoader::check_consistency().
fields()
cata::event::fields_type event_transformation::fields () const
Definition at line 726 of file event_statistics.cpp.
 {
     return impl_->fields();
 }
References impl_.
Referenced by event_transformation_event_source::fields().
load()
void event_transformation::load (const JsonObject & jo, std::string_view)
Definition at line 704 of file event_statistics.cpp.
 {
     std::map<std::string, new_field> new_fields;
     optional( jo, was_loaded, "new_fields", new_fields );
     std::map<std::string, value_constraint> constraints;
     optional( jo, was_loaded, "value_constraints", constraints );
     std::vector<std::string> drop_fields;
     optional( jo, was_loaded, "drop_fields", drop_fields );
     if( new_fields.empty() && constraints.empty() && drop_fields.empty() ) {
         jo.throw_error( "Event transformation is a no-op." );
     }
     impl_ = std::make_unique<event_transformation_impl>(
                 id, event_source::load( jo ), new_fields, constraints, drop_fields );
 }
References impl_, event_source::load(), optional(), JsonObject::throw_error(), and was_loaded.
load_transformation()
void event_transformation::load_transformation (const JsonObject & jo, const std::string & src) static
Definition at line 77 of file event_statistics.cpp.
 {
     event_transformation_factory.load( jo, src );
 }
References anonymous_namespace{event_statistics.cpp}::event_transformation_factory, and src.
Referenced by DynamicDataLoader::initialize().
monotonicity()
monotonically event_transformation::monotonicity () const
Definition at line 731 of file event_statistics.cpp.
 {
     return impl_->monotonicity();
 }
References impl_.
Referenced by event_transformation_event_source::monotonicity().
reset()
void event_transformation::reset () static
Definition at line 87 of file event_statistics.cpp.
 {
     event_transformation_factory.reset();
 }
References anonymous_namespace{event_statistics.cpp}::event_transformation_factory.
Referenced by DynamicDataLoader::unload_data().
value()
event_multiset event_transformation::value (stats_tracker & stats) const
Definition at line 694 of file event_statistics.cpp.
 {
     return impl_->initialize( stats );
 }
References impl_.
Referenced by stats_tracker::get_events().
watch()
std::unique_ptr< stats_tracker_state > event_transformation::watch (stats_tracker & stats) const
Definition at line 699 of file event_statistics.cpp.
 {
     return impl_->watch( stats );
 }
References impl_.
Member Data Documentation
id
string_id<event_transformation> event_transformation::id
Definition at line 57 of file event_statistics.h.
Referenced by event_transformation_event_source::debug_description().
impl_
cata::clone_ptr<impl> event_transformation::impl_ private
Definition at line 67 of file event_statistics.h.
Referenced by check(), fields(), load(), monotonicity(), value(), and watch().
src
std::vector<std::pair<string_id<event_transformation>, mod_id> > event_transformation::src
Definition at line 58 of file event_statistics.h.
Referenced by load_transformation().
was_loaded
bool event_transformation::was_loaded = false
Definition at line 59 of file event_statistics.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/event_statistics.h
src/event_statistics.cpp