Cataclysm DDA: item_contents Class Reference
item_contents Class Reference
#include <item_contents.h>
Classes
struct item_contents_helper
Public Member Functions
item_contents ()=default
item_contents (const std::vector< pocket_data > &pockets)
std::pair< item_location, item_pocket * > best_pocket (const item &it, item_location &this_loc, const item *avoid=nullptr, bool allow_sealed=false, bool ignore_settings=false, bool nested=false, bool ignore_rigidity=false)
returns an item_location and pointer to the best pocket that can contain the item @it checks all items contained in every pocket only checks CONTAINER pocket type
units::length max_containable_length (bool unrestricted_pockets_only=false) const
units::length min_containable_length () const
units::volume max_containable_volume (bool unrestricted_pockets_only=false) const
std::set< flag_id > magazine_flag_restrictions () const
ret_val< void > is_compatible (const item &it) const
returns whether any of the pockets contained is compatible with the specified item.
ret_val< void > can_contain (const item &it, bool ignore_pkt_settings=true, bool is_pick_up_inv=false, units::volume remaining_parent_volume=10000000_ml) const
returns whether an item can be physically stored within these item contents.
ret_val< void > can_contain (const item &it, int &copies_remaining, bool ignore_pkt_settings=true, bool is_pick_up_inv=false, units::volume remaining_parent_volume=10000000_ml) const
ret_val< void > can_contain_rigid (const item &it, bool ignore_pkt_settings=true, bool is_pick_up_inv=false) const
ret_val< void > can_contain_rigid (const item &it, int &copies_remaining, bool ignore_pkt_settings=true, bool is_pick_up_inv=false) const
bool can_contain_liquid (bool held_or_ground) const
bool contains_no_solids () const
bool can_reload_with (const item &ammo, bool now) const
returns whether any of the pockets can be reloaded with the specified item.
bool empty () const
bool empty_with_no_mods () const
bool empty_container () const
bool full (bool allow_bucket) const
bool is_magazine_full () const
bool bigger_on_the_inside (const units::volume &container_volume) const
size_t size () const
std::list< item * > all_items_top (const std::function< bool(item_pocket &)> &filter)
returns a list of pointers to all top-level items from pockets that match the predicate
std::list< const item * > all_items_top (const std::function< bool(const item_pocket &)> &filter) const
returns a list of pointers to all top-level items from pockets that match the predicate
std::list< item * > all_items_top (pocket_type pk_type, bool unloading=false)
returns a list of pointers to all top-level items
std::list< const item * > all_items_top (pocket_type pk_type) const
returns a list of pointers to all top-level items
std::list< item * > all_items_top ()
returns a list of pointers to all top-level items that are not mods
std::list< const item * > all_items_top () const
returns a list of pointers to all top-level items that are not mods
std::list< item * > all_known_contents ()
returns a list of pointers to all visible or remembered content items that are not mods
std::list< const item * > all_known_contents () const
std::list< item * > all_ablative_armor ()
std::list< const item * > all_ablative_armor () const
content_newness get_content_newness (const std::set< itype_id > &read_items) const
don't check top level item, do check its pockets, do check all nested
std::vector< item * > gunmods ()
gets all gunmods in the item
std::vector< const item * > gunmods () const
gets all gunmods in the item
bool allows_speedloader (const itype_id &speedloader_id) const
std::vector< const item * > mods () const
std::vector< const item * > softwares () const
std::vector< item * > ebooks ()
std::vector< const item * > ebooks () const
std::vector< item * > cables ()
std::vector< const item * > cables () const
void update_modified_pockets (const std::optional< const pocket_data * > &mag_or_mag_well, std::vector< const pocket_data * > container_pockets)
std::set< itype_id > magazine_compatible () const
itype_id magazine_default () const
item & legacy_front ()
This function is to aid migration to using nested containers.
const item & legacy_front () const
units::volume item_size_modifier () const
units::mass item_weight_modifier () const
units::length item_length_modifier () const
units::mass total_container_weight_capacity (bool unrestricted_pockets_only=false) const
units::volume total_container_capacity (bool unrestricted_pockets_only=false) const
gets the total volume available to be used.
units::volume total_standard_capacity (bool unrestricted_pockets_only=false) const
units::volume remaining_container_capacity (bool unrestricted_pockets_only=false) const
units::volume total_contained_volume (bool unrestricted_pockets_only=false) const
units::mass remaining_container_capacity_weight (bool unrestricted_pockets_only=false) const
units::mass total_contained_weight (bool unrestricted_pockets_only=false) const
units::volume get_contents_volume_with_tweaks (const std::map< const item *, int > &without) const
units::volume get_nested_content_volume_recursive (const std::map< const item *, int > &without) const
int get_used_holsters () const
int get_total_holsters () const
units::volume get_total_holster_volume () const
units::volume get_used_holster_volume () const
units::mass get_total_holster_weight () const
units::mass get_used_holster_weight () const
std::vector< const item_pocket * > get_all_contained_pockets () const
std::vector< item_pocket * > get_all_contained_pockets ()
std::vector< const item_pocket * > get_all_standard_pockets () const
std::vector< item_pocket * > get_all_standard_pockets ()
std::vector< const item_pocket * > get_all_ablative_pockets () const
std::vector< item_pocket * > get_all_ablative_pockets ()
std::vector< const item_pocket * > get_pockets (std::function< bool(item_pocket const &)> const &filter) const
std::vector< item_pocket * > get_pockets (std::function< bool(item_pocket const &)> const &filter)
void add_pocket (const item &pocket)
item remove_pocket (int index)
const item_pocket * get_added_pocket (int index) const
std::vector< const item * > get_added_pockets () const
bool has_additional_pockets () const
int get_additional_pocket_encumbrance (float mod) const
int get_additional_space_used () const
units::mass get_additional_weight () const
units::volume get_additional_volume () const
std::vector< const item_pocket * > get_all_reloadable_pockets () const
int remaining_capacity_for_liquid (const item &liquid) const
float relative_encumbrance () const
If contents should contribute to encumbrance, returns a value between 0 and 1 indicating the position between minimum and maximum contribution it's currently making.
bool all_pockets_rigid () const
True if every pocket is rigid or we have no pockets.
int best_quality (const quality_id &id) const
returns the best quality of the id that's contained in the item in CONTAINER pockets
int obtain_cost (const item &it) const
int insert_cost (const item &it) const
ret_val< item * > insert_item (const item &it, pocket_type pk_type, bool ignore_contents=false, bool unseal_pockets=false)
Attempts to insert an item into these item contents, stipulating that it must go into a pocket of the given type.
void force_insert_item (const item &it, pocket_type pk_type)
bool can_unload_liquid () const
size_t num_item_stacks () const
returns the number of items stacks in contents each item that is not count_by_charges, plus whole stacks of items that are
void favorite_settings_menu (item *i)
Open a menu for the player to set pocket favorite settings for the pockets in this item_contents.
item_pocket * contained_where (const item &contained)
void on_pickup (Character &guy, item *avoid=nullptr)
bool spill_contents (const tripoint &pos)
void overflow (const tripoint &pos, const item_location &loc)
void clear_items ()
void clear_magazines ()
void clear_pockets_if (const std::function< bool(item_pocket const &)> &filter)
void update_open_pockets ()
void set_item_defaults ()
Sets the items contained to their defaults.
bool seal_all_pockets ()
bool all_pockets_sealed () const
bool any_pockets_sealed () const
void heat_up ()
int ammo_consume (int qty, const tripoint &pos, float fuel_efficiency=-1.0)
item * magazine_current ()
std::set< ammotype > ammo_types () const
int ammo_capacity (const ammotype &ammo) const
item & first_ammo ()
const item & first_ammo () const
void handle_liquid_or_spill (Character &guy, const item *avoid=nullptr)
bool will_spill () const
bool will_spill_if_unsealed () const
bool spill_open_pockets (Character &guy, const item *avoid=nullptr)
void casings_handle (const std::function< bool(item &)> &func)
item & only_item ()
item & first_item ()
const item & only_item () const
const item & first_item () const
item * get_item_with (const std::function< bool(const item &)> &filter)
const item * get_item_with (const std::function< bool(const item &)> &filter) const
void remove_items_if (const std::function< bool(item &)> &filter)
bool has_pocket_type (pocket_type pk_type) const
bool has_unrestricted_pockets () const
bool has_any_with (const std::function< bool(const item &)> &filter, pocket_type pk_type) const
void process (map &here, Character *carrier, const tripoint &pos, float insulation=1, temperature_flag flag=temperature_flag::NORMAL, float spoil_multiplier_parent=1.0f)
Is part of the recursive call of item::process.
void leak (map &here, Character *carrier, const tripoint &pos, item_pocket *pocke=nullptr)
bool item_has_uses_recursive () const
bool stacks_with (const item_contents &rhs, int depth=0, int maxdepth=2) const
bool same_contents (const item_contents &rhs) const
bool is_funnel_container (units::volume &bigger_than) const
bool is_restricted_container () const
bool is_single_restricted_container () const
void remove_internal (const std::function< bool(item &)> &filter, int &count, std::list< item > &res)
void info (std::vector< iteminfo > &info, const iteminfo_query *parts) const
void read_mods (const item_contents &read_input)
void combine (const item_contents &read_input, bool convert=false, bool into_bottom=false, bool restack_charges=true, bool ignore_contents=false)
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
Private Member Functions
ret_val< item_pocket * > find_pocket_for (const item &it, pocket_type pk_type=pocket_type::CONTAINER)
ret_val< const item_pocket * > find_pocket_for (const item &it, pocket_type pk_type=pocket_type::CONTAINER) const
Private Attributes
std::list< item_pocket > contents
std::vector< item > additional_pockets
units::volume additional_pockets_volume = 0_ml
int additional_pockets_space_used = 0
Friends
struct item_contents_helper
Related Functions
(Note that these are not member functions.)
VisitResponse visit_contents (const std::function< VisitResponse(item *, item *)> &func, item *parent=nullptr)
NOTE: upon expansion, this may need to be filtered by type enum depending on accessibility.
Detailed Description
Definition at line 37 of file item_contents.h.
Constructor & Destructor Documentation
item_contents() [1/2]
item_contents::item_contents () default
item_contents() [2/2]
item_contents::item_contents (const std::vector< pocket_data > & pockets) explicit
Definition at line 570 of file item_contents.cpp.
 {
     for( const pocket_data &data : pockets ) {
         contents.emplace_back( &data );
     }
 }
References contents.
Member Function Documentation
add_pocket()
void item_contents::add_pocket (const item & pocket)
Definition at line 2119 of file item_contents.cpp.
 {
     units::volume total_nonrigid_volume = 0_ml;
     for( const item_pocket *i_pocket : pocket_item.get_all_contained_pockets() ) {
         // need to insert before the end since the final pocket is the migration pocket
         contents.insert( --contents.end(), *i_pocket );
         // these pockets should fallback to using the item name as a description
         // need to update it once it's stored in the contents list
         ( ++contents.rbegin() )->name_as_description = true;
         total_nonrigid_volume += i_pocket->max_contains_volume();
     }
     additional_pockets_volume += total_nonrigid_volume;
     additional_pockets_space_used += pocket_item.get_pocket_size();
     additional_pockets.push_back( pocket_item );
     additional_pockets.back().clear_items();
 }
References additional_pockets, additional_pockets_space_used, additional_pockets_volume, contents, item::get_all_contained_pockets(), and item::get_pocket_size().
Referenced by combine(), Item_modifier::modify(), and molle_attach_actor::use().
all_ablative_armor() [1/2]
std::list< item * > item_contents::all_ablative_armor ()
Definition at line 1777 of file item_contents.cpp.
 {
     return all_items_top( []( const item_pocket & pocket ) {
         return pocket.is_ablative();
     } );
 }
References all_items_top(), and item_pocket::is_ablative().
Referenced by item::all_ablative_armor().
all_ablative_armor() [2/2]
std::list< const item * > item_contents::all_ablative_armor () const
Definition at line 1784 of file item_contents.cpp.
 {
     return all_items_top( []( const item_pocket & pocket ) {
         return pocket.is_ablative();
     } );
 }
References all_items_top(), and item_pocket::is_ablative().
all_items_top() [1/6]
std::list< item * > item_contents::all_items_top ()
returns a list of pointers to all top-level items that are not mods
Definition at line 1749 of file item_contents.cpp.
 {
     return all_items_top( []( const item_pocket & pocket ) {
         return pocket.is_standard_type();
     } );
 }
References item_pocket::is_standard_type().
Referenced by all_ablative_armor(), all_items_top(), all_known_contents(), and legacy_front().
all_items_top() [2/6]
std::list< const item * > item_contents::all_items_top () const
returns a list of pointers to all top-level items that are not mods
Definition at line 1756 of file item_contents.cpp.
 {
     return all_items_top( []( const item_pocket & pocket ) {
         return pocket.is_standard_type();
     } );
 }
References all_items_top(), and item_pocket::is_standard_type().
all_items_top() [3/6]
std::list< const item * > item_contents::all_items_top (const std::function< bool(const item_pocket &)> & filter) const
returns a list of pointers to all top-level items from pockets that match the predicate
Definition at line 1703 of file item_contents.cpp.
 {
     std::list<const item *> all_items_internal;
     for( const item_pocket &pocket : contents ) {
         if( filter( pocket ) ) {
             std::list<const item *> contained_items = pocket.all_items_top();
             all_items_internal.splice( all_items_internal.end(), std::move( contained_items ) );
         }
     }
     return all_items_internal;
 }
References contents, and filter.
all_items_top() [4/6]
std::list< item * > item_contents::all_items_top (const std::function< bool(item_pocket &)> & filter)
returns a list of pointers to all top-level items from pockets that match the predicate
Definition at line 1677 of file item_contents.cpp.
 {
     std::list<item *> all_items_internal;
     for( item_pocket &pocket : contents ) {
         if( filter( pocket ) ) {
             std::list<item *> contained_items = pocket.all_items_top();
             all_items_internal.splice( all_items_internal.end(), std::move( contained_items ) );
         }
     }
     return all_items_internal;
 }
References contents, and filter.
Referenced by item::all_items_top(), item::all_items_top_recursive(), item::ammo_remaining(), item::check_for_free_space(), item::contents_info(), item::contents_only_one_type(), item::energy_remaining(), advanced_inventory::fill_lists_with_pane_items(), item::get_free_mod_locations(), item::gun_info(), item::is_dangerous(), item::reload_option::qty(), item::qualities_info(), item::set_owner(), advanced_inventory::start_activity(), item::toolmods(), and npc_trading::transfer_items().
all_items_top() [5/6]
std::list< const item * > item_contents::all_items_top (pocket_type pk_type) const
returns a list of pointers to all top-level items
Definition at line 1742 of file item_contents.cpp.
 {
     return all_items_top( [pk_type]( const item_pocket & pocket ) {
         return pocket.is_type( pk_type );
     } );
 }
References all_items_top(), and item_pocket::is_type().
all_items_top() [6/6]
std::list< item * > item_contents::all_items_top (pocket_type pk_type, bool unloading = false)
returns a list of pointers to all top-level items
if unloading is true it ignores items in pockets that are flagged to not unload
Definition at line 1689 of file item_contents.cpp.
 {
     if( unloading ) {
         return all_items_top( [pk_type]( item_pocket & pocket ) {
             return pocket.is_type( pk_type ) && pocket.settings.is_unloadable();
         } );
     }
     return all_items_top( [pk_type]( item_pocket & pocket ) {
         return pocket.is_type( pk_type );
     } );
 }
References all_items_top(), item_pocket::is_type(), item_pocket::favorite_settings::is_unloadable(), and item_pocket::settings.
all_known_contents() [1/2]
std::list< item * > item_contents::all_known_contents ()
returns a list of pointers to all visible or remembered content items that are not mods
Definition at line 1763 of file item_contents.cpp.
 {
     return all_items_top( []( const item_pocket & pocket ) {
         return pocket.is_standard_type() && pocket.transparent();
     } );
 }
References all_items_top(), item_pocket::is_standard_type(), and item_pocket::transparent().
Referenced by item::all_known_contents().
all_known_contents() [2/2]
std::list< const item * > item_contents::all_known_contents () const
Definition at line 1770 of file item_contents.cpp.
 {
     return all_items_top( []( const item_pocket & pocket ) {
         return pocket.is_standard_type() && pocket.transparent();
     } );
 }
References all_items_top(), item_pocket::is_standard_type(), and item_pocket::transparent().
all_pockets_rigid()
bool item_contents::all_pockets_rigid () const
True if every pocket is rigid or we have no pockets.
Definition at line 2556 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( !pocket.is_type( pocket_type::CONTAINER ) ) {
             continue;
         }
         if( !pocket.rigid() ) {
             return false;
         }
     }
     return true;
 }
References CONTAINER, and contents.
Referenced by item::all_pockets_rigid().
all_pockets_sealed()
bool item_contents::all_pockets_sealed () const
Definition at line 1479 of file item_contents.cpp.
 {
     bool all_sealed = false;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) ) {
             if( !pocket.sealed() ) {
                 return false;
             } else {
                 all_sealed = true;
             }
         }
     }
     return all_sealed;
 }
References CONTAINER, and contents.
Referenced by item::all_pockets_sealed().
allows_speedloader()
bool item_contents::allows_speedloader (const itype_id & speedloader_id) const
Definition at line 1833 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE ) ) {
             return pocket.allows_speedloader( speedloader_id );
         }
     }
     return false;
 }
References contents, and MAGAZINE.
Referenced by item::allows_speedloader().
ammo_capacity()
int item_contents::ammo_capacity (const ammotype & ammo) const
Definition at line 1300 of file item_contents.cpp.
 {
     int ret = 0;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE ) ) {
             ret += pocket.ammo_capacity( ammo );
         }
     }
     return ret;
 }
References contents, MAGAZINE, and cata::hash64_detail::ret.
Referenced by item::ammo_capacity().
ammo_consume()
int item_contents::ammo_consume (int qty, const tripoint & pos, float fuel_efficiency = -1.0)
Definition at line 1241 of file item_contents.cpp.
 {
     int consumed = 0;
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE_WELL ) ) {
             // we are assuming only one magazine per well
             if( pocket.empty() ) {
                 return 0;
             }
             // assuming only one mag
             item &mag = pocket.front();
             const int res = mag.ammo_consume( qty, pos, nullptr );
             if( res && mag.ammo_remaining() == 0 ) {
                 if( mag.has_flag( STATIC( flag_id( "MAG_DESTROY" ) ) ) ) {
                     pocket.remove_item( mag );
                 } else if( mag.has_flag( STATIC( flag_id( "MAG_EJECT" ) ) ) ) {
                     get_map().add_item( pos, mag );
                     pocket.remove_item( mag );
                 }
             }
             qty -= res;
             consumed += res;
         } else if( pocket.is_type( pocket_type::MAGAZINE ) ) {
             if( !pocket.empty() && pocket.front().is_fuel() && fuel_efficiency >= 0 ) {
                 // if using fuel instead of battery, everything is in kJ
                 // charges is going to be the energy needed over the energy in 1 unit of fuel * the efficiency of the generator
                 int charges_used = ceil( static_cast<float>( units::from_kilojoule( static_cast<std::int64_t>
                                          ( qty ) ).value() ) / (
                                              static_cast<float>( pocket.front().fuel_energy().value() ) * fuel_efficiency ) );
                 const int res = pocket.ammo_consume( charges_used );
                 //calculate the ammount of energy generated
                 int energy_generated = res * units::to_kilojoule( pocket.front().fuel_energy() );
                 consumed += energy_generated;
                 qty -= energy_generated;
                 qty = std::max( 0, qty );
             } else {
                 const int res = pocket.ammo_consume( qty );
                 consumed += res;
                 qty -= res;
             }
         }
     }
     return consumed;
 }
References map::add_item(), item::ammo_consume(), item::ammo_remaining(), ceil(), contents, flag_id, units::from_kilojoule(), get_map(), item::has_flag(), MAGAZINE, MAGAZINE_WELL, max(), math_opers::pos(), visitable::remove_item(), STATIC, and units::to_kilojoule().
Referenced by item::ammo_consume(), and item::energy_consume().
ammo_types()
std::set< ammotype > item_contents::ammo_types () const
Definition at line 1311 of file item_contents.cpp.
 {
     std::set<ammotype> ret;
     for( const item_pocket &pocket : contents ) {
         for( const ammotype &ammo : pocket.ammo_types() ) {
             ret.emplace( ammo );
         }
     }
     return ret;
 }
References contents, and cata::hash64_detail::ret.
Referenced by item::ammo_types().
any_pockets_sealed()
bool item_contents::any_pockets_sealed () const
Definition at line 1496 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) ) {
             if( pocket.sealed() ) {
                 return true;
             }
         }
     }
     return false;
 }
References CONTAINER, and contents.
Referenced by item::any_pockets_sealed().
best_pocket()
std::pair< item_location, item_pocket * > item_contents::best_pocket (const item & it, item_location & this_loc, const item * avoid = nullptr, bool allow_sealed = false, bool ignore_settings = false, bool nested = false, bool ignore_rigidity = false)
returns an item_location and pointer to the best pocket that can contain the item @it checks all items contained in every pocket only checks CONTAINER pocket type
Definition at line 893 of file item_contents.cpp.
 {
     // @TODO: this could be made better by doing a plain preliminary volume check.
     // if the total volume of the parent is not sufficient, a child won't have enough either.
     std::pair<item_location, item_pocket *> ret = { this_loc, nullptr };
     std::vector<item_pocket *> valid_pockets;
     for( item_pocket &pocket : contents ) {
         if( pocket.is_forbidden() ) {
             continue;
         }
         if( !pocket.is_type( pocket_type::CONTAINER ) ) {
             // best pocket is for picking stuff up.
             // containers are the only pockets that are available for such
             continue;
         }
         if( !allow_sealed && pocket.sealed() ) {
             // we don't want to unseal a pocket to put something in it automatically
             // that needs to be something a player explicitly does
             continue;
         }
         valid_pockets.emplace_back( &pocket );
         if( !ignore_settings && !pocket.settings.accepts_item( it ) ) {
             // Item forbidden by whitelist / blacklist
             continue;
         }
         if( !pocket.rigid() && (
                 !pocket.settings.get_item_whitelist().empty() ||
                 !pocket.settings.get_category_whitelist().empty() ||
                 pocket.settings.priority() > 0 ) ) {
             ignore_rigidity = true;
         }
         if( ( !ignore_rigidity && nested && !pocket.rigid() ) || !pocket.can_contain( it ).success() ) {
             // non-rigid nested pocket makes no sense, item should also be able to fit in parent.
             continue;
         }
         if( ret.second == nullptr || ret.second->better_pocket( pocket, it, /*nested=*/nested ) ) {
             ret.second = &pocket;
         }
     }
     const bool parent_pkt_selected = !!ret.second;
     for( item_pocket *pocket : valid_pockets ) {
         std::pair<item_location, item_pocket *const> nested_content_pocket =
             pocket->best_pocket_in_contents( this_loc, it, avoid, allow_sealed, ignore_settings );
         if( !nested_content_pocket.second ||
             ( !nested_content_pocket.second->rigid() && pocket->remaining_volume() < it.volume() ) ) {
             // no nested pocket found, or the nested pocket is soft and the parent is full
             continue;
         }
         if( parent_pkt_selected ) {
             if( ret.second->better_pocket( *nested_content_pocket.second, it, true ) ) {
                 // item is whitelisted in nested pocket, prefer that over parent pocket
                 ret = nested_content_pocket;
             }
             continue;
         }
         ret = nested_content_pocket;
     }
     return ret;
 }
References CONTAINER, contents, cata::hash64_detail::ret, and item::volume().
Referenced by item::best_pocket().
best_quality()
int item_contents::best_quality (const quality_id & id) const
returns the best quality of the id that's contained in the item in CONTAINER pockets
Definition at line 2596 of file item_contents.cpp.
 {
     int ret = 0;
     for( const item_pocket &pocket : contents ) {
         ret = std::max( pocket.best_quality( id ), ret );
     }
     return ret;
 }
References contents, max(), and cata::hash64_detail::ret.
Referenced by item::get_quality().
bigger_on_the_inside()
bool item_contents::bigger_on_the_inside (const units::volume & container_volume) const
Definition at line 641 of file item_contents.cpp.
 {
     units::volume min_logical_volume = 0_ml;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) ) {
             if( pocket.rigid() ) {
                 min_logical_volume += pocket.max_contains_volume();
             } else {
                 min_logical_volume += pocket.magazine_well();
             }
         }
     }
     return container_volume <= min_logical_volume;
 }
References CONTAINER, and contents.
Referenced by item::can_contain(), Item_factory::check_definitions(), and item::is_compatible().
cables() [1/2]
std::vector< item * > item_contents::cables ()
Definition at line 1895 of file item_contents.cpp.
 {
     std::vector<item *> cables;
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CABLE ) ) {
             for( item *it : pocket.all_items_top() ) {
                 cables.emplace_back( it );
             }
         }
     }
     return cables;
 }
References item::all_items_top(), CABLE, and contents.
Referenced by item::cables(), and cables().
cables() [2/2]
std::vector< const item * > item_contents::cables () const
Definition at line 1908 of file item_contents.cpp.
 {
     std::vector<const item *> cables;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CABLE ) ) {
             for( const item *it : pocket.all_items_top() ) {
                 // TODO: remove flag check after 0.H
                 if( it->has_flag( STATIC( flag_id( "CABLE_SPOOL" ) ) ) ) {
                     cables.emplace_back( it );
                 }
             }
         }
     }
     return cables;
 }
References item::all_items_top(), CABLE, cables(), contents, flag_id, item::has_flag(), and STATIC.
can_contain() [1/2]
ret_val< void > item_contents::can_contain (const item & it, bool ignore_pkt_settings = true, bool is_pick_up_inv = false, units::volume remaining_parent_volume = 10000000_ml) const
returns whether an item can be physically stored within these item contents.
Fails if all pockets are MOD, CORPSE, SOFTWARE, or MIGRATION type, as they are not physical pockets.
Parameters
it the item being put in
ignore_pkt_settings whether to ignore pocket autoinsert settings
remaining_parent_volume if we are nesting things without concern for rigidity we need to be careful about overfilling pockets this tracks the remaining volume of any parent pockets
Definition at line 1098 of file item_contents.cpp.
 {
     int copies = 1;
     return can_contain( it, copies, ignore_pkt_settings, is_pick_up_inv, remaining_parent_volume );
 }
Referenced by item::add_rain_to_container(), and item::can_contain().
can_contain() [2/2]
ret_val< void > item_contents::can_contain (const item & it, int & copies_remaining, bool ignore_pkt_settings = true, bool is_pick_up_inv = false, units::volume remaining_parent_volume = 10000000_ml) const
Definition at line 1105 of file item_contents.cpp.
 {
     ret_val<void> ret = ret_val<void>::make_failure( _( "is not a container" ) );
     if( copies_remaining <= 0 ) {
         return ret_val<void>::make_success();
     }
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_forbidden() ) {
             continue;
         }
         // Only count container in pickup_inventory_preset.
         if( is_pick_up_inv ) {
             if( !pocket.is_type( pocket_type::CONTAINER ) ) {
                 continue;
             }
         }
         // mod, migration, corpse, and software aren't regular pockets.
         if( !pocket.is_standard_type() ) {
             continue;
         }
         if( !ignore_pkt_settings && !pocket.settings.accepts_item( it ) ) {
             ret = ret_val<void>::make_failure( _( "denied by pocket auto insert settings" ) );
             continue;
         }
         if( !pocket.rigid() && it.volume() > remaining_parent_volume ) {
             continue;
         }
         const ret_val<item_pocket::contain_code> pocket_contain_code = pocket.can_contain( it,
                 copies_remaining );
         if( copies_remaining <= 0 ) {
             return ret_val<void>::make_success();
         }
         ret = ret_val<void>::make_failure( pocket_contain_code.str() );
     }
     return ret;
 }
References _, CONTAINER, contents, ret_val< T >::make_failure(), ret_val< T >::make_success(), cata::hash64_detail::ret, ret_val_common::str(), and item::volume().
can_contain_liquid()
bool item_contents::can_contain_liquid (bool held_or_ground) const
Definition at line 1145 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) &&
             pocket.can_contain_liquid( held_or_ground ) ) {
             return true;
         }
     }
     return false;
 }
References CONTAINER, and contents.
Referenced by item::get_remaining_capacity_for_liquid(), and item::is_watertight_container().
can_contain_rigid() [1/2]
ret_val< void > item_contents::can_contain_rigid (const item & it, bool ignore_pkt_settings = true, bool is_pick_up_inv = false) const
Definition at line 1057 of file item_contents.cpp.
 {
     int copies = 1;
     return can_contain_rigid( it, copies, ignore_pkt_settings, is_pick_up_inv );
 }
Referenced by item::can_contain().
can_contain_rigid() [2/2]
ret_val< void > item_contents::can_contain_rigid (const item & it, int & copies_remaining, bool ignore_pkt_settings = true, bool is_pick_up_inv = false) const
Definition at line 1064 of file item_contents.cpp.
 {
     ret_val<void> ret = ret_val<void>::make_failure( _( "is not a container" ) );
     for( const item_pocket &pocket : contents ) {
         // Only count container in pickup_inventory_preset.
         if( is_pick_up_inv ) {
             if( !pocket.is_type( pocket_type::CONTAINER ) ) {
                 continue;
             }
         }
         if( pocket.is_type( pocket_type::MOD ) ||
             pocket.is_type( pocket_type::CORPSE ) ||
             pocket.is_type( pocket_type::MIGRATION ) ) {
             continue;
         }
         if( !pocket.rigid() ) {
             ret = ret_val<void>::make_failure( _( "is not rigid" ) );
             continue;
         }
         if( !ignore_pkt_settings && !pocket.settings.accepts_item( it ) ) {
             ret = ret_val<void>::make_failure( _( "denied by pocket auto insert settings" ) );
             continue;
         }
         const ret_val<item_pocket::contain_code> pocket_contain_code = pocket.can_contain( it,
                 copies_remaining, false );
         if( copies_remaining <= 0 || pocket_contain_code.success() ) {
             return ret_val<void>::make_success();
         }
         ret = ret_val<void>::make_failure( pocket_contain_code.str() );
     }
     return ret;
 }
References _, CONTAINER, contents, CORPSE, ret_val< T >::make_failure(), ret_val< T >::make_success(), MIGRATION, MOD, cata::hash64_detail::ret, ret_val_common::str(), and ret_val_common::success().
can_reload_with()
bool item_contents::can_reload_with (const item & ammo, bool now) const
returns whether any of the pockets can be reloaded with the specified item.
Parameters
ammo item to be loaded in
now whether the currently contained ammo/magazine should be taken into account
Definition at line 1168 of file item_contents.cpp.
 {
     for( const item_pocket *pocket : get_all_reloadable_pockets() ) {
         if( pocket->can_reload_with( ammo, now ) ) {
             return true;
         }
     }
     return false;
 }
References get_all_reloadable_pockets().
Referenced by item::can_reload_with().
can_unload_liquid()
bool item_contents::can_unload_liquid () const
Definition at line 1179 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) && pocket.can_unload_liquid() ) {
             return true;
         }
     }
     return false;
 }
References CONTAINER, and contents.
Referenced by item::can_unload_liquid().
casings_handle()
void item_contents::casings_handle (const std::function< bool(item &)> & func)
Definition at line 1417 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         pocket.casings_handle( func );
     }
 }
References contents.
Referenced by item::casings_handle().
clear_items()
void item_contents::clear_items ()
Definition at line 1424 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         pocket.clear_items();
     }
 }
References contents.
Referenced by item::clear_items(), handle_problematic_pickup(), link_up_actor::link_extend_cable(), and link_up_actor::remove_extensions().
clear_magazines()
void item_contents::clear_magazines ()
Definition at line 1431 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE ) ) {
             pocket.clear_items();
         }
     }
 }
References contents, and MAGAZINE.
Referenced by item::ammo_unset().
clear_pockets_if()
void item_contents::clear_pockets_if (const std::function< bool(item_pocket const &)> & filter)
Definition at line 1440 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( filter( pocket ) ) {
             pocket.clear_items();
         }
     }
 }
References contents, and filter.
Referenced by link_up_actor::remove_extensions().
combine()
void item_contents::combine (const item_contents & read_input, bool convert = false, bool into_bottom = false, bool restack_charges = true, bool ignore_contents = false)
Definition at line 677 of file item_contents.cpp.
 {
     std::list<item_pocket> mismatched_pockets;
     std::vector<item> uninserted_items;
     size_t pocket_index = 0;
     for( const item &pocket : read_input.additional_pockets ) {
         add_pocket( pocket );
     }
     for( const item_pocket &pocket : read_input.contents ) {
         if( pocket_index < contents.size() ) {
             if( convert ) {
                 if( pocket.is_type( pocket_type::MIGRATION ) ||
                     pocket.is_type( pocket_type::CORPSE ) ||
                     pocket.is_type( pocket_type::MAGAZINE ) ||
                     pocket.is_type( pocket_type::MAGAZINE_WELL ) ||
                     pocket.is_type( pocket_type::SOFTWARE ) ||
                     pocket.is_type( pocket_type::EBOOK ) ) {
                     ++pocket_index;
                     for( const item *it : pocket.all_items_top() ) {
                         insert_item( *it, pocket.get_pocket_data()->type, ignore_contents );
                     }
                     continue;
                 } else if( pocket.is_type( pocket_type::MOD ) ) {
                     // skipping mod type pocket because using combine this way requires mods to come first
                     // and to call update_mod_pockets
                     ++pocket_index;
                     continue;
                 }
             } else {
                 if( pocket.saved_type() == pocket_type::MOD ) {
                     // this is already handled in item_contents::read_mods
                     ++pocket_index;
                     continue;
                 } else if( pocket.saved_type() == pocket_type::MIGRATION ||
                            pocket.saved_type() == pocket_type::CORPSE ) {
                     for( const item *it : pocket.all_items_top() ) {
                         insert_item( *it, pocket.saved_type(), ignore_contents );
                     }
                     ++pocket_index;
                     continue;
                 }
             }
             auto current_pocket_iter = contents.begin();
             std::advance( current_pocket_iter, pocket_index );
             if( !current_pocket_iter->is_type( pocket.saved_type() ) ) {
                 mismatched_pockets.push_back( pocket );
                 continue;
             }
             for( const item *it : pocket.all_items_top() ) {
                 const ret_val<item *> inserted = current_pocket_iter->insert_item( *it,
                                                  into_bottom, restack_charges, ignore_contents );
                 if( !inserted.success() ) {
                     uninserted_items.push_back( *it );
                     debugmsg( "error: item %s cannot fit into pocket while loading: %s",
                               it->typeId().str(), inserted.str() );
                 }
             }
             if( pocket.saved_sealed() ) {
                 current_pocket_iter->seal();
             }
             current_pocket_iter->settings = pocket.settings;
         } else {
             for( const item *it : pocket.all_items_top() ) {
                 uninserted_items.push_back( *it );
             }
         }
         ++pocket_index;
     }
     for( const item_pocket &pocket : mismatched_pockets ) {
         for( const item *it : pocket.all_items_top() ) {
             const ret_val<item *> inserted = insert_item( *it, pocket.saved_type(), ignore_contents );
             if( !inserted.success() ) {
                 uninserted_items.push_back( *it );
                 debugmsg( "error: item %s cannot fit into any pocket while loading: %s",
                           it->typeId().str(), inserted.str() );
             }
         }
     }
     for( const item &uninserted_item : uninserted_items ) {
         insert_item( uninserted_item, pocket_type::MIGRATION, ignore_contents );
     }
 }
References add_pocket(), additional_pockets, item::all_items_top(), contents, cata::convert(), CORPSE, debugmsg, EBOOK, insert_item(), MAGAZINE, MAGAZINE_WELL, MIGRATION, MOD, SOFTWARE, ret_val_common::str(), ret_val_common::success(), and item::type.
Referenced by item::combine().
contained_where()
item_pocket * item_contents::contained_where (const item & contained)
Definition at line 955 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.has_item( contained ) ) {
             return &pocket;
         }
     }
     return nullptr;
 }
References contents.
Referenced by item::contained_where().
contains_no_solids()
bool item_contents::contains_no_solids () const
Definition at line 1156 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) &&
             pocket.contains_phase( phase_id::SOLID ) ) {
             return false;
         }
     }
     return true;
 }
References CONTAINER, contents, and SOLID.
Referenced by item::contains_no_solids().
deserialize()
void item_contents::deserialize (const JsonObject & data)
Definition at line 237 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     data.read( "contents", contents );
     data.read( "additional_pockets", additional_pockets );
 }
References additional_pockets, JsonObject::allow_omitted_members(), contents, and JsonObject::read().
ebooks() [1/2]
std::vector< item * > item_contents::ebooks ()
Definition at line 1869 of file item_contents.cpp.
 {
     std::vector<item *> ebooks;
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::EBOOK ) ) {
             for( item *it : pocket.all_items_top() ) {
                 ebooks.emplace_back( it );
             }
         }
     }
     return ebooks;
 }
References item::all_items_top(), contents, and EBOOK.
Referenced by inventory_selector::add_contained_ebooks(), item::ebooks(), ebooks(), and Character::get_recipes_from_ebooks().
ebooks() [2/2]
std::vector< const item * > item_contents::ebooks () const
Definition at line 1882 of file item_contents.cpp.
 {
     std::vector<const item *> ebooks;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::EBOOK ) ) {
             for( const item *it : pocket.all_items_top() ) {
                 ebooks.emplace_back( it );
             }
         }
     }
     return ebooks;
 }
References item::all_items_top(), contents, EBOOK, and ebooks().
empty()
bool item_contents::empty () const
Definition at line 586 of file item_contents.cpp.
 {
     if( contents.empty() ) {
         return true;
     }
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MOD ) ) {
             // item mods aren't really contents per se
             continue;
         }
         if( !pocket.empty() ) {
             return false;
         }
     }
     return true;
 }
References contents, and MOD.
Referenced by item::ammo_data(), item::can_combine(), item::contents_info(), item::empty(), first_ammo(), item::is_bucket_nonempty(), item::is_collapsed(), item::is_container_empty(), legacy_front(), item::loaded_ammo(), serialize(), and stacks_with().
empty_container()
bool item_contents::empty_container () const
Definition at line 603 of file item_contents.cpp.
 {
     if( contents.empty() ) {
         return true;
     }
     for( const item_pocket &pocket : contents ) {
         if( !pocket.is_type( pocket_type::CONTAINER ) ) {
             continue;
         }
         if( !pocket.empty() ) {
             return false;
         }
     }
     return true;
 }
References CONTAINER, and contents.
Referenced by item::empty_container(), item::get_quality(), and item::get_quality_nonrecursive().
empty_with_no_mods()
bool item_contents::empty_with_no_mods () const
Definition at line 578 of file item_contents.cpp.
 {
     return contents.empty() ||
     std::all_of( contents.begin(), contents.end(), []( const item_pocket & p ) {
         return p.is_default_state();
     } );
 }
References contents.
Referenced by item::same_for_rle().
favorite_settings_menu()
void item_contents::favorite_settings_menu (item * i)
Open a menu for the player to set pocket favorite settings for the pockets in this item_contents.
Definition at line 2689 of file item_contents.cpp.
 {
     std::vector<item *> to_organize;
     to_organize.push_back( i );
     pocket_management_menu( remove_color_tags( i->display_name() ), to_organize );
 }
References item::display_name(), pocket_management_menu(), and remove_color_tags().
Referenced by item::favorite_settings_menu().
find_pocket_for() [1/2]
ret_val< item_pocket * > item_contents::find_pocket_for (const item & it, pocket_type pk_type = pocket_type::CONTAINER) private
Definition at line 823 of file item_contents.cpp.
 {
     return item_contents_helper::find_pocket_for( *this, it, pk_type );
 }
References item_contents::item_contents_helper::find_pocket_for().
Referenced by insert_cost(), and insert_item().
find_pocket_for() [2/2]
ret_val< const item_pocket * > item_contents::find_pocket_for (const item & it, pocket_type pk_type = pocket_type::CONTAINER) const private
Definition at line 829 of file item_contents.cpp.
 {
     return item_contents_helper::find_pocket_for( *this, it, pk_type );
 }
References item_contents::item_contents_helper::find_pocket_for().
first_ammo() [1/2]
item & item_contents::first_ammo ()
Definition at line 1322 of file item_contents.cpp.
 {
     if( empty() ) {
         debugmsg( "Error: Contents has no pockets" );
         return null_item_reference();
     }
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE_WELL ) ) {
             return pocket.front().first_ammo();
         }
         if( !pocket.is_type( pocket_type::MAGAZINE ) || pocket.empty() ) {
             continue;
         }
         if( pocket.front().has_flag( json_flag_CASING ) ) {
             for( item *i : pocket.all_items_top() ) {
                 if( !i->has_flag( json_flag_CASING ) ) {
                     return *i;
                 }
             }
             continue;
         }
         return pocket.front();
     }
     return null_item_reference();
 }
References item::all_items_top(), contents, debugmsg, empty(), json_flag_CASING, MAGAZINE, MAGAZINE_WELL, and null_item_reference().
Referenced by item::ammo_data(), item::can_reload_with(), item::first_ammo(), and item::loaded_ammo().
first_ammo() [2/2]
const item & item_contents::first_ammo () const
Definition at line 1348 of file item_contents.cpp.
 {
     if( empty() ) {
         debugmsg( "Error: Contents has no pockets" );
         return null_item_reference();
     }
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE_WELL ) ) {
             return pocket.front().first_ammo();
         }
         if( !pocket.is_type( pocket_type::MAGAZINE ) || pocket.empty() ) {
             continue;
         }
         if( pocket.front().has_flag( json_flag_CASING ) ) {
             for( const item *i : pocket.all_items_top() ) {
                 if( !i->has_flag( json_flag_CASING ) ) {
                     return *i;
                 }
             }
             continue;
         }
         return pocket.front();
     }
     return null_item_reference();
 }
References item::all_items_top(), contents, debugmsg, empty(), json_flag_CASING, MAGAZINE, MAGAZINE_WELL, and null_item_reference().
first_item() [1/2]
item & item_contents::first_item ()
Definition at line 1597 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.empty() || !pocket.is_type( pocket_type::CONTAINER ) ) {
             continue;
         }
         // the first item we come to is the only one.
         return pocket.front();
     }
     return null_item_reference();
 }
References CONTAINER, contents, and null_item_reference().
Referenced by item::add_automatic_whitelist(), only_item(), and item::this_or_single_content().
first_item() [2/2]
const item & item_contents::first_item () const
Definition at line 1618 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.empty() || !( pocket.is_type( pocket_type::CONTAINER ) ||
                                  pocket.is_type( pocket_type::SOFTWARE ) ) ) {
             continue;
         }
         // the first item we come to is the only one.
         return pocket.front();
     }
     return null_item_reference();
 }
References CONTAINER, contents, null_item_reference(), and SOFTWARE.
force_insert_item()
void item_contents::force_insert_item (const item & it, pocket_type pk_type)
Definition at line 882 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pk_type ) ) {
             pocket.add( it );
             return;
         }
     }
     debugmsg( "ERROR: Could not insert item %s as contents does not have pocket type", it.tname() );
 }
References contents, debugmsg, and item::tname().
Referenced by item::force_insert_item().
full()
bool item_contents::full (bool allow_bucket) const
Definition at line 619 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER )
             && !pocket.full( allow_bucket ) ) {
             return false;
         }
     }
     return true;
 }
References CONTAINER, and contents.
Referenced by item::is_container_full().
get_added_pocket()
const item_pocket * item_contents::get_added_pocket (int index) const
Definition at line 2173 of file item_contents.cpp.
 {
     if( additional_pockets.empty() || index >= static_cast<int>( additional_pockets.size() ) ) {
         return nullptr;
     }
     // start at the first pocket
     auto rit = contents.rbegin();
     // find the pockets to remove from the item
     for( int i = additional_pockets.size() - 1; i >= index; --i ) {
         // move the iterator past all the pockets we aren't removing
         std::advance( rit, additional_pockets[i].get_all_contained_pockets().size() );
     }
     // at this point reversed past the pockets we want to get rid of so now start going forward
     auto it = std::next( rit ).base();
     return &*it;
 }
References additional_pockets, contents, get_all_contained_pockets(), and size().
get_added_pockets()
std::vector< const item * > item_contents::get_added_pockets () const
Definition at line 2107 of file item_contents.cpp.
 {
     std::vector<const item *> items_added;
     items_added.reserve( additional_pockets.size() );
     for( const item &it : additional_pockets ) {
         items_added.push_back( &it );
     }
     return items_added;
 }
References additional_pockets.
Referenced by activity_on_turn_move_loot(), outfit::holster_opts(), anonymous_namespace{item_tname.cpp}::mods(), item::update_modified_pockets(), and molle_detach_actor::use().
get_additional_pocket_encumbrance()
int item_contents::get_additional_pocket_encumbrance (float mod) const
Definition at line 2200 of file item_contents.cpp.
 {
     return additional_pockets_volume * mod / 250_ml;
 }
References additional_pockets_volume.
Referenced by item::get_encumber().
get_additional_space_used()
int item_contents::get_additional_space_used () const
Definition at line 2205 of file item_contents.cpp.
 {
     return additional_pockets_space_used;
 }
References additional_pockets_space_used.
Referenced by attach_molle_inventory_preset::get_denial(), Item_modifier::modify(), and game_menus::inv::molle_attach().
get_additional_volume()
units::volume item_contents::get_additional_volume () const
Definition at line 2219 of file item_contents.cpp.
 {
     units::volume ret = 0_ml;
     for( const item &it : additional_pockets ) {
         ret += it.volume( false, true );
     }
     return ret;
 }
References additional_pockets, cata::hash64_detail::ret, and item::volume().
Referenced by item::volume().
get_additional_weight()
units::mass item_contents::get_additional_weight () const
Definition at line 2210 of file item_contents.cpp.
 {
     units::mass ret = 0_kilogram;
     for( const item &it : additional_pockets ) {
         ret += it.weight( false );
     }
     return ret;
 }
References additional_pockets, cata::hash64_detail::ret, and item::weight().
Referenced by item::weight().
get_all_ablative_pockets() [1/2]
std::vector< item_pocket * > item_contents::get_all_ablative_pockets ()
Definition at line 2100 of file item_contents.cpp.
 {
     return get_pockets( []( item_pocket const & pocket ) {
         return pocket.is_ablative();
     } );
 }
References get_pockets(), and item_pocket::is_ablative().
get_all_ablative_pockets() [2/2]
std::vector< const item_pocket * > item_contents::get_all_ablative_pockets () const
Definition at line 2093 of file item_contents.cpp.
 {
     return get_pockets( []( item_pocket const & pocket ) {
         return pocket.is_ablative();
     } );
 }
References get_pockets(), and item_pocket::is_ablative().
Referenced by item::get_all_ablative_pockets(), item::get_encumber(), item::is_bp_rigid(), item::is_rigid(), and serialize().
get_all_contained_pockets() [1/2]
std::vector< item_pocket * > item_contents::get_all_contained_pockets ()
Definition at line 2072 of file item_contents.cpp.
 {
     return get_pockets( []( item_pocket const & pocket ) {
         return pocket.is_type( pocket_type::CONTAINER );
     } );
 }
References CONTAINER, get_pockets(), and item_pocket::is_type().
get_all_contained_pockets() [2/2]
std::vector< const item_pocket * > item_contents::get_all_contained_pockets () const
Definition at line 2065 of file item_contents.cpp.
 {
     return get_pockets( []( item_pocket const & pocket ) {
         return pocket.is_type( pocket_type::CONTAINER );
     } );
 }
References CONTAINER, get_pockets(), and item_pocket::is_type().
Referenced by item::can_contain(), get_added_pocket(), item::get_all_contained_pockets(), get_contents_volume_with_tweaks(), item::get_encumber(), get_nested_content_volume_recursive(), has_unrestricted_pockets(), is_single_restricted_container(), item::randomize_rot(), remove_pocket(), and item::update_inherited_flags().
get_all_reloadable_pockets()
std::vector< const item_pocket * > item_contents::get_all_reloadable_pockets () const
Definition at line 2228 of file item_contents.cpp.
 {
     std::vector<const item_pocket *> pockets;
     for( const item_pocket &pocket : contents ) {
         if( ( pocket.is_type( pocket_type::CONTAINER ) && pocket.watertight() ) ||
             pocket.is_type( pocket_type::MAGAZINE ) ||
             pocket.is_type( pocket_type::MAGAZINE_WELL ) ) {
             pockets.push_back( &pocket );
         }
     }
     return pockets;
 }
References CONTAINER, contents, MAGAZINE, and MAGAZINE_WELL.
Referenced by can_reload_with(), and item::is_reloadable().
get_all_standard_pockets() [1/2]
std::vector< item_pocket * > item_contents::get_all_standard_pockets ()
Definition at line 2086 of file item_contents.cpp.
 {
     return get_pockets( []( item_pocket const & pocket ) {
         return pocket.is_standard_type();
     } );
 }
References get_pockets(), and item_pocket::is_standard_type().
get_all_standard_pockets() [2/2]
std::vector< const item_pocket * > item_contents::get_all_standard_pockets () const
Definition at line 2079 of file item_contents.cpp.
 {
     return get_pockets( []( item_pocket const & pocket ) {
         return pocket.is_standard_type();
     } );
 }
References get_pockets(), and item_pocket::is_standard_type().
Referenced by item::get_all_standard_pockets(), get_content_newness(), and item::item().
get_content_newness()
content_newness item_contents::get_content_newness (const std::set< itype_id > & read_items) const
don't check top level item, do check its pockets, do check all nested
Definition at line 1716 of file item_contents.cpp.
 {
     content_newness ret = content_newness::SEEN;
     for( const item_pocket *pocket : get_all_standard_pockets() ) {
         // taking transparent from item_contents::all_known_contents()
         if( !pocket->transparent() ) {
             ret = content_newness::MIGHT_BE_HIDDEN;
             continue;
         }
         for( const item *itm : pocket->all_items_top() ) {
             if( !read_items.count( itm->typeId() ) ) {
                 return content_newness::NEW;
             }
             switch( itm->get_contents().get_content_newness( read_items ) ) {
                 case content_newness::NEW:
                     return content_newness::NEW;
                 case content_newness::MIGHT_BE_HIDDEN:
                     ret = content_newness::MIGHT_BE_HIDDEN;
                 case content_newness::SEEN:
                     break;
             }
         }
     }
     return ret;
 }
References item::all_items_top(), get_all_standard_pockets(), MIGHT_BE_HIDDEN, NEW, cata::hash64_detail::ret, and SEEN.
Referenced by check_items_newness().
get_contents_volume_with_tweaks()
units::volume item_contents::get_contents_volume_with_tweaks (const std::map< const item *, int > & without) const
Definition at line 2428 of file item_contents.cpp.
 {
     units::volume ret = 0_ml;
     for( const item_pocket *pocket : get_all_contained_pockets() ) {
         if( !pocket->empty() && !pocket->contains_phase( phase_id::SOLID ) ) {
             const item *it = &pocket->front();
             auto stack = without.find( it );
             if( ( stack == without.end() ) || ( stack->second != it->charges ) ) {
                 ret += pocket->volume_capacity();
             }
         } else {
             for( const item *i : pocket->all_items_top() ) {
                 if( i->count_by_charges() ) {
                     ret += i->volume() - i->get_selected_stack_volume( without );
                 } else if( !without.count( i ) ) {
                     ret += i->volume();
                     ret -= i->get_nested_content_volume_recursive( without );
                 }
             }
         }
     }
     return ret;
 }
References item::all_items_top(), item::charges, get_all_contained_pockets(), cata::hash64_detail::ret, and SOLID.
Referenced by item::get_contents_volume_with_tweaks().
get_item_with() [1/2]
item* item_contents::get_item_with (const std::function< bool(const item &)> & filter)
Referenced by item::add_rain_to_container(), and item::get_item_with().
get_item_with() [2/2]
const item* item_contents::get_item_with (const std::function< bool(const item &)> & filter) const
get_nested_content_volume_recursive()
units::volume item_contents::get_nested_content_volume_recursive (const std::map< const item *, int > & without) const
Definition at line 2455 of file item_contents.cpp.
 {
     units::volume ret = 0_ml;
     for( const item_pocket *pocket : get_all_contained_pockets() ) {
         if( pocket->rigid() && !pocket->empty() && !pocket->contains_phase( phase_id::SOLID ) ) {
             const item *it = &pocket->front();
             auto stack = without.find( it );
             if( ( stack != without.end() ) && ( stack->second == it->charges ) ) {
                 ret += pocket->volume_capacity();
             }
         } else {
             for( const item *i : pocket->all_items_top() ) {
                 if( i->count_by_charges() ) {
                     ret += i->get_selected_stack_volume( without );
                 } else if( without.count( i ) ) {
                     ret += i->volume();
                 } else {
                     ret += i->get_nested_content_volume_recursive( without );
                 }
             }
             if( pocket->rigid() ) {
                 ret += pocket->remaining_volume();
             }
         }
     }
     return ret;
 }
References item::all_items_top(), item::charges, get_all_contained_pockets(), cata::hash64_detail::ret, and SOLID.
Referenced by item::get_nested_content_volume_recursive().
get_pockets() [1/2]
std::vector< item_pocket * > item_contents::get_pockets (std::function< bool(item_pocket const &)> const & filter)
Definition at line 2052 of file item_contents.cpp.
 {
     std::vector<item_pocket *> pockets;
     for( item_pocket &pocket : contents ) {
         if( filter( pocket ) ) {
             pockets.push_back( &pocket );
         }
     }
     return pockets;
 }
References contents, and filter.
get_pockets() [2/2]
std::vector< const item_pocket * > item_contents::get_pockets (std::function< bool(item_pocket const &)> const & filter) const
Definition at line 2039 of file item_contents.cpp.
 {
     std::vector<const item_pocket *> pockets;
     for( const item_pocket &pocket : contents ) {
         if( filter( pocket ) ) {
             pockets.push_back( &pocket );
         }
     }
     return pockets;
 }
References contents, and filter.
Referenced by item::aggregated_contents(), get_all_ablative_pockets(), get_all_contained_pockets(), get_all_standard_pockets(), item::is_collapsed(), and item::item().
get_total_holster_volume()
units::volume item_contents::get_total_holster_volume () const
Definition at line 2275 of file item_contents.cpp.
 {
     units::volume holster_volume = 0_ml;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) && pocket.is_holster() ) {
             holster_volume += pocket.volume_capacity();
         }
     }
     return holster_volume;
 }
References CONTAINER, and contents.
Referenced by item::get_total_holster_volume().
get_total_holster_weight()
units::mass item_contents::get_total_holster_weight () const
Definition at line 2297 of file item_contents.cpp.
 {
     units::mass holster_weight = units::mass();
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) && pocket.is_holster() ) {
             holster_weight += pocket.weight_capacity();
         }
     }
     return holster_weight;
 }
References CONTAINER, and contents.
Referenced by item::get_total_holster_weight().
get_total_holsters()
int item_contents::get_total_holsters () const
Definition at line 2253 of file item_contents.cpp.
 {
     int holsters = 0;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) && pocket.is_holster() ) {
             holsters++;
         }
     }
     return holsters;
 }
References CONTAINER, and contents.
Referenced by item::get_total_holsters().
get_used_holster_volume()
units::volume item_contents::get_used_holster_volume () const
Definition at line 2264 of file item_contents.cpp.
 {
     units::volume holster_volume = 0_ml;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) && pocket.holster_full() ) {
             holster_volume += pocket.volume_capacity();
         }
     }
     return holster_volume;
 }
References CONTAINER, and contents.
Referenced by item::get_used_holster_volume().
get_used_holster_weight()
units::mass item_contents::get_used_holster_weight () const
Definition at line 2286 of file item_contents.cpp.
 {
     units::mass holster_weight = units::mass();
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) && pocket.is_holster() ) {
             holster_weight += pocket.contains_weight();
         }
     }
     return holster_weight;
 }
References CONTAINER, and contents.
Referenced by item::get_used_holster_weight().
get_used_holsters()
int item_contents::get_used_holsters () const
Definition at line 2242 of file item_contents.cpp.
 {
     int holsters = 0;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) && pocket.holster_full() ) {
             holsters++;
         }
     }
     return holsters;
 }
References CONTAINER, and contents.
Referenced by item::get_used_holsters().
gunmods() [1/2]
std::vector< item * > item_contents::gunmods ()
gets all gunmods in the item
Definition at line 1809 of file item_contents.cpp.
 {
     std::vector<item *> mods;
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MOD ) ) {
             std::vector<item *> internal_mods{ pocket.gunmods() };
             mods.insert( mods.end(), internal_mods.begin(), internal_mods.end() );
         }
     }
     return mods;
 }
References contents, MOD, and mods().
Referenced by item::gunmods().
gunmods() [2/2]
std::vector< const item * > item_contents::gunmods () const
gets all gunmods in the item
Definition at line 1821 of file item_contents.cpp.
 {
     std::vector<const item *> mods;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MOD ) ) {
             std::vector<const item *> internal_mods{ pocket.gunmods() };
             mods.insert( mods.end(), internal_mods.begin(), internal_mods.end() );
         }
     }
     return mods;
 }
References contents, MOD, and mods().
handle_liquid_or_spill()
void item_contents::handle_liquid_or_spill (Character & guy, const item * avoid = nullptr)
Definition at line 1408 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) ) {
             pocket.handle_liquid_or_spill( guy, avoid );
         }
     }
 }
References CONTAINER, and contents.
Referenced by item::handle_liquid_or_spill(), and item::spill_contents().
has_additional_pockets()
bool item_contents::has_additional_pockets () const
Definition at line 2194 of file item_contents.cpp.
 {
     // if there are additional pockets return true
     return !additional_pockets.empty();
 }
References additional_pockets.
Referenced by item::get_layer(), anonymous_namespace{item_tname.cpp}::mods(), item::volume(), and item::weight().
has_any_with()
bool item_contents::has_any_with (const std::function< bool(const item &)> & filter, pocket_type pk_type) const
Definition at line 1530 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( !pocket.is_type( pk_type ) ) {
             continue;
         }
         if( pocket.has_any_with( filter ) ) {
             return true;
         }
     }
     return false;
 }
References contents, and filter.
Referenced by item::has_any_with(), item::is_ammo_container(), item::qualities_info(), and craft_command::safe_to_unload_comp().
has_pocket_type()
bool item_contents::has_pocket_type (pocket_type pk_type) const
Definition at line 1509 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pk_type ) ) {
             return true;
         }
     }
     return false;
 }
References contents.
Referenced by item::ammo_capacity(), item::has_pocket_type(), item::is_container(), item::is_ebook_storage(), item::is_magazine(), item::is_software_storage(), item::magazine_integral(), and item::uses_magazine().
has_unrestricted_pockets()
bool item_contents::has_unrestricted_pockets () const
Definition at line 1519 of file item_contents.cpp.
 {
     int restricted_pockets_qty = 0;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_restricted() ) {
             restricted_pockets_qty++;
         }
     }
     return restricted_pockets_qty < static_cast <int>( get_all_contained_pockets().size() );
 }
References contents, get_all_contained_pockets(), and size().
Referenced by item::has_unrestricted_pockets().
heat_up()
void item_contents::heat_up ()
Definition at line 1231 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( !pocket.is_type( pocket_type::CONTAINER ) ) {
             continue;
         }
         pocket.heat_up();
     }
 }
References CONTAINER, and contents.
Referenced by item::burn().
info()
void item_contents::info (std::vector< iteminfo > & info, const iteminfo_query * parts) const
Definition at line 2612 of file item_contents.cpp.
 {
     int pocket_number = 1;
     std::vector<iteminfo> contents_info;
     std::vector<item_pocket> found_pockets;
     std::map<int, int> pocket_num; // index, amount
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) ) {
             bool found = false;
             int idx = 0;
             for( const item_pocket &found_pocket : found_pockets ) {
                 if( found_pocket == pocket ) {
                     found = true;
                     pocket_num[idx]++;
                 }
                 idx++;
             }
             if( !found ) {
                 found_pockets.push_back( pocket );
                 pocket_num[idx]++;
             }
             pocket.contents_info( contents_info, pocket_number++, contents.size() != 1 );
         }
     }
     if( parts->test( iteminfo_parts::DESCRIPTION_POCKETS ) ) {
         // start by saying what items are attached to this directly
         if( !additional_pockets.empty() ) {
             insert_separation_line( info );
             info.emplace_back( "CONTAINER", _( "<bold>This item incorporates</bold>:" ) );
             for( const item &it : additional_pockets ) {
                 info.emplace_back( "CONTAINER", string_format( _( "%s." ),
                                    it.display_name() ) );
             }
             info.back().bNewLine = true;
         }
         // If multiple pockets and/or multiple kinds of pocket, show total capacity section
         units::volume capacity = total_container_capacity();
         units::mass weight = total_container_weight_capacity();
         if( ( found_pockets.size() > 1 || pocket_num[0] > 1 ) && capacity > 0_ml && weight > 0_gram ) {
             insert_separation_line( info );
             info.emplace_back( "CONTAINER", _( "<bold>Total capacity</bold>:" ) );
             info.push_back( vol_to_info( "CONTAINER", _( "Volume: " ), capacity, 2, false ) );
             info.push_back( weight_to_info( "CONTAINER", _( "  Weight: " ), weight,
                                             2, false ) );
             info.back().bNewLine = true;
         }
         int idx = 0;
         for( const item_pocket &pocket : found_pockets ) {
             if( pocket.is_forbidden() ) {
                 continue;
             }
             insert_separation_line( info );
             // If there are multiple similar pockets, show their capacity as a set
             if( pocket_num[idx] > 1 ) {
                 info.emplace_back( "DESCRIPTION", string_format( _( "<bold>%d pockets</bold> with capacity:" ),
                                    pocket_num[idx] ) );
             } else {
                 // If this is the only pocket the item has, label it "Total capacity"
                 // Otherwise, give it a generic "Pocket" heading (is one of several pockets)
                 bool only_one_pocket = ( found_pockets.size() == 1 && pocket_num[0] == 1 );
                 if( only_one_pocket ) {
                     info.emplace_back( "DESCRIPTION", _( "<bold>Total capacity</bold>:" ) );
                 } else {
                     info.emplace_back( "DESCRIPTION", _( "<bold>Pocket</bold> with capacity:" ) );
                 }
             }
             idx++;
             pocket.general_info( info, idx, false );
         }
     }
     if( parts->test( iteminfo_parts::DESCRIPTION_CONTENTS ) ) {
         info.insert( info.end(), contents_info.begin(), contents_info.end() );
     }
 }
References _, additional_pockets, CONTAINER, contents, DESCRIPTION_CONTENTS, DESCRIPTION_POCKETS, item::display_name(), insert_separation_line(), string_format(), iteminfo_query::test(), total_container_capacity(), total_container_weight_capacity(), vol_to_info(), and weight_to_info().
Referenced by item::info().
insert_cost()
int item_contents::insert_cost (const item & it) const
Definition at line 846 of file item_contents.cpp.
 {
     ret_val<const item_pocket *> pocket = find_pocket_for( it, pocket_type::CONTAINER );
     if( pocket.success() ) {
         return pocket.value()->moves();
     } else {
         return -1;
     }
 }
References CONTAINER, find_pocket_for(), ret_val_common::success(), and ret_val< T >::value().
Referenced by item::insert_cost().
insert_item()
ret_val< item * > item_contents::insert_item (const item & it, pocket_type pk_type, bool ignore_contents = false, bool unseal_pockets = false)
Attempts to insert an item into these item contents, stipulating that it must go into a pocket of the given type.
Fails if the contents have no pocket with that type.
With CONTAINER, MAGAZINE, or MAGAZINE_WELL pocket types, items must fit the pocket's volume, length, weight, ammo type, and all other physical restrictions. This is synonymous with the success of item_contents::can_contain with that item. If ignore_contents is true, will disregard other pocket contents for these checks.
For the MOD, CORPSE, SOFTWARE, CABLE, and MIGRATION pocket types, if contents have such a pocket, items will be successfully inserted without regard to volume, length, or any other restrictions, since these pockets are not considered to be normal "containers".
Definition at line 856 of file item_contents.cpp.
 {
     if( pk_type == pocket_type::LAST ) {
         // LAST is invalid, so we assume it will be a regular container
         pk_type = pocket_type::CONTAINER;
     }
     ret_val<item_pocket *> pocket = find_pocket_for( it, pk_type );
     if( !pocket.success() ) {
         return ret_val<item *>::make_failure( nullptr, pocket.str() );
     }
     if( pocket.value()->is_forbidden() ) {
         return ret_val<item *>::make_failure( nullptr, _( "Can't store anything in this." ) );
     }
     ret_val<item *> inserted = pocket.value()->insert_item( it, false, true, ignore_contents );
     if( inserted.success() ) {
         if( unseal_pockets ) {
             pocket.value()->unseal();
         }
         return inserted;
     }
     return ret_val<item *>::make_failure( nullptr, inserted.str() );
 }
References _, CONTAINER, find_pocket_for(), LAST, ret_val< T >::make_failure(), ret_val_common::str(), ret_val_common::success(), and ret_val< T >::value().
Referenced by combine(), item::put_in(), and read_mods().
is_compatible()
ret_val< void > item_contents::is_compatible (const item & it) const
returns whether any of the pockets contained is compatible with the specified item.
Does not check if the item actually fits volume/weight wise Ignores mod, migration, corpse pockets
Parameters
it the item being put in
Definition at line 1040 of file item_contents.cpp.
 {
     ret_val<void> ret = ret_val<void>::make_failure( _( "is not a container" ) );
     for( const item_pocket &pocket : contents ) {
         // mod, migration, corpse, and software aren't regular pockets.
         if( !pocket.is_standard_type() ) {
             continue;
         }
         const ret_val<item_pocket::contain_code> pocket_contain_code = pocket.is_compatible( it );
         if( pocket_contain_code.success() ) {
             return ret_val<void>::make_success();
         }
         ret = ret_val<void>::make_failure( pocket_contain_code.str() );
     }
     return ret;
 }
References _, contents, ret_val< T >::make_failure(), ret_val< T >::make_success(), cata::hash64_detail::ret, ret_val_common::str(), and ret_val_common::success().
Referenced by item::is_compatible().
is_funnel_container()
bool item_contents::is_funnel_container (units::volume & bigger_than) const
Definition at line 1569 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) ) {
             if( pocket.is_funnel_container( bigger_than ) ) {
                 return true;
             }
         }
     }
     return false;
 }
References CONTAINER, and contents.
Referenced by item::is_funnel_container().
is_magazine_full()
bool item_contents::is_magazine_full () const
Definition at line 630 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE )
             && pocket.full( false ) ) {
             return true;
         }
     }
     return false;
 }
References contents, and MAGAZINE.
Referenced by item::is_magazine_full().
is_restricted_container()
bool item_contents::is_restricted_container () const
Definition at line 1581 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_restricted() ) {
             return true;
         }
     }
     return false;
 }
References contents.
Referenced by item::is_container_with_restriction().
is_single_restricted_container()
bool item_contents::is_single_restricted_container () const
Definition at line 1591 of file item_contents.cpp.
 {
     std::vector<const item_pocket *> const contained_pockets = get_all_contained_pockets();
     return contained_pockets.size() == 1 && contained_pockets[0]->is_restricted();
 }
References get_all_contained_pockets().
Referenced by item::is_single_container_with_restriction().
item_has_uses_recursive()
bool item_contents::item_has_uses_recursive () const
Definition at line 87 of file item_action.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) &&
             pocket.item_has_uses_recursive() ) {
             return true;
         }
     }
     return false;
 }
References CONTAINER, and contents.
Referenced by item::item_has_uses_recursive().
item_length_modifier()
units::length item_contents::item_length_modifier () const
Definition at line 2587 of file item_contents.cpp.
 {
     units::length total_length = 0_mm;
     for( const item_pocket &pocket : contents ) {
         total_length = std::max( pocket.item_length_modifier(), total_length );
     }
     return total_length;
 }
References contents, and max().
Referenced by item::length().
item_size_modifier()
units::volume item_contents::item_size_modifier () const
Definition at line 2569 of file item_contents.cpp.
 {
     units::volume total_vol = 0_ml;
     for( const item_pocket &pocket : contents ) {
         total_vol += pocket.item_size_modifier();
     }
     return total_vol;
 }
References contents.
Referenced by item::volume().
item_weight_modifier()
units::mass item_contents::item_weight_modifier () const
Definition at line 2578 of file item_contents.cpp.
 {
     units::mass total_mass = 0_gram;
     for( const item_pocket &pocket : contents ) {
         total_mass += pocket.item_weight_modifier();
     }
     return total_mass;
 }
References contents.
Referenced by item::weight().
leak()
void item_contents::leak (map & here, Character * carrier, const tripoint & pos, item_pocket * pocke = nullptr)
Definition at line 2507 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) ) {
             pocket.leak( here, carrier, pos, pocke );
         }
     }
 }
References CONTAINER, contents, and math_opers::pos().
Referenced by item::leak().
legacy_front() [1/2]
item & item_contents::legacy_front ()
This function is to aid migration to using nested containers.
The call sites of this function need to be updated to search the pockets of the item, or not assume there is only one pocket or item.
Definition at line 1791 of file item_contents.cpp.
 {
     if( empty() ) {
         debugmsg( "naively asked for first content item and will get a nullptr" );
         return null_item_reference();
     }
     return *all_items_top().front();
 }
References all_items_top(), debugmsg, empty(), and null_item_reference().
Referenced by item::legacy_front().
legacy_front() [2/2]
const item & item_contents::legacy_front () const
Definition at line 1800 of file item_contents.cpp.
 {
     if( empty() ) {
         debugmsg( "naively asked for first content item and will get a nullptr" );
         return null_item_reference();
     }
     return *all_items_top().front();
 }
References all_items_top(), debugmsg, empty(), and null_item_reference().
magazine_compatible()
std::set< itype_id > item_contents::magazine_compatible () const
Definition at line 1992 of file item_contents.cpp.
 {
     std::set<itype_id> ret;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE_WELL ) ) {
             for( const itype_id &id : pocket.item_type_restrictions() ) {
                 if( item_is_blacklisted( id ) ) {
                     continue;
                 }
                 ret.emplace( id );
             }
         }
     }
     return ret;
 }
References contents, item_is_blacklisted(), MAGAZINE_WELL, and cata::hash64_detail::ret.
Referenced by item::magazine_compatible(), and item::magazine_default().
magazine_current()
item * item_contents::magazine_current ()
Definition at line 1287 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE_WELL ) ) {
             item *mag = pocket.magazine_current();
             if( mag != nullptr ) {
                 return mag;
             }
         }
     }
     return nullptr;
 }
References contents, item::magazine_current(), and MAGAZINE_WELL.
Referenced by item::magazine_current().
magazine_default()
itype_id item_contents::magazine_default () const
Definition at line 2008 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE_WELL ) ) {
             return pocket.magazine_default();
         }
     }
     return itype_id::NULL_ID();
 }
References contents, MAGAZINE_WELL, and string_id< itype >::NULL_ID().
Referenced by item::magazine_default().
magazine_flag_restrictions()
std::set< flag_id > item_contents::magazine_flag_restrictions () const
Definition at line 1004 of file item_contents.cpp.
 {
     std::set<flag_id> ret;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MAGAZINE_WELL ) ) {
             ret = pocket.get_pocket_data()->get_flag_restrictions();
         }
     }
     return ret;
 }
References contents, MAGAZINE_WELL, and cata::hash64_detail::ret.
Referenced by item::gun_info(), and item::tool_info().
max_containable_length()
units::length item_contents::max_containable_length (bool unrestricted_pockets_only = false) const
Definition at line 965 of file item_contents.cpp.
 {
     units::length ret = 0_mm;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_forbidden() ) {
             continue;
         }
         bool restriction_condition = !pocket.is_type( pocket_type::CONTAINER ) ||
                                      pocket.is_ablative() || pocket.holster_full();
         if( unrestricted_pockets_only ) {
             restriction_condition = restriction_condition && pocket.is_restricted();
         }
         if( restriction_condition ) {
             continue;
         }
         units::length candidate = pocket.max_containable_length();
         if( candidate > ret ) {
             ret = candidate;
         }
     }
     return ret;
 }
References CONTAINER, contents, and cata::hash64_detail::ret.
Referenced by item::max_containable_length().
max_containable_volume()
units::volume item_contents::max_containable_volume (bool unrestricted_pockets_only = false) const
Definition at line 1015 of file item_contents.cpp.
 {
     units::volume ret = 0_ml;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_forbidden() ) {
             continue;
         }
         bool restriction_condition = !pocket.is_type( pocket_type::CONTAINER ) ||
                                      pocket.is_ablative() || pocket.holster_full() ||
                                      pocket.volume_capacity() >= pocket_data::max_volume_for_container;
         if( unrestricted_pockets_only ) {
             restriction_condition = restriction_condition && pocket.is_restricted();
         }
         if( restriction_condition ) {
             continue;
         }
         units::volume candidate = pocket.remaining_volume();
         if( candidate > ret ) {
             ret = candidate;
         }
     }
     return ret;
 }
References CONTAINER, contents, pocket_data::max_volume_for_container, and cata::hash64_detail::ret.
Referenced by item::max_containable_volume().
min_containable_length()
units::length item_contents::min_containable_length () const
Definition at line 988 of file item_contents.cpp.
 {
     units::length ret = 0_mm;
     for( const item_pocket &pocket : contents ) {
         if( !pocket.is_type( pocket_type::CONTAINER ) || pocket.is_ablative() ||
             pocket.holster_full() ) {
             continue;
         }
         units::length candidate = pocket.min_containable_length();
         if( candidate > ret ) {
             ret = candidate;
         }
     }
     return ret;
 }
References CONTAINER, contents, and cata::hash64_detail::ret.
Referenced by item::min_containable_length().
mods()
std::vector< const item * > item_contents::mods () const
Definition at line 1843 of file item_contents.cpp.
 {
     std::vector<const item *> mods;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MOD ) ) {
             for( const item *it : pocket.all_items_top() ) {
                 mods.insert( mods.end(), it );
             }
         }
     }
     return mods;
 }
References item::all_items_top(), contents, and MOD.
Referenced by item::convert(), gunmods(), and item::mods().
num_item_stacks()
size_t item_contents::num_item_stacks () const
returns the number of items stacks in contents each item that is not count_by_charges, plus whole stacks of items that are
Definition at line 1189 of file item_contents.cpp.
 {
     size_t num = 0;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::MOD ) ||
             pocket.is_type( pocket_type::MAGAZINE_WELL ) ||
             pocket.is_type( pocket_type::CORPSE ) ) {
             // mods and magazine wells aren't really a contained item, which this function gets
             continue;
         }
         num += pocket.size();
     }
     return num;
 }
References contents, CORPSE, MAGAZINE_WELL, and MOD.
Referenced by item::num_item_stacks(), and only_item().
obtain_cost()
int item_contents::obtain_cost (const item & it) const
Definition at line 835 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         const int mv = pocket.obtain_cost( it );
         if( mv != 0 ) {
             return mv;
         }
     }
     return 0;
 }
References contents.
Referenced by item::obtain_cost().
on_pickup()
void item_contents::on_pickup (Character & guy, item * avoid = nullptr)
Definition at line 1204 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( !pocket.is_type( pocket_type::MOD ) ) {
             pocket.on_pickup( guy, avoid );
         }
     }
 }
References contents, and MOD.
Referenced by item::on_pickup().
only_item() [1/2]
item & item_contents::only_item ()
Definition at line 1609 of file item_contents.cpp.
 {
     if( num_item_stacks() != 1 ) {
         debugmsg( "ERROR: item_contents::only_item called with %d items contained", num_item_stacks() );
         return null_item_reference();
     }
     return first_item();
 }
References debugmsg, first_item(), null_item_reference(), and num_item_stacks().
Referenced by item::only_item().
only_item() [2/2]
const item & item_contents::only_item () const
Definition at line 1632 of file item_contents.cpp.
 {
     if( num_item_stacks() != 1 ) {
         debugmsg( "ERROR: item_contents::only_item called with %d items contained", num_item_stacks() );
         return null_item_reference();
     }
     return first_item();
 }
References debugmsg, first_item(), null_item_reference(), and num_item_stacks().
overflow()
void item_contents::overflow (const tripoint & pos, const item_location & loc)
Definition at line 1224 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         pocket.overflow( pos, loc );
     }
 }
References contents, and math_opers::pos().
Referenced by item::overflow().
process()
void item_contents::process (map & here, Character * carrier, const tripoint & pos, float insulation = 1, temperature_flag flag = temperature_flag::NORMAL, float spoil_multiplier_parent = 1.0f)
Is part of the recursive call of item::process.
see that function for additional comments NOTE: this destroys the items that get processed
Definition at line 2497 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) ) {
             pocket.process( here, carrier, pos, insulation, flag, spoil_multiplier_parent );
         }
     }
 }
References CONTAINER, contents, and math_opers::pos().
Referenced by item::process().
read_mods()
void item_contents::read_mods (const item_contents & read_input)
Definition at line 661 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : read_input.contents ) {
         if( pocket.saved_type() == pocket_type::MOD ) {
             for( const item *it : pocket.all_items_top() ) {
                 if( it->is_gunmod() || it->is_toolmod() ) {
                     insert_item( *it, pocket_type::MOD );
                 } else {
                     debugmsg( "Non-mod %s in MOD pocket!", it->tname() );
                     insert_item( *it, pocket_type::MIGRATION );
                 }
             }
         }
     }
 }
References item_pocket::all_items_top(), contents, debugmsg, insert_item(), MIGRATION, MOD, and item_pocket::saved_type().
relative_encumbrance()
float item_contents::relative_encumbrance () const
If contents should contribute to encumbrance, returns a value between 0 and 1 indicating the position between minimum and maximum contribution it's currently making.
Otherwise, return 0
Definition at line 2530 of file item_contents.cpp.
 {
     units::volume nonrigid_max_volume;
     units::volume nonrigid_volume;
     for( const item_pocket &pocket : contents ) {
         if( !pocket.is_type( pocket_type::CONTAINER ) ) {
             continue;
         }
         if( pocket.rigid() ) {
             continue;
         }
         // need to modify by pockets volume encumbrance modifier since some pockets may have less effect than others
         float modifier = pocket.get_pocket_data()->volume_encumber_modifier;
         nonrigid_volume += pocket.contains_volume() * modifier;
         nonrigid_max_volume += pocket.max_contains_volume() * modifier;
     }
     if( nonrigid_volume > nonrigid_max_volume ) {
         // volume exceeds capacity and will spill until 1 or lower if picked up, so assume 1
         return 1;
     }
     if( nonrigid_max_volume == 0_ml ) {
         return 0;
     }
     return nonrigid_volume * 1.0 / nonrigid_max_volume;
 }
References CONTAINER, and contents.
Referenced by item::get_encumber().
remaining_capacity_for_liquid()
int item_contents::remaining_capacity_for_liquid (const item & liquid) const
Definition at line 2516 of file item_contents.cpp.
 {
     int charges_of_liquid = 0;
     item liquid_copy = liquid;
     liquid_copy.charges = 1;
     for( const item_pocket &pocket : contents ) {
         if( !pocket.is_type( pocket_type::CONTAINER ) ) {
             continue;
         }
         charges_of_liquid += pocket.remaining_capacity_for_item( liquid );
     }
     return charges_of_liquid;
 }
References item::charges, CONTAINER, and contents.
Referenced by item::get_remaining_capacity_for_liquid().
remaining_container_capacity()
units::volume item_contents::remaining_container_capacity (bool unrestricted_pockets_only = false) const
Definition at line 2360 of file item_contents.cpp.
 {
     units::volume total_vol = 0_ml;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_forbidden() ) {
             continue;
         }
         bool restriction_condition = pocket.is_type( pocket_type::CONTAINER );
         if( unrestricted_pockets_only ) {
             restriction_condition = restriction_condition && !pocket.is_restricted();
         }
         if( restriction_condition ) {
             total_vol += pocket.remaining_volume();
         }
     }
     return total_vol;
 }
References CONTAINER, and contents.
Referenced by item::get_remaining_capacity().
remaining_container_capacity_weight()
units::mass item_contents::remaining_container_capacity_weight (bool unrestricted_pockets_only = false) const
Definition at line 2394 of file item_contents.cpp.
 {
     units::mass total_weight = 0_gram;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_forbidden() ) {
             continue;
         }
         bool restriction_condition = pocket.is_type( pocket_type::CONTAINER );
         if( unrestricted_pockets_only ) {
             restriction_condition = restriction_condition && !pocket.is_restricted();
         }
         if( restriction_condition ) {
             total_weight += pocket.remaining_weight();
         }
     }
     return total_weight;
 }
References CONTAINER, and contents.
Referenced by item::get_remaining_weight_capacity().
remove_internal()
void item_contents::remove_internal (const std::function< bool(item &)> & filter, int & count, std::list< item > & res)
Definition at line 2487 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.remove_internal( filter, count, res ) ) {
             return;
         }
     }
 }
References contents, and filter.
Referenced by item::remove_internal(), and visitable::remove_items_with().
remove_items_if()
void item_contents::remove_items_if (const std::function< bool(item &)> & filter)
Definition at line 1670 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         pocket.remove_items_if( filter );
     }
 }
References contents, and filter.
remove_pocket()
item item_contents::remove_pocket (int index)
Definition at line 2138 of file item_contents.cpp.
 {
     // start at the first pocket
     auto rit = contents.rbegin();
     // find the pockets to remove from the item
     for( int i = additional_pockets.size() - 1; i >= index; --i ) {
         // move the iterator past all the pockets we aren't removing
         std::advance( rit, additional_pockets[i].get_all_contained_pockets().size() );
     }
     // at this point reversed past the pockets we want to get rid of so now start going forward
     auto it = std::next( rit ).base();
     units::volume total_nonrigid_volume = 0_ml;
     for( item_pocket *i_pocket : additional_pockets[index].get_all_contained_pockets() ) {
         total_nonrigid_volume += i_pocket->max_contains_volume();
         // move items from the consolidated pockets to the item that will be returned
         for( const item *item_to_move : it->all_items_top() ) {
             i_pocket->add( *item_to_move );
         }
         // finally remove the pocket data
         contents.erase( it++ );
     }
     additional_pockets_volume -= total_nonrigid_volume;
     additional_pockets_space_used -= additional_pockets[index].get_pocket_size();
     // create a copy of the item to return and delete the old items entry
     item it_return( additional_pockets[index] );
     additional_pockets.erase( additional_pockets.begin() + index );
     return it_return;
 }
References additional_pockets, additional_pockets_space_used, additional_pockets_volume, item::all_items_top(), contents, get_all_contained_pockets(), and size().
Referenced by activity_on_turn_move_loot(), unload_loot_activity_actor::do_turn(), and molle_detach_actor::use().
same_contents()
bool item_contents::same_contents (const item_contents & rhs) const
Definition at line 1557 of file item_contents.cpp.
 {
     if( contents.size() != rhs.contents.size() ) {
         return false;
     }
     return std::equal( contents.begin(), contents.end(),
                        rhs.contents.begin(), rhs.contents.end(),
     []( const item_pocket & a, const item_pocket & b ) {
         return a.same_contents( b );
     } );
 }
References a, b, and contents.
Referenced by item::same_contents().
seal_all_pockets()
bool item_contents::seal_all_pockets ()
Definition at line 1470 of file item_contents.cpp.
 {
     bool any_sealed = false;
     for( item_pocket &pocket : contents ) {
         any_sealed = pocket.seal() || any_sealed;
     }
     return any_sealed;
 }
References contents.
Referenced by item::seal().
serialize()
void item_contents::serialize (JsonOut & json) const
Definition at line 225 of file savegame_json.cpp.
 {
     if( !contents.empty() || !get_all_ablative_pockets().empty() || !additional_pockets.empty() ) {
         json.start_object();
         json.member( "contents", contents );
         json.member( "additional_pockets", additional_pockets );
         json.end_object();
     }
 }
References additional_pockets, contents, empty(), JsonOut::end_object(), get_all_ablative_pockets(), JsonOut::member(), and JsonOut::start_object().
set_item_defaults()
void item_contents::set_item_defaults ()
Sets the items contained to their defaults.
Definition at line 1458 of file item_contents.cpp.
 {
     /* For Items with a magazine or battery in its contents */
     for( item_pocket &pocket : contents ) {
         if( !pocket.is_standard_type() ) {
             continue;
         }
         pocket.set_item_defaults();
     }
 }
References contents.
size()
size_t item_contents::size () const
Definition at line 656 of file item_contents.cpp.
 {
     return contents.size();
 }
References contents.
Referenced by anonymous_namespace{item.cpp}::_stacks_whiteblacklist(), get_added_pocket(), has_unrestricted_pockets(), and remove_pocket().
softwares()
std::vector< const item * > item_contents::softwares () const
Definition at line 1856 of file item_contents.cpp.
 {
     std::vector<const item *> softwares;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::SOFTWARE ) ) {
             for( const item *it : pocket.all_items_top() ) {
                 softwares.insert( softwares.end(), it );
             }
         }
     }
     return softwares;
 }
References item::all_items_top(), contents, and SOFTWARE.
Referenced by item::softwares().
spill_contents()
bool item_contents::spill_contents (const tripoint & pos)
Definition at line 1213 of file item_contents.cpp.
 {
     bool spilled = false;
     for( item_pocket &pocket : contents ) {
         if( !pocket.get_pocket_data()->_no_unload ) {
             spilled = pocket.spill_contents( pos ) || spilled;
         }
     }
     return spilled;
 }
References contents, and math_opers::pos().
Referenced by Character::handle_melee_wear(), and item::spill_contents().
spill_open_pockets()
bool item_contents::spill_open_pockets (Character & guy, const item * avoid = nullptr)
Definition at line 1395 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) && pocket.will_spill() ) {
             pocket.handle_liquid_or_spill( guy, avoid );
             if( !pocket.empty() ) {
                 return false;
             }
         }
     }
     return true;
 }
References CONTAINER, and contents.
Referenced by item::spill_open_pockets().
stacks_with()
bool item_contents::stacks_with (const item_contents & rhs, int depth = 0, int maxdepth = 2) const
Definition at line 1544 of file item_contents.cpp.
 {
     if( contents.size() != rhs.contents.size() ) {
         return false;
     }
     return ( empty() && rhs.empty() ) ||
            std::equal( contents.begin(), contents.end(),
                        rhs.contents.begin(),
     [depth, maxdepth]( const item_pocket & a, const item_pocket & b ) {
         return a.stacks_with( b, depth, maxdepth );
     } );
 }
References a, b, contents, and empty().
Referenced by item::stacks_with().
total_contained_volume()
units::volume item_contents::total_contained_volume (bool unrestricted_pockets_only = false) const
Definition at line 2379 of file item_contents.cpp.
 {
     units::volume total_vol = 0_ml;
     for( const item_pocket &pocket : contents ) {
         bool restriction_condition = pocket.is_type( pocket_type::CONTAINER );
         if( unrestricted_pockets_only ) {
             restriction_condition = restriction_condition && !pocket.is_restricted();
         }
         if( restriction_condition ) {
             total_vol += pocket.contains_volume();
         }
     }
     return total_vol;
 }
References CONTAINER, and contents.
Referenced by item::get_total_contained_volume(), and item::total_contained_volume().
total_contained_weight()
units::mass item_contents::total_contained_weight (bool unrestricted_pockets_only = false) const
Definition at line 2413 of file item_contents.cpp.
 {
     units::mass total_weight = 0_gram;
     for( const item_pocket &pocket : contents ) {
         bool restriction_condition = pocket.is_type( pocket_type::CONTAINER );
         if( unrestricted_pockets_only ) {
             restriction_condition = restriction_condition && !pocket.is_restricted();
         }
         if( restriction_condition ) {
             total_weight += pocket.contains_weight();
         }
     }
     return total_weight;
 }
References CONTAINER, and contents.
Referenced by item::get_total_contained_weight().
total_container_capacity()
units::volume item_contents::total_container_capacity (bool unrestricted_pockets_only = false) const
gets the total volume available to be used.
does not guarantee that an item of that size can be inserted.
Definition at line 2308 of file item_contents.cpp.
 {
     units::volume total_vol = 0_ml;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_forbidden() ) {
             continue;
         }
         bool restriction_condition = pocket.is_type( pocket_type::CONTAINER );
         if( unrestricted_pockets_only ) {
             restriction_condition = restriction_condition && !pocket.is_restricted();
         }
         if( restriction_condition ) {
             // If the pocket is a holster that has an item return the volume when it is full (not larger than capacity).
             // If the pocket has default volume or is a pocket that has normal pickup disabled return the volume of things contained.
             // Otherwise, return the capacity.
             if( pocket.holster_full() ) {
                 units::volume add_volume = pocket.front().volume();
                 for( const item_pocket *it_pocket : pocket.front().get_all_contained_pockets() ) {
                     // Here, the case where the pocket is not empty for the holster is not considered, which will lead to higher results.
                     // To obtain accurate results, a recursive function may be required. Since in the actual game,
                     // the situation of holster nested in the holster is very rare, from a performance perspective, it seems not worth it to do so.
                     if( it_pocket->is_valid() && !it_pocket->rigid() ) {
                         add_volume += it_pocket->remaining_volume();
                     }
                 }
                 total_vol += std::min( pocket.volume_capacity(), add_volume );
             } else if( pocket.volume_capacity() >= pocket_data::max_volume_for_container ||
                        pocket.settings.is_disabled() ) {
                 total_vol += pocket.contains_volume();
             } else {
                 total_vol += pocket.volume_capacity();
             }
         }
     }
     return total_vol;
 }
References CONTAINER, contents, item_pocket::front(), item::get_all_contained_pockets(), pocket_data::max_volume_for_container, and min().
Referenced by item::get_total_capacity(), and info().
total_container_weight_capacity()
units::mass item_contents::total_container_weight_capacity (bool unrestricted_pockets_only = false) const
Definition at line 2018 of file item_contents.cpp.
 {
     units::mass total_weight = 0_gram;
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_forbidden() ) {
             continue;
         }
         bool restriction_condition = pocket.is_type( pocket_type::CONTAINER ) &&
                                      !pocket.is_ablative() && pocket.weight_capacity() < pocket_data::max_weight_for_container;
         if( unrestricted_pockets_only ) {
             restriction_condition = restriction_condition && !pocket.is_restricted();
         }
         if( restriction_condition ) {
             total_weight += pocket.weight_capacity();
         }
     }
     return total_weight;
 }
References CONTAINER, contents, and pocket_data::max_weight_for_container.
Referenced by item::get_total_weight_capacity(), and info().
total_standard_capacity()
units::volume item_contents::total_standard_capacity (bool unrestricted_pockets_only = false) const
Definition at line 2345 of file item_contents.cpp.
 {
     units::volume total_vol = 0_ml;
     for( const item_pocket &pocket : contents ) {
         bool restriction_condition = pocket.is_standard_type();
         if( unrestricted_pockets_only ) {
             restriction_condition = restriction_condition && !pocket.is_restricted();
         }
         if( restriction_condition ) {
             total_vol += pocket.volume_capacity();
         }
     }
     return total_vol;
 }
References contents.
update_modified_pockets()
void item_contents::update_modified_pockets (const std::optional< const pocket_data * > & mag_or_mag_well, std::vector< const pocket_data * > container_pockets)
Definition at line 1924 of file item_contents.cpp.
 {
     bool mag_or_well_found = false;
     for( auto pocket_iter = contents.begin(); pocket_iter != contents.end(); ) {
         item_pocket &pocket = *pocket_iter;
         if( pocket.is_type( pocket_type::CONTAINER ) ) {
             const pocket_data *current = pocket.get_pocket_data();
             bool found = false;
             // this loop is to make sure the pockets on the current item are already here from @container_pockets,
             // so we don't need to clear them (saving the favorite data)
             for( auto container_pocket = container_pockets.begin(); container_pocket != container_pockets.end();
                ) {
                 // comparing pointers because each pocket is uniquely defined in json as its own.
                 if( *container_pocket == current ) {
                     container_pocket = container_pockets.erase( container_pocket );
                     found = true;
                     // there will not be more than one pocket with the same pocket_data pointer, so exit early
                     break;
                 } else {
                     ++container_pocket;
                 }
             }
             if( !found ) {
                 if( !pocket.empty() ) {
                     // in case the debugmsg wasn't clear, this should never happen
                     debugmsg( "Oops!  deleted some items when updating pockets that were added via toolmods" );
                 }
                 pocket_iter = contents.erase( pocket_iter );
             } else {
                 ++pocket_iter;
             }
         } else if( pocket.is_type( pocket_type::MAGAZINE ) ||
                    pocket.is_type( pocket_type::MAGAZINE_WELL ) ) {
             if( mag_or_mag_well ) {
                 if( pocket.get_pocket_data() != *mag_or_mag_well ) {
                     if( !pocket.empty() ) {
                         // in case the debugmsg wasn't clear, this should never happen
                         debugmsg( "Oops!  deleted some items when updating pockets that were added via toolmods" );
                     }
                     pocket_iter = contents.erase( pocket_iter );
                 } else {
                     mag_or_well_found = true;
                     ++pocket_iter;
                 }
             } else {
                 // no mag or mag well, so it needs to be erased
                 pocket_iter = contents.erase( pocket_iter );
             }
         } else {
             ++pocket_iter;
         }
     }
     // we've deleted all of the superfluous copies already, so time to add the new pockets
     for( const pocket_data *container_pocket : container_pockets ) {
         contents.emplace_back( container_pocket );
     }
     if( mag_or_mag_well && !mag_or_well_found ) {
         contents.emplace_back( *mag_or_mag_well );
     }
 }
References CONTAINER, contents, debugmsg, item_pocket::empty(), item_pocket::get_pocket_data(), item_pocket::is_type(), MAGAZINE, and MAGAZINE_WELL.
Referenced by item::update_modified_pockets().
update_open_pockets()
void item_contents::update_open_pockets ()
Definition at line 1449 of file item_contents.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( pocket.empty() ) {
             pocket.unseal();
         }
     }
 }
References contents.
Referenced by item::on_contents_changed().
will_spill()
bool item_contents::will_spill () const
Definition at line 1374 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER ) && pocket.will_spill() ) {
             return true;
         }
     }
     return false;
 }
References CONTAINER, and contents.
Referenced by item::will_spill().
will_spill_if_unsealed()
bool item_contents::will_spill_if_unsealed () const
Definition at line 1384 of file item_contents.cpp.
 {
     for( const item_pocket &pocket : contents ) {
         if( pocket.is_type( pocket_type::CONTAINER )
             && pocket.will_spill_if_unsealed() ) {
             return true;
         }
     }
     return false;
 }
References CONTAINER, and contents.
Referenced by item::will_spill_if_unsealed().
Friends And Related Function Documentation
item_contents_helper
friend struct item_contents_helper friend
Definition at line 405 of file item_contents.h.
visit_contents()
VisitResponse item_contents::visit_contents (const std::function< VisitResponse(item *, item *)> & func, item * parent = nullptr) related
NOTE: upon expansion, this may need to be filtered by type enum depending on accessibility.
Definition at line 372 of file visitable.cpp.
 {
     for( item_pocket &pocket : contents ) {
         if( !pocket.is_type( pocket_type::CONTAINER ) ) {
             // anything that is not CONTAINER is accessible only via its specific accessor
             continue;
         }
         switch( pocket.visit_contents( func, parent ) ) {
             case VisitResponse::ABORT:
                 return VisitResponse::ABORT;
             default:
                 break;
         }
     }
     return VisitResponse::NEXT;
 }
References ABORT, CONTAINER, contents, and NEXT.
Referenced by item::visit_contents().
Member Data Documentation
additional_pockets
std::vector<item> item_contents::additional_pockets private
Definition at line 396 of file item_contents.h.
Referenced by add_pocket(), combine(), deserialize(), get_added_pocket(), get_added_pockets(), get_additional_volume(), get_additional_weight(), has_additional_pockets(), info(), remove_pocket(), and serialize().
additional_pockets_space_used
int item_contents::additional_pockets_space_used = 0 private
Definition at line 401 of file item_contents.h.
Referenced by add_pocket(), get_additional_space_used(), and remove_pocket().
additional_pockets_volume
units::volume item_contents::additional_pockets_volume = 0_ml private
Definition at line 398 of file item_contents.h.
Referenced by add_pocket(), get_additional_pocket_encumbrance(), and remove_pocket().
contents
std::list<item_pocket> item_contents::contents private
Definition at line 393 of file item_contents.h.
Referenced by add_pocket(), all_items_top(), all_pockets_rigid(), all_pockets_sealed(), allows_speedloader(), ammo_capacity(), ammo_consume(), ammo_types(), any_pockets_sealed(), best_pocket(), best_quality(), bigger_on_the_inside(), cables(), can_contain(), can_contain_liquid(), can_contain_rigid(), can_unload_liquid(), casings_handle(), clear_items(), clear_magazines(), clear_pockets_if(), combine(), contained_where(), contains_no_solids(), deserialize(), ebooks(), empty(), empty_container(), empty_with_no_mods(), item_contents::item_contents_helper::find_pocket_for(), first_ammo(), first_item(), force_insert_item(), full(), get_added_pocket(), get_all_reloadable_pockets(), get_pockets(), get_total_holster_volume(), get_total_holster_weight(), get_total_holsters(), get_used_holster_volume(), get_used_holster_weight(), get_used_holsters(), gunmods(), handle_liquid_or_spill(), has_any_with(), has_pocket_type(), has_unrestricted_pockets(), heat_up(), info(), is_compatible(), is_funnel_container(), is_magazine_full(), is_restricted_container(), item_contents(), item_has_uses_recursive(), item_length_modifier(), item_size_modifier(), item_weight_modifier(), leak(), magazine_compatible(), magazine_current(), magazine_default(), magazine_flag_restrictions(), max_containable_length(), max_containable_volume(), min_containable_length(), mods(), num_item_stacks(), obtain_cost(), on_pickup(), overflow(), process(), read_mods(), relative_encumbrance(), remaining_capacity_for_liquid(), remaining_container_capacity(), remaining_container_capacity_weight(), remove_internal(), remove_items_if(), remove_pocket(), same_contents(), seal_all_pockets(), serialize(), set_item_defaults(), size(), softwares(), spill_contents(), spill_open_pockets(), stacks_with(), total_contained_volume(), total_contained_weight(), total_container_capacity(), total_container_weight_capacity(), total_standard_capacity(), update_modified_pockets(), update_open_pockets(), visit_contents(), will_spill(), and will_spill_if_unsealed().
The documentation for this class was generated from the following files:
src/item_contents.h
src/item_action.cpp
src/item_contents.cpp
src/savegame_json.cpp
src/visitable.cpp