Cataclysm DDA: relic Class Reference
relic Class Reference
#include <relic.h>
Public Member Functions
std::string name () const
int activate (Creature &caster, const tripoint &target)
int charges () const
int charges_per_use () const
int max_charges () const
bool has_activation () const
bool has_recharge () const
void try_recharge (item &parent, Character *carrier, const tripoint &pos)
bool can_recharge (item &parent, Character *carrier) const
void load (const JsonObject &jo)
void finalize ()
void serialize (JsonOut &jsout) const
void deserialize (const JsonObject &jobj)
void add_passive_effect (const enchant_cache &ench)
void add_passive_effect (const enchantment &ench)
void add_active_effect (const fake_spell &sp)
std::vector< enchant_cache > get_proc_enchantments () const
std::vector< enchantment > get_defined_enchantments () const
void overwrite_charge (const relic_charge_info &info)
int power_level (const relic_procgen_id &ruleset) const
Private Attributes
std::vector< fake_spell > active_effects
std::vector< enchant_cache > proc_passive_effects
std::vector< enchantment > defined_passive_effects
translation item_name_override
relic_charge_info charge
int moves = 0
std::vector< enchantment_id > passive_enchant_ids
Friends
bool operator== (const relic &source_relic, const relic &target_relic)
Detailed Description
Definition at line 201 of file relic.h.
Member Function Documentation
activate()
int relic::activate (Creature & caster, const tripoint & target)
Definition at line 416 of file relic.cpp.
 {
     if( charge.charges_per_use != 0 && charges() - charge.charges_per_use < 0 ) {
         caster.add_msg_if_player( m_bad, _( "This artifact lacks the charges to activate." ) );
         return 0;
     }
     caster.mod_moves( -moves );
     for( const fake_spell &sp : active_effects ) {
         spell casting = sp.get_spell( caster, sp.level );
         casting.cast_all_effects( caster, target );
         caster.add_msg_if_player( casting.message(), casting.name() );
     }
     charge.charges -= charge.charges_per_use;
     return charge.charges_per_use;
 }
References _, Creature::add_msg_if_player(), spell::cast_all_effects(), m_bad, spell::message(), Creature::mod_moves(), and spell::name().
add_active_effect()
void relic::add_active_effect (const fake_spell & sp)
Definition at line 109 of file relic.cpp.
 {
     active_effects.emplace_back( sp );
 }
References active_effects.
add_passive_effect() [1/2]
void relic::add_passive_effect (const enchant_cache & ench)
Definition at line 114 of file relic.cpp.
 {
     for( enchant_cache &ench : proc_passive_effects ) {
         if( ench.add( nench ) ) {
             return;
         }
     }
     proc_passive_effects.emplace_back( nench );
 }
References proc_passive_effects.
add_passive_effect() [2/2]
void relic::add_passive_effect (const enchantment & ench)
Definition at line 124 of file relic.cpp.
 {
     defined_passive_effects.emplace_back( nench );
 }
References defined_passive_effects.
can_recharge()
bool relic::can_recharge (item & parent, Character * carrier) const
Definition at line 533 of file relic.cpp.
 {
     if( carrier == nullptr && charge.has != relic_recharge_has::NUM ) {
         return false;
     }
     switch( charge.has ) {
         case relic_recharge_has::HELD: {
             return carrier->has_item( parent );
         }
         case relic_recharge_has::WORN: {
             return carrier->is_worn( parent ) || carrier->is_wielding( parent );
         }
         case relic_recharge_has::WIELD: {
             return carrier->is_wielding( parent );
         }
         case relic_recharge_has::NUM: {
             return true;
         }
     }
     return true;
 }
References visitable::has_item(), HELD, Character::is_wielding(), Character::is_worn(), NUM, WIELD, and WORN.
charges()
int relic::charges () const
Definition at line 432 of file relic.cpp.
 {
     return charge.charges;
 }
charges_per_use()
int relic::charges_per_use () const
Definition at line 437 of file relic.cpp.
 {
     return charge.charges_per_use;
 }
deserialize()
void relic::deserialize (const JsonObject & jobj)
Definition at line 380 of file relic.cpp.
 {
     load( jobj );
 }
References relic_procgen_data::load().
finalize()
void relic::finalize ()
Definition at line 372 of file relic.cpp.
 {
     // add the enchantments that we couldn't earlier in the load
     for( const enchantment_id &ench : passive_enchant_ids ) {
         add_passive_effect( ench.obj() );
     }
 }
get_defined_enchantments()
std::vector< enchantment > relic::get_defined_enchantments () const
Definition at line 579 of file relic.cpp.
 {
     return defined_passive_effects;
 }
get_proc_enchantments()
std::vector< enchant_cache > relic::get_proc_enchantments () const
Definition at line 574 of file relic.cpp.
 {
     return proc_passive_effects;
 }
has_activation()
bool relic::has_activation () const
Definition at line 597 of file relic.cpp.
 {
     return !active_effects.empty();
 }
has_recharge()
bool relic::has_recharge () const
Definition at line 447 of file relic.cpp.
 {
     return charge.type != relic_recharge_type::NONE;
 }
References NONE.
load()
void relic::load (const JsonObject & jo)
Definition at line 342 of file relic.cpp.
 {
     if( jo.has_array( "active_effects" ) ) {
         for( JsonObject jobj : jo.get_array( "active_effects" ) ) {
             fake_spell sp;
             sp.load( jobj );
             add_active_effect( sp );
         }
     }
     if( jo.has_array( "passive_effects" ) ) {
         for( JsonObject jobj : jo.get_array( "passive_effects" ) ) {
             enchant_cache ench;
             ench.load( jobj );
             if( !ench.id.is_empty() ) {
                 // for enchantments by id we need to wait till finalize to cast them to objects
                 // for now stash them
                 passive_enchant_ids.push_back( ench.id );
             } else {
                 add_passive_effect( ench );
             }
         }
     }
     jo.read( "charge_info", charge );
     if( jo.has_member( "charges_per_activation" ) ) {
         charge.charges_per_use = jo.get_int( "charges_per_activation", 1 );
     }
     jo.read( "name", item_name_override );
     moves = jo.get_int( "moves", 100 );
 }
References JsonObject::get_array(), JsonObject::get_int(), JsonObject::has_array(), JsonObject::has_member(), enchantment::id, string_id< T >::is_empty(), fake_spell::load(), enchant_cache::load(), and JsonObject::read().
Referenced by Item_factory::load().
max_charges()
int relic::max_charges () const
Definition at line 442 of file relic.cpp.
 {
     return charge.max_charges;
 }
name()
std::string relic::name () const
Definition at line 569 of file relic.cpp.
 {
     return item_name_override.translated();
 }
overwrite_charge()
void relic::overwrite_charge (const relic_charge_info & info)
Definition at line 564 of file relic.cpp.
 {
     charge = info;
 }
power_level()
int relic::power_level (const relic_procgen_id & ruleset) const
Definition at line 584 of file relic.cpp.
 {
     int total_power_level = 0;
     for( const enchant_cache &ench : proc_passive_effects ) {
         total_power_level += ruleset->power_level( ench );
     }
     for( const fake_spell &sp : active_effects ) {
         total_power_level += ruleset->power_level( sp );
     }
     total_power_level += charge.power;
     return total_power_level;
 }
References relic_procgen_data::power_level().
serialize()
void relic::serialize (JsonOut & jsout) const
Definition at line 385 of file relic.cpp.
 {
     jsout.start_object();
     jsout.member( "moves", moves );
     // item_name_override is not saved, in case the original json text changes:
     // in such case names read back from a save would no longer be properly translated.
     if( !proc_passive_effects.empty() ) {
         jsout.member( "passive_effects" );
         jsout.start_array();
         for( const enchant_cache &ench : proc_passive_effects ) {
             ench.serialize( jsout );
         }
         jsout.end_array();
     }
     if( !active_effects.empty() ) {
         jsout.member( "active_effects" );
         jsout.start_array();
         for( const fake_spell &sp : active_effects ) {
             sp.serialize( jsout );
         }
         jsout.end_array();
     }
     jsout.member( "charge_info", charge );
     jsout.end_object();
 }
References JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), JsonOut::start_array(), and JsonOut::start_object().
try_recharge()
void relic::try_recharge (item & parent, Character * carrier, const tripoint & pos)
Definition at line 470 of file relic.cpp.
 {
     if( charge.regenerate_ammo && item_can_not_load_ammo( parent ) ) {
         return;
     }
     if( !charge.regenerate_ammo && charge.charges >= charge.max_charges ) {
         return;
     }
     if( !can_recharge( parent, carrier ) ) {
         return;
     }
     switch( charge.type ) {
         case relic_recharge_type::NONE: {
             return;
         }
         case relic_recharge_type::PERIODIC: {
             charge.accumulate_charge( parent );
             return;
         }
         case relic_recharge_type::SOLAR_SUNNY: {
             if( can_recharge_solar( parent, carrier, pos ) &&
                 get_weather().weather_id->light_modifier >= 0 ) {
                 charge.accumulate_charge( parent );
             }
             return;
         }
         case relic_recharge_type::LUNAR : {
             if( can_recharge_lunar( parent, carrier, pos ) &&
                 get_moon_phase( calendar::turn ) >= MOON_NEW &&
                 get_moon_phase( calendar::turn ) <= MOON_WANING_CRESCENT ) {
                 charge.accumulate_charge( parent );
             }
             return;
         }
         case relic_recharge_type::FULL_MOON : {
             if( can_recharge_lunar( parent, carrier, pos ) &&
                 get_moon_phase( calendar::turn ) == MOON_FULL ) {
                 charge.accumulate_charge( parent );
             }
             return;
         }
         case relic_recharge_type::NEW_MOON : {
             if( can_recharge_lunar( parent, carrier, pos ) &&
                 get_moon_phase( calendar::turn ) == MOON_NEW ) {
                 charge.accumulate_charge( parent );
             }
             return;
         }
         case relic_recharge_type::SOLAR_CLOUDY: {
             if( can_recharge_solar( parent, carrier, pos ) &&
                 get_weather().weather_id->light_modifier < 0 ) {
                 charge.accumulate_charge( parent );
             }
             return;
         }
         case relic_recharge_type::NUM: {
             debugmsg( "Attempted to recharge relic with invalid recharge type" );
             return;
         }
     }
 }
References can_recharge_lunar(), can_recharge_solar(), debugmsg, FULL_MOON, get_moon_phase(), get_weather(), item_can_not_load_ammo(), LUNAR, MOON_FULL, MOON_NEW, MOON_WANING_CRESCENT, NEW_MOON, NONE, NUM, PERIODIC, math_opers::pos(), SOLAR_CLOUDY, SOLAR_SUNNY, and calendar::turn.
Friends And Related Function Documentation
operator==
bool operator== (const relic & source_relic, const relic & target_relic) friend
Definition at line 813 of file relic.cpp.
 {
     bool is_the_same = true;
     is_the_same &= ( source_relic.charges() == target_relic.charges() );
     is_the_same &= ( source_relic.charges_per_use() == target_relic.charges_per_use() );
     is_the_same &= ( source_relic.has_activation() == target_relic.has_activation() );
     is_the_same &= ( source_relic.has_recharge() == target_relic.has_recharge() );
     is_the_same &= ( source_relic.max_charges() == target_relic.max_charges() );
     is_the_same &= ( source_relic.name() == target_relic.name() );
     is_the_same &= ( source_relic.get_proc_enchantments().size() ==
                      target_relic.get_proc_enchantments().size() );
     is_the_same &= ( source_relic.get_defined_enchantments().size() ==
                      target_relic.get_defined_enchantments().size() );
     if( is_the_same ) {
         for( std::size_t i = 0; i < source_relic.get_proc_enchantments().size(); i++ ) {
             is_the_same &= source_relic.get_proc_enchantments()[i] == target_relic.get_proc_enchantments()[i];
         }
     }
     return is_the_same;
 }
Member Data Documentation
active_effects
std::vector<fake_spell> relic::active_effects private
Definition at line 204 of file relic.h.
Referenced by add_active_effect().
charge
relic_charge_info relic::charge private
Definition at line 211 of file relic.h.
defined_passive_effects
std::vector<enchantment> relic::defined_passive_effects private
Definition at line 206 of file relic.h.
Referenced by add_passive_effect().
item_name_override
translation relic::item_name_override private
Definition at line 209 of file relic.h.
moves
int relic::moves = 0 private
Definition at line 214 of file relic.h.
passive_enchant_ids
std::vector<enchantment_id> relic::passive_enchant_ids private
Definition at line 217 of file relic.h.
proc_passive_effects
std::vector<enchant_cache> relic::proc_passive_effects private
Definition at line 205 of file relic.h.
Referenced by add_passive_effect().
The documentation for this class was generated from the following files:
src/relic.h
src/relic.cpp