Cataclysm DDA: int_id< T > Class Template Reference
int_id< T > Class Template Reference
Just like the string_id, this is a wrapper for int based identifiers.
#include <int_id.h>
Public Types
using This = int_id< T >
Public Member Functions
int_id (const int id)
Explicit constructor to make it stand out in the code, so one can easily search for all places that use it.
template<typename S , typename std::enable_if_t< !std::is_same_v< S, T >, int > = 0>
int_id (const int_id< S > &id)=delete
Prevent accidental construction from other int ids.
int_id ()
Default constructor constructs a 0-id.
int_id (const string_id< T > &id)
Construct an id from the matching string based id.
template<typename S , class = std::enable_if_t< std::is_convertible_v<S, std::string >>>
int_id (S &&id)
Forwarding constructor, forwards any parameter to the string_id constructor to create the int id.
bool operator< (const This &rhs) const
Comparison, only useful when the id is used in std::map or std::set as key.
bool operator== (const This &rhs) const
The usual comparator, compares the integer id as usual.
bool operator!= (const This &rhs) const
The usual comparator, compares the integer id as usual.
int to_i () const
Returns the identifier as plain int.
operator int () const
Conversion to int as with the to_i function.
operator bool () const
const string_id< T > & id () const
const T & obj () const
const T & operator* () const
const T * operator-> () const
bool is_valid () const
Returns whether this id is valid, that means whether it refers to an existing object.
const climbing_aid & obj () const
const string_id< climbing_aid > & id () const
bool is_valid () const
int_id (const string_id< climbing_aid > &id)
bool is_valid () const
const construction_category & obj () const
const string_id< construction_category > & id () const
bool is_valid () const
const construction_group & obj () const
const string_id< construction_group > & id () const
const oter_type_t & obj () const
Private Attributes
int _id
Related Functions
(Note that these are not member functions.)
template<>
bool is_valid () const
template<>
const ammo_effect & obj () const
template<>
const string_id< ammo_effect > & id () const
template<>
int_id (const string_id< ammo_effect > &id)
template<>
bool is_valid () const
template<>
const body_part_type & obj () const
template<>
const bodypart_str_id & id () const
template<>
int_id (const string_id< body_part_type > &id)
template<>
bool is_valid () const
template<>
const field_type & obj () const
template<>
int_id (const string_id< field_type > &id)
template<>
bool is_valid () const
template<>
const ter_t & obj () const
template<>
const string_id< ter_t > & id () const
template<>
int_id (const string_id< ter_t > &id)
template<>
bool is_valid () const
template<>
const furn_t & obj () const
template<>
int_id (const string_id< furn_t > &id)
template<>
const monfaction & obj () const
template<>
const string_id< monfaction > & id () const
template<>
int_id (const string_id< monfaction > &id)
template<>
bool is_valid () const
template<>
const mon_flag & obj () const
template<>
const string_id< mon_flag > & id () const
template<>
int_id (const string_id< mon_flag > &id)
template<>
int_id (const string_id< oter_type_t > &id)
template<>
int_id (const string_id< oter_t > &id)
template<>
bool is_valid () const
template<>
const oter_t & obj () const
template<>
const string_id< oter_t > & id () const
template<>
bool is_valid () const
template<>
const sub_body_part_type & obj () const
template<>
int_id (const string_id< sub_body_part_type > &id)
template<>
const string_id< trap > & id () const
template<>
bool is_valid () const
Detailed Description
template<typename T>
class int_id< T >
Just like the string_id, this is a wrapper for int based identifiers.
The template parameter T specifies what kind of object it identifies (e.g. a trap type, monster type, ...) See string_id for documentation on usage.
Definition at line 21 of file int_id.h.
Member Typedef Documentation
This
template<typename T > using int_id< T >::This = int_id<T>
Definition at line 24 of file int_id.h.
Constructor & Destructor Documentation
int_id() [1/6]
template<typename T > int_id< T >::int_id (const int id) inline explicit
Explicit constructor to make it stand out in the code, so one can easily search for all places that use it.
Definition at line 30 of file int_id.h.
             : _id( id ) {
         }
int_id() [2/6]
template<typename T > template<typename S , typename std::enable_if_t< !std::is_same_v< S, T >, int > = 0> int_id< T >::int_id (const int_id< S > & id) delete
Prevent accidental construction from other int ids.
int_id() [3/6]
template<typename T > int_id< T >::int_id () inline
Default constructor constructs a 0-id.
No id value is special to this class, 0 as id is just as normal as any other integer value.
Definition at line 44 of file int_id.h.
             : _id( 0 ) {
         }
int_id() [4/6]
template<typename T > int_id< T >::int_id (const string_id< T > & id)
Construct an id from the matching string based id.
This may show a debug message if the string id is invalid.
int_id() [5/6]
template<typename T > template<typename S , class = std::enable_if_t< std::is_convertible_v<S, std::string >>> int_id< T >::int_id (S && id) inline explicit
Forwarding constructor, forwards any parameter to the string_id constructor to create the int id.
This allows plain C-strings, and std::strings to be used.
Definition at line 61 of file int_id.h.
 : int_id( string_id<T>( std::forward<S>( id ) ) ) {}
int_id() [6/6]
int_id< climbing_aid >::int_id (const string_id< climbing_aid > & id)
Definition at line 70 of file climbing.cpp.
                                                                 : _id( id.id() )
 {
 }
Member Function Documentation
id() [1/4]
const string_id< climbing_aid > & int_id< climbing_aid >::id () const
Definition at line 53 of file climbing.cpp.
 {
     return climbing_aid_factory.convert( *this );
 }
References anonymous_namespace{climbing.cpp}::climbing_aid_factory.
id() [2/4]
const string_id< construction_category > & int_id< construction_category >::id () const
Definition at line 51 of file construction_category.cpp.
 {
     return all_construction_categories.convert( *this );
 }
References anonymous_namespace{construction_category.cpp}::all_construction_categories.
id() [3/4]
const string_id< ter_t > & id () const
Definition at line 51 of file construction_group.cpp.
 {
     return all_construction_groups.convert( *this );
 }
References anonymous_namespace{construction_group.cpp}::all_construction_groups.
id() [4/4]
template<typename T > const string_id< ammo_effect > & id () const
Definition at line 33 of file ammo_effect.cpp.
 {
     return get_all_ammo_effects().convert( *this );
 }
References get_all_ammo_effects().
Referenced by Creature::add_effect(), add_effect_to_target(), construct::add_matching_down_above(), construct::add_roof(), map::add_roofs(), jmapgen_field::apply(), jmapgen_trap::apply(), jmapgen_make_rubble::apply(), jmapgen_furniture::apply(), jmapgen_terrain::apply(), jmapgen_setmap::apply(), cardreader_examine_actor::apply(), Character::apply_damage(), Character::apply_wetness_morale(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), iexamine::autoclave_empty(), iexamine::autoclave_full(), cata_event_dispatch::avatar_moves(), Character::base_comfort_value(), Character::bionic_armor_bonus(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), Character::body_window(), outfit::bodypart_exposure(), overmap::build_connection(), overmap::build_lab(), melee_actor::call(), Character::can_install_cbm_on_bp(), change_cleared_terrain(), debug_menu::character_edit_hp_menu(), construct::check_matching_down_above(), climb_affordance_menu_decode(), map::close_door(), companion_travel_time_calc(), mutation_branch::conflicts_with_item(), mutation_branch::conflicts_with_item_rigid(), overmap_specials::create_building_from(), mutation_branch::damage_resistance(), debug_menu::damage_self(), Character::deal_damage(), Creature::deal_damage(), basecamp::define_camp(), melee_actor::do_grab(), map::draw_map(), Character::drench(), Character::drench_mut_calc(), Character::expose_to_disease(), conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location(), body_part_set::fill(), hacksaw_activity_actor::finish(), boltcutting_activity_actor::finish(), oxytorch_activity_actor::finish(), map::furn_set(), generate_uniform_omt(), Character::get_armor_type(), Character::get_env_resist(), recipe_group::get_recipes_by_id(), Character::get_total_bionics_slots(), Character::get_used_bionics_slots(), talk_function::give_aid(), talk_function::give_all_aid(), good_fishing_spot(), map::grow_plant(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), Creature::has_effect(), Character::heat_emission(), talk_function::hospital_raid_return(), is_ot_match(), item::is_owned_by(), iexamine::kiln_empty(), iexamine::kiln_full(), layer_item(), talk_function::lesser_give_aid(), talk_function::lesser_give_all_aid(), display::limb_color(), generic_factory< T >::load(), mutation_branch::load(), submap::load(), talk_function::loot_building(), editmap::mapgen_preview(), mapgendata::mapgendata(), armor_portion_data::max_coverage(), mill_activate(), iexamine::mill_finalize(), avatar_action::move(), mremove_trap(), talk_function::om_building_region(), om_companion_path(), om_target_tile(), melee_actor::on_damage(), bite_actor::on_damage(), Character::on_damage_of_type(), player_morale::on_worn_item_washed(), open(), map::open_door(), gates::open_gate(), oter_get_rotation(), oter_get_rotation_string(), oter_no_dir(), mutable_overmap_special_data::place(), map::place_items(), mission_start::place_npc_software(), map::place_spawns(), iexamine::portable_structure(), avatar::power_bionics(), vehicle::precalculate_vehicle_turning(), outfit::prepare_bodymap_info(), bodygraph_display::prepare_partlist(), Character::process_bionic(), Creature::process_damage_over_time(), body_part_type::random_sub_part(), Character::recalculate_bodyparts(), Character::regen(), Creature::remove_effect(), scatter_chunks(), talk_function::scavenging_raid_return(), blueprint_options::serialize(), overmap::serialize(), Creature::set_body(), player_morale::set_worn(), smash(), smoker_activate(), smoker_finalize(), boltcutting_activity_actor::start(), hacksaw_activity_actor::start(), oxytorch_activity_actor::start(), prying_activity_actor::start(), basecamp::start_fortifications(), iexamine::stook_empty(), iexamine::stook_full(), submap::store(), basecamp::survey_field_return(), basecamp::survey_return(), map::ter_set(), jmapgen_nested::neighbor_oter_check::test(), ter_furn_transform::transform(), map::trap_set(), avatar::try_to_sleep(), mapbuffer::unserialize_submaps(), Character::update_bodytemp(), Character::update_frostbite(), editmap::update_view_with_help(), explosion_iuse::use(), heal_actor::use(), game::walk_move(), npc::wear_if_wanted(), JsonOut::write(), and JsonOut::write_as_string().
is_valid() [1/4]
bool int_id< climbing_aid >::is_valid () const
Definition at line 59 of file climbing.cpp.
 {
     return climbing_aid_factory.is_valid( *this );
 }
References anonymous_namespace{climbing.cpp}::climbing_aid_factory.
is_valid() [2/4]
bool int_id< construction_category >::is_valid () const
Definition at line 39 of file construction_category.cpp.
 {
     return all_construction_categories.is_valid( *this );
 }
References anonymous_namespace{construction_category.cpp}::all_construction_categories.
is_valid() [3/4]
bool is_valid () const
Definition at line 39 of file construction_group.cpp.
 {
     return all_construction_groups.is_valid( *this );
 }
References anonymous_namespace{construction_group.cpp}::all_construction_groups.
is_valid() [4/4]
template<typename T > bool is_valid () const
Returns whether this id is valid, that means whether it refers to an existing object.
Definition at line 19 of file ammo_effect.cpp.
 {
     return get_all_ammo_effects().is_valid( *this );
 }
References get_all_ammo_effects().
Referenced by debug_menu::character_edit_hp_menu(), ammo_effect::check(), climb_affordance_menu_decode(), colorized_feature_description_at(), map::drop_items(), get_bp_from_str(), mutation_branch::load(), and blueprint_options::query_con().
obj() [1/5]
const climbing_aid & int_id< climbing_aid >::obj () const
Definition at line 42 of file climbing.cpp.
 {
     return climbing_aid_factory.obj( *this );
 }
References anonymous_namespace{climbing.cpp}::climbing_aid_factory.
obj() [2/5]
const construction_category & int_id< construction_category >::obj () const
Definition at line 45 of file construction_category.cpp.
 {
     return all_construction_categories.obj( *this );
 }
References anonymous_namespace{construction_category.cpp}::all_construction_categories.
obj() [3/5]
const field_type & obj () const
Definition at line 45 of file construction_group.cpp.
 {
     return all_construction_groups.obj( *this );
 }
References anonymous_namespace{construction_group.cpp}::all_construction_groups.
obj() [4/5]
template<typename T > const ammo_effect & obj () const
Definition at line 26 of file ammo_effect.cpp.
 {
     return get_all_ammo_effects().obj( *this );
 }
References get_all_ammo_effects().
Referenced by map::actualize(), field::add_field(), map::add_field(), construct::add_roof(), jmapgen_terrain::apply(), Character::base_comfort_value(), map::bash_rating(), map::bash_resistance(), map::bash_strength(), map::bash_ter_furn(), iuse::blood_draw(), board_up(), activity_handlers::build_do_turn(), map::build_floor_cache(), map::build_obstacle_cache(), map::build_outside_cache(), map::build_transparency_cache(), MapExtras::burned_ground_parser(), can_examine_at(), map::can_move_furniture(), construct::check_deconstruct(), map::close_door(), complete_construction(), iexamine::curtains(), MapExtras::dead_vegetation_parser(), map::decay_cosmetic_fields(), iexamine::deployed_furniture(), map::determine_wall_corner(), field::displayed_description_affix(), field_entry::do_decay(), construct::done_deconstruct(), editmap_hilight::draw(), overmap_ui::draw_ascii(), editmap::draw_main_ui_overlay(), map::draw_maptile(), overmap_ui::draw_om_sidebar(), map::drop_furniture(), editmap::edit_fld(), map::examine(), game::examine(), find_base_construction(), iexamine::fireplace(), Character::floor_bedding_warmth(), game::forced_door_closing(), inventory::form_from_map(), furn_is_supported(), map::furn_set(), map::furnname(), field_entry::gas_can_spread(), generic_multi_activity_locations(), get_alt_ter(), blueprint_options::get_final_construction(), get_hack_type(), get_keg_capacity(), map::get_known_connections(), map::get_known_rotates_to(), map::get_known_rotates_to_f(), field_entry::get_max_field_intensity(), map::get_roof(), map::get_ter_transforms_into(), grab(), game::grabbed_furn_move(), game::grabbed_furn_move_time(), map::grow_plant(), map::has_flag_furn(), map::has_flag_ter(), map::has_flag_ter_or_furn(), field_entry::initialize_decay(), map::is_bashable(), map::is_bashable_furn(), map::is_bashable_ter(), Character::is_immune_field(), monster::is_immune_field(), iexamine::ledge(), map::ledge_coverage(), explosion_iuse::load(), talk_function::loot_building(), mapgen_lake_shore(), mapgen_ocean_shore(), fungal_effects::marlossify(), map_stack::max_volume(), map::move_cost(), map::move_cost_ter_furn(), veh_interact::move_cursor(), field_entry::name(), om_cutdown_trees(), om_harvest_ter(), map::open_door(), int_id< T >::operator*(), int_id< T >::operator->(), iexamine::part_con(), place_craft_or_disassembly(), overmap_ui::place_ter_or_special(), MapExtras::place_trap_if_clear(), game::print_furniture_info(), game::print_part_con_info(), game::print_terrain_info(), map::process_items_in_submap(), activity_handlers::pulp_do_turn(), blueprint_options::query_con(), map::rad_scorch(), reload_furniture(), field::remove_field(), map::remove_trap(), map::restock_fruits(), route_best_workbench(), basecamp::scan_pseudo_items(), set_item_map_or_vehicle(), smash(), iexamine::smoker_options(), fungal_effects::spread_fungus_one_tile(), map::supports_above(), map::ter_set(), map::tername(), map::tr_at(), map::translate(), map::translate_radius(), map::trap_set(), activity_handlers::tree_communion_do_turn(), avatar::try_to_sleep(), Character::update_bodytemp(), editmap::update_fmenu_entry(), editmap::update_view_with_help(), map::vehicle_wheel_traction(), game::walk_move(), map::water_from(), Character::workbench_crafting_speed_multiplier(), and iexamine::workbench_internal().
obj() [5/5]
const oter_t & obj () const
Definition at line 369 of file overmap.cpp.
 {
     return terrain_types.obj( *this );
 }
References anonymous_namespace{overmap.cpp}::terrain_types.
operator bool()
template<typename T > int_id< T >::operator bool () const inline explicit
Definition at line 97 of file int_id.h.
{
             return _id != 0;
         }
References int_id< T >::_id.
operator int()
template<typename T > int_id< T >::operator int () const inline explicit
Conversion to int as with the to_i function.
Definition at line 93 of file int_id.h.
{
             return _id;
         }
References int_id< T >::_id.
operator!=()
template<typename T > bool int_id< T >::operator!= (const This & rhs) const inline
The usual comparator, compares the integer id as usual.
Definition at line 78 of file int_id.h.
{
             return _id != rhs._id;
         }
References int_id< T >::_id.
operator*()
template<typename T > const T& int_id< T >::operator* () const inline
Definition at line 106 of file int_id.h.
{
             return obj();
         }
References int_id< T >::obj().
operator->()
template<typename T > const T* int_id< T >::operator-> () const inline
Definition at line 110 of file int_id.h.
{
             return &obj();
         }
References int_id< T >::obj().
operator<()
template<typename T > bool int_id< T >::operator< (const This & rhs) const inline
Comparison, only useful when the id is used in std::map or std::set as key.
Definition at line 66 of file int_id.h.
{
             return _id < rhs._id;
         }
References int_id< T >::_id.
operator==()
template<typename T > bool int_id< T >::operator== (const This & rhs) const inline
The usual comparator, compares the integer id as usual.
Definition at line 72 of file int_id.h.
{
             return _id == rhs._id;
         }
References int_id< T >::_id.
to_i()
template<typename T > int int_id< T >::to_i () const inline
Returns the identifier as plain int.
Use with care, the plain int does not have any information as what type of object it refers to (the T template parameter of the class).
Definition at line 87 of file int_id.h.
{
             return _id;
         }
References int_id< T >::_id.
Referenced by map::actualize(), climb_affordance_menu_encode(), editmap_hilight::draw(), generic_factory< T >::find_id(), generic_factory< T >::insert(), generic_factory< T >::obj(), map::remove_trap(), editmap::setup_fmenu(), mapgen_function_json_base::setup_setmap(), map::ter_set(), editmap::update_fmenu_entry(), and editmap::update_view_with_help().
Friends And Related Function Documentation
id() [1/7]
const bodypart_str_id & id () const related
Definition at line 33 of file ammo_effect.cpp.
 {
     return get_all_ammo_effects().convert( *this );
 }
Referenced by are_requirements_nearby(), talk_function::caravan_depart(), find_tent_itype(), get_all_mutation_prereqs(), get_bodygraph_lines(), iexamine::get_harvest_items(), list_filter_high_priority(), list_filter_low_priority(), load_inline_topic(), load_overlay_ordering_into_array(), load_talk_topic(), mapgen_lake_shore(), mapgen_ocean_shore(), mapgen_ravine_edge(), iexamine::nanofab(), parse_keymap(), sounds::sound(), to_string_id_helper(), and activity_handlers::view_recipe_do_turn().
id() [2/7]
const bodypart_str_id & id () const related
Definition at line 201 of file bodypart.cpp.
 {
     return body_part_factory.convert( *this );
 }
References anonymous_namespace{bodypart.cpp}::body_part_factory.
id() [3/7]
const string_id< monfaction > & id () const related
Definition at line 57 of file mapdata.cpp.
 {
     return terrain_data.convert( *this );
 }
References anonymous_namespace{mapdata.cpp}::terrain_data.
id() [4/7]
const string_id< mon_flag > & id () const related
Definition at line 27 of file monfaction.cpp.
 {
     return faction_factory.convert( *this );
 }
References faction_factory.
id() [5/7]
const string_id< oter_t > & id () const related
Definition at line 148 of file monstergenerator.cpp.
 {
     return mon_flags.convert( *this );
 }
References anonymous_namespace{monstergenerator.cpp}::mon_flags.
id() [6/7]
const string_id< trap > & id () const related
Definition at line 422 of file overmap.cpp.
 {
     return terrains.convert( *this );
 }
References anonymous_namespace{overmap.cpp}::terrains.
id() [7/7]
const string_id< trap > & id () const related
Definition at line 81 of file trap.cpp.
 {
     return trap_factory.convert( *this );
 }
References anonymous_namespace{trap.cpp}::trap_factory.
int_id() [1/10]
int_id (const string_id< ammo_effect > & id) related
Definition at line 61 of file ammo_effect.cpp.
                                                               : _id( id.id() )
 {
 }
int_id() [2/10]
int_id (const string_id< body_part_type > & id) related
Definition at line 215 of file bodypart.cpp.
 : _id( id.id() ) {}
int_id() [3/10]
int_id (const string_id< field_type > & id) related
Definition at line 166 of file field_type.cpp.
                                                             : _id( id.id() )
 {
 }
int_id() [4/10]
int_id (const string_id< furn_t > & id) related
Definition at line 133 of file mapdata.cpp.
                                                     : _id( id.id() )
 {
 }
int_id() [5/10]
int_id (const string_id< mon_flag > & id) related
Definition at line 162 of file monstergenerator.cpp.
                                                         : _id( id.id() )
 {
 }
int_id() [6/10]
int_id (const string_id< monfaction > & id) related
Definition at line 55 of file monfaction.cpp.
 : _id( id.id() ) {}
int_id() [7/10]
int_id (const string_id< oter_t > & id) related
Definition at line 404 of file overmap.cpp.
 : _id( id.id() ) {}
int_id() [8/10]
int_id (const string_id< oter_type_t > & id) related
Definition at line 366 of file overmap.cpp.
 : _id( id.id() ) {}
int_id() [9/10]
int_id (const string_id< sub_body_part_type > & id) related
Definition at line 67 of file subbodypart.cpp.
 : _id( id.id() ) {}
int_id() [10/10]
int_id (const string_id< ter_t > & id) related
Definition at line 71 of file mapdata.cpp.
                                                   : _id( id.id() )
 {
 }
is_valid() [1/9]
bool is_valid () const related
Definition at line 19 of file ammo_effect.cpp.
 {
     return get_all_ammo_effects().is_valid( *this );
 }
is_valid() [2/9]
bool is_valid () const related
Definition at line 180 of file bodypart.cpp.
 {
     return body_part_factory.is_valid( *this );
 }
References anonymous_namespace{bodypart.cpp}::body_part_factory.
is_valid() [3/9]
bool is_valid () const related
Definition at line 115 of file field_type.cpp.
 {
     return get_all_field_types().is_valid( *this );
 }
References get_all_field_types().
is_valid() [4/9]
bool is_valid () const related
Definition at line 43 of file mapdata.cpp.
 {
     return terrain_data.is_valid( *this );
 }
References anonymous_namespace{mapdata.cpp}::terrain_data.
is_valid() [5/9]
bool is_valid () const related
Definition at line 91 of file mapdata.cpp.
 {
     return furniture_data.is_valid( *this );
 }
References anonymous_namespace{mapdata.cpp}::furniture_data.
is_valid() [6/9]
bool is_valid () const related
Definition at line 134 of file monstergenerator.cpp.
 {
     return mon_flags.is_valid( *this );
 }
References anonymous_namespace{monstergenerator.cpp}::mon_flags.
is_valid() [7/9]
bool is_valid () const related
Definition at line 408 of file overmap.cpp.
 {
     return terrains.is_valid( *this );
 }
References anonymous_namespace{overmap.cpp}::terrains.
is_valid() [8/9]
bool is_valid () const related
Definition at line 32 of file subbodypart.cpp.
 {
     return sub_body_part_factory.is_valid( *this );
 }
References anonymous_namespace{subbodypart.cpp}::sub_body_part_factory.
is_valid() [9/9]
bool is_valid () const related
Definition at line 108 of file trap.cpp.
 {
     return trap_factory.is_valid( *this );
 }
References anonymous_namespace{trap.cpp}::trap_factory.
obj() [1/9]
const body_part_type & obj () const related
Definition at line 26 of file ammo_effect.cpp.
 {
     return get_all_ammo_effects().obj( *this );
 }
Referenced by assign(), butchery_drops_harvest(), create_byproducts_legacy(), create_charge_items(), Messages::deserialize(), deserialize(), deserialize_from_string(), find_ammo_helper(), find_index(), json_loader::from_path_at_offset(), load_distribution(), parse_vp_control_reqs(), parse_vp_reqs(), retrieve_index(), serialize(), iuse::water_purifier(), and iexamine::workbench().
obj() [2/9]
const body_part_type & obj () const related
Definition at line 194 of file bodypart.cpp.
 {
     return body_part_factory.obj( *this );
 }
References anonymous_namespace{bodypart.cpp}::body_part_factory.
obj() [3/9]
const ter_t & obj () const related
Definition at line 122 of file field_type.cpp.
 {
     return get_all_field_types().obj( *this );
 }
References get_all_field_types().
obj() [4/9]
const furn_t & obj () const related
Definition at line 50 of file mapdata.cpp.
 {
     return terrain_data.obj( *this );
 }
References anonymous_namespace{mapdata.cpp}::terrain_data.
obj() [5/9]
const monfaction & obj () const related
Definition at line 98 of file mapdata.cpp.
 {
     return furniture_data.obj( *this );
 }
References anonymous_namespace{mapdata.cpp}::furniture_data.
obj() [6/9]
const mon_flag & obj () const related
Definition at line 20 of file monfaction.cpp.
 {
     return faction_factory.obj( *this );
 }
References faction_factory.
obj() [7/9]
const mon_flag & obj () const related
Definition at line 141 of file monstergenerator.cpp.
 {
     return mon_flags.obj( *this );
 }
References anonymous_namespace{monstergenerator.cpp}::mon_flags.
obj() [8/9]
const sub_body_part_type & obj () const related
Definition at line 415 of file overmap.cpp.
 {
     return terrains.obj( *this );
 }
References anonymous_namespace{overmap.cpp}::terrains.
obj() [9/9]
const trap & obj () const related
Definition at line 46 of file subbodypart.cpp.
 {
     return sub_body_part_factory.obj( *this );
 }
References anonymous_namespace{subbodypart.cpp}::sub_body_part_factory.
Member Data Documentation
_id
template<typename T > int int_id< T >::_id private
Definition at line 120 of file int_id.h.
Referenced by int_id< T >::operator bool(), int_id< T >::operator int(), int_id< T >::operator!=(), int_id< T >::operator<(), int_id< T >::operator==(), and int_id< T >::to_i().
The documentation for this class was generated from the following files:
src/int_id.h
src/ammo_effect.cpp
src/bodypart.cpp
src/field_type.cpp
src/mapdata.cpp
src/monfaction.cpp
src/monstergenerator.cpp
src/overmap.cpp
src/start_location.cpp
src/subbodypart.cpp
src/trap.cpp