Cataclysm DDA: avatar Class Reference
avatar Class Reference
#include <avatar.h>
Classes
struct daily_calories
Public Member Functions
avatar ()
avatar (const avatar &)=delete
avatar (avatar &&)
~avatar () override
avatar & operator= (const avatar &)=delete
avatar & operator= (avatar &&)
void store (JsonOut &json) const
void load (const JsonObject &data)
void export_as_npc (const cata_path &path)
void serialize (JsonOut &json) const override
void deserialize (const JsonObject &data) override
bool save_map_memory ()
void load_map_memory ()
bool create (character_type type, const std::string &tempname="")
void initialize (character_type type)
void add_profession_items ()
void randomize (bool random_scenario, bool play_now=false)
void randomize_cosmetics ()
bool load_template (const std::string &template_name, pool_type &)
void save_template (const std::string &name, pool_type)
void character_to_template (const std::string &name)
bool is_avatar () const override
avatar * as_avatar () override
const avatar * as_avatar () const override
mfaction_id get_monster_faction () const override
void witness_thievery (item *) override
std::string get_save_id () const
void set_save_id (const std::string &id)
void control_npc (npc &, bool debug=false)
Makes the avatar "take over" the given NPC, while the current avatar character becomes an NPC.
void control_npc_menu (bool debug=false)
Open a menu to choose the NPC to take over.
bool query_yn (const std::string &mes) const override
void toggle_map_memory ()
bool is_map_memory_valid () const
bool should_show_map_memory () const
void prepare_map_memory_region (const tripoint_abs_ms &p1, const tripoint_abs_ms &p2)
const memorized_tile & get_memorized_tile (const tripoint_abs_ms &p) const
void memorize_terrain (const tripoint_abs_ms &p, std::string_view id, int subtile, int rotation)
void memorize_decoration (const tripoint_abs_ms &p, std::string_view id, int subtile, int rotation)
void memorize_symbol (const tripoint_abs_ms &p, char32_t symbol)
void memorize_clear_decoration (const tripoint_abs_ms &p, std::string_view prefix="")
nc_color basic_symbol_color () const override
Creature symbol color.
int print_info (const catacurses::window &w, int vStart, int vLines, int column) const override
Write information about this creature.
void disp_morale ()
Provides the window and detailed morale data.
void disp_medical ()
Opens the medical window.
void reset_stats () override
Resets stats, and applies effects in an idempotent manner.
void reset_all_missions ()
Resets all missions before saving character to template.
std::vector< mission * > get_active_missions () const
std::vector< mission * > get_completed_missions () const
std::vector< mission * > get_failed_missions () const
mission * get_active_mission () const
Returns the mission that is currently active.
tripoint_abs_omt get_active_mission_target () const
Returns the target of the active mission or overmap::invalid_tripoint if there is no active mission.
void set_active_mission (mission &cur_mission)
Set which mission is active.
void on_mission_assignment (mission &new_mission)
Called when a mission has been assigned to the player.
void on_mission_finished (mission &cur_mission)
Called when a mission has been completed or failed.
bool has_mission_id (const mission_type_id &miss_id)
Returns true if character has the mission in their active missions list.
void remove_active_mission (mission &cur_mission)
diary * get_avatar_diary ()
void talk_to (std::unique_ptr< talker > talk_with, bool radio_contact=false, bool is_computer=false, bool is_not_conversation=false)
void disarm (npc &target)
Try to disarm the NPC.
bool wield_contents (item &container, item *internal_item=nullptr, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY)
Try to wield a contained item consuming moves proportional to weapon skill and volume.
void try_to_sleep (const time_duration &dur)
Handles sleep attempts by the player, starts ACT_TRY_SLEEP activity.
void set_location (const tripoint_abs_ms &loc)
bool read (item_location &book, item_location ereader={})
Handles reading effects and returns true if activity started.
bool has_identified (const itype_id &item_id) const override
Note that we've read a book at least once.
void identify (const item &item) override
void clear_identified ()
void clear_nutrition ()
void add_snippet (snippet_id snippet)
bool has_seen_snippet (const snippet_id &snippet) const
const std::set< snippet_id > & get_snippets ()
void longpull (const std::string &name)
Opens the targeting menu to pull a nearby creature towards the character.
void wake_up () override
Removes "sleep" and "lying_down".
void grab (object_type grab_type, const tripoint &grab_point=tripoint_zero)
object_type get_grab_type () const
void vomit ()
Handles player vomiting effects.
bool try_break_relax_gas (const std::string &msg_success, const std::string &msg_failure)
void add_pain_msg (int val, const bodypart_id &bp) const
void steal (npc &target)
Try to steal an item from the NPC's inventory.
void reassign_item (item &it, int invlet)
Reassign letter.
void upgrade_stat_prompt (const character_stat &stat_name)
int free_upgrade_points () const
void power_bionics () override
Generates and handles the UI for player interaction with installed bionics.
void power_mutations () override
bionic * bionic_by_invlet (int ch)
Returns the bionic with the given invlet, or NULL if no bionic has that invlet.
faction * get_faction () const override
bool is_ally (const Character &p) const override
bool is_obeying (const Character &p) const override
bool cant_see (const tripoint &p)
void rebuild_aim_cache ()
void set_movement_mode (const move_mode_id &mode) override
void cycle_move_mode ()
void cycle_move_mode_reverse ()
void reset_move_mode ()
void toggle_run_mode ()
void toggle_crouch_mode ()
void toggle_prone_mode ()
void activate_crouch_mode ()
bool wield (item_location target)
bool wield (item &target) override
Removes currently wielded item (if any) and replaces it with the target item.
bool wield (item &target, int obtain_cost)
item::reload_option select_ammo (const item_location &base, bool prompt=false, bool empty=true) override
Select suitable ammo with which to reload the item.
std::vector< advanced_inv_listitem > get_AIM_inventory (const advanced_inventory_pane &pane, advanced_inv_area &square)
gets the inventory from the avatar that is interactible via advanced inventory management
bool invoke_item (item *, const tripoint &pt, int pre_obtain_moves) override
Asks how to use the item (if it has more than one use_method) and uses it.
bool invoke_item (item *) override
As above two, but with position equal to current position.
bool invoke_item (item *, const std::string &, const tripoint &pt, int pre_obtain_moves=-1) override
As above, but with a pre-selected method.
bool invoke_item (item *, const std::string &) override
monster_visible_info & get_mon_visible ()
const monster_visible_info & get_mon_visible () const
void advance_daily_calories ()
int get_daily_spent_kcal (bool yesterday) const
int get_daily_ingested_kcal (bool yesterday) const
void add_ingested_kcal (int kcal)
void update_cardio_acc () override
void add_spent_calories (int cal) override
void add_gained_calories (int cal) override
void log_activity_level (float level) override
std::string total_daily_calories_string () const
void randomize_hobbies ()
void add_random_hobby (std::vector< profession_id > &choices)
const mood_face_id & character_mood_face (bool clear_cache=false) const
template<typename ... Args>
bool query_yn (const char *const msg, Args &&... args) const
It is supposed to hide the query_yn to simplify player vs.
virtual bool query_yn (const std::string &msg) const=0
virtual bool invoke_item (item *, const tripoint &pt, int pre_obtain_moves=-1)
Asks how to use the item (if it has more than one use_method) and uses it.
virtual bool invoke_item (item *, const std::string &, const tripoint &pt, int pre_obtain_moves=-1)
As above, but with a pre-selected method.
virtual bool invoke_item (item *)
As above two, but with position equal to current position.
virtual bool invoke_item (item *, const std::string &)
Public Member Functions inherited from Character
Character (const Character &)=delete
Character & operator= (const Character &)=delete
~Character () override
void initialize (bool learn_recipes=true)
Character * as_character () override
const Character * as_character () const override
bool is_npc () const override
character_id getID () const
void setID (character_id i, bool force=false)
sets the ID, will only succeed when the current id is not valid allows forcing a -1 id which is required for templates to not throw errors
field_type_id bloodType () const override
field_type_id gibType () const override
bool is_warm () const override
bool in_species (const species_id &spec) const override
int get_str () const
Getters for stats exclusive to characters.
int get_dex () const
int get_per () const
int get_int () const
int get_str_base () const
int get_dex_base () const
int get_per_base () const
int get_int_base () const
int get_str_bonus () const
int get_dex_bonus () const
int get_per_bonus () const
int get_int_bonus () const
int get_arms_power_use () const
Getters for above stats.
int get_legs_power_use () const
float get_arms_stam_mult () const
float get_legs_stam_mult () const
std::vector< speed_bonus_effect > get_speed_bonus_effects () const
int get_speed () const override
int get_enchantment_speed_bonus () const
int get_arm_str () const
int get_eff_per () const override
int ranged_dex_mod () const
int ranged_per_mod () const
void set_str_bonus (int nstr)
Setters for stats exclusive to characters.
void set_dex_bonus (int ndex)
void set_per_bonus (int nper)
void set_int_bonus (int nint)
void mod_str_bonus (int nstr)
void mod_dex_bonus (int ndex)
void mod_per_bonus (int nper)
void mod_int_bonus (int nint)
void mod_speed_bonus (int nspeed, const std::string &desc)
int get_lifestyle () const
Getters for health values exclusive to characters.
int get_daily_health () const
int get_health_tally () const
void mod_livestyle (int nhealthy)
Modifiers for health values exclusive to characters.
void mod_daily_health (int nhealthy_mod, int cap)
void mod_health_tally (int mod)
void set_lifestyle (int nhealthy)
Setters for health values exclusive to characters.
void set_daily_health (int nhealthy_mod)
int get_stored_kcal () const
Getter for need values exclusive to characters.
int get_healthy_kcal () const
float get_kcal_percent () const
int kcal_speed_penalty () const
int get_hunger () const
int get_starvation () const
virtual int get_thirst () const
virtual int get_instant_thirst () const
time_duration get_daily_sleep () const
void mod_daily_sleep (time_duration mod)
void reset_daily_sleep ()
time_duration get_continuous_sleep () const
void mod_continuous_sleep (time_duration mod)
void reset_continuous_sleep ()
int get_sleepiness () const
int get_sleep_deprivation () const
void mod_stored_kcal (int nkcal, bool ignore_weariness=false)
Modifiers for need values exclusive to characters.
void mod_hunger (int nhunger)
void mod_thirst (int nthirst)
void mod_sleepiness (int nsleepiness)
void mod_sleep_deprivation (int nsleep_deprivation)
void set_stored_kcal (int kcal)
Setters for need values exclusive to characters.
void set_hunger (int nhunger)
void set_thirst (int nthirst)
void set_sleepiness (int nsleepiness)
void set_sleepiness (sleepiness_levels nsleepiness)
void set_sleep_deprivation (int nsleep_deprivation)
void gravity_check ()
void stagger ()
void mod_stat (const std::string &stat, float modifier) override
int get_standard_stamina_cost (const item *thrown_item=nullptr) const
int get_fat_to_hp () const
Get bonus to max_hp from excess stored fat.
creature_size get_size () const override
Get size class of character.
void recalculate_size ()
Recalculate size class of character.
std::string disp_name (bool possessive=false, bool capitalize_first=false) const override
Returns either "you" or the player's name.
virtual std::string name_and_maybe_activity () const
std::string skin_name () const override
Returns the name of the player's outer layer, e.g.
void add_msg_if_player (const std::string &msg) const override
void add_msg_if_player (const game_message_params &params, const std::string &msg) const override
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_str) const override
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg) const override
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech) const override
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech) const override
void set_fac_id (const std::string &my_fac_id)
const profession * get_profession () const
std::set< const profession * > get_hobbies () const
bool has_mission_item (int mission_id) const
int effective_dispersion (int dispersion, bool zoom=false) const
int get_character_parallax (bool zoom=false) const
std::vector< aim_type > get_aim_types (const item &gun) const
int point_shooting_limit (const item &gun) const
double fastest_aiming_method_speed (const item &gun, double recoil, const Target_attributes &target_attributes=Target_attributes(), std::optional< std::reference_wrapper< const parallax_cache >> parallax_cache=std::nullopt) const
int most_accurate_aiming_method_limit (const item &gun) const
double aim_factor_from_volume (const item &gun) const
double aim_factor_from_length (const item &gun) const
aim_mods_cache gen_aim_mods_cache (const item &gun) const
float get_modifier (const character_modifier_id &mod, const skill_id &skill=skill_id::NULL_ID()) const
bool has_gun_for_ammo (const ammotype &at) const
Check whether the player has a gun that uses the given type of ammo.
bool has_magazine_for_ammo (const ammotype &at) const
double aim_per_move (const item &gun, double recoil, const Target_attributes &target_attributes=Target_attributes(), std::optional< std::reference_wrapper< const aim_mods_cache >> aim_cache=std::nullopt) const
int get_dodges_left () const
void set_dodges_left (int dodges)
void mod_dodges_left (int mod)
void consume_dodge_attempts ()
ret_val< void > can_try_doge (bool ignore_dodges_left=false) const
float get_stamina_dodge_modifier () const
void on_dodge (Creature *source, float difficulty, float training_level=0.0f) override
Called after the player has successfully dodged an attack.
void on_try_dodge () override
Called after the player has tryed to dodge an attack.
float get_dodge_base () const override
Combat getters.
float dodge_roll () const override
Returns the player's dodge_roll to be compared against an aggressor's hit_roll()
float get_dodge () const override
Returns Creature::get_dodge() modified by any Character effects.
int get_spell_resist () const override
in this case spell resistance is just the spellcraft skill for characters.
bool uncanny_dodge () override
Handles the uncanny dodge bionic and effects, returns true if the player successfully dodges.
bool check_avoid_friendly_fire () const override
float get_hit_base () const override
void tally_organic_size ()
total hitsize of all non cybernetic body parts
float get_cached_organic_size () const
void recalc_limb_energy_usage ()
Called on limb change to update the usage values.
int sight_range (float light_level) const override
Returns the player's sight range.
int unimpaired_range () const
Returns the player maximum vision range factoring in mutations, diseases, and other effects.
bool overmap_los (const tripoint_abs_omt &omt, int sight_points) const
Returns true if overmap tile is within player line-of-sight.
int overmap_sight_range (float light_level) const
Returns the distance the player can see on the overmap.
int clairvoyance () const
Returns the distance the player can see through walls.
bool sight_impaired () const
Returns true if the player has some form of impaired sight.
bool has_alarm_clock () const
Returns true if the player or their vehicle has an alarm clock.
bool has_watch () const
Returns true if the player or their vehicle has a watch.
void action_taken ()
Called after every action, invalidates player caches.
bool is_on_ground () const override
Returns true if the player is knocked over, has broken legs or is lying down.
int swim_speed () const
Returns the player's movecost for swimming across water tiles.
float get_melee () const override
Returns melee skill level, to be used to throttle dodge practice.
void add_miss_reason (const std::string &reason, unsigned int weight)
Adds a reason for why the player would miss a melee attack.
void clear_miss_reasons ()
Clears the list of reasons for why the player would miss a melee attack.
std::string get_miss_reason ()
Returns an explanation for why the player would miss a melee attack.
void regen (int rate_multiplier)
Handles passive regeneration of pain and maybe hp.
ret_val< void > can_takeoff (const item &it, const std::list< item > *res=nullptr)
Check player capable of taking off an item.
std::pair< int, int > gunmod_installation_odds (const item_location &gun, const item &mod) const
void recalc_speed_bonus ()
Calculates the various speed bonuses we will get from mutations, etc.
void set_underwater (bool)
bool is_hallucination () const override
bool is_electrical () const override
bool is_fae () const override
bool is_nether () const override
bool has_mind () const override
stat_mod get_pain_penalty () const
Returns the effect of pain on stats.
int get_lift_str () const
returns players strength adjusted by any traits that affect strength during lifting jobs
bool takeoff (item_location loc, std::list< item > *res=nullptr)
Takes off an item, returning false on fail.
bool takeoff (int pos)
virtual void update_health ()
Handles health fluctuations over time.
void update_body ()
Updates all "biology" by one turn.
void update_body (const time_point &from, const time_point &to)
Updates all "biology" as if time between from and to passed.
void update_stomach (const time_point &from, const time_point &to)
Updates the stomach to give accurate hunger messages.
void update_enchantment_mutations ()
Updates the mutations from enchantments.
bool needs_food () const
Returns true if character needs food, false if character is an NPC with NO_NPC_FOOD set.
void update_needs (int rate_multiplier)
Increases hunger, thirst, sleepiness and stimulants wearing off.
needs_rates calc_needs_rates () const
void calc_sleep_recovery_rate (needs_rates &rates) const
void check_needs_extremes ()
Kills the player if too hungry, stimmed up etc., forces tired player to sleep and prints warnings.
void get_sick (bool is_flu=false)
Handles the chance to be infected by random diseases.
bool is_hibernating () const
Returns if the player has hibernation mutation and is asleep and well fed.
void update_bodytemp ()
Maintains body temperature.
void update_frostbite (const bodypart_id &bp, int FBwindPower, const std::map< bodypart_id, int > &warmth_per_bp)
void temp_equalizer (const bodypart_id &bp1, const bodypart_id &bp2)
Equalizes heat between body parts.
comfort_response_t base_comfort_value (const tripoint_bub_ms &p) const
Rate point's ability to serve as a bed.
int focus_equilibrium_sleepiness_cap (int equilibrium) const
Returns focus equilibrium cap due to sleepiness.
int calc_focus_equilibrium (bool ignore_pain=false) const
Uses morale and other factors to return the character's focus target goto value.
int calc_focus_change () const
Calculates actual focus gain/loss value from focus equilibrium.
void update_mental_focus ()
Uses calc_focus_change to update the character's current focus.
void reset_bonuses () override
Resets the value of all bonus fields to 0.
void reset_stats () override
Resets stats, and applies effects in an idempotent manner.
void reset () override
Handles stat and bonus reset.
int encumb (const bodypart_id &bp) const
Returns ENC provided by armor, etc.
int avg_encumb_of_limb_type (body_part_type::type part_type) const
units::mass get_weight () const override
Returns body weight plus weight of inventory and worn/wielded items.
void print_encumbrance (ui_adaptor &ui, const catacurses::window &win, int line=-1, const item *selected_clothing=nullptr) const
bool is_wearing_power_armor (bool *hasHelmet=nullptr) const
Returns true if the character is wearing power armor.
bool is_wearing_active_power_armor () const
Returns true if the character is wearing active power.
bool is_wearing_active_optcloak () const
Returns true if the player is wearing an active optical cloak.
std::pair< int, int > climate_control_strength () const
Returns strength of any climate control affecting character, for heating and chilling respectively.
std::map< bodypart_id, int > get_wind_resistance (const std::map< bodypart_id, std::vector< const item * >> &clothing_map) const
Returns wind resistance provided by armor, etc.
bool is_blind () const
Returns true if the player isn't able to see.
bool is_invisible () const
int visibility (bool check_color=false, int stillness=0) const
Checks is_invisible() as well as other factors.
float active_light () const
Returns character luminosity based on the brightest active item they are carrying.
bool sees_with_specials (const Creature &critter) const
body_part_set exclusive_flag_coverage (const flag_id &flag) const
Bitset of all the body parts covered only with items with flag (or nothing)
bool move_effects (bool attacking) override
Processes effects which may prevent the Character from moving (bear traps, crushed, etc.).
void wait_effects (bool attacking=false)
bool try_remove_grab (bool attacking=false)
Series of checks to remove effects for waiting or moving.
void try_remove_downed ()
void try_remove_bear_trap ()
void try_remove_lightsnare ()
void try_remove_heavysnare ()
void try_remove_crushed ()
void try_remove_webs ()
void try_remove_impeding_effect ()
bool can_escape_trap (int difficulty, bool manip) const
bool movement_mode_is (const move_mode_id &mode) const
Check against the character's current movement mode.
move_mode_id current_movement_mode () const
bool is_running () const
bool is_walking () const
bool is_crouching () const
bool is_prone () const
int footstep_sound () const
int clatter_sound () const
void make_footstep_noise () const
void make_clatter_sound () const
bool can_switch_to (const move_mode_id &mode) const
steed_type get_steed_type () const
int get_instability_per_category (const mutation_category_id &categ) const
Generates an integer based on how many times we've gained non-negative mutations.
void expose_to_disease (const diseasetype_id &dis_type)
Determine if character is susceptible to dis_type and if so apply the symptoms.
void process_turn () override
Handles end-of-turn processing.
void recalc_hp ()
Recalculates HP after a change to max strength or enchantment.
void update_body_wetness (const w_point &weather)
Maintains body wetness and handles the rate at which the player dries.
void recalc_sight_limits ()
Modifies the player's sight values Must be called when any of the following change: This must be called when any of the following change:
float get_vision_threshold (float light_level) const
Returns the apparent light level at which the player can see.
void flag_encumbrance ()
Flag encumbrance for updating.
void check_item_encumbrance_flag ()
Checks worn items for the "RESET_ENCUMBRANCE" flag, which indicates that encumbrance may have changed and require recalculating.
bool natural_attack_restricted_on (const bodypart_id &bp) const
Returns true if the character is wearing something on the entered body_part, ignoring items with the ALLOWS_NATURAL_ATTACKS flag.
bool natural_attack_restricted_on (const sub_bodypart_id &bp) const
bool is_quiet () const
Returns true if the player has quiet melee attacks.
bool block_hit (Creature *source, bodypart_id &bp_hit, damage_instance &dam) override
Checks for valid block abilities and reduces damage accordingly.
item_location best_shield ()
Returns the best item for blocking with.
bool handle_melee_wear (item_location shield, float wear_multiplier=1.0f)
Calculates melee weapon wear-and-tear through use, returns true if item is destroyed.
matec_id pick_technique (Creature &t, const item_location &weap, bool crit, bool dodge_counter, bool block_counter, const std::vector< matec_id > &blacklist={})
Returns a random valid technique.
std::vector< matec_id > evaluate_techniques (Creature &t, const item_location &weap, bool crit=false, bool dodge_counter=false, bool block_counter=false, const std::vector< matec_id > &blacklist={})
void perform_technique (const ma_technique &technique, Creature &t, damage_instance &di, int &move_cost, item_location &cur_weapon)
damage_instance modify_damage_dealt_with_enchantments (const damage_instance &dam) const override
bool melee_attack (Creature &t, bool allow_special, const matec_id &force_technique, bool allow_unarmed=true, int forced_movecost=-1)
Sets up a melee attack and handles melee attack function calls.
bool melee_attack_abstract (Creature &t, bool allow_special, const matec_id &force_technique, bool allow_unarmed=true, int forced_movecost=-1)
void reach_attack (const tripoint &p, int forced_movecost=-1)
Handles reach melee attacks.
bool melee_attack (Creature &t, bool allow_special)
Calls the to other melee_attack function with an empty technique id (meaning no specific technique should be used).
std::string melee_special_effects (Creature &t, damage_instance &d, item &weap)
Handles combat effects, returns a string of any valid combat effect messages.
void perform_special_attacks (Creature &t, dealt_damage_instance &dealt_dam)
Performs special attacks and their effects (poisonous, stinger, etc.)
std::vector< special_attack > mutation_attacks (Creature &t) const
Returns a vector of valid mutation attacks.
float bonus_damage (bool random) const
Returns the bonus bashing damage the player deals based on their stats.
float get_melee_hit_base () const
Returns weapon skill.
float hit_roll () const override
Returns the player's basic hit roll that is compared to the target's dodge roll.
double crit_chance (float roll_hit, float target_dodge, const item &weap) const
Returns the chance to critical given a hit roll and target's dodge roll.
bool scored_crit (float target_dodge, const item &weap) const
Returns true if the player scores a critical hit.
int attack_speed (const item &weap) const
Returns cost (in moves) of attacking with given item (no modifiers, like stuck)
int get_base_melee_stamina_cost (const item *weap=nullptr) const
Returns cost (in stamina) of attacking with given item, or wielded item if nullptr (no modifiers, worst possible is -50)
int get_total_melee_stamina_cost (const item *weap=nullptr) const
Returns total cost (in stamina) of attacking with given item, or wielded item if nullptr (modified by skill and walk/crouch/prone, worst possible is -50)
float get_hit_weapon (const item &weap) const
Gets melee accuracy component from weapon+skills.
bool can_attack_high () const override
Check if we can attack upper limbs.
double weapon_value (const item &weap, int ammo=10) const
NPC-related item rating functions.
double gun_value (const item &weap, int ammo=10) const
double melee_value (const item &weap) const
double unarmed_value () const
dispersion_sources get_weapon_dispersion (const item &obj) const
Returns a weapon's modified dispersion value.
void roll_all_damage (bool crit, damage_instance &di, bool average, const item &weap, const std::string &attack_vector, const Creature *target, const bodypart_id &bp) const
Adds all 3 types of physical damage to instance.
void roll_damage (const damage_type_id &dt, bool crit, damage_instance &di, bool average, const item &weap, const std::string &attack_vector, float crit_mod) const
bool is_dead_state () const override
Returns true if the player should be dead.
void set_part_hp_cur (const bodypart_id &id, int set) override
void mod_part_hp_cur (const bodypart_id &id, int set) override
void calc_all_parts_hp (float hp_mod=0.0, float hp_adjust=0.0, int str_max=0, int dex_max=0, int per_max=0, int int_max=0, int healthy_mod=0, int fat_to_max_hp=0)
bool is_stealthy () const
Returns true if the player has stealthy movement.
bool can_melee () const
Returns true if the current martial art works with the player's current weapon.
float stability_roll () const override
Returns value of player's stable footing.
bool can_autolearn (const matype_id &ma_id) const
Returns true if the player can learn the entered martial art.
bool practice (const skill_id &id, int amount, int cap=99, bool suppress_warning=false)
This handles giving xp for a skill.
void handle_skill_warning (const skill_id &id, bool force_warning=false)
This handles warning the player that there current activity will not give them xp.
ret_val< void > can_wield (const item &it) const
Check player capable of wielding an item.
bool unwield ()
std::string weapname () const
Get the formatted name of the currently wielded item (if any) with current gun mode (if gun)
std::string weapname_simple () const
Get the formatted name of the currently wielded item (if any) without current gun mode and ammo.
std::string weapname_mode () const
Get the formatted current gun mode (if gun)
std::string weapname_ammo () const
Get the formatted current ammo (if gun)
void on_hit (Creature *source, bodypart_id bp_hit, float difficulty=INT_MIN, dealt_projectile_attack const *proj=nullptr) override
Handles special defenses from melee attack that hit us (source can be null)
void did_hit (Creature &target)
void apply_damage (Creature *source, bodypart_id hurt, int dam, bool bypass_med=false) override
Actually hurt the player, hurts a body_part directly, no armor reduction.
dealt_damage_instance deal_damage (Creature *source, bodypart_id bp, const damage_instance &d, const weakpoint_attack &attack=weakpoint_attack()) override
Calls Creature::deal_damage and handles damaged effects (waking up, etc.)
int reduce_healing_effect (const efftype_id &eff_id, int remove_med, const bodypart_id &hurt)
Reduce healing effect intensity, return initial intensity of the effect.
void cough (bool harmful=false, int loudness=4)
void passive_absorb_hit (const bodypart_id &bp, damage_unit &du) const
Check for relevant passive, non-clothing that can absorb damage, and reduce by specified damage unit.
const weakpoint * absorb_hit (const weakpoint_attack &attack, const bodypart_id &bp, damage_instance &dam) override
Runs through all bionics and armor on a part and reduces damage through their armor_absorb.
float melee_weakpoint_skill (const item &weapon) const
The character's skill in hitting a weakpoint.
float ranged_weakpoint_skill (const item &weapon) const
float throw_weakpoint_skill () const
bool armor_absorb (damage_unit &du, item &armor, const bodypart_id &bp, int roll) const
Reduces and mutates du, prints messages about armor taking damage.
bool armor_absorb (damage_unit &du, item &armor, const bodypart_id &bp, const sub_bodypart_id &sbp, int roll) const
Reduces and mutates du, prints messages about armor taking damage.
bool ablative_armor_absorb (damage_unit &du, item &armor, const sub_bodypart_id &bp, int roll)
Reduces and mutates du, prints messages about armor taking damage.
void describe_damage (damage_unit &du, item &armor) const
float bionic_armor_bonus (const bodypart_id &bp, const damage_type_id &dt) const
Check for passive bionics that provide armor, and returns the armor bonus This is called from player::passive_absorb_hit.
int mabuff_armor_bonus (const damage_type_id &type) const
Returns the armor bonus against given type from martial arts buffs.
trait_id random_good_trait ()
Returns the id of a random starting trait that costs >= 0 points.
trait_id random_bad_trait ()
Returns the id of a random starting trait that costs < 0 points.
trait_id get_random_trait (const std::function< bool(const mutation_branch &)> &func)
Returns the id of a random trait matching the given predicate.
void randomize_cosmetic_trait (const std::string &mutation_type)
bool has_conflicting_trait (const trait_id &flag) const
Returns true if the player has a conflicting trait to the entered trait Uses has_opposite_trait(), has_lower_trait(), and has_higher_trait() to determine conflicts.
std::unordered_set< trait_id > get_conflicting_traits (const trait_id &flag) const
Returns all player's traits conflicting with the entered trait.
bool has_lower_trait (const trait_id &flag) const
Returns true if the player has a trait which upgrades into the entered trait.
std::unordered_set< trait_id > get_lower_traits (const trait_id &flag) const
Returns player's traits which upgrade into the entered trait.
bool has_replacement_trait (const trait_id &flag) const
Returns true if the player has a trait which is a replacement of the entered trait.
std::unordered_set< trait_id > get_replacement_traits (const trait_id &flag) const
Returns player's traits which replace the entered trait.
bool has_addition_trait (const trait_id &flag) const
Returns true if the player has a trait which adds to the entered trait.
std::unordered_set< trait_id > get_addition_traits (const trait_id &flag) const
Returns player's traits which add to the entered trait.
bool has_same_type_trait (const trait_id &flag) const
Returns true if the player has a trait that shares a type with the entered trait.
std::unordered_set< trait_id > get_same_type_traits (const trait_id &flag) const
Returns player's traits that share a type with the entered trait.
bool purifiable (const trait_id &flag) const
Returns true if the entered trait may be purified away Defaults to true.
std::string get_category_dream (const mutation_category_id &cat, int strength) const
Returns a dream's description selected randomly from the player's highest mutation category.
bool has_trait (const trait_id &b) const override
Returns true if the player has the entered trait.
bool has_trait_variant (const trait_and_var &) const
Returns true if the player has the entered trait with the desired variant.
bool has_base_trait (const trait_id &b) const
Returns true if the player has the entered starting trait.
bool has_trait_flag (const json_character_flag &b) const
Returns true if player has a trait with a flag.
bool has_bionic_with_flag (const json_character_flag &flag) const
Returns true if player has a bionic with a flag.
bool has_bodypart_with_flag (const json_character_flag &flag) const
Returns true if the player has any bodypart with a flag.
int count_trait_flag (const json_character_flag &b) const
Returns count of traits with a flag.
int count_bionic_with_flag (const json_character_flag &flag) const
Returns count of bionics with a flag.
int count_bodypart_with_flag (const json_character_flag &flag) const
Returns count of bodyparts with a flag.
bool has_flag (const json_character_flag &flag) const
Returns true if player has a trait, bionic, effect, bodypart, or martial arts buff with a flag.
int count_flag (const json_character_flag &flag) const
Returns the count of traits, bionics, effects, bodyparts, and martial arts buffs with a flag.
trait_id trait_by_invlet (int ch) const
Returns the trait id with the given invlet, or an empty string if no trait has that invlet.
void toggle_trait (const trait_id &, const std::string &="")
Toggles a trait on the player and in their mutation list.
void set_mutations (const std::vector< trait_id > &traits)
Add or removes a mutation on the player, but does not trigger mutation loss/gain effects.
void set_mutation (const trait_id &, const mutation_variant *=nullptr)
void set_mut_variant (const trait_id &, const mutation_variant *)
Switches the variant of the given mutation, if the player has that mutation.
void do_mutation_updates ()
void unset_mutation (const trait_id &)
void switch_mutations (const trait_id &switched, const trait_id &target, bool start_powered, bool safe=false)
Unset switched mutation and set target mutation instead, if safe mutates towards the target mutation.
bool can_power_mutation (const trait_id &mut) const
bool can_interface_armor () const
Check whether player has a bionic power armor interface.
void mutation_reflex_trigger (const trait_id &mut)
Trigger reflex activation if the mutation has one.
void activate_mutation (const trait_id &mutation)
void deactivate_mutation (const trait_id &mut)
bool can_mount (const monster &critter) const
void mount_creature (monster &z)
bool cant_do_mounted (bool msg=true) const
bool is_mounted () const
bool check_mount_will_move (const tripoint &dest_loc)
bool check_mount_is_spooked ()
void dismount ()
void forced_dismount ()
bool move_in_vehicle (Creature *c, const tripoint &dest_loc) const
Attempt to enter a tile in a vehicle.
bool is_deaf () const
bool is_mute () const
float get_limb_score (const limb_score_id &score, const body_part_type::type &bp=body_part_type::type::num_types, int override_encumb=-1, int override_wounds=-1) const
float manipulator_score (const std::map< bodypart_str_id, bodypart > &body, body_part_type::type type, int override_encumb, int override_wounds) const
bool has_min_manipulators () const
bool has_two_arms_lifting () const
Returns true if the character has two functioning arms.
std::set< matec_id > get_limb_techs () const
int get_working_arm_count () const
bool enough_working_legs () const
Returns true if enough of your legs are working Currently requires all, new morphologies could be different.
int get_working_leg_count () const
Returns the number of functioning legs.
bool is_limb_broken (const bodypart_id &limb) const
Returns true if the limb is broken.
bool can_run () const
source of truth of whether a Character can run
void hurtall (int dam, Creature *source, bool disturb=true)
Hurts all body parts for dam, no armor reduction.
int hitall (int dam, int vary, Creature *source)
Harms all body parts for dam, with armor reduction.
void on_hurt (Creature *source, bool disturb=true)
Handles effects that happen when the player is damaged and aware of the fact.
void heal_bp (bodypart_id bp, int dam) override
Heals a body_part for dam.
void heal (const bodypart_id &healed, int dam)
Heals an part for dam.
void healall (int dam)
Heals all body parts for dam.
std::vector< skill_id > skills_offered_to (const Character *you) const
std::vector< proficiency_id > proficiencies_offered_to (const Character *guy) const
Proficiencies we know that the character doesn't.
std::vector< matype_id > styles_offered_to (const Character *you) const
Martial art styles that we known, but the player p doesn't.
std::vector< spell_id > spells_offered_to (const Character *you) const
Spells that the NPC knows but that the player p doesn't.
int calc_spell_training_cost (bool knows, int difficulty, int level) const
void migrate_items_to_storage (bool disintegrate)
used for profession spawning and save migration for nested containers.
bodypart_id body_window (const std::string &menu_header, bool show_all, bool precise, int normal_bonus, int head_bonus, int torso_bonus, int bleed, float bite, float infect, float bandage_power, float disinfectant_power) const
Displays menu with body part hp, optionally with hp estimation after healing.
bool made_of (const material_id &m) const override
bool made_of_any (const std::set< material_id > &ms) const override
void calc_encumbrance ()
Recalculate encumbrance for all body parts.
void calc_discomfort ()
Calculate any discomfort your current clothes are causing.
void calc_encumbrance (const item &new_item)
Recalculate encumbrance for all body parts as if new_item was also worn.
void recalculate_bodyparts ()
void recalculate_enchantment_cache ()
double calculate_by_enchantment (double modify, enchant_vals::mod value, bool round_output=false) const
bool has_mabuff (const mabuff_id &buff_id) const
Returns true if the player has any martial arts buffs attached.
bool has_grab_break_tec () const override
Returns true if the player has a grab breaking technique available.
float mabuff_tohit_bonus () const
Returns the to hit bonus from martial arts buffs.
float mabuff_critical_hit_chance_bonus () const
Returns the critical hit chance bonus from martial arts buffs.
float mabuff_dodge_bonus () const
Returns the dodge bonus from martial arts buffs.
int mabuff_block_effectiveness_bonus () const
Returns the blocking effectiveness bonus from martial arts buffs.
int mabuff_block_bonus () const
Returns the block bonus from martial arts buffs.
int mabuff_speed_bonus () const
Returns the speed bonus from martial arts buffs.
int mabuff_arpen_bonus (const damage_type_id &type) const
Returns the arpen bonus from martial arts buffs.
float mabuff_damage_mult (const damage_type_id &type) const
Returns the damage multiplier to given type from martial arts buffs.
int mabuff_damage_bonus (const damage_type_id &type) const
Returns the flat damage bonus to given type from martial arts buffs, applied after the multiplier.
int mabuff_attack_cost_penalty () const
Returns the flat penalty to move cost of attacks.
float mabuff_attack_cost_mult () const
Returns the multiplier on move cost of attacks.
bool has_mabuff_flag (const json_character_flag &flag) const
Returns true if player has a MA buff with a flag.
int count_mabuff_flag (const json_character_flag &flag) const
void mutation_effect (const trait_id &mut, bool worn_destroyed_override)
Handles things like destruction of armor, etc.
void mutation_loss_effect (const trait_id &mut)
Handles what happens when you lose a mutation.
bool has_active_mutation (const trait_id &b) const
time_duration get_cost_timer (const trait_id &mut_id) const
void set_cost_timer (const trait_id &mut, time_duration set)
void mod_cost_timer (const trait_id &mut, time_duration mod)
void mutate (const int &true_random_chance, bool use_vitamins)
Picks a random valid mutation and gives it to the Character, possibly removing/changing others along the way.
void mutate ()
bool mutation_ok (const trait_id &mutation, bool allow_good, bool allow_bad, bool allow_neutral, const vitamin_id &mut_vit) const
Returns true if the player doesn't have the mutation or a conflicting one and it complies with the allowed typing.
bool mutation_ok (const trait_id &mutation, bool allow_good, bool allow_bad, bool allow_neutral) const
bool roll_bad_mutation (const mutation_category_id &categ) const
Roll, based on category and total mutations in/out of it, whether next mutation should be good or bad.
bool mutation_selector (const std::vector< trait_id > &prospective_traits, const mutation_category_id &cat, const bool &use_vitamins)
Opens a menu which allows players to choose from a list of mutations.
void mutate_category (const mutation_category_id &mut_cat, bool use_vitamins, bool true_random=false)
Picks a random valid mutation in a category and mutate_towards() it.
void mutate_category (const mutation_category_id &mut_cat)
bool mutate_towards (std::vector< trait_id > muts, const mutation_category_id &mut_cat, int num_tries=INT_MAX, bool use_vitamins=true, bool removed_base_trait=false)
Mutates toward one of the given mutations, upgrading or removing conflicts if necessary.
bool mutate_towards (const trait_id &mut, const mutation_category_id &mut_cat, const mutation_variant *chosen_var=nullptr, bool use_vitamins=true, bool removed_base_trait=false)
Mutates toward the entered mutation, upgrading or removing conflicts if necessary.
bool mutate_towards (const trait_id &mut, const mutation_variant *chosen_var=nullptr)
void remove_mutation (const trait_id &mut, bool silent=false)
Removes a mutation, downgrading to the previous level if possible.
bool has_child_flag (const trait_id &flag) const
Returns true if the player has the entered mutation child flag.
void remove_child_flag (const trait_id &flag)
Removes the mutation's child flag from the player's list.
void test_crossing_threshold (const mutation_category_id &mutation_category)
Try to cross The Threshold.
int mutation_height (const trait_id &mut) const
Returns how many steps are required to reach a mutation.
void calc_mutation_levels ()
Recalculates mutation_category_level[] values for the player.
weighted_int_list< mutation_category_id > get_vitamin_weighted_categories () const
Returns a weighted list of mutation categories based on blood vitamin levels.
void drench_mut_calc ()
Recalculates mutation drench protection for all bodyparts (ignored/good/neutral stats)
bool is_category_allowed (const std::vector< mutation_category_id > &category) const
Returns true if this category of mutation is allowed.
bool is_category_allowed (const mutation_category_id &category) const
bool can_use_heal_item (const item &med) const
Check for mutation disallowing the use of an healing item.
bool can_install_cbm_on_bp (const std::vector< bodypart_id > &bps) const
resistances mutation_armor (bodypart_id bp) const
Returns resistances on a body part provided by mutations.
float mutation_armor (bodypart_id bp, const damage_type_id &dt) const
float mutation_armor (bodypart_id bp, const damage_unit &du) const
void give_all_mutations (const mutation_category_trait &category, bool include_postthresh=false)
gives every mutation in a category, optionally including post-thresh mutations
void unset_all_mutations ()
unsets all mutations
bool activate_bionic (bionic &bio, bool eff_only=false, bool *close_bionics_ui=nullptr)
Handles bionic activation effects of the entered bionic, returns if anything activated.
std::vector< bionic_id > get_bionics () const
std::vector< const item * > get_pseudo_items () const
void invalidate_pseudo_items ()
void update_last_bionic_uid () const
Finds the highest UID for installed bionics and caches the next valid UID.
bionic_uid generate_bionic_uid () const
Returns the next valid UID for a bionic installation.
bool has_bionic (const bionic_id &b) const
Returns true if the player has the entered bionic id.
bool has_active_bionic (const bionic_id &b) const
Returns true if the player has the entered bionic id and it is powered on.
bool has_any_bionic () const
Returns true if the player has any bionic.
std::vector< bionic_id > get_bionic_fueled_with_muscle () const
Return bionic_id of bionics able to use it as fuel.
std::vector< bionic_id > get_fueled_bionics () const
Return bionic_id of fueled bionics.
bionic_id get_remote_fueled_bionic () const
Returns bionic_id of first remote fueled bionic found.
std::vector< item * > get_bionic_fuels (const bionic_id &bio)
Return list of available fuel sources that are not empty for this bionic.
std::vector< item * > get_cable_ups ()
Returns not-empty UPS connected to cable charger bionic.
std::vector< item * > get_cable_solar ()
Returns solar items connected to cable charger bionic.
std::vector< vehicle * > get_cable_vehicle () const
Returns vehicles connected to cable charger bionic.
bool is_using_bionic_weapon () const
bionic_uid get_weapon_bionic_uid () const
void process_bionic (bionic &bio)
Handles bionic effects over time of the entered bionic.
ret_val< void > can_deactivate_bionic (bionic &bio, bool eff_only=false) const
Checks if bionic can be deactivated (e.g.
bool deactivate_bionic (bionic &bio, bool eff_only=false)
Handles bionic deactivation effects of the entered bionic, returns if anything deactivated.
void force_bionic_deactivation (bionic &bio)
int num_bionics () const
Returns the size of my_bionics[].
bionic & bionic_at_index (int i)
Returns the bionic at a given index in my_bionics[].
void clear_bionics ()
Remove all bionics.
int get_used_bionics_slots (const bodypart_id &bp) const
int get_total_bionics_slots (const bodypart_id &bp) const
int get_free_bionics_slots (const bodypart_id &bp) const
bool has_enough_anesth (const itype &cbm, Character &patient) const
Has enough anesthetic for surgery.
bool has_enough_anesth (const itype &cbm) const
void consume_anesth_requirement (const itype &cbm, Character &patient)
bool has_installation_requirement (const bionic_id &bid) const
Has the required equipment for manual installation.
void consume_installation_requirement (const bionic_id &bid)
void introduce_into_anesthesia (const time_duration &duration, Character &installer, bool needs_anesthesia)
Handles process of introducing patient into anesthesia during Autodoc operations.
std::optional< bionic * > find_bionic_by_type (const bionic_id &b) const
Finds the first bionic instance that matches the bionic_id.
std::optional< bionic * > find_bionic_by_uid (bionic_uid bio_uid) const
Finds the bionic with specified UID.
void remove_bionic (const bionic &bio)
Removes a bionic from my_bionics[].
bionic_uid add_bionic (const bionic_id &b, bionic_uid parent_uid=0, bool suppress_debug=false)
Adds a bionic to my_bionics[].
float env_surgery_bonus (int radius) const
Calculate skill bonus from tiles in radius.
float bionics_adjusted_skill (bool autodoc, int skill_level=-1) const
Calculate skill for (un)installing bionics.
int bionics_pl_skill (bool autodoc, int skill_level=-1) const
Calculate non adjusted skill for (un)installing bionics.
bool can_install_bionics (const itype &type, Character &installer, bool autodoc=false, int skill_level=-1) const
Is the installation possible.
ret_val< void > is_installable (const item *it, bool by_autodoc) const
Is this bionic elligible to be installed in the player?
std::map< bodypart_id, int > bionic_installation_issues (const bionic_id &bioid) const
bool install_bionics (const itype &type, Character &installer, bool autodoc=false, int skill_level=-1)
Initialize all the values needed to start the operation player_activity.
void perform_install (const bionic_id &bid, bionic_uid upbio_uid, int difficulty, int success, int pl_skill, const std::string &installer_name, const std::vector< trait_id > &trait_to_rem, const tripoint &patient_pos)
Success or failure of installation happens here.
void bionics_install_failure (const bionic_id &bid, const std::string &installer, int difficulty, int success, float adjusted_skill, const tripoint &patient_pos)
bool wield_contents (item &container, item *internal_item=nullptr, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY)
Try to wield a contained item consuming moves proportional to weapon skill and volume.
void use (int inventory_position)
Uses a tool.
void use (item_location loc, int pre_obtain_moves=-1, std::string const &method={})
Uses a tool at location.
void use_wielded ()
Uses the current wielded weapon.
std::optional< std::list< item >::iterator > wear (int pos, bool interactive=true)
Wear item; returns false on fail.
std::optional< std::list< item >::iterator > wear (item_location item_wear, bool interactive=true)
Wear item; returns false on fail.
trinary consume (item_location loc, bool force=false)
Used for eating object at a location.
trinary consume (item &target, bool force=false)
Used for eating a particular item that doesn't need to be in inventory.
void store (item &container, item &put, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY, pocket_type pk_type=pocket_type::CONTAINER, bool check_best_pkt=false)
Stores an item inside another consuming moves proportional to weapon skill and volume.
void store (item_pocket *pocket, item &put, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY)
bool can_uninstall_bionic (const bionic &bio, Character &installer, bool autodoc=false, int skill_level=-1) const
Is The uninstallation possible.
bool uninstall_bionic (const bionic &bio, Character &installer, bool autodoc=false, int skill_level=-1)
Initialize all the values needed to start the operation player_activity.
void perform_uninstall (const bionic &bio, int difficulty, int success, int pl_skill)
Success or failure of removal happens here.
void bionics_uninstall_failure (int difficulty, int success, float adjusted_skill)
When a player fails the surgery.
void roll_critical_bionics_failure (const bodypart_id &bp)
When a critical failure occurs.
bool uninstall_bionic (const bionic &bio, monster &installer, Character &patient, float adjusted_skill)
Used by monster to perform surgery.
void bionics_uninstall_failure (monster &installer, Character &patient, int difficulty, int success, float adjusted_skill)
When a monster fails the surgery.
void on_worn_item_transform (const item &old_it, const item &new_it)
bool gunmod_remove (item &gun, item &mod)
Starts activity to remove gunmod after unloading any contained ammo.
void gunmod_add (item &gun, item &mod)
Starts activity to install gunmod having warned user about any risk of failure or irremovable mods s.
void toolmod_add (item_location tool, item_location mod)
Starts activity to install toolmod.
void mend_item (item_location &&obj, bool interactive=true)
Attempt to mend an item (fix any current faults)
bool list_ammo (const item_location &base, std::vector< item::reload_option > &ammo_list, bool empty=true) const
void process_items ()
void leak_items ()
void search_surroundings ()
Search surrounding squares for traps (and maybe other things in the future).
void heat_emission (const bionic &bio, units::energy fuel_energy)
Handle heat from exothermic power generation.
float get_effective_efficiency (const bionic &bio, float fuel_efficiency) const
Applies modifier to fuel_efficiency and returns the resulting efficiency.
units::energy get_power_level () const
units::energy get_max_power_level () const
void mod_power_level (const units::energy &npower)
void mod_max_power_level_modifier (const units::energy &npower_max)
void set_power_level (const units::energy &npower)
void set_max_power_level (const units::energy &capacity)
void set_max_power_level_modifier (const units::energy &capacity)
void update_bionic_power_capacity ()
bool is_max_power () const
bool has_power () const
bool has_max_power () const
bool enough_power_for (const bionic_id &bid) const
void disp_info (bool customize_character=false)
Handles and displays detailed character info for the '@' screen.
void conduct_blood_analysis ()
bool is_worn (const item &thing) const
bool is_worn_module (const item &thing) const
virtual bool dispose_item (item_location &&obj, const std::string &prompt=std::string())
Drop, wear, stash or otherwise try to dispose of an item consuming appropriate moves.
bool consume_charges (item &used, int qty)
Consume charges of a tool or comestible item, potentially destroying it in the process.
item reduce_charges (item *it, int quantity)
Remove charges from a specific item.
int item_handling_cost (const item &it, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY, int charges_in_it=-1, bool bulk_cost=false) const
Calculate (but do not deduct) the number of moves required when handling (e.g.
int item_store_cost (const item &it, const item &container, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY) const
Calculate (but do not deduct) the number of moves required when storing an item in a container.
int item_retrieve_cost (const item &it, const item &container, bool penalties=true, int base_cost=INVENTORY_HANDLING_PENALTY) const
Calculate (but do not deduct) the number of moves required when drawing a weapon from an holster or sheathe.
int item_wear_cost (const item &it) const
Calculate (but do not deduct) the number of moves required to wear an item.
std::optional< std::list< item >::iterator > wear_item (const item &to_wear, bool interactive=true, bool do_calc_encumbrance=true)
Wear item; returns nullopt on fail, or pointer to newly worn item on success.
int amount_worn (const itype_id &id) const
Returns the amount of item ‘type’ that is currently worn.
int count_softwares (const itype_id &id)
Returns the amount of software ‘type’ that are in the inventory.
std::vector< item_location > nearby (const std::function< bool(const item *, const item *)> &func, int radius=1) const
Returns nearby items which match the provided predicate.
std::list< item > remove_worn_items_with (const std::function< bool(item &)> &filter)
Similar to remove_items_with, but considers only worn items and not their content (item::contents is not checked).
void clear_worn ()
std::vector< item_location > all_items_loc ()
std::vector< item_location > top_items_loc ()
item * invlet_to_item (int invlet) const
Return the item pointer of the item with given invlet, return nullptr if the player does not have such an item with that invlet.
item & i_at (int position)
const item & i_at (int position) const
int get_item_position (const item *it) const
Returns the item position (suitable for i_at or similar) of a specific item.
item_location used_weapon () const
Returns a reference to the item which will be used to make attacks.
item_location used_weapon ()
item_location i_add (item it, bool should_stack=true, const item *avoid=nullptr, const item *original_inventory_item=nullptr, bool allow_drop=true, bool allow_wield=true, bool ignore_pkt_settings=false)
Adds the item to the character's worn items or wields it, or prompts if the Character cannot pick it up.
item_location i_add (item it, int &copies_remaining, bool should_stack=true, const item *avoid=nullptr, const item *original_inventory_item=nullptr, bool allow_drop=true, bool allow_wield=true, bool ignore_pkt_settings=false)
item_location try_add (item it, const item *avoid=nullptr, const item *original_inventory_item=nullptr, bool allow_wield=true, bool ignore_pkt_settings=false)
tries to add to the character's inventory without a popup.
item_location try_add (item it, int &copies_remaining, const item *avoid=nullptr, const item *original_inventory_item=nullptr, bool allow_wield=true, bool ignore_pkt_settings=false)
ret_val< item_location > i_add_or_fill (item &it, bool should_stack=true, const item *avoid=nullptr, const item *original_inventory_item=nullptr, bool allow_drop=true, bool allow_wield=true, bool ignore_pkt_settings=false)
item i_rem (const item *it)
Remove a specific item from player possession.
void i_rem_keep_contents (const item *it)
bool i_add_or_drop (item &it, int qty=1, const item *avoid=nullptr, const item *original_inventory_item=nullptr)
Sets invlet and adds to inventory if possible, drops otherwise, returns true if either succeeded.
bool i_drop_at (item &it, int qty=1)
Drops items at player location An optional qty can be provided (and will perform better than separate calls).
void handle_contents_changed (const std::vector< item_location > &containers)
Check any already unsealed pockets in items pointed to by containers and propagate the unsealed status through the container tree.
std::bitset< std::numeric_limits< char >::max()> allocated_invlets () const
Only use for UI things.
bool has_active_item (const itype_id &id) const
Whether the player carries an active item of the given item type.
item remove_weapon ()
void remove_mission_items (int mission_id)
std::vector< const item * > get_ammo (const ammotype &at) const
Returns the items that are ammo and have the matching ammo type.
std::vector< item_location > find_ammo (const item &obj, bool empty=true, int radius=1) const
Searches for ammo or magazines that can be used to reload obj.
std::vector< item_location > find_reloadables ()
Searches for weapons and magazines that can be reloaded.
int ammo_count_for (const item_location &gun) const
Counts ammo and UPS charges (lower of) for a given gun on the character.
bool can_reload (const item &it, const item *ammo=nullptr) const
Whether a tool or gun is potentially reloadable (optionally considering a specific ammo)
hint_rating rate_action_reload (const item &it) const
Same as Character::can_reload, but checks for attached gunmods as well.
hint_rating rate_action_unload (const item &it) const
Whether a tool or a gun can be unloaded.
hint_rating rate_action_insert (const item_location &loc) const
bool add_or_drop_with_msg (item &it, bool unloading=false, const item *avoid=nullptr, const item *original_inventory_item=nullptr)
So far only called by unload() from game.cpp @avoid - do not put @it into @avoid @original_inventory_item set if the item was already in the characters inventory (wielded, worn, in different pocket) and is being moved.
bool unload (item_location &loc, bool bypass_activity=false, const item_location &new_container=item_location::nowhere)
Unload item.
int item_reload_cost (const item &it, const item &ammo, int qty) const
Calculate (but do not deduct) the number of moves required to reload an item with specified quantity of ammo.
projectile thrown_item_projectile (const item &thrown) const
int thrown_item_adjusted_damage (const item &thrown) const
int thrown_item_total_damage_raw (const item &thrown) const
int throw_range (const item &) const
Maximum thrown range with a given item, taking all active effects into account.
int throwing_dispersion (const item &to_throw, Creature *critter=nullptr, bool is_blind_throw=false) const
Dispersion of a thrown item, against a given target, taking into account whether or not the throw was blind.
int throw_dispersion_per_dodge (bool add_encumbrance=true) const
How much dispersion does one point of target's dodge add when throwing at said target?
bool unarmed_attack () const
True if unarmed.
units::mass best_nearby_lifting_assist () const
Checks for items, tools, and vehicles with the Lifting quality near the character returning the largest weight liftable by an item in range.
units::mass best_nearby_lifting_assist (const tripoint &world_pos) const
Alternate version if you need to specify a different origin point for nearby vehicle sources of lifting used for operations on distant objects (e.g.
std::vector< item * > inv_dump ()
std::vector< const item * > inv_dump () const
units::mass weight_carried () const
units::volume volume_carried () const
units::length max_single_item_length () const
units::volume max_single_item_volume () const
units::mass weight_carried_with_tweaks (const item_tweaks &tweaks) const
units::mass weight_carried_with_tweaks (const std::vector< std::pair< item_location, int >> &locations) const
units::volume volume_carried_with_tweaks (const item_tweaks &tweaks) const
units::volume volume_carried_with_tweaks (const std::vector< std::pair< item_location, int >> &locations) const
units::mass weight_capacity () const override
units::volume volume_capacity () const
units::volume volume_capacity_with_tweaks (const item_tweaks &tweaks) const
units::volume volume_capacity_with_tweaks (const std::vector< std::pair< item_location, int >> &locations) const
units::volume free_space () const
units::mass free_weight_capacity () const
units::volume holster_volume () const
Returns the total volume of all worn holsters.
int used_holsters () const
Used and total holsters.
int total_holsters () const
units::volume free_holster_volume () const
int empty_holsters () const
units::volume small_pocket_volume (const units::volume &threshold=1000_ml) const
Returns the total volume of all pockets less than or equal to the volume passed in.
book_mastery get_book_mastery (const item &book) const
bool fun_to_read (const item &book) const
Calculates the total fun bonus relative to this character's traits and chapter progress.
int book_fun_for (const item &book, const Character &p) const
bool can_pickVolume (const item &it, bool safe=false, const item *avoid=nullptr, bool ignore_pkt_settings=true) const
bool can_pickVolume_partial (const item &it, bool safe=false, const item *avoid=nullptr, bool ignore_pkt_settings=true, bool is_pick_up_inv=false) const
bool can_pickWeight (const item &it, bool safe=true) const
bool can_pickWeight_partial (const item &it, bool safe=true) const
std::pair< item_location, item_pocket * > best_pocket (const item &it, const item *avoid=nullptr, bool ignore_settings=false)
What is the best pocket to put @it into?
std::vector< pocket_data_with_parent > get_all_pocket_with_parent (const std::function< bool(const item_pocket *)> &filter=return_true< const item_pocket * >, const std::function< bool(const pocket_data_with_parent &a, const pocket_data_with_parent &b)> *sort_func=nullptr)
Collect all pocket data (with parent and nest levels added) that the character has.
bool can_use (const item &it, const item &context=item()) const
Checks if character stats and skills meet minimum requirements for the item.
ret_val< void > can_wear (const item &it, bool with_equip_change=false) const
Check character capable of wearing an item.
bool is_armed () const
Returns true if the character is wielding something.
bool has_wield_conflicts (const item &it) const
Returns true if the character is wielding something and it can't be combined with the item passed as a parameter.
ret_val< void > can_unwield (const item &it) const
Check player capable of unwielding an item.
ret_val< void > can_drop (const item &it) const
Check player capable of dropping an item.
void clear_inventory_search_cache ()
void drop_invalid_inventory ()
void invalidate_inventory_validity_cache ()
void invalidate_weight_carried_cache ()
std::list< item * > get_dependent_worn_items (const item &it)
Returns all items that must be taken off before taking off this item.
void drop (item_location loc, const tripoint &where)
Drops an item to the specified location.
virtual void drop (const drop_locations &what, const tripoint &target, bool stash=false)
void pick_up (const drop_locations &what)
Assigns character activity to pick up items from the given drop_locations.
bool is_wielding (const item &target) const
bool covered_with_flag (const flag_id &flag, const body_part_set &parts) const
bool is_waterproof (const body_part_set &parts) const
bool is_wearing (const itype_id &it) const
Returns true if the player is wearing the item.
bool is_wearing_on_bp (const itype_id &it, const bodypart_id &bp) const
Returns true if the player is wearing the item on the given body part.
bool worn_with_flag (const flag_id &flag, const bodypart_id &bp) const
Returns true if the player is wearing an item with the given flag.
bool worn_with_flag (const flag_id &flag) const
item item_worn_with_flag (const flag_id &flag, const bodypart_id &bp) const
Returns the first worn item with a given flag.
item item_worn_with_flag (const flag_id &flag) const
item * item_worn_with_id (const itype_id &id)
Returns pointer of the first worn item with a given id.
std::vector< std::pair< std::string, std::string > > get_overlay_ids () const
Returns a list of the IDs of overlays on this character, sorted from "lowest" to "highest".
std::vector< std::pair< std::string, std::string > > get_overlay_ids_when_override_look () const
Returns a list of the IDs of overlays on this character if the character has override look mutations sorted from "lowest" to "highest".
float get_skill_level (const skill_id &ident) const
float get_skill_level (const skill_id &ident, const item &context) const
int get_knowledge_level (const skill_id &ident) const
float get_knowledge_plus_progress (const skill_id &ident) const
int get_knowledge_level (const skill_id &ident, const item &context) const
float get_average_skill_level (const skill_id &ident) const
float get_greater_skill_or_knowledge_level (const skill_id &ident) const
SkillLevelMap get_all_skills () const
SkillLevel & get_skill_level_object (const skill_id &ident)
const SkillLevel & get_skill_level_object (const skill_id &ident) const
void set_skill_level (const skill_id &ident, int level)
void mod_skill_level (const skill_id &ident, int delta)
void set_knowledge_level (const skill_id &ident, int level)
void mod_knowledge_level (const skill_id &ident, int delta)
bool meets_skill_requirements (const std::map< skill_id, int > &req, const item &context=item()) const
Checks whether the character's skills meet the required.
bool meets_skill_requirements (const construction &con) const
Checks whether the character's skills meet the required.
bool meets_stat_requirements (const item &it) const
Checks whether the character's stats meets the stats required by the item.
bool meets_requirements (const item &it, const item &context=item()) const
Checks whether the character meets overall requirements to be able to use the item.
std::string enumerate_unmet_requirements (const item &it, const item &context=item()) const
Returns a string of missed requirements (both stats and skills)
int read_speed () const
Returns the player's reading speed as a percentage.
int lie_skill () const
Returns a value used when attempting to convince NPC's of something false.
int persuade_skill () const
Returns a value used when attempting to convince NPC's of something true.
int intimidation () const
Returns a value used when attempting to intimidate NPC's.
void set_skills_from_hobbies ()
void set_bionics_from_hobbies ()
bool has_proficiency (const proficiency_id &prof) const
float get_proficiency_practice (const proficiency_id &prof) const
time_duration get_proficiency_practiced_time (const proficiency_id &prof) const
bool has_prof_prereqs (const proficiency_id &prof) const
void add_proficiency (const proficiency_id &prof, bool ignore_requirements=false)
void lose_proficiency (const proficiency_id &prof, bool ignore_requirements=false)
bool practice_proficiency (const proficiency_id &prof, const time_duration &amount, const std::optional< time_duration > &max=std::nullopt)
time_duration proficiency_training_needed (const proficiency_id &prof) const
void set_proficiency_practiced_time (const proficiency_id &prof, int turns)
std::vector< display_proficiency > display_proficiencies () const
std::vector< proficiency_id > known_proficiencies () const
std::vector< proficiency_id > learning_proficiencies () const
int get_proficiency_bonus (const std::string &category, proficiency_bonus_type prof_bonus) const
void add_default_background ()
void set_proficiencies_from_hobbies ()
void set_proficiency_practice (const proficiency_id &id, const time_duration &amount)
time_point get_time_died () const
return the calendar::turn the character expired
void set_time_died (const time_point &time)
set the turn the turn the character died if not already done
std::vector< spell > spells_known_of_class (const trait_id &spell_class) const
bool cast_spell (spell &sp, bool fake_spell, const std::optional< tripoint > &target)
bool avoid_trap (const tripoint &pos, const trap &tr) const override
Called when a player triggers a trap, returns true if they don't set it off.
bool add_faction_warning (const faction_id &id) const
int current_warnings_fac (const faction_id &id)
bool beyond_final_warning (const faction_id &id)
const Character * get_book_reader (const item &book, std::vector< std::string > &reasons) const
Helper function for player::read.
time_duration time_to_read (const item &book, const Character &reader, const Character *learner=nullptr) const
Helper function for get_book_reader.
read_condition_result check_read_condition (const item &book) const
Helper function for get_book_reader.
void normalize () override
Calls Creature::normalize() nulls out the player's weapon Should only be called through player::normalize(), not on it's own!
void die (Creature *nkiller) override
Empty function.
virtual void prevent_death ()
std::string get_name () const override
std::vector< std::string > get_grammatical_genders () const override
template<typename ... Args>
bool query_yn (const char *const msg, Args &&... args) const
It is supposed to hide the query_yn to simplify player vs.
std::pair< bodypart_id, int > best_part_to_smash () const
virtual int smash_ability () const
bool check_immunity_data (const field_immunity_data &ft) const override
bool is_immune_field (const field_type_id &fid) const override
Returns true if we are immune to the field type with the given fid.
bool is_elec_immune () const override
Returns true is the player is protected from electric shocks.
bool is_immune_effect (const efftype_id &) const override
Returns true if the player is immune to this kind of effect.
bool is_immune_damage (const damage_type_id &) const override
Returns true if the player is immune to this kind of damage.
bool is_rad_immune () const
Returns true if the player is protected from radiation.
bool is_knockdown_immune () const
Returns true if the player is immune to knockdowns.
bool is_melee_bash_damage_cap_bonus () const
Returns true if the player's melee skill increases the bash damage weapon cap.
bool immune_to (const bodypart_id &bp, damage_unit dam) const
Check if a given body part is immune to a given damage type.
void mod_pain (int npain) override
Modifies a pain value by player traits before passing it to Creature::mod_pain()
void set_pain (int npain) override
Sets new intensity of pain an reacts to it.
int get_perceived_pain () const override
Returns perceived pain (reduced with painkillers)
float fall_damage_mod () const override
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
int impact (int force, const tripoint &pos) override
Deals falling/collision damage with terrain/creature at pos.
bool can_fly ()
Checks to see if the character is able to use their wings properly.
void knock_back_to (const tripoint &to) override
Knocks the player to a specified tile.
int hp_percentage () const override
Returns overall % of HP remaining.
bool has_nv ()
Returns true if the player has some form of night vision.
int get_lift_assist () const
float rest_quality () const
Returns >0 if character is sitting/lying and relatively inactive.
float healing_rate (float at_rest_quality) const
Average hit points healed per turn.
float healing_rate_medicine (float at_rest_quality, const bodypart_id &bp) const
Average hit points healed per turn from healing effects.
social_modifiers get_mutation_bionic_social_mods () const
Goes over all mutations/bionics, returning the sum of the social modifiers.
nc_color symbol_color () const override
Creature symbol background color.
const std::string & symbol () const override
Creature symbol.
std::string extended_description () const override
std::string mutation_name (const trait_id &mut) const
std::string mutation_desc (const trait_id &mut) const
void empty_skills ()
void pick_name (bool bUseDefault=false)
Returns a random name from NAMES_*.
std::vector< trait_id > get_base_traits () const
Get the idents of all base traits.
std::vector< trait_id > get_mutations (bool include_hidden=true, bool ignore_enchantment=false, const std::function< bool(const mutation_branch &)> &filter=nullptr) const
Get the idents of all traits/mutations.
std::vector< trait_and_var > get_mutations_variants (bool include_hidden=true, bool ignore_enchantment=false) const
Same as above, but also grab the variant ids (or empty string if none)
const std::bitset< NUM_VISION_MODES > & get_vision_modes () const
void clear_mutations ()
Empties the trait and mutations lists.
void toggle_trait_deps (const trait_id &tr, const std::string &variant="")
Steps through the dependency chain for the given trait.
void add_traits ()
Adds mandatory scenario and profession traits unless you already have them And if you do already have them, refunds the points for the trait.
bool crossed_threshold () const
Returns true if the player has crossed a mutation threshold Player can only cross one mutation threshold.
mutation_category_id get_threshold_category () const
Returns the category that the player has crossed the threshold of, if they have one.
void environmental_revert_effect ()
int climbing_cost (const tripoint &from, const tripoint &to) const
Checks both the neighborhoods of from and to for climbable surfaces, returns move cost of climbing from from to to.
bodypart_id most_staunchable_bp ()
Which body part has the most staunchable bleeding, and what is the max improvement.
bodypart_id most_staunchable_bp (int &max)
void pause ()
template<typename T >
bool can_lift (const T &obj) const
Check player strong enough to lift an object unaided by equipment (jacks, levers etc)
item_location get_wielded_item () const
item_location get_wielded_item ()
void set_wielded_item (const item &to_wield)
std::vector< matype_id > known_styles (bool teachable_only) const
bool has_martialart (const matype_id &m) const
int get_oxygen_max () const
bool can_recover_oxygen () const
void randomize_blood ()
void randomize_heartrate ()
int get_focus () const
void mod_focus (int amount)
void set_focus (int amount)
void queue_effect (const std::string &name, const time_duration &delay, const time_duration &duration)
Queue an EOC to add effect after a delay.
int count_queued_effects (const std::string &effect) const
Count queued add_effect EOCs for specific effect.
void add_addiction (const addiction_id &type, int strength)
Adds an addiction to the player.
void rem_addiction (const addiction_id &type)
Removes an addition from the player.
bool has_addiction (const addiction_id &type) const
Returns true if the player has an addiction of the specified type.
int addiction_level (const addiction_id &type) const
Returns the intensity of the specified addiction.
bool knows_creature_type (const Creature *c) const
Returns true if the character is familiar with the given creature type.
bool knows_creature_type (const mtype_id &c) const
Returns true if the character is familiar with the given creature type.
void set_knows_creature_type (const Creature *c)
This character becomes familiar with creatures of the given type.
void set_knows_creature_type (const mtype_id &c)
This character becomes familiar with creatures of the given type.
const std::set< mtype_id > & get_known_monsters () const
Returns a list of all monster types known by this character.
void toggle_hauling ()
void start_hauling (const std::vector< item_location > &items_to_haul)
void stop_hauling ()
bool is_hauling () const
void start_autohaul ()
void stop_autohaul ()
bool is_autohauling () const
bool trim_haul_list (const std::vector< item_location > &valid_items)
void cache_visit_items_with (const itype_id &type, const std::function< void(item &)> &do_func)
Applies a lambda function on all items with the given flag and/or that pass the given boolean item function, using or creating caches from inv_search_caches.
void cache_visit_items_with (const flag_id &type_flag, const std::function< void(item &)> &do_func)
void cache_visit_items_with (const std::string &key, bool(item::*filter_func)() const, const std::function< void(item &)> &do_func)
void cache_visit_items_with (const std::string &key, const itype_id &type, const flag_id &type_flag, bool(item::*filter_func)() const, const std::function< void(item &)> &do_func)
void cache_visit_items_with (const itype_id &type, const std::function< void(const item &)> &do_func) const
void cache_visit_items_with (const flag_id &type_flag, const std::function< void(const item &)> &do_func) const
void cache_visit_items_with (const std::string &key, bool(item::*filter_func)() const, const std::function< void(const item &)> &do_func) const
void cache_visit_items_with (const std::string &key, const itype_id &type, const flag_id &type_flag, bool(item::*filter_func)() const, const std::function< void(const item &)> &do_func) const
bool cache_has_item_with (const itype_id &type, const std::function< bool(const item &)> &check_func=return_true< item >) const
Returns true if the character has an item with given flag and/or that passes the given boolean item function, using or creating caches from inv_search_caches.
bool cache_has_item_with (const flag_id &type_flag, const std::function< bool(const item &)> &check_func=return_true< item >) const
bool cache_has_item_with (const std::string &key, bool(item::*filter_func)() const, const std::function< bool(const item &)> &check_func=return_true< item >) const
bool cache_has_item_with (const std::string &key, const itype_id &type, const flag_id &type_flag, bool(item::*filter_func)() const, const std::function< bool(const item &)> &check_func=return_true< item >) const
bool has_item_with_flag (const flag_id &flag, bool need_charges=false) const
Find if the character has an item with a specific flag.
bool cache_has_item_with_flag (const flag_id &type_flag, bool need_charges=false) const
Find if the character has an item whose type has a specific flag.
std::vector< item * > cache_get_items_with (const itype_id &type, const std::function< bool(item &)> &do_and_check_func=return_true< item >)
Returns all items with the given flag and/or that pass the given boolean item function, using or creating caches from inv_search_caches.
std::vector< item * > cache_get_items_with (const flag_id &type_flag, const std::function< bool(item &)> &do_and_check_func=return_true< item >)
std::vector< item * > cache_get_items_with (const std::string &key, bool(item::*filter_func)() const, const std::function< bool(item &)> &do_and_check_func=return_true< item >)
std::vector< item * > cache_get_items_with (const std::string &key, const itype_id &type, const flag_id &type_flag, bool(item::*filter_func)() const, const std::function< bool(item &)> &do_and_check_func=return_true< item >)
std::vector< const item * > cache_get_items_with (const itype_id &type, const std::function< bool(const item &)> &check_func=return_true< item >) const
std::vector< const item * > cache_get_items_with (const flag_id &type_flag, const std::function< bool(const item &)> &check_func=return_true< item >) const
std::vector< const item * > cache_get_items_with (const std::string &key, bool(item::*filter_func)() const, const std::function< bool(const item &)> &check_func=return_true< item >) const
std::vector< const item * > cache_get_items_with (const std::string &key, const itype_id &type, const flag_id &type_flag, bool(item::*filter_func)() const, const std::function< bool(const item &)> &check_func=return_true< item >) const
void add_to_inv_search_caches (item &it) const
Add an item to existing inv_search_caches that it meets the criteria for.
bool has_charges (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const override
std::list< item > use_amount (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >, bool select_ind=false)
bool use_charges_if_avail (const itype_id &it, int quantity)
units::energy available_ups () const
Available ups from all sources Sum of mech, bionic UPS and UPS.
units::energy consume_ups (units::energy qty, int radius=-1)
Consume UPS charges.
std::list< item > use_charges (const itype_id &what, int qty, const std::function< bool(const item &)> &filter=return_true< item >)
Use charges in character inventory.
std::list< item > use_charges (const itype_id &what, int qty, int radius, const std::function< bool(const item &)> &filter=return_true< item >, bool in_tools=false)
Use charges within a radius.
item find_firestarter_with_charges (int quantity) const
bool has_fire (int quantity) const
void use_fire (int quantity)
void assign_stashed_activity ()
bool check_outbounds_activity (const player_activity &act, bool check_only=false)
void assign_activity (const activity_id &type, int moves=calendar::INDEFINITELY_LONG, int index=-1, int pos=INT_MIN, const std::string &name="")
void assign_activity (const player_activity &act)
Assigns activity to player, possibly resuming old activity if it's defined resumable.
void assign_activity (const activity_actor &actor)
Assigns activity actor to player, possibly resuming old activity if it's defined resumable.
bool has_activity (const activity_id &type) const
Check if player currently has a given activity.
bool has_activity (const std::vector< activity_id > &types) const
Check if player currently has any of the given activities.
void resume_backlog_activity ()
void cancel_activity ()
void cancel_stashed_activity ()
player_activity get_stashed_activity () const
void set_stashed_activity (const player_activity &act, const player_activity &act_back=player_activity())
bool has_stashed_activity () const
bool can_stash (const item &it, bool ignore_pkt_settings=false)
bool can_stash (const item &it, int &copies_remaining, bool ignore_pkt_settings=false)
bool can_stash_partial (const item &it, bool ignore_pkt_settings=false)
void initialize_stomach_contents ()
float metabolic_rate_base () const
Stable base metabolic rate due to traits.
float metabolic_rate () const
Current metabolic rate due to traits, hunger, speed, etc.
int get_max_healthy () const
float get_bmi () const
float get_bmi_fat () const
float get_bmi_lean () const
int get_bmr () const
void reset_chargen_attributes ()
int base_age () const
void set_base_age (int age)
void mod_base_age (int mod)
int age (time_point when=calendar::turn) const
std::string age_string (time_point when=calendar::turn) const
int base_height () const
void set_base_height (int height)
void mod_base_height (int mod)
std::string height_string () const
int height () const
void randomize_height ()
units::mass bodyweight () const
units::mass bodyweight_lean () const
units::mass bodyweight_fat () const
float fat_ratio () const
units::mass bionics_weight () const
void set_activity_level (float new_level)
void decrease_activity_level (float new_level)
void reset_activity_level ()
std::string activity_level_str () const
int get_env_resist (bodypart_id bp) const override
Returns overall env_resist on a body_part.
int get_armor_type (const damage_type_id &dt, bodypart_id bp) const override
Returns overall resistance to given type on the bod part.
std::map< bodypart_id, int > get_all_armor_type (const damage_type_id &dt, const std::map< bodypart_id, std::vector< const item * >> &clothing_map) const
int get_stim () const
void set_stim (int new_stim)
void mod_stim (int mod)
int get_rad () const
void set_rad (int new_rad)
void mod_rad (int mod)
float get_heartrate_index () const
void set_heartrate_effect_mod (int mod)
void modify_heartrate_effect_mod (int mod)
int get_heartrate_effect_mod () const
void update_heartrate_index ()
float get_bloodvol_index () const
void update_bloodvol_index ()
float get_circulation_resistance () const
void set_bp_effect_mod (int mod)
void modify_bp_effect_mod (int mod)
int get_bp_effect_mod () const
void update_circulation_resistance ()
float get_respiration_rate () const
void set_respiration_effect_mod (int mod)
int get_respiration_effect_mod () const
void modify_respiration_effect_mod (int mod)
void update_respiration_rate ()
void update_circulation ()
int get_stamina () const
int get_stamina_max () const
void set_stamina (int new_stamina)
void burn_energy_arms (int mod)
void burn_energy_legs (int mod)
void burn_energy_all (int mod)
float get_bionic_limb_percentage () const
void mod_stamina (int mod)
void burn_move_stamina (int moves)
void update_stamina (int turns)
Regenerates stamina.
int get_cardiofit () const
int get_cardio_acc () const
void set_cardio_acc (int ncardio_acc)
void reset_cardio_acc ()
int get_cardio_acc_base () const
bool handle_gun_damage (item &it)
Returns true if a gun misfires, jams, or has other problems, else returns false.
bool handle_gun_overheat (item &it)
Handles overheat mechanics for guns, returns true if the gun cant fire due to overheat effects.
double recoil_vehicle () const
Get maximum recoil penalty due to vehicle motion.
double recoil_total () const
Current total maximum recoil penalty from all sources.
int gun_engagement_moves (const item &gun, int target=0, int start=MAX_RECOIL, const Target_attributes &attributes=Target_attributes()) const
How many moves does it take to aim gun to the target accuracy.
int fire_gun (const tripoint &target, int shots=1)
Fires a gun or auxiliary gunmod (ignoring any current mode)
int fire_gun (const tripoint &target, int shots, item &gun)
Fires a gun or auxiliary gunmod (ignoring any current mode)
dealt_projectile_attack throw_item (const tripoint &target, const item &to_throw, const std::optional< tripoint > &blind_throw_from_pos=std::nullopt)
Execute a throw.
void on_item_wear (const item &it)
Called when an item is worn.
void on_item_takeoff (const item &it)
Called when an item is taken off.
void enchantment_wear_change ()
void on_worn_item_washed (const item &it)
Called when an item is washed.
void on_item_acquire (const item &it)
Called when an item is acquired (picked up, worn, or wielded)
void on_effect_int_change (const efftype_id &eid, int intensity, const bodypart_id &bp=bodypart_id("bp_null")) override
Called when effect intensity has been changed.
void on_mutation_gain (const trait_id &mid)
Called when a mutation is gained.
void on_mutation_loss (const trait_id &mid)
Called when a mutation is lost.
void on_stat_change (const std::string &stat, int value) override
Called when a stat is changed.
tripoint adjacent_tile () const
Returns an unoccupied, safe adjacent point.
bool has_opposite_trait (const trait_id &flag) const
Returns true if the player has a trait which cancels the entered trait.
std::unordered_set< trait_id > get_opposite_traits (const trait_id &flag) const
Returns traits that cancel the entered trait.
int get_shout_volume () const
void shout (std::string msg="", bool order=false)
void signal_nemesis ()
void vomit ()
Handles Character vomiting effects.
void customize_appearance (customize_appearance_choice choice)
float adjust_for_focus (float amount) const
void update_type_of_scent (bool init=false)
void update_type_of_scent (const trait_id &mut, bool gain=true)
void set_type_of_scent (const scenttype_id &id)
scenttype_id get_type_of_scent () const
void restore_scent ()
restore scent after masked_scent effect run out or is removed by water
void mod_painkiller (int npkill)
Modifies intensity of painkillers
void set_painkiller (int npkill)
Sets intensity of painkillers
int get_painkiller () const
Returns intensity of painkillers
void react_to_felt_pain (int intensity)
void clear_moncams ()
Monster cameras are mtype_ids with an integer range of transmission.
void remove_moncam (const mtype_id &moncam_id)
void add_moncam (const std::pair< mtype_id, int > &moncam)
void set_moncams (std::map< mtype_id, int > nmoncams)
std::map< mtype_id, int > const & get_moncams () const
moncam_cache_t get_active_moncams () const
void spores ()
void blossoms ()
void rooted_message () const
Handles rooting effects.
void rooted ()
void fall_asleep ()
Adds "sleep" to the player.
void fall_asleep (const time_duration &duration)
std::string is_snuggling () const
Checks to see if the player is using floor items to keep warm, and return the name of one such item if so.
ret_val< crush_tool_type > can_crush_frozen_liquid (item_location const &loc) const
bool crush_frozen_liquid (item_location loc)
Prompts user about crushing item at item_location loc, for harvesting of frozen liquids.
float power_rating () const override
Returns an approximation of the creature's strength.
float speed_rating () const override
Returns an approximate number of tiles this creature can travel per turn.
bool sees_with_infrared (const Creature &critter) const
Check whether the this player can see the other creature with infrared.
void place_corpse ()
void place_corpse (const tripoint_abs_omt &om_target)
std::vector< run_cost_effect > run_cost_effects (float &movecost) const
Modifies the movement cost and returns a list of effects.
int run_cost (int base_cost, bool diag=false) const
Returns the player's modified base movement cost.
const pathfinding_settings & get_pathfinding_settings () const override
Returns settings for pathfinding.
std::unordered_set< tripoint > get_path_avoid () const override
Returns a set of points we do not want to path through.
std::vector< Creature * > get_hostile_creatures (int range) const
Get all hostile creatures currently visible to this player.
std::vector< Creature * > get_visible_creatures (int range) const
Returns all creatures that this player can see and that are in the given range.
std::vector< Creature * > get_targetable_creatures (int range, bool melee) const
As above, but includes all creatures the player can detect well enough to target with ranged weapons, e.g.
int get_mutation_visibility_cap (const Character *observed) const
Returns the mutation visibility threshold for the observer (*this)
std::string visible_mutations (int visibility_cap) const
Returns an enumeration of visible mutations with colors.
player_activity get_destination_activity () const
void set_destination_activity (const player_activity &new_destination_activity)
void clear_destination_activity ()
bool can_use_pockets () const
bool can_use_hood () const
bool can_use_collar () const
std::map< bodypart_id, int > bonus_item_warmth () const
Returns warmth provided by an armor's bonus, like hoods, pockets, etc.
bool can_use_floor_warmth () const
Can the player lie down and cover self with blankets etc.
units::temperature_delta floor_warmth (const tripoint &pos) const
Final warmth from the floor.
units::temperature_delta bodytemp_modifier_traits (bool overheated) const
Correction factor of the body temperature due to traits and mutations.
units::temperature temp_corrected_by_climate_control (units::temperature temperature, int heat_strength, int chill_strength) const
Value of the body temperature corrected by climate control.
bool in_sleep_state () const override
void update_vitamins (const vitamin_id &vit)
Set vitamin deficiency/excess disease states dependent upon current vitamin levels.
int vitamin_get (const vitamin_id &vit) const
Check current level of a vitamin.
int get_daily_vitamin (const vitamin_id &vit, bool actual=true) const
void vitamin_set (const vitamin_id &vit, int qty)
Sets level of a vitamin.
int vitamin_mod (const vitamin_id &vit, int qty)
Add or subtract vitamins from character storage pools.
void vitamins_mod (const std::map< vitamin_id, int > &)
time_duration vitamin_rate (const vitamin_id &vit) const
Get vitamin usage rate (minutes per unit) accounting for bionics, mutations and effects.
std::map< vitamin_id, int > effect_vitamin_mod (const std::map< vitamin_id, int > &)
Modify vitamin intake (e.g.
void clear_vitamins ()
Remove all vitamins.
void reset_daily_vitamin (const vitamin_id &vit)
int nutrition_for (const item &comest) const
Handles the nutrition value for a comestible.
ret_val< edible_rating > can_eat (const item &food) const
Can the food be [theoretically] eaten no matter the consequences?
ret_val< edible_rating > will_eat (const item &food, bool interactive=false) const
Same as can_eat, but takes consequences into account.
int get_acquirable_energy (const item &it) const
Determine character's capability of recharging their CBMs.
void modify_stimulation (const islot_comestible &comest)
Used to apply stimulation modifications from food and medication.
void modify_sleepiness (const islot_comestible &comest)
Used to apply sleepiness modifications from food and medication.
void modify_radiation (const islot_comestible &comest)
void modify_addiction (const islot_comestible &comest)
Used to apply addiction modifications from food and medication.
void modify_health (const islot_comestible &comest)
Used to apply health modifications from food and medication.
double compute_effective_food_volume_ratio (const item &food) const
Used to compute how filling a food is.
units::volume masticated_volume (const item &food) const
Used to calculate dry volume of a chewed food.
int compute_calories_per_effective_volume (const item &food, const nutrients *nutrient=nullptr) const
Used to to display how filling a food is.
bool consume_effects (item &food)
Handles the effects of consuming an item.
bool can_consume_as_is (const item &it) const
Check whether the character can consume this very item.
bool can_estimate_rot () const
True if the character has enough skill (in cooking or survival) to estimate time to rot.
item & get_consumable_from (item &it) const
Returns a reference to the item itself (if it's consumable), the first of its contents (if it's consumable) or null item otherwise.
std::pair< nutrients, nutrients > compute_nutrient_range (const item &, const recipe_id &, std::map< recipe_id, std::pair< nutrients, nutrients >> &rec_cache, const cata::flat_set< flag_id > &extra_flags={}) const
Get calorie & vitamin contents for a comestible, taking into account character traits.
std::pair< nutrients, nutrients > compute_nutrient_range (const itype_id &, std::map< recipe_id, std::pair< nutrients, nutrients >> &rec_cache, const cata::flat_set< flag_id > &extra_flags={}) const
Same, but across arbitrary recipes.
morale_type allergy_type (const item &food) const
Returns allergy type or MORALE_NULL if not allergic for this character.
nutrients compute_effective_nutrients (const item &) const
bool wearing_something_on (const bodypart_id &bp) const
Returns true if the character is wearing something on the entered body part.
bool wearing_fitting_on (const bodypart_id &bp) const
Returns true if the character is wearing something on the entered body part.
double armwear_factor () const
Same as footwear factor, but for arms.
int shoe_type_count (const itype_id &it) const
Returns 1 if the player is wearing an item of that count on one foot, 2 if on both, and zero if on neither.
bool is_wearing_shoes (const side &check_side=side::BOTH) const
Returns true if the player is wearing something on their feet that is not SKINTIGHT.
bool is_barefoot () const
Returns true if the player is not wearing anything that covers the soles of their feet, ignoring INTEGRATED.
bool is_worn_item_visible (std::list< item >::const_iterator) const
Returns true if the worn item is visible (based on layering and coverage)
std::list< item > get_visible_worn_items () const
Returns all worn items visible to an outside observer.
bool change_side (item &it, bool interactive=true)
Swap side on which item is worn; returns false on fail.
bool change_side (item_location &loc, bool interactive=true)
bool get_check_encumbrance () const
void set_check_encumbrance (bool new_check)
void update_morale ()
Ticks down morale counters and removes them.
void apply_persistent_morale ()
Ensures persistent morale effects are up-to-date.
void hoarder_morale_penalty ()
void modify_morale (item &food, int nutr=0)
Used to apply morale modifications from food and medication.
int get_morale_level () const
void add_morale (const morale_type &type, int bonus, int max_bonus=0, const time_duration &duration=1_hours, const time_duration &decay_start=30_minutes, bool capped=false, const itype *item_type=nullptr)
int has_morale (const morale_type &type) const
void rem_morale (const morale_type &type, const itype *item_type=nullptr)
void clear_morale ()
bool has_morale_to_read () const
bool has_morale_to_craft () const
const inventory & crafting_inventory (bool clear_path) const
const inventory & crafting_inventory (const tripoint &src_pos=tripoint_zero, int radius=PICKUP_RANGE, bool clear_path=true) const
Returns items that can be used to craft with.
void invalidate_crafting_inventory ()
float fine_detail_vision_mod (const tripoint &p=tripoint_min) const
Returns a value from 1.0 to 11.0 that acts as a multiplier for the time taken to perform tasks that require detail vision, above 4.0 means these activities cannot be performed.
void make_craft_with_command (const recipe_id &id_to_make, int batch_size, bool is_long, const std::optional< tripoint > &loc)
bool has_recipe (const recipe *r) const
bool knows_recipe (const recipe *rec) const
void learn_recipe (const recipe *rec)
void forget_recipe (const recipe *rec)
void forget_all_recipes ()
int exceeds_recipe_requirements (const recipe &rec) const
bool has_recipe_requirements (const recipe &rec) const
bool can_decomp_learn (const recipe &rec) const
bool studied_all_recipes (const itype &book) const
const recipe_subset & get_learned_recipes () const
Returns all known recipes.
recipe_subset get_available_nested (const recipe_subset &) const
recipe_subset get_recipes_from_books (const inventory &crafting_inv) const
Returns all recipes that are known from the books (either in inventory or nearby).
recipe_subset get_recipes_from_ebooks (const inventory &crafting_inv) const
Returns all recipes that are known from the books inside ereaders (either in inventory or nearby).
recipe_subset get_group_available_recipes () const
Return all available recipes for any member of this crafter's group.
std::set< itype_id > get_books_for_recipe (const inventory &crafting_inv, const recipe *r) const
Returns the set of book types in crafting_inv that provide the given recipe.
float morale_crafting_speed_multiplier (const recipe &rec) const
float lighting_craft_speed_multiplier (const recipe &rec, const tripoint &p=tripoint_min) const
float crafting_speed_multiplier (const recipe &rec) const
float workbench_crafting_speed_multiplier (const item &craft, const std::optional< tripoint > &loc) const
float crafting_speed_multiplier (const item &craft, const std::optional< tripoint > &loc, bool use_cached_workbench_multiplier=false, float cached_workbench_multiplier=0.0f) const
For use with in progress crafts.
int available_assistant_count (const recipe &rec) const
int64_t expected_time_to_craft (const recipe &rec, int batch_size=1) const
Expected time to craft a recipe, with assumption that multipliers stay constant.
std::vector< const item * > get_eligible_containers_for_crafting () const
bool check_eligible_containers_for_crafting (const recipe &rec, int batch_size=1) const
bool can_make (const recipe *r, int batch_size=1) const
bool can_start_craft (const recipe *rec, recipe_filter_flags, int batch_size=1) const
Returns true if the player can start crafting the recipe with the given batch size The player is not required to have enough tool charges to finish crafting, only to complete the first step (total / 20 + total % 20 charges)
bool making_would_work (const recipe_id &id_to_make, int batch_size) const
void craft (const std::optional< tripoint > &loc=std::nullopt, const recipe_id &goto_recipe=recipe_id(), const std::string &filterstring="")
Start various types of crafts.
void recraft (const std::optional< tripoint > &loc=std::nullopt)
void long_craft (const std::optional< tripoint > &loc=std::nullopt, const recipe_id &goto_recipe=recipe_id())
void make_craft (const recipe_id &id, int batch_size, const std::optional< tripoint > &loc=std::nullopt)
void make_all_craft (const recipe_id &id, int batch_size, const std::optional< tripoint > &loc)
void start_craft (craft_command &command, const std::optional< tripoint > &loc)
consume components and create an active, in progress craft containing them
float crafting_success_roll (const recipe &making) const
Calculate a value representing the success of the player at crafting the given recipe, taking player skill, recipe difficulty, npc helpers, and player mutations into account.
float crafting_failure_roll (const recipe &making) const
float get_recipe_weighted_skill_average (const recipe &making) const
float recipe_success_chance (const recipe &making) const
float item_destruction_chance (const recipe &making) const
craft_roll_data recipe_success_roll_data (const recipe &making) const
craft_roll_data recipe_failure_roll_data (const recipe &making) const
void complete_craft (item &craft, const std::optional< tripoint > &loc)
bool can_continue_craft (item &craft)
Check if the player meets the requirements to continue the in progress craft and if unable to continue print messages explaining the reason.
bool can_continue_craft (item &craft, const requirement_data &continue_reqs)
std::vector< Character * > get_crafting_helpers () const
Return nearby Characters ready and willing to help with crafting.
std::vector< Character * > get_crafting_group () const
Return group of ally characters sharing knowledge of crafting.
int get_num_crafting_helpers (int max) const
bool craft_skill_gain (const item &craft, const int &num_practice_ticks)
Handle skill gain for player and followers during crafting.
bool craft_proficiency_gain (const item &craft, const time_duration &time)
Handle proficiency practice for player and followers while crafting.
ret_val< void > can_disassemble (const item &obj, const read_only_visitable &inv) const
Check if the player can disassemble an item using the current crafting inventory.
item_location create_in_progress_disassembly (item_location target)
bool disassemble ()
bool disassemble (item_location target, bool interactive=true, bool disassemble_all=false)
void disassemble_all (bool one_pass)
void complete_disassemble (item_location target)
Completely disassemble an item, and drop yielded components at its former position.
void complete_disassemble (item_location &target, const recipe &dis)
const requirement_data * select_requirements (const std::vector< const requirement_data * > &, int batch, const read_only_visitable &, const std::function< bool(const item &)> &filter) const
comp_selection< item_comp > select_item_component (const std::vector< item_comp > &components, int batch, read_only_visitable &map_inv, bool can_cancel=false, const std::function< bool(const item &)> &filter=return_true< item >, bool player_inv=true, bool npc_query=false, const recipe *rec=nullptr)
std::list< item > consume_items (const comp_selection< item_comp > &is, int batch, const std::function< bool(const item &)> &filter=return_true< item >, bool select_ind=false)
std::list< item > consume_items (map &m, const comp_selection< item_comp > &is, int batch, const std::function< bool(const item &)> &filter=return_true< item >, const std::vector< tripoint > &reachable_pts={}, bool select_ind=false)
std::list< item > consume_items (const std::vector< item_comp > &components, int batch=1, const std::function< bool(const item &)> &filter=return_true< item >, const std::function< bool(const itype_id &)> &select_ind=return_false< itype_id >)
bool consume_software_container (const itype_id &software_id)
comp_selection< tool_comp > select_tool_component (const std::vector< tool_comp > &tools, int batch, read_only_visitable &map_inv, bool can_cancel=false, bool player_inv=true, bool npc_query=false, const std::function< int(int)> &charges_required_modifier=[](int i) { return i;})
bool craft_consume_tools (item &craft, int multiplier, bool start_craft)
Consume tools for the next multiplier * 5% progress of the craft.
void consume_tools (const comp_selection< tool_comp > &tool, int batch)
void consume_tools (map &m, const comp_selection< tool_comp > &tool, int batch, const tripoint &origin=tripoint_zero, int radius=PICKUP_RANGE, basecamp *bcp=nullptr)
void consume_tools (map &m, const comp_selection< tool_comp > &tool, int batch, const std::vector< tripoint > &reachable_pts={}, basecamp *bcp=nullptr)
void consume_tools (const std::vector< tool_comp > &tools, int batch=1)
void check_and_recover_morale ()
Checks permanent morale for consistency and recovers it when an inconsistency is found.
std::pair< int, int > fun_for (const item &comest, bool ignore_already_ate=false) const
Handles the enjoyability value for a comestible.
void suffer ()
Handles a large number of timers decrementing and other randomized effects.
bool irradiate (float rads, bool bypass=false)
Handles mitigation and application of radiation.
void mend (int rate_multiplier)
Handles the chance for broken limbs to spontaneously heal to 1 HP.
float get_leak_level () const
void calculate_leak_level ()
Iterate through the character inventory to get its leak level.
void invalidate_leak_level_cache ()
Sets leak_level_dirty to true.
void sound_hallu ()
Creates an auditory hallucination.
void echo_pulse ()
All nearby obstacles make a very quiet sound.
bool is_driving () const
Checks if a Character is driving.
void drench (int saturation, const body_part_set &flags, bool ignore_waterproof)
Drenches the player with water, saturation is the percent gotten wet.
void apply_wetness_morale (units::temperature temperature)
Recalculates morale penalty/bonus from wetness based on mutations, equipment and temperature.
int heartrate_bpm () const
std::vector< std::string > short_description_parts () const
std::string short_description () const
bool can_hear (const tripoint &source, int volume) const
float hearing_ability () const
bool knows_trap (const tripoint &pos) const
void add_known_trap (const tripoint &pos, const trap &t)
bool sees (const tripoint &t, bool is_avatar=false, int range_mod=0) const override
bool sees (const tripoint_bub_ms &t, bool is_avatar=false, int range_mod=0) const override
bool sees (const Creature &critter) const override
Attitude attitude_to (const Creature &other) const override
Attitude (of this creature) towards another creature.
virtual npc_attitude get_attitude () const
int get_lowest_hp () const
bool has_weapon () const override
void shift_destination (const point &shift)
void set_destination (const std::vector< tripoint_bub_ms > &route, const player_activity &new_destination_activity=player_activity())
void clear_destination ()
bool has_distant_destination () const
bool is_auto_moving () const
bool has_destination () const
bool has_destination_activity () const
void start_destination_activity ()
std::vector< tripoint_bub_ms > & get_auto_move_route ()
action_id get_next_auto_move_direction ()
bool defer_move (const tripoint &next)
time_duration get_consume_time (const item &it) const
std::pair< int, int > weariness_transition_progress () const
int weariness_level () const
int weariness_transition_level () const
int weary_threshold () const
int weariness () const
float activity_level () const
float instantaneous_activity_level () const
Returns instantaneous activity level as a float from 0-10 (from game_constants)
int activity_level_index () const
Returns instantaneous activity level as an int from 0-5 (half of instantaneous_activity_level)
float exertion_adjusted_move_multiplier (float level=-1.0f) const
float maximum_exertion_level () const
std::string activity_level_str (float level) const
std::string debug_weary_info () const
void add_pain_msg (int, const bodypart_id &) const
double vomit_mod ()
Returns the modifier value used for vomiting effects.
bool can_sleep ()
Checked each turn during "lying_down", returns true if the player falls asleep.
int sleep_spot (const tripoint_bub_ms &p) const
Rate point's ability to serve as a bed.
void process_effects () override
Processes human-specific effects of effects before calling Creature::process_effects().
void hardcoded_effects (effect &it)
Handles the still hard-coded effects.
time_duration estimate_effect_dur (const skill_id &relevant_skill, const efftype_id &effect, const time_duration &error_magnitude, const time_duration &minimum_error, int threshold, const Creature &target) const
Estimate effect duration based on player relevant skill.
item & best_item_with_quality (const quality_id &qid)
Look for items in the player's inventory that have the specified quality; return the one with highest level.
bool has_quality (const quality_id &qual, int level=1, int qty=1) const override
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const override
Return maximum tool quality level provided by instance or INT_MIN if not found.
int max_quality (const quality_id &qual, int radius) const
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const override
Traverses this object and any child items contained using a visitor pattern.
std::list< item > remove_items_with (const std::function< bool(const item &)> &filter, int count=INT_MAX) override
Removes items contained by this instance which match the filter.
int charges_of (const itype_id &what, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >, const std::function< void(int)> &visitor=nullptr, bool in_tools=false) const override
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo=true, int limit=INT_MAX, const std::function< bool(const item &)> &filter=return_true< item >) const override
Count items matching id including both this instance and any contained items.
std::pair< int, int > kcal_range (const itype_id &id, const std::function< bool(const item &)> &filter, Character &player_character) const
int base_bmr () const
void store (JsonOut &json) const
Load variables from json into object.
void load (const JsonObject &data)
Gather variables for saving.
int vitamin_RDA (const vitamin_id &vitamin, int ammount) const
Returns the % of your RDA that ammount of vitamin represents.
void process_one_effect (effect &it, bool is_new) override
Processes human-specific effects of an effect.
std::map< bodypart_id, float > bodypart_exposure ()
Map body parts to their total exposure, from 0.0 (fully covered) to 1.0 (buck naked).
virtual void mod_speed_bonus (int nspeed)
Setters for stats shared with other creatures.
virtual void add_msg_if_player (const std::string &) const
virtual void add_msg_if_player (const game_message_params &, const std::string &) const
void add_msg_if_player (const translation &) const
void add_msg_if_player (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_player (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const translation &msg, Args &&... args) const
virtual void add_msg_player_or_npc (const std::string &, const std::string &) const
virtual void add_msg_player_or_npc (const game_message_params &, const std::string &, const std::string &) const
void add_msg_player_or_npc (const translation &, const translation &) const
void add_msg_player_or_npc (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const translation &player_msg, const translation &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const translation &player_msg, const translation &npc_msg, Args &&... args) const
virtual void add_msg_player_or_say (const std::string &, const std::string &) const
virtual void add_msg_player_or_say (const game_message_params &, const std::string &, const std::string &) const
void add_msg_player_or_say (const translation &, const translation &) const
void add_msg_player_or_say (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_say (const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const translation &player_msg, const translation &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const translation &player_msg, const translation &npc_speech, Args &&... args) const
virtual bool has_flag (const mon_flag_id &) const
This is to prevent clang complaining about overloading a virtual function, the creature version uses monster flags so confusion is unlikely.
bool pour_into (item_location &container, item &liquid, bool ignore_settings)
Try to pour the given liquid into the given container/vehicle.
bool pour_into (const vpart_reference &vp, item &liquid) const
Public Member Functions inherited from Creature
~Creature () override
virtual bool is_monster () const
virtual npc * as_npc ()
virtual const npc * as_npc () const
virtual monster * as_monster ()
virtual const monster * as_monster () const
virtual bool is_fake () const
Returns true for non-real Creatures used temporarily; i.e.
virtual void set_fake (bool fake_value)
Sets a Creature's fake boolean.
tripoint pos () const
tripoint_bub_ms pos_bub () const
int posx () const
int posy () const
int posz () const
void setpos (const tripoint &p)
void move_to (const tripoint_abs_ms &loc)
Moves the creature to the given location and calls the on_move() handler.
virtual void bleed () const
Adds an appropriate blood splatter.
bool sees (const Creature &critter) const override
The functions check whether this creature can see the target.
bool sees (const tripoint &t, bool is_avatar=false, int range_mod=0) const override
bool sees (const tripoint_bub_ms &t, bool is_avatar=false, int range_mod=0) const override
Creature * auto_find_hostile_target (int range, int &boo_hoo, int area=0)
For fake-players (turrets, mounted turrets) this functions chooses a target.
double ranged_target_size () const
Size of the target this creature presents to ranged weapons.
void knock_back_from (const tripoint &p)
float get_crit_factor (const bodypart_id &bp) const
int size_melee_penalty () const
virtual int deal_melee_attack (Creature *source, int hitroll)
bool is_adjacent (const Creature *target, bool allow_z_levels) const
virtual void deal_melee_hit (Creature *source, int hit_spread, bool critical_hit, damage_instance dam, dealt_damage_instance &dealt_dam, const weakpoint_attack &attack=weakpoint_attack(), const bodypart_id *bp=nullptr)
virtual void deal_projectile_attack (Creature *source, dealt_projectile_attack &attack, bool print_messages=true, const weakpoint_attack &wp_attack=weakpoint_attack())
Attempts to harm a creature with a projectile.
virtual void deal_damage_handle_type (const effect_source &source, const damage_unit &du, bodypart_id bp, int &damage, int &pain)
void longpull (const std::string &name, const tripoint &p)
Attempts to pull the target at point p towards this creature.
bool dodge_check (float hit_roll, bool force_try=false, float training_level=0.0f)
If training_level is anything but 0, the check will only train target's skill to that level.
bool dodge_check (monster *z, float training_level=0.0f)
bool dodge_check (monster *z, bodypart_id bp, const damage_instance &dam_inst, float training_level=0.0f)
bool stumble_invis (const Creature &player, bool stumblemsg=true)
bool attack_air (const tripoint &p)
virtual bool is_ranged_attacker () const
Returns true if this monster has a gun-type attack or the RANGED_ATTACKER flag.
virtual bool digging () const
bool cant_do_underwater (bool msg=true) const
virtual bool is_underwater () const
bool is_likely_underwater () const
bool is_dangerous_fields (const field &fld) const
Returns true if there is a field in the field set that is dangerous to us.
bool is_dangerous_field (const field_entry &entry) const
Returns true if the given field entry is dangerous to us.
void check_dead_state ()
This function checks the creatures is_dead_state and (if true) calls die.
void add_effect (const effect &eff, bool force=false, bool deferred=false)
void add_effect (const efftype_id &eff_id, const time_duration &dur, bodypart_id bp, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void add_effect (const efftype_id &eff_id, const time_duration &dur, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void add_effect (const effect_source &source, const effect &eff, bool force=false, bool deferred=false)
void add_effect (const effect_source &source, const efftype_id &eff_id, const time_duration &dur, bodypart_id bp, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
Adds or modifies an effect.
void add_effect (const effect_source &source, const efftype_id &eff_id, const time_duration &dur, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void schedule_effect (const effect &eff, bool force=false, bool deferred=false)
Schedules a new effect to be applied.
void schedule_effect (const efftype_id &eff_id, const time_duration &dur, bodypart_id bp, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void schedule_effect (const efftype_id &eff_id, const time_duration &dur, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
bool add_env_effect (const efftype_id &eff_id, const bodypart_id &vector, int strength, const time_duration &dur, const bodypart_id &bp, bool permanent=false, int intensity=1, bool force=false)
Gives chance to save via environmental resist, returns false if resistance was successful.
bool add_env_effect (const efftype_id &eff_id, const bodypart_id &vector, int strength, const time_duration &dur, bool permanent=false, int intensity=1, bool force=false)
bool remove_effect (const efftype_id &eff_id, const bodypart_id &bp)
Removes a listed effect.
bool remove_effect (const efftype_id &eff_id)
void schedule_effect_removal (const efftype_id &eff_id, const bodypart_id &bp)
Schedule effect removal.
void schedule_effect_removal (const efftype_id &eff_id)
void clear_effects ()
Remove all effects.
bool has_effect (const efftype_id &eff_id, const bodypart_id &bp) const
Check if creature has the matching effect.
bool has_effect (const efftype_id &eff_id) const
bool has_effect_with_flag (const flag_id &flag, const bodypart_id &bp) const
Check if creature has any effect with the given flag.
bool has_effect_with_flag (const flag_id &flag) const
std::vector< std::reference_wrapper< const effect > > get_effects_with_flag (const flag_id &flag) const
std::vector< std::reference_wrapper< const effect > > get_effects_from_bp (const bodypart_id &bp) const
std::vector< std::reference_wrapper< const effect > > get_effects () const
const effect & get_effect (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Return the effect that matches the given arguments exactly.
effect & get_effect (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID())
time_duration get_effect_dur (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Returns the duration of the matching effect.
int get_effect_int (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Returns the intensity of the matching effect.
bool resists_effect (const effect &e) const
Returns true if the creature resists an effect.
void set_value (const std::string &key, const std::string &value)
void remove_value (const std::string &key)
std::string get_value (const std::string &key) const
std::optional< std::string > maybe_get_value (const std::string &key) const
void clear_values ()
virtual void mod_pain_noresist (int npain)
virtual int get_pain () const
int get_moves () const
void mod_moves (int nmoves)
void set_moves (int nmoves)
virtual Creature * get_killer () const
virtual int get_num_blocks () const
virtual int get_num_dodges () const
virtual int get_num_blocks_bonus () const
virtual int get_num_dodges_bonus () const
virtual int get_num_dodges_base () const
virtual int get_num_blocks_base () const
virtual int get_armor_res (const damage_type_id &dt, bodypart_id bp) const
virtual int get_armor_res_base (const damage_type_id &dt, bodypart_id bp) const
virtual int get_armor_res_bonus (const damage_type_id &dt) const
virtual float get_hit () const
virtual int get_hp (const bodypart_id &bp) const
virtual int get_hp () const
virtual int get_hp_max (const bodypart_id &bp) const
virtual int get_hp_max () const
virtual bool has_flag (const mon_flag_id &) const
void set_reachable_zone (int zone)
int get_reachable_zone () const
anatomy_id get_anatomy () const
void set_anatomy (const anatomy_id &anat)
bodypart_id get_random_body_part (bool main=false) const
std::vector< bodypart_id > get_all_body_parts (get_body_part_flags=get_body_part_flags::none) const
Returns body parts this creature have.
std::vector< bodypart_id > get_all_body_parts_of_type (body_part_type::type part_type, get_body_part_flags flags=get_body_part_flags::none) const
bodypart_id get_random_body_part_of_type (body_part_type::type part_type) const
bodypart_id get_root_body_part () const
std::vector< bodypart_id > get_all_body_parts_with_flag (const json_character_flag &flag) const
body_part_set get_drenching_body_parts (bool upper=true, bool mid=true, bool lower=true) const
int get_num_body_parts_of_type (body_part_type::type part_type) const
int get_num_broken_body_parts_of_type (body_part_type::type part_type) const
const std::map< bodypart_str_id, bodypart > & get_body () const
void set_body ()
bool has_part (const bodypart_id &id, body_part_filter filter=body_part_filter::strict) const
bodypart * get_part (const bodypart_id &id)
const bodypart * get_part (const bodypart_id &id) const
bodypart_id get_part_id (const bodypart_id &id, body_part_filter filter=body_part_filter::next_best, bool suppress_debugmsg=false) const
int get_part_hp_cur (const bodypart_id &id) const
int get_part_hp_max (const bodypart_id &id) const
int get_part_healed_total (const bodypart_id &id) const
int get_part_damage_disinfected (const bodypart_id &id) const
int get_part_damage_bandaged (const bodypart_id &id) const
int get_part_drench_capacity (const bodypart_id &id) const
int get_part_wetness (const bodypart_id &id) const
units::temperature get_part_temp_cur (const bodypart_id &id) const
units::temperature get_part_temp_conv (const bodypart_id &id) const
int get_part_frostbite_timer (const bodypart_id &id) const
std::array< int, NUM_WATER_TOLERANCE > get_part_mut_drench (const bodypart_id &id) const
float get_part_wetness_percentage (const bodypart_id &id) const
const encumbrance_data & get_part_encumbrance_data (const bodypart_id &id) const
void set_part_hp_max (const bodypart_id &id, int set)
void set_part_healed_total (const bodypart_id &id, int set)
void set_part_damage_disinfected (const bodypart_id &id, int set)
void set_part_damage_bandaged (const bodypart_id &id, int set)
void set_part_encumbrance_data (const bodypart_id &id, const encumbrance_data &set)
void set_part_wetness (const bodypart_id &id, int set)
void set_part_temp_cur (const bodypart_id &id, units::temperature set)
void set_part_temp_conv (const bodypart_id &id, units::temperature set)
void set_part_frostbite_timer (const bodypart_id &id, int set)
void set_part_mut_drench (const bodypart_id &id, std::pair< water_tolerance, int > set)
void mod_part_hp_max (const bodypart_id &id, int mod)
void mod_part_healed_total (const bodypart_id &id, int mod)
void mod_part_damage_disinfected (const bodypart_id &id, int mod)
void mod_part_damage_bandaged (const bodypart_id &id, int mod)
void mod_part_wetness (const bodypart_id &id, int mod)
void mod_part_temp_cur (const bodypart_id &id, units::temperature_delta mod)
void mod_part_temp_conv (const bodypart_id &id, units::temperature_delta mod)
void mod_part_frostbite_timer (const bodypart_id &id, int mod)
void set_all_parts_temp_cur (units::temperature set)
void set_all_parts_temp_conv (units::temperature set)
void set_all_parts_wetness (int set)
void set_all_parts_hp_cur (int set)
void set_all_parts_hp_to_max ()
bool has_atleast_one_wet_part () const
bool is_part_at_max_hp (const bodypart_id &id) const
virtual int get_speed_base () const
virtual int get_speed_bonus () const
virtual int get_block_bonus () const
virtual int get_bash_bonus () const
virtual int get_cut_bonus () const
virtual float get_dodge_bonus () const
virtual float get_hit_bonus () const
virtual float get_bash_mult () const
virtual float get_cut_mult () const
virtual bool get_melee_quiet () const
virtual int get_throw_resist () const
virtual void set_num_blocks_bonus (int nblocks)
virtual void mod_num_blocks_bonus (int nblocks)
virtual void mod_num_dodges_bonus (int ndodges)
virtual void set_armor_res_bonus (int narm, const damage_type_id &dt)
virtual void set_speed_base (int nspeed)
virtual void set_speed_bonus (int nspeed)
virtual void set_block_bonus (int nblock)
virtual void set_bash_bonus (int nbash)
virtual void set_cut_bonus (int ncut)
virtual void mod_speed_bonus (int nspeed)
virtual void mod_block_bonus (int nblock)
virtual void mod_bash_bonus (int nbash)
virtual void mod_cut_bonus (int ncut)
virtual void mod_size_bonus (int nsize)
virtual void set_dodge_bonus (float ndodge)
virtual void set_hit_bonus (float nhit)
virtual void mod_dodge_bonus (float ndodge)
virtual void mod_hit_bonus (float nhit)
virtual void set_bash_mult (float nbashmult)
virtual void set_cut_mult (float ncutmult)
virtual void set_melee_quiet (bool nquiet)
virtual void set_throw_resist (int nthrowres)
void draw (const catacurses::window &w, const point &origin, bool inverted) const
void draw (const catacurses::window &w, const tripoint &origin, bool inverted) const
void describe_infrared (std::vector< std::string > &buf) const
Describe this creature as seen by the avatar via infrared vision.
void describe_specials (std::vector< std::string > &buf) const
Describe this creature as detected by the avatar's special senses.
void add_msg_if_player (const translation &) const
void add_msg_if_player (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_player (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const translation &msg, Args &&... args) const
virtual void add_msg_if_npc (const std::string &) const
virtual void add_msg_if_npc (const game_message_params &, const std::string &) const
void add_msg_if_npc (const translation &) const
void add_msg_if_npc (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_npc (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const translation &msg, Args &&... args) const
void add_msg_player_or_npc (const translation &, const translation &) const
void add_msg_player_or_npc (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const translation &player_msg, const translation &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const translation &player_msg, const translation &npc_msg, Args &&... args) const
void add_msg_player_or_say (const translation &, const translation &) const
void add_msg_player_or_say (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_say (const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const translation &player_msg, const translation &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const translation &player_msg, const translation &npc_speech, Args &&... args) const
virtual bool is_symbol_highlighted () const
std::unordered_map< std::string, std::string > & get_values ()
void clear_killer ()
void set_summon_time (const time_duration &length)
void decrement_summon_timer ()
void set_summoner (Creature *summoner)
void set_summoner (character_id summoner)
Creature * get_summoner () const
bodypart_id get_max_hitsize_bodypart () const
bodypart_id select_body_part (int min_hit, int max_hit, bool can_attack_high, int hit_roll) const
bodypart_id select_blocking_part (bool arm, bool leg, bool nonstandard) const
bodypart_id random_body_part (bool main_parts_only=false) const
std::vector< bodypart_id > get_all_eligable_parts (int min_hit, int max_hit, bool can_attack_high) const
void add_damage_over_time (const damage_over_time_data &DoT)
void process_damage_over_time ()
std::string replace_with_npc_name (std::string input) const
This function replaces the "<npcname>" substring with the disp_name of this creature.
tripoint_abs_ms get_location () const
Returns the location of the creature in map square coordinates (the most detailed coordinate system), relative to a fixed global point of origin.
tripoint_abs_sm global_sm_location () const
Returns the location of the creature in global submap coordinates.
tripoint_abs_omt global_omt_location () const
Returns the location of the creature in global overmap terrain coordinates.
Public Member Functions inherited from viewer
virtual ~viewer ()=default
Public Member Functions inherited from visitable
item remove_item (item &it)
Removes and returns the item which must be contained by this instance.
Public Member Functions inherited from read_only_visitable
item * find_parent (const item &it) const
Determine the immediate parent container (if any) for an item.
std::vector< item * > parents (const item &it) const
Returns vector of parent containers (if any) starting with the innermost.
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
std::pair< int, int > kcal_range (const itype_id &id, const std::function< bool(const item &)> &filter, Character &player_character) const
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
virtual ~read_only_visitable ()=default
bool has_tools (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
bool has_components (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
Public Attributes
teleporter_list translocators
bool dialogue_by_radio = false
std::string preferred_aiming_mode
int movecounter = 0
units::energy power_prev_turn = 0_kJ
units::energy power_balance = 0_kJ
time_point last_pocket_noise = time_point(0)
vproto_id starting_vehicle = vproto_id::NULL_ID()
std::vector< mtype_id > starting_pets
std::set< character_id > follower_ids
bool aim_cache_dirty = true
Public Attributes inherited from Character
bool death_drops
Turned to false for simulating NPCs on distant missions so they don't drop all their gear in sight.
bool controlling_vehicle = false
Is currently in control of a vehicle.
int str_max
Character stats.
int dex_max
int int_max
int per_max
int str_cur
int dex_cur
int int_cur
int per_cur
int kill_xp = 0
int spent_upgrade_points = 0
float cached_organic_size
const profession * prof
std::set< const profession * > hobbies
tripoint grab_point
std::optional< city > starting_city
std::optional< point_abs_om > world_origin
bool random_start_location = true
start_location_id start_location
bool manual_examine = false
int volume = 0
int arms_power_use
Cache variables to store stamina use info these will be updated when the player's limb makeup changes _power_use is how many joules to spend per stamina instead of stamina (default 0) _stam_mult is how much to multiply the incoming stamina cost's stamina drain (default of 1)
int legs_power_use
float arms_stam_mult
float legs_stam_mult
int blocks_left
double recoil = MAX_RECOIL
std::string custom_profession
bool reach_attacking = false
std::vector< tripoint_abs_omt > omt_path
std::unordered_set< tripoint_abs_omt > map_revealed_omts
pimpl< known_magic > magic
std::string name
std::optional< std::string > play_name
bool male = false
std::vector< effect_on_condition_id > death_eocs
outfit worn
bool nv_cached = false
bool in_vehicle = false
bool hauling = false
bool autohaul = false
bool suppress_autohaul = false
std::string hauling_filter
std::vector< item_location > haul_list
tripoint view_offset
player_activity stashed_outbounds_activity
player_activity stashed_outbounds_backlog
player_activity activity
std::list< player_activity > backlog
std::optional< tripoint > destination_point
pimpl< inventory > inv
itype_id last_item
int scent = 0
pimpl< bionic_collection > my_bionics
pimpl< character_martial_arts > martial_arts_data
stomach_contents stomach
stomach_contents guts
std::list< consumption_event > consumption_history
int oxygen = 0
int slow_rad = 0
blood_type my_blood_type
bool blood_rh_factor = false
int avg_nat_bpm
int cash = 0
weak_ptr_fast< Creature > last_target
std::optional< tripoint > last_target_pos
item_location ammo_location
std::set< tripoint_abs_omt > camps
std::vector< addiction > addictions
std::vector< effect_on_condition_id > inactive_effect_on_condition_vector
queued_eocs queued_effect_on_conditions
shared_ptr_fast< monster > mounted_creature
int mounted_creature_id = 0
int activity_vehicle_part_index = -1
std::map< mutation_category_id, int > mutation_category_level
moncam_cache_t moncam_cache
pimpl< craft_command > last_craft
recipe_id lastrecipe
int last_batch
int str_bonus = 0
Bonuses to stats, calculated each turn.
int dex_bonus = 0
int per_bonus = 0
int int_bonus = 0
int str_bonus_hardcoded = 0
Hardcoded stats bonus.
int dex_bonus_hardcoded = 0
int per_bonus_hardcoded = 0
int int_bonus_hardcoded = 0
int enchantment_speed_bonus = 0
int lifestyle = 0
How healthy the character is.
int daily_health = 0
int health_tally = 0
int init_age = 25
age in years at character creation
int init_height = 175
height at character creation
creature_size size_class = creature_size::medium
Size class of character.
activity_tracker activity_history
int old_weary_level = 0
trap_map known_traps
std::map< std::string, double > cached_info
bool bio_soporific_powered_at_last_sleep_check = false
time_point last_sleep_check = calendar::turn_zero
last time we checked for sleep
std::map< faction_id, std::pair< int, time_point > > warning_record
warnings from a faction about bad behavior
std::unordered_map< trait_id, trait_data > my_mutations
Traits / mutations of the character.
std::unordered_set< trait_id > my_traits
Contains mutation ids of the base traits.
std::vector< const mutation_branch * > cached_mutations
Pointers to mutation branches in my_mutations.
std::vector< trait_id > mutations_to_remove
std::vector< trait_id > mutations_to_add
std::optional< units::mass > cached_weight_carried = std::nullopt
The amount of weight the Character is carrying.
pimpl< SkillLevelMap > _skills
pimpl< proficiency_set > _proficiencies
std::bitset< NUM_VISION_MODES > vision_mode_cache
int sight_max = 0
time_point time_died = calendar::before_time_starts
turn the character expired, if calendar::before_time_starts it has not been set yet.
pimpl< pathfinding_settings > path_settings
Cache for pathfinding settings.
int faction_api_version = 2
faction_id fac_id
faction * my_fac = nullptr
move_mode_id move_mode
std::map< vitamin_id, int > vitamin_levels
Current deficiency/excess quantity for each vitamin.
std::map< vitamin_id, std::pair< int, int > > daily_vitamins
Current quantity for each vitamin today first value is expected second value is actual (digested) in vitamin units.
pimpl< player_morale > morale
time_point next_climate_control_check
bool last_climate_control_ret
pimpl< enchant_cache > enchantment_cache
Public Attributes inherited from Creature
FacingDirection facing = FacingDirection::RIGHT
return the direction the creature is facing, for sdl horizontal flip
bool underwater
int archery_aim_counter = 0
Private Member Functions
npc & get_shadow_npc ()
Private Attributes
std::string save_id
std::unique_ptr< map_memory > player_map_memory
bool show_map_memory
std::vector< mission * > active_missions
Missions that the player has accepted and that are not finished (one way or the other).
std::vector< mission * > completed_missions
Missions that the player has successfully completed.
std::vector< mission * > failed_missions
Missions that have failed while being assigned to the player.
mission * active_mission
The currently active mission, or null if no mission is currently in progress.
std::unique_ptr< diary > a_diary
diary to track player progression and to write the players stroy
std::list< daily_calories > calorie_diary
The amount of calories spent and gained per day for the last 30 days.
std::unordered_set< itype_id > items_identified
std::set< snippet_id > snippets_read
object_type grab_type
monster_visible_info mon_visible
std::unique_ptr< npc > shadow_npc
The NPC that would control the avatar's character in the avatar's absence.
cata::mdarray< bool, point_bub_ms > aim_cache
Friends
class debug_menu::mission_debug
Additional Inherited Members
Public Types inherited from Character
enum class comfort_level : int {
impossible = -999 , uncomfortable = -7 , neutral = 0 , slightly_comfortable = 3 ,
comfortable = 5 , very_comfortable = 10
}
using cached_moncam = std::pair< monster const *, tripoint_abs_ms >
using moncam_cache_t = cata::flat_set< cached_moncam >
using trap_map = std::map< tripoint, std::string >
Public Types inherited from Creature
enum class Attitude : int { HOSTILE , NEUTRAL , FRIENDLY , ANY }
Simplified attitude towards any creature: hostile - hate, want to kill, etc.
Static Public Member Functions inherited from Character
static int thirst_speed_penalty (int thirst)
Returns the penalty to speed from thirst.
static int worn_position_to_index (int position)
static units::temperature_delta floor_bedding_warmth (const tripoint &pos)
Warmth from terrain, furniture, vehicle furniture and traps.
static units::temperature_delta floor_item_warmth (const tripoint &pos)
Warmth from clothing on the floor.
static int min_height (creature_size size_category=creature_size::medium)
Min, max and default heights for each size category of a character in centimeters.
static int default_height (creature_size size_category=creature_size::medium)
static int max_height (creature_size size_category=creature_size::medium)
Static Public Member Functions inherited from Creature
static std::string attitude_raw_string (Attitude att)
Simplified attitude string for unlocalized needs.
static const std::pair< translation, nc_color > & get_attitude_ui_data (Attitude att)
Creature Attitude as String and color.
static void load_hit_range (const JsonObject &)
Static Public Attributes inherited from Character
static const std::vector< material_id > fleshy = { material_flesh, material_hflesh }
Static Public Attributes inherited from Creature
static const std::map< std::string, creature_size > size_map
static const std::set< material_id > cmat_flesh
static const std::set< material_id > cmat_fleshnveg
static const std::set< material_id > cmat_flammable
static const std::set< material_id > cmat_flameres
static std::vector< int > dispersion_for_even_chance_of_good_hit
Protected Member Functions inherited from Character
void mod_stored_calories (int ncal, bool ignore_weariness=false)
void set_stored_calories (int cal)
float generic_weakpoint_skill (skill_id skill_1, skill_id skill_2, limb_score_id limb_score_1, limb_score_id limb_score_2) const
void set_mutation_unsafe (const trait_id &, const mutation_variant *=nullptr)
void on_move (const tripoint_abs_ms &old_pos) override
void do_skill_rust ()
void apply_mods (const trait_id &mut, bool add_remove)
Applies stat mods to character.
void mut_cbm_encumb (std::map< bodypart_id, encumbrance_data > &vals) const
Applies encumbrance from mutations and bionics only.
void apply_mut_encumbrance (std::map< bodypart_id, encumbrance_data > &vals) const
void calc_bmi_encumb (std::map< bodypart_id, encumbrance_data > &vals) const
Applies encumbrance from BMI.
void calc_bmi_encumb () const
void on_damage_of_type (const effect_source &source, int adjusted_damage, const damage_type_id &dt, const bodypart_id &bp) override
recipe_subset get_available_recipes (const inventory &crafting_inv, const std::vector< Character * > *helpers=nullptr) const
Return all available recipes (from books and companions)
Character ()
Character (Character &&) noexcept(map_is_noexcept)
Character & operator= (Character &&) noexcept(list_is_noexcept)
void swap_character (Character &other)
Protected Member Functions inherited from Creature
void set_pos_only (const tripoint &p)
void set_location (const tripoint_abs_ms &loc)
void set_killer (Creature *killer)
Creature ()
Creature (const Creature &)
Creature (Creature &&) noexcept(map_is_noexcept)
Creature & operator= (const Creature &)
Creature & operator= (Creature &&) noexcept
void store (JsonOut &jsout) const
These two functions are responsible for storing and loading the members of this class to/from json data.
void load (const JsonObject &jsin)
Protected Attributes inherited from Character
int focus_pool = 0
std::set< mtype_id > known_monsters
bionic_uid weapon_bionic_uid = 0
bionic_uid next_bionic_uid = 0
pimpl< recipe_subset > learned_recipes
Subset of learned recipes.
decltype(_skills) valid_autolearn_skills
Stamp of skills.
std::unordered_map< point_abs_omt, time_duration > overmap_time
Amount of time the player has spent in each overmap tile.
Protected Attributes inherited from Creature
anatomy_id creature_anatomy = anatomy_id("default_anatomy")
anatomy is the plan of the creature's body
std::map< bodypart_str_id, bodypart > body
this is the actual body of the creature
int moves
Creature * killer
std::optional< time_point > lifespan_end = std::nullopt
std::optional< character_id > summoner = std::nullopt
pimpl< effects_map > effects
std::queue< scheduled_effect, std::list< scheduled_effect > > scheduled_effects
std::queue< terminating_effect, std::list< terminating_effect > > terminating_effects
std::vector< damage_over_time_data > damage_over_time_map
std::unordered_map< std::string, std::string > values
int num_blocks = 0
int num_dodges = 0
int num_blocks_bonus = 0
int num_dodges_bonus = 0
std::map< damage_type_id, float > armor_bonus
int speed_base = 0
int speed_bonus = 0
float dodge_bonus = 0.0f
int block_bonus = 0
float hit_bonus = 0.0f
int bash_bonus = 0
int cut_bonus = 0
int size_bonus = 0
float bash_mult = 0.0f
float cut_mult = 0.0f
bool melee_quiet = false
int throw_resist = 0
time_point last_updated
bool fake = false
Related Functions inherited from visitable
item * find_parent (const item &it) const
std::vector< item * > parents (const item &it) const
bool has_item (const item &it) const
bool has_item_with (const std::function< bool(const item &)> &filter) const
bool has_quality (const quality_id &qual, int level, int qty) const
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const
Traverses this object and any child items contained using a visitor pattern.
std::list< item > remove_items_with (const std::function< bool(const item &e)> &filter, int count)
int charges_of (const itype_id &what, int limit, const std::function< bool(const item &)> &filter, const std::function< void(int)> &visitor, bool in_tools) const
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo, int limit, const std::function< bool(const item &)> &filter) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo, const std::function< bool(const item &)> &filter) const
Detailed Description
Definition at line 83 of file avatar.h.
Constructor & Destructor Documentation
avatar() [1/3]
avatar::avatar ()
Definition at line 160 of file avatar.cpp.
 {
     player_map_memory = std::make_unique<map_memory>();
     show_map_memory = true;
     active_mission = nullptr;
     grab_type = object_type::NONE;
     calorie_diary.emplace_front( );
     a_diary = nullptr;
 }
References a_diary, active_mission, calorie_diary, grab_type, NONE, player_map_memory, and show_map_memory.
Referenced by randomize().
avatar() [2/3]
avatar::avatar (const avatar &) delete
avatar() [3/3]
avatar::avatar (avatar &&) default
~avatar()
avatar::~avatar () override default
Member Function Documentation
activate_crouch_mode()
void avatar::activate_crouch_mode ()
Definition at line 1351 of file avatar.cpp.
 {
     if( !is_crouching() ) {
         set_movement_mode( move_mode_crouch );
     }
 }
References Character::is_crouching(), move_mode_crouch, and set_movement_mode().
Referenced by game::peek().
add_gained_calories()
void avatar::add_gained_calories (int cal) override virtual
Reimplemented from Character.
Definition at line 1628 of file avatar.cpp.
 {
     calorie_diary.front().gained += cal;
 }
References calorie_diary.
add_ingested_kcal()
void avatar::add_ingested_kcal (int kcal)
Definition at line 1618 of file avatar.cpp.
 {
     calorie_diary.front().ingested += kcal;
 }
References calorie_diary.
Referenced by Character::consume_effects().
add_pain_msg()
void avatar::add_pain_msg (int val, const bodypart_id & bp) const
Definition at line 1865 of file avatar.cpp.
 {
     if( has_flag( json_flag_PAIN_IMMUNE ) ) {
         return;
     }
     if( bp == bodypart_id( "bp_null" ) ) {
         if( val > 20 ) {
             add_msg_if_player( _( "Your body is wracked with excruciating pain!" ) );
         } else if( val > 10 ) {
             add_msg_if_player( _( "Your body is wracked with terrible pain!" ) );
         } else if( val > 5 ) {
             add_msg_if_player( _( "Your body is wracked with pain!" ) );
         } else if( val > 1 ) {
             add_msg_if_player( _( "Your body pains you!" ) );
         } else {
             add_msg_if_player( _( "Your body aches." ) );
         }
     } else {
         if( val > 20 ) {
             add_msg_if_player( _( "Your %s is wracked with excruciating pain!" ),
                                body_part_name_accusative( bp ) );
         } else if( val > 10 ) {
             add_msg_if_player( _( "Your %s is wracked with terrible pain!" ),
                                body_part_name_accusative( bp ) );
         } else if( val > 5 ) {
             add_msg_if_player( _( "Your %s is wracked with pain!" ),
                                body_part_name_accusative( bp ) );
         } else if( val > 1 ) {
             add_msg_if_player( _( "Your %s pains you!" ),
                                body_part_name_accusative( bp ) );
         } else {
             add_msg_if_player( _( "Your %s aches." ),
                                body_part_name_accusative( bp ) );
         }
     }
 }
References _, Character::add_msg_if_player(), body_part_name_accusative(), bp, Character::has_flag(), and json_flag_PAIN_IMMUNE.
add_profession_items()
void avatar::add_profession_items ()
Definition at line 610 of file newcharacter.cpp.
 {
     // Our profession should not be a hobby
     if( prof->is_hobby() ) {
         return;
     }
     std::list<item> prof_items = prof->items( outfit, get_mutations() );
     for( item &it : prof_items ) {
         if( it.has_flag( STATIC( flag_id( "WET" ) ) ) ) {
             it.active = true;
             it.item_counter = 450; // Give it some time to dry off
         }
         // TODO: debugmsg if food that isn't a seed is inedible
         if( it.has_flag( json_flag_no_auto_equip ) ) {
             it.unset_flag( json_flag_no_auto_equip );
             inv->push_back( it );
         } else if( it.has_flag( json_flag_auto_wield ) ) {
             it.unset_flag( json_flag_auto_wield );
             if( !has_wield_conflicts( it ) ) {
                 wield( it );
             } else {
                 inv->push_back( it );
             }
         } else if( it.is_armor() ) {
             if( can_wear( it ).success() ) {
                 wear_item( it, false, false );
             } else {
                 inv->push_back( it );
             }
         } else {
             inv->push_back( it );
         }
         if( it.is_book() ) {
             items_identified.insert( it.typeId() );
         }
     }
     recalc_sight_limits();
     calc_encumbrance();
 }
References Character::calc_encumbrance(), Character::can_wear(), flag_id, Character::get_mutations(), Character::has_wield_conflicts(), Character::inv, profession::is_hobby(), profession::items(), items_identified, json_flag_auto_wield, json_flag_no_auto_equip, Character::prof, Character::recalc_sight_limits(), STATIC, Character::wear_item(), and wield().
Referenced by game::start_game().
add_random_hobby()
void avatar::add_random_hobby (std::vector< profession_id > & choices)
Definition at line 1830 of file avatar.cpp.
 {
     const profession_id hobby = random_entry_removed( choices );
     hobbies.insert( &*hobby );
     // Add or remove traits from hobby
     for( const trait_and_var &cur : hobby->get_locked_traits() ) {
         toggle_trait( cur.trait );
     }
 }
References profession::get_locked_traits(), Character::hobbies, random_entry_removed(), and Character::toggle_trait().
Referenced by randomize_hobbies().
add_snippet()
void avatar::add_snippet (snippet_id snippet)
Definition at line 850 of file avatar.cpp.
 {
     if( has_seen_snippet( snippet ) ) {
         return;
     }
     snippets_read.emplace( snippet );
 }
References has_seen_snippet(), and snippets_read.
Referenced by item::basic_info().
add_spent_calories()
void avatar::add_spent_calories (int cal) override virtual
Reimplemented from Character.
Definition at line 1623 of file avatar.cpp.
 {
     calorie_diary.front().spent += cal;
 }
References calorie_diary.
advance_daily_calories()
void avatar::advance_daily_calories ()
Definition at line 1584 of file avatar.cpp.
 {
     calorie_diary.emplace_front( );
     if( calorie_diary.size() > 30 ) {
         calorie_diary.pop_back();
     }
 }
References calorie_diary.
Referenced by Character::update_body().
as_avatar() [1/2]
const avatar* avatar::as_avatar () const inline override virtual
Reimplemented from Creature.
Definition at line 120 of file avatar.h.
{
             return this;
         }
as_avatar() [2/2]
avatar* avatar::as_avatar () inline override virtual
Reimplemented from Creature.
Definition at line 117 of file avatar.h.
{
             return this;
         }
Referenced by vehicle::autodrive_controller::check_drivable().
basic_symbol_color()
nc_color avatar::basic_symbol_color () const override virtual
Creature symbol color.
Implements Creature.
Definition at line 902 of file avatar.cpp.
 {
     bool in_shell = has_active_mutation( trait_SHELL2 ) ||
                     has_active_mutation( trait_SHELL3 );
     if( has_effect( effect_onfire ) ) {
         return c_red;
     }
     if( has_effect( effect_stunned ) ) {
         return c_light_blue;
     }
     if( has_effect( effect_psi_stunned ) ) {
         return c_light_blue;
     }
     if( has_effect( effect_boomered ) ) {
         return c_pink;
     }
     if( in_shell ) {
         return c_magenta;
     }
     if( underwater ) {
         return c_blue;
     }
     if( has_active_bionic( bio_cloak ) ||
         is_wearing_active_optcloak() || has_trait( trait_DEBUG_CLOAK ) ) {
         return c_dark_gray;
     }
     return move_mode->symbol_color();
 }
References bio_cloak, c_blue, c_dark_gray, c_light_blue, c_magenta, c_pink, c_red, effect_boomered, effect_onfire, effect_psi_stunned, effect_stunned, Character::has_active_bionic(), Character::has_active_mutation(), Creature::has_effect(), Character::has_trait(), Character::is_wearing_active_optcloak(), move_mode::symbol_color(), trait_DEBUG_CLOAK, trait_SHELL2, trait_SHELL3, and Creature::underwater.
bionic_by_invlet()
bionic * avatar::bionic_by_invlet (int ch)
Returns the bionic with the given invlet, or NULL if no bionic has that invlet.
Definition at line 183 of file bionics_ui.cpp.
 {
     // space is a special case for unassigned
     if( ch == ' ' ) {
         return nullptr;
     }
     for( bionic &elem : *my_bionics ) {
         if( elem.invlet == ch ) {
             return &elem;
         }
     }
     return nullptr;
 }
References Character::my_bionics.
Referenced by get_free_invlet(), and power_bionics().
cant_see()
bool avatar::cant_see (const tripoint & p)
Definition at line 1233 of file avatar.cpp.
 {
     // calc based on recoil
     if( !last_target_pos.has_value() ) {
         return false;
     }
     if( aim_cache_dirty ) {
         rebuild_aim_cache();
     }
     return aim_cache[p.x][p.y];
 }
References aim_cache, aim_cache_dirty, Character::last_target_pos, rebuild_aim_cache(), tripoint::x, and tripoint::y.
Referenced by map::apparent_light_helper().
character_mood_face()
const mood_face_id & avatar::character_mood_face (bool clear_cache = false) const
Definition at line 66 of file mood_face.cpp.
 {
     static std::optional<mood_face_id> mood_face_cache;
     static bool mood_face_horizontal = false;
     const bool option_horizontal = get_option<std::string>( "MORALE_STYLE" ) == "horizontal";
     if( clear_cache ) {
         mood_face_cache.reset();
     }
     if( mood_face_cache.has_value() && mood_face_horizontal == option_horizontal ) {
         return mood_face_cache.value();
     }
     mood_face_horizontal = option_horizontal;
     std::string face_type;
     for( const trait_id &mut : get_mutations() ) {
         if( !mut->threshold ) {
             continue;
         }
         face_type = mut.str();
         break;
     }
     // Valid: DEFAULT and DEFAULT_HORIZONTAL
     if( face_type.empty() ) {
         face_type = "DEFAULT";
     }
     if( mood_face_horizontal ) {
         face_type.append( "_HORIZONTAL" );
     }
     // Valid: THRESH_MUT and THRESH_MUT_HORIZONTAL
     // Example: THRESH_BIRD and THRESH_BIRD_HORIZONTAL
     for( const mood_face &face_id : mood_face::get_all() ) {
         if( face_id.getId().str() == face_type ) {
             mood_face_cache = face_id.getId();
             break;
         }
     }
     // If we didn't get it first try, we're not getting it again
     if( !mood_face_cache.has_value() ) {
         if( mood_face_horizontal ) {
             mood_face_cache = mood_face_DEFAULT_HORIZONTAL;
         } else {
             mood_face_cache = mood_face_DEFAULT;
         }
     }
     return mood_face_cache.value();
 }
References mood_face::get_all(), Character::get_mutations(), mood_face_DEFAULT, and mood_face_DEFAULT_HORIZONTAL.
Referenced by control_npc(), Character::on_mutation_gain(), Character::on_mutation_loss(), and game::setup().
character_to_template()
void avatar::character_to_template (const std::string & name)
Definition at line 4828 of file newcharacter.cpp.
 {
     save_template( name, pool_type::TRANSFER );
 }
References Character::name, save_template(), and TRANSFER.
Referenced by main_menu::world_tab().
clear_identified()
void avatar::clear_identified ()
Definition at line 827 of file avatar.cpp.
 {
     items_identified.clear();
 }
References items_identified.
clear_nutrition()
void avatar::clear_nutrition ()
Definition at line 820 of file avatar.cpp.
 {
     calorie_diary.clear();
     calorie_diary.emplace_front();
     consumption_history.clear();
 }
References calorie_diary, and Character::consumption_history.
control_npc()
void avatar::control_npc (npc & np, bool debug = false)
Makes the avatar "take over" the given NPC, while the current avatar character becomes an NPC.
Definition at line 176 of file avatar.cpp.
 {
     if( !np.is_player_ally() ) {
         debugmsg( "control_npc() called on non-allied npc %s", np.name );
         return;
     }
     character_id new_character = np.getID();
     const std::function<void( npc & )> update_npc = [new_character]( npc & guy ) {
         guy.update_missions_target( get_avatar().getID(), new_character );
     };
     overmap_buffer.foreach_npc( update_npc );
     mission().update_world_missions_character( get_avatar().getID(), new_character );
     // move avatar character data into shadow npc
     swap_character( get_shadow_npc() );
     // swap target npc with shadow npc
     std::swap( get_shadow_npc(), np );
     // move shadow npc character data into avatar
     swap_character( get_shadow_npc() );
     // the avatar character is no longer a follower NPC
     g->remove_npc_follower( getID() );
     // the previous avatar character is now a follower
     g->add_npc_follower( np.getID() );
     np.set_fac( faction_your_followers );
     // perception and mutations may have changed, so reset light level caches
     g->reset_light_level();
     // center the map on the new avatar character
     const bool z_level_changed = g->vertical_shift( posz() );
     g->update_map( *this, z_level_changed );
     character_mood_face( true );
     profession_id prof_id = prof ? prof->ident() : profession::generic()->ident();
     get_event_bus().send<event_type::game_avatar_new>( /*is_new_game=*/false, debug,
             getID(), name, male, prof_id, custom_profession );
 }
References character_mood_face(), Character::custom_profession, debug_menu::debug(), debugmsg, faction_your_followers, overmapbuffer::foreach_npc(), g, game_avatar_new, profession::generic(), get_avatar(), get_event_bus(), get_shadow_npc(), Character::getID(), profession::ident(), npc::is_player_ally(), Character::male, Character::name, overmap_buffer, Creature::posz(), Character::prof, event_bus::send(), npc::set_fac(), cata::swap(), Character::swap_character(), and mission::update_world_missions_character().
Referenced by basecamp::choose_new_leader(), control_npc_menu(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control().
control_npc_menu()
void avatar::control_npc_menu (bool debug = false)
Open a menu to choose the NPC to take over.
Definition at line 211 of file avatar.cpp.
 {
     std::vector<shared_ptr_fast<npc>> followers;
     uilist charmenu;
     int charnum = 0;
     for( const character_id &elem : g->get_follower_list() ) {
         shared_ptr_fast<npc> follower = overmap_buffer.find_npc( elem );
         if( follower ) {
             followers.emplace_back( follower );
             charmenu.addentry( charnum++, true, MENU_AUTOASSIGN, follower->get_name() );
         }
     }
     if( followers.empty() ) {
         popup( _( "There's no one to take control of!" ) );
         return;
     }
     charmenu.w_y_setup = 0;
     charmenu.query();
     if( charmenu.ret < 0 || static_cast<size_t>( charmenu.ret ) >= followers.size() ) {
         return;
     }
     get_avatar().control_npc( *followers[charmenu.ret], debug );
 }
References _, uilist::addentry(), control_npc(), debug_menu::debug(), overmapbuffer::find_npc(), g, get_avatar(), MENU_AUTOASSIGN, overmap_buffer, popup(), uilist::query(), uilist::ret, and uilist::w_y_setup.
Referenced by basecamp::choose_new_leader(), debug_menu::control_npc_menu(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control_menu().
create()
bool avatar::create (character_type type, const std::string & tempname = "")
Definition at line 667 of file newcharacter.cpp.
 {
     set_wielded_item( item() );
     prof = profession::generic();
     set_scenario( scenario::generic() );
     const bool interactive = type != character_type::NOW &&
                              type != character_type::FULL_RANDOM;
     std::vector<std::string> character_tabs = {
         _( "POINTS" ),
         _( "SCENARIO" ),
         _( "PROFESSION" ),
         //~ Not scenery/backdrop, but previous life up to this point
         _( "BACKGROUND" ),
         _( "STATS" ),
         _( "TRAITS" ),
         _( "SKILLS" ),
         _( "DESCRIPTION" ),
     };
     tab_manager tabs( character_tabs );
     const std::string point_pool = get_option<std::string>( "CHARACTER_POINT_POOLS" );
     pool_type pool = pool_type::FREEFORM;
     if( point_pool == "multi_pool" ) {
         // if using legacy multipool only set it to that
         pool = pool_type::MULTI_POOL;
     }
     switch( type ) {
         case character_type::CUSTOM:
             randomize_cosmetics();
             break;
         case character_type::RANDOM:
             //random scenario, default name if exist
             randomize( true );
             tabs.position.last();
             break;
         case character_type::NOW:
             //default world, fixed scenario, random name
             randomize( false, true );
             break;
         case character_type::FULL_RANDOM:
             //default world, random scenario, random name
             randomize( true, true );
             break;
         case character_type::TEMPLATE:
             if( !load_template( tempname, /*out*/ pool ) ) {
                 return false;
             }
             // We want to prevent recipes known by the template from being applied to the
             // new character. The recipe list will be rebuilt when entering the game.
             // Except if it is a character transfer template
             if( pool != pool_type::TRANSFER ) {
                 forget_all_recipes();
             }
             tabs.position.last();
             break;
     }
     // Don't apply the default backgrounds on a template
     if( type != character_type::TEMPLATE ) {
         add_default_background();
     }
     auto nameExists = [&]( const std::string & name ) {
         return world_generator->active_world->save_exists( save_t::from_save_id( name ) ) &&
                !query_yn( _( "A save with the name '%s' already exists in this world.\n"
                              "Saving will overwrite the already existing character.\n\n"
                              "Continue anyways?" ), name );
     };
     set_body();
     const bool allow_reroll = type == character_type::RANDOM;
     do {
         if( !interactive ) {
             // no window is created because "Play now" does not require any configuration
             if( nameExists( name ) ) {
                 return false;
             }
             break;
         }
         if( pool == pool_type::TRANSFER ) {
             tabs.position.last();
         }
         switch( tabs.position.cur_index() ) {
             case 0:
                 set_points( tabs, *this, /*out*/ pool );
                 break;
             case 1:
                 set_scenario( tabs, *this, pool );
                 break;
             case 2:
                 set_profession( tabs, *this, pool );
                 break;
             case 3:
                 set_hobbies( tabs, *this, pool );
                 break;
             case 4:
                 set_stats( tabs, *this, pool );
                 break;
             case 5:
                 set_traits( tabs, *this, pool );
                 break;
             case 6:
                 set_skills( tabs, *this, pool );
                 break;
             case 7:
                 set_description( tabs, *this, allow_reroll, pool );
                 break;
         }
         if( tabs.quit ) {
             return false;
         }
     } while( !tabs.complete );
     if( pool == pool_type::TRANSFER ) {
         return true;
     }
     save_template( _( "Last Character" ), pool );
     initialize( type );
     return true;
 }
References _, Character::add_default_background(), tab_manager::complete, tab_list::cur_index(), CUSTOM, Character::forget_all_recipes(), FREEFORM, save_t::from_save_id(), FULL_RANDOM, profession::generic(), scenario::generic(), initialize(), item, tab_list::last(), load_template(), MULTI_POOL, Character::name, NOW, tab_manager::position, Character::prof, query_yn(), tab_manager::quit, RANDOM, randomize(), randomize_cosmetics(), save_template(), Creature::set_body(), set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), Character::set_wielded_item(), TEMPLATE, TRANSFER, type, and world_generator.
Referenced by main_menu::new_character_tab().
cycle_move_mode()
void avatar::cycle_move_mode ()
Definition at line 1365 of file avatar.cpp.
 {
     const move_mode_id next = current_movement_mode()->cycle();
     set_movement_mode( next );
     // if a movemode is disabled then just cycle to the next one
     if( !movement_mode_is( next ) ) {
         set_movement_mode( next->cycle() );
     }
 }
References Character::current_movement_mode(), move_mode::cycle(), Character::movement_mode_is(), and set_movement_mode().
Referenced by game::do_regular_action(), and open_movement_mode_menu().
cycle_move_mode_reverse()
void avatar::cycle_move_mode_reverse ()
Definition at line 1375 of file avatar.cpp.
 {
     const move_mode_id prev = current_movement_mode()->cycle_reverse();
     set_movement_mode( prev );
     // if a movemode is disabled then just cycle to the previous one
     if( !movement_mode_is( prev ) ) {
         set_movement_mode( prev->cycle_reverse() );
     }
 }
References Character::current_movement_mode(), move_mode::cycle_reverse(), Character::movement_mode_is(), and set_movement_mode().
Referenced by game::do_regular_action().
deserialize()
void avatar::deserialize (const JsonObject & data) override virtual
Implements Character.
Definition at line 1609 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     load( data );
 }
References item_pocket::data, and ammo_effects::load().
disarm()
void avatar::disarm (npc & target)
Try to disarm the NPC.
May result in fail attempt, you receiving the weapon and instantly wielding it, or the weapon falling down on the floor nearby. NPC is always getting angry with you.
Parameters
target Target NPC to disarm
@ARM_STR increases chance to disarm, primary stat
Dexterity increases chance to disarm, secondary stat
Grip strength modifies all disarm rolls
Melee increases chance to disarm Unarmed increases chance to disarm, bonus when nothing wielded
Definition at line 2845 of file melee.cpp.
 {
     if( !target.is_armed() ) {
         return;
     }
     if( target.is_hallucination() ) {
         target.on_attacked( *this );
         return;
     }
     /** @ARM_STR increases chance to disarm, primary stat */
     /** @EFFECT_DEX increases chance to disarm, secondary stat */
     /** Grip strength modifies all disarm rolls */
     int my_roll = dice( 3, get_limb_score( limb_score_grip ) * get_arm_str() + get_dex() );
     /** @EFFECT_MELEE increases chance to disarm */
     my_roll += dice( 3, round( get_skill_level( skill_melee ) ) );
     int their_roll = dice( 3, target.get_limb_score( limb_score_grip ) * target.get_arm_str() +
                            target.get_dex() );
     their_roll *= target.get_limb_score( limb_score_reaction );
     their_roll += dice( 3, round( target.get_skill_level( skill_melee ) ) );
     item_location it = target.get_wielded_item();
     const item_location weapon = get_wielded_item();
     if( it->has_flag( flag_INTEGRATED ) ) {
         return;
     };
     // roll your melee and target's dodge skills to check if grab/smash attack succeeds
     int hitspread = target.deal_melee_attack( this, hit_roll() );
     if( hitspread < 0 ) {
         add_msg( _( "You lunge for the %s, but miss!" ), it->tname() );
         item weap = get_wielded_item() ? *get_wielded_item() : null_item_reference();
         mod_moves( -100 - stumble( *this, weapon ) - attack_speed( weap ) );
         target.on_attacked( *this );
         return;
     }
     map &here = get_map();
     // hitspread >= 0, which means we are going to disarm by grabbing target by their weapon
     if( !is_armed() ) {
         /** @EFFECT_UNARMED increases chance to disarm, bonus when nothing wielded */
         my_roll += dice( 3, round( get_skill_level( skill_unarmed ) ) );
         if( my_roll >= their_roll ) {
             //~ %s: weapon name
             add_msg( _( "You grab at %s and pull with all your force!" ), it->tname() );
             //~ %1$s: weapon name, %2$s: NPC name
             add_msg( _( "You forcefully take %1$s from %2$s!" ), it->tname(), target.get_name() );
             // wield() will deduce our moves, consider to deduce more/less moves for balance
             item rem_it = target.i_rem( &*it );
             wield( rem_it );
         } else if( my_roll >= their_roll / 2 ) {
             add_msg( _( "You grab at %s and pull with all your force, but it drops nearby!" ),
                      it->tname() );
             const tripoint tp = target.pos() + tripoint( rng( -1, 1 ), rng( -1, 1 ), 0 );
             here.add_item_or_charges( tp, target.i_rem( &*it ) );
             mod_moves( -100 );
         } else {
             add_msg( _( "You grab at %s and pull with all your force, but in vain!" ), it->tname() );
             mod_moves( -100 );
         }
         target.on_attacked( *this );
     } else {
         // Make their weapon fall on floor if we've rolled enough.
         mod_moves( -100 - attack_speed( *get_wielded_item() ) );
         if( my_roll >= their_roll ) {
             add_msg( _( "You smash %s with all your might forcing their %s to drop down nearby!" ),
                      target.get_name(), it->tname() );
             const tripoint tp = target.pos() + tripoint( rng( -1, 1 ), rng( -1, 1 ), 0 );
             here.add_item_or_charges( tp, target.i_rem( &*it ) );
         } else {
             add_msg( _( "You smash %s with all your might but %s remains in their hands!" ),
                      target.get_name(), it->tname() );
         }
         target.on_attacked( *this );
     }
 }
References _, map::add_item_or_charges(), add_msg(), Character::attack_speed(), Creature::deal_melee_attack(), dice(), flag_INTEGRATED, Character::get_arm_str(), Character::get_dex(), Character::get_limb_score(), get_map(), Character::get_name(), Character::get_skill_level(), Character::get_wielded_item(), item::has_flag(), Character::hit_roll(), Character::i_rem(), Character::is_armed(), npc::is_hallucination(), limb_score_grip, limb_score_reaction, Creature::mod_moves(), null_item_reference(), npc::on_attacked(), Creature::pos(), rng(), round(), skill_melee, skill_unarmed, stumble(), item::tname(), tripoint, Character::weapon, and wield().
Referenced by game::npc_menu().
disp_medical()
void avatar::disp_medical ()
Opens the medical window.
Definition at line 692 of file medical_ui.cpp.
 {
     // Windows
     catacurses::window w_title; // Title Bar - Tabs, Pain Indicator & Blood Indicator
     catacurses::window wMedical; // Primary Window
     catacurses::window w_description; // Bottom Detail Bar
     // Window Definitions
     const int TITLE_W_HEIGHT = 3;
     const int DESC_W_HEIGHT = 6; // Consistent with Player Info (@) Menu
     const int HEADER_Y = TITLE_W_HEIGHT;
     const int TEXT_START_Y = HEADER_Y + 2;
     const int INFO_START_Y = HEADER_Y + 8;
     int DESC_W_BEGIN;
     int HEIGHT;
     int WIDTH;
     // Column Definitions
     int second_column_x = 0;
     int third_column_x = 0;
     // Scrolling
     int SCROLL_POINT; // The number of printed rows at which to enable scrolling
     int scroll_position = 0;
     int INFO_SCROLL_POINT;
     int info_scroll_position = 0;
     int info_lines = 0;
     // Cursor
     std::array<int, 3> cursor_bounds; // Number of selectable rows in each column
     point cursor;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         const int WIDTH_OFFSET = ( TERMX - FULL_SCREEN_WIDTH ) / 4;
         HEIGHT = std::min( TERMY, FULL_SCREEN_HEIGHT );
         WIDTH = FULL_SCREEN_WIDTH + WIDTH_OFFSET;
         const point win( ( TERMX - WIDTH ) / 2, ( TERMY - HEIGHT ) / 2 );
         wMedical = catacurses::newwin( HEIGHT, WIDTH, win );
         w_title = catacurses::newwin( TITLE_W_HEIGHT, WIDTH, win );
         DESC_W_BEGIN = HEIGHT - DESC_W_HEIGHT - 1;
         w_description = catacurses::newwin( DESC_W_HEIGHT, WIDTH - 2,
                                             win + point( 1, DESC_W_BEGIN ) );
         //40% - 30% - 30%
         second_column_x = WIDTH / 2.5f;
         third_column_x = second_column_x + WIDTH / 3.3f;
         ui.position_from_window( wMedical );
     } );
     ui.mark_resize();
     ui.on_redraw( [&]( const ui_adaptor & ) {
         werase( wMedical );
         draw_border( wMedical, BORDER_COLOR, _( " MEDICAL " ) );
         mvwputch( wMedical, point( getmaxx( wMedical ) - 1, 2 ), BORDER_COLOR, LINE_XOXX ); // -|
         wnoutrefresh( wMedical );
         draw_medical_titlebar( w_title, this, WIDTH );
         mvwputch( w_title, point( second_column_x, HEADER_Y - 1 ), BORDER_COLOR, LINE_OXXX ); // ^|^
         mvwputch( w_title, point( third_column_x, HEADER_Y - 1 ), BORDER_COLOR, LINE_OXXX ); // ^|^
         wnoutrefresh( w_title );
         SCROLL_POINT = HEIGHT - TEXT_START_Y - DESC_W_HEIGHT - 3;
         // Columns
         int column_id = 0;
         // Health Summary
         fold_and_print( wMedical, point( 2, HEADER_Y ), WIDTH - 2, c_light_blue, _( "HEALTH" ) );
         medical_column health_column = draw_health_summary( column_id++, this, point( 0, TEXT_START_Y ),
                                        std::pair<int, int>( second_column_x, HEIGHT ) );
         // Effects Summary
         mvwprintz( wMedical, point( second_column_x + 2, HEADER_Y ), c_light_blue, _( "EFFECTS" ) );
         medical_column effects_column = draw_effects_summary( column_id++, this, point( second_column_x,
                                         TEXT_START_Y ), std::pair<int, int>( third_column_x, HEIGHT ) );
         // Stats Summary
         mvwprintz( wMedical, point( third_column_x + 2, HEADER_Y ), c_light_blue, _( "STATS" ) );
         medical_column stats_column = draw_stats_summary( column_id++, this, point( third_column_x,
                                       TEXT_START_Y ), std::pair<int, int>( WIDTH - 2, 5 ) );
         // Description Text
         std::string desc_str;
         std::pair<std::string, std::string> detail_str;
         switch( cursor.x ) {
             case 0:
                 desc_str = health_column.set_highlight( cursor.y ).description();
                 detail_str = health_column.detail_str( cursor.y );
                 break;
             case 1:
                 desc_str = effects_column.set_highlight( cursor.y ).description();
                 detail_str = effects_column.detail_str( cursor.y );
                 break;
             case 2:
                 desc_str = stats_column.set_highlight( cursor.y ).description();
                 detail_str = stats_column.detail_str( cursor.y );
                 break;
             default:
                 break;
         }
         // Description Bar
         werase( w_description );
         int DESCRIPTION_WIN_OFFSET; // Y Position of the start of the description bar (wMedical)
         if( !desc_str.empty() ) {
             // Number of display rows required by the highlighted line.
             std::vector<std::string> textformatted = foldstring( desc_str, WIDTH - 2, ' ' );
             // Beginning row of description text [0-6] (w_description)
             const int DESCRIPTION_TEXT_Y = DESC_W_HEIGHT - std::min( DESC_W_HEIGHT,
                                            static_cast<int>( textformatted.size() ) );
             DESCRIPTION_WIN_OFFSET = DESC_W_BEGIN + DESCRIPTION_TEXT_Y;
             mvwputch( wMedical, point( 0, DESCRIPTION_WIN_OFFSET - 1 ), BORDER_COLOR, LINE_XXXO );
             mvwhline( wMedical, point( 1, DESCRIPTION_WIN_OFFSET - 1 ), LINE_OXOX, getmaxx( wMedical ) - 2 );
             mvwputch( wMedical, point( getmaxx( wMedical ) - 1, DESCRIPTION_WIN_OFFSET - 1 ), BORDER_COLOR,
                       LINE_XOXX );
             fold_and_print( w_description, point( 1, DESCRIPTION_TEXT_Y ), WIDTH - 2, c_light_gray,
                             desc_str );
         } else {
             DESCRIPTION_WIN_OFFSET = getmaxy( wMedical );
         }
         wnoutrefresh( w_description );
         // Info Menu
         INFO_SCROLL_POINT = HEIGHT - INFO_START_Y - DESC_W_HEIGHT - 3;
         const int INFO_CUTOFF = DESCRIPTION_WIN_OFFSET - 1 - ( INFO_START_Y + 3 );
         if( !detail_str.first.empty() ) {
             mvwprintz( wMedical, point( third_column_x + 2, INFO_START_Y + 1 ), c_light_blue,
                        detail_str.first );
             mvwputch( wMedical, point( third_column_x, INFO_START_Y ), BORDER_COLOR, LINE_XXXO ); // |-
             mvwhline( wMedical, point( third_column_x + 1, INFO_START_Y ), LINE_OXOX,
                       getmaxx( wMedical ) - 2 ); // -
             mvwputch( wMedical, point( getmaxx( wMedical ) - 1, INFO_START_Y ), BORDER_COLOR, // -|
                       LINE_XOXX );
             const int info_width = WIDTH - third_column_x - 3;
             std::vector<std::string> textformatted = foldstring( detail_str.second, info_width,
                     ' ' );
             info_lines = textformatted.size();
             int i = 0;
             for( std::string &line : textformatted ) {
                 if( i - info_scroll_position >= INFO_CUTOFF ) {
                     break;
                 }
                 if( i++ >= info_scroll_position ) {
                     trim_and_print( wMedical, point( third_column_x + 2, INFO_START_Y + 2 + i - info_scroll_position ),
                                     info_width, c_light_gray, line );
                 }
             }
         } else {
             info_lines = 0;
         }
         // Draw Selection Lines For Each Column
         const int MAX_COLUMN_HEIGHT = DESCRIPTION_WIN_OFFSET - 1;
         health_column.print_column( wMedical,
                                     health_column.current_column( cursor.x ) ? scroll_position : 0, MAX_COLUMN_HEIGHT );
         effects_column.print_column( wMedical,
                                      effects_column.current_column( cursor.x ) ? scroll_position : 0, MAX_COLUMN_HEIGHT );
         stats_column.print_column( wMedical, stats_column.current_column( cursor.x ) ? scroll_position : 0,
                                    MAX_COLUMN_HEIGHT );
         // Update Cursor Boundaries to number of selectable rows
         cursor_bounds[0] = health_column.selection_count();
         cursor_bounds[1] = effects_column.selection_count();
         cursor_bounds[2] = stats_column.selection_count();
         // Draw Column Borders
         effects_column.draw_column( wMedical, HEADER_Y, DESCRIPTION_WIN_OFFSET );
         stats_column.draw_column( wMedical, HEADER_Y, DESCRIPTION_WIN_OFFSET );
         // Draw Scrollbars
         const int content_size = ( cursor_bounds[cursor.x] - 1 ) * 2;
         scrollbar()
         .offset_x( 0 )
         .offset_y( HEADER_Y )
         .content_size( content_size )
         .viewport_pos( cursor.y * 2 )
         .viewport_size( DESC_W_BEGIN - 3 )
         .scroll_to_last( true )
         .apply( wMedical );
         scrollbar()
         .offset_x( third_column_x )
         .offset_y( INFO_START_Y + 1 )
         .content_size( info_lines + INFO_SCROLL_POINT )
         .viewport_pos( info_scroll_position )
         .viewport_size( INFO_SCROLL_POINT + 1 )
         .scroll_to_last( true )
         .apply( wMedical );
         wnoutrefresh( wMedical );
     } );
     input_context ctxt( "MEDICAL" );
     ctxt.register_action( "UP" );
     ctxt.register_action( "DOWN" );
     ctxt.register_action( "LEFT" );
     ctxt.register_action( "RIGHT" );
     ctxt.register_action( "APPLY" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "SCROLL_INFOBOX_UP", to_translation( "Scroll up" ) );
     ctxt.register_action( "SCROLL_INFOBOX_DOWN", to_translation( "Scroll down" ) );
     ctxt.register_action( "QUIT" );
     for( ;; ) {
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         if( action == "DOWN" || action == "UP" ) {
             const int step = cursor.y + ( action == "DOWN" ? 1 : -1 );
             const int limit = cursor_bounds[cursor.x] - 1;
             if( step == -1 ) {
                 cursor.y = limit;
             } else if( step > limit ) {
                 cursor.y = 0;
             } else {
                 cursor.y = step;
             }
             const int scroll_overflow = limit - SCROLL_POINT;
             if( scroll_overflow > 0 ) {
                 const int half_list = SCROLL_POINT / 2;
                 scroll_position = std::max( 0, std::min( scroll_overflow, cursor.y - half_list ) );
             }
             info_scroll_position = 0;
         } else if( action == "RIGHT" || action == "LEFT" ) {
             const int step = cursor.x + ( action == "RIGHT" ? 1 : -1 );
             const int limit = 2;
             if( step == -1 ) {
                 cursor.x = limit;
             } else if( step > limit ) {
                 cursor.x = 0;
             } else {
                 cursor.x = step;
             }
             // Match the cursor to the nearest row on the next column.
             const int y_limit = cursor_bounds[cursor.x] - 1;
             cursor.y = std::min( cursor.y - scroll_position, y_limit );
             const int scroll_overflow = y_limit - SCROLL_POINT;
             if( scroll_overflow > 0 ) {
                 const int half_list = SCROLL_POINT / 2;
                 scroll_position = std::max( 0, std::min( scroll_overflow, cursor.y - half_list ) );
             } else {
                 scroll_position = 0;
             }
             info_scroll_position = 0;
         } else if( action == "APPLY" ) {
             avatar_action::use_item( *this );
         } else if( action == "SCROLL_INFOBOX_UP" || action == "SCROLL_INFOBOX_DOWN" ) {
             const int scroll_overflow = info_lines - INFO_SCROLL_POINT - 1;
             if( scroll_overflow > 0 ) {
                 const int step = info_scroll_position + ( action == "SCROLL_INFOBOX_DOWN" ? 1 : -1 );
                 if( step == -1 ) {
                     info_scroll_position = scroll_overflow;
                 } else if( step > scroll_overflow ) {
                     info_scroll_position = 0;
                 } else {
                     info_scroll_position = step;
                 }
             } else {
                 info_scroll_position = 0;
             }
         } else if( action == "QUIT" ) {
             break;
         }
     }
 }
References _, action, scrollbar::apply(), BORDER_COLOR, c_light_blue, c_light_gray, scrollbar::content_size(), medical_column::current_column(), selection_line::description(), medical_column::detail_str(), draw_border(), medical_column::draw_column(), draw_effects_summary(), draw_health_summary(), draw_medical_titlebar(), draw_stats_summary(), fold_and_print(), foldstring(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, catacurses::getmaxx(), catacurses::getmaxy(), input_context::handle_input(), char_creation::HEIGHT, line, LINE_OXOX, LINE_OXXX, LINE_XOXX, LINE_XXXO, max(), min(), catacurses::mvwhline(), mvwprintz(), mvwputch(), catacurses::newwin(), scrollbar::offset_x(), scrollbar::offset_y(), point, medical_column::print_column(), ui_manager::redraw(), input_context::register_action(), scrollbar::scroll_to_last(), medical_column::selection_count(), medical_column::set_highlight(), TERMX, TERMY, to_translation(), trim_and_print(), avatar_action::use_item(), scrollbar::viewport_pos(), scrollbar::viewport_size(), catacurses::werase(), catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by game::do_regular_action(), and handle_player_display_action().
disp_morale()
void avatar::disp_morale ()
Provides the window and detailed morale data.
Definition at line 943 of file avatar.cpp.
 {
     int equilibrium = calc_focus_equilibrium();
     int sleepiness_penalty = 0;
     const int sleepiness_cap = focus_equilibrium_sleepiness_cap( equilibrium );
     if( sleepiness_cap < equilibrium ) {
         sleepiness_penalty = equilibrium - sleepiness_cap;
         equilibrium = sleepiness_cap;
     }
     int pain_penalty = 0;
     if( get_perceived_pain() && !has_trait( trait_CENOBITE ) ) {
         pain_penalty = calc_focus_equilibrium( true ) - equilibrium - sleepiness_penalty;
     }
     morale->display( equilibrium, pain_penalty, sleepiness_penalty );
 }
References Character::calc_focus_equilibrium(), Character::focus_equilibrium_sleepiness_cap(), Character::get_perceived_pain(), Character::has_trait(), Character::morale, and trait_CENOBITE.
Referenced by game::do_regular_action(), and handle_player_display_action().
export_as_npc()
void avatar::export_as_npc (const cata_path & path)
Definition at line 2070 of file avatar.cpp.
 {
     swap_character( get_shadow_npc() );
     get_shadow_npc().export_to( path );
     swap_character( get_shadow_npc() );
 }
References npc::export_to(), get_shadow_npc(), and Character::swap_character().
Referenced by debug_menu::debug().
free_upgrade_points()
int avatar::free_upgrade_points () const
Definition at line 1134 of file avatar.cpp.
 {
     int lvl = 0;
     for( const int &xp_lvl : xp_cutoffs ) {
         if( kill_xp >= xp_lvl ) {
             lvl++;
         } else {
             break;
         }
     }
     return lvl - spent_upgrade_points;
 }
References Character::kill_xp, Character::spent_upgrade_points, and xp_cutoffs.
Referenced by upgrade_stat_prompt().
get_active_mission()
mission * avatar::get_active_mission () const
Returns the mission that is currently active.
Returns null if mission is active.
Definition at line 326 of file avatar.cpp.
 {
     return active_mission;
 }
References active_mission.
get_active_mission_target()
tripoint_abs_omt avatar::get_active_mission_target () const
Returns the target of the active mission or overmap::invalid_tripoint if there is no active mission.
Definition at line 339 of file avatar.cpp.
 {
     if( active_mission == nullptr ) {
         return overmap::invalid_tripoint;
     }
     return active_mission->get_target();
 }
References active_mission, mission::get_target(), and overmap::invalid_tripoint.
Referenced by overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), and display::mission_arrow_offset().
get_active_missions()
std::vector< mission * > avatar::get_active_missions () const
Definition at line 311 of file avatar.cpp.
 {
     return active_missions;
 }
References active_missions.
Referenced by computer_session::action_emerg_ref_center(), computer_session::action_repeater_mod(), mission_ui_impl::draw_controls(), overmap_ui::draw_om_sidebar(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_active_mission(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_mission(), talker_npc::get_topics(), mission::is_complete(), and mission::on_creature_death().
get_AIM_inventory()
std::vector< advanced_inv_listitem > avatar::get_AIM_inventory (const advanced_inventory_pane & pane, advanced_inv_area & square)
gets the inventory from the avatar that is interactible via advanced inventory management
Definition at line 156 of file advanced_inv_pane.cpp.
 {
     size_t item_index = 0;
     std::vector<advanced_inv_listitem> items = worn.get_AIM_inventory( item_index, *this, pane,
             square );
     item_location weapon = get_wielded_item();
     if( weapon && weapon->is_container() ) {
         for( const std::vector<item_location> &it_stack : item_list_to_stack( weapon,
                 weapon->all_items_top( pocket_type::CONTAINER ) ) ) {
             advanced_inv_listitem adv_it( it_stack, item_index++, square.id, false );
             if( !pane.is_filtered( *adv_it.items.front() ) ) {
                 square.volume += adv_it.volume;
                 square.weight += adv_it.weight;
                 items.push_back( adv_it );
             }
         }
     }
     return items;
 }
References item::all_items_top(), CONTAINER, outfit::get_AIM_inventory(), Character::get_wielded_item(), item::is_container(), advanced_inventory_pane::is_filtered(), item_list_to_stack(), advanced_inv_listitem::items, square(), advanced_inv_listitem::volume, Character::weapon, advanced_inv_listitem::weight, and Character::worn.
get_avatar_diary()
diary * avatar::get_avatar_diary ()
Definition at line 424 of file avatar.cpp.
 {
     if( a_diary == nullptr ) {
         a_diary = std::make_unique<diary>();
     }
     return a_diary.get();
 }
References a_diary.
Referenced by game::death_screen(), game::do_regular_action(), game::load(), and game::save_player_data().
get_completed_missions()
std::vector< mission * > avatar::get_completed_missions () const
Definition at line 316 of file avatar.cpp.
 {
     return completed_missions;
 }
References completed_missions.
Referenced by computer_session::action_emerg_ref_center(), and mission_ui_impl::draw_controls().
get_daily_ingested_kcal()
int avatar::get_daily_ingested_kcal (bool yesterday) const
Definition at line 1605 of file avatar.cpp.
 {
     if( yesterday ) {
         if( calorie_diary.size() < 2 ) {
             return 0;
         }
         std::list<avatar::daily_calories> copy = calorie_diary;
         copy.pop_front();
         return copy.front().ingested;
     }
     return calorie_diary.front().ingested;
 }
References calorie_diary.
Referenced by iuse::calories_intake_tracker(), iuse::fitness_check(), and get_consume_needs_hint().
get_daily_spent_kcal()
int avatar::get_daily_spent_kcal (bool yesterday) const
Definition at line 1592 of file avatar.cpp.
 {
     if( yesterday ) {
         if( calorie_diary.size() < 2 ) {
             return 0;
         }
         std::list<avatar::daily_calories> copy = calorie_diary;
         copy.pop_front();
         return copy.front().spent;
     }
     return calorie_diary.front().spent;
 }
References calorie_diary.
Referenced by iuse::fitness_check(), and get_consume_needs_hint().
get_faction()
faction * avatar::get_faction () const override virtual
Reimplemented from Character.
Definition at line 1210 of file avatar.cpp.
 {
     return g->faction_manager_ptr->get( faction_your_followers );
 }
References faction_your_followers, and g.
Referenced by debug_menu::debug().
get_failed_missions()
std::vector< mission * > avatar::get_failed_missions () const
Definition at line 321 of file avatar.cpp.
 {
     return failed_missions;
 }
References failed_missions.
Referenced by mission_ui_impl::draw_controls().
get_grab_type()
object_type avatar::get_grab_type () const
Definition at line 733 of file avatar.cpp.
 {
     return grab_type;
 }
References grab_type.
Referenced by Character::dismount(), map::draw_maptile(), Character::forced_dismount(), map::furn_set(), grab(), game::grabbed_move(), advanced_inv_area::init(), Character::mount_creature(), activity_handlers::move_cost(), game::npc_menu(), DefaultRemovePartHandler::removed(), Character::stagger(), vehicle_folding_activity_actor::start(), and game::walk_move().
get_memorized_tile()
const memorized_tile & avatar::get_memorized_tile (const tripoint_abs_ms & p) const
Definition at line 281 of file avatar.cpp.
 {
     if( should_show_map_memory() ) {
         return player_map_memory->get_tile( p );
     }
     return mm_submap::default_tile;
 }
References mm_submap::default_tile, player_map_memory, and should_show_map_memory().
Referenced by vehicle::autodrive_controller::check_drivable(), map::get_known_connections(), and get_memory_at().
get_mon_visible() [1/2]
monster_visible_info& avatar::get_mon_visible () inline
Definition at line 326 of file avatar.h.
{
             return mon_visible;
         }
References mon_visible.
Referenced by jmapgen_remove_npcs::apply(), game::check_safe_mode_allowed(), game::cleanup_dead(), display::colorized_compass_legend_text(), game::do_regular_action(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_monsters_in_direction(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_safe_mode_trigger(), get_compass_for_direction(), game::mon_info_update(), and game::place_player().
get_mon_visible() [2/2]
const monster_visible_info& avatar::get_mon_visible () const inline
Definition at line 330 of file avatar.h.
{
             return mon_visible;
         }
References mon_visible.
get_monster_faction()
mfaction_id avatar::get_monster_faction () const override virtual
Implements Creature.
Definition at line 938 of file avatar.cpp.
 {
     return monfaction_player.id();
 }
References string_id< T >::id(), and monfaction_player.
get_save_id()
std::string avatar::get_save_id () const inline
Definition at line 128 of file avatar.h.
{
             return save_id.empty() ? name : save_id;
         }
References Character::name, and save_id.
Referenced by debug_menu::character_edit_desc_menu(), game::move_save_to_graveyard(), game::quickload(), and game::save().
get_shadow_npc()
npc & avatar::get_shadow_npc () private
Definition at line 2059 of file avatar.cpp.
 {
     if( !shadow_npc ) {
         shadow_npc = std::make_unique<npc>();
         shadow_npc->op_of_u.trust = 10;
         shadow_npc->op_of_u.value = 10;
         shadow_npc->set_attitude( NPCATT_FOLLOW );
     }
     return *shadow_npc;
 }
References NPCATT_FOLLOW, and shadow_npc.
Referenced by control_npc(), and export_as_npc().
get_snippets()
const std::set< snippet_id > & avatar::get_snippets ()
Definition at line 864 of file avatar.cpp.
 {
     return snippets_read;
 }
References snippets_read.
Referenced by faction_manager::display().
grab()
void avatar::grab (object_type grab_type, const tripoint & grab_point = tripoint_zero)
Definition at line 699 of file avatar.cpp.
 {
     const auto update_memory =
     [this]( const object_type gtype, const tripoint & gpoint, const bool erase ) {
         map &m = get_map();
         if( gtype == object_type::VEHICLE ) {
             if( const optional_vpart_position ovp = m.veh_at( pos() + gpoint ) ) {
                 for( const tripoint &target : ovp->vehicle().get_points() ) {
                     if( erase ) {
                         memorize_clear_decoration( m.getglobal( target ), /* prefix = */ "vp_" );
                     }
                     m.memory_cache_dec_set_dirty( target, true );
                 }
             }
         } else if( gtype != object_type::NONE ) {
             if( erase ) {
                 memorize_clear_decoration( m.getglobal( pos() + gpoint ) );
             }
             m.memory_cache_dec_set_dirty( pos() + gpoint, true );
         }
     };
     // Mark the area covered by the previous vehicle/furniture/etc for re-memorizing.
     update_memory( grab_type, grab_point, /* erase = */ false );
     grab_type = grab_type_new;
     grab_point = grab_point_new;
     // Clear the map memory for the area covered by the vehicle/furniture/etc to
     // eliminate ghost vehicles/furnitures/etc.
     update_memory( grab_type, grab_point, /* erase = */ true );
     path_settings->avoid_rough_terrain = grab_type != object_type::NONE;
 }
References catacurses::erase(), get_map(), map::getglobal(), Character::grab_point, grab_type, memorize_clear_decoration(), map::memory_cache_dec_set_dirty(), NONE, Character::path_settings, Creature::pos(), map::veh_at(), and VEHICLE.
Referenced by move_furniture_activity_actor::canceled(), Character::dismount(), Character::forced_dismount(), map::furn_set(), grab(), game::grabbed_furn_move(), game::grabbed_move(), game::grabbed_veh_move(), iexamine::ledge(), vehicle::merge_appliance_into_grid(), Character::mount_creature(), game::phasing_move(), DefaultRemovePartHandler::removed(), Character::stagger(), vehicle_folding_activity_actor::start(), game::vertical_move(), and game::walk_move().
has_identified()
bool avatar::has_identified (const itype_id & item_id) const override virtual
Note that we've read a book at least once.
Implements Character.
Definition at line 738 of file avatar.cpp.
 {
     return items_identified.count( item_id ) > 0;
 }
References items_identified.
Referenced by basic_item_filter(), item::book_info(), identify(), read_inventory_preset::is_known(), read_activity_actor::player_read(), read_activity_actor::player_readma(), and read().
has_mission_id()
bool avatar::has_mission_id (const mission_type_id & miss_id)
Returns true if character has the mission in their active missions list.
Definition at line 394 of file avatar.cpp.
 {
     for( mission *miss : active_missions ) {
         if( miss->mission_id() == miss_id ) {
             return true;
         }
     }
     return false;
 }
References active_missions.
Referenced by computer_session::action_repeater_mod().
has_seen_snippet()
bool avatar::has_seen_snippet (const snippet_id & snippet) const
Definition at line 859 of file avatar.cpp.
 {
     return snippets_read.count( snippet ) > 0;
 }
References snippets_read.
Referenced by add_snippet().
identify()
void avatar::identify (const item & item) override virtual
Implements Character.
Definition at line 743 of file avatar.cpp.
 {
     if( has_identified( item.typeId() ) ) {
         return;
     }
     if( !item.is_book() ) {
         debugmsg( "tried to identify non-book item" );
         return;
     }
     const ::item &book = item; // alias
     cata_assert( !has_identified( item.typeId() ) );
     items_identified.insert( item.typeId() );
     cata_assert( has_identified( item.typeId() ) );
     const auto &reading = item.type->book;
     const skill_id &skill = reading->skill;
     add_msg( _( "You skim %s to find out what's in it." ), book.type_name() );
     if( skill && get_skill_level_object( skill ).can_train() ) {
         add_msg( m_info, _( "Can bring your %s knowledge to %d." ),
                  skill.obj().name(), reading->level );
         if( reading->req != 0 ) {
             add_msg( m_info, _( "Requires %1$s knowledge level %2$d to understand." ),
                      skill.obj().name(), reading->req );
         }
     }
     if( reading->intel != 0 ) {
         add_msg( m_info, _( "Requires intelligence of %d to easily read." ), reading->intel );
     }
     //It feels wrong to use a pointer to *this, but I can't find any other player pointers in this method.
     if( book_fun_for( book, *this ) != 0 ) {
         add_msg( m_info, _( "Reading this book affects your morale by %d." ), book_fun_for( book, *this ) );
     }
     if( book.type->use_methods.count( "MA_MANUAL" ) ) {
         const matype_id style_to_learn = martial_art_learned_from( *book.type );
         add_msg( m_info, _( "You can learn %s style from it." ), style_to_learn->name );
         add_msg( m_info, _( "This fighting style is %s to learn." ),
                  martialart_difficulty( style_to_learn ) );
         add_msg( m_info, _( "It would be easier to master if you'd have skill expertise in %s." ),
                  style_to_learn->primary_skill->name() );
         add_msg( m_info, _( "A training session with this book takes %s." ),
                  to_string_clipped( reading->time ) );
     } else {
         add_msg( m_info, _( "A chapter of this book takes %s to read." ),
                  to_string_clipped( reading->time ) );
     }
     std::vector<std::string> crafting_recipes;
     std::vector<std::string> practice_recipes;
     for( const islot_book::recipe_with_description_t &elem : reading->recipes ) {
         // If the player knows it, they recognize it even if it's not clearly stated.
         if( elem.is_hidden() && !knows_recipe( elem.recipe ) ) {
             continue;
         }
         if( elem.recipe->is_practice() ) {
             practice_recipes.emplace_back( elem.recipe->result_name() );
         } else {
             crafting_recipes.emplace_back( elem.name() );
         }
     }
     if( !crafting_recipes.empty() ) {
         add_msg( m_info, string_format( _( "This book can help you craft: %s" ),
                                         enumerate_as_string( crafting_recipes ) ) );
     }
     if( !practice_recipes.empty() ) {
         add_msg( m_info, string_format( _( "This book can help you practice: %s" ),
                                         enumerate_as_string( practice_recipes ) ) );
     }
     const std::size_t num_total_recipes = crafting_recipes.size() + practice_recipes.size();
     if( num_total_recipes < reading->recipes.size() ) {
         add_msg( m_info, _( "It might help you figuring out some more recipes." ) );
     }
 }
References _, add_msg(), itype::book, Character::book_fun_for(), cata_assert, debugmsg, enumerate_as_string(), Character::get_skill_level_object(), has_identified(), item::is_book(), islot_book::recipe_with_description_t::is_hidden(), recipe::is_practice(), item, items_identified, Character::knows_recipe(), m_info, martial_art_learned_from(), martialart_difficulty(), islot_book::recipe_with_description_t::name(), martialart::name, Skill::name(), string_id< T >::obj(), martialart::primary_skill, islot_book::recipe_with_description_t::recipe, recipe::result_name(), string_format(), to_string_clipped(), item::type, and item::typeId().
Referenced by read_activity_actor::player_read(), and read_activity_actor::player_readma().
initialize()
void avatar::initialize (character_type type)
Definition at line 936 of file newcharacter.cpp.
 {
     this->as_character()->initialize();
     for( const matype_id &ma : prof->ma_known() ) {
         if( !martial_arts_data->has_martialart( ma ) ) {
             martial_arts_data->add_martialart( ma );
         }
     }
     if( !prof->ma_choices().empty() ) {
         for( int i = 0; i < prof->ma_choice_amount; i++ ) {
             std::vector<matype_id> styles;
             for( const matype_id &ma : prof->ma_choices() ) {
                 if( !martial_arts_data->has_martialart( ma ) ) {
                     styles.push_back( ma );
                 }
             }
             if( !styles.empty() ) {
                 const matype_id ma_type = choose_ma_style( type, styles, *this );
                 martial_arts_data->add_martialart( ma_type );
             } else {
                 break;
             }
         }
     }
     for( const trait_id &t : get_base_traits() ) {
         std::vector<matype_id> styles;
         for( const matype_id &s : t->initial_ma_styles ) {
             if( !martial_arts_data->has_martialart( s ) ) {
                 styles.push_back( s );
             }
         }
         if( !styles.empty() ) {
             const matype_id ma_type = choose_ma_style( type, styles, *this );
             martial_arts_data->add_martialart( ma_type );
         }
     }
     // Select a random known style
     std::vector<matype_id> selectable_styles = martial_arts_data->get_known_styles( false );
     if( !selectable_styles.empty() ) {
         std::vector<matype_id>::iterator it_max_priority = std::max_element( selectable_styles.begin(),
         selectable_styles.end(), []( const matype_id & a, const matype_id & b ) {
             return a->priority < b->priority;
         } );
         int max_priority = ( *it_max_priority )->priority;
         selectable_styles.erase( std::remove_if( selectable_styles.begin(),
         selectable_styles.end(), [max_priority]( const matype_id & style ) {
             return style->priority != max_priority;
         } ), selectable_styles.end() );
     }
     martial_arts_data->set_style( random_entry( selectable_styles, style_none ) );
     for( const mtype_id &elem : prof->pets() ) {
         starting_pets.push_back( elem );
     }
     if( get_scenario()->vehicle() != vproto_id::NULL_ID() ) {
         starting_vehicle = get_scenario()->vehicle();
     } else {
         starting_vehicle = prof->vehicle();
     }
     prof->learn_spells( *this );
     // Also learn spells from hobbies
     for( const profession *profession : hobbies ) {
         profession->learn_spells( *this );
     }
 }
References a, Character::as_character(), b, choose_ma_style(), Character::get_base_traits(), get_scenario(), Character::hobbies, Character::initialize(), profession::learn_spells(), profession::ma_choice_amount, profession::ma_choices(), profession::ma_known(), Character::martial_arts_data, string_id< vehicle_prototype >::NULL_ID(), profession::pets(), Character::prof, random_entry(), starting_pets, starting_vehicle, style_none, type, vehicle, profession::vehicle(), and scenario::vehicle().
Referenced by create().
invoke_item() [1/8]
bool Character::invoke_item
As above two, but with position equal to current position.
Definition at line 1928 of file character.cpp.
 {
     return invoke_item( used, pos() );
 }
invoke_item() [2/8]
bool avatar::invoke_item (item * used) override virtual
As above two, but with position equal to current position.
Reimplemented from Character.
Definition at line 1532 of file avatar.cpp.
 {
     return Character::invoke_item( used );
 }
References Character::invoke_item().
invoke_item() [3/8]
bool Character::invoke_item
Definition at line 1929 of file character.cpp.
 {
     return invoke_item( used, method, pos() );
 }
invoke_item() [4/8]
bool avatar::invoke_item (item * used, const std::string & method) override virtual
Reimplemented from Character.
Definition at line 1546 of file avatar.cpp.
 {
     return Character::invoke_item( used, method );
 }
References Character::invoke_item().
invoke_item() [5/8]
bool Character::invoke_item
As above, but with a pre-selected method.
Debugmsg if this item doesn't have this method.
Definition at line 1925 of file character.cpp.
 {
     if( method.empty() ) {
         return invoke_item( used, pt, pre_obtain_moves );
     }
     if( used->is_broken() ) {
         add_msg_if_player( m_bad, _( "Your %s was broken and won't turn on." ), used->tname() );
         return false;
     }
     if( !used->ammo_sufficient( this, method ) ) {
         int ammo_req = used->ammo_required();
         std::string it_name = used->tname();
         if( used->has_flag( flag_USE_UPS ) ) {
             add_msg_if_player( m_info,
                                n_gettext( "Your %s needs %d charge from some UPS.",
                                           "Your %s needs %d charges from some UPS.",
                                           ammo_req ),
                                it_name, ammo_req );
         } else if( used->has_flag( flag_USES_BIONIC_POWER ) ) {
             add_msg_if_player( m_info,
                                n_gettext( "Your %s needs %d kJ of bionic power.",
                                           "Your %s needs %d kJ of bionic power.",
                                           ammo_req ),
                                it_name, ammo_req );
         } else {
             int ammo_rem = used->ammo_remaining();
             add_msg_if_player( m_info,
                                n_gettext( "Your %s has %d charge, but needs %d.",
                                           "Your %s has %d charges, but needs %d.",
                                           ammo_rem ),
                                it_name, ammo_rem, ammo_req );
         }
         set_moves( pre_obtain_moves );
         return false;
     }
     item *actually_used = used->get_usable_item( method );
     if( actually_used == nullptr ) {
         debugmsg( "Tried to invoke a method %s on item %s, which doesn't have this method",
                   method.c_str(), used->tname() );
         set_moves( pre_obtain_moves );
         return false;
     }
     std::optional<int> charges_used = actually_used->type->invoke( this, *actually_used,
                                       pt, method );
     if( !charges_used.has_value() ) {
         set_moves( pre_obtain_moves );
         return false;
     }
     if( charges_used.value() == 0 ) {
         // Not really used.
         // The item may also have been deleted
         return false;
     }
     if( actually_used->is_comestible() ) {
         const bool ret = consume_effects( *used );
         const int consumed = used->activation_consume( charges_used.value(), pt, this );
         if( consumed == 0 ) {
             // Nothing was consumed from within the item. "Eat" the item itself away.
             i_rem( actually_used );
         }
         return ret;
     }
     actually_used->activation_consume( charges_used.value(), pt, this );
     if( actually_used->has_flag( flag_SINGLE_USE ) || actually_used->is_bionic() ||
         actually_used->is_deployable() ) {
         i_rem( actually_used );
         return true;
     }
     return false;
 }
References Character::cached_dead_state.
invoke_item() [6/8]
bool avatar::invoke_item (item * used, const std::string & method, const tripoint & pt, int pre_obtain_moves = -1) override virtual
As above, but with a pre-selected method.
Debugmsg if this item doesn't have this method.
Reimplemented from Character.
Definition at line 1537 of file avatar.cpp.
 {
     if( pre_obtain_moves == -1 ) {
         pre_obtain_moves = get_moves();
     }
     return Character::invoke_item( used, method, pt, pre_obtain_moves );
 }
References Creature::get_moves(), and Character::invoke_item().
invoke_item() [7/8]
bool avatar::invoke_item (item * , const tripoint & pt, int pre_obtain_moves) override virtual
Asks how to use the item (if it has more than one use_method) and uses it.
Returns true if it destroys the item. Consumes charges from the item. Multi-use items are ONLY supported when all use_methods are iuse_actor!
Reimplemented from Character.
Definition at line 1482 of file avatar.cpp.
 {
     const std::map<std::string, use_function> &use_methods = used->type->use_methods;
     const int num_methods = use_methods.size();
     const bool has_relic = used->has_relic_activation();
     if( use_methods.empty() && !has_relic ) {
         return false;
     } else if( num_methods == 1 && !has_relic ) {
         return invoke_item( used, use_methods.begin()->first, pt, pre_obtain_moves );
     } else if( num_methods == 0 && has_relic ) {
         return used->use_relic( *this, pt );
     }
     uilist umenu;
     umenu.text = string_format( _( "What to do with your %s?" ), used->tname() );
     umenu.hilight_disabled = true;
     for( const auto &e : use_methods ) {
         const auto res = e.second.can_call( *this, *used, pt );
         umenu.addentry_desc( MENU_AUTOASSIGN, res.success(), MENU_AUTOASSIGN, e.second.get_name(),
                              res.str() );
     }
     if( has_relic ) {
         umenu.addentry_desc( MENU_AUTOASSIGN, true, MENU_AUTOASSIGN, _( "Use relic" ),
                              _( "Activate this relic." ) );
     }
     umenu.desc_enabled = std::any_of( umenu.entries.begin(),
     umenu.entries.end(), []( const uilist_entry & elem ) {
         return !elem.desc.empty();
     } );
     umenu.query();
     int choice = umenu.ret;
     // Use the relic
     if( choice == num_methods ) {
         return used->use_relic( *this, pt );
     }
     if( choice < 0 || choice >= num_methods ) {
         return false;
     }
     const std::string &method = std::next( use_methods.begin(), choice )->first;
     return invoke_item( used, method, pt, pre_obtain_moves );
 }
References _, uilist::addentry_desc(), uilist::desc_enabled, uilist::entries, item::has_relic_activation(), uilist::hilight_disabled, invoke_item(), MENU_AUTOASSIGN, uilist::query(), uilist::ret, string_format(), uilist::text, item::tname(), item::type, itype::use_methods, and item::use_relic().
Referenced by avatar_action::move(), game::npc_menu(), and game::wield().
invoke_item() [8/8]
bool Character::invoke_item
Asks how to use the item (if it has more than one use_method) and uses it.
Returns true if it destroys the item. Consumes charges from the item. Multi-use items are ONLY supported when all use_methods are iuse_actor!
Definition at line 1923 of file character.cpp.
 {
     return false;
 }
Referenced by invoke_item().
is_ally()
bool avatar::is_ally (const Character & p) const override virtual
Implements Character.
Definition at line 1215 of file avatar.cpp.
 {
     if( p.getID() == getID() ) {
         return true;
     }
     const npc &guy = dynamic_cast<const npc &>( p );
     return guy.is_ally( *this );
 }
References Character::getID(), and npc::is_ally().
is_avatar()
bool avatar::is_avatar () const inline override virtual
Reimplemented from Creature.
Definition at line 114 of file avatar.h.
{
             return true;
         }
is_map_memory_valid()
bool avatar::is_map_memory_valid () const
Definition at line 253 of file avatar.cpp.
 {
     return player_map_memory->is_valid();
 }
References player_map_memory.
Referenced by vehicle::autodrive_controller::check_drivable().
is_obeying()
bool avatar::is_obeying (const Character & p) const override virtual
Implements Character.
Definition at line 1224 of file avatar.cpp.
 {
     if( p.getID() == getID() ) {
         return true;
     }
     const npc &guy = dynamic_cast<const npc &>( p );
     return guy.is_obeying( *this );
 }
References Character::getID(), and npc::is_obeying().
load()
void avatar::load (const JsonObject & data)
Definition at line 1615 of file savegame_json.cpp.
 {
     Character::load( data );
     // TEMPORARY until 0.G
     if( !data.has_member( "location" ) ) {
         set_location( get_map().getglobal( read_legacy_creature_pos( data ) ) );
     }
     // TEMPORARY until 0.G
     if( !data.has_member( "kill_xp" ) ) {
         kill_xp = g->get_kill_tracker().legacy_kill_xp();
     }
     // Remove after 0.F
     // Exists to prevent failed to visit member errors
     if( data.has_member( "reactor_plut" ) ) {
         data.get_int( "reactor_plut" );
     }
     if( data.has_member( "tank_plut" ) ) {
         data.get_int( "tank_plut" );
     }
     std::string prof_ident = "(null)";
     if( data.read( "profession", prof_ident ) && string_id<profession>( prof_ident ).is_valid() ) {
         prof = &string_id<profession>( prof_ident ).obj();
     } else {
         //We are likely an older profession which has since been removed so just set to default.  This is only cosmetic after game start.
         prof = profession::generic();
     }
     std::vector<string_id<profession>> hobby_ids;
     data.read( "hobbies", hobby_ids );
     for( const profession_id &hobby : hobby_ids ) {
         hobbies.insert( hobbies.end(), &hobby.obj() );
     }
     data.read( "followers", follower_ids );
     if( data.has_member( "shadow_npc" ) ) {
         shadow_npc = std::make_unique<npc>();
         data.read( "shadow_npc", *shadow_npc );
     }
     data.read( "controlling_vehicle", controlling_vehicle );
     data.read( "grab_point", grab_point );
     std::string grab_typestr = "OBJECT_NONE";
     if( grab_point.x != 0 || grab_point.y != 0 ) {
         grab_typestr = "OBJECT_VEHICLE";
         data.read( "grab_type", grab_typestr );
     } else {
         // we just want to read, but ignore grab_type
         std::string fake;
         data.read( "grab_type", fake );
     }
     // On Visual Studio array iterators are not pointers, so prevent clang-tidy
     // from converting this to a pointer type.
     // NOLINTNEXTLINE(readability-qualified-auto)
     const auto iter = std::find( obj_type_name.begin(), obj_type_name.end(), grab_typestr );
     grab( iter == obj_type_name.end() ?
           object_type::NONE : static_cast<object_type>(
               std::distance( obj_type_name.begin(), iter ) ),
           grab_point );
     data.read( "magic", magic );
     calc_mutation_levels();
     drench_mut_calc();
     std::string scen_ident = "(null)";
     if( data.read( "scenario", scen_ident ) && string_id<scenario>( scen_ident ).is_valid() ) {
         set_scenario( &string_id<scenario>( scen_ident ).obj() );
         if( !get_scenario()->allowed_start( start_location ) ) {
             start_location = get_scenario()->random_start_location();
         }
     } else {
         const scenario *generic_scenario = scenario::generic();
         debugmsg( "Tried to use non-existent scenario '%s'. Setting to generic '%s'.",
                   scen_ident.c_str(), generic_scenario->ident().c_str() );
         set_scenario( generic_scenario );
     }
     data.read( "learned_recipes", *learned_recipes );
     valid_autolearn_skills->clear(); // Invalidates the cache
     items_identified.clear();
     data.read( "items_identified", items_identified );
     data.read( "translocators", translocators );
     std::vector<int> tmpmissions;
     if( data.read( "active_missions", tmpmissions ) ) {
         active_missions = mission::to_ptr_vector( tmpmissions );
     }
     if( data.read( "failed_missions", tmpmissions ) ) {
         failed_missions = mission::to_ptr_vector( tmpmissions );
     }
     if( data.read( "completed_missions", tmpmissions ) ) {
         completed_missions = mission::to_ptr_vector( tmpmissions );
     }
     int tmpactive_mission = 0;
     if( data.read( "active_mission", tmpactive_mission ) ) {
         if( tmpactive_mission != -1 ) {
             active_mission = mission::find( tmpactive_mission );
         }
     }
     // Normally there is only one player character loaded, so if a mission that is assigned to
     // another character (not the current one) fails, the other character(s) are not informed.
     // We must inform them when they get loaded the next time.
     // Only active missions need checking, failed/complete will not change anymore.
     const auto last = std::remove_if( active_missions.begin(),
     active_missions.end(), []( mission const * m ) {
         return m->has_failed();
     } );
     std::copy( last, active_missions.end(), std::back_inserter( failed_missions ) );
     active_missions.erase( last, active_missions.end() );
     if( active_mission && active_mission->has_failed() ) {
         if( active_missions.empty() ) {
             active_mission = nullptr;
         } else {
             active_mission = active_missions.front();
         }
     }
     data.read( "show_map_memory", show_map_memory );
     for( JsonArray pair : data.get_array( "assigned_invlet" ) ) {
         inv->assigned_invlet[static_cast<char>( pair.get_int( 0 ) )] =
             itype_id( pair.get_string( 1 ) );
     }
     if( data.has_member( "invcache" ) ) {
         inv->json_load_invcache( data.get_member( "invcache" ) );
     }
     data.read( "calorie_diary", calorie_diary );
     data.read( "preferred_aiming_mode", preferred_aiming_mode );
     if( data.has_member( "power_prev_turn" ) ) {
         data.read( "power_prev_turn", power_prev_turn );
     }
     data.read( "snippets_read", snippets_read );
 }
References string_id< T >::c_str(), item_pocket::data, debugmsg, mission::find(), g, profession::generic(), scenario::generic(), get_map(), get_scenario(), grab(), scenario::ident(), string_id< T >::is_valid(), itype_id, last, Character::load(), NONE, string_id< T >::obj(), obj_type_name, scenario::random_start_location(), read_legacy_creature_pos(), calendar::set_location(), set_scenario(), and mission::to_ptr_vector().
load_map_memory()
void avatar::load_map_memory ()
Definition at line 271 of file avatar.cpp.
 {
     player_map_memory->load( get_map().getglobal( pos() ) );
 }
References get_map(), player_map_memory, and Creature::pos().
Referenced by game::load().
load_template()
bool avatar::load_template (const std::string & template_name, pool_type & pool)
Definition at line 4865 of file newcharacter.cpp.
 {
     return read_from_file_json( PATH_INFO::templatedir_path() / ( template_name + ".template" ), [&](
     const JsonValue & jv ) {
         // Legacy templates are an object. Current templates are an array of 0, 1, or 2 objects.
         JsonObject legacy_template;
         if( jv.test_array() ) {
             // not a legacy template
             JsonArray template_array = jv;
             if( template_array.empty() ) {
                 return;
             }
             JsonObject jobj = template_array.get_object( 0 );
             jobj.get_int( "stat_points", 0 );
             jobj.get_int( "trait_points", 0 );
             jobj.get_int( "skill_points", 0 );
             pool = static_cast<pool_type>( jobj.get_int( "limit" ) );
             random_start_location = jobj.get_bool( "random_start_location", true );
             const std::string jobj_start_location = jobj.get_string( "start_location", "" );
             // get_scenario()->allowed_start( loc.ident() ) is checked once scenario loads in avatar::load()
             for( const class start_location &loc : start_locations::get_all() ) {
                 if( loc.id.str() == jobj_start_location ) {
                     random_start_location = false;
                     this->start_location = loc.id;
                     break;
                 }
             }
             if( template_array.size() == 1 ) {
                 return;
             }
             legacy_template = template_array.get_object( 1 );
         }
         deserialize( legacy_template );
         // If stored_calories the template is under a million (kcals < 1000), assume it predates the
         // kilocalorie-to-literal-calorie conversion and is off by a factor of 1000.
         if( get_stored_kcal() < 1000 ) {
             set_stored_kcal( 1000 * get_stored_kcal() );
         }
         if( MAP_SHARING::isSharing() ) {
             // just to make sure we have the right name
             name = MAP_SHARING::getUsername();
         }
     } );
 }
References start_locations::get_all(), JsonObject::get_int(), JsonObject::get_object(), Character::random_start_location, read_from_file_json(), PATH_INFO::templatedir_path(), and JsonValue::test_array().
Referenced by create().
log_activity_level()
void avatar::log_activity_level (float level) override virtual
Reimplemented from Character.
Definition at line 1633 of file avatar.cpp.
 {
     calorie_diary.front().activity_levels[level]++;
 }
References calorie_diary.
longpull()
void avatar::longpull (const std::string & name)
Opens the targeting menu to pull a nearby creature towards the character.
Parameters
name Name of the implement used to pull the creature.
Definition at line 235 of file avatar.cpp.
 {
     item wtmp( itype_mut_longpull );
     g->temp_exit_fullscreen();
     target_handler::trajectory traj = target_handler::mode_throw( *this, wtmp, false );
     g->reenter_fullscreen();
     if( traj.empty() ) {
         return; // cancel
     }
     Creature::longpull( name, traj.back() );
 }
References g, itype_mut_longpull, Creature::longpull(), target_handler::mode_throw(), and Character::name.
Referenced by activity_handlers::pull_creature_finish().
memorize_clear_decoration()
void avatar::memorize_clear_decoration (const tripoint_abs_ms & p, std::string_view prefix = "")
Definition at line 306 of file avatar.cpp.
 {
     player_map_memory->clear_tile_decoration( p, prefix );
 }
References player_map_memory, and prefix.
Referenced by game::control_vehicle(), map::detach_vehicle(), map::furn_set(), grab(), map::memory_clear_vehicle_points(), map::partial_con_remove(), map::remove_trap(), DefaultRemovePartHandler::removed(), map::ter_set(), and map::trap_set().
memorize_decoration()
void avatar::memorize_decoration (const tripoint_abs_ms & p, std::string_view id, int subtile, int rotation)
Definition at line 295 of file avatar.cpp.
 {
     player_map_memory->set_tile_decoration( p, id, subtile, rotation );
 }
References player_map_memory.
memorize_symbol()
void avatar::memorize_symbol (const tripoint_abs_ms & p, char32_t symbol)
Definition at line 301 of file avatar.cpp.
 {
     player_map_memory->set_tile_symbol( p, symbol );
 }
References player_map_memory, and Character::symbol().
Referenced by map::draw_maptile().
memorize_terrain()
void avatar::memorize_terrain (const tripoint_abs_ms & p, std::string_view id, int subtile, int rotation)
Definition at line 289 of file avatar.cpp.
 {
     player_map_memory->set_tile_terrain( p, id, subtile, rotation );
 }
References player_map_memory.
on_mission_assignment()
void avatar::on_mission_assignment (mission & new_mission)
Called when a mission has been assigned to the player.
Definition at line 358 of file avatar.cpp.
 {
     active_missions.push_back( &new_mission );
     set_active_mission( new_mission );
 }
References active_missions, and set_active_mission().
on_mission_finished()
void avatar::on_mission_finished (mission & cur_mission)
Called when a mission has been completed or failed.
Either way it's finished. Check mission::has_failed to see which case it is.
Definition at line 364 of file avatar.cpp.
 {
     if( cur_mission.has_failed() ) {
         if( !cur_mission.get_type().invisible_on_complete ) {
             failed_missions.push_back( &cur_mission );
         }
         add_msg_if_player( m_bad, _( "Mission \"%s\" is failed." ), cur_mission.name() );
     } else {
         if( !cur_mission.get_type().invisible_on_complete ) {
             completed_missions.push_back( &cur_mission );
         }
         add_msg_if_player( m_good, _( "Mission \"%s\" is successfully completed." ),
                            cur_mission.name() );
     }
     const auto iter = std::find( active_missions.begin(), active_missions.end(), &cur_mission );
     if( iter == active_missions.end() ) {
         debugmsg( "completed mission %s was not in the active_missions list",
                   cur_mission.mission_id().c_str() );
     } else {
         active_missions.erase( iter );
     }
     if( &cur_mission == active_mission ) {
         if( active_missions.empty() ) {
             active_mission = nullptr;
         } else {
             active_mission = active_missions.front();
         }
     }
 }
References _, active_mission, active_missions, Character::add_msg_if_player(), string_id< T >::c_str(), completed_missions, debugmsg, failed_missions, mission::get_type(), mission::has_failed(), mission_type::invisible_on_complete, m_bad, m_good, mission::mission_id(), and mission::name().
Referenced by mission::fail(), and mission::wrap_up().
operator=() [1/2]
avatar & avatar::operator= (avatar &&) default
operator=() [2/2]
avatar& avatar::operator= (const avatar &) delete
power_bionics()
void avatar::power_bionics () override virtual
Generates and handles the UI for player interaction with installed bionics.
Total required height is: top frame line: + 1 height of title window: + TITLE_HEIGHT height of tabs: + TITLE_TAB_HEIGHT height of the biggest list of active/passive bionics: + bionic_count bottom frame line: + 1 TOTAL: TITLE_HEIGHT + TITLE_TAB_HEIGHT + bionic_count + 2
Reimplemented from Character.
Definition at line 574 of file bionics_ui.cpp.
 {
     sorted_bionics passive = filtered_bionics( *my_bionics, TAB_PASSIVE );
     sorted_bionics active = filtered_bionics( *my_bionics, TAB_ACTIVE );
     bionic *bio_last = nullptr;
     bionic_tab_mode tab_mode = TAB_ACTIVE;
     //added title_tab_height for the tabbed bionic display
     const int TITLE_HEIGHT = 4;
     const int TITLE_TAB_HEIGHT = 3;
     int HEIGHT = 0;
     int WIDTH = 0;
     int LIST_HEIGHT = 0;
     int list_start_y = 0;
     int half_list_view_location = 0;
     catacurses::window wBio;
     catacurses::window w_description;
     catacurses::window w_title;
     catacurses::window w_tabs;
     bool hide = false;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         if( hide ) {
             ui.position( point_zero, point_zero );
             return;
         }
         // Main window
         /** Total required height is:
          * top frame line:                                         + 1
          * height of title window:                                 + TITLE_HEIGHT
          * height of tabs:                                         + TITLE_TAB_HEIGHT
          * height of the biggest list of active/passive bionics:   + bionic_count
          * bottom frame line:                                      + 1
          * TOTAL: TITLE_HEIGHT + TITLE_TAB_HEIGHT + bionic_count + 2
          */
         HEIGHT = std::min( TERMY,
                            std::max( FULL_SCREEN_HEIGHT,
                                      TITLE_HEIGHT + TITLE_TAB_HEIGHT +
                                      static_cast<int>( my_bionics->size() ) + 2 ) );
         WIDTH = FULL_SCREEN_WIDTH + ( TERMX - FULL_SCREEN_WIDTH ) / 2;
         const point START( ( TERMX - WIDTH ) / 2, ( TERMY - HEIGHT ) / 2 );
         //wBio is the entire bionic window
         wBio = catacurses::newwin( HEIGHT, WIDTH, START );
         LIST_HEIGHT = HEIGHT - TITLE_HEIGHT - TITLE_TAB_HEIGHT - 2;
         const int DESCRIPTION_WIDTH = WIDTH - 2 - 40;
         const int DESCRIPTION_START_Y = START.y + TITLE_HEIGHT + TITLE_TAB_HEIGHT + 1;
         const int DESCRIPTION_START_X = START.x + 1 + 40;
         //w_description is the description panel that is controlled with ! key
         w_description = catacurses::newwin( LIST_HEIGHT, DESCRIPTION_WIDTH,
                                             point( DESCRIPTION_START_X, DESCRIPTION_START_Y ) );
         // Title window
         const int TITLE_START_Y = START.y + 1;
         const int HEADER_LINE_Y = TITLE_HEIGHT + TITLE_TAB_HEIGHT;
         w_title = catacurses::newwin( TITLE_HEIGHT, WIDTH - 2, START + point_east );
         const int TAB_START_Y = TITLE_START_Y + 3;
         //w_tabs is the tab bar for passive and active bionic groups
         w_tabs = catacurses::newwin( TITLE_TAB_HEIGHT, WIDTH,
                                      point( START.x, TAB_START_Y ) );
         // offset for display: bionic with index i is drawn at y=list_start_y+i
         // drawing the bionics starts with bionic[scroll_position]
         // scroll_position;
         list_start_y = HEADER_LINE_Y;
         half_list_view_location = LIST_HEIGHT / 2;
         ui.position_from_window( wBio );
     } );
     ui.mark_resize();
     int scroll_position = 0;
     int cursor = 0;
     //generate the tab title string and a count of the bionics owned
     bionic_menu_mode menu_mode = ACTIVATING;
     int max_scroll_position = 0;
     input_context ctxt( "BIONICS", keyboard_mode::keychar );
     ctxt.register_updown();
     ctxt.register_action( "ANY_INPUT" );
     ctxt.register_action( "TOGGLE_EXAMINE" );
     ctxt.register_action( "REASSIGN" );
     ctxt.register_action( "NEXT_TAB" );
     ctxt.register_action( "PREV_TAB" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "TOGGLE_SAFE_FUEL" );
     ctxt.register_action( "TOGGLE_SPRITE" );
     ctxt.register_action( "SORT" );
     ui.on_redraw( [&]( const ui_adaptor & ) {
         if( hide ) {
             return;
         }
         sorted_bionics *current_bionic_list = tab_mode == TAB_ACTIVE ? &active : &passive;
         werase( wBio );
         draw_border( wBio, BORDER_COLOR, _( " BIONICS " ) );
         mvwputch( wBio, point( getmaxx( wBio ) - 1, 2 ), BORDER_COLOR, LINE_XOXX ); // -|
         int max_width = 0;
         std::vector<std::string> bps;
         std::map<bodypart_str_id, size_t> bp_to_pos;
         for( const bodypart_id &bp : get_all_body_parts() ) {
             const int total = get_total_bionics_slots( bp );
             const std::string s = string_format( "%s: %d/%d",
                                                  body_part_name_as_heading( bp, 1 ),
                                                  total - get_free_bionics_slots( bp ), total );
             bps.push_back( s );
             bp_to_pos.emplace( bp.id(), bps.size() - 1 );
             max_width = std::max( max_width, utf8_width( s ) );
         }
         const int pos_x = WIDTH - 2 - max_width;
         if( get_option < bool >( "CBM_SLOTS_ENABLED" ) ) {
             for( size_t i = 0; i < bps.size(); ++i ) {
                 mvwprintz( wBio, point( pos_x, i + list_start_y ), c_light_gray, bps[i] );
             }
         }
         if( current_bionic_list->empty() ) {
             std::string msg;
             switch( tab_mode ) {
                 case TAB_ACTIVE:
                     msg = _( "No activatable bionics installed." );
                     break;
                 case TAB_PASSIVE:
                     msg = _( "No passive bionics installed." );
                     break;
             }
             fold_and_print( wBio, point( 2, list_start_y ), pos_x - 1, c_light_gray, msg );
         } else {
             for( size_t i = scroll_position; i < current_bionic_list->size(); i++ ) {
                 if( list_start_y + static_cast<int>( i ) - scroll_position == HEIGHT - 1 ) {
                     break;
                 }
                 const bool is_highlighted = cursor == static_cast<int>( i );
                 const nc_color col = get_bionic_text_color( *( *current_bionic_list )[i],
                                      is_highlighted );
                 const std::string desc = string_format( "%c %s", ( *current_bionic_list )[i]->invlet,
                                                         build_bionic_powerdesc_string(
                                                                 *( *current_bionic_list )[i], this ).c_str() );
                 trim_and_print( wBio, point( 2, list_start_y + i - scroll_position ), WIDTH - 3, col,
                                 desc );
                 if( is_highlighted && menu_mode != EXAMINING && get_option < bool >( "CBM_SLOTS_ENABLED" ) ) {
                     const bionic_id bio_id = ( *current_bionic_list )[i]->id;
                     draw_connectors( wBio, point( utf8_width( desc ) + 3, list_start_y + i - scroll_position ),
                                      pos_x - 2, bio_id, bp_to_pos );
                     // redraw highlighted (occupied) body parts
                     for( const std::pair<const string_id<body_part_type>, size_t> &elem : bio_id->occupied_bodyparts ) {
                         const int i = bp_to_pos[elem.first];
                         mvwprintz( wBio, point( pos_x, i + list_start_y ), c_yellow, bps[i] );
                     }
                 }
             }
         }
         draw_scrollbar( wBio, cursor, LIST_HEIGHT, current_bionic_list->size(), point( 0, list_start_y ) );
         wnoutrefresh( wBio );
         draw_bionics_tabs( w_tabs, active.size(), passive.size(), tab_mode );
         draw_bionics_titlebar( w_title, this, menu_mode );
         if( menu_mode == EXAMINING && !current_bionic_list->empty() ) {
             draw_description( w_description, *( *current_bionic_list )[cursor], get_all_body_parts().size(),
                               this );
         }
     } );
     for( ;; ) {
         ui_manager::redraw();
         //track which list we are looking at
         ::sorted_bionics *current_bionic_list = tab_mode == TAB_ACTIVE ? &active : &passive;
         max_scroll_position = std::max( 0, static_cast<int>( current_bionic_list->size() ) - LIST_HEIGHT );
         scroll_position = clamp( scroll_position, 0, max_scroll_position );
         cursor = clamp<int>( cursor, 0, current_bionic_list->size() );
 #if defined(__ANDROID__)
         ctxt.get_registered_manual_keys().clear();
         for( size_t i = 0; i < current_bionic_list->size(); i++ ) {
             ctxt.register_manual_key( ( *current_bionic_list )[i]->invlet,
                                       build_bionic_powerdesc_string( *( *current_bionic_list )[i], this ) );
         }
 #endif
         const std::string action = ctxt.handle_input();
         const int ch = ctxt.get_raw_input().get_first_input();
         bionic *tmp = nullptr;
         if( action == "DOWN" ) {
             if( static_cast<size_t>( cursor ) < current_bionic_list->size() - 1 ) {
                 cursor++;
             } else {
                 cursor = 0;
             }
             if( scroll_position < max_scroll_position &&
                 cursor - scroll_position > LIST_HEIGHT - half_list_view_location ) {
                 scroll_position++;
             }
             if( scroll_position > 0 && cursor - scroll_position < half_list_view_location ) {
                 scroll_position = std::max( cursor - half_list_view_location, 0 );
             }
         } else if( action == "UP" ) {
             if( cursor > 0 ) {
                 cursor--;
             } else {
                 cursor = current_bionic_list->size() - 1;
             }
             if( scroll_position > 0 && cursor - scroll_position < half_list_view_location ) {
                 scroll_position--;
             }
             if( scroll_position < max_scroll_position &&
                 cursor - scroll_position > LIST_HEIGHT - half_list_view_location ) {
                 scroll_position =
                     std::max( std::min<int>( current_bionic_list->size() - LIST_HEIGHT,
                                              cursor - half_list_view_location ), 0 );
             }
         } else if( menu_mode == REASSIGNING ) {
             menu_mode = ACTIVATING;
             if( action == "CONFIRM" && !current_bionic_list->empty() ) {
                 sorted_bionics &bio_list = tab_mode == TAB_ACTIVE ? active : passive;
                 tmp = bio_list[cursor];
             } else {
                 tmp = bionic_by_invlet( ch );
             }
             if( tmp == nullptr ) {
                 // Selected an non-existing bionic (or Escape, or ...)
                 continue;
             }
             const int newch = popup_getkey( _( "%s; enter new letter.  Space to clear.  Esc to cancel." ),
                                             tmp->id->name );
             if( newch == ch || newch == KEY_ESCAPE ) {
                 continue;
             }
             if( newch == ' ' ) {
                 tmp->invlet = ' ';
                 continue;
             }
             if( !bionic_chars.valid( newch ) ) {
                 popup( _( "Invalid bionic letter.  Only those characters are valid:\n\n%s" ),
                        bionic_chars.get_allowed_chars() );
                 continue;
             }
             bionic *otmp = bionic_by_invlet( newch );
             if( otmp != nullptr ) {
                 std::swap( tmp->invlet, otmp->invlet );
             } else {
                 tmp->invlet = newch;
             }
             // TODO: show a message like when reassigning a key to an item?
         } else if( action == "NEXT_TAB" ) {
             scroll_position = 0;
             cursor = 0;
             if( tab_mode == TAB_ACTIVE ) {
                 tab_mode = TAB_PASSIVE;
             } else {
                 tab_mode = TAB_ACTIVE;
             }
         } else if( action == "PREV_TAB" ) {
             scroll_position = 0;
             cursor = 0;
             if( tab_mode == TAB_PASSIVE ) {
                 tab_mode = TAB_ACTIVE;
             } else {
                 tab_mode = TAB_PASSIVE;
             }
         } else if( action == "REASSIGN" ) {
             menu_mode = REASSIGNING;
         } else if( action == "TOGGLE_EXAMINE" ) {
             // switches between activation and examination
             menu_mode = menu_mode == ACTIVATING ? EXAMINING : ACTIVATING;
         } else if( action == "TOGGLE_SAFE_FUEL" ) {
             sorted_bionics &bio_list = tab_mode == TAB_ACTIVE ? active : passive;
             if( !current_bionic_list->empty() ) {
                 tmp = bio_list[cursor];
                 if( !tmp->info().fuel_opts.empty() || tmp->info().is_remote_fueled ) {
                     tmp->toggle_safe_fuel_mod();
                     g->invalidate_main_ui_adaptor();
                 } else {
                     popup( _( "You can't toggle fuel saving mode on a non-fueled CBM." ) );
                 }
             }
         } else if( action == "TOGGLE_SPRITE" ) {
             sorted_bionics &bio_list = tab_mode == TAB_ACTIVE ? active : passive;
             if( !current_bionic_list->empty() ) {
                 tmp = bio_list[cursor];
                 tmp->show_sprite = !tmp->show_sprite;
             }
         } else if( action == "SORT" ) {
             uistate.bionic_sort_mode = pick_sort_mode();
             // FIXME: is there a better way to resort?
             active = filtered_bionics( *my_bionics, TAB_ACTIVE );
             passive = filtered_bionics( *my_bionics, TAB_PASSIVE );
         } else if( action == "CONFIRM" || action == "ANY_INPUT" ) {
             sorted_bionics &bio_list = tab_mode == TAB_ACTIVE ? active : passive;
             if( action == "CONFIRM" && !current_bionic_list->empty() ) {
                 tmp = bio_list[cursor];
             } else {
                 tmp = bionic_by_invlet( ch );
                 if( tmp && tmp != bio_last ) {
                     // new bionic selected, update cursor and scroll position
                     int temp_cursor = 0;
                     for( temp_cursor = 0; temp_cursor < static_cast<int>( bio_list.size() ); temp_cursor++ ) {
                         if( bio_list[temp_cursor] == tmp ) {
                             break;
                         }
                     }
                     // if bionic is not found in current list, ignore the attempt to view/activate
                     if( temp_cursor >= static_cast<int>( bio_list.size() ) ) {
                         continue;
                     }
                     //relocate cursor to the bionic that was found
                     cursor = temp_cursor;
                     scroll_position = 0;
                     while( scroll_position < max_scroll_position &&
                            cursor - scroll_position > LIST_HEIGHT - half_list_view_location ) {
                         scroll_position++;
                     }
                 }
             }
             if( !tmp ) {
                 // entered a key that is not mapped to any bionic
                 continue;
             }
             bio_last = tmp;
             const bionic_id &bio_id = tmp->id;
             const bionic_data &bio_data = bio_id.obj();
             if( menu_mode == ACTIVATING ) {
                 if( bio_data.activated ) {
                     int b = tmp - my_bionics->data();
                     bionic &bio = ( *my_bionics )[b];
                     hide = true;
                     ui.mark_resize();
                     if( tmp->powered ) {
                         deactivate_bionic( bio );
                         if( bio_data.deactivated_close_ui ) {
                             ui.reset();
                             break;
                         }
                     } else {
                         bool activate = true;
                         if( bio.can_install_weapon() ) {
                             const bool has_weapon = bio.has_weapon();
                             activate = false;
                             uilist activate_action_menu;
                             activate_action_menu.title = _( "Select action" );
                             activate_action_menu.addentry( 0, has_weapon, 'a', _( "Activate" ) );
                             activate_action_menu.addentry( 1, has_weapon, 'u', _( "Uninstall weapon" ) );
                             activate_action_menu.addentry( 2, !has_weapon, 'i', _( "Install weapon" ) );
                             activate_action_menu.query();
                             switch( activate_action_menu.ret ) {
                                 case 0:
                                     activate = true;
                                     break;
                                 case 1:
                                     // TODO: Move to function, create activity and add tool requirements
                                     if( std::optional<item> weapon = bio.uninstall_weapon() ) {
                                         i_add_or_drop( *weapon );
                                     }
                                     break;
                                 case 2: {
                                     // TODO: Move to activity, create activity, add tool requirements, improve UI
                                     uilist install_weapon_menu;
                                     install_weapon_menu.title = _( "Select weapon to install" );
                                     // TODO: Choose from items around, obtain items before installing
                                     std::vector<item *> valid_weapons = items_with( [&bio]( const item & it ) {
                                         return it.has_any_flag( bio.id->installable_weapon_flags );
                                     } );
                                     for( size_t i = 0; i < valid_weapons.size(); i++ ) {
                                         install_weapon_menu.addentry( i, true, MENU_AUTOASSIGN, valid_weapons[i]->tname() );
                                     }
                                     if( install_weapon_menu.entries.empty() ) {
                                         popup( _( "You don't have any items you can install in this bionic" ) );
                                     } else {
                                         install_weapon_menu.query();
                                         if( install_weapon_menu.ret >= 0 &&
                                             static_cast<size_t>( install_weapon_menu.ret ) < valid_weapons.size() ) {
                                             item &new_weapon = *valid_weapons[install_weapon_menu.ret];
                                             if( bio.can_install_weapon( new_weapon ) && bio.install_weapon( new_weapon ) ) {
                                                 item_location loc( *this, &new_weapon );
                                                 loc.remove_item();
                                             } else {
                                                 popup( _( "Unable to install %s" ), new_weapon.tname() );
                                             }
                                         }
                                     }
                                     break;
                                 }
                                 default:
                                     break;
                             }
                         }
                         if( activate ) {
                             bool close_ui = false;
                             if( bio_data.activated_close_ui ) {
                                 ui.reset();
                                 activate_bionic( bio, false, &close_ui );
                                 break;
                             } else {
                                 activate_bionic( bio, false, &close_ui );
                                 // Exit this ui if we are firing a complex bionic
                                 if( close_ui && tmp->get_weapon().shots_remaining( this ) > 0 ) {
                                     break;
                                 }
                             }
                         }
                     }
                     hide = false;
                     ui.mark_resize();
                     g->invalidate_main_ui_adaptor();
                     if( moves < 0 ) {
                         return;
                     }
                     continue;
                 } else {
                     popup( _( "You can not activate %s!\n"
                               "To read a description of %s, press '%s', then '%c'." ), bio_data.name,
                            bio_data.name, ctxt.get_desc( "TOGGLE_EXAMINE" ), tmp->invlet );
                 }
             } else if( menu_mode == EXAMINING ) {
                 // Describing bionics, allow user to jump to description key
                 if( action != "CONFIRM" ) {
                     for( size_t i = 0; i < active.size(); i++ ) {
                         if( active[i] == tmp ) {
                             tab_mode = TAB_ACTIVE;
                             cursor = static_cast<int>( i );
                             int max_scroll_check = std::max( 0, static_cast<int>( active.size() ) - LIST_HEIGHT );
                             if( static_cast<int>( i ) > max_scroll_check ) {
                                 scroll_position = max_scroll_check;
                             } else {
                                 scroll_position = i;
                             }
                             break;
                         }
                     }
                     for( size_t i = 0; i < passive.size(); i++ ) {
                         if( passive[i] == tmp ) {
                             tab_mode = TAB_PASSIVE;
                             cursor = static_cast<int>( i );
                             int max_scroll_check = std::max( 0, static_cast<int>( passive.size() ) - LIST_HEIGHT );
                             if( static_cast<int>( i ) > max_scroll_check ) {
                                 scroll_position = max_scroll_check;
                             } else {
                                 scroll_position = i;
                             }
                             break;
                         }
                     }
                 }
             }
         } else if( action == "QUIT" ) {
             break;
         }
     }
 }
References _, action, Character::activate_bionic(), bionic_data::activated, bionic_data::activated_close_ui, anonymous_namespace{bionics_ui.cpp}::ACTIVATING, active, uilist::addentry(), b, bionic_by_invlet(), bionic_chars, uistatedata::bionic_sort_mode, body_part_name_as_heading(), BORDER_COLOR, bp, build_bionic_powerdesc_string(), c_light_gray, c_yellow, bionic::can_install_weapon(), clamp(), Character::deactivate_bionic(), bionic_data::deactivated_close_ui, draw_bionics_tabs(), draw_bionics_titlebar(), draw_border(), draw_connectors(), draw_description(), draw_scrollbar(), uilist::entries, anonymous_namespace{bionics_ui.cpp}::EXAMINING, anonymous_namespace{bionics_ui.cpp}::filtered_bionics(), fold_and_print(), bionic_data::fuel_opts, FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, g, Creature::get_all_body_parts(), invlet_wrapper::get_allowed_chars(), get_bionic_text_color(), input_context::get_desc(), input_event::get_first_input(), Character::get_free_bionics_slots(), input_context::get_raw_input(), Character::get_total_bionics_slots(), bionic::get_weapon(), catacurses::getmaxx(), input_context::handle_input(), item::has_any_flag(), bionic::has_weapon(), Character::has_weapon(), char_creation::HEIGHT, Character::i_add_or_drop(), bionic_data::id, bionic::id, int_id< T >::id(), bionic::info(), bionic::install_weapon(), bionic_data::installable_weapon_flags, bionic::invlet, bionic_data::is_remote_fueled, visitable::items_with(), KEY_ESCAPE, keychar, LINE_XOXX, max(), MENU_AUTOASSIGN, min(), Creature::moves, mvwprintz(), mvwputch(), Character::my_bionics, bionic_data::name, catacurses::newwin(), string_id< T >::obj(), bionic_data::occupied_bodyparts, passive, anonymous_namespace{bionics_ui.cpp}::pick_sort_mode(), point, point_east, point_zero, popup(), popup_getkey(), bionic::powered, uilist::query(), anonymous_namespace{bionics_ui.cpp}::REASSIGNING, ui_manager::redraw(), input_context::register_action(), input_context::register_updown(), item_location::remove_item(), uilist::ret, item::shots_remaining(), bionic::show_sprite, om_direction::size, START, string_format(), cata::swap(), anonymous_namespace{bionics_ui.cpp}::TAB_ACTIVE, anonymous_namespace{bionics_ui.cpp}::TAB_PASSIVE, TERMX, TERMY, uilist::title, item::tname(), bionic::toggle_safe_fuel_mod(), trim_and_print(), uistate, bionic::uninstall_weapon(), utf8_width(), invlet_wrapper::valid(), Character::weapon, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by game::do_regular_action().
power_mutations()
void avatar::power_mutations () override virtual
Total required height is: top frame line: + 1 height of title window: + TITLE_HEIGHT line after the title: + 1 line with active/passive mutation captions: + 1 height of the biggest list of active/passive mutations: + mutations_count line before mutation description: + 1 height of description window: + DESCRIPTION_HEIGHT bottom frame line: + 1 TOTAL: TITLE_HEIGHT + mutations_count + DESCRIPTION_HEIGHT + 5
Reimplemented from Character.
Definition at line 97 of file mutation_ui.cpp.
 {
     std::vector<trait_id> passive;
     std::vector<trait_id> active;
     for( std::pair<const trait_id, trait_data> &mut : my_mutations ) {
         if( !mut.first->player_display ) {
             continue;
         }
         if( !mut.first->activated ) {
             passive.push_back( mut.first );
         } else {
             active.push_back( mut.first );
         }
         // New mutations are initialized with no key at all, so we have to do this here.
         if( mut.second.key == ' ' ) {
             for( const char &letter : mutation_chars ) {
                 if( trait_by_invlet( letter ).is_null() ) {
                     mut.second.key = letter;
                     break;
                 }
             }
         }
     }
     // maximal number of rows in both columns
     const int mutations_count = std::max( passive.size(), active.size() );
     const int TITLE_HEIGHT = 2;
     const int DESCRIPTION_HEIGHT = 5;
     // + lines with text in titlebar, local
     const int HEADER_LINE_Y = TITLE_HEIGHT + 1;
     const int list_start_y = HEADER_LINE_Y + 2;
     // Main window
     /** Total required height is:
     * top frame line:                                         + 1
     * height of title window:                                 + TITLE_HEIGHT
     * line after the title:                                   + 1
     * line with active/passive mutation captions:               + 1
     * height of the biggest list of active/passive mutations:   + mutations_count
     * line before mutation description:                         + 1
     * height of description window:                           + DESCRIPTION_HEIGHT
     * bottom frame line:                                      + 1
     * TOTAL: TITLE_HEIGHT + mutations_count + DESCRIPTION_HEIGHT + 5
     */
     int HEIGHT = 0;
     int WIDTH = 0;
     catacurses::window wBio;
     int DESCRIPTION_LINE_Y = 0;
     catacurses::window w_description;
     catacurses::window w_title;
     int second_column = 0;
     int scroll_position = 0;
     int examine_pos = 0;
     int cursor = 0;
     int max_scroll_position = 0;
     int list_height = 0;
     int half_list_view_location = 0;
     mutation_menu_mode menu_mode = mutation_menu_mode::activating;
     mutation_tab_mode tab_mode;
     if( !active.empty() ) {
         tab_mode = mutation_tab_mode::active;
     } else if( !passive.empty() ) {
         tab_mode = mutation_tab_mode::passive;
     } else {
         tab_mode = mutation_tab_mode::none;
     }
     const auto recalc_max_scroll_position = [&]() {
         list_height = ( menu_mode == mutation_menu_mode::examining ?
                         DESCRIPTION_LINE_Y : HEIGHT - 1 ) - list_start_y;
         max_scroll_position = mutations_count - list_height;
         half_list_view_location = list_height / 2;
         if( max_scroll_position < 0 ) {
             scroll_position = 0;
         } else if( scroll_position > max_scroll_position ) {
             scroll_position = max_scroll_position;
         }
     };
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         HEIGHT = std::min( TERMY, std::max( FULL_SCREEN_HEIGHT,
                                             TITLE_HEIGHT + mutations_count + DESCRIPTION_HEIGHT + 5 ) );
         WIDTH = FULL_SCREEN_WIDTH + ( TERMX - FULL_SCREEN_WIDTH ) / 2;
         const point START( ( TERMX - WIDTH ) / 2, ( TERMY - HEIGHT ) / 2 );
         wBio = catacurses::newwin( HEIGHT, WIDTH, START );
         // Description window @ the bottom of the bionic window
         const int DESCRIPTION_START_Y = START.y + HEIGHT - DESCRIPTION_HEIGHT - 1;
         DESCRIPTION_LINE_Y = DESCRIPTION_START_Y - START.y - 1;
         w_description = catacurses::newwin( DESCRIPTION_HEIGHT, WIDTH - 2,
                                             point( START.x + 1, DESCRIPTION_START_Y ) );
         // Title window
         const int TITLE_START_Y = START.y + 1;
         w_title = catacurses::newwin( TITLE_HEIGHT, WIDTH - 2,
                                       point( START.x + 1, TITLE_START_Y ) );
         recalc_max_scroll_position();
         examine_pos = 0;
         // X-coordinate of the list of active mutations
         second_column = 32 + ( TERMX - FULL_SCREEN_WIDTH ) / 4;
         ui.position_from_window( wBio );
     } );
     ui.mark_resize();
     input_context ctxt( "MUTATIONS", keyboard_mode::keychar );
     ctxt.register_updown();
     ctxt.register_action( "ANY_INPUT" );
     ctxt.register_action( "TOGGLE_EXAMINE" );
     ctxt.register_action( "TOGGLE_SPRITE" );
     ctxt.register_action( "REASSIGN" );
     ctxt.register_action( "NEXT_TAB" );
     ctxt.register_action( "PREV_TAB" );
     ctxt.register_action( "SCROLL_TRAIT_INFO_UP" );
     ctxt.register_action( "SCROLL_TRAIT_INFO_DOWN" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "QUIT" );
 #if defined(__ANDROID__)
     for( const auto &p : passive ) {
         ctxt.register_manual_key( my_mutations[p].key, p.obj().name() );
     }
     for( const auto &a : active ) {
         ctxt.register_manual_key( my_mutations[a].key, a.obj().name() );
     }
 #endif
     std::optional<trait_id> examine_id;
     ui.on_redraw( [&]( const ui_adaptor & ) {
         werase( wBio );
         draw_border( wBio, BORDER_COLOR, _( "Mutations" ) );
         // Draw line under title
         mvwhline( wBio, point( 1, HEADER_LINE_Y ), LINE_OXOX, WIDTH - 2 );
         // Draw symbols to connect additional lines to border
         mvwputch( wBio, point( 0, HEADER_LINE_Y ), BORDER_COLOR, LINE_XXXO ); // |-
         mvwputch( wBio, point( WIDTH - 1, HEADER_LINE_Y ), BORDER_COLOR, LINE_XOXX ); // -|
         // Captions
         mvwprintz( wBio, point( 2, HEADER_LINE_Y + 1 ), c_light_blue, _( "Passive:" ) );
         mvwprintz( wBio, point( second_column, HEADER_LINE_Y + 1 ), c_light_blue, _( "Active:" ) );
         if( menu_mode == mutation_menu_mode::examining ) {
             draw_exam_window( wBio, DESCRIPTION_LINE_Y );
         }
         nc_color type;
         if( passive.empty() ) {
             mvwprintz( wBio, point( 2, list_start_y ), c_light_gray, _( "None" ) );
         } else {
             for( int i = scroll_position; static_cast<size_t>( i ) < passive.size(); i++ ) {
                 const mutation_branch &md = passive[i].obj();
                 const trait_data &td = my_mutations[passive[i]];
                 const bool is_highlighted = cursor == static_cast<int>( i );
                 if( i - scroll_position == list_height ) {
                     break;
                 }
                 if( is_highlighted && tab_mode == mutation_tab_mode::passive ) {
                     type = has_base_trait( passive[i] ) ? c_cyan_yellow : c_light_cyan_yellow;
                 } else {
                     type = has_base_trait( passive[i] ) ? c_cyan : c_light_cyan;
                 }
                 mvwprintz( wBio, point( 2, list_start_y + i - scroll_position ),
                            type, "%c %s", td.key, mutation_name( md.id ) );
                 if( !td.show_sprite ) {
                     //~ Hint: Letter to show which mutation is Hidden in the mutation menu
                     wprintz( wBio, c_cyan, _( " H" ) );
                 }
             }
         }
         if( active.empty() ) {
             mvwprintz( wBio, point( second_column, list_start_y ), c_light_gray, _( "None" ) );
         } else {
             for( int i = scroll_position; static_cast<size_t>( i ) < active.size(); i++ ) {
                 const mutation_branch &md = active[i].obj();
                 const trait_data &td = my_mutations[active[i]];
                 const bool is_highlighted = cursor == static_cast<int>( i );
                 if( i - scroll_position == list_height ) {
                     break;
                 }
                 if( td.powered ) {
                     if( is_highlighted && tab_mode == mutation_tab_mode::active ) {
                         type = has_base_trait( active[i] ) ? c_green_yellow : c_light_green_yellow;
                     } else {
                         type = has_base_trait( active[i] ) ? c_green : c_light_green;
                     }
                 } else {
                     if( is_highlighted && tab_mode == mutation_tab_mode::active ) {
                         type = has_base_trait( active[i] ) ? c_red_yellow : c_light_red_yellow;
                     } else {
                         type = has_base_trait( active[i] ) ? c_red : c_light_red;
                     }
                 }
                 // TODO: track resource(s) used and specify
                 mvwputch( wBio, point( second_column, list_start_y + i - scroll_position ),
                           type, td.key );
                 std::string mut_desc;
                 std::string resource_unit;
                 int number_of_resource = 0;
                 if( md.hunger ) {
                     resource_unit += _( " kcal" );
                     number_of_resource++;
                 }
                 if( md.thirst ) {
                     if( number_of_resource > 0 ) {
                         //~ Resources consumed by a mutation: "kcal & thirst & sleepiness"
                         resource_unit += _( " &" );
                     }
                     resource_unit += _( " thirst" );
                     number_of_resource++;
                 }
                 if( md.sleepiness ) {
                     if( number_of_resource > 0 ) {
                         //~ Resources consumed by a mutation: "kcal & thirst & sleepiness"
                         resource_unit += _( " &" );
                     }
                     resource_unit += _( " sleepiness" );
                 }
                 mut_desc += mutation_name( md.id );
                 if( md.cost > 0 && md.cooldown > 0_turns ) {
                     mut_desc += string_format( _( " - %d%s / %s" ),
                                                md.cost, resource_unit, to_string_clipped( md.cooldown ) );
                 } else if( md.cost > 0 ) {
                     mut_desc += string_format( _( " - %d%s" ), md.cost, resource_unit );
                 } else if( md.cooldown > 0_turns ) {
                     mut_desc += string_format( _( " - %s" ), to_string_clipped( md.cooldown ) );
                 }
                 if( td.powered ) {
                     mut_desc += _( " - Active" );
                 }
                 mvwprintz( wBio, point( second_column + 2, list_start_y + i - scroll_position ),
                            type, mut_desc );
             }
         }
         draw_scrollbar( wBio, scroll_position, list_height, mutations_count,
                         point( 0, list_start_y ), c_white, true );
         if( menu_mode == mutation_menu_mode::examining && examine_id.has_value() ) {
             werase( w_description );
             std::vector<std::string> desc = foldstring( mutation_desc( examine_id.value() ), WIDTH - 2 );
             const int winh = catacurses::getmaxy( w_description );
             const bool do_scroll = desc.size() > static_cast<unsigned>( std::abs( winh ) );
             const int fline = do_scroll ? examine_pos % ( desc.size() + 1 - winh ) : 0;
             const int lline = do_scroll ? fline + winh : desc.size();
             for( int i = fline; i < lline; i++ ) {
                 trim_and_print( w_description, point( 0, i - fline ), WIDTH - 2, c_light_blue, desc[i] );
             }
             draw_scrollbar( wBio, fline, winh, desc.size(), point( 0, catacurses::getmaxy( wBio ) - winh - 1 ),
                             c_white, true );
         }
         wnoutrefresh( wBio );
         show_mutations_titlebar( w_title, menu_mode, ctxt );
         if( menu_mode == mutation_menu_mode::examining && examine_id.has_value() ) {
             wnoutrefresh( w_description );
         }
     } );
     bool exit = false;
     while( !exit ) {
         recalc_max_scroll_position();
         ui_manager::redraw();
         bool handled = false;
         const std::string action = ctxt.handle_input();
         const input_event evt = ctxt.get_raw_input();
         if( evt.type == input_event_t::keyboard_char && !evt.sequence.empty() ) {
             const int ch = evt.get_first_input();
             if( ch == ' ' ) { //skip if space is pressed (space is used as an empty hotkey)
                 continue;
             }
             const trait_id mut_id = trait_by_invlet( ch );
             if( !mut_id.is_null() ) {
                 const mutation_branch &mut_data = mut_id.obj();
                 switch( menu_mode ) {
                     case mutation_menu_mode::reassigning: {
                         query_popup pop;
                         pop.message( _( "%s; enter new letter." ), mutation_name( mut_id ) )
                         .preferred_keyboard_mode( keyboard_mode::keychar )
                         .context( "POPUP_WAIT" )
                         .allow_cancel( true )
                         .allow_anykey( true );
                         bool pop_exit = false;
                         while( !pop_exit ) {
                             const query_popup::result ret = pop.query();
                             bool pop_handled = false;
                             if( ret.evt.type == input_event_t::keyboard_char && !ret.evt.sequence.empty() ) {
                                 const int newch = ret.evt.get_first_input();
                                 if( mutation_chars.valid( newch ) ) {
                                     const trait_id other_mut_id = trait_by_invlet( newch );
                                     if( !other_mut_id.is_null() ) {
                                         std::swap( my_mutations[mut_id].key, my_mutations[other_mut_id].key );
                                     } else {
                                         my_mutations[mut_id].key = newch;
                                     }
                                     pop_exit = true;
                                     pop_handled = true;
                                 }
                             }
                             if( !pop_handled ) {
                                 if( ret.action == "QUIT" ) {
                                     pop_exit = true;
                                 } else if( ret.action != "HELP_KEYBINDINGS" &&
                                            ret.evt.type == input_event_t::keyboard_char ) {
                                     popup( _( "Invalid mutation letter.  Only those characters are valid:\n\n%s" ),
                                            mutation_chars.get_allowed_chars() );
                                 }
                             }
                         }
                         menu_mode = mutation_menu_mode::activating;
                         examine_id = std::nullopt;
                         // TODO: show a message like when reassigning a key to an item?
                         break;
                     }
                     case mutation_menu_mode::activating: {
                         if( mut_data.activated ) {
                             if( my_mutations[mut_id].powered ) {
                                 add_msg_if_player( m_neutral, _( "You stop using your %s." ), mutation_name( mut_data.id ) );
                                 // Reset menu in advance
                                 ui.reset();
                                 deactivate_mutation( mut_id );
                                 // Action done, leave screen
                                 exit = true;
                             } else if( ( !mut_data.hunger || get_kcal_percent() >= 0.8f ) &&
                                        ( !mut_data.thirst || get_thirst() <= 400 ) &&
                                        ( !mut_data.sleepiness || get_sleepiness() <= 400 ) ) {
                                 add_msg_if_player( m_neutral, _( "You activate your %s." ), mutation_name( mut_data.id ) );
                                 // Reset menu in advance
                                 ui.reset();
                                 activate_mutation( mut_id );
                                 // Action done, leave screen
                                 exit = true;
                             } else {
                                 popup( _( "You don't have enough in you to activate your %s!" ), mutation_name( mut_data.id ) );
                             }
                         } else {
                             popup( _( "You cannot activate %1$s!  To read a description of "
                                       "%1$s, press '!', then '%2$c'." ),
                                    mutation_name( mut_data.id ), my_mutations[mut_id].key );
                         }
                         break;
                     }
                     case mutation_menu_mode::examining:
                         // Describing mutations, not activating them!
                         examine_id = mut_id;
                         break;
                     case mutation_menu_mode::hiding:
                         my_mutations[mut_id].show_sprite = !my_mutations[mut_id].show_sprite;
                         break;
                 }
                 handled = true;
             } else if( mutation_chars.valid( ch ) ) {
                 handled = true;
             }
         }
         if( !handled ) {
             // Essentially, up-down navigation adapted from the bionics_ui.cpp, with a bunch of extra workarounds to keep functionality
             if( action == "DOWN" ) {
                 int lowerlim;
                 if( tab_mode == mutation_tab_mode::passive ) {
                     lowerlim = static_cast<int>( passive.size() ) - 1;
                 } else if( tab_mode == mutation_tab_mode::active ) {
                     lowerlim = static_cast<int>( active.size() ) - 1;
                 } else {
                     continue;
                 }
                 if( cursor < lowerlim ) {
                     cursor++;
                 } else {
                     cursor = 0;
                 }
                 if( scroll_position < max_scroll_position &&
                     cursor - scroll_position > list_height - half_list_view_location ) {
                     scroll_position++;
                 }
                 if( scroll_position > 0 && cursor - scroll_position < half_list_view_location ) {
                     scroll_position = std::max( cursor - half_list_view_location, 0 );
                 }
                 examine_pos = 0;
                 // Draw the description, shabby workaround
                 examine_id = GetTrait( active, passive, cursor, tab_mode );
             } else if( action == "UP" ) {
                 int lim;
                 if( tab_mode == mutation_tab_mode::passive ) {
                     lim = passive.size() - 1;
                 } else if( tab_mode == mutation_tab_mode::active ) {
                     lim = active.size() - 1;
                 } else {
                     continue;
                 }
                 if( cursor > 0 ) {
                     cursor--;
                 } else {
                     cursor = lim;
                 }
                 if( scroll_position > 0 && cursor - scroll_position < half_list_view_location ) {
                     scroll_position--;
                 }
                 if( scroll_position < max_scroll_position &&
                     cursor - scroll_position > list_height - half_list_view_location ) {
                     scroll_position =
                         std::max( std::min<int>( lim + 1 - list_height,
                                                  cursor - half_list_view_location ), 0 );
                 }
                 examine_pos = 0;
                 examine_id = GetTrait( active, passive, cursor, tab_mode );
             } else if( ( action == "SCROLL_TRAIT_INFO_UP" || action == "SCROLL_TRAIT_INFO_DOWN" ) &&
                        menu_mode == mutation_menu_mode::examining ) {
                 examine_pos += action == "SCROLL_TRAIT_INFO_UP" ? -1 : 1;
             } else if( action == "NEXT_TAB" || action == "PREV_TAB" ) {
                 if( tab_mode == mutation_tab_mode::active && !passive.empty() ) {
                     tab_mode = mutation_tab_mode::passive;
                 } else if( tab_mode == mutation_tab_mode::passive && !active.empty() ) {
                     tab_mode = mutation_tab_mode::active;
                 } else {
                     continue;
                 }
                 scroll_position = 0;
                 examine_pos = 0;
                 cursor = 0;
                 examine_id = GetTrait( active, passive, cursor, tab_mode );
             } else if( action == "CONFIRM" ) {
                 trait_id mut_id;
                 if( tab_mode == mutation_tab_mode::active ) {
                     mut_id = active[cursor];
                 } else if( tab_mode == mutation_tab_mode::passive ) {
                     mut_id = passive[cursor];
                 } else {
                     continue;
                 }
                 if( !mut_id.is_null() ) {
                     const mutation_branch &mut_data = mut_id.obj();
                     switch( menu_mode ) {
                         case mutation_menu_mode::reassigning: {
                             query_popup pop;
                             pop.message( _( "%s; enter new letter." ), mutation_name( mut_id ) )
                             .preferred_keyboard_mode( keyboard_mode::keychar )
                             .context( "POPUP_WAIT" )
                             .allow_cancel( true )
                             .allow_anykey( true );
                             bool pop_exit = false;
                             while( !pop_exit ) {
                                 const query_popup::result ret = pop.query();
                                 bool pop_handled = false;
                                 if( ret.evt.type == input_event_t::keyboard_char && !ret.evt.sequence.empty() ) {
                                     const int newch = ret.evt.get_first_input();
                                     if( mutation_chars.valid( newch ) ) {
                                         const trait_id other_mut_id = trait_by_invlet( newch );
                                         if( !other_mut_id.is_null() ) {
                                             std::swap( my_mutations[mut_id].key, my_mutations[other_mut_id].key );
                                         } else {
                                             my_mutations[mut_id].key = newch;
                                         }
                                         pop_exit = true;
                                         pop_handled = true;
                                     } else if( newch == ' ' ) {
                                         my_mutations[mut_id].key = newch;
                                         pop_exit = true;
                                         pop_handled = true;
                                     }
                                 }
                                 if( !pop_handled ) {
                                     if( ret.action == "QUIT" ) {
                                         pop_exit = true;
                                     } else if( ret.action != "HELP_KEYBINDINGS" &&
                                                ret.evt.type == input_event_t::keyboard_char ) {
                                         popup( _( "Invalid mutation letter.  Only those characters are valid:\n\n%s" ),
                                                mutation_chars.get_allowed_chars() );
                                     }
                                 }
                             }
                             menu_mode = mutation_menu_mode::activating;
                             examine_id = std::nullopt;
                             // TODO: show a message like when reassigning a key to an item?
                             break;
                         }
                         case mutation_menu_mode::activating: {
                             if( mut_data.activated ) {
                                 if( my_mutations[mut_id].powered ) {
                                     add_msg_if_player( m_neutral, _( "You stop using your %s." ), mutation_name( mut_data.id ) );
                                     // Reset menu in advance
                                     ui.reset();
                                     deactivate_mutation( mut_id );
                                     // Action done, leave screen
                                     exit = true;
                                 } else if( ( !mut_data.hunger || get_kcal_percent() >= 0.8f ) &&
                                            ( !mut_data.thirst || get_thirst() <= 400 ) &&
                                            ( !mut_data.sleepiness || get_sleepiness() <= 400 ) ) {
                                     add_msg_if_player( m_neutral, _( "You activate your %s." ), mutation_name( mut_data.id ) );
                                     // Reset menu in advance
                                     ui.reset();
                                     activate_mutation( mut_id );
                                     // Action done, leave screen
                                     exit = true;
                                 } else {
                                     popup( _( "You don't have enough in you to activate your %s!" ), mutation_name( mut_data.id ) );
                                 }
                             } else {
                                 popup( _( "You cannot activate %1$s!  To read a description of "
                                           "%1$s, press '!', then '%2$c'." ),
                                        mutation_name( mut_data.id ), my_mutations[mut_id].key );
                             }
                             break;
                         }
                         case mutation_menu_mode::examining:
                             // Describing mutations, not activating them!
                             examine_id = mut_id;
                             break;
                         case mutation_menu_mode::hiding:
                             my_mutations[mut_id].show_sprite = !my_mutations[mut_id].show_sprite;
                             break;
                     }
                 }
             } else if( action == "REASSIGN" ) {
                 menu_mode = mutation_menu_mode::reassigning;
                 examine_id = std::nullopt;
             } else if( action == "TOGGLE_EXAMINE" ) {
                 // switches between activation and examination
                 menu_mode = menu_mode == mutation_menu_mode::activating ?
                             mutation_menu_mode::examining : mutation_menu_mode::activating;
                 if( menu_mode == mutation_menu_mode::examining ) {
                     examine_id = GetTrait( active, passive, cursor, tab_mode );
                 } else {
                     examine_id = std::nullopt;
                 }
                 examine_pos = 0;
             } else if( action == "TOGGLE_SPRITE" ) {
                 menu_mode = mutation_menu_mode::hiding;
                 examine_id = std::nullopt;
             } else if( action == "QUIT" ) {
                 exit = true;
             }
         }
     }
 }
References _, a, abs(), action, Character::activate_mutation(), mutation_branch::activated, activating, active, Character::add_msg_if_player(), query_popup::allow_anykey(), query_popup::allow_cancel(), BORDER_COLOR, c_cyan, c_cyan_yellow, c_green, c_green_yellow, c_light_blue, c_light_cyan, c_light_cyan_yellow, c_light_gray, c_light_green, c_light_green_yellow, c_light_red, c_light_red_yellow, c_red, c_red_yellow, c_white, query_popup::context(), mutation_branch::cooldown, mutation_branch::cost, Character::deactivate_mutation(), draw_border(), draw_exam_window(), draw_scrollbar(), examining, foldstring(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, invlet_wrapper::get_allowed_chars(), input_event::get_first_input(), Character::get_kcal_percent(), input_context::get_raw_input(), Character::get_sleepiness(), Character::get_thirst(), catacurses::getmaxy(), GetTrait(), input_context::handle_input(), Character::has_base_trait(), char_creation::HEIGHT, hiding, mutation_branch::hunger, mutation_branch::id, string_id< T >::is_null(), Character::trait_data::key, keyboard_char, keychar, LINE_OXOX, LINE_XOXX, LINE_XXXO, m_neutral, max(), query_popup::message(), min(), mutation_chars, Character::mutation_desc(), Character::mutation_name(), catacurses::mvwhline(), mvwprintz(), mvwputch(), Character::my_mutations, catacurses::newwin(), none, string_id< T >::obj(), passive, point, popup(), Character::trait_data::powered, query_popup::preferred_keyboard_mode(), query_popup::query(), reassigning, ui_manager::redraw(), input_context::register_action(), input_context::register_updown(), cata::hash64_detail::ret, input_event::sequence, show_mutations_titlebar(), Character::trait_data::show_sprite, mutation_branch::sleepiness, START, string_format(), cata::swap(), TERMX, TERMY, mutation_branch::thirst, to_string_clipped(), Character::trait_by_invlet(), trim_and_print(), type, input_event::type, invlet_wrapper::valid(), catacurses::werase(), catacurses::wnoutrefresh(), and wprintz().
Referenced by game::do_regular_action().
prepare_map_memory_region()
void avatar::prepare_map_memory_region (const tripoint_abs_ms & p1, const tripoint_abs_ms & p2)
Definition at line 276 of file avatar.cpp.
 {
     player_map_memory->prepare_region( p1, p2 );
 }
References player_map_memory.
Referenced by map::draw().
print_info()
int avatar::print_info (const catacurses::window & w, int vStart, int vLines, int column) const override virtual
Write information about this creature.
Parameters
w the window to print the text into.
vStart vertical start to print, that means the first line to print.
vLines number of lines to print at most (printing less is fine).
column horizontal start to print (column), horizontal end is one character before the right border of the window (to keep the border).
Returns
The line just behind the last printed line, that means multiple calls to this can be stacked, the return value is acceptable as vStart for the next call without creating empty lines or overwriting lines.
Implements Creature.
Definition at line 931 of file avatar.cpp.
 {
     return vStart + fold_and_print( w, point( column, vStart ), getmaxx( w ) - column - 1, c_dark_gray,
                                     _( "You (%s)" ),
                                     get_name() ) - 1;
 }
References _, c_dark_gray, fold_and_print(), Character::get_name(), catacurses::getmaxx(), and point.
query_yn() [1/3]
template<typename ... Args> bool Character::query_yn (typename ... Args) inline
It is supposed to hide the query_yn to simplify player vs.
npc code.
Definition at line 2544 of file character.h.
{
             return query_yn( string_format( msg, std::forward<Args>( args ) ... ) );
         }
query_yn() [2/3]
bool avatar::query_yn (const std::string & mes) const override virtual
Implements Character.
Definition at line 2049 of file avatar.cpp.
 {
     return ::query_yn( mes );
 }
References query_yn().
Referenced by best_installer().
query_yn() [3/3]
virtual bool Character::query_yn
Referenced by create(), and upgrade_stat_prompt().
randomize()
void avatar::randomize (bool random_scenario, bool play_now = false)
Definition at line 422 of file newcharacter.cpp.
 {
     const int max_trait_points = get_option<int>( "MAX_TRAIT_POINTS" );
     // Reset everything to the defaults to have a clean state.
     *this = avatar();
     bool gender_selection = one_in( 2 );
     male = gender_selection;
     outfit = gender_selection;
     if( !MAP_SHARING::isSharing() ) {
         play_now ? pick_name() : pick_name( true );
     } else {
         name = MAP_SHARING::getUsername();
     }
     randomize_height();
     randomize_blood();
     randomize_heartrate();
     bool cities_enabled = world_generator->active_world->WORLD_OPTIONS["CITY_SIZE"].getValue() != "0";
     if( random_scenario ) {
         std::vector<const scenario *> scenarios;
         for( const scenario &scen : scenario::get_all() ) {
             if( !scen.has_flag( flag_CHALLENGE ) && !scen.scen_is_blacklisted() &&
                 ( !scen.has_flag( flag_CITY_START ) || cities_enabled ) && scen.can_pick().success() ) {
                 scenarios.emplace_back( &scen );
             }
         }
         const scenario *selected_scenario = random_entry( scenarios );
         if( selected_scenario ) {
             set_scenario( selected_scenario );
         } else {
             debugmsg( "Failed randomizing sceario - no entries matching requirements." );
         }
     }
     prof = get_scenario()->weighted_random_profession();
     init_age = rng( this->prof->age_lower, this->prof->age_upper );
     starting_city = std::nullopt;
     world_origin = std::nullopt;
     random_start_location = true;
     str_max = rng( 6, HIGH_STAT - 2 );
     dex_max = rng( 6, HIGH_STAT - 2 );
     int_max = rng( 6, HIGH_STAT - 2 );
     per_max = rng( 6, HIGH_STAT - 2 );
     set_body();
     randomize_hobbies();
     int num_gtraits = 0;
     int num_btraits = 0;
     int tries = 0;
     add_traits(); // adds mandatory profession/scenario traits.
     for( const trait_id &mut : get_mutations() ) {
         const mutation_branch &mut_info = mut.obj();
         if( mut_info.profession ) {
             continue;
         }
         // Scenario/profession traits do not cost any points, but they are counted toward
         // the limit (MAX_TRAIT_POINTS)
         if( mut_info.points >= 0 ) {
             num_gtraits += mut_info.points;
         } else {
             num_btraits -= mut_info.points;
         }
     }
     /* The loops variable is used to prevent the algorithm running in an infinite loop */
     for( int loops = 0; loops <= 100000; loops++ ) {
         multi_pool p( *this );
         bool is_valid = p.stat_points_left >= 0 && p.trait_points_left >= 0 && p.skill_points_left >= 0;
         if( is_valid && rng( -3, 20 ) <= p.skill_points_left ) {
             break;
         }
         trait_id rn;
         if( num_btraits < max_trait_points && one_in( 3 ) ) {
             tries = 0;
             do {
                 rn = random_bad_trait();
                 tries++;
             } while( ( has_trait( rn ) || num_btraits - rn->points > max_trait_points ) &&
                      tries < 5 );
             if( tries < 5 && !has_conflicting_trait( rn ) ) {
                 toggle_trait_deps( rn );
                 num_btraits -= rn->points;
             }
         } else {
             switch( rng( 1, 4 ) ) {
                 case 1:
                     if( str_max > 5 ) {
                         str_max--;
                     }
                     break;
                 case 2:
                     if( dex_max > 5 ) {
                         dex_max--;
                     }
                     break;
                 case 3:
                     if( int_max > 5 ) {
                         int_max--;
                     }
                     break;
                 case 4:
                     if( per_max > 5 ) {
                         per_max--;
                     }
                     break;
             }
         }
     }
     for( int loops = 0;
          has_unspent_points( *this ) && loops <= 100000;
          loops++ ) {
         multi_pool p( *this );
         const bool allow_stats = p.stat_points_left > 0;
         const bool allow_traits = p.trait_points_left > 0 && num_gtraits < max_trait_points;
         int r = rng( 1, 9 );
         trait_id rn;
         switch( r ) {
             case 1:
             case 2:
             case 3:
             case 4:
                 if( allow_traits ) {
                     rn = random_good_trait();
                     const mutation_branch &mdata = rn.obj();
                     if( !has_trait( rn ) && p.trait_points_left >= mdata.points &&
                         num_gtraits + mdata.points <= max_trait_points && !has_conflicting_trait( rn ) ) {
                         toggle_trait_deps( rn );
                         num_gtraits += mdata.points;
                     }
                     break;
                 }
             /* fallthrough */
             case 5:
                 if( allow_stats ) {
                     switch( rng( 1, 4 ) ) {
                         case 1:
                             str_max++;
                             break;
                         case 2:
                             dex_max++;
                             break;
                         case 3:
                             int_max++;
                             break;
                         case 4:
                             per_max++;
                             break;
                     }
                     break;
                 }
             /* fallthrough */
             case 6:
             case 7:
             case 8:
             case 9:
                 const skill_id aSkill = Skill::random_skill();
                 const int level = get_skill_level( aSkill );
                 if( level < p.skill_points_left && level < MAX_SKILL && loops > 10000 ) {
                     // For balance reasons, increasing a skill from level 0 gives you 1 extra level for free
                     set_skill_level( aSkill, ( level == 0 ? 2 : level + 1 ) );
                 }
                 break;
         }
     }
     randomize_cosmetics();
     // Restart cardio accumulator
     reset_cardio_acc();
 }
References Character::add_traits(), profession::age_lower, avatar(), cities_enabled, debugmsg, Character::dex_max, flag_CHALLENGE(), flag_CITY_START(), scenario::get_all(), Character::get_mutations(), get_scenario(), Character::get_skill_level(), MAP_SHARING::getUsername(), Character::has_conflicting_trait(), Character::has_trait(), has_unspent_points(), HIGH_STAT, Character::init_age, Character::int_max, MAP_SHARING::isSharing(), Character::male, Character::name, string_id< T >::obj(), one_in(), Character::per_max, Character::pick_name(), mutation_branch::points, Character::prof, mutation_branch::profession, Character::random_bad_trait(), random_entry(), Character::random_good_trait(), Skill::random_skill(), Character::random_start_location, Character::randomize_blood(), randomize_cosmetics(), Character::randomize_heartrate(), Character::randomize_height(), randomize_hobbies(), Character::reset_cardio_acc(), rng(), Creature::set_body(), set_scenario(), Character::set_skill_level(), multi_pool::skill_points_left, Character::starting_city, multi_pool::stat_points_left, Character::str_max, Character::toggle_trait_deps(), multi_pool::trait_points_left, scenario::weighted_random_profession(), world_generator, and Character::world_origin.
Referenced by create(), and set_description().
randomize_cosmetics()
void avatar::randomize_cosmetics ()
Definition at line 597 of file newcharacter.cpp.
 {
     randomize_cosmetic_trait( type_hair_style );
     randomize_cosmetic_trait( type_skin_tone );
     randomize_cosmetic_trait( type_eye_color );
     //arbitrary 50% chance to add beard to male characters
     if( male && one_in( 2 ) ) {
         randomize_cosmetic_trait( type_facial_hair );
     } else {
         set_mutation( trait_FACIAL_HAIR_NONE );
     }
 }
References Character::male, one_in(), Character::randomize_cosmetic_trait(), Character::set_mutation(), trait_FACIAL_HAIR_NONE, type_eye_color(), type_facial_hair(), type_hair_style(), and type_skin_tone().
Referenced by create(), and randomize().
randomize_hobbies()
void avatar::randomize_hobbies ()
Definition at line 1804 of file avatar.cpp.
 {
     hobbies.clear();
     std::vector<profession_id> choices = get_scenario()->permitted_hobbies();
     choices.erase( std::remove_if( choices.begin(), choices.end(),
     [this]( const string_id<profession> &hobby ) {
         return !prof->allows_hobby( hobby );
     } ), choices.end() );
     if( choices.empty() ) {
         debugmsg( "Why would you blacklist all hobbies?" );
         choices = profession::get_all_hobbies();
     };
     int random = rng( 0, 5 );
     if( random >= 1 ) {
         add_random_hobby( choices );
     }
     if( random >= 3 ) {
         add_random_hobby( choices );
     }
     if( random >= 5 ) {
         add_random_hobby( choices );
     }
 }
References add_random_hobby(), debugmsg, profession::get_all_hobbies(), get_scenario(), Character::hobbies, scenario::permitted_hobbies(), om_direction::random(), and rng().
Referenced by randomize().
read()
bool avatar::read (item_location & book, item_location ereader = {})
Handles reading effects and returns true if activity started.
Definition at line 432 of file avatar.cpp.
 {
     if( !book ) {
         add_msg( m_info, _( "Never mind." ) );
         return false;
     }
     std::vector<std::string> fail_messages;
     const Character *reader = get_book_reader( *book, fail_messages );
     if( reader == nullptr ) {
         // We can't read, and neither can our followers
         for( const std::string &reason : fail_messages ) {
             add_msg( m_bad, reason );
         }
         return false;
     }
     // spells are handled in a different place
     // src/iuse_actor.cpp -> learn_spell_actor::use
     if( book->get_use( "learn_spell" ) ) {
         book->get_use( "learn_spell" )->call( this, *book, pos() );
         return true;
     }
     bool continuous = false;
     const time_duration time_taken = time_to_read( *book, *reader );
     add_msg_debug( debugmode::DF_ACT_READ, "avatar::read time_taken = %s",
                    to_string_writable( time_taken ) );
     // If the player hasn't read this book before, skim it to get an idea of what's in it.
     if( !has_identified( book->typeId() ) ) {
         if( reader != this ) {
             add_msg( m_info, fail_messages[0] );
             add_msg( m_info, _( "%s reads aloud" ), reader->disp_name() );
         }
         assign_activity( read_activity_actor( time_taken, book, ereader, false ) );
         return true;
     }
     if( book->typeId() == itype_guidebook ) {
         // special guidebook effect: print a misc. hint when read
         if( reader != this ) {
             add_msg( m_info, fail_messages[0] );
             dynamic_cast<const npc &>( *reader ).say( get_hint() );
         } else {
             add_msg( m_info, get_hint() );
         }
         get_event_bus().send<event_type::reads_book>( getID(), book->typeId() );
         mod_moves( -100 );
         return false;
     }
     const cata::value_ptr<islot_book> &type = book->type->book;
     const skill_id &skill = type->skill;
     const std::string skill_name = skill ? skill.obj().name() : "";
     // Find NPCs to join the study session:
     std::map<Character *, std::string> learners;
     //reading only for fun
     std::map<Character *, std::string> fun_learners;
     std::map<Character *, std::string> nonlearners;
     for( Character *elem : get_crafting_helpers() ) {
         const book_mastery mastery = elem->get_book_mastery( *book );
         const bool morale_req = elem->fun_to_read( *book ) || elem->has_morale_to_read();
         // Note that the reader cannot be a nonlearner
         // since a reader should always have enough morale to read
         // and at the very least be able to understand the book
         if( elem->is_deaf() && elem != reader ) {
             nonlearners.insert( { elem, _( " (deaf)" ) } );
         } else if( mastery == book_mastery::MASTERED && elem->fun_to_read( *book ) ) {
             fun_learners.insert( {elem, elem == reader ? _( " (reading aloud to you)" ) : "" } );
         } else if( mastery == book_mastery::LEARNING && morale_req ) {
             learners.insert( {elem, elem == reader ? _( " (reading aloud to you)" ) : ""} );
         } else {
             std::string reason = _( " (uninterested)" );
             if( !morale_req ) {
                 reason = _( " (too sad)" );
             } else if( mastery == book_mastery::CANT_UNDERSTAND ) {
                 reason = string_format( _( " (needs %d %s)" ), type->req, skill_name );
             } else if( mastery == book_mastery::MASTERED ) {
                 reason = string_format( _( " (already has %d %s)" ), type->level, skill_name );
             }
             nonlearners.insert( { elem, reason } );
         }
     }
     int learner_id = -1;
     const bool is_martialarts = book->type->use_methods.count( "MA_MANUAL" );
     //only show the menu if there's useful information or multiple options
     if( ( skill || !nonlearners.empty() || !fun_learners.empty() ) && !is_martialarts ) {
         uilist menu;
         // Some helpers to reduce repetition:
         auto length = []( const std::pair<Character *, std::string> &elem ) {
             return utf8_width( elem.first->disp_name() ) + utf8_width( elem.second );
         };
         auto max_length = [&length]( const std::map<Character *, std::string> &m ) {
             auto max_ele = std::max_element( m.begin(),
                                              m.end(), [&length]( const std::pair<Character *, std::string> &left,
             const std::pair<Character *, std::string> &right ) {
                 return length( left ) < length( right );
             } );
             return max_ele == m.end() ? 0 : length( *max_ele );
         };
         auto get_text = [&]( const std::map<Character *, std::string> &m,
                              const std::pair<Character *, std::string> &elem
         ) {
             const int lvl = elem.first->get_knowledge_level( skill );
             const std::string lvl_text = skill ? string_format( _( " | current level: %d" ), lvl ) : "";
             const std::string name_text = elem.first->disp_name() + elem.second;
             return string_format( "%s%s", left_justify( name_text, max_length( m ) ), lvl_text );
         };
         auto add_header = [&menu]( const std::string & str ) {
             menu.addentry( -1, false, -1, "" );
             uilist_entry header( -1, false, -1, str, c_yellow, c_yellow );
             header.force_color = true;
             menu.entries.push_back( header );
         };
         menu.title = !skill ? string_format( _( "Reading %s" ), book->type_name() ) :
                      //~ %1$s: book name, %2$s: skill name, %3$d and %4$d: skill levels
                      string_format( _( "Reading %1$s (can train %2$s from %3$d to %4$d)" ), book->type_name(),
                                     skill_name, type->req, type->level );
         menu.addentry( 0, true, '0', _( "Read once" ) );
         const int lvl = get_knowledge_level( skill );
         menu.addentry( 2 + getID().get_value(), lvl < type->level, '1',
                        string_format( _( "Read until you gain a level | current level: %d" ), lvl ) );
         // select until player gets level by default
         if( lvl < type->level ) {
             menu.selected = 1;
         }
         if( !learners.empty() ) {
             add_header( _( "Read until this character gains a level:" ) );
             for( const std::pair<Character *const, std::string> &elem : learners ) {
                 menu.addentry( 2 + elem.first->getID().get_value(), true, -1,
                                get_text( learners, elem ) );
             }
         }
         if( !fun_learners.empty() ) {
             add_header( _( "Reading for fun:" ) );
             for( const std::pair<Character *const, std::string> &elem : fun_learners ) {
                 menu.addentry( -1, false, -1, get_text( fun_learners, elem ) );
             }
         }
         if( !nonlearners.empty() ) {
             add_header( _( "Not participating:" ) );
             for( const std::pair<Character *const, std::string> &elem : nonlearners ) {
                 menu.addentry( -1, false, -1, get_text( nonlearners, elem ) );
             }
         }
         menu.query( true );
         if( menu.ret == UILIST_CANCEL ) {
             add_msg( m_info, _( "Never mind." ) );
             return false;
         } else if( menu.ret >= 2 ) {
             continuous = true;
             learner_id = menu.ret - 2;
         }
     }
     if( is_martialarts ) {
         if( martial_arts_data->has_martialart( martial_art_learned_from( *book->type ) ) ) {
             add_msg_if_player( m_info, _( "You already know all this book has to teach." ) );
             return false;
         }
         uilist menu;
         menu.title = string_format( _( "Train %s from manual:" ),
                                     martial_art_learned_from( *book->type )->name );
         menu.addentry( 1, true, '1', _( "Train once" ) );
         menu.addentry( 2, true, '0', _( "Train until tired or success" ) );
         menu.query( true );
         if( menu.ret == UILIST_CANCEL ) {
             add_msg( m_info, _( "Never mind." ) );
             return false;
         } else if( menu.ret == 1 ) {
             continuous = false;
         } else {    // menu.ret == 2
             continuous = true;
         }
     }
     add_msg( m_info, _( "Now reading %s, %s to stop early." ),
              book->type_name(), press_x( ACTION_PAUSE ) );
     // Print some informational messages
     if( reader != this ) {
         add_msg( m_info, fail_messages[0] );
         add_msg( m_info, _( "%s reads aloud" ), reader->disp_name() );
     } else if( !learners.empty() || !fun_learners.empty() ) {
         add_msg( m_info, _( "You read aloud" ) );
     }
     if( learners.size() == 1 ) {
         add_msg( m_info, _( "%s studies with you." ), learners.begin()->first->disp_name() );
     } else if( !learners.empty() ) {
         const std::string them = enumerate_as_string( learners.begin(),
         learners.end(), [&]( const std::pair<Character *, std::string> &elem ) {
             return elem.first->disp_name();
         } );
         add_msg( m_info, _( "%s study with you." ), them );
     }
     // Don't include the reader as it would be too redundant.
     std::set<std::string> readers;
     for( const std::pair<Character *const, std::string> &elem : fun_learners ) {
         if( elem.first != reader ) {
             readers.insert( elem.first->disp_name() );
         }
     }
     if( readers.size() == 1 ) {
         add_msg( m_info, _( "%s reads with you for fun." ), readers.begin()->c_str() );
     } else if( !readers.empty() ) {
         const std::string them = enumerate_as_string( readers );
         add_msg( m_info, _( "%s read with you for fun." ), them );
     }
     if( std::min( fine_detail_vision_mod(), reader->fine_detail_vision_mod() ) > 1.0 ) {
         add_msg( m_warning,
                  _( "It's difficult for %s to see fine details right now.  Reading will take longer than usual." ),
                  reader->disp_name() );
     }
     const int intelligence = get_int();
     const bool complex_penalty = type->intel > std::min( intelligence, reader->get_int() ) &&
                                  !reader->has_trait( trait_PROF_DICEMASTER );
     const Character *complex_player = reader->get_int() < intelligence ? reader : this;
     if( complex_penalty ) {
         add_msg( m_warning,
                  _( "This book is too complex for %s to easily understand.  It will take longer to read." ),
                  complex_player->disp_name() );
     }
     // push an identifier of martial art book to the action handling
     if( is_martialarts &&
         get_stamina() < get_stamina_max() / 10 )  {
         add_msg( m_info, _( "You are too exhausted to train martial arts." ) );
         return false;
     }
     assign_activity( read_activity_actor( time_taken, book, ereader, continuous, learner_id ) );
     return true;
 }
References _, ACTION_PAUSE, debug_menu::add_header(), add_msg(), add_msg_debug, Character::add_msg_if_player(), uilist::addentry(), Character::assign_activity(), itype::book, c_yellow, use_function::call(), CANT_UNDERSTAND, debugmode::DF_ACT_READ, Character::disp_name(), uilist::entries, enumerate_as_string(), Character::fine_detail_vision_mod(), uilist_entry::force_color, Character::get_book_reader(), Character::get_crafting_helpers(), get_event_bus(), get_hint(), Character::get_int(), Character::get_knowledge_level(), Character::get_stamina(), Character::get_stamina_max(), item::get_use(), Creature::get_value(), Character::getID(), has_identified(), Character::has_trait(), intelligence, itype_guidebook, LEARNING, left, left_justify(), length, m_bad, m_info, m_warning, martial_art_learned_from(), Character::martial_arts_data, MASTERED, min(), Creature::mod_moves(), martialart::name, Skill::name(), string_id< T >::obj(), Creature::pos(), press_x(), uilist::query(), reads_book, uilist::ret, right, npc::say(), uilist::selected, event_bus::send(), string_format(), Character::time_to_read(), uilist::title, to_string_writable(), trait_PROF_DICEMASTER, type, item::type, item::type_name(), item::typeId(), UILIST_CANCEL, itype::use_methods, and utf8_width().
Referenced by iuse::ebookread(), game::inventory_item_menu(), and read().
reassign_item()
void avatar::reassign_item (item & it, int invlet)
Reassign letter.
Definition at line 1841 of file avatar.cpp.
 {
     bool remove_old = true;
     if( invlet ) {
         item *prev = invlet_to_item( invlet );
         if( prev != nullptr ) {
             remove_old = it.typeId() != prev->typeId();
             inv->reassign_item( *prev, it.invlet, remove_old );
         }
     }
     if( !invlet || inv_chars.valid( invlet ) ) {
         const auto iter = inv->assigned_invlet.find( it.invlet );
         bool found = iter != inv->assigned_invlet.end();
         if( found ) {
             inv->assigned_invlet.erase( iter );
         }
         if( invlet && ( !found || it.invlet != invlet ) ) {
             inv->assigned_invlet[invlet] = it.typeId();
         }
         inv->reassign_item( it, invlet, remove_old );
     }
 }
References Character::inv, inv_chars, item::invlet, Character::invlet_to_item(), item::typeId(), and invlet_wrapper::valid().
Referenced by game_menus::inv::reassign_letter().
rebuild_aim_cache()
void avatar::rebuild_aim_cache ()
Definition at line 1248 of file avatar.cpp.
 {
     double pi = 2 * acos( 0.0 );
     const tripoint local_last_target = get_map().getlocal( last_target_pos.value() );
     float base_angle = atan2f( local_last_target.y - posy(),
                                local_last_target.x - posx() );
     // move from -pi to pi, to 0 to 2pi for angles
     if( base_angle < 0 ) {
         base_angle = base_angle + 2 * pi;
     }
     // todo: this is not the correct weapon when aiming with fake items
     item *weapon = get_wielded_item() ? &*get_wielded_item() : &null_item_reference();
     // calc steadiness with player recoil (like they are taking a regular shot not careful etc.
     float range = 3.0f - 2.8f * calc_steadiness( *this, *weapon, last_target_pos.value(), recoil );
     // pin between pi and negative pi
     float upper_bound = base_angle + range;
     float lower_bound = base_angle - range;
     // cap each within 0 - 2pi
     if( upper_bound > 2 * pi ) {
         upper_bound = upper_bound - 2 * pi;
     }
     if( lower_bound < 0 ) {
         lower_bound = lower_bound + 2 * pi;
     }
     for( int smx = 0; smx < MAPSIZE_X; ++smx ) {
         for( int smy = 0; smy < MAPSIZE_Y; ++smy ) {
             float current_angle = atan2f( smy - posy(), smx - posx() );
             // move from -pi to pi, to 0 to 2pi for angles
             if( current_angle < 0 ) {
                 current_angle = current_angle + 2 * pi;
             }
             // some basic angle inclusion math, but also everything with 15 is still seen
             if( rl_dist( tripoint( point( smx, smy ), pos().z ), pos() ) < 15 ) {
                 aim_cache[smx][smy] = false;
             } else if( lower_bound > upper_bound ) {
                 aim_cache[smx][smy] = !( current_angle >= lower_bound ||
                                          current_angle <= upper_bound );
             } else {
                 aim_cache[smx][smy] = !( current_angle >= lower_bound &&
                                          current_angle <= upper_bound );
             }
         }
     }
     // set cache as no longer dirty
     aim_cache_dirty = false;
 }
References units::acos(), aim_cache, aim_cache_dirty, calc_steadiness(), get_map(), Character::get_wielded_item(), map::getlocal(), Character::last_target_pos, MAPSIZE_X, MAPSIZE_Y, null_item_reference(), point, Creature::pos(), Creature::posx(), Creature::posy(), Character::recoil, rl_dist(), tripoint, Character::weapon, tripoint::x, and tripoint::y.
Referenced by cant_see().
remove_active_mission()
void avatar::remove_active_mission (mission & cur_mission)
Definition at line 404 of file avatar.cpp.
 {
     cur_mission.remove_active_world_mission( cur_mission );
     const auto iter = std::find( active_missions.begin(), active_missions.end(), &cur_mission );
     if( iter == active_missions.end() ) {
         debugmsg( "removed mission %s was not in the active_missions list",
                   cur_mission.mission_id().c_str() );
     } else {
         active_missions.erase( iter );
     }
     if( &cur_mission == active_mission ) {
         if( active_missions.empty() ) {
             active_mission = nullptr;
         } else {
             active_mission = active_missions.front();
         }
     }
 }
References active_mission, active_missions, string_id< T >::c_str(), debugmsg, mission::mission_id(), and mission::remove_active_world_mission().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_active_mission().
reset_all_missions()
void avatar::reset_all_missions ()
Resets all missions before saving character to template.
Definition at line 331 of file avatar.cpp.
 {
     active_mission = nullptr;
     active_missions.clear();
     completed_missions.clear();
     failed_missions.clear();
 }
References active_mission, active_missions, completed_missions, and failed_missions.
Referenced by main_menu::world_tab().
reset_move_mode()
void avatar::reset_move_mode ()
Definition at line 1358 of file avatar.cpp.
 {
     if( !is_walking() ) {
         set_movement_mode( move_mode_walk );
     }
 }
References Character::is_walking(), move_mode_walk, and set_movement_mode().
Referenced by game::do_regular_action(), game::peek(), and overmap_ui::try_travel_to_destination().
reset_stats()
void avatar::reset_stats () override virtual
Resets stats, and applies effects in an idempotent manner.
Implements Creature.
Definition at line 963 of file avatar.cpp.
 {
     const int current_stim = get_stim();
     // Trait / mutation buffs
     if( has_trait( trait_THICK_SCALES ) ) {
         add_miss_reason( _( "Your thick scales get in the way." ), 2 );
     }
     if( has_trait( trait_CHITIN2 ) || has_trait( trait_CHITIN3 ) || has_trait( trait_CHITIN_FUR3 ) ) {
         add_miss_reason( _( "Your chitin gets in the way." ), 1 );
     }
     if( has_trait( trait_COMPOUND_EYES ) && !wearing_something_on( bodypart_id( "eyes" ) ) ) {
         mod_per_bonus( 2 );
     }
     if( has_trait( trait_INSECT_ARMS ) ) {
         add_miss_reason( _( "Your insect limbs get in the way." ), 2 );
     }
     if( has_trait( trait_INSECT_ARMS_OK ) ) {
         if( !wearing_fitting_on( bodypart_id( "torso" ) ) ) {
             mod_dex_bonus( 1 );
         } else {
             add_miss_reason( _( "Your clothing restricts your insect arms." ), 1 );
         }
     }
     if( has_flag( json_flag_WEBBED_HANDS ) ) {
         add_miss_reason( _( "Your webbed hands get in the way." ), 1 );
     }
     if( has_trait( trait_ARACHNID_ARMS ) ) {
         add_miss_reason( _( "Your arachnid limbs get in the way." ), 4 );
     }
     if( has_trait( trait_ARACHNID_ARMS_OK ) ) {
         if( !wearing_fitting_on( bodypart_id( "torso" ) ) ) {
             mod_dex_bonus( 2 );
         } else {
             add_miss_reason( _( "Your clothing constricts your arachnid limbs." ), 2 );
         }
     }
     const auto set_fake_effect_dur = [this]( const efftype_id & type, const time_duration & dur ) {
         effect &eff = get_effect( type );
         if( eff.get_duration() == dur ) {
             return;
         }
         if( eff.is_null() && dur > 0_turns ) {
             add_effect( type, dur, true );
         } else if( dur > 0_turns ) {
             eff.set_duration( dur );
         } else {
             remove_effect( type );
         }
     };
     // Painkiller
     set_fake_effect_dur( effect_pkill, 1_turns * get_painkiller() );
     // Pain
     if( get_perceived_pain() > 0 ) {
         const stat_mod ppen = get_pain_penalty();
         mod_str_bonus( -ppen.strength );
         mod_dex_bonus( -ppen.dexterity );
         mod_int_bonus( -ppen.intelligence );
         mod_per_bonus( -ppen.perception );
         if( ppen.dexterity > 0 ) {
             add_miss_reason( _( "Your pain distracts you!" ), static_cast<unsigned>( ppen.dexterity ) );
         }
     }
     // Radiation
     set_fake_effect_dur( effect_irradiated, 1_turns * get_rad() );
     // Morale
     const int morale = get_morale_level();
     set_fake_effect_dur( effect_happy, 1_turns * morale );
     set_fake_effect_dur( effect_sad, 1_turns * -morale );
     // Stimulants
     set_fake_effect_dur( effect_stim, 1_turns * current_stim );
     set_fake_effect_dur( effect_depressants, 1_turns * -current_stim );
     if( has_trait( trait_STIMBOOST ) ) {
         set_fake_effect_dur( effect_stim_overdose, 1_turns * ( current_stim - 60 ) );
     } else {
         set_fake_effect_dur( effect_stim_overdose, 1_turns * ( current_stim - 30 ) );
     }
     // Starvation
     const float bmi = get_bmi_fat();
     if( bmi < character_weight_category::normal ) {
         const int str_penalty = std::floor( ( 1.0f - ( get_bmi_fat() /
                                               character_weight_category::normal ) ) * str_max );
         const int dexint_penalty = std::floor( ( character_weight_category::normal - bmi ) * 3.0f );
         add_miss_reason( _( "You're weak from hunger." ),
                          static_cast<unsigned>( ( get_starvation() + 300 ) / 1000 ) );
         mod_str_bonus( -1 * str_penalty );
         mod_dex_bonus( -1 * dexint_penalty );
         mod_int_bonus( -1 * dexint_penalty );
     }
     // Thirst
     if( get_thirst() >= 200 ) {
         // We die at 1200
         const int dex_mod = -get_thirst() / 200;
         add_miss_reason( _( "You're weak from thirst." ), static_cast<unsigned>( -dex_mod ) );
         mod_str_bonus( -get_thirst() / 200 );
         mod_dex_bonus( dex_mod );
         mod_int_bonus( -get_thirst() / 200 );
         mod_per_bonus( -get_thirst() / 200 );
     }
     if( get_sleep_deprivation() >= SLEEP_DEPRIVATION_HARMLESS ) {
         set_fake_effect_dur( effect_sleep_deprived, 1_turns * get_sleep_deprivation() );
     } else if( has_effect( effect_sleep_deprived ) ) {
         remove_effect( effect_sleep_deprived );
     }
     // Dodge-related effects
     mod_dodge_bonus( mabuff_dodge_bonus() );
     // Whiskers don't work so well if they're covered
     if( has_trait( trait_WHISKERS ) && !natural_attack_restricted_on( bodypart_id( "mouth" ) ) ) {
         mod_dodge_bonus( 1 );
     }
     if( has_trait( trait_WHISKERS_RAT ) && !natural_attack_restricted_on( bodypart_id( "mouth" ) ) ) {
         mod_dodge_bonus( 2 );
     }
     // depending on mounts size, attacks will hit the mount and use their dodge rating.
     // if they hit the player, the player cannot dodge as effectively.
     if( is_mounted() ) {
         mod_dodge_bonus( -4 );
     }
     // Spider hair is basically a full-body set of whiskers, once you get the brain for it
     if( has_trait( trait_CHITIN_FUR3 ) ) {
         static const std::array<bodypart_str_id, 5> parts {
             body_part_head, body_part_arm_r, body_part_arm_l,
             body_part_leg_r, body_part_leg_l
         };
         for( const bodypart_str_id &bp : parts ) {
             if( !wearing_something_on( bp ) ) {
                 mod_dodge_bonus( +1 );
             }
         }
         // Torso handled separately, bigger bonus
         if( !wearing_something_on( bodypart_id( "torso" ) ) ) {
             mod_dodge_bonus( 4 );
         }
     }
     // Apply static martial arts buffs
     martial_arts_data->ma_static_effects( *this );
     // Effects
     for( const auto &maps : *effects ) {
         for( const auto &i : maps.second ) {
             const effect &it = i.second;
             bool reduced = resists_effect( it );
             mod_str_bonus( it.get_mod( "STR", reduced ) );
             mod_dex_bonus( it.get_mod( "DEX", reduced ) );
             mod_per_bonus( it.get_mod( "PER", reduced ) );
             mod_int_bonus( it.get_mod( "INT", reduced ) );
         }
     }
     Character::reset_stats();
     recalc_sight_limits();
     recalc_speed_bonus();
 }
References _, Creature::add_effect(), Character::add_miss_reason(), body_part_arm_l, body_part_arm_r, body_part_head, body_part_leg_l, body_part_leg_r, bp, stat_mod::dexterity, dur, effect_depressants, effect_happy, effect_irradiated, effect_pkill, effect_sad, effect_sleep_deprived, effect_stim, effect_stim_overdose, Creature::effects, floor(), Character::get_bmi_fat(), effect::get_duration(), Creature::get_effect(), effect::get_mod(), Character::get_morale_level(), Character::get_pain_penalty(), Character::get_painkiller(), Character::get_perceived_pain(), Character::get_rad(), Character::get_sleep_deprivation(), Character::get_starvation(), Character::get_stim(), Character::get_thirst(), Creature::has_effect(), Character::has_flag(), Character::has_trait(), stat_mod::intelligence, Character::is_mounted(), effect::is_null(), json_flag_WEBBED_HANDS, Character::mabuff_dodge_bonus(), Character::martial_arts_data, Character::mod_dex_bonus(), Creature::mod_dodge_bonus(), Character::mod_int_bonus(), Character::mod_per_bonus(), Character::mod_str_bonus(), Character::morale, Character::natural_attack_restricted_on(), character_weight_category::normal, stat_mod::perception, Character::recalc_sight_limits(), Character::recalc_speed_bonus(), Creature::remove_effect(), Character::reset_stats(), Creature::resists_effect(), effect::set_duration(), SLEEP_DEPRIVATION_HARMLESS, Character::str_max, stat_mod::strength, trait_ARACHNID_ARMS, trait_ARACHNID_ARMS_OK, trait_CHITIN2, trait_CHITIN3, trait_CHITIN_FUR3, trait_COMPOUND_EYES, trait_INSECT_ARMS, trait_INSECT_ARMS_OK, trait_STIMBOOST, trait_THICK_SCALES, trait_WHISKERS, trait_WHISKERS_RAT, type, Character::wearing_fitting_on(), and Character::wearing_something_on().
save_map_memory()
bool avatar::save_map_memory ()
Definition at line 266 of file avatar.cpp.
 {
     return player_map_memory->save( get_map().getglobal( pos() ) );
 }
References get_map(), player_map_memory, and Creature::pos().
Referenced by game::save_player_data().
save_template()
void avatar::save_template (const std::string & name, pool_type pool)
Definition at line 4844 of file newcharacter.cpp.
 {
     write_to_file( PATH_INFO::templatedir() + name + ".template", [&]( std::ostream & fout ) {
         JsonOut jsout( fout, true );
         jsout.start_array();
         jsout.start_object();
         jsout.member( "limit", pool );
         jsout.member( "random_start_location", random_start_location );
         if( !random_start_location ) {
             jsout.member( "start_location", start_location );
         }
         jsout.end_object();
         serialize( jsout );
         jsout.end_array();
     }, _( "player template" ) );
 }
References _, JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), Character::name, Character::random_start_location, serialize(), JsonOut::start_array(), JsonOut::start_object(), PATH_INFO::templatedir(), and write_to_file().
Referenced by character_to_template(), create(), and set_description().
select_ammo()
item::reload_option avatar::select_ammo (const item_location & base, bool prompt = false, bool empty = true) override virtual
Select suitable ammo with which to reload the item.
Parameters
base Item to select ammo for
prompt force display of the menu even if only one choice
empty allow selection of empty magazines
Implements Character.
Definition at line 1472 of file avatar.cpp.
 {
     if( !base ) {
         return item::reload_option();
     }
     return game_menus::inv::select_ammo( *this, base, prompt, empty );
 }
References Pickup::prompt, and game_menus::inv::select_ammo().
Referenced by game::do_regular_action(), favorite_ammo_or_select(), and game::reload().
serialize()
void avatar::serialize (JsonOut & json) const override virtual
Implements Character.
Definition at line 1529 of file savegame_json.cpp.
 {
     json.start_object();
     store( json );
     json.end_object();
 }
References JsonOut::end_object(), and JsonOut::start_object().
Referenced by save_template().
set_active_mission()
void avatar::set_active_mission (mission & cur_mission)
Set which mission is active.
The mission must be listed in active_missions.
Definition at line 347 of file avatar.cpp.
 {
     const auto iter = std::find( active_missions.begin(), active_missions.end(), &cur_mission );
     if( iter == active_missions.end() ) {
         debugmsg( "new objective %s is not in the active_missions list",
                   cur_mission.mission_id().c_str() );
     } else {
         active_mission = &cur_mission;
     }
 }
References active_mission, active_missions, string_id< T >::c_str(), debugmsg, and mission::mission_id().
Referenced by mission_ui_impl::draw_controls(), mission_ui_impl::draw_mission_names(), and on_mission_assignment().
set_location()
void avatar::set_location (const tripoint_abs_ms & loc)
Definition at line 2054 of file avatar.cpp.
 {
     Creature::set_location( loc );
 }
References Creature::set_location().
set_movement_mode()
void avatar::set_movement_mode (const move_mode_id & mode) override virtual
Implements Character.
Definition at line 1307 of file avatar.cpp.
 {
     if( can_switch_to( new_mode ) ) {
         if( is_hauling() && new_mode->stop_hauling() ) {
             stop_hauling();
         }
         add_msg( new_mode->change_message( true, get_steed_type() ) );
         move_mode = new_mode;
         // Enchantments based on move modes can stack inappropriately without a recalc here
         recalculate_enchantment_cache();
         // crouching affects visibility
         get_map().set_seen_cache_dirty( pos().z );
         recoil = MAX_RECOIL;
     } else {
         add_msg( new_mode->change_message( false, get_steed_type() ) );
     }
 }
References add_msg(), Character::can_switch_to(), move_mode::change_message(), get_map(), Character::get_steed_type(), Character::is_hauling(), MAX_RECOIL, Creature::pos(), Character::recalculate_enchantment_cache(), Character::recoil, map::set_seen_cache_dirty(), Character::stop_hauling(), and move_mode::stop_hauling().
Referenced by activate_crouch_mode(), cycle_move_mode(), cycle_move_mode_reverse(), avatar_action::move(), open_movement_mode_menu(), reset_move_mode(), toggle_crouch_mode(), toggle_prone_mode(), and toggle_run_mode().
set_save_id()
void avatar::set_save_id (const std::string & id) inline
Definition at line 131 of file avatar.h.
{
             save_id = id;
         }
References Character::id, and save_id.
Referenced by debug_menu::character_edit_desc_menu(), and game::load().
should_show_map_memory()
bool avatar::should_show_map_memory () const
Definition at line 258 of file avatar.cpp.
 {
     if( get_timed_events().get( timed_event_type::OVERRIDE_PLACE ) ) {
         return false;
     }
     return show_map_memory;
 }
References rotatable_symbols::get(), get_timed_events(), OVERRIDE_PLACE, and show_map_memory.
Referenced by get_memorized_tile().
steal()
void avatar::steal (npc & target)
Try to steal an item from the NPC's inventory.
May result in fail attempt, when NPC not notices you, notices your steal attempt and getting angry with you, and you successfully stealing the item.
Parameters
target Target NPC to steal from
Dexterity defines the chance to steal Unarmed adds bonus to stealing when wielding nothing
Definition at line 2929 of file melee.cpp.
 {
     if( target.is_enemy() ) {
         add_msg( _( "%s is hostile!" ), target.get_name() );
         return;
     }
     item_location loc = game_menus::inv::steal( *this, target );
     if( !loc ) {
         return;
     }
     /** @EFFECT_DEX defines the chance to steal */
     int my_roll = dice( 3, get_dex() );
     /** @EFFECT_UNARMED adds bonus to stealing when wielding nothing */
     if( !is_armed() ) {
         my_roll += dice( 4, 3 );
     }
     if( has_trait( trait_DEFT ) ) {
         my_roll += dice( 2, 6 );
     }
     if( has_trait( trait_CLUMSY ) ) {
         my_roll -= dice( 4, 6 );
     }
     int their_roll = dice( 5, target.get_per() );
     const item *it = loc.get_item();
     if( my_roll >= their_roll && !target.is_hallucination() ) {
         add_msg( _( "You sneakily steal %1$s from %2$s!" ),
                  it->tname(), target.get_name() );
         i_add( target.i_rem( it ) );
     } else if( my_roll >= their_roll / 2 ) {
         add_msg( _( "You failed to steal %1$s from %2$s, but did not attract attention." ),
                  it->tname(), target.get_name() );
     } else  {
         add_msg( _( "You failed to steal %1$s from %2$s." ),
                  it->tname(), target.get_name() );
         target.on_attacked( *this );
     }
     // consider to deduce less/more moves for balance
     mod_moves( -200 );
 }
References _, add_msg(), dice(), Character::get_dex(), item_location::get_item(), Character::get_name(), Character::get_per(), Character::has_trait(), Character::i_add(), Character::i_rem(), Character::is_armed(), npc::is_enemy(), npc::is_hallucination(), Creature::mod_moves(), npc::on_attacked(), game_menus::inv::steal(), item::tname(), trait_CLUMSY, and trait_DEFT.
Referenced by game::npc_menu().
store()
void avatar::store (JsonOut & json) const
Definition at line 1538 of file savegame_json.cpp.
 {
     Character::store( json );
     // player-specific specifics
     if( prof != nullptr ) {
         json.member( "profession", prof->ident() );
     }
     if( get_scenario() != nullptr ) {
         json.member( "scenario", get_scenario()->ident() );
     }
     if( !hobbies.empty() ) {
         json.member( "hobbies" );
         json.start_array();
         for( const profession *hobby : hobbies ) {
             json.write( hobby->ident() );
         }
         json.end_array();
     }
     json.member( "followers", follower_ids );
     if( shadow_npc ) {
         json.member( "shadow_npc", *shadow_npc );
     }
     // someday, npcs may drive
     json.member( "controlling_vehicle", controlling_vehicle );
     // shopping carts, furniture etc
     json.member( "grab_point", grab_point );
     json.member( "grab_type", obj_type_name[static_cast<int>( grab_type ) ] );
     // npc: unimplemented, potentially useful
     json.member( "learned_recipes", *learned_recipes );
     // Player only, books they have read at least once.
     json.member( "items_identified", items_identified );
     // Player only, snippets they have read at least once.
     json.member( "snippets_read", snippets_read );
     json.member( "translocators", translocators );
     // mission stuff
     json.member( "active_mission", active_mission == nullptr ? -1 : active_mission->get_id() );
     json.member( "active_missions", mission::to_uid_vector( active_missions ) );
     json.member( "completed_missions", mission::to_uid_vector( completed_missions ) );
     json.member( "failed_missions", mission::to_uid_vector( failed_missions ) );
     json.member( "show_map_memory", show_map_memory );
     json.member( "assigned_invlet" );
     json.start_array();
     for( const auto &iter : inv->assigned_invlet ) {
         json.start_array();
         json.write( iter.first );
         json.write( iter.second );
         json.end_array();
     }
     json.end_array();
     json.member( "invcache" );
     inv->json_save_invcache( json );
     json.member( "calorie_diary", calorie_diary );
     json.member( "preferred_aiming_mode", preferred_aiming_mode );
     json.member( "power_prev_turn", power_prev_turn );
 }
References JsonOut::end_array(), get_scenario(), JsonOut::member(), obj_type_name, JsonOut::start_array(), Character::store(), mission::to_uid_vector(), and JsonOut::write().
talk_to()
void avatar::talk_to (std::unique_ptr< talker > talk_with, bool radio_contact = false, bool is_computer = false, bool is_not_conversation = false)
Definition at line 1358 of file npctalk.cpp.
 {
     const bool has_mind_control = has_trait( trait_DEBUG_MIND_CONTROL );
     if( !talk_with->will_talk_to_u( *this, has_mind_control ) ) {
         return;
     }
     dialogue d( get_talker_for( *this ), std::move( talk_with ), {} );
     d.by_radio = radio_contact;
     dialogue_by_radio = radio_contact;
     d.actor( true )->check_missions();
     for( mission *&mission : d.actor( true )->assigned_missions() ) {
         if( mission->get_assigned_player_id() == getID() ) {
             d.missions_assigned.push_back( mission );
         }
     }
     for( const std::string &topic_id : d.actor( true )->get_topics( radio_contact ) ) {
         d.add_topic( topic_id );
     }
     for( const std::string &topic_id : d.actor( true )->get_topics( radio_contact ) ) {
         d.add_topic( topic_id );
     }
     dialogue_window d_win;
     d_win.is_computer = is_computer;
     d_win.is_not_conversation = is_not_conversation;
     // Main dialogue loop
     do {
         d.actor( true )->update_missions( d.missions_assigned );
         const talk_topic next = d.opt( d_win, d.topic_stack.back() );
         if( next.id == "TALK_NONE" ) {
             int cat = topic_category( d.topic_stack.back() );
             do {
                 d.topic_stack.pop_back();
             } while( cat != -1 && topic_category( d.topic_stack.back() ) == cat );
         }
         if( next.id == "TALK_DONE" || d.topic_stack.empty() ) {
             npc *npc_actor = d.actor( true )->get_npc();
             if( npc_actor ) {
                 d.actor( true )->say( npc_actor->chat_snippets().snip_bye.translated() );
             }
             d.done = true;
         } else if( next.id != "TALK_NONE" ) {
             d.add_topic( next );
         }
     } while( !d.done );
     if( activity.id() == ACT_AIM && !has_weapon() ) {
         cancel_activity();
         // don't query certain activities that are started from dialogue
     } else if( activity.id() == ACT_TRAIN || activity.id() == ACT_WAIT_NPC ||
                activity.id() == ACT_SOCIALIZE || activity.index == d.actor( true )->getID().get_value() ) {
         return;
     }
     if( uistate.distraction_conversation &&
         !d.actor( true )->has_effect( effect_under_operation, bodypart_str_id::NULL_ID() ) ) {
         g->cancel_activity_or_ignore_query( distraction_type::talked_to,
                                             string_format( _( "%s talked to you." ),
                                                     d.actor( true )->disp_name() ) );
     }
 }
References _, ACT_AIM, ACT_SOCIALIZE, ACT_TRAIN, ACT_WAIT_NPC, Character::activity, dialogue::by_radio, Character::cancel_activity(), npc::chat_snippets(), dialogue_by_radio, uistatedata::distraction_conversation, effect_under_operation, g, mission::get_assigned_player_id(), get_talker_for(), Character::getID(), Character::has_trait(), Character::has_weapon(), talk_topic::id, player_activity::id(), player_activity::index, dialogue_window::is_computer, dialogue_window::is_not_conversation, string_id< body_part_type >::NULL_ID(), npc::say(), dialogue_chatbin_snippets::snip_bye, string_format(), talked_to, topic_category(), trait_DEBUG_MIND_CONTROL, translation::translated(), and uistate.
Referenced by game::chat(), faction_manager::display(), game::examine(), npc::execute_action(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), iexamine::intercom(), monexamine::mfriend_menu(), game::npc_menu(), and monexamine::pet_menu().
toggle_crouch_mode()
void avatar::toggle_crouch_mode ()
Definition at line 1334 of file avatar.cpp.
 {
     if( is_crouching() ) {
         set_movement_mode( move_mode_walk );
     } else {
         set_movement_mode( move_mode_crouch );
     }
 }
References Character::is_crouching(), move_mode_crouch, move_mode_walk, and set_movement_mode().
Referenced by game::do_regular_action().
toggle_map_memory()
void avatar::toggle_map_memory ()
Definition at line 248 of file avatar.cpp.
 {
     show_map_memory = !show_map_memory;
 }
References show_map_memory.
Referenced by do_deathcam_action().
toggle_prone_mode()
void avatar::toggle_prone_mode ()
Definition at line 1343 of file avatar.cpp.
 {
     if( is_prone() ) {
         set_movement_mode( move_mode_walk );
     } else {
         set_movement_mode( move_mode_prone );
     }
 }
References Character::is_prone(), move_mode_prone, move_mode_walk, and set_movement_mode().
Referenced by game::do_regular_action().
toggle_run_mode()
void avatar::toggle_run_mode ()
Definition at line 1325 of file avatar.cpp.
 {
     if( is_running() ) {
         set_movement_mode( move_mode_walk );
     } else {
         set_movement_mode( move_mode_run );
     }
 }
References Character::is_running(), move_mode_run, move_mode_walk, and set_movement_mode().
Referenced by game::do_regular_action(), and game::on_move_effects().
total_daily_calories_string()
std::string avatar::total_daily_calories_string () const
Definition at line 1706 of file avatar.cpp.
 {
     const std::string header_string =
         colorize( "       Minutes at each exercise level                  Calories per day",
                   c_white ) + "\n" +
         colorize( "  Day  Sleep None Light Moderate Brisk Active Extra    Gained  Spent  Total",
                   c_yellow ) + "\n";
     const std::string format_string =
         " %4d  %4d   %4d  %4d     %4d  %4d   %4d  %4d    %6d %6d";
     const float no_ex_thresh = ( SLEEP_EXERCISE + NO_EXERCISE ) / 2.0f;
     const float light_ex_thresh = ( NO_EXERCISE + LIGHT_EXERCISE ) / 2.0f;
     const float mod_ex_thresh = ( LIGHT_EXERCISE + MODERATE_EXERCISE ) / 2.0f;
     const float brisk_ex_thresh = ( MODERATE_EXERCISE + BRISK_EXERCISE ) / 2.0f;
     const float active_ex_thresh = ( BRISK_EXERCISE + ACTIVE_EXERCISE ) / 2.0f;
     const float extra_ex_thresh = ( ACTIVE_EXERCISE + EXTRA_EXERCISE ) / 2.0f;
     std::string ret = header_string;
     // Start with today in the first row, day number from start of the Cataclysm
     int today = day_of_season<int>( calendar::turn ) + 1;
     int day_offset = 0;
     for( const daily_calories &day : calorie_diary ) {
         // Yes, this is clunky.
         // Perhaps it should be done in log_activity_level? But that's called a lot more often.
         int sleep_exercise = 0;
         int no_exercise = 0;
         int light_exercise = 0;
         int moderate_exercise = 0;
         int brisk_exercise = 0;
         int active_exercise = 0;
         int extra_exercise = 0;
         for( const std::pair<const float, int> &level : day.activity_levels ) {
             if( level.second > 0 ) {
                 if( level.first < no_ex_thresh ) {
                     sleep_exercise += level.second;
                 } else if( level.first < light_ex_thresh ) {
                     no_exercise += level.second;
                 } else if( level.first < mod_ex_thresh ) {
                     light_exercise += level.second;
                 } else if( level.first < brisk_ex_thresh ) {
                     moderate_exercise += level.second;
                 } else if( level.first < active_ex_thresh ) {
                     brisk_exercise += level.second;
                 } else if( level.first < extra_ex_thresh ) {
                     active_exercise += level.second;
                 } else {
                     extra_exercise += level.second;
                 }
             }
         }
         std::string row_data = string_format( format_string, today + day_offset--,
                                               5 * sleep_exercise,
                                               5 * no_exercise,
                                               5 * light_exercise,
                                               5 * moderate_exercise,
                                               5 * brisk_exercise,
                                               5 * active_exercise,
                                               5 * extra_exercise,
                                               day.gained, day.spent );
         // Alternate gray and white text for row data
         if( day_offset % 2 == 0 ) {
             ret += colorize( row_data, c_white );
         } else {
             ret += colorize( row_data, c_light_gray );
         }
         // Color-code each day's net calories
         std::string total_kcals = string_format( " %6d", day.total() );
         if( day.total() > 4000 ) {
             ret += colorize( total_kcals, c_light_cyan );
         } else if( day.total() > 2000 ) {
             ret += colorize( total_kcals, c_cyan );
         } else if( day.total() > 250 ) {
             ret += colorize( total_kcals, c_light_blue );
         } else if( day.total() < -4000 ) {
             ret += colorize( total_kcals, c_pink );
         } else if( day.total() < -2000 ) {
             ret += colorize( total_kcals, c_red );
         } else if( day.total() < -250 ) {
             ret += colorize( total_kcals, c_light_red );
         } else {
             ret += colorize( total_kcals, c_light_gray );
         }
         ret += "\n";
     }
     return ret;
 }
References ACTIVE_EXERCISE, BRISK_EXERCISE, c_cyan, c_light_blue, c_light_cyan, c_light_gray, c_light_red, c_pink, c_red, c_white, c_yellow, calorie_diary, colorize(), day, EXTRA_EXERCISE, LIGHT_EXERCISE, MODERATE_EXERCISE, NO_EXERCISE, cata::hash64_detail::ret, SLEEP_EXERCISE, string_format(), and calendar::turn.
Referenced by debug_menu::debug_menu_game_state().
try_break_relax_gas()
bool avatar::try_break_relax_gas (const std::string & msg_success, const std::string & msg_failure)
Definition at line 887 of file avatar.cpp.
 {
     const effect &pacify = get_effect( effect_relax_gas, body_part_mouth );
     if( pacify.is_null() ) {
         return true;
     } else if( one_in( pacify.get_intensity() ) ) {
         add_msg( m_good, msg_success );
         return true;
     } else {
         mod_moves( std::max( 0, pacify.get_intensity() * 10 + rng( -30, 30 ) ) );
         add_msg( m_bad, msg_failure );
         return false;
     }
 }
References add_msg(), body_part_mouth, effect_relax_gas, Creature::get_effect(), effect::get_intensity(), effect::is_null(), m_bad, m_good, max(), Creature::mod_moves(), one_in(), and rng().
Referenced by avatar_action::can_fire_weapon(), fire(), avatar_action::move(), and avatar_action::plthrow().
try_to_sleep()
void avatar::try_to_sleep (const time_duration & dur)
Handles sleep attempts by the player, starts ACT_TRY_SLEEP activity.
Definition at line 1926 of file avatar.cpp.
 {
     map &here = get_map();
     const optional_vpart_position vp = here.veh_at( pos() );
     const trap &trap_at_pos = here.tr_at( pos() );
     const ter_id ter_at_pos = here.ter( pos() );
     const furn_id furn_at_pos = here.furn( pos() );
     bool plantsleep = false;
     bool fungaloid_cosplay = false;
     bool websleep = false;
     bool webforce = false;
     bool websleeping = false;
     bool in_shell = false;
     bool watersleep = false;
     if( has_trait( trait_CHLOROMORPH ) ) {
         plantsleep = true;
         const std::unordered_set<ter_str_id> comfy_ters = { ter_t_dirt, ter_t_dirtmound, ter_t_grass, ter_t_pit, ter_t_pit_shallow };
         if( comfy_ters.find( ter_at_pos.id() ) != comfy_ters.end() && !vp &&
             furn_at_pos == furn_str_id::NULL_ID() ) {
             add_msg_if_player( m_good, _( "You relax as your roots embrace the soil." ) );
         } else if( vp ) {
             add_msg_if_player( m_bad, _( "It's impossible to sleep in this wheeled pot!" ) );
         } else if( furn_at_pos != furn_str_id::NULL_ID() ) {
             add_msg_if_player( m_bad,
                                _( "The humans' furniture blocks your roots.  You can't get comfortable." ) );
         } else { // Floor problems
             add_msg_if_player( m_bad, _( "Your roots scrabble ineffectively at the unyielding surface." ) );
         }
     } else if( has_trait( trait_M_SKIN3 ) ) {
         fungaloid_cosplay = true;
         if( here.has_flag_ter_or_furn( ter_furn_flag::TFLAG_FUNGUS, pos() ) ) {
             add_msg_if_player( m_good,
                                _( "Our fibers meld with the ground beneath us.  The gills on our neck begin to seed the air with spores as our awareness fades." ) );
         }
     }
     if( has_trait( trait_WEB_WALKER ) ) {
         websleep = true;
     }
     // Not sure how one would get Arachnid w/o web-making, but Just In Case
     if( has_trait( trait_THRESH_SPIDER ) && ( has_trait( trait_WEB_SPINNER ) ||
             has_trait( trait_WEB_WEAVER ) ) ) {
         webforce = true;
     }
     if( websleep || webforce ) {
         int web = here.get_field_intensity( pos(), fd_web );
         if( !webforce ) {
             // At this point, it's kinda weird, but surprisingly comfy...
             if( web >= 3 ) {
                 add_msg_if_player( m_good,
                                    _( "These thick webs support your weight, and are strangely comfortable" ) );
                 websleeping = true;
             } else if( web > 0 ) {
                 add_msg_if_player( m_info,
                                    _( "You try to sleep, but the webs get in the way.  You brush them aside." ) );
                 here.remove_field( pos(), fd_web );
             }
         } else {
             // Here, you're just not comfortable outside a nice thick web.
             if( web >= 3 ) {
                 add_msg_if_player( m_good, _( "You relax into your web." ) );
                 websleeping = true;
             } else {
                 add_msg_if_player( m_bad,
                                    _( "You try to sleep, but you feel exposed and your spinnerets keep twitching." ) );
                 add_msg_if_player( m_info, _( "Maybe a nice thick web would help you sleep." ) );
             }
         }
     }
     if( has_active_mutation( trait_SHELL2 ) || has_active_mutation( trait_SHELL3 ) ) {
         // Your shell's interior is a comfortable place to sleep.
         in_shell = true;
     }
     if( has_trait( trait_WATERSLEEP ) || has_trait( trait_UNDINE_SLEEP_WATER ) ) {
         if( underwater ) {
             add_msg_if_player( m_good,
                                _( "You lay beneath the waves' embrace, gazing up through the water's surface" ) );
             watersleep = true;
         } else if( here.has_flag_ter( ter_furn_flag::TFLAG_SWIMMABLE, pos() ) ) {
             add_msg_if_player( m_good, _( "You settle into the water and begin to drowse" ) );
             watersleep = true;
         }
     }
     if( !plantsleep && ( furn_at_pos.obj().comfort > static_cast<int>( comfort_level::neutral ) ||
                          ter_at_pos.obj().comfort > static_cast<int>( comfort_level::neutral ) ||
                          trap_at_pos.comfort > static_cast<int>( comfort_level::neutral ) ||
                          in_shell || websleeping || watersleep ||
                          vp.part_with_feature( "SEAT", true ) ||
                          vp.part_with_feature( "BED", true ) ) ) {
         add_msg_if_player( m_good, _( "This is a comfortable place to sleep." ) );
     } else if( !plantsleep && !fungaloid_cosplay && !watersleep ) {
         if( !vp && ter_at_pos != ter_t_floor ) {
             add_msg_if_player( ter_at_pos.obj().movecost <= 2 ?
                                _( "It's a little hard to get to sleep on this %s." ) :
                                _( "It's hard to get to sleep on this %s." ),
                                ter_at_pos.obj().name() );
         } else if( vp ) {
             if( vp->part_with_feature( VPFLAG_AISLE, true ) ) {
                 add_msg_if_player(
                     //~ %1$s: vehicle name, %2$s: vehicle part name
                     _( "It's a little hard to get to sleep on this %2$s in %1$s." ),
                     vp->vehicle().disp_name(),
                     vp->part_with_feature( VPFLAG_AISLE, true )->part().name( false ) );
             } else {
                 add_msg_if_player(
                     //~ %1$s: vehicle name
                     _( "It's hard to get to sleep in %1$s." ),
                     vp->vehicle().disp_name() );
             }
         }
     }
     add_msg_if_player( _( "You start trying to fall asleep." ) );
     if( has_active_bionic( bio_soporific ) ) {
         bio_soporific_powered_at_last_sleep_check = has_power();
         if( bio_soporific_powered_at_last_sleep_check ) {
             // The actual bonus is applied in sleep_spot( p ).
             add_msg_if_player( m_good, _( "Your soporific inducer starts working its magic." ) );
         } else {
             add_msg_if_player( m_bad, _( "Your soporific inducer doesn't have enough power to operate." ) );
         }
     }
     assign_activity( try_sleep_activity_actor( dur ) );
 }
References _, Character::add_msg_if_player(), Character::assign_activity(), bio_soporific, Character::bio_soporific_powered_at_last_sleep_check, map_data_common_t::comfort, trap::comfort, dur, fd_web, map::furn(), map::get_field_intensity(), get_map(), Character::has_active_bionic(), Character::has_active_mutation(), map::has_flag_ter(), map::has_flag_ter_or_furn(), Character::has_power(), Character::has_trait(), int_id< T >::id(), m_bad, m_good, m_info, map_data_common_t::movecost, map_data_common_t::name(), Character::neutral, string_id< furn_t >::NULL_ID(), int_id< T >::obj(), optional_vpart_position::part_with_feature(), Creature::pos(), map::remove_field(), map::ter(), ter_t_dirt, ter_t_dirtmound, ter_t_floor, ter_t_grass, ter_t_pit, ter_t_pit_shallow, TFLAG_FUNGUS, TFLAG_SWIMMABLE, map::tr_at(), trait_CHLOROMORPH, trait_M_SKIN3, trait_SHELL2, trait_SHELL3, trait_THRESH_SPIDER, trait_UNDINE_SLEEP_WATER, trait_WATERSLEEP, trait_WEB_SPINNER, trait_WEB_WALKER, trait_WEB_WEAVER, Creature::underwater, map::veh_at(), and VPFLAG_AISLE.
Referenced by sleep().
update_cardio_acc()
void avatar::update_cardio_acc () override virtual
Implements Character.
Definition at line 1551 of file avatar.cpp.
 {
     // This function should be called once every 24 hours,
     // before the front of the calorie diary is reset for the next day.
     // Cardio goal is 1000 times the ratio of kcals spent versus bmr,
     // giving a default of 1000 for no extra activity.
     const int bmr = get_bmr();
     if( bmr == 0 ) {
         set_cardio_acc( clamp( get_cardio_acc(), get_cardio_acc_base(), get_cardio_acc_base() * 3 ) );
         return;
     }
     const int last_24h_kcal = calorie_diary.front().spent;
     const int cardio_goal = ( last_24h_kcal * get_cardio_acc_base() ) / bmr;
     // If cardio accumulator is below cardio goal, gain some cardio.
     // Or, if cardio accumulator is above cardio goal, lose some cardio.
     const int cardio_accum = get_cardio_acc();
     int adjustment = 0;
     if( cardio_accum > cardio_goal ) {
         adjustment = -std::sqrt( cardio_accum - cardio_goal );
     } else if( cardio_goal > cardio_accum ) {
         adjustment = std::sqrt( cardio_goal - cardio_accum );
     }
     // Set a large sane upper limit to cardio fitness. This could be done
     // asymptotically instead of as a sharp cutoff, but the gradual growth
     // rate of cardio_acc should accomplish that naturally.
     set_cardio_acc( clamp( cardio_accum + adjustment, get_cardio_acc_base(),
                            get_cardio_acc_base() * 3 ) );
 }
References calorie_diary, clamp(), Character::get_bmr(), Character::get_cardio_acc(), Character::get_cardio_acc_base(), Character::set_cardio_acc(), and sqrt().
Referenced by Character::update_body().
upgrade_stat_prompt()
void avatar::upgrade_stat_prompt (const character_stat & stat_name)
Definition at line 1147 of file avatar.cpp.
 {
     const int free_points = free_upgrade_points();
     if( free_points <= 0 ) {
         const std::size_t lvl = spent_upgrade_points + free_points;
         if( lvl >= xp_cutoffs.size() ) {
             popup( _( "You've already reached maximum level." ) );
         } else {
             popup( _( "Needs %d more experience to gain next level." ), xp_cutoffs[lvl] - kill_xp );
         }
         return;
     }
     std::string stat_string;
     switch( stat ) {
         case character_stat::STRENGTH:
             stat_string = _( "strength" );
             break;
         case character_stat::DEXTERITY:
             stat_string = _( "dexterity" );
             break;
         case character_stat::INTELLIGENCE:
             stat_string = _( "intelligence" );
             break;
         case character_stat::PERCEPTION:
             stat_string = _( "perception" );
             break;
         case character_stat::DUMMY_STAT:
             stat_string = _( "invalid stat" );
             debugmsg( "Tried to use invalid stat" );
             break;
         default:
             return;
     }
     if( query_yn( _( "Are you sure you want to raise %s?  %d points available." ), stat_string,
                   free_points ) ) {
         switch( stat ) {
             case character_stat::STRENGTH:
                 str_max++;
                 spent_upgrade_points++;
                 recalc_hp();
                 break;
             case character_stat::DEXTERITY:
                 dex_max++;
                 spent_upgrade_points++;
                 break;
             case character_stat::INTELLIGENCE:
                 int_max++;
                 spent_upgrade_points++;
                 break;
             case character_stat::PERCEPTION:
                 per_max++;
                 spent_upgrade_points++;
                 break;
             case character_stat::DUMMY_STAT:
                 debugmsg( "Tried to use invalid stat" );
                 break;
         }
     }
 }
References _, debugmsg, Character::dex_max, DEXTERITY, DUMMY_STAT, free_upgrade_points(), Character::int_max, INTELLIGENCE, Character::kill_xp, Character::per_max, PERCEPTION, popup(), query_yn(), Character::recalc_hp(), Character::spent_upgrade_points, Character::str_max, STRENGTH, and xp_cutoffs.
Referenced by handle_player_display_action().
vomit()
void avatar::vomit ()
Handles player vomiting effects.
Definition at line 869 of file avatar.cpp.
 {
     if( stomach.contains() != 0_ml ) {
         // Remove all joy from previously eaten food and apply the penalty
         rem_morale( MORALE_FOOD_GOOD );
         rem_morale( MORALE_FOOD_HOT );
         // bears must suffer too
         rem_morale( MORALE_HONEY );
         // 1.5 times longer
         add_morale( MORALE_VOMITED, -2 * units::to_milliliter( stomach.contains() / 50 ), -40, 90_minutes,
                     45_minutes, false );
     } else {
         add_msg( m_warning, _( "You retched, but your stomach is empty." ) );
     }
     Character::vomit();
 }
References _, Character::add_morale(), add_msg(), stomach_contents::contains(), m_warning, MORALE_FOOD_GOOD, MORALE_FOOD_HOT, MORALE_HONEY, MORALE_VOMITED, Character::rem_morale(), Character::stomach, units::to_milliliter(), and Character::vomit().
wake_up()
void avatar::wake_up () override virtual
Removes "sleep" and "lying_down".
Reimplemented from Character.
Definition at line 832 of file avatar.cpp.
 {
     if( has_effect( effect_sleep ) ) {
         // alarm was set and player hasn't slept through the alarm.
         if( has_effect( effect_alarm_clock ) && !has_effect( effect_slept_through_alarm ) ) {
             add_msg( _( "It looks like you woke up before your alarm." ) );
             // effects will be removed in Character::wake_up.
         } else if( has_effect( effect_slept_through_alarm ) ) {
             if( has_flag( json_flag_ALARMCLOCK ) ) {
                 add_msg( m_warning, _( "It looks like you've slept through your internal alarm" ) );
             } else {
                 add_msg( m_warning, _( "It looks like you've slept through the alarm" ) );
             }
         }
     }
     Character::wake_up();
 }
References _, add_msg(), effect_alarm_clock, effect_sleep, effect_slept_through_alarm, Creature::has_effect(), Character::has_flag(), json_flag_ALARMCLOCK, m_warning, and Character::wake_up().
wield() [1/3]
bool avatar::wield (item & target) override virtual
Removes currently wielded item (if any) and replaces it with the target item.
Parameters
target replacement item to wield or null item to remove existing weapon without replacing it
Returns
whether both removal and replacement were successful (they are performed atomically)
Implements Character.
Definition at line 1390 of file avatar.cpp.
 {
     invalidate_inventory_validity_cache();
     invalidate_leak_level_cache();
     return wield( target,
                   item_handling_cost( target, true,
                                       is_worn( target ) ? INVENTORY_HANDLING_PENALTY / 2 :
                                       INVENTORY_HANDLING_PENALTY ) );
 }
References Character::invalidate_inventory_validity_cache(), Character::invalidate_leak_level_cache(), INVENTORY_HANDLING_PENALTY, Character::is_worn(), Character::item_handling_cost(), and wield().
wield() [2/3]
bool avatar::wield (item & target, int obtain_cost)
Definition at line 1400 of file avatar.cpp.
 {
     if( is_wielding( target ) ) {
         return true;
     }
     item_location weapon = get_wielded_item();
     if( weapon && weapon->has_item( target ) ) {
         add_msg( m_info, _( "You need to put the bag away before trying to wield something from it." ) );
         return false;
     }
     if( !can_wield( target ).success() ) {
         return false;
     }
     bool combine_stacks = weapon && target.can_combine( *weapon );
     if( !combine_stacks && !unwield() ) {
         return false;
     }
     cached_info.erase( "weapon_value" );
     if( target.is_null() ) {
         return true;
     }
     // Wielding from inventory is relatively slow and does not improve with increasing weapon skill.
     // Worn items (including guns with shoulder straps) are faster but still slower
     // than a skilled player with a holster.
     // There is an additional penalty when wielding items from the inventory whilst currently grabbed.
     bool worn = is_worn( target );
     const int mv = obtain_cost;
     if( worn ) {
         target.on_takeoff( *this );
     }
     add_msg_debug( debugmode::DF_AVATAR, "wielding took %d moves", mv );
     mod_moves( -mv );
     if( has_item( target ) ) {
         item removed = i_rem( &target );
         if( combine_stacks ) {
             weapon->combine( removed );
         } else {
             set_wielded_item( removed );
         }
     } else {
         if( combine_stacks ) {
             weapon->combine( target );
         } else {
             set_wielded_item( target );
         }
     }
     // set_wielded_item invalidates the weapon item_location, so get it again
     weapon = get_wielded_item();
     last_item = weapon->typeId();
     recoil = MAX_RECOIL;
     weapon->on_wield( *this );
     cata::event e = cata::event::make<event_type::character_wields_item>( getID(), last_item );
     get_event_bus().send_with_talker( this, &weapon, e );
     inv->update_invlet( *weapon );
     inv->update_cache_with_item( *weapon );
     return true;
 }
References _, add_msg(), add_msg_debug, Character::cached_info, item::can_combine(), Character::can_wield(), item::combine(), debugmode::DF_AVATAR, get_event_bus(), Character::get_wielded_item(), Character::getID(), visitable::has_item(), Character::i_rem(), Character::inv, item::is_null(), Character::is_wielding(), Character::is_worn(), Character::last_item, m_info, MAX_RECOIL, Creature::mod_moves(), item::on_takeoff(), item::on_wield(), Character::recoil, event_bus::send_with_talker(), Character::set_wielded_item(), item::typeId(), Character::unwield(), Character::weapon, and Character::worn.
wield() [3/3]
bool avatar::wield (item_location target)
Definition at line 1385 of file avatar.cpp.
 {
     return wield( *target, target.obtain_cost( *this ) );
 }
References item_location::obtain_cost().
Referenced by add_profession_items(), disarm(), avatar_action::plthrow(), spell_effect::spawn_ethereal_item(), wield(), and game::wield().
wield_contents()
bool avatar::wield_contents (item & container, item * internal_item = nullptr, bool penalties = true, int base_cost = INVENTORY_HANDLING_PENALTY)
Try to wield a contained item consuming moves proportional to weapon skill and volume.
Parameters
container Container containing the item to be wielded
internal_item reference to contained item to wield.
penalties Whether item volume and temporary effects (e.g. GRABBED, DOWNED) should be considered.
base_cost Cost due to storage type.
Definition at line 1902 of file avatar.cpp.
 {
     // if index not specified and container has multiple items then ask the player to choose one
     if( internal_item == nullptr ) {
         std::vector<std::string> opts;
         std::list<item *> container_contents = container.all_items_top();
         std::transform( container_contents.begin(), container_contents.end(),
         std::back_inserter( opts ), []( const item * elem ) {
             return elem->display_name();
         } );
         if( opts.size() > 1 ) {
             int pos = uilist( _( "Wield what?" ), opts );
             if( pos < 0 ) {
                 return false;
             }
             internal_item = *std::next( container_contents.begin(), pos );
         } else {
             internal_item = container_contents.front();
         }
     }
     return Character::wield_contents( container, internal_item, penalties, base_cost );
 }
References _, item::all_items_top(), Creature::pos(), and Character::wield_contents().
witness_thievery()
void avatar::witness_thievery (item *) inline override virtual
Implements Creature.
Definition at line 126 of file avatar.h.
 {}
Friends And Related Function Documentation
debug_menu::mission_debug
friend class debug_menu::mission_debug friend
Definition at line 394 of file avatar.h.
Member Data Documentation
a_diary
std::unique_ptr<diary> avatar::a_diary private
diary to track player progression and to write the players stroy
Definition at line 415 of file avatar.h.
Referenced by avatar(), and get_avatar_diary().
active_mission
mission* avatar::active_mission private
The currently active mission, or null if no mission is currently in progress.
Definition at line 411 of file avatar.h.
Referenced by avatar(), get_active_mission(), get_active_mission_target(), on_mission_finished(), remove_active_mission(), debug_menu::mission_debug::remove_mission(), reset_all_missions(), and set_active_mission().
active_missions
std::vector<mission *> avatar::active_missions private
Missions that the player has accepted and that are not finished (one way or the other).
Definition at line 399 of file avatar.h.
Referenced by debug_menu::mission_debug::edit_player(), get_active_missions(), has_mission_id(), on_mission_assignment(), on_mission_finished(), remove_active_mission(), debug_menu::mission_debug::remove_mission(), reset_all_missions(), and set_active_mission().
aim_cache
cata::mdarray<bool, point_bub_ms> avatar::aim_cache private
Definition at line 439 of file avatar.h.
Referenced by cant_see(), and rebuild_aim_cache().
aim_cache_dirty
bool avatar::aim_cache_dirty = true
Definition at line 381 of file avatar.h.
Referenced by cant_see(), Character::fire_gun(), rebuild_aim_cache(), target_ui::recalc_aim_turning_penalty(), and target_ui::set_last_target().
calorie_diary
std::list<daily_calories> avatar::calorie_diary private
The amount of calories spent and gained per day for the last 30 days.
the back is popped off and a new one added to the front at midnight each day
Definition at line 420 of file avatar.h.
Referenced by add_gained_calories(), add_ingested_kcal(), add_spent_calories(), advance_daily_calories(), avatar(), clear_nutrition(), get_daily_ingested_kcal(), get_daily_spent_kcal(), log_activity_level(), total_daily_calories_string(), and update_cardio_acc().
completed_missions
std::vector<mission *> avatar::completed_missions private
Missions that the player has successfully completed.
Definition at line 403 of file avatar.h.
Referenced by debug_menu::mission_debug::edit_player(), get_completed_missions(), on_mission_finished(), debug_menu::mission_debug::remove_mission(), and reset_all_missions().
dialogue_by_radio
bool avatar::dialogue_by_radio = false
Definition at line 281 of file avatar.h.
Referenced by talk_to().
failed_missions
std::vector<mission *> avatar::failed_missions private
Missions that have failed while being assigned to the player.
Definition at line 407 of file avatar.h.
Referenced by debug_menu::mission_debug::edit_player(), get_failed_missions(), on_mission_finished(), debug_menu::mission_debug::remove_mission(), and reset_all_missions().
follower_ids
std::set<character_id> avatar::follower_ids
Definition at line 379 of file avatar.h.
Referenced by game::add_npc_follower(), game::remove_npc_follower(), and game::validate_npc_followers().
grab_type
object_type avatar::grab_type private
Definition at line 428 of file avatar.h.
Referenced by avatar(), get_grab_type(), and grab().
items_identified
std::unordered_set<itype_id> avatar::items_identified private
Definition at line 423 of file avatar.h.
Referenced by add_profession_items(), clear_identified(), has_identified(), and identify().
last_pocket_noise
time_point avatar::last_pocket_noise = time_point(0)
Definition at line 375 of file avatar.h.
Referenced by game::walk_move().
mon_visible
monster_visible_info avatar::mon_visible private
Definition at line 430 of file avatar.h.
Referenced by get_mon_visible().
movecounter
int avatar::movecounter = 0
Definition at line 367 of file avatar.h.
Referenced by widget::get_var_value(), and game::handle_action().
player_map_memory
std::unique_ptr<map_memory> avatar::player_map_memory private
Definition at line 391 of file avatar.h.
Referenced by avatar(), get_memorized_tile(), is_map_memory_valid(), load_map_memory(), memorize_clear_decoration(), memorize_decoration(), memorize_symbol(), memorize_terrain(), prepare_map_memory_region(), and save_map_memory().
power_balance
units::energy avatar::power_balance = 0_kJ
Definition at line 372 of file avatar.h.
Referenced by widget::get_var_value().
power_prev_turn
units::energy avatar::power_prev_turn = 0_kJ
Definition at line 370 of file avatar.h.
preferred_aiming_mode
std::string avatar::preferred_aiming_mode
Definition at line 283 of file avatar.h.
Referenced by target_ui::action_switch_mode(), and target_ui::init_window_and_input().
save_id
std::string avatar::save_id private
Definition at line 389 of file avatar.h.
Referenced by get_save_id(), and set_save_id().
shadow_npc
std::unique_ptr<npc> avatar::shadow_npc private
The NPC that would control the avatar's character in the avatar's absence.
The Character data in this object is not relevant/used.
Definition at line 436 of file avatar.h.
Referenced by get_shadow_npc().
show_map_memory
bool avatar::show_map_memory private
Definition at line 392 of file avatar.h.
Referenced by avatar(), should_show_map_memory(), and toggle_map_memory().
snippets_read
std::set<snippet_id> avatar::snippets_read private
Definition at line 426 of file avatar.h.
Referenced by add_snippet(), get_snippets(), and has_seen_snippet().
starting_pets
std::vector<mtype_id> avatar::starting_pets
Definition at line 378 of file avatar.h.
Referenced by initialize(), and game::start_game().
starting_vehicle
vproto_id avatar::starting_vehicle = vproto_id::NULL_ID()
Definition at line 377 of file avatar.h.
Referenced by initialize(), and game::start_game().
translocators
teleporter_list avatar::translocators
Definition at line 266 of file avatar.h.
Referenced by spell_effect::translocate(), and iexamine::translocator().
The documentation for this class was generated from the following files:
src/avatar.h
src/advanced_inv_pane.cpp
src/avatar.cpp
src/bionics_ui.cpp
src/medical_ui.cpp
src/melee.cpp
src/mood_face.cpp
src/mutation_ui.cpp
src/newcharacter.cpp
src/npctalk.cpp
src/savegame_json.cpp