Cataclysm DDA: bikerack_racking_activity_actor Class Reference
bikerack_racking_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
bikerack_racking_activity_actor (const vehicle &parent_vehicle, const vehicle &racked_vehicle, const std::vector< int > &racks)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
bikerack_racking_activity_actor ()=default
Private Attributes
int moves_total = to_moves<int>(5_minutes)
tripoint_bub_ms parent_vehicle_pos
tripoint_bub_ms racked_vehicle_pos
std::vector< int > racks
Detailed Description
Definition at line 381 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
bikerack_racking_activity_actor() [1/2]
bikerack_racking_activity_actor::bikerack_racking_activity_actor () explicit private default
bikerack_racking_activity_actor() [2/2]
bikerack_racking_activity_actor::bikerack_racking_activity_actor (const vehicle & parent_vehicle, const vehicle & racked_vehicle, const std::vector< int > & racks) explicit
Definition at line 1491 of file activity_actor.cpp.
     : racks( racks )
 {
     parent_vehicle_pos = parent_vehicle.bub_part_pos( 0 );
     racked_vehicle_pos = racked_vehicle.bub_part_pos( 0 );
 }
References vehicle::bub_part_pos(), parent_vehicle_pos, and racked_vehicle_pos.
Member Function Documentation
clone()
std::unique_ptr<activity_actor> bikerack_racking_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 402 of file activity_actor_definitions.h.
{
             return std::make_unique<bikerack_racking_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > bikerack_racking_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 1543 of file activity_actor.cpp.
 {
     bikerack_racking_activity_actor actor;
     JsonObject data = jsin.get_object();
     data.read( "moves_total", actor.moves_total );
     data.read( "parent_vehicle_pos", actor.parent_vehicle_pos );
     data.read( "racked_vehicle_pos", actor.racked_vehicle_pos );
     data.read( "racks", actor.racks );
     return actor.clone();
 }
References clone(), JsonValue::get_object(), moves_total, parent_vehicle_pos, racked_vehicle_pos, racks, and JsonObject::read().
do_turn()
void bikerack_racking_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 399 of file activity_actor_definitions.h.
 {}
finish()
void bikerack_racking_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1505 of file activity_actor.cpp.
 {
     map &here = get_map();
     const optional_vpart_position ovp_parent = here.veh_at( parent_vehicle_pos );
     if( !ovp_parent ) {
         debugmsg( "racking actor lost parent vehicle at %s", parent_vehicle_pos.to_string() );
         act.set_to_null();
         return;
     }
     const optional_vpart_position ovp_racked = here.veh_at( racked_vehicle_pos );
     if( !ovp_racked ) {
         debugmsg( "racking actor lost racked vehicle at %s", racked_vehicle_pos.to_string() );
         act.set_to_null();
         return;
     }
     vehicle &parent_veh = ovp_parent->vehicle();
     vehicle &racked_veh = ovp_racked->vehicle();
     if( !parent_veh.merge_rackable_vehicle( &racked_veh, racks ) ) {
         debugmsg( "racking actor failed: failed racking %s on %s, racks: [%s].",
                   racked_veh.name, parent_veh.name, enumerate_ints_to_string( racks ) );
     }
     act.set_to_null();
 }
References act, debugmsg, enumerate_ints_to_string(), get_map(), vehicle::merge_rackable_vehicle(), vehicle::name, parent_vehicle_pos, racked_vehicle_pos, racks, coords::coord_point_base< Point >::to_string(), and map::veh_at().
get_type()
activity_id bikerack_racking_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 394 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_BIKERACK_RACKING" );
         }
References activity_id.
serialize()
void bikerack_racking_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 1533 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves_total", moves_total );
     jsout.member( "parent_vehicle_pos", parent_vehicle_pos );
     jsout.member( "racked_vehicle_pos", racked_vehicle_pos );
     jsout.member( "racks", racks );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves_total, parent_vehicle_pos, racked_vehicle_pos, racks, and JsonOut::start_object().
start()
void bikerack_racking_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1499 of file activity_actor.cpp.
 {
     act.moves_total = moves_total;
     act.moves_left = moves_total;
 }
References act, and moves_total.
Member Data Documentation
moves_total
int bikerack_racking_activity_actor::moves_total = to_moves<int>(5_minutes) private
Definition at line 384 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), and start().
parent_vehicle_pos
tripoint_bub_ms bikerack_racking_activity_actor::parent_vehicle_pos private
Definition at line 385 of file activity_actor_definitions.h.
Referenced by bikerack_racking_activity_actor(), deserialize(), finish(), and serialize().
racked_vehicle_pos
tripoint_bub_ms bikerack_racking_activity_actor::racked_vehicle_pos private
Definition at line 386 of file activity_actor_definitions.h.
Referenced by bikerack_racking_activity_actor(), deserialize(), finish(), and serialize().
racks
std::vector<int> bikerack_racking_activity_actor::racks private
Definition at line 387 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp