Cataclysm DDA: talker_monster Class Reference
talker_monster Class Reference
#include <talker_monster.h>
Public Member Functions
talker_monster (monster *new_me)
~talker_monster () override=default
monster * get_monster () override
const monster * get_monster () const override
Creature * get_creature () override
const Creature * get_creature () const override
void add_effect (const efftype_id &new_effect, const time_duration &dur, const std::string &bp, bool permanent, bool force, int intensity) override
void remove_effect (const efftype_id &old_effect, const std::string &bp) override
void mod_pain (int amount) override
void set_value (const std::string &var_name, const std::string &value) override
void remove_value (const std::string &var_name) override
void set_anger (int) override
void set_morale (int) override
void set_friendly (int) override
bool get_is_alive () const override
void die () override
void set_all_parts_hp_cur (int) const override
Public Member Functions inherited from talker_cloner< talker_monster, talker_monster_const >
std::unique_ptr< talker > clone () const override
Public Member Functions inherited from talker_monster_const
talker_monster_const (const monster *new_me)
~talker_monster_const () override=default
std::string disp_name () const override
std::string get_name () const override
int posx () const override
int posy () const override
int posz () const override
tripoint pos () const override
tripoint_abs_ms global_pos () const override
tripoint_abs_omt global_omt_location () const override
int pain_cur () const override
int perceived_pain_cur () const override
bool has_effect (const efftype_id &effect_id, const bodypart_id &bp) const override
effect get_effect (const efftype_id &effect_id, const bodypart_id &bp) const override
std::optional< std::string > maybe_get_value (const std::string &var_name) const override
bool has_flag (const flag_id &f) const override
bool has_species (const species_id &species) const override
bool bodytype (const bodytype_id &bt) const override
std::string short_description () const override
int get_anger () const override
int morale_cur () const override
int get_friendly () const override
int get_size () const override
int get_grab_strength () const override
bool will_talk_to_u (const Character &u, bool force) override
std::vector< std::string > get_topics (bool radio_contact) override
int get_cur_hp (const bodypart_id &) const override
int get_hp_max (const bodypart_id &) const override
double armor_at (damage_type_id &dt, bodypart_id &bp) const override
bool can_see_location (const tripoint &pos) const override
int get_volume () const override
int get_weight () const override
Public Member Functions inherited from talker_cloner< talker_monster_const >
std::unique_ptr< talker > clone () const override
Public Member Functions inherited from talker
virtual ~talker ()=default
virtual Character * get_character ()
virtual const Character * get_character () const
virtual npc * get_npc ()
virtual npc * get_npc () const
virtual item_location * get_item ()
virtual item_location * get_item () const
virtual computer * get_computer ()
virtual const computer * get_computer () const
virtual character_id getID () const
virtual bool is_male () const
virtual std::vector< std::string > get_grammatical_genders () const
virtual void set_pos (tripoint)
virtual std::string distance_to_goal () const
virtual void check_missions ()
virtual void update_missions (const std::vector< mission * > &)
virtual bool check_hostile_response (int) const
virtual int parse_mod (const std::string &, int) const
virtual int trial_chance_mod (const std::string &) const
virtual int get_count () const
virtual units::temperature get_cur_part_temp (const bodypart_id &) const
virtual int str_cur () const
virtual int dex_cur () const
virtual int int_cur () const
virtual int per_cur () const
virtual void set_str_max (int)
virtual void set_dex_max (int)
virtual void set_int_max (int)
virtual void set_per_max (int)
virtual void set_str_bonus (int)
virtual void set_dex_bonus (int)
virtual void set_int_bonus (int)
virtual void set_per_bonus (int)
virtual int get_str_max () const
virtual int get_dex_max () const
virtual int get_int_max () const
virtual int get_per_max () const
virtual int get_str_bonus () const
virtual int get_dex_bonus () const
virtual int get_int_bonus () const
virtual int get_per_bonus () const
virtual int get_skill_level (const skill_id &) const
virtual int get_skill_exp (const skill_id &, bool) const
virtual int get_spell_level (const trait_id &) const
virtual int get_spell_level (const spell_id &) const
virtual int get_spell_exp (const spell_id &) const
virtual int get_highest_spell_level () const
virtual int get_spell_count (const trait_id &) const
virtual int get_spell_sum (const trait_id &, int) const
virtual void set_spell_level (const spell_id &, int)
virtual void set_spell_exp (const spell_id &, int)
virtual void set_skill_level (const skill_id &, int)
virtual void set_skill_exp (const skill_id &, int, bool)
virtual bool has_trait (const trait_id &) const
virtual bool has_recipe (const recipe_id &) const
virtual void learn_recipe (const recipe_id &)
virtual void forget_recipe (const recipe_id &)
virtual void mutate (const int &, const bool &)
virtual void mutate_category (const mutation_category_id &, const bool &)
virtual void mutate_towards (const trait_id &, const mutation_category_id &, const bool &)
virtual void set_mutation (const trait_id &, const mutation_variant *=nullptr)
virtual void unset_mutation (const trait_id &)
virtual void activate_mutation (const trait_id &)
virtual void deactivate_mutation (const trait_id &)
virtual void set_sleepiness (int)
virtual bool crossed_threshold () const
virtual int num_bionics () const
virtual bool has_max_power () const
virtual bool has_bionic (const bionic_id &) const
virtual bool knows_spell (const spell_id &) const
virtual bool knows_proficiency (const proficiency_id &) const
virtual time_duration proficiency_practiced_time (const proficiency_id &) const
virtual void set_proficiency_practiced_time (const proficiency_id &, int)
virtual void train_proficiency_for (const proficiency_id &, int)
virtual std::vector< skill_id > skills_offered_to (const talker &) const
virtual std::vector< skill_id > skills_teacheable () const
virtual std::string skill_seminar_text (const skill_id &) const
virtual std::string skill_training_text (const talker &, const skill_id &) const
virtual std::vector< proficiency_id > proficiencies_teacheable () const
virtual std::vector< proficiency_id > proficiencies_offered_to (const talker &) const
virtual std::string proficiency_seminar_text (const proficiency_id &) const
virtual std::string proficiency_training_text (const talker &, const proficiency_id &) const
virtual std::vector< matype_id > styles_teacheable () const
virtual std::vector< matype_id > styles_offered_to (const talker &) const
virtual std::string style_seminar_text (const matype_id &) const
virtual std::string style_training_text (const talker &, const matype_id &) const
virtual std::vector< spell_id > spells_teacheable () const
virtual std::vector< spell_id > spells_offered_to (talker &) const
virtual std::string spell_seminar_text (const spell_id &) const
virtual std::string spell_training_text (talker &, const spell_id &) const
virtual void store_chosen_training (const skill_id &, const matype_id &, const spell_id &, const proficiency_id &)
virtual bool is_deaf () const
virtual bool can_see () const
virtual bool is_mute () const
virtual void add_bionic (const bionic_id &)
virtual void remove_bionic (const bionic_id &)
virtual std::string get_value (const std::string &key) const
virtual bool is_wearing (const itype_id &) const
virtual int charges_of (const itype_id &) const
virtual bool has_charges (const itype_id &, int) const
virtual bool has_charges (const itype_id &, int, bool) const
virtual std::list< item > use_charges (const itype_id &, int)
virtual std::list< item > use_charges (const itype_id &, int, bool)
virtual bool has_amount (const itype_id &, int) const
virtual int get_amount (const itype_id &) const
virtual std::list< item > use_amount (const itype_id &, int)
virtual int value (const item &) const
virtual int cash () const
virtual int debt () const
virtual void add_debt (int)
virtual int sold () const
virtual void add_sold (int)
virtual std::vector< item * > items_with (const std::function< bool(const item &)> &) const
virtual std::vector< const item * > const_items_with (const std::function< bool(const item &)> &) const
virtual void i_add (const item &)
virtual void i_add_or_drop (item &, bool=false)
virtual void remove_items_with (const std::function< bool(const item &)> &)
virtual bool unarmed_attack () const
virtual bool can_stash_weapon () const
virtual bool has_stolen_item (const talker &) const
virtual int cash_to_favor (int) const
virtual std::string give_item_to (bool)
virtual bool buy_from (int)
virtual bool buy_monster (talker &, const mtype_id &, int, int, bool, const translation &)
virtual std::vector< mission * > available_missions () const
virtual std::vector< mission * > assigned_missions () const
virtual mission * selected_mission () const
virtual void select_mission (mission *)
virtual void add_mission (const mission_type_id &)
virtual void set_companion_mission (const std::string &)
virtual faction * get_faction () const
virtual void set_fac (const faction_id &)
virtual void add_faction_rep (int)
virtual bool is_following () const
virtual bool is_friendly (const Character &) const
virtual bool is_player_ally () const
virtual bool turned_hostile () const
virtual bool is_enemy () const
virtual void make_angry ()
virtual bool has_ai_rule (const std::string &, const std::string &) const
virtual void toggle_ai_rule (const std::string &, const std::string &)
virtual void set_ai_rule (const std::string &, const std::string &)
virtual void clear_ai_rule (const std::string &, const std::string &)
virtual std::string get_job_description () const
virtual std::string evaluation_by (const talker &) const
virtual std::string view_personality_traits () const
virtual bool has_activity () const
virtual bool is_mounted () const
virtual bool is_myclass (const npc_class_id &) const
virtual void set_class (const npc_class_id &)
virtual int get_activity_level () const
virtual int get_sleepiness () const
virtual int get_hunger () const
virtual int get_thirst () const
virtual int get_instant_thirst () const
virtual int get_stored_kcal () const
virtual int get_healthy_kcal () const
virtual int get_stim () const
virtual int get_addiction_intensity (const addiction_id &) const
virtual int get_addiction_turns (const addiction_id &) const
virtual void set_addiction_turns (const addiction_id &, int)
virtual void set_stored_kcal (int)
virtual void set_stim (int)
virtual void set_thirst (int)
virtual bool is_in_control_of (const vehicle &) const
virtual void say (const std::string &)
virtual void shout (const std::string &="", bool=false)
virtual bool enslave_mind ()
virtual std::string opinion_text () const
virtual void add_opinion (const npc_opinion &)
virtual void set_first_topic (const std::string &)
virtual bool is_safe () const
virtual void set_pain (int)
virtual void attack_target (Creature &, bool, const matec_id &, bool, int)
virtual int attack_speed () const
virtual int coverage_at (bodypart_id &) const
virtual int encumbrance_at (bodypart_id &) const
virtual bool worn_with_flag (const flag_id &, const bodypart_id &) const
virtual bool wielded_with_flag (const flag_id &) const
virtual bool wielded_with_weapon_category (const weapon_category_id &) const
virtual bool has_item_with_flag (const flag_id &) const
virtual int item_rads (const flag_id &, aggregate_type) const
virtual units::energy power_cur () const
virtual units::energy power_max () const
virtual void set_power_cur (units::energy)
virtual int mana_cur () const
virtual int mana_max () const
virtual void set_mana_cur (int)
virtual void mod_daily_health (int, int)
virtual int focus_cur () const
virtual void mod_focus (int)
virtual int get_pkill () const
virtual void set_pkill (int)
virtual int get_stamina () const
virtual void set_stamina (int)
virtual int get_sleep_deprivation () const
virtual void set_sleep_deprivation (int)
virtual int get_rad () const
virtual void set_rad (int)
virtual void add_morale (const morale_type &, int, int, time_duration, time_duration, bool)
virtual void remove_morale (const morale_type &)
virtual void set_kill_xp (int)
virtual int get_kill_xp () const
virtual void set_age (int)
virtual int get_age () const
virtual void set_height (int)
virtual int get_height () const
virtual void set_npc_trust (int)
virtual int get_npc_trust () const
virtual void set_npc_fear (int)
virtual int get_npc_fear () const
virtual void set_npc_value (int)
virtual int get_npc_value () const
virtual void set_npc_anger (int)
virtual int get_npc_anger () const
virtual int get_bmi_permil () const
virtual const move_mode_id & get_move_mode () const
virtual int get_fine_detail_vision_mod () const
virtual int get_health () const
virtual units::temperature get_body_temp () const
virtual units::temperature_delta get_body_temp_delta () const
virtual std::vector< bodypart_id > get_all_body_parts (get_body_part_flags) const
virtual int get_part_hp_cur (const bodypart_id &) const
virtual int get_part_hp_max (const bodypart_id &) const
virtual void set_part_hp_cur (const bodypart_id &, int) const
virtual matec_id get_random_technique (Creature &, bool, bool, bool, const std::vector< matec_id > &={}) const
virtual void learn_martial_art (const matype_id &) const
virtual void forget_martial_art (const matype_id &) const
virtual bool knows_martial_art (const matype_id &) const
virtual bool using_martial_art (const matype_id &) const
virtual int climate_control_str_heat () const
virtual int climate_control_str_chill () const
Protected Member Functions
talker_monster ()=default
Protected Member Functions inherited from talker_monster_const
talker_monster_const ()=default
Protected Attributes
monster * me_mon
Protected Attributes inherited from talker_monster_const
const monster * me_mon_const
Detailed Description
Definition at line 78 of file talker_monster.h.
Constructor & Destructor Documentation
talker_monster() [1/2]
talker_monster::talker_monster (monster * new_me) explicit
Definition at line 15 of file talker_monster.cpp.
 {
     me_mon = new_me;
     me_mon_const = new_me;
 }
References me_mon, and talker_monster_const::me_mon_const.
~talker_monster()
talker_monster::~talker_monster () override default
talker_monster() [2/2]
talker_monster::talker_monster () protected default
Member Function Documentation
add_effect()
void talker_monster::add_effect (const efftype_id & new_effect, const time_duration & dur, const std::string & bp, bool permanent, bool force, int intensity) override virtual
Reimplemented from talker.
Definition at line 81 of file talker_monster.cpp.
 {
     me_mon->add_effect( new_effect, dur, bodypart_str_id( bp ), permanent, intensity, force );
 }
References Creature::add_effect(), bp, dur, force, intensity, me_mon, and permanent.
die()
void talker_monster::die () override virtual
Reimplemented from talker.
Definition at line 210 of file talker_monster.cpp.
 {
     me_mon->die( nullptr );
 }
References monster::die(), and me_mon.
get_creature() [1/2]
const Creature* talker_monster::get_creature () const inline override virtual
Reimplemented from talker.
Definition at line 94 of file talker_monster.h.
{
             return me_mon_const;
         }
References talker_monster_const::me_mon_const.
get_creature() [2/2]
Creature* talker_monster::get_creature () inline override virtual
Reimplemented from talker.
Definition at line 91 of file talker_monster.h.
{
             return me_mon;
         }
References me_mon.
get_is_alive()
bool talker_monster::get_is_alive () const override virtual
Reimplemented from talker.
Definition at line 205 of file talker_monster.cpp.
 {
     return !me_mon->is_dead();
 }
References monster::is_dead(), and me_mon.
get_monster() [1/2]
const monster* talker_monster::get_monster () const inline override virtual
Reimplemented from talker.
Definition at line 88 of file talker_monster.h.
{
             return me_mon_const;
         }
References talker_monster_const::me_mon_const.
get_monster() [2/2]
monster* talker_monster::get_monster () inline override virtual
Reimplemented from talker.
Definition at line 85 of file talker_monster.h.
{
             return me_mon;
         }
References me_mon.
mod_pain()
void talker_monster::mod_pain (int amount) override virtual
Reimplemented from talker.
Definition at line 99 of file talker_monster.cpp.
 {
     me_mon->mod_pain( amount );
 }
References me_mon, and Creature::mod_pain().
remove_effect()
void talker_monster::remove_effect (const efftype_id & old_effect, const std::string & bp) override virtual
Reimplemented from talker.
Definition at line 88 of file talker_monster.cpp.
 {
     bodypart_id target_part;
     if( "RANDOM" == bp ) {
         target_part = get_player_character().random_body_part( true );
     } else {
         target_part = bodypart_str_id( bp );
     }
     me_mon->remove_effect( old_effect, target_part );
 }
References bp, get_player_character(), me_mon, Creature::random_body_part(), and Creature::remove_effect().
remove_value()
void talker_monster::remove_value (const std::string & var_name) override virtual
Reimplemented from talker.
Definition at line 136 of file talker_monster.cpp.
 {
     me_mon->remove_value( var_name );
 }
References me_mon, and Creature::remove_value().
set_all_parts_hp_cur()
void talker_monster::set_all_parts_hp_cur (int set) const override virtual
Reimplemented from talker.
Definition at line 215 of file talker_monster.cpp.
 {
     me_mon->set_hp( set );
 }
References me_mon, and monster::set_hp().
set_anger()
void talker_monster::set_anger (int new_val) override virtual
Reimplemented from talker.
Definition at line 151 of file talker_monster.cpp.
 {
     me_mon->anger = new_val;
 }
References monster::anger, and me_mon.
set_friendly()
void talker_monster::set_friendly (int new_val) override virtual
Reimplemented from talker.
Definition at line 200 of file talker_monster.cpp.
 {
     me_mon->friendly = new_val;
 }
References monster::friendly, and me_mon.
set_morale()
void talker_monster::set_morale (int new_val) override virtual
Reimplemented from talker.
Definition at line 161 of file talker_monster.cpp.
 {
     me_mon->morale = new_val;
 }
References me_mon, and monster::morale.
set_value()
void talker_monster::set_value (const std::string & var_name, const std::string & value) override virtual
Reimplemented from talker.
Definition at line 131 of file talker_monster.cpp.
 {
     me_mon->set_value( var_name, value );
 }
References me_mon, Creature::set_value(), and talker::value().
Member Data Documentation
me_mon
monster* talker_monster::me_mon protected
Definition at line 117 of file talker_monster.h.
Referenced by add_effect(), die(), get_creature(), get_is_alive(), get_monster(), mod_pain(), remove_effect(), remove_value(), set_all_parts_hp_cur(), set_anger(), set_friendly(), set_morale(), set_value(), and talker_monster().
The documentation for this class was generated from the following files:
src/talker_monster.h
src/talker_monster.cpp