Cataclysm DDA: disable_activity_actor Class Reference
disable_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
disable_activity_actor ()=default
disable_activity_actor (const tripoint &target, int moves_total, bool reprogram)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
static bool can_disable_or_reprogram (const monster &monster)
Returns whether the given monster is a robot and can currently be disabled or reprogrammed.
static int get_disable_turns ()
Private Attributes
tripoint target
int moves_total
bool reprogram
Detailed Description
Definition at line 1937 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
disable_activity_actor() [1/2]
disable_activity_actor::disable_activity_actor () default
Referenced by deserialize().
disable_activity_actor() [2/2]
disable_activity_actor::disable_activity_actor (const tripoint & target, int moves_total, bool reprogram) inline
Definition at line 1941 of file activity_actor_definitions.h.
                                                  : target( target ), moves_total( moves_total ), reprogram( reprogram ) {}
Member Function Documentation
can_disable_or_reprogram()
bool disable_activity_actor::can_disable_or_reprogram (const monster & monster) static
Returns whether the given monster is a robot and can currently be disabled or reprogrammed.
Definition at line 4446 of file activity_actor.cpp.
 {
     if( get_avatar().get_knowledge_level( skill_electronics ) + get_avatar().get_knowledge_level(
             skill_mechanics ) <= 0 ) {
         return false;
     }
     return ( ( monster.friendly != 0 || monster.has_effect( effect_sensor_stun ) ) &&
              !monster.has_flag( mon_flag_RIDEABLE_MECH ) &&
              !( monster.has_flag( mon_flag_PAY_BOT ) && monster.has_effect( effect_paid ) ) ) &&
            ( !monster.type->revert_to_itype.is_empty() || monster.type->id == mon_manhack );
 }
References effect_paid, effect_sensor_stun, monster::friendly, get_avatar(), Creature::has_effect(), monster::has_flag(), mtype::id, string_id< T >::is_empty(), mon_flag_PAY_BOT, mon_flag_RIDEABLE_MECH, mon_manhack, mtype::revert_to_itype, skill_electronics, skill_mechanics, and monster::type.
Referenced by game::disable_robot(), and do_turn().
clone()
std::unique_ptr<activity_actor> disable_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1952 of file activity_actor_definitions.h.
{
             return std::make_unique<disable_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > disable_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 4476 of file activity_actor.cpp.
 {
     disable_activity_actor actor = disable_activity_actor();
     JsonObject data = jsin.get_object();
     data.read( "target", actor.target );
     data.read( "reprogram", actor.reprogram );
     data.read( "moves_total", actor.moves_total );
     return actor.clone();
 }
References clone(), disable_activity_actor(), JsonValue::get_object(), moves_total, JsonObject::read(), reprogram, and target.
do_turn()
void disable_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 4392 of file activity_actor.cpp.
 {
     monster *const mon_ptr = get_creature_tracker().creature_at<monster>( target );
     if( !mon_ptr ) {
         who.add_msg_if_player( _( "The robot has moved somewhere else." ) );
         who.cancel_activity();
         return;
     }
     monster &critter = *mon_ptr;
     if( !can_disable_or_reprogram( critter ) ) {
         // I think recovery from stunned is the only reason this could happen
         who.add_msg_if_player( _( "The %s recovers before you can finish." ), critter.name() );
         who.cancel_activity();
         return;
     }
     critter.add_effect( effect_worked_on, 1_turns );
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), can_disable_or_reprogram(), Character::cancel_activity(), creature_tracker::creature_at(), effect_worked_on, get_creature_tracker(), monster::name(), and target.
finish()
void disable_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 4412 of file activity_actor.cpp.
 {
     // Should never be null as we just checked in do_turn
     monster &critter = *get_creature_tracker().creature_at<monster>( target );
     if( reprogram ) {
         if( critter.has_effect( effect_docile ) ) {
             critter.remove_effect( effect_docile );
             if( one_in( 3 ) ) {
                 add_msg( _( "The %s hovers momentarily as it surveys the area." ),
                          critter.name() );
             }
         } else {
             critter.add_effect( effect_docile, 1_turns, true );
             if( one_in( 3 ) ) {
                 add_msg( _( "The %s lets out a whirring noise and starts to follow you." ),
                          critter.name() );
             }
         }
     } else {
         get_map().add_item_or_charges( target, critter.to_item() );
         if( !critter.has_flag( mon_flag_INTERIOR_AMMO ) ) {
             for( std::pair<const itype_id, int> &ammodef : critter.ammo ) {
                 if( ammodef.second > 0 ) {
                     get_map().spawn_item( target.xy(), ammodef.first, 1, ammodef.second, calendar::turn );
                 }
             }
         }
         g->remove_zombie( critter );
     }
     act.set_to_null();
 }
References _, act, Creature::add_effect(), map::add_item_or_charges(), add_msg(), monster::ammo, creature_tracker::creature_at(), effect_docile, g, get_creature_tracker(), get_map(), Creature::has_effect(), monster::has_flag(), mon_flag_INTERIOR_AMMO, monster::name(), one_in(), Creature::remove_effect(), reprogram, map::spawn_item(), target, monster::to_item(), calendar::turn, and tripoint::xy().
get_disable_turns()
int disable_activity_actor::get_disable_turns () static
Definition at line 4459 of file activity_actor.cpp.
 {
     const float elec_skill = get_avatar().get_skill_level( skill_electronics );
     const float mech_skill = get_avatar().get_skill_level( skill_mechanics );
     const float time_scale = std::max( elec_skill + mech_skill, 1.0f );
     return 2000 / time_scale;
 }
References get_avatar(), Character::get_skill_level(), max(), skill_electronics, and skill_mechanics.
Referenced by game::disable_robot().
get_type()
activity_id disable_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1944 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_DISABLE" );
         }
References activity_id.
serialize()
void disable_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 4467 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target", target );
     jsout.member( "reprogram", reprogram );
     jsout.member( "moves_total", moves_total );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves_total, reprogram, JsonOut::start_object(), and target.
start()
void disable_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 4384 of file activity_actor.cpp.
 {
     act.moves_total = moves_total;
     act.moves_left = moves_total;
     monster &critter = *get_creature_tracker().creature_at<monster>( target );
     critter.add_effect( effect_worked_on, 1_turns );
 }
References act, Creature::add_effect(), creature_tracker::creature_at(), effect_worked_on, get_creature_tracker(), moves_total, and target.
Member Data Documentation
moves_total
int disable_activity_actor::moves_total private
Definition at line 1966 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), and start().
reprogram
bool disable_activity_actor::reprogram private
Definition at line 1967 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
target
tripoint disable_activity_actor::target private
Definition at line 1965 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), finish(), serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp