Cataclysm DDA: gun_actor Class Reference
gun_actor Class Reference
#include <mattack_actors.h>
Public Member Functions
bool try_target (monster &z, Creature &target) const
void shoot (monster &z, const tripoint &target, const gun_mode_id &mode, int inital_recoil=0) const
int get_max_range () const
gun_actor ()
~gun_actor () override=default
void load_internal (const JsonObject &obj, const std::string &src) override
bool call (monster &) const override
std::unique_ptr< mattack_actor > clone () const override
Public Member Functions inherited from mattack_actor
mattack_actor (const mattack_id &new_id)
void load (const JsonObject &jo, const std::string &src)
virtual ~mattack_actor ()=default
Public Attributes
itype_id gun_type
itype_id ammo_type = itype_id::NULL_ID()
Specific ammo type to use or for gun default if unspecified.
std::map< skill_id, int > fake_skills
Balanced against player.
int fake_str = 16
int fake_dex = 8
int fake_int = 8
int fake_per = 12
std::map< std::pair< int, int >, gun_mode_id > ranges
Specify weapon mode to use at different engagement distances.
int max_ammo = INT_MAX
translation description
limited also by monster starting ammo
translation failure_msg
Message to display (if any) for failures to fire excluding lack of ammo.
translation no_ammo_sound
Sound (if any) when either ammo depleted or max_ammo reached.
int move_cost = 150
Number of moves required for each attack.
bool target_moving_vehicles = false
Should moving vehicles be targeted.
int targeting_cost = 100
Turrets may need to expend moves targeting before firing on certain targets.
bool require_targeting_player = true
Moves consumed before first attack can be made.
bool require_targeting_npc = false
By default always give player some warning.
bool require_targeting_monster = false
int targeting_timeout = 8
int targeting_timeout_extend = 3
Default turns after which targeting is lost and needs repeating.
translation targeting_sound
Increase timeout by this many turns after each shot.
int targeting_volume = 6
bool laser_lock = false
If set to zero don't emit any targeting sounds.
bool require_sunlight = false
Does switching between targets incur further targeting penalty.
Public Attributes inherited from mattack_actor
mattack_id id
bool was_loaded = false
int cooldown = 0
int attack_chance = 100
std::function< bool(dialogue &)> condition
bool has_condition = false
Additional Inherited Members
Protected Member Functions inherited from mattack_actor
mattack_actor ()=default
Detailed Description
Definition at line 205 of file mattack_actors.h.
Constructor & Destructor Documentation
gun_actor()
gun_actor::gun_actor ()
Definition at line 1023 of file mattack_actors.cpp.
                      : description( to_translation( "The %1$s fires its %2$s!" ) ),
     targeting_sound( to_translation( "beep-beep-beep!" ) )
 {
 }
~gun_actor()
gun_actor::~gun_actor () override default
Member Function Documentation
call()
bool gun_actor::call (monster & z) const override virtual
Implements mattack_actor.
Definition at line 1106 of file mattack_actors.cpp.
 {
     Creature *target;
     tripoint aim_at;
     bool untargeted = false;
     if( has_condition ) {
         dialogue d( get_talker_for( &z ), nullptr );
         if( !condition( d ) ) {
             add_msg_debug( debugmode::DF_MATTACK, "Attack conditionals failed" );
             return false;
         }
     }
     if( z.friendly ) {
         int max_range = get_max_range();
         int hostiles; // hostiles which cannot be engaged without risking friendly fire
         target = z.auto_find_hostile_target( max_range, hostiles );
         if( !target ) {
             if( hostiles > 0 ) {
                 add_msg_if_player_sees( z, m_warning,
                                         n_gettext( "Pointed in your direction, the %s emits an IFF warning beep.",
                                                    "Pointed in your direction, the %s emits %d annoyed sounding beeps.",
                                                    hostiles ),
                                         z.name(), hostiles );
             }
             return false;
         }
         aim_at = target->pos();
     } else {
         target = z.attack_target();
         aim_at = target ? target->pos() : tripoint_zero;
         if( !target || !z.sees( *target ) || ( !target->is_monster() && !z.aggro_character ) ) {
             if( !target_moving_vehicles ) {
                 return false;
             }
             untargeted = true; // no living targets, try to find moving car parts
             const std::set<tripoint_bub_ms> moving_veh_parts = get_map()
                     .get_moving_vehicle_targets( z, get_max_range() );
             if( moving_veh_parts.empty() ) {
                 return false;
             }
             aim_at = random_entry( moving_veh_parts, tripoint_bub_ms() ).raw();
         }
     }
     const int dist = rl_dist( z.pos(), aim_at );
     if( target ) {
         add_msg_debug( debugmode::DF_MATTACK, "Target %s at range %d", target->disp_name(), dist );
     } else {
         add_msg_debug( debugmode::DF_MATTACK, "Shooting at vehicle at range %d", dist );
     }
     for( const auto &e : ranges ) {
         if( dist >= e.first.first && dist <= e.first.second ) {
             if( untargeted || try_target( z, *target ) ) {
                 shoot( z, aim_at, e.second );
             }
             return true;
         }
     }
     return false;
 }
References add_msg_debug, add_msg_if_player_sees(), monster::aggro_character, monster::attack_target(), Creature::auto_find_hostile_target(), mattack_actor::condition, debugmode::DF_MATTACK, Creature::disp_name(), monster::friendly, get_map(), get_max_range(), map::get_moving_vehicle_targets(), get_talker_for(), mattack_actor::has_condition, Creature::is_monster(), m_warning, n_gettext, monster::name(), Creature::pos(), random_entry(), ranges, rl_dist(), Creature::sees(), shoot(), target_moving_vehicles, tripoint_zero, and try_target().
clone()
std::unique_ptr< mattack_actor > gun_actor::clone () const override virtual
Implements mattack_actor.
Definition at line 1090 of file mattack_actors.cpp.
 {
     return std::make_unique<gun_actor>( *this );
 }
get_max_range()
int gun_actor::get_max_range () const
Definition at line 1095 of file mattack_actors.cpp.
 {
     int max_range = 0;
     for( const auto &e : ranges ) {
         max_range = std::max( std::max( max_range, e.first.first ), e.first.second );
     }
     add_msg_debug( debugmode::DF_MATTACK, "Max range %d", max_range );
     return max_range;
 }
References add_msg_debug, debugmode::DF_MATTACK, max(), and ranges.
Referenced by call(), and mdefense::return_fire().
load_internal()
void gun_actor::load_internal (const JsonObject & obj, const std::string & src) override virtual
Implements mattack_actor.
Definition at line 1028 of file mattack_actors.cpp.
 {
     obj.read( "gun_type", gun_type, true );
     obj.read( "ammo_type", ammo_type );
     if( obj.has_array( "fake_skills" ) ) {
         for( JsonArray cur : obj.get_array( "fake_skills" ) ) {
             fake_skills[skill_id( cur.get_string( 0 ) )] = cur.get_int( 1 );
         }
     }
     optional( obj, was_loaded, "fake_str", fake_str, 8 );
     optional( obj, was_loaded, "fake_dex", fake_dex, 8 );
     optional( obj, was_loaded, "fake_int", fake_int, 8 );
     optional( obj, was_loaded, "fake_per", fake_per, 8 );
     for( JsonArray mode : obj.get_array( "ranges" ) ) {
         if( mode.size() < 2 || mode.get_int( 0 ) > mode.get_int( 1 ) ) {
             obj.throw_error_at( "ranges", "incomplete or invalid range specified" );
         }
         ranges.emplace( std::make_pair<int, int>( mode.get_int( 0 ), mode.get_int( 1 ) ),
                         gun_mode_id( mode.size() > 2 ? mode.get_string( 2 ) : "" ) );
     }
     if( obj.has_member( "condition" ) ) {
         read_condition( obj, "condition", condition, false );
         has_condition = true;
     }
     obj.read( "max_ammo", max_ammo );
     obj.read( "move_cost", move_cost );
     obj.read( "description", description );
     obj.read( "failure_msg", failure_msg );
     if( !obj.read( "no_ammo_sound", no_ammo_sound ) ) {
         no_ammo_sound = to_translation( "Click." );
     }
     obj.read( "targeting_cost", targeting_cost );
     obj.read( "require_targeting_player", require_targeting_player );
     obj.read( "require_targeting_npc", require_targeting_npc );
     obj.read( "require_targeting_monster", require_targeting_monster );
     obj.read( "targeting_timeout", targeting_timeout );
     obj.read( "targeting_timeout_extend", targeting_timeout_extend );
     if( !obj.read( "targeting_sound", targeting_sound ) ) {
         targeting_sound = to_translation( "Beep." );
     }
     obj.read( "targeting_volume", targeting_volume );
     laser_lock = obj.get_bool( "laser_lock", false );
     obj.read( "target_moving_vehicles", target_moving_vehicles );
     obj.read( "require_sunlight", require_sunlight );
 }
References ammo_type, mattack_actor::condition, description, failure_msg, fake_dex, fake_int, fake_per, fake_skills, fake_str, JsonObject::get_array(), JsonObject::get_bool(), gun_type, JsonObject::has_array(), mattack_actor::has_condition, JsonObject::has_member(), laser_lock, max_ammo, move_cost, no_ammo_sound, optional(), ranges, JsonObject::read(), read_condition(), require_sunlight, require_targeting_monster, require_targeting_npc, require_targeting_player, skill_id, target_moving_vehicles, targeting_cost, targeting_sound, targeting_timeout, targeting_timeout_extend, targeting_volume, JsonObject::throw_error_at(), to_translation(), and mattack_actor::was_loaded.
shoot()
void gun_actor::shoot (monster & z, const tripoint & target, const gun_mode_id & mode, int inital_recoil = 0) const
Definition at line 1219 of file mattack_actors.cpp.
 {
     z.mod_moves( -move_cost );
     itype_id mig_gun_type = item_controller->migrate_id( gun_type );
     item gun( mig_gun_type );
     gun.gun_set_mode( mode );
     itype_id ammo = item_controller->migrate_id( ammo_type );
     if( ammo.is_null() ) {
         if( gun.magazine_integral() ) {
             ammo = gun.ammo_default();
         } else {
             ammo = item( gun.magazine_default() ).ammo_default();
         }
     }
     if( !ammo.is_null() ) {
         if( gun.magazine_integral() ) {
             gun.ammo_set( ammo, z.ammo[ammo_type] );
         } else {
             item mag( gun.magazine_default() );
             mag.ammo_set( ammo, z.ammo[ammo_type] );
             gun.put_in( mag, pocket_type::MAGAZINE_WELL );
         }
     }
     if( z.has_effect( effect_stunned ) || z.has_effect( effect_psi_stunned ) ||
         z.has_effect( effect_sensor_stun ) ) {
         return;
     }
     add_msg_debug( debugmode::DF_MATTACK, "%d ammo (%s) remaining", z.ammo[ammo_type],
                    gun.ammo_sort_name() );
     if( !gun.ammo_sufficient( nullptr ) ) {
         if( !no_ammo_sound.empty() ) {
             sounds::sound( z.pos(), 10, sounds::sound_t::combat, no_ammo_sound );
         }
         return;
     }
     standard_npc tmp( _( "The " ) + z.name(), z.pos(), {}, 8,
                       fake_str, fake_dex, fake_int, fake_per );
     tmp.worn.wear_item( tmp, item( "backpack" ), false, false, true, true );
     tmp.set_fake( true );
     tmp.set_attitude( z.friendly ? NPCATT_FOLLOW : NPCATT_KILL );
     tmp.recoil = inital_recoil; // set initial recoil
     bool throwing = false;
     for( const auto &pr : fake_skills ) {
         tmp.set_skill_level( pr.first, pr.second );
         throwing |= pr.first == skill_throw;
     }
     tmp.set_wielded_item( gun );
     add_msg_if_player_sees( z, m_warning, description.translated(), z.name(),
                             tmp.get_wielded_item()->tname() );
     add_msg_debug( debugmode::DF_MATTACK,
                    "Temp NPC:\nSTR %d, DEX %d, INT %d, PER %d\nGun skill (%s) %d",
                    tmp.str_cur, tmp.dex_cur, tmp.int_cur, tmp.per_cur,
                    gun.gun_skill().c_str(), static_cast<int>( tmp.get_skill_level( throwing ? skill_throw :
                            skill_gun ) ) );
     if( throwing ) {
         tmp.throw_item( target, item( ammo, calendar::turn, 1 ) );
         z.ammo[ammo_type]--;
     } else {
         z.ammo[ammo_type] -= tmp.fire_gun( target, gun.gun_current_mode().qty );
     }
 }
References _, add_msg_debug, add_msg_if_player_sees(), monster::ammo, item::ammo_set(), ammo_type, sounds::combat, description, Character::dex_cur, debugmode::DF_MATTACK, effect_psi_stunned, effect_sensor_stun, effect_stunned, translation::empty(), fake_dex, fake_int, fake_per, fake_skills, fake_str, Character::fire_gun(), monster::friendly, Character::get_skill_level(), Character::get_wielded_item(), gun, gun_type, Creature::has_effect(), Character::int_cur, string_id< T >::is_null(), item, item_controller, m_warning, MAGAZINE_WELL, Creature::mod_moves(), move_cost, monster::name(), no_ammo_sound, NPCATT_FOLLOW, NPCATT_KILL, Character::per_cur, Creature::pos(), Character::recoil, npc::set_attitude(), Creature::set_fake(), Character::set_skill_level(), Character::set_wielded_item(), skill_gun, skill_throw, sounds::sound(), Character::str_cur, Character::throw_item(), item::tname(), translation::translated(), calendar::turn, outfit::wear_item(), and Character::worn.
Referenced by call(), and mdefense::return_fire().
try_target()
bool gun_actor::try_target (monster & z, Creature & target) const
Definition at line 1171 of file mattack_actors.cpp.
 {
     if( require_sunlight && !g->is_in_sunlight( z.pos() ) ) {
         add_msg_debug( debugmode::DF_MATTACK, "Requires sunlight" );
         if( one_in( 3 ) ) {
             add_msg_if_player_sees( z, failure_msg.translated(), z.name() );
         }
         return false;
     }
     const bool require_targeting = ( require_targeting_player && target.is_avatar() ) ||
                                    ( require_targeting_npc && target.is_npc() ) ||
                                    ( require_targeting_monster && target.is_monster() );
     const bool not_targeted = require_targeting && !z.has_effect( effect_targeted );
     const bool not_laser_locked = require_targeting && laser_lock &&
                                   !target.has_effect( effect_was_laserlocked );
     if( not_targeted || not_laser_locked ) {
         if( targeting_volume > 0 && !targeting_sound.empty() ) {
             sounds::sound( z.pos(), targeting_volume, sounds::sound_t::alarm,
                            targeting_sound );
         }
         if( not_targeted ) {
             add_msg_debug( debugmode::DF_MATTACK, "%s targeted", target.disp_name() );
             z.add_effect( effect_targeted, time_duration::from_turns( targeting_timeout ) );
         }
         if( not_laser_locked ) {
             add_msg_debug( debugmode::DF_MATTACK, "%s laser-locked", target.disp_name() );
             target.add_effect( effect_laserlocked, time_duration::from_turns( targeting_timeout ) );
             target.add_effect( effect_was_laserlocked, time_duration::from_turns( targeting_timeout ) );
             target.add_msg_if_player( m_warning,
                                       _( "You're not sure why you've got a laser dot on you" ) );
         }
         z.mod_moves( -targeting_cost );
         return false;
     }
     if( require_targeting ) {
         z.add_effect( effect_targeted, time_duration::from_turns( targeting_timeout_extend ) );
     }
     if( laser_lock ) {
         // To prevent spamming laser locks when the player can tank that stuff somehow
         target.add_effect( effect_was_laserlocked, 5_turns );
     }
     return true;
 }
References _, Creature::add_effect(), add_msg_debug, Creature::add_msg_if_player(), add_msg_if_player_sees(), sounds::alarm, debugmode::DF_MATTACK, Creature::disp_name(), effect_laserlocked, effect_targeted, effect_was_laserlocked, translation::empty(), failure_msg, time_duration::from_turns(), g, Creature::has_effect(), Creature::is_avatar(), Creature::is_monster(), Creature::is_npc(), laser_lock, m_warning, Creature::mod_moves(), monster::name(), one_in(), Creature::pos(), require_sunlight, require_targeting_monster, require_targeting_npc, require_targeting_player, sounds::sound(), targeting_cost, targeting_sound, targeting_timeout, targeting_timeout_extend, targeting_volume, and translation::translated().
Referenced by call().
Member Data Documentation
ammo_type
itype_id gun_actor::ammo_type = itype_id::NULL_ID()
Specific ammo type to use or for gun default if unspecified.
Definition at line 212 of file mattack_actors.h.
Referenced by load_internal(), and shoot().
description
translation gun_actor::description
limited also by monster starting ammo
Description of the attack being run
Definition at line 229 of file mattack_actors.h.
Referenced by load_internal(), and shoot().
failure_msg
translation gun_actor::failure_msg
Message to display (if any) for failures to fire excluding lack of ammo.
Definition at line 232 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
fake_dex
int gun_actor::fake_dex = 8
Definition at line 218 of file mattack_actors.h.
Referenced by load_internal(), and shoot().
fake_int
int gun_actor::fake_int = 8
Definition at line 219 of file mattack_actors.h.
Referenced by load_internal(), and shoot().
fake_per
int gun_actor::fake_per = 12
Definition at line 220 of file mattack_actors.h.
Referenced by load_internal(), and shoot().
fake_skills
std::map<skill_id, int> gun_actor::fake_skills
Balanced against player.
If fake_skills unspecified defaults to GUN 4, WEAPON 8
Definition at line 216 of file mattack_actors.h.
Referenced by load_internal(), and shoot().
fake_str
int gun_actor::fake_str = 16
Definition at line 217 of file mattack_actors.h.
Referenced by load_internal(), and shoot().
gun_type
itype_id gun_actor::gun_type
Definition at line 209 of file mattack_actors.h.
Referenced by mdeath::broken(), load_internal(), and shoot().
laser_lock
bool gun_actor::laser_lock = false
If set to zero don't emit any targeting sounds.
Definition at line 257 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
max_ammo
int gun_actor::max_ammo = INT_MAX
Definition at line 226 of file mattack_actors.h.
Referenced by load_internal().
move_cost
int gun_actor::move_cost = 150
Number of moves required for each attack.
Definition at line 238 of file mattack_actors.h.
Referenced by load_internal(), and shoot().
no_ammo_sound
translation gun_actor::no_ammo_sound
Sound (if any) when either ammo depleted or max_ammo reached.
Definition at line 235 of file mattack_actors.h.
Referenced by load_internal(), and shoot().
ranges
std::map<std::pair<int, int>, gun_mode_id> gun_actor::ranges
Specify weapon mode to use at different engagement distances.
Definition at line 224 of file mattack_actors.h.
Referenced by call(), get_max_range(), and load_internal().
require_sunlight
bool gun_actor::require_sunlight = false
Does switching between targets incur further targeting penalty.
If true then disable this attack completely if not brightly lit
Definition at line 261 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
require_targeting_monster
bool gun_actor::require_targeting_monster = false
Definition at line 249 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
require_targeting_npc
bool gun_actor::require_targeting_npc = false
By default always give player some warning.
Definition at line 248 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
require_targeting_player
bool gun_actor::require_targeting_player = true
Moves consumed before first attack can be made.
Definition at line 247 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
target_moving_vehicles
bool gun_actor::target_moving_vehicles = false
Should moving vehicles be targeted.
Definition at line 241 of file mattack_actors.h.
Referenced by call(), and load_internal().
targeting_cost
int gun_actor::targeting_cost = 100
Turrets may need to expend moves targeting before firing on certain targets.
Definition at line 245 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
targeting_sound
translation gun_actor::targeting_sound
Increase timeout by this many turns after each shot.
Definition at line 254 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
targeting_timeout
int gun_actor::targeting_timeout = 8
Definition at line 251 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
targeting_timeout_extend
int gun_actor::targeting_timeout_extend = 3
Default turns after which targeting is lost and needs repeating.
Definition at line 252 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
targeting_volume
int gun_actor::targeting_volume = 6
Definition at line 255 of file mattack_actors.h.
Referenced by load_internal(), and try_target().
The documentation for this class was generated from the following files:
src/mattack_actors.h
src/mattack_actors.cpp