Cataclysm DDA: inventory_drop_selector Class Reference
inventory_drop_selector Class Reference
#include <inventory_ui.h>
Public Member Functions
inventory_drop_selector (Character &p, const inventory_selector_preset &preset=default_preset, const std::string &selection_column_title=_("ITEMS TO DROP"), bool warn_liquid=true)
drop_locations execute ()
Public Member Functions inherited from inventory_multiselector
inventory_multiselector (Character &p, const inventory_selector_preset &preset=default_preset, const std::string &selection_column_title="", const GetStats &={}, bool allow_select_contained=false)
drop_locations execute (bool allow_empty=false)
void toggle_entry (inventory_entry &entry, size_t count)
Public Member Functions inherited from inventory_selector
inventory_selector (Character &u, const inventory_selector_preset &preset=default_preset)
virtual ~inventory_selector ()
bool add_contained_items (item_location &container)
These functions add items from map / vehicles.
bool add_contained_items (item_location &container, inventory_column &column, const item_category *custom_category=nullptr, item_location const &topmost_parent={}, int indent=0)
void add_contained_gunmods (Character &you, item &gun)
void add_contained_ebooks (item_location &container)
void add_character_items (Character &character)
void add_map_items (const tripoint &target)
void add_vehicle_items (const tripoint &target)
void add_nearby_items (int radius=1)
void add_remote_map_items (tinymap *remote_map, const tripoint &target)
void add_basecamp_items (const basecamp &camp)
void clear_items ()
Remove all items.
void set_title (const std::string &title)
Assigns a title that will be shown on top of the menu.
void set_hint (const std::string &hint)
Assigns a hint.
void set_display_stats (bool display_stats)
Specify whether the header should show stats (weight and volume).
bool empty () const
bool has_available_choices () const
uint64_t item_entry_count () const
drop_location get_only_choice () const
void set_filter (const std::string &str)
Apply filter string to all columns.
std::string get_filter () const
Get last filter string set by set_filter or entered by player.
void set_invlet_type (selector_invlet_type type)
Set the letter group to use for automatic inventory letters.
selector_invlet_type invlet_type ()
void show_invlet (bool show)
Set whether to show inventory letters.
bool showing_invlet () const
void categorize_map_items (bool toggle)
bool highlight (const item_location &loc, bool hidden=false, bool front_only=false)
Highlight a location.
const inventory_entry & get_highlighted () const
item_location get_collation_next () const
void highlight_position (std::pair< size_t, size_t > position)
bool highlight_one_of (const std::vector< item_location > &locations, bool hidden=false)
std::pair< size_t, size_t > get_highlighted_position () const
inventory_column & get_column (size_t index) const
inventory_column & get_active_column () const
void toggle_categorize_contained ()
void set_active_column (size_t index)
void toggle_skip_unselectable ()
std::string action_bound_to_key (char key) const
Protected Member Functions
stats get_raw_stats () const override
Get stats to display in top right.
Protected Member Functions inherited from inventory_multiselector
void rearrange_columns (size_t client_width) override
Tackles screen overflow.
void set_chosen_count (inventory_entry &entry, size_t count)
void deselect_contained_items ()
void toggle_entries (int &count, toggle_mode mode=toggle_mode::SELECTED)
virtual void on_toggle ()
void on_input (const inventory_input &input)
void toggle_categorize_contained ()
Protected Member Functions inherited from inventory_selector
const item_category * naturalize_category (const item_category &category, const tripoint &pos)
inventory_entry * add_entry (inventory_column &target_column, std::vector< item_location > &&locations, const item_category *custom_category=nullptr, size_t chosen_count=0, item_location const &topmost_parent={}, bool chevron=false)
bool add_entry_rec (inventory_column &entry_column, inventory_column &children_column, item_location &loc, item_category const *entry_category=nullptr, item_category const *children_category=nullptr, item_location const &topmost_parent={}, int indent=0)
bool drag_drop_item (item *sourceItem, item *destItem)
inventory_input get_input ()
inventory_input process_input (const std::string &action, int ch)
void on_input (const inventory_input &input)
Given an action from the input_context, try to act according to it.
void on_change (const inventory_entry &entry)
Entry has been changed.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
size_t get_layout_width () const
size_t get_layout_height () const
std::pair< bool, std::string > query_string (const std::string &val, bool end_with_toggle=false)
Query user for a string and return it.
void query_set_filter ()
Query the user for a filter and apply it.
int query_count (char init=0, bool end_with_toggle=false)
Query the user for count and return it.
std::vector< std::string > get_stats () const
std::pair< std::string, nc_color > get_footer (navigation_mode m) const
size_t get_header_height () const
size_t get_header_min_width () const
size_t get_footer_min_width () const
inventory_entry * find_entry_by_invlet (int invlet) const
inventory_entry * find_entry_by_coordinate (const point &coordinate) const
inventory_entry * find_entry_by_location (item_location &loc) const
const std::vector< inventory_column * > & get_all_columns () const
std::vector< inventory_column * > get_visible_columns () const
void highlight ()
Highlight parent and contents of highlighted item.
void action_examine (const item_location &sitem)
Show detailed item information for the selected item.
virtual void reassign_custom_invlets ()
size_t get_columns_width (const std::vector< inventory_column * > &columns) const
double get_columns_occupancy_ratio (size_t client_width) const
bool are_columns_centered (size_t client_width) const
bool is_overflown (size_t client_width) const
bool is_active_column (const inventory_column &column) const
void append_column (inventory_column &column)
void toggle_active_column (scroll_direction dir)
Activates either previous or next column.
void refresh_active_column ()
void toggle_navigation_mode ()
const navigation_mode_data & get_navigation_data (navigation_mode m) const
Private Attributes
bool warn_liquid
Additional Inherited Members
Public Types inherited from inventory_multiselector
using GetStats = std::function< stats(const std::vector< std::pair< item_location, int > >)>
Public Types inherited from inventory_selector
enum selector_invlet_type { SELECTOR_INVLET_DEFAULT , SELECTOR_INVLET_NUMERIC , SELECTOR_INVLET_ALPHA }
enum class uimode : int { categories = 0 , hierarchy , last }
using stat = std::array< std::string, 4 >
using stats = std::array< stat, 3 >
Static Protected Member Functions inherited from inventory_selector
static stat get_weight_and_length_stat (units::mass weight_carried, units::mass weight_capacity, const units::length &longest_length)
static stat get_volume_stat (const units::volume &volume_carried, const units::volume &volume_capacity, const units::volume &largest_free_volume)
static stat get_holster_stat (const units::volume &holster_volume, int used_holsters, int total_holsters)
static stats get_weight_and_volume_and_holster_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume &volume_carried, const units::volume &volume_capacity, const units::length &longest_length, const units::volume &largest_free_volume, const units::volume &holster_volume, int used_holsters, int total_holsters)
Protected Attributes inherited from inventory_multiselector
size_t max_chosen_count
std::vector< std::pair< item_location, int > > to_use
std::vector< item_location > usable_locs
bool allow_select_contained
int count = 0
Protected Attributes inherited from inventory_selector
Character & u
const inventory_selector_preset & preset
input_context ctxt
The input context for navigation, already contains some actions for movement.
std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * > > rect_entry_map
std::vector< inventory_column * > columns
point _fixed_origin { -1, -1 }
point _fixed_size { -1, -1 }
bool _categorize_map_items = false
bool force_single_column = false
Detailed Description
Definition at line 1016 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_drop_selector()
inventory_drop_selector::inventory_drop_selector (Character & p, const inventory_selector_preset & preset = default_preset, const std::string & selection_column_title = _("ITEMS TO DROP"), bool warn_liquid = true) explicit
Definition at line 3818 of file inventory_ui.cpp.
                                  :
     inventory_multiselector( p, preset, selection_column_title ),
     warn_liquid( warn_liquid )
 {
 #if defined(__ANDROID__)
     // allow user to type a drop number without dismissing virtual keyboard after each keypress
     ctxt.allow_text_entry = true;
 #endif
 }
References inventory_selector::ctxt.
Member Function Documentation
execute()
drop_locations inventory_drop_selector::execute ()
Definition at line 3992 of file inventory_ui.cpp.
 {
     shared_ptr_fast<ui_adaptor> ui = create_or_get_ui_adaptor();
     debug_print_timer( tp_start );
     while( true ) {
         ui_manager::redraw();
         const inventory_input input = get_input();
         if( input.action == "CONFIRM" ) {
             if( to_use.empty() ) {
                 popup_getkey( _( "No items were selected.  Use %s to select them." ),
                               ctxt.get_desc( "TOGGLE_ENTRY" ) );
                 continue;
             }
             break;
         }
         if( input.action == "QUIT" ) {
             return drop_locations();
         }
         on_input( input );
     }
     drop_locations dropped_pos_and_qty;
     enum class drop_liquid {
         ask, no, yes
     } should_drop_liquid = drop_liquid::ask;
     for( const std::pair<item_location, int> &drop_pair : to_use ) {
         bool should_drop = true;
         if( drop_pair.first->made_of_from_type( phase_id::LIQUID ) &&
             !drop_pair.first->is_frozen_liquid() ) {
             if( should_drop_liquid == drop_liquid::ask ) {
                 if( !warn_liquid || query_yn(
                         _( "You are dropping liquid from its container.  You might not be able to pick it back up.  Really do so?" ) ) ) {
                     should_drop_liquid = drop_liquid::yes;
                 } else {
                     should_drop_liquid = drop_liquid::no;
                 }
             }
             if( should_drop_liquid == drop_liquid::no ) {
                 should_drop = false;
             }
         }
         if( should_drop ) {
             dropped_pos_and_qty.push_back( drop_pair );
         }
     }
     return dropped_pos_and_qty;
 }
References _, inventory_input::action, inventory_selector::create_or_get_ui_adaptor(), inventory_selector::ctxt, anonymous_namespace{inventory_ui.cpp}::debug_print_timer(), input_context::get_desc(), inventory_selector::get_input(), LIQUID, no, inventory_multiselector::on_input(), popup_getkey(), query_yn(), ui_manager::redraw(), inventory_multiselector::to_use, anonymous_namespace{inventory_ui.cpp}::tp_start, warn_liquid, and yes.
Referenced by game_menus::inv::holster(), and game_menus::inv::unload_container().
get_raw_stats()
inventory_selector::stats inventory_drop_selector::get_raw_stats () const override protected virtual
Get stats to display in top right.
By default, computes volume/weight numbers for u
Reimplemented from inventory_multiselector.
Reimplemented in inventory_insert_selector.
Definition at line 4046 of file inventory_ui.cpp.
 {
     return get_weight_and_volume_and_holster_stats(
                u.weight_carried_with_tweaks( to_use ),
                u.weight_capacity(),
                u.volume_carried_with_tweaks( to_use ),
                u.volume_capacity_with_tweaks( to_use ),
                u.max_single_item_length(), u.max_single_item_volume(),
                u.free_holster_volume(), u.used_holsters(), u.total_holsters() );
 }
References Character::free_holster_volume(), inventory_selector::get_weight_and_volume_and_holster_stats(), Character::max_single_item_length(), Character::max_single_item_volume(), inventory_multiselector::to_use, Character::total_holsters(), inventory_selector::u, Character::used_holsters(), Character::volume_capacity_with_tweaks(), Character::volume_carried_with_tweaks(), Character::weight_capacity(), and Character::weight_carried_with_tweaks().
Member Data Documentation
warn_liquid
bool inventory_drop_selector::warn_liquid private
Definition at line 1029 of file inventory_ui.h.
Referenced by execute().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp