Cataclysm DDA: vehicle_part_with_feature_range< feature_type > Class Template Reference
vehicle_part_with_feature_range< feature_type > Class Template Reference
A range that contains parts that have a given feature and (optionally) are not broken.
#include <vpart_range.h>
Public Member Functions
vehicle_part_with_feature_range (::vehicle &v, feature_type f, part_status_flag r)
bool matches (size_t part) const
bool matches (const size_t part) const
bool matches (const size_t part) const
Public Member Functions inherited from generic_vehicle_part_range< vehicle_part_with_feature_range< feature_type > >
generic_vehicle_part_range (::vehicle &v, bool with_fake=false)
size_t part_count () const
iterator begin () const
iterator end () const
::vehicle & vehicle () const
Private Attributes
feature_type feature_
part_status_flag required_
Additional Inherited Members
Public Types inherited from generic_vehicle_part_range< vehicle_part_with_feature_range< feature_type > >
using iterator = vehicle_part_iterator< vehicle_part_with_feature_range< feature_type > >
Detailed Description
template<typename feature_type>
class vehicle_part_with_feature_range< feature_type >
A range that contains parts that have a given feature and (optionally) are not broken.
Definition at line 173 of file vpart_range.h.
Constructor & Destructor Documentation
vehicle_part_with_feature_range()
template<typename feature_type > vehicle_part_with_feature_range< feature_type >::vehicle_part_with_feature_range (::vehicle & v, feature_type f, part_status_flag r) inline
Definition at line 181 of file vpart_range.h.
                                                                                           :
             generic_vehicle_part_range<vehicle_part_with_feature_range<feature_type>>( v ),
                     feature_( std::move( f ) ), required_( r ) { }
Member Function Documentation
matches() [1/3]
bool vehicle_part_with_feature_range< std::string >::matches (const size_t part) const
Definition at line 8328 of file vehicle.cpp.
 {
     const vehicle_part &vp = this->vehicle().part( part );
     return !vp.removed && !vp.is_fake && vp.info().has_flag( feature_ ) &&
            ( !( part_status_flag::working & required_ ) || !vp.is_broken() ) &&
            ( !( part_status_flag::available & required_ ) || vp.is_available() ) &&
            ( !( part_status_flag::enabled & required_ ) || vp.enabled );
 }
References available, enabled, vehicle_part::enabled, vpart_info::has_flag(), vehicle_part::info(), vehicle_part::is_available(), vehicle_part::is_broken(), vehicle_part::is_fake, vehicle::part(), vehicle_part::removed, and working.
matches() [2/3]
bool vehicle_part_with_feature_range< vpart_bitflags >::matches (const size_t part) const
Definition at line 8338 of file vehicle.cpp.
 {
     const vehicle_part &vp = this->vehicle().part( part );
     return !vp.removed && !vp.is_fake && vp.info().has_flag( feature_ ) &&
            ( !( part_status_flag::working & required_ ) || !vp.is_broken() ) &&
            ( !( part_status_flag::available & required_ ) || vp.is_available() ) &&
            ( !( part_status_flag::enabled & required_ ) || vp.enabled );
 }
References available, enabled, vehicle_part::enabled, vpart_info::has_flag(), vehicle_part::info(), vehicle_part::is_available(), vehicle_part::is_broken(), vehicle_part::is_fake, vehicle::part(), vehicle_part::removed, and working.
matches() [3/3]
template<typename feature_type > bool vehicle_part_with_feature_range< feature_type >::matches (size_t part) const
Member Data Documentation
feature_
template<typename feature_type > feature_type vehicle_part_with_feature_range< feature_type >::feature_ private
Definition at line 177 of file vpart_range.h.
required_
template<typename feature_type > part_status_flag vehicle_part_with_feature_range< feature_type >::required_ private
Definition at line 178 of file vpart_range.h.
The documentation for this class was generated from the following files:
src/vehicle.h
src/vpart_range.h