Cataclysm DDA: keybindings_ui Class Reference
keybindings_ui Class Reference
Public Member Functions
keybindings_ui (bool permit_execute_action, input_context *parent)
void init ()
Public Member Functions inherited from cataimgui::window
window (const std::string &id_, int window_flags=0)
virtual ~window ()
void draw_colored_text (std::string const &text, const nc_color &color, float wrap_width=0.0F, bool *is_selected=nullptr, bool *is_focused=nullptr, bool *is_hovered=nullptr)
void draw_colored_text (std::string const &text, nc_color &color, float wrap_width=0.0F, bool *is_selected=nullptr, bool *is_focused=nullptr, bool *is_hovered=nullptr)
bool action_button (const std::string &action, const std::string &text)
A button tied to a string action.
bool has_button_action ()
std::string get_button_action ()
void draw_header (std::string const &text)
bool get_is_open () const
virtual void draw ()
bool is_bounds_changed ()
size_t get_text_width (const std::string &text)
size_t get_text_height (const char *text)
size_t str_width_to_pixels (size_t len)
size_t str_height_to_pixels (size_t len)
std::string get_filter ()
void clear_filter ()
void mark_resized ()
Public Attributes
kb_menu_status status = kb_menu_status::show
kb_menu_status last_status = kb_menu_status::execute
std::vector< std::string > legend
std::vector< std::pair< std::string, std::string > > buttons
int width = 0
std::vector< std::string > filtered_registered_actions
std::string hotkeys
int highlight_row_index = -1
size_t scroll_offset = 0
Protected Member Functions
cataimgui::bounds get_bounds () override
void draw_controls () override
void on_resized () override
Protected Member Functions inherited from cataimgui::window
window (int window_flags=0)
void draw_filter (const input_context &ctxt, bool filtering_active)
Private Attributes
const nc_color global_key = c_light_gray
const nc_color h_global_key = h_light_gray
const nc_color local_key = c_light_green
const nc_color h_local_key = h_light_green
const nc_color unbound_key = c_light_red
const nc_color h_unbound_key = h_light_red
input_context * ctxt
Additional Inherited Members
Protected Attributes inherited from cataimgui::window
bool force_to_back = false
bool is_open
std::string id
int window_flags
std::string button_action
Detailed Description
Definition at line 41 of file input_context.cpp.
Constructor & Destructor Documentation
keybindings_ui()
keybindings_ui::keybindings_ui (bool permit_execute_action, input_context * parent)
Definition at line 642 of file input_context.cpp.
                                                         : cataimgui::window( "KEYBINDINGS", ImGuiWindowFlags_NoNav )
 {
     this->ctxt = parent;
     legend.push_back( colorize( _( "Unbound keys" ), unbound_key ) );
     legend.push_back( colorize( _( "Keybinding active only on this screen" ), local_key ) );
     legend.push_back( colorize( _( "Keybinding active globally" ), global_key ) );
     legend.push_back( colorize( _( "* User customized" ), global_key ) );
     if( permit_execute_action ) {
         legend.push_back( string_format(
                               _( "Press %c to execute action\n" ),
                               fallback_keys.at( fallback_action::execute ) ) );
     }
     buttons.assign( {
         {
             "REMOVE", string_format( _( "[<color_yellow>%c</color>] Remove keybinding" ),
                                      fallback_keys.at( fallback_action::remove ) )
         },
         {
             "ADD_LOCAL", string_format( _( "[<color_yellow>%c</color>] Add local keybinding" ),
                                         fallback_keys.at( fallback_action::add_local ) )
         },
         {
             "ADD_GLOBAL", string_format( _( "[<color_yellow>%c</color>] Add global keybinding" ),
                                          fallback_keys.at( fallback_action::add_global ) )
         },
         {
             "RESET", string_format( _( "[<color_yellow>%c</color>] Reset keybinding" ),
                                     fallback_keys.at( fallback_action::reset ) )
         } } );
 }
References _, buttons, colorize(), ctxt, fallback_keys, global_key, legend, local_key, string_format(), and unbound_key.
Member Function Documentation
draw_controls()
void keybindings_ui::draw_controls () override protected virtual
Implements cataimgui::window.
Definition at line 680 of file input_context.cpp.
 {
     scroll_offset = SIZE_MAX;
     size_t legend_idx = 0;
     for( ; legend_idx < 4; legend_idx++ ) {
         draw_colored_text( legend[legend_idx], c_white );
         ImGui::SameLine();
         std::string button_text_no_color = remove_color_tags( buttons[legend_idx].second );
         ImGui::SetCursorPosX( str_width_to_pixels( width ) - ( get_text_width(
                                   button_text_no_color ) +
                               ( ImGui::GetStyle().FramePadding.x * 2 ) + ImGui::GetStyle().ItemSpacing.x ) );
         ImGui::BeginDisabled( status == kb_menu_status::filter );
         action_button( buttons[legend_idx].first, button_text_no_color );
         ImGui::EndDisabled();
     }
     for( ; legend_idx < legend.size(); legend_idx++ ) {
         draw_colored_text( legend[legend_idx], c_white );
     }
     draw_filter( *ctxt, status == kb_menu_status::filter );
     if( last_status != status && status == kb_menu_status::filter ) {
         ImGui::SetKeyboardFocusHere( -1 );
     }
     ImGui::Separator();
     if( last_status != status && status == kb_menu_status::show ) {
         ImGui::SetNextWindowFocus();
     }
     if( ImGui::BeginTable( "KB_KEYS", 2, ImGuiTableFlags_ScrollY ) ) {
         ImGui::TableSetupColumn( "Action Name",
                                  ImGuiTableColumnFlags_WidthStretch | ImGuiTableColumnFlags_NoSort );
         float keys_col_width = str_width_to_pixels( width ) - str_width_to_pixels( TERMX >= 100 ? 62 : 52 );
         ImGui::TableSetupColumn( "Assigned Key(s)",
                                  ImGuiTableColumnFlags_WidthFixed | ImGuiTableColumnFlags_NoSort, keys_col_width );
         //ImGui::TableHeadersRow();
         for( size_t i = 0; i < filtered_registered_actions.size(); i++ ) {
             const std::string &action_id = filtered_registered_actions[i];
             bool overwrite_default;
             const action_attributes &attributes = inp_mngr.get_action_attributes( action_id, ctxt->category,
                                                   &overwrite_default );
             bool basic_overwrite_default;
             const action_attributes &basic_attributes = inp_mngr.get_action_attributes( action_id,
                     ctxt->category, &basic_overwrite_default, true );
             bool customized_keybinding = overwrite_default != basic_overwrite_default
                                          || attributes.input_events != basic_attributes.input_events;
             ImGui::TableNextColumn();
             ImGui::Text( " " );
             ImGui::SameLine( 0, 0 );
             char invlet = ' ';
             //if( i < hotkeys.size() ) {
             //    invlet = hotkeys[i];
             if( ImGui::IsItemVisible() ) {
                 if( scroll_offset == SIZE_MAX ) {
                     scroll_offset = i;
                 }
                 if( i >= scroll_offset && ( i - scroll_offset ) < hotkeys.size() ) {
                     invlet = hotkeys[i - scroll_offset];
                 }
             }
             std::string key_text;
             if( ( status == kb_menu_status::add_global && overwrite_default )
                 || ( status == kb_menu_status::reset && !customized_keybinding )
               ) {
                 // We're trying to add a global, but this action has a local
                 // defined, so gray out the invlet.
                 key_text = colorize( string_format( "%c", invlet ), c_dark_gray );
             } else if( status == kb_menu_status::add || status == kb_menu_status::add_global ||
                        status == kb_menu_status::remove || status == kb_menu_status::reset ) {
                 key_text = colorize( string_format( "%c", invlet ), c_light_blue );
             } else if( status == kb_menu_status::execute ) {
                 key_text = colorize( string_format( "%c", invlet ), c_white );
             } else {
                 key_text = " ";
             }
             nc_color col;
             if( attributes.input_events.empty() ) {
                 col = i == size_t( highlight_row_index ) ? h_unbound_key : unbound_key;
             } else if( overwrite_default ) {
                 col = i == size_t( highlight_row_index ) ? h_local_key : local_key;
             } else {
                 col = i == size_t( highlight_row_index ) ? h_global_key : global_key;
             }
             if( customized_keybinding ) {
                 key_text += "*";
             } else {
                 key_text += " ";
             }
             key_text += string_format( "%s:", ctxt->get_action_name( action_id ) );
             bool is_selected = false;
             bool is_hovered = false;
             draw_colored_text( key_text, col, 0.0f, status == kb_menu_status::show ? nullptr : &is_selected,
                                nullptr, &is_hovered );
             if( ( is_selected || is_hovered ) && invlet != ' ' ) {
                 highlight_row_index = i;
             }
             //ImGui::SameLine();
             //ImGui::SetCursorPosX(str_width_to_pixels(TERMX >= 100 ? 62 : 52));
             ImGui::TableNextColumn();
             ImGui::Text( "%s", ctxt->get_desc( action_id ).c_str() );
         }
         ImGui::EndTable();
     }
     last_status = status;
     // spopup.query_string() will call wnoutrefresh( w_help )
     //spopup.text(filter_phrase);
     //spopup.query_string(false, true);
     // Record cursor immediately after spopup drawing
     //ui.record_term_cursor();
 }
References cataimgui::window::action_button(), add, add_global, buttons, c_dark_gray, c_light_blue, c_white, input_context::category, colorize(), ctxt, cataimgui::window::draw_colored_text(), cataimgui::window::draw_filter(), execute, filter, filtered_registered_actions, input_manager::get_action_attributes(), input_context::get_action_name(), input_context::get_desc(), cataimgui::window::get_text_width(), global_key, h_global_key, h_local_key, h_unbound_key, highlight_row_index, hotkeys, inp_mngr, action_attributes::input_events, last_status, legend, local_key, remove, remove_color_tags(), reset, scroll_offset, second, show, status, cataimgui::window::str_width_to_pixels(), string_format(), TERMX, unbound_key, and width.
get_bounds()
cataimgui::bounds keybindings_ui::get_bounds () override protected virtual
Reimplemented from cataimgui::window.
Definition at line 675 of file input_context.cpp.
 {
     return { -1.f, -1.f, float( str_width_to_pixels( width ) ), float( str_height_to_pixels( TERMY ) ) };
 }
References cataimgui::window::str_height_to_pixels(), cataimgui::window::str_width_to_pixels(), TERMY, and width.
init()
void keybindings_ui::init ()
Definition at line 793 of file input_context.cpp.
 {
     width = TERMX >= 100 ? 100 : 80;
 }
References TERMX, and width.
Referenced by input_context::display_menu(), and on_resized().
on_resized()
void keybindings_ui::on_resized () inline override protected virtual
Reimplemented from cataimgui::window.
Definition at line 70 of file input_context.cpp.
{
             init();
         };
References init().
Member Data Documentation
buttons
std::vector<std::pair<std::string, std::string> > keybindings_ui::buttons
Definition at line 57 of file input_context.cpp.
Referenced by draw_controls(), and keybindings_ui().
ctxt
input_context* keybindings_ui::ctxt private
Definition at line 50 of file input_context.cpp.
Referenced by draw_controls(), and keybindings_ui().
filtered_registered_actions
std::vector<std::string> keybindings_ui::filtered_registered_actions
Definition at line 59 of file input_context.cpp.
Referenced by input_context::display_menu(), and draw_controls().
global_key
const nc_color keybindings_ui::global_key = c_light_gray private
Definition at line 44 of file input_context.cpp.
Referenced by draw_controls(), and keybindings_ui().
h_global_key
const nc_color keybindings_ui::h_global_key = h_light_gray private
Definition at line 45 of file input_context.cpp.
Referenced by draw_controls().
h_local_key
const nc_color keybindings_ui::h_local_key = h_light_green private
Definition at line 47 of file input_context.cpp.
Referenced by draw_controls().
h_unbound_key
const nc_color keybindings_ui::h_unbound_key = h_light_red private
Definition at line 49 of file input_context.cpp.
Referenced by draw_controls().
highlight_row_index
int keybindings_ui::highlight_row_index = -1
Definition at line 61 of file input_context.cpp.
Referenced by input_context::display_menu(), and draw_controls().
hotkeys
std::string keybindings_ui::hotkeys
Definition at line 60 of file input_context.cpp.
Referenced by input_context::display_menu(), and draw_controls().
last_status
kb_menu_status keybindings_ui::last_status = kb_menu_status::execute
Definition at line 53 of file input_context.cpp.
Referenced by draw_controls().
legend
std::vector<std::string> keybindings_ui::legend
Definition at line 56 of file input_context.cpp.
Referenced by draw_controls(), and keybindings_ui().
local_key
const nc_color keybindings_ui::local_key = c_light_green private
Definition at line 46 of file input_context.cpp.
Referenced by draw_controls(), and keybindings_ui().
scroll_offset
size_t keybindings_ui::scroll_offset = 0
Definition at line 62 of file input_context.cpp.
Referenced by input_context::display_menu(), and draw_controls().
status
kb_menu_status keybindings_ui::status = kb_menu_status::show
Definition at line 53 of file input_context.cpp.
Referenced by input_context::display_menu(), and draw_controls().
unbound_key
const nc_color keybindings_ui::unbound_key = c_light_red private
Definition at line 48 of file input_context.cpp.
Referenced by draw_controls(), and keybindings_ui().
width
int keybindings_ui::width = 0
Definition at line 58 of file input_context.cpp.
Referenced by draw_controls(), get_bounds(), and init().
The documentation for this class was generated from the following file:
src/input_context.cpp