Cataclysm DDA: trade_selector Class Reference
trade_selector Class Reference
#include <trade_ui.h>
Public Types
using entry_t = std::pair< item_location, int >
using select_t = std::vector< entry_t >
Public Types inherited from inventory_multiselector
using GetStats = std::function< stats(const std::vector< std::pair< item_location, int > >)>
Public Types inherited from inventory_selector
enum selector_invlet_type { SELECTOR_INVLET_DEFAULT , SELECTOR_INVLET_NUMERIC , SELECTOR_INVLET_ALPHA }
enum class uimode : int { categories = 0 , hierarchy , last }
using stat = std::array< std::string, 4 >
using stats = std::array< stat, 3 >
Public Member Functions
trade_selector (trade_ui *parent, Character &u, inventory_selector_preset const &preset=default_preset, std::string const &selection_column_title=_("TRADE OFFER"), point const &size={ -1, -1 }, point const &origin={ -1, -1 })
void execute ()
void on_toggle () override
select_t to_trade () const
void resize (point const &size, point const &origin)
shared_ptr_fast< ui_adaptor > get_ui () const
input_context const * get_ctxt () const
Public Member Functions inherited from inventory_drop_selector
inventory_drop_selector (Character &p, const inventory_selector_preset &preset=default_preset, const std::string &selection_column_title=_("ITEMS TO DROP"), bool warn_liquid=true)
drop_locations execute ()
Public Member Functions inherited from inventory_multiselector
inventory_multiselector (Character &p, const inventory_selector_preset &preset=default_preset, const std::string &selection_column_title="", const GetStats &={}, bool allow_select_contained=false)
drop_locations execute (bool allow_empty=false)
void toggle_entry (inventory_entry &entry, size_t count)
Public Member Functions inherited from inventory_selector
inventory_selector (Character &u, const inventory_selector_preset &preset=default_preset)
virtual ~inventory_selector ()
bool add_contained_items (item_location &container)
These functions add items from map / vehicles.
bool add_contained_items (item_location &container, inventory_column &column, const item_category *custom_category=nullptr, item_location const &topmost_parent={}, int indent=0)
void add_contained_gunmods (Character &you, item &gun)
void add_contained_ebooks (item_location &container)
void add_character_items (Character &character)
void add_map_items (const tripoint &target)
void add_vehicle_items (const tripoint &target)
void add_nearby_items (int radius=1)
void add_remote_map_items (tinymap *remote_map, const tripoint &target)
void add_basecamp_items (const basecamp &camp)
void clear_items ()
Remove all items.
void set_title (const std::string &title)
Assigns a title that will be shown on top of the menu.
void set_hint (const std::string &hint)
Assigns a hint.
void set_display_stats (bool display_stats)
Specify whether the header should show stats (weight and volume).
bool empty () const
bool has_available_choices () const
uint64_t item_entry_count () const
drop_location get_only_choice () const
void set_filter (const std::string &str)
Apply filter string to all columns.
std::string get_filter () const
Get last filter string set by set_filter or entered by player.
void set_invlet_type (selector_invlet_type type)
Set the letter group to use for automatic inventory letters.
selector_invlet_type invlet_type ()
void show_invlet (bool show)
Set whether to show inventory letters.
bool showing_invlet () const
void categorize_map_items (bool toggle)
bool highlight (const item_location &loc, bool hidden=false, bool front_only=false)
Highlight a location.
const inventory_entry & get_highlighted () const
item_location get_collation_next () const
void highlight_position (std::pair< size_t, size_t > position)
bool highlight_one_of (const std::vector< item_location > &locations, bool hidden=false)
std::pair< size_t, size_t > get_highlighted_position () const
inventory_column & get_column (size_t index) const
inventory_column & get_active_column () const
void toggle_categorize_contained ()
void set_active_column (size_t index)
void toggle_skip_unselectable ()
std::string action_bound_to_key (char key) const
Static Public Attributes
static constexpr char const * ACTION_AUTOBALANCE = "AUTO_BALANCE"
static constexpr char const * ACTION_BANKBALANCE = "BANK_BALANCE"
static constexpr char const * ACTION_SWITCH_PANES = "SWITCH_LISTS"
static constexpr char const * ACTION_TRADE_OK = "CONFIRM"
static constexpr char const * ACTION_TRADE_CANCEL = "QUIT"
Private Attributes
trade_ui * _parent
shared_ptr_fast< ui_adaptor > _ui
input_context _ctxt_trade
Additional Inherited Members
Protected Member Functions inherited from inventory_drop_selector
stats get_raw_stats () const override
Get stats to display in top right.
Protected Member Functions inherited from inventory_multiselector
void rearrange_columns (size_t client_width) override
Tackles screen overflow.
void set_chosen_count (inventory_entry &entry, size_t count)
void deselect_contained_items ()
void toggle_entries (int &count, toggle_mode mode=toggle_mode::SELECTED)
void on_input (const inventory_input &input)
void toggle_categorize_contained ()
Protected Member Functions inherited from inventory_selector
const item_category * naturalize_category (const item_category &category, const tripoint &pos)
inventory_entry * add_entry (inventory_column &target_column, std::vector< item_location > &&locations, const item_category *custom_category=nullptr, size_t chosen_count=0, item_location const &topmost_parent={}, bool chevron=false)
bool add_entry_rec (inventory_column &entry_column, inventory_column &children_column, item_location &loc, item_category const *entry_category=nullptr, item_category const *children_category=nullptr, item_location const &topmost_parent={}, int indent=0)
bool drag_drop_item (item *sourceItem, item *destItem)
inventory_input get_input ()
inventory_input process_input (const std::string &action, int ch)
void on_input (const inventory_input &input)
Given an action from the input_context, try to act according to it.
void on_change (const inventory_entry &entry)
Entry has been changed.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
size_t get_layout_width () const
size_t get_layout_height () const
std::pair< bool, std::string > query_string (const std::string &val, bool end_with_toggle=false)
Query user for a string and return it.
void query_set_filter ()
Query the user for a filter and apply it.
int query_count (char init=0, bool end_with_toggle=false)
Query the user for count and return it.
std::vector< std::string > get_stats () const
std::pair< std::string, nc_color > get_footer (navigation_mode m) const
size_t get_header_height () const
size_t get_header_min_width () const
size_t get_footer_min_width () const
inventory_entry * find_entry_by_invlet (int invlet) const
inventory_entry * find_entry_by_coordinate (const point &coordinate) const
inventory_entry * find_entry_by_location (item_location &loc) const
const std::vector< inventory_column * > & get_all_columns () const
std::vector< inventory_column * > get_visible_columns () const
void highlight ()
Highlight parent and contents of highlighted item.
void action_examine (const item_location &sitem)
Show detailed item information for the selected item.
virtual void reassign_custom_invlets ()
size_t get_columns_width (const std::vector< inventory_column * > &columns) const
double get_columns_occupancy_ratio (size_t client_width) const
bool are_columns_centered (size_t client_width) const
bool is_overflown (size_t client_width) const
bool is_active_column (const inventory_column &column) const
void append_column (inventory_column &column)
void toggle_active_column (scroll_direction dir)
Activates either previous or next column.
void refresh_active_column ()
void toggle_navigation_mode ()
const navigation_mode_data & get_navigation_data (navigation_mode m) const
Static Protected Member Functions inherited from inventory_selector
static stat get_weight_and_length_stat (units::mass weight_carried, units::mass weight_capacity, const units::length &longest_length)
static stat get_volume_stat (const units::volume &volume_carried, const units::volume &volume_capacity, const units::volume &largest_free_volume)
static stat get_holster_stat (const units::volume &holster_volume, int used_holsters, int total_holsters)
static stats get_weight_and_volume_and_holster_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume &volume_carried, const units::volume &volume_capacity, const units::length &longest_length, const units::volume &largest_free_volume, const units::volume &holster_volume, int used_holsters, int total_holsters)
Protected Attributes inherited from inventory_multiselector
size_t max_chosen_count
std::vector< std::pair< item_location, int > > to_use
std::vector< item_location > usable_locs
bool allow_select_contained
int count = 0
Protected Attributes inherited from inventory_selector
Character & u
const inventory_selector_preset & preset
input_context ctxt
The input context for navigation, already contains some actions for movement.
std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * > > rect_entry_map
std::vector< inventory_column * > columns
point _fixed_origin { -1, -1 }
point _fixed_size { -1, -1 }
bool _categorize_map_items = false
bool force_single_column = false
Detailed Description
Definition at line 25 of file trade_ui.h.
Member Typedef Documentation
entry_t
using trade_selector::entry_t = std::pair<item_location, int>
Definition at line 33 of file trade_ui.h.
select_t
using trade_selector::select_t = std::vector<entry_t>
Definition at line 34 of file trade_ui.h.
Constructor & Destructor Documentation
trade_selector()
trade_selector::trade_selector (trade_ui * parent, Character & u, inventory_selector_preset const & preset = default_preset, std::string const & selection_column_title = _("TRADE OFFER"), point const & size = { -1, -1 }, point const & origin = { -1, -1 }) explicit
Definition at line 4506 of file inventory_ui.cpp.
     : inventory_drop_selector( u, preset, selection_column_title ), _parent( parent ),
       _ctxt_trade( "INVENTORY", keyboard_mode::keychar )
 {
     _ctxt_trade.register_action( ACTION_SWITCH_PANES );
     _ctxt_trade.register_action( ACTION_TRADE_CANCEL );
     _ctxt_trade.register_action( ACTION_TRADE_OK );
     _ctxt_trade.register_action( ACTION_AUTOBALANCE );
     _ctxt_trade.register_action( ACTION_BANKBALANCE );
     _ctxt_trade.register_action( "ANY_INPUT" );
     // duplicate this action in the parent ctxt so it shows up in the keybindings menu
     // CANCEL and OK are already set in inventory_selector
     ctxt.register_action( ACTION_SWITCH_PANES );
     ctxt.register_action( ACTION_AUTOBALANCE );
     ctxt.register_action( ACTION_BANKBALANCE );
     resize( size, origin );
     _ui = create_or_get_ui_adaptor();
 }
References _ctxt_trade, _ui, ACTION_AUTOBALANCE, ACTION_BANKBALANCE, ACTION_SWITCH_PANES, ACTION_TRADE_CANCEL, ACTION_TRADE_OK, inventory_selector::create_or_get_ui_adaptor(), inventory_selector::ctxt, keychar, input_context::register_action(), resize(), om_direction::size, and u.
Member Function Documentation
execute()
void trade_selector::execute ()
Definition at line 4533 of file inventory_ui.cpp.
 {
     debug_print_timer( tp_start );
     bool exit = false;
     get_active_column().on_activate();
     while( !exit ) {
         _ui->invalidate_ui();
         ui_manager::redraw_invalidated();
         std::string const &action = _ctxt_trade.handle_input();
         if( action == ACTION_SWITCH_PANES ) {
             _parent->pushevent( trade_ui::event::SWITCH );
             get_active_column().on_deactivate();
             exit = true;
         } else if( action == ACTION_TRADE_OK ) {
             _parent->pushevent( trade_ui::event::TRADEOK );
             exit = true;
         } else if( action == ACTION_TRADE_CANCEL ) {
             _parent->pushevent( trade_ui::event::TRADECANCEL );
             exit = true;
         } else if( action == ACTION_AUTOBALANCE ) {
             _parent->autobalance();
         } else if( action == ACTION_BANKBALANCE ) {
             _parent->bank_balance();
         } else {
             input_event const iev = _ctxt_trade.get_raw_input();
             inventory_input const input =
                 process_input( ctxt.input_to_action( iev ), iev.get_first_input() );
             inventory_drop_selector::on_input( input );
             if( input.action == "HELP_KEYBINDINGS" ) {
                 ctxt.display_menu();
             }
         }
     }
 }
References _ctxt_trade, _parent, _ui, action, inventory_input::action, ACTION_AUTOBALANCE, ACTION_BANKBALANCE, ACTION_SWITCH_PANES, ACTION_TRADE_CANCEL, ACTION_TRADE_OK, trade_ui::autobalance(), trade_ui::bank_balance(), inventory_selector::ctxt, anonymous_namespace{inventory_ui.cpp}::debug_print_timer(), input_context::display_menu(), inventory_selector::get_active_column(), input_event::get_first_input(), input_context::get_raw_input(), input_context::handle_input(), input_context::input_to_action(), inventory_column::on_activate(), inventory_column::on_deactivate(), inventory_multiselector::on_input(), inventory_selector::process_input(), trade_ui::pushevent(), ui_manager::redraw_invalidated(), trade_ui::SWITCH, anonymous_namespace{inventory_ui.cpp}::tp_start, trade_ui::TRADECANCEL, and trade_ui::TRADEOK.
get_ctxt()
input_context const * trade_selector::get_ctxt () const
Definition at line 4589 of file inventory_ui.cpp.
 {
     return &_ctxt_trade;
 }
References _ctxt_trade.
get_ui()
shared_ptr_fast< ui_adaptor > trade_selector::get_ui () const
Definition at line 4584 of file inventory_ui.cpp.
 {
     return _ui;
 }
References _ui.
on_toggle()
void trade_selector::on_toggle () override virtual
Reimplemented from inventory_multiselector.
Definition at line 4570 of file inventory_ui.cpp.
 {
     _parent->recalc_values_cpane();
 }
References _parent, and trade_ui::recalc_values_cpane().
resize()
void trade_selector::resize (point const & size, point const & origin)
Definition at line 4575 of file inventory_ui.cpp.
 {
     _fixed_size = size;
     _fixed_origin = origin;
     if( _ui ) {
         _ui->mark_resize();
     }
 }
References inventory_selector::_fixed_origin, inventory_selector::_fixed_size, _ui, and om_direction::size.
Referenced by trade_selector().
to_trade()
trade_selector::select_t trade_selector::to_trade () const
Definition at line 4528 of file inventory_ui.cpp.
 {
     return to_use;
 }
References inventory_multiselector::to_use.
Member Data Documentation
_ctxt_trade
input_context trade_selector::_ctxt_trade private
Definition at line 51 of file trade_ui.h.
Referenced by execute(), get_ctxt(), and trade_selector().
_parent
trade_ui* trade_selector::_parent private
Definition at line 49 of file trade_ui.h.
Referenced by execute(), and on_toggle().
_ui
shared_ptr_fast<ui_adaptor> trade_selector::_ui private
Definition at line 50 of file trade_ui.h.
Referenced by execute(), get_ui(), resize(), and trade_selector().
ACTION_AUTOBALANCE
constexpr char const* trade_selector::ACTION_AUTOBALANCE = "AUTO_BALANCE" static constexpr
Definition at line 42 of file trade_ui.h.
Referenced by trade_ui::_draw_header(), execute(), and trade_selector().
ACTION_BANKBALANCE
constexpr char const* trade_selector::ACTION_BANKBALANCE = "BANK_BALANCE" static constexpr
Definition at line 43 of file trade_ui.h.
Referenced by trade_ui::_draw_header(), execute(), and trade_selector().
ACTION_SWITCH_PANES
constexpr char const* trade_selector::ACTION_SWITCH_PANES = "SWITCH_LISTS" static constexpr
Definition at line 44 of file trade_ui.h.
Referenced by trade_ui::_draw_header(), execute(), and trade_selector().
ACTION_TRADE_CANCEL
constexpr char const* trade_selector::ACTION_TRADE_CANCEL = "QUIT" static constexpr
Definition at line 46 of file trade_ui.h.
Referenced by execute(), and trade_selector().
ACTION_TRADE_OK
constexpr char const* trade_selector::ACTION_TRADE_OK = "CONFIRM" static constexpr
Definition at line 45 of file trade_ui.h.
Referenced by execute(), and trade_selector().
The documentation for this class was generated from the following files:
src/trade_ui.h
src/inventory_ui.cpp