Cataclysm DDA: iuse_transform Class Reference
iuse_transform Class Reference
Transform an item into a specific type.
#include <iuse_actor.h>
Public Member Functions
iuse_transform (const std::string &type="transform")
~iuse_transform () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
ret_val< void > can_use (const Character &, const item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
std::string get_name () const override
Returns the translated name of the action.
void finalize (const itype_id &my_item_type) override
Finalizes the actor.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_description () const
Returns the translated description of the action.
Public Attributes
translation msg_transform
displayed if player sees transformation with s replaced by item name
itype_id target
type of the resulting item
itype_id container
if set transform item to container and place new item (of type target) inside
std::string variant_type = "<any>"
if set choose this variant when transforming
bool sealed = true
whether the transformed container is sealed
int ammo_qty = -1
if zero or positive set remaining ammo of target to this (after transformation)
std::vector< int > random_ammo_qty
if this has values, set remaining ammo of target to one of them chosen at random (after transformation)
time_duration target_timer = 0_seconds
if positive set transformed item active and start countdown for countdown_action
itype_id ammo_type
if both this and ammo_qty are specified then set target to this specific ammo
bool active = false
used to set the active property of the transformed target
bool need_worn = false
does the item requires to be worn to be activable
bool need_wielding = false
does the item requires to be wielded to be activable
bool need_empty = false
does the item require being empty to be activable
int moves = 0
subtracted from Creature::moves when transformation is successful
int need_fire = 0
minimum number of fire charges required (if any) for transformation
translation need_fire_msg
displayed if item is in player possession with s replaced by item name
int need_charges = 0
minimum charges (if any) required for transformation
translation need_charges_msg
displayed if item is in player possession with s replaced by item name
std::map< quality_id, int > qualities_needed
Tool qualities needed, e.g.
translation menu_text
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Private Member Functions
void do_transform (Character *p, item &it, const std::string &variant_type) const
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Transform an item into a specific type.
Optionally activate it. Optionally split it in container and content (like opening a jar).
It optionally checks for
original item has a minimal amount of charges.
player has a minimal amount of "fire" charges and consumes them,
if fire is used, checks that the player is not underwater.
Definition at line 47 of file iuse_actor.h.
Constructor & Destructor Documentation
iuse_transform()
iuse_transform::iuse_transform (const std::string & type = "transform") inline explicit
Definition at line 109 of file iuse_actor.h.
 : iuse_actor( type ) {}
~iuse_transform()
iuse_transform::~iuse_transform () override default
Member Function Documentation
can_use()
ret_val< void > iuse_transform::can_use (const Character & p, const item & it, const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 352 of file iuse_actor.cpp.
 {
     if( need_worn && !p.is_worn( it ) ) {
         return ret_val<void>::make_failure( _( "You need to wear the %1$s before activating it." ),
                                             it.tname() );
     }
     if( need_wielding && !p.is_wielding( it ) ) {
         return ret_val<void>::make_failure( _( "You need to wield the %1$s before activating it." ),
                                             it.tname() );
     }
     if( need_empty && !it.empty() ) {
         return ret_val<void>::make_failure( _( "You need to empty the %1$s before activating it." ),
                                             it.tname() );
     }
     if( p.is_worn( it ) ) {
         item tmp = item( target );
         if( !tmp.has_flag( flag_OVERSIZE ) && !tmp.has_flag( flag_SEMITANGIBLE ) ) {
             for( const trait_id &mut : p.get_mutations() ) {
                 const mutation_branch &branch = mut.obj();
                 if( branch.conflicts_with_item( tmp ) ) {
                     return ret_val<void>::make_failure( _( "Your %1$s mutation prevents you from doing that." ),
                                                         p.mutation_name( mut ) );
                 }
             }
         }
     }
     if( need_charges && it.ammo_remaining( &p, true ) < need_charges ) {
         return ret_val<void>::make_failure( string_format( need_charges_msg, it.tname() ) );
     }
     if( qualities_needed.empty() ) {
         return ret_val<void>::make_success();
     }
     std::map<quality_id, int> unmet_reqs;
     inventory inv;
     inv.form_from_map( p.pos(), 1, &p, true, true );
     for( const auto &quality : qualities_needed ) {
         if( !p.has_quality( quality.first, quality.second ) &&
             !inv.has_quality( quality.first, quality.second ) ) {
             unmet_reqs.insert( quality );
         }
     }
     if( unmet_reqs.empty() ) {
         return ret_val<void>::make_success();
     }
     std::string unmet_reqs_string = enumerate_as_string( unmet_reqs.begin(), unmet_reqs.end(),
     [&]( const std::pair<quality_id, int> &unmet_req ) {
         return string_format( "%s %d", unmet_req.first.obj().name, unmet_req.second );
     } );
     return ret_val<void>::make_failure( n_gettext( "You need a tool with %s.",
                                         "You need tools with %s.",
                                         unmet_reqs.size() ), unmet_reqs_string );
 }
References _, item::ammo_remaining(), mutation_branch::conflicts_with_item(), item::empty(), enumerate_as_string(), flag_OVERSIZE, flag_SEMITANGIBLE, inventory::form_from_map(), Character::get_mutations(), item::has_flag(), Character::has_quality(), inventory::has_quality(), Character::is_wielding(), Character::is_worn(), item, ret_val< T >::make_failure(), ret_val< T >::make_success(), Character::mutation_name(), n_gettext, need_charges, need_charges_msg, need_empty, need_wielding, need_worn, Creature::pos(), qualities_needed, string_format(), target, and item::tname().
clone()
std::unique_ptr< iuse_actor > iuse_transform::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Reimplemented in delayed_transform_iuse.
Definition at line 163 of file iuse_actor.cpp.
 {
     return std::make_unique<iuse_transform>( *this );
 }
do_transform()
void iuse_transform::do_transform (Character * p, item & it, const std::string & variant_type) const private
Definition at line 284 of file iuse_actor.cpp.
 {
     item obj_copy( it );
     item *obj;
     // defined here to allow making a new item assigned to the pointer
     item obj_it;
     if( container.is_empty() ) {
         obj = &it.convert( target, p );
         obj->set_itype_variant( variant_type );
         if( ammo_qty >= 0 || !random_ammo_qty.empty() ) {
             int qty;
             if( !random_ammo_qty.empty() ) {
                 const int index = rng( 1, random_ammo_qty.size() - 1 );
                 qty = rng( random_ammo_qty[index - 1], random_ammo_qty[index] );
             } else {
                 qty = ammo_qty;
             }
             if( !ammo_type.is_empty() ) {
                 obj->ammo_set( ammo_type, qty );
             } else if( obj->is_ammo() ) {
                 obj->charges = qty;
             } else if( !obj->ammo_current().is_null() ) {
                 obj->ammo_set( obj->ammo_current(), qty );
             } else if( obj->has_flag( flag_RADIO_ACTIVATION ) && obj->has_flag( flag_BOMB ) ) {
                 obj->set_countdown( 1 );
             } else {
                 obj->set_countdown( qty );
             }
         }
     } else {
         obj = &it.convert( container, p );
         obj->set_itype_variant( variant_type );
         int count = std::max( ammo_qty, 1 );
         item cont;
         if( target->count_by_charges() ) {
             cont = item( target, calendar::turn, count );
             count = 1;
         } else {
             cont = item( target, calendar::turn );
         }
         for( int i = 0; i < count; i++ ) {
             if( !it.put_in( cont, pocket_type::CONTAINER ).success() ) {
                 it.put_in( cont, pocket_type::MIGRATION );
             }
         }
         if( sealed ) {
             it.seal();
         }
     }
     if( target_timer > 0_seconds ) {
         obj->countdown_point = calendar::turn + target_timer;
     }
     obj->active = active || obj->has_temperature() || target_timer > 0_seconds;
     if( p && p->is_worn( *obj ) ) {
         if( !obj->is_armor() ) {
             item_location il = item_location( *p, obj );
             p->takeoff( il );
         } else {
             p->calc_encumbrance();
             p->update_bodytemp();
             p->on_worn_item_transform( obj_copy, *obj );
         }
     }
     p->clear_inventory_search_cache();
 }
References item::active, active, item::ammo_current(), ammo_qty, item::ammo_set(), ammo_type, Character::calc_encumbrance(), item::charges, Character::clear_inventory_search_cache(), container, CONTAINER, item::convert(), itype::count_by_charges(), item::countdown_point, flag_BOMB, flag_RADIO_ACTIVATION, item::has_flag(), item::has_temperature(), item::is_ammo(), item::is_armor(), string_id< T >::is_empty(), string_id< T >::is_null(), Character::is_worn(), item, max(), MIGRATION, Character::on_worn_item_transform(), item::put_in(), random_ammo_qty, rng(), item::seal(), sealed, item::set_countdown(), item::set_itype_variant(), ret_val_common::success(), Character::takeoff(), target, target_timer, calendar::turn, Character::update_bodytemp(), and variant_type.
Referenced by use().
finalize()
void iuse_transform::finalize (const itype_id &) override virtual
Finalizes the actor.
Must be called after all items are loaded.
Reimplemented from iuse_actor.
Definition at line 418 of file iuse_actor.cpp.
 {
     if( !item::type_is_defined( target ) ) {
         debugmsg( "Invalid transform target: %s", target.c_str() );
     }
     if( !container.is_empty() ) {
         if( !item::type_is_defined( container ) ) {
             debugmsg( "Invalid transform container: %s", container.c_str() );
         }
         // todo: check contents fit container?
         // transform uses migration pocket if not
     }
 }
References string_id< T >::c_str(), container, debugmsg, string_id< T >::is_empty(), target, and item::type_is_defined().
get_name()
std::string iuse_transform::get_name () const override virtual
Returns the translated name of the action.
It is used for the item action menu.
Reimplemented from iuse_actor.
Definition at line 410 of file iuse_actor.cpp.
 {
     if( !menu_text.empty() ) {
         return menu_text.translated();
     }
     return iuse_actor::get_name();
 }
References translation::empty(), iuse_actor::get_name(), menu_text, and translation::translated().
info()
void iuse_transform::info (const item & it, std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 434 of file iuse_actor.cpp.
 {
     int amount = std::max( ammo_qty, 1 );
     item dummy( target, calendar::turn, target->count_by_charges() ? amount : 1 );
     dummy.set_itype_variant( variant_type );
     // If the variant is to be randomized, use default no-variant name
     if( variant_type == "<any>" ) {
         dummy.clear_itype_variant();
     }
     if( it.has_flag( flag_FIT ) ) {
         dummy.set_flag( flag_FIT );
     }
     if( target->count_by_charges() || !ammo_type.is_empty() ) {
         if( !ammo_type.is_empty() ) {
             dump.emplace_back( "TOOL", _( "<bold>Turns into</bold>: " ),
                                string_format( _( "%s (%d %s)" ), dummy.tname(), amount, ammo_type->nname( amount ) ) );
         } else if( !container.is_empty() ) {
             dump.emplace_back( "TOOL", _( "<bold>Turns into</bold>: " ),
                                amount > 1 ?
                                string_format( _( "%s (%d %s)" ),
                                               container->nname( 1 ), amount, target->nname( amount ) ) :
                                string_format( _( "%s (%s)" ),
                                               container->nname( 1 ), target->nname( amount ) ) );
         } else {
             dump.emplace_back( "TOOL", _( "<bold>Turns into</bold>: " ),
                                string_format( _( "%s (%d)" ), target->nname( amount ), amount ) );
         }
     } else {
         dump.emplace_back( "TOOL", _( "<bold>Turns into</bold>: " ),
                            amount > 1 ?
                            string_format( _( "%d %s" ), amount, target->nname( amount ) ) :
                            string_format( _( "%s" ), target->nname( amount ) ) );
     }
     if( target_timer > 0_seconds ) {
         dump.emplace_back( "TOOL", _( "Countdown: " ), to_seconds<int>( target_timer ) );
     }
     const auto *explosion_use = dummy.get_use( "explosion" );
     if( explosion_use != nullptr ) {
         explosion_use->get_actor_ptr()->info( it, dump );
     }
 }
References _, ammo_qty, ammo_type, item::clear_itype_variant(), container, itype::count_by_charges(), flag_FIT, use_function::get_actor_ptr(), item::get_use(), item::has_flag(), iuse_actor::info(), string_id< T >::is_empty(), max(), itype::nname(), item::set_flag(), item::set_itype_variant(), string_format(), target, target_timer, item::tname(), calendar::turn, and variant_type.
load()
void iuse_transform::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Reimplemented in delayed_transform_iuse.
Definition at line 168 of file iuse_actor.cpp.
 {
     obj.read( "target", target, true );
     obj.read( "msg", msg_transform );
     obj.read( "variant_type", variant_type );
     obj.read( "container", container );
     obj.read( "sealed", sealed );
     if( obj.has_member( "target_charges" ) && obj.has_member( "rand_target_charges" ) ) {
         obj.throw_error_at( "target_charges",
                             "Transform actor specified both fixed and random target charges" );
     }
     obj.read( "target_charges", ammo_qty );
     if( obj.has_array( "rand_target_charges" ) ) {
         for( const int charge : obj.get_array( "rand_target_charges" ) ) {
             random_ammo_qty.push_back( charge );
         }
         if( random_ammo_qty.size() < 2 ) {
             obj.throw_error_at( "rand_target_charges",
                                 "You must specify two or more values to choose between" );
         }
     }
     obj.read( "target_ammo", ammo_type );
     obj.read( "target_timer", target_timer );
     if( !ammo_type.is_empty() && !container.is_empty() ) {
         obj.throw_error_at( "target_ammo", "Transform actor specified both ammo type and container type" );
     }
     obj.read( "active", active );
     obj.read( "moves", moves );
     if( moves < 0 ) {
         obj.throw_error_at( "moves", "transform actor specified negative moves" );
     }
     obj.read( "need_fire", need_fire );
     need_fire = std::max( need_fire, 0 );
     if( !obj.read( "need_charges_msg", need_charges_msg ) ) {
         need_charges_msg = to_translation( "The %s is empty!" );
     }
     obj.read( "need_charges", need_charges );
     need_charges = std::max( need_charges, 0 );
     if( !obj.read( "need_fire_msg", need_fire_msg ) ) {
         need_fire_msg = to_translation( "You need a source of fire!" );
     }
     obj.read( "need_worn", need_worn );
     obj.read( "need_wielding", need_wielding );
     obj.read( "need_empty", need_empty );
     obj.read( "qualities_needed", qualities_needed );
     obj.read( "menu_text", menu_text );
 }
References active, ammo_qty, ammo_type, container, JsonObject::get_array(), JsonObject::has_array(), JsonObject::has_member(), string_id< T >::is_empty(), max(), menu_text, moves, msg_transform, need_charges, need_charges_msg, need_empty, need_fire, need_fire_msg, need_wielding, need_worn, qualities_needed, random_ammo_qty, JsonObject::read(), sealed, target, target_timer, JsonObject::throw_error_at(), to_translation(), and variant_type.
Referenced by delayed_transform_iuse::load().
use()
std::optional< int > iuse_transform::use (Character * p, item & it, const tripoint &) const override virtual
Implements iuse_actor.
Reimplemented in delayed_transform_iuse.
Definition at line 227 of file iuse_actor.cpp.
 {
     int scale = 1;
     auto iter = it.type->ammo_scale.find( type );
     if( iter != it.type->ammo_scale.end() ) {
         scale = iter->second;
     }
     if( !p ) {
         debugmsg( "%s called action transform that requires character but no character is present",
                   it.typeId().str() );
         return std::nullopt;
     }
     int result = 0;
     if( need_fire ) {
         if( !p->use_charges_if_avail( itype_fire, need_fire ) ) {
             p->add_msg_if_player( m_info, need_fire_msg, it.tname() );
             return std::nullopt;
         }
         if( p->cant_do_underwater() ) {
             return std::nullopt;
         }
     }
     if( !msg_transform.empty() ) {
         p->add_msg_if_player( m_neutral, msg_transform, it.tname() );
     }
     // Uses the moves specified by iuse_actor's definition
     p->mod_moves( -moves );
     if( need_fire && p->has_trait( trait_PYROMANIA ) ) {
         if( one_in( 2 ) ) {
             p->add_msg_if_player( m_mixed,
                                   _( "You light a fire, but it isn't enough.  You need to light more." ) );
         } else {
             p->add_msg_if_player( m_good, _( "You happily light a fire." ) );
             p->add_morale( MORALE_PYROMANIA_STARTFIRE, 5, 10, 3_hours, 2_hours );
             p->rem_morale( MORALE_PYROMANIA_NOFIRE );
         }
     }
     if( it.count_by_charges() != target->count_by_charges() && it.count() > 1 ) {
         item take_one = it.split( 1 );
         do_transform( p, take_one, variant_type );
         p->i_add_or_drop( take_one );
     } else {
         do_transform( p, it, variant_type );
     }
     if( it.is_tool() ) {
         result = scale;
     }
     return result;
 }
References _, Character::add_morale(), Character::add_msg_if_player(), itype::ammo_scale, Creature::cant_do_underwater(), item::count(), item::count_by_charges(), itype::count_by_charges(), debugmsg, do_transform(), translation::empty(), Character::has_trait(), Character::i_add_or_drop(), item::is_tool(), itype_fire, m_good, m_info, m_mixed, m_neutral, Creature::mod_moves(), MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, moves, msg_transform, need_fire, need_fire_msg, one_in(), Character::rem_morale(), item::split(), string_id< T >::str(), target, item::tname(), trait_PYROMANIA, item::type, iuse_actor::type, item::typeId(), Character::use_charges_if_avail(), and variant_type.
Referenced by delayed_transform_iuse::use().
Member Data Documentation
active
bool iuse_transform::active = false
used to set the active property of the transformed target
Definition at line 78 of file iuse_actor.h.
Referenced by do_transform(), and load().
ammo_qty
int iuse_transform::ammo_qty = -1
if zero or positive set remaining ammo of target to this (after transformation)
Definition at line 66 of file iuse_actor.h.
Referenced by do_transform(), info(), and load().
ammo_type
itype_id iuse_transform::ammo_type
if both this and ammo_qty are specified then set target to this specific ammo
Definition at line 75 of file iuse_actor.h.
Referenced by do_transform(), info(), and load().
container
itype_id iuse_transform::container
if set transform item to container and place new item (of type target) inside
Definition at line 57 of file iuse_actor.h.
Referenced by do_transform(), finalize(), info(), and load().
menu_text
translation iuse_transform::menu_text
Definition at line 107 of file iuse_actor.h.
Referenced by get_name(), and load().
moves
int iuse_transform::moves = 0
subtracted from Creature::moves when transformation is successful
Definition at line 90 of file iuse_actor.h.
Referenced by load(), and use().
msg_transform
translation iuse_transform::msg_transform
displayed if player sees transformation with s replaced by item name
Definition at line 51 of file iuse_actor.h.
Referenced by load(), and use().
need_charges
int iuse_transform::need_charges = 0
minimum charges (if any) required for transformation
Definition at line 99 of file iuse_actor.h.
Referenced by can_use(), and load().
need_charges_msg
translation iuse_transform::need_charges_msg
displayed if item is in player possession with s replaced by item name
Definition at line 102 of file iuse_actor.h.
Referenced by can_use(), and load().
need_empty
bool iuse_transform::need_empty = false
does the item require being empty to be activable
Definition at line 87 of file iuse_actor.h.
Referenced by can_use(), and load().
need_fire
int iuse_transform::need_fire = 0
minimum number of fire charges required (if any) for transformation
Definition at line 93 of file iuse_actor.h.
Referenced by load(), and use().
need_fire_msg
translation iuse_transform::need_fire_msg
displayed if item is in player possession with s replaced by item name
Definition at line 96 of file iuse_actor.h.
Referenced by load(), and use().
need_wielding
bool iuse_transform::need_wielding = false
does the item requires to be wielded to be activable
Definition at line 84 of file iuse_actor.h.
Referenced by can_use(), and load().
need_worn
bool iuse_transform::need_worn = false
does the item requires to be worn to be activable
Definition at line 81 of file iuse_actor.h.
Referenced by can_use(), and load().
qualities_needed
std::map<quality_id, int> iuse_transform::qualities_needed
Tool qualities needed, e.g.
"fine bolt turning 1".
Definition at line 105 of file iuse_actor.h.
Referenced by can_use(), and load().
random_ammo_qty
std::vector<int> iuse_transform::random_ammo_qty
if this has values, set remaining ammo of target to one of them chosen at random (after transformation)
Definition at line 69 of file iuse_actor.h.
Referenced by do_transform(), and load().
sealed
bool iuse_transform::sealed = true
whether the transformed container is sealed
Definition at line 63 of file iuse_actor.h.
Referenced by do_transform(), and load().
target
itype_id iuse_transform::target
type of the resulting item
Definition at line 54 of file iuse_actor.h.
Referenced by map::add_item(), can_use(), do_transform(), finalize(), info(), mattack::kamikaze(), load(), and use().
target_timer
time_duration iuse_transform::target_timer = 0_seconds
if positive set transformed item active and start countdown for countdown_action
Definition at line 72 of file iuse_actor.h.
Referenced by do_transform(), info(), mattack::kamikaze(), and load().
variant_type
std::string iuse_transform::variant_type = "<any>"
if set choose this variant when transforming
Definition at line 60 of file iuse_actor.h.
Referenced by do_transform(), info(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp