Cataclysm DDA: behavior::node_t Class Reference
behavior::node_t Class Reference
#include <behavior.h>
Public Member Functions
node_t ()=default
behavior_return tick (const oracle_t *subject) const
std::string goal () const
void set_strategy (const strategy_t *new_strategy)
void add_predicate (const std::function< status_t(const oracle_t *, const std::string &)> &new_predicate, const std::string &argument="", const bool &invert_result=false)
void set_goal (const std::string &new_goal)
void add_child (const node_t *new_child)
void load (const JsonObject &jo, std::string_view src)
void check () const
Public Attributes
string_id< node_t > id
std::vector< std::pair< string_id< node_t >, mod_id > > src
bool was_loaded = false
Private Types
using predicate_type = std::function< status_t(const oracle_t *, const std::string &)>
Private Member Functions
status_t process_predicates (const oracle_t *subject) const
Private Attributes
std::vector< const node_t * > children
const strategy_t * strategy = nullptr
std::vector< std::tuple< predicate_type, std::string, bool > > conditions
std::string _goal
Detailed Description
Definition at line 58 of file behavior.h.
Member Typedef Documentation
predicate_type
using behavior::node_t::predicate_type = std::function<status_t(const oracle_t *, const std::string &)> private
Definition at line 82 of file behavior.h.
Constructor & Destructor Documentation
node_t()
behavior::node_t::node_t () default
Member Function Documentation
add_child()
void node_t::add_child (const node_t * new_child)
Definition at line 34 of file behavior.cpp.
 {
     children.push_back( new_child );
 }
References children.
Referenced by mtype::add_goal().
add_predicate()
void node_t::add_predicate (const std::function< status_t(const oracle_t *, const std::string &)> & new_predicate, const std::string & argument = "", const bool & invert_result = false)
Definition at line 24 of file behavior.cpp.
 {
     conditions.emplace_back( new_predicate, argument, invert_result );
 }
References conditions.
check()
void node_t::check () const
Definition at line 174 of file behavior.cpp.
 {
     // Invariants
     if( children.empty() ) {
         if( _goal.empty() ) {
             debugmsg( "Behavior %s must have either children or a goal.",
                       id.str() );
         }
     } else {
         if( strategy == nullptr ) {
             debugmsg( "Behavior %s has children but no strategy.", id.str() );
         }
         if( !_goal.empty() ) {
             debugmsg( "Behavior %s has both children and a goal.", id.str() );
         }
     }
 }
References _goal, children, debugmsg, and strategy.
goal()
std::string node_t::goal () const
Definition at line 83 of file behavior.cpp.
 {
     return _goal;
 }
References _goal.
Referenced by behavior::tree::goal().
load()
void node_t::load (const JsonObject & jo, std::string_view src)
Definition at line 137 of file behavior.cpp.
 {
     // We don't initialize the node unless it has no children (opportunistic optimization).
     // Instead we initialize a parallel struct that holds the labels until finalization.
     if( jo.has_array( "children" ) ) {
         temp_node_data.emplace_back();
         node_data &new_data = temp_node_data.back();
         new_data.id = id;
         optional( jo, was_loaded, "children", new_data.children );
     }
     if( jo.has_string( "strategy" ) ) {
         std::unordered_map<std::string, const strategy_t *>::iterator new_strategy =
             behavior::strategy_map.find( jo.get_string( "strategy" ) );
         if( new_strategy != strategy_map.end() ) {
             strategy = new_strategy->second;
         } else {
             debugmsg( "While loading %s, failed to find strategy %s.",
                       id.str(), jo.get_string( "strategy" ) );
             jo.throw_error( "Invalid strategy in behavior." );
         }
     }
     for( const JsonObject predicate_object : jo.get_array( "conditions" ) ) {
         const std::string predicate_id = predicate_object.get_string( "predicate" );
         auto new_predicate = predicate_map.find( predicate_id );
         if( new_predicate == predicate_map.end() ) {
             debugmsg( "While loading %s, failed to find predicate %s.",
                       id.str(), predicate_id );
             jo.throw_error( "Invalid predicate in behavior." );
         }
         const std::string predicate_argument = predicate_object.get_string( "argument", "" );
         const bool invert_result = predicate_object.get_bool( "invert_result", false );
         conditions.emplace_back( new_predicate->second, predicate_argument,
                                  invert_result );
     }
     optional( jo, was_loaded, "goal", _goal );
 }
References _goal, node_data::children, conditions, debugmsg, JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), node_data::id, id, optional(), behavior::predicate_map, strategy, behavior::strategy_map, anonymous_namespace{behavior.cpp}::temp_node_data, JsonObject::throw_error(), and was_loaded.
process_predicates()
status_t node_t::process_predicates (const oracle_t * subject) const private
Definition at line 39 of file behavior.cpp.
 {
     status_t result = status_t::running;
     for( const std::tuple< predicate_type, std::string, bool > &predicate_tuple : conditions ) {
         predicate_type pt = std::get<0>( predicate_tuple );
         std::string pargs = std::get<1>( predicate_tuple );
         bool pinvert = std::get<2>( predicate_tuple );
         result = pt( subject, pargs );
         if( pinvert ) {
             if( result == status_t::running ) {
                 result = status_t::failure;
             } else if( result == status_t::failure ) {
                 result = status_t::running;
             }
         }
         if( result != status_t::running ) {
             break;
         }
     }
     return result;
 }
References conditions, behavior::failure, and behavior::running.
Referenced by tick().
set_goal()
void node_t::set_goal (const std::string & new_goal)
Definition at line 30 of file behavior.cpp.
 {
     _goal = new_goal;
 }
References _goal.
set_strategy()
void node_t::set_strategy (const strategy_t * new_strategy)
Definition at line 20 of file behavior.cpp.
 {
     strategy = new_strategy;
 }
References strategy.
Referenced by mtype::set_strategy().
tick()
behavior_return node_t::tick (const oracle_t * subject) const
Definition at line 66 of file behavior.cpp.
 {
     if( children.empty() ) {
         status_t result = process_predicates( subject );
         return { result, this };
     } else {
         cata_assert( strategy != nullptr );
         status_t result = process_predicates( subject );
         if( result == status_t::running ) {
             return strategy->evaluate( subject, children );
         } else {
             return { result, nullptr };
         }
     }
 }
References cata_assert, children, behavior::strategy_t::evaluate(), process_predicates(), behavior::running, and strategy.
Referenced by behavior::tree::tick().
Member Data Documentation
_goal
std::string behavior::node_t::_goal private
Definition at line 86 of file behavior.h.
Referenced by check(), goal(), load(), and set_goal().
children
std::vector<const node_t *> behavior::node_t::children private
Definition at line 80 of file behavior.h.
Referenced by add_child(), check(), and tick().
conditions
std::vector<std::tuple<predicate_type, std::string, bool> > behavior::node_t::conditions private
Definition at line 83 of file behavior.h.
Referenced by add_predicate(), load(), and process_predicates().
id
string_id<node_t> behavior::node_t::id
Definition at line 76 of file behavior.h.
Referenced by load().
src
std::vector<std::pair<string_id<node_t>, mod_id> > behavior::node_t::src
Definition at line 77 of file behavior.h.
strategy
const strategy_t* behavior::node_t::strategy = nullptr private
Definition at line 81 of file behavior.h.
Referenced by check(), load(), set_strategy(), and tick().
was_loaded
bool behavior::node_t::was_loaded = false
Definition at line 78 of file behavior.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/behavior.h
src/behavior.cpp