Cataclysm DDA: ret_val< void > Class Reference
ret_val< void > Class Reference
#include <ret_val.h>
Static Public Member Functions
static ret_val make_success ()
static ret_val make_failure ()
template<class... A, typename S = std::string, typename = is_convertible_to_string<S>>
static ret_val make_success (const S &msg, A &&... args)
template<class... A, typename S = std::string, typename = is_convertible_to_string<S>>
static ret_val make_failure (const S &msg, A &&... args)
Private Member Functions
ret_val_common (const std::string &msg, bool succ)
Additional Inherited Members
Public Member Functions inherited from ret_val_common
bool success () const
const std::string & str () const
const char * c_str () const
Protected Types inherited from ret_val_common
template<typename S >
using is_convertible_to_string = std::enable_if_t< !std::is_same_v< S, std::nullptr_t > &&std::is_convertible_v< S, std::string > >
Protected Member Functions inherited from ret_val_common
ret_val_common (const std::string &msg, bool succ)
Detailed Description
Definition at line 103 of file ret_val.h.
Member Function Documentation
make_failure() [1/2]
static ret_val ret_val< void >::make_failure () inline static
Definition at line 110 of file ret_val.h.
{
             return make_failure( std::string() );
         }
References ret_val< T >::make_failure().
make_failure() [2/2]
template<class... A, typename S = std::string, typename = is_convertible_to_string<S>> static ret_val ret_val< void >::make_failure (const S & msg, A &&... args) inline static
Definition at line 120 of file ret_val.h.
{
             return ret_val( string_format( msg, std::forward<A>( args )... ), false );
         }
References ret_val_common::msg, ret_val< T >::ret_val(), and string_format().
make_success() [1/2]
static ret_val ret_val< void >::make_success () inline static
Definition at line 106 of file ret_val.h.
{
             return make_success( std::string() );
         }
References ret_val< T >::make_success().
make_success() [2/2]
template<class... A, typename S = std::string, typename = is_convertible_to_string<S>> static ret_val ret_val< void >::make_success (const S & msg, A &&... args) inline static
Definition at line 115 of file ret_val.h.
{
             return ret_val( string_format( msg, std::forward<A>( args )... ), true );
         }
References ret_val_common::msg, ret_val< T >::ret_val(), and string_format().
ret_val_common()
ret_val_common::ret_val_common inline private
Definition at line 30 of file ret_val.h.
             : msg( msg ), succ( succ )
         {}
The documentation for this class was generated from the following file:
src/ret_val.h