Cataclysm DDA: unpack_actor Class Reference
unpack_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
unpack_actor (const std::string &type="unpack")
~unpack_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *p, item &it, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &dump) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
item_group_id unpack_group
The itemgroup from which we unpack items from.
bool items_fit = false
Whether or not the items from the group should spawn fitting.
units::volume filthy_vol_threshold = 0_ml
If the item is filthy, at what volume (held) threshold should the items unpacked be made filthy.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 123 of file iuse_actor.h.
Constructor & Destructor Documentation
unpack_actor()
unpack_actor::unpack_actor (const std::string & type = "unpack") inline explicit
Definition at line 138 of file iuse_actor.h.
 : iuse_actor( type ) {}
~unpack_actor()
unpack_actor::~unpack_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > unpack_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 478 of file iuse_actor.cpp.
 {
     return std::make_unique<unpack_actor>( *this );
 }
info()
void unpack_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 525 of file iuse_actor.cpp.
 {
     dump.emplace_back( "DESCRIPTION",
                        _( "This item could be unpacked to receive something." ) );
 }
References _.
load()
void unpack_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 483 of file iuse_actor.cpp.
 {
     obj.read( "group", unpack_group );
     obj.read( "items_fit", items_fit );
     assign( obj, "filthy_volume_threshold", filthy_vol_threshold );
 }
References assign(), filthy_vol_threshold, items_fit, JsonObject::read(), and unpack_group.
use()
std::optional< int > unpack_actor::use (Character * p, item & it, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 490 of file iuse_actor.cpp.
 {
     std::vector<item> items = item_group::items_from( unpack_group, calendar::turn );
     item last_armor;
     p->add_msg_if_player( _( "You unpack the %s." ), it.tname() );
     map &here = get_map();
     for( item &content : items ) {
         if( content.is_armor() ) {
             if( items_fit ) {
                 content.set_flag( flag_FIT );
             } else if( content.typeId() == last_armor.typeId() ) {
                 if( last_armor.has_flag( flag_FIT ) ) {
                     content.set_flag( flag_FIT );
                 } else if( !last_armor.has_flag( flag_FIT ) ) {
                     content.unset_flag( flag_FIT );
                 }
             }
             last_armor = content;
         }
         if( content.get_total_capacity() >= filthy_vol_threshold &&
             it.has_flag( flag_FILTHY ) ) {
             content.set_flag( flag_FILTHY );
         }
         here.add_item_or_charges( p->pos(), content );
     }
     p->i_rem( &it );
     return 0;
 }
References _, map::add_item_or_charges(), Character::add_msg_if_player(), filthy_vol_threshold, flag_FILTHY, flag_FIT, get_map(), item::has_flag(), Character::i_rem(), items_fit, item_group::items_from(), Creature::pos(), item::set_flag(), item::tname(), calendar::turn, item::typeId(), and unpack_group.
Member Data Documentation
filthy_vol_threshold
units::volume unpack_actor::filthy_vol_threshold = 0_ml
If the item is filthy, at what volume (held) threshold should the items unpacked be made filthy.
Definition at line 136 of file iuse_actor.h.
Referenced by load(), and use().
items_fit
bool unpack_actor::items_fit = false
Whether or not the items from the group should spawn fitting.
Definition at line 130 of file iuse_actor.h.
Referenced by load(), and use().
unpack_group
item_group_id unpack_actor::unpack_group
The itemgroup from which we unpack items from.
Definition at line 127 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp