Cataclysm DDA: pimpl< T > Class Template Reference
pimpl< T > Class Template Reference
This is a wrapper for implementing the pointer-to-implementation technique, see for example http://en.cppreference.com/w/cpp/language/pimpl.
#include <pimpl.h>
Public Member Functions
pimpl ()
template<typename P , typename ... Args, typename = std::enable_if_t < !is_pimpl<P>::value >>
pimpl (P &&head, Args &&... args)
pimpl (const pimpl< T > &rhs)
pimpl (pimpl< T > &&rhs) noexcept
pimpl< T > & operator= (const pimpl< T > &rhs)
pimpl< T > & operator= (pimpl< T > &&rhs) noexcept
bool operator== (const pimpl< T > &rhs) const
void deserialize (const JsonValue &stream)
Forwards the stream to T::deserialize.
void serialize (JsonOut &stream) const
Forwards the stream to T::serialize.
Detailed Description
template<typename T>
class pimpl< T >
This is a wrapper for implementing the pointer-to-implementation technique, see for example http://en.cppreference.com/w/cpp/language/pimpl.
It's a container for one element of type T, which is always present (one can not create a pimpl instance without a contained T instance).
The contained T can be access like a pointer via operator-> and operator.
The constructor forwards all its arguments to the constructor of T.
Definition at line 37 of file pimpl.h.
Constructor & Destructor Documentation
pimpl() [1/4]
template<typename T > pimpl< T >::pimpl () inline explicit
Definition at line 44 of file pimpl.h.
 : std::unique_ptr<T>( new T() ) { }
pimpl() [2/4]
template<typename T > template<typename P , typename ... Args, typename = std::enable_if_t < !is_pimpl<P>::value >> pimpl< T >::pimpl (P && head, Args &&... args) inline explicit
Definition at line 47 of file pimpl.h.
                                    : std::unique_ptr<T>( new T( std::forward<P>( head ), std::forward<Args>( args )... ) ) { }
pimpl() [3/4]
template<typename T > pimpl< T >::pimpl (const pimpl< T > & rhs) inline
Definition at line 50 of file pimpl.h.
 : std::unique_ptr<T>( new T( *rhs ) ) { }
pimpl() [4/4]
template<typename T > pimpl< T >::pimpl (pimpl< T > && rhs) inline noexcept
Definition at line 51 of file pimpl.h.
 : std::unique_ptr<T>( new T( std::move( *rhs ) ) ) { }
Member Function Documentation
deserialize()
template<typename T > void pimpl< T >::deserialize (const JsonValue & stream) inline
Forwards the stream to T::deserialize.
Definition at line 70 of file pimpl.h.
{
             operator*().deserialize( stream );
         }
References time_duration::deserialize(), and operator*().
operator=() [1/2]
template<typename T > pimpl<T>& pimpl< T >::operator= (const pimpl< T > & rhs) inline
Definition at line 53 of file pimpl.h.
{
             operator*() = *rhs;
             return *this;
         }
References operator*().
operator=() [2/2]
template<typename T > pimpl<T>& pimpl< T >::operator= (pimpl< T > && rhs) inline noexcept
Definition at line 57 of file pimpl.h.
{
             operator*() = std::move( *rhs );
             return *this;
         }
References operator*().
operator==()
template<typename T > bool pimpl< T >::operator== (const pimpl< T > & rhs) const inline
Definition at line 62 of file pimpl.h.
{
             return operator*() == *rhs;
         }
References operator*().
serialize()
template<typename T > void pimpl< T >::serialize (JsonOut & stream) const inline
Forwards the stream to T::serialize.
Definition at line 74 of file pimpl.h.
{
             operator*().serialize( stream );
         }
References operator*(), and time_duration::serialize().
The documentation for this class was generated from the following file:
src/pimpl.h