Cataclysm DDA: vehicle_folding_activity_actor Class Reference
vehicle_folding_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
vehicle_folding_activity_actor (const vehicle &target)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &p) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &p) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &p) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
bool fold_vehicle (Character &p, bool check_only) const
vehicle_folding_activity_actor ()=default
Private Attributes
tripoint_bub_ms target_pos
time_duration folding_time
Detailed Description
Definition at line 1606 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
vehicle_folding_activity_actor() [1/2]
vehicle_folding_activity_actor::vehicle_folding_activity_actor () explicit private default
vehicle_folding_activity_actor() [2/2]
vehicle_folding_activity_actor::vehicle_folding_activity_actor (const vehicle & target) explicit
Definition at line 7422 of file activity_actor.cpp.
 {
     folding_time = target.folding_time();
     target_pos = target.bub_part_pos( 0 );
 }
References vehicle::bub_part_pos(), folding_time, vehicle::folding_time(), and target_pos.
Member Function Documentation
clone()
std::unique_ptr<activity_actor> vehicle_folding_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1631 of file activity_actor_definitions.h.
{
             return std::make_unique<vehicle_folding_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > vehicle_folding_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 7471 of file activity_actor.cpp.
 {
     vehicle_folding_activity_actor actor;
     JsonObject data = jsin.get_object();
     data.read( "target_pos", actor.target_pos );
     data.read( "folding_time", actor.folding_time );
     return actor.clone();
 }
References clone(), folding_time, JsonValue::get_object(), JsonObject::read(), and target_pos.
do_turn()
void vehicle_folding_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 7448 of file activity_actor.cpp.
 {
     if( calendar::once_every( 30_seconds ) ) {
         if( !fold_vehicle( p, /* check_only = */ true ) ) {
             act.set_to_null();
         }
     }
 }
References act, fold_vehicle(), and calendar::once_every().
finish()
void vehicle_folding_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 7457 of file activity_actor.cpp.
 {
     fold_vehicle( p, /* check_only = */ false );
     act.set_to_null();
 }
References act, and fold_vehicle().
fold_vehicle()
bool vehicle_folding_activity_actor::fold_vehicle (Character & p, bool check_only) const private
Definition at line 7370 of file activity_actor.cpp.
 {
     map &here = get_map();
     const optional_vpart_position vp = here.veh_at( target_pos );
     if( !vp ) {
         debugmsg( "Lost ACT_VEHICLE_FOLD target vehicle" );
         return false;
     }
     vehicle &veh = vp->vehicle();
     if( !veh.is_foldable() ) {
         p.add_msg_if_player( m_warning, _( "%s cannot be folded." ), veh.name );
         return false;
     }
     const inventory &inv = p.crafting_inventory();
     for( const vpart_reference &vp : veh.get_all_parts() ) {
         for( const itype_id &tool : vp.info().get_folding_tools() ) {
             if( !inv.has_tools( tool, 1 ) ) {
                 p.add_msg_if_player( _( "You need %s to do it!" ), item::nname( tool ) );
                 return false;
             }
         }
     }
     if( veh.velocity != 0 ) {
         p.add_msg_if_player( m_warning, _( "You can't fold the %s while it's in motion." ), veh.name );
         return false;
     }
     if( check_only ) {
         return true; // bail out early if we're just checking
     }
     // Drop cargo to ground
     // TODO: make cargo shuffling add time to activity
     for( const vpart_reference &vpr : veh.get_any_parts( VPFLAG_CARGO ) ) {
         vehicle_stack cargo = vpr.items();
         for( const item &elem : cargo ) {
             here.add_item_or_charges( veh.pos_bub(), elem );
         }
         cargo.clear();
     }
     veh.unboard_all();
     p.add_msg_if_player( _( "You fold the %s." ), veh.name );
     here.add_item_or_charges( veh.pos_bub(), veh.get_folded_item() );
     here.destroy_vehicle( &veh );
     return true;
 }
References _, map::add_item_or_charges(), Character::add_msg_if_player(), item_stack::clear(), Character::crafting_inventory(), debugmsg, map::destroy_vehicle(), vehicle::get_all_parts(), vehicle::get_any_parts(), vehicle::get_folded_item(), get_map(), read_only_visitable::has_tools(), vehicle::is_foldable(), item_stack::items, m_warning, vehicle::name, item::nname(), vehicle::pos_bub(), target_pos, vehicle::unboard_all(), map::veh_at(), vehicle::velocity, and VPFLAG_CARGO.
Referenced by do_turn(), finish(), and start().
get_type()
activity_id vehicle_folding_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1623 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_VEHICLE_FOLD" );
         }
References activity_id.
serialize()
void vehicle_folding_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 7463 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target_pos", target_pos );
     jsout.member( "folding_time", folding_time );
     jsout.end_object();
 }
References JsonOut::end_object(), folding_time, JsonOut::member(), JsonOut::start_object(), and target_pos.
start()
void vehicle_folding_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 7428 of file activity_actor.cpp.
 {
     avatar *pc = p.as_avatar();
     if( pc && pc->get_grab_type() == object_type::VEHICLE ) {
         optional_vpart_position grabbed_veh = get_map().veh_at( pc->pos_bub() + pc->grab_point );
         optional_vpart_position target_veh = get_map().veh_at( target_pos );
         if( grabbed_veh && target_veh && ( &grabbed_veh->vehicle() == &target_veh->vehicle() ) ) {
             pc->grab( object_type::NONE );
             pc->add_msg_if_player( _( "You let go of %s." ), grabbed_veh->vehicle().name );
         }
     }
     act.moves_total = to_moves<int>( folding_time );
     act.moves_left = to_moves<int>( folding_time );
     if( !fold_vehicle( p, /* check_only = */ true ) ) {
         act.set_to_null();
     }
 }
References _, act, Character::add_msg_if_player(), Creature::as_avatar(), fold_vehicle(), folding_time, avatar::get_grab_type(), get_map(), avatar::grab(), Character::grab_point, NONE, Creature::pos_bub(), target_pos, map::veh_at(), and VEHICLE.
Member Data Documentation
folding_time
time_duration vehicle_folding_activity_actor::folding_time private
Definition at line 1612 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), start(), and vehicle_folding_activity_actor().
target_pos
tripoint_bub_ms vehicle_folding_activity_actor::target_pos private
Definition at line 1610 of file activity_actor_definitions.h.
Referenced by deserialize(), fold_vehicle(), serialize(), start(), and vehicle_folding_activity_actor().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp