Cataclysm DDA: demo_ui Class Reference
demo_ui Class Reference
Public Member Functions
demo_ui ()
void init ()
void run ()
Public Member Functions inherited from cataimgui::window
window (const std::string &id_, int window_flags=0)
virtual ~window ()
void draw_colored_text (std::string const &text, const nc_color &color, float wrap_width=0.0F, bool *is_selected=nullptr, bool *is_focused=nullptr, bool *is_hovered=nullptr)
void draw_colored_text (std::string const &text, nc_color &color, float wrap_width=0.0F, bool *is_selected=nullptr, bool *is_focused=nullptr, bool *is_hovered=nullptr)
bool action_button (const std::string &action, const std::string &text)
A button tied to a string action.
bool has_button_action ()
std::string get_button_action ()
void draw_header (std::string const &text)
bool get_is_open () const
virtual void draw ()
bool is_bounds_changed ()
size_t get_text_width (const std::string &text)
size_t get_text_height (const char *text)
size_t str_width_to_pixels (size_t len)
size_t str_height_to_pixels (size_t len)
std::string get_filter ()
void clear_filter ()
void mark_resized ()
Protected Member Functions
void draw_controls () override
cataimgui::bounds get_bounds () override
void on_resized () override
Protected Member Functions inherited from cataimgui::window
window (int window_flags=0)
void draw_filter (const input_context &ctxt, bool filtering_active)
Additional Inherited Members
Protected Attributes inherited from cataimgui::window
bool force_to_back = false
bool is_open
std::string id
int window_flags
std::string button_action
Detailed Description
Definition at line 59 of file main_menu.cpp.
Constructor & Destructor Documentation
demo_ui()
demo_ui::demo_ui ()
Definition at line 74 of file main_menu.cpp.
                  : cataimgui::window( _( "ImGui Demo Screen" ) )
 {
 }
Member Function Documentation
draw_controls()
void demo_ui::draw_controls () override protected virtual
Implements cataimgui::window.
Definition at line 83 of file main_menu.cpp.
 {
     ImGui::ShowDemoWindow();
 }
get_bounds()
cataimgui::bounds demo_ui::get_bounds () override protected virtual
Reimplemented from cataimgui::window.
Definition at line 78 of file main_menu.cpp.
 {
     return { -1.f, -1.f, float( str_width_to_pixels( TERMX ) ), float( str_height_to_pixels( TERMY ) ) };
 }
References cataimgui::window::str_height_to_pixels(), cataimgui::window::str_width_to_pixels(), TERMX, and TERMY.
init()
void demo_ui::init ()
Definition at line 88 of file main_menu.cpp.
 {
     // The demo makes it's own screen.  Don't get in the way
     force_to_back = true;
 }
References cataimgui::window::force_to_back.
Referenced by on_resized(), and run().
on_resized()
void demo_ui::on_resized () inline override protected virtual
Reimplemented from cataimgui::window.
Definition at line 69 of file main_menu.cpp.
{
             init();
         };
References init().
run()
void demo_ui::run ()
Definition at line 94 of file main_menu.cpp.
 {
     init();
     input_context ctxt( "HELP_KEYBINDINGS" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "SELECT" );
     ctxt.register_action( "MOUSE_MOVE" );
     ctxt.register_action( "ANY_INPUT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     std::string action;
     ui_manager::redraw();
     while( is_open ) {
         ui_manager::redraw();
         action = ctxt.handle_input( 5 );
         if( action == "QUIT" ) {
             break;
         }
     }
 }
References action, input_context::handle_input(), init(), cataimgui::window::is_open, ui_manager::redraw(), and input_context::register_action().
Referenced by main_menu::opening_screen().
The documentation for this class was generated from the following file:
src/main_menu.cpp