Cataclysm DDA: learn_spell_actor Class Reference
learn_spell_actor Class Reference
Learn a spell.
#include <iuse_actor.h>
Public Member Functions
learn_spell_actor (const std::string &type="learn_spell")
~learn_spell_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *p, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::vector< std::string > spells
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Learn a spell.
Definition at line 687 of file iuse_actor.h.
Constructor & Destructor Documentation
learn_spell_actor()
learn_spell_actor::learn_spell_actor (const std::string & type = "learn_spell") inline explicit
Definition at line 693 of file iuse_actor.h.
 : iuse_actor( type ) {}
~learn_spell_actor()
learn_spell_actor::~learn_spell_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > learn_spell_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2255 of file iuse_actor.cpp.
 {
     return std::make_unique<learn_spell_actor>( *this );
 }
info()
void learn_spell_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 2265 of file iuse_actor.cpp.
 {
     std::string message;
     if( spells.size() == 1 ) {
         message = _( "This can teach you a spell." );
     } else {
         message = _( "This can teach you a number of spells." );
     }
     dump.emplace_back( "DESCRIPTION", message );
     dump.emplace_back( "DESCRIPTION", _( "Spells Contained:" ) );
     avatar &pc = get_avatar();
     for( const std::string &sp_id_str : spells ) {
         const spell_id sp_id( sp_id_str );
         std::string spell_text = sp_id->name.translated();
         if( sp_id->spell_class.is_valid() ) {
             spell_text = string_format( pgettext( "spell name, spell class", "%s, %s" ),
                                         spell_text, sp_id->spell_class->name() );
         }
         if( pc.has_trait( trait_ILLITERATE ) ) {
             dump.emplace_back( "SPELL", spell_text );
         } else {
             if( pc.magic->knows_spell( sp_id ) ) {
                 const spell sp = pc.magic->get_spell( sp_id );
                 spell_text += ": " + string_format( _( "Level %u" ), sp.get_level() );
                 if( sp.is_max_level( pc ) ) {
                     spell_text = string_format( _( "<color_light_green>%1$s (Max)</color>" ), spell_text );
                 } else {
                     spell_text = string_format( "<color_yellow>%s</color>", spell_text );
                 }
             } else {
                 if( pc.magic->can_learn_spell( pc, sp_id ) ) {
                     spell_text = string_format( "<color_light_blue>%s</color>", spell_text );
                 }
             }
             dump.emplace_back( "SPELL", spell_text );
         }
     }
 }
References _, get_avatar(), spell::get_level(), Character::has_trait(), spell::is_max_level(), string_id< T >::is_valid(), Character::magic, mapgen_defer::message, spell_type::name, mutation_branch::name(), pgettext, spell_type::spell_class, spells, string_format(), trait_ILLITERATE, and translation::translated().
load()
void learn_spell_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2260 of file iuse_actor.cpp.
 {
     spells = obj.get_string_array( "spells" );
 }
References JsonObject::get_string_array(), and spells.
use()
std::optional< int > learn_spell_actor::use (Character * p, item & , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 2304 of file iuse_actor.cpp.
 {
     if( p->fine_detail_vision_mod() > 4 ) {
         p->add_msg_if_player( _( "It's too dark to read." ) );
         return std::nullopt;
     }
     if( p->has_trait( trait_ILLITERATE ) ) {
         p->add_msg_if_player( _( "You can't read." ) );
         return std::nullopt;
     }
     std::vector<uilist_entry> uilist_initializer;
     uilist spellbook_uilist;
     spellbook_callback sp_cb;
     bool know_it_all = true;
     for( const std::string &sp_id_str : spells ) {
         const spell_id sp_id( sp_id_str );
         sp_cb.add_spell( sp_id );
         uilist_entry entry( sp_id.obj().name.translated() );
         if( p->magic->knows_spell( sp_id ) ) {
             const spell sp = p->magic->get_spell( sp_id );
             entry.ctxt = string_format( _( "Level %u" ), sp.get_level() );
             if( sp.is_max_level( *p ) ) {
                 entry.ctxt += _( " (Max)" );
                 entry.enabled = false;
             } else {
                 know_it_all = false;
             }
         } else {
             if( p->magic->can_learn_spell( *p, sp_id ) ) {
                 entry.ctxt = _( "Study to Learn" );
                 know_it_all = false;
             } else {
                 entry.ctxt = _( "Can't learn!" );
                 entry.enabled = false;
             }
         }
         uilist_initializer.emplace_back( entry );
     }
     if( know_it_all ) {
         add_msg( m_info, _( "You already know everything this could teach you." ) );
         return std::nullopt;
     }
     spellbook_uilist.entries = uilist_initializer;
     spellbook_uilist.w_height_setup = 24;
     spellbook_uilist.w_width_setup = 80;
     spellbook_uilist.callback = &sp_cb;
     spellbook_uilist.title = _( "Study a spell:" );
     spellbook_uilist.pad_left_setup = 38;
     spellbook_uilist.query();
     const int action = spellbook_uilist.ret;
     if( action < 0 ) {
         return std::nullopt;
     }
     const bool knows_spell = p->magic->knows_spell( spells[action] );
     player_activity study_spell( ACT_STUDY_SPELL,
                                  p->magic->time_to_learn_spell( *p, spells[action] ) );
     study_spell.str_values = {
         "", // reserved for "until you gain a spell level" option [0]
         "learn"
     }; // [1]
     study_spell.values = { 0, 0, 0 };
     if( knows_spell ) {
         study_spell.str_values[1] = "study";
         const int study_time = uilist( _( "Spend how long studying?" ), {
             { to_moves<int>( 30_minutes ), true, -1, _( "30 minutes" ) },
             { to_moves<int>( 1_hours ), true, -1, _( "1 hour" ) },
             { to_moves<int>( 2_hours ), true, -1, _( "2 hours" ) },
             { to_moves<int>( 4_hours ), true, -1, _( "4 hours" ) },
             { to_moves<int>( 8_hours ), true, -1, _( "8 hours" ) },
             { 10100, true, -1, _( "Until you gain a spell level" ) }
         } );
         if( study_time <= 0 ) {
             return std::nullopt;
         }
         study_spell.moves_total = study_time;
         spell &studying = p->magic->get_spell( spell_id( spells[action] ) );
         if( studying.get_difficulty( *p ) < static_cast<int>( p->get_skill_level( studying.skill() ) ) ) {
             p->handle_skill_warning( studying.skill(),
                                      true ); // show the skill warning on start reading, since we don't show it during
         }
     }
     study_spell.moves_left = study_spell.moves_total;
     if( study_spell.moves_total == 10100 ) {
         study_spell.str_values[0] = "gain_level";
         study_spell.values[0] = 0; // reserved for xp
         study_spell.values[1] = p->magic->get_spell( spell_id( spells[action] ) ).get_level() + 1;
     }
     study_spell.name = spells[action];
     p->assign_activity( study_spell );
     return 0;
 }
References _, ACT_STUDY_SPELL, action, add_msg(), Character::add_msg_if_player(), spellbook_callback::add_spell(), Character::assign_activity(), uilist::callback, uilist_entry::ctxt, uilist_entry::enabled, uilist::entries, Character::fine_detail_vision_mod(), spell::get_difficulty(), spell::get_level(), Character::get_skill_level(), Character::handle_skill_warning(), Character::has_trait(), spell::is_max_level(), m_info, Character::magic, player_activity::moves_left, player_activity::moves_total, spell_type::name, player_activity::name, string_id< T >::obj(), uilist::pad_left_setup, uilist::query(), uilist::ret, spell::skill(), spell_id, spells, player_activity::str_values, string_format(), uilist::title, trait_ILLITERATE, translation::translated(), player_activity::values, uilist::w_height_setup, and uilist::w_width_setup.
Member Data Documentation
spells
std::vector<std::string> learn_spell_actor::spells
Definition at line 691 of file iuse_actor.h.
Referenced by item::color_in_inventory(), info(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp