Cataclysm DDA: jmapgen_nested::predecessor_oter_check Class Reference
jmapgen_nested::predecessor_oter_check Class Reference
Public Member Functions
predecessor_oter_check (const JsonArray &jarr)
bool test (const mapgendata &dat) const
Private Attributes
cata::flat_set< std::pair< std::string, ot_match_type > > allowed_predecessors
Detailed Description
Definition at line 3686 of file mapgen.cpp.
Constructor & Destructor Documentation
predecessor_oter_check()
jmapgen_nested::predecessor_oter_check::predecessor_oter_check (const JsonArray & jarr) inline explicit
Definition at line 3691 of file mapgen.cpp.
{
                     for( const JsonValue entry : jarr ) {
                         std::pair<std::string, ot_match_type> allowed_predecessor;
                         if( entry.test_string() ) {
                             allowed_predecessor.first = entry.get_string();
                             allowed_predecessor.second = ot_match_type::contains;
                         } else {
                             JsonObject jo = entry.get_object();
                             allowed_predecessor.first = jo.get_string( "om_terrain" );
                             allowed_predecessor.second = jo.get_enum_value<ot_match_type>( "om_terrain_match_type",
                                                          ot_match_type::contains );
                         }
                         allowed_predecessors.insert( allowed_predecessor );
                     }
                 }
References allowed_predecessors, contains, JsonObject::get_enum_value(), JsonObject::get_object(), JsonObject::get_string(), and cata::flat_set< T, Compare, Data >::insert().
Member Function Documentation
test()
bool jmapgen_nested::predecessor_oter_check::test (const mapgendata & dat) const inline
Definition at line 3707 of file mapgen.cpp.
{
                     const std::vector<oter_id> predecessors = dat.get_predecessors();
                     for( const std::pair<std::string, ot_match_type> &allowed_predecessor : allowed_predecessors ) {
                         for( const oter_id &predecessor : predecessors ) {
                             if( is_ot_match( allowed_predecessor.first, predecessor, allowed_predecessor.second ) ) {
                                 return true;
                             }
                         }
                     }
                     return allowed_predecessors.empty();
                 }
References allowed_predecessors, mapgendata::get_predecessors(), is_ot_match(), and jmapgen_nested::predecessors.
Referenced by jmapgen_nested::get_entries().
Member Data Documentation
allowed_predecessors
cata::flat_set<std::pair<std::string, ot_match_type> > jmapgen_nested::predecessor_oter_check::allowed_predecessors private
Definition at line 3689 of file mapgen.cpp.
Referenced by predecessor_oter_check(), and test().
The documentation for this class was generated from the following file:
src/mapgen.cpp