Cataclysm DDA: mission Class Reference
mission Class Reference
#include <mission.h>
Public Types
enum class mission_status : int {
yet_to_start , in_progress , success , failure ,
num_mission_status
}
Public Member Functions
std::string name () const
mission_type_id mission_id () const
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
mission ()
bool has_deadline () const
Getters, they mostly return the member directly, mostly.
time_point get_deadline () const
std::string get_description () const
bool has_target () const
const tripoint_abs_omt & get_target () const
const mission_type & get_type () const
bool has_follow_up () const
mission_type_id get_follow_up () const
int get_value () const
int get_id () const
const itype_id & get_item_id () const
character_id get_npc_id () const
const talk_effect_fun_t::likely_rewards_t & get_likely_rewards () const
bool has_generic_rewards () const
void register_kill_needed ()
bool is_assigned () const
Whether the mission is assigned to a player character.
character_id get_assigned_player_id () const
To which player the mission is assigned.
void set_target (const tripoint_abs_omt &p)
Simple setters, no checking if the values is performed.
void set_target_npc_id (const character_id &npc_id)
void set_assigned_player_id (const character_id &char_id)
void update_world_missions_character (const character_id &old_char_id, const character_id &new_char_id)
void assign (avatar &u)
Assigns the mission to the player.
void fail ()
Called when the mission has failed, calls the mission fail callback.
void wrap_up ()
Handles mission completion tasks (remove given item, etc.).
void step_complete (int step)
Handles partial mission completion (kill complete, now report back!).
bool is_complete (const character_id &npc_id) const
Checks if the player has completed the matching mission and returns true if they have.
bool has_failed () const
Checks if the player has failed the matching mission and returns true if they have.
bool in_progress () const
Checks if the mission is started, but not failed and not succeeded.
void process ()
Processes this mission.
void on_talk_with_npc (const character_id &npc_id)
Called when the player talks with an NPC.
std::string dialogue_for_topic (const std::string &topic) const
void remove_active_world_mission (mission &cur_mission)
Static Public Member Functions
static mission * reserve_new (const mission_type_id &type, const character_id &npc_id)
Create a new mission of the given type and assign it to the given npc.
static mission * reserve_random (mission_origin origin, const tripoint_abs_omt &p, const character_id &npc_id)
static mission * find (int id, bool ok_missing=false)
Returns the mission with the matching id (uid).
static void clear_all ()
Remove all active missions, used to cleanup on exit and before reloading a new game.
static void process_all ()
Handles mission deadline processing.
static void on_creature_death (Creature &poor_dead_dude)
various callbacks from events that may affect all missions
static bool on_creature_fusion (Creature &fuser, Creature &fused)
static void serialize_all (JsonOut &json)
static void unserialize_all (const JsonArray &ja)
static std::vector< mission * > to_ptr_vector (const std::vector< int > &vec, bool ok_missing=false)
Converts a vector mission ids to a vector of mission pointers.
static std::vector< int > to_uid_vector (const std::vector< mission * > &vec)
static std::vector< mission * > get_all_active ()
static void add_existing (const mission &m)
static mission_status status_from_string (const std::string &s)
static std::string status_to_string (mission_status st)
Private Member Functions
void set_target_to_mission_giver ()
Static Private Member Functions
static void get_all_item_group_matches (std::vector< item * > &items, item_group_id &grp_type, std::map< itype_id, int > &matches, const itype_id &required_container, const itype_id &actual_container, bool &specific_container_required)
Private Attributes
const mission_type * type
mission_status status
unsigned int value
npc_favor reward
int uid
tripoint_abs_omt target
itype_id item_id
int item_count = 0
string_id< oter_type_t > target_id
npc_class_id recruit_class
character_id target_npc_id
mtype_id monster_type
species_id monster_species
int monster_kill_goal = 0
int kill_count_to_reach = 0
time_point deadline
character_id npc_id
int good_fac_id = 0
int bad_fac_id = 0
int step = 0
mission_type_id follow_up
character_id player_id
Friends
struct mission_type
struct mission_start
class debug_menu::mission_debug
Detailed Description
Definition at line 272 of file mission.h.
Member Enumeration Documentation
mission_status
enum mission::mission_status : int strong
Enumerator
yet_to_start
in_progress
success
failure
num_mission_status
Definition at line 275 of file mission.h.
                                   : int {
             yet_to_start,
             in_progress,
             success,
             failure,
             num_mission_status
         };
Constructor & Destructor Documentation
mission()
mission::mission ()
Definition at line 870 of file mission.cpp.
     : deadline( 0 )
 {
     type = nullptr;
     status = mission_status::yet_to_start;
     value = 0;
     uid = -1;
     target = tripoint_abs_omt( tripoint_min );
     item_id = itype_id::NULL_ID();
     item_count = 1;
     target_id = string_id<oter_type_t>::NULL_ID();
     recruit_class = NC_NONE;
     target_npc_id = character_id();
     monster_type = mtype_id::NULL_ID();
     monster_kill_goal = -1;
     npc_id = character_id();
     good_fac_id = -1;
     bad_fac_id = -1;
     step = 0;
     player_id = character_id();
 }
References bad_fac_id, character_id, good_fac_id, item_count, item_id, monster_kill_goal, monster_type, NC_NONE, npc_id, string_id< T >::NULL_ID(), string_id< itype >::NULL_ID(), string_id< mtype >::NULL_ID(), player_id, recruit_class, status, step, target, target_id, target_npc_id, tripoint_min, type, uid, value, and yet_to_start.
Member Function Documentation
add_existing()
void mission::add_existing (const mission & m) static
Definition at line 121 of file mission.cpp.
 {
     world_missions[ m.uid ] = m;
 }
References uid, and world_missions.
Referenced by unserialize_all().
assign()
void mission::assign (avatar & u)
Assigns the mission to the player.
Definition at line 301 of file mission.cpp.
 {
     if( player_id == u.getID() ) {
         debugmsg( "strange: player is already assigned to mission %d", uid );
         return;
     }
     if( player_id.is_valid() ) {
         debugmsg( "tried to assign mission %d to player, but mission is already assigned to %d",
                   uid, player_id.get_value() );
         return;
     }
     player_id = u.getID();
     u.on_mission_assignment( *this );
     if( status == mission_status::yet_to_start ) {
         const kill_tracker &kills = g->get_kill_tracker();
         if( type->goal == MGOAL_KILL_MONSTER_TYPE && monster_type != mtype_id::NULL_ID() ) {
             kill_count_to_reach = kills.kill_count( monster_type ) + monster_kill_goal;
         } else if( type->goal == MGOAL_KILL_MONSTER_SPEC ) {
             kill_count_to_reach = kills.kill_count( monster_species ) + monster_kill_goal;
         }
         if( type->deadline_low != 0_turns || type->deadline_high != 0_turns ) {
             deadline = calendar::turn + rng( type->deadline_low, type->deadline_high );
         } else {
             deadline = calendar::turn_zero;
         }
         type->start( this );
         status = mission_status::in_progress;
     }
 }
References deadline, mission_type::deadline_high, mission_type::deadline_low, debugmsg, g, character_id::get_value(), mission_type::goal, in_progress, character_id::is_valid(), kill_tracker::kill_count(), kill_count_to_reach, MGOAL_KILL_MONSTER_SPEC, MGOAL_KILL_MONSTER_TYPE, monster_kill_goal, monster_species, monster_type, string_id< mtype >::NULL_ID(), player_id, rng(), mission_type::start, status, calendar::turn, calendar::turn_zero, type, u, uid, and yet_to_start.
Referenced by computer_session::action_emerg_ref_center(), talker_npc::add_mission(), talk_function::assign_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_mission(), talk_function::lead_to_safety(), and game::start_game().
clear_all()
void mission::clear_all () static
Remove all active missions, used to cleanup on exit and before reloading a new game.
Definition at line 155 of file mission.cpp.
 {
     world_missions.clear();
 }
References world_missions.
Referenced by game::setup().
deserialize()
void mission::deserialize (const JsonObject & jo)
Definition at line 3555 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     if( jo.has_int( "type_id" ) ) {
         type = &mission_type::from_legacy( jo.get_int( "type_id" ) ).obj();
     } else if( jo.has_string( "type_id" ) ) {
         type = &mission_type_id( jo.get_string( "type_id" ) ).obj();
     } else {
         debugmsg( "Saved mission has no type" );
         type = &mission_type::get_all().front();
     }
     bool failed;
     bool was_started;
     std::string status_string;
     if( jo.read( "status", status_string ) ) {
         status = status_from_string( status_string );
     } else if( jo.read( "failed", failed ) && failed ) {
         status = mission_status::failure;
     } else if( jo.read( "was_started", was_started ) && !was_started ) {
         status = mission_status::yet_to_start;
     } else {
         // Note: old code had no idea of successful missions!
         // We can't check properly here, since most of the game isn't loaded
         status = mission_status::in_progress;
     }
     jo.read( "value", value );
     jo.read( "kill_count_to_reach", kill_count_to_reach );
     jo.read( "reward", reward );
     jo.read( "uid", uid );
     JsonArray ja = jo.get_array( "target" );
     if( ja.size() == 3 ) {
         target.x() = ja.get_int( 0 );
         target.y() = ja.get_int( 1 );
         target.z() = ja.get_int( 2 );
     } else if( ja.size() == 2 ) {
         target.x() = ja.get_int( 0 );
         target.y() = ja.get_int( 1 );
     }
     if( jo.has_int( "follow_up" ) ) {
         follow_up = mission_type::from_legacy( jo.get_int( "follow_up" ) );
     } else if( jo.has_string( "follow_up" ) ) {
         follow_up = mission_type_id( jo.get_string( "follow_up" ) );
     }
     jo.read( "item_id", item_id );
     const std::string omid = jo.get_string( "target_id", "" );
     if( !omid.empty() ) {
         target_id = string_id<oter_type_t>( omid );
     }
     if( jo.has_int( "recruit_class" ) ) {
         recruit_class = npc_class::from_legacy_int( jo.get_int( "recruit_class" ) );
     } else {
         recruit_class = npc_class_id( jo.get_string( "recruit_class", "NC_NONE" ) );
     }
     jo.read( "target_npc_id", target_npc_id );
     jo.read( "monster_type", monster_type );
     jo.read( "monster_species", monster_species );
     jo.read( "monster_kill_goal", monster_kill_goal );
     jo.read( "deadline", deadline );
     jo.read( "step", step );
     jo.read( "item_count", item_count );
     jo.read( "npc_id", npc_id );
     jo.read( "good_fac_id", good_fac_id );
     jo.read( "bad_fac_id", bad_fac_id );
     jo.read( "player_id", player_id );
 }
References JsonObject::allow_omitted_members(), debugmsg, failed, mission_type::from_legacy(), npc_class::from_legacy_int(), mission_type::get_all(), JsonObject::get_array(), JsonArray::get_int(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_int(), JsonObject::has_string(), string_id< T >::obj(), JsonObject::read(), JsonArray::size(), status, and type.
Referenced by unserialize_all().
dialogue_for_topic()
std::string mission::dialogue_for_topic (const std::string & topic) const
Definition at line 840 of file mission.cpp.
 {
     // The internal keys are pretty ugly, it's better to translate them here than globally
     static const std::map<std::string, std::string> topic_translation = {{
             { "TALK_MISSION_DESCRIBE", "describe" },
             { "TALK_MISSION_DESCRIBE_URGENT", "describe" },
             { "TALK_MISSION_OFFER", "offer" },
             { "TALK_MISSION_ACCEPTED", "accepted" },
             { "TALK_MISSION_REJECTED", "rejected" },
             { "TALK_MISSION_ADVICE", "advice" },
             { "TALK_MISSION_INQUIRE", "inquire" },
             { "TALK_MISSION_SUCCESS", "success" },
             { "TALK_MISSION_SUCCESS_LIE", "success_lie" },
             { "TALK_MISSION_FAILURE", "failure" }
         }
     };
     const auto &replacement = topic_translation.find( in_topic );
     const std::string &topic = replacement != topic_translation.end() ? replacement->second : in_topic;
     const auto &response = type->dialogue.find( topic );
     if( response != type->dialogue.end() ) {
         return response->second.translated();
     }
     debugmsg( "Someone forgot to code this message id is %s, topic is %s!",
               type->id.c_str(), topic.c_str() );
     return "";
 }
References string_id< T >::c_str(), debugmsg, mission_type::dialogue, mission_type::id, replacement, and type.
Referenced by dialogue::dynamic_line().
fail()
void mission::fail ()
Called when the mission has failed, calls the mission fail callback.
Definition at line 331 of file mission.cpp.
 {
     status = mission_status::failure;
     avatar &player_character = get_avatar();
     if( player_character.getID() == player_id ) {
         player_character.on_mission_finished( *this );
     }
     type->fail( this );
 }
References mission_type::fail, failure, get_avatar(), Character::getID(), avatar::on_mission_finished(), player_id, status, and type.
Referenced by debug_menu::mission_debug::edit_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_function::mission_failure(), on_creature_death(), and process().
find()
mission * mission::find (int id, bool ok_missing = false) static
Returns the mission with the matching id (uid).
Returns NULL if no mission with that id exists.
Definition at line 87 of file mission.cpp.
 {
     const auto iter = world_missions.find( id );
     if( iter != world_missions.end() ) {
         return &iter->second;
     }
     if( !ok_missing ) {
         dbg( D_ERROR ) << "requested mission with uid " << id << " does not exist";
         debugmsg( "requested mission with uid %d does not exist", id );
     }
     return nullptr;
 }
References D_ERROR, dbg, debugmsg, and world_missions.
Referenced by computer_session::action_download_software(), dialogue_chatbin::deserialize(), avatar::load(), diary::mission_changes(), on_creature_death(), on_creature_fusion(), map::spawn_monsters_submap(), and to_ptr_vector().
get_all_active()
std::vector< mission * > mission::get_all_active () static
Definition at line 100 of file mission.cpp.
 {
     std::vector<mission *> ret;
     ret.reserve( world_missions.size() );
     for( auto &pr : world_missions ) {
         ret.push_back( &pr.second );
     }
     return ret;
 }
References cata::hash64_detail::ret, and world_missions.
Referenced by serialize_all().
get_all_item_group_matches()
void mission::get_all_item_group_matches (std::vector< item * > & items, item_group_id & grp_type, std::map< itype_id, int > & matches, const itype_id & required_container, const itype_id & actual_container, bool & specific_container_required) static private
Definition at line 648 of file mission.cpp.
 {
     for( item *itm : items ) {
         bool correct_container = ( required_container == actual_container ) ||
                                  !specific_container_required;
         bool item_in_group = item_group::group_contains_item( grp_type, itm->typeId() );
         //check whether item itself is target
         if( item_in_group && correct_container ) {
             std::map<itype_id, int>::iterator it = matches.find( itm->typeId() );
             if( it != matches.end() ) {
                 it->second = ( it->second ) + 1;
             } else {
                 matches.insert( std::make_pair( itm->typeId(), 1 ) );
             }
         }
         //recursively check item contents for target
         if( itm->is_container() && !itm->is_container_empty() ) {
             std::list<item *> content_list = itm->all_items_top();
             std::vector<item *> content = std::vector<item *>();
             //list of item into list item*
             std::transform(
                 content_list.begin(), content_list.end(),
                 std::back_inserter( content ),
             []( item * p ) {
                 return p;
             } );
             get_all_item_group_matches(
                 content, grp_type, matches,
                 required_container, itm->typeId(), specific_container_required );
         }
     }
 }
References item_group::group_contains_item().
Referenced by is_complete(), and wrap_up().
get_assigned_player_id()
character_id mission::get_assigned_player_id () const
To which player the mission is assigned.
It returns the id (player::getID) of the player.
Definition at line 819 of file mission.cpp.
 {
     return player_id;
 }
References player_id.
Referenced by talker_npc::get_topics(), is_complete(), talk_function::start_training_gen(), avatar::talk_to(), and talk_effect_t::update_missions().
get_deadline()
time_point mission::get_deadline () const
Definition at line 694 of file mission.cpp.
 {
     return deadline;
 }
References deadline.
Referenced by mission_ui_impl::draw_selected_description().
get_description()
std::string mission::get_description () const
Definition at line 699 of file mission.cpp.
 {
     return type->description.translated();
 }
References mission_type::description, translation::translated(), and type.
Referenced by mission_ui_impl::draw_selected_description(), and diary::mission_changes().
get_follow_up()
mission_type_id mission::get_follow_up () const
Definition at line 729 of file mission.cpp.
 {
     return follow_up;
 }
References follow_up.
Referenced by talk_function::clear_mission().
get_id()
int mission::get_id () const
Definition at line 739 of file mission.cpp.
 {
     return uid;
 }
References uid.
Referenced by jmapgen_monster::apply(), jmapgen_computer::apply(), create_lab_consoles(), mission_start::place_npc_software(), and remove_active_world_mission().
get_item_id()
const itype_id & mission::get_item_id () const
Definition at line 744 of file mission.cpp.
 {
     return item_id;
 }
References item_id.
Referenced by computer_session::action_download_software().
get_likely_rewards()
const talk_effect_fun_t::likely_rewards_t & mission::get_likely_rewards () const
Definition at line 777 of file mission.cpp.
 {
     return type->likely_rewards;
 }
References mission_type::likely_rewards, and type.
Referenced by mission_ui_impl::draw_selected_description().
get_npc_id()
character_id mission::get_npc_id () const
Definition at line 772 of file mission.cpp.
 {
     return npc_id;
 }
References npc_id.
Referenced by mission_ui_impl::draw_selected_description(), get_mission_om_origin(), mission_type::parse_funcs(), reveal_route(), and reveal_target().
get_target()
const tripoint_abs_omt & mission::get_target () const
Definition at line 709 of file mission.cpp.
 {
     return target;
 }
References target.
Referenced by computer_session::action_emerg_ref_center(), overmap_ui::draw_om_sidebar(), mission_ui_impl::draw_selected_description(), avatar::get_active_mission_target(), talk_function::lead_to_safety(), and mission_util::set_update_mapgen().
get_type()
const mission_type & mission::get_type () const
Definition at line 714 of file mission.cpp.
 {
     if( type == nullptr ) {
         debugmsg( "Null mission type" );
         return mission_type::get_all().front();
     }
     return *type;
 }
References debugmsg, mission_type::get_all(), and type.
Referenced by computer_session::action_emerg_ref_center(), dialogue::dynamic_line(), conditional_fun::anonymous_namespace{condition.cpp}::f_mission_goal(), dialogue::gen_responses(), talker_npc::get_topics(), avatar::on_mission_finished(), npc::regen_ai_cache(), and map::spawn_monsters_submap().
get_value()
int mission::get_value () const
Definition at line 734 of file mission.cpp.
 {
     return value;
 }
References value.
Referenced by talk_effect_t::apply(), npc::assigned_missions_value(), talk_function::mission_reward(), and talk_function::mission_success().
has_deadline()
bool mission::has_deadline () const
Getters, they mostly return the member directly, mostly.
Definition at line 689 of file mission.cpp.
 {
     return deadline != calendar::turn_zero;
 }
References deadline, and calendar::turn_zero.
Referenced by mission_ui_impl::draw_selected_description(), and process().
has_failed()
bool mission::has_failed () const
Checks if the player has failed the matching mission and returns true if they have.
Definition at line 749 of file mission.cpp.
 {
     return status == mission_status::failure;
 }
References failure, and status.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_mission_failed(), and avatar::on_mission_finished().
has_follow_up()
bool mission::has_follow_up () const
Definition at line 724 of file mission.cpp.
 {
     return !follow_up.is_null();
 }
References follow_up, and string_id< T >::is_null().
Referenced by talk_function::clear_mission(), and dialogue::dynamic_line().
has_generic_rewards()
bool mission::has_generic_rewards () const
Definition at line 782 of file mission.cpp.
 {
     return type->has_generic_rewards;
 }
References mission_type::has_generic_rewards, and type.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_mission_has_generic_rewards().
has_target()
bool mission::has_target () const
Definition at line 704 of file mission.cpp.
 {
     return target != overmap::invalid_tripoint;
 }
References overmap::invalid_tripoint, and target.
Referenced by mission_ui_impl::draw_selected_description().
in_progress()
bool mission::in_progress () const
Checks if the mission is started, but not failed and not succeeded.
Definition at line 754 of file mission.cpp.
 {
     return status == mission_status::in_progress;
 }
References in_progress, and status.
Referenced by on_creature_death(), and process().
is_assigned()
bool mission::is_assigned () const
Whether the mission is assigned to a player character.
If not, the mission is free and can be assigned.
Definition at line 814 of file mission.cpp.
 {
     return player_id.is_valid();
 }
References character_id::is_valid(), and player_id.
Referenced by talk_function::assign_mission().
is_complete()
bool mission::is_complete (const character_id & npc_id) const
Checks if the player has completed the matching mission and returns true if they have.
Definition at line 467 of file mission.cpp.
 {
     if( status == mission_status::success ) {
         return true;
     }
     avatar &player_character = get_avatar();
     switch( type->goal ) {
         case MGOAL_GO_TO: {
             const tripoint_abs_omt cur_pos = player_character.global_omt_location();
             return rl_dist( cur_pos, target ) <= 1;
         }
         case MGOAL_GO_TO_TYPE: {
             const oter_id cur_ter = overmap_buffer.ter( player_character.global_omt_location() );
             return ( cur_ter->get_type_id() == oter_type_str_id( type->target_id.str() ) );
         }
         case MGOAL_FIND_ITEM_GROUP: {
             inventory tmp_inv = player_character.crafting_inventory();
             std::vector<item *> items = std::vector<item *>();
             tmp_inv.dump( items );
             item_group_id grp_type = type->group_id;
             itype_id container = type->container_id;
             bool specific_container_required = !container.is_null();
             std::map<itype_id, int> matches = std::map<itype_id, int>();
             get_all_item_group_matches(
                 items, grp_type, matches,
                 container, itype_null, specific_container_required );
             int total_match = std::accumulate( matches.begin(), matches.end(), 0,
             []( const std::size_t previous, const std::pair<const itype_id, std::size_t> &p ) {
                 return static_cast<int>( previous + p.second );
             } );
             if( total_match >= ( type->item_count ) ) {
                 return true;
             }
         }
         return false;
         case MGOAL_FIND_ITEM: {
             if( npc_id.is_valid() && npc_id != _npc_id ) {
                 return false;
             }
             if( player_character.activity ) {
                 return false;
             }
             item item_sought( type->item_id );
             map &here = get_map();
             int found_quantity = 0;
             bool charges = item_sought.count_by_charges();
             bool software = item_sought.is_software();
             auto count_items = [this, &found_quantity, &player_character, charges, software]( item_stack &&
             items ) {
                 for( const item &i : items ) {
                     if( !i.is_owned_by( player_character, true ) ) {
                         continue;
                     }
                     if( software ) {
                         for( const item *soft : i.softwares() ) {
                             if( soft->typeId() == type->item_id ) {
                                 found_quantity ++;
                             }
                         }
                     }
                     if( charges ) {
                         found_quantity += i.charges_of( type->item_id, item_count - found_quantity );
                     } else {
                         found_quantity += i.amount_of( type->item_id, false, item_count - found_quantity );
                     }
                 }
             };
             for( const tripoint &p : here.points_in_radius( player_character.pos(), 5 ) ) {
                 if( player_character.sees( p ) ) {
                     if( here.has_items( p ) && here.accessible_items( p ) ) {
                         count_items( here.i_at( p ) );
                     }
                     if( const std::optional<vpart_reference> ovp = here.veh_at( p ).cargo() ) {
                         count_items( ovp->items() );
                     }
                     if( found_quantity >= item_count ) {
                         break;
                     }
                 }
             }
             if( software ) {
                 found_quantity += player_character.count_softwares( type->item_id );
             }
             if( charges ) {
                 return player_character.charges_of( type->item_id ) + found_quantity >= item_count;
             } else {
                 return player_character.amount_of( type->item_id ) + found_quantity >= item_count;
             }
         }
         return true;
         case MGOAL_FIND_ANY_ITEM:
             return player_character.has_mission_item( uid ) && ( !npc_id.is_valid() || npc_id == _npc_id );
         case MGOAL_FIND_MONSTER:
             if( npc_id.is_valid() && npc_id != _npc_id ) {
                 return false;
             }
             return g->get_creature_if( [&]( const Creature & critter ) {
                 const monster *const mon_ptr = dynamic_cast<const monster *>( &critter );
                 return mon_ptr && mon_ptr->mission_ids.count( uid );
             } );
         case MGOAL_RECRUIT_NPC: {
             npc *p = g->find_npc( target_npc_id );
             return p != nullptr && p->get_attitude() == NPCATT_FOLLOW;
         }
         case MGOAL_RECRUIT_NPC_CLASS: {
             const auto npcs = overmap_buffer.get_npcs_near_player( 100 );
             for( const auto &npc : npcs ) {
                 if( npc->myclass == recruit_class && npc->get_attitude() == NPCATT_FOLLOW ) {
                     return true;
                 }
             }
             return false;
         }
         case MGOAL_FIND_NPC:
             return npc_id == _npc_id;
         case MGOAL_TALK_TO_NPC:
         case MGOAL_ASSASSINATE:
         case MGOAL_KILL_MONSTER:
         case MGOAL_KILL_MONSTERS:
         case MGOAL_KILL_NEMESIS:
         case MGOAL_COMPUTER_TOGGLE:
             return step >= 1;
         case MGOAL_KILL_MONSTER_TYPE:
             return g->get_kill_tracker().kill_count( monster_type ) >= kill_count_to_reach;
         case MGOAL_KILL_MONSTER_SPEC:
             return g->get_kill_tracker().kill_count( monster_species ) >= kill_count_to_reach;
         case MGOAL_CONDITION: {
             std::unique_ptr<talker> beta;
             std::vector<mission *> miss;
             // Skip the NPC check if the mission was obtained via a scenario/profession/hobby
             if( npc_id.is_valid() || type->origins.empty() || type->origins.size() != 1 ||
                 type->origins.front() != mission_origin::ORIGIN_GAME_START ) {
                 // Only allow completing when talking to the mission originator.
                 if( npc_id != _npc_id ) {
                     return false;
                 }
                 npc *n = g->find_npc( _npc_id );
                 if( n == nullptr ) {
                     return false;
                 }
                 beta = get_talker_for( *n );
                 for( mission *&mission : n->chatbin.missions_assigned ) {
                     if( mission->get_assigned_player_id() == player_character.getID() ) {
                         miss.emplace_back( mission );
                     }
                 }
             } else {
                 for( mission *&mission : player_character.get_active_missions() ) {
                     if( mission->type->id == type->id ) {
                         miss.emplace_back( mission );
                     }
                 }
             }
             dialogue cc( get_talker_for( player_character ), std::move( beta ) );
             cc.missions_assigned = std::move( miss );
             return type->test_goal_condition( cc );
         }
         default:
             return false;
     }
 }
References map::accessible_items(), Character::activity, optional_vpart_position::cargo(), npc::chatbin, mission_type::container_id, item::count_by_charges(), Character::crafting_inventory(), inventory::dump(), g, avatar::get_active_missions(), get_all_item_group_matches(), get_assigned_player_id(), npc::get_attitude(), get_avatar(), get_map(), overmapbuffer::get_npcs_near_player(), get_talker_for(), oter_t::get_type_id(), Character::getID(), Creature::global_omt_location(), mission_type::goal, mission_type::group_id, map::has_items(), Character::has_mission_item(), map::i_at(), mission_type::id, string_id< T >::is_null(), item::is_software(), character_id::is_valid(), mission_type::item_count, item_count, mission_type::item_id, itype_null, kill_count_to_reach, MGOAL_ASSASSINATE, MGOAL_COMPUTER_TOGGLE, MGOAL_CONDITION, MGOAL_FIND_ANY_ITEM, MGOAL_FIND_ITEM, MGOAL_FIND_ITEM_GROUP, MGOAL_FIND_MONSTER, MGOAL_FIND_NPC, MGOAL_GO_TO, MGOAL_GO_TO_TYPE, MGOAL_KILL_MONSTER, MGOAL_KILL_MONSTER_SPEC, MGOAL_KILL_MONSTER_TYPE, MGOAL_KILL_MONSTERS, MGOAL_KILL_NEMESIS, MGOAL_RECRUIT_NPC, MGOAL_RECRUIT_NPC_CLASS, MGOAL_TALK_TO_NPC, monster::mission_ids, dialogue::missions_assigned, dialogue_chatbin::missions_assigned, monster_species, monster_type, npc::myclass, npc_id, NPCATT_FOLLOW, ORIGIN_GAME_START, mission_type::origins, overmap_buffer, map::points_in_radius(), recruit_class, rl_dist(), item::softwares(), status, step, string_id< T >::str(), success, target, mission_type::target_id, target_npc_id, overmapbuffer::ter(), mission_type::test_goal_condition(), type, uid, and map::veh_at().
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_mission_complete(), conditional_fun::anonymous_namespace{condition.cpp}::f_mission_incomplete(), process(), npc::regen_ai_cache(), and talk_function::start_training_gen().
mission_id()
mission_type_id mission::mission_id () const
Definition at line 832 of file mission.cpp.
 {
     if( type == nullptr ) {
         return mission_NULL;
     }
     return type->id;
 }
References mission_type::id, mission_NULL, and type.
Referenced by talk_function::assign_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_active_mission(), avatar::on_mission_finished(), avatar::remove_active_mission(), and avatar::set_active_mission().
name()
std::string mission::name () const
Definition at line 824 of file mission.cpp.
 {
     if( type == nullptr ) {
         return "NULL";
     }
     return type->tname();
 }
References mission_type::tname(), and type.
Referenced by overmap_ui::draw_om_sidebar(), mission_ui_impl::draw_selected_description(), diary::mission_changes(), and avatar::on_mission_finished().
on_creature_death()
void mission::on_creature_death (Creature & poor_dead_dude) static
various callbacks from events that may affect all missions
Definition at line 160 of file mission.cpp.
 {
     if( poor_dead_dude.is_hallucination() ) {
         return;
     }
     monster *mon = dynamic_cast<monster *>( &poor_dead_dude );
     if( mon != nullptr ) {
         if( mon->is_nemesis() ) {
             //the nemesis monster doesn't have a mission attached bc it's an overmap horde
             //so we loop to find the appropriate mission and complete it
             avatar &player_character = get_avatar();
             for( std::pair<const int, mission> &e : world_missions ) {
                 mission &i = e.second;
                 if( i.type->monster_kill_goal == 1 ) {
                     if( i.type->goal == MGOAL_KILL_NEMESIS && player_character.getID() == i.player_id ) {
                         i.step_complete( 1 );
                         return;
                     }
                 } else {
                     // Recurring nemesis!!
                     mission_start::kill_nemesis( &i );
                 }
             }
         }
         if( mon->mission_ids.empty() ) {
             return;
         }
         for( const int mission_id : mon->mission_ids ) {
             mission *found_mission = mission::find( mission_id );
             if( !found_mission ) {
                 debugmsg( "invalid mission id %d", mission_id );
                 continue;
             }
             const mission_type *type = found_mission->type;
             if( type->goal == MGOAL_FIND_MONSTER ) {
                 found_mission->fail();
             }
             if( type->goal == MGOAL_KILL_MONSTER ) {
                 found_mission->step_complete( 1 );
             }
             if( type->goal == MGOAL_KILL_MONSTERS ) {
                 if( found_mission->monster_kill_goal-- == 0 ) {
                     found_mission->step_complete( 1 );
                 }
             }
         }
         return;
     }
     npc *p = dynamic_cast<npc *>( &poor_dead_dude );
     if( p == nullptr ) {
         // Must be the player
         for( mission *&miss : get_avatar().get_active_missions() ) {
             // mission is free and can be reused
             miss->player_id = character_id();
         }
         // The missions remains assigned to the (dead) character. This should not cause any problems
         // as the character is dismissed anyway.
         // Technically, the active missions could be moved to the failed mission section.
         return;
     }
     const character_id dead_guys_id = p->getID();
     for( auto &e : world_missions ) {
         mission &i = e.second;
         if( !i.in_progress() ) {
             continue;
         }
         //complete the mission if you needed killing
         if( i.type->goal == MGOAL_ASSASSINATE && i.target_npc_id == dead_guys_id ) {
             i.step_complete( 1 );
         }
         //fail the mission if the mission giver dies
         if( i.npc_id == dead_guys_id ) {
             i.fail();
         }
         //fail the mission if recruit target dies
         if( i.type->goal == MGOAL_RECRUIT_NPC && i.target_npc_id == dead_guys_id ) {
             i.fail();
         }
     }
 }
References character_id, debugmsg, fail(), find(), avatar::get_active_missions(), get_avatar(), Character::getID(), mission_type::goal, in_progress(), Creature::is_hallucination(), monster::is_nemesis(), mission_start::kill_nemesis(), MGOAL_ASSASSINATE, MGOAL_FIND_MONSTER, MGOAL_KILL_MONSTER, MGOAL_KILL_MONSTERS, MGOAL_KILL_NEMESIS, MGOAL_RECRUIT_NPC, monster::mission_ids, mission_type::monster_kill_goal, monster_kill_goal, npc_id, player_id, step_complete(), target_npc_id, type, and world_missions.
Referenced by monster::die(), and Character::die().
on_creature_fusion()
bool mission::on_creature_fusion (Creature & fuser, Creature & fused) static
Definition at line 243 of file mission.cpp.
 {
     if( fuser.is_hallucination() || fused.is_hallucination() ) {
         return false;
     }
     monster *mon_fuser = dynamic_cast<monster *>( &fuser );
     if( mon_fuser == nullptr ) {
         debugmsg( "Unimplemented: fuser is not a monster" );
         return false;
     }
     monster *mon_fused = dynamic_cast<monster *>( &fused );
     if( mon_fused == nullptr ) {
         debugmsg( "Unimplemented: fused is not a monster" );
         return false;
     }
     bool mission_transfered = false;
     for( const int mission_id : mon_fused->mission_ids ) {
         const mission *const found_mission = mission::find( mission_id );
         if( !found_mission ) {
             debugmsg( "invalid mission id %d", mission_id );
             continue;
         }
         const mission_type *const type = found_mission->type;
         if( type->goal == MGOAL_KILL_MONSTER || type->goal == MGOAL_KILL_MONSTERS ) {
             // the fuser has to be killed now!
             mon_fuser->mission_ids.emplace( mission_id );
             mon_fused->mission_ids.erase( mission_id );
             mission_transfered = true;
         }
     }
     return mission_transfered;
 }
References debugmsg, find(), mission_type::goal, Creature::is_hallucination(), MGOAL_KILL_MONSTER, MGOAL_KILL_MONSTERS, monster::mission_ids, and type.
Referenced by mattack::zombie_fuse().
on_talk_with_npc()
void mission::on_talk_with_npc (const character_id & npc_id)
Called when the player talks with an NPC.
May resolve mission goals, e.g. MGOAL_TALK_TO_NPC.
Definition at line 276 of file mission.cpp.
 {
     switch( type->goal ) {
         case MGOAL_TALK_TO_NPC:
             // If our goal is to talk to this npc, and we haven't yet completed a step for this
             // mission, then complete a step.
             if( npc_id == target_npc_id && step == 0 ) {
                 step_complete( 1 );
             }
             break;
         default:
             break;
     }
 }
References mission_type::goal, MGOAL_TALK_TO_NPC, npc_id, step, step_complete(), target_npc_id, and type.
Referenced by talker_npc::get_topics().
process()
void mission::process ()
Processes this mission.
Definition at line 759 of file mission.cpp.
 {
     if( !in_progress() ) {
         return;
     }
     if( has_deadline() && calendar::turn > deadline ) {
         fail();
     } else if( !npc_id.is_valid() && is_complete( npc_id ) ) { // No quest giver.
         wrap_up();
     }
 }
References deadline, fail(), has_deadline(), in_progress(), is_complete(), character_id::is_valid(), npc_id, calendar::turn, and wrap_up().
process_all()
void mission::process_all () static
Handles mission deadline processing.
Definition at line 126 of file mission.cpp.
 {
     for( auto &e : world_missions ) {
         e.second.process();
     }
 }
References world_missions.
register_kill_needed()
void mission::register_kill_needed () inline
Definition at line 354 of file mission.h.
{
             monster_kill_goal++;
         };
References monster_kill_goal.
Referenced by map::spawn_monsters_submap().
remove_active_world_mission()
void mission::remove_active_world_mission (mission & cur_mission)
Definition at line 111 of file mission.cpp.
 {
     for( auto iter = world_missions.begin(); iter != world_missions.end(); iter++ ) {
         if( iter->second.get_id() == cur_mission.get_id() && iter->second.in_progress() ) {
             world_missions.erase( iter );
             break;
         }
     }
 }
References get_id(), and world_missions.
Referenced by avatar::remove_active_mission().
reserve_new()
mission * mission::reserve_new (const mission_type_id & type, const character_id & npc_id) static
Create a new mission of the given type and assign it to the given npc.
Returns the new mission.
Definition at line 79 of file mission.cpp.
 {
     const mission tmp = mission_type::get( type )->create( npc_id );
     // TODO: Warn about overwrite?
     mission &miss = world_missions[tmp.uid] = tmp;
     return &miss;
 }
References mission_type::create(), mission_type::get(), npc_id, type, uid, and world_missions.
Referenced by computer_session::action_emerg_ref_center(), talker_npc::add_mission(), debug_menu::character_edit_menu(), talk_function::clear_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission(), talk_function::lead_to_safety(), npc::load_npc_template(), reserve_random(), and game::start_game().
reserve_random()
mission * mission::reserve_random (mission_origin origin, const tripoint_abs_omt & p, const character_id & npc_id) static
Definition at line 291 of file mission.cpp.
 {
     const mission_type_id type = mission_type::get_random_id( origin, p );
     if( type.is_null() ) {
         return nullptr;
     }
     return mission::reserve_new( type, npc_id );
 }
References mission_type::get_random_id(), npc_id, reserve_new(), and type.
Referenced by game::create_starting_npcs(), game::perhaps_add_random_npc(), basecamp::recruit_return(), game::reset_npc_dispositions(), and debug_menu::spawn_npc().
serialize()
void mission::serialize (JsonOut & json) const
Definition at line 3629 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "type_id", type->id );
     json.member( "status", status_to_string( status ) );
     json.member( "value", value );
     json.member( "kill_count_to_reach", kill_count_to_reach );
     json.member( "reward", reward );
     json.member( "uid", uid );
     json.member( "target" );
     json.start_array();
     json.write( target.x() );
     json.write( target.y() );
     json.write( target.z() );
     json.end_array();
     json.member( "item_id", item_id );
     json.member( "item_count", item_count );
     json.member( "target_id", target_id.str() );
     json.member( "recruit_class", recruit_class );
     json.member( "target_npc_id", target_npc_id );
     json.member( "monster_type", monster_type );
     json.member( "monster_species", monster_species );
     json.member( "monster_kill_goal", monster_kill_goal );
     json.member( "deadline", deadline );
     json.member( "npc_id", npc_id );
     json.member( "good_fac_id", good_fac_id );
     json.member( "bad_fac_id", bad_fac_id );
     json.member( "step", step );
     json.member( "follow_up", follow_up );
     json.member( "player_id", player_id );
     json.end_object();
 }
References JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), JsonOut::start_array(), JsonOut::start_object(), status, type, and JsonOut::write().
serialize_all()
void mission::serialize_all (JsonOut & json) static
Definition at line 1447 of file savegame.cpp.
 {
     json.start_array();
     for( mission *&e : get_all_active() ) {
         e->serialize( json );
     }
     json.end_array();
 }
References JsonOut::end_array(), get_all_active(), and JsonOut::start_array().
Referenced by game::serialize_master().
set_assigned_player_id()
void mission::set_assigned_player_id (const character_id & char_id)
Definition at line 797 of file mission.cpp.
 {
     player_id = char_id;
 }
References player_id.
set_target()
void mission::set_target (const tripoint_abs_omt & p)
Simple setters, no checking if the values is performed.
Definition at line 787 of file mission.cpp.
 {
     target = p;
 }
References target.
Referenced by mission_util::assign_mission_target(), reveal_target(), mission_util::target_closest_lab_entrance(), mission_util::target_om_ter(), and mission_util::target_om_ter_random().
set_target_npc_id()
void mission::set_target_npc_id (const character_id & npc_id)
Definition at line 792 of file mission.cpp.
 {
     target_npc_id = npc_id;
 }
References npc_id, and target_npc_id.
Referenced by jmapgen_npc::apply().
set_target_to_mission_giver()
void mission::set_target_to_mission_giver () private
Definition at line 342 of file mission.cpp.
 {
     const npc *giver = g->find_npc( npc_id );
     if( giver != nullptr ) {
         target = giver->global_omt_location();
     } else {
         target = overmap::invalid_tripoint;
     }
 }
References g, Creature::global_omt_location(), overmap::invalid_tripoint, npc_id, and target.
Referenced by step_complete().
status_from_string()
mission::mission_status mission::status_from_string (const std::string & s) static
Definition at line 913 of file mission.cpp.
 {
     return io::string_to_enum<mission::mission_status>( s );
 }
status_to_string()
std::string mission::status_to_string (mission::mission_status st) static
Definition at line 918 of file mission.cpp.
 {
     return io::enum_to_string<mission::mission_status>( st );
 }
step_complete()
void mission::step_complete (int step)
Handles partial mission completion (kill complete, now report back!).
Definition at line 352 of file mission.cpp.
 {
     step = _step;
     switch( type->goal ) {
         case MGOAL_FIND_ITEM:
         case MGOAL_FIND_ITEM_GROUP:
         case MGOAL_FIND_MONSTER:
         case MGOAL_ASSASSINATE:
         case MGOAL_KILL_MONSTER:
         case MGOAL_KILL_MONSTERS:
         case MGOAL_COMPUTER_TOGGLE:
         case MGOAL_TALK_TO_NPC:
             // Go back and report.
             set_target_to_mission_giver();
             break;
         default:
             //Suppress warnings
             break;
     }
 }
References mission_type::goal, MGOAL_ASSASSINATE, MGOAL_COMPUTER_TOGGLE, MGOAL_FIND_ITEM, MGOAL_FIND_ITEM_GROUP, MGOAL_FIND_MONSTER, MGOAL_KILL_MONSTER, MGOAL_KILL_MONSTERS, MGOAL_TALK_TO_NPC, set_target_to_mission_giver(), step, and type.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), on_creature_death(), and on_talk_with_npc().
to_ptr_vector()
std::vector< mission * > mission::to_ptr_vector (const std::vector< int > & vec, bool ok_missing = false) static
Converts a vector mission ids to a vector of mission pointers.
Invalid ids are skipped!
Definition at line 133 of file mission.cpp.
 {
     std::vector<mission *> result;
     for( const int &id : vec ) {
         mission *miss = find( id, ok_missing );
         if( miss != nullptr ) {
             result.push_back( miss );
         }
     }
     return result;
 }
References find().
Referenced by dialogue_chatbin::deserialize(), and avatar::load().
to_uid_vector()
std::vector< int > mission::to_uid_vector (const std::vector< mission * > & vec) static
Definition at line 145 of file mission.cpp.
 {
     std::vector<int> result;
     result.reserve( vec.size() );
     for( const mission *miss : vec ) {
         result.push_back( miss->uid );
     }
     return result;
 }
Referenced by diary::new_page(), dialogue_chatbin::serialize(), and avatar::store().
unserialize_all()
void mission::unserialize_all (const JsonArray & ja) static
Definition at line 1399 of file savegame.cpp.
 {
     for( JsonObject jo : ja ) {
         mission mis;
         mis.deserialize( jo );
         add_existing( mis );
     }
 }
References add_existing(), and deserialize().
Referenced by game::unserialize_master().
update_world_missions_character()
void mission::update_world_missions_character (const character_id & old_char_id, const character_id & new_char_id)
Definition at line 802 of file mission.cpp.
 {
     for( auto &world_mission : world_missions ) {
         if( world_mission.second.in_progress() &&
             ( world_mission.second.get_assigned_player_id()  == old_char_id ||
               world_mission.second.get_assigned_player_id() == character_id( - 1 ) ) ) {
             world_mission.second.set_assigned_player_id( new_char_id );
         }
     }
 }
References world_missions.
Referenced by avatar::control_npc().
wrap_up()
void mission::wrap_up ()
Handles mission completion tasks (remove given item, etc.).
Definition at line 373 of file mission.cpp.
 {
     avatar &player_character = get_avatar();
     if( player_character.getID() != player_id ) {
         // This is called from npctalk.cpp, the npc should only offer the option to wrap up mission
         // that have been assigned to the current player.
         debugmsg( "mission::wrap_up called, player %d was assigned, but current player is %d",
                   player_id.get_value(), player_character.getID().get_value() );
     }
     status = mission_status::success;
     player_character.on_mission_finished( *this );
     std::vector<item_comp> comps;
     switch( type->goal ) {
         case MGOAL_FIND_ITEM_GROUP: {
             inventory tmp_inv = player_character.crafting_inventory();
             std::vector<item *> items = std::vector<item *>();
             tmp_inv.dump( items );
             item_group_id grp_type = type->group_id;
             itype_id container = type->container_id;
             bool specific_container_required = !container.is_null();
             bool remove_container = type->remove_container;
             itype_id empty_container = type->empty_container;
             std::map<itype_id, int> matches = std::map<itype_id, int>();
             get_all_item_group_matches(
                 items, grp_type, matches,
                 container, itype_null, specific_container_required );
             for( std::pair<const itype_id, int> &cnt : matches ) {
                 comps.emplace_back( cnt.first, cnt.second );
             }
             player_character.consume_items( comps );
             if( remove_container ) {
                 std::vector<item_comp> container_comp = std::vector<item_comp>();
                 if( !empty_container.is_null() ) {
                     container_comp.emplace_back( empty_container, type->item_count );
                     player_character.consume_items( container_comp );
                 } else {
                     container_comp.emplace_back( container, type->item_count );
                     player_character.consume_items( container_comp );
                 }
             }
         }
         break;
         case MGOAL_FIND_ITEM: {
             const item item_sought( type->item_id );
             if( item_sought.is_software() ) {
                 int consumed = 0;
                 while( consumed < item_count ) {
                     if( player_character.consume_software_container( type->item_id ) ) {
                         consumed++;
                     } else {
                         debugmsg( "Tried to consume more software %s than available", type->item_id.c_str() );
                         break;
                     }
                 }
             } else {
                 comps.emplace_back( type->item_id, item_count );
                 player_character.consume_items( comps );
             }
         }
         break;
         case MGOAL_FIND_ANY_ITEM:
             player_character.remove_mission_items( uid );
             break;
         case MGOAL_FIND_MONSTER: {
             Creature *found_creature = g->get_creature_if( [&]( const Creature & critter ) {
                 const monster *const mon_ptr = dynamic_cast<const monster *>( &critter );
                 return mon_ptr && mon_ptr->mission_ids.count( uid );
             } );
             if( found_creature != nullptr ) {
                 monster *found_monster = found_creature->as_monster();
                 if( found_monster != nullptr ) {
                     found_monster->mission_ids.erase( uid );
                     found_monster->remove_effect( effect_pet );
                     found_monster->remove_effect( effect_run );
                     found_monster->friendly = 0;
                     found_monster->morale = 100;
                 }
             }
         }
         default:
             //Suppress warnings
             break;
     }
     type->end( this );
 }
References Creature::as_monster(), string_id< T >::c_str(), Character::consume_items(), Character::consume_software_container(), mission_type::container_id, Character::crafting_inventory(), debugmsg, inventory::dump(), effect_pet, effect_run, mission_type::empty_container, mission_type::end, monster::friendly, g, get_all_item_group_matches(), get_avatar(), character_id::get_value(), Character::getID(), mission_type::goal, mission_type::group_id, string_id< T >::is_null(), item::is_software(), mission_type::item_count, item_count, mission_type::item_id, itype_null, MGOAL_FIND_ANY_ITEM, MGOAL_FIND_ITEM, MGOAL_FIND_ITEM_GROUP, MGOAL_FIND_MONSTER, monster::mission_ids, monster::morale, avatar::on_mission_finished(), player_id, mission_type::remove_container, Creature::remove_effect(), Character::remove_mission_items(), status, success, type, and uid.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_function::mission_success(), and process().
Friends And Related Function Documentation
debug_menu::mission_debug
friend class debug_menu::mission_debug friend
Definition at line 287 of file mission.h.
mission_start
friend struct mission_start friend
Definition at line 286 of file mission.h.
mission_type
friend struct mission_type friend
Definition at line 284 of file mission.h.
Member Data Documentation
bad_fac_id
int mission::bad_fac_id = 0 private
Definition at line 323 of file mission.h.
Referenced by mission().
deadline
time_point mission::deadline private
Definition at line 318 of file mission.h.
Referenced by assign(), get_deadline(), has_deadline(), and process().
follow_up
mission_type_id mission::follow_up private
Definition at line 327 of file mission.h.
Referenced by get_follow_up(), has_follow_up(), and mission_start::place_npc_software().
good_fac_id
int mission::good_fac_id = 0 private
Definition at line 322 of file mission.h.
Referenced by mission().
item_count
int mission::item_count = 0 private
Definition at line 303 of file mission.h.
Referenced by is_complete(), mission(), and wrap_up().
item_id
itype_id mission::item_id private
Definition at line 301 of file mission.h.
Referenced by get_item_id(), mission(), and mission_start::place_npc_software().
kill_count_to_reach
int mission::kill_count_to_reach = 0 private
Definition at line 317 of file mission.h.
Referenced by assign(), and is_complete().
monster_kill_goal
int mission::monster_kill_goal = 0 private
Definition at line 315 of file mission.h.
Referenced by assign(), mission(), on_creature_death(), and register_kill_needed().
monster_species
species_id mission::monster_species private
Definition at line 313 of file mission.h.
Referenced by assign(), and is_complete().
monster_type
mtype_id mission::monster_type private
Definition at line 311 of file mission.h.
Referenced by assign(), is_complete(), and mission().
npc_id
character_id mission::npc_id private
Definition at line 320 of file mission.h.
Referenced by debug_menu::mission_debug::describe(), get_npc_id(), is_complete(), mission(), on_creature_death(), on_talk_with_npc(), mission_start::place_deposit_box(), mission_start::place_npc_software(), process(), debug_menu::mission_debug::remove_mission(), reserve_new(), reserve_random(), set_target_npc_id(), and set_target_to_mission_giver().
player_id
character_id mission::player_id private
Definition at line 329 of file mission.h.
Referenced by assign(), debug_menu::mission_debug::describe(), fail(), get_assigned_player_id(), is_assigned(), mission(), on_creature_death(), set_assigned_player_id(), and wrap_up().
recruit_class
npc_class_id mission::recruit_class private
Definition at line 307 of file mission.h.
Referenced by is_complete(), and mission().
reward
npc_favor mission::reward private
Definition at line 294 of file mission.h.
status
mission_status mission::status private
Definition at line 290 of file mission.h.
Referenced by assign(), debug_menu::mission_debug::describe(), debug_menu::mission_debug::edit_mission(), fail(), has_failed(), in_progress(), is_complete(), mission(), and wrap_up().
step
int mission::step = 0 private
Definition at line 325 of file mission.h.
Referenced by is_complete(), mission(), on_talk_with_npc(), and step_complete().
target
tripoint_abs_omt mission::target private
Definition at line 299 of file mission.h.
Referenced by debug_menu::mission_debug::describe(), mission_start::find_safety(), get_target(), has_target(), is_complete(), mission(), mission_start::place_deposit_box(), mission_start::place_npc_software(), set_target(), and set_target_to_mission_giver().
target_id
string_id<oter_type_t> mission::target_id private
Definition at line 305 of file mission.h.
Referenced by mission().
target_npc_id
character_id mission::target_npc_id private
Definition at line 309 of file mission.h.
Referenced by is_complete(), mission(), on_creature_death(), on_talk_with_npc(), and set_target_npc_id().
type
const mission_type* mission::type private
Definition at line 289 of file mission.h.
Referenced by assign(), debug_menu::mission_debug::describe(), dialogue_for_topic(), debug_menu::mission_debug::edit_npc(), debug_menu::mission_debug::edit_player(), fail(), get_description(), get_likely_rewards(), get_type(), has_generic_rewards(), is_complete(), mission(), mission_id(), name(), on_creature_death(), on_creature_fusion(), on_talk_with_npc(), reserve_new(), reserve_random(), step_complete(), and wrap_up().
uid
int mission::uid private
Definition at line 296 of file mission.h.
Referenced by add_existing(), assign(), debug_menu::mission_debug::describe(), get_id(), is_complete(), mission(), reserve_new(), and wrap_up().
value
unsigned int mission::value private
Definition at line 292 of file mission.h.
Referenced by get_value(), and mission().
The documentation for this class was generated from the following files:
src/mission.h
src/mission.cpp
src/savegame.cpp
src/savegame_json.cpp