Cataclysm DDA: disease_type Class Reference
disease_type Class Reference
#include <disease.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view)
Static Public Member Functions
static void load_disease_type (const JsonObject &jo, const std::string &src)
static void reset ()
static const std::vector< disease_type > & get_all ()
static void check_disease_consistency ()
Public Attributes
bool was_loaded = false
diseasetype_id id
std::vector< std::pair< diseasetype_id, mod_id > > src
time_duration min_duration = 1_turns
time_duration max_duration = 1_turns
int min_intensity = 1
int max_intensity = 1
std::set< bodypart_str_id > affected_bodyparts
Affected body parts.
std::optional< int > health_threshold
If not empty this sets the health threshold above which you're immune to the disease.
efftype_id symptoms
effect applied by this disease
Detailed Description
Definition at line 17 of file disease.h.
Member Function Documentation
check_disease_consistency()
void disease_type::check_disease_consistency () static
Definition at line 58 of file disease.cpp.
 {
     for( const disease_type &dis : get_all() ) {
         const efftype_id &symp = dis.symptoms;
         if( !symp.is_valid() ) {
             debugmsg( "disease_type %s has invalid efftype_id %s in symptoms", dis.id.c_str(),  symp.c_str() );
         }
     }
 }
References string_id< T >::c_str(), debugmsg, get_all(), and string_id< T >::is_valid().
Referenced by DynamicDataLoader::check_consistency().
get_all()
const std::vector< disease_type > & disease_type::get_all () static
Definition at line 53 of file disease.cpp.
 {
     return disease_factory.get_all();
 }
References anonymous_namespace{disease.cpp}::disease_factory.
Referenced by check_disease_consistency().
load()
void disease_type::load (const JsonObject & jo, std::string_view)
Definition at line 32 of file disease.cpp.
 {
     disease_type new_disease;
     mandatory( jo, was_loaded, "id", id );
     mandatory( jo, was_loaded, "min_duration", min_duration );
     mandatory( jo, was_loaded, "max_duration", max_duration );
     mandatory( jo, was_loaded, "min_intensity", min_intensity );
     mandatory( jo, was_loaded, "max_intensity", max_intensity );
     mandatory( jo, was_loaded, "symptoms", symptoms );
     optional( jo, was_loaded, "health_threshold", health_threshold );
     optional( jo, was_loaded, "affected_bodyparts", affected_bodyparts );
 }
References affected_bodyparts, health_threshold, mandatory, max_duration, max_intensity, min_duration, min_intensity, optional(), symptoms, and was_loaded.
load_disease_type()
void disease_type::load_disease_type (const JsonObject & jo, const std::string & src) static
Definition at line 27 of file disease.cpp.
 {
     disease_factory.load( jo, src );
 }
References anonymous_namespace{disease.cpp}::disease_factory, and src.
Referenced by DynamicDataLoader::initialize().
reset()
void disease_type::reset () static
Definition at line 48 of file disease.cpp.
 {
     disease_factory.reset();
 }
References anonymous_namespace{disease.cpp}::disease_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
affected_bodyparts
std::set<bodypart_str_id> disease_type::affected_bodyparts
Affected body parts.
Definition at line 34 of file disease.h.
Referenced by Character::expose_to_disease(), and load().
health_threshold
std::optional<int> disease_type::health_threshold
If not empty this sets the health threshold above which you're immune to the disease.
Definition at line 36 of file disease.h.
Referenced by Character::expose_to_disease(), and load().
id
diseasetype_id disease_type::id
Definition at line 27 of file disease.h.
max_duration
time_duration disease_type::max_duration = 1_turns
Definition at line 30 of file disease.h.
Referenced by Character::expose_to_disease(), and load().
max_intensity
int disease_type::max_intensity = 1
Definition at line 32 of file disease.h.
Referenced by Character::expose_to_disease(), and load().
min_duration
time_duration disease_type::min_duration = 1_turns
Definition at line 29 of file disease.h.
Referenced by Character::expose_to_disease(), and load().
min_intensity
int disease_type::min_intensity = 1
Definition at line 31 of file disease.h.
Referenced by Character::expose_to_disease(), and load().
src
std::vector<std::pair<diseasetype_id, mod_id> > disease_type::src
Definition at line 28 of file disease.h.
Referenced by load_disease_type().
symptoms
efftype_id disease_type::symptoms
effect applied by this disease
Definition at line 38 of file disease.h.
Referenced by Character::expose_to_disease(), and load().
was_loaded
bool disease_type::was_loaded = false
Definition at line 25 of file disease.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/disease.h
src/disease.cpp