Cataclysm DDA: scrollbar Class Reference
scrollbar Class Reference
#include <output.h>
Public Member Functions
scrollbar ()
scrollbar & offset_x (int offx)
scrollbar & offset_y (int offy)
scrollbar & content_size (int csize)
scrollbar & viewport_pos (int vpos)
scrollbar & viewport_size (int vsize)
scrollbar & border_color (nc_color border_c)
scrollbar & arrow_color (nc_color arrow_c)
scrollbar & slot_color (nc_color slot_c)
scrollbar & bar_color (nc_color bar_c)
scrollbar & scroll_to_last (bool scr2last)
scrollbar & set_draggable (input_context &ctxt)
void apply (const catacurses::window &window)
bool handle_dragging (const std::string &action, const std::optional< point > &coord, int &position)
Private Attributes
int offset_x_v
int offset_y_v
int content_size_v
int viewport_pos_v
int viewport_size_v
nc_color border_color_v
nc_color arrow_color_v
nc_color slot_color_v
nc_color bar_color_v
bool scroll_to_last_v
bool dragging = false
inclusive_rectangle< point > scrollbar_area
Detailed Description
Definition at line 889 of file output.h.
Constructor & Destructor Documentation
scrollbar()
scrollbar::scrollbar ()
Definition at line 1719 of file output.cpp.
     : offset_x_v( 0 ), offset_y_v( 0 ), content_size_v( 0 ),
       viewport_pos_v( 0 ), viewport_size_v( 0 ),
       border_color_v( BORDER_COLOR ), arrow_color_v( c_light_green ),
       slot_color_v( c_white ), bar_color_v( c_cyan_cyan ), scroll_to_last_v( false )
 {
 }
Member Function Documentation
apply()
void scrollbar::apply (const catacurses::window & window)
Definition at line 1787 of file output.cpp.
 {
     scrollbar_area = inclusive_rectangle<point>( point( getbegx( window ) + offset_x_v,
                      getbegy( window ) + offset_y_v ), point( getbegx( window ) + offset_x_v,
                              getbegy( window ) + offset_y_v + viewport_size_v ) );
     if( viewport_size_v >= content_size_v || content_size_v <= 0 ) {
         // scrollbar not needed, fill output area with borders
         for( int i = offset_y_v; i < offset_y_v + viewport_size_v; ++i ) {
             mvwputch( window, point( offset_x_v, i ), border_color_v, LINE_XOXO );
         }
     } else {
         mvwputch( window, point( offset_x_v, offset_y_v ), arrow_color_v, '^' );
         mvwputch( window, point( offset_x_v, offset_y_v + viewport_size_v - 1 ), arrow_color_v, 'v' );
         int slot_size = viewport_size_v - 2;
         int bar_size = std::max( 2, slot_size * viewport_size_v / content_size_v );
         int scrollable_size = scroll_to_last_v ? content_size_v : content_size_v - viewport_size_v + 1;
         int bar_start;
         if( viewport_pos_v == 0 ) {
             bar_start = 0;
         } else if( scrollable_size > 2 ) {
             bar_start = ( slot_size - 1 - bar_size ) * ( viewport_pos_v - 1 ) / ( scrollable_size - 2 ) + 1;
         } else {
             bar_start = slot_size - bar_size;
         }
         int bar_end = bar_start + bar_size;
         nc_color temp_bar_color = dragging ? c_magenta_magenta : bar_color_v;
         for( int i = 0; i < slot_size; ++i ) {
             if( i >= bar_start && i < bar_end ) {
                 mvwputch( window, point( offset_x_v, offset_y_v + 1 + i ), temp_bar_color, LINE_XOXO );
             } else {
                 mvwputch( window, point( offset_x_v, offset_y_v + 1 + i ), slot_color_v, LINE_XOXO );
             }
         }
     }
 }
References arrow_color_v, bar_color_v, border_color_v, c_magenta_magenta, content_size_v, dragging, catacurses::getbegx(), catacurses::getbegy(), LINE_XOXO, max(), mvwputch(), offset_x_v, offset_y_v, point, scroll_to_last_v, scrollbar_area, slot_color_v, viewport_pos_v, and viewport_size_v.
Referenced by avatar::disp_medical(), talk_function::display_and_choose_opts(), bodygraph_display::draw_borders(), prof_window::draw_borders(), draw_item_info(), draw_left_win(), draw_scrollbar(), ma_style_callback::key(), string_editor_window::print_editor(), spellcasting_callback::refresh(), scrollable_text(), select_crafter_and_crafting_recipe(), set_hobbies(), set_profession(), set_scenario(), set_skills(), Messages::dialog::show(), options_manager::show(), worldfactory::show_worldgen_basic(), and outfit::sort_armor().
arrow_color()
scrollbar & scrollbar::arrow_color (nc_color arrow_c)
Definition at line 1763 of file output.cpp.
 {
     arrow_color_v = arrow_c;
     return *this;
 }
References arrow_color_v.
bar_color()
scrollbar & scrollbar::bar_color (nc_color bar_c)
Definition at line 1775 of file output.cpp.
 {
     bar_color_v = bar_c;
     return *this;
 }
References bar_color_v.
border_color()
scrollbar & scrollbar::border_color (nc_color border_c)
Definition at line 1757 of file output.cpp.
 {
     border_color_v = border_c;
     return *this;
 }
References border_color_v.
Referenced by debug_menu::change_spells(), bodygraph_display::draw_borders(), prof_window::draw_borders(), and worldfactory::show_worldgen_basic().
content_size()
scrollbar & scrollbar::content_size (int csize)
Definition at line 1739 of file output.cpp.
 {
     content_size_v = csize;
     return *this;
 }
References content_size_v.
Referenced by avatar::disp_medical(), talk_function::display_and_choose_opts(), scrolling_text_view::draw(), bodygraph_display::draw_borders(), prof_window::draw_borders(), draw_item_info(), draw_left_win(), draw_scrollbar(), ma_style_callback::key(), string_editor_window::print_editor(), spellcasting_callback::refresh(), scrollable_text(), select_crafter_and_crafting_recipe(), set_hobbies(), set_profession(), set_scenario(), set_skills(), Messages::dialog::show(), options_manager::show(), worldfactory::show_worldgen_basic(), and outfit::sort_armor().
handle_dragging()
bool scrollbar::handle_dragging (const std::string & action, const std::optional< point > & coord, int & position)
Definition at line 1834 of file output.cpp.
 {
     if( ( action != "MOUSE_MOVE" && action != "CLICK_AND_DRAG" ) && dragging ) {
         // Stopped dragging the scrollbar
         dragging = false;
         // We don't want to accidentally select something on mouse-up after dragging the scrollbar, so if
         // there's a mouse-up event, tell the UI that we've handled it
         return action == "SELECT";
     } else  if( action == "CLICK_AND_DRAG" && coord.has_value() &&
                 scrollbar_area.contains( coord.value() ) ) {
         // Started dragging the scrollbar
         dragging = true;
         return true;
     } else if( action == "MOUSE_MOVE" && coord.has_value() && dragging ) {
         // Currently dragging the scrollbar.  Clamp cursor position to scrollbar area, then interpolate
         int clamped_cursor_pos = clamp( coord->y - scrollbar_area.p_min.y, 0,
                                         scrollbar_area.p_max.y - scrollbar_area.p_min.y - 1 );
         viewport_pos_v = clamped_cursor_pos * ( content_size_v - viewport_size_v ) /
                          ( scrollbar_area.p_max.y - scrollbar_area.p_min.y - 1 );
         position = viewport_pos_v;
 #if !defined(TILES)
         // Tiles builds seem to trigger "SELECT" on mouse button-up (clearing "dragging") but curses does not
         dragging = false;
 #endif //TILES
         return true;
     } else {
         // Not doing anything related to the scrollbar
         return false;
     }
 }
References action, clamp(), inclusive_rectangle< Point, >::contains(), content_size_v, dragging, inclusive_rectangle< Point, >::p_max, inclusive_rectangle< Point, >::p_min, scrollbar_area, viewport_pos_v, viewport_size_v, and point::y.
Referenced by draw_item_info(), scrolling_text_view::handle_navigation(), ma_style_callback::key(), set_hobbies(), set_profession(), set_scenario(), and set_skills().
offset_x()
scrollbar & scrollbar::offset_x (int offx)
Definition at line 1727 of file output.cpp.
 {
     offset_x_v = offx;
     return *this;
 }
References offset_x_v.
Referenced by debug_menu::change_spells(), avatar::disp_medical(), talk_function::display_and_choose_opts(), bodygraph_display::draw_borders(), prof_window::draw_borders(), draw_item_info(), draw_left_win(), draw_scrollbar(), ma_style_callback::key(), spellcasting_callback::refresh(), scrollable_text(), select_crafter_and_crafting_recipe(), set_hobbies(), set_profession(), set_scenario(), set_skills(), Messages::dialog::show(), options_manager::show(), worldfactory::show_worldgen_basic(), and outfit::sort_armor().
offset_y()
scrollbar & scrollbar::offset_y (int offy)
Definition at line 1733 of file output.cpp.
 {
     offset_y_v = offy;
     return *this;
 }
References offset_y_v.
Referenced by debug_menu::change_spells(), avatar::disp_medical(), talk_function::display_and_choose_opts(), bodygraph_display::draw_borders(), prof_window::draw_borders(), draw_item_info(), draw_left_win(), draw_scrollbar(), ma_style_callback::key(), spellcasting_callback::refresh(), scrollable_text(), select_crafter_and_crafting_recipe(), set_hobbies(), set_profession(), set_scenario(), set_skills(), Messages::dialog::show(), options_manager::show(), worldfactory::show_worldgen_basic(), and outfit::sort_armor().
scroll_to_last()
scrollbar & scrollbar::scroll_to_last (bool scr2last)
Definition at line 1781 of file output.cpp.
 {
     scroll_to_last_v = scr2last;
     return *this;
 }
References scroll_to_last_v.
Referenced by avatar::disp_medical(), draw_item_info(), draw_scrollbar(), and ma_style_callback::key().
set_draggable()
scrollbar & scrollbar::set_draggable (input_context & ctxt)
Definition at line 1826 of file output.cpp.
 {
     ctxt.register_action( "MOUSE_MOVE" );
     ctxt.register_action( "CLICK_AND_DRAG" );
     ctxt.register_action( "SELECT" ); // Not directly used yet, but required for mouse-up reaction
     return *this;
 }
References input_context::register_action().
Referenced by draw_item_info(), ma_style_callback::key(), set_hobbies(), set_profession(), set_scenario(), set_skills(), and scrolling_text_view::set_up_navigation().
slot_color()
scrollbar & scrollbar::slot_color (nc_color slot_c)
Definition at line 1769 of file output.cpp.
 {
     slot_color_v = slot_c;
     return *this;
 }
References slot_color_v.
Referenced by draw_scrollbar(), and ma_style_callback::key().
viewport_pos()
scrollbar & scrollbar::viewport_pos (int vpos)
Definition at line 1745 of file output.cpp.
 {
     viewport_pos_v = vpos;
     return *this;
 }
References viewport_pos_v.
Referenced by avatar::disp_medical(), talk_function::display_and_choose_opts(), bodygraph_display::draw_borders(), prof_window::draw_borders(), draw_item_info(), draw_left_win(), draw_scrollbar(), ma_style_callback::key(), string_editor_window::print_editor(), spellcasting_callback::refresh(), scrollable_text(), select_crafter_and_crafting_recipe(), set_hobbies(), set_profession(), set_scenario(), set_skills(), Messages::dialog::show(), options_manager::show(), worldfactory::show_worldgen_basic(), and outfit::sort_armor().
viewport_size()
scrollbar & scrollbar::viewport_size (int vsize)
Definition at line 1751 of file output.cpp.
 {
     viewport_size_v = vsize;
     return *this;
 }
References viewport_size_v.
Referenced by avatar::disp_medical(), talk_function::display_and_choose_opts(), bodygraph_display::draw_borders(), prof_window::draw_borders(), draw_item_info(), draw_left_win(), draw_scrollbar(), ma_style_callback::key(), string_editor_window::print_editor(), spellcasting_callback::refresh(), scrollable_text(), select_crafter_and_crafting_recipe(), set_hobbies(), set_profession(), set_scenario(), set_skills(), Messages::dialog::show(), options_manager::show(), worldfactory::show_worldgen_basic(), and outfit::sort_armor().
Member Data Documentation
arrow_color_v
nc_color scrollbar::arrow_color_v private
Definition at line 922 of file output.h.
Referenced by apply(), and arrow_color().
bar_color_v
nc_color scrollbar::bar_color_v private
Definition at line 922 of file output.h.
Referenced by apply(), and bar_color().
border_color_v
nc_color scrollbar::border_color_v private
Definition at line 922 of file output.h.
Referenced by apply(), and border_color().
content_size_v
int scrollbar::content_size_v private
Definition at line 921 of file output.h.
Referenced by apply(), content_size(), and handle_dragging().
dragging
bool scrollbar::dragging = false private
Definition at line 924 of file output.h.
Referenced by apply(), and handle_dragging().
offset_x_v
int scrollbar::offset_x_v private
Definition at line 920 of file output.h.
Referenced by apply(), and offset_x().
offset_y_v
int scrollbar::offset_y_v private
Definition at line 920 of file output.h.
Referenced by apply(), and offset_y().
scroll_to_last_v
bool scrollbar::scroll_to_last_v private
Definition at line 923 of file output.h.
Referenced by apply(), and scroll_to_last().
scrollbar_area
inclusive_rectangle<point> scrollbar::scrollbar_area private
Definition at line 925 of file output.h.
Referenced by apply(), and handle_dragging().
slot_color_v
nc_color scrollbar::slot_color_v private
Definition at line 922 of file output.h.
Referenced by apply(), and slot_color().
viewport_pos_v
int scrollbar::viewport_pos_v private
Definition at line 921 of file output.h.
Referenced by apply(), handle_dragging(), and viewport_pos().
viewport_size_v
int scrollbar::viewport_size_v private
Definition at line 921 of file output.h.
Referenced by apply(), handle_dragging(), and viewport_size().
The documentation for this class was generated from the following files:
src/output.h
src/output.cpp