Cataclysm DDA: eoc_examine_actor Class Reference
eoc_examine_actor Class Reference
#include <iexamine_actors.h>
Public Member Functions
eoc_examine_actor (const std::string &type="effect_on_condition")
void load (const JsonObject &jo) override
void call (Character &you, const tripoint &examp) const override
void finalize () const override
std::unique_ptr< iexamine_actor > clone () const override
Public Member Functions inherited from iexamine_actor
iexamine_actor (const std::string &type)
virtual ~iexamine_actor ()=default
Private Attributes
std::vector< effect_on_condition_id > eocs
Additional Inherited Members
Public Attributes inherited from iexamine_actor
const std::string type
Detailed Description
Definition at line 70 of file iexamine_actors.h.
Constructor & Destructor Documentation
eoc_examine_actor()
eoc_examine_actor::eoc_examine_actor (const std::string & type = "effect_on_condition") inline explicit
Definition at line 75 of file iexamine_actors.h.
             : iexamine_actor( type ) {}
Member Function Documentation
call()
void eoc_examine_actor::call (Character & you, const tripoint & examp) const override virtual
Implements iexamine_actor.
Definition at line 250 of file iexamine_actors.cpp.
 {
     dialogue d( get_talker_for( you ), nullptr );
     d.set_value( "npctalk_var_this", get_map().furn( examp ).id().str() );
     d.set_value( "npctalk_var_pos", get_map().getglobal( examp ).to_string() );
     for( const effect_on_condition_id &eoc : eocs ) {
         eoc->activate( d );
     }
 }
References eoc, eocs, get_map(), get_talker_for(), dialogue::set_value(), and to_string().
clone()
std::unique_ptr< iexamine_actor > eoc_examine_actor::clone () const override virtual
Implements iexamine_actor.
Definition at line 276 of file iexamine_actors.cpp.
 {
     return std::make_unique<eoc_examine_actor>( *this );
 }
finalize()
void eoc_examine_actor::finalize () const override virtual
Implements iexamine_actor.
Definition at line 267 of file iexamine_actors.cpp.
 {
     for( const effect_on_condition_id &eoc : eocs ) {
         if( !eoc.is_valid() ) {
             debugmsg( "Invalid effect_on_condition_id: %s", eoc.str() );
         }
     }
 }
References debugmsg, eoc, and eocs.
load()
void eoc_examine_actor::load (const JsonObject & jo) override virtual
Implements iexamine_actor.
Definition at line 260 of file iexamine_actors.cpp.
 {
     for( JsonValue jv : jo.get_array( "effect_on_conditions" ) ) {
         eocs.emplace_back( effect_on_conditions::load_inline_eoc( jv, "" ) );
     }
 }
References eocs, JsonObject::get_array(), and effect_on_conditions::load_inline_eoc().
Member Data Documentation
eocs
std::vector<effect_on_condition_id> eoc_examine_actor::eocs private
Definition at line 73 of file iexamine_actors.h.
Referenced by call(), finalize(), and load().
The documentation for this class was generated from the following files:
src/iexamine_actors.h
src/iexamine_actors.cpp