Cataclysm DDA: monster Class Reference
monster Class Reference
#include <monster.h>
Public Member Functions
monster ()
monster (const mtype_id &id)
monster (const mtype_id &id, const tripoint &pos)
monster (const monster &)
monster (monster &&) noexcept(map_is_noexcept)
~monster () override
monster & operator= (const monster &)
monster & operator= (monster &&) noexcept(string_is_noexcept)
bool is_monster () const override
monster * as_monster () override
const monster * as_monster () const override
mfaction_id get_monster_faction () const override
void poly (const mtype_id &id)
bool can_upgrade () const
void hasten_upgrade ()
int get_upgrade_time () const
void allow_upgrade ()
void try_upgrade (bool pin_time)
void try_reproduce ()
void try_biosignature ()
void refill_udders ()
void digest_food ()
void reset_digestion ()
void spawn (const tripoint &p)
void spawn (const tripoint_abs_ms &loc)
std::vector< material_id > get_absorb_material () const
std::vector< material_id > get_no_absorb_material () const
creature_size get_size () const override
units::mass get_weight () const override
units::mass weight_capacity () const override
units::volume get_volume () const
int get_hp (const bodypart_id &) const override
int get_hp () const override
int get_hp_max (const bodypart_id &) const override
int get_hp_max () const override
int hp_percentage () const override
int get_eff_per () const override
void witness_thievery (item *it) override
float get_mountable_weight_ratio () const
std::string get_name () const override
std::string name (unsigned int quantity=1) const
std::string name_with_armor () const
std::string disp_name (bool possessive=false, bool capitalize_first=false) const override
std::string skin_name () const override
void get_HP_Bar (nc_color &color, std::string &text) const
std::pair< std::string, nc_color > get_attitude () const
int print_info (const catacurses::window &w, int vStart, int vLines, int column) const override
Write information about this creature.
nc_color basic_symbol_color () const override
Creature symbol color.
nc_color symbol_color () const override
Creature symbol background color.
const std::string & symbol () const override
Creature symbol.
bool is_symbol_highlighted () const override
nc_color color_with_effects () const
std::string extended_description () const override
bool has_flag (const mon_flag_id &f) const final
bool has_flag (flag_id f) const
bool can_see () const
bool can_hear () const
bool can_submerge () const
bool can_drown () const
bool can_climb () const
bool digging () const override
bool can_dig () const
bool digs () const
bool flies () const
bool climbs () const
bool swims () const
bool can_act () const
int sight_range (float light_level) const override
How far the creature sees under the given light.
bool made_of (const material_id &m) const override
bool made_of_any (const std::set< material_id > &ms) const override
bool made_of (phase_id p) const
bool shearable () const
bool is_pet () const
bool is_pet_follow () const
bool has_intelligence () const
bool avoid_trap (const tripoint &pos, const trap &tr) const override
Called when a creature triggers a trap, returns true if they don't set it off.
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
void deserialize (const JsonObject &data, const tripoint_abs_sm &submap_loc)
void shift (const point &sm_shift)
void set_patrol_route (const std::vector< point > &patrol_pts_rel_ms)
bool can_move_to (const tripoint &p) const
Checks whether we can move to/through p.
bool can_reach_to (const tripoint &p) const
bool will_move_to (const tripoint &p) const
bool know_danger_at (const tripoint &p) const
bool monster_move_in_vehicle (const tripoint &p) const
bool will_reach (const point &p)
int turns_to_reach (const point &p)
bool has_dest () const
tripoint_abs_ms get_dest () const
Creature * attack_target ()
void set_dest (const tripoint_abs_ms &p)
void unset_dest ()
bool is_wandering () const
void wander_to (const tripoint_abs_ms &p, int f)
Set p as wander destination.
float rate_target (Creature &c, float best, bool smart=false) const
bool mating_angry () const
void plan ()
void anger_hostile_seen (const monster_plan &mon_plan)
void anger_mating_season (const monster_plan &mon_plan)
void anger_cub_threatened (monster_plan &mon_plan)
void move ()
void footsteps (const tripoint &p)
void shove_vehicle (const tripoint &remote_destination, const tripoint &nearby_destination)
bool is_aquatic_danger (const tripoint &at_pos) const
Returns true if the given square presents a possibility of drowning for the monster: it's deep water, it's liquid, the monster can drown, and there is no boardable vehicle part present.
bool die_if_drowning (const tripoint &at_pos, int chance=1)
tripoint scent_move ()
int calc_movecost (const tripoint &f, const tripoint &t) const
int calc_climb_cost (const tripoint &f, const tripoint &t) const
bool is_immune_field (const field_type_id &fid) const override
Returns true if we are immune to the field type with the given fid.
bool move_to (const tripoint &p, bool force=false, bool step_on_critter=false, float stagger_adjustment=1.0)
Attempt to move to p.
bool attack_at (const tripoint &p)
Attack any enemies at the given location.
bool bash_at (const tripoint &p)
Try to smash/bash/destroy your way through the terrain at p.
bool push_to (const tripoint &p, int boost, size_t depth)
Try to push away whatever occupies p, then step in.
int bash_skill () const
Returns innate monster bash skill, without calculating additional from helpers.
int bash_estimate () const
int group_bash_skill (const tripoint &target)
Returns ability of monster and any cooperative helpers to bash the designated target.
void stumble ()
Stumble in a random direction, but with some caveats.
void knock_back_to (const tripoint &to) override
bool is_fleeing (Character &u) const
monster_attitude attitude (const Character *u=nullptr) const
Attitude attitude_to (const Creature &other) const override
Attitude (of this creature) towards another creature.
void process_triggers ()
bool is_underwater () const override
bool is_on_ground () const override
bool is_warm () const override
bool in_species (const species_id &spec) const override
void respond_to_light (float light_level)
bool has_weapon () const override
bool is_dead_state () const override
bool is_elec_immune () const override
bool is_immune_effect (const efftype_id &) const override
bool is_immune_damage (const damage_type_id &) const override
void make_bleed (const effect_source &source, time_duration duration, int intensity=1, bool permanent=false, bool force=false, bool defferred=false)
const weakpoint * absorb_hit (const weakpoint_attack &attack, const bodypart_id &bp, damage_instance &dam) override
float weakpoint_skill () const
bool block_hit (Creature *source, bodypart_id &bp_hit, damage_instance &d) override
bool melee_attack (Creature &target)
bool melee_attack (Creature &target, float accuracy)
void melee_attack (Creature &p, bool)=delete
void deal_projectile_attack (Creature *source, dealt_projectile_attack &attack, bool print_messages=true, const weakpoint_attack &wp_attack=weakpoint_attack()) override
Attempts to harm a creature with a projectile.
void deal_damage_handle_type (const effect_source &source, const damage_unit &du, bodypart_id bp, int &damage, int &pain) override
void apply_damage (Creature *source, bodypart_id bp, int dam, bool bypass_med=false) override
void explode ()
void die_in_explosion (Creature *source)
void heal_bp (bodypart_id bp, int dam) override
int heal (int delta_hp, bool overheal=false)
Flat addition to the monsters hp.
void set_hp (int hp)
Directly set the current hp of the monster (not capped at the maximal hp).
void process_effects () override
Processes monster-specific effects before calling Creature::process_effects().
bool movement_impaired ()
Returns true if the monster has its movement impaired.
bool move_effects (bool attacking) override
Processes effects which may prevent the monster from moving (bear traps, crushed, etc.).
std::string get_effect_status () const
Returns a std::string containing effects for descriptions.
float power_rating () const override
Returns an approximation of the creature's strength.
float speed_rating () const override
Returns an approximate number of tiles this creature can travel per turn.
int get_worn_armor_val (const damage_type_id &dt) const
int get_armor_type (const damage_type_id &dt, bodypart_id bp) const override
float get_hit_base () const override
float get_dodge_base () const override
float get_dodge () const override
float get_melee () const override
float hit_roll () const override
Should always be overwritten by the appropriate player/NPC/monster version.
float dodge_roll () const override
bool can_attack_high () const override
int get_grab_strength () const
void add_grab (bodypart_str_id bp)
void remove_grab (bodypart_str_id bp)
bool is_grabbing (bodypart_str_id bp)
monster_horde_attraction get_horde_attraction ()
void set_horde_attraction (monster_horde_attraction mha)
bool will_join_horde (int size)
float fall_damage_mod () const override
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
int impact (int force, const tripoint &pos) override
Deals falling/collision damage with terrain/creature at pos.
bool has_grab_break_tec () const override
float stability_roll () const override
void on_dodge (Creature *source, float difficulty, float training_level=0.0) override
This creature just dodged an attack - possibly special/ranged attack - from source.
void on_try_dodge () override
Invoked when the creature attempts to dodge, regardless of success or failure.
void on_hit (Creature *source, bodypart_id bp_hit, float difficulty=INT_MIN, dealt_projectile_attack const *proj=nullptr) override
This creature just got hit by an attack - possibly special/ranged attack - from source.
void reset_special (const std::string &special_name)
Resets a given special to its monster type cooldown value.
void reset_special_rng (const std::string &special_name)
Resets a given special to a value between 0 and its monster type cooldown value.
void set_special (const std::string &special_name, int time)
Sets a given special to the given value.
void disable_special (const std::string &special_name)
Sets the enabled flag for the given special to false.
bool has_special (const std::string &special_name) const
Test whether the monster has the specified special regardless of readiness.
bool special_available (std::string_view special_name) const
Test whether the specified special is ready.
void process_turn () override
Processes effects and bonuses and allocates move points based on speed.
void reset_bonuses () override
Resets the value of all bonus fields to 0, clears special effect flags.
void reset_stats () override
Resets stats, and applies effects in an idempotent manner.
void die (Creature *killer) override
Empty function.
void drop_items_on_death (item *corpse)
void spawn_dissectables_on_death (item *corpse)
void generate_inventory (bool disableDrops=true)
bool make_fungus ()
Makes this monster into a fungus version Returns false if no such monster exists Returns true if monster is immune or if it got fungalized.
void make_friendly ()
void make_ally (const monster &z)
Makes this monster an ally of the given monster.
void add_item (const item &it)
units::energy use_mech_power (units::energy amt)
Consume UPS from mech battery.
bool check_mech_powered () const
int mech_str_addition () const
void hear_sound (const tripoint &source, int vol, int distance, bool provocative)
Makes monster react to heard sound.
bool is_hallucination () const override
bool is_electrical () const override
bool is_fae () const override
bool is_nether () const override
bool has_mind () const override
field_type_id bloodType () const override
field_type_id gibType () const override
void add_msg_if_npc (const std::string &msg) const override
void add_msg_if_npc (const game_message_params &params, const std::string &msg) const override
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg) const override
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg) const override
units::mass get_carried_weight () const
units::volume get_carried_volume () const
void move_special_item_to_inv (cata::value_ptr< item > &it)
bool is_dead () const
bool is_nemesis () const
item to_item () const
Convert this monster into an item (see mtype::revert_to_itype).
void init_from_item (item &itm)
Initialize values like speed / hp from data of an item.
void on_unload ()
Do some cleanup and caching as monster is being unloaded from map.
void on_load ()
Retroactively update monster.
const pathfinding_settings & get_pathfinding_settings () const override
Returns settings for pathfinding.
std::unordered_set< tripoint > get_path_avoid () const override
Returns a set of points we do not want to path through.
double calculate_by_enchantment (double modify, enchant_vals::mod value, bool round_output=false) const
virtual void add_msg_if_npc (const std::string &) const
virtual void add_msg_if_npc (const game_message_params &, const std::string &) const
void add_msg_if_npc (const translation &) const
void add_msg_if_npc (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_npc (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const translation &msg, Args &&... args) const
virtual void add_msg_player_or_npc (const std::string &, const std::string &) const
virtual void add_msg_player_or_npc (const game_message_params &, const std::string &, const std::string &) const
void add_msg_player_or_npc (const translation &, const translation &) const
void add_msg_player_or_npc (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const translation &player_msg, const translation &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const translation &player_msg, const translation &npc_msg, Args &&... args) const
Public Member Functions inherited from Creature
~Creature () override
virtual std::vector< std::string > get_grammatical_genders () const
virtual bool is_avatar () const
virtual bool is_npc () const
virtual Character * as_character ()
virtual const Character * as_character () const
virtual avatar * as_avatar ()
virtual const avatar * as_avatar () const
virtual npc * as_npc ()
virtual const npc * as_npc () const
virtual bool is_fake () const
Returns true for non-real Creatures used temporarily; i.e.
virtual void set_fake (bool fake_value)
Sets a Creature's fake boolean.
tripoint pos () const
tripoint_bub_ms pos_bub () const
int posx () const
int posy () const
int posz () const
void setpos (const tripoint &p)
void move_to (const tripoint_abs_ms &loc)
Moves the creature to the given location and calls the on_move() handler.
virtual void normalize ()
Recreates the Creature from scratch.
virtual void reset ()
Handles stat and bonus reset.
virtual void bleed () const
Adds an appropriate blood splatter.
bool sees (const Creature &critter) const override
The functions check whether this creature can see the target.
bool sees (const tripoint &t, bool is_avatar=false, int range_mod=0) const override
bool sees (const tripoint_bub_ms &t, bool is_avatar=false, int range_mod=0) const override
Creature * auto_find_hostile_target (int range, int &boo_hoo, int area=0)
For fake-players (turrets, mounted turrets) this functions chooses a target.
double ranged_target_size () const
Size of the target this creature presents to ranged weapons.
void knock_back_from (const tripoint &p)
float get_crit_factor (const bodypart_id &bp) const
int size_melee_penalty () const
virtual int deal_melee_attack (Creature *source, int hitroll)
bool is_adjacent (const Creature *target, bool allow_z_levels) const
virtual damage_instance modify_damage_dealt_with_enchantments (const damage_instance &dam) const
virtual void deal_melee_hit (Creature *source, int hit_spread, bool critical_hit, damage_instance dam, dealt_damage_instance &dealt_dam, const weakpoint_attack &attack=weakpoint_attack(), const bodypart_id *bp=nullptr)
virtual dealt_damage_instance deal_damage (Creature *source, bodypart_id bp, const damage_instance &dam, const weakpoint_attack &attack=weakpoint_attack())
Deals the damage via an attack.
void longpull (const std::string &name, const tripoint &p)
Attempts to pull the target at point p towards this creature.
bool dodge_check (float hit_roll, bool force_try=false, float training_level=0.0f)
If training_level is anything but 0, the check will only train target's skill to that level.
bool dodge_check (monster *z, float training_level=0.0f)
bool dodge_check (monster *z, bodypart_id bp, const damage_instance &dam_inst, float training_level=0.0f)
bool stumble_invis (const Creature &player, bool stumblemsg=true)
bool attack_air (const tripoint &p)
virtual bool is_ranged_attacker () const
Returns true if this monster has a gun-type attack or the RANGED_ATTACKER flag.
bool cant_do_underwater (bool msg=true) const
bool is_likely_underwater () const
bool is_dangerous_fields (const field &fld) const
Returns true if there is a field in the field set that is dangerous to us.
bool is_dangerous_field (const field_entry &entry) const
Returns true if the given field entry is dangerous to us.
virtual bool check_immunity_data (const field_immunity_data &) const
void check_dead_state ()
This function checks the creatures is_dead_state and (if true) calls die.
void add_effect (const effect &eff, bool force=false, bool deferred=false)
void add_effect (const efftype_id &eff_id, const time_duration &dur, bodypart_id bp, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void add_effect (const efftype_id &eff_id, const time_duration &dur, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void add_effect (const effect_source &source, const effect &eff, bool force=false, bool deferred=false)
void add_effect (const effect_source &source, const efftype_id &eff_id, const time_duration &dur, bodypart_id bp, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
Adds or modifies an effect.
void add_effect (const effect_source &source, const efftype_id &eff_id, const time_duration &dur, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void schedule_effect (const effect &eff, bool force=false, bool deferred=false)
Schedules a new effect to be applied.
void schedule_effect (const efftype_id &eff_id, const time_duration &dur, bodypart_id bp, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
void schedule_effect (const efftype_id &eff_id, const time_duration &dur, bool permanent=false, int intensity=0, bool force=false, bool deferred=false)
bool add_env_effect (const efftype_id &eff_id, const bodypart_id &vector, int strength, const time_duration &dur, const bodypart_id &bp, bool permanent=false, int intensity=1, bool force=false)
Gives chance to save via environmental resist, returns false if resistance was successful.
bool add_env_effect (const efftype_id &eff_id, const bodypart_id &vector, int strength, const time_duration &dur, bool permanent=false, int intensity=1, bool force=false)
bool remove_effect (const efftype_id &eff_id, const bodypart_id &bp)
Removes a listed effect.
bool remove_effect (const efftype_id &eff_id)
void schedule_effect_removal (const efftype_id &eff_id, const bodypart_id &bp)
Schedule effect removal.
void schedule_effect_removal (const efftype_id &eff_id)
void clear_effects ()
Remove all effects.
bool has_effect (const efftype_id &eff_id, const bodypart_id &bp) const
Check if creature has the matching effect.
bool has_effect (const efftype_id &eff_id) const
bool has_effect_with_flag (const flag_id &flag, const bodypart_id &bp) const
Check if creature has any effect with the given flag.
bool has_effect_with_flag (const flag_id &flag) const
std::vector< std::reference_wrapper< const effect > > get_effects_with_flag (const flag_id &flag) const
std::vector< std::reference_wrapper< const effect > > get_effects_from_bp (const bodypart_id &bp) const
std::vector< std::reference_wrapper< const effect > > get_effects () const
const effect & get_effect (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Return the effect that matches the given arguments exactly.
effect & get_effect (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID())
time_duration get_effect_dur (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Returns the duration of the matching effect.
int get_effect_int (const efftype_id &eff_id, const bodypart_id &bp=bodypart_str_id::NULL_ID()) const
Returns the intensity of the matching effect.
bool resists_effect (const effect &e) const
Returns true if the creature resists an effect.
void set_value (const std::string &key, const std::string &value)
void remove_value (const std::string &key)
std::string get_value (const std::string &key) const
std::optional< std::string > maybe_get_value (const std::string &key) const
void clear_values ()
virtual bool has_trait (const trait_id &flag) const
Returns true if the player has the entered trait, returns false for non-humans.
virtual void mod_pain (int npain)
virtual void mod_pain_noresist (int npain)
virtual void set_pain (int npain)
virtual int get_pain () const
virtual int get_perceived_pain () const
int get_moves () const
void mod_moves (int nmoves)
void set_moves (int nmoves)
virtual bool in_sleep_state () const
virtual Creature * get_killer () const
virtual int get_num_blocks () const
virtual int get_num_dodges () const
virtual int get_num_blocks_bonus () const
virtual int get_num_dodges_bonus () const
virtual int get_num_dodges_base () const
virtual int get_num_blocks_base () const
virtual int get_env_resist (bodypart_id bp) const
virtual int get_armor_res (const damage_type_id &dt, bodypart_id bp) const
virtual int get_armor_res_base (const damage_type_id &dt, bodypart_id bp) const
virtual int get_armor_res_bonus (const damage_type_id &dt) const
virtual int get_spell_resist () const
virtual float get_hit () const
virtual int get_speed () const
virtual bool uncanny_dodge ()
virtual bool check_avoid_friendly_fire () const
void set_reachable_zone (int zone)
int get_reachable_zone () const
anatomy_id get_anatomy () const
void set_anatomy (const anatomy_id &anat)
bodypart_id get_random_body_part (bool main=false) const
std::vector< bodypart_id > get_all_body_parts (get_body_part_flags=get_body_part_flags::none) const
Returns body parts this creature have.
std::vector< bodypart_id > get_all_body_parts_of_type (body_part_type::type part_type, get_body_part_flags flags=get_body_part_flags::none) const
bodypart_id get_random_body_part_of_type (body_part_type::type part_type) const
bodypart_id get_root_body_part () const
std::vector< bodypart_id > get_all_body_parts_with_flag (const json_character_flag &flag) const
body_part_set get_drenching_body_parts (bool upper=true, bool mid=true, bool lower=true) const
int get_num_body_parts_of_type (body_part_type::type part_type) const
int get_num_broken_body_parts_of_type (body_part_type::type part_type) const
const std::map< bodypart_str_id, bodypart > & get_body () const
void set_body ()
bool has_part (const bodypart_id &id, body_part_filter filter=body_part_filter::strict) const
bodypart * get_part (const bodypart_id &id)
const bodypart * get_part (const bodypart_id &id) const
bodypart_id get_part_id (const bodypart_id &id, body_part_filter filter=body_part_filter::next_best, bool suppress_debugmsg=false) const
int get_part_hp_cur (const bodypart_id &id) const
int get_part_hp_max (const bodypart_id &id) const
int get_part_healed_total (const bodypart_id &id) const
int get_part_damage_disinfected (const bodypart_id &id) const
int get_part_damage_bandaged (const bodypart_id &id) const
int get_part_drench_capacity (const bodypart_id &id) const
int get_part_wetness (const bodypart_id &id) const
units::temperature get_part_temp_cur (const bodypart_id &id) const
units::temperature get_part_temp_conv (const bodypart_id &id) const
int get_part_frostbite_timer (const bodypart_id &id) const
std::array< int, NUM_WATER_TOLERANCE > get_part_mut_drench (const bodypart_id &id) const
float get_part_wetness_percentage (const bodypart_id &id) const
const encumbrance_data & get_part_encumbrance_data (const bodypart_id &id) const
virtual void set_part_hp_cur (const bodypart_id &id, int set)
void set_part_hp_max (const bodypart_id &id, int set)
void set_part_healed_total (const bodypart_id &id, int set)
void set_part_damage_disinfected (const bodypart_id &id, int set)
void set_part_damage_bandaged (const bodypart_id &id, int set)
void set_part_encumbrance_data (const bodypart_id &id, const encumbrance_data &set)
void set_part_wetness (const bodypart_id &id, int set)
void set_part_temp_cur (const bodypart_id &id, units::temperature set)
void set_part_temp_conv (const bodypart_id &id, units::temperature set)
void set_part_frostbite_timer (const bodypart_id &id, int set)
void set_part_mut_drench (const bodypart_id &id, std::pair< water_tolerance, int > set)
virtual void mod_part_hp_cur (const bodypart_id &id, int mod)
void mod_part_hp_max (const bodypart_id &id, int mod)
void mod_part_healed_total (const bodypart_id &id, int mod)
void mod_part_damage_disinfected (const bodypart_id &id, int mod)
void mod_part_damage_bandaged (const bodypart_id &id, int mod)
void mod_part_wetness (const bodypart_id &id, int mod)
void mod_part_temp_cur (const bodypart_id &id, units::temperature_delta mod)
void mod_part_temp_conv (const bodypart_id &id, units::temperature_delta mod)
void mod_part_frostbite_timer (const bodypart_id &id, int mod)
void set_all_parts_temp_cur (units::temperature set)
void set_all_parts_temp_conv (units::temperature set)
void set_all_parts_wetness (int set)
void set_all_parts_hp_cur (int set)
void set_all_parts_hp_to_max ()
bool has_atleast_one_wet_part () const
bool is_part_at_max_hp (const bodypart_id &id) const
virtual int get_speed_base () const
virtual int get_speed_bonus () const
virtual int get_block_bonus () const
virtual int get_bash_bonus () const
virtual int get_cut_bonus () const
virtual float get_dodge_bonus () const
virtual float get_hit_bonus () const
virtual float get_bash_mult () const
virtual float get_cut_mult () const
virtual bool get_melee_quiet () const
virtual int get_throw_resist () const
virtual void mod_stat (const std::string &stat, float modifier)
virtual void set_num_blocks_bonus (int nblocks)
virtual void mod_num_blocks_bonus (int nblocks)
virtual void mod_num_dodges_bonus (int ndodges)
virtual void set_armor_res_bonus (int narm, const damage_type_id &dt)
virtual void set_speed_base (int nspeed)
virtual void set_speed_bonus (int nspeed)
virtual void set_block_bonus (int nblock)
virtual void set_bash_bonus (int nbash)
virtual void set_cut_bonus (int ncut)
virtual void mod_speed_bonus (int nspeed)
virtual void mod_block_bonus (int nblock)
virtual void mod_bash_bonus (int nbash)
virtual void mod_cut_bonus (int ncut)
virtual void mod_size_bonus (int nsize)
virtual void set_dodge_bonus (float ndodge)
virtual void set_hit_bonus (float nhit)
virtual void mod_dodge_bonus (float ndodge)
virtual void mod_hit_bonus (float nhit)
virtual void set_bash_mult (float nbashmult)
virtual void set_cut_mult (float ncutmult)
virtual void set_melee_quiet (bool nquiet)
virtual void set_throw_resist (int nthrowres)
void draw (const catacurses::window &w, const point &origin, bool inverted) const
void draw (const catacurses::window &w, const tripoint &origin, bool inverted) const
void describe_infrared (std::vector< std::string > &buf) const
Describe this creature as seen by the avatar via infrared vision.
void describe_specials (std::vector< std::string > &buf) const
Describe this creature as detected by the avatar's special senses.
virtual void add_msg_if_player (const std::string &) const
virtual void add_msg_if_player (const game_message_params &, const std::string &) const
void add_msg_if_player (const translation &) const
void add_msg_if_player (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_player (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_player (const game_message_params &params, const translation &msg, Args &&... args) const
void add_msg_if_npc (const translation &) const
void add_msg_if_npc (const game_message_params &, const translation &) const
template<typename ... Args>
void add_msg_if_npc (const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const translation &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const char *const msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const std::string &msg, Args &&... args) const
template<typename ... Args>
void add_msg_if_npc (const game_message_params &params, const translation &msg, Args &&... args) const
void add_msg_player_or_npc (const translation &, const translation &) const
void add_msg_player_or_npc (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_npc (const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const translation &player_msg, const translation &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const char *const player_msg, const char *const npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const std::string &player_msg, const std::string &npc_msg, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_npc (const game_message_params &params, const translation &player_msg, const translation &npc_msg, Args &&... args) const
virtual void add_msg_player_or_say (const std::string &, const std::string &) const
virtual void add_msg_player_or_say (const game_message_params &, const std::string &, const std::string &) const
void add_msg_player_or_say (const translation &, const translation &) const
void add_msg_player_or_say (const game_message_params &, const translation &, const translation &) const
template<typename ... Args>
void add_msg_player_or_say (const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const translation &player_msg, const translation &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const char *const player_msg, const char *const npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const std::string &player_msg, const std::string &npc_speech, Args &&... args) const
template<typename ... Args>
void add_msg_player_or_say (const game_message_params &params, const translation &player_msg, const translation &npc_speech, Args &&... args) const
std::unordered_map< std::string, std::string > & get_values ()
void clear_killer ()
void set_summon_time (const time_duration &length)
void decrement_summon_timer ()
void set_summoner (Creature *summoner)
void set_summoner (character_id summoner)
Creature * get_summoner () const
bodypart_id get_max_hitsize_bodypart () const
bodypart_id select_body_part (int min_hit, int max_hit, bool can_attack_high, int hit_roll) const
bodypart_id select_blocking_part (bool arm, bool leg, bool nonstandard) const
bodypart_id random_body_part (bool main_parts_only=false) const
std::vector< bodypart_id > get_all_eligable_parts (int min_hit, int max_hit, bool can_attack_high) const
void add_damage_over_time (const damage_over_time_data &DoT)
void process_damage_over_time ()
std::string replace_with_npc_name (std::string input) const
This function replaces the "<npcname>" substring with the disp_name of this creature.
tripoint_abs_ms get_location () const
Returns the location of the creature in map square coordinates (the most detailed coordinate system), relative to a fixed global point of origin.
tripoint_abs_sm global_sm_location () const
Returns the location of the creature in global submap coordinates.
tripoint_abs_omt global_omt_location () const
Returns the location of the creature in global overmap terrain coordinates.
Public Member Functions inherited from viewer
virtual ~viewer ()=default
Static Public Member Functions
static std::string speed_description (float mon_speed_rating, bool immobile=false, const speed_description_id &speed_desc=speed_description_id::NULL_ID())
Static Public Member Functions inherited from Creature
static std::string attitude_raw_string (Attitude att)
Simplified attitude string for unlocalized needs.
static const std::pair< translation, nc_color > & get_attitude_ui_data (Attitude att)
Creature Attitude as String and color.
static void load_hit_range (const JsonObject &)
Public Attributes
std::unordered_set< bodypart_str_id > grabbed_limbs
tripoint_abs_ms wander_pos
bool provocative_sound = false
int wandf = 0
std::vector< item > inv
std::vector< item > dissectable_inv
Character * mounted_player = nullptr
character_id mounted_player_id
character_id dragged_foe_id
cata::value_ptr< item > tied_item
cata::value_ptr< item > tack_item
cata::value_ptr< item > armor_item
cata::value_ptr< item > storage_item
cata::value_ptr< item > battery_item
int friendly = 0
int anger = 0
int morale = 0
int stomach_size = 0
int amount_eaten = 0
mfaction_id faction
std::set< int > mission_ids
std::vector< std::string > mission_fused
const mtype * type
bool no_extra_death_drops = false
bool no_corpse_quiet = false
bool death_drops = true
bool quiet_death = false
bool made_footstep = false
std::string unique_name
std::string nickname
bool hallucination = false
int fish_population = 1
short ignoring = 0
bool aggro_character = true
std::optional< time_point > lastseen_turn
pimpl< enchant_cache > enchantment_cache
int staircount = 0
std::map< itype_id, int > ammo
Public Attributes inherited from Creature
FacingDirection facing = FacingDirection::RIGHT
return the direction the creature is facing, for sdl horizontal flip
bool underwater
int archery_aim_counter = 0
Protected Member Functions
void store (JsonOut &json) const
void load (const JsonObject &data)
void load (const JsonObject &data, const tripoint_abs_sm &submap_loc)
void on_move (const tripoint_abs_ms &old_pos) override
void process_one_effect (effect &it, bool is_new) override
Processes monster-specific effects of an effect.
Protected Member Functions inherited from Creature
void set_pos_only (const tripoint &p)
void set_location (const tripoint_abs_ms &loc)
void set_killer (Creature *killer)
Creature ()
Creature (const Creature &)
Creature (Creature &&) noexcept(map_is_noexcept)
Creature & operator= (const Creature &)
Creature & operator= (Creature &&) noexcept
virtual void on_stat_change (const std::string &, int)
virtual void on_effect_int_change (const efftype_id &, int, const bodypart_id &)
virtual void on_damage_of_type (const effect_source &, int, const damage_type_id &, const bodypart_id &)
void store (JsonOut &jsout) const
These two functions are responsible for storing and loading the members of this class to/from json data.
void load (const JsonObject &jsin)
Private Member Functions
void process_trigger (mon_trigger trig, int amount)
void process_trigger (mon_trigger trig, const std::function< int()> &amount_func)
int next_upgrade_time ()
Normal upgrades.
bool can_pathfind () const
void reset_pathfinding_cd ()
void increment_pathfinding_cd ()
Character * find_dragged_foe ()
void nursebot_operate (Character *dragged_foe)
Private Attributes
int hp = 0
std::map< std::string, mon_special_attack, std::less<> > special_attacks
std::optional< tripoint_abs_ms > goal
bool dead = false
bool upgrades = false
int upgrade_time = 0
bool reproduces = false
std::optional< time_point > baby_timer
bool biosignatures = false
std::optional< time_point > biosig_timer
time_point udder_timer
time_point stomach_timer
monster_horde_attraction horde_attraction = MHA_NULL
std::vector< tripoint > path
Found path.
time_point pathfinding_cd = calendar::turn
time_duration pathfinding_backoff = 2_seconds
std::vector< tripoint_abs_ms > patrol_route
patrol points for monsters that can pathfind and have a patrol route!
int next_patrol_point = -1
std::bitset< NUM_MEFF > effect_cache
int turns_since_target = 0
Friends
class editmap
Additional Inherited Members
Public Types inherited from Creature
enum class Attitude : int { HOSTILE , NEUTRAL , FRIENDLY , ANY }
Simplified attitude towards any creature: hostile - hate, want to kill, etc.
Static Public Attributes inherited from Creature
static const std::map< std::string, creature_size > size_map
static const std::set< material_id > cmat_flesh
static const std::set< material_id > cmat_fleshnveg
static const std::set< material_id > cmat_flammable
static const std::set< material_id > cmat_flameres
static std::vector< int > dispersion_for_even_chance_of_good_hit
Protected Attributes inherited from Creature
anatomy_id creature_anatomy = anatomy_id("default_anatomy")
anatomy is the plan of the creature's body
std::map< bodypart_str_id, bodypart > body
this is the actual body of the creature
int moves
Creature * killer
std::optional< time_point > lifespan_end = std::nullopt
std::optional< character_id > summoner = std::nullopt
pimpl< effects_map > effects
std::queue< scheduled_effect, std::list< scheduled_effect > > scheduled_effects
std::queue< terminating_effect, std::list< terminating_effect > > terminating_effects
std::vector< damage_over_time_data > damage_over_time_map
std::unordered_map< std::string, std::string > values
int num_blocks = 0
int num_dodges = 0
int num_blocks_bonus = 0
int num_dodges_bonus = 0
std::map< damage_type_id, float > armor_bonus
int speed_base = 0
int speed_bonus = 0
float dodge_bonus = 0.0f
int block_bonus = 0
float hit_bonus = 0.0f
int bash_bonus = 0
int cut_bonus = 0
int size_bonus = 0
float bash_mult = 0.0f
float cut_mult = 0.0f
bool melee_quiet = false
int throw_resist = 0
time_point last_updated
bool fake = false
Detailed Description
Definition at line 85 of file monster.h.
Constructor & Destructor Documentation
monster() [1/5]
monster::monster ()
Definition at line 260 of file monster.cpp.
 {
     unset_dest();
     wandf = 0;
     hp = 60;
     moves = 0;
     friendly = 0;
     anger = 0;
     morale = 2;
     faction = mfaction_id( 0 );
     no_extra_death_drops = false;
     dead = false;
     death_drops = true;
     made_footstep = false;
     hallucination = false;
     ignoring = 0;
     upgrades = false;
     upgrade_time = -1;
     stomach_timer = calendar::turn;
     last_updated = calendar::turn_zero;
     biosig_timer = calendar::before_time_starts;
     udder_timer = calendar::turn;
     horde_attraction = MHA_NULL;
     aggro_character = true;
     set_anatomy( anatomy_default_anatomy );
     set_body();
 }
References aggro_character, anatomy_default_anatomy, anger, calendar::before_time_starts, biosig_timer, dead, death_drops, friendly, hallucination, horde_attraction, hp, ignoring, Creature::last_updated, made_footstep, MHA_NULL, morale, Creature::moves, no_extra_death_drops, Creature::set_anatomy(), Creature::set_body(), stomach_timer, calendar::turn, calendar::turn_zero, udder_timer, unset_dest(), upgrade_time, upgrades, and wandf.
monster() [2/5]
monster::monster (const mtype_id & id) explicit
Definition at line 288 of file monster.cpp.
                                      : monster()
 {
     type = &id.obj();
     moves = type->speed;
     Creature::set_speed_base( type->speed );
     hp = type->hp;
     for( const auto &sa : type->special_attacks ) {
         mon_special_attack &entry = special_attacks[sa.first];
         entry.cooldown = rng( 0, sa.second->cooldown );
     }
     anger = type->agro;
     morale = type->morale;
     stomach_size = type->stomach_size;
     faction = type->default_faction;
     upgrades = type->upgrades && ( type->half_life || type->age_grow );
     reproduces = type->reproduces && type->baby_timer && !monster::has_flag( mon_flag_NO_BREED );
     biosignatures = type->biosignatures;
     if( monster::has_flag( mon_flag_AQUATIC ) ) {
         fish_population = dice( 1, 20 );
     }
     if( monster::has_flag( mon_flag_RIDEABLE_MECH ) ) {
         itype_id mech_bat = itype_id( type->mech_battery );
         const itype &type = *item::find_type( mech_bat );
         int max_charge = type.magazine->capacity;
         item mech_bat_item = item( mech_bat, calendar::turn_zero );
         mech_bat_item.ammo_consume( rng( 0, max_charge ), tripoint_zero, nullptr );
         battery_item = cata::make_value<item>( mech_bat_item );
     }
     if( monster::has_flag( mon_flag_PET_MOUNTABLE ) ) {
         if( !type->mount_items.tied.is_empty() ) {
             itype_id tied_item_id = itype_id( type->mount_items.tied );
             item tied_item_item = item( tied_item_id, calendar::turn_zero );
             add_effect( effect_leashed, 1_turns, true );
             tied_item = cata::make_value<item>( tied_item_item );
         }
         if( !type->mount_items.tack.is_empty() ) {
             itype_id tack_item_id = itype_id( type->mount_items.tack );
             item tack_item_item = item( tack_item_id, calendar::turn_zero );
             add_effect( effect_monster_saddled, 1_turns, true );
             tack_item = cata::make_value<item>( tack_item_item );
         }
         if( !type->mount_items.armor.is_empty() ) {
             itype_id armor_item_id = itype_id( type->mount_items.armor );
             item armor_item_item = item( armor_item_id, calendar::turn_zero );
             add_effect( effect_monster_armor, 1_turns, true );
             armor_item = cata::make_value<item>( armor_item_item );
         }
         if( !type->mount_items.storage.is_empty() ) {
             itype_id storage_item_id = itype_id( type->mount_items.storage );
             item storage_item_item = item( storage_item_id, calendar::turn_zero );
             add_effect( effect_has_bag, 1_turns, true );
             tack_item = cata::make_value<item>( storage_item_item );
         }
     }
     aggro_character = type->aggro_character;
 }
References Creature::add_effect(), mtype::age_grow, aggro_character, mtype::aggro_character, mtype::agro, item::ammo_consume(), anger, mount_item_data::armor, armor_item, mtype::baby_timer, battery_item, biosignatures, mtype::biosignatures, mon_special_attack::cooldown, mtype::default_faction, dice(), effect_has_bag, effect_leashed, effect_monster_armor, effect_monster_saddled, item::find_type(), fish_population, mtype::half_life, has_flag(), hp, mtype::hp, string_id< T >::is_empty(), item, itype_id, mtype::mech_battery, mon_flag_AQUATIC, mon_flag_NO_BREED, mon_flag_PET_MOUNTABLE, mon_flag_RIDEABLE_MECH, morale, mtype::morale, mtype::mount_items, Creature::moves, reproduces, mtype::reproduces, rng(), Creature::set_speed_base(), special_attacks, mtype::special_attacks, mtype::speed, stomach_size, mtype::stomach_size, mount_item_data::storage, mount_item_data::tack, tack_item, mount_item_data::tied, tied_item, tripoint_zero, calendar::turn_zero, type, upgrades, and mtype::upgrades.
monster() [3/5]
monster::monster (const mtype_id & id, const tripoint & pos)
Definition at line 345 of file monster.cpp.
                                                         : monster( id )
 {
     set_pos_only( p );
     unset_dest();
 }
References Creature::set_pos_only(), and unset_dest().
monster() [4/5]
monster::monster (const monster &) default
monster() [5/5]
monster::monster (monster &&) default noexcept
~monster()
monster::~monster () override default
Member Function Documentation
absorb_hit()
const weakpoint * monster::absorb_hit (const weakpoint_attack & attack, const bodypart_id & bp, damage_instance & dam) override virtual
Implements Creature.
Definition at line 1875 of file monster.cpp.
 {
     resistances r = resistances( *this );
     const weakpoint *wp = type->weakpoints.select_weakpoint( attack );
     wp->apply_to( r );
     for( damage_unit &elem : dam.damage_units ) {
         armor_enchantment_adjust( *this, elem );
         add_msg_debug( debugmode::DF_MONSTER,
                        "Dam Type: %s :: Dam Amt: %.1f :: Ar Pen: %.1f :: Armor Mult: %.1f",
                        elem.type.c_str(), elem.amount, elem.res_pen, elem.res_mult );
         add_msg_debug( debugmode::DF_MONSTER,
                        "Weakpoint: %s :: Armor Mult: %.1f :: Armor Penalty: %.1f :: Resist: %.1f",
                        wp->id, wp->armor_mult.count( elem.type ) > 0 ? wp->armor_mult.at( elem.type ) : 0.f,
                        wp->armor_penalty.count( elem.type ) > 0 ? wp->armor_penalty.at( elem.type ) : 0.f,
                        r.get_effective_resist( elem ) );
         elem.amount -= std::min( r.get_effective_resist( elem ) +
                                  get_worn_armor_val( elem.type ), elem.amount );
     }
     wp->apply_to( dam, attack.is_crit );
     return wp;
 }
References add_msg_debug, damage_unit::amount, weakpoint::apply_to(), armor_enchantment_adjust(), weakpoint::armor_mult, weakpoint::armor_penalty, spell_effect::attack(), string_id< T >::c_str(), damage_instance::damage_units, debugmode::DF_MONSTER, resistances::get_effective_resist(), get_worn_armor_val(), weakpoint::id, min(), damage_unit::res_mult, damage_unit::res_pen, weakpoints::select_weakpoint(), damage_unit::type, type, and mtype::weakpoints.
add_grab()
void monster::add_grab (bodypart_str_id bp)
Definition at line 2505 of file monster.cpp.
 {
     add_effect( effect_grabbing, 1_days, true, 1 );
     grabbed_limbs.insert( bp );
 }
References Creature::add_effect(), bp, effect_grabbing, and grabbed_limbs.
Referenced by melee_actor::do_grab().
add_item()
void monster::add_item (const item & it)
Definition at line 3455 of file monster.cpp.
 {
     inv.push_back( it );
 }
References inv.
Referenced by anonymous_namespace{monexamine.cpp}::attach_bag_to(), die(), drop_or_embed_projectile(), move_special_item_to_inv(), mattack::searchlight(), and stash_on_pet().
add_msg_if_npc() [1/12]
template<typename ... Args> void Creature::add_msg_if_npc (typename ... Args) inline
Definition at line 1024 of file creature.h.
{
             return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
         }
add_msg_if_npc() [2/12]
virtual void Creature::add_msg_if_npc inline
Definition at line 1019 of file creature.h.
                                                                 {}
add_msg_if_npc() [3/12]
void Creature::add_msg_if_npc
Definition at line 1022 of file creature.cpp.
 {
     return add_msg_if_npc( params, msg.translated() );
 }
add_msg_if_npc() [4/12]
template<typename ... Args> void Creature::add_msg_if_npc (typename ... Args) inline
Definition at line 1036 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
         }
add_msg_if_npc() [5/12]
void monster::add_msg_if_npc (const game_message_params & params, const std::string & msg) const override virtual
Reimplemented from Creature.
Definition at line 3534 of file monster.cpp.
 {
     add_msg_if_player_sees( *this, params, replace_with_npc_name( msg ) );
 }
References add_msg_if_player_sees(), and Creature::replace_with_npc_name().
add_msg_if_npc() [6/12]
template<typename ... Args> void Creature::add_msg_if_npc (typename ... Args) inline
Definition at line 1044 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
         }
add_msg_if_npc() [7/12]
template<typename ... Args> void Creature::add_msg_if_npc (typename ... Args) inline
Definition at line 1052 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_if_npc( params, string_format( msg, std::forward<Args>( args )... ) );
         }
add_msg_if_npc() [8/12]
virtual void Creature::add_msg_if_npc inline
Definition at line 1018 of file creature.h.
 {}
add_msg_if_npc() [9/12]
void monster::add_msg_if_npc (const std::string & msg) const override virtual
Reimplemented from Creature.
Definition at line 3523 of file monster.cpp.
 {
     add_msg_if_player_sees( *this, replace_with_npc_name( msg ) );
 }
References add_msg_if_player_sees(), and Creature::replace_with_npc_name().
add_msg_if_npc() [10/12]
template<typename ... Args> void Creature::add_msg_if_npc (typename ... Args) inline
Definition at line 1028 of file creature.h.
{
             return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
         }
add_msg_if_npc() [11/12]
void Creature::add_msg_if_npc
Definition at line 1021 of file creature.cpp.
 {
     return add_msg_if_npc( msg.translated() );
 }
add_msg_if_npc() [12/12]
template<typename ... Args> void Creature::add_msg_if_npc (typename ... Args) inline
Definition at line 1032 of file creature.h.
{
             return add_msg_if_npc( string_format( msg, std::forward<Args>( args )... ) );
         }
add_msg_player_or_npc() [1/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (typename ... Args) inline
Definition at line 1071 of file creature.h.
{
             return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
add_msg_player_or_npc() [2/12]
virtual void Creature::add_msg_player_or_npc inline
Definition at line 1062 of file creature.h.
                                                                        {}
add_msg_player_or_npc() [3/12]
void Creature::add_msg_player_or_npc
Definition at line 1067 of file creature.cpp.
 {
     return add_msg_player_or_npc( params, pc.translated(), npc.translated() );
 }
add_msg_player_or_npc() [4/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (typename ... Args) inline
Definition at line 1089 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
add_msg_player_or_npc() [5/12]
void monster::add_msg_player_or_npc (const game_message_params & params, const std::string & player_msg, const std::string & npc_msg) const override virtual
Reimplemented from Creature.
Definition at line 3539 of file monster.cpp.
 {
     add_msg_if_player_sees( *this, params, replace_with_npc_name( npc_msg ) );
 }
References add_msg_if_player_sees(), and Creature::replace_with_npc_name().
add_msg_player_or_npc() [6/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (typename ... Args) inline
Definition at line 1098 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
add_msg_player_or_npc() [7/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (typename ... Args) inline
Definition at line 1107 of file creature.h.
{
             if( params.type == m_debug && !debug_mode ) {
                 return;
             }
             return add_msg_player_or_npc( params, string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
add_msg_player_or_npc() [8/12]
virtual void Creature::add_msg_player_or_npc inline
Definition at line 1060 of file creature.h.
                                                                        {}
add_msg_player_or_npc() [9/12]
void monster::add_msg_player_or_npc (const std::string & player_msg, const std::string & npc_msg) const override virtual
Reimplemented from Creature.
Definition at line 3528 of file monster.cpp.
 {
     add_msg_if_player_sees( *this, replace_with_npc_name( npc_msg ) );
 }
References add_msg_if_player_sees(), and Creature::replace_with_npc_name().
add_msg_player_or_npc() [10/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (typename ... Args) inline
Definition at line 1077 of file creature.h.
{
             return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
add_msg_player_or_npc() [11/12]
void Creature::add_msg_player_or_npc
Definition at line 1065 of file creature.cpp.
 {
     return add_msg_player_or_npc( pc.translated(), npc.translated() );
 }
add_msg_player_or_npc() [12/12]
template<typename ... Args> void Creature::add_msg_player_or_npc (typename ... Args) inline
Definition at line 1083 of file creature.h.
{
             return add_msg_player_or_npc( string_format( player_msg, std::forward<Args>( args )... ),
                                           string_format( npc_msg, std::forward<Args>( args )... ) );
         }
allow_upgrade()
void monster::allow_upgrade ()
Definition at line 424 of file monster.cpp.
 {
     upgrade_time = 0;
 }
References upgrade_time.
Referenced by mattack::evolve_kill_strike(), and spell_effect::upgrade().
anger_cub_threatened()
void monster::anger_cub_threatened (monster_plan & mon_plan)
Definition at line 478 of file monmove.cpp.
 {
     if( mon_plan.angers_cub_threatened < 0 ) {
         // return early, not angered by cubs being threatened
         return;
     }
     for( monster &tmp : g->all_monsters() ) {
         if( type->baby_monster == tmp.type->id ) {
             // baby nearby; is the player too close?
             mon_plan.dist = tmp.rate_target( *mon_plan.target, mon_plan.dist, mon_plan.smart_planning );
             if( mon_plan.dist <= 3 ) {
                 //proximity to baby; monster gets furious and less likely to flee
                 anger += mon_plan.angers_cub_threatened;
                 morale += mon_plan.angers_cub_threatened / 2;
                 add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro triggered by threatening %s", name(),
                                tmp.name() );
                 aggro_character = true;
             }
         }
     }
 }
References add_msg_debug, aggro_character, anger, monster_plan::angers_cub_threatened, mtype::baby_monster, debugmode::DF_MONSTER, monster_plan::dist, g, mtype::id, morale, name(), monster_plan::smart_planning, monster_plan::target, and type.
Referenced by plan().
anger_hostile_seen()
void monster::anger_hostile_seen (const monster_plan & mon_plan)
Definition at line 446 of file monmove.cpp.
 {
     if( mon_plan.fleeing ) {
         // runng away, too busy to be angry
         return;
     }
     // Decide that the player is too annoying, less likely than the other triggers
     if( mon_plan.angers_hostile_seen && x_in_y( anger, 200 ) ) {
         if( mon_plan.target->is_avatar() ) {
             add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro triggered by seeing you", name() );
         } else {
             add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro triggered by seeing %s", name(),
                            mon_plan.target->as_npc()->name );
         }
         aggro_character = true;
     }
 }
References add_msg_debug, aggro_character, anger, monster_plan::angers_hostile_seen, Creature::as_npc(), debugmode::DF_MONSTER, monster_plan::fleeing, Creature::is_avatar(), Character::name, name(), monster_plan::target, and x_in_y().
Referenced by plan().
anger_mating_season()
void monster::anger_mating_season (const monster_plan & mon_plan)
Definition at line 465 of file monmove.cpp.
 {
     if( mon_plan.angers_mating_season > 0 && anger <= 30 ) {
         if( mating_angry() ) {
             anger += mon_plan.angers_mating_season;
             if( x_in_y( anger, 100 ) ) {
                 add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro triggered by season", name() );
                 aggro_character = true;
             }
         }
     }
 }
References add_msg_debug, aggro_character, anger, monster_plan::angers_mating_season, debugmode::DF_MONSTER, mating_angry(), name(), and x_in_y().
Referenced by plan().
apply_damage()
void monster::apply_damage (Creature * source, bodypart_id bp, int dam, bool bypass_med = false) override virtual
Implements Creature.
Definition at line 2169 of file monster.cpp.
 {
     if( is_dead_state() ) {
         return;
     }
     // Ensure we can try to get at what hit us.
     reset_pathfinding_cd();
     hp -= dam;
     if( hp < 1 ) {
         set_killer( source );
     } else if( dam > 0 ) {
         process_trigger( mon_trigger::HURT, 1 + static_cast<int>( dam / 3 ) );
         // Get angry at characters if hurt by one
         if( source != nullptr && !aggro_character && !source->is_monster() && !source->is_fake() ) {
             aggro_character = true;
         }
     }
 }
References aggro_character, hp, HURT, is_dead_state(), Creature::is_fake(), Creature::is_monster(), process_trigger(), reset_pathfinding_cd(), and Creature::set_killer().
Referenced by anonymous_namespace{monexamine.cpp}::cull(), mattack::dermatik(), spell_effect::directed_push(), map::drop_furniture(), explosion_handler::emp_blast(), iuse::extinguisher(), game::fling_creature(), game::forced_door_closing(), fungal_effects::fungalize(), impact(), knock_back_to(), map::monster_in_field(), move_to(), process_effects(), process_one_effect(), and map::shake_vehicle().
as_monster() [1/2]
const monster* monster::as_monster () const inline override virtual
Reimplemented from Creature.
Definition at line 104 of file monster.h.
{
             return this;
         }
as_monster() [2/2]
monster* monster::as_monster () inline override virtual
Reimplemented from Creature.
Definition at line 101 of file monster.h.
{
             return this;
         }
Referenced by Character::fire_gun(), and item::handle_pickup_ownership().
attack_at()
bool monster::attack_at (const tripoint & p)
Attack any enemies at the given location.
Attacks only if there is a creature at the given location towards we are hostile.
Returns
true if something was attacked, false otherwise
Definition at line 1778 of file monmove.cpp.
 {
     if( has_flag( mon_flag_PACIFIST ) ) {
         return false;
     }
     Character &player_character = get_player_character();
     const bool sees_player = sees( player_character );
     // Targeting player location
     if( p == player_character.pos() ) {
         if( sees_player ) {
             return melee_attack( player_character );
         } else {
             // Creature stumbles into a player it cannot see, briefly becoming aware of their location
             return stumble_invis( player_character );
         }
     }
     creature_tracker &creatures = get_creature_tracker();
     if( monster *mon_ = creatures.creature_at<monster>( p, is_hallucination() ) ) {
         monster &mon = *mon_;
         // Don't attack yourself.
         if( &mon == this ) {
             return false;
         }
         // With no melee dice, we can't attack, but we had to process until here
         // because hallucinations require no melee dice to destroy.
         if( type->melee_dice <= 0 ) {
             return false;
         }
         Creature::Attitude attitude = attitude_to( mon );
         // mon_flag_ATTACKMON == hulk behavior, whack everything in your way
         if( attitude == Attitude::HOSTILE || has_flag( mon_flag_ATTACKMON ) ) {
             return melee_attack( mon );
         }
         return false;
     }
     npc *const guy = creatures.creature_at<npc>( p, is_hallucination() );
     if( guy && type->melee_dice > 0 ) {
         // For now we're always attacking NPCs that are getting into our
         // way. This is consistent with how it worked previously, but
         // later on not hitting allied NPCs would be cool.
         guy->on_attacked( *this ); // allow NPC hallucination to be one shot by monsters
         return melee_attack( *guy );
     }
     // Attack last known position despite empty
     if( has_effect( effect_stumbled_into_invisible ) &&
         get_map().has_field_at( p, field_fd_last_known ) && !sees_player &&
         attitude_to( player_character ) == Attitude::HOSTILE ) {
         return attack_air( p );
     }
     // Nothing to attack.
     return false;
 }
References Creature::attack_air(), attitude(), attitude_to(), creature_tracker::creature_at(), effect_stumbled_into_invisible, field_fd_last_known, get_creature_tracker(), get_map(), get_player_character(), Creature::has_effect(), has_flag(), Creature::HOSTILE, is_hallucination(), melee_attack(), mtype::melee_dice, mon_flag_ATTACKMON, mon_flag_PACIFIST, npc::on_attacked(), Creature::pos(), Creature::sees(), Creature::stumble_invis(), and type.
Referenced by move().
attack_target()
Creature * monster::attack_target ()
Definition at line 1405 of file monster.cpp.
 {
     if( !has_dest() ) {
         return nullptr;
     }
     Creature *target = get_creature_tracker().creature_at( get_dest() );
     if( target == nullptr || target == this ||
         attitude_to( *target ) == Attitude::FRIENDLY || !sees( *target ) || target->is_hallucination() ) {
         return nullptr;
     }
     return target;
 }
References attitude_to(), creature_tracker::creature_at(), Creature::FRIENDLY, get_creature_tracker(), get_dest(), has_dest(), Creature::is_hallucination(), and Creature::sees().
Referenced by mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), leap_actor::call(), mon_spellcasting_actor::call(), melee_actor::call(), gun_actor::call(), mattack::chickenbot(), mattack::copbot(), mattack::dermatik(), mattack::evolve_kill_strike(), melee_actor::find_target(), mattack::flesh_golem(), mattack::flesh_tendril(), mattack::fungus_bristle(), mattack::howl(), mattack::kamikaze(), mattack::lunge(), mattack::multi_robot(), mattack::pull_metal_weapon(), mattack::riotbot(), mattack::science(), mattack::shockstorm(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), mattack::smash(), mattack::spit_sap(), sting_get_target(), mattack::stretch_attack(), mattack::suicide(), mattack::tazer(), and mattack::tindalos_teleport().
attitude()
monster_attitude monster::attitude (const Character * u = nullptr) const
Definition at line 1496 of file monster.cpp.
 {
     // override for the Personal Portal Storms Mod
     // if the monster is a nether portal monster and the character is an NPC then ignore
     if( u != nullptr && faction == monfaction_nether_player_hate && u->is_npc() &&
         get_option<bool>( "PORTAL_STORM_IGNORE_NPC" ) ) {
         // portal storm creatures ignore NPCs no matter what with this mod on
         return MATT_FPASSIVE;
     }
     if( friendly != 0 ) {
         if( has_effect( effect_docile ) ) {
             return MATT_FPASSIVE;
         }
         if( u != nullptr ) {
             if( u->is_avatar() ) {
                 return MATT_FRIEND;
             }
             if( u->is_npc() ) {
                 // Zombies don't understand not attacking NPCs, but dogs and bots should.
                 if( u->get_attitude() != NPCATT_KILL && !type->in_species( species_ZOMBIE ) ) {
                     return MATT_FRIEND;
                 }
                 if( u->is_hallucination() ) {
                     return MATT_IGNORE;
                 }
             }
         }
     }
     if( effect_cache[FLEEING] ) {
         return MATT_FLEE;
     }
     int effective_anger  = anger;
     int effective_morale = morale;
     if( u != nullptr ) {
         if( faction == monfaction_bee ) {
             if( u->has_trait( trait_BEE ) ) {
                 return MATT_FRIEND;
             } else if( u->has_trait( trait_FLOWERS ) ) {
                 effective_anger -= 10;
             }
         }
         auto *u_fac = u->get_faction();
         if( u_fac && u_fac->mon_faction && faction == u_fac->mon_faction ) {
             return MATT_FRIEND;
         }
         if( type->in_species( species_FUNGUS ) && ( u->has_trait( trait_THRESH_MYCUS ) ||
                 u->has_trait( trait_MYCUS_FRIEND ) ) ) {
             return MATT_FRIEND;
         }
         if( effective_anger >= 10 &&
             type->in_species( species_MAMMAL ) && u->has_trait( trait_PHEROMONE_MAMMAL ) ) {
             effective_anger -= 20;
         }
         if( effective_anger >= 10 &&
             type->in_species( species_AMPHIBIAN ) && u->has_trait( trait_PHEROMONE_AMPHIBIAN ) ) {
             effective_anger -= 20;
         }
         if( ( faction == monfaction_acid_ant || faction == monfaction_ant || faction == monfaction_bee ||
               faction == monfaction_wasp ) && effective_anger >= 10 && u->has_trait( trait_PHEROMONE_INSECT ) ) {
             effective_anger -= 20;
         }
         if( u->has_trait( trait_TERRIFYING ) ) {
             effective_morale -= 10;
         }
         if( has_flag( mon_flag_ANIMAL ) ) {
             if( u->has_effect( effect_natures_commune ) ) {
                 effective_anger -= 10;
                 if( effective_anger < 10 ) {
                     effective_morale += 55;
                 }
             }
             if( u->has_trait( trait_ANIMALEMPATH ) ) {
                 effective_anger -= 10;
                 if( effective_anger < 10 ) {
                     effective_morale += 55;
                 }
             } else if( u->has_trait( trait_ANIMALEMPATH2 ) ) {
                 effective_anger -= 20;
                 if( effective_anger < 20 ) {
                     effective_morale += 80;
                 }
             } else if( u->has_trait( trait_ANIMALDISCORD ) ) {
                 if( effective_anger >= 10 ) {
                     effective_anger += 10;
                 }
                 if( effective_anger < 10 ) {
                     effective_morale -= 5;
                 }
             } else if( u->has_trait( trait_ANIMALDISCORD2 ) ) {
                 if( effective_anger >= 20 ) {
                     effective_anger += 20;
                 }
                 if( effective_anger < 20 ) {
                     effective_morale -= 5;
                 }
             }
         }
         for( const trait_id &mut : u->get_mutations() ) {
             const mutation_branch &branch = *mut;
             if( branch.ignored_by.empty() && branch.anger_relations.empty() ) {
                 continue;
             }
             for( const species_id &spe : branch.ignored_by ) {
                 if( type->in_species( spe ) ) {
                     return MATT_IGNORE;
                 }
             }
             for( const std::pair<const species_id, int> &elem : branch.anger_relations ) {
                 if( type->in_species( elem.first ) ) {
                     effective_anger += elem.second;
                 }
             }
         }
     }
     if( effective_morale < 0 ) {
         if( effective_morale + effective_anger > 0 && get_hp() > get_hp_max() / 3 ) {
             return MATT_FOLLOW;
         }
         return MATT_FLEE;
     }
     if( effective_anger <= 0 ) {
         if( get_hp() <= 0.6 * get_hp_max() ) {
             return MATT_FLEE;
         } else {
             return MATT_IGNORE;
         }
     }
     if( effective_anger < 10 ) {
         return MATT_FOLLOW;
     }
     if( has_flag( mon_flag_KEEP_DISTANCE ) &&
         rl_dist( get_location(), get_dest() ) < type->tracking_distance ) {
         return MATT_FLEE;
     }
     if( u != nullptr && !aggro_character && !u->is_monster() ) {
         return MATT_IGNORE;
     }
     return MATT_ATTACK;
 }
References aggro_character, anger, mutation_branch::anger_relations, effect_cache, effect_docile, effect_natures_commune, FLEEING, friendly, get_dest(), get_hp(), get_hp_max(), Creature::get_location(), Creature::has_effect(), has_flag(), mutation_branch::ignored_by, mtype::in_species(), MATT_ATTACK, MATT_FLEE, MATT_FOLLOW, MATT_FPASSIVE, MATT_FRIEND, MATT_IGNORE, faction_template::mon_faction, mon_flag_ANIMAL, mon_flag_KEEP_DISTANCE, monfaction_acid_ant, monfaction_ant, monfaction_bee, monfaction_nether_player_hate, monfaction_wasp, morale, NPCATT_KILL, rl_dist(), species_AMPHIBIAN, species_FUNGUS, species_MAMMAL, species_ZOMBIE, mtype::tracking_distance, trait_ANIMALDISCORD, trait_ANIMALDISCORD2, trait_ANIMALEMPATH, trait_ANIMALEMPATH2, trait_BEE, trait_FLOWERS, trait_MYCUS_FRIEND, trait_PHEROMONE_AMPHIBIAN, trait_PHEROMONE_INSECT, trait_PHEROMONE_MAMMAL, trait_TERRIFYING, trait_THRESH_MYCUS, type, and u.
Referenced by attack_at(), Character::attitude_to(), attitude_to(), npc::attitude_to(), get_attitude(), is_fleeing(), know_danger_at(), game::mon_info_update(), move(), plan(), process_effects(), and will_reach().
attitude_to()
Creature::Attitude monster::attitude_to (const Creature & other) const override virtual
Attitude (of this creature) towards another creature.
This might not be symmetric.
Implements Creature.
Definition at line 1450 of file monster.cpp.
 {
     const monster *m = other.is_monster() ? static_cast< const monster *>( &other ) : nullptr;
     const Character *p = other.as_character();
     if( m != nullptr ) {
         if( m == this ) {
             return Attitude::FRIENDLY;
         }
         mf_attitude faction_att = faction.obj().attitude( m->faction );
         if( ( friendly != 0 && m->friendly != 0 ) ||
             ( friendly == 0 && m->friendly == 0 && faction_att == MFA_FRIENDLY ) ) {
             // Friendly (to player) monsters are friendly to each other
             // Unfriendly monsters go by faction attitude
             return Attitude::FRIENDLY;
             // NOLINTNEXTLINE(bugprone-branch-clone)
         } else if( friendly == 0 && m->friendly == 0 && faction_att == MFA_HATE ) {
             // Stuff that hates a specific faction will always attack that faction
             return Attitude::HOSTILE;
         } else if( ( friendly == 0 && m->friendly == 0 && faction_att == MFA_NEUTRAL ) ||
                    morale < 0 || anger < 10 ) {
             // Stuff that won't attack is neutral to everything
             return Attitude::NEUTRAL;
         } else {
             return Attitude::HOSTILE;
         }
     } else if( p != nullptr ) {
         switch( attitude( p ) ) {
             case MATT_FRIEND:
                 return Attitude::FRIENDLY;
             case MATT_FPASSIVE:
             case MATT_FLEE:
             case MATT_IGNORE:
             case MATT_FOLLOW:
                 return Attitude::NEUTRAL;
             case MATT_ATTACK:
                 return Attitude::HOSTILE;
             case MATT_NULL:
             case NUM_MONSTER_ATTITUDES:
                 break;
         }
     }
     // Should not happen!, creature should be either player or monster
     return Attitude::NEUTRAL;
 }
References anger, attitude(), faction, Creature::FRIENDLY, friendly, Creature::HOSTILE, MATT_ATTACK, MATT_FLEE, MATT_FOLLOW, MATT_FPASSIVE, MATT_FRIEND, MATT_IGNORE, MATT_NULL, MFA_FRIENDLY, MFA_HATE, MFA_NEUTRAL, morale, Creature::NEUTRAL, NUM_MONSTER_ATTITUDES, and other.
Referenced by attack_at(), attack_target(), bash_at(), mattack::chickenbot(), game::examine(), mattack::grenadier(), mattack::grenadier_elite(), mattack::growplants(), game::mon_info_update(), move(), avatar_action::move(), mattack::multi_robot(), mattack::nurse_assist(), mattack::nurse_operate(), plan(), rate_target(), mattack::resurrect(), mattack::upgrade(), and mattack::vine().
avoid_trap()
bool monster::avoid_trap (const tripoint & pos, const trap & tr) const override virtual
Called when a creature triggers a trap, returns true if they don't set it off.
Parameters
tr is the trap that was triggered.
pos is the location of the trap (not necessarily of the creature) in the main map.
Implements Creature.
Definition at line 1186 of file monster.cpp.
 {
     // The trap position is not used, monsters are to stupid to remember traps. Actually, they do
     // not even see them.
     // Traps are on the ground, digging monsters go below, fliers and climbers go above.
     if( digging() || flies() ) {
         return true;
     }
     if( type->trap_avoids.count( tr.id ) > 0 ) {
         return true;
     }
     return dice( 3, type->sk_dodge + 1 ) >= dice( 3, tr.get_avoidance() );
 }
References dice(), digging(), flies(), trap::get_avoidance(), trap::id, mtype::sk_dodge, mtype::trap_avoids, and type.
bash_at()
bool monster::bash_at (const tripoint & p)
Try to smash/bash/destroy your way through the terrain at p.
Returns
true if we destroyed something, false otherwise.
Definition at line 1676 of file monmove.cpp.
 {
     if( p.z != posz() ) {
         // TODO: Remove this
         return false;
     }
     //Hallucinations can't bash stuff.
     if( is_hallucination() ) {
         return false;
     }
     // Don't bash if a friendly monster is standing there
     monster *target = get_creature_tracker().creature_at<monster>( p );
     if( target != nullptr && attitude_to( *target ) == Attitude::FRIENDLY ) {
         return false;
     }
     bool try_bash = !can_move_to( p ) || one_in( 3 );
     if( !try_bash ) {
         return false;
     }
     if( bash_skill() <= 0 ) {
         return false;
     }
     map &here = get_map();
     if( !( here.is_bashable_furn( p ) || here.veh_at( p ).obstacle_at_part() ) ) {
         // if the only thing here is road or flat, rarely bash it
         bool flat_ground = here.has_flag( ter_furn_flag::TFLAG_ROAD, p ) ||
                            here.has_flag( ter_furn_flag::TFLAG_FLAT, p );
         if( !here.is_bashable_ter( p ) || ( flat_ground && !one_in( 50 ) ) ) {
             return false;
         }
     }
     int bashskill = group_bash_skill( p );
     here.bash( p, bashskill );
     mod_moves( -get_speed() );
     return true;
 }
References attitude_to(), map::bash(), bash_skill(), can_move_to(), creature_tracker::creature_at(), Creature::FRIENDLY, get_creature_tracker(), get_map(), Creature::get_speed(), group_bash_skill(), map::has_flag(), map::is_bashable_furn(), map::is_bashable_ter(), is_hallucination(), Creature::mod_moves(), optional_vpart_position::obstacle_at_part(), one_in(), Creature::posz(), TFLAG_FLAT, TFLAG_ROAD, map::veh_at(), and tripoint::z.
Referenced by move().
bash_estimate()
int monster::bash_estimate () const
Definition at line 1719 of file monmove.cpp.
 {
     int estimate = bash_skill();
     if( has_flag( mon_flag_GROUP_BASH ) ) {
         // Right now just give them a boost so they try to bash a lot of stuff.
         // TODO: base it on number of nearby friendlies.
         estimate *= 2;
     }
     return estimate;
 }
References bash_skill(), has_flag(), and mon_flag_GROUP_BASH.
Referenced by move(), and scent_move().
bash_skill()
int monster::bash_skill () const
Returns innate monster bash skill, without calculating additional from helpers.
Definition at line 1730 of file monmove.cpp.
 {
     return type->bash_skill;
 }
References mtype::bash_skill, and type.
Referenced by bash_at(), bash_estimate(), get_path_avoid(), group_bash_skill(), move(), and scent_move().
basic_symbol_color()
nc_color monster::basic_symbol_color () const override virtual
Creature symbol color.
Implements Creature.
Definition at line 1153 of file monster.cpp.
 {
     return type->color;
 }
References mtype::color, and type.
Referenced by print_info().
block_hit()
bool monster::block_hit (Creature * source, bodypart_id & bp_hit, damage_instance & d) override virtual
Implements Creature.
Definition at line 1870 of file monster.cpp.
 {
     return false;
 }
bloodType()
field_type_id monster::bloodType () const override virtual
Implements Creature.
Definition at line 3488 of file monster.cpp.
 {
     if( is_hallucination() ) {
         return fd_null;
     }
     return type->bloodType();
 }
References mtype::bloodType(), fd_null, is_hallucination(), and type.
Referenced by mattack::dogthing(), scatter_chunks(), and mdeath::splatter().
calc_climb_cost()
int monster::calc_climb_cost (const tripoint & f, const tripoint & t) const
Definition at line 1629 of file monmove.cpp.
 {
     if( flies() ) {
         return 100;
     }
     map &here = get_map();
     if( climbs() && !here.has_flag( ter_furn_flag::TFLAG_NO_FLOOR, t ) ) {
         const int diff = here.climb_difficulty( f );
         if( diff <= 10 ) {
             return 150;
         }
     }
     return 0;
 }
References map::climb_difficulty(), climbs(), flies(), get_map(), map::has_flag(), and TFLAG_NO_FLOOR.
Referenced by move_to().
calc_movecost()
int monster::calc_movecost (const tripoint & f, const tripoint & t) const
Definition at line 1575 of file monmove.cpp.
 {
     int movecost = 0;
     map &here = get_map();
     const int source_cost = here.move_cost( f );
     const int dest_cost = here.move_cost( t );
     // Digging and flying monsters ignore terrain cost
     if( flies() || ( digging() && here.has_flag( ter_furn_flag::TFLAG_DIGGABLE, t ) ) ) {
         movecost = 100;
         // Swimming monsters move super fast in water
     } else if( swims() ) {
         if( here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, f ) ) {
             movecost += 25;
         } else {
             movecost += 50 * here.move_cost( f );
         }
         if( here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, t ) ) {
             movecost += 25;
         } else {
             movecost += 50 * here.move_cost( t );
         }
     } else if( can_submerge() ) {
         // No-breathe monsters have to walk underwater slowly
         if( here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, f ) ) {
             movecost += 250;
         } else {
             movecost += 50 * here.move_cost( f );
         }
         if( here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, t ) ) {
             movecost += 250;
         } else {
             movecost += 50 * here.move_cost( t );
         }
         movecost /= 2;
     } else if( climbs() ) {
         if( here.has_flag( ter_furn_flag::TFLAG_CLIMBABLE, f ) ) {
             movecost += 150;
         } else {
             movecost += 50 * here.move_cost( f );
         }
         if( here.has_flag( ter_furn_flag::TFLAG_CLIMBABLE, t ) ) {
             movecost += 150;
         } else {
             movecost += 50 * here.move_cost( t );
         }
         movecost /= 2;
     } else {
         movecost = ( ( 50 * source_cost ) + ( 50 * dest_cost ) ) / 2.0;
     }
     return movecost;
 }
References can_submerge(), climbs(), digging(), flies(), get_map(), map::has_flag(), map::move_cost(), swims(), TFLAG_CLIMBABLE, TFLAG_DIGGABLE, and TFLAG_SWIMMABLE.
Referenced by move_to(), and turns_to_reach().
calculate_by_enchantment()
double monster::calculate_by_enchantment (double modify, enchant_vals::mod value, bool round_output = false) const
Definition at line 4016 of file monster.cpp.
 {
     modify += enchantment_cache->get_value_add( value );
     modify *= 1.0 + enchantment_cache->get_value_multiply( value );
     if( round_output ) {
         modify = std::round( modify );
     }
     return modify;
 }
References enchantment_cache, and round().
Referenced by armor_enchantment_adjust(), process_effects(), and process_one_effect().
can_act()
bool monster::can_act () const
Definition at line 1277 of file monster.cpp.
 {
     return moves > 0 &&
            ( effects->empty() ||
              ( !has_effect( effect_stunned ) && !has_effect( effect_psi_stunned ) &&
                !has_effect( effect_downed ) && !has_effect( effect_webbed ) ) );
 }
References effect_downed, effect_psi_stunned, effect_stunned, effect_webbed, Creature::effects, Creature::has_effect(), and Creature::moves.
Referenced by mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_random_biojutsu(), mattack::bio_op_takedown(), mattack::boomer(), mattack::boomer_glow(), leap_actor::call(), mon_spellcasting_actor::call(), mattack::dermatik(), mattack::evolve_kill_strike(), melee_actor::find_target(), mattack::flesh_golem(), grenade_helper(), mattack::lunge(), mattack::science(), mattack::shockstorm(), mattack::shriek_alert(), mattack::shriek_stun(), mattack::smash(), mattack::spit_sap(), and mattack::stretch_attack().
can_attack_high()
bool monster::can_attack_high () const override virtual
Implements Creature.
Definition at line 2494 of file monster.cpp.
 {
     return  !( ( type->size < creature_size::medium && !has_flag( mon_flag_FLIES ) &&
                  !has_flag( mon_flag_ATTACK_UPPER ) ) || has_flag( mon_flag_ATTACK_LOWER ) )  ;
 }
References has_flag(), medium, mon_flag_ATTACK_LOWER, mon_flag_ATTACK_UPPER, mon_flag_FLIES, mtype::size, and type.
can_climb()
bool monster::can_climb () const
Definition at line 1242 of file monster.cpp.
 {
     return climbs() || flies();
 }
References climbs(), and flies().
Referenced by know_danger_at(), move(), and will_move_to().
can_dig()
bool monster::can_dig () const
Definition at line 1252 of file monster.cpp.
 {
     return has_flag( mon_flag_CAN_DIG );
 }
References has_flag(), and mon_flag_CAN_DIG.
Referenced by digging(), extended_description(), and move_to().
can_drown()
bool monster::can_drown () const
Definition at line 1236 of file monster.cpp.
 {
     return !swims() && !has_flag( mon_flag_AQUATIC ) &&
            !has_flag( mon_flag_NO_BREATHE ) && !flies();
 }
References flies(), has_flag(), mon_flag_AQUATIC, mon_flag_NO_BREATHE, and swims().
Referenced by is_aquatic_danger().
can_hear()
bool monster::can_hear () const
Definition at line 1225 of file monster.cpp.
 {
     return has_flag( mon_flag_HEARS ) && !has_effect( effect_deaf );
 }
References effect_deaf, Creature::has_effect(), has_flag(), and mon_flag_HEARS.
Referenced by hear_sound(), and will_reach().
can_move_to()
bool monster::can_move_to (const tripoint & p) const
Checks whether we can move to/through p.
This does not account for bashing.
This is used in pathfinding and ONLY checks the terrain. It ignores players and monsters, which might only block this tile temporarily. will_move_to() checks for impassable terrain etc can_reach_to() checks for z-level difference. can_move_to() is a wrapper for both of them. know_danger_at() checks for fire, trap etc. (flag PATH_AVOID_)
Definition at line 356 of file monmove.cpp.
 {
     return can_reach_to( p ) && will_move_to( p );
 }
References can_reach_to(), and will_move_to().
Referenced by bash_at(), melee_actor::do_grab(), get_path_avoid(), move(), move_to(), push_to(), scent_move(), map::spawn_monsters_submap(), map::spawn_monsters_submap_group(), and stumble().
can_pathfind()
bool monster::can_pathfind () const inline private
Definition at line 638 of file monster.h.
{
             return pathfinding_cd <= calendar::turn;
         }
References pathfinding_cd, and calendar::turn.
Referenced by move().
can_reach_to()
bool monster::can_reach_to (const tripoint & p) const
Definition at line 330 of file monmove.cpp.
 {
     map &here = get_map();
     if( p.z > pos().z && z_is_valid( pos().z ) ) {
         if( here.has_flag( ter_furn_flag::TFLAG_RAMP_UP, tripoint( p.xy(), p.z - 1 ) ) ) {
             return true;
         }
         if( !here.has_flag( ter_furn_flag::TFLAG_GOES_UP, pos() ) && here.has_floor( p ) ) {
             // can't go through the roof
             return false;
         }
     } else if( p.z < pos().z && z_is_valid( pos().z ) ) {
         const tripoint above( p.xy(), p.z + 1 );
         if( here.has_flag( ter_furn_flag::TFLAG_RAMP_DOWN, above ) ) {
             return true;
         }
         if( !here.has_flag( ter_furn_flag::TFLAG_GOES_DOWN, pos() ) &&
             ( here.has_floor( above ) || ( !flies() && !here.has_floor_or_water( above ) ) ) ) {
             // can't go through the floor
             // Check floors for flying monsters movement
             return false;
         }
     }
     return true;
 }
References above, flies(), get_map(), map::has_flag(), map::has_floor(), map::has_floor_or_water(), Creature::pos(), TFLAG_GOES_DOWN, TFLAG_GOES_UP, TFLAG_RAMP_DOWN, TFLAG_RAMP_UP, tripoint::xy(), tripoint::z, and z_is_valid().
Referenced by can_move_to().
can_see()
bool monster::can_see () const
Definition at line 1220 of file monster.cpp.
 {
     return has_flag( mon_flag_SEES ) && !effect_cache[VISION_IMPAIRED];
 }
References effect_cache, has_flag(), mon_flag_SEES, and VISION_IMPAIRED.
Referenced by move(), sight_range(), and will_reach().
can_submerge()
bool monster::can_submerge () const
Definition at line 1230 of file monster.cpp.
 {
     return ( has_flag( mon_flag_NO_BREATHE ) || swims() || has_flag( mon_flag_AQUATIC ) ) &&
            !has_flag( mon_flag_ELECTRONIC );
 }
References has_flag(), mon_flag_AQUATIC, mon_flag_ELECTRONIC, mon_flag_NO_BREATHE, and swims().
Referenced by calc_movecost(), MonsterGenerator::check_monster_definitions(), is_underwater(), move_to(), and will_move_to().
can_upgrade()
bool monster::can_upgrade () const
Definition at line 399 of file monster.cpp.
 {
     return upgrades && get_option<float>( "MONSTER_UPGRADE_FACTOR" ) > 0.0;
 }
References upgrades.
Referenced by extended_description(), hasten_upgrade(), and try_upgrade().
check_mech_powered()
bool monster::check_mech_powered () const
Definition at line 2975 of file monster.cpp.
 {
     if( is_hallucination() || !has_flag( mon_flag_RIDEABLE_MECH ) || !battery_item ) {
         return false;
     }
     if( battery_item->ammo_remaining() <= 0 ) {
         return false;
     }
     const itype &type = *battery_item->type;
     if( battery_item->ammo_remaining() <= type.magazine->capacity / 10 && one_in( 10 ) ) {
         add_msg( m_bad, _( "Your %s emits a beeping noise as its batteries start to get low." ),
                  get_name() );
     }
     return true;
 }
References _, add_msg(), battery_item, get_name(), has_flag(), is_hallucination(), m_bad, mon_flag_RIDEABLE_MECH, one_in(), and type.
Referenced by avatar_action::plthrow(), game::vertical_move(), and game::walk_move().
climbs()
bool monster::climbs () const
Definition at line 1267 of file monster.cpp.
 {
     return has_flag( mon_flag_CLIMBS );
 }
References has_flag(), and mon_flag_CLIMBS.
Referenced by calc_climb_cost(), calc_movecost(), can_climb(), extended_description(), and move_to().
color_with_effects()
nc_color monster::color_with_effects () const
Definition at line 1168 of file monster.cpp.
 {
     nc_color ret = type->color;
     if( has_effect( effect_beartrap ) || has_effect( effect_stunned ) ||
         has_effect( effect_psi_stunned ) || has_effect( effect_downed ) ||
         has_effect( effect_tied ) ||
         has_effect( effect_lightsnare ) || has_effect( effect_heavysnare ) ) {
         ret = hilite( ret );
     }
     if( has_effect( effect_pacified ) ) {
         ret = invert_color( ret );
     }
     if( has_effect( effect_onfire ) ) {
         ret = red_background( ret );
     }
     return ret;
 }
References mtype::color, effect_beartrap, effect_downed, effect_heavysnare, effect_lightsnare, effect_onfire, effect_pacified, effect_psi_stunned, effect_stunned, effect_tied, Creature::has_effect(), hilite(), invert_color(), red_background(), cata::hash64_detail::ret, and type.
Referenced by symbol_color().
deal_damage_handle_type()
void monster::deal_damage_handle_type (const effect_source & source, const damage_unit & du, bodypart_id bp, int & damage, int & pain) override virtual
Reimplemented from Creature.
Definition at line 2127 of file monster.cpp.
 {
     const int adjusted_damage = du.amount * du.damage_multiplier * du.unconditional_damage_mult;
     if( is_immune_damage( du.type ) ) {
         return; // immunity
     }
     // FIXME: Hardcoded damage type effects (bash, bullet)
     if( du.type == damage_bash ) {
         if( has_flag( mon_flag_PLASTIC ) ) {
             damage += du.amount / rng( 2, 4 ); // lessened effect
             pain += du.amount / 4;
             return;
         }
     }
     if( du.type == damage_bullet || du.type->edged ) {
         make_bleed( source, 1_minutes * rng( 0, adjusted_damage ) );
     }
     Creature::deal_damage_handle_type( source, du,  bp, damage, pain );
 }
References damage_unit::amount, bp, damage_bash, damage_bullet, damage_unit::damage_multiplier, Creature::deal_damage_handle_type(), damage_type::edged, has_flag(), is_immune_damage(), make_bleed(), mon_flag_PLASTIC, Creature::pain, rng(), damage_unit::type, and damage_unit::unconditional_damage_mult.
deal_projectile_attack()
void monster::deal_projectile_attack (Creature * source, dealt_projectile_attack & attack, bool print_messages = true, const weakpoint_attack & wp_attack = weakpoint_attack()) override virtual
Attempts to harm a creature with a projectile.
Parameters
source Pointer to the creature who shot the projectile.
attack A structure describing the attack and its results.
print_messages enables message printing by default.
Reimplemented from Creature.
Definition at line 2097 of file monster.cpp.
 {
     const projectile &proj = attack.proj;
     double &missed_by = attack.missed_by; // We can change this here
     const auto &effects = proj.proj_effects;
     // Whip has a chance to scare wildlife even if it misses
     if( effects.count( "WHIP" ) && type->in_category( "WILDLIFE" ) && one_in( 3 ) ) {
         add_effect( effect_run, rng( 3_turns, 5_turns ) );
     }
     if( missed_by > 1.0 ) {
         // Total miss
         return;
     }
     // if it's a headshot with no head, make it not a headshot
     if( missed_by < accuracy_headshot && has_flag( mon_flag_NOHEAD ) ) {
         missed_by = accuracy_headshot;
     }
     Creature::deal_projectile_attack( source, attack, print_messages, wp_attack );
     if( !is_hallucination() && attack.hit_critter == this ) {
         // Maybe TODO: Get difficulty from projectile speed/size/missed_by
         on_hit( source, bodypart_id( "torso" ), INT_MIN, &attack );
     }
 }
References accuracy_headshot, Creature::add_effect(), spell_effect::attack(), Creature::deal_projectile_attack(), effect_run, Creature::effects, has_flag(), mtype::in_category(), is_hallucination(), mon_flag_NOHEAD, on_hit(), one_in(), projectile::proj_effects, rng(), and type.
deserialize() [1/2]
void monster::deserialize (const JsonObject & data)
Definition at line 2394 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     load( data );
 }
References item_pocket::data, and ammo_effects::load().
Referenced by mongroup::deserialize_legacy(), and overmap::unserialize().
deserialize() [2/2]
void monster::deserialize (const JsonObject & data, const tripoint_abs_sm & submap_loc)
Definition at line 2388 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     load( data, submap_loc );
 }
References item_pocket::data, and ammo_effects::load().
die()
void monster::die (Creature * killer) override virtual
Empty function.
Should always be overwritten by the appropriate player/NPC/monster version.
Implements Creature.
Definition at line 2742 of file monster.cpp.
 {
     if( dead ) {
         // We are already dead, don't die again, note that monster::dead is
         // *only* set to true in this function!
         return;
     }
     // We were carrying a creature, deposit the rider
     if( has_effect( effect_ridden ) && mounted_player ) {
         mounted_player->forced_dismount();
     }
     g->set_critter_died();
     dead = true;
     set_killer( nkiller );
     if( get_killer() != nullptr ) {
         Character *ch = get_killer()->as_character();
         if( ch == nullptr && get_killer()->get_summoner() != nullptr ) {
             ch = get_killer()->get_summoner()->as_character();
         }
         if( !is_hallucination() && ch != nullptr ) {
             cata::event e = cata::event::make<event_type::character_kills_monster>( ch->getID(), type->id,
                             compute_kill_xp( type->id ) );
             get_event_bus().send_with_talker( ch, this, e );
             if( ch->is_avatar() && ch->has_trait( trait_KILLER ) ) {
                 if( one_in( 4 ) ) {
                     const translation snip = SNIPPET.random_from_category( "killer_on_kill" ).value_or( translation() );
                     ch->add_msg_if_player( m_good, "%s", snip );
                 }
                 ch->add_morale( MORALE_KILLER_HAS_KILLED, 5, 10, 6_hours, 4_hours );
                 ch->rem_morale( MORALE_KILLER_NEED_TO_KILL );
             }
         }
     }
     map &here = get_map();
     creature_tracker &creatures = get_creature_tracker();
     if( has_effect_with_flag( json_flag_GRAB_FILTER ) ) {
         // Need to filter out which limb we were grabbing before death
         for( const tripoint &player_pos : here.points_in_radius( pos(), 1, 0 ) ) {
             Creature *you = creatures.creature_at( player_pos );
             if( !you || !you->has_effect_with_flag( json_flag_GRAB ) ) {
                 continue;
             }
             // ...but if there are no grabbers around we can just skip to the end
             bool grabbed = false;
             for( const tripoint &mon_pos : here.points_in_radius( player_pos, 1, 0 ) ) {
                 const monster *const mon = creatures.creature_at<monster>( mon_pos );
                 // No persisting our grabs from beyond the grave, but we also don't get to remove the effect early
                 if( mon && mon->has_effect_with_flag( json_flag_GRAB_FILTER ) && mon != this ) {
                     grabbed = true;
                     break;
                 }
             }
             if( !grabbed ) {
                 you->add_msg_player_or_npc( m_good, _( "The last enemy holding you collapses!" ),
                                             _( "The last enemy holding <npcname> collapses!" ) );
                 // A loop for safety
                 for( const effect &grab : you->get_effects_with_flag( json_flag_GRAB ) ) {
                     you->remove_effect( grab.get_id() );
                 }
                 continue;
             }
             // Iterate through all your grabs to figure out which one this critter held
             for( const effect &grab : you->get_effects_with_flag( json_flag_GRAB ) ) {
                 if( is_grabbing( grab.get_bp().id() ) ) {
                     const effect_type effid = *grab.get_effect_type();
                     you->remove_effect( effid.id, grab.get_bp() );
                 }
             }
         }
     }
     // If we're a queen, make nearby groups of our type start to die out
     if( !is_hallucination() && has_flag( mon_flag_QUEEN ) ) {
         // The submap coordinates of this monster, monster groups coordinates are
         // submap coordinates.
         const tripoint abssub = ms_to_sm_copy( here.getabs( pos() ) );
         // Do it for overmap above/below too
         for( const tripoint &p : points_in_radius( abssub, HALF_MAPSIZE, 1 ) ) {
             // TODO: fix point types
             for( mongroup *&mgp : overmap_buffer.groups_at( tripoint_abs_sm( p ) ) ) {
                 if( MonsterGroupManager::IsMonsterInGroup( mgp->type, type->id ) ) {
                     mgp->dying = true;
                 }
             }
         }
     }
     mission::on_creature_death( *this );
     // Hallucinations always just disappear
     if( is_hallucination() ) {
         mdeath::disappear( *this );
         return;
     }
     add_msg_if_player_sees( *this, m_good, type->mdeath_effect.death_message.translated(), name() );
     if( type->mdeath_effect.has_effect ) {
         //Not a hallucination, go process the death effects.
         spell death_spell = type->mdeath_effect.sp.get_spell( *this );
         if( killer != nullptr && !type->mdeath_effect.sp.self &&
             death_spell.is_target_in_range( *this, killer->pos() ) ) {
             death_spell.cast_all_effects( *this, killer->pos() );
         } else if( type->mdeath_effect.sp.self ) {
             death_spell.cast_all_effects( *this, pos() );
         }
     }
     if( type->mdeath_effect.eoc.has_value() ) {
         //Not a hallucination, go process the death effects.
         if( type->mdeath_effect.eoc.value().is_valid() ) {
             dialogue d( get_talker_for( *this ), nullptr );
             type->mdeath_effect.eoc.value()->activate( d );
         } else {
             debugmsg( "eoc id %s is not valid", type->mdeath_effect.eoc.value().str() );
         }
     }
     // scale overkill damage by enchantments
     if( nkiller && ( nkiller->is_npc() || nkiller->is_avatar() ) ) {
         int current_hp = get_hp();
         current_hp = nkiller->as_character()->enchantment_cache->modify_value(
                          enchant_vals::mod::OVERKILL_DAMAGE, current_hp );
         set_hp( current_hp );
     }
     item_location corpse;
     // drop a corpse, or not - this needs to happen after the spell, for e.g. revivification effects
     switch( type->mdeath_effect.corpse_type ) {
         case mdeath_type::NORMAL:
             corpse =  mdeath::normal( *this );
             break;
         case mdeath_type::BROKEN:
             mdeath::broken( *this );
             break;
         case mdeath_type::SPLATTER:
             corpse = mdeath::splatter( *this );
             break;
         default:
             break;
     }
     if( death_drops ) {
         // Drop items stored in optionals
         move_special_item_to_inv( tack_item );
         move_special_item_to_inv( armor_item );
         move_special_item_to_inv( storage_item );
         move_special_item_to_inv( tied_item );
         if( has_effect( effect_heavysnare ) ) {
             add_item( item( "rope_6", calendar::turn_zero ) );
             add_item( item( "snare_trigger", calendar::turn_zero ) );
         }
     }
     if( death_drops && !no_extra_death_drops ) {
         drop_items_on_death( corpse.get_item() );
         spawn_dissectables_on_death( corpse.get_item() );
     }
     if( death_drops && !is_hallucination() ) {
         for( const item &it : inv ) {
             if( it.has_var( "DESTROY_ITEM_ON_MON_DEATH" ) ) {
                 continue;
             }
             if( corpse ) {
                 corpse->force_insert_item( it, pocket_type::CONTAINER );
             } else {
                 get_map().add_item_or_charges( pos(), it );
             }
         }
         for( const item &it : dissectable_inv ) {
             if( corpse ) {
                 corpse->put_in( it, pocket_type::CORPSE );
             } else {
                 get_map().add_item( pos(), it );
             }
         }
     }
     if( corpse ) {
         corpse->process( get_map(), nullptr, corpse.position() );
         corpse.make_active();
     }
     // Adjust anger/morale of nearby monsters, if they have the appropriate trigger and are friendly
     // Keep filtering on the dying monsters' triggers to preserve current functionality
     bool trigger = type->has_anger_trigger( mon_trigger::FRIEND_DIED ) ||
                    type->has_fear_trigger( mon_trigger::FRIEND_DIED ) ||
                    type->has_placate_trigger( mon_trigger::FRIEND_DIED );
     if( trigger ) {
         int light = g->light_level( posz() );
         map &here = get_map();
         for( monster &critter : g->all_monsters() ) {
             // Do we actually care about this faction?
             if( critter.faction->attitude( faction ) != MFA_FRIENDLY ) {
                 continue;
             }
             if( here.sees( critter.pos(), pos(), light ) ) {
                 // Anger trumps fear trumps ennui
                 if( critter.type->has_anger_trigger( mon_trigger::FRIEND_DIED ) ) {
                     critter.anger += 15;
                     if( nkiller != nullptr && !nkiller->is_monster() && !nkiller->is_fake() ) {
                         // A character killed our friend
                         add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro triggered by killing a friendly %s",
                                        critter.name(), name() );
                         critter.aggro_character = true;
                     }
                 } else if( critter.type->has_fear_trigger( mon_trigger::FRIEND_DIED ) ) {
                     critter.morale -= 15;
                 } else if( critter.type->has_placate_trigger( mon_trigger::FRIEND_DIED ) ) {
                     critter.anger -= 15;
                 }
             }
         }
     }
 }
References _, add_item(), map::add_item(), map::add_item_or_charges(), Character::add_morale(), add_msg_debug, Character::add_msg_if_player(), add_msg_if_player_sees(), Creature::add_msg_player_or_npc(), armor_item, Creature::as_character(), mdeath::broken(), BROKEN, spell::cast_all_effects(), compute_kill_xp(), CONTAINER, corpse, CORPSE, monster_death_effect::corpse_type, creature_tracker::creature_at(), dead, death_drops, monster_death_effect::death_message, debugmsg, debugmode::DF_MONSTER, mdeath::disappear(), dissectable_inv, drop_items_on_death(), effect_heavysnare, effect_ridden, Character::enchantment_cache, monster_death_effect::eoc, Character::forced_dismount(), FRIEND_DIED, g, get_creature_tracker(), Creature::get_effects_with_flag(), get_event_bus(), get_hp(), Creature::get_killer(), get_map(), fake_spell::get_spell(), Creature::get_summoner(), get_talker_for(), map::getabs(), Character::getID(), overmapbuffer::groups_at(), HALF_MAPSIZE, mtype::has_anger_trigger(), Creature::has_effect(), monster_death_effect::has_effect, Creature::has_effect_with_flag(), mtype::has_fear_trigger(), has_flag(), mtype::has_placate_trigger(), Character::has_trait(), effect_type::id, mtype::id, inv, Creature::is_avatar(), Creature::is_fake(), is_grabbing(), is_hallucination(), Creature::is_monster(), Creature::is_npc(), spell::is_target_in_range(), MonsterGroupManager::IsMonsterInGroup(), item, json_flag_GRAB, json_flag_GRAB_FILTER, Creature::killer, light, m_good, mtype::mdeath_effect, MFA_FRIENDLY, mon_flag_QUEEN, MORALE_KILLER_HAS_KILLED, MORALE_KILLER_NEED_TO_KILL, mounted_player, move_special_item_to_inv(), ms_to_sm_copy(), name(), no_extra_death_drops, mdeath::normal(), NORMAL, mission::on_creature_death(), one_in(), enchant_vals::OVERKILL_DAMAGE, overmap_buffer, points_in_radius(), map::points_in_radius(), Creature::pos(), Creature::posz(), snippet_library::random_from_category(), Character::rem_morale(), Creature::remove_effect(), map::sees(), fake_spell::self, event_bus::send_with_talker(), set_hp(), Creature::set_killer(), SNIPPET, monster_death_effect::sp, spawn_dissectables_on_death(), mdeath::splatter(), SPLATTER, storage_item, tack_item, tied_item, trait_KILLER, translation::translated(), calendar::turn_zero, and type.
Referenced by computer_session::action_terminate(), creature_tracker::add(), game::catch_a_monster(), mattack::depart(), talker_monster::die(), die_if_drowning(), die_in_explosion(), iuse::fungicide(), mattack::kamikaze(), creature_tracker::kill_marked_for_death(), knock_back_to(), melee_attack(), move(), avatar_action::move(), mattack::photograph(), push_to(), mattack::suicide(), try_upgrade(), and mattack::zombie_fuse().
die_if_drowning()
bool monster::die_if_drowning (const tripoint & at_pos, int chance = 1)
Definition at line 849 of file monmove.cpp.
 {
     if( is_aquatic_danger( at_pos ) && one_in( chance ) ) {
         add_msg_if_player_sees( at_pos, _( "The %s drowns!" ), name() );
         die( nullptr );
         return true;
     }
     return false;
 }
References _, add_msg_if_player_sees(), die(), is_aquatic_danger(), name(), and one_in().
Referenced by knock_back_to(), and move().
die_in_explosion()
void monster::die_in_explosion (Creature * source)
Definition at line 2189 of file monster.cpp.
 {
     hp = -9999; // huge to trigger explosion and prevent corpse item
     die( source );
 }
References die(), and hp.
Referenced by game::forced_door_closing(), and iuse::granade_act().
digest_food()
void monster::digest_food ()
Definition at line 659 of file monster.cpp.
 {
     if( calendar::turn - stomach_timer > 1_days ) {
         if( ( amount_eaten >= stomach_size ) && !has_effect( effect_critter_underfed ) ) {
             add_effect( effect_critter_well_fed, 24_hours );
         } else if( ( amount_eaten < ( stomach_size / 10 ) ) && !has_effect( effect_critter_well_fed ) ) {
             add_effect( effect_critter_underfed, 24_hours );
         }
         amount_eaten = 0;
         stomach_timer = calendar::turn;
     }
 }
References Creature::add_effect(), amount_eaten, effect_critter_underfed, effect_critter_well_fed, Creature::has_effect(), stomach_size, stomach_timer, and calendar::turn.
Referenced by on_load(), and process_effects().
digging()
bool monster::digging () const override virtual
Reimplemented from Creature.
Definition at line 1247 of file monster.cpp.
 {
     return digs() || ( can_dig() && underwater );
 }
References can_dig(), digs(), and Creature::underwater.
Referenced by avoid_trap(), calc_movecost(), footsteps(), map::monster_in_field(), move_to(), projectile_attack(), sight_range(), and will_move_to().
digs()
bool monster::digs () const
Definition at line 1257 of file monster.cpp.
 {
     return has_flag( mon_flag_DIGS );
 }
References has_flag(), and mon_flag_DIGS.
Referenced by digging(), map::monster_in_field(), move_to(), will_move_to(), and will_reach().
disable_special()
void monster::disable_special (const std::string & special_name)
Sets the enabled flag for the given special to false.
Definition at line 2601 of file monster.cpp.
 {
     special_attacks.at( special_name ).enabled = false;
 }
References special_attacks.
Referenced by mattack::grenadier(), mattack::grenadier_elite(), and mattack::kamikaze().
disp_name()
std::string monster::disp_name (bool possessive = false, bool capitalize_first = false) const override virtual
Implements Creature.
Definition at line 775 of file monster.cpp.
 {
     if( !possessive ) {
         return string_format( capitalize_first ? _( "The %s" ) : _( "the %s" ), name() );
     } else {
         return string_format( capitalize_first ? _( "The %s's" ) : _( "the %s's" ), name() );
     }
 }
References _, name(), and string_format().
Referenced by mdefense::acidsplash(), blobify(), mon_spellcasting_actor::call(), melee_actor::call(), game::chat(), talker_monster_const::disp_name(), melee_actor::do_grab(), drop_or_embed_projectile(), shearing_activity_actor::finish(), melee_attack(), melee_actor::on_damage(), push_to(), map::shake_vehicle(), shove_vehicle(), map::spawn_monsters_submap_group(), shearing_activity_actor::start(), Character::try_remove_grab(), Character::uninstall_bionic(), and creature_tracker::update_pos().
dodge_roll()
float monster::dodge_roll () const override virtual
Implements Creature.
Definition at line 2489 of file monster.cpp.
 {
     return get_dodge() * 5;
 }
References get_dodge().
Referenced by mattack::dermatik().
drop_items_on_death()
void monster::drop_items_on_death (item * corpse)
Definition at line 3016 of file monster.cpp.
 {
     if( is_hallucination() ) {
         return;
     }
     if( type->death_drops.is_empty() ) {
         return;
     }
     std::vector<item> new_items = item_group::items_from( type->death_drops,
                                   calendar::start_of_cataclysm,
                                   spawn_flags::use_spawn_rate );
     for( item &e : new_items ) {
         e.randomize_rot();
     }
     // for non corpses this is much simpler
     if( !corpse ) {
         for( item &it : new_items ) {
             get_map().add_item_or_charges( pos(), it );
         }
         return;
     }
     // first put "on" things that are wearable
     for( item &it : new_items ) {
         if( has_flag( mon_flag_FILTHY ) ) {
             if( ( it.is_armor() || it.is_pet_armor() ) && !it.is_gun() ) {
                 // handle wearable guns as a special case
                 it.set_flag( STATIC( flag_id( "FILTHY" ) ) );
             }
         }
         // add stuff that could be worn or strapped to the creature
         if( it.is_armor() ) {
             corpse->force_insert_item( it, pocket_type::CONTAINER );
         }
     }
     // then nest the rest in those "worn" items if possible
     // TODO: disable the backup, only spawn items here that actually fit in something
     for( item &it : new_items ) {
         // add stuff that could be worn or strapped to the creature
         if( !it.is_armor() ) {
             std::pair<item_location, item_pocket *> current_best;
             for( item *worn_it : corpse->all_items_top() ) {
                 item_location loc;
                 std::pair<item_location, item_pocket *> internal_pocket =
                     worn_it->best_pocket( it, loc, nullptr, false, true );
                 if( internal_pocket.second != nullptr &&
                     ( current_best.second == nullptr ||
                       current_best.second->better_pocket( *internal_pocket.second, it ) ) ) {
                     current_best = internal_pocket;
                 }
             }
             if( current_best.second != nullptr ) {
                 current_best.second->insert_item( it );
             } else {
                 corpse->force_insert_item( it, pocket_type::CONTAINER );
             }
         }
     }
 }
References map::add_item_or_charges(), item::best_pocket(), CONTAINER, corpse, mtype::death_drops, flag_id, get_map(), has_flag(), string_id< T >::is_empty(), is_hallucination(), item_group::items_from(), mon_flag_FILTHY, Creature::pos(), item::set_flag(), calendar::start_of_cataclysm, STATIC, type, and use_spawn_rate.
Referenced by die().
explode()
void monster::explode ()
Definition at line 2620 of file monster.cpp.
 {
     // Handled in mondeath::normal
     // +1 to avoid overflow when evaluating -hp
     hp = INT_MIN + 1;
 }
References hp.
extended_description()
std::string monster::extended_description () const override virtual
Implements Creature.
Definition at line 958 of file monster.cpp.
 {
     std::string ss;
     Character &pc = get_player_character();
     const bool player_knows = !pc.has_trait( trait_INATTENTIVE );
     const std::pair<std::string, nc_color> att = get_attitude();
     std::string att_colored = colorize( att.first, att.second );
     std::string difficulty_str;
     if( debug_mode ) {
         difficulty_str = _( "Difficulty " ) + std::to_string( type->difficulty );
     } else {
         if( type->difficulty < 3 ) {
             difficulty_str = _( "<color_light_gray>Minimal threat.</color>" );
         } else if( type->difficulty < 10 ) {
             difficulty_str = _( "<color_light_gray>Mildly dangerous.</color>" );
         } else if( type->difficulty < 20 ) {
             difficulty_str = _( "<color_light_red>Dangerous.</color>" );
         } else if( type->difficulty < 30 ) {
             difficulty_str = _( "<color_red>Very dangerous.</color>" );
         } else if( type->difficulty < 50 ) {
             difficulty_str = _( "<color_red>Extremely dangerous.</color>" );
         } else {
             difficulty_str = _( "<color_red>Fatally dangerous!</color>" );
         }
     }
     ss += _( "Origin: " );
     ss += enumerate_as_string( type->src.begin(),
     type->src.end(), []( const std::pair<mtype_id, mod_id> &source ) {
         return string_format( "'%s'", source.second->name() );
     }, enumeration_conjunction::arrow );
     ss += "\n--\n";
     if( debug_mode ) {
         ss += type->id.str();
         ss += "\n";
     }
     ss += string_format( _( "This is a %s. %s%s" ), name(),
                          player_knows ? att_colored + " " : std::string(),
                          difficulty_str ) + "\n";
     if( !get_effect_status().empty() ) {
         ss += string_format( _( "<stat>It is %s.</stat>" ), get_effect_status() ) + "\n";
     }
     ss += "--\n";
     const std::pair<std::string, nc_color> hp_bar = hp_description( hp, type->hp );
     ss += colorize( hp_bar.first, hp_bar.second ) + "\n";
     const std::string speed_desc = speed_description(
                                        speed_rating(),
                                        has_flag( mon_flag_IMMOBILE ),
                                        type->speed_desc );
     ss += speed_desc + "\n";
     ss += "--\n";
     ss += string_format( "<dark>%s</dark>", type->get_description() ) + "\n";
     ss += "--\n";
     if( !mission_fused.empty() ) {
         // Mission monsters fused into this monster
         const std::string fused_desc = string_format( _( "Parts of %s protrude from its body." ),
                                        enumerate_as_string( mission_fused ) );
         ss += string_format( "<dark>%s</dark>", fused_desc ) + "\n";
         ss += "--\n";
     }
     ss += string_format( _( "It is %s in size." ),
                          size_names.at( get_size() ) ) + "\n";
     std::vector<std::string> types = type->species_descriptions();
     if( type->has_flag( mon_flag_ANIMAL ) ) {
         types.emplace_back( _( "an animal" ) );
     }
     if( !types.empty() ) {
         ss += string_format( _( "It is %s." ),
                              enumerate_as_string( types ) ) + "\n";
     }
     using flag_description = std::pair<const mon_flag_id, std::string>;
     const auto describe_flags = [this, &ss](
                                     const std::string_view format,
                                     const std::vector<flag_description> &flags_names,
     const std::string &if_empty = "" ) {
         std::string flag_descriptions = enumerate_as_string( flags_names.begin(),
         flags_names.end(), [this]( const flag_description & fd ) {
             return type->has_flag( fd.first ) ? fd.second : "";
         } );
         if( !flag_descriptions.empty() ) {
             ss += string_format( format, flag_descriptions ) + "\n";
         } else if( !if_empty.empty() ) {
             ss += if_empty + "\n";
         }
     };
     using property_description = std::pair<bool, std::string>;
     const auto describe_properties = [&ss](
                                          const std::string_view format,
                                          const std::vector<property_description> &property_names,
     const std::string &if_empty = "" ) {
         std::string property_descriptions = enumerate_as_string( property_names.begin(),
         property_names.end(), []( const property_description & pd ) {
             return pd.first ? pd.second : "";
         } );
         if( !property_descriptions.empty() ) {
             ss += string_format( format, property_descriptions ) + "\n";
         } else if( !if_empty.empty() ) {
             ss += if_empty + "\n";
         }
     };
     describe_flags( _( "It has the following senses: %s." ), {
         {mon_flag_HEARS, pgettext( "Hearing as sense", "hearing" )},
         {mon_flag_SEES, pgettext( "Sight as sense", "sight" )},
         {mon_flag_SMELLS, pgettext( "Smell as sense", "smell" )},
     }, _( "It doesn't have senses." ) );
     describe_properties( _( "It can %s." ), {
         {swims(), pgettext( "Swim as an action", "swim" )},
         {flies(), pgettext( "Fly as an action", "fly" )},
         {can_dig(), pgettext( "Dig as an action", "dig" )},
         {climbs(), pgettext( "Climb as an action", "climb" )}
     } );
     describe_flags( _( "<bad>In fight it can %s.</bad>" ), {
         {mon_flag_GRABS, pgettext( "Grab as an action", "grab" )},
         {mon_flag_VENOM, pgettext( "Poison as an action", "poison" )},
         {mon_flag_PARALYZEVENOM, pgettext( "Paralyze as an action", "paralyze" )}
     } );
     if( !type->has_flag( mon_flag_NOHEAD ) ) {
         ss += std::string( _( "It has a head." ) ) + "\n";
     }
     if( debug_mode ) {
         ss += "--\n";
         ss += string_format( _( "Current Speed: %1$d" ), get_speed() ) + "\n";
         ss += string_format( _( "Anger: %1$d" ), anger ) + "\n";
         ss += string_format( _( "Friendly: %1$d" ), friendly ) + "\n";
         ss += string_format( _( "Morale: %1$d" ), morale ) + "\n";
         if( aggro_character ) {
             ss += string_format( _( "<color_red>Aggressive towards characters</color>" ) ) + "\n";
         }
         const time_duration current_time = calendar::turn - calendar::turn_zero;
         ss += string_format( _( "Current Time: Turn %1$d  |  Day: %2$d" ),
                              to_turns<int>( current_time ),
                              to_days<int>( current_time ) ) + "\n";
         ss += string_format( _( "Upgrade time: %1$d (turns left %2$d) %3$s" ),
                              upgrade_time,
                              to_turns<int>( time_duration::from_days( upgrade_time ) - current_time ),
                              can_upgrade() ? "" : _( "<color_red>(can't upgrade)</color>" ) ) + "\n";
         if( !special_attacks.empty() ) {
             ss += string_format( _( "%d special attack(s): " ), special_attacks.size() );
             for( const auto &attack : special_attacks ) {
                 ss += string_format( _( "%s, cooldown %d; " ), attack.first.c_str(), attack.second.cooldown );
             }
             ss += "\n";
         }
         if( baby_timer.has_value() ) {
             ss += string_format( _( "Reproduce time: %1$d (turns left %2$d) %3$s" ),
                                  to_turn<int>( baby_timer.value() ),
                                  to_turn<int>( baby_timer.value() - current_time ),
                                  reproduces ? "" : _( "<color_red>(can't reproduce)</color>" ) ) + "\n";
         }
         if( biosig_timer.has_value() ) {
             ss += string_format( _( "Biosignature time: %1$d (turns left %2$d) %3$s" ),
                                  to_turn<int>( biosig_timer.value() ),
                                  to_turn<int>( biosig_timer.value()  - current_time ),
                                  biosignatures ? "" : _( "<color_red>(no biosignature)</color>" ) ) + "\n";
         }
         if( lifespan_end.has_value() ) {
             ss += string_format( _( "Lifespan end time: %1$d (turns left %2$d)" ),
                                  to_turn<int>( lifespan_end.value() ),
                                  to_turn<int>( lifespan_end.value() - current_time ) );
         } else {
             ss += "Lifespan end time: n/a <color_yellow>(indefinite)</color>";
         }
     }
     return replace_colors( ss );
 }
References _, aggro_character, anger, arrow, spell_effect::attack(), baby_timer, biosig_timer, biosignatures, can_dig(), can_upgrade(), climbs(), colorize(), debug_mode, mtype::difficulty, enumerate_as_string(), flies(), friendly, time_duration::from_days(), get_attitude(), mtype::get_description(), get_effect_status(), get_player_character(), get_size(), Creature::get_speed(), has_flag(), mtype::has_flag(), Character::has_trait(), hp, mtype::hp, hp_description(), mtype::id, Creature::lifespan_end, mission_fused, mon_flag_ANIMAL, mon_flag_GRABS, mon_flag_HEARS, mon_flag_IMMOBILE, mon_flag_NOHEAD, mon_flag_PARALYZEVENOM, mon_flag_SEES, mon_flag_SMELLS, mon_flag_VENOM, morale, name(), pgettext, replace_colors(), reproduces, size_names, special_attacks, mtype::species_descriptions(), mtype::speed_desc, speed_description(), speed_rating(), mtype::src, string_id< T >::str(), string_format(), swims(), to_string(), trait_INATTENTIVE, calendar::turn, calendar::turn_zero, type, and upgrade_time.
fall_damage_mod()
float monster::fall_damage_mod () const override virtual
Returns multiplier on fall damage at low velocity (knockback/pit/1 z-level, not 5 z-levels)
Implements Creature.
Definition at line 2524 of file monster.cpp.
 {
     if( flies() ) {
         return 0.0f;
     }
     switch( type->size ) {
         case creature_size::tiny:
             return 0.2f;
         case creature_size::small:
             return 0.6f;
         case creature_size::medium:
             return 1.0f;
         case creature_size::large:
             return 1.4f;
         case creature_size::huge:
             return 2.0f;
         case creature_size::num_sizes:
             debugmsg( "ERROR: Invalid Creature size class." );
             return 0.0f;
     }
     return 0.0f;
 }
References debugmsg, flies(), huge, large, medium, num_sizes, mtype::size, small, tiny, and type.
Referenced by impact().
find_dragged_foe()
Character * monster::find_dragged_foe () private
Definition at line 1334 of file monmove.cpp.
 {
     // Make sure they're actually dragging someone.
     if( !dragged_foe_id.is_valid() || !has_effect( effect_dragging ) ) {
         dragged_foe_id = character_id();
         return nullptr;
     }
     // Dragged critters may die or otherwise become invalid, which is why we look
     // them up each time. Luckily, monsters dragging critters is relatively rare,
     // so this check should happen infrequently.
     Character *dragged_foe = g->critter_by_id<Character>( dragged_foe_id );
     if( dragged_foe == nullptr ) {
         // Target no longer valid.
         dragged_foe_id = character_id();
         remove_effect( effect_dragging );
     }
     return dragged_foe;
 }
References character_id, dragged_foe_id, effect_dragging, g, Creature::has_effect(), character_id::is_valid(), and Creature::remove_effect().
Referenced by move().
flies()
bool monster::flies () const
Definition at line 1262 of file monster.cpp.
 {
     return has_flag( mon_flag_FLIES ) && !has_effect_with_flag( json_flag_DISABLE_FLIGHT );
 }
References Creature::has_effect_with_flag(), has_flag(), json_flag_DISABLE_FLIGHT, and mon_flag_FLIES.
Referenced by avoid_trap(), calc_climb_cost(), calc_movecost(), can_climb(), can_drown(), can_reach_to(), extended_description(), fall_damage_mod(), footsteps(), is_immune_field(), know_danger_at(), trapfunc::ledge(), map::monster_in_field(), monster_move_in_vehicle(), move(), move_to(), process_effects(), and will_move_to().
footsteps()
void monster::footsteps (const tripoint & p)
Definition at line 1428 of file monmove.cpp.
 {
     if( is_hallucination() ) {
         return;
     }
     if( made_footstep ) {
         return;
     }
     made_footstep = true;
     int volume = 6; // same as player's footsteps
     if( flies() || has_flag( mon_flag_SILENTMOVES ) ) {
         volume = 0;    // Flying monsters don't have footsteps!
     }
     if( digging() ) {
         volume = 10;
     }
     switch( type->size ) {
         case creature_size::tiny:
             volume = 0; // No sound for the tinies
             break;
         case creature_size::small:
             volume /= 3;
             break;
         case creature_size::medium:
             break;
         case creature_size::large:
             volume *= 1.5;
             break;
         case creature_size::huge:
             volume *= 2;
             break;
         default:
             break;
     }
     if( has_flag( mon_flag_LOUDMOVES ) ) {
         volume += 6;
     } else if( has_flag( mon_flag_QUIETMOVES ) ) {
         volume -= 3;
     }
     if( volume == 0 ) {
         return;
     }
     int dist = rl_dist( p, get_player_character().pos() );
     sounds::add_footstep( p, volume, dist, this, type->get_footsteps() );
 }
References sounds::add_footstep(), digging(), flies(), mtype::get_footsteps(), get_player_character(), has_flag(), huge, is_hallucination(), large, made_footstep, medium, mon_flag_LOUDMOVES, mon_flag_QUIETMOVES, mon_flag_SILENTMOVES, Creature::pos(), rl_dist(), mtype::size, small, tiny, and type.
Referenced by move_to().
generate_inventory()
void monster::generate_inventory (bool disableDrops = true)
Definition at line 2991 of file monster.cpp.
 {
     if( is_hallucination() ) {
         return;
     }
     if( type->death_drops.is_empty() ) {
         return;
     }
     std::vector<item> new_items = item_group::items_from( type->death_drops,
                                   calendar::start_of_cataclysm,
                                   spawn_flags::use_spawn_rate );
     for( item &it : new_items ) {
         if( has_flag( mon_flag_FILTHY ) ) {
             if( ( it.is_armor() || it.is_pet_armor() ) && !it.is_gun() ) {
                 // handle wearable guns as a special case
                 it.set_flag( STATIC( flag_id( "FILTHY" ) ) );
             }
         }
         inv.push_back( it );
     }
     no_extra_death_drops = disableDrops;
 }
References mtype::death_drops, flag_id, has_flag(), inv, string_id< T >::is_empty(), is_hallucination(), item_group::items_from(), mon_flag_FILTHY, no_extra_death_drops, calendar::start_of_cataclysm, STATIC, type, and use_spawn_rate.
Referenced by poly().
get_absorb_material()
std::vector< material_id > monster::get_absorb_material () const
Definition at line 1345 of file monster.cpp.
 {
     return type->absorb_material;
 }
References mtype::absorb_material, and type.
Referenced by mattack::absorb_items(), and behavior::monster_oracle_t::items_available().
get_armor_type()
int monster::get_armor_type (const damage_type_id & dt, bodypart_id bp) const override virtual
Implements Creature.
Definition at line 2405 of file monster.cpp.
 {
     return get_worn_armor_val( dt ) + type->armor.type_resist( dt ) + get_armor_res_bonus( dt );
 }
References mtype::armor, Creature::get_armor_res_bonus(), get_worn_armor_val(), type, and resistances::type_resist().
Referenced by talker_monster_const::armor_at(), game::fling_creature(), impact(), know_danger_at(), map::monster_in_field(), move_to(), and process_one_effect().
get_attitude()
std::pair< std::string, nc_color > monster::get_attitude () const
Definition at line 794 of file monster.cpp.
 {
     const auto att = attitude_names.at( attitude( &get_player_character() ) );
     return {
         _( att.first ),
         all_colors.get( att.second )
     };
 }
References _, all_colors, attitude(), attitude_names, and get_player_character().
Referenced by extended_description(), and print_info().
get_carried_volume()
units::volume monster::get_carried_volume () const
Definition at line 3563 of file monster.cpp.
 {
     units::volume total_volume = 0_ml;
     for( const item &it : inv ) {
         total_volume += it.volume();
     }
     return total_volume;
 }
References inv.
Referenced by anonymous_namespace{monexamine.cpp}::give_items_to(), and stash_on_pet().
get_carried_weight()
units::mass monster::get_carried_weight () const
Definition at line 3545 of file monster.cpp.
 {
     units::mass total_weight = 0_gram;
     if( tack_item ) {
         total_weight += tack_item->weight();
     }
     if( storage_item ) {
         total_weight += storage_item->weight();
     }
     if( armor_item ) {
         total_weight += armor_item->weight();
     }
     for( const item &it : inv ) {
         total_weight += it.weight();
     }
     return total_weight;
 }
References armor_item, inv, storage_item, and tack_item.
Referenced by anonymous_namespace{monexamine.cpp}::add_armor(), anonymous_namespace{monexamine.cpp}::give_items_to(), and stash_on_pet().
get_dest()
tripoint_abs_ms monster::get_dest () const
Definition at line 1375 of file monster.cpp.
 {
     return goal ? *goal : get_location();
 }
References Creature::get_location(), and goal.
Referenced by attack_target(), attitude(), leap_actor::call(), has_vine_parent(), know_danger_at(), move(), nursebot_operate(), plan(), editmap::uber_draw_ter(), and mattack::vine().
get_dodge()
float monster::get_dodge () const override virtual
Reimplemented from Creature.
Definition at line 2465 of file monster.cpp.
 {
     if( has_effect( effect_downed ) ) {
         return 0.0f;
     }
     float ret = Creature::get_dodge();
     if( has_effect( effect_lightsnare ) || has_effect( effect_heavysnare ) ||
         has_effect( effect_beartrap ) || has_effect( effect_tied ) ) {
         ret /= 2;
     }
     if( has_effect( effect_bouldering ) ) {
         ret /= 4;
     }
     return ret;
 }
References effect_beartrap, effect_bouldering, effect_downed, effect_heavysnare, effect_lightsnare, effect_tied, Creature::get_dodge(), Creature::has_effect(), and cata::hash64_detail::ret.
Referenced by dodge_roll(), and trapfunc::tripwire().
get_dodge_base()
float monster::get_dodge_base () const override virtual
Implements Creature.
Definition at line 2415 of file monster.cpp.
 {
     return type->sk_dodge;
 }
References mtype::sk_dodge, and type.
get_eff_per()
int monster::get_eff_per () const override virtual
Reimplemented from Creature.
Definition at line 1657 of file monster.cpp.
 {
     return std::min( type->vision_night, type->vision_day );
 }
References min(), type, mtype::vision_day, and mtype::vision_night.
get_effect_status()
std::string monster::get_effect_status () const
Returns a std::string containing effects for descriptions.
Definition at line 2380 of file monster.cpp.
 {
     std::vector<std::string> effect_status;
     for( auto &elem : *effects ) {
         for( auto &_it : elem.second ) {
             if( elem.first->is_show_in_info() ) {
                 effect_status.push_back( _it.second.disp_name() );
             }
         }
     }
     return enumerate_as_string( effect_status );
 }
References Creature::effects, and enumerate_as_string().
Referenced by extended_description(), and print_info().
get_grab_strength()
int monster::get_grab_strength () const
Definition at line 2500 of file monster.cpp.
 {
     return type->grab_strength;
 }
References mtype::grab_strength, and type.
Referenced by melee_actor::call(), melee_actor::do_grab(), talker_monster_const::get_grab_strength(), and Creature::longpull().
get_hit_base()
float monster::get_hit_base () const override virtual
Implements Creature.
Definition at line 2410 of file monster.cpp.
 {
     return type->melee_skill;
 }
References mtype::melee_skill, and type.
get_horde_attraction()
monster_horde_attraction monster::get_horde_attraction ()
Definition at line 3818 of file monster.cpp.
 {
     if( horde_attraction == MHA_NULL ) {
         horde_attraction = static_cast<monster_horde_attraction>( rng( 1, 5 ) );
     }
     return horde_attraction;
 }
References horde_attraction, MHA_NULL, and rng().
Referenced by will_join_horde().
get_hp() [1/2]
int monster::get_hp () const override virtual
Reimplemented from Creature.
Definition at line 3748 of file monster.cpp.
 {
     return hp;
 }
References hp.
Referenced by attitude(), die(), hp_percentage(), and move_to().
get_hp() [2/2]
int monster::get_hp (const bodypart_id &) const override virtual
Reimplemented from Creature.
Definition at line 3743 of file monster.cpp.
 {
     return hp;
 }
References hp.
Referenced by mattack::absorb_items(), mattack::absorb_meat(), mdeath::broken(), spell_effect::charm_monster(), mattack::chickenbot(), mattack::copbot(), anonymous_namespace{monexamine.cpp}::cull(), mattack::dermatik(), npc::evaluate_monster(), mattack::formblob(), mattack::generator(), talker_monster_const::get_cur_hp(), iuse::granade_act(), creature_tracker::kill_marked_for_death(), mattack::multi_robot(), mdeath::normal(), game::revive_corpse(), mattack::riotbot(), mattack::searchlight(), mdeath::splatter(), mattack::split(), behavior::monster_oracle_t::split_possible(), and mattack::zombie_fuse().
get_HP_Bar()
void monster::get_HP_Bar (nc_color & color, std::string & text) const
Definition at line 789 of file monster.cpp.
 {
     std::tie( text, color ) = ::get_hp_bar( hp, type->hp, true );
 }
References color(), get_hp_bar(), hp, mtype::hp, and type.
Referenced by print_info().
get_hp_max() [1/2]
int monster::get_hp_max () const override virtual
Reimplemented from Creature.
Definition at line 3738 of file monster.cpp.
 {
     return type->hp;
 }
References mtype::hp, and type.
Referenced by attitude(), and hp_percentage().
get_hp_max() [2/2]
int monster::get_hp_max (const bodypart_id &) const override virtual
Reimplemented from Creature.
Definition at line 3733 of file monster.cpp.
 {
     return type->hp;
 }
References mtype::hp, and type.
Referenced by mattack::absorb_meat(), mdeath::broken(), mattack::chickenbot(), mattack::copbot(), mattack::dermatik(), npc::evaluate_monster(), mattack::formblob(), mattack::generator(), talker_monster_const::get_hp_max(), iuse::granade_act(), mattack::mon_leech_evolution(), mattack::multi_robot(), mdeath::normal(), mattack::riotbot(), mattack::searchlight(), mdeath::splatter(), behavior::monster_oracle_t::split_possible(), and mattack::zombie_fuse().
get_melee()
float monster::get_melee () const override virtual
Implements Creature.
Definition at line 2484 of file monster.cpp.
 {
     return type->melee_skill;
 }
References mtype::melee_skill, and type.
get_monster_faction()
mfaction_id monster::get_monster_faction () const inline override virtual
Implements Creature.
Definition at line 108 of file monster.h.
{
             return faction.id();
         }
References faction_template::id.
get_mountable_weight_ratio()
float monster::get_mountable_weight_ratio () const
Definition at line 3753 of file monster.cpp.
 {
     return type->mountable_weight_ratio;
 }
References mtype::mountable_weight_ratio, and type.
Referenced by Character::can_mount(), and monexamine::pet_menu().
get_name()
std::string monster::get_name () const override virtual
Implements Creature.
Definition at line 717 of file monster.cpp.
 {
     return name( 1 );
 }
References name().
Referenced by anonymous_namespace{monexamine.cpp}::add_armor(), anonymous_namespace{monexamine.cpp}::add_leash(), assemble_profession_details(), anonymous_namespace{monexamine.cpp}::attach_bag_to(), check_mech_powered(), mattack::check_money_left(), anonymous_namespace{monexamine.cpp}::dump_items(), game::examine(), game::find_or_make_stairs(), milk_activity_actor::finish(), liquid_handler::get_liquid_target(), talker_monster_const::get_name(), anonymous_namespace{monexamine.cpp}::give_items_to(), anonymous_namespace{monexamine.cpp}::insert_battery(), trapfunc::lava(), monexamine::mech_hack(), melee_attack(), monexamine::mfriend_menu(), anonymous_namespace{monexamine.cpp}::milk_source(), Character::mount_creature(), move_effects(), monexamine::pay_bot(), monexamine::pet_menu(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), anonymous_namespace{monexamine.cpp}::play_with(), avatar_action::plthrow(), anonymous_namespace{monexamine.cpp}::push(), refill_udders(), anonymous_namespace{monexamine.cpp}::remove_armor(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), anonymous_namespace{monexamine.cpp}::remove_harness(), anonymous_namespace{monexamine.cpp}::remove_leash(), trapfunc::sinkhole(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), anonymous_namespace{monexamine.cpp}::start_leading(), anonymous_namespace{monexamine.cpp}::stop_leading(), anonymous_namespace{monexamine.cpp}::swap(), vehicle::thrust(), anonymous_namespace{monexamine.cpp}::tie_pet(), trapfunc::tripwire(), anonymous_namespace{monexamine.cpp}::untie_pet(), vehicle::use_harness(), game::vertical_move(), game::walk_move(), and witness_thievery().
get_no_absorb_material()
std::vector< material_id > monster::get_no_absorb_material () const
Definition at line 1350 of file monster.cpp.
 {
     return type->no_absorb_material;
 }
References mtype::no_absorb_material, and type.
Referenced by mattack::absorb_items(), and behavior::monster_oracle_t::items_available().
get_path_avoid()
std::unordered_set< tripoint > monster::get_path_avoid () const override virtual
Returns a set of points we do not want to path through.
Implements Creature.
Definition at line 3986 of file monster.cpp.
 {
     std::unordered_set<tripoint> ret;
     map &here = get_map();
     int radius = std::min( sight_range( here.ambient_light_at( pos() ) ), 5 );
     for( const tripoint &p : here.points_in_radius( pos(), radius ) ) {
         if( !can_move_to( p ) ) {
             if( bash_skill() <= 0 || !here.is_bashable( p ) ) {
                 ret.insert( p );
             }
         }
     }
     if( has_flag( mon_flag_PRIORITIZE_TARGETS ) ) {
         radius = 2;
     } else if( has_flag( mon_flag_PATH_AVOID_DANGER_1 ) ||
                has_flag( mon_flag_PATH_AVOID_DANGER_2 ) ) {
         radius = 1;
     } else {
         return ret;
     }
     for( Creature *critter : here.get_creatures_in_radius( pos(), radius ) ) {
         ret.insert( critter->pos() );
     }
     return ret;
 }
References map::ambient_light_at(), bash_skill(), can_move_to(), map::get_creatures_in_radius(), get_map(), has_flag(), map::is_bashable(), min(), mon_flag_PATH_AVOID_DANGER_1, mon_flag_PATH_AVOID_DANGER_2, mon_flag_PRIORITIZE_TARGETS, map::points_in_radius(), Creature::pos(), cata::hash64_detail::ret, and sight_range().
Referenced by move().
get_pathfinding_settings()
const pathfinding_settings & monster::get_pathfinding_settings () const override virtual
Returns settings for pathfinding.
Implements Creature.
Definition at line 3981 of file monster.cpp.
 {
     return type->path_settings;
 }
References mtype::path_settings, and type.
Referenced by has_intelligence(), know_danger_at(), move(), turns_to_reach(), and will_reach().
get_size()
creature_size monster::get_size () const override virtual
Implements Creature.
Definition at line 3503 of file monster.cpp.
 {
     return static_cast<creature_size>( type->size + size_bonus );
 }
References mtype::size, Creature::size_bonus, and type.
Referenced by Character::add_msg_player_or_say(), blobify(), leap_actor::call(), Character::can_mount(), iuse::capture_monster_act(), Creature::deal_melee_hit(), drop_or_embed_projectile(), explosion_handler::emp_blast(), extended_description(), Character::footstep_sound(), talker_monster_const::get_size(), get_volume(), get_weight(), monster_move_in_vehicle(), monexamine::pet_menu(), power_rating(), print_info(), process_effects(), shove_vehicle(), Character::swim_speed(), game::walk_move(), will_move_to(), and mattack::zombie_fuse().
get_upgrade_time()
int monster::get_upgrade_time () const
Definition at line 418 of file monster.cpp.
 {
     return upgrade_time;
 }
References upgrade_time.
Referenced by make_mon_corpse(), and mdeath::splatter().
get_volume()
units::volume monster::get_volume () const
Definition at line 3518 of file monster.cpp.
 {
     return units::operator*( type->volume, get_size() / type->size );
 }
References get_size(), units::operator*(), mtype::size, type, and mtype::volume.
Referenced by mattack::absorb_meat(), talker_monster_const::get_volume(), monster_move_in_vehicle(), anonymous_namespace{monexamine.cpp}::pet_armor_loc(), shearing_entry::roll(), and mattack::zombie_fuse().
get_weight()
units::mass monster::get_weight () const override virtual
Implements Creature.
Definition at line 3508 of file monster.cpp.
 {
     return units::operator*( type->weight, get_size() / type->size );
 }
References get_size(), units::operator*(), mtype::size, type, and mtype::weight.
Referenced by vehicle::calc_mass_center(), Character::can_mount(), item::contain_monster(), melee_actor::do_grab(), talker_monster_const::get_weight(), monexamine::pet_menu(), shearing_entry::roll(), map::shake_vehicle(), and mdeath::splatter().
get_worn_armor_val()
int monster::get_worn_armor_val (const damage_type_id & dt) const
Definition at line 2394 of file monster.cpp.
 {
     if( !has_effect( effect_monster_armor ) ) {
         return 0;
     }
     if( armor_item ) {
         return armor_item->resist( dt );
     }
     return 0;
 }
References armor_item, effect_monster_armor, and Creature::has_effect().
Referenced by absorb_hit(), and get_armor_type().
gibType()
field_type_id monster::gibType () const override virtual
Implements Creature.
Definition at line 3495 of file monster.cpp.
 {
     if( is_hallucination() ) {
         return fd_null;
     }
     return type->gibType();
 }
References fd_null, mtype::gibType(), is_hallucination(), and type.
Referenced by scatter_chunks(), and mdeath::splatter().
group_bash_skill()
int monster::group_bash_skill (const tripoint & target)
Returns ability of monster and any cooperative helpers to bash the designated target.
Definition at line 1735 of file monmove.cpp.
 {
     if( !has_flag( mon_flag_GROUP_BASH ) ) {
         return bash_skill();
     }
     int bashskill = 0;
     // pileup = more bash skill, but only help bashing mob directly in front of target
     const int max_helper_depth = 5;
     const std::vector<tripoint> bzone = get_bashing_zone( target, pos(), max_helper_depth );
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &candidate : bzone ) {
         // Drawing this line backwards excludes the target and includes the candidate.
         std::vector<tripoint> path_to_target = line_to( target, candidate, 0, 0 );
         bool connected = true;
         monster *mon = nullptr;
         for( const tripoint &in_path : path_to_target ) {
             // If any point in the line from zombie to target is not a cooperating zombie,
             // it can't contribute.
             mon = creatures.creature_at<monster>( in_path );
             if( !mon ) {
                 connected = false;
                 break;
             }
             monster &helpermon = *mon;
             if( !helpermon.has_flag( mon_flag_GROUP_BASH ) || helpermon.is_hallucination() ) {
                 connected = false;
                 break;
             }
         }
         if( !connected || !mon ) {
             continue;
         }
         // If we made it here, the last monster checked was the candidate.
         monster &helpermon = *mon;
         // Contribution falls off rapidly with distance from target.
         bashskill += helpermon.bash_skill() / rl_dist( candidate, target );
     }
     return bashskill;
 }
References bash_skill(), creature_tracker::creature_at(), get_bashing_zone(), get_creature_tracker(), has_flag(), is_hallucination(), line_to(), mon_flag_GROUP_BASH, Creature::pos(), and rl_dist().
Referenced by bash_at().
has_dest()
bool monster::has_dest () const
Definition at line 1370 of file monster.cpp.
 {
     return goal.has_value();
 }
References goal.
Referenced by attack_target(), leap_actor::call(), has_vine_parent(), is_wandering(), nursebot_operate(), and editmap::uber_draw_ter().
has_flag() [1/2]
bool monster::has_flag (const mon_flag_id & f) const final virtual
Reimplemented from Creature.
Definition at line 1202 of file monster.cpp.
 {
     return type->has_flag( f );
 }
References mtype::has_flag(), and type.
Referenced by Character::add_msg_player_or_say(), attack_at(), attitude(), npc::attitude_to(), bash_estimate(), melee_actor::call(), can_attack_high(), can_dig(), disable_activity_actor::can_disable_or_reprogram(), can_drown(), can_hear(), Character::can_mount(), can_see(), can_submerge(), Character::can_wield(), game::chat(), check_mech_powered(), climbs(), deal_damage_handle_type(), Creature::deal_melee_hit(), deal_projectile_attack(), mattack::depart(), die(), digs(), Character::dismount(), drop_items_on_death(), explosion_handler::emp_blast(), game::examine(), extended_description(), iuse::extinguisher(), disable_activity_actor::finish(), flies(), Character::footstep_sound(), footsteps(), generate_inventory(), get_path_avoid(), group_bash_skill(), talker_monster_const::has_flag(), has_flag(), has_intelligence(), has_mind(), has_weapon(), hear_sound(), impact(), is_electrical(), is_fae(), is_immune_damage(), is_immune_effect(), is_immune_field(), is_nemesis(), is_pet_follow(), is_warm(), knock_back_to(), know_danger_at(), iuse::mace(), melee_attack(), monexamine::mfriend_menu(), mattack::mon_leech_evolution(), monster(), map::monster_in_field(), monster_move_in_vehicle(), monster_plan::monster_plan(), Character::mount_creature(), move(), avatar_action::move(), move_to(), mdeath::normal(), bite_actor::on_damage(), on_load(), monexamine::pet_menu(), avatar_action::plthrow(), print_info(), process_effects(), process_turn(), push_to(), refill_udders(), scent_move(), explosion_handler::scrambler_blast(), shove_vehicle(), sight_range(), smash(), mattack::smash_specific(), stumble(), swims(), try_reproduce(), place_monster_iuse::use(), vehicle::use_harness(), use_mech_power(), game::vertical_move(), game::walk_move(), suffer::while_grabbed(), will_join_horde(), will_move_to(), and will_reach().
has_flag() [2/2]
bool monster::has_flag (flag_id f) const
Definition at line 1207 of file monster.cpp.
 {
     mon_flag_str_id checked( f.c_str() );
     add_msg_debug( debugmode::DF_MONSTER,
                    "Monster %s checked for flag %s", name(),
                    f.c_str() );
     if( checked.is_valid() ) {
         return has_flag( checked );
     } else {
         return has_effect_with_flag( f );
     }
 }
References add_msg_debug, string_id< T >::c_str(), debugmode::DF_MONSTER, Creature::has_effect_with_flag(), has_flag(), string_id< T >::is_valid(), and name().
has_grab_break_tec()
bool monster::has_grab_break_tec () const override virtual
Implements Creature.
Definition at line 2430 of file monster.cpp.
 {
     return false;
 }
has_intelligence()
bool monster::has_intelligence () const
Definition at line 1334 of file monster.cpp.
 {
     return has_flag( mon_flag_PATH_AVOID_FALL ) ||
            has_flag( mon_flag_PATH_AVOID_FIRE ) ||
            has_flag( mon_flag_PATH_AVOID_DANGER_1 ) ||
            has_flag( mon_flag_PATH_AVOID_DANGER_2 ) ||
            has_flag( mon_flag_PRIORITIZE_TARGETS ) ||
            get_pathfinding_settings().avoid_sharp ||
            get_pathfinding_settings().avoid_traps;
 }
References pathfinding_settings::avoid_sharp, pathfinding_settings::avoid_traps, get_pathfinding_settings(), has_flag(), mon_flag_PATH_AVOID_DANGER_1, mon_flag_PATH_AVOID_DANGER_2, mon_flag_PATH_AVOID_FALL, mon_flag_PATH_AVOID_FIRE, and mon_flag_PRIORITIZE_TARGETS.
Referenced by move().
has_mind()
bool monster::has_mind () const override virtual
Implements Creature.
Definition at line 3482 of file monster.cpp.
 {
     return ( !in_species( species_PSI_NULL ) && has_flag( mon_flag_HAS_MIND ) ) ||
            ( !in_species( species_PSI_NULL ) && !in_species( species_ZOMBIE ) && has_flag( mon_flag_HUMAN ) );
 }
References has_flag(), in_species(), mon_flag_HAS_MIND, mon_flag_HUMAN, species_PSI_NULL, and species_ZOMBIE.
has_special()
bool monster::has_special (const std::string & special_name) const
Test whether the monster has the specified special regardless of readiness.
Definition at line 2613 of file monster.cpp.
 {
     std::map<std::string, mon_special_attack>::const_iterator iter = special_attacks.find(
                 special_name );
     return iter != special_attacks.end() && iter->second.enabled;
 }
References special_attacks.
Referenced by behavior::monster_oracle_t::special_available(), and behavior::monster_oracle_t::split_possible().
has_weapon()
bool monster::has_weapon () const override virtual
Implements Creature.
Definition at line 1759 of file monster.cpp.
 {
     return has_flag( mon_flag_WIELDED_WEAPON ) && !has_effect( effect_disarmed ) &&
            !has_effect( effect_maimed_arm ); // monsters can actually have weapons, silly
 }
References effect_disarmed, effect_maimed_arm, Creature::has_effect(), has_flag(), and mon_flag_WIELDED_WEAPON.
hasten_upgrade()
void monster::hasten_upgrade ()
Definition at line 405 of file monster.cpp.
 {
     if( !can_upgrade() || upgrade_time < 1 ) {
         return;
     }
     const int scaled_half_life = type->half_life * get_option<float>( "MONSTER_UPGRADE_FACTOR" );
     upgrade_time -= rng( 1, scaled_half_life );
     if( upgrade_time < 0 ) {
         upgrade_time = 0;
     }
 }
References can_upgrade(), mtype::half_life, rng(), type, and upgrade_time.
Referenced by mattack::upgrade().
heal()
int monster::heal (int delta_hp, bool overheal = false)
Flat addition to the monsters hp.
If overheal is true, this is not capped by max hp. Returns actually healed hp.
Definition at line 2149 of file monster.cpp.
 {
     const int maxhp = type->hp;
     if( delta_hp <= 0 || ( hp >= maxhp && !overheal ) ) {
         return 0;
     }
     const int old_hp = hp;
     hp += delta_hp;
     if( hp > maxhp && !overheal ) {
         hp = maxhp;
     }
     return hp - old_hp;
 }
References hp, mtype::hp, and type.
Referenced by mattack::absorb_meat(), mattack::formblob(), mattack::generator(), spell::heal(), heal_bp(), on_load(), process_effects(), and mattack::zombie_fuse().
heal_bp()
void monster::heal_bp (bodypart_id bp, int dam) override virtual
Reimplemented from Creature.
Definition at line 2195 of file monster.cpp.
 {
     heal( dam );
 }
References heal().
hear_sound()
void monster::hear_sound (const tripoint & source, int vol, int distance, bool provocative)
Makes monster react to heard sound.
Parameters
source Location of the sound source
vol Volume at the center of the sound source
distance Distance to sound source (currently just rl_dist)
Definition at line 3758 of file monster.cpp.
 {
     if( !can_hear() ) {
         return;
     }
     const bool goodhearing = has_flag( mon_flag_GOODHEARING );
     const int volume = goodhearing ? 2 * vol - dist : vol - dist;
     // Error is based on volume, louder sound = less error
     if( volume <= 0 ) {
         return;
     }
     int tmp_provocative = provocative || volume >= normal_roll( 30, 5 );
     // already following a more interesting sound
     if( provocative_sound && !tmp_provocative && wandf > 0 ) {
         return;
     }
     int max_error = 0;
     if( volume < 2 ) {
         max_error = 10;
     } else if( volume < 5 ) {
         max_error = 5;
     } else if( volume < 10 ) {
         max_error = 3;
     } else if( volume < 20 ) {
         max_error = 1;
     }
     tripoint_abs_ms target = get_map().getglobal( source ) + point( rng( -max_error, max_error ),
                              rng( -max_error, max_error ) );
     // target_z will require some special check due to soil muffling sounds
     const int wander_turns = volume * ( goodhearing ? 6 : 1 );
     // again, already following a more interesting sound
     if( wander_turns < wandf ) {
         return;
     }
     // only trigger this if the monster is not friendly or the source isn't the player
     if( friendly == 0 || source != get_player_character().pos() ) {
         process_trigger( mon_trigger::SOUND, volume );
     }
     provocative_sound = tmp_provocative;
     if( morale >= 0 && anger >= 10 ) {
         // TODO: Add a proper check for fleeing attitude
         // but cache it nicely, because this part is called a lot
         wander_to( target, wander_turns );
     } else if( morale < 0 ) {
         // Monsters afraid of sound should not go towards sound.
         // Move towards a point on the opposite side of us from the target.
         // TODO: make the destination scale with the sound and handle
         // the case when (x,y) is the same by picking a random direction
         tripoint_abs_ms away = get_location() + ( get_location() - target );
         away.z() = posz();
         wander_to( away, wander_turns );
     }
 }
References anger, can_hear(), friendly, Creature::get_location(), get_map(), get_player_character(), map::getglobal(), has_flag(), mon_flag_GOODHEARING, morale, normal_roll(), point, Creature::pos(), Creature::posz(), process_trigger(), provocative_sound, rng(), SOUND, wander_to(), wandf, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
hit_roll()
float monster::hit_roll () const override virtual
Should always be overwritten by the appropriate player/NPC/monster version.
Implements Creature.
Definition at line 2420 of file monster.cpp.
 {
     float hit = get_hit();
     if( has_effect( effect_bouldering ) ) {
         hit /= 4;
     }
     return melee::melee_hit_range( hit );
 }
References effect_bouldering, Creature::get_hit(), Creature::has_effect(), and melee::melee_hit_range().
hp_percentage()
int monster::hp_percentage () const override virtual
Implements Creature.
Definition at line 1652 of file monster.cpp.
 {
     return get_hp( bodypart_id( "torso" ) ) * 100 / get_hp_max();
 }
References get_hp(), and get_hp_max().
Referenced by iuse::capture_monster_act(), and poly().
impact()
int monster::impact (int force, const tripoint & pos) override virtual
Deals falling/collision damage with terrain/creature at pos.
Implements Creature.
Definition at line 2549 of file monster.cpp.
 {
     if( force <= 0 ) {
         return force;
     }
     const float mod = fall_damage_mod();
     int total_dealt = 0;
     if( get_map().has_flag( ter_furn_flag::TFLAG_SHARP, p ) ) {
         const int cut_damage = std::max( 0.0f, 10 * mod - get_armor_type( damage_cut,
                                          bodypart_id( "torso" ) ) );
         apply_damage( nullptr, bodypart_id( "torso" ), cut_damage );
         total_dealt += 10 * mod;
     }
     const int bash_damage = std::max( 0.0f, force * mod - get_armor_type( damage_bash,
                                       bodypart_id( "torso" ) ) );
     apply_damage( nullptr, bodypart_id( "torso" ), bash_damage );
     total_dealt += force * mod;
     add_effect( effect_downed, time_duration::from_turns( rng( 0, mod * 3 + 1 ) ) );
     return total_dealt;
 }
References Creature::add_effect(), apply_damage(), damage_bash, damage_cut, effect_downed, fall_damage_mod(), force, time_duration::from_turns(), get_armor_type(), get_map(), has_flag(), max(), rng(), and TFLAG_SHARP.
in_species()
bool monster::in_species (const species_id & spec) const override virtual
Reimplemented from Creature.
Definition at line 1770 of file monster.cpp.
 {
     return type->in_species( spec );
 }
References mtype::in_species(), and type.
Referenced by has_mind(), talker_monster_const::has_species(), is_electrical(), is_nether(), and anonymous_namespace{math_parser_diag.cpp}::mon_check_species().
increment_pathfinding_cd()
void monster::increment_pathfinding_cd () inline private
Definition at line 645 of file monster.h.
{
             pathfinding_cd = calendar::turn + pathfinding_backoff;
             pathfinding_backoff = std::min( pathfinding_backoff * 2, 10_seconds );
         }
References min(), pathfinding_backoff, pathfinding_cd, and calendar::turn.
Referenced by move().
init_from_item()
void monster::init_from_item (item & itm)
Initialize values like speed / hp from data of an item.
This applies to robotic monsters that are spawned by invoking an item (e.g. turret), and to reviving monsters that spawn from a corpse.
Definition at line 3590 of file monster.cpp.
 {
     if( itm.is_corpse() ) {
         set_speed_base( get_speed_base() * 0.8 );
         const int burnt_penalty = itm.burnt;
         hp = static_cast<int>( hp * 0.7 );
         if( itm.damage_level() > 0 ) {
             set_speed_base( speed_base / ( itm.damage_level() + 1 ) );
             hp /= itm.damage_level() + 1;
         }
         hp -= burnt_penalty;
         // HP can be 0 or less, in this case revive_corpse will just deactivate the corpse
         if( hp > 0 && type->has_flag( mon_flag_REVIVES_HEALTHY ) ) {
             hp = type->hp;
             set_speed_base( type->speed );
         }
         // if parent corpse is revives healthy *and* dormant, so will the monster
         const mtype *corpse_mtype = itm.get_mtype();
         if( hp > 0 && corpse_mtype->has_flag( mon_flag_REVIVES_HEALTHY ) &&
             corpse_mtype->has_flag( mon_flag_DORMANT ) ) {
             hp = type->hp;
             set_speed_base( type->speed );
         }
         const std::string up_time = itm.get_var( "upgrade_time" );
         if( !up_time.empty() ) {
             upgrade_time = std::stoi( up_time );
         }
         for( item *it : itm.all_items_top( pocket_type::CONTAINER ) ) {
             if( it->is_armor() ) {
                 it->set_flag( STATIC( flag_id( "FILTHY" ) ) );
             }
             inv.push_back( *it );
             itm.remove_item( *it );
         }
         //Move dissectables (installed bionics, etc)
         for( item *dissectable : itm.all_items_top( pocket_type::CORPSE ) ) {
             dissectable_inv.push_back( *dissectable );
             itm.remove_item( *dissectable );
         }
     } else {
         // must be a robot
         const int damfac = itm.max_damage() - std::max( 0, itm.damage() ) + 1;
         // One hp at least, everything else would be unfair (happens only to monster with *very* low hp),
         hp = std::max( 1, hp * damfac / ( itm.max_damage() + 1 ) );
     }
 }
References item::all_items_top(), item::burnt, CONTAINER, CORPSE, item::damage(), item::damage_level(), dissectable_inv, flag_id, item::get_mtype(), Creature::get_speed_base(), item::get_var(), mtype::has_flag(), hp, mtype::hp, inv, item::is_corpse(), max(), item::max_damage(), mon_flag_DORMANT, mon_flag_REVIVES_HEALTHY, visitable::remove_item(), Creature::set_speed_base(), mtype::speed, Creature::speed_base, STATIC, type, and upgrade_time.
Referenced by game::revive_corpse(), and place_monster_iuse::use().
is_aquatic_danger()
bool monster::is_aquatic_danger (const tripoint & at_pos) const
Returns true if the given square presents a possibility of drowning for the monster: it's deep water, it's liquid, the monster can drown, and there is no boardable vehicle part present.
Definition at line 841 of file monmove.cpp.
 {
     map &here = get_map();
     return here.has_flag_ter( ter_furn_flag::TFLAG_DEEP_WATER, at_pos ) &&
            here.has_flag( ter_furn_flag::TFLAG_LIQUID, at_pos ) &&
            can_drown() && !here.veh_at( at_pos ).part_with_feature( "BOARDABLE", false );
 }
References can_drown(), get_map(), map::has_flag(), map::has_flag_ter(), optional_vpart_position::part_with_feature(), TFLAG_DEEP_WATER, TFLAG_LIQUID, and map::veh_at().
Referenced by die_if_drowning().
is_dead()
bool monster::is_dead () const
Definition at line 3580 of file monster.cpp.
 {
     return dead || is_dead_state();
 }
References dead, and is_dead_state().
Referenced by explosion_handler::emp_blast(), game::fling_creature(), game::forced_door_closing(), talker_monster::get_is_alive(), creature_tracker::kill_marked_for_death(), move(), avatar_action::move(), move_to(), creature_tracker::remove_dead(), iuse::robotcontrol_can_target(), stumble(), and creature_tracker::update_pos().
is_dead_state()
bool monster::is_dead_state () const override virtual
Implements Creature.
Definition at line 1865 of file monster.cpp.
 {
     return hp <= 0;
 }
References hp.
Referenced by apply_damage(), drop_or_embed_projectile(), is_dead(), and mdefense::return_fire().
is_elec_immune()
bool monster::is_elec_immune () const override virtual
Implements Creature.
Definition at line 1775 of file monster.cpp.
 {
     return is_immune_damage( damage_electric );
 }
References damage_electric, and is_immune_damage().
is_electrical()
bool monster::is_electrical () const override virtual
Implements Creature.
Definition at line 3465 of file monster.cpp.
 {
     return in_species( species_ROBOT ) || has_flag( mon_flag_ELECTRIC ) || in_species( species_CYBORG );
 }
References has_flag(), in_species(), mon_flag_ELECTRIC, species_CYBORG, and species_ROBOT.
is_fae()
bool monster::is_fae () const override virtual
Implements Creature.
Definition at line 3470 of file monster.cpp.
 {
     return has_flag( mon_flag_FAE_CREATURE );
 }
References has_flag(), and mon_flag_FAE_CREATURE.
is_fleeing()
bool monster::is_fleeing (Character & u) const
Definition at line 1438 of file monster.cpp.
 {
     if( effect_cache[FLEEING] ) {
         return true;
     }
     if( anger >= 100 || morale >= 100 ) {
         return false;
     }
     monster_attitude att = attitude( &u );
     return att == MATT_FLEE || ( att == MATT_FOLLOW && rl_dist( pos(), u.pos() ) <= 4 );
 }
References anger, attitude(), effect_cache, FLEEING, MATT_FLEE, MATT_FOLLOW, morale, Creature::pos(), rl_dist(), and u.
Referenced by plan(), process_effects(), and scent_move().
is_grabbing()
bool monster::is_grabbing (bodypart_str_id bp)
Definition at line 2519 of file monster.cpp.
 {
     return has_effect( effect_grabbing ) && grabbed_limbs.find( bp ) != grabbed_limbs.end();
 }
References bp, effect_grabbing, grabbed_limbs, and Creature::has_effect().
Referenced by melee_actor::call(), die(), Character::perform_technique(), and Character::try_remove_grab().
is_hallucination()
bool monster::is_hallucination () const override virtual
Implements Creature.
Definition at line 3460 of file monster.cpp.
 {
     return hallucination;
 }
References hallucination.
Referenced by creature_tracker::add(), attack_at(), bash_at(), bloodType(), iuse::camera(), check_mech_powered(), deal_projectile_attack(), game::despawn_monster(), die(), drop_items_on_death(), footsteps(), generate_inventory(), gibType(), iuse::granade_act(), group_bash_skill(), knock_back_to(), make_fungus(), melee_attack(), move(), avatar_action::move(), move_to(), behavior::monster_oracle_t::not_hallucination(), on_hit(), photo_def_for_camera_point(), process_turn(), push_to(), shove_vehicle(), spawn_dissectables_on_death(), stumble(), try_biosignature(), and use_mech_power().
is_immune_damage()
bool monster::is_immune_damage (const damage_type_id & dt) const override virtual
Implements Creature.
Definition at line 1829 of file monster.cpp.
 {
     if( !dt->mon_immune_flags.empty() ) {
         for( const std::string &mf : dt->mon_immune_flags ) {
             if( has_flag( mon_flag_id( mf ) ) ) {
                 return true;
             }
         }
     }
     // FIXME: Hardcoded damage type specific immunities
     if( dt == damage_heat && ( made_of( material_steel ) || made_of( material_stone ) ) ) {
         return true;
     }
     if( dt == damage_electric && type->sp_defense == &mdefense::zapback ) {
         return true;
     }
     return false;
 }
References damage_electric, damage_heat, has_flag(), made_of(), material_steel, material_stone, damage_type::mon_immune_flags, mtype::sp_defense, type, and mdefense::zapback().
Referenced by deal_damage_handle_type(), is_elec_immune(), and is_immune_effect().
is_immune_effect()
bool monster::is_immune_effect (const efftype_id & effect) const override virtual
Implements Creature.
Definition at line 1780 of file monster.cpp.
 {
     if( effect == effect_onfire ) {
         return is_immune_damage( damage_heat ) ||
                made_of( phase_id::LIQUID ) ||
                has_flag( mon_flag_FIREY );
     }
     if( effect == effect_bleed ) {
         return ( type->bloodType() == fd_null || type->bleed_rate == 0 );
     }
     if( effect == effect_venom_dmg ||
         effect == effect_venom_player1 ||
         effect == effect_venom_player2 ) {
         return ( !made_of( material_flesh ) && !made_of( material_iflesh ) ) ||
                type->in_species( species_NETHER ) || type->in_species( species_MIGO ) ||
                type->in_species( species_LEECH_PLANT );
     }
     if( effect == effect_paralyzepoison ||
         effect == effect_badpoison ||
         effect == effect_venom_weaken ||
         effect == effect_poison ) {
         return type->in_species( species_ZOMBIE ) || type->in_species( species_NETHER ) ||
                type->in_species( species_MIGO ) ||
                !made_of_any( Creature::cmat_flesh ) || type->in_species( species_LEECH_PLANT );
     }
     if( effect == effect_tpollen ) {
         return type->in_species( species_PLANT );
     }
     if( effect == effect_stunned ) {
         return has_flag( mon_flag_STUN_IMMUNE );
     }
     if( effect == effect_downed ) {
         if( type->bodytype == "insect" || type->bodytype == "flying insect" || type->bodytype == "spider" ||
             type->bodytype == "crab" ) {
             return x_in_y( 3, 4 );
         } else {
             return type->bodytype == "snake" || type->bodytype == "blob" || type->bodytype == "fish" ||
                    has_flag( mon_flag_FLIES ) || has_flag( mon_flag_IMMOBILE );
         }
     }
     return false;
 }
References mtype::bleed_rate, mtype::bloodType(), mtype::bodytype, Creature::cmat_flesh, damage_heat, effect_badpoison, effect_bleed, effect_downed, effect_onfire, effect_paralyzepoison, effect_poison, effect_stunned, effect_tpollen, effect_venom_dmg, effect_venom_player1, effect_venom_player2, effect_venom_weaken, fd_null, has_flag(), mtype::in_species(), is_immune_damage(), LIQUID, made_of(), made_of_any(), material_flesh, material_iflesh, mon_flag_FIREY, mon_flag_FLIES, mon_flag_IMMOBILE, mon_flag_STUN_IMMUNE, species_LEECH_PLANT, species_MIGO, species_NETHER, species_PLANT, species_ZOMBIE, type, and x_in_y().
is_immune_field()
bool monster::is_immune_field (const field_type_id &) const override virtual
Returns true if we are immune to the field type with the given fid.
Can handle intensity if field intensity data is specified for the effect , so this function should only be called through is_dangerous_field().
Reimplemented from Creature.
Definition at line 93 of file monmove.cpp.
 {
     if( fid == fd_fungal_haze ) {
         return has_flag( mon_flag_NO_BREATHE ) || type->in_species( species_FUNGUS );
     }
     if( fid == fd_fungicidal_gas ) {
         return !type->in_species( species_FUNGUS );
     }
     if( fid == fd_insecticidal_gas ) {
         return !made_of( material_iflesh ) || has_flag( mon_flag_INSECTICIDEPROOF );
     }
     if( fid == fd_web ) {
         return has_flag( mon_flag_WEBWALK );
     }
     if( fid == fd_sludge || fid == fd_sap ) {
         return flies();
     }
     const field_type &ft = fid.obj();
     if( ft.has_fume ) {
         return has_flag( mon_flag_NO_BREATHE );
     }
     if( ft.has_acid ) {
         return has_flag( mon_flag_ACIDPROOF ) || flies();
     }
     if( ft.has_fire ) {
         return has_flag( mon_flag_FIREPROOF );
     }
     if( ft.has_elec ) {
         return has_flag( mon_flag_ELECTRIC );
     }
     if( ft.immune_mtypes.count( type->id ) > 0 ) {
         return true;
     }
     // No specific immunity was found, so fall upwards
     return Creature::is_immune_field( fid );
 }
References fd_fungal_haze, fd_fungicidal_gas, fd_insecticidal_gas, fd_sap, fd_sludge, fd_web, flies(), field_type::has_acid, field_type::has_elec, field_type::has_fire, has_flag(), field_type::has_fume, mtype::id, field_type::immune_mtypes, mtype::in_species(), Creature::is_immune_field(), made_of(), material_iflesh, mon_flag_ACIDPROOF, mon_flag_ELECTRIC, mon_flag_FIREPROOF, mon_flag_INSECTICIDEPROOF, mon_flag_NO_BREATHE, mon_flag_WEBWALK, int_id< T >::obj(), species_FUNGUS, and type.
Referenced by know_danger_at().
is_monster()
bool monster::is_monster () const inline override virtual
Reimplemented from Creature.
Definition at line 98 of file monster.h.
{
             return true;
         }
is_nemesis()
bool monster::is_nemesis () const
Definition at line 3585 of file monster.cpp.
 {
     return has_flag( mon_flag_NEMESIS );
 }
References has_flag(), and mon_flag_NEMESIS.
Referenced by overmapbuffer::despawn_monster(), mission::on_creature_death(), and process_effects().
is_nether()
bool monster::is_nether () const override virtual
Implements Creature.
Definition at line 3475 of file monster.cpp.
 {
     return in_species( species_HORROR ) || in_species( species_NETHER ) ||
            in_species( species_nether_player_hate );
 }
References in_species(), species_HORROR, species_NETHER, and species_nether_player_hate.
is_on_ground()
bool monster::is_on_ground () const override virtual
Implements Creature.
Definition at line 1753 of file monster.cpp.
 {
     // TODO: actually make this work
     return false;
 }
is_pet()
bool monster::is_pet () const
Definition at line 1324 of file monster.cpp.
 {
     return friendly == -1 && has_effect( effect_pet );
 }
References effect_pet, friendly, and Creature::has_effect().
Referenced by is_pet_follow().
is_pet_follow()
bool monster::is_pet_follow () const
Definition at line 1329 of file monster.cpp.
 {
     return is_pet() && !has_flag( mon_flag_PET_WONT_FOLLOW );
 }
References has_flag(), is_pet(), and mon_flag_PET_WONT_FOLLOW.
Referenced by move(), and plan().
is_symbol_highlighted()
bool monster::is_symbol_highlighted () const override virtual
Reimplemented from Creature.
Definition at line 1163 of file monster.cpp.
 {
     return friendly != 0;
 }
References friendly.
is_underwater()
bool monster::is_underwater () const override virtual
Reimplemented from Creature.
Definition at line 1748 of file monster.cpp.
 {
     return underwater && can_submerge();
 }
References can_submerge(), and Creature::underwater.
is_wandering()
bool monster::is_wandering () const
Definition at line 1394 of file monster.cpp.
 {
     return !has_dest() && patrol_route.empty();
 }
References has_dest(), and patrol_route.
Referenced by move().
is_warm()
bool monster::is_warm () const override virtual
Reimplemented from Creature.
Definition at line 1765 of file monster.cpp.
 {
     return has_flag( mon_flag_WARM );
 }
References has_flag(), and mon_flag_WARM.
Referenced by make_mon_corpse().
knock_back_to()
void monster::knock_back_to (const tripoint & to) override virtual
Implements Creature.
Definition at line 2280 of file monmove.cpp.
 {
     if( to == pos() ) {
         return; // No effect
     }
     if( is_hallucination() ) {
         die( nullptr );
         return;
     }
     bool u_see = get_player_view().sees( to );
     creature_tracker &creatures = get_creature_tracker();
     // First, see if we hit another monster
     if( monster *const z = creatures.creature_at<monster>( to ) ) {
         apply_damage( z, bodypart_id( "torso" ), static_cast<float>( z->type->size ) );
         add_effect( effect_stunned, 1_turns );
         if( type->size > 1 + z->type->size ) {
             z->knock_back_from( pos() ); // Chain reaction!
             z->apply_damage( this, bodypart_id( "torso" ), static_cast<float>( type->size ) );
             z->add_effect( effect_stunned, 1_turns );
         } else if( type->size > z->type->size ) {
             z->apply_damage( this, bodypart_id( "torso" ), static_cast<float>( type->size ) );
             z->add_effect( effect_stunned, 1_turns );
         }
         z->check_dead_state();
         if( u_see ) {
             add_msg( _( "The %1$s bounces off a %2$s!" ), name(), z->name() );
         }
         return;
     }
     if( npc *const p = creatures.creature_at<npc>( to ) ) {
         apply_damage( p, bodypart_id( "torso" ), 3 );
         add_effect( effect_stunned, 1_turns );
         p->deal_damage( this, bodypart_id( "torso" ),
                         damage_instance( STATIC( damage_type_id( "bash" ) ), static_cast<float>( type->size ) ) );
         if( u_see ) {
             add_msg( _( "The %1$s bounces off %2$s!" ), name(), p->get_name() );
         }
         p->check_dead_state();
         return;
     }
     // If we're still in the function at this point, we're actually moving a tile!
     // die_if_drowning will kill the monster if necessary, but if the deep water
     // tile is on a vehicle, we should check for swimmers out of water
     if( !die_if_drowning( to ) && has_flag( mon_flag_AQUATIC ) ) {
         die( nullptr );
         if( u_see ) {
             add_msg( _( "The %s flops around and dies!" ), name() );
         }
     }
     map &here = get_map();
     // It's some kind of wall.
     if( here.impassable( to ) ) {
         const int dam = static_cast<int>( type->size );
         apply_damage( nullptr, bodypart_id( "torso" ), dam );
         add_effect( effect_stunned, 2_turns );
         if( u_see ) {
             add_msg( _( "The %1$s bounces off a %2$s and takes %3$d damage." ), name(),
                      here.obstacle_name( to ), dam );
         }
     } else { // It's no wall
         setpos( to );
     }
     check_dead_state();
 }
References _, Creature::add_effect(), add_msg(), apply_damage(), Creature::check_dead_state(), creature_tracker::creature_at(), die(), die_if_drowning(), effect_stunned, get_creature_tracker(), get_map(), get_player_view(), has_flag(), map::impassable(), is_hallucination(), mon_flag_AQUATIC, name(), map::obstacle_name(), Creature::pos(), viewer::sees(), Creature::setpos(), mtype::size, STATIC, and type.
know_danger_at()
bool monster::know_danger_at (const tripoint & p) const
Definition at line 237 of file monmove.cpp.
 {
     map &here = get_map();
     // Various avoiding behaviors.
     bool avoid_fire = has_flag( mon_flag_PATH_AVOID_FIRE );
     bool avoid_fall = has_flag( mon_flag_PATH_AVOID_FALL );
     bool avoid_simple = has_flag( mon_flag_PATH_AVOID_DANGER_1 );
     bool avoid_complex = has_flag( mon_flag_PATH_AVOID_DANGER_2 );
     bool avoid_sharp = get_pathfinding_settings().avoid_sharp;
     bool avoid_traps = get_pathfinding_settings().avoid_traps;
     /*
      * Because some avoidance behaviors are supersets of others,
      * we can cascade through the implications. Complex implies simple,
      * and simple implies fire and fall.
      * unfortunately, fall does not necessarily imply fire, nor the converse.
      */
     if( avoid_complex ) {
         avoid_simple = true;
         avoid_traps = true;
     }
     if( avoid_simple ) {
         avoid_fire = true;
         avoid_fall = true;
         avoid_sharp = true;
     }
     // technically this will shortcut in evaluation from fire or fall
     // before hitting simple or complex but this is more explicit
     if( avoid_fire || avoid_fall || avoid_simple ||
         avoid_complex || avoid_traps || avoid_sharp ) {
         const ter_id target = here.ter( p );
         if( !here.has_vehicle_floor( p ) ) {
             // Don't enter lava if we have any concept of heat being bad
             if( avoid_fire && target == ter_t_lava ) {
                 return false;
             }
             if( avoid_fall ) {
                 // Don't throw ourselves off cliffs if we have a concept of falling
                 if( !here.has_floor_or_water( p ) && !flies() ) {
                     return false;
                 }
                 // Don't enter open pits ever unless tiny, can fly or climb well
                 if( !( type->size == creature_size::tiny || can_climb() ) &&
                     ( target == ter_t_pit || target == ter_t_pit_spiked || target == ter_t_pit_glass ) ) {
                     return false;
                 }
             }
             // Some things are only avoided if we're not attacking
             if( get_player_character().get_location() != get_dest() ||
                 attitude( &get_player_character() ) != MATT_ATTACK ) {
                 // Sharp terrain is ignored while attacking
                 if( avoid_sharp && here.has_flag( ter_furn_flag::TFLAG_SHARP, p ) &&
                     !( type->size == creature_size::tiny || flies() ||
                        get_armor_type( damage_cut, bodypart_id( "torso" ) ) >= 10 ) ) {
                     return false;
                 }
             }
             // Don't step on any traps (if we can see)
             const trap &target_trap = here.tr_at( p );
             if( avoid_traps && has_flag( mon_flag_SEES ) &&
                 !target_trap.is_benign() && here.has_floor_or_water( p ) ) {
                 return false;
             }
         }
         const field &target_field = here.field_at( p );
         // Higher awareness is needed for identifying these as threats.
         if( avoid_complex ) {
             // Don't enter any dangerous fields
             if( is_dangerous_fields( target_field ) ) {
                 return false;
             }
         }
         // Without avoid_complex, only fire and electricity are checked for field avoidance.
         if( avoid_fire && target_field.find_field( fd_fire ) && !is_immune_field( fd_fire ) ) {
             return false;
         }
         if( avoid_simple && target_field.find_field( fd_electricity ) &&
             !is_immune_field( fd_electricity ) ) {
             return false;
         }
     }
     return true;
 }
References attitude(), pathfinding_settings::avoid_sharp, pathfinding_settings::avoid_traps, can_climb(), damage_cut, fd_electricity, fd_fire, map::field_at(), field::find_field(), flies(), get_armor_type(), get_dest(), Creature::get_location(), get_map(), get_pathfinding_settings(), get_player_character(), has_flag(), map::has_flag(), map::has_floor_or_water(), map::has_vehicle_floor(), trap::is_benign(), Creature::is_dangerous_fields(), is_immune_field(), MATT_ATTACK, mon_flag_PATH_AVOID_DANGER_1, mon_flag_PATH_AVOID_DANGER_2, mon_flag_PATH_AVOID_FALL, mon_flag_PATH_AVOID_FIRE, mon_flag_SEES, mtype::size, map::ter(), ter_t_lava, ter_t_pit, ter_t_pit_glass, ter_t_pit_spiked, TFLAG_SHARP, tiny, map::tr_at(), and type.
Referenced by leap_actor::call(), and can_place_monster().
load() [1/2]
void monster::load (const JsonObject & data) protected
Definition at line 2421 of file savegame_json.cpp.
 {
     Creature::load( data );
     // TEMPORARY until 0.G
     if( !data.has_member( "location" ) ) {
         set_location( get_map().getglobal( read_legacy_creature_pos( data ) ) );
         tripoint wand;
         data.read( "wandx", wand.x );
         data.read( "wandy", wand.y );
         data.read( "wandz", wand.z );
         wander_pos = get_map().getglobal( wand );
         tripoint destination;
         data.read( "destination", destination );
         if( destination != tripoint_zero ) {
             goal = get_location() + destination;
         }
     }
     const mtype_id montype( data.get_string( "typeid", "invalid*type" ) );
     if( montype.is_valid() ) {
         type = &montype.obj();
     } else { // type is invalid (monster deleted from data - replace with something neutral)
         type = &mon_breather.obj();
         DebugLog( D_WARNING, DC_ALL ) << "mtype '" << montype.str() << "' is invalid, set to mon_breather";
     }
     data.read( "unique_name", unique_name );
     data.read( "nickname", nickname );
     data.read( "goal", goal );
     data.read( "provocative_sound", provocative_sound );
     data.read( "wandf", wandf );
     data.read( "wander_pos", wander_pos );
     if( data.has_int( "next_patrol_point" ) ) {
         data.read( "next_patrol_point", next_patrol_point );
         data.read( "patrol_route", patrol_route );
     }
     if( data.has_object( "tied_item" ) ) {
         JsonValue tied_item_json = data.get_member( "tied_item" );
         item newitem;
         newitem.deserialize( tied_item_json );
         tied_item = cata::make_value<item>( newitem );
     }
     if( data.has_object( "tack_item" ) ) {
         JsonValue tack_item_json = data.get_member( "tack_item" );
         item newitem;
         newitem.deserialize( tack_item_json );
         tack_item = cata::make_value<item>( newitem );
     }
     if( data.has_object( "armor_item" ) ) {
         JsonValue armor_item_json = data.get_member( "armor_item" );
         item newitem;
         newitem.deserialize( armor_item_json );
         armor_item = cata::make_value<item>( newitem );
     }
     if( data.has_object( "storage_item" ) ) {
         JsonValue storage_item_json = data.get_member( "storage_item" );
         item newitem;
         newitem.deserialize( storage_item_json );
         storage_item = cata::make_value<item>( newitem );
     }
     if( data.has_object( "battery_item" ) ) {
         JsonValue battery_item_json = data.get_member( "battery_item" );
         item newitem;
         newitem.deserialize( battery_item_json );
         battery_item = cata::make_value<item>( newitem );
     }
     data.read( "hp", hp );
     // sp_timeout indicates an old save, prior to the special_attacks refactor
     if( data.has_array( "sp_timeout" ) ) {
         JsonArray parray = data.get_array( "sp_timeout" );
         size_t index = 0;
         int ptimeout = 0;
         while( parray.has_more() && index < type->special_attacks_names.size() ) {
             if( parray.read_next( ptimeout ) ) {
                 // assume timeouts saved in same order as current monsters.json listing
                 const std::string &aname = type->special_attacks_names[index++];
                 auto &entry = special_attacks[aname];
                 if( ptimeout >= 0 ) {
                     entry.cooldown = ptimeout;
                 } else { // -1 means disabled, unclear what <-1 values mean in old saves
                     entry.cooldown = type->special_attacks.at( aname )->cooldown;
                     entry.enabled = false;
                 }
             }
         }
     }
     // special_attacks indicates a save after the special_attacks refactor
     if( data.has_object( "special_attacks" ) ) {
         for( const JsonMember member : data.get_object( "special_attacks" ) ) {
             JsonObject saobject = member.get_object();
             saobject.allow_omitted_members();
             auto &entry = special_attacks[member.name()];
             entry.cooldown = saobject.get_int( "cooldown" );
             entry.enabled = saobject.get_bool( "enabled" );
         }
     }
     // make sure the loaded monster has every special attack its type says it should have
     for( const auto &sa : type->special_attacks ) {
         const std::string &aname = sa.first;
         if( special_attacks.find( aname ) == special_attacks.end() ) {
             auto &entry = special_attacks[aname];
             entry.cooldown = rng( 0, sa.second->cooldown );
         }
     }
     data.read( "friendly", friendly );
     if( data.has_member( "mission_ids" ) ) {
         data.read( "mission_ids", mission_ids );
     } else if( data.has_member( "mission_id" ) ) {
         const int mission_id = data.get_int( "mission_id" );
         if( mission_id > 0 ) {
             mission_ids = { mission_id };
         } else {
             mission_ids.clear();
         }
     }
     data.read( "mission_fused", mission_fused );
     data.read( "no_extra_death_drops", no_extra_death_drops );
     data.read( "dead", dead );
     data.read( "anger", anger );
     data.read( "morale", morale );
     data.read( "hallucination", hallucination );
     data.read( "aggro_character", aggro_character );
     data.read( "fish_population", fish_population );
     //for older saves convert summon time limit to lifespan end
     std::optional<time_duration> summon_time_limit;
     data.read( "summon_time_limit", summon_time_limit );
     if( summon_time_limit ) {
         set_summon_time( *summon_time_limit );
     }
     upgrades = data.get_bool( "upgrades", type->upgrades );
     upgrade_time = data.get_int( "upgrade_time", -1 );
     reproduces = data.get_bool( "reproduces", type->reproduces );
     baby_timer.reset();
     data.read( "baby_timer", baby_timer );
     if( baby_timer && *baby_timer == calendar::before_time_starts ) {
         baby_timer.reset();
     }
     biosignatures = data.get_bool( "biosignatures", type->biosignatures );
     biosig_timer = time_point( data.get_int( "biosig_timer", -1 ) );
     data.read( "udder_timer", udder_timer );
     horde_attraction = static_cast<monster_horde_attraction>( data.get_int( "horde_attraction", 0 ) );
     data.read( "inv", inv );
     data.read( "dissectable_inv", dissectable_inv );
     data.read( "dragged_foe_id", dragged_foe_id );
     data.read( "ammo", ammo );
     const mfaction_str_id mfac( data.get_string( "faction", "invalid*faction" ) );
     if( mfac.is_valid() ) {
         faction = mfac;
     } else {
         faction = monfaction_factionless;
         DebugLog( D_WARNING, DC_ALL ) << "mfaction " << mfac.str() << "' is invalid, set to factionless";
     }
     data.read( "mounted_player_id", mounted_player_id );
     data.read( "path", path );
     data.read( "grabbed_limbs", grabbed_limbs );
 }
References JsonObject::allow_omitted_members(), calendar::before_time_starts, D_WARNING, item_pocket::data, DC_ALL, DebugLog(), item::deserialize(), friendly, JsonObject::get_bool(), JsonObject::get_int(), get_map(), map::getglobal(), JsonArray::has_more(), hp, string_id< T >::is_valid(), Creature::load(), member, mon_breather, monfaction_factionless, spell_effect::morale(), string_id< T >::obj(), read_legacy_creature_pos(), JsonArray::read_next(), rng(), calendar::set_location(), string_id< T >::str(), tripoint_zero, type, tripoint::x, tripoint::y, and tripoint::z.
load() [2/2]
void monster::load (const JsonObject & data, const tripoint_abs_sm & submap_loc) protected
Definition at line 2401 of file savegame_json.cpp.
 {
     load( data );
     if( !data.has_member( "location" ) ) {
         // When loading an older save in which the monster's absolute location is not serialized
         // and the monster is not in the current map, the submap location inferred by load()
         // will be wrong. Use the supplied argument to fix it.
         const tripoint_abs_ms old_loc = get_location();
         point_abs_sm wrong_submap;
         tripoint_sm_ms_ib local_pos;
         std::tie( wrong_submap, local_pos ) = project_remain<coords::sm>( get_location() );
         set_location( project_combine( submap_loc.xy(), local_pos ) );
         // adjust other relative coordinates that would be subject to the same error
         wander_pos = wander_pos - old_loc + get_location();
         if( goal ) {
             *goal = *goal - old_loc + get_location();
         }
     }
 }
References item_pocket::data, ammo_effects::load(), coords::project_combine(), calendar::set_location(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
made_of() [1/2]
bool monster::made_of (const material_id & m) const override virtual
Implements Creature.
Definition at line 1304 of file monster.cpp.
 {
     return type->made_of( m );
 }
References mtype::made_of(), and type.
Referenced by iuse::extinguisher(), mattack::formblob(), is_immune_damage(), is_immune_effect(), is_immune_field(), trapfunc::lava(), make_fungus(), Character::melee_attack_abstract(), map::monster_in_field(), name_with_armor(), on_load(), and process_one_effect().
made_of() [2/2]
bool monster::made_of (phase_id p) const
Definition at line 1319 of file monster.cpp.
 {
     return type->phase == p;
 }
References mtype::phase, and type.
made_of_any()
bool monster::made_of_any (const std::set< material_id > & ms) const override virtual
Implements Creature.
Definition at line 1309 of file monster.cpp.
 {
     return type->made_of_any( ms );
 }
References mtype::made_of_any(), coords::ms, and type.
Referenced by is_immune_effect(), trapfunc::lava(), and map::monster_in_field().
make_ally()
void monster::make_ally (const monster & z)
Makes this monster an ally of the given monster.
Definition at line 3449 of file monster.cpp.
 {
     friendly = z.friendly;
     faction = z.faction;
 }
References faction, and friendly.
Referenced by blobify(), fungal_effects::fungalize(), magical_polymorph(), mattack::resurrect(), and mattack::split().
make_bleed()
void monster::make_bleed (const effect_source & source, time_duration duration, int intensity = 1, bool permanent = false, bool force = false, bool defferred = false)
Definition at line 1849 of file monster.cpp.
 {
     if( type->bleed_rate == 0 ) {
         return;
     }
     duration = ( duration * type->bleed_rate ) / 100;
     if( type->in_species( species_ROBOT ) ) {
         add_effect( source, effect_dripping_mechanical_fluid, duration, bodypart_str_id::NULL_ID() );
     } else {
         add_effect( source, effect_bleed, duration, bodypart_str_id::NULL_ID(), permanent, intensity, force,
                     defferred );
     }
 }
References Creature::add_effect(), mtype::bleed_rate, effect_bleed, effect_dripping_mechanical_fluid, force, mtype::in_species(), intensity, string_id< body_part_type >::NULL_ID(), permanent, species_ROBOT, and type.
Referenced by deal_damage_handle_type().
make_friendly()
void monster::make_friendly ()
Definition at line 3443 of file monster.cpp.
 {
     unset_dest();
     friendly = rng( 5, 30 ) + rng( 0, 20 );
 }
References friendly, rng(), and unset_dest().
Referenced by explosion_handler::emp_blast(), and explosion_handler::scrambler_blast().
make_fungus()
bool monster::make_fungus ()
Makes this monster into a fungus version Returns false if no such monster exists Returns true if monster is immune or if it got fungalized.
Definition at line 3413 of file monster.cpp.
 {
     if( is_hallucination() ) {
         return true;
     }
     if( type->in_species( species_FUNGUS ) ) { // No friendly-fungalizing ;-)
         return true;
     }
     if( !made_of( material_flesh ) && !made_of( material_hflesh ) &&
         !made_of( material_veggy ) && !made_of( material_iflesh ) &&
         !made_of( material_bone ) ) {
         // No fungalizing robots or weird stuff (mi-gos are technically fungi, blobs are goo)
         return true;
     }
     if( type->has_flag( mon_flag_NO_FUNG_DMG ) ) {
         return true; // Return true when monster is immune to fungal damage.
     }
     if( type->fungalize_into.is_empty() ) {
         return false;
     }
     const std::string old_name = name();
     poly( type->fungalize_into );
     add_msg_if_player_sees( pos(), m_info, _( "The spores transform %1$s into a %2$s!" ),
                             old_name, name() );
     return true;
 }
References _, add_msg_if_player_sees(), mtype::fungalize_into, mtype::has_flag(), mtype::in_species(), string_id< T >::is_empty(), is_hallucination(), m_info, made_of(), material_bone, material_flesh, material_hflesh, material_iflesh, material_veggy, mon_flag_NO_FUNG_DMG, name(), poly(), Creature::pos(), species_FUNGUS, and type.
Referenced by fungal_effects::fungalize(), iuse::fungicide(), and map::monster_in_field().
mating_angry()
bool monster::mating_angry () const
Definition at line 501 of file monmove.cpp.
 {
     bool mating_angry = false;
     season_type season = season_of_year( calendar::turn );
     for( const std::string &elem : type->baby_flags ) {
         if( ( season == SUMMER && elem == "SUMMER" ) ||
             ( season == WINTER && elem == "WINTER" ) ||
             ( season == SPRING && elem == "SPRING" ) ||
             ( season == AUTUMN && elem == "AUTUMN" ) ) {
             mating_angry = true;
             break;
         }
     }
     return mating_angry;
 }
References AUTUMN, mtype::baby_flags, season, season_of_year(), SPRING, SUMMER, calendar::turn, type, and WINTER.
Referenced by anger_mating_season().
mech_str_addition()
int monster::mech_str_addition () const
Definition at line 2970 of file monster.cpp.
 {
     return type->mech_str_bonus;
 }
References mtype::mech_str_bonus, and type.
melee_attack() [1/3]
void monster::melee_attack (Creature & p, bool) delete
melee_attack() [2/3]
bool monster::melee_attack (Creature & target)
Definition at line 1898 of file monster.cpp.
 {
     return melee_attack( target, get_hit() );
 }
References Creature::get_hit().
Referenced by attack_at().
melee_attack() [3/3]
bool monster::melee_attack (Creature & target, float accuracy)
Definition at line 1903 of file monster.cpp.
 {
     // Note: currently this method must consume move even if attack hasn't actually happen
     // otherwise infinite loop will happen
     mod_moves( -type->attack_cost );
     if( /*This happens sometimes*/ this == &target || !is_adjacent( &target, true ) ) {
         return false;
     }
     if( !sees( target ) && !target.is_hallucination() ) {
         debugmsg( "Z-Level view violation: %s tried to attack %s.", disp_name(), target.disp_name() );
         return false;
     }
     const int monster_hit_roll = melee::melee_hit_range( accuracy );
     int hitspread = target.deal_melee_attack( this, monster_hit_roll );
     if( type->melee_dice == 0 ) {
         // We don't hit, so just return
         return true;
     }
     Character &player_character = get_player_character();
     if( target.is_avatar() ||
         ( target.is_npc() && player_character.attitude_to( target ) == Attitude::FRIENDLY ) ) {
         // Make us a valid target for a few turns
         add_effect( effect_hit_by_player, 3_turns );
     }
     if( has_flag( mon_flag_HIT_AND_RUN ) ) {
         add_effect( effect_run, 4_turns );
     }
     const bool u_see_me = player_character.sees( *this );
     const bool u_see_my_spot = player_character.sees( this->pos() );
     const bool u_see_target = player_character.sees( target );
     damage_instance damage = !is_hallucination() ? type->melee_damage : damage_instance();
     if( !is_hallucination() && type->melee_dice > 0 ) {
         damage.add_damage( damage_bash, dice( type->melee_dice, type->melee_sides ) );
     }
     dealt_damage_instance dealt_dam;
     if( hitspread >= 0 ) {
         target.deal_melee_hit( this, hitspread, false, damage, dealt_dam );
     }
     const int total_dealt = dealt_dam.total_damage();
     if( hitspread < 0 ) {
         bool monster_missed = monster_hit_roll < 0.0;
         // Miss
         if( u_see_my_spot && !target.in_sleep_state() ) {
             if( target.is_avatar() ) {
                 if( monster_missed ) {
                     add_msg( _( "%s misses you." ), u_see_me ? disp_name( false, true ) : _( "Something" ) );
                 } else {
                     add_msg( _( "You dodge %s." ), u_see_me ? disp_name() : _( "something" ) );
                 }
             } else if( target.is_npc() ) {
                 if( monster_missed ) {
                     add_msg( _( "%1$s misses %2$s!" ),
                              u_see_me ? disp_name( false, true ) : _( "Something" ), target.disp_name() );
                 } else {
                     add_msg( _( "%1$s dodges %2$s attack." ),
                              target.disp_name(), u_see_me ? name() : _( "something" ) );
                 }
             }
         } else if( target.is_avatar() ) {
             add_msg( _( "You dodge an attack from an unseen source." ) );
         }
     } else if( is_hallucination() || total_dealt > 0 ) {
         // Hallucinations always produce messages but never actually deal damage
         if( u_see_my_spot ) {
             if( target.is_avatar() ) {
                 sfx::play_variant_sound( "melee_attack", "monster_melee_hit",
                                          sfx::get_heard_volume( target.pos() ) );
                 // don't make a pain yelp if our limb is a bionic
                 if( !dealt_dam.bp_hit->has_flag( json_flag_BIONIC_LIMB ) ) {
                     sfx::do_player_death_hurt( dynamic_cast<Character &>( target ), false );
                 }
                 //~ 1$s is attacker name, 2$s is bodypart name in accusative.
                 add_msg( m_bad, _( "%1$s hits your %2$s." ), u_see_me ? disp_name( false, true ) : _( "Something" ),
                          body_part_name_accusative( dealt_dam.bp_hit ) );
             } else if( target.is_npc() ) {
                 if( has_effect( effect_ridden ) && has_flag( mon_flag_RIDEABLE_MECH ) &&
                     pos() == player_character.pos() ) {
                     //~ %1$s: name of your mount, %2$s: target NPC name, %3$d: damage value
                     add_msg( m_good, _( "Your %1$s hits %2$s for %3$d damage!" ), name(), target.disp_name(),
                              total_dealt );
                 } else {
                     //~ %1$s: attacker name, %2$s: target NPC name, %3$s: bodypart name in accusative
                     add_msg( _( "%1$s hits %2$s %3$s." ), u_see_me ? disp_name( false, true ) : _( "Something" ),
                              target.disp_name( true ),
                              body_part_name_accusative( dealt_dam.bp_hit ) );
                 }
             } else {
                 if( has_effect( effect_ridden ) && has_flag( mon_flag_RIDEABLE_MECH ) &&
                     pos() == player_character.pos() ) {
                     //~ %1$s: name of your mount, %2$s: target creature name, %3$d: damage value
                     add_msg( m_good, _( "Your %1$s hits %2$s for %3$d damage!" ), get_name(), target.disp_name(),
                              total_dealt );
                 }
                 if( get_option<bool>( "LOG_MONSTER_ATTACK_MONSTER" ) ) {
                     if( !u_see_me && u_see_target ) {
                         add_msg( _( "Something hits the %1$s!" ), target.disp_name() );
                     } else if( !u_see_target ) {
                         add_msg( _( "The %1$s hits something!" ), name() );
                     } else {
                         //~ %1$s: attacker name, %2$s: target creature name
                         add_msg( _( "The %1$s hits %2$s!" ), name(), target.disp_name() );
                     }
                 }
             }
         } else if( target.is_avatar() ) {
             //~ %s is bodypart name in accusative.
             add_msg( m_bad, _( "Something hits your %s." ),
                      body_part_name_accusative( dealt_dam.bp_hit ) );
         }
     } else {
         // No damage dealt
         if( u_see_my_spot ) {
             if( target.is_avatar() ) {
                 //~ 1$s is attacker name, 2$s is bodypart name in accusative, 3$s is armor name
                 add_msg( _( "%1$s hits your %2$s, but your %3$s protects you." ), u_see_me ? disp_name( false,
                          true ) : _( "Something" ),
                          body_part_name_accusative( dealt_dam.bp_hit ), target.skin_name() );
             } else if( target.is_npc() ) {
                 //~ $1s is monster name, %2$s is that monster target name,
                 //~ $3s is target bodypart name in accusative, $4s is the monster target name,
                 //~ 5$s is target armor name.
                 add_msg( _( "%1$s hits %2$s %3$s but is stopped by %4$s %5$s." ), u_see_me ? disp_name( false,
                          true ) : _( "Something" ),
                          target.disp_name( true ),
                          body_part_name_accusative( dealt_dam.bp_hit ),
                          target.disp_name( true ),
                          target.skin_name() );
             } else if( get_option<bool>( "LOG_MONSTER_ATTACK_MONSTER" ) ) {
                 //~ $1s is monster name, %2$s is that monster target name,
                 //~ $3s is target armor name.
                 add_msg( _( "%1$s hits %2$s but is stopped by its %3$s." ),
                          u_see_me ? disp_name( false, true ) : _( "Something" ),
                          target.disp_name(),
                          target.skin_name() );
             }
         } else if( target.is_avatar() ) {
             //~ 1$s is bodypart name in accusative, 2$s is armor name.
             add_msg( _( "Something hits your %1$s, but your %2$s protects you." ),
                      body_part_name_accusative( dealt_dam.bp_hit ), target.skin_name() );
         }
     }
     target.check_dead_state();
     if( is_hallucination() ) {
         if( one_in( 7 ) ) {
             die( nullptr );
         }
         return true;
     }
     if( total_dealt <= 0 ) {
         return true;
     }
     // Add any on damage effects
     for( const mon_effect_data &eff : type->atk_effs ) {
         if( x_in_y( eff.chance, 100 ) ) {
             const bodypart_id affected_bp = eff.affect_hit_bp ? dealt_dam.bp_hit :  eff.bp.id();
             target.add_effect( eff.id, time_duration::from_turns( rng( eff.duration.first,
                                eff.duration.second ) ), affected_bp, eff.permanent, rng( eff.intensity.first,
                                        eff.intensity.second ) );
             target.add_msg_if_player( m_mixed, eff.message, name() );
         }
     }
     const int stab_cut = dealt_dam.type_damage( damage_cut ) + dealt_dam.type_damage( damage_stab );
     if( stab_cut > 0 && has_flag( mon_flag_VENOM ) ) {
         target.add_msg_if_player( m_bad, _( "You're envenomed!" ) );
         target.add_effect( effect_poison, 3_minutes );
     }
     if( stab_cut > 0 && has_flag( mon_flag_BADVENOM ) ) {
         target.add_msg_if_player( m_bad,
                                   _( "You feel venom flood your body, wracking you with pain" ) );
         target.add_effect( effect_badpoison, 4_minutes );
     }
     if( stab_cut > 0 && has_flag( mon_flag_PARALYZEVENOM ) ) {
         target.add_msg_if_player( m_bad, _( "You feel venom enter your body!" ) );
         target.add_effect( effect_paralyzepoison, 10_minutes );
     }
     return true;
 }
References _, damage_instance::add_damage(), Creature::add_effect(), add_msg(), Creature::add_msg_if_player(), mon_effect_data::affect_hit_bp, mtype::atk_effs, mtype::attack_cost, Character::attitude_to(), body_part_name_accusative(), mon_effect_data::bp, dealt_damage_instance::bp_hit, mon_effect_data::chance, Creature::check_dead_state(), damage_bash, damage_cut, damage_stab, Creature::deal_melee_attack(), Creature::deal_melee_hit(), debugmsg, dice(), die(), Creature::disp_name(), disp_name(), sfx::do_player_death_hurt(), mon_effect_data::duration, effect_badpoison, effect_hit_by_player, effect_paralyzepoison, effect_poison, effect_ridden, effect_run, Creature::FRIENDLY, time_duration::from_turns(), sfx::get_heard_volume(), get_name(), get_player_character(), Creature::has_effect(), body_part_type::has_flag(), has_flag(), mon_effect_data::id, string_id< T >::id(), Creature::in_sleep_state(), mon_effect_data::intensity, Creature::is_adjacent(), Creature::is_avatar(), Creature::is_hallucination(), is_hallucination(), Creature::is_npc(), json_flag_BIONIC_LIMB, m_bad, m_good, m_mixed, mtype::melee_damage, mtype::melee_dice, melee::melee_hit_range(), mtype::melee_sides, mon_effect_data::message, Creature::mod_moves(), mon_flag_BADVENOM, mon_flag_HIT_AND_RUN, mon_flag_PARALYZEVENOM, mon_flag_RIDEABLE_MECH, mon_flag_VENOM, name(), one_in(), mon_effect_data::permanent, sfx::play_variant_sound(), Creature::pos(), rng(), Creature::sees(), Character::sees(), Creature::skin_name(), dealt_damage_instance::total_damage(), type, dealt_damage_instance::type_damage(), and x_in_y().
monster_move_in_vehicle()
bool monster::monster_move_in_vehicle (const tripoint & p) const
Definition at line 135 of file monmove.cpp.
 {
     map &m = get_map();
     monster critter = *this;
     const optional_vpart_position vp = m.veh_at( p );
     if( vp.has_value() ) {
         vehicle &veh = vp->vehicle();
         units::volume capacity = 0_ml;
         units::volume free_cargo = 0_ml;
         auto cargo_parts = veh.get_parts_at( p, "CARGO", part_status_flag::any );
         for( vehicle_part *&part : cargo_parts ) {
             vehicle_stack contents = veh.get_items( *part );
             if( !vp.part_with_feature( "CARGO_PASSABLE", false ) &&
                 !vp.part_with_feature( "APPLIANCE", false ) && !vp.part_with_feature( "OBSTACLE", false ) ) {
                 capacity += contents.max_volume();
                 free_cargo += contents.free_volume();
             }
         }
         if( capacity > 0_ml ) {
             // First, we'll try to squeeze in. Open-topped vehicle parts have more room to step over cargo.
             if( !veh.enclosed_at( p ) ) {
                 free_cargo *= 1.2;
             }
             if( !veh.enclosed_at( p ) && flies() ) {
                 return true; // No amount of cargo will block a flying monster if there's no roof.
             }
             const creature_size size = get_size();
             if( ( size == creature_size::tiny && free_cargo < 15625_ml ) ||
                 ( size == creature_size::small && free_cargo < 31250_ml ) ||
                 ( size == creature_size::medium && free_cargo < 62500_ml ) ||
                 ( size == creature_size::large && free_cargo < 125000_ml ) ||
                 ( size == creature_size::huge && free_cargo < 250000_ml ) ) {
                 if( ( size == creature_size::tiny && free_cargo < 11719_ml ) ||
                     ( size == creature_size::small && free_cargo < 23438_ml ) ||
                     ( size == creature_size::medium && free_cargo < 46875_ml ) ||
                     ( size == creature_size::large && free_cargo < 93750_ml ) ||
                     ( size == creature_size::huge && free_cargo < 187500_ml ) ||
                     ( get_volume() > 850000_ml && !vp.part_with_feature( "HUGE_OK", false ) ) ) {
                     return false; // Return false if there's just no room whatsoever. Anything over 850 liters will simply never fit in a vehicle part that isn't specifically made for it.
                     // I'm sorry but you can't let a kaiju ride shotgun.
                 }
                 if( type->bodytype == "snake" || type->bodytype == "blob" || type->bodytype == "fish" ||
                     has_flag( mon_flag_PLASTIC ) || has_flag( mon_flag_SMALL_HIDER ) ) {
                     return true; // Return true if we're wiggly enough to be fine with cramped space.
                 }
                 critter.add_effect( effect_cramped_space, 2_turns, true );
                 return true; // Otherwise we add the effect and return true.
             }
             if( size == creature_size::huge && !vp.part_with_feature( "AISLE", false ) &&
                 !vp.part_with_feature( "HUGE_OK", false ) ) {
                 critter.add_effect( effect_cramped_space, 2_turns, true );
                 return true; // Sufficiently gigantic creatures have trouble in stock seats, roof or no.
             }
         }
     }
     return true;
 }
References Creature::add_effect(), any, mtype::bodytype, anonymous_namespace{item_tname.cpp}::contents(), effect_cramped_space, vehicle::enclosed_at(), flies(), vehicle::get_items(), get_map(), vehicle::get_parts_at(), get_size(), get_volume(), has_flag(), huge, large, medium, mon_flag_PLASTIC, mon_flag_SMALL_HIDER, optional_vpart_position::part_with_feature(), om_direction::size, small, tiny, type, and map::veh_at().
Referenced by move_to().
move()
void monster::move ()
Definition at line 865 of file monmove.cpp.
 {
     add_msg_debug( debugmode::DF_MONMOVE, "Monster %s starting monmove::move, remaining moves %d",
                    name(), moves );
     // We decrement wandf no matter what.  We'll save our wander_to plans until
     // after we finish out set_dest plans, UNLESS they time out first.
     if( wandf > 0 ) {
         wandf--;
     }
     //Hallucinations have a chance of disappearing each turn
     if( is_hallucination() && one_in( 25 ) ) {
         die( nullptr );
         return;
     }
     map &here = get_map();
     Character &player_character = get_player_character();
     behavior::monster_oracle_t oracle( this );
     behavior::tree goals;
     goals.add( type->get_goals() );
     std::string action = goals.tick( &oracle );
     //The monster can consume objects it stands on. Check if there are any.
     //If there are. Consume them.
     // TODO: Stick this in a map and dispatch to it via the action string.
     // TODO: Create a special attacks whitelist unordered map instead of an if chain.
     std::map<std::string, mtype_special_attack>::const_iterator attack =
         type->special_attacks.find( action );
     if( attack != type->special_attacks.end() && attack->second->call( *this ) ) {
         if( special_attacks.count( action ) != 0 ) {
             reset_special( action );
         }
     }
     // record position before moving to put the player there if we're dragging
     tripoint_abs_ms drag_to = get_location();
     const bool pacified = has_effect( effect_pacified );
     // First, use the special attack, if we can!
     // The attack may change `monster::special_attacks` (e.g. by transforming
     // this into another monster type). Therefore we can not iterate over it
     // directly and instead iterate over the map from the monster type
     // (properties of monster types should never change).
     for( const auto &sp_type : type->special_attacks ) {
         const std::string &special_name = sp_type.first;
         const auto local_iter = special_attacks.find( special_name );
         if( local_iter == special_attacks.end() ) {
             continue;
         }
         mon_special_attack &local_attack_data = local_iter->second;
         if( !local_attack_data.enabled ) {
             continue;
         }
         add_msg_debug( debugmode::DF_MATTACK, "%s attempting a special attack %s, cooldown %d", name(),
                        sp_type.first, local_attack_data.cooldown );
         // Cooldowns are decremented in monster::process_turn
         if( local_attack_data.cooldown == 0 && !pacified && !is_hallucination() ) {
             if( !sp_type.second->call( *this ) ) {
                 add_msg_debug( debugmode::DF_MATTACK, "Attack failed" );
                 continue;
             }
             // `special_attacks` might have changed at this point. Sadly `reset_special`
             // doesn't check the attack name, so we need to do it here.
             if( special_attacks.count( special_name ) == 0 ) {
                 continue;
             }
             reset_special( special_name );
         }
     }
     // Check if they're dragging a foe and find their hapless victim
     Character *dragged_foe = find_dragged_foe();
     // Give nursebots a chance to do surgery.
     nursebot_operate( dragged_foe );
     // The monster can sometimes hang in air due to last fall being blocked
     if( !flies() && !here.has_floor_or_water( pos() ) && !here.has_vehicle_floor( pos_bub() ) ) {
         here.creature_on_trap( *this, false );
         if( is_dead() ) {
             return;
         }
     }
     // if the monster is in a deep water tile, it has a chance to drown
     if( die_if_drowning( pos(), 10 ) ) {
         return;
     }
     if( moves < 0 ) {
         return;
     }
     // TODO: Move this to attack_at/move_to/etc. functions
     bool attacking = false;
     if( !move_effects( attacking ) ) {
         moves = 0;
         return;
     }
     if( has_flag( mon_flag_IMMOBILE ) || has_flag( mon_flag_RIDEABLE_MECH ) ) {
         moves = 0;
         return;
     }
     if( has_effect( effect_stunned ) || has_effect( effect_psi_stunned ) ) {
         stumble();
         moves = 0;
         return;
     }
     if( friendly > 0 ) {
         --friendly;
     }
     const optional_vpart_position ovp = here.veh_at( pos() );
     if( has_effect( effect_harnessed ) ) {
         if( !ovp.part_with_feature( "ANIMAL_CTRL", true ) ) {
             remove_effect( effect_harnessed ); // the harness part probably broke
         } else {
             moves = 0;
             return; // don't move if harnessed
         }
     }
     const std::optional<vpart_reference> vp_boardable = ovp.part_with_feature( "BOARDABLE", true );
     if( vp_boardable && friendly != 0 ) {
         const vehicle &veh = vp_boardable->vehicle();
         if( veh.is_moving() && veh.get_monster( vp_boardable->part_index() ) ) {
             moves = 0;
             return; // don't move if friendly and passenger in a moving vehicle
         }
     }
     // Set attitude to attitude to our current target
     monster_attitude current_attitude = attitude( nullptr );
     if( !is_wandering() ) {
         if( get_dest() == player_character.get_location() ) {
             current_attitude = attitude( &player_character );
         } else {
             for( const npc &guy : g->all_npcs() ) {
                 if( get_dest() == guy.get_location() ) {
                     current_attitude = attitude( &guy );
                 }
             }
         }
     }
     if( is_pet_follow() || ( friendly != 0 && has_effect( effect_led_by_leash ) ) ) {
         const int dist = rl_dist( get_location(), get_dest() );
         if( ( dist <= 1 || ( dist <= 2 && !has_effect( effect_led_by_leash ) &&
                              sees( player_character ) ) ) &&
             ( get_dest() == player_character.get_location() &&
               get_location().z() == player_character.get_location().z() ) ) {
             moves = 0;
             stumble();
             return;
         }
     } else if( ( current_attitude == MATT_IGNORE && patrol_route.empty() ) ||
                ( ( current_attitude == MATT_FOLLOW ||
                    ( has_flag( mon_flag_KEEP_DISTANCE ) && !( current_attitude == MATT_FLEE ) ) )
                  && rl_dist( get_location(), get_dest() ) <= type->tracking_distance ) ) {
         moves = 0;
         stumble();
         return;
     }
     bool moved = false;
     tripoint destination;
     bool try_to_move = false;
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &dest : here.points_in_radius( pos(), 1 ) ) {
         if( dest != pos() ) {
             if( can_move_to( dest ) &&
                 creatures.creature_at( dest, true ) == nullptr ) {
                 try_to_move = true;
                 break;
             }
         }
     }
     // If true, don't try to greedily avoid locally bad paths
     bool pathed = false;
     tripoint local_dest = here.getlocal( get_dest() );
     if( try_to_move ) {
         // Move using vision by follow smells and sounds
         bool move_without_target = false;
         if( is_wandering() && has_intelligence() && can_see() ) {
             if( has_flag( mon_flag_SMELLS ) ) {
                 unset_dest();
                 tripoint tmp = scent_move();
                 if( tmp.x != -1 ) {
                     local_dest = tmp;
                     move_without_target = true;
                     add_msg_debug( debugmode::DF_MONMOVE, "%s follows smell using vision", name() );
                 }
             }
             if( !move_without_target && wandf > 0 && friendly == 0 ) {
                 unset_dest();
                 if( wander_pos != get_location() ) {
                     local_dest = here.getlocal( wander_pos );
                     move_without_target = true;
                     add_msg_debug( debugmode::DF_MONMOVE, "%s follows sound using vision", name() );
                 }
             }
         }
         if( !is_wandering() || move_without_target ) {
             while( !path.empty() && path.front() == pos() ) {
                 path.erase( path.begin() );
             }
             const pathfinding_settings &pf_settings = get_pathfinding_settings();
             if( pf_settings.max_dist >= rl_dist( get_location(), get_dest() ) &&
                 ( path.empty() || rl_dist( pos(), path.front() ) >= 2 || path.back() != local_dest ) ) {
                 // We need a new path
                 if( can_pathfind() ) {
                     path = here.route( pos(), local_dest, pf_settings, get_path_avoid() );
                     if( path.empty() ) {
                         increment_pathfinding_cd();
                     }
                 } else {
                     path = here.straight_route( pos(), local_dest );
                     if( !path.empty() ) {
                         std::unordered_set<tripoint> closed = get_path_avoid();
                         if( std::any_of( path.begin(), path.end(), [&closed]( const tripoint & p ) {
                         return closed.count( p );
                         } ) ) {
                             path.clear();
                         }
                     }
                 }
                 if( !path.empty() ) {
                     reset_pathfinding_cd();
                 }
             }
             // Try to respect old paths, even if we can't pathfind at the moment
             if( !path.empty() && path.back() == local_dest ) {
                 destination = path.front();
                 moved = true;
                 pathed = true;
             } else {
                 // Straight line forward, probably because we can't pathfind (well enough)
                 destination = local_dest;
                 moved = true;
             }
         }
     }
     if( !moved && has_flag( mon_flag_SMELLS ) ) {
         // No sight... or our plans are invalid (e.g. moving through a transparent, but
         //  solid, square of terrain).  Fall back to smell if we have it.
         unset_dest();
         tripoint tmp = scent_move();
         if( tmp.x != -1 ) {
             destination = tmp;
             moved = true;
             add_msg_debug( debugmode::DF_MONMOVE, "%s follows smell to not use vision", name() );
         }
     }
     if( wandf > 0 && !moved && friendly == 0 ) { // No LOS, no scent, so as a fall-back follow sound
         unset_dest();
         if( wander_pos != get_location() ) {
             destination = here.getlocal( wander_pos );
             moved = true;
             add_msg_debug( debugmode::DF_MONMOVE, "%s follows sound to not use vision", name() );
         }
     }
     point new_d( destination.xy() - pos().xy() );
     // toggle facing direction for sdl flip
     if( !g->is_tileset_isometric() ) {
         if( new_d.x < 0 ) {
             facing = FacingDirection::LEFT;
         } else if( new_d.x > 0 ) {
             facing = FacingDirection::RIGHT;
         }
     } else {
         if( new_d.y <= 0 && new_d.x <= 0 ) {
             facing = FacingDirection::LEFT;
         }
         if( new_d.x >= 0 && new_d.y >= 0 ) {
             facing = FacingDirection::RIGHT;
         }
     }
     tripoint_abs_ms next_step;
     const bool can_open_doors = has_flag( mon_flag_CAN_OPEN_DOORS ) && !is_hallucination();
     const bool staggers = has_flag( mon_flag_STUMBLES );
     if( moved ) {
         // Implement both avoiding obstacles and staggering.
         moved = false;
         float switch_chance = 0.0f;
         const bool can_bash = bash_skill() > 0;
         // This is a float and using trig_dist() because that Does the Right Thing(tm)
         // in both circular and roguelike distance modes.
         const float distance_to_target = trig_dist( pos(), destination );
         for( tripoint &candidate : squares_closer_to( pos(), destination ) ) {
             // rare scenario when monster is on the border of the map and it's goal is outside of the map
             if( !here.inbounds( candidate ) ) {
                 continue;
             }
             bool via_ramp = false;
             int rampPos = 0;
             if( here.has_flag( ter_furn_flag::TFLAG_RAMP_UP, candidate ) ) {
                 via_ramp = true;
                 rampPos -= 1;
                 candidate.z += 1;
             } else if( here.has_flag( ter_furn_flag::TFLAG_RAMP_DOWN, candidate ) ) {
                 via_ramp = true;
                 rampPos += 1;
                 candidate.z -= 1;
             }
             const tripoint_abs_ms candidate_abs = get_map().getglobal( candidate );
             if( candidate.z != posz() ) {
                 bool can_z_move = true;
                 if( !here.valid_move( pos(), candidate, false, true, via_ramp ) ) {
                     // Can't phase through floor
                     can_z_move = false;
                 }
                 // If we're trying to go up but can't fly, check if we can climb. If we can't, then don't
                 // This prevents non-climb/fly enemies running up walls
                 if( candidate.z > posz() && !( via_ramp || flies() ) ) {
                     if( !can_climb() || !here.has_floor_or_support( candidate ) ) {
                         if( ( !here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, pos() ) ||
                               !here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, candidate ) ) ) {
                             // Can't "jump" up a whole z-level
                             can_z_move = false;
                         }
                     }
                 }
                 // Last chance - we can still do the z-level stair teleport bullshit that isn't removed yet
                 // TODO: Remove z-level stair bullshit teleport after aligning all stairs
                 if( !can_z_move &&
                     posx() / ( SEEX * 2 ) == candidate.x / ( SEEX * 2 ) &&
                     posy() / ( SEEY * 2 ) == candidate.y / ( SEEY * 2 ) ) {
                     const tripoint upper = candidate.z > posz() ? candidate : pos();
                     const tripoint lower = candidate.z > posz() ? pos() : candidate;
                     if( here.has_flag( ter_furn_flag::TFLAG_GOES_DOWN, upper ) &&
                         here.has_flag( ter_furn_flag::TFLAG_GOES_UP, lower ) ) {
                         can_z_move = true;
                     }
                 }
                 if( !can_z_move ) {
                     continue;
                 }
             }
             // A flag to allow non-stumbling critters to stumble when the most direct choice is bad.
             bool bad_choice = false;
             const Creature *target = creatures.creature_at( candidate, is_hallucination() );
             if( target != nullptr ) {
                 if( is_hallucination() != target->is_hallucination() && !target->is_avatar() ) {
                     // Hallucinations should only be capable of targeting the player or other hallucinations.
                     continue;
                 }
                 const Attitude att = attitude_to( *target );
                 if( att == Attitude::HOSTILE ) {
                     // When attacking an adjacent enemy, we're direct.
                     moved = true;
                     next_step = candidate_abs;
                     break;
                 }
                 if( att == Attitude::FRIENDLY && ( target->is_avatar() || target->is_npc() ||
                                                    target->has_flag( mon_flag_QUEEN ) ) ) {
                     // Friendly firing the player or an NPC is illegal for gameplay reasons.
                     // Monsters should instinctively avoid attacking queens that regenerate their own population.
                     continue;
                 }
                 if( !has_flag( mon_flag_ATTACKMON ) && !has_flag( mon_flag_PUSH_MON ) ) {
                     // Bail out if there's a non-hostile monster in the way and we're not pushy.
                     continue;
                 }
                 // Friendly fire and pushing are always bad choices - they take a lot of time
                 bad_choice = true;
             }
             // is there an openable door?
             if( can_open_doors &&
                 here.open_door( *this, candidate, !here.is_outside( pos() ), true ) ) {
                 moved = true;
                 next_step = candidate_abs;
                 continue;
             }
             // Try to shove vehicle out of the way
             shove_vehicle( destination, candidate );
             // Bail out if we can't move there and we can't bash.
             if( !pathed && !can_move_to( candidate ) ) {
                 if( !can_bash ) {
                     continue;
                 }
                 // Don't bash if we're just tracking a noise.
                 if( !provocative_sound && is_wandering() && destination == here.getlocal( wander_pos ) ) {
                     continue;
                 }
                 const int estimate = here.bash_rating( bash_estimate(), candidate );
                 if( estimate <= 0 ) {
                     continue;
                 }
                 if( estimate < 5 ) {
                     bad_choice = true;
                 }
             }
             const float progress = distance_to_target - trig_dist( tripoint( candidate.xy(),
                                    candidate.z + rampPos ), destination );
             // The x2 makes the first (and most direct) path twice as likely,
             // since the chance of switching is 1/1, 1/4, 1/6, 1/8
             switch_chance += progress * 2;
             // Randomly pick one of the viable squares to move to weighted by distance.
             if( progress > 0 && ( !moved || x_in_y( progress, switch_chance ) ) ) {
                 moved = true;
                 next_step = candidate_abs;
                 // If we stumble, pick a random square, otherwise take the first one,
                 // which is the most direct path.
                 // Except if the direct path is bad, then check others
                 // Or if the path is given by pathfinder
                 if( !staggers && ( !bad_choice || pathed ) ) {
                     break;
                 }
             }
         }
     }
     // Finished logic section.  By this point, we should have chosen a square to
     //  move to (moved = true).
     if( moved ) { // Actual effects of moving to the square we've chosen
         const tripoint local_next_step = here.getlocal( next_step );
         const bool did_something =
             ( !pacified && attack_at( local_next_step ) ) ||
             ( !pacified && can_open_doors &&
               here.open_door( *this, local_next_step, !here.is_outside( pos() ) ) ) ||
             ( !pacified && bash_at( local_next_step ) ) ||
             ( !pacified && push_to( local_next_step, 0, 0 ) ) ||
             move_to( local_next_step, false, false, get_stagger_adjust( pos(), destination, local_next_step ) );
         if( !did_something ) {
             mod_moves( -get_speed() ); // If we don't do this, we'll get infinite loops.
         }
         if( has_effect( effect_dragging ) && dragged_foe != nullptr ) {
             if( !dragged_foe->has_effect( effect_grabbed ) ) {
                 dragged_foe = nullptr;
                 remove_effect( effect_dragging );
             } else if( drag_to != get_location() && creatures.creature_at( drag_to ) == nullptr ) {
                 dragged_foe->move_to( drag_to );
             }
         }
     } else {
         moves = 0;
         stumble();
         path.clear();
     }
     if( has_effect( effect_led_by_leash ) ) {
         if( rl_dist( get_location(), player_character.get_location() ) > 2 ) {
             // Either failed to keep up with the player or moved away
             remove_effect( effect_led_by_leash );
             add_msg( m_info, _( "You lose hold of a leash." ) );
         }
     }
 }
References _, action, behavior::tree::add(), add_msg(), add_msg_debug, spell_effect::attack(), attack_at(), attitude(), attitude_to(), bash_at(), bash_estimate(), map::bash_rating(), bash_skill(), can_climb(), can_move_to(), can_pathfind(), can_see(), mon_special_attack::cooldown, creature_tracker::creature_at(), map::creature_on_trap(), debugmode::DF_MATTACK, debugmode::DF_MONMOVE, die(), die_if_drowning(), effect_dragging, effect_grabbed, effect_harnessed, effect_led_by_leash, effect_pacified, effect_psi_stunned, effect_stunned, mon_special_attack::enabled, Creature::facing, find_dragged_foe(), flies(), Creature::FRIENDLY, friendly, g, get_creature_tracker(), get_dest(), mtype::get_goals(), Creature::get_location(), get_map(), vehicle::get_monster(), get_path_avoid(), get_pathfinding_settings(), get_player_character(), Creature::get_speed(), get_stagger_adjust(), map::getglobal(), map::getlocal(), Creature::has_effect(), Creature::has_flag(), has_flag(), map::has_flag(), map::has_floor_or_support(), map::has_floor_or_water(), has_intelligence(), map::has_vehicle_floor(), Creature::HOSTILE, map::inbounds(), increment_pathfinding_cd(), Creature::is_avatar(), is_dead(), Creature::is_hallucination(), is_hallucination(), vehicle::is_moving(), Creature::is_npc(), map::is_outside(), is_pet_follow(), is_wandering(), LEFT, m_info, MATT_FLEE, MATT_FOLLOW, MATT_IGNORE, pathfinding_settings::max_dist, Creature::mod_moves(), mon_flag_ATTACKMON, mon_flag_CAN_OPEN_DOORS, mon_flag_IMMOBILE, mon_flag_KEEP_DISTANCE, mon_flag_PUSH_MON, mon_flag_QUEEN, mon_flag_RIDEABLE_MECH, mon_flag_SMELLS, mon_flag_STUMBLES, move_effects(), move_to(), Creature::move_to(), Creature::moves, name(), nursebot_operate(), one_in(), map::open_door(), optional_vpart_position::part_with_feature(), path, patrol_route, map::points_in_radius(), Creature::pos(), Creature::pos_bub(), Creature::posx(), Creature::posy(), Creature::posz(), provocative_sound, push_to(), Creature::remove_effect(), reset_pathfinding_cd(), reset_special(), RIGHT, rl_dist(), map::route(), scent_move(), Creature::sees(), SEEX, SEEY, shove_vehicle(), special_attacks, mtype::special_attacks, squares_closer_to(), map::straight_route(), stumble(), TFLAG_GOES_DOWN, TFLAG_GOES_UP, TFLAG_RAMP_DOWN, TFLAG_RAMP_UP, TFLAG_SWIMMABLE, behavior::tree::tick(), mtype::tracking_distance, trig_dist(), tripoint, type, unset_dest(), map::valid_move(), map::veh_at(), vehicle::vehicle(), wander_pos, wandf, point::x, tripoint::x, x_in_y(), tripoint::xy(), point::y, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and tripoint::z.
move_effects()
bool monster::move_effects (bool attacking) override virtual
Processes effects which may prevent the monster from moving (bear traps, crushed, etc.).
Returns false if movement is stopped.
Implements Creature.
Definition at line 2205 of file monster.cpp.
 {
     // This function is relatively expensive, we want that cached
     // IMPORTANT: If adding any new effects here, make SURE to
     // add them to hardcoded_movement_impairing in effect.cpp
     if( !effect_cache[MOVEMENT_IMPAIRED] ) {
         return true;
     }
     map &here = get_map();
     bool u_see_me = get_player_view().sees( *this );
     if( has_effect( effect_tied ) ) {
         // friendly pet, will stay tied down and obey.
         if( friendly == -1 ) {
             return false;
         }
         // non-friendly monster will struggle to get free occasionally.
         // some monsters can't be tangled up with a net/bolas/lasso etc.
         bool immediate_break = type->in_species( species_FISH ) || type->in_species( species_MOLLUSK ) ||
                                type->in_species( species_ROBOT ) || type->bodytype == "snake" || type->bodytype == "blob";
         if( !immediate_break && rng( 0, 900 ) > type->melee_dice * type->melee_sides * 1.5 ) {
             if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                 add_msg( _( "The %s struggles to break free of its bonds." ), name() );
             }
         } else if( immediate_break ) {
             remove_effect( effect_tied );
             if( tied_item ) {
                 if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                     add_msg( _( "The %s easily slips out of its bonds." ), name() );
                 }
                 here.add_item_or_charges( pos(), *tied_item );
                 tied_item.reset();
             }
         } else {
             if( tied_item ) {
                 const bool broken = rng( type->melee_dice * type->melee_sides, std::min( 10000,
                                          type->melee_dice * type->melee_sides * 250 ) ) > 800;
                 if( !broken ) {
                     here.add_item_or_charges( pos(), *tied_item );
                 }
                 tied_item.reset();
                 if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                     if( broken ) {
                         add_msg( _( "The %s snaps the bindings holding it down." ), name() );
                     } else {
                         add_msg( _( "The %s breaks free of the bindings holding it down." ), name() );
                     }
                 }
             }
             remove_effect( effect_tied );
         }
         return false;
     }
     if( has_effect( effect_downed ) ) {
         if( rng( 0, 40 ) > type->melee_dice * type->melee_sides * 1.5 ) {
             if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                 add_msg( _( "The %s struggles to stand." ), name() );
             }
         } else {
             if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                 add_msg( _( "The %s climbs to its feet!" ), name() );
             }
             remove_effect( effect_downed );
         }
         return false;
     }
     if( has_effect( effect_webbed ) ) {
         if( x_in_y( type->melee_dice * type->melee_sides, 6 * get_effect_int( effect_webbed ) ) ) {
             if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                 add_msg( _( "The %s breaks free of the webs!" ), name() );
             }
             remove_effect( effect_webbed );
         }
         return false;
     }
     if( has_effect( effect_lightsnare ) ) {
         if( x_in_y( type->melee_dice * type->melee_sides, 12 ) ) {
             remove_effect( effect_lightsnare );
             if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                 add_msg( _( "The %s escapes the light snare!" ), name() );
             }
         }
         return false;
     }
     if( has_effect( effect_heavysnare ) ) {
         if( type->melee_dice * type->melee_sides >= 7 ) {
             if( x_in_y( type->melee_dice * type->melee_sides, 32 ) ) {
                 remove_effect( effect_heavysnare );
                 here.spawn_item( pos(), "rope_6" );
                 here.spawn_item( pos(), "snare_trigger" );
                 if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                     add_msg( _( "The %s escapes the heavy snare!" ), name() );
                 }
             }
         }
         return false;
     }
     if( has_effect( effect_beartrap ) ) {
         if( type->melee_dice * type->melee_sides >= 18 ) {
             if( x_in_y( type->melee_dice * type->melee_sides, 200 ) ) {
                 remove_effect( effect_beartrap );
                 if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                     add_msg( _( "The %s escapes the bear trap!" ), name() );
                 }
             }
         }
         return false;
     }
     if( has_effect( effect_crushed ) ) {
         if( x_in_y( type->melee_dice * type->melee_sides, 100 ) ) {
             remove_effect( effect_crushed );
             if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                 add_msg( _( "The %s frees itself from the rubble!" ), name() );
             }
         }
         return false;
     }
     if( has_effect( effect_worked_on ) ) {
         return false;
     }
     // If we ever get more effects that force movement on success this will need to be reworked to
     // only trigger success effects if /all/ rolls succeed
     if( has_effect( effect_in_pit ) ) {
         if( rng( 0, 40 ) > type->melee_dice * type->melee_sides ) {
             return false;
         } else {
             if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                 add_msg( _( "The %s escapes the pit!" ), name() );
             }
             remove_effect( effect_in_pit );
         }
     }
     if( has_effect_with_flag( json_flag_GRAB ) ) {
         // Pretty hacky, but monsters have no stats
         map &here = get_map();
         creature_tracker &creatures = get_creature_tracker();
         const tripoint_range<tripoint> &surrounding = here.points_in_radius( pos(), 1, 0 );
         for( const effect &grab : get_effects_with_flag( json_flag_GRAB ) ) {
             // Is our grabber around?
             monster *grabber = nullptr;
             for( const tripoint loc : surrounding ) {
                 monster *mon = creatures.creature_at<monster>( loc );
                 if( mon && mon->has_effect_with_flag( json_flag_GRAB_FILTER ) ) {
                     add_msg_debug( debugmode::DF_MATTACK, "Grabber %s found", mon->name() );
                     grabber = mon;
                     break;
                 }
             }
             if( grabber == nullptr ) {
                 remove_effect( grab.get_id() );
                 add_msg_debug( debugmode::DF_MATTACK, "Orphan grab found and removed" );
                 if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                     add_msg( _( "The %s is no longer grabbed!" ), name() );
                 }
                 continue;
             }
             int monster = type->melee_skill + type->melee_damage.total_damage();
             int grab_str = get_effect_int( grab.get_id() );
             add_msg_debug( debugmode::DF_MONSTER, "%s attempting to break grab %s, success %d in intensity %d",
                            get_name(), grab.get_id().c_str(), monster, grabber );
             if( !x_in_y( monster, grab_str ) ) {
                 return false;
             } else {
                 if( u_see_me && get_option<bool>( "LOG_MONSTER_MOVE_EFFECTS" ) ) {
                     add_msg( _( "The %s breaks free from the %s's grab!" ), name(), grabber->name() );
                 }
                 remove_effect( grab.get_id() );
             }
         }
     }
     return true;
 }
References _, map::add_item_or_charges(), add_msg(), add_msg_debug, mtype::bodytype, broken, creature_tracker::creature_at(), debugmode::DF_MATTACK, debugmode::DF_MONSTER, effect_beartrap, effect_cache, effect_crushed, effect_downed, effect_heavysnare, effect_in_pit, effect_lightsnare, effect_tied, effect_webbed, effect_worked_on, friendly, get_creature_tracker(), Creature::get_effect_int(), Creature::get_effects_with_flag(), get_map(), get_name(), get_player_view(), Creature::has_effect(), Creature::has_effect_with_flag(), mtype::in_species(), json_flag_GRAB, json_flag_GRAB_FILTER, mtype::melee_damage, mtype::melee_dice, mtype::melee_sides, mtype::melee_skill, min(), MOVEMENT_IMPAIRED, name(), map::points_in_radius(), Creature::pos(), Creature::remove_effect(), rng(), viewer::sees(), map::spawn_item(), species_FISH, species_MOLLUSK, species_ROBOT, tied_item, damage_instance::total_damage(), type, and x_in_y().
Referenced by leap_actor::call(), move(), and game::walk_move().
move_special_item_to_inv()
void monster::move_special_item_to_inv (cata::value_ptr< item > & it)
Definition at line 3572 of file monster.cpp.
 {
     if( it ) {
         add_item( *it );
         it.reset();
     }
 }
References add_item().
Referenced by die().
move_to()
bool monster::move_to (const tripoint & p, bool force = false, bool step_on_critter = false, float stagger_adjustment = 1.0)
Attempt to move to p.
If there's something blocking the movement, such as infinite move costs at the target, an existing NPC or monster, this function simply aborts and does nothing.
Parameters
p Destination of movement
force If this is set to true, the movement will happen even if there's currently something, else than a creature, blocking the destination.
step_on_critter If this is set to true, the movement will happen even if there's currently a creature blocking the destination.
stagger_adjustment is a multiplier for move cost to compensate for staggering.
Returns
true if movement successful, false otherwise
Definition at line 1852 of file monmove.cpp.
 {
     const bool on_ground = !digging() && !flies();
     const bool z_move = p.z != pos().z;
     const bool going_up = p.z > pos().z;
     tripoint destination = p;
     map &here = get_map();
     // This is stair teleportation hackery.
     // TODO: Remove this in favor of stair alignment
     if( going_up ) {
         if( here.has_flag( ter_furn_flag::TFLAG_GOES_UP, pos() ) ) {
             destination = find_closest_stair( p, ter_furn_flag::TFLAG_GOES_DOWN );
         }
     } else if( z_move ) {
         if( here.has_flag( ter_furn_flag::TFLAG_GOES_DOWN, pos() ) ) {
             destination = find_closest_stair( p, ter_furn_flag::TFLAG_GOES_UP );
         }
     }
     if( here.veh_at( p ).part_with_feature( VPFLAG_CARGO, true ) && !monster_move_in_vehicle( p ) ) {
         return false;
     }
     // Allows climbing monsters to move on terrain with movecost <= 0
     Creature *critter = get_creature_tracker().creature_at( destination, is_hallucination() );
     if( here.has_flag( ter_furn_flag::TFLAG_CLIMBABLE, destination ) ) {
         if( here.impassable( destination ) && critter == nullptr ) {
             if( flies() ) {
                 mod_moves( -get_speed() );
                 force = true;
                 if( get_option<bool>( "LOG_MONSTER_MOVEMENT" ) ) {
                     add_msg_if_player_sees( *this, _( "The %1$s flies over the %2$s." ), name(),
                                             here.has_flag_furn( ter_furn_flag::TFLAG_CLIMBABLE, p ) ? here.furnname( p ) :
                                             here.tername( p ) );
                 }
             } else if( climbs() ) {
                 mod_moves( -get_speed() * 1.5 );
                 force = true;
                 if( get_option<bool>( "LOG_MONSTER_MOVEMENT" ) ) {
                     add_msg_if_player_sees( *this, _( "The %1$s climbs over the %2$s." ), name(),
                                             here.has_flag_furn( ter_furn_flag::TFLAG_CLIMBABLE, p ) ? here.furnname( p ) :
                                             here.tername( p ) );
                 }
             }
         }
     }
     if( critter != nullptr && !step_on_critter ) {
         return false;
     }
     // Make sure that we can move there, unless force is true.
     if( !force && !can_move_to( destination ) ) {
         return false;
     }
     if( !force ) {
         // This adjustment is to make it so that monster movement speed relative to the player
         // is consistent even if the monster stumbles,
         // and the same regardless of the distance measurement mode.
         // Note: Keep this as float here or else it will cancel valid moves
         const float cost = stagger_adjustment *
                            static_cast<float>( climbs() &&
                                                here.has_flag( ter_furn_flag::TFLAG_NO_FLOOR, p ) ? calc_climb_cost( pos(),
                                                        destination ) : calc_movecost( pos(),
                                                                destination ) );
         if( cost > 0.0f ) {
             mod_moves( -static_cast<int>( std::ceil( cost ) ) );
         } else {
             return false;
         }
     }
     //Check for moving into/out of water
     bool was_water = underwater;
     bool will_be_water =
         on_ground && (
             // AQUATIC monsters always "swim under" the vehicles, while other swimming monsters are forced to surface
             has_flag( mon_flag_AQUATIC ) || ( can_submerge() && !here.veh_at( destination ) )
         ) && here.is_divable( destination );
     if( get_option<bool>( "LOG_MONSTER_MOVEMENT" ) ) {
         //Birds and other flying creatures flying over the deep water terrain
         if( was_water && flies() ) {
             if( one_in( 4 ) ) {
                 add_msg_if_player_sees( *this, m_warning, _( "A %1$s flies over the %2$s!" ),
                                         name(), here.tername( pos() ) );
             }
         } else if( was_water && !will_be_water ) {
             // Use more dramatic messages for swimming monsters
             add_msg_if_player_sees( *this, m_warning,
                                     //~ Message when a monster emerges from water
                                     //~ %1$s: monster name, %2$s: leaps/emerges, %3$s: terrain name
                                     pgettext( "monster movement", "A %1$s %2$s from the %3$s!" ),
                                     name(), swims() ||
                                     has_flag( mon_flag_AQUATIC ) ? _( "leaps" ) : _( "emerges" ), here.tername( pos() ) );
         } else if( !was_water && will_be_water ) {
             add_msg_if_player_sees( *this, m_warning, pgettext( "monster movement",
                                     //~ Message when a monster enters water
                                     //~ %1$s: monster name, %2$s: dives/sinks, %3$s: terrain name
                                     "A %1$s %2$s into the %3$s!" ),
                                     name(), swims() ||
                                     has_flag( mon_flag_AQUATIC ) ? _( "dives" ) : _( "sinks" ), here.tername( destination ) );
         }
     }
     optional_vpart_position vp_orig = here.veh_at( pos() );
     if( vp_orig ) {
         vp_orig->vehicle().invalidate_mass();
     }
     setpos( destination );
     footsteps( destination );
     underwater = will_be_water;
     optional_vpart_position vp_dest = here.veh_at( destination );
     if( vp_dest ) {
         vp_dest->vehicle().invalidate_mass();
     }
     if( is_hallucination() ) {
         //Hallucinations don't do any of the stuff after this point
         return true;
     }
     if( here.has_flag( ter_furn_flag::TFLAG_UNSTABLE, destination ) &&
         on_ground && !here.has_vehicle_floor( destination ) ) {
         add_effect( effect_bouldering, 1_turns, true );
     } else if( has_effect( effect_bouldering ) ) {
         remove_effect( effect_bouldering );
     }
     if( here.has_flag_ter_or_furn( ter_furn_flag::TFLAG_NO_SIGHT, destination ) && on_ground ) {
         add_effect( effect_no_sight, 1_turns, true );
     } else if( has_effect( effect_no_sight ) ) {
         remove_effect( effect_no_sight );
     }
     if( !here.has_vehicle_floor( destination ) ) {
         if( type->size != creature_size::tiny && on_ground ) {
             const int sharp_damage = rng( 1, 10 );
             const int rough_damage = rng( 1, 2 );
             if( here.has_flag( ter_furn_flag::TFLAG_SHARP, pos() ) && !one_in( 4 ) &&
                 get_armor_type( damage_cut, bodypart_id( "torso" ) ) < sharp_damage && get_hp() > sharp_damage ) {
                 apply_damage( nullptr, bodypart_id( "torso" ), sharp_damage );
             }
             if( here.has_flag( ter_furn_flag::TFLAG_ROUGH, pos() ) && one_in( 6 ) &&
                 get_armor_type( damage_cut, bodypart_id( "torso" ) ) < rough_damage && get_hp() > rough_damage ) {
                 apply_damage( nullptr, bodypart_id( "torso" ), rough_damage );
             }
         }
         here.creature_on_trap( *this );
         if( is_dead() ) {
             return true;
         }
     }
     if( !will_be_water && ( digs() || can_dig() ) ) {
         underwater = here.has_flag( ter_furn_flag::TFLAG_DIGGABLE, pos() );
     }
     // Digging creatures leave a trail of churned earth
     // They always leave some on their tile, and larger creatures emit some around themselves as well
     if( digging() && here.has_flag( ter_furn_flag::TFLAG_DIGGABLE, pos() ) ) {
         int factor = 0;
         switch( type->size ) {
             case creature_size::medium:
                 factor = 4;
                 break;
             case creature_size::large:
                 factor = 3;
                 break;
             case creature_size::huge:
                 factor = 2;
                 break;
             case creature_size::num_sizes:
                 debugmsg( "ERROR: Invalid Creature size class." );
                 break;
             default:
                 factor = 4;
                 break;
         }
         here.add_field( pos(), fd_churned_earth, 2 );
         for( const tripoint &dest : here.points_in_radius( pos(), 1, 0 ) ) {
             if( here.has_flag( ter_furn_flag::TFLAG_DIGGABLE, dest ) && one_in( factor ) ) {
                 here.add_field( dest, fd_churned_earth, 2 );
             }
         }
     }
     // Acid trail monsters leave... a trail of acid
     if( has_flag( mon_flag_ACIDTRAIL ) ) {
         here.add_field( pos(), fd_acid, 3 );
     }
     // Not all acid trail monsters leave as much acid. Every time this monster takes a step, there is a 1/5 chance it will drop a puddle.
     if( has_flag( mon_flag_SHORTACIDTRAIL ) ) {
         if( one_in( 5 ) ) {
             here.add_field( pos(), fd_acid, 3 );
         }
     }
     if( has_flag( mon_flag_SLUDGETRAIL ) ) {
         for( const tripoint &sludge_p : here.points_in_radius( pos(), 1 ) ) {
             const int fstr = 3 - ( std::abs( sludge_p.x - posx() ) + std::abs( sludge_p.y - posy() ) );
             if( fstr >= 2 ) {
                 here.add_field( sludge_p, fd_sludge, fstr );
             }
         }
     }
     if( has_flag( mon_flag_SMALLSLUDGETRAIL ) ) {
         if( one_in( 2 ) ) {
             here.add_field( pos(), fd_sludge, 1 );
         }
     }
     // Don't leave any kind of liquids on water tiles
     if( !here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, destination ) ) {
         if( has_flag( mon_flag_DRIPS_NAPALM ) ) {
             if( one_in( 10 ) ) {
                 // if it has more napalm, drop some and reduce ammo in tank
                 if( ammo[itype_pressurized_tank] > 0 ) {
                     here.add_item_or_charges( pos(), item( "napalm", calendar::turn, 50 ) );
                     ammo[itype_pressurized_tank] -= 50;
                 } else {
                     // TODO: remove mon_flag_DRIPS_NAPALM flag since no more napalm in tank
                     // Not possible for now since flag check is done on type, not individual monster
                 }
             }
         }
         if( has_flag( mon_flag_DRIPS_GASOLINE ) ) {
             if( one_in( 5 ) ) {
                 // TODO: use same idea that limits napalm dripping
                 here.add_item_or_charges( pos(), item( "gasoline" ) );
             }
         }
     }
     return true;
 }
References _, abs(), Creature::add_effect(), map::add_field(), map::add_item_or_charges(), add_msg_if_player_sees(), ammo, apply_damage(), calc_climb_cost(), calc_movecost(), can_dig(), can_move_to(), can_submerge(), ceil(), climbs(), creature_tracker::creature_at(), map::creature_on_trap(), damage_cut, debugmsg, digging(), digs(), effect_bouldering, effect_no_sight, fd_acid, fd_churned_earth, fd_sludge, find_closest_stair(), flies(), footsteps(), force, map::furnname(), get_armor_type(), get_creature_tracker(), get_hp(), get_map(), Creature::get_speed(), Creature::has_effect(), has_flag(), map::has_flag(), map::has_flag_furn(), map::has_flag_ter_or_furn(), map::has_vehicle_floor(), huge, map::impassable(), is_dead(), map::is_divable(), is_hallucination(), item, itype_pressurized_tank, large, m_warning, medium, Creature::mod_moves(), mon_flag_ACIDTRAIL, mon_flag_AQUATIC, mon_flag_DRIPS_GASOLINE, mon_flag_DRIPS_NAPALM, mon_flag_SHORTACIDTRAIL, mon_flag_SLUDGETRAIL, mon_flag_SMALLSLUDGETRAIL, monster_move_in_vehicle(), name(), num_sizes, one_in(), optional_vpart_position::part_with_feature(), pgettext, map::points_in_radius(), Creature::pos(), Creature::posx(), Creature::posy(), Creature::remove_effect(), rng(), Creature::setpos(), mtype::size, swims(), map::tername(), TFLAG_CLIMBABLE, TFLAG_DIGGABLE, TFLAG_GOES_DOWN, TFLAG_GOES_UP, TFLAG_NO_FLOOR, TFLAG_NO_SIGHT, TFLAG_ROUGH, TFLAG_SHARP, TFLAG_SWIMMABLE, TFLAG_UNSTABLE, tiny, calendar::turn, type, Creature::underwater, map::veh_at(), VPFLAG_CARGO, and tripoint::z.
Referenced by melee_actor::do_grab(), move(), game::place_player(), anonymous_namespace{monexamine.cpp}::push(), push_to(), and stumble().
movement_impaired()
bool monster::movement_impaired ()
Returns true if the monster has its movement impaired.
Definition at line 2200 of file monster.cpp.
 {
     return effect_cache[MOVEMENT_IMPAIRED];
 }
References effect_cache, and MOVEMENT_IMPAIRED.
Referenced by push_to().
name()
std::string monster::name (unsigned int quantity = 1) const
Definition at line 722 of file monster.cpp.
 {
     if( !type ) {
         debugmsg( "monster::name empty type!" );
         return std::string();
     }
     std::string result = type->nname( quantity );
     if( !nickname.empty() ) {
         return nickname;
     }
     if( !unique_name.empty() ) {
         //~ %1$s: monster name, %2$s: unique name
         result = string_format( pgettext( "unique monster name", "%1$s: %2$s" ),
                                 result, unique_name );
     }
     if( !mission_fused.empty() ) {
         //~ name when a monster fuses with a mission target
         result = string_format( pgettext( "fused mission monster", "*%s" ), result );
     }
     return result;
 }
References debugmsg, mission_fused, nickname, mtype::nname(), pgettext, string_format(), type, and unique_name.
Referenced by mattack::absorb_items(), mattack::absorb_meat(), mattack::acid_barf(), anger_cub_threatened(), anger_hostile_seen(), anger_mating_season(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), Character::bionics_uninstall_failure(), mattack::blow_whistle(), talker_monster_const::bodytype(), mattack::boomer(), mattack::boomer_glow(), mdeath::broken(), mattack::browse(), leap_actor::call(), melee_actor::call(), gun_actor::call(), iuse::camera(), iuse::can_goo(), game::check_safe_mode_allowed(), mattack::chickenbot(), trapfunc::cot(), trapfunc::crossbow(), mattack::dance(), mattack::darkman(), mattack::depart(), mattack::dermatik(), mattack::dermatik_growth(), die(), die_if_drowning(), game::disable_robot(), mdeath::disappear(), disp_name(), melee_actor::do_grab(), disable_activity_actor::do_turn(), mattack::dogthing(), mattack::doot(), mattack::dsa_drone_scan(), mattack::eat_carrion(), mattack::eat_crop(), mattack::eat_food(), effects_description_for_creature(), iuse::einktabletpc(), explosion_handler::emp_blast(), mattack::evolve_kill_strike(), extended_description(), iuse::extinguisher(), disable_activity_actor::finish(), mattack::flamethrower(), mattack::flesh_golem(), mattack::flesh_tendril(), game::forced_door_closing(), mattack::frag(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus(), mattack::fungus_big_blossom(), mattack::fungus_bristle(), mattack::fungus_corporate(), mattack::fungus_fortify(), mattack::fungus_growth(), mattack::fungus_haze(), mattack::fungus_inject(), talker_monster_const::get_grab_strength(), get_name(), talker_monster_const::get_size(), mattack::graze(), grenade_helper(), spell_effect::guilt(), talker_monster_const::has_flag(), has_flag(), talker_monster_const::has_species(), mattack::jackson(), mattack::kamikaze(), creature_tracker::kill_marked_for_death(), knock_back_to(), mattack::lunge(), iuse::mace(), basecamp::make_corpse_from_group(), make_fake_npc(), make_fungus(), melee_attack(), game::mon_info_update(), mattack::mon_leech_evolution(), move(), avatar_action::move(), move_effects(), move_to(), mattack::multi_robot(), mdeath::normal(), mattack::nurse_assist(), mattack::nurse_operate(), nursebot_operate(), on_hit(), on_load(), photo_def_for_camera_point(), mattack::photograph(), game::place_player(), plan(), mattack::plant(), print_info(), process_effects(), process_triggers(), process_turn(), mattack::pull_metal_weapon(), push_to(), creature_tracker::remove(), mattack::resurrect(), mattack::rifle(), mattack::science(), explosion_handler::scrambler_blast(), mattack::shocking_reveal(), gun_actor::shoot(), trapfunc::shotgun(), mattack::shriek_alert(), mattack::smash(), mattack::split(), sting_shoot(), mattack::stretch_attack(), stumble(), mattack::tankgun(), mattack::taze(), mattack::tindalos_teleport(), mattack::triffid_growth(), Character::try_remove_grab(), gun_actor::try_target(), Character::uninstall_bionic(), mattack::upgrade(), place_monster_iuse::use(), mattack::vine(), suffer::while_grabbed(), mdefense::zapback(), and mattack::zombie_fuse().
name_with_armor()
std::string monster::name_with_armor () const
Definition at line 745 of file monster.cpp.
 {
     std::string ret;
     if( made_of( material_iflesh ) ) {
         ret = _( "carapace" );
     } else if( made_of( material_veggy ) ) {
         ret = _( "thick bark" );
     } else if( made_of( material_bone ) ) {
         ret = _( "exoskeleton" );
     } else if( made_of( material_flesh ) || made_of( material_hflesh ) ) {
         ret = _( "thick hide" );
     } else if( made_of( material_iron ) || made_of( material_steel ) ) {
         ret = _( "armor plating" );
     } else if( made_of( phase_id::LIQUID ) ) {
         ret = _( "dense jelly mass" );
     } else {
         ret = _( "armor" );
     }
     if( has_effect( effect_monster_armor ) && !inv.empty() ) {
         for( const item &armor : inv ) {
             if( armor.is_pet_armor( true ) ) {
                 ret += string_format( _( "wearing %1$s" ), armor.tname( 1 ) );
                 break;
             }
         }
     }
     return ret;
 }
References _, effect_monster_armor, Creature::has_effect(), inv, LIQUID, made_of(), material_bone, material_flesh, material_hflesh, material_iflesh, material_iron, material_steel, material_veggy, cata::hash64_detail::ret, and string_format().
Referenced by skin_name().
next_upgrade_time()
int monster::next_upgrade_time () private
Normal upgrades.
Definition at line 431 of file monster.cpp.
 {
     if( type->age_grow > 0 ) {
         return type->age_grow;
     }
     const int scaled_half_life = type->half_life * get_option<float>( "MONSTER_UPGRADE_FACTOR" );
     int day = 1; // 1 day of guaranteed evolve time
     for( int i = 0; i < UPGRADE_MAX_ITERS; i++ ) {
         if( one_in( 2 ) ) {
             day += rng( 0, scaled_half_life );
             return day;
         } else {
             day += scaled_half_life;
         }
     }
     // didn't manage to upgrade, shouldn't ever then
     upgrades = false;
     return -1;
 }
References mtype::age_grow, day, mtype::half_life, one_in(), rng(), type, UPGRADE_MAX_ITERS, and upgrades.
Referenced by try_upgrade().
nursebot_operate()
void monster::nursebot_operate (Character * dragged_foe) private
Definition at line 1357 of file monmove.cpp.
 {
     // No dragged foe, nothing to do.
     if( dragged_foe == nullptr || !has_dest() ) {
         return;
     }
     // Nothing to do if they can't operate, or they don't think they're dragging.
     if( !( type->has_special_attack( "OPERATE" ) && has_effect( effect_dragging ) ) ) {
         return;
     }
     creature_tracker &creatures = get_creature_tracker();
     map &here = get_map();
     if( rl_dist( get_location(), get_dest() ) == 1 &&
         !here.has_flag_furn( ter_furn_flag::TFLAG_AUTODOC_COUCH, here.getlocal( get_dest() ) ) &&
         !has_effect( effect_operating ) ) {
         if( dragged_foe->has_effect( effect_grabbed ) && !has_effect( effect_countdown ) &&
             ( creatures.creature_at( get_dest() ) == nullptr ||
               creatures.creature_at( get_dest() ) == dragged_foe ) ) {
             add_msg( m_bad, _( "The %1$s slowly but firmly puts %2$s down onto the Autodoc couch." ), name(),
                      dragged_foe->disp_name() );
             dragged_foe->move_to( get_dest() );
             // There's still time to get away
             add_effect( effect_countdown, 2_turns );
             add_msg( m_bad, _( "The %s produces a syringe full of some translucent liquid." ), name() );
         } else if( creatures.creature_at( get_dest() ) != nullptr && has_effect( effect_dragging ) ) {
             sounds::sound( pos(), 8, sounds::sound_t::electronic_speech,
                            string_format(
                                _( "a soft robotic voice say, \"Please step away from the Autodoc, this patient needs immediate care.\"" ) ) );
             // TODO: Make it able to push NPC/player
             push_to( here.getlocal( get_dest() ), 4, 0 );
         }
     }
     if( get_effect_dur( effect_countdown ) == 1_turns && !has_effect( effect_operating ) ) {
         if( dragged_foe->has_effect( effect_grabbed ) ) {
             const bionic_collection &collec = *dragged_foe->my_bionics;
             cata_assert( !collec.empty() );
             const int index = rng( 0, collec.size() - 1 );
             const bionic *const target_cbm = &collec[index];
             const bionic &real_target =
                 target_cbm->is_included()
                 ? **dragged_foe->find_bionic_by_uid( target_cbm->get_parent_uid() )
                 : *target_cbm;
             //8 intelligence*4 + 8 first aid*4 + 3 computer *3 + 4 electronic*1 = 77
             const float adjusted_skill = static_cast<float>( 77 ) - std::min( static_cast<float>( 40 ),
                                          static_cast<float>( 77 ) - static_cast<float>( 77 ) / static_cast<float>( 10.0 ) );
             dragged_foe->cancel_activity();
             get_player_character().uninstall_bionic( real_target, *this, *dragged_foe, adjusted_skill );
             // Remove target grab
             for( const effect &eff : dragged_foe->get_effects_with_flag( json_flag_GRAB ) ) {
                 dragged_foe->remove_effect( eff.get_id() );
             }
             // And our own grab filters
             for( const effect &eff : get_effects_with_flag( json_flag_GRAB_FILTER ) ) {
                 remove_effect( eff.get_id() );
             }
             dragged_foe_id = character_id();
         }
     }
 }
References _, Creature::add_effect(), add_msg(), Character::cancel_activity(), cata_assert, character_id, creature_tracker::creature_at(), Character::disp_name(), dragged_foe_id, effect_countdown, effect_dragging, effect_grabbed, effect_operating, sounds::electronic_speech, Character::find_bionic_by_uid(), get_creature_tracker(), get_dest(), Creature::get_effect_dur(), Creature::get_effects_with_flag(), Creature::get_location(), get_map(), bionic::get_parent_uid(), get_player_character(), map::getlocal(), has_dest(), Creature::has_effect(), map::has_flag_furn(), mtype::has_special_attack(), bionic::is_included(), json_flag_GRAB, json_flag_GRAB_FILTER, m_bad, min(), Creature::move_to(), Character::my_bionics, name(), Creature::pos(), push_to(), Creature::remove_effect(), rl_dist(), rng(), sounds::sound(), string_format(), TFLAG_AUTODOC_COUCH, type, and Character::uninstall_bionic().
Referenced by move().
on_dodge()
void monster::on_dodge (Creature * source, float difficulty, float training_level = 0.0) override virtual
This creature just dodged an attack - possibly special/ranged attack - from source.
Players should train dodge, monsters may use some special defenses.
Implements Creature.
Definition at line 3674 of file monster.cpp.
 {
     // Currently does nothing, later should handle faction relations
 }
on_hit()
void monster::on_hit (Creature * source, bodypart_id bp_hit, float difficulty = INT_MIN, dealt_projectile_attack const * proj = nullptr) override virtual
This creature just got hit by an attack - possibly special/ranged attack - from source.
Players should train dodge, possibly counter-attack somehow.
Implements Creature.
Definition at line 3679 of file monster.cpp.
 {
     if( is_hallucination() ) {
         return;
     }
     if( rng( 0, 100 ) <= static_cast<int>( type->def_chance ) ) {
         type->sp_defense( *this, source, proj );
     }
     // Adjust anger/morale of nearby monsters, if they have the appropriate trigger and are friendly
     // Keep filtering on the hit monsters' triggers to preserve current functionality
     bool trigger = type->has_anger_trigger( mon_trigger::FRIEND_ATTACKED ) ||
                    type->has_fear_trigger( mon_trigger::FRIEND_ATTACKED ) ||
                    type->has_placate_trigger( mon_trigger::FRIEND_ATTACKED );
     if( trigger ) {
         int light = g->light_level( posz() );
         map &here = get_map();
         for( monster &critter : g->all_monsters() ) {
             // Do we actually care about this faction?
             if( critter.faction->attitude( faction ) != MFA_FRIENDLY ) {
                 continue;
             }
             if( here.sees( critter.pos(), pos(), light ) ) {
                 // Anger trumps fear trumps ennui
                 if( critter.type->has_anger_trigger( mon_trigger::FRIEND_ATTACKED ) ) {
                     critter.anger += 15;
                     if( source != nullptr && !source->is_monster() && !source->is_fake() ) {
                         // A character attacked our friend
                         add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro triggered by attacking a friendly %s",
                                        critter.name(), name() );
                         critter.aggro_character = true;
                     }
                 } else if( critter.type->has_fear_trigger( mon_trigger::FRIEND_ATTACKED ) ) {
                     critter.morale -= 15;
                 } else if( critter.type->has_placate_trigger( mon_trigger::FRIEND_ATTACKED ) ) {
                     critter.anger -= 15;
                 }
             }
         }
     }
     if( source != nullptr ) {
         if( Character *attacker = source->as_character() ) {
             type->families.practice_hit( *attacker );
         }
     }
     check_dead_state();
     // TODO: Faction relations
 }
References add_msg_debug, Creature::as_character(), Creature::check_dead_state(), mtype::def_chance, debugmode::DF_MONSTER, mtype::families, FRIEND_ATTACKED, g, get_map(), mtype::has_anger_trigger(), mtype::has_fear_trigger(), mtype::has_placate_trigger(), Creature::is_fake(), is_hallucination(), Creature::is_monster(), light, MFA_FRIENDLY, name(), Creature::pos(), Creature::posz(), weakpoint_families::practice_hit(), rng(), map::sees(), mtype::sp_defense, and type.
Referenced by deal_projectile_attack().
on_load()
void monster::on_load ()
Retroactively update monster.
Call this after a preexisting monster has been placed on map. Don't call for monsters that have been freshly created, it may cause the monster to upgrade itself into another monster type.
Definition at line 3858 of file monster.cpp.
 {
     try_upgrade( false );
     try_reproduce();
     try_biosignature();
     reset_digestion();
     //Clean up runaway values for monsters which eat but don't digest yet.
     if( amount_eaten > 0 ) {
         if( has_flag( mon_flag_EATS ) ) {
             digest_food();
         } else {
             amount_eaten = 0;
         }
     }
     if( has_flag( mon_flag_MILKABLE ) ) {
         refill_udders();
     }
     const time_duration dt = calendar::turn - last_updated;
     last_updated = calendar::turn;
     if( dt <= 0_turns ) {
         return;
     }
     if( morale != type->morale ) { // if works, will put into helper function
         int dt_left_m = to_turns<int>( dt );
         if( std::abs( morale - type->morale ) > 15 ) {
             const int adjust_by_m = std::min( ( dt_left_m / 4 ),
                                               ( std::abs( morale - type->morale ) - 15 ) );
             dt_left_m -= adjust_by_m * 4;
             if( morale < type->morale ) {
                 morale += adjust_by_m;
             } else {
                 morale -= adjust_by_m;
             }
         }
         // Avoiding roll_remainder - PC out of situation, monster can calm down
         if( morale < type->morale ) {
             morale += std::min( static_cast<int>( std::ceil( dt_left_m / 8.0 ) ),
                                 std::abs( morale - type->morale ) );
         } else {
             morale -= std::min( ( dt_left_m / 8 ),
                                 std::abs( morale - type->morale ) );
         }
     }
     if( anger != type->agro ) {
         int dt_left_a = to_turns<int>( dt );
         if( std::abs( anger - type->agro ) > 15 ) {
             const int adjust_by_a = std::min( ( dt_left_a / 4 ),
                                               ( std::abs( anger - type->agro ) - 15 ) );
             dt_left_a -= adjust_by_a * 4;
             if( anger < type->agro ) {
                 anger += adjust_by_a;
             } else {
                 anger -= adjust_by_a;
             }
         }
         if( anger > type->agro ) {
             anger -= std::min( static_cast<int>( std::ceil( dt_left_a / 8.0 ) ),
                                std::abs( anger - type->agro ) );
         } else {
             anger += std::min( ( dt_left_a / 8 ),
                                std::abs( anger - type->agro ) );
         }
         // If we got angry at characters have a chance at calming down
         if( aggro_character && !type->aggro_character && !x_in_y( anger, 100 ) ) {
             add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro reset", name() );
             aggro_character = false;
         }
     }
     // TODO: regen_morale
     float regen = type->regenerates;
     if( regen <= 0 ) {
         if( has_flag( mon_flag_REVIVES ) && !has_flag( mon_flag_DORMANT ) ) {
             regen = 0.02f * type->hp / to_turns<int>( 1_hours );
         } else if( made_of( material_flesh ) || made_of( material_iflesh ) ||
                    made_of( material_veggy ) ) {
             // Most living stuff here
             regen = 0.005f * type->hp / to_turns<int>( 1_hours );
         }
     }
     const int heal_amount = roll_remainder( regen * to_turns<int>( dt ) );
     const int healed = heal( heal_amount );
     int healed_speed = 0;
     if( get_speed_base() < type->speed ) {
         const int old_speed = get_speed_base();
         if( hp >= type->hp ) {
             set_speed_base( type->speed );
         } else {
             const int speed_delta = std::max( healed * type->speed / type->hp, 1 );
             set_speed_base( std::min( old_speed + speed_delta, type->speed ) );
         }
         healed_speed = get_speed_base() - old_speed;
     }
     // Update special attacks' cooldown
     for( const auto &sp_type : type->special_attacks ) {
         const std::string &special_name = sp_type.first;
         const auto local_iter = special_attacks.find( special_name );
         if( local_iter == special_attacks.end() ) {
             continue;
         }
         mon_special_attack &local_attack_data = local_iter->second;
         if( !local_attack_data.enabled ) {
             continue;
         }
         if( local_attack_data.cooldown > 0 ) {
             local_attack_data.cooldown = std::max( 0, local_attack_data.cooldown - to_turns<int>( dt ) );
         }
     }
     add_msg_debug( debugmode::DF_MONSTER, "on_load() by %s, %d turns, healed %d hp, %d speed",
                    name(), to_turns<int>( dt ), healed, healed_speed );
 }
References abs(), add_msg_debug, aggro_character, mtype::aggro_character, mtype::agro, amount_eaten, anger, ceil(), mon_special_attack::cooldown, debugmode::DF_MONSTER, digest_food(), mon_special_attack::enabled, Creature::get_speed_base(), has_flag(), heal(), hp, mtype::hp, Creature::last_updated, made_of(), material_flesh, material_iflesh, material_veggy, max(), min(), mon_flag_DORMANT, mon_flag_EATS, mon_flag_MILKABLE, mon_flag_REVIVES, morale, mtype::morale, name(), refill_udders(), mtype::regenerates, reset_digestion(), roll_remainder(), Creature::set_speed_base(), special_attacks, mtype::special_attacks, mtype::speed, try_biosignature(), try_reproduce(), try_upgrade(), calendar::turn, type, and x_in_y().
Referenced by map::spawn_monsters_submap(), and map::spawn_monsters_submap_group().
on_move()
void monster::on_move (const tripoint_abs_ms & old_pos) override protected virtual
Reimplemented from Creature.
Definition at line 357 of file monster.cpp.
 {
     Creature::on_move( old_pos );
     if( old_pos == get_location() ) {
         return;
     }
     g->update_zombie_pos( *this, old_pos, get_location() );
     if( has_effect( effect_ridden ) && mounted_player &&
         mounted_player->get_location() != get_location() ) {
         add_msg_debug( debugmode::DF_MONSTER, "Ridden monster %s moved independently and dumped player",
                        get_name() );
         mounted_player->forced_dismount();
     }
     if( has_dest() && get_location() == get_dest() ) {
         unset_dest();
     }
 }
References add_msg_debug, debugmode::DF_MONSTER, effect_ridden, g, and Creature::on_move().
on_try_dodge()
void monster::on_try_dodge () inline override virtual
Invoked when the creature attempts to dodge, regardless of success or failure.
Implements Creature.
Definition at line 435 of file monster.h.
 {}
on_unload()
void monster::on_unload ()
Do some cleanup and caching as monster is being unloaded from map.
Definition at line 3853 of file monster.cpp.
 {
     last_updated = calendar::turn;
 }
References Creature::last_updated, and calendar::turn.
Referenced by game::despawn_monster().
operator=() [1/2]
monster & monster::operator= (const monster &) default
operator=() [2/2]
monster & monster::operator= (monster &&) default noexcept
plan()
void monster::plan ()
Definition at line 517 of file monmove.cpp.
 {
     monster_plan mon_plan( *this );
     map &here = get_map();
     std::bitset<OVERMAP_LAYERS> seen_levels = here.get_inter_level_visibility( pos().z );
     monster_attitude mood = attitude();
     Character &player_character = get_player_character();
     // If we can see the player, move toward them or flee.
     if( friendly == 0 && seen_levels.test( player_character.pos().z + OVERMAP_DEPTH ) &&
         sees( player_character ) ) {
         mon_plan.dist = rate_target( player_character, mon_plan.dist, mon_plan.smart_planning );
         mon_plan.fleeing = mon_plan.fleeing || is_fleeing( player_character );
         mon_plan.target = &player_character;
         if( !mon_plan.fleeing && anger <= 20 ) {
             anger += mon_plan.angers_hostile_seen;
         }
         anger_hostile_seen( mon_plan );
         if( mon_plan.dist <= 5 ) {
             if( anger <= 30 ) {
                 anger += mon_plan.angers_hostile_near;
             }
             if( mon_plan.angers_hostile_near && x_in_y( anger, 100 ) ) {
                 add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro triggered by proximity", name() );
                 aggro_character = true;
             }
             morale -= mon_plan.fears_hostile_near;
             anger_mating_season( mon_plan );
         }
         anger_cub_threatened( mon_plan );
     } else if( friendly != 0 && !mon_plan.docile ) {
         for( monster &tmp : g->all_monsters() ) {
             if( tmp.friendly == 0 && tmp.attitude_to( *this ) == Attitude::HOSTILE &&
                 seen_levels.test( tmp.pos().z + OVERMAP_DEPTH ) ) {
                 float rating = rate_target( tmp, mon_plan.dist, mon_plan.smart_planning );
                 if( rating < mon_plan.dist ) {
                     mon_plan.target = &tmp;
                     mon_plan.dist = rating;
                 }
             }
         }
     }
     if( mon_plan.docile ) {
         if( friendly != 0 && mon_plan.target != nullptr ) {
             set_dest( mon_plan.target->get_location() );
         }
         return;
     }
     int valid_targets = ( mon_plan.target == nullptr ) ? 0 : 1;
     for( npc &who : g->all_npcs() ) {
         mf_attitude faction_att = faction.obj().attitude( who.get_monster_faction() );
         if( faction_att == MFA_NEUTRAL || faction_att == MFA_FRIENDLY ) {
             continue;
         }
         if( !seen_levels.test( who.pos().z + OVERMAP_DEPTH ) ) {
             continue;
         }
         float rating = rate_target( who, mon_plan.dist, mon_plan.smart_planning );
         bool fleeing_from = is_fleeing( who );
         if( rating == mon_plan.dist && ( mon_plan.fleeing || attitude( &who ) == MATT_ATTACK ||
                                          attitude( &who ) == MATT_FOLLOW ) ) {
             ++valid_targets;
             if( one_in( valid_targets ) ) {
                 mon_plan.target = &who;
             }
         }
         // Switch targets if closer and hostile or scarier than current target
         if( ( rating < mon_plan.dist && mon_plan.fleeing ) ||
             ( faction_att == MFA_HATE ) ||
             ( rating < mon_plan.dist && attitude( &who ) == MATT_ATTACK ) ||
             ( !mon_plan.fleeing && fleeing_from ) ) {
             mon_plan.target = &who;
             mon_plan.dist = rating;
             valid_targets = 1;
         }
         mon_plan.fleeing = mon_plan.fleeing || fleeing_from;
         if( rating <= 5 ) {
             if( anger <= 30 ) {
                 anger += mon_plan.angers_hostile_near;
             }
             if( mon_plan.angers_hostile_near && x_in_y( anger, 100 ) ) {
                 add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro triggered by proximity to %s", name(),
                                who.name );
                 aggro_character = true;
             }
             morale -= mon_plan.fears_hostile_near;
             anger_mating_season( mon_plan );
         }
         if( !mon_plan.fleeing && anger <= 20 && valid_targets != 0 ) {
             anger += mon_plan.angers_hostile_seen;
         }
         if( !mon_plan.fleeing && valid_targets != 0 ) {
             morale -= mon_plan.fears_hostile_seen;
             anger_hostile_seen( mon_plan );
         }
     }
     mon_plan.fleeing = mon_plan.fleeing || ( mood == MATT_FLEE );
     // Throttle monster thinking, if there are no apparent threats, stop paying attention.
     constexpr int max_turns_for_rate_limiting = 1800;
     constexpr double max_turns_to_skip = 600.0;
     // Outputs a range from 0.0 - 1.0.
     float rate_limiting_factor = 1.0 - logarithmic_range( 0, max_turns_for_rate_limiting,
                                  turns_since_target );
     int turns_to_skip = max_turns_to_skip * rate_limiting_factor;
     creature_tracker &tracker = get_creature_tracker();
     if( friendly == 0 && ( turns_to_skip == 0 || turns_since_target % turns_to_skip == 0 ) ) {
         tracker.for_each_reachable( *this, [this]( const mfaction_id & other ) {
             const mf_attitude faction_att = faction->attitude( other );
             return !( faction_att == MFA_NEUTRAL || faction_att == MFA_FRIENDLY );
         },
         [this, &seen_levels, &mon_plan, &valid_targets]( Creature * other ) {
             if( !seen_levels.test( other->posz() + OVERMAP_DEPTH ) ) {
                 return;
             }
             monster *mon_ptr = dynamic_cast<monster *>( other );
             if( mon_ptr == nullptr ) {
                 return;
             }
             monster &mon = *mon_ptr;
             float rating = rate_target( mon, mon_plan.dist, mon_plan.smart_planning );
             if( rating == mon_plan.dist ) {
                 ++valid_targets;
                 if( one_in( valid_targets ) ) {
                     mon_plan.target = &mon;
                 }
             }
             if( rating < mon_plan.dist ) {
                 mon_plan.target = &mon;
                 mon_plan.dist = rating;
                 valid_targets = 1;
             }
             if( rating <= 5 ) {
                 if( anger <= 30 ) {
                     anger += mon_plan.angers_hostile_near;
                 }
                 morale -= mon_plan.fears_hostile_near;
             }
             if( !mon_plan.fleeing && anger <= 20 && valid_targets != 0 ) {
                 anger += mon_plan.angers_hostile_seen;
             }
             if( !mon_plan.fleeing && valid_targets != 0 ) {
                 morale -= mon_plan.fears_hostile_seen;
             }
         } );
     }
     if( mon_plan.target == nullptr ) {
         // Just avoiding overflow.
         turns_since_target = std::min( turns_since_target + 1, max_turns_for_rate_limiting );
     } else {
         turns_since_target = 0;
     }
     // Friendly monsters here
     // Avoid for hordes of same-faction stuff or it could get expensive
     const mfaction_id actual_faction = friendly == 0 ? faction : STATIC( mfaction_str_id( "player" ) );
     mon_plan.swarms = mon_plan.swarms && mon_plan.target == nullptr; // Only swarm if we have no target
     if( mon_plan.group_morale || mon_plan.swarms ) {
         tracker.for_each_reachable( *this, [actual_faction]( const mfaction_id & other ) {
             return actual_faction == other;
         },
         [this, &seen_levels, &mon_plan]( Creature * other ) {
             if( !seen_levels.test( other->posz() + OVERMAP_DEPTH ) ) {
                 return;
             }
             monster *mon_ptr = dynamic_cast<monster *>( other );
             if( mon_ptr == nullptr ) {
                 return;
             }
             monster &mon = *mon_ptr;
             float rating = rate_target( mon, mon_plan.dist, mon_plan.smart_planning );
             if( mon_plan.group_morale && rating <= 10 ) {
                 morale += 10 - rating;
             }
             if( mon_plan.swarms ) {
                 if( rating < 5 ) { // Too crowded here
                     wander_pos = get_location();
                     while( wander_pos == get_location() ) {
                         wander_pos += point( rng( -3, 3 ), rng( -3, 3 ) );
                     }
                     wandf = 2;
                     mon_plan.target = nullptr;
                     // Swarm to the furthest ally you can see
                 } else if( rating < FLT_MAX && rating > mon_plan.dist && wandf <= 0 ) {
                     mon_plan.target = &mon;
                     mon_plan.dist = rating;
                 }
             }
         } );
     }
     // Operating monster keep you safe while they operate, how nice....
     if( type->has_special_attack( "OPERATE" ) ) {
         if( has_effect( effect_operating ) ) {
             friendly = 100;
             for( Creature *critter : here.get_creatures_in_radius( pos(), 6 ) ) {
                 monster *mon = dynamic_cast<monster *>( critter );
                 if( mon != nullptr && mon->type->in_species( species_ZOMBIE ) ) {
                     anger = 100;
                 } else {
                     anger = 0;
                 }
             }
         }
     }
     if( has_effect( effect_dragging ) ) {
         if( type->has_special_attack( "OPERATE" ) ) {
             bool found_path_to_couch = false;
             tripoint tmp( pos() + point( 12, 12 ) );
             tripoint couch_loc;
             for( const tripoint &couch_pos : here.find_furnitures_with_flag_in_radius( pos(), 10,
                     ter_furn_flag::TFLAG_AUTODOC_COUCH ) ) {
                 if( here.clear_path( pos(), couch_pos, 10, 0, 100 ) ) {
                     if( rl_dist( pos(), couch_pos ) < rl_dist( pos(), tmp ) ) {
                         tmp = couch_pos;
                         found_path_to_couch = true;
                         couch_loc = couch_pos;
                     }
                 }
             }
             if( !found_path_to_couch ) {
                 anger = 0;
                 remove_effect( effect_dragging );
             } else {
                 set_dest( here.getglobal( couch_loc ) );
             }
         }
     } else if( mon_plan.target != nullptr ) {
         const tripoint_abs_ms dest = mon_plan.target->get_location();
         Creature::Attitude att_to_target = attitude_to( *mon_plan.target );
         if( att_to_target == Attitude::HOSTILE && !mon_plan.fleeing ) {
             set_dest( dest );
         } else if( mon_plan.fleeing ) {
             tripoint_abs_ms away = get_location() - dest + get_location();
             away.z() = posz();
             set_dest( away );
         }
         if( ( mon_plan.angers_hostile_weak || mon_plan.fears_hostile_weak ||
               mon_plan.placate_hostile_weak ) &&
             att_to_target != Attitude::FRIENDLY ) {
             int hp_per = mon_plan.target->hp_percentage();
             if( hp_per <= 70 ) {
                 if( mon_plan.angers_hostile_weak && anger <= 40 ) {
                     anger += 10 - static_cast<int>( hp_per / 10 );
                     if( x_in_y( anger, 100 ) ) {
                         add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro triggered by %s's weakness", name(),
                                        mon_plan.target->disp_name() );
                         aggro_character = true;
                     }
                 } else if( mon_plan.fears_hostile_weak ) {
                     morale -= 10 - static_cast<int>( hp_per / 10 );
                 } else if( mon_plan.placate_hostile_weak ) {
                     anger -= 10 - static_cast<int>( hp_per / 10 );
                 }
             }
         }
     } else if( !patrol_route.empty() ) {
         // If we have a patrol route and no target, find the current step on the route
         tripoint_abs_ms next_stop = patrol_route.at( next_patrol_point );
         // if there is more than one patrol point, advance to the next one if we're almost there
         // this handles impassable obstacles but patrollers can still get stuck
         if( ( patrol_route.size() > 1 ) && rl_dist( next_stop, get_location() ) < 2 ) {
             next_patrol_point = ( next_patrol_point + 1 ) % patrol_route.size();
             next_stop = patrol_route.at( next_patrol_point );
         }
         set_dest( next_stop );
     } else if( friendly != 0 && has_effect( effect_led_by_leash ) &&
                get_location().z() == get_dest().z() ) {
         // visibility doesn't matter, we're getting pulled by a leash
         // To use stairs smoothly, if the destination is on a different Z-level, move there first.
         set_dest( player_character.get_location() );
         if( friendly > 0 && one_in( 3 ) ) {
             // Grow restless with no targets
             friendly--;
         }
     } else if( friendly > 0 && one_in( 3 ) ) {
         // Grow restless with no targets
         friendly--;
     } else if( is_pet_follow() && sees( player_character ) &&
                ( get_location().z() == player_character.get_location().z() ||
                  get_location().z() == get_dest().z() ) ) {
         // Simpleminded animals are too dumb to follow the player.
         // To use stairs smoothly, if the destination is on a different Z-level, move there first.
         set_dest( player_character.get_location() );
     }
 }
References add_msg_debug, aggro_character, anger, anger_cub_threatened(), anger_hostile_seen(), anger_mating_season(), monster_plan::angers_hostile_near, monster_plan::angers_hostile_seen, monster_plan::angers_hostile_weak, attitude(), attitude_to(), map::clear_path(), debugmode::DF_MONSTER, Creature::disp_name(), monster_plan::dist, monster_plan::docile, effect_dragging, effect_led_by_leash, effect_operating, faction, monster_plan::fears_hostile_near, monster_plan::fears_hostile_seen, monster_plan::fears_hostile_weak, map::find_furnitures_with_flag_in_radius(), monster_plan::fleeing, creature_tracker::for_each_reachable(), Creature::FRIENDLY, friendly, g, get_creature_tracker(), map::get_creatures_in_radius(), get_dest(), map::get_inter_level_visibility(), Creature::get_location(), get_map(), get_player_character(), map::getglobal(), monster_plan::group_morale, Creature::has_effect(), mtype::has_special_attack(), Creature::HOSTILE, Creature::hp_percentage(), mtype::in_species(), is_fleeing(), is_pet_follow(), logarithmic_range(), MATT_ATTACK, MATT_FLEE, MATT_FOLLOW, MFA_FRIENDLY, MFA_HATE, MFA_NEUTRAL, min(), mood, morale, name(), next_patrol_point, one_in(), other, OVERMAP_DEPTH, patrol_route, monster_plan::placate_hostile_weak, point, Creature::pos(), Creature::posz(), rate_target(), Creature::remove_effect(), rl_dist(), rng(), Creature::sees(), set_dest(), monster_plan::smart_planning, species_ZOMBIE, STATIC, monster_plan::swarms, monster_plan::target, TFLAG_AUTODOC_COUCH, turns_since_target, type, wander_pos, wandf, x_in_y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and tripoint::z.
poly()
void monster::poly (const mtype_id & id)
Definition at line 375 of file monster.cpp.
 {
     double hp_percentage = static_cast<double>( hp ) / static_cast<double>( type->hp );
     if( !no_extra_death_drops ) {
         generate_inventory();
     }
     type = &id.obj();
     moves = 0;
     Creature::set_speed_base( type->speed );
     anger = type->agro;
     morale = type->morale;
     hp = static_cast<int>( hp_percentage * type->hp );
     special_attacks.clear();
     for( const auto &sa : type->special_attacks ) {
         mon_special_attack &entry = special_attacks[sa.first];
         entry.cooldown = sa.second->cooldown;
     }
     faction = type->default_faction;
     upgrades = type->upgrades;
     reproduces = type->reproduces;
     biosignatures = type->biosignatures;
     aggro_character = type->aggro_character;
 }
References aggro_character, mtype::aggro_character, mtype::agro, anger, biosignatures, mtype::biosignatures, mon_special_attack::cooldown, mtype::default_faction, generate_inventory(), hp, mtype::hp, hp_percentage(), morale, mtype::morale, Creature::moves, no_extra_death_drops, reproduces, mtype::reproduces, Creature::set_speed_base(), special_attacks, mtype::special_attacks, mtype::speed, type, upgrades, and mtype::upgrades.
Referenced by blobify(), iuse::can_goo(), mattack::dermatik_growth(), mattack::dogthing(), mattack::fungus_growth(), trapfunc::goo(), mattack::leech_spawner(), magical_polymorph(), make_fungus(), mattack::mon_leech_evolution(), mattack::plant(), poly_keep_speed(), mattack::triffid_growth(), and try_upgrade().
power_rating()
float monster::power_rating () const override virtual
Returns an approximation of the creature's strength.
Implements Creature.
Definition at line 3651 of file monster.cpp.
 {
     // This should probably be replaced by something based on difficulty,
     // at least for smarter critters using it for evaluation.
     float ret = get_size() - 2.0f; // Zed gets 1, cat -1, hulk 3
     ret += is_ranged_attacker() ? 2.0f : 0.0f;
     // Hostile stuff gets a big boost
     // Neutral moose will still get burned if it comes close
     return ret;
 }
References get_size(), Creature::is_ranged_attacker(), and cata::hash64_detail::ret.
print_info()
int monster::print_info (const catacurses::window & w, int vStart, int vLines, int column) const override virtual
Write information about this creature.
Parameters
w the window to print the text into.
vStart vertical start to print, that means the first line to print.
vLines number of lines to print at most (printing less is fine).
column horizontal start to print (column), horizontal end is one character before the right border of the window (to keep the border).
Returns
The line just behind the last printed line, that means multiple calls to this can be stacked, the return value is acceptable as vStart for the next call without creating empty lines or overwriting lines.
Implements Creature.
Definition at line 864 of file monster.cpp.
 {
     const int vEnd = vStart + vLines;
     const int max_width = getmaxx( w ) - column - 1;
     std::ostringstream oss;
     oss << get_tag_from_color( c_white ) << _( "Origin: " );
     oss << enumerate_as_string( type->src.begin(),
     type->src.end(), []( const std::pair<mtype_id, mod_id> &source ) {
         return string_format( "'%s'", source.second->name() );
     }, enumeration_conjunction::arrow );
     oss << "</color>" << "\n";
     if( debug_mode ) {
         oss << colorize( type->id.str(), c_white );
     }
     oss << "\n";
     // Print health bar, monster name, then statuses on the first line.
     nc_color bar_color = c_white;
     std::string bar_str;
     get_HP_Bar( bar_color, bar_str );
     oss << get_tag_from_color( bar_color ) << bar_str << "</color>";
     oss << "<color_white>" << std::string( 5 - utf8_width( bar_str ), '.' ) << "</color> ";
     oss << get_tag_from_color( basic_symbol_color() ) << name() << "</color> ";
     oss << "<color_h_white>" << get_effect_status() << "</color>";
     vStart += fold_and_print( w, point( column, vStart ), max_width, c_white, oss.str() );
     Character &pc = get_player_character();
     bool sees_player = sees( pc );
     const bool player_knows = !pc.has_trait( trait_INATTENTIVE );
     // Hostility indicator on the second line.
     std::pair<std::string, nc_color> att = get_attitude();
     if( player_knows ) {
         mvwprintz( w, point( column, vStart++ ), att.second, att.first );
     }
     // Awareness indicator in the third line.
     std::string senses_str = sees_player ? _( "Can see to your current location" ) :
                              _( "Can't see to your current location" );
     if( player_knows ) {
         vStart += fold_and_print( w, point( column, vStart ), max_width, player_knows &&
                                   sees_player ? c_red : c_green,
                                   senses_str );
     }
     const std::string speed_desc = speed_description(
                                        speed_rating(),
                                        has_flag( mon_flag_IMMOBILE ),
                                        type->speed_desc );
     vStart += fold_and_print( w, point( column, vStart ), max_width, c_white, speed_desc );
     // Monster description on following lines.
     std::vector<std::string> lines = foldstring( type->get_description(), max_width );
     int numlines = lines.size();
     for( int i = 0; i < numlines && vStart < vEnd; i++ ) {
         mvwprintz( w, point( column, vStart++ ), c_light_gray, lines[i] );
     }
     if( !mission_fused.empty() ) {
         // Mission monsters fused into this monster
         const std::string fused_desc = string_format( _( "Parts of %s protrude from its body." ),
                                        enumerate_as_string( mission_fused ) );
         lines = foldstring( fused_desc, max_width );
         numlines = lines.size();
         for( int i = 0; i < numlines && vStart < vEnd; i++ ) {
             mvwprintz( w, point( column, ++vStart ), c_light_gray, lines[i] );
         }
     }
     // Riding indicator on next line after description.
     if( has_effect( effect_ridden ) && mounted_player ) {
         mvwprintz( w, point( column, ++vStart ), c_white, _( "Rider: %s" ), mounted_player->disp_name() );
     }
     // Show monster size on the last line
     if( size_bonus > 0 ) {
         mvwprintz( w, point( column, ++vStart ), c_light_gray, _( " It is %s." ),
                    size_names.at( get_size() ) );
     }
     if( get_option<bool>( "ENABLE_ASCII_ART" ) ) {
         const ascii_art_id art = type->get_picture_id();
         if( art.is_valid() ) {
             for( const std::string &line : art->picture ) {
                 fold_and_print( w, point( column, ++vStart ), max_width, c_white, line );
             }
         }
     }
     return ++vStart;
 }
References _, arrow, basic_symbol_color(), c_green, c_light_gray, c_red, c_white, colorize(), debug_mode, Character::disp_name(), effect_ridden, enumerate_as_string(), fold_and_print(), foldstring(), get_attitude(), mtype::get_description(), get_effect_status(), get_HP_Bar(), mtype::get_picture_id(), get_player_character(), get_size(), get_tag_from_color(), catacurses::getmaxx(), Creature::has_effect(), has_flag(), Character::has_trait(), mtype::id, string_id< T >::is_valid(), line, mission_fused, mon_flag_IMMOBILE, mounted_player, mvwprintz(), name(), ascii_art::picture, point, Creature::sees(), Creature::size_bonus, size_names, mtype::speed_desc, speed_description(), speed_rating(), mtype::src, string_id< T >::str(), string_format(), trait_INATTENTIVE, type, and utf8_width().
Referenced by wish_monster_callback::refresh().
process_effects()
void monster::process_effects () override virtual
Processes monster-specific effects before calling Creature::process_effects().
Reimplemented from Creature.
Definition at line 3204 of file monster.cpp.
 {
     // Monster only effects
     for( auto &elem : *effects ) {
         for( auto &_effect_it : elem.second ) {
             process_one_effect( _effect_it.second, false );
         }
     }
     // Like with player/NPCs - keep the speed above 0
     const int min_speed_bonus = -0.75 * get_speed_base();
     if( get_speed_bonus() < min_speed_bonus ) {
         set_speed_bonus( min_speed_bonus );
     }
     Character &player_character = get_player_character();
     //If this monster has the ability to heal in combat, do it now.
     int regeneration_amount = type->regenerates;
     //Apply effect-triggered regeneartion modifiers
     for( const auto &regeneration_modifier : type->regeneration_modifiers ) {
         if( has_effect( regeneration_modifier.first ) ) {
             regeneration_amount += regeneration_modifier.second;
         }
     }
     //Apply enchantment modifiers
     regeneration_amount = calculate_by_enchantment( regeneration_amount, enchant_vals::mod::REGEN_HP,
                           true );
     //Prevent negative regeneration
     if( regeneration_amount < 0 ) {
         regeneration_amount = 0;
     }
     const int healed_amount = heal( regeneration_amount );
     if( healed_amount > 0 && one_in( 2 ) ) {
         std::string healing_format_string;
         if( healed_amount >= 50 ) {
             healing_format_string = _( "The %s is visibly regenerating!" );
         } else if( healed_amount >= 10 ) {
             healing_format_string = _( "The %s seems a little healthier." );
         } else {
             healing_format_string = _( "The %s is healing slowly." );
         }
         add_msg_if_player_sees( *this, m_warning, healing_format_string, name() );
     }
     if( type->regenerates_in_dark && !g->is_in_sunlight( pos() ) ) {
         const float light = get_map().ambient_light_at( pos() );
         // Magic number 10000 was chosen so that a floodlight prevents regeneration in a range of 20 tiles
         const float dHP = 50.0 * std::exp( - light * light / 10000 );
         if( heal( static_cast<int>( dHP ) ) > 0 && one_in( 2 ) ) {
             add_msg_if_player_sees( *this, m_warning, _( "The %s uses the darkness to regenerate." ), name() );
         }
     }
     if( has_effect( effect_critter_well_fed ) && one_in( 90 ) ) {
         heal( 1 );
     }
     //We already check these timers on_load, but adding a random chance for them to go off here
     //will make it so that the player needn't leave the area and return for critters to poop,
     //become hungry, evolve, have babies, or refill udders.
     if( one_in( 30000 ) ) {
         try_upgrade( false );
         try_reproduce();
         try_biosignature();
         if( amount_eaten > 0 ) {
             if( has_flag( mon_flag_EATS ) ) {
                 digest_food();
             } else {
                 amount_eaten = 0;
             }
         }
         if( has_flag( mon_flag_MILKABLE ) ) {
             refill_udders();
         }
     }
     //Monster will regen morale and aggression if it is at/above max HP
     //It regens more morale and aggression if is currently fleeing.
     if( type->regen_morale && hp >= type->hp ) {
         if( is_fleeing( player_character ) ) {
             morale = type->morale;
             anger = type->agro;
         }
         if( morale < type->morale ) {
             morale += 1;
         }
         if( anger < type->agro ) {
             anger += 1;
         }
         if( morale < 0 && morale < type->morale ) {
             morale += 5;
             morale = std::min( morale, type->morale );
         }
         if( anger < 0 && anger < type->agro ) {
             anger += 5;
             anger = std::min( anger, type->agro );
         }
     }
     if( has_flag( mon_flag_CORNERED_FIGHTER ) ) {
         map &here = get_map();
         creature_tracker &creatures = get_creature_tracker();
         for( const tripoint &p : here.points_in_radius( pos(), 2 ) ) {
             const monster *const mon = creatures.creature_at<monster>( p );
             const Character *const guy = creatures.creature_at<Character>( p );
             if( mon && mon != this && mon->faction->attitude( faction ) != MFA_FRIENDLY &&
                 !has_effect( effect_spooked ) && morale <= 0 ) {
                 if( !has_effect( effect_spooked_recent ) ) {
                     add_effect( effect_spooked, 3_turns, false );
                     add_effect( effect_spooked_recent, 9_turns, false );
                 } else {
                     if( morale < type->morale ) {
                         morale = type->morale;
                         anger = type->agro;
                     }
                 }
             }
             if( guy ) {
                 monster_attitude att = attitude( guy );
                 if( ( friendly == 0 ) && ( att == MATT_FOLLOW || att == MATT_FLEE ) &&
                     !has_effect( effect_spooked ) ) {
                     if( !has_effect( effect_spooked_recent ) ) {
                         add_effect( effect_spooked, 3_turns, false );
                         add_effect( effect_spooked_recent, 9_turns, false );
                     } else {
                         if( morale < type->morale ) {
                             morale = type->morale;
                             anger = type->agro;
                         }
                     }
                 }
             }
         }
     }
     if( is_nemesis() ) {
         add_effect( effect_nemesis_buff, 1000_turns, true );
     }
     if( has_flag( mon_flag_PHOTOPHOBIC ) && get_map().ambient_light_at( pos() ) >= 30.0f ) {
         add_msg_if_player_sees( *this, m_good, _( "The shadow withers in the light!" ), name() );
         add_effect( effect_photophobia, 5_turns, true );
     }
     // If this critter dies in sunlight, check & assess damage.
     if( has_flag( mon_flag_SUNDEATH ) && g->is_in_sunlight( pos() ) ) {
         add_msg_if_player_sees( *this, m_good, _( "The %s burns horribly in the sunlight!" ), name() );
         apply_damage( nullptr, bodypart_id( "torso" ), 100 );
         if( hp < 0 ) {
             hp = 0;
         }
     }
     // Apply or remove the cramped_space effect, which needs specific information about the monster's surroundings.
     map &here = get_map();
     const tripoint z_pos = pos();
     const optional_vpart_position vp = here.veh_at( z_pos );
     if( has_effect( effect_cramped_space ) && !vp.has_value() ) {
         remove_effect( effect_cramped_space );
     }
     if( vp.has_value() ) {
         vehicle &veh = vp->vehicle();
         units::volume capacity = 0_ml;
         units::volume free_cargo = 0_ml;
         auto cargo_parts = veh.get_parts_at( z_pos, "CARGO", part_status_flag::any );
         for( vehicle_part *&part : cargo_parts ) {
             vehicle_stack contents = veh.get_items( *part );
             const vpart_info &vpinfo = part->info();
             if( !vp.part_with_feature( "CARGO_PASSABLE", false ) ) {
                 capacity += vpinfo.size;
                 free_cargo += contents.free_volume();
             }
         }
         const creature_size size = get_size();
         if( capacity > 0_ml ) {
             // Open-topped vehicle parts have more room, and are always free space for fliers.
             if( !veh.enclosed_at( z_pos ) ) {
                 free_cargo *= 1.2;
                 if( flies() ) {
                     remove_effect( effect_cramped_space );
                     return;
                 }
             }
             if( ( size == creature_size::tiny && free_cargo < 15625_ml ) ||
                 ( size == creature_size::small && free_cargo < 31250_ml ) ||
                 ( size == creature_size::medium && free_cargo < 62500_ml ) ||
                 ( size == creature_size::large && free_cargo < 125000_ml ) ||
                 ( size == creature_size::huge && free_cargo < 250000_ml ) ) {
                 if( !has_effect( effect_cramped_space ) ) {
                     add_effect( effect_cramped_space, 2_turns, true );
                 }
                 return;
             }
         }
         if( get_size() == creature_size::huge && !vp.part_with_feature( "AISLE", false ) &&
             !vp.part_with_feature( "HUGE_OK", false ) ) {
             if( !has_effect( effect_cramped_space ) ) {
                 add_effect( effect_cramped_space, 2_turns, true );
             }
             return;
         }
         remove_effect( effect_cramped_space );
     }
     Creature::process_effects();
 }
References _, Creature::add_effect(), add_msg_if_player_sees(), mtype::agro, map::ambient_light_at(), amount_eaten, anger, any, apply_damage(), attitude(), monfaction::attitude(), calculate_by_enchantment(), anonymous_namespace{item_tname.cpp}::contents(), creature_tracker::creature_at(), digest_food(), effect_cramped_space, effect_critter_well_fed, effect_nemesis_buff, effect_photophobia, effect_spooked, effect_spooked_recent, Creature::effects, vehicle::enclosed_at(), faction, flies(), friendly, g, get_creature_tracker(), vehicle::get_items(), get_map(), vehicle::get_parts_at(), get_player_character(), get_size(), Creature::get_speed_base(), Creature::get_speed_bonus(), Creature::has_effect(), has_flag(), heal(), hp, mtype::hp, huge, is_fleeing(), is_nemesis(), large, light, m_good, m_warning, MATT_FLEE, MATT_FOLLOW, medium, MFA_FRIENDLY, min(), mon_flag_CORNERED_FIGHTER, mon_flag_EATS, mon_flag_MILKABLE, mon_flag_PHOTOPHOBIC, mon_flag_SUNDEATH, morale, mtype::morale, name(), one_in(), optional_vpart_position::part_with_feature(), map::points_in_radius(), Creature::pos(), Creature::process_effects(), process_one_effect(), refill_udders(), enchant_vals::REGEN_HP, mtype::regen_morale, mtype::regenerates, mtype::regenerates_in_dark, mtype::regeneration_modifiers, Creature::remove_effect(), Creature::set_speed_bonus(), om_direction::size, vpart_info::size, small, tiny, try_biosignature(), try_reproduce(), try_upgrade(), type, and map::veh_at().
process_one_effect()
void monster::process_one_effect (effect & it, bool is_new) override protected virtual
Processes monster-specific effects of an effect.
Implements Creature.
Definition at line 3111 of file monster.cpp.
 {
     // Monsters don't get trait-based reduction, but they do get effect based reduction
     bool reduced = resists_effect( it );
     const auto get_effect = [&it, is_new]( const std::string & arg, bool reduced ) {
         if( is_new ) {
             return it.get_amount( arg, reduced );
         }
         return it.get_mod( arg, reduced );
     };
     mod_speed_bonus( get_effect( "SPEED", reduced ) );
     mod_dodge_bonus( get_effect( "DODGE", reduced ) );
     mod_hit_bonus( get_effect( "HIT", reduced ) );
     mod_bash_bonus( get_effect( "BASH", reduced ) );
     mod_cut_bonus( get_effect( "CUT", reduced ) );
     mod_size_bonus( get_effect( "SIZE", reduced ) );
     int val = get_effect( "HURT", reduced );
     if( val > 0 ) {
         if( is_new || it.activated( calendar::turn, "HURT", val, reduced, 1 ) ) {
             apply_damage( it.get_source().resolve_creature(), bodypart_id( "torso" ), val );
         }
     }
     const efftype_id &id = it.get_id();
     // TODO: MATERIALS use fire resistance
     if( it.impairs_movement() ) {
         effect_cache[MOVEMENT_IMPAIRED] = true;
     } else if( id == effect_onfire ) {
         int dam = 0;
         if( made_of( material_veggy ) ) {
             dam = rng( 10, 20 );
         } else if( made_of( material_flesh ) || made_of( material_iflesh ) ) {
             dam = rng( 5, 10 );
         }
         dam -= get_armor_type( damage_heat, bodypart_id( "torso" ) );
         if( dam > 0 ) {
             apply_damage( it.get_source().resolve_creature(), bodypart_id( "torso" ), dam );
         } else {
             it.set_duration( 0_turns );
         }
     } else if( id == effect_run ) {
         effect_cache[FLEEING] = true;
     } else if( id == effect_no_sight || id == effect_blind ) {
         effect_cache[VISION_IMPAIRED] = true;
     } else if( ( id == effect_bleed || id == effect_dripping_mechanical_fluid ) &&
                x_in_y( it.get_intensity(), it.get_max_intensity() ) ) {
         // this is for balance only
         it.mod_duration( -rng( 1_turns, it.get_int_dur_factor() / 2 ) );
         bleed();
         if( id == effect_bleed ) {
             // monsters are simplified so they just take damage from bleeding
             apply_damage( it.get_source().resolve_creature(), bodypart_id( "torso" ), 1 );
         }
     } else if( id == effect_fake_common_cold ) {
         if( calendar::once_every( time_duration::from_seconds( rng( 30, 300 ) ) ) && one_in( 2 ) ) {
             sounds::sound( pos(), 4, sounds::sound_t::speech, _( "a hacking cough." ), false, "misc", "cough" );
         }
         avatar &you = get_avatar(); // No NPCs for now.
         if( rl_dist( pos(), you.pos() ) <= 1 ) {
             you.get_sick( false );
         }
     } else if( id == effect_fake_flu ) {
         // Need to define the two separately because it's theoretically (and realistically) possible to have both flu and cold at once, both for players and monsters.
         if( calendar::once_every( time_duration::from_seconds( rng( 30, 300 ) ) ) && one_in( 2 ) ) {
             sounds::sound( pos(), 4, sounds::sound_t::speech, _( "a hacking cough." ), false, "misc", "cough" );
         }
         avatar &you = get_avatar(); // No NPCs for now.
         if( rl_dist( pos(), you.pos() ) <= 1 ) {
             you.get_sick( true );
         }
     }
     //Process enchantments that apply to monsters.
     enchantment_cache->clear();
     for( const auto &elem : *effects ) {
         for( const enchantment_id &ench_id : elem.first->enchantments ) {
             const enchantment &ench = ench_id.obj();
             if( ench.is_active( *this ) && ench.is_monster_relevant() ) {
                 enchantment_cache->force_add( ench, *this );
             }
         }
     }
     //Reset max speed
     this->set_speed_base( calculate_by_enchantment( this->get_speed_base(), enchant_vals::mod::SPEED,
                           true ) );
 }
References _, effect::activated(), apply_damage(), Creature::bleed(), calculate_by_enchantment(), damage_heat, effect_bleed, effect_blind, effect_cache, effect_dripping_mechanical_fluid, effect_fake_common_cold, effect_fake_flu, effect_no_sight, effect_onfire, effect_run, Creature::effects, enchantment_cache, FLEEING, time_duration::from_seconds(), effect::get_amount(), get_armor_type(), get_avatar(), Creature::get_effect(), effect::get_id(), effect::get_int_dur_factor(), effect::get_intensity(), effect::get_max_intensity(), effect::get_mod(), Character::get_sick(), effect::get_source(), Creature::get_speed_base(), effect::impairs_movement(), enchantment::is_active(), enchantment::is_monster_relevant(), made_of(), material_flesh, material_iflesh, material_veggy, Creature::mod_bash_bonus(), Creature::mod_cut_bonus(), Creature::mod_dodge_bonus(), effect::mod_duration(), Creature::mod_hit_bonus(), Creature::mod_size_bonus(), Creature::mod_speed_bonus(), MOVEMENT_IMPAIRED, string_id< T >::obj(), calendar::once_every(), one_in(), Creature::pos(), Creature::resists_effect(), effect_source::resolve_creature(), rl_dist(), rng(), effect::set_duration(), Creature::set_speed_base(), sounds::sound(), sounds::speech, enchant_vals::SPEED, calendar::turn, VISION_IMPAIRED, and x_in_y().
Referenced by process_effects().
process_trigger() [1/2]
void monster::process_trigger (mon_trigger trig, const std::function< int()> & amount_func) private
Definition at line 1735 of file monster.cpp.
 {
     if( type->has_anger_trigger( trig ) ) {
         anger += amount_func();
     }
     if( type->has_fear_trigger( trig ) ) {
         morale -= amount_func();
     }
     if( type->has_placate_trigger( trig ) ) {
         anger -= amount_func();
     }
 }
References anger, mtype::has_anger_trigger(), mtype::has_fear_trigger(), mtype::has_placate_trigger(), morale, and type.
process_trigger() [2/2]
void monster::process_trigger (mon_trigger trig, int amount) private
Definition at line 1722 of file monster.cpp.
 {
     if( type->has_anger_trigger( trig ) ) {
         anger += amount;
     }
     if( type->has_fear_trigger( trig ) ) {
         morale -= amount;
     }
     if( type->has_placate_trigger( trig ) ) {
         anger -= amount;
     }
 }
References anger, mtype::has_anger_trigger(), mtype::has_fear_trigger(), mtype::has_placate_trigger(), morale, and type.
Referenced by apply_damage(), hear_sound(), and process_triggers().
process_triggers()
void monster::process_triggers ()
Definition at line 1662 of file monster.cpp.
 {
     process_trigger( mon_trigger::STALK, [this]() {
         return anger > 0 && one_in( 5 ) ? 1 : 0;
     } );
     process_trigger( mon_trigger::BRIGHT_LIGHT, [this]() {
         int ret = 0;
         static const int dim_light = round( .75 * default_daylight_level() );
         int light = round( get_map().ambient_light_at( pos() ) );
         if( light >= dim_light ) {
             ret += 10;
         }
         return ret;
     } );
     process_trigger( mon_trigger::FIRE, [this]() {
         int ret = 0;
         map &here = get_map();
         const field_type_id fd_fire = ::fd_fire; // convert to int_id once
         for( const tripoint &p : here.points_in_radius( pos(), 3 ) ) {
             // note using `has_field_at` without bound checks,
             // as points that come from `points_in_radius` are guaranteed to be in bounds
             const int fire_intensity =
                 here.has_field_at( p, false ) ? 5 * here.get_field_intensity( p, fd_fire ) : 0;
             ret += fire_intensity;
         }
         return ret;
     } );
     if( morale != type->morale && one_in( 4 ) &&
         ( ( std::abs( morale - type->morale ) > 15 ) || one_in( 2 ) ) ) {
         if( morale < type->morale ) {
             morale++;
         } else {
             morale--;
         }
     }
     if( anger != type->agro && one_in( 4 ) &&
         ( ( std::abs( anger - type->agro ) > 15 ) || one_in( 2 ) ) ) {
         if( anger < type->agro ) {
             anger++;
         } else {
             anger--;
         }
     }
     // If we got angry at characters have a chance at calming down
     if( anger == type->agro && aggro_character && !type->aggro_character && !x_in_y( anger, 100 ) ) {
         add_msg_debug( debugmode::DF_MONSTER, "%s's character aggro reset", name() );
         aggro_character = false;
     }
     // Cap values at [-100, 100] to prevent perma-angry moose etc.
     morale = std::min( 100, std::max( -100, morale ) );
     anger  = std::min( 100, std::max( -100, anger ) );
 }
References abs(), add_msg_debug, aggro_character, mtype::aggro_character, mtype::agro, anger, BRIGHT_LIGHT, default_daylight_level(), debugmode::DF_MONSTER, fd_fire, FIRE, map::get_field_intensity(), get_map(), map::has_field_at(), light, max(), min(), morale, mtype::morale, name(), one_in(), map::points_in_radius(), Creature::pos(), process_trigger(), cata::hash64_detail::ret, round(), STALK, type, and x_in_y().
Referenced by game::place_player().
process_turn()
void monster::process_turn () override virtual
Processes effects and bonuses and allocates move points based on speed.
Reimplemented from Creature.
Definition at line 2627 of file monster.cpp.
 {
     map &here = get_map();
     if( !is_hallucination() ) {
         for( const std::pair<const emit_id, time_duration> &e : type->emit_fields ) {
             if( !calendar::once_every( e.second ) ) {
                 continue;
             }
             const emit_id emid = e.first;
             if( emid == emit_emit_shock_cloud ) {
                 if( has_effect( effect_emp ) ) {
                     continue; // don't emit electricity while EMPed
                 } else if( has_effect( effect_supercharged ) ) {
                     here.emit_field( pos(), emit_emit_shock_cloud_big );
                     continue;
                 }
             }
             here.emit_field( pos(), emid );
         }
     }
     // Special attack cooldowns are updated here.
     // Loop through the monster's special attacks, same as monster::move.
     for( const auto &sp_type : type->special_attacks ) {
         const std::string &special_name = sp_type.first;
         const auto local_iter = special_attacks.find( special_name );
         if( local_iter == special_attacks.end() ) {
             continue;
         }
         mon_special_attack &local_attack_data = local_iter->second;
         if( !local_attack_data.enabled ) {
             continue;
         }
         if( local_attack_data.cooldown > 0 ) {
             local_attack_data.cooldown--;
         }
     }
     creature_tracker &creatures = get_creature_tracker();
     // Persist grabs as long as there's an adjacent target.
     if( has_effect_with_flag( json_flag_GRAB_FILTER ) ) {
         bool remove = true;
         for( const tripoint &dest : here.points_in_radius( pos(), 1, 0 ) ) {
             const Creature *const you = creatures.creature_at<Creature>( dest );
             if( you && you->has_effect_with_flag( json_flag_GRAB ) ) {
                 add_msg_debug( debugmode::DF_MATTACK, "Grabbed creature %s found, persisting grab.",
                                you->get_name() );
                 remove = false;
             }
         }
         if( remove ) {
             for( const effect &eff : get_effects_with_flag( json_flag_GRAB_FILTER ) ) {
                 const efftype_id effid = eff.get_id();
                 remove_effect( effid );
                 add_msg_debug( debugmode::DF_MATTACK, "Grab filter effect %s removed.", effid.c_str() );
             }
         }
     }
     // We update electrical fields here since they act every turn.
     if( has_flag( mon_flag_ELECTRIC_FIELD ) && !is_hallucination() ) {
         if( has_effect( effect_emp ) ) {
             if( calendar::once_every( 10_turns ) ) {
                 sounds::sound( pos(), 5, sounds::sound_t::combat, _( "hummmmm." ), false, "humming", "electric" );
             }
         } else {
             weather_manager &weather = get_weather();
             for( const tripoint &zap : here.points_in_radius( pos(), 1 ) ) {
                 const map_stack items = here.i_at( zap );
                 for( const item &item : items ) {
                     if( item.made_of( phase_id::LIQUID ) && item.flammable() ) { // start a fire!
                         here.add_field( zap, fd_fire, 2, 1_minutes );
                         sounds::sound( pos(), 30, sounds::sound_t::combat,  _( "fwoosh!" ), false, "fire", "ignition" );
                         break;
                     }
                 }
                 if( zap != pos() ) {
                     explosion_handler::emp_blast( zap ); // Fries electronics due to the intensity of the field
                 }
                 const ter_id t = here.ter( zap );
                 if( t == ter_t_gas_pump || t == ter_t_gas_pump_a ) {
                     if( one_in( 4 ) ) {
                         explosion_handler::explosion( this, pos(), 40, 0.8, true );
                         add_msg_if_player_sees( zap, m_warning, _( "The %s explodes in a fiery inferno!" ),
                                                 here.tername( zap ) );
                     } else {
                         add_msg_if_player_sees( zap, m_warning, _( "Lightning from %1$s engulfs the %2$s!" ),
                                                 name(), here.tername( zap ) );
                         here.add_field( zap, fd_fire, 1, 2_turns );
                     }
                 }
             }
             if( weather.lightning_active && !has_effect( effect_supercharged ) &&
                 here.is_outside( pos() ) ) {
                 weather.lightning_active = false; // only one supercharge per strike
                 sounds::sound( pos(), 300, sounds::sound_t::combat, _( "BOOOOOOOM!!!" ), false, "environment",
                                "thunder_near" );
                 sounds::sound( pos(), 20, sounds::sound_t::combat, _( "vrrrRRRUUMMMMMMMM!" ), false, "explosion",
                                "default" );
                 Character &player_character = get_player_character();
                 if( player_character.sees( pos() ) ) {
                     add_msg( m_bad, _( "Lightning strikes the %s!" ), name() );
                     add_msg( m_bad, _( "Your vision goes white!" ) );
                     player_character.add_effect( effect_blind, rng( 1_minutes, 2_minutes ) );
                 }
                 add_effect( effect_supercharged, 12_hours );
             } else if( has_effect( effect_supercharged ) && calendar::once_every( 5_turns ) ) {
                 sounds::sound( pos(), 20, sounds::sound_t::combat, _( "VMMMMMMMMM!" ), false, "humming",
                                "electric" );
             }
         }
     }
     Creature::process_turn();
 }
References _, Creature::add_effect(), map::add_field(), add_msg(), add_msg_debug, add_msg_if_player_sees(), string_id< T >::c_str(), sounds::combat, mon_special_attack::cooldown, creature_tracker::creature_at(), debugmode::DF_MATTACK, effect_blind, effect_emp, effect_supercharged, emit_emit_shock_cloud, emit_emit_shock_cloud_big, map::emit_field(), mtype::emit_fields, explosion_handler::emp_blast(), mon_special_attack::enabled, explosion_handler::explosion(), fd_fire, item::flammable(), get_creature_tracker(), Creature::get_effects_with_flag(), get_map(), Creature::get_name(), get_player_character(), get_weather(), Creature::has_effect(), Creature::has_effect_with_flag(), has_flag(), map::i_at(), is_hallucination(), map::is_outside(), json_flag_GRAB, json_flag_GRAB_FILTER, LIQUID, m_bad, m_warning, item::made_of(), mon_flag_ELECTRIC_FIELD, name(), calendar::once_every(), one_in(), map::points_in_radius(), Creature::pos(), Creature::process_turn(), remove, Creature::remove_effect(), rng(), Character::sees(), sounds::sound(), special_attacks, mtype::special_attacks, map::ter(), ter_t_gas_pump, ter_t_gas_pump_a, map::tername(), and type.
push_to()
bool monster::push_to (const tripoint & p, int boost, size_t depth)
Try to push away whatever occupies p, then step in.
May recurse and try to make the creature at p push further.
Parameters
p Location of pushed object
boost A bonus on the roll to represent a horde pushing from behind
depth Number of recursions so far
Returns
True if we managed to push something and took its place, false otherwise.
Definition at line 2094 of file monmove.cpp.
 {
     if( is_hallucination() ) {
         // Don't let hallucinations push, not even other hallucinations
         return false;
     }
     if( !has_flag( mon_flag_PUSH_MON ) || depth > 2 || has_effect( effect_pushed ) ) {
         return false;
     }
     creature_tracker &creatures = get_creature_tracker();
     // TODO: Generalize this to Creature
     monster *const critter = creatures.creature_at<monster>( p );
     if( critter == nullptr || critter == this ||
         p == pos() || critter->movement_impaired() ) {
         return false;
     }
     if( !can_move_to( p ) ) {
         return false;
     }
     if( critter->is_hallucination() ) {
         // Kill the hallu, but return false so that the regular move_to is uses instead
         critter->die( nullptr );
         return false;
     }
     // Stability roll of the pushed critter
     const int defend = critter->stability_roll();
     // Stability roll of the pushing zed
     const int attack = stability_roll() + boost;
     if( defend > attack ) {
         return false;
     }
     map &here = get_map();
     const int movecost_from = 50 * here.move_cost( p );
     const int movecost_attacker = std::max( movecost_from, 200 - 10 * ( attack - defend ) );
     const tripoint dir = p - pos();
     // Mark self as pushed to simplify recursive pushing
     add_effect( effect_pushed, 1_turns );
     for( size_t i = 0; i < 6; i++ ) {
         const point d( rng( -1, 1 ), rng( -1, 1 ) );
         if( d.x == 0 && d.y == 0 ) {
             continue;
         }
         // Pushing forward is easier than pushing aside
         const int direction_penalty = std::abs( d.x - dir.x ) + std::abs( d.y - dir.y );
         if( direction_penalty > 2 ) {
             continue;
         }
         tripoint dest( p + d );
         const int dest_movecost_from = 50 * here.move_cost( dest );
         // Pushing into cars/windows etc. is harder
         const int movecost_penalty = here.move_cost( dest ) - 2;
         if( movecost_penalty <= -2 ) {
             // Can't push into unpassable terrain
             continue;
         }
         int roll = attack - ( defend + direction_penalty + movecost_penalty );
         if( roll < 0 ) {
             continue;
         }
         Creature *critter_recur = creatures.creature_at( dest );
         if( !( critter_recur == nullptr || critter_recur->is_hallucination() ) ) {
             // Try to push recursively
             monster *mon_recur = dynamic_cast< monster * >( critter_recur );
             if( mon_recur == nullptr ) {
                 continue;
             }
             if( critter->push_to( dest, roll, depth + 1 ) ) {
                 // The tile isn't necessarily free, need to check
                 if( !creatures.creature_at( p ) ) {
                     move_to( p );
                 }
                 mod_moves( -movecost_attacker );
                 // Don't knock down a creature that successfully
                 // pushed another creature, just reduce moves
                 critter->mod_moves( -dest_movecost_from );
                 return true;
             } else {
                 return false;
             }
         }
         critter_recur = creatures.creature_at( dest );
         if( critter_recur != nullptr ) {
             if( critter_recur->is_hallucination() ) {
                 critter_recur->die( nullptr );
             }
         } else if( !critter->has_flag( mon_flag_IMMOBILE ) ) {
             critter->setpos( dest );
             move_to( p );
             mod_moves( -movecost_attacker );
             critter->add_effect( effect_downed, time_duration::from_turns( movecost_from / 100 + 1 ) );
         }
         return true;
     }
     // Try to trample over a much weaker zed (or one with worse rolls)
     // Don't allow trampling with boost
     if( boost > 0 || attack < 2 * defend ) {
         return false;
     }
     g->swap_critters( *critter, *this );
     critter->add_effect( effect_stunned, rng( 0_turns, 2_turns ) );
     Character &player_character = get_player_character();
     // Only print the message when near player or it can get spammy
     if( rl_dist( player_character.pos(), pos() ) < 4 ) {
         add_msg_if_player_sees( *critter, m_warning, _( "The %1$s tramples %2$s." ),
                                 name(), critter->disp_name() );
     }
     mod_moves( -movecost_attacker );
     if( movecost_from > 100 ) {
         critter->add_effect( effect_downed, time_duration::from_turns( movecost_from / 100 + 1 ) );
     } else {
         critter->mod_moves( -movecost_from );
     }
     return true;
 }
References _, abs(), Creature::add_effect(), add_msg_if_player_sees(), spell_effect::attack(), can_move_to(), creature_tracker::creature_at(), die(), Creature::die(), disp_name(), effect_downed, effect_pushed, effect_stunned, time_duration::from_turns(), g, get_creature_tracker(), get_map(), get_player_character(), Creature::has_effect(), has_flag(), Creature::is_hallucination(), is_hallucination(), m_warning, max(), Creature::mod_moves(), mon_flag_IMMOBILE, mon_flag_PUSH_MON, map::move_cost(), move_to(), movement_impaired(), name(), Creature::pos(), push_to(), rl_dist(), rng(), Creature::setpos(), stability_roll(), point::x, tripoint::x, point::y, and tripoint::y.
Referenced by move(), mattack::nurse_operate(), nursebot_operate(), and push_to().
rate_target()
float monster::rate_target (Creature & c, float best, bool smart = false) const
Definition at line 361 of file monmove.cpp.
 {
     const FastDistanceApproximation d = rl_dist_fast( pos(), c.pos() );
     if( d <= 0 ) {
         return FLT_MAX;
     }
     // Check a very common and cheap case first
     if( !smart && d >= best ) {
         return FLT_MAX;
     }
     if( !sees( c ) ) {
         return FLT_MAX;
     }
     if( !smart ) {
         return static_cast<int>( d );
     }
     float power = c.power_rating();
     monster *mon = dynamic_cast< monster * >( &c );
     // Their attitude to us and not ours to them, so that bobcats won't get gunned down
     if( mon != nullptr && mon->attitude_to( *this ) == Attitude::HOSTILE ) {
         power += 2;
     }
     if( power > 0 ) {
         return static_cast<int>( d ) / power;
     }
     return FLT_MAX;
 }
References attitude_to(), c, Creature::HOSTILE, Creature::pos(), rl_dist_fast(), and Creature::sees().
Referenced by plan().
refill_udders()
void monster::refill_udders ()
Definition at line 613 of file monster.cpp.
 {
     if( type->starting_ammo.empty() ) {
         debugmsg( "monster %s has no starting ammo to refill udders", get_name() );
         return;
     }
     if( ammo.empty() ) {
         // legacy animals got empty ammo map, fill them up now if needed.
         ammo[type->starting_ammo.begin()->first] = type->starting_ammo.begin()->second;
     }
     auto current_milk = ammo.find( itype_milk_raw );
     if( current_milk == ammo.end() ) {
         current_milk = ammo.find( itype_milk );
         if( current_milk != ammo.end() ) {
             // take this opportunity to update milk udders to raw_milk
             ammo[itype_milk_raw] = current_milk->second;
             // Erase old key-value from map
             ammo.erase( current_milk );
         }
     }
     // if we got here, we got milk.
     if( current_milk->second == type->starting_ammo.begin()->second ) {
         // already full up
         return;
     }
     if( !has_flag( mon_flag_EATS ) || has_effect( effect_critter_well_fed ) ) {
         if( calendar::turn - udder_timer > 1_days ) {
             // You milk once a day. Monsters with the EATS flag need to be well fed or they won't refill their udders.
             ammo.begin()->second = type->starting_ammo.begin()->second;
             udder_timer = calendar::turn;
         }
     }
 }
References ammo, debugmsg, effect_critter_well_fed, get_name(), Creature::has_effect(), has_flag(), itype_milk, itype_milk_raw, mon_flag_EATS, mtype::starting_ammo, calendar::turn, type, and udder_timer.
Referenced by on_load(), and process_effects().
remove_grab()
void monster::remove_grab (bodypart_str_id bp)
Definition at line 2511 of file monster.cpp.
 {
     grabbed_limbs.erase( bp );
     if( grabbed_limbs.empty() ) {
         add_effect( effect_grabbing, 1_days, true, 1 );
     }
 }
References Creature::add_effect(), bp, effect_grabbing, and grabbed_limbs.
Referenced by Character::perform_technique(), and Character::try_remove_grab().
reset_bonuses()
void monster::reset_bonuses () override virtual
Resets the value of all bonus fields to 0, clears special effect flags.
Reimplemented from Creature.
Definition at line 2574 of file monster.cpp.
 {
     effect_cache.reset();
     Creature::reset_bonuses();
 }
References effect_cache, and Creature::reset_bonuses().
reset_digestion()
void monster::reset_digestion ()
Definition at line 647 of file monster.cpp.
 {
     if( calendar::turn - stomach_timer > 3_days ) {
         //If the player hasn't been around, assume critters have been operating at a subsistence level.
         //Otherwise everything will constantly be underfed. We only run this on load to prevent problems.
         remove_effect( effect_critter_underfed );
         remove_effect( effect_critter_well_fed );
         amount_eaten = 0;
         stomach_timer = calendar::turn;
     }
 }
References amount_eaten, effect_critter_underfed, effect_critter_well_fed, Creature::remove_effect(), stomach_timer, and calendar::turn.
Referenced by on_load().
reset_pathfinding_cd()
void monster::reset_pathfinding_cd () inline private
Definition at line 641 of file monster.h.
{
             pathfinding_cd = calendar::turn;
             pathfinding_backoff = 2_seconds;
         }
References pathfinding_backoff, pathfinding_cd, and calendar::turn.
Referenced by apply_damage(), move(), and set_dest().
reset_special()
void monster::reset_special (const std::string & special_name)
Resets a given special to its monster type cooldown value.
Definition at line 2586 of file monster.cpp.
 {
     set_special( special_name, type->special_attacks.at( special_name )->cooldown );
 }
References set_special(), mtype::special_attacks, and type.
Referenced by mattack::breathe(), and move().
reset_special_rng()
void monster::reset_special_rng (const std::string & special_name)
Resets a given special to a value between 0 and its monster type cooldown value.
Definition at line 2591 of file monster.cpp.
 {
     set_special( special_name, rng( 0, type->special_attacks.at( special_name )->cooldown ) );
 }
References rng(), set_special(), mtype::special_attacks, and type.
reset_stats()
void monster::reset_stats () override virtual
Resets stats, and applies effects in an idempotent manner.
Implements Creature.
Definition at line 2581 of file monster.cpp.
 {
     // Nothing here yet
 }
respond_to_light()
void monster::respond_to_light (float light_level)
scent_move()
tripoint monster::scent_move ()
Definition at line 1475 of file monmove.cpp.
 {
     // TODO: Remove when scentmap is 3D
     if( std::abs( posz() - get_map().get_abs_sub().z() ) > SCENT_MAP_Z_REACH ) {
         return { -1, -1, INT_MIN };
     }
     scent_map &scents = get_scent();
     bool in_range = scents.inbounds( pos() );
     if( !in_range ) {
         return { -1, -1, INT_MIN };
     }
     const std::set<scenttype_id> &tracked_scents = type->scents_tracked;
     const std::set<scenttype_id> &ignored_scents = type->scents_ignored;
     std::vector<tripoint> sdirection;
     std::vector<tripoint> smoves;
     int bestsmell = 10; // Squares with smell 0 are not eligible targets.
     int smell_threshold = 200; // Squares at or above this level are ineligible.
     if( has_flag( mon_flag_KEENNOSE ) ) {
         bestsmell = 1;
         smell_threshold = 400;
     }
     Character &player_character = get_player_character();
     const bool fleeing = is_fleeing( player_character );
     int scent_here = scents.get_unsafe( pos() );
     if( fleeing ) {
         bestsmell = scent_here;
     }
     tripoint next( -1, -1, posz() );
     // Scent is too weak, can't follow it.
     if( scent_here == 0 ) {
         return next;
     }
     // Check for the scent type being compatible.
     const scenttype_id &type_scent = scents.get_type();
     bool right_scent = false;
     // is the monster tracking this scent
     if( !tracked_scents.empty() ) {
         right_scent = tracked_scents.find( type_scent ) != tracked_scents.end();
     }
     //is this scent recognised by the monster species
     if( !type_scent.is_empty() ) {
         const std::set<species_id> &receptive_species = type_scent->receptive_species;
         const std::set<species_id> &monster_species = type->species;
         std::vector<species_id> v_intersection;
         std::set_intersection( receptive_species.begin(), receptive_species.end(), monster_species.begin(),
                                monster_species.end(), std::back_inserter( v_intersection ) );
         if( !v_intersection.empty() ) {
             right_scent = true;
         }
     }
     // is the monster actually ignoring this scent
     if( !ignored_scents.empty() && ( ignored_scents.find( type_scent ) != ignored_scents.end() ) ) {
         right_scent = false;
     }
     if( !right_scent ) {
         return { -1, -1, INT_MIN };
     }
     const bool can_bash = bash_skill() > 0;
     map &here = get_map();
     if( !fleeing && scent_here > smell_threshold ) {
         // Smell too strong to track, wander around
         sdirection.push_back( pos() );
     } else {
         // Get direction of scent
         for( const tripoint &dest : here.points_in_radius( pos(), 1, SCENT_MAP_Z_REACH ) ) {
             int smell = scents.get( dest );
             if( ( !fleeing && smell < bestsmell ) || ( fleeing && smell > bestsmell ) ) {
                 continue;
             }
             if( ( !fleeing && smell > bestsmell ) || ( fleeing && smell < bestsmell ) ) {
                 sdirection.clear();
                 sdirection.push_back( dest );
                 bestsmell = smell;
             } else if( ( !fleeing && smell == bestsmell ) || ( fleeing && smell == bestsmell ) ) {
                 sdirection.push_back( dest );
             }
         }
     }
     for( const tripoint &direction : sdirection ) {
         // Add some randomness to make creatures zigzag towards the source
         for( const tripoint &dest : here.points_in_radius( direction, 1 ) ) {
             if( here.valid_move( pos(), dest, can_bash, true ) &&
                 ( can_move_to( dest ) || ( dest == player_character.pos() ) ||
                   ( can_bash && here.bash_rating( bash_estimate(), dest ) > 0 ) ) ) {
                 smoves.push_back( dest );
             }
         }
     }
     return random_entry( smoves, next );
 }
References abs(), bash_estimate(), map::bash_rating(), bash_skill(), can_move_to(), scent_map::get(), get_map(), get_player_character(), get_scent(), scent_map::get_type(), scent_map::get_unsafe(), has_flag(), scent_map::inbounds(), string_id< T >::is_empty(), is_fleeing(), mon_flag_KEENNOSE, map::points_in_radius(), Creature::pos(), Creature::posz(), random_entry(), scent_type::receptive_species, SCENT_MAP_Z_REACH, mtype::scents_ignored, mtype::scents_tracked, mtype::species, type, and map::valid_move().
Referenced by move().
serialize()
void monster::serialize (JsonOut & json) const
Definition at line 2596 of file savegame_json.cpp.
 {
     json.start_object();
     // This must be after the json object has been started, so any super class
     // puts their data into the same json object.
     store( json );
     json.end_object();
 }
References JsonOut::end_object(), and JsonOut::start_object().
set_dest()
void monster::set_dest (const tripoint_abs_ms & p)
Definition at line 1380 of file monster.cpp.
 {
     if( !goal || rl_dist( p, *goal ) > 2 ) {
         reset_pathfinding_cd();
     }
     goal = p;
 }
References goal, reset_pathfinding_cd(), and rl_dist().
Referenced by iuse::directional_hologram(), mattack::nurse_operate(), plan(), and mattack::smash_specific().
set_horde_attraction()
void monster::set_horde_attraction (monster_horde_attraction mha)
Definition at line 3826 of file monster.cpp.
 {
     horde_attraction = mha;
 }
References horde_attraction.
Referenced by map::spawn_monsters_submap_group().
set_hp()
void monster::set_hp (int hp)
Directly set the current hp of the monster (not capped at the maximal hp).
You might want to use heal / apply_damage or deal_damage instead.
Definition at line 2164 of file monster.cpp.
 {
     this->hp = hp;
 }
References hp.
Referenced by mattack::absorb_items(), blobify(), iuse::can_goo(), game::despawn_monster(), die(), mattack::disappear(), mattack::formblob(), trapfunc::goo(), iuse::granade_act(), mattack::mon_leech_evolution(), mattack::plant(), talker_monster::set_all_parts_hp_cur(), and mattack::split().
set_patrol_route()
void monster::set_patrol_route (const std::vector< point > & patrol_pts_rel_ms)
Definition at line 1355 of file monster.cpp.
 {
     const tripoint_abs_ms base_abs_ms = project_to<coords::ms>( global_omt_location() );
     for( const point &patrol_pt : patrol_pts_rel_ms ) {
         patrol_route.push_back( base_abs_ms + patrol_pt );
     }
     next_patrol_point = 0;
 }
References Creature::global_omt_location(), next_patrol_point, and patrol_route.
Referenced by map::spawn_monsters_submap().
set_special()
void monster::set_special (const std::string & special_name, int time)
Sets a given special to the given value.
Definition at line 2596 of file monster.cpp.
 {
     special_attacks[ special_name ].cooldown = time;
 }
References special_attacks.
Referenced by reset_special(), and reset_special_rng().
shearable()
bool monster::shearable () const
Definition at line 1314 of file monster.cpp.
 {
     return type->shearing.valid();
 }
References mtype::shearing, type, and shearing_data::valid().
Referenced by monexamine::pet_menu(), and shearing_activity_actor::start().
shift()
void monster::shift (const point & sm_shift)
Definition at line 1364 of file monster.cpp.
 {
     // TODO: migrate this to absolute coords and get rid of shift()
     path.clear();
 }
References path.
shove_vehicle()
void monster::shove_vehicle (const tripoint & remote_destination, const tripoint & nearby_destination)
Definition at line 2425 of file monmove.cpp.
 {
     map &here = get_map();
     if( this->has_flag( mon_flag_PUSH_VEH ) && !is_hallucination() ) {
         optional_vpart_position vp = here.veh_at( nearby_destination );
         if( vp ) {
             vehicle &veh = vp->vehicle();
             const units::mass veh_mass = veh.total_mass();
             int shove_moves_minimal = 0;
             int shove_veh_mass_moves_factor = 0;
             int shove_velocity = 0;
             float shove_damage_min = 0.00F;
             float shove_damage_max = 0.00F;
             switch( this->get_size() ) {
                 case creature_size::tiny:
                 case creature_size::small:
                     break;
                 case creature_size::medium:
                     if( veh_mass < 500_kilogram ) {
                         shove_moves_minimal = 150;
                         shove_veh_mass_moves_factor = 20;
                         shove_velocity = 500;
                         shove_damage_min = 0.00F;
                         shove_damage_max = 0.01F;
                     }
                     break;
                 case creature_size::large:
                     if( veh_mass < 1000_kilogram ) {
                         shove_moves_minimal = 100;
                         shove_veh_mass_moves_factor = 8;
                         shove_velocity = 1000;
                         shove_damage_min = 0.00F;
                         shove_damage_max = 0.03F;
                     }
                     break;
                 case creature_size::huge:
                     if( veh_mass < 2000_kilogram ) {
                         shove_moves_minimal = 50;
                         shove_veh_mass_moves_factor = 4;
                         shove_velocity = 1500;
                         shove_damage_min = 0.00F;
                         shove_damage_max = 0.05F;
                     }
                     break;
                 default:
                     break;
             }
             if( shove_velocity > 0 ) {
                 //~ %1$s - monster name, %2$s - vehicle name
                 add_msg_if_player_sees( this->pos(), m_bad, _( "%1$s shoves %2$s out of their way!" ),
                                         this->disp_name(),
                                         veh.disp_name() );
                 int shove_moves = shove_veh_mass_moves_factor * veh_mass / 10_kilogram;
                 shove_moves = std::max( shove_moves, shove_moves_minimal );
                 this->mod_moves( -shove_moves );
                 const tripoint destination_delta( -nearby_destination + remote_destination );
                 const tripoint shove_destination( clamp( destination_delta.x, -1, 1 ),
                                                   clamp( destination_delta.y, -1, 1 ),
                                                   clamp( destination_delta.z, -1, 1 ) );
                 veh.skidding = true;
                 veh.velocity = shove_velocity;
                 if( shove_destination != tripoint_zero ) {
                     if( shove_destination.z != 0 ) {
                         veh.vertical_velocity = shove_destination.z < 0 ? -shove_velocity : +shove_velocity;
                     }
                     here.move_vehicle( veh, shove_destination, veh.face );
                 }
                 veh.move = tileray( destination_delta.xy() );
                 veh.smash( here, shove_damage_min, shove_damage_max, 0.10F );
             }
         }
     }
 }
References _, add_msg_if_player_sees(), clamp(), vehicle::disp_name(), disp_name(), vehicle::face, get_map(), get_size(), has_flag(), huge, is_hallucination(), large, m_bad, max(), medium, Creature::mod_moves(), mon_flag_PUSH_VEH, vehicle::move, map::move_vehicle(), Creature::pos(), vehicle::skidding, small, vehicle::smash(), tiny, vehicle::total_mass(), tripoint_zero, map::veh_at(), vehicle::velocity, vehicle::vertical_velocity, tripoint::x, tripoint::xy(), tripoint::y, and tripoint::z.
Referenced by move().
sight_range()
int monster::sight_range (float light_level) const override virtual
How far the creature sees under the given light.
Creature cannot see places outside this range.
Parameters
light_level See game::light_level.
Implements Creature.
Definition at line 1285 of file monster.cpp.
 {
     // Non-aquatic monsters can't see much when submerged
     if( !can_see() || effect_cache[VISION_IMPAIRED] ||
         ( underwater && !swims() && !has_flag( mon_flag_AQUATIC ) && !digging() ) ) {
         return 1;
     }
     static const float default_daylight = default_daylight_level();
     if( light_level == 0 ) {
         return type->vision_night;
     } else if( light_level >= default_daylight ) {
         return type->vision_day;
     }
     int range = ( light_level * type->vision_day + ( default_daylight - light_level ) *
                   type->vision_night ) / default_daylight;
     return range;
 }
References can_see(), default_daylight_level(), digging(), effect_cache, has_flag(), mon_flag_AQUATIC, swims(), type, Creature::underwater, mtype::vision_day, VISION_IMPAIRED, and mtype::vision_night.
Referenced by get_path_avoid().
skin_name()
std::string monster::skin_name () const override virtual
Implements Creature.
Definition at line 784 of file monster.cpp.
 {
     return name_with_armor();
 }
References name_with_armor().
spawn() [1/2]
void monster::spawn (const tripoint & p)
Definition at line 705 of file monster.cpp.
 {
     set_pos_only( p );
     unset_dest();
 }
References Creature::set_pos_only(), and unset_dest().
Referenced by creature_tracker::swap_positions().
spawn() [2/2]
void monster::spawn (const tripoint_abs_ms & loc)
Definition at line 711 of file monster.cpp.
 {
     set_location( loc );
     unset_dest();
 }
References Creature::set_location(), and unset_dest().
spawn_dissectables_on_death()
void monster::spawn_dissectables_on_death (item * corpse)
Definition at line 3081 of file monster.cpp.
 {
     if( is_hallucination() ) {
         return;
     }
     if( type->dissect.is_empty() ) {
         return;
     }
     for( const harvest_entry &entry : *type->dissect ) {
         std::vector<item> dissectables = item_group::items_from( item_group_id( entry.drop ),
                                          calendar::turn,
                                          spawn_flags::use_spawn_rate );
         for( item &dissectable : dissectables ) {
             dissectable.dropped_from = entry.type;
             for( const flag_id &flg : entry.flags ) {
                 dissectable.set_flag( flg );
             }
             for( const fault_id &flt : entry.faults ) {
                 dissectable.faults.emplace( flt );
             }
             if( corpse ) {
                 corpse->put_in( dissectable, pocket_type::CORPSE );
             } else {
                 get_map().add_item_or_charges( pos(), dissectable );
             }
         }
     }
 }
References map::add_item_or_charges(), corpse, CORPSE, mtype::dissect, harvest_entry::drop, harvest_entry::faults, harvest_entry::flags, get_map(), string_id< T >::is_empty(), is_hallucination(), item_group_id, item_group::items_from(), Creature::pos(), calendar::turn, harvest_entry::type, type, and use_spawn_rate.
Referenced by die().
special_available()
bool monster::special_available (std::string_view special_name) const
Test whether the specified special is ready.
Definition at line 2606 of file monster.cpp.
 {
     std::map<std::string, mon_special_attack>::const_iterator iter = special_attacks.find(
                 special_name );
     return iter != special_attacks.end() && iter->second.enabled && iter->second.cooldown == 0;
 }
References special_attacks.
Referenced by behavior::monster_oracle_t::special_available().
speed_description()
std::string monster::speed_description (float mon_speed_rating, bool immobile = false, const speed_description_id & speed_desc = speed_description_id::NULL_ID()) static
Definition at line 835 of file monster.cpp.
 {
     if( speed_desc.is_null() || !speed_desc.is_valid() ) {
         return std::string();
     }
     const avatar &ply = get_avatar();
     double player_runcost = ply.run_cost( 100 );
     if( player_runcost <= 0.00 ) {
         player_runcost = 0.01f;
     }
     // tpt = tiles per turn
     const double player_tpt = ply.get_speed() / player_runcost;
     double ratio_tpt = player_tpt == 0.00 ?
                        100.00 : mon_speed_rating / player_tpt;
     ratio_tpt *= immobile ? 0.00 : 1.00;
     for( const speed_description_value &speed_value : speed_desc->values() ) {
         if( ratio_tpt >= speed_value.value() ) {
             return random_entry( speed_value.descriptions(), translation() ).translated();
         }
     }
     return std::string();
 }
References get_avatar(), Character::get_speed(), string_id< T >::is_null(), string_id< T >::is_valid(), random_entry(), Character::run_cost(), and speed_description::values().
Referenced by extended_description(), and print_info().
speed_rating()
float monster::speed_rating () const override virtual
Returns an approximate number of tiles this creature can travel per turn.
Implements Creature.
Definition at line 3662 of file monster.cpp.
 {
     float ret = get_speed() / 100.0f;
     const auto leap = type->special_attacks.find( "leap" );
     if( leap != type->special_attacks.end() ) {
         // TODO: Make this calculate sane values here
         ret += 0.5f;
     }
     return ret;
 }
References Creature::get_speed(), cata::hash64_detail::ret, mtype::special_attacks, and type.
Referenced by npc::evaluate_monster(), extended_description(), and print_info().
stability_roll()
float monster::stability_roll () const override virtual
Implements Creature.
Definition at line 2435 of file monster.cpp.
 {
     int size_bonus = 0;
     switch( type->size ) {
         case creature_size::tiny:
             size_bonus -= 7;
             break;
         case creature_size::small:
             size_bonus -= 3;
             break;
         case creature_size::large:
             size_bonus += 5;
             break;
         case creature_size::huge:
             size_bonus += 10;
             break;
         case creature_size::medium:
             break; // keep default
         case creature_size::num_sizes:
             debugmsg( "ERROR: Invalid Creature size class." );
             break;
     }
     int stability = dice( type->melee_sides, type->melee_dice ) + size_bonus;
     if( has_effect( effect_stunned ) ) {
         stability -= rng( 1, 5 );
     }
     return stability;
 }
References debugmsg, dice(), effect_stunned, Creature::has_effect(), huge, large, medium, mtype::melee_dice, mtype::melee_sides, num_sizes, rng(), mtype::size, Creature::size_bonus, small, tiny, and type.
Referenced by push_to().
store()
void monster::store (JsonOut & json) const protected
Definition at line 2605 of file savegame_json.cpp.
 {
     Creature::store( json );
     json.member( "typeid", type->id );
     json.member( "unique_name", unique_name );
     json.member( "nickname", nickname );
     json.member( "goal", goal );
     json.member( "wander_pos", wander_pos );
     json.member( "wandf", wandf );
     json.member( "provocative_sound", provocative_sound );
     if( !patrol_route.empty() ) {
         json.member( "patrol_route", patrol_route );
         json.member( "next_patrol_point", next_patrol_point );
     }
     json.member( "hp", hp );
     json.member( "special_attacks", special_attacks );
     json.member( "friendly", friendly );
     json.member( "fish_population", fish_population );
     json.member( "faction", faction.id().str() );
     json.member( "mission_ids", mission_ids );
     json.member( "mission_fused", mission_fused );
     json.member( "no_extra_death_drops", no_extra_death_drops );
     json.member( "dead", dead );
     json.member( "anger", anger );
     json.member( "morale", morale );
     json.member( "hallucination", hallucination );
     json.member( "aggro_character", aggro_character );
     if( tied_item ) {
         json.member( "tied_item", *tied_item );
     }
     if( tack_item ) {
         json.member( "tack_item", *tack_item );
     }
     if( armor_item ) {
         json.member( "armor_item", *armor_item );
     }
     if( storage_item ) {
         json.member( "storage_item", *storage_item );
     }
     if( battery_item ) {
         json.member( "battery_item", *battery_item );
     }
     json.member( "ammo", ammo );
     json.member( "underwater", underwater );
     json.member( "upgrades", upgrades );
     json.member( "upgrade_time", upgrade_time );
     json.member( "reproduces", reproduces );
     json.member( "baby_timer", baby_timer );
     json.member( "biosignatures", biosignatures );
     json.member( "biosig_timer", biosig_timer );
     json.member( "udder_timer", udder_timer );
     if( horde_attraction > MHA_NULL && horde_attraction < NUM_MONSTER_HORDE_ATTRACTION ) {
         json.member( "horde_attraction", horde_attraction );
     }
     json.member( "inv", inv );
     json.member( "dissectable_inv", dissectable_inv );
     json.member( "dragged_foe_id", dragged_foe_id );
     // storing the rider
     json.member( "mounted_player_id", mounted_player_id );
     // store grabbed limbs
     json.member( "grabbed_limbs", grabbed_limbs );
 }
References friendly, hp, faction_template::id, JsonOut::member(), MHA_NULL, spell_effect::morale(), NUM_MONSTER_HORDE_ATTRACTION, Creature::store(), string_id< T >::str(), and type.
stumble()
void monster::stumble ()
Stumble in a random direction, but with some caveats.
Definition at line 2233 of file monmove.cpp.
 {
     add_msg_debug( debugmode::DF_MONMOVE, "%s starting monmove::stumble", name() );
     // Only move every 10 turns.
     if( !one_in( 10 ) ) {
         return;
     }
     map &here = get_map();
     std::vector<tripoint> valid_stumbles;
     valid_stumbles.reserve( 11 );
     const bool avoid_water = has_flag( mon_flag_NO_BREATHE ) && !swims() &&
                              !has_flag( mon_flag_AQUATIC );
     for( const tripoint &dest : here.points_in_radius( pos(), 1 ) ) {
         if( dest != pos() ) {
             if( here.has_flag( ter_furn_flag::TFLAG_RAMP_DOWN, dest ) ) {
                 valid_stumbles.emplace_back( dest.xy(), dest.z - 1 );
             } else  if( here.has_flag( ter_furn_flag::TFLAG_RAMP_UP, dest ) ) {
                 valid_stumbles.emplace_back( dest.xy(), dest.z + 1 );
             } else {
                 valid_stumbles.push_back( dest );
             }
         }
     }
     const tripoint below( posx(), posy(), posz() - 1 );
     if( here.valid_move( pos(), below, false, true ) ) {
         valid_stumbles.push_back( below );
     }
     creature_tracker &creatures = get_creature_tracker();
     while( !valid_stumbles.empty() && !is_dead() ) {
         const tripoint dest = random_entry_removed( valid_stumbles );
         if( can_move_to( dest ) &&
             //Stop zombies and other non-breathing monsters wandering INTO water
             //(Unless they can swim/are aquatic)
             //But let them wander OUT of water if they are there.
             !( avoid_water &&
                here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, dest ) &&
                !here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, pos() ) ) &&
             ( creatures.creature_at( dest, is_hallucination() ) == nullptr ) ) {
             if( move_to( dest, true, false ) ) {
                 break;
             }
         }
     }
 }
References add_msg_debug, below, can_move_to(), creature_tracker::creature_at(), debugmode::DF_MONMOVE, get_creature_tracker(), get_map(), has_flag(), map::has_flag(), is_dead(), is_hallucination(), mon_flag_AQUATIC, mon_flag_NO_BREATHE, move_to(), name(), one_in(), map::points_in_radius(), Creature::pos(), Creature::posx(), Creature::posy(), Creature::posz(), random_entry_removed(), swims(), TFLAG_RAMP_DOWN, TFLAG_RAMP_UP, TFLAG_SWIMMABLE, and map::valid_move().
Referenced by mattack::dermatik(), move(), and trapfunc::tripwire().
swims()
bool monster::swims () const
Definition at line 1272 of file monster.cpp.
 {
     return has_flag( mon_flag_SWIMS );
 }
References has_flag(), and mon_flag_SWIMS.
Referenced by calc_movecost(), can_drown(), can_submerge(), extended_description(), move_to(), sight_range(), stumble(), and Character::swim_speed().
symbol()
const std::string & monster::symbol () const override virtual
Creature symbol.
Implements Creature.
Definition at line 1148 of file monster.cpp.
 {
     return type->sym;
 }
References mtype::sym, and type.
Referenced by anonymous_namespace{animation.cpp}::draw_hit_mon_curses().
symbol_color()
nc_color monster::symbol_color () const override virtual
Creature symbol background color.
Implements Creature.
Definition at line 1158 of file monster.cpp.
 {
     return color_with_effects();
 }
References color_with_effects().
to_item()
item monster::to_item () const
Convert this monster into an item (see mtype::revert_to_itype).
Only useful for robots and the like, the monster must have at least a non-empty item id as revert_to_itype.
Definition at line 3639 of file monster.cpp.
 {
     if( type->revert_to_itype.is_empty() ) {
         return item();
     }
     // Birthday is wrong, but the item created here does not use it anyway (I hope).
     item result( type->revert_to_itype, calendar::turn );
     const int damfac = std::max( 1, ( result.max_damage() + 1 ) * hp / type->hp );
     result.set_damage( std::max( 0, ( result.max_damage() + 1 ) - damfac ) );
     return result;
 }
References hp, mtype::hp, string_id< T >::is_empty(), item, max(), item::max_damage(), mtype::revert_to_itype, item::set_damage(), calendar::turn, and type.
Referenced by explosion_handler::emp_blast(), and disable_activity_actor::finish().
try_biosignature()
void monster::try_biosignature ()
Definition at line 672 of file monster.cpp.
 {
     if( is_hallucination() ) {
         return;
     }
     if( !biosignatures ) {
         return;
     }
     if( !type->biosig_timer ) {
         return;
     }
     if( has_effect( effect_critter_underfed ) ) {
         return;
     }
     if( !biosig_timer ) {
         biosig_timer.emplace( calendar::turn + *type->biosig_timer );
     }
     map &here = get_map();
     int counter = 0;
     while( true ) {
         // don't catch up too much, otherwise on some scenarios,
         // we could have years worth of poop just deposited on the floor.
         if( *biosig_timer > calendar::turn || counter > 50 ) {
             return;
         }
         here.add_item_or_charges( pos(), item( type->biosig_item, *biosig_timer, 1 ), true );
         *biosig_timer += *type->biosig_timer;
         counter += 1;
     }
 }
References map::add_item_or_charges(), mtype::biosig_item, biosig_timer, mtype::biosig_timer, biosignatures, effect_critter_underfed, get_map(), Creature::has_effect(), is_hallucination(), item, Creature::pos(), calendar::turn, and type.
Referenced by on_load(), and process_effects().
try_reproduce()
void monster::try_reproduce ()
Definition at line 547 of file monster.cpp.
 {
     if( !reproduces ) {
         return;
     }
     // This can happen if the monster type has changed (from reproducing to non-reproducing monster)
     if( !type->baby_timer ) {
         return;
     }
     if( !baby_timer && amount_eaten >= stomach_size ) {
         // Assume this is a freshly spawned monster (because baby_timer is not set yet), set the point when it reproduce to somewhere in the future.
         // Monsters need to have eaten eat to start their pregnancy timer, but that's all.
         baby_timer.emplace( calendar::turn + *type->baby_timer );
     }
     bool season_spawn = false;
     bool season_match = true;
     // only 50% of animals should reproduce
     bool female = one_in( 2 );
     for( const std::string &elem : type->baby_flags ) {
         if( elem == "SUMMER" || elem == "WINTER" || elem == "SPRING" || elem == "AUTUMN" ) {
             season_spawn = true;
         }
     }
     map &here = get_map();
     // add a decreasing chance of additional spawns when "catching up" an existing animal.
     int chance = -1;
     while( true ) {
         if( !baby_timer.has_value() || *baby_timer > calendar::turn ) {
             return;
         }
         if( season_spawn ) {
             season_match = false;
             for( const std::string &elem : type->baby_flags ) {
                 if( ( season_of_year( *baby_timer ) == SUMMER && elem == "SUMMER" ) ||
                     ( season_of_year( *baby_timer ) == WINTER && elem == "WINTER" ) ||
                     ( season_of_year( *baby_timer ) == SPRING && elem == "SPRING" ) ||
                     ( season_of_year( *baby_timer ) == AUTUMN && elem == "AUTUMN" ) ) {
                     season_match = true;
                 }
             }
         }
         chance += 2;
         if( has_flag( mon_flag_EATS ) && has_effect( effect_critter_underfed ) ) {
             chance += 1; //Reduce the chances but don't prevent birth if the animal is not eating.
         }
         if( season_match && female && one_in( chance ) ) {
             int spawn_cnt = rng( 1, type->baby_count );
             if( type->baby_monster ) {
                 here.add_spawn( type->baby_monster, spawn_cnt, pos_bub() );
             } else {
                 const item egg( type->baby_egg, *baby_timer );
                 for( int i = 0; i < spawn_cnt; i++ ) {
                     here.add_item_or_charges( pos(), egg, true );
                 }
             }
         }
         *baby_timer += *type->baby_timer;
     }
 }
References map::add_item_or_charges(), map::add_spawn(), amount_eaten, AUTUMN, mtype::baby_count, mtype::baby_egg, mtype::baby_flags, mtype::baby_monster, baby_timer, mtype::baby_timer, effect_critter_underfed, get_map(), Creature::has_effect(), has_flag(), mon_flag_EATS, one_in(), Creature::pos(), Creature::pos_bub(), reproduces, rng(), season_of_year(), SPRING, stomach_size, SUMMER, calendar::turn, type, and WINTER.
Referenced by on_load(), and process_effects().
try_upgrade()
void monster::try_upgrade (bool pin_time)
Definition at line 451 of file monster.cpp.
 {
     if( !can_upgrade() ) {
         return;
     }
     const int current_day = to_days<int>( calendar::turn - calendar::turn_zero );
     //This should only occur when a monster is created or upgraded to a new form
     if( upgrade_time < 0 ) {
         upgrade_time = next_upgrade_time();
         if( upgrade_time < 0 ) {
             return;
         }
         if( pin_time || type->age_grow > 0 ) {
             // offset by today, always true for growing creatures
             upgrade_time += current_day;
         } else {
             // offset by starting season
             // TODO: revisit this and make it simpler
             upgrade_time += to_days<int>( calendar::start_of_cataclysm - calendar::turn_zero );
         }
     }
     // Here we iterate until we either are before upgrade_time or can't upgrade any more.
     // This is so that late into game new monsters can 'catch up' with all that half-life
     // upgrades they'd get if we were simulating whole world.
     while( true ) {
         if( upgrade_time > current_day ) {
             // not yet
             return;
         }
         if( type->upgrade_into ) {
             //If we upgrade into a blacklisted monster, treat it as though we are non-upgradeable
             if( MonsterGroupManager::monster_is_blacklisted( type->upgrade_into ) ) {
                 return;
             }
             poly( type->upgrade_into );
         } else {
             mtype_id new_type;
             if( type->upgrade_multi_range ) {
                 bool ret_default = false;
                 std::vector<MonsterGroupResult> res = MonsterGroupManager::GetResultFromGroup(
                         type->upgrade_group, nullptr, nullptr, false, &ret_default );
                 if( !res.empty() && !ret_default ) {
                     // Set the type to poly the current monster (preserves inventory)
                     new_type = res.front().name;
                     res.front().pack_size--;
                     for( const MonsterGroupResult &mgr : res ) {
                         if( !mgr.name ) {
                             continue;
                         }
                         for( int i = 0; i < mgr.pack_size; i++ ) {
                             tripoint spawn_pos;
                             if( g->find_nearby_spawn_point( pos(), mgr.name, 1, *type->upgrade_multi_range,
                                                             spawn_pos, false, false ) ) {
                                 monster *spawned = g->place_critter_at( mgr.name, spawn_pos );
                                 if( spawned ) {
                                     spawned->friendly = friendly;
                                 }
                             }
                         }
                     }
                 }
             } else {
                 new_type = MonsterGroupManager::GetRandomMonsterFromGroup( type->upgrade_group );
             }
             if( !new_type.is_empty() ) {
                 if( new_type ) {
                     poly( new_type );
                 } else {
                     // "upgrading" to mon_null
                     if( type->upgrade_null_despawn ) {
                         g->remove_zombie( *this );
                     } else {
                         die( nullptr );
                     }
                     return;
                 }
             }
         }
         if( !upgrades ) {
             // upgraded into a non-upgradeable monster
             return;
         }
         const int next_upgrade = next_upgrade_time();
         if( next_upgrade < 0 ) {
             // hit never_upgrade
             return;
         }
         upgrade_time += next_upgrade;
     }
 }
References mtype::age_grow, can_upgrade(), die(), friendly, g, MonsterGroupManager::GetRandomMonsterFromGroup(), MonsterGroupManager::GetResultFromGroup(), string_id< T >::is_empty(), MonsterGroupManager::monster_is_blacklisted(), next_upgrade_time(), poly(), Creature::pos(), calendar::start_of_cataclysm, calendar::turn, calendar::turn_zero, type, mtype::upgrade_group, mtype::upgrade_into, mtype::upgrade_multi_range, mtype::upgrade_null_despawn, upgrade_time, and upgrades.
Referenced by mattack::evolve_kill_strike(), on_load(), process_effects(), spell_effect::upgrade(), and mattack::upgrade().
turns_to_reach()
int monster::turns_to_reach (const point & p)
Definition at line 2399 of file monmove.cpp.
 {
     map &here = get_map();
     // HACK: This function is a(n old) temporary hack that should soon be removed
     auto path = here.route( pos(), tripoint( p, posz() ), get_pathfinding_settings() );
     if( path.empty() ) {
         return 999;
     }
     double turns = 0.;
     for( size_t i = 0; i < path.size(); i++ ) {
         const tripoint &next = path[i];
         if( here.impassable( next ) ) {
             // No bashing through, it looks stupid when you go back and find
             // the doors intact.
             return 999;
         } else if( i == 0 ) {
             turns += static_cast<double>( calc_movecost( pos(), next ) ) / get_speed();
         } else {
             turns += static_cast<double>( calc_movecost( path[i - 1], next ) ) / get_speed();
         }
     }
     return static_cast<int>( turns + .9 ); // Halve (to get turns) and round up
 }
References calc_movecost(), get_map(), get_pathfinding_settings(), Creature::get_speed(), map::impassable(), path, Creature::pos(), Creature::posz(), map::route(), and tripoint.
unset_dest()
void monster::unset_dest ()
Definition at line 1388 of file monster.cpp.
 {
     goal = std::nullopt;
     path.clear();
 }
References goal, and path.
Referenced by spell_effect::charm_monster(), make_friendly(), monster(), move(), spawn(), and anonymous_namespace{monexamine.cpp}::start_leading().
use_mech_power()
units::energy monster::use_mech_power (units::energy amt)
Consume UPS from mech battery.
Parameters
amt amount of energy to consume. Is rounded down to kJ precision. Do not use negative values.
Returns
Actual amount of energy consumed
Definition at line 2959 of file monster.cpp.
 {
     if( is_hallucination() || !has_flag( mon_flag_RIDEABLE_MECH ) || !battery_item ) {
         return 0_kJ;
     }
     const int max_drain = battery_item->ammo_remaining();
     const int consumption = std::min( static_cast<int>( units::to_kilojoule( amt ) ), max_drain );
     battery_item->ammo_consume( consumption, pos(), nullptr );
     return units::from_kilojoule( static_cast<std::int64_t>( consumption ) );
 }
References battery_item, units::from_kilojoule(), has_flag(), is_hallucination(), min(), mon_flag_RIDEABLE_MECH, Creature::pos(), and units::to_kilojoule().
Referenced by smash(), mattack::smash_specific(), and game::vertical_move().
wander_to()
void monster::wander_to (const tripoint_abs_ms & p, int f)
Set p as wander destination.
This will cause the monster to slowly move towards the destination, unless there is an overriding smell or plan.
Parameters
p Destination of monster's wanderings
f The priority of the destination, as well as how long we should wander towards there.
Definition at line 1399 of file monster.cpp.
 {
     wander_pos = p;
     wandf = f;
 }
References wander_pos, and wandf.
Referenced by hear_sound(), and map::spawn_monsters_submap_group().
weakpoint_skill()
float monster::weakpoint_skill () const
Definition at line 72 of file weakpoint.cpp.
 {
     return type->melee_skill;
 }
References mtype::melee_skill, and type.
Referenced by weakpoint_attack::compute_wp_skill().
weight_capacity()
units::mass monster::weight_capacity () const override virtual
Reimplemented from Creature.
Definition at line 3513 of file monster.cpp.
 {
     return type->weight * type->mountable_weight_ratio;
 }
References mtype::mountable_weight_ratio, type, and mtype::weight.
Referenced by anonymous_namespace{monexamine.cpp}::add_armor(), anonymous_namespace{monexamine.cpp}::attach_bag_to(), anonymous_namespace{monexamine.cpp}::give_items_to(), and stash_on_pet().
will_join_horde()
bool monster::will_join_horde (int size)
Definition at line 3831 of file monster.cpp.
 {
     const monster_horde_attraction mha = get_horde_attraction();
     if( this->has_flag( mon_flag_IMMOBILE ) || this->has_flag( mon_flag_NEVER_WANDER ) ) {
         return false; //immobile monsters should never join a horde. Same with Never Wander monsters.
     }
     if( mha == MHA_NEVER ) {
         return false;
     }
     if( mha == MHA_ALWAYS ) {
         return true;
     }
     if( get_map().has_flag( ter_furn_flag::TFLAG_INDOORS, pos() ) &&
         ( mha == MHA_OUTDOORS || mha == MHA_OUTDOORS_AND_LARGE ) ) {
         return false;
     }
     if( size < 3 && ( mha == MHA_LARGE || mha == MHA_OUTDOORS_AND_LARGE ) ) {
         return false;
     }
     return true;
 }
References get_horde_attraction(), get_map(), has_flag(), MHA_ALWAYS, MHA_LARGE, MHA_NEVER, MHA_OUTDOORS, MHA_OUTDOORS_AND_LARGE, mon_flag_IMMOBILE, mon_flag_NEVER_WANDER, Creature::pos(), om_direction::size, and TFLAG_INDOORS.
Referenced by overmap::move_hordes().
will_move_to()
bool monster::will_move_to (const tripoint & p) const
Definition at line 193 of file monmove.cpp.
 {
     map &here = get_map();
     if( here.impassable( p ) ) {
         if( digging() ) {
             if( !here.has_flag( ter_furn_flag::TFLAG_BURROWABLE, p ) ) {
                 return false;
             }
         } else if( !( can_climb() && here.has_flag( ter_furn_flag::TFLAG_CLIMBABLE, p ) ) ) {
             return false;
         }
     }
     if( !here.has_vehicle_floor( p ) ) {
         if( !can_submerge() && !flies() && here.has_flag( ter_furn_flag::TFLAG_DEEP_WATER, p ) ) {
             return false;
         }
     }
     if( digs() && !here.has_flag( ter_furn_flag::TFLAG_DIGGABLE, p ) &&
         !here.has_flag( ter_furn_flag::TFLAG_BURROWABLE, p ) ) {
         return false;
     }
     if( has_flag( mon_flag_AQUATIC ) && (
             !here.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, p ) ||
             // AQUATIC (confined to water) monster avoid vehicles, unless they are already underneath one
             ( here.veh_at( p ) && !here.veh_at( pos() ) )
         ) ) {
         return false;
     }
     if( has_flag( mon_flag_SUNDEATH ) && g->is_in_sunlight( p ) ) {
         return false;
     }
     if( get_size() > creature_size::medium &&
         here.has_flag_ter( ter_furn_flag::TFLAG_SMALL_PASSAGE, p ) ) {
         return false; // if a large critter, can't move through tight passages
     }
     return true;
 }
References can_climb(), can_submerge(), digging(), digs(), flies(), g, get_map(), get_size(), has_flag(), map::has_flag(), map::has_flag_ter(), map::has_vehicle_floor(), map::impassable(), medium, mon_flag_AQUATIC, mon_flag_SUNDEATH, Creature::pos(), TFLAG_BURROWABLE, TFLAG_CLIMBABLE, TFLAG_DEEP_WATER, TFLAG_DIGGABLE, TFLAG_SMALL_PASSAGE, TFLAG_SWIMMABLE, and map::veh_at().
Referenced by leap_actor::call(), can_move_to(), and can_place_monster().
will_reach()
bool monster::will_reach (const point & p)
Definition at line 2361 of file monmove.cpp.
 {
     monster_attitude att = attitude( &get_player_character() );
     if( att != MATT_FOLLOW && att != MATT_ATTACK && att != MATT_FRIEND ) {
         return false;
     }
     if( digs() || has_flag( mon_flag_AQUATIC ) ) {
         return false;
     }
     if( ( has_flag( mon_flag_IMMOBILE ) || has_flag( mon_flag_RIDEABLE_MECH ) ) &&
         ( pos().xy() != p ) ) {
         return false;
     }
     auto path = get_map().route( pos(), tripoint( p, posz() ), get_pathfinding_settings() );
     if( path.empty() ) {
         return false;
     }
     if( has_flag( mon_flag_SMELLS ) && get_scent().get( pos() ) > 0 &&
         get_scent().get( { p, posz() } ) > get_scent().get( pos() ) ) {
         return true;
     }
     if( can_hear() && wandf > 0 && rl_dist( get_map().getlocal( wander_pos ).xy(), p ) <= 2 &&
         rl_dist( get_location().xy(), wander_pos.xy() ) <= wandf ) {
         return true;
     }
     if( can_see() && sees( tripoint( p, posz() ) ) ) {
         return true;
     }
     return false;
 }
References attitude(), can_hear(), can_see(), digs(), scent_map::get(), rotatable_symbols::get(), Creature::get_location(), get_map(), get_pathfinding_settings(), get_player_character(), get_scent(), has_flag(), MATT_ATTACK, MATT_FOLLOW, MATT_FRIEND, mon_flag_AQUATIC, mon_flag_IMMOBILE, mon_flag_RIDEABLE_MECH, mon_flag_SMELLS, path, Creature::pos(), Creature::posz(), rl_dist(), map::route(), Creature::sees(), tripoint, wander_pos, wandf, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
witness_thievery()
void monster::witness_thievery (item * it) override virtual
Implements Creature.
Definition at line 1420 of file monster.cpp.
 {
     add_msg( m_bad, _( "%1$s saw the %2$s being stolen!" ), get_name(), it->tname() );
     std::vector<npc *> friends;
     for( npc &guy : g->all_npcs() ) {
         if( guy.get_faction() && guy.get_faction()->mon_faction == faction.id() ) {
             friends.push_back( &guy );
         }
     }
     if( friends.empty() ) {
         aggro_character = true;
         anger = 100;
         return;
     }
     std::sort( friends.begin(), friends.end(), npc::theft_witness_compare );
     friends[0]->witness_thievery( it );
 }
References _, add_msg(), aggro_character, anger, g, get_name(), faction_template::id, m_bad, npc::theft_witness_compare(), and item::tname().
Friends And Related Function Documentation
editmap
friend class editmap friend
Definition at line 87 of file monster.h.
Member Data Documentation
aggro_character
bool monster::aggro_character = true
Definition at line 572 of file monster.h.
Referenced by anger_cub_threatened(), anger_hostile_seen(), anger_mating_season(), apply_damage(), attitude(), gun_actor::call(), extended_description(), monster(), on_load(), plan(), poly(), process_triggers(), and witness_thievery().
ammo
std::map<itype_id, int> monster::ammo
Definition at line 582 of file monster.h.
Referenced by mdeath::broken(), explosion_handler::emp_blast(), milk_activity_actor::finish(), disable_activity_actor::finish(), mattack::frag(), grenade_helper(), mattack::kamikaze(), anonymous_namespace{monexamine.cpp}::milk_source(), move_to(), mattack::nurse_operate(), refill_udders(), game::revive_corpse(), mattack::rifle(), mattack::science(), gun_actor::shoot(), map::spawn_monsters_submap(), mattack::tankgun(), Character::uninstall_bionic(), and place_monster_iuse::use().
amount_eaten
int monster::amount_eaten = 0
Definition at line 543 of file monster.h.
Referenced by mattack::browse(), digest_food(), mattack::eat_carrion(), mattack::eat_crop(), mattack::eat_food(), mattack::graze(), monexamine::mfriend_menu(), on_load(), monexamine::pet_menu(), process_effects(), reset_digestion(), and try_reproduce().
anger
int monster::anger = 0
Definition at line 540 of file monster.h.
Referenced by anger_cub_threatened(), anger_hostile_seen(), anger_mating_season(), attitude(), attitude_to(), mattack::copbot(), extended_description(), mattack::fungus_inject(), talker_monster_const::get_anger(), grenade_helper(), hear_sound(), is_fleeing(), monster(), mattack::nurse_operate(), on_load(), plan(), poly(), process_effects(), process_trigger(), process_triggers(), mattack::resurrect(), mattack::riotbot(), talker_monster::set_anger(), mattack::upgrade(), and witness_thievery().
armor_item
cata::value_ptr<item> monster::armor_item
Definition at line 531 of file monster.h.
Referenced by anonymous_namespace{monexamine.cpp}::add_armor(), die(), get_carried_weight(), get_worn_armor_val(), monster(), and anonymous_namespace{monexamine.cpp}::remove_armor().
baby_timer
std::optional<time_point> monster::baby_timer private
Definition at line 625 of file monster.h.
Referenced by extended_description(), and try_reproduce().
battery_item
cata::value_ptr<item> monster::battery_item
Definition at line 533 of file monster.h.
Referenced by check_mech_powered(), anonymous_namespace{monexamine.cpp}::insert_battery(), monster(), monexamine::pet_menu(), anonymous_namespace{monexamine.cpp}::remove_battery(), and use_mech_power().
biosig_timer
std::optional<time_point> monster::biosig_timer private
Definition at line 627 of file monster.h.
Referenced by extended_description(), monster(), and try_biosignature().
biosignatures
bool monster::biosignatures = false private
Definition at line 626 of file monster.h.
Referenced by extended_description(), monster(), poly(), and try_biosignature().
dead
bool monster::dead = false private
Definition at line 619 of file monster.h.
Referenced by die(), is_dead(), and monster().
death_drops
bool monster::death_drops = true
Definition at line 556 of file monster.h.
Referenced by die(), monster(), mdeath::normal(), and mattack::zombie_fuse().
dissectable_inv
std::vector<item> monster::dissectable_inv
Definition at line 525 of file monster.h.
Referenced by die(), and init_from_item().
dragged_foe_id
character_id monster::dragged_foe_id
Definition at line 528 of file monster.h.
Referenced by find_dragged_foe(), mattack::nurse_operate(), and nursebot_operate().
effect_cache
std::bitset<NUM_MEFF> monster::effect_cache private
Definition at line 654 of file monster.h.
Referenced by attitude(), can_see(), is_fleeing(), move_effects(), movement_impaired(), process_one_effect(), reset_bonuses(), and sight_range().
enchantment_cache
pimpl<enchant_cache> monster::enchantment_cache
Definition at line 576 of file monster.h.
Referenced by calculate_by_enchantment(), and process_one_effect().
faction
mfaction_id monster::faction
Definition at line 545 of file monster.h.
Referenced by attitude_to(), effect_source::effect_source(), item::is_owned_by(), make_ally(), plan(), process_effects(), and mattack::zombie_fuse().
fish_population
int monster::fish_population = 1
Definition at line 569 of file monster.h.
Referenced by iuse::fish_trap_tick(), monster(), and rod_fish().
friendly
int monster::friendly = 0
Definition at line 539 of file monster.h.
Referenced by anonymous_namespace{math_parser_diag.cpp}::_matches_attitude_filter(), Character::activate_mutation(), add_summoned_mon(), attitude(), Character::attitude_to(), attitude_to(), mattack::blow_whistle(), mattack::brandish(), mattack::browse(), talker_avatar::buy_monster(), gun_actor::call(), mattack::callblobs(), disable_activity_actor::can_disable_or_reprogram(), Character::can_mount(), iuse::capture_monster_act(), spell_effect::charm_monster(), mattack::check_money_left(), mattack::chickenbot(), mattack::darkman(), iuse::directional_hologram(), mattack::dogthing(), mattack::eat_food(), extended_description(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), game::find_or_make_stairs(), mattack::flamethrower(), mattack::formblob(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), talker_monster_const::get_friendly(), mattack::graze(), mattack::grow_vine(), hear_sound(), mattack::howl(), is_pet(), is_symbol_highlighted(), magical_polymorph(), make_ally(), make_fake_npc(), make_friendly(), monexamine::mech_hack(), monster(), monster_plan::monster_plan(), move(), avatar_action::move(), move_effects(), mattack::multi_robot(), mattack::nurse_operate(), monexamine::pay_bot(), mattack::photograph(), plan(), process_effects(), mattack::ratking(), mattack::rattle(), wish_monster_callback::refresh(), iuse::robotcontrol_can_target(), talker_monster::set_friendly(), gun_actor::shoot(), map::spawn_monsters_submap(), mattack::triffid_heartbeat(), try_upgrade(), place_monster_iuse::use(), vehicle::use_harness(), Character::valid_aoe_technique(), game::vertical_move(), iuse::vortex(), debug_menu::wishmonster(), and mission::wrap_up().
goal
std::optional<tripoint_abs_ms> monster::goal private
Definition at line 618 of file monster.h.
Referenced by get_dest(), has_dest(), set_dest(), and unset_dest().
grabbed_limbs
std::unordered_set<bodypart_str_id> monster::grabbed_limbs
Definition at line 519 of file monster.h.
Referenced by add_grab(), is_grabbing(), and remove_grab().
hallucination
bool monster::hallucination = false
Definition at line 567 of file monster.h.
Referenced by is_hallucination(), monster(), and debug_menu::wishmonster().
horde_attraction
monster_horde_attraction monster::horde_attraction = MHA_NULL private
Definition at line 630 of file monster.h.
Referenced by get_horde_attraction(), monster(), and set_horde_attraction().
hp
int monster::hp = 0 private
Definition at line 616 of file monster.h.
Referenced by apply_damage(), die_in_explosion(), explode(), extended_description(), get_hp(), get_HP_Bar(), heal(), init_from_item(), is_dead_state(), monster(), on_load(), poly(), process_effects(), set_hp(), and to_item().
ignoring
short monster::ignoring = 0
Definition at line 571 of file monster.h.
Referenced by game::do_regular_action(), game::mon_info_update(), and monster().
inv
std::vector<item> monster::inv
Definition at line 524 of file monster.h.
Referenced by add_item(), mattack::check_money_left(), die(), anonymous_namespace{monexamine.cpp}::dump_items(), generate_inventory(), get_carried_volume(), get_carried_weight(), init_from_item(), name_with_armor(), monexamine::pet_menu(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), and mattack::searchlight().
lastseen_turn
std::optional<time_point> monster::lastseen_turn
Definition at line 574 of file monster.h.
Referenced by game::mon_info_update().
made_footstep
bool monster::made_footstep = false
Definition at line 560 of file monster.h.
Referenced by footsteps(), and monster().
mission_fused
std::vector<std::string> monster::mission_fused
Definition at line 549 of file monster.h.
Referenced by extended_description(), name(), print_info(), and mattack::zombie_fuse().
mission_ids
std::set<int> monster::mission_ids
Definition at line 547 of file monster.h.
Referenced by mission::is_complete(), overmap::move_hordes(), mission::on_creature_death(), mission::on_creature_fusion(), map::spawn_monsters_submap(), and mission::wrap_up().
morale
int monster::morale = 0
Definition at line 541 of file monster.h.
Referenced by anger_cub_threatened(), attitude(), attitude_to(), extended_description(), hear_sound(), is_fleeing(), monster(), monster_plan::monster_plan(), talker_monster_const::morale_cur(), on_load(), plan(), poly(), process_effects(), process_trigger(), process_triggers(), talker_monster::set_morale(), and mission::wrap_up().
mounted_player
Character* monster::mounted_player = nullptr
Definition at line 526 of file monster.h.
Referenced by Creature::add_effect(), Character::add_msg_player_or_say(), Creature::deal_melee_hit(), die(), npc::die(), Character::dismount(), trapfunc::dissector(), print_info(), and game::vertical_move().
mounted_player_id
character_id monster::mounted_player_id
Definition at line 527 of file monster.h.
Referenced by npc::die(), Character::dismount(), and Character::mount_creature().
next_patrol_point
int monster::next_patrol_point = -1 private
Definition at line 652 of file monster.h.
Referenced by plan(), and set_patrol_route().
nickname
std::string monster::nickname
Definition at line 566 of file monster.h.
Referenced by game::look_around(), name(), and mattack::tindalos_teleport().
no_corpse_quiet
bool monster::no_corpse_quiet = false
Definition at line 554 of file monster.h.
Referenced by add_summoned_mon(), mdeath::broken(), game::catch_a_monster(), mattack::depart(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), mdeath::normal(), and mattack::photograph().
no_extra_death_drops
bool monster::no_extra_death_drops = false
Definition at line 552 of file monster.h.
Referenced by add_summoned_mon(), mattack::depart(), die(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), generate_inventory(), monster(), mattack::photograph(), poly(), and game::revive_corpse().
path
std::vector<tripoint> monster::path private
Found path.
Note: Not used by monsters that don't pathfind!
Definition at line 632 of file monster.h.
Referenced by move(), shift(), turns_to_reach(), unset_dest(), and will_reach().
pathfinding_backoff
time_duration monster::pathfinding_backoff = 2_seconds private
Definition at line 636 of file monster.h.
Referenced by increment_pathfinding_cd(), and reset_pathfinding_cd().
pathfinding_cd
time_point monster::pathfinding_cd = calendar::turn private
Definition at line 635 of file monster.h.
Referenced by can_pathfind(), increment_pathfinding_cd(), and reset_pathfinding_cd().
patrol_route
std::vector<tripoint_abs_ms> monster::patrol_route private
patrol points for monsters that can pathfind and have a patrol route!
Definition at line 651 of file monster.h.
Referenced by is_wandering(), move(), plan(), and set_patrol_route().
provocative_sound
bool monster::provocative_sound = false
Definition at line 522 of file monster.h.
Referenced by hear_sound(), and move().
quiet_death
bool monster::quiet_death = false
Definition at line 558 of file monster.h.
Referenced by mdeath::normal(), and mattack::zombie_fuse().
reproduces
bool monster::reproduces = false private
Definition at line 624 of file monster.h.
Referenced by extended_description(), monster(), poly(), and try_reproduce().
special_attacks
std::map<std::string, mon_special_attack, std::less<> > monster::special_attacks private
Definition at line 617 of file monster.h.
Referenced by disable_special(), extended_description(), has_special(), monster(), move(), on_load(), poly(), process_turn(), set_special(), and special_available().
staircount
int monster::staircount = 0
Definition at line 579 of file monster.h.
stomach_size
int monster::stomach_size = 0
Definition at line 542 of file monster.h.
Referenced by mattack::browse(), digest_food(), mattack::eat_carrion(), mattack::eat_crop(), mattack::eat_food(), mattack::graze(), monexamine::mfriend_menu(), monster(), monexamine::pet_menu(), and try_reproduce().
stomach_timer
time_point monster::stomach_timer private
Definition at line 629 of file monster.h.
Referenced by digest_food(), monster(), and reset_digestion().
storage_item
cata::value_ptr<item> monster::storage_item
Definition at line 532 of file monster.h.
Referenced by anonymous_namespace{monexamine.cpp}::attach_bag_to(), die(), get_carried_weight(), anonymous_namespace{monexamine.cpp}::give_items_to(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), and stash_on_pet().
tack_item
cata::value_ptr<item> monster::tack_item
Definition at line 530 of file monster.h.
Referenced by anonymous_namespace{monexamine.cpp}::attach_saddle_to(), die(), get_carried_weight(), monster(), and anonymous_namespace{monexamine.cpp}::remove_saddle_from().
tied_item
cata::value_ptr<item> monster::tied_item
Definition at line 529 of file monster.h.
Referenced by anonymous_namespace{monexamine.cpp}::add_leash(), projectile::apply_effects_damage(), die(), monster(), Character::mount_creature(), move_effects(), anonymous_namespace{monexamine.cpp}::remove_leash(), and vehicle::use_harness().
turns_since_target
int monster::turns_since_target = 0 private
Definition at line 655 of file monster.h.
Referenced by plan().
type
const mtype* monster::type
Definition at line 550 of file monster.h.
Referenced by absorb_hit(), mattack::absorb_items(), mattack::acid_barf(), creature_tracker::add(), anger_cub_threatened(), Creature::attack_air(), attack_at(), attitude(), avoid_trap(), bash_skill(), basic_symbol_color(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), bloodType(), talker_monster_const::bodytype(), mattack::breathe(), mdeath::broken(), melee_actor::call(), iuse::camera(), can_attack_high(), disable_activity_actor::can_disable_or_reprogram(), Character::can_wield(), iuse::capture_monster_act(), game::catch_a_monster(), game::chat(), check_mech_powered(), color_with_effects(), weakpoint_attack::compute_wp_skill(), item::contain_monster(), mattack::copbot(), trapfunc::crossbow(), deal_projectile_attack(), mattack::dermatik(), die(), game::disable_robot(), mdeath::disappear(), Character::dismount(), trapfunc::dissector(), anonymous_namespace{animation.cpp}::draw_hit_mon_curses(), drop_items_on_death(), mattack::eat_food(), iuse::einktabletpc(), explosion_handler::emp_blast(), npc::evaluate_monster(), mattack::evolve_kill_strike(), game::examine(), extended_description(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), fall_damage_mod(), milk_activity_actor::finish(), shearing_activity_actor::finish(), iuse::fish_trap_tick(), mattack::flesh_golem(), mattack::flesh_tendril(), game::fling_creature(), footsteps(), game::forced_door_closing(), mattack::formblob(), mattack::frag(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), generate_inventory(), get_absorb_material(), get_armor_type(), get_dodge_base(), get_eff_per(), get_grab_strength(), get_hit_base(), get_HP_Bar(), get_hp_max(), get_melee(), get_mountable_weight_ratio(), get_no_absorb_material(), get_pathfinding_settings(), get_size(), talker_monster_const::get_topics(), get_volume(), get_weight(), gibType(), trapfunc::goo(), iuse::granade_act(), spell_effect::guilt(), gunmode_checks_weapon(), item::handle_pickup_ownership(), has_flag(), has_vine_parent(), hasten_upgrade(), heal(), mattack::howl(), in_species(), init_from_item(), is_immune_damage(), is_immune_effect(), is_immune_field(), Creature::is_ranged_attacker(), knock_back_to(), know_danger_at(), mattack::lunge(), made_of(), made_of_any(), magical_polymorph(), make_bleed(), make_fungus(), make_mon_corpse(), mating_angry(), mech_str_addition(), melee_attack(), Character::melee_attack_abstract(), monexamine::mfriend_menu(), anonymous_namespace{monexamine.cpp}::milk_source(), anonymous_namespace{math_parser_diag.cpp}::mon_check_group(), anonymous_namespace{math_parser_diag.cpp}::mon_check_id(), game::mon_info_update(), monster(), map::monster_in_field(), monster_move_in_vehicle(), monster_plan::monster_plan(), Character::mount_creature(), move(), move_effects(), overmap::move_hordes(), move_to(), name(), next_upgrade_time(), mdeath::normal(), mattack::nurse_operate(), nursebot_operate(), on_hit(), on_load(), anonymous_namespace{monexamine.cpp}::pet_armor_loc(), monexamine::pet_menu(), photo_def_for_camera_point(), mattack::photograph(), plan(), anonymous_namespace{monexamine.cpp}::play_with(), poly(), print_info(), process_effects(), process_trigger(), process_triggers(), process_turn(), rate_critter(), refill_udders(), wish_monster_callback::refresh(), reset_special(), reset_special_rng(), mattack::resurrect(), mdefense::return_fire(), mattack::riotbot(), iuse::robotcontrol_can_target(), rod_fish(), scent_move(), mattack::searchlight(), Creature::sees(), shearable(), talker_monster_const::short_description(), trapfunc::shotgun(), sight_range(), spell_effect::slime_split_on_death(), mattack::smash(), trapfunc::snare_heavy(), spawn_dissectables_on_death(), map::spawn_monsters_submap(), speed_rating(), mdeath::splatter(), mattack::split(), stability_roll(), mattack::stretch_attack(), symbol(), to_item(), try_biosignature(), try_reproduce(), try_upgrade(), mattack::upgrade(), place_monster_iuse::use(), vehicle::use_harness(), weakpoint_skill(), and weight_capacity().
udder_timer
time_point monster::udder_timer private
Definition at line 628 of file monster.h.
Referenced by monster(), and refill_udders().
unique_name
std::string monster::unique_name
Definition at line 564 of file monster.h.
Referenced by talker_avatar::buy_monster(), shearing_activity_actor::finish(), make_mon_corpse(), name(), anonymous_namespace{monexamine.cpp}::rename_pet(), map::spawn_monsters_submap(), mdeath::splatter(), and shearing_activity_actor::start().
upgrade_time
int monster::upgrade_time = 0 private
Definition at line 623 of file monster.h.
Referenced by allow_upgrade(), extended_description(), get_upgrade_time(), hasten_upgrade(), init_from_item(), monster(), and try_upgrade().
upgrades
bool monster::upgrades = false private
Definition at line 622 of file monster.h.
Referenced by can_upgrade(), monster(), next_upgrade_time(), poly(), and try_upgrade().
wander_pos
tripoint_abs_ms monster::wander_pos
Definition at line 521 of file monster.h.
Referenced by move(), plan(), map::spawn_monsters_submap_group(), wander_to(), and will_reach().
wandf
int monster::wandf = 0
Definition at line 523 of file monster.h.
Referenced by iuse::directional_hologram(), hear_sound(), monster(), move(), plan(), wander_to(), and will_reach().
The documentation for this class was generated from the following files:
src/monster.h
src/monmove.cpp
src/monster.cpp
src/savegame_json.cpp
src/weakpoint.cpp