Cataclysm DDA: dialogue_window Class Reference
dialogue_window Class Reference
NPC conversation dialogue window.
#include <dialogue_win.h>
Classes
struct history_message
Public Member Functions
dialogue_window ()
void resize (ui_adaptor &ui)
void draw (const std::string &npc_name)
void handle_scrolling (std::string &action, input_context &ctxt)
void add_to_history (const std::string &text)
Adds a message to the conversation history.
void add_to_history (const std::string &text, const std::string &speaker_name, nc_color speaker_color)
Adds a message to the conversation history for a given speaker.
void add_history_separator ()
Adds a separator to the conversation history.
void set_responses (const std::vector< talk_data > &responses)
void set_up_scrolling (input_context &ctxt) const
void clear_history_highlights ()
Unhighlights all messages.
Public Attributes
bool is_computer = false
bool is_not_conversation = false
int sel_response = 0
Private Member Functions
void add_to_history (const std::string &text, nc_color color)
nc_color default_color () const
void print_header (const std::string &name) const
Private Attributes
catacurses::window d_win
catacurses::window history_win
catacurses::window resp_win
std::vector< history_message > history
This contains the exchanged words, it is basically like the global message log.
std::unique_ptr< scrolling_text_view > history_view
bool update_history_view = true
int num_lines_highlighted
Number of history messages to highlight.
std::vector< std::tuple< std::string, std::vector< std::string > > > folded_txt
Stored responses (hotkey, lines)
std::vector< int > folded_heights
std::unique_ptr< multiline_list > responses_list
Detailed Description
NPC conversation dialogue window.
Definition at line 27 of file dialogue_win.h.
Constructor & Destructor Documentation
dialogue_window()
dialogue_window::dialogue_window ()
Definition at line 23 of file dialogue_win.cpp.
 {
     responses_list = std::make_unique<multiline_list>( resp_win );
     history_view = std::make_unique<scrolling_text_view>( history_win );
 }
References history_view, history_win, resp_win, and responses_list.
Member Function Documentation
add_history_separator()
void dialogue_window::add_history_separator ()
Adds a separator to the conversation history.
Definition at line 142 of file dialogue_win.cpp.
 {
     add_to_history( "", default_color() );
 }
References add_to_history(), and default_color().
Referenced by dialogue::opt().
add_to_history() [1/3]
void dialogue_window::add_to_history (const std::string & text)
Adds a message to the conversation history.
Definition at line 130 of file dialogue_win.cpp.
 {
     add_to_history( text, default_color() );
 }
References default_color().
Referenced by add_history_separator(), add_to_history(), and dialogue::opt().
add_to_history() [2/3]
void dialogue_window::add_to_history (const std::string & text, const std::string & speaker_name, nc_color speaker_color)
Adds a message to the conversation history for a given speaker.
Definition at line 123 of file dialogue_win.cpp.
 {
     add_to_history( speaker_name, speaker_color );
     add_to_history( text );
 }
References add_to_history().
add_to_history() [3/3]
void dialogue_window::add_to_history (const std::string & text, nc_color color) private
Definition at line 135 of file dialogue_win.cpp.
 {
     history.emplace_back( color, text );
     ++num_lines_highlighted;
     update_history_view = true;
 }
References color(), history, num_lines_highlighted, and update_history_view.
clear_history_highlights()
void dialogue_window::clear_history_highlights ()
Unhighlights all messages.
Definition at line 147 of file dialogue_win.cpp.
 {
     num_lines_highlighted = 0;
 }
References num_lines_highlighted.
Referenced by dialogue::opt().
default_color()
nc_color dialogue_window::default_color () const private
Definition at line 152 of file dialogue_win.cpp.
 {
     return is_computer ? c_green : c_white;
 }
References c_green, c_white, and is_computer.
Referenced by add_history_separator(), add_to_history(), and print_header().
draw()
void dialogue_window::draw (const std::string & npc_name)
Definition at line 47 of file dialogue_win.cpp.
 {
     werase( d_win );
     print_header( npc_name );
     int ycurrent = getmaxy( d_win ) - 1 - RESPONSES_LINES + 1;
     const int xmid = getmaxx( d_win ) / 2;
     // Actions go on the right column; they're unaffected by scrolling.
     input_context ctxt( "DIALOGUE_CHOOSE_RESPONSE" );
     if( !is_computer && !is_not_conversation ) {
         const int actions_xoffset = xmid + 2;
         nc_color cur_color = c_magenta;
         std::string formatted_text = formatted_hotkey( ctxt.get_desc( "LOOK_AT", 1 ),
                                      cur_color ).append( _( "Look at" ) );
         print_colored_text( d_win, point( actions_xoffset, ycurrent ), cur_color, c_magenta,
                             formatted_text );
         ++ycurrent;
         formatted_text = formatted_hotkey( ctxt.get_desc( "SIZE_UP_STATS", 1 ),
                                            cur_color ).append( _( "Size up stats" ) );
         print_colored_text( d_win, point( actions_xoffset, ycurrent ), cur_color, c_magenta,
                             formatted_text );
         ++ycurrent;
         formatted_text = formatted_hotkey( ctxt.get_desc( "ASSESS_PERSONALITY", 1 ),
                                            cur_color ).append( _( "Assess personality" ) );
         print_colored_text( d_win, point( actions_xoffset, ycurrent ), cur_color, c_magenta,
                             formatted_text );
         ++ycurrent;
         formatted_text = formatted_hotkey( ctxt.get_desc( "YELL", 1 ), cur_color ).append( _( "Yell" ) );
         print_colored_text( d_win, point( actions_xoffset, ycurrent ), cur_color, c_magenta,
                             formatted_text );
         ++ycurrent;
         formatted_text = formatted_hotkey( ctxt.get_desc( "CHECK_OPINION", 1 ),
                                            cur_color ).append( _( "Check opinion" ) );
         print_colored_text( d_win, point( actions_xoffset, ycurrent ), cur_color, c_magenta,
                             formatted_text );
     }
     wnoutrefresh( d_win );
     responses_list->print_entries();
     if( update_history_view ) {
         update_history_view = false;
         const int newindex = history.size() - num_lines_highlighted;
         std::string assembled;
         for( int i = 0; i < static_cast<int>( history.size() ); ++i ) {
             nc_color col = ( i >= newindex ) ? history[i].color : c_light_gray;
             assembled += colorize( history[i].text, col ).append( "\n" );
         }
         history_view->set_text( assembled, false );
     }
     history_view->draw( c_light_gray );
 }
References _, c_light_gray, c_magenta, color(), colorize(), d_win, formatted_hotkey(), input_context::get_desc(), catacurses::getmaxx(), catacurses::getmaxy(), history, history_view, is_computer, is_not_conversation, num_lines_highlighted, point, print_colored_text(), print_header(), RESPONSES_LINES, responses_list, update_history_view, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by dialogue::opt().
handle_scrolling()
void dialogue_window::handle_scrolling (std::string & action, input_context & ctxt)
Definition at line 101 of file dialogue_win.cpp.
 {
     if( responses_list->handle_navigation( action, ctxt ) ||
         history_view->handle_navigation( action, ctxt ) ) {
         // No further action required
     }
     sel_response = responses_list->get_entry_pos();
 }
References action, history_view, responses_list, and sel_response.
Referenced by dialogue::opt().
print_header()
void dialogue_window::print_header (const std::string & name) const private
Definition at line 157 of file dialogue_win.cpp.
 {
     draw_border( d_win );
     if( is_computer ) {
         mvwprintz( d_win, point( 2, 1 ), default_color(), _( "Interaction: %s" ), name );
     } else if( !is_not_conversation ) {
         mvwprintz( d_win, point( 2, 1 ), default_color(), _( "Dialogue: %s" ), name );
     }
     const int xmax = getmaxx( d_win );
     const int ymax = getmaxy( d_win );
     const int ybar = ymax - 1 - RESPONSES_LINES - 1;
     // Horizontal bar dividing history and responses
     mvwputch( d_win, point( 0, ybar ), BORDER_COLOR, LINE_XXXO );
     mvwhline( d_win, point( 1, ybar ), LINE_OXOX, xmax - 1 );
     mvwputch( d_win, point( xmax - 1, ybar ), BORDER_COLOR, LINE_XOXX );
     if( is_computer ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         mvwprintz( d_win, point( 2, ybar + 1 ), default_color(), _( "Your input:" ) );
     } else if( is_not_conversation ) {
         mvwprintz( d_win, point( 2, ybar + 1 ), default_color(), _( "What do you do?" ) );
     } else {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         mvwprintz( d_win, point( 2, ybar + 1 ), default_color(), _( "Your response:" ) );
     }
 }
References _, BORDER_COLOR, d_win, default_color(), draw_border(), catacurses::getmaxx(), catacurses::getmaxy(), is_computer, is_not_conversation, LINE_OXOX, LINE_XOXX, LINE_XXXO, catacurses::mvwhline(), mvwprintz(), mvwputch(), om_direction::name(), point, and RESPONSES_LINES.
Referenced by draw().
resize()
void dialogue_window::resize (ui_adaptor & ui)
Definition at line 29 of file dialogue_win.cpp.
 {
     const int win_beginy = TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 4 : 0;
     const int win_beginx = TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 4 : 0;
     const int maxy = win_beginy ? TERMY - 2 * win_beginy : FULL_SCREEN_HEIGHT;
     const int maxx = win_beginx ? TERMX - 2 * win_beginx : FULL_SCREEN_WIDTH;
     d_win = catacurses::newwin( maxy, maxx, point( win_beginx, win_beginy ) );
     ui.position_from_window( d_win );
     history_win = catacurses::newwin( maxy - 1 - RESPONSES_LINES - 2 - 1, maxx - 1, point( win_beginx,
                                       win_beginy + 2 ) );
     resp_win = catacurses::newwin( RESPONSES_LINES - 1, maxx / 2, point( win_beginx,
                                    win_beginy + maxy - RESPONSES_LINES ) );
     // Reset size-dependant state
     update_history_view = true;
     responses_list->fold_entries();
 }
References d_win, FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, history_win, catacurses::newwin(), point, resp_win, RESPONSES_LINES, responses_list, TERMX, TERMY, and update_history_view.
Referenced by dialogue::opt().
set_responses()
void dialogue_window::set_responses (const std::vector< talk_data > & responses)
Definition at line 183 of file dialogue_win.cpp.
 {
     responses_list->create_entries( responses );
 }
References responses_list.
Referenced by dialogue::opt().
set_up_scrolling()
void dialogue_window::set_up_scrolling (input_context & ctxt) const
Definition at line 110 of file dialogue_win.cpp.
 {
     if( !is_computer && !is_not_conversation ) {
         ctxt.register_action( "LOOK_AT" );
         ctxt.register_action( "SIZE_UP_STATS" );
         ctxt.register_action( "ASSESS_PERSONALITY" );
         ctxt.register_action( "YELL" );
         ctxt.register_action( "CHECK_OPINION" );
     }
     history_view->set_up_navigation( ctxt, scrolling_key_scheme::angle_bracket_scroll );
     responses_list->set_up_navigation( ctxt );
 }
References angle_bracket_scroll, history_view, is_computer, is_not_conversation, input_context::register_action(), and responses_list.
Referenced by dialogue::opt().
Member Data Documentation
d_win
catacurses::window dialogue_window::d_win private
Definition at line 54 of file dialogue_win.h.
Referenced by draw(), print_header(), and resize().
folded_heights
std::vector<int> dialogue_window::folded_heights private
Definition at line 81 of file dialogue_win.h.
folded_txt
std::vector<std::tuple<std::string, std::vector<std::string> > > dialogue_window::folded_txt private
Stored responses (hotkey, lines)
Definition at line 80 of file dialogue_win.h.
history
std::vector<history_message> dialogue_window::history private
This contains the exchanged words, it is basically like the global message log.
Each responses of the player character and the NPC are added as are information about what each of them does (e.g. the npc drops their weapon). This will be displayed in the dialog window and should already be translated.
Definition at line 74 of file dialogue_win.h.
Referenced by add_to_history(), and draw().
history_view
std::unique_ptr<scrolling_text_view> dialogue_window::history_view private
Definition at line 75 of file dialogue_win.h.
Referenced by dialogue_window(), draw(), handle_scrolling(), and set_up_scrolling().
history_win
catacurses::window dialogue_window::history_win private
Definition at line 55 of file dialogue_win.h.
Referenced by dialogue_window(), and resize().
is_computer
bool dialogue_window::is_computer = false
Definition at line 50 of file dialogue_win.h.
Referenced by default_color(), draw(), dialogue::opt(), print_header(), set_up_scrolling(), and avatar::talk_to().
is_not_conversation
bool dialogue_window::is_not_conversation = false
Definition at line 51 of file dialogue_win.h.
Referenced by draw(), dialogue::opt(), print_header(), set_up_scrolling(), and avatar::talk_to().
num_lines_highlighted
int dialogue_window::num_lines_highlighted private
Number of history messages to highlight.
Definition at line 78 of file dialogue_win.h.
Referenced by add_to_history(), clear_history_highlights(), and draw().
resp_win
catacurses::window dialogue_window::resp_win private
Definition at line 56 of file dialogue_win.h.
Referenced by dialogue_window(), and resize().
responses_list
std::unique_ptr<multiline_list> dialogue_window::responses_list private
Definition at line 82 of file dialogue_win.h.
Referenced by dialogue_window(), draw(), handle_scrolling(), resize(), set_responses(), and set_up_scrolling().
sel_response
int dialogue_window::sel_response = 0
Definition at line 52 of file dialogue_win.h.
Referenced by handle_scrolling(), and dialogue::opt().
update_history_view
bool dialogue_window::update_history_view = true private
Definition at line 76 of file dialogue_win.h.
Referenced by add_to_history(), draw(), and resize().
The documentation for this class was generated from the following files:
src/dialogue_win.h
src/dialogue_win.cpp