Cataclysm DDA: jmapgen_gaspump Class Reference
jmapgen_gaspump Class Reference
Place a gas pump with fuel in it.
Public Member Functions
jmapgen_gaspump (const JsonObject &jsi, const std::string_view)
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
Public Attributes
jmapgen_int amount
mapgen_value< itype_id > fuel
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a gas pump with fuel in it.
"amount": number of fuel charges to place.
Definition at line 2133 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_gaspump()
jmapgen_gaspump::jmapgen_gaspump (const JsonObject & jsi, const std::string_view) inline
Definition at line 2138 of file mapgen.cpp.
                                                                         :
             amount( jsi, "amount", 0, 0 ) {
             if( jsi.has_member( "fuel" ) ) {
                 jsi.read( "fuel", fuel );
             }
         }
References fuel, JsonObject::has_member(), mapgen_defer::jsi, and JsonObject::read().
Member Function Documentation
apply()
void jmapgen_gaspump::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2160 of file mapgen.cpp.
{
             const tripoint_bub_ms r( x.get(), y.get(), dat.zlevel() + z.get() );
             int charges = amount.get() * 100;
             dat.m.furn_set( r, furn_str_id::NULL_ID() );
             if( charges == 0 ) {
                 charges = rng( 10000, 50000 );
             }
             itype_id chosen_fuel = fuel.get( dat );
             if( chosen_fuel.is_null() ) {
                 dat.m.place_gas_pump( r, charges );
             } else {
                 dat.m.place_gas_pump( r, charges, chosen_fuel );
             }
         }
References amount, fuel, map::furn_set(), jmapgen_int::get(), string_id< T >::is_null(), mapgendata::m, string_id< furn_t >::NULL_ID(), map::place_gas_pump(), rng(), and mapgendata::zlevel().
check()
void jmapgen_gaspump::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 2145 of file mapgen.cpp.
{
             fuel.check( oter_name, parameters );
             static const std::unordered_set<itype_id> valid_fuels = {
                 itype_id::NULL_ID(), itype_gasoline, itype_diesel, itype_jp8, itype_avgas
             };
             for( const itype_id &possible_fuel : fuel.all_possible_results( parameters ) ) {
                 // may want to not force this, if we want to support other fuels for some reason
                 if( !valid_fuels.count( possible_fuel ) ) {
                     debugmsg( "invalid fuel %s in %s", possible_fuel.str(), oter_name );
                 }
             }
         }
References debugmsg, fuel, itype_avgas, itype_diesel, itype_gasoline, itype_jp8, and string_id< itype >::NULL_ID().
has_vehicle_collision()
bool jmapgen_gaspump::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2175 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint_bub_ms( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
Member Data Documentation
amount
jmapgen_int jmapgen_gaspump::amount
Definition at line 2136 of file mapgen.cpp.
Referenced by apply().
fuel
mapgen_value<itype_id> jmapgen_gaspump::fuel
Definition at line 2137 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_gaspump().
The documentation for this class was generated from the following file:
src/mapgen.cpp