Cataclysm DDA: gunmod_add_activity_actor Class Reference
gunmod_add_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
gunmod_add_activity_actor ()=default
gunmod_add_activity_actor (int moves, std::string name)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves
std::string name
Detailed Description
Definition at line 2023 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
gunmod_add_activity_actor() [1/2]
gunmod_add_activity_actor::gunmod_add_activity_actor () default
gunmod_add_activity_actor() [2/2]
gunmod_add_activity_actor::gunmod_add_activity_actor (int moves, std::string name) inline
Definition at line 2027 of file activity_actor_definitions.h.
                                                                : moves( moves ),
             name( std::move( name ) ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> gunmod_add_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 2038 of file activity_actor_definitions.h.
{
             return std::make_unique<gunmod_add_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > gunmod_add_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6849 of file activity_actor.cpp.
 {
     gunmod_add_activity_actor actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "moves", actor.moves );
     data.read( "name", actor.name );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void gunmod_add_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 2035 of file activity_actor_definitions.h.
 {};
finish()
void gunmod_add_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 6782 of file activity_actor.cpp.
 {
     act.set_to_null();
     // first unpack all of our arguments
     if( act.values.size() != 4 ) {
         debugmsg( "Insufficient arguments to ACT_GUNMOD_ADD" );
         return;
     }
     item &gun = *act.targets.at( 0 );
     item &mod = *act.targets.at( 1 );
     // chance of success (%)
     const int roll = act.values[1];
     // chance of damage (%)
     const int risk = act.values[2];
     // any tool charges used during installation
     const itype_id tool( act.name );
     const int qty = act.values[3];
     if( !gun.is_gunmod_compatible( mod ).success() ) {
         debugmsg( "Invalid arguments in ACT_GUNMOD_ADD" );
         return;
     }
     if( !tool.is_empty() && qty > 0 ) {
         who.use_charges( tool, qty );
     }
     if( rng( 0, 100 ) <= roll ) {
         add_msg( m_good, _( "You successfully attached the %1$s to your %2$s." ), mod.tname(),
                  gun.tname() );
         gun.put_in( who.i_rem( &mod ), pocket_type::MOD );
         gun.on_contents_changed();
     } else if( rng( 0, 100 ) <= risk ) {
         if( gun.inc_damage() ) {
             // Remove irremovable mods prior to destroying the gun
             for( item *mod : gun.gunmods() ) {
                 if( mod->is_irremovable() ) {
                     who.remove_item( *mod );
                 }
             }
             add_msg( m_bad, _( "You failed at installing the %s and destroyed your %s!" ), mod.tname(),
                      gun.tname() );
             who.i_rem( &gun );
         } else {
             add_msg( m_bad, _( "You failed at installing the %s and damaged your %s!" ), mod.tname(),
                      gun.tname() );
         }
     } else {
         add_msg( m_info, _( "You failed at installing the %s." ), mod.tname() );
     }
 }
References _, act, add_msg(), debugmsg, gun, Character::i_rem(), string_id< T >::is_empty(), m_bad, m_good, m_info, MOD, visitable::remove_item(), rng(), and Character::use_charges().
get_type()
activity_id gunmod_add_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 2030 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_GUNMOD_ADD" );
         }
References activity_id.
serialize()
void gunmod_add_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6839 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves", moves );
     jsout.member( "name", name );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves, name, and JsonOut::start_object().
start()
void gunmod_add_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 6775 of file activity_actor.cpp.
 {
     act.moves_total = moves;
     act.moves_left = moves;
     act.name = name;
 }
References act, moves, and name.
Member Data Documentation
moves
int gunmod_add_activity_actor::moves private
Definition at line 2046 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
name
std::string gunmod_add_activity_actor::name private
Definition at line 2047 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp