Cataclysm DDA: invlet_wrapper Class Reference
invlet_wrapper Class Reference
Wrapper to handled a set of valid "inventory" letters.
#include <inventory.h>
Public Member Functions
invlet_wrapper (const char *chars)
bool valid (int invlet) const
std::string get_allowed_chars () const
Detailed Description
Wrapper to handled a set of valid "inventory" letters.
"inventory" can be any set of objects that the player can access via a single character (e.g. bionics). The class is (currently) derived from std::string for compatibility and because it's simpler. But it may be changed to derive from std::set<int> or similar to get the full range of possible characters.
Definition at line 52 of file inventory.h.
Constructor & Destructor Documentation
invlet_wrapper()
invlet_wrapper::invlet_wrapper (const char * chars) inline explicit
Definition at line 55 of file inventory.h.
 : std::string( chars ) { }
Member Function Documentation
get_allowed_chars()
std::string invlet_wrapper::get_allowed_chars () const inline
Definition at line 58 of file inventory.h.
{
             return *this;
         }
Referenced by avatar::power_bionics(), avatar::power_mutations(), and game_menus::inv::swap_letters().
valid()
bool invlet_wrapper::valid (int invlet) const
Definition at line 59 of file inventory.cpp.
 {
     if( invlet > std::numeric_limits<char>::max() || invlet < std::numeric_limits<char>::min() ) {
         return false;
     }
     return find( static_cast<char>( invlet ) ) != std::string::npos;
 }
References max(), and min().
Referenced by spellcasting_callback::key(), avatar::power_bionics(), avatar::power_mutations(), avatar::reassign_item(), game_menus::inv::reassign_letter(), and inventory::restack().
The documentation for this class was generated from the following files:
src/inventory.h
src/inventory.cpp