Cataclysm DDA: tripoint_range< Tripoint > Class Template Reference
tripoint_range< Tripoint > Class Template Reference
#include <map_iterator.h>
Classes
class point_generator
Generates points in a rectangle.
Public Types
using value_type = typename point_generator::value_type
using difference_type = typename point_generator::difference_type
using pointer = typename point_generator::pointer
using reference = typename point_generator::reference
using iterator_category = typename point_generator::iterator_category
using iterator = point_generator
using const_iterator = point_generator
Public Member Functions
tripoint_range (const Tripoint &_minp, const Tripoint &_maxp, const std::function< bool(const Tripoint &)> &pred)
tripoint_range (const Tripoint &_minp, const Tripoint &_maxp)
point_generator begin () const
point_generator end () const
size_t size () const
bool empty () const
bool is_point_inside (const Tripoint &point) const
const Tripoint & min () const
const Tripoint & max () const
Private Types
using traits = point_traits< Tripoint >
Private Attributes
Tripoint minp
Tripoint maxp
Tripoint endp
std::function< bool(const Tripoint &)> predicate
Detailed Description
template<typename Tripoint>
class tripoint_range< Tripoint >
Definition at line 12 of file map_iterator.h.
Member Typedef Documentation
const_iterator
template<typename Tripoint > using tripoint_range< Tripoint >::const_iterator = point_generator
Definition at line 95 of file map_iterator.h.
difference_type
template<typename Tripoint > using tripoint_range< Tripoint >::difference_type = typename point_generator::difference_type
Definition at line 90 of file map_iterator.h.
iterator
template<typename Tripoint > using tripoint_range< Tripoint >::iterator = point_generator
Definition at line 94 of file map_iterator.h.
iterator_category
template<typename Tripoint > using tripoint_range< Tripoint >::iterator_category = typename point_generator::iterator_category
Definition at line 93 of file map_iterator.h.
pointer
template<typename Tripoint > using tripoint_range< Tripoint >::pointer = typename point_generator::pointer
Definition at line 91 of file map_iterator.h.
reference
template<typename Tripoint > using tripoint_range< Tripoint >::reference = typename point_generator::reference
Definition at line 92 of file map_iterator.h.
traits
template<typename Tripoint > using tripoint_range< Tripoint >::traits = point_traits<Tripoint> private
Definition at line 16 of file map_iterator.h.
value_type
template<typename Tripoint > using tripoint_range< Tripoint >::value_type = typename point_generator::value_type
Definition at line 89 of file map_iterator.h.
Constructor & Destructor Documentation
tripoint_range() [1/2]
template<typename Tripoint > tripoint_range< Tripoint >::tripoint_range (const Tripoint & _minp, const Tripoint & _maxp, const std::function< bool(const Tripoint &)> & pred) inline
Definition at line 97 of file map_iterator.h.
                                                                             :
             minp( _minp ), maxp( _maxp ), predicate( pred )  {
             endp = Tripoint( minp.xy(), traits::z( maxp ) + 1 );
         }
References tripoint_range< Tripoint >::endp, tripoint_range< Tripoint >::maxp, tripoint_range< Tripoint >::minp, and point_traits< Point, typename >::z().
tripoint_range() [2/2]
template<typename Tripoint > tripoint_range< Tripoint >::tripoint_range (const Tripoint & _minp, const Tripoint & _maxp) inline
Definition at line 103 of file map_iterator.h.
                                                                        :
             minp( _minp ), maxp( _maxp ) {
             endp = Tripoint( minp.xy(), traits::z( maxp ) + 1 );
         }
References tripoint_range< Tripoint >::endp, tripoint_range< Tripoint >::maxp, tripoint_range< Tripoint >::minp, and point_traits< Point, typename >::z().
Member Function Documentation
begin()
template<typename Tripoint > point_generator tripoint_range< Tripoint >::begin () const inline
Definition at line 108 of file map_iterator.h.
{
             return point_generator( minp, *this );
         }
References tripoint_range< Tripoint >::minp.
Referenced by npc::move_away_from(), and tripoint_range< Tripoint >::size().
empty()
template<typename Tripoint > bool tripoint_range< Tripoint >::empty () const inline
Definition at line 132 of file map_iterator.h.
{
             return size() == 0;
         }
References tripoint_range< Tripoint >::size().
end()
template<typename Tripoint > point_generator tripoint_range< Tripoint >::end () const inline
Definition at line 112 of file map_iterator.h.
{
             // Return the point AFTER the last one
             // That is, point under (in z-levels) the first one, but one z-level below the last one
             return point_generator( endp, *this );
         }
References tripoint_range< Tripoint >::endp.
Referenced by npc::move_away_from(), and tripoint_range< Tripoint >::size().
is_point_inside()
template<typename Tripoint > bool tripoint_range< Tripoint >::is_point_inside (const Tripoint & point) const inline
Definition at line 136 of file map_iterator.h.
{
             for( const Tripoint &current : *this ) {
                 if( current == point ) {
                     return true;
                 }
             }
             return false;
         }
Referenced by anonymous_namespace{debug_menu.cpp}::_trim_mapbuffer(), anonymous_namespace{debug_menu.cpp}::_trim_overmapbuffer(), iuse::camera(), enumerate_objects_around_point(), and debug_menu::kill_area().
max()
template<typename Tripoint > const Tripoint& tripoint_range< Tripoint >::max () const inline
Definition at line 148 of file map_iterator.h.
{
             return maxp;
         }
References tripoint_range< Tripoint >::maxp.
Referenced by tinymap::points_in_radius(), tinymap::points_in_rectangle(), random_point(), and explosion_handler::shrapnel().
min()
template<typename Tripoint > const Tripoint& tripoint_range< Tripoint >::min () const inline
Definition at line 145 of file map_iterator.h.
{
             return minp;
         }
References tripoint_range< Tripoint >::minp.
Referenced by tinymap::points_in_radius(), tinymap::points_in_rectangle(), random_point(), and explosion_handler::shrapnel().
size()
template<typename Tripoint > size_t tripoint_range< Tripoint >::size () const inline
Definition at line 118 of file map_iterator.h.
{
             if( !predicate ) {
                 Tripoint range( traits::x( maxp ) - traits::x( minp ), traits::y( maxp ) - traits::y( minp ),
                                 traits::z( maxp ) - traits::z( minp ) );
                 return std::max( ++traits::x( range ) * ++traits::y( range ) * ++traits::z( range ), 0 );
             } else {
                 size_t count = 0;
                 for( point_generator it = begin(); it != end(); ++it ) {
                     ++count;
                 }
                 return count;
             }
         }
References tripoint_range< Tripoint >::begin(), tripoint_range< Tripoint >::end(), max(), tripoint_range< Tripoint >::maxp, tripoint_range< Tripoint >::minp, tripoint_range< Tripoint >::predicate, point_traits< Point, typename >::x(), point_traits< Point, typename >::y(), and point_traits< Point, typename >::z().
Referenced by tripoint_range< Tripoint >::empty().
Member Data Documentation
endp
template<typename Tripoint > Tripoint tripoint_range< Tripoint >::endp private
Definition at line 85 of file map_iterator.h.
Referenced by tripoint_range< Tripoint >::end(), tripoint_range< Tripoint >::point_generator::operator++(), tripoint_range< Tripoint >::point_generator::point_generator(), and tripoint_range< Tripoint >::tripoint_range().
maxp
template<typename Tripoint > Tripoint tripoint_range< Tripoint >::maxp private
Definition at line 83 of file map_iterator.h.
Referenced by tripoint_range< Tripoint >::max(), tripoint_range< Tripoint >::point_generator::operator++(), tripoint_range< Tripoint >::size(), and tripoint_range< Tripoint >::tripoint_range().
minp
template<typename Tripoint > Tripoint tripoint_range< Tripoint >::minp private
Definition at line 82 of file map_iterator.h.
Referenced by tripoint_range< Tripoint >::begin(), tripoint_range< Tripoint >::min(), tripoint_range< Tripoint >::point_generator::operator++(), tripoint_range< Tripoint >::size(), and tripoint_range< Tripoint >::tripoint_range().
predicate
template<typename Tripoint > std::function<bool(const Tripoint &)> tripoint_range< Tripoint >::predicate private
Definition at line 87 of file map_iterator.h.
Referenced by tripoint_range< Tripoint >::point_generator::operator++(), tripoint_range< Tripoint >::point_generator::point_generator(), and tripoint_range< Tripoint >::size().
The documentation for this class was generated from the following files:
src/game.h
src/map_iterator.h