Cataclysm DDA: cata::flat_set< T, Compare, Data > Class Template Reference
cata::flat_set< T, Compare, Data > Class Template Reference
A SimpleAssociativeContainer implemented as a sorted vector.
#include <flat_set.h>
Classes
struct has_is_transparent
struct has_is_transparent< Cmp, Sfinae, typename Cmp::is_transparent >
Public Types
using key_type = value_type
using key_compare = Compare
using value_compare = Compare
using iterator = const_iterator
using reverse_iterator = const_reverse_iterator
Public Member Functions
flat_set ()=default
flat_set (const key_compare &kc)
template<typename InputIt >
flat_set (InputIt first, InputIt last)
template<typename InputIt >
flat_set (InputIt first, InputIt last, const key_compare &kc)
flat_set (std::initializer_list< value_type > init)
const key_compare & key_comp () const
const value_compare & value_comp () const
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
const_reference operator[] (size_type i) const
const_iterator lower_bound (const T &t) const
template<typename K , typename = typename has_is_transparent<Compare, K>::type>
const_iterator lower_bound (const K &k) const
const_iterator upper_bound (const T &t) const
template<typename K , typename = typename has_is_transparent<Compare, K>::type>
const_iterator upper_bound (const K &k) const
std::pair< const_iterator, const_iterator > equal_range (const T &t) const
template<typename K , typename = typename has_is_transparent<Compare, K>::type>
std::pair< const_iterator, const_iterator > equal_range (const K &k) const
const_iterator find (const value_type &value) const
template<typename K , typename = typename has_is_transparent<Compare, K>::type>
const_iterator find (const K &k) const
size_type count (const T &t) const
template<typename K , typename = typename has_is_transparent<Compare, K>::type>
size_type count (const K &k) const
iterator insert (iterator, const value_type &value)
iterator insert (iterator, value_type &&value)
std::pair< iterator, bool > insert (const value_type &value)
std::pair< iterator, bool > insert (value_type &&value)
template<typename InputIt >
void insert (InputIt first, InputIt last)
size_type erase (const value_type &value)
Private Member Functions
const Data & data () const
void sort_data ()
Private Member Functions inherited from cata::transparent_less_than
template<typename T , typename U >
constexpr auto operator() (T &&lhs, U &&rhs) const noexcept -> decltype(std::forward< T >(lhs)< std::forward< U >(rhs))
Friends
void swap (flat_set &l, flat_set &r)
Additional Inherited Members
Private Types inherited from cata::transparent_less_than
using is_transparent = void
Detailed Description
template<typename T, typename Compare = transparent_less_than, typename Data = std::vector<T>>
class cata::flat_set< T, Compare, Data >
A SimpleAssociativeContainer implemented as a sorted vector.
O(n) insertion, O(log(n)) lookup, only one allocation at any given time.
Definition at line 29 of file flat_set.h.
Member Typedef Documentation
iterator
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> using cata::flat_set< T, Compare, Data >::iterator = const_iterator
Definition at line 49 of file flat_set.h.
key_compare
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> using cata::flat_set< T, Compare, Data >::key_compare = Compare
Definition at line 44 of file flat_set.h.
key_type
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> using cata::flat_set< T, Compare, Data >::key_type = value_type
Definition at line 43 of file flat_set.h.
reverse_iterator
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> using cata::flat_set< T, Compare, Data >::reverse_iterator = const_reverse_iterator
Definition at line 51 of file flat_set.h.
value_compare
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> using cata::flat_set< T, Compare, Data >::value_compare = Compare
Definition at line 45 of file flat_set.h.
Constructor & Destructor Documentation
flat_set() [1/5]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> cata::flat_set< T, Compare, Data >::flat_set () default
flat_set() [2/5]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> cata::flat_set< T, Compare, Data >::flat_set (const key_compare & kc) inline explicit
Definition at line 54 of file flat_set.h.
 : Compare( kc ) {}
flat_set() [3/5]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> template<typename InputIt > cata::flat_set< T, Compare, Data >::flat_set (InputIt first, InputIt last) inline
Definition at line 56 of file flat_set.h.
                                                 : Data( first, last ) {
             sort_data();
         }
References last, and cata::flat_set< T, Compare, Data >::sort_data().
flat_set() [4/5]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> template<typename InputIt > cata::flat_set< T, Compare, Data >::flat_set (InputIt first, InputIt last, const key_compare & kc) inline
Definition at line 60 of file flat_set.h.
                                                                        :
             Compare( kc ), Data( first, last ) {
             sort_data();
         }
References last, and cata::flat_set< T, Compare, Data >::sort_data().
flat_set() [5/5]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> cata::flat_set< T, Compare, Data >::flat_set (std::initializer_list< value_type > init) inline
Definition at line 64 of file flat_set.h.
                                                          : Data( init ) {
             sort_data();
         }
References cata::flat_set< T, Compare, Data >::sort_data().
Member Function Documentation
begin()
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> iterator cata::flat_set< T, Compare, Data >::begin () const inline
Definition at line 83 of file flat_set.h.
{
             return cbegin();
         }
Referenced by map::build_map_cache(), item::clear_automatic_whitelist(), cata::flat_set< T, Compare, Data >::lower_bound(), sort_body_parts(), and cata::flat_set< T, Compare, Data >::upper_bound().
count() [1/2]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> template<typename K , typename = typename has_is_transparent<Compare, K>::type> size_type cata::flat_set< T, Compare, Data >::count (const K & k) const inline
Definition at line 146 of file flat_set.h.
{
             auto at = lower_bound( k );
             return at != end() && *at == k;
         }
References cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::lower_bound().
count() [2/2]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> size_type cata::flat_set< T, Compare, Data >::count (const T & t) const inline
Definition at line 141 of file flat_set.h.
{
             auto at = lower_bound( t );
             return at != end() && *at == t;
         }
References cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::lower_bound().
Referenced by npc_template::check_consistency(), Item_factory::check_definitions(), overmap_special::has_flag(), map_extra::has_flag(), pocket_favorite_callback::key(), outfit::sort_armor(), and overmap_location::test().
data()
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> const Data& cata::flat_set< T, Compare, Data >::data () const inline private
Definition at line 209 of file flat_set.h.
{
             return *this;
         }
end()
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> iterator cata::flat_set< T, Compare, Data >::end () const inline
Definition at line 86 of file flat_set.h.
{
             return cend();
         }
Referenced by map::build_map_cache(), cata::flat_set< T, Compare, Data >::count(), cata::flat_set< T, Compare, Data >::erase(), cata::flat_set< T, Compare, Data >::find(), bionic::has_flag(), cata::flat_set< T, Compare, Data >::insert(), cata::flat_set< T, Compare, Data >::lower_bound(), sort_body_parts(), cata::flat_set< T, Compare, Data >::sort_data(), and cata::flat_set< T, Compare, Data >::upper_bound().
equal_range() [1/2]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> template<typename K , typename = typename has_is_transparent<Compare, K>::type> std::pair<const_iterator, const_iterator> cata::flat_set< T, Compare, Data >::equal_range (const K & k) const inline
Definition at line 122 of file flat_set.h.
{
             return { lower_bound( k ), upper_bound( k ) };
         }
References cata::flat_set< T, Compare, Data >::lower_bound(), and cata::flat_set< T, Compare, Data >::upper_bound().
equal_range() [2/2]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> std::pair<const_iterator, const_iterator> cata::flat_set< T, Compare, Data >::equal_range (const T & t) const inline
Definition at line 118 of file flat_set.h.
{
             return { lower_bound( t ), upper_bound( t ) };
         }
References cata::flat_set< T, Compare, Data >::lower_bound(), and cata::flat_set< T, Compare, Data >::upper_bound().
erase()
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> size_type cata::flat_set< T, Compare, Data >::erase (const value_type & value) inline
Definition at line 183 of file flat_set.h.
{
             auto at = find( value );
             if( at != end() ) {
                 erase( at );
                 return 1;
             }
             return 0;
         }
References cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::find().
Referenced by bionic::remove_flag(), and sort_body_parts().
find() [1/2]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> template<typename K , typename = typename has_is_transparent<Compare, K>::type> const_iterator cata::flat_set< T, Compare, Data >::find (const K & k) const inline
Definition at line 134 of file flat_set.h.
{
             auto at = lower_bound( k );
             if( at != end() && *at == k ) {
                 return at;
             }
             return end();
         }
References cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::lower_bound().
find() [2/2]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> const_iterator cata::flat_set< T, Compare, Data >::find (const value_type & value) const inline
Definition at line 126 of file flat_set.h.
{
             auto at = lower_bound( value );
             if( at != end() && *at == value ) {
                 return at;
             }
             return end();
         }
References cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::lower_bound().
Referenced by cata::flat_set< T, Compare, Data >::erase(), and bionic::has_flag().
insert() [1/5]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> std::pair<iterator, bool> cata::flat_set< T, Compare, Data >::insert (const value_type & value) inline
Definition at line 159 of file flat_set.h.
{
             auto at = lower_bound( value );
             if( at != end() && *at == value ) {
                 return { at, false };
             }
             return { Data::insert( at, value ), true };
         }
References cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::lower_bound().
insert() [2/5]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> template<typename InputIt > void cata::flat_set< T, Compare, Data >::insert (InputIt first, InputIt last) inline
TODO: could be faster when inserting only a few elements
Definition at line 175 of file flat_set.h.
{
             /// TODO: could be faster when inserting only a few elements
             Data::insert( end(), first, last );
             sort_data();
         }
References cata::flat_set< T, Compare, Data >::end(), last, and cata::flat_set< T, Compare, Data >::sort_data().
insert() [3/5]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> iterator cata::flat_set< T, Compare, Data >::insert (iterator , const value_type & value) inline
TODO: Use insertion hint
Definition at line 151 of file flat_set.h.
{
             /// TODO: Use insertion hint
             return insert( value ).first;
         }
Referenced by Item_factory::check_definitions(), Character::compute_nutrient_range(), overmap_specials::create_building_from(), bionic::deserialize(), anonymous_namespace{bionics_ui.cpp}::filtered_bionics(), overmap_location::finalize(), mutable_overmap_terrain_join::finalize(), cata::flat_set< T, Compare, Data >::insert(), pocket_favorite_callback::key(), damage_type::load(), jmapgen_nested::neighbor_oter_check::neighbor_oter_check(), jmapgen_nested::predecessor_oter_check::predecessor_oter_check(), item::properties_info(), bionic::set_flag(), outfit::sort_armor(), and sort_body_parts().
insert() [4/5]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> iterator cata::flat_set< T, Compare, Data >::insert (iterator , value_type && value) inline
TODO: Use insertion hint
Definition at line 155 of file flat_set.h.
{
             /// TODO: Use insertion hint
             return insert( std::move( value ) ).first;
         }
References cata::flat_set< T, Compare, Data >::insert().
insert() [5/5]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> std::pair<iterator, bool> cata::flat_set< T, Compare, Data >::insert (value_type && value) inline
Definition at line 166 of file flat_set.h.
{
             auto at = lower_bound( value );
             if( at != end() && *at == value ) {
                 return { at, false };
             }
             return { Data::insert( at, std::move( value ) ), true };
         }
References cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::lower_bound().
key_comp()
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> const key_compare& cata::flat_set< T, Compare, Data >::key_comp () const inline
Definition at line 68 of file flat_set.h.
{
             return *this;
         }
Referenced by cata::flat_set< T, Compare, Data >::lower_bound(), cata::flat_set< T, Compare, Data >::sort_data(), and cata::flat_set< T, Compare, Data >::upper_bound().
lower_bound() [1/2]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> template<typename K , typename = typename has_is_transparent<Compare, K>::type> const_iterator cata::flat_set< T, Compare, Data >::lower_bound (const K & k) const inline
Definition at line 108 of file flat_set.h.
{
             return std::lower_bound( begin(), end(), k, key_comp() );
         }
References cata::flat_set< T, Compare, Data >::begin(), cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::key_comp().
lower_bound() [2/2]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> const_iterator cata::flat_set< T, Compare, Data >::lower_bound (const T & t) const inline
Definition at line 104 of file flat_set.h.
{
             return std::lower_bound( begin(), end(), t, key_comp() );
         }
References cata::flat_set< T, Compare, Data >::begin(), cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::key_comp().
Referenced by cata::flat_set< T, Compare, Data >::count(), cata::flat_set< T, Compare, Data >::equal_range(), cata::flat_set< T, Compare, Data >::find(), and cata::flat_set< T, Compare, Data >::insert().
operator[]()
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> const_reference cata::flat_set< T, Compare, Data >::operator[] (size_type i) const inline
Definition at line 100 of file flat_set.h.
{
             return Data::operator[]( i );
         }
rbegin()
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> reverse_iterator cata::flat_set< T, Compare, Data >::rbegin () const inline
Definition at line 89 of file flat_set.h.
{
             return crbegin();
         }
rend()
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> reverse_iterator cata::flat_set< T, Compare, Data >::rend () const inline
Definition at line 92 of file flat_set.h.
{
             return crend();
         }
sort_data()
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> void cata::flat_set< T, Compare, Data >::sort_data () inline private
Definition at line 212 of file flat_set.h.
{
             std::sort( Data::begin(), Data::end(), key_comp() );
             auto new_end = std::unique( Data::begin(), Data::end() );
             Data::erase( new_end, end() );
         }
References cata::flat_set< T, Compare, Data >::end(), keycode::end, catacurses::erase(), and cata::flat_set< T, Compare, Data >::key_comp().
Referenced by cata::flat_set< T, Compare, Data >::flat_set(), and cata::flat_set< T, Compare, Data >::insert().
upper_bound() [1/2]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> template<typename K , typename = typename has_is_transparent<Compare, K>::type> const_iterator cata::flat_set< T, Compare, Data >::upper_bound (const K & k) const inline
Definition at line 115 of file flat_set.h.
{
             return std::upper_bound( begin(), end(), k, key_comp() );
         }
References cata::flat_set< T, Compare, Data >::begin(), cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::key_comp().
upper_bound() [2/2]
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> const_iterator cata::flat_set< T, Compare, Data >::upper_bound (const T & t) const inline
Definition at line 111 of file flat_set.h.
{
             return std::upper_bound( begin(), end(), t, key_comp() );
         }
References cata::flat_set< T, Compare, Data >::begin(), cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::key_comp().
Referenced by cata::flat_set< T, Compare, Data >::equal_range().
value_comp()
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> const value_compare& cata::flat_set< T, Compare, Data >::value_comp () const inline
Definition at line 71 of file flat_set.h.
{
             return *this;
         }
Friends And Related Function Documentation
swap
template<typename T , typename Compare = transparent_less_than, typename Data = std::vector<T>> void swap (flat_set< T, Compare, Data > & l, flat_set< T, Compare, Data > & r) friend
Definition at line 192 of file flat_set.h.
{
             using std::swap;
             swap( static_cast<Compare &>( l ), static_cast<Compare &>( r ) );
             swap( static_cast<Data &>( l ), static_cast<Data &>( r ) );
         }
The documentation for this class was generated from the following file:
src/flat_set.h