Cataclysm DDA: auto_pickup::rule_list Class Reference
auto_pickup::rule_list Class Reference
A list of rules.
#include <auto_pickup.h>
Public Member Functions
void serialize (JsonOut &jsout) const
void deserialize (const JsonArray &ja)
void refresh_map_items (cache &map_items) const
void create_rule (cache &map_items, const std::string &to_match)
void create_rule (cache &map_items, const item &it)
Detailed Description
A list of rules.
This is primarily a container with a few convenient functions (like saving/loading).
Definition at line 68 of file auto_pickup.h.
Member Function Documentation
create_rule() [1/2]
void rule_list::create_rule (cache & map_items, const item & it)
Definition at line 845 of file auto_pickup.cpp.
 {
     const std::string to_match = it.tname( 1, false );
     for( const rule &elem : *this ) {
         if( !elem.bActive ) {
             continue;
         }
         if( !check_special_rule( it.made_of(), elem.sRule ) &&
             !wildcard_match( to_match, elem.sRule ) ) {
             continue;
         }
         map_items[ to_match ] = elem.bExclude ? rule_state::BLACKLISTED : rule_state::WHITELISTED;
     }
 }
References auto_pickup::rule::bActive, auto_pickup::rule::bExclude, BLACKLISTED, check_special_rule(), item::made_of(), auto_pickup::rule::sRule, item::tname(), WHITELISTED, and wildcard_match().
create_rule() [2/2]
void rule_list::create_rule (cache & map_items, const std::string & to_match)
Definition at line 827 of file auto_pickup.cpp.
 {
     for( const rule &elem : *this ) {
         if( !elem.bActive || !wildcard_match( to_match, elem.sRule ) ) {
             continue;
         }
         map_items[ to_match ] = elem.bExclude ? rule_state::BLACKLISTED : rule_state::WHITELISTED;
     }
 }
References auto_pickup::rule::bActive, auto_pickup::rule::bExclude, BLACKLISTED, auto_pickup::rule::sRule, WHITELISTED, and wildcard_match().
Referenced by auto_pickup::player_settings::create_rule(), and auto_pickup::npc_settings::create_rule().
deserialize()
void rule_list::deserialize (const JsonArray & ja)
Definition at line 1004 of file auto_pickup.cpp.
 {
     clear();
     for( JsonObject jo : ja ) {
         rule tmp;
         tmp.deserialize( jo );
         push_back( tmp );
     }
 }
References clear, and auto_pickup::rule::deserialize().
Referenced by auto_pickup::npc_settings::deserialize().
refresh_map_items()
void rule_list::refresh_map_items (cache & map_items) const
Definition at line 871 of file auto_pickup.cpp.
 {
     for( const rule &elem : *this ) {
         if( elem.sRule.empty() || !elem.bActive ) {
             continue;
         }
         if( !elem.bExclude ) {
             //Check include patterns against all itemfactory items
             for( const itype *e : item_controller->all() ) {
                 const std::string &cur_item = e->nname( 1 );
                 if( !check_special_rule( e->materials, elem.sRule ) && !wildcard_match( cur_item, elem.sRule ) ) {
                     continue;
                 }
                 map_items[ cur_item ] = rule_state::WHITELISTED;
                 map_items.temp_items[ cur_item ] = e;
             }
         } else {
             //only re-exclude items from the existing mapping for now
             //new exclusions will process during pickup attempts
             for( auto &map_item : map_items ) {
                 if( !check_special_rule( map_items.temp_items[ map_item.first ]->materials, elem.sRule ) &&
                     !wildcard_match( map_item.first, elem.sRule ) ) {
                     continue;
                 }
                 map_items[ map_item.first ] = rule_state::BLACKLISTED;
             }
         }
     }
 }
References auto_pickup::rule::bActive, auto_pickup::rule::bExclude, BLACKLISTED, check_special_rule(), item_controller, auto_pickup::rule::sRule, auto_pickup::cache::temp_items, WHITELISTED, and wildcard_match().
Referenced by auto_pickup::player_settings::refresh_map_items(), and auto_pickup::npc_settings::refresh_map_items().
serialize()
void rule_list::serialize (JsonOut & jsout) const
Definition at line 988 of file auto_pickup.cpp.
 {
     jsout.start_array();
     for( const rule &elem : *this ) {
         elem.serialize( jsout );
     }
     jsout.end_array();
 }
References JsonOut::end_array(), auto_pickup::rule::serialize(), and JsonOut::start_array().
Referenced by auto_pickup::npc_settings::serialize().
The documentation for this class was generated from the following files:
src/auto_pickup.h
src/auto_pickup.cpp