Cataclysm DDA: json_item_substitution Class Reference
json_item_substitution Class Reference
Classes
struct substitution
struct trait_requirements
Public Member Functions
void reset ()
void load (const JsonObject &jo)
void check_consistency () const
std::vector< item > get_bonus_items (const std::vector< trait_id > &traits) const
std::vector< item > get_substitution (const item &it, const std::vector< trait_id > &traits) const
Private Attributes
std::map< itype_id, std::vector< substitution > > substitutions
std::vector< std::pair< item_group_id, trait_requirements > > bonuses
Detailed Description
Definition at line 40 of file profession.cpp.
Member Function Documentation
check_consistency()
void json_item_substitution::check_consistency () const
Definition at line 804 of file profession.cpp.
 {
     auto check_if_trait = []( const trait_id & t ) {
         if( !t.is_valid() ) {
             debugmsg( "%s is not a trait", t.c_str() );
         }
     };
     auto check_if_itype = []( const itype_id & i ) {
         if( !item::type_is_defined( i ) ) {
             debugmsg( "%s is not an itype_id", i.c_str() );
         }
     };
     auto check_if_igroup = []( const item_group_id & gr ) {
         if( !item_group::group_is_defined( gr ) ) {
             debugmsg( "%s is not an item_group_id", gr.c_str() );
         }
     };
     auto check_trait_reqs = [&check_if_trait]( const trait_requirements & tr ) {
         for( const trait_id &str : tr.present ) {
             check_if_trait( str );
         }
         for( const trait_id &str : tr.absent ) {
             check_if_trait( str );
         }
     };
     for( const auto &pair : substitutions ) {
         check_if_itype( pair.first );
         for( const substitution &s : pair.second ) {
             check_trait_reqs( s.trait_reqs );
             for( const substitution::info &inf : s.infos ) {
                 check_if_itype( inf.new_item );
             }
         }
     }
     for( const auto &pair : bonuses ) {
         check_if_igroup( pair.first );
         check_trait_reqs( pair.second );
     }
 }
References bonuses, debugmsg, item_group::group_is_defined(), json_item_substitution::substitution::infos, json_item_substitution::substitution::info::new_item, substitutions, json_item_substitution::substitution::trait_reqs, and item::type_is_defined().
Referenced by profession::check_definitions().
get_bonus_items()
std::vector< item > json_item_substitution::get_bonus_items (const std::vector< trait_id > & traits) const
Definition at line 896 of file profession.cpp.
 {
     std::vector<item> ret;
     for( const auto &pair : bonuses ) {
         if( pair.second.meets_condition( traits ) ) {
             const std::vector<item> &items = item_group::items_from( pair.first, advanced_spawn_time() );
             // ret = ret + items
             ret.reserve( ret.size() + items.size() );
             ret.insert( ret.end(), items.begin(), items.end() );
         }
     }
     return ret;
 }
References advanced_spawn_time(), bonuses, item_group::items_from(), and cata::hash64_detail::ret.
Referenced by profession::items().
get_substitution()
std::vector< item > json_item_substitution::get_substitution (const item & it, const std::vector< trait_id > & traits) const
Definition at line 855 of file profession.cpp.
 {
     auto iter = substitutions.find( it.typeId() );
     std::vector<item> ret;
     if( iter == substitutions.end() ) {
         for( const item *con : it.all_items_top() ) {
             const auto sub = get_substitution( *con, traits );
             ret.insert( ret.end(), sub.begin(), sub.end() );
         }
         return ret;
     }
     const auto sub = std::find_if( iter->second.begin(),
     iter->second.end(), [&traits]( const substitution & s ) {
         return s.trait_reqs.meets_condition( traits );
     } );
     if( sub == iter->second.end() ) {
         return ret;
     }
     const int old_amt = it.count();
     for( const substitution::info &inf : sub->infos ) {
         item result( inf.new_item, advanced_spawn_time() );
         int new_amount = std::max( 1, static_cast<int>( std::round( inf.ratio * old_amt ) ) );
         if( !result.count_by_charges() ) {
             for( int i = 0; i < new_amount; i++ ) {
                 ret.push_back( result.in_its_container() );
             }
         } else {
             while( new_amount > 0 ) {
                 const item pushed = result.in_its_container( new_amount );
                 new_amount -= pushed.charges_of( inf.new_item );
                 ret.push_back( pushed );
             }
         }
     }
     return ret;
 }
References advanced_spawn_time(), item::all_items_top(), visitable::charges_of(), item::count(), item::count_by_charges(), item::in_its_container(), max(), json_item_substitution::substitution::info::new_item, json_item_substitution::substitution::info::ratio, cata::hash64_detail::ret, round(), math_opers::sub(), substitutions, and item::typeId().
Referenced by profession::items().
load()
void json_item_substitution::load (const JsonObject & jo)
Definition at line 760 of file profession.cpp.
 {
     auto check_duplicate_item = [&]( const itype_id & it ) {
         return substitutions.find( it ) != substitutions.end();
     };
     if( jo.has_member( "item" ) ) {
         // items mode
         if( check_duplicate_item( itype_id( jo.get_string( "item" ) ) ) ) {
             jo.throw_error( "Duplicate definition of item" );
         }
         for( const JsonValue sub : jo.get_array( "sub" ) ) {
             substitution s;
             JsonObject obj = sub.get_object();
             s.trait_reqs = trait_requirements( obj );
             for( const JsonValue info : obj.get_array( "new" ) ) {
                 s.infos.emplace_back( info );
             }
             substitutions[itype_id( jo.get_string( "item" ) )].push_back( s );
         }
     } else if( jo.has_member( "trait" ) ) {
         // traits mode
         for( const JsonObject sub : jo.get_array( "sub" ) ) {
             substitution s;
             itype_id old_it;
             sub.read( "item", old_it, true );
             if( check_duplicate_item( old_it ) ) {
                 sub.throw_error( "Duplicate definition of item" );
             }
             s.trait_reqs.present.emplace_back( jo.get_string( "trait" ) );
             for( const JsonValue info : sub.get_array( "new" ) ) {
                 s.infos.emplace_back( info );
             }
             substitutions[old_it].push_back( s );
         }
     } else if( jo.has_member( "bonus" ) ) {
         // bonuses mode
         const item_group_id &bonus_items = item_group::load_item_group( jo.get_member( "group" ),
                                            "collection", "bonus items" );
         bonuses.emplace_back( bonus_items, trait_requirements( jo.get_object( "bonus" ) ) );
     }
 }
References bonuses, JsonObject::get_array(), JsonObject::get_member(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), json_item_substitution::substitution::infos, itype_id, item_group::load_item_group(), json_item_substitution::trait_requirements::present, math_opers::sub(), substitutions, JsonObject::throw_error(), and json_item_substitution::substitution::trait_reqs.
Referenced by profession::load_item_substitutions().
reset()
void json_item_substitution::reset ()
Definition at line 730 of file profession.cpp.
 {
     substitutions.clear();
     bonuses.clear();
 }
References bonuses, and substitutions.
Referenced by profession::reset().
Member Data Documentation
bonuses
std::vector<std::pair<item_group_id, trait_requirements> > json_item_substitution::bonuses private
Definition at line 66 of file profession.cpp.
Referenced by check_consistency(), get_bonus_items(), load(), and reset().
substitutions
std::map<itype_id, std::vector<substitution> > json_item_substitution::substitutions private
Definition at line 65 of file profession.cpp.
Referenced by check_consistency(), get_substitution(), load(), and reset().
The documentation for this class was generated from the following file:
src/profession.cpp