Cataclysm DDA: item_pocket Class Reference
item_pocket Class Reference
#include <item_pocket.h>
Classes
class favorite_settings
Public Types
enum class contain_code : int {
SUCCESS , ERR_MOD , ERR_LIQUID , ERR_GAS ,
ERR_TOO_BIG , ERR_TOO_HEAVY , ERR_TOO_SMALL , ERR_NO_SPACE ,
ERR_CANNOT_SUPPORT , ERR_FLAG , ERR_AMMO
}
Public Member Functions
item_pocket ()=default
item_pocket (const pocket_data *data)
bool stacks_with (const item_pocket &rhs, int depth=0, int maxdepth=2) const
bool is_funnel_container (units::volume &bigger_than) const
bool is_restricted () const
bool has_any_with (const std::function< bool(const item &)> &filter) const
bool is_valid () const
bool is_type (pocket_type ptype) const
bool is_ablative () const
bool is_holster () const
bool holster_full () const
bool empty () const
bool full (bool allow_bucket) const
bool rigid () const
bool watertight () const
bool airtight () const
bool inherits_flags () const
bool transparent () const
bool allows_speedloader (const itype_id &speedloader_id) const
bool is_standard_type () const
bool is_forbidden () const
const translation & get_description () const
const translation & get_name () const
const pocket_data * get_pocket_data () const
std::list< item * > all_items_top ()
std::list< const item * > all_items_top () const
std::list< item * > all_items_ptr (pocket_type pk_type)
std::list< const item * > all_items_ptr (pocket_type pk_type) const
item & back ()
const item & back () const
item & front ()
const item & front () const
size_t size () const
void pop_back ()
ret_val< contain_code > is_compatible (const item &it) const
Is the pocket compatible with the specified item? Does not check if the item actually fits volume/weight wise.
ret_val< contain_code > can_contain (const item &it, bool ignore_contents=false) const
Can the pocket contain the specified item?
ret_val< contain_code > can_contain (const item &it, int &copies_remaining, bool ignore_contents=false) const
bool can_contain_liquid (bool held_or_ground) const
bool contains_phase (phase_id phase) const
bool can_reload_with (const item &ammo, bool now) const
returns whether this pocket can be reloaded with the specified item.
units::length max_containable_length () const
units::length min_containable_length () const
units::volume contains_volume () const
units::volume remaining_volume () const
int remaining_capacity_for_item (const item &it) const
units::volume volume_capacity () const
units::volume magazine_well () const
units::mass weight_capacity () const
units::volume max_contains_volume () const
units::mass contains_weight () const
units::mass remaining_weight () const
int charges_per_remaining_volume (const item &it) const
int charges_per_remaining_weight (const item &it) const
units::volume item_size_modifier () const
units::mass item_weight_modifier () const
units::length item_length_modifier () const
float spoil_multiplier () const
gets the spoilage multiplier depending on sealed data
int moves () const
int best_quality (const quality_id &id) const
void heat_up ()
std::vector< item * > gunmods ()
std::vector< const item * > gunmods () const
cata::flat_set< itype_id > item_type_restrictions () const
item * magazine_current ()
itype_id magazine_default () const
int ammo_consume (int qty)
std::set< ammotype > ammo_types () const
int ammo_capacity (const ammotype &ammo) const
int remaining_ammo_capacity (const ammotype &ammo) const
void casings_handle (const std::function< bool(item &)> &func)
bool use_amount (const itype_id &it, int &quantity, std::list< item > &used)
bool will_explode_in_a_fire () const
bool item_has_uses_recursive () const
bool will_spill () const
bool will_spill_if_unsealed () const
bool seal ()
void unseal ()
bool sealable () const
A pocket is sealable IFF it has "sealed_data".
bool sealed () const
A pocket is sealed when item spawns if pocket has "sealed_data".
std::string translated_sealed_prefix () const
bool detonate (const tripoint &p, std::vector< item > &drops)
bool process (const itype &type, map &here, Character *carrier, const tripoint &pos, float insulation, temperature_flag flag)
void remove_all_ammo (Character &guy)
void remove_all_mods (Character &guy)
void set_item_defaults ()
std::optional< item > remove_item (const item &it)
std::optional< item > remove_item (const item_location &it)
void overflow (const tripoint &pos, const item_location &loc)
bool spill_contents (const tripoint &pos)
void on_pickup (Character &guy, item *avoid=nullptr)
void on_contents_changed ()
void handle_liquid_or_spill (Character &guy, const item *avoid=nullptr)
void clear_items ()
bool has_item (const item &it) const
item * get_item_with (const std::function< bool(const item &)> &filter)
const item * get_item_with (const std::function< bool(const item &)> &filter) const
void remove_items_if (const std::function< bool(item &)> &filter)
void process (map &here, Character *carrier, const tripoint &pos, float insulation=1, temperature_flag flag=temperature_flag::NORMAL, float spoil_multiplier_parent=1.0f)
Is part of the recursive call of item::process.
void leak (map &here, Character *carrier, const tripoint &pos, item_pocket *pocke=nullptr)
pocket_type saved_type () const
bool saved_sealed () const
ret_val< item * > insert_item (const item &it, bool into_bottom=false, bool restack_charges=true, bool ignore_contents=false)
void add (const item &it, item **ret=nullptr)
adds an item to the pocket with no checks may create a new pocket
void add (const item &it, int copies, std::vector< item * > &added)
bool can_unload_liquid () const
int fill_with (const item &contained, Character &guy, int amount=0, bool allow_unseal=false, bool ignore_settings=false)
std::pair< item_location, item_pocket * > best_pocket_in_contents (item_location &this_loc, const item &it, const item *avoid, bool allow_sealed, bool ignore_settings)
Check contents of pocket to see if it contains a valid item/pocket to store the given item.
std::list< item > & edit_contents ()
int obtain_cost (const item &it) const
bool remove_internal (const std::function< bool(item &)> &filter, int &count, std::list< item > &res)
VisitResponse visit_contents (const std::function< VisitResponse(item *, item *)> &func, item *parent=nullptr)
void general_info (std::vector< iteminfo > &info, int pocket_number, bool disp_pocket_number) const
void contents_info (std::vector< iteminfo > &info, int pocket_number, bool disp_pocket_number) const
void favorite_info (std::vector< iteminfo > &info) const
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
bool is_default_state () const
bool same_contents (const item_pocket &rhs) const
void restack ()
stacks like items inside the pocket
item * restack (item *it)
same as restack(), except returns the stack where input item was placed
bool has_item_stacks_with (const item &it) const
bool better_pocket (const item_pocket &rhs, const item &it, bool nested=false) const
Whether another pocket is a better fit for an item.
bool operator== (const item_pocket &rhs) const
void set_no_rigid (const std::set< sub_bodypart_id > &is_no_rigid)
Static Public Member Functions
static void serialize_presets (JsonOut &json)
static void deserialize_presets (const JsonArray &ja)
static void load_presets ()
static void add_preset (const item_pocket::favorite_settings &preset)
static void save_presets ()
static std::vector< item_pocket::favorite_settings >::iterator find_preset (const std::string &s)
static bool has_preset (const std::string &s)
static void delete_preset (std::vector< item_pocket::favorite_settings >::iterator iter)
Public Attributes
favorite_settings settings
bool name_as_description = false
Static Public Attributes
static std::vector< item_pocket::favorite_settings > pocket_presets
Private Member Functions
ret_val< contain_code > _can_contain (const item &it, int &copies_remaining, bool ignore_contents) const
Private Attributes
pocket_type _saved_type = pocket_type::LAST
bool _saved_sealed = false
const pocket_data * data = nullptr
std::list< item > contents
bool _sealed = false
std::set< sub_bodypart_id > no_rigid
Detailed Description
Definition at line 36 of file item_pocket.h.
Member Enumeration Documentation
contain_code
enum item_pocket::contain_code : int strong
Enumerator
SUCCESS
ERR_MOD
ERR_LIQUID
ERR_GAS
ERR_TOO_BIG
ERR_TOO_HEAVY
ERR_TOO_SMALL
ERR_NO_SPACE
ERR_CANNOT_SUPPORT
ERR_FLAG
ERR_AMMO
Definition at line 39 of file item_pocket.h.
                                 : int {
             SUCCESS,
             // only mods can go into the pocket for mods
             ERR_MOD,
             // trying to put a liquid into a non-watertight container
             ERR_LIQUID,
             // trying to put a gas into a non-airtight container
             ERR_GAS,
             // trying to store an item that wouldn't fit even if the container were empty
             ERR_TOO_BIG,
             // trying to store an item that would be too heavy even if the container were empty
             ERR_TOO_HEAVY,
             // trying to store an item that's below the minimum size or length
             ERR_TOO_SMALL,
             // pocket doesn't have sufficient volume capacity left
             ERR_NO_SPACE,
             // pocket doesn't have sufficient weight capacity left
             ERR_CANNOT_SUPPORT,
             // requires a flag the item doesn't have
             ERR_FLAG,
             // requires the item to be a specific ammotype
             ERR_AMMO
         };
Constructor & Destructor Documentation
item_pocket() [1/2]
item_pocket::item_pocket () default
item_pocket() [2/2]
item_pocket::item_pocket (const pocket_data * data) inline explicit
Definition at line 129 of file item_pocket.h.
 : data( data ) {}
Member Function Documentation
_can_contain()
ret_val< item_pocket::contain_code > item_pocket::_can_contain (const item & it, int & copies_remaining, bool ignore_contents) const private
Definition at line 1465 of file item_pocket.cpp.
 {
     ret_val<item_pocket::contain_code> compatible = is_compatible( it );
     if( copies_remaining <= 0 ) {
         return ret_val<item_pocket::contain_code>::make_success();
     }
     // To prevent debugmsg. Casings can only be inserted in a magazine during firing.
     if( data->type == pocket_type::MAGAZINE && it.has_flag( flag_CASING ) ) {
         copies_remaining = 0;
         return ret_val<item_pocket::contain_code>::make_success();
     }
     if( !compatible.success() ) {
         return compatible;
     }
     if( !is_standard_type() ) {
         copies_remaining = 0;
         return ret_val<item_pocket::contain_code>::make_success();
     }
     if( it.made_of( phase_id::LIQUID ) ) {
         if( size() != 0 && !contents.front().can_combine( it ) && data->watertight ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_LIQUID, _( "can't mix liquid with contained item" ) );
         }
     } else if( size() == 1 && !it.is_frozen_liquid() &&
                contents.front().made_of( phase_id::LIQUID ) && data->watertight ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_LIQUID, _( "can't put non liquid into pocket with liquid" ) );
     }
     if( it.is_frozen_liquid() ) {
         if( size() != 0 && !contents.front().can_combine( it ) && data->watertight ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_LIQUID,
                        _( "can't mix frozen liquid with contained item in the watertight container" ) );
         }
     } else if( data->watertight ) {
         if( size() == 1 && contents.front().is_frozen_liquid() && !contents.front().can_combine( it ) ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_LIQUID,
                        _( "can't mix item with contained frozen liquid in the watertight container" ) );
         }
     }
     if( it.made_of( phase_id::GAS ) ) {
         if( size() != 0 && !contents.front().can_combine( it ) ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_GAS, _( "can't mix gas with contained item" ) );
         }
     } else if( size() == 1 && contents.front().made_of( phase_id::GAS ) ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_GAS, _( "can't put non gas into pocket with gas" ) );
     }
     if( ignore_contents ) {
         // Skip all the checks against other pocket contents.
         if( it.weight() > weight_capacity() ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_TOO_HEAVY, _( "item is too heavy" ) );
         }
         if( it.volume() > volume_capacity() ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_TOO_BIG, _( "item is too big" ) );
         }
         return ret_val<item_pocket::contain_code>::make_success();
     }
     if( data->type == pocket_type::MAGAZINE && !empty() ) {
         for( const item &contained : contents ) {
             if( contained.has_flag( flag_CASING ) ) {
                 continue;
             } else if( contained.ammo_type() != it.ammo_type() ) {
                 return ret_val<item_pocket::contain_code>::make_failure(
                            contain_code::ERR_NO_SPACE, _( "can't mix different ammo" ) );
             }
         }
     }
     if( data->ablative ) {
         if( !contents.empty() ) {
             if( contents.front().can_combine( it ) ) {
                 // Only items with charges can succeed here.
                 return ret_val<item_pocket::contain_code>::make_success();
             } else {
                 return ret_val<item_pocket::contain_code>::make_failure(
                            contain_code::ERR_NO_SPACE, _( "ablative pocket already contains a plate" ) );
             }
         }
         if( it.is_rigid() ) {
             for( const sub_bodypart_id &sbp : it.get_covered_sub_body_parts() ) {
                 if( it.is_bp_rigid( sbp ) && std::count( no_rigid.begin(), no_rigid.end(), sbp ) != 0 ) {
                     return ret_val<item_pocket::contain_code>::make_failure(
                                contain_code::ERR_NO_SPACE,
                                _( "ablative pocket is being worn with hard armor can't support hard plate" ) );
                 }
             }
         }
         copies_remaining = std::max( 0, copies_remaining - 1 );
         return ret_val<item_pocket::contain_code>::make_success();
     }
     if( data->holster && !contents.empty() ) {
         if( contents.front().can_combine( it ) ) {
             // Only items with charges can succeed here.
             return ret_val<item_pocket::contain_code>::make_success();
         } else {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_NO_SPACE, _( "holster already contains an item" ) );
         }
     }
     if( !data->ammo_restriction.empty() ) {
         const ammotype it_ammo = it.ammo_type();
         if( it.count() > remaining_ammo_capacity( it_ammo ) ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_NO_SPACE, _( "tried to put too many charges of ammo in item" ) );
         }
         // ammo restriction overrides item volume/weight and watertight/airtight data
         copies_remaining = std::max( 0, copies_remaining - remaining_ammo_capacity( it_ammo ) );
         return ret_val<item_pocket::contain_code>::make_success();
     }
     units::mass weight = it.weight();
     if( weight > weight_capacity() ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_TOO_HEAVY, _( "item is too heavy" ) );
     }
     units::volume volume = it.volume();
     if( volume > volume_capacity() ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_TOO_BIG, _( "item is too big" ) );
     }
     int fallback_capacity = it.count_by_charges() ? it.charges : copies_remaining;
     int copy_weight_capacity = weight <= 0_gram ? fallback_capacity :
                                charges_per_remaining_weight( it );
     int copy_volume_capacity = volume <= 0_ml ? fallback_capacity :
                                charges_per_remaining_volume( it );
     if( copy_weight_capacity < it.count() ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_CANNOT_SUPPORT, _( "pocket is holding too much weight" ) );
     }
     if( copy_volume_capacity < it.count() ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_NO_SPACE, _( "not enough space" ) );
     }
     if( copies_remaining > 1 ) {
         int how_many_copies_fit = std::min( { copies_remaining, copy_weight_capacity, copy_volume_capacity } );
         copies_remaining -= how_many_copies_fit;
     } else {
         copies_remaining = 0;
     }
     return ret_val<item_pocket::contain_code>::make_success();
 }
References _, pocket_data::ablative, pocket_data::ammo_restriction, item::ammo_type(), item::charges, charges_per_remaining_volume(), charges_per_remaining_weight(), contents, item::count(), item::count_by_charges(), data, empty(), ERR_CANNOT_SUPPORT, ERR_GAS, ERR_LIQUID, ERR_NO_SPACE, ERR_TOO_BIG, ERR_TOO_HEAVY, flag_CASING, GAS, item::get_covered_sub_body_parts(), item::has_flag(), pocket_data::holster, item::is_bp_rigid(), is_compatible(), item::is_frozen_liquid(), item::is_rigid(), is_standard_type(), LIQUID, item::made_of(), MAGAZINE, ret_val< T >::make_failure(), ret_val< T >::make_success(), max(), min(), no_rigid, remaining_ammo_capacity(), size(), ret_val_common::success(), pocket_data::type, item::volume(), volume_capacity(), pocket_data::watertight, item::weight(), and weight_capacity().
Referenced by can_contain().
add() [1/2]
void item_pocket::add (const item & it, int copies, std::vector< item * > & added)
Definition at line 2127 of file item_pocket.cpp.
 {
     for( auto iter = contents.insert( contents.end(), copies, it ); iter != contents.end(); iter++ ) {
         added.push_back( &*iter );
     }
 }
References contents.
add() [2/2]
void item_pocket::add (const item & it, item ** ret = nullptr)
adds an item to the pocket with no checks may create a new pocket
Definition at line 2117 of file item_pocket.cpp.
 {
     contents.push_back( it );
     if( ret == nullptr ) {
         restack();
     } else {
         *ret = restack( &contents.back() );
     }
 }
References contents, restack(), and cata::hash64_detail::ret.
Referenced by leak(), link_up_actor::link_extend_cable(), and Character::load().
add_preset()
void item_pocket::add_preset (const item_pocket::favorite_settings & preset) static
Definition at line 2385 of file item_pocket.cpp.
 {
     pocket_presets.emplace_back( preset );
     save_presets();
 }
References pocket_presets, and save_presets().
airtight()
bool item_pocket::airtight () const
Definition at line 2093 of file item_pocket.cpp.
 {
     return data->airtight;
 }
References pocket_data::airtight, and data.
all_items_ptr() [1/2]
std::list< item * > item_pocket::all_items_ptr (pocket_type pk_type)
Definition at line 495 of file item_pocket.cpp.
 {
     if( !is_type( pk_type ) ) {
         return std::list<item *>();
     }
     std::list<item *> all_items_top_level{ all_items_top() };
     for( item *it : all_items_top_level ) {
         std::list<item *> all_items_internal{ it->all_items_ptr( pk_type ) };
         all_items_top_level.insert( all_items_top_level.end(), all_items_internal.begin(),
                                     all_items_internal.end() );
     }
     return all_items_top_level;
 }
References all_items_top(), and is_type().
all_items_ptr() [2/2]
std::list< const item * > item_pocket::all_items_ptr (pocket_type pk_type) const
Definition at line 509 of file item_pocket.cpp.
 {
     if( !is_type( pk_type ) ) {
         return std::list<const item *>();
     }
     std::list<const item *> all_items_top_level{ all_items_top() };
     for( const item *it : all_items_top_level ) {
         std::list<const item *> all_items_internal{ it->all_items_ptr( pk_type ) };
         all_items_top_level.insert( all_items_top_level.end(), all_items_internal.begin(),
                                     all_items_internal.end() );
     }
     return all_items_top_level;
 }
References all_items_top(), and is_type().
all_items_top() [1/2]
std::list< item * > item_pocket::all_items_top ()
Definition at line 477 of file item_pocket.cpp.
 {
     std::list<item *> items;
     for( item &it : contents ) {
         items.push_back( &it );
     }
     return items;
 }
References contents.
Referenced by all_items_ptr(), can_reload_with(), get_child_pocket_with_parent(), holster_full(), exosuit_interact::insert_replace_activate_mod(), pocket_favorite_callback::move_item(), and item_contents::read_mods().
all_items_top() [2/2]
std::list< const item * > item_pocket::all_items_top () const
Definition at line 486 of file item_pocket.cpp.
 {
     std::list<const item *> items;
     for( const item &it : contents ) {
         items.push_back( &it );
     }
     return items;
 }
References contents.
allows_speedloader()
bool item_pocket::allows_speedloader (const itype_id & speedloader_id) const
Definition at line 2103 of file item_pocket.cpp.
 {
     if( data->allowed_speedloaders.empty() ) {
         return false;
     } else {
         return data->allowed_speedloaders.count( speedloader_id );
     }
 }
References pocket_data::allowed_speedloaders, and data.
Referenced by can_reload_with().
ammo_capacity()
int item_pocket::ammo_capacity (const ammotype & ammo) const
Definition at line 732 of file item_pocket.cpp.
 {
     const auto found_ammo = data->ammo_restriction.find( ammo );
     if( found_ammo == data->ammo_restriction.end() ) {
         return 0;
     } else {
         return found_ammo->second;
     }
 }
References pocket_data::ammo_restriction, and data.
Referenced by can_reload_with(), fill_with(), item::fill_with(), general_info(), and remaining_ammo_capacity().
ammo_consume()
int item_pocket::ammo_consume (int qty)
Definition at line 709 of file item_pocket.cpp.
 {
     int need = qty;
     int used = 0;
     std::list<item>::iterator it;
     for( it = contents.begin(); it != contents.end(); ) {
         if( it->has_flag( flag_CASING ) ) {
             it++;
             continue;
         }
         if( need >= it->charges ) {
             need -= it->charges;
             used += it->charges;
             it = contents.erase( it );
         } else {
             it->charges -= need;
             used += need;
             break;
         }
     }
     return used;
 }
References contents, and flag_CASING.
ammo_types()
std::set< ammotype > item_pocket::ammo_types () const
Definition at line 760 of file item_pocket.cpp.
 {
     std::set<ammotype> ret;
     for( const std::pair<const ammotype, int> &type_pair : data->ammo_restriction ) {
         ret.emplace( type_pair.first );
     }
     return ret;
 }
References pocket_data::ammo_restriction, data, and cata::hash64_detail::ret.
Referenced by general_info().
back() [1/2]
item & item_pocket::back ()
Definition at line 528 of file item_pocket.cpp.
 {
     return contents.back();
 }
References contents.
back() [2/2]
const item & item_pocket::back () const
Definition at line 533 of file item_pocket.cpp.
 {
     return contents.back();
 }
References contents.
best_pocket_in_contents()
std::pair< item_location, item_pocket * > item_pocket::best_pocket_in_contents (item_location & this_loc, const item & it, const item * avoid, bool allow_sealed, bool ignore_settings)
Check contents of pocket to see if it contains a valid item/pocket to store the given item.
Parameters
ret Used to cache and return a pocket if a valid one was found.
pocket The item_pocket pocket to recursively look through.
parent The parent item location, most likely provided by initial call to best_pocket.
it The item to try and store.
avoid Item to avoid trying to search for/inside of.
Returns
A non-nullptr if a suitable pocket is found.
Definition at line 2220 of file item_pocket.cpp.
 {
     std::pair<item_location, item_pocket *> ret( this_loc, nullptr );
     // If the current pocket has restrictions or blacklists the item or is a holster,
     // try the nested pocket regardless of whether it's soft or rigid.
     const bool ignore_rigidity =
         !settings.accepts_item( it ) ||
         !get_pocket_data()->get_flag_restrictions().empty() ||
         settings.priority() > 0 || is_holster();
     for( item &contained_item : contents ) {
         if( &contained_item == &it || &contained_item == avoid ) {
             continue;
         }
         item_location new_loc( this_loc, &contained_item );
         std::pair<item_location, item_pocket *> nested_pocket = contained_item.best_pocket( it, new_loc,
                 avoid, allow_sealed, ignore_settings, /*nested=*/true, ignore_rigidity );
         if( nested_pocket.second != nullptr &&
             ( ret.second == nullptr ||
               ret.second->better_pocket( *nested_pocket.second, it, /*nested=*/true ) ) ) {
             ret = nested_pocket;
         }
     }
     return ret;
 }
References item_pocket::favorite_settings::accepts_item(), contents, pocket_data::get_flag_restrictions(), get_pocket_data(), is_holster(), item_pocket::favorite_settings::priority(), cata::hash64_detail::ret, and settings.
Referenced by Character::store().
best_quality()
int item_pocket::best_quality (const quality_id & id) const
Definition at line 2367 of file item_pocket.cpp.
 {
     int ret = 0;
     for( const item &it : contents ) {
         ret = std::max( ret, it.get_quality( id ) );
     }
     return ret;
 }
References contents, max(), and cata::hash64_detail::ret.
better_pocket()
bool item_pocket::better_pocket (const item_pocket & rhs, const item & it, bool nested = false) const
Whether another pocket is a better fit for an item.
This assumes that both pockets are able to and allowed to contain the item.
Definition at line 355 of file item_pocket.cpp.
 {
     if( this->settings.priority() != rhs.settings.priority() ) {
         // Priority overrides all other factors.
         return rhs.settings.priority() > this->settings.priority();
     }
     // if we've somehow bypassed the pocket autoinsert rules, check them here
     if( !rhs.settings.accepts_item( it ) ) {
         return false;
     } else if( !this->settings.accepts_item( it ) ) {
         return true;
     }
     const bool rhs_whitelisted = !rhs.settings.get_item_whitelist().empty() ||
                                  !rhs.settings.get_category_whitelist().empty();
     const bool lhs_whitelisted = !this->settings.get_item_whitelist().empty() ||
                                  !this->settings.get_category_whitelist().empty();
     if( rhs_whitelisted != lhs_whitelisted ) {
         return rhs_whitelisted;
     }
     const bool rhs_it_stack = rhs.has_item_stacks_with( it );
     if( has_item_stacks_with( it ) != rhs_it_stack ) {
         return rhs_it_stack;
     }
     if( data->ammo_restriction.empty() != rhs.data->ammo_restriction.empty() ) {
         // pockets restricted by ammo should try to get filled first
         return !rhs.data->ammo_restriction.empty();
     }
     if( data->get_flag_restrictions().empty() != rhs.data->get_flag_restrictions().empty() ) {
         // pockets restricted by flag should try to get filled first
         return !rhs.data->get_flag_restrictions().empty();
     }
     if( it.is_comestible() && it.get_comestible()->spoils != 0_seconds ) {
         // a lower spoil multiplier is better
         return rhs.spoil_multiplier() < spoil_multiplier();
     }
     if( it.made_of( phase_id::SOLID ) && !it.is_frozen_liquid() ) {
         if( data->watertight != rhs.data->watertight ) {
             return !rhs.data->watertight;
         }
     }
     if( it.is_frozen_liquid() ) {
         if( data->watertight != rhs.data->watertight ) {
             return rhs.data->watertight;
         }
     }
     //Skip irrelevant properties of nested containers
     if( nested ) {
         return false;
     }
     if( rhs.data->extra_encumbrance != data->extra_encumbrance ) {
         // pockets with less extra encumbrance should be prioritized
         return rhs.data->extra_encumbrance < data->extra_encumbrance;
     }
     if( data->ripoff != rhs.data->ripoff ) {
         // pockets without ripoff chance should be prioritized
         return rhs.data->ripoff < data->ripoff;
     }
     if( data->rigid != rhs.data->rigid ) {
         // Prefer rigid containers, as their fixed volume is wasted unless filled
         return rhs.data->rigid;
     }
     if( remaining_volume() != rhs.remaining_volume() ) {
         // we want the least amount of remaining volume
         return rhs.remaining_volume() < remaining_volume();
     }
     return rhs.obtain_cost( it ) < obtain_cost( it );
 }
References item_pocket::favorite_settings::accepts_item(), pocket_data::ammo_restriction, data, pocket_data::extra_encumbrance, item_pocket::favorite_settings::get_category_whitelist(), item::get_comestible(), pocket_data::get_flag_restrictions(), item_pocket::favorite_settings::get_item_whitelist(), has_item_stacks_with(), item::is_comestible(), item::is_frozen_liquid(), item::made_of(), obtain_cost(), item_pocket::favorite_settings::priority(), remaining_volume(), pocket_data::rigid, pocket_data::ripoff, settings, SOLID, spoil_multiplier(), and pocket_data::watertight.
Referenced by Character::store().
can_contain() [1/2]
ret_val< item_pocket::contain_code > item_pocket::can_contain (const item & it, bool ignore_contents = false) const
Can the pocket contain the specified item?
Parameters
it The item being put in
ignore_contents If true, only check for compatible phase, size, and weight, skipping the more CPU-intensive checks against other contents. Optional, default false.
copies_remaining An optional integer reference that will be set to the number of item copies that won't fit
Definition at line 1458 of file item_pocket.cpp.
 {
     int copies = 1;
     return _can_contain( it, copies, ignore_contents );
 }
References _can_contain().
Referenced by item::fill_with(), pickup_inventory_preset::get_denial(), outfit::holster_opts(), insert_item(), exosuit_interact::insert_replace_activate_mod(), is_funnel_container(), item::migrate_content_item(), pocket_favorite_callback::move_item(), move_to_parent_pocket_recursive(), overflow(), and remaining_capacity_for_item().
can_contain() [2/2]
ret_val< item_pocket::contain_code > item_pocket::can_contain (const item & it, int & copies_remaining, bool ignore_contents = false) const
Definition at line 1452 of file item_pocket.cpp.
 {
     return _can_contain( it, copies_remaining, ignore_contents );
 }
References _can_contain().
can_contain_liquid()
bool item_pocket::can_contain_liquid (bool held_or_ground) const
Definition at line 1627 of file item_pocket.cpp.
 {
     if( held_or_ground ) {
         return data->watertight;
     } else {
         if( will_spill() ) {
             return false;
         }
         return data->watertight;
     }
 }
References data, pocket_data::watertight, and will_spill().
can_reload_with()
bool item_pocket::can_reload_with (const item & ammo, bool now) const
returns whether this pocket can be reloaded with the specified item.
Parameters
ammo item to be loaded in
now whether the currently contained ammo/magazine should be taken into account
Definition at line 1644 of file item_pocket.cpp.
 {
     if( is_type( pocket_type::CONTAINER ) ) {
         // Only watertight container pockets are reloadable
         if( !watertight() ) {
             return false;
         }
         // CONTAINER pockets can reload liquids only
         if( !ammo.made_of( phase_id::LIQUID ) ) {
             return false;
         }
     }
     if( ammo.has_flag( flag_SPEEDLOADER ) ) {
         // The speedloader needs to be compatible,
         // The ammo in it needs to be compatible,
         // and the opcket needs to have enough space (except casings)
         return allows_speedloader( ammo.typeId() ) &&
                is_compatible( ammo.loaded_ammo() ).success() &&
                ( remaining_ammo_capacity( ammo.loaded_ammo().ammo_type() ) >= ammo.ammo_remaining() );
     }
     if( ammo.has_flag( flag_SPEEDLOADER_CLIP ) ) {
         // The speedloader clip needs to be compatible,
         // The ammo in it needs to be compatible,
         // and the pocket don't needs have enough space (except casings(if any))
         return allows_speedloader( ammo.typeId() ) &&
                is_compatible( ammo.loaded_ammo() ).success() &&
                ( remaining_ammo_capacity( ammo.loaded_ammo().ammo_type() ) + ammo_capacity(
                      ammo.loaded_ammo().ammo_type() ) > ammo_capacity( ammo.loaded_ammo().ammo_type() ) );
     }
     if( !is_compatible( ammo ).success() ) {
         return false;
     }
     if( !now ) {
         return true;
     } else {
         // Require that the new ammo can fit in with the old ammo.
         // No need to combine if empty.
         if( empty() ) {
             return true;
         }
         if( is_type( pocket_type::MAGAZINE ) ) {
             // Reloading is refused if
             // Pocket is full of ammo (casings are ignored)
             // Ammos are of different ammo type
             // If either of ammo is liquid while the other is not or they are different types
             if( full( false ) ) {
                 return false;
             }
             for( const item *loaded : all_items_top() ) {
                 if( loaded->has_flag( flag_CASING ) ) {
                     continue;
                 }
                 if( loaded->ammo_type() != ammo.ammo_type() ) {
                     return false;
                 }
                 if( loaded->made_of( phase_id::LIQUID ) || ammo.made_of( phase_id::LIQUID ) ) {
                     bool cant_combine = !loaded->made_of( phase_id::LIQUID ) || !ammo.made_of( phase_id::LIQUID ) ||
                                         loaded->type != ammo.type;
                     if( cant_combine ) {
                         return false;
                     }
                 }
             }
             return true;
         } else if( is_type( pocket_type::MAGAZINE_WELL ) ) {
             // Reloading is refused if there already is full magazine here
             // Reloading with another identical mag with identical contents is also pointless so it is not allowed
             // Pocket can't know what ammo are compatible with the item so that is checked elsewhere
             return !front().is_magazine_full() && !( front().typeId() == ammo.typeId() &&
                     front().same_contents( ammo ) );
         } else if( is_type( pocket_type::CONTAINER ) ) {
             // Reloading is possible if liquid combines with old liquid
             if( front().can_combine( ammo ) ) {
                 return true;
             }
         }
     }
     return false;
 }
References all_items_top(), allows_speedloader(), ammo_capacity(), item::ammo_remaining(), item::ammo_type(), item::can_combine(), CONTAINER, empty(), flag_CASING, flag_SPEEDLOADER, flag_SPEEDLOADER_CLIP, front(), full(), item::has_flag(), is_compatible(), item::is_magazine_full(), is_type(), LIQUID, item::loaded_ammo(), item::made_of(), MAGAZINE, MAGAZINE_WELL, remaining_ammo_capacity(), item::same_contents(), item::type, item::typeId(), and watertight().
can_unload_liquid()
bool item_pocket::can_unload_liquid () const
Definition at line 2134 of file item_pocket.cpp.
 {
     if( contents.size() != 1 ) {
         return true;
     }
     const item &cts = contents.front();
     bool cts_is_frozen_liquid = cts.made_of_from_type( phase_id::LIQUID ) &&
                                 cts.made_of( phase_id::SOLID );
     return will_spill() || !cts_is_frozen_liquid;
 }
References contents, LIQUID, item::made_of(), item::made_of_from_type(), SOLID, and will_spill().
casings_handle()
void item_pocket::casings_handle (const std::function< bool(item &)> & func)
Definition at line 769 of file item_pocket.cpp.
 {
     for( auto it = contents.begin(); it != contents.end(); ) {
         if( it->has_flag( flag_CASING ) ) {
             it->unset_flag( flag_CASING );
             if( func( *it ) ) {
                 it = contents.erase( it );
                 continue;
             }
             // didn't handle the casing so reset the flag ready for next call
             it->set_flag( flag_CASING );
         }
         ++it;
     }
 }
References contents, and flag_CASING.
charges_per_remaining_volume()
int item_pocket::charges_per_remaining_volume (const item & it) const
Definition at line 2331 of file item_pocket.cpp.
 {
     if( it.count_by_charges() ) {
         units::volume non_it_volume = volume_capacity();
         int contained_charges = 0;
         for( const item &contained : contents ) {
             if( contained.stacks_with( it ) ) {
                 contained_charges += contained.charges;
             } else {
                 non_it_volume -= contained.volume();
             }
         }
         return it.charges_per_volume( non_it_volume, true ) - contained_charges;
     } else {
         return it.charges_per_volume( remaining_volume(), true );
     }
 }
References item::charges_per_volume(), contents, item::count_by_charges(), remaining_volume(), and volume_capacity().
Referenced by _can_contain(), fill_with(), item::fill_with(), and remaining_capacity_for_item().
charges_per_remaining_weight()
int item_pocket::charges_per_remaining_weight (const item & it) const
Definition at line 2349 of file item_pocket.cpp.
 {
     if( it.count_by_charges() ) {
         units::mass non_it_weight = weight_capacity();
         int contained_charges = 0;
         for( const item &contained : contents ) {
             if( contained.stacks_with( it ) ) {
                 contained_charges += contained.charges;
             } else {
                 non_it_weight -= contained.weight();
             }
         }
         return it.charges_per_weight( non_it_weight, true ) - contained_charges;
     } else {
         return it.charges_per_weight( remaining_weight(), true );
     }
 }
References item::charges_per_weight(), contents, item::count_by_charges(), remaining_weight(), and weight_capacity().
Referenced by _can_contain(), fill_with(), item::fill_with(), and remaining_capacity_for_item().
clear_items()
void item_pocket::clear_items ()
Definition at line 1946 of file item_pocket.cpp.
 {
     contents.clear();
 }
References contents.
Referenced by turret_data::post_fire().
contains_phase()
bool item_pocket::contains_phase (phase_id phase) const
Definition at line 1639 of file item_pocket.cpp.
 {
     return !empty() && contents.front().made_of( phase );
 }
References contents, and empty().
contains_volume()
units::volume item_pocket::contains_volume () const
Definition at line 2308 of file item_pocket.cpp.
 {
     units::volume vol = 0_ml;
     for( const item &it : contents ) {
         vol += it.volume();
     }
     return vol;
 }
References contents.
Referenced by contents_info(), and remaining_volume().
contains_weight()
units::mass item_pocket::contains_weight () const
Definition at line 2317 of file item_pocket.cpp.
 {
     units::mass weight = 0_gram;
     for( const item &it : contents ) {
         weight += it.weight();
     }
     return weight;
 }
References contents.
Referenced by contents_info(), and remaining_weight().
contents_info()
void item_pocket::contents_info (std::vector< iteminfo > & info, int pocket_number, bool disp_pocket_number) const
Definition at line 1169 of file item_pocket.cpp.
 {
     if( is_forbidden() ) {
         return;
     }
     const std::string space = "  ";
     insert_separation_line( info );
     if( disp_pocket_number ) {
         if( sealable() ) {
             info.emplace_back( "DESCRIPTION", string_format( _( "<bold>%s pocket %d</bold>" ),
                                translated_sealed_prefix(),
                                pocket_number ) );
         } else if( is_ablative() && !contents.empty() ) {
             info.emplace_back( "DESCRIPTION", string_format( _( "<bold>Pocket %d</bold>: %s" ),
                                pocket_number, contents.front().display_name() ) );
         } else {
             info.emplace_back( "DESCRIPTION", string_format( _( "<bold>Pocket %d</bold>" ),
                                pocket_number ) );
         }
     }
     if( contents.empty() ) {
         info.emplace_back( "DESCRIPTION", _( "This pocket is empty." ) );
         return;
     }
     if( sealed() ) {
         info.emplace_back( "DESCRIPTION", _( "This pocket is <info>sealed</info>." ) );
     }
     // NOLINTNEXTLINE(cata-translate-string-literal)
     const std::string cont_type_str = string_format( "{%d}CONTAINER", pocket_number );
     // NOLINTNEXTLINE(cata-translate-string-literal)
     const std::string arm_type_str = string_format( "{%d}ARMOR", pocket_number );
     if( is_ablative() ) {
         // if we have contents for an ablative pocket display the armor data
         if( !contents.empty() ) {
             const item &ablative_armor = contents.front();
             info.emplace_back( arm_type_str, string_format( "%s%s", _( "Coverage:" ), space ), "",
                                iteminfo::no_newline,
                                ablative_armor.get_avg_coverage() );
             //~ (M)elee coverage
             info.emplace_back( arm_type_str, string_format( "%s%s%s", space, _( "(M):" ), space ), "",
                                iteminfo::no_newline,
                                ablative_armor.get_avg_coverage( item::cover_type::COVER_MELEE ) );
             //~ (R)anged coverage
             info.emplace_back( arm_type_str, string_format( "%s%s%s", space, _( "(R):" ), space ), "",
                                iteminfo::no_newline,
                                ablative_armor.get_avg_coverage( item::cover_type::COVER_RANGED ) );
             //~ (V)itals coverage
             info.emplace_back( arm_type_str, string_format( "%s%s%s", space, _( "(V):" ), space ), "",
                                iteminfo::no_flags,
                                ablative_armor.get_avg_coverage( item::cover_type::COVER_VITALS ) );
             info.back().bNewLine = true;
             size_t idx = 0;
             const std::vector<damage_info_order> &all_ablate = damage_info_order::get_all(
                         damage_info_order::info_type::ABLATE );
             for( const damage_info_order &dio : all_ablate ) {
                 std::string label = string_format( idx == 0 ? _( "<bold>Protection</bold>: %s: " ) :
                                                    pgettext( "protection info", " %s: " ),
                                                    uppercase_first_letter( dio.dmg_type->name.translated() ) );
                 iteminfo::flags flgs = idx == all_ablate.size() - 1 ?
                                        iteminfo::is_decimal : iteminfo::no_newline | iteminfo::is_decimal;
                 info.emplace_back( arm_type_str, label, "", flgs, ablative_armor.resist( dio.dmg_type ) );
                 idx++;
             }
         }
     } else if( data->ammo_restriction.empty() ) {
         // With no ammo_restriction defined, show current volume/weight, and total capacity
         info.emplace_back( vol_to_info( cont_type_str, _( "Volume: " ),
                                         contains_volume() ) );
         info.emplace_back( vol_to_info( cont_type_str, _( " of " ),
                                         volume_capacity() ) );
         info.back().bNewLine = true;
         info.emplace_back( weight_to_info( cont_type_str, _( "Weight: " ),
                                            contains_weight() ) );
         info.emplace_back( weight_to_info( cont_type_str, _( " of " ),
                                            weight_capacity() ) );
     } else {
         // With ammo_restriction, total capacity does not matter, but show current volume/weight
         info.emplace_back( vol_to_info( cont_type_str, _( "Volume: " ),
                                         contains_volume() ) );
         info.back().bNewLine = true;
         info.emplace_back( weight_to_info( cont_type_str, _( "Weight: " ),
                                            contains_weight() ) );
     }
     if( remaining_volume() < 0_ml || remaining_weight() < 0_gram ) {
         info.emplace_back( "DESCRIPTION",
                            colorize( _( "This pocket is over capacity and will spill if moved!" ), c_red ) );
     }
     // ablative pockets have their contents displayed earlier in the UI
     if( !is_ablative() ) {
         std::vector<std::pair<item const *, int>> counted_contents;
         bool contents_header = false;
         for( const item &contents_item : contents ) {
             if( !contents_header ) {
                 info.emplace_back( "DESCRIPTION", _( "<bold>Contents of this pocket</bold>:" ) );
                 contents_header = true;
             }
             const translation &desc = contents_item.type->description;
             if( contents_item.made_of_from_type( phase_id::LIQUID ) ) {
                 info.emplace_back( "DESCRIPTION", colorize( space + contents_item.display_name(),
                                    contents_item.color_in_inventory() ) );
                 info.emplace_back( vol_to_info( cont_type_str, desc + space, contents_item.volume() ) );
             } else {
                 bool found = false;
                 for( std::pair<item const *, int> &content : counted_contents ) {
                     if( content.first->display_stacked_with( contents_item ) ) {
                         content.second += 1;
                         found = true;
                     }
                 }
                 if( !found ) {
                     std::pair<item const *, int> new_content( &contents_item, 1 );
                     counted_contents.push_back( new_content );
                 }
             }
         }
         for( std::pair<item const *, int> content : counted_contents ) {
             if( content.second > 1 ) {
                 info.emplace_back( "DESCRIPTION",
                                    space + std::to_string( content.second ) + " " + colorize( content.first->display_name(
                                                content.second ), content.first->color_in_inventory() ) );
             } else {
                 info.emplace_back( "DESCRIPTION", space + colorize( content.first->display_name(),
                                    content.first->color_in_inventory() ) );
             }
         }
     }
 }
References _, damage_info_order::ABLATE, pocket_data::ammo_restriction, c_red, colorize(), contains_volume(), contains_weight(), contents, item::COVER_MELEE, item::COVER_RANGED, item::COVER_VITALS, data, damage_info_order::get_all(), item::get_avg_coverage(), insert_separation_line(), is_ablative(), iteminfo::is_decimal, is_forbidden(), LIQUID, iteminfo::no_flags, iteminfo::no_newline, pgettext, remaining_volume(), remaining_weight(), item::resist(), sealable(), sealed(), keycode::space, string_format(), to_string(), translated_sealed_prefix(), uppercase_first_letter(), vol_to_info(), volume_capacity(), weight_capacity(), and weight_to_info().
Referenced by exosuit_interact::draw_iteminfo(), and pocket_favorite_callback::refresh().
delete_preset()
void item_pocket::delete_preset (std::vector< item_pocket::favorite_settings >::iterator iter) static
Definition at line 2417 of file item_pocket.cpp.
 {
     pocket_presets.erase( iter );
     save_presets();
 }
References pocket_presets, and save_presets().
deserialize()
void item_pocket::deserialize (const JsonObject & data)
Definition at line 258 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     data.read( "contents", contents );
     int saved_type_int;
     data.read( "pocket_type", saved_type_int );
     _saved_type = static_cast<pocket_type>( saved_type_int );
     data.read( "_sealed", _sealed );
     _saved_sealed = _sealed;
     data.read( "no_rigid", no_rigid );
     if( data.has_member( "favorite_settings" ) ) {
         data.read( "favorite_settings", this->settings );
     } else {
         this->settings.clear();
     }
 }
References _saved_sealed, _saved_type, _sealed, item_pocket::favorite_settings::clear(), contents, data, no_rigid, and settings.
deserialize_presets()
void item_pocket::deserialize_presets (const JsonArray & ja) static
Definition at line 2458 of file item_pocket.cpp.
 {
     pocket_presets.clear();
     for( JsonObject jo : ja ) {
         item_pocket::favorite_settings preset;
         preset.deserialize( jo );
         pocket_presets.emplace_back( preset );
     }
 }
References item_pocket::favorite_settings::deserialize(), and pocket_presets.
Referenced by load_presets().
detonate()
bool item_pocket::detonate (const tripoint & p, std::vector< item > & drops)
Definition at line 888 of file item_pocket.cpp.
 {
     const auto new_end = std::remove_if( contents.begin(), contents.end(), [&pos, &drops]( item & it ) {
         return it.detonate( pos, drops );
     } );
     if( new_end != contents.end() ) {
         contents.erase( new_end, contents.end() );
         // If any of the contents explodes, so does the container
         return true;
     }
     return false;
 }
References contents, and math_opers::pos().
edit_contents()
std::list< item > & item_pocket::edit_contents ()
Definition at line 2192 of file item_pocket.cpp.
 {
     return contents;
 }
References contents.
empty()
bool item_pocket::empty () const
Definition at line 2040 of file item_pocket.cpp.
 {
     return contents.empty();
 }
References contents.
Referenced by _can_contain(), can_reload_with(), outfit::clatter_sound(), contains_phase(), general_info(), outfit::grab_drop_pockets(), exosuit_interact::insert_replace_activate_mod(), is_default_state(), Character::load(), on_pickup(), overflow(), seal(), stacks_with(), and item_contents::update_modified_pockets().
favorite_info()
void item_pocket::favorite_info (std::vector< iteminfo > & info) const
Definition at line 1307 of file item_pocket.cpp.
 {
     settings.info( info );
 }
References item_pocket::favorite_settings::info(), and settings.
Referenced by pocket_favorite_callback::refresh().
fill_with()
int item_pocket::fill_with (const item & contained, Character & guy, int amount = 0, bool allow_unseal = false, bool ignore_settings = false)
Definition at line 2146 of file item_pocket.cpp.
 {
     int num_contained = 0;
     if( !contained.count_by_charges() || amount <= 0 ) {
         return 0;
     }
     if( !ignore_settings && !settings.accepts_item( contained ) ) {
         return 0;
     }
     if( !allow_unseal && sealed() ) {
         return 0;
     }
     item contained_item( contained );
     item_location loc;
     ammotype ammo = contained.ammo_type();
     if( ammo_capacity( ammo ) ) {
         contained_item.charges = std::min( amount - num_contained,
                                            remaining_ammo_capacity( ammo ) );
     } else {
         contained_item.charges = std::min( { amount - num_contained,
                                              charges_per_remaining_volume( contained_item ),
                                              charges_per_remaining_weight( contained_item )
                                            } );
     }
     if( contained_item.charges == 0 ) {
         return 0;
     }
     contained_item.handle_pickup_ownership( guy );
     ret_val<item *> result = insert_item( contained_item );
     if( !result.success() ) {
         debugmsg( "charges per remaining pocket volume does not fit in that very volume" );
         return 0;
     }
     num_contained += contained_item.charges;
     if( allow_unseal ) {
         unseal();
     }
     result.value()->on_pickup( guy );
     return num_contained;
 }
References item_pocket::favorite_settings::accepts_item(), ammo_capacity(), item::ammo_type(), item::charges, charges_per_remaining_volume(), charges_per_remaining_weight(), item::count_by_charges(), debugmsg, item::handle_pickup_ownership(), insert_item(), min(), remaining_ammo_capacity(), sealed(), settings, ret_val_common::success(), unseal(), and ret_val< T >::value().
Referenced by outfit::add_stash().
find_preset()
std::vector< item_pocket::favorite_settings >::iterator item_pocket::find_preset (const std::string & s) static
Definition at line 2406 of file item_pocket.cpp.
 {
     std::vector<item_pocket::favorite_settings>::iterator iter = std::find_if( pocket_presets.begin(),
             pocket_presets.end(),
     [&s]( const item_pocket::favorite_settings & preset ) {
         return preset.get_preset_name().value() == s;
     } );
     return iter;
 }
References pocket_presets.
Referenced by has_preset().
front() [1/2]
item & item_pocket::front ()
Definition at line 538 of file item_pocket.cpp.
 {
     return contents.front();
 }
References contents.
Referenced by can_reload_with(), pickup_inventory_preset::get_denial(), item_location::impl::item_in_container::parent_pocket(), and item_contents::total_container_capacity().
front() [2/2]
const item & item_pocket::front () const
Definition at line 543 of file item_pocket.cpp.
 {
     return contents.front();
 }
References contents.
full()
bool item_pocket::full (bool allow_bucket) const
Definition at line 2045 of file item_pocket.cpp.
 {
     if( !allow_bucket && will_spill() ) {
         return true;
     }
     if( is_type( pocket_type::MAGAZINE ) && !data->ammo_restriction.empty() ) {
         // Fullness from remaining ammo capacity instead of volume
         for( const item &it : contents ) {
             if( it.has_flag( flag_CASING ) ) {
                 continue;
             } else {
                 return remaining_ammo_capacity( it.ammo_type() ) == 0;
             }
         }
         return false;
     }
     return remaining_volume() == 0_ml;
 }
References pocket_data::ammo_restriction, contents, data, flag_CASING, is_type(), MAGAZINE, remaining_ammo_capacity(), remaining_volume(), and will_spill().
Referenced by can_reload_with().
general_info()
void item_pocket::general_info (std::vector< iteminfo > & info, int pocket_number, bool disp_pocket_number) const
Definition at line 971 of file item_pocket.cpp.
 {
     if( disp_pocket_number ) {
         const std::string pocket_num = string_format( _( "Pocket %d:" ), pocket_number );
         info.emplace_back( "DESCRIPTION", pocket_num );
     }
     if( !get_description().empty() ) {
         info.emplace_back( "DESCRIPTION", string_format( "<info>%s</info>",
                            get_description().translated() ) );
     } else if( name_as_description ) {
         // fallback to the original items name as a description
         info.emplace_back( "DESCRIPTION", string_format( "<info>%s</info>",
                            get_name().translated() ) );
     }
     // NOLINTNEXTLINE(cata-translate-string-literal)
     const std::string cont_type_str = string_format( "{%d}CONTAINER", pocket_number );
     // NOLINTNEXTLINE(cata-translate-string-literal)
     const std::string base_type_str = string_format( "{%d}BASE", pocket_number );
     // Show volume/weight for normal containers, or ammo capacity if ammo_restriction is defined if its an ablative pocket don't display any info
     if( is_ablative() ) {
         // its an ablative pocket volume and weight maxes don't matter
         info.emplace_back( "DESCRIPTION",
                            _( "Holds a <info>single armored plate</info>." ) );
     } else if( data->ammo_restriction.empty() ) {
         info.push_back( vol_to_info( cont_type_str, _( "Volume: " ),
                                      volume_capacity(), 2, false ) );
         info.push_back( weight_to_info( cont_type_str, _( "  Weight: " ),
                                         weight_capacity(), 2, false ) );
         info.back().bNewLine = true;
     } else {
         std::vector<std::pair<std::string, int>> fmts;
         for( const ammotype &at : ammo_types() ) {
             int capacity = ammo_capacity( at );
             fmts.emplace_back( string_format( n_gettext( "<num> round of %s",
                                               "<num> rounds of %s", capacity ),
                                               at->name() ),
                                capacity );
         }
         std::sort( fmts.begin(), fmts.end(), localized_compare );
         for( const std::pair<std::string, int> &fmt : fmts ) {
             // NOLINTNEXTLINE(cata-translate-string-literal)
             info.emplace_back( string_format( "{%d}MAGAZINE", pocket_number ), _( "Holds: " ), fmt.first,
                                iteminfo::no_flags,
                                fmt.second );
         }
     }
     if( data->max_item_length != 0_mm && !is_ablative() ) {
         info.back().bNewLine = true;
         // if the item has no minimum length then keep it in the same units as max
         if( data->min_item_length == 0_mm ) {
             info.emplace_back( base_type_str, _( "Item length: " ),
                                string_format( "<num> %s", length_units( data->max_item_length ) ),
                                iteminfo::no_newline,
                                0 );
         } else {
             info.emplace_back( base_type_str, _( "Item length: " ),
                                string_format( "<num> %s", length_units( data->min_item_length ) ),
                                iteminfo::no_newline,
                                convert_length( data->min_item_length ), data->min_item_length.value() );
         }
         info.emplace_back( base_type_str, _( " to " ),
                            string_format( "<num> %s", length_units( data->max_item_length ) ),
                            iteminfo::no_flags,
                            convert_length( data->max_item_length ), data->max_item_length.value() );
     } else if( data->min_item_length > 0_mm && !is_ablative() ) {
         info.back().bNewLine = true;
         info.emplace_back( base_type_str, _( "Minimum item length: " ),
                            string_format( "<num> %s", length_units( data->min_item_length ) ),
                            iteminfo::no_flags,
                            convert_length( data->min_item_length ), data->min_item_length.value() );
     }
     if( data->min_item_volume > 0_ml ) {
         std::string fmt = string_format( "<num> %s", volume_units_abbr() );
         info.emplace_back( base_type_str, _( "Minimum item volume: " ), fmt,
                            iteminfo::lower_is_better | iteminfo::is_three_decimal,
                            convert_volume( data->min_item_volume.value(), nullptr ), data->min_item_volume.value() );
     }
     if( data->max_item_volume ) {
         std::string fmt = string_format( "<num> %s", volume_units_abbr() );
         info.emplace_back( base_type_str, _( "Maximum item volume: " ), fmt,
                            iteminfo::is_three_decimal, convert_volume( data->max_item_volume.value().value(), nullptr ),
                            data->max_item_volume.value().value() );
     }
     info.emplace_back( base_type_str, _( "Base moves to remove item: " ),
                        "<num>", iteminfo::lower_is_better, data->moves );
     if( !data->material_restriction.empty() ) {
         std::string materials;
         bool first = true;
         for( material_id mat : data->material_restriction ) {
             if( first ) {
                 materials += mat.obj().name();
                 first = false;
             } else {
                 materials += ", " + mat.obj().name();
             }
         }
         info.emplace_back( "DESCRIPTION", string_format( _( "Allowed materials: %s" ), materials ) );
     }
     if( data->rigid ) {
         info.emplace_back( "DESCRIPTION", _( "This pocket is <info>rigid</info>." ) );
     }
     if( data->holster ) {
         info.emplace_back( "DESCRIPTION",
                            _( "This is a <info>holster</info>, it only holds <info>one item at a time</info>." ) );
     }
     if( data->extra_encumbrance > 0 ) {
         info.emplace_back( "DESCRIPTION",
                            string_format( _( "Causes %d <bad>additional encumbrance</bad> while in use." ),
                                           data->extra_encumbrance ) ) ;
     }
     if( data->ripoff > 0 ) {
         info.emplace_back( "DESCRIPTION",
                            _( "Items may <bad>fall out</bad> if grabbed." ) );
     }
     if( data->activity_noise.chance > 0 ) {
         info.emplace_back( "DESCRIPTION",
                            _( "Items will <bad>make noise</bad> when you move." ) );
     }
     if( data->watertight ) {
         info.emplace_back( "DESCRIPTION",
                            _( "This pocket can <info>contain a liquid</info>." ) );
     }
     if( data->airtight ) {
         info.emplace_back( "DESCRIPTION",
                            _( "This pocket can <info>contain a gas</info>." ) );
     }
     if( will_spill() ) {
         info.emplace_back( "DESCRIPTION",
                            _( "This pocket will <bad>spill</bad> if placed into another item or worn." ) );
     }
     if( data->fire_protection ) {
         info.emplace_back( "DESCRIPTION",
                            _( "This pocket <info>protects its contents from fire</info>." ) );
     }
     if( spoil_multiplier() != 1.0f ) {
         if( spoil_multiplier() != 0.0f ) {
             info.emplace_back( "DESCRIPTION",
                                string_format( _( "Contained items spoil at <neutral>%.0f%%</neutral> their original rate." ),
                                               spoil_multiplier() * 100 ) );
         } else {
             info.emplace_back( "DESCRIPTION", _( "Contained items <info>won't spoil</info>." ) );
         }
     }
     if( data->weight_multiplier != 1.0f ) {
         info.emplace_back( "DESCRIPTION",
                            string_format( _( "Items in this pocket weigh <neutral>%.0f%%</neutral> their original weight." ),
                                           data->weight_multiplier * 100 ) );
     }
     if( data->volume_multiplier != 1.0f ) {
         info.emplace_back( "DESCRIPTION",
                            string_format(
                                _( "This pocket expands at <neutral>%.0f%%</neutral> of the rate of volume of items inside." ),
                                data->volume_multiplier * 100 ) );
     }
     // Display flags items need to be stored in this pocket
     if( !data->get_flag_restrictions().empty() ) {
         info.emplace_back( "DESCRIPTION", _( "<bold>Restrictions</bold>:" ) );
         bool first = true;
         for( const flag_id &e : data->get_flag_restrictions() ) {
             const json_flag &f = *e;
             if( !f.restriction().empty() ) {
                 if( first ) {
                     info.emplace_back( "DESCRIPTION", string_format( "* %s", f.restriction() ) );
                     first = false;
                 } else {
                     info.emplace_back( "DESCRIPTION", string_format( _( "* <bold>or</bold> %s" ), f.restriction() ) );
                 }
             }
         }
     }
     if( !no_rigid.empty() ) {
         std::vector<sub_bodypart_id> no_rigid_vec( no_rigid.begin(), no_rigid.end() );
         std::set<translation, localized_comparator> to_print = body_part_type::consolidate( no_rigid_vec );
         std::string bps = enumerate_as_string( to_print.begin(),
         to_print.end(), []( const translation & t ) {
             return t.translated();
         } );
         info.emplace_back( "DESCRIPTION", string_format( _( "<bold>Can't put hard armor on: %s</bold>:" ),
                            bps ) );
     }
 }
References _, pocket_data::activity_noise, pocket_data::airtight, ammo_capacity(), pocket_data::ammo_restriction, ammo_types(), pocket_noise::chance, body_part_type::consolidate(), convert_length(), convert_volume(), data, empty(), enumerate_as_string(), pocket_data::extra_encumbrance, pocket_data::fire_protection, get_description(), pocket_data::get_flag_restrictions(), get_name(), pocket_data::holster, is_ablative(), iteminfo::is_three_decimal, units::length_units, localized_compare, iteminfo::lower_is_better, pocket_data::material_restriction, pocket_data::max_item_length, pocket_data::max_item_volume, pocket_data::min_item_length, pocket_data::min_item_volume, pocket_data::moves, n_gettext, material_type::name(), name_as_description, iteminfo::no_flags, iteminfo::no_newline, no_rigid, string_id< T >::obj(), json_flag::restriction(), pocket_data::rigid, pocket_data::ripoff, spoil_multiplier(), string_format(), units::quantity< V, U >::value(), vol_to_info(), volume_capacity(), pocket_data::volume_multiplier, volume_units_abbr(), pocket_data::watertight, weight_capacity(), pocket_data::weight_multiplier, weight_to_info(), and will_spill().
Referenced by exosuit_interact::draw_iteminfo(), and pocket_favorite_callback::refresh().
get_description()
const translation & item_pocket::get_description () const
Definition at line 2271 of file item_pocket.cpp.
 {
     return get_pocket_data()->description;
 }
References pocket_data::description, and get_pocket_data().
Referenced by general_info().
get_item_with() [1/2]
item * item_pocket::get_item_with (const std::function< bool(const item &)> & filter)
Definition at line 1959 of file item_pocket.cpp.
 {
     for( item &it : contents ) {
         if( filter( it ) ) {
             return &it;
         }
     }
     return nullptr;
 }
References contents, and filter.
get_item_with() [2/2]
const item * item_pocket::get_item_with (const std::function< bool(const item &)> & filter) const
Definition at line 1969 of file item_pocket.cpp.
 {
     for( const item &it : contents ) {
         if( filter( it ) ) {
             return &it;
         }
     }
     return nullptr;
 }
References contents, and filter.
get_name()
const translation & item_pocket::get_name () const
Definition at line 2276 of file item_pocket.cpp.
 {
     return get_pocket_data()->name;
 }
References get_pocket_data(), and pocket_data::name.
Referenced by general_info(), leak(), and Character::load().
get_pocket_data()
const pocket_data * item_pocket::get_pocket_data () const
Definition at line 2112 of file item_pocket.cpp.
 {
     return data;
 }
References data.
Referenced by best_pocket_in_contents(), Character::can_crush_frozen_liquid(), outfit::clatter_sound(), get_description(), get_name(), exosuit_interact::get_pocket_name(), outfit::grab_drop_pockets(), holster_full(), exosuit_interact::insert_replace_activate_mod(), is_ablative(), is_holster(), is_worn_ablative(), pocket_favorite_callback::key(), item_location::max_charges_by_parent_recursive(), pocket_favorite_callback::move_item(), item_location::parents_can_contain_recursive(), pocket_favorite_callback::refresh(), and item_contents::update_modified_pockets().
gunmods() [1/2]
std::vector< item * > item_pocket::gunmods ()
Definition at line 666 of file item_pocket.cpp.
 {
     std::vector<item *> mods;
     for( item &it : contents ) {
         if( it.is_gunmod() ) {
             mods.push_back( &it );
         }
     }
     return mods;
 }
References contents, and anonymous_namespace{item_tname.cpp}::mods().
gunmods() [2/2]
std::vector< const item * > item_pocket::gunmods () const
Definition at line 677 of file item_pocket.cpp.
 {
     std::vector<const item *> mods;
     for( const item &it : contents ) {
         if( it.is_gunmod() ) {
             mods.push_back( &it );
         }
     }
     return mods;
 }
References contents, and anonymous_namespace{item_tname.cpp}::mods().
handle_liquid_or_spill()
void item_pocket::handle_liquid_or_spill (Character & guy, const item * avoid = nullptr)
Definition at line 785 of file item_pocket.cpp.
 {
     if( guy.is_npc() ) {
         spill_contents( guy.pos() );
         return;
     }
     for( auto iter = contents.begin(); iter != contents.end(); ) {
         if( iter->made_of( phase_id::LIQUID ) ) {
             while( iter->charges > 0 && liquid_handler::handle_liquid( *iter, avoid, 1 ) ) {
                 // query until completely handled or explicitly canceled
             }
             if( iter->charges == 0 ) {
                 iter = contents.erase( iter );
             } else {
                 return;
             }
         } else {
             item i_copy( *iter );
             guy.i_add_or_drop( i_copy, 1, avoid, &*iter );
             iter = contents.erase( iter );
         }
     }
 }
References contents, liquid_handler::handle_liquid(), Character::i_add_or_drop(), Character::is_npc(), LIQUID, Creature::pos(), and spill_contents().
Referenced by on_pickup(), and avatar_action::use_item().
has_any_with()
bool item_pocket::has_any_with (const std::function< bool(const item &)> & filter) const
Definition at line 523 of file item_pocket.cpp.
 {
     return std::any_of( contents.begin(), contents.end(), filter );
 }
References contents, and filter.
has_item()
bool item_pocket::has_item (const item & it) const
Definition at line 1951 of file item_pocket.cpp.
 {
     return contents.end() !=
     std::find_if( contents.begin(), contents.end(), [&it]( const item & e ) {
         return &it == &e || e.has_item( it );
     } );
 }
References contents.
Referenced by obtain_cost().
has_item_stacks_with()
bool item_pocket::has_item_stacks_with (const item & it) const
Definition at line 345 of file item_pocket.cpp.
 {
     for( const item &inside : contents ) {
         if( it.stacks_with( inside ) ) {
             return true;
         }
     }
     return false;
 }
References contents, and item::stacks_with().
Referenced by better_pocket().
has_preset()
bool item_pocket::has_preset (const std::string & s) static
Definition at line 2401 of file item_pocket.cpp.
 {
     return find_preset( s ) != pocket_presets.end();
 }
References find_preset(), and pocket_presets.
heat_up()
void item_pocket::heat_up ()
Definition at line 2376 of file item_pocket.cpp.
 {
     for( item &it : contents ) {
         if( it.has_temperature() ) {
             it.heat_up();
         }
     }
 }
References contents.
holster_full()
bool item_pocket::holster_full () const
Definition at line 2281 of file item_pocket.cpp.
 {
     const pocket_data *p_data = get_pocket_data();
     return p_data->holster && !all_items_top().empty();
 }
References all_items_top(), get_pocket_data(), and pocket_data::holster.
inherits_flags()
bool item_pocket::inherits_flags () const
Definition at line 2098 of file item_pocket.cpp.
 {
     return data->inherits_flags;
 }
References data, and pocket_data::inherits_flags.
insert_item()
ret_val< item * > item_pocket::insert_item (const item & it, bool into_bottom = false, bool restack_charges = true, bool ignore_contents = false)
Definition at line 2197 of file item_pocket.cpp.
 {
     ret_val<item_pocket::contain_code> containable = can_contain( it, ignore_contents );
     if( !containable.success() ) {
         return ret_val<item *>::make_failure( nullptr, containable.str() );
     }
     item *inserted = nullptr;
     if( !into_bottom ) {
         contents.push_front( it );
         inserted = &contents.front();
     } else {
         contents.push_back( it );
         inserted = &contents.back();
     }
     if( restack_charges ) {
         inserted = restack( inserted );
     }
     return ret_val<item *>::make_success( inserted );
 }
References can_contain(), contents, ret_val< T >::make_failure(), ret_val< T >::make_success(), restack(), ret_val_common::str(), and ret_val_common::success().
Referenced by fill_with(), item::fill_with(), exosuit_interact::insert_replace_activate_mod(), move_to_parent_pocket_recursive(), and Character::store().
is_ablative()
bool item_pocket::is_ablative () const
Definition at line 2261 of file item_pocket.cpp.
 {
     return get_pocket_data()->ablative;
 }
References pocket_data::ablative, and get_pocket_data().
Referenced by item_contents::all_ablative_armor(), contents_info(), general_info(), and item_contents::get_all_ablative_pockets().
is_compatible()
ret_val< item_pocket::contain_code > item_pocket::is_compatible (const item & it) const
Is the pocket compatible with the specified item? Does not check if the item actually fits volume/weight wise.
Parameters
it the item being put in
Definition at line 1332 of file item_pocket.cpp.
 {
     if( data->type == pocket_type::MIGRATION ) {
         // migration pockets need to always succeed
         return ret_val<item_pocket::contain_code>::make_success();
     }
     if( data->type == pocket_type::MOD ) {
         if( it.is_toolmod() || it.is_gunmod() ) {
             return ret_val<item_pocket::contain_code>::make_success();
         } else {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_MOD, _( "only mods can go into mod pocket" ) );
         }
     }
     if( data->type == pocket_type::CORPSE ) {
         // corpses can't have items stored in them the normal way,
         // we simply don't want them to "spill"
         return ret_val<item_pocket::contain_code>::make_success();
     }
     if( data->type == pocket_type::SOFTWARE ) {
         if( it.has_flag( flag_NO_DROP ) && it.has_flag( flag_IRREMOVABLE ) ) {
             return ret_val<item_pocket::contain_code>::make_success();
         } else {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_MOD, _( "only immaterial items can go into software pocket" ) );
         }
     }
     if( data->type == pocket_type::EBOOK ) {
         if( it.is_book() ) {
             return ret_val<item_pocket::contain_code>::make_success();
         } else {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_MOD, _( "only books can go into ebook pocket" ) );
         }
     }
     if( data->type == pocket_type::CABLE ) {
         if( it.has_flag( flag_CABLE_SPOOL ) ) {
             return ret_val<item_pocket::contain_code>::make_success();
         } else {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_MOD, _( "only cables can go into cable pocket" ) );
         }
     }
     if( it.has_flag( flag_NO_UNWIELD ) ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_MOD, _( "cannot unwield item" ) );
     }
     if( !data->item_id_restriction.empty() || !data->get_flag_restrictions().empty() ||
         !data->material_restriction.empty() ) {
         if( data->item_id_restriction.count( it.typeId() ) == 0 &&
             !it.has_any_flag( data->get_flag_restrictions() ) &&
             !data->material_restriction.count( it.get_base_material().id ) ) {
             return ret_val<item_pocket::contain_code>::make_failure( contain_code::ERR_FLAG,
                     _( "holster does not accept this item type or form factor" ) );
         }
     }
     // ammo restriction overrides item volume/weight and watertight/airtight data
     if( !data->ammo_restriction.empty() ) {
         if( !it.is_ammo() ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_AMMO, _( "item is not ammunition" ) );
         }
         const auto ammo_restriction_iter = data->ammo_restriction.find( it.ammo_type() );
         if( ammo_restriction_iter == data->ammo_restriction.end() ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_AMMO, _( "item is not the correct ammo type" ) );
         }
         return ret_val<item_pocket::contain_code>::make_success();
     }
     if( it.made_of( phase_id::LIQUID ) ) {
         if( !data->watertight && !it.has_flag( flag_FROM_FROZEN_LIQUID ) ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_LIQUID, _( "can't contain liquid" ) );
         }
     }
     if( it.made_of( phase_id::GAS ) ) {
         if( !data->airtight ) {
             return ret_val<item_pocket::contain_code>::make_failure(
                        contain_code::ERR_GAS, _( "can't contain gas" ) );
         }
     }
     // liquids and gases avoid the size limit altogether
     // soft items also avoid the size limit
     // count_by_charges items check volume of single charge
     if( !it.made_of( phase_id::LIQUID ) && !it.made_of( phase_id::GAS ) &&
         !it.is_frozen_liquid() && data->max_item_volume &&
         !charges_per_volume_recursive( *data->max_item_volume, it ) ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_TOO_BIG, _( "item is too big" ) );
     }
     if( it.length() > data->max_item_length ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_TOO_BIG, _( "item is too long" ) );
     }
     if( it.length() < data->min_item_length ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_TOO_SMALL, _( "item is too short" ) );
     }
     if( it.volume() < data->min_item_volume ) {
         return ret_val<item_pocket::contain_code>::make_failure(
                    contain_code::ERR_TOO_SMALL, _( "item is too small" ) );
     }
     return ret_val<item_pocket::contain_code>::make_success();
 }
References _, pocket_data::airtight, pocket_data::ammo_restriction, item::ammo_type(), CABLE, charges_per_volume_recursive(), CORPSE, data, EBOOK, ERR_AMMO, ERR_FLAG, ERR_GAS, ERR_LIQUID, ERR_MOD, ERR_TOO_BIG, ERR_TOO_SMALL, flag_CABLE_SPOOL, flag_FROM_FROZEN_LIQUID, flag_IRREMOVABLE, flag_NO_DROP, flag_NO_UNWIELD, GAS, item::get_base_material(), pocket_data::get_flag_restrictions(), item::has_any_flag(), item::has_flag(), material_type::id, item::is_ammo(), item::is_book(), item::is_frozen_liquid(), item::is_gunmod(), item::is_toolmod(), pocket_data::item_id_restriction, item::length(), LIQUID, item::made_of(), ret_val< T >::make_failure(), ret_val< T >::make_success(), pocket_data::material_restriction, pocket_data::max_item_length, pocket_data::max_item_volume, MIGRATION, pocket_data::min_item_length, pocket_data::min_item_volume, MOD, SOFTWARE, pocket_data::type, item::typeId(), item::volume(), and pocket_data::watertight.
Referenced by _can_contain(), can_reload_with(), and pocket_favorite_callback::key().
is_default_state()
bool item_pocket::is_default_state () const
Definition at line 2035 of file item_pocket.cpp.
 {
     return empty() && settings.is_null() && !sealable();
 }
References empty(), item_pocket::favorite_settings::is_null(), sealable(), and settings.
is_forbidden()
bool item_pocket::is_forbidden () const
Definition at line 2088 of file item_pocket.cpp.
 {
     return data->forbidden;
 }
References data, and pocket_data::forbidden.
Referenced by contents_info(), and pocket_favorite_callback::refresh().
is_funnel_container()
bool item_pocket::is_funnel_container (units::volume & bigger_than) const
Definition at line 450 of file item_pocket.cpp.
 {
     // should not be static, since after reloading some members of the item objects,
     // such as item types, may be invalidated.
     const std::vector<item> allowed_liquids{
         item( "water", calendar::turn_zero, 1 ),
     };
     if( !data->watertight ) {
         return false;
     }
     if( sealable() && _sealed ) {
         return false;
     }
     for( const item &liquid : allowed_liquids ) {
         if( can_contain( liquid ).success() ) {
             bigger_than = remaining_volume();
             return true;
         }
     }
     return false;
 }
References _sealed, can_contain(), data, item, remaining_volume(), sealable(), calendar::turn_zero, and pocket_data::watertight.
is_holster()
bool item_pocket::is_holster () const
Definition at line 2266 of file item_pocket.cpp.
 {
     return get_pocket_data()->holster;
 }
References get_pocket_data(), and pocket_data::holster.
Referenced by best_pocket_in_contents().
is_restricted()
bool item_pocket::is_restricted () const
Definition at line 472 of file item_pocket.cpp.
 {
     return !data->get_flag_restrictions().empty() || !data->ammo_restriction.empty();
 }
References pocket_data::ammo_restriction, data, and pocket_data::get_flag_restrictions().
is_standard_type()
bool item_pocket::is_standard_type () const
Definition at line 2081 of file item_pocket.cpp.
 {
     return data->type == pocket_type::CONTAINER ||
            data->type == pocket_type::MAGAZINE ||
            data->type == pocket_type::MAGAZINE_WELL;
 }
References CONTAINER, data, MAGAZINE, MAGAZINE_WELL, and pocket_data::type.
Referenced by _can_contain(), item_contents::all_items_top(), item_contents::all_known_contents(), item_contents::get_all_standard_pockets(), and item::is_collapsed().
is_type()
bool item_pocket::is_type (pocket_type ptype) const
Definition at line 2256 of file item_pocket.cpp.
 {
     return ptype == data->type;
 }
References data, and pocket_data::type.
Referenced by all_items_ptr(), item_contents::all_items_top(), can_reload_with(), item::contents_only_one_type(), full(), item_contents::get_all_contained_pockets(), item_length_modifier(), item_size_modifier(), item_weight_modifier(), pocket_favorite_callback::key(), magazine_default(), overflow(), turret_data::post_fire(), pocket_favorite_callback::refresh(), link_up_actor::remove_extensions(), restack(), spill_contents(), and item_contents::update_modified_pockets().
is_valid()
bool item_pocket::is_valid () const
Definition at line 2287 of file item_pocket.cpp.
 {
     return data != nullptr;
 }
References data.
Referenced by Creature::load().
item_has_uses_recursive()
bool item_pocket::item_has_uses_recursive () const
Definition at line 99 of file item_action.cpp.
 {
     for( const item &it : contents ) {
         if( it.item_has_uses_recursive() ) {
             return true;
         }
     }
     return false;
 }
References contents.
item_length_modifier()
units::length item_pocket::item_length_modifier () const
Definition at line 634 of file item_pocket.cpp.
 {
     if( is_type( pocket_type::EBOOK ) ) {
         return 0_mm;
     }
     units::length total_length = 0_mm;
     for( const item &it : contents ) {
         total_length = std::max( static_cast<units::length>( it.length() * std::cbrt(
                                      data->volume_multiplier ) ),
                                  total_length );
     }
     return total_length;
 }
References contents, data, EBOOK, is_type(), max(), and pocket_data::volume_multiplier.
item_size_modifier()
units::volume item_pocket::item_size_modifier () const
Definition at line 607 of file item_pocket.cpp.
 {
     if( data->rigid ) {
         return 0_ml;
     }
     units::volume total_vol = 0_ml;
     for( const item &it : contents ) {
         total_vol += it.volume( is_type( pocket_type::MOD ) );
     }
     total_vol -= data->magazine_well;
     total_vol *= data->volume_multiplier;
     return std::max( 0_ml, total_vol );
 }
References contents, data, is_type(), pocket_data::magazine_well, max(), MOD, pocket_data::rigid, and pocket_data::volume_multiplier.
item_type_restrictions()
cata::flat_set< itype_id > item_pocket::item_type_restrictions () const
Definition at line 688 of file item_pocket.cpp.
 {
     return data->item_id_restriction;
 }
References data, and pocket_data::item_id_restriction.
item_weight_modifier()
units::mass item_pocket::item_weight_modifier () const
Definition at line 621 of file item_pocket.cpp.
 {
     units::mass total_mass = 0_gram;
     for( const item &it : contents ) {
         if( is_type( pocket_type::MOD ) ) {
             total_mass += it.weight( true, true ) * data->weight_multiplier;
         } else {
             total_mass += it.weight() * data->weight_multiplier;
         }
     }
     return total_mass;
 }
References contents, data, is_type(), MOD, and pocket_data::weight_multiplier.
leak()
void item_pocket::leak (map & here, Character * carrier, const tripoint & pos, item_pocket * pocke = nullptr)
Definition at line 2000 of file item_pocket.cpp.
 {
     std::vector<item *> erases;
     for( auto iter = contents.begin(); iter != contents.end(); ) {
         if( iter->leak( here, carrier, pos, this ) ) {
             if( watertight() ) {
                 ++iter;
                 continue;
             }
             item *it = &*iter;
             if( pocke != nullptr ) {
                 if( pocke->watertight() ) {
                     ++iter;
                     continue;
                 }
                 pocke->add( *it );
             } else {
                 iter->unset_flag( flag_FROM_FROZEN_LIQUID );
                 iter->on_drop( pos );
                 here.add_item_or_charges( pos, *iter );
                 if( carrier != nullptr ) {
                     carrier->invalidate_weight_carried_cache();
                     carrier->add_msg_if_player( _( "Liquid leaked out from the %s and dripped onto the ground!" ),
                                                 this->get_name() );
                 }
             }
             iter = contents.erase( iter );
         } else {
             ++iter;
         }
     }
 }
References _, add(), map::add_item_or_charges(), Character::add_msg_if_player(), contents, flag_FROM_FROZEN_LIQUID, get_name(), Character::invalidate_weight_carried_cache(), math_opers::pos(), and watertight().
load_presets()
void item_pocket::load_presets () static
Definition at line 2429 of file item_pocket.cpp.
 {
     std::ifstream fin;
     cata_path file = PATH_INFO::pocket_presets();
     fs::path file_path = file.get_unrelative_path();
     fin.open( file_path, std::ifstream::in | std::ifstream::binary );
     if( fin.good() ) {
         try {
             JsonValue jsin = json_loader::from_path( file );
             deserialize_presets( jsin.get_array() );
         } catch( const JsonError &e ) {
             debugmsg( "Error while loading pocket presets: %s", e.what() );
         }
     }
     fin.close();
 }
References debugmsg, deserialize_presets(), file, json_loader::from_path(), JsonValue::get_array(), and PATH_INFO::pocket_presets().
magazine_current()
item * item_pocket::magazine_current ()
Definition at line 693 of file item_pocket.cpp.
 {
     auto iter = std::find_if( contents.begin(), contents.end(), []( const item & it ) {
         return !it.is_null();
     } );
     return iter != contents.end() ? &*iter : nullptr;
 }
References contents.
magazine_default()
itype_id item_pocket::magazine_default () const
Definition at line 701 of file item_pocket.cpp.
 {
     if( is_type( pocket_type::MAGAZINE_WELL ) ) {
         return data->default_magazine;
     }
     return itype_id::NULL_ID();
 }
References data, pocket_data::default_magazine, is_type(), MAGAZINE_WELL, and string_id< itype >::NULL_ID().
magazine_well()
units::volume item_pocket::magazine_well () const
Definition at line 563 of file item_pocket.cpp.
 {
     return data->magazine_well;
 }
References data, and pocket_data::magazine_well.
max_containable_length()
units::length item_pocket::max_containable_length () const
Definition at line 2292 of file item_pocket.cpp.
 {
     if( data ) {
         return data->max_item_length;
     }
     return 0_mm;
 }
References data, and pocket_data::max_item_length.
max_contains_volume()
units::volume item_pocket::max_contains_volume () const
Definition at line 573 of file item_pocket.cpp.
 {
     return data->max_contains_volume();
 }
References data, and pocket_data::max_contains_volume().
min_containable_length()
units::length item_pocket::min_containable_length () const
Definition at line 2300 of file item_pocket.cpp.
 {
     if( data ) {
         return data->min_item_length;
     }
     return 0_mm;
 }
References data, and pocket_data::min_item_length.
moves()
int item_pocket::moves () const
Definition at line 657 of file item_pocket.cpp.
 {
     if( data ) {
         return data->moves;
     } else {
         return -1;
     }
 }
References data, and pocket_data::moves.
Referenced by Creature::load(), item_location::impl::item_in_container::obtain_cost(), obtain_cost(), and Creature::store().
obtain_cost()
int item_pocket::obtain_cost (const item & it) const
Definition at line 2248 of file item_pocket.cpp.
 {
     if( has_item( it ) ) {
         return moves();
     }
     return 0;
 }
References has_item(), and moves().
Referenced by better_pocket(), and Character::store().
on_contents_changed()
void item_pocket::on_contents_changed ()
Definition at line 1924 of file item_pocket.cpp.
 {
     unseal();
     restack();
 }
References restack(), and unseal().
Referenced by item::reload(), remove_all_mods(), remove_items_if(), and avatar_action::use_item().
on_pickup()
void item_pocket::on_pickup (Character & guy, item * avoid = nullptr)
Definition at line 1914 of file item_pocket.cpp.
 {
     if( will_spill() ) {
         while( !empty() ) {
             handle_liquid_or_spill( guy, avoid );
         }
         restack();
     }
 }
References empty(), handle_liquid_or_spill(), restack(), and will_spill().
operator==()
bool item_pocket::operator== (const item_pocket & rhs) const
Definition at line 199 of file item_pocket.cpp.
 {
     return *data == *rhs.data;
 }
References data.
overflow()
void item_pocket::overflow (const tripoint & pos, const item_location & loc)
Definition at line 1806 of file item_pocket.cpp.
 {
     if( is_type( pocket_type::MOD ) || is_type( pocket_type::CORPSE ) ||
         is_type( pocket_type::EBOOK ) || is_type( pocket_type::CABLE ) ) {
         return;
     }
     if( empty() ) {
         // no items to overflow
         return;
     }
     // overflow recursively
     for( item &it : contents ) {
         if( loc ) {
             item_location content_loc( loc, &it );
             content_loc.overflow();
         } else {
             it.overflow( pos );
         }
     }
     Character *carrier = loc.carrier();
     // first remove items that shouldn't be in there anyway
     std::unordered_map<itype_id, bool> contained_type_validity;
     for( auto iter = contents.begin(); iter != contents.end(); ) {
         // if item has any contents, check it individually
         if( !iter->get_contents().empty_with_no_mods() ) {
             if( !is_type( pocket_type::MIGRATION ) && can_contain( *iter, true ).success() ) {
                 ++iter;
             } else {
                 move_to_parent_pocket_recursive( pos, *iter, loc, carrier );
                 iter = contents.erase( iter );
             }
             continue;
         }
         // otherwise, use cached results per item type
         auto cont_copy_type = contained_type_validity.emplace( iter->typeId(), true );
         if( cont_copy_type.second ) {
             cont_copy_type.first->second = !is_type( pocket_type::MIGRATION ) &&
                                            can_contain( *iter, true ).success();
         }
         if( cont_copy_type.first->second ) {
             ++iter;
         } else {
             move_to_parent_pocket_recursive( pos, *iter, loc, carrier );
             iter = contents.erase( iter );
         }
     }
     if( empty() ) {
         // we've removed the migration pockets and items that didn't fit
         return;
     }
     if( !data->ammo_restriction.empty() ) {
         const ammotype contained_ammotype = contents.front().ammo_type();
         const auto ammo_iter = data->ammo_restriction.find( contained_ammotype );
         if( ammo_iter == data->ammo_restriction.end() ) {
             // only one ammotype is allowed in an ammo restricted pocket
             // so if the first one is wrong, they're all wrong
             spill_contents( pos );
             return;
         }
         int total_qty = 0;
         for( auto iter = contents.begin(); iter != contents.end(); ) {
             item &ammo = *iter;
             total_qty += ammo.count();
             const int overflow_count = total_qty - ammo_iter->second;
             if( overflow_count > 0 ) {
                 ammo.charges -= overflow_count;
                 item dropped_ammo( ammo.typeId(), ammo.birthday(), overflow_count );
                 move_to_parent_pocket_recursive( pos, *iter, loc, carrier );
                 total_qty -= overflow_count;
             }
             if( ammo.count() == 0 ) {
                 iter = contents.erase( iter );
             } else {
                 ++iter;
             }
         }
         // return early, the rest of this function checks against volume and weight
         // and ammo_restriction is an override
         return;
     }
     if( remaining_volume() < 0_ml ) {
         contents.sort( []( const item & left, const item & right ) {
             return left.volume() > right.volume();
         } );
         while( remaining_volume() < 0_ml && !contents.empty() ) {
             move_to_parent_pocket_recursive( pos, contents.front(), loc, carrier );
             contents.pop_front();
         }
     }
     if( remaining_weight() < 0_gram ) {
         contents.sort( []( const item & left, const item & right ) {
             return left.weight() > right.weight();
         } );
         while( remaining_weight() < 0_gram && !contents.empty() ) {
             move_to_parent_pocket_recursive( pos, contents.front(), loc, carrier );
             contents.pop_front();
         }
     }
 }
References pocket_data::ammo_restriction, item::birthday(), CABLE, can_contain(), item_location::carrier(), item::charges, contents, CORPSE, item::count(), data, EBOOK, empty(), is_type(), left, MIGRATION, MOD, move_to_parent_pocket_recursive(), item_location::overflow(), math_opers::pos(), remaining_volume(), remaining_weight(), right, spill_contents(), and item::typeId().
pop_back()
void item_pocket::pop_back ()
Definition at line 548 of file item_pocket.cpp.
 {
     contents.pop_back();
 }
References contents.
process() [1/2]
bool item_pocket::process (const itype & type, map & here, Character * carrier, const tripoint & pos, float insulation, temperature_flag flag)
Definition at line 901 of file item_pocket.cpp.
 {
     bool processed = false;
     float spoil_multiplier = 1.0f;
     for( auto it = contents.begin(); it != contents.end(); ) {
         if( _sealed ) {
             spoil_multiplier = 0.0f;
         }
         if( it->process( here, carrier, pos, type.insulation_factor * insulation, flag,
                          spoil_multiplier ) ) {
             it->spill_contents( pos );
             it = contents.erase( it );
             processed = true;
         } else {
             ++it;
         }
     }
     return processed;
 }
References _sealed, contents, math_opers::pos(), spoil_multiplier(), and type.
process() [2/2]
void item_pocket::process (map & here, Character * carrier, const tripoint & pos, float insulation = 1, temperature_flag flag = temperature_flag::NORMAL, float spoil_multiplier_parent = 1.0f)
Is part of the recursive call of item::process.
see that function for additional comments NOTE: this destroys the items that get processed
Definition at line 1985 of file item_pocket.cpp.
 {
     for( auto iter = contents.begin(); iter != contents.end(); ) {
         if( iter->process( here, carrier, pos, insulation, flag,
                            // spoil multipliers on pockets are not additive or multiplicative, they choose the best
                            std::min( spoil_multiplier_parent, spoil_multiplier() ) ) ) {
             iter->spill_contents( pos );
             iter = contents.erase( iter );
         } else {
             ++iter;
         }
     }
 }
References contents, min(), math_opers::pos(), and spoil_multiplier().
remaining_ammo_capacity()
int item_pocket::remaining_ammo_capacity (const ammotype & ammo) const
Definition at line 742 of file item_pocket.cpp.
 {
     int total_capacity = ammo_capacity( ammo );
     if( total_capacity == 0 ) {
         return 0;
     }
     int ammo_count = 0;
     for( const item &it : contents ) {
         if( it.has_flag( flag_CASING ) ) {
             continue;
         } else if( ammo != it.ammo_type() ) {
             return 0;
         }
         ammo_count += it.count();
     }
     return total_capacity - ammo_count;
 }
References ammo_capacity(), contents, and flag_CASING.
Referenced by _can_contain(), can_reload_with(), fill_with(), item::fill_with(), and full().
remaining_capacity_for_item()
int item_pocket::remaining_capacity_for_item (const item & it) const
Definition at line 583 of file item_pocket.cpp.
 {
     if( it.count_by_charges() ) {
         item it_copy = it;
         it_copy.charges = 1;
         if( can_contain( it_copy ).success() ) {
             return std::min( {
                 it.charges,
                 charges_per_remaining_volume( it ),
                 charges_per_remaining_weight( it )
             } );
         } else {
             return 0;
         }
     } else if( can_contain( it ).success() ) {
         return std::min( {
             charges_per_remaining_volume( it ),
             charges_per_remaining_weight( it )
         } );
     } else {
         return 0;
     }
 }
References can_contain(), item::charges, charges_per_remaining_volume(), charges_per_remaining_weight(), item::count_by_charges(), and min().
Referenced by outfit::add_stash().
remaining_volume()
units::volume item_pocket::remaining_volume () const
Definition at line 578 of file item_pocket.cpp.
 {
     return volume_capacity() - contains_volume();
 }
References contains_volume(), and volume_capacity().
Referenced by better_pocket(), charges_per_remaining_volume(), contents_info(), full(), is_funnel_container(), overflow(), item_location::parents_can_contain_recursive(), and item_location::impl::item_in_container::volume_capacity().
remaining_weight()
units::mass item_pocket::remaining_weight () const
Definition at line 2326 of file item_pocket.cpp.
 {
     return weight_capacity() - contains_weight();
 }
References contains_weight(), and weight_capacity().
Referenced by charges_per_remaining_weight(), contents_info(), overflow(), item_location::parents_can_contain_recursive(), and item_location::impl::item_in_container::weight_capacity().
remove_all_ammo()
void item_pocket::remove_all_ammo (Character & guy)
Definition at line 922 of file item_pocket.cpp.
 {
     for( auto iter = contents.begin(); iter != contents.end(); ) {
         if( iter->is_irremovable() ) {
             iter++;
             continue;
         }
         drop_or_handle( *iter, guy );
         iter = contents.erase( iter );
     }
 }
References contents, and drop_or_handle().
remove_all_mods()
void item_pocket::remove_all_mods (Character & guy)
Definition at line 934 of file item_pocket.cpp.
 {
     for( auto iter = contents.begin(); iter != contents.end(); ) {
         if( iter->is_toolmod() ) {
             guy.i_add_or_drop( *iter );
             iter = contents.erase( iter );
         } else {
             ++iter;
         }
     }
     on_contents_changed();
 }
References contents, Character::i_add_or_drop(), and on_contents_changed().
remove_internal()
bool item_pocket::remove_internal (const std::function< bool(item &)> & filter, int & count, std::list< item > & res)
Definition at line 1751 of file item_pocket.cpp.
 {
     for( auto it = contents.begin(); it != contents.end(); ) {
         if( filter( *it ) ) {
             res.splice( res.end(), contents, it++ );
             if( --count == 0 ) {
                 return true;
             }
         } else {
             it->remove_internal( filter, count, res );
             ++it;
         }
     }
     return false;
 }
References contents, and filter.
remove_item() [1/2]
std::optional< item > item_pocket::remove_item (const item & it)
Definition at line 1737 of file item_pocket.cpp.
 {
     item ret( it );
     const size_t sz = contents.size();
     contents.remove_if( [&it]( const item & rhs ) {
         return &rhs == &it;
     } );
     if( sz == contents.size() ) {
         return std::nullopt;
     } else {
         return ret;
     }
 }
References contents, and cata::hash64_detail::ret.
Referenced by remove_item().
remove_item() [2/2]
std::optional< item > item_pocket::remove_item (const item_location & it)
Definition at line 1768 of file item_pocket.cpp.
 {
     if( !it ) {
         return std::nullopt;
     }
     return remove_item( *it );
 }
References remove_item().
remove_items_if()
void item_pocket::remove_items_if (const std::function< bool(item &)> & filter)
Definition at line 1979 of file item_pocket.cpp.
 {
     contents.remove_if( filter );
     on_contents_changed();
 }
References contents, filter, and on_contents_changed().
Referenced by exosuit_interact::insert_replace_activate_mod().
restack() [1/2]
void item_pocket::restack ()
stacks like items inside the pocket
Definition at line 247 of file item_pocket.cpp.
 {
     if( contents.size() <= 1 ) {
         return;
     }
     if( is_type( pocket_type::MAGAZINE ) ) {
         // Restack magazine contents in a way that preserves order of items
         for( auto iter = contents.begin(); iter != contents.end(); ) {
             if( !iter->count_by_charges() ) {
                 continue;
             }
             auto next = std::next( iter, 1 );
             if( next == contents.end() ) {
                 break;
             }
             if( iter->combine( *next ) ) {
                 iter = contents.erase( next );
             } else {
                 ++iter;
             }
         }
         return;
     }
     for( auto outer_iter = contents.begin(); outer_iter != contents.end(); ++outer_iter ) {
         if( !outer_iter->count_by_charges() ) {
             continue;
         }
         for( auto inner_iter = contents.begin(); inner_iter != contents.end(); ) {
             if( outer_iter == inner_iter || !inner_iter->count_by_charges() ) {
                 ++inner_iter;
                 continue;
             }
             if( outer_iter->combine( *inner_iter ) ) {
                 inner_iter = contents.erase( inner_iter );
                 outer_iter = contents.begin();
             } else {
                 ++inner_iter;
             }
         }
     }
 }
References contents, is_type(), and MAGAZINE.
Referenced by add(), insert_item(), game::inventory_item_menu(), on_contents_changed(), on_pickup(), and use_amount().
restack() [2/2]
item * item_pocket::restack (item * it)
same as restack(), except returns the stack where input item was placed
Definition at line 291 of file item_pocket.cpp.
 {
     item *ret = it;
     if( contents.size() <= 1 ) {
         return ret;
     }
     if( is_type( pocket_type::MAGAZINE ) ) {
         // Restack magazine contents in a way that preserves order of items
         for( auto iter = contents.begin(); iter != contents.end(); ) {
             if( !iter->count_by_charges() ) {
                 continue;
             }
             auto next = std::next( iter, 1 );
             if( next == contents.end() ) {
                 break;
             }
             if( iter->combine( *next ) ) {
                 // next was placed in iter, check if next was the item that we track
                 if( &( *next ) == ret ) {
                     ret = &( *iter );
                 }
                 iter = contents.erase( next );
             } else {
                 ++iter;
             }
         }
         return ret;
     }
     for( auto outer_iter = contents.begin(); outer_iter != contents.end(); ++outer_iter ) {
         if( !outer_iter->count_by_charges() ) {
             continue;
         }
         for( auto inner_iter = contents.begin(); inner_iter != contents.end(); ) {
             if( outer_iter == inner_iter || !inner_iter->count_by_charges() ) {
                 ++inner_iter;
                 continue;
             }
             if( outer_iter->combine( *inner_iter ) ) {
                 // inner was placed in outer, check if inner was the item that we track
                 if( &( *inner_iter ) == ret ) {
                     ret = &( *outer_iter );
                 }
                 inner_iter = contents.erase( inner_iter );
                 outer_iter = contents.begin();
             } else {
                 ++inner_iter;
             }
         }
     }
     return ret;
 }
References contents, is_type(), MAGAZINE, and cata::hash64_detail::ret.
rigid()
bool item_pocket::rigid () const
Definition at line 2066 of file item_pocket.cpp.
 {
     return data->rigid;
 }
References data, and pocket_data::rigid.
Referenced by item_location::max_charges_by_parent_recursive(), and item_location::parents_can_contain_recursive().
same_contents()
bool item_pocket::same_contents (const item_pocket & rhs) const
Definition at line 233 of file item_pocket.cpp.
 {
     if( contents.size() != rhs.contents.size() ) {
         return false;
     }
     return std::equal( contents.begin(), contents.end(),
                        rhs.contents.begin(), rhs.contents.end(),
     []( const item & a, const item & b ) {
         return a.typeId() == b.typeId() &&
                a.charges == b.charges &&
                a.same_contents( b );
     } );
 }
References a, b, and contents.
save_presets()
void item_pocket::save_presets () static
Definition at line 2391 of file item_pocket.cpp.
 {
     cata_path file = PATH_INFO::pocket_presets();
     write_to_file( file, [&]( std::ostream & fout ) {
         JsonOut jout( fout, true );
         serialize_presets( jout );
     }, _( "pocket preset configuration" ) );
 }
References _, file, PATH_INFO::pocket_presets(), serialize_presets(), and write_to_file().
Referenced by add_preset(), and delete_preset().
saved_sealed()
bool item_pocket::saved_sealed () const inline
Definition at line 315 of file item_pocket.h.
{
             return _saved_sealed;
         }
References _saved_sealed.
saved_type()
pocket_type item_pocket::saved_type () const inline
Definition at line 311 of file item_pocket.h.
{
             return _saved_type;
         }
References _saved_type.
Referenced by item_contents::read_mods().
seal()
bool item_pocket::seal ()
Definition at line 849 of file item_pocket.cpp.
 {
     if( !sealable() || empty() ) {
         return false;
     }
     _sealed = true;
     return true;
 }
References _sealed, empty(), and sealable().
sealable()
bool item_pocket::sealable () const
A pocket is sealable IFF it has "sealed_data".
Sealable pockets are sealed by calling seal(). If a pocket is not sealable, it is never considered "sealed".
Definition at line 871 of file item_pocket.cpp.
 {
     // if it has sealed data it is understood that the
     // data is different when sealed than when not
     // In other words, a pocket is sealable IFF it has sealed_data.
     return !!data->sealed_data;
 }
References data, and pocket_data::sealed_data.
Referenced by contents_info(), is_default_state(), is_funnel_container(), seal(), and sealed().
sealed()
bool item_pocket::sealed () const
A pocket is sealed when item spawns if pocket has "sealed_data".
A pocket can never be sealed unless it is sealable (having "sealed_data"). If a pocket is sealed, you cannot interact with it until the seal is broken with unseal().
Definition at line 863 of file item_pocket.cpp.
 {
     if( !sealable() ) {
         return false;
     } else {
         return _sealed;
     }
 }
References _sealed, and sealable().
Referenced by contents_info(), fill_with(), spoil_multiplier(), translated_sealed_prefix(), transparent(), and will_spill().
serialize()
void item_pocket::serialize (JsonOut & json) const
Definition at line 245 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "pocket_type", data->type );
     json.member( "contents", contents );
     json.member( "_sealed", _sealed );
     json.member( "no_rigid", no_rigid );
     if( !this->settings.is_null() ) {
         json.member( "favorite_settings", this->settings );
     }
     json.end_object();
 }
References _sealed, contents, data, JsonOut::end_object(), item_pocket::favorite_settings::is_null(), JsonOut::member(), no_rigid, settings, JsonOut::start_object(), and pocket_data::type.
serialize_presets()
void item_pocket::serialize_presets (JsonOut & json) static
Definition at line 2449 of file item_pocket.cpp.
 {
     json.start_array();
     for( const item_pocket::favorite_settings &preset : pocket_presets ) {
         preset.serialize( json );
     }
     json.end_array();
 }
References JsonOut::end_array(), pocket_presets, and JsonOut::start_array().
Referenced by save_presets().
set_item_defaults()
void item_pocket::set_item_defaults ()
Definition at line 947 of file item_pocket.cpp.
 {
     for( item &contained_item : contents ) {
         /* for guns and other items defined to have a magazine but don't use "ammo" */
         if( contained_item.is_magazine() ) {
             contained_item.ammo_set(
                 contained_item.ammo_default(),
                 contained_item.ammo_capacity( item_controller->find_template(
                                                   contained_item.ammo_default() )->ammo->type ) / 2
             );
         } else { //Contents are batteries or food
             contained_item.charges =
                 item::find_type( contained_item.typeId() )->charges_default();
         }
     }
 }
References itype::charges_default(), contents, item::find_type(), and item_controller.
set_no_rigid()
void item_pocket::set_no_rigid (const std::set< sub_bodypart_id > & is_no_rigid)
Definition at line 2424 of file item_pocket.cpp.
 {
     no_rigid = is_no_rigid;
 }
References no_rigid.
size()
size_t item_pocket::size () const
Definition at line 553 of file item_pocket.cpp.
 {
     return contents.size();
 }
References contents.
Referenced by _can_contain(), faction::deserialize(), and faction::serialize().
spill_contents()
bool item_pocket::spill_contents (const tripoint & pos)
Definition at line 1930 of file item_pocket.cpp.
 {
     if( is_type( pocket_type::EBOOK ) || is_type( pocket_type::CORPSE ) ||
         is_type( pocket_type::CABLE ) ) {
         return false;
     }
     map &here = get_map();
     for( item &it : contents ) {
         here.add_item_or_charges( pos, it );
     }
     contents.clear();
     return true;
 }
References map::add_item_or_charges(), CABLE, contents, CORPSE, EBOOK, get_map(), is_type(), and math_opers::pos().
Referenced by handle_liquid_or_spill(), and overflow().
spoil_multiplier()
float item_pocket::spoil_multiplier () const
gets the spoilage multiplier depending on sealed data
Definition at line 648 of file item_pocket.cpp.
 {
     if( sealed() ) {
         return data->sealed_data->spoil_multiplier;
     } else {
         return data->spoil_multiplier;
     }
 }
References data, sealed(), pocket_data::sealed_data, and pocket_data::spoil_multiplier.
Referenced by better_pocket(), general_info(), get_comestible_order(), comestible_inventory_preset::get_order(), and process().
stacks_with()
bool item_pocket::stacks_with (const item_pocket & rhs, int depth = 0, int maxdepth = 2) const
Definition at line 437 of file item_pocket.cpp.
 {
     if( _sealed != rhs._sealed ) {
         return false;
     }
     return ( empty() && rhs.empty() ) || std::equal( contents.begin(), contents.end(),
             rhs.contents.begin(), rhs.contents.end(),
     [depth, maxdepth]( const item & a, const item & b ) {
         return depth < maxdepth && a.charges == b.charges &&
                a.stacks_with( b, false, false, false, depth + 1, maxdepth );
     } );
 }
References _sealed, a, b, contents, and empty().
translated_sealed_prefix()
std::string item_pocket::translated_sealed_prefix () const
Definition at line 879 of file item_pocket.cpp.
 {
     if( sealed() ) {
         return _( "sealed" );
     } else {
         return _( "open" );
     }
 }
References _, and sealed().
Referenced by contents_info().
transparent()
bool item_pocket::transparent () const
Definition at line 2076 of file item_pocket.cpp.
 {
     return data->transparent || ( data->open_container && !sealed() );
 }
References data, pocket_data::open_container, sealed(), and pocket_data::transparent.
Referenced by item_contents::all_known_contents().
unseal()
void item_pocket::unseal ()
Definition at line 858 of file item_pocket.cpp.
 {
     _sealed = false;
 }
References _sealed.
Referenced by fill_with(), item::fill_with(), Character::handle_contents_changed(), on_contents_changed(), and contents_change_handler::unseal_pocket_containing().
use_amount()
bool item_pocket::use_amount (const itype_id & it, int & quantity, std::list< item > & used)
Definition at line 810 of file item_pocket.cpp.
 {
     bool used_item = false;
     for( auto a = contents.begin(); a != contents.end() && quantity > 0; ) {
         if( a->use_amount( it, quantity, used ) ) {
             used_item = true;
             a = contents.erase( a );
         } else {
             ++a;
         }
     }
     restack();
     return used_item;
 }
References a, contents, and restack().
visit_contents()
VisitResponse item_pocket::visit_contents (const std::function< VisitResponse(item *, item *)> & func, item * parent = nullptr)
Definition at line 390 of file visitable.cpp.
 {
     for( item &e : contents ) {
         switch( visit_internal( func, &e, parent ) ) {
             case VisitResponse::ABORT:
                 return VisitResponse::ABORT;
             default:
                 break;
         }
     }
     return VisitResponse::NEXT;
 }
References ABORT, contents, NEXT, and visit_internal().
volume_capacity()
units::volume item_pocket::volume_capacity () const
Definition at line 558 of file item_pocket.cpp.
 {
     return data->volume_capacity;
 }
References data, and pocket_data::volume_capacity.
Referenced by _can_contain(), charges_per_remaining_volume(), contents_info(), general_info(), and remaining_volume().
watertight()
bool item_pocket::watertight () const
Definition at line 2071 of file item_pocket.cpp.
 {
     return data->watertight;
 }
References data, and pocket_data::watertight.
Referenced by can_reload_with(), item::leak(), and leak().
weight_capacity()
units::mass item_pocket::weight_capacity () const
Definition at line 568 of file item_pocket.cpp.
 {
     return data->max_contains_weight;
 }
References data, and pocket_data::max_contains_weight.
Referenced by _can_contain(), charges_per_remaining_weight(), contents_info(), general_info(), and remaining_weight().
will_explode_in_a_fire()
bool item_pocket::will_explode_in_a_fire () const
Definition at line 825 of file item_pocket.cpp.
 {
     if( data->fire_protection ) {
         return false;
     }
     return std::any_of( contents.begin(), contents.end(), []( const item & it ) {
         return it.will_explode_in_fire();
     } );
 }
References contents, data, and pocket_data::fire_protection.
will_spill()
bool item_pocket::will_spill () const
Definition at line 835 of file item_pocket.cpp.
 {
     if( sealed() ) {
         return false;
     } else {
         return data->open_container;
     }
 }
References data, pocket_data::open_container, and sealed().
Referenced by can_contain_liquid(), can_unload_liquid(), full(), general_info(), on_pickup(), and avatar_action::use_item().
will_spill_if_unsealed()
bool item_pocket::will_spill_if_unsealed () const
Definition at line 844 of file item_pocket.cpp.
 {
     return data->open_container;
 }
References data, and pocket_data::open_container.
Member Data Documentation
_saved_sealed
bool item_pocket::_saved_sealed = false private
Definition at line 408 of file item_pocket.h.
Referenced by deserialize(), and saved_sealed().
_saved_type
pocket_type item_pocket::_saved_type = pocket_type::LAST private
Definition at line 407 of file item_pocket.h.
Referenced by deserialize(), and saved_type().
_sealed
bool item_pocket::_sealed = false private
Definition at line 412 of file item_pocket.h.
Referenced by deserialize(), is_funnel_container(), process(), seal(), sealed(), serialize(), stacks_with(), and unseal().
contents
std::list<item> item_pocket::contents private
Definition at line 411 of file item_pocket.h.
Referenced by _can_contain(), add(), all_items_top(), ammo_consume(), back(), best_pocket_in_contents(), best_quality(), can_unload_liquid(), casings_handle(), charges_per_remaining_volume(), charges_per_remaining_weight(), clear_items(), contains_phase(), contains_volume(), contains_weight(), contents_info(), item::deserialize(), deserialize(), detonate(), edit_contents(), empty(), front(), full(), get_item_with(), gunmods(), handle_liquid_or_spill(), has_any_with(), has_item(), has_item_stacks_with(), heat_up(), insert_item(), item_has_uses_recursive(), item_length_modifier(), item_size_modifier(), item_weight_modifier(), leak(), magazine_current(), item::migrate_content_item(), overflow(), pop_back(), process(), remaining_ammo_capacity(), remove_all_ammo(), remove_all_mods(), remove_internal(), remove_item(), remove_items_if(), restack(), same_contents(), item::serialize(), serialize(), set_item_defaults(), size(), spill_contents(), stacks_with(), use_amount(), visit_contents(), and will_explode_in_a_fire().
data
const pocket_data* item_pocket::data = nullptr private
Definition at line 409 of file item_pocket.h.
Referenced by _can_contain(), airtight(), allows_speedloader(), ammo_capacity(), ammo_types(), better_pocket(), can_contain_liquid(), contents_info(), basecamp::deserialize(), Character::trait_data::deserialize(), dialogue_chatbin::deserialize(), effect_source::deserialize(), item::deserialize(), item::link_data::deserialize(), item_pocket::favorite_settings::deserialize(), deserialize(), sealable_data::deserialize(), pocket_noise::deserialize(), pocket_data::deserialize(), kill_tracker::deserialize(), npc_personality::deserialize(), npc_opinion::deserialize(), npc_follower_rules::deserialize(), player_activity::deserialize(), requirement_data::deserialize(), SkillLevel::deserialize(), smart_controller_config::deserialize(), vehicle_part::carried_part_data::deserialize(), vehicle_part::deserialize(), label::deserialize(), vehicle::deserialize(), avatar::deserialize(), npc::deserialize(), monster::deserialize(), stats_tracker::deserialize(), vehicle::deserialize_parts(), full(), general_info(), get_pocket_data(), inherits_flags(), is_compatible(), is_forbidden(), is_funnel_container(), is_restricted(), is_standard_type(), is_type(), is_valid(), item_length_modifier(), item_size_modifier(), item_type_restrictions(), item_weight_modifier(), avatar::load(), Character::load(), npc::load(), monster::load(), magazine_default(), magazine_well(), max_containable_length(), max_contains_volume(), min_containable_length(), moves(), operator==(), overflow(), rigid(), sealable(), stats_tracker::serialize(), serialize(), spoil_multiplier(), transparent(), volume_capacity(), watertight(), weight_capacity(), will_explode_in_a_fire(), will_spill(), and will_spill_if_unsealed().
name_as_description
bool item_pocket::name_as_description = false
Definition at line 404 of file item_pocket.h.
Referenced by general_info().
no_rigid
std::set<sub_bodypart_id> item_pocket::no_rigid private
Definition at line 414 of file item_pocket.h.
Referenced by _can_contain(), deserialize(), general_info(), serialize(), and set_no_rigid().
pocket_presets
std::vector< item_pocket::favorite_settings > item_pocket::pocket_presets static
Definition at line 398 of file item_pocket.h.
Referenced by add_preset(), delete_preset(), deserialize_presets(), find_preset(), has_preset(), and serialize_presets().
settings
favorite_settings item_pocket::settings
Definition at line 387 of file item_pocket.h.
Referenced by item_contents::all_items_top(), best_pocket_in_contents(), better_pocket(), deserialize(), favorite_info(), fill_with(), item::is_collapsed(), is_default_state(), pocket_favorite_callback::key(), and serialize().
The documentation for this class was generated from the following files:
src/item_pocket.h
src/item_action.cpp
src/item_pocket.cpp
src/savegame_json.cpp
src/visitable.cpp