Cataclysm DDA: event_multiset_watcher Class Reference
event_multiset_watcher Class Reference abstract
#include <stats_tracker.h>
Public Member Functions
virtual void event_added (const cata::event &, stats_tracker &)=0
virtual void events_reset (const event_multiset &, stats_tracker &)=0
Public Member Functions inherited from base_watcher
base_watcher ()=default
base_watcher (const base_watcher &)=delete
base_watcher & operator= (const base_watcher &)=delete
Additional Inherited Members
Protected Member Functions inherited from base_watcher
virtual ~base_watcher ()
Detailed Description
Definition at line 128 of file stats_tracker.h.
Member Function Documentation
event_added()
virtual void event_multiset_watcher::event_added (const cata::event & , stats_tracker &) pure virtual
Implemented in event_statistic_last_value::state, event_statistic_first_value::state, event_statistic_unique_value::state, event_statistic_minimum::state, event_statistic_maximum::state, event_statistic_total::state, event_transformation_impl::state, and event_statistic_count::state.
Referenced by stats_tracker::notify(), and stats_tracker::transformed_set_changed().
events_reset()
virtual void event_multiset_watcher::events_reset (const event_multiset & , stats_tracker &) pure virtual
Implemented in event_transformation_impl::state, event_statistic_minimum::state, event_statistic_maximum::state, event_statistic_total::state, event_statistic_count::state, event_statistic_last_value::state, event_statistic_first_value::state, and event_statistic_unique_value::state.
Referenced by stats_tracker::transformed_set_changed().
The documentation for this class was generated from the following file:
src/stats_tracker.h