Cataclysm DDA: math_exp Class Reference
math_exp Class Reference
#include <math_parser.h>
Classes
class math_exp_impl
Public Member Functions
~math_exp ()
math_exp ()
math_exp (math_exp const &other)
math_exp (math_exp &&) noexcept
math_exp & operator= (math_exp const &other)
math_exp & operator= (math_exp &&) noexcept
math_exp (math_exp_impl impl_)
bool parse (std::string_view str, bool assignment=false)
double eval (dialogue &d) const
void assign (dialogue &d, double val) const
Private Attributes
std::unique_ptr< math_exp_impl > impl
Detailed Description
Definition at line 10 of file math_parser.h.
Constructor & Destructor Documentation
~math_exp()
math_exp::~math_exp () default
math_exp() [1/4]
math_exp::math_exp () default
math_exp() [2/4]
math_exp::math_exp (math_exp const & other)
Definition at line 844 of file math_parser.cpp.
                                           :
     impl( other.impl ? std::make_unique<math_exp_impl>( *other.impl ) :
           std::make_unique<math_exp_impl>() ) {}
References other.
math_exp() [3/4]
math_exp::math_exp (math_exp &&) default noexcept
math_exp() [4/4]
math_exp::math_exp (math_exp_impl impl_) explicit
Definition at line 833 of file math_parser.cpp.
     : impl( std::make_unique<math_exp_impl>( std::move( impl_ ) ) )
 {
 }
Member Function Documentation
assign()
void math_exp::assign (dialogue & d, double val) const
Definition at line 863 of file math_parser.cpp.
 {
     return impl->assign( d, val );
 }
References impl.
eval()
double math_exp::eval (dialogue & d) const
Definition at line 858 of file math_parser.cpp.
 {
     return impl->eval( d );
 }
References eval().
Referenced by eval(), and jmath_func::eval().
operator=() [1/2]
math_exp & math_exp::operator= (math_exp &&) default noexcept
operator=() [2/2]
math_exp & math_exp::operator= (math_exp const & other)
Definition at line 847 of file math_parser.cpp.
 {
     impl = other.impl ? std::make_unique<math_exp_impl>( *other.impl ) :
            std::make_unique<math_exp_impl>();
     return *this;
 }
References impl, and other.
parse()
bool math_exp::parse (std::string_view str, bool assignment = false)
Definition at line 838 of file math_parser.cpp.
 {
     impl = std::make_unique<math_exp_impl>();
     return impl->parse( str, assignment );
 }
References impl.
Member Data Documentation
impl
std::unique_ptr<math_exp_impl> math_exp::impl private
Definition at line 28 of file math_parser.h.
Referenced by assign(), operator=(), and parse().
The documentation for this class was generated from the following files:
src/math_parser.h
src/math_parser.cpp