Cataclysm DDA: inventory_entry Class Reference
inventory_entry Class Reference
#include <inventory_ui.h>
Classes
struct entry_cell_cache_t
Public Member Functions
inventory_entry ()=default
inventory_entry (const item_category *custom_category)
inventory_entry (const inventory_entry &entry, const item_category *custom_category)
inventory_entry (const std::vector< item_location > &locations, const item_category *custom_category=nullptr, bool enabled=true, const size_t chosen_count=0, size_t generation_number=0, item_location topmost_parent={}, bool chevron=false)
bool operator== (const inventory_entry &other) const
bool operator!= (const inventory_entry &other) const
operator bool () const
bool is_null () const
Whether the entry is null (dummy)
bool is_item () const
Whether the entry is an item.
bool is_category () const
Whether the entry is a category.
bool is_hidden (std::optional< bool > const &hide_entries_override) const
Whether it is hidden in inventory screen.
bool is_selectable () const
Whether the entry can be selected.
bool is_highlightable (bool skip_unselectable) const
bool is_collated () const
bool is_collation_header () const
bool is_collation_entry () const
const item_location & any_item () const
size_t get_stack_size () const
int get_total_charges () const
int get_selected_charges () const
size_t get_available_count () const
const item_category * get_category_ptr () const
int get_invlet () const
nc_color get_invlet_color () const
void update_cache ()
void cache_denial (inventory_selector_preset const &preset) const
void set_custom_category (const item_category *category)
void reset_collation ()
const entry_cell_cache_t & get_entry_cell_cache (inventory_selector_preset const &preset) const
void make_entry_cell_cache (inventory_selector_preset const &preset, bool update_only=true) const
void reset_entry_cell_cache () const
Public Attributes
std::vector< item_location > locations
size_t chosen_count = 0
int custom_invlet = INT_MIN
std::string * cached_name = nullptr
std::string * cached_name_full = nullptr
unsigned int contents_count = 0
size_t cached_denial_space = 0
bool highlight_as_parent = false
bool highlight_as_child = false
bool collapsed = false
item_location topmost_parent
std::shared_ptr< collation_meta_t > collation_meta
size_t generation = 0
bool chevron = false
int indent = 0
bool enabled = true
std::optional< std::string > denial
Protected Attributes
bool _indent = true
std::optional< entry_cell_cache_t > entry_cell_cache
Private Attributes
item_category const * custom_category = nullptr
Detailed Description
Definition at line 65 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_entry() [1/4]
inventory_entry::inventory_entry () default
inventory_entry() [2/4]
inventory_entry::inventory_entry (const item_category * custom_category) inline explicit
Definition at line 79 of file inventory_ui.h.
                                                                          :
             custom_category( custom_category )
         {}
inventory_entry() [3/4]
inventory_entry::inventory_entry (const inventory_entry & entry, const item_category * custom_category) inline
Definition at line 85 of file inventory_ui.h.
                                                                                               :
             inventory_entry( entry ) {
             this->custom_category = custom_category;
         }
References custom_category.
inventory_entry() [4/4]
inventory_entry::inventory_entry (const std::vector< item_location > & locations, const item_category * custom_category = nullptr, bool enabled = true, const size_t chosen_count = 0, size_t generation_number = 0, item_location topmost_parent = {}, bool chevron = false) inline explicit
Definition at line 90 of file inventory_ui.h.
                                                                  {}, bool chevron = false ) :
             locations( locations ),
             chosen_count( chosen_count ),
             topmost_parent( std::move( topmost_parent ) ),
             generation( generation_number ),
             chevron( chevron ),
             enabled( enabled ),
             custom_category( custom_category ) {
         }
Member Function Documentation
any_item()
const item_location& inventory_entry::any_item () const inline
Definition at line 153 of file inventory_ui.h.
{
             if( locations.empty() ) {
                 debugmsg( "inventory_entry::any_item called on a non-item entry.  "
                           "Test inventory_entry::is_item before calling this function." );
                 return item_location::nowhere;
             } else {
                 return locations.front();
             }
         }
References debugmsg, locations, and item_location::nowhere.
Referenced by inventory_selector_preset::append_cell(), trade_ui::autobalance(), inventory_column::collated_sort_compare(), inventory_column::draw(), inventory_pick_selector::execute(), ammo_inventory_selector::execute(), inventory_compare_selector::execute(), unload_selector::execute(), inventory_examiner::execute(), get_available_count(), inventory_selector_preset::get_caption(), selection_column_preset::get_caption(), get_category_ptr(), inventory_selector_preset::get_color(), read_inventory_preset::get_color(), selection_column_preset::get_color(), inventory_selector_preset::get_denial(), get_invlet(), inventory_selector::highlight(), ammo_inventory_selector::mod_chosen_count(), inventory_column::on_input(), inventory_selector::on_input(), inventory_multiselector::on_input(), anonymous_namespace{inventory_ui.cpp}::path_to_top(), inventory_selector::rearrange_columns(), inventory_multiselector::set_chosen_count(), comestible_inventory_preset::sort_compare(), gunmod_inventory_preset::sort_compare(), read_inventory_preset::sort_compare(), select_ammo_inventory_preset::sort_compare(), inventory_column::sort_compare(), inventory_multiselector::toggle_entries(), inventory_compare_selector::toggle_entry(), update_cache(), pickup_selector::wear(), and pickup_selector::wield().
cache_denial()
void inventory_entry::cache_denial (inventory_selector_preset const & preset) const
Definition at line 598 of file inventory_ui.cpp.
 {
     if( !denial ) {
         denial.emplace( preset.get_denial( *this ) );
         enabled = denial->empty();
     }
     if( is_collation_header() ) {
         collation_meta->enabled = denial->empty();
     }
 }
References collation_meta, denial, enabled, inventory_selector_preset::get_denial(), and is_collation_header().
Referenced by inventory_column::expand_to_fit().
get_available_count()
size_t inventory_entry::get_available_count () const
Definition at line 559 of file inventory_ui.cpp.
 {
     if( locations.size() == 1 ) {
         return any_item()->count();
     } else {
         return locations.size();
     }
 }
References any_item(), item::count(), and locations.
Referenced by trade_ui::autobalance(), inventory_column::draw(), selection_column_preset::get_caption(), inventory_multiselector::on_input(), and inventory_multiselector::set_chosen_count().
get_category_ptr()
const item_category * inventory_entry::get_category_ptr () const
Definition at line 609 of file inventory_ui.cpp.
 {
     if( custom_category != nullptr ) {
         return custom_category;
     }
     if( !is_item() ) {
         return nullptr;
     }
     return &any_item()->get_category_of_contents();
 }
References any_item(), custom_category, item::get_category_of_contents(), and is_item().
Referenced by inventory_column::add_entry(), inventory_selector_preset::cat_sort_compare(), inventory_selector_preset::get_cell_text(), is_null(), inventory_column::is_selected_by_category(), and operator==().
get_entry_cell_cache()
const inventory_entry::entry_cell_cache_t & inventory_entry::get_entry_cell_cache (inventory_selector_preset const & preset) const
Definition at line 1015 of file inventory_ui.cpp.
 {
     //lang check here is needed to rebuild cache when using "Toggle language to English" option
     if( !entry_cell_cache ||
         entry_cell_cache->lang_version != detail::get_current_language_version() ) {
         make_entry_cell_cache( preset, false );
         cache_denial( preset );
         cata_assert( entry_cell_cache.has_value() );
         entry_cell_cache->lang_version = detail::get_current_language_version();
     }
     return *entry_cell_cache;
 }
References cata_assert, and detail::get_current_language_version().
Referenced by inventory_column::draw(), inventory_column::get_entry_cell_width(), and inventory_selector_preset::is_stub_cell().
get_invlet()
int inventory_entry::get_invlet () const
Definition at line 568 of file inventory_ui.cpp.
 {
     if( custom_invlet != INT_MIN ) {
         return custom_invlet;
     }
     if( !is_item() ) {
         return '\0';
     }
     return any_item()->invlet;
 }
References any_item(), custom_invlet, item::invlet, and is_item().
Referenced by inventory_column::draw(), and get_invlet_color().
get_invlet_color()
nc_color inventory_entry::get_invlet_color () const
Definition at line 579 of file inventory_ui.cpp.
 {
     if( !is_selectable() ) {
         return c_dark_gray;
     } else if( get_player_character().inv->assigned_invlet.count( get_invlet() ) ) {
         return c_yellow;
     } else {
         return c_white;
     }
 }
References c_dark_gray, c_white, c_yellow, get_invlet(), get_player_character(), and is_selectable().
Referenced by inventory_column::draw().
get_selected_charges()
int inventory_entry::get_selected_charges () const
Definition at line 548 of file inventory_ui.cpp.
 {
     cata_assert( chosen_count <= locations.size() );
     int result = 0;
     for( size_t i = 0; i < chosen_count; ++i ) {
         const item_location &location = locations[i];
         result += location->charges;
     }
     return result;
 }
References cata_assert, chosen_count, location, and locations.
Referenced by selection_column_preset::get_caption().
get_stack_size()
size_t inventory_entry::get_stack_size () const inline
Definition at line 163 of file inventory_ui.h.
{
             return locations.size();
         }
References locations.
Referenced by inventory_selector_preset::get_caption(), and selection_column_preset::get_caption().
get_total_charges()
int inventory_entry::get_total_charges () const
Definition at line 539 of file inventory_ui.cpp.
 {
     int result = 0;
     for( const item_location &location : locations ) {
         result += location->charges;
     }
     return result;
 }
References location, and locations.
Referenced by inventory_selector_preset::get_caption().
is_category()
bool inventory_entry::is_category () const inline
Whether the entry is a category.
Definition at line 124 of file inventory_ui.h.
{
             return !is_null() && !is_item();
         }
References is_item(), and is_null().
Referenced by inventory_column::draw().
is_collated()
bool inventory_entry::is_collated () const inline
Definition at line 141 of file inventory_ui.h.
{
             return static_cast<bool>( collation_meta );
         }
References collation_meta.
Referenced by inventory_column::add_entry(), inventory_column::collated_sort_compare(), inventory_selector::get_collation_next(), is_collation_entry(), and is_collation_header().
is_collation_entry()
bool inventory_entry::is_collation_entry () const inline
Definition at line 149 of file inventory_ui.h.
{
             return is_collated() && !chevron;
         }
References chevron, and is_collated().
Referenced by inventory_column::draw(), inventory_column::get_entry_indent(), inv_internal(), is_hidden(), and inventory_selector::rearrange_columns().
is_collation_header()
bool inventory_entry::is_collation_header () const inline
Definition at line 145 of file inventory_ui.h.
{
             return is_collated() && chevron;
         }
References chevron, and is_collated().
Referenced by cache_denial(), inventory_column::collated_sort_compare(), inventory_column::draw(), inventory_selector_preset::get_caption(), inventory_selector::get_collation_next(), inventory_column::highlight(), reset_collation(), and inventory_column::set_collapsed().
is_hidden()
bool inventory_entry::is_hidden (std::optional< bool > const & hide_entries_override) const
Whether it is hidden in inventory screen.
Definition at line 512 of file inventory_ui.cpp.
 {
     if( !is_item() ) {
         return false;
     }
     if( is_collation_entry() && collation_meta->collapsed ) {
         return true;
     }
     if( !topmost_parent ) {
         return false;
     }
     item_location item = locations.front();
     if( hide_entries_override && topmost_parent && topmost_parent->is_container() ) {
         return *hide_entries_override;
     }
     while( item.has_parent() && item != topmost_parent ) {
         if( item.parent_pocket()->settings.is_collapsed() ) {
             return true;
         }
         item = item.parent_item();
     }
     return false;
 }
References collation_meta, item::is_collapsed(), is_collation_entry(), item::is_container(), is_item(), locations, and topmost_parent.
Referenced by inventory_column::add_entry().
is_highlightable()
bool inventory_entry::is_highlightable (bool skip_unselectable) const inline
Definition at line 137 of file inventory_ui.h.
{
             return is_item() && ( enabled || !skip_unselectable );
         }
References enabled, and is_item().
is_item()
bool inventory_entry::is_item () const inline
Whether the entry is an item.
Definition at line 120 of file inventory_ui.h.
{
             return !locations.empty();
         }
References locations.
Referenced by inventory_column::add_entry(), inventory_column::draw(), inventory_pick_selector::execute(), unload_selector::execute(), inventory_column::expand_to_fit(), get_category_ptr(), inventory_selector_preset::get_cell_text(), inventory_selector_preset::get_color(), read_inventory_preset::get_color(), selection_column_preset::get_color(), inventory_selector_preset::get_denial(), inventory_column::get_entry_indent(), get_invlet(), inventory_selector::highlight(), inventory_column::highlight(), is_category(), is_hidden(), is_highlightable(), is_selectable(), inventory_selector_preset::is_stub_cell(), inventory_selector::rearrange_columns(), anonymous_namespace{inventory_ui.cpp}::return_item(), inventory_multiselector::toggle_entries(), pickup_selector::wear(), and pickup_selector::wield().
is_null()
bool inventory_entry::is_null () const inline
Whether the entry is null (dummy)
Definition at line 114 of file inventory_ui.h.
{
             return get_category_ptr() == nullptr;
         }
References get_category_ptr().
Referenced by is_category(), operator bool(), and selection_column::prepare_paging().
is_selectable()
bool inventory_entry::is_selectable () const inline
Whether the entry can be selected.
Definition at line 133 of file inventory_ui.h.
{
             return is_item() && enabled;
         }
References enabled, and is_item().
Referenced by inventory_column::collated_sort_compare(), inventory_column::draw(), inventory_pick_selector::execute(), ammo_inventory_selector::execute(), unload_selector::execute(), get_invlet_color(), inventory_column::is_selected(), inventory_column::is_selected_by_category(), inventory_multiselector::on_input(), inventory_column::sort_compare(), and inventory_multiselector::toggle_entries().
make_entry_cell_cache()
void inventory_entry::make_entry_cell_cache (inventory_selector_preset const & preset, bool update_only = true) const
Definition at line 995 of file inventory_ui.cpp.
 {
     if( update_only && !entry_cell_cache ) {
         return;
     }
     entry_cell_cache.emplace( entry_cell_cache_t{
         preset.get_color( *this ),
         { preset.get_cells_count(), std::string() } } );
     for( size_t i = 0, n = preset.get_cells_count(); i < n; ++i ) {
         entry_cell_cache->text[i] = preset.get_cell_text( *this, i );
     }
 }
References inventory_selector_preset::get_cell_text(), inventory_selector_preset::get_cells_count(), and inventory_selector_preset::get_color().
Referenced by ammo_inventory_selector::mod_chosen_count(), selection_column::on_change(), inventory_column::set_collapsed(), and inventory_column::set_stack_favorite().
operator bool()
inventory_entry::operator bool () const inline explicit
Definition at line 110 of file inventory_ui.h.
{
             return !is_null();
         }
References is_null().
operator!=()
bool inventory_entry::operator!= (const inventory_entry & other) const inline
Definition at line 106 of file inventory_ui.h.
{
             return !( *this == other );
         }
References other.
operator==()
bool inventory_entry::operator== (const inventory_entry & other) const
Definition at line 244 of file inventory_ui.cpp.
 {
     return get_category_ptr() == other.get_category_ptr() && locations == other.locations;
 }
References get_category_ptr(), locations, and other.
reset_collation()
void inventory_entry::reset_collation () inline
Definition at line 192 of file inventory_ui.h.
{
             if( is_collation_header() ) {
                 chevron = false;
             }
             collation_meta.reset();
         }
References chevron, collation_meta, and is_collation_header().
reset_entry_cell_cache()
void inventory_entry::reset_entry_cell_cache () const
Definition at line 1010 of file inventory_ui.cpp.
 {
     entry_cell_cache.reset();
 }
set_custom_category()
void inventory_entry::set_custom_category (const item_category * category) inline
Definition at line 188 of file inventory_ui.h.
{
             custom_category = category;
         }
References anonymous_namespace{item_tname.cpp}::category(), and custom_category.
update_cache()
void inventory_entry::update_cache ()
Definition at line 590 of file inventory_ui.cpp.
 {
     item_name_t &names = get_cached_name( &*any_item() );
     cached_name = &names.sort_key;
     contents_count = names.contents_count;
     cached_name_full = &names.full_name;
 }
References any_item(), cached_name, cached_name_full, contents_count, anonymous_namespace{inventory_ui.cpp}::get_cached_name(), and PATH_INFO::names().
Referenced by inventory_column::collated_sort_compare(), and inventory_column::indented_sort_compare().
Member Data Documentation
_indent
bool inventory_entry::_indent = true protected
Definition at line 213 of file inventory_ui.h.
cached_denial_space
size_t inventory_entry::cached_denial_space = 0
Definition at line 75 of file inventory_ui.h.
Referenced by inventory_column::draw(), and inventory_multiselector::toggle_entries().
cached_name
std::string* inventory_entry::cached_name = nullptr
Definition at line 72 of file inventory_ui.h.
Referenced by update_cache().
cached_name_full
std::string* inventory_entry::cached_name_full = nullptr
Definition at line 73 of file inventory_ui.h.
Referenced by update_cache().
chevron
bool inventory_entry::chevron = false
Definition at line 182 of file inventory_ui.h.
Referenced by inventory_selector::add_entry_rec(), inventory_column::draw(), is_collation_entry(), is_collation_header(), and reset_collation().
chosen_count
size_t inventory_entry::chosen_count = 0
Definition at line 70 of file inventory_ui.h.
Referenced by pickup_selector::apply_selection(), trade_ui::autobalance(), inventory_column::draw(), ammo_inventory_selector::execute(), selection_column_preset::get_caption(), get_selected_charges(), ammo_inventory_selector::mod_chosen_count(), selection_column::on_change(), inventory_multiselector::on_input(), inventory_multiselector::set_chosen_count(), and inventory_compare_selector::toggle_entry().
collapsed
bool inventory_entry::collapsed = false
Definition at line 177 of file inventory_ui.h.
Referenced by inventory_selector::add_entry(), inventory_column::draw(), inventory_column::on_input(), and inventory_column::set_collapsed().
collation_meta
std::shared_ptr<collation_meta_t> inventory_entry::collation_meta
Definition at line 180 of file inventory_ui.h.
Referenced by cache_denial(), inventory_column::collated_sort_compare(), inventory_selector::get_collation_next(), is_collated(), is_hidden(), reset_collation(), and inventory_column::set_collapsed().
contents_count
unsigned int inventory_entry::contents_count = 0
Definition at line 74 of file inventory_ui.h.
Referenced by update_cache().
custom_category
item_category const* inventory_entry::custom_category = nullptr mutable private
Definition at line 210 of file inventory_ui.h.
Referenced by get_category_ptr(), inventory_entry(), and set_custom_category().
custom_invlet
int inventory_entry::custom_invlet = INT_MIN
Definition at line 71 of file inventory_ui.h.
Referenced by get_invlet().
denial
std::optional<std::string> inventory_entry::denial mutable
Definition at line 186 of file inventory_ui.h.
Referenced by cache_denial(), inventory_column::draw(), inventory_column::expand_to_fit(), and inventory_multiselector::toggle_entries().
enabled
bool inventory_entry::enabled = true mutable
Definition at line 184 of file inventory_ui.h.
Referenced by cache_denial(), is_highlightable(), and is_selectable().
entry_cell_cache
std::optional<entry_cell_cache_t> inventory_entry::entry_cell_cache mutable protected
Definition at line 214 of file inventory_ui.h.
generation
size_t inventory_entry::generation = 0
Definition at line 181 of file inventory_ui.h.
Referenced by inventory_column::collated_sort_compare(), and inventory_column::indented_sort_compare().
highlight_as_child
bool inventory_entry::highlight_as_child = false
Definition at line 176 of file inventory_ui.h.
Referenced by inventory_column::draw().
highlight_as_parent
bool inventory_entry::highlight_as_parent = false
Definition at line 175 of file inventory_ui.h.
Referenced by inventory_column::draw().
indent
int inventory_entry::indent = 0
Definition at line 183 of file inventory_ui.h.
Referenced by inventory_selector::add_entry_rec(), and inventory_column::get_entry_indent().
locations
std::vector<item_location> inventory_entry::locations
Definition at line 68 of file inventory_ui.h.
Referenced by inventory_column::add_entry(), any_item(), inventory_pick_selector::execute(), unload_selector::execute(), get_available_count(), inventory_selector_preset::get_cell_text(), inventory_selector::get_collation_next(), get_selected_charges(), get_stack_size(), get_total_charges(), inventory_selector::highlight(), inventory_column::highlight(), inv_internal(), is_hidden(), is_item(), inventory_selector::on_input(), operator==(), inventory_multiselector::set_chosen_count(), inventory_column::set_collapsed(), inventory_column::set_stack_favorite(), and inventory_selector::toggle_categorize_contained().
topmost_parent
item_location inventory_entry::topmost_parent
Definition at line 179 of file inventory_ui.h.
Referenced by is_hidden().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp