Cataclysm DDA: enum_bitset< E > Class Template Reference
enum_bitset< E > Class Template Reference
#include <enum_bitset.h>
Public Member Functions
enum_bitset ()=default
enum_bitset (const enum_bitset &)=default
enum_bitset & operator= (const enum_bitset &)=default
constexpr enum_bitset (unsigned long long val) noexcept
bool operator== (const enum_bitset &rhs) const noexcept
bool operator!= (const enum_bitset &rhs) const noexcept
enum_bitset & operator&= (const enum_bitset &rhs) noexcept
enum_bitset & operator|= (const enum_bitset &rhs) noexcept
bool operator[] (E e) const
enum_bitset & set (E e, bool val=true)
enum_bitset & set () noexcept
enum_bitset & reset (E e)
enum_bitset & reset ()
bool test (E e) const
bool any () const noexcept
bool all () const noexcept
bool none () const noexcept
void serialize (JsonOut &json) const
Static Public Member Functions
static constexpr size_t size () noexcept
Static Private Member Functions
static constexpr size_t get_pos (E e) noexcept
Private Attributes
std::bitset< enum_bitset< E >::size()> bits
Detailed Description
template<typename E>
class enum_bitset< E >
Definition at line 12 of file enum_bitset.h.
Constructor & Destructor Documentation
enum_bitset() [1/3]
template<typename E > enum_bitset< E >::enum_bitset () default
enum_bitset() [2/3]
template<typename E > enum_bitset< E >::enum_bitset (const enum_bitset< E > &) default
enum_bitset() [3/3]
template<typename E > constexpr enum_bitset< E >::enum_bitset (unsigned long long val) inline explicit constexpr noexcept
Definition at line 24 of file enum_bitset.h.
 : bits( val ) {}
Member Function Documentation
all()
template<typename E > bool enum_bitset< E >::all () const inline noexcept
Definition at line 76 of file enum_bitset.h.
{
             return bits.all();
         }
References enum_bitset< E >::bits.
any()
template<typename E > bool enum_bitset< E >::any () const inline noexcept
Definition at line 72 of file enum_bitset.h.
{
             return bits.any();
         }
References enum_bitset< E >::bits.
get_pos()
template<typename E > static constexpr size_t enum_bitset< E >::get_pos (E e) inline static constexpr private noexcept
Definition at line 101 of file enum_bitset.h.
{
             return static_cast<size_t>( static_cast<std::underlying_type_t<E>>( e ) );
         }
Referenced by enum_bitset< E >::operator[](), enum_bitset< E >::reset(), enum_bitset< E >::set(), enum_bitset< E >::size(), and enum_bitset< E >::test().
none()
template<typename E > bool enum_bitset< E >::none () const inline noexcept
Definition at line 80 of file enum_bitset.h.
{
             return bits.none();
         }
References enum_bitset< E >::bits.
operator!=()
template<typename E > bool enum_bitset< E >::operator!= (const enum_bitset< E > & rhs) const inline noexcept
Definition at line 30 of file enum_bitset.h.
{
             return !( *this == rhs );
         }
operator&=()
template<typename E > enum_bitset& enum_bitset< E >::operator&= (const enum_bitset< E > & rhs) inline noexcept
Definition at line 34 of file enum_bitset.h.
{
             bits &= rhs.bits;
             return *this;
         }
References enum_bitset< E >::bits.
operator=()
template<typename E > enum_bitset& enum_bitset< E >::operator= (const enum_bitset< E > &) default
operator==()
template<typename E > bool enum_bitset< E >::operator== (const enum_bitset< E > & rhs) const inline noexcept
Definition at line 26 of file enum_bitset.h.
{
             return bits == rhs.bits;
         }
References enum_bitset< E >::bits.
operator[]()
template<typename E > bool enum_bitset< E >::operator[] (E e) const inline
Definition at line 44 of file enum_bitset.h.
{
             return bits[ get_pos( e ) ];
         }
References enum_bitset< E >::bits, and enum_bitset< E >::get_pos().
operator|=()
template<typename E > enum_bitset& enum_bitset< E >::operator|= (const enum_bitset< E > & rhs) inline noexcept
Definition at line 39 of file enum_bitset.h.
{
             bits |= rhs.bits;
             return *this;
         }
References enum_bitset< E >::bits.
reset() [1/2]
template<typename E > enum_bitset& enum_bitset< E >::reset () inline
Definition at line 63 of file enum_bitset.h.
{
             bits.reset();
             return *this;
         }
References enum_bitset< E >::bits.
reset() [2/2]
template<typename E > enum_bitset& enum_bitset< E >::reset (E e) inline
Definition at line 58 of file enum_bitset.h.
{
             bits.reset( get_pos( e ) );
             return *this;
         }
References enum_bitset< E >::bits, and enum_bitset< E >::get_pos().
Referenced by anonymous_namespace{item.cpp}::_aggregate(), reader_detail::handler< enum_bitset< E > >::clear(), and reader_detail::handler< enum_bitset< E > >::erase().
serialize()
template<typename E > void enum_bitset< E >::serialize (JsonOut & json) const inline
Definition at line 88 of file enum_bitset.h.
{
             json.start_array();
             for( size_t i = 0; i < size(); i++ ) {
                 const E cast_num = static_cast<E>( i );
                 if( test( cast_num ) ) {
                     json.write_as_string( cast_num );
                 }
             }
             json.end_array();
         }
References JsonOut::end_array(), enum_bitset< E >::size(), JsonOut::start_array(), enum_bitset< E >::test(), and JsonOut::write_as_string().
set() [1/2]
template<typename E > enum_bitset& enum_bitset< E >::set () inline noexcept
Definition at line 53 of file enum_bitset.h.
{
             bits.set();
             return *this;
         }
References enum_bitset< E >::bits.
set() [2/2]
template<typename E > enum_bitset& enum_bitset< E >::set (E e, bool val = true) inline
Definition at line 48 of file enum_bitset.h.
{
             bits.set( get_pos( e ), val );
             return *this;
         }
References enum_bitset< E >::bits, and enum_bitset< E >::get_pos().
Referenced by item::aggregate_t::aggregate_t(), anonymous_namespace{item_tname.cpp}::contents(), inventory_selector::drag_drop_item(), reader_detail::handler< enum_bitset< E > >::insert(), spell_type::load(), make_gun_sound_effect(), TextJsonIn::read(), JsonValue::read(), map_data_common_t::set_flag(), oter_type_t::set_flag(), and Character::weapname_simple().
size()
template<typename E > static constexpr size_t enum_bitset< E >::size () inline static constexpr noexcept
Definition at line 84 of file enum_bitset.h.
{
             return get_pos( enum_traits<E>::last );
         }
References enum_bitset< E >::get_pos().
Referenced by enum_bitset< E >::serialize().
test()
template<typename E > bool enum_bitset< E >::test (E e) const inline
Definition at line 68 of file enum_bitset.h.
{
             return bits.test( get_pos( e ) );
         }
References enum_bitset< E >::bits, and enum_bitset< E >::get_pos().
Referenced by mapgendata::has_flag(), TextJsonIn::read(), JsonValue::read(), and enum_bitset< E >::serialize().
Member Data Documentation
bits
template<typename E > std::bitset<enum_bitset<E>::size()> enum_bitset< E >::bits private
Definition at line 105 of file enum_bitset.h.
Referenced by anonymous_namespace{item.cpp}::_aggregate(), enum_bitset< E >::all(), enum_bitset< E >::any(), enum_bitset< E >::none(), enum_bitset< E >::operator&=(), enum_bitset< E >::operator==(), enum_bitset< E >::operator[](), enum_bitset< E >::operator|=(), enum_bitset< E >::reset(), enum_bitset< E >::set(), and enum_bitset< E >::test().
The documentation for this class was generated from the following file:
src/enum_bitset.h