Cataclysm DDA: relic_procgen_data Class Reference
relic_procgen_data Class Reference
#include <relic.h>
Classes
struct enchantment_active
struct enchantment_value_passive
struct generation_rules
Public Types
enum type {
passive_enchantment_add , passive_enchantment_mult , hit_you , hit_me ,
active_enchantment , last
}
Public Member Functions
int power_level (const enchant_cache &ench) const
int power_level (const fake_spell &sp) const
item create_item (const relic_procgen_data::generation_rules &rules) const
relic generate (const generation_rules &rules, const itype_id &it_id) const
void load (const JsonObject &jo, std::string_view={})
void deserialize (const JsonObject &jobj)
Static Public Member Functions
static const std::vector< relic_procgen_data > & get_all ()
static void load_relic_procgen_data (const JsonObject &jo, const std::string &src)
static void reset ()
Public Attributes
relic_procgen_id id
std::vector< std::pair< relic_procgen_id, mod_id > > src
bool was_loaded = false
Private Attributes
weighted_int_list< relic_charge_template > charge_values
weighted_int_list< enchantment_value_passive< int > > passive_add_procgen_values
weighted_int_list< enchantment_value_passive< float > > passive_mult_procgen_values
weighted_int_list< enchantment_active > passive_hit_you
weighted_int_list< enchantment_active > passive_hit_me
weighted_int_list< enchantment_active > active_procgen_values
weighted_int_list< type > type_weights
weighted_int_list< itype_id > item_weights
Detailed Description
Definition at line 31 of file relic.h.
Member Enumeration Documentation
type
enum relic_procgen_data::type
Enumerator
passive_enchantment_add
passive_enchantment_mult
hit_you
hit_me
active_enchantment
last
Definition at line 102 of file relic.h.
                   {
             passive_enchantment_add,
             passive_enchantment_mult,
             hit_you,
             hit_me,
             active_enchantment,
             last
         };
Member Function Documentation
create_item()
item relic_procgen_data::create_item (const relic_procgen_data::generation_rules & rules) const
Definition at line 637 of file relic.cpp.
 {
     const itype_id *it_id = item_weights.pick();
     if( it_id == nullptr ) {
         debugmsg( "ERROR: %s procgen data does not have items", id.c_str() );
         return null_item_reference();
     }
     item it( *it_id, calendar::turn );
     it.overwrite_relic( generate( rules, *it_id ) );
     return it;
 }
References debugmsg, generate(), item_weights, null_item_reference(), item::overwrite_relic(), and calendar::turn.
deserialize()
void relic_procgen_data::deserialize (const JsonObject & jobj)
Definition at line 237 of file relic.cpp.
 {
     load( jobj );
 }
References load().
generate()
relic relic_procgen_data::generate (const generation_rules & rules, const itype_id & it_id) const
Definition at line 652 of file relic.cpp.
 {
     relic ret;
     int num_attributes = 0;
     int negative_attribute_power = 0;
     const bool is_armor = item( it_id ).is_armor();
     while( rules.max_attributes > num_attributes && rules.power_level > ret.power_level( id ) ) {
         switch( *type_weights.pick() ) {
             case relic_procgen_data::type::active_enchantment: {
                 const relic_procgen_data::enchantment_active *active = active_procgen_values.pick();
                 if( active != nullptr ) {
                     fake_spell active_sp;
                     active_sp.id = active->activated_spell;
                     active_sp.level = rng( active->min_level, active->max_level );
                     int power = power_level( active_sp );
                     if( power < 0 ) {
                         if( rules.max_negative_power > negative_attribute_power ) {
                             break;
                         }
                         negative_attribute_power += power;
                     }
                     num_attributes++;
                     ret.add_active_effect( active_sp );
                 }
                 break;
             }
             case relic_procgen_data::type::passive_enchantment_add: {
                 const relic_procgen_data::enchantment_value_passive<int> *add = passive_add_procgen_values.pick();
                 if( add != nullptr ) {
                     enchant_cache ench;
                     int value = rng( add->min_value, add->max_value );
                     if( value == 0 ) {
                         break;
                     }
                     ench.add_value_add( add->type, value );
                     int negative_ench_attribute = power_level( ench );
                     if( negative_ench_attribute < 0 ) {
                         if( rules.max_negative_power > negative_attribute_power ) {
                             break;
                         }
                         negative_attribute_power += negative_ench_attribute;
                     }
                     if( add->ench_has ) {
                         ench.set_has( add->ench_has );
                     } else if( is_armor ) {
                         ench.set_has( enchantment::has::WORN );
                     } else {
                         ench.set_has( enchantment::has::HELD );
                     }
                     num_attributes++;
                     ret.add_passive_effect( ench );
                 }
                 break;
             }
             case relic_procgen_data::type::passive_enchantment_mult: {
                 const relic_procgen_data::enchantment_value_passive<float> *mult =
                     passive_mult_procgen_values.pick();
                 if( mult != nullptr ) {
                     enchant_cache ench;
                     float value = rng_float( mult->min_value, mult->max_value );
                     ench.add_value_mult( mult->type, value );
                     int negative_ench_attribute = power_level( ench );
                     if( negative_ench_attribute < 0 ) {
                         if( rules.max_negative_power > negative_attribute_power ) {
                             break;
                         }
                         negative_attribute_power += negative_ench_attribute;
                     }
                     if( mult->ench_has ) {
                         ench.set_has( mult->ench_has );
                     } else if( is_armor ) {
                         ench.set_has( enchantment::has::WORN );
                     } else {
                         ench.set_has( enchantment::has::HELD );
                     }
                     num_attributes++;
                     ret.add_passive_effect( ench );
                 }
                 break;
             }
             case relic_procgen_data::type::hit_me: {
                 const relic_procgen_data::enchantment_active *active = passive_hit_me.pick();
                 if( active != nullptr ) {
                     fake_spell active_sp;
                     active_sp.id = active->activated_spell;
                     active_sp.level = rng( active->min_level, active->max_level );
                     enchant_cache ench;
                     ench.add_hit_me( active_sp );
                     int power = power_level( ench );
                     if( power < 0 ) {
                         if( rules.max_negative_power > negative_attribute_power ) {
                             break;
                         }
                         negative_attribute_power += power;
                     }
                     if( active->ench_has ) {
                         ench.set_has( active->ench_has );
                     } else if( is_armor ) {
                         ench.set_has( enchantment::has::WORN );
                     } else {
                         ench.set_has( enchantment::has::HELD );
                     }
                     num_attributes++;
                     ret.add_passive_effect( ench );
                 }
                 break;
             }
             case relic_procgen_data::type::hit_you: {
                 const relic_procgen_data::enchantment_active *active = passive_hit_you.pick();
                 if( active != nullptr ) {
                     fake_spell active_sp;
                     active_sp.id = active->activated_spell;
                     active_sp.level = rng( active->min_level, active->max_level );
                     enchant_cache ench;
                     ench.add_hit_you( active_sp );
                     int power = power_level( ench );
                     if( power < 0 ) {
                         if( rules.max_negative_power > negative_attribute_power ) {
                             break;
                         }
                         negative_attribute_power += power;
                     }
                     if( active->ench_has ) {
                         ench.set_has( active->ench_has );
                     } else if( is_armor ) {
                         ench.set_has( enchantment::has::WORN );
                     } else {
                         ench.set_has( enchantment::has::HELD );
                     }
                     num_attributes++;
                     ret.add_passive_effect( ench );
                 }
                 break;
             }
             case relic_procgen_data::type::last: {
                 debugmsg( "ERROR: invalid relic procgen type" );
                 break;
             }
         }
     }
     if( ret.has_activation() ) {
         const relic_charge_template *charge = charge_values.pick();
         if( charge != nullptr ) {
             ret.overwrite_charge( charge->generate() );
         }
     }
     //add an optional enchantment of the value of ret's power (the artifact being created) - resonance is equal to its power (min zero)
     if( rules.resonant ) {
         enchant_cache resonance;
         int value = std::max( 0, ret.power_level( id ) );
         resonance.add_value_add( enchant_vals::mod::ARTIFACT_RESONANCE, value );
         resonance.set_has( enchantment::has::HELD );
         ret.add_passive_effect( resonance );
     }
     return ret;
 }
References active, active_procgen_values, add, enchant_cache::add_hit_me(), enchant_cache::add_hit_you(), enchant_cache::add_value_add(), enchant_cache::add_value_mult(), enchant_vals::ARTIFACT_RESONANCE, charge_values, debugmsg, relic_procgen_data::enchantment_value_passive< T >::ench_has, relic_charge_template::generate(), fake_spell::id, item, last, fake_spell::level, max(), relic_procgen_data::generation_rules::max_attributes, relic_procgen_data::generation_rules::max_negative_power, relic_procgen_data::enchantment_value_passive< T >::max_value, relic_procgen_data::enchantment_value_passive< T >::min_value, passive_add_procgen_values, passive_hit_me, passive_hit_you, passive_mult_procgen_values, weighted_list< W, T >::pick(), relic_procgen_data::generation_rules::power_level, power_level(), relic_procgen_data::generation_rules::resonant, cata::hash64_detail::ret, rng(), rng_float(), enchant_cache::set_has(), relic_procgen_data::enchantment_value_passive< T >::type, and type_weights.
Referenced by create_item().
get_all()
const std::vector< relic_procgen_data > & relic_procgen_data::get_all () static
Definition at line 835 of file relic.cpp.
 {
     return relic_procgen_data_factory.get_all();
 }
References anonymous_namespace{relic.cpp}::relic_procgen_data_factory.
Referenced by debug_menu::spawn_artifact().
load()
void relic_procgen_data::load (const JsonObject & jo, std::string_view = {})
Definition at line 167 of file relic.cpp.
 {
     for( const JsonObject jo_inner : jo.get_array( "passive_add_procgen_values" ) ) {
         int weight = 0;
         mandatory( jo_inner, was_loaded, "weight", weight );
         relic_procgen_data::enchantment_value_passive<int> val;
         val.load( jo_inner );
         passive_add_procgen_values.add( val, weight );
     }
     for( const JsonObject jo_inner : jo.get_array( "passive_mult_procgen_values" ) ) {
         int weight = 0;
         mandatory( jo_inner, was_loaded, "weight", weight );
         relic_procgen_data::enchantment_value_passive<float> val;
         val.load( jo_inner );
         passive_mult_procgen_values.add( val, weight );
     }
     for( const JsonObject jo_inner : jo.get_array( "type_weights" ) ) {
         int weight = 0;
         mandatory( jo_inner, was_loaded, "weight", weight );
         relic_procgen_data::type val = relic_procgen_data::type::last;
         mandatory( jo_inner, was_loaded, "value", val );
         type_weights.add( val, weight );
     }
     for( const JsonObject jo_inner : jo.get_array( "items" ) ) {
         int weight = 0;
         mandatory( jo_inner, was_loaded, "weight", weight );
         itype_id it;
         mandatory( jo_inner, was_loaded, "item", it );
         item_weights.add( it, weight );
     }
     for( const JsonObject jo_inner : jo.get_array( "active_procgen_values" ) ) {
         int weight = 0;
         mandatory( jo_inner, was_loaded, "weight", weight );
         relic_procgen_data::enchantment_active val;
         val.load( jo_inner );
         active_procgen_values.add( val, weight );
     }
     for( const JsonObject jo_inner : jo.get_array( "charge_types" ) ) {
         int weight = 0;
         mandatory( jo_inner, was_loaded, "weight", weight );
         relic_charge_template charge;
         charge.load( jo_inner );
         charge_values.add( charge, weight );
     }
 }
References active_procgen_values, weighted_list< W, T >::add(), charge_values, JsonObject::get_array(), item_weights, last, relic_procgen_data::enchantment_value_passive< T >::load(), relic_procgen_data::enchantment_active::load(), relic_charge_template::load(), mandatory, passive_add_procgen_values, passive_mult_procgen_values, type_weights, and was_loaded.
Referenced by relic_procgen_data::generation_rules::deserialize(), relic_charge_template::deserialize(), relic_charge_info::deserialize(), relic_procgen_data::enchantment_active::deserialize(), deserialize(), and relic::deserialize().
load_relic_procgen_data()
void relic_procgen_data::load_relic_procgen_data (const JsonObject & jo, const std::string & src) static
Definition at line 104 of file relic.cpp.
 {
     relic_procgen_data_factory.load( jo, src );
 }
References anonymous_namespace{relic.cpp}::relic_procgen_data_factory, and src.
Referenced by DynamicDataLoader::initialize().
power_level() [1/2]
int relic_procgen_data::power_level (const enchant_cache & ench) const
Definition at line 602 of file relic.cpp.
 {
     int power = 0;
     for( const weighted_object<int, relic_procgen_data::enchantment_value_passive<int>>
          &add_val_passive : passive_add_procgen_values ) {
         int val = ench.get_value_add( add_val_passive.obj.type );
         if( val != 0 ) {
             power += static_cast<float>( add_val_passive.obj.power_per_increment ) /
                      static_cast<float>( add_val_passive.obj.increment ) * val;
         }
     }
     for( const weighted_object<int, relic_procgen_data::enchantment_value_passive<float>>
          &mult_val_passive : passive_mult_procgen_values ) {
         float val = ench.get_value_multiply( mult_val_passive.obj.type );
         if( val != 0.0f ) {
             power += mult_val_passive.obj.power_per_increment / mult_val_passive.obj.increment * val;
         }
     }
     return power;
 }
References enchant_cache::get_value_add(), enchant_cache::get_value_multiply(), passive_add_procgen_values, and passive_mult_procgen_values.
Referenced by relic_charge_template::generate(), generate(), relic_procgen_data::generation_rules::load(), relic_charge_template::load(), and relic::power_level().
power_level() [2/2]
int relic_procgen_data::power_level (const fake_spell & sp) const
Definition at line 626 of file relic.cpp.
 {
     for( const weighted_object<int, relic_procgen_data::enchantment_active> &vals :
          active_procgen_values ) {
         if( vals.obj.activated_spell == sp.id ) {
             return vals.obj.calc_power( sp.level );
         }
     }
     return 0;
 }
References active_procgen_values, fake_spell::id, and fake_spell::level.
reset()
void relic_procgen_data::reset () static
Definition at line 157 of file relic.cpp.
 {
     relic_procgen_data_factory.reset();
 }
References anonymous_namespace{relic.cpp}::relic_procgen_data_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
active_procgen_values
weighted_int_list<enchantment_active> relic_procgen_data::active_procgen_values private
Definition at line 117 of file relic.h.
Referenced by generate(), load(), and power_level().
charge_values
weighted_int_list<relic_charge_template> relic_procgen_data::charge_values private
Definition at line 112 of file relic.h.
Referenced by generate(), and load().
id
relic_procgen_id relic_procgen_data::id
Definition at line 122 of file relic.h.
item_weights
weighted_int_list<itype_id> relic_procgen_data::item_weights private
Definition at line 119 of file relic.h.
Referenced by create_item(), and load().
passive_add_procgen_values
weighted_int_list<enchantment_value_passive<int> > relic_procgen_data::passive_add_procgen_values private
Definition at line 113 of file relic.h.
Referenced by generate(), load(), and power_level().
passive_hit_me
weighted_int_list<enchantment_active> relic_procgen_data::passive_hit_me private
Definition at line 116 of file relic.h.
Referenced by generate().
passive_hit_you
weighted_int_list<enchantment_active> relic_procgen_data::passive_hit_you private
Definition at line 115 of file relic.h.
Referenced by generate().
passive_mult_procgen_values
weighted_int_list<enchantment_value_passive<float> > relic_procgen_data::passive_mult_procgen_values private
Definition at line 114 of file relic.h.
Referenced by generate(), load(), and power_level().
src
std::vector<std::pair<relic_procgen_id, mod_id> > relic_procgen_data::src
Definition at line 123 of file relic.h.
Referenced by load_relic_procgen_data().
type_weights
weighted_int_list<type> relic_procgen_data::type_weights private
Definition at line 118 of file relic.h.
Referenced by generate(), and load().
was_loaded
bool relic_procgen_data::was_loaded = false
Definition at line 132 of file relic.h.
Referenced by relic_procgen_data::generation_rules::load(), and load().
The documentation for this class was generated from the following files:
src/relic.h
src/relic.cpp