Cataclysm DDA: options_manager::Page Class Reference
options_manager::Page Class Reference
A page (or tab) to be displayed in the options UI.
Public Member Functions
void removeRepeatedEmptyLines ()
Page (const std::string &id, const translation &name)
Public Attributes
std::string id_
Page identifier.
translation name_
Page name.
std::vector< PageItem > items_
Page items (entries)
Detailed Description
A page (or tab) to be displayed in the options UI.
It contains a id that is used to detect what options should go into this page (see cOpt::getPage). It also has a name that will be translated and displayed. And it has items, each item is either nothing (will be represented as empty line in the UI) or the name of an option.
Definition at line 332 of file options.h.
Constructor & Destructor Documentation
Page()
options_manager::Page::Page (const std::string & id, const translation & name) inline
Definition at line 344 of file options.h.
 : id_( id ), name_( name ) { }
Member Function Documentation
removeRepeatedEmptyLines()
void options_manager::Page::removeRepeatedEmptyLines ()
Definition at line 1409 of file options.cpp.
 {
     const auto empty = [&]( const PageItem & it ) -> bool {
         return it.type == ItemType::BlankLine ||
         ( it.type == ItemType::Option && get_options().get_option( it.data ).is_hidden() );
     };
     while( !items_.empty() && empty( items_.front() ) ) {
         items_.erase( items_.begin() );
     }
     while( !items_.empty() && empty( items_.back() ) ) {
         items_.erase( items_.end() - 1 );
     }
     for( auto iter = std::next( items_.begin() ); iter != items_.end(); ) {
         if( empty( *std::prev( iter ) ) && empty( *iter ) ) {
             iter = items_.erase( iter );
         } else {
             ++iter;
         }
     }
 }
References options_manager::get_option(), get_options(), and options_manager::cOpt::is_hidden().
Member Data Documentation
id_
std::string options_manager::Page::id_
Page identifier.
Definition at line 336 of file options.h.
items_
std::vector<PageItem> options_manager::Page::items_
Page items (entries)
Definition at line 340 of file options.h.
Referenced by options_manager::show().
name_
translation options_manager::Page::name_
Page name.
Definition at line 338 of file options.h.
The documentation for this class was generated from the following files:
src/options.h
src/options.cpp