Cataclysm DDA: ter_furn_data< T > Class Template Reference
ter_furn_data< T > Class Template Reference
#include <magic_ter_furn_transform.h>
Public Member Functions
ter_furn_data ()=default
ter_furn_data (const weighted_int_list< T > &list, const translation &message, const bool message_good)
bool has_msg () const
std::optional< T > pick () const
void load (const JsonObject &jo)
Public Attributes
weighted_int_list< T > list
translation message
bool message_good = false
Detailed Description
template<class T>
class ter_furn_data< T >
Definition at line 20 of file magic_ter_furn_transform.h.
Constructor & Destructor Documentation
ter_furn_data() [1/2]
template<class T > ter_furn_data< T >::ter_furn_data () default
ter_furn_data() [2/2]
template<class T > ter_furn_data< T >::ter_furn_data (const weighted_int_list< T > & list, const translation & message, const bool message_good) inline
Definition at line 27 of file magic_ter_furn_transform.h.
                                                  :
             list( list ), message( message ), message_good( message_good ) {}
Member Function Documentation
has_msg()
template<class T > bool ter_furn_data< T >::has_msg
Definition at line 314 of file magic_ter_fur_transform.cpp.
 {
     return !message.empty();
 }
References mapgen_defer::message.
load()
template<class T > void ter_furn_data< T >::load (const JsonObject & jo)
Definition at line 79 of file magic_ter_fur_transform.cpp.
 {
     load_transform_results( jo, "result", list );
     jo.read( "message", message, false );
     message_good = jo.get_bool( "message_good", true );
 }
References JsonObject::get_bool(), load_transform_results(), mapgen_defer::message, and JsonObject::read().
Referenced by ter_furn_transform::load().
pick()
template<class T > std::optional< T > ter_furn_data< T >::pick
Definition at line 304 of file magic_ter_fur_transform.cpp.
 {
     const T *picked = list.pick();
     if( picked == nullptr ) {
         return std::nullopt;
     }
     return *picked;
 }
Member Data Documentation
list
template<class T > weighted_int_list<T> ter_furn_data< T >::list
Definition at line 23 of file magic_ter_furn_transform.h.
message
template<class T > translation ter_furn_data< T >::message
Definition at line 24 of file magic_ter_furn_transform.h.
message_good
template<class T > bool ter_furn_data< T >::message_good = false
Definition at line 25 of file magic_ter_furn_transform.h.
The documentation for this class was generated from the following files:
src/magic_ter_furn_transform.h
src/magic_ter_fur_transform.cpp