Cataclysm DDA: wear_activity_actor Class Reference
wear_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
wear_activity_actor (std::vector< item_location > target_items, std::vector< int > quantities)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &)
Private Attributes
std::vector< item_location > target_items
std::vector< int > quantities
contents_change_handler handler
Detailed Description
Definition at line 1703 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
wear_activity_actor()
wear_activity_actor::wear_activity_actor (std::vector< item_location > target_items, std::vector< int > quantities) inline
Definition at line 1706 of file activity_actor_definitions.h.
                                                                                                 :
             target_items( std::move( target_items ) ),
             quantities( std::move( quantities ) ) {};
Member Function Documentation
clone()
std::unique_ptr<activity_actor> wear_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1717 of file activity_actor_definitions.h.
{
             return std::make_unique<wear_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > wear_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6148 of file activity_actor.cpp.
 {
     wear_activity_actor actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "target_items", actor.target_items );
     data.read( "quantities", actor.quantities );
     data.read( "handler", actor.handler );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void wear_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 6088 of file activity_actor.cpp.
 {
     // ACT_WEAR has item_location targets, and int quantities
     while( who.get_moves() > 0 && !target_items.empty() ) {
         item_location target = std::move( target_items.back() );
         int quantity = quantities.back();
         target_items.pop_back();
         quantities.pop_back();
         if( !target ) {
             debugmsg( "Lost target item of ACT_WEAR" );
             continue;
         }
         // Make copies so the original remains untouched if wearing fails
         item newit = *target;
         item leftovers = newit;
         // Handle charges, quantity == 0 means move all
         if( quantity != 0 && newit.count_by_charges() ) {
             leftovers.charges = newit.charges - quantity;
             if( leftovers.charges > 0 ) {
                 newit.charges = quantity;
             }
         } else {
             leftovers.charges = 0;
         }
         if( check_stealing( who, newit ) ) {
             handler.unseal_pocket_containing( target );
             if( who.wear_item( newit ) ) {
                 // If we wore up a whole stack, remove the original item
                 // Otherwise, replace the item with the leftovers
                 if( leftovers.charges > 0 ) {
                     *target = std::move( leftovers );
                 } else {
                     target.remove_item();
                 }
             }
         }
     }
     // If there are no items left we are done
     if( target_items.empty() ) {
         handler.handle_by( who );
         who.cancel_activity();
     }
 }
References Character::cancel_activity(), item::charges, check_stealing(), item::count_by_charges(), debugmsg, Creature::get_moves(), contents_change_handler::handle_by(), handler, quantities, item_location::remove_item(), target_items, contents_change_handler::unseal_pocket_containing(), and Character::wear_item().
finish()
void wear_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1715 of file activity_actor_definitions.h.
 {};
get_type()
activity_id wear_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1709 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_WEAR" );
         }
References activity_id.
serialize()
void wear_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6137 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target_items", target_items );
     jsout.member( "quantities", quantities );
     jsout.member( "handler", handler );
     jsout.end_object();
 }
References JsonOut::end_object(), handler, JsonOut::member(), quantities, JsonOut::start_object(), and target_items.
start()
void wear_activity_actor::start (player_activity & act, Character & who) inline override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1713 of file activity_actor_definitions.h.
 {};
Member Data Documentation
handler
contents_change_handler wear_activity_actor::handler private
Definition at line 1727 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
quantities
std::vector<int> wear_activity_actor::quantities private
Definition at line 1726 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
target_items
std::vector<item_location> wear_activity_actor::target_items private
Definition at line 1725 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp