Cataclysm DDA: gunmod_inventory_preset Class Reference
gunmod_inventory_preset Class Reference
Public Member Functions
gunmod_inventory_preset (const Character &you, const item &gunmod)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const override
Whether the first item is considered to go before the second.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Protected Member Functions
std::pair< int, int > get_odds (const item_location &gun) const
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Private Attributes
const Character & you
const item & gunmod
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 1187 of file game_inventory.cpp.
Constructor & Destructor Documentation
gunmod_inventory_preset()
gunmod_inventory_preset::gunmod_inventory_preset (const Character & you, const item & gunmod) inline
Definition at line 1190 of file game_inventory.cpp.
                                                                             : you( you ), gunmod( gunmod ) {
             append_cell( [ this ]( const item_location & loc ) {
                 const auto odds = get_odds( loc );
                 if( odds.first >= 100 ) {
                     return string_format( "<color_light_green>%s</color>", _( "always" ) );
                 }
                 return string_format( "<color_light_green>%d%%</color>", odds.first );
             }, _( "SUCCESS CHANCE" ) );
             append_cell( [ this ]( const item_location & loc ) {
                 return good_bad_none( get_odds( loc ).second );
             }, _( "DAMAGE RISK" ) );
         }
References _, inventory_selector_preset::append_cell(), get_odds(), anonymous_namespace{game_inventory.cpp}::good_bad_none(), second, and string_format().
Member Function Documentation
get_denial()
std::string gunmod_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 1210 of file game_inventory.cpp.
{
             const auto ret = loc->is_gunmod_compatible( gunmod );
             if( !ret.success() ) {
                 return ret.str();
             }
             if( !you.meets_requirements( gunmod, *loc ) ) {
                 return string_format( _( "requires at least %s" ),
                                       you.enumerate_unmet_requirements( gunmod, *loc ) );
             }
             if( get_odds( loc ).first <= 0 ) {
                 return _( "is too difficult for you to modify" );
             }
             return std::string();
         }
References _, Character::enumerate_unmet_requirements(), get_odds(), gunmod, item::is_gunmod_compatible(), Character::meets_requirements(), cata::hash64_detail::ret, string_format(), and you.
get_odds()
std::pair<int, int> gunmod_inventory_preset::get_odds (const item_location & gun) const inline protected
Returns
Odds for successful installation (pair.first) and gunmod damage (pair.second)
Definition at line 1242 of file game_inventory.cpp.
{
             return you.gunmod_installation_odds( gun, gunmod );
         }
References gun, gunmod, Character::gunmod_installation_odds(), and you.
Referenced by get_denial(), gunmod_inventory_preset(), and sort_compare().
is_shown()
bool gunmod_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 1206 of file game_inventory.cpp.
{
             return loc->is_gun() && !loc->is_gunmod();
         }
References item::is_gun(), and item::is_gunmod().
sort_compare()
bool gunmod_inventory_preset::sort_compare (const inventory_entry & lhs, const inventory_entry & rhs) const inline override virtual
Whether the first item is considered to go before the second.
Reimplemented from inventory_selector_preset.
Definition at line 1229 of file game_inventory.cpp.
{
             const auto a = get_odds( lhs.any_item() );
             const auto b = get_odds( rhs.any_item() );
             if( a.first > b.first || ( a.first == b.first && a.second < b.second ) ) {
                 return true;
             }
             return inventory_selector_preset::sort_compare( lhs, rhs );
         }
References a, inventory_entry::any_item(), b, get_odds(), and inventory_selector_preset::sort_compare().
Member Data Documentation
gunmod
const item& gunmod_inventory_preset::gunmod private
Definition at line 1248 of file game_inventory.cpp.
Referenced by get_denial(), and get_odds().
you
const Character& gunmod_inventory_preset::you private
Definition at line 1247 of file game_inventory.cpp.
Referenced by get_denial(), and get_odds().
The documentation for this class was generated from the following file:
src/game_inventory.cpp