Cataclysm DDA: effect_on_conditons_actor Class Reference
effect_on_conditons_actor Class Reference
Activate an array of effect_on_conditions.
#include <iuse_actor.h>
Public Member Functions
effect_on_conditons_actor (const std::string &type="effect_on_conditions")
~effect_on_conditons_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *p, item &it, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
std::string get_name () const override
Returns the translated name of the action.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::vector< effect_on_condition_id > eocs
translation description
translation menu_text
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Activate an array of effect_on_conditions.
Definition at line 1171 of file iuse_actor.h.
Constructor & Destructor Documentation
effect_on_conditons_actor()
effect_on_conditons_actor::effect_on_conditons_actor (const std::string & type = "effect_on_conditions") inline explicit
Definition at line 1177 of file iuse_actor.h.
                                                                                              : iuse_actor(
                 type ) {}
~effect_on_conditons_actor()
effect_on_conditons_actor::~effect_on_conditons_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > effect_on_conditons_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 5544 of file iuse_actor.cpp.
 {
     return std::make_unique<effect_on_conditons_actor>( *this );
 }
get_name()
std::string effect_on_conditons_actor::get_name () const override virtual
Returns the translated name of the action.
It is used for the item action menu.
Reimplemented from iuse_actor.
Definition at line 5558 of file iuse_actor.cpp.
 {
     if( !menu_text.empty() ) {
         return menu_text.translated();
     }
     return iuse_actor::get_name();
 }
References iuse_actor::get_name().
info()
void effect_on_conditons_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 5566 of file iuse_actor.cpp.
 {
     dump.emplace_back( "DESCRIPTION", description.translated() );
 }
load()
void effect_on_conditons_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 5549 of file iuse_actor.cpp.
 {
     obj.read( "description", description );
     obj.read( "menu_text", menu_text );
     for( JsonValue jv : obj.get_array( "effect_on_conditions" ) ) {
         eocs.emplace_back( effect_on_conditions::load_inline_eoc( jv, "" ) );
     }
 }
References JsonObject::get_array(), effect_on_conditions::load_inline_eoc(), and JsonObject::read().
use()
std::optional< int > effect_on_conditons_actor::use (Character * p, item & it, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 5571 of file iuse_actor.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action effect_on_conditons that requires character but no character is present",
                   it.typeId().str() );
         return std::nullopt;
     }
     Character *char_ptr = nullptr;
     if( avatar *u = p->as_avatar() ) {
         char_ptr = u;
     } else if( npc *n = p->as_npc() ) {
         char_ptr = n;
     }
     item_location loc( *p->as_character(), &it );
     dialogue d( get_talker_for( char_ptr ), get_talker_for( loc ) );
     write_var_value( var_type::context, "npctalk_var_id", &d, it.typeId().str() );
     for( const effect_on_condition_id &eoc : eocs ) {
         if( eoc->type == eoc_type::ACTIVATION ) {
             eoc->activate( d );
         } else {
             debugmsg( "Must use an activation eoc for activation.  If you don't want the effect_on_condition to happen on its own (without the item's involvement), remove the recurrence min and max.  Otherwise, create a non-recurring effect_on_condition for this item with its condition and effects, then have a recurring one queue it." );
         }
     }
     // Prevents crash from trying to spend charge with item removed
     if( !p->has_item( it ) ) {
         return 0;
     }
     return 1;
 }
References ACTIVATION, Creature::as_avatar(), Character::as_character(), Creature::as_npc(), context, debugmsg, eoc, get_talker_for(), visitable::has_item(), string_id< T >::str(), item::typeId(), u, and write_var_value().
Member Data Documentation
description
translation effect_on_conditons_actor::description
Definition at line 1175 of file iuse_actor.h.
eocs
std::vector<effect_on_condition_id> effect_on_conditons_actor::eocs
Definition at line 1174 of file iuse_actor.h.
menu_text
translation effect_on_conditons_actor::menu_text
Definition at line 1176 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp