Cataclysm DDA: mon_spellcasting_actor Class Reference
mon_spellcasting_actor Class Reference
#include <mattack_actors.h>
Public Member Functions
mon_spellcasting_actor ()=default
~mon_spellcasting_actor () override=default
void load_internal (const JsonObject &obj, const std::string &src) override
bool call (monster &) const override
std::unique_ptr< mattack_actor > clone () const override
Public Member Functions inherited from mattack_actor
mattack_actor (const mattack_id &new_id)
void load (const JsonObject &jo, const std::string &src)
virtual ~mattack_actor ()=default
Public Attributes
fake_spell spell_data
bool allow_no_target = false
Public Attributes inherited from mattack_actor
mattack_id id
bool was_loaded = false
int cooldown = 0
int attack_chance = 100
std::function< bool(dialogue &)> condition
bool has_condition = false
Additional Inherited Members
Protected Member Functions inherited from mattack_actor
mattack_actor ()=default
Detailed Description
Definition at line 60 of file mattack_actors.h.
Constructor & Destructor Documentation
mon_spellcasting_actor()
mon_spellcasting_actor::mon_spellcasting_actor () default
~mon_spellcasting_actor()
mon_spellcasting_actor::~mon_spellcasting_actor () override default
Member Function Documentation
call()
bool mon_spellcasting_actor::call (monster & mon) const override virtual
Implements mattack_actor.
Definition at line 269 of file mattack_actors.cpp.
 {
     if( !mon.can_act() ) {
         return false;
     }
     if( !mon.attack_target() && !allow_no_target ) {
         // this is an attack. there is no reason to attack if there isn't a real target.
         // Unless we don't need one
         return false;
     }
     if( has_condition ) {
         dialogue d( get_talker_for( &mon ),
                     allow_no_target ? nullptr : get_talker_for( mon.attack_target() ) );
         if( !condition( d ) ) {
             add_msg_debug( debugmode::DF_MATTACK, "Attack conditionals failed" );
             return false;
         }
     }
     const tripoint target = ( spell_data.self ||
                               allow_no_target ) ? mon.pos() : mon.attack_target()->pos();
     spell spell_instance = spell_data.get_spell( mon );
     spell_instance.set_message( spell_data.trigger_message );
     // Bail out if the target is out of range.
     if( !spell_data.self && rl_dist( mon.pos(), target ) > spell_instance.range( mon ) ) {
         return false;
     }
     std::string target_name;
     if( const Creature *target_monster = get_creature_tracker().creature_at( target ) ) {
         target_name = target_monster->disp_name();
     }
     add_msg_if_player_sees( target, spell_instance.message(), mon.disp_name(),
                             spell_instance.name(), target_name );
     avatar fake_player;
     mon.mod_moves( -spell_instance.casting_time( fake_player, true ) );
     spell_instance.cast_all_effects( mon, target );
     return true;
 }
References add_msg_debug, add_msg_if_player_sees(), allow_no_target, monster::attack_target(), monster::can_act(), spell::cast_all_effects(), spell::casting_time(), mattack_actor::condition, creature_tracker::creature_at(), debugmode::DF_MATTACK, monster::disp_name(), get_creature_tracker(), fake_spell::get_spell(), get_talker_for(), mattack_actor::has_condition, spell::message(), Creature::mod_moves(), spell::name(), Creature::pos(), spell::range(), rl_dist(), fake_spell::self, spell::set_message(), spell_data, and fake_spell::trigger_message.
clone()
std::unique_ptr< mattack_actor > mon_spellcasting_actor::clone () const override virtual
Implements mattack_actor.
Definition at line 246 of file mattack_actors.cpp.
 {
     return std::make_unique<mon_spellcasting_actor>( *this );
 }
load_internal()
void mon_spellcasting_actor::load_internal (const JsonObject & obj, const std::string & src) override virtual
Implements mattack_actor.
Definition at line 251 of file mattack_actors.cpp.
 {
     mandatory( obj, was_loaded, "spell_data", spell_data );
     translation monster_message;
     optional( obj, was_loaded, "monster_message", monster_message,
               //~ "<Monster Display name> cast <Spell Name> on <Target name>!"
               to_translation( "%1$s casts %2$s at %3$s!" ) );
     spell_data.trigger_message = monster_message;
     optional( obj, was_loaded, "attack_chance", attack_chance, 100 );
     optional( obj, was_loaded, "allow_no_target", allow_no_target, false );
     if( obj.has_member( "condition" ) ) {
         read_condition( obj, "condition", condition, false );
         has_condition = true;
     }
 }
References allow_no_target, mattack_actor::attack_chance, mattack_actor::condition, mattack_actor::has_condition, JsonObject::has_member(), mandatory, optional(), read_condition(), spell_data, to_translation(), fake_spell::trigger_message, and mattack_actor::was_loaded.
Member Data Documentation
allow_no_target
bool mon_spellcasting_actor::allow_no_target = false
Definition at line 65 of file mattack_actors.h.
Referenced by call(), and load_internal().
spell_data
fake_spell mon_spellcasting_actor::spell_data
Definition at line 63 of file mattack_actors.h.
Referenced by call(), and load_internal().
The documentation for this class was generated from the following files:
src/mattack_actors.h
src/mattack_actors.cpp