Cataclysm DDA: mapgen_value< Id > Class Template Reference
mapgen_value< Id > Class Template Reference
Classes
struct distribution_source
struct id_source
struct null_source
struct param_source
struct switch_source
struct value_source
Public Types
using StringId = to_string_id_t< Id >
using Id_unless_string = std::conditional_t< std::is_same_v< Id, std::string >, void_, Id >
Public Member Functions
mapgen_value ()
mapgen_value (const std::string &s)
mapgen_value (const Id_unless_string &id)
mapgen_value (const JsonValue &jv)
mapgen_value (const JsonObject &jo)
template<typename S >
void init_string (const S &s)
void init_object (const JsonObject &jo)
bool is_null () const
void check (const std::string &context, const mapgen_parameters &params) const
void check_consistent_with (const mapgen_value &other, const std::string &context) const
Id get (const mapgendata &dat) const
std::vector< StringId > all_possible_results (const mapgen_parameters &params) const
const std::string * get_name_if_parameter () const
void deserialize (const JsonValue &jsin)
Private Attributes
bool is_null_ = false
shared_ptr_fast< const value_source > source_
Detailed Description
template<typename Id>
class mapgen_value< Id >
Definition at line 1206 of file mapgen.cpp.
Member Typedef Documentation
Id_unless_string
template<typename Id > using mapgen_value< Id >::Id_unless_string = std::conditional_t<std::is_same_v<Id, std::string>, void_, Id>
Definition at line 1211 of file mapgen.cpp.
StringId
template<typename Id > using mapgen_value< Id >::StringId = to_string_id_t<Id>
Definition at line 1209 of file mapgen.cpp.
Constructor & Destructor Documentation
mapgen_value() [1/5]
template<typename Id > mapgen_value< Id >::mapgen_value () inline
Definition at line 1486 of file mapgen.cpp.
             : is_null_( true )
             , source_( make_shared_fast<null_source>() )
         {}
Referenced by mapgen_value< Id >::deserialize().
mapgen_value() [2/5]
template<typename Id > mapgen_value< Id >::mapgen_value (const std::string & s) inline explicit
Definition at line 1491 of file mapgen.cpp.
{
             init_string( s );
         }
References mapgen_value< Id >::init_string().
mapgen_value() [3/5]
template<typename Id > mapgen_value< Id >::mapgen_value (const Id_unless_string & id) inline explicit
Definition at line 1495 of file mapgen.cpp.
{
             init_string( id );
         }
References mapgen_value< Id >::init_string().
mapgen_value() [4/5]
template<typename Id > mapgen_value< Id >::mapgen_value (const JsonValue & jv) inline explicit
Definition at line 1499 of file mapgen.cpp.
{
             if( jv.test_string() ) {
                 init_string( jv.get_string() );
             } else {
                 init_object( jv.get_object() );
             }
         }
References JsonValue::get_object(), JsonValue::get_string(), mapgen_value< Id >::init_object(), mapgen_value< Id >::init_string(), and JsonValue::test_string().
mapgen_value() [5/5]
template<typename Id > mapgen_value< Id >::mapgen_value (const JsonObject & jo) inline explicit
Definition at line 1507 of file mapgen.cpp.
{
             init_object( jo );
         }
References mapgen_value< Id >::init_object().
Member Function Documentation
all_possible_results()
template<typename Id > std::vector<StringId> mapgen_value< Id >::all_possible_results (const mapgen_parameters & params) const inline
Definition at line 1544 of file mapgen.cpp.
{
             return source_->all_possible_results( params );
         }
References mapgen_value< Id >::source_.
Referenced by mapgen_palette::add().
check()
template<typename Id > void mapgen_value< Id >::check (const std::string & context, const mapgen_parameters & params) const inline
Definition at line 1534 of file mapgen.cpp.
{
             source_->check( context, params );
         }
References context, and mapgen_value< Id >::source_.
check_consistent_with()
template<typename Id > void mapgen_value< Id >::check_consistent_with (const mapgen_value< Id > & other, const std::string & context) const inline
Definition at line 1537 of file mapgen.cpp.
{
             source_->check_consistent_with( *other.source_, context );
         }
References context, other, and mapgen_value< Id >::source_.
deserialize()
template<typename Id > void mapgen_value< Id >::deserialize (const JsonValue & jsin) inline
Definition at line 1552 of file mapgen.cpp.
{
             if( jsin.test_object() ) {
                 *this = mapgen_value( jsin.get_object() );
             } else {
                 *this = mapgen_value( jsin.get_string() );
             }
         }
References JsonValue::get_object(), JsonValue::get_string(), mapgen_value< Id >::mapgen_value(), and JsonValue::test_object().
get()
template<typename Id > Id mapgen_value< Id >::get (const mapgendata & dat) const inline
Definition at line 1541 of file mapgen.cpp.
{
             return source_->get( dat );
         }
References mapgen_value< Id >::source_.
Referenced by jmapgen_nested::apply().
get_name_if_parameter()
template<typename Id > const std::string* mapgen_value< Id >::get_name_if_parameter () const inline
Definition at line 1548 of file mapgen.cpp.
{
             return source_->get_name_if_parameter();
         }
References mapgen_value< Id >::source_.
Referenced by mapgen_palette::add().
init_object()
template<typename Id > void mapgen_value< Id >::init_object (const JsonObject & jo) inline
Definition at line 1517 of file mapgen.cpp.
{
             if( jo.has_member( "param" ) ) {
                 source_ = make_shared_fast<param_source>( jo );
             } else if( jo.has_member( "distribution" ) ) {
                 source_ = make_shared_fast<distribution_source>( jo );
             } else if( jo.has_member( "switch" ) ) {
                 source_ = make_shared_fast<switch_source>( jo );
             } else {
                 jo.throw_error(
                     R"(Expected member "param", "distribution", or "switch" in mapgen object)" );
             }
         }
References JsonObject::has_member(), mapgen_value< Id >::source_, and JsonObject::throw_error().
Referenced by mapgen_value< Id >::mapgen_value().
init_string()
template<typename Id > template<typename S > void mapgen_value< Id >::init_string (const S & s) inline
Definition at line 1512 of file mapgen.cpp.
{
             source_ = make_shared_fast<id_source>( s );
             is_null_ = is_null_helper( s );
         }
References mapgen_value< Id >::is_null_, is_null_helper(), and mapgen_value< Id >::source_.
Referenced by mapgen_value< Id >::mapgen_value().
is_null()
template<typename Id > bool mapgen_value< Id >::is_null () const inline
Definition at line 1530 of file mapgen.cpp.
{
             return is_null_;
         }
References mapgen_value< Id >::is_null_.
Member Data Documentation
is_null_
template<typename Id > bool mapgen_value< Id >::is_null_ = false private
Definition at line 1560 of file mapgen.cpp.
Referenced by mapgen_value< Id >::init_string(), and mapgen_value< Id >::is_null().
source_
template<typename Id > shared_ptr_fast<const value_source> mapgen_value< Id >::source_ private
Definition at line 1561 of file mapgen.cpp.
Referenced by mapgen_value< Id >::all_possible_results(), mapgen_value< Id >::check(), mapgen_value< Id >::check_consistent_with(), mapgen_value< Id >::get(), mapgen_value< Id >::get_name_if_parameter(), mapgen_value< Id >::init_object(), and mapgen_value< Id >::init_string().
The documentation for this class was generated from the following file:
src/mapgen.cpp