Cataclysm DDA: tripoint_range< Tripoint >::point_generator Class Reference
tripoint_range< Tripoint >::point_generator Class Reference
Generates points in a rectangle.
Public Types
using value_type = Tripoint
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
using iterator_category = std::forward_iterator_tag
Public Member Functions
point_generator (const Tripoint &_p, const tripoint_range &_range)
point_generator & operator++ ()
const Tripoint & operator* () const
bool operator!= (const point_generator &other) const
bool operator== (const point_generator &other) const
Private Attributes
Tripoint p
const tripoint_range & range
Friends
class tripoint_range
Detailed Description
template<typename Tripoint>
class tripoint_range< Tripoint >::point_generator
Generates points in a rectangle.
Definition at line 20 of file map_iterator.h.
Member Typedef Documentation
difference_type
template<typename Tripoint > using tripoint_range< Tripoint >::point_generator::difference_type = std::ptrdiff_t
Definition at line 29 of file map_iterator.h.
iterator_category
template<typename Tripoint > using tripoint_range< Tripoint >::point_generator::iterator_category = std::forward_iterator_tag
Definition at line 32 of file map_iterator.h.
pointer
template<typename Tripoint > using tripoint_range< Tripoint >::point_generator::pointer = value_type *
Definition at line 30 of file map_iterator.h.
reference
template<typename Tripoint > using tripoint_range< Tripoint >::point_generator::reference = value_type &
Definition at line 31 of file map_iterator.h.
value_type
template<typename Tripoint > using tripoint_range< Tripoint >::point_generator::value_type = Tripoint
Definition at line 28 of file map_iterator.h.
Constructor & Destructor Documentation
point_generator()
template<typename Tripoint > tripoint_range< Tripoint >::point_generator::point_generator (const Tripoint & _p, const tripoint_range & _range) inline
Definition at line 34 of file map_iterator.h.
                     : p( _p ), range( _range ) {
                     // Make sure we start on a valid point
                     if( range.predicate && !range.predicate( p ) && p != range.endp ) {
                         operator++();
                     }
                 }
References tripoint_range< Tripoint >::endp, tripoint_range< Tripoint >::point_generator::operator++(), tripoint_range< Tripoint >::point_generator::p, tripoint_range< Tripoint >::predicate, and tripoint_range< Tripoint >::point_generator::range.
Member Function Documentation
operator!=()
template<typename Tripoint > bool tripoint_range< Tripoint >::point_generator::operator!= (const point_generator & other) const inline
Definition at line 68 of file map_iterator.h.
{
                     // Reverse coordinates order, because it will usually only be compared with endpoint
                     // which will always differ in Z, except for the very last comparison
                     // TODO: In C++17 this range should use a sentinel to
                     // optimise the comparison.
                     const Tripoint &pt = other.p;
                     return traits::z( p ) != traits::z( pt ) || p.xy() != pt.xy();
                 }
References other, tripoint_range< Tripoint >::point_generator::p, and point_traits< Point, typename >::z().
operator*()
template<typename Tripoint > const Tripoint& tripoint_range< Tripoint >::point_generator::operator* () const inline
Definition at line 64 of file map_iterator.h.
{
                     return p;
                 }
References tripoint_range< Tripoint >::point_generator::p.
operator++()
template<typename Tripoint > point_generator& tripoint_range< Tripoint >::point_generator::operator++ () inline
Definition at line 44 of file map_iterator.h.
{
                     do {
                         traits::x( p )++;
                         if( traits::x( p ) <= traits::x( range.maxp ) ) {
                             continue;
                         }
                         traits::y( p )++;
                         traits::x( p ) = traits::x( range.minp );
                         if( traits::y( p ) <= traits::y( range.maxp ) ) {
                             continue;
                         }
                         traits::z( p )++;
                         traits::y( p ) = traits::y( range.minp );
                     } while( range.predicate && !range.predicate( p ) && p != range.endp );
                     return *this;
                 }
References tripoint_range< Tripoint >::endp, tripoint_range< Tripoint >::maxp, tripoint_range< Tripoint >::minp, tripoint_range< Tripoint >::point_generator::p, tripoint_range< Tripoint >::predicate, tripoint_range< Tripoint >::point_generator::range, point_traits< Point, typename >::x(), point_traits< Point, typename >::y(), and point_traits< Point, typename >::z().
Referenced by tripoint_range< Tripoint >::point_generator::point_generator().
operator==()
template<typename Tripoint > bool tripoint_range< Tripoint >::point_generator::operator== (const point_generator & other) const inline
Definition at line 77 of file map_iterator.h.
{
                     return !( *this != other );
                 }
References other.
Friends And Related Function Documentation
tripoint_range
template<typename Tripoint > friend class tripoint_range friend
Definition at line 22 of file map_iterator.h.
Member Data Documentation
p
template<typename Tripoint > Tripoint tripoint_range< Tripoint >::point_generator::p private
Definition at line 24 of file map_iterator.h.
Referenced by tripoint_range< Tripoint >::point_generator::operator!=(), tripoint_range< Tripoint >::point_generator::operator*(), tripoint_range< Tripoint >::point_generator::operator++(), and tripoint_range< Tripoint >::point_generator::point_generator().
range
template<typename Tripoint > const tripoint_range& tripoint_range< Tripoint >::point_generator::range private
Definition at line 25 of file map_iterator.h.
Referenced by tripoint_range< Tripoint >::point_generator::operator++(), and tripoint_range< Tripoint >::point_generator::point_generator().
The documentation for this class was generated from the following file:
src/map_iterator.h