Cataclysm DDA: jmapgen_liquid_item Class Reference
jmapgen_liquid_item Class Reference
Place a specific liquid into the map.
Public Member Functions
jmapgen_liquid_item (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
jmapgen_int amount
mapgen_value< itype_id > liquid
jmapgen_int chance
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a specific liquid into the map.
"liquid": id of the liquid item (item should use charges) "amount": quantity of liquid placed (a value of -1 uses the default amount) "chance": chance of liquid being placed, see map::place_items
Definition at line 2186 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_liquid_item()
jmapgen_liquid_item::jmapgen_liquid_item (const JsonObject & jsi, const std::string_view) inline
Definition at line 2192 of file mapgen.cpp.
                                                                             :
             amount( jsi, "amount", -1, -1 )
             , liquid( jsi.get_member( "liquid" ) )
             , chance( jsi, "chance", 1, 1 ) {
         }
Member Function Documentation
apply()
void jmapgen_liquid_item::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2197 of file mapgen.cpp.
{
             if( one_in( chance.get() ) ) {
                 itype_id chosen_id = liquid.get( dat );
                 if( chosen_id.is_null() ) {
                     return;
                 }
                 // Itemgroups apply migrations when being loaded, but we need to migrate
                 // individual items here.
                 itype_id migrated = item_controller->migrate_id( chosen_id );
                 item newliquid( migrated, calendar::start_of_cataclysm );
                 if( amount.val > -1 ) {
                     if( amount.valmax > -1 ) {
                         newliquid.charges = amount.get();
                     } else {
                         newliquid.charges = amount.val;
                     }
                     if( migrated == itype_gasoline ||
                         migrated == itype_avgas ||
                         migrated == itype_diesel ||
                         migrated == itype_jp8 ) {
                         newliquid.charges *= 100;
                     }
                 }
                 if( newliquid.charges > 0 ) {
                     dat.m.add_item_or_charges(
                         tripoint( x.get(), y.get(), dat.zlevel() + z.get() ), newliquid );
                 }
             }
         }
References map::add_item_or_charges(), amount, chance, item::charges, jmapgen_int::get(), string_id< T >::is_null(), item_controller, itype_avgas, itype_diesel, itype_gasoline, itype_jp8, liquid, mapgendata::m, one_in(), calendar::start_of_cataclysm, tripoint, jmapgen_int::val, jmapgen_int::valmax, and mapgendata::zlevel().
check()
void jmapgen_liquid_item::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 2229 of file mapgen.cpp.
{
             liquid.check( oter_name, parameters );
         }
References liquid.
Member Data Documentation
amount
jmapgen_int jmapgen_liquid_item::amount
Definition at line 2189 of file mapgen.cpp.
Referenced by apply().
chance
jmapgen_int jmapgen_liquid_item::chance
Definition at line 2191 of file mapgen.cpp.
Referenced by apply().
liquid
mapgen_value<itype_id> jmapgen_liquid_item::liquid
Definition at line 2190 of file mapgen.cpp.
Referenced by apply(), and check().
The documentation for this class was generated from the following file:
src/mapgen.cpp