Cataclysm DDA: zone_type Class Reference
zone_type Class Reference
#include <clzones.h>
Public Member Functions
zone_type ()=default
zone_type (const translation &name, const translation &desc, const field_type_str_id &field)
std::string name () const
std::string desc () const
field_type_str_id get_field () const
void load (const JsonObject &jo, std::string_view)
bool is_valid () const
Static Public Member Functions
static void load_zones (const JsonObject &jo, const std::string &src)
static void reset ()
static const std::vector< zone_type > & get_all ()
All zone types in the game.
Public Attributes
zone_type_id id
std::vector< std::pair< zone_type_id, mod_id > > src
bool was_loaded = false
bool can_be_personal = false
bool hidden = false
Private Attributes
translation name_
translation desc_
field_type_str_id field_
Detailed Description
Definition at line 41 of file clzones.h.
Constructor & Destructor Documentation
zone_type() [1/2]
zone_type::zone_type () default
zone_type() [2/2]
zone_type::zone_type (const translation & name, const translation & desc, const field_type_str_id & field) inline explicit
Definition at line 54 of file clzones.h.
                                                              : name_( name ),
             desc_( desc ), field_( field ) {}
Member Function Documentation
desc()
std::string zone_type::desc () const
Definition at line 119 of file clzones.cpp.
 {
     return desc_.translated();
 }
References desc_, and translation::translated().
get_all()
const std::vector< zone_type > & zone_type::get_all () static
All zone types in the game.
Definition at line 146 of file clzones.cpp.
 {
     return zone_type_factory.get_all();
 }
References anonymous_namespace{clzones.cpp}::zone_type_factory.
Referenced by zone_data::refresh_display(), and zone_manager::zone_manager().
get_field()
field_type_str_id zone_type::get_field () const
Definition at line 124 of file clzones.cpp.
 {
     return field_;
 }
References field_.
is_valid()
bool zone_type::is_valid () const
load()
void zone_type::load (const JsonObject & jo, std::string_view)
Definition at line 161 of file clzones.cpp.
 {
     mandatory( jo, was_loaded, "name", name_ );
     mandatory( jo, was_loaded, "id", id );
     mandatory( jo, was_loaded, "display_field", field_ );
     optional( jo, was_loaded, "description", desc_, translation() );
     optional( jo, was_loaded, "can_be_personal", can_be_personal );
     optional( jo, was_loaded, "hidden", hidden );
 }
References can_be_personal, desc_, field_, hidden, mandatory, name_, optional(), and was_loaded.
load_zones()
void zone_type::load_zones (const JsonObject & jo, const std::string & src) static
Definition at line 151 of file clzones.cpp.
 {
     zone_type_factory.load( jo, src );
 }
References src, and anonymous_namespace{clzones.cpp}::zone_type_factory.
Referenced by DynamicDataLoader::initialize().
name()
std::string zone_type::name () const
Definition at line 114 of file clzones.cpp.
 {
     return name_.translated();
 }
References name_, and translation::translated().
reset()
void zone_type::reset () static
Definition at line 156 of file clzones.cpp.
 {
     zone_type_factory.reset();
 }
References anonymous_namespace{clzones.cpp}::zone_type_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
can_be_personal
bool zone_type::can_be_personal = false
Definition at line 62 of file clzones.h.
Referenced by load().
desc_
translation zone_type::desc_ private
Definition at line 45 of file clzones.h.
Referenced by desc(), and load().
field_
field_type_str_id zone_type::field_ private
Definition at line 46 of file clzones.h.
Referenced by get_field(), and load().
hidden
bool zone_type::hidden = false
Definition at line 63 of file clzones.h.
Referenced by load().
id
zone_type_id zone_type::id
Definition at line 49 of file clzones.h.
name_
translation zone_type::name_ private
Definition at line 44 of file clzones.h.
Referenced by load(), and name().
src
std::vector<std::pair<zone_type_id, mod_id> > zone_type::src
Definition at line 50 of file clzones.h.
Referenced by load_zones().
was_loaded
bool zone_type::was_loaded = false
Definition at line 51 of file clzones.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/clzones.h
src/clzones.cpp