Cataclysm DDA: ter_furn_migrations Class Reference
ter_furn_migrations Class Reference
#include <mapdata.h>
Static Public Member Functions
static void load (const JsonObject &jo)
Handler for loading "ter_furn_migrations" type of json object.
static void reset ()
Clears migration list.
static void check ()
Checks migrations.
Detailed Description
Definition at line 692 of file mapdata.h.
Member Function Documentation
check()
void ter_furn_migrations::check () static
Checks migrations.
Definition at line 4656 of file savegame_json.cpp.
 {
     auto check_to_ids_valid = []( const std::pair<ter_str_id, furn_str_id> &to_ids,
     const std::string & context ) {
         if( !to_ids.first.is_valid() ) {
             debugmsg( "ter_furn_migration from '%s' specifies invalid to_ter id '%s'", context,
                       to_ids.first.c_str() );
         }
         if( !to_ids.second.is_valid() ) {
             debugmsg( "ter_furn_migration from '%s' specifies invalid to_furn id '%s'", context,
                       to_ids.second.c_str() );
         }
     };
     for( const auto &migration : ter_migrations ) {
         check_to_ids_valid( migration.second, migration.first.c_str() );
     }
     for( const auto &migration : furn_migrations ) {
         check_to_ids_valid( migration.second, migration.first.c_str() );
     }
 }
References context, debugmsg, furn_migrations, and ter_migrations.
Referenced by DynamicDataLoader::check_consistency().
load()
void ter_furn_migrations::load (const JsonObject & jo) static
Handler for loading "ter_furn_migrations" type of json object.
Definition at line 4624 of file savegame_json.cpp.
 {
     //TODO: Add support for migrating to items?
     const bool is_ter_migration = jo.has_string( "from_ter" );
     const bool is_furn_migration = jo.has_string( "from_furn" );
     if( ( is_ter_migration && is_furn_migration ) || ( !is_ter_migration && !is_furn_migration ) ) {
         debugmsg( "Should specify one of from_ter/from_furn" );
         return;
     }
     ter_str_id to_ter = ter_str_id::NULL_ID();
     furn_str_id to_furn = furn_str_id::NULL_ID();
     if( is_ter_migration ) {
         ter_str_id from_ter;
         mandatory( jo, true, "from_ter", from_ter );
         mandatory( jo, true, "to_ter", to_ter );
         optional( jo, true, "to_furn", to_furn );
         ter_migrations.insert( std::make_pair( from_ter, std::make_pair( to_ter, to_furn ) ) );
     } else {
         furn_str_id from_furn;
         mandatory( jo, true, "from_furn", from_furn );
         optional( jo, true, "to_ter", to_ter );
         mandatory( jo, true, "to_furn", to_furn );
         furn_migrations.insert( std::make_pair( from_furn, std::make_pair( to_ter, to_furn ) ) );
     }
 }
References debugmsg, furn_migrations, JsonObject::has_string(), mandatory, string_id< furn_t >::NULL_ID(), string_id< ter_t >::NULL_ID(), optional(), and ter_migrations.
Referenced by DynamicDataLoader::initialize().
reset()
void ter_furn_migrations::reset () static
Clears migration list.
Definition at line 4650 of file savegame_json.cpp.
 {
     ter_migrations.clear();
     furn_migrations.clear();
 }
References furn_migrations, and ter_migrations.
Referenced by DynamicDataLoader::unload_data().
The documentation for this class was generated from the following files:
src/mapdata.h
src/savegame_json.cpp