Cataclysm DDA: overmap Class Reference
overmap Class Reference
#include <overmap.h>
Public Member Functions
overmap (const overmap &)=default
overmap (overmap &&)=default
overmap (const point_abs_om &p)
~overmap ()
overmap & operator= (const overmap &)=default
void populate (overmap_special_batch &enabled_specials)
Create content in the overmap.
void populate ()
const point_abs_om & pos () const
int get_urbanity () const
void save () const
tripoint_om_omt find_random_omt (const std::pair< std::string, ot_match_type > &target, std::optional< city > target_city=std::nullopt) const
tripoint_om_omt find_random_omt (const std::string &omt_base_type, ot_match_type match_type=ot_match_type::type, std::optional< city > target_city=std::nullopt) const
std::vector< point_abs_omt > find_terrain (std::string_view term, int zlevel) const
Return a vector containing the absolute coordinates of every matching terrain on the current z level of the current overmap.
void ter_set (const tripoint_om_omt &p, const oter_id &id)
const oter_id & ter (const tripoint_om_omt &p) const
const oter_id & ter_unsafe (const tripoint_om_omt &p) const
std::optional< mapgen_arguments > * mapgen_args (const tripoint_om_omt &)
std::string * join_used_at (const om_pos_dir &)
std::vector< oter_id > predecessors (const tripoint_om_omt &)
void set_seen (const tripoint_om_omt &p, bool val)
bool seen (const tripoint_om_omt &p) const
bool & explored (const tripoint_om_omt &p)
bool is_explored (const tripoint_om_omt &p) const
bool has_note (const tripoint_om_omt &p) const
bool is_marked_dangerous (const tripoint_om_omt &p) const
const std::string & note (const tripoint_om_omt &p) const
void add_note (const tripoint_om_omt &p, std::string message)
void delete_note (const tripoint_om_omt &p)
void mark_note_dangerous (const tripoint_om_omt &p, int radius, bool is_dangerous)
int note_danger_radius (const tripoint_om_omt &p) const
bool has_extra (const tripoint_om_omt &p) const
const map_extra_id & extra (const tripoint_om_omt &p) const
void add_extra (const tripoint_om_omt &p, const map_extra_id &id)
void add_extra_note (const tripoint_om_omt &p)
void delete_extra (const tripoint_om_omt &p)
const scent_trace & scent_at (const tripoint_abs_omt &loc) const
Getter for overmap scents.
void set_scent (const tripoint_abs_omt &loc, const scent_trace &new_scent)
Setter for overmap scents, stores the provided scent at the provided location.
std::vector< point_abs_omt > find_notes (int z, const std::string &text)
Return a vector containing the absolute coordinates of every matching note on the current z level of the current overmap.
std::vector< point_abs_omt > find_extras (int z, const std::string &text)
Return a vector containing the absolute coordinates of every matching map extra on the current z level of the current overmap.
bool is_omt_generated (const tripoint_om_omt &loc) const
Returns whether or not the location has been generated (e.g.
point_abs_omt global_base_point () const
Returns the (0, 0) corner of the overmap in the global coordinates.
const regional_settings & get_settings () const
void clear_mon_groups ()
void clear_overmap_special_placements ()
void clear_cities ()
void clear_connections_out ()
void place_special_forced (const overmap_special_id &special_id, const tripoint_om_omt &p, om_direction::type dir)
bool mongroup_check (const mongroup &candidate) const
Unit test enablers to check if a given mongroup is present.
bool monster_check (const std::pair< tripoint_om_sm, monster > &candidate) const
std::optional< basecamp * > find_camp (const point_abs_omt &p)
void insert_npc (const shared_ptr_fast< npc > &who)
Adds the npc to the contained list of npcs (npcs).
shared_ptr_fast< npc > erase_npc (const character_id &id)
Removes the npc and returns it (or returns nullptr if not found).
shared_ptr_fast< npc > find_npc (const character_id &id) const
shared_ptr_fast< npc > find_npc_by_unique_id (const std::string &id) const
const std::vector< shared_ptr_fast< npc > > & get_npcs () const
std::vector< shared_ptr_fast< npc > > get_npcs (const std::function< bool(const npc &)> &predicate) const
void unserialize (const cata_path &file_name, std::istream &fin)
void unserialize (const JsonObject &jsobj)
void unserialize_omap (const JsonValue &jsin, const cata_path &json_path)
void unserialize_view (const cata_path &file_name, std::istream &fin)
void unserialize_view (const JsonObject &jsobj)
void serialize (std::ostream &fout) const
void serialize_view (std::ostream &fout) const
void build_connection (const overmap_connection &connection, const pf::directed_path< point_om_omt > &path, int z, cube_direction initial_dir=cube_direction::last)
void build_connection (const point_om_omt &source, const point_om_omt &dest, int z, const overmap_connection &connection, bool must_be_unexplored, cube_direction initial_dir=cube_direction::last)
void connect_closest_points (const std::vector< point_om_omt > &points, int z, const overmap_connection &connection)
bool check_ot (const std::string &otype, ot_match_type match_type, const tripoint_om_omt &p) const
bool check_overmap_special_type (const overmap_special_id &id, const tripoint_om_omt &location) const
std::optional< overmap_special_id > overmap_special_at (const tripoint_om_omt &p) const
void chip_rock (const tripoint_om_omt &p)
void polish_river ()
void good_river (const tripoint_om_omt &p)
om_direction::type random_special_rotation (const overmap_special &special, const tripoint_om_omt &p, bool must_be_unexplored) const
bool can_place_special (const overmap_special &special, const tripoint_om_omt &p, om_direction::type dir, bool must_be_unexplored) const
std::vector< tripoint_om_omt > place_special (const overmap_special &special, const tripoint_om_omt &p, om_direction::type dir, const city &cit, bool must_be_unexplored, bool force)
void migrate_oter_ids (const std::unordered_map< tripoint_om_omt, std::string > &points)
oter_id get_or_migrate_oter (const std::string &oterid)
Static Public Member Functions
static bool inbounds (const tripoint_om_omt &p, int clearance=0)
static bool inbounds (const point_om_omt &p, int clearance=0)
static void load_oter_id_migration (const JsonObject &jo)
static void reset_oter_id_migrations ()
static bool is_oter_id_obsolete (const std::string &oterid)
Public Attributes
std::vector< radio_tower > radios
std::map< int, om_vehicle > vehicles
std::vector< basecamp > camps
std::vector< city > cities
std::map< string_id< overmap_connection >, std::vector< tripoint_om_omt > > connections_out
std::unordered_multimap< tripoint_om_sm, monster > monster_map
When monsters despawn during map-shifting they will be added here.
Static Public Attributes
static constexpr tripoint_abs_omt invalid_tripoint { tripoint_min }
Dummy value, used to indicate that a point returned by a function is invalid.
Private Member Functions
oter_id get_default_terrain (int z) const
void init_layers ()
void open (overmap_special_batch &enabled_specials)
void generate (const overmap *north, const overmap *east, const overmap *south, const overmap *west, overmap_special_batch &enabled_specials)
bool generate_sub (int z)
bool generate_over (int z)
void generate_bridgeheads (const std::vector< point_om_omt > &bridge_points, oter_type_str_id bridge_type, const std::string &bridgehead_ground, const std::string &bridgehead_ramp)
const city & get_nearest_city (const tripoint_om_omt &p) const
void signal_hordes (const tripoint_rel_sm &p, int sig_power)
void process_mongroups ()
void move_hordes ()
void signal_nemesis (const tripoint_abs_sm &)
void move_nemesis ()
void place_nemesis (const tripoint_abs_omt &)
bool remove_nemesis ()
float calculate_ocean_gradient (const point_om_omt &p, point_abs_om this_omt)
void place_river (const point_om_omt &pa, const point_om_omt &pb)
void place_forests ()
void place_lakes ()
void place_oceans ()
void place_rivers (const overmap *north, const overmap *east, const overmap *south, const overmap *west)
void place_swamps ()
void place_forest_trails ()
void place_forest_trailheads ()
void place_roads (const overmap *north, const overmap *east, const overmap *south, const overmap *west)
void place_railroads (const overmap *north, const overmap *east, const overmap *south, const overmap *west)
void populate_connections_out_from_neighbors (const overmap *north, const overmap *east, const overmap *south, const overmap *west)
overmap_special_id pick_random_building_to_place (int town_dist, int town_size) const
void calculate_urbanity ()
void calculate_forestosity ()
void place_cities ()
void place_building (const tripoint_om_omt &p, om_direction::type dir, const city &town)
void build_city_street (const overmap_connection &connection, const point_om_omt &p, int cs, om_direction::type dir, const city &town, int block_width=2)
bool build_lab (const tripoint_om_omt &p, int s, std::vector< point_om_omt > *lab_train_points, const std::string &prefix, int train_odds)
bool build_slimepit (const tripoint_om_omt &origin, int s)
void place_ravines ()
pf::directed_path< point_om_omt > lay_out_connection (const overmap_connection &connection, const point_om_omt &source, const point_om_omt &dest, int z, bool must_be_unexplored) const
pf::directed_path< point_om_omt > lay_out_street (const overmap_connection &connection, const point_om_omt &source, om_direction::type dir, size_t len) const
void place_specials (overmap_special_batch &enabled_specials)
Iterate over the overmap and place the quota of specials.
void place_specials_pass (overmap_special_batch &enabled_specials, om_special_sectors &sectors, bool place_optional, bool must_be_unexplored)
Walk over the overmap and attempt to place specials.
bool place_special_attempt (overmap_special_batch &enabled_specials, const point_om_omt &sector, int sector_width, bool place_optional, bool must_be_unexplored)
Attempts to place specials within a sector.
void place_mongroups ()
void place_radios ()
void add_mon_group (const mongroup &group)
void add_mon_group (const mongroup &group, int radius)
void spawn_mon_group (const mongroup &group, int radius)
void load_monster_groups (const JsonArray &jsin)
void load_legacy_monstergroups (const JsonArray &jsin)
void save_monster_groups (JsonOut &jo) const
Private Attributes
std::multimap< tripoint_om_sm, mongroup > zg
std::vector< shared_ptr_fast< npc > > npcs
bool nullbool = false
point_abs_om loc
std::array< map_layer, OVERMAP_LAYERS > layer
std::unordered_map< tripoint_abs_omt, scent_trace > scents
std::unordered_map< tripoint_om_omt, overmap_special_id > overmap_special_placements
std::unordered_set< tripoint_om_omt > safe_at_worldgen
std::unordered_map< tripoint_om_omt, std::vector< oter_id > > predecessors_
cata::colony< std::optional< mapgen_arguments > > mapgen_arg_storage
std::unordered_map< tripoint_om_omt, std::optional< mapgen_arguments > * > mapgen_args_index
std::unordered_map< om_pos_dir, std::string > joins_used
const regional_settings * settings
int urbanity = 0
float forest_size_adjust = 0.0f
float forestosity = 0.0f
Friends
class overmapbuffer
Detailed Description
Definition at line 184 of file overmap.h.
Constructor & Destructor Documentation
overmap() [1/3]
overmap::overmap (const overmap &) default
overmap() [2/3]
overmap::overmap (overmap &&) default
overmap() [3/3]
overmap::overmap (const point_abs_om & p) explicit
Definition at line 2846 of file overmap.cpp.
                                         : loc( p )
 {
     const std::string rsettings_id = get_option<std::string>( "DEFAULT_REGION" );
     t_regional_settings_map_citr rsit = region_settings_map.find( rsettings_id );
     if( rsit == region_settings_map.end() ) {
         debugmsg( "overmap%s: can't find region '%s'", p.to_string(),
                   rsettings_id.c_str() ); // gonna die now =[
     }
     settings = &rsit->second;
     init_layers();
 }
References debugmsg, init_layers(), region_settings_map, settings, and coords::coord_point_base< Point >::to_string().
~overmap()
overmap::~overmap () default
Member Function Documentation
add_extra()
void overmap::add_extra (const tripoint_om_omt & p, const map_extra_id & id)
Definition at line 3255 of file overmap.cpp.
 {
     if( p.z() < -OVERMAP_DEPTH || p.z() > OVERMAP_HEIGHT ) {
         debugmsg( "Attempting to add not to overmap for blank layer %d", p.z() );
         return;
     }
     auto &extras = layer[p.z() + OVERMAP_DEPTH].extras;
     const auto it = std::find_if( begin( extras ),
     end( extras ), [&]( const om_map_extra & n ) {
         return n.p == p.xy();
     } );
     if( it == std::end( extras ) ) {
         extras.emplace_back( om_map_extra{ id, p.xy() } );
         add_extra_note( p );
     } else if( !id.is_null() ) {
         it->id = id;
         add_extra_note( p );
     } else {
         extras.erase( it );
     }
 }
References add_extra_note(), debugmsg, keycode::end, anonymous_namespace{map_extras.cpp}::extras, base_camps::id, layer, OVERMAP_DEPTH, OVERMAP_HEIGHT, om_map_extra::p, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by overmapbuffer::add_extra(), and delete_extra().
add_extra_note()
void overmap::add_extra_note (const tripoint_om_omt & p)
Definition at line 3279 of file overmap.cpp.
 {
     if( !seen( p ) ) {
         return;
     }
     const std::vector<om_map_extra> &layer_extras = layer[p.z() + OVERMAP_DEPTH].extras;
     auto extrait = std::find_if( layer_extras.begin(),
     layer_extras.end(), [&p]( const om_map_extra & extra ) {
         return extra.p == p.xy();
     } );
     if( extrait == layer_extras.end() ) {
         return;
     }
     const map_extra_id &extra = extrait->id;
     auto_notes::auto_note_settings &auto_note_settings = get_auto_notes_settings();
     // The player has discovered a map extra of this type.
     auto_note_settings.set_discovered( extra );
     if( get_option<bool>( "AUTO_NOTES" ) && get_option<bool>( "AUTO_NOTES_MAP_EXTRAS" ) ) {
         // Only place note if the user has not disabled it via the auto note manager
         if( !auto_note_settings.has_auto_note_enabled( extra, true ) ) {
             return;
         }
         const std::optional<auto_notes::custom_symbol> &symbol =
             auto_note_settings.get_custom_symbol( extra );
         const std::string note_symbol = symbol ? ( *symbol ).get_symbol_string() : extra->get_symbol();
         const nc_color note_color = symbol ? ( *symbol ).get_color() : extra->color;
         const std::string mx_note =
             string_format( "%s:%s;<color_yellow>%s</color>: <color_white>%s</color>",
                            note_symbol,
                            get_note_string_from_color( note_color ),
                            extra->name(),
                            extra->description() );
         add_note( p, mx_note );
     }
 }
References add_note(), map_extra::color, map_extra::description(), extra(), get_auto_notes_settings(), auto_notes::auto_note_settings::get_custom_symbol(), get_note_string_from_color(), map_extra::get_symbol(), auto_notes::auto_note_settings::has_auto_note_enabled(), map_extra::id, layer, map_extra::name(), OVERMAP_DEPTH, seen(), auto_notes::auto_note_settings::set_discovered(), string_format(), symbol(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by add_extra(), and set_seen().
add_mon_group() [1/2]
void overmap::add_mon_group (const mongroup & group) private
Definition at line 7243 of file overmap.cpp.
 {
     zg.emplace( group.rel_pos(), group );
 }
References zg.
Referenced by add_mon_group(), load_legacy_monstergroups(), load_monster_groups(), move_hordes(), place_mongroups(), place_nemesis(), and spawn_mon_group().
add_mon_group() [2/2]
void overmap::add_mon_group (const mongroup & group, int radius) private
Definition at line 7248 of file overmap.cpp.
 {
     // We only spread the groups out when radius is greater than 1
     if( radius <= 1 ) {
         add_mon_group( group );
         return;
     }
     const int rad = std::max<int>( 0, radius );
     const double total_area = rad * rad * M_PI + 1;
     const double pop = std::max<int>( 0, group.population );
     for( int x = -rad; x <= rad; x++ ) {
         for( int y = -rad; y <= rad; y++ ) {
             const int dist = trig_dist( point( x, y ), point_zero );
             if( dist > rad ) {
                 continue;
             }
             // Population on a single submap, *not* a integer
             double pop_here;
             if( rad == 0 ) {
                 pop_here = pop;
             } else {
                 // This computation is delicate, be careful and see
                 // https://github.com/CleverRaven/Cataclysm-DDA/issues/26941
                 pop_here = ( static_cast<double>( rad - dist ) / rad ) * pop / total_area;
             }
             if( pop_here > pop || pop_here < 0 ) {
                 DebugLog( D_ERROR, D_GAME ) << group.type.str() << ": invalid population here: " << pop_here;
             }
             int p = std::max( 0, static_cast<int>( std::floor( pop_here ) ) );
             if( pop_here - p != 0 ) {
                 // in case the population is something like 0.2, randomly add a
                 // single population unit, this *should* on average give the correct
                 // total population.
                 const int mod = static_cast<int>( 10000.0 * ( pop_here - p ) );
                 if( x_in_y( mod, 10000 ) ) {
                     p++;
                 }
             }
             if( p == 0 ) {
                 continue;
             }
             // Exact copy to keep all important values, only change what's needed
             // for a single-submap group.
             mongroup tmp( group );
             tmp.abs_pos += point( x, y );
             tmp.population = p;
             // This *can* create groups outside of the area of this overmap.
             // As this function is called during generating the overmap, the
             // neighboring overmaps might not have been generated and one can't access
             // them through the overmapbuffer as this would trigger generating them.
             // This would in turn to lead to a call to this function again.
             // To avoid this, the overmapbuffer checks the monster groups when loading
             // an overmap and moves groups with out-of-bounds position to another overmap.
             add_mon_group( tmp );
         }
     }
 }
References mongroup::abs_pos, add_mon_group(), D_ERROR, D_GAME, DebugLog(), floor(), M_PI, max(), point, point_zero, mongroup::population, trig_dist(), and x_in_y().
add_note()
void overmap::add_note (const tripoint_om_omt & p, std::string message)
Definition at line 3161 of file overmap.cpp.
 {
     if( p.z() < -OVERMAP_DEPTH || p.z() > OVERMAP_HEIGHT ) {
         debugmsg( "Attempting to add not to overmap for blank layer %d", p.z() );
         return;
     }
     auto &notes = layer[p.z() + OVERMAP_DEPTH].notes;
     const auto it = std::find_if( begin( notes ), end( notes ), [&]( const om_note & n ) {
         return n.p == p.xy();
     } );
     if( it == std::end( notes ) ) {
         notes.emplace_back( om_note{ std::move( message ), p.xy() } );
     } else if( !message.empty() ) {
         it->text = std::move( message );
     } else {
         notes.erase( it );
     }
 }
References debugmsg, keycode::end, layer, mapgen_defer::message, OVERMAP_DEPTH, OVERMAP_HEIGHT, om_note::p, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by add_extra_note(), overmapbuffer::add_note(), and delete_note().
build_city_street()
void overmap::build_city_street (const overmap_connection & connection, const point_om_omt & p, int cs, om_direction::type dir, const city & town, int block_width = 2) private
Definition at line 5611 of file overmap.cpp.
 {
     int c = cs;
     int croad = cs;
     if( dir == om_direction::type::invalid ) {
         debugmsg( "Invalid road direction." );
         return;
     }
     const pf::directed_path<point_om_omt> street_path = lay_out_street( connection, p, dir, cs + 1 );
     if( street_path.nodes.size() <= 1 ) {
         return; // Don't bother.
     }
     // Build the actual street.
     build_connection( connection, street_path, 0 );
     // Grow in the stated direction, sprouting off sub-roads and placing buildings as we go.
     const auto from = std::next( street_path.nodes.begin() );
     const auto to = street_path.nodes.end();
     //Alternate wide and thin blocks
     int new_width = block_width == 2 ? rng( 3, 5 ) : 2;
     for( auto iter = from; iter != to; ++iter ) {
         --c;
         const tripoint_om_omt rp( iter->pos, 0 );
         if( c >= 2 && c < croad - block_width ) {
             croad = c;
             int left = cs - rng( 1, 3 );
             int right = cs - rng( 1, 3 );
             //Remove 1 length road nubs
             if( left == 1 ) {
                 left++;
             }
             if( right == 1 ) {
                 right++;
             }
             build_city_street( connection, iter->pos, left, om_direction::turn_left( dir ),
                                town, new_width );
             build_city_street( connection, iter->pos, right, om_direction::turn_right( dir ),
                                town, new_width );
             const oter_id &oter = ter( rp );
             // TODO: Get rid of the hardcoded terrain ids.
             if( one_in( 2 ) && oter->get_line() == 15 && oter->type_is( oter_type_id( "road" ) ) ) {
                 ter_set( rp, oter_road_nesw_manhole.id() );
             }
         }
         if( !one_in( BUILDINGCHANCE ) ) {
             place_building( rp, om_direction::turn_left( dir ), town );
         }
         if( !one_in( BUILDINGCHANCE ) ) {
             place_building( rp, om_direction::turn_right( dir ), town );
         }
     }
     // If we're big, make a right turn at the edge of town.
     // Seems to make little neighborhoods.
     cs -= rng( 1, 3 );
     if( cs >= 2 && c == 0 ) {
         const auto &last_node = street_path.nodes.back();
         const om_direction::type rnd_dir = om_direction::turn_random( dir );
         build_city_street( connection, last_node.pos, cs, rnd_dir, town );
         if( one_in( 5 ) ) {
             build_city_street( connection, last_node.pos, cs, om_direction::opposite( rnd_dir ),
                                town, new_width );
         }
     }
 }
References build_connection(), BUILDINGCHANCE, c, debugmsg, oter_t::get_line(), string_id< T >::id(), om_direction::invalid, lay_out_street(), left, pf::directed_path< Point >::nodes, one_in(), om_direction::opposite(), oter_road_nesw_manhole, place_building(), right, rng(), ter(), ter_set(), om_direction::turn_left(), om_direction::turn_random(), om_direction::turn_right(), and oter_t::type_is().
Referenced by place_cities().
build_connection() [1/2]
void overmap::build_connection (const overmap_connection & connection, const pf::directed_path< point_om_omt > & path, int z, cube_direction initial_dir = cube_direction::last)
Definition at line 6087 of file overmap.cpp.
 {
     if( path.nodes.empty() ) {
         return;
     }
     om_direction::type prev_dir =
         om_direction::from_cube( initial_dir, "Up and down connections not yet supported" );
     const pf::directed_node<point_om_omt> start = path.nodes.front();
     const pf::directed_node<point_om_omt> end = path.nodes.back();
     for( const auto &node : path.nodes ) {
         const tripoint_om_omt pos( node.pos, z );
         const oter_id &ter_id = ter( pos );
         const om_direction::type new_dir = node.dir;
         const overmap_connection::subtype *subtype = connection.pick_subtype_for( ter_id );
         if( !subtype ) {
             debugmsg( "No suitable subtype of connection \"%s\" found for \"%s\".", connection.id.c_str(),
                       ter_id.id().c_str() );
             return;
         }
         if( subtype->terrain->is_linear() ) {
             size_t new_line = connection.has( ter_id ) ? ter_id->get_line() : 0;
             if( new_dir != om_direction::type::invalid ) {
                 new_line = om_lines::set_segment( new_line, new_dir );
             }
             if( prev_dir != om_direction::type::invalid ) {
                 new_line = om_lines::set_segment( new_line, om_direction::opposite( prev_dir ) );
             }
             for( const om_direction::type dir : om_direction::all ) {
                 const tripoint_om_omt np( pos + om_direction::displace( dir ) );
                 if( inbounds( np ) ) {
                     const oter_id &near_id = ter( np );
                     if( connection.has( near_id ) ) {
                         if( near_id->is_linear() ) {
                             const size_t near_line = near_id->get_line();
                             if( om_lines::is_straight( near_line ) || om_lines::has_segment( near_line, new_dir ) ) {
                                 // Mutual connection.
                                 const size_t new_near_line = om_lines::set_segment( near_line, om_direction::opposite( dir ) );
                                 ter_set( np, near_id->get_type_id()->get_linear( new_near_line ) );
                                 new_line = om_lines::set_segment( new_line, dir );
                             }
                         } else if( near_id->is_rotatable() && om_direction::are_parallel( dir, near_id->get_dir() ) ) {
                             new_line = om_lines::set_segment( new_line, dir );
                         }
                     }
                 } else if( pos.xy() == start.pos || pos.xy() == end.pos ) {
                     // Only automatically connect to out of bounds locations if we're the start or end of this path.
                     new_line = om_lines::set_segment( new_line, dir );
                     // Add this connection point to our connections out.
                     std::vector<tripoint_om_omt> &outs = connections_out[connection.id];
                     const auto existing_out = std::find_if( outs.begin(),
                     outs.end(), [pos]( const tripoint_om_omt & c ) {
                         return c == pos;
                     } );
                     if( existing_out == outs.end() ) {
                         outs.emplace_back( pos );
                     }
                 }
             }
             if( new_line == om_lines::invalid ) {
                 debugmsg( "Invalid path for connection \"%s\".", connection.id.c_str() );
                 return;
             }
             ter_set( pos, subtype->terrain->get_linear( new_line ) );
         } else if( new_dir != om_direction::type::invalid ) {
             ter_set( pos, subtype->terrain->get_rotated( new_dir ) );
         }
         prev_dir = new_dir;
     }
 }
References om_direction::all, om_direction::are_parallel(), c, string_id< T >::c_str(), connections_out, debugmsg, om_direction::displace(), keycode::end, om_direction::from_cube(), oter_t::get_dir(), oter_t::get_line(), oter_type_t::get_linear(), oter_t::get_type_id(), overmap_connection::has(), om_lines::has_segment(), int_id< T >::id(), overmap_connection::id, inbounds(), om_direction::invalid, om_lines::invalid, oter_t::is_linear(), oter_t::is_rotatable(), om_lines::is_straight(), pf::directed_path< Point >::nodes, om_direction::opposite(), overmap_connection::pick_subtype_for(), pos(), pf::directed_node< Point >::pos, om_lines::set_segment(), subtype, ter(), ter_set(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by build_city_street(), build_connection(), and connect_closest_points().
build_connection() [2/2]
void overmap::build_connection (const point_om_omt & source, const point_om_omt & dest, int z, const overmap_connection & connection, bool must_be_unexplored, cube_direction initial_dir = cube_direction::last)
Definition at line 6174 of file overmap.cpp.
 {
     build_connection(
         connection, lay_out_connection( connection, source, dest, z, must_be_unexplored ),
         z, initial_dir );
 }
References build_connection(), and lay_out_connection().
build_lab()
bool overmap::build_lab (const tripoint_om_omt & p, int s, std::vector< point_om_omt > * lab_train_points, const std::string & prefix, int train_odds) private
Definition at line 5690 of file overmap.cpp.
 {
     std::vector<tripoint_om_omt> generated_lab;
     const oter_id labt( prefix + "lab" );
     const oter_id labt_stairs( labt.id().str() + "_stairs" );
     const oter_id labt_core( labt.id().str() + "_core" );
     const oter_id labt_finale( labt.id().str() + "_finale" );
     const oter_id labt_ants( "ants_lab" );
     const oter_id labt_ants_stairs( "ants_lab_stairs" );
     ter_set( p, labt );
     generated_lab.push_back( p );
     // maintain a list of potential new lab maps
     // grows outwards from previously placed lab maps
     std::set<tripoint_om_omt> candidates;
     candidates.insert( { p + point_north, p + point_east, p + point_south, p + point_west } );
     while( !candidates.empty() ) {
         const tripoint_om_omt cand = *candidates.begin();
         candidates.erase( candidates.begin() );
         if( !inbounds( cand ) ) {
             continue;
         }
         const int dist = manhattan_dist( p.xy(), cand.xy() );
         if( dist <= s * 2 ) { // increase radius to compensate for sparser new algorithm
             int dist_increment = s > 3 ? 3 : 2; // Determines at what distance the odds of placement decreases
             if( one_in( dist / dist_increment + 1 ) ) { // odds diminish farther away from the stairs
                 // make an ants lab if it's a basic lab and ants were there before.
                 if( prefix.empty() && check_ot( "ants", ot_match_type::type, cand ) ) {
                     // skip over a queen's chamber.
                     if( ter( cand )->get_type_id() != oter_type_ants_queen ) {
                         ter_set( cand, labt_ants );
                     }
                 } else {
                     ter_set( cand, labt );
                 }
                 generated_lab.push_back( cand );
                 // add new candidates, don't backtrack
                 for( const point &offset : four_adjacent_offsets ) {
                     const tripoint_om_omt new_cand = cand + offset;
                     const int new_dist = manhattan_dist( p.xy(), new_cand.xy() );
                     if( ter( new_cand ) != labt && new_dist > dist ) {
                         candidates.insert( new_cand );
                     }
                 }
             }
         }
     }
     bool generate_stairs = true;
     for( tripoint_om_omt &elem : generated_lab ) {
         // Use a check for "_stairs" to catch the hidden_lab_stairs tiles.
         if( is_ot_match( "_stairs", ter( elem + tripoint_above ), ot_match_type::contains ) ) {
             generate_stairs = false;
         }
     }
     if( generate_stairs && !generated_lab.empty() ) {
         std::shuffle( generated_lab.begin(), generated_lab.end(), rng_get_engine() );
         // we want a spot where labs are above, but we'll settle for the last element if necessary.
         tripoint_om_omt lab_pos;
         for( tripoint_om_omt elem : generated_lab ) {
             lab_pos = elem;
             if( ter( lab_pos + tripoint_above ) == labt ) {
                 break;
             }
         }
         ter_set( lab_pos + tripoint_above, labt_stairs );
     }
     ter_set( p, labt_core );
     int numstairs = 0;
     if( s > 0 ) { // Build stairs going down
         while( !one_in( 6 ) ) {
             tripoint_om_omt stair;
             int tries = 0;
             do {
                 stair = p + point( rng( -s, s ), rng( -s, s ) );
                 tries++;
             } while( ( ter( stair ) != labt && ter( stair ) != labt_ants ) && tries < 15 );
             if( tries < 15 ) {
                 if( ter( stair ) == labt_ants ) {
                     ter_set( stair, labt_ants_stairs );
                 } else {
                     ter_set( stair, labt_stairs );
                 }
                 numstairs++;
             }
         }
     }
     // We need a finale on the bottom of labs.  Central labs have a chance of additional finales.
     if( numstairs == 0 || ( prefix == "central_" && one_in( -p.z() - 1 ) ) ) {
         tripoint_om_omt finale;
         int tries = 0;
         do {
             finale = p + point( rng( -s, s ), rng( -s, s ) );
             tries++;
         } while( tries < 15 && ter( finale ) != labt && ter( finale ) != labt_core );
         ter_set( finale, labt_finale );
     }
     if( train_odds > 0 && one_in( train_odds ) ) {
         tripoint_om_omt train;
         int tries = 0;
         int adjacent_labs;
         do {
             train = p + point( rng( -s * 1.5 - 1, s * 1.5 + 1 ), rng( -s * 1.5 - 1, s * 1.5 + 1 ) );
             tries++;
             adjacent_labs = 0;
             for( const point &offset : four_adjacent_offsets ) {
                 if( is_ot_match( "lab", ter( train + offset ), ot_match_type::contains ) &&
                     !is_ot_match( "lab_subway", ter( train + offset ), ot_match_type::contains ) ) {
                     ++adjacent_labs;
                 }
             }
         } while( tries < 50 && (
                      ter( train ) == labt ||
                      ter( train ) == labt_stairs ||
                      ter( train ) == labt_finale ||
                      adjacent_labs != 1 ) );
         if( tries < 50 ) {
             lab_train_points->push_back( train.xy() ); // possible train depot
             // next is rail connection
             for( const point &offset : four_adjacent_offsets ) {
                 if( is_ot_match( "lab", ter( train + offset ), ot_match_type::contains ) &&
                     !is_ot_match( "lab_subway", ter( train + offset ), ot_match_type::contains ) ) {
                     lab_train_points->push_back( train.xy() - offset );
                     break;
                 }
             }
         }
     }
     // 4th story of labs is a candidate for lab escape, as long as there's no train or finale.
     if( prefix.empty() && p.z() == -4 && train_odds == 0 && numstairs > 0 ) {
         tripoint_om_omt cell;
         int tries = 0;
         int adjacent_labs = 0;
         // Find a space bordering just one lab to the south.
         do {
             cell = p + point( rng( -s * 1.5 - 1, s * 1.5 + 1 ), rng( -s * 1.5 - 1, s * 1.5 + 1 ) );
             tries++;
             adjacent_labs = 0;
             for( const point &offset : four_adjacent_offsets ) {
                 if( is_ot_match( "lab", ter( cell + offset ), ot_match_type::contains ) &&
                     !is_ot_match( "lab_subway", ter( cell + offset ), ot_match_type::contains ) ) {
                     ++adjacent_labs;
                 }
             }
         } while( tries < 50 && (
                      ter( cell ) == labt_stairs ||
                      ter( cell ) == labt_finale ||
                      ter( cell + point_south ) != labt ||
                      adjacent_labs != 1 ) );
         if( tries < 50 ) {
             ter_set( cell, oter_lab_escape_cells.id() );
             ter_set( cell + point_south, oter_lab_escape_entrance.id() );
         }
     }
     return numstairs > 0;
 }
References check_ot(), contains, four_adjacent_offsets, int_id< T >::id(), string_id< T >::id(), inbounds(), is_ot_match(), manhattan_dist(), one_in(), oter_lab_escape_cells, oter_lab_escape_entrance, oter_type_ants_queen, point, point_east, point_north, point_south, point_west, prefix, rng(), rng_get_engine(), string_id< T >::str(), ter(), ter_set(), tripoint_above, type, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by generate_sub().
build_slimepit()
bool overmap::build_slimepit (const tripoint_om_omt & origin, int s) private
Definition at line 5860 of file overmap.cpp.
 {
     const oter_id slimepit_down( "slimepit_down" );
     const oter_id slimepit( "slimepit" );
     bool requires_sub = false;
     for( auto p : points_in_radius( origin, s + origin.z() + 1, 0 ) ) {
         int dist = square_dist( origin.xy(), p.xy() );
         if( one_in( 2 * dist ) ) {
             chip_rock( p );
             if( one_in( 8 ) && origin.z() > -OVERMAP_DEPTH ) {
                 ter_set( p, slimepit_down );
                 requires_sub = true;
             } else {
                 ter_set( p, slimepit );
             }
         }
     }
     return requires_sub;
 }
References chip_rock(), one_in(), OVERMAP_DEPTH, points_in_radius(), square_dist(), and ter_set().
Referenced by generate_sub().
calculate_forestosity()
void overmap::calculate_forestosity () private
Definition at line 5342 of file overmap.cpp.
 {
     float northern_forest_increase = get_option<float>( "OVERMAP_FOREST_INCREASE_NORTH" );
     float eastern_forest_increase = get_option<float>( "OVERMAP_FOREST_INCREASE_EAST" );
     float western_forest_increase = get_option<float>( "OVERMAP_FOREST_INCREASE_WEST" );
     float southern_forest_increase = get_option<float>( "OVERMAP_FOREST_INCREASE_SOUTH" );
     const point_abs_om this_om = pos();
     if( western_forest_increase != 0 && this_om.x() < 0 ) {
         forest_size_adjust -= this_om.x() * western_forest_increase;
     }
     if( northern_forest_increase != 0 && this_om.y() < 0 ) {
         forest_size_adjust -= this_om.y() * northern_forest_increase;
     }
     if( eastern_forest_increase != 0 && this_om.x() > 0 ) {
         forest_size_adjust += this_om.x() * eastern_forest_increase;
     }
     if( southern_forest_increase != 0 && this_om.y() > 0 ) {
         forest_size_adjust += this_om.y() * southern_forest_increase;
     }
     forestosity = forest_size_adjust * 25.0f;
     //debugmsg( "forestosity = %1.2f at OM %i, %i", forestosity, this_om.x(), this_om.y() );
     // make sure forest size never totally overwhelms the map
     forest_size_adjust = std::min( forest_size_adjust,
                                    get_option<float>( "OVERMAP_FOREST_LIMIT" ) - static_cast<float>
                                    ( settings->overmap_forest.noise_threshold_forest ) );
 }
References forest_size_adjust, forestosity, min(), overmap_forest_settings::noise_threshold_forest, regional_settings::overmap_forest, pos(), settings, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by generate().
calculate_ocean_gradient()
float overmap::calculate_ocean_gradient (const point_om_omt & p, point_abs_om this_omt) private
Definition at line 4725 of file overmap.cpp.
 {
     const int northern_ocean = settings->overmap_ocean.ocean_start_north;
     const int eastern_ocean = settings->overmap_ocean.ocean_start_east;
     const int western_ocean = settings->overmap_ocean.ocean_start_west;
     const int southern_ocean = settings->overmap_ocean.ocean_start_south;
     float ocean_adjust_N = 0.0f;
     float ocean_adjust_E = 0.0f;
     float ocean_adjust_W = 0.0f;
     float ocean_adjust_S = 0.0f;
     if( northern_ocean > 0 && this_om.y() <= northern_ocean * -1 ) {
         ocean_adjust_N = 0.0005f * static_cast<float>( OMAPY - p.y()
                          + std::abs( ( this_om.y() + northern_ocean ) * OMAPY ) );
     }
     if( eastern_ocean > 0 && this_om.x() >= eastern_ocean ) {
         ocean_adjust_E = 0.0005f * static_cast<float>( p.x() + ( this_om.x() - eastern_ocean )
                          * OMAPX );
     }
     if( western_ocean > 0 && this_om.x() <= western_ocean * -1 ) {
         ocean_adjust_W = 0.0005f * static_cast<float>( OMAPX - p.x()
                          + std::abs( ( this_om.x() + western_ocean ) * OMAPX ) );
     }
     if( southern_ocean > 0 && this_om.y() >= southern_ocean ) {
         ocean_adjust_S = 0.0005f * static_cast<float>( p.y() + ( this_om.y() - southern_ocean ) * OMAPY );
     }
     return std::max( { ocean_adjust_N, ocean_adjust_E, ocean_adjust_W, ocean_adjust_S } );
 }
References abs(), max(), overmap_ocean_settings::ocean_start_east, overmap_ocean_settings::ocean_start_north, overmap_ocean_settings::ocean_start_south, overmap_ocean_settings::ocean_start_west, OMAPX, OMAPY, regional_settings::overmap_ocean, settings, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by place_mongroups(), and place_oceans().
calculate_urbanity()
void overmap::calculate_urbanity () private
Definition at line 5369 of file overmap.cpp.
 {
     int op_city_size = get_option<int>( "CITY_SIZE" );
     if( op_city_size <= 0 ) {
         return;
     }
     int northern_urban_increase = get_option<int>( "OVERMAP_URBAN_INCREASE_NORTH" );
     int eastern_urban_increase = get_option<int>( "OVERMAP_URBAN_INCREASE_EAST" );
     int western_urban_increase = get_option<int>( "OVERMAP_URBAN_INCREASE_WEST" );
     int southern_urban_increase = get_option<int>( "OVERMAP_URBAN_INCREASE_SOUTH" );
     if( northern_urban_increase == 0 && eastern_urban_increase == 0 && western_urban_increase == 0 &&
         southern_urban_increase == 0 ) {
         return;
     }
     float urbanity_adj = 0.0f;
     const point_abs_om this_om = pos();
     if( northern_urban_increase != 0 && this_om.y() < 0 ) {
         urbanity_adj -= this_om.y() * northern_urban_increase / 10.0f;
         // add some falloff to the sides, keeping cities larger but breaking up the megacity a bit.
         // Doesn't apply if we expect megacity in those directions as well.
         if( this_om.x() < 0 && western_urban_increase == 0 ) {
             urbanity_adj /=  std::max( this_om.x() / -2.0f, 1.0f );
         }
         if( this_om.x() > 0 && eastern_urban_increase == 0 ) {
             urbanity_adj /=  std::max( this_om.x() / 2.0f, 1.0f );
         }
     }
     if( eastern_urban_increase != 0 && this_om.x() > 0 ) {
         urbanity_adj += this_om.x() * eastern_urban_increase / 10.0f;
         if( this_om.y() < 0 && northern_urban_increase == 0 ) {
             urbanity_adj /=  std::max( this_om.y() / -2.0f, 1.0f );
         }
         if( this_om.y() > 0 && southern_urban_increase == 0 ) {
             urbanity_adj /= std::max( this_om.y() / 2.0f, 1.0f );
         }
     }
     if( western_urban_increase != 0 && this_om.x() < 0 ) {
         urbanity_adj -= this_om.x() * western_urban_increase / 10.0f;
         if( this_om.y() < 0 && northern_urban_increase == 0 ) {
             urbanity_adj /=  std::max( this_om.y() / -2.0f, 1.0f );
         }
         if( this_om.y() > 0 && southern_urban_increase == 0 ) {
             urbanity_adj /=  std::max( this_om.y() / 2.0f, 1.0f );
         }
     }
     if( southern_urban_increase != 0 && this_om.y() > 0 ) {
         urbanity_adj += this_om.y() * southern_urban_increase / 10.0f;
         if( this_om.x() < 0 && western_urban_increase == 0 ) {
             urbanity_adj /=  std::max( this_om.x() / -2.0f, 1.0f );
         }
         if( this_om.x() > 0 && eastern_urban_increase == 0 ) {
             urbanity_adj /=  std::max( this_om.x() / 2.0f, 1.0f );
         }
     }
     urbanity = static_cast<int>( urbanity_adj );
     //debugmsg( "urbanity = %i at OM %i, %i", urbanity, this_om.x(), this_om.y() );
 }
References max(), pos(), urbanity, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by generate().
can_place_special()
bool overmap::can_place_special (const overmap_special & special, const tripoint_om_omt & p, om_direction::type dir, bool must_be_unexplored) const
Definition at line 6571 of file overmap.cpp.
 {
     cata_assert( dir != om_direction::type::invalid );
     if( !special.id ) {
         return false;
     }
     if( special.has_flag( "GLOBALLY_UNIQUE" ) &&
         overmap_buffer.contains_unique_special( special.id ) ) {
         return false;
     }
     if( special.has_eoc() ) {
         dialogue d( get_talker_for( get_avatar() ), nullptr );
         if( !special.get_eoc()->test_condition( d ) ) {
             return false;
         }
     }
     const std::vector<overmap_special_locations> fixed_terrains = special.required_locations();
     return std::all_of( fixed_terrains.begin(), fixed_terrains.end(),
     [&]( const overmap_special_locations & elem ) {
         const tripoint_om_omt rp = p + om_direction::rotate( elem.p, dir );
         if( !inbounds( rp, 1 ) ) {
             return false;
         }
         if( must_be_unexplored ) {
             // If this must be unexplored, check if we've already got a submap generated.
             const bool existing_submap = is_omt_generated( rp );
             // If there is an existing submap, this area has already been explored and this
             // isn't a valid placement.
             if( existing_submap ) {
                 return false;
             }
         }
         const oter_id &tid = ter( rp );
         return elem.can_be_placed_on( tid ) || ( rp.z() != 0 && tid == get_default_terrain( rp.z() ) );
     } );
 }
References cata_assert, overmapbuffer::contains_unique_special(), get_avatar(), overmap_special::get_eoc(), get_talker_for(), overmap_special::has_eoc(), overmap_special::has_flag(), overmap_special::id, om_direction::invalid, overmap_buffer, overmap_special::required_locations(), and effect_on_condition::test_condition().
Referenced by place_building(), place_forest_trailheads(), overmapbuffer::place_special(), place_special(), and random_special_rotation().
check_ot()
bool overmap::check_ot (const std::string & otype, ot_match_type match_type, const tripoint_om_omt & p) const
TODO: this check should be done by the caller. Probably.
Definition at line 6281 of file overmap.cpp.
 {
     /// TODO: this check should be done by the caller. Probably.
     if( !inbounds( p ) ) {
         return false;
     }
     const oter_id &oter = ter( p );
     return is_ot_match( otype, oter, match_type );
 }
References inbounds(), is_ot_match(), and ter().
Referenced by build_lab(), overmapbuffer::check_ot(), overmapbuffer::check_ot_existing(), and place_forest_trailheads().
check_overmap_special_type()
bool overmap::check_overmap_special_type (const overmap_special_id & id, const tripoint_om_omt & location) const
Definition at line 6292 of file overmap.cpp.
 {
     // Try and find the special associated with this location.
     auto found_id = overmap_special_placements.find( location );
     // There was no special here, so bail.
     if( found_id == overmap_special_placements.end() ) {
         return false;
     }
     // Return whether the found special was a match with our requested id.
     return found_id->second == id;
 }
References base_camps::id, location, and overmap_special_placements.
Referenced by overmapbuffer::check_overmap_special_type(), and overmapbuffer::check_overmap_special_type_existing().
chip_rock()
void overmap::chip_rock (const tripoint_om_omt & p)
Definition at line 6269 of file overmap.cpp.
 {
     const oter_id rock( "rock" );
     const oter_id empty_rock( "empty_rock" );
     for( const point &offset : four_adjacent_offsets ) {
         if( ter( p + offset ) == empty_rock ) {
             ter_set( p + offset, rock );
         }
     }
 }
References four_adjacent_offsets, ter(), and ter_set().
Referenced by build_slimepit().
clear_cities()
void overmap::clear_cities ()
Definition at line 3935 of file overmap.cpp.
 {
     cities.clear();
 }
References cities.
clear_connections_out()
void overmap::clear_connections_out ()
Definition at line 3939 of file overmap.cpp.
 {
     connections_out.clear();
 }
References connections_out.
clear_mon_groups()
void overmap::clear_mon_groups ()
Definition at line 3926 of file overmap.cpp.
 {
     zg.clear();
 }
References zg.
Referenced by tutorial_game::init().
clear_overmap_special_placements()
void overmap::clear_overmap_special_placements ()
Definition at line 3931 of file overmap.cpp.
 {
     overmap_special_placements.clear();
 }
References overmap_special_placements.
connect_closest_points()
void overmap::connect_closest_points (const std::vector< point_om_omt > & points, int z, const overmap_connection & connection)
Definition at line 6186 of file overmap.cpp.
 {
     // { weight, {i, j} }
     using edge = std::pair<float, std::pair<size_t, size_t>>;
     if( points.size() < 2 ) {
         return;
     }
     std::vector<edge> edges;
     // enumerate every possible connection between the points
     edges.reserve( points.size() * ( points.size() - 1 ) / 2 );
     for( size_t i = 0; i < points.size() - 1; ++i ) {
         for( size_t j = i + 1; j < points.size(); j++ ) {
             const float distance = trig_dist( points[i], points[j] );
             edges.push_back( {distance, {i, j}} );
         }
     }
     // sort from shortest to longest
     sort( edges.begin(), edges.end() );
     // track which subgraph each point belongs to
     std::vector<int> subgraphs( points.size(), -1 );
     for( edge candidate : edges ) {
         const size_t i = candidate.second.first;
         const size_t j = candidate.second.second;
         bool connect = false;
         if( subgraphs[i] < 0 && subgraphs[j] < 0 ) {
             // neither point of this connection has been connected yet
             // identify them each as the root of a new subgraph
             subgraphs[i] = i;
             subgraphs[j] = j;
             // and connect them
             connect = true;
         } else if( subgraphs[i] < 0 ) {
             // j is already connected to something
             // add i to j's subgraph
             subgraphs[i] = subgraphs[j];
             // and connect them
             connect = true;
         } else if( subgraphs[j] < 0 ) {
             // i is already connected to something
             // add j to i's subgraph
             subgraphs[j] = subgraphs[i];
             // and connect them
             connect = true;
         } else if( subgraphs[i] != subgraphs[j] ) {
             // i and j are both connected to different subgraphs
             // join the subgraphs
             int dead_subtree = subgraphs[j];
             for( size_t k = 0; k < points.size(); k++ ) {
                 if( subgraphs[k] == dead_subtree ) {
                     subgraphs[k] = subgraphs[i];
                 }
             }
             // and connect them
             connect = true;
         } else if( one_in( 10 ) ) {
             // the remaining case is that i and j are already in the same subgraph
             // making this connection creates a loop
             connect = true;
         }
         if( connect ) {
             build_connection( points[i], points[j], z, connection, false );
         }
     }
 }
References build_connection(), edge, one_in(), and trig_dist().
Referenced by generate_sub(), place_forest_trails(), place_railroads(), and place_roads().
delete_extra()
void overmap::delete_extra (const tripoint_om_omt & p)
Definition at line 3320 of file overmap.cpp.
 {
     add_extra( p, map_extra_id::NULL_ID() );
 }
References add_extra(), and string_id< map_extra >::NULL_ID().
Referenced by overmapbuffer::delete_extra().
delete_note()
void overmap::delete_note (const tripoint_om_omt & p)
Definition at line 3207 of file overmap.cpp.
 {
     add_note( p, std::string{} );
 }
References add_note().
Referenced by overmapbuffer::delete_note().
erase_npc()
shared_ptr_fast< npc > overmap::erase_npc (const character_id & id)
Removes the npc and returns it (or returns nullptr if not found).
Definition at line 3082 of file overmap.cpp.
 {
     const auto iter = std::find_if( npcs.begin(),
     npcs.end(), [id]( const shared_ptr_fast<npc> &n ) {
         return n->getID() == id;
     } );
     if( iter == npcs.end() ) {
         return nullptr;
     }
     auto ptr = *iter;
     npcs.erase( iter );
     g->set_npcs_dirty();
     return ptr;
 }
References g, and npcs.
Referenced by npc::on_move(), and npc::travel_overmap().
explored()
bool & overmap::explored (const tripoint_om_omt & p)
Definition at line 3033 of file overmap.cpp.
 {
     if( !inbounds( p ) ) {
         nullbool = false;
         return nullbool;
     }
     return layer[p.z() + OVERMAP_DEPTH].explored[p.xy()];
 }
References inbounds(), layer, nullbool, OVERMAP_DEPTH, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by serialize_view(), overmapbuffer::toggle_explored(), and unserialize_view().
extra()
const map_extra_id & overmap::extra (const tripoint_om_omt & p) const
Definition at line 3238 of file overmap.cpp.
 {
     static const map_extra_id fallback{};
     if( p.z() < -OVERMAP_DEPTH || p.z() > OVERMAP_HEIGHT ) {
         return fallback;
     }
     const auto &extras = layer[p.z() + OVERMAP_DEPTH].extras;
     const auto it = std::find_if( begin( extras ),
     end( extras ), [&]( const om_map_extra & n ) {
         return n.p == p.xy();
     } );
     return ( it != std::end( extras ) ) ? it->id : fallback;
 }
References keycode::end, anonymous_namespace{map_extras.cpp}::extras, layer, OVERMAP_DEPTH, OVERMAP_HEIGHT, om_map_extra::p, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by add_extra_note(), and find_extras().
find_camp()
std::optional< basecamp * > overmap::find_camp (const point_abs_omt & p)
Definition at line 7326 of file overmap.cpp.
 {
     for( basecamp &v : camps ) {
         if( v.camp_omt_pos().xy() == p ) {
             return &v;
         }
     }
     return std::nullopt;
 }
References camps.
find_extras()
std::vector< point_abs_omt > overmap::find_extras (int z, const std::string & text)
Return a vector containing the absolute coordinates of every matching map extra on the current z level of the current overmap.
Returns
A vector of map extra coordinates (absolute overmap terrain coordinates), or empty vector if no matching map extras are found.
Definition at line 3325 of file overmap.cpp.
 {
     std::vector<point_abs_omt> extra_locations;
     map_layer &this_layer = layer[z + OVERMAP_DEPTH];
     for( const om_map_extra &extra : this_layer.extras ) {
         const std::string extra_text = extra.id.c_str();
         if( match_include_exclude( extra_text, text ) ) {
             extra_locations.push_back( project_combine( pos(), extra.p ) );
         }
     }
     return extra_locations;
 }
References extra(), map_layer::extras, string_id< T >::id(), layer, match_include_exclude(), OVERMAP_DEPTH, pos(), and coords::project_combine().
find_notes()
std::vector< point_abs_omt > overmap::find_notes (int z, const std::string & text)
Return a vector containing the absolute coordinates of every matching note on the current z level of the current overmap.
Returns
A vector of note coordinates (absolute overmap terrain coordinates), or empty vector if no matching notes are found.
Definition at line 3212 of file overmap.cpp.
 {
     std::vector<point_abs_omt> note_locations;
     map_layer &this_layer = layer[z + OVERMAP_DEPTH];
     for( const om_note &note : this_layer.notes ) {
         if( match_include_exclude( note.text, text ) ) {
             note_locations.push_back( project_combine( pos(), note.p ) );
         }
     }
     return note_locations;
 }
References layer, match_include_exclude(), note(), map_layer::notes, OVERMAP_DEPTH, pos(), and coords::project_combine().
Referenced by overmap_ui::search().
find_npc()
shared_ptr_fast< npc > overmap::find_npc (const character_id & id) const
Definition at line 7306 of file overmap.cpp.
 {
     for( const auto &guy : npcs ) {
         if( guy->getID() == id ) {
             return guy;
         }
     }
     return nullptr;
 }
References npcs.
find_npc_by_unique_id()
shared_ptr_fast< npc > overmap::find_npc_by_unique_id (const std::string & id) const
Definition at line 7316 of file overmap.cpp.
 {
     for( const auto &guy : npcs ) {
         if( guy->get_unique_id() == id ) {
             return guy;
         }
     }
     return nullptr;
 }
References npcs.
Referenced by overmapbuffer::find_npc_by_unique_id().
find_random_omt() [1/2]
tripoint_om_omt overmap::find_random_omt (const std::pair< std::string, ot_match_type > & target, std::optional< city > target_city = std::nullopt) const
Returns
The (local) overmap terrain coordinates of a randomly chosen place on the overmap with the specific overmap terrain. Returns invalid_tripoint if no suitable place has been found.
Definition at line 3891 of file overmap.cpp.
 {
     const bool check_nearest_city = target_city.has_value();
     std::vector<tripoint_om_omt> valid;
     for( int i = 0; i < OMAPX; i++ ) {
         for( int j = 0; j < OMAPY; j++ ) {
             for( int k = -OVERMAP_DEPTH; k <= OVERMAP_HEIGHT; k++ ) {
                 tripoint_om_omt p( i, j, k );
                 if( is_ot_match( target.first, ter( p ), target.second ) ) {
                     if( !check_nearest_city || get_nearest_city( p ) == target_city.value() ) {
                         valid.push_back( p );
                     }
                 }
             }
         }
     }
     return random_entry( valid, tripoint_om_omt( tripoint_min ) );
 }
References get_nearest_city(), is_ot_match(), OMAPX, OMAPY, OVERMAP_DEPTH, OVERMAP_HEIGHT, random_entry(), ter(), and tripoint_min.
Referenced by start_location::find_player_initial_location(), and find_random_omt().
find_random_omt() [2/2]
tripoint_om_omt overmap::find_random_omt (const std::string & omt_base_type, ot_match_type match_type = ot_match_type::type, std::optional< city > target_city = std::nullopt) const inline
Definition at line 216 of file overmap.h.
{
             return find_random_omt( std::make_pair( omt_base_type, match_type ), std::move( target_city ) );
         }
References find_random_omt().
find_terrain()
std::vector< point_abs_omt > overmap::find_terrain (std::string_view term, int zlevel) const
Return a vector containing the absolute coordinates of every matching terrain on the current z level of the current overmap.
Returns
A vector of terrain coordinates (absolute overmap terrain coordinates), or empty vector if no matching terrain is found.
Definition at line 3858 of file overmap.cpp.
 {
     std::vector<point_abs_omt> found;
     for( int x = 0; x < OMAPX; x++ ) {
         for( int y = 0; y < OMAPY; y++ ) {
             tripoint_om_omt p( x, y, zlevel );
             if( seen( p ) &&
                 lcmatch( ter( p )->get_name(), term ) ) {
                 found.push_back( project_combine( pos(), p.xy() ) );
             }
         }
     }
     return found;
 }
References lcmatch(), OMAPX, OMAPY, pos(), coords::project_combine(), seen(), ter(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
generate()
void overmap::generate (const overmap * north, const overmap * east, const overmap * south, const overmap * west, overmap_special_batch & enabled_specials) private
Definition at line 3367 of file overmap.cpp.
 {
     dbg( D_INFO ) << "overmap::generate start";
     const oter_id omt_outside_defined_omap = static_cast<oter_id>
             ( get_option<std::string>( "OUTSIDE_DEFINED_OMAP_OMT" ) );
     const std::string overmap_pregenerated_path =
         get_option<std::string>( "OVERMAP_PREGENERATED_PATH" );
     if( !overmap_pregenerated_path.empty() ) {
         // HACK: For some reason gz files are automatically unpacked and renamed during Android build process
 #if defined(__ANDROID__)
         static const std::string fname = "%s/overmap_%d_%d.omap";
 #else
         static const std::string fname = "%s/overmap_%d_%d.omap.gz";
 #endif
         const cata_path fpath = PATH_INFO::moddir() / string_format( fname,
                                 overmap_pregenerated_path, pos().x(), pos().y() );
         dbg( D_INFO ) << "trying" << fpath;
         if( !read_from_file_optional_json( fpath, [this, &fpath]( const JsonValue & jv ) {
         unserialize_omap( jv, fpath );
         } ) ) {
             dbg( D_INFO ) << "failed" << fpath;
             int z = 0;
             for( int j = 0; j < OMAPY; j++ ) {
                 // NOLINTNEXTLINE(modernize-loop-convert)
                 for( int i = 0; i < OMAPX; i++ ) {
                     layer[z + OVERMAP_DEPTH].terrain[i][j] = omt_outside_defined_omap;
                 }
             }
         }
     }
     calculate_urbanity();
     calculate_forestosity();
     if( get_option<bool>( "OVERMAP_POPULATE_OUTSIDE_CONNECTIONS_FROM_NEIGHBORS" ) ) {
         populate_connections_out_from_neighbors( north, east, south, west );
     }
     if( get_option<bool>( "OVERMAP_PLACE_RIVERS" ) ) {
         place_rivers( north, east, south, west );
     }
     if( get_option<bool>( "OVERMAP_PLACE_LAKES" ) ) {
         place_lakes();
     }
     if( get_option<bool>( "OVERMAP_PLACE_OCEANS" ) ) {
         place_oceans();
     }
     if( get_option<bool>( "OVERMAP_PLACE_FORESTS" ) ) {
         place_forests();
     }
     if( get_option<bool>( "OVERMAP_PLACE_SWAMPS" ) ) {
         place_swamps();
     }
     if( get_option<bool>( "OVERMAP_PLACE_RAVINES" ) ) {
         place_ravines();
     }
     if( get_option<bool>( "OVERMAP_PLACE_CITIES" ) ) {
         place_cities();
     }
     if( get_option<bool>( "OVERMAP_PLACE_FOREST_TRAILS" ) ) {
         place_forest_trails();
     }
     if( get_option<bool>( "OVERMAP_PLACE_RAILROADS_BEFORE_ROADS" ) ) {
         if( get_option<bool>( "OVERMAP_PLACE_RAILROADS" ) ) {
             place_railroads( north, east, south, west );
         }
         if( get_option<bool>( "OVERMAP_PLACE_ROADS" ) ) {
             place_roads( north, east, south, west );
         }
     } else {
         if( get_option<bool>( "OVERMAP_PLACE_ROADS" ) ) {
             place_roads( north, east, south, west );
         }
         if( get_option<bool>( "OVERMAP_PLACE_RAILROADS" ) ) {
             place_railroads( north, east, south, west );
         }
     }
     if( get_option<bool>( "OVERMAP_PLACE_SPECIALS" ) ) {
         place_specials( enabled_specials );
     }
     if( get_option<bool>( "OVERMAP_PLACE_FOREST_TRAILHEADS" ) ) {
         place_forest_trailheads();
     }
     polish_river();
     // TODO: there is no reason we can't generate the sublevels in one pass
     //       for that matter there is no reason we can't as we add the entrance ways either
     // Always need at least one sublevel, but how many more
     int z = -1;
     bool requires_sub = false;
     do {
         requires_sub = generate_sub( z );
     } while( requires_sub && ( --z >= -OVERMAP_DEPTH ) );
     // Always need at least one overlevel, but how many more
     z = 1;
     bool requires_over = false;
     do {
         requires_over = generate_over( z );
     } while( requires_over && ( ++z <= OVERMAP_HEIGHT ) );
     // Place the monsters, now that the terrain is laid out
     place_mongroups();
     place_radios();
     dbg( D_INFO ) << "overmap::generate done";
 }
References calculate_forestosity(), calculate_urbanity(), D_INFO, dbg, east, generate_over(), generate_sub(), layer, PATH_INFO::moddir(), north, OMAPX, OMAPY, OVERMAP_DEPTH, OVERMAP_HEIGHT, place_cities(), place_forest_trailheads(), place_forest_trails(), place_forests(), place_lakes(), place_mongroups(), place_oceans(), place_radios(), place_railroads(), place_ravines(), place_rivers(), place_roads(), place_specials(), place_swamps(), polish_river(), populate_connections_out_from_neighbors(), pos(), read_from_file_optional_json(), south, string_format(), unserialize_omap(), and west.
Referenced by open().
generate_bridgeheads()
void overmap::generate_bridgeheads (const std::vector< point_om_omt > & bridge_points, oter_type_str_id bridge_type, const std::string & bridgehead_ground, const std::string & bridgehead_ramp) private
Definition at line 3816 of file overmap.cpp.
 {
     std::vector<std::pair<point_om_omt, std::string>> bridgehead_points;
     for( const point_om_omt &bp : bridge_points ) {
         //const oter_id oter_ground = ter( tripoint_om_omt( bp, 0 ) );
         const oter_id oter_ground_north = ter( tripoint_om_omt( bp, 0 ) + tripoint_north );
         const oter_id oter_ground_south = ter( tripoint_om_omt( bp, 0 ) + tripoint_south );
         const oter_id oter_ground_east = ter( tripoint_om_omt( bp, 0 ) + tripoint_east );
         const oter_id oter_ground_west = ter( tripoint_om_omt( bp, 0 ) + tripoint_west );
         const bool is_bridge_north = ( oter_ground_north->get_type_id() == bridge_type )
                                      && ( oter_get_rotation( oter_ground_north ) % 2 == 0 );
         const bool is_bridge_south = ( oter_ground_south->get_type_id() == bridge_type )
                                      && ( oter_get_rotation( oter_ground_south ) % 2 == 0 );
         const bool is_bridge_east = ( oter_ground_east->get_type_id() == bridge_type )
                                     && ( oter_get_rotation( oter_ground_east ) % 2 == 1 );
         const bool is_bridge_west = ( oter_ground_west->get_type_id() == bridge_type )
                                     && ( oter_get_rotation( oter_ground_west ) % 2 == 1 );
         if( is_bridge_north ^ is_bridge_south || is_bridge_east ^ is_bridge_west ) {
             std::string ramp_facing;
             if( is_bridge_north ) {
                 ramp_facing = "_south";
             } else if( is_bridge_south ) {
                 ramp_facing = "_north";
             } else if( is_bridge_east ) {
                 ramp_facing = "_west";
             } else {
                 ramp_facing = "_east";
             }
             bridgehead_points.emplace_back( bp, ramp_facing );
         }
     }
     for( const std::pair<point_om_omt, std::string> &bhp : bridgehead_points ) {
         tripoint_om_omt p( bhp.first, 0 );
         ter_set( p, oter_id( bridgehead_ground + bhp.second ) );
         ter_set( p + tripoint_above, oter_id( bridgehead_ramp + bhp.second ) );
     }
 }
References bp, oter_t::get_type_id(), oter_get_rotation(), oter_id, ter(), ter_set(), tripoint_above, tripoint_east, tripoint_north, tripoint_south, and tripoint_west.
Referenced by generate_over().
generate_over()
bool overmap::generate_over (int z) private
Definition at line 3765 of file overmap.cpp.
 {
     bool requires_over = false;
     std::vector<point_om_omt> bridge_points;
     std::vector<point_om_omt> railroad_bridge_points;
     // These are so common that it's worth checking first as int.
     const std::set<oter_id> skip_below = {
         oter_empty_rock.id(), oter_forest.id(), oter_field.id(),
         oter_forest_thick.id(), oter_forest_water.id(), oter_solid_earth.id()
     };
     if( z == 1 ) {
         for( int i = 0; i < OMAPX; i++ ) {
             for( int j = 0; j < OMAPY; j++ ) {
                 tripoint_om_omt p( i, j, z );
                 const oter_id oter_below = ter( p + tripoint_below );
                 const oter_id oter_ground = ter( tripoint_om_omt( p.xy(), 0 ) );
                 // implicitly skip skip_below oter_ids
                 if( skip_below.find( oter_below ) != skip_below.end() ) {
                     continue;
                 }
                 if( oter_ground->get_type_id() == oter_type_bridge ) {
                     ter_set( p, oter_id( "bridge_road" + oter_get_rotation_string( oter_ground ) ) );
                     bridge_points.push_back( p.xy() );
                     tripoint_om_omt support_point = p + tripoint_below;
                     int support_z = 0;
                     // place the rest of the support columns
                     while( ter( support_point ) -> is_water() && --support_z >= -OVERMAP_DEPTH ) {
                         ter_set( support_point, oter_id( "bridge" + oter_get_rotation_string( oter_ground ) ) );
                         support_point += tripoint_below;
                     }
                 }
                 if( oter_ground->get_type_id() == oter_type_railroad_bridge ) {
                     ter_set( p, oter_id( "railroad_bridge_overpass" + oter_get_rotation_string( oter_ground ) ) );
                     railroad_bridge_points.push_back( p.xy() );
                 }
             }
         }
     }
     generate_bridgeheads( bridge_points, oter_type_bridge,
                           "bridgehead_ground", "bridgehead_ramp" );
     generate_bridgeheads( railroad_bridge_points, oter_type_railroad_bridge,
                           "railroad_bridgehead_ground", "railroad_bridgehead_ramp" );
     return requires_over;
 }
References generate_bridgeheads(), oter_t::get_type_id(), string_id< T >::id(), OMAPX, OMAPY, oter_empty_rock, oter_field, oter_forest, oter_forest_thick, oter_forest_water, oter_get_rotation_string(), oter_id, oter_solid_earth, oter_type_bridge, oter_type_railroad_bridge, OVERMAP_DEPTH, ter(), ter_set(), tripoint_below, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by generate().
generate_sub()
bool overmap::generate_sub (int z) private
Definition at line 3475 of file overmap.cpp.
 {
     cata_assert( z < 0 );
     bool requires_sub = false;
     std::vector<point_om_omt> subway_points;
     std::vector<point_om_omt> sewer_points;
     std::vector<city> ant_points;
     std::vector<city> goo_points;
     std::vector<city> lab_points;
     std::vector<city> ice_lab_points;
     std::vector<city> central_lab_points;
     std::vector<point_om_omt> lab_train_points;
     std::vector<point_om_omt> central_lab_train_points;
     const auto add_goo_point = [&]( const tripoint_om_omt & p ) {
         const int size = rng( MIN_GOO_SIZE, MAX_GOO_SIZE );
         goo_points.emplace_back( p.xy(), size );
     };
     std::unordered_map<oter_type_id, std::function<void( const tripoint_om_omt &p )>>
     oter_above_actions = {
         { oter_type_empty_rock.id(), []( const tripoint_om_omt & ) {} },
         { oter_type_forest.id(), []( const tripoint_om_omt & ) {} },
         { oter_type_field.id(), []( const tripoint_om_omt & ) {} },
         { oter_type_forest_water.id(), []( const tripoint_om_omt & ) {} },
         { oter_type_forest_thick.id(), []( const tripoint_om_omt & ) {} },
         { oter_type_solid_earth.id(), []( const tripoint_om_omt & ) {} },
         {
             oter_type_road_nesw_manhole.id(),
             [&]( const tripoint_om_omt & p )
             {
                 ter_set( p, oter_sewer_isolated.id() );
                 sewer_points.emplace_back( p.xy() );
             }
         },
         { oter_type_slimepit_down.id(), add_goo_point },
         { oter_type_slimepit_bottom.id(), add_goo_point },
         {
             oter_type_lab_core.id(),
             [&]( const tripoint_om_omt & p )
             {
                 lab_points.emplace_back( p.xy(), rng( 1, 5 + z ) );
             }
         },
         {
             oter_type_lab_stairs.id(),
             [&]( const tripoint_om_omt & p )
             {
                 if( z == -1 ) {
                     lab_points.emplace_back( p.xy(), rng( 1, 5 + z ) );
                 } else {
                     ter_set( p, oter_lab.id() );
                 }
             }
         },
         {
             oter_type_ice_lab_core.id(),
             [&]( const tripoint_om_omt & p )
             {
                 ice_lab_points.emplace_back( p.xy(), rng( 1, 5 + z ) );
             }
         },
         {
             oter_type_ice_lab_stairs.id(),
             [&]( const tripoint_om_omt & p )
             {
                 if( z == -1 ) {
                     ice_lab_points.emplace_back( p.xy(), rng( 1, 5 + z ) );
                 } else {
                     ter_set( p, oter_ice_lab.id() );
                 }
             }
         },
         {
             oter_type_central_lab_core.id(),
             [&]( const tripoint_om_omt & p )
             {
                 central_lab_points.emplace_back( p.xy(), rng( std::max( 1, 7 + z ), 9 + z ) );
             }
         },
         {
             oter_type_central_lab_stairs.id(),
             [&]( const tripoint_om_omt & p )
             {
                 ter_set( p, oter_central_lab.id() );
             }
         },
     };
     // Avoid constructing strings inside the loop
     static const std::string s_hidden_lab_stairs = "hidden_lab_stairs";
     for( int i = 0; i < OMAPX; i++ ) {
         for( int j = 0; j < OMAPY; j++ ) {
             tripoint_om_omt p( i, j, z );
             const oter_id oter_id_here = ter_unsafe( p );
             const oter_t &oter_here = *oter_id_here;
             const oter_id oter_above = ter_unsafe( p + tripoint_above );
             const oter_id oter_ground = ter_unsafe( tripoint_om_omt( p.xy(), 0 ) );
             if( oter_here.get_type_id() == oter_type_sewer_connector ) {
                 om_direction::type rotation = oter_here.get_dir();
                 ter_set( p, oter_sewer_end_north.id()->get_rotated( rotation ) );
                 sewer_points.emplace_back( p.xy() );
             }
             if( oter_here.get_type_id() == oter_type_microlab_sub_connector ) {
                 om_direction::type rotation = oter_here.get_dir();
                 ter_set( p, oter_subway_end_north.id()->get_rotated( rotation ) );
                 subway_points.emplace_back( p.xy() );
             }
             if( oter_ground->get_type_id() == oter_type_sub_station ) {
                 if( z == -1 ) {
                     ter_set( p, oter_sewer_sub_station.id() );
                     requires_sub = true;
                     continue;
                 } else if( z == -2 ) {
                     ter_set( p, oter_subway_isolated.id() );
                     subway_points.emplace_back( i, j - 1 );
                     subway_points.emplace_back( i, j );
                     subway_points.emplace_back( i, j + 1 );
                     continue;
                 }
             }
             auto above_action_it = oter_above_actions.find( oter_above->get_type_id().id() );
             if( above_action_it != oter_above_actions.end() ) {
                 above_action_it->second( p );
             } else if( is_ot_match( s_hidden_lab_stairs, oter_above, ot_match_type::contains ) ) {
                 lab_points.emplace_back( p.xy(), rng( 1, 5 + z ) );
             }
         }
     }
     for( city &i : goo_points ) {
         requires_sub |= build_slimepit( tripoint_om_omt( i.pos, z ), i.size );
     }
     const overmap_connection_id &overmap_connection_sewer_tunnel =
         settings->overmap_connection.sewer_connection;
     connect_closest_points( sewer_points, z, *overmap_connection_sewer_tunnel );
     // A third of overmaps have labs with a 1-in-2 chance of being subway connected.
     // If the central lab exists, all labs which go down to z=4 will have a subway to central.
     int lab_train_odds = 0;
     if( z == -2 && one_in( 3 ) ) {
         lab_train_odds = 2;
     }
     if( z == -4 && !central_lab_points.empty() ) {
         lab_train_odds = 1;
     }
     for( city &i : lab_points ) {
         bool lab = build_lab( tripoint_om_omt( i.pos, z ), i.size, &lab_train_points, "", lab_train_odds );
         requires_sub |= lab;
         if( !lab && ter( tripoint_om_omt( i.pos, z ) ) == oter_lab_core ) {
             ter_set( tripoint_om_omt( i.pos, z ), oter_lab.id() );
         }
     }
     for( city &i : ice_lab_points ) {
         bool ice_lab = build_lab( tripoint_om_omt( i.pos, z ), i.size, &lab_train_points, "ice_",
                                   lab_train_odds );
         requires_sub |= ice_lab;
         if( !ice_lab && ter( tripoint_om_omt( i.pos, z ) ) == oter_ice_lab_core ) {
             ter_set( tripoint_om_omt( i.pos, z ), oter_ice_lab.id() );
         }
     }
     for( city &i : central_lab_points ) {
         bool central_lab = build_lab( tripoint_om_omt( i.pos, z ), i.size, &central_lab_train_points,
                                       "central_", lab_train_odds );
         requires_sub |= central_lab;
         if( !central_lab && ter( tripoint_om_omt( i.pos, z ) ) == oter_central_lab_core ) {
             ter_set( tripoint_om_omt( i.pos, z ), oter_central_lab.id() );
         }
     }
     const auto create_real_train_lab_points = [this, z](
                 const std::vector<point_om_omt> &train_points,
     std::vector<point_om_omt> &real_train_points ) {
         bool is_first_in_pair = true;
         for( const point_om_omt &p : train_points ) {
             tripoint_om_omt i( p, z );
             const std::vector<tripoint_om_omt> nearby_locations {
                 i + point_north,
                 i + point_south,
                 i + point_east,
                 i + point_west };
             if( is_first_in_pair ) {
                 ter_set( i, oter_open_air.id() ); // mark tile to prevent subway gen
                 for( const tripoint_om_omt &nearby_loc : nearby_locations ) {
                     if( is_ot_match( "empty_rock", ter( nearby_loc ), ot_match_type::contains ) ) {
                         // mark tile to prevent subway gen
                         ter_set( nearby_loc, oter_open_air.id() );
                     }
                     if( is_ot_match( "solid_earth", ter( nearby_loc ), ot_match_type::contains ) ) {
                         // mark tile to prevent subway gen
                         ter_set( nearby_loc, oter_field.id() );
                     }
                 }
             } else {
                 // change train connection point back to rock to allow gen
                 if( is_ot_match( "open_air", ter( i ), ot_match_type::contains ) ) {
                     ter_set( i, oter_empty_rock.id() );
                 }
                 if( is_ot_match( "field", ter( i ), ot_match_type::contains ) ) {
                     ter_set( i, oter_solid_earth.id() );
                 }
                 real_train_points.push_back( i.xy() );
             }
             is_first_in_pair = !is_first_in_pair;
         }
     };
     std::vector<point_om_omt>
     subway_lab_train_points; // real points for subway, excluding train depot points
     create_real_train_lab_points( lab_train_points, subway_lab_train_points );
     create_real_train_lab_points( central_lab_train_points, subway_lab_train_points );
     subway_points.insert( subway_points.end(), subway_lab_train_points.begin(),
                           subway_lab_train_points.end() );
     const overmap_connection_id &overmap_connection_subway_tunnel =
         settings->overmap_connection.subway_connection;
     connect_closest_points( subway_points, z, *overmap_connection_subway_tunnel );
     for( auto &i : subway_points ) {
         if( ( ter( tripoint_om_omt( i, z + 2 ) )->get_type_id() == oter_type_sub_station ) ) {
             ter_set( tripoint_om_omt( i, z ), oter_underground_sub_station.id() );
         }
     }
     // The first lab point is adjacent to a lab, set it a depot (as long as track was actually laid).
     const auto create_train_depots = [this, z,
                                             overmap_connection_subway_tunnel]( const oter_id & train_type,
     const std::vector<point_om_omt> &train_points ) {
         bool is_first_in_pair = true;
         std::vector<point_om_omt> extra_route;
         for( const point_om_omt &p : train_points ) {
             tripoint_om_omt i( p, z );
             if( is_first_in_pair ) {
                 const std::vector<tripoint_om_omt> subway_possible_loc {
                     i + point_north,
                     i + point_south,
                     i + point_east,
                     i + point_west };
                 extra_route.clear();
                 ter_set( i, oter_empty_rock.id() ); // this clears marked tiles
                 bool is_depot_generated = false;
                 for( const tripoint_om_omt &subway_loc : subway_possible_loc ) {
                     if( !is_depot_generated &&
                         is_ot_match( "subway", ter( subway_loc ), ot_match_type::contains ) ) {
                         extra_route.push_back( i.xy() );
                         extra_route.push_back( subway_loc.xy() );
                         connect_closest_points( extra_route, z, *overmap_connection_subway_tunnel );
                         ter_set( i, train_type );
                         is_depot_generated = true; // only one connection to depot
                     } else if( is_ot_match( "open_air", ter( subway_loc ),
                                             ot_match_type::contains ) ) {
                         // clear marked
                         ter_set( subway_loc, oter_empty_rock.id() );
                     } else if( is_ot_match( "field", ter( subway_loc ),
                                             ot_match_type::contains ) ) {
                         // clear marked
                         ter_set( subway_loc, oter_solid_earth.id() );
                     }
                 }
             }
             is_first_in_pair = !is_first_in_pair;
         }
     };
     create_train_depots( oter_lab_train_depot.id(), lab_train_points );
     create_train_depots( oter_central_lab_train_depot.id(), central_lab_train_points );
     for( city &i : cities ) {
         tripoint_om_omt omt_pos( i.pos, z );
         tripoint_om_sm sm_pos = project_to<coords::sm>( omt_pos );
         tripoint_abs_sm abs_pos = project_combine( pos(), sm_pos );
         // Normal subways are present at z == -2, but filtering for the terrain would be much nicer
         if( z == -2 ) {
             spawn_mon_group( mongroup( GROUP_SUBWAY_CITY, abs_pos, i.size * i.size * 2 ),
                              i.size * 2 );
         }
     }
     return requires_sub;
 }
References build_lab(), build_slimepit(), cata_assert, cities, connect_closest_points(), contains, oter_t::get_dir(), oter_t::get_rotated(), oter_t::get_type_id(), GROUP_SUBWAY_CITY, string_id< T >::id(), is_ot_match(), max(), MAX_GOO_SIZE, MIN_GOO_SIZE, OMAPX, OMAPY, one_in(), oter_central_lab, oter_central_lab_core, oter_central_lab_train_depot, oter_empty_rock, oter_field, oter_ice_lab, oter_ice_lab_core, oter_lab, oter_lab_core, oter_lab_train_depot, oter_open_air, oter_sewer_end_north, oter_sewer_isolated, oter_sewer_sub_station, oter_solid_earth, oter_subway_end_north, oter_subway_isolated, oter_type_central_lab_core, oter_type_central_lab_stairs, oter_type_empty_rock, oter_type_field, oter_type_forest, oter_type_forest_thick, oter_type_forest_water, oter_type_ice_lab_core, oter_type_ice_lab_stairs, oter_type_lab_core, oter_type_lab_stairs, oter_type_microlab_sub_connector, oter_type_road_nesw_manhole, oter_type_sewer_connector, oter_type_slimepit_bottom, oter_type_slimepit_down, oter_type_solid_earth, oter_type_sub_station, oter_underground_sub_station, regional_settings::overmap_connection, point_east, point_north, point_south, point_west, pos(), coords::project_combine(), rng(), settings, overmap_connection_settings::sewer_connection, om_lines::size, spawn_mon_group(), overmap_connection_settings::subway_connection, ter(), ter_set(), ter_unsafe(), tripoint_above, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by generate().
get_default_terrain()
oter_id overmap::get_default_terrain (int z) const private
Definition at line 2909 of file overmap.cpp.
 {
     return settings->default_oter[OVERMAP_DEPTH + z].id();
 }
References regional_settings::default_oter, OVERMAP_DEPTH, and settings.
Referenced by init_layers().
get_nearest_city()
const city & overmap::get_nearest_city (const tripoint_om_omt & p) const private
Definition at line 3873 of file overmap.cpp.
 {
     int distance = 999;
     const city *res = nullptr;
     for( const city &elem : cities ) {
         const int dist = elem.get_distance_from( p );
         if( dist < distance ) {
             distance = dist;
             res = &elem;
         }
     }
     if( res != nullptr ) {
         return *res;
     }
     static city invalid_city;
     return invalid_city;
 }
References cities, and city::get_distance_from().
Referenced by find_random_omt(), place_forest_trailheads(), overmapbuffer::place_special(), and place_special_attempt().
get_npcs() [1/2]
const std::vector<shared_ptr_fast<npc> >& overmap::get_npcs () const inline
Definition at line 334 of file overmap.h.
{
             return npcs;
         }
References npcs.
get_npcs() [2/2]
std::vector< shared_ptr_fast< npc > > overmap::get_npcs (const std::function< bool(const npc &)> & predicate) const
Definition at line 3097 of file overmap.cpp.
 {
     std::vector<shared_ptr_fast<npc>> result;
     for( const auto &g : npcs ) {
         if( predicate( *g ) ) {
             result.push_back( g );
         }
     }
     return result;
 }
References g, and npcs.
get_or_migrate_oter()
oter_id overmap::get_or_migrate_oter (const std::string & oterid)
Definition at line 3980 of file overmap.cpp.
 {
     auto migration = oter_id_migrations.find( oterid );
     if( migration != oter_id_migrations.end() ) {
         return oter_id( migration->second );
     } else {
         return oter_id( oterid );
     }
 }
References oter_id, and oter_id_migrations.
Referenced by unserialize().
get_settings()
const regional_settings& overmap::get_settings () const inline
Definition at line 304 of file overmap.h.
{
             return *settings;
         }
References settings.
get_urbanity()
int overmap::get_urbanity () const inline
Definition at line 203 of file overmap.h.
{
             return urbanity;
         }
References urbanity.
global_base_point()
point_abs_omt overmap::global_base_point () const
Returns the (0, 0) corner of the overmap in the global coordinates.
Definition at line 7157 of file overmap.cpp.
 {
     return project_to<coords::omt>( loc );
 }
References loc.
Referenced by place_forests(), place_lakes(), place_mongroups(), place_oceans(), and place_swamps().
good_river()
void overmap::good_river (const tripoint_om_omt & p)
Definition at line 6318 of file overmap.cpp.
 {
     if( !is_ot_match( "river", ter( p ), ot_match_type::prefix ) ) {
         return;
     }
     if( ( p.x() == 0 ) || ( p.x() == OMAPX - 1 ) ) {
         if( !is_water_body( ter( p + point_north ) ) ) {
             ter_set( p, oter_river_north.id() );
         } else if( !is_water_body( ter( p + point_south ) ) ) {
             ter_set( p, oter_river_south.id() );
         } else {
             ter_set( p, oter_river_center.id() );
         }
         return;
     }
     if( ( p.y() == 0 ) || ( p.y() == OMAPY - 1 ) ) {
         if( !is_water_body( ter( p + point_west ) ) ) {
             ter_set( p, oter_river_west.id() );
         } else if( !is_water_body( ter( p + point_east ) ) ) {
             ter_set( p, oter_river_east.id() );
         } else {
             ter_set( p, oter_river_center.id() );
         }
         return;
     }
     if( is_water_body( ter( p + point_west ) ) ) {
         if( is_water_body( ter( p + point_north ) ) ) {
             if( is_water_body( ter( p + point_south ) ) ) {
                 if( is_water_body( ter( p + point_east ) ) ) {
                     // River on N, S, E, W;
                     // but we might need to take a "bite" out of the corner
                     if( !is_water_body( ter( p + point_north_west ) ) ) {
                         ter_set( p, oter_river_c_not_nw.id() );
                     } else if( !is_water_body( ter( p + point_north_east ) ) ) {
                         ter_set( p, oter_river_c_not_ne.id() );
                     } else if( !is_water_body( ter( p + point_south_west ) ) ) {
                         ter_set( p, oter_river_c_not_sw.id() );
                     } else if( !is_water_body( ter( p + point_south_east ) ) ) {
                         ter_set( p, oter_river_c_not_se.id() );
                     } else {
                         ter_set( p, oter_river_center.id() );
                     }
                 } else {
                     ter_set( p, oter_river_east.id() );
                 }
             } else {
                 if( is_water_body( ter( p + point_east ) ) ) {
                     ter_set( p, oter_river_south.id() );
                 } else {
                     ter_set( p, oter_river_se.id() );
                 }
             }
         } else {
             if( is_water_body( ter( p + point_south ) ) ) {
                 if( is_water_body( ter( p + point_east ) ) ) {
                     ter_set( p, oter_river_north.id() );
                 } else {
                     ter_set( p, oter_river_ne.id() );
                 }
             } else {
                 if( is_water_body( ter( p + point_east ) ) ) { // Means it's swampy
                     ter_set( p, oter_forest_water.id() );
                 }
             }
         }
     } else {
         if( is_water_body( ter( p + point_north ) ) ) {
             if( is_water_body( ter( p + point_south ) ) ) {
                 if( is_water_body( ter( p + point_east ) ) ) {
                     ter_set( p, oter_river_west.id() );
                 } else { // Should never happen
                     ter_set( p, oter_forest_water.id() );
                 }
             } else {
                 if( is_water_body( ter( p + point_east ) ) ) {
                     ter_set( p, oter_river_sw.id() );
                 } else { // Should never happen
                     ter_set( p, oter_forest_water.id() );
                 }
             }
         } else {
             if( is_water_body( ter( p + point_south ) ) ) {
                 if( is_water_body( ter( p + point_east ) ) ) {
                     ter_set( p, oter_river_nw.id() );
                 } else { // Should never happen
                     ter_set( p, oter_forest_water.id() );
                 }
             } else { // Should never happen
                 ter_set( p, oter_forest_water.id() );
             }
         }
     }
 }
References string_id< T >::id(), is_ot_match(), is_water_body(), OMAPX, OMAPY, oter_forest_water, oter_river_c_not_ne, oter_river_c_not_nw, oter_river_c_not_se, oter_river_c_not_sw, oter_river_center, oter_river_east, oter_river_ne, oter_river_north, oter_river_nw, oter_river_se, oter_river_south, oter_river_sw, oter_river_west, point_east, point_north, point_north_east, point_north_west, point_south, point_south_east, point_south_west, point_west, prefix, ter(), ter_set(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by polish_river().
has_extra()
bool overmap::has_extra (const tripoint_om_omt & p) const
Definition at line 3224 of file overmap.cpp.
 {
     if( p.z() < -OVERMAP_DEPTH || p.z() > OVERMAP_HEIGHT ) {
         return false;
     }
     for( const om_map_extra &i : layer[p.z() + OVERMAP_DEPTH].extras ) {
         if( i.p == p.xy() ) {
             return true;
         }
     }
     return false;
 }
References layer, OVERMAP_DEPTH, OVERMAP_HEIGHT, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
has_note()
bool overmap::has_note (const tripoint_om_omt & p) const
Definition at line 3110 of file overmap.cpp.
 {
     if( p.z() < -OVERMAP_DEPTH || p.z() > OVERMAP_HEIGHT ) {
         return false;
     }
     for( const om_note &i : layer[p.z() + OVERMAP_DEPTH].notes ) {
         if( i.p == p.xy() ) {
             return true;
         }
     }
     return false;
 }
References layer, OVERMAP_DEPTH, OVERMAP_HEIGHT, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
inbounds() [1/2]
static bool overmap::inbounds (const point_om_omt & p, int clearance = 0) inline static
Definition at line 271 of file overmap.h.
{
             return inbounds( tripoint_om_omt( p, 0 ), clearance );
         }
References inbounds().
inbounds() [2/2]
bool overmap::inbounds (const tripoint_om_omt & p, int clearance = 0) static
Returns
Whether
Parameters
p is within desired bounds of the overmap
clearance Minimal distance from the edges of the overmap
Definition at line 3338 of file overmap.cpp.
 {
     static constexpr tripoint_om_omt overmap_boundary_min( 0, 0, -OVERMAP_DEPTH );
     static constexpr tripoint_om_omt overmap_boundary_max( OMAPX, OMAPY, OVERMAP_HEIGHT + 1 );
     static constexpr half_open_cuboid<tripoint_om_omt> overmap_boundaries(
         overmap_boundary_min, overmap_boundary_max );
     half_open_cuboid<tripoint_om_omt> stricter_boundaries = overmap_boundaries;
     stricter_boundaries.shrink( tripoint( clearance, clearance, 0 ) );
     return stricter_boundaries.contains( p );
 }
References half_open_cuboid< Tripoint, >::contains(), OMAPX, OMAPY, OVERMAP_DEPTH, OVERMAP_HEIGHT, cuboid< Tripoint, >::shrink(), and tripoint.
Referenced by joins_tracker::add_joins_for(), build_connection(), build_lab(), mutable_overmap_phase_remainder::can_place(), check_ot(), explored(), inbounds(), is_explored(), is_omt_generated(), lay_out_street(), fixed_overmap_special_data::place(), mutable_overmap_special_data::place(), place_forest_trails(), place_lakes(), place_mongroups(), place_oceans(), place_ravines(), place_river(), place_swamps(), fixed_overmap_special_data::score_rotation_at(), seen(), set_seen(), ter(), ter_set(), and unserialize_omap().
init_layers()
void overmap::init_layers () private
Definition at line 2914 of file overmap.cpp.
 {
     for( int k = 0; k < OVERMAP_LAYERS; ++k ) {
         const oter_id tid = get_default_terrain( k - OVERMAP_DEPTH );
         map_layer &l = layer[k];
         l.terrain.fill( tid );
         l.visible.fill( false );
         l.explored.fill( false );
     }
 }
References map_layer::explored, get_default_terrain(), layer, OVERMAP_DEPTH, OVERMAP_LAYERS, map_layer::terrain, and map_layer::visible.
Referenced by overmap().
insert_npc()
void overmap::insert_npc (const shared_ptr_fast< npc > & who)
Adds the npc to the contained list of npcs (npcs).
Definition at line 3076 of file overmap.cpp.
 {
     npcs.push_back( who );
     g->set_npcs_dirty();
 }
References g, and npcs.
Referenced by overmapbuffer::fix_npcs(), overmapbuffer::insert_npc(), npc::on_move(), and npc::travel_overmap().
is_explored()
bool overmap::is_explored (const tripoint_om_omt & p) const
Definition at line 3042 of file overmap.cpp.
 {
     if( !inbounds( p ) ) {
         return false;
     }
     return layer[p.z() + OVERMAP_DEPTH].explored[p.xy()];
 }
References inbounds(), layer, OVERMAP_DEPTH, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
is_marked_dangerous()
bool overmap::is_marked_dangerous (const tripoint_om_omt & p) const
Definition at line 3124 of file overmap.cpp.
 {
     for( const om_note &i : layer[p.z() + OVERMAP_DEPTH].notes ) {
         if( !i.dangerous ) {
             continue;
         } else if( p.xy() == i.p ) {
             return true;
         }
         const int radius = i.danger_radius;
         if( i.danger_radius == 0 && i.p != p.xy() ) {
             continue;
         }
         int dist = rl_dist( i.p, p.xy() );
         if( dist <= radius ) {
             return true;
         }
     }
     return false;
 }
References layer, OVERMAP_DEPTH, rl_dist(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
is_omt_generated()
bool overmap::is_omt_generated (const tripoint_om_omt & loc) const
Returns whether or not the location has been generated (e.g.
mapgen has run).
Parameters
loc Location to check.
Returns
True if param @loc has been generated.
Definition at line 7336 of file overmap.cpp.
 {
     if( !inbounds( loc ) ) {
         return false;
     }
     // Location is local to this overmap, but we need global submap coordinates
     // for the mapbuffer lookup.
     tripoint_abs_sm global_sm_loc =
         project_to<coords::sm>( project_combine( pos(), loc ) );
     const bool is_generated = MAPBUFFER.lookup_submap( global_sm_loc ) != nullptr;
     return is_generated;
 }
References inbounds(), loc, mapbuffer::lookup_submap(), MAPBUFFER, pos(), and coords::project_combine().
Referenced by lay_out_connection().
is_oter_id_obsolete()
bool overmap::is_oter_id_obsolete (const std::string & oterid) static
Definition at line 3958 of file overmap.cpp.
 {
     return oter_id_migrations.count( oterid ) > 0;
 }
References oter_id_migrations.
Referenced by unserialize(), and unserialize_omap().
join_used_at()
std::string * overmap::join_used_at (const om_pos_dir & p)
Definition at line 2990 of file overmap.cpp.
 {
     auto it = joins_used.find( p );
     if( it == joins_used.end() ) {
         return nullptr;
     }
     return &it->second;
 }
References joins_used.
Referenced by overmapbuffer::join_used_at().
lay_out_connection()
pf::directed_path< point_om_omt > overmap::lay_out_connection (const overmap_connection & connection, const point_om_omt & source, const point_om_omt & dest, int z, bool must_be_unexplored) const private
Definition at line 5952 of file overmap.cpp.
 {
     const pf::two_node_scoring_fn<point_om_omt> estimate =
     [&]( pf::directed_node<point_om_omt> cur, std::optional<pf::directed_node<point_om_omt>> prev ) {
         const oter_id id = ter( tripoint_om_omt( cur.pos, z ) );
         const overmap_connection::subtype *subtype = connection.pick_subtype_for( id );
         if( !subtype ) {
             return pf::node_score::rejected;  // No option for this terrain.
         }
         const bool existing_connection = connection.has( id );
         // Only do this check if it needs to be unexplored and there isn't already a connection.
         if( must_be_unexplored && !existing_connection ) {
             // If this must be unexplored, check if we've already got a submap generated.
             const bool existing_submap = is_omt_generated( tripoint_om_omt( cur.pos, z ) );
             // If there is an existing submap, this area has already been explored and this
             // isn't a valid placement.
             if( existing_submap ) {
                 return pf::node_score::rejected;
             }
         }
         if( existing_connection && id->is_rotatable() && cur.dir != om_direction::type::invalid &&
             !om_direction::are_parallel( id->get_dir(), cur.dir ) ) {
             return pf::node_score::rejected; // Can't intersect.
         }
         if( prev && prev->dir != om_direction::type::invalid && prev->dir != cur.dir ) {
             // Direction has changed.
             const oter_id &prev_id = ter( tripoint_om_omt( prev->pos, z ) );
             const overmap_connection::subtype *prev_subtype = connection.pick_subtype_for( prev_id );
             if( !prev_subtype || !prev_subtype->allows_turns() ) {
                 return pf::node_score::rejected;
             }
         }
         const int dist = subtype->is_orthogonal() ?
                          manhattan_dist( dest, cur.pos ) :
                          trig_dist( dest, cur.pos );
         const int existency_mult = existing_connection ? 1 : 5; // Prefer existing connections.
         return pf::node_score( subtype->basic_cost, existency_mult * dist );
     };
     return pf::greedy_path( source, dest, point_om_omt( OMAPX, OMAPY ), estimate );
 }
References overmap_connection::subtype::allows_turns(), om_direction::are_parallel(), pf::directed_node< Point >::dir, pf::greedy_path(), overmap_connection::has(), base_camps::id, om_direction::invalid, is_omt_generated(), manhattan_dist(), OMAPX, OMAPY, overmap_connection::pick_subtype_for(), pf::directed_node< Point >::pos, pf::node_score::rejected, subtype, ter(), and trig_dist().
Referenced by build_connection().
lay_out_street()
pf::directed_path< point_om_omt > overmap::lay_out_street (const overmap_connection & connection, const point_om_omt & source, om_direction::type dir, size_t len) const private
Definition at line 6023 of file overmap.cpp.
 {
     const tripoint_om_omt from( source, 0 );
     // See if we need to make another one "step" further.
     const tripoint_om_omt en_pos = from + om_direction::displace( dir, len + 1 );
     if( inbounds( en_pos, 1 ) && connection.has( ter( en_pos ) ) ) {
         ++len;
     }
     size_t actual_len = 0;
     while( actual_len < len ) {
         const tripoint_om_omt pos = from + om_direction::displace( dir, actual_len );
         if( !inbounds( pos, 1 ) ) {
             break;  // Don't approach overmap bounds.
         }
         const oter_id &ter_id = ter( pos );
         if( ter_id->is_river() || ter_id->is_ravine() || ter_id->is_ravine_edge() ||
             !connection.pick_subtype_for( ter_id ) ) {
             break;
         }
         bool collided = false;
         int collisions = 0;
         for( int i = -1; i <= 1; i++ ) {
             if( collided ) {
                 break;
             }
             for( int j = -1; j <= 1; j++ ) {
                 const tripoint_om_omt checkp = pos + tripoint( i, j, 0 );
                 if( checkp != pos + om_direction::displace( dir, 1 ) &&
                     checkp != pos + om_direction::displace( om_direction::opposite( dir ), 1 ) &&
                     checkp != pos ) {
                     if( ter( checkp )->get_type_id() == oter_type_road ) {
                         collisions++;
                     }
                 }
             }
             //Stop roads from running right next to each other
             if( collisions >= 3 ) {
                 collided = true;
                 break;
             }
         }
         if( collided ) {
             break;
         }
         ++actual_len;
         if( actual_len > 1 && connection.has( ter_id ) ) {
             break;  // Stop here.
         }
     }
     return straight_path( source, dir, actual_len );
 }
References om_direction::displace(), overmap_connection::has(), inbounds(), om_direction::opposite(), oter_type_road, overmap_connection::pick_subtype_for(), pos(), straight_path(), ter(), and tripoint.
Referenced by build_city_street().
load_legacy_monstergroups()
void overmap::load_legacy_monstergroups (const JsonArray & jsin) private
Definition at line 386 of file savegame.cpp.
 {
     for( JsonObject mongroup_json : jsin ) {
         mongroup new_group;
         new_group.deserialize_legacy( mongroup_json );
         add_mon_group( new_group );
     }
 }
References add_mon_group(), and mongroup::deserialize_legacy().
Referenced by unserialize().
load_monster_groups()
void overmap::load_monster_groups (const JsonArray & jsin) private
Definition at line 366 of file savegame.cpp.
 {
     for( JsonArray mongroup_with_tripoints : jsin ) {
         mongroup new_group;
         new_group.deserialize( mongroup_with_tripoints.next_object() );
         JsonArray tripoints_json = mongroup_with_tripoints.next_array();
         tripoint_om_sm temp;
         for( JsonValue tripoint_json : tripoints_json ) {
             temp.deserialize( tripoint_json );
             new_group.abs_pos = project_combine( pos(), temp );
             add_mon_group( new_group );
         }
         if( mongroup_with_tripoints.has_more() ) {
             mongroup_with_tripoints.throw_error( 2, "Unexpected value for mongroups json" );
         }
     }
 }
References mongroup::abs_pos, add_mon_group(), mongroup::deserialize(), JsonArray::next_array(), pos(), coords::project_combine(), and temp.
Referenced by unserialize().
load_oter_id_migration()
void overmap::load_oter_id_migration (const JsonObject & jo) static
Definition at line 3946 of file overmap.cpp.
 {
     for( const JsonMember &kv : jo.get_object( "oter_ids" ) ) {
         oter_id_migrations.emplace( kv.name(), kv.get_string() );
     }
 }
References JsonObject::get_object(), and oter_id_migrations.
Referenced by DynamicDataLoader::initialize().
mapgen_args()
std::optional< mapgen_arguments > * overmap::mapgen_args (const tripoint_om_omt & p)
Definition at line 2981 of file overmap.cpp.
 {
     auto it = mapgen_args_index.find( p );
     if( it == mapgen_args_index.end() ) {
         return nullptr;
     }
     return it->second;
 }
References mapgen_args_index.
Referenced by overmapbuffer::mapgen_args().
mark_note_dangerous()
void overmap::mark_note_dangerous (const tripoint_om_omt & p, int radius, bool is_dangerous)
Definition at line 3182 of file overmap.cpp.
 {
     for( om_note &i : layer[p.z() + OVERMAP_DEPTH].notes ) {
         if( p.xy() == i.p ) {
             i.dangerous = is_dangerous;
             i.danger_radius = radius;
             return;
         }
     }
 }
References layer, OVERMAP_DEPTH, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by overmapbuffer::mark_note_dangerous().
migrate_oter_ids()
void overmap::migrate_oter_ids (const std::unordered_map< tripoint_om_omt, std::string > & points)
Definition at line 3963 of file overmap.cpp.
 {
     for( const auto&[pos, old_id] : points ) {
         const oter_str_id new_id = oter_str_id( oter_id_migrations.at( old_id ) );
         const tripoint_abs_sm pos_abs = project_to<coords::sm>( project_combine( this->pos(), pos ) );
         if( new_id.is_valid() ) {
             DebugLog( D_WARNING, DC_ALL ) << "migrated oter_id '" << old_id << "' at " << pos_abs
                                           << " to '" << new_id.str() << "'";
             ter_set( pos, new_id );
         } else {
             debugmsg( "oter_id migration defined from '%s' to invalid ter_id '%s'", old_id, new_id.str() );
         }
     }
 }
References D_WARNING, DC_ALL, DebugLog(), debugmsg, string_id< T >::is_valid(), oter_id_migrations, pos(), coords::project_combine(), string_id< T >::str(), and ter_set().
Referenced by unserialize(), and unserialize_omap().
mongroup_check()
bool overmap::mongroup_check (const mongroup & candidate) const
Unit test enablers to check if a given mongroup is present.
Definition at line 3050 of file overmap.cpp.
 {
     tripoint_om_sm relp = candidate.rel_pos();
     const auto matching_range = zg.equal_range( relp );
     return std::find_if( matching_range.first, matching_range.second,
     [candidate]( const std::pair<tripoint_om_sm, mongroup> &match ) {
         // This is extra strict since we're using it to test serialization.
         return candidate.type == match.second.type && candidate.abs_pos == match.second.abs_pos &&
                candidate.population == match.second.population &&
                candidate.target == match.second.target &&
                candidate.interest == match.second.interest &&
                candidate.dying == match.second.dying &&
                candidate.horde == match.second.horde;
     } ) != matching_range.second;
 }
References mongroup::rel_pos(), and zg.
monster_check()
bool overmap::monster_check (const std::pair< tripoint_om_sm, monster > & candidate) const
Definition at line 3066 of file overmap.cpp.
 {
     const auto matching_range = monster_map.equal_range( candidate.first );
     return std::find_if( matching_range.first, matching_range.second,
     [candidate]( const std::pair<tripoint_om_sm, monster> &match ) {
         return candidate.second.pos() == match.second.pos() &&
                candidate.second.type == match.second.type;
     } ) != matching_range.second;
 }
References monster_map.
move_hordes()
void overmap::move_hordes () private
Definition at line 4033 of file overmap.cpp.
 {
     // Prevent hordes to be moved twice by putting them in here after moving.
     decltype( zg ) tmpzg;
     //MOVE ZOMBIE GROUPS
     for( auto it = zg.begin(); it != zg.end(); ) {
         mongroup &mg = it->second;
         if( !mg.horde || mg.behaviour == mongroup::horde_behaviour::nemesis ) {
             //nemesis hordes have their own move function
             ++it;
             continue;
         }
         if( mg.behaviour == mongroup::horde_behaviour::none ) {
             mg.behaviour =
                 one_in( 2 ) ? mongroup::horde_behaviour::city : mongroup::horde_behaviour::roam;
         }
         // Gradually decrease interest.
         mg.dec_interest( 1 );
         if( ( mg.abs_pos.xy() == mg.target ) || mg.interest <= 15 ) {
             mg.wander( *this );
         }
         // Decrease movement chance according to the terrain we're currently on.
         const oter_id &walked_into = ter( project_to<coords::omt>( mg.rel_pos() ) );
         int movement_chance = 1;
         if( walked_into == oter_forest || walked_into == oter_forest_water ) {
             movement_chance = 3;
         } else if( walked_into == oter_forest_thick ) {
             movement_chance = 6;
         } else if( walked_into == oter_river_center ) {
             movement_chance = 10;
         }
         // If the average horde speed is 50% that of normal, then the chance to
         // move should be 1/2 what it would be if the speed was 100%.
         // Since the max speed for a horde is one map space per 2.5 minutes,
         // choose that to be the speed of the fastest horde monster, which is
         // roughly 200 at the time of writing. So a horde with average speed
         // 200 or over will move at max speed, and slower hordes will move less
         // frequently. The average horde speed for regular Z's is around 100,
         // or one space per 5 minutes.
         if( one_in( movement_chance ) && rng( 0, 100 ) < mg.interest && rng( 0, 200 ) < mg.avg_speed() ) {
             // TODO: Handle moving to adjacent overmaps.
             if( mg.abs_pos.x() > mg.target.x() ) {
                 mg.abs_pos.x()--;
             }
             if( mg.abs_pos.x() < mg.target.x() ) {
                 mg.abs_pos.x()++;
             }
             if( mg.abs_pos.y() > mg.target.y() ) {
                 mg.abs_pos.y()--;
             }
             if( mg.abs_pos.y() < mg.target.y() ) {
                 mg.abs_pos.y()++;
             }
             // Erase the group at it's old location, add the group with the new location
             tmpzg.emplace( mg.rel_pos(), mg );
             zg.erase( it++ );
         } else {
             ++it;
         }
     }
     // and now back into the monster group map.
     zg.insert( tmpzg.begin(), tmpzg.end() );
     if( get_option<bool>( "WANDER_SPAWNS" ) ) {
         // Re-absorb zombies into hordes.
         // Scan over monsters outside the player's view and place them back into hordes.
         auto monster_map_it = monster_map.begin();
         while( monster_map_it != monster_map.end() ) {
             const tripoint_om_sm &p = monster_map_it->first;
             monster &this_monster = monster_map_it->second;
             // Only zombies on z-level 0 may join hordes.
             if( p.z() != 0 ) {
                 monster_map_it++;
                 continue;
             }
             // Check if the monster is a zombie.
             const mtype &type = *this_monster.type;
             if(
                 !type.species.count( species_ZOMBIE ) || // Only add zombies to hordes.
                 this_monster.get_speed() <= 30 || // So are very slow zombies, like crawling zombies.
                 !this_monster.will_join_horde( INT_MAX ) || // So are zombies who won't join a horde of any size.
                 !this_monster.mission_ids.empty() // We mustn't delete monsters that are related to missions.
             ) {
                 // Don't delete the monster, just increment the iterator.
                 monster_map_it++;
                 continue;
             }
             // Only monsters in the open (fields, forests, roads) are eligible to wander
             const oter_id &om_here = ter( project_to<coords::omt>( p ) );
             if( !is_ot_match( "field", om_here, ot_match_type::contains ) ) {
                 if( !is_ot_match( "road", om_here, ot_match_type::contains ) ) {
                     if( !is_ot_match( "forest", om_here, ot_match_type::prefix ) ) {
                         if( !is_ot_match( "swamp", om_here, ot_match_type::prefix ) ) {
                             monster_map_it++;
                             continue;
                         }
                     }
                 }
             }
             // Scan for compatible hordes in this area, selecting the largest.
             mongroup *add_to_group = nullptr;
             auto group_bucket = zg.equal_range( p );
             std::vector<monster>::size_type add_to_horde_size = 0;
             std::for_each( group_bucket.first, group_bucket.second,
             [&]( std::pair<const tripoint_om_sm, mongroup> &horde_entry ) {
                 mongroup &horde = horde_entry.second;
                 // We only absorb zombies into GROUP_ZOMBIE hordes
                 if( horde.horde && !horde.monsters.empty() && horde.type == GROUP_ZOMBIE &&
                     horde.monsters.size() > add_to_horde_size ) {
                     add_to_group = &horde;
                     add_to_horde_size = horde.monsters.size();
                 }
             } );
             // Check again if the zombie will join the largest horde, now that we know the accurate size.
             if( this_monster.will_join_horde( add_to_horde_size ) ) {
                 // If there is no horde to add the monster to, create one.
                 if( add_to_group == nullptr ) {
                     tripoint_abs_sm abs_pos = project_combine( pos(), p );
                     mongroup m( GROUP_ZOMBIE, abs_pos, 0 );
                     m.horde = true;
                     m.monsters.push_back( this_monster );
                     m.interest = 0; // Ensures that we will select a new target.
                     add_mon_group( m );
                 } else {
                     add_to_group->monsters.push_back( this_monster );
                 }
             } else { // Bad luck--the zombie would have joined a larger horde, but not this one.  Skip.
                 // Don't delete the monster, just increment the iterator.
                 monster_map_it++;
                 continue;
             }
             // Delete the monster, continue iterating.
             monster_map_it = monster_map.erase( monster_map_it );
         }
     }
 }
References mongroup::abs_pos, add_mon_group(), mongroup::avg_speed(), mongroup::behaviour, mongroup::city, contains, mongroup::dec_interest(), Creature::get_speed(), GROUP_ZOMBIE, mongroup::horde, mongroup::interest, is_ot_match(), monster::mission_ids, monster_map, mongroup::monsters, mongroup::nemesis, mongroup::none, one_in(), oter_forest, oter_forest_thick, oter_forest_water, oter_river_center, pos(), prefix, coords::project_combine(), mongroup::rel_pos(), rng(), mongroup::roam, species_ZOMBIE, mongroup::target, ter(), type, monster::type, mongroup::wander(), monster::will_join_horde(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and zg.
move_nemesis()
void overmap::move_nemesis () private
Definition at line 4184 of file overmap.cpp.
 {
     // Prevent hordes to be moved twice by putting them in here after moving.
     decltype( zg ) tmpzg;
     //cycle through zombie groups, skip non-nemesis hordes
     for( std::multimap<tripoint_om_sm, mongroup>::iterator it = zg.begin(); it != zg.end(); ) {
         mongroup &mg = it->second;
         if( !mg.horde || mg.behaviour != mongroup::horde_behaviour::nemesis ) {
             ++it;
             continue;
         }
         point_abs_om omp;
         tripoint_om_sm local_sm;
         std::tie( omp, local_sm ) = project_remain<coords::om>( mg.abs_pos );
         // Decrease movement chance according to the terrain we're currently on.
         // Hordes will tend toward roads / open fields and path around specials.
         const oter_id &walked_into = ter( project_to<coords::omt>( local_sm ) );
         int movement_chance = 25;
         if( is_ot_match( "road", walked_into, ot_match_type::contains ) ) {
             movement_chance = 1;
         } else if( is_ot_match( "field", walked_into, ot_match_type::contains ) ) {
             movement_chance = 3;
         } else if( is_ot_match( "forest", walked_into, ot_match_type::prefix ) ||
                    is_ot_match( "swamp", walked_into, ot_match_type::prefix ) ||
                    is_ot_match( "bridge", walked_into, ot_match_type::prefix ) ) {
             movement_chance = 6;
         } else if( is_ot_match( "river", walked_into, ot_match_type::prefix ) ) {
             movement_chance = 10;
         }
         //update the nemesis coordinates in abs_sm for movement across overmaps
         if( one_in( movement_chance ) && rng( 0, 200 ) < mg.avg_speed() ) {
             if( mg.abs_pos.x() > mg.nemesis_target.x() ) {
                 mg.abs_pos.x()--;
             }
             if( mg.abs_pos.x() < mg.nemesis_target.x() ) {
                 mg.abs_pos.x()++;
             }
             if( mg.abs_pos.y() > mg.nemesis_target.y() ) {
                 mg.abs_pos.y()--;
             }
             if( mg.abs_pos.y() < mg.nemesis_target.y() ) {
                 mg.abs_pos.y()++;
             }
             //if the nemesis horde is on the same overmap as its target
             //update the horde's om_sm coords from the abs_sm so it can spawn in correctly
             if( project_to<coords::om>( mg.nemesis_target ) == omp ) {
                 // Erase the group at its old location, add the group with the new location
                 tmpzg.emplace( mg.rel_pos(), mg );
                 zg.erase( it++ );
                 //there is only one nemesis horde, so we can stop looping after we move it
                 break;
             }
             //only one nemesis, so we break after moving it
             break;
         } else {
             //and we also break if it doesnt move
             break;
         }
     }
     // and now back into the monster group map.
     zg.insert( tmpzg.begin(), tmpzg.end() );
 }
References mongroup::abs_pos, mongroup::avg_speed(), mongroup::behaviour, contains, mongroup::horde, is_ot_match(), mongroup::nemesis, mongroup::nemesis_target, one_in(), prefix, mongroup::rel_pos(), rng(), ter(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), and zg.
note()
const std::string & overmap::note (const tripoint_om_omt & p) const
Definition at line 3145 of file overmap.cpp.
 {
     static const std::string fallback {};
     if( p.z() < -OVERMAP_DEPTH || p.z() > OVERMAP_HEIGHT ) {
         return fallback;
     }
     const auto &notes = layer[p.z() + OVERMAP_DEPTH].notes;
     const auto it = std::find_if( begin( notes ), end( notes ), [&]( const om_note & n ) {
         return n.p == p.xy();
     } );
     return ( it != std::end( notes ) ) ? it->text : fallback;
 }
References keycode::end, layer, OVERMAP_DEPTH, OVERMAP_HEIGHT, om_note::p, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by find_notes().
note_danger_radius()
int overmap::note_danger_radius (const tripoint_om_omt & p) const
Definition at line 3193 of file overmap.cpp.
 {
     if( p.z() < -OVERMAP_DEPTH || p.z() > OVERMAP_HEIGHT ) {
         return -1;
     }
     const auto &notes = layer[p.z() + OVERMAP_DEPTH].notes;
     const auto it = std::find_if( begin( notes ), end( notes ), [&]( const om_note & n ) {
         return n.p == p.xy();
     } );
     return ( it != std::end( notes ) ) && it->dangerous ? it->danger_radius : -1;
 }
References keycode::end, layer, OVERMAP_DEPTH, OVERMAP_HEIGHT, om_note::p, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
open()
void overmap::open (overmap_special_batch & enabled_specials) private
Definition at line 7195 of file overmap.cpp.
 {
     const cata_path terfilename = overmapbuffer::terrain_filename( loc );
     if( read_from_file_optional( terfilename, [this, &terfilename]( std::istream & is ) {
     unserialize( terfilename, is );
     } ) ) {
         const cata_path plrfilename = overmapbuffer::player_filename( loc );
         read_from_file_optional( plrfilename, [this, &plrfilename]( std::istream & is ) {
             unserialize_view( plrfilename, is );
         } );
     } else { // No map exists!  Prepare neighbors, and generate one.
         std::vector<const overmap *> pointers;
         // Fetch south and north
         for( int i = -1; i <= 1; i += 2 ) {
             pointers.push_back( overmap_buffer.get_existing( loc + point( 0, i ) ) );
         }
         // Fetch east and west
         for( int i = -1; i <= 1; i += 2 ) {
             pointers.push_back( overmap_buffer.get_existing( loc + point( i, 0 ) ) );
         }
         // pointers looks like (north, south, west, east)
         generate( pointers[0], pointers[3], pointers[1], pointers[2], enabled_specials );
     }
 }
References generate(), overmapbuffer::get_existing(), loc, overmap_buffer, overmapbuffer::player_filename(), read_from_file_optional(), overmapbuffer::terrain_filename(), unserialize(), and unserialize_view().
Referenced by populate().
operator=()
overmap& overmap::operator= (const overmap &) default
overmap_special_at()
std::optional< overmap_special_id > overmap::overmap_special_at (const tripoint_om_omt & p) const
Definition at line 6307 of file overmap.cpp.
 {
     auto it = overmap_special_placements.find( p );
     if( it == overmap_special_placements.end() ) {
         return std::nullopt;
     }
     return it->second;
 }
References overmap_special_placements.
Referenced by overmapbuffer::overmap_special_at().
pick_random_building_to_place()
overmap_special_id overmap::pick_random_building_to_place (int town_dist, int town_size) const private
Definition at line 5557 of file overmap.cpp.
 {
     const city_settings &city_spec = settings->city_spec;
     int shop_radius = city_spec.shop_radius;
     int park_radius = city_spec.park_radius;
     int shop_sigma = city_spec.shop_sigma;
     int park_sigma = city_spec.park_sigma;
     //Normally distribute shops and parks
     //Clamp at 1/2 radius to prevent houses from spawning in the city center.
     //Parks are nearly guaranteed to have a non-zero chance of spawning anywhere in the city.
     int shop_normal = shop_radius;
     if( shop_sigma > 0 ) {
         shop_normal = std::max( shop_normal, static_cast<int>( normal_roll( shop_radius, shop_sigma ) ) );
     }
     int park_normal = park_radius;
     if( park_sigma > 0 ) {
         park_normal = std::max( park_normal, static_cast<int>( normal_roll( park_radius, park_sigma ) ) );
     }
     auto building_type_to_pick = [&]() {
         if( shop_normal > town_dist ) {
             return std::mem_fn( &city_settings::pick_shop );
         } else if( park_normal > town_dist ) {
             return std::mem_fn( &city_settings::pick_park );
         } else {
             return std::mem_fn( &city_settings::pick_house );
         }
     };
     auto pick_building = building_type_to_pick();
     overmap_special_id ret;
     do {
         ret = pick_building( city_spec );
     } while( !ret->get_constraints().city_size.contains( town_size ) );
     return ret;
 }
References regional_settings::city_spec, max(), normal_roll(), city_settings::park_radius, city_settings::park_sigma, city_settings::pick_house(), city_settings::pick_park(), city_settings::pick_shop(), cata::hash64_detail::ret, settings, city_settings::shop_radius, and city_settings::shop_sigma.
Referenced by place_building().
place_building()
void overmap::place_building (const tripoint_om_omt & p, om_direction::type dir, const city & town) private
Definition at line 5594 of file overmap.cpp.
 {
     const tripoint_om_omt building_pos = p + om_direction::displace( dir );
     const om_direction::type building_dir = om_direction::opposite( dir );
     const int town_dist = ( trig_dist( building_pos.xy(), town.pos ) * 100 ) / std::max( town.size, 1 );
     for( size_t retries = 10; retries > 0; --retries ) {
         const overmap_special_id building_tid = pick_random_building_to_place( town_dist, town.size );
         if( can_place_special( *building_tid, building_pos, building_dir, false ) ) {
             place_special( *building_tid, building_pos, building_dir, town, false, false );
             break;
         }
     }
 }
References can_place_special(), om_direction::displace(), max(), om_direction::opposite(), pick_random_building_to_place(), place_special(), city::pos, city::size, trig_dist(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by build_city_street().
place_cities()
void overmap::place_cities () private
Definition at line 5438 of file overmap.cpp.
 {
     int op_city_spacing = get_option<int>( "CITY_SPACING" );
     int op_city_size = get_option<int>( "CITY_SIZE" );
     int max_urbanity = get_option<int>( "OVERMAP_MAXIMUM_URBANITY" );
     if( op_city_size <= 0 ) {
         return;
     }
     // make sure city size adjust is never high enough to drop op_city_size below 2
     int city_size_adjust = std::min( urbanity -  static_cast<int>( forestosity / 2.0f ),
                                      -1 * op_city_size + 2 );
     int city_space_adjust = urbanity / 2;
     int max_city_size = std::min( op_city_size + city_size_adjust, op_city_size * max_urbanity );
     if( max_city_size < op_city_size ) {
         // funny things happen if max_city_size is less than op_city_size.
         max_city_size = op_city_size;
     }
     if( op_city_spacing > 0 ) {
         city_space_adjust = std::min( city_space_adjust, op_city_spacing - 2 );
         op_city_spacing = op_city_spacing - city_space_adjust + static_cast<int>( forestosity );
     }
     // make sure not to get too extreme on the spacing if you go way far.
     op_city_spacing = std::min( op_city_spacing, 10 );
     // spacing dictates how much of the map is covered in cities
     //   city  |  cities  |   size N cities per overmap
     // spacing | % of map |  2  |  4  |  8  |  12 |  16
     //     0   |   ~99    |2025 | 506 | 126 |  56 |  31
     //     1   |    50    |1012 | 253 |  63 |  28 |  15
     //     2   |    25    | 506 | 126 |  31 |  14 |   7
     //     3   |    12    | 253 |  63 |  15 |   7 |   3
     //     4   |     6    | 126 |  31 |   7 |   3 |   1
     //     5   |     3    |  63 |  15 |   3 |   1 |   0
     //     6   |     1    |  31 |   7 |   1 |   0 |   0
     //     7   |     0    |  15 |   3 |   0 |   0 |   0
     //     8   |     0    |   7 |   1 |   0 |   0 |   0
     const double omts_per_overmap = OMAPX * OMAPY;
     const double city_map_coverage_ratio = 1.0 / std::pow( 2.0, op_city_spacing );
     const double omts_per_city = ( op_city_size * 2 + 1 ) * ( max_city_size * 2 + 1 ) * 3 / 4.0;
     // how many cities on this overmap?
     int num_cities_on_this_overmap = 0;
     std::vector<city> cities_to_place;
     for( const city &c : city::get_all() ) {
         if( c.pos_om == pos() ) {
             num_cities_on_this_overmap++;
             cities_to_place.emplace_back( c );
         }
     }
     const bool use_random_cities = city::get_all().empty();
     // Random cities if no cities were defined in regional settings
     if( use_random_cities ) {
         num_cities_on_this_overmap = roll_remainder( omts_per_overmap * city_map_coverage_ratio /
                                      omts_per_city );
     }
     const overmap_connection_id &overmap_connection_intra_city_road =
         settings->overmap_connection.intra_city_road_connection;
     const overmap_connection &local_road( *overmap_connection_intra_city_road );
     // if there is only a single free tile, the probability of NOT finding it after MAX_PLACEMENT_ATTEMPTS attempts
     // is (1 - 1/(OMAPX * OMAPY))^MAX_PLACEMENT_ATTEMPTS  36% for the OMAPX=OMAPY=180 and MAX_PLACEMENT_ATTEMPTS=OMAPX * OMAPY
     const int MAX_PLACEMENT_ATTEMPTS = 50;//OMAPX * OMAPY;
     int placement_attempts = 0;
     // place a seed for num_cities_on_this_overmap cities, and maybe one more
     while( cities.size() < static_cast<size_t>( num_cities_on_this_overmap ) &&
            placement_attempts < MAX_PLACEMENT_ATTEMPTS ) {
         placement_attempts++;
         tripoint_om_omt p;
         city tmp;
         tmp.pos_om = pos();
         if( use_random_cities ) {
             // randomly make some cities smaller or larger
             int size = rng( op_city_size - 1, max_city_size );
             if( one_in( 3 ) ) { // 33% tiny
                 size = size * 1 / 3;
             } else if( one_in( 2 ) ) { // 33% small
                 size = size * 2 / 3;
             } else if( one_in( 2 ) ) { // 17% large
                 size = size * 3 / 2;
             } else {             // 17% huge
                 size = size * 2;
             }
             // Ensure that cities are at least size 2, as city of size 1 is just a crossroad with no buildings at all
             size = std::max( size, 2 );
             size = std::min( size, 55 );
             // TODO: put cities closer to the edge when they can span overmaps
             // don't draw cities across the edge of the map, they will get clipped
             point_om_omt c( rng( size - 1, OMAPX - size ), rng( size - 1, OMAPY - size ) );
             p = tripoint_om_omt( c, 0 );
             if( ter( p ) == settings->default_oter[OVERMAP_DEPTH] ) {
                 placement_attempts = 0;
                 ter_set( p, oter_road_nesw ); // every city starts with an intersection
                 tmp.pos = p.xy();
                 tmp.size = size;
             }
         } else {
             placement_attempts = 0;
             tmp = random_entry( cities_to_place );
             p = tripoint_om_omt( tmp.pos, 0 );
             ter_set( tripoint_om_omt( tmp.pos, 0 ), oter_road_nesw );
         }
         if( placement_attempts == 0 ) {
             cities.push_back( tmp );
             const om_direction::type start_dir = om_direction::random();
             om_direction::type cur_dir = start_dir;
             do {
                 build_city_street( local_road, tmp.pos, tmp.size, cur_dir, tmp );
             } while( ( cur_dir = om_direction::turn_right( cur_dir ) ) != start_dir );
         }
     }
 }
References build_city_street(), c, cities, regional_settings::default_oter, forestosity, city::get_all(), overmap_connection_settings::intra_city_road_connection, max(), min(), OMAPX, OMAPY, one_in(), oter_road_nesw, regional_settings::overmap_connection, OVERMAP_DEPTH, city::pos, pos(), city::pos_om, om_direction::random(), random_entry(), rng(), roll_remainder(), settings, city::size, om_lines::size, ter(), ter_set(), om_direction::turn_right(), urbanity, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by generate().
place_forest_trailheads()
void overmap::place_forest_trailheads () private
Definition at line 4504 of file overmap.cpp.
 {
     // No trailheads if there are no cities.
     const int city_size = get_option<int>( "CITY_SIZE" );
     if( city_size <= 0 ) {
         return;
     }
     // Trailheads may be placed if all of the following are true:
     // 1. we're at a forest_trail_end_north/south/west/east,
     // 2. we're within trailhead_road_distance from an existing road
     // 3. rng rolls a success for our trailhead_chance from the configuration
     // 4. the trailhead special we've picked can be placed in the selected location
     const auto trailhead_close_to_road = [&]( const tripoint_om_omt & trailhead ) {
         bool close = false;
         for( const tripoint_om_omt &nearby_point : closest_points_first(
                  trailhead,
                  settings->forest_trail.trailhead_road_distance
              ) ) {
             if( check_ot( "road", ot_match_type::contains, nearby_point ) ) {
                 close = true;
             }
         }
         return close;
     };
     const auto try_place_trailhead_special = [&]( const tripoint_om_omt & trail_end,
     const om_direction::type & dir ) {
         overmap_special_id trailhead = settings->forest_trail.trailheads.pick();
         if( one_in( settings->forest_trail.trailhead_chance ) &&
             trailhead_close_to_road( trail_end ) &&
             can_place_special( *trailhead, trail_end, dir, false ) ) {
             const city &nearest_city = get_nearest_city( trail_end );
             place_special( *trailhead, trail_end, dir, nearest_city, false, false );
         }
     };
     for( int i = 2; i < OMAPX - 2; i++ ) {
         for( int j = 2; j < OMAPY - 2; j++ ) {
             const tripoint_om_omt p( i, j, 0 );
             oter_id oter = ter( p );
             if( is_ot_match( "forest_trail_end", oter, ot_match_type::prefix ) ) {
                 try_place_trailhead_special( p, static_cast<om_direction::type>( oter->get_rotation() ) );
             }
         }
     }
 }
References can_place_special(), check_ot(), close(), closest_points_first(), contains, regional_settings::forest_trail, get_nearest_city(), oter_t::get_rotation(), is_ot_match(), OMAPX, OMAPY, one_in(), building_bin::pick(), place_special(), prefix, settings, ter(), forest_trail_settings::trailhead_chance, forest_trail_settings::trailhead_road_distance, and forest_trail_settings::trailheads.
Referenced by generate().
place_forest_trails()
void overmap::place_forest_trails () private
Definition at line 4379 of file overmap.cpp.
 {
     std::unordered_set<point_om_omt> visited;
     const auto is_forest = [&]( const point_om_omt & p ) {
         if( !inbounds( p, 1 ) ) {
             return false;
         }
         const oter_id current_terrain = ter( tripoint_om_omt( p, 0 ) );
         return current_terrain == oter_forest || current_terrain == oter_forest_thick ||
                current_terrain == oter_forest_water;
     };
     const forest_trail_settings &forest_trail = settings->forest_trail;
     for( int i = 0; i < OMAPX; i++ ) {
         for( int j = 0; j < OMAPY; j++ ) {
             tripoint_om_omt seed_point( i, j, 0 );
             oter_id oter = ter( seed_point );
             if( !is_ot_match( "forest", oter, ot_match_type::prefix ) ) {
                 continue;
             }
             // If we've already visited this point, we don't need to
             // process it since it's already part of another forest.
             if( visited.find( seed_point.xy() ) != visited.end() ) {
                 continue;
             }
             // Get the contiguous forest from this point.
             std::vector<point_om_omt> forest_points =
                 ff::point_flood_fill_4_connected( seed_point.xy(), visited, is_forest );
             // If we don't have enough points to build a trail, move on.
             if( forest_points.empty() ||
                 forest_points.size() < static_cast<std::vector<point>::size_type>
                 ( forest_trail.minimum_forest_size ) ) {
                 continue;
             }
             // If we don't rng a forest based on our settings, move on.
             if( !one_in( forest_trail.chance ) ) {
                 continue;
             }
             // Get the north and south most points in the forest.
             auto north_south_most = std::minmax_element( forest_points.begin(),
             forest_points.end(), []( const point_om_omt & lhs, const point_om_omt & rhs ) {
                 return lhs.y() < rhs.y();
             } );
             // Get the west and east most points in the forest.
             auto west_east_most = std::minmax_element( forest_points.begin(),
             forest_points.end(), []( const point_om_omt & lhs, const point_om_omt & rhs ) {
                 return lhs.x() < rhs.x();
             } );
             // We'll use these points later as points that are guaranteed to be
             // at a boundary and will form a good foundation for the trail system.
             point_om_omt northmost = *north_south_most.first;
             point_om_omt southmost = *north_south_most.second;
             point_om_omt westmost = *west_east_most.first;
             point_om_omt eastmost = *west_east_most.second;
             // Do a simplistic calculation of the center of the forest (rather than
             // calculating the actual centroid--it's not that important) to have another
             // good point to form the foundation of the trail system.
             point_om_omt center( westmost.x() + ( eastmost.x() - westmost.x() ) / 2,
                                  northmost.y() + ( southmost.y() - northmost.y() ) / 2 );
             point_om_omt center_point = center;
             // Because we didn't do the centroid of a concave polygon, there's no
             // guarantee that our center point is actually within the bounds of the
             // forest. Just find the point within our set that is closest to our
             // center point and use that.
             point_om_omt actual_center_point =
                 *std::min_element( forest_points.begin(), forest_points.end(),
             [&center_point]( const point_om_omt & lhs, const point_om_omt & rhs ) {
                 return square_dist( lhs, center_point ) < square_dist( rhs,
                         center_point );
             } );
             // Figure out how many random points we'll add to our trail system, based on the forest
             // size and our configuration.
             int max_random_points = forest_trail.random_point_min + forest_points.size() /
                                     forest_trail.random_point_size_scalar;
             max_random_points = std::min( max_random_points, forest_trail.random_point_max );
             // Start with the center...
             std::vector<point_om_omt> chosen_points = { actual_center_point };
             // ...and then add our random points.
             int random_point_count = 0;
             std::shuffle( forest_points.begin(), forest_points.end(), rng_get_engine() );
             for( auto &random_point : forest_points ) {
                 if( random_point_count >= max_random_points ) {
                     break;
                 }
                 random_point_count++;
                 chosen_points.emplace_back( random_point );
             }
             // Add our north/south/west/east-most points based on our configuration.
             if( one_in( forest_trail.border_point_chance ) ) {
                 chosen_points.emplace_back( northmost );
             }
             if( one_in( forest_trail.border_point_chance ) ) {
                 chosen_points.emplace_back( southmost );
             }
             if( one_in( forest_trail.border_point_chance ) ) {
                 chosen_points.emplace_back( westmost );
             }
             if( one_in( forest_trail.border_point_chance ) ) {
                 chosen_points.emplace_back( eastmost );
             }
             // Finally, connect all the points and make a forest trail out of them.
             const overmap_connection_id &overmap_connection_forest_trail =
                 settings->overmap_connection.trail_connection;
             connect_closest_points( chosen_points, 0, *overmap_connection_forest_trail );
         }
     }
 }
References forest_trail_settings::border_point_chance, center, forest_trail_settings::chance, connect_closest_points(), regional_settings::forest_trail, inbounds(), is_ot_match(), min(), forest_trail_settings::minimum_forest_size, OMAPX, OMAPY, one_in(), oter_forest, oter_forest_thick, oter_forest_water, regional_settings::overmap_connection, ff::point_flood_fill_4_connected(), prefix, random_point(), forest_trail_settings::random_point_max, forest_trail_settings::random_point_min, forest_trail_settings::random_point_size_scalar, rng_get_engine(), settings, ter(), overmap_connection_settings::trail_connection, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by generate().
place_forests()
void overmap::place_forests () private
Definition at line 4553 of file overmap.cpp.
 {
     const oter_id default_oter_id( settings->default_oter[OVERMAP_DEPTH] );
     const om_noise::om_noise_layer_forest f( global_base_point(), g->get_seed() );
     for( int x = 0; x < OMAPX; x++ ) {
         for( int y = 0; y < OMAPY; y++ ) {
             const tripoint_om_omt p( x, y, 0 );
             const oter_id &oter = ter( p );
             // At this point in the process, we only want to consider converting the terrain into
             // a forest if it's currently the default terrain type (e.g. a field).
             if( oter != default_oter_id ) {
                 continue;
             }
             const float n = f.noise_at( p.xy() );
             // If the noise here meets our threshold, turn it into a forest.
             if( n + forest_size_adjust > settings->overmap_forest.noise_threshold_forest_thick ) {
                 ter_set( p, oter_forest_thick );
             } else if( n + forest_size_adjust > settings->overmap_forest.noise_threshold_forest ) {
                 ter_set( p, oter_forest );
             }
         }
     }
 }
References regional_settings::default_oter, forest_size_adjust, g, global_base_point(), om_noise::om_noise_layer_forest::noise_at(), overmap_forest_settings::noise_threshold_forest, overmap_forest_settings::noise_threshold_forest_thick, OMAPX, OMAPY, oter_forest, oter_forest_thick, OVERMAP_DEPTH, regional_settings::overmap_forest, settings, ter(), ter_set(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by generate().
place_lakes()
void overmap::place_lakes () private
Definition at line 4582 of file overmap.cpp.
 {
     const om_noise::om_noise_layer_lake f( global_base_point(), g->get_seed() );
     const auto is_lake = [&]( const point_om_omt & p ) {
         // credit to ehughsbaird for thinking up this inbounds solution to infinite flood fill lag.
         bool inbounds = p.x() > -5 && p.y() > -5 && p.x() < OMAPX + 5 && p.y() < OMAPY + 5;
         if( !inbounds ) {
             return false;
         }
         return f.noise_at( p ) > settings->overmap_lake.noise_threshold_lake;
     };
     const oter_id lake_surface( "lake_surface" );
     const oter_id lake_shore( "lake_shore" );
     const oter_id lake_water_cube( "lake_water_cube" );
     const oter_id lake_bed( "lake_bed" );
     // We'll keep track of our visited lake points so we don't repeat the work.
     std::unordered_set<point_om_omt> visited;
     for( int i = 0; i < OMAPX; i++ ) {
         for( int j = 0; j < OMAPY; j++ ) {
             point_om_omt seed_point( i, j );
             if( visited.find( seed_point ) != visited.end() ) {
                 continue;
             }
             // It's a lake if it exceeds the noise threshold defined in the region settings.
             if( !is_lake( seed_point ) ) {
                 continue;
             }
             // We're going to flood-fill our lake so that we can consider the entire lake when evaluating it
             // for placement, even when the lake runs off the edge of the current overmap.
             std::vector<point_om_omt> lake_points =
                 ff::point_flood_fill_4_connected( seed_point, visited, is_lake );
             // If this lake doesn't exceed our minimum size threshold, then skip it. We can use this to
             // exclude the tiny lakes that don't provide interesting map features and exist mostly as a
             // noise artifact.
             if( lake_points.size() < static_cast<std::vector<point>::size_type>
                 ( settings->overmap_lake.lake_size_min ) ) {
                 continue;
             }
             // Build a set of "lake" points. We're actually going to combine both the lake points
             // we just found AND all of the rivers on the map, because we want our lakes to write
             // over any rivers that are placed already. Note that the assumption here is that river
             // overmap generation (e.g. place_rivers) runs BEFORE lake overmap generation.
             std::unordered_set<point_om_omt> lake_set;
             for( auto &p : lake_points ) {
                 lake_set.emplace( p );
             }
             for( int x = 0; x < OMAPX; x++ ) {
                 for( int y = 0; y < OMAPY; y++ ) {
                     const tripoint_om_omt p( x, y, 0 );
                     if( ter( p )->is_river() ) {
                         lake_set.emplace( p.xy() );
                     }
                 }
             }
             // Iterate through all of our lake points, rejecting the ones that are out of bounds. For
             // those that are inbounds, look at the 8 adjacent locations and see if they are also part
             // of our lake points set. If they are, that means that this location is entirely surrounded
             // by lake and should be considered a lake surface. If at least one adjacent location is not
             // part of this lake points set, that means this location should be considered a lake shore.
             // Either way, make the determination and set the overmap terrain.
             for( auto &p : lake_points ) {
                 if( !inbounds( p ) ) {
                     continue;
                 }
                 bool shore = false;
                 for( int ni = -1; ni <= 1 && !shore; ni++ ) {
                     for( int nj = -1; nj <= 1 && !shore; nj++ ) {
                         const point_om_omt n = p + point( ni, nj );
                         if( lake_set.find( n ) == lake_set.end() ) {
                             shore = true;
                         }
                     }
                 }
                 ter_set( tripoint_om_omt( p, 0 ), shore ? lake_shore : lake_surface );
                 // If this is not a shore, we'll make our subsurface lake cubes and beds.
                 if( !shore ) {
                     for( int z = -1; z > settings->overmap_lake.lake_depth; z-- ) {
                         ter_set( tripoint_om_omt( p, z ), lake_water_cube );
                     }
                     ter_set( tripoint_om_omt( p, settings->overmap_lake.lake_depth ), lake_bed );
                 }
             }
             // We're going to attempt to connect some points on this lake to the nearest river.
             const auto connect_lake_to_closest_river =
             [&]( const point_om_omt & lake_connection_point ) {
                 int closest_distance = -1;
                 point_om_omt closest_point;
                 for( int x = 0; x < OMAPX; x++ ) {
                     for( int y = 0; y < OMAPY; y++ ) {
                         const tripoint_om_omt p( x, y, 0 );
                         if( !ter( p )->is_river() ) {
                             continue;
                         }
                         const int distance = square_dist( lake_connection_point, p.xy() );
                         if( distance < closest_distance || closest_distance < 0 ) {
                             closest_point = p.xy();
                             closest_distance = distance;
                         }
                     }
                 }
                 if( closest_distance > 0 ) {
                     place_river( closest_point, lake_connection_point );
                 }
             };
             // Get the north and south most points in our lake.
             auto north_south_most = std::minmax_element( lake_points.begin(), lake_points.end(),
             []( const point_om_omt & lhs, const point_om_omt & rhs ) {
                 return lhs.y() < rhs.y();
             } );
             point_om_omt northmost = *north_south_most.first;
             point_om_omt southmost = *north_south_most.second;
             // It's possible that our northmost/southmost points in the lake are not on this overmap, because our
             // lake may extend across multiple overmaps.
             if( inbounds( northmost ) ) {
                 connect_lake_to_closest_river( northmost );
             }
             if( inbounds( southmost ) ) {
                 connect_lake_to_closest_river( southmost );
             }
         }
     }
 }
References g, global_base_point(), inbounds(), is_river(), overmap_lake_settings::lake_depth, lake_shore, overmap_lake_settings::lake_size_min, om_noise::om_noise_layer_lake::noise_at(), overmap_lake_settings::noise_threshold_lake, OMAPX, OMAPY, regional_settings::overmap_lake, place_river(), point, ff::point_flood_fill_4_connected(), settings, shore, square_dist(), ter(), ter_set(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by generate().
place_mongroups()
void overmap::place_mongroups () private
Definition at line 6936 of file overmap.cpp.
 {
     // Cities can be full of zombies
     int city_spawn_threshold = get_option<int>( "SPAWN_CITY_HORDE_THRESHOLD" );
     if( city_spawn_threshold > -1 ) {
         int city_spawn_chance = get_option<int>( "SPAWN_CITY_HORDE_SMALL_CITY_CHANCE" );
         float city_spawn_scalar = get_option<float>( "SPAWN_CITY_HORDE_SCALAR" );
         float city_spawn_spread = get_option<float>( "SPAWN_CITY_HORDE_SPREAD" );
         float spawn_density = get_option<float>( "SPAWN_DENSITY" );
         for( city &elem : cities ) {
             if( elem.size > city_spawn_threshold || !one_in( city_spawn_chance ) ) {
                 // with the default numbers (80 scalar, 1 density), a size 16 city
                 // will produce 1280 zombies.
                 int desired_zombies = elem.size * city_spawn_scalar * spawn_density;
                 float city_effective_radius = elem.size * city_spawn_spread;
                 int city_distance_increment = std::ceil( city_effective_radius / 4 );
                 tripoint_abs_omt city_center = project_combine( elem.pos_om, tripoint_om_omt( elem.pos, 0 ) );
                 std::vector<tripoint_abs_sm> submap_list;
                 // gather all of the points in range to test for viable placement of hordes.
                 for( tripoint_om_omt const &temp_omt : points_in_radius( tripoint_om_omt( elem.pos, 0 ),
                         static_cast<int>( city_effective_radius ), 0 ) ) {
                     // running too close to the edge of the overmap can get us cascading mapgen
                     if( inbounds( temp_omt, 2 ) ) {
                         tripoint_abs_omt target_omt = project_combine( elem.pos_om, temp_omt );
                         // right now we're only placing city horde spawns on roads, for simplicity.
                         // this can be replaced with an OMT flag for later for better flexibility.
                         if( overmap_buffer.ter( target_omt )->get_type_id() == oter_type_road ) {
                             tripoint_abs_sm this_sm = project_to<coords::sm>( target_omt );
                             // for some reason old style spawns are submap-aligned.
                             // get all four quadrants for better distribution.
                             std::vector<tripoint_abs_sm> local_sm_list;
                             local_sm_list.push_back( this_sm );
                             local_sm_list.push_back( this_sm + point_east );
                             local_sm_list.push_back( this_sm + point_south );
                             local_sm_list.push_back( this_sm + point_south_east );
                             // shuffle, then prune submaps based on distance from city center
                             // this should let us concentrate hordes closer to the center.
                             // the shuffling is so they aren't all aligned consistently.
                             int new_size = 4 - ( trig_dist( target_omt, city_center ) / city_distance_increment );
                             if( new_size > 0 ) {
                                 std::shuffle( local_sm_list.begin(), local_sm_list.end(), rng_get_engine() );
                                 local_sm_list.resize( new_size );
                                 submap_list.insert( submap_list.end(), local_sm_list.begin(), local_sm_list.end() );
                             }
                         }
                     }
                 }
                 if( submap_list.empty() ) {
                     // somehow the city has no roads. this shouldn't happen.
                     add_msg_debug( debugmode::DF_OVERMAP,
                                    "tried to add zombie hordes to city %s centered at omt %s, but there were no roads!",
                                    elem.name, city_center.to_string_writable() );
                     continue;
                 }
                 add_msg_debug( debugmode::DF_OVERMAP, "adding %i zombies in hordes to city %s centered at omt %s.",
                                desired_zombies, elem.name, city_center.to_string_writable() );
                 // if there aren't enough roads, we'll just reuse them, re-shuffled.
                 while( desired_zombies > 0 ) {
                     std::shuffle( submap_list.begin(), submap_list.end(), rng_get_engine() );
                     for( tripoint_abs_sm const &s : submap_list ) {
                         if( desired_zombies <= 0 ) {
                             break;
                         }
                         mongroup m( GROUP_ZOMBIE, s, desired_zombies > 10 ? 10 : desired_zombies );
                         // with wander_spawns (aka wandering hordes) off, these become 'normal'
                         // zombie spawns and behave like ants, triffids, fungals, etc.
                         // they won't try very hard to get placed in the world, so there will
                         // probably be fewer zombies than expected.
                         m.horde = true;
                         if( get_option<bool>( "WANDER_SPAWNS" ) ) {
                             m.wander( *this );
                         }
                         add_mon_group( m );
                         desired_zombies -= 10;
                     }
                 }
             }
         }
     }
     if( get_option<bool>( "DISABLE_ANIMAL_CLASH" ) ) {
         // Figure out where swamps are, and place swamp monsters
         for( int x = 3; x < OMAPX - 3; x += 7 ) {
             for( int y = 3; y < OMAPY - 3; y += 7 ) {
                 int swamp_count = 0;
                 for( int sx = x - 3; sx <= x + 3; sx++ ) {
                     for( int sy = y - 3; sy <= y + 3; sy++ ) {
                         if( ter( { sx, sy, 0 } ) == oter_forest_water ) {
                             swamp_count += 2;
                         }
                     }
                 }
                 if( swamp_count >= 25 ) {
                     tripoint_om_omt p( x, y, 0 );
                     float norm_factor = std::abs( GROUP_SWAMP->freq_total / 1000.0f );
                     unsigned int pop =
                         std::round( norm_factor * rng( swamp_count * 8, swamp_count * 25 ) );
                     spawn_mon_group(
                         mongroup(
                             GROUP_SWAMP, project_combine( pos(), project_to<coords::sm>( p ) ),
                             pop ), 3 );
                 }
             }
         }
     }
     // Figure out where rivers and lakes are, and place appropriate critters
     for( int x = 3; x < OMAPX - 3; x += 7 ) {
         for( int y = 3; y < OMAPY - 3; y += 7 ) {
             int river_count = 0;
             for( int sx = x - 3; sx <= x + 3; sx++ ) {
                 for( int sy = y - 3; sy <= y + 3; sy++ ) {
                     if( is_lake_or_river( ter( { sx, sy, 0 } ) ) ) {
                         river_count++;
                     }
                 }
             }
             if( river_count >= 25 && is_lake_or_river( ter( { x, y, 0 } ) ) ) {
                 tripoint_om_omt p( x, y, 0 );
                 float norm_factor = std::abs( GROUP_RIVER->freq_total / 1000.0f );
                 unsigned int pop =
                     std::round( norm_factor * rng( river_count * 8, river_count * 25 ) );
                 spawn_mon_group(
                     mongroup( GROUP_RIVER, project_combine( pos(), project_to<coords::sm>( p ) ),
                               pop ), 3 );
             }
         }
     }
     // Now place ocean mongroup. Weights may need to be altered.
     const om_noise::om_noise_layer_ocean f( global_base_point(), g->get_seed() );
     const point_abs_om this_om = pos();
     const int northern_ocean = settings->overmap_ocean.ocean_start_north;
     const int eastern_ocean = settings->overmap_ocean.ocean_start_east;
     const int western_ocean = settings->overmap_ocean.ocean_start_west;
     const int southern_ocean = settings->overmap_ocean.ocean_start_south;
     // noise threshold adjuster for deep ocean. Increase to make deep ocean move further from the shore.
     constexpr float DEEP_OCEAN_THRESHOLD_ADJUST = 1.25;
     // code taken from place_oceans, but noise threshold increased to determine "deep ocean".
     const auto is_deep_ocean = [&]( const point_om_omt & p ) {
         // credit to ehughsbaird for thinking up this inbounds solution to infinite flood fill lag.
         if( northern_ocean == 0 && eastern_ocean == 0 && western_ocean == 0 && southern_ocean == 0 ) {
             // you know you could just turn oceans off in global_settings.json right?
             return false;
         }
         bool inbounds = p.x() > -5 && p.y() > -5 && p.x() < OMAPX + 5 && p.y() < OMAPY + 5;
         if( !inbounds ) {
             return false;
         }
         float ocean_adjust = calculate_ocean_gradient( p, this_om );
         if( ocean_adjust == 0.0f ) {
             // It's too soon!  Too soon for an ocean!!  ABORT!!!
             return false;
         }
         return f.noise_at( p ) + ocean_adjust > settings->overmap_ocean.noise_threshold_ocean *
                DEEP_OCEAN_THRESHOLD_ADJUST;
     };
     for( int x = 3; x < OMAPX - 3; x += 7 ) {
         for( int y = 3; y < OMAPY - 3; y += 7 ) {
             int ocean_count = 0;
             for( int sx = x - 3; sx <= x + 3; sx++ ) {
                 for( int sy = y - 3; sy <= y + 3; sy++ ) {
                     if( is_ocean( ter( { sx, sy, 0 } ) ) ) {
                         ocean_count++;
                     }
                 }
             }
             bool am_deep = is_deep_ocean( { x, y } );
             if( ocean_count >= 25 ) {
                 tripoint_om_omt p( x, y, 0 );
                 if( am_deep ) {
                     float norm_factor = std::abs( GROUP_OCEAN_DEEP->freq_total / 1000.0f );
                     unsigned int pop =
                         std::round( norm_factor * rng( ocean_count * 8, ocean_count * 25 ) );
                     spawn_mon_group(
                         mongroup( GROUP_OCEAN_DEEP, project_combine( pos(), project_to<coords::sm>( p ) ),
                                   pop ), 3 );
                 } else {
                     float norm_factor = std::abs( GROUP_OCEAN_SHORE->freq_total / 1000.0f );
                     unsigned int pop =
                         std::round( norm_factor * rng( ocean_count * 8, ocean_count * 25 ) );
                     spawn_mon_group(
                         mongroup( GROUP_OCEAN_SHORE, project_combine( pos(), project_to<coords::sm>( p ) ),
                                   pop ), 3 );
                 }
             }
         }
     }
 }
References abs(), add_mon_group(), add_msg_debug, calculate_ocean_gradient(), ceil(), cities, debugmode::DF_OVERMAP, MonsterGroup::freq_total, g, oter_t::get_type_id(), global_base_point(), GROUP_OCEAN_DEEP, GROUP_OCEAN_SHORE, GROUP_RIVER, GROUP_SWAMP, GROUP_ZOMBIE, mongroup::horde, inbounds(), is_lake_or_river(), is_ocean(), om_noise::om_noise_layer_ocean::noise_at(), overmap_ocean_settings::noise_threshold_ocean, overmap_ocean_settings::ocean_start_east, overmap_ocean_settings::ocean_start_north, overmap_ocean_settings::ocean_start_south, overmap_ocean_settings::ocean_start_west, OMAPX, OMAPY, one_in(), oter_forest_water, oter_type_road, overmap_buffer, regional_settings::overmap_ocean, point_east, point_south, point_south_east, points_in_radius(), pos(), coords::project_combine(), rng(), rng_get_engine(), round(), settings, spawn_mon_group(), sx, sy, overmapbuffer::ter(), ter(), coords::coord_point_base< Point >::to_string_writable(), trig_dist(), and mongroup::wander().
Referenced by generate().
place_nemesis()
void overmap::place_nemesis (const tripoint_abs_omt & p) private
Definition at line 7147 of file overmap.cpp.
 {
     tripoint_abs_sm pos_sm = project_to<coords::sm>( p );
     mongroup nemesis = mongroup( GROUP_NEMESIS, pos_sm, 1 );
     nemesis.horde = true;
     nemesis.behaviour = mongroup::horde_behaviour::nemesis;
     add_mon_group( nemesis );
 }
References add_mon_group(), mongroup::behaviour, GROUP_NEMESIS, mongroup::horde, and mongroup::nemesis.
place_oceans()
void overmap::place_oceans () private
Definition at line 4754 of file overmap.cpp.
 {
     int northern_ocean = settings->overmap_ocean.ocean_start_north;
     int eastern_ocean = settings->overmap_ocean.ocean_start_east;
     int western_ocean = settings->overmap_ocean.ocean_start_west;
     int southern_ocean = settings->overmap_ocean.ocean_start_south;
     const om_noise::om_noise_layer_ocean f( global_base_point(), g->get_seed() );
     const point_abs_om this_om = pos();
     const auto is_ocean = [&]( const point_om_omt & p ) {
         // credit to ehughsbaird for thinking up this inbounds solution to infinite flood fill lag.
         if( northern_ocean == 0 && eastern_ocean  == 0 && western_ocean  == 0 && southern_ocean == 0 ) {
             // you know you could just turn oceans off in global_settings.json right?
             return false;
         }
         bool inbounds = p.x() > -5 && p.y() > -5 && p.x() < OMAPX + 5 && p.y() < OMAPY + 5;
         if( !inbounds ) {
             return false;
         }
         float ocean_adjust = calculate_ocean_gradient( p, this_om );
         if( ocean_adjust == 0.0f ) {
             // It's too soon!  Too soon for an ocean!!  ABORT!!!
             return false;
         }
         return f.noise_at( p ) + ocean_adjust > settings->overmap_ocean.noise_threshold_ocean;
     };
     const oter_id ocean_surface( "ocean_surface" );
     const oter_id ocean_shore( "ocean_shore" );
     const oter_id ocean_water_cube( "ocean_water_cube" );
     const oter_id ocean_bed( "ocean_bed" );
     // This code is repeated from is_lake(), see comments there for explanation.
     std::unordered_set<point_om_omt> visited;
     for( int i = 0; i < OMAPX; i++ ) {
         for( int j = 0; j < OMAPY; j++ ) {
             point_om_omt seed_point( i, j );
             if( visited.find( seed_point ) != visited.end() ) {
                 continue;
             }
             if( !is_ocean( seed_point ) ) {
                 continue;
             }
             std::vector<point_om_omt> ocean_points =
                 ff::point_flood_fill_4_connected( seed_point, visited, is_ocean );
             // Ocean size is checked like lake size, but minimum size is much bigger.
             // you could change this, if you want little tiny oceans all over the place.
             // I'm not sure why you'd want that.  Use place_lakes, my friend.
             if( ocean_points.size() < static_cast<std::vector<point>::size_type>
                 ( settings->overmap_ocean.ocean_size_min ) ) {
                 continue;
             }
             std::unordered_set<point_om_omt> ocean_set;
             for( auto &p : ocean_points ) {
                 ocean_set.emplace( p );
             }
             for( int x = 0; x < OMAPX; x++ ) {
                 for( int y = 0; y < OMAPY; y++ ) {
                     const tripoint_om_omt p( x, y, 0 );
                     if( ter( p )->is_river() ) {
                         ocean_set.emplace( p.xy() );
                     }
                 }
             }
             for( auto &p : ocean_points ) {
                 if( !inbounds( p ) ) {
                     continue;
                 }
                 bool shore = false;
                 for( int ni = -1; ni <= 1 && !shore; ni++ ) {
                     for( int nj = -1; nj <= 1 && !shore; nj++ ) {
                         const point_om_omt n = p + point( ni, nj );
                         if( ocean_set.find( n ) == ocean_set.end() ) {
                             shore = true;
                         }
                     }
                 }
                 ter_set( tripoint_om_omt( p, 0 ), shore ? ocean_shore : ocean_surface );
                 if( !shore ) {
                     for( int z = -1; z > settings->overmap_ocean.ocean_depth; z-- ) {
                         ter_set( tripoint_om_omt( p, z ), ocean_water_cube );
                     }
                     ter_set( tripoint_om_omt( p, settings->overmap_ocean.ocean_depth ), ocean_bed );
                 }
             }
             // We're going to attempt to connect some points to the nearest river.
             // This isn't a lake but the code is the same, we can reuse it.  Water is water.
             const auto connect_lake_to_closest_river =
             [&]( const point_om_omt & lake_connection_point ) {
                 int closest_distance = -1;
                 point_om_omt closest_point;
                 for( int x = 0; x < OMAPX; x++ ) {
                     for( int y = 0; y < OMAPY; y++ ) {
                         const tripoint_om_omt p( x, y, 0 );
                         if( !ter( p )->is_river() ) {
                             continue;
                         }
                         const int distance = square_dist( lake_connection_point, p.xy() );
                         if( distance < closest_distance || closest_distance < 0 ) {
                             closest_point = p.xy();
                             closest_distance = distance;
                         }
                     }
                 }
                 if( closest_distance > 0 ) {
                     place_river( closest_point, lake_connection_point );
                 }
             };
             // Get the north and south most points in our ocean.
             auto north_south_most = std::minmax_element( ocean_points.begin(), ocean_points.end(),
             []( const point_om_omt & lhs, const point_om_omt & rhs ) {
                 return lhs.y() < rhs.y();
             } );
             point_om_omt northmost = *north_south_most.first;
             point_om_omt southmost = *north_south_most.second;
             // It's possible that our northmost/southmost points in the lake are not on this overmap, because our
             // lake may extend across multiple overmaps.
             if( inbounds( northmost ) ) {
                 connect_lake_to_closest_river( northmost );
             }
             if( inbounds( southmost ) ) {
                 connect_lake_to_closest_river( southmost );
             }
         }
     }
 }
References calculate_ocean_gradient(), g, global_base_point(), inbounds(), is_ocean(), is_river(), om_noise::om_noise_layer_ocean::noise_at(), overmap_ocean_settings::noise_threshold_ocean, overmap_ocean_settings::ocean_depth, ocean_shore, overmap_ocean_settings::ocean_size_min, overmap_ocean_settings::ocean_start_east, overmap_ocean_settings::ocean_start_north, overmap_ocean_settings::ocean_start_south, overmap_ocean_settings::ocean_start_west, OMAPX, OMAPY, regional_settings::overmap_ocean, place_river(), point, ff::point_flood_fill_4_connected(), pos(), settings, shore, square_dist(), ter(), ter_set(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by generate().
place_radios()
void overmap::place_radios () private
Definition at line 7162 of file overmap.cpp.
 {
     auto strength = []() {
         return rng( RADIO_MIN_STRENGTH, RADIO_MAX_STRENGTH );
     };
     std::string message;
     for( int i = 0; i < OMAPX; i++ ) {
         for( int j = 0; j < OMAPY; j++ ) {
             tripoint_om_omt pos_omt( i, j, 0 );
             point_om_sm pos_sm = project_to<coords::sm>( pos_omt.xy() );
             // Since location have id such as "radio_tower_1_north", we must check the beginning of the id
             if( is_ot_match( "radio_tower", ter( pos_omt ), ot_match_type::prefix ) ) {
                 if( one_in( 3 ) ) {
                     radios.emplace_back( pos_sm, strength(), "", radio_type::WEATHER_RADIO );
                 } else {
                     message = SNIPPET.expand( SNIPPET.random_from_category( "radio_archive" ).value_or(
                                                   translation() ).translated() );
                     radios.emplace_back( pos_sm, strength(), message );
                 }
             } else if( is_ot_match( "lmoe", ter( pos_omt ), ot_match_type::prefix ) ) {
                 message = string_format( _( "This is automated emergency shelter beacon %d%d."
                                             "  Supplies, amenities and shelter are stocked." ), i, j );
                 radios.emplace_back( pos_sm, strength() / 2, message );
             } else if( is_ot_match( "fema_entrance", ter( pos_omt ), ot_match_type::prefix ) ) {
                 message = string_format( _( "This is FEMA camp %d%d."
                                             "  Supplies are limited, please bring supplemental food, water, and bedding."
                                             "  This is FEMA camp %d%d.  A designated long-term emergency shelter." ), i, j, i, j );
                 radios.emplace_back( pos_sm, strength(), message );
             }
         }
     }
 }
References _, snippet_library::expand(), is_ot_match(), mapgen_defer::message, OMAPX, OMAPY, one_in(), prefix, RADIO_MAX_STRENGTH, RADIO_MIN_STRENGTH, radios, snippet_library::random_from_category(), rng(), SNIPPET, strength, string_format(), ter(), WEATHER_RADIO, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by generate().
place_railroads()
void overmap::place_railroads (const overmap * north, const overmap * east, const overmap * south, const overmap * west) private
Definition at line 5180 of file overmap.cpp.
 {
     // no railroads if there are no cities
     int op_city_size = get_option<int>( "CITY_SIZE" );
     if( op_city_size <= 0 ) {
         return;
     }
     const overmap_connection_id &overmap_connection_local_railroad =
         settings->overmap_connection.rail_connection;
     std::vector<tripoint_om_omt> &railroads_out = connections_out[overmap_connection_local_railroad];
     // At least 3 exit points, to guarantee railroad continuity across overmaps
     if( railroads_out.size() < 3 ) {
         std::array<const overmap *, 4> neighbors = { east, south, west, north };
         static constexpr std::array<point, 4> neighbor_deltas = {
             point_east, point_south, point_west, point_north
         };
         // x and y coordinates for a point on the edge in each direction
         // -1 represents a variable one dimensional coordinate along that edge
         // east == point( OMAPX - 1, n ); north == point( n, 0 );
         static constexpr std::array<int, 4> edge_coords_x = {OMAPX - 1, -1, 0, -1};
         static constexpr std::array<int, 4> edge_coords_y = {-1, OMAPY - 1, -1, 0};
         // all the points on an edge except the 10 on each end
         std::array < int, OMAPX - 20 > omap_num;
         for( int i = 0; i < OMAPX - 20; i++ ) {
             omap_num[i] = i + 10;
         }
         std::array < size_t, 4 > dirs = {0, 1, 2, 3};
         std::shuffle( dirs.begin(), dirs.end(), rng_get_engine() );
         for( size_t dir : dirs ) {
             // only potentially add a new random connection toward ungenerated overmaps
             if( neighbors[dir] == nullptr ) {
                 std::shuffle( omap_num.begin(), omap_num.end(), rng_get_engine() );
                 for( const int &i : omap_num ) {
                     tripoint_om_omt tmp = tripoint_om_omt(
                                               edge_coords_x[dir] >= 0 ? edge_coords_x[dir] : i,
                                               edge_coords_y[dir] >= 0 ? edge_coords_y[dir] : i,
                                               0 );
                     // Make sure these points don't conflict with rivers.
                     if( !( is_river( ter( tmp ) ) ||
                            // avoid adjacent rivers
                            // east/west of a point on the north/south edge, and vice versa
                            is_river( ter( tmp + neighbor_deltas[( dir + 1 ) % 4] ) ) ||
                            is_river( ter( tmp + neighbor_deltas[( dir + 3 ) % 4] ) ) ) ) {
                         railroads_out.push_back( tmp );
                         break;
                     }
                 }
                 if( railroads_out.size() == 3 ) {
                     break;
                 }
             }
         }
     }
     std::vector<point_om_omt> railroad_points; // cities and railroads_out together
     // Compile our master list of railroads; it's less messy if railroads_out is first
     railroad_points.reserve( railroads_out.size() + cities.size() );
     for( const auto &elem : railroads_out ) {
         railroad_points.emplace_back( elem.xy() );
     }
     for( const city &elem : cities ) {
         // place railroads in random point around the center of the city
         railroad_points.emplace_back( random_entry(
                                           points_in_radius( tripoint_om_omt( elem.pos, 0 ), elem.size * 4 ) ).xy()
                                     );
     }
     // And finally connect them via railroads.
     connect_closest_points( railroad_points, 0, *overmap_connection_local_railroad );
 }
References cities, connect_closest_points(), connections_out, east, is_river(), north, OMAPX, OMAPY, regional_settings::overmap_connection, point_east, point_north, point_south, point_west, points_in_radius(), overmap_connection_settings::rail_connection, random_entry(), rng_get_engine(), settings, south, ter(), and west.
Referenced by generate().
place_ravines()
void overmap::place_ravines () private
Definition at line 5882 of file overmap.cpp.
 {
     if( settings->overmap_ravine.num_ravines == 0 ) {
         return;
     }
     const oter_id rift( "ravine" );
     const oter_id rift_edge( "ravine_edge" );
     const oter_id rift_floor( "ravine_floor" );
     const oter_id rift_floor_edge( "ravine_floor_edge" );
     std::set<point_om_omt> rift_points;
     // We dont really care about the paths each ravine takes, so this can be whatever
     // The random return value was chosen because it easily produces decent looking windy ravines
     const pf::two_node_scoring_fn<point_om_omt> estimate =
     [&]( pf::directed_node<point_om_omt>, const std::optional<pf::directed_node<point_om_omt>> & ) {
         return pf::node_score( 0, rng( 1, 2 ) );
     };
     // A path is generated for each of ravine, and all its constituent points are stored within the
     // rift_points set. In the code block below, the set is then used to determine edges and place the
     // actual terrain pieces of the ravine.
     for( int n = 0; n < settings->overmap_ravine.num_ravines; n++ ) {
         const point_rel_omt offset( rng( -settings->overmap_ravine.ravine_range,
                                          settings->overmap_ravine.ravine_range ),
                                     rng( -settings->overmap_ravine.ravine_range, settings->overmap_ravine.ravine_range ) );
         const point_om_omt origin( rng( 0, OMAPX ), rng( 0, OMAPY ) );
         const point_om_omt destination = origin + offset;
         if( !inbounds( destination, settings->overmap_ravine.ravine_width * 3 ) ) {
             continue;
         }
         const auto path = pf::greedy_path( origin, destination, point_om_omt( OMAPX, OMAPY ), estimate );
         for( const auto &node : path.nodes ) {
             for( int i = 1 - settings->overmap_ravine.ravine_width; i < settings->overmap_ravine.ravine_width;
                  i++ ) {
                 for( int j = 1 - settings->overmap_ravine.ravine_width; j < settings->overmap_ravine.ravine_width;
                      j++ ) {
                     const point_om_omt n = node.pos + point( j, i );
                     if( inbounds( n, 1 ) ) {
                         rift_points.emplace( n );
                     }
                 }
             }
         }
     }
     // We look at the 8 adjacent locations of each ravine point and see if they are also part of a
     // ravine, if at least one of them isn't, the location is part of the ravine's edge. Whatever the
     // case, the chosen ravine terrain is then propagated downwards until the ravine_depth specified
     // by the region settings.
     for( const point_om_omt &p : rift_points ) {
         bool edge = false;
         for( int ni = -1; ni <= 1 && !edge; ni++ ) {
             for( int nj = -1; nj <= 1 && !edge; nj++ ) {
                 const point_om_omt n = p + point_rel_omt( ni, nj );
                 if( rift_points.find( n ) == rift_points.end() || !inbounds( n ) ) {
                     edge = true;
                 }
             }
         }
         for( int z = 0; z >= settings->overmap_ravine.ravine_depth; z-- ) {
             if( z == settings->overmap_ravine.ravine_depth ) {
                 ter_set( tripoint_om_omt( p, z ), edge ? rift_floor_edge : rift_floor );
             } else {
                 ter_set( tripoint_om_omt( p, z ), edge ? rift_edge : rift );
             }
         }
     }
 }
References edge, pf::greedy_path(), inbounds(), overmap_ravine_settings::num_ravines, OMAPX, OMAPY, regional_settings::overmap_ravine, point, overmap_ravine_settings::ravine_depth, overmap_ravine_settings::ravine_range, overmap_ravine_settings::ravine_width, rng(), settings, and ter_set().
Referenced by generate().
place_river()
void overmap::place_river (const point_om_omt & pa, const point_om_omt & pb) private
Definition at line 5258 of file overmap.cpp.
 {
     int river_chance = static_cast<int>( std::max( 1.0, 1.0 / settings->river_scale ) );
     int river_scale = static_cast<int>( std::max( 1.0, settings->river_scale ) );
     point_om_omt p2( pa );
     do {
         p2.x() += rng( -1, 1 );
         p2.y() += rng( -1, 1 );
         if( p2.x() < 0 ) {
             p2.x() = 0;
         }
         if( p2.x() > OMAPX - 1 ) {
             p2.x() = OMAPX - 1;
         }
         if( p2.y() < 0 ) {
             p2.y() = 0;
         }
         if( p2.y() > OMAPY - 1 ) {
             p2.y() = OMAPY - 1;
         }
         for( int i = -1 * river_scale; i <= 1 * river_scale; i++ ) {
             for( int j = -1 * river_scale; j <= 1 * river_scale; j++ ) {
                 tripoint_om_omt p( p2 + point( j, i ), 0 );
                 if( p.y() >= 0 && p.y() < OMAPY && p.x() >= 0 && p.x() < OMAPX ) {
                     if( !ter( p )->is_lake() && one_in( river_chance ) ) {
                         ter_set( p, oter_river_center );
                     }
                 }
             }
         }
         if( pb.x() > p2.x() && ( rng( 0, static_cast<int>( OMAPX * 1.2 ) - 1 ) < pb.x() - p2.x() ||
                                  ( rng( 0, static_cast<int>( OMAPX * 0.2 ) - 1 ) > pb.x() - p2.x() &&
                                    rng( 0, static_cast<int>( OMAPY * 0.2 ) - 1 ) > std::abs( pb.y() - p2.y() ) ) ) ) {
             p2.x()++;
         }
         if( pb.x() < p2.x() && ( rng( 0, static_cast<int>( OMAPX * 1.2 ) - 1 ) < p2.x() - pb.x() ||
                                  ( rng( 0, static_cast<int>( OMAPX * 0.2 ) - 1 ) > p2.x() - pb.x() &&
                                    rng( 0, static_cast<int>( OMAPY * 0.2 ) - 1 ) > std::abs( pb.y() - p2.y() ) ) ) ) {
             p2.x()--;
         }
         if( pb.y() > p2.y() && ( rng( 0, static_cast<int>( OMAPY * 1.2 ) - 1 ) < pb.y() - p2.y() ||
                                  ( rng( 0, static_cast<int>( OMAPY * 0.2 ) - 1 ) > pb.y() - p2.y() &&
                                    rng( 0, static_cast<int>( OMAPX * 0.2 ) - 1 ) > std::abs( p2.x() - pb.x() ) ) ) ) {
             p2.y()++;
         }
         if( pb.y() < p2.y() && ( rng( 0, static_cast<int>( OMAPY * 1.2 ) - 1 ) < p2.y() - pb.y() ||
                                  ( rng( 0, static_cast<int>( OMAPY * 0.2 ) - 1 ) > p2.y() - pb.y() &&
                                    rng( 0, static_cast<int>( OMAPX * 0.2 ) - 1 ) > std::abs( p2.x() - pb.x() ) ) ) ) {
             p2.y()--;
         }
         p2.x() += rng( -1, 1 );
         p2.y() += rng( -1, 1 );
         if( p2.x() < 0 ) {
             p2.x() = 0;
         }
         if( p2.x() > OMAPX - 1 ) {
             p2.x() = OMAPX - 2;
         }
         if( p2.y() < 0 ) {
             p2.y() = 0;
         }
         if( p2.y() > OMAPY - 1 ) {
             p2.y() = OMAPY - 1;
         }
         for( int i = -1 * river_scale; i <= 1 * river_scale; i++ ) {
             for( int j = -1 * river_scale; j <= 1 * river_scale; j++ ) {
                 // We don't want our riverbanks touching the edge of the map for many reasons
                 tripoint_om_omt p( p2 + point( j, i ), 0 );
                 if( inbounds( p, 1 ) ||
                     // UNLESS, of course, that's where the river is headed!
                     ( std::abs( pb.y() - p.y() ) < 4 && std::abs( pb.x() - p.x() ) < 4 ) ) {
                     if( !inbounds( p ) ) {
                         continue;
                     }
                     if( !ter( p )->is_lake() && one_in( river_chance ) ) {
                         ter_set( p, oter_river_center );
                     }
                 }
             }
         }
     } while( pb != p2 );
 }
References abs(), inbounds(), max(), OMAPX, OMAPY, one_in(), oter_river_center, point, regional_settings::river_scale, rng(), settings, ter(), ter_set(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by place_lakes(), place_oceans(), and place_rivers().
place_rivers()
void overmap::place_rivers (const overmap * north, const overmap * east, const overmap * south, const overmap * west) private
Definition at line 4898 of file overmap.cpp.
 {
     if( settings->river_scale == 0.0 ) {
         return;
     }
     int river_chance = static_cast<int>( std::max( 1.0, 1.0 / settings->river_scale ) );
     int river_scale = static_cast<int>( std::max( 1.0, settings->river_scale ) );
     // West/North endpoints of rivers
     std::vector<point_om_omt> river_start;
     // East/South endpoints of rivers
     std::vector<point_om_omt> river_end;
     // Determine points where rivers & roads should connect w/ adjacent maps
     // optimized comparison.
     if( north != nullptr ) {
         for( int i = 2; i < OMAPX - 2; i++ ) {
             const tripoint_om_omt p_neighbour( i, OMAPY - 1, 0 );
             const tripoint_om_omt p_mine( i, 0, 0 );
             if( is_river( north->ter( p_neighbour ) ) ) {
                 ter_set( p_mine, oter_river_center );
             }
             if( is_river( north->ter( p_neighbour ) ) &&
                 is_river( north->ter( p_neighbour + point_east ) ) &&
                 is_river( north->ter( p_neighbour + point_west ) ) ) {
                 if( one_in( river_chance ) && ( river_start.empty() ||
                                                 river_start[river_start.size() - 1].x() < ( i - 6 ) * river_scale ) ) {
                     river_start.push_back( p_mine.xy() );
                 }
             }
         }
     }
     size_t rivers_from_north = river_start.size();
     if( west != nullptr ) {
         for( int i = 2; i < OMAPY - 2; i++ ) {
             const tripoint_om_omt p_neighbour( OMAPX - 1, i, 0 );
             const tripoint_om_omt p_mine( 0, i, 0 );
             if( is_river( west->ter( p_neighbour ) ) ) {
                 ter_set( p_mine, oter_river_center );
             }
             if( is_river( west->ter( p_neighbour ) ) &&
                 is_river( west->ter( p_neighbour + point_north ) ) &&
                 is_river( west->ter( p_neighbour + point_south ) ) ) {
                 if( one_in( river_chance ) && ( river_start.size() == rivers_from_north ||
                                                 river_start[river_start.size() - 1].y() < ( i - 6 ) * river_scale ) ) {
                     river_start.push_back( p_mine.xy() );
                 }
             }
         }
     }
     if( south != nullptr ) {
         for( int i = 2; i < OMAPX - 2; i++ ) {
             const tripoint_om_omt p_neighbour( i, 0, 0 );
             const tripoint_om_omt p_mine( i, OMAPY - 1, 0 );
             if( is_river( south->ter( p_neighbour ) ) ) {
                 ter_set( p_mine, oter_river_center );
             }
             if( is_river( south->ter( p_neighbour ) ) &&
                 is_river( south->ter( p_neighbour + point_east ) ) &&
                 is_river( south->ter( p_neighbour + point_west ) ) ) {
                 if( river_end.empty() ||
                     river_end[river_end.size() - 1].x() < i - 6 ) {
                     river_end.push_back( p_mine.xy() );
                 }
             }
         }
     }
     size_t rivers_to_south = river_end.size();
     if( east != nullptr ) {
         for( int i = 2; i < OMAPY - 2; i++ ) {
             const tripoint_om_omt p_neighbour( 0, i, 0 );
             const tripoint_om_omt p_mine( OMAPX - 1, i, 0 );
             if( is_river( east->ter( p_neighbour ) ) ) {
                 ter_set( p_mine, oter_river_center );
             }
             if( is_river( east->ter( p_neighbour ) ) &&
                 is_river( east->ter( p_neighbour + point_north ) ) &&
                 is_river( east->ter( p_neighbour + point_south ) ) ) {
                 if( river_end.size() == rivers_to_south ||
                     river_end[river_end.size() - 1].y() < i - 6 ) {
                     river_end.push_back( p_mine.xy() );
                 }
             }
         }
     }
     // Even up the start and end points of rivers. (difference of 1 is acceptable)
     // Also ensure there's at least one of each.
     std::vector<point_om_omt> new_rivers;
     if( north == nullptr || west == nullptr ) {
         while( river_start.empty() || river_start.size() + 1 < river_end.size() ) {
             new_rivers.clear();
             if( north == nullptr && one_in( river_chance ) ) {
                 new_rivers.emplace_back( rng( 10, OMAPX - 11 ), 0 );
             }
             if( west == nullptr && one_in( river_chance ) ) {
                 new_rivers.emplace_back( 0, rng( 10, OMAPY - 11 ) );
             }
             river_start.push_back( random_entry( new_rivers ) );
         }
     }
     if( south == nullptr || east == nullptr ) {
         while( river_end.empty() || river_end.size() + 1 < river_start.size() ) {
             new_rivers.clear();
             if( south == nullptr && one_in( river_chance ) ) {
                 new_rivers.emplace_back( rng( 10, OMAPX - 11 ), OMAPY - 1 );
             }
             if( east == nullptr && one_in( river_chance ) ) {
                 new_rivers.emplace_back( OMAPX - 1, rng( 10, OMAPY - 11 ) );
             }
             river_end.push_back( random_entry( new_rivers ) );
         }
     }
     // Now actually place those rivers.
     if( river_start.size() > river_end.size() && !river_end.empty() ) {
         std::vector<point_om_omt> river_end_copy = river_end;
         while( !river_start.empty() ) {
             const point_om_omt start = random_entry_removed( river_start );
             if( !river_end.empty() ) {
                 place_river( start, river_end[0] );
                 river_end.erase( river_end.begin() );
             } else {
                 place_river( start, random_entry( river_end_copy ) );
             }
         }
     } else if( river_end.size() > river_start.size() && !river_start.empty() ) {
         std::vector<point_om_omt> river_start_copy = river_start;
         while( !river_end.empty() ) {
             const point_om_omt end = random_entry_removed( river_end );
             if( !river_start.empty() ) {
                 place_river( river_start[0], end );
                 river_start.erase( river_start.begin() );
             } else {
                 place_river( random_entry( river_start_copy ), end );
             }
         }
     } else if( !river_end.empty() ) {
         if( river_start.size() != river_end.size() ) {
             river_start.emplace_back( rng( OMAPX / 4, ( OMAPX * 3 ) / 4 ),
                                       rng( OMAPY / 4, ( OMAPY * 3 ) / 4 ) );
         }
         for( size_t i = 0; i < river_start.size(); i++ ) {
             place_river( river_start[i], river_end[i] );
         }
     }
 }
References east, keycode::end, is_river(), max(), north, OMAPX, OMAPY, one_in(), oter_river_center, place_river(), point_east, point_north, point_south, point_west, random_entry(), random_entry_removed(), regional_settings::river_scale, rng(), settings, south, ter_set(), west, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by generate().
place_roads()
void overmap::place_roads (const overmap * north, const overmap * east, const overmap * south, const overmap * west) private
Definition at line 5106 of file overmap.cpp.
 {
     int op_city_size = get_option<int>( "CITY_SIZE" );
     if( op_city_size <= 0 ) {
         return;
     }
     const overmap_connection_id &overmap_connection_inter_city_road =
         settings->overmap_connection.inter_city_road_connection;
     std::vector<tripoint_om_omt> &roads_out = connections_out[overmap_connection_inter_city_road];
     // At least 3 exit points, to guarantee road continuity across overmaps
     if( roads_out.size() < 3 ) {
         std::array<const overmap *, 4> neighbors = { east, south, west, north };
         static constexpr std::array<point, 4> neighbor_deltas = {
             point_east, point_south, point_west, point_north
         };
         // x and y coordinates for a point on the edge in each direction
         // -1 represents a variable one dimensional coordinate along that edge
         // east == point( OMAPX - 1, n ); north == point( n, 0 );
         static constexpr std::array<int, 4> edge_coords_x = {OMAPX - 1, -1, 0, -1};
         static constexpr std::array<int, 4> edge_coords_y = {-1, OMAPY - 1, -1, 0};
         // all the points on an edge except the 10 on each end
         std::array < int, OMAPX - 20 > omap_num;
         for( int i = 0; i < OMAPX - 20; i++ ) {
             omap_num[i] = i + 10;
         }
         std::array < size_t, 4 > dirs = {0, 1, 2, 3};
         std::shuffle( dirs.begin(), dirs.end(), rng_get_engine() );
         for( size_t dir : dirs ) {
             // only potentially add a new random connection toward ungenerated overmaps
             if( neighbors[dir] == nullptr ) {
                 std::shuffle( omap_num.begin(), omap_num.end(), rng_get_engine() );
                 for( const int &i : omap_num ) {
                     tripoint_om_omt tmp = tripoint_om_omt(
                                               edge_coords_x[dir] >= 0 ? edge_coords_x[dir] : i,
                                               edge_coords_y[dir] >= 0 ? edge_coords_y[dir] : i,
                                               0 );
                     // Make sure these points don't conflict with rivers.
                     if( !( is_river( ter( tmp ) ) ||
                            // avoid adjacent rivers
                            // east/west of a point on the north/south edge, and vice versa
                            is_river( ter( tmp + neighbor_deltas[( dir + 1 ) % 4] ) ) ||
                            is_river( ter( tmp + neighbor_deltas[( dir + 3 ) % 4] ) ) ) ) {
                         roads_out.push_back( tmp );
                         break;
                     }
                 }
                 if( roads_out.size() == 3 ) {
                     break;
                 }
             }
         }
     }
     std::vector<point_om_omt> road_points; // cities and roads_out together
     // Compile our master list of roads; it's less messy if roads_out is first
     road_points.reserve( roads_out.size() + cities.size() );
     for( const auto &elem : roads_out ) {
         road_points.emplace_back( elem.xy() );
     }
     for( const city &elem : cities ) {
         road_points.emplace_back( elem.pos );
     }
     // And finally connect them via roads.
     connect_closest_points( road_points, 0, *overmap_connection_inter_city_road );
 }
References cities, connect_closest_points(), connections_out, east, overmap_connection_settings::inter_city_road_connection, is_river(), north, OMAPX, OMAPY, regional_settings::overmap_connection, point_east, point_north, point_south, point_west, rng_get_engine(), settings, south, ter(), and west.
Referenced by generate().
place_special()
std::vector< tripoint_om_omt > overmap::place_special (const overmap_special & special, const tripoint_om_omt & p, om_direction::type dir, const city & cit, bool must_be_unexplored, bool force)
Definition at line 6619 of file overmap.cpp.
 {
     cata_assert( dir != om_direction::type::invalid );
     if( !force ) {
         cata_assert( can_place_special( special, p, dir, must_be_unexplored ) );
     }
     if( special.has_flag( "GLOBALLY_UNIQUE" ) ) {
         overmap_buffer.add_unique_special( special.id );
     }
     if( special.has_flag( "UNIQUE" ) ) {
         overmap_buffer.log_unique_special( special.id );
     }
     const bool is_safe_zone = special.has_flag( "SAFE_AT_WORLDGEN" );
     std::optional<mapgen_arguments> *mapgen_args_p = &*mapgen_arg_storage.emplace();
     special_placement_result result = special.place( *this, p, dir, cit, must_be_unexplored );
     for( const std::pair<om_pos_dir, std::string> &join : result.joins_used ) {
         joins_used[join.first] = join.second;
     }
     for( const tripoint_om_omt &location : result.omts_used ) {
         overmap_special_placements[location] = special.id;
         mapgen_args_index[location] = mapgen_args_p;
         if( is_safe_zone ) {
             safe_at_worldgen.emplace( location );
         }
     }
     // Place spawns.
     const overmap_special_spawns &spawns = special.get_monster_spawns();
     if( spawns.group ) {
         const int pop = rng( spawns.population.min, spawns.population.max );
         const int rad = rng( spawns.radius.min, spawns.radius.max );
         spawn_mon_group(
             mongroup( spawns.group, project_to<coords::sm>( project_combine( pos(), p ) ), pop ),
             rad );
     }
     // If it's a safe zone, remove existing spawns
     if( is_safe_zone ) {
         for( auto it = zg.begin(); it != zg.end(); ) {
             tripoint_om_omt pos = project_to<coords::omt>( it->second.rel_pos() );
             if( safe_at_worldgen.find( pos ) != safe_at_worldgen.end() ) {
                 zg.erase( it++ );
             } else {
                 ++it;
             }
         }
     }
     return result.omts_used;
 }
References overmapbuffer::add_unique_special(), can_place_special(), cata_assert, cata::colony< element_type, element_allocator_type, element_skipfield_type >::emplace(), force, overmap_special::get_monster_spawns(), overmap_spawns::group, overmap_special::has_flag(), overmap_special::id, om_direction::invalid, special_placement_result::joins_used, joins_used, location, overmapbuffer::log_unique_special(), mapgen_arg_storage, mapgen_args_index, numeric_interval< T, typename >::max, numeric_interval< T, typename >::min, special_placement_result::omts_used, overmap_buffer, overmap_special_placements, overmap_special::place(), overmap_spawns::population, pos(), coords::project_combine(), overmap_special_spawns::radius, rng(), safe_at_worldgen, spawn_mon_group(), and zg.
Referenced by place_building(), place_forest_trailheads(), overmapbuffer::place_special(), place_special_attempt(), and place_special_forced().
place_special_attempt()
bool overmap::place_special_attempt (overmap_special_batch & enabled_specials, const point_om_omt & sector, int sector_width, bool place_optional, bool must_be_unexplored) private
Attempts to place specials within a sector.
Parameters
enabled_specials vector of objects that track specials being placed.
sector sector identifies the location where specials are being placed.
place_optional restricts attempting to place specials that have met their minimum count in the first pass.
Definition at line 6687 of file overmap.cpp.
 {
     const point_om_omt p2( sector );
     const tripoint_om_omt p( rng( p2.x(), p2.x() + sector_width - 1 ),
                              rng( p2.y(), p2.y() + sector_width - 1 ), 0 );
     const city &nearest_city = get_nearest_city( p );
     std::shuffle( enabled_specials.begin(), enabled_specials.end(), rng_get_engine() );
     std::set<int> priorities;
     for( const overmap_special_placement &os : enabled_specials ) {
         priorities.emplace( os.special_details->get_priority() );
     }
     for( auto pri_iter = priorities.rbegin(); pri_iter != priorities.rend(); ++pri_iter ) {
         for( auto iter = enabled_specials.begin(); iter != enabled_specials.end(); ++iter ) {
             const overmap_special &special = *iter->special_details;
             if( *pri_iter != special.get_priority() ) {
                 continue;
             }
             const overmap_special_placement_constraints &constraints = special.get_constraints();
             // If we haven't finished placing minimum instances of all specials,
             // skip specials that are at their minimum count already.
             if( !place_optional && iter->instances_placed >= constraints.occurrences.min ) {
                 continue;
             }
             // City check is the fastest => it goes first.
             if( !special.can_belong_to_city( p, nearest_city ) ) {
                 continue;
             }
             // See if we can actually place the special there.
             const om_direction::type rotation = random_special_rotation( special, p, must_be_unexplored );
             if( rotation == om_direction::type::invalid ) {
                 continue;
             }
             place_special( special, p, rotation, nearest_city, false, must_be_unexplored );
             if( ++iter->instances_placed >= constraints.occurrences.max ) {
                 enabled_specials.erase( iter );
             }
             return true;
         }
     }
     return false;
 }
References overmap_special_batch::begin(), overmap_special::can_belong_to_city(), overmap_special_batch::end(), overmap_special_batch::erase(), overmap_special::get_constraints(), get_nearest_city(), overmap_special::get_priority(), om_direction::invalid, numeric_interval< T, typename >::max, numeric_interval< T, typename >::min, overmap_special_placement_constraints::occurrences, place_special(), random_special_rotation(), rng(), rng_get_engine(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by place_specials_pass().
place_special_forced()
void overmap::place_special_forced (const overmap_special_id & special_id, const tripoint_om_omt & p, om_direction::type dir)
Definition at line 3990 of file overmap.cpp.
 {
     static city invalid_city;
     place_special( *special_id, p, dir, invalid_city, false, true );
 }
References place_special().
Referenced by tutorial_game::init(), and game::start_game().
place_specials()
void overmap::place_specials (overmap_special_batch & enabled_specials) private
Iterate over the overmap and place the quota of specials.
If the stated minimums are not reached, it will spawn a new nearby overmap and continue placing specials there.
Parameters
enabled_specials specifies what specials to place, and tracks how many have been placed.
Definition at line 6768 of file overmap.cpp.
 {
     // Calculate if this overmap has any lake terrain--if it doesn't, we should just
     // completely skip placing any lake specials here since they'll never place and if
     // they're mandatory they just end up causing us to spiral out into adjacent overmaps
     // which probably don't have lakes either.
     bool overmap_has_lake = false;
     bool overmap_has_ocean = false;
     for( int z = -OVERMAP_DEPTH; z <= OVERMAP_HEIGHT && !overmap_has_lake; z++ ) {
         for( int x = 0; x < OMAPX && !overmap_has_lake; x++ ) {
             for( int y = 0; y < OMAPY && !overmap_has_lake; y++ ) {
                 overmap_has_lake = ter_unsafe( { x, y, z } )->is_lake();
             }
         }
     }
     for( int z = -OVERMAP_DEPTH; z <= OVERMAP_HEIGHT && !overmap_has_ocean; z++ ) {
         for( int x = 0; x < OMAPX && !overmap_has_ocean; x++ ) {
             for( int y = 0; y < OMAPY && !overmap_has_ocean; y++ ) {
                 overmap_has_ocean = ter_unsafe( { x, y, z } )->is_ocean();
             }
         }
     }
     for( auto iter = enabled_specials.begin(); iter != enabled_specials.end(); ) {
         // If this special has the LAKE flag and the overmap doesn't have any
         // lake terrain, then remove this special from the candidates for this
         // overmap.
         if( iter->special_details->has_flag( "LAKE" ) && !overmap_has_lake ) {
             iter = enabled_specials.erase( iter );
             continue;
         }
         if( iter->special_details->has_flag( "OCEAN" ) && !overmap_has_ocean ) {
             iter = enabled_specials.erase( iter );
             continue;
         }
         const bool unique = iter->special_details->has_flag( "UNIQUE" );
         const bool globally_unique = iter->special_details->has_flag( "GLOBALLY_UNIQUE" );
         if( unique || globally_unique ) {
             const overmap_special_id &id = iter->special_details->id;
             const overmap_special_placement_constraints &constraints = iter->special_details->get_constraints();
             const float special_count = overmap_buffer.get_unique_special_count( id );
             const float overmap_count = overmap_buffer.get_overmap_count();
             const float min = special_count > 0 ? constraints.occurrences.min / special_count :
                               constraints.occurrences.min;
             const float max = std::max( overmap_count > 0 ? constraints.occurrences.max / overmap_count :
                                         constraints.occurrences.max, min );
             if( x_in_y( min, max ) && ( !globally_unique || !overmap_buffer.contains_unique_special( id ) ) ) {
                 // Min and max are overloaded to be the chance of occurrence,
                 // so reset instances placed to one short of max so we don't place several.
                 iter->instances_placed = constraints.occurrences.max - 1;
             } else {
                 iter = enabled_specials.erase( iter );
                 continue;
             }
         }
         ++iter;
     }
     // Bail out early if we have nothing to place.
     if( enabled_specials.empty() ) {
         return;
     }
     om_special_sectors sectors = get_sectors( OMSPEC_FREQ );
     // First, place the mandatory specials to ensure that all minimum instance
     // counts are met.
     place_specials_pass( enabled_specials, sectors, false, false );
     // Snapshot remaining specials, which will be the optional specials and
     // any unplaced mandatory specials. By passing a copy into the creation of
     // the adjacent overmaps, we ensure that when we unwind the overmap creation
     // back to filling in our non-mandatory specials for this overmap, we won't
     // count the placement of the specials in those maps when looking for optional
     // specials to place here.
     overmap_special_batch custom_overmap_specials = enabled_specials;
     // Check for any unplaced mandatory specials, and if there are any, attempt to
     // place them on adjacent uncreated overmaps.
     bool any_below_minimum =
         std::any_of( custom_overmap_specials.begin(), custom_overmap_specials.end(),
     []( const overmap_special_placement & placement ) {
         return placement.instances_placed <
                placement.special_details->get_constraints().occurrences.min;
     } );
     if( any_below_minimum ) {
         // Randomly select from among the nearest uninitialized overmap positions.
         int previous_distance = 0;
         std::vector<point_abs_om> nearest_candidates;
         // Since this starts at enabled_specials::origin, it will only place new overmaps
         // in the 5x5 area surrounding the initial overmap, bounding the amount of work we will do.
         for( const point_abs_om &candidate_addr : closest_points_first(
                  custom_overmap_specials.get_origin(), 2 ) ) {
             if( !overmap_buffer.has( candidate_addr ) ) {
                 int current_distance = square_dist( pos(), candidate_addr );
                 if( nearest_candidates.empty() || current_distance == previous_distance ) {
                     nearest_candidates.push_back( candidate_addr );
                     previous_distance = current_distance;
                 } else {
                     break;
                 }
             }
         }
         if( !nearest_candidates.empty() ) {
             point_abs_om new_om_addr = random_entry( nearest_candidates );
             overmap_buffer.create_custom_overmap( new_om_addr, custom_overmap_specials );
         } else {
             std::string msg =
                 "The following specials could not be placed, some missions may fail to initialize: ";
             int n = 0;
             for( auto iter = custom_overmap_specials.begin(); iter != custom_overmap_specials.end(); ) {
                 if( iter->instances_placed < iter->special_details->get_constraints().occurrences.min ) {
                     msg.append( iter->special_details->id.c_str() ).append( ", " );
                     n++;
                 }
                 ++iter;
             }
             if( n > 0 ) {
                 msg = msg.substr( 0, msg.length() - 2 );
             } else {
                 msg = msg.append( "<unknown>" );
             }
             add_msg( _( msg ) );
         }
     }
     // Then fill in non-mandatory specials.
     place_specials_pass( enabled_specials, sectors, true, false );
     // Clean up...
     // Because we passed a copy of the specials for placement in adjacent overmaps rather than
     // the original, but our caller is concerned with whether or not they were placed at all,
     // regardless of whether we placed them or our callee did, we need to reconcile the placement
     // that we did of the optional specials with the placement our callee did of optional
     // and mandatory.
     // Make a lookup of our callee's specials after processing.
     // Because specials are removed from the list once they meet their maximum
     // occurrences, this will only contain those which have not yet met their
     // maximum.
     std::map<overmap_special_id, int> processed_specials;
     for( overmap_special_placement &elem : custom_overmap_specials ) {
         processed_specials[elem.special_details->id] = elem.instances_placed;
     }
     // Loop through the specials we started with.
     for( auto it = enabled_specials.begin(); it != enabled_specials.end(); ) {
         // Determine if this special is still in our callee's list of specials...
         std::map<overmap_special_id, int>::iterator iter = processed_specials.find(
                     it->special_details->id );
         if( iter != processed_specials.end() ) {
             // ... and if so, increment the placement count to reflect the callee's.
             it->instances_placed += ( iter->second - it->instances_placed );
             // If, after incrementing the placement count, we're at our max, remove
             // this special from our list.
             if( it->instances_placed >= it->special_details->get_constraints().occurrences.max ) {
                 it = enabled_specials.erase( it );
             } else {
                 it++;
             }
         } else {
             // This special is no longer in our callee's list, which means it was completely
             // placed, and we can remove it from our list.
             it = enabled_specials.erase( it );
         }
     }
 }
References _, add_msg(), overmap_special_batch::begin(), closest_points_first(), overmapbuffer::contains_unique_special(), overmapbuffer::create_custom_overmap(), overmap_special_batch::empty(), overmap_special_batch::end(), overmap_special_batch::erase(), overmap_special_batch::get_origin(), overmapbuffer::get_overmap_count(), get_sectors(), overmapbuffer::get_unique_special_count(), overmapbuffer::has(), overmap_special::id, is_ocean(), numeric_interval< T, typename >::max, max(), numeric_interval< T, typename >::min, min(), overmap_special_placement_constraints::occurrences, OMAPX, OMAPY, OMSPEC_FREQ, overmap_buffer, OVERMAP_DEPTH, OVERMAP_HEIGHT, place_specials_pass(), pos(), random_entry(), square_dist(), ter_unsafe(), and x_in_y().
Referenced by generate().
place_specials_pass()
void overmap::place_specials_pass (overmap_special_batch & enabled_specials, om_special_sectors & sectors, bool place_optional, bool must_be_unexplored) private
Walk over the overmap and attempt to place specials.
Parameters
enabled_specials vector of objects that track specials being placed.
sectors sectors in which to attempt placement.
place_optional restricts attempting to place specials that have met their minimum count in the first pass.
Definition at line 6737 of file overmap.cpp.
 {
     // Walk over sectors in random order, to minimize "clumping".
     std::shuffle( sectors.sectors.begin(), sectors.sectors.end(), rng_get_engine() );
     for( auto it = sectors.sectors.begin(); it != sectors.sectors.end(); ) {
         const size_t attempts = 10;
         bool placed = false;
         for( size_t i = 0; i < attempts; ++i ) {
             if( place_special_attempt( enabled_specials, *it, sectors.sector_width, place_optional,
                                        must_be_unexplored ) ) {
                 placed = true;
                 it = sectors.sectors.erase( it );
                 if( enabled_specials.empty() ) {
                     return; // Job done. Bail out.
                 }
                 break;
             }
         }
         if( !placed ) {
             it++;
         }
     }
 }
References overmap_special_batch::empty(), place_special_attempt(), rng_get_engine(), om_special_sectors::sector_width, and om_special_sectors::sectors.
Referenced by place_specials().
place_swamps()
void overmap::place_swamps () private
Definition at line 5051 of file overmap.cpp.
 {
     // Buffer our river terrains by a variable radius and increment a counter for the location each
     // time it's included in a buffer. It's a floodplain that we'll then intersect later with some
     // noise to adjust how frequently it occurs.
     std::unique_ptr<cata::mdarray<int, point_om_omt>> floodptr =
                 std::make_unique<cata::mdarray<int, point_om_omt>>( 0 );
     cata::mdarray<int, point_om_omt> &floodplain = *floodptr;
     for( int x = 0; x < OMAPX; x++ ) {
         for( int y = 0; y < OMAPY; y++ ) {
             const tripoint_om_omt pos( x, y, 0 );
             if( is_ot_match( "river", ter_unsafe( pos ), ot_match_type::contains ) ) {
                 std::vector<point_om_omt> buffered_points =
                     closest_points_first(
                         pos.xy(),
                         rng( settings->overmap_forest.river_floodplain_buffer_distance_min,
                              settings->overmap_forest.river_floodplain_buffer_distance_max ) );
                 for( const point_om_omt &p : buffered_points )  {
                     if( !inbounds( p ) ) {
                         continue;
                     }
                     floodplain[p] += 1;
                 }
             }
         }
     }
     // Get a layer of noise to use in conjunction with our river buffered floodplain.
     const om_noise::om_noise_layer_floodplain f( global_base_point(), g->get_seed() );
     for( int x = 0; x < OMAPX; x++ ) {
         for( int y = 0; y < OMAPY; y++ ) {
             const tripoint_om_omt pos( x, y, 0 );
             // If this location isn't a forest, there's nothing to do here. We'll only grow swamps in existing
             // forest terrain.
             if( !is_ot_match( "forest", ter( pos ), ot_match_type::contains ) ) {
                 continue;
             }
             // If this was a part of our buffered floodplain, and the noise here meets the threshold, and the one_in rng
             // triggers, then we should flood this location and make it a swamp.
             const bool should_flood = ( floodplain[x][y] > 0 && !one_in( floodplain[x][y] ) && f.noise_at( { x, y } )
                                         > settings->overmap_forest.noise_threshold_swamp_adjacent_water );
             // If this location meets our isolated swamp threshold, regardless of floodplain values, we'll make it
             // into a swamp.
             const bool should_isolated_swamp = f.noise_at( pos.xy() ) >
                                                settings->overmap_forest.noise_threshold_swamp_isolated;
             if( should_flood || should_isolated_swamp )  {
                 ter_set( pos, oter_forest_water );
             }
         }
     }
 }
References closest_points_first(), contains, g, global_base_point(), inbounds(), is_ot_match(), om_noise::om_noise_layer_floodplain::noise_at(), overmap_forest_settings::noise_threshold_swamp_adjacent_water, overmap_forest_settings::noise_threshold_swamp_isolated, OMAPX, OMAPY, one_in(), oter_forest_water, regional_settings::overmap_forest, pos(), overmap_forest_settings::river_floodplain_buffer_distance_max, overmap_forest_settings::river_floodplain_buffer_distance_min, rng(), settings, ter(), ter_set(), ter_unsafe(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by generate().
polish_river()
void overmap::polish_river ()
Definition at line 6259 of file overmap.cpp.
 {
     for( int x = 0; x < OMAPX; x++ ) {
         for( int y = 0; y < OMAPY; y++ ) {
             good_river( { x, y, 0 } );
         }
     }
 }
References good_river(), OMAPX, and OMAPY.
Referenced by generate().
populate() [1/2]
void overmap::populate ()
Definition at line 2871 of file overmap.cpp.
 {
     overmap_special_batch enabled_specials = overmap_specials::get_default_batch( loc );
     const overmap_feature_flag_settings &overmap_feature_flag = settings->overmap_feature_flag;
     const bool should_blacklist = !overmap_feature_flag.blacklist.empty();
     const bool should_whitelist = !overmap_feature_flag.whitelist.empty();
     // If this region's settings has blacklisted or whitelisted overmap feature flags, let's
     // filter our default batch.
     // Remove any items that have a flag that is present in the blacklist.
     if( should_blacklist ) {
         for( auto it = enabled_specials.begin(); it != enabled_specials.end(); ) {
             if( cata::sets_intersect( overmap_feature_flag.blacklist,
                                       it->special_details->get_flags() ) ) {
                 it = enabled_specials.erase( it );
             } else {
                 ++it;
             }
         }
     }
     // Remove any items which do not have any of the flags from the whitelist.
     if( should_whitelist ) {
         for( auto it = enabled_specials.begin(); it != enabled_specials.end(); ) {
             if( cata::sets_intersect( overmap_feature_flag.whitelist,
                                       it->special_details->get_flags() ) ) {
                 ++it;
             } else {
                 it = enabled_specials.erase( it );
             }
         }
     }
     populate( enabled_specials );
 }
References overmap_special_batch::begin(), overmap_feature_flag_settings::blacklist, overmap_special_batch::end(), overmap_special_batch::erase(), overmap_specials::get_default_batch(), loc, regional_settings::overmap_feature_flag, cata::sets_intersect(), settings, and overmap_feature_flag_settings::whitelist.
populate() [2/2]
void overmap::populate (overmap_special_batch & enabled_specials)
Create content in the overmap.
Definition at line 2862 of file overmap.cpp.
 {
     try {
         open( enabled_specials );
     } catch( const std::exception &err ) {
         debugmsg( "overmap (%d,%d) failed to load: %s", loc.x(), loc.y(), err.what() );
     }
 }
References debugmsg, loc, open(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by overmapbuffer::create_custom_overmap(), and overmapbuffer::get().
populate_connections_out_from_neighbors()
void overmap::populate_connections_out_from_neighbors (const overmap * north, const overmap * east, const overmap * south, const overmap * west) private
Definition at line 4332 of file overmap.cpp.
 {
     const auto populate_for_side =
         [&]( const overmap * adjacent,
              const std::function<bool( const tripoint_om_omt & )> &should_include,
     const std::function<tripoint_om_omt( const tripoint_om_omt & )> &build_point ) {
         if( adjacent == nullptr ) {
             return;
         }
         for( const std::pair<const string_id<overmap_connection>, std::vector<tripoint_om_omt>> &kv :
              adjacent->connections_out ) {
             std::vector<tripoint_om_omt> &out = connections_out[kv.first];
             const auto adjacent_out = adjacent->connections_out.find( kv.first );
             if( adjacent_out != adjacent->connections_out.end() ) {
                 for( const tripoint_om_omt &p : adjacent_out->second ) {
                     if( should_include( p ) ) {
                         out.push_back( build_point( p ) );
                     }
                 }
             }
         }
     };
     populate_for_side( north, []( const tripoint_om_omt & p ) {
         return p.y() == OMAPY - 1;
     }, []( const tripoint_om_omt & p ) {
         return tripoint_om_omt( p.x(), 0, p.z() );
     } );
     populate_for_side( west, []( const tripoint_om_omt & p ) {
         return p.x() == OMAPX - 1;
     }, []( const tripoint_om_omt & p ) {
         return tripoint_om_omt( 0, p.y(), p.z() );
     } );
     populate_for_side( south, []( const tripoint_om_omt & p ) {
         return p.y() == 0;
     }, []( const tripoint_om_omt & p ) {
         return tripoint_om_omt( p.x(), OMAPY - 1, p.z() );
     } );
     populate_for_side( east, []( const tripoint_om_omt & p ) {
         return p.x() == 0;
     }, []( const tripoint_om_omt & p ) {
         return tripoint_om_omt( OMAPX - 1, p.y(), p.z() );
     } );
 }
References connections_out, east, north, OMAPX, OMAPY, south, west, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by generate().
pos()
const point_abs_om& overmap::pos () const inline
Definition at line 200 of file overmap.h.
{
             return loc;
         }
References loc.
Referenced by build_connection(), calculate_forestosity(), calculate_urbanity(), find_extras(), find_notes(), find_terrain(), overmapbuffer::fix_mongroups(), overmapbuffer::fix_nemesis(), overmapbuffer::fix_npcs(), generate(), generate_sub(), overmapbuffer::get(), overmapbuffer::get_existing(), is_omt_generated(), lay_out_street(), load_monster_groups(), migrate_oter_ids(), move_hordes(), place_cities(), place_mongroups(), place_oceans(), overmapbuffer::place_special(), place_special(), place_specials(), place_swamps(), overmap_ui::search(), serialize(), signal_hordes(), spawn_mon_group(), unserialize(), and unserialize_omap().
predecessors()
std::vector< oter_id > overmap::predecessors (const tripoint_om_omt & p)
Definition at line 2999 of file overmap.cpp.
 {
     auto it = predecessors_.find( p );
     if( it == predecessors_.end() ) {
         return {};
     }
     return it->second;
 }
References predecessors_.
Referenced by overmapbuffer::predecessors(), and unserialize().
process_mongroups()
void overmap::process_mongroups () private
Definition at line 3911 of file overmap.cpp.
 {
     for( auto it = zg.begin(); it != zg.end(); ) {
         mongroup &mg = it->second;
         if( mg.dying ) {
             mg.population = ( mg.population * 4 ) / 5;
         }
         if( mg.empty() ) {
             zg.erase( it++ );
         } else {
             ++it;
         }
     }
 }
References mongroup::dying, mongroup::empty(), mongroup::population, and zg.
random_special_rotation()
om_direction::type overmap::random_special_rotation (const overmap_special & special, const tripoint_om_omt & p, bool must_be_unexplored) const
Definition at line 6536 of file overmap.cpp.
 {
     std::vector<om_direction::type> rotations( om_direction::size );
     const auto first = rotations.begin();
     auto last = first;
     int top_score = 0; // Maximal number of existing connections (roads).
     // Try to find the most suitable rotation: satisfy as many connections
     // as possible with the existing terrain.
     for( om_direction::type r : om_direction::all ) {
         int score = special.score_rotation_at( *this, p, r );
         if( score >= top_score ) {
             if( score > top_score ) {
                 top_score = score;
                 last = first; // New top score. Forget previous rotations.
             }
             *last = r;
             ++last;
         }
         if( !special.is_rotatable() ) {
             break;
         }
     }
     // Pick first valid rotation at random.
     std::shuffle( first, last, rng_get_engine() );
     const auto rotation = std::find_if( first, last, [&]( om_direction::type elem ) {
         return can_place_special( special, p, elem, must_be_unexplored );
     } );
     return rotation != last ? *rotation : om_direction::type::invalid;
 }
References om_direction::all, can_place_special(), om_direction::invalid, overmap_special::is_rotatable(), last, rng_get_engine(), overmap_special::score_rotation_at(), and om_direction::size.
Referenced by place_special_attempt().
remove_nemesis()
bool overmap::remove_nemesis () private
Definition at line 4257 of file overmap.cpp.
 {
     //cycle through zombie groups, find nemesis horde
     for( std::multimap<tripoint_om_sm, mongroup>::iterator it = zg.begin(); it != zg.end(); ) {
         mongroup &mg = it->second;
         if( mg.behaviour == mongroup::horde_behaviour::nemesis ) {
             zg.erase( it++ );
             return true;
         }
         it++;
     }
     return false;
 }
References mongroup::behaviour, mongroup::nemesis, and zg.
reset_oter_id_migrations()
void overmap::reset_oter_id_migrations () static
Definition at line 3953 of file overmap.cpp.
 {
     oter_id_migrations.clear();
 }
References oter_id_migrations.
Referenced by DynamicDataLoader::unload_data().
save()
void overmap::save () const
Definition at line 7223 of file overmap.cpp.
 {
     write_to_file( overmapbuffer::player_filename( loc ), [&]( std::ostream & stream ) {
         serialize_view( stream );
     } );
     write_to_file( overmapbuffer::terrain_filename( loc ), [&]( std::ostream & stream ) {
         serialize( stream );
     } );
 }
References loc, overmapbuffer::player_filename(), serialize(), serialize_view(), overmapbuffer::terrain_filename(), and write_to_file().
save_monster_groups()
void overmap::save_monster_groups (JsonOut & jo) const private
Definition at line 1105 of file savegame.cpp.
 {
     jout.member( "monster_groups" );
     jout.start_array();
     // Bin groups by their fields, except positions and monsters
     std::unordered_map<mongroup, std::list<tripoint_om_sm>, mongroup_hash, mongroup_bin_eq>
     binned_groups;
     binned_groups.reserve( zg.size() );
     for( const auto &pos_group : zg ) {
         // Each group in bin adds only position
         // so that 100 identical groups are 1 group data and 100 tripoints
         std::list<tripoint_om_sm> &positions = binned_groups[pos_group.second];
         positions.emplace_back( pos_group.first );
     }
     for( auto &group_bin : binned_groups ) {
         jout.start_array();
         // Zero the bin position so that it isn't serialized
         // The position is stored separately, in the list
         // TODO: Do it without the copy
         mongroup saved_group = group_bin.first;
         saved_group.abs_pos = tripoint_abs_sm();
         jout.write( saved_group );
         jout.write( group_bin.second );
         jout.end_array();
     }
     jout.end_array();
 }
References mongroup::abs_pos, JsonOut::end_array(), JsonOut::member(), JsonOut::start_array(), JsonOut::write(), and zg.
Referenced by serialize().
scent_at()
const scent_trace & overmap::scent_at (const tripoint_abs_omt & loc) const
Getter for overmap scents.
Returns
a reference to a scent_trace from the requested location.
Definition at line 3351 of file overmap.cpp.
 {
     static const scent_trace null_scent;
     const auto &scent_found = scents.find( loc );
     if( scent_found != scents.end() ) {
         return scent_found->second;
     }
     return null_scent;
 }
References loc, and scents.
seen()
bool overmap::seen (const tripoint_om_omt & p) const
Definition at line 3025 of file overmap.cpp.
 {
     if( !inbounds( p ) ) {
         return false;
     }
     return layer[p.z() + OVERMAP_DEPTH].visible[p.xy()];
 }
References inbounds(), layer, OVERMAP_DEPTH, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by add_extra_note(), find_terrain(), overmap_ui::search(), and set_seen().
serialize()
void overmap::serialize (std::ostream & fout) const
Definition at line 1134 of file savegame.cpp.
 {
     fout << "# version " << savegame_version << std::endl;
     JsonOut json( fout, false );
     json.start_object();
     json.member( "layers" );
     json.start_array();
     for( int z = 0; z < OVERMAP_LAYERS; ++z ) {
         const auto &layer_terrain = layer[z].terrain;
         int count = 0;
         oter_id last_tertype( -1 );
         json.start_array();
         for( int j = 0; j < OMAPY; j++ ) {
             // NOLINTNEXTLINE(modernize-loop-convert)
             for( int i = 0; i < OMAPX; i++ ) {
                 oter_id t = layer_terrain[i][j];
                 if( t != last_tertype ) {
                     if( count ) {
                         json.write( count );
                         json.end_array();
                     }
                     last_tertype = t;
                     json.start_array();
                     json.write( t.id() );
                     count = 1;
                 } else {
                     count++;
                 }
             }
         }
         json.write( count );
         // End the last entry for a z-level.
         json.end_array();
         // End the z-level
         json.end_array();
         // Insert a newline occasionally so the file isn't totally unreadable.
         fout << std::endl;
     }
     json.end_array();
     // temporary, to allow user to manually switch regions during play until regionmap is done.
     json.member( "region_id", settings->id );
     fout << std::endl;
     save_monster_groups( json );
     fout << std::endl;
     json.member( "cities" );
     json.start_array();
     for( const city &i : cities ) {
         json.start_object();
         json.member( "name", i.name );
         json.member( "id", i.id );
         json.member( "database_id", i.database_id );
         json.member( "pos_om", i.pos_om );
         json.member( "pos", i.pos );
         json.member( "population", i.population );
         json.member( "size", i.size );
         json.end_object();
     }
     json.end_array();
     fout << std::endl;
     json.member( "connections_out", connections_out );
     fout << std::endl;
     json.member( "radios" );
     json.start_array();
     for( const radio_tower &i : radios ) {
         json.start_object();
         json.member( "x", i.pos.x() );
         json.member( "y", i.pos.y() );
         json.member( "strength", i.strength );
         json.member( "type", radio_type_names[i.type] );
         json.member( "message", i.message );
         json.member( "frequency", i.frequency );
         json.end_object();
     }
     json.end_array();
     fout << std::endl;
     json.member( "monster_map" );
     json.start_array();
     for( const auto &i : monster_map ) {
         i.first.serialize( json );
         i.second.serialize( json );
     }
     json.end_array();
     fout << std::endl;
     json.member( "tracked_vehicles" );
     json.start_array();
     for( const auto &i : vehicles ) {
         json.start_object();
         json.member( "id", i.first );
         json.member( "name", i.second.name );
         json.member( "x", i.second.p.x() );
         json.member( "y", i.second.p.y() );
         json.end_object();
     }
     json.end_array();
     fout << std::endl;
     json.member( "scent_traces" );
     json.start_array();
     for( const auto &scent : scents ) {
         json.start_object();
         json.member( "pos", scent.first );
         json.member( "time", scent.second.creation_time );
         json.member( "strength", scent.second.initial_strength );
         json.end_object();
     }
     json.end_array();
     fout << std::endl;
     json.member( "npcs" );
     json.start_array();
     for( const auto &i : npcs ) {
         json.write( *i );
     }
     json.end_array();
     fout << std::endl;
     json.member( "camps" );
     json.start_array();
     for( const basecamp &i : camps ) {
         json.write( i );
     }
     json.end_array();
     fout << std::endl;
     // Condense the overmap special placements so that all placements of a given special
     // are grouped under a single key for that special.
     std::map<overmap_special_id, std::vector<tripoint_om_omt>> condensed_overmap_special_placements;
     for( const auto &placement : overmap_special_placements ) {
         condensed_overmap_special_placements[placement.second].emplace_back( placement.first );
     }
     json.member( "overmap_special_placements" );
     json.start_array();
     for( const auto &placement : condensed_overmap_special_placements ) {
         json.start_object();
         json.member( "special", placement.first );
         json.member( "placements" );
         json.start_array();
         // When we have a discriminator for different instances of a given special,
         // we'd use that that group them, but since that doesn't exist yet we'll
         // dump all the points of a given special into a single entry.
         json.start_object();
         json.member( "points" );
         json.start_array();
         for( const tripoint_om_omt &pos : placement.second ) {
             json.start_object();
             json.member( "p", pos );
             json.end_object();
         }
         json.end_array();
         json.end_object();
         json.end_array();
         json.end_object();
     }
     json.end_array();
     fout << std::endl;
     json.member( "mapgen_arg_storage", mapgen_arg_storage );
     fout << std::endl;
     json.member( "mapgen_arg_index" );
     json.start_array();
     for( const std::pair<const tripoint_om_omt, std::optional<mapgen_arguments> *> &p :
          mapgen_args_index ) {
         json.start_array();
         json.write( p.first );
         auto it = mapgen_arg_storage.get_iterator_from_pointer( p.second );
         int index = mapgen_arg_storage.get_index_from_iterator( it );
         json.write( index );
         json.end_array();
     }
     json.end_array();
     fout << std::endl;
     std::vector<std::pair<om_pos_dir, std::string>> flattened_joins_used(
                 joins_used.begin(), joins_used.end() );
     json.member( "joins_used", flattened_joins_used );
     fout << std::endl;
     std::vector<std::pair<tripoint_om_omt, std::vector<oter_id>>> flattened_predecessors(
         predecessors_.begin(), predecessors_.end() );
     json.member( "predecessors", flattened_predecessors );
     fout << std::endl;
     json.end_object();
     fout << std::endl;
 }
References camps, cities, connections_out, JsonOut::end_array(), JsonOut::end_object(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::get_index_from_iterator(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::get_iterator_from_pointer(), int_id< T >::id(), regional_settings::id, joins_used, layer, mapgen_arg_storage, mapgen_args_index, JsonOut::member(), monster_map, npcs, OMAPX, OMAPY, OVERMAP_LAYERS, overmap_special_placements, pos(), predecessors_, radio_type_names, radios, save_monster_groups(), savegame_version, scents, settings, JsonOut::start_array(), JsonOut::start_object(), and JsonOut::write().
Referenced by save().
serialize_view()
void overmap::serialize_view (std::ostream & fout) const
Definition at line 1011 of file savegame.cpp.
 {
     fout << "# version " << savegame_version << std::endl;
     JsonOut json( fout, false );
     json.start_object();
     json.member( "visible" );
     json.start_array();
     for( int z = 0; z < OVERMAP_LAYERS; ++z ) {
         json.start_array();
         serialize_array_to_compacted_sequence( json, layer[z].visible );
         json.end_array();
         fout << std::endl;
     }
     json.end_array();
     json.member( "explored" );
     json.start_array();
     for( int z = 0; z < OVERMAP_LAYERS; ++z ) {
         json.start_array();
         serialize_array_to_compacted_sequence( json, layer[z].explored );
         json.end_array();
         fout << std::endl;
     }
     json.end_array();
     json.member( "notes" );
     json.start_array();
     for( int z = 0; z < OVERMAP_LAYERS; ++z ) {
         json.start_array();
         for( const om_note &i : layer[z].notes ) {
             json.start_array();
             json.write( i.p.x() );
             json.write( i.p.y() );
             json.write( i.text );
             json.write( i.dangerous );
             json.write( i.danger_radius );
             json.end_array();
             fout << std::endl;
         }
         json.end_array();
     }
     json.end_array();
     json.member( "extras" );
     json.start_array();
     for( int z = 0; z < OVERMAP_LAYERS; ++z ) {
         json.start_array();
         for( const om_map_extra &i : layer[z].extras ) {
             json.start_array();
             json.write( i.p.x() );
             json.write( i.p.y() );
             json.write( i.id );
             json.end_array();
             fout << std::endl;
         }
         json.end_array();
     }
     json.end_array();
     json.end_object();
 }
References JsonOut::end_array(), JsonOut::end_object(), explored(), anonymous_namespace{map_extras.cpp}::extras, layer, JsonOut::member(), OVERMAP_LAYERS, savegame_version, serialize_array_to_compacted_sequence(), JsonOut::start_array(), JsonOut::start_object(), and JsonOut::write().
Referenced by save().
set_scent()
void overmap::set_scent (const tripoint_abs_omt & loc, const scent_trace & new_scent)
Setter for overmap scents, stores the provided scent at the provided location.
Definition at line 3361 of file overmap.cpp.
 {
     // TODO: increase strength of scent trace when applied repeatedly in a short timespan.
     scents[loc] = new_scent;
 }
References loc, and scents.
Referenced by overmapbuffer::set_scent().
set_seen()
void overmap::set_seen (const tripoint_om_omt & p, bool val)
Definition at line 3008 of file overmap.cpp.
 {
     if( !inbounds( p ) ) {
         return;
     }
     if( seen( p ) == val ) {
         return;
     }
     layer[p.z() + OVERMAP_DEPTH].visible[p.xy()] = val;
     if( val ) {
         add_extra_note( p );
     }
 }
References add_extra_note(), inbounds(), layer, OVERMAP_DEPTH, seen(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by debug_menu::debug(), and overmapbuffer::set_seen().
signal_hordes()
void overmap::signal_hordes (const tripoint_rel_sm & p_rel, int sig_power) private
Parameters
p location of signal relative to this overmap origin
sig_power - power of signal or max distance for reaction of zombies
Definition at line 4275 of file overmap.cpp.
 {
     tripoint_om_sm p( p_rel.raw() );
     tripoint_abs_sm absp = project_combine( pos(), p );
     for( auto &elem : zg ) {
         mongroup &mg = elem.second;
         if( !mg.horde ) {
             continue;
         }
         const int dist = rl_dist( absp, mg.abs_pos );
         if( sig_power < dist ) {
             continue;
         }
         if( mg.behaviour == mongroup::horde_behaviour::nemesis ) {
             // nemesis hordes are signaled to the player by their own function and dont react to noise
             continue;
         }
         // TODO: base this in monster attributes, foremost GOODHEARING.
         const int inter_per_sig_power = 15; //Interest per signal value
         const int min_initial_inter = 30; //Min initial interest for horde
         const int calculated_inter = ( sig_power + 1 - dist ) * inter_per_sig_power; // Calculated interest
         const int roll = rng( 0, mg.interest );
         // Minimum capped calculated interest. Used to give horde enough interest to really investigate the target at start.
         const int min_capped_inter = std::max( min_initial_inter, calculated_inter );
         if( roll < min_capped_inter ) { //Rolling if horde interested in new signal
             // TODO: Z-coordinate for mongroup targets
             const int targ_dist = rl_dist( absp.xy(), mg.target );
             // TODO: Base this on targ_dist:dist ratio.
             if( targ_dist < 5 ) {  // If signal source already pursued by horde
                 mg.set_target( midpoint( mg.target, absp.xy() ) );
                 const int min_inc_inter = 3; // Min interest increase to already targeted source
                 const int inc_roll = rng( min_inc_inter, calculated_inter );
                 mg.inc_interest( inc_roll );
                 add_msg_debug( debugmode::DF_OVERMAP, "horde inc interest %d dist %d", inc_roll, dist );
             } else { // New signal source
                 mg.set_target( absp.xy() );
                 mg.set_interest( min_capped_inter );
                 add_msg_debug( debugmode::DF_OVERMAP, "horde set interest %d dist %d", min_capped_inter, dist );
             }
         }
     }
 }
References mongroup::abs_pos, add_msg_debug, mongroup::behaviour, debugmode::DF_OVERMAP, mongroup::horde, mongroup::inc_interest(), mongroup::interest, max(), midpoint(), mongroup::nemesis, pos(), coords::project_combine(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), rl_dist(), rng(), mongroup::set_interest(), mongroup::set_target(), mongroup::target, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and zg.
signal_nemesis()
void overmap::signal_nemesis (const tripoint_abs_sm & p_abs_sm) private
Definition at line 4318 of file overmap.cpp.
 {
     for( std::pair<const tripoint_om_sm, mongroup> &elem : zg ) {
         mongroup &mg = elem.second;
         if( mg.behaviour == mongroup::horde_behaviour::nemesis ) {
             // if the horde is a nemesis, we set its target directly on the player
             mg.set_target( p_abs_sm.xy() );
             mg.set_nemesis_target( p_abs_sm.xy() );
         }
     }
 }
References mongroup::behaviour, mongroup::nemesis, mongroup::set_nemesis_target(), mongroup::set_target(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and zg.
spawn_mon_group()
void overmap::spawn_mon_group (const mongroup & group, int radius) private
Definition at line 7234 of file overmap.cpp.
 {
     tripoint_om_omt pos = project_to<coords::omt>( group.rel_pos() );
     if( safe_at_worldgen.find( pos ) != safe_at_worldgen.end() ) {
         return;
     }
     add_mon_group( group, radius );
 }
References add_mon_group(), pos(), and safe_at_worldgen.
Referenced by generate_sub(), place_mongroups(), and place_special().
ter()
const oter_id & overmap::ter (const tripoint_om_omt & p) const
TODO: Add a debug message reporting this, but currently there are way too many place that would trigger it.
Definition at line 2966 of file overmap.cpp.
 {
     if( !inbounds( p ) ) {
         /// TODO: Add a debug message reporting this, but currently there are way too many place that would trigger it.
         return ot_null;
     }
     return ter_unsafe( p );
 }
References inbounds(), ot_null, and ter_unsafe().
Referenced by build_city_street(), build_connection(), build_lab(), check_ot(), chip_rock(), start_location::find_player_initial_location(), find_random_omt(), find_terrain(), generate_bridgeheads(), generate_over(), generate_sub(), good_river(), lay_out_connection(), lay_out_street(), move_hordes(), move_nemesis(), place_cities(), place_forest_trailheads(), place_forest_trails(), place_forests(), place_lakes(), place_mongroups(), place_oceans(), place_radios(), place_railroads(), place_river(), place_roads(), place_swamps(), overmap_ui::search(), overmapbuffer::ter(), and overmapbuffer::ter_existing().
ter_set()
void overmap::ter_set (const tripoint_om_omt & p, const oter_id & id)
TODO: Add a debug message reporting this, but currently there are way too many place that would trigger it.
Definition at line 2925 of file overmap.cpp.
 {
     if( !inbounds( p ) ) {
         /// TODO: Add a debug message reporting this, but currently there are way too many place that would trigger it.
         return;
     }
     oter_id &current_oter = layer[p.z() + OVERMAP_DEPTH].terrain[p.xy()];
     const oter_type_str_id &current_type_id = current_oter->get_type_id();
     const oter_type_str_id &incoming_type_id = id->get_type_id();
     const bool current_type_same = current_type_id == incoming_type_id;
     // Mapgen refinement can push multiple different roads over each other.
     // Roads require a predecessor. A road pushed over a road might cause a
     // road to be a predecessor to another road. That causes too many spawns
     // to happen. So when pushing a predecessor, if the predecessor to-be-pushed
     // is linear and the previous predecessor is linear, overwrite it.
     // This way only the 'last' rotation/variation generated is kept.
     if( id->has_flag( oter_flags::requires_predecessor ) ) {
         std::vector<oter_id> &om_predecessors = predecessors_[p];
         if( om_predecessors.empty() || ( !current_oter->is_linear() && !current_type_same ) ) {
             // If we need a predecessor, we must have a predecessor no matter what.
             // Or, if the oter to-be-pushed is not linear, push it only if the incoming oter is different.
             om_predecessors.push_back( current_oter );
         } else if( !current_type_same ) {
             // Current oter is linear, incoming oter is different from current.
             // If the last predecessor is the same type as the current type, overwrite.
             // Else push the current type.
             oter_id &last_predecessor = om_predecessors.back();
             if( last_predecessor->get_type_id() == current_type_id ) {
                 last_predecessor = current_oter;
             } else {
                 om_predecessors.push_back( current_oter );
             }
         }
         // We had a predecessor, and it was the same type as the incoming one
         // Don't push another copy.
     }
     current_oter = id;
 }
References oter_t::get_type_id(), base_camps::id, inbounds(), oter_t::is_linear(), layer, OVERMAP_DEPTH, predecessors_, requires_predecessor, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by build_city_street(), build_connection(), build_lab(), build_slimepit(), chip_rock(), generate_bridgeheads(), generate_over(), generate_sub(), good_river(), migrate_oter_ids(), place_cities(), place_forests(), place_lakes(), place_oceans(), place_ravines(), place_river(), place_rivers(), place_swamps(), overmapbuffer::ter_set(), and unserialize_omap().
ter_unsafe()
const oter_id & overmap::ter_unsafe (const tripoint_om_omt & p) const
Definition at line 2976 of file overmap.cpp.
 {
     return layer[p.z() + OVERMAP_DEPTH].terrain[p.xy()];
 }
References layer, OVERMAP_DEPTH, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by generate_sub(), place_specials(), place_swamps(), and ter().
unserialize() [1/2]
void overmap::unserialize (const cata_path & file_name, std::istream & fin)
Definition at line 396 of file savegame.cpp.
 {
     size_t json_offset = chkversion( fin );
     JsonValue jsin = json_loader::from_path_at_offset( file_name, json_offset );
     unserialize( jsin.get_object() );
 }
References chkversion(), json_loader::from_path_at_offset(), and JsonValue::get_object().
Referenced by open().
unserialize() [2/2]
void overmap::unserialize (const JsonObject & jsobj)
Definition at line 403 of file savegame.cpp.
 {
     // These must be read in this order.
     if( jsobj.has_member( "mapgen_arg_storage" ) ) {
         jsobj.read( "mapgen_arg_storage", mapgen_arg_storage, true );
     }
     if( jsobj.has_member( "mapgen_arg_index" ) ) {
         std::vector<std::pair<tripoint_om_omt, int>> flat_index;
         jsobj.read( "mapgen_arg_index", flat_index, true );
         for( const std::pair<tripoint_om_omt, int> &p : flat_index ) {
             auto it = mapgen_arg_storage.get_iterator_from_index( p.second );
             mapgen_args_index.emplace( p.first, &*it );
         }
     }
     // Extract layers first so predecessor deduplication can happen.
     if( jsobj.has_member( "layers" ) ) {
         std::unordered_map<tripoint_om_omt, std::string> oter_id_migrations;
         JsonArray layers_json = jsobj.get_array( "layers" );
         for( int z = 0; z < OVERMAP_LAYERS; ++z ) {
             JsonArray layer_json = layers_json.next_array();
             int count = 0;
             std::string tmp_ter;
             oter_id tmp_otid( 0 );
             for( int j = 0; j < OMAPY; j++ ) {
                 for( int i = 0; i < OMAPX; i++ ) {
                     if( count == 0 ) {
{
                             JsonArray rle_terrain = layer_json.next_array();
                             tmp_ter = rle_terrain.next_string();
                             count = rle_terrain.next_int();
                             if( rle_terrain.has_more() ) {
                                 rle_terrain.throw_error( 2, "Unexpected value in RLE encoding" );
                             }
                         }
                         if( is_oter_id_obsolete( tmp_ter ) ) {
                             for( int p = i; p < i + count; p++ ) {
                                 oter_id_migrations.emplace( tripoint_om_omt( p, j, z - OVERMAP_DEPTH ), tmp_ter );
                             }
                         } else if( oter_str_id( tmp_ter ).is_valid() ) {
                             tmp_otid = oter_id( tmp_ter );
                         } else {
                             debugmsg( "Loaded invalid oter_id '%s'", tmp_ter.c_str() );
                             tmp_otid = oter_omt_obsolete;
                         }
                     }
                     count--;
                     layer[z].terrain[i][j] = tmp_otid;
                 }
             }
         }
         migrate_oter_ids( oter_id_migrations );
     }
     for( JsonMember om_member : jsobj ) {
         const std::string name = om_member.name();
         if( name == "region_id" ) {
             std::string new_region_id;
             om_member.read( new_region_id );
             if( settings->id != new_region_id ) {
                 t_regional_settings_map_citr rit = region_settings_map.find( new_region_id );
                 if( rit != region_settings_map.end() ) {
                     // TODO: optimize
                     settings = &rit->second;
                 }
             }
         } else if( name == "mongroups" ) {
             load_legacy_monstergroups( om_member );
         } else if( name == "monster_groups" ) {
             load_monster_groups( om_member );
         } else if( name == "cities" ) {
             JsonArray cities_json = om_member;
             for( JsonObject city_json : cities_json ) {
                 city new_city;
                 for( JsonMember city_member : city_json ) {
                     std::string city_member_name = city_member.name();
                     if( city_member_name == "name" ) {
                         city_member.read( new_city.name );
                     } else if( city_member_name == "id" ) {
                         city_member.read( new_city.id );
                     } else if( city_member_name == "database_id" ) {
                         city_member.read( new_city.database_id );
                     } else if( city_member_name == "pos" ) {
                         city_member.read( new_city.pos );
                     } else if( city_member_name == "pos_om" ) {
                         city_member.read( new_city.pos_om );
                     } else if( city_member_name == "x" ) {
                         city_member.read( new_city.pos.x() );
                     } else if( city_member_name == "y" ) {
                         city_member.read( new_city.pos.y() );
                     } else if( city_member_name == "population" ) {
                         city_member.read( new_city.population );
                     } else if( city_member_name == "size" ) {
                         city_member.read( new_city.size );
                     }
                 }
                 cities.push_back( new_city );
             }
         } else if( name == "connections_out" ) {
             om_member.read( connections_out );
         } else if( name == "roads_out" ) {
             // Legacy data, superseded by that stored in the "connections_out" member. A load and save
             // cycle will migrate this to "connections_out".
             std::vector<tripoint_om_omt> &roads_out =
                 connections_out[overmap_connection_local_road];
             JsonArray roads_json = om_member;
             for( JsonObject road_json : roads_json ) {
                 tripoint_om_omt new_road;
                 for( JsonMember road_member : road_json ) {
                     std::string road_member_name = road_member.name();
                     if( road_member_name == "x" ) {
                         road_member.read( new_road.x() );
                     } else if( road_member_name == "y" ) {
                         road_member.read( new_road.y() );
                     }
                 }
                 roads_out.push_back( new_road );
             }
         } else if( name == "radios" ) {
             JsonArray radios_json = om_member;
             for( JsonObject radio_json : radios_json ) {
                 radio_tower new_radio{ point_om_sm( point_min ) };
                 for( JsonMember radio_member : radio_json ) {
                     const std::string radio_member_name = radio_member.name();
                     if( radio_member_name == "type" ) {
                         const std::string radio_name = radio_member.get_string();
                         const auto mapping =
                             find_if( radio_type_names.begin(), radio_type_names.end(),
                         [radio_name]( const std::pair<radio_type, std::string> &p ) {
                             return p.second == radio_name;
                         } );
                         if( mapping != radio_type_names.end() ) {
                             new_radio.type = mapping->first;
                         }
                     } else if( radio_member_name == "x" ) {
                         radio_member.read( new_radio.pos.x() );
                     } else if( radio_member_name == "y" ) {
                         radio_member.read( new_radio.pos.y() );
                     } else if( radio_member_name == "strength" ) {
                         radio_member.read( new_radio.strength );
                     } else if( radio_member_name == "message" ) {
                         radio_member.read( new_radio.message );
                     } else if( radio_member_name == "frequency" ) {
                         radio_member.read( new_radio.frequency );
                     }
                 }
                 radios.push_back( new_radio );
             }
         } else if( name == "monster_map" ) {
             JsonArray monster_map_json = om_member;
             while( monster_map_json.has_more() ) {
                 tripoint_om_sm monster_location;
                 monster new_monster;
                 monster_location.deserialize( monster_map_json.next_value() );
                 new_monster.deserialize( monster_map_json.next_object(), project_combine( loc, monster_location ) );
                 monster_map.insert( std::make_pair( monster_location,
                                                     std::move( new_monster ) ) );
             }
         } else if( name == "tracked_vehicles" ) {
             JsonArray tracked_vehicles_json = om_member;
             for( JsonObject tracked_vehicle_json : tracked_vehicles_json ) {
                 om_vehicle new_tracker;
                 int id;
                 for( JsonMember tracker_member : tracked_vehicle_json ) {
                     std::string tracker_member_name = tracker_member.name();
                     if( tracker_member_name == "id" ) {
                         tracker_member.read( id );
                     } else if( tracker_member_name == "x" ) {
                         tracker_member.read( new_tracker.p.x() );
                     } else if( tracker_member_name == "y" ) {
                         tracker_member.read( new_tracker.p.y() );
                     } else if( tracker_member_name == "name" ) {
                         tracker_member.read( new_tracker.name );
                     }
                 }
                 vehicles[id] = new_tracker;
             }
         } else if( name == "scent_traces" ) {
             JsonArray scents_json = om_member;
             for( JsonObject scent_json : scents_json ) {
                 tripoint_abs_omt pos;
                 time_point time = calendar::before_time_starts;
                 int strength = 0;
                 for( JsonMember scent_member : scent_json ) {
                     std::string scent_member_name = scent_member.name();
                     if( scent_member_name == "pos" ) {
                         scent_member.read( pos );
                     } else if( scent_member_name == "time" ) {
                         scent_member.read( time );
                     } else if( scent_member_name == "strength" ) {
                         scent_member.read( strength );
                     }
                 }
                 scents[pos] = scent_trace( time, strength );
             }
         } else if( name == "npcs" ) {
             JsonArray npcs_json = om_member;
             for( JsonObject npc_json : npcs_json ) {
                 shared_ptr_fast<npc> new_npc = make_shared_fast<npc>();
                 new_npc->deserialize( npc_json );
                 if( !new_npc->get_fac_id().str().empty() ) {
                     new_npc->set_fac( new_npc->get_fac_id() );
                 }
                 npcs.push_back( new_npc );
             }
         } else if( name == "camps" ) {
             JsonArray camps_json = om_member;
             for( JsonObject camp_json : camps_json ) {
                 basecamp new_camp;
                 new_camp.deserialize( camp_json );
                 camps.push_back( new_camp );
             }
         } else if( name == "overmap_special_placements" ) {
             JsonArray special_placements_json = om_member;
             for( JsonObject special_placement_json : special_placements_json ) {
                 overmap_special_id s;
                 bool is_safe_zone = false;
                 if( special_placement_json.has_member( "special" ) ) {
                     special_placement_json.read( "special", s );
                     s = overmap_special_migration::migrate( s );
                     if( !s.is_null() ) {
                         is_safe_zone = s->has_flag( "SAFE_AT_WORLDGEN" );
                     }
                 }
                 for( JsonMember special_placement_member : special_placement_json ) {
                     std::string name = special_placement_member.name();
                     if( name == "placements" ) {
                         JsonArray placements_json = special_placement_member;
                         for( JsonObject placement_json : placements_json ) {
                             for( JsonMember placement_member : placement_json ) {
                                 std::string name = placement_member.name();
                                 if( name == "points" ) {
                                     JsonArray points_json = placement_member;
                                     for( JsonObject point_json : points_json ) {
                                         tripoint_om_omt p;
                                         for( JsonMember point_member : point_json ) {
                                             std::string name = point_member.name();
                                             if( name == "p" ) {
                                                 point_member.read( p );
                                                 if( !s.is_null() ) {
                                                     overmap_special_placements[p] = s;
                                                     if( is_safe_zone ) {
                                                         safe_at_worldgen.emplace( p );
                                                     }
                                                 }
                                             }
                                         }
                                     }
                                 }
                             }
                         }
                     }
                 }
             }
         } else if( name == "joins_used" ) {
             std::vector<std::pair<om_pos_dir, std::string>> flat_index;
             om_member.read( flat_index, true );
             for( const std::pair<om_pos_dir, std::string> &p : flat_index ) {
                 joins_used.insert( p );
             }
         } else if( name == "predecessors" ) {
             std::vector<std::pair<tripoint_om_omt, std::vector<oter_id>>> flattened_predecessors;
             JsonArray predecessors_json = om_member;
             for( JsonArray point_and_predecessors : predecessors_json ) {
                 if( point_and_predecessors.size() != 2 ) {
                     point_and_predecessors.throw_error( 2,
                                                         "Invalid overmap predecessors: expected a point and an array" );
                 }
                 tripoint_om_omt point;
                 point_and_predecessors.read( 0, point, true );
                 std::vector<oter_id> predecessors;
                 for( std::string oterid : point_and_predecessors.get_array( 1 ) ) {
                     predecessors.push_back( get_or_migrate_oter( oterid ) );
                 }
                 flattened_predecessors.emplace_back( point, std::move( predecessors ) );
             }
             std::vector<oter_id> om_predecessors;
             for( auto& [p, serialized_predecessors] : flattened_predecessors ) {
                 if( !serialized_predecessors.empty() ) {
                     // TODO remove after 0.H release.
                     // JSONizing roads caused some bad mapgen data to get saved to disk. Fixup bad saves to conform.
                     // The logic to do this is to emulate setting overmap::set_ter repeatedly. The difference is the
                     // 'original' terrain is lost, all we have is a chain of predecessors.
                     // This doesn't matter for the sake of deduplicating predecessors.
                     //
                     // Mapgen refinement can push multiple different roads over each other.
                     // Roads require a predecessor. A road pushed over a road might cause a
                     // road to be a predecessor to another road. That causes too many spawns
                     // to happen. So when pushing a predecessor, if the predecessor to-be-pushed
                     // is linear and the previous predecessor is linear, overwrite it.
                     // This way only the 'last' rotation/variation generated is kept.
                     om_predecessors.reserve( serialized_predecessors.size() );
                     oter_id current_oter;
                     auto local_set_ter = [&]( oter_id & id ) {
                         const oter_type_str_id &current_type_id = current_oter->get_type_id();
                         const oter_type_str_id &incoming_type_id = id->get_type_id();
                         const bool current_type_same = current_type_id == incoming_type_id;
                         if( om_predecessors.empty() || ( !current_oter->is_linear() && !current_type_same ) ) {
                             // If we need a predecessor, we must have a predecessor no matter what.
                             // Or, if the oter to-be-pushed is not linear, push it only if the incoming oter is different.
                             om_predecessors.push_back( current_oter );
                         } else if( !current_type_same ) {
                             // Current oter is linear, incoming oter is different from current.
                             // If the last predecessor is the same type as the current type, overwrite.
                             // Else push the current type.
                             oter_id &last_predecessor = om_predecessors.back();
                             if( last_predecessor->get_type_id() == current_type_id ) {
                                 last_predecessor = current_oter;
                             } else {
                                 om_predecessors.push_back( current_oter );
                             }
                         }
                         current_oter = id;
                     };
                     current_oter = serialized_predecessors.front();
                     for( size_t i = 1; i < serialized_predecessors.size(); ++i ) {
                         local_set_ter( serialized_predecessors[i] );
                     }
                     local_set_ter( layer[p.z() + OVERMAP_DEPTH].terrain[p.xy()] );
                 }
                 predecessors_.insert_or_assign( p, std::move( om_predecessors ) );
                 // Reuse allocations because it's a good habit.
                 om_predecessors = std::move( serialized_predecessors );
                 om_predecessors.clear();
             }
         }
     }
 }
References calendar::before_time_starts, camps, cities, connections_out, city::database_id, debugmsg, basecamp::deserialize(), monster::deserialize(), coords::coord_point_mut< Point, Subpoint, InBounds >::deserialize(), flat_index(), JsonObject::get_array(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::get_iterator_from_index(), get_or_migrate_oter(), oter_t::get_type_id(), overmap_special::has_flag(), JsonObject::has_member(), JsonArray::has_more(), base_camps::id, city::id, regional_settings::id, oter_t::is_linear(), string_id< T >::is_null(), is_oter_id_obsolete(), joins_used, layer, load_legacy_monstergroups(), load_monster_groups(), loc, mapgen_arg_storage, mapgen_args_index, overmap_special_migration::migrate(), migrate_oter_ids(), monster_map, city::name, om_direction::name(), om_vehicle::name, JsonArray::next_array(), JsonArray::next_int(), JsonArray::next_object(), JsonArray::next_string(), JsonArray::next_value(), npcs, OMAPX, OMAPY, oter_id, oter_id_migrations, oter_omt_obsolete, overmap_connection_local_road, OVERMAP_DEPTH, OVERMAP_LAYERS, overmap_special_placements, om_vehicle::p, point, point_min, city::population, city::pos, pos(), city::pos_om, predecessors(), predecessors_, coords::project_combine(), radio_type_names, radios, JsonObject::read(), region_settings_map, safe_at_worldgen, scents, settings, city::size, strength, JsonArray::throw_error(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
unserialize_omap()
void overmap::unserialize_omap (const JsonValue & jsin, const cata_path & json_path)
Definition at line 736 of file savegame.cpp.
 {
     JsonArray ja = jsin.get_array();
     JsonObject jo = ja.next_object();
     std::string type;
     point_abs_om om_pos( point_min );
     int z = 0;
     jo.read( "type", type );
     jo.read( "om_pos", om_pos );
     jo.read( "z", z );
     JsonArray jal = jo.get_array( "layers" );
     std::vector<tripoint_om_omt> lake_points;
     std::vector<tripoint_om_omt> ocean_points;
     std::vector<tripoint_om_omt> forest_points;
     if( type == "overmap" ) {
         std::unordered_map<tripoint_om_omt, std::string> oter_id_migrations;
         if( om_pos != pos() ) {
             debugmsg( "Loaded invalid overmap from omap file %s. Loaded %s, expected %s",
                       json_path.generic_u8string(), om_pos.to_string(), pos().to_string() );
         } else {
             int count = 0;
             std::string tmp_ter;
             oter_id tmp_otid( 0 );
             for( int j = 0; j < OMAPY; j++ ) {
                 for( int i = 0; i < OMAPX; i++ ) {
                     if( count == 0 ) {
                         JsonArray jat = jal.next_array();
                         tmp_ter = jat.next_string();
                         count = jat.next_int();
                         if( is_oter_id_obsolete( tmp_ter ) ) {
                             for( int p = i; p < i + count; p++ ) {
                                 oter_id_migrations.emplace( tripoint_om_omt( p, j, z - OVERMAP_DEPTH ), tmp_ter );
                             }
                         } else if( oter_str_id( tmp_ter ).is_valid() ) {
                             tmp_otid = oter_id( tmp_ter );
                         } else {
                             debugmsg( "Loaded invalid oter_id '%s'", tmp_ter.c_str() );
                             tmp_otid = oter_omt_obsolete;
                         }
                     }
                     count--;
                     layer[z + OVERMAP_DEPTH].terrain[i][j] = tmp_otid;
                     if( tmp_otid == oter_lake_shore || tmp_otid == oter_lake_surface ) {
                         lake_points.emplace_back( i, j, z );
                     }
                     if( tmp_otid == oter_ocean_shore || tmp_otid == oter_ocean_surface ) {
                         ocean_points.emplace_back( i, j, z );
                     }
                     if( tmp_otid == oter_forest || tmp_otid == oter_forest_thick ) {
                         forest_points.emplace_back( i, j, z );
                     }
                 }
             }
         }
         migrate_oter_ids( oter_id_migrations );
     }
     std::unordered_set<tripoint_om_omt> lake_set;
     for( auto &p : lake_points ) {
         lake_set.emplace( p );
     }
     for( auto &p : lake_points ) {
         if( !inbounds( p ) ) {
             continue;
         }
         bool shore = false;
         for( int ni = -1; ni <= 1 && !shore; ni++ ) {
             for( int nj = -1; nj <= 1 && !shore; nj++ ) {
                 const tripoint_om_omt n = p + point( ni, nj );
                 if( inbounds( n, 1 ) && lake_set.find( n ) == lake_set.end() ) {
                     shore = true;
                 }
             }
         }
         ter_set( tripoint_om_omt( p ), shore ? oter_lake_shore : oter_lake_surface );
         // If this is not a shore, we'll make our subsurface lake cubes and beds.
         if( !shore ) {
             for( int z = -1; z > settings->overmap_lake.lake_depth; z-- ) {
                 ter_set( tripoint_om_omt( p.xy(), z ), oter_lake_water_cube );
             }
             ter_set( tripoint_om_omt( p.xy(), settings->overmap_lake.lake_depth ), oter_lake_bed );
             layer[p.z() + OVERMAP_DEPTH].terrain[p.x()][p.y()] = oter_lake_surface;
         }
     }
     std::unordered_set<tripoint_om_omt> ocean_set;
     for( auto &p : ocean_points ) {
         ocean_set.emplace( p );
     }
     for( auto &p : ocean_points ) {
         if( !inbounds( p ) ) {
             continue;
         }
         bool shore = false;
         for( int ni = -1; ni <= 1 && !shore; ni++ ) {
             for( int nj = -1; nj <= 1 && !shore; nj++ ) {
                 const tripoint_om_omt n = p + point( ni, nj );
                 if( inbounds( n, 1 ) && ocean_set.find( n ) == ocean_set.end() ) {
                     shore = true;
                 }
             }
         }
         ter_set( tripoint_om_omt( p ), shore ? oter_ocean_shore : oter_ocean_surface );
         // If this is not a shore, we'll make our subsurface ocean cubes and beds.
         if( !shore ) {
             for( int z = -1; z > settings->overmap_ocean.ocean_depth; z-- ) {
                 ter_set( tripoint_om_omt( p.xy(), z ), oter_ocean_water_cube );
             }
             ter_set( tripoint_om_omt( p.xy(), settings->overmap_ocean.ocean_depth ), oter_ocean_bed );
             layer[p.z() + OVERMAP_DEPTH].terrain[p.x()][p.y()] = oter_ocean_surface;
         }
     }
     std::unordered_set<tripoint_om_omt> forest_set;
     for( auto &p : forest_points ) {
         forest_set.emplace( p );
     }
     for( auto &p : forest_points ) {
         if( !inbounds( p ) ) {
             continue;
         }
         bool forest_border = false;
         for( int ni = -1; ni <= 1 && !forest_border; ni++ ) {
             for( int nj = -1; nj <= 1 && !forest_border; nj++ ) {
                 const tripoint_om_omt n = p + point( ni, nj );
                 if( inbounds( n, 1 ) && forest_set.find( n ) == forest_set.end() ) {
                     forest_border = true;
                 }
             }
         }
         ter_set( tripoint_om_omt( p ), forest_border ? oter_forest : oter_forest_thick );
     }
 }
References debugmsg, cata_path::generic_u8string(), JsonValue::get_array(), JsonObject::get_array(), inbounds(), is_oter_id_obsolete(), overmap_lake_settings::lake_depth, layer, migrate_oter_ids(), JsonArray::next_array(), JsonArray::next_int(), JsonArray::next_object(), JsonArray::next_string(), overmap_ocean_settings::ocean_depth, OMAPX, OMAPY, oter_forest, oter_forest_thick, oter_id, oter_id_migrations, oter_lake_bed, oter_lake_shore, oter_lake_surface, oter_lake_water_cube, oter_ocean_bed, oter_ocean_shore, oter_ocean_surface, oter_ocean_water_cube, oter_omt_obsolete, OVERMAP_DEPTH, regional_settings::overmap_lake, regional_settings::overmap_ocean, point, point_min, pos(), JsonObject::read(), settings, shore, ter_set(), coords::coord_point_base< Point >::to_string(), to_string(), and type.
Referenced by generate().
unserialize_view() [1/2]
void overmap::unserialize_view (const cata_path & file_name, std::istream & fin)
Definition at line 904 of file savegame.cpp.
 {
     size_t json_offset = chkversion( fin );
     JsonValue jsin = json_loader::from_path_at_offset( file_name, json_offset );
     unserialize_view( jsin.get_object() );
 }
References chkversion(), json_loader::from_path_at_offset(), and JsonValue::get_object().
Referenced by open().
unserialize_view() [2/2]
void overmap::unserialize_view (const JsonObject & jsobj)
Definition at line 911 of file savegame.cpp.
 {
     for( JsonMember view_member : jsobj ) {
         const std::string name = view_member.name();
         if( name == "visible" ) {
             JsonArray visible_json = view_member;
             for( int z = 0; z < OVERMAP_LAYERS; ++z ) {
                 JsonArray visible_by_z_json = visible_json.next_array();
                 unserialize_array_from_compacted_sequence( visible_by_z_json, layer[z].visible );
                 if( visible_by_z_json.has_more() ) {
                     visible_by_z_json.throw_error( "Too many sequences for z visible view" );
                 }
             }
             if( visible_json.has_more() ) {
                 visible_json.throw_error( "Too many views by z count" );
             }
         } else if( name == "explored" ) {
             JsonArray explored_json = view_member;
             for( int z = 0; z < OVERMAP_LAYERS; ++z ) {
                 JsonArray explored_by_z_json = explored_json.next_array();
                 unserialize_array_from_compacted_sequence( explored_by_z_json, layer[z].explored );
                 if( explored_by_z_json.has_more() ) {
                     explored_by_z_json.throw_error( "Too many sequences for z explored view" );
                 }
             }
             if( explored_json.has_more() ) {
                 explored_json.throw_error( "Too many views by z count" );
             }
         } else if( name == "notes" ) {
             JsonArray notes_json = view_member;
             for( int z = 0; z < OVERMAP_LAYERS; ++z ) {
                 JsonArray notes_by_z_json = notes_json.next_array();
                 for( JsonArray note_json : notes_by_z_json ) {
                     om_note tmp;
                     note_json.read_next( tmp.p.x() );
                     note_json.read_next( tmp.p.y() );
                     note_json.read_next( tmp.text );
                     note_json.read_next( tmp.dangerous );
                     note_json.read_next( tmp.danger_radius );
                     if( note_json.size() > 5 ) {
                         note_json.throw_error( "Too many values for note" );
                     }
                     layer[z].notes.push_back( tmp );
                 }
             }
             if( notes_json.has_more() ) {
                 notes_json.throw_error( "Too many notes by z count" );
             }
         } else if( name == "extras" ) {
             JsonArray extras_json = view_member;
             for( int z = 0; z < OVERMAP_LAYERS; ++z ) {
                 JsonArray extras_by_z = extras_json.next_array();
                 for( JsonArray extra_json : extras_by_z ) {
                     om_map_extra tmp;
                     extra_json.read_next( tmp.p.x() );
                     extra_json.read_next( tmp.p.y() );
                     extra_json.read_next( tmp.id );
                     if( extra_json.has_more() ) {
                         extra_json.throw_error( "Too many values for extra" );
                     }
                     layer[z].extras.push_back( tmp );
                 }
             }
             if( extras_json.has_more() ) {
                 extras_json.throw_error( "Too many extras by z count" );
             }
         }
     }
 }
References om_note::danger_radius, om_note::dangerous, explored(), JsonArray::has_more(), om_map_extra::id, layer, om_direction::name(), JsonArray::next_array(), OVERMAP_LAYERS, om_note::p, om_map_extra::p, om_note::text, JsonArray::throw_error(), unserialize_array_from_compacted_sequence(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Friends And Related Function Documentation
overmapbuffer
friend class overmapbuffer friend
Definition at line 342 of file overmap.h.
Member Data Documentation
camps
std::vector<basecamp> overmap::camps
Definition at line 324 of file overmap.h.
Referenced by overmapbuffer::add_camp(), find_camp(), overmapbuffer::has_camp(), overmapbuffer::remove_camp(), serialize(), talk_function::start_camp(), and unserialize().
cities
std::vector<city> overmap::cities
Definition at line 325 of file overmap.h.
Referenced by clear_cities(), generate_sub(), get_nearest_city(), place_cities(), place_mongroups(), place_railroads(), place_roads(), serialize(), unserialize(), and debug_menu::write_city_list().
connections_out
std::map<string_id<overmap_connection>, std::vector<tripoint_om_omt> > overmap::connections_out
Definition at line 326 of file overmap.h.
Referenced by build_connection(), clear_connections_out(), place_railroads(), place_roads(), populate_connections_out_from_neighbors(), serialize(), and unserialize().
forest_size_adjust
float overmap::forest_size_adjust = 0.0f private
Definition at line 461 of file overmap.h.
Referenced by calculate_forestosity(), and place_forests().
forestosity
float overmap::forestosity = 0.0f private
Definition at line 463 of file overmap.h.
Referenced by calculate_forestosity(), and place_cities().
invalid_tripoint
constexpr tripoint_abs_omt overmap::invalid_tripoint { tripoint_min } static constexpr
Dummy value, used to indicate that a point returned by a function is invalid.
Definition at line 277 of file overmap.h.
Referenced by computer_session::action_miss_launch(), disp_overmap_cache::disp_overmap_cache(), overmap_ui::display(), overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal(), overmapbuffer::find_closest(), find_or_create_om_terrain(), start_location::find_player_initial_location(), overmapbuffer::find_random(), avatar::get_active_mission_target(), overmapbuffer::get_travel_path(), talk_function::goto_location(), mission::has_target(), talk_function::hospital_raid_return(), mission_start::kill_nemesis(), debug_menu::map_extra(), om_target_tile(), display::overmap_tile_symbol_color(), mission_start::place_deposit_box(), reveal_destination(), mission_util::reveal_om_ter(), overmapbuffer::reveal_route(), reveal_target(), npc::set_omt_destination(), mission::set_target_to_mission_giver(), game::start_game(), basecamp::survey_field_return(), basecamp::survey_return(), mission_util::target_closest_lab_entrance(), mission_util::target_om_ter_random(), debug_menu::teleport_long(), and update_mapgen_function_json::update_map().
joins_used
std::unordered_map<om_pos_dir, std::string> overmap::joins_used private
Definition at line 374 of file overmap.h.
Referenced by join_used_at(), place_special(), serialize(), and unserialize().
layer
std::array<map_layer, OVERMAP_LAYERS> overmap::layer private
Definition at line 351 of file overmap.h.
Referenced by add_extra(), add_extra_note(), add_note(), explored(), extra(), find_extras(), find_notes(), generate(), has_extra(), has_note(), init_layers(), is_explored(), is_marked_dangerous(), mark_note_dangerous(), note(), note_danger_radius(), seen(), serialize(), serialize_view(), set_seen(), ter_set(), ter_unsafe(), unserialize(), unserialize_omap(), and unserialize_view().
loc
point_abs_om overmap::loc private
Definition at line 349 of file overmap.h.
Referenced by global_base_point(), is_omt_generated(), open(), populate(), pos(), save(), scent_at(), set_scent(), and unserialize().
mapgen_arg_storage
cata::colony<std::optional<mapgen_arguments> > overmap::mapgen_arg_storage private
Definition at line 369 of file overmap.h.
Referenced by place_special(), serialize(), and unserialize().
mapgen_args_index
std::unordered_map<tripoint_om_omt, std::optional<mapgen_arguments> *> overmap::mapgen_args_index private
Definition at line 370 of file overmap.h.
Referenced by mapgen_args(), place_special(), serialize(), and unserialize().
monster_map
std::unordered_multimap<tripoint_om_sm, monster> overmap::monster_map
When monsters despawn during map-shifting they will be added here.
map::spawn_monsters will load them and place them into the reality bubble (adding it to the creature tracker and putting it onto the map). This stores each submap worth of monsters in a different bucket of the multimap.
Definition at line 392 of file overmap.h.
Referenced by monster_check(), move_hordes(), serialize(), and unserialize().
npcs
std::vector<shared_ptr_fast<npc> > overmap::npcs private
Definition at line 344 of file overmap.h.
Referenced by erase_npc(), find_npc(), find_npc_by_unique_id(), overmapbuffer::fix_npcs(), get_npcs(), overmapbuffer::get_overmap_npcs(), insert_npc(), serialize(), and unserialize().
nullbool
bool overmap::nullbool = false private
Definition at line 348 of file overmap.h.
Referenced by explored().
overmap_special_placements
std::unordered_map<tripoint_om_omt, overmap_special_id> overmap::overmap_special_placements private
Definition at line 357 of file overmap.h.
Referenced by check_overmap_special_type(), clear_overmap_special_placements(), overmap_special_at(), place_special(), serialize(), and unserialize().
predecessors_
std::unordered_map<tripoint_om_omt, std::vector<oter_id> > overmap::predecessors_ private
Definition at line 364 of file overmap.h.
Referenced by predecessors(), serialize(), ter_set(), and unserialize().
radios
std::vector<radio_tower> overmap::radios
Definition at line 322 of file overmap.h.
Referenced by place_radios(), serialize(), and unserialize().
safe_at_worldgen
std::unordered_set<tripoint_om_omt> overmap::safe_at_worldgen private
Definition at line 360 of file overmap.h.
Referenced by place_special(), spawn_mon_group(), and unserialize().
scents
std::unordered_map<tripoint_abs_omt, scent_trace> overmap::scents private
Definition at line 352 of file overmap.h.
Referenced by scent_at(), serialize(), set_scent(), and unserialize().
settings
const regional_settings* overmap::settings private
Definition at line 376 of file overmap.h.
Referenced by calculate_forestosity(), calculate_ocean_gradient(), generate_sub(), get_default_terrain(), get_settings(), overmap(), pick_random_building_to_place(), place_cities(), place_forest_trailheads(), place_forest_trails(), place_forests(), place_lakes(), place_mongroups(), place_oceans(), place_railroads(), place_ravines(), place_river(), place_rivers(), place_roads(), place_swamps(), populate(), serialize(), unserialize(), and unserialize_omap().
urbanity
int overmap::urbanity = 0 private
Definition at line 457 of file overmap.h.
Referenced by calculate_urbanity(), get_urbanity(), and place_cities().
vehicles
std::map<int, om_vehicle> overmap::vehicles
Definition at line 323 of file overmap.h.
Referenced by overmapbuffer::add_vehicle(), overmapbuffer::get_vehicle(), overmapbuffer::has_vehicle(), overmapbuffer::move_vehicle(), and overmapbuffer::remove_vehicle().
zg
std::multimap<tripoint_om_sm, mongroup> overmap::zg private
Definition at line 315 of file overmap.h.
Referenced by add_mon_group(), clear_mon_groups(), overmapbuffer::fix_mongroups(), overmapbuffer::fix_nemesis(), mongroup_check(), move_hordes(), move_nemesis(), place_special(), process_mongroups(), remove_nemesis(), save_monster_groups(), signal_hordes(), and signal_nemesis().
The documentation for this class was generated from the following files:
src/overmap.h
src/overmap.cpp
src/savegame.cpp