Cataclysm DDA: mission_ui_impl Class Reference
mission_ui_impl Class Reference
Public Member Functions
mission_ui_impl ()
Public Member Functions inherited from cataimgui::window
window (const std::string &id_, int window_flags=0)
virtual ~window ()
void draw_colored_text (std::string const &text, const nc_color &color, float wrap_width=0.0F, bool *is_selected=nullptr, bool *is_focused=nullptr, bool *is_hovered=nullptr)
void draw_colored_text (std::string const &text, nc_color &color, float wrap_width=0.0F, bool *is_selected=nullptr, bool *is_focused=nullptr, bool *is_hovered=nullptr)
bool action_button (const std::string &action, const std::string &text)
A button tied to a string action.
bool has_button_action ()
std::string get_button_action ()
void draw_header (std::string const &text)
bool get_is_open () const
virtual void draw ()
virtual void on_resized ()
bool is_bounds_changed ()
size_t get_text_width (const std::string &text)
size_t get_text_height (const char *text)
size_t str_width_to_pixels (size_t len)
size_t str_height_to_pixels (size_t len)
std::string get_filter ()
void clear_filter ()
void mark_resized ()
Public Attributes
std::string last_action
Protected Member Functions
void draw_controls () override
Protected Member Functions inherited from cataimgui::window
window (int window_flags=0)
virtual bounds get_bounds ()
void draw_filter (const input_context &ctxt, bool filtering_active)
Private Member Functions
void draw_mission_names (std::vector< mission * > missions, int &selected_mission, bool &need_adjust) const
void draw_selected_description (std::vector< mission * > missions, int &selected_mission)
Private Attributes
mission_ui_tab_enum selected_tab = mission_ui_tab_enum::ACTIVE
mission_ui_tab_enum switch_tab = mission_ui_tab_enum::num_tabs
size_t window_width = str_width_to_pixels(TERMX) / 2
size_t window_height = str_height_to_pixels(TERMY) / 2
size_t table_column_width = window_width / 2
Additional Inherited Members
Protected Attributes inherited from cataimgui::window
bool force_to_back = false
bool is_open
std::string id
int window_flags
std::string button_action
Detailed Description
Definition at line 57 of file mission_ui.cpp.
Constructor & Destructor Documentation
mission_ui_impl()
mission_ui_impl::mission_ui_impl () inline explicit
Definition at line 61 of file mission_ui.cpp.
                                    : cataimgui::window( _( "Your missions" ),
                     ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoNav |
                     ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse ) {
         }
Member Function Documentation
draw_controls()
void mission_ui_impl::draw_controls () override protected virtual
Implements cataimgui::window.
Definition at line 113 of file mission_ui.cpp.
 {
     ImGui::SetWindowSize( ImVec2( window_width, window_height ), ImGuiCond_Once );
     std::vector<mission *> umissions;
     static int selected_mission = 0;
     bool adjust_selected = false;
     if( last_action == "QUIT" ) {
         return;
     } else if( last_action == "UP" ) {
         adjust_selected = true;
         ImGui::SetKeyboardFocusHere( -1 );
         selected_mission--;
     } else if( last_action == "DOWN" ) {
         adjust_selected = true;
         ImGui::SetKeyboardFocusHere( 1 );
         selected_mission++;
     } else if( last_action == "NEXT_TAB" || last_action == "RIGHT" ) {
         adjust_selected = true;
         selected_mission = 0;
         switch_tab = selected_tab;
         ++switch_tab;
     } else if( last_action == "PREV_TAB" || last_action == "LEFT" ) {
         adjust_selected = true;
         selected_mission = 0;
         switch_tab = selected_tab;
         --switch_tab;
     }
     ImGuiTabItemFlags_ flags = ImGuiTabItemFlags_None;
     if( ImGui::BeginTabBar( "##TAB_BAR" ) ) {
         flags = ImGuiTabItemFlags_None;
         if( switch_tab == mission_ui_tab_enum::ACTIVE ) {
             flags = ImGuiTabItemFlags_SetSelected;
             switch_tab = mission_ui_tab_enum::num_tabs;
         }
         if( ImGui::BeginTabItem( _( "ACTIVE" ), nullptr, flags ) ) {
             selected_tab = mission_ui_tab_enum::ACTIVE;
             umissions = get_avatar().get_active_missions();
             ImGui::EndTabItem();
         }
         flags = ImGuiTabItemFlags_None;
         if( switch_tab == mission_ui_tab_enum::COMPLETED ) {
             flags = ImGuiTabItemFlags_SetSelected;
             switch_tab = mission_ui_tab_enum::num_tabs;
         }
         if( ImGui::BeginTabItem( _( "COMPLETED" ), nullptr, flags ) ) {
             selected_tab = mission_ui_tab_enum::COMPLETED;
             umissions = get_avatar().get_completed_missions();
             ImGui::EndTabItem();
         }
         flags = ImGuiTabItemFlags_None;
         if( switch_tab == mission_ui_tab_enum::FAILED ) {
             flags = ImGuiTabItemFlags_SetSelected;
             switch_tab = mission_ui_tab_enum::num_tabs;
         }
         if( ImGui::BeginTabItem( _( "FAILED" ), nullptr, flags ) ) {
             selected_tab = mission_ui_tab_enum::FAILED;
             umissions = get_avatar().get_failed_missions();
             ImGui::EndTabItem();
         }
         ImGui::EndTabBar();
     }
     if( selected_mission < 0 ) {
         selected_mission = 0;
     }
     if( static_cast<size_t>( selected_mission ) > umissions.size() - 1 ) {
         selected_mission = umissions.size() - 1;
     }
     // This action needs to be after umissions is populated
     if( !umissions.empty() && last_action == "CONFIRM" &&
         selected_tab == mission_ui_tab_enum::ACTIVE ) {
         get_avatar().set_active_mission( *umissions[selected_mission] );
     }
     if( umissions.empty() ) {
         static const std::map< mission_ui_tab_enum, std::string > nope = {
             { mission_ui_tab_enum::ACTIVE, translate_marker( "You have no active missions!" ) },
             { mission_ui_tab_enum::COMPLETED, translate_marker( "You haven't completed any missions!" ) },
             { mission_ui_tab_enum::FAILED, translate_marker( "You haven't failed any missions!" ) }
         };
         ImGui::TextWrapped( "%s", nope.at( selected_tab ).c_str() );
         return;
     }
     if( get_avatar().get_active_mission() ) {
         ImGui::TextWrapped( _( "Current objective: %s" ),
                             get_avatar().get_active_mission()->name().c_str() );
     }
     if( ImGui::BeginTable( "##MISSION_TABLE", 2, ImGuiTableFlags_None,
                            ImVec2( window_width, window_height ) ) ) {
         // Missions selection is purposefully thinner than the description, it has less to convey.
         ImGui::TableSetupColumn( _( "Missions" ), ImGuiTableColumnFlags_WidthStretch,
                                  table_column_width * 0.8 );
         ImGui::TableSetupColumn( _( "Description" ), ImGuiTableColumnFlags_WidthStretch,
                                  table_column_width * 1.2 );
         ImGui::TableHeadersRow();
         ImGui::TableNextColumn();
         draw_mission_names( umissions, selected_mission, adjust_selected );
         ImGui::TableNextColumn();
         draw_selected_description( umissions, selected_mission );
         ImGui::EndTable();
     }
 }
References _, ACTIVE, COMPLETED, draw_mission_names(), draw_selected_description(), FAILED, avatar::get_active_missions(), get_avatar(), avatar::get_completed_missions(), avatar::get_failed_missions(), last_action, om_direction::name(), num_tabs, selected_tab, avatar::set_active_mission(), switch_tab, table_column_width, translate_marker, window_height, and window_width.
draw_mission_names()
void mission_ui_impl::draw_mission_names (std::vector< mission * > missions, int & selected_mission, bool & need_adjust) const private
Definition at line 224 of file mission_ui.cpp.
 {
     const int num_missions = missions.size();
     // roughly 6 lines of header info. title+tab+objective+table headers+2 lines worth of padding between those four
     const float header_height = ImGui::GetTextLineHeight() * 6;
     if( ImGui::BeginListBox( "##LISTBOX", ImVec2( table_column_width * 0.75,
                              window_height - header_height ) ) ) {
         for( int i = 0; i < num_missions; i++ ) {
             const bool is_selected = selected_mission == i;
             ImGui::PushID( i );
             if( ImGui::Selectable( missions[i]->name().c_str(), is_selected,
                                    ImGuiSelectableFlags_AllowDoubleClick ) ) {
                 selected_mission = i;
                 if( ImGui::IsMouseDoubleClicked( ImGuiMouseButton_Left ) ) {
                     get_avatar().set_active_mission( *missions[selected_mission] );
                 }
             }
             if( is_selected && need_adjust ) {
                 ImGui::SetScrollHereY();
                 ImGui::SetItemDefaultFocus();
             }
             ImGui::PopID();
         }
         ImGui::EndListBox();
     }
 }
References get_avatar(), om_direction::name(), avatar::set_active_mission(), table_column_width, and window_height.
Referenced by draw_controls().
draw_selected_description()
void mission_ui_impl::draw_selected_description (std::vector< mission * > missions, int & selected_mission) private
Definition at line 254 of file mission_ui.cpp.
 {
     mission *miss = missions[selected_mission];
     ImGui::TextWrapped( _( "Mission: %s" ), miss->name().c_str() );
     if( miss->get_npc_id().is_valid() ) {
         npc *guy = g->find_npc( miss->get_npc_id() );
         if( guy ) {
             ImGui::TextWrapped( _( "Given by: %s" ), guy->disp_name().c_str() );
         }
     }
     ImGui::Separator();
     static std::string raw_description;
     static std::string parsed_description;
     // Avoid replacing expanded snippets with other valid snippet text on redraw
     if( raw_description != miss->get_description() ) {
         raw_description = miss->get_description();
         parsed_description = raw_description;
         // Handles(example)  <reward_count:item>   in description
         // Not handled in parse_tags for some reason!
         dialogue d( get_talker_for( get_avatar() ), nullptr, {} );
         const talk_effect_fun_t::likely_rewards_t &rewards = miss->get_likely_rewards();
         for( const auto &reward : rewards ) {
             std::string token = "<reward_count:" + itype_id( reward.second.evaluate( d ) ).str() + ">";
             parsed_description = string_replace( parsed_description, token, string_format( "%g",
                                                  reward.first.evaluate( d ) ) );
         }
         parse_tags( parsed_description, get_player_character(), get_player_character() );
     }
     draw_colored_text( parsed_description, c_unset, table_column_width * 1.15 );
     if( miss->has_deadline() ) {
         const time_point deadline = miss->get_deadline();
         ImGui::Text( _( "Deadline: %s" ), to_string( deadline ).c_str() );
         if( selected_tab == mission_ui_tab_enum::ACTIVE ) {
             // There's no point in displaying this for a completed/failed mission.
             // @ TODO: But displaying when you completed it would be useful.
             const time_duration remaining = deadline - calendar::turn;
             std::string remaining_time;
             if( remaining <= 0_turns ) {
                 remaining_time = _( "None!" );
             } else if( get_player_character().has_watch() ) {
                 remaining_time = to_string( remaining );
             } else {
                 remaining_time = to_string_approx( remaining );
             }
             ImGui::TextWrapped( _( "Time remaining: %s" ), remaining_time.c_str() );
         }
     }
     if( miss->has_target() ) {
         // TODO: target does not contain a z-component, targets are assumed to be on z=0
         const tripoint_abs_omt pos = get_player_character().global_omt_location();
         draw_colored_text( string_format( _( "Target: %s" ), miss->get_target().to_string() ), c_white );
         // Below is done instead of a table for the benefit of right-to-left languages
         //~Extra padding spaces in the English text are so that the replaced string vertically aligns with the one above
         draw_colored_text( string_format( _( "You:    %s" ), pos.to_string() ), c_white );
     }
 }
References _, ACTIVE, c_unset, c_white, Character::disp_name(), cataimgui::window::draw_colored_text(), g, get_avatar(), mission::get_deadline(), mission::get_description(), mission::get_likely_rewards(), mission::get_npc_id(), get_player_character(), get_talker_for(), mission::get_target(), Creature::global_omt_location(), mission::has_deadline(), mission::has_target(), character_id::is_valid(), itype_id, mission::name(), parse_tags(), math_opers::pos(), selected_tab, string_format(), string_replace(), table_column_width, coords::coord_point_base< Point >::to_string(), to_string(), to_string_approx(), and calendar::turn.
Referenced by draw_controls().
Member Data Documentation
last_action
std::string mission_ui_impl::last_action
Definition at line 60 of file mission_ui.cpp.
Referenced by draw_controls(), and mission_ui::draw_mission_ui().
selected_tab
mission_ui_tab_enum mission_ui_impl::selected_tab = mission_ui_tab_enum::ACTIVE private
Definition at line 71 of file mission_ui.cpp.
Referenced by draw_controls(), and draw_selected_description().
switch_tab
mission_ui_tab_enum mission_ui_impl::switch_tab = mission_ui_tab_enum::num_tabs private
Definition at line 72 of file mission_ui.cpp.
Referenced by draw_controls().
table_column_width
size_t mission_ui_impl::table_column_width = window_width / 2 private
Definition at line 76 of file mission_ui.cpp.
Referenced by draw_controls(), draw_mission_names(), and draw_selected_description().
window_height
size_t mission_ui_impl::window_height = str_height_to_pixels(TERMY) / 2 private
Definition at line 75 of file mission_ui.cpp.
Referenced by draw_controls(), and draw_mission_names().
window_width
size_t mission_ui_impl::window_width = str_width_to_pixels(TERMX) / 2 private
Definition at line 74 of file mission_ui.cpp.
Referenced by draw_controls().
The documentation for this class was generated from the following file:
src/mission_ui.cpp