Cataclysm DDA: behavior::character_oracle_t Class Reference
behavior::character_oracle_t Class Reference
#include <character_oracle.h>
Public Member Functions
character_oracle_t (const Character *subject)
status_t needs_warmth_badly (std::string_view) const
Predicates used by AI to determine goals.
status_t needs_water_badly (std::string_view) const
status_t needs_food_badly (std::string_view) const
status_t can_wear_warmer_clothes (std::string_view) const
status_t can_make_fire (std::string_view) const
status_t can_take_shelter (std::string_view) const
status_t has_water (std::string_view) const
status_t has_food (std::string_view) const
Private Attributes
const Character * subject
Detailed Description
Definition at line 15 of file character_oracle.h.
Constructor & Destructor Documentation
character_oracle_t()
behavior::character_oracle_t::character_oracle_t (const Character * subject) inline explicit
Definition at line 18 of file character_oracle.h.
{
             this->subject = subject;
         }
Member Function Documentation
can_make_fire()
status_t behavior::character_oracle_t::can_make_fire (std::string_view) const
Definition at line 64 of file character_oracle.cpp.
 {
     // Check inventory for firemaking tools and fuel
     bool tool = false;
     bool fuel = false;
     bool found_fire_stuff = subject->has_item_with( [&tool, &fuel]( const item & candidate ) {
         if( candidate.has_flag( STATIC( flag_id( "FIRESTARTER" ) ) ) ) {
             tool = true;
             if( fuel ) {
                 return true;
             }
         } else if( candidate.flammable() ) {
             fuel = true;
             if( tool ) {
                 return true;
             }
         }
         return false;
     } );
     return found_fire_stuff ? status_t::running : status_t::success;
 }
References item::flammable(), item::has_flag(), visitable::has_item_with(), STATIC, and subject.
can_take_shelter()
status_t behavior::character_oracle_t::can_take_shelter (std::string_view) const
Definition at line 86 of file character_oracle.cpp.
 {
     // There be no shelter here.
     // The frontline is everywhere.
     return status_t::failure;
 }
can_wear_warmer_clothes()
status_t behavior::character_oracle_t::can_wear_warmer_clothes (std::string_view) const
Definition at line 53 of file character_oracle.cpp.
 {
     // Check inventory for wearable warmer clothes, greedily.
     // Don't consider swapping clothes yet, just evaluate adding clothes.
     bool found_clothes = subject->has_item_with( [this]( const item & candidate ) {
         return candidate.get_warmth() > 0 && subject->can_wear( candidate ).success() &&
                !subject->is_worn( candidate );
     } );
     return found_clothes ? status_t::running : status_t::failure;
 }
References Character::can_wear(), behavior::failure, item::get_warmth(), visitable::has_item_with(), Character::is_worn(), behavior::running, subject, and ret_val_common::success().
has_food()
status_t behavior::character_oracle_t::has_food (std::string_view) const
Definition at line 102 of file character_oracle.cpp.
 {
     // Check if we know about food somewhere
     bool found_food = subject->has_item_with( []( const item & cand ) {
         return cand.is_food() && cand.get_comestible()->has_calories();
     } );
     return found_food ? status_t::running : status_t::failure;
 }
References item::get_comestible(), and item::is_food().
has_water()
status_t behavior::character_oracle_t::has_water (std::string_view) const
Definition at line 93 of file character_oracle.cpp.
 {
     // Check if we know about water somewhere
     bool found_water = subject->has_item_with( []( const item & cand ) {
         return cand.is_food() && cand.get_comestible()->quench > 0;
     } );
     return found_water ? status_t::running : status_t::failure;
 }
References item::get_comestible(), and item::is_food().
needs_food_badly()
status_t behavior::character_oracle_t::needs_food_badly (std::string_view) const
Definition at line 44 of file character_oracle.cpp.
 {
     // Check hunger threshold.
     if( subject->get_hunger() >= 300 && subject->get_starvation() > base_metabolic_rate ) {
         return status_t::running;
     }
     return status_t::success;
 }
References base_metabolic_rate, Character::get_hunger(), Character::get_starvation(), behavior::running, subject, and behavior::success.
needs_warmth_badly()
status_t behavior::character_oracle_t::needs_warmth_badly (std::string_view) const
Predicates used by AI to determine goals.
Definition at line 24 of file character_oracle.cpp.
 {
     // Use player::temp_conv to predict whether the Character is "in trouble".
     for( const bodypart_id &bp : subject->get_all_body_parts() ) {
         if( subject->get_part_temp_conv( bp ) <= BODYTEMP_VERY_COLD ) {
             return status_t::running;
         }
     }
     return status_t::success;
 }
References BODYTEMP_VERY_COLD, bp, Creature::get_all_body_parts(), Creature::get_part_temp_conv(), behavior::running, subject, and behavior::success.
needs_water_badly()
status_t behavior::character_oracle_t::needs_water_badly (std::string_view) const
Definition at line 35 of file character_oracle.cpp.
 {
     // Check thirst threshold.
     if( subject->get_thirst() > 520 ) {
         return status_t::running;
     }
     return status_t::success;
 }
References Character::get_thirst(), behavior::running, subject, and behavior::success.
Member Data Documentation
subject
const Character* behavior::character_oracle_t::subject private
Definition at line 33 of file character_oracle.h.
Referenced by can_make_fire(), can_wear_warmer_clothes(), needs_food_badly(), needs_warmth_badly(), and needs_water_badly().
The documentation for this class was generated from the following files:
src/character_oracle.h
src/character_oracle.cpp