Cataclysm DDA: veh_app_interact Class Reference
veh_app_interact Class Reference
Appliance interaction UI.
#include <veh_appliance.h>
Static Public Member Functions
static player_activity run (vehicle &veh, const point &p=point_zero)
Starts and manages the appliance interaction UI.
Private Member Functions
veh_app_interact (vehicle &veh, const point &p)
~veh_app_interact ()=default
void init_ui_windows ()
Sets up the window parameters to fit the amount of text to be displayed.
void draw_info ()
Draws the upper portion, representing the appliance's usage info.
void populate_app_actions ()
Populates the list of available actions for this appliance.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
Initializes the ui_adaptor and callbacks responsible for drawing w_border and w_info.
bool can_refill ()
Checks whether the current appliance can be refilled (excludes batteries).
bool can_siphon ()
Checks whether the player can siphon liquids from the appliance.
void refill ()
Function associated with the "REFILL" action.
void siphon ()
Function associated with the "SIPHON" action.
void rename ()
Function associated with the "RENAME" action.
void remove ()
Function associated with the "REMOVE" action.
bool can_disconnect ()
Checks whether the part has any items linked to it so it can tell the player to disconnect those first.
void disconnect ()
Function associated with the "DISCONNECT_GRID" action.
void plug ()
Function associated with the "PLUG" action.
void app_loop ()
The main loop of the appliance UI.
Private Attributes
point a_point = point_zero
vehicle * veh
input_context ctxt
weak_ptr_fast< ui_adaptor > ui
player_activity act
std::vector< std::function< void()> > app_actions
catacurses::window w_border
catacurses::window w_info
uilist imenu
Detailed Description
Appliance interaction UI.
Works similarly to veh_interact, but has a much simpler design. The intended usage is:
player_activity act = veh_app_interact::run(veh); if(act) { player_character.moves = 0; player_character.assign_activity(act); }
The UI contains 2 parts: an upper portion showing usage info about the appliance, and a lower portion listing actions that can be performed on the appliance.
Definition at line 29 of file veh_appliance.h.
Constructor & Destructor Documentation
veh_app_interact()
veh_app_interact::veh_app_interact (vehicle & veh, const point & p) explicit private
Definition at line 139 of file veh_appliance.cpp.
     : a_point( p ), veh( &veh ), ctxt( "APP_INTERACT", keyboard_mode::keycode )
 {
     ctxt.register_directions();
     ctxt.register_action( "REFILL" );
     ctxt.register_action( "SIPHON" );
     ctxt.register_action( "RENAME" );
     ctxt.register_action( "REMOVE" );
     ctxt.register_action( "MERGE" );
     ctxt.register_action( "DISCONNECT_GRID" );
 }
References ctxt, input_context::register_action(), and input_context::register_directions().
~veh_app_interact()
veh_app_interact::~veh_app_interact () private default
Member Function Documentation
app_loop()
void veh_app_interact::app_loop () private
The main loop of the appliance UI.
Redraws windows, checks for input, and performs selected actions. The loop exits once an activity is assigned (either directly to the player or to 'act'), or when QUIT input is received.
Definition at line 627 of file veh_appliance.cpp.
 {
     bool done = false;
     while( !done ) {
         // scope this tighter so that this ui is hidden when app_actions[ret]() triggers
         {
             ui.reset();
             shared_ptr_fast<ui_adaptor> current_ui = create_or_get_ui_adaptor();
             ui_manager::redraw();
             shared_ptr_fast<ui_adaptor> input_ui = imenu.create_or_get_ui_adaptor();
             imenu.query();
         }
         int ret = imenu.ret;
         if( ret < 0 || static_cast<size_t>( ret ) >= imenu.entries.size() ) {
             done = true;
         } else if( imenu.entries[ret].enabled ) {
             app_actions[ret]();
         }
         // Player activity queued up, close interaction menu
         if( veh == nullptr || !act.is_null() || !get_player_character().activity.is_null() ) {
             done = true;
         }
     }
 }
References act, Character::activity, app_actions, uilist::create_or_get_ui_adaptor(), create_or_get_ui_adaptor(), uilist::entries, get_player_character(), imenu, player_activity::is_null(), uilist::query(), ui_manager::redraw(), cata::hash64_detail::ret, uilist::ret, and veh.
Referenced by run().
can_disconnect()
bool veh_app_interact::can_disconnect () private
Checks whether the part has any items linked to it so it can tell the player to disconnect those first.
This prevents players from doing this by accident.
Returns
True if there aren't any tow cable parts or items linked to the mount point.
Definition at line 506 of file veh_appliance.cpp.
 {
     for( int &i : veh->parts_at_relative( a_point, true ) ) {
         if( veh->part( i ).has_flag( vp_flag::linked_flag ) ||
             veh->part( i ).info().has_flag( "TOW_CABLE" ) ) {
             return false;
         }
     }
     return true;
 }
References a_point, vpart_info::has_flag(), vehicle_part::has_flag(), vehicle_part::info(), linked_flag, vehicle::part(), vehicle::parts_at_relative(), and veh.
Referenced by populate_app_actions().
can_refill()
bool veh_app_interact::can_refill () private
Checks whether the current appliance can be refilled (excludes batteries).
Returns
True if the appliance contains a part that can be refilled.
Definition at line 304 of file veh_appliance.cpp.
 {
     for( const vpart_reference &vpr : veh->get_all_parts() ) {
         if( vpr.part().can_reload() ) {
             return true;
         }
     }
     return false;
 }
References vehicle::get_all_parts(), and veh.
Referenced by populate_app_actions().
can_siphon()
bool veh_app_interact::can_siphon () private
Checks whether the player can siphon liquids from the appliance.
Requires an item with HOSE quality and a part containing liquid.
Returns
True if a liquid can be siphoned from the appliance.
Definition at line 314 of file veh_appliance.cpp.
 {
     for( const vpart_reference &vpr : veh->get_any_parts( VPFLAG_FLUIDTANK ) ) {
         if( vpr.part().get_base().has_item_with( []( const item & it ) {
         return it.made_of( phase_id::LIQUID );
         } ) ) {
             return get_player_character().has_quality( qual_HOSE );
         }
     }
     return false;
 }
References vehicle::get_any_parts(), get_player_character(), Character::has_quality(), qual_HOSE, veh, and VPFLAG_FLUIDTANK.
Referenced by populate_app_actions().
create_or_get_ui_adaptor()
shared_ptr_fast< ui_adaptor > veh_app_interact::create_or_get_ui_adaptor () private
Initializes the ui_adaptor and callbacks responsible for drawing w_border and w_info.
Definition at line 608 of file veh_appliance.cpp.
 {
     shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
     if( !current_ui ) {
         ui = current_ui = make_shared_fast<ui_adaptor>();
         current_ui->on_screen_resize( [this]( ui_adaptor & cui ) {
             init_ui_windows();
             cui.position_from_window( catacurses::stdscr );
         } );
         current_ui->mark_resize();
         current_ui->on_redraw( [this]( const ui_adaptor & ) {
             draw_border( w_border, c_white, veh->name, c_white );
             wnoutrefresh( w_border );
             draw_info();
         } );
     }
     return current_ui;
 }
References c_white, draw_border(), draw_info(), init_ui_windows(), vehicle::name, ui_adaptor::position_from_window(), catacurses::stdscr, veh, w_border, and catacurses::wnoutrefresh().
Referenced by app_loop().
disconnect()
void veh_app_interact::disconnect () private
Function associated with the "DISCONNECT_GRID" action.
Removes appliance from a power grid, allowing it to be moved individually.
Definition at line 517 of file veh_appliance.cpp.
 {
     veh->separate_from_grid( a_point );
     get_player_character().pause();
 }
References a_point, get_player_character(), Character::pause(), vehicle::separate_from_grid(), and veh.
Referenced by populate_app_actions().
draw_info()
void veh_app_interact::draw_info () private
Draws the upper portion, representing the appliance's usage info.
Definition at line 209 of file veh_appliance.cpp.
 {
     werase( w_info );
     int row = 0;
     // Fuel indicators
     veh->print_fuel_indicators( w_info, point( 0, row ), 0, true, true, true, true );
     row += veh->get_printable_fuel_types().size();
     // Onboard battery power
     if( !veh->batteries.empty() ) {
         std::pair<int, int> battery = veh->battery_power_level();
         nc_color batt_col = c_yellow;
         if( battery.second > 0 ) {
             batt_col = battery.first == 0 ? c_light_red :
                        battery.first == battery.second ? c_light_green : c_yellow;
         }
         mvwprintz( w_info, point( 0, row ), c_white, _( "Onboard battery power: " ) );
         wprintz( w_info, batt_col, string_format( "%d/%d", battery.first, battery.second ) );
         row++;
     }
     auto print_charge = [this]( const std::string & lbl, units::power rate, int row ) {
         std::string rstr;
         if( rate > 10_kW || rate < -10_kW ) {
             //~ Power in killoWatts. %+4.1f is a 4 digit number with 1 decimal point (ex: 2198.3 kW)
             rstr = string_format( _( "%+4.1f kW" ), units::to_watt( rate ) / 1000.f );
         } else {
             //~ Power in Watts. %+4.1f is a 4 digit number with 1 decimal point (ex: 4737.3 W)
             rstr = string_format( _( "%+4.1f W" ), units::to_milliwatt( rate ) / 1000.f );
         }
         nc_color rcol = rate < 0_W ? c_light_red :
                         rate > 0_W ? c_light_green : c_yellow;
         mvwprintz( w_info, point( 0, row ), c_white, lbl );
         wprintz( w_info, rcol, rstr );
     };
     if( !has_battery_in_grid( veh ) ) {
         mvwprintz( w_info, point( 0, row ), c_light_red, _( "Appliance has no connection to a battery." ) );
         row++;
     }
     // Battery power output
     units::power grid_flow = 0_W;
     for( const std::pair<vehicle *const, float> &pair : veh->search_connected_vehicles() ) {
         grid_flow += pair.first->net_battery_charge_rate( /* include_reactors = */ true );
     }
     print_charge( _( "Grid battery power flow: " ), grid_flow, row );
     row++;
     // Reactor power output
     if( !veh->reactors.empty() ) {
         const units::power rate = veh->active_reactor_epower();
         print_charge( _( "Reactor power output: " ), rate, row );
         row++;
     }
     // Wind power output
     if( !veh->wind_turbines.empty() ) {
         units::power rate = veh->total_wind_epower();
         print_charge( _( "Wind power output: " ), rate, row );
         row++;
     }
     // Solar power output
     if( !veh->solar_panels.empty() ) {
         units::power rate = veh->total_solar_epower();
         print_charge( _( "Solar power output: " ), rate, row );
         row++;
     }
     // Water power output
     if( !veh->water_wheels.empty() ) {
         units::power rate = veh->total_water_wheel_epower();
         print_charge( _( "Water power output: " ), rate, row );
         row++;
     }
     // Alternator power output
     if( !veh->alternators.empty() ) {
         units::power rate = veh->total_alternator_epower();
         print_charge( _( "Alternator power output: " ), rate, row );
         row++;
     }
     // Other power output
     if( !veh->accessories.empty() ) {
         units::power rate = veh->total_accessory_epower();
         print_charge( _( "Appliance power consumption: " ), rate, row );
         row++;
     }
     wnoutrefresh( w_info );
 }
References _, vehicle::accessories, vehicle::active_reactor_epower(), vehicle::alternators, vehicle::batteries, vehicle::battery_power_level(), c_light_green, c_light_red, c_white, c_yellow, vehicle::get_printable_fuel_types(), has_battery_in_grid(), mvwprintz(), point, vehicle::print_fuel_indicators(), vehicle::reactors, vehicle::search_connected_vehicles(), vehicle::solar_panels, string_format(), units::to_milliwatt(), units::to_watt(), vehicle::total_accessory_epower(), vehicle::total_alternator_epower(), vehicle::total_solar_epower(), vehicle::total_water_wheel_epower(), vehicle::total_wind_epower(), veh, w_info, vehicle::water_wheels, catacurses::werase(), vehicle::wind_turbines, catacurses::wnoutrefresh(), and wprintz().
Referenced by create_or_get_ui_adaptor().
init_ui_windows()
void veh_app_interact::init_ui_windows () private
Sets up the window parameters to fit the amount of text to be displayed.
The setup calls populate_app_actions() to initialize the content.
Definition at line 157 of file veh_appliance.cpp.
 {
     imenu.reset();
     populate_app_actions();
     int height_info = veh->get_printable_fuel_types().size() + 2;
     if( !has_battery_in_grid( veh ) ) {
         height_info++;
     }
     if( !veh->batteries.empty() ) {
         height_info++;
     }
     if( !veh->reactors.empty() ) {
         height_info++;
     }
     if( !veh->wind_turbines.empty() ) {
         height_info++;
     }
     if( !veh->solar_panels.empty() ) {
         height_info++;
     }
     if( !veh->water_wheels.empty() ) {
         height_info++;
     }
     if( !veh->alternators.empty() ) {
         height_info++;
     }
     if( !veh->accessories.empty() ) {
         height_info++;
     }
     const int width_info = win_width - 2;
     const int height_input = app_actions.size();
     const int width_input = win_width;
     const int height = height_info + height_input + 2;
     // Center the UI
     point topleft( TERMX / 2 - win_width / 2, TERMY / 2 - height / 2 );
     w_border = catacurses::newwin( height, win_width, topleft );
     //NOLINTNEXTLINE(cata-use-named-point-constants)
     w_info = catacurses::newwin( height_info, width_info, topleft + point( 1, 1 ) );
     // Setup modifications to the uilist to integrate it into the UI
     imenu.w_width_setup = width_input;
     imenu.w_x_setup = topleft.x;
     imenu.w_y_setup = topleft.y + height_info;
     imenu.allow_cancel = true;
     imenu.border_color = c_white;
     imenu.callback = &app_callback;
     imenu.setup();
 }
References vehicle::accessories, uilist::allow_cancel, vehicle::alternators, app_actions, app_callback, vehicle::batteries, uilist::border_color, c_white, uilist::callback, vehicle::get_printable_fuel_types(), has_battery_in_grid(), imenu, catacurses::newwin(), point, populate_app_actions(), vehicle::reactors, uilist::reset(), uilist::setup(), vehicle::solar_panels, TERMX, TERMY, veh, w_border, w_info, uilist::w_width_setup, uilist::w_x_setup, uilist::w_y_setup, vehicle::water_wheels, win_width, vehicle::wind_turbines, point::x, and point::y.
Referenced by create_or_get_ui_adaptor().
plug()
void veh_app_interact::plug () private
Function associated with the "PLUG" action.
Connects the power cable to selected tile.
Definition at line 523 of file veh_appliance.cpp.
 {
     const int part = veh->part_at( veh->coord_translate( a_point ) );
     const tripoint pos = veh->global_part_pos3( part );
     item cord( "power_cord" );
     cord.link_to( *veh, a_point, link_state::automatic );
     if( cord.get_use( "link_up" ) ) {
         cord.type->get_use( "link_up" )->call( &get_player_character(), cord, pos );
     }
 }
References a_point, automatic, use_function::call(), vehicle::coord_translate(), get_player_character(), itype::get_use(), item::get_use(), vehicle::global_part_pos3(), item::link_to(), vehicle::part_at(), math_opers::pos(), item::type, and veh.
Referenced by populate_app_actions().
populate_app_actions()
void veh_app_interact::populate_app_actions () private
Populates the list of available actions for this appliance.
The action display names are stored as uilist entries in imenu, and the associated functions are stored in app_actions.
Definition at line 534 of file veh_appliance.cpp.
 {
     map &here = get_map();
     vehicle_part *vp;
     const tripoint a_point_bub( veh->mount_to_tripoint( a_point ) );
     if( auto sel_part = here.veh_at( a_point_bub ).part_with_feature( VPFLAG_APPLIANCE, false ) ) {
         vp = &sel_part->part();
     } else {
         const int part = veh->part_at( veh->coord_translate( a_point ) );
         vp = &veh->part( part >= 0 ? part : 0 );
     }
     const std::string ctxt_letters = ctxt.get_available_single_char_hotkeys();
     imenu.entries.clear();
     app_actions.clear();
     /******************** General actions ********************/
     // Refill
     app_actions.emplace_back( [this]() {
         refill();
     } );
     imenu.addentry( -1, can_refill(), ctxt.keys_bound_to( "REFILL" ).front(),
                     ctxt.get_action_name( "REFILL" ) );
     // Siphon
     app_actions.emplace_back( [this]() {
         siphon();
     } );
     imenu.addentry( -1, can_siphon(), ctxt.keys_bound_to( "SIPHON" ).front(),
                     ctxt.get_action_name( "SIPHON" ) );
     // Rename
     app_actions.emplace_back( [this]() {
         rename();
     } );
     imenu.addentry( -1, true, ctxt.keys_bound_to( "RENAME" ).front(),
                     ctxt.get_action_name( "RENAME" ) );
     // Remove
     app_actions.emplace_back( [this]() {
         remove();
     } );
     imenu.addentry( -1, veh->can_unmount( *vp, true ).success(), ctxt.keys_bound_to( "REMOVE" ).front(),
                     ctxt.get_action_name( "REMOVE" ) );
     // Plug
     app_actions.emplace_back( [this]() {
         plug();
     } );
     imenu.addentry( -1, true, ctxt.keys_bound_to( "PLUG" ).front(),
                     string_format( "%s%s", ctxt.get_action_name( "PLUG" ),
                                    //~ An addendum to Plug In's description, as in: Plug in appliance / merge power grid".
                                    veh->is_powergrid() ? _( " / merge power grid" ) : "" ) );
     if( veh->is_powergrid() && veh->part_count() > 1 && !vp->info().has_flag( VPFLAG_WALL_MOUNTED ) ) {
         // Disconnect from power grid
         app_actions.emplace_back( [this]() {
             disconnect();
             veh = nullptr;
         } );
         const bool can_disc = can_disconnect();
         imenu.addentry_desc( -1, can_disc, ctxt.keys_bound_to( "DISCONNECT_GRID" ).front(),
                              ctxt.get_action_name( "DISCONNECT_GRID" ), can_disc ? "" : _( "Remove other cables first" ) );
     }
     /*************** Get part-specific actions ***************/
     veh_menu menu( veh, "IF YOU SEE THIS IT IS A BUG" );
     veh->build_interact_menu( menu, veh->mount_to_tripoint( a_point ), false );
     const std::vector<veh_menu_item> items = menu.get_items();
     for( size_t i = 0; i < items.size(); i++ ) {
         const veh_menu_item &it = items[i];
         const char hotkey = i < ctxt_letters.size() ? ctxt_letters[i] : 0;
         imenu.addentry( -1, it._enabled, hotkey, it._text );
         app_actions.emplace_back( it._on_submit );
     }
     imenu.setup();
 }
References _, veh_menu_item::_enabled, veh_menu_item::_on_submit, veh_menu_item::_text, a_point, uilist::addentry(), uilist::addentry_desc(), app_actions, vehicle::build_interact_menu(), can_disconnect(), can_refill(), can_siphon(), vehicle::can_unmount(), vehicle::coord_translate(), ctxt, disconnect(), uilist::entries, input_context::get_action_name(), input_context::get_available_single_char_hotkeys(), veh_menu::get_items(), get_map(), vpart_info::has_flag(), imenu, vehicle_part::info(), vehicle::is_powergrid(), input_context::keys_bound_to(), vehicle::mount_to_tripoint(), vehicle::part(), vehicle::part_at(), vehicle::part_count(), optional_vpart_position::part_with_feature(), plug(), refill(), remove(), rename(), uilist::setup(), siphon(), string_format(), ret_val_common::success(), veh, map::veh_at(), VPFLAG_APPLIANCE, and VPFLAG_WALL_MOUNTED.
Referenced by init_ui_windows().
refill()
void veh_app_interact::refill () private
Function associated with the "REFILL" action.
Checks all appliance parts for a watertight container to refill. If multiple parts are eligible, the player is prompted to select one. A refill activity is created and assigned to 'act' to be assigned to the player once run returns.
Definition at line 364 of file veh_appliance.cpp.
 {
     std::vector<vehicle_part *> ptlist;
     for( const vpart_reference &vpr : veh->get_all_parts() ) {
         if( vpr.part().can_reload() ) {
             ptlist.emplace_back( &vpr.part() );
         }
     }
     vehicle_part *pt = pick_part( ptlist, _( "Which part to refill?" ) );
     if( pt == nullptr ) {
         return;
     }
     auto validate = [&pt]( const item & obj ) {
         if( pt->is_tank() ) {
             if( obj.is_watertight_container() && obj.num_item_stacks() == 1 ) {
                 // we are assuming only one pocket here, and it's a liquid so only one item
                 return pt->can_reload( obj.only_item() );
             }
         } else if( pt->is_fuel_store() ) {
             bool can_reload = pt->can_reload( obj );
             //check base item for fuel_stores that can take multiple types of ammunition (like the fuel_bunker)
             if( pt->get_base().can_reload_with( obj, true ) ) {
                 return true;
             }
             return can_reload;
         }
         return false;
     };
     // Setup the refill activity
     item_location target = g->inv_map_splice( validate, string_format( _( "Refill %s" ), pt->name() ),
                            1 );
     if( target ) {
         act = player_activity( ACT_VEHICLE, 1000, static_cast<int>( 'f' ) );
         act.targets.push_back( target );
         act.str_values.push_back( pt->info().id.str() );
         const point q = veh->coord_translate( pt->mount );
         map &here = get_map();
         for( const tripoint &p : veh->get_points( true ) ) {
             act.coord_set.insert( here.getabs( p ) );
         }
         act.values.push_back( here.getabs( veh->global_pos3() ).x + q.x );
         act.values.push_back( here.getabs( veh->global_pos3() ).y + q.y );
         act.values.push_back( a_point.x );
         act.values.push_back( a_point.y );
         act.values.push_back( -a_point.x );
         act.values.push_back( -a_point.y );
         act.values.push_back( veh->index_of_part( pt ) );
     }
 }
References _, a_point, act, ACT_VEHICLE, vehicle_part::can_reload(), item::can_reload_with(), player_activity::coord_set, vehicle::coord_translate(), g, vehicle::get_all_parts(), vehicle_part::get_base(), get_map(), vehicle::get_points(), map::getabs(), vehicle::global_pos3(), vpart_info::id, vehicle::index_of_part(), vehicle_part::info(), vehicle_part::is_fuel_store(), vehicle_part::is_tank(), vehicle_part::mount, vehicle_part::name(), pick_part(), string_id< T >::str(), player_activity::str_values, string_format(), player_activity::targets, player_activity::values, veh, point::x, tripoint::x, point::y, and tripoint::y.
Referenced by populate_app_actions().
remove()
void veh_app_interact::remove () private
Function associated with the "REMOVE" action.
Turns the installed appliance into its base item.
Definition at line 457 of file veh_appliance.cpp.
 {
     map &here = get_map();
     const tripoint a_point_bub( veh->mount_to_tripoint( a_point ) );
     vehicle_part *vp;
     if( auto sel_part = here.veh_at( a_point_bub ).part_with_feature( VPFLAG_APPLIANCE, false ) ) {
         vp = &sel_part->part();
     } else {
         int const part = veh->part_at( veh->coord_translate( a_point ) );
         vp = &veh->part( part >= 0 ? part : 0 );
     }
     const vpart_info &vpinfo = vp->info();
     const requirement_data reqs = vpinfo.removal_requirements();
     Character &you = get_player_character();
     const inventory &inv = you.crafting_inventory();
     std::string msg;
     bool can_remove = reqs.can_make_with_inventory( inv, is_crafting_component );
     if( !can_remove ) {
         msg += _( "Insufficient components/tools!\n" );
         msg += reqs.list_missing();
     }
     time_duration time = vpinfo.removal_time( you );
     if( you.has_trait( trait_DEBUG_HS ) ) {
         can_remove = true;
         time = 1_seconds;
     }
     if( !can_remove ) {
         popup( msg );
         //~ Prompt the player if they want to remove the appliance. %s = appliance name.
     } else if( query_yn( _( "Are you sure you want to take down the %s?" ), veh->name ) ) {
         act = player_activity( ACT_VEHICLE, to_moves<int>( time ), static_cast<int>( 'O' ) );
         act.str_values.push_back( vpinfo.id.str() );
         for( const tripoint &p : veh->get_points( true ) ) {
             act.coord_set.insert( here.getabs( p ) );
         }
         const tripoint a_point_abs( here.getabs( a_point_bub ) );
         act.values.push_back( a_point_abs.x );
         act.values.push_back( a_point_abs.y );
         act.values.push_back( a_point.x );
         act.values.push_back( a_point.y );
         act.values.push_back( -a_point.x );
         act.values.push_back( -a_point.y );
         act.values.push_back( veh->index_of_part( vp ) );
     }
 }
References _, a_point, act, ACT_VEHICLE, requirement_data::can_make_with_inventory(), player_activity::coord_set, vehicle::coord_translate(), Character::crafting_inventory(), get_map(), get_player_character(), vehicle::get_points(), map::getabs(), Character::has_trait(), vpart_info::id, vehicle::index_of_part(), vehicle_part::info(), is_crafting_component(), requirement_data::list_missing(), vehicle::mount_to_tripoint(), vehicle::name, vehicle::part(), vehicle::part_at(), optional_vpart_position::part_with_feature(), popup(), query_yn(), vpart_info::removal_requirements(), vpart_info::removal_time(), string_id< T >::str(), player_activity::str_values, trait_DEBUG_HS, player_activity::values, veh, map::veh_at(), VPFLAG_APPLIANCE, point::x, tripoint::x, point::y, and tripoint::y.
Referenced by populate_app_actions().
rename()
void veh_app_interact::rename () private
Function associated with the "RENAME" action.
Prompts the player to choose a new name for this appliance. The name is reflected in the UI's title.
Definition at line 441 of file veh_appliance.cpp.
 {
     std::string name = string_input_popup()
                        .title( _( "Enter new appliance name:" ) )
                        .width( 20 )
                        .query_string();
     if( !name.empty() ) {
         veh->name = name;
         if( veh->tracking_on ) {
             overmap_buffer.remove_vehicle( veh );
             // Add the vehicle again, this time with the new name
             overmap_buffer.add_vehicle( veh );
         }
     }
 }
References _, overmapbuffer::add_vehicle(), om_direction::name(), vehicle::name, overmap_buffer, string_input_popup::query_string(), overmapbuffer::remove_vehicle(), string_input_popup::title(), vehicle::tracking_on, veh, and string_input_popup::width().
Referenced by populate_app_actions().
run()
player_activity veh_app_interact::run (vehicle & veh, const point & p = point_zero) static
Starts and manages the appliance interaction UI.
Parameters
veh The vehicle representing the appliance
p The point of interaction on the vehicle (Default = (0,0))
Returns
An activity to assign to the player (ACT_VEHICLE), or a null activity if no further action is required.
Definition at line 131 of file veh_appliance.cpp.
 {
     veh_app_interact ap( veh, p );
     ap.app_loop();
     return ap.act;
 }
References act, app_loop(), and veh.
Referenced by game::exam_appliance().
siphon()
void veh_app_interact::siphon () private
Function associated with the "SIPHON" action.
Checks all appliance parts for a liquid containing part that can be siphoned. If multiple parts are eligible, the player is prompted to select one. A liquid handling activity is assigned to the player to process the transfer.
Definition at line 416 of file veh_appliance.cpp.
 {
     std::vector<vehicle_part *> ptlist;
     for( const vpart_reference &vpr : veh->get_any_parts( VPFLAG_FLUIDTANK ) ) {
         if( vpr.part().get_base().has_item_with( []( const item & it ) {
         return it.made_of( phase_id::LIQUID );
         } ) ) {
             ptlist.emplace_back( &vpr.part() );
         }
     }
     vehicle_part *pt = pick_part( ptlist, _( "Which part to siphon from?" ) );
     if( pt == nullptr ) {
         return;
     }
     // Setup liquid handling activity
     const item &base = pt->get_base();
     const int idx = veh->index_of_part( pt );
     item liquid( base.legacy_front() );
     const int liq_charges = liquid.charges;
     if( liquid_handler::handle_liquid( liquid, nullptr, 1, nullptr, veh, idx ) ) {
         veh->drain( idx, liq_charges - liquid.charges );
     }
 }
References _, item::charges, vehicle::drain(), vehicle::get_any_parts(), vehicle_part::get_base(), liquid_handler::handle_liquid(), vehicle::index_of_part(), item::legacy_front(), pick_part(), veh, and VPFLAG_FLUIDTANK.
Referenced by populate_app_actions().
Member Data Documentation
a_point
point veh_app_interact::a_point = point_zero private
Definition at line 47 of file veh_appliance.h.
Referenced by can_disconnect(), disconnect(), plug(), populate_app_actions(), refill(), and remove().
act
player_activity veh_app_interact::act private
Definition at line 57 of file veh_appliance.h.
Referenced by app_loop(), refill(), remove(), and run().
app_actions
std::vector<std::function<void()> > veh_app_interact::app_actions private
Definition at line 59 of file veh_appliance.h.
Referenced by app_loop(), init_ui_windows(), and populate_app_actions().
ctxt
input_context veh_app_interact::ctxt private
Definition at line 53 of file veh_appliance.h.
Referenced by populate_app_actions(), and veh_app_interact().
imenu
uilist veh_app_interact::imenu private
Definition at line 68 of file veh_appliance.h.
Referenced by app_loop(), init_ui_windows(), and populate_app_actions().
ui
weak_ptr_fast<ui_adaptor> veh_app_interact::ui private
Definition at line 54 of file veh_appliance.h.
veh
vehicle* veh_app_interact::veh private
Definition at line 49 of file veh_appliance.h.
Referenced by app_loop(), can_disconnect(), can_refill(), can_siphon(), create_or_get_ui_adaptor(), disconnect(), draw_info(), init_ui_windows(), plug(), populate_app_actions(), refill(), remove(), rename(), run(), and siphon().
w_border
catacurses::window veh_app_interact::w_border private
Definition at line 61 of file veh_appliance.h.
Referenced by create_or_get_ui_adaptor(), and init_ui_windows().
w_info
catacurses::window veh_app_interact::w_info private
Definition at line 64 of file veh_appliance.h.
Referenced by draw_info(), and init_ui_windows().
The documentation for this class was generated from the following files:
src/veh_appliance.h
src/veh_appliance.cpp