Cataclysm DDA: TextJsonObject Class Reference
TextJsonObject Class Reference
#include <json.h>
Classes
class const_iterator
Public Member Functions
TextJsonObject (TextJsonIn &jsin)
TextJsonObject ()
TextJsonObject (const TextJsonObject &)=default
TextJsonObject (TextJsonObject &&)=default
TextJsonObject & operator= (const TextJsonObject &)=default
TextJsonObject & operator= (TextJsonObject &&)=default
~TextJsonObject ()
const_iterator begin () const
const_iterator end () const
void finish ()
size_t size () const
bool empty () const
void allow_omitted_members () const
void copy_visited_members (const TextJsonObject &rhs) const
bool has_member (const std::string &name) const
std::string str () const
void throw_error (const std::string &err) const
void throw_error_at (std::string_view name, const std::string &err) const
TextJsonIn * get_raw (std::string_view name) const
TextJsonValue get_member (std::string_view name) const
json_source_location get_source_location () const
bool get_bool (std::string_view name) const
bool get_bool (std::string_view name, bool fallback) const
int get_int (std::string_view name) const
int get_int (std::string_view name, int fallback) const
double get_float (std::string_view name) const
double get_float (std::string_view name, double fallback) const
std::string get_string (std::string_view name) const
std::string get_string (std::string_view name, const std::string &fallback) const
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value (const std::string &name, const E fallback) const
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E get_enum_value (const std::string_view name) const
TextJsonArray get_array (std::string_view name) const
std::vector< int > get_int_array (std::string_view name) const
std::vector< std::string > get_string_array (std::string_view name) const
std::vector< std::string > get_as_string_array (std::string_view name) const
TextJsonObject get_object (std::string_view name) const
template<typename T = std::string, typename Res = std::set<T>>
Res get_tags (std::string_view name) const
bool has_null (std::string_view name) const
bool has_bool (std::string_view name) const
bool has_number (std::string_view name) const
bool has_int (const std::string_view name) const
bool has_float (const std::string_view name) const
bool has_string (std::string_view name) const
bool has_array (std::string_view name) const
bool has_object (std::string_view name) const
template<typename T >
bool read (const std::string_view name, T &t, bool throw_on_error=true) const
std::string line_number () const
Public Attributes
friend const_iterator
Private Member Functions
void mark_visited (std::string_view name) const
void report_unvisited () const
int verify_position (std::string_view name, bool throw_exception=true) const
Private Attributes
std::map< std::string, int, std::less<> > positions
int start
int end_
bool final_separator
std::set< std::string > visited_members
bool report_unvisited_members = true
bool reported_unvisited_members = false
TextJsonIn * jsin
Detailed Description
Definition at line 1038 of file json.h.
Constructor & Destructor Documentation
TextJsonObject() [1/4]
TextJsonObject::TextJsonObject (TextJsonIn & jsin) explicit
Definition at line 115 of file json.cpp.
 {
     jsin = &j;
     start = jsin->tell();
     // cache the position of the value for each member
     jsin->start_object();
     while( !jsin->end_object() ) {
         std::string n = jsin->get_member_name();
         int p = jsin->tell();
         if( positions.count( n ) > 0 ) {
             j.error( "duplicate entry in json object" );
         }
         positions[n] = p;
         jsin->skip_value();
     }
     end_ = jsin->tell();
     final_separator = jsin->get_ate_separator();
 }
References end_, TextJsonIn::end_object(), TextJsonIn::error(), final_separator, TextJsonIn::get_ate_separator(), TextJsonIn::get_member_name(), jsin, positions, TextJsonIn::skip_value(), start, TextJsonIn::start_object(), and TextJsonIn::tell().
TextJsonObject() [2/4]
TextJsonObject::TextJsonObject () inline
Definition at line 1059 of file json.h.
                          :
             start( 0 ), end_( 0 ), final_separator( false ), jsin( nullptr ) {}
Referenced by get_object().
TextJsonObject() [3/4]
TextJsonObject::TextJsonObject (const TextJsonObject &) default
TextJsonObject() [4/4]
TextJsonObject::TextJsonObject (TextJsonObject &&) default
~TextJsonObject()
TextJsonObject::~TextJsonObject () inline
Definition at line 1065 of file json.h.
{
             finish();
         }
References finish().
Member Function Documentation
allow_omitted_members()
void TextJsonObject::allow_omitted_members () const
Definition at line 190 of file json.cpp.
 {
 #ifndef CATA_IN_TOOL
     report_unvisited_members = false;
 #endif
 }
References report_unvisited_members.
Referenced by JsonObject::error_no_member(), JsonObject::error_skipped_members(), and str().
begin()
TextJsonObject::const_iterator TextJsonObject::begin () const inline
Definition at line 1531 of file json.h.
 {
     return const_iterator( *this, positions.begin() );
 }
References const_iterator, and positions.
copy_visited_members()
void TextJsonObject::copy_visited_members (const TextJsonObject & rhs) const
Definition at line 197 of file json.cpp.
 {
 #ifndef CATA_IN_TOOL
     visited_members = rhs.visited_members;
 #else
     static_cast<void>( rhs );
 #endif
 }
References visited_members.
empty()
bool TextJsonObject::empty () const
Definition at line 185 of file json.cpp.
 {
     return positions.empty();
 }
References positions.
end()
TextJsonObject::const_iterator TextJsonObject::end () const inline
Definition at line 1536 of file json.h.
 {
     return const_iterator( *this, positions.end() );
 }
References const_iterator, and positions.
finish()
void TextJsonObject::finish ()
Definition at line 172 of file json.cpp.
 {
     report_unvisited();
     if( jsin && jsin->good() ) {
         jsin->seek( end_ );
         jsin->set_ate_separator( final_separator );
     }
 }
References end_, final_separator, TextJsonIn::good(), jsin, report_unvisited(), TextJsonIn::seek(), and TextJsonIn::set_ate_separator().
Referenced by ~TextJsonObject().
get_array()
TextJsonArray TextJsonObject::get_array (std::string_view name) const
Definition at line 396 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return TextJsonArray();
     }
     mark_visited( name );
     jsin->seek( pos );
     return TextJsonArray( *jsin );
 }
References jsin, mark_visited(), om_direction::name(), math_opers::pos(), TextJsonIn::seek(), and verify_position().
Referenced by add_array_to_set(), get_as_string_array(), get_int_array(), and get_string_array().
get_as_string_array()
std::vector< std::string > TextJsonObject::get_as_string_array (std::string_view name) const
Definition at line 425 of file json.cpp.
 {
     std::vector<std::string> ret;
     if( has_array( name ) ) {
         for( const std::string entry : get_array( name ) ) {
             ret.push_back( entry );
         }
     } else {
         ret.push_back( get_string( name ) );
     }
     return ret;
 }
References get_array(), get_string(), has_array(), om_direction::name(), and cata::hash64_detail::ret.
get_bool() [1/2]
bool TextJsonObject::get_bool (std::string_view name) const
Definition at line 329 of file json.cpp.
 {
     return get_member( name ).get_bool();
 }
References TextJsonValue::get_bool(), get_member(), and om_direction::name().
get_bool() [2/2]
bool TextJsonObject::get_bool (std::string_view name, bool fallback) const
Definition at line 334 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return fallback;
     }
     mark_visited( name );
     jsin->seek( pos );
     return jsin->get_bool();
 }
References TextJsonIn::get_bool(), jsin, mark_visited(), om_direction::name(), math_opers::pos(), TextJsonIn::seek(), and verify_position().
get_enum_value() [1/2]
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>> E TextJsonObject::get_enum_value (const std::string & name, const E fallback) const inline
Definition at line 1107 of file json.h.
{
             if( !has_member( name ) ) {
                 return fallback;
             }
             mark_visited( name );
             jsin->seek( verify_position( name ) );
             return jsin->get_enum_value<E>();
         }
References TextJsonIn::get_enum_value(), has_member(), jsin, mark_visited(), om_direction::name(), TextJsonIn::seek(), and verify_position().
get_enum_value() [2/2]
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>> E TextJsonObject::get_enum_value (const std::string_view name) const inline
Definition at line 1116 of file json.h.
{
             mark_visited( name );
             jsin->seek( verify_position( name ) );
             return jsin->get_enum_value<E>();
         }
References TextJsonIn::get_enum_value(), jsin, mark_visited(), om_direction::name(), TextJsonIn::seek(), and verify_position().
get_float() [1/2]
double TextJsonObject::get_float (std::string_view name) const
Definition at line 361 of file json.cpp.
 {
     return get_member( name ).get_float();
 }
References TextJsonValue::get_float(), get_member(), and om_direction::name().
get_float() [2/2]
double TextJsonObject::get_float (std::string_view name, double fallback) const
Definition at line 366 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return fallback;
     }
     mark_visited( name );
     jsin->seek( pos );
     return jsin->get_float();
 }
References TextJsonIn::get_float(), jsin, mark_visited(), om_direction::name(), math_opers::pos(), TextJsonIn::seek(), and verify_position().
get_int() [1/2]
int TextJsonObject::get_int (std::string_view name) const
Definition at line 345 of file json.cpp.
 {
     return get_member( name ).get_int();
 }
References TextJsonValue::get_int(), get_member(), and om_direction::name().
get_int() [2/2]
int TextJsonObject::get_int (std::string_view name, int fallback) const
Definition at line 350 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return fallback;
     }
     mark_visited( name );
     jsin->seek( pos );
     return jsin->get_int();
 }
References TextJsonIn::get_int(), jsin, mark_visited(), om_direction::name(), math_opers::pos(), TextJsonIn::seek(), and verify_position().
get_int_array()
std::vector< int > TextJsonObject::get_int_array (std::string_view name) const
Definition at line 407 of file json.cpp.
 {
     std::vector<int> ret;
     for( const int entry : get_array( name ) ) {
         ret.push_back( entry );
     }
     return ret;
 }
References get_array(), om_direction::name(), and cata::hash64_detail::ret.
get_member()
TextJsonValue TextJsonObject::get_member (std::string_view name) const
Definition at line 2456 of file json.cpp.
 {
     const auto iter = positions.find( name );
     if( !jsin || iter == positions.end() ) {
         throw_error( str_cat( "missing required field \"", name, "\" in object: ", str() ) );
     }
     mark_visited( name );
     return TextJsonValue( *jsin, iter->second );
 }
References jsin, mark_visited(), om_direction::name(), positions, str(), str_cat(), and throw_error().
Referenced by JsonObject::error_no_member(), get_bool(), get_float(), get_int(), and get_string().
get_object()
TextJsonObject TextJsonObject::get_object (std::string_view name) const
Definition at line 438 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return TextJsonObject();
     }
     mark_visited( name );
     jsin->seek( pos );
     return jsin->get_object();
 }
References TextJsonIn::get_object(), jsin, mark_visited(), om_direction::name(), math_opers::pos(), TextJsonIn::seek(), TextJsonObject(), and verify_position().
Referenced by TextJsonValue::operator TextJsonObject().
get_raw()
TextJsonIn * TextJsonObject::get_raw (std::string_view name) const
Definition at line 304 of file json.cpp.
 {
     int pos = verify_position( name );
     mark_visited( name );
     jsin->seek( pos );
     return jsin;
 }
References jsin, mark_visited(), om_direction::name(), math_opers::pos(), TextJsonIn::seek(), and verify_position().
get_source_location()
json_source_location TextJsonObject::get_source_location () const
Definition at line 312 of file json.cpp.
 {
     if( !jsin ) {
         throw JsonError( "TextJsonObject::get_source_location called when stream is null" );
     }
     json_source_location loc;
     loc.path = jsin->get_path();
     if( !loc.path ) {
         jsin->seek( start );
         jsin->error( "TextJsonObject::get_source_location called but the path is unknown" );
     }
     loc.offset = start;
     return loc;
 }
References TextJsonIn::error(), TextJsonIn::get_path(), jsin, json_source_location::offset, json_source_location::path, TextJsonIn::seek(), and start.
get_string() [1/2]
std::string TextJsonObject::get_string (std::string_view name) const
Definition at line 377 of file json.cpp.
 {
     return get_member( name ).get_string();
 }
References get_member(), TextJsonValue::get_string(), and om_direction::name().
Referenced by get_as_string_array().
get_string() [2/2]
std::string TextJsonObject::get_string (std::string_view name, const std::string & fallback) const
Definition at line 382 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return fallback;
     }
     mark_visited( name );
     jsin->seek( pos );
     return jsin->get_string();
 }
References TextJsonIn::get_string(), jsin, mark_visited(), om_direction::name(), math_opers::pos(), TextJsonIn::seek(), and verify_position().
get_string_array()
std::vector< std::string > TextJsonObject::get_string_array (std::string_view name) const
Definition at line 416 of file json.cpp.
 {
     std::vector<std::string> ret;
     for( const std::string entry : get_array( name ) ) {
         ret.push_back( entry );
     }
     return ret;
 }
References get_array(), om_direction::name(), and cata::hash64_detail::ret.
get_tags()
template<typename T , typename Res > Res TextJsonObject::get_tags (std::string_view name) const
Definition at line 1565 of file json.h.
 {
     Res res;
     int pos = verify_position( name, false );
     if( !pos ) {
         return res;
     }
     mark_visited( name );
     jsin->seek( pos );
     // allow single string as tag
     if( jsin->test_string() ) {
         res.insert( T( jsin->get_string() ) );
         return res;
     }
     // otherwise assume it's an array and error if it isn't.
     for( const std::string line : jsin->get_array() ) {
         if( !res.insert( T( line ) ).second ) {
             jsin->error( "duplicate item in set defined by json array" );
         }
     }
     return res;
 }
References TextJsonIn::error(), TextJsonIn::get_array(), TextJsonIn::get_string(), jsin, line, mark_visited(), om_direction::name(), math_opers::pos(), second, TextJsonIn::seek(), TextJsonIn::test_string(), and verify_position().
has_array()
bool TextJsonObject::has_array (std::string_view name) const
Definition at line 492 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return false;
     }
     jsin->seek( pos );
     return jsin->test_array();
 }
References jsin, om_direction::name(), math_opers::pos(), TextJsonIn::seek(), TextJsonIn::test_array(), and verify_position().
Referenced by get_as_string_array().
has_bool()
bool TextJsonObject::has_bool (std::string_view name) const
Definition at line 462 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return false;
     }
     jsin->seek( pos );
     return jsin->test_bool();
 }
References jsin, om_direction::name(), math_opers::pos(), TextJsonIn::seek(), TextJsonIn::test_bool(), and verify_position().
has_float()
bool TextJsonObject::has_float (const std::string_view name) const inline
Definition at line 1145 of file json.h.
{
             return has_number( name );
         }
References has_number(), and om_direction::name().
has_int()
bool TextJsonObject::has_int (const std::string_view name) const inline
Definition at line 1142 of file json.h.
{
             return has_number( name );
         }
References has_number(), and om_direction::name().
has_member()
bool TextJsonObject::has_member (const std::string & name) const
Definition at line 230 of file json.cpp.
 {
     return positions.count( name ) > 0;
 }
References om_direction::name(), and positions.
Referenced by get_enum_value().
has_null()
bool TextJsonObject::has_null (std::string_view name) const
Definition at line 451 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return false;
     }
     mark_visited( name );
     jsin->seek( pos );
     return jsin->test_null();
 }
References jsin, mark_visited(), om_direction::name(), math_opers::pos(), TextJsonIn::seek(), TextJsonIn::test_null(), and verify_position().
has_number()
bool TextJsonObject::has_number (std::string_view name) const
Definition at line 472 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return false;
     }
     jsin->seek( pos );
     return jsin->test_number();
 }
References jsin, om_direction::name(), math_opers::pos(), TextJsonIn::seek(), TextJsonIn::test_number(), and verify_position().
Referenced by has_float(), and has_int().
has_object()
bool TextJsonObject::has_object (std::string_view name) const
Definition at line 502 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return false;
     }
     jsin->seek( pos );
     return jsin->test_object();
 }
References jsin, om_direction::name(), math_opers::pos(), TextJsonIn::seek(), TextJsonIn::test_object(), and verify_position().
has_string()
bool TextJsonObject::has_string (std::string_view name) const
Definition at line 482 of file json.cpp.
 {
     int pos = verify_position( name, false );
     if( !pos ) {
         return false;
     }
     jsin->seek( pos );
     return jsin->test_string();
 }
References jsin, om_direction::name(), math_opers::pos(), TextJsonIn::seek(), TextJsonIn::test_string(), and verify_position().
line_number()
std::string TextJsonObject::line_number () const
Definition at line 235 of file json.cpp.
 {
     jsin->seek( start );
     return jsin->line_number();
 }
References jsin, TextJsonIn::line_number(), TextJsonIn::seek(), and start.
mark_visited()
void TextJsonObject::mark_visited (std::string_view name) const private
Definition at line 134 of file json.cpp.
 {
 #ifndef CATA_IN_TOOL
     visited_members.emplace( name );
 #else
     static_cast<void>( name );
 #endif
 }
References om_direction::name(), and visited_members.
Referenced by get_array(), get_bool(), get_enum_value(), get_float(), get_int(), get_member(), get_object(), get_raw(), get_string(), get_tags(), has_null(), TextJsonObject::const_iterator::operator*(), read(), and throw_error_at().
operator=() [1/2]
TextJsonObject& TextJsonObject::operator= (const TextJsonObject &) default
operator=() [2/2]
TextJsonObject& TextJsonObject::operator= (TextJsonObject &&) default
read()
template<typename T > bool TextJsonObject::read (const std::string_view name, T & t, bool throw_on_error = true) const inline
Definition at line 1158 of file json.h.
{
             int pos = verify_position( name, false );
             if( !pos ) {
                 return false;
             }
             mark_visited( name );
             jsin->seek( pos );
             return jsin->read( t, throw_on_error );
         }
References jsin, mark_visited(), om_direction::name(), math_opers::pos(), TextJsonIn::read(), TextJsonIn::seek(), and verify_position().
report_unvisited()
void TextJsonObject::report_unvisited () const private
Definition at line 143 of file json.cpp.
 {
 #ifndef CATA_IN_TOOL
     if( report_unvisited_members && !reported_unvisited_members &&
         !std::uncaught_exceptions() ) {
         reported_unvisited_members = true;
         for( const std::pair<const std::string, int> &p : positions ) {
             const std::string &name = p.first;
             if( !visited_members.count( name ) ) {
                 try {
                     if( !string_starts_with( name, "//" ) ) {
                         throw_error_at(
                             name,
                             string_format( "Invalid or misplaced field name \"%s\" in JSON data, or "
                                            "value in unexpected format.", name ) );
                     } else if( name == "//~" ) {
                         throw_error_at(
                             name,
                             "\"//~\" should be within a text object and contain comments for translators." );
                     }
                 } catch( const JsonError &e ) {
                     debugmsg( "(json-error)\n%s", e.what() );
                 }
             }
         }
     }
 #endif
 }
References debugmsg, om_direction::name(), positions, report_unvisited_members, reported_unvisited_members, string_format(), string_starts_with(), throw_error_at(), and visited_members.
Referenced by finish().
size()
size_t TextJsonObject::size () const
Definition at line 181 of file json.cpp.
 {
     return positions.size();
 }
References positions.
str()
std::string TextJsonObject::str () const
Definition at line 241 of file json.cpp.
 {
     // If we're getting the string form, we might be re-parsing later, so don't
     // complain about unvisited members.
     allow_omitted_members();
     if( jsin && end_ >= start ) {
         return jsin->substr( start, end_ - start );
     } else {
         return "{}";
     }
 }
References allow_omitted_members(), end_, jsin, start, and TextJsonIn::substr().
Referenced by get_member().
throw_error()
void TextJsonObject::throw_error (const std::string & err) const
Definition at line 296 of file json.cpp.
 {
     if( !jsin ) {
         throw JsonError( err );
     }
     jsin->error( err );
 }
References TextJsonIn::error(), and jsin.
Referenced by JsonObject::error_no_member(), and get_member().
throw_error_at()
void TextJsonObject::throw_error_at (std::string_view name, const std::string & err) const
Definition at line 254 of file json.cpp.
 {
     mark_visited( name );
     if( !jsin ) {
         throw JsonError( err );
     }
     const int pos = verify_position( name, false );
     if( pos ) {
         jsin->seek( pos );
     }
     jsin->error( err );
 }
References TextJsonIn::error(), jsin, mark_visited(), om_direction::name(), math_opers::pos(), TextJsonIn::seek(), and verify_position().
Referenced by JsonObject::error_skipped_members(), and report_unvisited().
verify_position()
int TextJsonObject::verify_position (std::string_view name, bool throw_exception = true) const private
Definition at line 206 of file json.cpp.
 {
     if( !jsin ) {
         if( throw_exception ) {
             throw JsonError( str_cat( "member lookup on empty object: ", name ) );
         }
         // 0 is always before the opening brace,
         // so it will never indicate a valid member position
         return 0;
     }
     const auto iter = positions.find( name );
     if( iter == positions.end() ) {
         if( throw_exception ) {
             jsin->seek( start );
             jsin->error( str_cat( "member not found: ", name ) );
         }
         // 0 is always before the opening brace,
         // so it will never indicate a valid member position
         return 0;
     }
     return iter->second;
 }
References TextJsonIn::error(), jsin, om_direction::name(), positions, TextJsonIn::seek(), start, and str_cat().
Referenced by get_array(), get_bool(), get_enum_value(), get_float(), get_int(), get_object(), get_raw(), get_string(), get_tags(), has_array(), has_bool(), has_null(), has_number(), has_object(), has_string(), read(), and throw_error_at().
Member Data Documentation
const_iterator
friend TextJsonObject::const_iterator
Definition at line 1071 of file json.h.
Referenced by begin(), and end().
end_
int TextJsonObject::end_ private
Definition at line 1043 of file json.h.
Referenced by finish(), str(), and TextJsonObject().
final_separator
bool TextJsonObject::final_separator private
Definition at line 1044 of file json.h.
Referenced by finish(), and TextJsonObject().
jsin
TextJsonIn* TextJsonObject::jsin private
Definition at line 1053 of file json.h.
Referenced by finish(), get_array(), get_bool(), get_enum_value(), get_float(), get_int(), get_member(), get_object(), get_raw(), get_source_location(), get_string(), get_tags(), has_array(), has_bool(), has_null(), has_number(), has_object(), has_string(), line_number(), TextJsonObject::const_iterator::operator*(), read(), str(), TextJsonObject(), throw_error(), throw_error_at(), and verify_position().
positions
std::map<std::string, int, std::less<> > TextJsonObject::positions private
Definition at line 1041 of file json.h.
Referenced by begin(), empty(), end(), get_member(), has_member(), report_unvisited(), size(), TextJsonObject(), and verify_position().
report_unvisited_members
bool TextJsonObject::report_unvisited_members = true mutable private
Definition at line 1047 of file json.h.
Referenced by allow_omitted_members(), and report_unvisited().
reported_unvisited_members
bool TextJsonObject::reported_unvisited_members = false mutable private
Definition at line 1048 of file json.h.
Referenced by report_unvisited().
start
int TextJsonObject::start private
Definition at line 1042 of file json.h.
Referenced by get_source_location(), line_number(), str(), TextJsonObject(), and verify_position().
visited_members
std::set<std::string> TextJsonObject::visited_members mutable private
Definition at line 1046 of file json.h.
Referenced by copy_visited_members(), mark_visited(), and report_unvisited().
The documentation for this class was generated from the following files:
src/json.h
src/json.cpp