Cataclysm DDA: MapgenRemovePartHandler Class Reference
MapgenRemovePartHandler Class Reference
#include <vehicle.h>
Public Member Functions
MapgenRemovePartHandler (map &m)
~MapgenRemovePartHandler () override=default
void unboard (const tripoint &) override
void add_item_or_charges (const tripoint &loc, item it, bool permit_oob) override
void set_transparency_cache_dirty (const int) override
void set_floor_cache_dirty (const int) override
void removed (vehicle &veh, const int) override
void spawn_animal_from_part (item &, const tripoint &) override
map & get_map_ref () override
Public Member Functions inherited from RemovePartHandler
virtual ~RemovePartHandler ()=default
Private Attributes
map & m
Detailed Description
Definition at line 2432 of file vehicle.h.
Constructor & Destructor Documentation
MapgenRemovePartHandler()
MapgenRemovePartHandler::MapgenRemovePartHandler (map & m) inline explicit
Definition at line 2438 of file vehicle.h.
 : m( m ) { }
~MapgenRemovePartHandler()
MapgenRemovePartHandler::~MapgenRemovePartHandler () override default
Member Function Documentation
add_item_or_charges()
void MapgenRemovePartHandler::add_item_or_charges (const tripoint & loc, item it, bool permit_oob) override virtual
Implements RemovePartHandler.
Definition at line 8359 of file vehicle.cpp.
 {
     if( !m.inbounds( loc ) ) {
         if( !permit_oob ) {
             debugmsg( "Tried to put item %s on invalid tile %s during mapgen!",
                       it.tname(), loc.to_string() );
         }
         tripoint copy = loc;
         m.clip_to_bounds( copy );
         cata_assert( m.inbounds( copy ) ); // prevent infinite recursion
         add_item_or_charges( copy, std::move( it ), false );
         return;
     }
     m.add_item_or_charges( loc, std::move( it ) );
 }
References map::add_item_or_charges(), cata_assert, map::clip_to_bounds(), debugmsg, map::inbounds(), m, item::tname(), and tripoint::to_string().
get_map_ref()
map& MapgenRemovePartHandler::get_map_ref () inline override virtual
Implements RemovePartHandler.
Definition at line 2465 of file vehicle.h.
{
             return m;
         }
References m.
removed()
void MapgenRemovePartHandler::removed (vehicle & veh, const int) inline override virtual
Implements RemovePartHandler.
Definition at line 2454 of file vehicle.h.
{
             // TODO: check if this is necessary, it probably isn't during mapgen
             m.dirty_vehicle_list.insert( &veh );
         }
References map::dirty_vehicle_list, and m.
set_floor_cache_dirty()
void MapgenRemovePartHandler::set_floor_cache_dirty (const int) inline override virtual
Implements RemovePartHandler.
Definition at line 2451 of file vehicle.h.
{
             // Ignored for now. We don't initialize the floor cache in mapgen anyway.
         }
set_transparency_cache_dirty()
void MapgenRemovePartHandler::set_transparency_cache_dirty (const int) inline override virtual
Implements RemovePartHandler.
Definition at line 2448 of file vehicle.h.
{
             // Ignored for now. We don't initialize the transparency cache in mapgen anyway.
         }
spawn_animal_from_part()
void MapgenRemovePartHandler::spawn_animal_from_part (item & , const tripoint &) inline override virtual
Implements RemovePartHandler.
Definition at line 2458 of file vehicle.h.
{
             debugmsg( "Tried to spawn animal from vehicle part during mapgen!" );
             // Ignored. The base item will not be changed and will spawn as is:
             // still containing the animal.
             // This should not happend during mapgen anyway.
             // TODO: *if* this actually happens: create a spawn point for the animal instead.
         }
References debugmsg.
unboard()
void MapgenRemovePartHandler::unboard (const tripoint &) inline override virtual
Implements RemovePartHandler.
Definition at line 2442 of file vehicle.h.
{
             debugmsg( "Tried to unboard during mapgen!" );
             // Ignored. Will almost certainly not be called anyway, because
             // there are no creatures that could have been mounted during mapgen.
         }
References debugmsg.
Member Data Documentation
m
map& MapgenRemovePartHandler::m private
Definition at line 2435 of file vehicle.h.
Referenced by add_item_or_charges(), get_map_ref(), and removed().
The documentation for this class was generated from the following files:
src/vehicle.h
src/vehicle.cpp