Cataclysm DDA: jmapgen_field Class Reference
jmapgen_field Class Reference
Places fields on the map.
Public Member Functions
jmapgen_field (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
mapgen_value< field_type_id > ftype
std::vector< int > intensities
time_duration age
bool remove
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Places fields on the map.
"field": field type ident. "intensity": initial field intensity. "age": initial field age.
Definition at line 1826 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_field()
jmapgen_field::jmapgen_field (const JsonObject & jsi, const std::string_view) inline
Definition at line 1833 of file mapgen.cpp.
                                                                       :
             ftype( jsi.get_member( "field" ) )
             , age( time_duration::from_turns( jsi.get_int( "age", 0 ) ) )
             , remove( jsi.get_bool( "remove", false ) ) {
             if( jsi.has_array( "intensity" ) ) {
                 for( JsonValue jv : jsi.get_array( "intensity" ) ) {
                     intensities.push_back( jv.get_int() );
                 }
             }
             if( intensities.empty() ) {
                 intensities.push_back( jsi.get_int( "intensity", 1 ) );
             }
         }
References JsonObject::get_array(), JsonObject::get_int(), JsonObject::has_array(), intensities, and mapgen_defer::jsi.
Member Function Documentation
apply()
void jmapgen_field::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1846 of file mapgen.cpp.
{
             field_type_id chosen_id = ftype.get( dat );
             if( chosen_id.id().is_null() ) {
                 return;
             }
             if( remove ) {
                 dat.m.remove_field( tripoint( x.get(), y.get(), z.get() ), chosen_id );
             } else {
                 dat.m.add_field( tripoint( x.get(), y.get(), z.get() ), chosen_id,
                                  random_entry( intensities ), age );
             }
         }
References map::add_field(), age, ftype, jmapgen_int::get(), int_id< T >::id(), intensities, string_id< T >::is_null(), mapgendata::m, random_entry(), remove, map::remove_field(), and tripoint.
check()
void jmapgen_field::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 1860 of file mapgen.cpp.
{
             ftype.check( oter_name, parameters );
         }
References ftype.
Member Data Documentation
age
time_duration jmapgen_field::age
Definition at line 1831 of file mapgen.cpp.
Referenced by apply().
ftype
mapgen_value<field_type_id> jmapgen_field::ftype
Definition at line 1829 of file mapgen.cpp.
Referenced by apply(), and check().
intensities
std::vector<int> jmapgen_field::intensities
Definition at line 1830 of file mapgen.cpp.
Referenced by apply(), and jmapgen_field().
remove
bool jmapgen_field::remove
Definition at line 1832 of file mapgen.cpp.
Referenced by apply().
The documentation for this class was generated from the following file:
src/mapgen.cpp