Cataclysm DDA: string_identity_static Class Reference
string_identity_static Class Reference
"static" here means std::string inside is interned.
#include <string_id.h>
Private Member Functions
string_identity_static ()
template<typename S , class = std::enable_if_t<std::is_convertible_v<S, std::string>>>
string_identity_static (S &&id)
const std::string & str () const
bool is_empty () const
Static Private Member Functions
static int string_id_intern (std::string &&s)
Returns unique int identifier for this string.
static int string_id_intern (std::string &s)
static int string_id_intern (const std::string &s)
static const std::string & get_interned_string (int id)
Returns string by its unique identifier.
static int empty_interned_string ()
Returns unique int identifier for empty string (cached)
Private Attributes
int _id
const char * _string_id = nullptr
Friends
template<typename T >
class string_id
template<typename T >
struct std::hash
Detailed Description
"static" here means std::string inside is interned.
Can be used only if all string_id values are fixed in number and not generated dynamically.
Definition at line 114 of file string_id.h.
Constructor & Destructor Documentation
string_identity_static() [1/2]
string_identity_static::string_identity_static () inline private
Definition at line 124 of file string_id.h.
             : _id( empty_interned_string() )
 #ifdef CATA_STRING_ID_DEBUGGING
             , _string_id( "" )
 #endif
         {}
string_identity_static() [2/2]
template<typename S , class = std::enable_if_t<std::is_convertible_v<S, std::string>>> string_identity_static::string_identity_static (S && id) inline explicit private
Definition at line 132 of file string_id.h.
                      : _id( string_id_intern( std::forward<S>( id ) ) )
 #ifdef CATA_STRING_ID_DEBUGGING
             , _string_id( str().c_str() )
 #endif
         {}
Member Function Documentation
empty_interned_string()
int string_identity_static::empty_interned_string () static private
Returns unique int identifier for empty string (cached)
Definition at line 54 of file string_id.cpp.
 {
     static int empty_string_id = string_id_intern( "" );
     return empty_string_id;
 }
References string_id_intern().
Referenced by is_empty().
get_interned_string()
const std::string & string_identity_static::get_interned_string (int id) static private
Returns string by its unique identifier.
Definition at line 49 of file string_id.cpp.
 {
     return *get_reverse_lookup_vec()[id];
 }
References get_reverse_lookup_vec(), and base_camps::id.
Referenced by str().
is_empty()
bool string_identity_static::is_empty () const inline private
Definition at line 143 of file string_id.h.
{
             return _id == empty_interned_string();
         }
References _id, and empty_interned_string().
str()
const std::string& string_identity_static::str () const inline private
Definition at line 139 of file string_id.h.
{
             return get_interned_string( _id );
         }
References _id, and get_interned_string().
string_id_intern() [1/3]
int string_identity_static::string_id_intern (const std::string & s) static private
Definition at line 34 of file string_id.cpp.
 {
     return universal_string_id_intern( s );
 }
References universal_string_id_intern().
string_id_intern() [2/3]
int string_identity_static::string_id_intern (std::string && s) static private
Returns unique int identifier for this string.
Definition at line 44 of file string_id.cpp.
 {
     return universal_string_id_intern( std::move( s ) );
 }
References universal_string_id_intern().
Referenced by empty_interned_string().
string_id_intern() [3/3]
int string_identity_static::string_id_intern (std::string & s) static private
Definition at line 39 of file string_id.cpp.
 {
     return universal_string_id_intern( s );
 }
References universal_string_id_intern().
Friends And Related Function Documentation
std::hash
template<typename T > friend struct std::hash friend
Definition at line 161 of file string_id.h.
string_id
template<typename T > friend class string_id friend
Definition at line 158 of file string_id.h.
Member Data Documentation
_id
int string_identity_static::_id private
Definition at line 117 of file string_id.h.
Referenced by is_empty(), and str().
_string_id
const char* string_identity_static::_string_id = nullptr private
Definition at line 122 of file string_id.h.
The documentation for this class was generated from the following files:
src/string_id.h
src/string_id.cpp