Cataclysm DDA: visitable Class Reference
visitable Class Reference abstract
Read-write interface for the "container of items".
#include <visitable.h>
Public Member Functions
virtual std::list< item > remove_items_with (const std::function< bool(const item &)> &filter, int count=INT_MAX)=0
Removes items contained by this instance which match the filter.
item remove_item (item &it)
Removes and returns the item which must be contained by this instance.
Public Member Functions inherited from read_only_visitable
item * find_parent (const item &it) const
Determine the immediate parent container (if any) for an item.
std::vector< item * > parents (const item &it) const
Returns vector of parent containers (if any) starting with the innermost.
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
std::pair< int, int > kcal_range (const itype_id &id, const std::function< bool(const item &)> &filter, Character &player_character) const
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
virtual ~read_only_visitable ()=default
bool has_tools (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
bool has_components (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
virtual bool has_charges (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
Related Functions
(Note that these are not member functions.)
item * find_parent (const item &it) const
std::vector< item * > parents (const item &it) const
bool has_item (const item &it) const
bool has_item_with (const std::function< bool(const item &)> &filter) const
bool has_quality (const quality_id &qual, int level, int qty) const
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const
Traverses this object and any child items contained using a visitor pattern.
std::list< item > remove_items_with (const std::function< bool(const item &e)> &filter, int count)
int charges_of (const itype_id &what, int limit, const std::function< bool(const item &)> &filter, const std::function< void(int)> &visitor, bool in_tools) const
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo, int limit, const std::function< bool(const item &)> &filter) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo, const std::function< bool(const item &)> &filter) const
Detailed Description
Read-write interface for the "container of items".
Provides API for the traversal and querying of the items hierarchy. Also provides means to modify the hierarchy.
Definition at line 118 of file visitable.h.
Member Function Documentation
remove_item()
item remove_item (item & it)
Removes and returns the item which must be contained by this instance.
Definition at line 543 of file visitable.cpp.
 {
     auto obj = remove_items_with( [&it]( const item & e ) {
         return &e == &it;
     }, 1 );
     if( !obj.empty() ) {
         return obj.front();
     } else {
         debugmsg( "Tried removing item from object which did not contain it" );
         return item();
     }
 }
References debugmsg, item, and remove_items_with().
Referenced by Character::ablative_armor_absorb(), activity_on_turn_move_loot(), item_contents::ammo_consume(), anonymous_namespace{monexamine.cpp}::attach_bag_to(), vehicle_part::consume_energy(), consume_items_in_zones(), talker_item::die(), Character::dismount(), Character::dispose_item(), basecamp::distribute_food(), empty_autopickup_target(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), gunmod_add_activity_actor::finish(), Character::forced_dismount(), talk_function::give_equipment_allowance(), item::gun_info(), liquid_handler::handle_liquid_from_container(), Character::handle_melee_wear(), monster::init_from_item(), iuse::multicooker(), om_set_hide_site(), process_map_items(), iuse::radiocar(), item::reload(), item_location::impl::item_on_map::remove_item(), item_location::impl::item_on_person::remove_item(), item_location::impl::item_on_vehicle::remove_item(), item_location::impl::item_in_container::remove_item(), npc::stow_item(), npc_trading::transfer_items(), unload_activity_actor::unload(), detach_gunmods_actor::use(), item::use_amount(), Character::use_amount(), Character::use_charges(), Character::wear(), npc::wield(), and Character::wield_contents().
remove_items_with()
virtual std::list<item> visitable::remove_items_with (const std::function< bool(const item &)> & filter, int count = INT_MAX) pure virtual
Removes items contained by this instance which match the filter.
Note
: Implement for each class that will implement the visitable interface
if this instance itself is an item it will not be considered by the filter
Parameters
filter a UnaryPredicate which should return true if the item is to be removed
count maximum number of items to if unspecified unlimited. A count of zero is a no-op
Returns
any items removed (items counted by charges are not guaranteed to be stacked)
Implemented in vehicle_selector, vehicle_cursor, map_selector, map_cursor, item, inventory, and Character.
Referenced by remove_item().
Friends And Related Function Documentation
amount_of()
int amount_of (const itype_id & what, bool pseudo, int limit, const std::function< bool(const item &)> & filter) const related
Count items matching id including both this instance and any contained items.
Parameters
what ID of items to count. "any" will count all items (usually used with a filter)
pseudo whether pseudo-items (from map/vehicle tiles, bionics etc) are considered
limit stop searching after this many matches
filter only count items that match the filter
Note
items must be empty to be considered a match
Reimplemented from read_only_visitable.
Definition at line 959 of file visitable.cpp.
 {
     return amount_of_internal( *this, what, pseudo, limit, filter );
 }
References amount_of_internal(), and filter.
charges_of()
int charges_of (const itype_id & what, int limit, const std::function< bool(const item &)> & filter, const std::function< void(int)> & visitor, bool in_tools) const related
Count maximum available charges from this instance and any contained items.
Parameters
what ID of item to count charges of
limit stop searching after this many charges have been found
filter only count charges of items that match the filter
visitor is called when UPS charge is used (parameter is the charge itself)
Reimplemented from read_only_visitable.
Definition at line 895 of file visitable.cpp.
 {
     return charges_of_internal( *this, *this, what, limit, filter, visitor, in_tools );
 }
References charges_of_internal(), and filter.
Referenced by json_item_substitution::get_substitution().
find_parent()
item * find_parent (const item & it) const related
Definition at line 49 of file visitable.cpp.
 {
     item *res = nullptr;
     if( visit_items( [&]( item * node, item * parent ) {
     if( node == &it ) {
             res = parent;
             return VisitResponse::ABORT;
         }
         return VisitResponse::NEXT;
     } ) != VisitResponse::ABORT ) {
         debugmsg( "Tried to find item parent using an object that doesn't contain it" );
     }
     return res;
 }
References ABORT, debugmsg, NEXT, and read_only_visitable::visit_items().
Referenced by form_loc_recursive(), Character::get_weapon_dispersion(), and item::use_amount().
has_amount()
bool has_amount (const itype_id & what, int qty, bool pseudo, const std::function< bool(const item &)> & filter) const related
Definition at line 1018 of file visitable.cpp.
 {
     return amount_of( what, pseudo, qty, filter ) == qty;
 }
References read_only_visitable::amount_of(), and filter.
Referenced by computer_session::action_repeater_mod(), computer_session::action_srcf_elevator(), timed_event::actualize(), game::bury_screen(), Character::can_eat(), iexamine::can_fertilize(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), craft_command::check_item_components_missing(), craft_command::check_tool_components_missing(), consume_med(), Character::craft_consume_tools(), talk_function::field_harvest(), game::find_or_make_stairs(), activatable_inventory_preset::get_denial(), repair_item_actor::handle_components(), talker_character_const::has_amount(), monexamine::mech_hack(), iuse::meth(), iuse::multicooker(), iexamine::pedestal_temple(), tutorial_game::per_turn(), monexamine::pet_menu(), iexamine::pit(), tutorial_game::post_action(), query_for_item(), repair_inventory_preset::repair_inventory_preset(), repair_item_finish(), Character::select_item_component(), Character::select_tool_component(), try_consume(), consume_drug_iuse::use(), sew_advanced_actor::use(), npc::value(), and weed_msg().
has_item()
bool has_item (const item & it) const related
Definition at line 75 of file visitable.cpp.
 {
     return visit_items( [&it]( const item * node, item * ) {
         return node == &it ? VisitResponse::ABORT : VisitResponse::NEXT;
     } ) == VisitResponse::ABORT;
 }
References ABORT, NEXT, and read_only_visitable::visit_items().
Referenced by can_butcher_at(), relic::can_recharge(), Character::consume_charges(), item::convert(), iuse::disassemble(), game::do_regular_action(), iuse::einktabletpc(), form_loc(), pickup_inventory_preset::get_denial(), get_item_location(), Character::get_item_position(), liquid_handler::get_liquid_target(), item::get_remaining_capacity_for_liquid(), Character::get_weapon_dispersion(), Character::gunmod_add(), outfit::holster_opts(), exosuit_interact::insert_replace_activate_mod(), game::inventory_item_menu(), enchantment::is_active(), link_up_actor::link_to_veh_app(), link_up_actor::link_tow_cable(), avatar_action::mend(), item_location::impl::item_on_map::obtain(), item::process_extinguish(), inventory_column::reassign_custom_invlets(), Character::reduce_charges(), game::reload(), effect_on_conditons_actor::use(), Character::wear(), npc::wield(), avatar::wield(), game::wield(), and Character::wield_contents().
has_item_with()
bool has_item_with (const std::function< bool(const item &)> & filter) const related
Definition at line 83 of file visitable.cpp.
 {
     return visit_items( [&filter]( const item * node, item * ) {
         return filter( *node ) ? VisitResponse::ABORT : VisitResponse::NEXT;
     } ) == VisitResponse::ABORT;
 }
References ABORT, filter, NEXT, and read_only_visitable::visit_items().
Referenced by behavior::character_oracle_t::can_make_fire(), behavior::character_oracle_t::can_wear_warmer_clothes(), Character::has_active_item(), Character::has_item_with_flag(), Character::has_mission_item(), item::in_container(), item::is_food_container(), iexamine::keg(), iuse::portable_game(), Character::pour_into(), and iuse::water_purifier().
has_quality()
bool has_quality (const quality_id & qual, int level, int qty) const related
Returns true if instance has amount (or more) items of at least quality level.
Reimplemented from read_only_visitable.
Definition at line 153 of file visitable.cpp.
 {
     const quality_query query{ qual, level, qty };
     if( qualities_cache.find( query ) == qualities_cache.end() ) {
         int res = 0;
         for( const auto &stack : this->items ) {
             res += stack.size() * has_quality_internal( stack.front(), qual, level, qty );
             if( res >= qty ) {
                 qualities_cache[query] = true;
             }
         }
     }
     return qualities_cache[query];
 }
References has_quality_internal(), inventory::items, and inventory::qualities_cache.
Referenced by iexamine::autodoc(), autodoc_internal(), can_do_activity_there(), check_deploy_square(), requirements_map(), and prying_activity_actor::start().
items_with() [1/2]
std::vector< item * > items_with (const std::function< bool(const item &)> & filter) related
Definition at line 336 of file visitable.cpp.
 {
     return items_with_internal<item *>( *this, filter );
 }
References filter.
items_with() [2/2]
std::vector< const item * > items_with (const std::function< bool(const item &)> & filter) const related
Definition at line 330 of file visitable.cpp.
 {
     return items_with_internal<const item *>( *this, filter );
 }
References filter.
Referenced by npc::alt_attack(), iexamine::autodoc(), autodoc_internal(), Character::best_item_with_quality(), iuse::binder_add_recipe(), game::butcher(), can_do_activity_there(), talker_character_const::const_items_with(), farm_action(), bookbinder_copy_activity_actor::finish(), iexamine::fireplace(), generic_multi_activity_do(), bionic_install_preset::get_failure_chance(), Character::gunmod_add(), npc::heal_self(), npc_trading::init_selling(), talker_character::items_with(), iexamine::keg(), iexamine::locked_object_pickable(), mill_load_food(), mine_activity(), npc::mug_player(), avatar::power_bionics(), iexamine::sign(), Character::use_amount(), and vehicle::use_washing_machine().
max_quality()
int max_quality (const quality_id & qual) const related
Return maximum tool quality level provided by instance or INT_MIN if not found.
Reimplemented from read_only_visitable.
Definition at line 268 of file visitable.cpp.
 {
     int res = INT_MIN;
     for( const bionic &bio : *my_bionics ) {
         res = std::max( res, bio.get_quality( qual ) );
     }
     if( qual == qual_BUTCHER ) {
         for( const trait_id &mut : get_mutations() ) {
             res = std::max( res, mut->butchering_quality );
         }
     }
     return std::max( res, max_quality_internal( *this, qual ) );
 }
References Character::get_mutations(), max(), max_quality_internal(), Character::my_bionics, and qual_BUTCHER.
Referenced by Character::best_nearby_lifting_assist(), and veh_interact::cache_tool_availability().
parents()
std::vector< item * > parents (const item & it) const related
Definition at line 65 of file visitable.cpp.
 {
     std::vector<item *> res;
     for( item *obj = find_parent( it ); obj; obj = find_parent( *obj ) ) {
         res.push_back( obj );
     }
     return res;
 }
References read_only_visitable::find_parent().
Referenced by item_location::impl::item_on_person::describe(), inventory_selector::drag_drop_item(), and item::inherit_flags().
remove_items_with()
std::list< item > remove_items_with (const std::function< bool(const item &e)> & filter, int count) related
Definition at line 558 of file visitable.cpp.
 {
     std::list<item> res;
     if( count <= 0 ) {
         // nothing to do
         return res;
     }
     contents.remove_internal( filter, count, res );
     // updating pockets is only necessary when removing mods,
     // but no way to determine where something got removed here
     update_modified_pockets();
     return res;
 }
References item::contents, item::count(), filter, item_contents::remove_internal(), and item::update_modified_pockets().
visit_items()
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> & func) const related
Traverses this object and any child items contained using a visitor pattern.
Note
Implement for each class that will implement the visitable interface. Other visit_items variants rely on this function.
Parameters
func visitor function called for each node which controls whether traversal continues. The first argument is the node and the second is the parent node (if any) The visitor function should return VisitResponse::Next to recursively process child items, VisitResponse::Skip to ignore children of the current node or VisitResponse::Abort to skip all remaining nodes
Returns
This method itself only ever returns VisitResponse::Next or VisitResponse::Abort.
Implements read_only_visitable.
Definition at line 405 of file visitable.cpp.
 {
     return visit_internal( func, this );
 }
References visit_internal().
The documentation for this class was generated from the following files:
src/visitable.h
src/visitable.cpp