Cataclysm DDA: weather_generator Class Reference
weather_generator Class Reference
#include <weather_gen.h>
Public Member Functions
weather_generator ()
w_point get_weather (const tripoint_abs_ms &, const time_point &, unsigned) const
Input should be an absolute position in the map square system (the one used by the map).
weather_type_id get_weather_conditions (const tripoint_abs_ms &, const time_point &, unsigned seed) const
weather_type_id get_weather_conditions (const w_point &) const
int get_wind_direction (season_type) const
int convert_winddir (int) const
units::temperature get_water_temperature () const
void test_weather (unsigned seed) const
void sort_weather ()
units::temperature get_weather_temperature (const tripoint &, const time_point &, unsigned) const
Static Public Member Functions
static weather_generator load (const JsonObject &jo)
Public Attributes
double base_temperature = 0
double base_humidity = 0
double base_pressure = 0
double base_wind = 0
int base_wind_distrib_peaks = 0
int summer_temp_manual_mod = 0
int spring_temp_manual_mod = 0
int autumn_temp_manual_mod = 0
int winter_temp_manual_mod = 0
int spring_humidity_manual_mod = 0
int summer_humidity_manual_mod = 0
int autumn_humidity_manual_mod = 0
int winter_humidity_manual_mod = 0
int base_wind_season_variation = 0
std::vector< std::string > weather_black_list
std::vector< std::string > weather_white_list
std::vector< weather_type_id > sorted_weather
All the current weather types based on white or black list and sorted by load order.
Static Public Attributes
static int current_winddir = 1000
Detailed Description
Definition at line 28 of file weather_gen.h.
Constructor & Destructor Documentation
weather_generator()
weather_generator::weather_generator () default
Member Function Documentation
convert_winddir()
int weather_generator::convert_winddir (int inputdir) const
Definition at line 242 of file weather_gen.cpp.
 {
     // Convert from discrete distribution output to angle
     float finputdir = inputdir * 22.5f;
     return static_cast<int>( finputdir );
 }
Referenced by get_weather().
get_water_temperature()
units::temperature weather_generator::get_water_temperature () const
WATER TEMPERATURE source : http://echo2.epfl.ch/VICAIRE/mod_2/chapt_5/main.htm source : http://www.grandriver.ca/index/document.cfm?Sec=2&Sub1=7&sub2=1
Definition at line 249 of file weather_gen.cpp.
 {
     /**
     WATER TEMPERATURE
     source : http://echo2.epfl.ch/VICAIRE/mod_2/chapt_5/main.htm
     source : http://www.grandriver.ca/index/document.cfm?Sec=2&Sub1=7&sub2=1
     **/
     season_effective_time t( calendar::turn );
     int season_length = to_days<int>( calendar::season_length() );
     int day = to_days<int>( time_past_new_year( t.t ) );
     int hour = hour_of_day<int>( t.t );
     float water_temperature = 0;
     if( season_length == 0 ) {
         season_length = 1;
     }
     // Temperature varies between 33.8F and 75.2F depending on the time of year. Day = 0 corresponds to the start of spring.
     float annual_mean_water_temperature = 54.5 + 20.7 * std::sin( tau * ( day - season_length * 0.5 ) /
                                           ( season_length * 4.0 ) );
     // Temperature varies between +2F and -2F depending on the time of day. Hour = 0 corresponds to midnight.
     float daily_water_temperature_variation = 2.0 + 2.0 * std::sin( tau * ( hour - 6.0 ) / 24.0 );
     water_temperature = annual_mean_water_temperature + daily_water_temperature_variation;
     return units::from_fahrenheit( water_temperature );
 }
References day, units::from_fahrenheit(), hour, calendar::season_length(), sin(), season_effective_time::t, anonymous_namespace{weather_gen.cpp}::tau, time_past_new_year(), and calendar::turn.
Referenced by Character::update_bodytemp().
get_weather()
w_point weather_generator::get_weather (const tripoint_abs_ms & location, const time_point & real_t, unsigned seed) const
Input should be an absolute position in the map square system (the one used by the map).
You can use map::getabs to get an absolute position from a relative position (relative to the map you called getabs on).
Definition at line 114 of file weather_gen.cpp.
 {
     season_effective_time t( real_t );
     const weather_gen_common common = get_common_data( location.raw(), real_t, seed );
     const double x( common.x );
     const double y( common.y );
     const double z( common.z );
     const unsigned modSEED = common.modSEED;
     const double cyf( common.cyf );
     const double seasonality = -common.cyf;
     // -1 in midwinter, +1 in midsummer
     const season_type season = common.season;
     // Noise factors
     const units::temperature T( weather_temperature_from_common_data( *this, common, t ) );
     double W( raw_noise_4d( x / 2.5, y / 2.5, z / 200, modSEED ) * 10.0 );
     // Humidity variation
     double mod_h( 0 );
     if( season == WINTER ) {
         mod_h += winter_humidity_manual_mod;
     } else if( season == SPRING ) {
         mod_h += spring_humidity_manual_mod;
     } else if( season == SUMMER ) {
         mod_h += summer_humidity_manual_mod;
     } else if( season == AUTUMN ) {
         mod_h += autumn_humidity_manual_mod;
     }
     // Relative humidity, a percentage.
     double H = std::min( 100., std::max( 0.,
                                          base_humidity + mod_h + 100 * (
                                                  .15 * seasonality +
                                                  raw_noise_4d( x, y, z, modSEED + 101 ) *
                                                  .2 * ( -seasonality + 2 ) ) ) );
     // Pressure
     double P =
         base_pressure +
         raw_noise_4d( x, y, z, modSEED + 211 ) *
         10 * ( -seasonality + 2 );
     // Wind power
     W = std::max( 0, static_cast<int>( base_wind * rng( 1, 2 ) / std::pow( ( P + W ) / 1014.78, rng( 9,
                                        base_wind_distrib_peaks ) ) +
                                        -cyf / base_wind_season_variation * rng( 1, 2 ) ) );
     // Initial static variable
     if( current_winddir == 1000 ) {
         current_winddir = get_wind_direction( season );
         current_winddir = convert_winddir( current_winddir );
     } else {
         // When wind strength is low, wind direction is more variable
         bool changedir = one_in( W * 2160 );
         if( changedir ) {
             current_winddir = get_wind_direction( season );
             current_winddir = convert_winddir( current_winddir );
         }
     }
     std::string wind_desc = get_wind_desc( W );
     return w_point{ T, H, P, W, wind_desc, current_winddir, t, location };
 }
References AUTUMN, autumn_humidity_manual_mod, base_humidity, base_pressure, base_wind, base_wind_distrib_peaks, base_wind_season_variation, game_menus::inv::common(), convert_winddir(), current_winddir, get_common_data(), get_wind_desc(), get_wind_direction(), location, max(), min(), one_in(), raw_noise_4d(), rng(), season, iuse::seed(), SPRING, spring_humidity_manual_mod, SUMMER, summer_humidity_manual_mod, weather_temperature_from_common_data(), WINTER, and winter_humidity_manual_mod.
Referenced by get_weather_conditions(), test_weather(), weather_manager::update_weather(), and weather_forecast().
get_weather_conditions() [1/2]
weather_type_id weather_generator::get_weather_conditions (const tripoint_abs_ms & location, const time_point & t, unsigned seed) const
Definition at line 178 of file weather_gen.cpp.
 {
     w_point w( get_weather( location, t, seed ) );
     weather_type_id wt = get_weather_conditions( w );
     return wt;
 }
References get_weather(), location, and iuse::seed().
Referenced by current_weather(), overmap_ui::get_weather_at_point(), test_weather(), weather_manager::update_weather(), and weather_forecast().
get_weather_conditions() [2/2]
weather_type_id weather_generator::get_weather_conditions (const w_point & w) const
Definition at line 186 of file weather_gen.cpp.
 {
     // We're being asked for the weather condition given a set of parameters (humidity, pressure, etc),
     // but the dialogue condition system which drives that logic has no way for us to provide them
     // directly; it can only reference the current game state. Until it's overhauled, we'll just hack
     // the current game state while checking the conditions.
     const weather_manager &game_weather = get_weather_const();
     w_point original_weather_precise = *game_weather.weather_precise;
     *game_weather.weather_precise = w;
     std::unordered_map<std::string, std::string> context;
     context["npctalk_var_weather_location"] = w.location.to_string();
     weather_type_id current_conditions = WEATHER_CLEAR;
     dialogue d( get_talker_for( get_avatar() ), nullptr, {}, context );
     for( const weather_type_id &type : sorted_weather ) {
         bool required_weather = type->required_weathers.empty();
         if( !required_weather ) {
             for( const weather_type_id &weather : type->required_weathers ) {
                 if( weather == current_conditions ) {
                     required_weather = true;
                     break;
                 }
             }
         }
         if( required_weather && type->condition( d ) ) {
             current_conditions = type;
             continue;
         }
     }
     // Cleanup our conditional hack.
     *game_weather.weather_precise = original_weather_precise;
     return current_conditions;
 }
References context, get_avatar(), get_talker_for(), get_weather_const(), w_point::location, sorted_weather, coords::coord_point_base< Point >::to_string(), type, WEATHER_CLEAR(), and weather_manager::weather_precise.
get_weather_temperature()
units::temperature weather_generator::get_weather_temperature (const tripoint & location, const time_point & real_t, unsigned seed) const
Definition at line 108 of file weather_gen.cpp.
 {
     return weather_temperature_from_common_data( *this, get_common_data( location, real_t, seed ),
             season_effective_time( real_t ) );
 }
References get_common_data(), location, iuse::seed(), and weather_temperature_from_common_data().
Referenced by item::process_temperature_rot().
get_wind_direction()
int weather_generator::get_wind_direction (season_type season) const
Definition at line 221 of file weather_gen.cpp.
 {
     cata_default_random_engine &wind_dir_gen = rng_get_engine();
     // Assign chance to angle direction
     if( season == SPRING ) {
         std::discrete_distribution<int> distribution {3, 3, 5, 8, 11, 10, 5, 2, 5, 6, 6, 5, 8, 10, 8, 6};
         return distribution( wind_dir_gen );
     } else if( season == SUMMER ) {
         std::discrete_distribution<int> distribution {3, 4, 4, 8, 8, 9, 8, 3, 7, 8, 10, 7, 7, 7, 5, 3};
         return distribution( wind_dir_gen );
     } else if( season == AUTUMN ) {
         std::discrete_distribution<int> distribution {4, 6, 6, 7, 6, 5, 4, 3, 5, 6, 8, 8, 10, 10, 8, 5};
         return distribution( wind_dir_gen );
     } else if( season == WINTER ) {
         std::discrete_distribution<int> distribution {5, 3, 2, 3, 2, 2, 2, 2, 4, 6, 10, 8, 12, 19, 13, 9};
         return distribution( wind_dir_gen );
     } else {
         return 0;
     }
 }
References AUTUMN, rng_get_engine(), season, SPRING, SUMMER, and WINTER.
Referenced by get_weather().
load()
weather_generator weather_generator::load (const JsonObject & jo) static
Definition at line 337 of file weather_gen.cpp.
 {
     weather_generator ret;
     ret.base_temperature = jo.get_float( "base_temperature", 0.0 );
     ret.base_humidity = jo.get_float( "base_humidity", 50.0 );
     ret.base_pressure = jo.get_float( "base_pressure", 0.0 );
     ret.base_wind = jo.get_float( "base_wind", 0.0 );
     ret.base_wind_distrib_peaks = jo.get_int( "base_wind_distrib_peaks", 0 );
     ret.base_wind_season_variation = jo.get_int( "base_wind_season_variation", 0 );
     ret.summer_temp_manual_mod = jo.get_int( "summer_temp_manual_mod", 0 );
     ret.spring_temp_manual_mod = jo.get_int( "spring_temp_manual_mod", 0 );
     ret.autumn_temp_manual_mod = jo.get_int( "autumn_temp_manual_mod", 0 );
     ret.winter_temp_manual_mod = jo.get_int( "winter_temp_manual_mod", 0 );
     ret.spring_humidity_manual_mod = jo.get_int( "spring_humidity_manual_mod", 0 );
     ret.summer_humidity_manual_mod = jo.get_int( "summer_humidity_manual_mod", 0 );
     ret.autumn_humidity_manual_mod = jo.get_int( "autumn_humidity_manual_mod", 0 );
     ret.winter_humidity_manual_mod = jo.get_int( "winter_humidity_manual_mod", 0 );
     ret.weather_black_list = jo.get_string_array( "weather_black_list" );
     ret.weather_white_list = jo.get_string_array( "weather_white_list" );
     if( !ret.weather_black_list.empty() && !ret.weather_white_list.empty() ) {
         jo.throw_error( "weather_black_list and weather_white_list are mutually exclusive" );
     }
     return ret;
 }
References JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_string_array(), cata::hash64_detail::ret, and JsonObject::throw_error().
Referenced by load_region_settings().
sort_weather()
void weather_generator::sort_weather ()
Definition at line 316 of file weather_gen.cpp.
 {
     sorted_weather.clear();
     for( const weather_type &wt : weather_types::get_all() ) {
         // if we have a white list, only add those, if we have a black list, add all but those
         if( weather_white_list.empty() ) {
             if( std::find( weather_black_list.begin(), weather_black_list.end(),
                            wt.id.c_str() ) == weather_black_list.end() ) {
                 sorted_weather.push_back( wt.id );
             }
         } else if( std::find( weather_white_list.begin(), weather_white_list.end(),
                               wt.id.c_str() ) != weather_white_list.end() || wt.id == WEATHER_CLEAR ) {
             sorted_weather.push_back( wt.id );
         }
     }
     std::sort( sorted_weather.begin(), sorted_weather.end(), []( const weather_type_id & a,
     const weather_type_id & b ) {
         return a->priority < b->priority;
     } );
 }
References a, b, weather_types::get_all(), sorted_weather, weather_black_list, WEATHER_CLEAR(), and weather_white_list.
test_weather()
void weather_generator::test_weather (unsigned seed) const
Definition at line 279 of file weather_gen.cpp.
 {
     // Outputs a Cata year's worth of weather data to a CSV file.
     // Usage:
     // weather_generator WEATHERGEN; // Instantiate the class.
     // WEATHERGEN.test_weather(); // Runs this test.
     write_to_file( "weather.output", [&]( std::ostream & testfile ) {
         testfile <<
                  "|;year;season;day;hour;minute;temperature(F);humidity(%);pressure(mB);weatherdesc;windspeed(mph);winddirection"
                  << std::endl;
         const time_point begin = calendar::turn;
         const time_point end = begin + 2 * calendar::year_length();
         for( time_point i = begin; i < end; i += 20_minutes ) {
             w_point w = get_weather( tripoint_abs_ms( tripoint_zero ), i, seed );
             weather_type_id conditions = get_weather_conditions( w );
             int year = to_turns<int>( i - calendar::turn_zero ) / to_turns<int>
                        ( calendar::year_length() ) + 1;
             const int hour = hour_of_day<int>( i );
             const int minute = minute_of_hour<int>( i );
             int day;
             if( calendar::eternal_season() ) {
                 day = to_days<int>( time_past_new_year( i ) );
             } else {
                 day = day_of_season<int>( i );
             }
             testfile << "|;" << year << ";" << season_of_year( i ) << ";" << day << ";" << hour << ";" << minute
                      << ";" << units::to_fahrenheit( w.temperature ) << ";" << w.humidity << ";" << w.pressure << ";" <<
                      conditions->name << ";"
                      <<
                      w.windpower << ";" << w.winddirection << std::endl;
         }
     }, "weather test file" );
 }
References day, keycode::end, calendar::eternal_season(), get_weather(), get_weather_conditions(), hour, w_point::humidity, minute, weather_type::name, w_point::pressure, season_of_year(), iuse::seed(), w_point::temperature, time_past_new_year(), units::to_fahrenheit(), tripoint_zero, calendar::turn, calendar::turn_zero, w_point::winddirection, w_point::windpower, write_to_file(), year, and calendar::year_length().
Referenced by debug_menu::debug().
Member Data Documentation
autumn_humidity_manual_mod
int weather_generator::autumn_humidity_manual_mod = 0
Definition at line 47 of file weather_gen.h.
Referenced by get_weather().
autumn_temp_manual_mod
int weather_generator::autumn_temp_manual_mod = 0
Definition at line 43 of file weather_gen.h.
Referenced by weather_temperature_from_common_data().
base_humidity
double weather_generator::base_humidity = 0
Definition at line 34 of file weather_gen.h.
Referenced by get_weather().
base_pressure
double weather_generator::base_pressure = 0
Definition at line 36 of file weather_gen.h.
Referenced by get_weather().
base_temperature
double weather_generator::base_temperature = 0
Definition at line 32 of file weather_gen.h.
Referenced by weather_temperature_from_common_data().
base_wind
double weather_generator::base_wind = 0
Definition at line 38 of file weather_gen.h.
Referenced by get_weather().
base_wind_distrib_peaks
int weather_generator::base_wind_distrib_peaks = 0
Definition at line 40 of file weather_gen.h.
Referenced by get_weather().
base_wind_season_variation
int weather_generator::base_wind_season_variation = 0
Definition at line 50 of file weather_gen.h.
Referenced by get_weather().
current_winddir
int weather_generator::current_winddir = 1000 static
Definition at line 51 of file weather_gen.h.
Referenced by get_weather().
sorted_weather
std::vector<weather_type_id> weather_generator::sorted_weather
All the current weather types based on white or black list and sorted by load order.
Definition at line 55 of file weather_gen.h.
Referenced by debug_menu::change_weather(), get_weather_conditions(), and sort_weather().
spring_humidity_manual_mod
int weather_generator::spring_humidity_manual_mod = 0
Definition at line 45 of file weather_gen.h.
Referenced by get_weather().
spring_temp_manual_mod
int weather_generator::spring_temp_manual_mod = 0
Definition at line 42 of file weather_gen.h.
Referenced by weather_temperature_from_common_data().
summer_humidity_manual_mod
int weather_generator::summer_humidity_manual_mod = 0
Definition at line 46 of file weather_gen.h.
Referenced by get_weather().
summer_temp_manual_mod
int weather_generator::summer_temp_manual_mod = 0
Definition at line 41 of file weather_gen.h.
Referenced by weather_temperature_from_common_data().
weather_black_list
std::vector<std::string> weather_generator::weather_black_list
Definition at line 52 of file weather_gen.h.
Referenced by sort_weather().
weather_white_list
std::vector<std::string> weather_generator::weather_white_list
Definition at line 53 of file weather_gen.h.
Referenced by sort_weather().
winter_humidity_manual_mod
int weather_generator::winter_humidity_manual_mod = 0
Definition at line 48 of file weather_gen.h.
Referenced by get_weather().
winter_temp_manual_mod
int weather_generator::winter_temp_manual_mod = 0
Definition at line 44 of file weather_gen.h.
Referenced by weather_temperature_from_common_data().
The documentation for this class was generated from the following files:
src/weather_gen.h
src/weather_gen.cpp