Cataclysm DDA: widget Class Reference
widget Class Reference
#include <widget.h>
Public Member Functions
widget ()=default
widget (const widget_id &id)
void load (const JsonObject &jo, std::string_view src)
const widget_id & getId () const
std::string layout (const avatar &ava, unsigned int max_width=0, int label_width=0, bool skip_pad=false)
std::string show (const avatar &ava, unsigned int max_width)
window_panel get_window_panel (int width, int req_height=1)
std::string color_text_function_string (const avatar &ava, unsigned int max_width)
bool uses_text_function () const
int get_var_value (const avatar &ava) const
bool has_flag (const flag_id &flag) const
bool has_flag (const std::string &flag) const
const bodypart_id & only_bp () const
void set_default_var_range (const avatar &ava)
std::string color_value_string (int value, int width_max=0)
std::string value_string (int value, int width_max=0)
nc_color value_color (int value)
std::string number (int value, bool from_condition) const
std::string number_cond (enumeration_conjunction join_type=enumeration_conjunction::none) const
std::string text (bool from_condition, int width=0)
std::string text_cond (bool no_join=false, int width=0)
std::string sym (bool from_condition)
std::string sym_cond (bool no_join=true, enumeration_conjunction join_type=enumeration_conjunction::none) const
std::string sym_text (bool from_condition, int width=0)
std::string sym_text_cond (bool no_join=true, int width=0)
std::vector< string_id< widget > > widgets (bool from_condition)
std::vector< string_id< widget > > widgets_cond ()
std::string graph (int value) const
Static Public Member Functions
static void load_widget (const JsonObject &jo, const std::string &src)
static void finalize ()
static int finalize_label_width_recursive (const widget_id &id)
static void finalize_inherited_fields_recursive (const widget_id &id, const std::string &label_separator, int col_padding)
static void reset ()
static const std::vector< widget > & get_all ()
static int custom_draw_multiline (const std::string &widget_string, const catacurses::window &w, int margin, int width, int row_num)
Public Attributes
std::string _style
translation _label
std::string _description
int _label_width = 0
std::string _separator
int _padding
widget_var _var = widget_var::last
int _var_min = INT_MIN
int _var_max = INT_MAX
bool explicit_separator
bool explicit_padding
bool _pad_labels
std::pair< int, int > _var_norm = std::make_pair(INT_MIN, INT_MAX)
std::set< bodypart_id > _bps
int _width = 0
int _height = 0
int _height_max = 0
std::string _symbols
std::string _fill
translation _string
std::vector< nc_color > _colors
std::vector< int > _breaks
std::vector< widget_id > _widgets
std::string _arrange
std::string _body_graph
cardinal_direction _direction
std::set< flag_id > _flags
std::vector< widget_clause > _clauses
widget_clause _default_clause
widget_alignment _text_align
widget_alignment _label_align
Private Member Functions
const widget_clause * get_clause (const std::string &clause_id="") const
std::vector< const widget_clause * > get_clauses () const
Private Attributes
widget_id id
std::vector< std::pair< widget_id, mod_id > > src
bool was_loaded = false
Friends
class generic_factory< widget >
struct mod_tracker
Detailed Description
Definition at line 210 of file widget.h.
Constructor & Destructor Documentation
widget() [1/2]
widget::widget () default
widget() [2/2]
widget::widget (const widget_id & id) inline explicit
Definition at line 224 of file widget.h.
 : id( id ) {}
Member Function Documentation
color_text_function_string()
std::string widget::color_text_function_string (const avatar & ava, unsigned int max_width)
Definition at line 1088 of file widget.cpp.
 {
     std::string ret;
     // Most text variables have both a string and a color.
     // The string and color in `desc` will be converted to colorized text with markup.
     std::pair<std::string, nc_color> desc;
     // Set a default color
     desc.second = c_light_gray;
     // By default, colorize the string in desc.first with the color in desc.second.
     bool apply_color = true;
     // Don't bother updating the widget's height by default
     bool update_height = false;
     // Some helper display:: functions do their own internal colorization of the string.
     // For those, desc.first is the already-colorized string, and apply_color is set to false.
     switch( _var ) {
         case widget_var::activity_text:
             desc = display::activity_text_color( ava );
             break;
         case widget_var::body_graph:
             desc.first = display::colorized_bodygraph_text( ava, _body_graph,
                          bodygraph_var::hp, _width == 0 ? max_width : _width, _height_max, _height );
             update_height = true; // Dynamically adjusted height
             apply_color = false; // Already colorized
             break;
         case widget_var::body_graph_temp:
             desc.first = display::colorized_bodygraph_text( ava, _body_graph,
                          bodygraph_var::temp, _width == 0 ? max_width : _width, _height_max, _height );
             update_height = true; // Dynamically adjusted height
             apply_color = false; // Already colorized
             break;
         case widget_var::body_graph_encumb:
             desc.first = display::colorized_bodygraph_text( ava, _body_graph,
                          bodygraph_var::encumb, _width == 0 ? max_width : _width, _height_max, _height );
             update_height = true; // Dynamically adjusted height
             apply_color = false; // Already colorized
             break;
         case widget_var::body_graph_status:
             desc.first = display::colorized_bodygraph_text( ava, _body_graph,
                          bodygraph_var::status, _width == 0 ? max_width : _width, _height_max, _height );
             update_height = true; // Dynamically adjusted height
             apply_color = false; // Already colorized
             break;
         case widget_var::body_graph_wet:
             desc.first = display::colorized_bodygraph_text( ava, _body_graph,
                          bodygraph_var::wet, _width == 0 ? max_width : _width, _height_max, _height );
             update_height = true; // Dynamically adjusted height
             apply_color = false; // Already colorized
             break;
         case widget_var::bp_armor_outer_text:
             desc.first = ava.worn.get_armor_display( only_bp() );
             apply_color = false; // Item name already colorized by tname
             break;
         case widget_var::carry_weight_text:
             desc = display::carry_weight_text_color( ava );
             break;
         case widget_var::date_text:
             desc.first = display::date_string();
             break;
         case widget_var::env_temp_text:
             desc.first = display::get_temp( ava );
             break;
         case widget_var::mood_text:
             desc = display::morale_face_color( ava );
             break;
         case widget_var::move_count_mode_text:
             desc = display::move_count_and_mode_text_color( ava );
             break;
         case widget_var::pain_text:
             desc = display::pain_text_color( ava );
             break;
         case widget_var::overmap_loc_text:
             desc.first = display::overmap_position_text( ava.global_omt_location() );
             break;
         case widget_var::overmap_text:
             desc.first = display::colorized_overmap_text( ava, _width == 0 ? max_width : _width, _height );
             apply_color = false;
             break;
         case widget_var::place_text:
             desc.first = display::current_position_text( ava.global_omt_location() );
             break;
         case widget_var::power_text:
             desc = display::power_text_color( ava );
             break;
         case widget_var::power_balance_text:
             desc = display::power_balance_text_color( ava );
             break;
         case widget_var::safe_mode_text:
             desc = display::safe_mode_text_color( false );
             break;
         case widget_var::safe_mode_classic_text:
             desc = display::safe_mode_text_color( true );
             break;
         case widget_var::style_text:
             desc.first = ava.martial_arts_data->selected_style_name( ava );
             break;
         case widget_var::sundial_text:
             desc.first = display::sundial_text_color( ava, _width == 0 ? max_width : _width );
             apply_color = false; // Already colorized
             break;
         case widget_var::sundial_time_text:
             desc.first = display::sundial_time_text_color( ava, _width == 0 ? max_width : _width );
             apply_color = false; // Already colorized
             break;
         case widget_var::time_text:
             desc.first = display::time_string( ava );
             break;
         case widget_var::veh_azimuth_text:
             desc.first = display::vehicle_azimuth_text( ava );
             break;
         case widget_var::veh_cruise_text:
             desc = display::vehicle_cruise_text_color( ava );
             break;
         case widget_var::veh_fuel_text:
             desc = display::vehicle_fuel_percent_text_color( ava );
             break;
         case widget_var::weariness_text:
             desc = display::weariness_text_color( ava );
             break;
         case widget_var::weary_malus_text:
             desc = display::weary_malus_text_color( ava );
             break;
         case widget_var::weather_text:
             desc = display::weather_text_color( ava );
             break;
         case widget_var::wielding_text:
             desc.first = ava.weapname();
             break;
         case widget_var::wielding_simple_text:
             desc.first = ava.weapname_simple();
             break;
         case widget_var::wielding_mode_text:
             desc.first = ava.weapname_mode();
             break;
         case widget_var::wielding_ammo_text:
             desc.first = ava.weapname_ammo();
             break;
         case widget_var::wind_text:
             desc = display::wind_text_color( ava );
             break;
         case widget_var::compass_text:
             desc.first = display::colorized_compass_text( _direction, _width );
             apply_color = false; // Already colorized
             break;
         case widget_var::compass_legend_text:
             desc.first = display::colorized_compass_legend_text( _width == 0 ? max_width : _width, _height_max,
                          _height );
             update_height = true; // Dynamically adjusted height
             apply_color = false; // Already colorized
             break;
         default:
             debugmsg( "Unexpected widget_var %s - no text_color function defined",
                       io::enum_to_string<widget_var>( _var ) );
             return _( "???" );
     }
     // Update height dynamically for widgets that support it
     if( update_height && has_flag( json_flag_W_DYNAMIC_HEIGHT ) ) {
         set_height_for_widget( id, _height ); // Set within widget factory
     } else {
         _height = _height_max; // reset height
     }
     // Colorize if applicable
     if( !_colors.empty() ) {
         ret += colorize( desc.first, _colors.front() );
     } else if( apply_color ) {
         ret += colorize( desc.first, desc.second );
     } else {
         ret += desc.first;
     }
     return ret;
 }
References _, _body_graph, _colors, _direction, _height, _height_max, _var, _width, activity_text, display::activity_text_color(), body_graph, body_graph_encumb, body_graph_status, body_graph_temp, body_graph_wet, bp_armor_outer_text, c_light_gray, carry_weight_text, display::carry_weight_text_color(), colorize(), display::colorized_bodygraph_text(), display::colorized_compass_legend_text(), display::colorized_compass_text(), display::colorized_overmap_text(), compass_legend_text, compass_text, display::current_position_text(), display::date_string(), date_text, debugmsg, encumb, io::enum_to_string< widget_var >(), env_temp_text, outfit::get_armor_display(), display::get_temp(), Creature::global_omt_location(), has_flag(), hp, json_flag_W_DYNAMIC_HEIGHT, Character::martial_arts_data, mood_text, display::morale_face_color(), display::move_count_and_mode_text_color(), move_count_mode_text, only_bp(), overmap_loc_text, display::overmap_position_text(), overmap_text, pain_text, display::pain_text_color(), place_text, power_balance_text, display::power_balance_text_color(), power_text, display::power_text_color(), cata::hash64_detail::ret, safe_mode_classic_text, safe_mode_text, display::safe_mode_text_color(), set_height_for_widget(), status, style_text, sundial_text, display::sundial_text_color(), sundial_time_text, display::sundial_time_text_color(), temp, display::time_string(), time_text, veh_azimuth_text, veh_cruise_text, veh_fuel_text, display::vehicle_azimuth_text(), display::vehicle_cruise_text_color(), display::vehicle_fuel_percent_text_color(), Character::weapname(), Character::weapname_ammo(), Character::weapname_mode(), Character::weapname_simple(), weariness_text, display::weariness_text_color(), weary_malus_text, display::weary_malus_text_color(), weather_text, display::weather_text_color(), wet, wielding_ammo_text, wielding_mode_text, wielding_simple_text, wielding_text, wind_text, display::wind_text_color(), and Character::worn.
Referenced by show().
color_value_string()
std::string widget::color_value_string (int value, int width_max = 0)
Definition at line 1259 of file widget.cpp.
 {
     std::string val_string = value_string( value, width_max );
     const nc_color cur_color = value_color( value );
     if( cur_color == c_unset ) {
         return val_string;
     } else {
         return colorize( val_string, cur_color );
     }
 }
References c_unset, colorize(), value_color(), and value_string().
Referenced by show().
custom_draw_multiline()
int widget::custom_draw_multiline (const std::string & widget_string, const catacurses::window & w, int margin, int width, int row_num) static
Definition at line 895 of file widget.cpp.
 {
     std::string wgt_str = widget_string;
     size_t strpos = 0;
     // Split the widget string into lines (for height > 1)
     while( ( strpos = wgt_str.find( '\n' ) ) != std::string::npos ) {
         trim_and_print( w, point( margin, row_num ), width, c_light_gray, wgt_str.substr( 0, strpos ) );
         wgt_str.erase( 0, strpos + 1 );
         row_num++;
     }
     // Last line (or first line for single-line widgets)
     trim_and_print( w, point( margin, row_num ), width, c_light_gray, wgt_str );
     row_num++;
     return row_num;
 }
References c_light_gray, point, and trim_and_print().
Referenced by custom_draw_func().
finalize()
void widget::finalize () static
Definition at line 556 of file widget.cpp.
 {
     widget_factory.finalize();
     for( const widget &wgt : widget::get_all() ) {
         if( wgt._style == "sidebar" ) {
             widget::finalize_inherited_fields_recursive( wgt.getId(), wgt._separator, wgt._padding );
             widget::finalize_label_width_recursive( wgt.getId() );
         }
     }
 }
References finalize_inherited_fields_recursive(), finalize_label_width_recursive(), get_all(), and anonymous_namespace{widget.cpp}::widget_factory.
Referenced by DynamicDataLoader::finalize_loaded_data().
finalize_inherited_fields_recursive()
void widget::finalize_inherited_fields_recursive (const widget_id & id, const std::string & label_separator, int col_padding) static
Definition at line 518 of file widget.cpp.
 {
     widget *w = nullptr;
     // Get the original widget from the widget factory.
     for( const widget &wgt : widget::get_all() ) {
         if( wgt.getId() == id ) {
             w = const_cast<widget *>( &wgt );
             break;
         }
     }
     if( w == nullptr ) {
         return;
     }
     if( !w->explicit_separator ) {
         w->_separator = label_separator;
     }
     if( !w->explicit_padding ) {
         w->_padding = col_padding;
     }
     // If we get here, we have a layout that contains nested widgets.
     for( const widget_id &wid : w->_widgets ) {
         widget::finalize_inherited_fields_recursive( wid,
                 w->explicit_separator ? w->_separator : label_separator,
                 w->explicit_padding ? w->_padding : col_padding );
     }
     // Also do it for widgets used in clauses
     for( const widget_clause &clause : w->_clauses ) {
         for( const widget_id &wid : clause.widgets ) {
             widget::finalize_inherited_fields_recursive( wid,
                     w->explicit_separator ? w->_separator : label_separator,
                     w->explicit_padding ? w->_padding : col_padding );
         }
     }
 }
References _clauses, _padding, _separator, _widgets, explicit_padding, explicit_separator, get_all(), and widget_clause::widgets.
Referenced by finalize(), panel_manager::init(), and panel_manager::show_adm().
finalize_label_width_recursive()
int widget::finalize_label_width_recursive (const widget_id & id) static
Definition at line 478 of file widget.cpp.
 {
     widget *w = nullptr;
     // Get the original widget from the widget factory.
     for( const widget &wgt : widget::get_all() ) {
         if( wgt.getId() == id ) {
             w = const_cast<widget *>( &wgt );
             break;
         }
     }
     // None found, return 0 as the label width.
     if( w == nullptr ) {
         return 0;
     } else if( w->_widgets.empty() ) {
         // No more nested layouts, we've found an individual widget.
         // Return the widget's label width, or 0 if the label or pad_labels is disabled.
         return w->_label.empty() || w->has_flag( json_flag_W_LABEL_NONE ) ||
                ! w->_pad_labels ? 0 : w->_label_width;
     }
     // If we get here, we have a layout that contains nested widgets.
     // Find the longest label width within this layout.
     int width = 0;
     for( const widget_id &wid : w->_widgets ) {
         // Dive deeper to retrieve the nested element's label width.
         int tmpw = widget::finalize_label_width_recursive( wid );
         if( tmpw > width ) {
             width = tmpw;
         }
     }
     if( w->_pad_labels ) {
         // Update this layout's label width to reflect the longest label within.
         w->_label_width = width;
     } else {
         w->_label_width = 0;
     }
     return w->_label_width;
 }
References _label, _label_width, _pad_labels, _widgets, translation::empty(), get_all(), has_flag(), and json_flag_W_LABEL_NONE.
Referenced by finalize().
get_all()
const std::vector< widget > & widget::get_all () static
Definition at line 50 of file widget.cpp.
 {
     return widget_factory.get_all();
 }
References anonymous_namespace{widget.cpp}::widget_factory.
Referenced by draw_center_win(), finalize(), finalize_inherited_fields_recursive(), finalize_label_width_recursive(), panel_manager::get_sidebar(), initialize_default_panel_layouts(), and set_height_for_widget().
get_clause()
const widget_clause * widget::get_clause (const std::string & clause_id = "") const private
Definition at line 1499 of file widget.cpp.
 {
     // Look for a clause with satisfied conditions
     for( const widget_clause &wp : _clauses ) {
         // If an id is given, only check conditions for that id
         if( !clause_id.empty() && clause_id != wp.id ) {
             continue;
         }
         // Return this clause if it has no condition or the condition is true
         if( !wp.has_condition || wp.meets_condition( only_bp().id().str() ) ) {
             return &wp;
         }
     }
     return nullptr;
 }
References _clauses, and only_bp().
get_clauses()
std::vector< const widget_clause * > widget::get_clauses () const private
Definition at line 1515 of file widget.cpp.
 {
     std::vector<const widget_clause *> ret;
     // Look for clauses with satisfied conditions
     for( const widget_clause &wp : _clauses ) {
         // Include this clause if it has no condition or the condition is true
         if( !wp.has_condition || wp.meets_condition( _bps ) ) {
             ret.emplace_back( &wp );
         }
     }
     return ret;
 }
References _bps, _clauses, and cata::hash64_detail::ret.
Referenced by number_cond(), sym_cond(), sym_text_cond(), text_cond(), and widgets_cond().
get_var_value()
int widget::get_var_value (const avatar & ava) const
Definition at line 739 of file widget.cpp.
 {
     // Numeric value to be rendered in the widget
     int value = 0;
     // Each "var" value refers to some attribute, typically of the avatar, that yields a numeric
     // value, and can be displayed as a numeric field, a graph, or a series of text clauses.
     switch( _var ) {
         // Vars with a known max val
         case widget_var::stamina:
             value = ava.get_stamina();
             break;
         case widget_var::mana:
             value = ava.magic->available_mana();
             break;
         case widget_var::max_mana:
             value = ava.magic->max_mana( ava );
             break;
         case widget_var::power_percentage:
             value = ava.has_max_power() ? ( 100 * ava.get_power_level().value() ) /
                     ava.get_max_power_level().value() : 0;
             break;
         case widget_var::log_power_balance: {
             int value_abs = std::abs( ava.power_balance.value() );
             if( value_abs < 500 ) {
                 value = 0;
             } else {
                 int sign = ava.power_balance.value() > 0 ? 1 : -1;
                 value = ( sign * 100.0 * std::log10( value_abs / 500.0 ) );
             }
             value += 600;
             break;
         }
         case widget_var::morale_level:
             value = ava.get_morale_level();
             break;
         case widget_var::bp_hp:
             // HP for body part
             if( ava.has_part( only_bp(), body_part_filter::equivalent ) ) {
                 value = ava.get_part_hp_cur( only_bp() );
             } else {
                 value = 0;
             }
             break;
         case widget_var::bp_warmth:
             // Body part warmth/temperature
             if( ava.has_part( only_bp(), body_part_filter::equivalent ) ) {
                 value = units::to_legacy_bodypart_temp( ava.get_part_temp_cur( only_bp() ) );
             } else {
                 value = 0;
             }
             break;
         case widget_var::bp_wetness:
             // Body part wetness
             if( ava.has_part( only_bp(), body_part_filter::equivalent ) ) {
                 value = ava.get_part_wetness( only_bp() );
             } else {
                 value = 0;
             }
             break;
         case widget_var::focus:
             value = ava.get_focus();
             break;
         case widget_var::speed:
             value = ava.get_speed();
             break;
         case widget_var::move:
             value = ava.movecounter;
             break;
         case widget_var::move_remainder:
             value = ava.get_moves();
             break;
         case widget_var::move_cost:
             value = ava.run_cost( 100 );
             break;
         case widget_var::pain:
             value = ava.get_perceived_pain();
             break;
         case widget_var::sleepiness:
             value = ava.get_sleepiness();
             break;
         case widget_var::health:
             value = ava.get_lifestyle();
             break;
         case widget_var::weariness_level:
             value = ava.weariness_level();
             break;
         case widget_var::weary_transition_level:
             value = ava.weariness_transition_level();
             break;
         case widget_var::stat_str:
             value = ava.get_str();
             break;
         case widget_var::stat_dex:
             value = ava.get_dex();
             break;
         case widget_var::stat_int:
             value = ava.get_int();
             break;
         case widget_var::stat_per:
             value = ava.get_per();
             break;
         case widget_var::sound:
             value = ava.volume;
             break;
         case widget_var::bp_encumb:
             // Encumbrance for body part
             value = ava.get_part_encumbrance_data( only_bp() ).encumbrance;
             break;
         case widget_var::cardio_fit:
             value = ava.get_cardiofit();
             break;
         case widget_var::cardio_acc:
             value = ava.get_cardio_acc();
             break;
         case widget_var::carry_weight:
             value = ( 100 * ava.weight_carried() ) / ava.weight_capacity();
             break;
         // TODO
         case widget_var::mood:
         // see morale_emotion
         default:
             value = 0;
     }
     return value;
 }
References _var, abs(), bp_encumb, bp_hp, bp_warmth, bp_wetness, cardio_acc, cardio_fit, carry_weight, encumbrance_data::encumbrance, equivalent, focus, Character::get_cardio_acc(), Character::get_cardiofit(), Character::get_dex(), Character::get_focus(), Character::get_int(), Character::get_lifestyle(), Character::get_max_power_level(), Character::get_morale_level(), Creature::get_moves(), Creature::get_part_encumbrance_data(), Creature::get_part_hp_cur(), Creature::get_part_temp_cur(), Creature::get_part_wetness(), Character::get_per(), Character::get_perceived_pain(), Character::get_power_level(), Character::get_sleepiness(), Character::get_speed(), Character::get_stamina(), Character::get_str(), Character::has_max_power(), Creature::has_part(), health, log_power_balance, Character::magic, mana, max_mana, mood, morale_level, move, move_cost, move_remainder, avatar::movecounter, only_bp(), pain, avatar::power_balance, power_percentage, Character::run_cost(), iexamine::sign(), sleepiness, sound, speed, stamina, stat_dex, stat_int, stat_per, stat_str, units::to_legacy_bodypart_temp(), units::quantity< V, U >::value(), Character::volume, Character::weariness_level(), weariness_level, Character::weariness_transition_level(), weary_transition_level, Character::weight_capacity(), and Character::weight_carried().
Referenced by show().
get_window_panel()
window_panel widget::get_window_panel (int width, int req_height = 1)
Definition at line 995 of file widget.cpp.
 {
     // Width is fixed, but height may vary depending on child widgets
     int height = req_height;
     // For layout with rows, height will be the combined
     // height of all child widgets.
     if( _style == "layout" && _arrange == "rows" ) {
         height = 0;
         for( const widget_id &wid : _widgets ) {
             height += wid->_height > 0 ? wid->_height : 1;
         }
         for( const widget_clause &clause : _clauses ) {
             int clause_height = 0;
             for( const widget_id &wid : clause.widgets ) {
                 clause_height += wid->_height > 0 ? wid->_height : 1;
             }
             if( clause_height > height ) {
                 height = clause_height;
             }
         }
     } else if( _style == "widget" || _style == "text" ) {
         height = _height > 1 ? _height : req_height;
     }
     // Minimap and log do not have a predetermined height
     // (or they should allow caller to customize height)
     window_panel win( _label.translated(), _label, height, width,
                       !has_flag( json_flag_W_DISABLED_BY_DEFAULT ) );
     win.set_widget( this->id );
     win.set_draw_func( custom_draw_func );
     return win;
 }
References _arrange, _clauses, _height, _label, _style, _widgets, custom_draw_func(), has_flag(), json_flag_W_DISABLED_BY_DEFAULT, window_panel::set_draw_func(), window_panel::set_widget(), and translation::translated().
Referenced by initialize_default_custom_panels().
getId()
const widget_id & widget::getId () const
Definition at line 55 of file widget.cpp.
 {
     return id;
 }
References id.
graph()
std::string widget::graph (int value) const
Definition at line 1528 of file widget.cpp.
 {
     // graph "depth is equal to the number of nonzero symbols
     int depth = utf8_width( _symbols ) - 1;
     // Number of graph characters
     const int w = _arrange == "rows" ? _height : _width;
     // Max integer value this graph can show
     int max_graph_val = w * depth;
     // Scale value range to current graph resolution (width x depth)
     if( _var_max > 0 && _var_max != max_graph_val ) {
         // Scale max source value to max graph value
         value = max_graph_val * value / _var_max;
     }
     // Negative values are not (yet) supported
     if( value < 0 ) {
         value = 0;
     }
     // Truncate to maximum value displayable by graph
     if( value > max_graph_val ) {
         value = max_graph_val;
     }
     int quot;
     int rem;
     const std::wstring syms = utf8_to_wstr( _symbols );
     std::wstring ret;
     if( _fill == "bucket" ) {
         quot = value / depth; // number of full cells/buckets
         rem = value % depth;  // partly full next cell, maybe
         // Full cells at the front
         ret += std::wstring( quot, syms.back() );
         // Any partly-full cells?
         if( w > quot ) {
             // Current partly-full cell
             ret += syms[rem];
             // Any more zero cells at the end
             if( w > quot + 1 ) {
                 ret += std::wstring( w - quot - 1, syms[0] );
             }
         }
     } else if( _fill == "pool" ) {
         quot = value / w; // baseline depth of the pool
         rem = value % w;  // number of cells at next depth
         // Most-filled cells come first
         if( rem > 0 ) {
             ret += std::wstring( rem, syms[quot + 1] );
             // Less-filled cells may follow
             if( w > rem ) {
                 ret += std::wstring( w - rem, syms[quot] );
             }
         } else {
             // All cells at the same level
             ret += std::wstring( w, syms[quot] );
         }
     } else {
         debugmsg( "Unknown widget fill type %s", _fill );
         return "";
     }
     // Re-arrange characters to a vertical bar graph
     if( _arrange == "rows" ) {
         std::wstring temp = ret;
         ret.clear();
         for( int i = temp.size() - 1; i >= 0; i-- ) {
             ret += temp[i];
             if( i > 0 ) {
                 ret += '\n';
             }
         }
     }
     return wstr_to_utf8( ret );
 }
References _arrange, _fill, _height, _symbols, _var_max, _width, debugmsg, cata::hash64_detail::ret, temp, utf8_to_wstr(), utf8_width(), and wstr_to_utf8().
Referenced by value_string().
has_flag() [1/2]
bool widget::has_flag (const flag_id & flag) const
Definition at line 867 of file widget.cpp.
 {
     return _flags.count( flag ) != 0;
 }
References _flags.
Referenced by color_text_function_string(), custom_draw_func(), dummy_wgt_render(), finalize_label_width_recursive(), get_window_panel(), has_flag(), layout(), load(), sym_text_cond(), and text_cond().
has_flag() [2/2]
bool widget::has_flag (const std::string & flag) const
Definition at line 872 of file widget.cpp.
 {
     return has_flag( flag_id( flag ) );
 }
References flag_id, and has_flag().
layout()
std::string widget::layout (const avatar & ava, unsigned int max_width = 0, int label_width = 0, bool skip_pad = false)
Definition at line 1710 of file widget.cpp.
 {
     std::string ret;
     if( _style == "layout" ) {
         std::vector<string_id<widget>> wgts = widgets( !_clauses.empty() );
         int layout_label_width = ( label_width == 0 || ! _pad_labels ) ? _label_width : label_width;
         if( _arrange == "rows" ) {
             std::string sep;
             int h = 0;
             // Stack rows vertically into a multiline widget
             for( const widget_id &wid : wgts ) {
                 widget cur_child = wid.obj();
                 ret += sep + cur_child.layout( ava, max_width, layout_label_width,
                                                skip_pad || wid->has_flag( json_flag_W_NO_PADDING ) );
                 sep = "\n";
                 h += wid->_height < 0 ? 0 : wid->_height;
             }
             // Set height for the final layout
             set_height_for_widget( id, h );
         } else { // columns
             const int num_widgets = wgts.size();
             if( num_widgets == 0 ) {
                 debugmsg( "widget layout has no widgets" );
             }
             // Number of spaces between columns
             const int col_padding = _padding;
             // Subtract column padding to get space available for widgets
             const int avail_width = max_width - col_padding * ( num_widgets - 1 );
             // Divide available width equally among all widgets
             const int child_width = avail_width / num_widgets;
             // Total widget width w/o padding
             const int total_widget_width = std::accumulate( wgts.begin(), wgts.end(), 0,
             [child_width]( int sum, const widget_id & wid ) {
                 widget cur_child = wid.obj();
                 return sum + ( cur_child._style == "layout" &&
                                cur_child._width > 0 ? cur_child._width : child_width );
             } );
             // Total widget width with padding
             const int total_widget_padded_width = total_widget_width + col_padding * ( num_widgets - 1 );
             // Keep remainder to distribute
             int remainder = max_width - total_widget_padded_width;
             // Store the (potentially) multi-row text for each column
             std::vector<std::vector<std::string>> cols;
             std::vector<int> widths;
             unsigned int total_width = 0;
             std::string debug_widths;
             for( size_t i = 0; i < wgts.size(); i++ ) {
                 const widget_id &wid = wgts[i];
                 widget cur_child = wid.obj();
                 int cur_width = child_width;
                 // determine spacing based on type of column
                 if( _arrange == "minimum_columns" ) {
                     if( cur_child._width > 0 ) {
                         cur_width = cur_child._width;
                     }
                     // if last widget make it take the remaining space
                     if( i == wgts.size() - 1 ) {
                         cur_width = std::max<int>( 0, avail_width - total_width );
                     }
                 } else { //columns
                     if( cur_child._style == "layout" && cur_child._width > 0 ) {
                         cur_width = cur_child._width;
                     }
                     // Spread remainder over the first few columns
                     if( remainder > 0 ) {
                         cur_width += 1;
                         remainder -= 1;
                     }
                 }
                 // for debug keep track of each and width
                 debug_widths.append( string_format( "%s: %d,", wid.str(), cur_width ) );
                 if( cur_width > 0 ) {
                     total_width += cur_width;
                 }
                 if( total_width > max_width ) {
                     debugmsg( string_format( "widget layout is wider (%d) than sidebar allows (%d) for %s.",
                                              total_width, max_width, debug_widths ) );
                 }
                 const bool skip_pad_this = skip_pad || wid->has_flag( json_flag_W_NO_PADDING );
                 // Layout child in this column
                 const std::string txt = cur_child.layout( ava, skip_pad_this ? 0 : cur_width,
                                         layout_label_width, skip_pad_this );
                 // Store the resulting text for this column
                 cols.emplace_back( string_split( txt, '\n' ) );
                 widths.emplace_back( cur_width );
             }
             int h_max = 0;
             std::string sep;
             // Line up each row of each column to form the whole multi-line layout
             for( size_t r = 0; ; r++ ) {
                 bool any_val = false;
                 std::string line;
                 for( size_t c = 0; c < cols.size(); c++ ) {
                     if( r >= cols[c].size() ) {
                         if( !skip_pad ) {
                             // No row r for this column, pad with empty space
                             line += std::string( widths[c], ' ' );
                         }
                     } else {
                         any_val = true;
                         line += cols[c][r];
                     }
                     if( !skip_pad && c + 1 < cols.size() ) {
                         // Add padding between columns
                         line += std::string( col_padding, ' ' );
                     }
                 }
                 if( !any_val ) {
                     break;
                 }
                 ret += sep + line;
                 sep = "\n";
                 h_max++;
             }
             // Set height for the final layout
             set_height_for_widget( id, h_max );
         }
     } else {
         // Get displayed value (colorized)
         std::string shown = show( ava, max_width );
         // If nothing was printed, the widget never had a chance to adjust the height. Adjust it here.
         if( shown.empty() && has_flag( json_flag_W_DYNAMIC_HEIGHT ) ) {
             _height = 0;
         }
         // Let the calling func know that this widget should be skipped for rendering
         if( has_flag( json_flag_W_DISABLED_WHEN_EMPTY ) &&
             string_empty_or_whitespace( remove_color_tags( shown ) ) ) {
             return "";
         }
         size_t strpos = 0;
         int row_num = 0;
         // For multi-line widgets, each line is separated by a '\n' character
         while( ( strpos = shown.find( '\n' ) ) != std::string::npos && row_num < _height ) {
             // Process line, including '\n'
             ret += append_line( shown.substr( 0, strpos + 1 ), row_num == 0, max_width,
                                 has_flag( json_flag_W_LABEL_NONE ) ? translation() : _label,
                                 0, _separator, _text_align, _label_align, skip_pad );
             // Delete used token
             shown.erase( 0, strpos + 1 );
             row_num++;
         }
         if( row_num < _height ) {
             // Process last line, or first for single-line widgets
             ret += append_line( shown, row_num == 0, max_width,
                                 has_flag( json_flag_W_LABEL_NONE ) ? translation() : _label,
                                 row_num == 0 && _pad_labels ? label_width : 0, _separator, _text_align, _label_align, skip_pad );
         }
         if( !ret.empty() && ret.back() == '\n' ) {
             ret.pop_back();
         }
     }
     return ret.find( '\n' ) != std::string::npos || max_width == 0 ?
            ret : trim_by_length( ret, max_width );
 }
References _arrange, _clauses, _height, _label, _label_align, _label_width, _pad_labels, _padding, _separator, _style, _text_align, _width, append_line(), c, debugmsg, has_flag(), Character::has_flag(), json_flag_W_DISABLED_WHEN_EMPTY, json_flag_W_DYNAMIC_HEIGHT, json_flag_W_LABEL_NONE, json_flag_W_NO_PADDING, layout(), line, string_id< T >::obj(), remove_color_tags(), cata::hash64_detail::ret, set_height_for_widget(), show(), om_direction::size, string_id< T >::str(), string_empty_or_whitespace(), string_format(), string_split(), trim_by_length(), and widgets().
Referenced by custom_draw_func(), dummy_wgt_render(), and layout().
load()
void widget::load (const JsonObject & jo, std::string_view src)
Definition at line 388 of file widget.cpp.
 {
     optional( jo, was_loaded, "width", _width, 0 );
     optional( jo, was_loaded, "height", _height_max, 1 );
     optional( jo, was_loaded, "symbols", _symbols, "-" );
     optional( jo, was_loaded, "fill", _fill, "bucket" );
     optional( jo, was_loaded, "label", _label, translation() );
     optional( jo, was_loaded, "description", _description, "" );
     optional( jo, was_loaded, "style", _style, "number" );
     optional( jo, was_loaded, "arrange", _arrange, "columns" );
     optional( jo, was_loaded, "body_graph", _body_graph, "full_body_widget" );
     optional( jo, was_loaded, "direction", _direction, cardinal_direction::num_cardinal_directions );
     optional( jo, was_loaded, "text_align", _text_align, widget_alignment::LEFT );
     optional( jo, was_loaded, "label_align", _label_align, widget_alignment::LEFT );
     // Row layouts and non-layout widgets default to true
     optional( jo, was_loaded, "pad_labels", _pad_labels, _style != "layout" || _arrange == "rows" );
     optional( jo, was_loaded, "flags", _flags );
     if( _style == "sidebar" ) {
         mandatory( jo, was_loaded, "separator", _separator );
         mandatory( jo, was_loaded, "padding", _padding );
         explicit_separator = true;
         explicit_padding = true;
     } else {
         explicit_separator = jo.has_string( "separator" );
         explicit_padding = jo.has_number( "padding" );
         optional( jo, was_loaded, "separator", _separator, default_separator );
         optional( jo, was_loaded, "padding", _padding, 2 );
     }
     _height = _height_max;
     _label_width = _label.empty() ||
                    has_flag( json_flag_W_LABEL_NONE ) ? 0 : utf8_width( _label.translated() );
     if( jo.has_string( "var" ) ) {
         _var = io::string_to_enum<widget_var>( jo.get_string( "var" ) );
     }
     if( jo.has_string( "bodypart" ) ) {
         _bps.clear();
         _bps.emplace( jo.get_string( "bodypart" ) );
     }
     if( jo.has_array( "bodyparts" ) ) {
         _bps.clear();
         for( const JsonValue val : jo.get_array( "bodyparts" ) ) {
             if( !val.test_string() ) {
                 jo.throw_error_at( "bodyparts", "Invalid string value in bodyparts array" );
                 continue;
             }
             _bps.emplace( val.get_string() );
         }
     }
     if( jo.has_array( "colors" ) ) {
         _colors.clear();
         _breaks.clear();
         for( const std::string color_name : jo.get_array( "colors" ) ) {
             _colors.emplace_back( get_all_colors().name_to_color( color_name ) );
         }
         if( jo.has_array( "breaks" ) ) {
             for( const int value : jo.get_array( "breaks" ) ) {
                 _breaks.emplace_back( value );
             }
             if( _breaks.size() != _colors.size() - 1 ) {
                 debugmsg( "Widget property 'breaks' must have one element less than 'colors'" );
             }
         }
     }
     if( jo.has_array( "clauses" ) ) {
         _clauses.clear();
         for( JsonObject jobj : jo.get_array( "clauses" ) ) {
             widget_clause phs;
             phs.load( jobj );
             _clauses.emplace_back( phs );
         }
     }
     if( jo.has_object( "default_clause" ) ) {
         _default_clause.load( jo.get_object( "default_clause" ) );
     }
     if( _style == "text" && _clauses.empty() && _var == widget_var::last ) {
         mandatory( jo, was_loaded, "string", _string );
     } else {
         optional( jo, was_loaded, "string", _string );
     }
     optional( jo, was_loaded, "widgets", _widgets, string_id_reader<::widget> {} );
 }
References _arrange, _body_graph, _bps, _breaks, _clauses, _colors, _default_clause, _description, _direction, _fill, _flags, _height, _height_max, _label, _label_align, _label_width, _pad_labels, _padding, _separator, _string, _style, _symbols, _text_align, _var, _widgets, _width, debugmsg, default_separator, translation::empty(), explicit_padding, explicit_separator, get_all_colors(), JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), has_flag(), JsonObject::has_number(), JsonObject::has_object(), JsonObject::has_string(), json_flag_W_LABEL_NONE, last, LEFT, widget_clause::load(), mandatory, num_cardinal_directions, optional(), JsonObject::throw_error_at(), translation::translated(), utf8_width(), and was_loaded.
load_widget()
void widget::load_widget (const JsonObject & jo, const std::string & src) static
Definition at line 40 of file widget.cpp.
 {
     widget_factory.load( jo, src );
 }
References src, and anonymous_namespace{widget.cpp}::widget_factory.
Referenced by DynamicDataLoader::initialize().
number()
std::string widget::number (int value, bool from_condition) const
Definition at line 1354 of file widget.cpp.
 {
     return from_condition ? number_cond() : string_format( "%d", value );
 }
References number_cond(), and string_format().
Referenced by value_string().
number_cond()
std::string widget::number_cond (enumeration_conjunction join_type = enumeration_conjunction::none) const
Definition at line 1388 of file widget.cpp.
 {
     std::vector<const widget_clause *> wplist = get_clauses();
     if( wplist.empty() ) {
         // All clauses returned false conditions, use default
         std::string txt = string_format( "%d", _default_clause.value );
         return _default_clause.value == INT_MIN ? "" :
                _default_clause.color == c_unset ? txt : colorize( txt, _default_clause.color );
     }
     // Get values as a comma-separated list
     return enumerate_as_string( wplist.begin(), wplist.end(), []( const widget_clause * wp ) {
         std::string txt = string_format( "%d", wp->value );
         return wp->color == c_unset ? txt : colorize( txt, wp->color );
     }, join_type );
 }
References _default_clause, c_unset, widget_clause::color, colorize(), enumerate_as_string(), get_clauses(), string_format(), and widget_clause::value.
Referenced by number().
only_bp()
const bodypart_id & widget::only_bp () const
Definition at line 568 of file widget.cpp.
 {
     static const bodypart_id bp_null = bodypart_str_id::NULL_ID();
     // For widgets that rely on just one bodypart, assume there's only one in the set
     return _bps.empty() ? bp_null : *_bps.begin();
 }
References _bps, and string_id< body_part_type >::NULL_ID().
Referenced by color_text_function_string(), get_clause(), get_var_value(), and set_default_var_range().
reset()
void widget::reset () static
Definition at line 45 of file widget.cpp.
 {
     widget_factory.reset();
 }
References anonymous_namespace{widget.cpp}::widget_factory.
Referenced by DynamicDataLoader::unload_data().
set_default_var_range()
void widget::set_default_var_range (const avatar & ava)
Definition at line 575 of file widget.cpp.
 {
     _var_min = INT_MIN;
     _var_max = INT_MAX;
     _var_norm = std::make_pair( INT_MIN, INT_MAX );
     switch( _var ) {
         case widget_var::cardio_acc:
             break; // TODO
         case widget_var::cardio_fit:
             _var_min = 0;
             // Same maximum used by get_cardiofit - 3 x BMR, adjusted for mutations
             _var_max = 3 * ava.base_bmr() * ava.enchantment_cache->modify_value(
                            enchant_vals::mod::CARDIO_MULTIPLIER, 1 );
             break;
         case widget_var::carry_weight:
             _var_min = 0;
             _var_max = 120;
             break;
         case widget_var::sleepiness:
             _var_min = 0;
             _var_max = 1000;
             break;
         case widget_var::focus:
             _var_min = 0;
             _var_max = 200;
             // Small range of normal focus that won't be color-coded
             _var_norm = std::make_pair( 90, 110 );
             break;
         case widget_var::health:
             _var_min = -200;
             _var_max = 200;
             // Small range of normal health that won't be color-coded
             _var_norm = std::make_pair( -10, 10 );
             break;
         case widget_var::mana:
             _var_min = 0;
             _var_max = ava.magic->max_mana( ava );
             break;
         case widget_var::max_mana:
             _var_min = 0;
             // What could "max max mana" mean? Use 2x current max because why not
             _var_max = 2 * ava.magic->max_mana( ava );
             break;
         case widget_var::power_percentage:
             _var_min = 0;
             _var_max = 100;
             break;
         case widget_var::log_power_balance:
             _var_min = 0;
             _var_max = 1200;
             _var_norm = std::make_pair( 600, 600 );
             break;
         case widget_var::mood:
             break; // TODO
         case widget_var::morale_level:
             _var_min = -100;
             _var_max = 100;
             // Small range of morale that isn't worth crying about
             _var_norm = std::make_pair( -10, 10 );
             break;
         case widget_var::move:
             _var_min = 0;
             _var_max = 1000; // TODO: Determine better max
             // Move cost of last action
             break;
         case widget_var::move_remainder:
             _var_min = 0;
             _var_max = 9999; // TODO: Determine better max
             // remaining moves for the current turn
             break;
         case widget_var::move_cost:
             _var_min = 0;
             _var_max = 300; // Can go up to 500-600 while prone
             _var_norm = std::make_pair( 100, 100 );
             break;
         case widget_var::pain:
             _var_min = 0;
             _var_max = 80;
             // Zero pain isn't really normal but it's the state we prefer
             _var_norm = std::make_pair( 0, 0 );
             break;
         case widget_var::sound:
             _var_min = 0;
             _var_max = 200;
             // Quiet sounds are normal
             _var_norm = std::make_pair( 0, 5 );
             break;
         case widget_var::speed:
             _var_min = 0;
             _var_max = 200;
             _var_norm.first = ava.get_speed_base();
             _var_norm.second = ava.get_speed_base();
             break;
         case widget_var::stamina:
             _var_min = 0;
             _var_max = ava.get_stamina_max();
             // No normal defined, unless we want max stamina to be colored white? (maybe)
             break;
         case widget_var::weariness_level:
             _var_min = 0;
             _var_max = 10;
             break;
         case widget_var::weary_transition_level:
             _var_min = 0;
             _var_max = ava.weary_threshold();
             break;
         // Base stats
         // Normal is the base stat value only; min and max are -3 and +3 from base
         case widget_var::stat_str:
             _var_norm.first = ava.get_str_base();
             _var_norm.second = ava.get_str_base();
             _var_min = _var_norm.first - 3;
             _var_max = _var_norm.first + 3;
             break;
         case widget_var::stat_dex:
             _var_norm.first = ava.get_dex_base();
             _var_norm.second = ava.get_dex_base();
             _var_min = _var_norm.first - 3;
             _var_max = _var_norm.first + 3;
             break;
         case widget_var::stat_int:
             _var_norm.first = ava.get_int_base();
             _var_norm.second = ava.get_int_base();
             _var_min = _var_norm.first - 3;
             _var_max = _var_norm.first + 3;
             break;
         case widget_var::stat_per:
             _var_norm.first = ava.get_per_base();
             _var_norm.second = ava.get_per_base();
             _var_min = _var_norm.first - 3;
             _var_max = _var_norm.first + 3;
             break;
         // Bodypart attributes
         case widget_var::bp_hp:
             // HP for body part
             _var_min = 0;
             if( ava.has_part( only_bp(), body_part_filter::equivalent ) ) {
                 _var_max = ava.get_part_hp_max( only_bp() );
             } else {
                 _var_max = 0;
             }
             break;
         case widget_var::bp_encumb:
             _var_min = 0;
             _var_max = 100; // ???
             break;
         case widget_var::bp_warmth:
             // From weather.h: Body temperature is measured on a scale of 0u to 10000u,
             // where 10u = 0.02C and 5000u is 37C
             _var_min = 0;
             _var_max = 10000;
             break;
         case widget_var::bp_wetness:
             _var_min = 0;
             _var_max = 100; // ???
             break;
         default:
             break;
     }
 }
References _var, _var_max, _var_min, _var_norm, Character::base_bmr(), bp_encumb, bp_hp, bp_warmth, bp_wetness, cardio_acc, cardio_fit, enchant_vals::CARDIO_MULTIPLIER, carry_weight, Character::enchantment_cache, equivalent, focus, Character::get_dex_base(), Character::get_int_base(), Creature::get_part_hp_max(), Character::get_per_base(), Creature::get_speed_base(), Character::get_stamina_max(), Character::get_str_base(), Creature::has_part(), health, log_power_balance, Character::magic, mana, max_mana, mood, morale_level, move, move_cost, move_remainder, only_bp(), pain, power_percentage, sleepiness, sound, speed, stamina, stat_dex, stat_int, stat_per, stat_str, weariness_level, Character::weary_threshold(), and weary_transition_level.
Referenced by show().
show()
std::string widget::show (const avatar & ava, unsigned int max_width)
Definition at line 877 of file widget.cpp.
 {
     set_default_var_range( ava );
     if( uses_text_function() ) {
         // Text functions are a carry-over from before widgets, with existing functions generating
         // descriptive colorized text for avatar attributes.  The "value" for these is immaterial;
         // only the final color string is shown.  Bypass value calculation and call the
         // text-rendering function directly.
         return color_text_function_string( ava, max_width );
     } else {
         // For normal widgets, get current numeric value and potential maximum,
         // and return a color string rendering of that value in the appropriate style.
         int value = get_var_value( ava );
         return color_value_string( value, max_width );
     }
 }
References color_text_function_string(), color_value_string(), get_var_value(), set_default_var_range(), and uses_text_function().
Referenced by layout().
sym()
std::string widget::sym (bool from_condition)
Definition at line 1367 of file widget.cpp.
 {
     return from_condition ? sym_cond() : text( from_condition, 0 );
 }
References sym_cond(), and text().
Referenced by value_string().
sym_cond()
std::string widget::sym_cond (bool no_join = true, enumeration_conjunction join_type = enumeration_conjunction::none) const
Definition at line 1433 of file widget.cpp.
 {
     std::vector<const widget_clause *> wplist = get_clauses();
     if( wplist.empty() ) {
         // All clauses returned false conditions, use default
         std::string txt = _default_clause.sym;
         return txt.empty() ? "" : _default_clause.color == c_unset ? txt : colorize( txt,
                 _default_clause.color );
     }
     // No string joining, just show symbols one-after-the-other
     if( no_join ) {
         std::string ret;
         for( const widget_clause *wp : wplist ) {
             ret += wp->color == c_unset ? wp->sym : colorize( wp->sym, wp->color );
         }
         return ret;
     }
     // Get values as a comma-separated list
     return enumerate_as_string( wplist.begin(), wplist.end(), []( const widget_clause * wp ) {
         return wp->color == c_unset ? wp->sym : colorize( wp->sym, wp->color );
     }, join_type );
 }
References _default_clause, c_unset, widget_clause::color, colorize(), enumerate_as_string(), get_clauses(), cata::hash64_detail::ret, and widget_clause::sym.
Referenced by sym().
sym_text()
std::string widget::sym_text (bool from_condition, int width = 0)
Definition at line 1372 of file widget.cpp.
 {
     if( from_condition ) {
         return sym_text_cond( true, width );
     }
     return _string.translated();
 }
References _string, sym_text_cond(), and translation::translated().
Referenced by value_string().
sym_text_cond()
std::string widget::sym_text_cond (bool no_join = true, int width = 0)
Definition at line 1456 of file widget.cpp.
 {
     std::vector<const widget_clause *> wplist = get_clauses();
     if( wplist.empty() ) {
         // All clauses returned false conditions, use default
         std::string txt = _default_clause.sym;
         txt += ( txt.empty() ? "" : " " ) + _default_clause.text.translated();
         return txt.empty() ? "" : _default_clause.color == c_unset ? txt : colorize( txt,
                 _default_clause.color );
     }
     std::vector<std::string> strings;
     strings.reserve( wplist.size() );
     for( const widget_clause *wp : wplist ) {
         std::string s = wp->color == c_unset ? wp->sym : colorize( wp->sym, wp->color );
         std::string txt_str = wp->text.translated();
         if( wp->should_parse_tags ) {
             parse_tags( txt_str, get_player_character(), get_player_character() );
         }
         std::string txt = string_format( "%s %s", s, txt_str );
         strings.emplace_back( txt );
     }
     int h = 0;
     std::string ret = format_widget_multiline( strings, _height_max, width, h, !no_join );
     if( has_flag( json_flag_W_DYNAMIC_HEIGHT ) ) {
         _height = h;
         set_height_for_widget( id, h );
     }
     return ret;
 }
References _default_clause, _height, _height_max, c_unset, widget_clause::color, colorize(), format_widget_multiline(), get_clauses(), get_player_character(), has_flag(), json_flag_W_DYNAMIC_HEIGHT, parse_tags(), cata::hash64_detail::ret, set_height_for_widget(), string_format(), widget_clause::sym, widget_clause::text, and translation::translated().
Referenced by sym_text().
text()
std::string widget::text (bool from_condition, int width = 0)
Definition at line 1359 of file widget.cpp.
 {
     if( from_condition ) {
         return text_cond( false, width );
     }
     return _string.translated();
 }
References _string, text_cond(), and translation::translated().
Referenced by sym(), and value_string().
text_cond()
std::string widget::text_cond (bool no_join = false, int width = 0)
Definition at line 1404 of file widget.cpp.
 {
     std::vector<const widget_clause *> wplist = get_clauses();
     if( wplist.empty() ) {
         // All clauses returned false conditions, use default
         std::string txt = _default_clause.text.translated();
         return txt.empty() ? "" : _default_clause.color == c_unset ? txt : colorize( txt,
                 _default_clause.color );
     }
     std::vector<std::string> strings;
     strings.reserve( wplist.size() );
     for( const widget_clause *wp : wplist ) {
         std::string txt = wp->text.translated();
         if( wp->should_parse_tags ) {
             parse_tags( txt, get_player_character(), get_player_character() );
         }
         txt = wp->color == c_unset ? txt : colorize(
                   txt, wp->color );
         strings.emplace_back( txt );
     }
     int h = 0;
     std::string ret = format_widget_multiline( strings, _height_max, width, h, !no_join );
     if( has_flag( json_flag_W_DYNAMIC_HEIGHT ) ) {
         _height = h;
         set_height_for_widget( id, h );
     }
     return ret;
 }
References _default_clause, _height, _height_max, c_unset, widget_clause::color, colorize(), format_widget_multiline(), get_clauses(), get_player_character(), has_flag(), json_flag_W_DYNAMIC_HEIGHT, parse_tags(), cata::hash64_detail::ret, set_height_for_widget(), widget_clause::text, and translation::translated().
Referenced by text().
uses_text_function()
bool widget::uses_text_function () const
Definition at line 1029 of file widget.cpp.
 {
     switch( _var ) {
         case widget_var::activity_text:
         case widget_var::body_graph:
         case widget_var::body_graph_temp:
         case widget_var::body_graph_encumb:
         case widget_var::body_graph_status:
         case widget_var::body_graph_wet:
         case widget_var::bp_armor_outer_text:
         case widget_var::carry_weight_text:
         case widget_var::compass_text:
         case widget_var::compass_legend_text:
         case widget_var::date_text:
         case widget_var::env_temp_text:
         case widget_var::mood_text:
         case widget_var::move_count_mode_text:
         case widget_var::pain_text:
         case widget_var::overmap_loc_text:
         case widget_var::overmap_text:
         case widget_var::place_text:
         case widget_var::power_text:
         case widget_var::power_balance_text:
         case widget_var::safe_mode_text:
         case widget_var::safe_mode_classic_text:
         case widget_var::style_text:
         case widget_var::sundial_text:
         case widget_var::sundial_time_text:
         case widget_var::time_text:
         case widget_var::veh_azimuth_text:
         case widget_var::veh_cruise_text:
         case widget_var::veh_fuel_text:
         case widget_var::weariness_text:
         case widget_var::weary_malus_text:
         case widget_var::weather_text:
         case widget_var::wielding_text:
         case widget_var::wielding_simple_text:
         case widget_var::wielding_mode_text:
         case widget_var::wielding_ammo_text:
         case widget_var::wind_text:
             return true;
         default:
             return false;
     }
 }
References _var, activity_text, body_graph, body_graph_encumb, body_graph_status, body_graph_temp, body_graph_wet, bp_armor_outer_text, carry_weight_text, compass_legend_text, compass_text, date_text, env_temp_text, mood_text, move_count_mode_text, overmap_loc_text, overmap_text, pain_text, place_text, power_balance_text, power_text, safe_mode_classic_text, safe_mode_text, style_text, sundial_text, sundial_time_text, time_text, veh_azimuth_text, veh_cruise_text, veh_fuel_text, weariness_text, weary_malus_text, weather_text, wielding_ammo_text, wielding_mode_text, wielding_simple_text, wielding_text, and wind_text.
Referenced by show().
value_color()
nc_color widget::value_color (int value)
Definition at line 1291 of file widget.cpp.
 {
     // Maps the range of values from min to max to the list of "colors", 0-indexed
     // [ _var_min ... ( _var_norm ) ... _var_max ]
     // [ 0, 1, 2, ...           ... num_colors-1 ]
     //
     if( _colors.empty() ) {
         return c_unset;
     }
     // Index of last color
     const int color_max = _colors.size() - 1;
     // Whether min, max, and normal are defined
     const bool min_max_defined = INT_MIN < _var_min && _var_max < INT_MAX;
     const bool normal_defined = INT_MIN < _var_norm.first && _var_norm.second < INT_MAX;
     // Get range of values from min to max
     const int var_range = _var_max - _var_min;
     if( ! _breaks.empty() ) {
         const int value_offset = ( 100 * ( value - _var_min ) ) / var_range;
         for( int i = 0; i < color_max; i++ ) {
             if( value_offset < _breaks[i] ) {
                 return _colors[i];
             }
         }
         return _colors[color_max];
     }
     // Convert value to a positive offset within the range
     const int value_offset = std::max( value - _var_min, 0 );
     // If (min, max) is a valid nonzero range, fit value to a color using that range
     if( min_max_defined && var_range > 0 ) {
         // If value is within defined _var_norm range, the color is c_white
         if( normal_defined && _var_norm.first <= value && value <= _var_norm.second ) {
             return c_white;
         } else if( value <= _var_min ) {
             // If smaller than lower limit, return first color
             return _colors.front();
         } else if( value >= _var_max ) {
             // If larger than upper limit, return last color
             return _colors.back();
         } else {
             // If value is within the range, map it to an appropriate color
             // Scale value offset within range from [0, 1] to map color range
             const double scale = static_cast<double>( value_offset ) / var_range;
             // The +0.5 offset makes top and bottom color slots more equitable
             // (without the offset, only the max value gets the top color)
             const int color_index = std::floor( scale * color_max + 0.5 );
             return _colors[color_index];
         }
     }
     // No scaling by min-max range; assume colors map to 0, 1, 2 ...
     // Truncate below 0 and above color_max
     if( value < 0 ) {
         return _colors[0];
     } else if( value <= color_max ) {
         return _colors[value];
     } else {
         return _colors.back();
     }
 }
References _breaks, _colors, _var_max, _var_min, _var_norm, c_unset, c_white, floor(), and max().
Referenced by color_value_string().
value_string()
std::string widget::value_string (int value, int width_max = 0)
Definition at line 1270 of file widget.cpp.
 {
     std::string ret;
     // Use the available horizontal space unless widget has an explicit width
     const int w = _width > 0 ? _width : width_max;
     if( _style == "graph" ) {
         ret += graph( value );
     } else if( _style == "text" ) {
         ret += text( !_clauses.empty(), w );
     } else if( _style == "symbol" ) {
         ret += sym( !_clauses.empty() );
     } else if( _style == "legend" ) {
         ret += sym_text( !_clauses.empty(), w );
     } else if( _style == "number" ) {
         ret += number( value, !_clauses.empty() );
     } else {
         ret += "???";
     }
     return ret;
 }
References _clauses, _style, _width, graph(), number(), cata::hash64_detail::ret, sym(), sym_text(), and text().
Referenced by color_value_string().
widgets()
std::vector< string_id< widget > > widget::widgets (bool from_condition)
Definition at line 1380 of file widget.cpp.
 {
     if( from_condition ) {
         return widgets_cond();
     }
     return _widgets;
 }
References _widgets, and widgets_cond().
Referenced by custom_draw_func(), layout(), and widgets_cond().
widgets_cond()
std::vector< string_id< widget > > widget::widgets_cond ()
Definition at line 1486 of file widget.cpp.
 {
     std::vector<const widget_clause *> wplist = get_clauses();
     if( wplist.empty() ) {
         return _default_clause.widgets;
     }
     std::vector<string_id<widget>> widgets;
     for( const widget_clause *wp : wplist ) {
         widgets.insert( widgets.end(), wp->widgets.begin(), wp->widgets.end() );
     }
     return widgets;
 }
References _default_clause, get_clauses(), widget_clause::widgets, and widgets().
Referenced by widgets().
Friends And Related Function Documentation
generic_factory< widget >
friend class generic_factory< widget > friend
Definition at line 204 of file widget.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 214 of file widget.h.
Member Data Documentation
_arrange
std::string widget::_arrange
Definition at line 276 of file widget.h.
Referenced by custom_draw_func(), get_wgt_height(), get_window_panel(), graph(), layout(), and load().
_body_graph
std::string widget::_body_graph
Definition at line 278 of file widget.h.
Referenced by color_text_function_string(), and load().
_bps
std::set<bodypart_id> widget::_bps
Definition at line 256 of file widget.h.
Referenced by widget_clause::get_clause_for_id(), get_clauses(), load(), and only_bp().
_breaks
std::vector<int> widget::_breaks
Definition at line 272 of file widget.h.
Referenced by load(), and value_color().
_clauses
std::vector<widget_clause> widget::_clauses
Definition at line 284 of file widget.h.
Referenced by custom_draw_func(), finalize_inherited_fields_recursive(), get_clause(), widget_clause::get_clause_for_id(), get_clauses(), get_window_panel(), layout(), load(), and value_string().
_colors
std::vector<nc_color> widget::_colors
Definition at line 270 of file widget.h.
Referenced by color_text_function_string(), load(), and value_color().
_default_clause
widget_clause widget::_default_clause
Definition at line 286 of file widget.h.
Referenced by load(), number_cond(), sym_cond(), sym_text_cond(), text_cond(), and widgets_cond().
_description
std::string widget::_description
Definition at line 233 of file widget.h.
Referenced by draw_center_win(), and load().
_direction
cardinal_direction widget::_direction
Definition at line 280 of file widget.h.
Referenced by color_text_function_string(), and load().
_fill
std::string widget::_fill
Definition at line 266 of file widget.h.
Referenced by graph(), and load().
_flags
std::set<flag_id> widget::_flags
Definition at line 282 of file widget.h.
Referenced by has_flag(), and load().
_height
int widget::_height = 0
Definition at line 260 of file widget.h.
Referenced by color_text_function_string(), custom_draw_func(), get_wgt_height(), get_window_panel(), graph(), layout(), load(), sym_text_cond(), and text_cond().
_height_max
int widget::_height_max = 0
Definition at line 262 of file widget.h.
Referenced by color_text_function_string(), load(), sym_text_cond(), and text_cond().
_label
translation widget::_label
Definition at line 231 of file widget.h.
Referenced by finalize_label_width_recursive(), get_window_panel(), layout(), and load().
_label_align
widget_alignment widget::_label_align
Definition at line 290 of file widget.h.
Referenced by layout(), and load().
_label_width
int widget::_label_width = 0
Definition at line 235 of file widget.h.
Referenced by custom_draw_func(), finalize_label_width_recursive(), layout(), and load().
_pad_labels
bool widget::_pad_labels
Definition at line 251 of file widget.h.
Referenced by finalize_label_width_recursive(), layout(), and load().
_padding
int widget::_padding
Definition at line 239 of file widget.h.
Referenced by finalize_inherited_fields_recursive(), layout(), and load().
_separator
std::string widget::_separator
Definition at line 237 of file widget.h.
Referenced by finalize_inherited_fields_recursive(), layout(), and load().
_string
translation widget::_string
Definition at line 268 of file widget.h.
Referenced by load(), sym_text(), and text().
_style
std::string widget::_style
Definition at line 229 of file widget.h.
Referenced by custom_draw_func(), dummy_wgt_render(), get_window_panel(), layout(), load(), and value_string().
_symbols
std::string widget::_symbols
Definition at line 264 of file widget.h.
Referenced by graph(), and load().
_text_align
widget_alignment widget::_text_align
Definition at line 288 of file widget.h.
Referenced by layout(), and load().
_var
widget_var widget::_var = widget_var::last
Definition at line 241 of file widget.h.
Referenced by color_text_function_string(), get_var_value(), load(), set_default_var_range(), and uses_text_function().
_var_max
int widget::_var_max = INT_MAX
Definition at line 245 of file widget.h.
Referenced by graph(), set_default_var_range(), and value_color().
_var_min
int widget::_var_min = INT_MIN
Definition at line 243 of file widget.h.
Referenced by set_default_var_range(), and value_color().
_var_norm
std::pair<int, int> widget::_var_norm = std::make_pair(INT_MIN, INT_MAX)
Definition at line 254 of file widget.h.
Referenced by set_default_var_range(), and value_color().
_widgets
std::vector<widget_id> widget::_widgets
Definition at line 274 of file widget.h.
Referenced by dummy_wgt_render(), finalize_inherited_fields_recursive(), finalize_label_width_recursive(), get_wgt_height(), get_window_panel(), initialize_default_custom_panels(), load(), and widgets().
_width
int widget::_width = 0
Definition at line 258 of file widget.h.
Referenced by color_text_function_string(), graph(), initialize_default_custom_panels(), layout(), load(), and value_string().
explicit_padding
bool widget::explicit_padding
Definition at line 249 of file widget.h.
Referenced by finalize_inherited_fields_recursive(), and load().
explicit_separator
bool widget::explicit_separator
Definition at line 247 of file widget.h.
Referenced by finalize_inherited_fields_recursive(), and load().
id
widget_id widget::id private
Definition at line 216 of file widget.h.
Referenced by getId().
src
std::vector<std::pair<widget_id, mod_id> > widget::src private
Definition at line 217 of file widget.h.
Referenced by load_widget().
was_loaded
bool widget::was_loaded = false private
Definition at line 218 of file widget.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/widget.h
src/widget.cpp