Cataclysm DDA: map_extra Class Reference
map_extra Class Reference
#include <map_extras.h>
Public Member Functions
bool is_valid_for (const mapgendata &) const
std::string get_symbol () const
std::string name () const
std::string description () const
bool has_flag (const std::string &flag) const
const cata::flat_set< std::string > & get_flags () const
void load (const JsonObject &jo, std::string_view src)
void check () const
Public Attributes
map_extra_id id = string_id<map_extra>::NULL_ID()
std::vector< std::pair< map_extra_id, mod_id > > src
std::string generator_id
map_extra_method generator_method = map_extra_method::null
bool autonote = false
uint32_t symbol = UTF8_getch("X")
nc_color color = c_red
bool was_loaded = false
Private Attributes
translation name_
translation description_
std::optional< std::pair< int, int > > min_max_zlevel_
cata::flat_set< std::string > flags_
Detailed Description
Definition at line 41 of file map_extras.h.
Member Function Documentation
check()
void map_extra::check () const
Definition at line 2372 of file map_extras.cpp.
 {
     switch( generator_method ) {
         case map_extra_method::map_extra_function: {
             const map_extra_pointer mx_func = MapExtras::get_function( map_extra_id( generator_id ) );
             if( mx_func == nullptr ) {
                 debugmsg( "invalid map extra function (%s) defined for map extra (%s)", generator_id, id.str() );
                 break;
             }
             MapExtras::all_function_names.push_back( id );
             break;
         }
         case map_extra_method::mapgen: {
             MapExtras::all_function_names.push_back( id );
             break;
         }
         case map_extra_method::update_mapgen: {
             const auto update_mapgen_func = update_mapgens.find( update_mapgen_id( generator_id ) );
             if( update_mapgen_func == update_mapgens.end() ||
                 update_mapgen_func->second.funcs().empty() ) {
                 debugmsg( "invalid update mapgen function (%s) defined for map extra (%s)", generator_id,
                           id.str() );
                 break;
             }
             MapExtras::all_function_names.push_back( id );
             break;
         }
         case map_extra_method::null:
         default:
             break;
     }
 }
References MapExtras::all_function_names, debugmsg, generator_id, generator_method, MapExtras::get_function(), map_extra_function, mapgen, null, update_mapgen, and update_mapgens.
description()
std::string map_extra::description () const inline
Definition at line 60 of file map_extras.h.
{
             return description_.translated();
         }
References description_, and translation::translated().
Referenced by overmap::add_extra_note().
get_flags()
const cata::flat_set<std::string>& map_extra::get_flags () const inline
Definition at line 66 of file map_extras.h.
{
             return flags_;
         }
References flags_.
Referenced by is_valid_for().
get_symbol()
std::string map_extra::get_symbol () const inline
Definition at line 54 of file map_extras.h.
{
             return utf32_to_utf8( symbol );
         }
References symbol, and utf32_to_utf8().
Referenced by overmap::add_extra_note().
has_flag()
bool map_extra::has_flag (const std::string & flag) const inline
Definition at line 63 of file map_extras.h.
{
             return flags_.count( flag );
         }
References cata::flat_set< T, Compare, Data >::count(), and flags_.
is_valid_for()
bool map_extra::is_valid_for (const mapgendata & md) const
Definition at line 2331 of file map_extras.cpp.
 {
     int z = md.zlevel();
     if( min_max_zlevel_ ) {
         if( z < min_max_zlevel_->first || z > min_max_zlevel_->second ) {
             return false;
         }
     }
     if( !md.region.overmap_feature_flag.blacklist.empty() ) {
         // map extra is blacklisted by flag
         if( cata::sets_intersect( md.region.overmap_feature_flag.blacklist, get_flags() ) ) {
             return false;
         }
     }
     if( !md.region.overmap_feature_flag.whitelist.empty() ) {
         // map extra is not whitelisted by flag
         if( !cata::sets_intersect( md.region.overmap_feature_flag.whitelist, get_flags() ) ) {
             return false;
         }
     }
     return true;
 }
References overmap_feature_flag_settings::blacklist, get_flags(), min_max_zlevel_, regional_settings::overmap_feature_flag, mapgendata::region, cata::sets_intersect(), overmap_feature_flag_settings::whitelist, and mapgendata::zlevel().
Referenced by map_extras::filtered_by().
load()
void map_extra::load (const JsonObject & jo, std::string_view src)
Definition at line 2355 of file map_extras.cpp.
 {
     mandatory( jo, was_loaded, "name", name_ );
     mandatory( jo, was_loaded, "description", description_ );
     if( jo.has_object( "generator" ) ) {
         JsonObject jg = jo.get_object( "generator" );
         generator_method = jg.get_enum_value<map_extra_method>( "generator_method",
                            map_extra_method::null );
         mandatory( jg, was_loaded, "generator_id", generator_id );
     }
     optional( jo, was_loaded, "sym", symbol, unicode_codepoint_from_symbol_reader, NULL_UNICODE );
     color = jo.has_member( "color" ) ? color_from_string( jo.get_string( "color" ) ) : c_white;
     optional( jo, was_loaded, "autonote", autonote, false );
     optional( jo, was_loaded, "min_max_zlevel", min_max_zlevel_ );
     optional( jo, was_loaded, "flags", flags_ );
 }
References autonote, c_white, color, color_from_string(), description_, flags_, generator_id, generator_method, JsonObject::get_enum_value(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_object(), mandatory, min_max_zlevel_, name_, null, NULL_UNICODE, optional(), symbol, unicode_codepoint_from_symbol_reader(), and was_loaded.
name()
std::string map_extra::name () const inline
Definition at line 57 of file map_extras.h.
{
             return name_.translated();
         }
References name_, and translation::translated().
Referenced by overmap::add_extra_note().
Member Data Documentation
autonote
bool map_extra::autonote = false
Definition at line 48 of file map_extras.h.
Referenced by load().
color
nc_color map_extra::color = c_red
Definition at line 50 of file map_extras.h.
Referenced by overmap::add_extra_note(), and load().
description_
translation map_extra::description_ private
Definition at line 76 of file map_extras.h.
Referenced by description(), and load().
flags_
cata::flat_set<std::string> map_extra::flags_ private
Definition at line 78 of file map_extras.h.
Referenced by get_flags(), has_flag(), and load().
generator_id
std::string map_extra::generator_id
Definition at line 46 of file map_extras.h.
Referenced by MapExtras::apply_function(), check(), and load().
generator_method
map_extra_method map_extra::generator_method = map_extra_method::null
Definition at line 47 of file map_extras.h.
Referenced by MapExtras::apply_function(), check(), and load().
id
map_extra_id map_extra::id = string_id<map_extra>::NULL_ID()
Definition at line 44 of file map_extras.h.
Referenced by overmap::add_extra_note().
min_max_zlevel_
std::optional<std::pair<int, int> > map_extra::min_max_zlevel_ private
Definition at line 77 of file map_extras.h.
Referenced by is_valid_for(), and load().
name_
translation map_extra::name_ private
Definition at line 75 of file map_extras.h.
Referenced by load(), and name().
src
std::vector<std::pair<map_extra_id, mod_id> > map_extra::src
Definition at line 45 of file map_extras.h.
Referenced by overmapbuffer::get_travel_path().
symbol
uint32_t map_extra::symbol = UTF8_getch("X")
Definition at line 49 of file map_extras.h.
Referenced by get_symbol(), and load().
was_loaded
bool map_extra::was_loaded = false
Definition at line 71 of file map_extras.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/map_extras.h
src/map_extras.cpp