Cataclysm DDA: craft_activity_actor Class Reference
craft_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
craft_activity_actor (item_location &it, bool is_long)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &crafter) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &crafter) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &crafter) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &, Character &) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
float exertion_level () const override
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
craft_activity_actor ()=default
bool check_if_craft_okay (item_location &craft_item, Character &crafter)
Private Attributes
item_location craft_item
bool is_long
float activity_override = NO_EXERCISE
std::optional< requirement_data > cached_continuation_requirements
float cached_crafting_speed
int cached_assistants
double cached_base_total_moves
double cached_cur_total_moves
float cached_workbench_multiplier
bool use_cached_workbench_multiplier
Detailed Description
Definition at line 933 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
craft_activity_actor() [1/2]
craft_activity_actor::craft_activity_actor () private default
Referenced by deserialize().
craft_activity_actor() [2/2]
craft_activity_actor::craft_activity_actor (item_location & it, bool is_long)
Definition at line 3581 of file activity_actor.cpp.
                                                                                   :
     craft_item( it ), is_long( is_long )
 {
     cached_crafting_speed = 0;
     cached_assistants = 0;
     cached_base_total_moves = 1;
     cached_cur_total_moves = 1;
     cached_workbench_multiplier = 0;
     use_cached_workbench_multiplier = false;
 }
References cached_assistants, cached_base_total_moves, cached_crafting_speed, cached_cur_total_moves, cached_workbench_multiplier, and use_cached_workbench_multiplier.
Member Function Documentation
canceled()
void craft_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 3772 of file activity_actor.cpp.
 {
     item *craft = craft_item.get_item();
     // item_location::get_item() will return nullptr if the item is lost
     if( !craft ) {
         return;
     }
     const recipe item_recipe = craft->get_making();
     // practice recipe items with no components can be safely removed
     if( item_recipe.category == "CC_PRACTICE" && craft->components.empty() ) {
         craft_item.remove_item();
     }
 }
References recipe::category, anonymous_namespace{item_tname.cpp}::craft(), craft_item, item_location::get_item(), and item_location::remove_item().
check_if_craft_okay()
bool craft_activity_actor::check_if_craft_okay (item_location & craft_item, Character & crafter) private
Definition at line 3592 of file activity_actor.cpp.
 {
     item *craft = craft_item.get_item();
     // item_location::get_item() will return nullptr if the item is lost
     if( !craft || square_dist( craft_item.pos_bub(), crafter.pos_bub() ) > 1 ) {
         crafter.add_msg_player_or_npc(
             _( "You no longer have the in progress craft in your possession.  "
                "You stop crafting.  "
                "Reactivate the in progress craft to continue crafting." ),
             _( "<npcname> no longer has the in progress craft in their possession.  "
                "<npcname> stops crafting." ) );
         return false;
     }
     if( !craft->is_craft() ) {
         debugmsg( "ACT_CRAFT target '%s' is not a craft.  Aborting ACT_CRAFT.", craft->tname() );
         return false;
     }
     if( !cached_continuation_requirements ) {
         cached_continuation_requirements = craft->get_continue_reqs();
     }
     return crafter.can_continue_craft( *craft, *cached_continuation_requirements );
 }
References _, Character::add_msg_player_or_npc(), cached_continuation_requirements, Character::can_continue_craft(), anonymous_namespace{item_tname.cpp}::craft(), craft_item, debugmsg, item_location::get_item(), Creature::pos_bub(), item_location::pos_bub(), and square_dist().
Referenced by do_turn(), and start().
clone()
std::unique_ptr<activity_actor> craft_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 962 of file activity_actor_definitions.h.
{
             return std::make_unique<craft_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > craft_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 3811 of file activity_actor.cpp.
 {
     JsonObject data = jsin.get_object();
     craft_activity_actor actor = craft_activity_actor();
     data.read( "craft_loc", actor.craft_item );
     data.read( "long", actor.is_long );
     data.read( "activity_override", actor.activity_override );
     return actor.clone();
 }
References activity_override, clone(), craft_activity_actor(), craft_item, JsonValue::get_object(), is_long, and JsonObject::read().
do_turn()
void craft_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 3631 of file activity_actor.cpp.
 {
     if( !check_if_craft_okay( craft_item, crafter ) ) {
         act.set_to_null();
         return;
     }
     // We already checked if this is nullptr above
     item &craft = *craft_item.get_item();
     const std::optional<tripoint> location = craft_item.where() == item_location::type::character
             ? std::optional<tripoint>() : std::optional<tripoint>( craft_item.position() );
     const recipe &rec = craft.get_making();
     if( !use_cached_workbench_multiplier ) {
         cached_workbench_multiplier = crafter.workbench_crafting_speed_multiplier( craft, location );
         use_cached_workbench_multiplier = true;
     }
     const float crafting_speed = crafter.crafting_speed_multiplier( craft, location,
                                  use_cached_workbench_multiplier,
                                  cached_workbench_multiplier );
     const int assistants = crafter.available_assistant_count( craft.get_making() );
     if( crafting_speed <= 0.0f ) {
         crafter.cancel_activity();
         return;
     }
     if( cached_crafting_speed != crafting_speed || cached_assistants != assistants ) {
         cached_crafting_speed = crafting_speed;
         cached_assistants = assistants;
         // Base moves for batch size with no speed modifier or assistants
         // Must ensure >= 1 so we don't divide by 0;
         cached_base_total_moves = std::max( static_cast<int64_t>( 1 ),
                                             rec.batch_time( crafter, craft.get_making_batch_size(), 1.0f, 0 ) );
         // Current expected total moves, includes crafting speed modifiers and assistants
         cached_cur_total_moves = std::max( static_cast<int64_t>( 1 ),
                                            rec.batch_time( crafter, craft.get_making_batch_size(), crafting_speed,
                                                    assistants ) );
     }
     const double base_total_moves = cached_base_total_moves;
     const double cur_total_moves = cached_cur_total_moves;
     // item_counter represents the percent progress relative to the base batch time
     // stored precise to 5 decimal places ( e.g. 67.32 percent would be stored as 6'732'000 )
     const int old_counter = craft.item_counter;
     // Delta progress in moves adjusted for current crafting speed /
     //crafter.exertion_adjusted_move_multiplier( exertion_level() )
     int spent_moves = crafter.get_moves() * crafter.exertion_adjusted_move_multiplier(
                           exertion_level() );
     const double delta_progress = spent_moves * base_total_moves / cur_total_moves;
     // Current progress in moves
     const double current_progress = craft.item_counter * base_total_moves / 10'000'000.0 +
                                     delta_progress;
     // Current progress as a percent of base_total_moves to 2 decimal places
     craft.item_counter = std::round( current_progress / base_total_moves * 10'000'000.0 );
     crafter.set_moves( 0 );
     // This is to ensure we don't over count skill steps
     craft.item_counter = std::min( craft.item_counter, 10'000'000 );
     // This nominal craft time is also how many practice ticks to perform
     // spread out evenly across the actual duration.
     const double total_practice_ticks = rec.time_to_craft_moves( crafter,
                                         recipe_time_flag::ignore_proficiencies ) / 100.0;
     const int ticks_per_practice = 10'000'000.0 / total_practice_ticks;
     int num_practice_ticks = craft.item_counter / ticks_per_practice -
                              old_counter / ticks_per_practice;
     bool level_up = false;
     if( num_practice_ticks > 0 ) {
         level_up |= crafter.craft_skill_gain( craft, num_practice_ticks );
     }
     // Proficiencies and tools are gained/consumed after every 5% progress
     int five_percent_steps = craft.item_counter / 500'000 - old_counter / 500'000;
     if( five_percent_steps > 0 ) {
         // Divide by 100 for seconds, 20 for 5%
         const time_duration pct_time = time_duration::from_seconds( base_total_moves / 2000 );
         level_up |= crafter.craft_proficiency_gain( craft, pct_time * five_percent_steps );
         // Invalidate the crafting time cache because proficiencies may have changed
         cached_crafting_speed = 0;
         // Also reset the multiplier
         use_cached_workbench_multiplier = false;
     }
     // Unlike skill, tools are consumed once at the start and should not be consumed at the end
     if( craft.item_counter >= 10'000'000 ) {
         --five_percent_steps;
     }
     if( five_percent_steps > 0 ) {
         if( !crafter.craft_consume_tools( craft, five_percent_steps, false ) ) {
             // So we don't skip over any tool comsuption
             craft.item_counter -= craft.item_counter % 500'000 + 1;
             crafter.cancel_activity();
             return;
         }
     }
     // if item_counter has reached 100% or more
     if( craft.item_counter >= 10'000'000 ) {
         if( rec.is_practice() && !is_long && craft.get_making_batch_size() == 1 ) {
             if( query_yn( _( "Keep practicing until proficiency increases?" ) ) ) {
                 is_long = true;
                 *( crafter.last_craft ) = craft_command( &craft.get_making(), 1, is_long, &crafter, location );
             }
         }
         item craft_copy = craft;
         craft_item.remove_item();
         // We need to cache this before we cancel the activity else we risk Use After Free
         const bool will_continue = is_long;
         crafter.cancel_activity();
         crafter.complete_craft( craft_copy, location );
         if( will_continue ) {
             if( crafter.making_would_work( crafter.lastrecipe, craft_copy.get_making_batch_size() ) ) {
                 crafter.last_craft->execute( location );
             }
         }
     } else {
         if( level_up && craft.get_making().is_practice() &&
             query_yn( _( "Your proficiency has increased.  Stop practicing?" ) ) ) {
             crafter.cancel_activity();
         } else if( craft.item_counter >= craft.get_next_failure_point() ) {
             bool destroy = craft.handle_craft_failure( crafter );
             // If the craft needs to be destroyed, do it and stop crafting.
             if( destroy ) {
                 crafter.add_msg_player_or_npc( _( "There is nothing left of the %s to craft from." ),
                                                _( "There is nothing left of the %s <npcname> was crafting." ), craft.tname() );
                 craft_item.remove_item();
                 crafter.cancel_activity();
             }
         }
     }
 }
References _, act, Character::add_msg_player_or_npc(), Character::available_assistant_count(), recipe::batch_time(), cached_assistants, cached_base_total_moves, cached_crafting_speed, cached_cur_total_moves, cached_workbench_multiplier, Character::cancel_activity(), item_location::character, check_if_craft_okay(), Character::complete_craft(), anonymous_namespace{item_tname.cpp}::craft(), Character::craft_consume_tools(), craft_item, Character::craft_proficiency_gain(), Character::craft_skill_gain(), Character::crafting_speed_multiplier(), Character::exertion_adjusted_move_multiplier(), exertion_level(), time_duration::from_seconds(), item_location::get_item(), item::get_making_batch_size(), Creature::get_moves(), ignore_proficiencies, is_long, recipe::is_practice(), Character::last_craft, Character::lastrecipe, location, Character::making_would_work(), max(), min(), item_location::position(), query_yn(), item_location::remove_item(), round(), Creature::set_moves(), recipe::time_to_craft_moves(), use_cached_workbench_multiplier, item_location::where(), and Character::workbench_crafting_speed_multiplier().
exertion_level()
float craft_activity_actor::exertion_level () const override virtual
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
Reimplemented from activity_actor.
Definition at line 3795 of file activity_actor.cpp.
 {
     return activity_override;
 }
References activity_override.
Referenced by do_turn().
finish()
void craft_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 3767 of file activity_actor.cpp.
 {
     act.set_to_null();
 }
References act.
get_progress_message()
std::string craft_activity_actor::get_progress_message (const player_activity & act) const override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 3786 of file activity_actor.cpp.
 {
     if( !craft_item ) {
         //We have somehow lost the craft item.  This will be handled in do_turn in the check_if_craft_is_ok call.
         return "";
     }
     return craft_item.get_item()->tname();
 }
References craft_item, item_location::get_item(), and item::tname().
get_type()
activity_id craft_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 953 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_CRAFT" );
         }
References activity_id.
serialize()
void craft_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 3800 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "craft_loc", craft_item );
     jsout.member( "long", is_long );
     jsout.member( "activity_override", activity_override );
     jsout.end_object();
 }
References activity_override, craft_item, JsonOut::end_object(), is_long, JsonOut::member(), and JsonOut::start_object().
start()
void craft_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 3618 of file activity_actor.cpp.
 {
     if( !check_if_craft_okay( craft_item, crafter ) ) {
         act.set_to_null();
     }
     activity_override = craft_item.get_item()->get_making().exertion_level();
     cached_crafting_speed = 0;
     cached_workbench_multiplier = 0;
     use_cached_workbench_multiplier = false;
     act.targets.clear();
     act.targets.push_back( craft_item );
 }
References act, activity_override, cached_crafting_speed, cached_workbench_multiplier, check_if_craft_okay(), craft_item, recipe::exertion_level(), item_location::get_item(), item::get_making(), and use_cached_workbench_multiplier.
Member Data Documentation
activity_override
float craft_activity_actor::activity_override = NO_EXERCISE private
Definition at line 941 of file activity_actor_definitions.h.
Referenced by deserialize(), exertion_level(), serialize(), and start().
cached_assistants
int craft_activity_actor::cached_assistants private
Definition at line 944 of file activity_actor_definitions.h.
Referenced by craft_activity_actor(), and do_turn().
cached_base_total_moves
double craft_activity_actor::cached_base_total_moves private
Definition at line 945 of file activity_actor_definitions.h.
Referenced by craft_activity_actor(), and do_turn().
cached_continuation_requirements
std::optional<requirement_data> craft_activity_actor::cached_continuation_requirements private
Definition at line 942 of file activity_actor_definitions.h.
Referenced by check_if_craft_okay().
cached_crafting_speed
float craft_activity_actor::cached_crafting_speed private
Definition at line 943 of file activity_actor_definitions.h.
Referenced by craft_activity_actor(), do_turn(), and start().
cached_cur_total_moves
double craft_activity_actor::cached_cur_total_moves private
Definition at line 946 of file activity_actor_definitions.h.
Referenced by craft_activity_actor(), and do_turn().
cached_workbench_multiplier
float craft_activity_actor::cached_workbench_multiplier private
Definition at line 947 of file activity_actor_definitions.h.
Referenced by craft_activity_actor(), do_turn(), and start().
craft_item
item_location craft_activity_actor::craft_item private
Definition at line 938 of file activity_actor_definitions.h.
Referenced by canceled(), check_if_craft_okay(), deserialize(), do_turn(), get_progress_message(), serialize(), and start().
is_long
bool craft_activity_actor::is_long private
Definition at line 939 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
use_cached_workbench_multiplier
bool craft_activity_actor::use_cached_workbench_multiplier private
Definition at line 948 of file activity_actor_definitions.h.
Referenced by craft_activity_actor(), do_turn(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp