Cataclysm DDA: enchantment Class Reference
enchantment Class Reference
#include <magic_enchantment.h>
Classes
struct bodypart_changes
Public Types
enum has { WIELD , WORN , HELD , NUM_HAS }
enum condition {
ALWAYS , ACTIVE , INACTIVE , DIALOG_CONDITION ,
NUM_CONDITION
}
Public Member Functions
void load (const JsonObject &jo, std::string_view src={}, const std::optional< std::string > &inline_id=std::nullopt, bool is_child=false)
bool is_active (const Character &guy, const item &parent) const
bool is_active (const Character &guy, bool active) const
bool is_active (const monster &mon) const
bool is_monster_relevant () const
bool active_wield () const
const std::set< trait_id > & get_mutations () const
double get_value_add (enchant_vals::mod value, const Character &guy) const
double get_value_multiply (enchant_vals::mod value, const Character &guy) const
body_part_set modify_bodyparts (const body_part_set &unmodified) const
bool modifies_bodyparts () const
void add_activation (const time_duration &dur, const fake_spell &fake)
Static Public Member Functions
static void load_enchantment (const JsonObject &jo, const std::string &src)
static void reset ()
static enchantment_id load_inline_enchantment (const JsonValue &jv, std::string_view src, std::string &inline_id)
Public Attributes
enchantment_id id
std::vector< std::pair< enchantment_id, mod_id > > src
bool was_loaded = false
std::vector< bodypart_changes > modified_bodyparts
std::set< trait_id > mutations
std::optional< emit_id > emitter
std::map< efftype_id, int > ench_effects
translation name
translation description
std::map< enchant_vals::mod, dbl_or_var > values_add
std::map< enchant_vals::mod, dbl_or_var > values_multiply
std::map< skill_id, dbl_or_var > skill_values_add
std::map< skill_id, dbl_or_var > skill_values_multiply
std::vector< fake_spell > hit_me_effect
std::vector< fake_spell > hit_you_effect
std::map< time_duration, std::vector< fake_spell > > intermittent_activation
std::pair< has, condition > active_conditions
std::function< bool(dialogue &)> dialog_condition
Detailed Description
Definition at line 181 of file magic_enchantment.h.
Member Enumeration Documentation
condition
enum enchantment::condition
Enumerator
ALWAYS
ACTIVE
INACTIVE
DIALOG_CONDITION
NUM_CONDITION
Definition at line 191 of file magic_enchantment.h.
{
             ALWAYS,
             ACTIVE, // the item, mutation, etc. is active
             INACTIVE, // the item, mutation, etc. is inactive
             DIALOG_CONDITION, // Check a provided dialog condition
             NUM_CONDITION
         };
has
enum enchantment::has
Enumerator
WIELD
WORN
HELD
NUM_HAS
Definition at line 184 of file magic_enchantment.h.
                  {
             WIELD,
             WORN,
             HELD,
             NUM_HAS
         };
Member Function Documentation
active_wield()
bool enchantment::active_wield () const
Definition at line 352 of file magic_enchantment.cpp.
 {
     return active_conditions.first == has::HELD || active_conditions.first == has::WIELD;
 }
References active_conditions, and WIELD.
add_activation()
void enchantment::add_activation (const time_duration & dur, const fake_spell & fake)
Definition at line 357 of file magic_enchantment.cpp.
 {
     intermittent_activation[dur].emplace_back( fake );
 }
References dur, and intermittent_activation.
Referenced by load().
get_mutations()
const std::set<trait_id>& enchantment::get_mutations () const inline
Definition at line 230 of file magic_enchantment.h.
{
             return mutations;
         }
References mutations.
Referenced by enchant_cache::operator==().
get_value_add()
double enchantment::get_value_add (enchant_vals::mod value, const Character & guy) const
Definition at line 860 of file magic_enchantment.cpp.
 {
     const auto found = values_add.find( value );
     if( found == values_add.cend() ) {
         return 0;
     }
     dialogue d( get_talker_for( guy ), nullptr );
     return found->second.evaluate( d );
 }
References get_talker_for(), and values_add.
Referenced by enchant_cache::modify_value(), and enchant_cache::serialize().
get_value_multiply()
double enchantment::get_value_multiply (enchant_vals::mod value, const Character & guy) const
Definition at line 870 of file magic_enchantment.cpp.
 {
     const auto found = values_multiply.find( value );
     if( found == values_multiply.cend() ) {
         return 0;
     }
     dialogue d( get_talker_for( guy ), nullptr );
     return found->second.evaluate( d );
 }
References get_talker_for(), and values_multiply.
Referenced by enchant_cache::modify_value(), enchant_cache::mult_bonus(), and enchant_cache::serialize().
is_active() [1/3]
bool enchantment::is_active (const Character & guy, bool active) const
Definition at line 277 of file magic_enchantment.cpp.
 {
     if( active_conditions.second == condition::ACTIVE ) {
         return active;
     }
     if( active_conditions.second == condition::INACTIVE ) {
         return !active;
     }
     if( active_conditions.second == condition::ALWAYS ) {
         return true;
     }
     if( active_conditions.second == condition::DIALOG_CONDITION ) {
         dialogue d( get_talker_for( guy ), nullptr );
         return dialog_condition( d );
     }
     return false;
 }
References active, active_conditions, dialog_condition, and get_talker_for().
is_active() [2/3]
bool enchantment::is_active (const Character & guy, const item & parent) const
Definition at line 256 of file magic_enchantment.cpp.
 {
     if( !guy.has_item( parent ) ) {
         return false;
     }
     if( active_conditions.first == has::HELD &&
         active_conditions.second == condition::ALWAYS ) {
         return true;
     }
     if( !( active_conditions.first == has::HELD ||
            ( active_conditions.first == has::WIELD && guy.is_wielding( parent ) ) ||
            ( active_conditions.first == has::WORN &&
              ( guy.is_worn( parent ) || guy.is_worn_module( parent ) ) ) ) ) {
         return false;
     }
     return is_active( guy, parent.active );
 }
References item::active, active_conditions, visitable::has_item(), Character::is_wielding(), Character::is_worn(), Character::is_worn_module(), and WIELD.
Referenced by monster::process_one_effect().
is_active() [3/3]
bool enchantment::is_active (const monster & mon) const
Definition at line 298 of file magic_enchantment.cpp.
 {
     //This is very limited at the moment. Basically, we can't use any conditions except "ALWAYS"
     if( active_conditions.second == condition::ALWAYS && !mon.is_fake() ) {
         return true;
     }
     // Dialogue conditions for monsters seems like overkill.
     // Definitely not an excuse for not knowing how to add them. Nope! Sure isn't!
     return false;
 }
References active_conditions, and Creature::is_fake().
is_monster_relevant()
bool enchantment::is_monster_relevant () const
Definition at line 310 of file magic_enchantment.cpp.
 {
     // Check add values.
     for( const std::pair<const enchant_vals::mod, dbl_or_var> &pair_values :
          values_add ) {
         if( pair_values.first == enchant_vals::mod::ARMOR_ACID ||
             pair_values.first == enchant_vals::mod::ARMOR_ALL ||
             pair_values.first == enchant_vals::mod::ARMOR_BASH ||
             pair_values.first == enchant_vals::mod::ARMOR_BIO ||
             pair_values.first == enchant_vals::mod::ARMOR_BULLET ||
             pair_values.first == enchant_vals::mod::ARMOR_COLD ||
             pair_values.first == enchant_vals::mod::ARMOR_CUT ||
             pair_values.first == enchant_vals::mod::ARMOR_ELEC ||
             pair_values.first == enchant_vals::mod::ARMOR_HEAT ||
             pair_values.first == enchant_vals::mod::ARMOR_STAB ||
             pair_values.first == enchant_vals::mod::REGEN_HP ||
             pair_values.first == enchant_vals::mod::SPEED ) {
             return true;
         }
     }
     // Check mult values.
     for( const std::pair<const enchant_vals::mod, dbl_or_var> &pair_values :
          values_multiply ) {
         if( pair_values.first == enchant_vals::mod::ARMOR_ACID ||
             pair_values.first == enchant_vals::mod::ARMOR_ALL ||
             pair_values.first == enchant_vals::mod::ARMOR_BASH ||
             pair_values.first == enchant_vals::mod::ARMOR_BIO ||
             pair_values.first == enchant_vals::mod::ARMOR_BULLET ||
             pair_values.first == enchant_vals::mod::ARMOR_COLD ||
             pair_values.first == enchant_vals::mod::ARMOR_CUT ||
             pair_values.first == enchant_vals::mod::ARMOR_ELEC ||
             pair_values.first == enchant_vals::mod::ARMOR_HEAT ||
             pair_values.first == enchant_vals::mod::ARMOR_STAB ||
             pair_values.first == enchant_vals::mod::REGEN_HP ||
             pair_values.first == enchant_vals::mod::SPEED ) {
             return true;
         }
     }
     return false;
 }
References enchant_vals::ARMOR_ACID, enchant_vals::ARMOR_ALL, enchant_vals::ARMOR_BASH, enchant_vals::ARMOR_BIO, enchant_vals::ARMOR_BULLET, enchant_vals::ARMOR_COLD, enchant_vals::ARMOR_CUT, enchant_vals::ARMOR_ELEC, enchant_vals::ARMOR_HEAT, enchant_vals::ARMOR_STAB, enchant_vals::REGEN_HP, enchant_vals::SPEED, values_add, and values_multiply.
Referenced by monster::process_one_effect().
load()
void enchantment::load (const JsonObject & jo, std::string_view src = {}, const std::optional< std::string > & inline_id = std::nullopt, bool is_child = false)
Definition at line 381 of file magic_enchantment.cpp.
 {
     optional( jo, was_loaded, "id", id, enchantment_id( inline_id.value_or( "" ) ) );
     jo.read( "hit_you_effect", hit_you_effect );
     jo.read( "hit_me_effect", hit_me_effect );
     jo.read( "emitter", emitter );
     if( jo.has_object( "intermittent_activation" ) ) {
         JsonObject jobj = jo.get_object( "intermittent_activation" );
         for( const JsonObject effect_obj : jobj.get_array( "effects" ) ) {
             time_duration dur = read_from_json_string<time_duration>( effect_obj.get_member( "frequency" ),
                                 time_duration::units );
             if( effect_obj.has_array( "spell_effects" ) ) {
                 for( const JsonObject fake_spell_obj : effect_obj.get_array( "spell_effects" ) ) {
                     fake_spell fake;
                     fake.load( fake_spell_obj );
                     add_activation( dur, fake );
                 }
             } else if( effect_obj.has_object( "spell_effects" ) ) {
                 fake_spell fake;
                 JsonObject fake_spell_obj = effect_obj.get_object( "spell_effects" );
                 fake.load( fake_spell_obj );
                 add_activation( dur, fake );
             }
         }
     }
     active_conditions.first = io::string_to_enum<has>( jo.get_string( "has", "HELD" ) );
     if( jo.has_string( "condition" ) ) {
         std::string condit;
         optional( jo, was_loaded, "condition", condit );
         std::optional<condition> con = io::string_to_enum_optional<condition>( condit );
         if( con.has_value() ) {
             active_conditions.second = con.value();
         } else {
             active_conditions.second = condition::DIALOG_CONDITION;
         }
     } else if( jo.has_member( "condition" ) ) {
         active_conditions.second = condition::DIALOG_CONDITION;
     } else {
         active_conditions.second = condition::ALWAYS;
     }
     if( active_conditions.second == condition::DIALOG_CONDITION ) {
         read_condition( jo, "condition", dialog_condition, false );
     }
     for( JsonObject jsobj : jo.get_array( "ench_effects" ) ) {
         ench_effects.emplace( efftype_id( jsobj.get_string( "effect" ) ), jsobj.get_int( "intensity" ) );
     }
     optional( jo, was_loaded, "modified_bodyparts", modified_bodyparts );
     optional( jo, was_loaded, "mutations", mutations );
     optional( jo, was_loaded, "name", name );
     optional( jo, was_loaded, "description", description );
     if( !is_child && jo.has_array( "values" ) ) {
         for( const JsonObject value_obj : jo.get_array( "values" ) ) {
             const enchant_vals::mod value = io::string_to_enum<enchant_vals::mod>
                                             ( value_obj.get_string( "value" ) );
             dbl_or_var add = get_dbl_or_var( value_obj, "add", false );
             values_add.emplace( value, add );
             dbl_or_var mult = get_dbl_or_var( value_obj, "multiply", false );
             if( value_obj.has_member( "multiply" ) ) {
                 if( value_obj.has_float( "multiply" ) ) {
                     mult.max.dbl_val = mult.min.dbl_val = value_obj.get_float( "multiply" );
                 }
             }
             values_multiply.emplace( value, mult );
         }
     }
     // note: if we add another map to enchantment that looks exactly the same as this,
     // i believe it would then be the time to consider using a template to read this in
     if( !is_child && jo.has_array( "skills" ) ) {
         for( const JsonObject value_obj : jo.get_array( "skills" ) ) {
             const skill_id value = skill_id( value_obj.get_string( "value" ) );
             if( value_obj.has_member( "add" ) ) {
                 dbl_or_var add = get_dbl_or_var( value_obj, "add", false );
                 skill_values_add.emplace( value, add );
             }
             if( value_obj.has_member( "multiply" ) ) {
                 dbl_or_var mult;
                 if( value_obj.has_float( "multiply" ) ) {
                     mult.max.dbl_val = mult.min.dbl_val = value_obj.get_float( "multiply" );
                 } else {
                     mult = get_dbl_or_var( value_obj, "multiply", false );
                 }
                 skill_values_multiply.emplace( value, mult );
             }
         }
     }
 }
References active_conditions, add, add_activation(), dbl_or_var_part::dbl_val, description, dialog_condition, dur, efftype_id, emitter, ench_effects, JsonObject::get_array(), get_dbl_or_var(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), hit_me_effect, hit_you_effect, fake_spell::load(), dbl_or_var::max, dbl_or_var::min, modified_bodyparts, mutations, name, optional(), JsonObject::read(), read_condition(), skill_id, skill_values_add, skill_values_multiply, time_duration::units, values_add, values_multiply, and was_loaded.
Referenced by enchantment::bodypart_changes::deserialize(), enchant_cache::load(), and load_inline_enchantment().
load_enchantment()
void enchantment::load_enchantment (const JsonObject & jo, const std::string & src) static
Definition at line 222 of file magic_enchantment.cpp.
 {
     spell_factory.load( jo, src );
 }
References anonymous_namespace{magic_enchantment.cpp}::spell_factory, and src.
Referenced by DynamicDataLoader::initialize().
load_inline_enchantment()
enchantment_id enchantment::load_inline_enchantment (const JsonValue & jv, std::string_view src, std::string & inline_id) static
Definition at line 232 of file magic_enchantment.cpp.
 {
     if( jv.test_string() ) {
         return enchantment_id( jv.get_string() );
     } else if( jv.test_object() ) {
         if( inline_id.empty() ) {
             jv.throw_error( "Inline enchantment cannot be created without an id." );
         }
         if( spell_factory.is_valid( enchantment_id( inline_id ) ) ) {
             jv.throw_error( "Inline enchantment " + inline_id +
                             " cannot be created as an enchantment already has this id." );
         }
         enchantment inline_enchant;
         inline_enchant.load( jv.get_object(), src, inline_id );
         spell_factory.insert( inline_enchant );
         return enchantment_id( inline_id );
     } else {
         jv.throw_error( "Enchantment needs to be either string or enchantment object." );
     }
 }
References JsonValue::get_object(), JsonValue::get_string(), load(), anonymous_namespace{magic_enchantment.cpp}::spell_factory, src, JsonValue::test_object(), JsonValue::test_string(), and JsonValue::throw_error().
Referenced by mutation_branch::load(), and bionic_data::load().
modifies_bodyparts()
bool enchantment::modifies_bodyparts () const
Definition at line 980 of file magic_enchantment.cpp.
 {
     return !modified_bodyparts.empty();
 }
References modified_bodyparts.
modify_bodyparts()
body_part_set enchantment::modify_bodyparts (const body_part_set & unmodified) const
Definition at line 985 of file magic_enchantment.cpp.
 {
     body_part_set modified( unmodified );
     for( const bodypart_changes &changes : modified_bodyparts ) {
         if( !changes.gain.is_empty() ) {
             modified.set( changes.gain );
         }
         if( !changes.lose.is_empty() ) {
             modified.reset( changes.lose );
         }
     }
     return modified;
 }
References modified_bodyparts, body_part_set::reset(), and body_part_set::set().
reset()
void enchantment::reset () static
Definition at line 227 of file magic_enchantment.cpp.
 {
     spell_factory.reset();
 }
References anonymous_namespace{magic_enchantment.cpp}::spell_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
active_conditions
std::pair<has, condition> enchantment::active_conditions
Definition at line 274 of file magic_enchantment.h.
Referenced by active_wield(), is_active(), load(), enchant_cache::serialize(), enchant_cache::set_has(), and enchant_cache::stacks_with().
description
translation enchantment::description
Definition at line 257 of file magic_enchantment.h.
Referenced by enchant_cache::force_add(), and load().
dialog_condition
std::function<bool(dialogue &)> enchantment::dialog_condition
Definition at line 275 of file magic_enchantment.h.
Referenced by is_active(), and load().
emitter
std::optional<emit_id> enchantment::emitter
Definition at line 250 of file magic_enchantment.h.
Referenced by enchant_cache::activate_passive(), enchant_cache::force_add(), load(), and enchant_cache::serialize().
ench_effects
std::map<efftype_id, int> enchantment::ench_effects
Definition at line 251 of file magic_enchantment.h.
Referenced by enchant_cache::activate_passive(), enchant_cache::clear(), enchant_cache::force_add(), load(), and enchant_cache::serialize().
hit_me_effect
std::vector<fake_spell> enchantment::hit_me_effect
Definition at line 269 of file magic_enchantment.h.
Referenced by enchant_cache::add_hit_me(), enchant_cache::cast_hit_me(), enchant_cache::clear(), enchant_cache::force_add(), load(), and enchant_cache::serialize().
hit_you_effect
std::vector<fake_spell> enchantment::hit_you_effect
Definition at line 270 of file magic_enchantment.h.
Referenced by enchant_cache::add_hit_you(), enchant_cache::cast_hit_you(), enchant_cache::clear(), enchant_cache::force_add(), load(), and enchant_cache::serialize().
id
enchantment_id enchantment::id
Definition at line 224 of file magic_enchantment.h.
Referenced by relic::load(), and enchant_cache::operator==().
intermittent_activation
std::map<time_duration, std::vector<fake_spell> > enchantment::intermittent_activation
Definition at line 272 of file magic_enchantment.h.
Referenced by enchant_cache::activate_passive(), add_activation(), enchant_cache::force_add(), and enchant_cache::serialize().
modified_bodyparts
std::vector<bodypart_changes> enchantment::modified_bodyparts
Definition at line 247 of file magic_enchantment.h.
Referenced by enchant_cache::force_add(), load(), modifies_bodyparts(), modify_bodyparts(), and enchant_cache::serialize().
mutations
std::set<trait_id> enchantment::mutations
Definition at line 249 of file magic_enchantment.h.
Referenced by enchant_cache::force_add(), get_mutations(), load(), and enchant_cache::serialize().
name
translation enchantment::name
Definition at line 254 of file magic_enchantment.h.
Referenced by enchant_cache::force_add(), and load().
skill_values_add
std::map<skill_id, dbl_or_var> enchantment::skill_values_add
Definition at line 266 of file magic_enchantment.h.
Referenced by enchant_cache::clear(), enchant_cache::force_add(), enchant_cache::get_skill_value_add(), enchant_cache::load(), and load().
skill_values_multiply
std::map<skill_id, dbl_or_var> enchantment::skill_values_multiply
Definition at line 267 of file magic_enchantment.h.
Referenced by enchant_cache::clear(), enchant_cache::force_add(), enchant_cache::get_skill_value_multiply(), enchant_cache::load(), and load().
src
std::vector<std::pair<enchantment_id, mod_id> > enchantment::src
Definition at line 226 of file magic_enchantment.h.
Referenced by load_enchantment(), and load_inline_enchantment().
values_add
std::map<enchant_vals::mod, dbl_or_var> enchantment::values_add
Definition at line 260 of file magic_enchantment.h.
Referenced by enchant_cache::add_value_add(), enchant_cache::clear(), enchant_cache::force_add(), enchant_cache::get_value_add(), get_value_add(), is_monster_relevant(), enchant_cache::load(), load(), and enchant_cache::operator==().
values_multiply
std::map<enchant_vals::mod, dbl_or_var> enchantment::values_multiply
Definition at line 263 of file magic_enchantment.h.
Referenced by enchant_cache::add_value_mult(), enchant_cache::clear(), enchant_cache::force_add(), enchant_cache::get_value_multiply(), get_value_multiply(), is_monster_relevant(), enchant_cache::load(), load(), and enchant_cache::operator==().
was_loaded
bool enchantment::was_loaded = false
Definition at line 228 of file magic_enchantment.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/magic_enchantment.h
src/magic_enchantment.cpp