Cataclysm DDA: bionic_install_surgeon_preset Class Reference
bionic_install_surgeon_preset Class Reference
Public Member Functions
bionic_install_surgeon_preset (Character &you, Character &patient)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Protected Attributes
Character & you
Character & pa
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Private Member Functions
std::string get_operation_duration (const item_location &loc)
std::string get_failure_chance (const item_location &loc)
std::string get_money_amount (const item_location &loc)
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Detailed Description
Definition at line 2641 of file game_inventory.cpp.
Constructor & Destructor Documentation
bionic_install_surgeon_preset()
bionic_install_surgeon_preset::bionic_install_surgeon_preset (Character & you, Character & patient) inline
Definition at line 2644 of file game_inventory.cpp.
                                                                             :
             you( you ), pa( patient ) {
             append_cell( [this]( const item_location & loc ) {
                 return get_failure_chance( loc );
             }, _( "FAILURE CHANCE" ) );
             append_cell( [this]( const item_location & loc ) {
                 return get_operation_duration( loc );
             }, _( "OPERATION DURATION" ) );
             append_cell( [this]( const item_location & loc ) {
                 return get_money_amount( loc );
             }, _( "PRICE" ) );
         }
References _, inventory_selector_preset::append_cell(), get_failure_chance(), get_money_amount(), and get_operation_duration().
Member Function Documentation
get_denial()
std::string bionic_install_surgeon_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 2663 of file game_inventory.cpp.
{
             if( you.is_npc() ) {
                 int const price = npc_trading::bionic_install_price( you, pa, loc );
                 ret_val<void> const refusal =
                     you.as_npc()->wants_to_sell( loc, price );
                 if( !refusal.success() ) {
                     return you.replace_with_npc_name( refusal.str() );
                 }
             }
             const ret_val<void> installable = pa.is_installable( loc.get_item(), false );
             return installable.str();
         }
References Creature::as_npc(), npc_trading::bionic_install_price(), item_location::get_item(), Character::is_installable(), Character::is_npc(), pa, Creature::replace_with_npc_name(), ret_val_common::str(), ret_val_common::success(), npc::wants_to_sell(), and you.
get_failure_chance()
std::string bionic_install_surgeon_preset::get_failure_chance (const item_location & loc) inline private
Definition at line 2689 of file game_inventory.cpp.
{
             const int difficulty = loc.get_item()->type->bionic->difficulty;
             int chance_of_failure = 100;
             Character &installer = you;
             if( get_player_character().has_trait( trait_DEBUG_BIONICS ) ||
                 get_player_character().has_flag( json_flag_MANUAL_CBM_INSTALLATION ) ) {
                 chance_of_failure = 0;
             } else {
                 chance_of_failure = 100 - bionic_success_chance( true, 20, difficulty, installer );
             }
             return string_format( _( "%i%%" ), chance_of_failure );
         }
References _, itype::bionic, bionic_success_chance(), item_location::get_item(), get_player_character(), json_flag_MANUAL_CBM_INSTALLATION, string_format(), trait_DEBUG_BIONICS, item::type, and you.
Referenced by bionic_install_surgeon_preset().
get_money_amount()
std::string bionic_install_surgeon_preset::get_money_amount (const item_location & loc) inline private
Definition at line 2705 of file game_inventory.cpp.
{
             return format_money( npc_trading::bionic_install_price( you, pa, loc ) );
         }
References npc_trading::bionic_install_price(), format_money(), pa, and you.
Referenced by bionic_install_surgeon_preset().
get_operation_duration()
std::string bionic_install_surgeon_preset::get_operation_duration (const item_location & loc) inline private
Definition at line 2682 of file game_inventory.cpp.
{
             const int difficulty = loc.get_item()->type->bionic->difficulty;
             // 20 minutes per bionic difficulty.
             return to_string( time_duration::from_minutes( difficulty * 20 ) );
         }
References itype::bionic, time_duration::from_minutes(), item_location::get_item(), to_string(), and item::type.
Referenced by bionic_install_surgeon_preset().
is_shown()
bool bionic_install_surgeon_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 2659 of file game_inventory.cpp.
{
             return ( loc->is_owned_by( you ) || loc->is_owned_by( pa ) ) && loc->is_bionic();
         }
References item::is_bionic(), item::is_owned_by(), pa, and you.
Member Data Documentation
pa
Character& bionic_install_surgeon_preset::pa protected
Definition at line 2678 of file game_inventory.cpp.
Referenced by get_denial(), get_money_amount(), and is_shown().
you
Character& bionic_install_surgeon_preset::you protected
Definition at line 2677 of file game_inventory.cpp.
Referenced by get_denial(), get_failure_chance(), get_money_amount(), and is_shown().
The documentation for this class was generated from the following file:
src/game_inventory.cpp