Cataclysm DDA: mapgen_factory Class Reference
mapgen_factory Class Reference
Public Member Functions
void reset ()
void setup ()
void finalize_parameters ()
void check_consistency () const
bool has (const std::string &key) const
Checks whether we have an entry for the given key.
const mapgen_basic_container * find (const std::string &key) const
int add (const std::string &key, const std::shared_ptr< mapgen_function > &ptr)
bool generate (mapgendata &dat, const std::string &key, const int hardcoded_weight=0)
mapgen_parameters get_map_special_params (const std::string &key) const
Static Private Member Functions
static std::set< std::string > get_usages ()
Collect all the possible and expected keys that may get used with pick.
Private Attributes
std::map< std::string, mapgen_basic_container > mapgens_
Detailed Description
Definition at line 432 of file mapgen.cpp.
Member Function Documentation
add()
int mapgen_factory::add (const std::string & key, const std::shared_ptr< mapgen_function > & ptr) inline
See also
mapgen_basic_container::add
Definition at line 504 of file mapgen.cpp.
{
             return mapgens_[key].add( ptr );
         }
References mapgens_.
Referenced by load_and_add_mapgen_function(), load_mapgen(), and register_mapgen_function().
check_consistency()
void mapgen_factory::check_consistency () const inline
Definition at line 476 of file mapgen.cpp.
{
             // Cache all strings that may get looked up here so we don't have to go through
             // all the sources for them upon each loop.
             const std::set<std::string> usages = get_usages();
             for( const std::pair<const std::string, mapgen_basic_container> &omw : mapgens_ ) {
                 omw.second.check_consistency();
                 if( usages.count( omw.first ) == 0 ) {
                     debugmsg( "Mapgen %s is not used by anything!", omw.first );
                 }
             }
         }
References debugmsg, get_usages(), and mapgens_.
Referenced by check_mapgen_definitions().
finalize_parameters()
void mapgen_factory::finalize_parameters () inline
Definition at line 471 of file mapgen.cpp.
{
             for( std::pair<const std::string, mapgen_basic_container> &omw : mapgens_ ) {
                 omw.second.finalize_parameters();
             }
         }
References mapgens_.
Referenced by calculate_mapgen_weights().
find()
const mapgen_basic_container* mapgen_factory::find (const std::string & key) const inline
Definition at line 495 of file mapgen.cpp.
{
             auto it = mapgens_.find( key );
             if( it == mapgens_.end() ) {
                 return nullptr;
             } else {
                 return &it->second;
             }
         }
References mapgens_.
Referenced by check_mapgen_consistent_with().
generate()
bool mapgen_factory::generate (mapgendata & dat, const std::string & key, const int hardcoded_weight = 0) inline
See also
mapgen_basic_container::generate
Definition at line 508 of file mapgen.cpp.
{
             const auto iter = mapgens_.find( key );
             if( iter == mapgens_.end() ) {
                 return false;
             }
             return iter->second.generate( dat, hardcoded_weight );
         }
References mapgens_.
Referenced by map::draw_lab(), and run_mapgen_func().
get_map_special_params()
mapgen_parameters mapgen_factory::get_map_special_params (const std::string & key) const inline
Definition at line 516 of file mapgen.cpp.
{
             const auto iter = mapgens_.find( key );
             if( iter == mapgens_.end() ) {
                 return mapgen_parameters();
             }
             return iter->second.get_mapgen_params( mapgen_parameter_scope::overmap_special,
                                                    // NOLINTNEXTLINE(cata-translate-string-literal)
                                                    string_format( "map special %s", key ) );
         }
References mapgens_, overmap_special, and string_format().
Referenced by get_map_special_params().
get_usages()
static std::set<std::string> mapgen_factory::get_usages () inline static private
Collect all the possible and expected keys that may get used with pick.
Definition at line 438 of file mapgen.cpp.
{
             std::set<std::string> result;
             for( const oter_t &elem : overmap_terrains::get_all() ) {
                 result.insert( elem.get_mapgen_id() );
                 result.insert( elem.id.str() );
             }
             // Why do I have to repeat the MapExtras here? Wouldn't "MapExtras::factory" be enough?
             for( const map_extra &elem : MapExtras::mapExtraFactory().get_all() ) {
                 if( elem.generator_method == map_extra_method::mapgen ) {
                     result.insert( elem.generator_id );
                 }
             }
             // Used in C++ code only, see calls to `oter_mapgen.generate()` below
             result.insert( "lab_1side" );
             result.insert( "lab_4side" );
             result.insert( "lab_finale_1level" );
             return result;
         }
References ammo_effects::get_all(), overmap_terrains::get_all(), MapExtras::mapExtraFactory(), and mapgen.
Referenced by check_consistency().
has()
bool mapgen_factory::has (const std::string & key) const inline
Checks whether we have an entry for the given key.
Note that the entry itself may not contain any valid mapgen instance (could all have been removed via erase).
Definition at line 492 of file mapgen.cpp.
{
             return mapgens_.count( key ) != 0;
         }
References mapgens_.
Referenced by has_mapgen_for().
reset()
void mapgen_factory::reset () inline
Definition at line 458 of file mapgen.cpp.
                      {
             mapgens_.clear();
         }
References mapgens_.
Referenced by reset_mapgens().
setup()
void mapgen_factory::setup () inline
See also
mapgen_basic_container::setup
Definition at line 462 of file mapgen.cpp.
                      {
             for( std::pair<const std::string, mapgen_basic_container> &omw : mapgens_ ) {
                 omw.second.setup();
                 inp_mngr.pump_events();
             }
             // Dummy entry, overmap terrain null should never appear and is
             // therefore never generated.
             mapgens_.erase( "null" );
         }
References inp_mngr, mapgens_, and input_manager::pump_events().
Referenced by calculate_mapgen_weights().
Member Data Documentation
mapgens_
std::map<std::string, mapgen_basic_container> mapgen_factory::mapgens_ private
Definition at line 435 of file mapgen.cpp.
Referenced by add(), check_consistency(), finalize_parameters(), find(), generate(), get_map_special_params(), has(), reset(), and setup().
The documentation for this class was generated from the following file:
src/mapgen.cpp