Cataclysm DDA: achievements_tracker Class Reference
achievements_tracker Class Reference
#include <achievement.h>
Public Member Functions
achievements_tracker (const achievements_tracker &)=delete
achievements_tracker & operator= (const achievements_tracker &)=delete
achievements_tracker (stats_tracker &, const std::function< void(const achievement *, bool)> &achievement_attained_callback, const std::function< void(const achievement *, bool)> &achievement_failed_callback, bool active)
~achievements_tracker () override
std::vector< const achievement * > valid_achievements () const
void report_achievement (const achievement *, achievement_completion)
void write_json_achievements (std::ostream &achievement_file, const std::string &avatar_name) const
achievement_completion is_completed (const achievement_id &) const
bool is_hidden (const achievement *) const
std::string ui_text_for (const achievement *) const
bool is_enabled () const
void set_enabled (bool enabled)
void clear ()
void notify (const cata::event &) override
void serialize (JsonOut &) const
void deserialize (const JsonObject &jo)
virtual void notify (const cata::event &)=0
virtual void notify (const cata::event &, std::unique_ptr< talker >, std::unique_ptr< talker >)
Public Member Functions inherited from event_subscriber
event_subscriber ()=default
event_subscriber (const event_subscriber &)=delete
event_subscriber & operator= (const event_subscriber &)=delete
virtual ~event_subscriber ()
virtual void notify (const cata::event &, std::unique_ptr< talker >, std::unique_ptr< talker >)
Private Member Functions
void init_watchers ()
Private Attributes
stats_tracker * stats_ = nullptr
bool enabled_ = true
bool active_
std::function< void(const achievement *, bool)> achievement_attained_callback_
std::function< void(const achievement *, bool)> achievement_failed_callback_
std::unordered_set< achievement_id > initial_achievements_
std::unordered_map< achievement_id, achievement_tracker > trackers_
std::unordered_map< achievement_id, achievement_state > achievements_status_
Detailed Description
Definition at line 189 of file achievement.h.
Constructor & Destructor Documentation
achievements_tracker() [1/2]
achievements_tracker::achievements_tracker (const achievements_tracker &) delete
achievements_tracker() [2/2]
achievements_tracker::achievements_tracker (stats_tracker & stats, const std::function< void(const achievement *, bool)> & achievement_attained_callback, const std::function< void(const achievement *, bool)> & achievement_failed_callback, bool active)
Parameters
active Whether this achievements_tracker needs to create watchers for the stats_tracker to monitor ongoing events. If only using the achievements_tracker for analyzing past achievements, this should not be necessary.
Definition at line 768 of file achievement.cpp.
                   :
     stats_( &stats ),
     active_( active ),
     achievement_attained_callback_( achievement_attained_callback ),
     achievement_failed_callback_( achievement_failed_callback )
 {}
~achievements_tracker()
achievements_tracker::~achievements_tracker () override default
Member Function Documentation
clear()
void achievements_tracker::clear ()
Definition at line 887 of file achievement.cpp.
 {
     enabled_ = true;
     trackers_.clear();
     initial_achievements_.clear();
     achievements_status_.clear();
 }
References achievements_status_, enabled_, initial_achievements_, and trackers_.
deserialize()
void achievements_tracker::deserialize (const JsonObject & jo)
Definition at line 915 of file achievement.cpp.
 {
     if( !jo.read( "enabled", enabled_ ) ) {
         enabled_ = true;
     }
     jo.read( "initial_achievements", initial_achievements_ );
     jo.read( "achievements_status", achievements_status_ );
     init_watchers();
 }
References achievements_status_, enabled_, init_watchers(), initial_achievements_, and JsonObject::read().
init_watchers()
void achievements_tracker::init_watchers () private
Definition at line 926 of file achievement.cpp.
 {
     if( !active_ ) {
         return;
     }
     for( const achievement *a : valid_achievements() ) {
         if( achievements_status_.count( a->id ) ) {
             continue;
         }
         trackers_.emplace(
             std::piecewise_construct, std::forward_as_tuple( a->id ),
             std::forward_as_tuple( *a, *this, *stats_ ) );
     }
 }
References a, achievements_status_, active_, stats_, trackers_, and valid_achievements().
Referenced by deserialize(), and notify().
is_completed()
achievement_completion achievements_tracker::is_completed (const achievement_id & id) const
Definition at line 814 of file achievement.cpp.
 {
     auto it = achievements_status_.find( id );
     if( it == achievements_status_.end() ) {
         // It might still have failed; check for time expiry
         auto tracker_it = trackers_.find( id );
         if( tracker_it != trackers_.end() && tracker_it->second.time_is_expired() ) {
             return achievement_completion::failed;
         }
         return achievement_completion::pending;
     }
     return it->second.completion;
 }
References achievements_status_, failed, pending, and trackers_.
Referenced by is_hidden().
is_enabled()
bool achievements_tracker::is_enabled () const inline
Definition at line 220 of file achievement.h.
{
             return enabled_;
         }
References enabled_.
Referenced by debug_menu::debug(), get_achievements_text(), and report_achievement().
is_hidden()
bool achievements_tracker::is_hidden (const achievement * ach) const
Definition at line 828 of file achievement.cpp.
 {
     // hard code for arcade mode achievement
     if( ach->id == achievement_achievement_arcade_mode ) {
         return true;
     }
     achievement_completion end_state =
         ach->is_conduct() ? achievement_completion::failed : achievement_completion::completed;
     if( is_completed( ach->id ) == end_state ) {
         return false;
     }
     for( const achievement_id &hidden_by : ach->hidden_by() ) {
         if( is_completed( hidden_by ) != end_state ) {
             return true;
         }
     }
     return false;
 }
References achievement_achievement_arcade_mode, completed, failed, achievement::hidden_by(), achievement::id, is_completed(), and achievement::is_conduct().
notify() [1/3]
void achievements_tracker::notify (const cata::event & e) override virtual
Implements event_subscriber.
Definition at line 895 of file achievement.cpp.
 {
     if( e.type() == event_type::game_start ) {
         cata_assert( initial_achievements_.empty() );
         for( const achievement &ach : achievement::get_all() ) {
             initial_achievements_.insert( ach.id );
         }
         init_watchers();
     }
 }
References cata_assert, game_start, achievement::get_all(), init_watchers(), initial_achievements_, and cata::event::type().
notify() [2/3]
virtual void event_subscriber::notify
notify() [3/3]
void event_subscriber::notify
Definition at line 22 of file event_bus.cpp.
 {
     notify( e );
 }
operator=()
achievements_tracker& achievements_tracker::operator= (const achievements_tracker &) delete
report_achievement()
void achievements_tracker::report_achievement (const achievement * a, achievement_completion comp)
Definition at line 792 of file achievement.cpp.
 {
     cata_assert( comp != achievement_completion::pending );
     cata_assert( !achievements_status_.count( a->id ) );
     auto tracker_it = trackers_.find( a->id );
     achievements_status_.emplace(
         a->id,
     achievement_state{
         comp,
         calendar::turn,
         tracker_it->second.current_values()
     }
     );
     trackers_.erase( tracker_it );
     if( comp == achievement_completion::completed ) {
         achievement_attained_callback_( a, is_enabled() );
     } else if( comp == achievement_completion::failed ) {
         achievement_failed_callback_( a, is_enabled() );
     }
 }
References a, achievement_attained_callback_, achievement_failed_callback_, achievements_status_, cata_assert, completed, failed, is_enabled(), pending, and trackers_.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_achievment(), achievement_tracker::set_requirement(), and debug_menu::unlock_all().
serialize()
void achievements_tracker::serialize (JsonOut & jsout) const
Definition at line 906 of file achievement.cpp.
 {
     jsout.start_object();
     jsout.member( "enabled", enabled_ );
     jsout.member( "initial_achievements", initial_achievements_ );
     jsout.member( "achievements_status", achievements_status_ );
     jsout.end_object();
 }
References achievements_status_, enabled_, JsonOut::end_object(), initial_achievements_, JsonOut::member(), and JsonOut::start_object().
set_enabled()
void achievements_tracker::set_enabled (bool enabled) inline
Definition at line 223 of file achievement.h.
{
             enabled_ = enabled;
         }
References enabled, and enabled_.
Referenced by debug_menu::debug().
ui_text_for()
std::string achievements_tracker::ui_text_for (const achievement * ach) const
Definition at line 873 of file achievement.cpp.
 {
     auto state_it = achievements_status_.find( ach->id );
     if( state_it != achievements_status_.end() ) {
         return state_it->second.ui_text( ach );
     }
     auto tracker_it = trackers_.find( ach->id );
     if( tracker_it == trackers_.end() ) {
         return colorize( ach->description() + _( "\nInternal error: achievement lacks watcher." ),
                          c_red );
     }
     return tracker_it->second.ui_text();
 }
References _, achievements_status_, c_red, colorize(), achievement::description(), achievement::id, and trackers_.
Referenced by achievement_attained(), and get_achievements_text().
valid_achievements()
std::vector< const achievement * > achievements_tracker::valid_achievements () const
Definition at line 781 of file achievement.cpp.
 {
     std::vector<const achievement *> result;
     for( const achievement &ach : achievement::get_all() ) {
         if( initial_achievements_.count( ach.id ) ) {
             result.push_back( &ach );
         }
     }
     return result;
 }
References achievement::get_all(), and initial_achievements_.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_achievment(), get_achievements_text(), and init_watchers().
write_json_achievements()
void achievements_tracker::write_json_achievements (std::ostream & achievement_file, const std::string & avatar_name) const
Definition at line 849 of file achievement.cpp.
 {
     JsonOut jsout( achievement_file, true, 2 );
     jsout.start_object();
     jsout.member( "achievement_version", 1 );
     std::vector<achievement_id> ach_ids;
     for( const auto &kv : achievements_status_ ) {
         if( kv.second.completion == achievement_completion::completed ) {
             ach_ids.push_back( kv.first );
         }
     }
     jsout.member( "achievements", ach_ids );
     jsout.member( "avatar_name", avatar_name );
     jsout.end_object();
     // Clear past achievements so that it will be reloaded
     clear_past_achievements();
 }
References achievements_status_, clear_past_achievements(), completed, JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Referenced by game::save_achievements().
Member Data Documentation
achievement_attained_callback_
std::function<void(const achievement *, bool)> achievements_tracker::achievement_attained_callback_ private
Definition at line 243 of file achievement.h.
Referenced by report_achievement().
achievement_failed_callback_
std::function<void(const achievement *, bool)> achievements_tracker::achievement_failed_callback_ private
Definition at line 245 of file achievement.h.
Referenced by report_achievement().
achievements_status_
std::unordered_map<achievement_id, achievement_state> achievements_tracker::achievements_status_ private
Definition at line 251 of file achievement.h.
Referenced by clear(), deserialize(), init_watchers(), is_completed(), report_achievement(), serialize(), ui_text_for(), and write_json_achievements().
active_
bool achievements_tracker::active_ private
Definition at line 241 of file achievement.h.
Referenced by init_watchers().
enabled_
bool achievements_tracker::enabled_ = true private
Definition at line 237 of file achievement.h.
Referenced by clear(), deserialize(), is_enabled(), serialize(), and set_enabled().
initial_achievements_
std::unordered_set<achievement_id> achievements_tracker::initial_achievements_ private
Definition at line 246 of file achievement.h.
Referenced by clear(), deserialize(), notify(), serialize(), and valid_achievements().
stats_
stats_tracker* achievements_tracker::stats_ = nullptr private
Definition at line 236 of file achievement.h.
Referenced by init_watchers().
trackers_
std::unordered_map<achievement_id, achievement_tracker> achievements_tracker::trackers_ private
Definition at line 250 of file achievement.h.
Referenced by clear(), init_watchers(), is_completed(), report_achievement(), and ui_text_for().
The documentation for this class was generated from the following files:
src/achievement.h
src/achievement.cpp