Cataclysm DDA: hacking_activity_actor Class Reference
hacking_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
hacking_activity_actor (const item_location &tool)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
item_location tool
Detailed Description
Definition at line 210 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
hacking_activity_actor()
hacking_activity_actor::hacking_activity_actor (const item_location & tool) inline explicit
Definition at line 213 of file activity_actor_definitions.h.
 : tool( tool ) {};
Member Function Documentation
clone()
std::unique_ptr<activity_actor> hacking_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 223 of file activity_actor_definitions.h.
{
             return std::make_unique<hacking_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > hacking_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 870 of file activity_actor.cpp.
 {
     hacking_activity_actor actor( {} );
     JsonObject data = jsin.get_object();
     data.read( "tool", actor.tool );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void hacking_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 220 of file activity_actor_definitions.h.
 {}
finish()
void hacking_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 808 of file activity_actor.cpp.
 {
     // TODO: fix point types
     tripoint examp = get_map().getlocal( act.placement );
     hack_type type = get_hack_type( examp );
     switch( hack_attempt( who, tool ) ) {
         case hack_result::UNABLE:
             who.add_msg_if_player( _( "You cannot hack this." ) );
             break;
         case hack_result::FAIL:
             // currently all things that can be hacked have equivalent alarm failure states.
             // this may not always be the case with new hackable things.
             get_event_bus().send<event_type::triggers_alarm>( who.getID() );
             sounds::sound( who.pos(), 60, sounds::sound_t::music, _( "an alarm sound!" ), true, "environment",
                            "alarm" );
             break;
         case hack_result::NOTHING:
             who.add_msg_if_player( _( "You fail the hack, but no alarms are triggered." ) );
             break;
         case hack_result::SUCCESS:
             map &here = get_map();
             if( type == hack_type::GAS ) {
                 int tankUnits;
                 fuel_station_fuel_type fuelType;
                 const std::optional<tripoint> pTank_ = iexamine::getNearFilledGasTank( examp, tankUnits,
                                                        fuelType );
                 if( !pTank_ ) {
                     break;
                 }
                 const tripoint pTank = *pTank_;
                 const std::optional<tripoint> pGasPump = iexamine::getGasPumpByNumber( examp,
                         uistate.ags_pay_gas_selected_pump );
                 if( pGasPump && iexamine::toPumpFuel( pTank, *pGasPump, tankUnits ) ) {
                     who.add_msg_if_player( _( "You hack the terminal and route all available fuel to your pump!" ) );
                     sounds::sound( examp, 6, sounds::sound_t::activity,
                                    _( "Glug Glug Glug Glug Glug Glug Glug Glug Glug" ), true, "tool", "gaspump" );
                 } else {
                     who.add_msg_if_player( _( "Nothing happens." ) );
                 }
             } else if( type == hack_type::SAFE ) {
                 who.add_msg_if_player( m_good, _( "The door on the safe swings open." ) );
                 here.furn_set( examp, furn_f_safe_o );
             } else if( type == hack_type::DOOR ) {
                 who.add_msg_if_player( _( "You activate the panel!" ) );
                 who.add_msg_if_player( m_good, _( "The nearby doors unlock." ) );
                 here.ter_set( examp, ter_t_card_reader_broken );
                 for( const tripoint &tmp : here.points_in_radius( examp, 3 ) ) {
                     if( here.ter( tmp ) == ter_t_door_metal_locked ) {
                         here.ter_set( tmp, ter_t_door_metal_c );
                     }
                 }
             }
             break;
     }
     act.set_to_null();
 }
References _, act, sounds::activity, Character::add_msg_if_player(), uistatedata::ags_pay_gas_selected_pump, DOOR, FAIL, furn_f_safe_o, map::furn_set(), GAS, get_event_bus(), get_hack_type(), get_map(), iexamine::getGasPumpByNumber(), Character::getID(), map::getlocal(), iexamine::getNearFilledGasTank(), hack_attempt(), m_good, sounds::music, NOTHING, map::points_in_radius(), Creature::pos(), SAFE, event_bus::send(), sounds::sound(), SUCCESS, map::ter(), map::ter_set(), ter_t_card_reader_broken, ter_t_door_metal_c, ter_t_door_metal_locked, tool, iexamine::toPumpFuel(), triggers_alarm, type, uistate, and UNABLE.
get_progress_message()
std::string hacking_activity_actor::get_progress_message (const player_activity & act) const inline override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 227 of file activity_actor_definitions.h.
{
             return std::string();
         }
get_type()
activity_id hacking_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 215 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_HACKING" );
         }
References activity_id.
serialize()
void hacking_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 865 of file activity_actor.cpp.
 {
     jsout.write_null();
 }
References JsonOut::write_null().
start()
void hacking_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 730 of file activity_actor.cpp.
 {
     act.moves_total = to_moves<int>( 5_minutes );
     act.moves_left = to_moves<int>( 5_minutes );
 }
References act.
Member Data Documentation
tool
item_location hacking_activity_actor::tool private
Definition at line 234 of file activity_actor_definitions.h.
Referenced by finish().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp