Cataclysm DDA: activity_tracker Class Reference
activity_tracker Class Reference
#include <activity_tracker.h>
Public Member Functions
void log_activity (float new_level)
void new_turn (bool sleeping=false)
void reset_activity_level ()
std::string activity_level_str () const
float activity (bool sleeping=false) const
float average_activity () const
float instantaneous_activity_level () const
int weariness () const
void try_reduce_weariness (int bmr, float sleepiness_mod, float sleepiness_regen_mod)
void calorie_adjust (int ncal)
void weary_clear ()
void set_intake (int ncal)
std::string debug_weary_info () const
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
Public Attributes
int tracker = 0
int intake = 0
Private Attributes
float current_activity = 0.0
float accumulated_activity = 0.0
float previous_activity = 0.0
float previous_turn_activity = 0.0
time_point current_turn = calendar::turn_zero
bool activity_reset = true
int num_events = 1
float low_activity_ticks = 0.0f
Detailed Description
Definition at line 12 of file activity_tracker.h.
Member Function Documentation
activity()
float activity_tracker::activity (bool sleeping = false) const
Definition at line 88 of file activity_tracker.cpp.
 {
     if( current_turn == calendar::turn ) {
         return current_activity;
     } else if( sleeping ) {
         return SLEEP_EXERCISE;
     } else {
         return NO_EXERCISE;
     }
 }
References current_activity, current_turn, NO_EXERCISE, SLEEP_EXERCISE, and calendar::turn.
Referenced by Character::activity_level(), Character::exertion_adjusted_move_multiplier(), and suffer::from_exertion().
activity_level_str()
std::string activity_tracker::activity_level_str () const
Definition at line 156 of file activity_tracker.cpp.
 {
     for( const std::pair<const float, std::string> &member : activity_levels_str_map ) {
         if( current_activity <= member.first ) {
             return member.second;
         }
     }
     return ( --activity_levels_str_map.end() )->second;
 }
References activity_levels_str_map, current_activity, and member.
Referenced by Character::activity_level_str().
average_activity()
float activity_tracker::average_activity () const
Definition at line 99 of file activity_tracker.cpp.
 {
     if( activity_reset && current_turn != calendar::turn ) {
         return previous_activity / num_events;
     }
     return ( accumulated_activity + current_activity ) / num_events;
 }
References accumulated_activity, activity_reset, current_activity, current_turn, num_events, previous_activity, and calendar::turn.
Referenced by Character::get_bmr(), try_reduce_weariness(), and Character::update_stomach().
calorie_adjust()
void activity_tracker::calorie_adjust (int ncal)
Definition at line 78 of file activity_tracker.cpp.
 {
     if( ncal > 0 ) {
         intake += ncal;
     } else {
         // ncal is negative, we need positive
         tracker -= ncal;
     }
 }
References intake, and tracker.
Referenced by Character::mod_stored_calories().
debug_weary_info()
std::string activity_tracker::debug_weary_info () const
Definition at line 73 of file activity_tracker.cpp.
 {
     return string_format( "Intake: %.1f Tracker: %.1f", intake / 1000.0f, tracker / 1000.0f );
 }
References intake, string_format(), and tracker.
Referenced by Character::debug_weary_info().
deserialize()
void activity_tracker::deserialize (const JsonObject & jo)
Definition at line 611 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     jo.read( "current_activity", current_activity );
     jo.read( "accumulated_activity", accumulated_activity );
     jo.read( "previous_activity", previous_activity );
     jo.read( "previous_turn_activity", previous_turn_activity );
     jo.read( "current_turn", current_turn );
     jo.read( "activity_reset", activity_reset );
     jo.read( "num_events", num_events );
     jo.read( "tracker", tracker );
     jo.read( "intake", intake );
     jo.read( "low_activity_ticks", low_activity_ticks );
     if( jo.has_member( "tick_counter" ) ) { // migration - remove after 0.G
         tracker *= 1000;
         intake *= 1000;
     }
 }
References JsonObject::allow_omitted_members(), JsonObject::has_member(), and JsonObject::read().
instantaneous_activity_level()
float activity_tracker::instantaneous_activity_level () const
Definition at line 107 of file activity_tracker.cpp.
 {
     if( current_turn == calendar::turn ) {
         return current_activity;
     }
     return previous_turn_activity;
 }
References current_activity, current_turn, previous_turn_activity, and calendar::turn.
Referenced by Character::instantaneous_activity_level().
log_activity()
void activity_tracker::log_activity (float new_level)
Definition at line 119 of file activity_tracker.cpp.
 {
     current_activity = std::max( current_activity, new_level );
     current_turn = calendar::turn;
 }
References current_activity, current_turn, max(), and calendar::turn.
Referenced by Character::set_activity_level().
new_turn()
void activity_tracker::new_turn (bool sleeping = false)
Definition at line 125 of file activity_tracker.cpp.
 {
     float base_activity_level = sleeping ? SLEEP_EXERCISE : NO_EXERCISE;
     if( activity_reset ) {
         activity_reset = false;
         previous_turn_activity = current_activity;
         current_activity = base_activity_level;
         accumulated_activity = 0.0f;
         num_events = 1;
     } else {
         // This is for the last turn that had activity logged.
         accumulated_activity += current_activity;
         // Then handle the interventing turns that had no activity logged.
         int num_turns = to_turns<int>( calendar::turn - current_turn );
         if( num_turns > 1 ) {
             accumulated_activity += ( num_turns - 1 ) * std::min( NO_EXERCISE, current_activity );
             num_events += num_turns - 1;
         }
         previous_turn_activity = current_activity;
         current_activity = base_activity_level;
         num_events++;
     }
 }
References accumulated_activity, activity_reset, current_activity, current_turn, min(), NO_EXERCISE, num_events, previous_turn_activity, SLEEP_EXERCISE, and calendar::turn.
Referenced by Character::update_body().
reset_activity_level()
void activity_tracker::reset_activity_level ()
Definition at line 150 of file activity_tracker.cpp.
 {
     previous_activity = accumulated_activity;
     activity_reset = true;
 }
References accumulated_activity, activity_reset, and previous_activity.
Referenced by Character::reset_activity_level(), and Character::update_body().
serialize()
void activity_tracker::serialize (JsonOut & json) const
Definition at line 594 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "current_activity", current_activity );
     json.member( "accumulated_activity", accumulated_activity );
     json.member( "previous_activity", previous_activity );
     json.member( "previous_turn_activity", previous_turn_activity );
     json.member( "current_turn", current_turn );
     json.member( "activity_reset", activity_reset );
     json.member( "num_events", num_events );
     json.member( "tracker", tracker );
     json.member( "intake", intake );
     json.member( "low_activity_ticks", low_activity_ticks );
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
set_intake()
void activity_tracker::set_intake (int ncal)
Definition at line 68 of file activity_tracker.cpp.
 {
     intake = ncal;
 }
References intake.
try_reduce_weariness()
void activity_tracker::try_reduce_weariness (int bmr, float sleepiness_mod, float sleepiness_regen_mod)
Definition at line 22 of file activity_tracker.cpp.
 {
     if( average_activity() < LIGHT_EXERCISE ) {
         cata_assert( sleepiness_mod > 0.0f );
         low_activity_ticks += std::min( 1.0f, ( ( LIGHT_EXERCISE - average_activity() ) /
                                                 ( LIGHT_EXERCISE - NO_EXERCISE ) ) ) / sleepiness_mod;
         // Recover (by default) twice as fast while sleeping
         if( average_activity() < NO_EXERCISE ) {
             low_activity_ticks += ( ( NO_EXERCISE - average_activity() ) /
                                     ( NO_EXERCISE - SLEEP_EXERCISE ) ) * sleepiness_regen_mod;
         }
     }
     const float recovery_mult = get_option<float>( "WEARY_RECOVERY_MULT" );
     const int bmr_cal = bmr * 1000;
     if( low_activity_ticks >= 1.0f ) {
         int reduction = tracker;
         // 1/120 of whichever's bigger
         if( bmr_cal > reduction ) {
             reduction = std::floor( bmr_cal * recovery_mult * low_activity_ticks / 6.0f );
         } else {
             reduction = std::ceil( reduction * recovery_mult * low_activity_ticks / 6.0f );
         }
         low_activity_ticks = 0.0f;
         tracker -= std::max( reduction, 1 );
     }
     // If happens to be no reduction, character is not (as) hypoglycemic
     intake = static_cast<int>( intake * std::pow( 1 - recovery_mult, ( 1.0f / 12.0f ) ) );
     // Normalize values, make sure we stay above 0
     intake = std::max( intake, 0 );
     tracker = std::max( tracker, 0 );
     low_activity_ticks = std::max( low_activity_ticks, 0.0f );
 }
References average_activity(), cata_assert, ceil(), floor(), intake, LIGHT_EXERCISE, low_activity_ticks, max(), min(), NO_EXERCISE, SLEEP_EXERCISE, and tracker.
Referenced by Character::update_body().
weariness()
int activity_tracker::weariness () const
Definition at line 13 of file activity_tracker.cpp.
 {
     if( intake > tracker ) {
         return tracker / 2000;
     }
     return ( tracker - intake * 0.5 ) / 1000;
 }
References intake, and tracker.
Referenced by Character::debug_weary_info(), and Character::weariness().
weary_clear()
void activity_tracker::weary_clear ()
Definition at line 61 of file activity_tracker.cpp.
 {
     tracker = 0;
     intake = 0;
     low_activity_ticks = 0.0f;
 }
References intake, low_activity_ticks, and tracker.
Referenced by debug_menu::character_edit_needs_menu(), and Character::normalize().
Member Data Documentation
accumulated_activity
float activity_tracker::accumulated_activity = 0.0 private
Definition at line 16 of file activity_tracker.h.
Referenced by average_activity(), new_turn(), and reset_activity_level().
activity_reset
bool activity_tracker::activity_reset = true private
Definition at line 20 of file activity_tracker.h.
Referenced by average_activity(), new_turn(), and reset_activity_level().
current_activity
float activity_tracker::current_activity = 0.0 private
Definition at line 15 of file activity_tracker.h.
Referenced by activity(), activity_level_str(), average_activity(), instantaneous_activity_level(), log_activity(), and new_turn().
current_turn
time_point activity_tracker::current_turn = calendar::turn_zero private
Definition at line 19 of file activity_tracker.h.
Referenced by activity(), average_activity(), instantaneous_activity_level(), log_activity(), and new_turn().
intake
int activity_tracker::intake = 0
Definition at line 28 of file activity_tracker.h.
Referenced by calorie_adjust(), debug_weary_info(), set_intake(), try_reduce_weariness(), weariness(), and weary_clear().
low_activity_ticks
float activity_tracker::low_activity_ticks = 0.0f private
Definition at line 25 of file activity_tracker.h.
Referenced by try_reduce_weariness(), and weary_clear().
num_events
int activity_tracker::num_events = 1 private
Definition at line 21 of file activity_tracker.h.
Referenced by average_activity(), and new_turn().
previous_activity
float activity_tracker::previous_activity = 0.0 private
Definition at line 17 of file activity_tracker.h.
Referenced by average_activity(), and reset_activity_level().
previous_turn_activity
float activity_tracker::previous_turn_activity = 0.0 private
Definition at line 18 of file activity_tracker.h.
Referenced by instantaneous_activity_level(), and new_turn().
tracker
int activity_tracker::tracker = 0
Definition at line 27 of file activity_tracker.h.
Referenced by calorie_adjust(), debug_weary_info(), try_reduce_weariness(), weariness(), and weary_clear().
The documentation for this class was generated from the following files:
src/activity_tracker.h
src/activity_tracker.cpp
src/savegame_json.cpp