Cataclysm DDA: TextJsonArray Class Reference
TextJsonArray Class Reference
#include <json.h>
Classes
class const_iterator
Public Member Functions
TextJsonArray (TextJsonIn &jsin)
TextJsonArray (const TextJsonArray &ja)
TextJsonArray ()
~TextJsonArray ()
TextJsonArray & operator= (const TextJsonArray &)
void finish ()
bool has_more () const
size_t size () const
bool empty ()
std::string str ()
void throw_error (const std::string &err) const
void throw_error (int idx, const std::string &err) const
void string_error (int idx, int offset, const std::string &err) const
TextJsonValue next_value ()
bool next_bool ()
int next_int ()
double next_float ()
std::string next_string ()
TextJsonArray next_array ()
TextJsonObject next_object ()
void skip_value ()
bool get_bool (size_t index) const
int get_int (size_t index) const
double get_float (size_t index) const
std::string get_string (size_t index) const
TextJsonArray get_array (size_t index) const
TextJsonObject get_object (size_t index) const
template<typename T = std::string, typename Res = std::set<T>>
Res get_tags (size_t index) const
const_iterator begin () const
const_iterator end () const
bool test_null () const
bool test_bool () const
bool test_number () const
bool test_int () const
bool test_float () const
bool test_string () const
bool test_bitset () const
bool test_array () const
bool test_object () const
bool has_null (size_t index) const
bool has_bool (size_t index) const
bool has_number (size_t index) const
bool has_int (size_t index) const
bool has_float (size_t index) const
bool has_string (size_t index) const
bool has_array (size_t index) const
bool has_object (size_t index) const
template<typename T >
bool read_next (T &t)
template<typename T >
bool read (size_t i, T &t, bool throw_on_error=false) const
Private Member Functions
void verify_index (size_t i) const
Private Attributes
std::vector< size_t > positions
int start
size_t index
int end_
bool final_separator
TextJsonIn * jsin
Detailed Description
Definition at line 1242 of file json.h.
Constructor & Destructor Documentation
TextJsonArray() [1/3]
TextJsonArray::TextJsonArray (TextJsonIn & jsin) explicit
Definition at line 516 of file json.cpp.
 {
     jsin = &j;
     start = jsin->tell();
     index = 0;
     // cache the position of each element
     jsin->start_array();
     while( !jsin->end_array() ) {
         positions.push_back( jsin->tell() );
         jsin->skip_value();
     }
     end_ = jsin->tell();
     final_separator = jsin->get_ate_separator();
 }
References end_, TextJsonIn::end_array(), final_separator, TextJsonIn::get_ate_separator(), index, jsin, positions, TextJsonIn::skip_value(), start, TextJsonIn::start_array(), and TextJsonIn::tell().
TextJsonArray() [2/3]
TextJsonArray::TextJsonArray (const TextJsonArray & ja)
Definition at line 531 of file json.cpp.
 {
     *this = ja;
 }
TextJsonArray() [3/3]
TextJsonArray::TextJsonArray () inline
Definition at line 1256 of file json.h.
 : start( 0 ), index( 0 ), end_( 0 ), final_separator( false ), jsin( nullptr ) {}
~TextJsonArray()
TextJsonArray::~TextJsonArray () inline
Definition at line 1257 of file json.h.
{
             finish();
         }
References finish().
Member Function Documentation
begin()
TextJsonArray::const_iterator TextJsonArray::begin () const inline
Definition at line 1463 of file json.h.
 {
     return const_iterator( *this, 0 );
 }
empty()
bool TextJsonArray::empty ()
Definition at line 565 of file json.cpp.
 {
     return positions.empty();
 }
References positions.
end()
TextJsonArray::const_iterator TextJsonArray::end () const inline
Definition at line 1468 of file json.h.
 {
     return const_iterator( *this, size() );
 }
References size().
finish()
void TextJsonArray::finish ()
Definition at line 549 of file json.cpp.
 {
     if( jsin && jsin->good() ) {
         jsin->seek( end_ );
         jsin->set_ate_separator( final_separator );
     }
 }
References end_, final_separator, TextJsonIn::good(), jsin, TextJsonIn::seek(), and TextJsonIn::set_ate_separator().
Referenced by ~TextJsonArray().
get_array()
TextJsonArray TextJsonArray::get_array (size_t index) const
Definition at line 678 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->get_array();
 }
References TextJsonIn::get_array(), jsin, positions, TextJsonIn::seek(), and verify_index().
Referenced by TextJsonValue::operator TextJsonArray().
get_bool()
bool TextJsonArray::get_bool (size_t index) const
Definition at line 650 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->get_bool();
 }
References TextJsonIn::get_bool(), jsin, positions, TextJsonIn::seek(), and verify_index().
get_float()
double TextJsonArray::get_float (size_t index) const
Definition at line 664 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->get_float();
 }
References TextJsonIn::get_float(), jsin, positions, TextJsonIn::seek(), and verify_index().
get_int()
int TextJsonArray::get_int (size_t index) const
Definition at line 657 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->get_int();
 }
References TextJsonIn::get_int(), jsin, positions, TextJsonIn::seek(), and verify_index().
get_object()
TextJsonObject TextJsonArray::get_object (size_t index) const
Definition at line 685 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->get_object();
 }
References TextJsonIn::get_object(), jsin, positions, TextJsonIn::seek(), and verify_index().
get_string()
std::string TextJsonArray::get_string (size_t index) const
Definition at line 671 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->get_string();
 }
References TextJsonIn::get_string(), jsin, positions, TextJsonIn::seek(), and verify_index().
get_tags()
template<typename T , typename Res > Res TextJsonArray::get_tags (size_t index) const
Definition at line 1542 of file json.h.
 {
     Res res;
     verify_index( index );
     jsin->seek( positions[ index ] );
     // allow single string as tag
     if( jsin->test_string() ) {
         res.insert( T( jsin->get_string() ) );
         return res;
     }
     for( const std::string line : jsin->get_array() ) {
         if( !res.insert( T( line ) ).second ) {
             jsin->error( "duplicate item in set defined by json array" );
         }
     }
     return res;
 }
References TextJsonIn::error(), TextJsonIn::get_array(), TextJsonIn::get_string(), index, jsin, line, positions, second, TextJsonIn::seek(), TextJsonIn::test_string(), and verify_index().
has_array()
bool TextJsonArray::has_array (size_t index) const
Definition at line 787 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->test_array();
 }
References jsin, positions, TextJsonIn::seek(), TextJsonIn::test_array(), and verify_index().
has_bool()
bool TextJsonArray::has_bool (size_t index) const
Definition at line 766 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->test_bool();
 }
References jsin, positions, TextJsonIn::seek(), TextJsonIn::test_bool(), and verify_index().
has_float()
bool TextJsonArray::has_float (size_t index) const inline
Definition at line 1322 of file json.h.
{
             return has_number( index );
         }
References has_number(), and index.
has_int()
bool TextJsonArray::has_int (size_t index) const inline
Definition at line 1319 of file json.h.
{
             return has_number( index );
         }
References has_number(), and index.
has_more()
bool TextJsonArray::has_more () const
Definition at line 557 of file json.cpp.
 {
     return index < positions.size();
 }
References index, and positions.
Referenced by test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), and test_string().
has_null()
bool TextJsonArray::has_null (size_t index) const
Definition at line 759 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->test_null();
 }
References jsin, positions, TextJsonIn::seek(), TextJsonIn::test_null(), and verify_index().
has_number()
bool TextJsonArray::has_number (size_t index) const
Definition at line 773 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->test_number();
 }
References jsin, positions, TextJsonIn::seek(), TextJsonIn::test_number(), and verify_index().
Referenced by has_float(), and has_int().
has_object()
bool TextJsonArray::has_object (size_t index) const
Definition at line 794 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->test_object();
 }
References jsin, positions, TextJsonIn::seek(), TextJsonIn::test_object(), and verify_index().
has_string()
bool TextJsonArray::has_string (size_t index) const
Definition at line 780 of file json.cpp.
 {
     verify_index( i );
     jsin->seek( positions[i] );
     return jsin->test_string();
 }
References jsin, positions, TextJsonIn::seek(), TextJsonIn::test_string(), and verify_index().
next_array()
TextJsonArray TextJsonArray::next_array ()
Definition at line 628 of file json.cpp.
 {
     verify_index( index );
     jsin->seek( positions[index++] );
     return jsin->get_array();
 }
References TextJsonIn::get_array(), index, jsin, positions, TextJsonIn::seek(), and verify_index().
next_bool()
bool TextJsonArray::next_bool ()
Definition at line 600 of file json.cpp.
 {
     verify_index( index );
     jsin->seek( positions[index++] );
     return jsin->get_bool();
 }
References TextJsonIn::get_bool(), index, jsin, positions, TextJsonIn::seek(), and verify_index().
next_float()
double TextJsonArray::next_float ()
Definition at line 614 of file json.cpp.
 {
     verify_index( index );
     jsin->seek( positions[index++] );
     return jsin->get_float();
 }
References TextJsonIn::get_float(), index, jsin, positions, TextJsonIn::seek(), and verify_index().
next_int()
int TextJsonArray::next_int ()
Definition at line 607 of file json.cpp.
 {
     verify_index( index );
     jsin->seek( positions[index++] );
     return jsin->get_int();
 }
References TextJsonIn::get_int(), index, jsin, positions, TextJsonIn::seek(), and verify_index().
next_object()
TextJsonObject TextJsonArray::next_object ()
Definition at line 635 of file json.cpp.
 {
     verify_index( index );
     jsin->seek( positions[index++] );
     return jsin->get_object();
 }
References TextJsonIn::get_object(), index, jsin, positions, TextJsonIn::seek(), and verify_index().
next_string()
std::string TextJsonArray::next_string ()
Definition at line 621 of file json.cpp.
 {
     verify_index( index );
     jsin->seek( positions[index++] );
     return jsin->get_string();
 }
References TextJsonIn::get_string(), index, jsin, positions, TextJsonIn::seek(), and verify_index().
next_value()
TextJsonValue TextJsonArray::next_value ()
Definition at line 593 of file json.cpp.
 {
     verify_index( index );
     jsin->seek( positions[index++] );
     return jsin->get_value();
 }
References TextJsonIn::get_value(), index, jsin, positions, TextJsonIn::seek(), and verify_index().
operator=()
TextJsonArray & TextJsonArray::operator= (const TextJsonArray & ja)
Definition at line 537 of file json.cpp.
 {
     jsin = ja.jsin;
     start = ja.start;
     index = 0;
     positions = ja.positions;
     end_ = ja.end_;
     final_separator = ja.final_separator;
     return *this;
 }
References end_, final_separator, index, jsin, positions, and start.
read()
template<typename T > bool TextJsonArray::read (size_t i, T & t, bool throw_on_error = false) const inline
Definition at line 1336 of file json.h.
{
             verify_index( i );
             jsin->seek( positions[i] );
             return jsin->read( t, throw_on_error );
         }
References jsin, positions, TextJsonIn::read(), TextJsonIn::seek(), and verify_index().
read_next()
template<typename T > bool TextJsonArray::read_next (T & t) inline
Definition at line 1330 of file json.h.
{
             verify_index( index );
             jsin->seek( positions[index++] );
             return jsin->read( t );
         }
References index, jsin, positions, TextJsonIn::read(), TextJsonIn::seek(), and verify_index().
size()
size_t TextJsonArray::size () const
Definition at line 561 of file json.cpp.
 {
     return positions.size();
 }
References positions.
Referenced by end().
skip_value()
void TextJsonArray::skip_value ()
Definition at line 642 of file json.cpp.
 {
     verify_index( index );
     ++index;
 }
References index, and verify_index().
str()
std::string TextJsonArray::str ()
Definition at line 570 of file json.cpp.
 {
     if( jsin ) {
         return jsin->substr( start, end_ - start );
     } else {
         return "[]";
     }
 }
References end_, jsin, start, and TextJsonIn::substr().
string_error()
void TextJsonArray::string_error (int idx, int offset, const std::string & err) const
Definition at line 286 of file json.cpp.
 {
     if( jsin && idx >= 0 && static_cast<size_t>( idx ) < positions.size() ) {
         jsin->seek( positions[idx] );
         jsin->string_error( offset, err );
     } else {
         throw_error( err );
     }
 }
References jsin, positions, TextJsonIn::seek(), TextJsonIn::string_error(), and throw_error().
test_array()
bool TextJsonArray::test_array () const
Definition at line 739 of file json.cpp.
 {
     if( !has_more() ) {
         return false;
     }
     jsin->seek( positions[index] );
     return jsin->test_array();
 }
References has_more(), index, jsin, positions, TextJsonIn::seek(), and TextJsonIn::test_array().
test_bitset()
bool TextJsonArray::test_bitset () const
Definition at line 730 of file json.cpp.
 {
     if( !has_more() ) {
         return false;
     }
     jsin->seek( positions[index] );
     return jsin->test_bitset();
 }
References has_more(), index, jsin, positions, TextJsonIn::seek(), and TextJsonIn::test_bitset().
test_bool()
bool TextJsonArray::test_bool () const
Definition at line 703 of file json.cpp.
 {
     if( !has_more() ) {
         return false;
     }
     jsin->seek( positions[index] );
     return jsin->test_bool();
 }
References has_more(), index, jsin, positions, TextJsonIn::seek(), and TextJsonIn::test_bool().
test_float()
bool TextJsonArray::test_float () const inline
Definition at line 1307 of file json.h.
{
             return test_number();
         }
References test_number().
test_int()
bool TextJsonArray::test_int () const inline
Definition at line 1304 of file json.h.
{
             return test_number();
         }
References test_number().
test_null()
bool TextJsonArray::test_null () const
Definition at line 694 of file json.cpp.
 {
     if( !has_more() ) {
         return false;
     }
     jsin->seek( positions[index] );
     return jsin->test_null();
 }
References has_more(), index, jsin, positions, TextJsonIn::seek(), and TextJsonIn::test_null().
test_number()
bool TextJsonArray::test_number () const
Definition at line 712 of file json.cpp.
 {
     if( !has_more() ) {
         return false;
     }
     jsin->seek( positions[index] );
     return jsin->test_number();
 }
References has_more(), index, jsin, positions, TextJsonIn::seek(), and TextJsonIn::test_number().
Referenced by test_float(), and test_int().
test_object()
bool TextJsonArray::test_object () const
Definition at line 748 of file json.cpp.
 {
     if( !has_more() ) {
         return false;
     }
     jsin->seek( positions[index] );
     return jsin->test_object();
 }
References has_more(), index, jsin, positions, TextJsonIn::seek(), and TextJsonIn::test_object().
test_string()
bool TextJsonArray::test_string () const
Definition at line 721 of file json.cpp.
 {
     if( !has_more() ) {
         return false;
     }
     jsin->seek( positions[index] );
     return jsin->test_string();
 }
References has_more(), index, jsin, positions, TextJsonIn::seek(), and TextJsonIn::test_string().
throw_error() [1/2]
void TextJsonArray::throw_error (const std::string & err) const
Definition at line 267 of file json.cpp.
 {
     if( !jsin ) {
         throw JsonError( err );
     }
     jsin->error( err );
 }
References TextJsonIn::error(), and jsin.
Referenced by string_error().
throw_error() [2/2]
void TextJsonArray::throw_error (int idx, const std::string & err) const
Definition at line 275 of file json.cpp.
 {
     if( !jsin ) {
         throw JsonError( err );
     }
     if( idx >= 0 && static_cast<size_t>( idx ) < positions.size() ) {
         jsin->seek( positions[idx] );
     }
     jsin->error( err );
 }
References TextJsonIn::error(), jsin, positions, and TextJsonIn::seek().
verify_index()
void TextJsonArray::verify_index (size_t i) const private
Definition at line 579 of file json.cpp.
 {
     if( !jsin ) {
         throw JsonError( "tried to access empty array." );
     } else if( i >= positions.size() ) {
         jsin->seek( start );
         std::stringstream err;
         err << "bad index value: " << i;
         jsin->error( err.str() );
     }
 }
References TextJsonIn::error(), jsin, positions, TextJsonIn::seek(), and start.
Referenced by get_array(), get_bool(), get_float(), get_int(), get_object(), get_string(), get_tags(), has_array(), has_bool(), has_null(), has_number(), has_object(), has_string(), next_array(), next_bool(), next_float(), next_int(), next_object(), next_string(), next_value(), TextJsonArray::const_iterator::operator*(), read(), read_next(), and skip_value().
Member Data Documentation
end_
int TextJsonArray::end_ private
Definition at line 1248 of file json.h.
Referenced by finish(), operator=(), str(), and TextJsonArray().
final_separator
bool TextJsonArray::final_separator private
Definition at line 1249 of file json.h.
Referenced by finish(), operator=(), and TextJsonArray().
index
size_t TextJsonArray::index private
Definition at line 1247 of file json.h.
Referenced by get_tags(), has_float(), has_int(), has_more(), next_array(), next_bool(), next_float(), next_int(), next_object(), next_string(), next_value(), operator=(), read_next(), skip_value(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), test_string(), and TextJsonArray().
jsin
TextJsonIn* TextJsonArray::jsin private
Definition at line 1250 of file json.h.
Referenced by finish(), get_array(), get_bool(), get_float(), get_int(), get_object(), get_string(), get_tags(), has_array(), has_bool(), has_null(), has_number(), has_object(), has_string(), next_array(), next_bool(), next_float(), next_int(), next_object(), next_string(), next_value(), TextJsonArray::const_iterator::operator*(), operator=(), read(), read_next(), str(), string_error(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), test_string(), TextJsonArray(), throw_error(), and verify_index().
positions
std::vector<size_t> TextJsonArray::positions private
Definition at line 1245 of file json.h.
Referenced by empty(), get_array(), get_bool(), get_float(), get_int(), get_object(), get_string(), get_tags(), has_array(), has_bool(), has_more(), has_null(), has_number(), has_object(), has_string(), next_array(), next_bool(), next_float(), next_int(), next_object(), next_string(), next_value(), TextJsonArray::const_iterator::operator*(), operator=(), read(), read_next(), size(), string_error(), test_array(), test_bitset(), test_bool(), test_null(), test_number(), test_object(), test_string(), TextJsonArray(), throw_error(), and verify_index().
start
int TextJsonArray::start private
Definition at line 1246 of file json.h.
Referenced by operator=(), str(), TextJsonArray(), and verify_index().
The documentation for this class was generated from the following files:
src/json.h
src/json.cpp