Cataclysm DDA: hacksaw_activity_actor Class Reference
hacksaw_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
hacksaw_activity_actor (const tripoint &target, const item_location &tool)
hacksaw_activity_actor (const tripoint &target, const itype_id &type, const tripoint &veh_pos)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Public Attributes
bool testing = false
Private Member Functions
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
Private Attributes
tripoint target
item_location tool
std::optional< itype_id > type
std::optional< tripoint > veh_pos
Detailed Description
Definition at line 177 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
hacksaw_activity_actor() [1/2]
hacksaw_activity_actor::hacksaw_activity_actor (const tripoint & target, const item_location & tool) inline explicit
Definition at line 180 of file activity_actor_definitions.h.
                                                                      : target( target ), tool( tool ) {};
hacksaw_activity_actor() [2/2]
hacksaw_activity_actor::hacksaw_activity_actor (const tripoint & target, const itype_id & type, const tripoint & veh_pos) inline explicit
Definition at line 182 of file activity_actor_definitions.h.
                                                                    : target( target ), type( type ), veh_pos( veh_pos ) {};
Member Function Documentation
can_resume_with_internal()
bool hacksaw_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const override private virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 1454 of file activity_actor.cpp.
 {
     const hacksaw_activity_actor &actor = static_cast<const hacksaw_activity_actor &>
                                           ( other );
     return actor.target == target && ( ( veh_pos.has_value() &&
                                          veh_pos.value() == actor.veh_pos.value_or( tripoint_max ) ) || actor.tool.operator == ( tool ) );
 }
References other, target, tool, tripoint_max, and veh_pos.
clone()
std::unique_ptr<activity_actor> hacksaw_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 192 of file activity_actor_definitions.h.
{
             return std::make_unique<hacksaw_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > hacksaw_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 1473 of file activity_actor.cpp.
 {
     hacksaw_activity_actor actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "target", actor.target );
     data.read( "tool", actor.tool );
     data.read( "type", actor.type );
     data.read( "veh_pos", actor.veh_pos );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void hacksaw_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1322 of file activity_actor.cpp.
 {
     std::string method = "HACKSAW";
     if( !veh_pos.has_value() ) {
         if( tool->ammo_sufficient( &who, method ) ) {
             int ammo_consumed = tool->ammo_required();
             std::map<std::string, int>::const_iterator iter = tool->type->ammo_scale.find( method );
             if( iter != tool->type->ammo_scale.end() ) {
                 ammo_consumed *= iter->second;
             }
             tool->ammo_consume( ammo_consumed, tool.position(), &who );
             sfx::play_activity_sound( "tool", "hacksaw", sfx::get_heard_volume( target ) );
             if( calendar::once_every( 1_minutes ) ) {
                 //~ Sound of a metal sawing tool at work!
                 sounds::sound( target, 15, sounds::sound_t::destructive_activity, _( "grnd grnd grnd" ) );
             }
         } else {
             if( who.is_avatar() ) {
                 who.add_msg_if_player( m_bad, _( "Your %1$s ran out of charges." ), tool->tname() );
             } else { // who.is_npc()
                 add_msg_if_player_sees( who.pos(), _( "%1$s %2$s ran out of charges." ), who.disp_name( false,
                                         true ), tool->tname() );
             }
             who.cancel_activity();
         }
     } else {
         map &here = get_map();
         const optional_vpart_position vp = here.veh_at( veh_pos.value() );
         if( !vp ) {
             debugmsg( "Lost ACT_HACKSAW vehicle tool" );
             return;
         }
         vehicle &veh = vp->vehicle();
         if( vehicle::use_vehicle_tool( veh, veh_pos.value(), type.value(), true ) ) {
             sfx::play_activity_sound( "tool", "hacksaw", sfx::get_heard_volume( target ) );
             if( calendar::once_every( 1_minutes ) ) {
                 //~ Sound of a metal sawing tool at work!
                 sounds::sound( target, 15, sounds::sound_t::destructive_activity, _( "grnd grnd grnd" ) );
             }
         } else {
             if( who.is_avatar() ) {
                 who.add_msg_if_player( m_bad, _( "Your %1$s ran out of charges." ), type.value()->nname( 1 ) );
             } else { // who.is_npc()
                 add_msg_if_player_sees( who.pos(), _( "%1$s %2$s ran out of charges." ), who.disp_name( false,
                                         true ), type.value()->nname( 1 ) );
             }
             who.cancel_activity();
         }
     }
 }
References _, Character::add_msg_if_player(), add_msg_if_player_sees(), item::ammo_consume(), item::ammo_required(), itype::ammo_scale, item::ammo_sufficient(), Character::cancel_activity(), debugmsg, sounds::destructive_activity, Character::disp_name(), sfx::get_heard_volume(), get_map(), Creature::is_avatar(), m_bad, calendar::once_every(), sfx::play_activity_sound(), Creature::pos(), item_location::position(), sounds::sound(), target, item::tname(), tool, type, item::type, vehicle::use_vehicle_tool(), map::veh_at(), and veh_pos.
finish()
void hacksaw_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1375 of file activity_actor.cpp.
 {
     map &here = get_map();
     const activity_data_common *data;
     if( here.has_furn( target ) ) {
         const furn_id furn_type = here.furn( target );
         if( !furn_type->hacksaw->valid() ) {
             if( !testing ) {
                 debugmsg( "%s hacksaw is invalid", furn_type.id().str() );
             }
             act.set_to_null();
             return;
         }
         const furn_str_id new_furn = furn_type->hacksaw->result();
         if( !new_furn.is_valid() ) {
             if( !testing ) {
                 debugmsg( "hacksaw furniture: %s invalid furniture", new_furn.str() );
             }
             act.set_to_null();
             return;
         }
         data = static_cast<const activity_data_common *>( &*furn_type->hacksaw );
         here.furn_set( target, new_furn );
     } else if( !here.ter( target )->is_null() ) {
         const ter_id ter_type = here.ter( target );
         if( !ter_type->hacksaw->valid() ) {
             if( !testing ) {
                 debugmsg( "%s hacksaw is invalid", ter_type.id().str() );
             }
             act.set_to_null();
             return;
         }
         const ter_str_id new_ter = ter_type->hacksaw->result();
         if( !new_ter.is_valid() ) {
             if( !testing ) {
                 debugmsg( "hacksaw terrain: %s invalid terrain", new_ter.str() );
             }
             act.set_to_null();
             return;
         }
         data = static_cast<const activity_data_common *>( &*ter_type->hacksaw );
         here.ter_set( target, new_ter );
     } else {
         if( !testing ) {
             debugmsg( "hacksaw activity finished on invalid terrain" );
         }
         act.set_to_null();
         return;
     }
     for( const activity_byproduct &byproduct : data->byproducts() ) {
         const int amount = byproduct.roll();
         if( byproduct.item->count_by_charges() ) {
             item byproduct_item( byproduct.item, calendar::turn, amount );
             here.add_item_or_charges( target, byproduct_item );
         } else {
             item byproduct_item( byproduct.item, calendar::turn );
             for( int i = 0; i < amount; ++i ) {
                 here.add_item_or_charges( target, byproduct_item );
             }
         }
     }
     if( !data->message().empty() ) {
         who.add_msg_if_player( m_info, data->message().translated() );
     }
     act.set_to_null();
 }
References act, map::add_item_or_charges(), Character::add_msg_if_player(), activity_data_common::byproducts(), debugmsg, translation::empty(), map::furn(), map::furn_set(), get_map(), ter_t::hacksaw, furn_t::hacksaw, map::has_furn(), int_id< T >::id(), ter_t::is_null(), string_id< T >::is_valid(), m_info, activity_data_common::message(), string_id< T >::str(), target, map::ter(), map::ter_set(), testing, translation::translated(), and calendar::turn.
get_type()
activity_id hacksaw_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 184 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_HACKSAW" );
         }
References activity_id.
serialize()
void hacksaw_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 1463 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target", target );
     jsout.member( "tool", tool );
     jsout.member( "type", type );
     jsout.member( "veh_pos", veh_pos );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), target, tool, type, and veh_pos.
start()
void hacksaw_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1255 of file activity_actor.cpp.
 {
     const map &here = get_map();
     int moves_before_quality;
     if( here.has_furn( target ) ) {
         const furn_id furn_type = here.furn( target );
         if( !furn_type->hacksaw->valid() ) {
             if( !testing ) {
                 debugmsg( "%s hacksaw is invalid", furn_type.id().str() );
             }
             act.set_to_null();
             return;
         }
         moves_before_quality = to_moves<int>( furn_type->hacksaw->duration() );
     } else if( !here.ter( target )->is_null() ) {
         const ter_id ter_type = here.ter( target );
         if( !ter_type->hacksaw->valid() ) {
             if( !testing ) {
                 debugmsg( "%s hacksaw is invalid", ter_type.id().str() );
             }
             act.set_to_null();
             return;
         }
         moves_before_quality = to_moves<int>( ter_type->hacksaw->duration() );
     } else {
         if( !testing ) {
             debugmsg( "hacksaw activity called on invalid terrain" );
         }
         act.set_to_null();
         return;
     }
     int qual = 0;
     if( type.has_value() ) {
         item veh_tool = item( type.value(), calendar::turn );
         for( const std::pair<const quality_id, int> &quality : type.value()->qualities ) {
             if( quality.first == qual_SAW_M ) {
                 qual = quality.second;
             }
         }
         for( const std::pair<const quality_id, int> &quality : type.value()->charged_qualities ) {
             if( quality.first == qual_SAW_M ) {
                 qual = std::max( qual, quality.second );
             }
         }
     } else {
         qual = tool->get_quality( qual_SAW_M );
     }
     if( qual < 2 ) {
         if( !testing ) {
             debugmsg( "Item %s with 'HACKSAW' use action requires SAW_M quality of at least 2.",
                       tool->typeId().c_str() );
         }
         act.set_to_null();
         return;
     }
     //Speed of hacksaw action is the SAW_M quality over 2, 2 being the hacksaw level.
     //3 makes the speed one-and-a-half times, and the total moves 66% of hacksaw. 4 is twice the speed, 50% the moves, etc, 5 is 2.5 times the speed, 40% the original time
     //done because it's easy to code, and diminising returns on cutting speed make sense as the limiting factor becomes aligning the tool and controlling it instead of the actual cutting
     act.moves_total = moves_before_quality / ( qual / 2 );
     add_msg_debug( debugmode::DF_ACTIVITY, "%s moves_total: %d", act.id().str(), act.moves_total );
     act.moves_left = act.moves_total;
 }
References act, add_msg_debug, string_id< T >::c_str(), debugmsg, debugmode::DF_ACTIVITY, map::furn(), get_map(), item::get_quality(), ter_t::hacksaw, furn_t::hacksaw, map::has_furn(), int_id< T >::id(), string_id< T >::id(), ter_t::is_null(), item, max(), qual_SAW_M, string_id< T >::str(), target, map::ter(), testing, tool, calendar::turn, type, and item::typeId().
Member Data Documentation
target
tripoint hacksaw_activity_actor::target private
Definition at line 202 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), do_turn(), finish(), serialize(), and start().
testing
bool hacksaw_activity_actor::testing = false
Definition at line 200 of file activity_actor_definitions.h.
Referenced by finish(), and start().
tool
item_location hacksaw_activity_actor::tool private
Definition at line 203 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), do_turn(), serialize(), and start().
type
std::optional<itype_id> hacksaw_activity_actor::type private
Definition at line 204 of file activity_actor_definitions.h.
Referenced by do_turn(), serialize(), and start().
veh_pos
std::optional<tripoint> hacksaw_activity_actor::veh_pos private
Definition at line 205 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp