Cataclysm DDA: mission_data Class Reference
mission_data Class Reference
#include <mission_companion.h>
Public Member Functions
mission_data ()
void add (const ui_mission_id &id, const std::string &name_display="", const std::string &text="", bool priority=false, bool possible=true)
Adds the id's to the correct vectors (i.e.
void add_return (const mission_id &id, const std::string &name_display, const std::string &text, bool possible=true)
void add_start (const mission_id &id, const std::string &name_display, const std::string &text, bool possible=true)
Public Attributes
std::vector< std::vector< mission_entry > > entries
mission_entry cur_key
Detailed Description
Definition at line 133 of file mission_companion.h.
Constructor & Destructor Documentation
mission_data()
mission_data::mission_data ()
Definition at line 576 of file mission_companion.cpp.
 {
     for( int tab_num = base_camps::TAB_MAIN; tab_num != base_camps::TAB_NW + 3; tab_num++ ) {
         std::vector<mission_entry> k;
         entries.push_back( k );
     }
 }
References entries, base_camps::TAB_MAIN, and base_camps::TAB_NW.
Member Function Documentation
add()
void mission_data::add (const ui_mission_id & id, const std::string & name_display = "", const std::string & text = "", bool priority = false, bool possible = true)
Adds the id's to the correct vectors (i.e.
tabs) in the UI.
Parameters
id is the mission reference
name_display is string displayed
priority turns the mission key yellow and pushes to front of main tab
possible grays the mission key when false and makes it impossible to select
Definition at line 2885 of file mission_companion.cpp.
 {
     Character &player_character = get_player_character();
     std::optional<basecamp *> bcp = overmap_buffer.find_camp(
                                         player_character.global_omt_location().xy() );
     if( bcp.has_value() && bcp.value()->is_hidden( id ) ) {
         return;
     }
     mission_entry miss;
     miss.id = id;
     if( name_display.empty() ) {  //  Poorly designed if this is the case. Do it properly...
         miss.name_display = miss_info[id.id.id].serialize_id;
     } else {
         miss.name_display = name_display;
     }
     miss.text = text;
     miss.priority = priority;
     miss.possible = possible;
     if( priority ) {
         entries[0].push_back( miss );
     }
     if( !possible ) {
         entries[10].push_back( miss );
     }
     const point direction = id.id.dir ? *id.id.dir : base_camps::base_dir;
     const int tab_order = base_camps::all_directions.at( direction ).tab_order;
     entries[tab_order + 1].emplace_back( miss );
 }
References base_camps::all_directions, base_camps::base_dir, entries, overmapbuffer::find_camp(), get_player_character(), Creature::global_omt_location(), base_camps::id, mission_entry::id, miss_info, mission_entry::name_display, overmap_buffer, possible, mission_entry::possible, mission_entry::priority, mission_entry::text, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by add_return(), add_start(), basecamp::get_available_missions(), and basecamp::get_available_missions_by_dir().
add_return()
void mission_data::add_return (const mission_id & id, const std::string & name_display, const std::string & text, bool possible = true)
Definition at line 2875 of file mission_companion.cpp.
 {
     add( { id, true }, name_display, text, true, possible );
 }
References add(), base_camps::id, and possible.
Referenced by talk_function::commune_carpentry(), talk_function::commune_forage(), talk_function::commune_menial(), talk_function::commune_refuge_caravan(), basecamp::get_available_missions(), basecamp::get_available_missions_by_dir(), talk_function::hospital_raid(), talk_function::scavenger_patrol(), and talk_function::scavenger_raid().
add_start()
void mission_data::add_start (const mission_id & id, const std::string & name_display, const std::string & text, bool possible = true)
Definition at line 2880 of file mission_companion.cpp.
 {
     add( { id, false }, name_display, text, false, possible );
 }
References add(), base_camps::id, and possible.
Referenced by basecamp::add_available_recipes(), talk_function::commune_carpentry(), talk_function::commune_forage(), talk_function::commune_menial(), talk_function::commune_refuge_caravan(), basecamp::get_available_missions(), basecamp::get_available_missions_by_dir(), talk_function::hospital_raid(), talk_function::scavenger_patrol(), and talk_function::scavenger_raid().
Member Data Documentation
cur_key
mission_entry mission_data::cur_key
Definition at line 137 of file mission_companion.h.
Referenced by talk_function::basecamp_mission(), iexamine::bulletin_board(), talk_function::companion_mission(), and talk_function::display_and_choose_opts().
entries
std::vector<std::vector<mission_entry> > mission_data::entries
Definition at line 136 of file mission_companion.h.
Referenced by add(), talk_function::display_and_choose_opts(), basecamp::get_available_missions(), basecamp::get_available_missions_by_dir(), and mission_data().
The documentation for this class was generated from the following files:
src/mission_companion.h
src/mission_companion.cpp