Cataclysm DDA: plot_options Class Reference
plot_options Class Reference
#include <clzones.h>
Public Member Functions
std::string get_mark () const override
itype_id get_seed () const
bool has_options () const override
bool query_at_creation () override
bool query () override
std::string get_zone_name_suggestion () const override
std::vector< std::pair< std::string, std::string > > get_descriptions () const override
void serialize (JsonOut &json) const override
void deserialize (const JsonObject &jo_zone) override
Public Member Functions inherited from zone_options
virtual ~zone_options ()=default
Public Member Functions inherited from mark_option
virtual ~mark_option ()=default
Private Types
enum query_seed_result { canceled , successful , changed }
Private Member Functions
query_seed_result query_seed ()
Private Attributes
itype_id mark
itype_id seed
Additional Inherited Members
Static Public Member Functions inherited from zone_options
static shared_ptr_fast< zone_options > create (const zone_type_id &type)
static bool is_valid (const zone_type_id &type, const zone_options &options)
Detailed Description
Definition at line 126 of file clzones.h.
Member Enumeration Documentation
query_seed_result
enum plot_options::query_seed_result private
Enumerator
canceled
successful
changed
Definition at line 132 of file clzones.h.
{
             canceled,
             successful,
             changed,
         };
Member Function Documentation
deserialize()
void plot_options::deserialize (const JsonObject & jo_zone) override virtual
Reimplemented from zone_options.
Definition at line 545 of file clzones.cpp.
 {
     jo_zone.read( "mark", mark );
     jo_zone.read( "seed", seed );
 }
References mark, JsonObject::read(), and seed.
get_descriptions()
std::vector< std::pair< std::string, std::string > > plot_options::get_descriptions () const override virtual
Reimplemented from zone_options.
Definition at line 477 of file clzones.cpp.
 {
     auto options = std::vector<std::pair<std::string, std::string>>();
     options.emplace_back(
         _( "Plant seed: " ),
         !seed.is_empty() ? item::nname( itype_id( seed ) ) : _( "No seed" ) );
     return options;
 }
References _, string_id< T >::is_empty(), itype_id, item::nname(), PATH_INFO::options(), and seed.
get_mark()
std::string plot_options::get_mark () const inline override virtual
Implements mark_option.
Definition at line 141 of file clzones.h.
{
             return mark.str();
         }
References mark, and string_id< T >::str().
get_seed()
itype_id plot_options::get_seed () const inline
Definition at line 144 of file clzones.h.
{
             return seed;
         }
References seed.
Referenced by generic_multi_activity_check_requirement().
get_zone_name_suggestion()
std::string plot_options::get_zone_name_suggestion () const override virtual
Reimplemented from zone_options.
Definition at line 425 of file clzones.cpp.
 {
     if( !seed.is_empty() ) {
         const itype_id type = itype_id( seed );
         item it = item( type );
         if( it.is_seed() ) {
             return it.type->seed->plant_name.translated();
         } else {
             return item::nname( type );
         }
     }
     return _( "No seed" );
 }
References _, string_id< T >::is_empty(), item::is_seed(), item, itype_id, item::nname(), seed, itype::seed, type, and item::type.
has_options()
bool plot_options::has_options () const inline override virtual
Reimplemented from zone_options.
Definition at line 148 of file clzones.h.
{
             return true;
         }
query()
bool plot_options::query () override virtual
Reimplemented from zone_options.
Definition at line 398 of file clzones.cpp.
 {
     return query_seed() == changed;
 }
References changed, and query_seed().
query_at_creation()
bool plot_options::query_at_creation () override virtual
Reimplemented from zone_options.
Definition at line 373 of file clzones.cpp.
 {
     return query_seed() != canceled;
 }
References canceled, and query_seed().
query_seed()
plot_options::query_seed_result plot_options::query_seed () private
Definition at line 304 of file clzones.cpp.
 {
     Character &player_character = get_player_character();
     std::vector<item *> seed_inv = player_character.cache_get_items_with( "is_seed", &item::is_seed );
     zone_manager &mgr = zone_manager::get_manager();
     map &here = get_map();
     const std::unordered_set<tripoint_abs_ms> zone_src_set =
         mgr.get_near( zone_type_LOOT_SEEDS, here.getglobal( player_character.pos() ), 60 );
     for( const tripoint_abs_ms &elem : zone_src_set ) {
         tripoint elem_loc = here.getlocal( elem );
         for( item &it : here.i_at( elem_loc ) ) {
             if( it.is_seed() ) {
                 seed_inv.push_back( &it );
             }
         }
     }
     std::vector<seed_tuple> seed_entries = iexamine::get_seed_entries( seed_inv );
     seed_entries.emplace( seed_entries.begin(), itype_null, _( "No seed" ), 0 );
     int seed_index = iexamine::query_seed( seed_entries );
     if( seed_index > 0 && seed_index < static_cast<int>( seed_entries.size() ) ) {
         const auto &seed_entry = seed_entries[seed_index];
         const itype_id &new_seed = std::get<0>( seed_entry );
         itype_id new_mark;
         item it = item( new_seed );
         if( it.is_seed() ) {
             new_mark = it.type->seed->fruit_id;
         } else {
             new_mark = seed;
         }
         if( new_seed != seed || new_mark != mark ) {
             seed = new_seed;
             mark = new_mark;
             return changed;
         } else {
             return successful;
         }
     } else if( seed_index == 0 ) {
         // No seeds
         if( !seed.is_empty() || !mark.is_empty() ) {
             seed = itype_id();
             mark = itype_id();
             return changed;
         } else {
             return successful;
         }
     } else {
         return canceled;
     }
 }
References _, Character::cache_get_items_with(), canceled, changed, zone_manager::get_manager(), get_map(), zone_manager::get_near(), get_player_character(), iexamine::get_seed_entries(), map::getglobal(), map::getlocal(), map::i_at(), string_id< T >::is_empty(), item::is_seed(), item, itype_id, itype_null, mark, Creature::pos(), iexamine::query_seed(), seed, itype::seed, successful, item::type, and zone_type_LOOT_SEEDS.
Referenced by query(), and query_at_creation().
serialize()
void plot_options::serialize (JsonOut & json) const override virtual
Reimplemented from zone_options.
Definition at line 539 of file clzones.cpp.
 {
     json.member( "mark", mark );
     json.member( "seed", seed );
 }
References mark, JsonOut::member(), and seed.
Member Data Documentation
mark
itype_id plot_options::mark private
Definition at line 129 of file clzones.h.
Referenced by deserialize(), get_mark(), query_seed(), and serialize().
seed
itype_id plot_options::seed private
Definition at line 130 of file clzones.h.
Referenced by deserialize(), get_descriptions(), get_seed(), get_zone_name_suggestion(), query_seed(), and serialize().
The documentation for this class was generated from the following files:
src/clzones.h
src/clzones.cpp