Cataclysm DDA: npc_attack_throw Class Reference
npc_attack_throw Class Reference
#include <npc_attack.h>
Public Member Functions
npc_attack_throw (item &thrown_item)
npc_attack_rating evaluate (const npc &source, const Creature *target) const override
Parameters: source - the npc making the attack target - the desired target of the npc.
std::vector< npc_attack_rating > all_evaluations (const npc &source, const Creature *target) const override
For debug information.
void use (npc &source, const tripoint &location) const override
Public Member Functions inherited from npc_attack
virtual ~npc_attack ()=default
Private Member Functions
tripoint_range< tripoint > targetable_points (const npc &source) const
bool can_use (const npc &source) const
int base_penalty (const npc &source) const
npc_attack_rating evaluate_tripoint (const npc &source, const Creature *target, const tripoint &location) const
Private Attributes
item & thrown_item
Detailed Description
Definition at line 114 of file npc_attack.h.
Constructor & Destructor Documentation
npc_attack_throw()
npc_attack_throw::npc_attack_throw (item & thrown_item) inline explicit
Definition at line 118 of file npc_attack.h.
 : thrown_item( thrown_item ) {}
Member Function Documentation
all_evaluations()
std::vector< npc_attack_rating > npc_attack_throw::all_evaluations (const npc & source, const Creature * target) const override virtual
For debug information.
returns all evaluated effectivenesses. This is abstracted out in evaluate() as it's faster to not use a container
Implements npc_attack.
Definition at line 773 of file npc_attack.cpp.
 {
     std::vector<npc_attack_rating> effectiveness;
     if( !can_use( source ) ) {
         // please don't throw your pants...
         return effectiveness;
     }
     const int penalty = base_penalty( source );
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &potential : targetable_points( source ) ) {
         if( Creature *critter = creatures.creature_at( potential ) ) {
             if( source.attitude_to( *critter ) != Creature::Attitude::HOSTILE ) {
                 // no point in friendly fire!
                 continue;
             }
             npc_attack_rating effectiveness_at_point = evaluate_tripoint( source, target,
                     potential );
             effectiveness_at_point -= penalty;
             effectiveness.push_back( effectiveness_at_point );
         }
     }
     return effectiveness;
 }
References npc::attitude_to(), base_penalty(), can_use(), creature_tracker::creature_at(), evaluate_tripoint(), get_creature_tracker(), Creature::HOSTILE, and targetable_points().
base_penalty()
int npc_attack_throw::base_penalty (const npc & source) const private
Definition at line 700 of file npc_attack.cpp.
 {
     item single_item( thrown_item );
     if( single_item.count_by_charges() ) {
         single_item.charges = 1;
     }
     const int time_penalty = source.is_wielding( single_item ) ? 0 :
                              npc_attack_constants::base_time_penalty;
     return time_penalty;
 }
References npc_attack_constants::base_time_penalty, item::charges, item::count_by_charges(), Character::is_wielding(), and thrown_item.
Referenced by all_evaluations(), and evaluate().
can_use()
bool npc_attack_throw::can_use (const npc & source) const private
Definition at line 660 of file npc_attack.cpp.
 {
     // Don't throw anything if we're hallucination
     // TODO: make an analogue of pretend_fire function
     if( source.is_hallucination() ) {
         return false;
     }
     if( !source.is_wielding( thrown_item ) && !source.can_wield( thrown_item ).success() ) {
         return false;
     }
     item single_item( thrown_item );
     if( single_item.count_by_charges() ) {
         single_item.charges = 1;
     }
     // Always allow throwing items that are flagged as throw now to
     // get rid of dangerous items ASAP, even if ranged attacks aren't allowed
     if( thrown_item.has_flag( flag_NPC_THROW_NOW ) ) {
         return true;
     }
     if( source.is_player_ally() && !source.rules.has_flag( ally_rule::use_guns ) ) {
         return false;
     }
     // Items flagged as NPC_THROWN are always allowed
     if( thrown_item.has_flag( flag_NPC_THROWN ) ) {
         return true;
     }
     bool throwable = source.throw_range( single_item ) > 0 && !source.is_worn( thrown_item ) &&
                      !thrown_item.has_flag( flag_NPC_ACTIVATE );
     throwable = throwable && !thrown_item.is_gun() && !thrown_item.is_armor() &&
                 !thrown_item.is_comestible() && !thrown_item.is_magazine() && !thrown_item.is_tool();
     // TODO: Better choose what should be thrown
     return throwable;
 }
References Character::can_wield(), item::charges, item::count_by_charges(), flag_NPC_ACTIVATE, flag_NPC_THROW_NOW, flag_NPC_THROWN, npc_follower_rules::has_flag(), item::has_flag(), item::is_armor(), item::is_comestible(), item::is_gun(), npc::is_hallucination(), item::is_magazine(), npc::is_player_ally(), item::is_tool(), Character::is_wielding(), Character::is_worn(), npc::rules, ret_val_common::success(), Character::throw_range(), thrown_item, and use_guns.
Referenced by all_evaluations(), and evaluate().
evaluate()
npc_attack_rating npc_attack_throw::evaluate (const npc & source, const Creature * target) const override virtual
Parameters: source - the npc making the attack target - the desired target of the npc.
valued at 100%
Implements npc_attack.
Definition at line 722 of file npc_attack.cpp.
 {
     npc_attack_rating effectiveness( std::nullopt, source.pos() );
     if( !can_use( source ) ) {
         // please don't throw your pants...
         return effectiveness;
     }
     const inventory &available_weapons = source.crafting_inventory( -1 );
     if( &thrown_item == source.evaluate_best_weapon() &&
         available_weapons.amount_of( thrown_item.typeId() ) <= 1 &&
         available_weapons.charges_of( thrown_item.typeId() ) <= 1 ) {
         // Don't throw if it's the best individual killy-thing we've got
         return effectiveness;
     }
     const int penalty = base_penalty( source );
     const bool throw_now = thrown_item.has_flag( flag_NPC_THROW_NOW );
     // TODO: Should this be a field to cache the result?
     const bool avoids_friendly_fire = source.rules.has_flag( ally_rule::avoid_friendly_fire );
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &potential : targetable_points( source ) ) {
         // hot potato! HOT POTATO!
         // Calculated for all targetable points, not just those with targets
         if( throw_now ) {
             // TODO: Take into account distance to allies too
             const int distance_to_me = rl_dist( potential, source.pos() );
             int result = npc_attack_constants::base_throw_now + distance_to_me;
             if( !has_obstruction( source.pos(), potential, avoids_friendly_fire ) ) {
                 // More likely to pick a target tile that isn't obstructed
                 result += 100;
             }
             return npc_attack_rating( result, potential );
         }
         if( Creature *critter = creatures.creature_at( potential ) ) {
             if( source.attitude_to( *critter ) != Creature::Attitude::HOSTILE ) {
                 // no point in friendly fire!
                 continue;
             }
             npc_attack_rating effectiveness_at_point = evaluate_tripoint( source, target,
                     potential );
             effectiveness_at_point -= penalty;
             if( effectiveness_at_point > effectiveness ) {
                 effectiveness = effectiveness_at_point;
             }
         }
     }
     return effectiveness;
 }
References inventory::amount_of(), npc::attitude_to(), avoid_friendly_fire, base_penalty(), npc_attack_constants::base_throw_now, can_use(), inventory::charges_of(), Character::crafting_inventory(), creature_tracker::creature_at(), npc::evaluate_best_weapon(), evaluate_tripoint(), flag_NPC_THROW_NOW, get_creature_tracker(), npc_follower_rules::has_flag(), item::has_flag(), has_obstruction(), Creature::HOSTILE, Creature::pos(), rl_dist(), npc::rules, targetable_points(), thrown_item, and item::typeId().
evaluate_tripoint()
npc_attack_rating npc_attack_throw::evaluate_tripoint (const npc & source, const Creature * target, const tripoint & location) const private
Definition at line 798 of file npc_attack.cpp.
 {
     if( has_obstruction( source.pos(), location ) ) {
         return npc_attack_rating( std::nullopt, location );
     }
     item single_item( thrown_item );
     if( single_item.count_by_charges() ) {
         single_item.charges = 1;
     }
     Creature::Attitude att = Creature::Attitude::NEUTRAL;
     const Creature *critter = get_creature_tracker().creature_at( location );
     if( critter ) {
         att = source.attitude_to( *critter );
     }
     if( att != Creature::Attitude::HOSTILE ) {
         // No point in throwing stuff at neutral/friendly targets
         return npc_attack_rating( std::nullopt, location );
     }
     if( source.rules.has_flag( ally_rule::avoid_friendly_fire ) &&
         !source.wont_hit_friend( location, thrown_item, true ) ) {
         // Avoid friendy fire
         return npc_attack_rating( std::nullopt, location );
     }
     const float throw_mult = throw_cost( source, single_item ) * source.speed_rating() / 100.0f;
     const int damage = source.thrown_item_total_damage_raw( single_item );
     float dps = damage / throw_mult;
     const int distance_to_me = rl_dist( location, source.pos() );
     float suitable_item_mult = -0.15f;
     if( distance_to_me > 1 ) {
         if( thrown_item.has_flag( flag_NPC_THROWN ) ) {
             suitable_item_mult = 0.08f * std::min( distance_to_me - 1, 5 );
         }
     } else {
         suitable_item_mult = -0.35f;
     }
     double potential = dps * ( 1.0 + suitable_item_mult );
     if( potential > 0.0f && critter && damage >= critter->get_hp() ) {
         potential *= npc_attack_constants::kill_modifier;
     }
     if( potential > 0.0f && target && critter && target->pos() == critter->pos() ) {
         potential *= npc_attack_constants::target_modifier;
     }
     return npc_attack_rating( static_cast<int>( std::round( potential ) ), location );
 }
References npc::attitude_to(), avoid_friendly_fire, item::charges, item::count_by_charges(), creature_tracker::creature_at(), flag_NPC_THROWN, get_creature_tracker(), Creature::get_hp(), npc_follower_rules::has_flag(), item::has_flag(), has_obstruction(), Creature::HOSTILE, npc_attack_constants::kill_modifier, location, min(), Creature::NEUTRAL, Creature::pos(), rl_dist(), round(), npc::rules, npc::speed_rating(), npc_attack_constants::target_modifier, throw_cost(), thrown_item, Character::thrown_item_total_damage_raw(), and npc::wont_hit_friend().
Referenced by all_evaluations(), and evaluate().
targetable_points()
tripoint_range< tripoint > npc_attack_throw::targetable_points (const npc & source) const private
Definition at line 712 of file npc_attack.cpp.
 {
     item single_item( thrown_item );
     if( single_item.count_by_charges() ) {
         single_item.charges = 1;
     }
     const int range = source.throw_range( single_item );
     return get_map().points_in_radius( source.pos(), range );
 }
References item::charges, item::count_by_charges(), get_map(), map::points_in_radius(), Creature::pos(), Character::throw_range(), and thrown_item.
Referenced by all_evaluations(), and evaluate().
use()
void npc_attack_throw::use (npc & source, const tripoint & location) const override virtual
Implements npc_attack.
Definition at line 627 of file npc_attack.cpp.
 {
     if( !source.is_wielding( thrown_item ) ) {
         if( !source.wield( thrown_item ) ) {
             debugmsg( "ERROR: npc tried to equip a weapon it couldn't wield" );
         }
         return;
     }
     if( has_obstruction( source.pos(), location, false ) ||
         ( source.rules.has_flag( ally_rule::avoid_friendly_fire ) &&
           !source.wont_hit_friend( location, thrown_item, false ) ) ) {
         if( can_move( source ) ) {
             source.avoid_friendly_fire();
         } else {
             source.move_pause();
         }
         return;
     }
     item_location weapon = source.get_wielded_item();
     add_msg_debug( debugmode::debug_filter::DF_NPC, "%s throws the %s", source.disp_name(),
                    weapon->display_name() );
     item thrown( *weapon );
     if( weapon->count_by_charges() && weapon->charges > 1 ) {
         weapon->mod_charges( -1 );
         thrown.charges = 1;
     } else {
         source.remove_weapon();
     }
     source.throw_item( location, thrown );
 }
References add_msg_debug, avoid_friendly_fire, npc::avoid_friendly_fire(), can_move(), item::charges, item::count_by_charges(), debugmsg, debugmode::DF_NPC, Character::disp_name(), item::display_name(), Character::get_wielded_item(), npc_follower_rules::has_flag(), has_obstruction(), Character::is_wielding(), location, item::mod_charges(), npc::move_pause(), Creature::pos(), Character::remove_weapon(), npc::rules, Character::throw_item(), thrown_item, npc::wield(), and npc::wont_hit_friend().
Member Data Documentation
thrown_item
item& npc_attack_throw::thrown_item private
Definition at line 116 of file npc_attack.h.
Referenced by base_penalty(), can_use(), evaluate(), evaluate_tripoint(), targetable_points(), and use().
The documentation for this class was generated from the following files:
src/npc_attack.h
src/npc_attack.cpp