Cataclysm DDA: building_bin Class Reference
building_bin Class Reference
#include <regional_settings.h>
Public Member Functions
building_bin ()=default
void add (const overmap_special_id &building, int weight)
overmap_special_id pick () const
void clear ()
void finalize ()
weighted_int_list< overmap_special_id > get_all_buildings () const
Public Attributes
std::vector< std::string > all
Private Attributes
bool finalized = false
weighted_int_list< overmap_special_id > buildings
std::map< overmap_special_id, int > unfinalized_buildings
Detailed Description
Definition at line 23 of file regional_settings.h.
Constructor & Destructor Documentation
building_bin()
building_bin::building_bin () default
Member Function Documentation
add()
void building_bin::add (const overmap_special_id & building, int weight)
Definition at line 1072 of file regional_settings.cpp.
 {
     if( finalized ) {
         debugmsg( "Tried to add special %s to a finalized building bin", building.c_str() );
         return;
     }
     unfinalized_buildings[ building ] = weight;
 }
References string_id< T >::c_str(), debugmsg, finalized, and unfinalized_buildings.
Referenced by load_forest_trail_settings().
clear()
void building_bin::clear ()
Definition at line 1093 of file regional_settings.cpp.
 {
     finalized = false;
     buildings.clear();
     unfinalized_buildings.clear();
     all.clear();
 }
References all, buildings, finalized, and unfinalized_buildings.
finalize()
void building_bin::finalize ()
Definition at line 1101 of file regional_settings.cpp.
 {
     if( finalized ) {
         debugmsg( "Tried to finalize a finalized bin (that's a code-side error which can't be fixed with jsons)" );
         return;
     }
     if( unfinalized_buildings.empty() ) {
         debugmsg( "There must be at least one entry in this building bin." );
         return;
     }
     for( const std::pair<const overmap_special_id, int> &pr : unfinalized_buildings ) {
         overmap_special_id current_id = pr.first;
         if( !current_id.is_valid() ) {
             // First, try to convert oter to special
             string_id<oter_type_t> converted_id( pr.first.str() );
             if( !converted_id.is_valid() ) {
                 debugmsg( "Tried to add city building %s, but it is neither a special nor a terrain type",
                           pr.first.c_str() );
                 continue;
             } else {
                 all.emplace_back( pr.first.str() );
             }
             current_id = overmap_specials::create_building_from( converted_id );
         }
         buildings.add( current_id, pr.second );
     }
     finalized = true;
 }
References all, buildings, overmap_specials::create_building_from(), debugmsg, finalized, string_id< T >::is_valid(), and unfinalized_buildings.
Referenced by city_settings::finalize(), and forest_trail_settings::finalize().
get_all_buildings()
weighted_int_list<overmap_special_id> building_bin::get_all_buildings () const inline
Definition at line 36 of file regional_settings.h.
{
             return buildings;
         }
References buildings.
Referenced by city_settings::get_all_houses(), city_settings::get_all_parks(), and city_settings::get_all_shops().
pick()
overmap_special_id building_bin::pick () const
Definition at line 1082 of file regional_settings.cpp.
 {
     if( !finalized ) {
         debugmsg( "Tried to pick a special out of a non-finalized bin" );
         overmap_special_id null_special( "null" );
         return null_special;
     }
     return *buildings.pick();
 }
References buildings, debugmsg, and finalized.
Referenced by city_settings::pick_house(), city_settings::pick_park(), city_settings::pick_shop(), and overmap::place_forest_trailheads().
Member Data Documentation
all
std::vector<std::string> building_bin::all
Definition at line 33 of file regional_settings.h.
Referenced by clear(), and finalize().
buildings
weighted_int_list<overmap_special_id> building_bin::buildings private
Definition at line 27 of file regional_settings.h.
Referenced by clear(), finalize(), get_all_buildings(), and pick().
finalized
bool building_bin::finalized = false private
Definition at line 26 of file regional_settings.h.
Referenced by add(), clear(), finalize(), and pick().
unfinalized_buildings
std::map<overmap_special_id, int> building_bin::unfinalized_buildings private
Definition at line 28 of file regional_settings.h.
Referenced by add(), clear(), and finalize().
The documentation for this class was generated from the following files:
src/regional_settings.h
src/regional_settings.cpp