Cataclysm DDA: ammobelt_actor Class Reference
ammobelt_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
ammobelt_actor ()
what type of belt is created with this linkage?
~ammobelt_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
itype_id belt
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 756 of file iuse_actor.h.
Constructor & Destructor Documentation
ammobelt_actor()
ammobelt_actor::ammobelt_actor () inline
what type of belt is created with this linkage?
Definition at line 761 of file iuse_actor.h.
 : iuse_actor( "ammobelt" ) {}
~ammobelt_actor()
ammobelt_actor::~ammobelt_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > ammobelt_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2626 of file iuse_actor.cpp.
 {
     return std::make_unique<ammobelt_actor>( *this );
 }
info()
void ammobelt_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 2636 of file iuse_actor.cpp.
 {
     dump.emplace_back( "AMMO", string_format( _( "Can be used to assemble: %s" ),
                        item::nname( belt ) ) );
 }
References _, belt, item::nname(), and string_format().
load()
void ammobelt_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2631 of file iuse_actor.cpp.
 {
     belt = itype_id( obj.get_string( "belt" ) );
 }
References belt, JsonObject::get_string(), and itype_id.
use()
std::optional< int > ammobelt_actor::use (Character * p, item & , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 2642 of file iuse_actor.cpp.
 {
     item mag( belt );
     mag.ammo_unset();
     if( p->rate_action_reload( mag ) != hint_rating::good ) {
         p->add_msg_if_player( _( "Insufficient ammunition to assemble %s" ), mag.tname() );
         return std::nullopt;
     }
     item_location loc = p->i_add( mag );
     item::reload_option opt = p->select_ammo( loc, true );
     if( opt ) {
         p->assign_activity( reload_activity_actor( std::move( opt ) ) );
     } else {
         loc.remove_item();
     }
     return 0;
 }
References _, Character::add_msg_if_player(), item::ammo_unset(), Character::assign_activity(), belt, good, Character::i_add(), Character::rate_action_reload(), item_location::remove_item(), Character::select_ammo(), and item::tname().
Member Data Documentation
belt
itype_id ammobelt_actor::belt
Definition at line 759 of file iuse_actor.h.
Referenced by info(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp