Cataclysm DDA: message_iuse Class Reference
message_iuse Class Reference
#include <iuse_actor.h>
Public Member Functions
message_iuse (const std::string &type="message")
~message_iuse () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
std::string get_name () const override
Returns the translated name of the action.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
translation name
if specified overrides default action name
translation message
message if player sees activation with s replaced by item name
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 147 of file iuse_actor.h.
Constructor & Destructor Documentation
message_iuse()
message_iuse::message_iuse (const std::string & type = "message") inline explicit
Definition at line 150 of file iuse_actor.h.
 : iuse_actor( type ) {}
~message_iuse()
message_iuse::~message_iuse () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > message_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 531 of file iuse_actor.cpp.
 {
     return std::make_unique<message_iuse>( *this );
 }
get_name()
std::string message_iuse::get_name () const override virtual
Returns the translated name of the action.
It is used for the item action menu.
Reimplemented from iuse_actor.
Definition at line 556 of file iuse_actor.cpp.
 {
     if( !name.empty() ) {
         return name.translated();
     }
     return iuse_actor::get_name();
 }
References translation::empty(), iuse_actor::get_name(), name, and translation::translated().
load()
void message_iuse::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 536 of file iuse_actor.cpp.
 {
     obj.read( "name", name );
     obj.read( "message", message );
 }
References message, name, and JsonObject::read().
use()
std::optional< int > message_iuse::use (Character * p, item & it, const tripoint & pos) const override virtual
Implements iuse_actor.
Definition at line 542 of file iuse_actor.cpp.
 {
     if( !p ) {
         return std::nullopt;
     }
     if( p->sees( pos ) && !message.empty() ) {
         p->add_msg_if_player( m_info, message.translated(), it.tname() );
     }
     return 0;
 }
References Character::add_msg_if_player(), translation::empty(), m_info, message, math_opers::pos(), Character::sees(), item::tname(), and translation::translated().
Member Data Documentation
message
translation message_iuse::message
message if player sees activation with s replaced by item name
Definition at line 156 of file iuse_actor.h.
Referenced by load(), and use().
name
translation message_iuse::name
if specified overrides default action name
Definition at line 153 of file iuse_actor.h.
Referenced by get_name(), and load().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp