Cataclysm DDA: inventory_holster_preset Class Reference
inventory_holster_preset Class Reference
#include <inventory_ui.h>
Public Member Functions
inventory_holster_preset (item_location holster, Character *c)
const item_location & get_holster () const
bool is_shown (const item_location &contained) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &it) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Private Attributes
item_location holster
Character * who = nullptr
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 319 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_holster_preset()
inventory_holster_preset::inventory_holster_preset (item_location holster, Character * c) inline explicit
Definition at line 322 of file inventory_ui.h.
             : holster( std::move( holster ) ), who( c ) {
         }
Member Function Documentation
get_denial()
std::string inventory_holster_preset::get_denial (const item_location &) const override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 853 of file inventory_ui.cpp.
 {
     if( who->is_worn( *it ) ) {
         ret_val<void> const ret = who->can_takeoff( *it );
         if( !ret.success() ) {
             return ret.str();
         }
     }
     if( it->is_bucket_nonempty() ) {
         return "item would spill";
     }
     item item_copy( *it );
     item_copy.charges = 1;
     item_location parent = it.has_parent() ? it.parent_item() : item_location();
     ret_val<void> ret = holster->can_contain( item_copy, false, false, true, false, parent );
     if( !ret.success() ) {
         return !ret.str().empty() ? ret.str() : "item can't be stored there";
     }
     ret = holster.parents_can_contain_recursive( &item_copy );
     if( !ret.success() ) {
         return !ret.str().empty() ? ret.str() : "item can't be stored there";
     }
     return {};
 }
References item::charges, item_location::has_parent(), game_menus::inv::holster(), item::is_bucket_nonempty(), item_location::parent_item(), and cata::hash64_detail::ret.
get_holster()
const item_location & inventory_holster_preset::get_holster () const
Definition at line 825 of file inventory_ui.cpp.
 {
     return holster;
 }
References game_menus::inv::holster().
is_shown()
bool inventory_holster_preset::is_shown (const item_location & contained) const override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 830 of file inventory_ui.cpp.
 {
     if( contained == holster ) {
         return false;
     }
     if( contained.eventually_contains( holster ) || holster.eventually_contains( contained ) ) {
         return false;
     }
     if( !is_container( contained ) && contained->made_of( phase_id::LIQUID ) &&
         !contained->is_frozen_liquid() ) {
         // spilt liquid cannot be picked up
         return false;
     }
     //only hide if it is in the toplevel of holster (to allow shuffling of items inside a bag)
     for( const item *it : holster->all_items_top() ) {
         if( it == contained.get_item() ) {
             return false;
         }
     }
     return true;
 }
References item_location::eventually_contains(), item_location::get_item(), game_menus::inv::holster(), anonymous_namespace{inventory_ui.cpp}::is_container(), item::is_frozen_liquid(), LIQUID, and item::made_of().
Member Data Documentation
holster
item_location inventory_holster_preset::holster private
Definition at line 331 of file inventory_ui.h.
who
Character* inventory_holster_preset::who = nullptr private
Definition at line 332 of file inventory_ui.h.
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp