Cataclysm DDA: DefaultRemovePartHandler Class Reference
DefaultRemovePartHandler Class Reference
#include <vehicle.h>
Public Member Functions
~DefaultRemovePartHandler () override=default
void unboard (const tripoint &loc) override
void add_item_or_charges (const tripoint &loc, item it, bool) override
void set_transparency_cache_dirty (const int z) override
void set_floor_cache_dirty (const int z) override
void removed (vehicle &veh, int part) override
void spawn_animal_from_part (item &base, const tripoint &loc) override
map & get_map_ref () override
Public Member Functions inherited from RemovePartHandler
virtual ~RemovePartHandler ()=default
Detailed Description
Definition at line 2404 of file vehicle.h.
Constructor & Destructor Documentation
~DefaultRemovePartHandler()
DefaultRemovePartHandler::~DefaultRemovePartHandler () override default
Member Function Documentation
add_item_or_charges()
void DefaultRemovePartHandler::add_item_or_charges (const tripoint & loc, item it, bool) inline override virtual
Implements RemovePartHandler.
Definition at line 2412 of file vehicle.h.
{
             get_map().add_item_or_charges( loc, std::move( it ) );
         }
References map::add_item_or_charges(), and get_map().
get_map_ref()
map& DefaultRemovePartHandler::get_map_ref () inline override virtual
Implements RemovePartHandler.
Definition at line 2427 of file vehicle.h.
{
             return get_map();
         }
References get_map().
removed()
void DefaultRemovePartHandler::removed (vehicle & veh, int part) override virtual
Implements RemovePartHandler.
Definition at line 148 of file vehicle.cpp.
 {
     avatar &player_character = get_avatar();
     const vehicle_part &vp = veh.part( part );
     const tripoint part_pos = veh.global_part_pos3( vp );
     // If the player is currently working on the removed part, stop them as it's futile now.
     const player_activity &act = player_character.activity;
     map &here = get_map();
     if( act.id() == ACT_VEHICLE && act.moves_left > 0 && act.values.size() > 6 ) {
         if( veh_pointer_or_null( here.veh_at( tripoint( act.values[0], act.values[1],
                                               player_character.posz() ) ) ) == &veh ) {
             if( act.values[6] >= part ) {
                 player_character.cancel_activity();
                 add_msg( m_info, _( "The vehicle part you were working on has gone!" ) );
             }
         }
     }
     // TODO: maybe do this for all the nearby NPCs as well?
     if( player_character.get_grab_type() == object_type::VEHICLE &&
         player_character.pos() + player_character.grab_point == part_pos ) {
         if( veh.parts_at_relative( vp.mount, false ).empty() ) {
             add_msg( m_info, _( "The vehicle part you were holding has been destroyed!" ) );
             player_character.grab( object_type::NONE );
         }
     }
     here.dirty_vehicle_list.insert( &veh );
     here.clear_vehicle_point_from_cache( &veh, part_pos );
     here.add_vehicle_to_cache( &veh );
     here.memory_cache_dec_set_dirty( part_pos, true );
     player_character.memorize_clear_decoration(
         here.getglobal( part_pos ), "vp_" + vp.info().id.str() );
 }
References _, act, ACT_VEHICLE, Character::activity, add_msg(), map::add_vehicle_to_cache(), Character::cancel_activity(), map::clear_vehicle_point_from_cache(), map::dirty_vehicle_list, get_avatar(), avatar::get_grab_type(), get_map(), map::getglobal(), vehicle::global_part_pos3(), avatar::grab(), Character::grab_point, string_id< T >::id(), vpart_info::id, vehicle_part::info(), m_info, avatar::memorize_clear_decoration(), map::memory_cache_dec_set_dirty(), vehicle_part::mount, NONE, vehicle::part(), vehicle::parts_at_relative(), Creature::pos(), Creature::posz(), string_id< T >::str(), map::veh_at(), veh_pointer_or_null(), and VEHICLE.
set_floor_cache_dirty()
void DefaultRemovePartHandler::set_floor_cache_dirty (const int z) inline override virtual
Implements RemovePartHandler.
Definition at line 2420 of file vehicle.h.
{
             get_map().set_floor_cache_dirty( z );
         }
References get_map(), and map::set_floor_cache_dirty().
set_transparency_cache_dirty()
void DefaultRemovePartHandler::set_transparency_cache_dirty (const int z) inline override virtual
Implements RemovePartHandler.
Definition at line 2415 of file vehicle.h.
{
             map &here = get_map();
             here.set_transparency_cache_dirty( z );
             here.set_seen_cache_dirty( tripoint_zero );
         }
References get_map(), map::set_seen_cache_dirty(), map::set_transparency_cache_dirty(), and tripoint_zero.
spawn_animal_from_part()
void DefaultRemovePartHandler::spawn_animal_from_part (item & base, const tripoint & loc) inline override virtual
Implements RemovePartHandler.
Definition at line 2424 of file vehicle.h.
{
             base.release_monster( loc, 1 );
         }
References item::release_monster().
unboard()
void DefaultRemovePartHandler::unboard (const tripoint & loc) inline override virtual
Implements RemovePartHandler.
Definition at line 2409 of file vehicle.h.
{
             get_map().unboard_vehicle( loc );
         }
References get_map(), and map::unboard_vehicle().
The documentation for this class was generated from the following files:
src/vehicle.h
src/vehicle.cpp