Cataclysm DDA: jmapgen_monster Class Reference
jmapgen_monster Class Reference
Place spawn points for a specific monster.
Public Member Functions
jmapgen_monster (const JsonObject &jsi, const std::string_view)
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
weighted_int_list< mapgen_value< mtype_id > > ids
mapgen_value< mongroup_id > m_id
jmapgen_int chance
jmapgen_int pack_size
bool one_or_none
bool friendly
std::optional< translation > name = std::nullopt
std::string random_name_str
bool target
bool use_pack_size
struct spawn_data data
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place spawn points for a specific monster.
"monster": id of the monster. or "group": id of the monster group. "friendly": whether the new monster is friendly to the player character. "name": the name of the monster (if it has one). "chance": the percentage chance of a monster, affected by spawn density If high density means greater than one hundred percent, can place multiples. "repeat": roll this many times for creatures, potentially spawning multiples. "pack_size": place this many creatures each time a roll is successful. "one_or_none": place max of 1 (or pack_size) monsters, even if spawn density > 1. Defaults to true if repeat and pack_size are unset, false if one is set.
Definition at line 2406 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_monster()
jmapgen_monster::jmapgen_monster (const JsonObject & jsi, const std::string_view) inline
Definition at line 2420 of file mapgen.cpp.
                                                                         :
             chance( jsi, "chance", 100, 100 )
             , pack_size( jsi, "pack_size", 1, 1 )
             , one_or_none( jsi.get_bool( "one_or_none",
                                          !( jsi.has_member( "repeat" ) ||
                                             jsi.has_member( "pack_size" ) ) ) )
             , friendly( jsi.get_bool( "friendly", false ) )
             , random_name_str( jsi.get_string( "random_name", "" ) )
             , target( jsi.get_bool( "target", false ) )
             , use_pack_size( jsi.get_bool( "use_pack_size", false ) ) {
             {
                 translation translated_name;
                 if( jsi.read( "name", translated_name ) ) {
                     name.emplace( std::move( translated_name ) );
                 } else if( random_name_str == "snippet" ) {
                     debugmsg( "Field \"name\" is missing for random name 'snippet'" );
                 }
             }
             if( jsi.has_member( "group" ) ) {
                 jsi.read( "group", m_id );
             } else if( jsi.has_array( "monster" ) ) {
                 load_weighted_list( jsi.get_member( "monster" ), ids, 100 );
             } else {
                 mapgen_value<mtype_id> id( jsi.get_member( "monster" ) );
                 ids.add( id, 100 );
             }
             std::set<std::string> valid_random_name_strs = { "random", "female", "male", "snippet", "" };
             if( valid_random_name_strs.count( random_name_str ) == 0 ) {
                 debugmsg( "Invalid random name '%s'", random_name_str );
             }
             if( jsi.has_object( "spawn_data" ) ) {
                 const JsonObject &sd = jsi.get_object( "spawn_data" );
                 if( sd.has_array( "ammo" ) ) {
                     const JsonArray &ammos = sd.get_array( "ammo" );
                     for( const JsonObject adata : ammos ) {
                         data.ammo.emplace( itype_id( adata.get_string( "ammo_id" ) ),
                                            jmapgen_int( adata, "qty" ) );
                     }
                 }
                 if( sd.has_array( "patrol" ) ) {
                     const JsonArray &patrol_pts = sd.get_array( "patrol" );
                     for( const JsonObject p_pt : patrol_pts ) {
                         jmapgen_int ptx = jmapgen_int( p_pt, "x" );
                         jmapgen_int pty = jmapgen_int( p_pt, "y" );
                         data.patrol_points_rel_ms.emplace_back( ptx.get(), pty.get() );
                     }
                 }
             }
         }
References spawn_data::ammo, data, debugmsg, jmapgen_int::get(), JsonObject::get_array(), JsonObject::get_member(), JsonObject::get_object(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), base_camps::id, ids, itype_id, mapgen_defer::jsi, load_weighted_list(), m_id, name, spawn_data::patrol_points_rel_ms, random_name_str, and JsonObject::read().
Member Function Documentation
apply()
void jmapgen_monster::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2483 of file mapgen.cpp.
{
             int raw_odds = chance.get();
             // Handle spawn density: Increase odds, but don't let the odds of absence go below
             // half the odds at density 1.
             // Instead, apply a multiplier to the number of monsters for really high densities.
             // For example, a 50% chance at spawn density 4 becomes a 75% chance of ~2.7 monsters.
             int odds_after_density = raw_odds * get_option<float>( "SPAWN_DENSITY" );
             int max_odds = ( 100 + raw_odds ) / 2;
             float density_multiplier = 1.0f;
             if( odds_after_density > max_odds ) {
                 density_multiplier = 1.0f * odds_after_density / max_odds;
                 odds_after_density = max_odds;
             }
             int mission_id = -1;
             if( dat.mission() && target ) {
                 mission_id = dat.mission()->get_id();
             }
             int spawn_count = roll_remainder( density_multiplier );
             // don't let high spawn density alone cause more than 1 to spawn.
             if( one_or_none ) {
                 spawn_count = std::min( spawn_count, 1 );
             }
             // don't spawn less than 1 if odds were 100%, even with low spawn density.
             if( raw_odds == 100 ) {
                 spawn_count = std::max( spawn_count, 1 );
             } else {
                 if( !x_in_y( odds_after_density, 100 ) ) {
                     return;
                 }
             }
             mongroup_id chosen_group = m_id.get( dat );
             std::optional<std::string> chosen_name = std::nullopt;
             if( !random_name_str.empty() ) {
                 if( random_name_str == "female" ) {
                     chosen_name.emplace( SNIPPET.expand( "<female_given_name>" ) );
                 } else if( random_name_str == "male" ) {
                     chosen_name.emplace( SNIPPET.expand( "<male_given_name>" ) );
                 } else if( random_name_str == "random" ) {
                     chosen_name.emplace( SNIPPET.expand( "<given_name>" ) );
                 } else if( random_name_str == "snippet" && name.has_value() ) {
                     chosen_name.emplace( SNIPPET.expand( name.value().translated() ) );
                 }
             }
             if( !chosen_name.has_value() && name.has_value() ) {
                 chosen_name.emplace( name.value().translated() );
             }
             if( !chosen_group.is_null() ) {
                 std::vector<MonsterGroupResult> spawn_details =
                     MonsterGroupManager::GetResultFromGroup( chosen_group, nullptr, nullptr, false, nullptr,
                             use_pack_size );
                 for( const MonsterGroupResult &mgr : spawn_details ) {
                     dat.m.add_spawn( mgr.name, spawn_count * pack_size.get(),
                     { x.get(), y.get(), dat.zlevel() + z.get()},
                     friendly, -1, mission_id, chosen_name, data );
                 }
             } else if( ids.is_valid() ) {
                 mtype_id chosen_type = ids.pick()->get( dat );
                 if( !chosen_type.is_null() ) {
                     dat.m.add_spawn( chosen_type, spawn_count * pack_size.get(),
                     { x.get(), y.get(), dat.zlevel() + z.get()},
                     friendly, -1, mission_id, chosen_name, data );
                 }
             }
         }
References map::add_spawn(), chance, data, snippet_library::expand(), friendly, jmapgen_int::get(), mission::get_id(), MonsterGroupManager::GetResultFromGroup(), ids, string_id< T >::is_null(), mapgendata::m, m_id, max(), min(), mapgendata::mission(), name, one_or_none, pack_size, random_name_str, roll_remainder(), SNIPPET, target, use_pack_size, and x_in_y().
check()
void jmapgen_monster::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 2474 of file mapgen.cpp.
{
             for( const weighted_object<int, mapgen_value<mtype_id>> &id : ids ) {
                 id.obj.check( oter_name, parameters );
             }
             m_id.check( oter_name, parameters );
         }
References ids, and m_id.
Member Data Documentation
chance
jmapgen_int jmapgen_monster::chance
Definition at line 2411 of file mapgen.cpp.
Referenced by apply().
data
struct spawn_data jmapgen_monster::data
Definition at line 2418 of file mapgen.cpp.
Referenced by apply(), and jmapgen_monster().
friendly
bool jmapgen_monster::friendly
Definition at line 2414 of file mapgen.cpp.
Referenced by apply().
ids
weighted_int_list<mapgen_value<mtype_id> > jmapgen_monster::ids
Definition at line 2409 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_monster().
m_id
mapgen_value<mongroup_id> jmapgen_monster::m_id
Definition at line 2410 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_monster().
name
std::optional<translation> jmapgen_monster::name = std::nullopt
Definition at line 2415 of file mapgen.cpp.
Referenced by apply(), and jmapgen_monster().
one_or_none
bool jmapgen_monster::one_or_none
Definition at line 2413 of file mapgen.cpp.
Referenced by apply().
pack_size
jmapgen_int jmapgen_monster::pack_size
Definition at line 2412 of file mapgen.cpp.
Referenced by apply().
random_name_str
std::string jmapgen_monster::random_name_str
Definition at line 2416 of file mapgen.cpp.
Referenced by apply(), and jmapgen_monster().
target
bool jmapgen_monster::target
Definition at line 2417 of file mapgen.cpp.
Referenced by apply().
use_pack_size
bool jmapgen_monster::use_pack_size
Definition at line 2418 of file mapgen.cpp.
Referenced by apply().
The documentation for this class was generated from the following file:
src/mapgen.cpp