Cataclysm DDA: safecracking_activity_actor Class Reference
safecracking_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
safecracking_activity_actor (const tripoint &safe)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static time_duration safecracking_time (const Character &who)
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
Private Attributes
tripoint safe
int exp_step = 0
Detailed Description
Definition at line 867 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
safecracking_activity_actor()
safecracking_activity_actor::safecracking_activity_actor (const tripoint & safe) inline explicit
Definition at line 870 of file activity_actor_definitions.h.
 : safe( safe ) {};
Referenced by deserialize().
Member Function Documentation
can_resume_with_internal()
bool safecracking_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override private virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 893 of file activity_actor_definitions.h.
{
             const safecracking_activity_actor &actor = static_cast<const safecracking_activity_actor &>
                     ( other );
             return actor.safe == safe;
         }
References other, and safe.
clone()
std::unique_ptr<activity_actor> safecracking_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 882 of file activity_actor_definitions.h.
{
             return std::make_unique<safecracking_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > safecracking_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 3457 of file activity_actor.cpp.
 {
     safecracking_activity_actor actor = safecracking_activity_actor( {} );
     JsonObject data = jsin.get_object();
     data.read( "safe", actor.safe );
     data.read( "exp_step", actor.exp_step );
     return actor.clone();
 }
References clone(), exp_step, JsonValue::get_object(), JsonObject::read(), safe, and safecracking_activity_actor().
do_turn()
void safecracking_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 3399 of file activity_actor.cpp.
 {
     bool can_crack = who.has_flag( json_flag_SAFECRACK_NO_TOOL );
     // short-circuit to avoid the more expensive iteration over items
     can_crack = can_crack || who.cache_has_item_with( flag_SAFECRACK );
     if( !can_crack ) {
         // We lost our cracking tool somehow, bail out.
         act.set_to_null();
         return;
     }
     if( calendar::once_every( 5_minutes ) ) {
         add_msg_debug( debugmode::DF_ACT_SAFECRACKING, "safecracking time left = %s",
                        to_string_writable( time_duration::from_moves( act.moves_left ) ) );
     }
     /* Split experience gain in 20 parts, each giving 5% of the total*/
     const int current_step =
         ( 100 * ( act.moves_total - act.moves_left ) / act.moves_total ) / 5;
     const int difference = current_step - exp_step ;
     if( difference > 0 ) {
         exp_step += difference;
         if( !who.has_proficiency( proficiency_prof_safecracking ) ) {
             who.practice_proficiency( proficiency_prof_safecracking, 3_minutes * difference );
             // player gained the proficiency mid-way through cracking
             if( who.has_proficiency( proficiency_prof_safecracking ) ) {
                 int new_time = to_moves<int>( safecracking_time( who ) );
                 act.moves_total = act.moves_total > new_time ? new_time : act.moves_total;
                 act.moves_left = act.moves_left > new_time ? new_time : act.moves_left;
             }
         }
         const float skill_level = who.get_skill_level( skill_traps );
         who.practice( skill_traps, std::max( 1.0f,  skill_level / 2 ) );
         if( who.get_skill_level( skill_traps ) > skill_level ) {
             int new_time = to_moves<int>( safecracking_time( who ) );
             act.moves_total = act.moves_total > new_time ? new_time : act.moves_total;
             act.moves_left = act.moves_left > new_time ? new_time : act.moves_left;
         }
     }
 }
References act, add_msg_debug, Character::cache_has_item_with(), debugmode::DF_ACT_SAFECRACKING, exp_step, flag_SAFECRACK, time_duration::from_moves(), Character::get_skill_level(), Character::has_flag(), Character::has_proficiency(), json_flag_SAFECRACK_NO_TOOL, max(), calendar::once_every(), Character::practice(), Character::practice_proficiency(), proficiency_prof_safecracking, safecracking_time(), skill_traps, and to_string_writable().
finish()
void safecracking_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 3442 of file activity_actor.cpp.
 {
     who.add_msg_if_player( m_good, _( "With a satisfying click, the lock on the safe opens!" ) );
     get_map().furn_set( safe, furn_f_safe_c );
     act.set_to_null();
 }
References _, act, Character::add_msg_if_player(), furn_f_safe_c, map::furn_set(), get_map(), m_good, and safe.
get_type()
activity_id safecracking_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 872 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_CRACKING" );
         }
References activity_id.
safecracking_time()
time_duration safecracking_activity_actor::safecracking_time (const Character & who) static
@EFFECT_DEVICES decreases time needed for safe cracking
Perception decreases time needed for safe cracking
Definition at line 3365 of file activity_actor.cpp.
 {
     time_duration cracking_time = 150_minutes;
     /** @EFFECT_DEVICES decreases time needed for safe cracking */
     cracking_time -= 20_minutes * ( who.get_skill_level( skill_traps ) - 3 ) ;
     /** @EFFECT_PER decreases time needed for safe cracking */
     cracking_time -= 10_minutes * ( who.get_per() - 8 );
     cracking_time = std::max( 30_minutes, cracking_time );
     if( !who.has_proficiency( proficiency_prof_safecracking ) ) {
         cracking_time *= 3;
     }
     return cracking_time;
 }
References Character::get_per(), Character::get_skill_level(), Character::has_proficiency(), max(), proficiency_prof_safecracking, and skill_traps.
Referenced by do_turn(), and start().
serialize()
void safecracking_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 3449 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "safe", safe );
     jsout.member( "exp_step", exp_step );
     jsout.end_object();
 }
References JsonOut::end_object(), exp_step, JsonOut::member(), safe, and JsonOut::start_object().
start()
void safecracking_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 3381 of file activity_actor.cpp.
 {
     time_duration cracking_time = safecracking_time( who );
     if( who.is_avatar() ) {
         add_msg( m_info, _( "You start cracking the safe." ) );
     } else { // who.is_npc
         // npcs can't crack safes yet, this is for when they are able to
         add_msg_if_player_sees( who, _( "%1$s starts cracking the safe." ), who.disp_name() );
     }
     add_msg_debug( debugmode::DF_ACT_SAFECRACKING, "safecracking time = %s",
                    to_string_writable( cracking_time ) );
     act.moves_total = to_moves<int>( cracking_time );
     act.moves_left = act.moves_total;
 }
References _, act, add_msg(), add_msg_debug, add_msg_if_player_sees(), debugmode::DF_ACT_SAFECRACKING, Character::disp_name(), Creature::is_avatar(), m_info, safecracking_time(), and to_string_writable().
Member Data Documentation
exp_step
int safecracking_activity_actor::exp_step = 0 private
Definition at line 891 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
safe
tripoint safecracking_activity_actor::safe private
Definition at line 890 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp