Cataclysm DDA: autodrive_activity_actor Class Reference
autodrive_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
autodrive_activity_actor ()=default
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void canceled (player_activity &, Character &) override
Called just before Character::cancel_activity() executes.
void finish (player_activity &act, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
void update_player_vehicle (Character &)
Private Attributes
vehicle * player_vehicle = nullptr
Detailed Description
Definition at line 113 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
autodrive_activity_actor()
autodrive_activity_actor::autodrive_activity_actor () default
Referenced by deserialize().
Member Function Documentation
canceled()
void autodrive_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 615 of file activity_actor.cpp.
 {
     // The activity might be canceled because the driver got unboarded, in which case we may not have a valid pointer anymore (e.g. summoned vehicle).
     update_player_vehicle( who );
     who.add_msg_if_player( m_info, _( "Auto drive canceled." ) );
     if( player_vehicle ) {
         player_vehicle->stop_autodriving( false );
     }
     act.set_to_null();
 }
References _, act, Character::add_msg_if_player(), m_info, player_vehicle, vehicle::stop_autodriving(), and update_player_vehicle().
clone()
std::unique_ptr<activity_actor> autodrive_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 136 of file activity_actor_definitions.h.
{
             return std::make_unique<autodrive_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > autodrive_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 640 of file activity_actor.cpp.
 {
     return autodrive_activity_actor().clone();
 }
References autodrive_activity_actor().
do_turn()
void autodrive_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 586 of file activity_actor.cpp.
 {
     if( who.in_vehicle && who.controlling_vehicle && player_vehicle ) {
         if( who.get_moves() <= 0 ) {
             // out of moves? the driver's not doing anything this turn
             // (but the vehicle will continue moving)
             return;
         }
         switch( player_vehicle->do_autodrive( who ) ) {
             case autodrive_result::ok:
                 if( who.get_moves() > 0 ) {
                     // if do_autodrive() didn't eat up all our moves, end the turn
                     // equivalent to player pressing the "pause" button
                     who.set_moves( 0 );
                 }
                 sounds::reset_markers();
                 break;
             case autodrive_result::abort:
                 who.cancel_activity();
                 break;
             case autodrive_result::finished:
                 act.moves_left = 0;
                 break;
         }
     } else {
         who.cancel_activity();
     }
 }
References abort, act, Character::cancel_activity(), Character::controlling_vehicle, vehicle::do_autodrive(), finished, Creature::get_moves(), Character::in_vehicle, ok, player_vehicle, sounds::reset_markers(), and Creature::set_moves().
finish()
void autodrive_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 627 of file activity_actor.cpp.
 {
     who.add_msg_if_player( m_info, _( "You have reached your destination." ) );
     player_vehicle->stop_autodriving( false );
     act.set_to_null();
 }
References _, act, Character::add_msg_if_player(), m_info, player_vehicle, and vehicle::stop_autodriving().
get_type()
activity_id autodrive_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 127 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_AUTODRIVE" );
         }
References activity_id.
serialize()
void autodrive_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 634 of file activity_actor.cpp.
 {
     // Activity is not being saved but still provide some valid json if called.
     jsout.write_null();
 }
References JsonOut::write_null().
start()
void autodrive_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 576 of file activity_actor.cpp.
 {
     update_player_vehicle( who );
     if( player_vehicle == nullptr ) {
         who.cancel_activity();
     } else {
         player_vehicle->is_autodriving = true;
     }
 }
References Character::cancel_activity(), vehicle::is_autodriving, player_vehicle, and update_player_vehicle().
update_player_vehicle()
void autodrive_activity_actor::update_player_vehicle (Character & who) private
Definition at line 565 of file activity_actor.cpp.
 {
     const bool in_vehicle = who.in_vehicle && who.controlling_vehicle;
     const optional_vpart_position vp = get_map().veh_at( who.pos() );
     if( !( vp && in_vehicle ) ) {
         player_vehicle = nullptr;
     } else {
         player_vehicle = &vp->vehicle();
     }
 }
References Character::controlling_vehicle, get_map(), Character::in_vehicle, player_vehicle, Creature::pos(), and map::veh_at().
Referenced by canceled(), and start().
Member Data Documentation
player_vehicle
vehicle* autodrive_activity_actor::player_vehicle = nullptr private
Definition at line 119 of file activity_actor_definitions.h.
Referenced by canceled(), do_turn(), finish(), start(), and update_player_vehicle().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp