Cataclysm DDA: armor_inventory_preset Class Reference
armor_inventory_preset Class Reference
Public Member Functions
armor_inventory_preset (Character &pl, const std::string &color_in)
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool is_shown (const item_location &) const
Does this entry satisfy the basic preset conditions?
virtual std::string get_denial (const item_location &) const
The reason why this entry cannot be selected.
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Protected Attributes
Character & you
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Private Member Functions
std::string get_number_string (int number) const
std::string get_decimal_string (double number) const
Private Attributes
const std::string color
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Detailed Description
Definition at line 341 of file game_inventory.cpp.
Constructor & Destructor Documentation
armor_inventory_preset()
armor_inventory_preset::armor_inventory_preset (Character & pl, const std::string & color_in) inline
Definition at line 344 of file game_inventory.cpp.
                                                                            :
             you( pl ), color( color_in ) {
             append_cell( [ this ]( const item_location & loc ) {
                 return get_number_string( loc->get_avg_encumber( you ) );
             }, _( "AVG ENCUMBRANCE" ) );
             append_cell( [ this ]( const item_location & loc ) {
                 return string_format( "<%s>%d%%</color>", color, loc->get_avg_coverage() );
             }, _( "AVG COVERAGE" ) );
             append_cell( [ this ]( const item_location & loc ) {
                 return get_number_string( loc->get_warmth() );
             }, _( "WARMTH" ) );
             for( const damage_type &dt : damage_type::get_all() ) {
                 if( dt.no_resist ) {
                     continue;
                 }
                 const damage_type_id &dtid = dt.id;
                 append_cell( [ this, dtid ]( const item_location & loc ) {
                     return get_decimal_string( loc->resist( dtid ) );
                 }, to_upper_case( dt.name.translated() ) );
             }
             append_cell( [ this ]( const item_location & loc ) {
                 return get_number_string( loc->get_env_resist() );
             }, _( "ENV" ) );
             // Show total storage capacity in user's preferred volume units, to 2 decimal places
             append_cell( [ this ]( const item_location & loc ) {
                 const int storage_ml = to_milliliter( loc->get_total_capacity() );
                 return get_decimal_string( round_up( convert_volume( storage_ml ), 2 ) );
             }, string_format( _( "STORAGE (%s)" ), volume_units_abbr() ) );
         }
References _, inventory_selector_preset::append_cell(), color, convert_volume(), damage_type::get_all(), item::get_avg_coverage(), item::get_avg_encumber(), get_decimal_string(), item::get_env_resist(), get_number_string(), item::get_total_capacity(), item::get_warmth(), string_id< T >::id(), item::resist(), round_up(), string_format(), units::to_milliliter(), to_upper_case(), volume_units_abbr(), and you.
Member Function Documentation
get_decimal_string()
std::string armor_inventory_preset::get_decimal_string (double number) const inline private
Definition at line 385 of file game_inventory.cpp.
{
             return number ? string_format( "<%s>%.2f</color>", color, number ) : std::string();
         }
References color, and string_format().
Referenced by armor_inventory_preset().
get_number_string()
std::string armor_inventory_preset::get_number_string (int number) const inline private
Definition at line 382 of file game_inventory.cpp.
{
             return number ? string_format( "<%s>%d</color>", color, number ) : std::string();
         }
References color, and string_format().
Referenced by armor_inventory_preset().
Member Data Documentation
color
const std::string armor_inventory_preset::color private
Definition at line 389 of file game_inventory.cpp.
Referenced by armor_inventory_preset(), get_decimal_string(), and get_number_string().
you
Character& armor_inventory_preset::you protected
Definition at line 380 of file game_inventory.cpp.
Referenced by armor_inventory_preset(), wear_inventory_preset::get_denial(), take_off_inventory_preset::get_denial(), wear_inventory_preset::is_shown(), and take_off_inventory_preset::is_shown().
The documentation for this class was generated from the following file:
src/game_inventory.cpp