Cataclysm DDA: move_furniture_activity_actor Class Reference
move_furniture_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
move_furniture_activity_actor (const tripoint &dp, bool via_ramp)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &act, Character &who) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
tripoint dp
bool via_ramp
Detailed Description
Definition at line 1286 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
move_furniture_activity_actor()
move_furniture_activity_actor::move_furniture_activity_actor (const tripoint & dp, bool via_ramp) inline
Definition at line 1293 of file activity_actor_definitions.h.
                                                                            :
             dp( dp ), via_ramp( via_ramp ) {}
Referenced by deserialize().
Member Function Documentation
canceled()
void move_furniture_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 4504 of file activity_actor.cpp.
 {
     add_msg( m_warning, _( "You let go of the grabbed object." ) );
     get_avatar().grab( object_type::NONE );
 }
References _, add_msg(), get_avatar(), avatar::grab(), m_warning, and NONE.
clone()
std::unique_ptr<activity_actor> move_furniture_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1304 of file activity_actor_definitions.h.
{
             return std::make_unique<move_furniture_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > move_furniture_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 4518 of file activity_actor.cpp.
 {
     move_furniture_activity_actor actor = move_furniture_activity_actor( tripoint_zero, false );
     JsonObject data = jsin.get_object();
     data.read( "dp", actor.dp );
     data.read( "via_ramp", actor.via_ramp );
     return actor.clone();
 }
References clone(), dp, JsonValue::get_object(), move_furniture_activity_actor(), JsonObject::read(), tripoint_zero, and via_ramp.
do_turn()
void move_furniture_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1300 of file activity_actor_definitions.h.
 {}
finish()
void move_furniture_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 4496 of file activity_actor.cpp.
 {
     if( !g->grabbed_furn_move( dp ) ) {
         g->walk_move( who.pos() + dp, via_ramp, true );
     }
     act.set_to_null();
 }
References act, dp, g, Creature::pos(), and via_ramp.
get_type()
activity_id move_furniture_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1295 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_FURNITURE_MOVE" );
         }
References activity_id.
serialize()
void move_furniture_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 4510 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "dp", dp );
     jsout.member( "via_ramp", via_ramp );
     jsout.end_object();
 }
References dp, JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and via_ramp.
start()
void move_furniture_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 4489 of file activity_actor.cpp.
 {
     int moves = g->grabbed_furn_move_time( dp );
     act.moves_left = moves;
     act.moves_total = moves;
 }
References act, dp, and g.
Member Data Documentation
dp
tripoint move_furniture_activity_actor::dp private
Definition at line 1289 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), serialize(), and start().
via_ramp
bool move_furniture_activity_actor::via_ramp private
Definition at line 1290 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp