Cataclysm DDA: Trait_group Class Reference
Trait_group Class Reference abstract
A group of traits to generate.
#include <trait_group.h>
Public Types
using CreatorList = std::vector< std::unique_ptr< Trait_creation_data > >
Public Types inherited from Trait_creation_data
using RecursionList = std::vector< trait_group::Trait_group_tag >
Public Member Functions
Trait_group (int probability)
~Trait_group () override=default
void add_trait_entry (const trait_id &tid, const std::string &var, int probability)
void add_group_entry (const trait_group::Trait_group_tag &gid, int probability)
virtual void add_entry (std::unique_ptr< Trait_creation_data > ptr)=0
Once the relevant data has been read from JSON, this function is always called (either from mutation_branch::add_entry, add_trait_entry or add_group_entry).
void check_consistency () const override
Check the trait templates for consistency (valid trait types, etc).
bool remove_trait (const trait_id &tid) override
Remove the given trait from this and all linked groups.
bool has_trait (const trait_id &tid) const override
Check if this group or any linked groups contain the given trait.
Public Member Functions inherited from Trait_creation_data
Trait_creation_data (int _probability)
virtual ~Trait_creation_data ()=default
Trait_creation_data (const Trait_creation_data &)=delete
Trait_creation_data & operator= (const Trait_creation_data &)=delete
virtual trait_group::Trait_list create (RecursionList &rec) const =0
Create a list of traits.
trait_group::Trait_list create () const
Protected Attributes
CreatorList creators
int sum_prob
Additional Inherited Members
Public Attributes inherited from Trait_creation_data
int probability
Detailed Description
A group of traits to generate.
Definition at line 147 of file trait_group.h.
Member Typedef Documentation
CreatorList
using Trait_group::CreatorList = std::vector<std::unique_ptr<Trait_creation_data> >
Definition at line 150 of file trait_group.h.
Constructor & Destructor Documentation
Trait_group()
Trait_group::Trait_group (int probability) explicit
Definition at line 129 of file trait_group.cpp.
     : Trait_creation_data( probability ), sum_prob( 0 )
 {
 }
~Trait_group()
Trait_group::~Trait_group () override default
Member Function Documentation
add_entry()
virtual void Trait_group::add_entry (std::unique_ptr< Trait_creation_data > ptr) pure virtual
Once the relevant data has been read from JSON, this function is always called (either from mutation_branch::add_entry, add_trait_entry or add_group_entry).
Its purpose is to add a Single_trait_creator or Trait_group_creator to creators.
Implemented in Trait_group_distribution, and Trait_group_collection.
Referenced by mutation_branch::add_entry(), add_group_entry(), add_trait_entry(), and mutation_branch::load_trait_group().
add_group_entry()
void Trait_group::add_group_entry (const trait_group::Trait_group_tag & gid, int probability)
Definition at line 214 of file trait_group.cpp.
 {
     add_entry( std::make_unique<Trait_group_creator>( gid, probability ) );
 }
References add_entry(), and Trait_creation_data::probability.
Referenced by mutation_branch::load_trait_group().
add_trait_entry()
void Trait_group::add_trait_entry (const trait_id & tid, const std::string & var, int probability)
Definition at line 209 of file trait_group.cpp.
 {
     add_entry( std::make_unique<Single_trait_creator>( tid, var, probability ) );
 }
References add_entry(), and Trait_creation_data::probability.
Referenced by mutation_branch::load_trait_group().
check_consistency()
void Trait_group::check_consistency () const override virtual
Check the trait templates for consistency (valid trait types, etc).
Implements Trait_creation_data.
Definition at line 219 of file trait_group.cpp.
 {
     for( const auto &creator : creators ) {
         creator->check_consistency();
     }
 }
References creators.
has_trait()
bool Trait_group::has_trait (const trait_id & tid) const override virtual
Check if this group or any linked groups contain the given trait.
Implements Trait_creation_data.
Definition at line 239 of file trait_group.cpp.
 {
     for( const auto &creator : creators ) {
         if( creator->has_trait( tid ) ) {
             return true;
         }
     }
     return false;
 }
References creators.
remove_trait()
bool Trait_group::remove_trait (const trait_id & tid) override virtual
Remove the given trait from this and all linked groups.
Used for blacklisting.
Implements Trait_creation_data.
Definition at line 226 of file trait_group.cpp.
 {
     for( auto it = creators.begin(); it != creators.end(); ) {
         if( ( *it )->remove_trait( tid ) ) {
             sum_prob -= ( *it )->probability;
             it = creators.erase( it );
         } else {
             ++it;
         }
     }
     return creators.empty();
 }
References creators, and sum_prob.
Member Data Documentation
creators
CreatorList Trait_group::creators protected
Definition at line 171 of file trait_group.h.
Referenced by Trait_group_collection::add_entry(), Trait_group_distribution::add_entry(), check_consistency(), Trait_group_collection::create(), Trait_group_distribution::create(), has_trait(), and remove_trait().
sum_prob
int Trait_group::sum_prob protected
Definition at line 173 of file trait_group.h.
Referenced by Trait_group_distribution::add_entry(), Trait_group_distribution::create(), and remove_trait().
The documentation for this class was generated from the following files:
src/trait_group.h
src/trait_group.cpp