Cataclysm DDA: coords::coord_point_base< Point > Class Template Reference
coords::coord_point_base< Point > Class Template Reference
A generic coordinate-type-safe point.
#include <coordinates.h>
Public Member Functions
std::string to_string () const
std::string to_string_writable () const
void serialize (JsonOut &jsout) const
Protected Member Functions
constexpr coord_point_base ()=default
template<typename... Ts>
constexpr coord_point_base (Ts &&... ts)
Protected Attributes
Point raw_
Detailed Description
template<typename Point>
class coords::coord_point_base< Point >
A generic coordinate-type-safe point.
Generally you wouldn't use this class directly, but via the typedefs below (point_abs_ms, etc.).
Point should be the underlying representation type (either point or tripoint).
Origin and Scale define the coordinate system for the point.
InBounds define if the point is guaranteed to be inbounds.
For more details see doc/POINTS_COORDINATES.md.
Definition at line 118 of file coordinates.h.
Constructor & Destructor Documentation
coord_point_base() [1/2]
template<typename Point > constexpr coords::coord_point_base< Point >::coord_point_base () constexpr protected default
coord_point_base() [2/2]
template<typename Point > template<typename... Ts> constexpr coords::coord_point_base< Point >::coord_point_base (Ts &&... ts) inline explicit constexpr protected
Definition at line 136 of file coordinates.h.
 : raw_( std::forward<Ts>( ts )... ) {}
Member Function Documentation
serialize()
template<typename Point > void coords::coord_point_base< Point >::serialize (JsonOut & jsout) const inline
Definition at line 128 of file coordinates.h.
{
             raw_.serialize( jsout );
         }
to_string()
template<typename Point > std::string coords::coord_point_base< Point >::to_string () const inline
Definition at line 121 of file coordinates.h.
{
             return raw_.to_string();
         }
Referenced by computer_session::action_amigara_log(), map::add_vehicle_to_map(), debug_menu::character_edit_menu(), vehicle::autodrive_controller::check_drivable(), joins_tracker::consistency_check(), map::decay_fields_and_scent(), debug_menu::mission_debug::describe(), mapbuffer::deserialize(), game::disp_NPCs(), overmap_ui::display(), mission_ui_impl::draw_selected_description(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), basecamp::faction_display(), npc::faction_display(), mutable_overmap_placement_rule::finalize(), bikerack_racking_activity_actor::finish(), overmapbuffer::fix_npcs(), get_get_str_(), weather_generator::get_weather_conditions(), is_sm_tile_outside(), is_sm_tile_over_water(), map::load(), map::loadn(), mapbuffer::lookup_submap(), overmap::overmap(), map::partial_con_at(), map::partial_con_remove(), map::partial_con_set(), mutable_overmap_special_data::place(), map::process_items(), mapbuffer::remove_submap(), npc::set_omt_destination(), debug_menu::teleport_long(), debug_menu::teleport_overmap(), overmap::unserialize_omap(), and mapbuffer::unserialize_submaps().
to_string_writable()
template<typename Point > std::string coords::coord_point_base< Point >::to_string_writable () const inline
Definition at line 124 of file coordinates.h.
{
             return raw_.to_string_writable();
         }
Referenced by creature_tracker::add(), deserialize(), npc::go_to_omt_destination(), creature_tracker::kill_marked_for_death(), game::load_npcs(), overmap::place_mongroups(), map::spawn_monsters_submap_group(), and creature_tracker::update_pos().
Member Data Documentation
raw_
template<typename Point > Point coords::coord_point_base< Point >::raw_ protected
Definition at line 138 of file coordinates.h.
The documentation for this class was generated from the following file:
src/coordinates.h