Cataclysm DDA: mission_ui Class Reference
mission_ui Class Reference
Public Member Functions
void draw_mission_ui ()
Friends
class mission_ui_impl
Detailed Description
Definition at line 50 of file mission_ui.cpp.
Member Function Documentation
draw_mission_ui()
void mission_ui::draw_mission_ui ()
Definition at line 82 of file mission_ui.cpp.
 {
     input_context ctxt;
     mission_ui_impl p_impl;
     ctxt.register_navigate_ui_list();
     ctxt.register_leftright();
     ctxt.register_action( "NEXT_TAB" );
     ctxt.register_action( "PREV_TAB" );
     ctxt.register_action( "SELECT" );
     ctxt.register_action( "MOUSE_MOVE" );
     ctxt.register_action( "CONFIRM", to_translation( "Set selected mission as current objective" ) );
     // We don't actually have a way to remap this right now
     //ctxt.register_action( "DOUBLE_CLICK", to_translation( "Set selected mission as current objective" ) );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "QUIT" );
     // Smooths out our handling, makes tabs load immediately after input instead of waiting for next.
     ctxt.set_timeout( 10 );
     while( true ) {
         ui_manager::redraw_invalidated();
         p_impl.last_action = ctxt.handle_input();
         if( p_impl.last_action == "QUIT" ) {
             break;
         }
     }
 }
References input_context::handle_input(), mission_ui_impl::last_action, ui_manager::redraw_invalidated(), input_context::register_action(), input_context::register_leftright(), input_context::register_navigate_ui_list(), input_context::set_timeout(), and to_translation().
Referenced by game::list_missions().
Friends And Related Function Documentation
mission_ui_impl
friend class mission_ui_impl friend
Definition at line 52 of file mission_ui.cpp.
The documentation for this class was generated from the following file:
src/mission_ui.cpp