Cataclysm DDA: loading_ui Class Reference
loading_ui Class Reference
#include <loading_ui.h>
Public Member Functions
loading_ui (bool display)
~loading_ui ()
void new_context (const std::string &desc)
Sets the description for the menu and clears existing entries.
void add_entry (const std::string &description)
Adds a named entry in the current loading context.
void proceed ()
Place the UI onto UI stack, mark current entry as processed, scroll down, and redraw.
void show ()
Place the UI onto UI stack and redraw it on the screen (if display is enabled).
Private Member Functions
void init ()
Private Attributes
std::unique_ptr< uilist > menu
std::unique_ptr< ui_adaptor > ui
std::unique_ptr< background_pane > ui_background
Detailed Description
Definition at line 12 of file loading_ui.h.
Constructor & Destructor Documentation
loading_ui()
loading_ui::loading_ui (bool display) explicit
Definition at line 18 of file loading_ui.cpp.
 {
     if( display && !test_mode ) {
         menu = std::make_unique<uilist>();
         menu->settext( _( "Loading" ) );
     }
 }
References _, menu, and test_mode.
~loading_ui()
loading_ui::~loading_ui () default
Member Function Documentation
add_entry()
void loading_ui::add_entry (const std::string & description)
Adds a named entry in the current loading context.
Definition at line 28 of file loading_ui.cpp.
 {
     if( menu != nullptr ) {
         menu->addentry( menu->entries.size(), true, 0, description );
     }
 }
References menu.
init()
void loading_ui::init () private
Definition at line 45 of file loading_ui.cpp.
 {
     if( menu != nullptr && ui == nullptr ) {
         ui_background = std::make_unique<background_pane>();
         ui = std::make_unique<ui_adaptor>();
         ui->on_screen_resize( [this]( ui_adaptor & ui ) {
             menu->reposition( ui );
         } );
         menu->reposition( *ui );
         ui->on_redraw( [this]( ui_adaptor & ui ) {
             menu->show( ui );
         } );
     }
 }
References menu, and ui_background.
Referenced by proceed(), and show().
new_context()
void loading_ui::new_context (const std::string & desc)
Sets the description for the menu and clears existing entries.
Definition at line 35 of file loading_ui.cpp.
 {
     if( menu != nullptr ) {
         menu->reset();
         menu->settext( desc );
         ui = nullptr;
         ui_background = nullptr;
     }
 }
References menu, and ui_background.
proceed()
void loading_ui::proceed ()
Place the UI onto UI stack, mark current entry as processed, scroll down, and redraw.
(if display is enabled)
Definition at line 61 of file loading_ui.cpp.
 {
     init();
     if( menu != nullptr && !menu->entries.empty() ) {
         if( menu->selected >= 0 && menu->selected < static_cast<int>( menu->entries.size() ) ) {
             // TODO: Color it red if it errored hard, yellow on warnings
             menu->entries[menu->selected].text_color = c_green;
         }
         if( menu->selected + 1 < static_cast<int>( menu->entries.size() ) ) {
             menu->scrollby( 1 );
         }
     }
     show();
 }
References c_green, init(), menu, and show().
show()
void loading_ui::show ()
Place the UI onto UI stack and redraw it on the screen (if display is enabled).
Definition at line 79 of file loading_ui.cpp.
 {
     init();
     if( menu != nullptr ) {
         ui_manager::redraw();
         refresh_display();
         inp_mngr.pump_events();
     }
 }
References init(), inp_mngr, menu, input_manager::pump_events(), ui_manager::redraw(), and refresh_display().
Referenced by proceed().
Member Data Documentation
menu
std::unique_ptr<uilist> loading_ui::menu private
Definition at line 15 of file loading_ui.h.
Referenced by add_entry(), init(), loading_ui(), new_context(), proceed(), and show().
ui
std::unique_ptr<ui_adaptor> loading_ui::ui private
Definition at line 16 of file loading_ui.h.
ui_background
std::unique_ptr<background_pane> loading_ui::ui_background private
Definition at line 17 of file loading_ui.h.
Referenced by init(), and new_context().
The documentation for this class was generated from the following files:
src/loading_ui.h
src/loading_ui.cpp