Cataclysm DDA: overmap_ui::map_notes_callback Class Reference
overmap_ui::map_notes_callback Class Reference
Public Member Functions
map_notes_callback (const overmapbuffer::t_notes_vector &notes, int z)
bool key (const input_context &ctxt, const input_event &event, int, uilist *menu) override
void select (uilist *menu) override
After a new item is selected, call this once.
Public Member Functions inherited from uilist_callback
virtual void refresh (uilist *)
virtual ~uilist_callback ()=default
Private Member Functions
point_abs_omt point_selected ()
tripoint_abs_omt note_location ()
Private Attributes
overmapbuffer::t_notes_vector _notes
int _z
int _selected = 0
catacurses::window w_preview
catacurses::window w_preview_title
catacurses::window w_preview_map
std::tuple< catacurses::window *, catacurses::window *, catacurses::window * > preview_windows
ui_adaptor ui
Detailed Description
Definition at line 343 of file overmap_ui.cpp.
Constructor & Destructor Documentation
map_notes_callback()
overmap_ui::map_notes_callback::map_notes_callback (const overmapbuffer::t_notes_vector & notes, int z) inline
Definition at line 363 of file overmap_ui.cpp.
             : _notes( notes ), _z( z ) {
             ui.on_screen_resize( [this]( ui_adaptor & ui ) {
                 w_preview = catacurses::newwin( npm_height + 2, max_note_display_length - npm_width - 1,
                                                 point( npm_width + 2, 2 ) );
                 w_preview_title = catacurses::newwin( 2, max_note_display_length + 1, point_zero );
                 w_preview_map = catacurses::newwin( npm_height + 2, npm_width + 2, point( 0, 2 ) );
                 preview_windows = std::make_tuple( &w_preview, &w_preview_title, &w_preview_map );
                 ui.position( point_zero, point( max_note_display_length + 1, npm_height + 4 ) );
             } );
             ui.mark_resize();
             ui.on_redraw( [this]( const ui_adaptor & ) {
                 if( _selected >= 0 && static_cast<size_t>( _selected ) < _notes.size() ) {
                     const tripoint_abs_omt note_pos = note_location();
                     const auto map_around = get_overmap_neighbors( note_pos );
                     update_note_preview( overmap_buffer.note( note_pos ), map_around, preview_windows );
                 } else {
                     update_note_preview( {}, {}, preview_windows );
                 }
             } );
         }
References _notes, _selected, overmap_ui::get_overmap_neighbors(), max_note_display_length, catacurses::newwin(), overmapbuffer::note(), note_location(), npm_height, npm_width, overmap_buffer, point_zero, preview_windows, overmap_ui::update_note_preview(), w_preview, w_preview_map, and w_preview_title.
Member Function Documentation
key()
bool overmap_ui::map_notes_callback::key (const input_context & ctxt, const input_event & event, int , uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 386 of file overmap_ui.cpp.
{
             _selected = menu->selected;
             if( _selected >= 0 && _selected < static_cast<int>( _notes.size() ) ) {
                 const std::string &action = ctxt.input_to_action( event );
                 if( action == "DELETE_NOTE" ) {
                     if( overmap_buffer.has_note( note_location() ) &&
                         query_yn( _( "Really delete note?" ) ) ) {
                         overmap_buffer.delete_note( note_location() );
                     }
                     menu->ret = UILIST_MAP_NOTE_DELETED;
                     return true;
                 }
                 if( action == "EDIT_NOTE" ) {
                     create_note( note_location() );
                     menu->ret = UILIST_MAP_NOTE_EDITED;
                     return true;
                 }
                 if( action == "MARK_DANGER" ) {
                     if( overmap_buffer.note_danger_radius( note_location() ) >= 0 &&
                         query_yn( _( "Remove dangerous mark?" ) ) ) {
                         overmap_buffer.mark_note_dangerous( note_location(), 0, false );
                         menu->ret = UILIST_MAP_NOTE_EDITED;
                         return true;
                     } else {
                         bool has_mark = overmap_buffer.note_danger_radius( note_location() ) >= 0;
                         bool has_note = overmap_buffer.has_note( note_location() );
                         std::string query_text = has_mark ?  _( "Edit dangerous mark?" )  : has_note ?
                                                  _( "Mark area as dangerous (to avoid on auto move paths)?" ) :
                                                  _( "Create note and mark area as dangerous (to avoid on auto move paths)?" );
                         if( query_yn( query_text ) ) {
                             if( !has_note ) {
                                 create_note( note_location() );
                             }
                             const int max_amount = 20;
                             // NOLINTNEXTLINE(cata-text-style): No need for two whitespaces
                             const std::string popupmsg = _( "Danger radius in overmap squares? (0-20)" );
                             int amount = string_input_popup()
                                          .title( popupmsg )
                                          .width( 20 )
                                          .text( "0" )
                                          .only_digits( true )
                                          .query_int();
                             if( amount >= 0 && amount <= max_amount ) {
                                 overmap_buffer.mark_note_dangerous( note_location(), amount, true );
                                 menu->ret = UILIST_MAP_NOTE_EDITED;
                                 return true;
                             }
                         }
                     }
                 }
             }
             return false;
         }
References _, _notes, _selected, action, overmap_ui::create_note(), overmapbuffer::delete_note(), overmapbuffer::has_note(), input_context::input_to_action(), overmapbuffer::mark_note_dangerous(), overmapbuffer::note_danger_radius(), note_location(), string_input_popup::only_digits(), overmap_buffer, string_input_popup::query_int(), query_yn(), uilist::ret, uilist::selected, string_input_popup::text(), string_input_popup::title(), UILIST_MAP_NOTE_DELETED, UILIST_MAP_NOTE_EDITED, and string_input_popup::width().
note_location()
tripoint_abs_omt overmap_ui::map_notes_callback::note_location () inline private
Definition at line 359 of file overmap_ui.cpp.
{
             return tripoint_abs_omt( point_selected(), _z );
         }
References _z, and point_selected().
Referenced by key(), and map_notes_callback().
point_selected()
point_abs_omt overmap_ui::map_notes_callback::point_selected () inline private
Definition at line 356 of file overmap_ui.cpp.
{
             return _notes[_selected].first;
         }
References _notes, and _selected.
Referenced by note_location().
select()
void overmap_ui::map_notes_callback::select (uilist *) inline override virtual
After a new item is selected, call this once.
Reimplemented from uilist_callback.
Definition at line 439 of file overmap_ui.cpp.
{
             _selected = menu->selected;
             ui.invalidate_ui();
         }
References _selected, and uilist::selected.
Member Data Documentation
_notes
overmapbuffer::t_notes_vector overmap_ui::map_notes_callback::_notes private
Definition at line 346 of file overmap_ui.cpp.
Referenced by key(), map_notes_callback(), and point_selected().
_selected
int overmap_ui::map_notes_callback::_selected = 0 private
Definition at line 348 of file overmap_ui.cpp.
Referenced by key(), map_notes_callback(), point_selected(), and select().
_z
int overmap_ui::map_notes_callback::_z private
Definition at line 347 of file overmap_ui.cpp.
Referenced by note_location().
preview_windows
std::tuple<catacurses::window *, catacurses::window *, catacurses::window *> overmap_ui::map_notes_callback::preview_windows private
Definition at line 353 of file overmap_ui.cpp.
Referenced by map_notes_callback().
ui
ui_adaptor overmap_ui::map_notes_callback::ui private
Definition at line 354 of file overmap_ui.cpp.
w_preview
catacurses::window overmap_ui::map_notes_callback::w_preview private
Definition at line 350 of file overmap_ui.cpp.
Referenced by map_notes_callback().
w_preview_map
catacurses::window overmap_ui::map_notes_callback::w_preview_map private
Definition at line 352 of file overmap_ui.cpp.
Referenced by map_notes_callback().
w_preview_title
catacurses::window overmap_ui::map_notes_callback::w_preview_title private
Definition at line 351 of file overmap_ui.cpp.
Referenced by map_notes_callback().
The documentation for this class was generated from the following file:
src/overmap_ui.cpp