Cataclysm DDA: oxytorch_activity_actor Class Reference
oxytorch_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
oxytorch_activity_actor (const tripoint &target, const item_location &tool)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Public Attributes
bool testing = false
Private Member Functions
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
Private Attributes
tripoint target
item_location tool
Detailed Description
Definition at line 1381 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
oxytorch_activity_actor()
oxytorch_activity_actor::oxytorch_activity_actor (const tripoint & target, const item_location & tool) inline explicit
Definition at line 1384 of file activity_actor_definitions.h.
                                                                       : target( target ), tool( tool ) {};
Member Function Documentation
can_resume_with_internal()
bool oxytorch_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override private virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 1408 of file activity_actor_definitions.h.
{
             const oxytorch_activity_actor &actor = static_cast<const oxytorch_activity_actor &>
                                                    ( other );
             return actor.target == target;
         }
References other, and target.
clone()
std::unique_ptr<activity_actor> oxytorch_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1395 of file activity_actor_definitions.h.
{
             return std::make_unique<oxytorch_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > oxytorch_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 5423 of file activity_actor.cpp.
 {
     oxytorch_activity_actor actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "target", actor.target );
     data.read( "tool", actor.tool );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void oxytorch_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 5316 of file activity_actor.cpp.
 {
     if( tool->ammo_sufficient( &who ) ) {
         tool->ammo_consume( tool->ammo_required(), tool.position(), &who );
         sfx::play_activity_sound( "tool", "oxytorch", sfx::get_heard_volume( target ) );
         if( calendar::once_every( 2_turns ) ) {
             sounds::sound( target, 10, sounds::sound_t::destructive_activity, _( "hissssssssss!" ) );
         }
     } else {
         if( who.is_avatar() ) {
             who.add_msg_if_player( m_bad, _( "Your %1$s ran out of charges." ), tool->tname() );
         } else { // who.is_npc()
             add_msg_if_player_sees( who.pos(), _( "%1$s %2$s ran out of charges." ), who.disp_name( false,
                                     true ), tool->tname() );
         }
         who.cancel_activity();
     }
 }
References _, Character::add_msg_if_player(), add_msg_if_player_sees(), item::ammo_consume(), item::ammo_required(), item::ammo_sufficient(), Character::cancel_activity(), sounds::destructive_activity, Character::disp_name(), sfx::get_heard_volume(), Creature::is_avatar(), m_bad, calendar::once_every(), sfx::play_activity_sound(), Creature::pos(), item_location::position(), sounds::sound(), target, item::tname(), and tool.
finish()
void oxytorch_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 5335 of file activity_actor.cpp.
 {
     map &here = get_map();
     const activity_data_common *data;
     if( here.has_furn( target ) ) {
         const furn_id furn_type = here.furn( target );
         if( !furn_type->oxytorch->valid() ) {
             if( !testing ) {
                 debugmsg( "%s oxytorch is invalid", furn_type.id().str() );
             }
             act.set_to_null();
             return;
         }
         const furn_str_id new_furn = furn_type->oxytorch->result();
         if( !new_furn.is_valid() ) {
             if( !testing ) {
                 debugmsg( "oxytorch furniture: %s invalid furniture", new_furn.str() );
             }
             act.set_to_null();
             return;
         }
         data = static_cast<const activity_data_common *>( &*furn_type->oxytorch );
         here.furn_set( target, new_furn );
     } else if( !here.ter( target )->is_null() ) {
         const ter_id ter_type = here.ter( target );
         if( !ter_type->oxytorch->valid() ) {
             if( !testing ) {
                 debugmsg( "%s oxytorch is invalid", ter_type.id().str() );
             }
             act.set_to_null();
             return;
         }
         const ter_str_id new_ter = ter_type->oxytorch->result();
         if( !new_ter.is_valid() ) {
             if( !testing ) {
                 debugmsg( "oxytorch terrain: %s invalid terrain", new_ter.str() );
             }
             act.set_to_null();
             return;
         }
         data = static_cast<const activity_data_common *>( &*ter_type->oxytorch );
         here.ter_set( target, new_ter );
     } else {
         if( !testing ) {
             debugmsg( "oxytorch activity finished on invalid terrain" );
         }
         act.set_to_null();
         return;
     }
     for( const activity_byproduct &byproduct : data->byproducts() ) {
         const int amount = byproduct.roll();
         if( byproduct.item->count_by_charges() ) {
             item byproduct_item( byproduct.item, calendar::turn, amount );
             here.add_item_or_charges( target, byproduct_item );
         } else {
             item byproduct_item( byproduct.item, calendar::turn );
             for( int i = 0; i < amount; ++i ) {
                 here.add_item_or_charges( target, byproduct_item );
             }
         }
     }
     // 50% chance of starting a fire.
     if( one_in( 2 ) && here.flammable_items_at( target ) ) {
         here.add_field( target, fd_fire, 1, 10_minutes );
     }
     if( !data->message().empty() ) {
         who.add_msg_if_player( m_info, data->message().translated() );
     }
     act.set_to_null();
 }
References act, map::add_field(), map::add_item_or_charges(), Character::add_msg_if_player(), activity_data_common::byproducts(), debugmsg, translation::empty(), fd_fire, map::flammable_items_at(), map::furn(), map::furn_set(), get_map(), map::has_furn(), int_id< T >::id(), ter_t::is_null(), string_id< T >::is_valid(), m_info, activity_data_common::message(), one_in(), ter_t::oxytorch, furn_t::oxytorch, string_id< T >::str(), target, map::ter(), map::ter_set(), testing, translation::translated(), and calendar::turn.
get_type()
activity_id oxytorch_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1387 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_OXYTORCH" );
         }
References activity_id.
serialize()
void oxytorch_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 5415 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "target", target );
     jsout.member( "tool", tool );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), target, and tool.
start()
void oxytorch_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 5279 of file activity_actor.cpp.
 {
     const map &here = get_map();
     if( here.has_furn( target ) ) {
         const furn_id furn_type = here.furn( target );
         if( !furn_type->oxytorch->valid() ) {
             if( !testing ) {
                 debugmsg( "%s oxytorch is invalid", furn_type.id().str() );
             }
             act.set_to_null();
             return;
         }
         act.moves_total = to_moves<int>( furn_type->oxytorch->duration() );
     } else if( !here.ter( target )->is_null() ) {
         const ter_id ter_type = here.ter( target );
         if( !ter_type->oxytorch->valid() ) {
             if( !testing ) {
                 debugmsg( "%s oxytorch is invalid", ter_type.id().str() );
             }
             act.set_to_null();
             return;
         }
         act.moves_total = to_moves<int>( ter_type->oxytorch->duration() );
     } else {
         if( !testing ) {
             debugmsg( "oxytorch activity called on invalid terrain" );
         }
         act.set_to_null();
         return;
     }
     add_msg_debug( debugmode::DF_ACTIVITY, "%s moves_total: %d", act.id().str(), act.moves_total );
     act.moves_left = act.moves_total;
 }
References act, add_msg_debug, debugmsg, debugmode::DF_ACTIVITY, map::furn(), get_map(), map::has_furn(), int_id< T >::id(), string_id< T >::id(), ter_t::is_null(), ter_t::oxytorch, furn_t::oxytorch, string_id< T >::str(), target, map::ter(), and testing.
Member Data Documentation
target
tripoint oxytorch_activity_actor::target private
Definition at line 1405 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), do_turn(), finish(), serialize(), and start().
testing
bool oxytorch_activity_actor::testing = false
Definition at line 1403 of file activity_actor_definitions.h.
Referenced by finish(), and start().
tool
item_location oxytorch_activity_actor::tool private
Definition at line 1406 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp