Cataclysm DDA: inventory_multiselector Class Reference
inventory_multiselector Class Reference
#include <inventory_ui.h>
Public Types
using GetStats = std::function< stats(const std::vector< std::pair< item_location, int > >)>
Public Types inherited from inventory_selector
enum selector_invlet_type { SELECTOR_INVLET_DEFAULT , SELECTOR_INVLET_NUMERIC , SELECTOR_INVLET_ALPHA }
enum class uimode : int { categories = 0 , hierarchy , last }
using stat = std::array< std::string, 4 >
using stats = std::array< stat, 3 >
Public Member Functions
inventory_multiselector (Character &p, const inventory_selector_preset &preset=default_preset, const std::string &selection_column_title="", const GetStats &={}, bool allow_select_contained=false)
drop_locations execute (bool allow_empty=false)
void toggle_entry (inventory_entry &entry, size_t count)
Public Member Functions inherited from inventory_selector
inventory_selector (Character &u, const inventory_selector_preset &preset=default_preset)
virtual ~inventory_selector ()
bool add_contained_items (item_location &container)
These functions add items from map / vehicles.
bool add_contained_items (item_location &container, inventory_column &column, const item_category *custom_category=nullptr, item_location const &topmost_parent={}, int indent=0)
void add_contained_gunmods (Character &you, item &gun)
void add_contained_ebooks (item_location &container)
void add_character_items (Character &character)
void add_map_items (const tripoint &target)
void add_vehicle_items (const tripoint &target)
void add_nearby_items (int radius=1)
void add_remote_map_items (tinymap *remote_map, const tripoint &target)
void add_basecamp_items (const basecamp &camp)
void clear_items ()
Remove all items.
void set_title (const std::string &title)
Assigns a title that will be shown on top of the menu.
void set_hint (const std::string &hint)
Assigns a hint.
void set_display_stats (bool display_stats)
Specify whether the header should show stats (weight and volume).
bool empty () const
bool has_available_choices () const
uint64_t item_entry_count () const
drop_location get_only_choice () const
void set_filter (const std::string &str)
Apply filter string to all columns.
std::string get_filter () const
Get last filter string set by set_filter or entered by player.
void set_invlet_type (selector_invlet_type type)
Set the letter group to use for automatic inventory letters.
selector_invlet_type invlet_type ()
void show_invlet (bool show)
Set whether to show inventory letters.
bool showing_invlet () const
void categorize_map_items (bool toggle)
bool highlight (const item_location &loc, bool hidden=false, bool front_only=false)
Highlight a location.
const inventory_entry & get_highlighted () const
item_location get_collation_next () const
void highlight_position (std::pair< size_t, size_t > position)
bool highlight_one_of (const std::vector< item_location > &locations, bool hidden=false)
std::pair< size_t, size_t > get_highlighted_position () const
inventory_column & get_column (size_t index) const
inventory_column & get_active_column () const
void toggle_categorize_contained ()
void set_active_column (size_t index)
void toggle_skip_unselectable ()
std::string action_bound_to_key (char key) const
Protected Member Functions
void rearrange_columns (size_t client_width) override
Tackles screen overflow.
void set_chosen_count (inventory_entry &entry, size_t count)
void deselect_contained_items ()
void toggle_entries (int &count, toggle_mode mode=toggle_mode::SELECTED)
virtual void on_toggle ()
void on_input (const inventory_input &input)
stats get_raw_stats () const override
Get stats to display in top right.
void toggle_categorize_contained ()
Protected Member Functions inherited from inventory_selector
const item_category * naturalize_category (const item_category &category, const tripoint &pos)
inventory_entry * add_entry (inventory_column &target_column, std::vector< item_location > &&locations, const item_category *custom_category=nullptr, size_t chosen_count=0, item_location const &topmost_parent={}, bool chevron=false)
bool add_entry_rec (inventory_column &entry_column, inventory_column &children_column, item_location &loc, item_category const *entry_category=nullptr, item_category const *children_category=nullptr, item_location const &topmost_parent={}, int indent=0)
bool drag_drop_item (item *sourceItem, item *destItem)
inventory_input get_input ()
inventory_input process_input (const std::string &action, int ch)
void on_input (const inventory_input &input)
Given an action from the input_context, try to act according to it.
void on_change (const inventory_entry &entry)
Entry has been changed.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
size_t get_layout_width () const
size_t get_layout_height () const
std::pair< bool, std::string > query_string (const std::string &val, bool end_with_toggle=false)
Query user for a string and return it.
void query_set_filter ()
Query the user for a filter and apply it.
int query_count (char init=0, bool end_with_toggle=false)
Query the user for count and return it.
std::vector< std::string > get_stats () const
std::pair< std::string, nc_color > get_footer (navigation_mode m) const
size_t get_header_height () const
size_t get_header_min_width () const
size_t get_footer_min_width () const
inventory_entry * find_entry_by_invlet (int invlet) const
inventory_entry * find_entry_by_coordinate (const point &coordinate) const
inventory_entry * find_entry_by_location (item_location &loc) const
const std::vector< inventory_column * > & get_all_columns () const
std::vector< inventory_column * > get_visible_columns () const
void highlight ()
Highlight parent and contents of highlighted item.
void action_examine (const item_location &sitem)
Show detailed item information for the selected item.
virtual void reassign_custom_invlets ()
size_t get_columns_width (const std::vector< inventory_column * > &columns) const
double get_columns_occupancy_ratio (size_t client_width) const
bool are_columns_centered (size_t client_width) const
bool is_overflown (size_t client_width) const
bool is_active_column (const inventory_column &column) const
void append_column (inventory_column &column)
void toggle_active_column (scroll_direction dir)
Activates either previous or next column.
void refresh_active_column ()
void toggle_navigation_mode ()
const navigation_mode_data & get_navigation_data (navigation_mode m) const
Protected Attributes
size_t max_chosen_count
std::vector< std::pair< item_location, int > > to_use
std::vector< item_location > usable_locs
bool allow_select_contained
int count = 0
Protected Attributes inherited from inventory_selector
Character & u
const inventory_selector_preset & preset
input_context ctxt
The input context for navigation, already contains some actions for movement.
std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * > > rect_entry_map
std::vector< inventory_column * > columns
point _fixed_origin { -1, -1 }
point _fixed_size { -1, -1 }
bool _categorize_map_items = false
bool force_single_column = false
Private Attributes
std::unique_ptr< inventory_column > selection_col
GetStats get_stats
Additional Inherited Members
Static Protected Member Functions inherited from inventory_selector
static stat get_weight_and_length_stat (units::mass weight_carried, units::mass weight_capacity, const units::length &longest_length)
static stat get_volume_stat (const units::volume &volume_carried, const units::volume &volume_capacity, const units::volume &largest_free_volume)
static stat get_holster_stat (const units::volume &holster_volume, int used_holsters, int total_holsters)
static stats get_weight_and_volume_and_holster_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume &volume_carried, const units::volume &volume_capacity, const units::length &longest_length, const units::volume &largest_free_volume, const units::volume &holster_volume, int used_holsters, int total_holsters)
Detailed Description
Definition at line 961 of file inventory_ui.h.
Member Typedef Documentation
GetStats
using inventory_multiselector::GetStats = std::function<stats(const std::vector<std::pair<item_location, int> >)>
Definition at line 964 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_multiselector()
inventory_multiselector::inventory_multiselector (Character & p, const inventory_selector_preset & preset = default_preset, const std::string & selection_column_title = "", const GetStats & get_stats = {}, bool allow_select_contained = false) explicit
Definition at line 3514 of file inventory_ui.cpp.
                                             :
     inventory_selector( p, preset ),
     allow_select_contained( allow_select_contained ),
     selection_col( new selection_column( "SELECTION_COLUMN", selection_column_title ) ),
     get_stats( get_stats )
 {
     ctxt.register_action( "TOGGLE_ENTRY", to_translation( "Mark/unmark selected item" ) );
     ctxt.register_action( "MARK_WITH_COUNT",
                           to_translation( "Mark a specific amount of selected item" ) );
     ctxt.register_action( "TOGGLE_NON_FAVORITE", to_translation( "Mark/unmark non-favorite items" ) );
     ctxt.register_action( "INCREASE_COUNT" );
     ctxt.register_action( "DECREASE_COUNT" );
     max_chosen_count = std::numeric_limits<decltype( max_chosen_count )>::max();
     set_invlet_type( inventory_selector::SELECTOR_INVLET_ALPHA );
     for( inventory_column * const &elem : get_all_columns() ) {
         elem->set_multiselect( true );
     }
     append_column( *selection_col );
 }
References inventory_selector::append_column(), inventory_selector::ctxt, inventory_selector::get_all_columns(), max(), max_chosen_count, input_context::register_action(), selection_col, inventory_selector::SELECTOR_INVLET_ALPHA, inventory_selector::set_invlet_type(), and to_translation().
Member Function Documentation
deselect_contained_items()
void inventory_multiselector::deselect_contained_items () protected
Definition at line 3843 of file inventory_ui.cpp.
 {
     std::vector<item_location> inventory_items;
     for( std::pair<item_location, int> &drop : to_use ) {
         item_location loc_front = drop.first;
         inventory_items.push_back( loc_front );
     }
     for( item_location loc_container : inventory_items ) {
         if( !loc_container->empty() ) {
             for( inventory_column *col : get_all_columns() ) {
                 for( inventory_entry *selected : col->get_entries( []( const inventory_entry & entry ) {
                 return entry.chosen_count > 0;
             } ) ) {
                     if( !selected->is_item() ) {
                         continue;
                     }
                     for( const item *item_contained : loc_container->all_items_ptr() ) {
                         for( const item_location &selected_loc : selected->locations ) {
                             if( selected_loc.get_item() == item_contained ) {
                                 set_chosen_count( *selected, 0 );
                             }
                         }
                     }
                 }
             }
         }
     }
     for( inventory_column *col : get_all_columns() ) {
         for( inventory_entry *selected : col->get_entries(
         []( const inventory_entry & entry ) {
         return entry.is_item() && entry.chosen_count > 0 && entry.locations.front()->is_frozen_liquid() &&
                    //Frozen liquids can be selected if it have the SHREDDED flag.
                    !entry.locations.front()->has_flag( STATIC( flag_id( "SHREDDED" ) ) ) &&
                    (
                        ( //Frozen liquids on the map are not selectable if they can't be crushed.
                            entry.locations.front().where() == item_location::type::map &&
                            !get_player_character().can_crush_frozen_liquid( entry.locations.front() ).success() ) ||
                        ( //Weapon in hand is can selectable.
                            entry.locations.front().where() == item_location::type::character &&
                            !entry.locations.front().has_parent() &&
                            entry.locations.front() != get_player_character().used_weapon() ) ||
                        ( //Frozen liquids are unselectable if they don't have SHREDDED flag and can't be crushed in a container.
                            entry.locations.front().has_parent() &&
                            entry.locations.front().where() == item_location::type::container &&
                            !get_player_character().can_crush_frozen_liquid( entry.locations.front() ).success() )
                    );
         } ) ) {
             set_chosen_count( *selected, 0 );
         }
     }
 }
References item::all_items_ptr(), inventory_selector::get_all_columns(), item_location::get_item(), set_chosen_count(), and to_use.
Referenced by toggle_entries().
execute()
drop_locations inventory_multiselector::execute (bool allow_empty = false)
Definition at line 3705 of file inventory_ui.cpp.
 {
     shared_ptr_fast<ui_adaptor> ui = create_or_get_ui_adaptor();
     debug_print_timer( tp_start );
     while( true ) {
         ui_manager::redraw();
         const inventory_input input = get_input();
         if( input.action == "CONFIRM" ) {
             if( to_use.empty() && !allow_empty ) {
                 popup_getkey( _( "No items were selected.  Use %s to select them." ),
                               ctxt.get_desc( "TOGGLE_ENTRY" ) );
                 continue;
             }
             break;
         }
         if( input.action == "QUIT" ) {
             return drop_locations();
         }
         on_input( input );
     }
     drop_locations dropped_pos_and_qty;
     for( const std::pair<item_location, int> &drop_pair : to_use ) {
         dropped_pos_and_qty.push_back( drop_pair );
     }
     return dropped_pos_and_qty;
 }
References _, inventory_input::action, inventory_selector::create_or_get_ui_adaptor(), inventory_selector::ctxt, anonymous_namespace{inventory_ui.cpp}::debug_print_timer(), input_context::get_desc(), inventory_selector::get_input(), on_input(), popup_getkey(), ui_manager::redraw(), to_use, and anonymous_namespace{inventory_ui.cpp}::tp_start.
Referenced by game_menus::inv::ebooksave(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), basecamp::get_equipment(), basecamp::give_basecamp_equipment(), basecamp::give_equipment(), haul(), inv_internal_multi(), game_menus::inv::smoke_food(), and iuse::wash_items().
get_raw_stats()
inventory_selector::stats inventory_multiselector::get_raw_stats () const override protected virtual
Get stats to display in top right.
By default, computes volume/weight numbers for u
Reimplemented from inventory_selector.
Reimplemented in pickup_selector, inventory_insert_selector, and inventory_drop_selector.
Definition at line 3810 of file inventory_ui.cpp.
 {
     if( get_stats ) {
         return get_stats( to_use );
     }
     return stats{{ stat{{ "", "", "", "" }}, stat{{ "", "", "", "" }} }};
 }
References get_stats, and to_use.
on_input()
void inventory_multiselector::on_input (const inventory_input & input) protected
Definition at line 3909 of file inventory_ui.cpp.
 {
     if( input.entry != nullptr ) { // Single Item from mouse
         highlight( input.entry->any_item() );
         if( input.action == "SELECT" || input.action == "ANY_INPUT" ) {
             toggle_entries( count );
         }
     }
     if( input.action == "TOGGLE_NON_FAVORITE" ) {
         toggle_entries( count, toggle_mode::NON_FAVORITE_NON_WORN );
     } else if( input.action == "MARK_WITH_COUNT" ) { // Set count and mark selected with specific key
         int query_result = query_count();
         if( query_result >= 0 ) {
             toggle_entries( query_result, toggle_mode::SELECTED );
         }
     } else if( !uistate.numpad_navigation && input.ch >= '0' && input.ch <= '9' ) {
         int query_result = query_count( input.ch, true );
         if( query_result >= 0 ) {
             toggle_entries( query_result, toggle_mode::SELECTED );
         }
     } else if( input.action == "TOGGLE_ENTRY" ) { // Mark selected
         toggle_entries( count, toggle_mode::SELECTED );
     } else if( input.action == "INCREASE_COUNT" || input.action == "DECREASE_COUNT" ) {
         inventory_entry &entry = get_active_column().get_highlighted();
         if( entry.is_selectable() ) {
             size_t const count = entry.chosen_count;
             size_t const max = entry.get_available_count();
             size_t const newcount = input.action == "INCREASE_COUNT"
                                     ? count < max ? count + 1 : max
                                     : count > 1 ? count - 1 : 0;
             toggle_entry( entry, newcount );
         }
     } else if( input.action == "VIEW_CATEGORY_MODE" ) {
         toggle_categorize_contained();
     } else {
         inventory_selector::on_input( input );
     }
 }
References inventory_input::action, inventory_entry::any_item(), inventory_input::ch, inventory_entry::chosen_count, count, inventory_input::entry, inventory_selector::get_active_column(), inventory_entry::get_available_count(), inventory_column::get_highlighted(), inventory_selector::highlight(), inventory_entry::is_selectable(), max(), NON_FAVORITE_NON_WORN, uistatedata::numpad_navigation, inventory_selector::on_input(), inventory_selector::query_count(), SELECTED, toggle_categorize_contained(), toggle_entries(), toggle_entry(), and uistate.
Referenced by inventory_drop_selector::execute(), pickup_selector::execute(), trade_selector::execute(), and execute().
on_toggle()
virtual void inventory_multiselector::on_toggle () inline protected virtual
Reimplemented in trade_selector.
Definition at line 981 of file inventory_ui.h.
 {};
Referenced by toggle_entries(), and toggle_entry().
rearrange_columns()
void inventory_multiselector::rearrange_columns (size_t client_width) override protected virtual
Tackles screen overflow.
Reimplemented from inventory_selector.
Definition at line 3547 of file inventory_ui.cpp.
 {
     selection_col->set_visibility( true );
     inventory_selector::rearrange_columns( client_width );
     selection_col->set_visibility( !is_overflown( client_width ) );
 }
References inventory_selector::is_overflown(), inventory_selector::rearrange_columns(), and selection_col.
set_chosen_count()
void inventory_multiselector::set_chosen_count (inventory_entry & entry, size_t count) protected
Definition at line 3554 of file inventory_ui.cpp.
 {
     const item_location &it = entry.any_item();
     /* Since we're modifying selection of this entry, we need to clear out
        anything that's been set before.
      */
     for( const item_location &loc : entry.locations ) {
         for( auto iter = to_use.begin(); iter != to_use.end(); ) {
             if( iter->first == loc ) {
                 iter = to_use.erase( iter );
             } else {
                 ++iter;
             }
         }
     }
     if( count == 0 ) {
         entry.chosen_count = 0;
     } else {
         size_t size_before = to_use.size();
         entry.chosen_count = std::min( {count, max_chosen_count, entry.get_available_count() } );
         if( it->count_by_charges() ) {
             auto iter = find_if( to_use.begin(),
             to_use.begin() + size_before, [&it]( const drop_location & drop ) {
                 return drop.first == it;
             } );
             if( iter == to_use.begin() + size_before ) {
                 to_use.emplace_back( it, static_cast<int>( entry.chosen_count ) );
             }
         } else {
             for( const item_location &loc : entry.locations ) {
                 if( count == 0 ) {
                     break;
                 }
                 auto iter = find_if( to_use.begin(),
                 to_use.begin() + size_before, [&loc]( const drop_location & drop ) {
                     return drop.first == loc;
                 } );
                 if( iter == to_use.begin() + size_before ) {
                     to_use.emplace_back( loc, 1 );
                 }
                 count--;
             }
         }
     }
     on_change( entry );
 }
References inventory_entry::any_item(), inventory_entry::chosen_count, count, item::count_by_charges(), inventory_entry::get_available_count(), inventory_entry::locations, max_chosen_count, min(), inventory_selector::on_change(), and to_use.
Referenced by pickup_selector::apply_selection(), inventory_haul_selector::apply_selection(), deselect_contained_items(), toggle_entries(), and toggle_entry().
toggle_categorize_contained()
void inventory_multiselector::toggle_categorize_contained () protected
Definition at line 3895 of file inventory_ui.cpp.
 {
     selection_col->clear();
     inventory_selector::toggle_categorize_contained();
     for( inventory_column *col : get_all_columns() ) {
         for( inventory_entry *entry : col->get_entries( return_item, true ) ) {
             if( entry->chosen_count > 0 ) {
                 toggle_entry( *entry, entry->chosen_count );
             }
         }
     }
 }
References inventory_selector::get_all_columns(), anonymous_namespace{inventory_ui.cpp}::return_item(), selection_col, inventory_selector::toggle_categorize_contained(), and toggle_entry().
Referenced by on_input().
toggle_entries()
void inventory_multiselector::toggle_entries (int & count, toggle_mode mode = toggle_mode::SELECTED) protected
Definition at line 3604 of file inventory_ui.cpp.
 {
     std::vector<inventory_entry *> selected;
     switch( mode ) {
         case toggle_mode::SELECTED:
             selected = get_active_column().get_all_selected();
             break;
         case toggle_mode::NON_FAVORITE_NON_WORN: {
             const auto filter_to_nonfavorite_and_nonworn = [this]( const inventory_entry & entry ) {
                 return entry.is_selectable() &&
                        !entry.any_item()->is_favorite &&
                        !u.is_worn( *entry.any_item() );
             };
             selected = get_active_column().get_entries( filter_to_nonfavorite_and_nonworn );
         }
     }
     // Deal with entries that can be highlighted but not selected (e.g. items too large to pick up)
     inventory_entry &highlighted_entry = get_active_column().get_highlighted();
     if( mode == toggle_mode::SELECTED
         && !highlighted_entry.is_selectable() && highlighted_entry.is_item() ) {
         cata_assert( highlighted_entry.denial.has_value() );
         const std::string &denial = *highlighted_entry.denial;
         if( !denial.empty() ) {
             const std::string assembled = highlighted_entry.any_item().get_item()->display_name() + ":\n"
                                           + colorize( denial, c_red );
             if( static_cast<size_t>( utf8_width( denial ) ) > highlighted_entry.cached_denial_space ) {
                 popup( assembled, PF_GET_KEY );
             }
         }
         count = 0;
         return;
     }
     // Deal with anything else that can't be selected
     if( selected.empty() ) {
         count = 0;
         return;
     }
     // No amount entered, select all
     if( count == 0 ) {
         bool select_nonfav = true;
         bool select_fav = true;
         switch( mode ) {
             case toggle_mode::SELECTED: {
                 count = INT_MAX;
                 // Any non favorite item to select?
                 select_nonfav = std::any_of( selected.begin(), selected.end(),
                 []( const inventory_entry * elem ) {
                     return ( !elem->any_item()->is_favorite ) && elem->chosen_count == 0;
                 } );
                 // Otherwise, any favorite item to select?
                 select_fav = !select_nonfav && std::any_of( selected.begin(), selected.end(),
                 []( const inventory_entry * elem ) {
                     return elem->any_item()->is_favorite && elem->chosen_count == 0;
                 } );
                 break;
             }
             case toggle_mode::NON_FAVORITE_NON_WORN: {
                 const bool clear = std::none_of( selected.begin(), selected.end(),
                 []( const inventory_entry * elem ) {
                     return elem->chosen_count > 0;
                 } );
                 if( clear ) {
                     count = max_chosen_count;
                 }
                 break;
             }
         }
         for( inventory_entry *elem : selected ) {
             const bool is_favorite = elem->any_item()->is_favorite;
             if( ( select_nonfav && !is_favorite ) || ( select_fav && is_favorite ) ) {
                 set_chosen_count( *elem, count );
             } else if( !select_nonfav && !select_fav ) {
                 // Every element is selected, unselect all
                 set_chosen_count( *elem, 0 );
             }
         }
         // Select the entered amount
     } else {
         for( inventory_entry *elem : selected ) {
             set_chosen_count( *elem, count );
         }
     }
     if( !allow_select_contained ) {
         deselect_contained_items();
     }
     selection_col->prepare_paging();
     count = 0;
     on_toggle();
 }
References allow_select_contained, inventory_entry::any_item(), c_red, inventory_entry::cached_denial_space, cata_assert, clear, colorize(), count, inventory_entry::denial, deselect_contained_items(), item::display_name(), inventory_selector::get_active_column(), inventory_column::get_all_selected(), inventory_column::get_entries(), inventory_column::get_highlighted(), item_location::get_item(), inventory_entry::is_item(), inventory_entry::is_selectable(), Character::is_worn(), max_chosen_count, inventory_selector::mode, NON_FAVORITE_NON_WORN, on_toggle(), PF_GET_KEY, popup(), SELECTED, selection_col, set_chosen_count(), inventory_selector::u, and utf8_width().
Referenced by on_input().
toggle_entry()
void inventory_multiselector::toggle_entry (inventory_entry & entry, size_t count)
Definition at line 3540 of file inventory_ui.cpp.
 {
     set_chosen_count( entry, count );
     on_toggle();
     selection_col->prepare_paging();
 }
References count, on_toggle(), selection_col, and set_chosen_count().
Referenced by on_input(), and toggle_categorize_contained().
Member Data Documentation
allow_select_contained
bool inventory_multiselector::allow_select_contained protected
Definition at line 980 of file inventory_ui.h.
Referenced by toggle_entries().
count
int inventory_multiselector::count = 0 protected
Definition at line 983 of file inventory_ui.h.
Referenced by inventory_haul_selector::apply_selection(), pickup_selector::execute(), on_input(), set_chosen_count(), toggle_entries(), toggle_entry(), and pickup_selector::wield().
get_stats
GetStats inventory_multiselector::get_stats private
Definition at line 988 of file inventory_ui.h.
Referenced by get_raw_stats().
max_chosen_count
size_t inventory_multiselector::max_chosen_count protected
Definition at line 974 of file inventory_ui.h.
Referenced by inventory_haul_selector::apply_selection(), inventory_multiselector(), set_chosen_count(), and toggle_entries().
selection_col
std::unique_ptr<inventory_column> inventory_multiselector::selection_col private
Definition at line 987 of file inventory_ui.h.
Referenced by inventory_multiselector(), rearrange_columns(), toggle_categorize_contained(), toggle_entries(), and toggle_entry().
to_use
std::vector<std::pair<item_location, int> > inventory_multiselector::to_use protected
Definition at line 978 of file inventory_ui.h.
Referenced by pickup_selector::add_reopen_activity(), deselect_contained_items(), inventory_drop_selector::execute(), pickup_selector::execute(), execute(), get_raw_stats(), inventory_drop_selector::get_raw_stats(), pickup_selector::get_raw_stats(), pickup_selector::remove_from_to_use(), set_chosen_count(), and trade_selector::to_trade().
usable_locs
std::vector<item_location> inventory_multiselector::usable_locs protected
Definition at line 979 of file inventory_ui.h.
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp