Cataclysm DDA: distraction_manager::distraction_manager_gui Class Reference
distraction_manager::distraction_manager_gui Class Reference
#include <distraction_manager.h>
Public Member Functions
void show ()
Detailed Description
Definition at line 8 of file distraction_manager.h.
Member Function Documentation
show()
void distraction_manager::distraction_manager_gui::show ()
Definition at line 47 of file distraction_manager.cpp.
 {
     const int iHeaderHeight = 4;
     int iContentHeight = 0;
     const int number_of_distractions = get_configurable_distractions().size();
     catacurses::window w_border;
     catacurses::window w_header;
     catacurses::window w;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         iContentHeight = FULL_SCREEN_HEIGHT - 2 - iHeaderHeight;
         const point iOffset( TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0,
                              TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0 );
         w_border = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                        iOffset );
         w_header = catacurses::newwin( iHeaderHeight, FULL_SCREEN_WIDTH - 2,
                                        iOffset + point_south_east );
         w = catacurses::newwin( iContentHeight, FULL_SCREEN_WIDTH - 2,
                                 iOffset + point( 1, iHeaderHeight + 1 ) );
         ui.position_from_window( w_border );
     } );
     ui.mark_resize();
     int currentLine = 0;
     int startPosition = 0;
     input_context ctxt{ "DISTRACTION_MANAGER" };
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_leftright();
     ctxt.register_navigate_ui_list();
     ui.on_redraw( [&]( const ui_adaptor & ) {
         // Draw border
         draw_border( w_border, BORDER_COLOR, _( "Distractions manager" ) );
         mvwputch( w_border, point( 0, iHeaderHeight - 1 ), c_light_gray, LINE_XXXO );
         mvwputch( w_border, point( 79, iHeaderHeight - 1 ), c_light_gray, LINE_XOXX );
         mvwputch( w_border, point( 61, FULL_SCREEN_HEIGHT - 1 ), c_light_gray, LINE_XXOX );
         wnoutrefresh( w_border );
         // Draw header
         werase( w_header );
         fold_and_print( w_header, point_zero, getmaxx( w_header ), c_white,
                         _( get_configurable_distractions()[currentLine].description.c_str() ) );
         // Draw horizontal line and corner pieces of the table
         for( int x = 0; x < 78; x++ ) {
             if( x == 60 ) {
                 mvwputch( w_header, point( x, iHeaderHeight - 2 ), c_light_gray, LINE_OXXX );
                 mvwputch( w_header, point( x, iHeaderHeight - 1 ), c_light_gray, LINE_XOXO );
             } else {
                 mvwputch( w_header, point( x, iHeaderHeight - 2 ), c_light_gray, LINE_OXOX );
             }
         }
         wnoutrefresh( w_header );
         // Clear table
         for( int y = 0; y < iContentHeight; y++ ) {
             for( int x = 0; x < 79; x++ ) {
                 if( x == 60 ) {
                     mvwputch( w, point( x, y ), c_light_gray, LINE_XOXO );
                 } else {
                     mvwputch( w, point( x, y ), c_black, ' ' );
                 }
             }
         }
         draw_scrollbar( w_border, currentLine, iContentHeight, number_of_distractions, point( 0,
                         iHeaderHeight + 1 ) );
         calcStartPos( startPosition, currentLine, iContentHeight, number_of_distractions );
         for( int i = startPosition; i < number_of_distractions; ++i ) {
             const nc_color line_color = i == currentLine ? hilite( c_white ) : c_white;
             const nc_color status_color = *( get_configurable_distractions()[i].state ) ? c_light_green :
                                           c_red;
             const std::string status_string = *( get_configurable_distractions()[i].state ) ?
                                               _( "Enabled" ) :
                                               _( "Disabled" );
             // Print distraction types
             mvwprintz( w, point( 1, i - startPosition ), line_color, "%s",
                        _( get_configurable_distractions()[i].name.c_str() ) );
             // Print "Enabled/Disabled" text
             mvwprintz( w, point( 62, i - startPosition ), status_color, "%s", status_string );
         }
         wnoutrefresh( w_header );
         wnoutrefresh( w_border );
         wnoutrefresh( w );
     } );
     while( true ) {
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         if( action == "QUIT" ) {
             break;
         }
         if( navigate_ui_list( action, currentLine, 5, number_of_distractions, true ) ) {
         } else if( action == "CONFIRM" || action == "LEFT" || action == "RIGHT" ) {
             *( get_configurable_distractions()[currentLine].state ) ^= true;
         }
     }
 }
References _, action, BORDER_COLOR, c_black, c_light_gray, c_light_green, c_red, c_white, calcStartPos(), draw_border(), draw_scrollbar(), fold_and_print(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, distraction_manager::get_configurable_distractions(), catacurses::getmaxx(), hilite(), LINE_OXOX, LINE_OXXX, LINE_XOXO, LINE_XOXX, LINE_XXOX, LINE_XXXO, mvwprintz(), mvwputch(), om_direction::name(), navigate_ui_list(), catacurses::newwin(), point_south_east, point_zero, ui_manager::redraw(), input_context::register_action(), status_color(), TERMX, TERMY, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by game::cancel_activity_or_ignore_query(), and game::do_regular_action().
The documentation for this class was generated from the following files:
src/distraction_manager.h
src/distraction_manager.cpp