Cataclysm DDA: speed_description Class Reference
speed_description Class Reference
#include <speed_description.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
const std::vector< speed_description_value > & values () const
Static Public Member Functions
static void load_speed_descriptions (const JsonObject &jo, const std::string &src)
static void reset ()
static const std::vector< speed_description > & get_all ()
Private Attributes
speed_description_id id
std::vector< std::pair< speed_description_id, mod_id > > src
bool was_loaded = false
std::vector< speed_description_value > values_
Friends
class generic_factory< speed_description >
struct mod_tracker
Detailed Description
Definition at line 16 of file speed_description.h.
Member Function Documentation
get_all()
const std::vector< speed_description > & speed_description::get_all () static
Definition at line 44 of file speed_description.cpp.
 {
     return speed_description_factory.get_all();
 }
References anonymous_namespace{speed_description.cpp}::speed_description_factory.
load()
void speed_description::load (const JsonObject & jo, std::string_view src)
Definition at line 35 of file speed_description.cpp.
 {
     optional( jo, was_loaded, "values", values_ );
     std::sort( values_.begin(), values_.end(),
     []( const speed_description_value & valueA, const speed_description_value & valueB ) {
         return valueA.value() > valueB.value();
     } );
 }
References optional(), values_, and was_loaded.
load_speed_descriptions()
void speed_description::load_speed_descriptions (const JsonObject & jo, const std::string & src) static
Definition at line 25 of file speed_description.cpp.
 {
     speed_description_factory.load( jo, src );
 }
References anonymous_namespace{speed_description.cpp}::speed_description_factory, and src.
Referenced by DynamicDataLoader::initialize().
reset()
void speed_description::reset () static
Definition at line 30 of file speed_description.cpp.
 {
     speed_description_factory.reset();
 }
References anonymous_namespace{speed_description.cpp}::speed_description_factory.
Referenced by DynamicDataLoader::unload_data().
values()
const std::vector<speed_description_value>& speed_description::values () const inline
Definition at line 26 of file speed_description.h.
{
             return values_;
         }
Referenced by monster::speed_description().
Friends And Related Function Documentation
generic_factory< speed_description >
friend class generic_factory< speed_description > friend
Definition at line 26 of file speed_description.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 32 of file speed_description.h.
Member Data Documentation
id
speed_description_id speed_description::id private
Definition at line 34 of file speed_description.h.
src
std::vector<std::pair<speed_description_id, mod_id> > speed_description::src private
Definition at line 35 of file speed_description.h.
Referenced by load_speed_descriptions().
values_
std::vector<speed_description_value> speed_description::values_ private
Definition at line 39 of file speed_description.h.
Referenced by load().
was_loaded
bool speed_description::was_loaded = false private
Definition at line 36 of file speed_description.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/speed_description.h
src/speed_description.cpp