Cataclysm DDA: reel_cable_activity_actor Class Reference
reel_cable_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
reel_cable_activity_actor (int moves_total, const item_location &cable)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves_total
item_location cable
Detailed Description
Definition at line 1535 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
reel_cable_activity_actor()
reel_cable_activity_actor::reel_cable_activity_actor (int moves_total, const item_location & cable) inline
Definition at line 1541 of file activity_actor_definitions.h.
                                                                                  :
             moves_total( moves_total ), cable( cable ) {}
Member Function Documentation
can_resume_with_internal()
bool reel_cable_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 1547 of file activity_actor_definitions.h.
{
             const reel_cable_activity_actor &actor = static_cast<const reel_cable_activity_actor &>
                     ( other );
             return actor.cable == cable;
         }
References cable, and other.
clone()
std::unique_ptr<activity_actor> reel_cable_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1558 of file activity_actor_definitions.h.
{
             return std::make_unique<reel_cable_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > reel_cable_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 5560 of file activity_actor.cpp.
 {
     reel_cable_activity_actor actor( 0, {} );
     JsonObject data = jsin.get_object();
     data.read( "moves_total", actor.moves_total );
     data.read( "cable", actor.cable );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void reel_cable_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1555 of file activity_actor_definitions.h.
 {}
finish()
void reel_cable_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 5542 of file activity_actor.cpp.
 {
     cable->reset_link( false, &who, -2 );
     who.add_msg_if_player( m_info, _( "You reel in the %s and wind it up." ), cable->link_name() );
     if( cable->has_flag( flag_NO_DROP ) ) {
         cable.remove_item();
     }
     act.set_to_null();
 }
References _, act, Character::add_msg_if_player(), cable, flag_NO_DROP, item::has_flag(), item::link_name(), m_info, item_location::remove_item(), and item::reset_link().
get_type()
activity_id reel_cable_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1543 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_REEL_CABLE" );
         }
References activity_id.
serialize()
void reel_cable_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 5552 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves_total", moves_total );
     jsout.member( "cable", cable );
     jsout.end_object();
 }
References cable, JsonOut::end_object(), JsonOut::member(), moves_total, and JsonOut::start_object().
start()
void reel_cable_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 5536 of file activity_actor.cpp.
 {
     act.moves_total = moves_total;
     act.moves_left = moves_total;
 }
References act, and moves_total.
Member Data Documentation
cable
item_location reel_cable_activity_actor::cable private
Definition at line 1539 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), finish(), and serialize().
moves_total
int reel_cable_activity_actor::moves_total private
Definition at line 1538 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp