Cataclysm DDA: pickup_selector Class Reference
pickup_selector Class Reference
#include <inventory_ui.h>
Public Member Functions
pickup_selector (Character &p, const inventory_selector_preset &preset=default_preset, const std::string &selection_column_title=_("ITEMS TO PICK UP"), const std::optional< tripoint > &where=std::nullopt)
drop_locations execute ()
void apply_selection (std::vector< drop_location > selection)
Public Member Functions inherited from inventory_multiselector
inventory_multiselector (Character &p, const inventory_selector_preset &preset=default_preset, const std::string &selection_column_title="", const GetStats &={}, bool allow_select_contained=false)
drop_locations execute (bool allow_empty=false)
void toggle_entry (inventory_entry &entry, size_t count)
Public Member Functions inherited from inventory_selector
inventory_selector (Character &u, const inventory_selector_preset &preset=default_preset)
virtual ~inventory_selector ()
bool add_contained_items (item_location &container)
These functions add items from map / vehicles.
bool add_contained_items (item_location &container, inventory_column &column, const item_category *custom_category=nullptr, item_location const &topmost_parent={}, int indent=0)
void add_contained_gunmods (Character &you, item &gun)
void add_contained_ebooks (item_location &container)
void add_character_items (Character &character)
void add_map_items (const tripoint &target)
void add_vehicle_items (const tripoint &target)
void add_nearby_items (int radius=1)
void add_remote_map_items (tinymap *remote_map, const tripoint &target)
void add_basecamp_items (const basecamp &camp)
void clear_items ()
Remove all items.
void set_title (const std::string &title)
Assigns a title that will be shown on top of the menu.
void set_hint (const std::string &hint)
Assigns a hint.
void set_display_stats (bool display_stats)
Specify whether the header should show stats (weight and volume).
bool empty () const
bool has_available_choices () const
uint64_t item_entry_count () const
drop_location get_only_choice () const
void set_filter (const std::string &str)
Apply filter string to all columns.
std::string get_filter () const
Get last filter string set by set_filter or entered by player.
void set_invlet_type (selector_invlet_type type)
Set the letter group to use for automatic inventory letters.
selector_invlet_type invlet_type ()
void show_invlet (bool show)
Set whether to show inventory letters.
bool showing_invlet () const
void categorize_map_items (bool toggle)
bool highlight (const item_location &loc, bool hidden=false, bool front_only=false)
Highlight a location.
const inventory_entry & get_highlighted () const
item_location get_collation_next () const
void highlight_position (std::pair< size_t, size_t > position)
bool highlight_one_of (const std::vector< item_location > &locations, bool hidden=false)
std::pair< size_t, size_t > get_highlighted_position () const
inventory_column & get_column (size_t index) const
inventory_column & get_active_column () const
void toggle_categorize_contained ()
void set_active_column (size_t index)
void toggle_skip_unselectable ()
std::string action_bound_to_key (char key) const
Protected Member Functions
stats get_raw_stats () const override
Get stats to display in top right.
void reassign_custom_invlets () override
Protected Member Functions inherited from inventory_multiselector
void rearrange_columns (size_t client_width) override
Tackles screen overflow.
void set_chosen_count (inventory_entry &entry, size_t count)
void deselect_contained_items ()
void toggle_entries (int &count, toggle_mode mode=toggle_mode::SELECTED)
virtual void on_toggle ()
void on_input (const inventory_input &input)
void toggle_categorize_contained ()
Protected Member Functions inherited from inventory_selector
const item_category * naturalize_category (const item_category &category, const tripoint &pos)
inventory_entry * add_entry (inventory_column &target_column, std::vector< item_location > &&locations, const item_category *custom_category=nullptr, size_t chosen_count=0, item_location const &topmost_parent={}, bool chevron=false)
bool add_entry_rec (inventory_column &entry_column, inventory_column &children_column, item_location &loc, item_category const *entry_category=nullptr, item_category const *children_category=nullptr, item_location const &topmost_parent={}, int indent=0)
bool drag_drop_item (item *sourceItem, item *destItem)
inventory_input get_input ()
inventory_input process_input (const std::string &action, int ch)
void on_input (const inventory_input &input)
Given an action from the input_context, try to act according to it.
void on_change (const inventory_entry &entry)
Entry has been changed.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
size_t get_layout_width () const
size_t get_layout_height () const
std::pair< bool, std::string > query_string (const std::string &val, bool end_with_toggle=false)
Query user for a string and return it.
void query_set_filter ()
Query the user for a filter and apply it.
int query_count (char init=0, bool end_with_toggle=false)
Query the user for count and return it.
std::vector< std::string > get_stats () const
std::pair< std::string, nc_color > get_footer (navigation_mode m) const
size_t get_header_height () const
size_t get_header_min_width () const
size_t get_footer_min_width () const
inventory_entry * find_entry_by_invlet (int invlet) const
inventory_entry * find_entry_by_coordinate (const point &coordinate) const
inventory_entry * find_entry_by_location (item_location &loc) const
const std::vector< inventory_column * > & get_all_columns () const
std::vector< inventory_column * > get_visible_columns () const
void highlight ()
Highlight parent and contents of highlighted item.
void action_examine (const item_location &sitem)
Show detailed item information for the selected item.
size_t get_columns_width (const std::vector< inventory_column * > &columns) const
double get_columns_occupancy_ratio (size_t client_width) const
bool are_columns_centered (size_t client_width) const
bool is_overflown (size_t client_width) const
bool is_active_column (const inventory_column &column) const
void append_column (inventory_column &column)
void toggle_active_column (scroll_direction dir)
Activates either previous or next column.
void refresh_active_column ()
void toggle_navigation_mode ()
const navigation_mode_data & get_navigation_data (navigation_mode m) const
Private Member Functions
bool wield (int &count)
bool wear ()
void remove_from_to_use (item_location &it)
void add_reopen_activity ()
Private Attributes
const std::optional< tripoint > where
Additional Inherited Members
Public Types inherited from inventory_multiselector
using GetStats = std::function< stats(const std::vector< std::pair< item_location, int > >)>
Public Types inherited from inventory_selector
enum selector_invlet_type { SELECTOR_INVLET_DEFAULT , SELECTOR_INVLET_NUMERIC , SELECTOR_INVLET_ALPHA }
enum class uimode : int { categories = 0 , hierarchy , last }
using stat = std::array< std::string, 4 >
using stats = std::array< stat, 3 >
Static Protected Member Functions inherited from inventory_selector
static stat get_weight_and_length_stat (units::mass weight_carried, units::mass weight_capacity, const units::length &longest_length)
static stat get_volume_stat (const units::volume &volume_carried, const units::volume &volume_capacity, const units::volume &largest_free_volume)
static stat get_holster_stat (const units::volume &holster_volume, int used_holsters, int total_holsters)
static stats get_weight_and_volume_and_holster_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume &volume_carried, const units::volume &volume_capacity, const units::length &longest_length, const units::volume &largest_free_volume, const units::volume &holster_volume, int used_holsters, int total_holsters)
Protected Attributes inherited from inventory_multiselector
size_t max_chosen_count
std::vector< std::pair< item_location, int > > to_use
std::vector< item_location > usable_locs
bool allow_select_contained
int count = 0
Protected Attributes inherited from inventory_selector
Character & u
const inventory_selector_preset & preset
input_context ctxt
The input context for navigation, already contains some actions for movement.
std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * > > rect_entry_map
std::vector< inventory_column * > columns
point _fixed_origin { -1, -1 }
point _fixed_size { -1, -1 }
bool _categorize_map_items = false
bool force_single_column = false
Detailed Description
Definition at line 1044 of file inventory_ui.h.
Constructor & Destructor Documentation
pickup_selector()
pickup_selector::pickup_selector (Character & p, const inventory_selector_preset & preset = default_preset, const std::string & selection_column_title = _("ITEMS TO PICK UP"), const std::optional< tripoint > & where = std::nullopt) explicit
Definition at line 4146 of file inventory_ui.cpp.
                                                                                                                 :
     inventory_multiselector( p, preset, selection_column_title ), where( where )
 {
     ctxt.register_action( "WEAR" );
     ctxt.register_action( "WIELD" );
 #if defined(__ANDROID__)
     // allow user to type a drop number without dismissing virtual keyboard after each keypress
     ctxt.allow_text_entry = true;
 #endif
     set_hint( string_format(
                   _( "%s wield %s wear\n%s expand %s all\n%s examine %s/%s/%s quantity (or type number then %s)" ),
                   colorize( ctxt.get_desc( "WIELD" ), c_yellow ),
                   colorize( ctxt.get_desc( "WEAR" ), c_yellow ),
                   colorize( ctxt.get_desc( "SHOW_HIDE_CONTENTS" ), c_yellow ),
                   colorize( ctxt.get_desc( "SHOW_HIDE_CONTENTS_ALL" ), c_yellow ),
                   colorize( ctxt.get_desc( "EXAMINE" ), c_yellow ),
                   colorize( ctxt.get_desc( "MARK_WITH_COUNT" ), c_yellow ),
                   colorize( ctxt.get_desc( "INCREASE_COUNT" ), c_yellow ),
                   colorize( ctxt.get_desc( "DECREASE_COUNT" ), c_yellow ),
                   colorize( ctxt.get_desc( "TOGGLE_ENTRY" ), c_yellow ) ) );
 }
References _, c_yellow, colorize(), inventory_selector::ctxt, input_context::get_desc(), input_context::register_action(), inventory_selector::set_hint(), and string_format().
Member Function Documentation
add_reopen_activity()
void pickup_selector::add_reopen_activity () private
Definition at line 4266 of file inventory_ui.cpp.
 {
     u.assign_activity( pickup_menu_activity_actor( where, to_use ) );
     u.activity.auto_resume = true;
 }
References Character::activity, Character::assign_activity(), player_activity::auto_resume, inventory_multiselector::to_use, inventory_selector::u, and where.
Referenced by wear(), and wield().
apply_selection()
void pickup_selector::apply_selection (std::vector< drop_location > selection)
Definition at line 4170 of file inventory_ui.cpp.
 {
     for( drop_location &loc : selection ) {
         inventory_entry *entry = find_entry_by_location( loc.first );
         if( entry != nullptr ) {
             set_chosen_count( *entry, loc.second + entry->chosen_count );
         }
     }
 }
References inventory_entry::chosen_count, inventory_selector::find_entry_by_location(), and inventory_multiselector::set_chosen_count().
Referenced by game_menus::inv::pickup().
execute()
drop_locations pickup_selector::execute ()
Definition at line 4180 of file inventory_ui.cpp.
 {
     shared_ptr_fast<ui_adaptor> ui = create_or_get_ui_adaptor();
     debug_print_timer( tp_start );
     while( true ) {
         ui_manager::redraw();
         const inventory_input input = get_input();
         if( input.action == "CONFIRM" ) {
             if( to_use.empty() ) {
                 popup_getkey( _( "No items were selected.  Use %s to select them." ),
                               ctxt.get_desc( "TOGGLE_ENTRY" ) );
                 continue;
             }
             break;
         } else if( input.action == "WIELD" ) {
             if( wield( count ) ) {
                 return drop_locations();
             }
         } else if( input.action == "WEAR" ) {
             if( wear() ) {
                 return drop_locations();
             }
         } else if( input.action == "QUIT" ) {
             return drop_locations();
         } else {
             on_input( input );
         }
     }
     drop_locations dropped_pos_and_qty;
     for( const std::pair<item_location, int> &drop_pair : to_use ) {
         dropped_pos_and_qty.push_back( drop_pair );
     }
     return dropped_pos_and_qty;
 }
References _, inventory_input::action, inventory_multiselector::count, inventory_selector::create_or_get_ui_adaptor(), inventory_selector::ctxt, anonymous_namespace{inventory_ui.cpp}::debug_print_timer(), input_context::get_desc(), inventory_selector::get_input(), inventory_multiselector::on_input(), popup_getkey(), ui_manager::redraw(), inventory_multiselector::to_use, anonymous_namespace{inventory_ui.cpp}::tp_start, wear(), and wield().
Referenced by game_menus::inv::pickup().
get_raw_stats()
inventory_selector::stats pickup_selector::get_raw_stats () const override protected virtual
Get stats to display in top right.
By default, computes volume/weight numbers for u
Reimplemented from inventory_multiselector.
Definition at line 4292 of file inventory_ui.cpp.
 {
     units::mass weight;
     units::volume volume;
     for( const drop_location &loc : to_use ) {
         if( loc.first->count_by_charges() ) {
             item copy( *loc.first.get_item() );
             copy.charges = loc.second;
             weight += copy.weight();
             volume += copy.volume();
         } else {
             weight += loc.first->weight() * loc.second;
             volume += loc.first->volume() * loc.second;
         }
     }
     return get_weight_and_volume_and_holster_stats(
                u.weight_carried() + weight,
                u.weight_capacity(),
                u.volume_carried() + volume,
                u.volume_capacity(),
                u.max_single_item_length(),
                u.max_single_item_volume(),
                u.free_holster_volume(),
                u.used_holsters(),
                u.total_holsters() );
 }
References item::charges, Character::free_holster_volume(), inventory_selector::get_weight_and_volume_and_holster_stats(), Character::max_single_item_length(), Character::max_single_item_volume(), inventory_multiselector::to_use, Character::total_holsters(), inventory_selector::u, Character::used_holsters(), item::volume(), Character::volume_capacity(), Character::volume_carried(), item::weight(), Character::weight_capacity(), and Character::weight_carried().
reassign_custom_invlets()
void pickup_selector::reassign_custom_invlets () override protected virtual
Reimplemented from inventory_selector.
Definition at line 4284 of file inventory_ui.cpp.
 {
     if( invlet_type() == SELECTOR_INVLET_DEFAULT ) {
         set_invlet_type( SELECTOR_INVLET_ALPHA );
     }
     inventory_selector::reassign_custom_invlets();
 }
References inventory_selector::invlet_type(), inventory_selector::reassign_custom_invlets(), inventory_selector::SELECTOR_INVLET_ALPHA, inventory_selector::SELECTOR_INVLET_DEFAULT, and inventory_selector::set_invlet_type().
remove_from_to_use()
void pickup_selector::remove_from_to_use (item_location & it) private
Definition at line 4272 of file inventory_ui.cpp.
 {
     for( auto iter = to_use.begin(); iter < to_use.end(); ) {
         if( iter->first == it ) {
             to_use.erase( iter );
             return;
         } else {
             iter++;
         }
     }
 }
References inventory_multiselector::to_use.
Referenced by wear(), and wield().
wear()
bool pickup_selector::wear () private
Definition at line 4244 of file inventory_ui.cpp.
 {
     inventory_entry &selected = get_active_column().get_highlighted();
     if( !selected.is_item() ) {
         return false;
     }
     std::vector<item_location> items{ selected.any_item() };
     std::vector<int> quantities{ 0 };
     if( u.can_wear( *items.front() ).success() ) {
         remove_from_to_use( items.front() );
         add_reopen_activity();
         u.assign_activity( wear_activity_actor( items, quantities ) );
         return true;
     } else {
         popup_getkey( _( "You can't wear the %s." ), items.front()->display_name() );
     }
     return false;
 }
References _, add_reopen_activity(), inventory_entry::any_item(), Character::assign_activity(), Character::can_wear(), inventory_selector::get_active_column(), inventory_column::get_highlighted(), inventory_entry::is_item(), popup_getkey(), remove_from_to_use(), ret_val_common::success(), and inventory_selector::u.
Referenced by execute().
wield()
bool pickup_selector::wield (int & count) private
Definition at line 4219 of file inventory_ui.cpp.
 {
     inventory_entry &selected = get_active_column().get_highlighted();
     if( !selected.is_item() ) {
         return false;
     }
     item_location it = selected.any_item();
     if( count == 0 ) {
         count = INT_MAX;
     }
     int charges = std::min( it->charges, count );
     if( u.can_wield( *it ).success() ) {
         remove_from_to_use( it );
         add_reopen_activity();
         u.assign_activity( wield_activity_actor( it, charges ) );
         return true;
     } else {
         popup_getkey( u.can_wield( *it ).c_str() );
     }
     return false;
 }
References add_reopen_activity(), inventory_entry::any_item(), Character::assign_activity(), ret_val_common::c_str(), Character::can_wield(), item::charges, inventory_multiselector::count, inventory_selector::get_active_column(), inventory_column::get_highlighted(), inventory_entry::is_item(), min(), popup_getkey(), remove_from_to_use(), ret_val_common::success(), and inventory_selector::u.
Referenced by execute().
Member Data Documentation
where
const std::optional<tripoint> pickup_selector::where private
Definition at line 1060 of file inventory_ui.h.
Referenced by add_reopen_activity().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp