Cataclysm DDA: coords::coord_point_mut< Point, Subpoint, InBounds > Class Template Reference
coords::coord_point_mut< Point, Subpoint, InBounds > Class Template Reference
#include <coordinates.h>
Public Member Functions
constexpr coord_point_mut ()=default
constexpr coord_point_mut (const Point &p)
template<typename T >
constexpr coord_point_mut (const Subpoint &p, T z)
template<typename T >
constexpr coord_point_mut (T x, T y)
template<typename T >
constexpr coord_point_mut (T x, T y, T z)
constexpr const Point & raw () const
constexpr auto x () const
constexpr auto y () const
constexpr auto z () const
constexpr Point & raw ()
constexpr auto & x ()
constexpr auto & y ()
constexpr auto & z ()
void deserialize (const JsonValue &jv)
Public Member Functions inherited from coords::coord_point_base< Point >
std::string to_string () const
std::string to_string_writable () const
void serialize (JsonOut &jsout) const
Private Types
using base = coord_point_base< Point >
Additional Inherited Members
Protected Member Functions inherited from coords::coord_point_base< Point >
constexpr coord_point_base ()=default
template<typename... Ts>
constexpr coord_point_base (Ts &&... ts)
Protected Attributes inherited from coords::coord_point_base< Point >
Point raw_
Detailed Description
template<typename Point, typename Subpoint, bool InBounds>
class coords::coord_point_mut< Point, Subpoint, InBounds >
Definition at line 142 of file coordinates.h.
Member Typedef Documentation
base
template<typename Point , typename Subpoint , bool InBounds> using coords::coord_point_mut< Point, Subpoint, InBounds >::base = coord_point_base<Point> private
Definition at line 144 of file coordinates.h.
Constructor & Destructor Documentation
coord_point_mut() [1/5]
template<typename Point , typename Subpoint , bool InBounds> constexpr coords::coord_point_mut< Point, Subpoint, InBounds >::coord_point_mut () constexpr default
coord_point_mut() [2/5]
template<typename Point , typename Subpoint , bool InBounds> constexpr coords::coord_point_mut< Point, Subpoint, InBounds >::coord_point_mut (const Point & p) inline explicit constexpr
Definition at line 148 of file coordinates.h.
 : base( p ) {}
coord_point_mut() [3/5]
template<typename Point , typename Subpoint , bool InBounds> template<typename T > constexpr coords::coord_point_mut< Point, Subpoint, InBounds >::coord_point_mut (const Subpoint & p, T z) inline constexpr
Definition at line 150 of file coordinates.h.
 : base( p.raw(), z ) {}
coord_point_mut() [4/5]
template<typename Point , typename Subpoint , bool InBounds> template<typename T > constexpr coords::coord_point_mut< Point, Subpoint, InBounds >::coord_point_mut (T x, T y) inline constexpr
Definition at line 152 of file coordinates.h.
 : base( x, y ) {}
coord_point_mut() [5/5]
template<typename Point , typename Subpoint , bool InBounds> template<typename T > constexpr coords::coord_point_mut< Point, Subpoint, InBounds >::coord_point_mut (T x, T y, T z) inline constexpr
Definition at line 154 of file coordinates.h.
 : base( x, y, z ) {}
Member Function Documentation
deserialize()
template<typename Point , typename Subpoint , bool InBounds> void coords::coord_point_mut< Point, Subpoint, InBounds >::deserialize (const JsonValue & jv) inline
Definition at line 185 of file coordinates.h.
{
             raw().deserialize( jv );
         }
Referenced by mongroup::deserialize_legacy(), and overmap::unserialize().
raw() [1/2]
template<typename Point , typename Subpoint , bool InBounds> constexpr Point& coords::coord_point_mut< Point, Subpoint, InBounds >::raw () inline constexpr
Definition at line 171 of file coordinates.h.
{
             return this->raw_;
         }
raw() [2/2]
template<typename Point , typename Subpoint , bool InBounds> constexpr const Point& coords::coord_point_mut< Point, Subpoint, InBounds >::raw () const inline constexpr
Definition at line 157 of file coordinates.h.
{
             return this->raw_;
         }
Referenced by anonymous_namespace{clzones.cpp}::_rotate_zone(), anonymous_namespace{item.cpp}::_stacks_location_hint(), basecamp::abandon_camp(), map::accessible_items(), activity_on_turn_move_loot(), inventory_selector::add_basecamp_items(), add_fallback_zone(), map::add_field(), tinymap::add_field(), map::add_spawn(), jmapgen_sign::apply(), jmapgen_graffiti::apply(), jmapgen_computer::apply(), jmapgen_setmap::apply(), jmapgen_objects::apply(), MapExtras::apply_function(), vehicle::autopilot_patrol(), cata_event_dispatch::avatar_moves(), Character::base_comfort_value(), vehicle::build_interact_menu(), butcher_corpse_activity(), can_do_activity_there(), can_interact_at(), map::can_put_items(), map::can_put_items_ter_furn(), vehicle::autodrive_controller::check_drivable(), construct::check_support_below(), map::clear_path(), map::close_door(), closest_points_first(), Character::complete_disassemble(), vehicle::autodrive_controller::compute_coordinates(), vehicle::autodrive_controller::compute_goal_zone(), vehicle::autodrive_controller::compute_path(), npc::could_move_onto(), map::create_anomaly(), map::cut_down_tree(), tinymap::cut_down_tree(), map::dangerous_field_at(), tinymap::delete_field(), map::delete_signage(), map::destroy_furn(), direction_from(), map::displace_vehicle(), item::display_name(), vehicle::do_towing_move(), glide_activity_actor::do_turn(), construct::do_turn_shovel(), construct::done_appliance(), construct::done_dig_grave(), construct::done_grave(), construct::done_mine_upstair(), construct::done_vehicle(), construct::done_wiring(), overmap_ui::draw_ascii(), game::draw_line(), map::drawsq(), vehicle::drive_to_local_target(), drop_on_map(), npc::evaluate_sleep_spot(), map::field_at(), npc::find_item(), start_location::find_player_initial_location(), vehicle::find_vehicle(), map::flammable_items_at(), creature_tracker::flood_fill_zone(), game::forced_door_closing(), map::free_volume(), map::furn(), tinymap::furn(), map::furn_set(), map::furnname(), generic_multi_activity_do(), vehicle::get_angle_from_targ(), vehicle::get_debug_overlay_data(), map::get_field(), map::get_field_age(), Character::get_next_auto_move_direction(), map::getabs(), map::getglobal(), map::getlocal(), om_noise::om_noise_layer::global_omt_pos(), npc::good_escape_direction(), npc::handle_sound(), map::has_flag(), tinymap::has_flag_ter(), map::has_flag_ter_or_furn(), map::has_furn(), zone_data::has_inside(), map::has_items(), jmapgen_setmap::has_vehicle_collision(), jmapgen_objects::has_vehicle_collision(), map::i_at(), map::i_clear(), map::i_rem(), map::impassable(), map::inbounds(), tinymap::inbounds(), game::is_empty(), map::is_flammable(), is_sm_tile_outside(), is_sm_tile_over_water(), line_to(), item::link_to(), game::look_around(), manhattan_dist(), map::maptile_at(), midpoint(), iuse::mop(), npc::move(), map::move_cost(), npc::move_to(), mremove_fields(), MapExtras::mx_portal_in(), map::name(), map::obstacle_name(), octile_dist(), coords::operator!=(), coords::project_to_impl< 0, ScaleDown, ResultScale, false >::operator()(), coords::project_to_impl< ScaleUp, 0, ResultScale, InBounds >::operator()(), coords::project_to_impl< 0, ScaleDown, ResultScale, true >::operator()(), std::hash< coords::coord_point< Point, Origin, Scale, InBounds > >::operator()(), coords::operator*(), coords::operator+(), coords::operator+=(), coords::operator-(), coords::operator-=(), coords::operator<(), coords::operator<<(), coords::operator==(), map::partial_con_remove(), map::passable(), map::place_gas_pump(), map::place_items(), map::place_toilet(), map::place_vending(), tinymap::points_in_rectangle(), map_memory::prepare_region(), map::process_items(), coords::project_combine(), coords::project_remain(), rebase_bub(), rebase_omt(), rebase_rel(), map::remove_field(), map::remove_trap(), rl_dist(), map::rotate(), map::route(), game::safe_route_to(), Character::sees(), Creature::sees(), overmap::signal_hordes(), Character::sleep_spot(), sounds::sound(), map::spawn_items(), square_dist(), game::start_game(), map::ter(), tinymap::ter(), map::ter_set(), auto_navigation_data::to_view(), map::tr_at(), tinymap::tr_at(), map::trap_set(), tinymap::trap_set(), trig_dist(), map::unsafe_get_submap_at(), game::update_overmap_seen(), npc::update_path(), reveal_map_actor::use(), map::veh_at(), tinymap::veh_at(), and game::zones_manager().
x() [1/2]
template<typename Point , typename Subpoint , bool InBounds> constexpr auto& coords::coord_point_mut< Point, Subpoint, InBounds >::x () inline constexpr
Definition at line 175 of file coordinates.h.
{
             return raw().x;
         }
x() [2/2]
template<typename Point , typename Subpoint , bool InBounds> constexpr auto coords::coord_point_mut< Point, Subpoint, InBounds >::x () const inline constexpr
Definition at line 161 of file coordinates.h.
{
             return raw().x;
         }
Referenced by computer_session::action_amigara_log(), computer_session::action_miss_launch(), map::add_item(), map::add_spawn(), jmapgen_setmap::apply(), overmap::calculate_forestosity(), overmap::calculate_ocean_gradient(), overmap::calculate_urbanity(), display::colorized_overmap_text(), coords::coord_max(), coords::coord_min(), map_memory::coord_pair::coord_pair(), debug_menu::debug_menu_game_state(), map::displace_vehicle(), overmap_ui::display(), overmap_ui::draw_ascii(), overmap_ui::draw_city_labels(), game::draw_minimap(), overmap_ui::draw_notes(), overmapbuffer::find_camp(), find_dirname(), find_quad_path(), ff::flood_fill_visit_10_connected(), Character::get_next_auto_move_direction(), overmapbuffer::get_overmaps_near(), map_memory::get_submap(), mm_submap::get_tile(), npc::go_to_omt_destination(), npc::good_escape_direction(), overmap::good_river(), npc::handle_sound(), jmapgen_setmap::has_vehicle_collision(), jmapgen_alternatively< PieceType >::has_vehicle_collision(), jmapgen_sign::has_vehicle_collision(), jmapgen_vending_machine::has_vehicle_collision(), jmapgen_toilet::has_vehicle_collision(), jmapgen_gaspump::has_vehicle_collision(), jmapgen_vehicle::has_vehicle_collision(), jmapgen_trap::has_vehicle_collision(), jmapgen_furniture::has_vehicle_collision(), jmapgen_terrain::has_vehicle_collision(), jmapgen_computer::has_vehicle_collision(), jmapgen_sealed_item::has_vehicle_collision(), map::inbounds(), is_sm_tile_outside(), is_sm_tile_over_water(), map::loadn(), game::look_around(), mapbuffer::lookup_submap(), map::make_active(), mapgen_function_json::mapgen_function_json(), display::mission_arrow_offset(), npc::move(), overmap::move_hordes(), overmap::move_nemesis(), MapExtras::mx_portal_in(), om_noise::om_noise_layer_forest::noise_at(), om_noise::om_noise_layer_floodplain::noise_at(), om_noise::om_noise_layer_lake::noise_at(), om_noise::om_noise_layer_ocean::noise_at(), talk_function::om_simple_dir(), Character::overmap_los(), display::overmap_tile_symbol_color(), mission_util::parse_mission_om_target(), overmap::place_forest_trails(), overmap::place_river(), map::place_spawns(), overmap::place_special_attempt(), overmapbuffer::player_filename(), overmap::populate(), overmap::populate_connections_out_from_neighbors(), map_memory::prepare_region(), iuse::radio_on(), iuse::radio_tick(), advanced_inventory::recalc_pane(), zone_data::refresh_display(), map::saven(), basecamp::scan_pseudo_items(), overmap_ui::search(), game::serialize(), mm_submap::set_tile(), basecamp::start_fortifications(), basecamp::start_salt_water_pipe(), overmapbuffer::terrain_filename(), zone_data::toggle_display(), overmap::unserialize(), game::unserialize(), mapbuffer::unserialize_submaps(), overmap::unserialize_view(), update_mapgen_function_json::update_map(), and game::update_overmap_seen().
y() [1/2]
template<typename Point , typename Subpoint , bool InBounds> constexpr auto& coords::coord_point_mut< Point, Subpoint, InBounds >::y () inline constexpr
Definition at line 178 of file coordinates.h.
{
             return raw().y;
         }
y() [2/2]
template<typename Point , typename Subpoint , bool InBounds> constexpr auto coords::coord_point_mut< Point, Subpoint, InBounds >::y () const inline constexpr
Definition at line 164 of file coordinates.h.
{
             return raw().y;
         }
Referenced by computer_session::action_amigara_log(), computer_session::action_miss_launch(), map::add_item(), map::add_spawn(), jmapgen_setmap::apply(), overmap::calculate_forestosity(), overmap::calculate_ocean_gradient(), overmap::calculate_urbanity(), display::colorized_overmap_text(), coords::coord_max(), coords::coord_min(), map_memory::coord_pair::coord_pair(), debug_menu::debug_menu_game_state(), map::displace_vehicle(), overmap_ui::display(), overmap_ui::draw_ascii(), overmap_ui::draw_city_labels(), game::draw_minimap(), overmap_ui::draw_notes(), overmapbuffer::find_camp(), find_dirname(), find_quad_path(), ff::flood_fill_visit_10_connected(), Character::get_next_auto_move_direction(), overmapbuffer::get_overmaps_near(), map_memory::get_submap(), mm_submap::get_tile(), npc::go_to_omt_destination(), npc::good_escape_direction(), overmap::good_river(), npc::handle_sound(), jmapgen_setmap::has_vehicle_collision(), jmapgen_alternatively< PieceType >::has_vehicle_collision(), jmapgen_sign::has_vehicle_collision(), jmapgen_vending_machine::has_vehicle_collision(), jmapgen_toilet::has_vehicle_collision(), jmapgen_gaspump::has_vehicle_collision(), jmapgen_vehicle::has_vehicle_collision(), jmapgen_trap::has_vehicle_collision(), jmapgen_furniture::has_vehicle_collision(), jmapgen_terrain::has_vehicle_collision(), jmapgen_computer::has_vehicle_collision(), jmapgen_sealed_item::has_vehicle_collision(), map::inbounds(), is_sm_tile_outside(), is_sm_tile_over_water(), map::loadn(), game::look_around(), mapbuffer::lookup_submap(), map::make_active(), mapgen_function_json::mapgen_function_json(), display::mission_arrow_offset(), npc::move(), overmap::move_hordes(), overmap::move_nemesis(), MapExtras::mx_portal_in(), om_noise::om_noise_layer_forest::noise_at(), om_noise::om_noise_layer_floodplain::noise_at(), om_noise::om_noise_layer_lake::noise_at(), om_noise::om_noise_layer_ocean::noise_at(), talk_function::om_simple_dir(), Character::overmap_los(), display::overmap_tile_symbol_color(), mission_util::parse_mission_om_target(), overmap::place_forest_trails(), overmap::place_river(), map::place_spawns(), overmap::place_special_attempt(), overmapbuffer::player_filename(), overmap::populate(), overmap::populate_connections_out_from_neighbors(), map_memory::prepare_region(), iuse::radio_on(), iuse::radio_tick(), advanced_inventory::recalc_pane(), zone_data::refresh_display(), map::saven(), basecamp::scan_pseudo_items(), overmap_ui::search(), game::serialize(), mm_submap::set_tile(), basecamp::start_fortifications(), basecamp::start_salt_water_pipe(), overmapbuffer::terrain_filename(), zone_data::toggle_display(), overmap::unserialize(), game::unserialize(), mapbuffer::unserialize_submaps(), overmap::unserialize_view(), update_mapgen_function_json::update_map(), and game::update_overmap_seen().
z() [1/2]
template<typename Point , typename Subpoint , bool InBounds> constexpr auto& coords::coord_point_mut< Point, Subpoint, InBounds >::z () inline constexpr
Definition at line 181 of file coordinates.h.
{
             return raw().z;
         }
z() [2/2]
template<typename Point , typename Subpoint , bool InBounds> constexpr auto coords::coord_point_mut< Point, Subpoint, InBounds >::z () const inline constexpr
Definition at line 167 of file coordinates.h.
{
             return raw().z;
         }
Referenced by anonymous_namespace{clzones.cpp}::_rotate_zone(), computer_session::action_amigara_log(), activity_on_turn_move_loot(), timed_event::actualize(), add_corpse(), overmap::add_extra(), overmap::add_extra_note(), map::add_item(), map::add_item_or_charges(), tinymap::add_item_or_charges(), add_monsters(), overmap::add_note(), map::add_spawn(), map::adjust_radiation(), jmapgen_remove_npcs::apply(), jmapgen_setmap::apply(), VehicleFunction_json::apply(), apply_construction_marker(), map::bash_rating(), map::bash_resistance(), map::bash_strength(), map::build_floor_caches(), overmap::build_lab(), VehicleSpawnFunction::builtin_parkinglot(), start_location::burn(), zone_manager::cache_vzones(), map::can_put_items(), map::can_put_items_ter_furn(), vehicle::autodrive_controller::check_collision_zone(), ui::omap::choose_point(), display::colorized_overmap_text(), coords::coord_max(), coords::coord_min(), map_memory::coord_pair::coord_pair(), map::create_anomaly(), mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), mission_start::create_lab_console(), zone_manager::create_vehicle_loot_zone(), debug_menu::debug(), map::decay_fields_and_scent(), map::detach_vehicle(), map::displace_vehicle(), overmap_ui::display(), basecamp::distribute_food(), move_items_activity_actor::do_turn(), unload_loot_activity_actor::do_turn(), overmap_ui::draw_ascii(), map::draw_fill_background(), map::draw_lab(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), map::draw_rough_circle_furn(), vehicle::autodrive_controller::enqueue_if_ramp(), overmap::explored(), overmap::extra(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), computer_session::failure_amigara(), farm_action(), map::features(), find_dirname(), pf::find_overmap_path(), find_potential_computer_point(), find_quad_path(), overmapbuffer::fix_npcs(), ff::flood_fill_visit_10_connected(), basecamp::form_crafting_inventory(), basecamp::form_storage_zones(), mapf::formatted_set_simple(), map::furn(), map::furn_clear(), map::furn_set(), tinymap::furn_set(), map::furnname(), map::generate(), zone_manager::get_bottom_zone(), overmapbuffer::get_description_at(), overmapbuffer::get_existing_om_global(), get_mission_om_origin(), map::get_moving_vehicle_targets(), zone_manager::get_near(), zone_manager::get_near_zones(), Character::get_next_auto_move_direction(), map::get_nonant(), overmapbuffer::get_om_global(), map::get_rc_items(), map_memory::get_submap(), map::get_submap_at(), map::get_vehicles(), zone_manager::get_zones(), zone_manager::get_zones_at(), map::getabs(), map::getlocal(), overmapbuffer::groups_at(), overmapbuffer::has_camp(), overmap::has_extra(), map::has_flag(), map::has_flag_furn(), map::has_flag_ter(), map::has_flag_ter_or_furn(), map::has_furn(), zone_manager::has_near(), overmap::has_note(), jmapgen_setmap::has_vehicle_collision(), jmapgen_alternatively< PieceType >::has_vehicle_collision(), jmapgen_sign::has_vehicle_collision(), jmapgen_vending_machine::has_vehicle_collision(), jmapgen_toilet::has_vehicle_collision(), jmapgen_gaspump::has_vehicle_collision(), jmapgen_vehicle::has_vehicle_collision(), jmapgen_trap::has_vehicle_collision(), jmapgen_furniture::has_vehicle_collision(), jmapgen_terrain::has_vehicle_collision(), jmapgen_computer::has_vehicle_collision(), jmapgen_sealed_item::has_vehicle_collision(), monster::hear_sound(), talk_function::hospital_raid_return(), map::i_at(), map::i_clear(), map::i_rem(), scent_map::inbounds(), map::inbounds(), map::is_bashable(), map::is_bashable_furn(), map::is_bashable_ter(), map::is_bashable_ter_furn(), is_creature_outside(), map::is_divable(), overmap::is_explored(), overmap::is_marked_dangerous(), map::is_outside(), map::is_water_shallow_current(), game::load(), map::load(), map::loadn(), game::look_around(), mapbuffer::lookup_submap(), madd_field(), debug_menu::map_extra(), mapgen_function_json::mapgen_function_json(), editmap::mapgen_veh_destroy(), overmap::mark_note_dangerous(), vehicle::merge_rackable_vehicle(), map::mirror(), monster::move(), map::move_cost(), map::move_cost_ter_furn(), overmap::move_hordes(), mtrap_set(), MapExtras::mx_fungal_zone(), map::name(), overmap::note(), overmap::note_danger_radius(), om_cutdown_trees(), om_harvest_itm(), om_harvest_ter(), Character::on_move(), display::overmap_position_text(), mission_util::parse_mission_om_target(), map::partial_con_at(), map::partial_con_remove(), map::partial_con_set(), map::passable(), game::peek(), timed_event::per_turn(), Character::perform_install(), Character::perform_uninstall(), mission_start::place_deposit_box(), start_location::place_player(), game::place_player(), game::place_player_overmap(), MapExtras::place_trap_if_clear(), vehicle::place_zones(), monster::plan(), map::points_on_zlevel(), overmap::populate_connections_out_from_neighbors(), Creature::posz(), start_location::prepare_map(), map_memory::prepare_region(), map::process_items(), coords::project_remain(), veh_menu::query(), advanced_inventory::recalc_pane(), zone_data::refresh_display(), reg_coord_pair::reg_coord_pair(), vehicle::remove_carried_vehicle(), map::reset_vehicles_sm_pos(), mission_util::reveal_om_ter(), zone_manager::revert_vzones(), map::rotate(), zone_manager::rotate_zones(), map::save(), map::saven(), basecamp::scan_pseudo_items(), talk_function::scavenging_raid_return(), map::scent_blockers(), overmap_ui::search(), overmap::seen(), game::serialize(), npc::set_omt_destination(), map::set_radiation(), overmap::set_seen(), map::set_temperature_mod(), map::spawn_items(), map::spawn_monsters(), debug_menu::spawn_nested_mapgen(), square(), square_furn(), game::start_game(), basecamp::start_salt_water_pipe(), basecamp::survey_field_return(), basecamp::survey_return(), mission_util::target_closest_lab_entrance(), map::ter(), map::ter_set(), overmap::ter_set(), overmap::ter_unsafe(), map::tername(), game::unserialize(), mapbuffer::unserialize_submaps(), update_mapgen_function_json::update_map(), game::update_map(), game::update_overmap_seen(), weather_manager::update_weather(), activity_handlers::vehicle_finish(), map::vehmove(), game::vertical_move(), wait(), and weather_sound().
The documentation for this class was generated from the following file:
src/coordinates.h