Cataclysm DDA: vpart_reference Class Reference
vpart_reference Class Reference
This is a wrapper over a vehicle pointer and a reference to a part of it.
#include <vpart_position.h>
Public Member Functions
vpart_reference (::vehicle &v, const size_t part)
vpart_reference (const vpart_reference &)=default
vpart_reference & operator= (const vpart_reference &)=default
vehicle_part & part () const
Yields the vehicle_part object referenced by this.
const vpart_info & info () const
See vehicle_part::info.
vehicle_stack items () const
Character * get_passenger () const
Returns the passenger in this part, or nullptr if no passenger.
::vehicle & vehicle () const
bool has_feature (const std::string &f) const
Returns whether the part type has the given feature.
bool has_feature (vpart_bitflags f) const
Public Member Functions inherited from vpart_position
vpart_position (::vehicle &v, const size_t part)
::vehicle & vehicle () const
size_t part_index () const
bool is_inside () const
void set_label (const std::string &text) const
Sets the label at this part of the vehicle.
std::optional< std::string > get_label () const
std::optional< vpart_reference > cargo () const
std::optional< vpart_reference > part_with_feature (const std::string &f, bool unbroken) const
std::optional< vpart_reference > part_with_feature (vpart_bitflags f, bool unbroken) const
std::optional< vpart_reference > avail_part_with_feature (const std::string &f) const
std::optional< vpart_reference > avail_part_with_feature (vpart_bitflags f) const
std::optional< vpart_reference > obstacle_at_part () const
Returns the obstacle that exists at this point of the vehicle (if any).
std::optional< vpart_reference > part_displayed () const
Returns the part displayed at this point of the vehicle.
std::optional< vpart_reference > part_with_tool (const itype_id &tool_type) const
std::map< item, int > get_tools () const
void form_inventory (inventory &inv) const
tripoint_bub_ms pos_bub () const
Returns the position of this part in the coordinates system that game::m uses.
tripoint pos () const
point mount () const
Returns the mount point: the point in the vehicles own coordinate system.
bool operator< (const vpart_position &other) const
Detailed Description
This is a wrapper over a vehicle pointer and a reference to a part of it.
The class does not support an "invalid" state, it is created from a valid reference and the user must ensure it's still valid when used. Most functions just forward to the equally named functions in the vehicle class, so see there for documentation.
Definition at line 153 of file vpart_position.h.
Constructor & Destructor Documentation
vpart_reference() [1/2]
vpart_reference::vpart_reference (::vehicle & v, const size_t part) inline
Definition at line 156 of file vpart_position.h.
 : vpart_position( v, part ) { }
vpart_reference() [2/2]
vpart_reference::vpart_reference (const vpart_reference &) default
Member Function Documentation
get_passenger()
Character * vpart_reference::get_passenger () const
Returns the passenger in this part, or nullptr if no passenger.
Definition at line 7796 of file vehicle.cpp.
 {
     return vehicle().get_passenger( part_index() );
 }
References vehicle::get_passenger(), vpart_position::part_index(), and vehicle().
has_feature() [1/2]
bool vpart_reference::has_feature (const std::string & f) const
Returns whether the part type has the given feature.
Note that this is different from part flags (which apply to part instances). For example a feature is "CARGO" (the part can store items).
Definition at line 7822 of file vehicle.cpp.
 {
     return info().has_flag( f );
 }
References vpart_info::has_flag(), and info().
Referenced by vehicle_caching_internal(), and vehicle_caching_internal_above().
has_feature() [2/2]
bool vpart_reference::has_feature (vpart_bitflags f) const
Definition at line 7827 of file vehicle.cpp.
 {
     return info().has_flag( f );
 }
References vpart_info::has_flag(), and info().
info()
const vpart_info & vpart_reference::info () const
See vehicle_part::info.
Definition at line 7786 of file vehicle.cpp.
 {
     return part().info();
 }
References vehicle_part::info(), and part().
Referenced by has_feature().
items()
vehicle_stack vpart_reference::items () const
Definition at line 7791 of file vehicle.cpp.
 {
     return vehicle().get_items( part() );
 }
References vehicle::get_items(), part(), and vehicle().
Referenced by game::start_game(), and item_location::impl::item_on_vehicle::volume_capacity().
operator=()
vpart_reference& vpart_reference::operator= (const vpart_reference &) default
part()
vehicle_part & vpart_reference::part () const
Yields the vehicle_part object referenced by this.
See also
vehicle::parts
Definition at line 7780 of file vehicle.cpp.
 {
     cata_assert( part_index() < static_cast<size_t>( vehicle().part_count() ) );
     return vehicle().part( part_index() );
 }
References cata_assert, vehicle::part(), vpart_position::part_index(), and vehicle().
Referenced by add_electronic_toggle(), veh_interact::get_most_damaged_part(), info(), items(), vpart_position::part_with_tool(), Character::pour_into(), put_into_vehicle(), vehicle::search_connected_batteries(), map::unboard_vehicle(), vehicle_caching_internal(), and vehicle_caching_internal_above().
vehicle()
::vehicle& vpart_position::vehicle inline
Definition at line 52 of file vpart_position.h.
{
             return vehicle_.get();
         }
Referenced by get_passenger(), items(), part(), Character::pour_into(), put_into_vehicle(), serialize_liquid_target(), and map::unboard_vehicle().
The documentation for this class was generated from the following files:
src/vpart_position.h
src/vehicle.cpp