Cataclysm DDA: item_location::impl Class Reference
item_location::impl Class Reference abstract
Classes
class item_in_container
class item_on_map
class item_on_person
class item_on_vehicle
class nowhere
Public Member Functions
impl ()=default
impl (item *i)
impl (int idx)
virtual ~impl ()=default
virtual type where () const =0
virtual type where_recursive () const
virtual item_location parent_item () const
virtual item_pocket * parent_pocket () const
virtual tripoint position () const =0
virtual Character * carrier () const =0
virtual std::string describe (const Character *) const =0
virtual item_location obtain (Character &, int)=0
virtual units::volume volume_capacity () const =0
virtual units::mass weight_capacity () const =0
virtual bool check_parent_capacity_recursive () const =0
virtual int obtain_cost (const Character &, int) const =0
virtual void remove_item ()=0
virtual void on_contents_changed ()=0
virtual void serialize (JsonOut &js) const =0
virtual item * unpack (int) const =0
item * target () const
virtual bool valid () const
Public Attributes
bool should_stack = true
Private Member Functions
void ensure_unpacked () const
Private Attributes
safe_reference< item > what
int idx = -1
bool needs_unpacking = false
Detailed Description
Definition at line 66 of file item_location.cpp.
Constructor & Destructor Documentation
impl() [1/3]
item_location::impl::impl () default
impl() [2/3]
item_location::impl::impl (item * i) inline explicit
Definition at line 76 of file item_location.cpp.
 : what( i->get_safe_reference() ) {}
impl() [3/3]
item_location::impl::impl (int idx) inline explicit
Definition at line 77 of file item_location.cpp.
 : idx( idx ), needs_unpacking( true ) {}
~impl()
virtual item_location::impl::~impl () virtual default
Member Function Documentation
carrier()
virtual Character* item_location::impl::carrier () const pure virtual
Implemented in item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, and item_location::impl::nowhere.
check_parent_capacity_recursive()
virtual bool item_location::impl::check_parent_capacity_recursive () const pure virtual
Implemented in item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, and item_location::impl::nowhere.
describe()
virtual std::string item_location::impl::describe (const Character *) const pure virtual
Implemented in item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, item_location::impl::item_in_container, and item_location::impl::nowhere.
ensure_unpacked()
void item_location::impl::ensure_unpacked () const inline private
Definition at line 115 of file item_location.cpp.
{
             if( needs_unpacking ) {
                 if( item *i = unpack( idx ) ) {
                     what = i->get_safe_reference();
                 } else {
                     debugmsg( "item_location lost its target item during a save/load cycle" );
                 }
                 needs_unpacking = false;
             }
         }
References debugmsg, item::get_safe_reference(), idx, needs_unpacking, unpack(), and what.
Referenced by target(), valid(), and item_location::impl::item_on_person::valid().
obtain()
virtual item_location item_location::impl::obtain (Character & , int) pure virtual
Implemented in item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, item_location::impl::item_in_container, and item_location::impl::nowhere.
obtain_cost()
virtual int item_location::impl::obtain_cost (const Character & , int) const pure virtual
Implemented in item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, and item_location::impl::nowhere.
on_contents_changed()
virtual void item_location::impl::on_contents_changed () pure virtual
Implemented in item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, and item_location::impl::nowhere.
parent_item()
virtual item_location item_location::impl::parent_item () const inline virtual
Reimplemented in item_location::impl::item_in_container.
Definition at line 85 of file item_location.cpp.
{
             return item_location();
         }
References item_location::item_location().
parent_pocket()
virtual item_pocket* item_location::impl::parent_pocket () const inline virtual
Reimplemented in item_location::impl::item_in_container.
Definition at line 88 of file item_location.cpp.
{
             return nullptr;
         }
position()
virtual tripoint item_location::impl::position () const pure virtual
Implemented in item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, and item_location::impl::nowhere.
remove_item()
virtual void item_location::impl::remove_item () pure virtual
Implemented in item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, and item_location::impl::nowhere.
serialize()
virtual void item_location::impl::serialize (JsonOut & js) const pure virtual
Implemented in item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, and item_location::impl::nowhere.
target()
item* item_location::impl::target () const inline
Definition at line 104 of file item_location.cpp.
{
             ensure_unpacked();
             return what.get();
         }
References ensure_unpacked(), safe_reference< T >::get(), and what.
Referenced by item_location::impl::item_in_container::calc_index(), item_location::impl::item_in_container::describe(), item_location::impl::item_on_person::describe(), item_location::impl::item_in_container::obtain(), item_location::impl::item_on_map::obtain(), item_location::impl::item_on_person::obtain(), item_location::impl::item_on_vehicle::obtain(), item_location::impl::item_on_map::obtain_cost(), item_location::impl::item_on_person::obtain_cost(), item_location::impl::item_on_vehicle::obtain_cost(), item_location::impl::item_in_container::obtain_cost(), item_location::impl::item_on_map::on_contents_changed(), item_location::impl::item_on_person::on_contents_changed(), item_location::impl::item_on_vehicle::on_contents_changed(), item_location::impl::item_in_container::on_contents_changed(), item_location::impl::item_in_container::parent_pocket(), item_location::impl::item_on_vehicle::remove_item(), item_location::impl::item_in_container::remove_item(), item_location::impl::item_on_map::serialize(), item_location::impl::item_on_person::serialize(), item_location::impl::item_on_vehicle::serialize(), and item_location::impl::item_in_container::unpack().
unpack()
virtual item* item_location::impl::unpack (int) const pure virtual
Implemented in item_location::impl::nowhere, item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, and item_location::impl::item_on_map.
Referenced by ensure_unpacked().
valid()
virtual bool item_location::impl::valid () const inline virtual
Reimplemented in item_location::impl::item_on_person.
Definition at line 109 of file item_location.cpp.
{
             ensure_unpacked();
             return !!what;
         }
References ensure_unpacked(), and what.
volume_capacity()
virtual units::volume item_location::impl::volume_capacity () const pure virtual
Implemented in item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, and item_location::impl::nowhere.
weight_capacity()
virtual units::mass item_location::impl::weight_capacity () const pure virtual
Implemented in item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, and item_location::impl::nowhere.
where()
virtual type item_location::impl::where () const pure virtual
Implemented in item_location::impl::item_in_container, item_location::impl::item_on_vehicle, item_location::impl::item_on_person, item_location::impl::item_on_map, and item_location::impl::nowhere.
Referenced by where_recursive().
where_recursive()
virtual type item_location::impl::where_recursive () const inline virtual
Reimplemented in item_location::impl::item_in_container.
Definition at line 82 of file item_location.cpp.
{
             return where();
         }
References where().
Member Data Documentation
idx
int item_location::impl::idx = -1 mutable private
Definition at line 126 of file item_location.cpp.
Referenced by item_location::impl::item_in_container::calc_index(), ensure_unpacked(), item_location::impl::item_on_map::unpack(), item_location::impl::item_on_person::unpack(), item_location::impl::item_on_vehicle::unpack(), and item_location::impl::item_in_container::unpack().
needs_unpacking
bool item_location::impl::needs_unpacking = false mutable private
Definition at line 127 of file item_location.cpp.
Referenced by ensure_unpacked().
should_stack
bool item_location::impl::should_stack = true
Definition at line 132 of file item_location.cpp.
Referenced by item_location::impl::item_in_container::obtain(), item_location::impl::item_on_map::obtain(), item_location::impl::item_on_person::obtain(), and item_location::impl::item_on_vehicle::obtain().
what
safe_reference<item> item_location::impl::what mutable private
Definition at line 125 of file item_location.cpp.
Referenced by ensure_unpacked(), item_location::impl::item_on_map::remove_item(), item_location::impl::item_on_person::remove_item(), target(), valid(), and item_location::impl::item_on_person::valid().
The documentation for this class was generated from the following file:
src/item_location.cpp