Cataclysm DDA: time_duration Class Reference
time_duration Class Reference
A duration defined as a number of specific time units.
#include <calendar.h>
Public Member Functions
time_duration ()
void serialize (JsonOut &jsout) const
void deserialize (const JsonValue &jsin)
Static Public Member Functions
template<typename T >
static constexpr time_duration from_turns (const T t)
Named constructors to get a duration representing a multiple of the named time units.
template<typename T >
static constexpr time_duration from_moves (const T t)
template<typename T >
static constexpr time_duration from_seconds (const T t)
template<typename T >
static constexpr time_duration from_minutes (const T m)
template<typename T >
static constexpr time_duration from_hours (const T h)
template<typename T >
static constexpr time_duration from_days (const T d)
template<typename T >
static constexpr time_duration from_weeks (const T d)
Private Member Functions
constexpr time_duration (const int t)
Private Attributes
int turns_
Friends
class time_point
template<typename T >
constexpr friend T to_turns (const time_duration &duration)
Converts the duration to an amount of the given units.
template<typename T >
constexpr friend T to_seconds (const time_duration &duration)
template<typename T >
constexpr friend T to_minutes (const time_duration &duration)
template<typename T >
constexpr friend T to_hours (const time_duration &duration)
template<typename T >
constexpr friend T to_days (const time_duration &duration)
template<typename T >
constexpr friend T to_weeks (const time_duration &duration)
template<typename T >
constexpr friend T to_moves (const time_duration &duration)
constexpr friend time_duration operator- (const time_duration &duration)
constexpr friend time_duration operator+ (const time_duration &lhs, const time_duration &rhs)
time_duration & operator+= (time_duration &lhs, const time_duration &rhs)
constexpr friend time_duration operator- (const time_duration &lhs, const time_duration &rhs)
time_duration & operator-= (time_duration &lhs, const time_duration &rhs)
double operator/ (const time_duration &lhs, const time_duration &rhs)
template<typename T >
constexpr friend time_duration operator/ (const time_duration &lhs, const T rhs)
template<typename T >
time_duration & operator/= (time_duration &lhs, const T rhs)
template<typename T >
constexpr friend time_duration operator* (const time_duration &lhs, const T rhs)
template<typename T >
constexpr friend time_duration operator* (const T lhs, const time_duration &rhs)
template<typename T >
time_duration & operator*= (time_duration &lhs, const T rhs)
time_duration operator% (const time_duration &lhs, const time_duration &rhs)
time_duration rng (time_duration lo, time_duration hi)
Returns a random duration in the range [low, hi].
static const std::vector< std::pair< std::string, time_duration > > units
constexpr bool operator< (const time_duration &rhs) const
constexpr bool operator<= (const time_duration &rhs) const
constexpr bool operator> (const time_duration &rhs) const
constexpr bool operator>= (const time_duration &rhs) const
constexpr bool operator== (const time_duration &rhs) const
constexpr bool operator!= (const time_duration &rhs) const
Detailed Description
A duration defined as a number of specific time units.
Currently it stores the number (as integer) of turns. Note: currently variable season length is ignored by this class (N turns are always N turns) and there is no way to create an instance from units larger than days (e.g. seasons or years) and no way to convert a duration into those units directly. (You can still use calendar to do this.)
Operators for time points and time duration are defined as one may expect them: -duration ==> duration (inverse) point - point ==> duration (duration between to points in time) point + duration ==> point (the revers of above) point - duration ==> point (same as: point + -duration) duration + duration ==> duration duration - duration ==> duration (same as: duration + -duration) duration * scalar ==> duration (simple scaling yields a double with precise value) scalar * duration ==> duration (same as above) duration / duration ==> scalar (revers of above) duration / scalar ==> duration (same as: duration * 1/scalar) duration % duration ==> duration ("remainder" of duration / some integer) Also shortcuts: += and -= and *= and /=
Definition at line 196 of file calendar.h.
Constructor & Destructor Documentation
time_duration() [1/2]
constexpr time_duration::time_duration (const int t) inline explicit constexpr private
Definition at line 202 of file calendar.h.
 : turns_( t ) { }
time_duration() [2/2]
time_duration::time_duration () inline
Definition at line 205 of file calendar.h.
 : turns_( 0 ) {}
Referenced by from_moves(), from_seconds(), and from_turns().
Member Function Documentation
deserialize()
void time_duration::deserialize (const JsonValue & jsin)
Definition at line 2694 of file savegame_json.cpp.
 {
     if( jsin.test_string() ) {
         *this = read_from_json_string<time_duration>( jsin, time_duration::units );
     } else {
         turns_ = jsin.get_int();
     }
 }
References JsonValue::get_int(), JsonValue::test_string(), and units.
Referenced by pimpl< T >::deserialize().
from_days()
template<typename T > static constexpr time_duration time_duration::from_days (const T d) inline static constexpr
Definition at line 241 of file calendar.h.
{
             return from_hours( d * 24 );
         }
References from_hours().
Referenced by monster::extended_description(), from_weeks(), mtype::load(), operator""_days(), and calendar::season_length().
from_hours()
template<typename T > static constexpr time_duration time_duration::from_hours (const T h) inline static constexpr
Definition at line 237 of file calendar.h.
{
             return from_minutes( h * 60 );
         }
References from_minutes().
Referenced by npc::complain(), from_days(), operator""_hours(), and game::debug_hour_timer::print_time().
from_minutes()
template<typename T > static constexpr time_duration time_duration::from_minutes (const T m) inline static constexpr
Definition at line 233 of file calendar.h.
{
             return from_turns( m * 60 );
         }
References from_turns().
Referenced by chop_moves(), npc::complain(), from_hours(), Character::get_consume_time(), bionic_install_preset::get_operation_duration(), bionic_install_surgeon_preset::get_operation_duration(), anonymous_namespace{monexamine.cpp}::milk_source(), operator""_minutes(), monexamine::pay_bot(), iuse::pick_lock(), iuse::play_music(), weakpoint_families::practice_dissect(), and weakpoint_families::practice_kill().
from_moves()
template<typename T > static constexpr time_duration time_duration::from_moves (const T t) inline static constexpr
Definition at line 225 of file calendar.h.
{
             return time_duration( t / 100 );
         }
References time_duration().
Referenced by add_effect_to_target(), iexamine::autodoc(), game::butcher(), butcher_submenu(), read_activity_actor::do_turn(), safecracking_activity_actor::do_turn(), spell::duration_turns(), vehicle::engine_start_time(), lockpick_activity_actor::finish(), basecamp::get_available_missions_by_dir(), Character::get_consume_time(), construction::get_time_string(), moves_to_string(), basecamp::om_upgrade_description(), activity_handlers::operation_do_turn(), parse_vp_reqs(), debug_menu::spell_description(), lockpick_activity_actor::start(), read_activity_actor::start(), basecamp::start_multi_mission(), recipe::time_to_craft(), vehicle_unfolding_activity_actor::vehicle_unfolding_activity_actor(), and iuse::wash_items().
from_seconds()
template<typename T > static constexpr time_duration time_duration::from_seconds (const T t) inline static constexpr
Definition at line 229 of file calendar.h.
{
             return time_duration( t );
         }
References time_duration().
Referenced by iuse::c4(), calc_spell_training_time(), craft_activity_actor::do_turn(), eff_fun_fake_common_cold(), eff_fun_fake_flu(), Character::get_consume_time(), hackveh(), activity_handlers::hand_crank_do_turn(), heat_item(), item::io(), iuse::mininuke(), operator""_seconds(), units::operator/(), timed_event::per_turn(), weakpoint_families::practice_hit(), Character::practice_proficiency(), monster::process_one_effect(), prying_activity_actor::prying_time(), npc::time_to_read(), Character::time_to_read(), place_trap_actor::use(), and debug_menu::wisheffect().
from_turns()
template<typename T > static constexpr time_duration time_duration::from_turns (const T t) inline static constexpr
Named constructors to get a duration representing a multiple of the named time units.
Note that a duration is stored as integer number of turns, so from_minutes(0.0001) will be stored as "0 turns". The template type is used for the conversion from given time unit to turns, so from_hours(0.5) will yield "1800 turns". Conversion of units greater than days (seasons) is not supported because they depend on option settings ("season length").
Definition at line 221 of file calendar.h.
{
             return time_duration( t );
         }
References time_duration().
Referenced by outfit::absorb_damage(), mattack::acid_barf(), effect::activated(), add_salvagables(), ma_buff::apply_buff(), apply_construction_marker(), weakpoint_effect::apply_to(), recipe::batch_duration(), map::burn_body_part(), leap_actor::call(), melee_actor::call(), item::charge_linked_batteries(), recipe::check_blueprint_requirements(), basecamp::choose_new_leader(), Character::trait_data::deserialize(), bionic::deserialize(), eff_fun_hallu(), basecamp::emergency_recall(), duration_or_var_part::evaluate(), item::final_info(), heal_actor::finish_using(), explosion_handler::flashbang(), iuse::foodperson(), from_minutes(), Character::get_book_reader(), get_duration_or_var_part(), monster::impact(), field_entry::initialize_decay(), mutation_branch::load(), damage_over_time_data::load(), musical_instrument_actor::load(), submap::load(), load_effect_data(), monster::melee_attack(), iuse::mininuke(), game::mon_info_update(), melee_actor::on_damage(), operator""_turns(), opiate_effect(), vehicle::part_collision(), Character::perform_technique(), vehicle::print_fuel_indicator(), Character::process_one_effect(), sounds::process_sound_markers(), monster::push_to(), iexamine::quern_examine(), read_inventory_preset::read_inventory_preset(), recipe_info(), zone_data::refresh_display(), explosion_handler::resonance_cascade(), display::safe_mode_text_color(), salvage_inventory_preset::salvage_inventory_preset(), calendar_ui::select_time_point(), talker_character::set_addiction_turns(), Character::set_proficiency_practiced_time(), iexamine::smoker_options(), gun_actor::try_target(), Character::vitamin_rate(), and wait().
from_weeks()
template<typename T > static constexpr time_duration time_duration::from_weeks (const T d) inline static constexpr
Definition at line 245 of file calendar.h.
{
             return from_days( d * 7 );
         }
References from_days().
Referenced by operator""_weeks().
operator!=()
constexpr bool time_duration::operator!= (const time_duration & rhs) const inline constexpr
Definition at line 306 of file calendar.h.
{
             return turns_ != rhs.turns_;
         }
References turns_.
operator<()
constexpr bool time_duration::operator< (const time_duration & rhs) const inline constexpr
Definition at line 291 of file calendar.h.
{
             return turns_ < rhs.turns_;
         }
References turns_.
operator<=()
constexpr bool time_duration::operator<= (const time_duration & rhs) const inline constexpr
Definition at line 294 of file calendar.h.
{
             return turns_ <= rhs.turns_;
         }
References turns_.
operator==()
constexpr bool time_duration::operator== (const time_duration & rhs) const inline constexpr
Definition at line 303 of file calendar.h.
{
             return turns_ == rhs.turns_;
         }
References turns_.
operator>()
constexpr bool time_duration::operator> (const time_duration & rhs) const inline constexpr
Definition at line 297 of file calendar.h.
{
             return turns_ > rhs.turns_;
         }
References turns_.
operator>=()
constexpr bool time_duration::operator>= (const time_duration & rhs) const inline constexpr
Definition at line 300 of file calendar.h.
{
             return turns_ >= rhs.turns_;
         }
References turns_.
serialize()
void time_duration::serialize (JsonOut & jsout) const
Definition at line 2689 of file savegame_json.cpp.
 {
     jsout.write( turns_ );
 }
References JsonOut::write().
Referenced by pimpl< T >::serialize().
Friends And Related Function Documentation
operator%
time_duration operator% (const time_duration & lhs, const time_duration & rhs) friend
Definition at line 349 of file calendar.h.
{
             return time_duration( lhs.turns_ % rhs.turns_ );
         }
operator* [1/2]
template<typename T > constexpr friend time_duration operator* (const T lhs, const time_duration & rhs) friend
Definition at line 342 of file calendar.h.
{
             return time_duration( lhs * rhs.turns_ );
         }
operator* [2/2]
template<typename T > constexpr friend time_duration operator* (const time_duration & lhs, const T rhs) friend
Definition at line 338 of file calendar.h.
{
             return time_duration( lhs.turns_ * rhs );
         }
operator*=
template<typename T > time_duration& operator*= (time_duration & lhs, const T rhs) friend
Definition at line 346 of file calendar.h.
{
             return lhs = time_duration( lhs.turns_ * rhs );
         }
operator+
constexpr friend time_duration operator+ (const time_duration & lhs, const time_duration & rhs) friend
Definition at line 313 of file calendar.h.
{
             return time_duration( lhs.turns_ + rhs.turns_ );
         }
operator+=
time_duration& operator+= (time_duration & lhs, const time_duration & rhs) friend
Definition at line 316 of file calendar.h.
{
             return lhs = time_duration( lhs.turns_ + rhs.turns_ );
         }
operator- [1/2]
constexpr friend time_duration operator- (const time_duration & duration) friend
Definition at line 310 of file calendar.h.
{
             return time_duration( -duration.turns_ );
         }
operator- [2/2]
constexpr friend time_duration operator- (const time_duration & lhs, const time_duration & rhs) friend
Definition at line 319 of file calendar.h.
{
             return time_duration( lhs.turns_ - rhs.turns_ );
         }
operator-=
time_duration& operator-= (time_duration & lhs, const time_duration & rhs) friend
Definition at line 322 of file calendar.h.
{
             return lhs = time_duration( lhs.turns_ - rhs.turns_ );
         }
operator/ [1/2]
template<typename T > constexpr friend time_duration operator/ (const time_duration & lhs, const T rhs) friend
Definition at line 330 of file calendar.h.
{
             return time_duration( lhs.turns_ / rhs );
         }
operator/ [2/2]
double operator/ (const time_duration & lhs, const time_duration & rhs) friend
Definition at line 326 of file calendar.h.
{
             return static_cast<double>( lhs.turns_ ) / static_cast<double>( rhs.turns_ );
         }
operator/=
template<typename T > time_duration& operator/= (time_duration & lhs, const T rhs) friend
Definition at line 334 of file calendar.h.
{
             return lhs = time_duration( lhs.turns_ / rhs );
         }
rng
time_duration rng (time_duration lo, time_duration hi) friend
Returns a random duration in the range [low, hi].
Definition at line 779 of file calendar.cpp.
 {
     return time_duration( rng( lo.turns_, hi.turns_ ) );
 }
time_point
friend class time_point friend
Definition at line 199 of file calendar.h.
to_days
template<typename T > constexpr friend T to_days (const time_duration & duration) friend
Definition at line 278 of file calendar.h.
{
             return static_cast<T>( duration.turns_ ) / static_cast<T>( 60 * 60 * 24 );
         }
to_hours
template<typename T > constexpr friend T to_hours (const time_duration & duration) friend
Definition at line 274 of file calendar.h.
{
             return static_cast<T>( duration.turns_ ) / static_cast<T>( 60 * 60 );
         }
to_minutes
template<typename T > constexpr friend T to_minutes (const time_duration & duration) friend
Definition at line 270 of file calendar.h.
{
             return static_cast<T>( duration.turns_ ) / static_cast<T>( 60 );
         }
to_moves
template<typename T > constexpr friend T to_moves (const time_duration & duration) friend
Definition at line 286 of file calendar.h.
{
             return to_turns<int>( duration ) * 100;
         }
to_seconds
template<typename T > constexpr friend T to_seconds (const time_duration & duration) friend
Definition at line 266 of file calendar.h.
{
             return duration.turns_;
         }
to_turns
template<typename T > constexpr friend T to_turns (const time_duration & duration) friend
Converts the duration to an amount of the given units.
The conversions is done with values of the given template type. That means using an integer type (e.g. int) will return a truncated value (amount of full minutes that make up the duration, discarding the remainder). Calling to_minutes<double> will return a precise number. Example: to_hours<int>(from_minutes(90)) == 1 to_hours<double>(from_minutes(90)) == 1.5
Definition at line 262 of file calendar.h.
{
             return duration.turns_;
         }
to_weeks
template<typename T > constexpr friend T to_weeks (const time_duration & duration) friend
Definition at line 282 of file calendar.h.
{
             return static_cast<T>( duration.turns_ ) / static_cast<T>( 60 * 60 * 24 * 7 );
         }
Member Data Documentation
turns_
int time_duration::turns_ private
Definition at line 200 of file calendar.h.
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
units
const std::vector< std::pair< std::string, time_duration > > time_duration::units static
Initial value:
= { {
        { "turns", 1_turns },
        { "turn", 1_turns },
        { "t", 1_turns },
        { "seconds", 1_seconds },
        { "second", 1_seconds },
        { "s", 1_seconds },
        { "minutes", 1_minutes },
        { "minute", 1_minutes },
        { "m", 1_minutes },
        { "hours", 1_hours },
        { "hour", 1_hours },
        { "h", 1_hours },
        { "days", 1_days },
        { "day", 1_days },
        { "d", 1_days },
    }
}
Definition at line 356 of file calendar.h.
Referenced by anonymous_namespace{math_parser_diag.cpp}::_time_in_unit(), abstract_read_var_info(), recipe::check_blueprint_requirements(), deserialize(), get_duration_or_var_part(), mtype::load(), recipe::load(), enchantment::load(), damage_over_time_data::load(), Item_factory::load(), load_construction(), load_effect_data(), vitamin::load_vitamin(), read_with_factor(), and anonymous_namespace{math_parser_diag.cpp}::time_eval().
The documentation for this class was generated from the following files:
src/calendar.h
src/calendar.cpp
src/savegame_json.cpp