Cataclysm DDA: glide_activity_actor Class Reference
glide_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
glide_activity_actor (Character *you, int jump_direction, int glide_distance)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &you) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &you) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
glide_activity_actor ()=default
Private Attributes
int jump_direction
int glide_distance
int moved_tiles = 0
int moves_total = to_moves<int>(1_seconds)
Detailed Description
Definition at line 353 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
glide_activity_actor() [1/2]
glide_activity_actor::glide_activity_actor () explicit private default
glide_activity_actor() [2/2]
glide_activity_actor::glide_activity_actor (Character * you, int jump_direction, int glide_distance) explicit
Definition at line 1646 of file activity_actor.cpp.
     : jump_direction( jump_direction ), glide_distance( glide_distance )
 {
     you->add_effect( effect_gliding, 1_turns, true );
     tripoint heading;
     if( jump_direction == 0 ) {
         heading = tripoint_south;
     }
     if( jump_direction == 1 ) {
         heading = tripoint_south_west;
     }
     if( jump_direction == 2 ) {
         heading = tripoint_west;
     }
     if( jump_direction == 3 ) {
         heading = tripoint_north_west;
     }
     if( jump_direction == 4 ) {
         heading = tripoint_north;
     }
     if( jump_direction == 5 ) {
         heading = tripoint_north_east;
     }
     if( jump_direction == 6 ) {
         heading = tripoint_east;
     }
     if( jump_direction == 7 ) {
         heading = tripoint_south_west;
     }
 }
References Creature::add_effect(), effect_gliding, jump_direction, tripoint_east, tripoint_north, tripoint_north_east, tripoint_north_west, tripoint_south, tripoint_south_west, and tripoint_west.
Member Function Documentation
clone()
std::unique_ptr<activity_actor> glide_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 373 of file activity_actor_definitions.h.
{
             return std::make_unique<glide_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > glide_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 1689 of file activity_actor.cpp.
 {
     glide_activity_actor actor;
     JsonObject data = jsin.get_object();
     data.read( "moved_tiles", actor.moved_tiles );
     data.read( "moves_total", actor.moves_total );
     data.read( "jump_direction", actor.jump_direction );
     data.read( "glide_distance", actor.glide_distance );
     return actor.clone();
 }
References clone(), JsonValue::get_object(), glide_distance, jump_direction, moved_tiles, moves_total, and JsonObject::read().
do_turn()
void glide_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1555 of file activity_actor.cpp.
 {
     tripoint heading;
     if( jump_direction == 0 ) {
         heading = tripoint_south;
     }
     if( jump_direction == 1 ) {
         heading = tripoint_south_west;
     }
     if( jump_direction == 2 ) {
         heading = tripoint_west;
     }
     if( jump_direction == 3 ) {
         heading = tripoint_north_west;
     }
     if( jump_direction == 4 ) {
         heading = tripoint_north;
     }
     if( jump_direction == 5 ) {
         heading = tripoint_north_east;
     }
     if( jump_direction == 6 ) {
         heading = tripoint_east;
     }
     if( jump_direction == 7 ) {
         heading = tripoint_south_east;
     }
     const tripoint_abs_ms newpos = you.get_location() + heading;
     const tripoint_bub_ms checknewpos = you.pos_bub() + heading;
     if( get_map().tr_at( you.pos() ) != tr_ledge || heading == tripoint_zero ) {
         you.add_msg_player_or_npc( m_good,
                                    _( "You come to a gentle landing." ),
                                    _( "<npcname> comes to a gentle landing." ) );
         you.remove_effect( effect_gliding );
         you.gravity_check();
         act.set_to_null();
         return;
     }   // Have we crashed into a wall?
     if( get_map().impassable( checknewpos ) ) {
         you.add_msg_player_or_npc( m_bad,
                                    _( "You collide with %s, bringing an abrupt halt to your glide." ),
                                    _( "<npcname> collides with %s, bringing an abrupt halt to their glide." ),
                                    get_map().tername( checknewpos.raw() ) );
         you.remove_effect( effect_gliding );
         you.gravity_check();
         act.set_to_null();
         return;
     }
     if( !you.can_fly() ) {
         you.remove_effect( effect_gliding );
         you.gravity_check();
         act.set_to_null();
         return;
     }
     Creature *creature_ahead = get_creature_tracker().creature_at( newpos );
     if( creature_ahead && creature_ahead->get_size() >= creature_size::medium &&
         you.get_size() >= creature_size::medium ) {
         // Zombies are too stupid to avoid midair collision
         if( !you.dodge_check( 15, true ) || ( !creature_ahead->in_species( species_ZOMBIE ) &&
                                               !creature_ahead->dodge_check( 15, true ) ) ) {
             you.add_msg_player_or_npc( m_bad,
                                        _( "You collide with %s, bringing an abrupt halt to your glide." ),
                                        _( "<npcname> collides with %s, bringing an abrupt halt to their glide." ),
                                        creature_ahead->disp_name() );
             if( creature_ahead->get_size() < creature_size::huge ) {
                 creature_ahead->add_effect( effect_downed, 2_turns, false );
             }
             you.remove_effect( effect_gliding );
             you.gravity_check();
             act.set_to_null();
             return;
         }
         you.add_msg_player_or_npc( m_good,
                                    _( "You deftly maneuver around %s." ),
                                    _( "<npcname> deftly maneuvers around %s." ), creature_ahead->disp_name() );
     }
     you.move_to( newpos );
     moved_tiles ++;
     if( moved_tiles >= glide_distance ) {
         g->vertical_move( -1, false, false );
         moved_tiles = 0;
     }
     you.mod_moves( -you.get_speed() * 0.5 );
     get_map().update_visibility_cache( you.pos().z );
     get_map().update_visibility_cache( you.pos().x );
     get_map().update_visibility_cache( you.pos().y );
     if( you.is_avatar() ) {
         g->update_map( you );
     }
 }
References _, act, Creature::add_effect(), Character::add_msg_player_or_npc(), Character::can_fly(), creature_tracker::creature_at(), Creature::disp_name(), Creature::dodge_check(), effect_downed, effect_gliding, g, get_creature_tracker(), Creature::get_location(), get_map(), Creature::get_size(), Character::get_size(), Character::get_speed(), glide_distance, Character::gravity_check(), huge, impassable, Creature::in_species(), Creature::is_avatar(), jump_direction, m_bad, m_good, medium, Creature::mod_moves(), Creature::move_to(), moved_tiles, Creature::pos(), Creature::pos_bub(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), Creature::remove_effect(), species_ZOMBIE, tr_ledge, tripoint_east, tripoint_north, tripoint_north_east, tripoint_north_west, tripoint_south, tripoint_south_east, tripoint_south_west, tripoint_west, tripoint_zero, map::update_visibility_cache(), tripoint::x, tripoint::y, and tripoint::z.
finish()
void glide_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1705 of file activity_actor.cpp.
 {
     g->update_map( you );
     you.add_msg_player_or_npc( m_good,
                                _( "You come to a gentle landing." ),
                                _( "<npcname> comes to a gentle landing." ) );
     you.remove_effect( effect_gliding );
     you.gravity_check();
     act.set_to_null();
 }
References _, act, Character::add_msg_player_or_npc(), effect_gliding, g, Character::gravity_check(), m_good, and Creature::remove_effect().
get_type()
activity_id glide_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 365 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_GLIDE" );
         }
References activity_id.
serialize()
void glide_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 1677 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moved_tiles", moved_tiles );
     jsout.member( "moves_total", moves_total );
     jsout.member( "jump_direction", jump_direction );
     jsout.member( "glide_distance", glide_distance );
     jsout.end_object();
 }
References JsonOut::end_object(), glide_distance, jump_direction, JsonOut::member(), moved_tiles, moves_total, and JsonOut::start_object().
start()
void glide_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1699 of file activity_actor.cpp.
 {
     act.moves_total = moves_total;
     act.moves_left = moves_total;
 }
References act, and moves_total.
Member Data Documentation
glide_distance
int glide_activity_actor::glide_distance private
Definition at line 357 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
jump_direction
int glide_activity_actor::jump_direction private
Definition at line 356 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), glide_activity_actor(), and serialize().
moved_tiles
int glide_activity_actor::moved_tiles = 0 private
Definition at line 358 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
moves_total
int glide_activity_actor::moves_total = to_moves<int>(1_seconds) private
Definition at line 359 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp