Cataclysm DDA: scrolling_text_view Class Reference
scrolling_text_view Class Reference
#include <output.h>
Public Member Functions
scrolling_text_view (catacurses::window &w)
bool handle_navigation (const std::string &action, input_context &ctxt)
void set_up_navigation (input_context &ctxt, scrolling_key_scheme scheme=scrolling_key_scheme::no_scheme, bool enable_paging=false)
void set_text (const std::string &text, bool scroll_to_top=true)
void scroll_up ()
void scroll_down ()
void page_up ()
void page_down ()
void draw (const nc_color &base_color)
Private Member Functions
int text_width ()
int num_lines ()
int max_offset ()
Private Attributes
catacurses::window & w_
std::vector< std::string > text_
int offset_ = 0
std::string scroll_up_action
std::string scroll_down_action
bool paging_enabled = false
scrollbar text_view_scrollbar
Detailed Description
Definition at line 1026 of file output.h.
Constructor & Destructor Documentation
scrolling_text_view()
scrolling_text_view::scrolling_text_view (catacurses::window & w) inline explicit
Definition at line 1029 of file output.h.
 : w_( w ) {}
Member Function Documentation
draw()
void scrolling_text_view::draw (const nc_color & base_color)
Definition at line 2182 of file output.cpp.
 {
     werase( w_ );
     const int height = getmaxy( w_ );
     if( max_offset() > 0 ) {
         text_view_scrollbar.content_size( text_.size() ).
         viewport_pos( offset_ ).
         viewport_size( height ).
         scroll_to_last( false ).
         apply( w_ );
     } else {
         text_view_scrollbar = scrollbar();
         // No scrollbar; we need to draw the window edge instead
         for( int i = 0; i < height; i++ ) {
             mvwputch( w_, point( 0, i ), BORDER_COLOR, LINE_XOXO );
         }
     }
     nc_color color = base_color;
     int end = std::min( num_lines() - offset_, height );
     for( int line_num = 0; line_num < end; ++line_num ) {
         print_colored_text( w_, point( 1, line_num ), color, base_color,
                             text_[line_num + offset_] );
     }
     wnoutrefresh( w_ );
 }
References apply(), BORDER_COLOR, color(), scrollbar::content_size(), keycode::end, catacurses::getmaxy(), LINE_XOXO, max_offset(), min(), mvwputch(), num_lines(), offset_, point, print_colored_text(), text_, text_view_scrollbar, w_, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by show_scores_ui().
handle_navigation()
bool scrolling_text_view::handle_navigation (const std::string & action, input_context & ctxt)
Definition at line 2212 of file output.cpp.
 {
     std::optional<point> coord = ctxt.get_coordinates_text( catacurses::stdscr );
     inclusive_rectangle<point> mouseover_area( point( getbegx( w_ ), getbegy( w_ ) ),
             point( getmaxx( w_ ) + getbegx( w_ ), getmaxy( w_ ) + getbegy( w_ ) ) );
     bool mouse_in_window = coord.has_value() && mouseover_area.contains( coord.value() );
     if( text_view_scrollbar.handle_dragging( action, coord, offset_ ) ) {
         // No action required, the scrollbar has handled it
     } else if( action == scroll_up_action || ( action == "SCROLL_UP" && mouse_in_window ) ) {
         scroll_up();
     } else if( action == scroll_down_action || ( action == "SCROLL_DOWN" && mouse_in_window ) ) {
         scroll_down();
     } else if( paging_enabled && action == "PAGE_UP" ) {
         page_up();
     } else if( paging_enabled && action == "PAGE_DOWN" ) {
         page_down();
     } else {
         return false;
     }
     return true;
 }
References action, inclusive_rectangle< Point, >::contains(), input_context::get_coordinates_text(), catacurses::getbegx(), catacurses::getbegy(), catacurses::getmaxx(), catacurses::getmaxy(), scrollbar::handle_dragging(), mouse_in_window(), offset_, page_down(), page_up(), paging_enabled, point, scroll_down(), scroll_down_action, scroll_up(), scroll_up_action, catacurses::stdscr, text_view_scrollbar, and w_.
Referenced by show_scores_ui().
max_offset()
int scrolling_text_view::max_offset () private
Definition at line 2273 of file output.cpp.
 {
     return std::max( 0, num_lines() - getmaxy( w_ ) );
 }
References catacurses::getmaxy(), max(), num_lines(), and w_.
Referenced by draw(), page_down(), scroll_down(), and set_text().
num_lines()
int scrolling_text_view::num_lines () private
Definition at line 2268 of file output.cpp.
 {
     return text_.size();
 }
References text_.
Referenced by draw(), and max_offset().
page_down()
void scrolling_text_view::page_down ()
Definition at line 2177 of file output.cpp.
 {
     offset_ = std::min( max_offset(), offset_ + getmaxy( w_ ) );
 }
References catacurses::getmaxy(), max_offset(), min(), offset_, and w_.
Referenced by handle_navigation().
page_up()
void scrolling_text_view::page_up ()
Definition at line 2172 of file output.cpp.
 {
     offset_ = std::max( 0, offset_ - getmaxy( w_ ) );
 }
References catacurses::getmaxy(), max(), offset_, and w_.
Referenced by handle_navigation().
scroll_down()
void scrolling_text_view::scroll_down ()
Definition at line 2165 of file output.cpp.
 {
     if( offset_ < max_offset() ) {
         ++offset_;
     }
 }
References max_offset(), and offset_.
Referenced by handle_navigation().
scroll_up()
void scrolling_text_view::scroll_up ()
Definition at line 2158 of file output.cpp.
 {
     if( offset_ ) {
         --offset_;
     }
 }
References offset_.
Referenced by handle_navigation().
set_text()
void scrolling_text_view::set_text (const std::string & text, bool scroll_to_top = true)
Definition at line 2148 of file output.cpp.
 {
     text_ = foldstring( text, text_width() );
     if( scroll_to_top ) {
         offset_ = 0;
     } else {
         offset_ = max_offset();
     }
 }
References foldstring(), max_offset(), offset_, text_, and text_width().
Referenced by show_scores_ui().
set_up_navigation()
void scrolling_text_view::set_up_navigation (input_context & ctxt, scrolling_key_scheme scheme = scrolling_key_scheme::no_scheme, bool enable_paging = false)
Definition at line 2235 of file output.cpp.
 {
     ctxt.register_action( "CLICK_AND_DRAG" );
     ctxt.register_action( "MOUSE_MOVE" );
     ctxt.register_action( "SCROLL_UP" );
     ctxt.register_action( "SCROLL_DOWN" );
     ctxt.register_action( "SELECT" );
     if( scheme != scrolling_key_scheme::no_scheme ) {
         if( scheme == scrolling_key_scheme::angle_bracket_scroll ) {
             scroll_up_action = "SCROLL_INFOBOX_UP";
             scroll_down_action = "SCROLL_INFOBOX_DOWN";
         } else if( scheme == scrolling_key_scheme::arrow_scroll ) {
             scroll_up_action = "UP";
             scroll_down_action = "DOWN";
         }
         ctxt.register_action( scroll_up_action );
         ctxt.register_action( scroll_down_action );
     }
     if( enable_paging ) {
         paging_enabled = true;
         ctxt.register_action( "PAGE_UP" );
         ctxt.register_action( "PAGE_DOWN" );
     }
     text_view_scrollbar.set_draggable( ctxt );
 }
References angle_bracket_scroll, arrow_scroll, no_scheme, paging_enabled, input_context::register_action(), scroll_down_action, scroll_up_action, scrollbar::set_draggable(), and text_view_scrollbar.
Referenced by show_scores_ui().
text_width()
int scrolling_text_view::text_width () private
Definition at line 2263 of file output.cpp.
 {
     return getmaxx( w_ ) - 1;
 }
References catacurses::getmaxx(), and w_.
Referenced by set_text().
Member Data Documentation
offset_
int scrolling_text_view::offset_ = 0 private
Definition at line 1047 of file output.h.
Referenced by draw(), handle_navigation(), page_down(), page_up(), scroll_down(), scroll_up(), and set_text().
paging_enabled
bool scrolling_text_view::paging_enabled = false private
Definition at line 1050 of file output.h.
Referenced by handle_navigation(), and set_up_navigation().
scroll_down_action
std::string scrolling_text_view::scroll_down_action private
Definition at line 1049 of file output.h.
Referenced by handle_navigation(), and set_up_navigation().
scroll_up_action
std::string scrolling_text_view::scroll_up_action private
Definition at line 1048 of file output.h.
Referenced by handle_navigation(), and set_up_navigation().
text_
std::vector<std::string> scrolling_text_view::text_ private
Definition at line 1046 of file output.h.
Referenced by draw(), num_lines(), and set_text().
text_view_scrollbar
scrollbar scrolling_text_view::text_view_scrollbar private
Definition at line 1051 of file output.h.
Referenced by draw(), handle_navigation(), and set_up_navigation().
w_
catacurses::window& scrolling_text_view::w_ private
Definition at line 1045 of file output.h.
Referenced by draw(), handle_navigation(), max_offset(), page_down(), page_up(), and text_width().
The documentation for this class was generated from the following files:
src/output.h
src/output.cpp