Cataclysm DDA: map_memory Class Reference
map_memory Class Reference
Manages map tiles memorized by the avatar.
#include <map_memory.h>
Classes
struct coord_pair
Helper class for converting global ms coord into global sm coord + ms coord within the submap.
Public Member Functions
map_memory ()
bool is_valid () const
void load (const tripoint_abs_ms &pos)
Load memorized submaps around given global map square pos.
bool save (const tripoint_abs_ms &pos)
Save memorized submaps to disk, drop ones far from given global map square pos.
bool prepare_region (const tripoint_abs_ms &p1, const tripoint_abs_ms &p2)
Prepares map memory for rendering and/or memorization of given region.
const memorized_tile & get_tile (const tripoint_abs_ms &pos) const
Returns memorized tile.
void set_tile_terrain (const tripoint_abs_ms &pos, std::string_view id, int subtile, int rotation)
Memorizes terrain at pos, overwriting old terrain values.
void set_tile_decoration (const tripoint_abs_ms &pos, std::string_view id, int subtile, int rotation)
Memorizes decoraiton at pos, overwriting old decoration values.
void set_tile_symbol (const tripoint_abs_ms &pos, char32_t symbol)
Memorizes symbol at pos, overwriting old symbol.
void clear_tile_decoration (const tripoint_abs_ms &pos, std::string_view prefix="")
Clears memorized decorations and symbol.
Private Member Functions
shared_ptr_fast< mm_submap > fetch_submap (const tripoint_abs_sm &sm_pos)
Find, load or allocate a submap.
shared_ptr_fast< mm_submap > find_submap (const tripoint_abs_sm &sm_pos)
Find submap amongst the loaded submaps.
shared_ptr_fast< mm_submap > load_submap (const tripoint_abs_sm &sm_pos)
Load submap from disk.
shared_ptr_fast< mm_submap > allocate_submap (const tripoint_abs_sm &sm_pos)
Allocate empty submap.
const mm_submap & get_submap (const tripoint_abs_sm &sm_pos) const
Get submap from within the cache.
mm_submap & get_submap (const tripoint_abs_sm &sm_pos)
void clear_cache ()
Private Attributes
std::map< tripoint_abs_sm, shared_ptr_fast< mm_submap > > submaps
std::map< int, std::vector< shared_ptr_fast< mm_submap > > > cached
tripoint_abs_sm cache_pos
point cache_size
Detailed Description
Manages map tiles memorized by the avatar.
Definition at line 98 of file map_memory.h.
Constructor & Destructor Documentation
map_memory()
map_memory::map_memory ()
Definition at line 186 of file map_memory.cpp.
 {
     clear_cache();
 }
References clear_cache().
Member Function Documentation
allocate_submap()
shared_ptr_fast< mm_submap > map_memory::allocate_submap (const tripoint_abs_sm & sm_pos) private
Allocate empty submap.
Returns
the submap.
Definition at line 310 of file map_memory.cpp.
 {
     // Since all save/load operations are done on regions of submaps,
     // we need to allocate the whole region at once.
     shared_ptr_fast<mm_submap> ret;
     tripoint reg = reg_coord_pair( sm_pos ).reg;
     dbg( D_INFO ) << "Allocated mm_region " << reg << " [" << mmr_to_sm_copy( reg ) << "]";
     for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
         for( size_t x = 0; x < MM_REG_SIZE; x++ ) {
             const tripoint_abs_sm pos( mmr_to_sm_copy( reg ) + tripoint( x, y, 0 ) );
             shared_ptr_fast<mm_submap> sm = make_shared_fast<mm_submap>();
             if( pos == sm_pos ) {
                 ret = sm;
             }
             submaps.insert( std::make_pair( pos, sm ) );
         }
     }
     return ret;
 }
References D_INFO, dbg, MM_REG_SIZE, mmr_to_sm_copy(), math_opers::pos(), reg_coord_pair::reg, cata::hash64_detail::ret, coords::sm, submaps, and tripoint.
Referenced by fetch_submap().
clear_cache()
void map_memory::clear_cache () private
Definition at line 502 of file map_memory.cpp.
 {
     cached.clear();
     cache_pos = invalid_cache_pos;
     cache_size = point_zero;
 }
References cache_pos, cache_size, cached, invalid_cache_pos, and point_zero.
Referenced by load(), map_memory(), and save().
clear_tile_decoration()
void map_memory::clear_tile_decoration (const tripoint_abs_ms & pos, std::string_view prefix = "")
Clears memorized decorations and symbol.
Parameters
pos tile position, in global ms coords.
prefix if non-empty only clears if decoration starts with this prefix
Definition at line 240 of file map_memory.cpp.
 {
     const coord_pair p( pos );
     mm_submap &sm = get_submap( p.sm );
     if( !sm.is_valid() ) {
         return;
     }
     memorized_tile mt = sm.get_tile( p.loc );
     if( string_starts_with( mt.get_dec_id(), prefix ) ) {
         mt.set_dec_id( "" );
         mt.set_dec_rotation( 0 );
         mt.set_dec_subtile( 0 );
         mt.symbol = 0;
     }
     sm.set_tile( p.loc, mt );
 }
References memorized_tile::get_dec_id(), get_submap(), map_memory::coord_pair::loc, math_opers::pos(), prefix, memorized_tile::set_dec_id(), memorized_tile::set_dec_rotation(), memorized_tile::set_dec_subtile(), coords::sm, map_memory::coord_pair::sm, string_starts_with(), and memorized_tile::symbol.
fetch_submap()
shared_ptr_fast< mm_submap > map_memory::fetch_submap (const tripoint_abs_sm & sm_pos) private
Find, load or allocate a submap.
Returns
the submap.
Definition at line 297 of file map_memory.cpp.
 {
     shared_ptr_fast<mm_submap> sm = find_submap( sm_pos );
     if( sm ) {
         return sm;
     }
     sm = load_submap( sm_pos );
     if( sm ) {
         return sm;
     }
     return allocate_submap( sm_pos );
 }
References allocate_submap(), find_submap(), load_submap(), and coords::sm.
Referenced by load(), and prepare_region().
find_submap()
shared_ptr_fast< mm_submap > map_memory::find_submap (const tripoint_abs_sm & sm_pos) private
Find submap amongst the loaded submaps.
Returns
nullptr if failed.
Definition at line 333 of file map_memory.cpp.
 {
     auto sm = submaps.find( sm_pos );
     if( sm == submaps.end() ) {
         return nullptr;
     } else {
         return sm->second;
     }
 }
References coords::sm, and submaps.
Referenced by fetch_submap().
get_submap() [1/2]
mm_submap & map_memory::get_submap (const tripoint_abs_sm & sm_pos) private
Definition at line 395 of file map_memory.cpp.
 {
     if( !is_valid() ) {
         return invalid_mz_submap;
     }
     const point_rel_sm idx = ( sm_pos - cache_pos ).xy();
     if( idx.x() > 0 && idx.y() > 0 && idx.x() < cache_size.x && idx.y() < cache_size.y &&
         !cached[sm_pos.z()].empty() ) {
         return *cached[sm_pos.z()][idx.y() * cache_size.x + idx.x()];
     } else {
         return null_mz_submap;
     }
 }
References cache_pos, cache_size, cached, invalid_mz_submap, is_valid(), null_mz_submap, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), point::x, coords::coord_point_mut< Point, Subpoint, InBounds >::y(), point::y, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
get_submap() [2/2]
const mm_submap & map_memory::get_submap (const tripoint_abs_sm & sm_pos) const private
Get submap from within the cache.
Definition at line 390 of file map_memory.cpp.
 {
     return const_cast<map_memory *>( this )->get_submap( sm_pos );
 }
Referenced by clear_tile_decoration(), get_tile(), set_tile_decoration(), set_tile_symbol(), and set_tile_terrain().
get_tile()
const memorized_tile & map_memory::get_tile (const tripoint_abs_ms & pos) const
Returns memorized tile.
Parameters
pos tile position, in global ms coords.
Definition at line 191 of file map_memory.cpp.
 {
     const coord_pair p( pos );
     const mm_submap &sm = get_submap( p.sm );
     return sm.get_tile( p.loc );
 }
References get_submap(), map_memory::coord_pair::loc, math_opers::pos(), coords::sm, and map_memory::coord_pair::sm.
is_valid()
bool map_memory::is_valid () const
Definition at line 409 of file map_memory.cpp.
 {
     return cache_pos != invalid_cache_pos;
 }
References cache_pos, and invalid_cache_pos.
Referenced by get_submap().
load()
void map_memory::load (const tripoint_abs_ms & pos)
Load memorized submaps around given global map square pos.
Definition at line 414 of file map_memory.cpp.
 {
     const coord_pair p( pos );
     const tripoint_abs_sm start = p.sm - tripoint_rel_sm( MM_SIZE / 2, MM_SIZE / 2, 0 );
     dbg( D_INFO ) << "[LOAD] Loading memory map around " << p.sm << ". Loading submaps within " << start
                   << "->" << start + tripoint( MM_SIZE, MM_SIZE, 0 );
     clear_cache();
     for( int dy = 0; dy < MM_SIZE; dy++ ) {
         for( int dx = 0; dx < MM_SIZE; dx++ ) {
             fetch_submap( start + tripoint_rel_sm( dx, dy, 0 ) );
         }
     }
     dbg( D_INFO ) << "[LOAD] Done.";
 }
References clear_cache(), D_INFO, dbg, fetch_submap(), MM_SIZE, math_opers::pos(), map_memory::coord_pair::sm, and tripoint.
load_submap()
shared_ptr_fast< mm_submap > map_memory::load_submap (const tripoint_abs_sm & sm_pos) private
Load submap from disk.
Returns
nullptr if failed.
Definition at line 343 of file map_memory.cpp.
 {
     if( test_mode ) {
         return nullptr;
     }
     const reg_coord_pair p( sm_pos );
     const cata_path path = find_region_path( find_mm_dir(), p.reg );
     mm_region mmr;
     const auto loader = [&mmr]( const JsonValue & jsin ) {
         mmr.deserialize( jsin );
     };
     try {
         if( !read_from_file_optional_json( path, loader ) ) {
             // Region not found
             return nullptr;
         }
     } catch( const std::exception &err ) {
         debugmsg( "Failed to load memory map region (%d,%d,%d): %s",
                   p.reg.x, p.reg.y, p.reg.z, err.what() );
         return nullptr;
     }
     dbg( D_INFO ) << "Loaded mm_region " << p.reg << " [" << mmr_to_sm_copy( p.reg ) << "]";
     shared_ptr_fast<mm_submap> ret;
     for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
         for( size_t x = 0; x < MM_REG_SIZE; x++ ) {
             const tripoint_abs_sm pos( mmr_to_sm_copy( p.reg ) + tripoint( x, y, 0 ) );
             shared_ptr_fast<mm_submap> &sm = mmr.submaps[x][y];
             if( pos == sm_pos ) {
                 ret = sm;
             }
             submaps.emplace( pos, sm );
         }
     }
     return ret;
 }
References D_INFO, dbg, debugmsg, mm_region::deserialize(), find_mm_dir(), find_region_path(), MM_REG_SIZE, mmr_to_sm_copy(), math_opers::pos(), read_from_file_optional_json(), reg_coord_pair::reg, cata::hash64_detail::ret, coords::sm, mm_region::submaps, submaps, test_mode, tripoint::x, tripoint::y, and tripoint::z.
Referenced by fetch_submap().
prepare_region()
bool map_memory::prepare_region (const tripoint_abs_ms & p1, const tripoint_abs_ms & p2)
Prepares map memory for rendering and/or memorization of given region.
Parameters
p1 top-left corner of the region, in global ms coords
p2 bottom-right corner of the region, in global ms coords Both coords are inclusive and should be on the same Z level.
Returns
whether the region was re-cached
Definition at line 257 of file map_memory.cpp.
 {
     cata_assert( p1.z() == p2.z() );
     cata_assert( p1.x() <= p2.x() && p1.y() <= p2.y() );
     tripoint_abs_sm sm_p1 = coord_pair( p1 ).sm + point_north_west;
     tripoint_abs_sm sm_p2 = coord_pair( p2 ).sm + point_south_east;
     tripoint_abs_sm sm_pos = sm_p1;
     point_rel_sm sm_size = sm_p2.xy() - sm_p1.xy();
     if( sm_pos.z() == cache_pos.z() ) {
         inclusive_rectangle<point_abs_sm> rect(
             point_abs_sm( cache_pos.xy() ),
             point_abs_sm( cache_pos.xy() + cache_size ) );
         if( rect.contains( sm_p1.xy() ) && rect.contains( sm_p2.xy() ) ) {
             return false;
         }
     }
     dbg( D_INFO ) << "Preparing memory map for area: pos: " << sm_pos << " size: " << sm_size;
     cache_pos = sm_pos;
     cache_size = sm_size.raw();
     cached.clear();
     // Loop through each z-level in vision range
     for( int z = std::max( sm_pos.z() - fov_3d_z_range, -OVERMAP_DEPTH );
          z <= std::min( sm_pos.z() + fov_3d_z_range, OVERMAP_HEIGHT ); z++ ) {
         cached[z].reserve( static_cast<std::size_t>( cache_size.x ) * cache_size.y );
         for( int dy = 0; dy < cache_size.y; dy++ ) {
             for( int dx = 0; dx < cache_size.x; dx++ ) {
                 // Store submap pointer in cache, categorized by z-level
                 const tripoint_abs_sm smpos( cache_pos.x() + dx, cache_pos.y() + dy, z );
                 cached[z].push_back( fetch_submap( smpos ) );
             }
         }
     }
     return true;
 }
References cache_pos, cache_size, cached, cata_assert, inclusive_rectangle< Point, >::contains(), D_INFO, dbg, fetch_submap(), fov_3d_z_range, max(), min(), OVERMAP_DEPTH, OVERMAP_HEIGHT, point_north_west, point_south_east, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), map_memory::coord_pair::sm, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), point::x, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), point::y, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
save()
bool map_memory::save (const tripoint_abs_ms & pos)
Save memorized submaps to disk, drop ones far from given global map square pos.
Definition at line 429 of file map_memory.cpp.
 {
     const tripoint_abs_sm sm_center = coord_pair( pos ).sm;
     const cata_path dirname = find_mm_dir();
     assure_dir_exist( dirname );
     clear_cache();
     dbg( D_INFO ) << "N submaps before save: " << submaps.size();
     // Since mm_submaps are always allocated in regions,
     // we are certain that each region will be filled.
     std::map<tripoint, mm_region> regions;
     for( auto &it : submaps ) {
         const reg_coord_pair p( it.first );
         regions[p.reg].submaps[p.sm_loc.x][p.sm_loc.y] = it.second;
     }
     submaps.clear();
     constexpr point MM_HSIZE_P = point( MM_SIZE / 2, MM_SIZE / 2 );
     rectangle<point_abs_sm> rect_keep( sm_center.xy() - MM_HSIZE_P, sm_center.xy() + MM_HSIZE_P );
     dbg( D_INFO ) << "[SAVE] Saving memory map around " << sm_center << ". Keeping submaps within " <<
                   rect_keep.p_min << "->" << rect_keep.p_max;
     bool result = true;
     for( auto &it : regions ) {
         const tripoint &regp = it.first;
         mm_region &reg = it.second;
         if( !reg.is_empty() ) {
             const cata_path path = find_region_path( dirname, regp );
             const std::string descr = string_format(
                                           _( "memory map region for (%d,%d,%d)" ),
                                           regp.x, regp.y, regp.z
                                       );
             const auto writer = [&]( std::ostream & fout ) -> void {
                 fout << serialize_wrapper( [&]( JsonOut & jsout )
                 {
                     reg.serialize( jsout );
                 } );
             };
             const bool res = write_to_file( path, writer, descr.c_str() );
             result = result & res;
         }
         const tripoint_abs_sm regp_sm( mmr_to_sm_copy( regp ) );
         const half_open_rectangle<point_abs_sm> rect_reg(
             regp_sm.xy(),
             regp_sm.xy() + point( MM_REG_SIZE, MM_REG_SIZE ) );
         if( rect_reg.overlaps( rect_keep ) ) {
             dbg( D_INFO ) << "Keeping mm_region " << regp << " [" << regp_sm << "]";
             // Put submaps back
             for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
                 for( size_t x = 0; x < MM_REG_SIZE; x++ ) {
                     const tripoint_abs_sm p = regp_sm + tripoint( x, y, 0 );
                     shared_ptr_fast<mm_submap> &sm = reg.submaps[x][y];
                     submaps.insert( std::make_pair( p, sm ) );
                 }
             }
         } else {
             dbg( D_INFO ) << "Dropping mm_region " << regp << " [" << regp_sm << "]";
         }
     }
     dbg( D_INFO ) << "[SAVE] Done.";
     dbg( D_INFO ) << "N submaps after save: " << submaps.size();
     return result;
 }
References _, assure_dir_exist(), clear_cache(), D_INFO, dbg, find_mm_dir(), find_region_path(), mm_region::is_empty(), MM_REG_SIZE, MM_SIZE, mmr_to_sm_copy(), half_open_rectangle< Point, >::overlaps(), rectangle< Point, >::p_max, rectangle< Point, >::p_min, point, math_opers::pos(), reg_coord_pair::reg, mm_region::serialize(), serialize_wrapper(), coords::sm, map_memory::coord_pair::sm, reg_coord_pair::sm_loc, string_format(), mm_region::submaps, submaps, tripoint, write_to_file(), point::x, tripoint::x, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), point::y, tripoint::y, and tripoint::z.
set_tile_decoration()
void map_memory::set_tile_decoration (const tripoint_abs_ms & pos, std::string_view id, int subtile, int rotation)
Memorizes decoraiton at pos, overwriting old decoration values.
Parameters
pos tile position, in global ms coords.
Definition at line 213 of file map_memory.cpp.
 {
     const coord_pair p( pos );
     mm_submap &sm = get_submap( p.sm );
     if( !sm.is_valid() ) {
         return;
     }
     memorized_tile mt = sm.get_tile( p.loc );
     mt.set_dec_id( id );
     mt.set_dec_subtile( subtile );
     mt.set_dec_rotation( rotation );
     sm.set_tile( p.loc, mt );
 }
References get_submap(), map_memory::coord_pair::loc, math_opers::pos(), memorized_tile::set_dec_id(), memorized_tile::set_dec_rotation(), memorized_tile::set_dec_subtile(), coords::sm, and map_memory::coord_pair::sm.
set_tile_symbol()
void map_memory::set_tile_symbol (const tripoint_abs_ms & pos, char32_t symbol)
Memorizes symbol at pos, overwriting old symbol.
Parameters
pos tile position, in global ms coords.
Definition at line 228 of file map_memory.cpp.
 {
     const coord_pair p( pos );
     mm_submap &sm = get_submap( p.sm );
     if( !sm.is_valid() ) {
         return;
     }
     memorized_tile mt = sm.get_tile( p.loc );
     mt.symbol = symbol;
     sm.set_tile( p.loc, mt );
 }
References get_submap(), map_memory::coord_pair::loc, math_opers::pos(), coords::sm, map_memory::coord_pair::sm, symbol(), and memorized_tile::symbol.
set_tile_terrain()
void map_memory::set_tile_terrain (const tripoint_abs_ms & pos, std::string_view id, int subtile, int rotation)
Memorizes terrain at pos, overwriting old terrain values.
Parameters
pos tile position, in global ms coords.
Definition at line 198 of file map_memory.cpp.
 {
     const coord_pair p( pos );
     mm_submap &sm = get_submap( p.sm );
     if( !sm.is_valid() ) {
         return;
     }
     memorized_tile mt = sm.get_tile( p.loc );
     mt.set_ter_id( id );
     mt.set_ter_subtile( subtile );
     mt.set_ter_rotation( rotation );
     sm.set_tile( p.loc, mt );
 }
References get_submap(), map_memory::coord_pair::loc, math_opers::pos(), memorized_tile::set_ter_id(), memorized_tile::set_ter_rotation(), memorized_tile::set_ter_subtile(), coords::sm, and map_memory::coord_pair::sm.
Member Data Documentation
cache_pos
tripoint_abs_sm map_memory::cache_pos private
Definition at line 170 of file map_memory.h.
Referenced by clear_cache(), get_submap(), is_valid(), and prepare_region().
cache_size
point map_memory::cache_size private
Definition at line 171 of file map_memory.h.
Referenced by clear_cache(), get_submap(), and prepare_region().
cached
std::map<int, std::vector<shared_ptr_fast<mm_submap> > > map_memory::cached mutable private
Definition at line 169 of file map_memory.h.
Referenced by clear_cache(), get_submap(), and prepare_region().
submaps
std::map<tripoint_abs_sm, shared_ptr_fast<mm_submap> > map_memory::submaps private
Definition at line 167 of file map_memory.h.
Referenced by allocate_submap(), find_submap(), load_submap(), and save().
The documentation for this class was generated from the following files:
src/map_memory.h
src/map_memory.cpp