Cataclysm DDA: emit Class Reference
emit Class Reference
#include <emit.h>
Public Member Functions
emit ()
const emit_id & id () const
bool is_null () const
When null field is always fd_null.
bool is_valid () const
When valid field is never fd_null.
field_type_id field (dialogue &d) const
Type of field to emit.
int intensity (dialogue &d) const
Intensity of output fields, range [1..maximum_intensity].
int qty (dialogue &d) const
Units of field to generate per turn subject to chance.
int chance (dialogue &d) const
Chance to emit each turn, range [1..100].
Static Public Member Functions
static void load_emit (const JsonObject &jo)
Load emission data from JSON definition.
static const std::map< emit_id, emit > & all ()
Get all currently loaded emission data.
static void finalize ()
Check consistency of all loaded emission data.
static void check_consistency ()
Check consistency of all loaded emission data.
static void reset ()
Clear all loaded emission data (invalidating any pointers)
Private Attributes
emit_id id_
str_or_var field_
dbl_or_var intensity_
dbl_or_var qty_
dbl_or_var chance_
Detailed Description
Definition at line 14 of file emit.h.
Constructor & Destructor Documentation
emit()
emit::emit ()
Definition at line 37 of file emit.cpp.
 : id_( emit_id::NULL_ID() ) {}
Member Function Documentation
all()
const std::map< emit_id, emit > & emit::all () static
Get all currently loaded emission data.
Definition at line 57 of file emit.cpp.
 {
     return emits_all;
 }
References emits_all.
chance()
int emit::chance (dialogue & d) const inline
Chance to emit each turn, range [1..100].
Definition at line 45 of file emit.h.
{
             return chance_.evaluate( d );
         }
References chance_, and dbl_or_var::evaluate().
Referenced by map::emit_field().
check_consistency()
void emit::check_consistency () static
Check consistency of all loaded emission data.
Definition at line 66 of file emit.cpp.
 {
 }
Referenced by DynamicDataLoader::check_consistency().
field()
field_type_id emit::field (dialogue & d) const inline
Type of field to emit.
See also
emit::is_valid
Definition at line 30 of file emit.h.
{
             return field_type_id( field_.evaluate( d ) );
         }
References abstract_str_or_var< T >::evaluate(), field_, and field_type_id.
Referenced by map::emit_field().
finalize()
void emit::finalize () static
Check consistency of all loaded emission data.
Definition at line 62 of file emit.cpp.
 {
 }
Referenced by DynamicDataLoader::finalize_loaded_data().
id()
const emit_id& emit::id () const inline
Definition at line 19 of file emit.h.
{
             return id_;
         }
References id_.
intensity()
int emit::intensity (dialogue & d) const inline
Intensity of output fields, range [1..maximum_intensity].
Definition at line 35 of file emit.h.
{
             return intensity_.evaluate( d );
         }
References dbl_or_var::evaluate(), and intensity_.
Referenced by map::emit_field().
is_null()
bool emit::is_null () const
When null field is always fd_null.
Definition at line 39 of file emit.cpp.
 {
     return id_ == emit_id::NULL_ID();
 }
References id_, and string_id< emit >::NULL_ID().
is_valid()
bool emit::is_valid () const
When valid field is never fd_null.
load_emit()
void emit::load_emit (const JsonObject & jo) static
Load emission data from JSON definition.
Definition at line 44 of file emit.cpp.
 {
     emit et;
     et.id_ = emit_id( jo.get_string( "id" ) );
     et.field_ = get_str_or_var( jo.get_member( "field" ), "field" );
     et.intensity_ = get_dbl_or_var( jo, "intensity", false, 1.0 );
     et.qty_ = get_dbl_or_var( jo, "qty", false, 1.0 );
     et.chance_ = get_dbl_or_var( jo, "chance", false, 100.0 );
     emits_all[ et.id_ ] = et;
 }
References chance_, emits_all, field_, get_dbl_or_var(), JsonObject::get_member(), get_str_or_var(), JsonObject::get_string(), id_, intensity_, and qty_.
Referenced by DynamicDataLoader::initialize().
qty()
int emit::qty (dialogue & d) const inline
Units of field to generate per turn subject to chance.
Definition at line 40 of file emit.h.
{
             return qty_.evaluate( d );
         }
References dbl_or_var::evaluate(), and qty_.
Referenced by map::emit_field().
reset()
void emit::reset () static
Clear all loaded emission data (invalidating any pointers)
Definition at line 70 of file emit.cpp.
 {
     emits_all.clear();
 }
References emits_all.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
chance_
dbl_or_var emit::chance_ private
Definition at line 69 of file emit.h.
Referenced by chance(), and load_emit().
field_
str_or_var emit::field_ private
Definition at line 66 of file emit.h.
Referenced by field(), and load_emit().
id_
emit_id emit::id_ private
Definition at line 65 of file emit.h.
Referenced by id(), is_null(), and load_emit().
intensity_
dbl_or_var emit::intensity_ private
Definition at line 67 of file emit.h.
Referenced by intensity(), and load_emit().
qty_
dbl_or_var emit::qty_ private
Definition at line 68 of file emit.h.
Referenced by load_emit(), and qty().
The documentation for this class was generated from the following files:
src/emit.h
src/emit.cpp