Cataclysm DDA: test_data Class Reference
test_data Class Reference
#include <test_data.h>
Static Public Member Functions
static void load (const JsonObject &jo)
Static Public Attributes
static std::set< itype_id > known_bad
static std::unordered_set< oter_type_id > overmap_terrain_coverage_whitelist
static std::map< vproto_id, std::vector< double > > drag_data
static std::map< vproto_id, efficiency_data > eff_data
static std::map< itype_id, double > expected_dps
static std::map< spawn_type, std::vector< container_spawn_test_data > > container_spawn_data
static std::map< std::string, pocket_mod_test_data > pocket_mod_data
static std::map< std::string, npc_boarding_test_data > npc_boarding_data
static std::vector< bash_test_set > bash_tests
static std::map< std::string, item_demographic_test_data > item_demographics
Detailed Description
Definition at line 100 of file test_data.h.
Member Function Documentation
load()
void test_data::load (const JsonObject & jo) static
Definition at line 110 of file test_data.cpp.
 {
     // It's probably not necessary, but these are set up to
     // extend existing data instead of overwrite it.
     if( jo.has_array( "known_bad" ) ) {
         std::set<itype_id> new_known_bad;
         jo.read( "known_bad", new_known_bad );
         known_bad.insert( new_known_bad.begin(), new_known_bad.end() );
     }
     if( jo.has_array( "overmap_terrain_coverage_whitelist" ) ) {
         std::unordered_set<oter_type_str_id> new_overmap_terrain_coverage_whitelist;
         jo.read( "overmap_terrain_coverage_whitelist", new_overmap_terrain_coverage_whitelist );
         for( const oter_type_str_id &o : new_overmap_terrain_coverage_whitelist ) {
             overmap_terrain_coverage_whitelist.insert( o.id() );
         }
     }
     if( jo.has_object( "drag_data" ) ) {
         std::map<vproto_id, std::vector<double>> new_drag_data;
         jo.read( "drag_data", new_drag_data );
         drag_data.insert( new_drag_data.begin(), new_drag_data.end() );
     }
     if( jo.has_object( "efficiency_data" ) ) {
         std::map<vproto_id, efficiency_data> new_efficiency_data;
         jo.read( "efficiency_data", new_efficiency_data );
         eff_data.insert( new_efficiency_data.begin(), new_efficiency_data.end() );
     }
     if( jo.has_object( "expected_dps" ) ) {
         std::map<itype_id, double> new_expected_dps;
         jo.read( "expected_dps", new_expected_dps );
         expected_dps.insert( new_expected_dps.begin(), new_expected_dps.end() );
     }
     if( jo.has_object( "bash_test" ) ) {
         bash_test_set loaded;
         optional( jo, false, "bash_test", loaded );
         bash_tests.push_back( loaded );
     }
     if( jo.has_object( "spawn_data" ) )  {
         JsonObject spawn_jo = jo.get_object( "spawn_data" );
         if( spawn_jo.has_array( "group" ) ) {
             std::vector<container_spawn_test_data> test_groups;
             spawn_jo.read( "group", test_groups );
             container_spawn_data[spawn_type::item_group].insert(
                 container_spawn_data[spawn_type::item_group].end(), test_groups.begin(), test_groups.end() );
         }
         if( spawn_jo.has_array( "recipe" ) ) {
             std::vector<container_spawn_test_data> test_recipes;
             spawn_jo.read( "recipe", test_recipes );
             container_spawn_data[spawn_type::recipe].insert( container_spawn_data[spawn_type::recipe].end(),
                     test_recipes.begin(), test_recipes.end() );
         }
         if( spawn_jo.has_array( "vehicle" ) ) {
             std::vector<container_spawn_test_data> test_vehicles;
             spawn_jo.read( "vehicle", test_vehicles );
             container_spawn_data[spawn_type::vehicle].insert( container_spawn_data[spawn_type::vehicle].end(),
                     test_vehicles.begin(), test_vehicles.end() );
         }
         if( spawn_jo.has_array( "profession" ) ) {
             std::vector<container_spawn_test_data> test_professions;
             spawn_jo.read( "profession", test_professions );
             container_spawn_data[spawn_type::profession].insert(
                 container_spawn_data[spawn_type::profession].end(), test_professions.begin(),
                 test_professions.end() );
         }
         if( spawn_jo.has_array( "map" ) ) {
             std::vector<container_spawn_test_data> test_map;
             spawn_jo.read( "map", test_map );
             container_spawn_data[spawn_type::map].insert( container_spawn_data[spawn_type::map].end(),
                     test_map.begin(), test_map.end() );
         }
     }
     if( jo.has_object( "pocket_mod_data" ) ) {
         std::map<std::string, pocket_mod_test_data> new_pocket_mod_data;
         jo.read( "pocket_mod_data", new_pocket_mod_data );
         pocket_mod_data.insert( new_pocket_mod_data.begin(), new_pocket_mod_data.end() );
     }
     if( jo.has_object( "npc_boarding_data" ) ) {
         std::map<std::string, npc_boarding_test_data> new_boarding_data;
         jo.read( "npc_boarding_data", new_boarding_data );
         npc_boarding_data.insert( new_boarding_data.begin(), new_boarding_data.end() );
     }
     if( jo.has_object( "item_demographics" ) ) {
         item_demographic_test_data data;
         std::string category;
         const JsonObject demo_obj = jo.get_object( "item_demographics" );
         demo_obj.read( "category", category );
         demo_obj.read( "tests", data.tests );
         demo_obj.read( "ignored_items", data.ignored_items );
         JsonArray demo_list = demo_obj.get_array( "items" );
         while( demo_list.has_more() ) {
             demo_list.read_next( data );
         }
         // This does not support merging, so only add one instance of each category.
         item_demographics[category] = data;
     }
 }
References bash_tests, anonymous_namespace{item_tname.cpp}::category(), container_spawn_data, drag_data, eff_data, keycode::end, expected_dps, JsonObject::get_array(), JsonObject::get_object(), JsonObject::has_array(), JsonArray::has_more(), JsonObject::has_object(), item_demographic_test_data::ignored_items, item_demographics, item_group, known_bad, map, npc_boarding_data, optional(), overmap_terrain_coverage_whitelist, pocket_mod_data, profession, JsonObject::read(), JsonArray::read_next(), recipe, item_demographic_test_data::tests, and vehicle.
Referenced by DynamicDataLoader::initialize().
Member Data Documentation
bash_tests
std::vector< bash_test_set > test_data::bash_tests static
Definition at line 112 of file test_data.h.
Referenced by load().
container_spawn_data
std::map< spawn_type, std::vector< container_spawn_test_data > > test_data::container_spawn_data static
Definition at line 109 of file test_data.h.
Referenced by load().
drag_data
std::map< vproto_id, std::vector< double > > test_data::drag_data static
Definition at line 106 of file test_data.h.
Referenced by load().
eff_data
std::map< vproto_id, efficiency_data > test_data::eff_data static
Definition at line 107 of file test_data.h.
Referenced by load().
expected_dps
std::map< itype_id, double > test_data::expected_dps static
Definition at line 108 of file test_data.h.
Referenced by load().
item_demographics
std::map< std::string, item_demographic_test_data > test_data::item_demographics static
Definition at line 113 of file test_data.h.
Referenced by load().
known_bad
std::set< itype_id > test_data::known_bad static
Definition at line 104 of file test_data.h.
Referenced by load().
npc_boarding_data
std::map< std::string, npc_boarding_test_data > test_data::npc_boarding_data static
Definition at line 111 of file test_data.h.
Referenced by load().
overmap_terrain_coverage_whitelist
std::unordered_set< oter_type_id > test_data::overmap_terrain_coverage_whitelist static
Definition at line 105 of file test_data.h.
Referenced by load().
pocket_mod_data
std::map< std::string, pocket_mod_test_data > test_data::pocket_mod_data static
Definition at line 110 of file test_data.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/test_data.h
src/test_data.cpp