Cataclysm DDA: medical_column Class Reference
medical_column Class Reference
Public Member Functions
medical_column ()=default
medical_column (const int column_id, const point &COLUMN_START, const std::pair< int, int > &COLUMN_BOUNDS)
void draw_column (const catacurses::window &window, const int BORDER_START, const int BORDER_END) const
void print_column (const catacurses::window &window, const int LINE_START, const int MAX_HEIGHT)
void add_column_line (const selection_line &line)
selection_line set_highlight (int y)
int selection_count () const
int row_count () const
int max_width () const
bool empty ()
bool current_column (const int selected_id) const
std::pair< std::string, std::string > detail_str (int y)
Private Attributes
int column_id
const int left_padding = 2
std::pair< int, int > COLUMN_ROWS = { 0, 0 }
std::pair< int, int > COLUMN_BOUNDS
point COLUMN_START
std::vector< selection_line > column_lines
std::string column_title
Detailed Description
Definition at line 101 of file medical_ui.cpp.
Constructor & Destructor Documentation
medical_column() [1/2]
medical_column::medical_column () default
medical_column() [2/2]
medical_column::medical_column (const int column_id, const point & COLUMN_START, const std::pair< int, int > & COLUMN_BOUNDS) inline
Definition at line 105 of file medical_ui.cpp.
             : column_id( column_id ), COLUMN_BOUNDS( COLUMN_BOUNDS ), COLUMN_START( COLUMN_START ) {}
Member Function Documentation
add_column_line()
void medical_column::add_column_line (const selection_line & line) inline
Definition at line 145 of file medical_ui.cpp.
{
             column_lines.emplace_back( line );
             COLUMN_ROWS.second += line.get_row_count();
         }
References column_lines, COLUMN_ROWS, and line.
Referenced by draw_effects_summary(), draw_health_summary(), and draw_stats_summary().
current_column()
bool medical_column::current_column (const int selected_id) const inline
Definition at line 172 of file medical_ui.cpp.
{
             return column_id == selected_id;
         }
References column_id.
Referenced by avatar::disp_medical().
detail_str()
std::pair<std::string, std::string> medical_column::detail_str (int y) inline
Definition at line 176 of file medical_ui.cpp.
{
             std::pair<std::string, std::string> ret;
             if( y < static_cast<int>( column_lines.size() ) ) {
                 int offset = y % column_lines.size();
                 ret = column_lines[offset].get_detail();
             }
             return ret;
         }
References column_lines, and cata::hash64_detail::ret.
Referenced by avatar::disp_medical().
draw_column()
void medical_column::draw_column (const catacurses::window & window, const int BORDER_START, const int BORDER_END) const inline
Definition at line 109 of file medical_ui.cpp.
{
             mvwvline( window, point( COLUMN_START.x, BORDER_START ), LINE_XOXO,
                       BORDER_END - 4 ); // |
             mvwputch( window, point( COLUMN_START.x, BORDER_END - 1 ), BORDER_COLOR,
                       LINE_XXOX ); // _|_
         }
References BORDER_COLOR, COLUMN_START, LINE_XOXO, LINE_XXOX, mvwputch(), catacurses::mvwvline(), point, and point::x.
Referenced by avatar::disp_medical().
empty()
bool medical_column::empty () inline
Definition at line 168 of file medical_ui.cpp.
                      {
             return column_lines.empty();
         }
References column_lines.
Referenced by draw_effects_summary().
max_width()
int medical_column::max_width () const inline
Definition at line 164 of file medical_ui.cpp.
{
             return COLUMN_BOUNDS.first - COLUMN_START.x - left_padding;
         }
References COLUMN_BOUNDS, COLUMN_START, left_padding, and point::x.
Referenced by draw_effects_summary(), draw_health_summary(), draw_stats_summary(), and print_column().
print_column()
void medical_column::print_column (const catacurses::window & window, const int LINE_START, const int MAX_HEIGHT) inline
Definition at line 117 of file medical_ui.cpp.
{
             int linerow = 0;
             int selectionrow = 0;
             for( selection_line &line : column_lines ) {
                 const point row_start(
                     line.highlighted() ?
                     COLUMN_START.x + left_padding - 1 :
                     COLUMN_START.x + left_padding,
                     COLUMN_START.y + linerow
                 );
                 if( row_start.y - LINE_START >= MAX_HEIGHT ) {
                     break;
                 }
                 if( linerow >= LINE_START ) {
                     fold_and_print( window, row_start - point( 0, LINE_START ), max_width(),
                                     c_light_gray, line.print() );
                     linerow += line.get_row_count();
                 } else {
                     linerow++;
                 }
                 ++selectionrow;
             }
             COLUMN_ROWS = { selectionrow, linerow };
         }
References c_light_gray, column_lines, COLUMN_ROWS, COLUMN_START, fold_and_print(), left_padding, line, max_width(), point, point::x, and point::y.
Referenced by avatar::disp_medical().
row_count()
int medical_column::row_count () const inline
Definition at line 160 of file medical_ui.cpp.
{
             return COLUMN_ROWS.second;
         }
References COLUMN_ROWS.
selection_count()
int medical_column::selection_count () const inline
Definition at line 156 of file medical_ui.cpp.
{
             return COLUMN_ROWS.first;
         }
References COLUMN_ROWS.
Referenced by avatar::disp_medical().
set_highlight()
selection_line medical_column::set_highlight (int y) inline
Definition at line 150 of file medical_ui.cpp.
{
             int offset = y % column_lines.size();
             column_lines[offset].set_highlight();
             return column_lines[offset];
         }
References column_lines.
Referenced by avatar::disp_medical().
Member Data Documentation
COLUMN_BOUNDS
std::pair<int, int> medical_column::COLUMN_BOUNDS private
Definition at line 189 of file medical_ui.cpp.
Referenced by max_width().
column_id
int medical_column::column_id private
Definition at line 186 of file medical_ui.cpp.
Referenced by current_column().
column_lines
std::vector<selection_line> medical_column::column_lines private
Definition at line 191 of file medical_ui.cpp.
Referenced by add_column_line(), detail_str(), empty(), print_column(), and set_highlight().
COLUMN_ROWS
std::pair<int, int> medical_column::COLUMN_ROWS = { 0, 0 } private
Definition at line 188 of file medical_ui.cpp.
Referenced by add_column_line(), print_column(), row_count(), and selection_count().
COLUMN_START
point medical_column::COLUMN_START private
Definition at line 190 of file medical_ui.cpp.
Referenced by draw_column(), max_width(), and print_column().
column_title
std::string medical_column::column_title private
Definition at line 192 of file medical_ui.cpp.
left_padding
const int medical_column::left_padding = 2 private
Definition at line 187 of file medical_ui.cpp.
Referenced by max_width(), and print_column().
The documentation for this class was generated from the following file:
src/medical_ui.cpp