Cataclysm DDA: disassemble_activity_actor Class Reference
disassemble_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
disassemble_activity_actor (int moves_total)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &act, Character &who) override
Called just before Character::cancel_activity() executes.
float exertion_level () const override
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Public Attributes
item_location target
Private Attributes
int moves_total
float activity_override = NO_EXERCISE
float cached_workbench_multiplier
bool use_cached_workbench_multiplier
Detailed Description
Definition at line 1253 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
disassemble_activity_actor()
disassemble_activity_actor::disassemble_activity_actor (int moves_total) inline explicit
Definition at line 1263 of file activity_actor_definitions.h.
                                                                :
             moves_total( moves_total ) {}
Referenced by deserialize().
Member Function Documentation
canceled()
void disassemble_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 5234 of file activity_actor.cpp.
 {
     if( target.get_item() ) {
         target->erase_var( "activity_var" );
     }
 }
References item::erase_var(), item_location::get_item(), and target.
clone()
std::unique_ptr<activity_actor> disassemble_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1278 of file activity_actor_definitions.h.
{
             return std::make_unique<disassemble_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > disassemble_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 5266 of file activity_actor.cpp.
 {
     disassemble_activity_actor actor = disassemble_activity_actor( 0 );
     JsonObject data = jsin.get_object();
     data.read( "target", actor.target );
     data.read( "moves_total", actor.moves_total );
     data.read( "activity_override", actor.activity_override );
     return actor.clone();
 }
References activity_override, clone(), disassemble_activity_actor(), JsonValue::get_object(), moves_total, JsonObject::read(), and target.
do_turn()
void disassemble_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 5191 of file activity_actor.cpp.
 {
     if( !check_if_disassemble_okay( target, who ) ) {
         act.set_to_null();
         return;
     }
     // We already checked if this is nullptr above
     item &craft = *target;
     const std::optional<tripoint> location = target.where() == item_location::type::character
             ? std::optional<tripoint>() : std::optional<tripoint>( target.position() );
     if( !use_cached_workbench_multiplier ) {
         cached_workbench_multiplier = who.workbench_crafting_speed_multiplier( craft, location );
         use_cached_workbench_multiplier = true;
     }
     const float crafting_speed = who.crafting_speed_multiplier( craft, location,
                                  use_cached_workbench_multiplier, cached_workbench_multiplier );
     if( crafting_speed <= 0.0f ) {
         who.cancel_activity();
         return;
     }
     if( moves_total == 0 ) {
         craft.item_counter = 10'000'000;
     } else {
         const int spent_moves = who.get_moves() * who.exertion_adjusted_move_multiplier( exertion_level() );
         craft.item_counter += std::round( spent_moves * crafting_speed * 10'000'000.0 / moves_total );
         craft.item_counter = std::min( craft.item_counter, 10'000'000 );
         who.set_moves( 0 );
     }
     if( craft.item_counter >= 10'000'000 ) {
         who.complete_disassemble( target );
     }
 }
References act, cached_workbench_multiplier, Character::cancel_activity(), item_location::character, check_if_disassemble_okay(), Character::complete_disassemble(), anonymous_namespace{item_tname.cpp}::craft(), Character::crafting_speed_multiplier(), Character::exertion_adjusted_move_multiplier(), exertion_level(), Creature::get_moves(), location, min(), moves_total, item_location::position(), round(), Creature::set_moves(), target, use_cached_workbench_multiplier, item_location::where(), and Character::workbench_crafting_speed_multiplier().
exertion_level()
float disassemble_activity_actor::exertion_level () const override virtual
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
Reimplemented from activity_actor.
Definition at line 5241 of file activity_actor.cpp.
 {
     return activity_override;
 }
References activity_override.
Referenced by do_turn().
finish()
void disassemble_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 5229 of file activity_actor.cpp.
 {
     act.set_to_null();
 }
References act.
get_progress_message()
std::string disassemble_activity_actor::get_progress_message (const player_activity & act) const override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 5246 of file activity_actor.cpp.
 {
     if( !target ) {
         // We have somehow lost the disassembly item.  This will be handled in do_turn in the check_if_disassemble_okay call.
         return "";
     }
     return target->tname();
 }
References target, and item::tname().
get_type()
activity_id disassemble_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1265 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_DISASSEMBLE" );
         }
References activity_id.
serialize()
void disassemble_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 5255 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves_total", moves_total );
     jsout.member( "target", target );
     jsout.member( "activity_override", activity_override );
     jsout.end_object();
 }
References activity_override, JsonOut::end_object(), JsonOut::member(), moves_total, JsonOut::start_object(), and target.
start()
void disassemble_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 5165 of file activity_actor.cpp.
 {
     if( act.targets.empty() ) {
         act.set_to_null();
         return;
     }
     if( act.targets.back()->typeId() == itype_disassembly ) {
         act.position = act.targets.back()->get_making_batch_size();
     }
     target = who.create_in_progress_disassembly( act.targets.back() );
     act.targets.pop_back();
     if( !check_if_disassemble_okay( target, who ) ) {
         act.set_to_null();
         return;
     }
     // Mark the item, not available for other characters
     target->set_var( "activity_var", who.name );
     activity_override = target->get_making().exertion_level();
     cached_workbench_multiplier = 0;
     use_cached_workbench_multiplier = false;
 }
References act, activity_override, cached_workbench_multiplier, check_if_disassemble_okay(), Character::create_in_progress_disassembly(), recipe::exertion_level(), item::get_making(), itype_disassembly, Character::name, item::set_var(), target, and use_cached_workbench_multiplier.
Member Data Documentation
activity_override
float disassemble_activity_actor::activity_override = NO_EXERCISE private
Definition at line 1257 of file activity_actor_definitions.h.
Referenced by deserialize(), exertion_level(), serialize(), and start().
cached_workbench_multiplier
float disassemble_activity_actor::cached_workbench_multiplier private
Definition at line 1258 of file activity_actor_definitions.h.
Referenced by do_turn(), and start().
moves_total
int disassemble_activity_actor::moves_total private
Definition at line 1256 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
target
item_location disassemble_activity_actor::target
Definition at line 1261 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), do_turn(), get_progress_message(), serialize(), and start().
use_cached_workbench_multiplier
bool disassemble_activity_actor::use_cached_workbench_multiplier private
Definition at line 1259 of file activity_actor_definitions.h.
Referenced by do_turn(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp