Cataclysm DDA: talker Class Reference
talker Class Reference
#include <talker.h>
Public Member Functions
virtual ~talker ()=default
virtual std::unique_ptr< talker > clone () const
virtual Character * get_character ()
virtual const Character * get_character () const
virtual npc * get_npc ()
virtual npc * get_npc () const
virtual item_location * get_item ()
virtual item_location * get_item () const
virtual monster * get_monster ()
virtual const monster * get_monster () const
virtual Creature * get_creature ()
virtual const Creature * get_creature () const
virtual computer * get_computer ()
virtual const computer * get_computer () const
virtual std::string disp_name () const
virtual std::string get_name () const
virtual character_id getID () const
virtual bool is_male () const
virtual std::vector< std::string > get_grammatical_genders () const
virtual int posx () const
virtual int posy () const
virtual int posz () const
virtual tripoint pos () const
virtual tripoint_abs_ms global_pos () const
virtual tripoint_abs_omt global_omt_location () const
virtual void set_pos (tripoint)
virtual std::string distance_to_goal () const
virtual bool will_talk_to_u (const Character &, bool)
virtual std::vector< std::string > get_topics (bool)
virtual void check_missions ()
virtual void update_missions (const std::vector< mission * > &)
virtual bool check_hostile_response (int) const
virtual int parse_mod (const std::string &, int) const
virtual int trial_chance_mod (const std::string &) const
virtual int get_cur_hp (const bodypart_id &) const
virtual int get_hp_max (const bodypart_id &) const
virtual int get_count () const
virtual units::temperature get_cur_part_temp (const bodypart_id &) const
virtual bool get_is_alive () const
virtual int str_cur () const
virtual int dex_cur () const
virtual int int_cur () const
virtual int per_cur () const
virtual void set_str_max (int)
virtual void set_dex_max (int)
virtual void set_int_max (int)
virtual void set_per_max (int)
virtual void set_str_bonus (int)
virtual void set_dex_bonus (int)
virtual void set_int_bonus (int)
virtual void set_per_bonus (int)
virtual int get_str_max () const
virtual int get_dex_max () const
virtual int get_int_max () const
virtual int get_per_max () const
virtual int get_str_bonus () const
virtual int get_dex_bonus () const
virtual int get_int_bonus () const
virtual int get_per_bonus () const
virtual int get_skill_level (const skill_id &) const
virtual int get_skill_exp (const skill_id &, bool) const
virtual int get_spell_level (const trait_id &) const
virtual int get_spell_level (const spell_id &) const
virtual int get_spell_exp (const spell_id &) const
virtual int get_highest_spell_level () const
virtual int get_spell_count (const trait_id &) const
virtual int get_spell_sum (const trait_id &, int) const
virtual void set_spell_level (const spell_id &, int)
virtual void set_spell_exp (const spell_id &, int)
virtual void set_skill_level (const skill_id &, int)
virtual void set_skill_exp (const skill_id &, int, bool)
virtual bool has_trait (const trait_id &) const
virtual bool has_recipe (const recipe_id &) const
virtual void learn_recipe (const recipe_id &)
virtual void forget_recipe (const recipe_id &)
virtual void mutate (const int &, const bool &)
virtual void mutate_category (const mutation_category_id &, const bool &)
virtual void mutate_towards (const trait_id &, const mutation_category_id &, const bool &)
virtual void set_mutation (const trait_id &, const mutation_variant *=nullptr)
virtual void unset_mutation (const trait_id &)
virtual void activate_mutation (const trait_id &)
virtual void deactivate_mutation (const trait_id &)
virtual void set_sleepiness (int)
virtual bool has_flag (const json_character_flag &) const
virtual bool has_species (const species_id &) const
virtual bool bodytype (const bodytype_id &) const
virtual int get_grab_strength () const
virtual bool crossed_threshold () const
virtual int num_bionics () const
virtual bool has_max_power () const
virtual bool has_bionic (const bionic_id &) const
virtual bool knows_spell (const spell_id &) const
virtual bool knows_proficiency (const proficiency_id &) const
virtual time_duration proficiency_practiced_time (const proficiency_id &) const
virtual void set_proficiency_practiced_time (const proficiency_id &, int)
virtual void train_proficiency_for (const proficiency_id &, int)
virtual std::vector< skill_id > skills_offered_to (const talker &) const
virtual std::vector< skill_id > skills_teacheable () const
virtual std::string skill_seminar_text (const skill_id &) const
virtual std::string skill_training_text (const talker &, const skill_id &) const
virtual std::vector< proficiency_id > proficiencies_teacheable () const
virtual std::vector< proficiency_id > proficiencies_offered_to (const talker &) const
virtual std::string proficiency_seminar_text (const proficiency_id &) const
virtual std::string proficiency_training_text (const talker &, const proficiency_id &) const
virtual std::vector< matype_id > styles_teacheable () const
virtual std::vector< matype_id > styles_offered_to (const talker &) const
virtual std::string style_seminar_text (const matype_id &) const
virtual std::string style_training_text (const talker &, const matype_id &) const
virtual std::vector< spell_id > spells_teacheable () const
virtual std::vector< spell_id > spells_offered_to (talker &) const
virtual std::string spell_seminar_text (const spell_id &) const
virtual std::string spell_training_text (talker &, const spell_id &) const
virtual void store_chosen_training (const skill_id &, const matype_id &, const spell_id &, const proficiency_id &)
virtual bool has_effect (const efftype_id &, const bodypart_id &) const
virtual effect get_effect (const efftype_id &, const bodypart_id &) const
virtual bool is_deaf () const
virtual bool can_see () const
virtual bool can_see_location (const tripoint &) const
virtual bool is_mute () const
virtual void add_effect (const efftype_id &, const time_duration &, const std::string &, bool, bool, int)
virtual void remove_effect (const efftype_id &, const std::string &)
virtual void add_bionic (const bionic_id &)
virtual void remove_bionic (const bionic_id &)
virtual std::string get_value (const std::string &key) const
virtual std::optional< std::string > maybe_get_value (const std::string &) const
virtual void set_value (const std::string &, const std::string &)
virtual void remove_value (const std::string &)
virtual bool is_wearing (const itype_id &) const
virtual int charges_of (const itype_id &) const
virtual bool has_charges (const itype_id &, int) const
virtual bool has_charges (const itype_id &, int, bool) const
virtual std::list< item > use_charges (const itype_id &, int)
virtual std::list< item > use_charges (const itype_id &, int, bool)
virtual bool has_amount (const itype_id &, int) const
virtual int get_amount (const itype_id &) const
virtual std::list< item > use_amount (const itype_id &, int)
virtual int value (const item &) const
virtual int cash () const
virtual int debt () const
virtual void add_debt (int)
virtual int sold () const
virtual void add_sold (int)
virtual std::vector< item * > items_with (const std::function< bool(const item &)> &) const
virtual std::vector< const item * > const_items_with (const std::function< bool(const item &)> &) const
virtual void i_add (const item &)
virtual void i_add_or_drop (item &, bool=false)
virtual void remove_items_with (const std::function< bool(const item &)> &)
virtual bool unarmed_attack () const
virtual bool can_stash_weapon () const
virtual bool has_stolen_item (const talker &) const
virtual int cash_to_favor (int) const
virtual std::string give_item_to (bool)
virtual bool buy_from (int)
virtual bool buy_monster (talker &, const mtype_id &, int, int, bool, const translation &)
virtual std::vector< mission * > available_missions () const
virtual std::vector< mission * > assigned_missions () const
virtual mission * selected_mission () const
virtual void select_mission (mission *)
virtual void add_mission (const mission_type_id &)
virtual void set_companion_mission (const std::string &)
virtual faction * get_faction () const
virtual void set_fac (const faction_id &)
virtual void add_faction_rep (int)
virtual bool is_following () const
virtual bool is_friendly (const Character &) const
virtual bool is_player_ally () const
virtual bool turned_hostile () const
virtual bool is_enemy () const
virtual void make_angry ()
virtual bool has_ai_rule (const std::string &, const std::string &) const
virtual void toggle_ai_rule (const std::string &, const std::string &)
virtual void set_ai_rule (const std::string &, const std::string &)
virtual void clear_ai_rule (const std::string &, const std::string &)
virtual std::string get_job_description () const
virtual std::string evaluation_by (const talker &) const
virtual std::string view_personality_traits () const
virtual std::string short_description () const
virtual bool has_activity () const
virtual bool is_mounted () const
virtual bool is_myclass (const npc_class_id &) const
virtual void set_class (const npc_class_id &)
virtual int get_activity_level () const
virtual int get_sleepiness () const
virtual int get_hunger () const
virtual int get_thirst () const
virtual int get_instant_thirst () const
virtual int get_stored_kcal () const
virtual int get_healthy_kcal () const
virtual int get_size () const
virtual int get_stim () const
virtual int get_addiction_intensity (const addiction_id &) const
virtual int get_addiction_turns (const addiction_id &) const
virtual void set_addiction_turns (const addiction_id &, int)
virtual void set_stored_kcal (int)
virtual void set_stim (int)
virtual void set_thirst (int)
virtual bool is_in_control_of (const vehicle &) const
virtual void say (const std::string &)
virtual void shout (const std::string &="", bool=false)
virtual bool enslave_mind ()
virtual std::string opinion_text () const
virtual void add_opinion (const npc_opinion &)
virtual void set_first_topic (const std::string &)
virtual bool is_safe () const
virtual void mod_pain (int)
virtual void set_pain (int)
virtual int pain_cur () const
virtual int perceived_pain_cur () const
virtual void attack_target (Creature &, bool, const matec_id &, bool, int)
virtual int attack_speed () const
virtual double armor_at (damage_type_id &, bodypart_id &) const
virtual int coverage_at (bodypart_id &) const
virtual int encumbrance_at (bodypart_id &) const
virtual bool worn_with_flag (const flag_id &, const bodypart_id &) const
virtual bool wielded_with_flag (const flag_id &) const
virtual bool wielded_with_weapon_category (const weapon_category_id &) const
virtual bool has_item_with_flag (const flag_id &) const
virtual int item_rads (const flag_id &, aggregate_type) const
virtual units::energy power_cur () const
virtual units::energy power_max () const
virtual void set_power_cur (units::energy)
virtual int mana_cur () const
virtual int mana_max () const
virtual void set_mana_cur (int)
virtual void mod_daily_health (int, int)
virtual int morale_cur () const
virtual int focus_cur () const
virtual void mod_focus (int)
virtual int get_pkill () const
virtual void set_pkill (int)
virtual int get_stamina () const
virtual void set_stamina (int)
virtual int get_sleep_deprivation () const
virtual void set_sleep_deprivation (int)
virtual int get_rad () const
virtual void set_rad (int)
virtual int get_anger () const
virtual void set_anger (int)
virtual void set_morale (int)
virtual int get_friendly () const
virtual void set_friendly (int)
virtual void add_morale (const morale_type &, int, int, time_duration, time_duration, bool)
virtual void remove_morale (const morale_type &)
virtual void set_kill_xp (int)
virtual int get_kill_xp () const
virtual void set_age (int)
virtual int get_age () const
virtual void set_height (int)
virtual int get_height () const
virtual int get_volume () const
virtual int get_weight () const
virtual void set_npc_trust (int)
virtual int get_npc_trust () const
virtual void set_npc_fear (int)
virtual int get_npc_fear () const
virtual void set_npc_value (int)
virtual int get_npc_value () const
virtual void set_npc_anger (int)
virtual int get_npc_anger () const
virtual int get_bmi_permil () const
virtual const move_mode_id & get_move_mode () const
virtual int get_fine_detail_vision_mod () const
virtual int get_health () const
virtual units::temperature get_body_temp () const
virtual units::temperature_delta get_body_temp_delta () const
virtual std::vector< bodypart_id > get_all_body_parts (get_body_part_flags) const
virtual int get_part_hp_cur (const bodypart_id &) const
virtual int get_part_hp_max (const bodypart_id &) const
virtual void set_all_parts_hp_cur (int) const
virtual void set_part_hp_cur (const bodypart_id &, int) const
virtual void die ()
virtual matec_id get_random_technique (Creature &, bool, bool, bool, const std::vector< matec_id > &={}) const
virtual void learn_martial_art (const matype_id &) const
virtual void forget_martial_art (const matype_id &) const
virtual bool knows_martial_art (const matype_id &) const
virtual bool using_martial_art (const matype_id &) const
virtual int climate_control_str_heat () const
virtual int climate_control_str_chill () const
Detailed Description
Definition at line 35 of file talker.h.
Constructor & Destructor Documentation
~talker()
virtual talker::~talker () virtual default
Member Function Documentation
activate_mutation()
virtual void talker::activate_mutation (const trait_id &) inline virtual
Reimplemented in talker_character.
Definition at line 238 of file talker.h.
 {}
add_bionic()
virtual void talker::add_bionic (const bionic_id &) inline virtual
Reimplemented in talker_character.
Definition at line 350 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder().
add_debt()
virtual void talker::add_debt (int) inline virtual
Reimplemented in talker_npc.
Definition at line 400 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_debt(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), and conditional_t::get_set_dbl().
add_effect()
virtual void talker::add_effect (const efftype_id & , const time_duration & , const std::string & , bool , bool , int) inline virtual
Reimplemented in talker_monster, and talker_character.
Definition at line 347 of file talker.h.
                                        {}
add_faction_rep()
virtual void talker::add_faction_rep (int) inline virtual
Reimplemented in talker_npc.
Definition at line 458 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_change_faction_rep().
add_mission()
virtual void talker::add_mission (const mission_type_id &) inline virtual
Reimplemented in talker_npc.
Definition at line 450 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_mission().
add_morale()
virtual void talker::add_morale (const morale_type & , int , int , time_duration , time_duration , bool) inline virtual
Reimplemented in talker_character.
Definition at line 649 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale().
add_opinion()
virtual void talker::add_opinion (const npc_opinion &) inline virtual
Reimplemented in talker_npc.
Definition at line 559 of file talker.h.
 {}
Referenced by talk_effect_t::apply().
add_sold()
virtual void talker::add_sold (int) inline virtual
Reimplemented in talker_npc.
Definition at line 404 of file talker.h.
 {}
Referenced by conditional_t::get_set_dbl().
armor_at()
virtual double talker::armor_at (damage_type_id & , bodypart_id &) const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 578 of file talker.h.
{
             return 0;
         }
assigned_missions()
virtual std::vector<mission *> talker::assigned_missions () const inline virtual
Reimplemented in talker_npc.
Definition at line 442 of file talker.h.
{
             return {};
         }
Referenced by talk_effect_t::update_missions().
attack_speed()
virtual int talker::attack_speed () const inline virtual
Reimplemented in talker_character_const.
Definition at line 575 of file talker.h.
{
             return 0;
         }
attack_target()
virtual void talker::attack_target (Creature & , bool , const matec_id & , bool , int) inline virtual
Reimplemented in talker_character.
Definition at line 572 of file talker.h.
                                                 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack().
available_missions()
virtual std::vector<mission *> talker::available_missions () const inline virtual
Reimplemented in talker_npc.
Definition at line 439 of file talker.h.
{
             return {};
         }
bodytype()
virtual bool talker::bodytype (const bodytype_id &) const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 247 of file talker.h.
{
             return false;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_bodytype().
buy_from()
virtual bool talker::buy_from (int) inline virtual
Reimplemented in talker_npc.
Definition at line 430 of file talker.h.
{
             return false;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_spend_cash().
buy_monster()
virtual bool talker::buy_monster (talker & , const mtype_id & , int , int , bool , const translation &) inline virtual
Reimplemented in talker_avatar.
Definition at line 433 of file talker.h.
{
             return false;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster().
can_see()
virtual bool talker::can_see () const inline virtual
Reimplemented in talker_character_const.
Definition at line 338 of file talker.h.
{
             return false;
         }
Referenced by talker_npc::evaluation_by().
can_see_location()
virtual bool talker::can_see_location (const tripoint &) const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 341 of file talker.h.
{
             return false;
         }
can_stash_weapon()
virtual bool talker::can_stash_weapon () const inline virtual
Reimplemented in talker_character_const.
Definition at line 418 of file talker.h.
{
             return false;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_can_stow_weapon().
cash()
virtual int talker::cash () const inline virtual
Reimplemented in talker_character_const.
Definition at line 394 of file talker.h.
{
             return 0;
         }
cash_to_favor()
virtual int talker::cash_to_favor (int) const inline virtual
Reimplemented in talker_npc.
Definition at line 424 of file talker.h.
{
             return 0;
         }
Referenced by talk_effect_t::apply().
charges_of()
virtual int talker::charges_of (const itype_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 365 of file talker.h.
{
             return 0;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item(), json_talk_topic::gen_responses(), and total_price().
check_hostile_response()
virtual bool talker::check_hostile_response (int) const inline virtual
Reimplemented in talker_npc.
Definition at line 127 of file talker.h.
{
             return false;
         }
Referenced by talk_effect_t::get_consequence().
check_missions()
virtual void talker::check_missions () inline virtual
Reimplemented in talker_npc.
Definition at line 125 of file talker.h.
 {}
clear_ai_rule()
virtual void talker::clear_ai_rule (const std::string & , const std::string &) inline virtual
Reimplemented in talker_npc.
Definition at line 482 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_clear_npc_rule().
climate_control_str_chill()
virtual int talker::climate_control_str_chill () const inline virtual
Reimplemented in talker_character_const.
Definition at line 730 of file talker.h.
{
             return 0;
         }
climate_control_str_heat()
virtual int talker::climate_control_str_heat () const inline virtual
Reimplemented in talker_character_const.
Definition at line 727 of file talker.h.
{
             return 0;
         }
clone()
virtual std::unique_ptr<talker> talker::clone () const inline virtual
Reimplemented in talker_cloner< T, B >, talker_cloner< talker_character, talker_character_const >, talker_cloner< talker_monster, talker_monster_const >, talker_cloner< talker_item, talker_item_const >, talker_cloner< talker_furniture >, talker_cloner< talker_character_const >, talker_cloner< talker_item_const >, talker_cloner< talker_topic >, talker_cloner< talker_npc, talker_character >, talker_cloner< talker_avatar, talker_character >, and talker_cloner< talker_monster_const >.
Definition at line 39 of file talker.h.
{
             return std::make_unique<talker>();
         }
Referenced by dialogue::dialogue(), and run_item_eocs().
const_items_with()
virtual std::vector<const item *> talker::const_items_with (const std::function< bool(const item &)> &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 408 of file talker.h.
               {
             return {};
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_category(), and total_price().
coverage_at()
virtual int talker::coverage_at (bodypart_id &) const inline virtual
Reimplemented in talker_item_const, and talker_character_const.
Definition at line 581 of file talker.h.
{
             return 0;
         }
crossed_threshold()
virtual bool talker::crossed_threshold () const inline virtual
Reimplemented in talker_character_const.
Definition at line 253 of file talker.h.
{
             return false;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_flag(), and anonymous_namespace{math_parser_diag.cpp}::has_flag_eval().
deactivate_mutation()
virtual void talker::deactivate_mutation (const trait_id &) inline virtual
Reimplemented in talker_character.
Definition at line 239 of file talker.h.
 {}
debt()
virtual int talker::debt () const inline virtual
Reimplemented in talker_npc.
Definition at line 397 of file talker.h.
{
             return 0;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), and conditional_t::get_set_dbl().
dex_cur()
virtual int talker::dex_cur () const inline virtual
Reimplemented in talker_character_const.
Definition at line 156 of file talker.h.
{
             return 0;
         }
die()
virtual void talker::die () inline virtual
Reimplemented in talker_npc, talker_monster, talker_item, and talker_character.
Definition at line 714 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_die().
disp_name()
virtual std::string talker::disp_name () const inline virtual
Reimplemented in talker_topic, talker_monster_const, talker_item_const, talker_furniture, and talker_character_const.
Definition at line 80 of file talker.h.
{
             return "";
         }
Referenced by talker_avatar::buy_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item().
distance_to_goal()
virtual std::string talker::distance_to_goal () const inline virtual
Reimplemented in talker_npc.
Definition at line 114 of file talker.h.
{
             return "";
         }
Referenced by dialogue::dynamic_line().
encumbrance_at()
virtual int talker::encumbrance_at (bodypart_id &) const inline virtual
Reimplemented in talker_item_const, and talker_character_const.
Definition at line 584 of file talker.h.
{
             return 0;
         }
enslave_mind()
virtual bool talker::enslave_mind () inline virtual
Reimplemented in talker_npc.
Definition at line 553 of file talker.h.
{
             return false;
         }
evaluation_by()
virtual std::string talker::evaluation_by (const talker &) const inline virtual
Reimplemented in talker_npc.
Definition at line 488 of file talker.h.
{
             return "";
         }
Referenced by dialogue::dynamic_line().
focus_cur()
virtual int talker::focus_cur () const inline virtual
Reimplemented in talker_character_const.
Definition at line 620 of file talker.h.
{
             return 0;
         }
Referenced by conditional_t::get_set_dbl().
forget_martial_art()
virtual void talker::forget_martial_art (const matype_id &) const inline virtual
Reimplemented in talker_character.
Definition at line 720 of file talker.h.
 {}
forget_recipe()
virtual void talker::forget_recipe (const recipe_id &) inline virtual
Reimplemented in talker_character.
Definition at line 232 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_recipe().
get_activity_level()
virtual int talker::get_activity_level () const inline virtual
Reimplemented in talker_character_const.
Definition at line 507 of file talker.h.
{
             return 0;
         }
get_addiction_intensity()
virtual int talker::get_addiction_intensity (const addiction_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 534 of file talker.h.
{
             return 0;
         }
get_addiction_turns()
virtual int talker::get_addiction_turns (const addiction_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 537 of file talker.h.
{
             return 0;
         }
get_age()
virtual int talker::get_age () const inline virtual
Reimplemented in talker_character_const.
Definition at line 656 of file talker.h.
{
             return 0;
         }
get_all_body_parts()
virtual std::vector<bodypart_id> talker::get_all_body_parts (get_body_part_flags) const inline virtual
Reimplemented in talker_character.
Definition at line 703 of file talker.h.
{
             return std::vector<bodypart_id>();
         }
get_amount()
virtual int talker::get_amount (const itype_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 385 of file talker.h.
{
             return 0;
         }
get_anger()
virtual int talker::get_anger () const inline virtual
Reimplemented in talker_monster_const.
Definition at line 640 of file talker.h.
{
             return 0;
         }
get_bmi_permil()
virtual int talker::get_bmi_permil () const inline virtual
Reimplemented in talker_character_const.
Definition at line 685 of file talker.h.
{
             return 0;
         }
get_body_temp()
virtual units::temperature talker::get_body_temp () const inline virtual
Reimplemented in talker_character_const.
Definition at line 697 of file talker.h.
{
             return 0_K;
         }
get_body_temp_delta()
virtual units::temperature_delta talker::get_body_temp_delta () const inline virtual
Reimplemented in talker_character_const.
Definition at line 700 of file talker.h.
{
             return 0_C_delta;
         }
get_character() [1/2]
virtual Character* talker::get_character () inline virtual
Reimplemented in talker_character, and talker_character_const.
Definition at line 43 of file talker.h.
{
             return nullptr;
         }
Referenced by anonymous_namespace{math_parser_diag.cpp}::_characters_nearby_eval(), talk_response::create_option_line(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_wet(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_activity(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_visible_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_prevent_death(), conditional_fun::anonymous_namespace{condition.cpp}::f_query(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_turn_cost(), talker_character_const::has_stolen_item(), parse_tags(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::process_eoc(), talker_character_const::proficiencies_offered_to(), talker_character_const::proficiency_training_text(), talk_trial::roll(), run_item_eocs(), talker_character_const::skill_training_text(), talker_character_const::skills_offered_to(), talker_character_const::spell_training_text(), talker_character_const::spells_offered_to(), talker_character_const::style_training_text(), and talker_character_const::styles_offered_to().
get_character() [2/2]
virtual const Character* talker::get_character () const inline virtual
Reimplemented in talker_character, and talker_character_const.
Definition at line 46 of file talker.h.
{
             return nullptr;
         }
get_computer() [1/2]
virtual computer* talker::get_computer () inline virtual
Reimplemented in talker_furniture.
Definition at line 73 of file talker.h.
{
             return nullptr;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue().
get_computer() [2/2]
virtual const computer* talker::get_computer () const inline virtual
Reimplemented in talker_furniture.
Definition at line 76 of file talker.h.
{
             return nullptr;
         }
get_count()
virtual int talker::get_count () const inline virtual
Reimplemented in talker_item_const.
Definition at line 142 of file talker.h.
{
             return 0;
         }
get_creature() [1/2]
virtual Creature* talker::get_creature () inline virtual
Reimplemented in talker_monster, talker_character, and talker_character_const.
Definition at line 67 of file talker.h.
{
             return nullptr;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_outside(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport().
get_creature() [2/2]
virtual const Creature* talker::get_creature () const inline virtual
Reimplemented in talker_monster, talker_character, and talker_character_const.
Definition at line 70 of file talker.h.
{
             return nullptr;
         }
get_cur_hp()
virtual int talker::get_cur_hp (const bodypart_id &) const inline virtual
Reimplemented in talker_character_const, talker_monster_const, and talker_item_const.
Definition at line 136 of file talker.h.
{
             return 0;
         }
get_cur_part_temp()
virtual units::temperature talker::get_cur_part_temp (const bodypart_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 145 of file talker.h.
{
             return 0_K;
         }
get_dex_bonus()
virtual int talker::get_dex_bonus () const inline virtual
Reimplemented in talker_character_const.
Definition at line 188 of file talker.h.
{
             return 0;
         }
get_dex_max()
virtual int talker::get_dex_max () const inline virtual
Reimplemented in talker_character_const.
Definition at line 176 of file talker.h.
{
             return 0;
         }
get_effect()
virtual effect talker::get_effect (const efftype_id & , const bodypart_id &) const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 332 of file talker.h.
{
             return effect::null_effect;
         }
References effect::null_effect.
get_faction()
virtual faction* talker::get_faction () const inline virtual
Reimplemented in talker_character_const.
Definition at line 454 of file talker.h.
{
             return nullptr;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_faction_trust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_faction_trust(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item().
get_fine_detail_vision_mod()
virtual int talker::get_fine_detail_vision_mod () const inline virtual
Reimplemented in talker_character_const.
Definition at line 691 of file talker.h.
{
             return 0;
         }
get_friendly()
virtual int talker::get_friendly () const inline virtual
Reimplemented in talker_monster_const.
Definition at line 645 of file talker.h.
{
             return 0;
         }
get_grab_strength()
virtual int talker::get_grab_strength () const inline virtual
Reimplemented in talker_monster_const.
Definition at line 250 of file talker.h.
{
             return 0;
         }
get_grammatical_genders()
virtual std::vector<std::string> talker::get_grammatical_genders () const inline virtual
Reimplemented in talker_character_const.
Definition at line 92 of file talker.h.
{
             return {};
         }
Referenced by translate_gendered_line().
get_health()
virtual int talker::get_health () const inline virtual
Reimplemented in talker_character_const.
Definition at line 694 of file talker.h.
{
             return 0;
         }
get_healthy_kcal()
virtual int talker::get_healthy_kcal () const inline virtual
Reimplemented in talker_character_const.
Definition at line 525 of file talker.h.
{
             return 0;
         }
get_height()
virtual int talker::get_height () const inline virtual
Reimplemented in talker_character_const.
Definition at line 660 of file talker.h.
{
             return 0;
         }
get_highest_spell_level()
virtual int talker::get_highest_spell_level () const inline virtual
Reimplemented in talker_character_const.
Definition at line 212 of file talker.h.
{
             return 0;
         }
get_hp_max()
virtual int talker::get_hp_max (const bodypart_id &) const inline virtual
Reimplemented in talker_character_const, talker_monster_const, and talker_item_const.
Definition at line 139 of file talker.h.
{
             return 0;
         }
get_hunger()
virtual int talker::get_hunger () const inline virtual
Reimplemented in talker_character_const.
Definition at line 513 of file talker.h.
{
             return 0;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_need().
get_instant_thirst()
virtual int talker::get_instant_thirst () const inline virtual
Reimplemented in talker_character_const.
Definition at line 519 of file talker.h.
{
             return 0;
         }
get_int_bonus()
virtual int talker::get_int_bonus () const inline virtual
Reimplemented in talker_character_const.
Definition at line 191 of file talker.h.
{
             return 0;
         }
get_int_max()
virtual int talker::get_int_max () const inline virtual
Reimplemented in talker_character_const.
Definition at line 179 of file talker.h.
{
             return 0;
         }
get_is_alive()
virtual bool talker::get_is_alive () const inline virtual
Reimplemented in talker_monster, and talker_character.
Definition at line 148 of file talker.h.
{
             return false;
         }
get_item() [1/2]
virtual item_location* talker::get_item () inline virtual
Reimplemented in talker_item.
Definition at line 55 of file talker.h.
{
             return nullptr;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_item(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_unset_flag().
get_item() [2/2]
virtual item_location* talker::get_item () const inline virtual
Reimplemented in talker_item.
Definition at line 58 of file talker.h.
{
             return nullptr;
         }
get_job_description()
virtual std::string talker::get_job_description () const inline virtual
Reimplemented in talker_npc.
Definition at line 485 of file talker.h.
{
             return "";
         }
Referenced by dialogue::dynamic_line().
get_kill_xp()
virtual int talker::get_kill_xp () const inline virtual
Reimplemented in talker_character_const.
Definition at line 652 of file talker.h.
{
             return 0;
         }
get_monster() [1/2]
virtual monster* talker::get_monster () inline virtual
Reimplemented in talker_monster.
Definition at line 61 of file talker.h.
{
             return nullptr;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue().
get_monster() [2/2]
virtual const monster* talker::get_monster () const inline virtual
Reimplemented in talker_monster.
Definition at line 64 of file talker.h.
{
             return nullptr;
         }
get_move_mode()
virtual const move_mode_id& talker::get_move_mode () const inline virtual
Reimplemented in talker_character_const.
Definition at line 688 of file talker.h.
{
             return move_mode_id::NULL_ID();
         }
References string_id< move_mode >::NULL_ID().
get_name()
virtual std::string talker::get_name () const inline virtual
Reimplemented in talker_monster_const, talker_item_const, and talker_character_const.
Definition at line 83 of file talker.h.
{
             return "";
         }
Referenced by parse_tags().
get_npc() [1/2]
virtual npc* talker::get_npc () inline virtual
Reimplemented in talker_npc.
Definition at line 49 of file talker.h.
{
             return nullptr;
         }
Referenced by dialogue::add_topic(), talker_avatar::buy_monster(), talk_response::create_option_line(), dialogue::dynamic_line(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_guard_pos(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_wants_to_talk(), and dialogue::opt().
get_npc() [2/2]
virtual npc* talker::get_npc () const inline virtual
Reimplemented in talker_npc.
Definition at line 52 of file talker.h.
{
             return nullptr;
         }
get_npc_anger()
virtual int talker::get_npc_anger () const inline virtual
Reimplemented in talker_npc.
Definition at line 682 of file talker.h.
{
             return 0;
         }
get_npc_fear()
virtual int talker::get_npc_fear () const inline virtual
Reimplemented in talker_npc.
Definition at line 674 of file talker.h.
{
             return 0;
         }
get_npc_trust()
virtual int talker::get_npc_trust () const inline virtual
Reimplemented in talker_npc.
Definition at line 670 of file talker.h.
{
             return 0;
         }
get_npc_value()
virtual int talker::get_npc_value () const inline virtual
Reimplemented in talker_npc.
Definition at line 678 of file talker.h.
{
             return 0;
         }
get_part_hp_cur()
virtual int talker::get_part_hp_cur (const bodypart_id &) const inline virtual
Reimplemented in talker_character.
Definition at line 706 of file talker.h.
{
             return 0;
         }
get_part_hp_max()
virtual int talker::get_part_hp_max (const bodypart_id &) const inline virtual
Reimplemented in talker_character.
Definition at line 709 of file talker.h.
{
             return 0;
         }
get_per_bonus()
virtual int talker::get_per_bonus () const inline virtual
Reimplemented in talker_character_const.
Definition at line 194 of file talker.h.
{
             return 0;
         }
get_per_max()
virtual int talker::get_per_max () const inline virtual
Reimplemented in talker_character_const.
Definition at line 182 of file talker.h.
{
             return 0;
         }
get_pkill()
virtual int talker::get_pkill () const inline virtual
Reimplemented in talker_character_const.
Definition at line 624 of file talker.h.
{
             return 0;
         }
get_rad()
virtual int talker::get_rad () const inline virtual
Reimplemented in talker_character_const.
Definition at line 636 of file talker.h.
{
             return 0;
         }
get_random_technique()
virtual matec_id talker::get_random_technique (Creature & , bool , bool , bool , const std::vector< matec_id > & = {}) const inline virtual
Reimplemented in talker_character.
Definition at line 715 of file talker.h.
                                                                                    {} ) const {
             return matec_id();
         }
get_size()
virtual int talker::get_size () const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 528 of file talker.h.
{
             return 0;
         }
get_skill_exp()
virtual int talker::get_skill_exp (const skill_id & , bool) const inline virtual
Reimplemented in talker_character_const.
Definition at line 200 of file talker.h.
{
             return 0;
         }
get_skill_level()
virtual int talker::get_skill_level (const skill_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 197 of file talker.h.
{
             return 0;
         }
Referenced by talk_trial::calc_chance(), and talk_response::create_option_line().
get_sleep_deprivation()
virtual int talker::get_sleep_deprivation () const inline virtual
Reimplemented in talker_character_const.
Definition at line 632 of file talker.h.
{
             return 0;
         }
get_sleepiness()
virtual int talker::get_sleepiness () const inline virtual
Reimplemented in talker_character_const.
Definition at line 510 of file talker.h.
{
             return 0;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_need().
get_spell_count()
virtual int talker::get_spell_count (const trait_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 215 of file talker.h.
{
             return 0;
         }
get_spell_exp()
virtual int talker::get_spell_exp (const spell_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 209 of file talker.h.
{
             return 0;
         }
get_spell_level() [1/2]
virtual int talker::get_spell_level (const spell_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 206 of file talker.h.
{
             return 0;
         }
get_spell_level() [2/2]
virtual int talker::get_spell_level (const trait_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 203 of file talker.h.
{
             return 0;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder().
get_spell_sum()
virtual int talker::get_spell_sum (const trait_id & , int) const inline virtual
Reimplemented in talker_character_const.
Definition at line 218 of file talker.h.
{
             return 0;
         }
get_stamina()
virtual int talker::get_stamina () const inline virtual
Reimplemented in talker_character_const.
Definition at line 628 of file talker.h.
{
             return 0;
         }
get_stim()
virtual int talker::get_stim () const inline virtual
Reimplemented in talker_character_const.
Definition at line 531 of file talker.h.
{
             return 0;
         }
get_stored_kcal()
virtual int talker::get_stored_kcal () const inline virtual
Reimplemented in talker_character_const.
Definition at line 522 of file talker.h.
{
             return 0;
         }
get_str_bonus()
virtual int talker::get_str_bonus () const inline virtual
Reimplemented in talker_character_const.
Definition at line 185 of file talker.h.
{
             return 0;
         }
get_str_max()
virtual int talker::get_str_max () const inline virtual
Reimplemented in talker_character_const.
Definition at line 173 of file talker.h.
{
             return 0;
         }
get_thirst()
virtual int talker::get_thirst () const inline virtual
Reimplemented in talker_character_const.
Definition at line 516 of file talker.h.
{
             return 0;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_need().
get_topics()
virtual std::vector<std::string> talker::get_topics (bool) inline virtual
Reimplemented in talker_avatar, talker_topic, talker_npc, talker_monster_const, talker_item_const, and talker_furniture.
Definition at line 122 of file talker.h.
{
             return {};
         }
get_value()
virtual std::string talker::get_value (const std::string & key) const inline virtual
Definition at line 352 of file talker.h.
{
             return maybe_get_value( key ).value_or( std::string{} );
         }
References maybe_get_value().
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), and parse_tags().
get_volume()
virtual int talker::get_volume () const inline virtual
Reimplemented in talker_monster_const, and talker_item_const.
Definition at line 663 of file talker.h.
{
             return 0;
         }
get_weight()
virtual int talker::get_weight () const inline virtual
Reimplemented in talker_monster_const, talker_item_const, and talker_character_const.
Definition at line 666 of file talker.h.
{
             return 0;
         }
getID()
virtual character_id talker::getID () const inline virtual
Reimplemented in talker_character_const.
Definition at line 86 of file talker.h.
{
             return character_id( 0 );
         }
References character_id.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_talker(), and talk_effect_t::update_missions().
give_item_to()
virtual std::string talker::give_item_to (bool) inline virtual
Reimplemented in talker_npc.
Definition at line 427 of file talker.h.
{
             return _( "Nope." );
         }
References _.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_gets_item().
global_omt_location()
virtual tripoint_abs_omt talker::global_omt_location () const inline virtual
Reimplemented in talker_topic, talker_monster_const, talker_item_const, talker_furniture, and talker_character_const.
Definition at line 110 of file talker.h.
{
             return {};
         }
global_pos()
virtual tripoint_abs_ms talker::global_pos () const inline virtual
Reimplemented in talker_topic, talker_monster_const, talker_item_const, talker_furniture, and talker_character_const.
Definition at line 107 of file talker.h.
{
             return {};
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius().
has_activity()
virtual bool talker::has_activity () const inline virtual
Reimplemented in talker_npc, and talker_character_const.
Definition at line 497 of file talker.h.
{
             return false;
         }
has_ai_rule()
virtual bool talker::has_ai_rule (const std::string & , const std::string &) const inline virtual
Reimplemented in talker_npc.
Definition at line 477 of file talker.h.
{
             return false;
         }
has_amount()
virtual bool talker::has_amount (const itype_id & , int) const inline virtual
Reimplemented in talker_character_const.
Definition at line 382 of file talker.h.
{
             return false;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_items(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), and json_talk_topic::gen_responses().
has_bionic()
virtual bool talker::has_bionic (const bionic_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 262 of file talker.h.
{
             return false;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_bionics(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder().
has_charges() [1/2]
virtual bool talker::has_charges (const itype_id & , int) const inline virtual
Reimplemented in talker_character_const.
Definition at line 368 of file talker.h.
{
             return false;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_items(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item().
has_charges() [2/2]
virtual bool talker::has_charges (const itype_id & , int , bool) const inline virtual
Reimplemented in talker_character_const.
Definition at line 372 of file talker.h.
{
             return false;
         }
has_effect()
virtual bool talker::has_effect (const efftype_id & , const bodypart_id &) const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 329 of file talker.h.
{
             return false;
         }
has_flag()
virtual bool talker::has_flag (const json_character_flag &) const inline virtual
Reimplemented in talker_character_const, talker_monster_const, and talker_item_const.
Definition at line 241 of file talker.h.
{
             return false;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_flag(), and anonymous_namespace{math_parser_diag.cpp}::has_flag_eval().
has_item_with_flag()
virtual bool talker::has_item_with_flag (const flag_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 596 of file talker.h.
{
             return false;
         }
has_max_power()
virtual bool talker::has_max_power () const inline virtual
Reimplemented in talker_character_const.
Definition at line 259 of file talker.h.
{
             return false;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_bionics().
has_recipe()
virtual bool talker::has_recipe (const recipe_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 228 of file talker.h.
{
             return false;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder().
has_species()
virtual bool talker::has_species (const species_id &) const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 244 of file talker.h.
{
             return false;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_species().
has_stolen_item()
virtual bool talker::has_stolen_item (const talker &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 421 of file talker.h.
{
             return false;
         }
has_trait()
virtual bool talker::has_trait (const trait_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 225 of file talker.h.
{
             return false;
         }
Referenced by talk_trial::calc_chance(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_trait(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_visible_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), and talk_trial::roll().
i_add()
virtual void talker::i_add (const item &) inline virtual
Reimplemented in talker_character.
Definition at line 412 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item().
i_add_or_drop()
virtual void talker::i_add_or_drop (item & , bool = false) inline virtual
Reimplemented in talker_character.
Definition at line 413 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item().
int_cur()
virtual int talker::int_cur () const inline virtual
Reimplemented in talker_character_const.
Definition at line 159 of file talker.h.
{
             return 0;
         }
Referenced by talker_npc::evaluation_by().
is_deaf()
virtual bool talker::is_deaf () const inline virtual
Reimplemented in talker_character_const.
Definition at line 335 of file talker.h.
{
             return false;
         }
is_enemy()
virtual bool talker::is_enemy () const inline virtual
Reimplemented in talker_npc.
Definition at line 471 of file talker.h.
{
             return false;
         }
is_following()
virtual bool talker::is_following () const inline virtual
Reimplemented in talker_npc.
Definition at line 459 of file talker.h.
{
             return false;
         }
is_friendly()
virtual bool talker::is_friendly (const Character &) const inline virtual
Reimplemented in talker_npc.
Definition at line 462 of file talker.h.
{
             return false;
         }
is_in_control_of()
virtual bool talker::is_in_control_of (const vehicle &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 544 of file talker.h.
{
             return false;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_is_driving().
is_male()
virtual bool talker::is_male () const inline virtual
Reimplemented in talker_character_const.
Definition at line 89 of file talker.h.
{
             return false;
         }
Referenced by parse_tags().
is_mounted()
virtual bool talker::is_mounted () const inline virtual
Reimplemented in talker_character_const.
Definition at line 500 of file talker.h.
{
             return false;
         }
is_mute()
virtual bool talker::is_mute () const inline virtual
Reimplemented in talker_character_const.
Definition at line 344 of file talker.h.
{
             return false;
         }
is_myclass()
virtual bool talker::is_myclass (const npc_class_id &) const inline virtual
Reimplemented in talker_npc.
Definition at line 503 of file talker.h.
{
             return false;
         }
is_player_ally()
virtual bool talker::is_player_ally () const inline virtual
Reimplemented in talker_npc.
Definition at line 465 of file talker.h.
{
             return false;
         }
is_safe()
virtual bool talker::is_safe () const inline virtual
Reimplemented in talker_npc.
Definition at line 561 of file talker.h.
{
             return true;
         }
is_wearing()
virtual bool talker::is_wearing (const itype_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 362 of file talker.h.
{
             return false;
         }
item_rads()
virtual int talker::item_rads (const flag_id & , aggregate_type) const inline virtual
Reimplemented in talker_character_const.
Definition at line 599 of file talker.h.
{
             return 0;
         }
items_with()
virtual std::vector<item *> talker::items_with (const std::function< bool(const item &)> &) const inline virtual
Reimplemented in talker_character.
Definition at line 405 of file talker.h.
{
             return {};
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), and json_talk_topic::gen_responses().
knows_martial_art()
virtual bool talker::knows_martial_art (const matype_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 721 of file talker.h.
{
             return false;
         }
knows_proficiency()
virtual bool talker::knows_proficiency (const proficiency_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 268 of file talker.h.
{
             return false;
         }
knows_spell()
virtual bool talker::knows_spell (const spell_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 265 of file talker.h.
{
             return false;
         }
learn_martial_art()
virtual void talker::learn_martial_art (const matype_id &) const inline virtual
Reimplemented in talker_character.
Definition at line 719 of file talker.h.
 {}
learn_recipe()
virtual void talker::learn_recipe (const recipe_id &) inline virtual
Reimplemented in talker_character.
Definition at line 231 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_recipe(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder().
make_angry()
virtual void talker::make_angry () inline virtual
Reimplemented in talker_npc.
Definition at line 474 of file talker.h.
 {}
Referenced by talk_effect_t::apply().
mana_cur()
virtual int talker::mana_cur () const inline virtual
Reimplemented in talker_character_const.
Definition at line 609 of file talker.h.
{
             return 0;
         }
mana_max()
virtual int talker::mana_max () const inline virtual
Reimplemented in talker_character_const.
Definition at line 612 of file talker.h.
{
             return 0;
         }
Referenced by conditional_t::get_set_dbl().
maybe_get_value()
virtual std::optional<std::string> talker::maybe_get_value (const std::string &) const inline virtual
Reimplemented in talker_monster_const, talker_item_const, talker_furniture, and talker_character_const.
Definition at line 355 of file talker.h.
{
             return std::nullopt;
         }
Referenced by get_value(), and maybe_read_var_value().
mod_daily_health()
virtual void talker::mod_daily_health (int , int) inline virtual
Reimplemented in talker_character.
Definition at line 616 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mod_healthy().
mod_focus()
virtual void talker::mod_focus (int) inline virtual
Reimplemented in talker_character.
Definition at line 623 of file talker.h.
 {}
Referenced by conditional_t::get_set_dbl().
mod_pain()
virtual void talker::mod_pain (int) inline virtual
Reimplemented in talker_monster, and talker_character.
Definition at line 564 of file talker.h.
 {}
morale_cur()
virtual int talker::morale_cur () const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 617 of file talker.h.
{
             return 0;
         }
mutate()
virtual void talker::mutate (const int & , const bool &) inline virtual
Reimplemented in talker_character.
Definition at line 233 of file talker.h.
 {}
mutate_category()
virtual void talker::mutate_category (const mutation_category_id & , const bool &) inline virtual
Reimplemented in talker_character.
Definition at line 234 of file talker.h.
 {}
mutate_towards()
virtual void talker::mutate_towards (const trait_id & , const mutation_category_id & , const bool &) inline virtual
Reimplemented in talker_character.
Definition at line 235 of file talker.h.
 {};
num_bionics()
virtual int talker::num_bionics () const inline virtual
Reimplemented in talker_character_const.
Definition at line 256 of file talker.h.
{
             return 0;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_bionics().
opinion_text()
virtual std::string talker::opinion_text () const inline virtual
Reimplemented in talker_npc.
Definition at line 556 of file talker.h.
{
             return "";
         }
Referenced by dialogue::dynamic_line().
pain_cur()
virtual int talker::pain_cur () const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 566 of file talker.h.
{
             return 0;
         }
parse_mod()
virtual int talker::parse_mod (const std::string & , int) const inline virtual
Reimplemented in talker_npc, and talker_avatar.
Definition at line 130 of file talker.h.
{
             return 0;
         }
Referenced by parse_mod().
per_cur()
virtual int talker::per_cur () const inline virtual
Reimplemented in talker_character_const.
Definition at line 162 of file talker.h.
{
             return 0;
         }
Referenced by talker_npc::evaluation_by().
perceived_pain_cur()
virtual int talker::perceived_pain_cur () const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 569 of file talker.h.
{
             return 0;
         }
pos()
virtual tripoint talker::pos () const inline virtual
Reimplemented in talker_topic, talker_monster_const, talker_item_const, talker_furniture, and talker_character_const.
Definition at line 104 of file talker.h.
{
             return {};
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_is_driving(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), conditional_t::get_set_dbl(), and get_tripoint_from_var().
posx()
virtual int talker::posx () const inline virtual
Reimplemented in talker_topic, talker_monster_const, talker_item_const, talker_furniture, and talker_character_const.
Definition at line 95 of file talker.h.
{
             return 0;
         }
posy()
virtual int talker::posy () const inline virtual
Reimplemented in talker_topic, talker_monster_const, talker_item_const, talker_furniture, and talker_character_const.
Definition at line 98 of file talker.h.
{
             return 0;
         }
posz()
virtual int talker::posz () const inline virtual
Reimplemented in talker_topic, talker_monster_const, talker_item_const, talker_furniture, and talker_character_const.
Definition at line 101 of file talker.h.
{
             return 0;
         }
power_cur()
virtual units::energy talker::power_cur () const inline virtual
Reimplemented in talker_character_const.
Definition at line 602 of file talker.h.
{
             return 0_kJ;
         }
power_max()
virtual units::energy talker::power_max () const inline virtual
Reimplemented in talker_character_const.
Definition at line 605 of file talker.h.
{
             return 0_kJ;
         }
Referenced by conditional_t::get_set_dbl().
proficiencies_offered_to()
virtual std::vector<proficiency_id> talker::proficiencies_offered_to (const talker &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 291 of file talker.h.
{
             return {};
         }
Referenced by dialogue::gen_responses().
proficiencies_teacheable()
virtual std::vector<proficiency_id> talker::proficiencies_teacheable () const inline virtual
Reimplemented in talker_character_const.
Definition at line 288 of file talker.h.
{
             return {};
         }
Referenced by dialogue::gen_responses().
proficiency_practiced_time()
virtual time_duration talker::proficiency_practiced_time (const proficiency_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 271 of file talker.h.
{
             return 0_seconds;
         }
proficiency_seminar_text()
virtual std::string talker::proficiency_seminar_text (const proficiency_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 294 of file talker.h.
{
             return {};
         }
proficiency_training_text()
virtual std::string talker::proficiency_training_text (const talker & , const proficiency_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 297 of file talker.h.
{
             return {};
         }
remove_bionic()
virtual void talker::remove_bionic (const bionic_id &) inline virtual
Reimplemented in talker_character.
Definition at line 351 of file talker.h.
 {}
remove_effect()
virtual void talker::remove_effect (const efftype_id & , const std::string &) inline virtual
Reimplemented in talker_monster, and talker_character.
Definition at line 349 of file talker.h.
 {}
remove_items_with()
virtual void talker::remove_items_with (const std::function< bool(const item &)> &) inline virtual
Reimplemented in talker_character.
Definition at line 414 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_item_with().
remove_morale()
virtual void talker::remove_morale (const morale_type &) inline virtual
Reimplemented in talker_character.
Definition at line 650 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_morale().
remove_value()
virtual void talker::remove_value (const std::string &) inline virtual
Reimplemented in talker_monster, talker_character, talker_topic, talker_item, and talker_furniture.
Definition at line 359 of file talker.h.
 {}
say()
virtual void talker::say (const std::string &) inline virtual
Reimplemented in talker_npc.
Definition at line 549 of file talker.h.
 {}
select_mission()
virtual void talker::select_mission (mission *) inline virtual
Reimplemented in talker_npc.
Definition at line 448 of file talker.h.
{
         }
Referenced by dialogue::opt().
selected_mission()
virtual mission* talker::selected_mission () const inline virtual
Reimplemented in talker_npc.
Definition at line 445 of file talker.h.
{
             return nullptr;
         }
Referenced by talk_effect_t::apply(), dialogue::dynamic_line(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update().
set_addiction_turns()
virtual void talker::set_addiction_turns (const addiction_id & , int) inline virtual
Reimplemented in talker_character.
Definition at line 540 of file talker.h.
 {}
set_age()
virtual void talker::set_age (int) inline virtual
Reimplemented in talker_character.
Definition at line 655 of file talker.h.
 {}
set_ai_rule()
virtual void talker::set_ai_rule (const std::string & , const std::string &) inline virtual
Reimplemented in talker_npc.
Definition at line 481 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_aim_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_recharge_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_reserve_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_engagement_rule(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_npc_rule().
set_all_parts_hp_cur()
virtual void talker::set_all_parts_hp_cur (int) const inline virtual
Reimplemented in talker_monster, talker_item, and talker_character.
Definition at line 712 of file talker.h.
 {}
set_anger()
virtual void talker::set_anger (int) inline virtual
Reimplemented in talker_monster.
Definition at line 643 of file talker.h.
 {}
set_class()
virtual void talker::set_class (const npc_class_id &) inline virtual
Reimplemented in talker_npc.
Definition at line 506 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_class().
set_companion_mission()
virtual void talker::set_companion_mission (const std::string &) inline virtual
Reimplemented in talker_npc.
Definition at line 451 of file talker.h.
 {}
set_dex_bonus()
virtual void talker::set_dex_bonus (int) inline virtual
Reimplemented in talker_character.
Definition at line 170 of file talker.h.
 {}
set_dex_max()
virtual void talker::set_dex_max (int) inline virtual
Reimplemented in talker_character.
Definition at line 166 of file talker.h.
 {}
set_fac()
virtual void talker::set_fac (const faction_id &) inline virtual
Reimplemented in talker_npc.
Definition at line 457 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_faction().
set_first_topic()
virtual void talker::set_first_topic (const std::string &) inline virtual
Reimplemented in talker_npc.
Definition at line 560 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_first_topic().
set_friendly()
virtual void talker::set_friendly (int) inline virtual
Reimplemented in talker_monster.
Definition at line 648 of file talker.h.
 {}
set_height()
virtual void talker::set_height (int) inline virtual
Reimplemented in talker_character.
Definition at line 659 of file talker.h.
 {}
set_int_bonus()
virtual void talker::set_int_bonus (int) inline virtual
Reimplemented in talker_character.
Definition at line 171 of file talker.h.
 {}
set_int_max()
virtual void talker::set_int_max (int) inline virtual
Reimplemented in talker_character.
Definition at line 167 of file talker.h.
 {}
set_kill_xp()
virtual void talker::set_kill_xp (int) inline virtual
Reimplemented in talker_character.
Definition at line 651 of file talker.h.
 {}
set_mana_cur()
virtual void talker::set_mana_cur (int) inline virtual
Reimplemented in talker_character.
Definition at line 615 of file talker.h.
 {}
Referenced by conditional_t::get_set_dbl().
set_morale()
virtual void talker::set_morale (int) inline virtual
Reimplemented in talker_monster.
Definition at line 644 of file talker.h.
 {}
set_mutation()
virtual void talker::set_mutation (const trait_id & , const mutation_variant * = nullptr) inline virtual
Reimplemented in talker_character.
Definition at line 236 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder().
set_npc_anger()
virtual void talker::set_npc_anger (int) inline virtual
Reimplemented in talker_npc.
Definition at line 681 of file talker.h.
 {}
set_npc_fear()
virtual void talker::set_npc_fear (int) inline virtual
Reimplemented in talker_npc.
Definition at line 673 of file talker.h.
 {}
set_npc_trust()
virtual void talker::set_npc_trust (int) inline virtual
Reimplemented in talker_npc.
Definition at line 669 of file talker.h.
 {}
set_npc_value()
virtual void talker::set_npc_value (int) inline virtual
Reimplemented in talker_npc.
Definition at line 677 of file talker.h.
 {}
set_pain()
virtual void talker::set_pain (int) inline virtual
Reimplemented in talker_character.
Definition at line 565 of file talker.h.
 {}
set_part_hp_cur()
virtual void talker::set_part_hp_cur (const bodypart_id & , int) const inline virtual
Reimplemented in talker_character.
Definition at line 713 of file talker.h.
 {}
set_per_bonus()
virtual void talker::set_per_bonus (int) inline virtual
Reimplemented in talker_character.
Definition at line 172 of file talker.h.
 {}
set_per_max()
virtual void talker::set_per_max (int) inline virtual
Reimplemented in talker_character.
Definition at line 168 of file talker.h.
 {}
set_pkill()
virtual void talker::set_pkill (int) inline virtual
Reimplemented in talker_character.
Definition at line 627 of file talker.h.
 {}
set_pos()
virtual void talker::set_pos (tripoint) inline virtual
Reimplemented in talker_character.
Definition at line 113 of file talker.h.
 {}
Referenced by conditional_t::get_set_dbl().
set_power_cur()
virtual void talker::set_power_cur (units::energy) inline virtual
Reimplemented in talker_character.
Definition at line 608 of file talker.h.
 {}
Referenced by conditional_t::get_set_dbl().
set_proficiency_practiced_time()
virtual void talker::set_proficiency_practiced_time (const proficiency_id & , int) inline virtual
Reimplemented in talker_character.
Definition at line 274 of file talker.h.
 {}
set_rad()
virtual void talker::set_rad (int) inline virtual
Reimplemented in talker_character.
Definition at line 639 of file talker.h.
 {}
set_skill_exp()
virtual void talker::set_skill_exp (const skill_id & , int , bool) inline virtual
Reimplemented in talker_character.
Definition at line 224 of file talker.h.
 {}
set_skill_level()
virtual void talker::set_skill_level (const skill_id & , int) inline virtual
Reimplemented in talker_character.
Definition at line 223 of file talker.h.
 {}
set_sleep_deprivation()
virtual void talker::set_sleep_deprivation (int) inline virtual
Reimplemented in talker_character.
Definition at line 635 of file talker.h.
 {}
set_sleepiness()
virtual void talker::set_sleepiness (int) inline virtual
Reimplemented in talker_character.
Definition at line 240 of file talker.h.
 {};
set_spell_exp()
virtual void talker::set_spell_exp (const spell_id & , int) inline virtual
Reimplemented in talker_character.
Definition at line 222 of file talker.h.
 {}
set_spell_level()
virtual void talker::set_spell_level (const spell_id & , int) inline virtual
Reimplemented in talker_character.
Definition at line 221 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder().
set_stamina()
virtual void talker::set_stamina (int) inline virtual
Reimplemented in talker_character.
Definition at line 631 of file talker.h.
 {}
set_stim()
virtual void talker::set_stim (int) inline virtual
Reimplemented in talker_character.
Definition at line 542 of file talker.h.
 {}
set_stored_kcal()
virtual void talker::set_stored_kcal (int) inline virtual
Reimplemented in talker_character.
Definition at line 541 of file talker.h.
 {}
set_str_bonus()
virtual void talker::set_str_bonus (int) inline virtual
Reimplemented in talker_character.
Definition at line 169 of file talker.h.
 {}
set_str_max()
virtual void talker::set_str_max (int) inline virtual
Reimplemented in talker_character.
Definition at line 165 of file talker.h.
 {}
set_thirst()
virtual void talker::set_thirst (int) inline virtual
Reimplemented in talker_character.
Definition at line 543 of file talker.h.
 {}
set_value()
virtual void talker::set_value (const std::string & , const std::string &) inline virtual
Reimplemented in talker_topic, talker_monster, talker_item, talker_furniture, and talker_character.
Definition at line 358 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), json_dynamic_line_effect::json_dynamic_line_effect(), and write_var_value().
short_description()
virtual std::string talker::short_description () const inline virtual
Reimplemented in talker_monster_const, and talker_character_const.
Definition at line 494 of file talker.h.
{
             return "";
         }
Referenced by dialogue::dynamic_line().
shout()
virtual void talker::shout (const std::string & = "", bool = false) inline virtual
Reimplemented in talker_character.
Definition at line 550 of file talker.h.
 {}
Referenced by dialogue::dynamic_line().
skill_seminar_text()
virtual std::string talker::skill_seminar_text (const skill_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 282 of file talker.h.
{
             return {};
         }
skill_training_text()
virtual std::string talker::skill_training_text (const talker & , const skill_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 285 of file talker.h.
{
             return {};
         }
skills_offered_to()
virtual std::vector<skill_id> talker::skills_offered_to (const talker &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 276 of file talker.h.
{
             return {};
         }
Referenced by dialogue::gen_responses().
skills_teacheable()
virtual std::vector<skill_id> talker::skills_teacheable () const inline virtual
Reimplemented in talker_character_const.
Definition at line 279 of file talker.h.
{
             return {};
         }
Referenced by dialogue::gen_responses().
sold()
virtual int talker::sold () const inline virtual
Reimplemented in talker_npc.
Definition at line 401 of file talker.h.
{
             return 0;
         }
Referenced by conditional_t::get_set_dbl().
spell_seminar_text()
virtual std::string talker::spell_seminar_text (const spell_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 318 of file talker.h.
{
             return {};
         }
spell_training_text()
virtual std::string talker::spell_training_text (talker & , const spell_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 321 of file talker.h.
{
             return {};
         }
spells_offered_to()
virtual std::vector<spell_id> talker::spells_offered_to (talker &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 315 of file talker.h.
{
             return {};
         }
Referenced by dialogue::gen_responses().
spells_teacheable()
virtual std::vector<spell_id> talker::spells_teacheable () const inline virtual
Reimplemented in talker_character_const.
Definition at line 312 of file talker.h.
{
             return {};
         }
Referenced by dialogue::gen_responses().
store_chosen_training()
virtual void talker::store_chosen_training (const skill_id & , const matype_id & , const spell_id & , const proficiency_id &) inline virtual
Reimplemented in talker_npc.
Definition at line 324 of file talker.h.
{
         }
Referenced by dialogue::opt().
str_cur()
virtual int talker::str_cur () const inline virtual
Reimplemented in talker_character_const.
Definition at line 153 of file talker.h.
{
             return 0;
         }
style_seminar_text()
virtual std::string talker::style_seminar_text (const matype_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 306 of file talker.h.
{
             return {};
         }
style_training_text()
virtual std::string talker::style_training_text (const talker & , const matype_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 309 of file talker.h.
{
             return {};
         }
styles_offered_to()
virtual std::vector<matype_id> talker::styles_offered_to (const talker &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 303 of file talker.h.
{
             return {};
         }
Referenced by dialogue::gen_responses().
styles_teacheable()
virtual std::vector<matype_id> talker::styles_teacheable () const inline virtual
Reimplemented in talker_character_const.
Definition at line 300 of file talker.h.
{
             return {};
         }
Referenced by dialogue::gen_responses().
toggle_ai_rule()
virtual void talker::toggle_ai_rule (const std::string & , const std::string &) inline virtual
Reimplemented in talker_npc.
Definition at line 480 of file talker.h.
 {}
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_toggle_npc_rule().
train_proficiency_for()
virtual void talker::train_proficiency_for (const proficiency_id & , int) inline virtual
Reimplemented in talker_character.
Definition at line 275 of file talker.h.
 {}
trial_chance_mod()
virtual int talker::trial_chance_mod (const std::string &) const inline virtual
Reimplemented in talker_npc, and talker_avatar.
Definition at line 133 of file talker.h.
{
             return 0;
         }
Referenced by talk_trial::calc_chance().
turned_hostile()
virtual bool talker::turned_hostile () const inline virtual
Reimplemented in talker_npc.
Definition at line 468 of file talker.h.
{
             return false;
         }
Referenced by talk_effect_t::apply().
unarmed_attack()
virtual bool talker::unarmed_attack () const inline virtual
Reimplemented in talker_character_const.
Definition at line 415 of file talker.h.
{
             return false;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_can_drop_weapon(), and conditional_fun::anonymous_namespace{condition.cpp}::f_can_stow_weapon().
unset_mutation()
virtual void talker::unset_mutation (const trait_id &) inline virtual
Reimplemented in talker_character.
Definition at line 237 of file talker.h.
 {}
update_missions()
virtual void talker::update_missions (const std::vector< mission * > &) inline virtual
Reimplemented in talker_npc.
Definition at line 126 of file talker.h.
 {}
use_amount()
virtual std::list<item> talker::use_amount (const itype_id & , int) inline virtual
Reimplemented in talker_character.
Definition at line 388 of file talker.h.
{
             return {};
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item().
use_charges() [1/2]
virtual std::list<item> talker::use_charges (const itype_id & , int) inline virtual
Reimplemented in talker_character.
Definition at line 375 of file talker.h.
{
             return {};
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item().
use_charges() [2/2]
virtual std::list<item> talker::use_charges (const itype_id & , int , bool) inline virtual
Reimplemented in talker_character.
Definition at line 379 of file talker.h.
{
             return {};
         }
using_martial_art()
virtual bool talker::using_martial_art (const matype_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 724 of file talker.h.
{
             return false;
         }
value()
virtual int talker::value (const item &) const inline virtual
Reimplemented in talker_npc.
Definition at line 391 of file talker.h.
{
             return 0;
         }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talker_character::set_dex_bonus(), talker_character::set_dex_max(), talker_character::set_int_bonus(), talker_character::set_int_max(), talker_character::set_mana_cur(), talker_character::set_per_bonus(), talker_character::set_per_max(), talker_character::set_power_cur(), talker_character::set_skill_exp(), talker_character::set_skill_level(), talker_character::set_stored_kcal(), talker_character::set_str_bonus(), talker_character::set_str_max(), talker_character::set_thirst(), talker_character::set_value(), talker_furniture::set_value(), talker_item::set_value(), and talker_monster::set_value().
view_personality_traits()
virtual std::string talker::view_personality_traits () const inline virtual
Reimplemented in talker_npc.
Definition at line 491 of file talker.h.
{
             return "";
         }
Referenced by dialogue::dynamic_line().
wielded_with_flag()
virtual bool talker::wielded_with_flag (const flag_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 590 of file talker.h.
{
             return false;
         }
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_can_drop_weapon().
wielded_with_weapon_category()
virtual bool talker::wielded_with_weapon_category (const weapon_category_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 593 of file talker.h.
{
             return false;
         }
will_talk_to_u()
virtual bool talker::will_talk_to_u (const Character & , bool) inline virtual
Reimplemented in talker_topic, talker_npc, talker_item_const, talker_furniture, and talker_monster_const.
Definition at line 119 of file talker.h.
{
             return false;
         }
worn_with_flag()
virtual bool talker::worn_with_flag (const flag_id & , const bodypart_id &) const inline virtual
Reimplemented in talker_character_const.
Definition at line 587 of file talker.h.
{
             return false;
         }
The documentation for this class was generated from the following file:
src/talker.h