Cataclysm DDA: islot_milling Class Reference
islot_milling Class Reference
#include <itype.h>
Public Member Functions
void load (const JsonObject &jo)
void deserialize (const JsonObject &jo)
Public Attributes
itype_id into_
recipe_id recipe_
bool was_loaded = false
Detailed Description
Definition at line 1156 of file itype.h.
Member Function Documentation
deserialize()
void islot_milling::deserialize (const JsonObject & jo)
Definition at line 2639 of file item_factory.cpp.
 {
     load( jo );
 }
References load().
load()
void islot_milling::load (const JsonObject & jo)
Definition at line 2633 of file item_factory.cpp.
 {
     optional( jo, was_loaded, "into", into_ );
     optional( jo, was_loaded, "recipe", recipe_ );
 }
References into_, optional(), recipe_, and was_loaded.
Referenced by deserialize().
Member Data Documentation
into_
itype_id islot_milling::into_
Definition at line 1159 of file itype.h.
Referenced by item::final_info(), and load().
recipe_
recipe_id islot_milling::recipe_
Definition at line 1160 of file itype.h.
Referenced by item::final_info(), and load().
was_loaded
bool islot_milling::was_loaded = false
Definition at line 1162 of file itype.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/itype.h
src/item_factory.cpp