Cataclysm DDA: Trait_group_creator Class Reference
Trait_group_creator Class Reference
Interface for creating a group of traits.
#include <trait_group.h>
Public Member Functions
Trait_group_creator (const trait_group::Trait_group_tag &id, int probability)
~Trait_group_creator () override=default
trait_group::Trait_list create (RecursionList &rec) const override
Create a list of traits.
void check_consistency () const override
Check the trait templates for consistency (valid trait types, etc).
bool remove_trait (const trait_id &tid) override
Remove the given trait from this and all linked groups.
bool has_trait (const trait_id &tid) const override
Check if this group or any linked groups contain the given trait.
Public Member Functions inherited from Trait_creation_data
Trait_creation_data (int _probability)
virtual ~Trait_creation_data ()=default
Trait_creation_data (const Trait_creation_data &)=delete
Trait_creation_data & operator= (const Trait_creation_data &)=delete
trait_group::Trait_list create () const
Public Attributes
trait_group::Trait_group_tag id
Public Attributes inherited from Trait_creation_data
int probability
Additional Inherited Members
Public Types inherited from Trait_creation_data
using RecursionList = std::vector< trait_group::Trait_group_tag >
Detailed Description
Interface for creating a group of traits.
This corresponds to a JSON list of traits.
Definition at line 130 of file trait_group.h.
Constructor & Destructor Documentation
Trait_group_creator()
Trait_group_creator::Trait_group_creator (const trait_group::Trait_group_tag & id, int probability)
Definition at line 164 of file trait_group.cpp.
     : Trait_creation_data( probability ), id( id )
 {
 }
~Trait_group_creator()
Trait_group_creator::~Trait_group_creator () override default
Member Function Documentation
check_consistency()
void Trait_group_creator::check_consistency () const override virtual
Check the trait templates for consistency (valid trait types, etc).
Implements Trait_creation_data.
Definition at line 192 of file trait_group.cpp.
 {
     if( id.is_valid() ) {
         debugmsg( "trait group id %s is unknown", id.c_str() );
     }
 }
References debugmsg.
create()
Trait_list Trait_group_creator::create (RecursionList & rec) const override virtual
Create a list of traits.
The resulting list might be empty.
Parameters
[out] rec Recursion list, output goes here
Implements Trait_creation_data.
Definition at line 169 of file trait_group.cpp.
 {
     Trait_list result;
     if( std::find( rec.begin(), rec.end(), id ) != rec.end() ) {
         debugmsg( "recursion in trait creation list %s", id.c_str() );
         return result;
     }
     rec.push_back( id );
     if( !id.is_valid() ) {
         debugmsg( "unknown trait creation list %s", id.c_str() );
         return result;
     }
     const auto tcd = mutation_branch::get_group( id );
     Trait_list tmplist = tcd->create( rec );
     rec.pop_back();
     result.insert( result.end(), tmplist.begin(), tmplist.end() );
     return result;
 }
References debugmsg, and mutation_branch::get_group().
has_trait()
bool Trait_group_creator::has_trait (const trait_id & tid) const override virtual
Check if this group or any linked groups contain the given trait.
Implements Trait_creation_data.
Definition at line 204 of file trait_group.cpp.
 {
     return mutation_branch::get_group( id )->has_trait( tid );
 }
References mutation_branch::get_group().
remove_trait()
bool Trait_group_creator::remove_trait (const trait_id & tid) override virtual
Remove the given trait from this and all linked groups.
Used for blacklisting.
Implements Trait_creation_data.
Definition at line 199 of file trait_group.cpp.
 {
     return mutation_branch::get_group( id )->remove_trait( tid );
 }
References mutation_branch::get_group().
Member Data Documentation
id
trait_group::Trait_group_tag Trait_group_creator::id
Definition at line 136 of file trait_group.h.
The documentation for this class was generated from the following files:
src/trait_group.h
src/trait_group.cpp