Cataclysm DDA: JsonOut Class Reference
JsonOut Class Reference
#include <json.h>
Public Member Functions
JsonOut (std::ostream &stream, bool pretty_print=false, int depth=0)
JsonOut (const JsonOut &)=delete
JsonOut & operator= (const JsonOut &)=delete
void write_indent ()
void write_separator ()
void write_member_separator ()
bool get_need_separator () const
void set_need_separator ()
std::ostream * get_stream ()
int tell ()
void seek (int pos)
void start_pretty ()
void end_pretty ()
void start_object (bool wrap=false)
void end_object ()
void start_array (bool wrap=false)
void end_array ()
void write_null ()
template<typename T , std::enable_if_t< std::is_fundamental_v< T >, int > = 0>
void write (T val)
template<typename T >
auto write (const T &v) -> decltype(serialize(v, *this), void())
Overload that calls a global function serialize(const T&,JsonOut&), if available.
template<typename T >
auto write (const T &v) -> decltype(v.serialize(*this), void())
Overload that calls a member function T::serialize(JsonOut&) const, if available.
template<typename T >
auto write (const std::reference_wrapper< const T > &v) -> decltype(v.get().serialize(*this), void())
Overload to be able to write reference_wrapper as normal references.
template<typename T , std::enable_if_t< std::is_enum_v< T >, int > = 0>
void write (T val)
void write (std::string_view val)
void write (const char *val)
void write (char val)
void write (signed char val)
void write (unsigned char val)
template<size_t N>
void write (const std::bitset< N > &b)
template<typename T >
auto write (const string_id< T > &thing)
template<typename T >
auto write (const int_id< T > &thing)
template<typename E , std::enable_if_t< std::is_enum_v< E >> * = nullptr>
void write_as_string (const E value)
void write_as_string (const std::string_view s)
template<typename T >
void write_as_string (const string_id< T > &s)
template<typename T >
void write_as_string (const int_id< T > &s)
template<typename T , typename U >
void write (const std::pair< T, U > &p)
template<typename T >
void write_as_array (const T &container)
template<typename T , typename std::enable_if_t< !std::is_same_v< void, typename T::value_type > &&!is_string_like< T >::value > * = nullptr>
auto write (const T &container) -> decltype(container.front(),(void) 0)
template<typename T , std::enable_if_t< std::is_same_v< typename T::key_type, typename T::value_type >> * = nullptr>
void write (const T &container)
template<typename T , std::enable_if_t< std::is_same_v< T, item >> * = nullptr>
void write (const cata::colony< T > &container)
template<typename T , std::enable_if_t< !std::is_same_v< T, item > > * = nullptr>
void write (const cata::colony< T > &container)
template<typename T , std::enable_if_t< !std::is_same_v< typename T::key_type, typename T::value_type > > * = nullptr>
void write (const T &map)
void member (std::string_view name)
void null_member (std::string_view name)
template<typename T >
void member (const std::string_view name, const T &value)
template<typename T >
void member (const std::string_view name, const T &value, const T &value_default)
template<typename T >
void member_as_string (const std::string_view name, const T &value)
Private Attributes
std::ostream * stream
bool pretty_print
std::vector< bool > need_wrap
int indent_level = 0
bool need_separator = false
Detailed Description
Definition at line 735 of file json.h.
Constructor & Destructor Documentation
JsonOut() [1/2]
JsonOut::JsonOut (std::ostream & stream, bool pretty_print = false, int depth = 0) explicit
Definition at line 2226 of file json.cpp.
                                                         :
     stream( &s ), pretty_print( pretty ), indent_level( depth )
 {
     // ensure consistent and locale-independent formatting of numerals
     stream->imbue( std::locale::classic() );
     stream->setf( std::ios_base::showpoint );
     stream->setf( std::ios_base::dec, std::ostream::basefield );
     stream->setf( std::ios_base::fixed, std::ostream::floatfield );
     // automatically stringify bool to "true" or "false"
     stream->setf( std::ios_base::boolalpha );
 }
References stream.
JsonOut() [2/2]
JsonOut::JsonOut (const JsonOut &) delete
Member Function Documentation
end_array()
void JsonOut::end_array ()
Definition at line 2346 of file json.cpp.
 {
     end_pretty();
     need_wrap.pop_back();
     stream->put( ']' );
     need_separator = true;
 }
References end_pretty(), need_separator, need_wrap, and stream.
Referenced by anonymous_namespace{savegame_json.cpp}::_write_rle_terrain(), recipe::check_blueprint_requirements(), tool_comp::dump(), item_comp::dump(), dump_req_vec(), inventory::json_save_invcache(), inventory::json_save_items(), input_manager::save(), WORLD::save(), avatar::daily_calories::save_activity(), overmap::save_monster_groups(), mapbuffer::save_quad(), avatar::save_template(), vehicle_prototype::save_vehicle_as_prototype(), serialize(), cata_variant::serialize(), kill_tracker::serialize(), panel_manager::serialize(), basecamp::serialize(), color_manager::serialize(), enum_bitset< E >::serialize(), known_magic::serialize(), teleporter_list::serialize(), mission::serialize(), options_manager::serialize(), safemode::serialize(), uistatedata::serialize(), vehicle_part::serialize(), vehicle::serialize(), diary::serialize(), auto_pickup::rule_list::serialize(), creature_tracker::serialize(), enchant_cache::serialize(), mm_submap::serialize(), mm_region::serialize(), pos_dir< Tripoint >::serialize(), point::serialize(), tripoint::serialize(), relic::serialize(), game::serialize(), overmap::serialize(), mission::serialize_all(), timed_event_manager::serialize_all(), uistatedata::serialize_array(), serialize_array_to_compacted_sequence(), item_pocket::serialize_presets(), overmap::serialize_view(), avatar::store(), Character::store(), submap::store(), write(), write_as_array(), and io::JsonArrayOutputArchive::~JsonArrayOutputArchive().
end_object()
void JsonOut::end_object ()
Definition at line 2327 of file json.cpp.
 {
     end_pretty();
     need_wrap.pop_back();
     stream->put( '}' );
     need_separator = true;
 }
References end_pretty(), need_separator, need_wrap, and stream.
Referenced by recipe::check_blueprint_requirements(), quality_requirement::dump(), requirement_data::dump(), inventory::json_save_invcache(), input_manager::save(), WORLD::save(), worldfactory::save_last_world_info(), mapbuffer::save_quad(), avatar::save_template(), vehicle_prototype::save_vehicle_as_prototype(), serialize(), achievement_state::serialize(), achievements_tracker::serialize(), effect_source::serialize(), kill_tracker::serialize(), memorial_log_entry::serialize(), mission_id::serialize(), event_summary::serialize(), event_multiset::serialize(), stats_tracker::serialize(), nutrients::serialize(), data_handling_activity_actor::serialize(), wear_activity_actor::serialize(), wield_activity_actor::serialize(), invoke_item_activity_actor::serialize(), pickup_menu_activity_actor::serialize(), computer_option::serialize(), computer_failure::serialize(), computer::serialize(), item_location::impl::nowhere::serialize(), item_location::impl::item_on_map::serialize(), item_location::impl::item_on_person::serialize(), item_location::impl::item_on_vehicle::serialize(), item_location::impl::item_in_container::serialize(), Messages::serialize(), panel_manager::serialize(), activity_tracker::serialize(), addiction::serialize(), avatar::daily_calories::serialize(), basecamp::serialize(), bionic::serialize(), bodypart::serialize(), consumption_event::serialize(), Character::trait_data::serialize(), outfit::serialize(), character_martial_arts::serialize(), zone_data::serialize(), color_manager::serialize(), dialogue_chatbin::serialize(), effect::serialize(), faction::serialize(), inventory_selector_save_state::serialize(), item_contents::serialize(), item_pocket::favorite_settings::serialize(), item_pocket::serialize(), fake_spell::serialize(), spell_type::serialize(), known_magic::serialize(), teleporter_list::serialize(), mission::serialize(), mon_special_attack::serialize(), monster::serialize(), player_morale::morale_point::serialize(), job_data::serialize(), npc_personality::serialize(), npc_opinion::serialize(), npc_follower_rules::serialize(), npc_favor::serialize(), options_manager::serialize(), player_activity::serialize(), requirement_data::serialize(), safemode::serialize(), SkillLevel::serialize(), stomach_contents::serialize(), uistatedata::serialize(), smart_controller_config::serialize(), vehicle_part::carried_part_data::serialize(), vehicle_part::serialize(), label::serialize(), vehicle::serialize(), avatar::serialize(), npc::serialize(), drop_or_stash_item_info::serialize(), auto_pickup::rule::serialize(), comp_selection< CompType >::serialize(), damage_over_time_data::serialize(), item::link_data::serialize(), item::extended_photo_def::serialize(), item::craft_data::serialize(), enchantment::bodypart_changes::serialize(), enchant_cache::serialize(), mm_region::serialize(), anonymous_namespace{messages.cpp}::game_message::serialize(), trait_and_var::serialize(), Pickup::pick_info::serialize(), proficiency_set::serialize(), learning_proficiency::serialize(), relic_charge_info::serialize(), relic::serialize(), aim_activity_actor::serialize(), gunmod_remove_activity_actor::serialize(), hacksaw_activity_actor::serialize(), bookbinder_copy_activity_actor::serialize(), hotwire_car_activity_actor::serialize(), glide_activity_actor::serialize(), bikerack_racking_activity_actor::serialize(), bikerack_unracking_activity_actor::serialize(), read_activity_actor::serialize(), move_items_activity_actor::serialize(), pickup_activity_actor::serialize(), boltcutting_activity_actor::serialize(), lockpick_activity_actor::serialize(), ebooksave_activity_actor::serialize(), open_gate_activity_actor::serialize(), consume_activity_actor::serialize(), try_sleep_activity_actor::serialize(), safecracking_activity_actor::serialize(), unload_activity_actor::serialize(), craft_activity_actor::serialize(), workout_activity_actor::serialize(), drop_activity_actor::serialize(), stash_activity_actor::serialize(), harvest_activity_actor::serialize(), reload_activity_actor::serialize(), milk_activity_actor::serialize(), shearing_activity_actor::serialize(), disassemble_activity_actor::serialize(), move_furniture_activity_actor::serialize(), insert_item_activity_actor::serialize(), tent_placement_activity_actor::serialize(), oxytorch_activity_actor::serialize(), play_with_pet_activity_actor::serialize(), prying_activity_actor::serialize(), tent_deconstruct_activity_actor::serialize(), reel_cable_activity_actor::serialize(), vehicle_folding_activity_actor::serialize(), vehicle_unfolding_activity_actor::serialize(), wash_activity_actor::serialize(), chop_logs_activity_actor::serialize(), chop_planks_activity_actor::serialize(), chop_tree_activity_actor::serialize(), churn_activity_actor::serialize(), clear_rubble_activity_actor::serialize(), disable_activity_actor::serialize(), firstaid_activity_actor::serialize(), forage_activity_actor::serialize(), gunmod_add_activity_actor::serialize(), longsalvage_activity_actor::serialize(), mop_activity_actor::serialize(), unload_loot_activity_actor::serialize(), diary::serialize(), game::serialize(), overmap::serialize(), weather_manager::serialize_all(), timed_event_manager::serialize_all(), game::serialize_master(), overmapbuffer::serialize_overmap_global_state(), overmap::serialize_view(), mod_manager::set_default_mods(), Character::store(), write(), achievements_tracker::write_json_achievements(), memorial_logger::write_json_memorial(), and io::JsonObjectOutputArchive::~JsonObjectOutputArchive().
end_pretty()
void JsonOut::end_pretty ()
Definition at line 2300 of file json.cpp.
 {
     if( pretty_print ) {
         indent_level -= 1;
         // Wrap after ending top level array and object.
         // Also wrap in the special case of exiting an array containing an object.
         if( indent_level < 1 || need_wrap.back() ) {
             stream->put( '\n' );
             write_indent();
         } else {
             // Otherwise pad after ending.
             stream->put( ' ' );
         }
     }
 }
References indent_level, need_wrap, pretty_print, stream, and write_indent().
Referenced by end_array(), and end_object().
get_need_separator()
bool JsonOut::get_need_separator () const inline
Definition at line 753 of file json.h.
{
             return need_separator;
         }
References need_separator.
get_stream()
std::ostream* JsonOut::get_stream () inline
Definition at line 759 of file json.h.
{
             return stream;
         }
References stream.
member() [1/3]
template<typename T > void JsonOut::member (const std::string_view name, const T & value) inline
Definition at line 948 of file json.h.
{
             member( name );
             write( value );
         }
References member(), om_direction::name(), and write().
member() [2/3]
template<typename T > void JsonOut::member (const std::string_view name, const T & value, const T & value_default) inline
Definition at line 952 of file json.h.
{
             if( value != value_default ) {
                 member( name, value );
             }
         }
References member(), and om_direction::name().
member() [3/3]
void JsonOut::member (std::string_view name)
Definition at line 2422 of file json.cpp.
 {
     write( name );
     write_member_separator();
 }
References om_direction::name(), write(), and write_member_separator().
Referenced by recipe::check_blueprint_requirements(), quality_requirement::dump(), requirement_data::dump(), io::JsonObjectOutputArchive::io(), inventory::json_save_invcache(), member(), member_as_string(), null_member(), input_manager::save(), WORLD::save(), avatar::daily_calories::save_activity(), save_inv_state(), worldfactory::save_last_world_info(), overmap::save_monster_groups(), mapbuffer::save_quad(), avatar::save_template(), vehicle_prototype::save_vehicle_as_prototype(), serialize(), achievement_state::serialize(), achievements_tracker::serialize(), effect_source::serialize(), kill_tracker::serialize(), memorial_log_entry::serialize(), mission_id::serialize(), event_summary::serialize(), event_multiset::serialize(), stats_tracker::serialize(), nutrients::serialize(), data_handling_activity_actor::serialize(), wear_activity_actor::serialize(), wield_activity_actor::serialize(), invoke_item_activity_actor::serialize(), pickup_menu_activity_actor::serialize(), computer_option::serialize(), computer_failure::serialize(), computer::serialize(), item_location::impl::nowhere::serialize(), item_location::impl::item_on_map::serialize(), item_location::impl::item_on_person::serialize(), item_location::impl::item_on_vehicle::serialize(), item_location::impl::item_in_container::serialize(), Messages::serialize(), panel_manager::serialize(), activity_tracker::serialize(), addiction::serialize(), avatar::daily_calories::serialize(), basecamp::serialize(), bionic::serialize(), bodypart::serialize(), consumption_event::serialize(), Character::trait_data::serialize(), outfit::serialize(), character_martial_arts::serialize(), zone_data::serialize(), color_manager::serialize(), dialogue_chatbin::serialize(), effect::serialize(), faction::serialize(), inventory_selector_save_state::serialize(), item::serialize(), item_contents::serialize(), item_pocket::favorite_settings::serialize(), item_pocket::serialize(), fake_spell::serialize(), spell_type::serialize(), known_magic::serialize(), teleporter_list::serialize(), mission::serialize(), mon_special_attack::serialize(), player_morale::morale_point::serialize(), job_data::serialize(), npc_personality::serialize(), npc_opinion::serialize(), npc_follower_rules::serialize(), npc_favor::serialize(), options_manager::serialize(), player_activity::serialize(), requirement_data::serialize(), safemode::serialize(), SkillLevel::serialize(), stomach_contents::serialize(), uistatedata::serialize(), smart_controller_config::serialize(), vehicle_part::carried_part_data::serialize(), vehicle_part::serialize(), label::serialize(), vehicle::serialize(), plot_options::serialize(), blueprint_options::serialize(), ignorable_options::serialize(), loot_options::serialize(), unload_options::serialize(), advanced_inv_pane_save_state::serialize(), advanced_inv_save_state::serialize(), diary::serialize(), drop_or_stash_item_info::serialize(), auto_pickup::rule::serialize(), comp_selection< CompType >::serialize(), damage_over_time_data::serialize(), global_variables::serialize(), item::link_data::serialize(), item::extended_photo_def::serialize(), item::craft_data::serialize(), enchantment::bodypart_changes::serialize(), enchant_cache::serialize(), mm_region::serialize(), anonymous_namespace{messages.cpp}::game_message::serialize(), trait_and_var::serialize(), Pickup::pick_info::serialize(), proficiency_set::serialize(), learning_proficiency::serialize(), relic_charge_info::serialize(), relic::serialize(), aim_activity_actor::serialize(), gunmod_remove_activity_actor::serialize(), hacksaw_activity_actor::serialize(), bookbinder_copy_activity_actor::serialize(), hotwire_car_activity_actor::serialize(), glide_activity_actor::serialize(), bikerack_racking_activity_actor::serialize(), bikerack_unracking_activity_actor::serialize(), read_activity_actor::serialize(), move_items_activity_actor::serialize(), pickup_activity_actor::serialize(), boltcutting_activity_actor::serialize(), lockpick_activity_actor::serialize(), ebooksave_activity_actor::serialize(), open_gate_activity_actor::serialize(), consume_activity_actor::serialize(), try_sleep_activity_actor::serialize(), safecracking_activity_actor::serialize(), unload_activity_actor::serialize(), craft_activity_actor::serialize(), workout_activity_actor::serialize(), drop_activity_actor::serialize(), stash_activity_actor::serialize(), harvest_activity_actor::serialize(), reload_activity_actor::serialize(), milk_activity_actor::serialize(), shearing_activity_actor::serialize(), disassemble_activity_actor::serialize(), move_furniture_activity_actor::serialize(), insert_item_activity_actor::serialize(), tent_placement_activity_actor::serialize(), oxytorch_activity_actor::serialize(), play_with_pet_activity_actor::serialize(), prying_activity_actor::serialize(), tent_deconstruct_activity_actor::serialize(), reel_cable_activity_actor::serialize(), vehicle_folding_activity_actor::serialize(), vehicle_unfolding_activity_actor::serialize(), wash_activity_actor::serialize(), chop_logs_activity_actor::serialize(), chop_planks_activity_actor::serialize(), chop_tree_activity_actor::serialize(), churn_activity_actor::serialize(), clear_rubble_activity_actor::serialize(), disable_activity_actor::serialize(), firstaid_activity_actor::serialize(), forage_activity_actor::serialize(), gunmod_add_activity_actor::serialize(), longsalvage_activity_actor::serialize(), mop_activity_actor::serialize(), unload_loot_activity_actor::serialize(), game::serialize(), overmap::serialize(), weather_manager::serialize_all(), timed_event_manager::serialize_all(), uistatedata::serialize_array(), game::serialize_master(), overmapbuffer::serialize_overmap_global_state(), overmap::serialize_view(), mod_manager::set_default_mods(), avatar::store(), Character::store(), monster::store(), npc::store(), Creature::store(), player_morale::store(), submap::store(), achievements_tracker::write_json_achievements(), and memorial_logger::write_json_memorial().
member_as_string()
template<typename T > void JsonOut::member_as_string (const std::string_view name, const T & value) inline
Definition at line 958 of file json.h.
{
             member( name );
             write_as_string( value );
         }
References member(), om_direction::name(), and write_as_string().
Referenced by achievement_state::serialize(), mission_id::serialize(), and Character::store().
null_member()
void JsonOut::null_member (std::string_view name)
Definition at line 2428 of file json.cpp.
 {
     member( name );
     write_null();
 }
References member(), om_direction::name(), and write_null().
operator=()
JsonOut& JsonOut::operator= (const JsonOut &) delete
seek()
void JsonOut::seek (int pos)
Definition at line 2244 of file json.cpp.
 {
     stream->clear();
     stream->seekp( pos );
     need_separator = false;
 }
References need_separator, math_opers::pos(), and stream.
set_need_separator()
void JsonOut::set_need_separator () inline
Definition at line 756 of file json.h.
{
             need_separator = true;
         }
References need_separator.
start_array()
void JsonOut::start_array (bool wrap = false)
Definition at line 2335 of file json.cpp.
 {
     if( need_separator ) {
         write_separator();
     }
     stream->put( '[' );
     need_wrap.push_back( wrap );
     start_pretty();
     need_separator = false;
 }
References need_separator, need_wrap, start_pretty(), stream, and write_separator().
Referenced by anonymous_namespace{savegame_json.cpp}::_write_rle_terrain(), recipe::check_blueprint_requirements(), tool_comp::dump(), item_comp::dump(), dump_req_vec(), inventory::json_save_invcache(), inventory::json_save_items(), io::JsonArrayOutputArchive::JsonArrayOutputArchive(), input_manager::save(), WORLD::save(), avatar::daily_calories::save_activity(), overmap::save_monster_groups(), mapbuffer::save_quad(), avatar::save_template(), vehicle_prototype::save_vehicle_as_prototype(), serialize(), cata_variant::serialize(), kill_tracker::serialize(), panel_manager::serialize(), basecamp::serialize(), color_manager::serialize(), enum_bitset< E >::serialize(), known_magic::serialize(), teleporter_list::serialize(), mission::serialize(), options_manager::serialize(), safemode::serialize(), uistatedata::serialize(), vehicle_part::serialize(), vehicle::serialize(), diary::serialize(), auto_pickup::rule_list::serialize(), creature_tracker::serialize(), enchant_cache::serialize(), mm_submap::serialize(), mm_region::serialize(), pos_dir< Tripoint >::serialize(), point::serialize(), tripoint::serialize(), relic::serialize(), game::serialize(), overmap::serialize(), mission::serialize_all(), timed_event_manager::serialize_all(), uistatedata::serialize_array(), serialize_array_to_compacted_sequence(), item_pocket::serialize_presets(), overmap::serialize_view(), avatar::store(), Character::store(), submap::store(), write(), and write_as_array().
start_object()
void JsonOut::start_object (bool wrap = false)
Definition at line 2316 of file json.cpp.
 {
     if( need_separator ) {
         write_separator();
     }
     stream->put( '{' );
     need_wrap.push_back( wrap );
     start_pretty();
     need_separator = false;
 }
References need_separator, need_wrap, start_pretty(), stream, and write_separator().
Referenced by recipe::check_blueprint_requirements(), quality_requirement::dump(), requirement_data::dump(), inventory::json_save_invcache(), io::JsonObjectOutputArchive::JsonObjectOutputArchive(), input_manager::save(), auto_notes::auto_note_settings::save(), WORLD::save(), worldfactory::save_last_world_info(), mapbuffer::save_quad(), avatar::save_template(), vehicle_prototype::save_vehicle_as_prototype(), serialize(), achievement_state::serialize(), achievements_tracker::serialize(), effect_source::serialize(), kill_tracker::serialize(), memorial_log_entry::serialize(), mission_id::serialize(), event_summary::serialize(), event_multiset::serialize(), stats_tracker::serialize(), nutrients::serialize(), data_handling_activity_actor::serialize(), wear_activity_actor::serialize(), wield_activity_actor::serialize(), invoke_item_activity_actor::serialize(), pickup_menu_activity_actor::serialize(), computer_option::serialize(), computer_failure::serialize(), computer::serialize(), item_location::impl::nowhere::serialize(), item_location::impl::item_on_map::serialize(), item_location::impl::item_on_person::serialize(), item_location::impl::item_on_vehicle::serialize(), item_location::impl::item_in_container::serialize(), Messages::serialize(), panel_manager::serialize(), activity_tracker::serialize(), addiction::serialize(), avatar::daily_calories::serialize(), basecamp::serialize(), bionic::serialize(), bodypart::serialize(), consumption_event::serialize(), Character::trait_data::serialize(), outfit::serialize(), character_martial_arts::serialize(), zone_data::serialize(), color_manager::serialize(), dialogue_chatbin::serialize(), effect::serialize(), faction::serialize(), inventory_selector_save_state::serialize(), item_contents::serialize(), item_pocket::favorite_settings::serialize(), item_pocket::serialize(), fake_spell::serialize(), spell_type::serialize(), known_magic::serialize(), teleporter_list::serialize(), mission::serialize(), mon_special_attack::serialize(), monster::serialize(), player_morale::morale_point::serialize(), job_data::serialize(), npc_personality::serialize(), npc_opinion::serialize(), npc_follower_rules::serialize(), npc_favor::serialize(), options_manager::serialize(), player_activity::serialize(), requirement_data::serialize(), safemode::serialize(), SkillLevel::serialize(), stomach_contents::serialize(), uistatedata::serialize(), smart_controller_config::serialize(), vehicle_part::carried_part_data::serialize(), vehicle_part::serialize(), label::serialize(), vehicle::serialize(), avatar::serialize(), npc::serialize(), drop_or_stash_item_info::serialize(), auto_pickup::rule::serialize(), comp_selection< CompType >::serialize(), damage_over_time_data::serialize(), item::link_data::serialize(), item::extended_photo_def::serialize(), item::craft_data::serialize(), enchantment::bodypart_changes::serialize(), enchant_cache::serialize(), mm_region::serialize(), anonymous_namespace{messages.cpp}::game_message::serialize(), trait_and_var::serialize(), Pickup::pick_info::serialize(), proficiency_set::serialize(), learning_proficiency::serialize(), relic_charge_info::serialize(), relic::serialize(), aim_activity_actor::serialize(), gunmod_remove_activity_actor::serialize(), hacksaw_activity_actor::serialize(), bookbinder_copy_activity_actor::serialize(), hotwire_car_activity_actor::serialize(), glide_activity_actor::serialize(), bikerack_racking_activity_actor::serialize(), bikerack_unracking_activity_actor::serialize(), read_activity_actor::serialize(), move_items_activity_actor::serialize(), pickup_activity_actor::serialize(), boltcutting_activity_actor::serialize(), lockpick_activity_actor::serialize(), ebooksave_activity_actor::serialize(), open_gate_activity_actor::serialize(), consume_activity_actor::serialize(), try_sleep_activity_actor::serialize(), safecracking_activity_actor::serialize(), unload_activity_actor::serialize(), craft_activity_actor::serialize(), workout_activity_actor::serialize(), drop_activity_actor::serialize(), stash_activity_actor::serialize(), harvest_activity_actor::serialize(), reload_activity_actor::serialize(), milk_activity_actor::serialize(), shearing_activity_actor::serialize(), disassemble_activity_actor::serialize(), move_furniture_activity_actor::serialize(), insert_item_activity_actor::serialize(), tent_placement_activity_actor::serialize(), oxytorch_activity_actor::serialize(), play_with_pet_activity_actor::serialize(), prying_activity_actor::serialize(), tent_deconstruct_activity_actor::serialize(), reel_cable_activity_actor::serialize(), vehicle_folding_activity_actor::serialize(), vehicle_unfolding_activity_actor::serialize(), wash_activity_actor::serialize(), chop_logs_activity_actor::serialize(), chop_planks_activity_actor::serialize(), chop_tree_activity_actor::serialize(), churn_activity_actor::serialize(), clear_rubble_activity_actor::serialize(), disable_activity_actor::serialize(), firstaid_activity_actor::serialize(), forage_activity_actor::serialize(), gunmod_add_activity_actor::serialize(), longsalvage_activity_actor::serialize(), mop_activity_actor::serialize(), unload_loot_activity_actor::serialize(), diary::serialize(), game::serialize(), overmap::serialize(), weather_manager::serialize_all(), timed_event_manager::serialize_all(), game::serialize_master(), overmapbuffer::serialize_overmap_global_state(), overmap::serialize_view(), mod_manager::set_default_mods(), Character::store(), write(), achievements_tracker::write_json_achievements(), and memorial_logger::write_json_memorial().
start_pretty()
void JsonOut::start_pretty ()
Definition at line 2285 of file json.cpp.
 {
     if( pretty_print ) {
         indent_level += 1;
         // Wrap after top level object and array opening.
         if( indent_level < 2 || need_wrap.back() ) {
             stream->put( '\n' );
             write_indent();
         } else {
             // Otherwise pad after opening.
             stream->put( ' ' );
         }
     }
 }
References indent_level, need_wrap, pretty_print, stream, and write_indent().
Referenced by start_array(), and start_object().
tell()
int JsonOut::tell ()
Definition at line 2239 of file json.cpp.
 {
     return stream->tellp();
 }
References stream.
write() [1/19]
void JsonOut::write (char val) inline
Definition at line 815 of file json.h.
{
             write( static_cast<int>( val ) );
         }
References write().
write() [2/19]
template<typename T , std::enable_if_t< std::is_same_v< T, item >> * = nullptr> void JsonOut::write (const cata::colony< T > & container) inline
Definition at line 896 of file json.h.
{
             start_array();
             // simple RLE implementation:
             // run_l is the length of the "running sequence" of identical items, ending with the current item.
             // when sequence ends, it's written as either the single item object (run_l==1) or as a two-element
             // array (run_l > 1), where the first element is the item and second element is the size of the sequence.
             int run_l = 1;
             for( auto it = container.begin(); it != container.end(); ++it ) {
                 const auto nxt = std::next( it );
                 if( nxt == container.end() || !it->same_for_rle( *nxt ) ) {
                     if( run_l == 1 ) {
                         write( *it );
                     } else {
                         start_array();
                         write( *it );
                         write( run_l );
                         end_array();
                     }
                     run_l = 1;
                 } else {
                     run_l++;
                 }
             }
             end_array();
         }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::begin(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::end(), end_array(), start_array(), and write().
write() [3/19]
template<typename T , std::enable_if_t< !std::is_same_v< T, item > > * = nullptr> void JsonOut::write (const cata::colony< T > & container) inline
Definition at line 925 of file json.h.
{
             write_as_array( container );
         }
References write_as_array().
write() [4/19]
void JsonOut::write (const char * val) inline
Definition at line 810 of file json.h.
{
             write( std::string( val ) );
         }
References write().
write() [5/19]
template<typename T > auto JsonOut::write (const int_id< T > & thing) inline
Definition at line 834 of file json.h.
{
             write( thing.id().str() );
         }
References int_id< T >::id(), and write().
write() [6/19]
template<size_t N> void JsonOut::write (const std::bitset< N > & b)
Definition at line 2407 of file json.cpp.
 {
     if( need_separator ) {
         write_separator();
     }
     std::string converted = b.to_string();
     stream->put( '"' );
     for( char &i : converted ) {
         unsigned char ch = i;
         stream->put( ch );
     }
     stream->put( '"' );
     need_separator = true;
 }
References b, need_separator, stream, and write_separator().
write() [7/19]
template<typename T , typename U > void JsonOut::write (const std::pair< T, U > & p) inline
Definition at line 859 of file json.h.
{
             start_array();
             write( p.first );
             write( p.second );
             end_array();
         }
References end_array(), start_array(), and write().
write() [8/19]
template<typename T > auto JsonOut::write (const std::reference_wrapper< const T > & v) -> decltype(v.get().serialize(*this), void()) inline
Overload to be able to write reference_wrapper as normal references.
Definition at line 798 of file json.h.
{
             v.get().serialize( *this );
         }
write() [9/19]
template<typename T > auto JsonOut::write (const string_id< T > & thing) inline
Definition at line 829 of file json.h.
{
             write( thing.str() );
         }
References string_id< T >::str(), and write().
write() [10/19]
template<typename T , std::enable_if_t< std::is_same_v< typename T::key_type, typename T::value_type >> * = nullptr> void JsonOut::write (const T & container) inline
Definition at line 890 of file json.h.
{
             write_as_array( container );
         }
References write_as_array().
write() [11/19]
template<typename T , typename std::enable_if_t< !std::is_same_v< void, typename T::value_type > &&!is_string_like< T >::value > * = nullptr> auto JsonOut::write (const T & container) -> decltype(container.front(), (void)0) inline
Definition at line 881 of file json.h.
{
             write_as_array( container );
         }
References write_as_array().
write() [12/19]
template<typename T , std::enable_if_t< !std::is_same_v< typename T::key_type, typename T::value_type > > * = nullptr> void JsonOut::write (const T & map) inline
Definition at line 934 of file json.h.
{
             start_object();
             for( const auto &it : map ) {
                 write_as_string( it.first );
                 write_member_separator();
                 write( it.second );
             }
             end_object();
         }
References end_object(), start_object(), write(), write_as_string(), and write_member_separator().
write() [13/19]
template<typename T > auto JsonOut::write (const T & v) -> decltype(serialize(v, *this), void()) inline
Overload that calls a global function serialize(const T&,JsonOut&), if available.
Definition at line 786 of file json.h.
{
             serialize( v, *this );
         }
References serialize().
write() [14/19]
template<typename T > auto JsonOut::write (const T & v) -> decltype(v.serialize(*this), void()) inline
Overload that calls a member function T::serialize(JsonOut&) const, if available.
Definition at line 792 of file json.h.
{
             v.serialize( *this );
         }
write() [15/19]
void JsonOut::write (signed char val) inline
Definition at line 818 of file json.h.
{
             write( static_cast<int>( val ) );
         }
References write().
write() [16/19]
void JsonOut::write (std::string_view val)
Definition at line 2363 of file json.cpp.
 {
     if( need_separator ) {
         write_separator();
     }
     stream->put( '"' );
     for( const char &i : val ) {
         unsigned char ch = i;
         if( ch == '"' ) {
             stream->write( "\\\"", 2 );
         } else if( ch == '\\' ) {
             stream->write( "\\\\", 2 );
         } else if( ch == '/' ) {
             // don't technically need to escape this
             stream->put( '/' );
         } else if( ch == '\b' ) {
             stream->write( "\\b", 2 );
         } else if( ch == '\f' ) {
             stream->write( "\\f", 2 );
         } else if( ch == '\n' ) {
             stream->write( "\\n", 2 );
         } else if( ch == '\r' ) {
             stream->write( "\\r", 2 );
         } else if( ch == '\t' ) {
             stream->write( "\\t", 2 );
         } else if( ch < 0x20 ) {
             // convert to "\uxxxx" unicode escape
             stream->write( "\\u00", 4 );
             stream->put( ( ch < 0x10 ) ? '0' : '1' );
             char remainder = ch & 0x0F;
             if( remainder < 0x0A ) {
                 stream->put( '0' + remainder );
             } else {
                 stream->put( 'A' + ( remainder - 0x0A ) );
             }
         } else {
             stream->put( ch );
         }
     }
     stream->put( '"' );
     need_separator = true;
 }
References need_separator, stream, and write_separator().
write() [17/19]
template<typename T , std::enable_if_t< std::is_fundamental_v< T >, int > = 0> void JsonOut::write (T val) inline
Definition at line 776 of file json.h.
{
             if( need_separator ) {
                 write_separator();
             }
             *stream << val;
             need_separator = true;
         }
References need_separator, stream, and write_separator().
Referenced by anonymous_namespace{savegame_json.cpp}::_write_rle_terrain(), recipe::check_blueprint_requirements(), tool_comp::dump(), item_comp::dump(), dump_to_json_string(), vehicle::get_folded_item(), inventory::json_save_invcache(), member(), input_manager::save(), memorial_logger::save(), avatar::daily_calories::save_activity(), mod_manager::save_mods_list(), overmap::save_monster_groups(), mapbuffer::save_quad(), vehicle_prototype::save_vehicle_as_prototype(), zone_manager::save_world_zones(), serialize(), cata_variant::serialize(), character_id::serialize(), kill_tracker::serialize(), mapgen_arguments::serialize(), zone_manager::serialize(), mission::serialize(), uistatedata::serialize(), vehicle_part::serialize(), time_duration::serialize(), time_point::serialize(), nc_color::serialize(), contents_change_handler::serialize(), creature_tracker::serialize(), faction_manager::serialize(), item_components::serialize(), mm_submap::serialize(), mm_region::serialize(), pos_dir< Tripoint >::serialize(), point::serialize(), tripoint::serialize(), units::quantity< V, U >::serialize(), body_part_set::serialize(), overmap::serialize(), uistatedata::serialize_array(), serialize_array_to_compacted_sequence(), overmap::serialize_view(), mod_manager::set_default_mods(), avatar::store(), Character::store(), submap::store(), io::detail::has_archive_tag< T, E >::write(), write(), write_as_array(), write_as_string(), and item::write_extended_photos().
write() [18/19]
template<typename T , std::enable_if_t< std::is_enum_v< T >, int > = 0> void JsonOut::write (T val) inline
Definition at line 804 of file json.h.
{
             write( static_cast<std::underlying_type_t<T>>( val ) );
         }
References write().
write() [19/19]
void JsonOut::write (unsigned char val) inline
Definition at line 821 of file json.h.
{
             write( static_cast<int>( val ) );
         }
References write().
write_as_array()
template<typename T > void JsonOut::write_as_array (const T & container) inline
Definition at line 867 of file json.h.
{
             start_array();
             for( const auto &e : container ) {
                 write( e );
             }
             end_array();
         }
References end_array(), start_array(), and write().
Referenced by overmapbuffer::serialize_overmap_global_state(), and write().
write_as_string() [1/4]
template<typename E , std::enable_if_t< std::is_enum_v< E >> * = nullptr> void JsonOut::write_as_string (const E value) inline
Definition at line 840 of file json.h.
{
             write( io::enum_to_string<E>( value ) );
         }
References write().
Referenced by member_as_string(), vehicle_prototype::save_vehicle_as_prototype(), cata_variant::serialize(), computer_option::serialize(), computer_failure::serialize(), enum_bitset< E >::serialize(), write(), and io::detail::has_archive_tag< T, E >::write().
write_as_string() [2/4]
template<typename T > void JsonOut::write_as_string (const int_id< T > & s) inline
Definition at line 854 of file json.h.
{
             write( s.id() );
         }
References int_id< T >::id(), and write().
write_as_string() [3/4]
void JsonOut::write_as_string (const std::string_view s) inline
Definition at line 844 of file json.h.
{
             write( s );
         }
References write().
write_as_string() [4/4]
template<typename T > void JsonOut::write_as_string (const string_id< T > & s) inline
Definition at line 849 of file json.h.
{
             write( s );
         }
References write().
write_indent()
void JsonOut::write_indent ()
Definition at line 2251 of file json.cpp.
 {
     std::fill_n( std::ostream_iterator<char>( *stream ), indent_level * 2, ' ' );
 }
References indent_level, and stream.
Referenced by end_pretty(), start_pretty(), and write_separator().
write_member_separator()
void JsonOut::write_member_separator ()
Definition at line 2275 of file json.cpp.
 {
     if( pretty_print ) {
         stream->write( ": ", 2 );
     } else {
         stream->put( ':' );
     }
     need_separator = false;
 }
References need_separator, pretty_print, and stream.
Referenced by member(), mm_region::serialize(), and write().
write_null()
void JsonOut::write_null ()
Definition at line 2354 of file json.cpp.
 {
     if( need_separator ) {
         write_separator();
     }
     stream->write( "null", 4 );
     need_separator = true;
 }
References need_separator, stream, and write_separator().
Referenced by null_member(), serialize(), meditate_activity_actor::serialize(), shave_activity_actor::serialize(), haircut_activity_actor::serialize(), mm_region::serialize(), autodrive_activity_actor::serialize(), hacking_activity_actor::serialize(), and migration_cancel_activity_actor::serialize().
write_separator()
void JsonOut::write_separator ()
Definition at line 2256 of file json.cpp.
 {
     if( !need_separator ) {
         return;
     }
     stream->put( ',' );
     if( pretty_print ) {
         // Wrap after separator between objects and between members of top-level objects.
         if( indent_level < 2 || need_wrap.back() ) {
             stream->put( '\n' );
             write_indent();
         } else {
             // Otherwise pad after commas.
             stream->put( ' ' );
         }
     }
     need_separator = false;
 }
References indent_level, need_separator, need_wrap, pretty_print, stream, and write_indent().
Referenced by start_array(), start_object(), write(), and write_null().
Member Data Documentation
indent_level
int JsonOut::indent_level = 0 private
Definition at line 741 of file json.h.
Referenced by end_pretty(), start_pretty(), write_indent(), and write_separator().
need_separator
bool JsonOut::need_separator = false private
Definition at line 742 of file json.h.
Referenced by end_array(), end_object(), get_need_separator(), seek(), set_need_separator(), start_array(), start_object(), write(), write_member_separator(), write_null(), and write_separator().
need_wrap
std::vector<bool> JsonOut::need_wrap private
Definition at line 740 of file json.h.
Referenced by end_array(), end_object(), end_pretty(), start_array(), start_object(), start_pretty(), and write_separator().
pretty_print
bool JsonOut::pretty_print private
Definition at line 739 of file json.h.
Referenced by end_pretty(), start_pretty(), write_member_separator(), and write_separator().
stream
std::ostream* JsonOut::stream private
Definition at line 738 of file json.h.
Referenced by end_array(), end_object(), end_pretty(), get_stream(), JsonOut(), seek(), start_array(), start_object(), start_pretty(), tell(), write(), write_indent(), write_member_separator(), write_null(), and write_separator().
The documentation for this class was generated from the following files:
src/json.h
src/json.cpp