Cataclysm DDA: chop_tree_activity_actor Class Reference
chop_tree_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
chop_tree_activity_actor ()=default
chop_tree_activity_actor (int moves, const item_location &tool)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves
item_location tool
Detailed Description
Definition at line 1860 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
chop_tree_activity_actor() [1/2]
chop_tree_activity_actor::chop_tree_activity_actor () default
chop_tree_activity_actor() [2/2]
chop_tree_activity_actor::chop_tree_activity_actor (int moves, const item_location & tool) inline
Definition at line 1864 of file activity_actor_definitions.h.
 : moves( moves ), tool( tool ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> chop_tree_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1874 of file activity_actor_definitions.h.
{
             return std::make_unique<chop_tree_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > chop_tree_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6459 of file activity_actor.cpp.
 {
     chop_tree_activity_actor actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "moves", actor.moves );
     data.read( "tool", actor.tool );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void chop_tree_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 6375 of file activity_actor.cpp.
 {
     chop_single_do_turn( act );
 }
References act, and chop_single_do_turn().
finish()
void chop_tree_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 6380 of file activity_actor.cpp.
 {
     map &here = get_map();
     const tripoint &pos = here.getlocal( act.placement );
     tripoint direction;
     if( !who.is_npc() &&
         ( who.backlog.empty() || who.backlog.front().id() != ACT_MULTIPLE_CHOP_TREES ) ) {
         while( true ) {
             if( const std::optional<tripoint> dir = choose_direction(
                     _( "Select a direction for the tree to fall in." ) ) ) {
                 direction = *dir;
                 break;
             }
             // try again
         }
     } else {
         creature_tracker &creatures = get_creature_tracker();
         const point main_dir = pos.xy() - who.pos().xy();
         const int circle_size = 8;
         static constexpr std::array<point, circle_size> circle = {
             point_east, point_south_east, point_south, point_south_west, point_west,
             point_north_west, point_north, point_north_east
         };
         int circle_center = 0;  //  Initialized as the compiler complained
         for( int i = 0; i < circle_size; i++ ) {
             if( main_dir == circle[i] ) {
                 circle_center = i;
                 break;
             }
         }
         std::vector<point> candidates;
         candidates = { main_dir,                                  // Fall straight away
                        circle[( circle_center + circle_size - 1 ) % circle_size], // Fall away to the left. Adding the full circle to ensure modulo gives a non negative result
                        circle[( circle_center + 1 ) % circle_size],              // Fall away to the right
                        circle[( circle_center + circle_size - 2 ) % circle_size], // Fall to the left
                        circle[( circle_center + 2 ) % circle_size],              // Fall to the right
                        circle[( circle_center + circle_size - 3 ) % circle_size], // Fall towards to the left
                        circle[( circle_center + 3 ) % circle_size]
                      };              // Fall towards to the right
         for( const point &direc : candidates ) {
             bool cantuse = false;
             tripoint proposed_to = pos + point( 3 * direc.x, 3 * direc.y );
             std::vector<tripoint> rough_tree_line = line_to( pos, proposed_to );
             for( const tripoint &elem : rough_tree_line ) {
                 if( creatures.creature_at( elem ) ) {
                     cantuse = true;
                     break;
                 }
             }
             if( !cantuse ) {
                 direction = tripoint( direc, pos.z );
                 break;
             }
         }
     }
     here.cut_down_tree( tripoint_bub_ms( pos ), direction.xy() );
     who.add_msg_if_player( m_good, _( "You finish chopping down a tree." ) );
     // sound of falling tree
     here.collapse_at( pos, false, true, false );
     sfx::play_variant_sound( "misc", "timber",
                              sfx::get_heard_volume( here.getlocal( act.placement ) ) );
     get_event_bus().send<event_type::cuts_tree>( who.getID() );
     act.set_to_null();
     activity_handlers::resume_for_multi_activities( who );
 }
References _, act, ACT_MULTIPLE_CHOP_TREES, Character::add_msg_if_player(), Character::backlog, choose_direction(), circle(), map::collapse_at(), creature_tracker::creature_at(), map::cut_down_tree(), cuts_tree, get_creature_tracker(), get_event_bus(), sfx::get_heard_volume(), get_map(), Character::getID(), map::getlocal(), Character::is_npc(), line_to(), m_good, sfx::play_variant_sound(), point, point_east, point_north, point_north_east, point_north_west, point_south, point_south_east, point_south_west, point_west, Creature::pos(), math_opers::pos(), activity_handlers::resume_for_multi_activities(), event_bus::send(), tripoint, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and tripoint::xy().
get_type()
activity_id chop_tree_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1866 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_CHOP_TREE" );
         }
References activity_id.
serialize()
void chop_tree_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6449 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves", moves );
     jsout.member( "tool", tool );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves, JsonOut::start_object(), and tool.
start()
void chop_tree_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 6369 of file activity_actor.cpp.
 {
     act.moves_total = moves;
     act.moves_left = moves;
 }
References act, and moves.
Member Data Documentation
moves
int chop_tree_activity_actor::moves private
Definition at line 1882 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
tool
item_location chop_tree_activity_actor::tool private
Definition at line 1883 of file activity_actor_definitions.h.
Referenced by serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp