Cataclysm DDA: inventory_selector_preset Class Reference
inventory_selector_preset Class Reference
#include <inventory_ui.h>
Classes
class cell_t
Public Member Functions
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool is_shown (const item_location &) const
Does this entry satisfy the basic preset conditions?
virtual std::string get_denial (const item_location &) const
The reason why this entry cannot be selected.
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Public Attributes
inventory_selector_save_state * save_state = nullptr
Protected Member Functions
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Private Attributes
std::vector< cell_t > cells
Detailed Description
Definition at line 219 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_selector_preset()
inventory_selector_preset::inventory_selector_preset ()
Definition at line 674 of file inventory_ui.cpp.
 {
     append_cell(
     std::function<std::string( const inventory_entry & )>( [ this ]( const inventory_entry & entry ) {
         return get_caption( entry );
     } ) );
 }
References append_cell(), and get_caption().
~inventory_selector_preset()
virtual inventory_selector_preset::~inventory_selector_preset () virtual default
Member Function Documentation
append_cell() [1/2]
void inventory_selector_preset::append_cell (const std::function< std::string(const inventory_entry &)> & func, const std::string & title = std::string(), const std::string & stub = std::string()) protected
Definition at line 806 of file inventory_ui.cpp.
 {
     const auto iter = std::find_if( cells.begin(), cells.end(), [ &title ]( const cell_t &cell ) {
         return cell.title == title;
     } );
     if( iter != cells.end() ) {
         debugmsg( "Tried to append a duplicate cell \"%s\": ignored.", title.c_str() );
         return;
     }
     cells.emplace_back( func, title, stub );
 }
References cells, debugmsg, and music::title.
append_cell() [2/2]
void inventory_selector_preset::append_cell (const std::function< std::string(const item_location &)> & func, const std::string & title = std::string(), const std::string & stub = std::string()) protected
Append a new cell to the preset.
Parameters
func The function that returns text for the cell.
title Title of the cell.
stub The cell won't be "revealed" if it contains only this value
Definition at line 795 of file inventory_ui.cpp.
 {
     // Don't capture by reference here. The func should be able to die earlier than the object itself
     append_cell( std::function<std::string( const inventory_entry & )>( [ func ](
     const inventory_entry & entry ) {
         return func( entry.any_item() );
     } ), title, stub );
 }
References inventory_entry::any_item(), and music::title.
Referenced by activatable_inventory_preset::activatable_inventory_preset(), armor_inventory_preset::armor_inventory_preset(), bionic_install_preset::bionic_install_preset(), bionic_install_surgeon_preset::bionic_install_surgeon_preset(), change_sprite_inventory_preset::change_sprite_inventory_preset(), comestible_inventory_preset::comestible_inventory_preset(), disassemble_inventory_preset::disassemble_inventory_preset(), ereader_inventory_preset::ereader_inventory_preset(), gunmod_inventory_preset::gunmod_inventory_preset(), gunmod_remove_inventory_preset::gunmod_remove_inventory_preset(), inventory_selector_preset(), liquid_inventory_selector_preset::liquid_inventory_selector_preset(), read_inventory_preset::read_inventory_preset(), repair_inventory_preset::repair_inventory_preset(), salvage_inventory_preset::salvage_inventory_preset(), select_ammo_inventory_preset::select_ammo_inventory_preset(), trade_preset::trade_preset(), and weapon_inventory_preset::weapon_inventory_preset().
cat_sort_compare()
bool inventory_selector_preset::cat_sort_compare (const inventory_entry & lhs, const inventory_entry & rhs) const virtual
Reimplemented in trade_preset.
Definition at line 692 of file inventory_ui.cpp.
 {
     return *lhs.get_category_ptr() < *rhs.get_category_ptr();
 }
References inventory_entry::get_category_ptr().
collate_entries()
bool inventory_selector_preset::collate_entries () const inline
Definition at line 268 of file inventory_ui.h.
{
             return _collate_entries;
         }
References _collate_entries.
Referenced by inventory_column::collate_entries(), and inventory_column::get_entry_indent().
get_caption()
std::string inventory_selector_preset::get_caption (const inventory_entry & entry) const protected virtual
Text of the first column (default: item name)
Reimplemented in selection_column_preset.
Definition at line 713 of file inventory_ui.cpp.
 {
     size_t count = entry.get_stack_size();
     std::string disp_name;
     if( entry.any_item()->is_money() ) {
         disp_name = entry.any_item()->display_money( count, entry.any_item()->ammo_remaining() );
     } else if( entry.is_collation_header() && entry.any_item()->count_by_charges() ) {
         item temp( *entry.any_item() );
         temp.charges = entry.get_total_charges();
         disp_name = temp.display_name();
         count = 1;
     } else {
         disp_name = entry.any_item()->display_name( count );
     }
     return ( count > 1 ) ? string_format( "%d %s", count, disp_name ) : disp_name;
 }
References item::ammo_remaining(), inventory_entry::any_item(), item::count_by_charges(), item::display_money(), item::display_name(), inventory_entry::get_stack_size(), inventory_entry::get_total_charges(), inventory_entry::is_collation_header(), item::is_money(), string_format(), and temp.
Referenced by inventory_selector_preset().
get_cell_text()
std::string inventory_selector_preset::get_cell_text (const inventory_entry & entry, size_t cell_index) const
Text in the cell.
Definition at line 736 of file inventory_ui.cpp.
 {
     if( cell_index >= cells.size() ) {
         debugmsg( "Invalid cell index %d.", cell_index );
         return "it's a bug!";
     }
     if( !entry ) {
         return std::string();
     } else if( entry.is_item() ) {
         std::string text = cells[cell_index].get_text( entry );
         const item &actual_item = *entry.locations.front();
         const std::string info_display = get_option<std::string>( "DETAILED_CONTAINERS" );
         // if we want no additional info skip this
         if( info_display != "NONE" ) {
             // if we want additional info for all items or it is worn then add the additional info
             if( info_display == "ALL" || ( info_display == "WORN" &&
                                            is_worn_id( entry.get_category_ptr()->get_id() ) &&
                                            actual_item.is_worn_by_player() ) ) {
                 if( cell_index == 0 && !text.empty() &&
                     actual_item.is_container() && actual_item.has_unrestricted_pockets() ) {
                     const units::volume total_capacity = actual_item.get_total_capacity( true );
                     const units::mass total_capacity_weight = actual_item.get_total_weight_capacity( true );
                     const units::length max_containable_length = actual_item.max_containable_length( true );
                     const units::volume actual_capacity = actual_item.get_total_contained_volume( true );
                     const units::mass actual_capacity_weight = actual_item.get_total_contained_weight( true );
                     container_data container_data = {
                         actual_capacity,
                         total_capacity,
                         actual_capacity_weight,
                         total_capacity_weight,
                         max_containable_length
                     };
                     std::string formatted_string = container_data.to_formatted_string( false );
                     text = text + string_format( " %s", formatted_string );
                 }
             }
         }
         return text;
     } else if( cell_index != 0 ) {
         return replace_colors( cells[cell_index].title );
     } else {
         return entry.get_category_ptr()->name_header();
     }
 }
References cells, debugmsg, inventory_entry::get_category_ptr(), item_category::get_id(), item::get_total_capacity(), item::get_total_contained_volume(), item::get_total_contained_weight(), item::get_total_weight_capacity(), item::has_unrestricted_pockets(), item::is_container(), inventory_entry::is_item(), item::is_worn_by_player(), anonymous_namespace{inventory_ui.cpp}::is_worn_id(), inventory_entry::locations, item::max_containable_length(), item_category::name_header(), replace_colors(), string_format(), music::title, and container_data::to_formatted_string().
Referenced by inventory_entry::make_entry_cell_cache().
get_cells_count()
size_t inventory_selector_preset::get_cells_count () const inline
Number of cells in the preset.
Definition at line 249 of file inventory_ui.h.
{
             return cells.size();
         }
References cells.
Referenced by inventory_column::inventory_column(), inventory_entry::make_entry_cell_cache(), and inventory_column::visible().
get_checking_components()
bool inventory_selector_preset::get_checking_components () const inline
Whether items should make new stacks if components differ.
Definition at line 253 of file inventory_ui.h.
{
             return check_components;
         }
References check_components.
get_color()
nc_color inventory_selector_preset::get_color (const inventory_entry & entry) const virtual
Color that will be used to display the entry string.
Reimplemented in selection_column_preset, and read_inventory_preset.
Definition at line 698 of file inventory_ui.cpp.
 {
     return entry.is_item() ? entry.any_item()->color_in_inventory() : c_magenta;
 }
References inventory_entry::any_item(), c_magenta, item::color_in_inventory(), and inventory_entry::is_item().
Referenced by selection_column_preset::get_color(), and inventory_entry::make_entry_cell_cache().
get_denial() [1/2]
std::string inventory_selector_preset::get_denial (const inventory_entry & entry) const
Definition at line 731 of file inventory_ui.cpp.
 {
     return entry.is_item() ? get_denial( entry.any_item() ) : std::string();
 }
References inventory_entry::any_item(), get_denial(), and inventory_entry::is_item().
get_denial() [2/2]
virtual std::string inventory_selector_preset::get_denial (const item_location &) const inline virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented in trade_preset, bionic_install_surgeon_preset, bionic_install_preset, attach_veh_tool_inventory_preset, attach_molle_inventory_preset, saw_stock_inventory_preset, saw_barrel_inventory_preset, weapon_inventory_preset, ebookread_inventory_preset, read_inventory_preset, ereader_inventory_preset, gunmod_remove_inventory_preset, gunmod_inventory_preset, activatable_inventory_preset, comestible_inventory_preset, disassemble_inventory_preset, pickup_inventory_preset, take_off_inventory_preset, wear_inventory_preset, haul_selector_preset, and inventory_holster_preset.
Definition at line 234 of file inventory_ui.h.
{
             return std::string();
         }
Referenced by inventory_entry::cache_denial(), get_denial(), comestible_inventory_preset::get_denial(), and trade_preset::get_denial().
get_filter()
std::function< bool(const inventory_entry &)> inventory_selector_preset::get_filter (const std::string & filter) const virtual
Reimplemented in read_inventory_preset.
Definition at line 703 of file inventory_ui.cpp.
 {
     auto item_filter = basic_item_filter( filter );
     return [item_filter]( const inventory_entry & e ) {
         return item_filter( *e.any_item() );
     };
 }
References basic_item_filter(), and filter.
Referenced by read_inventory_preset::get_filter().
get_pocket_type()
pocket_type inventory_selector_preset::get_pocket_type () const inline
Definition at line 257 of file inventory_ui.h.
{
             return _pk_type;
         }
References _pk_type.
Referenced by inventory_selector::add_contained_items().
indent_entries()
bool inventory_selector_preset::indent_entries () const inline
Definition at line 264 of file inventory_ui.h.
{
             return _indent_entries;
         }
References _indent_entries.
Referenced by inventory_column::collate(), inventory_column::collated_sort_compare(), inventory_column::get_entry_indent(), and inventory_column::indent_entries().
is_shown()
virtual bool inventory_selector_preset::is_shown (const item_location &) const inline virtual
Does this entry satisfy the basic preset conditions?
Reimplemented in trade_preset, inventory_filter_preset, smokable_selector_preset, liquid_inventory_selector_preset, select_ammo_inventory_preset, change_sprite_inventory_preset, bionic_install_surgeon_preset, bionic_install_preset, repair_inventory_preset, salvage_inventory_preset, attach_veh_tool_inventory_preset, attach_molle_inventory_preset, saw_stock_inventory_preset, saw_barrel_inventory_preset, holster_inventory_preset, weapon_inventory_preset, steal_inventory_preset, read_inventory_preset, ereader_inventory_preset, gunmod_remove_inventory_preset, gunmod_inventory_preset, activatable_inventory_preset, comestible_filtered_inventory_preset, comestible_inventory_preset, disassemble_inventory_preset, pickup_inventory_preset, take_off_inventory_preset, wear_inventory_preset, haul_selector_preset, and inventory_holster_preset.
Definition at line 226 of file inventory_ui.h.
{
             return true;
         }
Referenced by inventory_selector::add_entry(), inventory_selector::add_entry_rec(), anonymous_namespace{inventory_ui.cpp}::get_topmost_parent(), trade_preset::is_shown(), and anonymous_namespace{inventory_ui.cpp}::path_to_top().
is_stub_cell()
bool inventory_selector_preset::is_stub_cell (const inventory_entry & entry, size_t cell_index) const
Returns
Whether the cell is a stub
Definition at line 785 of file inventory_ui.cpp.
 {
     if( !entry.is_item() ) {
         return false;
     }
     const std::string &text = entry.get_entry_cell_cache( *this ).text[ cell_index ];
     return text.empty() || text == cells[cell_index].stub;
 }
References cells, inventory_entry::get_entry_cell_cache(), inventory_entry::is_item(), and inventory_entry::entry_cell_cache_t::text.
sort_compare()
bool inventory_selector_preset::sort_compare (const inventory_entry & lhs, const inventory_entry & rhs) const virtual
Whether the first item is considered to go before the second.
Reimplemented in select_ammo_inventory_preset, read_inventory_preset, gunmod_inventory_preset, and comestible_inventory_preset.
Definition at line 682 of file inventory_ui.cpp.
 {
     auto const sort_key = []( inventory_entry const & e ) {
         return std::make_tuple( *e.cached_name, e.contents_count, *e.cached_name_full,
                                 e.any_item()->link_sort_key(), e.generation );
     };
     return localized_compare( sort_key( lhs ), sort_key( rhs ) );
 }
References localized_compare.
Referenced by inventory_column::collated_sort_compare(), inventory_column::indented_sort_compare(), comestible_inventory_preset::sort_compare(), gunmod_inventory_preset::sort_compare(), read_inventory_preset::sort_compare(), and select_ammo_inventory_preset::sort_compare().
Member Data Documentation
_collate_entries
bool inventory_selector_preset::_collate_entries = false protected
Definition at line 293 of file inventory_ui.h.
Referenced by activatable_inventory_preset::activatable_inventory_preset(), collate_entries(), comestible_inventory_preset::comestible_inventory_preset(), ereader_inventory_preset::ereader_inventory_preset(), and select_ammo_inventory_preset::select_ammo_inventory_preset().
_indent_entries
bool inventory_selector_preset::_indent_entries = true protected
Definition at line 292 of file inventory_ui.h.
Referenced by comestible_inventory_preset::comestible_inventory_preset(), indent_entries(), repair_inventory_preset::repair_inventory_preset(), and select_ammo_inventory_preset::select_ammo_inventory_preset().
_pk_type
pocket_type inventory_selector_preset::_pk_type = pocket_type::CONTAINER protected
Definition at line 295 of file inventory_ui.h.
Referenced by get_pocket_type(), and pickup_inventory_preset::pickup_inventory_preset().
cells
std::vector<cell_t> inventory_selector_preset::cells private
Definition at line 316 of file inventory_ui.h.
Referenced by append_cell(), inventory_column::draw(), inventory_column::expand_to_fit(), get_cell_text(), get_cells_count(), inventory_column::get_cells_width(), is_stub_cell(), inventory_column::reset_width(), inventory_column::set_width(), and inventory_column::visible_cells().
check_components
bool inventory_selector_preset::check_components = false protected
Definition at line 289 of file inventory_ui.h.
Referenced by disassemble_inventory_preset::disassemble_inventory_preset(), and get_checking_components().
save_state
inventory_selector_save_state* inventory_selector_preset::save_state = nullptr
Definition at line 272 of file inventory_ui.h.
Referenced by game_menus::inv::common(), game_menus::inv::pickup(), pickup_inventory_preset::pickup_inventory_preset(), trade_preset::trade_preset(), and inventory_selector::~inventory_selector().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp