Cataclysm DDA: jmapgen_make_rubble Class Reference
jmapgen_make_rubble Class Reference
Calls map::make_rubble to create rubble and destroy the existing terrain/furniture.
Public Member Functions
jmapgen_make_rubble (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
mapgen_value< furn_id > rubble_type = mapgen_value<furn_id>(furn_f_rubble)
bool items = false
mapgen_value< ter_id > floor_type = mapgen_value<ter_id>(ter_t_dirt)
bool overwrite = false
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Calls map::make_rubble to create rubble and destroy the existing terrain/furniture.
See map::make_rubble for explanation of the parameters.
Definition at line 3105 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_make_rubble()
jmapgen_make_rubble::jmapgen_make_rubble (const JsonObject & jsi, const std::string_view) inline
Definition at line 3112 of file mapgen.cpp.
{
             if( jsi.has_member( "rubble_type" ) ) {
                 rubble_type = mapgen_value<furn_id>( jsi.get_member( "rubble_type" ) );
             }
             jsi.read( "items", items );
             if( jsi.has_member( "floor_type" ) ) {
                 floor_type = mapgen_value<ter_id>( jsi.get_member( "floor_type" ) );
             }
             jsi.read( "overwrite", overwrite );
         }
References floor_type, JsonObject::get_member(), JsonObject::has_member(), items, mapgen_defer::jsi, overwrite, JsonObject::read(), and rubble_type.
Member Function Documentation
apply()
void jmapgen_make_rubble::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 3122 of file mapgen.cpp.
{
             furn_id chosen_rubble_type = rubble_type.get( dat );
             ter_id chosen_floor_type = floor_type.get( dat );
             if( chosen_rubble_type.id().is_null() ) {
                 return;
             }
             if( chosen_floor_type.id().is_null() ) {
                 debugmsg( "null floor type when making rubble" );
                 chosen_floor_type = ter_t_dirt;
             }
             dat.m.make_rubble( tripoint( x.get(), y.get(), dat.zlevel() + z.get() ),
                                chosen_rubble_type, items, chosen_floor_type, overwrite );
         }
References debugmsg, floor_type, jmapgen_int::get(), int_id< T >::id(), string_id< T >::is_null(), items, mapgendata::m, map::make_rubble(), overwrite, rubble_type, ter_t_dirt, tripoint, and mapgendata::zlevel().
check()
void jmapgen_make_rubble::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 3137 of file mapgen.cpp.
{
             rubble_type.check( oter_name, parameters );
             floor_type.check( oter_name, parameters );
         }
References floor_type, and rubble_type.
Member Data Documentation
floor_type
mapgen_value<ter_id> jmapgen_make_rubble::floor_type = mapgen_value<ter_id>(ter_t_dirt)
Definition at line 3110 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_make_rubble().
items
bool jmapgen_make_rubble::items = false
Definition at line 3109 of file mapgen.cpp.
Referenced by apply(), and jmapgen_make_rubble().
overwrite
bool jmapgen_make_rubble::overwrite = false
Definition at line 3111 of file mapgen.cpp.
Referenced by apply(), and jmapgen_make_rubble().
rubble_type
mapgen_value<furn_id> jmapgen_make_rubble::rubble_type = mapgen_value<furn_id>(furn_f_rubble)
Definition at line 3108 of file mapgen.cpp.
Referenced by apply(), check(), and jmapgen_make_rubble().
The documentation for this class was generated from the following file:
src/mapgen.cpp