Cataclysm DDA: spellcasting_callback Class Reference
spellcasting_callback Class Reference
Public Member Functions
spellcasting_callback (std::vector< spell * > &spells, bool casting_ignore)
bool key (const input_context &ctxt, const input_event &event, int entnum, uilist *menu) override
void refresh (uilist *menu) override
Public Member Functions inherited from uilist_callback
virtual void select (uilist *)
After a new item is selected, call this once.
virtual ~uilist_callback ()=default
Public Attributes
const std::set< int > reserved_invlets { 'I', '=', '*' }
bool casting_ignore
Private Member Functions
void spell_info_text (const spell &sp, int width)
void draw_spell_info (const uilist *menu)
Private Attributes
int selected_sp = 0
int scroll_pos = 0
std::vector< std::string > info_txt
std::vector< spell * > known_spells
Detailed Description
Definition at line 2292 of file magic.cpp.
Constructor & Destructor Documentation
spellcasting_callback()
spellcasting_callback::spellcasting_callback (std::vector< spell * > & spells, bool casting_ignore) inline
Definition at line 2306 of file magic.cpp.
                                                      : known_spells( spells ),
             casting_ignore( casting_ignore ) {}
Member Function Documentation
draw_spell_info()
void spellcasting_callback::draw_spell_info (const uilist * menu) private
Definition at line 2667 of file magic.cpp.
 {
     const int h_offset = menu->w_width - menu->pad_right + 1;
     int row = 1;
     nc_color clr = c_light_gray;
     for( int line = scroll_pos; row < menu->w_height - 1 &&
          line < static_cast<int>( info_txt.size() ); row++, line++ ) {
         print_colored_text( menu->window, point( h_offset + 1, row ), clr, c_light_gray, info_txt[line] );
     }
 }
References c_light_gray, info_txt, line, uilist::pad_right, print_colored_text(), scroll_pos, uilist::w_height, uilist::w_width, and uilist::window.
Referenced by refresh().
key()
bool spellcasting_callback::key (const input_context & ctxt, const input_event & event, int entnum, uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 2309 of file magic.cpp.
{
             const std::string &action = ctxt.input_to_action( event );
             if( action == "CAST_IGNORE" ) {
                 casting_ignore = !casting_ignore;
                 return true;
             } else if( action == "CHOOSE_INVLET" ) {
                 int invlet = 0;
                 invlet = popup_getkey( _( "Choose a new hotkey for this spell." ) );
                 if( inv_chars.valid( invlet ) ) {
                     const bool invlet_set =
                         get_player_character().magic->set_invlet( known_spells[entnum]->id(), invlet, reserved_invlets );
                     if( !invlet_set ) {
                         popup( _( "Hotkey already used." ) );
                     } else {
                         popup( _( "%c set.  Close and reopen spell menu to refresh list with changes." ),
                                invlet );
                     }
                 } else {
                     popup( _( "Hotkey removed." ) );
                     get_player_character().magic->rem_invlet( known_spells[entnum]->id() );
                 }
                 return true;
             } else if( action == "SCROLL_UP_SPELL_MENU" || action == "SCROLL_DOWN_SPELL_MENU" ) {
                 scroll_pos += action == "SCROLL_DOWN_SPELL_MENU" ? 1 : -1;
             } else if( action == "SCROLL_FAVORITE" ) {
                 get_player_character().magic->toggle_favorite( known_spells[entnum]->id() );
                 reflesh_favorite( menu, known_spells );
             }
             return false;
         }
References _, action, casting_ignore, get_player_character(), input_context::input_to_action(), inv_chars, known_spells, Character::magic, popup(), popup_getkey(), reflesh_favorite(), reserved_invlets, scroll_pos, and invlet_wrapper::valid().
refresh()
void spellcasting_callback::refresh (uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 2341 of file magic.cpp.
{
             const std::string space( menu->pad_right - 2, ' ' );
             mvwputch( menu->window, point( menu->w_width - menu->pad_right, 0 ), c_magenta, LINE_OXXX );
             mvwputch( menu->window, point( menu->w_width - menu->pad_right, menu->w_height - 1 ), c_magenta,
                       LINE_XXOX );
             for( int i = 1; i < menu->w_height - 1; i++ ) {
                 mvwputch( menu->window, point( menu->w_width - menu->pad_right, i ), c_magenta, LINE_XOXO );
                 mvwputch( menu->window, point( menu->w_width - menu->pad_right + 1, i ), menu->text_color, space );
             }
             std::string ignore_string = casting_ignore ? _( "Ignore Distractions" ) :
                                         _( "Popup Distractions" );
             mvwprintz( menu->window, point( menu->w_width - menu->pad_right + 2, 0 ),
                        casting_ignore ? c_red : c_light_green, string_format( "%s %s", "[I]", ignore_string ) );
             const std::string assign_letter = _( "Assign Hotkey [=]" );
             mvwprintz( menu->window, point( menu->w_width - assign_letter.length() - 1, 0 ), c_yellow,
                        assign_letter );
             if( menu->selected >= 0 && static_cast<size_t>( menu->selected ) < known_spells.size() ) {
                 if( info_txt.empty() || selected_sp != menu->selected ) {
                     info_txt.clear();
                     spell_info_text( *known_spells[menu->selected], menu->pad_right - 4 );
                     selected_sp = menu->selected;
                     scroll_pos = 0;
                 }
                 if( scroll_pos > static_cast<int>( info_txt.size() ) - ( menu->w_height - 2 ) ) {
                     scroll_pos = info_txt.size() - ( menu->w_height - 2 );
                 }
                 if( scroll_pos < 0 ) {
                     scroll_pos = 0;
                 }
                 scrollbar()
                 .offset_x( menu->w_width - 1 )
                 .offset_y( 1 )
                 .content_size( info_txt.size() )
                 .viewport_pos( scroll_pos )
                 .viewport_size( menu->w_height - 2 )
                 .apply( menu->window );
                 draw_spell_info( menu );
             }
             wnoutrefresh( menu->window );
         }
References _, scrollbar::apply(), c_light_green, c_magenta, c_red, c_yellow, casting_ignore, scrollbar::content_size(), draw_spell_info(), info_txt, known_spells, LINE_OXXX, LINE_XOXO, LINE_XXOX, mvwprintz(), mvwputch(), scrollbar::offset_x(), scrollbar::offset_y(), uilist::pad_right, scroll_pos, uilist::selected, selected_sp, keycode::space, spell_info_text(), string_format(), uilist::text_color, scrollbar::viewport_pos(), scrollbar::viewport_size(), uilist::w_height, uilist::w_width, uilist::window, and catacurses::wnoutrefresh().
spell_info_text()
void spellcasting_callback::spell_info_text (const spell & sp, int width) private
Definition at line 2444 of file magic.cpp.
 {
     Character &pc = get_player_character();
     info_txt.emplace_back( colorize( sp.spell_class() == trait_NONE ? _( "Classless" ) :
                                      sp.spell_class()->name(), c_yellow ) );
     for( const std::string &line : foldstring( sp.description(), width ) ) {
         info_txt.emplace_back( colorize( line, c_light_gray ) );
     }
     info_txt.emplace_back( );
     for( const std::string &line : foldstring( sp.enumerate_spell_data( pc ), width ) ) {
         info_txt.emplace_back( colorize( line, c_light_gray ) );
     }
     info_txt.emplace_back( );
     auto columnize = [&width]( const std::string & col1, const std::string & col2 ) {
         std::string line = col1;
         int pad = clamp<int>( width / 2 - utf8_width( line, true ), 1, width / 2 );
         line.append( pad, ' ' );
         line.append( col2 );
         return line;
     };
     // Calculates temp_level_adjust from EoC, saves it to the spell for later use, and prepares to display the result
     int temp_level_adjust = sp.get_temp_level_adjustment();
     std::string temp_level_adjust_string;
     if( temp_level_adjust < 0 ) {
         temp_level_adjust_string = " (-" + std::to_string( -temp_level_adjust ) + ")";
     } else if( temp_level_adjust > 0 ) {
         temp_level_adjust_string = " (+" + std::to_string( temp_level_adjust ) + ")";
     }
     info_txt.emplace_back(
         colorize( columnize( string_format( "%s: %d%s%s", _( "Spell Level" ), sp.get_effective_level(),
                                             sp.is_max_level( pc ) ? _( " (MAX)" ) : "", temp_level_adjust_string.c_str() ),
                              string_format( "%s: %d", _( "Max Level" ), sp.get_max_level( pc ) ) ), c_light_gray ) );
     info_txt.emplace_back(
         colorize( columnize( sp.colorized_fail_percent( pc ),
                              string_format( "%s: %d", _( "Difficulty" ), sp.get_difficulty( pc ) ) ), c_light_gray ) );
     info_txt.emplace_back(
         colorize( columnize( string_format( "%s: %s", _( "Current Exp" ),
                                             colorize( std::to_string( sp.xp() ), c_light_green ) ),
                              string_format( "%s: %s", _( "to Next Level" ),
                                             colorize( std::to_string( sp.exp_to_next_level() ), c_light_green ) ) ), c_light_gray ) );
     info_txt.emplace_back( );
     const bool cost_encumb = sp.energy_cost_encumbered( pc );
     const bool is_psi = sp.has_flag( spell_flag::PSIONIC );
     if( is_psi ) {
         std::string cost_string = cost_encumb ? _( "Channeling Cost (impeded)" ) : _( "Channeling Cost" );
         std::string energy_cur = sp.energy_source() == magic_energy_type::hp ? "" :
                                  string_format( _( " (%s current)" ), sp.energy_cur_string( pc ) );
         if( !pc.magic->has_enough_energy( pc, sp ) ) {
             cost_string = colorize( _( "Not Enough Stamina" ), c_red );
             energy_cur.clear();
         }
         info_txt.emplace_back(
             colorize( string_format( "%s: %s %s%s", cost_string, sp.energy_cost_string( pc ),
                                      sp.energy_string(), energy_cur ), c_light_gray ) );
     } else {
         std::string cost_string = cost_encumb ? _( "Casting Cost (impeded)" ) : _( "Casting Cost" );
         std::string energy_cur = sp.energy_source() == magic_energy_type::hp ? "" :
                                  string_format( _( " (%s current)" ), sp.energy_cur_string( pc ) );
         if( !pc.magic->has_enough_energy( pc, sp ) ) {
             cost_string = colorize( _( "Not Enough Energy" ), c_red );
             energy_cur.clear();
         }
         info_txt.emplace_back(
             colorize( string_format( "%s: %s %s%s", cost_string, sp.energy_cost_string( pc ),
                                      sp.energy_string(), energy_cur ), c_light_gray ) );
     };
     const bool c_t_encumb = sp.casting_time_encumbered( pc );
     if( is_psi ) {
         info_txt.emplace_back(
             colorize( string_format( "%s: %s",
                                      c_t_encumb ? _( "Channeling Time (impeded)" ) : _( "Channeling Time" ),
                                      moves_to_string( sp.casting_time( pc ) ) ), c_t_encumb  ? c_red : c_light_gray ) );
         info_txt.emplace_back( );
     } else {
         info_txt.emplace_back(
             colorize( string_format( "%s: %s", c_t_encumb ? _( "Casting Time (impeded)" ) : _( "Casting Time" ),
                                      moves_to_string( sp.casting_time( pc ) ) ), c_t_encumb  ? c_red : c_light_gray ) );
         info_txt.emplace_back( );
     };
     std::string targets;
     if( sp.is_valid_target( spell_target::none ) ) {
         targets = _( "self" );
     } else {
         targets = sp.enumerate_targets();
     }
     info_txt.emplace_back(
         colorize( string_format( "%s: %s", _( "Valid Targets" ), targets ), c_light_gray ) );
     info_txt.emplace_back( );
     std::string target_ids;
     target_ids = sp.list_targeted_monster_names();
     if( !target_ids.empty() ) {
         for( const std::string &line :
              foldstring( string_format( _( "Only affects the monsters: %s" ), target_ids ), width ) ) {
             info_txt.emplace_back( colorize( line, c_light_gray ) );
         }
         info_txt.emplace_back( );
     }
     const int damage = sp.damage( pc );
     std::string damage_string;
     std::string aoe_string;
     // if it's any type of attack spell, the stats are normal.
     if( sp.effect() == "attack" ) {
         if( damage > 0 ) {
             std::string dot_string;
             if( sp.damage_dot( pc ) != 0 ) {
                 //~ amount of damage per second, abbreviated
                 dot_string = string_format( _( ", %d/sec" ), sp.damage_dot( pc ) );
             }
             damage_string = string_format( "%s: %s %s%s", _( "Damage" ), sp.damage_string( pc ),
                                            sp.damage_type_string(), dot_string );
             damage_string = colorize( damage_string, sp.damage_type_color() );
         } else if( damage < 0 ) {
             damage_string = string_format( "%s: %s", _( "Healing" ), colorize( sp.damage_string( pc ),
                                            c_light_green ) );
         }
         if( sp.aoe( pc ) > 0 ) {
             std::string aoe_string_temp = _( "Spell Radius" );
             std::string degree_string;
             if( sp.shape() == spell_shape::cone ) {
                 aoe_string_temp = _( "Cone Arc" );
                 degree_string = _( "degrees" );
             } else if( sp.shape() == spell_shape::line ) {
                 aoe_string_temp = _( "Line Width" );
             }
             aoe_string = string_format( "%s: %d %s", aoe_string_temp, sp.aoe( pc ), degree_string );
         }
     } else if( sp.effect() == "short_range_teleport" ) {
         if( sp.aoe( pc ) > 0 ) {
             aoe_string = string_format( "%s: %d", _( "Variance" ), sp.aoe( pc ) );
         }
     } else if( sp.effect() == "spawn_item" ) {
         if( sp.has_flag( spell_flag::SPAWN_GROUP ) ) {
             // todo: more user-friendly presentation
             damage_string = string_format( _( "Spawn item group %1$s %2$d times" ), sp.effect_data(),
                                            sp.damage( pc ) );
         } else {
             damage_string = string_format( "%s %d %s", _( "Spawn" ), sp.damage( pc ),
                                            item::nname( itype_id( sp.effect_data() ), sp.damage( pc ) ) );
         }
     } else if( sp.effect() == "summon" ) {
         std::string monster_name = "FIXME";
         if( sp.has_flag( spell_flag::SPAWN_GROUP ) ) {
             // TODO: Get a more user-friendly group name
             if( MonsterGroupManager::isValidMonsterGroup( mongroup_id( sp.effect_data() ) ) ) {
                 monster_name = "from " + sp.effect_data();
             } else {
                 debugmsg( "Unknown monster group: %s", sp.effect_data() );
             }
         } else {
             monster_name = monster( mtype_id( sp.effect_data() ) ).get_name( );
         }
         damage_string = string_format( "%s %d %s", _( "Summon" ), sp.damage( pc ), monster_name );
         aoe_string = string_format( "%s: %d", _( "Spell Radius" ), sp.aoe( pc ) );
     } else if( sp.effect() == "targeted_polymorph" ) {
         std::string monster_name = sp.effect_data();
         if( sp.has_flag( spell_flag::POLYMORPH_GROUP ) ) {
             // TODO: Get a more user-friendly group name
             if( MonsterGroupManager::isValidMonsterGroup( mongroup_id( sp.effect_data() ) ) ) {
                 monster_name = _( "random creature" );
             } else {
                 debugmsg( "Unknown monster group: %s", sp.effect_data() );
             }
         } else if( monster_name.empty() ) {
             monster_name = _( "random creature" );
         } else {
             monster_name = mtype_id( sp.effect_data() )->nname();
         }
         damage_string = string_format( _( "Targets under: %dhp become a %s" ), sp.damage( pc ),
                                        monster_name );
     } else if( sp.effect() == "ter_transform" ) {
         aoe_string = string_format( "%s: %s", _( "Spell Radius" ), sp.aoe_string( pc ) );
     } else if( sp.effect() == "banishment" ) {
         damage_string = string_format( "%s: %s %s", _( "Damage" ), sp.damage_string( pc ),
                                        sp.damage_type_string() );
         if( sp.aoe( pc ) > 0 ) {
             aoe_string = string_format( _( "Spell Radius: %d" ), sp.aoe( pc ) );
         }
     }
     // Range / AOE in two columns
     info_txt.emplace_back( colorize( string_format( "%s: %s", _( "Range" ),
                                      sp.range( pc ) <= 0 ? _( "self" ) : std::to_string( sp.range( pc ) ) ), c_light_gray ) );
     info_txt.emplace_back( colorize( aoe_string, c_light_gray ) );
     // One line for damage / healing / spawn / summon effect
     info_txt.emplace_back( colorize( damage_string, c_light_gray ) );
     // todo: damage over time here, when it gets implemented
     // Show duration for spells that endure
     if( sp.duration( pc ) > 0 || sp.has_flag( spell_flag::PERMANENT ) ||
         sp.has_flag( spell_flag::PERMANENT_ALL_LEVELS ) ) {
         info_txt.emplace_back(
             colorize( string_format( "%s: %s", _( "Duration" ), sp.duration_string( pc ) ), c_light_gray ) );
     }
     if( sp.has_components() ) {
         if( !sp.components().get_components().empty() ) {
             for( const std::string &line : sp.components().get_folded_components_list(
                      width - 2, c_light_gray, pc.crafting_inventory( pc.pos(), 0, false ), return_true<item> ) ) {
                 info_txt.emplace_back( line );
             }
         }
         if( !( sp.components().get_tools().empty() && sp.components().get_qualities().empty() ) ) {
             for( const std::string &line : sp.components().get_folded_tools_list(
                      width - 2, c_light_gray, pc.crafting_inventory( pc.pos(), 0, false ) ) ) {
                 info_txt.emplace_back( line );
             }
         }
     }
 }
References _, spell::aoe(), spell::aoe_string(), c_light_gray, c_light_green, c_red, c_yellow, spell::casting_time(), spell::casting_time_encumbered(), colorize(), spell::colorized_fail_percent(), spell::components(), cone, Character::crafting_inventory(), spell::damage(), spell::damage_dot(), spell::damage_string(), spell::damage_type_color(), spell::damage_type_string(), debugmsg, spell::description(), spell::duration(), spell::duration_string(), spell::effect(), spell::effect_data(), spell::energy_cost_encumbered(), spell::energy_cost_string(), spell::energy_cur_string(), spell::energy_source(), spell::energy_string(), spell::enumerate_spell_data(), spell::enumerate_targets(), spell::exp_to_next_level(), foldstring(), requirement_data::get_components(), spell::get_difficulty(), spell::get_effective_level(), requirement_data::get_folded_components_list(), requirement_data::get_folded_tools_list(), spell::get_max_level(), monster::get_name(), get_player_character(), requirement_data::get_qualities(), spell::get_temp_level_adjustment(), requirement_data::get_tools(), spell::has_components(), spell::has_flag(), hp, info_txt, spell::is_max_level(), spell::is_valid_target(), MonsterGroupManager::isValidMonsterGroup(), line, spell::list_targeted_monster_names(), Character::magic, mongroup_id, moves_to_string(), mtype_id, mutation_branch::name(), item::nname(), none, PERMANENT, PERMANENT_ALL_LEVELS, POLYMORPH_GROUP, Creature::pos(), PSIONIC, spell::range(), spell::shape(), SPAWN_GROUP, spell::spell_class(), string_format(), to_string(), trait_NONE, utf8_width(), and spell::xp().
Referenced by refresh().
Member Data Documentation
casting_ignore
bool spellcasting_callback::casting_ignore
Definition at line 2304 of file magic.cpp.
Referenced by key(), and refresh().
info_txt
std::vector<std::string> spellcasting_callback::info_txt private
Definition at line 2297 of file magic.cpp.
Referenced by draw_spell_info(), refresh(), and spell_info_text().
known_spells
std::vector<spell *> spellcasting_callback::known_spells private
Definition at line 2298 of file magic.cpp.
Referenced by key(), and refresh().
reserved_invlets
const std::set<int> spellcasting_callback::reserved_invlets { 'I', '=', '*' }
Definition at line 2303 of file magic.cpp.
Referenced by key(), and known_magic::select_spell().
scroll_pos
int spellcasting_callback::scroll_pos = 0 private
Definition at line 2296 of file magic.cpp.
Referenced by draw_spell_info(), key(), and refresh().
selected_sp
int spellcasting_callback::selected_sp = 0 private
Definition at line 2295 of file magic.cpp.
Referenced by refresh().
The documentation for this class was generated from the following file:
src/magic.cpp