Cataclysm DDA: firstaid_activity_actor Class Reference
firstaid_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
firstaid_activity_actor ()=default
firstaid_activity_actor (int moves, std::string name, character_id patientID)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves
std::string name
character_id patientID
Detailed Description
Definition at line 1970 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
firstaid_activity_actor() [1/2]
firstaid_activity_actor::firstaid_activity_actor () default
firstaid_activity_actor() [2/2]
firstaid_activity_actor::firstaid_activity_actor (int moves, std::string name, character_id patientID) inline
Definition at line 1974 of file activity_actor_definitions.h.
                                                                                      : moves( moves ),
             name( std::move( name ) ), patientID( patientID ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> firstaid_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1985 of file activity_actor_definitions.h.
{
             return std::make_unique<firstaid_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > firstaid_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6633 of file activity_actor.cpp.
 {
     firstaid_activity_actor actor( {},  {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "moves", actor.moves );
     data.read( "name", actor.name );
     data.read( "patientID", actor.patientID );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void firstaid_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 1982 of file activity_actor_definitions.h.
 {};
finish()
void firstaid_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 6555 of file activity_actor.cpp.
 {
     static const std::string iuse_name_string( "heal" );
     item_location it = act.targets.front();
     item *used_tool = it->get_usable_item( iuse_name_string );
     if( used_tool == nullptr ) {
         debugmsg( "Lost tool used for healing" );
         act.set_to_null();
         return;
     }
     const use_function *use_fun = used_tool->get_use( iuse_name_string );
     const heal_actor *actor = dynamic_cast<const heal_actor *>( use_fun->get_actor_ptr() );
     if( actor == nullptr ) {
         debugmsg( "iuse_actor type descriptor and actual type mismatch" );
         act.set_to_null();
         return;
     }
     Character *patient = patientID == get_avatar().getID() ? &get_avatar() :
                          dynamic_cast<Character *>( g->find_npc( patientID ) );
     if( !patient ) {
         debugmsg( "Your patient can no longer be found so you stop using the %s.", name );
         act.set_to_null();
         act.values.clear();
         return;
     }
     const bodypart_id healed = bodypart_id( act.str_values[0] );
     int charges_consumed = actor->finish_using( who, *patient,
                            *used_tool, healed );
     std::list<item>used;
     if( used_tool->has_flag( flag_SINGLE_USE ) ) {
         it.remove_item();
     } else if( used_tool->is_medication() ) {
         if( !it->count_by_charges() ||
             it->use_charges( it->typeId(), charges_consumed, used, it.position() ) ) {
             it.remove_item();
         }
     } else if( used_tool->is_tool() ) {
         if( used_tool->type->charges_to_use() ) {
             it->activation_consume( charges_consumed, it.position(), &who );
         }
     }
     // Erase activity and values.
     act.set_to_null();
     act.values.clear();
     // Return to first eat or consume meds menu activity in the backlog.
     for( player_activity &backlog_act : who.backlog ) {
         if( backlog_act.id() == ACT_EAT_MENU ||
             backlog_act.id() == ACT_CONSUME_MEDS_MENU ) {
             backlog_act.auto_resume = true;
             break;
         }
     }
     // Clear the backlog of any activities that will not auto resume.
     for( auto iter = who.backlog.begin(); iter != who.backlog.end(); ) {
         if( !iter->auto_resume ) {
             iter = who.backlog.erase( iter );
         } else {
             ++iter;
         }
     }
 }
References act, ACT_CONSUME_MEDS_MENU, ACT_EAT_MENU, item::activation_consume(), player_activity::auto_resume, Character::backlog, itype::charges_to_use(), item::count_by_charges(), debugmsg, heal_actor::finish_using(), flag_SINGLE_USE, g, use_function::get_actor_ptr(), get_avatar(), item::get_usable_item(), item::get_use(), Character::getID(), item::has_flag(), player_activity::id(), item::is_medication(), item::is_tool(), name, patientID, item_location::position(), item_location::remove_item(), item::type, item::typeId(), and item::use_charges().
get_type()
activity_id firstaid_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1977 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_FIRSTAID" );
         }
References activity_id.
serialize()
void firstaid_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6622 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves", moves );
     jsout.member( "name", name );
     jsout.member( "patientID", patientID );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves, name, patientID, and JsonOut::start_object().
start()
void firstaid_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 6548 of file activity_actor.cpp.
 {
     act.moves_total = moves;
     act.moves_left = moves;
     act.name = name;
 }
References act, moves, and name.
Member Data Documentation
moves
int firstaid_activity_actor::moves private
Definition at line 1993 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
name
std::string firstaid_activity_actor::name private
Definition at line 1994 of file activity_actor_definitions.h.
Referenced by finish(), serialize(), and start().
patientID
character_id firstaid_activity_actor::patientID private
Definition at line 1995 of file activity_actor_definitions.h.
Referenced by finish(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp