Cataclysm DDA: jmapgen_remove_all Class Reference
jmapgen_remove_all Class Reference
Public Member Functions
jmapgen_remove_all (const JsonObject &, const std::string_view)
mapgen_phase phase () const override
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Additional Inherited Members
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Definition at line 3483 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_remove_all()
jmapgen_remove_all::jmapgen_remove_all (const JsonObject & , const std::string_view) inline
Definition at line 3486 of file mapgen.cpp.
{
         }
Member Function Documentation
apply()
void jmapgen_remove_all::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 3491 of file mapgen.cpp.
{
             const tripoint start = tripoint( x.val, y.val, dat.zlevel() + z.get() );
             const tripoint end = tripoint( x.valmax, y.valmax, dat.zlevel() + z.get() );
             for( const tripoint &p : tripoint_range<tripoint>( start, end ) ) {
                 dat.m.furn_clear( p );
                 dat.m.i_clear( p );
                 dat.m.remove_trap( p );
                 dat.m.clear_fields( p );
                 dat.m.delete_graffiti( p );
                 if( optional_vpart_position vp = dat.m.veh_at( p ) ) {
                     if( get_map().inbounds( dat.m.getglobal( start ) ) ) {
                         get_map().remove_vehicle_from_cache( &vp->vehicle(), start.z, end.z );
                     }
                     dat.m.destroy_vehicle( &vp->vehicle() );
                 }
             }
         }
References map::clear_fields, map::delete_graffiti(), map::destroy_vehicle(), keycode::end, map::furn_clear(), jmapgen_int::get(), get_map(), map::getglobal(), map::i_clear(), mapgendata::m, map::remove_trap(), map::remove_vehicle_from_cache(), tripoint, jmapgen_int::val, jmapgen_int::valmax, map::veh_at(), tripoint::z, and mapgendata::zlevel().
phase()
mapgen_phase jmapgen_remove_all::phase () const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 3488 of file mapgen.cpp.
{
             return mapgen_phase::removal;
         }
References removal.
The documentation for this class was generated from the following file:
src/mapgen.cpp