Cataclysm DDA: character_id Class Reference
character_id Class Reference
#include <character_id.h>
Public Member Functions
character_id ()
character_id (int i)
bool is_valid () const
int get_value () const
character_id & operator++ ()
void serialize (JsonOut &) const
void deserialize (int)
Private Attributes
int value
Detailed Description
Definition at line 9 of file character_id.h.
Constructor & Destructor Documentation
character_id() [1/2]
character_id::character_id () inline
Definition at line 12 of file character_id.h.
 : value( -1 ) {}
character_id() [2/2]
character_id::character_id (int i) inline explicit
Definition at line 14 of file character_id.h.
                                        : value( i ) {
         }
Member Function Documentation
deserialize()
void character_id::deserialize (int i)
Definition at line 502 of file savegame_json.cpp.
 {
     value = i;
 }
Referenced by game::unserialize_master().
get_value()
int character_id::get_value () const inline
Definition at line 21 of file character_id.h.
{
             return value;
         }
References value.
Referenced by item::already_used_by_player(), mission::assign(), item_location::impl::item_on_person::ensure_who_unpacked(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_talker(), activity_handlers::generic_game_finish(), item::mark_as_used_by_player(), operator!=(), operator<(), operator==(), mission_start::place_deposit_box(), mission_start::place_npc_software(), iuse::portable_game(), game::save_achievements(), talk_function::start_training_gen(), cata_variant_detail::convert< cata_variant_type::character_id >::to_string(), and mission::wrap_up().
is_valid()
bool character_id::is_valid () const inline
Definition at line 17 of file character_id.h.
{
             return value > 0;
         }
References value.
Referenced by mission::assign(), vehicle_part::crew(), mission_ui_impl::draw_selected_description(), monster::find_dragged_foe(), mission::is_assigned(), mission::is_complete(), Character::load(), game::load(), eoc_events::notify(), and mission::process().
operator++()
character_id& character_id::operator++ () inline
Definition at line 25 of file character_id.h.
{
             ++value;
             return *this;
         }
References value.
serialize()
void character_id::serialize (JsonOut & jsout) const
Definition at line 497 of file savegame_json.cpp.
 {
     jsout.write( value );
 }
References JsonOut::write().
Member Data Documentation
value
int character_id::value private
Definition at line 34 of file character_id.h.
Referenced by get_value(), is_valid(), and operator++().
The documentation for this class was generated from the following files:
src/character_id.h
src/savegame_json.cpp