Cataclysm DDA: spell_events Class Reference
spell_events Class Reference
#include <magic.h>
Public Member Functions
void notify (const cata::event &) override
virtual void notify (const cata::event &)=0
virtual void notify (const cata::event &, std::unique_ptr< talker >, std::unique_ptr< talker >)
Public Member Functions inherited from event_subscriber
event_subscriber ()=default
event_subscriber (const event_subscriber &)=delete
event_subscriber & operator= (const event_subscriber &)=delete
virtual ~event_subscriber ()
virtual void notify (const cata::event &, std::unique_ptr< talker >, std::unique_ptr< talker >)
Detailed Description
Definition at line 190 of file magic.h.
Member Function Documentation
notify() [1/3]
void spell_events::notify (const cata::event & e) override virtual
Implements event_subscriber.
Definition at line 3059 of file magic.cpp.
 {
     switch( e.type() ) {
         case event_type::player_levels_spell: {
             spell_id sid = e.get<spell_id>( "spell" );
             int slvl = e.get<int>( "new_level" );
             spell_type spell_cast = spell_factory.obj( sid );
             for( std::map<std::string, int>::iterator it = spell_cast.learn_spells.begin();
                  it != spell_cast.learn_spells.end(); ++it ) {
                 int learn_at_level = it->second;
                 const std::string learn_spell_id = it->first;
                 if( learn_at_level <= slvl && !get_player_character().magic->knows_spell( learn_spell_id ) ) {
                     get_player_character().magic->learn_spell( learn_spell_id, get_player_character() );
                     spell_type spell_learned = spell_factory.obj( spell_id( learn_spell_id ) );
                     add_msg(
                         _( "Your experience and knowledge in creating and manipulating magical energies to cast %s have opened your eyes to new possibilities, you can now cast %s." ),
                         spell_cast.name,
                         spell_learned.name );
                 }
             }
             break;
         }
         default:
             break;
     }
 }
References _, add_msg(), cata::event::get(), get_player_character(), Character::magic, spell_type::name, player_levels_spell, anonymous_namespace{magic.cpp}::spell_factory, spell_id, and cata::event::type().
notify() [2/3]
virtual void event_subscriber::notify
notify() [3/3]
void event_subscriber::notify
Definition at line 22 of file event_bus.cpp.
 {
     notify( e );
 }
The documentation for this class was generated from the following files:
src/magic.h
src/magic.cpp