Cataclysm DDA: npc_class Class Reference
npc_class Class Reference
#include <npc_class.h>
Public Member Functions
npc_class ()
std::string get_name () const
std::string get_job_description () const
int roll_strength () const
int roll_dexterity () const
int roll_intelligence () const
int roll_perception () const
int roll_aggression () const
int roll_bravery () const
int roll_collector () const
int roll_altruism () const
int roll_skill (const skill_id &) const
const std::vector< shopkeeper_item_group > & get_shopkeeper_items () const
const shopkeeper_cons_rates & get_shopkeeper_cons_rates () const
const shopkeeper_blacklist & get_shopkeeper_blacklist () const
const time_duration & get_shop_restock_interval () const
faction_price_rule const * get_price_rules (item const &it, npc const &guy) const
void load (const JsonObject &jo, std::string_view src)
Static Public Member Functions
static const npc_class_id & from_legacy_int (int i)
static const npc_class_id & random_common ()
static void load_npc_class (const JsonObject &jo, const std::string &src)
static const std::vector< npc_class > & get_all ()
static void reset_npc_classes ()
static void finalize_all ()
static void check_consistency ()
Public Attributes
npc_class_id id
std::vector< std::pair< npc_class_id, mod_id > > src
bool was_loaded = false
bool sells_belongings = true
item_group_id worn_override
item_group_id carry_override
item_group_id weapon_override
std::map< mutation_category_id, distribution > mutation_rounds
trait_group::Trait_group_tag traits = trait_group::Trait_group_tag("EMPTY_GROUP")
std::map< spell_id, int > _starting_spells
std::map< bionic_id, int > bionic_list
std::vector< proficiency_id > _starting_proficiencies
Private Attributes
translation name
translation job_description
bool common = true
distribution bonus_str
distribution bonus_dex
distribution bonus_int
distribution bonus_per
distribution bonus_aggression
distribution bonus_bravery
distribution bonus_collector
distribution bonus_altruism
std::map< skill_id, distribution > skills
std::map< skill_id, distribution > bonus_skills
std::vector< shopkeeper_item_group > shop_item_groups
std::vector< faction_price_rule > shop_price_rules
shopkeeper_cons_rates_id shop_cons_rates_id = shopkeeper_cons_rates_id::NULL_ID()
shopkeeper_blacklist_id shop_blacklist_id = shopkeeper_blacklist_id::NULL_ID()
time_duration restock_interval = 6_days
Detailed Description
Definition at line 71 of file npc_class.h.
Constructor & Destructor Documentation
npc_class()
npc_class::npc_class ()
Definition at line 84 of file npc_class.cpp.
                      : id( NC_NONE )
 {
 }
Member Function Documentation
check_consistency()
void npc_class::check_consistency () static
Definition at line 135 of file npc_class.cpp.
 {
     for( const npc_class_id &legacy : legacy_ids ) {
         if( !npc_class_factory.is_valid( legacy ) ) {
             debugmsg( "Missing legacy npc class %s (at index %d)",
                       legacy.c_str(), &legacy - legacy_ids.data() );
         }
     }
     for( const npc_class &cl : npc_class_factory.get_all() ) {
         for( const shopkeeper_item_group &ig : cl.shop_item_groups ) {
             if( !item_group::group_is_defined( ig.id ) ) {
                 debugmsg( "Missing shopkeeper item group %s", ig.id.c_str() );
             }
         }
         if( !cl.worn_override.is_empty() && !item_group::group_is_defined( cl.worn_override ) ) {
             debugmsg( "Missing worn override item group %s", cl.worn_override.c_str() );
         }
         if( !cl.carry_override.is_empty() && !item_group::group_is_defined( cl.carry_override ) ) {
             debugmsg( "Missing carry override item group %s", cl.carry_override.c_str() );
         }
         if( !cl.weapon_override.is_empty() && !item_group::group_is_defined( cl.weapon_override ) ) {
             debugmsg( "Missing weapon override item group %s", cl.weapon_override.c_str() );
         }
         for( const auto &pr : cl.skills ) {
             if( !pr.first.is_valid() ) {
                 debugmsg( "Invalid skill %s", pr.first.c_str() );
             }
         }
         if( !cl.traits.is_valid() ) {
             debugmsg( "Trait group %s is undefined", cl.traits.c_str() );
         }
     }
 }
References string_id< T >::c_str(), debugmsg, item_group::group_is_defined(), shopkeeper_item_group::id, legacy_ids, and npc_class_factory.
Referenced by DynamicDataLoader::check_consistency().
finalize_all()
void npc_class::finalize_all () static
Definition at line 118 of file npc_class.cpp.
 {
     for( const npc_class &cl_const : npc_class_factory.get_all() ) {
         npc_class &cl = const_cast<npc_class &>( cl_const );
         apply_all_to_unassigned( cl.skills );
         apply_all_to_unassigned( cl.bonus_skills );
         for( const auto &pr : cl.bonus_skills ) {
             if( cl.skills.count( pr.first ) == 0 ) {
                 cl.skills[ pr.first ] = pr.second;
             } else {
                 cl.skills[ pr.first ] = cl.skills[ pr.first ] + pr.second;
             }
         }
     }
 }
References apply_all_to_unassigned(), bonus_skills, npc_class_factory, and skills.
Referenced by DynamicDataLoader::finalize_loaded_data().
from_legacy_int()
const npc_class_id & npc_class::from_legacy_int (int i) static
Definition at line 376 of file npc_class.cpp.
 {
     if( i < 0 || static_cast<size_t>( i ) >= legacy_ids.size() ) {
         debugmsg( "Invalid legacy class id: %d", i );
         return npc_class_id::NULL_ID();
     }
     return legacy_ids[ i ];
 }
References debugmsg, legacy_ids, and string_id< npc_class >::NULL_ID().
Referenced by mission::deserialize(), npc::load(), and npc_template::load().
get_all()
const std::vector< npc_class > & npc_class::get_all () static
Definition at line 386 of file npc_class.cpp.
 {
     return npc_class_factory.get_all();
 }
References npc_class_factory.
Referenced by debug_menu::character_edit_menu().
get_job_description()
std::string npc_class::get_job_description () const
Definition at line 412 of file npc_class.cpp.
 {
     return job_description.translated();
 }
References job_description, and translation::translated().
Referenced by npc::describe_mission().
get_name()
std::string npc_class::get_name () const
Definition at line 407 of file npc_class.cpp.
 {
     return name.translated();
 }
References name, and translation::translated().
Referenced by debug_menu::character_edit_menu().
get_price_rules()
faction_price_rule const * npc_class::get_price_rules (item const & it, npc const & guy) const
Definition at line 440 of file npc_class.cpp.
 {
     auto const el = std::find_if(
     shop_price_rules.crbegin(), shop_price_rules.crend(), [&it, &guy]( faction_price_rule const & fc ) {
         return fc.matches( it, guy );
     } );
     if( el != shop_price_rules.crend() ) {
         return &*el;
     }
     return nullptr;
 }
References shop_price_rules.
Referenced by npc::get_price_rules().
get_shop_restock_interval()
const time_duration & npc_class::get_shop_restock_interval () const
Definition at line 452 of file npc_class.cpp.
 {
     return restock_interval;
 }
References restock_interval.
Referenced by npc::shop_restock().
get_shopkeeper_blacklist()
const shopkeeper_blacklist & npc_class::get_shopkeeper_blacklist () const
Definition at line 431 of file npc_class.cpp.
 {
     if( shop_blacklist_id.is_null() ) {
         shopkeeper_blacklist static const null_blacklist;
         return null_blacklist;
     }
     return shop_blacklist_id.obj();
 }
References string_id< T >::is_null(), string_id< T >::obj(), and shop_blacklist_id.
Referenced by npc::wants_to_buy().
get_shopkeeper_cons_rates()
const shopkeeper_cons_rates & npc_class::get_shopkeeper_cons_rates () const
Definition at line 422 of file npc_class.cpp.
 {
     if( shop_cons_rates_id.is_null() ) {
         shopkeeper_cons_rates static const null_rates;
         return null_rates;
     }
     return shop_cons_rates_id.obj();
 }
References string_id< T >::is_null(), string_id< T >::obj(), and shop_cons_rates_id.
Referenced by anonymous_namespace{npctrade_utils.cpp}::_consume_item().
get_shopkeeper_items()
const std::vector< shopkeeper_item_group > & npc_class::get_shopkeeper_items () const
Definition at line 417 of file npc_class.cpp.
 {
     return shop_item_groups;
 }
References shop_item_groups.
Referenced by npc::is_shopkeeper(), npc::shop_restock(), and npc::wants_to_sell().
load()
void npc_class::load (const JsonObject & jo, std::string_view src)
Definition at line 271 of file npc_class.cpp.
 {
     mandatory( jo, was_loaded, "name", name );
     mandatory( jo, was_loaded, "job_description", job_description );
     optional( jo, was_loaded, "common", common, true );
     bonus_str = load_distribution( jo, "bonus_str" );
     bonus_dex = load_distribution( jo, "bonus_dex" );
     bonus_int = load_distribution( jo, "bonus_int" );
     bonus_per = load_distribution( jo, "bonus_per" );
     bonus_aggression = load_distribution( jo, "bonus_aggression" );
     bonus_bravery = load_distribution( jo, "bonus_bravery" );
     bonus_collector = load_distribution( jo, "bonus_collector" );
     bonus_altruism = load_distribution( jo, "bonus_altruism" );
     if( jo.has_member( "shopkeeper_item_group" ) ) {
         if( jo.has_array( "shopkeeper_item_group" ) &&
             jo.get_array( "shopkeeper_item_group" ).test_object() ) {
             mandatory( jo, was_loaded, "shopkeeper_item_group", shop_item_groups );
         } else if( jo.has_string( "shopkeeper_item_group" ) ) {
             const std::string &ig_str = jo.get_string( "shopkeeper_item_group" );
             shop_item_groups.emplace_back( ig_str, 0, false );
         } else {
             jo.throw_error( string_format( "invalid format for shopkeeper_item_group in npc class %s", name ) );
         }
     }
     optional( jo, was_loaded, "shopkeeper_price_rules", shop_price_rules, faction_price_rules_reader {} );
     optional( jo, was_loaded, SHOPKEEPER_CONSUMPTION_RATES, shop_cons_rates_id,
               shopkeeper_cons_rates_id::NULL_ID() );
     optional( jo, was_loaded, SHOPKEEPER_BLACKLIST, shop_blacklist_id,
               shopkeeper_blacklist_id::NULL_ID() );
     optional( jo, was_loaded, "restock_interval", restock_interval, 6_days );
     optional( jo, was_loaded, "worn_override", worn_override );
     optional( jo, was_loaded, "carry_override", carry_override );
     optional( jo, was_loaded, "weapon_override", weapon_override );
     if( jo.has_member( "traits" ) ) {
         traits = trait_group::load_trait_group( jo.get_member( "traits" ), "collection" );
     }
     if( jo.has_array( "spells" ) ) {
         for( JsonObject subobj : jo.get_array( "spells" ) ) {
             const int level = subobj.get_int( "level" );
             const spell_id sp = spell_id( subobj.get_string( "id" ) );
             _starting_spells.emplace( sp, level );
         }
     }
     optional( jo, was_loaded, "proficiencies", _starting_proficiencies );
     optional( jo, was_loaded, "sells_belongings", sells_belongings, true );
     /* Mutation rounds can be specified as follows:
      *   "mutation_rounds": {
      *     "ANY" : { "constant": 1 },
      *     "INSECT" : { "rng": [1, 3] }
      *   }
      */
     if( jo.has_object( "mutation_rounds" ) ) {
         const std::map<mutation_category_id, mutation_category_trait> &mutation_categories =
             mutation_category_trait::get_all();
         for( const JsonMember member : jo.get_object( "mutation_rounds" ) ) {
             const mutation_category_id mutation( member.name() );
             const auto category_match = [&mutation]( const
                                         std::pair<const mutation_category_id, mutation_category_trait>
             &p ) {
                 return p.second.id == mutation;
             };
             if( std::find_if( mutation_categories.begin(), mutation_categories.end(),
                               category_match ) == mutation_categories.end() ) {
                 debugmsg( "Unrecognized mutation category %s", mutation.str() );
                 continue;
             }
             JsonObject distrib = member.get_object();
             mutation_rounds[mutation] = load_distribution( distrib );
         }
     }
     if( jo.has_array( "skills" ) ) {
         for( JsonObject skill_obj : jo.get_array( "skills" ) ) {
             auto skill_ids = skill_obj.get_tags( "skill" );
             if( skill_obj.has_object( "level" ) ) {
                 const distribution dis = load_distribution( skill_obj, "level" );
                 for( const auto &sid : skill_ids ) {
                     skills[ skill_id( sid ) ] = dis;
                 }
             } else {
                 const distribution dis = load_distribution( skill_obj, "bonus" );
                 for( const auto &sid : skill_ids ) {
                     bonus_skills[ skill_id( sid ) ] = dis;
                 }
             }
         }
     }
     if( jo.has_array( "bionics" ) ) {
         for( JsonObject bionic_obj : jo.get_array( "bionics" ) ) {
             auto bionic_ids = bionic_obj.get_tags( "id" );
             int chance = bionic_obj.get_int( "chance" );
             for( const auto &bid : bionic_ids ) {
                 bionic_list[ bionic_id( bid )] = chance;
             }
         }
     }
 }
References _starting_proficiencies, _starting_spells, bionic_id, bionic_list, bonus_aggression, bonus_altruism, bonus_bravery, bonus_collector, bonus_dex, bonus_int, bonus_per, bonus_skills, bonus_str, carry_override, common, debugmsg, mutation_category_trait::get_all(), JsonObject::get_array(), JsonObject::get_member(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), job_description, load_distribution(), trait_group::load_trait_group(), mandatory, member, mutation, mutation_rounds, name, string_id< shopkeeper_blacklist >::NULL_ID(), string_id< shopkeeper_cons_rates >::NULL_ID(), optional(), restock_interval, sells_belongings, shop_blacklist_id, shop_cons_rates_id, shop_item_groups, shop_price_rules, SHOPKEEPER_BLACKLIST, SHOPKEEPER_CONSUMPTION_RATES, skill_id, skills, spell_id, string_format(), JsonArray::test_object(), JsonObject::throw_error(), traits, was_loaded, weapon_override, and worn_override.
load_npc_class()
void npc_class::load_npc_class (const JsonObject & jo, const std::string & src) static
Definition at line 88 of file npc_class.cpp.
 {
     npc_class_factory.load( jo, src );
 }
References npc_class_factory, and src.
Referenced by DynamicDataLoader::initialize().
random_common()
const npc_class_id & npc_class::random_common () static
Definition at line 391 of file npc_class.cpp.
 {
     std::list<const npc_class_id *> common_classes;
     for( const npc_class &pr : npc_class_factory.get_all() ) {
         if( pr.common ) {
             common_classes.push_back( &pr.id );
         }
     }
     if( common_classes.empty() || one_in( common_classes.size() ) ) {
         return NC_NONE;
     }
     return *random_entry( common_classes );
 }
References NC_NONE, npc_class_factory, one_in(), and random_entry().
Referenced by npc::randomize().
reset_npc_classes()
void npc_class::reset_npc_classes () static
Definition at line 93 of file npc_class.cpp.
 {
     npc_class_factory.reset();
 }
References npc_class_factory.
Referenced by DynamicDataLoader::unload_data().
roll_aggression()
int npc_class::roll_aggression () const
Definition at line 477 of file npc_class.cpp.
 {
     return bonus_aggression.roll();
 }
References bonus_aggression, and distribution::roll().
Referenced by npc::randomize().
roll_altruism()
int npc_class::roll_altruism () const
Definition at line 492 of file npc_class.cpp.
 {
     return bonus_altruism.roll();
 }
References bonus_altruism, and distribution::roll().
Referenced by npc::randomize().
roll_bravery()
int npc_class::roll_bravery () const
Definition at line 482 of file npc_class.cpp.
 {
     return bonus_bravery.roll();
 }
References bonus_bravery, and distribution::roll().
Referenced by npc::randomize().
roll_collector()
int npc_class::roll_collector () const
Definition at line 487 of file npc_class.cpp.
 {
     return bonus_collector.roll();
 }
References bonus_collector, and distribution::roll().
Referenced by npc::randomize().
roll_dexterity()
int npc_class::roll_dexterity () const
Definition at line 462 of file npc_class.cpp.
 {
     return bonus_dex.roll();
 }
References bonus_dex, and distribution::roll().
Referenced by npc::randomize().
roll_intelligence()
int npc_class::roll_intelligence () const
Definition at line 467 of file npc_class.cpp.
 {
     return bonus_int.roll();
 }
References bonus_int, and distribution::roll().
Referenced by npc::randomize().
roll_perception()
int npc_class::roll_perception () const
Definition at line 472 of file npc_class.cpp.
 {
     return bonus_per.roll();
 }
References bonus_per, and distribution::roll().
Referenced by npc::randomize().
roll_skill()
int npc_class::roll_skill (const skill_id & sid) const
Definition at line 497 of file npc_class.cpp.
 {
     const auto &iter = skills.find( sid );
     if( iter == skills.end() ) {
         return 0;
     }
     return std::max<int>( 0, iter->second.roll() );
 }
References skills.
Referenced by npc::randomize().
roll_strength()
int npc_class::roll_strength () const
Definition at line 457 of file npc_class.cpp.
 {
     return bonus_str.roll();
 }
References bonus_str, and distribution::roll().
Referenced by npc::randomize().
Member Data Documentation
_starting_proficiencies
std::vector<proficiency_id> npc_class::_starting_proficiencies
Definition at line 117 of file npc_class.h.
Referenced by load().
_starting_spells
std::map<spell_id, int> npc_class::_starting_spells
Definition at line 115 of file npc_class.h.
Referenced by load().
bionic_list
std::map<bionic_id, int> npc_class::bionic_list
Definition at line 116 of file npc_class.h.
Referenced by load().
bonus_aggression
distribution npc_class::bonus_aggression private
Definition at line 84 of file npc_class.h.
Referenced by load(), and roll_aggression().
bonus_altruism
distribution npc_class::bonus_altruism private
Definition at line 87 of file npc_class.h.
Referenced by load(), and roll_altruism().
bonus_bravery
distribution npc_class::bonus_bravery private
Definition at line 85 of file npc_class.h.
Referenced by load(), and roll_bravery().
bonus_collector
distribution npc_class::bonus_collector private
Definition at line 86 of file npc_class.h.
Referenced by load(), and roll_collector().
bonus_dex
distribution npc_class::bonus_dex private
Definition at line 80 of file npc_class.h.
Referenced by load(), and roll_dexterity().
bonus_int
distribution npc_class::bonus_int private
Definition at line 81 of file npc_class.h.
Referenced by load(), and roll_intelligence().
bonus_per
distribution npc_class::bonus_per private
Definition at line 82 of file npc_class.h.
Referenced by load(), and roll_perception().
bonus_skills
std::map<skill_id, distribution> npc_class::bonus_skills private
Definition at line 91 of file npc_class.h.
Referenced by finalize_all(), and load().
bonus_str
distribution npc_class::bonus_str private
Definition at line 79 of file npc_class.h.
Referenced by load(), and roll_strength().
carry_override
item_group_id npc_class::carry_override
Definition at line 109 of file npc_class.h.
Referenced by load().
common
bool npc_class::common = true private
Definition at line 77 of file npc_class.h.
Referenced by load().
id
npc_class_id npc_class::id
Definition at line 101 of file npc_class.h.
Referenced by debug_menu::character_edit_menu().
job_description
translation npc_class::job_description private
Definition at line 75 of file npc_class.h.
Referenced by get_job_description(), and load().
mutation_rounds
std::map<mutation_category_id, distribution> npc_class::mutation_rounds
Definition at line 112 of file npc_class.h.
Referenced by load().
name
translation npc_class::name private
Definition at line 74 of file npc_class.h.
Referenced by get_name(), and load().
restock_interval
time_duration npc_class::restock_interval = 6_days private
Definition at line 98 of file npc_class.h.
Referenced by get_shop_restock_interval(), and load().
sells_belongings
bool npc_class::sells_belongings = true
Definition at line 106 of file npc_class.h.
Referenced by load(), and npc::wants_to_sell().
shop_blacklist_id
shopkeeper_blacklist_id npc_class::shop_blacklist_id = shopkeeper_blacklist_id::NULL_ID() private
Definition at line 97 of file npc_class.h.
Referenced by get_shopkeeper_blacklist(), and load().
shop_cons_rates_id
shopkeeper_cons_rates_id npc_class::shop_cons_rates_id = shopkeeper_cons_rates_id::NULL_ID() private
Definition at line 96 of file npc_class.h.
Referenced by get_shopkeeper_cons_rates(), and load().
shop_item_groups
std::vector<shopkeeper_item_group> npc_class::shop_item_groups private
Definition at line 94 of file npc_class.h.
Referenced by get_shopkeeper_items(), and load().
shop_price_rules
std::vector<faction_price_rule> npc_class::shop_price_rules private
Definition at line 95 of file npc_class.h.
Referenced by get_price_rules(), and load().
skills
std::map<skill_id, distribution> npc_class::skills private
Definition at line 89 of file npc_class.h.
Referenced by finalize_all(), load(), and roll_skill().
src
std::vector<std::pair<npc_class_id, mod_id> > npc_class::src
Definition at line 102 of file npc_class.h.
Referenced by load_npc_class().
traits
trait_group::Trait_group_tag npc_class::traits = trait_group::Trait_group_tag("EMPTY_GROUP")
Definition at line 113 of file npc_class.h.
Referenced by load(), and npc::randomize().
was_loaded
bool npc_class::was_loaded = false
Definition at line 103 of file npc_class.h.
Referenced by load().
weapon_override
item_group_id npc_class::weapon_override
Definition at line 110 of file npc_class.h.
Referenced by load().
worn_override
item_group_id npc_class::worn_override
Definition at line 108 of file npc_class.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/npc_class.h
src/npc_class.cpp