Cataclysm DDA: distribution Class Reference
distribution Class Reference
#include <npc_class.h>
Public Member Functions
distribution ()
distribution (const distribution &)
float roll () const
distribution operator+ (const distribution &other) const
distribution operator* (const distribution &other) const
distribution & operator= (const distribution &other)
Static Public Member Functions
static distribution constant (float val)
static distribution rng_roll (int from, int to)
static distribution dice_roll (int sides, int size)
static distribution one_in (float in)
Private Member Functions
distribution (const std::function< float()> &gen)
Private Attributes
std::function< float()> generator_function
Detailed Description
Definition at line 29 of file npc_class.h.
Constructor & Destructor Documentation
distribution() [1/3]
distribution::distribution (const std::function< float()> & gen) explicit private
Definition at line 519 of file npc_class.cpp.
 {
     generator_function = gen;
 }
References generator_function.
distribution() [2/3]
distribution::distribution ()
Definition at line 507 of file npc_class.cpp.
 {
     generator_function = []() {
         return 0.0f;
     };
 }
References generator_function.
Referenced by constant(), dice_roll(), one_in(), operator*(), operator+(), and rng_roll().
distribution() [3/3]
distribution::distribution (const distribution & d)
Definition at line 514 of file npc_class.cpp.
 {
     generator_function = d.generator_function;
 }
References generator_function.
Member Function Documentation
constant()
distribution distribution::constant (float val) static
Definition at line 529 of file npc_class.cpp.
 {
     return distribution( [val]() {
         return val;
     } );
 }
References distribution().
Referenced by load_distribution().
dice_roll()
distribution distribution::dice_roll (int sides, int size) static
Definition at line 555 of file npc_class.cpp.
 {
     if( sides < 1 || size < 1 ) {
         debugmsg( "Invalid dice: %d sides, %d sizes", sides, size );
         return distribution();
     }
     return distribution( [sides, size]() -> float {
         return dice( sides, size );
     } );
 }
References debugmsg, dice(), distribution(), and om_direction::size.
Referenced by load_distribution().
one_in()
distribution distribution::one_in (float in) static
Definition at line 536 of file npc_class.cpp.
 {
     if( in <= 1.0f ) {
         debugmsg( "Invalid one_in: %.2f", in );
         return distribution();
     }
     return distribution( [in]() {
         return x_in_y( 1, in );
     } );
 }
References debugmsg, distribution(), and x_in_y().
Referenced by load_distribution().
operator*()
distribution distribution::operator* (const distribution & other) const
Definition at line 576 of file npc_class.cpp.
 {
     auto my_fun = generator_function;
     auto other_fun = other.generator_function;
     return distribution( [my_fun, other_fun]() {
         return my_fun() * other_fun();
     } );
 }
References distribution(), generator_function, and other.
operator+()
distribution distribution::operator+ (const distribution & other) const
Definition at line 567 of file npc_class.cpp.
 {
     auto my_fun = generator_function;
     auto other_fun = other.generator_function;
     return distribution( [my_fun, other_fun]() {
         return my_fun() + other_fun();
     } );
 }
References distribution(), generator_function, and other.
operator=()
distribution & distribution::operator= (const distribution & other) default
rng_roll()
distribution distribution::rng_roll (int from, int to) static
Definition at line 548 of file npc_class.cpp.
 {
     return distribution( [from, to]() -> float {
         return rng( from, to );
     } );
 }
References distribution(), and rng().
Referenced by load_distribution().
roll()
float distribution::roll () const
Definition at line 524 of file npc_class.cpp.
 {
     return generator_function();
 }
References generator_function.
Referenced by npc_class::roll_aggression(), npc_class::roll_altruism(), npc_class::roll_bravery(), npc_class::roll_collector(), npc_class::roll_dexterity(), npc_class::roll_intelligence(), npc_class::roll_perception(), and npc_class::roll_strength().
Member Data Documentation
generator_function
std::function<float()> distribution::generator_function private
Definition at line 32 of file npc_class.h.
Referenced by distribution(), operator*(), operator+(), and roll().
The documentation for this class was generated from the following files:
src/npc_class.h
src/npc_class.cpp