Cataclysm DDA: ascii_art Class Reference
ascii_art Class Reference
#include <ascii_art.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view)
Static Public Member Functions
static void load_ascii_art (const JsonObject &jo, const std::string &src)
static void reset ()
Public Attributes
bool was_loaded = false
ascii_art_id id
std::vector< std::pair< ascii_art_id, mod_id > > src
std::vector< std::string > picture
Detailed Description
Definition at line 14 of file ascii_art.h.
Member Function Documentation
load()
void ascii_art::load (const JsonObject & jo, std::string_view)
Definition at line 39 of file ascii_art.cpp.
 {
     assign( jo, "id", id );
     assign( jo, "picture", picture );
     for( std::string &line : picture ) {
         if( utf8_width( remove_color_tags( line ) ) > ascii_art_width ) {
             line = trim_by_length( line, ascii_art_width );
             debugmsg( "picture in %s contains a line too long to be displayed (>%i char).", id.c_str(),
                       ascii_art_width );
         }
     }
 }
References ascii_art_width, assign(), debugmsg, line, picture, remove_color_tags(), trim_by_length(), and utf8_width().
load_ascii_art()
void ascii_art::load_ascii_art (const JsonObject & jo, const std::string & src) static
Definition at line 34 of file ascii_art.cpp.
 {
     ascii_art_factory.load( jo, src );
 }
References anonymous_namespace{ascii_art.cpp}::ascii_art_factory, and src.
Referenced by DynamicDataLoader::initialize().
reset()
void ascii_art::reset () static
Definition at line 53 of file ascii_art.cpp.
 {
     ascii_art_factory.reset();
 }
References anonymous_namespace{ascii_art.cpp}::ascii_art_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
id
ascii_art_id ascii_art::id
Definition at line 23 of file ascii_art.h.
picture
std::vector<std::string> ascii_art::picture
Definition at line 25 of file ascii_art.h.
Referenced by item::ascii_art_info(), load(), and monster::print_info().
src
std::vector<std::pair<ascii_art_id, mod_id> > ascii_art::src
Definition at line 24 of file ascii_art.h.
Referenced by load_ascii_art().
was_loaded
bool ascii_art::was_loaded = false
Definition at line 21 of file ascii_art.h.
The documentation for this class was generated from the following files:
src/ascii_art.h
src/ascii_art.cpp