Cataclysm DDA: auto_pickup::npc_settings Class Reference
auto_pickup::npc_settings Class Reference
#include <auto_pickup.h>
Public Member Functions
~npc_settings () override=default
void create_rule (const std::string &to_match)
void show (const std::string &name)
void serialize (JsonOut &jsout) const
void deserialize (const JsonArray &ja)
bool empty () const
Public Member Functions inherited from auto_pickup::base_settings
virtual ~base_settings ()=default
rule_state check_item (const std::string &sItemName) const
Private Member Functions
void refresh_map_items (cache &map_items) const override
Private Attributes
rule_list rules
Additional Inherited Members
Protected Member Functions inherited from auto_pickup::base_settings
void invalidate ()
Protected Attributes inherited from auto_pickup::base_settings
cache map_items
Detailed Description
Definition at line 147 of file auto_pickup.h.
Constructor & Destructor Documentation
~npc_settings()
auto_pickup::npc_settings::~npc_settings () override default
Member Function Documentation
create_rule()
void npc_settings::create_rule (const std::string & to_match)
Definition at line 822 of file auto_pickup.cpp.
 {
     rules.create_rule( map_items, to_match );
 }
References auto_pickup::rule_list::create_rule(), auto_pickup::base_settings::map_items, and rules.
Referenced by npc::item_name_whitelisted().
deserialize()
void npc_settings::deserialize (const JsonArray & ja)
Definition at line 1033 of file auto_pickup.cpp.
 {
     rules.deserialize( ja );
 }
References auto_pickup::rule_list::deserialize(), and rules.
empty()
bool npc_settings::empty () const
Definition at line 1043 of file auto_pickup.cpp.
 {
     return rules.empty();
 }
References rules.
refresh_map_items()
void npc_settings::refresh_map_items (cache & map_items) const override private virtual
Implements auto_pickup::base_settings.
Definition at line 1038 of file auto_pickup.cpp.
 {
     rules.refresh_map_items( map_items );
 }
References auto_pickup::base_settings::map_items, auto_pickup::rule_list::refresh_map_items(), and rules.
serialize()
void npc_settings::serialize (JsonOut & jsout) const
Definition at line 1028 of file auto_pickup.cpp.
 {
     rules.serialize( jsout );
 }
References rules, and auto_pickup::rule_list::serialize().
show()
void npc_settings::show (const std::string & name)
Definition at line 1015 of file auto_pickup.cpp.
 {
     user_interface ui;
     ui.title = string_format( _( "Pickup rules for %s" ), name );
     ui.tabs.emplace_back( name, rules );
     ui.show();
     // Don't need to save the rules here, it will be save along with the NPC object itself.
     if( !ui.bStuffChanged ) {
         return;
     }
     invalidate();
 }
References _, auto_pickup::base_settings::invalidate(), om_direction::name(), rules, and string_format().
Member Data Documentation
rules
rule_list auto_pickup::npc_settings::rules private
Definition at line 150 of file auto_pickup.h.
Referenced by create_rule(), deserialize(), empty(), refresh_map_items(), serialize(), and show().
The documentation for this class was generated from the following files:
src/auto_pickup.h
src/auto_pickup.cpp