Cataclysm DDA: salvage_inventory_preset Class Reference
salvage_inventory_preset Class Reference
Public Member Functions
salvage_inventory_preset (const salvage_actor *actor)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual std::string get_denial (const item_location &) const
The reason why this entry cannot be selected.
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Private Attributes
const salvage_actor * actor
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 1989 of file game_inventory.cpp.
Constructor & Destructor Documentation
salvage_inventory_preset()
salvage_inventory_preset::salvage_inventory_preset (const salvage_actor * actor) inline explicit
Definition at line 1992 of file game_inventory.cpp.
                                                                         :
             actor( actor ) {
             append_cell( [ actor ]( const item_location & loc ) {
                 return to_string_clipped( time_duration::from_turns( actor->time_to_cut_up(
                                               *loc.get_item() ) / 100 ) );
             }, _( "TIME" ) );
         }
References _, actor, inventory_selector_preset::append_cell(), time_duration::from_turns(), item_location::get_item(), salvage_actor::time_to_cut_up(), and to_string_clipped().
Member Function Documentation
is_shown()
bool salvage_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 2001 of file game_inventory.cpp.
{
             return actor->valid_to_cut_up( nullptr, *loc.get_item() );
         }
References actor, item_location::get_item(), and salvage_actor::valid_to_cut_up().
Member Data Documentation
actor
const salvage_actor* salvage_inventory_preset::actor private
Definition at line 2006 of file game_inventory.cpp.
Referenced by is_shown(), and salvage_inventory_preset().
The documentation for this class was generated from the following file:
src/game_inventory.cpp