Cataclysm DDA: sound_iuse Class Reference
sound_iuse Class Reference
#include <iuse_actor.h>
Public Member Functions
sound_iuse (const std::string &type="sound")
~sound_iuse () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
std::string get_name () const override
Returns the translated name of the action.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
translation name
if specified overrides default action name
translation sound_message
message if player hears activation with s replaced by item name
int sound_volume = 0
std::string sound_id = "misc"
std::string sound_variant = "default"
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 165 of file iuse_actor.h.
Constructor & Destructor Documentation
sound_iuse()
sound_iuse::sound_iuse (const std::string & type = "sound") inline explicit
Definition at line 168 of file iuse_actor.h.
 : iuse_actor( type ) {}
~sound_iuse()
sound_iuse::~sound_iuse () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > sound_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 564 of file iuse_actor.cpp.
 {
     return std::make_unique<sound_iuse>( *this );
 }
get_name()
std::string sound_iuse::get_name () const override virtual
Returns the translated name of the action.
It is used for the item action menu.
Reimplemented from iuse_actor.
Definition at line 586 of file iuse_actor.cpp.
 {
     if( !name.empty() ) {
         return name.translated();
     }
     return iuse_actor::get_name();
 }
References translation::empty(), iuse_actor::get_name(), name, and translation::translated().
load()
void sound_iuse::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 569 of file iuse_actor.cpp.
 {
     obj.read( "name", name );
     obj.read( "sound_message", sound_message );
     obj.read( "sound_volume", sound_volume );
     obj.read( "sound_id", sound_id );
     obj.read( "sound_variant", sound_variant );
 }
References name, JsonObject::read(), sound_id, sound_message, sound_variant, and sound_volume.
use()
std::optional< int > sound_iuse::use (Character * , item & , const tripoint & pos) const override virtual
Implements iuse_actor.
Definition at line 578 of file iuse_actor.cpp.
 {
     sounds::sound( pos, sound_volume, sounds::sound_t::alarm, sound_message.translated(), true,
                    sound_id, sound_variant );
     return 0;
 }
References sounds::alarm, math_opers::pos(), sounds::sound(), sound_id, sound_message, sound_variant, sound_volume, and translation::translated().
Member Data Documentation
name
translation sound_iuse::name
if specified overrides default action name
Definition at line 171 of file iuse_actor.h.
Referenced by get_name(), and load().
sound_id
std::string sound_iuse::sound_id = "misc"
Definition at line 177 of file iuse_actor.h.
Referenced by load(), and use().
sound_message
translation sound_iuse::sound_message
message if player hears activation with s replaced by item name
Definition at line 174 of file iuse_actor.h.
Referenced by load(), and use().
sound_variant
std::string sound_iuse::sound_variant = "default"
Definition at line 178 of file iuse_actor.h.
Referenced by load(), and use().
sound_volume
int sound_iuse::sound_volume = 0
Definition at line 176 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp