Cataclysm DDA: auto_notes::custom_symbol Class Reference
auto_notes::custom_symbol Class Reference
#include <auto_note.h>
Public Member Functions
std::string get_symbol_string () const
std::string get_color_string () const
uint32_t get_symbol () const
nc_color get_color () const
void set_symbol (const std::string &str)
void set_color (const std::string &col)
Private Attributes
std::optional< uint32_t > symbol
std::optional< nc_color > color
Detailed Description
Definition at line 22 of file auto_note.h.
Member Function Documentation
get_color()
nc_color auto_notes::custom_symbol::get_color () const inline
Definition at line 42 of file auto_note.h.
{
             return color ? *color : c_yellow;
         };
References c_yellow, and color.
get_color_string()
std::string auto_notes::custom_symbol::get_color_string () const inline
Definition at line 34 of file auto_note.h.
{
             return color ? get_all_colors().get_name( *color ) : "";
         };
References color, get_all_colors(), and color_manager::get_name().
get_symbol()
uint32_t auto_notes::custom_symbol::get_symbol () const inline
Definition at line 38 of file auto_note.h.
{
             return symbol ? *symbol : UTF8_getch( "N" );
         };
References symbol, and UTF8_getch().
get_symbol_string()
std::string auto_notes::custom_symbol::get_symbol_string () const inline
Definition at line 30 of file auto_note.h.
{
             return symbol ? utf32_to_utf8( *symbol ) : "";
         };
References symbol, and utf32_to_utf8().
set_color()
void auto_notes::custom_symbol::set_color (const std::string & col) inline
Definition at line 54 of file auto_note.h.
{
             if( !col.empty() ) {
                 color = get_all_colors().name_to_color( col );
             } else {
                 color.reset();
             }
         };
References color, get_all_colors(), and color_manager::name_to_color().
Referenced by auto_notes::auto_note_settings::load(), and auto_notes::auto_note_manager_gui::show().
set_symbol()
void auto_notes::custom_symbol::set_symbol (const std::string & str) inline
Definition at line 46 of file auto_note.h.
{
             if( !str.empty() ) {
                 symbol = UTF8_getch( str );
             } else {
                 symbol.reset();
             }
         };
References symbol, and UTF8_getch().
Referenced by auto_notes::auto_note_settings::load(), and auto_notes::auto_note_manager_gui::show().
Member Data Documentation
color
std::optional<nc_color> auto_notes::custom_symbol::color private
Definition at line 27 of file auto_note.h.
Referenced by get_color(), get_color_string(), and set_color().
symbol
std::optional<uint32_t> auto_notes::custom_symbol::symbol private
Definition at line 25 of file auto_note.h.
Referenced by get_symbol(), get_symbol_string(), and set_symbol().
The documentation for this class was generated from the following file:
src/auto_note.h