Cataclysm DDA: unload_activity_actor Class Reference
unload_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
unload_activity_actor (int moves_total, const item_location &target)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static void unload (Character &who, item_location &target)
Unloads the magazine instantly.
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves_total
item_location target
Detailed Description
Definition at line 901 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
unload_activity_actor()
unload_activity_actor::unload_activity_actor (int moves_total, const item_location & target) inline
Definition at line 907 of file activity_actor_definitions.h.
                                                                               :
             moves_total( moves_total ), target( target ) {}
Referenced by deserialize().
Member Function Documentation
can_resume_with_internal()
bool unload_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 913 of file activity_actor_definitions.h.
{
             const unload_activity_actor &act = static_cast<const unload_activity_actor &>( other );
             return target == act.target;
         }
References act, other, and target.
clone()
std::unique_ptr<activity_actor> unload_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 925 of file activity_actor_definitions.h.
{
             return std::make_unique<unload_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > unload_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 3569 of file activity_actor.cpp.
 {
     unload_activity_actor actor = unload_activity_actor( 0, item_location::nowhere );
     JsonObject data = jsin.get_object();
     data.read( "moves_total", actor.moves_total );
     data.read( "target", actor.target );
     return actor.clone();
 }
References clone(), JsonValue::get_object(), moves_total, item_location::nowhere, JsonObject::read(), target, and unload_activity_actor().
do_turn()
void unload_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 919 of file activity_actor_definitions.h.
 {}
finish()
void unload_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 3473 of file activity_actor.cpp.
 {
     // Need to copy `target` here because `::unload` is static and `this` might be invalidated
     // after `act.set_to_null()` has been called (so `this.target` might also be invalidated)
     item_location target_copy = target;
     act.set_to_null();
     unload( who, target_copy );
 }
References act, target, and unload().
get_type()
activity_id unload_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 909 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_UNLOAD" );
         }
References activity_id.
serialize()
void unload_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 3559 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves_total", moves_total );
     jsout.member( "target", target );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves_total, JsonOut::start_object(), and target.
start()
void unload_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 3467 of file activity_actor.cpp.
 {
     act.moves_left = moves_total;
     act.moves_total = moves_total;
 }
References act, and moves_total.
unload()
void unload_activity_actor::unload (Character & who, item_location & target) static
Unloads the magazine instantly.
Can be called without an activity. May destroy the item.
Definition at line 3482 of file activity_actor.cpp.
 {
     int qty = 0;
     item &it = *target.get_item();
     bool actually_unloaded = false;
     if( it.is_container() ) {
         contents_change_handler handler;
         bool changed = false;
         for( pocket_type ptype : {
                  pocket_type::CONTAINER,
                  pocket_type::MAGAZINE_WELL,
                  pocket_type::MAGAZINE
              } ) {
             for( item *contained : it.all_items_top( ptype, true ) ) {
                 int old_charges = contained->charges;
                 const bool consumed = who.add_or_drop_with_msg( *contained, true, &it, contained );
                 if( consumed || contained->charges != old_charges ) {
                     changed = true;
                     handler.unseal_pocket_containing( item_location( target, contained ) );
                 }
                 if( consumed ) {
                     it.remove_item( *contained );
                 }
             }
             if( changed ) {
                 it.on_contents_changed();
                 who.invalidate_weight_carried_cache();
                 handler.handle_by( who );
             }
         }
         return;
     }
     std::vector<item *> remove_contained;
     for( item *contained : it.all_items_top() ) {
         if( contained->ammo_type() == ammo_plutonium ) {
             contained->charges /= PLUTONIUM_CHARGES;
         }
         if( who.add_or_drop_with_msg( *contained, true, &it, contained ) ) {
             qty += contained->charges;
             remove_contained.push_back( contained );
             actually_unloaded = true;
         }
     }
     // remove the ammo leads in the belt
     for( item *remove : remove_contained ) {
         it.remove_item( *remove );
         actually_unloaded = true;
     }
     // remove the belt linkage
     if( it.is_ammo_belt() ) {
         if( it.type->magazine->linkage ) {
             item link( *it.type->magazine->linkage, calendar::turn, qty );
             if( who.add_or_drop_with_msg( link, true ) ) {
                 actually_unloaded = true;
             }
         }
         if( actually_unloaded ) {
             who.add_msg_if_player( _( "You disassemble your %s." ), it.tname() );
         }
     } else if( actually_unloaded ) {
         who.add_msg_if_player( _( "You unload your %s." ), it.tname() );
     }
     if( it.has_flag( flag_MAG_DESTROY ) && it.ammo_remaining() == 0 ) {
         target.remove_item();
     }
     who.recoil = MAX_RECOIL;
 }
References _, Character::add_msg_if_player(), Character::add_or_drop_with_msg(), item::all_items_top(), ammo_plutonium, item::ammo_remaining(), CONTAINER, flag_MAG_DESTROY, item_location::get_item(), contents_change_handler::handle_by(), item::has_flag(), Character::invalidate_weight_carried_cache(), item::is_ammo_belt(), item::is_container(), itype::magazine, MAGAZINE, MAGAZINE_WELL, MAX_RECOIL, item::on_contents_changed(), PLUTONIUM_CHARGES, Character::recoil, remove, item_location::remove_item(), visitable::remove_item(), target, item::tname(), calendar::turn, item::type, and contents_change_handler::unseal_pocket_containing().
Referenced by craft_command::create_in_progress_craft(), finish(), and Character::unload().
Member Data Documentation
moves_total
int unload_activity_actor::moves_total private
Definition at line 904 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), and start().
target
item_location unload_activity_actor::target private
Definition at line 905 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), serialize(), and unload().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp