Cataclysm DDA: Item_group Class Reference
Item_group Class Reference
This is a list of item spawns.
#include <item_group.h>
Public Types
enum Type { G_COLLECTION , G_DISTRIBUTION }
using ItemList = std::vector< item >
using prop_list = std::vector< std::unique_ptr< Item_spawn_data > >
Item data to create item from and probability that items should be created.
Public Types inherited from Item_spawn_data
enum class overflow_behaviour { none , spill , discard , last }
using ItemList = std::vector< item >
using RecursionList = std::vector< item_group_id >
Public Member Functions
Item_group (Type type, int probability, int ammo_chance, int magazine_chance, const std::string &context, holiday event=holiday::none)
~Item_group () override=default
void add_item_entry (const itype_id &itemid, int probability, const std::string &variant="")
void add_group_entry (const item_group_id &groupid, int probability)
void add_entry (std::unique_ptr< Item_spawn_data > ptr)
Once the relevant data has been read from JSON, this function is always called (either from Item_factory::add_entry, add_item_entry or add_group_entry).
void finalize (const itype_id &container=itype_id::NULL_ID()) override
Instead of calculating at run-time, give a step to finalize those item_groups that has count-min but not count-max.
std::size_t create (ItemList &list, const time_point &birthday, RecursionList &rec, spawn_flags) const override
Create a list of items.
item create_single (const time_point &birthday, RecursionList &rec) const override
The same as create, but create a single item only.
void check_consistency (bool actually_spawn) const override
Check item / spawn settings for consistency.
bool remove_item (const itype_id &itemid) override
For item blacklisted, remove the given item from this and all linked groups.
void replace_items (const std::unordered_map< itype_id, itype_id > &replacements) override
bool has_item (const itype_id &itemid) const override
std::set< const itype * > every_item () const override
Public Member Functions inherited from Item_spawn_data
Item_spawn_data (int _probability, const std::string &context, holiday _event=holiday::none)
virtual ~Item_spawn_data ()=default
std::size_t create (ItemList &list, const time_point &birthday, spawn_flags=spawn_flags::none) const
item create_single (const time_point &birthday) const
const std::string & context () const
int get_probability (bool skip_event_check) const
void set_probablility (int prob)
bool is_event_based () const
Public Attributes
const Type type
const int with_ammo
These aren't directly used.
const int with_magazine
Every item in this group has this chance [0-100%] for items to spawn with their default magazine (if any)
Public Attributes inherited from Item_spawn_data
std::optional< itype_id > container_item
The group spawns contained in this item.
std::optional< std::string > container_item_variant
overflow_behaviour on_overflow = overflow_behaviour::none
std::optional< std::vector< itype_id > > components_items
These item(s) are spawned as components.
bool sealed = true
cata::value_ptr< relic_generator > artifact
Protected Attributes
int sum_prob
Contains the sum of the probability of all entries that this group contains.
prop_list items
Links to the entries in this group.
Protected Attributes inherited from Item_spawn_data
int probability
probability, used by the parent object.
std::string context_
holiday event = holiday::none
Detailed Description
This is a list of item spawns.
It can act as distribution (one entry from the list) or as collection (all entries get a chance).
Definition at line 352 of file item_group.h.
Member Typedef Documentation
ItemList
using Item_group::ItemList = std::vector<item>
Definition at line 355 of file item_group.h.
prop_list
using Item_group::prop_list = std::vector<std::unique_ptr<Item_spawn_data> >
Item data to create item from and probability that items should be created.
If type is G_COLLECTION, probability is in percent. A value of 100 means always create items, a value of 0 never. If type is G_DISTRIBUTION, probability is relative, the sum probability is sum_prob.
Definition at line 374 of file item_group.h.
Member Enumeration Documentation
Type
enum Item_group::Type
Enumerator
G_COLLECTION
G_DISTRIBUTION
Definition at line 356 of file item_group.h.
                   {
             G_COLLECTION,
             G_DISTRIBUTION
         };
Constructor & Destructor Documentation
Item_group()
Item_group::Item_group (Type type, int probability, int ammo_chance, int magazine_chance, const std::string & context, holiday event = holiday::none)
Definition at line 776 of file item_group.cpp.
     : Item_spawn_data( probability, context, event )
     , type( t )
     , with_ammo( ammo_chance )
     , with_magazine( magazine_chance )
     , sum_prob( 0 )
 {
     if( probability <= 0 || ( t != Type::G_DISTRIBUTION && probability > 100 ) ) {
         debugmsg( "Probability %d out of range", probability );
     }
     if( ammo_chance < 0 || ammo_chance > 100 ) {
         debugmsg( "Ammo chance %d is out of range.", ammo_chance );
     }
     if( magazine_chance < 0 || magazine_chance > 100 ) {
         debugmsg( "Magazine chance %d is out of range.", magazine_chance );
     }
 }
References context, debugmsg, and Item_spawn_data::probability.
~Item_group()
Item_group::~Item_group () override default
Member Function Documentation
add_entry()
void Item_group::add_entry (std::unique_ptr< Item_spawn_data > ptr)
Once the relevant data has been read from JSON, this function is always called (either from Item_factory::add_entry, add_item_entry or add_group_entry).
Its purpose is to add a Single_item_creator or Item_group to items.
Definition at line 815 of file item_group.cpp.
 {
     cata_assert( ptr.get() != nullptr );
     if( ptr->get_probability( true ) <= 0 ) {
         return;
     }
     if( type == G_COLLECTION ) {
         ptr->set_probablility( std::min( 100, ptr->get_probability( true ) ) );
     }
     sum_prob += ptr->get_probability( true );
     // Make the ammo and magazine probabilities from the outer entity apply to the nested entity:
     // If ptr is an Item_group, it already inherited its parent's ammo/magazine chances in its constructor.
     Single_item_creator *sic = dynamic_cast<Single_item_creator *>( ptr.get() );
     if( sic ) {
         sic->inherit_ammo_mag_chances( with_ammo, with_magazine );
     }
     items.push_back( std::move( ptr ) );
 }
References cata_assert, G_COLLECTION, Single_item_creator::inherit_ammo_mag_chances(), items, min(), sum_prob, type, with_ammo, and with_magazine.
Referenced by Item_factory::add_entry(), add_group_entry(), and add_item_entry().
add_group_entry()
void Item_group::add_group_entry (const item_group_id & groupid, int probability)
Definition at line 808 of file item_group.cpp.
 {
     add_entry( std::make_unique<Single_item_creator>(
                    groupid.str(), Single_item_creator::S_ITEM_GROUP, probability,
                    "item_group id " + groupid.str() ) );
 }
References add_entry(), Item_spawn_data::probability, Single_item_creator::S_ITEM_GROUP, and string_id< T >::str().
Referenced by jmapgen_loot::jmapgen_loot(), Item_factory::load_item_group_data(), and Item_factory::load_sub_ref().
add_item_entry()
void Item_group::add_item_entry (const itype_id & itemid, int probability, const std::string & variant = "")
Definition at line 795 of file item_group.cpp.
 {
     std::string entry_context = "item " + itemid.str() + " within " + context();
     std::unique_ptr<Single_item_creator> added = std::make_unique<Single_item_creator>(
                 itemid.str(), Single_item_creator::S_ITEM, probability, entry_context );
     if( !variant.empty() ) {
         added->modifier.emplace();
         added->modifier->variant = variant;
     }
     add_entry( std::move( added ) );
 }
References add_entry(), Item_spawn_data::context(), Item_spawn_data::probability, Single_item_creator::S_ITEM, and string_id< T >::str().
Referenced by jmapgen_loot::jmapgen_loot(), Item_factory::load_item_group_data(), and Item_factory::load_sub_ref().
check_consistency()
void Item_group::check_consistency (bool actually_spawn) const override virtual
Check item / spawn settings for consistency.
Includes checking for valid item types and valid settings.
Reimplemented from Item_spawn_data.
Definition at line 905 of file item_group.cpp.
 {
     // if type is collection, then spawning itself automatically spawnes all entries,
     // thus no need to spawn them individually.
     for( const auto &elem : items ) {
         // Assuming every entry needs to be spawned.
         elem->check_consistency( true );
     }
     // If this group has no container, no need to spawn it as a whole as every entry has been spawned.
     Item_spawn_data::check_consistency( container_item ? actually_spawn : false );
 }
References Item_spawn_data::check_consistency(), Item_spawn_data::container_item, and items.
create()
std::size_t Item_group::create (ItemList & list, const time_point & birthday, RecursionList & rec, spawn_flags) const override virtual
Create a list of items.
The create list might be empty. No item of it will be the null item.
Parameters
[out] list New items are appended to the list
[in] birthday All items have that value as birthday.
[out] rec Recursion list, output goes here.
[in] spawn_flags Extra information to change how items are spawned.
Returns
The number of new items appended to the list
Implements Item_spawn_data.
Definition at line 848 of file item_group.cpp.
 {
     std::size_t prev_list_size = list.size();
     if( type == G_COLLECTION ) {
         for( const auto &elem : items ) {
             if( !( flags & spawn_flags::maximized ) && rng( 0, 99 ) >= elem->get_probability( false ) ) {
                 continue;
             }
             elem->create( list, birthday, rec, flags );
         }
     } else if( type == G_DISTRIBUTION ) {
         int p = rng( 0, sum_prob - 1 );
         for( const auto &elem : items ) {
             bool ev_based = elem->is_event_based();
             int prob = elem->get_probability( false );
             int real_prob = elem->get_probability( true );
             p -= real_prob;
             if( ( ev_based && prob == 0 ) || p >= 0 ) {
                 continue;
             }
             elem->create( list, birthday, rec, flags );
             break;
         }
     }
     const std::size_t items_created = list.size() - prev_list_size;
     put_into_container( list, items_created, container_item, container_item_variant, sealed, birthday,
                         on_overflow, context() );
     return list.size() - prev_list_size;
 }
References Item_spawn_data::container_item, Item_spawn_data::container_item_variant, Item_spawn_data::context(), G_COLLECTION, G_DISTRIBUTION, items, maximized, Item_spawn_data::on_overflow, put_into_container(), rng(), Item_spawn_data::sealed, sum_prob, and type.
create_single()
item Item_group::create_single (const time_point & birthday, RecursionList & rec) const override virtual
The same as create, but create a single item only.
The returned item might be a null item!
Implements Item_spawn_data.
Definition at line 880 of file item_group.cpp.
 {
     if( type == G_COLLECTION ) {
         for( const auto &elem : items ) {
             if( rng( 0, 99 ) >= elem->get_probability( false ) ) {
                 continue;
             }
             return elem->create_single( birthday, rec );
         }
     } else if( type == G_DISTRIBUTION ) {
         int p = rng( 0, sum_prob - 1 );
         for( const auto &elem : items ) {
             bool ev_based = elem->is_event_based();
             int prob = elem->get_probability( false );
             int real_prob = elem->get_probability( true );
             p -= real_prob;
             if( ( ev_based && prob == 0 ) || p >= 0 ) {
                 continue;
             }
             return elem->create_single( birthday, rec );
         }
     }
     return item( null_item_id, birthday );
 }
References G_COLLECTION, G_DISTRIBUTION, item, items, null_item_id(), rng(), sum_prob, and type.
every_item()
std::set< const itype * > Item_group::every_item () const override virtual
Implements Item_spawn_data.
Definition at line 969 of file item_group.cpp.
 {
     std::set<const itype *> result;
     for( const auto &spawn_data : items ) {
         std::set<const itype *> these_items = spawn_data->every_item();
         result.insert( these_items.begin(), these_items.end() );
     }
     return result;
 }
References items.
finalize()
void Item_group::finalize (const itype_id & = itype_id::NULL_ID()) override virtual
Instead of calculating at run-time, give a step to finalize those item_groups that has count-min but not count-max.
The reason is
Implements Item_spawn_data.
Definition at line 835 of file item_group.cpp.
 {
     itype_id cont;
     if( container_item.has_value() ) {
         cont = container_item.value();
     } else {
         cont = container;
     }
     for( auto &e : items ) {
         e->finalize( cont );
     }
 }
References Item_spawn_data::container_item, and items.
Referenced by jmapgen_loot::jmapgen_loot().
has_item()
bool Item_group::has_item (const itype_id & itemid) const override virtual
Implements Item_spawn_data.
Definition at line 959 of file item_group.cpp.
 {
     for( const std::unique_ptr<Item_spawn_data> &elem : items ) {
         if( elem->has_item( itemid ) ) {
             return true;
         }
     }
     return false;
 }
References items.
remove_item()
bool Item_group::remove_item (const itype_id & itemid) override virtual
For item blacklisted, remove the given item from this and all linked groups.
Implements Item_spawn_data.
Definition at line 939 of file item_group.cpp.
 {
     for( prop_list::iterator a = items.begin(); a != items.end(); ) {
         if( ( *a )->remove_item( itemid ) ) {
             sum_prob -= ( *a )->get_probability( true );
             a = items.erase( a );
         } else {
             ++a;
         }
     }
     return items.empty();
 }
References a, items, and sum_prob.
replace_items()
void Item_group::replace_items (const std::unordered_map< itype_id, itype_id > & replacements) override virtual
Implements Item_spawn_data.
Definition at line 952 of file item_group.cpp.
 {
     for( const std::unique_ptr<Item_spawn_data> &elem : items ) {
         elem->replace_items( replacements );
     }
 }
References items.
Member Data Documentation
items
prop_list Item_group::items protected
Links to the entries in this group.
Definition at line 414 of file item_group.h.
Referenced by add_entry(), check_consistency(), create(), create_single(), every_item(), finalize(), has_item(), remove_item(), and replace_items().
sum_prob
int Item_group::sum_prob protected
Contains the sum of the probability of all entries that this group contains.
Definition at line 410 of file item_group.h.
Referenced by add_entry(), create(), create_single(), and remove_item().
type
const Type Item_group::type
Definition at line 365 of file item_group.h.
Referenced by add_entry(), create(), create_single(), and make_group_or_throw().
with_ammo
const int Item_group::with_ammo
These aren't directly used.
Instead, the values (both with a default value of 0) "trickle down" to apply to every item/group entry within this item group. It's added to the Single_item_creator's Item_modifier via Single_item_creator::inherit_ammo_mag_chances() Every item in this group has this chance [0-100%] for items to spawn with ammo (plus default magazine if necessary)
Definition at line 401 of file item_group.h.
Referenced by Item_factory::add_entry(), add_entry(), and Item_factory::load_sub_ref().
with_magazine
const int Item_group::with_magazine
Every item in this group has this chance [0-100%] for items to spawn with their default magazine (if any)
Definition at line 403 of file item_group.h.
Referenced by Item_factory::add_entry(), add_entry(), and Item_factory::load_sub_ref().
The documentation for this class was generated from the following files:
src/item_group.h
src/item_group.cpp