Cataclysm DDA: cata_variant Class Reference
cata_variant Class Reference
#include <cata_variant.h>
Public Member Functions
cata_variant ()
template<typename Value , typename = std::enable_if_t <(cata_variant_type_for<Value>() < cata_variant_type::num_types)>>
cata_variant (Value &&value)
cata_variant_type type () const
template<cata_variant_type Type>
auto get () const -> typename cata_variant_detail::convert< Type >::type
template<typename T >
T get () const
const std::string & get_string () const
bool is_valid () const
std::pair< cata_variant_type, std::string > as_pair () const
void serialize (JsonOut &) const
void deserialize (const JsonValue &jsin)
CATA_VARIANT_OPERATOR (<) CATA_VARIANT_OPERATOR(<
Static Public Member Functions
template<cata_variant_type Type, typename Value >
static cata_variant make (Value &&value)
static cata_variant from_string (cata_variant_type t, std::string &&v)
Public Attributes
std::string value_
Detailed Description
Definition at line 433 of file cata_variant.h.
Constructor & Destructor Documentation
cata_variant() [1/2]
cata_variant::cata_variant () inline
Definition at line 438 of file cata_variant.h.
 : type_( cata_variant_type::void_ ) {}
cata_variant() [2/2]
template<typename Value , typename = std::enable_if_t <(cata_variant_type_for<Value>() < cata_variant_type::num_types)>> cata_variant::cata_variant (Value && value) inline explicit
Definition at line 445 of file cata_variant.h.
{
             constexpr cata_variant_type Type = cata_variant_type_for<Value>();
             type_ = Type;
             value_ =
                 cata_variant_detail::convert<Type>::to_string( std::forward<Value>( value ) );
         }
References to_string().
Member Function Documentation
as_pair()
std::pair<cata_variant_type, std::string> cata_variant::as_pair () const inline
Definition at line 496 of file cata_variant.h.
{
             return std::make_pair( type_, value_ );
         }
CATA_VARIANT_OPERATOR()
cata_variant::CATA_VARIANT_OPERATOR ()
deserialize()
void cata_variant::deserialize (const JsonValue & jsin)
Definition at line 4498 of file savegame_json.cpp.
 {
     if( jsin.test_int() ) {
         *this = cata_variant::make<cata_variant_type::int_>( jsin.get_int() );
     } else if( jsin.test_bool() ) {
         *this = cata_variant::make<cata_variant_type::bool_>( jsin.get_bool() );
     } else {
         JsonArray ja = jsin.get_array();
         // FIXME: add_type migration - remove after 0.G
         if( ja.get_string( 0 ) == "add_type" ) {
             type_ = cata_variant_type::addiction_id;
             value_ = add_type_legacy_conv( ja.get_string( 1 ) );
         } else if( !( ja.read_next( type_ ) && ja.read_next( value_ ) ) ) {
             ja.throw_error( "Failed to read cata_variant" );
         }
         if( ja.size() > 2 ) {
             ja.throw_error( "Too many values for cata_variant" );
         }
     }
 }
References add_type_legacy_conv(), addiction_id, JsonValue::get_array(), JsonValue::get_bool(), JsonValue::get_int(), JsonArray::get_string(), JsonArray::read_next(), JsonArray::size(), JsonValue::test_bool(), JsonValue::test_int(), and JsonArray::throw_error().
from_string()
static cata_variant cata_variant::from_string (cata_variant_type t, std::string && v) inline static
Definition at line 466 of file cata_variant.h.
{
             return cata_variant( t, std::move( v ) );
         }
Referenced by calculate_all_blueprint_reqs(), mapgen_parameter::check(), value_constraint::deserialize(), mapgen_parameter::get(), anonymous_namespace{event_bus.cpp}::make_dyn_helper< Type, std::index_sequence< I... > >::operator()(), start_location::set_parameters(), and overmap_ui::set_special_args().
get() [1/2]
template<typename T > T cata_variant::get () const inline
Definition at line 486 of file cata_variant.h.
                       {
             return get<cata_variant_type_for<T>()>();
         }
get() [2/2]
template<cata_variant_type Type> auto cata_variant::get () const -> typename cata_variant_detail::convert<Type>::type inline
Definition at line 475 of file cata_variant.h.
{
             if( type_ != Type ) {
                 debugmsg( "Tried to extract type %s from cata_variant which contained %s",
                           io::enum_to_string( Type ),
                           io::enum_to_string( type_ ) );
                 return {};
             }
             return cata_variant_detail::convert<Type>::from_string( value_ );
         }
References debugmsg, and io::enum_to_string().
Referenced by score::description(), mapgendata_detail::extract_variant_value(), flags_of_itype(), flags_of_terrain(), cata::event::get(), is_mounted(), is_swimming_terrain(), math_abs(), eoc_events::notify(), oter_type_of_oter(), overmap_special_at(), event_transformation_impl::updatable_value_constraint::permits(), achievement_requirement::satisfied_by(), species_of_monster(), and text_for_requirement().
get_string()
const std::string& cata_variant::get_string () const inline
Definition at line 490 of file cata_variant.h.
{
             return value_;
         }
Referenced by recipe::blueprint_parameter_ui_string(), achievement_requirement::check(), mapgen_value< Id >::distribution_source::check(), mapgen_value< Id >::switch_source::check(), mapgen_value< Id >::id_source::check_consistent_with(), mapgen_value< Id >::switch_source::check_consistent_with(), score::description(), mapgendata_detail::extract_variant_value< std::string >(), and is_valid_impl().
is_valid()
bool cata_variant::is_valid () const
Definition at line 24 of file cata_variant.cpp.
 {
     constexpr size_t num_types = static_cast<size_t>( cata_variant_type::num_types );
     return is_valid_impl( *this, std::make_index_sequence<num_types> {} );
 }
References is_valid_impl(), and num_types.
Referenced by achievement_requirement::check().
make()
template<cata_variant_type Type, typename Value > static cata_variant cata_variant::make (Value && value) inline static
Definition at line 457 of file cata_variant.h.
{
             return cata_variant(
                 Type, cata_variant_detail::convert<Type>::to_string(
                     std::forward<Value>( value ) ) );
         }
Referenced by cata::event_detail::make_event_helper< Type, std::index_sequence< I... > >::operator()().
serialize()
void cata_variant::serialize (JsonOut & jsout) const
Definition at line 4490 of file savegame_json.cpp.
 {
     jsout.start_array();
     jsout.write_as_string( type_ );
     jsout.write( value_ );
     jsout.end_array();
 }
References JsonOut::end_array(), JsonOut::start_array(), JsonOut::write(), and JsonOut::write_as_string().
type()
cata_variant_type cata_variant::type () const inline
Definition at line 470 of file cata_variant.h.
{
             return type_;
         }
Referenced by achievement_requirement::check(), score::description(), value_constraint::deserialize(), is_valid_impl(), and text_for_requirement().
Member Data Documentation
value_
std::string cata_variant::value_
Definition at line 521 of file cata_variant.h.
The documentation for this class was generated from the following files:
src/cata_variant.h
src/cata_variant.cpp
src/savegame_json.cpp