Cataclysm DDA: SkillLevel Class Reference
SkillLevel Class Reference
#include <skill.h>
Public Member Functions
SkillLevel ()=default
bool isTraining () const
bool toggleTraining ()
int level () const
int level (int plevel)
int knowledgeLevel () const
int knowledgeLevel (int plevel)
int knowledgeExperience (bool raw=false) const
int rustAccumulator () const
int exercise (bool raw=false) const
int exercised_level () const
void train (int amount, float catchup_modifier, float knowledge_modifier, bool allow_multilevel=false)
void knowledge_train (int amount, int npc_knowledge=0)
bool isRusty () const
bool rust (int rust_resist, float rust_multiplier=1)
void practice ()
bool can_train () const
void set_exercise (int value, bool raw=false)
void readBook (int minimumGain, int maximumGain, int maximumLevel=-1)
bool operator== (const SkillLevel &b) const
bool operator< (const SkillLevel &b) const
bool operator> (const SkillLevel &b) const
bool operator== (const int &b) const
bool operator< (const int &b) const
bool operator> (const int &b) const
bool operator!= (const SkillLevel &b) const
bool operator<= (const SkillLevel &b) const
bool operator>= (const SkillLevel &b) const
bool operator!= (const int &b) const
bool operator<= (const int &b) const
bool operator>= (const int &b) const
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
Private Member Functions
int unadjustedLevel () const
int unadjustedKnowledgeLevel () const
void on_exercise_change (bool allow_multilevel=false)
Private Attributes
int _level = 0
int _exercise = 0
time_point _lastPracticed = calendar::turn
bool _isTraining = true
int _knowledgeLevel = 0
int _knowledgeExperience = 0
int _rustAccumulator = 0
Detailed Description
Definition at line 122 of file skill.h.
Constructor & Destructor Documentation
SkillLevel()
SkillLevel::SkillLevel () default
Member Function Documentation
can_train()
bool SkillLevel::can_train () const
Definition at line 407 of file skill.cpp.
 {
     return get_option<float>( "SKILL_TRAINING_SPEED" ) > 0.0;
 }
Referenced by item::book_info(), Character::calc_focus_equilibrium(), item::color_in_inventory(), draw_skills_tab(), read_inventory_preset::get_filter(), read_activity_actor::get_progress_message(), read_activity_actor::npc_read(), read_activity_actor::player_read(), Character::practice(), and read_inventory_preset::read_inventory_preset().
deserialize()
void SkillLevel::deserialize (const JsonObject & data)
Definition at line 467 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     data.read( "level", _level );
     data.read( "exercise", _exercise );
     if( _level < 0 ) {
         _level = 0;
         _exercise = 0;
     }
     if( _exercise < 0 ) {
         _exercise = 0;
     }
     data.read( "istraining", _isTraining );
     data.read( "rustaccumulator", _rustAccumulator );
     if( !data.read( "lastpracticed", _lastPracticed ) ) {
         _lastPracticed = calendar::start_of_game;
     }
     data.read( "knowledgeLevel", _knowledgeLevel );
     if( _knowledgeLevel < _level ) {
         _knowledgeLevel = _level;
     }
     data.read( "knowledgeExperience", _knowledgeExperience );
     if( _knowledgeLevel == _level && _knowledgeExperience < _exercise ) {
         _knowledgeExperience = _exercise;
     }
 }
References item_pocket::data, and calendar::start_of_game.
exercise()
int SkillLevel::exercise (bool raw = false) const inline
Definition at line 170 of file skill.h.
{
             return raw ? _exercise : _exercise / ( 100 * ( level() + 1 ) * ( level() + 1 ) );
         }
References _exercise, and level().
Referenced by draw_skills_info(), draw_skills_tab(), exercised_level(), SkillLevelMap::get_progress_level(), talker_character_const::get_skill_exp(), and memorial_logger::write_text_memorial().
exercised_level()
int SkillLevel::exercised_level () const inline
Definition at line 174 of file skill.h.
{
             return level() * level() * 100 + exercise();
         }
References exercise(), and level().
Referenced by set_description().
isRusty()
bool SkillLevel::isRusty () const
Definition at line 340 of file skill.cpp.
 {
     // skill is considered rusty if the practical xp lags knowledge xp by at least 1%
     return level() != knowledgeLevel() ||
            _knowledgeExperience - _exercise >= pow( level() + 1, 2U ) * 10;
 }
References _exercise, _knowledgeExperience, knowledgeLevel(), and level().
Referenced by draw_skills_info().
isTraining()
bool SkillLevel::isTraining () const inline
Definition at line 135 of file skill.h.
{
             return _isTraining;
         }
References _isTraining.
Referenced by draw_skills_info(), draw_skills_tab(), and Character::practice().
knowledge_train()
void SkillLevel::knowledge_train (int amount, int npc_knowledge = 0)
Definition at line 307 of file skill.cpp.
 {
     float level_gap = 1.0f;
     // when your _level is the same or 1 level below your knowledge, gain xp at the normal rate.
     // as your practical skill lags behind your knowledge, it gets harder to contextualize that
     // theoretical knowledge, and your ability to learn the theory gets slower.
     // The same formula applies to NPCs teaching you, but in that case the level decreases as their knowledge
     // level exceeds your own.  The best teacher is one who is only somewhat more knowledgeable than you.
     if( npc_knowledge > 0 ) {
         // This should later be modified by NPC teaching proficiencies.
         level_gap = std::max<float>( npc_knowledge - unadjustedKnowledgeLevel(), 1.0f );
     } else {
         // Some day this should be affected by json specific to the skill, some skills are more amenable
         // to book learning.
         level_gap = std::max<float>( unadjustedKnowledgeLevel() - unadjustedLevel(), 1.0f );
     }
     float level_mult = 2.0f / ( level_gap + 1.0f );
     amount *= level_mult;
     const double scaling = get_option<float>( "SKILL_TRAINING_SPEED" );
     if( scaling > 0.0 ) {
         amount = std::ceil( amount * scaling );
     }
     _knowledgeExperience += amount;
     if( _knowledgeExperience >= 10000 * pow( unadjustedKnowledgeLevel() + 1, 2U ) ) {
         _knowledgeExperience = 0;
         ++_knowledgeLevel;
     }
 }
References _knowledgeExperience, _knowledgeLevel, ceil(), unadjustedKnowledgeLevel(), and unadjustedLevel().
Referenced by readBook(), and talker_character_const::skill_training_text().
knowledgeExperience()
int SkillLevel::knowledgeExperience (bool raw = false) const inline
Definition at line 162 of file skill.h.
{
             return raw ? _knowledgeExperience : _knowledgeExperience / ( 100 * ( _knowledgeLevel + 1 ) *
                     ( _knowledgeLevel + 1 ) );
         }
References _knowledgeExperience, and _knowledgeLevel.
Referenced by draw_skills_info(), draw_skills_tab(), SkillLevelMap::get_knowledge_progress_level(), player_activity::get_progress_message(), read_activity_actor::get_progress_message(), read_activity_actor::player_read(), and talker_character_const::skill_training_text().
knowledgeLevel() [1/2]
int SkillLevel::knowledgeLevel () const inline
Definition at line 154 of file skill.h.
{
             return std::min( _knowledgeLevel, MAX_SKILL );
         }
References _knowledgeLevel, MAX_SKILL, and min().
Referenced by item::book_info(), draw_skills_info(), draw_skills_tab(), SkillLevelMap::get_knowledge_level(), player_activity::get_progress_message(), read_activity_actor::get_progress_message(), SkillLevelMap::has_same_levels_as(), isRusty(), knowledgeLevel(), SkillLevelMap::mod_knowledge_level(), read_activity_actor::npc_read(), on_exercise_change(), read_activity_actor::player_read(), read_activity_actor::read_book(), read_inventory_preset::read_inventory_preset(), readBook(), Character::set_knowledge_level(), talker_character_const::skill_training_text(), and train().
knowledgeLevel() [2/2]
int SkillLevel::knowledgeLevel (int plevel) inline
Definition at line 157 of file skill.h.
{
             _knowledgeLevel = plevel;
             return knowledgeLevel();
         }
References _knowledgeLevel, and knowledgeLevel().
level() [1/2]
int SkillLevel::level () const inline
Definition at line 143 of file skill.h.
{
             return std::min( _level, MAX_SKILL );
         }
References _level, MAX_SKILL, and min().
Referenced by draw_skills_info(), draw_skills_tab(), exercise(), exercised_level(), SkillLevelMap::get_skill_level(), Character::handle_skill_warning(), SkillLevelMap::has_same_levels_as(), isRusty(), level(), SkillLevelMap::mod_skill_level(), on_exercise_change(), operator<(), operator==(), operator>(), Character::practice(), rust(), set_exercise(), Character::set_skill_level(), train(), and memorial_logger::write_text_memorial().
level() [2/2]
int SkillLevel::level (int plevel) inline
Definition at line 146 of file skill.h.
{
             _level = plevel;
             if( _level > _knowledgeLevel ) {
                 _knowledgeLevel = _level;
             }
             return level();
         }
References _knowledgeLevel, _level, and level().
on_exercise_change()
void SkillLevel::on_exercise_change (bool allow_multilevel = false) private
Definition at line 418 of file skill.cpp.
 {
     if( _exercise < 0 ) {
         _exercise = ( 100 * 100 * pow( unadjustedLevel(), 2U ) ) - 1;
         --_level;
     } else {
         const auto xp_to_level = [&]() {
             return 100 * 100 * pow( unadjustedLevel() + 1, 2U );
         };
         while( _exercise >= xp_to_level() ) {
             _exercise = allow_multilevel ? _exercise - xp_to_level() : 0;
             ++_level;
             if( unadjustedLevel() > unadjustedKnowledgeLevel() ) {
                 _knowledgeLevel = _level;
                 _knowledgeExperience = 0;
             }
         }
         if( _rustAccumulator < 0 ) {
             _rustAccumulator = 0;
         }
         if( level() == knowledgeLevel() && _exercise > _knowledgeExperience ) {
             _knowledgeExperience = _exercise;
         }
         if( _knowledgeExperience >= 10000 * pow( unadjustedKnowledgeLevel() + 1, 2U ) ) {
             _knowledgeExperience = 0;
             ++_knowledgeLevel;
         }
     }
 }
References _exercise, _knowledgeExperience, _knowledgeLevel, _level, _rustAccumulator, knowledgeLevel(), level(), unadjustedKnowledgeLevel(), and unadjustedLevel().
Referenced by rust(), set_exercise(), and train().
operator!=() [1/2]
bool SkillLevel::operator!= (const int & b) const inline
Definition at line 219 of file skill.h.
{
             return !( *this == b );
         }
References b.
operator!=() [2/2]
bool SkillLevel::operator!= (const SkillLevel & b) const inline
Definition at line 209 of file skill.h.
{
             return !( *this == b );
         }
References b.
operator<() [1/2]
bool SkillLevel::operator< (const int & b) const inline
Definition at line 202 of file skill.h.
{
             return this->level() < b;
         }
References b, and level().
operator<() [2/2]
bool SkillLevel::operator< (const SkillLevel & b) const inline
Definition at line 192 of file skill.h.
{
             return this->level() < b.level() || ( this->level() == b.level() && this->_exercise < b._exercise );
         }
References b, and level().
operator<=() [1/2]
bool SkillLevel::operator<= (const int & b) const inline
Definition at line 222 of file skill.h.
{
             return !( *this > b );
         }
References b.
operator<=() [2/2]
bool SkillLevel::operator<= (const SkillLevel & b) const inline
Definition at line 212 of file skill.h.
{
             return !( *this > b );
         }
References b.
operator==() [1/2]
bool SkillLevel::operator== (const int & b) const inline
Definition at line 199 of file skill.h.
{
             return this->level() == b;
         }
References b, and level().
operator==() [2/2]
bool SkillLevel::operator== (const SkillLevel & b) const inline
Definition at line 189 of file skill.h.
{
             return this->level() == b.level() && this->_exercise == b._exercise;
         }
References b, and level().
operator>() [1/2]
bool SkillLevel::operator> (const int & b) const inline
Definition at line 205 of file skill.h.
{
             return this->level() > b;
         }
References b, and level().
operator>() [2/2]
bool SkillLevel::operator> (const SkillLevel & b) const inline
Definition at line 195 of file skill.h.
{
             return this->level() > b.level() || ( this->level() == b.level() && this->_exercise > b._exercise );
         }
References b, and level().
operator>=() [1/2]
bool SkillLevel::operator>= (const int & b) const inline
Definition at line 225 of file skill.h.
{
             return !( *this < b );
         }
References b.
operator>=() [2/2]
bool SkillLevel::operator>= (const SkillLevel & b) const inline
Definition at line 215 of file skill.h.
{
             return !( *this < b );
         }
References b.
practice()
void SkillLevel::practice ()
Definition at line 393 of file skill.cpp.
 {
     _lastPracticed = calendar::turn;
 }
References _lastPracticed, and calendar::turn.
Referenced by Character::practice(), readBook(), train(), and debug_menu::wishskill().
readBook()
void SkillLevel::readBook (int minimumGain, int maximumGain, int maximumLevel = -1)
Definition at line 398 of file skill.cpp.
 {
     if( knowledgeLevel() < maximumLevel || maximumLevel < 0 ) {
         knowledge_train( ( knowledgeLevel() + 1 ) * rng( minimumGain, maximumGain ) * 100 );
     }
     practice();
 }
References knowledge_train(), knowledgeLevel(), practice(), and rng().
Referenced by read_activity_actor::read_book().
rust()
bool SkillLevel::rust (int rust_resist, float rust_multiplier = 1)
Definition at line 347 of file skill.cpp.
 {
     if( ( calendar::turn - _lastPracticed ) < 24_hours ) {
         // don't rust within the grace period
         return false;
     }
     if( unadjustedLevel() >= MAX_SKILL ) {
         // don't rust any more once you hit the level cap, at least until we have a way to "pause" rust for a while.
         return false;
     }
     const int level_multiplier = pow( unadjustedLevel() + 1, 2U );
     float level_exp = level_multiplier * 10000.0f;
     if( _rustAccumulator > level_exp * 3 ) {
         // at this point the numbers ahead will be too small to bother.  Just cap it off.
         return false;
     }
     // Future plans: Have rust_slowdown impacted by intelligence and other memory-affecting things
     float rust_slowdown = std::max( static_cast<float>( std::sqrt( _rustAccumulator / level_exp ) ),
                                     0.04f );
     // rust amount starts at 4% of a level's xp, run every 24 hours.
     // Once the accumulated rust exceeds 16% of a level, rust_amount starts to drop.
     int rust_amount = level_multiplier * rust_multiplier * 16 / rust_slowdown;
     if( rust_resist > 0 ) {
         rust_amount = std::lround( rust_amount * ( std::max( ( 100 - rust_resist ), 0 ) / 100.0 ) );
     }
     if( level() == 0 ) {
         rust_amount = std::min( rust_amount, _exercise );
     }
     if( rust_amount <= 0 ) {
         return false;
     }
     _rustAccumulator += rust_amount;
     _exercise -= rust_amount;
     on_exercise_change();
     return false;
 }
References _exercise, _lastPracticed, _rustAccumulator, level(), max(), MAX_SKILL, min(), on_exercise_change(), sqrt(), calendar::turn, and unadjustedLevel().
Referenced by Character::do_skill_rust().
rustAccumulator()
int SkillLevel::rustAccumulator () const inline
Definition at line 167 of file skill.h.
{
             return _rustAccumulator;
         }
References _rustAccumulator.
serialize()
void SkillLevel::serialize (JsonOut & json) const
Definition at line 454 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "level", _level );
     json.member( "exercise", _exercise );
     json.member( "istraining", _isTraining );
     json.member( "lastpracticed", _lastPracticed );
     json.member( "knowledgeLevel", _knowledgeLevel );
     json.member( "knowledgeExperience", _knowledgeExperience );
     json.member( "rustaccumulator", _rustAccumulator );
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
set_exercise()
void SkillLevel::set_exercise (int value, bool raw = false)
Definition at line 412 of file skill.cpp.
 {
     _exercise = raw ? value : value * ( 100 * ( level() + 1 ) * ( level() + 1 ) );
     on_exercise_change( true );
 }
References _exercise, level(), and on_exercise_change().
Referenced by talker_character::set_skill_exp().
toggleTraining()
bool SkillLevel::toggleTraining () inline
Definition at line 138 of file skill.h.
{
             _isTraining = !_isTraining;
             return _isTraining;
         }
References _isTraining.
Referenced by handle_player_display_action().
train()
void SkillLevel::train (int amount, float catchup_modifier, float knowledge_modifier, bool allow_multilevel = false)
Definition at line 253 of file skill.cpp.
 {
     if( amount < 0 ) {
         debugmsg( "train() called with negative xp: %d", amount );
         return;
     }
     // catchup gets faster the higher the level gap gets.
     float level_gap = 1.0f * std::max( knowledgeLevel(), 1 ) / std::max( level(), 1 );
     float catchup_amount = amount * catchup_modifier;
     float knowledge_amount = amount * knowledge_modifier;
     if( knowledgeLevel() > level() ) {
         catchup_amount *= level_gap;
     } else if( knowledgeLevel() == level() && _knowledgeExperience > _exercise ) {
         // when you're in the same level, the catchup starts to slow down.
         catchup_amount = amount * std::max( catchup_modifier - 1.0f * _exercise / _knowledgeExperience,
                                             1.0f );
         knowledge_amount = amount * std::max( knowledge_modifier - 0.1f * _exercise / _knowledgeExperience,
                                               1.0f );
     } else {
         // When your two xp's are equal just do the basic thing.
         catchup_amount = amount * 1.0f;
         knowledge_amount = amount * 1.0f;
     }
     // Learning knowledge faster than skill, when you're actually practicing, will generate some annoying problems.
     if( knowledge_amount > catchup_amount * 0.9f ) {
         knowledge_amount = catchup_amount * 0.9f;
     }
     if( unadjustedKnowledgeLevel() >= MAX_SKILL ) {
         knowledge_amount = 0;
     }
     const double scaling = get_option<float>( "SKILL_TRAINING_SPEED" );
     if( scaling > 0.0 ) {
         catchup_amount *= scaling;
         knowledge_amount *= scaling;
     }
     _exercise += catchup_amount;
     if( _exercise < 0 ) {
         debugmsg( "integer overflow in train() amount=%d catchup_modifier=%g knowledge_modifier=%g level_gap=%g catchup_amount=%g knowledge_amount=%g scaling=%g _exercise=%d",
                   amount, catchup_modifier, knowledge_modifier, level_gap, catchup_amount, knowledge_amount, scaling,
                   _exercise );
         _exercise -= catchup_amount;
         return;
     }
     _rustAccumulator -= catchup_amount;
     _knowledgeExperience += knowledge_amount;
     on_exercise_change( allow_multilevel );
     practice();
 }
References _exercise, _knowledgeExperience, _rustAccumulator, debugmsg, knowledgeLevel(), level(), max(), MAX_SKILL, on_exercise_change(), practice(), and unadjustedKnowledgeLevel().
Referenced by Character::practice(), and Character::set_skills_from_hobbies().
unadjustedKnowledgeLevel()
int SkillLevel::unadjustedKnowledgeLevel () const inline private
Definition at line 237 of file skill.h.
{
             return _knowledgeLevel;
         }
References _knowledgeLevel.
Referenced by knowledge_train(), on_exercise_change(), and train().
unadjustedLevel()
int SkillLevel::unadjustedLevel () const inline private
Definition at line 233 of file skill.h.
{
             return _level;
         }
References _level.
Referenced by knowledge_train(), on_exercise_change(), and rust().
Member Data Documentation
_exercise
int SkillLevel::_exercise = 0 private
Definition at line 125 of file skill.h.
Referenced by exercise(), isRusty(), on_exercise_change(), rust(), set_exercise(), and train().
_isTraining
bool SkillLevel::_isTraining = true private
Definition at line 127 of file skill.h.
Referenced by isTraining(), and toggleTraining().
_knowledgeExperience
int SkillLevel::_knowledgeExperience = 0 private
Definition at line 129 of file skill.h.
Referenced by isRusty(), knowledge_train(), knowledgeExperience(), on_exercise_change(), and train().
_knowledgeLevel
int SkillLevel::_knowledgeLevel = 0 private
Definition at line 128 of file skill.h.
Referenced by knowledge_train(), knowledgeExperience(), knowledgeLevel(), level(), on_exercise_change(), and unadjustedKnowledgeLevel().
_lastPracticed
time_point SkillLevel::_lastPracticed = calendar::turn private
Definition at line 126 of file skill.h.
Referenced by practice(), and rust().
_level
int SkillLevel::_level = 0 private
Definition at line 124 of file skill.h.
Referenced by level(), on_exercise_change(), and unadjustedLevel().
_rustAccumulator
int SkillLevel::_rustAccumulator = 0 private
Definition at line 130 of file skill.h.
Referenced by on_exercise_change(), rust(), rustAccumulator(), and train().
The documentation for this class was generated from the following files:
src/skill.h
src/savegame_json.cpp
src/skill.cpp