Cataclysm DDA: jmapgen_remove_vehicles Class Reference
jmapgen_remove_vehicles Class Reference
Removes vehicles.
Public Member Functions
jmapgen_remove_vehicles (const JsonObject &jo, const std::string_view)
mapgen_phase phase () const override
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
std::vector< vproto_id > vehicles_to_remove
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Removes vehicles.
Definition at line 3419 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_remove_vehicles()
jmapgen_remove_vehicles::jmapgen_remove_vehicles (const JsonObject & jo, const std::string_view) inline
Definition at line 3423 of file mapgen.cpp.
{
             for( std::string item_id : jo.get_string_array( "vehicles" ) ) {
                 vehicles_to_remove.emplace_back( item_id );
             }
         }
References JsonObject::get_string_array(), and vehicles_to_remove.
Member Function Documentation
apply()
void jmapgen_remove_vehicles::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 3431 of file mapgen.cpp.
{
             const tripoint start( x.val, y.val, dat.zlevel() + z.get() );
             const tripoint end( x.valmax, y.valmax, dat.zlevel() + z.get() );
             const tripoint_range<tripoint> range = tripoint_range<tripoint>( start, end );
             for( const tripoint &p : range ) {
                 if( optional_vpart_position vp = dat.m.veh_at( p ) ) {
                     const auto rit = std::find( vehicles_to_remove.begin(), vehicles_to_remove.end(),
                                                 vp->vehicle().type );
                     if( rit != vehicles_to_remove.end() ) {
                         get_map().remove_vehicle_from_cache( &vp->vehicle(), start.z, end.z );
                         dat.m.destroy_vehicle( &vp->vehicle() );
                     }
                 }
             }
         }
References map::destroy_vehicle(), keycode::end, jmapgen_int::get(), get_map(), mapgendata::m, map::remove_vehicle_from_cache(), jmapgen_int::val, jmapgen_int::valmax, map::veh_at(), vehicles_to_remove, tripoint::z, and mapgendata::zlevel().
phase()
mapgen_phase jmapgen_remove_vehicles::phase () const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 3428 of file mapgen.cpp.
{
             return mapgen_phase::removal;
         }
References removal.
Member Data Documentation
vehicles_to_remove
std::vector<vproto_id> jmapgen_remove_vehicles::vehicles_to_remove
Definition at line 3422 of file mapgen.cpp.
Referenced by apply(), and jmapgen_remove_vehicles().
The documentation for this class was generated from the following file:
src/mapgen.cpp