Cataclysm DDA: string_editor_window Class Reference
string_editor_window Class Reference
Editor, to let the player edit text.
#include <string_editor_window.h>
Public Member Functions
string_editor_window (const std::function< catacurses::window()> &create_window, const std::string &text)
~string_editor_window ()
std::pair< bool, std::string > query_string ()
Private Member Functions
void print_editor (ui_adaptor &ui)
void create_context ()
void cursor_leftright (int diff)
void cursor_updown (int diff)
point get_line_and_position (int position, bool zero_x)
Private Attributes
catacurses::window _win
std::function< catacurses::window()> _create_window
point _max
utf8_wrapper _utext
std::unique_ptr< folded_text > _folded
int _position = -1
point _cursor_display
int _cursor_desired_x = -1
std::unique_ptr< ime_preview_range > _ime_preview_range
std::unique_ptr< input_context > ctxt
Detailed Description
Editor, to let the player edit text.
Example: string_editor_window ed = string_editor_window(create_window, text); new_text = ed.query_string();
Definition at line 27 of file string_editor_window.h.
Constructor & Destructor Documentation
string_editor_window()
string_editor_window::string_editor_window (const std::function< catacurses::window()> & create_window, const std::string & text)
Definition at line 200 of file string_editor_window.cpp.
 {
     _create_window = create_window;
     _utext = utf8_wrapper( text );
 }
References _create_window, and _utext.
~string_editor_window()
string_editor_window::~string_editor_window () default
Member Function Documentation
create_context()
void string_editor_window::create_context () private
Definition at line 284 of file string_editor_window.cpp.
 {
     ctxt = std::make_unique<input_context>( "STRING_EDITOR", keyboard_mode::keychar );
     ctxt->register_action( "TEXT.QUIT" );
     ctxt->register_action( "TEXT.CONFIRM" );
     ctxt->register_action( "TEXT.LEFT" );
     ctxt->register_action( "TEXT.RIGHT" );
     ctxt->register_action( "TEXT.UP" );
     ctxt->register_action( "TEXT.DOWN" );
     ctxt->register_action( "TEXT.CLEAR" );
     ctxt->register_action( "TEXT.BACKSPACE" );
     ctxt->register_action( "TEXT.HOME" );
     ctxt->register_action( "TEXT.END" );
     ctxt->register_action( "TEXT.PAGE_UP" );
     ctxt->register_action( "TEXT.PAGE_DOWN" );
     ctxt->register_action( "TEXT.DELETE" );
 #if defined(TILES)
     ctxt->register_action( "TEXT.PASTE" );
 #endif
     ctxt->register_action( "TEXT.INPUT_FROM_FILE" );
     ctxt->register_action( "HELP_KEYBINDINGS" );
     ctxt->register_action( "ANY_INPUT" );
 }
References ctxt, and keychar.
Referenced by query_string().
cursor_leftright()
void string_editor_window::cursor_leftright (int diff) private
Definition at line 308 of file string_editor_window.cpp.
 {
     const int size = _utext.size();
     if( diff < 0 && _position <= 0 ) {
         // Warp to end
         _position = size;
     } else if( diff > 0 && _position >= size ) {
         // Warp to start
         _position = 0;
     } else {
         // Move at most `diff` codepoints without warping
         _position = clamp( _position + diff, 0, size );
     }
 }
References _position, _utext, clamp(), utf8_wrapper::size(), and om_direction::size.
Referenced by query_string().
cursor_updown()
void string_editor_window::cursor_updown (int diff) private
Definition at line 323 of file string_editor_window.cpp.
 {
     if( diff != 0 && !_folded->get_lines().empty() ) {
         const int size = _folded->get_lines().size();
         int new_y = 0;
         if( diff < 0 && _cursor_display.y <= 0 ) {
             // Warp to last line
             new_y = size - 1;
         } else if( diff > 0 && _cursor_display.y >= size - 1 ) {
             // Warp to first line
             new_y = 0;
         } else {
             // Move at most `diff` lines without warping
             new_y = clamp( _cursor_display.y + diff, 0, size - 1 );
         }
         const folded_line &new_line = _folded->get_lines()[new_y];
         utf8_wrapper ustr( new_line.str );
         if( !ustr.empty() && is_linebreak( ustr.at( ustr.size() - 1 ) ) ) {
             ustr = ustr.substr( 0, ustr.size() - 1 );
         }
         // Put cursor at tbe largest x coordinate in the line less or equal to
         // the desired position.
         const int offset = ustr.substr_display( 0, _cursor_desired_x ).size();
         _position = new_line.cpts_start + offset;
     }
 }
References _cursor_desired_x, _cursor_display, _folded, _position, utf8_wrapper::at(), clamp(), folded_line::cpts_start, utf8_wrapper::empty(), is_linebreak(), utf8_wrapper::size(), om_direction::size, folded_line::str, utf8_wrapper::substr(), utf8_wrapper::substr_display(), and point::y.
Referenced by query_string().
get_line_and_position()
point string_editor_window::get_line_and_position (int position, bool zero_x) private
Definition at line 210 of file string_editor_window.cpp.
 {
     return _folded->codepoint_coordinates( position, zero_x );
 }
References _folded.
Referenced by query_string().
print_editor()
void string_editor_window::print_editor (ui_adaptor & ui) private
Definition at line 215 of file string_editor_window.cpp.
 {
     const point focus = _ime_preview_range ? _ime_preview_range->display_last : _cursor_display;
     const int ftsize = _folded->get_lines().size();
     const int middleofpage = _max.y / 2;
     int topoflist = 0;
     int bottomoflist = std::min( topoflist + _max.y, ftsize );
     if( _max.y <= ftsize ) {
         if( focus.y > middleofpage ) {
             topoflist = focus.y - middleofpage;
             bottomoflist = topoflist + _max.y;
         }
         if( focus.y + middleofpage >= ftsize ) {
             bottomoflist = ftsize ;
             topoflist = bottomoflist - _max.y;
         }
     }
     for( int i = topoflist; i < bottomoflist; i++ ) {
         const int y = i - topoflist;
         const folded_line &line = _folded->get_lines()[i];
         mvwprintz( _win, point( 1, y ), c_white, "%s", line.str );
         if( !_ime_preview_range && i == _cursor_display.y ) {
             uint32_t c_cursor = 0;
             const char *src = line.str.c_str();
             int len = line.str.length();
             int cpts = line.cpts_start;
             // display the cursor as the first non-zero-width character after
             // the cursor position if any
             while( len > 0 && ( cpts <= _position || mk_wcwidth( c_cursor ) < 1 ) ) {
                 c_cursor = UTF8_getch( &src, &len );
                 cpts += 1;
             }
             // but display cursor as space at end of line
             if( cpts <= _position || c_cursor == 0
                 || is_linebreak( c_cursor ) || mk_wcwidth( c_cursor ) < 1 ) {
                 c_cursor = ' ';
             }
             const point cursor_pos( _cursor_display.x + 1, y );
             mvwprintz( _win, cursor_pos, h_white, "%s", utf32_to_utf8( c_cursor ) );
             ui.set_cursor( _win, cursor_pos );
         }
         if( _ime_preview_range && i >= _ime_preview_range->display_first.y
             && i <= _ime_preview_range->display_last.y ) {
             const int beg = std::max( 0, _ime_preview_range->begin - line.cpts_start );
             const int end = std::min( _ime_preview_range->end, line.cpts_end ) - line.cpts_start;
             const utf8_wrapper preview = utf8_wrapper( line.str ).substr( beg, end - beg );
             const point disp = i == _ime_preview_range->display_first.y
                                ? point( _ime_preview_range->display_first.x + 1, y )
                                : point( 1, y );
             mvwprintz( _win, disp, c_dark_gray_white, "%s", preview.str() );
         }
     }
     if( _ime_preview_range ) {
         const point cursor_pos = _ime_preview_range->display_last + point( 1, -topoflist );
         ui.set_cursor( _win, cursor_pos );
     }
     if( ftsize > _max.y ) {
         scrollbar()
         .content_size( ftsize )
         .viewport_pos( topoflist )
         .viewport_size( _max.y )
         .apply( _win );
     }
 }
References _cursor_display, _folded, _ime_preview_range, _max, _position, _win, scrollbar::apply(), c_dark_gray_white, c_white, scrollbar::content_size(), keycode::end, focus, h_white, is_linebreak(), line, max(), min(), mk_wcwidth(), mvwprintz(), point, utf8_wrapper::str(), utf8_wrapper::substr(), utf32_to_utf8(), UTF8_getch(), scrollbar::viewport_pos(), scrollbar::viewport_size(), point::x, and point::y.
Referenced by query_string().
query_string()
std::pair< bool, std::string > string_editor_window::query_string ()
Definition at line 350 of file string_editor_window.cpp.
 {
     if( !ctxt ) {
         create_context();
     }
     utf8_wrapper edit( ctxt->get_edittext() );
     if( _position == -1 ) {
         _position = _utext.length();
     }
     // fold the text
     bool refold = true;
     // calculate the cursor position
     bool reposition = true;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         _win = _create_window();
         _max.x = getmaxx( _win );
         _max.y =  getmaxy( _win );
         _cursor_desired_x = -1;
         refold = true;
         ui.position_from_window( _win );
     } );
     ui.mark_resize();
     ui.on_redraw( [&]( ui_adaptor & ui ) {
         if( refold ) {
             utf8_wrapper text = _utext;
             if( !edit.empty() ) {
                 text.insert( _position, edit );
             }
             _folded = std::make_unique<folded_text>( text.str(), _max.x - 2 );
             refold = false;
             reposition = true;
         }
         if( reposition ) {
             _cursor_display = get_line_and_position( _position, _cursor_desired_x == 0 );
             if( _cursor_desired_x < 0 ) {
                 _cursor_desired_x = _cursor_display.x;
             }
             if( edit.empty() ) {
                 _ime_preview_range.reset();
             } else {
                 _ime_preview_range = std::make_unique<ime_preview_range>( ime_preview_range {
                     _position, _position + static_cast<int>( edit.size() ),
                     _cursor_display, get_line_and_position( _position + edit.size() - 1, true )
                 } );
             }
             reposition = false;
         }
         werase( _win );
         print_editor( ui );
         wnoutrefresh( _win );
     } );
 #if defined(__ANDROID__)
     on_out_of_scope stop_text_input( []() {
         if( get_option<bool>( "ANDROID_AUTO_KEYBOARD" ) ) {
             StopTextInput();
         }
     } );
 #endif
     int ch = 0;
     do {
         ui_manager::redraw();
         const std::string action = ctxt->handle_input();
         const input_event ev = ctxt->get_raw_input();
         ch = ev.type == input_event_t::keyboard_char ? ev.get_first_input() : 0;
         if( action == "TEXT.QUIT" ) {
             return { false, _utext.str() };
         } else if( action == "TEXT.CONFIRM" ) {
             return { true, _utext.str() };
         } else if( action == "TEXT.UP" ) {
             if( edit.empty() ) {
                 cursor_updown( -1 );
                 reposition = true;
             }
         } else if( action == "TEXT.DOWN" ) {
             if( edit.empty() ) {
                 cursor_updown( 1 );
                 reposition = true;
             }
         } else if( action == "TEXT.RIGHT" ) {
             if( edit.empty() ) {
                 cursor_leftright( 1 );
                 _cursor_desired_x = -1;
                 reposition = true;
             }
         } else if( action == "TEXT.LEFT" ) {
             if( edit.empty() ) {
                 cursor_leftright( -1 );
                 _cursor_desired_x = -1;
                 reposition = true;
             }
         } else if( action == "TEXT.CLEAR" ) {
             _position = 0;
             _cursor_desired_x = -1;
             _utext.erase( 0 );
             refold = true;
         } else if( action == "TEXT.BACKSPACE" ) {
             if( _position > 0 && _position <= static_cast<int>( _utext.size() ) ) {
                 _position--;
                 _cursor_desired_x = -1;
                 _utext.erase( _position, 1 );
                 refold = true;
             }
         } else if( action == "TEXT.HOME" ) {
             if( edit.empty()
                 && static_cast<size_t>( _cursor_display.y ) < _folded->get_lines().size() ) {
                 _position = _folded->get_lines()[_cursor_display.y].cpts_start;
                 // put the cursor at line start rather than the previous line end
                 _cursor_desired_x = 0;
                 reposition = true;
             }
         } else if( action == "TEXT.END" ) {
             if( edit.empty()
                 && static_cast<size_t>( _cursor_display.y ) < _folded->get_lines().size() ) {
                 _position = _folded->get_lines()[_cursor_display.y].cpts_end;
                 const utf8_wrapper ustr( _folded->get_lines()[_cursor_display.y].str );
                 if( is_linebreak( ustr.at( ustr.size() - 1 ) ) ) {
                     --_position;
                 }
                 _cursor_desired_x = -1;
                 reposition = true;
             }
         } else if( action == "TEXT.PAGE_UP" ) {
             if( edit.empty() ) {
                 cursor_updown( -_max.y );
                 reposition = true;
             }
         } else if( action == "TEXT.PAGE_DOWN" ) {
             if( edit.empty() ) {
                 cursor_updown( _max.y );
                 reposition = true;
             }
         } else if( action == "TEXT.DELETE" ) {
             if( _position < static_cast<int>( _utext.size() ) ) {
                 _cursor_desired_x = -1;
                 _utext.erase( _position, 1 );
                 refold = true;
             }
         } else if( action == "TEXT.PASTE" || action == "TEXT.INPUT_FROM_FILE"
                    || !ev.text.empty() || ch == KEY_ENTER || ch == '\n' ) {
             // paste, input from file, or text input
             std::string entered;
             if( action == "TEXT.PASTE" ) {
 #if defined(TILES)
                 if( edit.empty() ) {
                     char *const clip = SDL_GetClipboardText();
                     if( clip ) {
                         entered = clip;
                         SDL_free( clip );
                     }
                 }
 #endif
             } else if( action == "TEXT.INPUT_FROM_FILE" ) {
                 if( edit.empty() ) {
                     entered = get_input_string_from_file();
                 }
             } else if( ch == KEY_ENTER || ch == '\n' ) {
                 if( edit.empty() ) {
                     entered = "\n";
                 }
             } else {
                 entered = ev.text;
             }
             if( !entered.empty() ) {
                 utf8_wrapper insertion;
                 const char *str = entered.c_str();
                 int len = entered.length();
                 while( len > 0 ) {
                     const uint32_t ch = UTF8_getch( &str, &len );
                     // Use mk_wcwidth to filter out control characters
                     if( ch == '\n' || mk_wcwidth( ch ) >= 0 ) {
                         insertion.append( utf8_wrapper( utf32_to_utf8( ch ) ) );
                     }
                 }
                 _utext.insert( _position, insertion );
                 _position += insertion.length();
                 _cursor_desired_x = -1;
                 edit = utf8_wrapper();
                 refold = true;
                 ctxt->set_edittext( std::string() );
             }
         } else if( ev.edit_refresh ) {
             edit = utf8_wrapper( ev.edit );
             refold = true;
             ctxt->set_edittext( ev.edit );
         }
     } while( true );
     return { false, _utext.str() };
 }
References _create_window, _cursor_desired_x, _cursor_display, _folded, _ime_preview_range, _max, _position, _utext, _win, action, utf8_wrapper::at(), create_context(), ctxt, cursor_leftright(), cursor_updown(), input_event::edit, input_event::edit_refresh, utf8_wrapper::empty(), utf8_wrapper::erase(), input_event::get_first_input(), get_input_string_from_file(), get_line_and_position(), catacurses::getmaxx(), catacurses::getmaxy(), utf8_wrapper::insert(), insertion, is_linebreak(), KEY_ENTER, keyboard_char, utf8_wrapper::length(), mk_wcwidth(), print_editor(), ui_manager::redraw(), utf8_wrapper::size(), StopTextInput(), utf8_wrapper::str(), input_event::text, input_event::type, utf32_to_utf8(), UTF8_getch(), catacurses::werase(), catacurses::wnoutrefresh(), point::x, and point::y.
Referenced by diary::edit_page_ui().
Member Data Documentation
_create_window
std::function<catacurses::window()> string_editor_window::_create_window private
Definition at line 33 of file string_editor_window.h.
Referenced by query_string(), and string_editor_window().
_cursor_desired_x
int string_editor_window::_cursor_desired_x = -1 private
Definition at line 46 of file string_editor_window.h.
Referenced by cursor_updown(), and query_string().
_cursor_display
point string_editor_window::_cursor_display private
Definition at line 44 of file string_editor_window.h.
Referenced by cursor_updown(), print_editor(), and query_string().
_folded
std::unique_ptr<folded_text> string_editor_window::_folded private
Definition at line 39 of file string_editor_window.h.
Referenced by cursor_updown(), get_line_and_position(), print_editor(), and query_string().
_ime_preview_range
std::unique_ptr<ime_preview_range> string_editor_window::_ime_preview_range private
Definition at line 48 of file string_editor_window.h.
Referenced by print_editor(), and query_string().
_max
point string_editor_window::_max private
Definition at line 35 of file string_editor_window.h.
Referenced by print_editor(), and query_string().
_position
int string_editor_window::_position = -1 private
Definition at line 42 of file string_editor_window.h.
Referenced by cursor_leftright(), cursor_updown(), print_editor(), and query_string().
_utext
utf8_wrapper string_editor_window::_utext private
Definition at line 37 of file string_editor_window.h.
Referenced by cursor_leftright(), query_string(), and string_editor_window().
_win
catacurses::window string_editor_window::_win private
Definition at line 31 of file string_editor_window.h.
Referenced by print_editor(), and query_string().
ctxt
std::unique_ptr<input_context> string_editor_window::ctxt private
Definition at line 50 of file string_editor_window.h.
Referenced by create_context(), and query_string().
The documentation for this class was generated from the following files:
src/string_editor_window.h
src/string_editor_window.cpp