Cataclysm DDA: longsalvage_activity_actor Class Reference
longsalvage_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
longsalvage_activity_actor ()=default
longsalvage_activity_actor (int index)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int index
Detailed Description
Definition at line 2050 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
longsalvage_activity_actor() [1/2]
longsalvage_activity_actor::longsalvage_activity_actor () default
longsalvage_activity_actor() [2/2]
longsalvage_activity_actor::longsalvage_activity_actor (int index) inline explicit
Definition at line 2054 of file activity_actor_definitions.h.
 : index( index ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> longsalvage_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 2064 of file activity_actor_definitions.h.
{
             return std::make_unique<longsalvage_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > longsalvage_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6914 of file activity_actor.cpp.
 {
     longsalvage_activity_actor actor( {} );
     JsonObject data = jsin.get_object();
     data.read( "index", actor.index );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void longsalvage_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 2061 of file activity_actor_definitions.h.
 {};
finish()
void longsalvage_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 6870 of file activity_actor.cpp.
 {
     static const std::string salvage_string = "salvage";
     item &main_tool = who.i_at( act.index );
     map &here = get_map();
     map_stack items = here.i_at( who.pos() );
     item *salvage_tool = main_tool.get_usable_item( salvage_string );
     if( salvage_tool == nullptr ) {
         debugmsg( "Lost tool used for long salvage" );
         act.set_to_null();
         return;
     }
     const use_function *use_fun = salvage_tool->get_use( salvage_string );
     const salvage_actor *actor = dynamic_cast<const salvage_actor *>( use_fun->get_actor_ptr() );
     if( actor == nullptr ) {
         debugmsg( "iuse_actor type descriptor and actual type mismatch" );
         act.set_to_null();
         return;
     }
     for( item &it : items ) {
         // Check first and only if possible attempt it with player char
         // This suppresses warnings unless it is an item the player wears
         if( actor->valid_to_cut_up( nullptr, it ) ) {
             item_location item_loc( map_cursor( who.pos() ), &it );
             actor->try_to_cut_up( who, *salvage_tool, item_loc );
             return;
         }
     }
     add_msg( _( "You finish salvaging." ) );
     act.set_to_null();
 }
References _, act, add_msg(), debugmsg, use_function::get_actor_ptr(), get_map(), item::get_usable_item(), item::get_use(), map::i_at(), Character::i_at(), Creature::pos(), salvage_actor::try_to_cut_up(), and salvage_actor::valid_to_cut_up().
get_type()
activity_id longsalvage_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 2056 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_LONGSALVAGE" );
         }
References activity_id.
serialize()
void longsalvage_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6905 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "index", index );
     jsout.end_object();
 }
References JsonOut::end_object(), index, JsonOut::member(), and JsonOut::start_object().
start()
void longsalvage_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 6861 of file activity_actor.cpp.
 {
     act.index = index;
     //todo: refactor the actor to process items in ::do_turn, then remove setting the moves to 0
     //this currently still can't get interrupted before you get attacked
     act.moves_left = 0;
 }
References act, and index.
Member Data Documentation
index
int longsalvage_activity_actor::index private
Definition at line 2072 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp