Cataclysm DDA: jmapgen_nested Class Reference
jmapgen_nested Class Reference
Calls another mapgen call inside the current one.
Classes
class correct_z_level_check
class neighbor_flag_any_check
class neighbor_flag_check
class neighbor_join_check
class neighbor_oter_check
class predecessor_oter_check
Public Member Functions
jmapgen_nested (const JsonObject &jsi, const std::string_view)
mapgen_phase phase () const override
void merge_parameters_into (mapgen_parameters &params, const std::string &outer_context) const override
const weighted_int_list< mapgen_value< nested_mapgen_id > > & get_entries (const mapgendata &dat) const
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &context) const override
Place something on the map from mapgendata &dat, at (x,y).
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z) const override
Sanity-check this piece.
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual ~jmapgen_piece ()=default
Public Attributes
weighted_int_list< mapgen_value< nested_mapgen_id > > entries
weighted_int_list< mapgen_value< nested_mapgen_id > > else_entries
neighbor_oter_check neighbor_oters
neighbor_join_check neighbor_joins
neighbor_flag_check neighbor_flags
neighbor_flag_any_check neighbor_flags_any
predecessor_oter_check predecessors
correct_z_level_check correct_z_level
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Calls another mapgen call inside the current one.
Note: can't use regular overmap ids.
Parameters
entries list of pairs [nested mapgen id, weight].
Definition at line 3517 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_nested()
jmapgen_nested::jmapgen_nested (const JsonObject & jsi, const std::string_view) inline
Definition at line 3743 of file mapgen.cpp.
             : neighbor_oters( jsi.get_object( "neighbors" ) )
             , neighbor_joins( jsi.get_object( "joins" ) )
             , neighbor_flags( jsi.get_object( "flags" ) )
             , neighbor_flags_any( jsi.get_object( "flags_any" ) )
             , predecessors( jsi.get_array( "predecessors" ) )
             , correct_z_level( jsi.get_array( "check_z" ) ) {
             if( jsi.has_member( "chunks" ) ) {
                 load_weighted_list( jsi.get_member( "chunks" ), entries, 100 );
             }
             if( jsi.has_member( "else_chunks" ) ) {
                 load_weighted_list( jsi.get_member( "else_chunks" ), else_entries, 100 );
             }
         }
References else_entries, entries, JsonObject::get_member(), JsonObject::has_member(), mapgen_defer::jsi, and load_weighted_list().
Member Function Documentation
apply()
void jmapgen_nested::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 3794 of file mapgen.cpp.
{
             const mapgen_value<nested_mapgen_id> *val = get_entries( dat ).pick();
             if( val == nullptr ) {
                 return;
             }
             const nested_mapgen_id res = val->get( dat );
             if( res.is_empty() || res.is_null() ) {
                 // This will be common when neighbors.test(...) is false, since else_entires is
                 // often empty.
                 return;
             }
             const auto iter = nested_mapgens.find( res );
             if( iter == nested_mapgens.end() ) {
                 debugmsg( "Unknown nested mapgen function id %s", res.str() );
                 return;
             }
             // A second roll? Let's allow it for now
             const auto &ptr = iter->second.funcs().pick();
             if( ptr == nullptr ) {
                 return;
             }
             ( *ptr )->nest( dat, tripoint_rel_ms( x.get(), y.get(), z.get() ), context );
         }
References context, debugmsg, jmapgen_int::get(), mapgen_value< Id >::get(), get_entries(), string_id< T >::is_empty(), string_id< T >::is_null(), nested_mapgens, and string_id< T >::str().
check()
void jmapgen_nested::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 3821 of file mapgen.cpp.
{
             for( const weighted_object<int, mapgen_value<nested_mapgen_id>> &p : entries ) {
                 p.obj.check( oter_name, parameters );
             }
             for( const weighted_object<int, mapgen_value<nested_mapgen_id>> &p : else_entries ) {
                 p.obj.check( oter_name, parameters );
             }
             neighbor_joins.check( oter_name, parameters );
             // Check whether any of the nests can attempt to place stuff out of
             // bounds
             std::unordered_map<point, nested_mapgen_id> nest_placement_coords;
             auto add_coords_from = [&]( const mapgen_value<nested_mapgen_id> &nest_id_val ) {
                 for( const nested_mapgen_id &nest_id :
                      nest_id_val.all_possible_results( parameters ) ) {
                     if( nest_id.is_null() ) {
                         continue;
                     }
                     for( const point &p : nest_id->all_placement_coords() ) {
                         nest_placement_coords.emplace( p, nest_id );
                     }
                 }
             };
             for( const weighted_object<int, mapgen_value<nested_mapgen_id>> &p : entries ) {
                 add_coords_from( p.obj );
             }
             for( const weighted_object<int, mapgen_value<nested_mapgen_id>> &p : else_entries ) {
                 add_coords_from( p.obj );
             }
             point max_relative;
             nested_mapgen_id offending_nest_x;
             nested_mapgen_id offending_nest_y;
             for( const std::pair<const point, nested_mapgen_id> &p : nest_placement_coords ) {
                 if( p.first.x > max_relative.x ) {
                     max_relative.x = p.first.x;
                     offending_nest_x = p.second;
                 }
                 if( p.first.y > max_relative.y ) {
                     max_relative.y = p.first.y;
                     offending_nest_y = p.second;
                 }
             }
             static constexpr int omt_size = SEEX * 2;
             point max = point( x.valmax % omt_size, y.valmax % omt_size ) + max_relative;
             if( max.x >= omt_size ) {
                 debugmsg( "nest %s within %s can place something at x = %d, which is in a "
                           "different OMT from the smallest nest origin (%d, %d), and could lead to "
                           "an out of bounds placement",
                           offending_nest_x.str(), oter_name, x.valmax + max_relative.x, x.val,
                           y.val );
             }
             if( max.y >= omt_size ) {
                 debugmsg( "nest %s within %s can place something at y = %d, which is in a "
                           "different OMT from the smallest nest origin (%d, %d), and could lead to "
                           "an out of bounds placement",
                           offending_nest_y.str(), oter_name, y.valmax + max_relative.y, x.val,
                           y.val );
             }
             if( z.val != z.valmax ) {
                 debugmsg( "nest %s within %s defines a range for Z level placement, which isn't"
                           "permitted.  Range: %d - %d.",
                           offending_nest_x.str(), oter_name, z.val, z.valmax );
             }
         }
References jmapgen_nested::neighbor_join_check::check(), debugmsg, else_entries, entries, max(), neighbor_joins, point, SEEX, string_id< T >::str(), jmapgen_int::val, jmapgen_int::valmax, point::x, and point::y.
get_entries()
const weighted_int_list<mapgen_value<nested_mapgen_id> >& jmapgen_nested::get_entries (const mapgendata & dat) const inline
Definition at line 3785 of file mapgen.cpp.
{
             if( neighbor_oters.test( dat ) && neighbor_joins.test( dat ) && neighbor_flags.test( dat ) &&
                 neighbor_flags_any.test( dat ) && predecessors.test( dat ) && correct_z_level.test( dat ) ) {
                 return entries;
             } else {
                 return else_entries;
             }
         }
References correct_z_level, else_entries, entries, neighbor_flags, neighbor_flags_any, neighbor_joins, neighbor_oters, predecessors, jmapgen_nested::neighbor_oter_check::test(), jmapgen_nested::neighbor_join_check::test(), jmapgen_nested::neighbor_flag_check::test(), jmapgen_nested::neighbor_flag_any_check::test(), jmapgen_nested::predecessor_oter_check::test(), and jmapgen_nested::correct_z_level_check::test().
Referenced by apply(), and has_vehicle_collision().
has_vehicle_collision()
bool jmapgen_nested::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 3892 of file mapgen.cpp.
{
             const weighted_int_list<mapgen_value<nested_mapgen_id>> &selected_entries =
                         get_entries( dat );
             if( selected_entries.empty() ) {
                 return false;
             }
             for( const auto &entry : selected_entries ) {
                 nested_mapgen_id id = entry.obj.get( dat );
                 if( id.is_null() ) {
                     continue;
                 }
                 const auto iter = nested_mapgens.find( id );
                 if( iter == nested_mapgens.end() ) {
                     return false;
                 }
                 for( const auto &nest : iter->second.funcs() ) {
                     if( nest.obj->has_vehicle_collision( dat, p ) ) {
                         return true;
                     }
                 }
             }
             return false;
         }
References weighted_list< W, T >::empty(), get_entries(), nest, nested_mapgens, and string_id< T >::obj().
merge_parameters_into()
void jmapgen_nested::merge_parameters_into (mapgen_parameters & params, const std::string & outer_context) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 3760 of file mapgen.cpp.
{
             auto merge_from = [&]( const mapgen_value<nested_mapgen_id> &val ) {
                 for( const nested_mapgen_id &id : val.all_possible_results( params ) ) {
                     if( id.is_null() ) {
                         return;
                     }
                     const auto iter = nested_mapgens.find( id );
                     if( iter == nested_mapgens.end() ) {
                         debugmsg( "Unknown nested mapgen function id '%s'", id.str() );
                         return;
                     }
                     using Obj = weighted_object<int, std::shared_ptr<mapgen_function_json_nested>>;
                     for( const Obj &nested : iter->second.funcs() ) {
                         nested.obj->merge_non_nest_parameters_into( params, outer_context );
                     }
                 }
             };
             for( const weighted_object<int, mapgen_value<nested_mapgen_id>> &name : entries ) {
                 merge_from( name.obj );
             }
             for( const weighted_object<int, mapgen_value<nested_mapgen_id>> &name : else_entries ) {
                 merge_from( name.obj );
             }
         }
References debugmsg, else_entries, entries, om_direction::name(), nested_mapgens, and weighted_object< W, T >::obj.
phase()
mapgen_phase jmapgen_nested::phase () const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 3757 of file mapgen.cpp.
{
             return mapgen_phase::nested_mapgen;
         }
References nested_mapgen.
Member Data Documentation
correct_z_level
correct_z_level_check jmapgen_nested::correct_z_level
Definition at line 3742 of file mapgen.cpp.
Referenced by get_entries().
else_entries
weighted_int_list<mapgen_value<nested_mapgen_id> > jmapgen_nested::else_entries
Definition at line 3736 of file mapgen.cpp.
Referenced by check(), get_entries(), jmapgen_nested(), and merge_parameters_into().
entries
weighted_int_list<mapgen_value<nested_mapgen_id> > jmapgen_nested::entries
Definition at line 3735 of file mapgen.cpp.
Referenced by check(), get_entries(), jmapgen_nested(), and merge_parameters_into().
neighbor_flags
neighbor_flag_check jmapgen_nested::neighbor_flags
Definition at line 3739 of file mapgen.cpp.
Referenced by get_entries().
neighbor_flags_any
neighbor_flag_any_check jmapgen_nested::neighbor_flags_any
Definition at line 3740 of file mapgen.cpp.
Referenced by get_entries().
neighbor_joins
neighbor_join_check jmapgen_nested::neighbor_joins
Definition at line 3738 of file mapgen.cpp.
Referenced by check(), and get_entries().
neighbor_oters
neighbor_oter_check jmapgen_nested::neighbor_oters
Definition at line 3737 of file mapgen.cpp.
Referenced by get_entries().
predecessors
predecessor_oter_check jmapgen_nested::predecessors
Definition at line 3741 of file mapgen.cpp.
Referenced by get_entries(), and jmapgen_nested::predecessor_oter_check::test().
The documentation for this class was generated from the following file:
src/mapgen.cpp