Cataclysm DDA: iteminfo_query Class Reference
iteminfo_query Class Reference
#include <iteminfo_query.h>
Public Member Functions
iteminfo_query ()
iteminfo_query (const iteminfo_query_base &values)
iteminfo_query (const std::string &bits)
iteminfo_query (const std::vector< iteminfo_parts > &setBits)
bool test (const iteminfo_parts &value) const
Static Public Attributes
static const iteminfo_query all
static const iteminfo_query notext
static const iteminfo_query anyflags
Detailed Description
Definition at line 258 of file iteminfo_query.h.
Constructor & Destructor Documentation
iteminfo_query() [1/4]
iteminfo_query::iteminfo_query () default
iteminfo_query() [2/4]
iteminfo_query::iteminfo_query (const iteminfo_query_base & values) explicit
Definition at line 19 of file iteminfo_query.cpp.
     : iteminfo_query_base( values )
 {
 }
iteminfo_query() [3/4]
iteminfo_query::iteminfo_query (const std::string & bits) explicit
Definition at line 8 of file iteminfo_query.cpp.
                                                       : iteminfo_query_base( bits )
 {
 }
iteminfo_query() [4/4]
iteminfo_query::iteminfo_query (const std::vector< iteminfo_parts > & setBits) explicit
Definition at line 12 of file iteminfo_query.cpp.
 {
     for( const iteminfo_parts &bit : setBits ) {
         set( static_cast<size_t>( bit ) );
     }
 }
Member Function Documentation
test()
bool iteminfo_query::test (const iteminfo_parts & value) const
Definition at line 24 of file iteminfo_query.cpp.
 {
     return iteminfo_query_base::test( static_cast<size_t>( value ) );
 }
Referenced by item::actions_info(), item::ammo_info(), item::armor_attribute_info(), item::armor_fit_info(), item::armor_info(), item::armor_material_info(), item::armor_protection_info(), item::basic_info(), item::bionic_info(), item::book_info(), item::component_info(), item::contents_info(), item::debug_info(), item::disassembly_info(), item::enchantment_info(), item::final_info(), item::food_info(), item::gun_info(), item::gunmod_info(), item_contents::info(), item::info(), item::magazine_info(), item::med_info(), item::melee_combat_info(), item::pet_armor_protection_info(), item::properties_info(), item::qualities_info(), item::repair_info(), item::rot_info(), and item::tool_info().
Member Data Documentation
all
const iteminfo_query iteminfo_query::all static
Initial value:
= iteminfo_query(
            std::string( static_cast<size_t>( iteminfo_parts::NUM_VALUES ), '1' ) )
Definition at line 296 of file iteminfo_query.h.
Referenced by item::info().
anyflags
const iteminfo_query iteminfo_query::anyflags static
Initial value:
= iteminfo_query(
std::vector<iteminfo_parts> {
    iteminfo_parts::DESCRIPTION_FLAGS,
    iteminfo_parts::DESCRIPTION_FLAGS_HELMETCOMPAT,
    iteminfo_parts::DESCRIPTION_FLAGS_FITS,
    iteminfo_parts::DESCRIPTION_FLAGS_VARSIZE,
    iteminfo_parts::DESCRIPTION_FLAGS_SIDED,
    iteminfo_parts::DESCRIPTION_FLAGS_POWERARMOR,
    iteminfo_parts::DESCRIPTION_FLAGS_POWERARMOR_RADIATIONHINT,
    iteminfo_parts::DESCRIPTION_IRRADIATION
})
Definition at line 298 of file iteminfo_query.h.
notext
const iteminfo_query iteminfo_query::notext static
Definition at line 297 of file iteminfo_query.h.
Referenced by item::info().
The documentation for this class was generated from the following files:
src/iteminfo_query.h
src/iteminfo_query.cpp