Cataclysm DDA: sew_advanced_actor Class Reference
sew_advanced_actor Class Reference
Modify clothing.
#include <iuse_actor.h>
Public Member Functions
sew_advanced_actor (const std::string &type="sew_advanced")
~sew_advanced_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
std::set< material_id > materials
Materials.
std::vector< clothing_mod_id > clothing_mods
Clothing mods.
skill_id used_skill
Skill used.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Modify clothing.
Definition at line 1150 of file iuse_actor.h.
Constructor & Destructor Documentation
sew_advanced_actor()
sew_advanced_actor::sew_advanced_actor (const std::string & type = "sew_advanced") inline explicit
Definition at line 1160 of file iuse_actor.h.
 : iuse_actor( type ) {}
~sew_advanced_actor()
sew_advanced_actor::~sew_advanced_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > sew_advanced_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 5498 of file iuse_actor.cpp.
 {
     return std::make_unique<sew_advanced_actor>( *this );
 }
load()
void sew_advanced_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 5261 of file iuse_actor.cpp.
 {
     // Mandatory:
     for( const std::string line : obj.get_array( "materials" ) ) {
         materials.emplace( line );
     }
     for( const std::string line : obj.get_array( "clothing_mods" ) ) {
         clothing_mods.emplace_back( line );
     }
     // TODO: Make skill non-mandatory while still erroring on invalid skill
     const std::string skill_string = obj.get_string( "skill" );
     used_skill = skill_id( skill_string );
     if( !used_skill.is_valid() ) {
         obj.throw_error_at( "skill", "Invalid skill" );
     }
 }
References JsonObject::get_array(), JsonObject::get_string(), line, skill_id, and JsonObject::throw_error_at().
use()
std::optional< int > sew_advanced_actor::use (Character * p, item & it, const tripoint &) const override virtual
Tailor randomly improves clothing modification efforts Dexterity randomly improves clothing modification efforts Perception randomly improves clothing modification efforts
Implements iuse_actor.
Definition at line 5279 of file iuse_actor.cpp.
 {
     if( p->is_npc() ) {
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( p->fine_detail_vision_mod() > 4 ) {
         add_msg( m_info, _( "You can't see to sew!" ) );
         return std::nullopt;
     }
     auto filter = [this]( const item & itm ) {
         return itm.is_armor() && !itm.is_firearm() && !itm.is_power_armor() && !itm.is_gunmod() &&
                itm.made_of_any( materials ) && !itm.has_flag( flag_INTEGRATED );
     };
     // note: if !p.is_npc() then p is avatar.
     item_location loc = game_menus::inv::titled_filter_menu(
                             filter, *p->as_avatar(), _( "Enhance which clothing?" ) );
     if( !loc ) {
         p->add_msg_if_player( m_info, _( "You do not have that item!" ) );
         return std::nullopt;
     }
     item &mod = *loc;
     if( &mod == &it ) {
         p->add_msg_if_player( m_info,
                               _( "This can be used to repair or modify other items, not itself." ) );
         return std::nullopt;
     }
     // Gives us an item with the mod added or removed (toggled)
     const auto modded_copy = []( const item & proto, const flag_id & mod_type ) {
         item mcopy = proto;
         if( mcopy.has_own_flag( mod_type ) == 0 ) {
             mcopy.set_flag( mod_type );
         } else {
             mcopy.unset_flag( mod_type );
         }
         return mcopy;
     };
     // Cache available materials
     std::map< itype_id, bool > has_enough;
     const int items_needed = mod.base_volume() / 750_ml + 1;
     const inventory &crafting_inv = p->crafting_inventory();
     const std::function<bool( const item & )> is_filthy_filter = is_crafting_component;
     // Go through all discovered repair items and see if we have any of them available
     for( const clothing_mod &cm : clothing_mods::get_all() ) {
         has_enough[cm.item_string] = crafting_inv.has_amount( cm.item_string, items_needed, false,
                                      is_filthy_filter );
     }
     int mod_count = 0;
     for( const clothing_mod &cm : clothing_mods::get_all() ) {
         mod_count += mod.has_own_flag( cm.flag );
     }
     // We need extra thread to lose it on bad rolls
     const int thread_needed = mod.base_volume() / 125_ml + 10;
     const auto valid_mods = mod.find_armor_data()->valid_mods;
     const auto get_compare_color = [&]( const float before, const float after,
     const bool higher_is_better ) {
         return before == after ? c_unset : ( ( after > before ) == higher_is_better ? c_light_green :
                                              c_red );
     };
     uilist tmenu;
     tmenu.text = _( "How do you want to modify it?" );
     int index = 0;
     for( const clothing_mod_id &cm : clothing_mods ) {
         clothing_mod obj = cm.obj();
         item temp_item = modded_copy( mod, obj.flag );
         temp_item.update_clothing_mod_val();
         bool enab = false;
         std::string prompt;
         if( !mod.has_own_flag( obj.flag ) ) {
             // Mod not already present, check if modification is possible
             if( obj.restricted &&
                 std::find( valid_mods.begin(), valid_mods.end(), obj.flag.str() ) == valid_mods.end() ) {
                 //~ %1$s: modification desc, %2$s: mod name
                 prompt = string_format( _( "Can't %1$s (incompatible with %2$s)" ),
                                         lowercase_first_letter( obj.implement_prompt.translated() ),
                                         mod.tname( 1, false ) );
             } else if( !it.ammo_sufficient( p, thread_needed ) ) {
                 //~ %1$s: modification desc, %2$d: number of thread needed
                 prompt = string_format( _( "Can't %1$s (need %2$d thread loaded)" ),
                                         lowercase_first_letter( obj.implement_prompt.translated() ), thread_needed );
             } else if( !has_enough[obj.item_string] ) {
                 //~ %1$s: modification desc, %2$d: number of items needed, %3$s: items needed
                 prompt = string_format( _( "Can't %1$s (need %2$d %3$s)" ),
                                         lowercase_first_letter( obj.implement_prompt.translated() ),
                                         items_needed, item::nname( obj.item_string, items_needed ) );
             } else {
                 // Modification is possible
                 enab = true;
                 //~ %1$s: modification desc, %2$d: number of items needed, %3$s: items needed, %4$s: number of thread needed
                 prompt = string_format( _( "%1$s (%2$d %3$s and %4$d thread)" ),
                                         lowercase_first_letter( obj.implement_prompt.translated() ),
                                         items_needed, item::nname( obj.item_string, items_needed ), thread_needed );
             }
         } else {
             // Mod already present, give option to destroy
             enab = true;
             prompt = obj.destroy_prompt.translated();
         }
         std::string desc;
         // FIXME: Remove sew_advanced_actor, no longer used since before 0.G
         desc += colorize( string_format( "%s: %.2f->%.2f\n", _( "Bash" ), mod.resist( damage_bash ),
                                          temp_item.resist( damage_bash ) ), get_compare_color( mod.resist( damage_bash ),
                                                  temp_item.resist( damage_bash ), true ) );
         desc += colorize( string_format( "%s: %.2f->%.2f\n", _( "Cut" ), mod.resist( damage_cut ),
                                          temp_item.resist( damage_cut ) ), get_compare_color( mod.resist( damage_cut ),
                                                  temp_item.resist( damage_cut ), true ) );
         desc += colorize( string_format( "%s: %.2f->%.2f\n", _( "Ballistic" ),
                                          mod.resist( damage_bullet ),
                                          temp_item.resist( damage_bullet ) ), get_compare_color( mod.resist( damage_bullet ),
                                                  temp_item.resist( damage_bullet ),
                                                  true ) );
         desc += colorize( string_format( "%s: %.2f->%.2f\n", _( "Acid" ), mod.resist( damage_acid ),
                                          temp_item.resist( damage_acid ) ), get_compare_color( mod.resist( damage_acid ),
                                                  temp_item.resist( damage_acid ), true ) );
         desc += colorize( string_format( "%s: %.2f->%.2f\n", _( "Fire" ), mod.resist( damage_heat ),
                                          temp_item.resist( damage_heat ) ), get_compare_color( mod.resist( damage_heat ),
                                                  temp_item.resist( damage_heat ), true ) );
         desc += colorize( string_format( "%s: %d->%d\n", _( "Warmth" ), mod.get_warmth(),
                                          temp_item.get_warmth() ), get_compare_color( mod.get_warmth(), temp_item.get_warmth(), true ) );
         desc += colorize( string_format( "%s: %d->%d\n", _( "Encumbrance" ), mod.get_avg_encumber( *p ),
                                          temp_item.get_avg_encumber( *p ) ), get_compare_color( mod.get_avg_encumber( *p ),
                                                  temp_item.get_avg_encumber( *p ), false ) );
         tmenu.addentry_desc( index++, enab, MENU_AUTOASSIGN, prompt, desc );
     }
     tmenu.textwidth = 80;
     tmenu.desc_enabled = true;
     tmenu.query();
     const int choice = tmenu.ret;
     if( choice < 0 || choice >= static_cast<int>( clothing_mods.size() ) ) {
         return std::nullopt;
     }
     // The mod player picked
     const flag_id &the_mod = clothing_mods[choice].obj().flag;
     // If the picked mod already exists, player wants to destroy it
     if( mod.has_own_flag( the_mod ) ) {
         if( query_yn( _( "Are you sure?  You will not gain any materials back." ) ) ) {
             mod.unset_flag( the_mod );
         }
         mod.update_clothing_mod_val();
         return 0;
     }
     // Get the id of the material used
     const itype_id &repair_item = clothing_mods[choice].obj().item_string;
     std::vector<item_comp> comps;
     comps.emplace_back( repair_item, items_needed );
     p->mod_moves( -to_moves<int>( 30_seconds * p->fine_detail_vision_mod() ) );
     p->practice( used_skill, items_needed * 3 + 3 );
     /** @EFFECT_TAILOR randomly improves clothing modification efforts */
     int rn = dice( 3, 2 + round( p->get_skill_level( used_skill ) ) ); // Skill
     /** @EFFECT_DEX randomly improves clothing modification efforts */
     rn += rng( 0, p->dex_cur / 2 );                    // Dexterity
     /** @EFFECT_PER randomly improves clothing modification efforts */
     rn += rng( 0, p->per_cur / 2 );                    // Perception
     rn -= mod_count * 10;                              // Other mods
     if( rn <= 8 ) {
         const std::string startdurability = mod.durability_indicator( true );
         const bool destroyed = mod.inc_damage();
         const std::string resultdurability = mod.durability_indicator( true );
         p->add_msg_if_player( m_bad, _( "You damage your %s trying to modify it!  ( %s-> %s)" ),
                               mod.tname( 1, false ), startdurability, resultdurability );
         if( destroyed ) {
             p->add_msg_if_player( m_bad, _( "You destroy it!" ) );
             p->i_rem_keep_contents( &mod );
             p->calc_encumbrance();
             p->calc_discomfort();
         }
         return thread_needed / 2;
     } else if( rn <= 10 ) {
         p->add_msg_if_player( m_bad,
                               _( "You fail to modify the clothing, and you waste thread and materials." ) );
         p->consume_items( comps, 1, is_crafting_component );
         return thread_needed;
     } else if( rn <= 14 ) {
         p->add_msg_if_player( m_mixed, _( "You modify your %s, but waste a lot of thread." ),
                               mod.tname() );
         p->consume_items( comps, 1, is_crafting_component );
         mod.set_flag( the_mod );
         mod.update_clothing_mod_val();
         p->calc_encumbrance();
         p->calc_discomfort();
         return thread_needed;
     }
     p->add_msg_if_player( m_good, _( "You modify your %s!" ), mod.tname() );
     mod.set_flag( the_mod );
     mod.update_clothing_mod_val();
     p->consume_items( comps, 1, is_crafting_component );
     p->calc_encumbrance();
     p->calc_discomfort();
     return thread_needed / 2;
 }
References _, add_msg(), Character::add_msg_if_player(), uilist::addentry_desc(), item::ammo_sufficient(), Creature::as_avatar(), c_light_green, c_red, c_unset, Character::calc_discomfort(), Character::calc_encumbrance(), Character::cant_do_mounted(), Creature::cant_do_underwater(), colorize(), Character::consume_items(), Character::crafting_inventory(), damage_acid, damage_bash, damage_bullet, damage_cut, damage_heat, uilist::desc_enabled, clothing_mod::destroy_prompt, Character::dex_cur, dice(), filter, Character::fine_detail_vision_mod(), clothing_mod::flag, flag_INTEGRATED, clothing_mods::get_all(), item::get_avg_encumber(), Character::get_skill_level(), item::get_warmth(), visitable::has_amount(), item::has_own_flag(), Character::i_rem_keep_contents(), clothing_mod::implement_prompt, is_crafting_component(), Character::is_npc(), clothing_mod::item_string, lowercase_first_letter(), m_bad, m_good, m_info, m_mixed, MENU_AUTOASSIGN, Creature::mod_moves(), item::nname(), Character::per_cur, Character::practice(), Pickup::prompt, uilist::query(), query_yn(), item::resist(), clothing_mod::restricted, uilist::ret, rng(), round(), item::set_flag(), string_id< T >::str(), string_format(), uilist::text, uilist::textwidth, game_menus::inv::titled_filter_menu(), translation::translated(), item::unset_flag(), and item::update_clothing_mod_val().
Member Data Documentation
clothing_mods
std::vector<clothing_mod_id> sew_advanced_actor::clothing_mods
Clothing mods.
Definition at line 1156 of file iuse_actor.h.
materials
std::set<material_id> sew_advanced_actor::materials
Materials.
Definition at line 1154 of file iuse_actor.h.
used_skill
skill_id sew_advanced_actor::used_skill
Skill used.
Definition at line 1158 of file iuse_actor.h.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp