Cataclysm DDA: effect_type Class Reference
effect_type Class Reference
#include <effect.h>
Public Types
enum class memorial_gender : int { male , female }
Public Member Functions
effect_type ()=default
game_message_type get_rating (int intensity=1) const
Returns if an effect is good or bad for message display.
bool use_name_ints () const
Returns true if there is a listed name in the JSON entry for each intensity from 1 to max_intensity.
bool use_desc_ints (bool reduced) const
Returns true if there is a listed description in the JSON entry for each intensity from 1 to max_intensity with the matching reduced value.
game_message_type lose_game_message_type (int intensity=1) const
Returns the appropriate game_message_type when an effect is lost.
void add_apply_msg (int intensity) const
std::string get_apply_memorial_log (memorial_gender gender) const
Returns the memorial log added when a new effect is obtained.
std::string get_remove_message () const
Returns the message displayed when an effect is removed.
std::string get_remove_memorial_log (memorial_gender gender) const
Returns the memorial log added when an effect is removed.
std::string get_blood_analysis_description () const
Returns the effect's description displayed when character conducts blood analysis.
bool get_main_parts () const
Returns true if an effect will only target main body parts (i.e., those with HP).
double get_mod_value (const std::string &type, mod_action action, uint8_t reduction_level, int intensity) const
bool is_show_in_info () const
void load_mod_data (const JsonObject &jo)
Loading helper functions.
bool load_miss_msgs (const JsonObject &jo, std::string_view member)
bool load_decay_msgs (const JsonObject &jo, std::string_view member)
bool load_apply_msgs (const JsonObject &jo, std::string_view member)
void verify () const
bool has_flag (const flag_id &flag) const
Check if the effect type has the specified flag.
const time_duration & intensity_duration () const
Static Public Member Functions
static void check_consistency ()
Verifies data is accurate.
static void register_ma_buff_effect (const effect_type &eff)
Registers the effect in the global map.
Public Attributes
efftype_id id
std::vector< enchantment_id > enchantments
cata::flat_set< json_character_flag > immune_flags
cata::flat_set< json_character_flag > immune_bp_flags
Protected Member Functions
uint32_t get_effect_modifier_key (mod_action action, uint8_t reduction_level) const
void extract_effect (const std::array< std::optional< JsonObject >, 2 > &j, const std::string &effect_name, const std::vector< std::pair< std::string, mod_action >> &action_keys)
Protected Attributes
int max_intensity = 0
int max_effective_intensity = 0
time_duration max_duration = 365_days
int dur_add_perc = 0
int int_add_val = 0
int int_decay_step = 0
int int_decay_tick = 0
time_duration int_dur_factor = 0_turns
bool int_decay_remove = false
std::set< flag_id > flags
bool main_parts_only = false
bool show_in_info = false
bool show_intensity = false
std::vector< trait_id > resist_traits
std::vector< efftype_id > resist_effects
std::vector< efftype_id > removes_effects
std::vector< efftype_id > blocks_effects
std::vector< std::pair< translation, int > > miss_msgs
bool pain_sizing = false
bool hurt_sizing = false
bool harmful_cough = false
bool pkill_addict_reduces = false
bool impairs_movement = false
std::vector< translation > name
translation speed_mod_name
std::vector< translation > desc
std::vector< translation > reduced_desc
bool part_descs = false
std::vector< std::pair< translation, game_message_type > > decay_msgs
std::vector< std::pair< translation, game_message_type > > apply_msgs
std::string apply_memorial_log
translation remove_message
std::string remove_memorial_log
translation blood_analysis_description
translation death_msg
std::optional< event_type > death_event
std::unordered_map< std::string, std::unordered_map< uint32_t, modifier_value_arr > > mod_data
std::vector< vitamin_rate_effect > vitamin_data
std::vector< limb_score_effect > limb_score_data
std::vector< effect_dur_mod > effect_dur_scaling
std::vector< std::pair< int, int > > kill_chance
std::vector< std::pair< int, int > > red_kill_chance
Friends
class effect
void load_effect_type (const JsonObject &jo)
Detailed Description
Definition at line 104 of file effect.h.
Member Enumeration Documentation
memorial_gender
enum effect_type::memorial_gender : int strong
Enumerator
male
female
Definition at line 109 of file effect.h.
                                    : int {
             male,
             female,
         };
Constructor & Destructor Documentation
effect_type()
effect_type::effect_type () default
Member Function Documentation
add_apply_msg()
void effect_type::add_apply_msg (int intensity) const
Definition at line 645 of file effect.cpp.
 {
     if( intensity == 0 ) {
         return;
     }
     if( intensity - 1 < static_cast<int>( apply_msgs.size() ) ) {
         add_msg( apply_msgs[intensity - 1].second,
                  apply_msgs[intensity - 1].first.translated() );
     } else if( !apply_msgs.empty() && !apply_msgs[0].first.empty() ) {
         // if the apply message is empty we shouldn't show the message
         add_msg( apply_msgs[0].second,
                  apply_msgs[0].first.translated() );
     }
 }
References add_msg(), apply_msgs, intensity, and second.
Referenced by Creature::add_effect(), and effect::set_intensity().
check_consistency()
void effect_type::check_consistency () static
Verifies data is accurate.
Definition at line 583 of file effect.cpp.
 {
     for( auto const &check : effect_types ) {
         check.second.verify();
     }
 }
References check(), and anonymous_namespace{effect.cpp}::effect_types.
Referenced by DynamicDataLoader::check_consistency().
extract_effect()
void effect_type::extract_effect (const std::array< std::optional< JsonObject >, 2 > & j, const std::string & effect_name, const std::vector< std::pair< std::string, mod_action >> & action_keys) protected
Definition at line 286 of file effect.cpp.
 {
     std::unordered_map<uint32_t, modifier_value_arr> modifiers;
     for( uint32_t cur_mod_type = 0; cur_mod_type < static_cast<size_t>( mod_type::MAX );
          cur_mod_type++ ) {
         if( !j[cur_mod_type].has_value() ) {
             continue;
         }
         const JsonObject &base = *j[cur_mod_type];
         for( const auto &action_key : action_keys ) {
             if( !base.has_array( action_key.first ) ) {
                 continue;
             }
             JsonArray jsarr = base.get_array( action_key.first );
             if( jsarr.empty() ) {
                 continue;
             }
             mod_action action = action_key.second;
             cata_assert( jsarr.size() < 0x100 );
             for( size_t i = 0; i < jsarr.size(); i++ ) {
                 uint32_t key = get_effect_modifier_key( action, i );
                 // Create default entry if doesn't exist
                 const auto &it = modifiers.emplace( key, default_modifier_values );
                 // Update entry with the fetched value
                 it.first->second[cur_mod_type] = jsarr.get_float( i );
             }
         }
     }
     if( modifiers.empty() ) {
         return;
     }
     mod_data[effect_name] = std::move( modifiers );
 }
References action, cata_assert, default_modifier_values, JsonArray::empty(), JsonObject::get_array(), get_effect_modifier_key(), JsonArray::get_float(), JsonObject::has_array(), MAX, mod_data, and JsonArray::size().
Referenced by load_mod_data().
get_apply_memorial_log()
std::string effect_type::get_apply_memorial_log (memorial_gender gender) const
Returns the memorial log added when a new effect is obtained.
Definition at line 659 of file effect.cpp.
 {
     switch( gender ) {
         case memorial_gender::male:
             return pgettext( "memorial_male", apply_memorial_log.c_str() );
         case memorial_gender::female:
             return pgettext( "memorial_female", apply_memorial_log.c_str() );
     }
     return std::string();
 }
References apply_memorial_log, female, male, and pgettext.
get_blood_analysis_description()
std::string effect_type::get_blood_analysis_description () const
Returns the effect's description displayed when character conducts blood analysis.
Definition at line 683 of file effect.cpp.
 {
     return blood_analysis_description.translated();
 }
References blood_analysis_description, and translation::translated().
get_effect_modifier_key()
uint32_t effect_type::get_effect_modifier_key (mod_action action, uint8_t reduction_level) const inline protected
Definition at line 175 of file effect.h.
{
             return static_cast<uint8_t>( action ) << 0 |
                    reduction_level << 8;
         }
References action.
Referenced by extract_effect(), and get_mod_value().
get_main_parts()
bool effect_type::get_main_parts () const
Returns true if an effect will only target main body parts (i.e., those with HP).
Definition at line 687 of file effect.cpp.
 {
     return main_parts_only;
 }
References main_parts_only.
get_mod_value()
double effect_type::get_mod_value (const std::string & type, mod_action action, uint8_t reduction_level, int intensity) const
Definition at line 562 of file effect.cpp.
 {
     const auto &it = mod_data.find( type );
     if( it == mod_data.cend() ) {
         return 0;
     }
     const auto &action_map = it->second;
     const auto &modifier = action_map.find( get_effect_modifier_key( action, reduction_level ) );
     if( modifier == action_map.end() ) {
         return 0;
     }
     double ret = 0;
     const auto &data_entry = modifier->second;
     ret += data_entry[static_cast<size_t>( mod_type::BASE_MOD )];
     ret += data_entry[static_cast<size_t>( mod_type::SCALING_MOD )] * ( intensity - 1 );
     return ret;
 }
References action, BASE_MOD, get_effect_modifier_key(), intensity, mod_data, cata::hash64_detail::ret, SCALING_MOD, and type.
Referenced by effect::activated(), effect::get_amount(), effect::get_avg_mod(), effect::get_max_val(), effect::get_min_val(), effect::get_mod(), and effect::get_percentage().
get_rating()
game_message_type effect_type::get_rating (int intensity = 1) const
Returns if an effect is good or bad for message display.
Definition at line 609 of file effect.cpp.
 {
     intensity = std::clamp( intensity, 0, static_cast<int>( apply_msgs.size() ) - 1 );
     return apply_msgs[intensity].second;
 }
References apply_msgs, clamp(), and intensity.
Referenced by lose_game_message_type(), and bodygraph_display::prepare_infotext().
get_remove_memorial_log()
std::string effect_type::get_remove_memorial_log (memorial_gender gender) const
Returns the memorial log added when an effect is removed.
Definition at line 673 of file effect.cpp.
 {
     switch( gender ) {
         case memorial_gender::male:
             return pgettext( "memorial_male", remove_memorial_log.c_str() );
         case memorial_gender::female:
             return pgettext( "memorial_female", remove_memorial_log.c_str() );
     }
     return std::string();
 }
References female, male, pgettext, and remove_memorial_log.
get_remove_message()
std::string effect_type::get_remove_message () const
Returns the message displayed when an effect is removed.
Definition at line 669 of file effect.cpp.
 {
     return remove_message.translated();
 }
References remove_message, and translation::translated().
has_flag()
bool effect_type::has_flag (const flag_id & flag) const
Check if the effect type has the specified flag.
Definition at line 604 of file effect.cpp.
 {
     return flags.count( flag );
 }
References flags.
Referenced by effect::has_flag().
intensity_duration()
const time_duration& effect_type::intensity_duration () const inline
Definition at line 168 of file effect.h.
{
             return int_dur_factor;
         }
References int_dur_factor.
Referenced by debug_menu::wisheffect().
is_show_in_info()
bool effect_type::is_show_in_info () const
Definition at line 691 of file effect.cpp.
 {
     return show_in_info;
 }
References show_in_info.
Referenced by bodygraph_display::prepare_infotext().
load_apply_msgs()
bool effect_type::load_apply_msgs (const JsonObject & jo, std::string_view member)
Definition at line 744 of file effect.cpp.
 {
     if( jo.has_array( member ) ) {
         JsonArray ja = jo.get_array( member );
         for( JsonArray inner : jo.get_array( member ) ) {
             load_msg_help( inner, apply_msgs );
         }
         return true;
     } else {
         translation msg;
         optional( jo, false, member, msg );
         if( jo.has_string( "rating" ) ) {
             std::optional<game_message_type> rate = process_rating( jo.get_string( "rating" ) );
             apply_msgs.emplace_back( msg, rate.value() );
         } else {
             apply_msgs.emplace_back( msg, game_message_type::m_neutral );
         }
     }
     return false;
 }
References apply_msgs, JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), load_msg_help(), m_neutral, member, optional(), and process_rating().
load_decay_msgs()
bool effect_type::load_decay_msgs (const JsonObject & jo, std::string_view member)
Definition at line 733 of file effect.cpp.
 {
     if( jo.has_array( member ) ) {
         for( JsonArray inner : jo.get_array( member ) ) {
             load_msg_help( inner, decay_msgs );
         }
         return true;
     }
     return false;
 }
References decay_msgs, JsonObject::get_array(), JsonObject::has_array(), load_msg_help(), and member.
load_miss_msgs()
bool effect_type::load_miss_msgs (const JsonObject & jo, std::string_view member)
Definition at line 695 of file effect.cpp.
 {
     return jo.read( member, miss_msgs );
 }
References member, miss_msgs, and JsonObject::read().
load_mod_data()
void effect_type::load_mod_data (const JsonObject & jo)
Loading helper functions.
Definition at line 332 of file effect.cpp.
 {
     // Fetch the JSON objects at the start so we can do unvisited member checking
     std::array<std::optional<JsonObject>, 2> to_extract;
     to_extract[0] = j.has_object( MOD_TYPE_STRINGS[0] ) ?
                     std::optional<JsonObject>( j.get_object( MOD_TYPE_STRINGS[0] ) ) :
                     std::nullopt;
     to_extract[1] = j.has_object( MOD_TYPE_STRINGS[1] ) ?
                     std::optional<JsonObject>( j.get_object( MOD_TYPE_STRINGS[1] ) ) :
                     std::nullopt;
     // Stats first
     extract_effect( to_extract, "STR",   { {"str_mod",   mod_action::MIN} } );
     extract_effect( to_extract, "DEX",   { {"dex_mod",   mod_action::MIN} } );
     extract_effect( to_extract, "PER",   { {"per_mod",   mod_action::MIN} } );
     extract_effect( to_extract, "INT",   { {"int_mod",   mod_action::MIN} } );
     extract_effect( to_extract, "SPEED", { {"speed_mod", mod_action::MIN} } );
     // Then pain
     extract_effect( to_extract, "PAIN", {
         { "pain_amount",     mod_action::AMOUNT},
         { "pain_min",        mod_action::MIN},
         { "pain_max",        mod_action::MAX},
         { "pain_max_val",    mod_action::MAX_VAL},
         { "pain_chance",     mod_action::CHANCE_TOP},
         { "pain_chance_bot", mod_action::CHANCE_BOT},
         { "pain_tick",       mod_action::TICK},
     } );
     // Then hurt
     extract_effect( to_extract, "HURT", {
         {"hurt_amount",      mod_action::AMOUNT},
         {"hurt_min",         mod_action::MIN},
         {"hurt_max",         mod_action::MAX},
         {"hurt_chance",      mod_action::CHANCE_TOP},
         {"hurt_chance_bot",  mod_action::CHANCE_BOT},
         {"hurt_tick",        mod_action::TICK},
     } );
     // Then sleep
     extract_effect( to_extract, "SLEEP", {
         {"sleep_amount",      mod_action::AMOUNT},
         {"sleep_min",         mod_action::MIN},
         {"sleep_max",         mod_action::MAX},
         {"sleep_chance",      mod_action::CHANCE_TOP},
         {"sleep_chance_bot",  mod_action::CHANCE_BOT},
         {"sleep_tick",        mod_action::TICK},
     } );
     // Then pkill
     extract_effect( to_extract, "PKILL", {
         {"pkill_amount",      mod_action::AMOUNT},
         {"pkill_min",         mod_action::MIN},
         {"pkill_max",         mod_action::MAX},
         {"pkill_max_val",     mod_action::MAX_VAL},
         {"pkill_chance",      mod_action::CHANCE_TOP},
         {"pkill_chance_bot",  mod_action::CHANCE_BOT},
         {"pkill_tick",        mod_action::TICK},
     } );
     // Then stim
     extract_effect( to_extract, "STIM", {
         {"stim_amount",      mod_action::AMOUNT},
         {"stim_min",         mod_action::MIN},
         {"stim_max",         mod_action::MAX},
         {"stim_min_val",     mod_action::MIN_VAL},
         {"stim_max_val",     mod_action::MAX_VAL},
         {"stim_chance",      mod_action::CHANCE_TOP},
         {"stim_chance_bot",  mod_action::CHANCE_BOT},
         {"stim_tick",        mod_action::TICK},
     } );
     // Then health
     extract_effect( to_extract, "HEALTH", {
         {"health_amount",      mod_action::AMOUNT},
         {"health_min",         mod_action::MIN},
         {"health_max",         mod_action::MAX},
         {"health_min_val",     mod_action::MIN_VAL},
         {"health_max_val",     mod_action::MAX_VAL},
         {"health_chance",      mod_action::CHANCE_TOP},
         {"health_chance_bot",  mod_action::CHANCE_BOT},
         {"health_tick",        mod_action::TICK},
     } );
     // Then health mod
     extract_effect( to_extract, "H_MOD", {
         {"h_mod_amount",      mod_action::AMOUNT},
         {"h_mod_min",         mod_action::MIN},
         {"h_mod_max",         mod_action::MAX},
         {"h_mod_min_val",     mod_action::MIN_VAL},
         {"h_mod_max_val",     mod_action::MAX_VAL},
         {"h_mod_chance",      mod_action::CHANCE_TOP},
         {"h_mod_chance_bot",  mod_action::CHANCE_BOT},
         {"h_mod_tick",        mod_action::TICK},
     } );
     // Then radiation
     extract_effect( to_extract, "RAD", {
         {"rad_amount",      mod_action::AMOUNT},
         {"rad_min",         mod_action::MIN},
         {"rad_max",         mod_action::MAX},
         {"rad_max_val",     mod_action::MAX_VAL},
         {"rad_chance",      mod_action::CHANCE_TOP},
         {"rad_chance_bot",  mod_action::CHANCE_BOT},
         {"rad_tick",        mod_action::TICK},
     } );
     // Then hunger
     extract_effect( to_extract, "HUNGER", {
         {"hunger_amount",      mod_action::AMOUNT},
         {"hunger_min",         mod_action::MIN},
         {"hunger_max",         mod_action::MAX},
         {"hunger_min_val",     mod_action::MIN_VAL},
         {"hunger_max_val",     mod_action::MAX_VAL},
         {"hunger_chance",      mod_action::CHANCE_TOP},
         {"hunger_chance_bot",  mod_action::CHANCE_BOT},
         {"hunger_tick",        mod_action::TICK},
     } );
     // Then thirst
     extract_effect( to_extract, "THIRST", {
         {"thirst_amount",      mod_action::AMOUNT},
         {"thirst_min",         mod_action::MIN},
         {"thirst_max",         mod_action::MAX},
         {"thirst_min_val",     mod_action::MIN_VAL},
         {"thirst_max_val",     mod_action::MAX_VAL},
         {"thirst_chance",      mod_action::CHANCE_TOP},
         {"thirst_chance_bot",  mod_action::CHANCE_BOT},
         {"thirst_tick",        mod_action::TICK},
     } );
     // Then thirst
     extract_effect( to_extract, "PERSPIRATION", {
         {"perspiration_amount",      mod_action::AMOUNT},
         {"perspiration_min",         mod_action::MIN},
         {"perspiration_max",         mod_action::MAX},
         {"perspiration_min_val",     mod_action::MIN_VAL},
         {"perspiration_max_val",     mod_action::MAX_VAL},
         {"perspiration_chance",      mod_action::CHANCE_TOP},
         {"perspiration_chance_bot",  mod_action::CHANCE_BOT},
         {"perspiration_tick",        mod_action::TICK},
     } );
     // Then sleepiness
     extract_effect( to_extract, "SLEEPINESS", {
         {"sleepiness_amount",      mod_action::AMOUNT},
         {"sleepiness_min",         mod_action::MIN},
         {"sleepiness_max",         mod_action::MAX},
         {"sleepiness_min_val",     mod_action::MIN_VAL},
         {"sleepiness_max_val",     mod_action::MAX_VAL},
         {"sleepiness_chance",      mod_action::CHANCE_TOP},
         {"sleepiness_chance_bot",  mod_action::CHANCE_BOT},
         {"sleepiness_tick",        mod_action::TICK},
     } );
     // Then stamina
     extract_effect( to_extract, "STAMINA", {
         {"stamina_amount",      mod_action::AMOUNT},
         {"stamina_min",         mod_action::MIN},
         {"stamina_max",         mod_action::MAX},
         {"stamina_max_val",     mod_action::MAX_VAL},
         {"stamina_chance",      mod_action::CHANCE_TOP},
         {"stamina_chance_bot",  mod_action::CHANCE_BOT},
         {"stamina_tick",        mod_action::TICK},
     } );
     // Then blood pressure. No min/max val, as they are handled internally.
     extract_effect( to_extract, "BLOOD_PRESSURE", {
         {"blood_pressure_amount",      mod_action::AMOUNT},
         {"blood_pressure_min",         mod_action::MIN},
         {"blood_pressure_max",         mod_action::MAX},
         {"blood_pressure_max_val",     mod_action::MAX_VAL},
         {"blood_pressure_min_val",     mod_action::MIN_VAL},
         {"blood_pressure_chance",      mod_action::CHANCE_TOP},
         {"blood_pressure_chance_bot",  mod_action::CHANCE_BOT},
         {"blood_pressure_tick",        mod_action::TICK},
     } );
     // Then Heart Rate
     extract_effect( to_extract, "HEART_RATE", {
         {"heart_rate_amount",      mod_action::AMOUNT},
         {"heart_rate_min",         mod_action::MIN},
         {"heart_rate_max",         mod_action::MAX},
         {"heart_rate_max_val",     mod_action::MAX_VAL},
         {"heart_rate_min_val",     mod_action::MIN_VAL},
         {"heart_rate_chance",      mod_action::CHANCE_TOP},
         {"heart_rate_chance_bot",  mod_action::CHANCE_BOT},
         {"heart_rate_tick",        mod_action::TICK},
     } );
     // Then Respirato Rate
     extract_effect( to_extract, "RESPIRATORY_RATE", {
         {"respiratory_rate_amount",      mod_action::AMOUNT},
         {"respiratory_rate_min",         mod_action::MIN},
         {"respiratory_rate_max",         mod_action::MAX},
         {"respiratory_rate_max_val",     mod_action::MAX_VAL},
         {"respiratory_rate_min_val",     mod_action::MIN_VAL},
         {"respiratory_rate_chance",      mod_action::CHANCE_TOP},
         {"respiratory_rate_chance_bot",  mod_action::CHANCE_BOT},
         {"respiratory_rate_tick",        mod_action::TICK},
     } );
     // Then coughing
     extract_effect( to_extract, "COUGH", {
         {"cough_chance",      mod_action::CHANCE_TOP},
         {"cough_chance_bot",  mod_action::CHANCE_BOT},
         {"cough_tick",        mod_action::TICK},
     } );
     // Then vomiting
     extract_effect( to_extract, "VOMIT", {
         {"vomit_chance",      mod_action::CHANCE_TOP},
         {"vomit_chance_bot",  mod_action::CHANCE_BOT},
         {"vomit_tick",        mod_action::TICK},
     } );
     // Then healing effects
     extract_effect( to_extract, "HEAL_RATE",  { {"healing_rate",  mod_action::AMOUNT} } );
     extract_effect( to_extract, "HEAL_HEAD",  { {"healing_head",  mod_action::AMOUNT} } );
     extract_effect( to_extract, "HEAL_TORSO", { {"healing_torso", mod_action::AMOUNT} } );
     // creature stats mod
     extract_effect( to_extract, "DODGE", { {"dodge_mod", mod_action::MIN} } );
     extract_effect( to_extract, "HIT",   { {"hit_mod",   mod_action::MIN} } );
     extract_effect( to_extract, "BASH",  { {"bash_mod",  mod_action::MIN} } );
     extract_effect( to_extract, "CUT",   { {"cut_mod",   mod_action::MIN} } );
     extract_effect( to_extract, "SIZE",  { {"size_mod",  mod_action::MIN} } );
 }
References AMOUNT, CHANCE_BOT, CHANCE_TOP, extract_effect(), JsonObject::get_object(), JsonObject::has_object(), MAX, MAX_VAL, MIN, MIN_VAL, MOD_TYPE_STRINGS, and TICK.
lose_game_message_type()
game_message_type effect_type::lose_game_message_type (int intensity = 1) const
Returns the appropriate game_message_type when an effect is lost.
This is opposite to an effect's "rating" value.
Definition at line 629 of file effect.cpp.
 {
     switch( get_rating( intensity ) ) {
         case m_good:
             return m_bad;
         case m_bad:
             return m_good;
         case m_neutral:
             return m_neutral;
         case m_mixed:
             return m_mixed;
         default:
             // Should never happen
             return m_neutral;
     }
 }
References get_rating(), intensity, m_bad, m_good, m_mixed, and m_neutral.
register_ma_buff_effect()
void effect_type::register_ma_buff_effect (const effect_type & eff) static
Registers the effect in the global map.
Definition at line 1666 of file effect.cpp.
 {
     if( eff.id.is_valid() ) {
         debugmsg( "effect id %s of a martial art buff is already used as id for an effect",
                   eff.id.c_str() );
         return;
     }
     effect_types.insert( std::make_pair( eff.id, eff ) );
 }
References string_id< T >::c_str(), debugmsg, anonymous_namespace{effect.cpp}::effect_types, id, and string_id< T >::is_valid().
Referenced by finalize_martial_arts().
use_desc_ints()
bool effect_type::use_desc_ints (bool reduced) const
Returns true if there is a listed description in the JSON entry for each intensity from 1 to max_intensity with the matching reduced value.
Definition at line 620 of file effect.cpp.
 {
     if( reduced ) {
         return static_cast<size_t>( max_intensity ) <= reduced_desc.size();
     } else {
         return static_cast<size_t>( max_intensity ) <= desc.size();
     }
 }
References desc, max_intensity, and reduced_desc.
Referenced by effect::disp_desc(), and effect::disp_short_desc().
use_name_ints()
bool effect_type::use_name_ints () const
Returns true if there is a listed name in the JSON entry for each intensity from 1 to max_intensity.
Definition at line 615 of file effect.cpp.
 {
     return name.size() > 1;
 }
References name.
Referenced by effect::disp_name(), and effect::get_speed_name().
verify()
void effect_type::verify () const
Definition at line 590 of file effect.cpp.
 {
     if( death_event.has_value() ) {
         const std::unordered_map<std::string, cata_variant_type> &fields = cata::event::get_fields(
                     *death_event );
         // Only allow events inheriting from event_spec_character at the moment.
         if( fields.size() != 1 || fields.count( "character" ) != 1 ) {
             debugmsg( "Invalid death event type %s in effect_type %s", "lol",
                       io::enum_to_string( *death_event ),
                       id.str() );
         }
     }
 }
References death_event, debugmsg, io::enum_to_string(), and cata::event::get_fields().
Friends And Related Function Documentation
effect
friend class effect friend
Definition at line 107 of file effect.h.
load_effect_type
void load_effect_type (const JsonObject & jo) friend
Definition at line 1506 of file effect.cpp.
 {
     effect_type new_etype;
     new_etype.id = efftype_id( jo.get_string( "id" ) );
     if( jo.has_member( "name" ) ) {
         for( const JsonValue entry : jo.get_array( "name" ) ) {
             translation name;
             if( !entry.read( name ) ) {
                 entry.throw_error( "Error reading effect names" );
             }
             new_etype.name.emplace_back( name );
         }
     } else {
         new_etype.name.emplace_back();
     }
     jo.read( "speed_name", new_etype.speed_mod_name );
     if( jo.has_member( "desc" ) ) {
         jo.read( "desc", new_etype.desc );
     } else {
         new_etype.desc.emplace_back();
     }
     if( jo.has_member( "reduced_desc" ) ) {
         jo.read( "reduced_desc", new_etype.reduced_desc );
     } else {
         new_etype.reduced_desc = new_etype.desc;
     }
     new_etype.part_descs = jo.get_bool( "part_descs", false );
     jo.read( "remove_message", new_etype.remove_message );
     optional( jo, false, "apply_memorial_log", new_etype.apply_memorial_log,
               text_style_check_reader() );
     optional( jo, false, "remove_memorial_log", new_etype.remove_memorial_log,
               text_style_check_reader() );
     jo.read( "blood_analysis_description", new_etype.blood_analysis_description );
     for( auto &&f : jo.get_string_array( "resist_traits" ) ) { // *NOPAD*
         new_etype.resist_traits.emplace_back( f );
     }
     for( auto &&f : jo.get_string_array( "resist_effects" ) ) { // *NOPAD*
         new_etype.resist_effects.emplace_back( f );
     }
     optional( jo, false, "immune_flags", new_etype.immune_flags );
     optional( jo, false, "immune_bp_flags", new_etype.immune_bp_flags );
     for( auto &&f : jo.get_string_array( "removes_effects" ) ) { // *NOPAD*
         new_etype.removes_effects.emplace_back( f );
     }
     for( auto &&f : jo.get_string_array( "blocks_effects" ) ) { // *NOPAD*
         new_etype.blocks_effects.emplace_back( f );
     }
     optional( jo, false, "max_duration", new_etype.max_duration, 365_days );
     if( jo.has_string( "int_dur_factor" ) ) {
         new_etype.int_dur_factor = read_from_json_string<time_duration>( jo.get_member( "int_dur_factor" ),
                                    time_duration::units );
     } else {
         new_etype.int_dur_factor = time_duration::from_turns( jo.get_int( "int_dur_factor", 0 ) );
     }
     optional( jo, false, "vitamins", new_etype.vitamin_data );
     optional( jo, false, "limb_score_mods", new_etype.limb_score_data );
     optional( jo, false, "effect_dur_scaling", new_etype.effect_dur_scaling );
     optional( jo, false, "chance_kill", new_etype.kill_chance );
     optional( jo, false, "chance_kill_resist", new_etype.red_kill_chance );
     optional( jo, false, "death_msg", new_etype.death_msg, to_translation( "You died." ) );
     optional( jo, false, "death_event", new_etype.death_event,
               enum_flags_reader<event_type>( "event_type" ), std::nullopt );
     new_etype.max_intensity = jo.get_int( "max_intensity", 1 );
     new_etype.dur_add_perc = jo.get_int( "dur_add_perc", 100 );
     new_etype.int_add_val = jo.get_int( "int_add_val", 0 );
     new_etype.int_decay_step = jo.get_int( "int_decay_step", -1 );
     new_etype.int_decay_tick = jo.get_int( "int_decay_tick", 0 );
     optional( jo, false, "int_decay_remove", new_etype.int_decay_remove, false );
     new_etype.load_miss_msgs( jo, "miss_messages" );
     new_etype.load_decay_msgs( jo, "decay_messages" );
     new_etype.load_apply_msgs( jo, "apply_message" );
     new_etype.main_parts_only = jo.get_bool( "main_parts_only", false );
     new_etype.show_in_info = jo.get_bool( "show_in_info", false );
     new_etype.show_intensity = jo.get_bool( "show_intensity", true );
     new_etype.pkill_addict_reduces = jo.get_bool( "pkill_addict_reduces", false );
     new_etype.pain_sizing = jo.get_bool( "pain_sizing", false );
     new_etype.hurt_sizing = jo.get_bool( "hurt_sizing", false );
     new_etype.harmful_cough = jo.get_bool( "harmful_cough", false );
     new_etype.max_effective_intensity = jo.get_int( "max_effective_intensity", 0 );
     new_etype.load_mod_data( jo );
     new_etype.impairs_movement = hardcoded_movement_impairing.count( new_etype.id ) > 0;
     new_etype.flags = jo.get_tags<flag_id>( "flags" );
     int enchant_num = 0;
     for( JsonValue jv : jo.get_array( "enchantments" ) ) {
         std::string enchant_name = "INLINE_ENCH_" + new_etype.id.str() + "_" + std::to_string(
                                        enchant_num++ );
         new_etype.enchantments.push_back( enchantment::load_inline_enchantment( jv, "", enchant_name ) );
     }
     effect_types[new_etype.id] = new_etype;
 }
Member Data Documentation
apply_memorial_log
std::string effect_type::apply_memorial_log protected
Definition at line 234 of file effect.h.
Referenced by get_apply_memorial_log().
apply_msgs
std::vector<std::pair<translation, game_message_type> > effect_type::apply_msgs protected
Definition at line 232 of file effect.h.
Referenced by add_apply_msg(), get_rating(), load_apply_msgs(), and ma_buff_effect_type::ma_buff_effect_type().
blocks_effects
std::vector<efftype_id> effect_type::blocks_effects protected
Definition at line 210 of file effect.h.
Referenced by effect::get_blocks_effects().
blood_analysis_description
translation effect_type::blood_analysis_description protected
Definition at line 238 of file effect.h.
Referenced by get_blood_analysis_description().
death_event
std::optional<event_type> effect_type::death_event protected
Definition at line 241 of file effect.h.
Referenced by effect::death_event(), and verify().
death_msg
translation effect_type::death_msg protected
Definition at line 240 of file effect.h.
Referenced by effect::get_death_message().
decay_msgs
std::vector<std::pair<translation, game_message_type> > effect_type::decay_msgs protected
Definition at line 230 of file effect.h.
Referenced by load_decay_msgs(), and effect::set_intensity().
desc
std::vector<translation> effect_type::desc protected
Definition at line 226 of file effect.h.
Referenced by effect::disp_desc(), effect::disp_short_desc(), ma_buff_effect_type::ma_buff_effect_type(), and use_desc_ints().
dur_add_perc
int effect_type::dur_add_perc = 0 protected
Definition at line 189 of file effect.h.
Referenced by effect::get_dur_add_perc(), and ma_buff_effect_type::ma_buff_effect_type().
effect_dur_scaling
std::vector<effect_dur_mod> effect_type::effect_dur_scaling protected
Definition at line 246 of file effect.h.
Referenced by effect::get_effect_dur_scaling().
enchantments
std::vector<enchantment_id> effect_type::enchantments
Definition at line 171 of file effect.h.
flags
std::set<flag_id> effect_type::flags protected
Definition at line 197 of file effect.h.
Referenced by has_flag().
harmful_cough
bool effect_type::harmful_cough = false protected
Definition at line 216 of file effect.h.
Referenced by effect::get_harmful_cough().
hurt_sizing
bool effect_type::hurt_sizing = false protected
Definition at line 215 of file effect.h.
Referenced by effect::get_sizing().
id
efftype_id effect_type::id
Definition at line 116 of file effect.h.
Referenced by effect::death_event(), effect::decay(), monster::die(), effect::disp_desc(), effect::disp_name(), ma_buff::from_effect(), effect::get_id(), register_ma_buff_effect(), and effect::serialize().
immune_bp_flags
cata::flat_set<json_character_flag> effect_type::immune_bp_flags
Definition at line 173 of file effect.h.
Referenced by Creature::add_effect().
immune_flags
cata::flat_set<json_character_flag> effect_type::immune_flags
Definition at line 172 of file effect.h.
Referenced by Character::is_immune_effect().
impairs_movement
bool effect_type::impairs_movement = false protected
Definition at line 222 of file effect.h.
Referenced by effect::impairs_movement().
int_add_val
int effect_type::int_add_val = 0 protected
Definition at line 190 of file effect.h.
Referenced by effect::get_int_add_val(), and ma_buff_effect_type::ma_buff_effect_type().
int_decay_remove
bool effect_type::int_decay_remove = false protected
Definition at line 195 of file effect.h.
Referenced by effect::get_int_decay_remove(), ma_buff_effect_type::ma_buff_effect_type(), and effect::set_intensity().
int_decay_step
int effect_type::int_decay_step = 0 protected
Definition at line 192 of file effect.h.
Referenced by effect::decay(), effect::get_int_decay_step(), and ma_buff_effect_type::ma_buff_effect_type().
int_decay_tick
int effect_type::int_decay_tick = 0 protected
Definition at line 193 of file effect.h.
Referenced by effect::decay(), effect::get_int_decay_tick(), and ma_buff_effect_type::ma_buff_effect_type().
int_dur_factor
time_duration effect_type::int_dur_factor = 0_turns protected
Definition at line 194 of file effect.h.
Referenced by effect::get_int_dur_factor(), intensity_duration(), ma_buff_effect_type::ma_buff_effect_type(), and effect::set_duration().
kill_chance
std::vector<std::pair<int, int> > effect_type::kill_chance protected
Definition at line 247 of file effect.h.
Referenced by effect::kill_roll().
limb_score_data
std::vector<limb_score_effect> effect_type::limb_score_data protected
Definition at line 245 of file effect.h.
Referenced by effect::get_limb_score_data(), and effect::get_limb_score_mod().
main_parts_only
bool effect_type::main_parts_only = false protected
Definition at line 199 of file effect.h.
Referenced by get_main_parts().
max_duration
time_duration effect_type::max_duration = 365_days protected
Definition at line 187 of file effect.h.
Referenced by effect::get_max_duration(), ma_buff_effect_type::ma_buff_effect_type(), and effect::set_duration().
max_effective_intensity
int effect_type::max_effective_intensity = 0 protected
Definition at line 186 of file effect.h.
Referenced by effect::get_effective_intensity(), and effect::get_max_effective_intensity().
max_intensity
int effect_type::max_intensity = 0 protected
Definition at line 185 of file effect.h.
Referenced by effect::get_max_intensity(), ma_buff_effect_type::ma_buff_effect_type(), effect::set_intensity(), and use_desc_ints().
miss_msgs
std::vector<std::pair<translation, int> > effect_type::miss_msgs protected
Definition at line 212 of file effect.h.
Referenced by effect::get_miss_msgs(), and load_miss_msgs().
mod_data
std::unordered_map<std::string, std::unordered_map<uint32_t, modifier_value_arr> > effect_type::mod_data protected
Definition at line 243 of file effect.h.
Referenced by extract_effect(), and get_mod_value().
name
std::vector<translation> effect_type::name protected
Definition at line 224 of file effect.h.
Referenced by effect::disp_name(), effect::get_speed_name(), ma_buff_effect_type::ma_buff_effect_type(), and use_name_ints().
pain_sizing
bool effect_type::pain_sizing = false protected
Definition at line 214 of file effect.h.
Referenced by effect::get_sizing().
part_descs
bool effect_type::part_descs = false protected
Definition at line 228 of file effect.h.
Referenced by effect::use_part_descs().
pkill_addict_reduces
bool effect_type::pkill_addict_reduces = false protected
Definition at line 219 of file effect.h.
Referenced by effect::get_addict_mod().
red_kill_chance
std::vector<std::pair<int, int> > effect_type::red_kill_chance protected
Definition at line 248 of file effect.h.
Referenced by effect::kill_roll().
reduced_desc
std::vector<translation> effect_type::reduced_desc protected
Definition at line 227 of file effect.h.
Referenced by effect::disp_desc(), effect::disp_short_desc(), and use_desc_ints().
remove_memorial_log
std::string effect_type::remove_memorial_log protected
Definition at line 236 of file effect.h.
Referenced by get_remove_memorial_log().
remove_message
translation effect_type::remove_message protected
Definition at line 235 of file effect.h.
Referenced by get_remove_message().
removes_effects
std::vector<efftype_id> effect_type::removes_effects protected
Definition at line 209 of file effect.h.
Referenced by effect::get_blocks_effects(), and effect::get_removes_effects().
resist_effects
std::vector<efftype_id> effect_type::resist_effects protected
Definition at line 208 of file effect.h.
Referenced by effect::get_resist_effects().
resist_traits
std::vector<trait_id> effect_type::resist_traits protected
Definition at line 207 of file effect.h.
Referenced by effect::get_resist_traits().
show_in_info
bool effect_type::show_in_info = false protected
Definition at line 202 of file effect.h.
Referenced by is_show_in_info().
show_intensity
bool effect_type::show_intensity = false protected
Definition at line 205 of file effect.h.
Referenced by effect::disp_name(), and ma_buff_effect_type::ma_buff_effect_type().
speed_mod_name
translation effect_type::speed_mod_name protected
Definition at line 225 of file effect.h.
Referenced by effect::get_speed_name().
vitamin_data
std::vector<vitamin_rate_effect> effect_type::vitamin_data protected
Definition at line 244 of file effect.h.
Referenced by effect::vit_effects().
The documentation for this class was generated from the following files:
src/effect.h
src/effect.cpp