Cataclysm DDA: auto_notes::auto_note_manager_gui Class Reference
auto_notes::auto_note_manager_gui Class Reference
Class implementing the user interface for the auto note configuration.
#include <auto_note.h>
Public Member Functions
auto_note_manager_gui ()
void show ()
bool was_changed (bool bCharacter) const
void set_cached_custom_symbol (const map_extra_id &mapExtId, const custom_symbol &symbol, bool bCharacter)
Private Member Functions
void fill_custom_symbols_cache ()
Private Attributes
std::unordered_map< map_extra_id, std::pair< const map_extra, bool > > char_mapExtraCache
The map extra type cache.
std::unordered_map< map_extra_id, std::pair< const map_extra, bool > > global_mapExtraCache
std::vector< map_extra_id > char_displayCache
All map extra types for the character that will be displayed in the GUI.
std::vector< map_extra_id > global_displayCache
All map extra types for global types that will be displayed in the GUI.
std::unordered_map< map_extra_id, custom_symbol > char_custom_symbol_cache
std::unordered_map< map_extra_id, custom_symbol > global_custom_symbol_cache
bool charwasChanged {false}
bool globalwasChanged {false}
Detailed Description
Class implementing the user interface for the auto note configuration.
Definition at line 66 of file auto_note.h.
Constructor & Destructor Documentation
auto_note_manager_gui()
auto_notes::auto_note_manager_gui::auto_note_manager_gui ()
Definition at line 241 of file auto_note.cpp.
 {
     const auto_note_settings &settings = get_auto_notes_settings();
     for( const map_extra &extra : MapExtras::mapExtraFactory().get_all() ) {
         // Ignore all extras that have autonote disabled in the JSON.
         // This filters out lots of extras users shouldn't see (like "normal")
         if( !extra.autonote ) {
             continue;
         }
         char_mapExtraCache.emplace( extra.id, std::make_pair( extra,
                                     settings.has_auto_note_enabled( extra.id, true ) ) );
         global_mapExtraCache.emplace( extra.id, std::make_pair( extra,
                                       settings.has_auto_note_enabled( extra.id, false ) ) );
         if( settings.was_discovered( extra.id ) ) {
             char_displayCache.push_back( extra.id );
             global_displayCache.push_back( extra.id );
         }
     }
     fill_custom_symbols_cache();
 }
References char_displayCache, char_mapExtraCache, fill_custom_symbols_cache(), ammo_effects::get_all(), get_auto_notes_settings(), global_displayCache, global_mapExtraCache, auto_notes::auto_note_settings::has_auto_note_enabled(), MapExtras::mapExtraFactory(), and auto_notes::auto_note_settings::was_discovered().
Member Function Documentation
fill_custom_symbols_cache()
void auto_notes::auto_note_manager_gui::fill_custom_symbols_cache () private
Definition at line 271 of file auto_note.cpp.
 {
     const auto_note_settings &settings = get_auto_notes_settings();
     char_custom_symbol_cache.clear();
     global_custom_symbol_cache.clear();
     for( const std::pair<const map_extra_id &, const auto_notes::custom_symbol &> symbol_entry :
          settings.character_custom_symbols ) {
         char_custom_symbol_cache.emplace( symbol_entry.first, symbol_entry.second );
     }
     for( const std::pair<const map_extra_id &, const auto_notes::custom_symbol &> symbol_entry :
          settings.global_custom_symbols ) {
         global_custom_symbol_cache.emplace( symbol_entry.first, symbol_entry.second );
     }
 }
References char_custom_symbol_cache, auto_notes::auto_note_settings::character_custom_symbols, get_auto_notes_settings(), global_custom_symbol_cache, and auto_notes::auto_note_settings::global_custom_symbols.
Referenced by auto_note_manager_gui().
set_cached_custom_symbol()
void auto_notes::auto_note_manager_gui::set_cached_custom_symbol (const map_extra_id & mapExtId, const custom_symbol & symbol, bool bCharacter)
Definition at line 286 of file auto_note.cpp.
 {
     auto found = ( bCharacter ? char_custom_symbol_cache : global_custom_symbol_cache ).find(
                      mapExtId );
     if( found == ( bCharacter ? char_custom_symbol_cache : global_custom_symbol_cache ).end() ) {
         ( bCharacter ? char_custom_symbol_cache : global_custom_symbol_cache ).emplace( mapExtId, symbol );
     } else {
         found->second = symbol;
     }
 }
References char_custom_symbol_cache, global_custom_symbol_cache, and symbol().
Referenced by show().
show()
void auto_notes::auto_note_manager_gui::show ()
Definition at line 298 of file auto_note.cpp.
 {
     const int iHeaderHeight = 4;
     int iContentHeight = 0;
     catacurses::window w_border;
     catacurses::window w_header;
     catacurses::window w;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         iContentHeight = FULL_SCREEN_HEIGHT - 2 - iHeaderHeight;
         const point iOffset( TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0,
                              TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0 );
         w_border = catacurses::newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
                                        iOffset );
         w_header = catacurses::newwin( iHeaderHeight, FULL_SCREEN_WIDTH - 2,
                                        iOffset + point_south_east );
         w = catacurses::newwin( iContentHeight, FULL_SCREEN_WIDTH - 2,
                                 iOffset + point( 1, iHeaderHeight + 1 ) );
         ui.position_from_window( w_border );
     } );
     ui.mark_resize();
     // ===========================================================================
     // If the display cache contains no entries, the player might not have discovered any of
     // the map extras. In this case, we switch to a special state that alerts the user of this
     // in order to avoid confusion a completely empty GUI might normally create.
     bool bCharacter = true;
     const bool char_emptyMode = char_displayCache.empty();
     const bool global_emptyMode = global_displayCache.empty();
     const int char_cacheSize = static_cast<int>( char_displayCache.size() );
     const int global_cacheSize = static_cast<int>( global_displayCache.size() );
     int currentLine = 0;
     int startPosition = 0;
     int endPosition = 0;
     input_context ctxt{ "AUTO_NOTES" };
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "SWITCH_AUTO_NOTE_OPTION" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "NEXT_TAB" );
     if( !char_emptyMode || !global_emptyMode ) {
         ctxt.register_navigate_ui_list();
         ctxt.register_action( "CONFIRM" );
         ctxt.register_action( "QUIT" );
         ctxt.register_action( "ENABLE_MAPEXTRA_NOTE" );
         ctxt.register_action( "DISABLE_MAPEXTRA_NOTE" );
         ctxt.register_action( "CHANGE_MAPEXTRA_CHARACTER" );
     }
     ui.on_redraw( [&]( const ui_adaptor & ) {
         // == Draw border
         draw_border( w_border, BORDER_COLOR, _( "Auto notes manager" ) );
         mvwputch( w_border, point( 0, iHeaderHeight - 1 ), c_light_gray, LINE_XXXO );
         mvwputch( w_border, point( 79, iHeaderHeight - 1 ), c_light_gray, LINE_XOXX );
         mvwputch( w_border, point( 52, FULL_SCREEN_HEIGHT - 1 ), c_light_gray, LINE_XXOX );
         mvwputch( w_border, point( 61, FULL_SCREEN_HEIGHT - 1 ), c_light_gray, LINE_XXOX );
         wnoutrefresh( w_border );
         // == Draw header
         int tmpx = 0;
         tmpx += shortcut_print( w_header, point( tmpx, 0 ), c_white, c_light_green, _( "<E>nable" ) ) + 2;
         tmpx += shortcut_print( w_header, point( tmpx, 0 ), c_white, c_light_green, _( "<D>isable" ) ) + 2;
         shortcut_print( w_header, point( tmpx, 0 ), c_white, c_light_green, _( "<Enter> - Toggle" ) );
         // Draw horizontal line and corner pieces of the table
         for( int x = 0; x < 78; x++ ) {
             if( x == 51 || x == 60 ) {
                 mvwputch( w_header, point( x, iHeaderHeight - 2 ), c_light_gray, LINE_OXXX );
                 mvwputch( w_header, point( x, iHeaderHeight - 1 ), c_light_gray, LINE_XOXO );
             } else {
                 mvwputch( w_header, point( x, iHeaderHeight - 2 ), c_light_gray, LINE_OXOX );
             }
         }
         tmpx = 17;
         tmpx += shortcut_print( w_header, point( tmpx, iHeaderHeight - 2 ),
                                 bCharacter ? hilite( c_white ) : c_white, c_light_green, _( "Character" ) ) + 2;
         shortcut_print( w_header, point( tmpx, iHeaderHeight - 2 ),
                         !bCharacter ? hilite( c_white ) : c_white, c_light_green, _( "Global" ) );
         mvwprintz( w_header, point( 1, iHeaderHeight - 1 ), c_white, _( "Map Extra" ) );
         mvwprintz( w_header, point( 53, iHeaderHeight - 1 ), c_white, _( "Symbol" ) );
         mvwprintz( w_header, point( 62, iHeaderHeight - 1 ), c_white, _( "Enabled" ) );
         wnoutrefresh( w_header );
         // TODO: Show info about custom symbols (hotkey, hint, state)
         std::string header_info_custom_symbols = string_format( _( "<color_light_green>%1$s</color> %2$s" ),
                 ctxt.get_desc( "CHANGE_MAPEXTRA_CHARACTER" ), _( "Change a symbol for map extra" ) );
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         fold_and_print( w_header, point( 0, 1 ), FULL_SCREEN_WIDTH - 2, c_white,
                         header_info_custom_symbols );
         mvwprintz( w_header, point( 39, 1 ), c_white, _( "Auto notes enabled:" ) );
         int currentX = 60;
         mvwprintz( w_header, point( currentX, 1 ), c_white,
                    std::string( FULL_SCREEN_WIDTH - 2 - currentX, ' ' ) );
         const bool enabled_auto_notes_ME = get_option<bool>( "AUTO_NOTES_MAP_EXTRAS" );
         currentX += shortcut_print( w_header, point( currentX, 1 ),
                                     enabled_auto_notes_ME ? c_light_green : c_light_red, c_white,
                                     enabled_auto_notes_ME ? _( "True" ) : _( "False" ) );
         currentX += shortcut_print( w_header, point( currentX, 1 ), c_white, c_light_green, "  " );
         shortcut_print( w_header, point( currentX, 1 ), c_white, c_light_green, _( "<S>witch " ) );
         currentX = 39;
         mvwprintz( w_header, point( currentX, 0 ), c_white, std::string( FULL_SCREEN_WIDTH - 2 - currentX,
                    ' ' ) );
         shortcut_print( w_header, point( currentX, 0 ), c_white, c_light_green,
                         _( "<Tab> to change pages." ) );
         // Clear table
         for( int y = 0; y < iContentHeight; y++ ) {
             for( int x = 0; x < 79; x++ ) {
                 // The middle beams needs special treatment
                 if( x == 51 || x == 60 ) {
                     mvwputch( w, point( x, y ), c_light_gray, LINE_XOXO );
                 } else {
                     mvwputch( w, point( x, y ), c_black, ' ' );
                 }
             }
         }
         int cacheSize = bCharacter ? char_cacheSize : global_cacheSize;
         draw_scrollbar( w_border, currentLine, iContentHeight, cacheSize, point( 0, iHeaderHeight + 1 ) );
         if( bCharacter ? char_emptyMode : global_emptyMode ) {
             // NOLINTNEXTLINE(cata-use-named-point-constants)
             mvwprintz( w, point( 1, 0 ), c_light_gray,
                        _( "Discover more special encounters to populate this list" ) );
         } else {
             calcStartPos( startPosition, currentLine, iContentHeight,
                           ( bCharacter ? char_displayCache : global_displayCache ).size() );
             endPosition = startPosition + ( iContentHeight > cacheSize ? cacheSize : iContentHeight );
             for( int i = startPosition; i < endPosition; ++i ) {
                 const map_extra_id &displayCacheEntry = ( bCharacter ? char_displayCache : global_displayCache )[i];
                 const auto &cacheEntry = ( bCharacter ? char_mapExtraCache :
                                            global_mapExtraCache )[displayCacheEntry];
                 const nc_color lineColor = ( i == currentLine ) ? hilite( c_white ) : c_white;
                 const nc_color statusColor = enabled_auto_notes_ME ? ( cacheEntry.second ? c_green : c_red ) :
                                              c_dark_gray;
                 const std::string statusString = cacheEntry.second ? _( "yes" ) : _( "no" );
                 auto found_custom_symbol = ( bCharacter ? char_custom_symbol_cache :
                                              global_custom_symbol_cache ).find( displayCacheEntry );
                 const bool has_custom_symbol = ( found_custom_symbol != ( bCharacter ? char_custom_symbol_cache :
                                                  global_custom_symbol_cache ).end() );
                 const nc_color charColor = has_custom_symbol ? found_custom_symbol->second.get_color() :
                                            cacheEntry.first.color;
                 const std::string displayChar = has_custom_symbol ? found_custom_symbol->second.get_symbol_string()
                                                 :
                                                 cacheEntry.first.get_symbol();
                 mvwprintz( w, point( 1, i - startPosition ), lineColor, "" );
                 if( i == currentLine ) {
                     wprintz( w, c_yellow, ">> " );
                 } else {
                     wprintz( w, c_yellow, "   " );
                 }
                 wprintz( w, lineColor, "%s", cacheEntry.first.name() );
                 // Print the character this map extra is indicated by on the map
                 mvwprintz( w, point( 55, i - startPosition ), charColor, "%s", displayChar );
                 if( has_custom_symbol ) {
                     mvwprintz( w, point( 56, i - startPosition ), c_white, "*" );
                 }
                 // Since yes is longer than no, we need to clear the space for the status string before
                 // displaying the current text. Otherwise artifacts might occur.
                 mvwprintz( w, point( 64, i - startPosition ), statusColor, "     " );
                 mvwprintz( w, point( 64, i - startPosition ), statusColor, "%s", statusString );
             }
         }
         wnoutrefresh( w_header );
         wnoutrefresh( w_border );
         wnoutrefresh( w );
     } );
     while( true ) {
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         // Actions that also work with no items to display
         if( action == "SWITCH_AUTO_NOTE_OPTION" ) {
             get_options().get_option( "AUTO_NOTES_MAP_EXTRAS" ).setNext();
             get_options().save();
         } else if( action == "QUIT" ) {
             break;
         } else if( action == "NEXT_TAB" ) {
             bCharacter = !bCharacter;
         }
         if( bCharacter ? char_emptyMode : global_emptyMode ) {
             continue;
         }
         int cacheSize = bCharacter ? char_cacheSize : global_cacheSize;
         const map_extra_id &currentItem = ( bCharacter ? char_displayCache :
                                             global_displayCache )[currentLine];
         std::pair<const map_extra, bool> &entry = ( bCharacter ? char_mapExtraCache :
                 global_mapExtraCache )[currentItem];
         const int scroll_rate = cacheSize > 20 ? 10 : 3;
         if( navigate_ui_list( action, currentLine, scroll_rate, cacheSize, true ) ) {
         } else if( action == "ENABLE_MAPEXTRA_NOTE" ) {
             entry.second = true;
             ( bCharacter ? charwasChanged : globalwasChanged ) = true;
         } else if( action == "DISABLE_MAPEXTRA_NOTE" ) {
             entry.second = false;
             ( bCharacter ? charwasChanged : globalwasChanged ) = true;
         } else if( action == "CHANGE_MAPEXTRA_CHARACTER" ) {
             string_input_popup custom_symbol_popup;
             custom_symbol_popup
             .title( _( "Enter a map extra custom symbol (empty to unset):" ) )
             .width( 2 )
             .query_string();
             if( !custom_symbol_popup.canceled() ) {
                 const std::string &custom_symbol_str = custom_symbol_popup.text();
                 if( custom_symbol_str.empty() ) {
                     ( bCharacter ? char_custom_symbol_cache : global_custom_symbol_cache ).erase( currentItem );
                 } else {
                     uilist ui_colors;
                     ui_colors.text = _( "Pick a color:" );
                     int i = 0;
                     const std::unordered_map<std::string, note_color> &note_color_names = get_note_color_names();
                     for( const std::pair<const std::string, note_color> &color_pair : note_color_names ) {
                         ui_colors.addentry( string_format( pgettext( "note color", "%1$s:%2$s, " ), color_pair.first,
                                                            colorize( color_pair.second.name, color_pair.second.color ) ) );
                         if( entry.first.color == color_pair.second.color ) {
                             ui_colors.selected = i;
                         }
                         i++;
                     }
                     // Default note color is the last one
                     const nc_color color_default = c_yellow;
                     const color_manager &colors = get_all_colors();
                     const std::string color_default_name = colors.get_name( color_default );
                     const translation color_yellow = to_translation( "color", "yellow" );
                     ui_colors.addentry( string_format( _( "Default: %s" ),
                                                        colorize( color_yellow.translated(), color_default ) ) );
                     ui_colors.query();
                     std::string custom_symbol_color;
                     if( ui_colors.ret >= 0 && static_cast<size_t>( ui_colors.ret ) < note_color_names.size() ) {
                         auto iter = note_color_names.begin();
                         std::advance( iter, ui_colors.ret );
                         // selected color
                         custom_symbol_color = colors.get_name( iter->second.color );
                     }
                     custom_symbol value_to_set;
                     value_to_set.set_symbol( custom_symbol_str );
                     value_to_set.set_color( custom_symbol_color );
                     set_cached_custom_symbol( currentItem, value_to_set, bCharacter );
                 }
                 ( bCharacter ? charwasChanged : globalwasChanged ) = true;
             }
         } else if( action == "CONFIRM" ) {
             entry.second = !entry.second;
             ( bCharacter ? charwasChanged : globalwasChanged ) = true;
         }
     }
     if( !get_option<bool>( "AUTO_NOTES" ) &&
         get_option<bool>( "AUTO_NOTES_MAP_EXTRAS" ) &&
         query_yn( _( "Auto notes are disabled globally.\nDo you want to enable?" ) ) ) {
         get_options().get_option( "AUTO_NOTES" ).setNext();
         get_options().save();
     }
     if( !was_changed( false ) && !was_changed( true ) ) {
         return;
     }
     if( query_yn( _( "Save changes?" ) ) ) {
         auto_notes::auto_note_settings &settings = get_auto_notes_settings();
         for( const auto &entry : char_mapExtraCache ) {
             settings.set_auto_note_status( entry.second.first.id, entry.second.second, true );
         }
         for( const auto &entry : global_mapExtraCache ) {
             settings.set_auto_note_status( entry.second.first.id, entry.second.second, false );
         }
         settings.clear_all_custom_symbols( true );
         settings.clear_all_custom_symbols( false );
         for( const auto &entry : char_custom_symbol_cache ) {
             settings.set_custom_symbol( entry.first, entry.second, true );
         }
         for( const auto &entry : global_custom_symbol_cache ) {
             settings.set_custom_symbol( entry.first, entry.second, false );
         }
     }
 }
References _, action, uilist::addentry(), BORDER_COLOR, c_black, c_dark_gray, c_green, c_light_gray, c_light_green, c_light_red, c_red, c_white, c_yellow, calcStartPos(), string_input_popup::canceled(), char_custom_symbol_cache, char_displayCache, char_mapExtraCache, charwasChanged, auto_notes::auto_note_settings::clear_all_custom_symbols(), colorize(), PATH_INFO::colors(), draw_border(), draw_scrollbar(), keycode::end, catacurses::erase(), fold_and_print(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, get_all_colors(), get_auto_notes_settings(), get_note_color_names(), options_manager::get_option(), get_options(), global_custom_symbol_cache, global_displayCache, global_mapExtraCache, globalwasChanged, hilite(), LINE_OXOX, LINE_OXXX, LINE_XOXO, LINE_XOXX, LINE_XXOX, LINE_XXXO, mvwprintz(), mvwputch(), navigate_ui_list(), catacurses::newwin(), pgettext, point_south_east, uilist::query(), string_input_popup::query_string(), query_yn(), ui_manager::redraw(), input_context::register_action(), uilist::ret, options_manager::save(), uilist::selected, auto_notes::auto_note_settings::set_auto_note_status(), set_cached_custom_symbol(), auto_notes::custom_symbol::set_color(), auto_notes::auto_note_settings::set_custom_symbol(), auto_notes::custom_symbol::set_symbol(), options_manager::cOpt::setNext(), shortcut_print(), om_direction::size, string_format(), TERMX, TERMY, string_input_popup::text(), uilist::text, string_input_popup::title(), to_translation(), translation::translated(), was_changed(), catacurses::wnoutrefresh(), and wprintz().
Referenced by auto_notes::auto_note_settings::show_gui().
was_changed()
bool auto_notes::auto_note_manager_gui::was_changed (bool bCharacter) const
Definition at line 266 of file auto_note.cpp.
 {
     return bCharacter ? charwasChanged : globalwasChanged;
 }
References charwasChanged, and globalwasChanged.
Referenced by show().
Member Data Documentation
char_custom_symbol_cache
std::unordered_map<map_extra_id, custom_symbol> auto_notes::auto_note_manager_gui::char_custom_symbol_cache private
Definition at line 92 of file auto_note.h.
Referenced by fill_custom_symbols_cache(), set_cached_custom_symbol(), and show().
char_displayCache
std::vector<map_extra_id> auto_notes::auto_note_manager_gui::char_displayCache private
All map extra types for the character that will be displayed in the GUI.
Definition at line 87 of file auto_note.h.
Referenced by auto_note_manager_gui(), and show().
char_mapExtraCache
std::unordered_map<map_extra_id, std::pair<const map_extra, bool> > auto_notes::auto_note_manager_gui::char_mapExtraCache private
The map extra type cache.
This is initialized with all known map extra types and their auto note status with every call of initialize(). All changes to this will be applied to the per-character or global auto notes settings object after the user closes the GUI.
Definition at line 83 of file auto_note.h.
Referenced by auto_note_manager_gui(), and show().
charwasChanged
bool auto_notes::auto_note_manager_gui::charwasChanged {false} private
Definition at line 97 of file auto_note.h.
Referenced by show(), and was_changed().
global_custom_symbol_cache
std::unordered_map<map_extra_id, custom_symbol> auto_notes::auto_note_manager_gui::global_custom_symbol_cache private
Definition at line 93 of file auto_note.h.
Referenced by fill_custom_symbols_cache(), set_cached_custom_symbol(), and show().
global_displayCache
std::vector<map_extra_id> auto_notes::auto_note_manager_gui::global_displayCache private
All map extra types for global types that will be displayed in the GUI.
Definition at line 90 of file auto_note.h.
Referenced by auto_note_manager_gui(), and show().
global_mapExtraCache
std::unordered_map<map_extra_id, std::pair<const map_extra, bool> > auto_notes::auto_note_manager_gui::global_mapExtraCache private
Definition at line 84 of file auto_note.h.
Referenced by auto_note_manager_gui(), and show().
globalwasChanged
bool auto_notes::auto_note_manager_gui::globalwasChanged {false} private
Definition at line 98 of file auto_note.h.
Referenced by show(), and was_changed().
The documentation for this class was generated from the following files:
src/auto_note.h
src/auto_note.cpp