Cataclysm DDA: ebooksave_activity_actor Class Reference
ebooksave_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
ebooksave_activity_actor (const std::vector< item_location > &books, const item_location &ereader)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &act, Character &who) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static int pages_in_book (const itype_id &book)
static int total_pages (const std::vector< item_location > &books)
static time_duration required_time (const std::vector< item_location > &books)
static int required_charges (const std::vector< item_location > &books, const item_location &ereader)
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
void start_scanning_next_book (player_activity &act)
void completed_scanning_current_book (player_activity &act, Character &who)
Private Attributes
std::vector< item_location > books
All remaining books left to scan.
item_location ereader
int handled_books = 0
How many books this activity has scanned to ereader so far.
int turns_left_on_current_book = 0
How much time is left on this book until it is fully scanned and we can move on to the next book.
Static Private Attributes
static constexpr time_duration time_per_page = 5_seconds
static constexpr int pages_per_charge = 25
Detailed Description
Definition at line 669 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
ebooksave_activity_actor()
ebooksave_activity_actor::ebooksave_activity_actor (const std::vector< item_location > & books, const item_location & ereader) inline explicit
Definition at line 672 of file activity_actor_definitions.h.
                                                                           :
             books( books ), ereader( ereader ) {};
Referenced by deserialize().
Member Function Documentation
canceled()
void ebooksave_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 3044 of file activity_actor.cpp.
 {
     if( who.is_avatar() ) {
         add_msg( m_info, _( "You stop scanning the remaining books." ) );
     } else { // who.is_npc()
         add_msg_if_player_sees( who, _( "%s stops scanning books." ),
                                 who.disp_name( false, true ) );
     }
     act.set_to_null();
 }
References _, act, add_msg(), add_msg_if_player_sees(), Character::disp_name(), Creature::is_avatar(), and m_info.
clone()
std::unique_ptr<activity_actor> ebooksave_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 694 of file activity_actor_definitions.h.
{
             return std::make_unique<ebooksave_activity_actor>( *this );
         }
Referenced by deserialize().
completed_scanning_current_book()
void ebooksave_activity_actor::completed_scanning_current_book (player_activity & act, Character & who) private
Definition at line 3007 of file activity_actor.cpp.
 {
     item_location scanned_book = books.back();
     books.pop_back();
     if( scanned_book ) {
         ereader->put_in( *scanned_book, pocket_type::EBOOK );
         if( who.is_avatar() ) {
             if( !who.has_identified( scanned_book->typeId() ) ) {
                 who.identify( *scanned_book );
             }
         }
         handled_books++;
     } else {
         add_msg_debug( debugmode::DF_ACT_EBOOK,
                        "Spent time to scan book at %s, but it is no longer available?",
                        scanned_book.describe() );
     }
     start_scanning_next_book( act );
 }
References act, add_msg_debug, books, item_location::describe(), debugmode::DF_ACT_EBOOK, EBOOK, ereader, handled_books, Character::has_identified(), Character::identify(), Creature::is_avatar(), item::put_in(), start_scanning_next_book(), and item::typeId().
Referenced by do_turn(), and finish().
deserialize()
std::unique_ptr< activity_actor > ebooksave_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 3065 of file activity_actor.cpp.
 {
     ebooksave_activity_actor actor = ebooksave_activity_actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "books", actor.books );
     if( data.has_member( "book" ) ) {
         // legacy compatibility: in 0.G, this activity only handled one book each
         item_location book;
         data.read( "book", book );
         actor.books.push_back( book );
     }
     data.read( "ereader", actor.ereader );
     data.read( "handled_books", actor.handled_books );
     data.read( "turns_left_on_current_book", actor.turns_left_on_current_book );
     return actor.clone();
 }
References books, clone(), ebooksave_activity_actor(), ereader, JsonValue::get_object(), handled_books, JsonObject::read(), and turns_left_on_current_book.
do_turn()
void ebooksave_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 2981 of file activity_actor.cpp.
 {
     // only consume charges every 25 pages
     if( calendar::once_every( pages_per_charge * time_per_page ) ) {
         if( !ereader->ammo_sufficient( &who ) ) {
             add_msg_if_player_sees(
                 who,
                 _( "%1$s %2$s ran out of batteries." ),
                 who.disp_name( true, true ),
                 item::nname( ereader->typeId() ) );
             who.cancel_activity();
             return;
         }
         ereader->ammo_consume( ereader->ammo_required(), who.pos(), &who );
     }
     turns_left_on_current_book--;
     if( turns_left_on_current_book > 0 ) {
         return; // not fully scanned yet
     }
     // We have now spent enough time to fully scan current book
     completed_scanning_current_book( act, who );
 }
References _, act, add_msg_if_player_sees(), item::ammo_consume(), item::ammo_required(), item::ammo_sufficient(), Character::cancel_activity(), completed_scanning_current_book(), Character::disp_name(), ereader, item::nname(), calendar::once_every(), pages_per_charge, Creature::pos(), time_per_page, turns_left_on_current_book, and item::typeId().
finish()
void ebooksave_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 3028 of file activity_actor.cpp.
 {
     while( !books.empty() ) {
         // We can end up here with books left if the player has speed>100
         completed_scanning_current_book( act, who );
     }
     if( who.is_avatar() ) {
         add_msg( m_info, _( "You scan %d %s into your device." ), handled_books,
                  n_gettext( "book", "books", handled_books ) );
     } else { // who.is_npc()
         add_msg_if_player_sees( who, _( "%s scans %d %s into their device." ),
                                 who.disp_name( false, true ), handled_books, n_gettext( "book", "books", handled_books ) );
     }
     act.set_to_null();
 }
References _, act, add_msg(), add_msg_if_player_sees(), books, completed_scanning_current_book(), Character::disp_name(), handled_books, Creature::is_avatar(), m_info, and n_gettext.
get_type()
activity_id ebooksave_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 676 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_EBOOKSAVE" );
         }
References activity_id.
pages_in_book()
static int ebooksave_activity_actor::pages_in_book (const itype_id & book) inline static
Definition at line 680 of file activity_actor_definitions.h.
{
             // an A4 sheet weights roughly 5 grams
             return std::max( 1, static_cast<int>( units::to_gram( book->weight ) / 5 ) );
         };
References max(), units::to_gram(), and itype::weight.
Referenced by start_scanning_next_book(), and total_pages().
required_charges()
int ebooksave_activity_actor::required_charges (const std::vector< item_location > & books, const item_location & ereader) static
Definition at line 2947 of file activity_actor.cpp.
 {
     const int charges = total_pages( books ) / pages_per_charge;
     return charges * ereader->ammo_required();
 }
References item::ammo_required(), books, ereader, pages_per_charge, and total_pages().
Referenced by game_menus::inv::ebooksave().
required_time()
time_duration ebooksave_activity_actor::required_time (const std::vector< item_location > & books) static
Definition at line 2941 of file activity_actor.cpp.
 {
     return total_pages( books ) * time_per_page;
 }
References books, time_per_page, and total_pages().
Referenced by game_menus::inv::ebooksave(), start(), and start_scanning_next_book().
serialize()
void ebooksave_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 3055 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "books", books );
     jsout.member( "ereader", ereader );
     jsout.member( "handled_books", handled_books );
     jsout.member( "turns_left_on_current_book", turns_left_on_current_book );
     jsout.end_object();
 }
References books, JsonOut::end_object(), ereader, handled_books, JsonOut::member(), JsonOut::start_object(), and turns_left_on_current_book.
start()
void ebooksave_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 2972 of file activity_actor.cpp.
 {
     const time_duration scanning_time = required_time( books );
     add_msg_debug( debugmode::DF_ACT_EBOOK, "scanning_time time = %s",
                    to_string_writable( scanning_time ) );
     act.moves_total = to_moves<int>( scanning_time );
     start_scanning_next_book( act );
 }
References act, add_msg_debug, books, debugmode::DF_ACT_EBOOK, required_time(), start_scanning_next_book(), and to_string_writable().
start_scanning_next_book()
void ebooksave_activity_actor::start_scanning_next_book (player_activity & act) private
Definition at line 2955 of file activity_actor.cpp.
 {
     while( !books.empty() && !books.back() ) {
         add_msg_debug( debugmode::DF_ACT_EBOOK, "Skipping unavailable book at %s",
                        books.back().describe() );
         books.pop_back();
     }
     if( books.empty() ) {
         act.moves_left = 0;
         return;
     }
     const item_location &current_book = books.back();
     const int pages_in_current_book = pages_in_book( current_book->typeId() );
     turns_left_on_current_book = to_turns<int>( pages_in_current_book * time_per_page );
     act.moves_left = to_moves<int>( required_time( books ) );
 }
References act, add_msg_debug, books, debugmode::DF_ACT_EBOOK, pages_in_book(), required_time(), time_per_page, turns_left_on_current_book, and item::typeId().
Referenced by completed_scanning_current_book(), and start().
total_pages()
int ebooksave_activity_actor::total_pages (const std::vector< item_location > & books) static
Definition at line 2931 of file activity_actor.cpp.
 {
     int pages = 0;
     for( const item_location &book : books ) {
         pages += pages_in_book( book->typeId() );
     }
     return pages;
 }
References books, and pages_in_book().
Referenced by required_charges(), and required_time().
Member Data Documentation
books
std::vector<item_location> ebooksave_activity_actor::books private
All remaining books left to scan.
After a book is fully scanned to ereader, this list is modified so that the scanned book is removed from here.
Definition at line 706 of file activity_actor_definitions.h.
Referenced by completed_scanning_current_book(), deserialize(), finish(), required_charges(), required_time(), serialize(), start(), start_scanning_next_book(), and total_pages().
ereader
item_location ebooksave_activity_actor::ereader private
Definition at line 707 of file activity_actor_definitions.h.
Referenced by completed_scanning_current_book(), deserialize(), do_turn(), required_charges(), and serialize().
handled_books
int ebooksave_activity_actor::handled_books = 0 private
How many books this activity has scanned to ereader so far.
Definition at line 709 of file activity_actor_definitions.h.
Referenced by completed_scanning_current_book(), deserialize(), finish(), and serialize().
pages_per_charge
constexpr int ebooksave_activity_actor::pages_per_charge = 25 static constexpr private
Definition at line 715 of file activity_actor_definitions.h.
Referenced by do_turn(), and required_charges().
time_per_page
constexpr time_duration ebooksave_activity_actor::time_per_page = 5_seconds static constexpr private
Definition at line 713 of file activity_actor_definitions.h.
Referenced by do_turn(), required_time(), and start_scanning_next_book().
turns_left_on_current_book
int ebooksave_activity_actor::turns_left_on_current_book = 0 private
How much time is left on this book until it is fully scanned and we can move on to the next book.
Definition at line 711 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), serialize(), and start_scanning_next_book().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp