Cataclysm DDA: bodypart Class Reference
bodypart Class Reference
#include <bodypart.h>
Public Member Functions
bodypart ()
bodypart (bodypart_str_id id)
bodypart_id get_id () const
void set_hp_to_max ()
bool is_at_max_hp () const
float get_wetness_percentage () const
int get_encumbrance_threshold () const
bool is_limb_overencumbered () const
bool has_conditional_flag (const json_character_flag &flag) const
std::set< matec_id > get_limb_techs () const
efftype_id get_windage_effect () const
Returns the string id of the effect to be used.
efftype_id get_no_power_effect () const
Returns the string id of the effect to be used.
std::vector< bp_onhit_effect > get_onhit_effects (damage_type_id dtype) const
float get_limb_score (const limb_score_id &score, int skill=-1, int override_encumb=-1, int override_wounds=-1) const
float get_limb_score_max (const limb_score_id &score) const
int get_hp_cur () const
int get_hp_max () const
float get_hit_size () const
int get_healed_total () const
int get_damage_bandaged () const
int get_damage_disinfected () const
int get_drench_capacity () const
int get_wetness () const
int get_frostbite_timer () const
units::temperature get_temp_cur () const
units::temperature get_temp_conv () const
int get_bmi_encumbrance_threshold () const
float get_bmi_encumbrance_scalar () const
int get_power_efficiency () const
std::array< int, NUM_WATER_TOLERANCE > get_mut_drench () const
const encumbrance_data & get_encumbrance_data () const
void set_hp_cur (int set)
void set_hp_max (int set)
void set_healed_total (int set)
void set_damage_bandaged (int set)
void set_damage_disinfected (int set)
void set_wetness (int set)
void set_temp_cur (units::temperature set)
void set_temp_conv (units::temperature set)
void set_frostbite_timer (int set)
void set_encumbrance_data (const encumbrance_data &set)
void set_mut_drench (const std::pair< water_tolerance, int > &set)
void mod_hp_cur (int mod)
void mod_hp_max (int mod)
void mod_healed_total (int mod)
void mod_damage_bandaged (int mod)
void mod_damage_disinfected (int mod)
void mod_wetness (int mod)
void mod_temp_cur (units::temperature_delta mod)
void mod_temp_conv (units::temperature_delta mod)
void mod_frostbite_timer (int mod)
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
Private Member Functions
float wound_adjusted_limb_value (float val) const
float encumb_adjusted_limb_value (float val) const
float skill_adjusted_limb_value (float val, int skill) const
Private Attributes
bodypart_str_id id
int hp_cur = 0
int hp_max = 0
int wetness = 0
units::temperature temp_cur = BODYTEMP_NORM
units::temperature temp_conv = BODYTEMP_NORM
int frostbite_timer = 0
int healed_total = 0
int damage_bandaged = 0
int damage_disinfected = 0
encumbrance_data encumb_data
std::array< int, NUM_WATER_TOLERANCE > mut_drench
Detailed Description
Definition at line 439 of file bodypart.h.
Constructor & Destructor Documentation
bodypart() [1/2]
bodypart::bodypart () inline
Definition at line 467 of file bodypart.h.
 : id( bodypart_str_id::NULL_ID() ), mut_drench() {}
bodypart() [2/2]
bodypart::bodypart (bodypart_str_id id) inline explicit
Definition at line 468 of file bodypart.h.
                                                : id( id ), hp_cur( id->base_hp ), hp_max( id->base_hp ),
             mut_drench() {}
Member Function Documentation
deserialize()
void bodypart::deserialize (const JsonObject & jo)
Definition at line 1203 of file bodypart.cpp.
 {
     jo.read( "id", id, true );
     jo.read( "hp_cur", hp_cur, true );
     jo.read( "hp_max", hp_max, true );
     jo.read( "healed_total", healed_total );
     jo.read( "damage_bandaged", damage_bandaged, true );
     jo.read( "damage_disinfected", damage_disinfected, true );
     jo.read( "wetness", wetness, true );
     if( int legacy_temp_cur; jo.read( "temp_cur", legacy_temp_cur, true ) ) {
         temp_cur = units::from_legacy_bodypart_temp( legacy_temp_cur );
     }
     if( int legacy_temp_conv; jo.read( "temp_conv", legacy_temp_conv, true ) ) {
         temp_conv = units::from_legacy_bodypart_temp( legacy_temp_conv );
     }
     jo.read( "frostbite_timer", frostbite_timer, true );
 }
References damage_bandaged, damage_disinfected, units::from_legacy_bodypart_temp(), frostbite_timer, healed_total, hp_cur, hp_max, JsonObject::read(), temp_conv, temp_cur, and wetness.
encumb_adjusted_limb_value()
float bodypart::encumb_adjusted_limb_value (float val) const private
Definition at line 956 of file bodypart.cpp.
 {
     int enc = get_encumbrance_data().encumbrance;
     // Check if we're over our encumbrance limit, return 0 if so
     if( is_limb_overencumbered() ) {
         return 0;
     }
     // Reduce encumbrance by the limb's encumbrance threshold, limiting to 0
     enc = std::max( 0, ( enc - get_encumbrance_threshold() ) );
     // This is designed to get a 5% adjustment for an increase of 3 encumbrance, with further
     // adjustments decreasing to avoid a multiplier of 0 (or infinity if reciprocal).
     return val * 19.0f / ( 19.0f + enc / 3.0f );
 }
References encumbrance_data::encumbrance, get_encumbrance_data(), get_encumbrance_threshold(), is_limb_overencumbered(), and max().
Referenced by get_limb_score().
get_bmi_encumbrance_scalar()
float bodypart::get_bmi_encumbrance_scalar () const
Definition at line 1062 of file bodypart.cpp.
 {
     return id->bmi_encumbrance_scalar;
 }
get_bmi_encumbrance_threshold()
int bodypart::get_bmi_encumbrance_threshold () const
Definition at line 1057 of file bodypart.cpp.
 {
     return id->bmi_encumbrance_threshold;
 }
get_damage_bandaged()
int bodypart::get_damage_bandaged () const
Definition at line 1017 of file bodypart.cpp.
 {
     return damage_bandaged;
 }
References damage_bandaged.
Referenced by Creature::get_part_damage_bandaged().
get_damage_disinfected()
int bodypart::get_damage_disinfected () const
Definition at line 1022 of file bodypart.cpp.
 {
     return damage_disinfected;
 }
References damage_disinfected.
Referenced by Creature::get_part_damage_disinfected().
get_drench_capacity()
int bodypart::get_drench_capacity () const
Definition at line 1032 of file bodypart.cpp.
 {
     return id->drench_max;
 }
Referenced by Creature::get_part_drench_capacity().
get_encumbrance_data()
const encumbrance_data & bodypart::get_encumbrance_data () const
Definition at line 1027 of file bodypart.cpp.
 {
     return encumb_data;
 }
References encumb_data.
Referenced by encumb_adjusted_limb_value(), get_limb_techs(), Creature::get_part_encumbrance_data(), and is_limb_overencumbered().
get_encumbrance_threshold()
int bodypart::get_encumbrance_threshold () const
Definition at line 908 of file bodypart.cpp.
 {
     return id->encumbrance_threshold;
 }
Referenced by encumb_adjusted_limb_value().
get_frostbite_timer()
int bodypart::get_frostbite_timer () const
Definition at line 1042 of file bodypart.cpp.
 {
     return frostbite_timer;
 }
References frostbite_timer.
Referenced by Creature::get_part_frostbite_timer().
get_healed_total()
int bodypart::get_healed_total () const
Definition at line 1012 of file bodypart.cpp.
 {
     return healed_total;
 }
References healed_total.
Referenced by Creature::get_part_healed_total().
get_hit_size()
float bodypart::get_hit_size () const
Definition at line 1072 of file bodypart.cpp.
 {
     return id->hit_size;
 }
get_hp_cur()
int bodypart::get_hp_cur () const
Definition at line 1002 of file bodypart.cpp.
 {
     return hp_cur;
 }
References hp_cur.
Referenced by Creature::get_part_hp_cur(), and wound_adjusted_limb_value().
get_hp_max()
int bodypart::get_hp_max () const
Definition at line 1007 of file bodypart.cpp.
 {
     return hp_max;
 }
References hp_max.
Referenced by Creature::get_part_hp_max(), and wound_adjusted_limb_value().
get_id()
bodypart_id bodypart::get_id () const
Definition at line 879 of file bodypart.cpp.
 {
     return id;
 }
References id.
Referenced by get_encumbrance_description().
get_limb_score()
float bodypart::get_limb_score (const limb_score_id & score, int skill = -1, int override_encumb = -1, int override_wounds = -1) const
Definition at line 976 of file bodypart.cpp.
 {
     bool process_wounds = override_wounds == 1 || ( override_wounds == -1 &&
                           score->affected_by_wounds() );
     bool process_encumb = override_encumb == 1 || ( override_encumb == -1 &&
                           score->affected_by_encumb() );
     float sc = id->get_limb_score( score );
     if( process_wounds ) {
         sc = wound_adjusted_limb_value( sc );
     }
     if( process_encumb ) {
         sc = encumb_adjusted_limb_value( sc );
     }
     if( skill >= 0 ) {
         sc = skill_adjusted_limb_value( sc, skill );
     }
     return sc;
 }
References encumb_adjusted_limb_value(), skill_adjusted_limb_value(), and wound_adjusted_limb_value().
Referenced by Character::block_hit(), character_martial_arts::can_arm_block(), character_martial_arts::can_leg_block(), character_martial_arts::can_nonstandard_block(), and get_encumbrance_description().
get_limb_score_max()
float bodypart::get_limb_score_max (const limb_score_id & score) const
Definition at line 997 of file bodypart.cpp.
 {
     return id->get_limb_score_max( score );
 }
get_limb_techs()
std::set< matec_id > bodypart::get_limb_techs () const
Definition at line 924 of file bodypart.cpp.
 {
     std::set<matec_id> result;
     if( !x_in_y( get_encumbrance_data().encumbrance, id->technique_enc_limit ) &&
         hp_cur > id->health_limit ) {
         result.insert( id->techniques.begin(), id->techniques.end() );
     }
     return result;
 }
References get_encumbrance_data(), body_part_type::health_limit, hp_cur, id, body_part_type::technique_enc_limit, body_part_type::techniques, and x_in_y().
Referenced by Character::get_limb_techs().
get_mut_drench()
std::array< int, NUM_WATER_TOLERANCE > bodypart::get_mut_drench () const
Definition at line 1067 of file bodypart.cpp.
 {
     return mut_drench;
 }
References mut_drench.
Referenced by Creature::get_part_mut_drench().
get_no_power_effect()
efftype_id bodypart::get_no_power_effect () const
Returns the string id of the effect to be used.
get_onhit_effects()
std::vector< bp_onhit_effect > bodypart::get_onhit_effects (damage_type_id dtype) const
Definition at line 934 of file bodypart.cpp.
 {
     std::vector<bp_onhit_effect> result;
     for( const bp_onhit_effect &effect : id->effects_on_hit ) {
         if( effect.dtype == dtype || effect.dtype == damage_type_id::NULL_ID() ) {
             result.push_back( effect );
         }
     }
     return result;
 }
References body_part_type::effects_on_hit, id, and string_id< damage_type >::NULL_ID().
get_power_efficiency()
int bodypart::get_power_efficiency () const
Definition at line 1077 of file bodypart.cpp.
 {
     return id->power_efficiency;
 }
get_temp_conv()
units::temperature bodypart::get_temp_conv () const
Definition at line 1052 of file bodypart.cpp.
 {
     return temp_conv;
 }
References temp_conv.
Referenced by Creature::get_part_temp_conv().
get_temp_cur()
units::temperature bodypart::get_temp_cur () const
Definition at line 1047 of file bodypart.cpp.
 {
     return temp_cur;
 }
References temp_cur.
Referenced by Creature::get_part_temp_cur().
get_wetness()
int bodypart::get_wetness () const
Definition at line 1037 of file bodypart.cpp.
 {
     return wetness;
 }
References wetness.
Referenced by Creature::get_part_wetness().
get_wetness_percentage()
float bodypart::get_wetness_percentage () const
Definition at line 894 of file bodypart.cpp.
 {
     if( id->drench_max == 0 ) {
         return 0.0f;
     } else {
         return static_cast<float>( wetness ) / id->drench_max;
     }
 }
References body_part_type::drench_max, id, and wetness.
Referenced by Creature::get_part_wetness_percentage(), and game::slip_down_chance().
get_windage_effect()
efftype_id bodypart::get_windage_effect () const
Returns the string id of the effect to be used.
Definition at line 903 of file bodypart.cpp.
 {
     return id->windage_effect;
 }
has_conditional_flag()
bool bodypart::has_conditional_flag (const json_character_flag & flag) const
Definition at line 918 of file bodypart.cpp.
 {
     return id->conditional_flags.count( flag ) > 0 && hp_cur > id->health_limit &&
            !is_limb_overencumbered();
 }
References hp_cur, and is_limb_overencumbered().
is_at_max_hp()
bool bodypart::is_at_max_hp () const
Definition at line 889 of file bodypart.cpp.
 {
     return hp_cur == hp_max;
 }
References hp_cur, and hp_max.
Referenced by Creature::is_part_at_max_hp().
is_limb_overencumbered()
bool bodypart::is_limb_overencumbered () const
Definition at line 913 of file bodypart.cpp.
 {
     return get_encumbrance_data().encumbrance >= id->encumbrance_limit;
 }
References encumbrance_data::encumbrance, and get_encumbrance_data().
Referenced by encumb_adjusted_limb_value(), and has_conditional_flag().
mod_damage_bandaged()
void bodypart::mod_damage_bandaged (int mod)
Definition at line 1155 of file bodypart.cpp.
 {
     damage_bandaged += mod;
 }
References damage_bandaged.
Referenced by Creature::mod_part_damage_bandaged().
mod_damage_disinfected()
void bodypart::mod_damage_disinfected (int mod)
Definition at line 1160 of file bodypart.cpp.
 {
     damage_disinfected += mod;
 }
References damage_disinfected.
Referenced by Creature::mod_part_damage_disinfected().
mod_frostbite_timer()
void bodypart::mod_frostbite_timer (int mod)
Definition at line 1180 of file bodypart.cpp.
 {
     frostbite_timer += mod;
 }
References frostbite_timer.
Referenced by Creature::mod_part_frostbite_timer().
mod_healed_total()
void bodypart::mod_healed_total (int mod)
Definition at line 1150 of file bodypart.cpp.
 {
     healed_total += mod;
 }
References healed_total.
Referenced by Creature::mod_part_healed_total().
mod_hp_cur()
void bodypart::mod_hp_cur (int mod)
Definition at line 1140 of file bodypart.cpp.
 {
     hp_cur += mod;
 }
References hp_cur.
Referenced by Creature::mod_part_hp_cur().
mod_hp_max()
void bodypart::mod_hp_max (int mod)
Definition at line 1145 of file bodypart.cpp.
 {
     hp_max += mod;
 }
References hp_max.
Referenced by Creature::mod_part_hp_max().
mod_temp_conv()
void bodypart::mod_temp_conv (units::temperature_delta mod)
Definition at line 1175 of file bodypart.cpp.
 {
     temp_conv += mod;
 }
References temp_conv.
Referenced by Creature::mod_part_temp_conv().
mod_temp_cur()
void bodypart::mod_temp_cur (units::temperature_delta mod)
Definition at line 1170 of file bodypart.cpp.
 {
     temp_cur += mod;
 }
References temp_cur.
Referenced by Creature::mod_part_temp_cur().
mod_wetness()
void bodypart::mod_wetness (int mod)
Definition at line 1165 of file bodypart.cpp.
 {
     wetness += mod;
 }
References wetness.
Referenced by Creature::mod_part_wetness().
serialize()
void bodypart::serialize (JsonOut & json) const
Definition at line 1185 of file bodypart.cpp.
 {
     json.start_object();
     json.member( "id", id );
     json.member( "hp_cur", hp_cur );
     json.member( "hp_max", hp_max );
     json.member( "healed_total", healed_total );
     json.member( "damage_bandaged", damage_bandaged );
     json.member( "damage_disinfected", damage_disinfected );
     json.member( "wetness", wetness );
     json.member( "temp_cur", units::to_legacy_bodypart_temp( temp_cur ) );
     json.member( "temp_conv", units::to_legacy_bodypart_temp( temp_conv ) );
     json.member( "frostbite_timer", frostbite_timer );
     json.end_object();
 }
References damage_bandaged, damage_disinfected, JsonOut::end_object(), frostbite_timer, healed_total, hp_cur, hp_max, JsonOut::member(), JsonOut::start_object(), temp_conv, temp_cur, units::to_legacy_bodypart_temp(), and wetness.
set_damage_bandaged()
void bodypart::set_damage_bandaged (int set)
Definition at line 1097 of file bodypart.cpp.
 {
     damage_bandaged = set;
 }
References damage_bandaged.
Referenced by Creature::set_part_damage_bandaged().
set_damage_disinfected()
void bodypart::set_damage_disinfected (int set)
Definition at line 1102 of file bodypart.cpp.
 {
     damage_disinfected = set;
 }
References damage_disinfected.
Referenced by Creature::set_part_damage_disinfected().
set_encumbrance_data()
void bodypart::set_encumbrance_data (const encumbrance_data & set)
Definition at line 1107 of file bodypart.cpp.
 {
     encumb_data = set;
 }
References encumb_data.
Referenced by Creature::set_part_encumbrance_data().
set_frostbite_timer()
void bodypart::set_frostbite_timer (int set)
Definition at line 1135 of file bodypart.cpp.
 {
     frostbite_timer = set;
 }
References frostbite_timer.
Referenced by Creature::set_part_frostbite_timer().
set_healed_total()
void bodypart::set_healed_total (int set)
Definition at line 1092 of file bodypart.cpp.
 {
     healed_total = set;
 }
References healed_total.
Referenced by Creature::set_part_healed_total().
set_hp_cur()
void bodypart::set_hp_cur (int set)
Definition at line 1082 of file bodypart.cpp.
 {
     hp_cur = set;
 }
References hp_cur.
Referenced by Creature::set_part_hp_cur().
set_hp_max()
void bodypart::set_hp_max (int set)
Definition at line 1087 of file bodypart.cpp.
 {
     hp_max = set;
 }
References hp_max.
Referenced by Creature::set_part_hp_max().
set_hp_to_max()
void bodypart::set_hp_to_max ()
Definition at line 884 of file bodypart.cpp.
 {
     hp_cur = hp_max;
 }
References hp_cur, and hp_max.
set_mut_drench()
void bodypart::set_mut_drench (const std::pair< water_tolerance, int > & set)
Definition at line 1112 of file bodypart.cpp.
 {
     if( set.first < WT_IGNORED || set.first > NUM_WATER_TOLERANCE ) {
         debugmsg( "Tried to use invalid water tolerance enum in set_mut_drench()." );
     }
     mut_drench[set.first] = set.second;
 }
References debugmsg, mut_drench, NUM_WATER_TOLERANCE, and WT_IGNORED.
Referenced by Creature::set_part_mut_drench().
set_temp_conv()
void bodypart::set_temp_conv (units::temperature set)
Definition at line 1130 of file bodypart.cpp.
 {
     temp_conv = set;
 }
References temp_conv.
Referenced by Creature::set_part_temp_conv().
set_temp_cur()
void bodypart::set_temp_cur (units::temperature set)
Definition at line 1125 of file bodypart.cpp.
 {
     temp_cur = set;
 }
References temp_cur.
Referenced by Creature::set_part_temp_cur().
set_wetness()
void bodypart::set_wetness (int set)
Definition at line 1120 of file bodypart.cpp.
 {
     wetness = set;
 }
References wetness.
Referenced by Creature::set_part_wetness().
skill_adjusted_limb_value()
float bodypart::skill_adjusted_limb_value (float val, int skill) const private
Definition at line 970 of file bodypart.cpp.
 {
     const float mitigated_score = val * ( 1.0f + ( skill / 10.0f ) );
     return std::min( val, mitigated_score );
 }
References min().
Referenced by get_limb_score().
wound_adjusted_limb_value()
float bodypart::wound_adjusted_limb_value (float val) const private
Definition at line 945 of file bodypart.cpp.
 {
     double percent = static_cast<double>( get_hp_cur() ) /
                      static_cast<double>( get_hp_max() );
     if( percent > 0.75 ) {
         return val;
     }
     percent /= 0.75;
     return val * static_cast<float>( percent );
 }
References get_hp_cur(), and get_hp_max().
Referenced by get_limb_score().
Member Data Documentation
damage_bandaged
int bodypart::damage_bandaged = 0 private
Definition at line 453 of file bodypart.h.
Referenced by deserialize(), get_damage_bandaged(), mod_damage_bandaged(), serialize(), and set_damage_bandaged().
damage_disinfected
int bodypart::damage_disinfected = 0 private
Definition at line 454 of file bodypart.h.
Referenced by deserialize(), get_damage_disinfected(), mod_damage_disinfected(), serialize(), and set_damage_disinfected().
encumb_data
encumbrance_data bodypart::encumb_data private
Definition at line 456 of file bodypart.h.
Referenced by get_encumbrance_data(), and set_encumbrance_data().
frostbite_timer
int bodypart::frostbite_timer = 0 private
Definition at line 450 of file bodypart.h.
Referenced by deserialize(), get_frostbite_timer(), mod_frostbite_timer(), serialize(), and set_frostbite_timer().
healed_total
int bodypart::healed_total = 0 private
Definition at line 452 of file bodypart.h.
Referenced by deserialize(), get_healed_total(), mod_healed_total(), serialize(), and set_healed_total().
hp_cur
int bodypart::hp_cur = 0 private
Definition at line 444 of file bodypart.h.
Referenced by deserialize(), get_hp_cur(), get_limb_techs(), has_conditional_flag(), is_at_max_hp(), mod_hp_cur(), serialize(), set_hp_cur(), and set_hp_to_max().
hp_max
int bodypart::hp_max = 0 private
Definition at line 445 of file bodypart.h.
Referenced by deserialize(), get_hp_max(), is_at_max_hp(), mod_hp_max(), serialize(), set_hp_max(), and set_hp_to_max().
id
bodypart_str_id bodypart::id private
Definition at line 442 of file bodypart.h.
Referenced by get_id(), get_limb_techs(), get_onhit_effects(), get_wetness_percentage(), and item::portion_for_bodypart().
mut_drench
std::array<int, NUM_WATER_TOLERANCE> bodypart::mut_drench private
Definition at line 458 of file bodypart.h.
Referenced by get_mut_drench(), and set_mut_drench().
temp_conv
units::temperature bodypart::temp_conv = BODYTEMP_NORM private
Definition at line 449 of file bodypart.h.
Referenced by deserialize(), get_temp_conv(), mod_temp_conv(), serialize(), and set_temp_conv().
temp_cur
units::temperature bodypart::temp_cur = BODYTEMP_NORM private
Definition at line 448 of file bodypart.h.
Referenced by deserialize(), get_temp_cur(), mod_temp_cur(), serialize(), and set_temp_cur().
wetness
int bodypart::wetness = 0 private
Definition at line 447 of file bodypart.h.
Referenced by deserialize(), get_wetness(), get_wetness_percentage(), mod_wetness(), serialize(), and set_wetness().
The documentation for this class was generated from the following files:
src/bodypart.h
src/bodypart.cpp