Cataclysm DDA: proficiency Class Reference
proficiency Class Reference
#include <proficiency.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
bool can_learn () const
bool ignore_focus () const
bool is_teachable () const
proficiency_id prof_id () const
proficiency_category_id prof_category () const
std::string name () const
std::string description () const
float default_time_multiplier () const
float default_skill_penalty () const
float default_weakpoint_bonus () const
float default_weakpoint_penalty () const
time_duration time_to_learn () const
std::set< proficiency_id > required_proficiencies () const
std::vector< proficiency_bonus > get_bonuses (const std::string &category) const
std::optional< float > bonus_for (const std::string &category, proficiency_bonus_type type) const
Static Public Member Functions
static void load_proficiencies (const JsonObject &jo, const std::string &src)
static void reset ()
static const std::vector< proficiency > & get_all ()
Private Attributes
proficiency_id id
proficiency_category_id _category
std::vector< std::pair< proficiency_id, mod_id > > src
bool was_loaded = false
bool _can_learn = false
bool _ignore_focus = false
bool _teachable = true
translation _name
translation _description
float _default_time_multiplier = 2.0f
float _default_skill_penalty = 1.0f
float _default_weakpoint_bonus = 0.0f
float _default_weakpoint_penalty = 0.0f
time_duration _time_to_learn = 9999_hours
std::set< proficiency_id > _required
std::map< std::string, std::vector< proficiency_bonus > > _bonuses
Friends
class generic_factory< proficiency >
struct mod_tracker
Detailed Description
Definition at line 63 of file proficiency.h.
Member Function Documentation
bonus_for()
std::optional< float > proficiency::bonus_for (const std::string & category, proficiency_bonus_type type) const
Definition at line 224 of file proficiency.cpp.
 {
     auto bonus_it = _bonuses.find( category );
     if( bonus_it == _bonuses.end() ) {
         return std::nullopt;
     }
     for( const proficiency_bonus &b : bonus_it->second ) {
         if( b.type == type ) {
             return b.value;
         }
     }
     return std::nullopt;
 }
References _bonuses, b, anonymous_namespace{item_tname.cpp}::category(), and type.
can_learn()
bool proficiency::can_learn () const
Definition at line 140 of file proficiency.cpp.
 {
     if( _can_learn ) {
         const double scaling = get_option<float>( "PROFICIENCY_TRAINING_SPEED" );
         return scaling != 0.0;
     } else {
         return false;
     }
 }
References _can_learn.
Referenced by draw_proficiencies_tab(), and proficiency_set::practice().
default_skill_penalty()
float proficiency::default_skill_penalty () const
Definition at line 185 of file proficiency.cpp.
 {
     return _default_skill_penalty;
 }
References _default_skill_penalty.
default_time_multiplier()
float proficiency::default_time_multiplier () const
Definition at line 180 of file proficiency.cpp.
 {
     return _default_time_multiplier;
 }
References _default_time_multiplier.
default_weakpoint_bonus()
float proficiency::default_weakpoint_bonus () const
Definition at line 190 of file proficiency.cpp.
 {
     return _default_weakpoint_bonus;
 }
References _default_weakpoint_bonus.
Referenced by weakpoint_family::modifier().
default_weakpoint_penalty()
float proficiency::default_weakpoint_penalty () const
Definition at line 195 of file proficiency.cpp.
 {
     return _default_weakpoint_penalty;
 }
References _default_weakpoint_penalty.
Referenced by weakpoint_family::modifier().
description()
std::string proficiency::description () const
Definition at line 175 of file proficiency.cpp.
 {
     return _description.translated();
 }
References _description, and translation::translated().
Referenced by draw_proficiencies_info(), and diary::prof_changes().
get_all()
const std::vector< proficiency > & proficiency::get_all () static
Definition at line 130 of file proficiency.cpp.
 {
     return proficiency_factory.get_all();
 }
References anonymous_namespace{proficiency.cpp}::proficiency_factory.
Referenced by prof_window::populate_categories(), and debug_menu::wishproficiency().
get_bonuses()
std::vector< proficiency_bonus > proficiency::get_bonuses (const std::string & category) const
Definition at line 215 of file proficiency.cpp.
 {
     auto bonus_it = _bonuses.find( category );
     if( bonus_it == _bonuses.end() ) {
         return std::vector<proficiency_bonus>();
     }
     return bonus_it->second;
 }
References _bonuses, and anonymous_namespace{item_tname.cpp}::category().
ignore_focus()
bool proficiency::ignore_focus () const
Definition at line 150 of file proficiency.cpp.
 {
     return _ignore_focus;
 }
References _ignore_focus.
is_teachable()
bool proficiency::is_teachable () const
Definition at line 155 of file proficiency.cpp.
 {
     return _teachable;
 }
References _teachable.
load()
void proficiency::load (const JsonObject & jo, std::string_view src)
Definition at line 98 of file proficiency.cpp.
 {
     mandatory( jo, was_loaded, "name", _name );
     mandatory( jo, was_loaded, "description", _description );
     mandatory( jo, was_loaded, "can_learn", _can_learn );
     mandatory( jo, was_loaded, "category", _category );
     optional( jo, was_loaded, "default_time_multiplier", _default_time_multiplier );
     optional( jo, was_loaded, "default_skill_penalty", _default_skill_penalty );
     optional( jo, was_loaded, "default_weakpoint_bonus", _default_weakpoint_bonus );
     optional( jo, was_loaded, "default_weakpoint_penalty", _default_weakpoint_penalty );
     optional( jo, was_loaded, "time_to_learn", _time_to_learn );
     optional( jo, was_loaded, "required_proficiencies", _required );
     optional( jo, was_loaded, "ignore_focus", _ignore_focus );
     optional( jo, was_loaded, "teachable", _teachable, true );
     optional( jo, was_loaded, "bonuses", _bonuses );
     // TODO: Remove at some point
     if( jo.has_float( "default_fail_multiplier" ) ) {
         debugmsg( "Proficiency %s uses 'default_fail_multiplier' instead of 'default_skill_penalty'!",
                   id.c_str() );
         _default_skill_penalty = jo.get_float( "default_fail_multiplier" ) - 1.f;
     }
 }
References _bonuses, _can_learn, _category, _default_skill_penalty, _default_time_multiplier, _default_weakpoint_bonus, _default_weakpoint_penalty, _description, _ignore_focus, _name, _required, _teachable, _time_to_learn, debugmsg, JsonObject::get_float(), JsonObject::has_float(), mandatory, optional(), and was_loaded.
load_proficiencies()
void proficiency::load_proficiencies (const JsonObject & jo, const std::string & src) static
Definition at line 71 of file proficiency.cpp.
 {
     proficiency_factory.load( jo, src );
 }
References anonymous_namespace{proficiency.cpp}::proficiency_factory, and src.
Referenced by DynamicDataLoader::initialize().
name()
std::string proficiency::name () const
Definition at line 170 of file proficiency.cpp.
 {
     return _name.translated();
 }
References _name, and translation::translated().
Referenced by butcher_submenu(), veh_interact::do_repair(), draw_proficiencies_info(), draw_proficiencies_tab(), dialogue::gen_responses(), memorial_logger::notify(), diary::prof_changes(), talker_character_const::proficiency_seminar_text(), talker_character_const::proficiency_training_text(), profstring(), activity_handlers::teach_finish(), and debug_menu::wishproficiency().
prof_category()
proficiency_category_id proficiency::prof_category () const
Definition at line 165 of file proficiency.cpp.
 {
     return _category;
 }
References _category.
prof_id()
proficiency_id proficiency::prof_id () const
Definition at line 160 of file proficiency.cpp.
 {
     return id;
 }
References id.
required_proficiencies()
std::set< proficiency_id > proficiency::required_proficiencies () const
Definition at line 210 of file proficiency.cpp.
 {
     return _required;
 }
References _required.
Referenced by book_proficiency_bonuses::add(), proficiency_set::has_prereqs(), and proficiency_set::learn().
reset()
void proficiency::reset () static
Definition at line 88 of file proficiency.cpp.
 {
     proficiency_factory.reset();
 }
References anonymous_namespace{proficiency.cpp}::proficiency_factory.
Referenced by DynamicDataLoader::unload_data().
time_to_learn()
time_duration proficiency::time_to_learn () const
Definition at line 200 of file proficiency.cpp.
 {
     const double scaling = get_option<float>( "PROFICIENCY_TRAINING_SPEED" );
     if( scaling != 1.0 && scaling != 0.0 ) {
         return _time_to_learn / scaling;
     } else {
         return _time_to_learn;
     }
 }
References _time_to_learn.
Referenced by proficiency_set::pct_practiced(), proficiency_set::pct_practiced_time(), proficiency_set::practice(), anonymous_namespace{math_parser_diag.cpp}::proficiency_ass(), anonymous_namespace{math_parser_diag.cpp}::proficiency_eval(), talker_character_const::proficiency_training_text(), proficiency_set::set_time_practiced(), and proficiency_set::training_time_needed().
Friends And Related Function Documentation
generic_factory< proficiency >
friend class generic_factory< proficiency > friend
Definition at line 60 of file proficiency.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 66 of file proficiency.h.
Member Data Documentation
_bonuses
std::map<std::string, std::vector<proficiency_bonus> > proficiency::_bonuses private
Definition at line 89 of file proficiency.h.
Referenced by bonus_for(), get_bonuses(), and load().
_can_learn
bool proficiency::_can_learn = false private
Definition at line 73 of file proficiency.h.
Referenced by can_learn(), and load().
_category
proficiency_category_id proficiency::_category private
Definition at line 69 of file proficiency.h.
Referenced by load(), and prof_category().
_default_skill_penalty
float proficiency::_default_skill_penalty = 1.0f private
Definition at line 81 of file proficiency.h.
Referenced by default_skill_penalty(), and load().
_default_time_multiplier
float proficiency::_default_time_multiplier = 2.0f private
Definition at line 80 of file proficiency.h.
Referenced by default_time_multiplier(), and load().
_default_weakpoint_bonus
float proficiency::_default_weakpoint_bonus = 0.0f private
Definition at line 83 of file proficiency.h.
Referenced by default_weakpoint_bonus(), and load().
_default_weakpoint_penalty
float proficiency::_default_weakpoint_penalty = 0.0f private
Definition at line 84 of file proficiency.h.
Referenced by default_weakpoint_penalty(), and load().
_description
translation proficiency::_description private
Definition at line 78 of file proficiency.h.
Referenced by description(), and load().
_ignore_focus
bool proficiency::_ignore_focus = false private
Definition at line 74 of file proficiency.h.
Referenced by ignore_focus(), and load().
_name
translation proficiency::_name private
Definition at line 77 of file proficiency.h.
Referenced by load(), and name().
_required
std::set<proficiency_id> proficiency::_required private
Definition at line 87 of file proficiency.h.
Referenced by load(), and required_proficiencies().
_teachable
bool proficiency::_teachable = true private
Definition at line 75 of file proficiency.h.
Referenced by is_teachable(), and load().
_time_to_learn
time_duration proficiency::_time_to_learn = 9999_hours private
Definition at line 86 of file proficiency.h.
Referenced by load(), and time_to_learn().
id
proficiency_id proficiency::id private
Definition at line 68 of file proficiency.h.
Referenced by prof_id().
src
std::vector<std::pair<proficiency_id, mod_id> > proficiency::src private
Definition at line 70 of file proficiency.h.
Referenced by load_proficiencies().
was_loaded
bool proficiency::was_loaded = false private
Definition at line 71 of file proficiency.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/proficiency.h
src/proficiency.cpp