Cataclysm DDA: wish_mutate_callback Class Reference
wish_mutate_callback Class Reference
Public Member Functions
nc_color mcolor (const trait_id &m)
wish_mutate_callback ()=default
bool key (const input_context &, const input_event &event, int entnum, uilist *menu) override
void refresh (uilist *menu) override
~wish_mutate_callback () override=default
Public Member Functions inherited from uilist_callback
virtual void select (uilist *)
After a new item is selected, call this once.
virtual ~uilist_callback ()=default
Public Attributes
int lastlen = 0
std::string msg
bool started = false
bool only_active = false
std::vector< trait_id > vTraits
std::map< trait_id, bool > pTraits
Character * you
Detailed Description
Definition at line 52 of file wish.cpp.
Constructor & Destructor Documentation
wish_mutate_callback()
wish_mutate_callback::wish_mutate_callback () default
~wish_mutate_callback()
wish_mutate_callback::~wish_mutate_callback () override default
Member Function Documentation
key()
bool wish_mutate_callback::key (const input_context & , const input_event & event, int entnum, uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 73 of file wish.cpp.
{
             if( event.get_first_input() == 't' && you->has_trait( vTraits[ entnum ] ) ) {
                 if( !you->has_base_trait( vTraits[ entnum ] ) ) {
                     you->unset_mutation( vTraits[ entnum ] );
                 }
                 you->toggle_trait( vTraits[ entnum ] );
                 you->set_mutation( vTraits[ entnum ] );
                 menu->entries[ entnum ].text_color = you->has_trait( vTraits[ entnum ] ) ? c_green :
                                                      menu->text_color;
                 menu->entries[ entnum ].extratxt.txt = you->has_base_trait( vTraits[ entnum ] ) ? "T" : "";
                 return true;
             } else if( event.get_first_input() == 'a' ) {
                 only_active = !only_active;
                 for( size_t i = 0; i < vTraits.size(); i++ ) {
                     if( !you->has_trait( vTraits[ i ] ) ) {
                         menu->entries[ i ].enabled = !only_active;
                     }
                 }
                 return true;
             }
             return false;
         }
References c_green, uilist::entries, input_event::get_first_input(), Character::has_base_trait(), Character::has_trait(), only_active, Character::set_mutation(), uilist::text_color, Character::toggle_trait(), Character::unset_mutation(), vTraits, and you.
mcolor()
nc_color wish_mutate_callback::mcolor (const trait_id & m) inline
Definition at line 65 of file wish.cpp.
{
             if( pTraits[ m ] ) {
                 return c_green;
             }
             return c_light_gray;
         }
References c_green, c_light_gray, and pTraits.
Referenced by refresh().
refresh()
void wish_mutate_callback::refresh (uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 100 of file wish.cpp.
{
             if( !started ) {
                 started = true;
                 for( const mutation_branch &traits_iter : mutation_branch::get_all() ) {
                     vTraits.push_back( traits_iter.id );
                     pTraits[traits_iter.id] = you->has_trait( traits_iter.id );
                 }
             }
             const std::string padding = std::string( menu->pad_right - 1, ' ' );
             const int startx = menu->w_width - menu->pad_right;
             for( int i = 2; i < lastlen; i++ ) {
                 mvwprintw( menu->window, point( startx, i ), padding );
             }
             int line2 = 4;
             if( menu->selected >= 0 && static_cast<size_t>( menu->selected ) < vTraits.size() ) {
                 const mutation_branch &mdata = vTraits[menu->selected].obj();
                 mvwprintw( menu->window, point( startx, 3 ),
                            mdata.valid ? _( "Valid" ) : _( "Nonvalid" ) );
                 line2++;
                 mvwprintz(
                     menu->window,
                     point( startx, line2 ),
                     c_light_gray,
                     _( "Id:" )
                 );
                 mvwprintw(
                     menu->window,
                     point( startx + 11, line2 ),
                     mdata.id.str()
                 );
                 if( !mdata.prereqs.empty() ) {
                     line2++;
                     mvwprintz( menu->window, point( startx, line2 ), c_light_gray, _( "Prereqs:" ) );
                     for( const trait_id &j : mdata.prereqs ) {
                         mvwprintz( menu->window, point( startx + 11, line2 ), mcolor( j ),
                                    j->name() );
                         line2++;
                     }
                 }
                 if( !mdata.prereqs2.empty() ) {
                     line2++;
                     mvwprintz( menu->window, point( startx, line2 ), c_light_gray, _( "Prereqs, 2d:" ) );
                     for( const trait_id &j : mdata.prereqs2 ) {
                         mvwprintz( menu->window, point( startx + 15, line2 ), mcolor( j ),
                                    j->name() );
                         line2++;
                     }
                 }
                 if( !mdata.threshreq.empty() ) {
                     line2++;
                     mvwprintz( menu->window, point( startx, line2 ), c_light_gray, _( "Thresholds required:" ) );
                     for( const trait_id &j : mdata.threshreq ) {
                         mvwprintz( menu->window, point( startx + 21, line2 ), mcolor( j ),
                                    j->name() );
                         line2++;
                     }
                 }
                 if( !mdata.cancels.empty() ) {
                     line2++;
                     mvwprintz( menu->window, point( startx, line2 ), c_light_gray, _( "Cancels:" ) );
                     for( const trait_id &j : mdata.cancels ) {
                         mvwprintz( menu->window, point( startx + 11, line2 ), mcolor( j ),
                                    j->name() );
                         line2++;
                     }
                 }
                 if( !mdata.replacements.empty() ) {
                     line2++;
                     mvwprintz( menu->window, point( startx, line2 ), c_light_gray, _( "Becomes:" ) );
                     for( const trait_id &j : mdata.replacements ) {
                         mvwprintz( menu->window, point( startx + 11, line2 ), mcolor( j ),
                                    j->name() );
                         line2++;
                     }
                 }
                 if( !mdata.additions.empty() ) {
                     line2++;
                     mvwprintz( menu->window, point( startx, line2 ), c_light_gray, _( "Add-ons:" ) );
                     for( const string_id<mutation_branch> &j : mdata.additions ) {
                         mvwprintz( menu->window, point( startx + 11, line2 ), mcolor( j ),
                                    j->name() );
                         line2++;
                     }
                 }
                 if( !mdata.types.empty() ) {
                     line2++;
                     mvwprintz( menu->window, point( startx, line2 ), c_light_gray,  _( "Type:" ) );
                     for( const std::string &j : mdata.types ) {
                         mvwprintw( menu->window, point( startx + 11, line2 ), j );
                         line2++;
                     }
                 }
                 if( !mdata.category.empty() ) {
                     line2++;
                     mvwprintz( menu->window, point( startx, line2 ), c_light_gray,  _( "Category:" ) );
                     for( const mutation_category_id &j : mdata.category ) {
                         mvwprintw( menu->window, point( startx + 11, line2 ), j.str() );
                         line2++;
                     }
                 }
                 line2 += 2;
                 //~ pts: points, vis: visibility, ugly: ugliness
                 mvwprintz( menu->window, point( startx, line2 ), c_light_gray, _( "pts: %d vis: %d ugly: %d" ),
                            mdata.points,
                            mdata.visibility,
                            mdata.ugliness
                          );
                 line2 += 2;
                 std::vector<std::string> desc = foldstring( mdata.desc(),
                                                 menu->pad_right - 1 );
                 for( auto &elem : desc ) {
                     mvwprintz( menu->window, point( startx, line2 ), c_light_gray, elem );
                     line2++;
                 }
             }
             lastlen = line2 + 1;
             mvwprintz( menu->window, point( startx, menu->w_height - 4 ), c_green, msg );
             msg.clear();
             input_context ctxt( menu->input_category, keyboard_mode::keycode );
             mvwprintw( menu->window, point( startx, menu->w_height - 3 ),
                        _( "[%s] find, [%s] quit, [t] toggle base trait" ),
                        ctxt.get_desc( "FILTER" ), ctxt.get_desc( "QUIT" ) );
             if( only_active ) {
                 mvwprintz( menu->window, point( startx, menu->w_height - 2 ), c_green,
                            _( "[a] show active traits (active)" ) );
             } else {
                 mvwprintz( menu->window, point( startx, menu->w_height - 2 ), c_white,
                            _( "[a] show active traits" ) );
             }
             wnoutrefresh( menu->window );
         }
References _, mutation_branch::additions, c_green, c_light_gray, c_white, mutation_branch::cancels, mutation_branch::category, mutation_branch::desc(), foldstring(), mutation_branch::get_all(), input_context::get_desc(), Character::has_trait(), mutation_branch::id, uilist::input_category, keycode, lastlen, mcolor(), msg, catacurses::mvwprintw(), mvwprintz(), mutation_branch::name(), only_active, uilist::pad_right, mutation_branch::points, mutation_branch::prereqs, mutation_branch::prereqs2, pTraits, mutation_branch::replacements, uilist::selected, started, string_id< T >::str(), mutation_branch::threshreq, mutation_branch::types, mutation_branch::ugliness, mutation_branch::valid, mutation_branch::visibility, vTraits, uilist::w_height, uilist::w_width, uilist::window, catacurses::wnoutrefresh(), and you.
Member Data Documentation
lastlen
int wish_mutate_callback::lastlen = 0
Definition at line 56 of file wish.cpp.
Referenced by refresh().
msg
std::string wish_mutate_callback::msg
Definition at line 58 of file wish.cpp.
Referenced by refresh(), and debug_menu::wishmutate().
only_active
bool wish_mutate_callback::only_active = false
Definition at line 60 of file wish.cpp.
Referenced by key(), refresh(), and debug_menu::wishmutate().
pTraits
std::map<trait_id, bool> wish_mutate_callback::pTraits
Definition at line 62 of file wish.cpp.
Referenced by mcolor(), refresh(), and debug_menu::wishmutate().
started
bool wish_mutate_callback::started = false
Definition at line 59 of file wish.cpp.
Referenced by refresh().
vTraits
std::vector<trait_id> wish_mutate_callback::vTraits
Definition at line 61 of file wish.cpp.
Referenced by key(), refresh(), and debug_menu::wishmutate().
you
Character* wish_mutate_callback::you
Definition at line 63 of file wish.cpp.
Referenced by key(), refresh(), and debug_menu::wishmutate().
The documentation for this class was generated from the following file:
src/wish.cpp