Cataclysm DDA: manualnoise_actor Class Reference
manualnoise_actor Class Reference
Makes noise of a given volume.
#include <iuse_actor.h>
Public Member Functions
manualnoise_actor (const std::string &type="manualnoise")
~manualnoise_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
ret_val< void > can_use (const Character &, const item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
translation use_message
translation noise_message = to_translation("hsss")
std::string noise_id
std::string noise_variant
int noise = 0
int moves = 0
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Makes noise of a given volume.
Definition at line 608 of file iuse_actor.h.
Constructor & Destructor Documentation
manualnoise_actor()
manualnoise_actor::manualnoise_actor (const std::string & type = "manualnoise") inline explicit
Definition at line 618 of file iuse_actor.h.
 : iuse_actor( type ) {}
~manualnoise_actor()
manualnoise_actor::~manualnoise_actor () override default
Member Function Documentation
can_use()
ret_val< void > manualnoise_actor::can_use (const Character & p, const item & it, const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 2065 of file iuse_actor.cpp.
 {
     if( !it.ammo_sufficient( &p ) ) {
         return ret_val<void>::make_failure( _( "This tool doesn't have enough charges." ) );
     }
     return ret_val<void>::make_success();
 }
References _, item::ammo_sufficient(), ret_val< T >::make_failure(), and ret_val< T >::make_success().
clone()
std::unique_ptr< iuse_actor > manualnoise_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2048 of file iuse_actor.cpp.
 {
     return std::make_unique<manualnoise_actor>( *this );
 }
load()
void manualnoise_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2038 of file iuse_actor.cpp.
 {
     obj.get_member( "use_message" ).read( use_message );
     obj.read( "noise_message", noise_message );
     noise_id            = obj.get_string( "noise_id", "misc" );
     noise_variant       = obj.get_string( "noise_variant", "default" );
     noise               = obj.get_int( "noise", 0 );
     moves               = obj.get_int( "moves", 0 );
 }
References JsonObject::get_int(), JsonObject::get_member(), JsonObject::get_string(), moves, noise, noise_id, noise_message, noise_variant, JsonValue::read(), JsonObject::read(), and use_message.
use()
std::optional< int > manualnoise_actor::use (Character * p, item & , const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 2053 of file iuse_actor.cpp.
 {
     // Uses the moves specified by iuse_actor's definition
     p->mod_moves( -moves );
     if( noise > 0 ) {
         sounds::sound( p->pos(), noise, sounds::sound_t::activity,
                        noise_message.empty() ? _( "Hsss" ) : noise_message.translated(), true, noise_id, noise_variant );
     }
     p->add_msg_if_player( "%s", use_message );
     return 1;
 }
References _, sounds::activity, Character::add_msg_if_player(), translation::empty(), Creature::mod_moves(), moves, noise, noise_id, noise_message, noise_variant, Creature::pos(), sounds::sound(), translation::translated(), and use_message.
Member Data Documentation
moves
int manualnoise_actor::moves = 0
Definition at line 616 of file iuse_actor.h.
Referenced by load(), and use().
noise
int manualnoise_actor::noise = 0
Definition at line 615 of file iuse_actor.h.
Referenced by load(), and use().
noise_id
std::string manualnoise_actor::noise_id
Definition at line 613 of file iuse_actor.h.
Referenced by load(), and use().
noise_message
translation manualnoise_actor::noise_message = to_translation("hsss")
Definition at line 612 of file iuse_actor.h.
Referenced by load(), and use().
noise_variant
std::string manualnoise_actor::noise_variant
Definition at line 614 of file iuse_actor.h.
Referenced by load(), and use().
use_message
translation manualnoise_actor::use_message
Definition at line 611 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp