Cataclysm DDA: debug_menu::mission_debug Class Reference
debug_menu::mission_debug Class Reference
Static Public Member Functions
static void edit_mission (mission &m)
static void edit (Character &who)
static void edit_player ()
static void edit_npc (npc &who)
static std::string describe (const mission &m)
Static Private Member Functions
static void remove_mission (mission &m)
Detailed Description
Definition at line 419 of file debug_menu.cpp.
Member Function Documentation
describe()
std::string debug_menu::mission_debug::describe (const mission & m) static
Definition at line 2437 of file debug_menu.cpp.
 {
     std::stringstream data;
     data << _( "Type:" ) << m.type->id.str();
     data << _( " Status:" ) << mission_status_string( m.status );
     data << _( " ID:" ) << m.uid;
     data << _( " NPC ID:" ) << m.npc_id;
     data << _( " Target:" ) << m.target.to_string();
     data << _( "Player ID:" ) << m.player_id;
     return data.str();
 }
References _, mission_type::id, debug_menu::mission_status_string(), mission::npc_id, mission::player_id, mission::status, string_id< T >::str(), mission::target, coords::coord_point_base< Point >::to_string(), mission::type, and mission::uid.
Referenced by edit_mission().
edit()
void debug_menu::mission_debug::edit (Character & who) static
Definition at line 2460 of file debug_menu.cpp.
 {
     if( who.is_avatar() ) {
         edit_player();
     } else if( who.is_npc() ) {
         edit_npc( dynamic_cast<npc &>( who ) );
     }
 }
References edit_npc(), edit_player(), Creature::is_avatar(), and Character::is_npc().
Referenced by debug_menu::character_edit_menu().
edit_mission()
void debug_menu::mission_debug::edit_mission (mission & m) static
Definition at line 2568 of file debug_menu.cpp.
 {
     uilist mmenu;
     mmenu.text = describe( m );
     enum {
         M_FAIL, M_SUCCEED, M_REMOVE
     };
     mmenu.addentry( M_FAIL, true, 'f', "%s", _( "Fail mission" ) );
     mmenu.addentry( M_SUCCEED, true, 'c', "%s", _( "Mark as complete" ) );
     mmenu.addentry( M_REMOVE, true, 'r', "%s", _( "Remove mission without proper cleanup" ) );
     mmenu.query();
     switch( mmenu.ret ) {
         case M_FAIL:
             m.fail();
             break;
         case M_SUCCEED:
             m.status = mission::mission_status::success;
             break;
         case M_REMOVE:
             remove_mission( m );
             break;
     }
 }
References _, uilist::addentry(), describe(), mission::fail(), uilist::query(), remove_mission(), uilist::ret, mission::status, mission::success, and uilist::text.
Referenced by edit_npc(), and edit_player().
edit_npc()
void debug_menu::mission_debug::edit_npc (npc & who) static
Definition at line 2469 of file debug_menu.cpp.
 {
     dialogue_chatbin &bin = who.chatbin;
     std::vector<mission *> all_missions;
     uilist mmenu;
     mmenu.text = _( "Select mission to edit" );
     add_header( mmenu, _( "Currently assigned missions:" ) );
     for( mission *m : bin.missions_assigned ) {
         mmenu.addentry( all_missions.size(), true, MENU_AUTOASSIGN, "%s", m->type->id.c_str() );
         all_missions.emplace_back( m );
     }
     add_header( mmenu, _( "Not assigned missions:" ) );
     for( mission *m : bin.missions ) {
         mmenu.addentry( all_missions.size(), true, MENU_AUTOASSIGN, "%s", m->type->id.c_str() );
         all_missions.emplace_back( m );
     }
     mmenu.query();
     if( mmenu.ret < 0 || mmenu.ret >= static_cast<int>( all_missions.size() ) ) {
         return;
     }
     edit_mission( *all_missions[mmenu.ret] );
 }
References _, debug_menu::add_header(), uilist::addentry(), string_id< T >::c_str(), npc::chatbin, edit_mission(), mission_type::id, MENU_AUTOASSIGN, dialogue_chatbin::missions, dialogue_chatbin::missions_assigned, uilist::query(), uilist::ret, uilist::text, and mission::type.
Referenced by edit().
edit_player()
void debug_menu::mission_debug::edit_player () static
Definition at line 2497 of file debug_menu.cpp.
 {
     std::vector<mission *> all_missions;
     uilist mmenu;
     mmenu.text = _( "Select mission to edit" );
     avatar &player_character = get_avatar();
     add_header( mmenu, _( "Active missions:" ) );
     for( mission *m : player_character.active_missions ) {
         mmenu.addentry( all_missions.size(), true, MENU_AUTOASSIGN, "%s", m->type->id.c_str() );
         all_missions.emplace_back( m );
     }
     add_header( mmenu, _( "Completed missions:" ) );
     for( mission *m : player_character.completed_missions ) {
         mmenu.addentry( all_missions.size(), true, MENU_AUTOASSIGN, "%s", m->type->id.c_str() );
         all_missions.emplace_back( m );
     }
     add_header( mmenu, _( "Failed missions:" ) );
     for( mission *m : player_character.failed_missions ) {
         mmenu.addentry( all_missions.size(), true, MENU_AUTOASSIGN, "%s", m->type->id.c_str() );
         all_missions.emplace_back( m );
     }
     mmenu.query();
     if( mmenu.ret < 0 || mmenu.ret >= static_cast<int>( all_missions.size() ) ) {
         return;
     }
     edit_mission( *all_missions[mmenu.ret] );
 }
References _, avatar::active_missions, debug_menu::add_header(), uilist::addentry(), string_id< T >::c_str(), avatar::completed_missions, edit_mission(), avatar::failed_missions, get_avatar(), mission_type::id, MENU_AUTOASSIGN, uilist::query(), uilist::ret, uilist::text, and mission::type.
Referenced by edit().
remove_mission()
void debug_menu::mission_debug::remove_mission (mission & m) static private
Definition at line 2539 of file debug_menu.cpp.
 {
     avatar &player_character = get_avatar();
     if( remove_from_vec( player_character.active_missions, &m ) ) {
         add_msg( _( "Removing from active_missions" ) );
     }
     if( remove_from_vec( player_character.completed_missions, &m ) ) {
         add_msg( _( "Removing from completed_missions" ) );
     }
     if( remove_from_vec( player_character.failed_missions, &m ) ) {
         add_msg( _( "Removing from failed_missions" ) );
     }
     if( player_character.active_mission == &m ) {
         player_character.active_mission = nullptr;
         add_msg( _( "Unsetting current objective" ) );
     }
     npc *giver = g->find_npc( m.npc_id );
     if( giver != nullptr ) {
         if( remove_from_vec( giver->chatbin.missions_assigned, &m ) ) {
             add_msg( _( "Removing from %s missions_assigned" ), giver->get_name() );
         }
         if( remove_from_vec( giver->chatbin.missions, &m ) ) {
             add_msg( _( "Removing from %s missions" ), giver->get_name() );
         }
     }
 }
References _, avatar::active_mission, avatar::active_missions, add_msg(), npc::chatbin, avatar::completed_missions, avatar::failed_missions, g, get_avatar(), Character::get_name(), dialogue_chatbin::missions, dialogue_chatbin::missions_assigned, mission::npc_id, and debug_menu::remove_from_vec().
Referenced by edit_mission().
The documentation for this class was generated from the following file:
src/debug_menu.cpp