Cataclysm DDA: mapgen_function_json_base Class Reference
mapgen_function_json_base Class Reference abstract
#include <mapgen.h>
Public Member Functions
void merge_non_nest_parameters_into (mapgen_parameters &, const std::string &outer_context) const
bool check_inbounds (const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const JsonObject &jso) const
size_t calc_index (const point &p) const
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &offset) const
void add_placement_coords_to (std::unordered_set< point > &) const
const mapgen_parameters & get_parameters () const
Protected Member Functions
mapgen_function_json_base (const JsonObject &jsobj, const std::string &context)
virtual ~mapgen_function_json_base ()
void setup_common ()
bool setup_common (const JsonObject &jo)
void setup_setmap (const JsonArray &parray)
virtual bool setup_internal (const JsonObject &jo)=0
virtual void setup_setmap_internal ()
void finalize_parameters_common ()
void check_common () const
mapgen_arguments get_args (const mapgendata &md, mapgen_parameter_scope) const
Protected Attributes
std::string context_
enum_bitset< jmapgen_flags > flags_
bool is_ready
point mapgensize
tripoint_rel_ms m_offset
point total_size
std::vector< jmapgen_setmap > setmap_points
jmapgen_objects objects
mapgen_parameters parameters
Private Attributes
JsonObject jsobj
Detailed Description
Definition at line 442 of file mapgen.h.
Constructor & Destructor Documentation
mapgen_function_json_base()
mapgen_function_json_base::mapgen_function_json_base (const JsonObject & jsobj, const std::string & context) protected
Definition at line 845 of file mapgen.cpp.
     : jsobj( jsobj )
     , context_( context )
     , is_ready( false )
     , mapgensize( SEEX * 2, SEEY * 2 )
     , total_size( mapgensize )
     , objects( m_offset, mapgensize, total_size )
 {
     this->jsobj.allow_omitted_members();
 }
References JsonObject::allow_omitted_members(), and context.
~mapgen_function_json_base()
mapgen_function_json_base::~mapgen_function_json_base () protected virtual default
Member Function Documentation
add_placement_coords_to()
void mapgen_function_json_base::add_placement_coords_to (std::unordered_set< point > & result) const
Definition at line 4762 of file mapgen.cpp.
 {
     objects.add_placement_coords_to( result );
 }
calc_index()
size_t mapgen_function_json_base::calc_index (const point & p) const
Definition at line 788 of file mapgen.cpp.
 {
     if( p.x >= mapgensize.x ) {
         debugmsg( "invalid value %zu for x in calc_index", p.x );
     }
     if( p.y >= mapgensize.y ) {
         debugmsg( "invalid value %zu for y in calc_index", p.y );
     }
     return p.y * mapgensize.y + p.x;
 }
References debugmsg, mapgensize, point::x, and point::y.
check_common()
void mapgen_function_json_base::check_common () const protected
Definition at line 4718 of file mapgen.cpp.
 {
     if( static_cast <int>( flags_.test( jmapgen_flags::allow_terrain_under_other_data ) ) +
         flags_.test( jmapgen_flags::dismantle_all_before_placing_terrain ) +
         flags_.test( jmapgen_flags::erase_all_before_placing_terrain ) > 1 ) {
         debugmsg( "In %s, the mutually exclusive flags ERASE_ALL_BEFORE_PLACING_TERRAIN, "
                   "DISMANTLE_ALL_BEFORE_PLACING_TERRAIN and ALLOW_TERRAIN_UNDER_OTHER_DATA "
                   "cannot be used together", context_ );
     }
     if( static_cast <int>( flags_.test( jmapgen_flags::allow_terrain_under_furniture ) ) +
         flags_.test( jmapgen_flags::dismantle_furniture_before_placing_terrain ) +
         flags_.test( jmapgen_flags::erase_furniture_before_placing_terrain ) > 1 ) {
         debugmsg( "In %s, the mutually exclusive flags ALLOW_TERRAIN_UNDER_FURNITURE, "
                   "DISMANTLE_FURNITURE_BEFORE_PLACING_TERRAIN and ERASE_FURNITURE_BEFORE_PLACING_TERRAIN "
                   "cannot be used together", context_ );
     }
     if( static_cast <int>( flags_.test( jmapgen_flags::allow_terrain_under_trap ) ) +
         flags_.test( jmapgen_flags::dismantle_trap_before_placing_terrain ) +
         flags_.test( jmapgen_flags::erase_trap_before_placing_terrain ) > 1 ) {
         debugmsg( "In %s, the mutually exclusive flags ALLOW_TERRAIN_UNDER_TRAP, "
                   "DISMANTLE_TRAP_BEFORE_PLACING_TERRAIN and ERASE_TRAP_BEFORE_PLACING_TERRAIN "
                   "cannot be used together", context_ );
     }
     if( static_cast <int>( flags_.test( jmapgen_flags::allow_terrain_under_items ) ) +
         flags_.test( jmapgen_flags::erase_items_before_placing_terrain ) > 1 ) {
         debugmsg( "In %s, the mutually exclusive flags "
                   "ALLOW_TERRAIN_UNDER_ITEMS and ERASE_ITEMS_BEFORE_PLACING_TERRAIN "
                   "cannot be used together", context_ );
     }
     for( const jmapgen_setmap &setmap : setmap_points ) {
         if( setmap.op != JMAPGEN_SETMAP_FURN &&
             setmap.op != JMAPGEN_SETMAP_LINE_FURN &&
             setmap.op != JMAPGEN_SETMAP_SQUARE_FURN ) {
             continue;
         }
         furn_id id( setmap.val.get() );
         if( check_furn( id, context_ ) ) {
             return;
         }
     }
     objects.check( context_, parameters );
 }
References allow_terrain_under_furniture, allow_terrain_under_items, allow_terrain_under_other_data, allow_terrain_under_trap, check_furn(), debugmsg, dismantle_all_before_placing_terrain, dismantle_furniture_before_placing_terrain, dismantle_trap_before_placing_terrain, erase_all_before_placing_terrain, erase_furniture_before_placing_terrain, erase_items_before_placing_terrain, erase_trap_before_placing_terrain, mapgen_palette::id, JMAPGEN_SETMAP_FURN, JMAPGEN_SETMAP_LINE_FURN, JMAPGEN_SETMAP_SQUARE_FURN, and mapgen_palette::parameters.
Referenced by update_mapgen_function_json::check().
check_inbounds()
bool mapgen_function_json_base::check_inbounds (const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const JsonObject & jso) const
Definition at line 838 of file mapgen.cpp.
 {
     return common_check_bounds( x, y, z, mapgensize, jso );
 }
References common_check_bounds(), and mapgensize.
Referenced by setup_setmap().
finalize_parameters_common()
void mapgen_function_json_base::finalize_parameters_common () protected
Definition at line 1082 of file mapgen.cpp.
 {
     objects.merge_parameters_into( parameters, context_ );
 }
References context_, jmapgen_objects::merge_parameters_into(), objects, and parameters.
get_args()
mapgen_arguments mapgen_function_json_base::get_args (const mapgendata & md, mapgen_parameter_scope scope) const protected
Definition at line 1087 of file mapgen.cpp.
 {
     return parameters.get_args( md, scope );
 }
References mapgen_parameters::get_args(), and parameters.
Referenced by update_mapgen_function_json::update_map().
get_parameters()
const mapgen_parameters& mapgen_function_json_base::get_parameters () const inline
Definition at line 454 of file mapgen.h.
{
             return parameters;
         }
References parameters.
Referenced by calculate_all_blueprint_reqs().
has_vehicle_collision()
bool mapgen_function_json_base::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & offset) const
Definition at line 5162 of file mapgen.cpp.
 {
     for( const jmapgen_setmap &elem : setmap_points ) {
         if( elem.has_vehicle_collision( dat, offset ) ) {
             return true;
         }
     }
     return objects.has_vehicle_collision( dat, offset );
 }
merge_non_nest_parameters_into()
void mapgen_function_json_base::merge_non_nest_parameters_into (mapgen_parameters & params, const std::string & outer_context) const
Definition at line 830 of file mapgen.cpp.
 {
     // NOLINTNEXTLINE(cata-translate-string-literal)
     const std::string context = string_format( "%s within %s", context_, outer_context );
     params.check_and_merge( parameters, context, mapgen_parameter_scope::nest );
 }
References mapgen_parameters::check_and_merge(), context, context_, nest, parameters, and string_format().
setup_common() [1/2]
void mapgen_function_json_base::setup_common () protected
Definition at line 4514 of file mapgen.cpp.
 {
     if( is_ready ) {
         return;
     }
     JsonObject jo = jsobj;
     mapgen_defer::defer = false;
     if( !setup_common( jo ) ) {
         jo.throw_error( "format: no terrain map" );
     }
     if( mapgen_defer::defer ) {
         mapgen_defer::jsi.throw_error_at( mapgen_defer::member, mapgen_defer::message );
     } else {
         mapgen_defer::jsi = JsonObject();
     }
 }
References mapgen_defer::defer, mapgen_defer::jsi, mapgen_defer::member, mapgen_defer::message, JsonObject::throw_error(), and JsonObject::throw_error_at().
Referenced by update_mapgen_function_json::setup_update().
setup_common() [2/2]
bool mapgen_function_json_base::setup_common (const JsonObject & jo) protected
Definition at line 4531 of file mapgen.cpp.
 {
     bool fallback_terrain_exists = setup_internal( jo );
     JsonArray parray;
     JsonArray sparray;
     JsonObject pjo;
     jo.read( "flags", flags_ );
     // mandatory: mapgensize rows of mapgensize character lines, each of which must have a
     // matching key in "terrain", unless fill_ter is set
     // "rows:" [ "aaaajustlikeinmapgen.cpp", "this.must!be!exactly.24!", "and_must_match_terrain_", .... ]
     point expected_dim = mapgensize + m_offset.xy().raw();
     cata_assert( expected_dim.x >= 0 );
     cata_assert( expected_dim.y >= 0 );
     const std::string default_row( expected_dim.x, ' ' );
     const bool default_rows = !jo.has_array( "rows" );
     if( !default_rows ) {
         parray = jo.get_array( "rows" );
         if( static_cast<int>( parray.size() ) < expected_dim.y ) {
             parray.throw_error( string_format( "format: rows: must have at least %d rows, not %d",
                                                expected_dim.y, parray.size() ) );
         }
         if( static_cast<int>( parray.size() ) != total_size.y ) {
             parray.throw_error(
                 string_format( "format: rows: must have %d rows, not %d; check mapgensize if applicable",
                                total_size.y, parray.size() ) );
         }
     }
     // just like mapf::basic_bind("stuff",blargle("foo", etc) ), only json input and faster when applying
     mapgen_palette palette = mapgen_palette::load_temp( jo, "dda", context_ );
     auto &keys_with_terrain = palette.keys_with_terrain;
     mapgen_palette::placing_map &format_placings = palette.format_placings;
     if( palette.keys_with_terrain.empty() && !fallback_terrain_exists ) {
         return false;
     }
     parameters = palette.get_parameters();
     for( int c = m_offset.y(); c < expected_dim.y; c++ ) {
         const std::string row = default_rows ? default_row : parray.get_string( c );
         static std::vector<std::string_view> row_keys;
         row_keys.clear();
         row_keys.reserve( total_size.x );
         utf8_display_split_into( row, row_keys );
         if( row_keys.size() < static_cast<size_t>( expected_dim.x ) ) {
             cata_assert( !default_rows );
             parray.throw_error(
                 string_format( "format: row %d must have at least %d columns, not %d",
                                c + 1, expected_dim.x, row_keys.size() ) );
         }
         if( row_keys.size() != static_cast<size_t>( total_size.x ) ) {
             cata_assert( !default_rows );
             parray.throw_error(
                 string_format( "format: row %d must have %d columns, not %d; check mapgensize if applicable",
                                c + 1, total_size.x, row_keys.size() ) );
         }
         for( int i = m_offset.x(); i < expected_dim.x; i++ ) {
             const tripoint_rel_ms p = tripoint_rel_ms( i, c, 0 ) - m_offset;
             const map_key key{ std::string( row_keys[i] ) };
             const auto iter_ter = keys_with_terrain.find( key );
             const auto fpi = format_placings.find( key );
             const bool has_terrain = iter_ter != keys_with_terrain.end();
             const bool has_placing = fpi != format_placings.end();
             if( !has_terrain && !fallback_terrain_exists ) {
                 cata_assert( !default_rows );
                 parray.string_error( c, i + 1,
                                      string_format( "format: rows: row %d column %d: '%s' is not in 'terrain',"
                                                     "and no 'fill_ter', 'predecessor_mapgen' or 'fallback_predecessor_mapgen' is set!",
                                                     c + 1, i + 1, key.str ) );
             }
             if( !has_terrain && !has_placing && key.str != " " && key.str != "." ) {
                 try {
                     cata_assert( !default_rows );
                     parray.string_error( c, i + 1,
                                          string_format( "format: rows: row %d column %d: '%s' has no terrain, furniture, or other definition",
                                                         c + 1, i + 1, key.str ) );
                 } catch( const JsonError &e ) {
                     debugmsg( "(json-error)\n%s", e.what() );
                 }
             }
             if( has_placing ) {
                 jmapgen_place where( p );
                 for( auto &what : fpi->second ) {
                     objects.add( where, what );
                 }
             }
         }
     }
     fallback_terrain_exists = true;
     // No fill_ter? No format? GTFO.
     if( !fallback_terrain_exists ) {
         jo.throw_error(
             "Need one of 'fill_terrain', 'predecessor_mapgen', 'fallback_predecessor_mapgen', 'terrain' or a palette providing 'terrain'." );
         // TODO: write TFM.
     }
     if( jo.has_array( "set" ) ) {
         setup_setmap( jo.get_array( "set" ) );
     }
     objects.load_objects<jmapgen_remove_all>( jo, "place_remove_all", context_ );
     // "add" is deprecated in favor of "place_item", but kept to support mods
     // which are not under our control.
     objects.load_objects<jmapgen_spawn_item>( jo, "add", context_ );
     objects.load_objects<jmapgen_spawn_item>( jo, "place_item", context_ );
     objects.load_objects<jmapgen_field>( jo, "place_fields", context_ );
     objects.load_objects<jmapgen_npc>( jo, "place_npcs", context_ );
     objects.load_objects<jmapgen_sign>( jo, "place_signs", context_ );
     objects.load_objects<jmapgen_vending_machine>( jo, "place_vendingmachines", context_ );
     objects.load_objects<jmapgen_toilet>( jo, "place_toilets", context_ );
     objects.load_objects<jmapgen_liquid_item>( jo, "place_liquids", context_ );
     objects.load_objects<jmapgen_corpse>( jo, "place_corpses", context_ );
     objects.load_objects<jmapgen_gaspump>( jo, "place_gaspumps", context_ );
     objects.load_objects<jmapgen_item_group>( jo, "place_items", context_ );
     objects.load_objects<jmapgen_loot>( jo, "place_loot", context_ );
     objects.load_objects<jmapgen_monster_group>( jo, "place_monsters", context_ );
     objects.load_objects<jmapgen_vehicle>( jo, "place_vehicles", context_ );
     objects.load_objects<jmapgen_remove_vehicles>( jo, "remove_vehicles", context_ );
     objects.load_objects<jmapgen_remove_npcs>( jo, "remove_npcs", context_ );
     objects.load_objects<jmapgen_trap>( jo, "place_traps", context_ );
     objects.load_objects<jmapgen_furniture>( jo, "place_furniture", context_ );
     objects.load_objects<jmapgen_terrain>( jo, "place_terrain", context_ );
     objects.load_objects<jmapgen_monster>( jo, "place_monster", context_ );
     objects.load_objects<jmapgen_make_rubble>( jo, "place_rubble", context_ );
     objects.load_objects<jmapgen_computer>( jo, "place_computers", context_ );
     objects.load_objects<jmapgen_nested>( jo, "place_nested", context_ );
     objects.load_objects<jmapgen_graffiti>( jo, "place_graffiti", context_ );
     objects.load_objects<jmapgen_zone>( jo, "place_zones", context_ );
     objects.load_objects<jmapgen_ter_furn_transform>( jo, "place_ter_furn_transforms", context_ );
     objects.load_objects<jmapgen_variable>( jo, "place_variables", context_ );
     // Needs to be last as it affects other placed items
     objects.load_objects<jmapgen_faction>( jo, "faction_owner", context_ );
     objects.finalize();
     std::stable_sort( setmap_points.begin(), setmap_points.end(), compare_phases );
     if( !mapgen_defer::defer ) {
         is_ready = true; // skip setup attempts from any additional pointers
     }
     return true;
 }
References c, cata_assert, compare_phases, debugmsg, mapgen_defer::defer, mapgen_palette::format_placings, JsonObject::get_array(), mapgen_palette::get_parameters(), JsonArray::get_string(), JsonObject::has_array(), mapgen_palette::keys_with_terrain, mapgen_palette::load_temp(), mapgen_palette::parameters, JsonObject::read(), JsonArray::size(), JsonArray::string_error(), string_format(), JsonObject::throw_error(), JsonArray::throw_error(), utf8_display_split_into(), point::x, and point::y.
setup_internal()
virtual bool mapgen_function_json_base::setup_internal (const JsonObject & jo) protected pure virtual
Implemented in mapgen_function_json_nested, mapgen_function_json, and update_mapgen_function_json.
setup_setmap()
void mapgen_function_json_base::setup_setmap (const JsonArray & parray) protected
Definition at line 956 of file mapgen.cpp.
 {
     std::string tmpval;
     std::map<std::string, jmapgen_setmap_op> setmap_opmap;
     setmap_opmap[ "terrain" ] = JMAPGEN_SETMAP_TER;
     setmap_opmap[ "furniture" ] = JMAPGEN_SETMAP_FURN;
     setmap_opmap[ "trap" ] = JMAPGEN_SETMAP_TRAP;
     setmap_opmap[ "trap_remove" ] = JMAPGEN_SETMAP_TRAP_REMOVE;
     setmap_opmap[ "creature_remove" ] = JMAPGEN_SETMAP_CREATURE_REMOVE;
     setmap_opmap[ "item_remove" ] = JMAPGEN_SETMAP_ITEM_REMOVE;
     setmap_opmap[ "field_remove" ] = JMAPGEN_SETMAP_FIELD_REMOVE;
     setmap_opmap[ "radiation" ] = JMAPGEN_SETMAP_RADIATION;
     setmap_opmap[ "bash" ] = JMAPGEN_SETMAP_BASH;
     setmap_opmap[ "variable" ] = JMAPGEN_SETMAP_VARIABLE;
     std::map<std::string, jmapgen_setmap_op>::iterator sm_it;
     jmapgen_setmap_op tmpop;
     int setmap_optype = 0;
     for( const JsonObject pjo : parray ) {
         if( pjo.read( "point", tmpval ) ) {
             setmap_optype = JMAPGEN_SETMAP_OPTYPE_POINT;
         } else if( pjo.read( "set", tmpval ) ) {
             setmap_optype = JMAPGEN_SETMAP_OPTYPE_POINT;
             debugmsg( "Warning, set: [ { \"set\":  } is deprecated, use set: [ { \"point\":  " );
         } else if( pjo.read( "line", tmpval ) ) {
             setmap_optype = JMAPGEN_SETMAP_OPTYPE_LINE;
         } else if( pjo.read( "square", tmpval ) ) {
             setmap_optype = JMAPGEN_SETMAP_OPTYPE_SQUARE;
         } else {
             pjo.throw_error( R"(invalid data: must contain "point", "set", "line" or "square" member)" );
         }
         sm_it = setmap_opmap.find( tmpval );
         if( sm_it == setmap_opmap.end() ) {
             pjo.throw_error( string_format( "invalid subfunction %s", tmpval.c_str() ) );
         }
         tmpop = sm_it->second;
         jmapgen_int tmp_x2( 0, 0 );
         jmapgen_int tmp_y2( 0, 0 );
         jmapgen_int tmp_i( 0, 0 );
         std::string string_val;
         int tmp_chance = 1;
         int tmp_rotation = 0;
         int tmp_fuel = -1;
         int tmp_status = -1;
         const jmapgen_int tmp_x( pjo, "x" );
         const jmapgen_int tmp_y( pjo, "y" );
         const jmapgen_int tmp_z( pjo, "z", 0, 0 );
         if( !check_inbounds( tmp_x, tmp_y, tmp_z, pjo ) ) {
             pjo.allow_omitted_members();
             continue;
         }
         if( setmap_optype != JMAPGEN_SETMAP_OPTYPE_POINT ) {
             tmp_x2 = jmapgen_int( pjo, "x2" );
             tmp_y2 = jmapgen_int( pjo, "y2" );
             if( !check_inbounds( tmp_x2, tmp_y2, tmp_z, pjo ) ) {
                 pjo.allow_omitted_members();
                 continue;
             }
         }
         if( tmpop == JMAPGEN_SETMAP_RADIATION ) {
             tmp_i = jmapgen_int( pjo, "amount" );
         } else if( tmpop == JMAPGEN_SETMAP_BASH || tmpop == JMAPGEN_SETMAP_ITEM_REMOVE ||
                    tmpop == JMAPGEN_SETMAP_FIELD_REMOVE || tmpop == JMAPGEN_SETMAP_CREATURE_REMOVE ) {
             //suppress warning
         } else if( tmpop == JMAPGEN_SETMAP_VARIABLE ) {
             string_val = pjo.get_string( "id" );
         } else {
             std::string tmpid = pjo.get_string( "id" );
             switch( tmpop ) {
                 case JMAPGEN_SETMAP_TER: {
                     const ter_str_id tid( tmpid );
                     if( !tid.is_valid() ) {
                         set_mapgen_defer( pjo, "id", "no such terrain" );
                         return;
                     }
                     tmp_i.val = tid.id().to_i();
                 }
                 break;
                 case JMAPGEN_SETMAP_FURN: {
                     const furn_str_id fid( tmpid );
                     if( !fid.is_valid() ) {
                         set_mapgen_defer( pjo, "id", "no such furniture" );
                         return;
                     }
                     tmp_i.val = fid.id().to_i();
                 }
                 break;
                 case JMAPGEN_SETMAP_TRAP_REMOVE:
                 case JMAPGEN_SETMAP_TRAP: {
                     const trap_str_id sid( tmpid );
                     if( !sid.is_valid() ) {
                         set_mapgen_defer( pjo, "id", "no such trap" );
                         return;
                     }
                     tmp_i.val = sid.id().to_i();
                 }
                 break;
                 default:
                     //Suppress warnings
                     break;
             }
             // TODO: ... support for random furniture? or not.
             tmp_i.valmax = tmp_i.val;
         }
         // TODO: sanity check?
         const jmapgen_int tmp_repeat = jmapgen_int( pjo, "repeat", 1, 1 );
         pjo.read( "chance", tmp_chance );
         pjo.read( "rotation", tmp_rotation );
         pjo.read( "fuel", tmp_fuel );
         pjo.read( "status", tmp_status );
         jmapgen_setmap tmp( tmp_x, tmp_y, tmp_z, tmp_x2, tmp_y2,
                             static_cast<jmapgen_setmap_op>( tmpop + setmap_optype ), tmp_i,
                             tmp_chance, tmp_repeat, tmp_rotation, tmp_fuel, tmp_status, string_val );
         setmap_points.push_back( tmp );
         tmpval.clear();
     }
 }
References check_inbounds(), debugmsg, string_id< T >::id(), string_id< T >::is_valid(), JMAPGEN_SETMAP_BASH, JMAPGEN_SETMAP_CREATURE_REMOVE, JMAPGEN_SETMAP_FIELD_REMOVE, JMAPGEN_SETMAP_FURN, JMAPGEN_SETMAP_ITEM_REMOVE, JMAPGEN_SETMAP_OPTYPE_LINE, JMAPGEN_SETMAP_OPTYPE_POINT, JMAPGEN_SETMAP_OPTYPE_SQUARE, JMAPGEN_SETMAP_RADIATION, JMAPGEN_SETMAP_TER, JMAPGEN_SETMAP_TRAP, JMAPGEN_SETMAP_TRAP_REMOVE, JMAPGEN_SETMAP_VARIABLE, set_mapgen_defer(), setmap_points, string_format(), int_id< T >::to_i(), jmapgen_int::val, and jmapgen_int::valmax.
setup_setmap_internal()
virtual void mapgen_function_json_base::setup_setmap_internal () inline protected virtual
Definition at line 469 of file mapgen.h.
 { }
Member Data Documentation
context_
std::string mapgen_function_json_base::context_ protected
Definition at line 476 of file mapgen.h.
Referenced by finalize_parameters_common(), merge_non_nest_parameters_into(), and update_mapgen_function_json::update_map().
flags_
enum_bitset<jmapgen_flags> mapgen_function_json_base::flags_ protected
Definition at line 477 of file mapgen.h.
Referenced by update_mapgen_function_json::update_map().
is_ready
bool mapgen_function_json_base::is_ready protected
Definition at line 478 of file mapgen.h.
jsobj
JsonObject mapgen_function_json_base::jsobj private
Definition at line 459 of file mapgen.h.
m_offset
tripoint_rel_ms mapgen_function_json_base::m_offset protected
Definition at line 481 of file mapgen.h.
Referenced by mapgen_function_json::mapgen_function_json().
mapgensize
point mapgen_function_json_base::mapgensize protected
Definition at line 480 of file mapgen.h.
Referenced by calc_index(), check_inbounds(), and mapgen_function_json::mapgen_function_json().
objects
jmapgen_objects mapgen_function_json_base::objects protected
Definition at line 485 of file mapgen.h.
Referenced by finalize_parameters_common(), mapgen_function_json::mapgen_function_json(), and update_mapgen_function_json::update_map().
parameters
mapgen_parameters mapgen_function_json_base::parameters protected
Definition at line 487 of file mapgen.h.
Referenced by finalize_parameters_common(), get_args(), get_parameters(), and merge_non_nest_parameters_into().
setmap_points
std::vector<jmapgen_setmap> mapgen_function_json_base::setmap_points protected
Definition at line 483 of file mapgen.h.
Referenced by setup_setmap(), and update_mapgen_function_json::update_map().
total_size
point mapgen_function_json_base::total_size protected
Definition at line 482 of file mapgen.h.
Referenced by mapgen_function_json::mapgen_function_json().
The documentation for this class was generated from the following files:
src/mapgen.h
src/mapgen.cpp