Cataclysm DDA: ter_furn_transform Class Reference
ter_furn_transform Class Reference
#include <magic_ter_furn_transform.h>
Public Member Functions
void transform (map &m, const tripoint_bub_ms &location) const
void load (const JsonObject &jo, std::string_view)
bool is_valid () const
Static Public Member Functions
static void reset ()
static void load_transform (const JsonObject &jo, const std::string &src)
static const std::vector< ter_furn_transform > & get_all ()
static void reset_all ()
Public Attributes
ter_furn_transform_id id
std::vector< std::pair< ter_furn_transform_id, mod_id > > src
bool was_loaded = false
Private Member Functions
std::optional< std::pair< ter_str_id, std::pair< translation, bool > > > next_ter (const ter_str_id &ter) const
std::optional< std::pair< ter_str_id, std::pair< translation, bool > > > next_ter (const std::string &flag) const
std::optional< std::pair< furn_str_id, std::pair< translation, bool > > > next_furn (const furn_str_id &furn) const
std::optional< std::pair< furn_str_id, std::pair< translation, bool > > > next_furn (const std::string &flag) const
std::optional< std::pair< trap_str_id, std::pair< translation, bool > > > next_trap (const trap_str_id &trap) const
std::optional< std::pair< trap_str_id, std::pair< translation, bool > > > next_trap (const std::string &flag) const
std::optional< std::pair< field_type_id, std::pair< translation, bool > > > next_field (const field_type_id &field) const
template<class T , class K >
std::optional< ter_furn_data< T > > find_transform (const std::map< K, ter_furn_data< T >> &list, const K &key) const
template<class T , class K >
std::optional< std::pair< T, std::pair< translation, bool > > > next (const std::map< K, ter_furn_data< T >> &list, const K &key) const
Private Attributes
std::map< ter_str_id, ter_furn_data< ter_str_id > > ter_transform
std::map< std::string, ter_furn_data< ter_str_id > > ter_flag_transform
std::map< furn_str_id, ter_furn_data< furn_str_id > > furn_transform
std::map< std::string, ter_furn_data< furn_str_id > > furn_flag_transform
std::map< trap_str_id, ter_furn_data< trap_str_id > > trap_transform
std::map< std::string, ter_furn_data< trap_str_id > > trap_flag_transform
std::map< field_type_id, ter_furn_data< field_type_id > > field_transform
Detailed Description
Definition at line 36 of file magic_ter_furn_transform.h.
Member Function Documentation
find_transform()
template<class T , class K > std::optional< ter_furn_data< T > > ter_furn_transform::find_transform (const std::map< K, ter_furn_data< T >> & list, const K & key) const private
Definition at line 150 of file magic_ter_fur_transform.cpp.
 {
     const auto result_iter = list.find( key );
     if( result_iter == list.cend() ) {
         return std::nullopt;
     }
     return result_iter->second;
 }
Referenced by next().
get_all()
const std::vector< ter_furn_transform > & ter_furn_transform::get_all () static
Definition at line 57 of file magic_ter_fur_transform.cpp.
 {
     return ter_furn_transform_factory.get_all();
 }
References anonymous_namespace{magic_ter_fur_transform.cpp}::ter_furn_transform_factory.
is_valid()
bool ter_furn_transform::is_valid () const
Definition at line 52 of file magic_ter_fur_transform.cpp.
 {
     return ter_furn_transform_factory.is_valid( this->id );
 }
References anonymous_namespace{magic_ter_fur_transform.cpp}::ter_furn_transform_factory.
load()
void ter_furn_transform::load (const JsonObject & jo, std::string_view)
Definition at line 86 of file magic_ter_fur_transform.cpp.
 {
     std::string input;
     mandatory( jo, was_loaded, "id", input );
     id = ter_furn_transform_id( input );
     if( jo.has_member( "terrain" ) ) {
         for( JsonObject ter_obj : jo.get_array( "terrain" ) ) {
             ter_furn_data<ter_str_id> cur_results = ter_furn_data<ter_str_id>();
             cur_results.load( ter_obj );
             for( const std::string valid_terrain : ter_obj.get_array( "valid_terrain" ) ) {
                 ter_transform.emplace( ter_str_id( valid_terrain ), cur_results );
             }
             for( const std::string valid_terrain : ter_obj.get_array( "valid_flags" ) ) {
                 ter_flag_transform.emplace( valid_terrain, cur_results );
             }
         }
     }
     if( jo.has_member( "furniture" ) ) {
         for( JsonObject furn_obj : jo.get_array( "furniture" ) ) {
             ter_furn_data<furn_str_id> cur_results = ter_furn_data<furn_str_id>();
             cur_results.load( furn_obj );
             for( const std::string valid_furn : furn_obj.get_array( "valid_furniture" ) ) {
                 furn_transform.emplace( furn_str_id( valid_furn ), cur_results );
             }
             for( const std::string valid_terrain : furn_obj.get_array( "valid_flags" ) ) {
                 furn_flag_transform.emplace( valid_terrain, cur_results );
             }
         }
     }
     if( jo.has_member( "field" ) ) {
         for( JsonObject field_obj : jo.get_array( "field" ) ) {
             ter_furn_data<field_type_id> cur_results = ter_furn_data<field_type_id>();
             cur_results.load( field_obj );
             for( const std::string valid_field : field_obj.get_array( "valid_field" ) ) {
                 field_transform.emplace( field_type_id( valid_field ), cur_results );
             }
         }
     }
     if( jo.has_member( "trap" ) ) {
         for( JsonObject trap_obj : jo.get_array( "trap" ) ) {
             ter_furn_data<trap_str_id> cur_results = ter_furn_data<trap_str_id>();
             cur_results.load( trap_obj );
             for( const std::string valid_trap : trap_obj.get_array( "valid_trap" ) ) {
                 trap_transform.emplace( trap_str_id( valid_trap ), cur_results );
             }
             for( const std::string valid_trap : trap_obj.get_array( "valid_flags" ) ) {
                 trap_flag_transform.emplace( valid_trap, cur_results );
             }
         }
     }
 }
References field_transform, field_type_id, furn_flag_transform, furn_str_id, furn_transform, JsonObject::get_array(), JsonObject::has_member(), ter_furn_data< T >::load(), mandatory, ter_flag_transform, ter_furn_transform_id, ter_str_id, ter_transform, trap_flag_transform, trap_str_id, trap_transform, and was_loaded.
load_transform()
void ter_furn_transform::load_transform (const JsonObject & jo, const std::string & src) static
Definition at line 42 of file magic_ter_fur_transform.cpp.
 {
     ter_furn_transform_factory.load( jo, src );
 }
References src, and anonymous_namespace{magic_ter_fur_transform.cpp}::ter_furn_transform_factory.
Referenced by DynamicDataLoader::initialize().
next()
template<class T , class K > std::optional< std::pair< T, std::pair< translation, bool > > > ter_furn_transform::next (const std::map< K, ter_furn_data< T >> & list, const K & key) const private
Definition at line 161 of file magic_ter_fur_transform.cpp.
 {
     const std::optional<ter_furn_data<T>> result = find_transform( list, key );
     if( result.has_value() ) {
         return std::make_pair( result.value().pick().value(), std::make_pair( result->message,
                                result->message_good ) );
     }
     return std::nullopt;
 }
References find_transform().
Referenced by next_field(), next_furn(), next_ter(), and next_trap().
next_field()
std::optional< std::pair< field_type_id, std::pair< translation, bool > > > ter_furn_transform::next_field (const field_type_id & field) const private
Definition at line 198 of file magic_ter_fur_transform.cpp.
 {
     return next( field_transform, field );
 }
References field_transform, and next().
Referenced by transform().
next_furn() [1/2]
std::optional< std::pair< furn_str_id, std::pair< translation, bool > > > ter_furn_transform::next_furn (const furn_str_id & furn) const private
Definition at line 185 of file magic_ter_fur_transform.cpp.
 {
     return next( furn_transform, furn );
 }
References furn_transform, and next().
Referenced by transform().
next_furn() [2/2]
std::optional< std::pair< furn_str_id, std::pair< translation, bool > > > ter_furn_transform::next_furn (const std::string & flag) const private
Definition at line 191 of file magic_ter_fur_transform.cpp.
 {
     return next( furn_flag_transform, flag );
 }
References furn_flag_transform, and next().
next_ter() [1/2]
std::optional< std::pair< ter_str_id, std::pair< translation, bool > > > ter_furn_transform::next_ter (const std::string & flag) const private
Definition at line 179 of file magic_ter_fur_transform.cpp.
 {
     return next( ter_flag_transform, flag );
 }
References next(), and ter_flag_transform.
next_ter() [2/2]
std::optional< std::pair< ter_str_id, std::pair< translation, bool > > > ter_furn_transform::next_ter (const ter_str_id & ter) const private
Definition at line 173 of file magic_ter_fur_transform.cpp.
 {
     return next( ter_transform, ter );
 }
References next(), and ter_transform.
Referenced by transform().
next_trap() [1/2]
std::optional< std::pair< trap_str_id, std::pair< translation, bool > > > ter_furn_transform::next_trap (const std::string & flag) const private
Definition at line 210 of file magic_ter_fur_transform.cpp.
 {
     return next( trap_flag_transform, flag );
 }
References next(), and trap_flag_transform.
next_trap() [2/2]
std::optional< std::pair< trap_str_id, std::pair< translation, bool > > > ter_furn_transform::next_trap (const trap_str_id & trap) const private
Definition at line 204 of file magic_ter_fur_transform.cpp.
 {
     return next( trap_transform, trap );
 }
References next(), and trap_transform.
Referenced by transform().
reset()
void ter_furn_transform::reset () static
Definition at line 73 of file magic_ter_fur_transform.cpp.
 {
     ter_furn_transform_factory.reset();
 }
References anonymous_namespace{magic_ter_fur_transform.cpp}::ter_furn_transform_factory.
Referenced by DynamicDataLoader::unload_data().
reset_all()
void ter_furn_transform::reset_all () static
Definition at line 47 of file magic_ter_fur_transform.cpp.
 {
     ter_furn_transform_factory.reset();
 }
References anonymous_namespace{magic_ter_fur_transform.cpp}::ter_furn_transform_factory.
transform()
void ter_furn_transform::transform (map & m, const tripoint_bub_ms & location) const
Definition at line 216 of file magic_ter_fur_transform.cpp.
 {
     avatar &you = get_avatar();
     const ter_id ter_at_loc = m.ter( location );
     std::optional<std::pair<ter_str_id, std::pair<translation, bool>>> ter_potential = next_ter(
                 ter_at_loc->id );
     const furn_id furn_at_loc = m.furn( location );
     std::optional<std::pair<furn_str_id, std::pair<translation, bool>>> furn_potential = next_furn(
                 furn_at_loc->id );
     const trap_str_id trap_at_loc = m.maptile_at( location ).get_trap().id();
     std::optional<std::pair<trap_str_id, std::pair<translation, bool>>> trap_potential = next_trap(
                 trap_at_loc );
     const field &field_at_loc = m.field_at( location );
     for( const auto &fld : field_at_loc ) {
         std::optional<std::pair<field_type_id, std::pair<translation, bool>>> field_potential = next_field(
                     fld.first );
         if( field_potential ) {
             m.add_field( location, field_potential->first, fld.second.get_field_intensity(),
                          fld.second.get_field_age(), true );
             m.remove_field( location, fld.first );
             if( you.sees( location ) && !field_potential->second.first.empty() ) {
                 you.add_msg_if_player( field_potential->second.first.translated(),
                                        field_potential->second.second ? m_good : m_bad );
             }
         }
     }
     if( !ter_potential ) {
         for( const std::pair<const std::string, ter_furn_data<ter_str_id>> &flag_result :
              ter_flag_transform )             {
             if( ter_at_loc->has_flag( flag_result.first ) ) {
                 ter_potential = next_ter( flag_result.first );
                 if( ter_potential ) {
                     break;
                 }
             }
         }
     }
     if( !furn_potential ) {
         for( const std::pair<const std::string, ter_furn_data<furn_str_id>> &flag_result :
              furn_flag_transform ) {
             if( furn_at_loc->has_flag( flag_result.first ) ) {
                 furn_potential = next_furn( flag_result.first );
                 if( furn_potential ) {
                     break;
                 }
             }
         }
     }
     if( !trap_potential ) {
         for( const std::pair<const std::string, ter_furn_data<trap_str_id>> &flag_result :
              trap_flag_transform ) {
             if( trap_at_loc->has_flag( flag_id( flag_result.first ) ) ) {
                 trap_potential = next_trap( flag_result.first );
                 if( trap_potential ) {
                     break;
                 }
             }
         }
     }
     if( ter_potential ) {
         m.ter_set( location, ter_potential->first );
         if( you.sees( location ) && !ter_potential->second.first.empty() ) {
             you.add_msg_if_player( ter_potential->second.first.translated(),
                                    ter_potential->second.second ? m_good : m_bad );
         }
     }
     if( furn_potential ) {
         m.furn_set( location, furn_potential->first );
         if( you.sees( location ) && !furn_potential->second.first.empty() ) {
             you.add_msg_if_player( furn_potential->second.first.translated(),
                                    furn_potential->second.second ? m_good : m_bad );
         }
     }
     if( trap_potential ) {
         m.trap_set( location, trap_potential->first );
         if( you.sees( location ) && !trap_potential->second.first.empty() ) {
             you.add_msg_if_player( trap_potential->second.first.translated(),
                                    trap_potential->second.second ? m_good : m_bad );
         }
     }
 }
References map::add_field(), Character::add_msg_if_player(), map::field_at(), map::furn(), furn_flag_transform, map::furn_set(), get_avatar(), maptile_impl< Submap >::get_trap(), trap::has_flag(), map_data_common_t::has_flag(), int_id< T >::id(), ter_t::id, furn_t::id, location, m_bad, m_good, map::maptile_at(), next_field(), next_furn(), next_ter(), next_trap(), map::remove_field(), Character::sees(), map::ter(), ter_flag_transform, map::ter_set(), trap_flag_transform, and map::trap_set().
Referenced by jmapgen_ter_furn_transform::apply().
Member Data Documentation
field_transform
std::map<field_type_id, ter_furn_data<field_type_id> > ter_furn_transform::field_transform private
Definition at line 48 of file magic_ter_furn_transform.h.
Referenced by load(), and next_field().
furn_flag_transform
std::map<std::string, ter_furn_data<furn_str_id> > ter_furn_transform::furn_flag_transform private
Definition at line 43 of file magic_ter_furn_transform.h.
Referenced by load(), next_furn(), and transform().
furn_transform
std::map<furn_str_id, ter_furn_data<furn_str_id> > ter_furn_transform::furn_transform private
Definition at line 42 of file magic_ter_furn_transform.h.
Referenced by load(), and next_furn().
id
ter_furn_transform_id ter_furn_transform::id
Definition at line 77 of file magic_ter_furn_transform.h.
src
std::vector<std::pair<ter_furn_transform_id, mod_id> > ter_furn_transform::src
Definition at line 78 of file magic_ter_furn_transform.h.
Referenced by load_transform().
ter_flag_transform
std::map<std::string, ter_furn_data<ter_str_id> > ter_furn_transform::ter_flag_transform private
Definition at line 40 of file magic_ter_furn_transform.h.
Referenced by load(), next_ter(), and transform().
ter_transform
std::map<ter_str_id, ter_furn_data<ter_str_id> > ter_furn_transform::ter_transform private
Definition at line 39 of file magic_ter_furn_transform.h.
Referenced by load(), and next_ter().
trap_flag_transform
std::map<std::string, ter_furn_data<trap_str_id> > ter_furn_transform::trap_flag_transform private
Definition at line 46 of file magic_ter_furn_transform.h.
Referenced by load(), next_trap(), and transform().
trap_transform
std::map<trap_str_id, ter_furn_data<trap_str_id> > ter_furn_transform::trap_transform private
Definition at line 45 of file magic_ter_furn_transform.h.
Referenced by load(), and next_trap().
was_loaded
bool ter_furn_transform::was_loaded = false
Definition at line 79 of file magic_ter_furn_transform.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/magic_ter_furn_transform.h
src/magic_ter_fur_transform.cpp