Cataclysm DDA: event_multiset Class Reference
event_multiset Class Reference
#include <stats_tracker.h>
Public Types
using summaries_type = std::unordered_map< cata::event::data_type, event_summary, cata::range_hash >
Public Member Functions
event_multiset ()
event_multiset (event_type type)
void set_type (event_type)
const summaries_type & counts () const
int count () const
int count (const cata::event::data_type &criteria) const
int total (const std::string &field) const
int total (const std::string &field, const cata::event::data_type &criteria) const
int minimum (const std::string &field) const
int maximum (const std::string &field) const
std::optional< summaries_type::value_type > first () const
std::optional< summaries_type::value_type > last () const
void add (const cata::event &)
void add (const summaries_type::value_type &)
void serialize (JsonOut &) const
void deserialize (const JsonObject &jo)
Private Attributes
event_type type_
summaries_type summaries_
Detailed Description
Definition at line 57 of file stats_tracker.h.
Member Typedef Documentation
summaries_type
using event_multiset::summaries_type = std::unordered_map<cata::event::data_type, event_summary, cata::range_hash>
Definition at line 60 of file stats_tracker.h.
Constructor & Destructor Documentation
event_multiset() [1/2]
event_multiset::event_multiset () inline
Definition at line 65 of file stats_tracker.h.
 : type_( event_type::num_event_types ) {}
event_multiset() [2/2]
event_multiset::event_multiset (event_type type) inline explicit
Definition at line 66 of file stats_tracker.h.
 : type_( type ) {}
Member Function Documentation
add() [1/2]
void event_multiset::add (const cata::event & e)
Definition at line 186 of file stats_tracker.cpp.
 {
     summaries_[e.data()].add( e );
 }
References cata::event::data(), and summaries_.
Referenced by event_transformation_impl::state::event_added(), event_transformation_impl::initialize(), and stats_tracker::notify().
add() [2/2]
void event_multiset::add (const summaries_type::value_type & e)
Definition at line 191 of file stats_tracker.cpp.
 {
     summaries_[e.first].add( e.second );
 }
References summaries_.
count() [1/2]
int event_multiset::count () const
Definition at line 86 of file stats_tracker.cpp.
 {
     int total = 0;
     for( const auto &pair : summaries_ ) {
         total += pair.second.count;
     }
     return total;
 }
References summaries_, and total().
Referenced by stats_tracker::deserialize(), event_statistic_count::state::events_reset(), event_statistic_unique_value::state::init(), event_statistic_first_value::state::init(), and event_statistic_count::value().
count() [2/2]
int event_multiset::count (const cata::event::data_type & criteria) const
Definition at line 95 of file stats_tracker.cpp.
 {
     int total = 0;
     for( const auto &pair : summaries_ ) {
         if( event_data_matches( pair.first, criteria ) ) {
             total += pair.second.count;
         }
     }
     return total;
 }
References event_data_matches(), summaries_, and total().
counts()
const summaries_type& event_multiset::counts () const inline
Definition at line 70 of file stats_tracker.h.
{
             return summaries_;
         }
References summaries_.
Referenced by event_transformation_impl::state::events_reset(), event_transformation_impl::initialize(), past_game_info::past_game_info(), and event_statistic_unique_value::value().
deserialize()
void event_multiset::deserialize (const JsonObject & jo)
Definition at line 4527 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     JsonArray events = jo.get_array( "event_counts" );
     if( !events.empty() && events.get_array( 0 ).has_int( 1 ) ) {
         // TEMPORARY until 0.F
         // Read legacy format with just ints
         std::vector<std::pair<cata::event::data_type, int>> copy;
         jo.read( "event_counts", copy );
         summaries_.clear();
         for( const std::pair<cata::event::data_type, int> &p : copy ) {
             event_summary summary{ p.second, calendar::start_of_game, calendar::start_of_game };
             summaries_.emplace( p.first, summary );
         }
     } else {
         // Read actual summaries
         std::vector<std::pair<cata::event::data_type, event_summary>> copy;
         jo.read( "event_counts", copy );
         summaries_ = { copy.begin(), copy.end() };
     }
 }
References JsonObject::allow_omitted_members(), JsonArray::empty(), JsonArray::get_array(), JsonObject::get_array(), JsonArray::has_int(), JsonObject::read(), and calendar::start_of_game.
first()
std::optional< event_multiset::summaries_type::value_type > event_multiset::first () const
Definition at line 166 of file stats_tracker.cpp.
 {
     auto minimum = std::min_element( summaries_.begin(), summaries_.end(),
                                      compare_times<&event_summary::first>() );
     if( minimum == summaries_.end() ) {
         return std::nullopt;
     }
     return *minimum;
 }
References minimum(), and summaries_.
Referenced by stats_tracker::deserialize(), event_transformation_impl::initialize(), and event_statistic_first_value::value().
last()
std::optional< event_multiset::summaries_type::value_type > event_multiset::last () const
Definition at line 176 of file stats_tracker.cpp.
 {
     auto minimum = std::max_element( summaries_.begin(), summaries_.end(),
                                      compare_times<&event_summary::last>() );
     if( minimum == summaries_.end() ) {
         return std::nullopt;
     }
     return *minimum;
 }
References minimum(), and summaries_.
Referenced by game::load(), and event_statistic_last_value::value().
maximum()
int event_multiset::maximum (const std::string & field) const
Definition at line 142 of file stats_tracker.cpp.
 {
     int maximum = 0;
     for( const auto &pair : summaries_ ) {
         auto it = pair.first.find( field );
         if( it == pair.first.end() ) {
             continue;
         }
         const int potential = it->second.get<cata_variant_type::int_>();
         if( potential > maximum ) {
             maximum = potential;
         }
     }
     return maximum;
 }
References int_, and summaries_.
Referenced by event_statistic_maximum::state::events_reset(), and event_statistic_maximum::value().
minimum()
int event_multiset::minimum (const std::string & field) const
Definition at line 126 of file stats_tracker.cpp.
 {
     int minimum = 0;
     for( const auto &pair : summaries_ ) {
         auto it = pair.first.find( field );
         if( it == pair.first.end() ) {
             continue;
         }
         const int potential = it->second.get<cata_variant_type::int_>();
         if( potential < minimum ) {
             minimum = potential;
         }
     }
     return minimum;
 }
References int_, and summaries_.
Referenced by event_statistic_minimum::state::events_reset(), first(), last(), and event_statistic_minimum::value().
serialize()
void event_multiset::serialize (JsonOut & jsout) const
Definition at line 4519 of file savegame_json.cpp.
 {
     jsout.start_object();
     std::vector<summaries_type::value_type> copy( summaries_.begin(), summaries_.end() );
     jsout.member( "event_counts", copy );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
set_type()
void event_multiset::set_type (event_type type)
Definition at line 79 of file stats_tracker.cpp.
 {
     // Used during stats_tracker deserialization to set the type
     cata_assert( type_ == event_type::num_event_types );
     type_ = type;
 }
References cata_assert, num_event_types, type, and type_.
total() [1/2]
int event_multiset::total (const std::string & field) const
Definition at line 106 of file stats_tracker.cpp.
 {
     return total( field, {} );
 }
Referenced by count(), event_statistic_total::state::events_reset(), total(), and event_statistic_total::value().
total() [2/2]
int event_multiset::total (const std::string & field, const cata::event::data_type & criteria) const
Definition at line 111 of file stats_tracker.cpp.
 {
     int total = 0;
     for( const auto &pair : summaries_ ) {
         auto it = pair.first.find( field );
         if( it == pair.first.end() ) {
             continue;
         }
         if( event_data_matches( pair.first, criteria ) ) {
             total += pair.second.count * it->second.get<cata_variant_type::int_>();
         }
     }
     return total;
 }
References event_data_matches(), int_, summaries_, and total().
Member Data Documentation
summaries_
summaries_type event_multiset::summaries_ private
Definition at line 104 of file stats_tracker.h.
Referenced by add(), count(), counts(), first(), last(), maximum(), minimum(), and total().
type_
event_type event_multiset::type_ private
Definition at line 103 of file stats_tracker.h.
Referenced by set_type().
The documentation for this class was generated from the following files:
src/stats_tracker.h
src/savegame_json.cpp
src/stats_tracker.cpp