Cataclysm DDA: map_cursor Class Reference
map_cursor Class Reference
#include <map_selector.h>
Public Member Functions
map_cursor (const tripoint &pos)
tripoint pos () const
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const override
Traverses this object and any child items contained using a visitor pattern.
std::list< item > remove_items_with (const std::function< bool(const item &)> &filter, int count=INT_MAX) override
Removes items contained by this instance which match the filter.
Public Member Functions inherited from visitable
item remove_item (item &it)
Removes and returns the item which must be contained by this instance.
Public Member Functions inherited from read_only_visitable
item * find_parent (const item &it) const
Determine the immediate parent container (if any) for an item.
std::vector< item * > parents (const item &it) const
Returns vector of parent containers (if any) starting with the innermost.
bool has_item (const item &it) const
Returns true if this visitable instance contains the item.
bool has_item_with (const std::function< bool(const item &)> &filter) const
Returns true if any item (including those within a container) matches the filter.
std::pair< int, int > kcal_range (const itype_id &id, const std::function< bool(const item &)> &filter, Character &player_character) const
bool has_amount (const itype_id &what, int qty, bool pseudo=true, const std::function< bool(const item &)> &filter=return_true< item >) const
Check instance provides at least qty of an item (.
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
Returns all items (including those within a container) matching the filter.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
virtual ~read_only_visitable ()=default
bool has_tools (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
bool has_components (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
virtual bool has_charges (const itype_id &it, int quantity, const std::function< bool(const item &)> &filter=return_true< item >) const
Private Attributes
tripoint pos_
Additional Inherited Members
Related Functions inherited from visitable
item * find_parent (const item &it) const
std::vector< item * > parents (const item &it) const
bool has_item (const item &it) const
bool has_item_with (const std::function< bool(const item &)> &filter) const
bool has_quality (const quality_id &qual, int level, int qty) const
Returns true if instance has amount (or more) items of at least quality level.
int max_quality (const quality_id &qual) const
Return maximum tool quality level provided by instance or INT_MIN if not found.
std::vector< const item * > items_with (const std::function< bool(const item &)> &filter) const
std::vector< item * > items_with (const std::function< bool(const item &)> &filter)
VisitResponse visit_items (const std::function< VisitResponse(item *, item *)> &func) const
Traverses this object and any child items contained using a visitor pattern.
std::list< item > remove_items_with (const std::function< bool(const item &e)> &filter, int count)
int charges_of (const itype_id &what, int limit, const std::function< bool(const item &)> &filter, const std::function< void(int)> &visitor, bool in_tools) const
Count maximum available charges from this instance and any contained items.
int amount_of (const itype_id &what, bool pseudo, int limit, const std::function< bool(const item &)> &filter) const
Count items matching id including both this instance and any contained items.
bool has_amount (const itype_id &what, int qty, bool pseudo, const std::function< bool(const item &)> &filter) const
Detailed Description
Definition at line 15 of file map_selector.h.
Constructor & Destructor Documentation
map_cursor()
map_cursor::map_cursor (const tripoint & pos) explicit
Definition at line 64 of file map_selector.cpp.
 : pos_( g ? get_map().getabs( pos ) : pos ) { }
Member Function Documentation
pos()
tripoint map_cursor::pos () const
Definition at line 66 of file map_selector.cpp.
 {
     return g ? get_map().getlocal( pos_ ) : pos_;
 }
References g, get_map(), map::getlocal(), and pos_.
Referenced by item_location::impl::item_on_map::describe(), item_location::impl::item_on_map::obtain_cost(), item_location::impl::item_on_map::position(), and item_location::impl::item_on_map::volume_capacity().
remove_items_with()
std::list<item> map_cursor::remove_items_with (const std::function< bool(const item &)> & filter, int count = INT_MAX) override virtual
Removes items contained by this instance which match the filter.
Note
: Implement for each class that will implement the visitable interface
if this instance itself is an item it will not be considered by the filter
Parameters
filter a UnaryPredicate which should return true if the item is to be removed
count maximum number of items to if unspecified unlimited. A count of zero is a no-op
Returns
any items removed (items counted by charges are not guaranteed to be stacked)
Implements visitable.
visit_items()
VisitResponse map_cursor::visit_items (const std::function< VisitResponse(item *, item *)> & func) const override virtual
Traverses this object and any child items contained using a visitor pattern.
Note
Implement for each class that will implement the visitable interface. Other visit_items variants rely on this function.
Parameters
func visitor function called for each node which controls whether traversal continues. The first argument is the node and the second is the parent node (if any) The visitor function should return VisitResponse::Next to recursively process child items, VisitResponse::Skip to ignore children of the current node or VisitResponse::Abort to skip all remaining nodes
Returns
This method itself only ever returns VisitResponse::Next or VisitResponse::Abort.
Implements read_only_visitable.
Member Data Documentation
pos_
tripoint map_cursor::pos_ private
Definition at line 18 of file map_selector.h.
Referenced by pos().
The documentation for this class was generated from the following files:
src/map_selector.h
src/map_selector.cpp