Cataclysm DDA: game::non_dead_range< T >::iterator Class Reference
game::non_dead_range< T >::iterator Class Reference
#include <game.h>
Public Member Functions
iterator (std::vector< weak_ptr_fast< T >> &i, const typename std::vector< weak_ptr_fast< T >>::iterator t)
iterator (const iterator &)=default
iterator & operator= (const iterator &)=default
bool operator== (const iterator &rhs) const
bool operator!= (const iterator &rhs) const
iterator & operator++ ()
T & operator* () const
Public Attributes
std::vector< weak_ptr_fast< T > > & items
std::vector< weak_ptr_fast< T > >::iterator iter
shared_ptr_fast< T > current
Private Member Functions
bool valid ()
bool valid ()
bool valid ()
bool valid ()
Detailed Description
template<typename T>
class game::non_dead_range< T >::iterator
Definition at line 397 of file game.h.
Constructor & Destructor Documentation
iterator() [1/2]
template<typename T > game::non_dead_range< T >::iterator::iterator (std::vector< weak_ptr_fast< T >> & i, const typename std::vector< weak_ptr_fast< T >>::iterator t) inline
Definition at line 406 of file game.h.
                                                                                          : items( i ), iter( t ) {
                             while( iter != items.end() && !valid() ) {
                                 ++iter;
                             }
                         }
References game::non_dead_range< T >::iterator::items, game::non_dead_range< T >::iterator::iter, and game::non_dead_range< T >::iterator::valid().
iterator() [2/2]
template<typename T > game::non_dead_range< T >::iterator::iterator (const iterator &) default
Member Function Documentation
operator!=()
template<typename T > bool game::non_dead_range< T >::iterator::operator!= (const iterator & rhs) const inline
Definition at line 418 of file game.h.
{
                             return !operator==( rhs );
                         }
References game::non_dead_range< T >::iterator::operator==().
operator*()
template<typename T > T& game::non_dead_range< T >::iterator::operator* () const inline
Definition at line 427 of file game.h.
{
                             return *current;
                         }
References game::non_dead_range< T >::iterator::current.
operator++()
template<typename T > iterator& game::non_dead_range< T >::iterator::operator++ () inline
Definition at line 421 of file game.h.
{
                             do {
                                 ++iter;
                             } while( iter != items.end() && !valid() );
                             return *this;
                         }
References game::non_dead_range< T >::iterator::items, game::non_dead_range< T >::iterator::iter, and game::non_dead_range< T >::iterator::valid().
operator=()
template<typename T > iterator& game::non_dead_range< T >::iterator::operator= (const iterator &) default
operator==()
template<typename T > bool game::non_dead_range< T >::iterator::operator== (const iterator & rhs) const inline
Definition at line 415 of file game.h.
{
                             return iter == rhs.iter;
                         }
References game::non_dead_range< T >::iterator::iter.
Referenced by game::non_dead_range< T >::iterator::operator!=().
valid() [1/4]
bool game::non_dead_range::iterator< monster >::valid () private
Definition at line 13170 of file game.cpp.
 {
     current = iter->lock();
     return current && !current->is_dead();
 }
valid() [2/4]
bool game::non_dead_range::iterator< npc >::valid () private
Definition at line 13177 of file game.cpp.
 {
     current = iter->lock();
     return current && !current->is_dead();
 }
valid() [3/4]
bool game::non_dead_range::iterator< Creature >::valid () private
Definition at line 13184 of file game.cpp.
 {
     current = iter->lock();
     // There is no Creature::is_dead function, so we can't write
     // return current && !current->is_dead();
     if( !current ) {
         return false;
     }
     const Creature *const critter = current.get();
     if( critter->is_monster() ) {
         return !static_cast<const monster *>( critter )->is_dead();
     }
     if( critter->is_npc() ) {
         return !static_cast<const npc *>( critter )->is_dead();
     }
     return true; // must be the avatar
 }
References Creature::is_monster(), and Creature::is_npc().
valid() [4/4]
template<typename T > bool game::non_dead_range< T >::iterator::valid () private
Referenced by game::non_dead_range< T >::iterator::iterator(), and game::non_dead_range< T >::iterator::operator++().
Member Data Documentation
current
template<typename T > shared_ptr_fast<T> game::non_dead_range< T >::iterator::current
Definition at line 404 of file game.h.
Referenced by game::non_dead_range< T >::iterator::operator*().
items
template<typename T > std::vector<weak_ptr_fast<T> >& game::non_dead_range< T >::iterator::items
Definition at line 402 of file game.h.
Referenced by game::non_dead_range< T >::iterator::iterator(), and game::non_dead_range< T >::iterator::operator++().
iter
template<typename T > std::vector<weak_ptr_fast<T> >::iterator game::non_dead_range< T >::iterator::iter
Definition at line 403 of file game.h.
Referenced by game::non_dead_range< T >::iterator::iterator(), game::non_dead_range< T >::iterator::operator++(), and game::non_dead_range< T >::iterator::operator==().
The documentation for this class was generated from the following file:
src/game.h