Cataclysm DDA: harvest_list Class Reference
harvest_list Class Reference
#include <harvest.h>
Public Member Functions
harvest_list ()
std::string message () const
bool is_null () const
const std::list< harvest_entry > & entries () const
bool empty () const
bool has_entry_type (const harvest_drop_type_id &type) const
const std::set< std::string > & names () const
Returns a set of cached, translated names of the items this harvest entry could produce.
const butchery_requirements & get_butchery_requirements () const
std::string describe (int at_skill=-1) const
std::list< harvest_entry >::const_iterator begin () const
std::list< harvest_entry >::const_iterator end () const
std::list< harvest_entry >::const_reverse_iterator rbegin () const
std::list< harvest_entry >::const_reverse_iterator rend () const
void load (const JsonObject &obj, std::string_view)
Static Public Member Functions
static void finalize_all ()
Fills out the set of cached names.
static void check_consistency ()
Check consistency of all loaded harvest data.
static void reset ()
Reset all loaded harvest data.
static void load_harvest_list (const JsonObject &jo, const std::string &src)
static const std::vector< harvest_list > & get_all ()
Public Attributes
itype_id leftovers = itype_id("ruined_chunks")
harvest_id id
std::vector< std::pair< harvest_id, mod_id > > src
bool was_loaded = false
Private Member Functions
void finalize ()
Private Attributes
std::list< harvest_entry > entries_
std::set< std::string > names_
translation message_
butchery_requirements_id butchery_requirements_
Detailed Description
Definition at line 95 of file harvest.h.
Constructor & Destructor Documentation
harvest_list()
harvest_list::harvest_list ()
Definition at line 79 of file harvest.cpp.
 : id( harvest_id::NULL_ID() ) {}
Member Function Documentation
begin()
std::list< harvest_entry >::const_iterator harvest_list::begin () const
Definition at line 233 of file harvest.cpp.
 {
     return entries().begin();
 }
References entries().
Referenced by describe().
check_consistency()
void harvest_list::check_consistency () static
Check consistency of all loaded harvest data.
Definition at line 193 of file harvest.cpp.
 {
     for( const harvest_list &hl : get_all() ) {
         const std::string hl_id = hl.id.c_str();
         auto error_func = [&]( const harvest_entry & entry ) {
             std::string errorlist;
             if( entry.type.is_null() ) {
                 // Type id is null
                 if( item::type_is_defined( itype_id( entry.drop ) ) ) {
                     return errorlist;
                 }
                 errorlist += "null type";
             } else if( !entry.type.is_valid() ) {
                 // Type id is invalid
                 errorlist += "invalid type \"" + entry.type.str() + "\"";
             } else if( ( entry.type->is_item_group() &&
                          !item_group::group_is_defined( item_group_id( entry.drop ) ) ) ||
                        ( !entry.type->is_item_group() && !item::type_is_defined( itype_id( entry.drop ) ) ) ) {
                 // Specified as item_group but no such group exists, or
                 // specified as single itype but no such itype exists
                 errorlist += entry.drop;
             }
             return errorlist;
         };
         const std::string errors = enumerate_as_string( hl.entries_.begin(), hl.entries_.end(),
                                    error_func );
         if( !errors.empty() ) {
             debugmsg( "Harvest list %s has invalid entry: %s", hl_id, errors );
         }
         if( !hl.leftovers.is_valid() ) {
             debugmsg( "Harvest id %s has invalid leftovers: %s", hl.id.c_str(), hl.leftovers.c_str() );
         }
     }
 }
References debugmsg, enumerate_as_string(), get_all(), item_group::group_is_defined(), itype_id, and item::type_is_defined().
Referenced by DynamicDataLoader::check_consistency().
describe()
std::string harvest_list::describe (int at_skill = -1) const
Definition at line 253 of file harvest.cpp.
 {
     if( empty() ) {
         return "";
     }
     return enumerate_as_string( entries().begin(), entries().end(),
     [at_skill]( const harvest_entry & en ) {
         float min_f = en.base_num.first;
         float max_f = en.base_num.second;
         if( at_skill >= 0 ) {
             min_f += en.scale_num.first * at_skill;
             max_f += en.scale_num.second * at_skill;
         } else {
             max_f = en.max;
         }
         // TODO: Avoid repetition here by making a common harvest drop function
         int max_drops = std::min<int>( en.max, std::round( std::max( 0.0f, max_f ) ) );
         int min_drops = std::max<int>( 0.0f, std::round( std::min( min_f, max_f ) ) );
         if( max_drops <= 0 ) {
             return std::string();
         }
         std::string ss;
         ss += "<bold>" + item::nname( itype_id( en.drop ), max_drops ) + "</bold>";
         // If the number is unspecified, just list the type
         if( max_drops >= 1000 && min_drops <= 0 ) {
             return ss;
         }
         ss += ": ";
         if( min_drops == max_drops ) {
             ss += string_format( "<stat>%d</stat>", min_drops );
         } else if( max_drops < 1000 ) {
             ss += string_format( "<stat>%d-%d</stat>", min_drops, max_drops );
         } else {
             ss += string_format( "<stat>%d+</stat>", min_drops );
         }
         return ss;
     } );
 }
References harvest_entry::base_num, begin(), harvest_entry::drop, empty(), end(), entries(), enumerate_as_string(), itype_id, harvest_entry::max, max(), min(), item::nname(), round(), harvest_entry::scale_num, and string_format().
empty()
bool harvest_list::empty () const inline
Definition at line 113 of file harvest.h.
{
             return entries().empty();
         }
References entries().
Referenced by describe(), map_data_common_t::extended_description(), iexamine::harvestable_now(), and map::is_harvestable().
end()
std::list< harvest_entry >::const_iterator harvest_list::end () const
Definition at line 238 of file harvest.cpp.
 {
     return entries().end();
 }
References entries().
Referenced by describe().
entries()
const std::list<harvest_entry>& harvest_list::entries () const inline
Definition at line 109 of file harvest.h.
{
             return entries_;
         }
References entries_.
Referenced by begin(), describe(), empty(), end(), has_entry_type(), rbegin(), and rend().
finalize()
void harvest_list::finalize () private
Definition at line 156 of file harvest.cpp.
 {
     std::transform( entries_.begin(), entries_.end(), std::inserter( names_, names_.begin() ),
     []( const harvest_entry & entry ) {
         return item::type_is_defined( itype_id( entry.drop ) ) ?
                item::nname( itype_id( entry.drop ) ) : "";
     } );
 }
References entries_, and names_.
Referenced by finalize_all().
finalize_all()
void harvest_list::finalize_all () static
Fills out the set of cached names.
Definition at line 165 of file harvest.cpp.
 {
     for( const harvest_list &pr : get_all() ) {
         const_cast<harvest_list &>( pr ).finalize();
     }
 }
References finalize(), and get_all().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< harvest_list > & harvest_list::get_all () static
Definition at line 188 of file harvest.cpp.
 {
     return harvest_list_factory.get_all();
 }
References anonymous_namespace{harvest.cpp}::harvest_list_factory.
Referenced by butchery_drops_harvest(), check_consistency(), and finalize_all().
get_butchery_requirements()
const butchery_requirements& harvest_list::get_butchery_requirements () const inline
Definition at line 127 of file harvest.h.
{
             return butchery_requirements_.obj();
         }
References butchery_requirements_, and string_id< T >::obj().
has_entry_type()
bool harvest_list::has_entry_type (const harvest_drop_type_id & type) const
Definition at line 91 of file harvest.cpp.
 {
     for( const harvest_entry &entry : entries() ) {
         if( entry.type == type ) {
             return true;
         }
     }
     return false;
 }
References entries(), and type.
Referenced by set_up_butchery().
is_null()
bool harvest_list::is_null () const
Definition at line 86 of file harvest.cpp.
 {
     return id == harvest_id::NULL_ID();
 }
References string_id< harvest_list >::NULL_ID().
Referenced by iexamine::harvestable_now().
load()
void harvest_list::load (const JsonObject & obj, std::string_view)
Definition at line 172 of file harvest.cpp.
 {
     mandatory( obj, was_loaded, "id", id );
     mandatory( obj, was_loaded, "entries", entries_ );
     optional( obj, was_loaded, "butchery_requirements", butchery_requirements_,
               butchery_requirements_default );
     optional( obj, was_loaded, "message", message_ );
     optional( obj, was_loaded, "leftovers", leftovers, itype_ruined_chunks );
 }
References butchery_requirements_, butchery_requirements_default, entries_, itype_ruined_chunks, leftovers, mandatory, message_, optional(), and was_loaded.
load_harvest_list()
void harvest_list::load_harvest_list (const JsonObject & jo, const std::string & src) static
Definition at line 183 of file harvest.cpp.
 {
     harvest_list_factory.load( jo, src );
 }
References anonymous_namespace{harvest.cpp}::harvest_list_factory, and src.
Referenced by DynamicDataLoader::initialize().
message()
std::string harvest_list::message () const
Definition at line 81 of file harvest.cpp.
 {
     return SNIPPET.expand( message_.translated() );
 }
References snippet_library::expand(), message_, SNIPPET, and translation::translated().
Referenced by butchery_drops_harvest().
names()
const std::set<std::string>& harvest_list::names () const inline
Returns a set of cached, translated names of the items this harvest entry could produce.
Filled in at finalization and not valid before that stage.
Definition at line 123 of file harvest.h.
{
             return names_;
         }
References names_.
Referenced by map_data_common_t::get_harvest_names().
rbegin()
std::list< harvest_entry >::const_reverse_iterator harvest_list::rbegin () const
Definition at line 243 of file harvest.cpp.
 {
     return entries().rbegin();
 }
References entries().
rend()
std::list< harvest_entry >::const_reverse_iterator harvest_list::rend () const
Definition at line 248 of file harvest.cpp.
 {
     return entries().rend();
 }
References entries().
reset()
void harvest_list::reset () static
Reset all loaded harvest data.
Definition at line 228 of file harvest.cpp.
 {
     harvest_list_factory.reset();
 }
References anonymous_namespace{harvest.cpp}::harvest_list_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
butchery_requirements_
butchery_requirements_id harvest_list::butchery_requirements_ private
Definition at line 155 of file harvest.h.
Referenced by get_butchery_requirements(), and load().
entries_
std::list<harvest_entry> harvest_list::entries_ private
Definition at line 152 of file harvest.h.
Referenced by entries(), finalize(), and load().
id
harvest_id harvest_list::id
Definition at line 102 of file harvest.h.
leftovers
itype_id harvest_list::leftovers = itype_id("ruined_chunks")
Definition at line 100 of file harvest.h.
Referenced by butchery_drops_harvest(), load(), and mdeath::splatter().
message_
translation harvest_list::message_ private
Definition at line 154 of file harvest.h.
Referenced by load(), and message().
names_
std::set<std::string> harvest_list::names_ private
Definition at line 153 of file harvest.h.
Referenced by finalize(), and names().
src
std::vector<std::pair<harvest_id, mod_id> > harvest_list::src
Definition at line 103 of file harvest.h.
Referenced by load_harvest_list().
was_loaded
bool harvest_list::was_loaded = false
Definition at line 146 of file harvest.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/harvest.h
src/harvest.cpp