Cataclysm DDA: memorized_tile Class Reference
memorized_tile Class Reference
#include <map_memory.h>
Public Member Functions
const std::string & get_ter_id () const
const std::string & get_dec_id () const
void set_ter_id (std::string_view id)
void set_dec_id (std::string_view id)
int get_ter_rotation () const
void set_ter_rotation (int rotation)
int get_dec_rotation () const
void set_dec_rotation (int rotation)
int get_ter_subtile () const
void set_ter_subtile (int subtile)
int get_dec_subtile () const
void set_dec_subtile (int subtile)
bool operator== (const memorized_tile &rhs) const
bool operator!= (const memorized_tile &rhs) const
Public Attributes
char32_t symbol = 0
Private Attributes
ter_str_id ter_id
std::string dec_id
int8_t ter_rotation = 0
int8_t dec_rotation = 0
int8_t ter_subtile = 0
int8_t dec_subtile = 0
Friends
struct mm_submap
Detailed Description
Definition at line 19 of file map_memory.h.
Member Function Documentation
get_dec_id()
const std::string & memorized_tile::get_dec_id () const
Definition at line 93 of file map_memory.cpp.
 {
     return dec_id;
 }
References dec_id.
Referenced by map_memory::clear_tile_decoration().
get_dec_rotation()
int memorized_tile::get_dec_rotation () const
Definition at line 123 of file map_memory.cpp.
 {
     return dec_rotation;
 }
References dec_rotation.
get_dec_subtile()
int memorized_tile::get_dec_subtile () const
Definition at line 153 of file map_memory.cpp.
 {
     return dec_subtile;
 }
References dec_subtile.
get_ter_id()
const std::string & memorized_tile::get_ter_id () const
Definition at line 88 of file map_memory.cpp.
 {
     return ter_id.str();
 }
get_ter_rotation()
int memorized_tile::get_ter_rotation () const
Definition at line 108 of file map_memory.cpp.
 {
     return ter_rotation;
 }
References ter_rotation.
get_ter_subtile()
int memorized_tile::get_ter_subtile () const
Definition at line 138 of file map_memory.cpp.
 {
     return ter_subtile;
 }
References ter_subtile.
operator!=()
bool memorized_tile::operator!= (const memorized_tile & rhs) const inline
Definition at line 40 of file map_memory.h.
{
             return !( *this == rhs );
         }
operator==()
bool memorized_tile::operator== (const memorized_tile & rhs) const
Definition at line 168 of file map_memory.cpp.
 {
     return symbol == rhs.symbol &&
            ter_rotation == rhs.ter_rotation &&
            dec_rotation == rhs.dec_rotation &&
            ter_subtile == rhs.ter_subtile &&
            dec_subtile == rhs.dec_subtile &&
            ter_id == rhs.ter_id &&
            dec_id == rhs.dec_id;
 }
References dec_id, dec_rotation, dec_subtile, symbol, ter_id, ter_rotation, and ter_subtile.
set_dec_id()
void memorized_tile::set_dec_id (std::string_view id)
Definition at line 103 of file map_memory.cpp.
 {
     dec_id = id;
 }
References dec_id, and base_camps::id.
Referenced by map_memory::clear_tile_decoration(), mm_submap::deserialize(), and map_memory::set_tile_decoration().
set_dec_rotation()
void memorized_tile::set_dec_rotation (int rotation)
Definition at line 128 of file map_memory.cpp.
 {
     if( rotation < std::numeric_limits<decltype( dec_rotation )>::min() ||
         rotation > std::numeric_limits<decltype( dec_rotation )>::max() ) {
         debugmsg( "map memory can't store rotation value %d", rotation );
         rotation = 0;
     }
     dec_rotation = rotation;
 }
References debugmsg, dec_rotation, max(), and min().
Referenced by map_memory::clear_tile_decoration(), mm_submap::deserialize(), and map_memory::set_tile_decoration().
set_dec_subtile()
void memorized_tile::set_dec_subtile (int subtile)
Definition at line 158 of file map_memory.cpp.
 {
     if( subtile < std::numeric_limits<decltype( dec_subtile )>::min() ||
         subtile > std::numeric_limits<decltype( dec_subtile )>::max() ) {
         debugmsg( "map memory can't store decoration subtile value %d", subtile );
         subtile = 0;
     }
     dec_subtile = subtile;
 }
References debugmsg, dec_subtile, max(), and min().
Referenced by map_memory::clear_tile_decoration(), mm_submap::deserialize(), and map_memory::set_tile_decoration().
set_ter_id()
void memorized_tile::set_ter_id (std::string_view id)
Definition at line 98 of file map_memory.cpp.
 {
     ter_id = ter_str_id( id );
 }
References ter_str_id.
Referenced by mm_submap::deserialize(), and map_memory::set_tile_terrain().
set_ter_rotation()
void memorized_tile::set_ter_rotation (int rotation)
Definition at line 113 of file map_memory.cpp.
 {
     if( rotation < std::numeric_limits<decltype( ter_rotation )>::min() ||
         rotation > std::numeric_limits<decltype( ter_rotation )>::max() ) {
         debugmsg( "map memory can't store rotation value %d", rotation );
         rotation = 0;
     }
     ter_rotation = rotation;
 }
References debugmsg, max(), min(), and ter_rotation.
Referenced by mm_submap::deserialize(), and map_memory::set_tile_terrain().
set_ter_subtile()
void memorized_tile::set_ter_subtile (int subtile)
Definition at line 143 of file map_memory.cpp.
 {
     if( subtile < std::numeric_limits<decltype( ter_subtile )>::min() ||
         subtile > std::numeric_limits<decltype( ter_subtile )>::max() ) {
         debugmsg( "map memory can't store terrain subtile value %d", subtile );
         subtile = 0;
     }
     ter_subtile = subtile;
 }
References debugmsg, max(), min(), and ter_subtile.
Referenced by mm_submap::deserialize(), and map_memory::set_tile_terrain().
Friends And Related Function Documentation
mm_submap
friend struct mm_submap friend
Definition at line 44 of file map_memory.h.
Member Data Documentation
dec_id
std::string memorized_tile::dec_id private
Definition at line 46 of file map_memory.h.
Referenced by mm_submap::deserialize(), get_dec_id(), operator==(), and set_dec_id().
dec_rotation
int8_t memorized_tile::dec_rotation = 0 private
Definition at line 48 of file map_memory.h.
Referenced by mm_submap::deserialize(), get_dec_rotation(), operator==(), and set_dec_rotation().
dec_subtile
int8_t memorized_tile::dec_subtile = 0 private
Definition at line 50 of file map_memory.h.
Referenced by mm_submap::deserialize(), get_dec_subtile(), operator==(), and set_dec_subtile().
symbol
char32_t memorized_tile::symbol = 0
Definition at line 22 of file map_memory.h.
Referenced by map_memory::clear_tile_decoration(), mm_submap::deserialize(), get_memory_at(), operator==(), and map_memory::set_tile_symbol().
ter_id
ter_str_id memorized_tile::ter_id private
Definition at line 45 of file map_memory.h.
Referenced by operator==().
ter_rotation
int8_t memorized_tile::ter_rotation = 0 private
Definition at line 47 of file map_memory.h.
Referenced by mm_submap::deserialize(), get_ter_rotation(), operator==(), and set_ter_rotation().
ter_subtile
int8_t memorized_tile::ter_subtile = 0 private
Definition at line 49 of file map_memory.h.
Referenced by mm_submap::deserialize(), get_ter_subtile(), operator==(), and set_ter_subtile().
The documentation for this class was generated from the following files:
src/map_memory.h
src/map_memory.cpp