Cataclysm DDA: delayed_transform_iuse Class Reference
delayed_transform_iuse Class Reference
This is a iuse_transform that uses the age of the item instead of a counter.
#include <iuse_actor.h>
Public Member Functions
int time_to_do (const item &it) const
How much longer (in turns) until the transformation can be done, can be negative.
delayed_transform_iuse (const std::string &type="delayed_transform")
~delayed_transform_iuse () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_transform
iuse_transform (const std::string &type="transform")
~iuse_transform () override=default
ret_val< void > can_use (const Character &, const item &, const tripoint &) const override
std::string get_name () const override
Returns the translated name of the action.
void finalize (const itype_id &my_item_type) override
Finalizes the actor.
void info (const item &, std::vector< iteminfo > &) const override
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_description () const
Returns the translated description of the action.
Public Attributes
int transform_age = 0
The minimal age of the item (in turns) to allow the transformation.
translation not_ready_msg
Message to display when the user activates the item before the age has been reached.
Public Attributes inherited from iuse_transform
translation msg_transform
displayed if player sees transformation with s replaced by item name
itype_id target
type of the resulting item
itype_id container
if set transform item to container and place new item (of type target) inside
std::string variant_type = "<any>"
if set choose this variant when transforming
bool sealed = true
whether the transformed container is sealed
int ammo_qty = -1
if zero or positive set remaining ammo of target to this (after transformation)
std::vector< int > random_ammo_qty
if this has values, set remaining ammo of target to one of them chosen at random (after transformation)
time_duration target_timer = 0_seconds
if positive set transformed item active and start countdown for countdown_action
itype_id ammo_type
if both this and ammo_qty are specified then set target to this specific ammo
bool active = false
used to set the active property of the transformed target
bool need_worn = false
does the item requires to be worn to be activable
bool need_wielding = false
does the item requires to be wielded to be activable
bool need_empty = false
does the item require being empty to be activable
int moves = 0
subtracted from Creature::moves when transformation is successful
int need_fire = 0
minimum number of fire charges required (if any) for transformation
translation need_fire_msg
displayed if item is in player possession with s replaced by item name
int need_charges = 0
minimum charges (if any) required for transformation
translation need_charges_msg
displayed if item is in player possession with s replaced by item name
std::map< quality_id, int > qualities_needed
Tool qualities needed, e.g.
translation menu_text
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
This is a iuse_transform that uses the age of the item instead of a counter.
The age is calculated from the current turn and the birthday of the item. The player has to activate the item manually, only when the specific age has been reached, it will transform.
Definition at line 282 of file iuse_actor.h.
Constructor & Destructor Documentation
delayed_transform_iuse()
delayed_transform_iuse::delayed_transform_iuse (const std::string & type = "delayed_transform") inline explicit
Definition at line 298 of file iuse_actor.h.
                                                                                        : iuse_transform(
                 type ) {}
~delayed_transform_iuse()
delayed_transform_iuse::~delayed_transform_iuse () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > delayed_transform_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Reimplemented from iuse_transform.
Definition at line 849 of file iuse_actor.cpp.
 {
     return std::make_unique<delayed_transform_iuse>( *this );
 }
load()
void delayed_transform_iuse::load (const JsonObject & obj) override virtual
Reimplemented from iuse_transform.
Definition at line 854 of file iuse_actor.cpp.
 {
     iuse_transform::load( obj );
     obj.get_member( "not_ready_msg" ).read( not_ready_msg );
     transform_age = obj.get_int( "transform_age" );
 }
References JsonObject::get_int(), JsonObject::get_member(), iuse_transform::load(), not_ready_msg, JsonValue::read(), and transform_age.
time_to_do()
int delayed_transform_iuse::time_to_do (const item & it) const
How much longer (in turns) until the transformation can be done, can be negative.
Definition at line 861 of file iuse_actor.cpp.
 {
     // TODO: change return type to time_duration
     return transform_age - to_turns<int>( it.age() );
 }
References item::age(), and transform_age.
Referenced by item::final_info(), and use().
use()
std::optional< int > delayed_transform_iuse::use (Character * p, item & it, const tripoint & pos) const override virtual
Reimplemented from iuse_transform.
Definition at line 867 of file iuse_actor.cpp.
 {
     if( time_to_do( it ) > 0 ) {
         p->add_msg_if_player( m_info, "%s", not_ready_msg );
         return std::nullopt;
     }
     return iuse_transform::use( p, it, pos );
 }
References Character::add_msg_if_player(), m_info, not_ready_msg, math_opers::pos(), time_to_do(), and iuse_transform::use().
Member Data Documentation
not_ready_msg
translation delayed_transform_iuse::not_ready_msg
Message to display when the user activates the item before the age has been reached.
Definition at line 293 of file iuse_actor.h.
Referenced by load(), and use().
transform_age
int delayed_transform_iuse::transform_age = 0
The minimal age of the item (in turns) to allow the transformation.
Definition at line 288 of file iuse_actor.h.
Referenced by load(), and time_to_do().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp