Cataclysm DDA: cast_spell_actor Class Reference
cast_spell_actor Class Reference
Cast a spell.
#include <iuse_actor.h>
Public Member Functions
cast_spell_actor (const std::string &type="cast_spell")
~cast_spell_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *p, item &it, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
void info (const item &, std::vector< iteminfo > &) const override
std::string get_name () const override
Returns the translated name of the action.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
bool no_fail = false
spell_id item_spell
int spell_level = 0
bool need_worn = false
does the item requires to be worn to be activable
bool need_wielding = false
does the item requires to be wielded to be activable
bool mundane = false
is the item mundane in nature
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Cast a spell.
The item's spell level is fixed, and the casting action uses up a charge from the item.
Definition at line 705 of file iuse_actor.h.
Constructor & Destructor Documentation
cast_spell_actor()
cast_spell_actor::cast_spell_actor (const std::string & type = "cast_spell") inline explicit
Definition at line 720 of file iuse_actor.h.
 : iuse_actor( type ) {}
~cast_spell_actor()
cast_spell_actor::~cast_spell_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > cast_spell_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2398 of file iuse_actor.cpp.
 {
     return std::make_unique<cast_spell_actor>( *this );
 }
get_name()
std::string cast_spell_actor::get_name () const override virtual
Returns the translated name of the action.
It is used for the item action menu.
Reimplemented from iuse_actor.
Definition at line 2430 of file iuse_actor.cpp.
 {
     return mundane ? _( "Activate" ) : _( "Cast spell" );
 }
References _, and mundane.
info()
void cast_spell_actor::info (const item & , std::vector< iteminfo > & dump) const override virtual
Reimplemented from iuse_actor.
Definition at line 2413 of file iuse_actor.cpp.
 {
     if( mundane ) {
         const std::string message = string_format( _( "This item when activated: %1$s" ),
                                     item_spell->description );
         dump.emplace_back( "DESCRIPTION", message );
     } else {
         //~ %1$s: spell name, %2$i: spell level
         const std::string message = string_format( _( "This item casts %1$s at level %2$i." ),
                                     item_spell->name, spell_level );
         dump.emplace_back( "DESCRIPTION", message );
         if( no_fail ) {
             dump.emplace_back( "DESCRIPTION", _( "This item never fails." ) );
         }
     }
 }
References _, spell_type::description, item_spell, mapgen_defer::message, mundane, spell_type::name, no_fail, spell_level, and string_format().
load()
void cast_spell_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2403 of file iuse_actor.cpp.
 {
     no_fail = obj.get_bool( "no_fail" );
     item_spell = spell_id( obj.get_string( "spell_id" ) );
     spell_level = obj.get_int( "level" );
     need_worn = obj.get_bool( "need_worn", false );
     need_wielding = obj.get_bool( "need_wielding", false );
     mundane = obj.get_bool( "mundane", false );
 }
References JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_string(), item_spell, mundane, need_wielding, need_worn, no_fail, spell_id, and spell_level.
use()
std::optional< int > cast_spell_actor::use (Character * p, item & it, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 2435 of file iuse_actor.cpp.
 {
     if( need_worn && !p->is_worn( it ) ) {
         p->add_msg_if_player( m_info, _( "You need to wear the %1$s before activating it." ), it.tname() );
         return std::nullopt;
     }
     if( need_wielding && !p->is_wielding( it ) ) {
         p->add_msg_if_player( m_info, _( "You need to wield the %1$s before activating it." ), it.tname() );
         return std::nullopt;
     }
     spell casting = spell( spell_id( item_spell ) );
     player_activity cast_spell( ACT_SPELLCASTING, casting.casting_time( *p ) );
     // [0] this is used as a spell level override for items casting spells
     cast_spell.values.emplace_back( spell_level );
     if( no_fail ) {
         // [1] if this value is 1, the spell never fails
         cast_spell.values.emplace_back( 1 );
     } else {
         // [1]
         cast_spell.values.emplace_back( 0 );
     }
     cast_spell.name = casting.id().c_str();
     if( it.has_flag( flag_USE_PLAYER_ENERGY ) ) {
         // [2] this value overrides the mana cost if set to 0
         cast_spell.values.emplace_back( 1 );
     } else {
         // [2]
         cast_spell.values.emplace_back( 0 );
     }
     p->assign_activity( cast_spell );
     p->activity.targets.emplace_back( *p, &it );
     // Actual handling of charges_to_use is in activity_handlers::spellcasting_finish
     return 0;
 }
References _, ACT_SPELLCASTING, Character::activity, Character::add_msg_if_player(), Character::assign_activity(), string_id< T >::c_str(), cast_spell(), spell::casting_time(), flag_USE_PLAYER_ENERGY, item::has_flag(), spell::id(), Character::is_wielding(), Character::is_worn(), item_spell, m_info, need_wielding, need_worn, no_fail, spell_id, spell_level, player_activity::targets, and item::tname().
Member Data Documentation
item_spell
spell_id cast_spell_actor::item_spell
Definition at line 711 of file iuse_actor.h.
Referenced by info(), load(), and use().
mundane
bool cast_spell_actor::mundane = false
is the item mundane in nature
Definition at line 718 of file iuse_actor.h.
Referenced by get_name(), info(), and load().
need_wielding
bool cast_spell_actor::need_wielding = false
does the item requires to be wielded to be activable
Definition at line 716 of file iuse_actor.h.
Referenced by load(), and use().
need_worn
bool cast_spell_actor::need_worn = false
does the item requires to be worn to be activable
Definition at line 714 of file iuse_actor.h.
Referenced by load(), and use().
no_fail
bool cast_spell_actor::no_fail = false
Definition at line 709 of file iuse_actor.h.
Referenced by info(), load(), and use().
spell_level
int cast_spell_actor::spell_level = 0
Definition at line 712 of file iuse_actor.h.
Referenced by info(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp