Cataclysm DDA: jmapgen_alternatively< PieceType > Class Template Reference
jmapgen_alternatively< PieceType > Class Template Reference
This is a generic mapgen piece, the template parameter PieceType should be another specific type of jmapgen_piece.
Public Member Functions
jmapgen_alternatively ()=default
mapgen_phase phase () const override
void check (const std::string &context, const mapgen_parameters &params, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z) const override
Sanity-check this piece.
void merge_parameters_into (mapgen_parameters &params, const std::string &outer_context) const override
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &context) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual ~jmapgen_piece ()=default
Public Attributes
std::vector< PieceType > alternatives
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
template<typename PieceType>
class jmapgen_alternatively< PieceType >
This is a generic mapgen piece, the template parameter PieceType should be another specific type of jmapgen_piece.
This class contains a vector of those objects and will chose one of it at random.
Definition at line 1744 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_alternatively()
template<typename PieceType > jmapgen_alternatively< PieceType >::jmapgen_alternatively () default
Member Function Documentation
apply()
template<typename PieceType > void jmapgen_alternatively< PieceType >::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1772 of file mapgen.cpp.
{
             if( const auto chosen = random_entry_opt( alternatives ) ) {
                 chosen->get().apply( dat, x, y, z, context );
             }
         }
References jmapgen_alternatively< PieceType >::alternatives, context, and random_entry_opt().
check()
template<typename PieceType > void jmapgen_alternatively< PieceType >::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 1757 of file mapgen.cpp.
{
             if( alternatives.empty() ) {
                 debugmsg( "zero alternatives in jmapgen_alternatively in %s", context );
             }
             for( const PieceType &piece : alternatives ) {
                 piece.check( context, params, x, y, z );
             }
         }
References jmapgen_alternatively< PieceType >::alternatives, context, and debugmsg.
has_vehicle_collision()
template<typename PieceType > bool jmapgen_alternatively< PieceType >::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 1778 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, tripoint, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
merge_parameters_into()
template<typename PieceType > void jmapgen_alternatively< PieceType >::merge_parameters_into (mapgen_parameters & params, const std::string & outer_context) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 1766 of file mapgen.cpp.
{
             for( const PieceType &piece : alternatives ) {
                 piece.merge_parameters_into( params, outer_context );
             }
         }
References jmapgen_alternatively< PieceType >::alternatives.
phase()
template<typename PieceType > mapgen_phase jmapgen_alternatively< PieceType >::phase () const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 1751 of file mapgen.cpp.
{
             if( alternatives.empty() ) {
                 return mapgen_phase::default_;
             }
             return alternatives[0].phase();
         }
References jmapgen_alternatively< PieceType >::alternatives, and default_.
Member Data Documentation
alternatives
template<typename PieceType > std::vector<PieceType> jmapgen_alternatively< PieceType >::alternatives
Definition at line 1749 of file mapgen.cpp.
Referenced by jmapgen_alternatively< PieceType >::apply(), jmapgen_alternatively< PieceType >::check(), jmapgen_alternatively< PieceType >::merge_parameters_into(), and jmapgen_alternatively< PieceType >::phase().
The documentation for this class was generated from the following file:
src/mapgen.cpp