Cataclysm DDA: mapgen_function_json Class Reference
mapgen_function_json Class Reference
#include <mapgen.h>
Public Member Functions
void setup () override
void finalize_parameters () override
void check () const override
void check_consistent_with (const oter_t &) const override
bool expects_predecessor () const override
void generate (mapgendata &) override
mapgen_parameters get_mapgen_params (mapgen_parameter_scope) const override
mapgen_function_json (const JsonObject &jsobj, dbl_or_var w, const std::string &context, const point &grid_offset, const point &grid_total)
~mapgen_function_json () override=default
Public Member Functions inherited from mapgen_function_json_base
void merge_non_nest_parameters_into (mapgen_parameters &, const std::string &outer_context) const
bool check_inbounds (const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const JsonObject &jso) const
size_t calc_index (const point &p) const
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &offset) const
void add_placement_coords_to (std::unordered_set< point > &) const
const mapgen_parameters & get_parameters () const
Public Member Functions inherited from mapgen_function
virtual ~mapgen_function ()=default
Public Attributes
ter_id fill_ter
oter_id predecessor_mapgen
Public Attributes inherited from mapgen_function
dbl_or_var weight
Protected Member Functions
bool setup_internal (const JsonObject &jo) override
Protected Member Functions inherited from mapgen_function_json_base
mapgen_function_json_base (const JsonObject &jsobj, const std::string &context)
virtual ~mapgen_function_json_base ()
void setup_common ()
bool setup_common (const JsonObject &jo)
void setup_setmap (const JsonArray &parray)
virtual void setup_setmap_internal ()
void finalize_parameters_common ()
void check_common () const
mapgen_arguments get_args (const mapgendata &md, mapgen_parameter_scope) const
Protected Member Functions inherited from mapgen_function
mapgen_function (dbl_or_var w)
mapgen_function (int w)
Private Attributes
jmapgen_int rotation
oter_str_id fallback_predecessor_mapgen_
Additional Inherited Members
Protected Attributes inherited from mapgen_function_json_base
std::string context_
enum_bitset< jmapgen_flags > flags_
bool is_ready
point mapgensize
tripoint_rel_ms m_offset
point total_size
std::vector< jmapgen_setmap > setmap_points
jmapgen_objects objects
mapgen_parameters parameters
Detailed Description
Definition at line 490 of file mapgen.h.
Constructor & Destructor Documentation
mapgen_function_json()
mapgen_function_json::mapgen_function_json (const JsonObject & jsobj, dbl_or_var w, const std::string & context, const point & grid_offset, const point & grid_total)
Definition at line 859 of file mapgen.cpp.
     : mapgen_function( std::move( w ) )
     , mapgen_function_json_base( jsobj, context )
     , fill_ter( t_null )
     , rotation( 0 )
     , fallback_predecessor_mapgen_( oter_str_id::NULL_ID() )
 {
     m_offset.x() = grid_offset.x * mapgensize.x;
     m_offset.y() = grid_offset.y * mapgensize.y;
     m_offset.z() = 0;
     total_size.x = grid_total.x * mapgensize.x;
     total_size.y = grid_total.y * mapgensize.y;
     objects = jmapgen_objects( m_offset, mapgensize, total_size );
 }
References context, mapgen_function_json_base::m_offset, mapgen_function_json_base::mapgensize, mapgen_function_json_base::objects, mapgen_function_json_base::total_size, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), point::x, coords::coord_point_mut< Point, Subpoint, InBounds >::y(), point::y, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
~mapgen_function_json()
mapgen_function_json::~mapgen_function_json () override default
Member Function Documentation
check()
void mapgen_function_json::check () const override virtual
Reimplemented from mapgen_function.
Definition at line 4680 of file mapgen.cpp.
 {
     check_common();
     if( predecessor_mapgen != oter_str_id::NULL_ID() && expects_predecessor() ) {
         debugmsg( "%s uses both predecessor_mapgen and expects_predecessor; these features are "
                   "incompatible", context_ );
     }
 }
References debugmsg, and string_id< oter_t >::NULL_ID().
check_consistent_with()
void mapgen_function_json::check_consistent_with (const oter_t & ter) const override virtual
Reimplemented from mapgen_function.
Definition at line 4690 of file mapgen.cpp.
 {
     bool requires_predecessor = ter.has_flag( oter_flags::requires_predecessor );
     if( expects_predecessor() && !requires_predecessor ) {
         debugmsg( "mapgen for oter_t %s expects a predecessor terrain but oter_type_t %s lacks the "
                   "REQUIRES_PREDECESSOR flag", ter.id.str(), ter.get_type_id().str() );
     }
 }
References debugmsg, oter_t::get_type_id(), oter_t::has_flag(), oter_t::id, requires_predecessor, and string_id< T >::str().
expects_predecessor()
bool mapgen_function_json::expects_predecessor () const override virtual
Reimplemented from mapgen_function.
Definition at line 5272 of file mapgen.cpp.
 {
     return fallback_predecessor_mapgen_ != oter_str_id::NULL_ID();
 }
References string_id< oter_t >::NULL_ID().
finalize_parameters()
void mapgen_function_json::finalize_parameters () override virtual
Reimplemented from mapgen_function.
Definition at line 4474 of file mapgen.cpp.
 {
     finalize_parameters_common();
 }
generate()
void mapgen_function_json::generate (mapgendata & md) override virtual
Implements mapgen_function.
Definition at line 5214 of file mapgen.cpp.
 {
     map *const m = &md.m;
     if( fill_ter != t_null ) {
         m->draw_fill_background( fill_ter );
     }
     const oter_t &ter = *md.terrain_type();
     auto do_predecessor_mapgen = [&]( mapgendata & predecessor_md ) {
         const std::string function_key = predecessor_md.terrain_type()->get_mapgen_id();
         bool success = run_mapgen_func( function_key, predecessor_md );
         if( !success ) {
             debugmsg( "predecessor mapgen with key %s failed", function_key );
         }
         // Now we have to do some rotation shenanigans. We need to ensure that
         // our predecessor is not rotated out of alignment as part of rotating this location,
         // and there are actually two sources of rotation--the mapgen can rotate explicitly, and
         // the entire overmap terrain may be rotatable. To ensure we end up in the right rotation,
         // we basically have to initially reverse the rotation that we WILL do in the future so that
         // when we apply that rotation, our predecessor is back in its original state while this
         // location is rotated as desired.
         m->rotate( ( -rotation.get() + 4 ) % 4 );
         if( ter.is_rotatable() || ter.is_linear() ) {
             m->rotate( ( -ter.get_rotation() + 4 ) % 4 );
         }
     };
     if( predecessor_mapgen != oter_str_id::NULL_ID() ) {
         mapgendata predecessor_md( md, predecessor_mapgen );
         do_predecessor_mapgen( predecessor_md );
     } else if( expects_predecessor() ) {
         if( md.has_predecessor() ) {
             mapgendata predecessor_md( md, md.last_predecessor() );
             predecessor_md.pop_last_predecessor();
             do_predecessor_mapgen( predecessor_md );
         } else {
             mapgendata predecessor_md( md, fallback_predecessor_mapgen_ );
             do_predecessor_mapgen( predecessor_md );
         }
     }
     mapgendata md_with_params( md, get_args( md, mapgen_parameter_scope::omt ), flags_ );
     apply_mapgen_in_phases( md_with_params, setmap_points, objects, tripoint_rel_ms( tripoint_zero ),
                             context_ );
     m->rotate( rotation.get() );
     if( ter.is_rotatable() || ter.is_linear() ) {
         m->rotate( ter.get_rotation() );
     }
     set_queued_points();
 }
References apply_mapgen_in_phases(), debugmsg, map::draw_fill_background(), oter_t::get_mapgen_id(), oter_t::get_rotation(), mapgendata::has_predecessor(), oter_t::is_linear(), oter_t::is_rotatable(), mapgendata::last_predecessor(), mapgendata::m, string_id< oter_t >::NULL_ID(), omt, mapgendata::pop_last_predecessor(), map::rotate(), run_mapgen_func(), set_queued_points(), t_null, mapgendata::terrain_type(), and tripoint_zero.
get_mapgen_params()
mapgen_parameters mapgen_function_json::get_mapgen_params (mapgen_parameter_scope scope) const override virtual
Reimplemented from mapgen_function.
Definition at line 5277 of file mapgen.cpp.
 {
     return parameters.params_for_scope( scope );
 }
References mapgen_palette::parameters, and mapgen_parameters::params_for_scope().
setup()
void mapgen_function_json::setup () override virtual
Reimplemented from mapgen_function.
Definition at line 4459 of file mapgen.cpp.
 {
     setup_common();
 }
setup_internal()
bool mapgen_function_json::setup_internal (const JsonObject & jo) override protected virtual
Implements mapgen_function_json_base.
Definition at line 4408 of file mapgen.cpp.
 {
     // Just to make sure no one does anything stupid
     if( jo.has_member( "mapgensize" ) ) {
         jo.throw_error( "\"mapgensize\" only allowed for nested mapgen" );
     }
     // something akin to mapgen fill_background.
     if( jo.has_string( "fill_ter" ) ) {
         fill_ter = ter_str_id( jo.get_string( "fill_ter" ) ).id();
     }
     if( jo.has_member( "rotation" ) ) {
         rotation = jmapgen_int( jo, "rotation" );
     }
     if( jo.has_member( "predecessor_mapgen" ) ) {
         predecessor_mapgen = oter_str_id( jo.get_string( "predecessor_mapgen" ) ).id();
     } else {
         predecessor_mapgen = oter_str_id::NULL_ID();
     }
     jo.read( "fallback_predecessor_mapgen", fallback_predecessor_mapgen_ );
     return fill_ter != t_null || predecessor_mapgen != oter_str_id::NULL_ID() ||
            fallback_predecessor_mapgen_ != oter_str_id::NULL_ID();
 }
References JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_string(), string_id< T >::id(), string_id< oter_t >::NULL_ID(), JsonObject::read(), t_null, ter_str_id, and JsonObject::throw_error().
Member Data Documentation
fallback_predecessor_mapgen_
oter_str_id mapgen_function_json::fallback_predecessor_mapgen_ private
Definition at line 513 of file mapgen.h.
fill_ter
ter_id mapgen_function_json::fill_ter
Definition at line 505 of file mapgen.h.
predecessor_mapgen
oter_id mapgen_function_json::predecessor_mapgen
Definition at line 506 of file mapgen.h.
rotation
jmapgen_int mapgen_function_json::rotation private
Definition at line 512 of file mapgen.h.
The documentation for this class was generated from the following files:
src/mapgen.h
src/mapgen.cpp