Cataclysm DDA: ma_weapon_damage_reader Class Reference
ma_weapon_damage_reader Class Reference
Public Member Functions
std::pair< damage_type_id, int > get_next (const JsonObject &jo) const
template<typename C >
void erase_next (const JsonObject &jo, C &container) const
Public Member Functions inherited from generic_typed_reader< ma_weapon_damage_reader >
void insert_values_from (const JsonObject &jo, const std::string_view member_name, C &container) const
void insert_next (JsonValue &jv, C &container) const
void erase_values_from (const JsonObject &jo, const std::string_view member_name, C &container) const
void erase_next (JsonValue &jv, C &container) const
bool operator() (const JsonObject &jo, const std::string_view member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string_view member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string_view name, C &) const
bool do_relative (const JsonObject &jo, const std::string_view name, C &member) const
bool read_normal (const JsonObject &jo, const std::string_view name, C &member) const
Detailed Description
Definition at line 154 of file martialarts.cpp.
Member Function Documentation
erase_next()
template<typename C > void ma_weapon_damage_reader::erase_next (const JsonObject & jo, C & container) const inline
Definition at line 161 of file martialarts.cpp.
{
             damage_type_id id( jo.get_string( "type" ) );
             reader_detail::handler<C>().erase_if( container,
             [&id]( const std::pair<const damage_type_id, int> &e ) {
                 return e.first == id;
             } );
         }
References JsonObject::get_string(), and base_camps::id.
get_next()
std::pair<damage_type_id, int> ma_weapon_damage_reader::get_next (const JsonObject & jo) const inline
Definition at line 157 of file martialarts.cpp.
{
             return std::pair<damage_type_id, int>( jo.get_string( "type" ), jo.get_int( "min" ) );
         }
References JsonObject::get_int(), and JsonObject::get_string().
The documentation for this class was generated from the following file:
src/martialarts.cpp