Cataclysm DDA: book_proficiency_bonuses Class Reference
book_proficiency_bonuses Class Reference
#include <proficiency.h>
Public Member Functions
void add (const book_proficiency_bonus &bonus)
book_proficiency_bonuses & operator+= (const book_proficiency_bonuses &rhs)
float fail_factor (const proficiency_id &id) const
float time_factor (const proficiency_id &id) const
Private Member Functions
void add (const book_proficiency_bonus &bonus, std::set< proficiency_id > &already_included)
Private Attributes
std::vector< book_proficiency_bonus > bonuses
Detailed Description
Definition at line 211 of file proficiency.h.
Member Function Documentation
add() [1/2]
void book_proficiency_bonuses::add (const book_proficiency_bonus & bonus)
Definition at line 590 of file proficiency.cpp.
 {
     std::set<proficiency_id> ret;
     add( bonus, ret );
 }
References add(), and cata::hash64_detail::ret.
add() [2/2]
void book_proficiency_bonuses::add (const book_proficiency_bonus & bonus, std::set< proficiency_id > & already_included) private
Definition at line 596 of file proficiency.cpp.
 {
     bonuses.push_back( bonus );
     if( bonus.include_prereqs ) {
         for( const proficiency_id &prereqs : bonus.id->required_proficiencies() ) {
             if( !already_included.count( prereqs ) ) {
                 already_included.emplace( prereqs );
                 book_proficiency_bonus inherited_bonus = bonus;
                 inherited_bonus.id = prereqs;
                 add( inherited_bonus );
             }
         }
     }
 }
References bonuses, book_proficiency_bonus::id, book_proficiency_bonus::include_prereqs, and proficiency::required_proficiencies().
Referenced by add(), and operator+=().
fail_factor()
float book_proficiency_bonuses::fail_factor (const proficiency_id & id) const
Definition at line 621 of file proficiency.cpp.
 {
     double sum = 0;
     for( const book_proficiency_bonus &bonus : bonuses ) {
         if( id != bonus.id ) {
             continue;
         }
         sum += std::pow( std::log( 1.0 - bonus.fail_factor ), 2 );
     }
     return static_cast<float>( 1.0 - std::exp( -std::sqrt( sum ) ) );
 }
References bonuses, log(), and sqrt().
Referenced by recipe::missing_proficiencies_string(), and proficiency_skill_malus().
operator+=()
book_proficiency_bonuses & book_proficiency_bonuses::operator+= (const book_proficiency_bonuses & rhs)
Definition at line 612 of file proficiency.cpp.
 {
     for( const book_proficiency_bonus &bonus : rhs.bonuses ) {
         add( bonus );
     }
     return *this;
 }
References add(), and bonuses.
time_factor()
float book_proficiency_bonuses::time_factor (const proficiency_id & id) const
Definition at line 635 of file proficiency.cpp.
 {
     double sum = 0;
     for( const book_proficiency_bonus &bonus : bonuses ) {
         if( id != bonus.id ) {
             continue;
         }
         sum += std::pow( std::log( 1.0 - bonus.time_factor ), 2 );
     }
     return static_cast<float>( 1.0 - std::exp( -std::sqrt( sum ) ) );
 }
References bonuses, log(), and sqrt().
Referenced by recipe::missing_proficiencies_string(), and proficiency_time_malus().
Member Data Documentation
bonuses
std::vector<book_proficiency_bonus> book_proficiency_bonuses::bonuses private
Definition at line 214 of file proficiency.h.
Referenced by add(), fail_factor(), operator+=(), and time_factor().
The documentation for this class was generated from the following files:
src/proficiency.h
src/proficiency.cpp