Cataclysm DDA: vehicle_unfolding_activity_actor Class Reference
vehicle_unfolding_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
vehicle_unfolding_activity_actor (const item &it)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &p) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &p) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &p) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &act, Character &p) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Member Functions
bool unfold_vehicle (Character &p, bool check_only) const
vehicle_unfolding_activity_actor ()=default
Private Attributes
item it
time_duration unfolding_time
Detailed Description
Definition at line 1639 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
vehicle_unfolding_activity_actor() [1/2]
vehicle_unfolding_activity_actor::vehicle_unfolding_activity_actor () explicit private default
vehicle_unfolding_activity_actor() [2/2]
vehicle_unfolding_activity_actor::vehicle_unfolding_activity_actor (const item & it) explicit
Definition at line 7548 of file activity_actor.cpp.
     : it( it )
 {
     constexpr int legacy_unfold_moves = 500;
     unfolding_time = time_duration::from_moves( it.get_var( "unfolding_time", legacy_unfold_moves ) );
 }
References time_duration::from_moves(), item::get_var(), it, and unfolding_time.
Member Function Documentation
canceled()
void vehicle_unfolding_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 7582 of file activity_actor.cpp.
 {
     get_map().add_item_or_charges( p.pos(), it, true );
     act.set_to_null();
 }
References act, map::add_item_or_charges(), get_map(), it, and Creature::pos().
clone()
std::unique_ptr<activity_actor> vehicle_unfolding_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1665 of file activity_actor_definitions.h.
{
             return std::make_unique<vehicle_unfolding_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > vehicle_unfolding_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 7596 of file activity_actor.cpp.
 {
     vehicle_unfolding_activity_actor actor;
     JsonObject data = jsin.get_object();
     data.read( "it", actor.it );
     data.read( "unfolding_time", actor.unfolding_time );
     return actor.clone();
 }
References clone(), JsonValue::get_object(), it, JsonObject::read(), and unfolding_time.
do_turn()
void vehicle_unfolding_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 7564 of file activity_actor.cpp.
 {
     if( calendar::once_every( 30_seconds ) ) {
         if( !unfold_vehicle( p, /* check_only = */ true ) ) {
             act.canceled( p );
         }
     }
 }
References act, calendar::once_every(), and unfold_vehicle().
finish()
void vehicle_unfolding_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 7573 of file activity_actor.cpp.
 {
     if( !unfold_vehicle( p, /* check_only = */ false ) ) {
         debugmsg( "failed unfolding %s", it.display_name() );
         act.canceled( p );
     }
     act.set_to_null();
 }
References act, debugmsg, item::display_name(), it, and unfold_vehicle().
get_type()
activity_id vehicle_unfolding_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1656 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_VEHICLE_UNFOLD" );
         }
References activity_id.
serialize()
void vehicle_unfolding_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 7588 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "it", it );
     jsout.member( "unfolding_time", unfolding_time );
     jsout.end_object();
 }
References JsonOut::end_object(), it, JsonOut::member(), JsonOut::start_object(), and unfolding_time.
start()
void vehicle_unfolding_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 7555 of file activity_actor.cpp.
 {
     act.moves_total = to_moves<int>( unfolding_time );
     act.moves_left = to_moves<int>( unfolding_time );
     if( !unfold_vehicle( p, /* check_only = */ true ) ) {
         act.canceled( p );
     }
 }
References act, unfold_vehicle(), and unfolding_time.
unfold_vehicle()
bool vehicle_unfolding_activity_actor::unfold_vehicle (Character & p, bool check_only) const private
Definition at line 7480 of file activity_actor.cpp.
 {
     if( p.cant_do_underwater() ) {
         return false;
     }
     if( p.cant_do_mounted() ) {
         return false;
     }
     map &here = get_map();
     vehicle *veh = here.add_vehicle( vehicle_prototype_none, p.pos(), 0_degrees, 0, 0, false );
     if( veh == nullptr ) {
         p.add_msg_if_player( m_info, _( "There's no room to unfold the %s." ), it.tname() );
         return false;
     }
     if( !veh->restore_folded_parts( it ) ) {
         here.destroy_vehicle( veh );
         return false;
     }
     const bool cant_float = !veh->can_float();
     const auto invalid_pos = [&here, &cant_float]( const tripoint & p ) {
         return ( cant_float && here.has_flag_ter( ter_furn_flag::TFLAG_DEEP_WATER, p ) )
                || here.veh_at( p )
                || here.impassable( p );
     };
     const inventory &inv = p.crafting_inventory();
     for( const vpart_reference &vp : veh->get_all_parts() ) {
         if( vp.info().location != "structure" ) {
             continue;
         }
         if( invalid_pos( vp.pos() ) ) {
             p.add_msg_if_player( m_info, _( "There's no room to unfold the %s." ), it.tname() );
             here.destroy_vehicle( veh );
             return false;
         }
         for( const itype_id &tool : vp.info().get_unfolding_tools() ) {
             if( !inv.has_tools( tool, 1 ) ) {
                 p.add_msg_if_player( _( "You need %s to do it!" ), item::nname( tool ) );
                 here.destroy_vehicle( veh );
                 return false;
             }
         }
     }
     if( check_only ) { // if we're just checking bail out at this point - this is a valid location.
         here.destroy_vehicle( veh );
         return true;
     }
     veh->name = it.get_var( "vehicle_name" );
     veh->set_owner( p );
     here.add_vehicle_to_cache( veh );
     if( here.veh_at( p.pos() ).part_with_feature( "BOARDABLE", true ) ) {
         here.board_vehicle( p.pos(), &p ); // if boardable unbroken part is present -> get on it
     }
     if( p.is_avatar() && it.get_var( "tracking", 0 ) == 1 ) {
         veh->toggle_tracking(); // restore position tracking state
     }
     std::string unfold_msg = it.get_var( "unfold_msg" );
     if( unfold_msg.empty() ) {
         unfold_msg = _( "You unfold the %s." );
     } else {
         unfold_msg = _( unfold_msg );
     }
     p.add_msg_if_player( m_neutral, unfold_msg, veh->name );
     return true;
 }
References _, Character::add_msg_if_player(), map::add_vehicle(), map::add_vehicle_to_cache(), map::board_vehicle(), vehicle::can_float(), Character::cant_do_mounted(), Creature::cant_do_underwater(), Character::crafting_inventory(), map::destroy_vehicle(), vehicle::get_all_parts(), get_map(), item::get_var(), map::has_flag_ter(), read_only_visitable::has_tools(), map::impassable(), Creature::is_avatar(), it, m_info, m_neutral, vehicle::name, item::nname(), optional_vpart_position::part_with_feature(), Creature::pos(), vehicle::restore_folded_parts(), vehicle::set_owner(), TFLAG_DEEP_WATER, item::tname(), vehicle::toggle_tracking(), map::veh_at(), and vehicle_prototype_none.
Referenced by do_turn(), finish(), and start().
Member Data Documentation
it
item vehicle_unfolding_activity_actor::it private
Definition at line 1643 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), finish(), serialize(), unfold_vehicle(), and vehicle_unfolding_activity_actor().
unfolding_time
time_duration vehicle_unfolding_activity_actor::unfolding_time private
Definition at line 1645 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), start(), and vehicle_unfolding_activity_actor().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp