Cataclysm DDA: npc_template Class Reference
npc_template Class Reference
#include <npc.h>
Public Types
enum class gender : int { random , male , female }
Public Member Functions
npc_template ()=default
Static Public Member Functions
static void load (const JsonObject &jsobj)
static void reset ()
static void check_consistency ()
Public Attributes
npc guy
dialogue_chatbin_snippets snippets
translation name_unique
translation name_suffix
gender gender_override = gender::random
std::optional< int > age
std::optional< int > height
std::optional< int > str
std::optional< int > dex
std::optional< int > intl
std::optional< int > per
std::optional< npc_personality > personality
Detailed Description
Definition at line 1491 of file npc.h.
Member Enumeration Documentation
gender
enum npc_template::gender : int strong
Enumerator
random
male
female
Definition at line 1500 of file npc.h.
                           : int {
             random,
             male,
             female
         };
Constructor & Destructor Documentation
npc_template()
npc_template::npc_template () default
Member Function Documentation
check_consistency()
void npc_template::check_consistency () static
Definition at line 461 of file npc.cpp.
 {
     for( const auto &e : npc_templates ) {
         const npc &guy = e.second.guy;
         if( !guy.myclass.is_valid() ) {
             debugmsg( "Invalid NPC class %s", guy.myclass.c_str() );
         }
         std::string first_topic = guy.chatbin.first_topic;
         if( const json_talk_topic *topic = get_talk_topic( first_topic ) ) {
             cata::flat_set<std::string> reachable_topics =
                 topic->get_directly_reachable_topics( true );
             if( reachable_topics.count( "TALK_MISSION_OFFER" ) ) {
                 debugmsg(
                     "NPC template \"%s\" has dialogue \"%s\" which leads unconditionally to "
                     "\"TALK_MISSION_OFFER\", which doesn't check for an available mission.  "
                     "You should probably prefer \"TALK_MISSION_LIST\"",
                     e.first.str(), first_topic );
             }
         }
     }
 }
References string_id< T >::c_str(), npc::chatbin, cata::flat_set< T, Compare, Data >::count(), debugmsg, dialogue_chatbin::first_topic, get_talk_topic(), guy, string_id< T >::is_valid(), npc::myclass, and npc_templates.
Referenced by DynamicDataLoader::check_consistency().
load()
void npc_template::load (const JsonObject & jsobj) static
Definition at line 293 of file npc.cpp.
 {
     npc_template tem;
     npc &guy = tem.guy;
     jsobj.get_member( "id" ).read( guy.idz );
     guy.name.clear();
     jsobj.read( "name_unique", tem.name_unique );
     jsobj.read( "name_suffix", tem.name_suffix );
     if( jsobj.has_string( "gender" ) ) {
         if( jsobj.get_string( "gender" ) == "male" ) {
             tem.gender_override = gender::male;
         } else {
             tem.gender_override = gender::female;
         }
     }
     if( jsobj.has_string( "faction" ) ) {
         guy.set_fac_id( jsobj.get_string( "faction" ) );
     }
     if( jsobj.has_int( "class" ) ) {
         guy.myclass = npc_class::from_legacy_int( jsobj.get_int( "class" ) );
     } else if( jsobj.has_string( "class" ) ) {
         guy.myclass = npc_class_id( jsobj.get_string( "class" ) );
     }
     guy.set_attitude( static_cast<npc_attitude>( jsobj.get_int( "attitude" ) ) );
     guy.mission = static_cast<npc_mission>( jsobj.get_int( "mission" ) );
     guy.chatbin.first_topic = jsobj.get_string( "chat" );
     if( jsobj.has_string( "mission_offered" ) ) {
         guy.miss_ids.emplace_back( jsobj.get_string( "mission_offered" ) );
     } else if( jsobj.has_array( "mission_offered" ) ) {
         for( const std::string line : jsobj.get_array( "mission_offered" ) ) {
             guy.miss_ids.emplace_back( line );
         }
     }
     if( jsobj.has_string( "talk_radio" ) ) {
         guy.chatbin.talk_radio = jsobj.get_string( "talk_radio" );
     }
     if( jsobj.has_string( "talk_leader" ) ) {
         guy.chatbin.talk_leader = jsobj.get_string( "talk_leader" );
     }
     if( jsobj.has_string( "talk_friend" ) ) {
         guy.chatbin.talk_friend = jsobj.get_string( "talk_friend" );
     }
     if( jsobj.has_string( "talk_stole_item" ) ) {
         guy.chatbin.talk_stole_item = jsobj.get_string( "talk_stole_item" );
     }
     if( jsobj.has_string( "talk_wake_up" ) ) {
         guy.chatbin.talk_wake_up = jsobj.get_string( "talk_wake_up" );
     }
     if( jsobj.has_string( "talk_mug" ) ) {
         guy.chatbin.talk_mug = jsobj.get_string( "talk_mug" );
     }
     if( jsobj.has_string( "talk_stranger_aggressive" ) ) {
         guy.chatbin.talk_stranger_aggressive = jsobj.get_string( "talk_stranger_aggressive" );
     }
     if( jsobj.has_string( "talk_stranger_scared" ) ) {
         guy.chatbin.talk_stranger_scared = jsobj.get_string( "talk_stranger_scared" );
     }
     if( jsobj.has_string( "talk_stranger_wary" ) ) {
         guy.chatbin.talk_stranger_wary = jsobj.get_string( "talk_stranger_wary" );
     }
     if( jsobj.has_string( "talk_stranger_friendly" ) ) {
         guy.chatbin.talk_stranger_friendly = jsobj.get_string( "talk_stranger_friendly" );
     }
     if( jsobj.has_string( "talk_stranger_neutral" ) ) {
         guy.chatbin.talk_stranger_neutral = jsobj.get_string( "talk_stranger_neutral" );
     }
     if( jsobj.has_string( "talk_friend_guard" ) ) {
         guy.chatbin.talk_friend_guard = jsobj.get_string( "talk_friend_guard" );
     }
     jsobj.read( "<acknowledged>", tem.snippets.snip_acknowledged );
     jsobj.read( "<camp_food_thanks>", tem.snippets.snip_camp_food_thanks );
     jsobj.read( "<camp_larder_empty>", tem.snippets.snip_camp_larder_empty );
     jsobj.read( "<camp_water_thanks>", tem.snippets.snip_camp_water_thanks );
     jsobj.read( "<cant_flee>", tem.snippets.snip_cant_flee );
     jsobj.read( "<close_distance>", tem.snippets.snip_close_distance );
     jsobj.read( "<combat_noise_warning>", tem.snippets.snip_combat_noise_warning );
     jsobj.read( "<danger_close_distance>", tem.snippets.snip_danger_close_distance );
     jsobj.read( "<done_mugging>", tem.snippets.snip_done_mugging );
     jsobj.read( "<far_distance>", tem.snippets.snip_far_distance );
     jsobj.read( "<fire_bad>", tem.snippets.snip_fire_bad );
     jsobj.read( "<fire_in_the_hole_h>", tem.snippets.snip_fire_in_the_hole_h );
     jsobj.read( "<fire_in_the_hole>", tem.snippets.snip_fire_in_the_hole );
     jsobj.read( "<general_danger_h>", tem.snippets.snip_general_danger_h );
     jsobj.read( "<general_danger>", tem.snippets.snip_general_danger );
     jsobj.read( "<heal_self>", tem.snippets.snip_heal_self );
     jsobj.read( "<hungry>", tem.snippets.snip_hungry );
     jsobj.read( "<im_leaving_you>", tem.snippets.snip_im_leaving_you );
     jsobj.read( "<its_safe_h>", tem.snippets.snip_its_safe_h );
     jsobj.read( "<its_safe>", tem.snippets.snip_its_safe );
     jsobj.read( "<keep_up>", tem.snippets.snip_keep_up );
     jsobj.read( "<kill_npc_h>", tem.snippets.snip_kill_npc_h );
     jsobj.read( "<kill_npc>", tem.snippets.snip_kill_npc );
     jsobj.read( "<kill_player_h>", tem.snippets.snip_kill_player_h );
     jsobj.read( "<let_me_pass>", tem.snippets.snip_let_me_pass );
     jsobj.read( "<lets_talk>", tem.snippets.snip_lets_talk );
     jsobj.read( "<medium_distance>", tem.snippets.snip_medium_distance );
     jsobj.read( "<monster_warning_h>", tem.snippets.snip_monster_warning_h );
     jsobj.read( "<monster_warning>", tem.snippets.snip_monster_warning );
     jsobj.read( "<movement_noise_warning>", tem.snippets.snip_movement_noise_warning );
     jsobj.read( "<need_batteries>", tem.snippets.snip_need_batteries );
     jsobj.read( "<need_booze>", tem.snippets.snip_need_booze );
     jsobj.read( "<need_fuel>", tem.snippets.snip_need_fuel );
     jsobj.read( "<no_to_thorazine>", tem.snippets.snip_no_to_thorazine );
     jsobj.read( "<run_away>", tem.snippets.snip_run_away );
     jsobj.read( "<speech_warning>", tem.snippets.snip_speech_warning );
     jsobj.read( "<thirsty>", tem.snippets.snip_thirsty );
     jsobj.read( "<wait>", tem.snippets.snip_wait );
     jsobj.read( "<warn_sleep>", tem.snippets.snip_warn_sleep );
     jsobj.read( "<yawn>", tem.snippets.snip_yawn );
     jsobj.read( "<yes_to_lsd>", tem.snippets.snip_yes_to_lsd );
     jsobj.read( "snip_pulp_zombie", tem.snippets.snip_pulp_zombie );
     jsobj.read( "snip_heal_player", tem.snippets.snip_heal_player );
     jsobj.read( "snip_mug_dontmove", tem.snippets.snip_mug_dontmove );
     jsobj.read( "snip_wound_infected", tem.snippets.snip_wound_infected );
     jsobj.read( "snip_wound_bite", tem.snippets.snip_wound_bite );
     jsobj.read( "snip_radiation_sickness", tem.snippets.snip_radiation_sickness );
     jsobj.read( "snip_bleeding", tem.snippets.snip_bleeding );
     jsobj.read( "snip_bleeding_badly", tem.snippets.snip_bleeding_badly );
     jsobj.read( "snip_lost_blood", tem.snippets.snip_lost_blood );
     jsobj.read( "snip_bye", tem.snippets.snip_bye );
     jsobj.read( "snip_consume_cant_accept", tem.snippets.snip_consume_cant_accept );
     jsobj.read( "snip_consume_cant_consume", tem.snippets.snip_consume_cant_consume );
     jsobj.read( "snip_consume_rotten", tem.snippets.snip_consume_rotten );
     jsobj.read( "snip_consume_eat", tem.snippets.snip_consume_eat );
     jsobj.read( "snip_consume_need_item", tem.snippets.snip_consume_need_item );
     jsobj.read( "snip_consume_med", tem.snippets.snip_consume_med );
     jsobj.read( "snip_consume_nocharge", tem.snippets.snip_consume_nocharge );
     jsobj.read( "snip_consume_use_med", tem.snippets.snip_consume_use_med );
     jsobj.read( "snip_give_nope", tem.snippets.snip_give_nope );
     jsobj.read( "snip_give_to_hallucination", tem.snippets.snip_give_to_hallucination );
     jsobj.read( "snip_give_cancel", tem.snippets.snip_give_cancel );
     jsobj.read( "snip_give_dangerous", tem.snippets.snip_give_dangerous );
     jsobj.read( "snip_give_wield", tem.snippets.snip_give_wield );
     jsobj.read( "snip_give_weapon_weak", tem.snippets.snip_give_weapon_weak );
     jsobj.read( "snip_give_carry", tem.snippets.snip_give_carry );
     jsobj.read( "snip_give_carry_cant", tem.snippets.snip_give_carry_cant );
     jsobj.read( "snip_give_carry_cant_few_space", tem.snippets.snip_give_carry_cant_few_space );
     jsobj.read( "snip_give_carry_cant_no_space", tem.snippets.snip_give_carry_cant_no_space );
     jsobj.read( "snip_give_carry_too_heavy", tem.snippets.snip_give_carry_too_heavy );
     jsobj.read( "snip_wear", tem.snippets.snip_wear );
     jsobj.read( "age", tem.age );
     jsobj.read( "height", tem.height );
     jsobj.read( "str", tem.str );
     jsobj.read( "dex", tem.dex );
     jsobj.read( "int", tem.intl );
     jsobj.read( "per", tem.per );
     if( jsobj.has_object( "personality" ) ) {
         const JsonObject personality = jsobj.get_object( "personality" );
         tem.personality = npc_personality();
         tem.personality->aggression = personality.get_int( "aggression" );
         tem.personality->bravery = personality.get_int( "bravery" );
         tem.personality->collector = personality.get_int( "collector" );
         tem.personality->altruism = personality.get_int( "altruism" );
     }
     for( JsonValue jv : jsobj.get_array( "death_eocs" ) ) {
         guy.death_eocs.emplace_back( effect_on_conditions::load_inline_eoc( jv, "" ) );
     }
     npc_templates.emplace( guy.idz, std::move( tem ) );
 }
References age, npc::chatbin, Character::death_eocs, dex, dialogue_chatbin::first_topic, npc_class::from_legacy_int(), gender_override, JsonValue::get_array(), JsonObject::get_int(), JsonObject::get_object(), guy, height, npc::idz, intl, line(), effect_on_conditions::load_inline_eoc(), male, npc::miss_ids, npc::mission, npc::myclass, Character::name, name_suffix, name_unique, npc_templates, per, personality, npc::set_attitude(), Character::set_fac_id(), dialogue_chatbin_snippets::snip_acknowledged, dialogue_chatbin_snippets::snip_bleeding, dialogue_chatbin_snippets::snip_bleeding_badly, dialogue_chatbin_snippets::snip_bye, dialogue_chatbin_snippets::snip_camp_food_thanks, dialogue_chatbin_snippets::snip_camp_larder_empty, dialogue_chatbin_snippets::snip_camp_water_thanks, dialogue_chatbin_snippets::snip_cant_flee, dialogue_chatbin_snippets::snip_close_distance, dialogue_chatbin_snippets::snip_combat_noise_warning, dialogue_chatbin_snippets::snip_consume_cant_accept, dialogue_chatbin_snippets::snip_consume_cant_consume, dialogue_chatbin_snippets::snip_consume_eat, dialogue_chatbin_snippets::snip_consume_med, dialogue_chatbin_snippets::snip_consume_need_item, dialogue_chatbin_snippets::snip_consume_nocharge, dialogue_chatbin_snippets::snip_consume_rotten, dialogue_chatbin_snippets::snip_consume_use_med, dialogue_chatbin_snippets::snip_danger_close_distance, dialogue_chatbin_snippets::snip_done_mugging, dialogue_chatbin_snippets::snip_far_distance, dialogue_chatbin_snippets::snip_fire_bad, dialogue_chatbin_snippets::snip_fire_in_the_hole, dialogue_chatbin_snippets::snip_fire_in_the_hole_h, dialogue_chatbin_snippets::snip_general_danger, dialogue_chatbin_snippets::snip_general_danger_h, dialogue_chatbin_snippets::snip_give_cancel, dialogue_chatbin_snippets::snip_give_carry, dialogue_chatbin_snippets::snip_give_carry_cant, dialogue_chatbin_snippets::snip_give_carry_cant_few_space, dialogue_chatbin_snippets::snip_give_carry_cant_no_space, dialogue_chatbin_snippets::snip_give_carry_too_heavy, dialogue_chatbin_snippets::snip_give_dangerous, dialogue_chatbin_snippets::snip_give_nope, dialogue_chatbin_snippets::snip_give_to_hallucination, dialogue_chatbin_snippets::snip_give_weapon_weak, dialogue_chatbin_snippets::snip_give_wield, dialogue_chatbin_snippets::snip_heal_player, dialogue_chatbin_snippets::snip_heal_self, dialogue_chatbin_snippets::snip_hungry, dialogue_chatbin_snippets::snip_im_leaving_you, dialogue_chatbin_snippets::snip_its_safe, dialogue_chatbin_snippets::snip_its_safe_h, dialogue_chatbin_snippets::snip_keep_up, dialogue_chatbin_snippets::snip_kill_npc, dialogue_chatbin_snippets::snip_kill_npc_h, dialogue_chatbin_snippets::snip_kill_player_h, dialogue_chatbin_snippets::snip_let_me_pass, dialogue_chatbin_snippets::snip_lets_talk, dialogue_chatbin_snippets::snip_lost_blood, dialogue_chatbin_snippets::snip_medium_distance, dialogue_chatbin_snippets::snip_monster_warning, dialogue_chatbin_snippets::snip_monster_warning_h, dialogue_chatbin_snippets::snip_movement_noise_warning, dialogue_chatbin_snippets::snip_mug_dontmove, dialogue_chatbin_snippets::snip_need_batteries, dialogue_chatbin_snippets::snip_need_booze, dialogue_chatbin_snippets::snip_need_fuel, dialogue_chatbin_snippets::snip_no_to_thorazine, dialogue_chatbin_snippets::snip_pulp_zombie, dialogue_chatbin_snippets::snip_radiation_sickness, dialogue_chatbin_snippets::snip_run_away, dialogue_chatbin_snippets::snip_speech_warning, dialogue_chatbin_snippets::snip_thirsty, dialogue_chatbin_snippets::snip_wait, dialogue_chatbin_snippets::snip_warn_sleep, dialogue_chatbin_snippets::snip_wear, dialogue_chatbin_snippets::snip_wound_bite, dialogue_chatbin_snippets::snip_wound_infected, dialogue_chatbin_snippets::snip_yawn, dialogue_chatbin_snippets::snip_yes_to_lsd, snippets, str, dialogue_chatbin::talk_friend, dialogue_chatbin::talk_friend_guard, dialogue_chatbin::talk_leader, dialogue_chatbin::talk_mug, dialogue_chatbin::talk_radio, dialogue_chatbin::talk_stole_item, dialogue_chatbin::talk_stranger_aggressive, dialogue_chatbin::talk_stranger_friendly, dialogue_chatbin::talk_stranger_neutral, dialogue_chatbin::talk_stranger_scared, dialogue_chatbin::talk_stranger_wary, and dialogue_chatbin::talk_wake_up.
Referenced by DynamicDataLoader::initialize().
reset()
void npc_template::reset () static
Definition at line 456 of file npc.cpp.
 {
     npc_templates.clear();
 }
References npc_templates.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
age
std::optional<int> npc_template::age
Definition at line 1506 of file npc.h.
Referenced by load(), and npc::randomize().
dex
std::optional<int> npc_template::dex
Definition at line 1509 of file npc.h.
Referenced by load(), and npc::randomize().
gender_override
gender npc_template::gender_override = gender::random
Definition at line 1505 of file npc.h.
Referenced by load(), and npc::load_npc_template().
guy
npc npc_template::guy
Definition at line 1496 of file npc.h.
Referenced by check_consistency(), load(), and npc::load_npc_template().
height
std::optional<int> npc_template::height
Definition at line 1507 of file npc.h.
Referenced by load(), and npc::randomize().
intl
std::optional<int> npc_template::intl
Definition at line 1510 of file npc.h.
Referenced by load(), and npc::randomize().
name_suffix
translation npc_template::name_suffix
Definition at line 1499 of file npc.h.
Referenced by load(), and npc::load_npc_template().
name_unique
translation npc_template::name_unique
Definition at line 1498 of file npc.h.
Referenced by load(), and npc::load_npc_template().
per
std::optional<int> npc_template::per
Definition at line 1511 of file npc.h.
Referenced by load(), and npc::randomize().
personality
std::optional<npc_personality> npc_template::personality
Definition at line 1512 of file npc.h.
Referenced by load(), and npc::randomize().
snippets
dialogue_chatbin_snippets npc_template::snippets
Definition at line 1497 of file npc.h.
Referenced by npc::chat_snippets(), and load().
str
std::optional<int> npc_template::str
Definition at line 1508 of file npc.h.
Referenced by load(), and npc::randomize().
The documentation for this class was generated from the following files:
src/npc.h
src/npc.cpp