Cataclysm DDA: stash_activity_actor Class Reference
stash_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
stash_activity_actor ()=default
stash_activity_actor (const std::vector< drop_or_stash_item_info > &items, const tripoint &placement)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &act, Character &who) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
std::vector< drop_or_stash_item_info > items
contents_change_handler handler
tripoint placement
bool current_bulk_unload = false
Detailed Description
Definition at line 1083 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
stash_activity_actor() [1/2]
stash_activity_actor::stash_activity_actor () default
stash_activity_actor() [2/2]
stash_activity_actor::stash_activity_actor (const std::vector< drop_or_stash_item_info > & items, const tripoint & placement) inline
Definition at line 1087 of file activity_actor_definitions.h.
             : items( items ), placement( placement ) {}
Member Function Documentation
canceled()
void stash_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 4356 of file activity_actor.cpp.
 {
     handler.handle_by( who );
 }
References contents_change_handler::handle_by(), and handler.
clone()
std::unique_ptr<activity_actor> stash_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1100 of file activity_actor_definitions.h.
{
             return std::make_unique<stash_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > stash_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 4371 of file activity_actor.cpp.
 {
     stash_activity_actor actor;
     JsonObject jsobj = jsin.get_object();
     jsobj.read( "items", actor.items );
     jsobj.read( "unhandled_containers", actor.handler );
     jsobj.read( "placement", actor.placement );
     jsobj.read( "current_bulk_unload", actor.current_bulk_unload );
     return actor.clone();
 }
References clone(), current_bulk_unload, JsonValue::get_object(), handler, items, placement, and JsonObject::read().
do_turn()
void stash_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 4339 of file activity_actor.cpp.
 {
     const tripoint pos = placement + who.pos();
     monster *pet = get_creature_tracker().creature_at<monster>( pos );
     if( pet != nullptr && pet->has_effect( effect_pet ) ) {
         stash_on_pet( obtain_activity_items( items, handler, who, current_bulk_unload ),
                       *pet, who );
         if( items.empty() ) {
             who.cancel_activity();
         }
     } else {
         who.add_msg_if_player( _( "The pet has moved somewhere else." ) );
         who.cancel_activity();
     }
 }
References _, Character::add_msg_if_player(), Character::cancel_activity(), creature_tracker::creature_at(), current_bulk_unload, effect_pet, get_creature_tracker(), handler, Creature::has_effect(), items, obtain_activity_items(), placement, Creature::pos(), math_opers::pos(), and stash_on_pet().
finish()
void stash_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1097 of file activity_actor_definitions.h.
 {}
get_progress_message()
std::string stash_activity_actor::get_progress_message (const player_activity & act) const inline override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 1104 of file activity_actor_definitions.h.
{
             return std::string();
         }
get_type()
activity_id stash_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1091 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_STASH" );
         }
References activity_id.
serialize()
void stash_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 4361 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "items", items );
     jsout.member( "unhandled_containers", handler );
     jsout.member( "placement", placement );
     jsout.member( "current_bulk_unload", current_bulk_unload );
     jsout.end_object();
 }
References current_bulk_unload, JsonOut::end_object(), handler, items, JsonOut::member(), placement, and JsonOut::start_object().
start()
void stash_activity_actor::start (player_activity & act, Character & who) inline override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1095 of file activity_actor_definitions.h.
 {}
Member Data Documentation
current_bulk_unload
bool stash_activity_actor::current_bulk_unload = false private
Definition at line 1115 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
handler
contents_change_handler stash_activity_actor::handler private
Definition at line 1113 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), do_turn(), and serialize().
items
std::vector<drop_or_stash_item_info> stash_activity_actor::items private
Definition at line 1112 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
placement
tripoint stash_activity_actor::placement private
Definition at line 1114 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp