Cataclysm DDA: event_bus Class Reference
event_bus Class Reference
#include <event_bus.h>
Public Member Functions
event_bus ()=default
event_bus (const event_bus &)=delete
event_bus & operator= (const event_bus &)=delete
~event_bus ()
void subscribe (event_subscriber *)
void unsubscribe (event_subscriber *)
void send (const cata::event &) const
void send_with_talker (Creature *, Creature *, const cata::event &) const
void send_with_talker (Creature *, item_location *, const cata::event &) const
template<event_type Type, typename... Args>
void send (Args &&... args) const
Private Attributes
std::vector< event_subscriber * > subscribers
Detailed Description
Definition at line 14 of file event_bus.h.
Constructor & Destructor Documentation
event_bus() [1/2]
event_bus::event_bus () default
event_bus() [2/2]
event_bus::event_bus (const event_bus &) delete
~event_bus()
event_bus::~event_bus ()
Definition at line 48 of file event_bus.cpp.
 {
     while( !subscribers.empty() ) {
         unsubscribe( subscribers.front() );
     }
 }
References subscribers, and unsubscribe().
Member Function Documentation
operator=()
event_bus& event_bus::operator= (const event_bus &) delete
send() [1/2]
template<event_type Type, typename... Args> void event_bus::send (Args &&... args) const inline
Definition at line 28 of file event_bus.h.
{
             send( cata::event::make<Type>( std::forward<Args>( args )... ) );
         }
References send().
send() [2/2]
void event_bus::send (const cata::event & e) const
Definition at line 72 of file event_bus.cpp.
 {
     // don't accept malformed events (ex: wrong number of arguments)
     // from event::make_dyn()
     if( e.type() == event_type::num_event_types ) {
         debugmsg( "Null event sent to bus.  REJECTED!" );
         return;
     }
     for( event_subscriber *s : subscribers ) {
         s->notify( e );
     }
 }
References debugmsg, num_event_types, subscribers, and cata::event::type().
Referenced by achievement_attained(), achievement_failed(), computer_session::action_cascade(), computer_session::action_miss_disarm(), computer_session::action_portal(), computer_session::action_release(), computer_session::action_srcf_seal(), computer_session::action_terminate(), timed_event::actualize(), Character::add_addiction(), Creature::add_effect(), Character::apply_damage(), cata_event_dispatch::avatar_moves(), Character::bionics_install_failure(), game::bury_screen(), activity_handlers::butcher_finish(), player_activity::canceled(), cast_spell(), spell::cast_spell_effect(), Character::check_needs_extremes(), turn_handler::cleanup_at_end(), Character::consume(), avatar::control_npc(), debug_menu::debug(), mattack::dermatik(), stats_tracker::deserialize(), npc::die(), player_activity::do_turn(), construct::done_dig_grave(), construct::done_dig_grave_nospawn(), construct::done_digormine_stair(), construct::done_grave(), eat(), eff_fun_datura(), eff_fun_hypovolemia(), eff_fun_redcells_anemia(), eff_fun_teleglow(), npc::evaluate_best_attack(), vehicle::explode_fuel(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_trigger_event(), computer_session::failure_alarm(), Character::fall_asleep(), hacking_activity_actor::finish(), read_activity_actor::finish(), chop_tree_activity_actor::finish(), Character::fire_gun(), known_magic::forget_spell(), spell::gain_exp(), prying_activity_actor::handle_prying(), Character::hardcoded_effects(), Character::heal(), talk_function::hostile(), Character::hurtall(), game::is_game_over(), known_magic::learn_spell(), game::load(), main(), iuse::marloss(), marloss_common(), iuse::marloss_gel(), iuse::marloss_seed(), Character::mend(), iuse::mininuke(), Creature::mod_part_hp_cur(), Character::mutate_towards(), iuse::mycus(), read_activity_actor::npc_read(), vehicle::on_move(), iexamine::pedestal_wyrm(), Character::perform_install(), Character::perform_uninstall(), read_activity_actor::player_read(), Character::practice(), Character::practice_proficiency(), Creature::process_effects(), iuse::purify_smart(), avatar::read(), Character::rem_addiction(), Creature::remove_effect(), Character::remove_mutation(), Character::remove_weapon(), game::save(), send(), Creature::set_part_hp_cur(), known_magic::set_spell_exp(), known_magic::set_spell_level(), iuse::sewage(), smash(), activity_handlers::spellcasting_finish(), try_sleep_activity_actor::start(), game::start_game(), player_activity::start_or_resume(), teleport::teleport_to_point(), Character::test_crossing_threshold(), Character::throw_item(), Character::toggle_trait(), trap::trigger(), Character::unset_all_mutations(), Character::vomit(), Character::wake_up(), and npc::wield().
send_with_talker() [1/2]
void event_bus::send_with_talker (Creature * alpha, Creature * beta, const cata::event & e) const
Definition at line 85 of file event_bus.cpp.
 {
     for( event_subscriber *s : subscribers ) {
         s->notify( e, get_talker_for( alpha ), get_talker_for( beta ) );
     }
 }
References get_talker_for(), and subscribers.
Referenced by debug_menu::character_edit_menu(), monster::die(), Character::fire_gun(), Character::melee_attack_abstract(), npc::starting_weapon(), Character::wear(), outfit::wear_item(), npc::wield(), avatar::wield(), and Character::wield_contents().
send_with_talker() [2/2]
void event_bus::send_with_talker (Creature * alpha, item_location * beta, const cata::event & e) const
Definition at line 93 of file event_bus.cpp.
 {
     for( event_subscriber *s : subscribers ) {
         s->notify( e, get_talker_for( alpha ), get_talker_for( beta ) );
     }
 }
References get_talker_for(), and subscribers.
subscribe()
void event_bus::subscribe (event_subscriber * s)
Definition at line 55 of file event_bus.cpp.
 {
     subscribers.push_back( s );
     s->on_subscribe( this );
 }
References event_subscriber::on_subscribe(), and subscribers.
Referenced by game::game().
unsubscribe()
void event_bus::unsubscribe (event_subscriber * s)
Definition at line 61 of file event_bus.cpp.
 {
     auto it = std::find( subscribers.begin(), subscribers.end(), s );
     if( it == subscribers.end() ) {
         debugmsg( "Trying to remove subscriber that isn't there" );
     } else {
         ( *it )->on_unsubscribe( this );
         subscribers.erase( it );
     }
 }
References debugmsg, and subscribers.
Referenced by ~event_bus(), and event_subscriber::~event_subscriber().
Member Data Documentation
subscribers
std::vector<event_subscriber *> event_bus::subscribers private
Definition at line 32 of file event_bus.h.
Referenced by send(), send_with_talker(), subscribe(), unsubscribe(), and ~event_bus().
The documentation for this class was generated from the following files:
src/event_bus.h
src/event_bus.cpp