Cataclysm DDA: jmapgen_toilet Class Reference
jmapgen_toilet Class Reference
Place a toilet with (dirty) water in it.
Public Member Functions
jmapgen_toilet (const JsonObject &jsi, const std::string_view)
mapgen_phase phase () const override
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &p) const override
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
Public Attributes
jmapgen_int amount
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a toilet with (dirty) water in it.
"amount": number of water charges to place.
Definition at line 2104 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_toilet()
jmapgen_toilet::jmapgen_toilet (const JsonObject & jsi, const std::string_view) inline
Definition at line 2108 of file mapgen.cpp.
                                                                        :
             amount( jsi, "amount", 0, 0 ) {
         }
Member Function Documentation
apply()
void jmapgen_toilet::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2114 of file mapgen.cpp.
{
             const tripoint_bub_ms r( x.get(), y.get(), dat.zlevel() + z.get() );
             const int charges = amount.get();
             dat.m.furn_set( r, furn_str_id::NULL_ID() );
             if( charges == 0 ) {
                 dat.m.place_toilet( r ); // Use the default charges supplied as default values
             } else {
                 dat.m.place_toilet( r, charges );
             }
         }
References amount, map::furn_set(), jmapgen_int::get(), mapgendata::m, string_id< furn_t >::NULL_ID(), map::place_toilet(), and mapgendata::zlevel().
has_vehicle_collision()
bool jmapgen_toilet::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & p) const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2125 of file mapgen.cpp.
{
             return dat.m.veh_at( tripoint_bub_ms( p.x(), p.y(), dat.zlevel() + p.z() ) ).has_value();
         }
References mapgendata::m, map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
phase()
mapgen_phase jmapgen_toilet::phase () const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 2111 of file mapgen.cpp.
{
             return mapgen_phase::furniture;
         }
References furniture.
Member Data Documentation
amount
jmapgen_int jmapgen_toilet::amount
Definition at line 2107 of file mapgen.cpp.
Referenced by apply().
The documentation for this class was generated from the following file:
src/mapgen.cpp