Cataclysm DDA: talker_avatar Class Reference
talker_avatar Class Reference
#include <talker_avatar.h>
Public Member Functions
talker_avatar (avatar *new_me)
~talker_avatar () override=default
std::vector< std::string > get_topics (bool) override
int parse_mod (const std::string &attribute, int factor) const override
int trial_chance_mod (const std::string &trial_type) const override
bool buy_monster (talker &seller, const mtype_id &mtype, int cost, int count, bool pacified, const translation &name) override
Public Member Functions inherited from talker_cloner< talker_avatar, talker_character >
std::unique_ptr< talker > clone () const override
Public Member Functions inherited from talker_character
talker_character (Character *new_me)
~talker_character () override=default
Character * get_character () override
const Character * get_character () const override
Creature * get_creature () override
const Creature * get_creature () const override
void set_pos (tripoint new_pos) override
void set_str_max (int value) override
void set_dex_max (int value) override
void set_int_max (int value) override
void set_per_max (int value) override
void set_str_bonus (int value) override
void set_dex_bonus (int value) override
void set_int_bonus (int value) override
void set_per_bonus (int value) override
void set_power_cur (units::energy value) override
void set_mana_cur (int value) override
void set_spell_level (const spell_id &, int) override
void set_spell_exp (const spell_id &, int) override
void set_proficiency_practiced_time (const proficiency_id &prof, int turns) override
void train_proficiency_for (const proficiency_id &prof, int turns) override
void mutate (const int &highest_cat_chance, const bool &use_vitamins) override
void mutate_category (const mutation_category_id &mut_cat, const bool &use_vitamins) override
void mutate_towards (const trait_id &trait, const mutation_category_id &mut_cat, const bool &use_vitamins) override
void set_mutation (const trait_id &new_trait, const mutation_variant *=nullptr) override
void unset_mutation (const trait_id &old_trait) override
void activate_mutation (const trait_id &trait) override
void deactivate_mutation (const trait_id &trait) override
void set_skill_level (const skill_id &skill, int value) override
void set_skill_exp (const skill_id &skill, int value, bool raw=false) override
void learn_recipe (const recipe_id &recipe_to_learn) override
void forget_recipe (const recipe_id &recipe_to_forget) override
void add_effect (const efftype_id &new_effect, const time_duration &dur, const std::string &bp, bool permanent, bool force, int intensity) override
void remove_effect (const efftype_id &old_effect, const std::string &bp) override
void set_value (const std::string &var_name, const std::string &value) override
void remove_value (const std::string &var_name) override
std::vector< item * > items_with (const std::function< bool(const item &)> &filter) const override
std::list< item > use_charges (const itype_id &item_name, int count) override
std::list< item > use_charges (const itype_id &item_name, int count, bool in_tools) override
std::list< item > use_amount (const itype_id &item_name, int count) override
void i_add (const item &new_item) override
void i_add_or_drop (item &new_item, bool force_equip=false) override
void remove_items_with (const std::function< bool(const item &)> &filter) override
void set_stored_kcal (int value) override
void set_thirst (int value) override
void shout (const std::string &speech="", bool order=false) override
void set_sleepiness (int amount) override
void mod_pain (int amount) override
void set_pain (int amount) override
void mod_daily_health (int, int) override
void add_morale (const morale_type &new_morale, int bonus, int max_bonus, time_duration duration, time_duration decay_started, bool capped) override
void remove_morale (const morale_type &old_morale) override
void set_addiction_turns (const addiction_id &add_id, int amount) override
void mod_focus (int) override
void set_rad (int) override
void set_stim (int) override
void set_pkill (int) override
void set_stamina (int) override
void set_sleep_deprivation (int) override
void set_kill_xp (int) override
void set_age (int) override
void set_height (int) override
void add_bionic (const bionic_id &new_bionic) override
void remove_bionic (const bionic_id &old_bionic) override
std::vector< bodypart_id > get_all_body_parts (get_body_part_flags flags) const override
int get_part_hp_cur (const bodypart_id &id) const override
int get_part_hp_max (const bodypart_id &id) const override
void set_all_parts_hp_cur (int) const override
void set_part_hp_cur (const bodypart_id &id, int set) const override
bool get_is_alive () const override
void die () override
void attack_target (Creature &t, bool allow_special, const matec_id &force_technique, bool allow_unarmed, int forced_movecost) override
matec_id get_random_technique (Creature &t, bool crit, bool dodge_counter, bool block_counter, const std::vector< matec_id > &blacklist={}) const override
void learn_martial_art (const matype_id &id) const override
void forget_martial_art (const matype_id &id) const override
Public Member Functions inherited from talker_character_const
talker_character_const (const Character *new_me)
~talker_character_const () override=default
std::string disp_name () const override
std::string get_name () const override
character_id getID () const override
bool is_male () const override
std::vector< std::string > get_grammatical_genders () const override
int posx () const override
int posy () const override
int posz () const override
tripoint pos () const override
tripoint_abs_ms global_pos () const override
tripoint_abs_omt global_omt_location () const override
int get_cur_hp (const bodypart_id &bp) const override
int get_hp_max (const bodypart_id &bp) const override
units::temperature get_cur_part_temp (const bodypart_id &bp) const override
int str_cur () const override
int dex_cur () const override
int int_cur () const override
int per_cur () const override
int attack_speed () const override
int pain_cur () const override
int perceived_pain_cur () const override
double armor_at (damage_type_id &dt, bodypart_id &bp) const override
int coverage_at (bodypart_id &) const override
int encumbrance_at (bodypart_id &) const override
int get_str_max () const override
int get_dex_max () const override
int get_int_max () const override
int get_per_max () const override
int get_str_bonus () const override
int get_dex_bonus () const override
int get_int_bonus () const override
int get_per_bonus () const override
units::energy power_cur () const override
units::energy power_max () const override
int mana_cur () const override
int mana_max () const override
bool has_trait (const trait_id &trait_to_check) const override
bool has_recipe (const recipe_id &recipe_to_check) const override
bool has_flag (const json_character_flag &trait_flag_to_check) const override
bool has_species (const species_id &species) const override
bool bodytype (const bodytype_id &bt) const override
bool crossed_threshold () const override
int num_bionics () const override
bool has_max_power () const override
bool has_bionic (const bionic_id &bionics_id) const override
bool knows_spell (const spell_id &sp) const override
int get_skill_level (const skill_id &) const override
int get_skill_exp (const skill_id &skill, bool raw=false) const override
int get_spell_level (const trait_id &) const override
int get_spell_level (const spell_id &) const override
int get_spell_exp (const spell_id &) const override
int get_highest_spell_level () const override
int get_spell_count (const trait_id &) const override
int get_spell_sum (const trait_id &school, int min_level) const override
bool knows_proficiency (const proficiency_id &proficiency) const override
time_duration proficiency_practiced_time (const proficiency_id &) const override
bool has_effect (const efftype_id &effect_id, const bodypart_id &bp) const override
effect get_effect (const efftype_id &effect_id, const bodypart_id &bp) const override
bool is_deaf () const override
bool is_mute () const override
std::optional< std::string > maybe_get_value (const std::string &var_name) const override
std::vector< skill_id > skills_teacheable () const override
std::vector< skill_id > skills_offered_to (const talker &student) const override
std::string skill_seminar_text (const skill_id &s) const override
std::string skill_training_text (const talker &, const skill_id &) const override
std::vector< proficiency_id > proficiencies_teacheable () const override
std::vector< proficiency_id > proficiencies_offered_to (const talker &student) const override
std::string proficiency_seminar_text (const proficiency_id &) const override
std::string proficiency_training_text (const talker &student, const proficiency_id &proficiency) const override
std::vector< matype_id > styles_teacheable () const override
std::vector< matype_id > styles_offered_to (const talker &student) const override
std::string style_seminar_text (const matype_id &) const override
std::string style_training_text (const talker &, const matype_id &) const override
std::vector< spell_id > spells_teacheable () const override
std::vector< spell_id > spells_offered_to (talker &student) const override
std::string spell_seminar_text (const spell_id &) const override
std::string spell_training_text (talker &, const spell_id &) const override
bool is_wearing (const itype_id &item_id) const override
int charges_of (const itype_id &item_id) const override
bool has_charges (const itype_id &item_id, int count) const override
bool has_charges (const itype_id &item_id, int count, bool in_tools) const override
bool has_amount (const itype_id &item_id, int count) const override
int get_amount (const itype_id &item_id) const override
int cash () const override
std::vector< const item * > const_items_with (const std::function< bool(const item &)> &filter) const override
bool unarmed_attack () const override
bool can_stash_weapon () const override
bool has_stolen_item (const talker &guy) const override
faction * get_faction () const override
std::string short_description () const override
bool has_activity () const override
bool is_mounted () const override
int get_activity_level () const override
int get_sleepiness () const override
int get_hunger () const override
int get_thirst () const override
int get_instant_thirst () const override
int get_stored_kcal () const override
int get_healthy_kcal () const override
int get_size () const override
bool is_in_control_of (const vehicle &veh) const override
bool worn_with_flag (const flag_id &flag, const bodypart_id &bp) const override
bool wielded_with_flag (const flag_id &flag) const override
bool wielded_with_weapon_category (const weapon_category_id &w_cat) const override
bool has_item_with_flag (const flag_id &flag) const override
int item_rads (const flag_id &flag, aggregate_type agg_func) const override
bool can_see () const override
bool can_see_location (const tripoint &pos) const override
int morale_cur () const override
int focus_cur () const override
int get_rad () const override
int get_stim () const override
int get_addiction_intensity (const addiction_id &add_id) const override
int get_addiction_turns (const addiction_id &add_id) const override
int get_pkill () const override
int get_stamina () const override
int get_sleep_deprivation () const override
int get_kill_xp () const override
int get_age () const override
int get_height () const override
int get_bmi_permil () const override
int get_weight () const override
const move_mode_id & get_move_mode () const override
int get_fine_detail_vision_mod () const override
int get_health () const override
units::temperature get_body_temp () const override
units::temperature_delta get_body_temp_delta () const override
bool knows_martial_art (const matype_id &id) const override
bool using_martial_art (const matype_id &id) const override
int climate_control_str_heat () const override
int climate_control_str_chill () const override
Public Member Functions inherited from talker
virtual ~talker ()=default
virtual npc * get_npc ()
virtual npc * get_npc () const
virtual item_location * get_item ()
virtual item_location * get_item () const
virtual monster * get_monster ()
virtual const monster * get_monster () const
virtual computer * get_computer ()
virtual const computer * get_computer () const
virtual std::string distance_to_goal () const
virtual bool will_talk_to_u (const Character &, bool)
virtual void check_missions ()
virtual void update_missions (const std::vector< mission * > &)
virtual bool check_hostile_response (int) const
virtual int get_count () const
virtual int get_grab_strength () const
virtual void store_chosen_training (const skill_id &, const matype_id &, const spell_id &, const proficiency_id &)
virtual std::string get_value (const std::string &key) const
virtual int value (const item &) const
virtual int debt () const
virtual void add_debt (int)
virtual int sold () const
virtual void add_sold (int)
virtual int cash_to_favor (int) const
virtual std::string give_item_to (bool)
virtual bool buy_from (int)
virtual std::vector< mission * > available_missions () const
virtual std::vector< mission * > assigned_missions () const
virtual mission * selected_mission () const
virtual void select_mission (mission *)
virtual void add_mission (const mission_type_id &)
virtual void set_companion_mission (const std::string &)
virtual void set_fac (const faction_id &)
virtual void add_faction_rep (int)
virtual bool is_following () const
virtual bool is_friendly (const Character &) const
virtual bool is_player_ally () const
virtual bool turned_hostile () const
virtual bool is_enemy () const
virtual void make_angry ()
virtual bool has_ai_rule (const std::string &, const std::string &) const
virtual void toggle_ai_rule (const std::string &, const std::string &)
virtual void set_ai_rule (const std::string &, const std::string &)
virtual void clear_ai_rule (const std::string &, const std::string &)
virtual std::string get_job_description () const
virtual std::string evaluation_by (const talker &) const
virtual std::string view_personality_traits () const
virtual bool is_myclass (const npc_class_id &) const
virtual void set_class (const npc_class_id &)
virtual void say (const std::string &)
virtual bool enslave_mind ()
virtual std::string opinion_text () const
virtual void add_opinion (const npc_opinion &)
virtual void set_first_topic (const std::string &)
virtual bool is_safe () const
virtual int get_anger () const
virtual void set_anger (int)
virtual void set_morale (int)
virtual int get_friendly () const
virtual void set_friendly (int)
virtual int get_volume () const
virtual void set_npc_trust (int)
virtual int get_npc_trust () const
virtual void set_npc_fear (int)
virtual int get_npc_fear () const
virtual void set_npc_value (int)
virtual int get_npc_value () const
virtual void set_npc_anger (int)
virtual int get_npc_anger () const
Additional Inherited Members
Protected Member Functions inherited from talker_character
talker_character ()=default
Protected Member Functions inherited from talker_character_const
talker_character_const ()=default
Protected Attributes inherited from talker_character
Character * me_chr
Protected Attributes inherited from talker_character_const
const Character * me_chr_const
Detailed Description
Definition at line 18 of file talker_avatar.h.
Constructor & Destructor Documentation
talker_avatar()
talker_avatar::talker_avatar (avatar * new_me) explicit
Definition at line 27 of file talker_avatar.cpp.
 {
     me_chr = new_me;
     me_chr_const = new_me;
 }
References talker_character::me_chr, and talker_character_const::me_chr_const.
~talker_avatar()
talker_avatar::~talker_avatar () override default
Member Function Documentation
buy_monster()
bool talker_avatar::buy_monster (talker & seller, const mtype_id & mtype, int cost, int count, bool pacified, const translation & name) override virtual
Reimplemented from talker.
Definition at line 67 of file talker_avatar.cpp.
 {
     npc *seller_guy = seller.get_npc();
     if( !seller_guy ) {
         popup( _( "%s can't sell you any %s" ), seller.disp_name(), mtype.obj().nname( 2 ) );
         return false;
     }
     if( cost > 0 && !npc_trading::pay_npc( *seller_guy, cost ) ) {
         popup( _( "You can't afford it!" ) );
         return false;
     }
     for( int i = 0; i < count; i++ ) {
         monster *const mon_ptr = g->place_critter_around( mtype, me_chr->pos(), 3 );
         if( !mon_ptr ) {
             add_msg_debug( debugmode::DF_TALKER, "Cannot place u_buy_monster, no valid placement locations." );
             break;
         }
         monster &tmp = *mon_ptr;
         // Our monster is always a pet.
         tmp.friendly = -1;
         tmp.add_effect( effect_pet, 1_turns, true );
         if( pacified ) {
             tmp.add_effect( effect_pacified, 1_turns, true );
         }
         if( !name.empty() ) {
             tmp.unique_name = name.translated();
         }
     }
     if( name.empty() ) {
         popup( _( "%1$s gives you %2$d %3$s." ), seller_guy->get_name(),
                count, mtype.obj().nname( count ) );
     } else {
         popup( _( "%1$s gives you %2$s." ), seller_guy->get_name(), name );
     }
     return true;
 }
References _, Creature::add_effect(), add_msg_debug, debugmode::DF_TALKER, talker::disp_name(), effect_pacified, effect_pet, monster::friendly, g, Character::get_name(), talker::get_npc(), talker_character::me_chr, om_direction::name(), mtype::nname(), npc_trading::pay_npc(), popup(), Creature::pos(), and monster::unique_name.
get_topics()
std::vector< std::string > talker_avatar::get_topics (bool) override virtual
Reimplemented from talker.
Definition at line 33 of file talker_avatar.cpp.
 {
     std::vector<std::string> add_topics;
     if( has_trait( trait_PROF_FOODP ) && !( is_wearing( itype_foodperson_mask ) ||
                                             is_wearing( itype_foodperson_mask_on ) ) ) {
         add_topics.emplace_back( "TALK_NOFACE" );
     }
     return add_topics;
 }
References talker_character_const::has_trait(), talker_character_const::is_wearing(), itype_foodperson_mask, itype_foodperson_mask_on, and trait_PROF_FOODP.
parse_mod()
int talker_avatar::parse_mod (const std::string & attribute, int factor) const override virtual
Reimplemented from talker.
Definition at line 43 of file talker_avatar.cpp.
 {
     int modifier = 0;
     if( attribute == "U_INTIMIDATE" ) {
         modifier = me_chr->intimidation();
     }
     modifier *= factor;
     return modifier;
 }
References Character::intimidation(), and talker_character::me_chr.
trial_chance_mod()
int talker_avatar::trial_chance_mod (const std::string & trial_type) const override virtual
Reimplemented from talker.
Definition at line 53 of file talker_avatar.cpp.
 {
     int chance = 0;
     const social_modifiers &me_mods = me_chr->get_mutation_bionic_social_mods();
     if( trial_type == "lie" ) {
         chance += me_chr->lie_skill() + me_mods.lie;
     } else if( trial_type == "persuade" ) {
         chance += me_chr->persuade_skill() + me_mods.persuade;
     } else if( trial_type == "intimidate" ) {
         chance += me_chr->intimidation() + me_mods.intimidate;
     }
     return chance;
 }
References Character::get_mutation_bionic_social_mods(), social_modifiers::intimidate, Character::intimidation(), social_modifiers::lie, Character::lie_skill(), talker_character::me_chr, social_modifiers::persuade, and Character::persuade_skill().
The documentation for this class was generated from the following files:
src/talker_avatar.h
src/talker_avatar.cpp