Cataclysm DDA: game::debug_hour_timer Class Reference
game::debug_hour_timer Class Reference
Public Types
using IRLTimeMs = std::chrono::time_point< std::chrono::steady_clock, std::chrono::milliseconds >
Public Member Functions
void toggle ()
void print_time ()
Private Attributes
bool enabled = false
std::optional< IRLTimeMs > start_time = std::nullopt
Detailed Description
Definition at line 1039 of file game.h.
Member Typedef Documentation
IRLTimeMs
using game::debug_hour_timer::IRLTimeMs = std::chrono::time_point<std::chrono::steady_clock, std::chrono::milliseconds>
Definition at line 1042 of file game.h.
Member Function Documentation
print_time()
void game::debug_hour_timer::print_time ()
Definition at line 12982 of file game.cpp.
 {
     if( enabled ) {
         if( calendar::once_every( time_duration::from_hours( 1 ) ) ) {
             const IRLTimeMs now = std::chrono::time_point_cast<std::chrono::milliseconds>(
                                       std::chrono::steady_clock::now() );
             if( start_time ) {
                 add_msg( "in-game hour took: %d ms", ( now - *start_time ).count() );
             } else {
                 add_msg( "starting debug timer" );
             }
             start_time = now;
         }
     }
 }
References add_msg(), enabled, time_duration::from_hours(), and calendar::once_every().
toggle()
void game::debug_hour_timer::toggle ()
Definition at line 12975 of file game.cpp.
 {
     enabled = !enabled;
     start_time = std::nullopt;
     add_msg( string_format( "debug timer %s", enabled ? "enabled" : "disabled" ) );
 }
References add_msg(), enabled, and string_format().
Referenced by game::toggle_debug_hour_timer().
Member Data Documentation
enabled
bool game::debug_hour_timer::enabled = false private
Definition at line 1046 of file game.h.
start_time
std::optional<IRLTimeMs> game::debug_hour_timer::start_time = std::nullopt private
Definition at line 1047 of file game.h.
The documentation for this class was generated from the following files:
src/game.h
src/game.cpp