Cataclysm DDA: creature_tracker Class Reference
creature_tracker Class Reference
#include <creature_tracker.h>
Public Member Functions
creature_tracker ()
~creature_tracker ()
shared_ptr_fast< monster > find (const tripoint_abs_ms &pos) const
Returns the monster at the given location.
template<typename PredicateFn >
Creature * find_reachable (const Creature &origin, PredicateFn &&predicate_fn)
Returns the reachable creature matching the given predicate.
template<typename FactionPredicateFn , typename CreaturePredicateFn >
Creature * find_reachable (const Creature &origin, FactionPredicateFn &&faction_fn, CreaturePredicateFn &&creature_fn)
Returns the reachable creature matching the given predicates.
template<typename VisitFn >
void for_each_reachable (const Creature &origin, VisitFn &&visit_fn)
Visits all reachable creatures using the given functor.
template<typename FactionPredicateFn , typename CreatureVisitFn >
void for_each_reachable (const Creature &origin, FactionPredicateFn &&faction_fn, CreatureVisitFn &&creature_fn)
Visits all reachable creatures using the given functor matching the given predicate.
int temporary_id (const monster &critter) const
Returns a temporary id of the given monster (which must exist in the tracker).
shared_ptr_fast< monster > from_temporary_id (int id)
bool add (const shared_ptr_fast< monster > &critter)
Adds the given monster to the tracker.
size_t size () const
bool update_pos (const monster &critter, const tripoint_abs_ms &old_pos, const tripoint_abs_ms &new_pos)
Updates the position of the given monster to the given point.
void remove (const monster &critter)
Removes the given monster from the Creature tracker, adjusting other entries as needed.
void clear ()
void clear_npcs ()
void swap_positions (monster &first, monster &second)
Swaps the positions of two monsters.
bool kill_marked_for_death ()
Kills 0 hp monsters.
void remove_dead ()
Removes dead monsters from.
template<typename T = Creature>
T * creature_at (const tripoint &p, bool allow_hallucination=false)
Returns the Creature at the given location.
template<typename T = Creature>
T * creature_at (const tripoint_bub_ms &p, bool allow_hallucination=false)
template<typename T = Creature>
T * creature_at (const tripoint_abs_ms &p, bool allow_hallucination=false)
template<typename T = Creature>
const T * creature_at (const tripoint &p, bool allow_hallucination=false) const
template<typename T = Creature>
const T * creature_at (const tripoint_bub_ms &p, bool allow_hallucination=false) const
template<typename T = Creature>
const T * creature_at (const tripoint_abs_ms &p, bool allow_hallucination=false) const
const std::vector< shared_ptr_fast< monster > > & get_monsters_list () const
void serialize (JsonOut &jsout) const
void deserialize (const JsonArray &ja)
void invalidate_reachability_cache ()
Private Member Functions
void remove_from_location_map (const monster &critter)
Remove the monsters entry in monsters_by_location.
void flood_fill_zone (const Creature &origin)
This is lazily evaluated on demand.
void rebuild_cache ()
bool is_present (Creature *creature) const
Private Attributes
std::list< shared_ptr_fast< npc > > active_npc
std::vector< shared_ptr_fast< monster > > monsters_list
std::unordered_map< tripoint_abs_ms, shared_ptr_fast< monster > > monsters_by_location
std::unordered_set< shared_ptr_fast< monster > > removed_this_turn_
Creatures that get removed via remove are stored here until the end of the turn.
bool dirty_ = true
int zone_tick_ = 1
int zone_number_ = 0
std::unordered_map< int, std::unordered_map< mfaction_id, std::vector< shared_ptr_fast< Creature > > > > creatures_by_zone_and_faction_
friend game
Detailed Description
Definition at line 24 of file creature_tracker.h.
Constructor & Destructor Documentation
creature_tracker()
creature_tracker::creature_tracker () default
~creature_tracker()
creature_tracker::~creature_tracker () default
Member Function Documentation
add()
bool creature_tracker::add (const shared_ptr_fast< monster > & critter)
Adds the given monster to the tracker.
critter must not be null. If the operation succeeded, the monster pointer is now managed by this tracker.
Returns
Whether the operation was successful. It may fail if there is already another monster at the location of the new monster.
Definition at line 68 of file creature_tracker.cpp.
 {
     cata_assert( critter_ptr );
     monster &critter = *critter_ptr;
     if( critter.type->id.is_null() ) { // Don't want to spawn null monsters o.O
         return false;
     }
     if( critter.type->has_flag( mon_flag_VERMIN ) ) {
         // Don't spawn vermin, they aren't implemented yet
         return false;
     }
     if( const shared_ptr_fast<monster> existing_mon_ptr = find( critter.get_location() ) ) {
         // We can spawn stuff on hallucinations, but we need to kill them first
         if( existing_mon_ptr->is_hallucination() ) {
             existing_mon_ptr->die( nullptr );
             // But don't remove - that would change the monster order and could segfault
         } else if( critter.is_hallucination() ) {
             return false;
         } else {
             debugmsg( "there's already a monster at %s", critter.get_location().to_string_writable() );
             return false;
         }
     }
     if( MonsterGroupManager::monster_is_blacklisted( critter.type->id ) ) {
         return false;
     }
     monsters_list.emplace_back( critter_ptr );
     monsters_by_location[critter.get_location()] = critter_ptr;
     return true;
 }
References cata_assert, debugmsg, monster::die(), find(), Creature::get_location(), mtype::has_flag(), mtype::id, monster::is_hallucination(), string_id< T >::is_null(), mon_flag_VERMIN, MonsterGroupManager::monster_is_blacklisted(), monsters_by_location, monsters_list, coords::coord_point_base< Point >::to_string_writable(), and monster::type.
Referenced by deserialize().
clear()
void creature_tracker::clear ()
Definition at line 184 of file creature_tracker.cpp.
 {
     monsters_list.clear();
     monsters_by_location.clear();
     removed_this_turn_.clear();
     creatures_by_zone_and_faction_.clear();
     invalidate_reachability_cache();
 }
References creatures_by_zone_and_faction_, invalidate_reachability_cache(), monsters_by_location, monsters_list, and removed_this_turn_.
clear_npcs()
void creature_tracker::clear_npcs () inline
Definition at line 97 of file creature_tracker.h.
{
             active_npc.clear();
         }
References active_npc.
creature_at() [1/6]
template<typename T > T * creature_tracker::creature_at (const tripoint & p, bool allow_hallucination = false)
Returns the Creature at the given location.
Optionally casted to the given type of creature: npc, player, monster - if there is a creature, but it's not of the requested type, returns nullptr.
Parameters
allow_hallucination Whether to return monsters that are actually hallucinations.
Definition at line 303 of file creature_tracker.cpp.
 {
     return creature_at<T>( get_map().getglobal( p ), allow_hallucination );
 }
References get_map().
Referenced by target_ui::action_aim_and_shoot(), computer_session::action_terminate(), add_effect_to_target(), Character::adjacent_tile(), npc_attack_melee::all_evaluations(), npc_attack_gun::all_evaluations(), npc_attack_throw::all_evaluations(), npc::alt_attack(), jmapgen_setmap::apply(), monster::attack_at(), monster::attack_target(), spell_effect::banishment(), monster::bash_at(), mattack::breathe(), calculate_aim_cap(), mon_spellcasting_actor::call(), melee_actor::call(), iuse::camera(), computer_session::can_activate(), vehicle::can_close(), can_examine_at(), iuse::can_goo(), game::can_move_furniture(), can_place_monster(), can_place_npc(), shearing_activity_actor::canceled(), iuse::capture_monster_act(), debug_menu::character_edit_menu(), spell_effect::charm_monster(), vehicle::autodrive_controller::check_drivable(), vehicle::check_heli_ascend(), vehicle::check_heli_descend(), clear_shot_reach(), doors::close_door(), map::collapse_at(), veh_interact::complete_vehicle(), item::contain_monster(), map::crush(), damage_targets(), spell_effect::dash(), monster::die(), spell_effect::directed_push(), game::disable_robot(), map::displace_vehicle(), game::display_visibility(), explosion_handler::do_blast(), milk_activity_actor::do_turn(), disable_activity_actor::do_turn(), stash_activity_actor::do_turn(), glide_activity_actor::do_turn(), editmap_hilight::draw(), anonymous_namespace{animation.cpp}::draw_line_curses(), game::draw_look_around_cursor(), editmap::draw_main_ui_overlay(), draw_throw_aim(), map::drop_furniture(), map::drop_items(), Character::echo_pulse(), editmap::edit(), eff_fun_teleglow(), spell_effect::effect_on_condition(), effects_description_for_creature(), iuse::emf_passive_on(), npc_attack_melee::evaluate(), npc_attack_gun::evaluate(), npc_attack_throw::evaluate(), npc_attack_spell::evaluate_tripoint(), npc_attack_gun::evaluate_tripoint(), npc_attack_throw::evaluate_tripoint(), game::examine(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), climbing_aid::fall_scan::fall_scan(), field_processor_fd_last_known(), field_processor_fd_push_items(), activity_handlers::fill_liquid_do_turn(), find_empty_spot_nearby(), game::find_or_make_stairs(), milk_activity_actor::finish(), shearing_activity_actor::finish(), chop_tree_activity_actor::finish(), disable_activity_actor::finish(), game::fling_creature(), game::forced_door_closing(), mattack::formblob(), iuse::fungicide(), map::furn_set(), map::get_creatures_in_radius(), vehicle::get_monster(), get_patient(), game::get_player_input(), vehicle::get_riders(), iuse::granade_act(), monster::group_bash_skill(), mattack::growplants(), spell_effect::guilt(), npc::handle_sound(), Character::hardcoded_effects(), has_obstruction(), has_vine_parent(), spell::heal(), Character::impact(), npc::is_active(), game::is_empty(), Character::knock_back_to(), monster::knock_back_to(), game::knockback(), iexamine::ledge(), trapfunc::ledge(), target_ui::list_friendlies_in_lof(), Creature::longpull(), game::look_around(), talk_function::loot_building(), spell_effect::mod_moves(), spell_effect::morale(), monster::move(), avatar_action::move(), veh_interact::move_cursor(), monster::move_effects(), monster::move_to(), npc::move_to(), mtrap_set(), spell_effect::mutate(), monster::nursebot_operate(), vehicle::part_collision(), iuse::petfood(), game::phasing_move(), photo_def_for_camera_point(), vehicle::precollision_check(), game::print_all_tile_info(), monster::process_effects(), monster::process_turn(), projectile_attack(), monster::push_to(), spell::random_valid_target(), Character::reach_attack(), spell_effect::recover_energy(), npc::regen_ai_cache(), spell_effect::remove_effect(), mattack::resurrect(), route_best_workbench(), mattack::searchlight(), seen_critter(), target_ui::set_cursor_pos(), mattack::shriek_stun(), map::spawn_monsters_submap(), map::spawn_monsters_submap_group(), spawn_spores(), Character::stagger(), shearing_activity_actor::start(), disable_activity_actor::start(), monster::stumble(), game::swap_critters(), swap_pos(), Target_attributes::Target_attributes(), iuse::tazer(), map::ter_set(), Character::throw_item(), teleporter_list::translocate(), mattack::triffid_heartbeat(), target_ui::try_reacquire_target(), Character::try_remove_grab(), editmap::uber_draw_ter(), map::unboard_vehicle(), editmap::update_view_with_help(), spell_effect::upgrade(), deploy_tent_actor::use(), npc_attack_melee::use(), vehicle::use_harness(), game::vertical_move(), mattack::vine(), spell_effect::vomit(), suffer::while_grabbed(), npc::worker_downtime(), and mattack::zombie_fuse().
creature_at() [2/6]
template<typename T > const T * creature_tracker::creature_at (const tripoint & p, bool allow_hallucination = false) const
Definition at line 429 of file creature_tracker.cpp.
 {
     return creature_at<T>( get_map().getglobal( p ), allow_hallucination );
 }
References get_map().
creature_at() [3/6]
template<typename T > T * creature_tracker::creature_at (const tripoint_abs_ms & p, bool allow_hallucination = false)
Definition at line 315 of file creature_tracker.cpp.
 {
     if( const shared_ptr_fast<monster> mon_ptr = find( p ) ) {
         if( !allow_hallucination && mon_ptr->is_hallucination() ) {
             return nullptr;
         }
         // if we wanted to check for an NPC / player / avatar,
         // there is sometimes a monster AND an NPC/player there at the same time.
         // because the NPC/player etc may be riding that monster.
         // so only return the monster if we were actually looking for a monster.
         // otherwise, keep looking for the rider.
         // creature_at<creature> or creature_at() with no template will still default to returning monster first,
         // which is ok for the occasions where that happens.
         if( !mon_ptr->has_effect( effect_ridden ) || ( std::is_same<T, monster>::value ||
                 std::is_same<T, Creature>::value || std::is_same<T, const monster>::value ||
                 std::is_same<T, const Creature>::value ) ) {
             return dynamic_cast<T *>( mon_ptr.get() );
         }
     }
     if( !std::is_same<T, npc>::value && !std::is_same<T, const npc>::value ) {
         avatar &you = get_avatar();
         if( p == you.get_location() ) {
             return dynamic_cast<T *>( &you );
         }
     }
     for( auto &cur_npc : active_npc ) {
         if( cur_npc->get_location() == p && !cur_npc->is_dead() ) {
             return dynamic_cast<T *>( cur_npc.get() );
         }
     }
     return nullptr;
 }
References active_npc, effect_ridden, find(), get_avatar(), and Creature::get_location().
creature_at() [4/6]
template<typename T > const T * creature_tracker::creature_at (const tripoint_abs_ms & p, bool allow_hallucination = false) const
Definition at line 441 of file creature_tracker.cpp.
 {
     return const_cast<creature_tracker *>( this )->creature_at<T>( p, allow_hallucination );
 }
creature_at() [5/6]
template<typename T > T * creature_tracker::creature_at (const tripoint_bub_ms & p, bool allow_hallucination = false)
Definition at line 309 of file creature_tracker.cpp.
 {
     return creature_at<T>( get_map().getglobal( p ), allow_hallucination );
 }
References get_map().
creature_at() [6/6]
template<typename T > const T * creature_tracker::creature_at (const tripoint_bub_ms & p, bool allow_hallucination = false) const
Definition at line 435 of file creature_tracker.cpp.
 {
     return creature_at<T>( get_map().getglobal( p ), allow_hallucination );
 }
References get_map().
deserialize()
void creature_tracker::deserialize (const JsonArray & ja)
Definition at line 1682 of file savegame.cpp.
 {
     monsters_list.clear();
     monsters_by_location.clear();
     for( JsonValue jv : ja ) {
         // TODO: would be nice if monster had a constructor using JsonIn or similar, so this could be one statement.
         shared_ptr_fast<monster> mptr = make_shared_fast<monster>();
         jv.read( *mptr );
         add( mptr );
     }
 }
References add(), monsters_by_location, and monsters_list.
find()
shared_ptr_fast< monster > creature_tracker::find (const tripoint_abs_ms & pos) const
Returns the monster at the given location.
If there is no monster, it returns a nullptr. Dead monsters are ignored and not returned.
Definition at line 35 of file creature_tracker.cpp.
 {
     const auto iter = monsters_by_location.find( pos );
     if( iter != monsters_by_location.end() ) {
         const shared_ptr_fast<monster> &mon_ptr = iter->second;
         if( !mon_ptr->is_dead() ) {
             return mon_ptr;
         }
     }
     return nullptr;
 }
References monsters_by_location, and math_opers::pos().
Referenced by add(), creature_at(), vehicle::part_collision(), and update_pos().
find_reachable() [1/2]
template<typename FactionPredicateFn , typename CreaturePredicateFn > Creature * creature_tracker::find_reachable (const Creature & origin, FactionPredicateFn && faction_fn, CreaturePredicateFn && creature_fn)
Returns the reachable creature matching the given predicates.
FactionPredicateFn: bool(const mfaction_id&)
CreaturePredicateFn: bool(Creature*) If there is no creature, it returns a nullptr. Dead monsters are ignored and not returned.
Definition at line 189 of file creature_tracker.h.
 {
     flood_fill_zone( origin );
     const auto map_iter = creatures_by_zone_and_faction_.find( origin.get_reachable_zone() );
     if( map_iter != creatures_by_zone_and_faction_.end() ) {
         for( auto& [faction, creatures] : map_iter->second ) {
             if( !faction_fn( faction ) ) {
                 continue;
             }
             for( std::size_t i = 0; i < creatures.size(); ) {
                 if( Creature *other = creatures[i].get(); is_present( other ) ) {
                     if( creature_fn( other ) ) {
                         return other;
                     }
                     ++i;
                 } else {
                     using std::swap;
                     swap( creatures[i], creatures.back() );
                     creatures.pop_back();
                 }
             }
         }
     }
     return nullptr;
 }
References creatures_by_zone_and_faction_, flood_fill_zone(), rotatable_symbols::get(), is_present(), other, and cata::swap().
find_reachable() [2/2]
template<typename PredicateFn > Creature * creature_tracker::find_reachable (const Creature & origin, PredicateFn && predicate_fn)
Returns the reachable creature matching the given predicate.
CreaturePredicateFn: bool(Creature*) If there is no creature, it returns a nullptr. Dead monsters are ignored and not returned.
Definition at line 181 of file creature_tracker.h.
 {
     return find_reachable( origin, []( const mfaction_id & ) {
         return true;
     }, std::forward<PredicateFn>( predicate_fn ) );
 }
Referenced by for_each_reachable(), and mattack::parrot_at_danger().
flood_fill_zone()
void creature_tracker::flood_fill_zone (const Creature & origin) private
This is lazily evaluated on demand.
Each creature in a zone is visited as it flood fills, then the zone number is incremented. At the end all creatures in the same zone will have the same zone number assigned, which can be used to have creatures in different zones ignore each other very cheaply.
Definition at line 353 of file creature_tracker.cpp.
 {
     if( dirty_ ) {
         creatures_by_zone_and_faction_.clear();
         zone_tick_ = zone_tick_ > 0 ? -1 : 1;
         zone_number_ = 1;
         dirty_ = false;
     }
     // This check insures we only flood fill when the target monster has an uninitialized zone,
     // or if it has a zone from last turn.  In other words it only triggers on
     // the first monster in a zone each turn. We can detect this because the sign
     // of the zone numbers changes on every invalidation.
     int old_zone = origin.get_reachable_zone();
     // Compare with zone_tick == old_zone && old_zone != 0
     if( old_zone * zone_tick_ > 0 ) {
         return;
     }
     map &map = get_map();
     ff::flood_fill_visit_10_connected( origin.pos_bub(),
     [&map]( const tripoint_bub_ms & loc, int direction ) {
         if( direction == 0 ) {
             return map.inbounds( loc ) && ( map.is_transparent_wo_fields( loc.raw() ) ||
                                             map.passable( loc ) );
         }
         if( direction == 1 ) {
             const maptile &up = map.maptile_at( loc );
             const ter_t &up_ter = up.get_ter_t();
             if( up_ter.id.is_null() ) {
                 return false;
             }
             if( ( ( up_ter.movecost != 0 && up.get_furn_t().movecost >= 0 ) ||
                   map.is_transparent_wo_fields( loc.raw() ) ) &&
                 ( up_ter.has_flag( ter_furn_flag::TFLAG_NO_FLOOR ) ||
                   up_ter.has_flag( ter_furn_flag::TFLAG_GOES_DOWN ) ) ) {
                 return true;
             }
         }
         if( direction == -1 ) {
             const maptile &up = map.maptile_at( loc + tripoint_above );
             const ter_t &up_ter = up.get_ter_t();
             if( up_ter.id.is_null() ) {
                 return false;
             }
             const maptile &down = map.maptile_at( loc );
             const ter_t &down_ter = up.get_ter_t();
             if( down_ter.id.is_null() ) {
                 return false;
             }
             if( ( ( down_ter.movecost != 0 && down.get_furn_t().movecost >= 0 ) ||
                   map.is_transparent_wo_fields( loc.raw() ) ) &&
                 ( up_ter.has_flag( ter_furn_flag::TFLAG_NO_FLOOR ) ||
                   up_ter.has_flag( ter_furn_flag::TFLAG_GOES_DOWN ) ) ) {
                 return true;
             }
         }
         return false;
     },
     [this]( const tripoint_bub_ms & loc ) {
         if( Creature *creature = this->creature_at<Creature>( loc, true ) ) {
             if( shared_ptr_fast<Creature> ptr = g->shared_from( *creature ) ) {
                 const int n = zone_number_ * zone_tick_;
                 creatures_by_zone_and_faction_[n][creature->get_monster_faction()].emplace_back( std::move( ptr ) );
                 creature->set_reachable_zone( n );
             }
         }
     } );
     if( zone_number_ == std::numeric_limits<int>::max() ) {
         zone_number_ = 1;
     } else {
         zone_number_++;
     }
 }
References creatures_by_zone_and_faction_, dirty_, ff::flood_fill_visit_10_connected(), get_map(), map::is_transparent_wo_fields(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), TFLAG_GOES_DOWN, TFLAG_NO_FLOOR, keycode::up, zone_number_, and zone_tick_.
Referenced by find_reachable().
for_each_reachable() [1/2]
template<typename FactionPredicateFn , typename CreatureVisitFn > void creature_tracker::for_each_reachable (const Creature & origin, FactionPredicateFn && faction_fn, CreatureVisitFn && creature_fn)
Visits all reachable creatures using the given functor matching the given predicate.
FactionPredicateFn: bool(const mfaction_id&)
CreatureVisitFn: void(Creature*) Dead monsters are ignored and not visited.
Definition at line 227 of file creature_tracker.h.
 {
     find_reachable( origin, std::forward<FactionPredicateFn>( faction_fn ), [&creature_fn](
     Creature * other ) {
         creature_fn( other );
         return false;
     } );
 }
References find_reachable(), and other.
for_each_reachable() [2/2]
template<typename VisitFn > void creature_tracker::for_each_reachable (const Creature & origin, VisitFn && visit_fn)
Visits all reachable creatures using the given functor.
VisitFn: void(Creature*) Dead monsters are ignored and not visited.
Definition at line 218 of file creature_tracker.h.
 {
     find_reachable( origin, [&visit_fn]( Creature * other ) {
         visit_fn( other );
         return false;
     } );
 }
References find_reachable(), and other.
Referenced by monster::plan().
from_temporary_id()
shared_ptr_fast< monster > creature_tracker::from_temporary_id (int id)
Definition at line 59 of file creature_tracker.cpp.
 {
     if( static_cast<size_t>( id ) < monsters_list.size() ) {
         return monsters_list[id];
     } else {
         return nullptr;
     }
 }
References base_camps::id, and monsters_list.
get_monsters_list()
const std::vector<shared_ptr_fast<monster> >& creature_tracker::get_monsters_list () const inline
Definition at line 128 of file creature_tracker.h.
{
             return monsters_list;
         }
References monsters_list.
invalidate_reachability_cache()
void creature_tracker::invalidate_reachability_cache () inline
Definition at line 138 of file creature_tracker.h.
{
             dirty_ = true;
         }
References dirty_.
Referenced by clear(), map::furn_set(), map::set_transparency_cache_dirty(), swap_positions(), and map::ter_set().
is_present()
bool creature_tracker::is_present (Creature * creature) const private
Definition at line 201 of file creature_tracker.cpp.
 {
     if( creature->is_monster() ) {
         if( const auto iter = monsters_by_location.find( creature->get_location() );
             iter != monsters_by_location.end() ) {
             if( static_cast<const Creature *>( iter->second.get() ) == creature ) {
                 return !iter->second->is_dead();
             }
         }
     } else if( creature->is_avatar() ) {
         return true;
     } else if( creature->is_npc() ) {
         for( const shared_ptr_fast<npc> &cur_npc : active_npc ) {
             if( static_cast<const Creature *>( cur_npc.get() ) == creature ) {
                 return !cur_npc->is_dead();
             }
         }
     }
     return false;
 }
References active_npc, creature, and monsters_by_location.
Referenced by find_reachable().
kill_marked_for_death()
bool creature_tracker::kill_marked_for_death ()
Kills 0 hp monsters.
Returns if it killed any.
Definition at line 263 of file creature_tracker.cpp.
 {
     // Important: `Creature::die` must not be called after creature objects (NPCs, monsters) have
     // been removed, the dying creature could still have a pointer (the killer) to another creature.
     bool monster_is_dead = false;
     // Copy the list so we can iterate the copy safely *and* add new monsters from within monster::die
     // This happens for example with blob monsters (they split into two smaller monsters).
     const auto copy = monsters_list;
     for( const shared_ptr_fast<monster> &mon_ptr : copy ) {
         cata_assert( mon_ptr );
         monster &critter = *mon_ptr;
         if( !critter.is_dead() ) {
             continue;
         }
         dbg( D_INFO ) << string_format( "cleanup_dead: critter at %s hp:%d %s",
                                         critter.get_location().to_string_writable(),
                                         critter.get_hp(), critter.name() );
         critter.die( nullptr );
         monster_is_dead = true;
     }
     return monster_is_dead;
 }
References cata_assert, D_INFO, dbg, monster::die(), monster::get_hp(), Creature::get_location(), monster::is_dead(), monsters_list, monster::name(), string_format(), and coords::coord_point_base< Point >::to_string_writable().
rebuild_cache()
void creature_tracker::rebuild_cache () private
Definition at line 193 of file creature_tracker.cpp.
 {
     monsters_by_location.clear();
     for( const shared_ptr_fast<monster> &mon_ptr : monsters_list ) {
         monsters_by_location[mon_ptr->get_location()] = mon_ptr;
     }
 }
References monsters_by_location, and monsters_list.
Referenced by update_pos().
remove()
void creature_tracker::remove (const monster & critter)
Removes the given monster from the Creature tracker, adjusting other entries as needed.
Definition at line 168 of file creature_tracker.cpp.
 {
     const auto iter = std::find_if( monsters_list.begin(), monsters_list.end(),
     [&]( const shared_ptr_fast<monster> &ptr ) {
         return ptr.get() == &critter;
     } );
     if( iter == monsters_list.end() ) {
         debugmsg( "Tried to remove invalid monster %s", critter.name() );
         return;
     }
     remove_from_location_map( critter );
     removed_this_turn_.emplace( *iter );
     monsters_list.erase( iter );
 }
References debugmsg, monsters_list, monster::name(), remove_from_location_map(), and removed_this_turn_.
remove_dead()
void creature_tracker::remove_dead ()
Removes dead monsters from.
Their pointers are invalidated.
Definition at line 287 of file creature_tracker.cpp.
 {
     // Can't use game::all_monsters() as it would not contain *dead* monsters.
     for( auto iter = monsters_list.begin(); iter != monsters_list.end(); ) {
         monster *const critter = iter->get();
         if( critter->is_dead() ) {
             remove_from_location_map( *critter );
             iter = monsters_list.erase( iter );
         } else {
             ++iter;
         }
     }
     removed_this_turn_.clear();
 }
References monster::is_dead(), monsters_list, remove_from_location_map(), and removed_this_turn_.
remove_from_location_map()
void creature_tracker::remove_from_location_map (const monster & critter) private
Remove the monsters entry in monsters_by_location.
Definition at line 149 of file creature_tracker.cpp.
 {
     const auto pos_iter = monsters_by_location.find( critter.get_location() );
     if( pos_iter != monsters_by_location.end() && pos_iter->second.get() == &critter ) {
         monsters_by_location.erase( pos_iter );
         return;
     }
     // When it's not in the map at its current location, it might still be there under,
     // another location, so look for it.
     const auto iter = std::find_if( monsters_by_location.begin(), monsters_by_location.end(),
     [&]( const decltype( monsters_by_location )::value_type & v ) {
         return v.second.get() == &critter;
     } );
     if( iter != monsters_by_location.end() ) {
         monsters_by_location.erase( iter );
     }
 }
References Creature::get_location(), and monsters_by_location.
Referenced by remove(), remove_dead(), and update_pos().
serialize()
void creature_tracker::serialize (JsonOut & jsout) const
Definition at line 1694 of file savegame.cpp.
 {
     jsout.start_array();
     for( const auto &monster_ptr : monsters_list ) {
         jsout.write( *monster_ptr );
     }
     jsout.end_array();
 }
References JsonOut::end_array(), monsters_list, JsonOut::start_array(), and JsonOut::write().
size()
size_t creature_tracker::size () const
Definition at line 104 of file creature_tracker.cpp.
 {
     return monsters_list.size();
 }
References monsters_list.
swap_positions()
void creature_tracker::swap_positions (monster & first, monster & second)
Swaps the positions of two monsters.
Definition at line 222 of file creature_tracker.cpp.
 {
     if( first.get_location() == second.get_location() ) {
         return;
     }
     if( first.get_reachable_zone() != second.get_reachable_zone() ) {
         invalidate_reachability_cache();
     }
     // Either of them may be invalid!
     const auto first_iter = monsters_by_location.find( first.get_location() );
     const auto second_iter = monsters_by_location.find( second.get_location() );
     // implied: first_iter != second_iter
     shared_ptr_fast<monster> first_ptr;
     if( first_iter != monsters_by_location.end() ) {
         first_ptr = first_iter->second;
         monsters_by_location.erase( first_iter );
     }
     shared_ptr_fast<monster> second_ptr;
     if( second_iter != monsters_by_location.end() ) {
         second_ptr = second_iter->second;
         monsters_by_location.erase( second_iter );
     }
     // implied: (first_ptr != second_ptr) or (first_ptr == nullptr && second_ptr == nullptr)
     const tripoint_abs_ms temp = second.get_location();
     second.spawn( first.get_location() );
     first.spawn( temp );
     // If the pointers have been taken out of the list, put them back in.
     if( first_ptr ) {
         monsters_by_location[first.get_location()] = first_ptr;
     }
     if( second_ptr ) {
         monsters_by_location[second.get_location()] = second_ptr;
     }
 }
References Creature::get_location(), Creature::get_reachable_zone(), invalidate_reachability_cache(), monsters_by_location, second, monster::spawn(), and temp.
temporary_id()
int creature_tracker::temporary_id (const monster & critter) const
Returns a temporary id of the given monster (which must exist in the tracker).
The id is valid until monsters are added or removed from the tracker. The id remains valid through serializing and deserializing. Use from_temporary_id to get the monster pointer back. (The later may return a nullptr if the given id is not valid.)
Definition at line 47 of file creature_tracker.cpp.
 {
     const auto iter = std::find_if( monsters_list.begin(), monsters_list.end(),
     [&]( const shared_ptr_fast<monster> &ptr ) {
         return ptr.get() == &critter;
     } );
     if( iter == monsters_list.end() ) {
         return -1;
     }
     return iter - monsters_list.begin();
 }
References monsters_list.
update_pos()
bool creature_tracker::update_pos (const monster & critter, const tripoint_abs_ms & old_pos, const tripoint_abs_ms & new_pos)
Updates the position of the given monster to the given point.
Returns whether the operation was successful.
Definition at line 109 of file creature_tracker.cpp.
 {
     if( critter.is_dead() ) {
         // find ignores dead critters anyway, changing their position in the
         // monsters_by_location map is useless.
         remove_from_location_map( critter );
         return true;
     }
     if( const shared_ptr_fast<monster> new_critter_ptr = find( new_pos ) ) {
         auto &othermon = *new_critter_ptr;
         if( othermon.is_hallucination() ) {
             othermon.die( nullptr );
         } else {
             debugmsg( "update_zombie_pos: wanted to move %s to %s, but new location already has %s",
                       critter.disp_name(), new_pos.to_string_writable(), othermon.disp_name() );
             return false;
         }
     }
     const auto iter = std::find_if( monsters_list.begin(), monsters_list.end(),
     [&]( const shared_ptr_fast<monster> &ptr ) {
         return ptr.get() == &critter;
     } );
     if( iter != monsters_list.end() ) {
         monsters_by_location.erase( old_pos );
         monsters_by_location[new_pos] = *iter;
         return true;
     } else {
         // We're changing the x/y/z coordinates of a zombie that hasn't been added
         // to the game yet. `add` will update monsters_by_location for us.
         debugmsg( "update_zombie_pos: no %s at %s (moving to %s)",
                   critter.disp_name(), old_pos.to_string_writable(), new_pos.to_string_writable() );
         // Rebuild cache in case the monster actually IS in the game, just bugged
         rebuild_cache();
         return false;
     }
 }
References debugmsg, monster::disp_name(), find(), monster::is_dead(), monsters_by_location, monsters_list, rebuild_cache(), remove_from_location_map(), and coords::coord_point_base< Point >::to_string_writable().
Member Data Documentation
active_npc
std::list<shared_ptr_fast<npc> > creature_tracker::active_npc private
Definition at line 153 of file creature_tracker.h.
Referenced by clear_npcs(), creature_at(), and is_present().
creatures_by_zone_and_faction_
std::unordered_map<int, std::unordered_map<mfaction_id, std::vector<shared_ptr_fast<Creature> > > > creature_tracker::creatures_by_zone_and_faction_ private
Definition at line 171 of file creature_tracker.h.
Referenced by clear(), find_reachable(), and flood_fill_zone().
dirty_
bool creature_tracker::dirty_ = true private
Definition at line 167 of file creature_tracker.h.
Referenced by flood_fill_zone(), and invalidate_reachability_cache().
game
friend creature_tracker::game private
Definition at line 173 of file creature_tracker.h.
monsters_by_location
std::unordered_map<tripoint_abs_ms, shared_ptr_fast<monster> > creature_tracker::monsters_by_location private
Definition at line 156 of file creature_tracker.h.
Referenced by add(), clear(), deserialize(), find(), is_present(), rebuild_cache(), remove_from_location_map(), swap_positions(), and update_pos().
monsters_list
std::vector<shared_ptr_fast<monster> > creature_tracker::monsters_list private
Definition at line 154 of file creature_tracker.h.
Referenced by add(), clear(), deserialize(), from_temporary_id(), get_monsters_list(), kill_marked_for_death(), rebuild_cache(), remove(), remove_dead(), serialize(), size(), temporary_id(), and update_pos().
removed_this_turn_
std::unordered_set<shared_ptr_fast<monster> > creature_tracker::removed_this_turn_ private
Creatures that get removed via remove are stored here until the end of the turn.
This keeps the objects valid and they can still be accessed instead of causing UB.
Definition at line 162 of file creature_tracker.h.
Referenced by clear(), remove(), and remove_dead().
zone_number_
int creature_tracker::zone_number_ = 0 private
Definition at line 169 of file creature_tracker.h.
Referenced by flood_fill_zone().
zone_tick_
int creature_tracker::zone_tick_ = 1 private
Definition at line 168 of file creature_tracker.h.
Referenced by flood_fill_zone().
The documentation for this class was generated from the following files:
src/creature_tracker.h
src/creature_tracker.cpp
src/savegame.cpp