Cataclysm DDA: io::JsonArrayOutputArchive Class Reference
io::JsonArrayOutputArchive Class Reference
Output archive matching the input archive JsonArrayInputArchive.
#include <cata_io.h>
Public Types
using is_input = std::false_type
Public Member Functions
JsonArrayOutputArchive (JsonOut &stream)
~JsonArrayOutputArchive ()
template<typename T >
bool io (const T &value)
Public Attributes
JsonOut & stream
Detailed Description
Output archive matching the input archive JsonArrayInputArchive.
The class creates a valid JSON value in the output stream (that means it adds the initial '[' and ']' to the stream).
Definition at line 491 of file cata_io.h.
Member Typedef Documentation
is_input
using io::JsonArrayOutputArchive::is_input = std::false_type
Definition at line 494 of file cata_io.h.
Constructor & Destructor Documentation
JsonArrayOutputArchive()
io::JsonArrayOutputArchive::JsonArrayOutputArchive (JsonOut & stream) inline explicit
Definition at line 498 of file cata_io.h.
             : stream( stream ) {
             stream.start_array();
         }
References JsonOut::start_array(), and stream.
~JsonArrayOutputArchive()
io::JsonArrayOutputArchive::~JsonArrayOutputArchive () inline
Definition at line 502 of file cata_io.h.
{
             stream.end_array();
         }
References JsonOut::end_array(), and stream.
Member Function Documentation
io()
template<typename T > bool io::JsonArrayOutputArchive::io (const T & value) inline
Definition at line 507 of file cata_io.h.
{
             io::detail::has_archive_tag<T>::write( stream, value );
             return false;
         }
References stream, and io::detail::has_archive_tag< T, E >::write().
Member Data Documentation
stream
JsonOut& io::JsonArrayOutputArchive::stream
Definition at line 496 of file cata_io.h.
Referenced by io(), JsonArrayOutputArchive(), and ~JsonArrayOutputArchive().
The documentation for this class was generated from the following file:
src/cata_io.h