Cataclysm DDA: cataimgui::window Class Reference
cataimgui::window Class Reference abstract
#include <cata_imgui.h>
Public Member Functions
window (const std::string &id_, int window_flags=0)
virtual ~window ()
void draw_colored_text (std::string const &text, const nc_color &color, float wrap_width=0.0F, bool *is_selected=nullptr, bool *is_focused=nullptr, bool *is_hovered=nullptr)
void draw_colored_text (std::string const &text, nc_color &color, float wrap_width=0.0F, bool *is_selected=nullptr, bool *is_focused=nullptr, bool *is_hovered=nullptr)
bool action_button (const std::string &action, const std::string &text)
A button tied to a string action.
bool has_button_action ()
std::string get_button_action ()
void draw_header (std::string const &text)
bool get_is_open () const
virtual void draw ()
virtual void on_resized ()
bool is_bounds_changed ()
size_t get_text_width (const std::string &text)
size_t get_text_height (const char *text)
size_t str_width_to_pixels (size_t len)
size_t str_height_to_pixels (size_t len)
std::string get_filter ()
void clear_filter ()
void mark_resized ()
Protected Member Functions
window (int window_flags=0)
virtual bounds get_bounds ()
virtual void draw_controls ()=0
void draw_filter (const input_context &ctxt, bool filtering_active)
Protected Attributes
bool force_to_back = false
bool is_open
std::string id
int window_flags
std::string button_action
Private Attributes
std::unique_ptr< class window_impl > p_impl
std::unique_ptr< class filter_box_impl > filter_impl
bounds cached_bounds
Detailed Description
Definition at line 76 of file cata_imgui.h.
Constructor & Destructor Documentation
window() [1/2]
cataimgui::window::window (int window_flags = 0) explicit protected
Definition at line 466 of file cata_imgui.cpp.
 {
     p_impl = nullptr;
     this->window_flags = window_flags | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize |
                          ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoNavFocus |
                          ImGuiWindowFlags_NoBringToFrontOnFocus;
 }
window() [2/2]
cataimgui::window::window (const std::string & id_, int window_flags = 0) explicit
Definition at line 475 of file cata_imgui.cpp.
                                                                 : window( window_flags )
 {
     p_impl = std::make_unique<cataimgui::window_impl>( this );
     id = id_ + "##" + std::to_string( uint64_t( this ) );
     is_open = true;
 }
References is_open, p_impl, and to_string().
~window()
cataimgui::window::~window () virtual
Definition at line 482 of file cata_imgui.cpp.
 {
     p_impl.reset();
     if( GImGui ) {
         ImGui::ClearWindowSettings( id.c_str() );
         if( !ui_adaptor::has_imgui() ) {
             ImGui::GetIO().ClearInputKeys();
             GImGui->InputEventsQueue.resize( 0 );
         }
     }
 }
References ui_adaptor::has_imgui().
Member Function Documentation
action_button()
bool cataimgui::window::action_button (const std::string & action, const std::string & text)
A button tied to a string action.
When the button is clicked, push the desired action to input_context to be returned the next time there is no input action
Parameters
action The action id to be returned by the button
text The button's text
Returns
Definition at line 599 of file cata_imgui.cpp.
 {
     if( ImGui::Button( text.c_str() ) ) {
         button_action = action;
         return true;
     }
     return false;
 }
References action.
Referenced by keybindings_ui::draw_controls().
clear_filter()
void cataimgui::window::clear_filter ()
Definition at line 660 of file cata_imgui.cpp.
 {
     if( filter_impl && filter_impl->id != 0 ) {
         ImGuiInputTextState *input_state = ImGui::GetInputTextState( filter_impl->id );
         if( input_state ) {
             input_state->ClearText();
             filter_impl->text[0] = '\0';
         }
     }
 }
Referenced by input_context::display_menu().
draw()
void cataimgui::window::draw () virtual
Definition at line 544 of file cata_imgui.cpp.
 {
     button_action.clear();
     if( !is_open ) {
         return;
     }
     bool handled_resize = false;
     if( is_bounds_changed() ) {
         cached_bounds = get_bounds();
         // we want to make sure is_resized is able to be handled for at least a full frame
         handled_resize = true;
     }
     if( cached_bounds.x == -1 || cached_bounds.y == -1 ) {
         ImVec2 center = ImGui::GetMainViewport()->GetCenter();
         if( cached_bounds.x != -1.f ) {
             center.x = cached_bounds.x;
         }
         if( cached_bounds.y != -1.f ) {
             center.y = cached_bounds.y;
         }
         ImGui::SetNextWindowPos( center, ImGuiCond_Always, { cached_bounds.x == -1.f ? 0.5f : 0.f,  cached_bounds.y == -1.f ? 0.5f : 0.f } );
     } else if( cached_bounds.x >= 0 && cached_bounds.y >= 0 ) {
         ImGui::SetNextWindowPos( { cached_bounds.x, cached_bounds.y } );
     }
     if( cached_bounds.h > 0 || cached_bounds.w > 0 ) {
         ImGui::SetNextWindowSize( { cached_bounds.w, cached_bounds.h } );
     }
     if( ImGui::Begin( id.c_str(), &is_open, window_flags ) ) {
         draw_controls();
         if( p_impl->window_adaptor->is_on_top && !force_to_back ) {
             ImGui::BringWindowToDisplayFront( ImGui::GetCurrentWindow() );
         }
         if( handled_resize ) {
             point catapos;
             point catasize;
             ImVec2 impos = ImGui::GetWindowPos();
             ImVec2 imsize = ImGui::GetWindowSize();
             imvec2_to_point( &impos, &catapos );
             imvec2_to_point( &imsize, &catasize );
             p_impl->window_adaptor->position_absolute( catapos, catasize );
         }
     }
     ImGui::End();
     if( handled_resize ) {
         p_impl->is_resized = false;
     }
 }
References center, and cataimgui::imvec2_to_point().
Referenced by cataimgui::window_impl::window_impl().
draw_colored_text() [1/2]
void cataimgui::window::draw_colored_text (std::string const & text, const nc_color & color, float wrap_width = 0.0F, bool * is_selected = nullptr, bool * is_focused = nullptr, bool * is_hovered = nullptr)
Definition at line 351 of file cata_imgui.cpp.
 {
     nc_color color_cpy = color;
     draw_colored_text( text, color_cpy, wrap_width, is_selected, is_focused, is_hovered );
 }
References color().
Referenced by keybindings_ui::draw_controls(), query_popup_impl::draw_controls(), and mission_ui_impl::draw_selected_description().
draw_colored_text() [2/2]
void cataimgui::window::draw_colored_text (std::string const & text, nc_color & color, float wrap_width = 0.0F, bool * is_selected = nullptr, bool * is_focused = nullptr, bool * is_hovered = nullptr)
Definition at line 358 of file cata_imgui.cpp.
 {
     ImGui::PushID( text.c_str() );
     ImGuiID itemId = GImGui->CurrentWindow->IDStack.back();
     std::stack<nc_color> color_stack;
     color_stack.push( color );
     size_t chars_per_line = size_t( wrap_width );
     if( chars_per_line == 0 ) {
         chars_per_line = SIZE_MAX;
     }
 #if defined(WIN32) || defined(TILES)
     size_t char_width = size_t( ImGui::CalcTextSize( " " ).x );
     chars_per_line /= char_width;
 #endif
     std::vector<std::string> folded_msg = foldstring( text, chars_per_line );
     for( const std::string &line : folded_msg ) {
         const auto color_segments = split_by_color( line );
         if( is_selected != nullptr ) {
             ImGui::Selectable( "", is_selected );
             ImGui::SameLine( 0, 0 );
         }
         int i = 0;
         for( auto seg : color_segments ) {
             if( seg.empty() ) {
                 continue;
             }
             if( seg[0] == '<' ) {
                 const color_tag_parse_result::tag_type type =
                     update_color_stack( color_stack, seg, report_color_error::yes );
                 if( type != color_tag_parse_result::non_color_tag ) {
                     seg = rm_prefix( seg );
                 }
             }
             color = color_stack.empty() ? color : color_stack.top();
             if( i++ != 0 ) {
                 ImGui::SameLine( 0, 0 );
             }
 #if !(defined(TILES) || defined(WIN32))
             int pair_id = color.get_index();
             pairs &pair = colorpairs[pair_id];
             int palette_index = pair.FG != 0 ? pair.FG : pair.BG;
             if( color.is_bold() ) {
                 palette_index += color_loader<RGBTuple>::COLOR_NAMES_COUNT / 2;
             }
             RGBTuple &rgbCol = rgbPalette[palette_index];
             ImGui::TextColored( { static_cast<float>( rgbCol.Red / 255. ), static_cast<float>( rgbCol.Green / 255. ),
                                   static_cast<float>( rgbCol.Blue / 255. ), static_cast<float>( 255. ) },
                                 "%s", seg.c_str() );
 #else
             SDL_Color c = curses_color_to_SDL( color );
             ImGui::TextColored( { static_cast<float>( c.r / 255. ), static_cast<float>( c.g / 255. ),
                                   static_cast<float>( c.b / 255. ), static_cast<float>( c.a / 255. ) },
                                 "%s", seg.c_str() );
 #endif
             GImGui->LastItemData.ID = itemId;
             if( is_focused && !*is_focused ) {
                 *is_focused = ImGui::IsItemFocused();
             }
             if( is_hovered && !*is_hovered ) {
                 *is_hovered = GImGui->HoveredId == itemId;
             }
         }
     }
     ImGui::PopID();
 }
References pairs::BG, RGBTuple::Blue, c, color(), colorpairs, curses_color_to_SDL(), pairs::FG, foldstring(), nc_color::get_index(), RGBTuple::Green, nc_color::is_bold(), line(), color_tag_parse_result::non_color_tag, RGBTuple::Red, rgbPalette, rm_prefix(), coords::seg, split_by_color(), update_color_stack(), and yes.
draw_controls()
virtual void cataimgui::window::draw_controls () protected pure virtual
Implemented in query_popup_impl, mission_ui_impl, demo_ui, and keybindings_ui.
draw_filter()
void cataimgui::window::draw_filter (const input_context & ctxt, bool filtering_active) protected
Definition at line 623 of file cata_imgui.cpp.
 {
     if( !filter_impl ) {
         filter_impl = std::make_unique<cataimgui::filter_box_impl>();
         filter_impl->id = 0;
         filter_impl->text[0] = '\0';
     }
     if( !filtering_active ) {
         action_button( "FILTER", ctxt.get_button_text( "FILTER" ) );
         ImGui::SameLine();
         action_button( "RESET_FILTER", ctxt.get_button_text( "RESET_FILTER" ) );
         ImGui::SameLine();
     } else {
         action_button( "QUIT", ctxt.get_button_text( "QUIT", _( "Cancel" ) ) );
         ImGui::SameLine();
         action_button( "TEXT.CONFIRM", ctxt.get_button_text( "TEXT.CONFIRM", _( "OK" ) ) );
         ImGui::SameLine();
     }
     ImGui::BeginDisabled( !filtering_active );
     ImGui::InputText( "##FILTERBOX", filter_impl->text.data(),
                       filter_impl->text.size() );
     ImGui::EndDisabled();
     if( !filter_impl->id ) {
         filter_impl->id = GImGui->LastItemData.ID;
     }
 }
References _, and input_context::get_button_text().
Referenced by keybindings_ui::draw_controls().
draw_header()
void cataimgui::window::draw_header (std::string const & text)
get_bounds()
cataimgui::bounds cataimgui::window::get_bounds () protected virtual
Reimplemented in query_popup_impl, demo_ui, and keybindings_ui.
Definition at line 618 of file cata_imgui.cpp.
 {
     return { -1.f, -1.f, -1.f, -1.f };
 }
get_button_action()
std::string cataimgui::window::get_button_action ()
Definition at line 613 of file cata_imgui.cpp.
 {
     return button_action;
 }
Referenced by input_context::display_menu().
get_filter()
std::string cataimgui::window::get_filter ()
Definition at line 651 of file cata_imgui.cpp.
 {
     if( filter_impl ) {
         return std::string( filter_impl->text.data() );
     } else {
         return std::string();
     }
 }
Referenced by input_context::display_menu().
get_is_open()
bool cataimgui::window::get_is_open () const
Definition at line 432 of file cata_imgui.cpp.
 {
     return is_open;
 }
Referenced by input_context::display_menu().
get_text_height()
size_t cataimgui::window::get_text_height (const char * text)
Definition at line 508 of file cata_imgui.cpp.
 {
 #if defined(WIN32) || defined(TILES)
     return ImGui::CalcTextSize( "0" ).y * strlen( text );
 #else
     return utf8_width( text );
 #endif
 }
References utf8_width().
get_text_width()
size_t cataimgui::window::get_text_width (const std::string & text)
Definition at line 499 of file cata_imgui.cpp.
 {
 #if defined(WIN32) || defined(TILES)
     return ImGui::CalcTextSize( text.c_str() ).x;
 #else
     return utf8_width( text );
 #endif
 }
References utf8_width().
Referenced by keybindings_ui::draw_controls(), query_popup_impl::fold_query(), and query_popup_impl::on_resized().
has_button_action()
bool cataimgui::window::has_button_action ()
Definition at line 608 of file cata_imgui.cpp.
 {
     return !button_action.empty();
 }
Referenced by input_context::display_menu().
is_bounds_changed()
bool cataimgui::window::is_bounds_changed ()
Definition at line 494 of file cata_imgui.cpp.
 {
     return p_impl->is_resized;
 }
mark_resized()
void cataimgui::window::mark_resized ()
Definition at line 535 of file cata_imgui.cpp.
 {
     if( p_impl ) {
         p_impl->is_resized = true;
         p_impl->window_adaptor->mark_resize();
     }
 }
on_resized()
virtual void cataimgui::window::on_resized () inline virtual
Reimplemented in query_popup_impl, demo_ui, and keybindings_ui.
Definition at line 98 of file cata_imgui.h.
 {}
Referenced by cataimgui::window_impl::window_impl().
str_height_to_pixels()
size_t cataimgui::window::str_height_to_pixels (size_t len)
Definition at line 526 of file cata_imgui.cpp.
 {
 #if defined(WIN32) || defined(TILES)
     return ImGui::CalcTextSize( "0" ).y * len;
 #else
     return len;
 #endif
 }
Referenced by keybindings_ui::get_bounds(), and demo_ui::get_bounds().
str_width_to_pixels()
size_t cataimgui::window::str_width_to_pixels (size_t len)
Definition at line 517 of file cata_imgui.cpp.
 {
 #if defined(WIN32) || defined(TILES)
     return ImGui::CalcTextSize( "0" ).x * len;
 #else
     return len;
 #endif
 }
Referenced by keybindings_ui::draw_controls(), keybindings_ui::get_bounds(), demo_ui::get_bounds(), and query_popup_impl::on_resized().
Member Data Documentation
button_action
std::string cataimgui::window::button_action protected
Definition at line 113 of file cata_imgui.h.
cached_bounds
bounds cataimgui::window::cached_bounds private
Definition at line 80 of file cata_imgui.h.
filter_impl
std::unique_ptr<class filter_box_impl> cataimgui::window::filter_impl private
Definition at line 79 of file cata_imgui.h.
force_to_back
bool cataimgui::window::force_to_back = false protected
Definition at line 109 of file cata_imgui.h.
Referenced by demo_ui::init().
id
std::string cataimgui::window::id protected
Definition at line 111 of file cata_imgui.h.
is_open
bool cataimgui::window::is_open protected
Definition at line 110 of file cata_imgui.h.
Referenced by demo_ui::run(), and window().
p_impl
std::unique_ptr<class window_impl> cataimgui::window::p_impl private
Definition at line 78 of file cata_imgui.h.
Referenced by window().
window_flags
int cataimgui::window::window_flags protected
Definition at line 112 of file cata_imgui.h.
The documentation for this class was generated from the following files:
src/cata_imgui.h
src/cata_imgui.cpp