Cataclysm DDA: play_instrument_iuse Class Reference
play_instrument_iuse Class Reference
#include <iuse_actor.h>
Public Member Functions
play_instrument_iuse (const std::string &type="play_instrument")
~play_instrument_iuse () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
ret_val< void > can_use (const Character &, const item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Additional Inherited Members
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 627 of file iuse_actor.h.
Constructor & Destructor Documentation
play_instrument_iuse()
play_instrument_iuse::play_instrument_iuse (const std::string & type = "play_instrument") inline explicit
Definition at line 630 of file iuse_actor.h.
 : iuse_actor( type ) {}
~play_instrument_iuse()
play_instrument_iuse::~play_instrument_iuse () override default
Member Function Documentation
can_use()
ret_val< void > play_instrument_iuse::can_use (const Character & , const item & , const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 2101 of file iuse_actor.cpp.
 {
     return ret_val<void>::make_success();
 }
References ret_val< T >::make_success().
clone()
std::unique_ptr< iuse_actor > play_instrument_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2079 of file iuse_actor.cpp.
 {
     return std::make_unique<play_instrument_iuse>( *this );
 }
load()
void play_instrument_iuse::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2075 of file iuse_actor.cpp.
 {
 }
use()
std::optional< int > play_instrument_iuse::use (Character * p, item & it, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 2084 of file iuse_actor.cpp.
 {
     if( it.active ) {
         it.active = false;
         p->add_msg_player_or_npc( _( "You stop playing your %s." ),
                                   _( "<npcname> stops playing their %s." ),
                                   it.display_name() );
     } else {
         p->add_msg_player_or_npc( m_good,
                                   _( "You start playing your %s." ),
                                   _( "<npcname> starts playing their %s." ),
                                   it.display_name() );
         it.active = true;
     }
     return std::nullopt;
 }
References _, item::active, Character::add_msg_player_or_npc(), item::display_name(), and m_good.
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp