Cataclysm DDA: past_game_info Class Reference
past_game_info Class Reference
#include <past_games_info.h>
Public Member Functions
past_game_info (const JsonObject &jo)
stats_tracker & stats ()
const std::string & avatar_name () const
bool is_legacy_achievements () const
Private Attributes
std::vector< memorial_log_entry > log_
std::unique_ptr< stats_tracker > stats_
std::unique_ptr< achievements_tracker > achievements_
std::unordered_map< string_id< score >, cata_variant > scores_
std::string avatar_name_
bool legacy_achievements
Detailed Description
Definition at line 19 of file past_games_info.h.
Constructor & Destructor Documentation
past_game_info()
past_game_info::past_game_info (const JsonObject & jo) explicit
Definition at line 34 of file past_games_info.cpp.
 {
     int version;
     jo.read( "memorial_version", version );
     if( version == 0 || version == 1 ) {
         jo.read( "log", log_ );
         stats_ = std::make_unique<stats_tracker>();
         jo.read( "stats", *stats_ );
         achievements_ = std::make_unique<achievements_tracker>( *stats_, no_op, no_op, false );
         jo.read( "achievements", *achievements_ );
         jo.read( "scores", scores_ );
     } else {
         throw JsonError( string_format( "unexpected memorial version %d", version ) );
     }
     // See past_games_info::legacy_achievement
     legacy_achievements = version == 0;
     // Extract avatar name info from the game_avatar_new event
     // gives the starting character name; "et. al." is appended if there was character switching
     event_multiset &new_avatar_events = stats_->get_events( event_type::game_avatar_new );
     const event_multiset::summaries_type &new_avatar_counts = new_avatar_events.counts();
     if( !new_avatar_counts.empty() ) {
         const cata::event::data_type &new_avatar_event_data = new_avatar_counts.begin()->first;
         auto avatar_name_it = new_avatar_event_data.find( "avatar_name" );
         if( avatar_name_it != new_avatar_event_data.end() ) {
             avatar_name_ = avatar_name_it->second.get_string() +
                            ( new_avatar_counts.size() > 1 ? " et. al." : "" );
         }
     } else {
         // Legacy approach using the game_start event
         event_multiset &start_events = stats_->get_events( event_type::game_start );
         const event_multiset::summaries_type &start_counts = start_events.counts();
         if( start_counts.size() != 1 ) {
             if( start_counts.empty() ) {
                 throw too_old_memorial_file_error( "memorial file lacks game_start event" );
             }
             debugmsg( "Unexpected number of game start events: %d\n", start_counts.size() );
             return;
         }
         const cata::event::data_type &start_event_data = start_counts.begin()->first;
         auto avatar_name_it = start_event_data.find( "avatar_name" );
         if( avatar_name_it != start_event_data.end() ) {
             avatar_name_ = avatar_name_it->second.get_string();
         }
     }
 }
References achievements_, avatar_name_, event_multiset::counts(), debugmsg, game_avatar_new, game_start, legacy_achievements, log_, no_op(), JsonObject::read(), scores_, stats_, and string_format().
Member Function Documentation
avatar_name()
const std::string& past_game_info::avatar_name () const inline
Definition at line 28 of file past_games_info.h.
{
             return avatar_name_;
         }
References avatar_name_.
Referenced by past_achievements_info::avatars_completed().
is_legacy_achievements()
bool past_game_info::is_legacy_achievements () const inline
Definition at line 33 of file past_games_info.h.
{
             return legacy_achievements;
         }
References legacy_achievements.
stats()
stats_tracker& past_game_info::stats () inline
Definition at line 24 of file past_games_info.h.
{
             return *stats_;
         }
References stats_.
Member Data Documentation
achievements_
std::unique_ptr<achievements_tracker> past_game_info::achievements_ private
Definition at line 40 of file past_games_info.h.
Referenced by past_game_info().
avatar_name_
std::string past_game_info::avatar_name_ private
Definition at line 42 of file past_games_info.h.
Referenced by avatar_name(), and past_game_info().
legacy_achievements
bool past_game_info::legacy_achievements private
Definition at line 43 of file past_games_info.h.
Referenced by is_legacy_achievements(), and past_game_info().
log_
std::vector<memorial_log_entry> past_game_info::log_ private
Definition at line 38 of file past_games_info.h.
Referenced by past_game_info().
scores_
std::unordered_map<string_id<score>, cata_variant> past_game_info::scores_ private
Definition at line 41 of file past_games_info.h.
Referenced by past_game_info().
stats_
std::unique_ptr<stats_tracker> past_game_info::stats_ private
Definition at line 39 of file past_games_info.h.
Referenced by past_game_info(), and stats().
The documentation for this class was generated from the following files:
src/past_games_info.h
src/past_games_info.cpp