Cataclysm DDA: Skill Class Reference
Skill Class Reference
#include <skill.h>
Public Member Functions
Skill ()
Skill (const skill_id &ident, const translation &name, const translation &description, const std::set< std::string > &tags, skill_displayType_id display_type)
const skill_id & ident () const
std::string name () const
std::string description () const
int get_companion_skill_practice (const std::string &companion_skill) const
skill_displayType_id display_category () const
int get_sort_rank () const
time_info_t time_to_attack () const
int companion_combat_rank_factor () const
int companion_survival_rank_factor () const
int companion_industry_rank_factor () const
bool is_teachable () const
bool operator== (const Skill &b) const
bool operator< (const Skill &b) const
bool operator!= (const Skill &b) const
bool obsolete () const
bool is_combat_skill () const
bool is_contextual_skill () const
Static Public Member Functions
static void load_skill (const JsonObject &jsobj)
static skill_id from_legacy_int (int legacy_id)
static skill_id random_skill ()
static void reset ()
static std::vector< const Skill * > get_skills_sorted_by (std::function< bool(const Skill &, const Skill &)> pred)
Static Public Attributes
static std::vector< Skill > skills
Private Attributes
skill_id _ident
translation _name
translation _description
std::set< std::string > _tags
time_info_t _time_to_attack
skill_displayType_id _display_type
int _sort_rank
std::unordered_map< std::string, int > _companion_skill_practice
int _companion_combat_rank_factor = 0
int _companion_survival_rank_factor = 0
int _companion_industry_rank_factor = 0
bool _teachable = true
bool _obsolete = false
Static Private Attributes
static std::map< skill_id, Skill > contextual_skills
Friends
class string_id< Skill >
Detailed Description
Definition at line 32 of file skill.h.
Constructor & Destructor Documentation
Skill() [1/2]
Skill::Skill ()
Definition at line 79 of file skill.cpp.
              : Skill( skill_id::NULL_ID(), to_translation( "nothing" ),
                             to_translation( "The zen-most skill there is." ),
                             std::set<std::string> {}, skill_displayType_id::NULL_ID() )
 {
 }
References string.
Skill() [2/2]
Skill::Skill (const skill_id & ident, const translation & name, const translation & description, const std::set< std::string > & tags, skill_displayType_id display_type)
Definition at line 85 of file skill.cpp.
     : _ident( ident ), _name( name ), _description( description ), _tags( tags ),
       _display_type( display_type )
 {
 }
Member Function Documentation
companion_combat_rank_factor()
int Skill::companion_combat_rank_factor () const inline
Definition at line 90 of file skill.h.
{
             return _companion_combat_rank_factor;
         }
References _companion_combat_rank_factor.
companion_industry_rank_factor()
int Skill::companion_industry_rank_factor () const inline
Definition at line 96 of file skill.h.
{
             return _companion_industry_rank_factor;
         }
References _companion_industry_rank_factor.
companion_survival_rank_factor()
int Skill::companion_survival_rank_factor () const inline
Definition at line 93 of file skill.h.
{
             return _companion_survival_rank_factor;
         }
References _companion_survival_rank_factor.
description()
std::string Skill::description () const inline
Definition at line 74 of file skill.h.
{
             return _description.translated();
         }
References _description, and translation::translated().
Referenced by assemble_skill_details(), draw_skills_info(), and diary::skill_changes().
display_category()
skill_displayType_id Skill::display_category () const inline
Definition at line 81 of file skill.h.
{
             return _display_type;
         }
References _display_type.
Referenced by draw_skills_tab(), and set_skills().
from_legacy_int()
skill_id Skill::from_legacy_int (int legacy_id) static
Definition at line 216 of file skill.cpp.
 {
     static const std::array<skill_id, 28> legacy_skills = { {
             skill_id::NULL_ID(), skill_dodge, skill_melee, skill_unarmed,
             skill_bashing, skill_cutting, skill_stabbing, skill_throw,
             skill_gun, skill_pistol, skill_shotgun, skill_smg,
             skill_rifle, skill_archery, skill_launcher, skill_mechanics,
             skill_electronics, skill_cooking, skill_tailor, skill_id::NULL_ID(),
             skill_firstaid, skill_speech, skill_computer,
             skill_survival, skill_traps, skill_swimming, skill_driving,
         }
     };
     if( static_cast<size_t>( legacy_id ) < legacy_skills.size() ) {
         return legacy_skills[legacy_id];
     }
     debugmsg( "legacy skill id %d is invalid", legacy_id );
     return skills.front().ident(); // return a non-null id because callers might not expect a null-id
 }
References debugmsg, string_id< Skill >::NULL_ID(), skill_archery, skill_bashing, skill_computer, skill_cooking, skill_cutting, skill_dodge, skill_driving, skill_electronics, skill_firstaid, skill_gun, skill_launcher, skill_mechanics, skill_melee, skill_pistol, skill_rifle, skill_shotgun, skill_smg, skill_speech, skill_stabbing, skill_survival, skill_swimming, skill_tailor, skill_throw, skill_traps, skill_unarmed, and skills.
Referenced by npc_favor::deserialize().
get_companion_skill_practice()
int Skill::get_companion_skill_practice (const std::string & companion_skill) const inline
Definition at line 77 of file skill.h.
{
             return _companion_skill_practice.find( companion_skill ) == _companion_skill_practice.end() ? 0 :
                    _companion_skill_practice.at( companion_skill );
         }
References _companion_skill_practice.
get_skills_sorted_by()
std::vector< const Skill * > Skill::get_skills_sorted_by (std::function< bool(const Skill &, const Skill &)> pred) static
Definition at line 92 of file skill.cpp.
 {
     std::vector<const Skill *> result;
     result.reserve( skills.size() );
     for( const Skill &sk : skills ) {
         if( !sk.obsolete() ) {
             result.push_back( &sk );
         }
     }
     std::sort( begin( result ), end( result ), [&]( const Skill * lhs, const Skill * rhs ) {
         return pred( *lhs, *rhs );
     } );
     return result;
 }
References keycode::end, and skills.
Referenced by Character::disp_info(), npc::faction_display(), basecamp::recruit_return(), enchant_cache::serialize(), set_description(), set_skills(), and debug_menu::wishskill().
get_sort_rank()
int Skill::get_sort_rank () const inline
Definition at line 84 of file skill.h.
{
             return _sort_rank;
         }
References _sort_rank.
ident()
const skill_id& Skill::ident () const inline
Definition at line 68 of file skill.h.
{
             return _ident;
         }
References _ident.
Referenced by assemble_hobby_details(), assemble_skill_details(), talk_response::create_option_line(), draw_skills_info(), draw_skills_tab(), handle_player_display_action(), load_skill(), enchant_cache::serialize(), set_skills(), and debug_menu::wishskill().
is_combat_skill()
bool Skill::is_combat_skill () const
Definition at line 241 of file skill.cpp.
 {
     static const std::string combat_skill( "combat_skill" );
     return _tags.count( combat_skill ) > 0;
 }
References _tags.
Referenced by Character::do_skill_rust(), and Character::practice().
is_contextual_skill()
bool Skill::is_contextual_skill () const
Definition at line 247 of file skill.cpp.
 {
     static const std::string contextual_skill( "contextual_skill" );
     return _tags.count( contextual_skill ) > 0;
 }
References _tags.
Referenced by SkillLevelMap::get_skill_level_object(), and load_skill().
is_teachable()
bool Skill::is_teachable () const inline
Definition at line 99 of file skill.h.
{
             return _teachable;
         }
References _teachable.
load_skill()
void Skill::load_skill (const JsonObject & jsobj) static
Definition at line 117 of file skill.cpp.
 {
     // TEMPORARY until 0.G: Remove "ident" support
     skill_id ident = skill_id( jsobj.has_string( "ident" ) ? jsobj.get_string( "ident" ) :
                                jsobj.get_string( "id" ) );
     skills.erase( std::remove_if( begin( skills ), end( skills ), [&]( const Skill & s ) {
         return s._ident == ident;
     } ), end( skills ) );
     translation name;
     jsobj.read( "name", name );
     translation desc;
     jsobj.read( "description", desc );
     std::unordered_map<std::string, int> companion_skill_practice;
     for( JsonObject jo_csp : jsobj.get_array( "companion_skill_practice" ) ) {
         companion_skill_practice.emplace( jo_csp.get_string( "skill" ), jo_csp.get_int( "weight" ) );
     }
     time_info_t time_to_attack;
     if( jsobj.has_object( "time_to_attack" ) ) {
         JsonObject jso_tta = jsobj.get_object( "time_to_attack" );
         jso_tta.read( "min_time", time_to_attack.min_time );
         jso_tta.read( "base_time", time_to_attack.base_time );
         jso_tta.read( "time_reduction_per_level", time_to_attack.time_reduction_per_level );
     }
     skill_displayType_id display_type = skill_displayType_id( jsobj.get_string( "display_category" ) );
     Skill sk( ident, name, desc, jsobj.get_tags( "tags" ), display_type );
     if( jsobj.has_int( "sort_rank" ) ) {
         sk._sort_rank = jsobj.get_int( "sort_rank" );
     } else {
         sk._sort_rank = 1000000;
         debugmsg( "skill '%s' missing 'sort_rank' field.", ident.str() );
     }
     sk._time_to_attack = time_to_attack;
     sk._companion_combat_rank_factor = jsobj.get_int( "companion_combat_rank_factor", 0 );
     sk._companion_survival_rank_factor = jsobj.get_int( "companion_survival_rank_factor", 0 );
     sk._companion_industry_rank_factor = jsobj.get_int( "companion_industry_rank_factor", 0 );
     sk._companion_skill_practice = companion_skill_practice;
     sk._obsolete = jsobj.get_bool( "obsolete", false );
     sk._teachable = jsobj.get_bool( "teachable", true );
     if( sk.is_contextual_skill() ) {
         contextual_skills[sk.ident()] = sk;
     } else {
         skills.push_back( sk );
     }
 }
References _companion_combat_rank_factor, _companion_industry_rank_factor, _companion_skill_practice, _companion_survival_rank_factor, _ident, _obsolete, _sort_rank, _teachable, _time_to_attack, time_info_t::base_time, contextual_skills, debugmsg, keycode::end, JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::get_tags(), JsonObject::has_int(), JsonObject::has_object(), JsonObject::has_string(), ident(), is_contextual_skill(), time_info_t::min_time, name(), JsonObject::read(), skill_id, skills, string_id< T >::str(), time_info_t::time_reduction_per_level, and time_to_attack().
Referenced by DynamicDataLoader::initialize().
name()
std::string Skill::name () const inline
Definition at line 71 of file skill.h.
{
             return _name.translated();
         }
References _name, and translation::translated().
Referenced by assemble_hobby_details(), assemble_skill_details(), item::book_info(), talk_function::companion_choose(), basecamp::craft_description(), talk_response::create_option_line(), draw_skills_tab(), dialogue::gen_responses(), Character::get_book_reader(), read_inventory_preset::get_filter(), player_activity::get_progress_message(), read_activity_actor::get_progress_message(), get_repair_hint(), item::gun_info(), Character::handle_skill_warning(), avatar::identify(), load_skill(), memorial_logger::notify(), read_activity_actor::npc_read(), read_activity_actor::player_read(), Character::practice(), practice_recipe_description(), avatar::read(), read_inventory_preset::read_inventory_preset(), repair_item_finish(), set_skills(), diary::skill_changes(), talker_character_const::skill_seminar_text(), talker_character_const::skill_training_text(), activity_handlers::teach_finish(), veh_interact::update_part_requirements(), and debug_menu::wishskill().
obsolete()
bool Skill::obsolete () const inline
Definition at line 114 of file skill.h.
{
             return _obsolete;
         }
References _obsolete.
operator!=()
bool Skill::operator!= (const Skill & b) const inline
Definition at line 110 of file skill.h.
{
             return !( *this == b );
         }
References b.
operator<()
bool Skill::operator< (const Skill & b) const inline
Definition at line 106 of file skill.h.
{
             return this->_ident < b._ident;    // Only here for the benefit of std::map<Skill,T>
         }
References b.
operator==()
bool Skill::operator== (const Skill & b) const inline
Definition at line 103 of file skill.h.
{
             return this->_ident == b._ident;
         }
References b.
random_skill()
skill_id Skill::random_skill () static
Definition at line 235 of file skill.cpp.
 {
     return random_entry_ref( skills ).ident();
 }
References random_entry_ref(), and skills.
Referenced by avatar::randomize().
reset()
void Skill::reset () static
Definition at line 111 of file skill.cpp.
 {
     skills.clear();
     contextual_skills.clear();
 }
References contextual_skills, and skills.
Referenced by DynamicDataLoader::unload_data().
time_to_attack()
time_info_t Skill::time_to_attack () const inline
Definition at line 87 of file skill.h.
{
             return _time_to_attack;
         }
References _time_to_attack.
Referenced by load_skill(), and time_to_attack().
Friends And Related Function Documentation
string_id< Skill >
friend class string_id< Skill > friend
Definition at line 29 of file skill.h.
Member Data Documentation
_companion_combat_rank_factor
int Skill::_companion_combat_rank_factor = 0 private
Definition at line 46 of file skill.h.
Referenced by companion_combat_rank_factor(), and load_skill().
_companion_industry_rank_factor
int Skill::_companion_industry_rank_factor = 0 private
Definition at line 48 of file skill.h.
Referenced by companion_industry_rank_factor(), and load_skill().
_companion_skill_practice
std::unordered_map<std::string, int> Skill::_companion_skill_practice private
Definition at line 43 of file skill.h.
Referenced by get_companion_skill_practice(), and load_skill().
_companion_survival_rank_factor
int Skill::_companion_survival_rank_factor = 0 private
Definition at line 47 of file skill.h.
Referenced by companion_survival_rank_factor(), and load_skill().
_description
translation Skill::_description private
Definition at line 38 of file skill.h.
Referenced by description().
_display_type
skill_displayType_id Skill::_display_type private
Definition at line 41 of file skill.h.
Referenced by display_category().
_ident
skill_id Skill::_ident private
Definition at line 35 of file skill.h.
Referenced by ident(), and load_skill().
_name
translation Skill::_name private
Definition at line 37 of file skill.h.
Referenced by name().
_obsolete
bool Skill::_obsolete = false private
Definition at line 50 of file skill.h.
Referenced by load_skill(), and obsolete().
_sort_rank
int Skill::_sort_rank private
Definition at line 42 of file skill.h.
Referenced by get_sort_rank(), and load_skill().
_tags
std::set<std::string> Skill::_tags private
Definition at line 39 of file skill.h.
Referenced by is_combat_skill(), and is_contextual_skill().
_teachable
bool Skill::_teachable = true private
Definition at line 49 of file skill.h.
Referenced by is_teachable(), and load_skill().
_time_to_attack
time_info_t Skill::_time_to_attack private
Definition at line 40 of file skill.h.
Referenced by load_skill(), and time_to_attack().
contextual_skills
std::map< skill_id, Skill > Skill::contextual_skills static private
Definition at line 45 of file skill.h.
Referenced by load_skill(), and reset().
skills
std::vector< Skill > Skill::skills static
Definition at line 52 of file skill.h.
Referenced by apply_all_to_unassigned(), companion_combat_rank(), companion_industry_rank(), talk_function::companion_skill_trainer(), companion_survival_rank(), from_legacy_int(), get_skills_sorted_by(), load_skill(), diary::new_page(), random_skill(), npc::randomize(), reset(), skill_points_used(), and standard_npc::standard_npc().
The documentation for this class was generated from the following files:
src/skill.h
src/skill.cpp