Cataclysm DDA: achievement_tracker Class Reference
achievement_tracker Class Reference
#include <achievement.h>
Public Member Functions
achievement_tracker (const achievement_tracker &)=delete
achievement_tracker & operator= (const achievement_tracker &)=delete
achievement_tracker (const achievement &a, achievements_tracker &tracker, stats_tracker &stats)
void set_requirement (requirement_watcher *watcher, bool is_satisfied)
bool time_is_expired () const
std::vector< cata_variant > current_values () const
std::string ui_text () const
Private Attributes
const achievement * achievement_
achievements_tracker * tracker_
std::vector< std::unique_ptr< requirement_watcher > > watchers_
std::array< std::unordered_set< requirement_watcher * >, 2 > sorted_watchers_
Detailed Description
Definition at line 162 of file achievement.h.
Constructor & Destructor Documentation
achievement_tracker() [1/2]
achievement_tracker::achievement_tracker (const achievement_tracker &) delete
achievement_tracker() [2/2]
achievement_tracker::achievement_tracker (const achievement & a, achievements_tracker & tracker, stats_tracker & stats)
Definition at line 653 of file achievement.cpp.
                                :
     achievement_( &a ),
     tracker_( &tracker )
 {
     for( const achievement_requirement &req : a.requirements() ) {
         watchers_.push_back( std::make_unique<requirement_watcher>( *this, req, stats ) );
     }
     for( const std::unique_ptr<requirement_watcher> &watcher : watchers_ ) {
         bool is_satisfied = watcher->is_satisfied( stats );
         sorted_watchers_[is_satisfied].insert( watcher.get() );
     }
 }
References a, sorted_watchers_, and watchers_.
Member Function Documentation
current_values()
std::vector< cata_variant > achievement_tracker::current_values () const
Definition at line 702 of file achievement.cpp.
 {
     std::vector<cata_variant> result;
     result.reserve( watchers_.size() );
     for( const std::unique_ptr<requirement_watcher> &watcher : watchers_ ) {
         result.push_back( watcher->current_value() );
     }
     return result;
 }
References watchers_.
Referenced by ui_text().
operator=()
achievement_tracker& achievement_tracker::operator= (const achievement_tracker &) delete
set_requirement()
void achievement_tracker::set_requirement (requirement_watcher * watcher, bool is_satisfied)
Definition at line 668 of file achievement.cpp.
 {
     if( sorted_watchers_[is_satisfied].insert( watcher ).second ) {
         // Remove from other
         sorted_watchers_[!is_satisfied].erase( watcher );
         cata_assert( sorted_watchers_[0].size() + sorted_watchers_[1].size() == watchers_.size() );
     }
     achievement_completion time_comp =
         achievement_->time_constraint() ?
         achievement_->time_constraint()->completed() : achievement_completion::completed;
     if( sorted_watchers_[false].empty() && time_comp == achievement_completion::completed &&
         !achievement_->is_conduct() ) {
         // report_achievement can result in this being deleted, so it must be
         // the last thing in the function
         tracker_->report_achievement( achievement_, achievement_completion::completed );
         return;
     }
     if( time_comp == achievement_completion::failed ||
         ( !is_satisfied && watcher->requirement().becomes_false ) ) {
         // report_achievement can result in this being deleted, so it must be
         // the last thing in the function
         tracker_->report_achievement( achievement_, achievement_completion::failed );
     }
 }
References achievement_, achievement_requirement::becomes_false, cata_assert, completed, failed, achievement::is_conduct(), achievements_tracker::report_achievement(), requirement_watcher::requirement(), second, om_direction::size, sorted_watchers_, achievement::time_constraint(), tracker_, and watchers_.
time_is_expired()
bool achievement_tracker::time_is_expired () const
Definition at line 696 of file achievement.cpp.
 {
     return achievement_->time_constraint() &&
            achievement_->time_constraint()->completed() == achievement_completion::failed;
 }
References achievement_, failed, and achievement::time_constraint().
Referenced by ui_text().
ui_text()
std::string achievement_tracker::ui_text () const
Definition at line 712 of file achievement.cpp.
 {
     // Determine overall achievement status
     if( time_is_expired() ) {
         return achievement_state{
             achievement_completion::failed,
             achievement_->time_constraint()->target(),
             current_values()
         } .ui_text( achievement_ );
     }
     // First: the achievement name and description
     nc_color c = color_from_completion( achievement_->is_conduct(),
                                         achievement_completion::pending,
                                         false );
     nc_color c_title = color_from_completion( achievement_->is_conduct(),
                        achievement_completion::pending,
                        true );
     std::string result = colorize( achievement_->name(), c_title ) + "\n";
     if( !achievement_->description().empty() ) {
         result += "  " + colorize( achievement_->description(), c ) + "\n";
     }
     // Note if it's been completed in other games
     const std::vector<std::string> avatars_completed =
         get_past_achievements().avatars_completed( achievement_->id );
     if( !avatars_completed.empty() ) {
         std::string message =
             string_format( _( "Previously completed by %s" ), avatars_completed.front() );
         const size_t num_completions = avatars_completed.size();
         if( num_completions > 1 ) {
             message += string_format(
                            n_gettext( " and %d other", " and %d others", num_completions - 1 ),
                            num_completions - 1 );
         }
         result += "  " + colorize( message, c_blue ) + "\n";
     }
     // Next: the time constraint
     if( achievement_->time_constraint() ) {
         result += "  " + achievement_->time_constraint()->ui_text( achievement_->is_conduct() ) +
                   "\n";
     }
     // Next: the requirements
     std::vector<std::optional<std::string>> req_texts;
     req_texts.reserve( watchers_.size() );
     for( const std::unique_ptr<requirement_watcher> &watcher : watchers_ ) {
         req_texts.push_back( watcher->ui_text() );
     }
     result += format_requirements( req_texts, c );
     return result;
 }
References _, achievement_, past_achievements_info::avatars_completed(), c, c_blue, color_from_completion(), colorize(), current_values(), achievement::description(), translation::empty(), failed, format_requirements(), get_past_achievements(), achievement::id, achievement::is_conduct(), mapgen_defer::message, n_gettext, achievement::name(), pending, string_format(), achievement::time_constraint(), time_is_expired(), and watchers_.
Member Data Documentation
achievement_
const achievement* achievement_tracker::achievement_ private
Definition at line 178 of file achievement.h.
Referenced by set_requirement(), time_is_expired(), and ui_text().
sorted_watchers_
std::array<std::unordered_set<requirement_watcher *>, 2> achievement_tracker::sorted_watchers_ private
Definition at line 186 of file achievement.h.
Referenced by achievement_tracker(), and set_requirement().
tracker_
achievements_tracker* achievement_tracker::tracker_ private
Definition at line 179 of file achievement.h.
Referenced by set_requirement().
watchers_
std::vector<std::unique_ptr<requirement_watcher> > achievement_tracker::watchers_ private
Definition at line 180 of file achievement.h.
Referenced by achievement_tracker(), current_values(), set_requirement(), and ui_text().
The documentation for this class was generated from the following files:
src/achievement.h
src/achievement.cpp