Cataclysm DDA: scent_map Class Reference
scent_map Class Reference
#include <scent_map.h>
Public Member Functions
scent_map (const game &g)
void deserialize (const std::string &data, bool is_type=false)
std::string serialize (bool is_type=false) const
void draw (const catacurses::window &win, int div, const tripoint &center) const
void update (const tripoint &center, map &m)
void reset ()
void decay ()
void shift (const point &sm_shift)
void set_unsafe (const tripoint &p, int value, const scenttype_id &type=scenttype_id())
int get_unsafe (const tripoint &p) const
scenttype_id get_type () const
scenttype_id get_type (const tripoint &p) const
bool inbounds (const tripoint &p) const
bool inbounds (const point &p) const
void set (const tripoint &p, int value, const scenttype_id &type=scenttype_id())
Get the scent value at the given position.
int get (const tripoint &p) const
Protected Types
template<typename T >
using scent_array = std::array< std::array< T, MAPSIZE_Y >, MAPSIZE_X >
Protected Attributes
scent_array< int > grscent
scenttype_id typescent
std::optional< tripoint > player_last_position
time_point player_last_moved = calendar::before_time_starts
const game & gm
Detailed Description
Definition at line 44 of file scent_map.h.
Member Typedef Documentation
scent_array
template<typename T > using scent_map::scent_array = std::array<std::array<T, MAPSIZE_Y>, MAPSIZE_X> protected
Definition at line 48 of file scent_map.h.
Constructor & Destructor Documentation
scent_map()
scent_map::scent_map (const game & g) inline explicit
Definition at line 58 of file scent_map.h.
 : gm( g ) { }
Member Function Documentation
decay()
void scent_map::decay ()
Definition at line 62 of file scent_map.cpp.
 {
     for( auto &elem : grscent ) {
         for( int &val : elem ) {
             val = std::max( 0, val - 1 );
         }
     }
 }
References grscent, and max().
Referenced by map::decay_fields_and_scent().
deserialize()
void scent_map::deserialize (const std::string & data, bool is_type = false)
Definition at line 297 of file savegame.cpp.
 {
     std::istringstream buffer( data );
     buffer.imbue( std::locale::classic() );
     if( is_type ) {
         std::string str;
         buffer >> str;
         typescent = scenttype_id( str );
     } else {
         int stmp = 0;
         int count = 0;
         for( auto &elem : grscent ) {
             for( int &val : elem ) {
                 if( count == 0 ) {
                     buffer >> stmp >> count;
                 }
                 count--;
                 val = stmp;
             }
         }
     }
 }
References grscent, and typescent.
Referenced by game::unserialize().
draw()
void scent_map::draw (const catacurses::window & win, int div, const tripoint & center) const
Definition at line 71 of file scent_map.cpp.
 {
     cata_assert( div != 0 );
     const point max( getmaxx( win ), getmaxy( win ) );
     for( int x = 0; x < max.x; ++x ) {
         for( int y = 0; y < max.y; ++y ) {
             const int sn = get( center + point( -max.x / 2 + x, -max.y / 2 + y ) ) / div;
             mvwprintz( win, point( x, y ), sev( sn / 10 ), "%d", sn % 10 );
         }
     }
 }
References cata_assert, center, math_opers::div(), get(), catacurses::getmaxx(), catacurses::getmaxy(), max(), mvwprintz(), point, and sev().
Referenced by game::display_scent().
get()
int scent_map::get (const tripoint & p) const
Definition at line 95 of file scent_map.cpp.
 {
     if( inbounds( p ) && grscent[p.x][p.y] > 0 ) {
         return get_unsafe( p );
     }
     return 0;
 }
References get_unsafe(), grscent, inbounds(), tripoint::x, and tripoint::y.
Referenced by draw(), monster::scent_move(), and monster::will_reach().
get_type() [1/2]
scenttype_id scent_map::get_type () const
Definition at line 122 of file scent_map.cpp.
 {
     return typescent;
 }
References typescent.
Referenced by monster::scent_move().
get_type() [2/2]
scenttype_id scent_map::get_type (const tripoint & p) const
Definition at line 127 of file scent_map.cpp.
 {
     scenttype_id id;
     if( inbounds( p ) && grscent[p.x][p.y] > 0 ) {
         id = typescent;
     }
     return id;
 }
References grscent, base_camps::id, inbounds(), typescent, tripoint::x, and tripoint::y.
get_unsafe()
int scent_map::get_unsafe (const tripoint & p) const
Definition at line 117 of file scent_map.cpp.
 {
     return grscent[p.x][p.y] - std::abs( get_map().get_abs_sub().z() - p.z );
 }
References abs(), get_map(), grscent, tripoint::x, tripoint::y, and tripoint::z.
Referenced by scent_block::commit_modifications(), get(), and monster::scent_move().
inbounds() [1/2]
bool scent_map::inbounds (const point & p) const
Definition at line 151 of file scent_map.cpp.
 {
     static constexpr point scent_map_boundary_min{};
     static constexpr point scent_map_boundary_max( MAPSIZE_X, MAPSIZE_Y );
     static constexpr half_open_rectangle<point> scent_map_boundaries(
         scent_map_boundary_min, scent_map_boundary_max );
     return scent_map_boundaries.contains( p );
 }
References MAPSIZE_X, and MAPSIZE_Y.
inbounds() [2/2]
bool scent_map::inbounds (const tripoint & p) const
Definition at line 136 of file scent_map.cpp.
 {
     // HACK: This weird long check here is a hack around the fact that scentmap is 2D
     // A z-level can access scentmap if it is within SCENT_MAP_Z_REACH flying z-level move from player's z-level
     // That is, if a flying critter could move directly up or down (or stand still) and be on same z-level as player
     const int levz = get_map().get_abs_sub().z();
     const bool scent_map_z_level_inbounds = ( p.z == levz ) ||
                                             ( std::abs( p.z - levz ) == SCENT_MAP_Z_REACH &&
                                                     get_map().valid_move( p, tripoint( p.xy(), levz ), false, true ) );
     if( !scent_map_z_level_inbounds ) {
         return false;
     }
     return inbounds( p.xy() );
 }
References abs(), map::get_abs_sub(), get_map(), SCENT_MAP_Z_REACH, tripoint, map::valid_move(), tripoint::xy(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and tripoint::z.
Referenced by scent_block::commit_modifications(), get(), get_type(), monster::scent_move(), set(), and shift().
reset()
void scent_map::reset ()
Definition at line 52 of file scent_map.cpp.
 {
     for( auto &elem : grscent ) {
         for( int &val : elem ) {
             val = 0;
         }
     }
     typescent = scenttype_id();
 }
References grscent, and typescent.
Referenced by tutorial_game::init(), game::setup(), game::unserialize(), Character::update_type_of_scent(), and game::vertical_shift().
serialize()
std::string scent_map::serialize (bool is_type = false) const
Definition at line 156 of file savegame.cpp.
 {
     std::ostringstream rle_out;
     rle_out.imbue( std::locale::classic() );
     if( is_type ) {
         rle_out << typescent.str();
     } else {
         int rle_lastval = -1;
         int rle_count = 0;
         for( const auto &elem : grscent ) {
             for( const int &val : elem ) {
                 if( val == rle_lastval ) {
                     rle_count++;
                 } else {
                     if( rle_count ) {
                         rle_out << rle_count << " ";
                     }
                     rle_out << val << " ";
                     rle_lastval = val;
                     rle_count = 1;
                 }
             }
         }
         rle_out << rle_count;
     }
     return rle_out.str();
 }
References grscent, string_id< T >::str(), and typescent.
Referenced by game::serialize().
set()
void scent_map::set (const tripoint & p, int value, const scenttype_id & type = scenttype_id())
Get the scent value at the given position.
An invalid position is allows and will yield a 0 value. The coordinate system is the same as the map (g->m) uses.
Definition at line 103 of file scent_map.cpp.
 {
     if( inbounds( p ) ) {
         set_unsafe( p, value, type );
     }
 }
References inbounds(), set_unsafe(), and type.
set_unsafe()
void scent_map::set_unsafe (const tripoint & p, int value, const scenttype_id & type = scenttype_id())
Definition at line 110 of file scent_map.cpp.
 {
     grscent[p.x][p.y] = value;
     if( !type.is_empty() ) {
         typescent = type;
     }
 }
References grscent, type, typescent, tripoint::x, and tripoint::y.
Referenced by scent_block::commit_modifications(), and set().
shift()
void scent_map::shift (const point & sm_shift)
Definition at line 83 of file scent_map.cpp.
 {
     scent_array<int> new_scent;
     for( size_t x = 0; x < MAPSIZE_X; ++x ) {
         for( size_t y = 0; y < MAPSIZE_Y; ++y ) {
             const point p = point( x, y ) + sm_shift;
             new_scent[x][y] = inbounds( p ) ? grscent[ p.x ][ p.y ] : 0;
         }
     }
     grscent = new_scent;
 }
References grscent, inbounds(), MAPSIZE_X, MAPSIZE_Y, point, point::x, and point::y.
Referenced by game::update_map().
update()
void scent_map::update (const tripoint & center, map & m)
Definition at line 162 of file scent_map.cpp.
 {
     // Stop updating scent after X turns of the player not moving.
     // Once wind is added, need to reset this on wind shifts as well.
     if( !player_last_position || center != *player_last_position ) {
         player_last_position.emplace( center );
         player_last_moved = calendar::turn;
     } else if( player_last_moved + 1000_turns < calendar::turn ) {
         return;
     }
     // note: the next four intermediate matrices need to be at least
     // [2*SCENT_RADIUS+3][2*SCENT_RADIUS+1] in size to hold enough data
     // The code I'm modifying used [MAPSIZE_X]. I'm staying with that to avoid new bugs.
     // These two matrices are transposed so that x addresses are contiguous in memory
     scent_array<int> sum_3_scent_y;
     scent_array<int> squares_used_y;
     // these are for caching flag lookups
     scent_array<bool> blocks_scent; // currently only ter_furn_flag::TFLAG_NO_SCENT blocks scent
     scent_array<bool> reduces_scent;
     // for loop constants
     const int scentmap_minx = center.x - SCENT_RADIUS;
     const int scentmap_maxx = center.x + SCENT_RADIUS;
     const int scentmap_miny = center.y - SCENT_RADIUS;
     const int scentmap_maxy = center.y + SCENT_RADIUS;
     // decrease this to reduce gas spread. Keep it under 125 for
     // stability. This is essentially a decimal number * 1000.
     const int diffusivity = 100;
     // The new scent flag searching function. Should be wayyy faster than the old one.
     m.scent_blockers( blocks_scent, reduces_scent, point( scentmap_minx - 1, scentmap_miny - 1 ),
                       point( scentmap_maxx + 1, scentmap_maxy + 1 ) );
     // Sum neighbors in the y direction.  This way, each square gets called 3 times instead of 9
     // times. This cost us an extra loop here, but it also eliminated a loop at the end, so there
     // is a net performance improvement over the old code. Could probably still be better.
     // note: this method needs an array that is one square larger on each side in the x direction
     // than the final scent matrix. I think this is fine since SCENT_RADIUS is less than
     // MAPSIZE_X, but if that changes, this may need tweaking.
     for( int x = scentmap_minx - 1; x <= scentmap_maxx + 1; ++x ) {
         for( int y = scentmap_miny; y <= scentmap_maxy; ++y ) {
             // remember the sum of the scent val for the 3 neighboring squares that can defuse into
             sum_3_scent_y[y][x] = 0;
             squares_used_y[y][x] = 0;
             for( int i = y - 1; i <= y + 1; ++i ) {
                 if( !blocks_scent[x][i] ) {
                     if( reduces_scent[x][i] ) {
                         // only 20% of scent can diffuse on REDUCE_SCENT squares
                         sum_3_scent_y[y][x] += 2 * grscent[x][i];
                         squares_used_y[y][x] += 2;
                     } else {
                         sum_3_scent_y[y][x] += 10 * grscent[x][i];
                         squares_used_y[y][x] += 10;
                     }
                 }
             }
         }
     }
     // Rest of the scent map
     for( int x = scentmap_minx; x <= scentmap_maxx; ++x ) {
         for( int y = scentmap_miny; y <= scentmap_maxy; ++y ) {
             int &scent_here = grscent[x][y];
             if( !blocks_scent[x][y] ) {
                 // to how many neighboring squares do we diffuse out? (include our own square
                 // since we also include our own square when diffusing in)
                 const int squares_used = squares_used_y[y][x - 1]
                                          + squares_used_y[y][x]
                                          + squares_used_y[y][x + 1];
                 int this_diffusivity;
                 if( !reduces_scent[x][y] ) {
                     this_diffusivity = diffusivity;
                 } else {
                     this_diffusivity = diffusivity / 5; //less air movement for REDUCE_SCENT square
                 }
                 // take the old scent and subtract what diffuses out
                 int temp_scent = scent_here * ( 10 * 1000 - squares_used * this_diffusivity );
                 // neighboring REDUCE_SCENT squares absorb some scent
                 temp_scent -= scent_here * this_diffusivity * ( 90 - squares_used ) / 5;
                 // we've already summed neighboring scent values in the y direction in the previous
                 // loop. Now we do it for the x direction, multiply by diffusion, and this is what
                 // diffuses into our current square.
                 scent_here =
                     ( temp_scent
                       + this_diffusivity * ( sum_3_scent_y[y][x - 1]
                                              + sum_3_scent_y[y][x]
                                              + sum_3_scent_y[y][x + 1] )
                     ) / ( 1000 * 10 );
             } else {
                 // this cell blocks scent via NO_SCENT (in json)
                 scent_here = 0;
             }
         }
     }
 }
References center, grscent, player_last_moved, player_last_position, point, map::scent_blockers(), SCENT_RADIUS, and calendar::turn.
Member Data Documentation
gm
const game& scent_map::gm protected
Definition at line 55 of file scent_map.h.
grscent
scent_array<int> scent_map::grscent protected
Definition at line 50 of file scent_map.h.
Referenced by decay(), deserialize(), get(), get_type(), get_unsafe(), reset(), serialize(), set_unsafe(), shift(), and update().
player_last_moved
time_point scent_map::player_last_moved = calendar::before_time_starts protected
Definition at line 53 of file scent_map.h.
Referenced by update().
player_last_position
std::optional<tripoint> scent_map::player_last_position protected
Definition at line 52 of file scent_map.h.
Referenced by update().
typescent
scenttype_id scent_map::typescent protected
Definition at line 51 of file scent_map.h.
Referenced by deserialize(), get_type(), reset(), serialize(), and set_unsafe().
The documentation for this class was generated from the following files:
src/scent_map.h
src/savegame.cpp
src/scent_map.cpp