Cataclysm DDA: bookbinder_copy_activity_actor Class Reference
bookbinder_copy_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
bookbinder_copy_activity_actor ()=default
bookbinder_copy_activity_actor (const item_location &book_binder, const recipe_id &rec_id)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
bool can_resume_with_internal (const activity_actor &other, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &p) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &p) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static int pages_for_recipe (const recipe &r)
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
item_location book_binder
recipe_id rec_id
int pages = 0
Detailed Description
Definition at line 237 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
bookbinder_copy_activity_actor() [1/2]
bookbinder_copy_activity_actor::bookbinder_copy_activity_actor () default
bookbinder_copy_activity_actor() [2/2]
bookbinder_copy_activity_actor::bookbinder_copy_activity_actor (const item_location & book_binder, const recipe_id & rec_id) inline
Definition at line 247 of file activity_actor_definitions.h.
           : book_binder( book_binder ), rec_id( rec_id ) {};
Member Function Documentation
can_resume_with_internal()
bool bookbinder_copy_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 256 of file activity_actor_definitions.h.
{
             const bookbinder_copy_activity_actor &act = static_cast<const bookbinder_copy_activity_actor &>
                     ( other );
             return rec_id == act.rec_id && book_binder == act.book_binder;
         }
References act, book_binder, other, and rec_id.
clone()
std::unique_ptr<activity_actor> bookbinder_copy_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 270 of file activity_actor_definitions.h.
{
             return std::make_unique<bookbinder_copy_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > bookbinder_copy_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 941 of file activity_actor.cpp.
 {
     bookbinder_copy_activity_actor actor;
     JsonObject jsobj = jsin.get_object();
     jsobj.read( "book_binder", actor.book_binder );
     jsobj.read( "rec_id", actor.rec_id );
     jsobj.read( "pages", actor.pages );
     return actor.clone();
 }
References book_binder, clone(), JsonValue::get_object(), pages, JsonObject::read(), and rec_id.
do_turn()
void bookbinder_copy_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 885 of file activity_actor.cpp.
 {
     if( p.fine_detail_vision_mod() > 4.0f ) {
         p.cancel_activity();
         p.add_msg_if_player( m_info, _( "It's too dark to write!" ) );
         return;
     }
 }
References _, Character::add_msg_if_player(), Character::cancel_activity(), Character::fine_detail_vision_mod(), and m_info.
finish()
void bookbinder_copy_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 894 of file activity_actor.cpp.
 {
     if( !book_binder->can_contain( item( itype_paper, calendar::turn, pages ) ).success() ) {
         debugmsg( "Book binder can not contain '%s' recipe when it should.", rec_id.str() );
         act.set_to_null();
         return;
     }
     std::set<recipe_id> recipes = book_binder->get_saved_recipes();
     if( recipes.emplace( rec_id ).second ) { // if .second is true then recipe was inserted
         book_binder->set_saved_recipes( recipes );
         p.add_msg_if_player( m_good, _( "You copy the recipe for %1$s into your recipe book." ),
                              rec_id->result_name() );
         p.use_charges( itype_paper, pages );
         const std::vector<const item *> writing_tools_filter =
         p.crafting_inventory().items_with( [&]( const item & it ) {
             return it.has_flag( flag_WRITE_MESSAGE ) && it.ammo_remaining() >= it.ammo_required() ;
         } );
         std::vector<tool_comp> writing_tools;
         writing_tools.reserve( writing_tools_filter.size() );
         for( const item *tool : writing_tools_filter ) {
             writing_tools.emplace_back( tool->typeId(), 1 );
         }
         p.consume_tools( writing_tools, pages );
         book_binder->put_in( item( itype_paper, calendar::turn, pages ),
                              pocket_type::MAGAZINE );
     } else {
         debugmsg( "Recipe book already has '%s' recipe when it should not.", rec_id.str() );
     }
     act.set_to_null();
 }
References _, act, Character::add_msg_if_player(), item::ammo_remaining(), item::ammo_required(), book_binder, item::can_contain(), Character::consume_tools(), Character::crafting_inventory(), debugmsg, flag_WRITE_MESSAGE, item::get_saved_recipes(), item::has_flag(), item, visitable::items_with(), itype_paper, m_good, MAGAZINE, pages, item::put_in(), rec_id, recipe::result_name(), item::set_saved_recipes(), string_id< T >::str(), calendar::turn, and Character::use_charges().
get_type()
activity_id bookbinder_copy_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 252 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_BINDER_COPY_RECIPE" );
         }
References activity_id.
pages_for_recipe()
static int bookbinder_copy_activity_actor::pages_for_recipe (const recipe & r) inline static
Definition at line 262 of file activity_actor_definitions.h.
{
             return 1 + r.difficulty / 2;
         }
References recipe::difficulty.
Referenced by iuse::binder_add_recipe(), iuse::binder_manage_recipe(), and start().
serialize()
void bookbinder_copy_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 932 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "book_binder", book_binder );
     jsout.member( "rec_id", rec_id );
     jsout.member( "pages", pages );
     jsout.end_object();
 }
References book_binder, JsonOut::end_object(), JsonOut::member(), pages, rec_id, and JsonOut::start_object().
start()
void bookbinder_copy_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 878 of file activity_actor.cpp.
 {
     pages = bookbinder_copy_activity_actor::pages_for_recipe( *rec_id );
     act.moves_total = to_moves<int>( pages * 10_minutes );
     act.moves_left = to_moves<int>( pages * 10_minutes );
 }
References act, pages, pages_for_recipe(), and rec_id.
Member Data Documentation
book_binder
item_location bookbinder_copy_activity_actor::book_binder private
Definition at line 240 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), and serialize().
pages
int bookbinder_copy_activity_actor::pages = 0 private
Definition at line 242 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), serialize(), and start().
rec_id
recipe_id bookbinder_copy_activity_actor::rec_id private
Definition at line 241 of file activity_actor_definitions.h.
Referenced by can_resume_with_internal(), deserialize(), finish(), serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp