Cataclysm DDA: scent_type Class Reference
scent_type Class Reference
#include <scent_map.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view)
Static Public Member Functions
static void load_scent_type (const JsonObject &jo, const std::string &src)
static const std::vector< scent_type > & get_all ()
static void check_scent_consistency ()
static void reset ()
Public Attributes
bool was_loaded = false
scenttype_id id
std::vector< std::pair< scenttype_id, mod_id > > src
std::set< species_id > receptive_species
Detailed Description
Definition at line 29 of file scent_map.h.
Member Function Documentation
check_scent_consistency()
void scent_type::check_scent_consistency () static
Definition at line 295 of file scent_map.cpp.
 {
     for( const scent_type &styp : get_all() ) {
         for( const species_id &spe : styp.receptive_species ) {
             if( !spe.is_valid() ) {
                 debugmsg( "scent_type %s has invalid species_id %s in receptive_species", styp.id.c_str(),
                           spe.c_str() );
             }
         }
     }
 }
References string_id< T >::c_str(), debugmsg, get_all(), and string_id< T >::is_valid().
Referenced by DynamicDataLoader::check_consistency().
get_all()
const std::vector< scent_type > & scent_type::get_all () static
Definition at line 290 of file scent_map.cpp.
 {
     return scent_factory.get_all();
 }
References anonymous_namespace{scent_map.cpp}::scent_factory.
Referenced by check_scent_consistency().
load()
void scent_type::load (const JsonObject & jo, std::string_view)
Definition at line 284 of file scent_map.cpp.
 {
     assign( jo, "id", id );
     assign( jo, "receptive_species", receptive_species );
 }
References assign(), and receptive_species.
load_scent_type()
void scent_type::load_scent_type (const JsonObject & jo, const std::string & src) static
Definition at line 279 of file scent_map.cpp.
 {
     scent_factory.load( jo, src );
 }
References anonymous_namespace{scent_map.cpp}::scent_factory, and src.
Referenced by DynamicDataLoader::initialize().
reset()
void scent_type::reset () static
Definition at line 307 of file scent_map.cpp.
 {
     scent_factory.reset();
 }
References anonymous_namespace{scent_map.cpp}::scent_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
id
scenttype_id scent_type::id
Definition at line 38 of file scent_map.h.
receptive_species
std::set<species_id> scent_type::receptive_species
Definition at line 40 of file scent_map.h.
Referenced by load(), and monster::scent_move().
src
std::vector<std::pair<scenttype_id, mod_id> > scent_type::src
Definition at line 39 of file scent_map.h.
Referenced by load_scent_type().
was_loaded
bool scent_type::was_loaded = false
Definition at line 36 of file scent_map.h.
The documentation for this class was generated from the following files:
src/scent_map.h
src/scent_map.cpp