Cataclysm DDA: jmapgen_spawn_item Class Reference
jmapgen_spawn_item Class Reference
Place a specific item.
Public Member Functions
jmapgen_spawn_item (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
mapgen_value< itype_id > type
std::string variant
std::string faction
jmapgen_int amount
jmapgen_int chance
std::set< flag_id > flags
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a specific item.
"item": id of item type to spawn. "chance": chance of spawning it (1 = always, otherwise one_in(chance)). "amount": amount of items to spawn. "repeat": number of times to apply this piece
Definition at line 2767 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_spawn_item()
jmapgen_spawn_item::jmapgen_spawn_item (const JsonObject & jsi, const std::string_view) inline
Definition at line 2776 of file mapgen.cpp.
                                                                            :
             type( jsi.get_member( "item" ) )
             , amount( jsi, "amount", 1, 1 )
             , chance( jsi, "chance", 100, 100 )
             , flags( jsi.get_tags<flag_id>( "custom-flags" ) ) {
             if( jsi.has_string( "variant" ) ) {
                 variant = jsi.get_string( "variant" );
             }
             if( jsi.has_string( "faction" ) ) {
                 faction = jsi.get_string( "faction" );
             }
             repeat = jmapgen_int( jsi, "repeat", 1, 1 );
         }
References JsonObject::get_string(), JsonObject::has_string(), mapgen_defer::jsi, jmapgen_piece::repeat, and variant.
Member Function Documentation
apply()
void jmapgen_spawn_item::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2789 of file mapgen.cpp.
{
             itype_id chosen_id = type.get( dat );
             if( chosen_id.is_null() ) {
                 return;
             }
             // Itemgroups apply migrations when being loaded, but we need to migrate
             // individual items here.
             chosen_id = item_controller->migrate_id( chosen_id );
             const int c = chance.get();
             // 100% chance = exactly 1 item, otherwise scale by item spawn rate.
             const float spawn_rate = get_option<float>( "ITEM_SPAWNRATE" );
             int spawn_count = ( c == 100 ) ? 1 : roll_remainder( c * spawn_rate / 100.0f );
             for( int i = 0; i < spawn_count; i++ ) {
                 dat.m.spawn_item( tripoint( x.get(), y.get(), dat.zlevel() + z.get() ), chosen_id, amount.get(),
                                   0, calendar::start_of_cataclysm, 0, flags, variant, faction );
             }
         }
References amount, c, chance, faction, flags, jmapgen_int::get(), string_id< T >::is_null(), item_controller, mapgendata::m, roll_remainder(), map::spawn_item(), calendar::start_of_cataclysm, tripoint, type, variant, and mapgendata::zlevel().
check()
void jmapgen_spawn_item::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 2810 of file mapgen.cpp.
{
             type.check( oter_name, parameters );
         }
References type.
Member Data Documentation
amount
jmapgen_int jmapgen_spawn_item::amount
Definition at line 2773 of file mapgen.cpp.
Referenced by apply().
chance
jmapgen_int jmapgen_spawn_item::chance
Definition at line 2774 of file mapgen.cpp.
Referenced by apply().
faction
std::string jmapgen_spawn_item::faction
Definition at line 2772 of file mapgen.cpp.
Referenced by apply().
flags
std::set<flag_id> jmapgen_spawn_item::flags
Definition at line 2775 of file mapgen.cpp.
Referenced by apply().
type
mapgen_value<itype_id> jmapgen_spawn_item::type
Definition at line 2770 of file mapgen.cpp.
Referenced by apply(), and check().
variant
std::string jmapgen_spawn_item::variant
Definition at line 2771 of file mapgen.cpp.
Referenced by apply(), and jmapgen_spawn_item().
The documentation for this class was generated from the following file:
src/mapgen.cpp