Cataclysm DDA: mmap_file Class Reference
mmap_file Class Reference
#include <mmap_file.h>
Classes
struct handle
Public Member Functions
~mmap_file ()
Static Public Member Functions
static std::shared_ptr< mmap_file > map_file (const std::string &file_path)
static std::shared_ptr< mmap_file > map_file (const fs::path &file_path)
Public Attributes
uint8_t * base = nullptr
size_t len = 0
Private Member Functions
mmap_file ()
Private Attributes
std::shared_ptr< handle > mmap_handle
Detailed Description
Definition at line 10 of file mmap_file.h.
Constructor & Destructor Documentation
~mmap_file()
mmap_file::~mmap_file ()
Definition at line 26 of file mmap_file.cpp.
 {
 #ifdef _WIN32
     if( base != nullptr ) {
         UnmapViewOfFile( base );
     }
 #else
     if( base != nullptr ) {
         munmap( base, len );
     }
 #endif
 }
References base, and len.
mmap_file()
mmap_file::mmap_file () private default
Referenced by map_file().
Member Function Documentation
map_file() [1/2]
std::shared_ptr< mmap_file > mmap_file::map_file (const fs::path & file_path) static
Definition at line 71 of file mmap_file.cpp.
 {
     std::shared_ptr<mmap_file> mapped_file;
 #ifdef _WIN32
     HANDLE file_handle = CreateFileW(
                              file_path.native().c_str(),
                              GENERIC_READ,
                              FILE_SHARE_READ | FILE_SHARE_DELETE,
                              nullptr,
                              OPEN_EXISTING,
                              0,
                              nullptr
                          );
     if( file_handle == INVALID_HANDLE_VALUE ) {
         // Failed to open file.
         return mapped_file;
     }
     LARGE_INTEGER file_size{};
     if( !GetFileSizeEx( file_handle, &file_size ) ) {
         // Failed to get file size.
         return mapped_file;
     }
     HANDLE file_mapping_handle = CreateFileMappingW(
                                      file_handle,
                                      nullptr,
                                      PAGE_READONLY,
                                      0,
                                      0,
                                      nullptr
                                  );
     if( file_mapping_handle == nullptr ) {
         return mapped_file;
     }
     void *map_base = MapViewOfFile(
                          file_mapping_handle,
                          FILE_MAP_READ,
                          0,
                          0,
                          file_size.QuadPart
                      );
     if( map_base == nullptr ) {
         // Failed to mmap file.
         return mapped_file;
     }
     mapped_file = std::shared_ptr<mmap_file> { new mmap_file() };
     mapped_file->mmap_handle = std::make_shared<handle>();
     mapped_file->mmap_handle->file = file_handle;
     mapped_file->mmap_handle->file_mapping = file_mapping_handle;
     mapped_file->base = static_cast<uint8_t *>( map_base );
     mapped_file->len = file_size.QuadPart;
 #else
     const std::string &file_path_string = file_path.native();
     std::error_code ec;
     size_t file_size = fs::file_size( file_path, ec );
     if( ec ) {
         return mapped_file;
     }
     int fd = open( file_path_string.c_str(), O_RDONLY );
     if( fd == -1 ) {
         return mapped_file;
     }
     on_out_of_scope close_file_guard( [&] { close( fd ); } );
     void *map_base = mmap( nullptr, file_size, PROT_READ, MAP_PRIVATE, fd, 0 );
     if( !map_base ) {
         return mapped_file;
     }
     mapped_file = std::shared_ptr<mmap_file> { new mmap_file() };
     // No need for an underlying handle.
     mapped_file->base = static_cast<uint8_t *>( map_base );
     mapped_file->len = file_size;
 #endif
     return mapped_file;
 }
References close(), mmap_file(), and open().
map_file() [2/2]
std::shared_ptr< mmap_file > mmap_file::map_file (const std::string & file_path) static
Definition at line 66 of file mmap_file.cpp.
 {
     return map_file( fs::u8path( file_path ) );
 }
Referenced by flexbuffer_disk_cache::load_flexbuffer_if_not_stale(), and flexbuffer_cache::parse().
Member Data Documentation
base
uint8_t* mmap_file::base = nullptr
Definition at line 18 of file mmap_file.h.
Referenced by ~mmap_file().
len
size_t mmap_file::len = 0
Definition at line 19 of file mmap_file.h.
Referenced by ~mmap_file().
mmap_handle
std::shared_ptr<handle> mmap_file::mmap_handle private
Definition at line 26 of file mmap_file.h.
The documentation for this class was generated from the following files:
src/mmap_file.h
src/mmap_file.cpp