Cataclysm DDA: teleporter_list Class Reference
teleporter_list Class Reference
#include <magic_teleporter_list.h>
Public Member Functions
bool knows_translocator (const tripoint_abs_omt &omt_pos) const
bool activate_teleporter (const tripoint_abs_omt &omt_pt, const tripoint &local_pt)
void deactivate_teleporter (const tripoint_abs_omt &omt_pt, const tripoint &local_pt)
void translocate (const std::set< tripoint > &targets)
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
Private Member Functions
std::optional< tripoint_abs_omt > choose_teleport_location ()
bool place_avatar_overmap (Character &you, const tripoint_abs_omt &omt_pt) const
Private Attributes
std::map< tripoint_abs_omt, std::string > known_teleporters
Detailed Description
Definition at line 17 of file magic_teleporter_list.h.
Member Function Documentation
activate_teleporter()
bool teleporter_list::activate_teleporter (const tripoint_abs_omt & omt_pt, const tripoint & local_pt)
Definition at line 49 of file magic_teleporter_list.cpp.
 {
     std::string point_name;
     std::string title = _( "Name this gate." );
     popup_string( point_name, title );
     return known_teleporters.emplace( omt_pt, point_name ).second;
 }
References _, known_teleporters, popup_string(), and music::title.
Referenced by iexamine::translocator().
choose_teleport_location()
std::optional< tripoint_abs_omt > teleporter_list::choose_teleport_location () private
Definition at line 188 of file magic_teleporter_list.cpp.
 {
     std::optional<tripoint_abs_omt> ret = std::nullopt;
     uilist teleport_selector;
     teleport_selector.w_height_setup = 24;
     int index = 0;
     int column_width = 25;
     std::map<int, tripoint_abs_omt> index_pairs;
     for( const std::pair<const tripoint_abs_omt, std::string> &gate : known_teleporters ) {
         teleport_selector.addentry( index, true, 0, gate.second );
         column_width = std::max( column_width, utf8_width( gate.second ) );
         index_pairs.emplace( index, gate.first );
         index++;
     }
     teleporter_callback cb( index_pairs );
     teleport_selector.callback = &cb;
     teleport_selector.w_width_setup = 38 + column_width;
     teleport_selector.pad_right_setup = 33;
     teleport_selector.title = _( "Choose Translocator Gate" );
     teleport_selector.query();
     if( teleport_selector.ret >= 0 ) {
         ret = index_pairs[teleport_selector.ret];
     }
     return ret;
 }
References _, uilist::addentry(), uilist::callback, known_teleporters, max(), uilist::pad_right_setup, uilist::query(), cata::hash64_detail::ret, uilist::ret, uilist::title, utf8_width(), uilist::w_height_setup, and uilist::w_width_setup.
Referenced by translocate().
deactivate_teleporter()
void teleporter_list::deactivate_teleporter (const tripoint_abs_omt & omt_pt, const tripoint & local_pt)
Definition at line 57 of file magic_teleporter_list.cpp.
 {
     known_teleporters.erase( omt_pt );
 }
References known_teleporters.
Referenced by translocate(), and iexamine::translocator().
deserialize()
void teleporter_list::deserialize (const JsonObject & data)
Definition at line 147 of file magic_teleporter_list.cpp.
 {
     for( JsonObject jo : data.get_array( "known_teleporters" ) ) {
         tripoint_abs_omt temp_pos;
         jo.read( "position", temp_pos );
         std::string name;
         jo.read( "name", name );
         known_teleporters.emplace( temp_pos, name );
     }
 }
References JsonObject::get_array(), known_teleporters, and om_direction::name().
knows_translocator()
bool teleporter_list::knows_translocator (const tripoint_abs_omt & omt_pos) const
Definition at line 125 of file magic_teleporter_list.cpp.
 {
     return known_teleporters.find( omt_pos ) != known_teleporters.end();
 }
References known_teleporters.
Referenced by iexamine::translocator().
place_avatar_overmap()
bool teleporter_list::place_avatar_overmap (Character & you, const tripoint_abs_omt & omt_pt) const private
Definition at line 79 of file magic_teleporter_list.cpp.
 {
     tinymap omt_dest;
     omt_dest.load( omt_pt, true );
     std::optional<tripoint> global_dest = find_valid_teleporters_omt( omt_pt );
     if( !global_dest ) {
         return false;
     }
     tripoint local_dest = omt_dest.getlocal( *global_dest ) + point( 60, 60 );
     you.add_effect( effect_ignore_fall_damage, 1_seconds, false, 0, true );
     g->place_player_overmap( omt_pt );
     g->place_player( local_dest );
     return true;
 }
References Creature::add_effect(), effect_ignore_fall_damage, find_valid_teleporters_omt(), g, tinymap::getlocal(), tinymap::load(), and point.
Referenced by translocate().
serialize()
void teleporter_list::serialize (JsonOut & json) const
Definition at line 130 of file magic_teleporter_list.cpp.
 {
     json.start_object();
     json.member( "known_teleporters" );
     json.start_array();
     for( const std::pair<const tripoint_abs_omt, std::string> &pair : known_teleporters ) {
         json.start_object();
         json.member( "position", pair.first );
         json.member( "name", pair.second );
         json.end_object();
     }
     json.end_array();
     json.end_object();
 }
References JsonOut::end_array(), JsonOut::end_object(), known_teleporters, JsonOut::member(), JsonOut::start_array(), and JsonOut::start_object().
translocate()
void teleporter_list::translocate (const std::set< tripoint > & targets)
Definition at line 94 of file magic_teleporter_list.cpp.
 {
     if( known_teleporters.empty() ) {
         // we can't go somewhere if we don't know how to get there!
         add_msg( m_bad, _( "No translocator target known." ) );
         return;
     }
     std::optional<tripoint_abs_omt> omt_dest = choose_teleport_location();
     if( !omt_dest ) {
         add_msg( _( "Teleport canceled." ) );
         return;
     }
     bool valid_targets = false;
     for( const tripoint &pt : targets ) {
         Character *you = get_creature_tracker().creature_at<Character>( pt );
         if( you && you->is_avatar() ) {
             valid_targets = true;
             if( !place_avatar_overmap( *you, *omt_dest ) ) {
                 add_msg( _( "Failed to teleport.  Teleporter obstructed or destroyed." ) );
                 deactivate_teleporter( *omt_dest, pt );
             }
         }
     }
     if( !valid_targets ) {
         add_msg( _( "No valid targets to teleport." ) );
     }
 }
References _, add_msg(), choose_teleport_location(), creature_tracker::creature_at(), deactivate_teleporter(), get_creature_tracker(), Creature::is_avatar(), known_teleporters, m_bad, and place_avatar_overmap().
Referenced by spell_effect::translocate().
Member Data Documentation
known_teleporters
std::map<tripoint_abs_omt, std::string> teleporter_list::known_teleporters private
Definition at line 21 of file magic_teleporter_list.h.
Referenced by activate_teleporter(), choose_teleport_location(), deactivate_teleporter(), deserialize(), knows_translocator(), serialize(), and translocate().
The documentation for this class was generated from the following files:
src/magic_teleporter_list.h
src/magic_teleporter_list.cpp