Cataclysm DDA: coords::coord_point< Point, Origin, Scale, InBounds > Class Template Reference
coords::coord_point< Point, Origin, Scale, InBounds > Class Template Reference
#include <coordinates.h>
Public Types
using this_as_tripoint_ob = coord_point< tripoint, Origin, Scale >
using this_as_point = coord_point< point, Origin, Scale, InBounds >
using this_as_ob = coord_point< Point, Origin, Scale >
Public Member Functions
operator this_as_ob () const
constexpr auto xy () const
Public Member Functions inherited from coords::coord_point_mut< Point, coord_point< point, Origin, Scale, false >, false >
constexpr coord_point_mut ()=default
constexpr coord_point_mut (const Point &p)
constexpr coord_point_mut (const coord_point< point, Origin, Scale, false > &p, T z)
constexpr coord_point_mut (T x, T y)
constexpr coord_point_mut (T x, T y, T z)
constexpr const Point & raw () const
constexpr Point & raw ()
constexpr auto x () const
constexpr auto & x ()
constexpr auto y () const
constexpr auto & y ()
constexpr auto z () const
constexpr auto & z ()
void deserialize (const JsonValue &jv)
Public Member Functions inherited from coords::coord_point_base< Point >
std::string to_string () const
std::string to_string_writable () const
void serialize (JsonOut &jsout) const
Static Public Member Functions
template<typename T >
static constexpr coord_point make_unchecked (T x, T y)
template<typename T >
static constexpr coord_point make_unchecked (T x, T y, T z)
static constexpr coord_point make_unchecked (const this_as_ob &other)
static constexpr coord_point make_unchecked (const Point &other)
template<typename T >
static constexpr coord_point make_unchecked (const this_as_point &other, T z)
template<typename T >
static constexpr coord_point make_unchecked (const point &other, T z)
Static Public Attributes
static constexpr int dimension = Point::dimension
Private Types
using base = coord_point_mut< Point, coord_point< point, Origin, Scale, InBounds >, InBounds >
Friends
this_as_ob operator+ (const coord_point &l, const point &r)
this_as_tripoint_ob operator+ (const coord_point &l, const tripoint &r)
this_as_ob operator+ (const point &l, const coord_point &r)
this_as_tripoint_ob operator+ (const tripoint &l, const coord_point &r)
this_as_ob operator- (const coord_point &l, const point &r)
this_as_tripoint_ob operator- (const coord_point &l, const tripoint &r)
Additional Inherited Members
Protected Member Functions inherited from coords::coord_point_base< Point >
constexpr coord_point_base ()=default
template<typename... Ts>
constexpr coord_point_base (Ts &&... ts)
Protected Attributes inherited from coords::coord_point_base< Point >
Point raw_
Detailed Description
template<typename Point, origin Origin, scale Scale, bool InBounds = false>
class coords::coord_point< Point, Origin, Scale, InBounds >
Definition at line 228 of file coordinates.h.
Member Typedef Documentation
base
template<typename Point , origin Origin, scale Scale, bool InBounds = false> using coords::coord_point< Point, Origin, Scale, InBounds >::base = coord_point_mut<Point, coord_point<point, Origin, Scale, InBounds>, InBounds> private
Definition at line 231 of file coordinates.h.
this_as_ob
template<typename Point , origin Origin, scale Scale, bool InBounds = false> using coords::coord_point< Point, Origin, Scale, InBounds >::this_as_ob = coord_point<Point, Origin, Scale>
Definition at line 239 of file coordinates.h.
this_as_point
template<typename Point , origin Origin, scale Scale, bool InBounds = false> using coords::coord_point< Point, Origin, Scale, InBounds >::this_as_point = coord_point<point, Origin, Scale, InBounds>
Definition at line 238 of file coordinates.h.
this_as_tripoint_ob
template<typename Point , origin Origin, scale Scale, bool InBounds = false> using coords::coord_point< Point, Origin, Scale, InBounds >::this_as_tripoint_ob = coord_point<tripoint, Origin, Scale>
Definition at line 237 of file coordinates.h.
Member Function Documentation
make_unchecked() [1/6]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> static constexpr coord_point coords::coord_point< Point, Origin, Scale, InBounds >::make_unchecked (const Point & other) inline static constexpr
Definition at line 255 of file coordinates.h.
{
             return coord_point( other );
         }
References other.
make_unchecked() [2/6]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> template<typename T > static constexpr coord_point coords::coord_point< Point, Origin, Scale, InBounds >::make_unchecked (const point & other, T z) inline static constexpr
Definition at line 263 of file coordinates.h.
{
             return coord_point( other.x, other.y, z );
         }
References other.
make_unchecked() [3/6]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> static constexpr coord_point coords::coord_point< Point, Origin, Scale, InBounds >::make_unchecked (const this_as_ob & other) inline static constexpr
Definition at line 252 of file coordinates.h.
{
             return coord_point( other.raw() );
         }
References other.
make_unchecked() [4/6]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> template<typename T > static constexpr coord_point coords::coord_point< Point, Origin, Scale, InBounds >::make_unchecked (const this_as_point & other, T z) inline static constexpr
Definition at line 259 of file coordinates.h.
{
             return coord_point( other, z );
         }
References other.
make_unchecked() [5/6]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> template<typename T > static constexpr coord_point coords::coord_point< Point, Origin, Scale, InBounds >::make_unchecked (T x, T y) inline static constexpr
Definition at line 245 of file coordinates.h.
{
             return coord_point( x, y );
         }
make_unchecked() [6/6]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> template<typename T > static constexpr coord_point coords::coord_point< Point, Origin, Scale, InBounds >::make_unchecked (T x, T y, T z) inline static constexpr
Definition at line 249 of file coordinates.h.
{
             return coord_point( x, y, z );
         }
operator this_as_ob()
template<typename Point , origin Origin, scale Scale, bool InBounds = false> coords::coord_point< Point, Origin, Scale, InBounds >::operator this_as_ob () const inline
Definition at line 269 of file coordinates.h.
{
             return this_as_ob( this->raw() );
         }
xy()
template<typename Point , origin Origin, scale Scale, bool InBounds = false> constexpr auto coords::coord_point< Point, Origin, Scale, InBounds >::xy () const inline constexpr
Definition at line 273 of file coordinates.h.
{
             return this_as_point::make_unchecked( this->raw().xy() );
         }
Referenced by anonymous_namespace{iexamine.cpp}::_choose_elevator_destz(), talk_function::abandon_camp(), computer_session::action_amigara_log(), mission_data::add(), overmapbuffer::add_camp(), overmap::add_extra(), overmapbuffer::add_nemesis(), overmap::add_note(), talk_function::assign_camp(), map::bub_from_abs(), overmap::build_connection(), overmap::build_lab(), display::colorized_overmap_text(), talk_function::companion_choose(), vehicle::autodrive_controller::compute_next_step(), npc::consume_food_from_camp(), map_memory::coord_pair::coord_pair(), iuse::directional_antenna(), faction_manager::display(), overmap_ui::display(), vehicle::do_autodrive(), overmap_ui::draw_ascii(), game::draw_minimap(), overmap_ui::draw_notes(), overmap_ui::draw_overmap_chunk(), game::draw_ter(), iexamine::elevator(), overmap::explored(), overmap::extra(), conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), pf::find_overmap_path(), overmap::find_terrain(), chop_tree_activity_actor::finish(), overmapbuffer::fix_mongroups(), overmapbuffer::fix_nemesis(), overmapbuffer::fix_npcs(), overmap::generate_over(), overmap::generate_sub(), map::get_active_items_in_radius(), get_basecamp(), game::get_cur_om(), overmapbuffer::get_existing_om_global(), overmapbuffer::get_extras(), overmapbuffer::get_notes(), overmapbuffer::get_npcs_near(), overmapbuffer::get_npcs_near_omt(), overmapbuffer::get_om_global(), overmapbuffer::get_vehicle(), map::getabs(), map::getglobal(), map::getlocal(), npc::go_to_omt_destination(), overmapbuffer::groups_at(), overmapbuffer::has_camp(), overmap::has_extra(), overmap::has_note(), overmapbuffer::has_vehicle(), overmapbuffer::insert_npc(), overmap::is_explored(), overmap::is_marked_dangerous(), mission_start::kill_nemesis(), link_up_actor::link_to_veh_app(), monster::load(), game::load_npcs(), map::loadn(), overmap::mark_note_dangerous(), map::mirror(), display::mission_arrow_offset(), overmap::move_hordes(), overmapbuffer::move_vehicle(), MapExtras::mx_city_trap(), MapExtras::mx_fungal_zone(), MapExtras::mx_portal_in(), talk_function::name_mission_tabs(), overmap::note(), overmap::note_danger_radius(), om_companion_path(), om_set_hide_site(), talk_function::om_simple_dir(), om_target_tile(), npc::on_move(), npc_dist_to_player::operator()(), Character::overmap_los(), display::overmap_position_text(), display::overmap_tile_symbol_color(), fixed_overmap_special_data::place(), overmap::place_building(), overmap::place_cities(), overmap::place_forest_trails(), overmap::place_forests(), overmap::place_lakes(), overmap::place_oceans(), overmap::place_radios(), overmap::place_rivers(), overmap::place_swamps(), overmap_ui::place_ter_or_special(), map::point_within_camp(), map_memory::prepare_region(), map::process_items(), Character::process_turn(), coords::project_remain(), overmapbuffer::remove_camp(), map::rotate(), map_memory::save(), map::saven(), overmap_ui::search(), overmap::seen(), overmap::set_seen(), vehicle::set_submap_moved(), overmap::signal_hordes(), overmap::signal_nemesis(), map::spawn_monsters_submap(), basecamp::start_clearcut(), basecamp::start_cut_logs(), basecamp::start_fortifications(), game::start_game(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), basecamp::survey_field_return(), basecamp::survey_return(), mission_util::target_closest_lab_entrance(), overmap::ter_set(), overmap::ter_unsafe(), zone_data::toggle_display(), game::try_get_left_click_action(), game::try_get_right_click_action(), game::update_overmap_seen(), map::vertical_shift(), game::vertical_shift(), mongroup::wander(), and monster::will_reach().
Friends And Related Function Documentation
operator+ [1/4]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> this_as_ob operator+ (const coord_point< Point, Origin, Scale, InBounds > & l, const point & r) friend
Definition at line 277 of file coordinates.h.
{
             return this_as_ob( l.raw() + r );
         }
operator+ [2/4]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> this_as_tripoint_ob operator+ (const coord_point< Point, Origin, Scale, InBounds > & l, const tripoint & r) friend
Definition at line 281 of file coordinates.h.
{
             return this_as_tripoint_ob( l.raw() + r );
         }
operator+ [3/4]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> this_as_ob operator+ (const point & l, const coord_point< Point, Origin, Scale, InBounds > & r) friend
Definition at line 285 of file coordinates.h.
{
             return this_as_ob( l + r.raw() );
         }
operator+ [4/4]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> this_as_tripoint_ob operator+ (const tripoint & l, const coord_point< Point, Origin, Scale, InBounds > & r) friend
Definition at line 289 of file coordinates.h.
{
             return this_as_tripoint_ob( l + r.raw() );
         }
operator- [1/2]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> this_as_ob operator- (const coord_point< Point, Origin, Scale, InBounds > & l, const point & r) friend
Definition at line 293 of file coordinates.h.
{
             return this_as_ob( l.raw() - r );
         }
operator- [2/2]
template<typename Point , origin Origin, scale Scale, bool InBounds = false> this_as_tripoint_ob operator- (const coord_point< Point, Origin, Scale, InBounds > & l, const tripoint & r) friend
Definition at line 297 of file coordinates.h.
{
             return this_as_tripoint_ob( l.raw() - r );
         }
Member Data Documentation
dimension
template<typename Point , origin Origin, scale Scale, bool InBounds = false> constexpr int coords::coord_point< Point, Origin, Scale, InBounds >::dimension = Point::dimension static constexpr
Definition at line 235 of file coordinates.h.
The documentation for this class was generated from the following file:
src/coordinates.h