Cataclysm DDA: exosuit_interact Class Reference
exosuit_interact Class Reference
Static Public Member Functions
static int run (item *it)
Private Member Functions
exosuit_interact (item *it)
~exosuit_interact ()=default
void init_windows ()
void draw_menu ()
void draw_iteminfo ()
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
void interact_loop ()
int insert_replace_activate_mod (item_pocket *pkt, item *it)
Static Private Member Functions
static std::string get_pocket_name (const item_pocket *pkt)
Private Attributes
item * suit
weak_ptr_fast< ui_adaptor > ui
input_context ctxt
catacurses::window w_border
catacurses::window w_info
catacurses::window w_menu
std::map< int, inclusive_rectangle< point > > pkt_map
int moves = 0
int pocket_count = 0
int cur_pocket = 0
int scroll_pos = 0
int height = 0
const int height_default = 20
int width_info = 30
int width_menu = 30
int sel_frame = 0
Detailed Description
Definition at line 1973 of file iuse.cpp.
Constructor & Destructor Documentation
exosuit_interact()
exosuit_interact::exosuit_interact (item * it) inline explicit private
Definition at line 1983 of file iuse.cpp.
                                               : suit( it ), ctxt( "", keyboard_mode::keycode ) {
             ctxt.register_navigate_ui_list();
             ctxt.register_leftright();
             ctxt.register_action( "SCROLL_INFOBOX_UP" );
             ctxt.register_action( "SCROLL_INFOBOX_DOWN" );
             ctxt.register_action( "CONFIRM" );
             ctxt.register_action( "QUIT" );
             // mouse selection
             ctxt.register_action( "SELECT" );
             ctxt.register_action( "SEC_SELECT" );
             ctxt.register_action( "MOUSE_MOVE" );
             ctxt.register_action( "SCROLL_UP" );
             ctxt.register_action( "SCROLL_DOWN" );
             pocket_count = it->get_all_contained_pockets().size();
             height = std::max( pocket_count, height_default ) + 2;
             width_menu = 30;
             for( const item_pocket *pkt : it->get_all_contained_pockets() ) {
                 int tmp = utf8_width( get_pocket_name( pkt ) );
                 if( tmp > width_menu ) {
                     width_menu = tmp;
                 }
             }
             width_menu = std::min( width_menu, 50 );
             width_info = 80 - width_menu;
             moves = 0;
         }
References ctxt, item::get_all_contained_pockets(), get_pocket_name(), height, height_default, max(), min(), moves, pocket_count, input_context::register_action(), input_context::register_leftright(), input_context::register_navigate_ui_list(), utf8_width(), width_info, and width_menu.
~exosuit_interact()
exosuit_interact::~exosuit_interact () private default
Member Function Documentation
create_or_get_ui_adaptor()
shared_ptr_fast<ui_adaptor> exosuit_interact::create_or_get_ui_adaptor () inline private
Definition at line 2085 of file iuse.cpp.
{
             shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
             if( !current_ui ) {
                 ui = current_ui = make_shared_fast<ui_adaptor>();
                 current_ui->on_screen_resize( [this]( ui_adaptor & cui ) {
                     init_windows();
                     cui.position_from_window( w_border );
                 } );
                 current_ui->mark_resize();
                 current_ui->on_redraw( [this]( const ui_adaptor & ) {
                     draw_border( w_border, c_white, suit->tname(), c_light_green );
                     for( int i = 1; i < height - 1; i++ ) {
                         mvwputch( w_border, point( width_menu + 1, i ), c_white, LINE_XOXO );
                     }
                     mvwputch( w_border, point( width_menu + 1, height - 1 ), c_white, LINE_XXOX );
                     wnoutrefresh( w_border );
                     draw_menu();
                     draw_iteminfo();
                 } );
             }
             return current_ui;
         }
References c_light_green, c_white, draw_border(), draw_iteminfo(), draw_menu(), height, init_windows(), LINE_XOXO, LINE_XXOX, mvwputch(), point, ui_adaptor::position_from_window(), suit, item::tname(), w_border, width_menu, and catacurses::wnoutrefresh().
Referenced by interact_loop().
draw_iteminfo()
void exosuit_interact::draw_iteminfo () inline private
Definition at line 2070 of file iuse.cpp.
{
             std::vector<iteminfo> dummy;
             std::vector<iteminfo> suitinfo;
             item_pocket *pkt = suit->get_all_contained_pockets()[cur_pocket];
             pkt->general_info( suitinfo, cur_pocket, true );
             pkt->contents_info( suitinfo, cur_pocket, true );
             item_info_data data( suit->tname(), suit->type_name(), suitinfo, dummy, scroll_pos );
             data.without_getch = true;
             data.without_border = true;
             data.scrollbar_left = false;
             data.use_full_win = true;
             data.padding = 0;
             draw_item_info( w_info, data );
         }
References item_pocket::contents_info(), cur_pocket, draw_item_info(), item_pocket::general_info(), item::get_all_contained_pockets(), item_info_data::padding, scroll_pos, item_info_data::scrollbar_left, suit, item::tname(), item::type_name(), item_info_data::use_full_win, w_info, item_info_data::without_border, and item_info_data::without_getch.
Referenced by create_or_get_ui_adaptor().
draw_menu()
void exosuit_interact::draw_menu () inline private
Definition at line 2049 of file iuse.cpp.
{
             pkt_map.clear();
             // info box
             pkt_map.emplace( -1, inclusive_rectangle<point>( point( 2 + width_menu, 1 ),
                              point( 2 + width_menu + width_info, height - 2 ) ) );
             werase( w_menu );
             int row = 0;
             for( const item_pocket *pkt : suit->get_all_contained_pockets() ) {
                 nc_color colr = row == cur_pocket ? h_white : c_white;
                 std::string txt = get_pocket_name( pkt );
                 int remaining = width_menu - utf8_width( txt, true );
                 if( remaining > 0 ) {
                     txt.append( remaining, ' ' );
                 }
                 trim_and_print( w_menu, point( 0, row ), width_menu, colr, txt );
                 pkt_map.emplace( row, inclusive_rectangle<point>( point( 0, row ), point( width_menu, row ) ) );
                 row++;
             }
             wnoutrefresh( w_menu );
         }
References c_white, cur_pocket, item::get_all_contained_pockets(), get_pocket_name(), h_white, height, pkt_map, point, suit, trim_and_print(), utf8_width(), w_menu, catacurses::werase(), width_info, width_menu, and catacurses::wnoutrefresh().
Referenced by create_or_get_ui_adaptor().
get_pocket_name()
static std::string exosuit_interact::get_pocket_name (const item_pocket * pkt) inline static private
Definition at line 2028 of file iuse.cpp.
{
             if( !pkt->get_pocket_data()->pocket_name.empty() ) {
                 return pkt->get_pocket_data()->pocket_name.translated();
             }
             const std::set<flag_id> flags = pkt->get_pocket_data()->get_flag_restrictions();
             return enumerate_as_string( flags, []( const flag_id & fid ) {
                 if( fid->name().empty() ) {
                     return fid.str();
                 }
                 return fid->name();
             } );
         }
References translation::empty(), enumerate_as_string(), pocket_data::get_flag_restrictions(), item_pocket::get_pocket_data(), json_flag::name(), pocket_data::pocket_name, and translation::translated().
Referenced by draw_menu(), and exosuit_interact().
init_windows()
void exosuit_interact::init_windows () inline private
Definition at line 2041 of file iuse.cpp.
{
             const point topleft( TERMX / 2 - ( width_info + width_menu + 3 ) / 2, TERMY / 2 - height / 2 );
             //NOLINTNEXTLINE(cata-use-named-point-constants)
             w_menu = catacurses::newwin( height - 2, width_menu, topleft + point( 1, 1 ) );
             w_info = catacurses::newwin( height - 2, width_info, topleft + point( 2 + width_menu, 1 ) );
             w_border = catacurses::newwin( height, width_info + width_menu + 3, topleft );
         }
References height, catacurses::newwin(), point, TERMX, TERMY, w_border, w_info, w_menu, width_info, and width_menu.
Referenced by create_or_get_ui_adaptor().
insert_replace_activate_mod()
int exosuit_interact::insert_replace_activate_mod (item_pocket * pkt, item * it) inline private
Definition at line 2171 of file iuse.cpp.
{
             Character &c = get_player_character();
             map &here = get_map();
             const std::set<flag_id> flags = pkt->get_pocket_data()->get_flag_restrictions();
             if( flags.empty() ) {
                 //~ Modular exoskeletons require pocket restrictions to insert modules. %s = pocket name.
                 popup( _( "%s doesn't define any restrictions for modules!" ), get_pocket_name( pkt ) );
                 return 0;
             }
             // If pocket already contains a module, ask to unload or replace
             const bool not_empty = !pkt->empty();
             if( not_empty ) {
                 item *mod_it = pkt->all_items_top().front();
                 std::string mod_name = mod_it->tname();
                 uilist amenu;
                 //~ Prompt the player to handle the module inside the modular exoskeleton
                 amenu.text = _( "What to do with the existing module?" );
                 amenu.addentry( -1, true, MENU_AUTOASSIGN, _( "Unload everything from this %s" ),
                                 get_pocket_name( pkt ) );
                 amenu.addentry( -1, true, MENU_AUTOASSIGN, _( "Replace the %s" ), mod_name );
                 amenu.addentry( -1, mod_it->has_relic_activation() || mod_it->type->has_use(), MENU_AUTOASSIGN,
                                 mod_it->active ? _( "Deactivate the %s" ) : _( "Activate the %s" ), mod_name );
                 amenu.addentry( -1, mod_it->is_reloadable() && c.can_reload( *mod_it ), MENU_AUTOASSIGN,
                                 _( "Reload the %s" ), mod_name );
                 amenu.addentry( -1, !mod_it->is_container_empty(), MENU_AUTOASSIGN, _( "Unload the %s" ),
                                 mod_name );
                 amenu.query();
                 int ret = amenu.ret;
                 item_location loc_it;
                 item_location held = c.get_wielded_item();
                 if( !!held && held->has_item( *mod_it ) ) {
                     loc_it = item_location( held, mod_it );
                 } else {
                     for( const item_location &loc : c.top_items_loc() ) {
                         if( loc->has_item( *mod_it ) ) {
                             loc_it = item_location( loc, mod_it );
                             break;
                         }
                     }
                 }
                 if( ret < 0 || ret > 4 ) {
                     return 0;
                 } else if( ret == 0 ) {
                     // Unload existing module
                     pkt->remove_items_if( [&c, &here]( const item & i ) {
                         here.add_item_or_charges( c.pos(), i );
                         return true;
                     } );
                     return to_moves<int>( 5_seconds );
                 } else if( ret == 2 ) {
                     if( !!loc_it ) {
                         avatar_action::use_item( get_avatar(), loc_it );
                     }
                     return 0;
                 } else if( ret == 3 ) {
                     if( !!loc_it ) {
                         g->reload( loc_it );
                     }
                     return 0;
                 } else if( ret == 4 ) {
                     if( !!loc_it ) {
                         c.unload( loc_it );
                     }
                     return 0;
                 }
             }
             const item_filter filter = [&flags, pkt, it]( const item & i ) {
                 return i.has_any_flag( flags ) && ( pkt->empty() || !it->has_item( i ) ) &&
                        pkt->can_contain( i ).success();
             };
             std::vector<item_location> candidates;
             for( item *i : c.items_with( filter ) ) {
                 candidates.emplace_back( c, i );
             }
             for( const tripoint &p : here.points_in_radius( c.pos(), PICKUP_RANGE ) ) {
                 for( item &i : here.i_at( p ) ) {
                     if( filter( i ) ) {
                         candidates.emplace_back( map_cursor( p ), &i );
                     }
                 }
             }
             if( candidates.empty() ) {
                 //~ The player has nothing that fits in the modular exoskeleton's pocket
                 popup( _( "You don't have anything compatible with this module!" ) );
                 return 0;
             }
             //~ Prompt the player to select an item to attach to the modular exoskeleton's pocket (%s)
             uilist imenu( string_format( _( "Which module to attach to the %s?" ), get_pocket_name( pkt ) ), {} );
             for( const item_location &i : candidates ) {
                 imenu.addentry( -1, true, MENU_AUTOASSIGN, i->tname() );
             }
             imenu.query();
             int ret = imenu.ret;
             if( ret < 0 || static_cast<size_t>( ret ) >= candidates.size() ) {
                 // Cancelled
                 return 0;
             }
             int moves = 0;
             // Unload existing module
             if( not_empty ) {
                 pkt->remove_items_if( [&c, &here]( const item & i ) {
                     here.add_item_or_charges( c.pos(), i );
                     return true;
                 } );
                 moves += to_moves<int>( 5_seconds );
             }
             ret_val<item *> rval = pkt->insert_item( *candidates[ret] );
             if( rval.success() ) {
                 candidates[ret].remove_item();
                 moves += to_moves<int>( 5_seconds );
                 return moves;
             }
             debugmsg( "Could not insert item \"%s\" into pocket \"%s\": %s",
                       candidates[ret]->type_name(), get_pocket_name( pkt ), rval.str() );
             return moves;
         }
References _, item::active, map::add_item_or_charges(), uilist::addentry(), item_pocket::all_items_top(), c, item_pocket::can_contain(), debugmsg, item_pocket::empty(), filter, g, get_avatar(), pocket_data::get_flag_restrictions(), get_map(), get_player_character(), item_pocket::get_pocket_data(), visitable::has_item(), item::has_relic_activation(), itype::has_use(), map::i_at(), item_pocket::insert_item(), item::is_container_empty(), item::is_reloadable(), MENU_AUTOASSIGN, PICKUP_RANGE, map::points_in_radius(), popup(), uilist::query(), item_pocket::remove_items_if(), cata::hash64_detail::ret, uilist::ret, ret_val_common::str(), string_format(), ret_val_common::success(), uilist::text, item::tname(), item::type, and avatar_action::use_item().
Referenced by interact_loop().
interact_loop()
void exosuit_interact::interact_loop () inline private
Definition at line 2108 of file iuse.cpp.
{
             bool done = false;
             shared_ptr_fast<ui_adaptor> current_ui = create_or_get_ui_adaptor();
             while( !done ) {
                 ui_manager::redraw();
                 std::string action = ctxt.handle_input();
                 if( action == "MOUSE_MOVE" || action == "SELECT" ) {
                     std::optional<point> coord = ctxt.get_coordinates_text( w_border );
                     if( !!coord ) {
                         int tmp_frame = 0;
                         run_for_point_in<int, point>( pkt_map, *coord,
                         [&tmp_frame]( const std::pair<int, inclusive_rectangle<point>> &p ) {
                             if( p.first == -1 ) {
                                 tmp_frame = 1;
                             }
                         } );
                         sel_frame = tmp_frame;
                     }
                     coord = ctxt.get_coordinates_text( w_menu );
                     if( !!coord ) {
                         int tmp_pocket = cur_pocket;
                         run_for_point_in<int, point>( pkt_map, *coord,
                         [&tmp_pocket, &action]( const std::pair<int, inclusive_rectangle<point>> &p ) {
                             if( p.first >= 0 ) {
                                 tmp_pocket = p.first;
                                 if( action == "SELECT" ) {
                                     action = "CONFIRM";
                                 }
                             }
                         } );
                         cur_pocket = tmp_pocket;
                     }
                 } else if( action == "SCROLL_UP" || action == "SCROLL_DOWN" ) {
                     if( sel_frame == 0 ) {
                         action = action == "SCROLL_UP" ? "UP" : "DOWN";
                     } else {
                         action = action == "SCROLL_UP" ? "SCROLL_INFOBOX_UP" : "SCROLL_INFOBOX_DOWN";
                     }
                 }
                 if( action == "QUIT" || action == "SEC_SELECT" ) {
                     scroll_pos = 0;
                     done = true;
                 } else if( action == "CONFIRM" ) {
                     scroll_pos = 0;
                     int nmoves = insert_replace_activate_mod(
                                      suit->get_all_contained_pockets()[cur_pocket], suit );
                     moves = moves > nmoves ? moves : nmoves;
                     if( !get_player_character().activity.is_null() ) {
                         done = true;
                     }
                 } else if( navigate_ui_list( action, cur_pocket, 5, pocket_count, true ) ) {
                     scroll_pos = 0;
                     sel_frame = 0;
                 } else if( action == "SCROLL_INFOBOX_UP" ) {
                     scroll_pos--;
                     sel_frame = 1;
                 } else if( action == "SCROLL_INFOBOX_DOWN" ) {
                     scroll_pos++;
                     sel_frame = 1;
                 }
             }
         }
References action, create_or_get_ui_adaptor(), ctxt, cur_pocket, item::get_all_contained_pockets(), input_context::get_coordinates_text(), get_player_character(), input_context::handle_input(), insert_replace_activate_mod(), moves, navigate_ui_list(), pkt_map, pocket_count, ui_manager::redraw(), scroll_pos, sel_frame, suit, w_border, and w_menu.
Referenced by run().
run()
static int exosuit_interact::run (item * it) inline static
Definition at line 1976 of file iuse.cpp.
{
             exosuit_interact menu( it );
             menu.interact_loop();
             return menu.moves;
         }
References interact_loop(), and moves.
Referenced by iuse::manage_exosuit().
Member Data Documentation
ctxt
input_context exosuit_interact::ctxt private
Definition at line 2013 of file iuse.cpp.
Referenced by exosuit_interact(), and interact_loop().
cur_pocket
int exosuit_interact::cur_pocket = 0 private
Definition at line 2020 of file iuse.cpp.
Referenced by draw_iteminfo(), draw_menu(), and interact_loop().
height
int exosuit_interact::height = 0 private
Definition at line 2022 of file iuse.cpp.
Referenced by create_or_get_ui_adaptor(), draw_menu(), exosuit_interact(), and init_windows().
height_default
const int exosuit_interact::height_default = 20 private
Definition at line 2023 of file iuse.cpp.
Referenced by exosuit_interact().
moves
int exosuit_interact::moves = 0 private
Definition at line 2018 of file iuse.cpp.
Referenced by exosuit_interact(), interact_loop(), and run().
pkt_map
std::map<int, inclusive_rectangle<point> > exosuit_interact::pkt_map private
Definition at line 2017 of file iuse.cpp.
Referenced by draw_menu(), and interact_loop().
pocket_count
int exosuit_interact::pocket_count = 0 private
Definition at line 2019 of file iuse.cpp.
Referenced by exosuit_interact(), and interact_loop().
scroll_pos
int exosuit_interact::scroll_pos = 0 private
Definition at line 2021 of file iuse.cpp.
Referenced by draw_iteminfo(), and interact_loop().
sel_frame
int exosuit_interact::sel_frame = 0 private
Definition at line 2026 of file iuse.cpp.
Referenced by interact_loop().
suit
item* exosuit_interact::suit private
Definition at line 2011 of file iuse.cpp.
Referenced by create_or_get_ui_adaptor(), draw_iteminfo(), draw_menu(), and interact_loop().
ui
weak_ptr_fast<ui_adaptor> exosuit_interact::ui private
Definition at line 2012 of file iuse.cpp.
w_border
catacurses::window exosuit_interact::w_border private
Definition at line 2014 of file iuse.cpp.
Referenced by create_or_get_ui_adaptor(), init_windows(), and interact_loop().
w_info
catacurses::window exosuit_interact::w_info private
Definition at line 2015 of file iuse.cpp.
Referenced by draw_iteminfo(), and init_windows().
w_menu
catacurses::window exosuit_interact::w_menu private
Definition at line 2016 of file iuse.cpp.
Referenced by draw_menu(), init_windows(), and interact_loop().
width_info
int exosuit_interact::width_info = 30 private
Definition at line 2024 of file iuse.cpp.
Referenced by draw_menu(), exosuit_interact(), and init_windows().
width_menu
int exosuit_interact::width_menu = 30 private
Definition at line 2025 of file iuse.cpp.
Referenced by create_or_get_ui_adaptor(), draw_menu(), exosuit_interact(), and init_windows().
The documentation for this class was generated from the following file:
src/iuse.cpp