Cataclysm DDA: migration_cancel_activity_actor Class Reference
migration_cancel_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
migration_cancel_activity_actor ()=default
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Detailed Description
Definition at line 721 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
migration_cancel_activity_actor()
migration_cancel_activity_actor::migration_cancel_activity_actor () default
Referenced by deserialize().
Member Function Documentation
clone()
std::unique_ptr<activity_actor> migration_cancel_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 734 of file activity_actor_definitions.h.
{
             return std::make_unique<migration_cancel_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > migration_cancel_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 3106 of file activity_actor.cpp.
 {
     return migration_cancel_activity_actor().clone();
 }
References migration_cancel_activity_actor().
do_turn()
void migration_cancel_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 3083 of file activity_actor.cpp.
 {
     // Stop the activity
     act.set_to_null();
     // Ensure that neither avatars nor npcs end up in an invalid state
     if( who.is_npc() ) {
         npc &npc_who = dynamic_cast<npc &>( who );
         npc_who.revert_after_activity();
     } else {
         avatar &avatar_who = dynamic_cast<avatar &>( who );
         avatar_who.clear_destination();
         avatar_who.backlog.clear();
     }
 }
References act, Character::backlog, Character::clear_destination(), Character::is_npc(), and npc::revert_after_activity().
finish()
void migration_cancel_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 732 of file activity_actor_definitions.h.
 {}
get_progress_message()
std::string migration_cancel_activity_actor::get_progress_message (const player_activity & act) const inline override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 738 of file activity_actor_definitions.h.
{
             return std::string();
         }
get_type()
activity_id migration_cancel_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 726 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_MIGRATION_CANCEL" );
         }
References activity_id.
serialize()
void migration_cancel_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 3099 of file activity_actor.cpp.
 {
     // This will probably never be called, but write null to avoid invalid json in
     // the case that it is
     jsout.write_null();
 }
References JsonOut::write_null().
start()
void migration_cancel_activity_actor::start (player_activity & act, Character & who) inline override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 730 of file activity_actor_definitions.h.
 {}
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp