Cataclysm DDA: jmapgen_monster_group Class Reference
jmapgen_monster_group Class Reference
Place spawn points for a monster group (actual monster spawning is done later).
Public Member Functions
jmapgen_monster_group (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
mapgen_value< mongroup_id > id
float density
jmapgen_int chance
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place spawn points for a monster group (actual monster spawning is done later).
"monster": id of the monster group. "chance": see density: see map::place_spawns
Definition at line 2366 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_monster_group()
jmapgen_monster_group::jmapgen_monster_group (const JsonObject & jsi, const std::string_view) inline
Definition at line 2372 of file mapgen.cpp.
                                                                               :
             id( jsi.get_member( "monster" ) )
             , density( jsi.get_float( "density", -1.0f ) )
             , chance( jsi, "chance", 1, 1 ) {
         }
Member Function Documentation
apply()
void jmapgen_monster_group::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2377 of file mapgen.cpp.
{
             mongroup_id chosen_id = id.get( dat );
             if( chosen_id.is_null() ) {
                 return;
             }
             dat.m.place_spawns( chosen_id, chance.get(), point_bub_ms( x.val, y.val ),
                                 point_bub_ms( x.valmax, y.valmax ), dat.zlevel() + z.get(),
                                 density == -1.0f ? dat.monster_density() : density );
         }
References chance, density, jmapgen_int::get(), string_id< T >::is_null(), mapgendata::m, mapgendata::monster_density(), map::place_spawns(), jmapgen_int::val, jmapgen_int::valmax, and mapgendata::zlevel().
check()
void jmapgen_monster_group::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 2388 of file mapgen.cpp.
{
             id.check( oter_name, parameters );
         }
Member Data Documentation
chance
jmapgen_int jmapgen_monster_group::chance
Definition at line 2371 of file mapgen.cpp.
Referenced by apply().
density
float jmapgen_monster_group::density
Definition at line 2370 of file mapgen.cpp.
Referenced by apply().
id
mapgen_value<mongroup_id> jmapgen_monster_group::id
Definition at line 2369 of file mapgen.cpp.
The documentation for this class was generated from the following file:
src/mapgen.cpp