Cataclysm DDA: activity_data_common Class Reference
activity_data_common Class Reference
#include <mapdata.h>
Public Member Functions
activity_data_common ()=default
bool valid () const
const time_duration & duration () const
const translation & message () const
const translation & sound () const
const pry_data & prying_data () const
const std::vector< activity_byproduct > & byproducts () const
void load (const JsonObject &jo)
Public Attributes
bool was_loaded = false
Protected Attributes
bool valid_ = false
time_duration duration_
translation message_
translation sound_
struct pry_data prying_data_
std::vector< activity_byproduct > byproducts_
Detailed Description
Definition at line 379 of file mapdata.h.
Constructor & Destructor Documentation
activity_data_common()
activity_data_common::activity_data_common () default
Member Function Documentation
byproducts()
const std::vector<activity_byproduct>& activity_data_common::byproducts () const inline
Definition at line 404 of file mapdata.h.
{
             return byproducts_;
         }
References byproducts_.
Referenced by hacksaw_activity_actor::finish(), boltcutting_activity_actor::finish(), oxytorch_activity_actor::finish(), prying_activity_actor::handle_prying(), and prying_activity_actor::handle_prying_nails().
duration()
const time_duration& activity_data_common::duration () const inline
Definition at line 388 of file mapdata.h.
{
             return duration_;
         }
References duration_.
Referenced by prying_activity_actor::prying_time().
load()
void activity_data_common::load (const JsonObject & jo)
Definition at line 1197 of file mapdata.cpp.
 {
     optional( jo, was_loaded, "duration", duration_, 1_seconds );
     optional( jo, was_loaded, "message", message_ );
     optional( jo, was_loaded, "sound", sound_ );
     optional( jo, was_loaded, "byproducts", byproducts_ );
     optional( jo, was_loaded, "prying_data", prying_data_ );
 }
References byproducts_, duration_, message_, optional(), prying_data_, sound_, and was_loaded.
Referenced by activity_data_ter::load(), and activity_data_furn::load().
message()
const translation& activity_data_common::message () const inline
Definition at line 392 of file mapdata.h.
{
             return message_;
         }
References message_.
Referenced by hacksaw_activity_actor::finish(), boltcutting_activity_actor::finish(), oxytorch_activity_actor::finish(), prying_activity_actor::handle_prying(), and prying_activity_actor::handle_prying_nails().
prying_data()
const pry_data& activity_data_common::prying_data () const inline
Definition at line 400 of file mapdata.h.
{
             return prying_data_;
         }
References prying_data_.
Referenced by prying_activity_actor::handle_prying(), and prying_activity_actor::prying_time().
sound()
const translation& activity_data_common::sound () const inline
Definition at line 396 of file mapdata.h.
{
             return sound_;
         }
References sound_.
Referenced by boltcutting_activity_actor::finish().
valid()
bool activity_data_common::valid () const inline
Definition at line 384 of file mapdata.h.
{
             return valid_;
         }
References valid_.
Member Data Documentation
byproducts_
std::vector<activity_byproduct> activity_data_common::byproducts_ protected
Definition at line 417 of file mapdata.h.
Referenced by byproducts(), and load().
duration_
time_duration activity_data_common::duration_ protected
Definition at line 413 of file mapdata.h.
Referenced by duration(), and load().
message_
translation activity_data_common::message_ protected
Definition at line 414 of file mapdata.h.
Referenced by load(), and message().
prying_data_
struct pry_data activity_data_common::prying_data_ protected
Definition at line 415 of file mapdata.h.
Referenced by load(), and prying_data().
sound_
translation activity_data_common::sound_ protected
Definition at line 415 of file mapdata.h.
Referenced by load(), and sound().
valid_
bool activity_data_common::valid_ = false protected
Definition at line 412 of file mapdata.h.
Referenced by activity_data_ter::load(), activity_data_furn::load(), and valid().
was_loaded
bool activity_data_common::was_loaded = false
Definition at line 408 of file mapdata.h.
Referenced by load(), activity_data_ter::load(), and activity_data_furn::load().
The documentation for this class was generated from the following files:
src/mapdata.h
src/mapdata.cpp