Cataclysm DDA: place_monster_iuse Class Reference
place_monster_iuse Class Reference
This iuse contains the logic to transform a robot item into an actual monster on the map.
#include <iuse_actor.h>
Public Member Functions
place_monster_iuse ()
~place_monster_iuse () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
mtype_id mtypeid
The monster type id of the monster to create.
bool place_randomly = false
If true, place the monster at a random square around the player, otherwise allow the player to select the target square.
int moves = 100
How many move points this action takes.
int difficulty = 0
Difficulty of programming the monster (to be friendly).
translation friendly_msg
Shown when programming the monster succeeded and it's friendly.
translation hostile_msg
Shown when programming the monster failed and it's hostile.
std::set< skill_id > skills
Skills used to make the monster not hostile when activated.
bool is_pet = false
The monster will be spawned in as a pet.
int need_charges = 0
minimum charges (if any) required for activating monster
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
This iuse contains the logic to transform a robot item into an actual monster on the map.
Definition at line 310 of file iuse_actor.h.
Constructor & Destructor Documentation
place_monster_iuse()
place_monster_iuse::place_monster_iuse () inline
Definition at line 333 of file iuse_actor.h.
 : iuse_actor( "place_monster" ) { }
~place_monster_iuse()
place_monster_iuse::~place_monster_iuse () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > place_monster_iuse::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 877 of file iuse_actor.cpp.
 {
     return std::make_unique<place_monster_iuse>( *this );
 }
load()
void place_monster_iuse::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 882 of file iuse_actor.cpp.
 {
     mtypeid = mtype_id( obj.get_string( "monster_id" ) );
     obj.read( "friendly_msg", friendly_msg );
     obj.read( "hostile_msg", hostile_msg );
     obj.read( "difficulty", difficulty );
     obj.read( "moves", moves );
     obj.read( "place_randomly", place_randomly );
     obj.read( "is_pet", is_pet );
     obj.read( "need_charges", need_charges );
     need_charges = std::max( need_charges, 0 );
     if( obj.has_array( "skills" ) ) {
         JsonArray skills_ja = obj.get_array( "skills" );
         for( JsonValue s : skills_ja ) {
             skills.emplace( s.get_string() );
         }
     }
 }
References difficulty, friendly_msg, JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), hostile_msg, is_pet, max(), moves, mtype_id, mtypeid, need_charges, place_randomly, JsonObject::read(), and skills.
use()
std::optional< int > place_monster_iuse::use (Character * p, item & it, const tripoint &) const override virtual
Intelligence increases chance of a placed turret being friendly
Implements iuse_actor.
Definition at line 902 of file iuse_actor.cpp.
 {
     if( it.ammo_remaining() < need_charges ) {
         p->add_msg_if_player( m_info, _( "This requires %d charges to activate." ), need_charges );
         return std::nullopt;
     }
     shared_ptr_fast<monster> newmon_ptr = make_shared_fast<monster>( mtypeid );
     monster &newmon = *newmon_ptr;
     newmon.init_from_item( it );
     if( place_randomly ) {
         // place_critter_around returns the same pointer as its parameter (or null)
         if( !g->place_critter_around( newmon_ptr, p->pos(), 1 ) ) {
             p->add_msg_if_player( m_info, _( "There is no adjacent square to release the %s in!" ),
                                   newmon.name() );
             return std::nullopt;
         }
     } else {
         const std::string query = string_format( _( "Place the %s where?" ), newmon.name() );
         const std::optional<tripoint> pnt_ = choose_adjacent( query );
         if( !pnt_ ) {
             return std::nullopt;
         }
         // place_critter_at returns the same pointer as its parameter (or null)
         if( !g->place_critter_at( newmon_ptr, *pnt_ ) ) {
             p->add_msg_if_player( m_info, _( "You cannot place a %s there." ), newmon.name() );
             return std::nullopt;
         }
     }
     // Uses the moves specified by iuse_actor's definition
     p->mod_moves( -moves );
     newmon.ammo = newmon.type->starting_ammo;
     if( !newmon.has_flag( mon_flag_INTERIOR_AMMO ) ) {
         for( std::pair<const itype_id, int> &amdef : newmon.ammo ) {
             item ammo_item( amdef.first, calendar::turn_zero );
             const int available = p->charges_of( amdef.first );
             if( available == 0 ) {
                 amdef.second = 0;
                 p->add_msg_if_player( m_info,
                                       _( "If you had standard factory-built %1$s bullets, you could load the %2$s." ),
                                       ammo_item.type_name( 2 ), newmon.name() );
                 continue;
             }
             // Don't load more than the default from the monster definition.
             ammo_item.charges = std::min( available, amdef.second );
             p->use_charges( amdef.first, ammo_item.charges );
             //~ First %s is the ammo item (with plural form and count included), second is the monster name
             p->add_msg_if_player( n_gettext( "You load %1$d x %2$s round into the %3$s.",
                                              "You load %1$d x %2$s rounds into the %3$s.", ammo_item.charges ),
                                   ammo_item.charges, ammo_item.type_name( ammo_item.charges ),
                                   newmon.name() );
             amdef.second = ammo_item.charges;
         }
     }
     float skill_offset = 0;
     for( const skill_id &sk : skills ) {
         skill_offset += p->get_skill_level( sk ) / 2.0f;
     }
     /** @EFFECT_INT increases chance of a placed turret being friendly */
     if( rng( 0, p->int_cur / 2 ) + skill_offset < rng( 0, difficulty ) ) {
         if( hostile_msg.empty() ) {
             p->add_msg_if_player( m_bad, _( "You deploy the %s wrong.  It is hostile!" ), newmon.name() );
         } else {
             p->add_msg_if_player( m_bad, "%s", hostile_msg );
         }
     } else {
         if( friendly_msg.empty() ) {
             p->add_msg_if_player( m_warning, _( "You deploy the %s." ), newmon.name() );
         } else {
             p->add_msg_if_player( m_warning, "%s", friendly_msg );
         }
         newmon.friendly = -1;
         if( is_pet ) {
             newmon.add_effect( effect_pet, 1_turns, true );
         }
     }
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), monster::ammo, item::ammo_remaining(), available, item::charges, Character::charges_of(), choose_adjacent(), difficulty, effect_pet, translation::empty(), monster::friendly, friendly_msg, g, Character::get_skill_level(), monster::has_flag(), hostile_msg, monster::init_from_item(), Character::int_cur, is_pet, m_bad, m_info, m_warning, min(), Creature::mod_moves(), mon_flag_INTERIOR_AMMO, moves, mtypeid, n_gettext, monster::name(), need_charges, place_randomly, Creature::pos(), rng(), skills, mtype::starting_ammo, string_format(), calendar::turn_zero, monster::type, item::type_name(), and Character::use_charges().
Member Data Documentation
difficulty
int place_monster_iuse::difficulty = 0
Difficulty of programming the monster (to be friendly).
Definition at line 321 of file iuse_actor.h.
Referenced by load(), and use().
friendly_msg
translation place_monster_iuse::friendly_msg
Shown when programming the monster succeeded and it's friendly.
Can be empty.
Definition at line 323 of file iuse_actor.h.
Referenced by load(), and use().
hostile_msg
translation place_monster_iuse::hostile_msg
Shown when programming the monster failed and it's hostile.
Can be empty.
Definition at line 325 of file iuse_actor.h.
Referenced by load(), and use().
is_pet
bool place_monster_iuse::is_pet = false
The monster will be spawned in as a pet.
False by default. Can be empty.
Definition at line 329 of file iuse_actor.h.
Referenced by load(), and use().
moves
int place_monster_iuse::moves = 100
How many move points this action takes.
Definition at line 319 of file iuse_actor.h.
Referenced by load(), and use().
mtypeid
mtype_id place_monster_iuse::mtypeid
The monster type id of the monster to create.
Definition at line 314 of file iuse_actor.h.
Referenced by grenade_helper(), load(), and use().
need_charges
int place_monster_iuse::need_charges = 0
minimum charges (if any) required for activating monster
Definition at line 331 of file iuse_actor.h.
Referenced by load(), and use().
place_randomly
bool place_monster_iuse::place_randomly = false
If true, place the monster at a random square around the player, otherwise allow the player to select the target square.
Definition at line 317 of file iuse_actor.h.
Referenced by load(), and use().
skills
std::set<skill_id> place_monster_iuse::skills
Skills used to make the monster not hostile when activated.
Definition at line 327 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp