Cataclysm DDA: optional_vpart_position Class Reference
optional_vpart_position Class Reference
Simple wrapper to forward functions that may return a std::optional to vpart_position.
#include <vpart_position.h>
Public Member Functions
optional_vpart_position (std::optional< vpart_position > p)
std::optional< std::string > get_label () const
std::optional< vpart_reference > cargo () const
std::optional< vpart_reference > part_with_feature (const std::string &f, bool unbroken) const
std::optional< vpart_reference > part_with_feature (vpart_bitflags f, bool unbroken) const
std::optional< vpart_reference > avail_part_with_feature (const std::string &f) const
std::optional< vpart_reference > avail_part_with_feature (vpart_bitflags f) const
std::optional< vpart_reference > obstacle_at_part () const
std::optional< vpart_reference > part_displayed () const
std::optional< vpart_reference > part_with_tool (const itype_id &tool_type) const
std::string extended_description () const
Detailed Description
Simple wrapper to forward functions that may return a std::optional to vpart_position.
They generally return an empty optional, or forward to the same function in vpart_position.
Definition at line 124 of file vpart_position.h.
Constructor & Destructor Documentation
optional_vpart_position()
optional_vpart_position::optional_vpart_position (std::optional< vpart_position > p) inline explicit
Definition at line 127 of file vpart_position.h.
                                                                           :
             std::optional<vpart_position>( p ) { }
Member Function Documentation
avail_part_with_feature() [1/2]
std::optional< vpart_reference > optional_vpart_position::avail_part_with_feature (const std::string & f) const
Definition at line 2715 of file vehicle.cpp.
 {
     return has_value() ? value().avail_part_with_feature( f ) : std::nullopt;
 }
Referenced by melee_actor::do_grab(), and Character::uncanny_dodge().
avail_part_with_feature() [2/2]
std::optional< vpart_reference > optional_vpart_position::avail_part_with_feature (vpart_bitflags f) const
Definition at line 2721 of file vehicle.cpp.
 {
     return has_value() ? value().avail_part_with_feature( f ) : std::nullopt;
 }
cargo()
std::optional< vpart_reference > optional_vpart_position::cargo () const
Definition at line 2710 of file vehicle.cpp.
 {
     return has_value() ? value().cargo() : std::nullopt;
 }
Referenced by activity_on_turn_move_loot(), zone_manager::add(), inventory_selector::add_vehicle_items(), are_requirements_nearby(), Character::base_comfort_value(), can_pickup_at(), map::can_put_items(), craft_command::continue_prompt_liquids(), cycle_action(), distribute_items_to_npc_zones(), unload_loot_activity_actor::do_turn(), Character::drop(), fetch_activity(), npc::find_item(), get_auto_consume_moves(), Character::get_eligible_containers_for_crafting(), advanced_inv_area::init(), mission::is_complete(), put_into_vehicle_or_drop(), zone_manager::revert_vzones(), set_item_map_or_vehicle(), tidy_activity(), and game::wield().
extended_description()
std::string optional_vpart_position::extended_description () const
Definition at line 2743 of file vehicle.cpp.
 {
     if( !has_value() ) {
         return std::string();
     }
     vehicle &v = value().vehicle();
     std::string desc = v.name;
     for( int idx : v.parts_at_relative( value().mount(), true ) ) {
         desc += "\n" + v.part( idx ).name();
     }
     return desc;
 }
References vehicle_part::name(), vehicle::name, vehicle::part(), vehicle::parts_at_relative(), and vehicle::vehicle().
Referenced by game::extended_description().
get_label()
std::optional<std::string> optional_vpart_position::get_label () const inline
Definition at line 130 of file vpart_position.h.
{
             return has_value() ? value().get_label() : std::nullopt;
         }
Referenced by game::place_player().
obstacle_at_part()
std::optional< vpart_reference > optional_vpart_position::obstacle_at_part () const
Definition at line 2727 of file vehicle.cpp.
 {
     return has_value() ? value().obstacle_at_part() : std::nullopt;
 }
Referenced by monster::bash_at(), and game::fling_creature().
part_displayed()
std::optional< vpart_reference > optional_vpart_position::part_displayed () const
Definition at line 2732 of file vehicle.cpp.
 {
     return has_value() ? value().part_displayed() : std::nullopt;
 }
Referenced by enumerate_objects_around_point(), and game::walk_move().
part_with_feature() [1/2]
std::optional< vpart_reference > optional_vpart_position::part_with_feature (const std::string & f, bool unbroken) const
Definition at line 2698 of file vehicle.cpp.
 {
     return has_value() ? value().part_with_feature( f, unbroken ) : std::nullopt;
 }
Referenced by map::board_vehicle(), veh_interact::complete_vehicle(), game::control_vehicle(), melee_actor::do_grab(), npc::find_item(), Character::floor_bedding_warmth(), game::get_dangerous_tile(), npc::get_path_avoid(), gunmode_checks_weapon(), map::has_nearby_table(), map::has_vehicle_floor(), monster::is_aquatic_danger(), game::load(), monster::monster_move_in_vehicle(), monster::move(), avatar_action::move(), Character::move_in_vehicle(), monster::move_to(), npc::move_to(), Character::on_hit(), game::phasing_move(), npc::pick_up_item(), place_craft_or_disassembly(), game::place_player(), veh_app_interact::populate_app_actions(), Character::process_effects(), monster::process_effects(), veh_app_interact::remove(), Character::rest_quality(), route_best_workbench(), game::swap_critters(), avatar_action::swim(), avatar::try_to_sleep(), map::unboard_vehicle(), vehicle_unfolding_activity_actor::unfold_vehicle(), Character::update_bodytemp(), and Character::workbench_crafting_speed_multiplier().
part_with_feature() [2/2]
std::optional< vpart_reference > optional_vpart_position::part_with_feature (vpart_bitflags f, bool unbroken) const
Definition at line 2704 of file vehicle.cpp.
 {
     return has_value() ? value().part_with_feature( f, unbroken ) : std::nullopt;
 }
part_with_tool()
std::optional< vpart_reference > optional_vpart_position::part_with_tool (const itype_id & tool_type) const
Definition at line 2737 of file vehicle.cpp.
 {
     return has_value() ? value().part_with_tool( tool_type ) : std::nullopt;
 }
Referenced by are_requirements_nearby(), and weldrig_hack::init().
The documentation for this class was generated from the following files:
src/vpart_position.h
src/vehicle.cpp