Cataclysm DDA: teleporter_callback Class Reference
teleporter_callback Class Reference
Public Member Functions
teleporter_callback (std::map< int, tripoint_abs_omt > &ip)
void refresh (uilist *menu) override
Public Member Functions inherited from uilist_callback
virtual void select (uilist *)
After a new item is selected, call this once.
virtual bool key (const input_context &, const input_event &, int, uilist *)
virtual ~uilist_callback ()=default
Private Attributes
std::map< int, tripoint_abs_omt > index_pairs
Detailed Description
Definition at line 159 of file magic_teleporter_list.cpp.
Constructor & Destructor Documentation
teleporter_callback()
teleporter_callback::teleporter_callback (std::map< int, tripoint_abs_omt > & ip) inline explicit
Definition at line 165 of file magic_teleporter_list.cpp.
 : index_pairs( ip ) {}
Member Function Documentation
refresh()
void teleporter_callback::refresh (uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 166 of file magic_teleporter_list.cpp.
{
             const int entnum = menu->selected;
             const int start_x = menu->w_width - menu->pad_right;
             mvwputch( menu->window, point( start_x, 0 ), c_magenta, LINE_OXXX );
             mvwputch( menu->window, point( start_x, menu->w_height - 1 ), c_magenta, LINE_XXOX );
             for( int i = 1; i < menu->w_height - 1; i++ ) {
                 mvwputch( menu->window, point( start_x, i ), c_magenta, LINE_XOXO );
             }
             if( entnum >= 0 && static_cast<size_t>( entnum ) < index_pairs.size() ) {
                 avatar &player_character = get_avatar();
                 overmap_ui::draw_overmap_chunk( menu->window, player_character, index_pairs[entnum],
                                                 point( start_x + 1, 1 ),
                                                 29, 21 );
                 int dist = rl_dist( player_character.global_omt_location(), index_pairs[entnum] );
                 mvwprintz( menu->window, point( start_x + 2, 1 ), c_white,
                            string_format( _( "Distance: %d %s" ), dist,
                                           index_pairs[entnum].to_string() ) );
             }
             wnoutrefresh( menu->window );
         }
References _, c_magenta, c_white, overmap_ui::draw_overmap_chunk(), get_avatar(), Creature::global_omt_location(), index_pairs, LINE_OXXX, LINE_XOXO, LINE_XXOX, mvwprintz(), mvwputch(), uilist::pad_right, rl_dist(), uilist::selected, string_format(), to_string(), uilist::w_height, uilist::w_width, uilist::window, and catacurses::wnoutrefresh().
Member Data Documentation
index_pairs
std::map<int, tripoint_abs_omt> teleporter_callback::index_pairs private
Definition at line 163 of file magic_teleporter_list.cpp.
Referenced by refresh().
The documentation for this class was generated from the following file:
src/magic_teleporter_list.cpp