Cataclysm DDA: fake_map Class Reference
fake_map Class Reference
#include <map.h>
Public Member Functions
fake_map (const ter_id &ter_type=ter_str_id("t_dirt").id())
~fake_map () override
Public Member Functions inherited from tinymap
tinymap ()
bool inbounds (const tripoint &p) const
bool inbounds (const tripoint_omt_ms &p) const
map * cast_to_map ()
void load (const tripoint_abs_omt &w, bool update_vehicles, bool pump_events=false)
void place_spawns (const mongroup_id &group, int chance, const point_omt_ms &p1, const point_omt_ms &p2, const int z_level, float density, bool individual=false, bool friendly=false, const std::optional< std::string > &name=std::nullopt, int mission_id=-1)
void add_spawn (const mtype_id &type, int count, const tripoint_omt_ms &p, bool friendly=false, int faction_id=-1, int mission_id=-1, const std::optional< std::string > &name=std::nullopt)
ter_id ter (const tripoint &p) const
ter_id ter (const tripoint_omt_ms &p) const
bool ter_set (const tripoint &p, const ter_id &new_terrain, bool avoid_creatures=false)
bool has_flag_ter (ter_furn_flag flag, const tripoint &p) const
bool has_flag_ter (ter_furn_flag flag, const tripoint_omt_ms &p) const
void draw_line_ter (const ter_id &type, const point &p1, const point &p2, bool avoid_creature=false)
bool is_last_ter_wall (bool no_furn, const point &p, const point &max, direction dir) const
furn_id furn (const point &p) const
furn_id furn (const tripoint &p) const
furn_id furn (const tripoint_omt_ms &p) const
bool has_furn (const tripoint &p) const
void set (const tripoint &p, const ter_id &new_terrain, const furn_id &new_furniture)
bool furn_set (const point &p, const furn_id &new_furniture, bool avoid_creatures=false)
bool furn_set (const tripoint &p, const furn_id &new_furniture, bool furn_reset=false, bool avoid_creatures=false)
void draw_line_furn (const furn_id &type, const point &p1, const point &p2, bool avoid_creatures=false)
void draw_square_furn (const furn_id &type, const point &p1, const point &p2, bool avoid_creatures=false)
bool has_flag_furn (ter_furn_flag flag, const tripoint &p) const
computer * add_computer (const tripoint &p, const std::string &name, int security)
std::string name (const tripoint &p)
bool impassable (const tripoint &p) const
tripoint_range< tripoint > points_on_zlevel () const
tripoint_range< tripoint > points_on_zlevel (int z) const
tripoint_range< tripoint > points_in_rectangle (const tripoint &from, const tripoint &to) const
tripoint_range< tripoint_omt_ms > points_in_rectangle (const tripoint_omt_ms &from, const tripoint_omt_ms &to) const
tripoint_range< tripoint > points_in_radius (const tripoint &center, size_t radius, size_t radiusz=0) const
tripoint_range< tripoint_omt_ms > points_in_radius (const tripoint_omt_ms &center, size_t radius, size_t radiusz=0) const
map_stack i_at (const tripoint &p)
void spawn_item (const tripoint &p, const itype_id &type_id, unsigned quantity=1, int charges=0, const time_point &birthday=calendar::start_of_cataclysm, int damlevel=0, const std::set< flag_id > &flags={}, const std::string &variant="", const std::string &faction="")
void spawn_item (const tripoint &p, const std::string &type_id, unsigned quantity=1, int charges=0, const time_point &birthday=calendar::start_of_cataclysm, int damlevel=0, const std::set< flag_id > &flags={}, const std::string &variant="", const std::string &faction="")
std::vector< item * > spawn_items (const tripoint &p, const std::vector< item > &new_items)
item & add_item (const tripoint &p, item new_item)
item & add_item_or_charges (const point &p, const item &obj, bool overflow=true)
std::vector< item * > put_items_from_loc (const item_group_id &group_id, const tripoint &p, const time_point &turn=calendar::start_of_cataclysm)
item & add_item_or_charges (const tripoint &pos, item obj, bool overflow=true)
std::vector< item * > place_items (const item_group_id &group_id, int chance, const tripoint &p1, const tripoint &p2, bool ongrass, const time_point &turn, int magazine=0, int ammo=0, const std::string &faction="")
void add_corpse (const tripoint &p)
void i_rem (const tripoint &p, item *it)
void i_clear (const tripoint &p)
bool add_field (const tripoint &p, const field_type_id &type_id, int intensity=INT_MAX, const time_duration &age=0_turns, bool hit_player=true)
bool add_field (const tripoint_omt_ms &p, const field_type_id &type_id, int intensity=INT_MAX, const time_duration &age=0_turns, bool hit_player=true)
void delete_field (const tripoint &p, const field_type_id &field_to_remove)
void delete_field (const tripoint_omt_ms &p, const field_type_id &field_to_remove)
bool has_flag (ter_furn_flag flag, const tripoint &p) const
bool has_flag (ter_furn_flag flag, const point &p) const
void destroy (const tripoint &p, bool silent=false)
const trap & tr_at (const tripoint &p) const
const trap & tr_at (const tripoint_omt_ms &p) const
void trap_set (const tripoint &p, const trap_id &type)
void trap_set (const tripoint_omt_ms &p, const trap_id &type)
void set_signage (const tripoint &p, const std::string &message)
void delete_signage (const tripoint &p)
VehicleList get_vehicles ()
optional_vpart_position veh_at (const tripoint &p) const
optional_vpart_position veh_at (const tripoint_omt_ms &p) const
vehicle * add_vehicle (const vproto_id &type, const tripoint &p, const units::angle &dir, int init_veh_fuel=-1, int init_veh_status=-1, bool merge_wrecks=true)
void add_splatter_trail (const field_type_id &type, const tripoint &from, const tripoint &to)
void collapse_at (const tripoint &p, bool silent, bool was_supporting=false, bool destroy_pos=true)
tripoint getlocal (const tripoint &p) const
tripoint_abs_sm get_abs_sub () const
tripoint getabs (const tripoint &p) const
tripoint getlocal (const tripoint_abs_ms &p) const
bool is_outside (const tripoint &p) const
void save ()
Add currently loaded submaps (in grid) to the mapbuffer.
bool is_main_cleanup_queued () const
void main_cleanup_override (bool over)
void generate (const tripoint_abs_omt &p, const time_point &when)
void translate (const ter_id &from, const ter_id &to)
void rotate (int turns, bool setpos_safe=false)
Rotates this map, and all of its contents, by the specified multiple of 90 degrees.
void mirror (bool mirror_horizontal, bool mirror_vertical)
Mirrors this map, and all of its contents along with all its contents in the directions specified.
void build_outside_cache (int zlev)
Static Public Attributes
static constexpr int fake_map_z = -OVERMAP_DEPTH
Private Attributes
std::vector< std::unique_ptr< submap > > temp_submaps_
Additional Inherited Members
Protected Member Functions inherited from tinymap
tinymap (int mapsize, bool zlev)
void cut_down_tree (tripoint_omt_ms p, point dir)
int get_my_MAPSIZE ()
void set_abs_sub (const tripoint_abs_sm &p)
Sets abs_sub, see there.
void setsubmap (size_t grididx, submap *smap)
Set the submap pointer in grid at the give index.
size_t get_nonant (const tripoint &gridp) const
Get the index of a submap pointer in the grid given by grid coordinates.
size_t get_nonant (const point &gridp) const
Detailed Description
Definition at line 2693 of file map.h.
Constructor & Destructor Documentation
fake_map()
fake_map::fake_map (const ter_id & ter_type = ter_str_id("t_dirt").id()) explicit
Definition at line 9131 of file map.cpp.
 {
     const tripoint_abs_sm tripoint_below_zero( 0, 0, fake_map_z );
     set_abs_sub( tripoint_below_zero );
     for( int gridx = 0; gridx < get_my_MAPSIZE(); gridx++ ) {
         for( int gridy = 0; gridy < get_my_MAPSIZE(); gridy++ ) {
             std::unique_ptr<submap> sm = std::make_unique<submap>();
             sm->set_all_ter( ter_type );
             sm->set_all_furn( furn_str_id::NULL_ID() );
             sm->set_all_traps( tr_null );
             setsubmap( get_nonant( { gridx, gridy, fake_map_z } ), sm.get() );
             temp_submaps_.emplace_back( std::move( sm ) );
         }
     }
 }
References fake_map_z, tinymap::get_my_MAPSIZE(), tinymap::get_nonant(), string_id< furn_t >::NULL_ID(), tinymap::set_abs_sub(), tinymap::setsubmap(), coords::sm, temp_submaps_, and tr_null.
~fake_map()
fake_map::~fake_map () override default
Member Data Documentation
fake_map_z
constexpr int fake_map::fake_map_z = -OVERMAP_DEPTH static constexpr
Definition at line 2700 of file map.h.
Referenced by apply_construction_marker(), fake_map(), and get_changed_ids_from_update().
temp_submaps_
std::vector<std::unique_ptr<submap> > fake_map::temp_submaps_ private
Definition at line 2696 of file map.h.
Referenced by fake_map().
The documentation for this class was generated from the following files:
src/map.h
src/map.cpp