Cataclysm DDA: vehicle_part_with_fakes_range Class Reference
vehicle_part_with_fakes_range Class Reference
#include <vpart_range.h>
Public Member Functions
vehicle_part_with_fakes_range (::vehicle &v, bool with_inactive)
bool matches (size_t part) const
Public Member Functions inherited from generic_vehicle_part_range< vehicle_part_with_fakes_range >
generic_vehicle_part_range (::vehicle &v, bool with_fake=false)
size_t part_count () const
iterator begin () const
iterator end () const
::vehicle & vehicle () const
Private Attributes
bool with_inactive_fakes_
Additional Inherited Members
Public Types inherited from generic_vehicle_part_range< vehicle_part_with_fakes_range >
using iterator = vehicle_part_iterator< vehicle_part_with_fakes_range >
Detailed Description
Definition at line 158 of file vpart_range.h.
Constructor & Destructor Documentation
vehicle_part_with_fakes_range()
vehicle_part_with_fakes_range::vehicle_part_with_fakes_range (::vehicle & v, bool with_inactive) inline
Definition at line 164 of file vpart_range.h.
                                                                         :
             generic_vehicle_part_range( v, true ),
             with_inactive_fakes_( with_inactive ) { }
Member Function Documentation
matches()
bool vehicle_part_with_fakes_range::matches (size_t part) const
Definition at line 8352 of file vehicle.cpp.
 {
     return this->with_inactive_fakes_ ||
            ( static_cast<int>( part ) < this->vehicle().part_count() &&
              this->vehicle().part( part ).is_real_or_active_fake() );
 }
References vehicle_part::is_real_or_active_fake(), vehicle::part(), vehicle::part_count(), generic_vehicle_part_range< vehicle_part_with_fakes_range >::vehicle(), and with_inactive_fakes_.
Member Data Documentation
with_inactive_fakes_
bool vehicle_part_with_fakes_range::with_inactive_fakes_ private
Definition at line 162 of file vpart_range.h.
Referenced by matches().
The documentation for this class was generated from the following files:
src/vpart_range.h
src/vehicle.cpp