Cataclysm DDA: proficiency_set Class Reference
proficiency_set Class Reference
#include <proficiency.h>
Public Member Functions
std::vector< display_proficiency > display () const
bool practice (const proficiency_id &practicing, const time_duration &amount, float remainder, const std::optional< time_duration > &max)
void learn (const proficiency_id &learned)
void remove (const proficiency_id &lost)
void direct_learn (const proficiency_id &learned)
void direct_remove (const proficiency_id &lost)
bool has_learned (const proficiency_id &query) const
bool has_practiced (const proficiency_id &query) const
bool has_prereqs (const proficiency_id &query) const
float pct_practiced (const proficiency_id &query) const
time_duration pct_practiced_time (const proficiency_id &query) const
void set_time_practiced (const proficiency_id &practicing, const time_duration &amount)
time_duration training_time_needed (const proficiency_id &query) const
std::vector< proficiency_id > known_profs () const
std::vector< proficiency_id > learning_profs () const
float get_proficiency_bonus (const std::string &category, proficiency_bonus_type prof_bonus) const
void serialize (JsonOut &jsout) const
void deserialize (const JsonObject &jsobj)
Private Member Functions
learning_proficiency & fetch_learning (const proficiency_id &target)
Private Attributes
cata::flat_set< proficiency_id > known
std::vector< learning_proficiency > learning
Detailed Description
Definition at line 120 of file proficiency.h.
Member Function Documentation
deserialize()
void proficiency_set::deserialize (const JsonObject & jsobj)
Definition at line 552 of file proficiency.cpp.
 {
     jsobj.read( "known", known );
     jsobj.read( "learning", learning );
 }
References known, learning, and JsonObject::read().
direct_learn()
void proficiency_set::direct_learn (const proficiency_id & learned)
Definition at line 427 of file proficiency.cpp.
 {
     // Player might be learning proficiency
     for( std::vector<learning_proficiency>::iterator it = learning.begin(); it != learning.end(); ) {
         if( it->id == learned ) {
             it = learning.erase( it );
         } else {
             ++it;
         }
     }
     known.insert( learned );
 }
References known, and learning.
direct_remove()
void proficiency_set::direct_remove (const proficiency_id & lost)
Definition at line 441 of file proficiency.cpp.
 {
     known.erase( lost );
 }
References known.
display()
std::vector< display_proficiency > proficiency_set::display () const
Definition at line 254 of file proficiency.cpp.
 {
     // The proficiencies are sorted by whether or not you know them
     // and then alphabetically
     std::vector<std::pair<std::string, proficiency_id>> sorted_known;
     std::vector<std::pair<std::string, proficiency_id>> sorted_learning;
     for( const proficiency_id &cur : known ) {
         sorted_known.emplace_back( cur->name(), cur );
     }
     sorted_learning.reserve( learning.size() );
     for( const learning_proficiency &cur : learning ) {
         sorted_learning.emplace_back( cur.id->name(), cur.id );
     }
     std::sort( sorted_known.begin(), sorted_known.end(), localized_compare );
     std::sort( sorted_learning.begin(), sorted_learning.end(), localized_compare );
     // Our display_proficiencies, sorted in the order above
     std::vector<display_proficiency> ret;
     for( const std::pair<std::string, proficiency_id> &cur : sorted_known ) {
         display_proficiency disp;
         disp.id = cur.second;
         disp.color = c_white;
         disp.practice = 1.0f;
         disp.spent = cur.second->time_to_learn();
         disp.known = true;
         ret.insert( ret.end(), disp );
     }
     for( const std::pair<std::string, proficiency_id> &cur : sorted_learning ) {
         display_proficiency disp;
         disp.id = cur.second;
         disp.color = c_light_gray;
         time_duration practiced;
         for( const learning_proficiency &cursor : learning ) {
             if( cursor.id == cur.second ) {
                 practiced = cursor.practiced;
                 break;
             }
         }
         disp.spent = practiced;
         disp.practice = practiced / cur.second->time_to_learn();
         disp.known = false;
         ret.insert( ret.end(), disp );
     }
     return ret;
 }
References c_light_gray, c_white, display_proficiency::color, display_proficiency::id, known, display_proficiency::known, learning, localized_compare, display_proficiency::practice, cata::hash64_detail::ret, and display_proficiency::spent.
fetch_learning()
learning_proficiency & proficiency_set::fetch_learning (const proficiency_id & target) private
Definition at line 240 of file proficiency.cpp.
 {
     for( learning_proficiency &cursor : learning ) {
         if( cursor.id == target ) {
             return cursor;
         }
     }
     // This should _never_ happen
     debugmsg( "Uh-oh!  Requested proficiency that character does not know"
               " - expect crash or undefined behavior" );
     return learning[0];
 }
References debugmsg, and learning.
Referenced by practice(), and set_time_practiced().
get_proficiency_bonus()
float proficiency_set::get_proficiency_bonus (const std::string & category, proficiency_bonus_type prof_bonus) const
Definition at line 526 of file proficiency.cpp.
 {
     float stat_bonus = 0;
     for( const proficiency_id &knows : known ) {
         const std::vector<proficiency_bonus> &prof_bonuses = knows->get_bonuses( category );
         for( const proficiency_bonus &bonus : prof_bonuses ) {
             if( bonus.type == prof_bonus ) {
                 stat_bonus += bonus.value;
             }
         }
     }
     return stat_bonus;
 }
References anonymous_namespace{item_tname.cpp}::category(), and known.
has_learned()
bool proficiency_set::has_learned (const proficiency_id & query) const
Definition at line 446 of file proficiency.cpp.
 {
     return known.count( query );
 }
References known.
Referenced by has_prereqs(), learn(), pct_practiced(), pct_practiced_time(), and practice().
has_practiced()
bool proficiency_set::has_practiced (const proficiency_id & query) const
Definition at line 451 of file proficiency.cpp.
 {
     for( const learning_proficiency &cursor : learning ) {
         if( cursor.id == query ) {
             return true;
         }
     }
     return false;
 }
References learning.
Referenced by practice(), and set_time_practiced().
has_prereqs()
bool proficiency_set::has_prereqs (const proficiency_id & query) const
Definition at line 461 of file proficiency.cpp.
 {
     for( const proficiency_id &req : query->required_proficiencies() ) {
         if( !has_learned( req ) ) {
             return false;
         }
     }
     return true;
 }
References has_learned(), and proficiency::required_proficiencies().
Referenced by practice().
known_profs()
std::vector< proficiency_id > proficiency_set::known_profs () const
Definition at line 507 of file proficiency.cpp.
 {
     std::vector<proficiency_id> ret;
     for( const proficiency_id &knows : known ) {
         ret.push_back( knows );
     }
     return ret;
 }
References known, and cata::hash64_detail::ret.
learn()
void proficiency_set::learn (const proficiency_id & learned)
Definition at line 368 of file proficiency.cpp.
 {
     for( const proficiency_id &req : learned->required_proficiencies() ) {
         if( !has_learned( req ) ) {
             return;
         }
     }
     known.insert( learned );
 }
References has_learned(), known, and proficiency::required_proficiencies().
Referenced by practice(), and set_time_practiced().
learning_profs()
std::vector< proficiency_id > proficiency_set::learning_profs () const
Definition at line 516 of file proficiency.cpp.
 {
     std::vector<proficiency_id> ret;
     ret.reserve( learning.size() );
     for( const learning_proficiency &subject : learning ) {
         ret.push_back( subject.id );
     }
     return ret;
 }
References learning, and cata::hash64_detail::ret.
pct_practiced()
float proficiency_set::pct_practiced (const proficiency_id & query) const
Definition at line 471 of file proficiency.cpp.
 {
     for( const learning_proficiency &prof : learning ) {
         if( prof.id == query ) {
             return prof.practiced / query->time_to_learn();
         }
     }
     if( has_learned( query ) ) {
         return 1.0f;
     }
     return 0.0f;
 }
References has_learned(), learning, and proficiency::time_to_learn().
pct_practiced_time()
time_duration proficiency_set::pct_practiced_time (const proficiency_id & query) const
Definition at line 484 of file proficiency.cpp.
 {
     for( const learning_proficiency &prof : learning ) {
         if( prof.id == query ) {
             return prof.practiced;
         }
     }
     if( has_learned( query ) ) {
         return query->time_to_learn();
     }
     return 0_seconds;
 }
References has_learned(), learning, and proficiency::time_to_learn().
practice()
bool proficiency_set::practice (const proficiency_id & practicing, const time_duration & amount, float remainder, const std::optional< time_duration > & max)
Definition at line 306 of file proficiency.cpp.
 {
     if( has_learned( practicing ) || !practicing->can_learn() || !has_prereqs( practicing ) ) {
         return false;
     }
     if( !has_practiced( practicing ) ) {
         learning.emplace_back( practicing, 0_seconds );
     }
     learning_proficiency &current = fetch_learning( practicing );
     if( max && current.practiced > *max ) {
         return false;
     }
     current.practiced += amount;
     current.remainder += remainder;
     if( current.remainder > 1.f ) {
         current.practiced += 1_seconds;
         current.remainder -= 1.f;
     }
     if( current.practiced >= practicing->time_to_learn() ) {
         for( std::vector<learning_proficiency>::iterator it = learning.begin(); it != learning.end(); ) {
             if( it->id == practicing ) {
                 it = learning.erase( it );
             } else {
                 ++it;
             }
         }
         learn( practicing );
         return true;
     }
     return false;
 }
References proficiency::can_learn(), fetch_learning(), has_learned(), has_practiced(), has_prereqs(), learn(), learning, max(), learning_proficiency::practiced, learning_proficiency::remainder, and proficiency::time_to_learn().
remove()
void proficiency_set::remove (const proficiency_id & lost)
Definition at line 395 of file proficiency.cpp.
 {
     // Removes from proficiencies you are learning
     for( std::vector<learning_proficiency>::iterator it = learning.begin(); it != learning.end(); ) {
         if( it->id == lost ) {
             it = learning.erase( it );
         } else {
             ++it;
         }
     }
     // No unintended side effects
     if( !known.count( lost ) ) {
         return;
     }
     // Loop over all the proficiencies requiring lost, to remove them too
     // Then the ones requiring it, etc.
     std::set<proficiency_id> to_remove;
     to_remove.insert( lost );
     size_t cached_size = 0;
     // While we have new proficiencies we need to check for anything requiring them
     while( to_remove.size() != cached_size ) {
         cached_size = to_remove.size();
         std::set<proficiency_id> additional = proficiencies_requiring( to_remove, known );
         to_remove.insert( additional.begin(), additional.end() );
     }
     for( const proficiency_id &gone : to_remove ) {
         known.erase( gone );
     }
 }
References known, learning, and proficiencies_requiring().
Referenced by set_time_practiced().
serialize()
void proficiency_set::serialize (JsonOut & jsout) const
Definition at line 542 of file proficiency.cpp.
 {
     jsout.start_object();
     jsout.member( "known", known );
     jsout.member( "learning", learning );
     jsout.end_object();
 }
References JsonOut::end_object(), known, learning, JsonOut::member(), and JsonOut::start_object().
set_time_practiced()
void proficiency_set::set_time_practiced (const proficiency_id & practicing, const time_duration & amount)
Definition at line 345 of file proficiency.cpp.
 {
     if( amount >= practicing->time_to_learn() ) {
         for( std::vector<learning_proficiency>::iterator it = learning.begin(); it != learning.end(); ) {
             if( it->id == practicing ) {
                 it = learning.erase( it );
             } else {
                 ++it;
             }
         }
         learn( practicing );
         return;
     } else if( known.count( practicing ) ) {
         remove( practicing );
     }
     if( !has_practiced( practicing ) ) {
         learning.emplace_back( practicing, 0_seconds );
     }
     learning_proficiency &current = fetch_learning( practicing );
     current.practiced = amount;
 }
References fetch_learning(), has_practiced(), known, learn(), learning, learning_proficiency::practiced, remove(), and proficiency::time_to_learn().
training_time_needed()
time_duration proficiency_set::training_time_needed (const proficiency_id & query) const
Definition at line 497 of file proficiency.cpp.
 {
     for( const learning_proficiency &prof : learning ) {
         if( prof.id == query ) {
             return query->time_to_learn() - prof.practiced;
         }
     }
     return query->time_to_learn();
 }
References learning, and proficiency::time_to_learn().
Member Data Documentation
known
cata::flat_set<proficiency_id> proficiency_set::known private
Definition at line 123 of file proficiency.h.
Referenced by deserialize(), direct_learn(), direct_remove(), display(), get_proficiency_bonus(), has_learned(), known_profs(), learn(), remove(), serialize(), and set_time_practiced().
learning
std::vector<learning_proficiency> proficiency_set::learning private
Definition at line 126 of file proficiency.h.
Referenced by deserialize(), direct_learn(), display(), fetch_learning(), has_practiced(), learning_profs(), pct_practiced(), pct_practiced_time(), practice(), remove(), serialize(), set_time_practiced(), and training_time_needed().
The documentation for this class was generated from the following files:
src/proficiency.h
src/proficiency.cpp