Cataclysm DDA: attach_molle_inventory_preset Class Reference
attach_molle_inventory_preset Class Reference
Public Member Functions
attach_molle_inventory_preset (const molle_attach_actor *actor, const item *vest)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Private Attributes
const molle_attach_actor * actor
const item * vest
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 1938 of file game_inventory.cpp.
Constructor & Destructor Documentation
attach_molle_inventory_preset()
attach_molle_inventory_preset::attach_molle_inventory_preset (const molle_attach_actor * actor, const item * vest) inline
Definition at line 1941 of file game_inventory.cpp.
                                                                                            :
             actor( actor ), vest( vest ) {
         }
Member Function Documentation
get_denial()
std::string attach_molle_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 1949 of file game_inventory.cpp.
{
             if( actor->size - vest->get_contents().get_additional_space_used() < loc->get_pocket_size() ) {
                 return "not enough space left on the vest.";
             }
             {
                 return std::string();
             }
         }
References actor, item_contents::get_additional_space_used(), item::get_contents(), item::get_pocket_size(), molle_attach_actor::size, and vest.
is_shown()
bool attach_molle_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 1945 of file game_inventory.cpp.
{
             return loc->can_attach_as_pocket();
         }
References item::can_attach_as_pocket().
Member Data Documentation
actor
const molle_attach_actor* attach_molle_inventory_preset::actor private
Definition at line 1961 of file game_inventory.cpp.
Referenced by get_denial().
vest
const item* attach_molle_inventory_preset::vest private
Definition at line 1962 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp