Cataclysm DDA: dependency_node Class Reference
dependency_node Class Reference
#include <dependency_tree.h>
Public Member Functions
dependency_node ()
dependency_node (const mod_id &key)
void add_parent (dependency_node *parent)
void add_child (dependency_node *child)
bool is_available () const
bool has_errors ()
std::map< NODE_ERROR_TYPE, std::vector< std::string > > errors () const
std::string s_errors ()
std::vector< mod_id > get_dependencies_as_strings ()
std::vector< dependency_node * > get_dependencies_as_nodes ()
std::vector< mod_id > get_dependents_as_strings ()
std::vector< dependency_node * > get_dependents_as_nodes ()
void inherit_errors ()
void check_cyclicity ()
Public Attributes
std::vector< dependency_node * > parents
std::vector< dependency_node * > children
std::map< NODE_ERROR_TYPE, std::vector< std::string > > all_errors
mod_id key
bool availability
int index
int lowlink
bool on_stack
Detailed Description
Definition at line 18 of file dependency_tree.h.
Constructor & Destructor Documentation
dependency_node() [1/2]
dependency_node::dependency_node ()
Definition at line 16 of file dependency_tree.cpp.
                                 : index( -1 ), lowlink( -1 ), on_stack( false )
 {
     availability = true;
 }
References availability.
dependency_node() [2/2]
dependency_node::dependency_node (const mod_id & key) explicit
Definition at line 21 of file dependency_tree.cpp.
                                                     : index( -1 ), lowlink( -1 ),
     on_stack( false )
 {
     key = _key;
     availability = true;
 }
References availability, and key.
Member Function Documentation
add_child()
void dependency_node::add_child (dependency_node * child)
Definition at line 35 of file dependency_tree.cpp.
 {
     if( child ) {
         children.push_back( child );
     }
 }
References children.
Referenced by dependency_tree::build_connections().
add_parent()
void dependency_node::add_parent (dependency_node * parent)
Definition at line 28 of file dependency_tree.cpp.
 {
     if( parent ) {
         parents.push_back( parent );
     }
 }
References parents.
Referenced by dependency_tree::build_connections().
check_cyclicity()
void dependency_node::check_cyclicity ()
Definition at line 62 of file dependency_tree.cpp.
 {
     std::stack<dependency_node *> nodes_to_check;
     std::set<mod_id> nodes_visited;
     for( dependency_node *&elem : parents ) {
         nodes_to_check.push( elem );
     }
     nodes_visited.insert( key );
     while( !nodes_to_check.empty() ) {
         dependency_node *check = nodes_to_check.top();
         nodes_to_check.pop();
         if( nodes_visited.find( check->key ) != nodes_visited.end() ) {
             if( all_errors[CYCLIC].empty() ) {
                 all_errors[CYCLIC].emplace_back( "Error: Circular Dependency Circuit Found!" );
             }
             continue;
         }
         // add check parents, if exist, to stack
         for( dependency_node *&elem : check->parents ) {
             nodes_to_check.push( elem );
         }
         nodes_visited.insert( check->key );
     }
 }
References all_errors, check(), CYCLIC, key, and parents.
errors()
std::map< NODE_ERROR_TYPE, std::vector< std::string > > dependency_node::errors () const
Definition at line 47 of file dependency_tree.cpp.
 {
     return all_errors;
 }
References all_errors.
get_dependencies_as_nodes()
std::vector< dependency_node * > dependency_node::get_dependencies_as_nodes ()
Definition at line 157 of file dependency_tree.cpp.
 {
     std::vector<dependency_node *> dependencies;
     std::vector<dependency_node *> ret;
     std::set<mod_id> found;
     std::stack<dependency_node *> nodes_to_check;
     for( dependency_node *&elem : parents ) {
         nodes_to_check.push( elem );
     }
     found.insert( key );
     while( !nodes_to_check.empty() ) {
         dependency_node *check = nodes_to_check.top();
         nodes_to_check.pop();
         // make sure that the one we are checking is not THIS one
         if( found.find( check->key ) != found.end() ) {
             continue; // just keep going, we aren't really caring about availability right now
         }
         // add check to dependencies
         dependencies.push_back( check );
         // add parents to check list
         for( dependency_node *&elem : check->parents ) {
             nodes_to_check.push( elem );
         }
         found.insert( check->key );
     }
     // sort from the back!
     for( std::vector<dependency_node *>::reverse_iterator it =
              dependencies.rbegin();
          it != dependencies.rend(); ++it ) {
         if( std::find( ret.begin(), ret.end(), *it ) == ret.end() ) {
             ret.push_back( *it );
         }
     }
     return ret;
 }
References check(), key, parents, and cata::hash64_detail::ret.
Referenced by get_dependencies_as_strings().
get_dependencies_as_strings()
std::vector< mod_id > dependency_node::get_dependencies_as_strings ()
Definition at line 141 of file dependency_tree.cpp.
 {
     std::vector<mod_id> ret;
     std::vector<dependency_node *> as_nodes = get_dependencies_as_nodes();
     ret.reserve( as_nodes.size() );
     for( dependency_node *&as_node : as_nodes ) {
         ret.push_back( as_node->key );
     }
     // returns dependencies in a guaranteed valid order
     return ret;
 }
References get_dependencies_as_nodes(), and cata::hash64_detail::ret.
get_dependents_as_nodes()
std::vector< dependency_node * > dependency_node::get_dependents_as_nodes ()
Definition at line 216 of file dependency_tree.cpp.
 {
     std::vector<dependency_node *> dependents;
     std::vector<dependency_node *> ret;
     std::set<mod_id> found;
     std::stack<dependency_node *> nodes_to_check;
     for( dependency_node *&elem : children ) {
         nodes_to_check.push( elem );
     }
     found.insert( key );
     while( !nodes_to_check.empty() ) {
         dependency_node *check = nodes_to_check.top();
         nodes_to_check.pop();
         if( found.find( check->key ) != found.end() ) {
             // skip it because we recursed for some reason
             continue;
         }
         dependents.push_back( check );
         for( dependency_node *&elem : check->children ) {
             nodes_to_check.push( elem );
         }
         found.insert( check->key );
     }
     // sort from front, keeping only one copy of the node
     for( dependency_node *&dependent : dependents ) {
         if( std::find( ret.begin(), ret.end(), dependent ) == ret.end() ) {
             ret.push_back( dependent );
         }
     }
     return ret;
 }
References check(), children, key, and cata::hash64_detail::ret.
Referenced by get_dependents_as_strings().
get_dependents_as_strings()
std::vector< mod_id > dependency_node::get_dependents_as_strings ()
Definition at line 200 of file dependency_tree.cpp.
 {
     std::vector<mod_id> ret;
     std::vector<dependency_node *> as_nodes = get_dependents_as_nodes();
     ret.reserve( as_nodes.size() );
     for( dependency_node *&as_node : as_nodes ) {
         ret.push_back( as_node->key );
     }
     // returns dependencies in a guaranteed valid order
     return ret;
 }
References get_dependents_as_nodes(), and cata::hash64_detail::ret.
has_errors()
bool dependency_node::has_errors ()
Definition at line 91 of file dependency_tree.cpp.
 {
     bool ret = false;
     for( auto &elem : all_errors ) {
         if( !elem.second.empty() ) {
             ret = true;
             break;
         }
     }
     return ret;
 }
References all_errors, and cata::hash64_detail::ret.
Referenced by mod_ui::try_add().
inherit_errors()
void dependency_node::inherit_errors ()
Definition at line 103 of file dependency_tree.cpp.
 {
     std::stack<dependency_node * > nodes_to_check;
     std::set<mod_id> nodes_visited;
     for( dependency_node *&elem : parents ) {
         nodes_to_check.push( elem );
     }
     nodes_visited.insert( key );
     while( !nodes_to_check.empty() ) {
         dependency_node *check = nodes_to_check.top();
         nodes_to_check.pop();
         // add check errors
         std::map<NODE_ERROR_TYPE, std::vector<std::string > > cerrors = check->errors();
         for( auto &cerror : cerrors ) {
             std::vector<std::string> node_errors = cerror.second;
             NODE_ERROR_TYPE error_type = cerror.first;
             std::vector<std::string> cur_errors = all_errors[error_type];
             for( auto &node_error : node_errors ) {
                 if( std::find( cur_errors.begin(), cur_errors.end(), node_error ) ==
                     cur_errors.end() ) {
                     all_errors[cerror.first].push_back( node_error );
                 }
             }
         }
         if( nodes_visited.find( check->key ) != nodes_visited.end() ) {
             continue;
         }
         // add check parents, if exist, to stack
         for( dependency_node *&elem : check->parents ) {
             nodes_to_check.push( elem );
         }
         nodes_visited.insert( check->key );
     }
 }
References all_errors, check(), key, and parents.
is_available()
bool dependency_node::is_available () const
Definition at line 42 of file dependency_tree.cpp.
 {
     return all_errors.empty();
 }
References all_errors.
s_errors()
std::string dependency_node::s_errors ()
Definition at line 52 of file dependency_tree.cpp.
 {
     std::string ret;
     for( auto &elem : all_errors ) {
         ret += error_keyvals[static_cast<unsigned>( elem.first )];
         ret += enumerate_as_string( elem.second, enumeration_conjunction::none );
     }
     return ret;
 }
References all_errors, enumerate_as_string(), error_keyvals, none, and cata::hash64_detail::ret.
Referenced by game::check_mod_data().
Member Data Documentation
all_errors
std::map<NODE_ERROR_TYPE, std::vector<std::string> > dependency_node::all_errors
Definition at line 22 of file dependency_tree.h.
Referenced by dependency_tree::build_connections(), check_cyclicity(), errors(), has_errors(), inherit_errors(), is_available(), and s_errors().
availability
bool dependency_node::availability
Definition at line 24 of file dependency_tree.h.
Referenced by dependency_node().
children
std::vector<dependency_node *> dependency_node::children
Definition at line 21 of file dependency_tree.h.
Referenced by add_child(), and get_dependents_as_nodes().
index
int dependency_node::index
Definition at line 27 of file dependency_tree.h.
Referenced by dependency_tree::strong_connect().
key
mod_id dependency_node::key
Definition at line 23 of file dependency_tree.h.
Referenced by check_cyclicity(), dependency_node(), get_dependencies_as_nodes(), get_dependents_as_nodes(), inherit_errors(), and dependency_tree::strong_connect().
lowlink
int dependency_node::lowlink
Definition at line 28 of file dependency_tree.h.
Referenced by dependency_tree::strong_connect().
on_stack
bool dependency_node::on_stack
Definition at line 29 of file dependency_tree.h.
Referenced by dependency_tree::strong_connect().
parents
std::vector<dependency_node *> dependency_node::parents
Definition at line 21 of file dependency_tree.h.
Referenced by add_parent(), check_cyclicity(), get_dependencies_as_nodes(), inherit_errors(), and dependency_tree::strong_connect().
The documentation for this class was generated from the following files:
src/dependency_tree.h
src/dependency_tree.cpp