Cataclysm DDA: inventory_examiner Class Reference
inventory_examiner Class Reference
#include <inventory_ui.h>
Public Member Functions
inventory_examiner (Character &p, item_location item_to_look_inside, const inventory_selector_preset &preset=default_preset)
bool check_parent_item ()
If parent_item has no contents or is otherwise unsuitable for inventory_examiner, return false.
int cleanup () const
If the parent_item had items hidden, re-hides them.
void draw_item_details (const item_location &sitem)
Draw the details of sitem in the w_examine window.
int execute ()
Method to display the inventory_examiner menu.
void setup ()
Does initial setup work prior to display of the window.
Public Member Functions inherited from inventory_selector
inventory_selector (Character &u, const inventory_selector_preset &preset=default_preset)
virtual ~inventory_selector ()
bool add_contained_items (item_location &container)
These functions add items from map / vehicles.
bool add_contained_items (item_location &container, inventory_column &column, const item_category *custom_category=nullptr, item_location const &topmost_parent={}, int indent=0)
void add_contained_gunmods (Character &you, item &gun)
void add_contained_ebooks (item_location &container)
void add_character_items (Character &character)
void add_map_items (const tripoint &target)
void add_vehicle_items (const tripoint &target)
void add_nearby_items (int radius=1)
void add_remote_map_items (tinymap *remote_map, const tripoint &target)
void add_basecamp_items (const basecamp &camp)
void clear_items ()
Remove all items.
void set_title (const std::string &title)
Assigns a title that will be shown on top of the menu.
void set_hint (const std::string &hint)
Assigns a hint.
void set_display_stats (bool display_stats)
Specify whether the header should show stats (weight and volume).
bool empty () const
bool has_available_choices () const
uint64_t item_entry_count () const
drop_location get_only_choice () const
void set_filter (const std::string &str)
Apply filter string to all columns.
std::string get_filter () const
Get last filter string set by set_filter or entered by player.
void set_invlet_type (selector_invlet_type type)
Set the letter group to use for automatic inventory letters.
selector_invlet_type invlet_type ()
void show_invlet (bool show)
Set whether to show inventory letters.
bool showing_invlet () const
void categorize_map_items (bool toggle)
bool highlight (const item_location &loc, bool hidden=false, bool front_only=false)
Highlight a location.
const inventory_entry & get_highlighted () const
item_location get_collation_next () const
void highlight_position (std::pair< size_t, size_t > position)
bool highlight_one_of (const std::vector< item_location > &locations, bool hidden=false)
std::pair< size_t, size_t > get_highlighted_position () const
inventory_column & get_column (size_t index) const
inventory_column & get_active_column () const
void toggle_categorize_contained ()
void set_active_column (size_t index)
void toggle_skip_unselectable ()
std::string action_bound_to_key (char key) const
Protected Attributes
item_location parent_item
item_location selected_item
catacurses::window w_examine
bool changes_made
bool parent_was_collapsed
Protected Attributes inherited from inventory_selector
Character & u
const inventory_selector_preset & preset
input_context ctxt
The input context for navigation, already contains some actions for movement.
std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * > > rect_entry_map
std::vector< inventory_column * > columns
point _fixed_origin { -1, -1 }
point _fixed_size { -1, -1 }
bool _categorize_map_items = false
bool force_single_column = false
Private Member Functions
void force_max_window_size ()
Private Attributes
int examine_window_scroll
int scroll_item_info_lines
Additional Inherited Members
Public Types inherited from inventory_selector
enum selector_invlet_type { SELECTOR_INVLET_DEFAULT , SELECTOR_INVLET_NUMERIC , SELECTOR_INVLET_ALPHA }
enum class uimode : int { categories = 0 , hierarchy , last }
using stat = std::array< std::string, 4 >
using stats = std::array< stat, 3 >
Protected Member Functions inherited from inventory_selector
const item_category * naturalize_category (const item_category &category, const tripoint &pos)
inventory_entry * add_entry (inventory_column &target_column, std::vector< item_location > &&locations, const item_category *custom_category=nullptr, size_t chosen_count=0, item_location const &topmost_parent={}, bool chevron=false)
bool add_entry_rec (inventory_column &entry_column, inventory_column &children_column, item_location &loc, item_category const *entry_category=nullptr, item_category const *children_category=nullptr, item_location const &topmost_parent={}, int indent=0)
bool drag_drop_item (item *sourceItem, item *destItem)
inventory_input get_input ()
inventory_input process_input (const std::string &action, int ch)
void on_input (const inventory_input &input)
Given an action from the input_context, try to act according to it.
void on_change (const inventory_entry &entry)
Entry has been changed.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
size_t get_layout_width () const
size_t get_layout_height () const
std::pair< bool, std::string > query_string (const std::string &val, bool end_with_toggle=false)
Query user for a string and return it.
void query_set_filter ()
Query the user for a filter and apply it.
int query_count (char init=0, bool end_with_toggle=false)
Query the user for count and return it.
virtual void rearrange_columns (size_t client_width)
Tackles screen overflow.
virtual stats get_raw_stats () const
Get stats to display in top right.
std::vector< std::string > get_stats () const
std::pair< std::string, nc_color > get_footer (navigation_mode m) const
size_t get_header_height () const
size_t get_header_min_width () const
size_t get_footer_min_width () const
inventory_entry * find_entry_by_invlet (int invlet) const
inventory_entry * find_entry_by_coordinate (const point &coordinate) const
inventory_entry * find_entry_by_location (item_location &loc) const
const std::vector< inventory_column * > & get_all_columns () const
std::vector< inventory_column * > get_visible_columns () const
void highlight ()
Highlight parent and contents of highlighted item.
void action_examine (const item_location &sitem)
Show detailed item information for the selected item.
virtual void reassign_custom_invlets ()
size_t get_columns_width (const std::vector< inventory_column * > &columns) const
double get_columns_occupancy_ratio (size_t client_width) const
bool are_columns_centered (size_t client_width) const
bool is_overflown (size_t client_width) const
bool is_active_column (const inventory_column &column) const
void append_column (inventory_column &column)
void toggle_active_column (scroll_direction dir)
Activates either previous or next column.
void refresh_active_column ()
void toggle_navigation_mode ()
const navigation_mode_data & get_navigation_data (navigation_mode m) const
Static Protected Member Functions inherited from inventory_selector
static stat get_weight_and_length_stat (units::mass weight_carried, units::mass weight_capacity, const units::length &longest_length)
static stat get_volume_stat (const units::volume &volume_carried, const units::volume &volume_capacity, const units::volume &largest_free_volume)
static stat get_holster_stat (const units::volume &holster_volume, int used_holsters, int total_holsters)
static stats get_weight_and_volume_and_holster_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume &volume_carried, const units::volume &volume_capacity, const units::length &longest_length, const units::volume &largest_free_volume, const units::volume &holster_volume, int used_holsters, int total_holsters)
Detailed Description
Definition at line 1082 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_examiner()
inventory_examiner::inventory_examiner (Character & p, item_location item_to_look_inside, const inventory_selector_preset & preset = default_preset) inline explicit
Definition at line 1098 of file inventory_ui.h.
                                                                                                 :
             inventory_selector( p, preset ) {
             force_max_window_size();
             examine_window_scroll = 0;
             selected_item = item_location::nowhere;
             parent_item = std::move( item_to_look_inside );
             changes_made = false;
             parent_was_collapsed = false;
             //Space in inventory isn't particularly relevant, so don't display it
             set_display_stats( false );
             setup();
         }
References changes_made, examine_window_scroll, force_max_window_size(), item_location::nowhere, parent_item, parent_was_collapsed, selected_item, inventory_selector::set_display_stats(), and setup().
Member Function Documentation
check_parent_item()
bool inventory_examiner::check_parent_item ()
If parent_item has no contents or is otherwise unsuitable for inventory_examiner, return false.
Otherwise, true
Definition at line 4321 of file inventory_ui.cpp.
 {
     return !( parent_item->is_container_empty() || empty() );
 }
References inventory_selector::empty(), item::is_container_empty(), and parent_item.
Referenced by execute().
cleanup()
int inventory_examiner::cleanup () const
If the parent_item had items hidden, re-hides them.
Determines the appropriate return value for execute()
Called at the end of execute(). Checks if anything was changed (e.g. show/hide contents), and selects the appropriate return value
Definition at line 4326 of file inventory_ui.cpp.
 {
     if( changes_made ) {
         return EXAMINED_CONTENTS_WITH_CHANGES;
     } else {
         return EXAMINED_CONTENTS_UNCHANGED;
     }
 }
References changes_made, EXAMINED_CONTENTS_UNCHANGED, and EXAMINED_CONTENTS_WITH_CHANGES.
Referenced by execute().
draw_item_details()
void inventory_examiner::draw_item_details (const item_location & sitem)
Draw the details of sitem in the w_examine window.
Definition at line 4335 of file inventory_ui.cpp.
 {
     std::vector<iteminfo> vThisItem;
     std::vector<iteminfo> vDummy;
     sitem->info( true, vThisItem );
     item_info_data data( sitem->tname(), sitem->type_name(), vThisItem, vDummy, examine_window_scroll );
     data.without_getch = true;
     draw_item_info( w_examine, data );
 }
References draw_item_info(), examine_window_scroll, item::info(), item::tname(), item::type_name(), w_examine, and item_info_data::without_getch.
Referenced by execute().
execute()
int inventory_examiner::execute ()
Method to display the inventory_examiner menu.
Sets up ui_adaptor callbacks for w_examine to draw the item detail pane and allow it to be resized Figures out which item is currently selected and calls draw_item_details Passes essentially everything else back to inventory_selector for handling. If the user changed something while looking through the item's contents (e.g. collapsing a container), it should return EXAMINED_CONTENTS_WITH_CHANGES to inform the parent window. If the parent_item has no contents to examine, it should return NO_CONTENTS_TO_EXAMINE, telling the parent window to examine the item with action_examine()
Definition at line 4355 of file inventory_ui.cpp.
 {
     if( !check_parent_item() ) {
         return NO_CONTENTS_TO_EXAMINE;
     }
     shared_ptr_fast<ui_adaptor> ui = create_or_get_ui_adaptor();
     debug_print_timer( tp_start );
     ui_adaptor ui_examine;
     ui_examine.on_screen_resize( [&]( ui_adaptor & ui_examine ) {
         force_max_window_size();
         ui->mark_resize();
         int const width = TERMX - _fixed_size.x;
         int const height = TERMY;
         point const start_position = point( TERMX - width, 0 );
         scroll_item_info_lines = TERMY / 2;
         w_examine = catacurses::newwin( height, width, start_position );
         ui_examine.position_from_window( w_examine );
     } );
     ui_examine.mark_resize();
     ui_examine.on_redraw( [&]( const ui_adaptor & ) {
         const inventory_entry &selected = get_active_column().get_highlighted();
         if( selected ) {
             if( selected_item != selected.any_item() ) {
                 //A new item has been selected, reset scrolling
                 examine_window_scroll = 0;
                 selected_item = selected.any_item();
             }
             draw_item_details( selected_item );
         }
     } );
     while( true ) {
         /* Since ui_examine is the most recently created ui_adaptor, it will always be redrawn.
          The item list will only be redrawn when specifically invalidated */
         ui_manager::redraw();
         const inventory_input input = get_input();
         if( input.entry != nullptr ) {
             if( highlight( input.entry->any_item() ) ) {
                 ui_manager::redraw();
             }
             if( input.action == "SELECT" ) {
                 return cleanup();
             }
         }
         if( input.action == "QUIT" || input.action == "CONFIRM" ) {
             return cleanup();
         } else if( input.action == "PAGE_UP" || input.action == "SCROLL_UP" ) {
             examine_window_scroll -= scroll_item_info_lines;
         } else if( input.action == "PAGE_DOWN" || input.action == "SCROLL_DOWN" ) {
             examine_window_scroll += scroll_item_info_lines;
         } else {
             ui->invalidate_ui(); //The player is probably doing something that requires updating the base window
             if( input.action == "SHOW_HIDE_CONTENTS" ) {
                 changes_made = true;
             }
             on_input( input );
         }
     }
 }
References inventory_selector::_fixed_size, inventory_input::action, inventory_entry::any_item(), changes_made, check_parent_item(), cleanup(), inventory_selector::create_or_get_ui_adaptor(), anonymous_namespace{inventory_ui.cpp}::debug_print_timer(), draw_item_details(), inventory_input::entry, examine_window_scroll, force_max_window_size(), inventory_selector::get_active_column(), inventory_column::get_highlighted(), inventory_selector::get_input(), inventory_selector::highlight(), ui_adaptor::mark_resize(), catacurses::newwin(), NO_CONTENTS_TO_EXAMINE, inventory_selector::on_input(), ui_adaptor::on_redraw(), ui_adaptor::on_screen_resize(), point, ui_adaptor::position_from_window(), ui_manager::redraw(), scroll_item_info_lines, selected_item, TERMX, TERMY, anonymous_namespace{inventory_ui.cpp}::tp_start, w_examine, and point::x.
Referenced by advanced_inventory::display(), and inventory_selector::on_input().
force_max_window_size()
void inventory_examiner::force_max_window_size () private
Definition at line 4348 of file inventory_ui.cpp.
 {
     constexpr int border_width = 1;
     _fixed_size = { TERMX / 3 + 2 * border_width, TERMY };
     _fixed_origin = point_zero;
 }
References inventory_selector::_fixed_origin, inventory_selector::_fixed_size, point_zero, TERMX, and TERMY.
Referenced by execute(), and inventory_examiner().
setup()
void inventory_examiner::setup ()
Does initial setup work prior to display of the window.
Definition at line 4424 of file inventory_ui.cpp.
 {
     if( parent_item == item_location::nowhere ) {
         set_title( "ERROR: Item not found" );
     } else {
         set_title( parent_item->display_name() );
     }
 }
References item::display_name(), item_location::nowhere, parent_item, and inventory_selector::set_title().
Referenced by inventory_examiner().
Member Data Documentation
changes_made
bool inventory_examiner::changes_made protected
Definition at line 1094 of file inventory_ui.h.
Referenced by cleanup(), execute(), and inventory_examiner().
examine_window_scroll
int inventory_examiner::examine_window_scroll private
Definition at line 1085 of file inventory_ui.h.
Referenced by draw_item_details(), execute(), and inventory_examiner().
parent_item
item_location inventory_examiner::parent_item protected
Definition at line 1091 of file inventory_ui.h.
Referenced by check_parent_item(), inventory_examiner(), and setup().
parent_was_collapsed
bool inventory_examiner::parent_was_collapsed protected
Definition at line 1095 of file inventory_ui.h.
Referenced by inventory_examiner().
scroll_item_info_lines
int inventory_examiner::scroll_item_info_lines private
Definition at line 1086 of file inventory_ui.h.
Referenced by execute().
selected_item
item_location inventory_examiner::selected_item protected
Definition at line 1092 of file inventory_ui.h.
Referenced by execute(), and inventory_examiner().
w_examine
catacurses::window inventory_examiner::w_examine protected
Definition at line 1093 of file inventory_ui.h.
Referenced by draw_item_details(), and execute().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp