Cataclysm DDA: item_location::impl::nowhere Class Reference
item_location::impl::nowhere Class Reference
Public Member Functions
type where () const override
tripoint position () const override
Character * carrier () const override
std::string describe (const Character *) const override
item_location obtain (Character &, int) override
int obtain_cost (const Character &, int) const override
void remove_item () override
void on_contents_changed () override
item * unpack (int) const override
void serialize (JsonOut &js) const override
units::volume volume_capacity () const override
units::mass weight_capacity () const override
bool check_parent_capacity_recursive () const override
Public Member Functions inherited from item_location::impl
impl ()=default
impl (item *i)
impl (int idx)
virtual ~impl ()=default
virtual type where_recursive () const
virtual item_location parent_item () const
virtual item_pocket * parent_pocket () const
item * target () const
virtual bool valid () const
Additional Inherited Members
Public Attributes inherited from item_location::impl
bool should_stack = true
Detailed Description
Definition at line 135 of file item_location.cpp.
Member Function Documentation
carrier()
Character* item_location::impl::nowhere::carrier () const inline override virtual
Implements item_location::impl.
Definition at line 147 of file item_location.cpp.
{
             return nullptr;
         }
check_parent_capacity_recursive()
bool item_location::impl::nowhere::check_parent_capacity_recursive () const inline override virtual
Implements item_location::impl.
Definition at line 192 of file item_location.cpp.
{
             return false;
         }
describe()
std::string item_location::impl::nowhere::describe (const Character *) const inline override virtual
Implements item_location::impl.
Definition at line 151 of file item_location.cpp.
{
             debugmsg( "invalid use of nowhere item_location" );
             return "";
         }
References debugmsg.
obtain()
item_location item_location::impl::nowhere::obtain (Character & , int) inline override virtual
Implements item_location::impl.
Definition at line 156 of file item_location.cpp.
{
             debugmsg( "invalid use of nowhere item_location" );
             return item_location();
         }
References debugmsg, and item_location::item_location().
obtain_cost()
int item_location::impl::nowhere::obtain_cost (const Character & , int) const inline override virtual
Implements item_location::impl.
Definition at line 161 of file item_location.cpp.
{
             debugmsg( "invalid use of nowhere item_location" );
             return 0;
         }
References debugmsg.
on_contents_changed()
void item_location::impl::nowhere::on_contents_changed () inline override virtual
Implements item_location::impl.
Definition at line 170 of file item_location.cpp.
{
             debugmsg( "invalid use of nowhere item_location" );
         }
References debugmsg.
position()
tripoint item_location::impl::nowhere::position () const inline override virtual
Implements item_location::impl.
Definition at line 142 of file item_location.cpp.
{
             debugmsg( "invalid use of nowhere item_location" );
             return tripoint_min;
         }
References debugmsg, and tripoint_min.
remove_item()
void item_location::impl::nowhere::remove_item () inline override virtual
Implements item_location::impl.
Definition at line 166 of file item_location.cpp.
{
             debugmsg( "invalid use of nowhere item_location" );
         }
References debugmsg.
serialize()
void item_location::impl::nowhere::serialize (JsonOut & js) const inline override virtual
Implements item_location::impl.
Definition at line 178 of file item_location.cpp.
{
             js.start_object();
             js.member( "type", "null" );
             js.end_object();
         }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
unpack()
item* item_location::impl::nowhere::unpack (int) const inline override virtual
Implements item_location::impl.
Definition at line 174 of file item_location.cpp.
{
             return nullptr;
         }
volume_capacity()
units::volume item_location::impl::nowhere::volume_capacity () const inline override virtual
Implements item_location::impl.
Definition at line 184 of file item_location.cpp.
{
             return units::volume();
         }
weight_capacity()
units::mass item_location::impl::nowhere::weight_capacity () const inline override virtual
Implements item_location::impl.
Definition at line 188 of file item_location.cpp.
{
             return units::mass();
         }
where()
type item_location::impl::nowhere::where () const inline override virtual
Implements item_location::impl.
Definition at line 138 of file item_location.cpp.
{
             return type::invalid;
         }
References item_location::invalid.
The documentation for this class was generated from the following file:
src/item_location.cpp