Cataclysm DDA: inventory_column Class Reference
inventory_column Class Reference
#include <inventory_ui.h>
Classes
struct cell_t
Public Types
using get_entries_t = std::vector< inventory_entry * >
using ffilter_t = std::function< bool(const inventory_entry &entry)>
Public Member Functions
inventory_column (const inventory_selector_preset &preset=default_preset)
virtual ~inventory_column ()=default
bool empty () const
virtual bool activatable () const
Can this column be activated?
bool visible () const
Is this column visible?
virtual bool allows_selecting () const
Does this column allow selecting? "Cosmetic" columns (list of selected items) can explicitly prohibit selecting.
size_t page_index () const
size_t pages_count () const
bool has_available_choices () const
bool is_selected (const inventory_entry &entry) const
bool is_highlighted (const inventory_entry &entry) const
bool is_selected_by_category (const inventory_entry &entry) const
Does this entry belong to the selected category? When navigation_mode::ITEM is used it's equivalent to is_selected().
const inventory_entry & get_highlighted () const
inventory_entry & get_highlighted ()
std::vector< inventory_entry * > get_all_selected () const
get_entries_t get_entries (const ffilter_t &filter_func, bool include_hidden=false) const
void order_by_parent ()
inventory_entry * find_by_invlet (int invlet) const
inventory_entry * find_by_location (item_location const &loc, bool hidden=false) const
void draw (const catacurses::window &win, const point &p, std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * >> &rect_entry_map)
inventory_entry * add_entry (const inventory_entry &entry)
void move_entries_to (inventory_column &dest)
void clear ()
void set_stack_favorite (inventory_entry &entry, bool favorite)
void set_collapsed (inventory_entry &entry, bool collapse)
bool highlight (const item_location &loc, bool front_only=false)
Highlights the specified location.
void highlight (size_t new_index, scroll_direction dir)
Change the highlight.
size_t get_highlighted_index () const
void set_multiselect (bool multiselect)
void set_visibility (bool visibility)
void set_width (size_t new_width)
void set_height (size_t new_height)
size_t get_width () const
size_t get_height () const
void expand_to_fit (inventory_entry &entry, bool with_denial=true)
Expands the column to fit the new entry.
virtual void reset_width (const std::vector< inventory_column * > &all_columns)
Resets width to original (unchanged).
int reassign_custom_invlets (const Character &p, int min_invlet, int max_invlet)
Returns next custom inventory letter.
int reassign_custom_invlets (int cur_idx, std::string_view pickup_chars)
virtual void prepare_paging (const std::string &filter="")
Reorder entries, repopulate titles, adjust to the new height.
virtual void on_input (const inventory_input &input)
Event handlers.
virtual void on_change (const inventory_entry &entry)
The entry has been changed.
virtual void on_activate ()
The column has been activated.
virtual void on_deactivate ()
The column has been deactivated.
virtual void on_mode_change (navigation_mode mode)
Selection mode has been changed.
virtual void set_filter (const std::string &filter)
bool indent_entries () const
bool collate_entries () const
void set_indent_entries_override (bool entry_override)
void clear_indent_entries_override ()
void invalidate_paging ()
void toggle_skip_unselectable (bool skip)
Toggle being able to highlight unselectable entries.
void collate ()
void uncollate ()
virtual void cycle_hide_override ()
Protected Types
using entries_t = std::vector< inventory_entry >
Protected Member Functions
void move_selection (scroll_direction dir)
Move the selection.
void move_selection_page (scroll_direction dir)
void scroll_selection_page (scroll_direction dir)
size_t next_highlightable_index (size_t index, scroll_direction dir) const
size_t page_of (size_t index) const
size_t page_of (const inventory_entry &entry) const
bool sort_compare (inventory_entry const &lhs, inventory_entry const &rhs)
bool indented_sort_compare (inventory_entry const &lhs, inventory_entry const &rhs)
bool collated_sort_compare (inventory_entry const &lhs, inventory_entry const &rhs)
size_t get_entry_indent (const inventory_entry &entry) const
Indentation of the entry.
size_t get_entry_cell_width (const inventory_entry &entry, size_t cell_index) const
Overall cell width.
size_t get_cells_width () const
Sum of the cell widths.
Protected Attributes
const inventory_selector_preset & preset
entries_t entries
entries_t entries_hidden
navigation_mode mode = navigation_mode::ITEM
bool active = false
bool multiselect = false
bool paging_is_valid = false
bool visibility = true
size_t highlighted_index = std::numeric_limits<size_t>::max()
size_t page_offset = 0
size_t entries_per_page = std::numeric_limits<size_t>::max()
size_t height = std::numeric_limits<size_t>::max()
size_t reserved_width = 0
std::optional< bool > hide_entries_override = std::nullopt
Private Member Functions
size_t visible_cells () const
void _get_entries (get_entries_t *res, entries_t const &ent, const ffilter_t &filter_func) const
Static Private Member Functions
static void _move_entries_to (entries_t const &ent, inventory_column &dest)
static void _reset_collation (entries_t &ent)
Private Attributes
std::vector< cell_t > cells
std::optional< bool > indent_entries_override = std::nullopt
bool skip_unselectable = false
bool _collated = false
Detailed Description
Definition at line 337 of file inventory_ui.h.
Member Typedef Documentation
entries_t
using inventory_column::entries_t = std::vector<inventory_entry> protected
Definition at line 529 of file inventory_ui.h.
ffilter_t
using inventory_column::ffilter_t = std::function<bool(const inventory_entry &entry)>
Definition at line 388 of file inventory_ui.h.
get_entries_t
using inventory_column::get_entries_t = std::vector<inventory_entry *>
Definition at line 387 of file inventory_ui.h.
Constructor & Destructor Documentation
inventory_column()
inventory_column::inventory_column (const inventory_selector_preset & preset = default_preset) explicit
Definition at line 620 of file inventory_ui.cpp.
                                                                             :
     preset( preset )
 {
     hide_entries_override = uistate.hide_entries_override;
     cells.resize( preset.get_cells_count() );
 }
References cells, inventory_selector_preset::get_cells_count(), hide_entries_override, uistatedata::hide_entries_override, preset, and uistate.
~inventory_column()
virtual inventory_column::~inventory_column () virtual default
Member Function Documentation
_get_entries()
void inventory_column::_get_entries (get_entries_t * res, entries_t const & ent, const ffilter_t & filter_func) const private
Definition at line 1181 of file inventory_ui.cpp.
 {
     if( allows_selecting() ) {
         for( const inventory_entry &elem : ent ) {
             if( filter_func( elem ) ) {
                 res->push_back( const_cast<inventory_entry *>( &elem ) );
             }
         }
     }
 }
_move_entries_to()
static void inventory_column::_move_entries_to (entries_t const & ent, inventory_column & dest) static private
_reset_collation()
void inventory_column::_reset_collation (entries_t & ent) static private
Definition at line 1453 of file inventory_ui.cpp.
 {
     for( auto iter = entries.begin(); iter != entries.end(); ) {
         if( iter->is_collation_header() ) {
             iter = entries.erase( iter );
         } else {
             iter->reset_collation();
             ++iter;
         }
     }
 }
activatable()
bool inventory_column::activatable () const virtual
Can this column be activated?
Returns
Whether the column contains selectable entries. Note: independent from 'allows_selecting'
Reimplemented in selection_column.
Definition at line 627 of file inventory_ui.cpp.
 {
     return std::any_of( entries.begin(), entries.end(), [this]( const inventory_entry & e ) {
         return e.is_highlightable( skip_unselectable );
     } );
 }
References entries.
Referenced by selection_column::activatable(), and inventory_selector::highlight().
add_entry()
inventory_entry * inventory_column::add_entry (const inventory_entry & entry)
Definition at line 1282 of file inventory_ui.cpp.
 {
     entries_t &dest = entry.is_hidden( hide_entries_override ) ? entries_hidden : entries;
     if( auto it = std::find( dest.begin(), dest.end(), entry ); it != dest.end() ) {
         debugmsg( "Tried to add a duplicate entry." );
         return &*it;
     }
     paging_is_valid = false;
     if( entry.is_item() ) {
         item_location entry_item = entry.locations.front();
         auto entry_with_loc = std::find_if( dest.begin(),
         dest.end(), [&entry, &entry_item, this]( const inventory_entry & e ) {
             if( !e.is_item() ) {
                 return false;
             }
             item_location found_entry_item = e.locations.front();
             return !e.is_collated() &&
                    e.get_category_ptr() == entry.get_category_ptr() &&
                    entry_item.where() == found_entry_item.where() &&
                    entry_item.position() == found_entry_item.position() &&
                    entry_item.parent_item() == found_entry_item.parent_item() &&
                    entry_item->is_collapsed() == found_entry_item->is_collapsed() &&
                    entry_item->link_length() == found_entry_item->link_length() &&
                    entry_item->max_link_length() == found_entry_item->max_link_length() &&
                    entry_item->display_stacked_with( *found_entry_item, preset.get_checking_components() );
         } );
         if( entry_with_loc != dest.end() ) {
             std::vector<item_location> &locations = entry_with_loc->locations;
             std::move( entry.locations.begin(), entry.locations.end(), std::back_inserter( locations ) );
             return &*entry_with_loc;
         }
     }
     dest.emplace_back( entry );
     inventory_entry &newent = dest.back();
     newent.update_cache();
     return &newent;
 }
References debugmsg, item::display_stacked_with(), inventory_entry::get_category_ptr(), item::is_collapsed(), inventory_entry::is_collated(), inventory_entry::is_hidden(), inventory_entry::is_item(), item::link_length(), inventory_entry::locations, anonymous_namespace{overmap_location.cpp}::locations, item::max_link_length(), item_location::parent_item(), item_location::position(), and item_location::where().
Referenced by inventory_selector::add_entry(), selection_column::on_change(), and inventory_selector::toggle_categorize_contained().
allows_selecting()
virtual bool inventory_column::allows_selecting () const inline virtual
Does this column allow selecting? "Cosmetic" columns (list of selected items) can explicitly prohibit selecting.
Note: independent from 'activatable'
Reimplemented in selection_column.
Definition at line 362 of file inventory_ui.h.
{
             return true;
         }
clear()
void inventory_column::clear ()
Definition at line 1553 of file inventory_ui.cpp.
 {
     entries.clear();
     entries_hidden.clear();
     paging_is_valid = false;
 }
Referenced by inventory_selector::clear_items(), and inventory_selector::toggle_categorize_contained().
clear_indent_entries_override()
void inventory_column::clear_indent_entries_override () inline
Definition at line 481 of file inventory_ui.h.
{
             indent_entries_override = std::nullopt;
         }
References indent_entries_override.
Referenced by inventory_selector::_uncategorize().
collate()
void inventory_column::collate ()
Definition at line 1413 of file inventory_ui.cpp.
 {
     for( auto outer = entries.begin(); outer != entries.end(); ++outer ) {
         if( !outer->is_item() || outer->is_collated() || outer->chevron ) {
             continue;
         }
         for( auto e = std::next( outer ); e != entries.end(); ) {
             if( e->is_item() && e->get_category_ptr() == outer->get_category_ptr() &&
                 e->any_item()->is_favorite == outer->any_item()->is_favorite &&
                 e->any_item()->typeId() == outer->any_item()->typeId() &&
                 std::min( 0, e->any_item()->link_length() ) == std::min( 0, outer->any_item()->link_length() ) &&
                 e->any_item()->max_link_length() == outer->any_item()->max_link_length() &&
                 ( !indent_entries() ||
                   e->any_item().parent_item() == outer->any_item().parent_item() ) &&
                 ( e->is_collation_header() || !e->chevron ) &&
                 e->any_item()->is_same_relic( *outer->any_item() ) ) {
                 if( !outer->is_collated() ) {
                     outer->collation_meta = std::make_shared<collation_meta_t>(
                                                 collation_meta_t{ outer->any_item(), true, outer->is_selectable() } );
                     entries_hidden.emplace_back( *outer );
                     outer->chevron = true;
                     set_collapsed( *outer, true );
                     outer->reset_entry_cell_cache(); // needed when switching UI modes
                 }
                 e->collation_meta = outer->collation_meta;
                 std::copy( e->locations.begin(), e->locations.end(),
                            std::back_inserter( outer->locations ) );
                 entries_hidden.emplace_back( std::move( *e ) );
                 e = entries.erase( e );
             } else {
                 ++e;
             }
         }
     }
     _collated = true;
 }
References inventory_selector_preset::indent_entries(), and min().
collate_entries()
bool inventory_column::collate_entries () const inline
Definition at line 473 of file inventory_ui.h.
{
             return preset.collate_entries();
         }
References inventory_selector_preset::collate_entries(), and preset.
collated_sort_compare()
bool inventory_column::collated_sort_compare (inventory_entry const & lhs, inventory_entry const & rhs) protected
Definition at line 1383 of file inventory_ui.cpp.
 {
     if( lhs.is_collated() && lhs.collation_meta == rhs.collation_meta ) {
         if( lhs.is_collation_header() ) {
             return true;
         }
         if( rhs.is_collation_header() ) {
             return false;
         }
         return sort_compare( lhs, rhs );
     }
     item_location p_lhs = lhs.is_collated() ? lhs.collation_meta->tip : lhs.any_item();
     item_location p_rhs = rhs.is_collated() ? rhs.collation_meta->tip : rhs.any_item();
     inventory_entry ep_lhs(
     { p_lhs }, nullptr, lhs.is_collated() ? lhs.collation_meta->enabled : lhs.is_selectable(),
     0, lhs.generation );
     inventory_entry ep_rhs(
     { p_rhs }, nullptr, rhs.is_collated() ? rhs.collation_meta->enabled : rhs.is_selectable(),
     0, rhs.generation );
     ep_lhs.update_cache();
     ep_rhs.update_cache();
     if( indent_entries() ) {
         return indented_sort_compare( ep_lhs, ep_rhs );
     }
     return sort_compare( ep_lhs, ep_rhs );
 }
References inventory_entry::any_item(), inventory_entry::collation_meta, inventory_entry::generation, inventory_selector_preset::indent_entries(), inventory_entry::is_collated(), inventory_entry::is_collation_header(), inventory_entry::is_selectable(), inventory_selector_preset::sort_compare(), and inventory_entry::update_cache().
cycle_hide_override()
void inventory_column::cycle_hide_override () virtual
Reimplemented in selection_column.
Definition at line 2965 of file inventory_ui.cpp.
 {
     if( hide_entries_override ) {
         if( *hide_entries_override ) {
             hide_entries_override = std::nullopt;
         } else {
             hide_entries_override = true;
         }
     } else {
         hide_entries_override = false;
     }
     uistate.hide_entries_override = hide_entries_override;
 }
References hide_entries_override, uistatedata::hide_entries_override, and uistate.
draw()
void inventory_column::draw (const catacurses::window & win, const point & p, std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * >> & rect_entry_map)
Definition at line 1628 of file inventory_ui.cpp.
 {
     if( !visible() ) {
         return;
     }
     const auto available_cell_width = [ this ]( inventory_entry const & entry, size_t cell_index ) {
         const size_t displayed_width = cells[cell_index].current_width;
         const size_t real_width = get_entry_cell_width( entry, cell_index );
         return displayed_width > real_width ? displayed_width - real_width : 0;
     };
     // Do the actual drawing
     for( size_t index = page_offset, line = 0; index < entries.size() &&
          line < entries_per_page; ++index, ++line ) {
         inventory_entry &entry = entries[index];
         if( !entry ) {
             continue;
         }
         const inventory_entry::entry_cell_cache_t &entry_cell_cache = entry.get_entry_cell_cache( preset );
         int x1 = p.x + get_entry_indent( entry );
         int x2 = p.x + std::max( static_cast<int>( reserved_width - get_cells_width() ), 0 );
         int yy = p.y + line;
         const bool selected = active && is_highlighted( entry );
         const int hx_max = p.x + get_width();
         inclusive_rectangle<point> rect = inclusive_rectangle<point>( point( x1, yy ),
                                           point( hx_max - 1, yy ) );
         rect_entry_map.emplace_back( rect,
                                      &entry );
         if( selected && visible_cells() > 1 ) {
             for( int hx = x1; hx < hx_max; ++hx ) {
                 mvwputch( win, point( hx, yy ), h_white, ' ' );
             }
         }
         cata_assert( entry.denial.has_value() );
         const std::string &denial = *entry.denial;
         if( !denial.empty() ) {
             // Determine the width available for the first cell to print, then use that to trim the denial
             const size_t first_cell_width = std::min( get_entry_cell_width( entry, 0 ),
                                             x2 + cells[0].current_width - min_denial_gap );
             const size_t max_denial_width = std::max( static_cast<int>( get_width() - ( min_denial_gap +
                                             first_cell_width ) ), 0 );
             const size_t denial_width = std::min( max_denial_width, static_cast<size_t>( utf8_width( denial,
                                                   true ) ) );
             if( denial_width > 0 ) {
                 /* Need to determine exact point to start printing from the left, since just trimming produces
                  * artifacts on languages with wide characters, and right_print expects only a second column */
                 std::string trimmed = trim_by_length( denial, denial_width );
                 const int x = p.x + get_width() - utf8_width( remove_color_tags( trimmed ) );
                 nc_color temp = c_red;
                 print_colored_text( win, point( x, yy ), temp, c_red,
                                     selected ? hilite_string( colorize( trimmed, c_red ) ) : trimmed );
                 entry.cached_denial_space = denial_width;
             }
         }
         size_t count = denial.empty() ? cells.size() : 1;
         for( size_t cell_index = 0; cell_index < count; ++cell_index ) {
             if( !cells[cell_index].visible() ) {
                 continue; // Don't show empty cells
             }
             if( line != 0 && cell_index != 0 && entry.is_category() ) {
                 break; // Don't show duplicated titles
             }
             x2 += cells[cell_index].current_width;
             std::string text = entry_cell_cache.text[cell_index];
             size_t text_width = utf8_width( text, true );
             size_t text_gap = cell_index > 0 ? std::max( cells[cell_index].gap(), min_cell_gap ) : 0;
             size_t available_width = x2 - x1 - text_gap;
             if( text_width > available_width ) {
                 // See if we can steal some of the needed width from an adjacent cell
                 if( cell_index == 0 && count >= 2 ) {
                     available_width += available_cell_width( entry, 1 );
                 } else if( cell_index > 0 ) {
                     available_width += available_cell_width( entry, cell_index - 1 );
                 }
                 text_width = std::min( text_width, available_width );
             }
             if( text_width > 0 ) {
                 const int text_x = cell_index == 0 ? x1 : x2 -
                                    text_width; // Align either to the left or to the right
                 const std::string &hl_option = get_option<std::string>( "INVENTORY_HIGHLIGHT" );
                 if( cell_index == 0 && entry.chevron ) {
                     bool const hide_override = hide_entries_override && entry.any_item()->is_container();
                     nc_color const col = entry.is_collation_header() ? c_light_blue : hide_override ?
                                          *hide_entries_override ? c_red : c_green : c_dark_gray;
                     bool const stat = entry.is_collation_entry() ||
                                       !hide_override ? entry.collapsed : *hide_entries_override;
                     trim_and_print( win, point( text_x - 1, yy ), 1, col,
                                     stat ? "" : "" );
                 }
                 if( entry.is_item() && ( selected || !entry.is_selectable() ) ) {
                     trim_and_print( win, point( text_x, yy ), text_width, selected ? h_white : c_dark_gray,
                                     remove_color_tags( text ) );
                 } else if( entry.is_item() && entry.highlight_as_parent ) {
                     if( hl_option == "symbol" ) {
                         trim_and_print( win, point( text_x - 1, yy ), 1, h_white, "<" );
                         trim_and_print( win, point( text_x, yy ), text_width, entry_cell_cache.color, text );
                     } else {
                         trim_and_print( win, point( text_x, yy ), text_width, c_white_white,
                                         remove_color_tags( text ) );
                     }
                     entry.highlight_as_parent = false;
                 } else if( entry.is_item() && entry.highlight_as_child ) {
                     if( hl_option == "symbol" ) {
                         trim_and_print( win, point( text_x - 1, yy ), 1, h_white, ">" );
                         trim_and_print( win, point( text_x, yy ), text_width, entry_cell_cache.color, text );
                     } else {
                         trim_and_print( win, point( text_x, yy ), text_width, c_black_white,
                                         remove_color_tags( text ) );
                     }
                     entry.highlight_as_child = false;
                 } else {
                     trim_and_print( win, point( text_x, yy ), text_width, entry_cell_cache.color, text );
                 }
             }
             x1 = x2;
         }
         if( entry.is_item() ) {
             int xx = p.x;
             if( entry.get_invlet() != '\0' ) {
                 mvwputch( win, point( p.x, yy ), entry.get_invlet_color(), entry.get_invlet() );
             }
             xx += 2;
             if( get_option<bool>( "ITEM_SYMBOLS" ) ) {
                 const nc_color color = entry.any_item()->color();
                 mvwputch( win, point( xx, yy ), color, entry.any_item()->symbol() );
                 xx += 2;
             }
             if( allows_selecting() && activatable() && multiselect ) {
                 if( entry.chosen_count == 0 ) {
                     mvwputch( win, point( xx, yy ), c_dark_gray, '-' );
                 } else if( entry.chosen_count >= entry.get_available_count() ) {
                     mvwputch( win, point( xx, yy ), c_light_green, '+' );
                 } else {
                     mvwputch( win, point( xx, yy ), c_light_green, '#' );
                 }
             }
         }
     }
     if( pages_count() > 1 ) {
         mvwprintw( win, p + point( 0, height - 1 ), _( "Page %d/%d" ), page_index() + 1, pages_count() );
     }
 }
References _, active, inventory_entry::any_item(), c_black_white, c_dark_gray, c_green, c_light_blue, c_light_green, c_red, c_white_white, inventory_entry::cached_denial_space, cata_assert, inventory_selector_preset::cells, inventory_entry::chevron, inventory_entry::chosen_count, inventory_entry::collapsed, inventory_entry::entry_cell_cache_t::color, item::color(), color(), colorize(), inventory_entry::denial, inventory_entry::get_available_count(), inventory_entry::get_entry_cell_cache(), inventory_entry::get_invlet(), inventory_entry::get_invlet_color(), h_white, inventory_entry::highlight_as_child, inventory_entry::highlight_as_parent, hilite_string(), inventory_entry::is_category(), inventory_entry::is_collation_entry(), inventory_entry::is_collation_header(), item::is_container(), inventory_entry::is_item(), inventory_entry::is_selectable(), line, max(), min(), min_cell_gap, min_denial_gap, catacurses::mvwprintw(), mvwputch(), point, print_colored_text(), remove_color_tags(), item::symbol(), temp, inventory_entry::entry_cell_cache_t::text, trim_and_print(), trim_by_length(), utf8_width(), point::x, and point::y.
Referenced by inventory_selector::draw_columns().
empty()
bool inventory_column::empty () const inline
Definition at line 344 of file inventory_ui.h.
{
             return entries.empty();
         }
References entries.
Referenced by inventory_selector::rearrange_columns(), and visible().
expand_to_fit()
void inventory_column::expand_to_fit (inventory_entry & entry, bool with_denial = true)
Expands the column to fit the new entry.
Definition at line 1077 of file inventory_ui.cpp.
 {
     if( !entry ) {
         return;
     }
     entry.cache_denial( preset );
     cata_assert( entry.denial.has_value() );
     const std::string &denial = *entry.denial;
     for( size_t i = 0, num = with_denial && denial.empty() ? cells.size() : 1; i < num; ++i ) {
         auto &cell = cells[i];
         cell.real_width = std::max( cell.real_width, get_entry_cell_width( entry, i ) );
         // Don't reveal the cell for headers and stubs
         if( cell.visible() || ( entry.is_item() && !preset.is_stub_cell( entry, i ) ) ) {
             const size_t cell_gap = i > 0 ? normal_cell_gap : 0;
             cell.current_width = std::max( cell.current_width, cell_gap + cell.real_width );
         }
     }
     if( with_denial && !denial.empty() ) {
         reserved_width = std::max( get_entry_cell_width( entry, 0 ) + min_denial_gap + utf8_width( denial,
                                    true ),
                                    reserved_width );
     }
 }
References inventory_entry::cache_denial(), cata_assert, inventory_selector_preset::cells, inventory_entry::denial, inventory_entry::is_item(), max(), min_denial_gap, normal_cell_gap, and utf8_width().
Referenced by selection_column::prepare_paging(), and selection_column::reset_width().
find_by_invlet()
inventory_entry * inventory_column::find_by_invlet (int invlet) const
Definition at line 634 of file inventory_ui.cpp.
 {
     for( const inventory_entry &elem : entries ) {
         if( elem.is_item() && elem.get_invlet() == invlet ) {
             return const_cast<inventory_entry *>( &elem );
         }
     }
     return nullptr;
 }
References entries.
find_by_location()
inventory_entry * inventory_column::find_by_location (item_location const & loc, bool hidden = false) const
Definition at line 644 of file inventory_ui.cpp.
 {
     std::vector<inventory_entry> const &ents = hidden ? entries_hidden : entries;
     for( const inventory_entry &elem : ents ) {
         if( elem.is_item() ) {
             for( const item_location &it : elem.locations ) {
                 if( it == loc ) {
                     return const_cast<inventory_entry *>( &elem );
                 }
             }
         }
     }
     return nullptr;
 }
References entries, and entries_hidden.
Referenced by inventory_selector::get_collation_next(), and inventory_selector::highlight().
get_all_selected()
std::vector< inventory_entry * > inventory_column::get_all_selected () const
Definition at line 1173 of file inventory_ui.cpp.
 {
     const auto filter_to_selected = [&]( const inventory_entry & entry ) {
         return is_selected( entry );
     };
     return get_entries( filter_to_selected );
 }
Referenced by inventory_multiselector::toggle_entries().
get_cells_width()
size_t inventory_column::get_cells_width () const protected
Sum of the cell widths.
Definition at line 976 of file inventory_ui.cpp.
 {
     return std::accumulate( cells.begin(), cells.end(), static_cast<size_t>( 0 ), []( size_t lhs,
     const cell_t &cell ) {
         return lhs + cell.current_width;
     } );
 }
References inventory_selector_preset::cells.
Referenced by get_width().
get_entries()
inventory_column::get_entries_t inventory_column::get_entries (const ffilter_t & filter_func, bool include_hidden = false) const
Definition at line 1193 of file inventory_ui.cpp.
 {
     get_entries_t res;
     if( allows_selecting() ) {
         _get_entries( &res, entries, filter_func );
         if( include_hidden ) {
             _get_entries( &res, entries_hidden, filter_func );
         }
     }
     return res;
 }
Referenced by inventory_selector::_categorize(), inventory_selector::_uncategorize(), inventory_selector::toggle_categorize_contained(), and inventory_multiselector::toggle_entries().
get_entry_cell_width()
size_t inventory_column::get_entry_cell_width (const inventory_entry & entry, size_t cell_index) const protected
Overall cell width.
If corresponding cell is not empty (its width is greater than zero), then a value returned by inventory_column::get_entry_indent() is added to the result.
Definition at line 964 of file inventory_ui.cpp.
 {
     size_t res = utf8_width( entry.get_entry_cell_cache( preset ).text[cell_index], true );
     if( cell_index == 0 ) {
         res += get_entry_indent( entry );
     }
     return res;
 }
References inventory_entry::get_entry_cell_cache(), inventory_entry::entry_cell_cache_t::text, and utf8_width().
get_entry_indent()
size_t inventory_column::get_entry_indent (const inventory_entry & entry) const protected
Indentation of the entry.
Parameters
entry The entry to check
Returns
Either left indent when it's zero, or a gap between cells.
Definition at line 1575 of file inventory_ui.cpp.
 {
     if( !entry.is_item() ) {
         return 0;
     }
     size_t res = 2;
     if( get_option<bool>( "ITEM_SYMBOLS" ) ) {
         res += 2;
     }
     if( allows_selecting() && activatable() && multiselect ) {
         res += 2;
     }
     if( entry.is_item() ) {
         if( collate_entries() && entry.is_collation_entry() ) {
             res += 2;
         }
         if( indent_entries() ) {
             res += entry.indent;
         }
     }
     return res;
 }
References inventory_selector_preset::collate_entries(), inventory_entry::indent, inventory_selector_preset::indent_entries(), inventory_entry::is_collation_entry(), and inventory_entry::is_item().
get_height()
size_t inventory_column::get_height () const
Definition at line 664 of file inventory_ui.cpp.
 {
     return std::min( entries.size(), height );
 }
References entries, height, and min().
get_highlighted() [1/2]
inventory_entry & inventory_column::get_highlighted ()
Definition at line 1167 of file inventory_ui.cpp.
 {
     return const_cast<inventory_entry &>( const_cast<const inventory_column *>
                                           ( this )->get_highlighted() );
 }
get_highlighted() [2/2]
const inventory_entry & inventory_column::get_highlighted () const
Definition at line 1157 of file inventory_ui.cpp.
 {
     if( highlighted_index >= entries.size() || !entries[highlighted_index].is_item() ) {
         // clang complains if we use the default constructor here
         static const inventory_entry dummy( nullptr );
         return dummy;
     }
     return entries[highlighted_index];
 }
Referenced by inventory_pick_selector::execute(), ammo_inventory_selector::execute(), unload_selector::execute(), inventory_examiner::execute(), inventory_selector::get_collation_next(), inventory_selector::get_highlighted(), inventory_selector::highlight(), inventory_selector::on_input(), inventory_multiselector::on_input(), inventory_multiselector::toggle_entries(), pickup_selector::wear(), and pickup_selector::wield().
get_highlighted_index()
size_t inventory_column::get_highlighted_index () const inline
Definition at line 418 of file inventory_ui.h.
{
             return highlighted_index;
         }
References highlighted_index.
Referenced by inventory_selector::get_highlighted_position(), and inventory_selector::prepare_layout().
get_width()
size_t inventory_column::get_width () const
Definition at line 659 of file inventory_ui.cpp.
 {
     return std::max( get_cells_width(), reserved_width );
 }
References get_cells_width(), max(), and reserved_width.
has_available_choices()
bool inventory_column::has_available_choices () const
Definition at line 1129 of file inventory_ui.cpp.
 {
     if( !allows_selecting() || !activatable() ) {
         return false;
     }
     return std::any_of( entries.begin(), entries.end(), []( inventory_entry const & e ) {
         return e.is_item() && e.enabled;
     } );
 }
highlight() [1/2]
bool inventory_column::highlight (const item_location & loc, bool front_only = false)
Highlights the specified location.
Definition at line 1560 of file inventory_ui.cpp.
 {
     for( size_t index = 0; index < entries.size(); ++index ) {
         inventory_entry &ent = entries[index];
         if( ent.is_item() &&
             ( ( !front_only && std::find( ent.locations.begin(), ent.locations.end(), loc ) !=
                 ent.locations.end() ) ||
               ( !ent.is_collation_header() && ent.locations.front() == loc ) ) ) {
             highlight( index, scroll_direction::FORWARD );
             return true;
         }
     }
     return false;
 }
References FORWARD, inventory_entry::is_collation_header(), inventory_entry::is_item(), and inventory_entry::locations.
Referenced by inventory_selector::highlight(), inventory_selector::highlight_position(), inventory_selector::prepare_layout(), and selection_column::prepare_paging().
highlight() [2/2]
void inventory_column::highlight (size_t new_index, scroll_direction dir)
Change the highlight.
Parameters
new_index Index of the entry to highlight.
dir If the entry is not highlightable, move in the specified direction
Definition at line 883 of file inventory_ui.cpp.
 {
     if( new_index < entries.size() ) {
         if( !entries[new_index].is_highlightable( skip_unselectable ) ) {
             new_index = next_highlightable_index( new_index, dir );
         }
         highlighted_index = new_index;
         page_offset = ( new_index == static_cast<size_t>( -1 ) ) ?
                       0 : highlighted_index - highlighted_index % entries_per_page;
     }
 }
indent_entries()
bool inventory_column::indent_entries () const inline
Definition at line 465 of file inventory_ui.h.
{
             if( indent_entries_override ) {
                 return *indent_entries_override;
             } else {
                 return preset.indent_entries();
             }
         }
References inventory_selector_preset::indent_entries(), indent_entries_override, and preset.
Referenced by inventory_selector::rearrange_columns().
indented_sort_compare()
bool inventory_column::indented_sort_compare (inventory_entry const & lhs, inventory_entry const & rhs) protected
Definition at line 1356 of file inventory_ui.cpp.
 {
     // place children below all parents
     parent_path_t const path_lhs = path_to_top( lhs, preset );
     parent_path_t const path_rhs = path_to_top( rhs, preset );
     parent_path_t::size_type const common_depth = std::min( path_lhs.size(), path_rhs.size() );
     parent_path_t::size_type li = path_lhs.size() - common_depth;
     parent_path_t::size_type ri = path_rhs.size() - common_depth;
     item_location p_lhs = path_lhs[li];
     item_location p_rhs = path_rhs[ri];
     if( p_lhs == p_rhs ) {
         return path_lhs.size() < path_rhs.size();
     }
     // otherwise sort the entries below their lowest common ancestor
     while( li < path_lhs.size() && path_lhs[li] != path_rhs[ri] ) {
         p_lhs = path_lhs[li++];
         p_rhs = path_rhs[ri++];
     }
     inventory_entry ep_lhs( { p_lhs }, nullptr, true, 0, lhs.generation );
     inventory_entry ep_rhs( { p_rhs }, nullptr, true, 0, rhs.generation );
     ep_lhs.update_cache();
     ep_rhs.update_cache();
     return sort_compare( ep_lhs, ep_rhs );
 }
References inventory_entry::generation, min(), anonymous_namespace{inventory_ui.cpp}::path_to_top(), inventory_selector_preset::sort_compare(), and inventory_entry::update_cache().
invalidate_paging()
void inventory_column::invalidate_paging () inline
Definition at line 485 of file inventory_ui.h.
{
             paging_is_valid = false;
         }
References paging_is_valid.
Referenced by inventory_selector::_categorize(), and inventory_selector::_uncategorize().
is_highlighted()
bool inventory_column::is_highlighted (const inventory_entry & entry) const
Definition at line 1145 of file inventory_ui.cpp.
 {
     return entry == get_highlighted() || ( multiselect && is_selected_by_category( entry ) );
 }
is_selected()
bool inventory_column::is_selected (const inventory_entry & entry) const
Definition at line 1139 of file inventory_ui.cpp.
 {
     return ( entry.is_selectable() && entry == get_highlighted() ) || ( multiselect &&
             is_selected_by_category( entry ) );
 }
References inventory_entry::is_selectable().
is_selected_by_category()
bool inventory_column::is_selected_by_category (const inventory_entry & entry) const
Does this entry belong to the selected category? When navigation_mode::ITEM is used it's equivalent to is_selected().
Definition at line 1150 of file inventory_ui.cpp.
 {
     return entry.is_selectable() && mode == navigation_mode::CATEGORY
            && entry.get_category_ptr() == get_highlighted().get_category_ptr()
            && page_of( entry ) == page_index();
 }
References CATEGORY, inventory_entry::get_category_ptr(), and inventory_entry::is_selectable().
move_entries_to()
void inventory_column::move_entries_to (inventory_column & dest)
Definition at line 1323 of file inventory_ui.cpp.
 {
     std::move( entries.begin(), entries.end(), std::back_inserter( dest.entries ) );
     std::move( entries_hidden.begin(), entries_hidden.end(),
                std::back_inserter( dest.entries_hidden ) );
     dest.paging_is_valid = false;
     clear();
 }
References clear, entries, entries_hidden, and paging_is_valid.
Referenced by inventory_selector::_add_map_items(), inventory_selector::add_entry_rec(), inventory_selector::rearrange_columns(), and inventory_selector::toggle_categorize_contained().
move_selection()
void inventory_column::move_selection (scroll_direction dir) protected
Move the selection.
Definition at line 920 of file inventory_ui.cpp.
 {
     size_t index = highlighted_index;
     do {
         index = next_highlightable_index( index, dir );
     } while( index != highlighted_index && is_selected_by_category( entries[index] ) );
     highlight( index, dir );
 }
move_selection_page()
void inventory_column::move_selection_page (scroll_direction dir) protected
Definition at line 931 of file inventory_ui.cpp.
 {
     size_t index = highlighted_index;
     do {
         const size_t next_index = next_highlightable_index( index, dir );
         const bool flipped = next_index == highlighted_index ||
                              ( next_index > highlighted_index ) != ( static_cast<int>( dir ) > 0 );
         if( flipped && page_of( next_index ) == page_index() ) {
             break; // If flipped and still on the same page - no need to flip
         }
         index = next_index;
     } while( page_of( next_highlightable_index( index, dir ) ) == page_index() );
     highlight( index, dir );
 }
next_highlightable_index()
size_t inventory_column::next_highlightable_index (size_t index, scroll_direction dir) const protected
Definition at line 896 of file inventory_ui.cpp.
 {
     if( entries.empty() ) {
         return index;
     }
     // limit index to the space of the size of entries
     index = index % entries.size();
     size_t new_index = index;
     do {
         // 'new_index' incremented by 'dir' using division remainder (number of entries) to loop over the entries.
         // Negative step '-k' (backwards) is equivalent to '-k + N' (forward), where:
         //     N = entries.size()  - number of elements,
         //     k = |step|          - absolute step (k <= N).
         new_index = ( new_index + static_cast<int>( dir ) + entries.size() ) % entries.size();
     } while( new_index != index &&
              !entries[new_index].is_highlightable( skip_unselectable ) );
     if( !entries[new_index].is_highlightable( skip_unselectable ) ) {
         return static_cast<size_t>( -1 );
     }
     return new_index;
 }
on_activate()
virtual void inventory_column::on_activate () inline virtual
The column has been activated.
Definition at line 450 of file inventory_ui.h.
{
             active = true;
         }
References active.
Referenced by inventory_selector::append_column(), trade_selector::execute(), and inventory_selector::set_active_column().
on_change()
void inventory_column::on_change (const inventory_entry & entry) virtual
The entry has been changed.
Reimplemented in selection_column.
Definition at line 1277 of file inventory_ui.cpp.
 {
     // stub
 }
on_deactivate()
virtual void inventory_column::on_deactivate () inline virtual
The column has been deactivated.
Definition at line 454 of file inventory_ui.h.
{
             active = false;
         }
References active.
Referenced by trade_selector::execute(), and inventory_selector::set_active_column().
on_input()
void inventory_column::on_input (const inventory_input & input) virtual
Event handlers.
Definition at line 1241 of file inventory_ui.cpp.
 {
     if( !empty() && active ) {
         if( input.action == "DOWN" ) {
             move_selection( scroll_direction::FORWARD );
         } else if( input.action == "UP" ) {
             move_selection( scroll_direction::BACKWARD );
         } else if( input.action == "PAGE_DOWN" ) {
             move_selection_page( scroll_direction::FORWARD );
         } else if( input.action == "PAGE_UP" ) {
             move_selection_page( scroll_direction::BACKWARD );
         } else if( input.action == "SCROLL_DOWN" ) {
             scroll_selection_page( scroll_direction::FORWARD );
         } else if( input.action == "SCROLL_UP" ) {
             scroll_selection_page( scroll_direction::BACKWARD );
         } else if( input.action == "HOME" ) {
             highlight( 0, scroll_direction::FORWARD );
         } else if( input.action == "END" ) {
             highlight( entries.size() - 1, scroll_direction::BACKWARD );
         } else if( input.action == "TOGGLE_FAVORITE" ) {
             inventory_entry &selected = get_highlighted();
             set_stack_favorite( selected, !selected.any_item()->is_favorite );
         } else if( input.action == "SHOW_HIDE_CONTENTS" ) {
             inventory_entry &selected = get_highlighted();
             selected.collapsed ? set_collapsed( selected, false ) : set_collapsed( selected, true );
         }
     }
     if( input.action == "TOGGLE_FAVORITE" ) {
         // Favoriting items in one column may change item names in another column
         // if that column contains an item that contains the favorited item. So
         // we invalidate every column on TOGGLE_FAVORITE action.
         paging_is_valid = false;
     }
 }
References inventory_input::action, active, inventory_entry::any_item(), BACKWARD, inventory_entry::collapsed, FORWARD, and item::is_favorite.
on_mode_change()
virtual void inventory_column::on_mode_change (navigation_mode mode) inline virtual
Selection mode has been changed.
Reimplemented in selection_column.
Definition at line 458 of file inventory_ui.h.
{
             this->mode = mode;
         }
References mode.
Referenced by inventory_selector::append_column().
order_by_parent()
void inventory_column::order_by_parent ()
page_index()
size_t inventory_column::page_index () const inline
Definition at line 366 of file inventory_ui.h.
{
             return page_of( page_offset );
         }
References page_of(), and page_offset.
page_of() [1/2]
size_t inventory_column::page_of (const inventory_entry & entry) const protected
Definition at line 1124 of file inventory_ui.cpp.
 {
     return page_of( std::distance( entries.begin(), std::find( entries.begin(), entries.end(),
                                    entry ) ) );
 }
page_of() [2/2]
size_t inventory_column::page_of (size_t index) const protected
Definition at line 1117 of file inventory_ui.cpp.
 {
     cata_assert( entries_per_page ); // To appease static analysis
     // NOLINTNEXTLINE(clang-analyzer-core.DivideZero)
     return index / entries_per_page;
 }
References cata_assert.
Referenced by page_index(), and pages_count().
pages_count()
size_t inventory_column::pages_count () const inline
Definition at line 370 of file inventory_ui.h.
{
             return page_of( entries.size() + entries_per_page - 1 );
         }
References entries, entries_per_page, and page_of().
Referenced by selection_column::activatable().
prepare_paging()
void inventory_column::prepare_paging (const std::string & filter = "") virtual
Reorder entries, repopulate titles, adjust to the new height.
Reimplemented in selection_column.
Definition at line 1474 of file inventory_ui.cpp.
 {
     if( paging_is_valid ) {
         return;
     }
     const auto filter_fn = filter_from_string<inventory_entry>(
     filter, [this]( const std::string & filter ) {
         return preset.get_filter( filter );
     } );
     const auto is_visible = [&filter_fn, &filter, this]( inventory_entry const & it ) {
         return it.is_item() &&
                ( filter_fn( it ) &&
                  ( ( !filter.empty() && !it.is_collation_entry() ) || !it.is_hidden( hide_entries_override ) ) );
     };
     const auto is_not_visible = [&is_visible, this]( inventory_entry const & it ) {
         it.cache_denial( preset ); // do it here since we're looping over all visible entries anyway
         return !is_visible( it );
     };
     // restore entries revealed by SHOW_HIDE_CONTENTS or filter
     move_if( entries_hidden, entries, is_visible );
     // remove entries hidden by SHOW_HIDE_CONTENTS
     move_if( entries, entries_hidden, is_not_visible );
     // Then sort them with respect to categories
     std::stable_sort( entries.begin(), entries.end(),
     [this]( const inventory_entry & lhs, const inventory_entry & rhs ) {
         if( *lhs.get_category_ptr() == *rhs.get_category_ptr() ) {
             if( _collated ) {
                 return collated_sort_compare( lhs, rhs );
             }
             if( indent_entries() ) {
                 return indented_sort_compare( lhs, rhs );
             }
             return sort_compare( lhs, rhs );
         }
         return preset.cat_sort_compare( lhs, rhs );
     } );
     if( !_collated && collate_entries() ) {
         collate();
     }
     // Recover categories
     const item_category *current_category = nullptr;
     for( auto iter = entries.begin(); iter != entries.end(); ++iter ) {
         if( iter->get_category_ptr() == current_category ) {
             continue;
         }
         current_category = iter->get_category_ptr();
         iter = entries.insert( iter, inventory_entry( current_category ) );
     }
     // Determine the new height.
     entries_per_page = height;
     if( entries.size() > entries_per_page ) {
         entries_per_page -= 1;  // Make room for the page number.
         for( size_t i = entries_per_page - 1; i < entries.size(); i += entries_per_page ) {
             auto iter = std::next( entries.begin(), i );
             if( iter->is_category() ) {
                 // The last item on the page must not be a category.
                 entries.insert( iter, inventory_entry() );
             } else {
                 // The first item on the next page must be a category.
                 iter = std::next( iter );
                 if( iter != entries.end() && iter->is_item() ) {
                     entries.insert( iter, inventory_entry( iter->get_category_ptr() ) );
                 }
             }
         }
     }
     paging_is_valid = true;
     // Select the uppermost possible entry
     const size_t ind = highlighted_index >= entries.size() ? 0 : highlighted_index;
     highlight( ind, ind ? scroll_direction::BACKWARD : scroll_direction::FORWARD );
 }
References filter, and anonymous_namespace{inventory_ui.cpp}::move_if().
Referenced by selection_column::prepare_paging().
reassign_custom_invlets() [1/2]
int inventory_column::reassign_custom_invlets (const Character & p, int min_invlet, int max_invlet)
Returns next custom inventory letter.
Definition at line 1600 of file inventory_ui.cpp.
 {
     int cur_invlet = min_invlet;
     for( inventory_entry &elem : entries ) {
         // Only items on map/in vehicles: those that the player does not possess.
         if( elem.is_selectable() && !p.has_item( *elem.any_item() ) ) {
             elem.custom_invlet = cur_invlet <= max_invlet ? cur_invlet++ : '\0';
         }
     }
     return cur_invlet;
 }
References visitable::has_item().
reassign_custom_invlets() [2/2]
int inventory_column::reassign_custom_invlets (int cur_idx, std::string_view pickup_chars)
Definition at line 1612 of file inventory_ui.cpp.
 {
     for( inventory_entry &elem : entries ) {
         // Only items on map/in vehicles: those that the player does not possess.
         if( elem.is_selectable() && elem.any_item()->invlet <= '\0' ) {
             elem.custom_invlet =
                 static_cast<uint8_t>(
                     cur_idx < static_cast<int>( pickup_chars.size() ) ?
                     pickup_chars[cur_idx] : '\0'
                 );
             cur_idx++;
         }
     }
     return cur_idx;
 }
reset_width()
void inventory_column::reset_width (const std::vector< inventory_column * > & all_columns) virtual
Resets width to original (unchanged).
Reimplemented in selection_column.
Definition at line 1106 of file inventory_ui.cpp.
 {
     for( inventory_column::cell_t &elem : cells ) {
         elem = cell_t();
     }
     reserved_width = 0;
     for( inventory_entry &elem : entries ) {
         expand_to_fit( elem );
     }
 }
References inventory_selector_preset::cells.
Referenced by inventory_selector::rearrange_columns(), and selection_column::reset_width().
scroll_selection_page()
void inventory_column::scroll_selection_page (scroll_direction dir) protected
Definition at line 950 of file inventory_ui.cpp.
 {
     size_t index = highlighted_index;
     while( page_of( index = next_highlightable_index( index, dir ) ) == page_index() ) {
         if( index == highlighted_index && page_of( index ) == page_index() ) {
             break; // If flipped and still on the same page - no need to flip
         }
     }
     highlight( index, dir );
 }
set_collapsed()
void inventory_column::set_collapsed (inventory_entry & entry, bool collapse)
Definition at line 1217 of file inventory_ui.cpp.
 {
     bool collapsed = false;
     if( entry.is_collation_header() ) {
         entry.collation_meta->collapsed = collapse;
         collapsed = true;
     } else {
         std::vector<item_location> &locations = entry.locations;
         for( item_location &loc : locations ) {
             for( item_pocket *pocket : loc->get_all_standard_pockets() ) {
                 pocket->settings.set_collapse( collapse );
                 collapsed = true;
             }
         }
     }
     if( collapsed ) {
         entry.collapsed = collapse;
         paging_is_valid = false;
         entry.make_entry_cell_cache( preset );
     }
 }
References inventory_entry::collapsed, inventory_entry::collation_meta, inventory_entry::is_collation_header(), inventory_entry::locations, anonymous_namespace{overmap_location.cpp}::locations, and inventory_entry::make_entry_cell_cache().
Referenced by inventory_selector::highlight().
set_filter()
void inventory_column::set_filter (const std::string & filter) virtual
Reimplemented in selection_column.
Definition at line 984 of file inventory_ui.cpp.
 {
     paging_is_valid = false;
 }
Referenced by selection_column::set_filter().
set_height()
void inventory_column::set_height (size_t new_height)
Definition at line 1064 of file inventory_ui.cpp.
 {
     if( height != new_height ) {
         if( new_height <= 1 ) {
             debugmsg( "Unable to assign height <= 1 (was %zd).", new_height );
             return;
         }
         height = new_height;
         entries_per_page = new_height;
         paging_is_valid = false;
     }
 }
References debugmsg.
set_indent_entries_override()
void inventory_column::set_indent_entries_override (bool entry_override) inline
Definition at line 477 of file inventory_ui.h.
{
             indent_entries_override = entry_override;
         }
References indent_entries_override.
Referenced by inventory_selector::_add_map_items(), inventory_selector::_categorize(), inventory_selector::add_character_items(), and inventory_selector::rearrange_columns().
set_multiselect()
void inventory_column::set_multiselect (bool multiselect) inline
Definition at line 422 of file inventory_ui.h.
{
             this->multiselect = multiselect;
         }
References multiselect.
set_stack_favorite()
void inventory_column::set_stack_favorite (inventory_entry & entry, bool favorite)
Definition at line 1208 of file inventory_ui.cpp.
 {
     for( item_location &loc : entry.locations ) {
         loc->set_favorite( favorite );
     }
     entry.make_entry_cell_cache( preset );
 }
References inventory_entry::locations, inventory_entry::make_entry_cell_cache(), and item::set_favorite().
set_visibility()
void inventory_column::set_visibility (bool visibility) inline
Definition at line 426 of file inventory_ui.h.
{
             this->visibility = visibility;
         }
References visibility.
set_width()
void inventory_column::set_width (size_t new_width)
Definition at line 1030 of file inventory_ui.cpp.
 {
     int width_gap = get_width() - new_width;
     // Now adjust the width if we must
     while( width_gap != 0 ) {
         const int step = width_gap > 0 ? -1 : 1;
         // Should return true when lhs < rhs
         const auto cmp_for_expansion = []( const cell_t &lhs, const cell_t &rhs ) {
             return lhs.visible() && lhs.gap() < rhs.gap();
         };
         // Should return true when lhs < rhs
         const auto cmp_for_shrinking = []( const cell_t &lhs, const cell_t &rhs ) {
             if( !lhs.visible() ) {
                 return false;
             }
             if( rhs.gap() <= min_cell_gap ) {
                 return lhs.current_width < rhs.current_width;
             } else {
                 return lhs.gap() < rhs.gap();
             }
         };
         const auto &cell = step > 0
                            ? std::min_element( cells.begin(), cells.end(), cmp_for_expansion )
                            : std::max_element( cells.begin(), cells.end(), cmp_for_shrinking );
         if( cell == cells.end() || !cell->visible() ) {
             break; // This is highly unlikely to happen, but just in case
         }
         cell->current_width += step;
         width_gap += step;
     }
     reserved_width = new_width;
 }
References inventory_selector_preset::cells, inventory_column::cell_t::current_width, inventory_column::cell_t::gap(), min_cell_gap, and inventory_column::cell_t::visible().
sort_compare()
bool inventory_column::sort_compare (inventory_entry const & lhs, inventory_entry const & rhs) protected
Definition at line 1332 of file inventory_ui.cpp.
 {
     if( lhs.is_selectable() != rhs.is_selectable() ) {
         return lhs.is_selectable(); // Disabled items always go last
     }
     Character &player_character = get_player_character();
     // Place favorite items and items with an assigned inventory letter first,
     // since the player cared enough to assign them
     const bool left_has_invlet =
         player_character.inv->assigned_invlet.count( lhs.any_item()->invlet ) != 0;
     const bool right_has_invlet =
         player_character.inv->assigned_invlet.count( rhs.any_item()->invlet ) != 0;
     if( left_has_invlet != right_has_invlet ) {
         return left_has_invlet;
     }
     const bool left_fav = lhs.any_item()->is_favorite;
     const bool right_fav = rhs.any_item()->is_favorite;
     if( left_fav != right_fav ) {
         return left_fav;
     }
     return preset.sort_compare( lhs, rhs );
 }
References inventory_entry::any_item(), get_player_character(), Character::inv, item::invlet, item::is_favorite, and inventory_entry::is_selectable().
toggle_skip_unselectable()
void inventory_column::toggle_skip_unselectable (bool skip)
Toggle being able to highlight unselectable entries.
Definition at line 669 of file inventory_ui.cpp.
 {
     skip_unselectable = skip;
 }
References skip_unselectable.
uncollate()
void inventory_column::uncollate ()
Definition at line 1465 of file inventory_ui.cpp.
 {
     if( _collated ) {
         _reset_collation( entries );
         _reset_collation( entries_hidden );
         _collated = false;
     }
 }
Referenced by inventory_selector::_categorize(), and inventory_selector::_uncategorize().
visible()
bool inventory_column::visible () const inline
Is this column visible?
Definition at line 354 of file inventory_ui.h.
{
             return !empty() && visibility && preset.get_cells_count() > 0;
         }
References empty(), inventory_selector_preset::get_cells_count(), preset, and visibility.
Referenced by inventory_selector::highlight().
visible_cells()
size_t inventory_column::visible_cells () const private
Returns
Number of visible cells
Definition at line 1792 of file inventory_ui.cpp.
 {
     return std::count_if( cells.begin(), cells.end(), []( const cell_t &elem ) {
         return elem.visible();
     } );
 }
References inventory_selector_preset::cells.
Member Data Documentation
_collated
bool inventory_column::_collated = false private
Definition at line 570 of file inventory_ui.h.
active
bool inventory_column::active = false protected
Definition at line 533 of file inventory_ui.h.
Referenced by on_activate(), and on_deactivate().
cells
std::vector<cell_t> inventory_column::cells private
Definition at line 559 of file inventory_ui.h.
Referenced by inventory_column().
entries
entries_t inventory_column::entries protected
Definition at line 530 of file inventory_ui.h.
Referenced by activatable(), empty(), find_by_invlet(), find_by_location(), get_height(), move_entries_to(), selection_column::on_change(), pages_count(), and selection_column::prepare_paging().
entries_hidden
entries_t inventory_column::entries_hidden protected
Definition at line 531 of file inventory_ui.h.
Referenced by find_by_location(), and move_entries_to().
entries_per_page
size_t inventory_column::entries_per_page = std::numeric_limits<size_t>::max() protected
Definition at line 540 of file inventory_ui.h.
Referenced by pages_count().
height
size_t inventory_column::height = std::numeric_limits<size_t>::max() protected
Definition at line 541 of file inventory_ui.h.
Referenced by get_height().
hide_entries_override
std::optional<bool> inventory_column::hide_entries_override = std::nullopt protected
Definition at line 543 of file inventory_ui.h.
Referenced by cycle_hide_override(), inventory_column(), and selection_column::selection_column().
highlighted_index
size_t inventory_column::highlighted_index = std::numeric_limits<size_t>::max() protected
Definition at line 538 of file inventory_ui.h.
Referenced by get_highlighted_index().
indent_entries_override
std::optional<bool> inventory_column::indent_entries_override = std::nullopt private
Definition at line 561 of file inventory_ui.h.
Referenced by clear_indent_entries_override(), indent_entries(), and set_indent_entries_override().
mode
navigation_mode inventory_column::mode = navigation_mode::ITEM protected
Definition at line 532 of file inventory_ui.h.
Referenced by on_mode_change().
multiselect
bool inventory_column::multiselect = false protected
Definition at line 534 of file inventory_ui.h.
Referenced by set_multiselect().
page_offset
size_t inventory_column::page_offset = 0 protected
Definition at line 539 of file inventory_ui.h.
Referenced by page_index().
paging_is_valid
bool inventory_column::paging_is_valid = false protected
Definition at line 535 of file inventory_ui.h.
Referenced by invalidate_paging(), move_entries_to(), and selection_column::on_change().
preset
const inventory_selector_preset& inventory_column::preset protected
Definition at line 527 of file inventory_ui.h.
Referenced by collate_entries(), indent_entries(), inventory_column(), selection_column::on_change(), and visible().
reserved_width
size_t inventory_column::reserved_width = 0 protected
Definition at line 542 of file inventory_ui.h.
Referenced by get_width().
skip_unselectable
bool inventory_column::skip_unselectable = false private
Definition at line 569 of file inventory_ui.h.
Referenced by toggle_skip_unselectable().
visibility
bool inventory_column::visibility = true protected
Definition at line 536 of file inventory_ui.h.
Referenced by set_visibility(), and visible().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp