Cataclysm DDA: advanced_inventory_pagination Class Reference
advanced_inventory_pagination Class Reference
This class determines the page and line at which an item appears in the AIM.
#include <advanced_inv_pagination.h>
Public Member Functions
advanced_inventory_pagination (int linesPerPage, const advanced_inventory_pane &pane)
void reset_page ()
Reset pagination state to the start of the current page, so it can be printed.
bool new_category (const item_category *cat) const
Returns true if printing an item with the category requires a category header.
bool step (int index)
Step the pagination state forward for the item with this index.
Public Attributes
int line
int page
const item_category * last_category
Private Member Functions
int lines_needed (int index)
Private Attributes
const int linesPerPage
const advanced_inventory_pane & pane
Detailed Description
This class determines the page and line at which an item appears in the AIM.
Definition at line 11 of file advanced_inv_pagination.h.
Constructor & Destructor Documentation
advanced_inventory_pagination()
advanced_inventory_pagination::advanced_inventory_pagination (int linesPerPage, const advanced_inventory_pane & pane) inline
Definition at line 21 of file advanced_inv_pagination.h.
             : linesPerPage( linesPerPage ), pane( pane ), line( 0 ), page( 0 ), last_category( nullptr ) { }
Member Function Documentation
lines_needed()
int advanced_inventory_pagination::lines_needed (int index) private
Definition at line 22 of file advanced_inv_pagination.cpp.
 {
     if( pane.sortby == SORTBY_CATEGORY && new_category( pane.items[index].cat ) ) {
         return 2;
     }
     return 1;
 }
References advanced_inventory_pane::items, new_category(), pane, advanced_inventory_pane::sortby, and SORTBY_CATEGORY.
Referenced by step().
new_category()
bool advanced_inventory_pagination::new_category (const item_category * cat) const
Returns true if printing an item with the category requires a category header.
Definition at line 17 of file advanced_inv_pagination.cpp.
 {
     return last_category != cat;
 }
References last_category.
Referenced by lines_needed(), and advanced_inventory::print_items().
reset_page()
void advanced_inventory_pagination::reset_page ()
Reset pagination state to the start of the current page, so it can be printed.
Definition at line 10 of file advanced_inv_pagination.cpp.
 {
     line = 0;
     page = 0;
     last_category = nullptr;
 }
References last_category, line, and page.
Referenced by advanced_inventory::print_items().
step()
bool advanced_inventory_pagination::step (int index)
Step the pagination state forward for the item with this index.
Returns true if printing the item required starting a new page.
Definition at line 30 of file advanced_inv_pagination.cpp.
 {
     // item would overflow page
     if( line + lines_needed( index ) > linesPerPage ) {
         page++;
         line = 0;
         // always reprint category header on next page
         last_category = nullptr;
         // print item on next page
         step( index );
         return true;
     }
     // print on this page
     line += lines_needed( index );
     last_category = pane.items[index].cat;
     return false;
 }
References advanced_inventory_pane::items, last_category, line, lines_needed(), linesPerPage, page, and pane.
Referenced by advanced_inventory::print_items(), advanced_inventory::redraw_pane(), and advanced_inventory_pane::scroll_page().
Member Data Documentation
last_category
const item_category* advanced_inventory_pagination::last_category
Definition at line 20 of file advanced_inv_pagination.h.
Referenced by new_category(), reset_page(), and step().
line
int advanced_inventory_pagination::line
Definition at line 18 of file advanced_inv_pagination.h.
Referenced by advanced_inventory::print_items(), reset_page(), advanced_inventory_pane::scroll_page(), and step().
linesPerPage
const int advanced_inventory_pagination::linesPerPage private
Definition at line 14 of file advanced_inv_pagination.h.
Referenced by step().
page
int advanced_inventory_pagination::page
Definition at line 19 of file advanced_inv_pagination.h.
Referenced by advanced_inventory::redraw_pane(), reset_page(), advanced_inventory_pane::scroll_page(), and step().
pane
const advanced_inventory_pane& advanced_inventory_pagination::pane private
Definition at line 15 of file advanced_inv_pagination.h.
Referenced by lines_needed(), and step().
The documentation for this class was generated from the following files:
src/advanced_inv_pagination.h
src/advanced_inv_pagination.cpp