Cataclysm DDA: item_pricing Class Reference
item_pricing Class Reference
#include <npctrade.h>
Public Member Functions
item_pricing (Character &c, item &it, double v, int count)
item_pricing (item_location &&l, double v, int count)
void set_values (int ip_count)
Public Attributes
item_location loc
double price = 0
bool selected = false
bool is_container = false
int count = 0
int charges = 0
int u_has = 0
int npc_has = 0
int u_charges = 0
int npc_charges = 0
units::mass weight = 0_gram
units::volume vol = 0_ml
Detailed Description
Definition at line 20 of file npctrade.h.
Constructor & Destructor Documentation
item_pricing() [1/2]
item_pricing::item_pricing (Character & c, item & it, double v, int count) inline
Definition at line 23 of file npctrade.h.
                                                                     : loc( c, &it ), price( v ) {
             set_values( count );
         }
References count, and set_values().
item_pricing() [2/2]
item_pricing::item_pricing (item_location && l, double v, int count) inline
Definition at line 27 of file npctrade.h.
                                                                : loc( std::move( l ) ), price( v ) {
             set_values( count );
         }
References count, and set_values().
Member Function Documentation
set_values()
void item_pricing::set_values (int ip_count)
Definition at line 226 of file npctrade.cpp.
 {
     const item *i_p = loc.get_item();
     is_container = i_p->is_container() || i_p->is_ammo_container();
     vol = i_p->volume();
     weight = i_p->weight();
     if( is_container || i_p->count() == 1 ) {
         count = ip_count;
     } else {
         charges = i_p->count();
         if( charges > 0 ) {
             price /= charges;
             vol /= charges;
             weight /= charges;
         } else {
             debugmsg( "item %s has zero or negative charges", i_p->typeId().str() );
         }
     }
 }
References charges, item::count(), count, debugmsg, item_location::get_item(), item::is_ammo_container(), item::is_container(), is_container, loc, price, string_id< T >::str(), item::typeId(), vol, item::volume(), item::weight(), and weight.
Referenced by item_pricing().
Member Data Documentation
charges
int item_pricing::charges = 0
Definition at line 38 of file npctrade.h.
Referenced by set_values().
count
int item_pricing::count = 0
Definition at line 37 of file npctrade.h.
Referenced by item_pricing(), and set_values().
is_container
bool item_pricing::is_container = false
Definition at line 36 of file npctrade.h.
Referenced by set_values().
loc
item_location item_pricing::loc
Definition at line 32 of file npctrade.h.
Referenced by set_values().
npc_charges
int item_pricing::npc_charges = 0
Definition at line 42 of file npctrade.h.
npc_has
int item_pricing::npc_has = 0
Definition at line 40 of file npctrade.h.
price
double item_pricing::price = 0
Definition at line 33 of file npctrade.h.
Referenced by set_values().
selected
bool item_pricing::selected = false
Definition at line 35 of file npctrade.h.
u_charges
int item_pricing::u_charges = 0
Definition at line 41 of file npctrade.h.
u_has
int item_pricing::u_has = 0
Definition at line 39 of file npctrade.h.
vol
units::volume item_pricing::vol = 0_ml
Definition at line 44 of file npctrade.h.
Referenced by set_values().
weight
units::mass item_pricing::weight = 0_gram
Definition at line 43 of file npctrade.h.
Referenced by set_values().
The documentation for this class was generated from the following files:
src/npctrade.h
src/npctrade.cpp