Cataclysm DDA: butchery_requirements Class Reference
butchery_requirements Class Reference
Contains several requirements, each with a speed modifier.
#include <butchery_requirements.h>
Public Member Functions
std::pair< float, requirement_id > get_fastest_requirements (const read_only_visitable &crafting_inv, creature_size size, butcher_type butcher) const
void load (const JsonObject &jo, std::string_view)
bool is_valid () const
Static Public Member Functions
static void load_butchery_req (const JsonObject &jo, const std::string &src)
static const std::vector< butchery_requirements > & get_all ()
static void check_consistency ()
static void reset ()
Public Attributes
bool was_loaded = false
string_id< butchery_requirements > id
std::vector< std::pair< string_id< butchery_requirements >, mod_id > > src
Private Attributes
std::map< float, std::map< creature_size, std::map< butcher_type, requirement_id > > > requirements
Detailed Description
Contains several requirements, each with a speed modifier.
The goal is to iterate from highest speed modifier to lowest to find the first requirement satisfied to butcher a corpse.
Definition at line 24 of file butchery_requirements.h.
Member Function Documentation
check_consistency()
void butchery_requirements::check_consistency () static
Definition at line 84 of file butchery_requirements.cpp.
 {
     for( const butchery_requirements &req : get_all() ) {
         for( const auto &size_req : req.requirements ) {
             if( size_req.second.size() != static_cast<size_t>( creature_size::num_sizes - 1 ) ) {
                 debugmsg( "ERROR: %s needs exactly %d entries to cover all creature sizes",
                           req.id.c_str(), static_cast<int>( creature_size::num_sizes ) - 1 );
             }
             for( const auto &butcher_req : size_req.second ) {
                 if( butcher_req.second.size() != static_cast<size_t>( butcher_type::NUM_TYPES ) ) {
                     debugmsg( "ERROR: %s needs exactly %d entries to cover all butchery types",
                               req.id.c_str(), static_cast<int>( butcher_type::NUM_TYPES ) );
                 }
             }
         }
     }
 }
References debugmsg, get_all(), num_sizes, and NUM_TYPES.
get_all()
const std::vector< butchery_requirements > & butchery_requirements::get_all () static
Definition at line 41 of file butchery_requirements.cpp.
 {
     return butchery_req_factory.get_all();
 }
References anonymous_namespace{butchery_requirements.cpp}::butchery_req_factory.
Referenced by check_consistency().
get_fastest_requirements()
std::pair< float, requirement_id > butchery_requirements::get_fastest_requirements (const read_only_visitable & crafting_inv, creature_size size, butcher_type butcher) const
Definition at line 102 of file butchery_requirements.cpp.
 {
     for( const std::pair<const float, std::map<creature_size, std::map<butcher_type, requirement_id>>>
          &riter : requirements ) {
         if( riter.second.at( size ).at( butcher )->can_make_with_inventory( crafting_inv,
                 is_crafting_component ) ) {
             return std::make_pair( riter.first, riter.second.at( size ).at( butcher ) );
         }
     }
     // we didn't find anything we could "craft", so return the requirement that's the fastest
     const auto first = requirements.rbegin();
     return std::make_pair( first->first, first->second.at( size ).at( butcher ) );
 }
References is_crafting_component(), spell_effect::map(), requirements, and om_direction::size.
is_valid()
bool butchery_requirements::is_valid () const
Definition at line 51 of file butchery_requirements.cpp.
 {
     return butchery_req_factory.is_valid( this->id );
 }
References anonymous_namespace{butchery_requirements.cpp}::butchery_req_factory.
load()
void butchery_requirements::load (const JsonObject & jo, std::string_view)
Definition at line 56 of file butchery_requirements.cpp.
 {
     for( const JsonMember member : jo.get_object( "requirements" ) ) {
         float modifier = std::stof( member.name() );
         requirements.emplace( modifier, std::map<creature_size, std::map<butcher_type, requirement_id>> {} );
         int critter_size = 1;
         for( JsonObject butcher_jo : member.get_array() ) {
             if( critter_size == creature_size::num_sizes ) {
                 debugmsg( "ERROR: %s has too many creature sizes.  must have exactly %d",
                           id.c_str(), creature_size::num_sizes - 1 );
                 break;
             }
             requirements[modifier].emplace( static_cast<creature_size>( critter_size ),
                                             std::map<butcher_type, requirement_id> {} );
             for( int i_butchery_type = 0; i_butchery_type < static_cast<int>( butcher_type::NUM_TYPES );
                  i_butchery_type++ ) {
                 butcher_type converted = static_cast<butcher_type>( i_butchery_type );
                 requirements[modifier][static_cast<creature_size>( critter_size )][converted] =
                     requirement_id( butcher_jo.get_string( io::enum_to_string( converted ) ) );
             }
             critter_size++;
         }
     }
 }
References debugmsg, io::enum_to_string(), JsonObject::get_object(), spell_effect::map(), member, num_sizes, NUM_TYPES, and requirements.
load_butchery_req()
void butchery_requirements::load_butchery_req (const JsonObject & jo, const std::string & src) static
Definition at line 36 of file butchery_requirements.cpp.
 {
     butchery_req_factory.load( jo, src );
 }
References anonymous_namespace{butchery_requirements.cpp}::butchery_req_factory, and src.
Referenced by DynamicDataLoader::initialize().
reset()
void butchery_requirements::reset () static
Definition at line 46 of file butchery_requirements.cpp.
 {
     butchery_req_factory.reset();
 }
References anonymous_namespace{butchery_requirements.cpp}::butchery_req_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
id
string_id<butchery_requirements> butchery_requirements::id
Definition at line 28 of file butchery_requirements.h.
requirements
std::map<float, std::map<creature_size, std::map<butcher_type, requirement_id> > > butchery_requirements::requirements private
Definition at line 43 of file butchery_requirements.h.
Referenced by get_fastest_requirements(), and load().
src
std::vector<std::pair<string_id<butchery_requirements>, mod_id> > butchery_requirements::src
Definition at line 29 of file butchery_requirements.h.
Referenced by load_butchery_req().
was_loaded
bool butchery_requirements::was_loaded = false
Definition at line 27 of file butchery_requirements.h.
The documentation for this class was generated from the following files:
src/butchery_requirements.h
src/butchery_requirements.cpp