Cataclysm DDA: molle_attach_actor Class Reference
molle_attach_actor Class Reference
#include <iuse_actor.h>
Public Member Functions
molle_attach_actor (const std::string &type="attach_molle")
void load (const JsonObject &jo) override
std::optional< int > use (Character *p, item &it, const tripoint &pnt) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
int size
int moves
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 1014 of file iuse_actor.h.
Constructor & Destructor Documentation
molle_attach_actor()
molle_attach_actor::molle_attach_actor (const std::string & type = "attach_molle") inline explicit
Definition at line 1017 of file iuse_actor.h.
 : iuse_actor( type ) {}
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > molle_attach_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 4144 of file iuse_actor.cpp.
 {
     return std::make_unique<molle_attach_actor>( *this );
 }
load()
void molle_attach_actor::load (const JsonObject & jo) override virtual
Implements iuse_actor.
Definition at line 4111 of file iuse_actor.cpp.
 {
     assign( jo, "size", size );
     assign( jo, "moves", moves );
 }
References assign(), and om_direction::size.
use()
std::optional< int > molle_attach_actor::use (Character * p, item & it, const tripoint & pnt) const override virtual
Implements iuse_actor.
Definition at line 4117 of file iuse_actor.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action molle_attach that requires character but no character is present",
                   it.typeId().str() );
         return std::nullopt;
     }
     item_location loc = game_menus::inv::molle_attach( *p, it );
     if( !loc ) {
         p->add_msg_if_player( _( "Never mind." ) );
         return std::nullopt;
     }
     item &obj = *loc.get_item();
     p->add_msg_if_player( _( "You attach %s to your MOLLE webbing." ), obj.tname() );
     it.get_contents().add_pocket( obj );
     // the item has been added to the vest it should no longer exist in the world
     loc.remove_item();
     return 0;
 }
References _, Character::add_msg_if_player(), item_contents::add_pocket(), debugmsg, item::get_contents(), item_location::get_item(), game_menus::inv::molle_attach(), item_location::remove_item(), string_id< T >::str(), item::tname(), and item::typeId().
Member Data Documentation
moves
int molle_attach_actor::moves
Definition at line 1020 of file iuse_actor.h.
size
int molle_attach_actor::size
Definition at line 1019 of file iuse_actor.h.
Referenced by attach_molle_inventory_preset::get_denial(), Item_modifier::modify(), and game_menus::inv::molle_attach().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp