Cataclysm DDA: talker_character_const Class Reference
talker_character_const Class Reference
#include <talker_character.h>
Public Member Functions
talker_character_const (const Character *new_me)
~talker_character_const () override=default
Character * get_character () override
const Character * get_character () const override
Creature * get_creature () override
const Creature * get_creature () const override
std::string disp_name () const override
std::string get_name () const override
character_id getID () const override
bool is_male () const override
std::vector< std::string > get_grammatical_genders () const override
int posx () const override
int posy () const override
int posz () const override
tripoint pos () const override
tripoint_abs_ms global_pos () const override
tripoint_abs_omt global_omt_location () const override
int get_cur_hp (const bodypart_id &bp) const override
int get_hp_max (const bodypart_id &bp) const override
units::temperature get_cur_part_temp (const bodypart_id &bp) const override
int str_cur () const override
int dex_cur () const override
int int_cur () const override
int per_cur () const override
int attack_speed () const override
int pain_cur () const override
int perceived_pain_cur () const override
double armor_at (damage_type_id &dt, bodypart_id &bp) const override
int coverage_at (bodypart_id &) const override
int encumbrance_at (bodypart_id &) const override
int get_str_max () const override
int get_dex_max () const override
int get_int_max () const override
int get_per_max () const override
int get_str_bonus () const override
int get_dex_bonus () const override
int get_int_bonus () const override
int get_per_bonus () const override
units::energy power_cur () const override
units::energy power_max () const override
int mana_cur () const override
int mana_max () const override
bool has_trait (const trait_id &trait_to_check) const override
bool has_recipe (const recipe_id &recipe_to_check) const override
bool has_flag (const json_character_flag &trait_flag_to_check) const override
bool has_species (const species_id &species) const override
bool bodytype (const bodytype_id &bt) const override
bool crossed_threshold () const override
int num_bionics () const override
bool has_max_power () const override
bool has_bionic (const bionic_id &bionics_id) const override
bool knows_spell (const spell_id &sp) const override
int get_skill_level (const skill_id &) const override
int get_skill_exp (const skill_id &skill, bool raw=false) const override
int get_spell_level (const trait_id &) const override
int get_spell_level (const spell_id &) const override
int get_spell_exp (const spell_id &) const override
int get_highest_spell_level () const override
int get_spell_count (const trait_id &) const override
int get_spell_sum (const trait_id &school, int min_level) const override
bool knows_proficiency (const proficiency_id &proficiency) const override
time_duration proficiency_practiced_time (const proficiency_id &) const override
bool has_effect (const efftype_id &effect_id, const bodypart_id &bp) const override
effect get_effect (const efftype_id &effect_id, const bodypart_id &bp) const override
bool is_deaf () const override
bool is_mute () const override
std::optional< std::string > maybe_get_value (const std::string &var_name) const override
std::vector< skill_id > skills_teacheable () const override
std::vector< skill_id > skills_offered_to (const talker &student) const override
std::string skill_seminar_text (const skill_id &s) const override
std::string skill_training_text (const talker &, const skill_id &) const override
std::vector< proficiency_id > proficiencies_teacheable () const override
std::vector< proficiency_id > proficiencies_offered_to (const talker &student) const override
std::string proficiency_seminar_text (const proficiency_id &) const override
std::string proficiency_training_text (const talker &student, const proficiency_id &proficiency) const override
std::vector< matype_id > styles_teacheable () const override
std::vector< matype_id > styles_offered_to (const talker &student) const override
std::string style_seminar_text (const matype_id &) const override
std::string style_training_text (const talker &, const matype_id &) const override
std::vector< spell_id > spells_teacheable () const override
std::vector< spell_id > spells_offered_to (talker &student) const override
std::string spell_seminar_text (const spell_id &) const override
std::string spell_training_text (talker &, const spell_id &) const override
bool is_wearing (const itype_id &item_id) const override
int charges_of (const itype_id &item_id) const override
bool has_charges (const itype_id &item_id, int count) const override
bool has_charges (const itype_id &item_id, int count, bool in_tools) const override
bool has_amount (const itype_id &item_id, int count) const override
int get_amount (const itype_id &item_id) const override
int cash () const override
std::vector< const item * > const_items_with (const std::function< bool(const item &)> &filter) const override
bool unarmed_attack () const override
bool can_stash_weapon () const override
bool has_stolen_item (const talker &guy) const override
faction * get_faction () const override
std::string short_description () const override
bool has_activity () const override
bool is_mounted () const override
int get_activity_level () const override
int get_sleepiness () const override
int get_hunger () const override
int get_thirst () const override
int get_instant_thirst () const override
int get_stored_kcal () const override
int get_healthy_kcal () const override
int get_size () const override
bool is_in_control_of (const vehicle &veh) const override
bool worn_with_flag (const flag_id &flag, const bodypart_id &bp) const override
bool wielded_with_flag (const flag_id &flag) const override
bool wielded_with_weapon_category (const weapon_category_id &w_cat) const override
bool has_item_with_flag (const flag_id &flag) const override
int item_rads (const flag_id &flag, aggregate_type agg_func) const override
bool can_see () const override
bool can_see_location (const tripoint &pos) const override
int morale_cur () const override
int focus_cur () const override
int get_rad () const override
int get_stim () const override
int get_addiction_intensity (const addiction_id &add_id) const override
int get_addiction_turns (const addiction_id &add_id) const override
int get_pkill () const override
int get_stamina () const override
int get_sleep_deprivation () const override
int get_kill_xp () const override
int get_age () const override
int get_height () const override
int get_bmi_permil () const override
int get_weight () const override
const move_mode_id & get_move_mode () const override
int get_fine_detail_vision_mod () const override
int get_health () const override
units::temperature get_body_temp () const override
units::temperature_delta get_body_temp_delta () const override
bool knows_martial_art (const matype_id &id) const override
bool using_martial_art (const matype_id &id) const override
int climate_control_str_heat () const override
int climate_control_str_chill () const override
Public Member Functions inherited from talker_cloner< talker_character_const >
std::unique_ptr< talker > clone () const override
Public Member Functions inherited from talker
virtual ~talker ()=default
virtual npc * get_npc ()
virtual npc * get_npc () const
virtual item_location * get_item ()
virtual item_location * get_item () const
virtual monster * get_monster ()
virtual const monster * get_monster () const
virtual computer * get_computer ()
virtual const computer * get_computer () const
virtual void set_pos (tripoint)
virtual std::string distance_to_goal () const
virtual bool will_talk_to_u (const Character &, bool)
virtual std::vector< std::string > get_topics (bool)
virtual void check_missions ()
virtual void update_missions (const std::vector< mission * > &)
virtual bool check_hostile_response (int) const
virtual int parse_mod (const std::string &, int) const
virtual int trial_chance_mod (const std::string &) const
virtual int get_count () const
virtual bool get_is_alive () const
virtual void set_str_max (int)
virtual void set_dex_max (int)
virtual void set_int_max (int)
virtual void set_per_max (int)
virtual void set_str_bonus (int)
virtual void set_dex_bonus (int)
virtual void set_int_bonus (int)
virtual void set_per_bonus (int)
virtual void set_spell_level (const spell_id &, int)
virtual void set_spell_exp (const spell_id &, int)
virtual void set_skill_level (const skill_id &, int)
virtual void set_skill_exp (const skill_id &, int, bool)
virtual void learn_recipe (const recipe_id &)
virtual void forget_recipe (const recipe_id &)
virtual void mutate (const int &, const bool &)
virtual void mutate_category (const mutation_category_id &, const bool &)
virtual void mutate_towards (const trait_id &, const mutation_category_id &, const bool &)
virtual void set_mutation (const trait_id &, const mutation_variant *=nullptr)
virtual void unset_mutation (const trait_id &)
virtual void activate_mutation (const trait_id &)
virtual void deactivate_mutation (const trait_id &)
virtual void set_sleepiness (int)
virtual int get_grab_strength () const
virtual void set_proficiency_practiced_time (const proficiency_id &, int)
virtual void train_proficiency_for (const proficiency_id &, int)
virtual void store_chosen_training (const skill_id &, const matype_id &, const spell_id &, const proficiency_id &)
virtual void add_effect (const efftype_id &, const time_duration &, const std::string &, bool, bool, int)
virtual void remove_effect (const efftype_id &, const std::string &)
virtual void add_bionic (const bionic_id &)
virtual void remove_bionic (const bionic_id &)
virtual std::string get_value (const std::string &key) const
virtual void set_value (const std::string &, const std::string &)
virtual void remove_value (const std::string &)
virtual std::list< item > use_charges (const itype_id &, int)
virtual std::list< item > use_charges (const itype_id &, int, bool)
virtual std::list< item > use_amount (const itype_id &, int)
virtual int value (const item &) const
virtual int debt () const
virtual void add_debt (int)
virtual int sold () const
virtual void add_sold (int)
virtual std::vector< item * > items_with (const std::function< bool(const item &)> &) const
virtual void i_add (const item &)
virtual void i_add_or_drop (item &, bool=false)
virtual void remove_items_with (const std::function< bool(const item &)> &)
virtual int cash_to_favor (int) const
virtual std::string give_item_to (bool)
virtual bool buy_from (int)
virtual bool buy_monster (talker &, const mtype_id &, int, int, bool, const translation &)
virtual std::vector< mission * > available_missions () const
virtual std::vector< mission * > assigned_missions () const
virtual mission * selected_mission () const
virtual void select_mission (mission *)
virtual void add_mission (const mission_type_id &)
virtual void set_companion_mission (const std::string &)
virtual void set_fac (const faction_id &)
virtual void add_faction_rep (int)
virtual bool is_following () const
virtual bool is_friendly (const Character &) const
virtual bool is_player_ally () const
virtual bool turned_hostile () const
virtual bool is_enemy () const
virtual void make_angry ()
virtual bool has_ai_rule (const std::string &, const std::string &) const
virtual void toggle_ai_rule (const std::string &, const std::string &)
virtual void set_ai_rule (const std::string &, const std::string &)
virtual void clear_ai_rule (const std::string &, const std::string &)
virtual std::string get_job_description () const
virtual std::string evaluation_by (const talker &) const
virtual std::string view_personality_traits () const
virtual bool is_myclass (const npc_class_id &) const
virtual void set_class (const npc_class_id &)
virtual void set_addiction_turns (const addiction_id &, int)
virtual void set_stored_kcal (int)
virtual void set_stim (int)
virtual void set_thirst (int)
virtual void say (const std::string &)
virtual void shout (const std::string &="", bool=false)
virtual bool enslave_mind ()
virtual std::string opinion_text () const
virtual void add_opinion (const npc_opinion &)
virtual void set_first_topic (const std::string &)
virtual bool is_safe () const
virtual void mod_pain (int)
virtual void set_pain (int)
virtual void attack_target (Creature &, bool, const matec_id &, bool, int)
virtual void set_power_cur (units::energy)
virtual void set_mana_cur (int)
virtual void mod_daily_health (int, int)
virtual void mod_focus (int)
virtual void set_pkill (int)
virtual void set_stamina (int)
virtual void set_sleep_deprivation (int)
virtual void set_rad (int)
virtual int get_anger () const
virtual void set_anger (int)
virtual void set_morale (int)
virtual int get_friendly () const
virtual void set_friendly (int)
virtual void add_morale (const morale_type &, int, int, time_duration, time_duration, bool)
virtual void remove_morale (const morale_type &)
virtual void set_kill_xp (int)
virtual void set_age (int)
virtual void set_height (int)
virtual int get_volume () const
virtual void set_npc_trust (int)
virtual int get_npc_trust () const
virtual void set_npc_fear (int)
virtual int get_npc_fear () const
virtual void set_npc_value (int)
virtual int get_npc_value () const
virtual void set_npc_anger (int)
virtual int get_npc_anger () const
virtual std::vector< bodypart_id > get_all_body_parts (get_body_part_flags) const
virtual int get_part_hp_cur (const bodypart_id &) const
virtual int get_part_hp_max (const bodypart_id &) const
virtual void set_all_parts_hp_cur (int) const
virtual void set_part_hp_cur (const bodypart_id &, int) const
virtual void die ()
virtual matec_id get_random_technique (Creature &, bool, bool, bool, const std::vector< matec_id > &={}) const
virtual void learn_martial_art (const matype_id &) const
virtual void forget_martial_art (const matype_id &) const
Protected Member Functions
talker_character_const ()=default
Protected Attributes
const Character * me_chr_const
Detailed Description
Definition at line 30 of file talker_character.h.
Constructor & Destructor Documentation
talker_character_const() [1/2]
talker_character_const::talker_character_const (const Character * new_me) inline explicit
Definition at line 33 of file talker_character.h.
                                                                   : me_chr_const( new_me ) {
         }
~talker_character_const()
talker_character_const::~talker_character_const () override default
talker_character_const() [2/2]
talker_character_const::talker_character_const () protected default
Member Function Documentation
armor_at()
double talker_character_const::armor_at (damage_type_id & dt, bodypart_id & bp) const override virtual
Reimplemented from talker.
Definition at line 708 of file talker_character.cpp.
 {
     return me_chr_const->worn.damage_resist( dt, bp );
 }
References bp, outfit::damage_resist(), me_chr_const, and Character::worn.
attack_speed()
int talker_character_const::attack_speed () const override virtual
Reimplemented from talker.
Definition at line 125 of file talker_character.cpp.
 {
     item_location cur_weapon = me_chr_const->used_weapon();
     item cur_weap = cur_weapon ? *cur_weapon : null_item_reference();
     return me_chr_const->attack_speed( cur_weap );
 }
References Character::attack_speed(), me_chr_const, null_item_reference(), and Character::used_weapon().
bodytype()
bool talker_character_const::bodytype (const bodytype_id & bt) const override virtual
Reimplemented from talker.
Definition at line 291 of file talker_character.cpp.
 {
     add_msg_debug( debugmode::DF_TALKER, "Character %s checked for bodytype %s", me_chr_const->name,
                    bt );
     // All characters are human-bodytyped for now
     // TODO: Change that for very limby characters
     return bt == "human";
 }
References add_msg_debug, debugmode::DF_TALKER, me_chr_const, and Character::name.
can_see()
bool talker_character_const::can_see () const override virtual
Reimplemented from talker.
Definition at line 790 of file talker_character.cpp.
 {
     return !me_chr_const->is_blind() && ( !me_chr_const->in_sleep_state() ||
                                           me_chr_const->has_flag( json_flag_SEESLEEP ) );
 }
References Character::has_flag(), Character::in_sleep_state(), Character::is_blind(), json_flag_SEESLEEP, and me_chr_const.
can_see_location()
bool talker_character_const::can_see_location (const tripoint & pos) const override virtual
Reimplemented from talker.
Definition at line 796 of file talker_character.cpp.
 {
     return me_chr_const->sees( pos );
 }
References me_chr_const, pos(), and Character::sees().
can_stash_weapon()
bool talker_character_const::can_stash_weapon () const override virtual
Reimplemented from talker.
Definition at line 593 of file talker_character.cpp.
 {
     std::optional<bionic *> bionic_weapon = me_chr_const->find_bionic_by_uid(
             me_chr_const->get_weapon_bionic_uid() );
     if( bionic_weapon && me_chr_const->can_deactivate_bionic( **bionic_weapon ).success() ) {
         return true;
     }
     return me_chr_const->can_pickVolume( *me_chr_const->get_wielded_item() );
 }
References Character::can_deactivate_bionic(), Character::can_pickVolume(), Character::find_bionic_by_uid(), Character::get_weapon_bionic_uid(), Character::get_wielded_item(), me_chr_const, and ret_val_common::success().
cash()
int talker_character_const::cash () const override virtual
Reimplemented from talker.
Definition at line 544 of file talker_character.cpp.
 {
     return me_chr_const->cash;
 }
References Character::cash, and me_chr_const.
charges_of()
int talker_character_const::charges_of (const itype_id & item_id) const override virtual
Reimplemented from talker.
Definition at line 495 of file talker_character.cpp.
 {
     return me_chr_const->charges_of( item_id );
 }
References Character::charges_of(), and me_chr_const.
climate_control_str_chill()
int talker_character_const::climate_control_str_chill () const override virtual
Reimplemented from talker.
Definition at line 1243 of file talker_character.cpp.
 {
     return me_chr_const->climate_control_strength().second;
 }
References Character::climate_control_strength(), and me_chr_const.
climate_control_str_heat()
int talker_character_const::climate_control_str_heat () const override virtual
Reimplemented from talker.
Definition at line 1238 of file talker_character.cpp.
 {
     return me_chr_const->climate_control_strength().first;
 }
References Character::climate_control_strength(), and me_chr_const.
const_items_with()
std::vector< const item * > talker_character_const::const_items_with (const std::function< bool(const item &)> & filter) const override virtual
Reimplemented from talker.
Definition at line 549 of file talker_character.cpp.
 {
     return me_chr_const->items_with( filter );
 }
References filter, visitable::items_with(), and me_chr_const.
coverage_at()
int talker_character_const::coverage_at (bodypart_id & id) const override virtual
Reimplemented from talker.
Definition at line 713 of file talker_character.cpp.
 {
     return me_chr_const->worn.get_coverage( id );
 }
References outfit::get_coverage(), me_chr_const, and Character::worn.
crossed_threshold()
bool talker_character_const::crossed_threshold () const override virtual
Reimplemented from talker.
Definition at line 300 of file talker_character.cpp.
 {
     return me_chr_const->crossed_threshold();
 }
References Character::crossed_threshold(), and me_chr_const.
dex_cur()
int talker_character_const::dex_cur () const override virtual
Reimplemented from talker.
Definition at line 110 of file talker_character.cpp.
 {
     return me_chr_const->dex_cur;
 }
References Character::dex_cur, and me_chr_const.
disp_name()
std::string talker_character_const::disp_name () const override virtual
Reimplemented from talker.
Definition at line 30 of file talker_character.cpp.
 {
     return me_chr_const->disp_name();
 }
References Character::disp_name(), and me_chr_const.
Referenced by talker_npc::will_talk_to_u().
encumbrance_at()
int talker_character_const::encumbrance_at (bodypart_id & id) const override virtual
Reimplemented from talker.
Definition at line 718 of file talker_character.cpp.
 {
     return me_chr_const->encumb( id );
 }
References Character::encumb(), and me_chr_const.
focus_cur()
int talker_character_const::focus_cur () const override virtual
Reimplemented from talker.
Definition at line 827 of file talker_character.cpp.
 {
     return me_chr_const->get_focus();
 }
References Character::get_focus(), and me_chr_const.
get_activity_level()
int talker_character_const::get_activity_level () const override virtual
Reimplemented from talker.
Definition at line 637 of file talker_character.cpp.
 {
     return me_chr_const->activity_level_index();
 }
References Character::activity_level_index(), and me_chr_const.
get_addiction_intensity()
int talker_character_const::get_addiction_intensity (const addiction_id & add_id) const override virtual
Reimplemented from talker.
Definition at line 852 of file talker_character.cpp.
 {
     return me_chr_const->addiction_level( add_id );
 }
References Character::addiction_level(), and me_chr_const.
get_addiction_turns()
int talker_character_const::get_addiction_turns (const addiction_id & add_id) const override virtual
Reimplemented from talker.
Definition at line 857 of file talker_character.cpp.
 {
     for( const addiction &add : me_chr_const->addictions ) {
         if( add.type == add_id ) {
             return to_turns<int>( add.sated );
         }
     }
     return 0;
 }
References add, Character::addictions, and me_chr_const.
get_age()
int talker_character_const::get_age () const override virtual
Reimplemented from talker.
Definition at line 928 of file talker_character.cpp.
 {
     return me_chr_const->age();
 }
References Character::age(), and me_chr_const.
get_amount()
int talker_character_const::get_amount (const itype_id & item_id) const override virtual
Reimplemented from talker.
Definition at line 539 of file talker_character.cpp.
 {
     return me_chr_const->amount_of( item_id );
 }
References Character::amount_of(), and me_chr_const.
get_bmi_permil()
int talker_character_const::get_bmi_permil () const override virtual
Reimplemented from talker.
Definition at line 933 of file talker_character.cpp.
 {
     return std::round( me_chr_const->get_bmi_fat() * 1000.0f );
 }
References Character::get_bmi_fat(), me_chr_const, and round().
get_body_temp()
units::temperature talker_character_const::get_body_temp () const override virtual
Reimplemented from talker.
Definition at line 985 of file talker_character.cpp.
 {
     return me_chr_const->get_part_temp_cur( temp_delta( me_chr_const ).first );
 }
References Creature::get_part_temp_cur(), me_chr_const, and temp_delta().
get_body_temp_delta()
units::temperature_delta talker_character_const::get_body_temp_delta () const override virtual
Reimplemented from talker.
Definition at line 990 of file talker_character.cpp.
 {
     return me_chr_const->get_part_temp_conv( temp_delta( me_chr_const ).second ) -
            me_chr_const->get_part_temp_cur( temp_delta( me_chr_const ).first );
 }
References Creature::get_part_temp_conv(), Creature::get_part_temp_cur(), me_chr_const, second, and temp_delta().
get_character() [1/2]
const Character* talker_character_const::get_character () const inline override virtual
Reimplemented from talker.
Reimplemented in talker_character.
Definition at line 41 of file talker_character.h.
{
             return me_chr_const;
         }
References me_chr_const.
get_character() [2/2]
Character* talker_character_const::get_character () inline override virtual
Reimplemented from talker.
Reimplemented in talker_character.
Definition at line 38 of file talker_character.h.
{
             return nullptr;
         }
get_creature() [1/2]
const Creature* talker_character_const::get_creature () const inline override virtual
Reimplemented from talker.
Reimplemented in talker_character.
Definition at line 47 of file talker_character.h.
{
             return me_chr_const;
         }
References me_chr_const.
get_creature() [2/2]
Creature* talker_character_const::get_creature () inline override virtual
Reimplemented from talker.
Reimplemented in talker_character.
Definition at line 44 of file talker_character.h.
{
             return nullptr;
         }
get_cur_hp()
int talker_character_const::get_cur_hp (const bodypart_id & bp) const override virtual
Reimplemented from talker.
Definition at line 90 of file talker_character.cpp.
 {
     return me_chr_const->get_hp( bp );
 }
References bp, Creature::get_hp(), and me_chr_const.
get_cur_part_temp()
units::temperature talker_character_const::get_cur_part_temp (const bodypart_id & bp) const override virtual
Reimplemented from talker.
Definition at line 100 of file talker_character.cpp.
 {
     return me_chr_const->get_part_temp_conv( bp );
 }
References bp, Creature::get_part_temp_conv(), and me_chr_const.
get_dex_bonus()
int talker_character_const::get_dex_bonus () const override virtual
Reimplemented from talker.
Definition at line 197 of file talker_character.cpp.
 {
     return me_chr_const->get_dex_bonus();
 }
References Character::get_dex_bonus(), and me_chr_const.
get_dex_max()
int talker_character_const::get_dex_max () const override virtual
Reimplemented from talker.
Definition at line 177 of file talker_character.cpp.
 {
     return me_chr_const->dex_max;
 }
References Character::dex_max, and me_chr_const.
get_effect()
effect talker_character_const::get_effect (const efftype_id & effect_id, const bodypart_id & bp) const override virtual
Reimplemented from talker.
Definition at line 443 of file talker_character.cpp.
 {
     return me_chr_const->get_effect( effect_id, bp );
 }
References bp, Creature::get_effect(), and me_chr_const.
get_faction()
faction * talker_character_const::get_faction () const override virtual
Reimplemented from talker.
Definition at line 617 of file talker_character.cpp.
 {
     return me_chr_const->get_faction();
 }
References Character::get_faction(), and me_chr_const.
get_fine_detail_vision_mod()
int talker_character_const::get_fine_detail_vision_mod () const override virtual
Reimplemented from talker.
Definition at line 958 of file talker_character.cpp.
 {
     return std::ceil( me_chr_const->fine_detail_vision_mod() );
 }
References ceil(), Character::fine_detail_vision_mod(), and me_chr_const.
get_grammatical_genders()
std::vector< std::string > talker_character_const::get_grammatical_genders () const override virtual
Reimplemented from talker.
Definition at line 50 of file talker_character.cpp.
 {
     return me_chr_const->get_grammatical_genders();
 }
References Character::get_grammatical_genders(), and me_chr_const.
get_health()
int talker_character_const::get_health () const override virtual
Reimplemented from talker.
Definition at line 963 of file talker_character.cpp.
 {
     return me_chr_const->get_lifestyle();
 }
References Character::get_lifestyle(), and me_chr_const.
get_healthy_kcal()
int talker_character_const::get_healthy_kcal () const override virtual
Reimplemented from talker.
Definition at line 667 of file talker_character.cpp.
 {
     return me_chr_const->get_healthy_kcal();
 }
References Character::get_healthy_kcal(), and me_chr_const.
get_height()
int talker_character_const::get_height () const override virtual
Reimplemented from talker.
Definition at line 948 of file talker_character.cpp.
 {
     return me_chr_const->height();
 }
References Character::height(), and me_chr_const.
get_highest_spell_level()
int talker_character_const::get_highest_spell_level () const override virtual
Reimplemented from talker.
Definition at line 367 of file talker_character.cpp.
 {
     int spell_level = -1;
     for( const spell *sp : me_chr_const->magic->get_spells() ) {
         spell_level = std::max( sp->get_effective_level(), spell_level );
     }
     return spell_level;
 }
References Character::magic, max(), and me_chr_const.
get_hp_max()
int talker_character_const::get_hp_max (const bodypart_id & bp) const override virtual
Reimplemented from talker.
Definition at line 95 of file talker_character.cpp.
 {
     return me_chr_const->get_hp_max( bp );
 }
References bp, Creature::get_hp_max(), and me_chr_const.
get_hunger()
int talker_character_const::get_hunger () const override virtual
Reimplemented from talker.
Definition at line 647 of file talker_character.cpp.
 {
     return me_chr_const->get_hunger();
 }
References Character::get_hunger(), and me_chr_const.
Referenced by talker_npc::evaluation_by().
get_instant_thirst()
int talker_character_const::get_instant_thirst () const override virtual
Reimplemented from talker.
Definition at line 657 of file talker_character.cpp.
 {
     return me_chr_const->get_instant_thirst();
 }
References Character::get_instant_thirst(), and me_chr_const.
get_int_bonus()
int talker_character_const::get_int_bonus () const override virtual
Reimplemented from talker.
Definition at line 202 of file talker_character.cpp.
 {
     return me_chr_const->get_int_bonus();
 }
References Character::get_int_bonus(), and me_chr_const.
get_int_max()
int talker_character_const::get_int_max () const override virtual
Reimplemented from talker.
Definition at line 182 of file talker_character.cpp.
 {
     return me_chr_const->int_max;
 }
References Character::int_max, and me_chr_const.
get_kill_xp()
int talker_character_const::get_kill_xp () const override virtual
Reimplemented from talker.
Definition at line 916 of file talker_character.cpp.
 {
     return me_chr_const->kill_xp;
 }
References Character::kill_xp, and me_chr_const.
get_move_mode()
const move_mode_id & talker_character_const::get_move_mode () const override virtual
Reimplemented from talker.
Definition at line 953 of file talker_character.cpp.
 {
     return me_chr_const->move_mode;
 }
References me_chr_const, and Character::move_mode.
get_name()
std::string talker_character_const::get_name () const override virtual
Reimplemented from talker.
Definition at line 35 of file talker_character.cpp.
 {
     return me_chr_const->get_name();
 }
References Character::get_name(), and me_chr_const.
get_per_bonus()
int talker_character_const::get_per_bonus () const override virtual
Reimplemented from talker.
Definition at line 207 of file talker_character.cpp.
 {
     return me_chr_const->get_per_bonus();
 }
References Character::get_per_bonus(), and me_chr_const.
get_per_max()
int talker_character_const::get_per_max () const override virtual
Reimplemented from talker.
Definition at line 187 of file talker_character.cpp.
 {
     return me_chr_const->per_max;
 }
References me_chr_const, and Character::per_max.
get_pkill()
int talker_character_const::get_pkill () const override virtual
Reimplemented from talker.
Definition at line 881 of file talker_character.cpp.
 {
     return me_chr_const->get_painkiller();
 }
References Character::get_painkiller(), and me_chr_const.
get_rad()
int talker_character_const::get_rad () const override virtual
Reimplemented from talker.
Definition at line 842 of file talker_character.cpp.
 {
     return me_chr_const->get_rad();
 }
References Character::get_rad(), and me_chr_const.
get_size()
int talker_character_const::get_size () const override virtual
Reimplemented from talker.
Definition at line 672 of file talker_character.cpp.
 {
     add_msg_debug( debugmode::DF_TALKER, "Size category of character %s = %d", me_chr_const->name,
                    me_chr_const->get_size() - 0 );
     return me_chr_const->get_size() - 0;
 }
References add_msg_debug, debugmode::DF_TALKER, Character::get_size(), me_chr_const, and Character::name.
get_skill_exp()
int talker_character_const::get_skill_exp (const skill_id & skill, bool raw = false) const override virtual
Reimplemented from talker.
Definition at line 340 of file talker_character.cpp.
 {
     return me_chr_const->get_skill_level_object( skill ).exercise( raw );
 }
References SkillLevel::exercise(), Character::get_skill_level_object(), and me_chr_const.
get_skill_level()
int talker_character_const::get_skill_level (const skill_id & skill) const override virtual
Reimplemented from talker.
Definition at line 330 of file talker_character.cpp.
 {
     return me_chr_const->get_skill_level( skill );
 }
References Character::get_skill_level(), and me_chr_const.
get_sleep_deprivation()
int talker_character_const::get_sleep_deprivation () const override virtual
Reimplemented from talker.
Definition at line 901 of file talker_character.cpp.
 {
     return me_chr_const->get_sleep_deprivation();
 }
References Character::get_sleep_deprivation(), and me_chr_const.
get_sleepiness()
int talker_character_const::get_sleepiness () const override virtual
Reimplemented from talker.
Definition at line 642 of file talker_character.cpp.
 {
     return me_chr_const->get_sleepiness();
 }
References Character::get_sleepiness(), and me_chr_const.
Referenced by talker_npc::evaluation_by().
get_spell_count()
int talker_character_const::get_spell_count (const trait_id & school) const override virtual
Reimplemented from talker.
Definition at line 384 of file talker_character.cpp.
 {
     int count = 0;
     for( const spell *sp : me_chr_const->magic->get_spells() ) {
         if( school.is_null() || sp->spell_class() == school ) {
             count++;
         }
     }
     return count;
 }
References string_id< T >::is_null(), Character::magic, and me_chr_const.
get_spell_exp()
int talker_character_const::get_spell_exp (const spell_id & spell_name) const override virtual
Reimplemented from talker.
Definition at line 376 of file talker_character.cpp.
 {
     if( !me_chr_const->magic->knows_spell( spell_name ) ) {
         return -1;
     }
     return me_chr_const->magic->get_spell( spell_name ).xp();
 }
References Character::magic, and me_chr_const.
get_spell_level() [1/2]
int talker_character_const::get_spell_level (const spell_id & spell_name) const override virtual
Reimplemented from talker.
Definition at line 359 of file talker_character.cpp.
 {
     if( !me_chr_const->magic->knows_spell( spell_name ) ) {
         return -1;
     }
     return me_chr_const->magic->get_spell( spell_name ).get_effective_level();
 }
References Character::magic, and me_chr_const.
get_spell_level() [2/2]
int talker_character_const::get_spell_level (const trait_id & spell_school) const override virtual
Reimplemented from talker.
Definition at line 350 of file talker_character.cpp.
 {
     int spell_level = -1;
     for( const spell &sp : me_chr_const->spells_known_of_class( spell_school ) ) {
         spell_level = std::max( sp.get_effective_level(), spell_level );
     }
     return spell_level;
 }
References max(), me_chr_const, and Character::spells_known_of_class().
get_spell_sum()
int talker_character_const::get_spell_sum (const trait_id & school, int min_level) const override virtual
Reimplemented from talker.
Definition at line 395 of file talker_character.cpp.
 {
     int count = 0;
     for( const spell *sp : me_chr_const->magic->get_spells() ) {
         if( school.is_null() || ( sp->spell_class() == school &&
                                   sp->get_effective_level() >= min_level ) ) {
             count = count + sp->get_effective_level() ;
         }
     }
     return count;
 }
References string_id< T >::is_null(), Character::magic, and me_chr_const.
get_stamina()
int talker_character_const::get_stamina () const override virtual
Reimplemented from talker.
Definition at line 891 of file talker_character.cpp.
 {
     return me_chr_const->get_stamina();
 }
References Character::get_stamina(), and me_chr_const.
get_stim()
int talker_character_const::get_stim () const override virtual
Reimplemented from talker.
Definition at line 847 of file talker_character.cpp.
 {
     return me_chr_const->get_stim();
 }
References Character::get_stim(), and me_chr_const.
get_stored_kcal()
int talker_character_const::get_stored_kcal () const override virtual
Reimplemented from talker.
Definition at line 662 of file talker_character.cpp.
 {
     return me_chr_const->get_stored_kcal();
 }
References Character::get_stored_kcal(), and me_chr_const.
get_str_bonus()
int talker_character_const::get_str_bonus () const override virtual
Reimplemented from talker.
Definition at line 192 of file talker_character.cpp.
 {
     return me_chr_const->get_str_bonus();
 }
References Character::get_str_bonus(), and me_chr_const.
get_str_max()
int talker_character_const::get_str_max () const override virtual
Reimplemented from talker.
Definition at line 172 of file talker_character.cpp.
 {
     return me_chr_const->str_max;
 }
References me_chr_const, and Character::str_max.
get_thirst()
int talker_character_const::get_thirst () const override virtual
Reimplemented from talker.
Definition at line 652 of file talker_character.cpp.
 {
     return me_chr_const->get_thirst();
 }
References Character::get_thirst(), and me_chr_const.
Referenced by talker_npc::evaluation_by().
get_weight()
int talker_character_const::get_weight () const override virtual
Reimplemented from talker.
Definition at line 938 of file talker_character.cpp.
 {
     return units::to_milligram( me_chr_const->get_weight() );
 }
References Character::get_weight(), me_chr_const, and units::to_milligram().
getID()
character_id talker_character_const::getID () const override virtual
Reimplemented from talker.
Definition at line 40 of file talker_character.cpp.
 {
     return me_chr_const->getID();
 }
References Character::getID(), and me_chr_const.
Referenced by talker_npc::will_talk_to_u().
global_omt_location()
tripoint_abs_omt talker_character_const::global_omt_location () const override virtual
Reimplemented from talker.
Definition at line 80 of file talker_character.cpp.
 {
     return me_chr_const->global_omt_location();
 }
References Creature::global_omt_location(), and me_chr_const.
global_pos()
tripoint_abs_ms talker_character_const::global_pos () const override virtual
Reimplemented from talker.
Definition at line 75 of file talker_character.cpp.
 {
     return me_chr_const->get_location();
 }
References Creature::get_location(), and me_chr_const.
has_activity()
bool talker_character_const::has_activity () const override virtual
Reimplemented from talker.
Reimplemented in talker_npc.
Definition at line 627 of file talker_character.cpp.
 {
     return !me_chr_const->activity.is_null();
 }
References Character::activity, player_activity::is_null(), and me_chr_const.
has_amount()
bool talker_character_const::has_amount (const itype_id & item_id, int count) const override virtual
Reimplemented from talker.
Definition at line 534 of file talker_character.cpp.
 {
     return me_chr_const->has_amount( item_id, count );
 }
References visitable::has_amount(), and me_chr_const.
has_bionic()
bool talker_character_const::has_bionic (const bionic_id & bionics_id) const override virtual
Reimplemented from talker.
Definition at line 320 of file talker_character.cpp.
 {
     return me_chr_const->has_bionic( bionics_id );
 }
References Character::has_bionic(), and me_chr_const.
has_charges() [1/2]
bool talker_character_const::has_charges (const itype_id & item_id, int count) const override virtual
Reimplemented from talker.
Definition at line 500 of file talker_character.cpp.
 {
     return me_chr_const->has_charges( item_id, count );
 }
References Character::has_charges(), and me_chr_const.
has_charges() [2/2]
bool talker_character_const::has_charges (const itype_id & item_id, int count, bool in_tools) const override virtual
Reimplemented from talker.
Definition at line 505 of file talker_character.cpp.
 {
     if( !in_tools ) {
         return me_chr_const->has_charges( item_id, count );
     } else {
         return me_chr_const->charges_of( item_id, count, return_true<item>, nullptr, in_tools ) >= count;
     }
 }
References Character::charges_of(), Character::has_charges(), and me_chr_const.
has_effect()
bool talker_character_const::has_effect (const efftype_id & effect_id, const bodypart_id & bp) const override virtual
Reimplemented from talker.
Definition at line 438 of file talker_character.cpp.
 {
     return me_chr_const->has_effect( effect_id, bp );
 }
References bp, Creature::has_effect(), and me_chr_const.
has_flag()
bool talker_character_const::has_flag (const json_character_flag & trait_flag_to_check) const override virtual
Reimplemented from talker.
Definition at line 279 of file talker_character.cpp.
 {
     return me_chr_const->has_flag( trait_flag_to_check );
 }
References Character::has_flag(), and me_chr_const.
has_item_with_flag()
bool talker_character_const::has_item_with_flag (const flag_id & flag) const override virtual
Reimplemented from talker.
Definition at line 749 of file talker_character.cpp.
 {
     return me_chr_const->cache_has_item_with( flag );
 }
References Character::cache_has_item_with(), and me_chr_const.
has_max_power()
bool talker_character_const::has_max_power () const override virtual
Reimplemented from talker.
Definition at line 310 of file talker_character.cpp.
 {
     return me_chr_const->has_max_power();
 }
References Character::has_max_power(), and me_chr_const.
has_recipe()
bool talker_character_const::has_recipe (const recipe_id & recipe_to_check) const override virtual
Reimplemented from talker.
Definition at line 217 of file talker_character.cpp.
 {
     return me_chr_const->knows_recipe( &*recipe_to_check );
 }
References Character::knows_recipe(), and me_chr_const.
has_species()
bool talker_character_const::has_species (const species_id & species) const override virtual
Reimplemented from talker.
Definition at line 284 of file talker_character.cpp.
 {
     add_msg_debug( debugmode::DF_TALKER, "Character %s checked for species %s", me_chr_const->name,
                    species.c_str() );
     return me_chr_const->in_species( species );
 }
References add_msg_debug, string_id< T >::c_str(), debugmode::DF_TALKER, Character::in_species(), me_chr_const, and Character::name.
has_stolen_item()
bool talker_character_const::has_stolen_item (const talker & guy) const override virtual
Reimplemented from talker.
Definition at line 604 of file talker_character.cpp.
 {
     const Character *owner = guy.get_character();
     if( owner ) {
         for( const item *&elem : me_chr_const->inv_dump() ) {
             if( elem->is_old_owner( *owner, true ) ) {
                 return true;
             }
         }
     }
     return false;
 }
References talker::get_character(), Character::inv_dump(), and me_chr_const.
has_trait()
bool talker_character_const::has_trait (const trait_id & trait_to_check) const override virtual
Reimplemented from talker.
Definition at line 212 of file talker_character.cpp.
 {
     return me_chr_const->has_trait( trait_to_check );
 }
References Character::has_trait(), and me_chr_const.
Referenced by talker_avatar::get_topics().
int_cur()
int talker_character_const::int_cur () const override virtual
Reimplemented from talker.
Definition at line 115 of file talker_character.cpp.
 {
     return me_chr_const->int_cur;
 }
References Character::int_cur, and me_chr_const.
is_deaf()
bool talker_character_const::is_deaf () const override virtual
Reimplemented from talker.
Definition at line 232 of file talker_character.cpp.
 {
     return me_chr_const->is_deaf();
 }
References Character::is_deaf(), and me_chr_const.
is_in_control_of()
bool talker_character_const::is_in_control_of (const vehicle & veh) const override virtual
Reimplemented from talker.
Definition at line 688 of file talker_character.cpp.
 {
     return veh.player_in_control( *me_chr_const );
 }
References me_chr_const, and vehicle::player_in_control().
is_male()
bool talker_character_const::is_male () const override virtual
Reimplemented from talker.
Definition at line 45 of file talker_character.cpp.
 {
     return me_chr_const->male;
 }
References Character::male, and me_chr_const.
is_mounted()
bool talker_character_const::is_mounted () const override virtual
Reimplemented from talker.
Definition at line 632 of file talker_character.cpp.
 {
     return me_chr_const->is_mounted();
 }
References Character::is_mounted(), and me_chr_const.
is_mute()
bool talker_character_const::is_mute () const override virtual
Reimplemented from talker.
Definition at line 237 of file talker_character.cpp.
 {
     return me_chr_const->is_mute();
 }
References Character::is_mute(), and me_chr_const.
is_wearing()
bool talker_character_const::is_wearing (const itype_id & item_id) const override virtual
Reimplemented from talker.
Definition at line 490 of file talker_character.cpp.
 {
     return me_chr_const->is_wearing( item_id );
 }
References Character::is_wearing(), and me_chr_const.
Referenced by talker_avatar::get_topics().
item_rads()
int talker_character_const::item_rads (const flag_id & flag, aggregate_type agg_func) const override virtual
Reimplemented from talker.
Definition at line 754 of file talker_character.cpp.
 {
     std::vector<int> rad_vals;
     me_chr_const->cache_visit_items_with( flag, [&]( const item & it ) {
         if( me_chr_const->is_worn( it ) || me_chr_const->is_wielding( it ) ) {
             rad_vals.emplace_back( it.irradiation );
         }
     } );
     return aggregate( rad_vals, agg_func );
 }
References aggregate(), Character::cache_visit_items_with(), Character::is_wielding(), Character::is_worn(), and me_chr_const.
knows_martial_art()
bool talker_character_const::knows_martial_art (const matype_id & id) const override virtual
Reimplemented from talker.
Definition at line 996 of file talker_character.cpp.
 {
     return me_chr_const->martial_arts_data->has_martialart( id );
 }
References Character::martial_arts_data, and me_chr_const.
knows_proficiency()
bool talker_character_const::knows_proficiency (const proficiency_id & proficiency) const override virtual
Reimplemented from talker.
Definition at line 418 of file talker_character.cpp.
 {
     return me_chr_const->has_proficiency( proficiency );
 }
References Character::has_proficiency(), and me_chr_const.
knows_spell()
bool talker_character_const::knows_spell (const spell_id & sp) const override virtual
Reimplemented from talker.
Definition at line 325 of file talker_character.cpp.
 {
     return me_chr_const->magic->knows_spell( sp );
 }
References Character::magic, and me_chr_const.
mana_cur()
int talker_character_const::mana_cur () const override virtual
Reimplemented from talker.
Definition at line 775 of file talker_character.cpp.
 {
     return me_chr_const->magic->available_mana();
 }
References Character::magic, and me_chr_const.
mana_max()
int talker_character_const::mana_max () const override virtual
Reimplemented from talker.
Definition at line 780 of file talker_character.cpp.
 {
     return me_chr_const->magic->max_mana( *me_chr_const );
 }
References Character::magic, and me_chr_const.
maybe_get_value()
std::optional< std::string > talker_character_const::maybe_get_value (const std::string & var_name) const override virtual
Reimplemented from talker.
Definition at line 474 of file talker_character.cpp.
 {
     return me_chr_const->maybe_get_value( var_name );
 }
References Creature::maybe_get_value(), and me_chr_const.
morale_cur()
int talker_character_const::morale_cur () const override virtual
Reimplemented from talker.
Definition at line 811 of file talker_character.cpp.
 {
     return me_chr_const->get_morale_level();
 }
References Character::get_morale_level(), and me_chr_const.
num_bionics()
int talker_character_const::num_bionics () const override virtual
Reimplemented from talker.
Definition at line 305 of file talker_character.cpp.
 {
     return me_chr_const->num_bionics();
 }
References me_chr_const, and Character::num_bionics().
pain_cur()
int talker_character_const::pain_cur () const override virtual
Reimplemented from talker.
Definition at line 698 of file talker_character.cpp.
 {
     return me_chr_const->get_pain();
 }
References Creature::get_pain(), and me_chr_const.
per_cur()
int talker_character_const::per_cur () const override virtual
Reimplemented from talker.
Definition at line 120 of file talker_character.cpp.
 {
     return me_chr_const->per_cur;
 }
References me_chr_const, and Character::per_cur.
perceived_pain_cur()
int talker_character_const::perceived_pain_cur () const override virtual
Reimplemented from talker.
Definition at line 703 of file talker_character.cpp.
 {
     return me_chr_const->get_perceived_pain();
 }
References Character::get_perceived_pain(), and me_chr_const.
pos()
tripoint talker_character_const::pos () const override virtual
Reimplemented from talker.
Definition at line 70 of file talker_character.cpp.
 {
     return me_chr_const->pos();
 }
References me_chr_const, and Creature::pos().
Referenced by can_see_location().
posx()
int talker_character_const::posx () const override virtual
Reimplemented from talker.
Definition at line 55 of file talker_character.cpp.
 {
     return me_chr_const->posx();
 }
References me_chr_const, and Creature::posx().
posy()
int talker_character_const::posy () const override virtual
Reimplemented from talker.
Definition at line 60 of file talker_character.cpp.
 {
     return me_chr_const->posy();
 }
References me_chr_const, and Creature::posy().
posz()
int talker_character_const::posz () const override virtual
Reimplemented from talker.
Definition at line 65 of file talker_character.cpp.
 {
     return me_chr_const->posz();
 }
References me_chr_const, and Creature::posz().
power_cur()
units::energy talker_character_const::power_cur () const override virtual
Reimplemented from talker.
Definition at line 765 of file talker_character.cpp.
 {
     return me_chr_const->get_power_level();
 }
References Character::get_power_level(), and me_chr_const.
power_max()
units::energy talker_character_const::power_max () const override virtual
Reimplemented from talker.
Definition at line 770 of file talker_character.cpp.
 {
     return me_chr_const->get_max_power_level();
 }
References Character::get_max_power_level(), and me_chr_const.
proficiencies_offered_to()
std::vector< proficiency_id > talker_character_const::proficiencies_offered_to (const talker & student) const override virtual
Reimplemented from talker.
Definition at line 1070 of file talker_character.cpp.
 {
     if( student.get_character() ) {
         return me_chr_const->proficiencies_offered_to( student.get_character() );
     } else {
         return {};
     }
 }
References talker::get_character(), me_chr_const, and Character::proficiencies_offered_to().
proficiencies_teacheable()
std::vector< proficiency_id > talker_character_const::proficiencies_teacheable () const override virtual
Reimplemented from talker.
Definition at line 1023 of file talker_character.cpp.
 {
     return me_chr_const->proficiencies_offered_to( nullptr );
 }
References me_chr_const, and Character::proficiencies_offered_to().
proficiency_practiced_time()
time_duration talker_character_const::proficiency_practiced_time (const proficiency_id & prof) const override virtual
Reimplemented from talker.
Definition at line 423 of file talker_character.cpp.
 {
     return me_chr_const->get_proficiency_practiced_time( prof );
 }
References Character::get_proficiency_practiced_time(), and me_chr_const.
proficiency_seminar_text()
std::string talker_character_const::proficiency_seminar_text (const proficiency_id & p) const override virtual
Reimplemented from talker.
Definition at line 1165 of file talker_character.cpp.
 {
     return p->name();
 }
References proficiency::name().
proficiency_training_text()
std::string talker_character_const::proficiency_training_text (const talker & student, const proficiency_id & proficiency) const override virtual
Reimplemented from talker.
Definition at line 1080 of file talker_character.cpp.
 {
     const Character *pupil = student.get_character();
     if( !pupil ) {
         return "";
     }
     const time_duration time_needed = proficiency->time_to_learn();
     const time_duration current_time = time_needed - pupil->proficiency_training_needed( proficiency );
     const int cost = calc_proficiency_training_cost( *me_chr_const, *pupil, proficiency );
     const std::string name = proficiency->name();
     const float pct_before = current_time / time_needed * 100;
     const float pct_after = ( current_time + 15_minutes ) / time_needed * 100;
     const std::string after_str = pct_after >= 100.0f ? pgettext( "NPC training: proficiency learned",
                                   "done" ) : string_format( "%2.0f%%", pct_after );
     if( cost > 0 ) {
         //~ Proficiency name: (current_practice) -> (next_practice) (cost in dollars)
         return string_format( _( "%s: (%2.0f%%) -> (%s) (cost $%d)" ), name, pct_before, after_str, cost );
     }
     //~ Proficiency name: (current_practice) -> (next_practice)
     return string_format( _( "%s: (%2.0f%%) -> (%s)" ), name, pct_before, after_str );
 }
References _, calc_proficiency_training_cost(), talker::get_character(), me_chr_const, proficiency::name(), om_direction::name(), pgettext, Character::proficiency_training_needed(), string_format(), and proficiency::time_to_learn().
short_description()
std::string talker_character_const::short_description () const override virtual
Reimplemented from talker.
Definition at line 622 of file talker_character.cpp.
 {
     return me_chr_const->short_description();
 }
References me_chr_const, and Character::short_description().
skill_seminar_text()
std::string talker_character_const::skill_seminar_text (const skill_id & s) const override virtual
Reimplemented from talker.
Definition at line 1159 of file talker_character.cpp.
 {
     int lvl = me_chr_const->get_skill_level( s );
     return string_format( "%s (%d)", s.obj().name(), lvl );
 }
References Character::get_skill_level(), me_chr_const, Skill::name(), string_id< T >::obj(), and string_format().
skill_training_text()
std::string talker_character_const::skill_training_text (const talker & student, const skill_id & skill) const override virtual
Reimplemented from talker.
Definition at line 1047 of file talker_character.cpp.
 {
     const Character *pupil = student.get_character();
     if( !pupil ) {
         return "";
     }
     const int cost = calc_skill_training_cost_char( *me_chr_const, *pupil, skill );
     SkillLevel skill_level_obj = pupil->get_skill_level_object( skill );
     SkillLevel teacher_skill_level = me_chr_const->get_skill_level_object( skill );
     const int cur_level = skill_level_obj.knowledgeLevel();
     const int cur_level_exercise = skill_level_obj.knowledgeExperience();
     // knowledge_train will adjust level xp based on the difference between your understanding and the NPC's.
     skill_level_obj.knowledge_train( 10000, teacher_skill_level.knowledgeLevel() );
     const int next_level = skill_level_obj.knowledgeLevel();
     const int next_level_exercise = skill_level_obj.knowledgeExperience();
     //~Skill name: current level (experience) -> next level (experience) (cost in dollars)
     return string_format( cost > 0 ?  _( "%s: %d (%d%%) -> %d (%d%%) (cost $%d)" ) :
                           _( "%s: %d (%d%%) -> %d (%d%%)" ), skill.obj().name(), cur_level,
                           cur_level_exercise, next_level, next_level_exercise, cost / 100 );
 }
References _, calc_skill_training_cost_char(), talker::get_character(), Character::get_skill_level_object(), SkillLevel::knowledge_train(), SkillLevel::knowledgeExperience(), SkillLevel::knowledgeLevel(), me_chr_const, Skill::name(), string_id< T >::obj(), and string_format().
skills_offered_to()
std::vector< skill_id > talker_character_const::skills_offered_to (const talker & student) const override virtual
Reimplemented from talker.
Definition at line 1038 of file talker_character.cpp.
 {
     if( student.get_character() ) {
         return me_chr_const->skills_offered_to( student.get_character() );
     } else {
         return {};
     }
 }
References talker::get_character(), me_chr_const, and Character::skills_offered_to().
skills_teacheable()
std::vector< skill_id > talker_character_const::skills_teacheable () const override virtual
Reimplemented from talker.
Definition at line 1018 of file talker_character.cpp.
 {
     return me_chr_const->skills_offered_to( nullptr );
 }
References me_chr_const, and Character::skills_offered_to().
spell_seminar_text()
std::string talker_character_const::spell_seminar_text (const spell_id & s) const override virtual
Reimplemented from talker.
Definition at line 1175 of file talker_character.cpp.
 {
     return s->name.translated();
 }
References spell_type::name, and translation::translated().
spell_training_text()
std::string talker_character_const::spell_training_text (talker & student, const spell_id & sp) const override virtual
Reimplemented from talker.
Definition at line 1136 of file talker_character.cpp.
 {
     Character *pupil = student.get_character();
     if( !pupil ) {
         return "";
     }
     const spell &temp_spell = me_chr_const->magic->get_spell( sp );
     const bool knows = pupil->magic->knows_spell( sp );
     const int cost = me_chr_const->calc_spell_training_cost( knows, temp_spell.get_difficulty( *pupil ),
                      temp_spell.get_level() );
     std::string text;
     if( cost == 0 && ( !me_chr_const->is_npc() || me_chr_const->as_npc()->is_ally( *pupil ) ) ) {
         text = temp_spell.name();
     } else if( knows ) {
         text = string_format( _( "%s: 1 hour lesson (cost %s)" ), temp_spell.name(),
                               format_money( cost ) );
     } else {
         text = string_format( _( "%s: teaching spell knowledge (cost %s)" ),
                               temp_spell.name(), format_money( cost ) );
     }
     return text;
 }
References _, Creature::as_npc(), Character::calc_spell_training_cost(), format_money(), talker::get_character(), spell::get_difficulty(), spell::get_level(), npc::is_ally(), Character::is_npc(), Character::magic, me_chr_const, spell::name(), and string_format().
spells_offered_to()
std::vector< spell_id > talker_character_const::spells_offered_to (talker & student) const override virtual
Reimplemented from talker.
Definition at line 1127 of file talker_character.cpp.
 {
     if( student.get_character() ) {
         return me_chr_const->spells_offered_to( student.get_character() );
     } else {
         return {};
     }
 }
References talker::get_character(), me_chr_const, and Character::spells_offered_to().
spells_teacheable()
std::vector< spell_id > talker_character_const::spells_teacheable () const override virtual
Reimplemented from talker.
Definition at line 1033 of file talker_character.cpp.
 {
     return me_chr_const->spells_offered_to( nullptr );
 }
References me_chr_const, and Character::spells_offered_to().
str_cur()
int talker_character_const::str_cur () const override virtual
Reimplemented from talker.
Definition at line 105 of file talker_character.cpp.
 {
     return me_chr_const->str_cur;
 }
References me_chr_const, and Character::str_cur.
style_seminar_text()
std::string talker_character_const::style_seminar_text (const matype_id & m) const override virtual
Reimplemented from talker.
Definition at line 1170 of file talker_character.cpp.
 {
     return m->name.translated();
 }
References martialart::name, and translation::translated().
style_training_text()
std::string talker_character_const::style_training_text (const talker & student, const matype_id & style) const override virtual
Reimplemented from talker.
Definition at line 1114 of file talker_character.cpp.
 {
     if( !student.get_character() ) {
         return "";
     } else if( !me_chr_const->is_npc() ||
                me_chr_const->as_npc()->is_ally( *student.get_character() ) ) {
         return string_format( "%s", style.obj().name );
     } else {
         return string_format( _( "%s ( cost $%d )" ), style.obj().name, 8 );
     }
 }
References _, Creature::as_npc(), talker::get_character(), npc::is_ally(), Character::is_npc(), me_chr_const, martialart::name, string_id< T >::obj(), and string_format().
styles_offered_to()
std::vector< matype_id > talker_character_const::styles_offered_to (const talker & student) const override virtual
Reimplemented from talker.
Definition at line 1105 of file talker_character.cpp.
 {
     if( student.get_character() ) {
         return me_chr_const->styles_offered_to( student.get_character() );
     } else {
         return {};
     }
 }
References talker::get_character(), me_chr_const, and Character::styles_offered_to().
styles_teacheable()
std::vector< matype_id > talker_character_const::styles_teacheable () const override virtual
Reimplemented from talker.
Definition at line 1028 of file talker_character.cpp.
 {
     return me_chr_const->styles_offered_to( nullptr );
 }
References me_chr_const, and Character::styles_offered_to().
unarmed_attack()
bool talker_character_const::unarmed_attack () const override virtual
Reimplemented from talker.
Definition at line 588 of file talker_character.cpp.
 {
     return me_chr_const->unarmed_attack();
 }
References me_chr_const, and Character::unarmed_attack().
using_martial_art()
bool talker_character_const::using_martial_art (const matype_id & id) const override virtual
Reimplemented from talker.
Definition at line 1001 of file talker_character.cpp.
 {
     return me_chr_const->martial_arts_data->selected_style() == id;
 }
References base_camps::id, Character::martial_arts_data, and me_chr_const.
wielded_with_flag()
bool talker_character_const::wielded_with_flag (const flag_id & flag) const override virtual
Reimplemented from talker.
Definition at line 738 of file talker_character.cpp.
 {
     return me_chr_const->get_wielded_item() && me_chr_const->get_wielded_item()->has_flag( flag );
 }
References Character::get_wielded_item(), item::has_flag(), and me_chr_const.
wielded_with_weapon_category()
bool talker_character_const::wielded_with_weapon_category (const weapon_category_id & w_cat) const override virtual
Reimplemented from talker.
Definition at line 743 of file talker_character.cpp.
 {
     return me_chr_const->get_wielded_item() &&
            me_chr_const->get_wielded_item()->typeId()->weapon_category.count( w_cat ) > 0;
 }
References Character::get_wielded_item(), me_chr_const, item::typeId(), and itype::weapon_category.
worn_with_flag()
bool talker_character_const::worn_with_flag (const flag_id & flag, const bodypart_id & bp) const override virtual
Reimplemented from talker.
Definition at line 733 of file talker_character.cpp.
 {
     return me_chr_const->worn_with_flag( flag, bp );
 }
References bp, me_chr_const, and Character::worn_with_flag().
Member Data Documentation
me_chr_const
const Character* talker_character_const::me_chr_const protected
Definition at line 201 of file talker_character.h.
Referenced by armor_at(), attack_speed(), bodytype(), can_see(), can_see_location(), can_stash_weapon(), cash(), charges_of(), climate_control_str_chill(), climate_control_str_heat(), const_items_with(), coverage_at(), crossed_threshold(), dex_cur(), disp_name(), encumbrance_at(), focus_cur(), get_activity_level(), get_addiction_intensity(), get_addiction_turns(), get_age(), get_amount(), get_bmi_permil(), get_body_temp(), get_body_temp_delta(), get_character(), talker_character::get_character(), get_creature(), talker_character::get_creature(), get_cur_hp(), get_cur_part_temp(), get_dex_bonus(), get_dex_max(), get_effect(), get_faction(), get_fine_detail_vision_mod(), get_grammatical_genders(), get_health(), get_healthy_kcal(), get_height(), get_highest_spell_level(), get_hp_max(), get_hunger(), get_instant_thirst(), get_int_bonus(), get_int_max(), get_kill_xp(), get_move_mode(), get_name(), get_per_bonus(), get_per_max(), get_pkill(), get_rad(), get_size(), get_skill_exp(), get_skill_level(), get_sleep_deprivation(), get_sleepiness(), get_spell_count(), get_spell_exp(), get_spell_level(), get_spell_sum(), get_stamina(), get_stim(), get_stored_kcal(), get_str_bonus(), get_str_max(), get_thirst(), get_weight(), getID(), global_omt_location(), global_pos(), has_activity(), has_amount(), has_bionic(), has_charges(), has_effect(), has_flag(), has_item_with_flag(), has_max_power(), has_recipe(), has_species(), has_stolen_item(), has_trait(), int_cur(), is_deaf(), is_in_control_of(), is_male(), is_mounted(), is_mute(), is_wearing(), item_rads(), knows_martial_art(), knows_proficiency(), knows_spell(), mana_cur(), mana_max(), maybe_get_value(), morale_cur(), num_bionics(), pain_cur(), per_cur(), perceived_pain_cur(), pos(), posx(), posy(), posz(), power_cur(), power_max(), proficiencies_offered_to(), proficiencies_teacheable(), proficiency_practiced_time(), proficiency_training_text(), short_description(), skill_seminar_text(), skill_training_text(), skills_offered_to(), skills_teacheable(), spell_training_text(), spells_offered_to(), spells_teacheable(), str_cur(), style_training_text(), styles_offered_to(), styles_teacheable(), talker_avatar::talker_avatar(), talker_character::talker_character(), talker_npc::talker_npc(), unarmed_attack(), using_martial_art(), wielded_with_flag(), wielded_with_weapon_category(), and worn_with_flag().
The documentation for this class was generated from the following files:
src/talker_character.h
src/talker_character.cpp