Cataclysm DDA: cata_path Class Reference
cata_path Class Reference
One of the problems of filesystem paths is they lack contextual awareness of 'where' they are.
#include <cata_path.h>
Public Types
enum class root_path {
base , config , data , memorial ,
save , user , unknown
}
Public Member Functions
cata_path ()
template<typename T >
cata_path (root_path logical_root, T &&relative_path)
cata_path (const cata_path &)=default
cata_path & operator= (const cata_path &)=default
cata_path (cata_path &&)=default
cata_path & operator= (cata_path &&)=default
fs::path get_unrelative_path () const
operator fs::path () const
root_path get_logical_root () const
fs::path get_logical_root_path () const
const fs::path & get_relative_path () const
template<typename T >
cata_path operator/ (T &&segment) const
template<typename T >
cata_path & operator/= (T &&segment)
template<typename T >
cata_path operator+ (T &&segment)
template<typename T >
cata_path & operator+= (T &&segment)
cata_path lexically_normal () const
bool empty () const
bool operator== (const cata_path &rhs) const
cata_path parent_path () const
std::string generic_u8string () const
Static Private Member Functions
template<typename T >
static std::enable_if_t< std::is_same_v< std::decay_t< T >, fs::path >, T && > as_fs_path (T &&path)
template<typename T >
static std::enable_if_t< !std::is_same_v< std::decay_t< T >, fs::path >, fs::path > as_fs_path (T &&path)
Private Attributes
root_path logical_root_
fs::path relative_path_
Friends
template<class CharT , class Traits >
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &os, const cata_path &p)
Detailed Description
One of the problems of filesystem paths is they lack contextual awareness of 'where' they are.
They're just a list of segments pointing into the filesystem. There are cases where it's useful to have a path relative to some logical root which isn't the actual filesystem root, and work with / manipulate that path independently of the logical root.
cata_path combines a logical root concept and an fs::path. The logical root is an enum value containing well known cataclysm 'roots'. It only exposes operator / for concatenating segments to the relative path. The constructor requires passing a logical root value which can be queried, and when (explicitly) converting to fs::path will prepend the logical root with the relative path to give a final absolute path. Callers can know this absolute path is relative to the logical root without having to perform any further tests.
Attempting to construct a path that 'escapes' the logical root will result in a path rooted at the logical root, just like what happens if you try to resolve '/../'.
All string values are assumed to be utf-8 encoded, but fs::path values are used as-is without checking for encoding, so fs::u8path should be used if the path is utf-8 encoded.
Definition at line 33 of file cata_path.h.
Member Enumeration Documentation
root_path
enum cata_path::root_path strong
Enumerator
base
config
data
memorial
save
user
unknown
Definition at line 39 of file cata_path.h.
{
             base,
             config,
             data,
             memorial,
             save,
             user,
             unknown, // assumed relative to cwd, path is "."
             // fun fact: fs::path{} / "foo" == "foo", no "/foo".
         };
Constructor & Destructor Documentation
cata_path() [1/4]
cata_path::cata_path () inline
Definition at line 50 of file cata_path.h.
 : logical_root_{ root_path::unknown } {}
References unknown.
cata_path() [2/4]
template<typename T > cata_path::cata_path (root_path logical_root, T && relative_path) inline
Definition at line 53 of file cata_path.h.
                                                                : logical_root_{ logical_root },
             relative_path_{ as_fs_path( std::forward<T>( relative_path ) ) } { }
cata_path() [3/4]
cata_path::cata_path (const cata_path &) default
cata_path() [4/4]
cata_path::cata_path (cata_path &&) default
Member Function Documentation
as_fs_path() [1/2]
template<typename T > static std::enable_if_t< std::is_same_v<std::decay_t<T>, fs::path>, T && > cata_path::as_fs_path (T && path) inline static private
Definition at line 152 of file cata_path.h.
{
             return std::forward<T>( path );
         }
Referenced by operator+(), operator+=(), operator/(), and operator/=().
as_fs_path() [2/2]
template<typename T > static std::enable_if_t< !std::is_same_v<std::decay_t<T>, fs::path>, fs::path > cata_path::as_fs_path (T && path) inline static private
Definition at line 158 of file cata_path.h.
{
             return fs::u8path( std::forward<T>( path ) );
         }
empty()
bool cata_path::empty () const inline
Definition at line 123 of file cata_path.h.
{
             return logical_root_ == root_path::unknown && relative_path_.empty();
         }
References logical_root_, relative_path_, and unknown.
Referenced by leap_actor::call(), fire(), get_bar(), color_manager::load_custom(), normalize_relative_path(), iuse::radio_on(), and vehicle::turrets_aim_and_fire_single().
generic_u8string()
std::string cata_path::generic_u8string () const inline
Definition at line 142 of file cata_path.h.
{
             return get_unrelative_path().generic_u8string();
         }
References get_unrelative_path().
Referenced by DynamicDataLoader::add(), anonymous_namespace{json_loader.cpp}::cache_for_lexically_normal_path(), input_manager::load(), color_loader< ColorType >::load(), read_from_file_json(), color_manager::save_custom(), overmap::unserialize_omap(), mapbuffer::unserialize_submaps(), and write_to_file().
get_logical_root()
root_path cata_path::get_logical_root () const inline
Definition at line 75 of file cata_path.h.
{
             return logical_root_;
         }
References logical_root_.
Referenced by anonymous_namespace{json_loader.cpp}::cache_for_lexically_normal_path(), anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{json_loader.cpp}::from_path_at_offset_opt_impl().
get_logical_root_path()
fs::path cata_path::get_logical_root_path () const
Definition at line 595 of file path_info.cpp.
 {
     const std::string &path_value = ( []( cata_path::root_path root ) -> const std::string& {
         switch( root )
         {
             case cata_path::root_path::base:
                 return base_path_value;
             case cata_path::root_path::config:
                 return config_dir_value;
             case cata_path::root_path::data:
                 return datadir_value;
             case cata_path::root_path::memorial:
                 return memorialdir_value;
             case cata_path::root_path::save:
                 return savedir_value;
             case cata_path::root_path::user:
                 return user_dir_value;
             case cata_path::root_path::unknown:
             default: {
                 return STATIC( std::string() );
             }
         }
     } )( logical_root_ );
     return fs::u8path( path_value );
 }
References base, base_path_value, config, config_dir_value, data, datadir_value, logical_root_, memorial, memorialdir_value, save, savedir_value, STATIC, unknown, user, and user_dir_value.
Referenced by anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and get_unrelative_path().
get_relative_path()
const fs::path& cata_path::get_relative_path () const inline
Definition at line 84 of file cata_path.h.
{
             return relative_path_;
         }
References relative_path_.
Referenced by anonymous_namespace{json_loader.cpp}::cache_for_save(), and mod_manager::copy_mod_contents().
get_unrelative_path()
fs::path cata_path::get_unrelative_path () const inline
Definition at line 65 of file cata_path.h.
{
             fs::path result = get_logical_root_path();
             result /= relative_path_;
             return result;
         }
References get_logical_root_path(), and relative_path_.
Referenced by assure_dir_exist(), anonymous_namespace{main.cpp}::assure_essential_dirs_exist(), build_resource_list(), copy_file(), debug_menu::debug(), file_exist(), anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), anonymous_namespace{json_loader.cpp}::from_path_at_offset_opt_impl(), generic_u8string(), game::load(), DynamicDataLoader::load_data_from_path(), mod_manager::load_mods_from(), operator fs::path(), read_from_file(), read_from_file_optional(), read_from_file_optional_json(), read_maybe_compressed_file(), read_whole_file(), mod_manager::save_mods_list(), mapbuffer::save_quad(), debug_menu::vehicle_export(), and write_to_file().
lexically_normal()
cata_path cata_path::lexically_normal () const inline
Definition at line 117 of file cata_path.h.
{
             cata_path ret{ logical_root_, fs::path{} };
             ret.relative_path_ = relative_path_.lexically_normal();
             return ret;
         }
References logical_root_, relative_path_, and cata::hash64_detail::ret.
Referenced by anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{json_loader.cpp}::from_path_at_offset_opt_impl().
operator fs::path()
cata_path::operator fs::path () const inline explicit
Definition at line 71 of file cata_path.h.
{
             return get_unrelative_path();
         }
References get_unrelative_path().
operator+()
template<typename T > cata_path cata_path::operator+ (T && segment) inline
Definition at line 105 of file cata_path.h.
{
             cata_path ret = *this;
             ret += as_fs_path( std::forward<T>( segment ) );
             return ret;
         }
References as_fs_path(), and cata::hash64_detail::ret.
operator+=()
template<typename T > cata_path& cata_path::operator+= (T && segment) inline
Definition at line 112 of file cata_path.h.
{
             relative_path_ += as_fs_path( std::forward<T>( segment ) );
             return *this;
         }
References as_fs_path(), and relative_path_.
operator/()
template<typename T > cata_path cata_path::operator/ (T && segment) const inline
Definition at line 92 of file cata_path.h.
{
             cata_path ret = *this;
             ret /= as_fs_path( std::forward<T>( segment ) );
             return ret;
         }
References as_fs_path(), and cata::hash64_detail::ret.
operator/=()
template<typename T > cata_path& cata_path::operator/= (T && segment) inline
Definition at line 99 of file cata_path.h.
{
             relative_path_ /= as_fs_path( std::forward<T>( segment ) );
             return *this;
         }
References as_fs_path(), and relative_path_.
operator=() [1/2]
cata_path& cata_path::operator= (cata_path &&) default
operator=() [2/2]
cata_path& cata_path::operator= (const cata_path &) default
operator==()
bool cata_path::operator== (const cata_path & rhs) const inline
Definition at line 127 of file cata_path.h.
{
             return logical_root_ == rhs.logical_root_ && relative_path_ == rhs.relative_path_;
         }
References logical_root_, and relative_path_.
parent_path()
cata_path cata_path::parent_path () const inline
Definition at line 138 of file cata_path.h.
{
             return cata_path{ logical_root_, relative_path_.parent_path() };
         }
References logical_root_, and relative_path_.
Referenced by mod_manager::load_mod_info().
Friends And Related Function Documentation
operator<<
template<class CharT , class Traits > std::basic_ostream<CharT, Traits>& operator<< (std::basic_ostream< CharT, Traits > & os, const cata_path & p) friend
Definition at line 132 of file cata_path.h.
{
             os << p.get_unrelative_path();
             return os;
         }
Member Data Documentation
logical_root_
root_path cata_path::logical_root_ private
Definition at line 147 of file cata_path.h.
Referenced by empty(), get_logical_root(), get_logical_root_path(), lexically_normal(), operator==(), and parent_path().
relative_path_
fs::path cata_path::relative_path_ private
Definition at line 148 of file cata_path.h.
Referenced by empty(), get_relative_path(), get_unrelative_path(), lexically_normal(), operator+=(), operator/=(), operator==(), and parent_path().
The documentation for this class was generated from the following files:
src/cata_path.h
src/path_info.cpp