Cataclysm DDA: item_location::impl::item_on_vehicle Class Reference
item_location::impl::item_on_vehicle Class Reference
Public Member Functions
item_on_vehicle (const vehicle_cursor &cur, item *which)
item_on_vehicle (const vehicle_cursor &cur, int idx)
void serialize (JsonOut &js) const override
item * unpack (int idx) const override
type where () const override
tripoint position () const override
Character * carrier () const override
std::string describe (const Character *ch) const override
item_location obtain (Character &ch, int qty) override
int obtain_cost (const Character &ch, int qty) const override
void remove_item () override
void on_contents_changed () override
void make_active (item_location &head)
units::volume volume_capacity () const override
units::mass weight_capacity () const override
bool check_parent_capacity_recursive () const override
Public Member Functions inherited from item_location::impl
impl ()=default
impl (item *i)
impl (int idx)
virtual ~impl ()=default
virtual type where_recursive () const
virtual item_location parent_item () const
virtual item_pocket * parent_pocket () const
item * target () const
virtual bool valid () const
Private Attributes
vehicle_cursor cur
Additional Inherited Members
Public Attributes inherited from item_location::impl
bool should_stack = true
Detailed Description
Definition at line 456 of file item_location.cpp.
Constructor & Destructor Documentation
item_on_vehicle() [1/2]
item_location::impl::item_on_vehicle::item_on_vehicle (const vehicle_cursor & cur, item * which) inline
Definition at line 462 of file item_location.cpp.
 : impl( which ), cur( cur ) {}
item_on_vehicle() [2/2]
item_location::impl::item_on_vehicle::item_on_vehicle (const vehicle_cursor & cur, int idx) inline
Definition at line 463 of file item_location.cpp.
 : impl( idx ), cur( cur ) {}
Member Function Documentation
carrier()
Character* item_location::impl::item_on_vehicle::carrier () const inline override virtual
Implements item_location::impl.
Definition at line 488 of file item_location.cpp.
{
             return nullptr;
         }
check_parent_capacity_recursive()
bool item_location::impl::item_on_vehicle::check_parent_capacity_recursive () const inline override virtual
Implements item_location::impl.
Definition at line 565 of file item_location.cpp.
{
             return volume_capacity() >= 0_ml && weight_capacity() >= 0_gram;
         }
References volume_capacity(), and weight_capacity().
describe()
std::string item_location::impl::item_on_vehicle::describe (const Character * ch) const inline override virtual
Implements item_location::impl.
Definition at line 492 of file item_location.cpp.
{
             const vpart_position part_pos( cur.veh, cur.part );
             std::string res;
             if( const std::optional<std::string> label = part_pos.get_label() ) {
                 res = colorize( *label, c_light_blue ) + " ";
             }
             if( const std::optional<vpart_reference> cargo_part = part_pos.cargo() ) {
                 res += cargo_part->part().name();
             } else {
                 debugmsg( "item in vehicle part without cargo storage" );
             }
             if( ch ) {
                 res += " " + direction_suffix( ch->pos(), part_pos.pos() );
             }
             return res;
         }
References c_light_blue, vpart_position::cargo(), colorize(), cur, debugmsg, direction_suffix(), vpart_position::get_label(), vehicle_cursor::part, Creature::pos(), vpart_position::pos(), and vehicle_cursor::veh.
make_active()
void item_location::impl::item_on_vehicle::make_active (item_location & head) inline
Definition at line 553 of file item_location.cpp.
{
             cur.veh.make_active( head );
         }
References cur, vehicle::make_active(), and vehicle_cursor::veh.
obtain()
item_location item_location::impl::item_on_vehicle::obtain (Character & ch, int qty) inline override virtual
Implements item_location::impl.
Definition at line 509 of file item_location.cpp.
{
             ch.mod_moves( -obtain_cost( ch, qty ) );
             on_contents_changed();
             item obj = target()->split( qty );
             if( !obj.is_null() ) {
                 return ch.i_add( obj, should_stack );
             } else {
                 item_location inv = ch.i_add( *target(), should_stack, nullptr, target() );
                 remove_item();
                 return inv;
             }
         }
References Character::i_add(), item::is_null(), Creature::mod_moves(), obtain_cost(), on_contents_changed(), remove_item(), item_location::impl::should_stack, item::split(), and item_location::impl::target().
obtain_cost()
int item_location::impl::item_on_vehicle::obtain_cost (const Character & ch, int qty) const inline override virtual
Implements item_location::impl.
Definition at line 523 of file item_location.cpp.
{
             if( !target() ) {
                 return 0;
             }
             item *obj = target();
             int mv = ch.item_handling_cost( *obj, true, VEHICLE_HANDLING_PENALTY, qty );
             mv += 100 * rl_dist( ch.pos(), cur.veh.global_part_pos3( cur.part ) );
             // TODO: handle unpacking costs
             return mv;
         }
References cur, vehicle::global_part_pos3(), Character::item_handling_cost(), vehicle_cursor::part, Creature::pos(), rl_dist(), item_location::impl::target(), vehicle_cursor::veh, and VEHICLE_HANDLING_PENALTY.
Referenced by obtain().
on_contents_changed()
void item_location::impl::item_on_vehicle::on_contents_changed () inline override virtual
Implements item_location::impl.
Definition at line 548 of file item_location.cpp.
{
             target()->on_contents_changed();
             cur.veh.invalidate_mass();
         }
References cur, vehicle::invalidate_mass(), item::on_contents_changed(), item_location::impl::target(), and vehicle_cursor::veh.
Referenced by obtain(), and remove_item().
position()
tripoint item_location::impl::item_on_vehicle::position () const inline override virtual
Implements item_location::impl.
Definition at line 484 of file item_location.cpp.
{
             return cur.veh.global_part_pos3( cur.part );
         }
References cur, vehicle::global_part_pos3(), vehicle_cursor::part, and vehicle_cursor::veh.
Referenced by serialize().
remove_item()
void item_location::impl::item_on_vehicle::remove_item () inline override virtual
Implements item_location::impl.
Definition at line 537 of file item_location.cpp.
{
             on_contents_changed();
             vehicle_part &vp = cur.veh.part( cur.part );
             item &base = vp.base;
             if( &base == target() ) {
                 cur.veh.remove_part( vp ); // vehicle_part::base
             } else {
                 cur.remove_item( *target() ); // item within CARGO
             }
         }
References vehicle_part::base, cur, on_contents_changed(), vehicle::part(), vehicle_cursor::part, visitable::remove_item(), vehicle::remove_part(), item_location::impl::target(), and vehicle_cursor::veh.
Referenced by obtain().
serialize()
void item_location::impl::item_on_vehicle::serialize (JsonOut & js) const inline override virtual
Implements item_location::impl.
Definition at line 465 of file item_location.cpp.
{
             js.start_object();
             js.member( "type", "vehicle" );
             js.member( "pos", position() );
             js.member( "part", cur.part );
             if( target() != &cur.veh.part( cur.part ).base ) {
                 js.member( "idx", find_index( cur, target() ) );
             }
             js.end_object();
         }
References vehicle_part::base, cur, JsonOut::end_object(), find_index(), JsonOut::member(), vehicle::part(), vehicle_cursor::part, position(), JsonOut::start_object(), item_location::impl::target(), and vehicle_cursor::veh.
unpack()
item* item_location::impl::item_on_vehicle::unpack (int idx) const inline override virtual
Implements item_location::impl.
Definition at line 476 of file item_location.cpp.
{
             return idx >= 0 ? retrieve_index( cur, idx ) : &cur.veh.part( cur.part ).base;
         }
References vehicle_part::base, cur, item_location::impl::idx, vehicle::part(), vehicle_cursor::part, retrieve_index(), and vehicle_cursor::veh.
volume_capacity()
units::volume item_location::impl::item_on_vehicle::volume_capacity () const inline override virtual
Implements item_location::impl.
Definition at line 557 of file item_location.cpp.
{
             return vpart_reference( cur.veh, cur.part ).items().free_volume();
         }
References cur, item_stack::free_volume(), vpart_reference::items(), vehicle_cursor::part, and vehicle_cursor::veh.
Referenced by check_parent_capacity_recursive().
weight_capacity()
units::mass item_location::impl::item_on_vehicle::weight_capacity () const inline override virtual
Implements item_location::impl.
Definition at line 561 of file item_location.cpp.
{
             return units::mass_max;
         }
References units::mass_max.
Referenced by check_parent_capacity_recursive().
where()
type item_location::impl::item_on_vehicle::where () const inline override virtual
Implements item_location::impl.
Definition at line 480 of file item_location.cpp.
{
             return type::vehicle;
         }
References item_location::vehicle.
Member Data Documentation
cur
vehicle_cursor item_location::impl::item_on_vehicle::cur private
Definition at line 459 of file item_location.cpp.
Referenced by describe(), make_active(), obtain_cost(), on_contents_changed(), position(), remove_item(), serialize(), unpack(), and volume_capacity().
The documentation for this class was generated from the following file:
src/item_location.cpp