Cataclysm DDA: achievement Class Reference
achievement Class Reference
#include <achievement.h>
Classes
class time_bound
Public Member Functions
achievement ()=default
void load (const JsonObject &, std::string_view)
void check () const
const translation & name () const
const translation & description () const
bool is_conduct () const
const std::vector< achievement_id > & hidden_by () const
const std::optional< time_bound > & time_constraint () const
const std::vector< achievement_requirement > & requirements () const
bool is_manually_given () const
Static Public Member Functions
static void load_achievement (const JsonObject &, const std::string &)
static void finalize ()
static void check_consistency ()
static const std::vector< achievement > & get_all ()
static void reset ()
Public Attributes
achievement_id id
std::vector< std::pair< achievement_id, mod_id > > src
bool was_loaded = false
Private Attributes
translation name_
translation description_
bool is_conduct_ = false
bool manually_given_ = false
std::vector< achievement_id > hidden_by_
std::optional< time_bound > time_constraint_
std::vector< achievement_requirement > requirements_
Detailed Description
Definition at line 61 of file achievement.h.
Constructor & Destructor Documentation
achievement()
achievement::achievement () default
Member Function Documentation
check()
void achievement::check () const
Definition at line 444 of file achievement.cpp.
 {
     for( const achievement_id &a : hidden_by_ ) {
         if( !a.is_valid() ) {
             debugmsg( "Achievement %s specifies hidden_by achievement %s, but the latter does not "
                       "exist.", id.str(), a.str() );
             continue;
         }
         if( is_conduct() != a->is_conduct() ) {
             debugmsg( "Achievement %s is hidden by achievement %s, but one is a conduct and the "
                       "other is not.  This is not supported.", id.str(), a.str() );
         }
     }
     bool all_requirements_become_false = true;
     if( time_constraint_ ) {
         time_constraint_->check( id );
         all_requirements_become_false = time_constraint_->becomes_false();
     }
     for( const achievement_requirement &req : requirements_ ) {
         req.check( id );
         if( !req.becomes_false ) {
             all_requirements_become_false = false;
         }
     }
     // handled with debug mode or given by EOC
     if( is_manually_given() ) {
         all_requirements_become_false = false;
     }
     if( all_requirements_become_false && !is_conduct() ) {
         debugmsg( "All requirements for achievement %s become false, so this achievement will be "
                   "impossible or trivial", id.str() );
     }
     if( !all_requirements_become_false && is_conduct() ) {
         debugmsg( "All requirements for conduct %s must become false, but at least one does not",
                   id.str() );
     }
 }
References a, debugmsg, hidden_by_, is_conduct(), is_manually_given(), requirements_, and time_constraint_.
check_consistency()
void achievement::check_consistency () static
Definition at line 418 of file achievement.cpp.
 {
     achievement_factory.check();
 }
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::check_consistency().
description()
const translation& achievement::description () const inline
Definition at line 82 of file achievement.h.
{
             return description_;
         }
References description_.
Referenced by achievement_tracker::ui_text(), achievement_state::ui_text(), and achievements_tracker::ui_text_for().
finalize()
void achievement::finalize () static
Definition at line 409 of file achievement.cpp.
 {
     for( achievement &a : const_cast<std::vector<achievement>&>( achievement::get_all() ) ) {
         for( achievement_requirement &req : a.requirements_ ) {
             req.finalize();
         }
     }
 }
References a, achievement_requirement::finalize(), and get_all().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< achievement > & achievement::get_all () static
Definition at line 423 of file achievement.cpp.
 {
     return achievement_factory.get_all();
 }
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by finalize(), achievements_tracker::notify(), and achievements_tracker::valid_achievements().
hidden_by()
const std::vector<achievement_id>& achievement::hidden_by () const inline
Definition at line 90 of file achievement.h.
{
             return hidden_by_;
         }
References hidden_by_.
Referenced by achievements_tracker::is_hidden().
is_conduct()
bool achievement::is_conduct () const inline
Definition at line 86 of file achievement.h.
{
             return is_conduct_;
         }
References is_conduct_.
Referenced by check(), achievements_tracker::is_hidden(), achievement_tracker::set_requirement(), achievement_tracker::ui_text(), achievement::time_bound::ui_text(), and achievement_state::ui_text().
is_manually_given()
bool achievement::is_manually_given () const inline
Definition at line 124 of file achievement.h.
{
             return manually_given_;
         }
References manually_given_.
Referenced by check().
load()
void achievement::load (const JsonObject & jo, std::string_view)
Definition at line 433 of file achievement.cpp.
 {
     mandatory( jo, was_loaded, "name", name_ );
     is_conduct_ = jo.get_string( "type" ) == "conduct";
     optional( jo, was_loaded, "description", description_ );
     optional( jo, was_loaded, "hidden_by", hidden_by_ );
     optional( jo, was_loaded, "time_constraint", time_constraint_ );
     optional( jo, was_loaded, "manually_given", manually_given_ );
     mandatory( jo, was_loaded, "requirements", requirements_ );
 }
References description_, JsonObject::get_string(), hidden_by_, is_conduct_, mandatory, manually_given_, name_, optional(), requirements_, time_constraint_, and was_loaded.
load_achievement()
void achievement::load_achievement (const JsonObject & jo, const std::string & src) static
Definition at line 404 of file achievement.cpp.
 {
     achievement_factory.load( jo, src );
 }
References anonymous_namespace{achievement.cpp}::achievement_factory, and src.
Referenced by DynamicDataLoader::initialize().
name()
const translation& achievement::name () const inline
Definition at line 78 of file achievement.h.
{
             return name_;
         }
References name_.
Referenced by memorial_logger::notify(), achievement_tracker::ui_text(), and achievement_state::ui_text().
requirements()
const std::vector<achievement_requirement>& achievement::requirements () const inline
Definition at line 120 of file achievement.h.
{
             return requirements_;
         }
References requirements_.
Referenced by achievement_state::ui_text().
reset()
void achievement::reset () static
Definition at line 428 of file achievement.cpp.
 {
     achievement_factory.reset();
 }
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::unload_data().
time_constraint()
const std::optional<time_bound>& achievement::time_constraint () const inline
Definition at line 116 of file achievement.h.
{
             return time_constraint_;
         }
References time_constraint_.
Referenced by achievement_tracker::set_requirement(), achievement_tracker::time_is_expired(), achievement_tracker::ui_text(), and achievement_state::ui_text().
Member Data Documentation
description_
translation achievement::description_ private
Definition at line 130 of file achievement.h.
Referenced by description(), and load().
hidden_by_
std::vector<achievement_id> achievement::hidden_by_ private
Definition at line 134 of file achievement.h.
Referenced by check(), hidden_by(), and load().
id
achievement_id achievement::id
Definition at line 74 of file achievement.h.
Referenced by achievements_tracker::is_hidden(), achievement_tracker::ui_text(), and achievements_tracker::ui_text_for().
is_conduct_
bool achievement::is_conduct_ = false private
Definition at line 131 of file achievement.h.
Referenced by is_conduct(), and load().
manually_given_
bool achievement::manually_given_ = false private
Definition at line 133 of file achievement.h.
Referenced by is_manually_given(), and load().
name_
translation achievement::name_ private
Definition at line 129 of file achievement.h.
Referenced by load(), and name().
requirements_
std::vector<achievement_requirement> achievement::requirements_ private
Definition at line 136 of file achievement.h.
Referenced by check(), load(), and requirements().
src
std::vector<std::pair<achievement_id, mod_id> > achievement::src
Definition at line 75 of file achievement.h.
Referenced by load_achievement().
time_constraint_
std::optional<time_bound> achievement::time_constraint_ private
Definition at line 135 of file achievement.h.
Referenced by check(), load(), and time_constraint().
was_loaded
bool achievement::was_loaded = false
Definition at line 76 of file achievement.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/achievement.h
src/achievement.cpp