Cataclysm DDA: scenario Class Reference
scenario Class Reference
#include <scenario.h>
Public Member Functions
scenario ()
void check_definition () const
Check that item definitions are valid.
const string_id< scenario > & ident () const
std::string gender_appropriate_name (bool male) const
std::string description (bool male) const
start_location_id start_location () const
start_location_id random_start_location () const
std::string start_name () const
int start_location_count () const
int start_location_targets_count () const
std::optional< achievement_id > get_requirement () const
bool get_reveal_locale () const
void normalize_calendar () const
void reset_calendar () const
time_point start_of_cataclysm () const
time_point start_of_game () const
void change_start_of_cataclysm (const time_point &t) const
void change_start_of_game (const time_point &t) const
vproto_id vehicle () const
const profession * weighted_random_profession () const
std::vector< string_id< profession > > permitted_professions () const
std::vector< string_id< profession > > permitted_hobbies () const
bool traitquery (const trait_id &trait) const
std::set< trait_id > get_locked_traits () const
bool is_locked_trait (const trait_id &trait) const
bool is_forbidden_trait (const trait_id &trait) const
bool allowed_start (const start_location_id &loc) const
signed int point_cost () const
bool has_map_extra () const
const map_extra_id & get_map_extra () const
std::string prof_count_str () const
Returns "All", "Limited", or "Almost all" (translated) This is used by newcharacter.cpp.
bool scen_is_blacklisted () const
bool has_flag (const std::string &flag) const
Such as a seasonal start, fiery start, surrounded start, etc.
ret_val< void > can_pick () const
Do you have the necessary achievement state.
ret_val< void > can_afford (const scenario &current_scenario, int points) const
Do you have the points to afford swapping to this scenario.
const std::vector< mission_type_id > & missions () const
const std::vector< effect_on_condition_id > & eoc () const
const std::vector< std::pair< mongroup_id, float > > & surround_groups () const
Static Public Member Functions
static void load_scenario (const JsonObject &jo, const std::string &src)
static const scenario * generic ()
static const scenario * weighted_random ()
static const std::vector< scenario > & get_all ()
static void reset ()
static void finalize ()
calls check_definition for each scenario
Public Attributes
std::vector< std::pair< string_id< scenario >, mod_id > > src
Private Member Functions
void load (const JsonObject &jo, std::string_view src)
bool scenario_traits_conflict_with_profession_traits (const profession &p) const
Private Attributes
string_id< scenario > id
bool was_loaded = false
translation _name_male
translation _name_female
translation _description_male
translation _description_female
translation _start_name
bool blacklist = false
bool extra_professions = false
std::vector< string_id< profession > > professions
std::set< string_id< profession > > hobby_exclusion
bool hobbies_whitelist = true
std::vector< string_id< profession > > cached_permitted_professions
permitted_professions populates this vector on the first call, which takes a bit of work.
std::vector< string_id< profession > > cached_permitted_hobbies
std::set< trait_id > _allowed_traits
std::set< trait_id > _forced_traits
std::set< trait_id > _forbidden_traits
std::vector< start_location_id > _allowed_locs
int _point_cost = 0
std::set< std::string > flags
map_extra_id _map_extra
std::vector< mission_type_id > _missions
std::vector< effect_on_condition_id > _eoc
std::optional< achievement_id > _requirement
bool reveal_locale = true
time_point _default_start_of_cataclysm
time_point _default_start_of_game
time_point _start_of_cataclysm
time_point _start_of_game
vproto_id _starting_vehicle = vproto_id::NULL_ID()
std::vector< std::pair< mongroup_id, float > > _surround_groups
Friends
class string_id< scenario >
class generic_factory< scenario >
struct mod_tracker
Detailed Description
Definition at line 20 of file scenario.h.
Constructor & Destructor Documentation
scenario()
scenario::scenario ()
Definition at line 45 of file scenario.cpp.
     : id( "" ), _name_male( no_translation( "null" ) ),
       _name_female( no_translation( "null" ) ),
       _description_male( no_translation( "null" ) ),
       _description_female( no_translation( "null" ) )
 {
 }
Member Function Documentation
allowed_start()
bool scenario::allowed_start (const start_location_id & loc) const
Definition at line 639 of file scenario.cpp.
 {
     const auto &vec = _allowed_locs;
     return std::find( vec.begin(), vec.end(), loc ) != vec.end();
 }
References _allowed_locs.
can_afford()
ret_val< void > scenario::can_afford (const scenario & current_scenario, int points) const
Do you have the points to afford swapping to this scenario.
Definition at line 645 of file scenario.cpp.
 {
     if( point_cost() - current_scenario.point_cost() <= points ) {
         return ret_val<void>::make_success();
     }
     return ret_val<void>::make_failure( _( "You don't have enough points" ) );
 }
References _, ret_val< T >::make_failure(), ret_val< T >::make_success(), and point_cost().
can_pick()
ret_val< void > scenario::can_pick () const
Do you have the necessary achievement state.
Definition at line 655 of file scenario.cpp.
 {
     // if meta progression is disabled then skip this
     if( get_past_achievements().is_completed( achievement_achievement_arcade_mode ) ||
         !get_option<bool>( "META_PROGRESS" ) ) {
         return ret_val<void>::make_success();
     }
     if( _requirement ) {
         const bool has_req = get_past_achievements().is_completed(
                                  _requirement.value()->id );
         if( !has_req ) {
             return ret_val<void>::make_failure(
                        _( "You must complete the achievement \"%s\" to unlock this scenario." ),
                        _requirement.value()->name() );
         }
     }
     return ret_val<void>::make_success();
 }
References _, _requirement, achievement_achievement_arcade_mode, get_past_achievements(), past_achievements_info::is_completed(), ret_val< T >::make_failure(), and ret_val< T >::make_success().
Referenced by assemble_scenario_details().
change_start_of_cataclysm()
void scenario::change_start_of_cataclysm (const time_point & t) const
Definition at line 584 of file scenario.cpp.
 {
     scenario *hack = const_cast<scenario *>( this );
     hack->_start_of_cataclysm = t;
     hack->normalize_calendar();
 }
References _start_of_cataclysm, and normalize_calendar().
Referenced by set_description(), and set_scenario().
change_start_of_game()
void scenario::change_start_of_game (const time_point & t) const
Definition at line 591 of file scenario.cpp.
 {
     scenario *hack = const_cast<scenario *>( this );
     hack->_start_of_game = t;
     hack->normalize_calendar();
 }
References _start_of_game, and normalize_calendar().
Referenced by set_description(), and set_scenario().
check_definition()
void scenario::check_definition () const
Check that item definitions are valid.
Definition at line 233 of file scenario.cpp.
 {
     for( const auto &p : professions ) {
         if( !p.is_valid() ) {
             debugmsg( "profession %s for scenario %s does not exist", p.c_str(), id.c_str() );
         }
     }
     for( const string_id<profession> &hobby : hobby_exclusion ) {
         if( !hobby.is_valid() ) {
             debugmsg( "hobby %s for scenario %s does not exist", hobby.str(), id.str() );
         } else if( !hobby->is_hobby() ) {
             debugmsg( "hobby %s for scenario %s is a profession", hobby.str(), id.str() );
         }
     }
     std::unordered_set<string_id<profession>> professions_set;
     for( const auto &p : professions ) {
         if( professions_set.count( p ) == 1 ) {
             debugmsg( "Duplicate profession %s in scenario %s.", p.c_str(), this->id.c_str() );
         } else {
             professions_set.insert( p );
         }
     }
     for( const start_location_id &l : _allowed_locs ) {
         if( !l.is_valid() ) {
             debugmsg( "starting location %s for scenario %s does not exist", l.c_str(), id.c_str() );
         }
     }
     if( blacklist ) {
         if( professions.empty() ) {
             debugmsg( "Scenario %s: Use an empty whitelist to whitelist everything.", id.c_str() );
         } else {
             permitted_professions(); // Debug msg if every profession is blacklisted
         }
     }
     check_traits( _allowed_traits, id );
     check_traits( _forced_traits, id );
     check_traits( _forbidden_traits, id );
     if( !_map_extra.is_valid() )  {
         debugmsg( "there is no map extra with id %s", _map_extra.str() );
     }
     for( const auto &e : eoc() ) {
         if( !e.is_valid() ) {
             debugmsg( "effect on condition %s for scenario %s does not exist", e.c_str(), id.c_str() );
         }
     }
     for( const auto &m : _missions ) {
         if( !m.is_valid() ) {
             debugmsg( "starting mission %s for scenario %s does not exist", m.c_str(), id.c_str() );
         }
         if( std::find( m->origins.begin(), m->origins.end(), ORIGIN_GAME_START ) == m->origins.end() ) {
             debugmsg( "starting mission %s for scenario %s must include an origin of ORIGIN_GAME_START",
                       m.c_str(), id.c_str() );
         }
     }
     if( _starting_vehicle && !_starting_vehicle.is_valid() ) {
         debugmsg( "vehicle prototype %s for profession %s does not exist", _starting_vehicle.c_str(),
                   id.c_str() );
     }
 }
References _allowed_locs, _allowed_traits, _forbidden_traits, _forced_traits, _map_extra, _missions, _starting_vehicle, blacklist, string_id< T >::c_str(), check_traits(), debugmsg, eoc(), hobby_exclusion, string_id< T >::is_valid(), ORIGIN_GAME_START, permitted_professions(), professions, and string_id< T >::str().
description()
std::string scenario::description (bool male) const
Definition at line 317 of file scenario.cpp.
 {
     if( male ) {
         return _description_male.translated();
     } else {
         return _description_female.translated();
     }
 }
References _description_female, _description_male, male, and translation::translated().
Referenced by assemble_scenario_details().
eoc()
const std::vector< effect_on_condition_id > & scenario::eoc () const
Definition at line 688 of file scenario.cpp.
 {
     return _eoc;
 }
References _eoc.
Referenced by check_definition().
finalize()
void scenario::finalize () static
calls check_definition for each scenario
Definition at line 216 of file scenario.cpp.
 {
     for( const scenario &scen : all_scenarios.get_all() ) {
         scen.check_definition();
     }
     sc_blacklist.finalize();
 }
References anonymous_namespace{scenario.cpp}::all_scenarios, scen_blacklist::finalize(), and sc_blacklist.
Referenced by DynamicDataLoader::finalize_loaded_data().
gender_appropriate_name()
std::string scenario::gender_appropriate_name (bool male) const
Definition at line 308 of file scenario.cpp.
 {
     if( male ) {
         return _name_male.translated();
     } else {
         return _name_female.translated();
     }
 }
References _name_female, _name_male, male, and translation::translated().
Referenced by assemble_scenario_details().
generic()
const scenario * scenario::generic () static
Definition at line 162 of file scenario.cpp.
 {
     static const string_id<scenario> generic_scenario_id(
         get_option<std::string>( "GENERIC_SCENARIO_ID" ) );
     std::vector<const scenario *> all;
     for( const scenario &scen : scenario::get_all() ) {
         if( scen.scen_is_blacklisted() ) {
             continue;
         }
         all.push_back( &scen );
     }
     if( find_if( all.begin(), all.end(), []( const scenario * s ) {
     return s->ident() == generic_scenario_id;
     } ) != all.end() ) {
         // if the default scenario exists return it
         return &generic_scenario_id.obj();
     }
     // if generic doesn't exist just return to the first scenario
     return *all.begin();
 }
References om_direction::all, get_all(), and string_id< T >::obj().
Referenced by avatar::create(), and avatar::load().
get_all()
const std::vector< scenario > & scenario::get_all () static
Definition at line 206 of file scenario.cpp.
 {
     return all_scenarios.get_all();
 }
References anonymous_namespace{scenario.cpp}::all_scenarios.
Referenced by scen_blacklist::finalize(), generic(), avatar::randomize(), and set_scenario().
get_locked_traits()
std::set< trait_id > scenario::get_locked_traits () const
Definition at line 619 of file scenario.cpp.
 {
     return _forced_traits;
 }
References _forced_traits.
Referenced by scenario_traits_conflict_with_profession_traits(), and set_traits().
get_map_extra()
const map_extra_id & scenario::get_map_extra () const
Definition at line 680 of file scenario.cpp.
 {
     return _map_extra;
 }
References _map_extra.
Referenced by game::start_game().
get_requirement()
std::optional< achievement_id > scenario::get_requirement () const
Definition at line 554 of file scenario.cpp.
 {
     return _requirement;
 }
References _requirement.
Referenced by assemble_scenario_details().
get_reveal_locale()
bool scenario::get_reveal_locale () const
Definition at line 559 of file scenario.cpp.
 {
     return reveal_locale;
 }
References reveal_locale.
has_flag()
bool scenario::has_flag (const std::string & flag) const
Such as a seasonal start, fiery start, surrounded start, etc.
Definition at line 634 of file scenario.cpp.
 {
     return flags.count( flag ) != 0;
 }
References flags.
Referenced by assemble_scenario_details(), and game::start_game().
has_map_extra()
bool scenario::has_map_extra () const
Definition at line 676 of file scenario.cpp.
 {
     return !_map_extra.is_null();
 }
References _map_extra, and string_id< T >::is_null().
Referenced by game::start_game().
ident()
const string_id< scenario > & scenario::ident () const
Definition at line 303 of file scenario.cpp.
 {
     return id;
 }
References id.
Referenced by avatar::load(), and permitted_professions().
is_forbidden_trait()
bool scenario::is_forbidden_trait (const trait_id & trait) const
Definition at line 629 of file scenario.cpp.
 {
     return _forbidden_traits.count( trait ) != 0;
 }
References _forbidden_traits.
Referenced by scenario_traits_conflict_with_profession_traits(), and traitquery().
is_locked_trait()
bool scenario::is_locked_trait (const trait_id & trait) const
Definition at line 624 of file scenario.cpp.
 {
     return _forced_traits.count( trait ) != 0;
 }
References _forced_traits.
Referenced by scenario_traits_conflict_with_profession_traits(), trait_points_used(), and traitquery().
load()
void scenario::load (const JsonObject & jo, std::string_view src) private
Definition at line 59 of file scenario.cpp.
 {
     // TODO: pretty much the same as in profession::load, but different contexts for pgettext.
     // TODO: maybe combine somehow?
     if( !was_loaded || jo.has_string( "name" ) ) {
         // These may differ depending on the language settings!
         const std::string name = jo.get_string( "name" );
         _name_female = to_translation( "scenario_female", name );
         _name_male = to_translation( "scenario_male", name );
     }
     if( !was_loaded || jo.has_string( "description" ) ) {
         // These also may differ depending on the language settings!
         std::string desc;
         mandatory( jo, false, "description", desc, text_style_check_reader() );
         _description_male = to_translation( "scen_desc_male", desc );
         _description_female = to_translation( "scen_desc_female", desc );
     }
     if( !was_loaded || jo.has_string( "start_name" ) ) {
         // Specifying translation context here and above to avoid adding unnecessary json code for every scenario
         // NOLINTNEXTLINE(cata-json-translation-input)
         _start_name = to_translation( "start_name", jo.get_string( "start_name" ) );
     }
     mandatory( jo, was_loaded, "points", _point_cost );
     optional( jo, was_loaded, "blacklist_professions", blacklist );
     optional( jo, was_loaded, "add_professions", extra_professions );
     optional( jo, was_loaded, "professions", professions, string_id_reader<::profession> {} );
     optional( jo, was_loaded, "hobbies", hobby_exclusion );
     optional( jo, was_loaded, "whitelist_hobbies", hobbies_whitelist, true );
     optional( jo, was_loaded, "traits", _allowed_traits, string_id_reader<::mutation_branch> {} );
     optional( jo, was_loaded, "forced_traits", _forced_traits, string_id_reader<::mutation_branch> {} );
     optional( jo, was_loaded, "forbidden_traits", _forbidden_traits,
               string_id_reader<::mutation_branch> {} );
     optional( jo, was_loaded, "allowed_locs", _allowed_locs, string_id_reader<::start_location> {} );
     if( _allowed_locs.empty() ) {
         jo.throw_error( "at least one starting location (member \"allowed_locs\") must be defined" );
     }
     optional( jo, was_loaded, "flags", flags, auto_flags_reader<> {} );
     optional( jo, was_loaded, "map_extra", _map_extra, map_extra_id::NULL_ID() );
     optional( jo, was_loaded, "missions", _missions, string_id_reader<::mission_type> {} );
     optional( jo, was_loaded, "requirement", _requirement );
     optional( jo, was_loaded, "reveal_locale", reveal_locale, true );
     optional( jo, was_loaded, "eoc", _eoc, auto_flags_reader<effect_on_condition_id> {} );
     if( !was_loaded ) {
         int _start_of_cataclysm_hour = 0;
         int _start_of_cataclysm_day = 61;
         season_type _start_of_cataclysm_season = SPRING;
         int _start_of_cataclysm_year = 1;
         if( jo.has_member( "start_of_cataclysm" ) ) {
             JsonObject jocid = jo.get_member( "start_of_cataclysm" );
             optional( jocid, was_loaded, "hour", _start_of_cataclysm_hour );
             optional( jocid, was_loaded, "day", _start_of_cataclysm_day );
             optional( jocid, was_loaded, "season", _start_of_cataclysm_season );
             optional( jocid, was_loaded, "year", _start_of_cataclysm_year );
         }
         _default_start_of_cataclysm = calendar::turn_zero +
                                       1_hours * _start_of_cataclysm_hour +
                                       1_days * ( _start_of_cataclysm_day - 1 ) +
                                       1_days * get_option<int>( "SEASON_LENGTH" ) * _start_of_cataclysm_season +
                                       calendar::year_length() * ( _start_of_cataclysm_year - 1 )
                                       ;
         int _start_of_game_hour = 8;
         int _start_of_game_day = 61;
         season_type _start_of_game_season = SPRING;
         int _start_of_game_year = 1;
         if( jo.has_member( "start_of_game" ) ) {
             JsonObject jocid = jo.get_member( "start_of_game" );
             optional( jocid, was_loaded, "hour", _start_of_game_hour );
             optional( jocid, was_loaded, "day", _start_of_game_day );
             optional( jocid, was_loaded, "season", _start_of_game_season );
             optional( jocid, was_loaded, "year", _start_of_game_year );
         }
         _default_start_of_game = calendar::turn_zero +
                                  1_hours * _start_of_game_hour +
                                  1_days * ( _start_of_game_day - 1 ) +
                                  1_days * get_option<int>( "SEASON_LENGTH" ) * _start_of_game_season +
                                  calendar::year_length() * ( _start_of_game_year - 1 )
                                  ;
         reset_calendar();
     }
     if( jo.has_string( "vehicle" ) ) {
         _starting_vehicle = vproto_id( jo.get_string( "vehicle" ) );
     }
     for( JsonArray ja : jo.get_array( "surround_groups" ) ) {
         _surround_groups.emplace_back( mongroup_id( ja.get_string( 0 ) ),
                                        static_cast<float>( ja.get_float( 1 ) ) );
     }
 }
References _allowed_locs, _allowed_traits, _default_start_of_cataclysm, _default_start_of_game, _description_female, _description_male, _eoc, _forbidden_traits, _forced_traits, _map_extra, _missions, _name_female, _name_male, _point_cost, _requirement, _start_name, _starting_vehicle, _surround_groups, blacklist, extra_professions, flags, JsonObject::get_array(), JsonObject::get_member(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_string(), hobbies_whitelist, hobby_exclusion, mandatory, mongroup_id, om_direction::name(), string_id< map_extra >::NULL_ID(), optional(), professions, reset_calendar(), reveal_locale, SPRING, JsonObject::throw_error(), to_translation(), calendar::turn_zero, was_loaded, and calendar::year_length().
load_scenario()
void scenario::load_scenario (const JsonObject & jo, const std::string & src) static
Definition at line 54 of file scenario.cpp.
 {
     all_scenarios.load( jo, src );
 }
References anonymous_namespace{scenario.cpp}::all_scenarios, and src.
Referenced by DynamicDataLoader::initialize().
missions()
const std::vector< mission_type_id > & scenario::missions () const
Definition at line 684 of file scenario.cpp.
 {
     return _missions;
 }
References _missions.
Referenced by assemble_scenario_details(), and game::start_game().
normalize_calendar()
void scenario::normalize_calendar () const
Definition at line 564 of file scenario.cpp.
 {
     scenario *hack = const_cast<scenario *>( this );
     // We don't currently allow to start game before cataclysm
     if( hack->_default_start_of_game < hack->_default_start_of_cataclysm ) {
         hack->_default_start_of_game = hack->_default_start_of_cataclysm;
     }
     if( hack->_start_of_game < hack->_start_of_cataclysm ) {
         hack->_start_of_game = hack->_start_of_cataclysm;
     }
 }
References _default_start_of_cataclysm, _default_start_of_game, _start_of_cataclysm, and _start_of_game.
Referenced by change_start_of_cataclysm(), change_start_of_game(), and reset_calendar().
permitted_hobbies()
std::vector< string_id< profession > > scenario::permitted_hobbies () const
Definition at line 449 of file scenario.cpp.
 {
     if( !cached_permitted_hobbies.empty() ) {
         return cached_permitted_hobbies;
     }
     std::vector<string_id<profession>> all = profession::get_all_hobbies();
     std::vector<string_id<profession>> &res = cached_permitted_hobbies;
     for( const string_id<profession> &hobby : all ) {
         if( hobby->is_blacklisted() ) {
             continue;
         }
         if( scenario_traits_conflict_with_profession_traits( *hobby ) ) {
             continue;
         }
         if( !hobbies_whitelist && hobby_exclusion.count( hobby ) != 0 ) {
             continue;
         }
         if( hobbies_whitelist && !hobby_exclusion.empty() && hobby_exclusion.count( hobby ) == 0 ) {
             continue;
         }
         res.push_back( hobby );
     }
     if( res.empty() ) {
         debugmsg( "Why would you blacklist every hobby?" );
         res.insert( res.end(), all.begin(), all.end() );
     }
     return res;
 }
References om_direction::all, cached_permitted_hobbies, debugmsg, profession::get_all_hobbies(), hobbies_whitelist, hobby_exclusion, and scenario_traits_conflict_with_profession_traits().
Referenced by avatar::randomize_hobbies(), and set_hobbies().
permitted_professions()
std::vector< string_id< profession > > scenario::permitted_professions () const
Definition at line 407 of file scenario.cpp.
 {
     if( !cached_permitted_professions.empty() ) {
         return cached_permitted_professions;
     }
     const std::vector<profession> &all = profession::get_all();
     std::vector<string_id<profession>> &res = cached_permitted_professions;
     for( const profession &p : all ) {
         if( p.is_hobby() || p.is_blacklisted() ) {
             continue;
         }
         const bool present = std::find( professions.begin(), professions.end(),
                                         p.ident() ) != professions.end();
         bool conflicting_traits = scenario_traits_conflict_with_profession_traits( p );
         if( blacklist || professions.empty() ) {
             if( !present && !p.has_flag( "SCEN_ONLY" ) && !conflicting_traits ) {
                 res.push_back( p.ident() );
             }
         } else if( present ) {
             if( !conflicting_traits ) {
                 res.push_back( p.ident() );
             } else {
                 debugmsg( "Scenario %s and profession %s have conflicting trait requirements",
                           id.c_str(), p.ident().c_str() );
             }
         } else if( extra_professions ) {
             if( !p.has_flag( "SCEN_ONLY" ) && !conflicting_traits ) {
                 res.push_back( p.ident() );
             }
         }
     }
     if( res.empty() ) {
         debugmsg( "Why would you blacklist every profession?" );
         res.push_back( profession::generic()->ident() );
     }
     return res;
 }
References om_direction::all, blacklist, cached_permitted_professions, debugmsg, extra_professions, profession::generic(), profession::get_all(), ident(), professions, and scenario_traits_conflict_with_profession_traits().
Referenced by assemble_scenario_details(), check_definition(), reset_scenario(), set_profession(), and weighted_random_profession().
point_cost()
signed int scenario::point_cost () const
Definition at line 326 of file scenario.cpp.
 {
     return _point_cost;
 }
References _point_cost.
Referenced by can_afford(), set_scenario(), skill_points_used(), and weighted_random().
prof_count_str()
std::string scenario::prof_count_str () const
Returns "All", "Limited", or "Almost all" (translated) This is used by newcharacter.cpp.
Definition at line 527 of file scenario.cpp.
 {
     if( professions.empty() ) {
         return _( "All" );
     }
     return blacklist ? _( "Almost all" ) : _( "Limited" );
 }
References _, blacklist, and professions.
Referenced by assemble_scenario_details().
random_start_location()
start_location_id scenario::random_start_location () const
Definition at line 335 of file scenario.cpp.
 {
     return random_entry( _allowed_locs );
 }
References _allowed_locs, and random_entry().
Referenced by avatar::load(), and game::start_game().
reset()
void scenario::reset () static
Definition at line 211 of file scenario.cpp.
 {
     all_scenarios.reset();
 }
References anonymous_namespace{scenario.cpp}::all_scenarios.
Referenced by DynamicDataLoader::unload_data().
reset_calendar()
void scenario::reset_calendar () const
Definition at line 576 of file scenario.cpp.
 {
     scenario *hack = const_cast<scenario *>( this );
     hack->_start_of_cataclysm = _default_start_of_cataclysm;
     hack->_start_of_game = _default_start_of_game;
     hack->normalize_calendar();
 }
References _default_start_of_cataclysm, _default_start_of_game, _start_of_cataclysm, _start_of_game, and normalize_calendar().
Referenced by load(), set_description(), and set_scenario().
scen_is_blacklisted()
bool scenario::scen_is_blacklisted () const
Definition at line 340 of file scenario.cpp.
 {
     return sc_blacklist.scenarios.count( id ) != 0;
 }
References sc_blacklist, and scen_blacklist::scenarios.
scenario_traits_conflict_with_profession_traits()
bool scenario::scenario_traits_conflict_with_profession_traits (const profession & p) const private
Definition at line 482 of file scenario.cpp.
 {
     for( const auto &pt : p.get_forbidden_traits() ) {
         if( is_locked_trait( pt ) ) {
             return true;
         }
     }
     for( trait_and_var &pt : p.get_locked_traits() ) {
         if( is_forbidden_trait( pt.trait ) ) {
             return true;
         }
     }
     //  check if:
     //  locked traits for scenario prevent taking locked traits for professions
     //  locked traits for professions prevent taking locked traits for scenario
     for( const trait_id &st : get_locked_traits() ) {
         for( trait_and_var &pt : p.get_locked_traits() ) {
             if( are_conflicting_traits( st, pt.trait ) || are_conflicting_traits( pt.trait, st ) ) {
                 return true;
             }
         }
     }
     return false;
 }
References are_conflicting_traits(), profession::get_forbidden_traits(), profession::get_locked_traits(), get_locked_traits(), is_forbidden_trait(), and is_locked_trait().
Referenced by permitted_hobbies(), and permitted_professions().
start_location()
start_location_id scenario::start_location () const
Definition at line 331 of file scenario.cpp.
 {
     return _allowed_locs.front();
 }
References _allowed_locs.
Referenced by char_creation::draw_location().
start_location_count()
int scenario::start_location_count () const
Definition at line 540 of file scenario.cpp.
 {
     return _allowed_locs.size();
 }
References _allowed_locs.
Referenced by assemble_scenario_details().
start_location_targets_count()
int scenario::start_location_targets_count () const
Definition at line 545 of file scenario.cpp.
 {
     int cnt = 0;
     for( const auto &sloc : _allowed_locs ) {
         cnt += sloc.obj().targets_count();
     }
     return cnt;
 }
References _allowed_locs.
Referenced by assemble_scenario_details().
start_name()
std::string scenario::start_name () const
Definition at line 535 of file scenario.cpp.
 {
     return _start_name.translated();
 }
References _start_name, and translation::translated().
Referenced by assemble_scenario_details().
start_of_cataclysm()
time_point scenario::start_of_cataclysm () const
Definition at line 598 of file scenario.cpp.
 {
     return _start_of_cataclysm;
 }
References _start_of_cataclysm.
Referenced by assemble_scenario_details(), set_description(), set_scenario(), and game::start_calendar().
start_of_game()
time_point scenario::start_of_game () const
Definition at line 603 of file scenario.cpp.
 {
     return _start_of_game;
 }
References _start_of_game.
Referenced by assemble_scenario_details(), set_description(), set_scenario(), and game::start_calendar().
surround_groups()
const std::vector< std::pair< mongroup_id, float > > & scenario::surround_groups () const
Definition at line 692 of file scenario.cpp.
 {
     return _surround_groups;
 }
References _surround_groups.
Referenced by game::start_game().
traitquery()
bool scenario::traitquery (const trait_id & trait) const
Definition at line 613 of file scenario.cpp.
 {
     return _allowed_traits.count( trait ) != 0 || is_locked_trait( trait ) ||
            ( !is_forbidden_trait( trait ) && trait->startingtrait );
 }
References _allowed_traits, is_forbidden_trait(), is_locked_trait(), and mutation_branch::startingtrait.
vehicle()
vproto_id scenario::vehicle () const
Definition at line 608 of file scenario.cpp.
 {
     return _starting_vehicle;
 }
References _starting_vehicle.
Referenced by assemble_scenario_details(), avatar::initialize(), and set_description().
weighted_random()
const scenario * scenario::weighted_random () static
Definition at line 189 of file scenario.cpp.
 {
     if( one_in( 3 ) ) {
         return generic();
     }
     const auto &list = all_scenarios.get_all();
     while( true ) {
         const scenario &scen = random_entry_ref( list );
         if( x_in_y( 2, std::abs( scen.point_cost() ) + 2 ) ) {
             return &scen;
         }
         // else reroll in the while loop.
     }
 }
References abs(), anonymous_namespace{scenario.cpp}::all_scenarios, one_in(), point_cost(), random_entry_ref(), and x_in_y().
weighted_random_profession()
const profession * scenario::weighted_random_profession () const
Definition at line 509 of file scenario.cpp.
 {
     // Strategy: 1/3 of the time, return the generic profession (if it's permitted).
     // Otherwise, the weight of each permitted profession is 2 / ( |point cost| + 2 )
     const auto choices = permitted_professions();
     if( one_in( 3 ) && choices.front() == profession::generic()->ident() ) {
         return profession::generic();
     }
     while( true ) {
         const string_id<profession> &candidate = random_entry_ref( choices );
         if( candidate->can_pick().success() && x_in_y( 2, 2 + std::abs( candidate->point_cost() ) ) ) {
             return &candidate.obj();
         }
     }
     return profession::generic(); // Suppress warnings
 }
References abs(), profession::can_pick(), profession::generic(), profession::ident(), string_id< T >::obj(), one_in(), permitted_professions(), profession::point_cost(), random_entry_ref(), ret_val_common::success(), and x_in_y().
Referenced by avatar::randomize().
Friends And Related Function Documentation
generic_factory< scenario >
friend class generic_factory< scenario > friend
Definition at line 173 of file scenario.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 25 of file scenario.h.
string_id< scenario >
friend class string_id< scenario > friend
Definition at line 173 of file scenario.h.
Member Data Documentation
_allowed_locs
std::vector<start_location_id> scenario::_allowed_locs private
Definition at line 52 of file scenario.h.
Referenced by allowed_start(), check_definition(), load(), random_start_location(), start_location(), start_location_count(), and start_location_targets_count().
_allowed_traits
std::set<trait_id> scenario::_allowed_traits private
Definition at line 49 of file scenario.h.
Referenced by check_definition(), load(), and traitquery().
_default_start_of_cataclysm
time_point scenario::_default_start_of_cataclysm private
Definition at line 64 of file scenario.h.
Referenced by load(), normalize_calendar(), and reset_calendar().
_default_start_of_game
time_point scenario::_default_start_of_game private
Definition at line 65 of file scenario.h.
Referenced by load(), normalize_calendar(), and reset_calendar().
_description_female
translation scenario::_description_female private
Definition at line 31 of file scenario.h.
Referenced by description(), and load().
_description_male
translation scenario::_description_male private
Definition at line 30 of file scenario.h.
Referenced by description(), and load().
_eoc
std::vector<effect_on_condition_id> scenario::_eoc private
Definition at line 57 of file scenario.h.
Referenced by eoc(), and load().
_forbidden_traits
std::set<trait_id> scenario::_forbidden_traits private
Definition at line 51 of file scenario.h.
Referenced by check_definition(), is_forbidden_trait(), and load().
_forced_traits
std::set<trait_id> scenario::_forced_traits private
Definition at line 50 of file scenario.h.
Referenced by check_definition(), get_locked_traits(), is_locked_trait(), and load().
_map_extra
map_extra_id scenario::_map_extra private
Definition at line 55 of file scenario.h.
Referenced by check_definition(), get_map_extra(), has_map_extra(), and load().
_missions
std::vector<mission_type_id> scenario::_missions private
Definition at line 56 of file scenario.h.
Referenced by check_definition(), load(), and missions().
_name_female
translation scenario::_name_female private
Definition at line 29 of file scenario.h.
Referenced by gender_appropriate_name(), and load().
_name_male
translation scenario::_name_male private
Definition at line 28 of file scenario.h.
Referenced by gender_appropriate_name(), and load().
_point_cost
int scenario::_point_cost = 0 private
Definition at line 53 of file scenario.h.
Referenced by load(), and point_cost().
_requirement
std::optional<achievement_id> scenario::_requirement private
Definition at line 60 of file scenario.h.
Referenced by can_pick(), get_requirement(), and load().
_start_name
translation scenario::_start_name private
Definition at line 32 of file scenario.h.
Referenced by load(), and start_name().
_start_of_cataclysm
time_point scenario::_start_of_cataclysm private
Definition at line 67 of file scenario.h.
Referenced by change_start_of_cataclysm(), normalize_calendar(), reset_calendar(), and start_of_cataclysm().
_start_of_game
time_point scenario::_start_of_game private
Definition at line 68 of file scenario.h.
Referenced by change_start_of_game(), normalize_calendar(), reset_calendar(), and start_of_game().
_starting_vehicle
vproto_id scenario::_starting_vehicle = vproto_id::NULL_ID() private
Definition at line 70 of file scenario.h.
Referenced by check_definition(), load(), and vehicle().
_surround_groups
std::vector<std::pair<mongroup_id, float> > scenario::_surround_groups private
Definition at line 72 of file scenario.h.
Referenced by load(), and surround_groups().
blacklist
bool scenario::blacklist = false private
Definition at line 34 of file scenario.h.
Referenced by check_definition(), load(), permitted_professions(), and prof_count_str().
cached_permitted_hobbies
std::vector<string_id<profession> > scenario::cached_permitted_hobbies mutable private
Definition at line 47 of file scenario.h.
Referenced by permitted_hobbies().
cached_permitted_professions
std::vector<string_id<profession> > scenario::cached_permitted_professions mutable private
permitted_professions populates this vector on the first call, which takes a bit of work.
On subsequent calls, this vector is returned.
Definition at line 46 of file scenario.h.
Referenced by permitted_professions().
extra_professions
bool scenario::extra_professions = false private
Definition at line 35 of file scenario.h.
Referenced by load(), and permitted_professions().
flags
std::set<std::string> scenario::flags private
Definition at line 54 of file scenario.h.
Referenced by has_flag(), and load().
hobbies_whitelist
bool scenario::hobbies_whitelist = true private
Definition at line 40 of file scenario.h.
Referenced by load(), and permitted_hobbies().
hobby_exclusion
std::set<string_id<profession> > scenario::hobby_exclusion private
Definition at line 39 of file scenario.h.
Referenced by check_definition(), load(), and permitted_hobbies().
id
string_id<scenario> scenario::id private
Definition at line 26 of file scenario.h.
Referenced by ident().
professions
std::vector<string_id<profession> > scenario::professions private
Definition at line 36 of file scenario.h.
Referenced by check_definition(), load(), permitted_professions(), and prof_count_str().
reveal_locale
bool scenario::reveal_locale = true private
Definition at line 62 of file scenario.h.
Referenced by get_reveal_locale(), and load().
src
std::vector<std::pair<string_id<scenario>, mod_id> > scenario::src
Definition at line 158 of file scenario.h.
Referenced by assemble_scenario_details(), and load_scenario().
was_loaded
bool scenario::was_loaded = false private
Definition at line 27 of file scenario.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/scenario.h
src/scenario.cpp