Cataclysm DDA: query_destination_callback Class Reference
query_destination_callback Class Reference
Public Member Functions
query_destination_callback (advanced_inventory &adv_inv)
void refresh (uilist *menu) override
Public Member Functions inherited from uilist_callback
virtual void select (uilist *)
After a new item is selected, call this once.
virtual bool key (const input_context &, const input_event &, int, uilist *)
virtual ~uilist_callback ()=default
Private Member Functions
void draw_squares (const uilist *menu)
Private Attributes
advanced_inventory & _adv_inv
Detailed Description
Definition at line 2043 of file advanced_inv.cpp.
Constructor & Destructor Documentation
query_destination_callback()
query_destination_callback::query_destination_callback (advanced_inventory & adv_inv) inline explicit
Definition at line 2050 of file advanced_inv.cpp.
 : _adv_inv( adv_inv ) {}
Member Function Documentation
draw_squares()
void query_destination_callback::draw_squares (const uilist * menu) private
Definition at line 2056 of file advanced_inv.cpp.
 {
     cata_assert( menu->entries.size() >= 9 );
     int ofs = -25 - 4;
     int sel = 0;
     if( menu->selected >= 0 && static_cast<size_t>( menu->selected ) < menu->entries.size() ) {
         sel = _adv_inv.screen_relative_location(
                   static_cast <aim_location>( menu->selected + 1 ) );
     }
     for( int i = 1; i < 10; i++ ) {
         aim_location loc = _adv_inv.screen_relative_location( static_cast <aim_location>( i ) );
         std::string key = _adv_inv.get_location_key( loc );
         advanced_inv_area &square = _adv_inv.get_one_square( loc );
         bool in_vehicle = square.can_store_in_vehicle();
         const char *bracket = in_vehicle ? "<>" : "[]";
         // always show storage option for vehicle storage, if applicable
         bool canputitems = menu->entries[i - 1].enabled && square.canputitems();
         nc_color bcolor = canputitems ? sel == loc ? h_white : c_light_gray : c_red;
         nc_color kcolor = canputitems ? sel == loc ? h_white : c_dark_gray : c_red;
         const point p( square.hscreen + point( ofs, 5 ) );
         mvwprintz( menu->window, p, bcolor, "%c", bracket[0] );
         wprintz( menu->window, kcolor, "%s", key );
         wprintz( menu->window, bcolor, "%c", bracket[1] );
     }
     wnoutrefresh( menu->window );
 }
References _adv_inv, c_dark_gray, c_light_gray, c_red, cata_assert, uilist::entries, advanced_inventory::get_location_key(), advanced_inventory::get_one_square(), h_white, uilist_callback::key(), mvwprintz(), advanced_inventory::screen_relative_location(), uilist::selected, square(), uilist::window, catacurses::wnoutrefresh(), and wprintz().
Referenced by refresh().
refresh()
void query_destination_callback::refresh (uilist * menu) inline override virtual
Reimplemented from uilist_callback.
Definition at line 2051 of file advanced_inv.cpp.
{
             draw_squares( menu );
         }
References draw_squares().
Member Data Documentation
_adv_inv
advanced_inventory& query_destination_callback::_adv_inv private
Definition at line 2046 of file advanced_inv.cpp.
Referenced by draw_squares().
The documentation for this class was generated from the following file:
src/advanced_inv.cpp