Cataclysm DDA: generic_factory< T > Class Template Reference
generic_factory< T > Class Template Reference
#include <generic_factory.h>
Classes
struct T_has_handle_inheritance
struct T_has_handle_inheritance< U, std::void_t< T_has_handle_inheritance_t< U > > >
class Version
Wrapper around generic_factory::version.
Public Types
template<typename U >
using T_has_handle_inheritance_t = decltype(std::declval< U >().handle_inheritance(std::declval< const T & >(), std::declval< const std::unordered_map< std::string, T > & >()))
Public Member Functions
virtual ~generic_factory ()=default
generic_factory (const std::string &type_name, const std::string &id_member_name="id", const std::string &alias_member_name="alias")
template<typename U = T, std::enable_if_t< T_has_handle_inheritance< U >::value > * = nullptr>
void handle_inheritance_on_T (T &def, const T &copy_from)
template<typename U = T, std::enable_if_t<!T_has_handle_inheritance< U >::value > * = nullptr>
void handle_inheritance_on_T (T &def, const T &copy_from)
bool handle_inheritance (T &def, const JsonObject &jo, const std::string &src)
Perform JSON inheritance handling for T def and returns true if JsonObject is real.
void load (const JsonObject &jo, const std::string &src)
Load an object of type T with the data from the given JSON object.
T & insert (const T &obj)
Add an object to the factory, without loading from JSON.
virtual void finalize ()
Finalize all entries (derived classes should chain to this method)
void check () const
Checks loaded/inserted objects for consistency.
size_t size () const
Returns the number of loaded objects.
bool empty () const
Returns whether factory is empty.
void reset ()
Removes all loaded objects.
const std::vector< T > & get_all () const
Returns all the loaded objects.
Version get_version ()
bool is_valid (const Version &v)
<tt>string_id/int_id</tt> interface functions
The functions here are supposed to be used by the id classes, they have the same behavior as described in the id classes and can be used directly by forwarding the parameters to them and returning their result.
const T & obj (const int_id< T > &id) const
Returns the object with the given id.
const T & obj (const string_id< T > &id) const
Returns the object with the given id.
bool is_valid (const int_id< T > &id) const
Checks whether the factory contains an object with the given id.
bool is_valid (const string_id< T > &id) const
Checks whether the factory contains an object with the given id.
int_id< T > convert (const string_id< T > &id, const int_id< T > &null_id, const bool warn=true) const
Converts string_id<T> to int_id<T>.
const string_id< T > & convert (const int_id< T > &id) const
Converts int_id<T> to string_id<T>.
Public Attributes
const bool initialized
Protected Member Functions
bool find_id (const string_id< T > &id, int_id< T > &result) const
void remove_aliases (const string_id< T > &id)
Protected Attributes
std::vector< T > list
std::unordered_map< string_id< T >, int_id< T > > map
std::unordered_map< std::string, T > abstracts
std::string type_name
std::string id_member_name
std::string alias_member_name
const std::string legacy_id_member_name = "ident"
const T dummy_obj
Private Member Functions
void inc_version ()
Private Attributes
DynamicDataLoader::deferred_json deferred
int64_t version = 0
Detailed Description
template<typename T>
class generic_factory< T >
Definition at line 119 of file generic_factory.h.
Member Typedef Documentation
T_has_handle_inheritance_t
template<typename T > template<typename U > using generic_factory< T >::T_has_handle_inheritance_t = decltype(std::declval<U>().handle_inheritance(std::declval<const T &>(), std::declval<const std::unordered_map<std::string, T>&>()))
Definition at line 210 of file generic_factory.h.
Constructor & Destructor Documentation
~generic_factory()
template<typename T > virtual generic_factory< T >::~generic_factory () virtual default
generic_factory()
template<typename T > generic_factory< T >::generic_factory (const std::string & type_name, const std::string & id_member_name = "id", const std::string & alias_member_name = "alias") inline explicit
Parameters
type_name A string used in debug messages as the name of T, for example "vehicle type".
id_member_name The name of the JSON member that contains the id(s) of the loaded object(s).
alias_member_name Alternate names of the JSON member that contains the id(s) of the loaded object alias(es).
Definition at line 195 of file generic_factory.h.
             : type_name( type_name ),
               id_member_name( id_member_name ),
               alias_member_name( alias_member_name ),
               dummy_obj(),
               initialized( true ) {
         }
Member Function Documentation
check()
template<typename T > void generic_factory< T >::check () const inline
Checks loaded/inserted objects for consistency.
Definition at line 413 of file generic_factory.h.
{
             for( const T &obj : list ) {
                 obj.check();
             }
         }
References generic_factory< T >::list, and generic_factory< T >::obj().
convert() [1/2]
template<typename T > const string_id<T>& generic_factory< T >::convert (const int_id< T > & id) const inline
Converts int_id<T> to string_id<T>.
Returns null_id on failure.
Definition at line 520 of file generic_factory.h.
{
             return obj( id ).id;
         }
References generic_factory< T >::obj().
convert() [2/2]
template<typename T > int_id<T> generic_factory< T >::convert (const string_id< T > & id, const int_id< T > & null_id, const bool warn = true) const inline
Converts string_id<T> to int_id<T>.
Returns null_id on failure. When optional flag warn is true, issues a warning if id is not found and null_id was returned.
Definition at line 506 of file generic_factory.h.
{
             int_id<T> result;
             if( find_id( id, result ) ) {
                 return result;
             }
             if( warn ) {
                 debugmsg( "invalid %s id \"%s\"", type_name, id.c_str() );
             }
             return null_id;
         }
References debugmsg, generic_factory< T >::find_id(), and generic_factory< T >::type_name.
empty()
template<typename T > bool generic_factory< T >::empty () const inline
Returns whether factory is empty.
Definition at line 427 of file generic_factory.h.
{
             return list.empty();
         }
References generic_factory< T >::list.
finalize()
template<typename T > virtual void generic_factory< T >::finalize () inline virtual
Finalize all entries (derived classes should chain to this method)
Definition at line 400 of file generic_factory.h.
{
             DynamicDataLoader::get_instance().load_deferred( deferred );
             abstracts.clear();
             inc_version();
             for( size_t i = 0; i < list.size(); i++ ) {
                 list[i].id.set_cid_version( static_cast<int>( i ), version );
             }
         }
References generic_factory< T >::abstracts, generic_factory< T >::deferred, DynamicDataLoader::get_instance(), generic_factory< T >::inc_version(), generic_factory< T >::list, DynamicDataLoader::load_deferred(), and generic_factory< T >::version.
find_id()
template<typename T > bool generic_factory< T >::find_id (const string_id< T > & id, int_id< T > & result) const inline protected
Definition at line 150 of file generic_factory.h.
{
             if( id._version == version ) {
                 result = int_id<T>( id._cid );
                 return is_valid( result );
             }
             const auto iter = map.find( id );
             // map lookup happens at most once per string_id instance per generic_factory::version
             // id was not found, explicitly marking it as "invalid"
             if( iter == map.end() ) {
                 id.set_cid_version( INVALID_CID, version );
                 return false;
             }
             result = iter->second;
             id.set_cid_version( result.to_i(), version );
             return true;
         }
References INVALID_CID, generic_factory< T >::is_valid(), int_id< T >::to_i(), and generic_factory< T >::version.
Referenced by generic_factory< T >::convert(), generic_factory< T >::is_valid(), generic_factory< T >::obj(), and generic_factory< T >::remove_aliases().
get_all()
template<typename T > const std::vector<T>& generic_factory< T >::get_all () const inline
Returns all the loaded objects.
It can be used to iterate over them.
Definition at line 447 of file generic_factory.h.
{
             return list;
         }
References generic_factory< T >::list.
get_version()
template<typename T > Version generic_factory< T >::get_version () inline
Definition at line 548 of file generic_factory.h.
{
             return Version( version );
         }
References generic_factory< T >::version.
handle_inheritance()
template<typename T > bool generic_factory< T >::handle_inheritance (T & def, const JsonObject & jo, const std::string & src) inline
Perform JSON inheritance handling for T def and returns true if JsonObject is real.
If the object contains a "copy-from" member the corresponding abstract gets copied if found. If abstract is not found, object is added to deferred. If the object is abstract, it is loaded via T::load and added to abstracts
Returns
true if jo is loaded and false if loading is deferred.
Exceptions
JsonError If jo is both abstract and real. (contains "abstract" and "id" members)
Definition at line 240 of file generic_factory.h.
{
             static const std::string copy_from_member_name( "copy-from" );
             static const std::string abstract_member_name( "abstract" );
             if( jo.has_string( copy_from_member_name ) ) {
                 const std::string source = jo.get_string( copy_from_member_name );
                 auto base = map.find( string_id<T>( source ) );
                 if( base != map.end() ) {
                     const T &base_obj = obj( base->second );
                     handle_inheritance_on_T( def, base_obj );
                 } else {
                     auto ab = abstracts.find( source );
                     if( ab != abstracts.end() ) {
                         const T &base_obj = ab->second;
                         handle_inheritance_on_T( def, base_obj );
                     } else {
                         def.was_loaded = false;
                         deferred.emplace_back( jo, src );
                         jo.allow_omitted_members();
                         return false;
                     }
                 }
                 def.was_loaded = true;
             }
             if( jo.has_string( abstract_member_name ) ) {
                 if( jo.has_string( id_member_name ) || jo.has_string( legacy_id_member_name ) ) {
                     jo.throw_error( string_format( "cannot specify both '%s' and '%s'/'%s'",
                                                    abstract_member_name, id_member_name, legacy_id_member_name ) );
                 }
                 restore_on_out_of_scope<check_plural_t> restore_check_plural( check_plural );
                 check_plural = check_plural_t::none;
                 const std::string abstract_id =  jo.get_string( abstract_member_name );
                 def.id = string_id<T>( abstract_id );
                 def.load( jo, src );
                 abstracts[abstract_id] = def;
             }
             return true;
         }
References generic_factory< T >::abstracts, JsonObject::allow_omitted_members(), check_plural, generic_factory< T >::deferred, JsonObject::get_string(), generic_factory< T >::handle_inheritance_on_T(), JsonObject::has_string(), generic_factory< T >::id_member_name, generic_factory< T >::legacy_id_member_name, none, generic_factory< T >::obj(), string_format(), and JsonObject::throw_error().
Referenced by generic_factory< T >::load().
handle_inheritance_on_T() [1/2]
template<typename T > template<typename U = T, std::enable_if_t< T_has_handle_inheritance< U >::value > * = nullptr> void generic_factory< T >::handle_inheritance_on_T (T & def, const T & copy_from) inline
Definition at line 220 of file generic_factory.h.
{
             def.handle_inheritance( copy_from, abstracts ); // let the function handle it
         }
References generic_factory< T >::abstracts.
Referenced by generic_factory< T >::handle_inheritance().
handle_inheritance_on_T() [2/2]
template<typename T > template<typename U = T, std::enable_if_t<!T_has_handle_inheritance< U >::value > * = nullptr> void generic_factory< T >::handle_inheritance_on_T (T & def, const T & copy_from) inline
Definition at line 224 of file generic_factory.h.
{
             def = copy_from; // just use assignment
         }
inc_version()
template<typename T > void generic_factory< T >::inc_version () inline private
Definition at line 133 of file generic_factory.h.
{
             do {
                 version++;
             } while( version == INVALID_VERSION );
         }
References INVALID_VERSION, and generic_factory< T >::version.
Referenced by generic_factory< T >::finalize(), generic_factory< T >::insert(), and generic_factory< T >::reset().
insert()
template<typename T > T& generic_factory< T >::insert (const T & obj) inline
Add an object to the factory, without loading from JSON.
The new object replaces any existing object of the same id. The function returns the actual object reference.
Definition at line 374 of file generic_factory.h.
{
             // this invalidates `_cid` cache for all previously added string_ids,
             // but! it's necessary to invalidate cache for all possibly cached "missed" lookups
             // (lookups for not-yet-inserted elements)
             // in the common scenario there is no loss of performance, as `finalize` will make cache
             // for all ids valid again
             inc_version();
             const auto iter = map.find( obj.id );
             if( iter != map.end() ) {
                 mod_tracker::check_duplicate_entries( obj, list[iter->second.to_i()] );
                 T &result = list[iter->second.to_i()];
                 result = obj;
                 result.id.set_cid_version( iter->second.to_i(), version );
                 return result;
             }
             const int_id<T> cid( list.size() );
             list.push_back( obj );
             T &result = list.back();
             result.id.set_cid_version( cid.to_i(), version );
             map[result.id] = cid;
             return result;
         }
References mod_tracker::check_duplicate_entries(), generic_factory< T >::inc_version(), generic_factory< T >::list, generic_factory< T >::obj(), int_id< T >::to_i(), and generic_factory< T >::version.
Referenced by generic_factory< T >::load().
is_valid() [1/3]
template<typename T > bool generic_factory< T >::is_valid (const int_id< T > & id) const inline
Checks whether the factory contains an object with the given id.
This function can be used to implement int_id::is_valid().
Definition at line 491 of file generic_factory.h.
{
             return static_cast<size_t>( id.to_i() ) < list.size();
         }
References generic_factory< T >::list.
Referenced by generic_factory< T >::find_id(), and generic_factory< T >::obj().
is_valid() [2/3]
template<typename T > bool generic_factory< T >::is_valid (const string_id< T > & id) const inline
Checks whether the factory contains an object with the given id.
This function can be used to implement string_id::is_valid().
Definition at line 498 of file generic_factory.h.
{
             int_id<T> dummy;
             return find_id( id, dummy );
         }
References generic_factory< T >::find_id().
is_valid() [3/3]
template<typename T > bool generic_factory< T >::is_valid (const Version & v) inline
Definition at line 553 of file generic_factory.h.
{
             return v.version == version;
         }
References generic_factory< T >::version, and generic_factory< T >::Version::version.
load()
template<typename T > void generic_factory< T >::load (const JsonObject & jo, const std::string & src) inline
Load an object of type T with the data from the given JSON object.
The id of the object is taken from the JSON object. The object data is loaded by calling T::load(jo) (either on a new object or on an existing object). See class documentation for intended behavior of that function.
Exceptions
JsonError If loading fails for any reason (thrown by T::load).
Definition at line 290 of file generic_factory.h.
{
             bool strict = src == "dda";
             static const std::string abstract_member_name( "abstract" );
             T def;
             if( !handle_inheritance( def, jo, src ) ) {
                 return;
             }
             if( jo.has_string( id_member_name ) ) {
                 def.id = string_id<T>( jo.get_string( id_member_name ) );
                 mod_tracker::assign_src( def, src );
                 def.load( jo, src );
                 insert( def );
                 if( jo.has_member( alias_member_name ) ) {
                     std::set<string_id<T>> aliases;
                     assign( jo, alias_member_name, aliases, strict );
                     const int_id<T> ref = map[def.id];
                     for( const auto &e : aliases ) {
                         map[e] = ref;
                     }
                 }
             } else if( jo.has_array( id_member_name ) ) {
                 for( JsonValue e : jo.get_array( id_member_name ) ) {
                     T def;
                     if( !handle_inheritance( def, jo, src ) ) {
                         break;
                     }
                     def.id = string_id<T>( e );
                     mod_tracker::assign_src( def, src );
                     def.load( jo, src );
                     insert( def );
                 }
                 if( jo.has_member( alias_member_name ) ) {
                     jo.throw_error( string_format( "can not specify '%s' when '%s' is array",
                                                    alias_member_name, id_member_name ) );
                 }
             } else if( jo.has_string( legacy_id_member_name ) ) {
                 def.id = string_id<T>( jo.get_string( legacy_id_member_name ) );
                 mod_tracker::assign_src( def, src );
                 def.load( jo, src );
                 insert( def );
                 if( jo.has_member( alias_member_name ) ) {
                     std::set<string_id<T>> aliases;
                     assign( jo, alias_member_name, aliases, strict );
                     const int_id<T> ref = map[def.id];
                     for( const auto &e : aliases ) {
                         map[e] = ref;
                     }
                 }
             } else if( jo.has_array( legacy_id_member_name ) ) {
                 for( const JsonValue e : jo.get_array( legacy_id_member_name ) ) {
                     T def;
                     if( !handle_inheritance( def, jo, src ) ) {
                         break;
                     }
                     def.id = string_id<T>( e );
                     mod_tracker::assign_src( def, src );
                     def.load( jo, src );
                     insert( def );
                 }
                 if( jo.has_member( alias_member_name ) ) {
                     jo.throw_error( string_format( "can not specify '%s' when '%s' is array",
                                                    alias_member_name, legacy_id_member_name ) );
                 }
             } else if( !jo.has_string( abstract_member_name ) ) {
                 jo.throw_error( string_format( "must specify either '%s' or '%s'/'%s'",
                                                abstract_member_name, id_member_name, legacy_id_member_name ) );
             }
         }
References generic_factory< T >::alias_member_name, assign(), mod_tracker::assign_src(), JsonObject::get_array(), JsonObject::get_string(), generic_factory< T >::handle_inheritance(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), int_id< T >::id(), generic_factory< T >::id_member_name, generic_factory< T >::insert(), generic_factory< T >::legacy_id_member_name, strict, string_format(), and JsonObject::throw_error().
obj() [1/2]
template<typename T > const T& generic_factory< T >::obj (const int_id< T > & id) const inline
Returns the object with the given id.
The input id should be valid, otherwise a debug message is issued. This function can be used to implement int_id::obj(). Note: If the id was valid, the returned object can be modified (after casting the const away).
Definition at line 465 of file generic_factory.h.
{
             if( !is_valid( id ) ) {
                 debugmsg( "invalid %s id \"%d\"", type_name, id.to_i() );
                 return dummy_obj;
             }
             return list[id.to_i()];
         }
References debugmsg, generic_factory< T >::dummy_obj, generic_factory< T >::is_valid(), generic_factory< T >::list, and generic_factory< T >::type_name.
Referenced by generic_factory< T >::check(), generic_factory< T >::convert(), generic_factory< T >::handle_inheritance(), and generic_factory< T >::insert().
obj() [2/2]
template<typename T > const T& generic_factory< T >::obj (const string_id< T > & id) const inline
Returns the object with the given id.
The input id should be valid, otherwise a debug message is issued. This function can be used to implement string_id::obj(). Note: If the id was valid, the returned object can be modified (after casting the const away).
Definition at line 479 of file generic_factory.h.
{
             int_id<T> i_id;
             if( !find_id( id, i_id ) ) {
                 debugmsg( "invalid %s id \"%s\"", type_name, id.c_str() );
                 return dummy_obj;
             }
             return list[i_id.to_i()];
         }
References debugmsg, generic_factory< T >::dummy_obj, generic_factory< T >::find_id(), generic_factory< T >::list, int_id< T >::to_i(), and generic_factory< T >::type_name.
remove_aliases()
template<typename T > void generic_factory< T >::remove_aliases (const string_id< T > & id) inline protected
Definition at line 167 of file generic_factory.h.
{
             int_id<T> i_id;
             if( !find_id( id, i_id ) ) {
                 return;
             }
             auto iter = map.begin();
             const auto end = map.end();
             while( iter != end ) {
                 if( iter->second == i_id && iter->first != id ) {
                     map.erase( iter++ );
                 } else {
                     ++iter;
                 }
             }
         }
References keycode::end, and generic_factory< T >::find_id().
reset()
template<typename T > void generic_factory< T >::reset () inline
Removes all loaded objects.
Postcondition: size() == 0
Definition at line 434 of file generic_factory.h.
                      {
             /* Avoid unvisited member errors when iterating on json */
             for( std::pair<JsonObject, std::string> &deferred_json : deferred ) {
                 deferred_json.first.allow_omitted_members();
             }
             deferred.clear();
             list.clear();
             map.clear();
             inc_version();
         }
References generic_factory< T >::deferred, generic_factory< T >::inc_version(), and generic_factory< T >::list.
size()
template<typename T > size_t generic_factory< T >::size () const inline
Returns the number of loaded objects.
Definition at line 421 of file generic_factory.h.
{
             return list.size();
         }
References generic_factory< T >::list.
Member Data Documentation
abstracts
template<typename T > std::unordered_map<std::string, T> generic_factory< T >::abstracts protected
Definition at line 142 of file generic_factory.h.
Referenced by generic_factory< T >::finalize(), generic_factory< T >::handle_inheritance(), and generic_factory< T >::handle_inheritance_on_T().
alias_member_name
template<typename T > std::string generic_factory< T >::alias_member_name protected
Definition at line 146 of file generic_factory.h.
Referenced by generic_factory< T >::load().
deferred
template<typename T > DynamicDataLoader::deferred_json generic_factory< T >::deferred private
Definition at line 126 of file generic_factory.h.
Referenced by generic_factory< T >::finalize(), generic_factory< T >::handle_inheritance(), and generic_factory< T >::reset().
dummy_obj
template<typename T > const T generic_factory< T >::dummy_obj protected
Definition at line 183 of file generic_factory.h.
Referenced by generic_factory< T >::obj().
id_member_name
template<typename T > std::string generic_factory< T >::id_member_name protected
Definition at line 145 of file generic_factory.h.
Referenced by generic_factory< T >::handle_inheritance(), and generic_factory< T >::load().
initialized
template<typename T > const bool generic_factory< T >::initialized
Definition at line 186 of file generic_factory.h.
legacy_id_member_name
template<typename T > const std::string generic_factory< T >::legacy_id_member_name = "ident" protected
Definition at line 148 of file generic_factory.h.
Referenced by generic_factory< T >::handle_inheritance(), and generic_factory< T >::load().
list
template<typename T > std::vector<T> generic_factory< T >::list protected
Definition at line 140 of file generic_factory.h.
Referenced by generic_factory< T >::check(), generic_factory< T >::empty(), generic_factory< T >::finalize(), generic_factory< T >::get_all(), generic_factory< T >::insert(), generic_factory< T >::is_valid(), generic_factory< T >::obj(), generic_factory< T >::reset(), and generic_factory< T >::size().
map
template<typename T > std::unordered_map<string_id<T>, int_id<T> > generic_factory< T >::map protected
Definition at line 141 of file generic_factory.h.
type_name
template<typename T > std::string generic_factory< T >::type_name protected
Definition at line 144 of file generic_factory.h.
Referenced by generic_factory< T >::convert(), and generic_factory< T >::obj().
version
template<typename T > int64_t generic_factory< T >::version = 0 private
Definition at line 131 of file generic_factory.h.
Referenced by generic_factory< T >::finalize(), generic_factory< T >::find_id(), generic_factory< T >::get_version(), generic_factory< T >::inc_version(), generic_factory< T >::insert(), and generic_factory< T >::is_valid().
The documentation for this class was generated from the following files:
src/ammo_effect.h
src/generic_factory.h