Cataclysm DDA: VehicleFunction_json Class Reference
VehicleFunction_json Class Reference
#include <vehicle_group.h>
Public Member Functions
VehicleFunction_json (const JsonObject &jo)
~VehicleFunction_json () override=default
void apply (map &m, const std::string &terrain_name) const override
This will invoke the vehicle spawning function on the map.
Public Member Functions inherited from VehicleFunction
virtual ~VehicleFunction ()=default
Private Attributes
vgroup_id vehicle
jmapgen_int number
int fuel
int status
std::string placement
std::optional< VehicleLocation > location
Detailed Description
Definition at line 133 of file vehicle_group.h.
Constructor & Destructor Documentation
VehicleFunction_json()
VehicleFunction_json::VehicleFunction_json (const JsonObject & jo) explicit
Definition at line 129 of file vehicle_group.cpp.
     : vehicle( jo.get_string( "vehicle" ) ),
       number( jo, "number" ),
       fuel( jo.get_int( "fuel" ) ),
       status( jo.get_int( "status" ) )
 {
     if( jo.has_string( "placement" ) ) {
         placement = jo.get_string( "placement" );
     } else {
         VehicleFacings facings( jo, "facing" );
         location.emplace( jmapgen_int( jo, "x" ), jmapgen_int( jo, "y" ), facings );
     }
 }
References JsonObject::get_string(), JsonObject::has_string(), location, placement, and status.
~VehicleFunction_json()
VehicleFunction_json::~VehicleFunction_json () override default
Member Function Documentation
apply()
void VehicleFunction_json::apply (map & m, const std::string & terrain_name) const override virtual
This will invoke the vehicle spawning function on the map.
Parameters
m The map on which to add the vehicle.
terrain_name The name of the terrain being spawned on. This is ignored by the json handler.
Implements VehicleFunction.
Definition at line 143 of file vehicle_group.cpp.
 {
     for( int i = number.get(); i > 0; i-- ) {
         if( !location ) {
             const size_t replace = placement.find( "%t" );
             const VehicleLocation *loc = vplacement_id( replace != std::string::npos ?
                                          placement.substr( 0, replace ) + terrain_name +
                                          placement.substr( replace + 2 ) :
                                          placement ).obj().pick();
             if( !loc ) {
                 debugmsg( "vehiclefunction_json: unable to get location to place vehicle." );
                 return;
             }
             const tripoint pos = tripoint( loc->pick_point(), m.get_abs_sub().z() );
             m.add_vehicle( vehicle->pick(), pos, loc->pick_facing(), fuel, status );
         } else {
             const tripoint pos = tripoint( location->pick_point(), m.get_abs_sub().z() );
             m.add_vehicle( vehicle->pick(), pos, location->pick_facing(), fuel, status );
         }
     }
 }
References map::add_vehicle(), debugmsg, fuel, jmapgen_int::get(), map::get_abs_sub(), location, number, VehicleLocation::pick_facing(), VehicleLocation::pick_point(), placement, math_opers::pos(), status, tripoint, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Member Data Documentation
fuel
int VehicleFunction_json::fuel private
Definition at line 149 of file vehicle_group.h.
Referenced by apply().
location
std::optional<VehicleLocation> VehicleFunction_json::location private
Definition at line 153 of file vehicle_group.h.
Referenced by apply(), and VehicleFunction_json().
number
jmapgen_int VehicleFunction_json::number private
Definition at line 148 of file vehicle_group.h.
Referenced by apply().
placement
std::string VehicleFunction_json::placement private
Definition at line 152 of file vehicle_group.h.
Referenced by apply(), and VehicleFunction_json().
status
int VehicleFunction_json::status private
Definition at line 150 of file vehicle_group.h.
Referenced by apply().
vehicle
vgroup_id VehicleFunction_json::vehicle private
Definition at line 147 of file vehicle_group.h.
The documentation for this class was generated from the following files:
src/vehicle_group.h
src/vehicle_group.cpp