Cataclysm DDA: joins_tracker Class Reference
joins_tracker Class Reference
Classes
struct compare_iterators
struct indexed_joins
struct join
Public Types
enum class join_status {
disallowed , matched_available , matched_non_available , mismatched_available ,
free
}
using iterator = std::list< join >::iterator
using const_iterator = std::list< join >::const_iterator
Public Member Functions
bool any_unresolved () const
std::vector< const join * > all_unresolved_at (const tripoint_om_omt &pos) const
std::size_t count_unresolved_at (const tripoint_om_omt &pos) const
bool any_postponed () const
bool any_postponed_at (const tripoint_om_omt &p) const
void consistency_check () const
join_status allows (const om_pos_dir &this_side, const mutable_overmap_terrain_join &this_ter_join) const
void add_joins_for (const mutable_overmap_terrain &ter, const tripoint_om_omt &pos, om_direction::type rot, const std::vector< om_pos_dir > &suppressed_joins)
tripoint_om_omt pick_top_priority () const
void postpone (const tripoint_om_omt &pos)
void restore_postponed_at (const tripoint_om_omt &pos)
void restore_postponed ()
const std::vector< std::pair< om_pos_dir, std::string > > & all_used () const
Private Member Functions
void add_unresolved (const om_pos_dir &p, const mutable_overmap_join *j)
bool erase_unresolved (const om_pos_dir &p)
Private Attributes
indexed_joins unresolved
std::vector< cata::flat_set< iterator, compare_iterators > > unresolved_priority_index
indexed_joins resolved
indexed_joins postponed
std::vector< std::pair< om_pos_dir, std::string > > used
Detailed Description
Definition at line 1818 of file overmap.cpp.
Member Typedef Documentation
const_iterator
using joins_tracker::const_iterator = std::list<join>::const_iterator
Definition at line 1826 of file overmap.cpp.
iterator
using joins_tracker::iterator = std::list<join>::iterator
Definition at line 1825 of file overmap.cpp.
Member Enumeration Documentation
join_status
enum joins_tracker::join_status strong
Enumerator
disallowed
matched_available
matched_non_available
mismatched_available
free
Definition at line 1873 of file overmap.cpp.
{
             disallowed, // Conflicts with existing join, and at least one was mandatory
             matched_available, // Matches an existing non-mandatory join
             matched_non_available, // Matches an existing mandatory join
             mismatched_available, // Points at an incompatible join, but both are non-mandatory
             free, // Doesn't point at another join at all
         };
Member Function Documentation
add_joins_for()
void joins_tracker::add_joins_for (const mutable_overmap_terrain & ter, const tripoint_om_omt & pos, om_direction::type rot, const std::vector< om_pos_dir > & suppressed_joins) inline
Definition at line 1918 of file overmap.cpp.
{
             consistency_check();
             std::unordered_set<om_pos_dir> avoid(
                 suppressed_joins.begin(), suppressed_joins.end() );
             for( const std::pair<const cube_direction, mutable_overmap_terrain_join> &p :
                  ter.joins ) {
                 cube_direction dir = p.first + rot;
                 const mutable_overmap_terrain_join &this_side_join = p.second;
                 om_pos_dir this_side{ pos, dir };
                 om_pos_dir other_side = this_side.opposite();
                 if( const join *other_side_join = resolved.find( other_side ) ) {
                     erase_unresolved( this_side );
                     if( !avoid.count( this_side ) ) {
                         used.emplace_back( other_side, other_side_join->join->id );
                         // Because of the existence of alternative joins, we don't
                         // simply add this_side_join here, we add the opposite of
                         // the opposite that was actually present (this saves us
                         // from heaving to search through the alternates to find
                         // which one actually matched).
                         used.emplace_back( this_side, other_side_join->join->opposite_id );
                     }
                 } else {
                     // If there were postponed joins pointing into this point,
                     // so we need to un-postpone them because it might now be
                     // possible to satisfy them.
                     restore_postponed_at( other_side.p );
                     if( this_side_join.type == join_type::mandatory ) {
                         if( !overmap::inbounds( other_side.p ) ) {
                             debugmsg( "out of bounds join" );
                             continue;
                         }
                         const mutable_overmap_join *opposite_join = this_side_join.join->opposite;
                         add_unresolved( other_side, opposite_join );
                     }
                 }
                 resolved.add( this_side, this_side_join.join );
             }
             consistency_check();
         }
References joins_tracker::indexed_joins::add(), add_unresolved(), consistency_check(), debugmsg, erase_unresolved(), joins_tracker::indexed_joins::find(), overmap::inbounds(), mutable_overmap_terrain_join::join, mutable_overmap_terrain::joins, mandatory, mutable_overmap_join::opposite, pos_dir< Tripoint >::opposite(), pos_dir< Tripoint >::p, math_opers::pos(), resolved, restore_postponed_at(), mutable_overmap_terrain_join::type, and used.
Referenced by mutable_overmap_special_data::place().
add_unresolved()
void joins_tracker::add_unresolved (const om_pos_dir & p, const mutable_overmap_join * j) inline private
Definition at line 2096 of file overmap.cpp.
{
             iterator it = unresolved.add( p, j );
             unsigned priority = it->join->priority;
             if( unresolved_priority_index.size() <= priority ) {
                 unresolved_priority_index.resize( priority + 1 );
             }
             [[maybe_unused]] const bool inserted = unresolved_priority_index[priority].insert( it ).second;
             cata_assert( inserted );
         }
References joins_tracker::indexed_joins::add(), cata_assert, unresolved, and unresolved_priority_index.
Referenced by add_joins_for(), restore_postponed(), and restore_postponed_at().
all_unresolved_at()
std::vector<const join *> joins_tracker::all_unresolved_at (const tripoint_om_omt & pos) const inline
Definition at line 1832 of file overmap.cpp.
{
             std::vector<const join *> result;
             for( iterator it : unresolved.all_at( pos ) ) {
                 result.push_back( &*it );
             }
             return result;
         }
References joins_tracker::indexed_joins::all_at(), math_opers::pos(), and unresolved.
Referenced by mutable_overmap_special_data::place(), and mutable_overmap_phase_remainder::satisfy().
all_used()
const std::vector<std::pair<om_pos_dir, std::string> >& joins_tracker::all_used () const inline
Definition at line 2001 of file overmap.cpp.
{
             return used;
         }
References used.
Referenced by mutable_overmap_special_data::place().
allows()
join_status joins_tracker::allows (const om_pos_dir & this_side, const mutable_overmap_terrain_join & this_ter_join) const inline
Definition at line 1881 of file overmap.cpp.
{
             om_pos_dir other_side = this_side.opposite();
             auto is_allowed_opposite = [&]( const std::string & candidate ) {
                 const mutable_overmap_join &this_join = *this_ter_join.join;
                 if( this_join.opposite_id == candidate ) {
                     return true;
                 }
                 for( const mutable_overmap_join *alt_join : this_ter_join.alternative_joins ) {
                     if( alt_join->opposite_id == candidate ) {
                         return true;
                     }
                 }
                 return false;
             };
             if( const join *existing = resolved.find( other_side ) ) {
                 bool other_side_mandatory = unresolved.count( this_side );
                 if( is_allowed_opposite( existing->join->id ) ) {
                     return other_side_mandatory
                            ? join_status::matched_non_available : join_status::matched_available;
                 } else {
                     if( other_side_mandatory || this_ter_join.type != join_type::available ) {
                         return join_status::disallowed;
                     } else {
                         return join_status::mismatched_available;
                     }
                 }
             } else {
                 return join_status::free;
             }
         }
References mutable_overmap_terrain_join::alternative_joins, available, joins_tracker::indexed_joins::count(), disallowed, joins_tracker::indexed_joins::find(), free, mutable_overmap_terrain_join::join, matched_available, matched_non_available, mismatched_available, pos_dir< Tripoint >::opposite(), mutable_overmap_join::opposite_id, resolved, mutable_overmap_terrain_join::type, and unresolved.
Referenced by mutable_overmap_phase_remainder::can_place().
any_postponed()
bool joins_tracker::any_postponed () const inline
Definition at line 1844 of file overmap.cpp.
{
             return !postponed.empty();
         }
References joins_tracker::indexed_joins::empty(), and postponed.
Referenced by mutable_overmap_special_data::place().
any_postponed_at()
bool joins_tracker::any_postponed_at (const tripoint_om_omt & p) const inline
Definition at line 1848 of file overmap.cpp.
{
             return postponed.any_at( p );
         }
References joins_tracker::indexed_joins::any_at(), and postponed.
Referenced by mutable_overmap_phase_remainder::can_place().
any_unresolved()
bool joins_tracker::any_unresolved () const inline
Definition at line 1828 of file overmap.cpp.
{
             return !unresolved.empty();
         }
References joins_tracker::indexed_joins::empty(), and unresolved.
Referenced by pick_top_priority(), and mutable_overmap_special_data::place().
consistency_check()
void joins_tracker::consistency_check () const inline
Definition at line 1852 of file overmap.cpp.
{
 #if 0 // Enable this to check the class invariants, at the cost of more runtime
             // verify that there are no positions in common between the
             // resolved and postponed lists
             for( const join &j : postponed ) {
                 auto j_pos = j.where.p;
                 if( unresolved.any_at( j_pos ) ) {
                     std::vector<iterator> unr = unresolved.all_at( j_pos );
                     if( unr.empty() ) {
                         cata_fatal( "inconsistency between all_at and any_at" );
                     } else {
                         const join &unr_j = *unr.front();
                         cata_fatal( "postponed and unresolved should be disjoint but are not at "
                                     "%s where unresolved has %s: %s",
                                     j_pos.to_string(), unr_j.where.p.to_string(), unr_j.join_id );
                     }
                 }
             }
 #endif
         }
References joins_tracker::indexed_joins::all_at(), joins_tracker::indexed_joins::any_at(), cata_fatal, pos_dir< Tripoint >::p, postponed, coords::coord_point_base< Point >::to_string(), unresolved, and joins_tracker::join::where.
Referenced by add_joins_for(), postpone(), restore_postponed(), and restore_postponed_at().
count_unresolved_at()
std::size_t joins_tracker::count_unresolved_at (const tripoint_om_omt & pos) const inline
Definition at line 1840 of file overmap.cpp.
{
             return unresolved.count_at( pos );
         }
References joins_tracker::indexed_joins::count_at(), math_opers::pos(), and unresolved.
Referenced by mutable_overmap_phase_remainder::can_place().
erase_unresolved()
bool joins_tracker::erase_unresolved (const om_pos_dir & p) inline private
Definition at line 2106 of file overmap.cpp.
{
             auto pos_it = unresolved.position_index.find( p );
             if( pos_it == unresolved.position_index.end() ) {
                 return false;
             }
             iterator it = pos_it->second;
             unsigned priority = it->join->priority;
             cata_assert( priority < unresolved_priority_index.size() );
             [[maybe_unused]] const size_t erased = unresolved_priority_index[priority].erase( it );
             cata_assert( erased );
             unresolved.erase( it );
             return true;
         }
References cata_assert, joins_tracker::indexed_joins::erase(), joins_tracker::indexed_joins::position_index, unresolved, and unresolved_priority_index.
Referenced by add_joins_for(), and postpone().
pick_top_priority()
tripoint_om_omt joins_tracker::pick_top_priority () const inline
Definition at line 1964 of file overmap.cpp.
{
             cata_assert( any_unresolved() );
             auto priority_it =
                 std::find_if( unresolved_priority_index.begin(), unresolved_priority_index.end(),
             []( const cata::flat_set<iterator, compare_iterators> &its ) {
                 return !its.empty();
             } );
             cata_assert( priority_it != unresolved_priority_index.end() );
             auto it = random_entry( *priority_it );
             const tripoint_om_omt &pos = it->where.p;
             cata_assert( !postponed.any_at( pos ) );
             return pos;
         }
References joins_tracker::indexed_joins::any_at(), any_unresolved(), cata_assert, math_opers::pos(), postponed, random_entry(), and unresolved_priority_index.
Referenced by mutable_overmap_special_data::place().
postpone()
void joins_tracker::postpone (const tripoint_om_omt & pos) inline
Definition at line 1977 of file overmap.cpp.
{
             consistency_check();
             for( iterator it : unresolved.all_at( pos ) ) {
                 postponed.add( *it );
                 [[maybe_unused]] const bool erased = erase_unresolved( it->where );
                 cata_assert( erased );
             }
             consistency_check();
         }
References joins_tracker::indexed_joins::add(), joins_tracker::indexed_joins::all_at(), cata_assert, consistency_check(), erase_unresolved(), math_opers::pos(), postponed, and unresolved.
Referenced by mutable_overmap_special_data::place().
restore_postponed()
void joins_tracker::restore_postponed () inline
Definition at line 1993 of file overmap.cpp.
{
             consistency_check();
             for( const join &j : postponed ) {
                 add_unresolved( j.where, j.join );
             }
             postponed.clear();
         }
References add_unresolved(), joins_tracker::indexed_joins::clear(), consistency_check(), and postponed.
Referenced by mutable_overmap_special_data::place().
restore_postponed_at()
void joins_tracker::restore_postponed_at (const tripoint_om_omt & pos) inline
Definition at line 1986 of file overmap.cpp.
{
             for( iterator it : postponed.all_at( pos ) ) {
                 add_unresolved( it->where, it->join );
                 postponed.erase( it );
             }
             consistency_check();
         }
References add_unresolved(), joins_tracker::indexed_joins::all_at(), consistency_check(), joins_tracker::indexed_joins::erase(), math_opers::pos(), and postponed.
Referenced by add_joins_for().
Member Data Documentation
postponed
indexed_joins joins_tracker::postponed private
Definition at line 2130 of file overmap.cpp.
Referenced by any_postponed(), any_postponed_at(), consistency_check(), pick_top_priority(), postpone(), restore_postponed(), and restore_postponed_at().
resolved
indexed_joins joins_tracker::resolved private
Definition at line 2129 of file overmap.cpp.
Referenced by add_joins_for(), and allows().
unresolved
indexed_joins joins_tracker::unresolved private
Definition at line 2126 of file overmap.cpp.
Referenced by add_unresolved(), all_unresolved_at(), allows(), any_unresolved(), consistency_check(), count_unresolved_at(), erase_unresolved(), and postpone().
unresolved_priority_index
std::vector<cata::flat_set<iterator, compare_iterators> > joins_tracker::unresolved_priority_index private
Definition at line 2127 of file overmap.cpp.
Referenced by add_unresolved(), erase_unresolved(), and pick_top_priority().
used
std::vector<std::pair<om_pos_dir, std::string> > joins_tracker::used private
Definition at line 2132 of file overmap.cpp.
Referenced by add_joins_for(), and all_used().
The documentation for this class was generated from the following file:
src/overmap.cpp