Cataclysm DDA: JsonError Class Reference
JsonError Class Reference
#include <json_error.h>
Public Member Functions
JsonError (const std::string &msg)
const char * c_str () const noexcept
Detailed Description
Definition at line 7 of file json_error.h.
Constructor & Destructor Documentation
JsonError()
JsonError::JsonError (const std::string & msg) explicit
Definition at line 2434 of file json.cpp.
     : std::runtime_error( msg )
 {
 }
Member Function Documentation
c_str()
const char* JsonError::c_str () const inline noexcept
Definition at line 11 of file json_error.h.
{
             return what();
         }
Referenced by iuse::camera(), data_handling_activity_actor::do_turn(), vehicle::get_folded_item(), inventory::json_load_invcache(), game::serialize_master(), show_photo_selection(), game::unserialize(), and game::unserialize_master().
The documentation for this class was generated from the following files:
src/json_error.h
src/json.cpp