Cataclysm DDA: generic_vehicle_part_range< range_type > Class Template Reference
generic_vehicle_part_range< range_type > Class Template Reference
The generic range, it misses the bool contained(size_t) function that is required by the iterator class.
#include <vpart_range.h>
Public Types
using iterator = vehicle_part_iterator< range_type >
Public Member Functions
generic_vehicle_part_range (::vehicle &v, bool with_fake=false)
template<typename T = ::vehicle>
size_t part_count () const
iterator begin () const
iterator end () const
::vehicle & vehicle () const
Private Attributes
std::reference_wrapper<::vehicle > vehicle_
bool with_fake_
Friends
bool empty (const generic_vehicle_part_range< range_type > &range)
size_t size (const generic_vehicle_part_range< range_type > &range)
iterator begin (const generic_vehicle_part_range< range_type > &range)
iterator end (const generic_vehicle_part_range< range_type > &range)
Detailed Description
template<typename range_type>
class generic_vehicle_part_range< range_type >
The generic range, it misses the bool contained(size_t) function that is required by the iterator class.
You need to derive from it and implement that function. It uses the curiously recurring template pattern (CRTP), so use your derived range class as range_type.
Definition at line 101 of file vpart_range.h.
Member Typedef Documentation
iterator
template<typename range_type > using generic_vehicle_part_range< range_type >::iterator = vehicle_part_iterator<range_type>
Definition at line 122 of file vpart_range.h.
Constructor & Destructor Documentation
generic_vehicle_part_range()
template<typename range_type > generic_vehicle_part_range< range_type >::generic_vehicle_part_range (::vehicle & v, bool with_fake = false) inline explicit
Definition at line 108 of file vpart_range.h.
                                                                                   : vehicle_( v ),
             with_fake_( with_fake ) { }
Member Function Documentation
begin()
template<typename range_type > iterator generic_vehicle_part_range< range_type >::begin () const inline
Definition at line 123 of file vpart_range.h.
{
             return iterator( const_cast<range_type &>( static_cast<const range_type &>( *this ) ), 0 );
         }
Referenced by veh_interact::cant_do(), veh_interact::count_durability(), vehicle::folding_time(), vehicle::fuel_capacity(), liquid_handler::get_liquid_target(), veh_interact::get_most_damaged_part(), veh_interact::select_part(), and vehicle::unfolding_time().
end()
template<typename range_type > iterator generic_vehicle_part_range< range_type >::end () const inline
Definition at line 126 of file vpart_range.h.
{
             return iterator( const_cast<range_type &>( static_cast<const range_type &>( *this ) ),
                              part_count() );
         }
References generic_vehicle_part_range< range_type >::part_count().
Referenced by veh_interact::cant_do(), veh_interact::count_durability(), vehicle::folding_time(), vehicle::fuel_capacity(), liquid_handler::get_liquid_target(), veh_interact::get_most_damaged_part(), veh_interact::select_part(), and vehicle::unfolding_time().
part_count()
template<typename range_type > template<typename T = ::vehicle> size_t generic_vehicle_part_range< range_type >::part_count () const inline
Definition at line 113 of file vpart_range.h.
{
             if( with_fake_ ) {
                 return static_cast<const T &>( vehicle_.get() ).part_count();
             } else {
                 return static_cast<const T &>( vehicle_.get() ).part_count_real_cached();
             }
         }
References generic_vehicle_part_range< range_type >::vehicle_, and generic_vehicle_part_range< range_type >::with_fake_.
Referenced by generic_vehicle_part_range< range_type >::end().
vehicle()
template<typename range_type > ::vehicle& generic_vehicle_part_range< range_type >::vehicle () const inline
Definition at line 144 of file vpart_range.h.
{
             return vehicle_.get();
         }
References generic_vehicle_part_range< range_type >::vehicle_.
Friends And Related Function Documentation
begin
template<typename range_type > iterator begin (const generic_vehicle_part_range< range_type > & range) friend
Definition at line 137 of file vpart_range.h.
{
             return range.begin();
         }
empty
template<typename range_type > bool empty (const generic_vehicle_part_range< range_type > & range) friend
Definition at line 131 of file vpart_range.h.
{
             return range.begin() == range.end();
         }
end
template<typename range_type > iterator end (const generic_vehicle_part_range< range_type > & range) friend
Definition at line 140 of file vpart_range.h.
{
             return range.end();
         }
size
template<typename range_type > size_t size (const generic_vehicle_part_range< range_type > & range) friend
Definition at line 134 of file vpart_range.h.
{
             return std::distance( range.begin(), range.end() );
         }
Member Data Documentation
vehicle_
template<typename range_type > std::reference_wrapper<::vehicle> generic_vehicle_part_range< range_type >::vehicle_ private
Definition at line 104 of file vpart_range.h.
Referenced by generic_vehicle_part_range< range_type >::part_count(), and generic_vehicle_part_range< range_type >::vehicle().
with_fake_
template<typename range_type > bool generic_vehicle_part_range< range_type >::with_fake_ private
Definition at line 105 of file vpart_range.h.
Referenced by generic_vehicle_part_range< range_type >::part_count().
The documentation for this class was generated from the following file:
src/vpart_range.h