Cataclysm DDA: selection_column_preset Class Reference
selection_column_preset Class Reference
Public Member Functions
selection_column_preset ()=default
std::string get_caption (const inventory_entry &entry) const override
Text of the first column (default: item name)
nc_color get_color (const inventory_entry &entry) const override
Color that will be used to display the entry string.
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool is_shown (const item_location &) const
Does this entry satisfy the basic preset conditions?
virtual std::string get_denial (const item_location &) const
The reason why this entry cannot be selected.
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 249 of file inventory_ui.cpp.
Constructor & Destructor Documentation
selection_column_preset()
selection_column_preset::selection_column_preset () default
Member Function Documentation
get_caption()
std::string selection_column_preset::get_caption (const inventory_entry & entry) const inline override virtual
Text of the first column (default: item name)
Reimplemented from inventory_selector_preset.
Definition at line 253 of file inventory_ui.cpp.
{
             std::string res;
             const size_t available_count = entry.get_available_count();
             const item_location &item = entry.any_item();
             if( entry.chosen_count > 0 && entry.chosen_count < available_count ) {
                 //~ %1$d: chosen count, %2$d: available count
                 res += string_format( pgettext( "count", "%1$d of %2$d" ), entry.chosen_count,
                                       available_count ) + " ";
             } else if( available_count != 1 ) {
                 res += string_format( "%d ", available_count );
             }
             if( item->is_money() ) {
                 cata_assert( available_count == entry.get_stack_size() );
                 if( entry.chosen_count > 0 && entry.chosen_count < available_count ) {
                     res += item->display_money( available_count, item->ammo_remaining(),
                                                 entry.get_selected_charges() );
                 } else {
                     res += item->display_money( available_count, item->ammo_remaining() );
                 }
             } else {
                 res += item->display_name( available_count );
             }
             return res;
         }
References item::ammo_remaining(), inventory_entry::any_item(), cata_assert, inventory_entry::chosen_count, item::display_money(), item::display_name(), inventory_entry::get_available_count(), inventory_entry::get_selected_charges(), inventory_entry::get_stack_size(), item::is_money(), pgettext, and string_format().
get_color()
nc_color selection_column_preset::get_color (const inventory_entry & entry) const inline override virtual
Color that will be used to display the entry string.
Reimplemented from inventory_selector_preset.
Definition at line 279 of file inventory_ui.cpp.
{
             Character &player_character = get_player_character();
             if( entry.is_item() ) {
                 if( entry.any_item() == player_character.get_wielded_item() ) {
                     return c_light_blue;
                 } else if( player_character.is_worn( *entry.any_item() ) ) {
                     return c_cyan;
                 }
             }
             return inventory_selector_preset::get_color( entry );
         }
References inventory_entry::any_item(), c_cyan, c_light_blue, inventory_selector_preset::get_color(), get_player_character(), Character::get_wielded_item(), inventory_entry::is_item(), and Character::is_worn().
The documentation for this class was generated from the following file:
src/inventory_ui.cpp