Cataclysm DDA: inscribe_actor Class Reference
inscribe_actor Class Reference
Writes on stuff (ground or items)
#include <iuse_actor.h>
Public Member Functions
bool item_inscription (item &tool, item &cut) const
inscribe_actor (const std::string &type="inscribe")
~inscribe_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
bool on_items = true
bool on_terrain = false
bool material_restricted = true
std::set< material_id > material_whitelist
translation verb = to_translation("Carve")
translation gerund = to_translation("Carved")
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Writes on stuff (ground or items)
Definition at line 523 of file iuse_actor.h.
Constructor & Destructor Documentation
inscribe_actor()
inscribe_actor::inscribe_actor (const std::string & type = "inscribe") inline explicit
Definition at line 553 of file iuse_actor.h.
 : iuse_actor( type ) {}
~inscribe_actor()
inscribe_actor::~inscribe_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > inscribe_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 1805 of file iuse_actor.cpp.
 {
     return std::make_unique<inscribe_actor>( *this );
 }
item_inscription()
bool inscribe_actor::item_inscription (item & tool, item & cut) const
Definition at line 1810 of file iuse_actor.cpp.
 {
     if( !cut.made_of( phase_id::SOLID ) ) {
         add_msg( m_info, _( "You can't inscribe an item that isn't solid!" ) );
         return false;
     }
     if( material_restricted && !cut.made_of_any( material_whitelist ) ) {
         std::wstring lower_verb = utf8_to_wstr( verb.translated() );
         std::transform( lower_verb.begin(), lower_verb.end(), lower_verb.begin(), towlower );
         add_msg( m_info, _( "You can't %1$s %2$s because of the material it is made of." ),
                  wstr_to_utf8( lower_verb ), cut.display_name() );
         return false;
     }
     enum inscription_type {
         INSCRIPTION_LABEL,
         INSCRIPTION_NOTE,
     };
     uilist menu;
     menu.text = string_format( _( "%s meaning?" ), verb );
     menu.addentry( INSCRIPTION_LABEL, true, -1, _( "It's a label" ) );
     menu.addentry( INSCRIPTION_NOTE, true, -1, _( "It's a note" ) );
     menu.query();
     std::string carving;
     std::string carving_tool;
     switch( menu.ret ) {
         case INSCRIPTION_LABEL:
             carving = "item_label";
             carving_tool = "item_label_tool";
             break;
         case INSCRIPTION_NOTE:
             carving = "item_note";
             carving_tool = "item_note_tool";
             break;
         default:
             return false;
     }
     const bool hasnote = cut.has_var( carving );
     std::string messageprefix = ( hasnote ? _( "(To delete, clear the text and confirm)\n" ) : "" ) +
                                 //~ %1$s: gerund (e.g. carved), %2$s: item name
                                 string_format( pgettext( "carving", "%1$s on the %2$s is: " ),
                                         gerund, cut.type_name() );
     string_input_popup popup;
     popup.title( string_format( _( "%s what?" ), verb ) )
     .width( 64 )
     .text( hasnote ? cut.get_var( carving ) : std::string() )
     .description( messageprefix )
     .identifier( "inscribe_item" )
     .max_length( 128 )
     .query();
     if( popup.canceled() ) {
         return false;
     }
     const std::string message = popup.text();
     if( message.empty() ) {
         cut.erase_var( carving );
         cut.erase_var( carving_tool );
     } else {
         cut.set_var( carving, message );
         cut.set_var( carving_tool, tool.typeId().str() );
     }
     return true;
 }
References _, add_msg(), uilist::addentry(), item::display_name(), item::erase_var(), gerund, item::get_var(), item::has_var(), m_info, item::made_of(), item::made_of_any(), material_restricted, material_whitelist, mapgen_defer::message, pgettext, popup(), uilist::query(), uilist::ret, item::set_var(), SOLID, string_id< T >::str(), string_format(), uilist::text, translation::translated(), item::type_name(), item::typeId(), utf8_to_wstr(), verb, and wstr_to_utf8().
Referenced by use().
load()
void inscribe_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 1784 of file iuse_actor.cpp.
 {
     assign( obj, "cost", cost );
     assign( obj, "on_items", on_items );
     assign( obj, "on_terrain", on_terrain );
     assign( obj, "material_restricted", material_restricted );
     if( obj.has_array( "material_whitelist" ) ) {
         material_whitelist.clear();
         assign( obj, "material_whitelist", material_whitelist );
     }
     assign( obj, "verb", verb );
     assign( obj, "gerund", gerund );
     if( !on_items && !on_terrain ) {
         obj.throw_error(
             R"(Tried to create an useless inscribe_actor, at least on of "on_items" or "on_terrain" should be true)" );
     }
 }
References assign(), iuse_actor::cost, gerund, JsonObject::has_array(), material_restricted, material_whitelist, on_items, on_terrain, JsonObject::throw_error(), and verb.
use()
std::optional< int > inscribe_actor::use (Character * p, item & it, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 1880 of file iuse_actor.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action inscribe that requires character but no character is present",
                   it.typeId().str() );
         return std::nullopt;
     }
     int choice = INT_MAX;
     if( on_terrain && on_items ) {
         uilist imenu;
         imenu.text = string_format( _( "%s on what?" ), verb );
         imenu.addentry( 0, true, MENU_AUTOASSIGN, _( "The terrain" ) );
         imenu.addentry( 1, true, MENU_AUTOASSIGN, _( "An item" ) );
         imenu.query();
         choice = imenu.ret;
     } else if( on_terrain ) {
         choice = 0;
     } else {
         choice = 1;
     }
     if( choice < 0 || choice > 1 ) {
         return std::nullopt;
     }
     if( choice == 0 ) {
         const std::optional<tripoint> dest_ = choose_adjacent( _( "Write where?" ) );
         if( !dest_ ) {
             return std::nullopt;
         }
         return iuse::handle_ground_graffiti( *p, &it, string_format( _( "%s what?" ), verb ),
                                              dest_.value() );
     }
     item_location loc = game_menus::inv::titled_menu( get_avatar(), _( "Inscribe which item?" ) );
     if( !loc ) {
         p->add_msg_if_player( m_info, _( "Never mind." ) );
         return std::nullopt;
     }
     item &cut = *loc;
     if( &cut == &it ) {
         p->add_msg_if_player( _( "You try to bend your %s, but fail." ), it.tname() );
         return 0;
     }
     // inscribe_item returns false if the action fails or is canceled somehow.
     if( item_inscription( it, cut ) ) {
         return cost >= 0 ? cost : 1;
     }
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), uilist::addentry(), choose_adjacent(), iuse_actor::cost, debugmsg, get_avatar(), iuse::handle_ground_graffiti(), item_inscription(), m_info, MENU_AUTOASSIGN, on_items, on_terrain, uilist::query(), uilist::ret, string_id< T >::str(), string_format(), uilist::text, game_menus::inv::titled_menu(), item::tname(), item::typeId(), and verb.
Member Data Documentation
gerund
translation inscribe_actor::gerund = to_translation("Carved")
Definition at line 549 of file iuse_actor.h.
Referenced by item::final_info(), item_inscription(), and load().
material_restricted
bool inscribe_actor::material_restricted = true
Definition at line 531 of file iuse_actor.h.
Referenced by item_inscription(), and load().
material_whitelist
std::set<material_id> inscribe_actor::material_whitelist
Initial value:
= {
            material_id( "wood" ),
            material_id( "clay" ),
            material_id( "porcelain" ),
            material_id( "plastic" ),
            material_id( "glass" ),
            material_id( "chitin" ),
            material_id( "iron" ),
            material_id( "steel" ),
            material_id( "silver" ),
            material_id( "bone" )
        }
Definition at line 534 of file iuse_actor.h.
Referenced by item_inscription(), and load().
on_items
bool inscribe_actor::on_items = true
Definition at line 527 of file iuse_actor.h.
Referenced by load(), and use().
on_terrain
bool inscribe_actor::on_terrain = false
Definition at line 528 of file iuse_actor.h.
Referenced by load(), and use().
verb
translation inscribe_actor::verb = to_translation("Carve")
Definition at line 548 of file iuse_actor.h.
Referenced by item_inscription(), load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp