Cataclysm DDA: cata::list< element_type, element_allocator_type > Class Template Reference
cata::list< element_type, element_allocator_type > Class Template Reference
#include <list.h>
Classes
struct choose
struct choose< false, IsTrue, IsFalse >
struct choose< true, IsTrue, IsFalse >
struct ebco_pair1
struct ebco_pair2
struct eq
struct eq_to
struct group
class group_vector
struct less
class list_iterator
class list_reverse_iterator
struct node
struct node_base
struct plf_enable_if_c
struct plf_enable_if_c< false, T >
struct sort_dereferencer
Public Types
using value_type = element_type
using allocator_type = element_allocator_type
using group_size_type = unsigned short
using size_type = typename std::allocator_traits< element_allocator_type >::size_type
using difference_type = typename std::allocator_traits< element_allocator_type >::difference_type
using reference = element_type &
using const_reference = const element_type &
using pointer = typename std::allocator_traits< element_allocator_type >::pointer
using const_pointer = typename std::allocator_traits< element_allocator_type >::const_pointer
using iterator = list_iterator< false >
using const_iterator = list_iterator< true >
using reverse_iterator = list_reverse_iterator< false >
using const_reverse_iterator = list_reverse_iterator< true >
Public Member Functions
list () noexcept
list (const element_allocator_type &alloc)
list (const list &source)
list (const list &source, const allocator_type &alloc)
list (list &&source) noexcept
list (list &&source, const allocator_type &alloc)
list (const size_type fill_number, const element_type &element, const element_allocator_type &alloc=element_allocator_type())
template<typename iterator_type >
list (const typename plf_enable_if_c< !std::numeric_limits< iterator_type >::is_integer, iterator_type >::type &first, const iterator_type &last, const element_allocator_type &alloc=element_allocator_type())
list (const std::initializer_list< element_type > &element_list, const element_allocator_type &alloc=element_allocator_type())
~list () noexcept
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
reverse_iterator rbegin () const noexcept
reverse_iterator rend () const noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void clear () noexcept
iterator insert (const iterator it, const element_type &element)
LIST_FORCE_INLINE void push_back (const element_type &element)
LIST_FORCE_INLINE void push_front (const element_type &element)
iterator insert (const iterator it, element_type &&element)
LIST_FORCE_INLINE void push_back (element_type &&element)
LIST_FORCE_INLINE void push_front (element_type &&element)
template<typename... arguments>
iterator emplace (const iterator it, arguments &&... parameters)
template<typename... arguments>
LIST_FORCE_INLINE reference emplace_back (arguments &&... parameters)
template<typename... arguments>
LIST_FORCE_INLINE reference emplace_front (arguments &&... parameters)
iterator insert (iterator position, const size_type number_of_elements, const element_type &element)
template<class iterator_type >
iterator insert (const iterator it, typename plf_enable_if_c< !std::numeric_limits< iterator_type >::is_integer, iterator_type >::type first, const iterator_type last)
iterator insert (const iterator it, const std::initializer_list< element_type > &element_list)
iterator erase (const const_iterator it)
void erase (const const_iterator iterator1, const const_iterator iterator2)
void pop_back ()
void pop_front ()
list & operator= (const list &source)
list & operator= (list &&source) LIST_NOEXCEPT_MOVE_ASSIGNMENT(allocator_type)
bool operator== (const list &rh) const noexcept
bool operator!= (const list &rh) const noexcept
bool empty () const noexcept
size_type size () const noexcept
size_type max_size () const noexcept
size_type capacity () const noexcept
size_type approximate_memory_use () const noexcept
template<class comparison_function >
void sort (comparison_function compare)
void sort ()
void reorder (const iterator position, const iterator first, const iterator last) noexcept
void reorder (const iterator position, const iterator location) noexcept
void reserve (size_type reserve_amount)
LIST_FORCE_INLINE void free_unused_memory () noexcept
void shrink_to_fit ()
void splice (iterator position, list &source)
template<class comparison_function >
void merge (list &source, comparison_function compare)
void merge (list &source)
void reverse () noexcept
template<class comparison_function >
size_type unique (comparison_function compare)
size_type unique ()
template<class predicate_function >
size_type remove_if (predicate_function predicate)
size_type remove (const element_type &value)
void resize (const size_type number_of_elements, const element_type &value=element_type())
template<class iterator_type >
void assign (const typename plf_enable_if_c< !std::numeric_limits< iterator_type >::is_integer, iterator_type >::type first, const iterator_type last)
void assign (const size_type number_of_elements, const element_type &value)
void assign (const std::initializer_list< element_type > &element_list)
allocator_type get_allocator () const noexcept
void swap (list &source) LIST_NOEXCEPT_SWAP(allocator_type)
Private Types
using group_allocator_type = typename std::allocator_traits< element_allocator_type >::template rebind_alloc< group >
using node_allocator_type = typename std::allocator_traits< element_allocator_type >::template rebind_alloc< node >
using group_pointer_type = typename std::allocator_traits< group_allocator_type >::pointer
using node_pointer_type = typename std::allocator_traits< node_allocator_type >::pointer
using node_pointer_allocator_type = typename std::allocator_traits< element_allocator_type >::template rebind_alloc< node_pointer_type >
Private Member Functions
void reset () noexcept
void group_fill_position (const element_type &element, group_size_type number_of_elements, node_pointer_type const position)
LIST_FORCE_INLINE void destroy_all_node_pointers (group_pointer_type const group_to_process, const node_pointer_type beyond_end_node) noexcept
void append_process (list &source)
Private Attributes
group_vector groups
node_base end_node
node_pointer_type last_endpoint
iterator end_iterator
iterator begin_iterator
cata::list::ebco_pair1 node_pointer_allocator_pair
cata::list::ebco_pair2 node_allocator_pair
Friends
class list_iterator< false >
class list_iterator< true >
class list_reverse_iterator< false >
class list_reverse_iterator< true >
Detailed Description
template<class element_type, class element_allocator_type = std::allocator<element_type>>
class cata::list< element_type, element_allocator_type >
Definition at line 67 of file list.h.
Member Typedef Documentation
allocator_type
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::allocator_type = element_allocator_type
Definition at line 73 of file list.h.
const_iterator
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::const_iterator = list_iterator<true>
Definition at line 86 of file list.h.
const_pointer
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::const_pointer = typename std::allocator_traits<element_allocator_type>::const_pointer
Definition at line 81 of file list.h.
const_reference
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::const_reference = const element_type&
Definition at line 79 of file list.h.
const_reverse_iterator
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::const_reverse_iterator = list_reverse_iterator<true>
Definition at line 92 of file list.h.
difference_type
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::difference_type = typename std::allocator_traits<element_allocator_type>::difference_type
Definition at line 77 of file list.h.
group_allocator_type
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::group_allocator_type = typename std::allocator_traits<element_allocator_type>::template rebind_alloc<group> private
Definition at line 100 of file list.h.
group_pointer_type
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::group_pointer_type = typename std::allocator_traits<group_allocator_type>::pointer private
Definition at line 104 of file list.h.
group_size_type
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::group_size_type = unsigned short
Definition at line 74 of file list.h.
iterator
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::iterator = list_iterator<false>
Definition at line 85 of file list.h.
node_allocator_type
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::node_allocator_type = typename std::allocator_traits<element_allocator_type>::template rebind_alloc<node> private
Definition at line 102 of file list.h.
node_pointer_allocator_type
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::node_pointer_allocator_type = typename std::allocator_traits<element_allocator_type>::template rebind_alloc<node_pointer_type> private
Definition at line 106 of file list.h.
node_pointer_type
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::node_pointer_type = typename std::allocator_traits<node_allocator_type>::pointer private
Definition at line 105 of file list.h.
pointer
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::pointer = typename std::allocator_traits<element_allocator_type>::pointer
Definition at line 80 of file list.h.
reference
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::reference = element_type&
Definition at line 78 of file list.h.
reverse_iterator
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::reverse_iterator = list_reverse_iterator<false>
Definition at line 91 of file list.h.
size_type
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::size_type = typename std::allocator_traits<element_allocator_type>::size_type
Definition at line 76 of file list.h.
value_type
template<class element_type , class element_allocator_type = std::allocator<element_type>> using cata::list< element_type, element_allocator_type >::value_type = element_type
Definition at line 72 of file list.h.
Constructor & Destructor Documentation
list() [1/9]
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::list () inline noexcept
Definition at line 994 of file list.h.
                        :
             element_allocator_type( element_allocator_type() ),
             end_node( reinterpret_cast<node_pointer_type>( &end_node ),
                       reinterpret_cast<node_pointer_type>( &end_node ) ),
             last_endpoint( nullptr ),
             end_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             begin_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             node_pointer_allocator_pair( 0 ),
             node_allocator_pair( 0 )
         {}
list() [2/9]
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::list (const element_allocator_type & alloc) inline explicit
Definition at line 1006 of file list.h.
                                                             :
             element_allocator_type( alloc ),
             end_node( reinterpret_cast<node_pointer_type>( &end_node ),
                       reinterpret_cast<node_pointer_type>( &end_node ) ),
             last_endpoint( NULL ),
             end_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             begin_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             node_pointer_allocator_pair( 0 ),
             node_allocator_pair( 0 )
         {}
list() [3/9]
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::list (const list< element_type, element_allocator_type > & source) inline
Definition at line 1018 of file list.h.
                                   :
             element_allocator_type( source ),
             end_node( reinterpret_cast<node_pointer_type>( &end_node ),
                       reinterpret_cast<node_pointer_type>( &end_node ) ),
             last_endpoint( nullptr ),
             end_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             begin_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             node_pointer_allocator_pair( 0 ),
             node_allocator_pair( 0 ) {
             reserve( source.node_pointer_allocator_pair.total_number_of_elements );
             insert( end_iterator, source.begin_iterator, source.end_iterator );
         }
References cata::list< element_type, element_allocator_type >::begin_iterator, cata::list< element_type, element_allocator_type >::end_iterator, cata::list< element_type, element_allocator_type >::node_pointer_allocator_pair, and cata::list< element_type, element_allocator_type >::ebco_pair1::total_number_of_elements.
list() [4/9]
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::list (const list< element_type, element_allocator_type > & source, const allocator_type & alloc) inline
Definition at line 1032 of file list.h.
                                                                :
             element_allocator_type( alloc ),
             end_node( reinterpret_cast<node_pointer_type>( &end_node ),
                       reinterpret_cast<node_pointer_type>( &end_node ) ),
             last_endpoint( nullptr ),
             end_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             begin_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             node_pointer_allocator_pair( 0 ),
             node_allocator_pair( 0 ) {
             reserve( source.node_pointer_allocator_pair.total_number_of_elements );
             insert( end_iterator, source.begin_iterator, source.end_iterator );
         }
References cata::list< element_type, element_allocator_type >::begin_iterator, cata::list< element_type, element_allocator_type >::end_iterator, cata::list< element_type, element_allocator_type >::node_pointer_allocator_pair, and cata::list< element_type, element_allocator_type >::ebco_pair1::total_number_of_elements.
list() [5/9]
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::list (list< element_type, element_allocator_type > && source) inline noexcept
Definition at line 1046 of file list.h.
                                       :
             element_allocator_type( source ),
             groups( std::move( source.groups ) ),
             end_node( std::move( source.end_node ) ),
             last_endpoint( std::move( source.last_endpoint ) ),
             end_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             begin_iterator( ( source.begin_iterator.node_pointer == source.end_iterator.node_pointer ) ?
                             reinterpret_cast<node_pointer_type>( &end_node ) : std::move( source.begin_iterator ) ),
             node_pointer_allocator_pair( source.node_pointer_allocator_pair.total_number_of_elements ),
             node_allocator_pair( source.node_allocator_pair.number_of_erased_nodes ) {
             end_node.previous->next = begin_iterator.node_pointer->previous = end_iterator.node_pointer;
             source.groups.blank();
             source.reset();
         }
References cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, and cata::list< element_type, element_allocator_type >::node_base::previous.
list() [6/9]
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::list (list< element_type, element_allocator_type > && source, const allocator_type & alloc) inline
Definition at line 1062 of file list.h.
                                                           :
             element_allocator_type( alloc ),
             groups( std::move( source.groups ) ),
             end_node( std::move( source.end_node ) ),
             last_endpoint( std::move( source.last_endpoint ) ),
             end_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             begin_iterator( ( source.begin_iterator.node_pointer == source.end_iterator.node_pointer ) ?
                             reinterpret_cast<node_pointer_type>( &end_node ) : std::move( source.begin_iterator ) ),
             node_pointer_allocator_pair( source.node_pointer_allocator_pair.total_number_of_elements ),
             node_allocator_pair( source.node_allocator_pair.number_of_erased_nodes ) {
             end_node.previous->next = begin_iterator.node_pointer->previous = end_iterator.node_pointer;
             source.groups.blank();
             source.reset();
         }
References cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, and cata::list< element_type, element_allocator_type >::node_base::previous.
list() [7/9]
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::list (const size_type fill_number, const element_type & element, const element_allocator_type & alloc = element_allocator_type()) inline
Definition at line 1078 of file list.h.
                                                                               :
             element_allocator_type( alloc ),
             end_node( reinterpret_cast<node_pointer_type>( &end_node ),
                       reinterpret_cast<node_pointer_type>( &end_node ) ),
             last_endpoint( nullptr ),
             end_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             begin_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             node_pointer_allocator_pair( 0 ),
             node_allocator_pair( 0 ) {
             reserve( fill_number );
             insert( end_iterator, fill_number, element );
         }
list() [8/9]
template<class element_type , class element_allocator_type = std::allocator<element_type>> template<typename iterator_type > cata::list< element_type, element_allocator_type >::list (const typename plf_enable_if_c< !std::numeric_limits< iterator_type >::is_integer, iterator_type >::type & first, const iterator_type & last, const element_allocator_type & alloc = element_allocator_type()) inline
Definition at line 1094 of file list.h.
                                                                               :
             element_allocator_type( alloc ),
             end_node( reinterpret_cast<node_pointer_type>( &end_node ),
                       reinterpret_cast<node_pointer_type>( &end_node ) ),
             last_endpoint( nullptr ),
             end_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             begin_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             node_pointer_allocator_pair( 0 ),
             node_allocator_pair( 0 ) {
             insert<iterator_type>( end_iterator, first, last );
         }
References last.
list() [9/9]
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::list (const std::initializer_list< element_type > & element_list, const element_allocator_type & alloc = element_allocator_type()) inline
Definition at line 1109 of file list.h.
                                                                               :
             element_allocator_type( alloc ),
             end_node( reinterpret_cast<node_pointer_type>( &end_node ),
                       reinterpret_cast<node_pointer_type>( &end_node ) ),
             last_endpoint( nullptr ),
             end_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             begin_iterator( reinterpret_cast<node_pointer_type>( &end_node ) ),
             node_pointer_allocator_pair( 0 ),
             node_allocator_pair( 0 ) {
             reserve( element_list.size() );
             insert( end_iterator, element_list );
         }
~list()
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list< element_type, element_allocator_type >::~list () inline noexcept
Definition at line 1123 of file list.h.
{
             groups.destroy_all_data( last_endpoint );
         }
References cata::list< element_type, element_allocator_type >::group_vector::destroy_all_data().
Member Function Documentation
append_process()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::append_process (list< element_type, element_allocator_type > & source) inline private
Definition at line 2143 of file list.h.
                                             { // used by merge and splice
             if( last_endpoint != groups.last_endpoint_group->beyond_end ) {
                 // Add unused nodes to group's free list
                 const node_pointer_type back_node = last_endpoint - 1;
                 for( node_pointer_type current_node = groups.last_endpoint_group->beyond_end - 1;
                      current_node != back_node; --current_node ) {
                     current_node->next = nullptr;
                     current_node->previous = groups.last_endpoint_group->free_list_head;
                     groups.last_endpoint_group->free_list_head = current_node;
                 }
                 node_allocator_pair.number_of_erased_nodes += static_cast<size_type>
                         ( groups.last_endpoint_group->beyond_end - last_endpoint );
             }
             groups.append( source.groups );
             last_endpoint = source.last_endpoint;
             node_pointer_allocator_pair.total_number_of_elements +=
                 source.node_pointer_allocator_pair.total_number_of_elements;
             source.reset();
         }
References cata::list< element_type, element_allocator_type >::group_vector::append(), cata::list< element_type, element_allocator_type >::groups, cata::list< element_type, element_allocator_type >::last_endpoint, cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, cata::list< element_type, element_allocator_type >::node_pointer_allocator_pair, cata::list< element_type, element_allocator_type >::reset(), and cata::list< element_type, element_allocator_type >::ebco_pair1::total_number_of_elements.
approximate_memory_use()
template<class element_type , class element_allocator_type = std::allocator<element_type>> size_type cata::list< element_type, element_allocator_type >::approximate_memory_use () const inline noexcept
Definition at line 1898 of file list.h.
{
             return static_cast<size_type>( sizeof( *this ) + ( groups.element_allocator_pair.capacity * sizeof(
                                                node ) ) + ( sizeof( group ) * groups.group_allocator_pair.capacity ) );
         }
References cata::list< element_type, element_allocator_type >::group_vector::ebco_pair2::capacity, cata::list< element_type, element_allocator_type >::group_vector::ebco_pair::capacity, cata::list< element_type, element_allocator_type >::group_vector::element_allocator_pair, and cata::list< element_type, element_allocator_type >::group_vector::group_allocator_pair.
assign() [1/3]
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::assign (const size_type number_of_elements, const element_type & value) inline
Definition at line 2430 of file list.h.
{
             clear();
             reserve( number_of_elements ); // Will return anyway if capacity already > number_of_elements
             insert( end_iterator, number_of_elements, value );
         }
References clear.
assign() [2/3]
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::assign (const std::initializer_list< element_type > & element_list) inline
Definition at line 2437 of file list.h.
{
             clear();
             reserve( element_list.size() );
             insert( end_iterator, element_list );
         }
References clear.
assign() [3/3]
template<class element_type , class element_allocator_type = std::allocator<element_type>> template<class iterator_type > void cata::list< element_type, element_allocator_type >::assign (const typename plf_enable_if_c< !std::numeric_limits< iterator_type >::is_integer, iterator_type >::type first, const iterator_type last) inline
Definition at line 2421 of file list.h.
{
             clear();
             insert( end_iterator, first, last );
             groups.trim_trailing_groups();
         }
References clear, last, and cata::list< element_type, element_allocator_type >::group_vector::trim_trailing_groups().
back() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> reference cata::list< element_type, element_allocator_type >::back () inline
Definition at line 1177 of file list.h.
{
             cata_assert( end_node.previous != &end_node );
             return end_node.previous->element;
         }
References cata_assert, and cata::list< element_type, element_allocator_type >::node_base::previous.
back() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> const_reference cata::list< element_type, element_allocator_type >::back () const inline
Definition at line 1182 of file list.h.
{
             cata_assert( end_node.previous != &end_node );
             return end_node.previous->element;
         }
References cata_assert, and cata::list< element_type, element_allocator_type >::node_base::previous.
begin() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> const_iterator cata::list< element_type, element_allocator_type >::begin () const inline noexcept
Definition at line 1131 of file list.h.
{
             return begin_iterator;
         }
begin() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> iterator cata::list< element_type, element_allocator_type >::begin () inline noexcept
Definition at line 1127 of file list.h.
{
             return begin_iterator;
         }
Referenced by cast_horizontal_zlight_segment(), and cast_vertical_zlight_segment().
capacity()
template<class element_type , class element_allocator_type = std::allocator<element_type>> size_type cata::list< element_type, element_allocator_type >::capacity () const inline noexcept
Definition at line 1894 of file list.h.
{
             return groups.element_allocator_pair.capacity;
         }
References cata::list< element_type, element_allocator_type >::group_vector::ebco_pair2::capacity, and cata::list< element_type, element_allocator_type >::group_vector::element_allocator_pair.
cbegin()
template<class element_type , class element_allocator_type = std::allocator<element_type>> const_iterator cata::list< element_type, element_allocator_type >::cbegin () const inline noexcept
Definition at line 1143 of file list.h.
{
             return const_iterator( begin_iterator.node_pointer );
         }
References cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer.
cend()
template<class element_type , class element_allocator_type = std::allocator<element_type>> const_iterator cata::list< element_type, element_allocator_type >::cend () const inline noexcept
Definition at line 1147 of file list.h.
{
             return const_iterator( end_iterator.node_pointer );
         }
References cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer.
clear()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::clear () inline noexcept
Definition at line 1187 of file list.h.
{
             if( last_endpoint == nullptr ) {
                 return;
             }
             if( node_pointer_allocator_pair.total_number_of_elements != 0 ) {
                 groups.clear( last_endpoint );
             }
             end_node.next = reinterpret_cast<node_pointer_type>( &end_node );
             end_node.previous = reinterpret_cast<node_pointer_type>( &end_node );
             last_endpoint = groups.block_pointer->nodes;
             begin_iterator.node_pointer = end_iterator.node_pointer;
             node_pointer_allocator_pair.total_number_of_elements = 0;
             node_allocator_pair.number_of_erased_nodes = 0;
         }
References cata::list< element_type, element_allocator_type >::group_vector::block_pointer, cata::list< element_type, element_allocator_type >::group_vector::clear(), cata::list< element_type, element_allocator_type >::node_base::next, cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, and cata::list< element_type, element_allocator_type >::node_base::previous.
crbegin()
template<class element_type , class element_allocator_type = std::allocator<element_type>> const_reverse_iterator cata::list< element_type, element_allocator_type >::crbegin () const inline noexcept
Definition at line 1159 of file list.h.
{
             return const_reverse_iterator( end_node.previous );
         }
References cata::list< element_type, element_allocator_type >::node_base::previous.
crend()
template<class element_type , class element_allocator_type = std::allocator<element_type>> const_reverse_iterator cata::list< element_type, element_allocator_type >::crend () const inline noexcept
Definition at line 1163 of file list.h.
{
             return const_reverse_iterator( end_iterator.node_pointer );
         }
References cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer.
destroy_all_node_pointers()
template<class element_type , class element_allocator_type = std::allocator<element_type>> LIST_FORCE_INLINE void cata::list< element_type, element_allocator_type >::destroy_all_node_pointers (group_pointer_type const group_to_process, const node_pointer_type beyond_end_node) inline private noexcept
Definition at line 1690 of file list.h.
{
             for( node_pointer_type current_node = group_to_process->nodes; current_node != beyond_end_node;
                  ++current_node ) {
                 LIST_DESTROY( node_pointer_allocator_type, node_pointer_allocator_pair,
                               &( current_node->next ) ); // Destruct element
                 LIST_DESTROY( node_pointer_allocator_type, node_pointer_allocator_pair,
                               &( current_node->previous ) ); // Destruct element
             }
         }
References LIST_DESTROY.
emplace()
template<class element_type , class element_allocator_type = std::allocator<element_type>> template<typename... arguments> iterator cata::list< element_type, element_allocator_type >::emplace (const iterator it, arguments &&... parameters) inline
Definition at line 1404 of file list.h.
{
             if( last_endpoint != nullptr ) {
                 if( node_allocator_pair.number_of_erased_nodes == 0 ) {
                     if( last_endpoint == groups.last_endpoint_group->beyond_end ) {
                         if( static_cast<size_type>( groups.last_endpoint_group - groups.block_pointer ) == groups.size -
                             1 ) {
                             groups.add_new( ( node_pointer_allocator_pair.total_number_of_elements < LIST_BLOCK_MAX ) ?
                                             static_cast<group_size_type>( node_pointer_allocator_pair.total_number_of_elements ) :
                                             LIST_BLOCK_MAX );
                         } else {
                             ++groups.last_endpoint_group;
                         }
                         last_endpoint = groups.last_endpoint_group->nodes;
                     }
                     LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint, it.node_pointer,
                                     it.node_pointer->previous, std::forward<arguments>( parameters )... );
                     ++( groups.last_endpoint_group->number_of_elements );
                     ++node_pointer_allocator_pair.total_number_of_elements;
                     if( it.node_pointer == begin_iterator.node_pointer ) {
                         begin_iterator.node_pointer = last_endpoint;
                     }
                     it.node_pointer->previous->next = last_endpoint;
                     it.node_pointer->previous = last_endpoint;
                     return iterator( last_endpoint++ );
                 } else {
                     group_pointer_type const node_group = groups.get_nearest_freelist_group( (
                             it.node_pointer != end_iterator.node_pointer ) ? it.node_pointer : end_node.previous );
                     node_pointer_type const selected_node = node_group->free_list_head;
                     const node_pointer_type previous = node_group->free_list_head->previous;
                     LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, selected_node, it.node_pointer,
                                     it.node_pointer->previous, std::forward<arguments>( parameters )... );
                     node_group->free_list_head = previous;
                     ++( node_group->number_of_elements );
                     ++node_pointer_allocator_pair.total_number_of_elements;
                     --node_allocator_pair.number_of_erased_nodes;
                     it.node_pointer->previous->next = selected_node;
                     it.node_pointer->previous = selected_node;
                     if( it.node_pointer == begin_iterator.node_pointer ) {
                         begin_iterator.node_pointer = selected_node;
                     }
                     return iterator( selected_node );
                 }
             } else {
                 if( groups.block_pointer == nullptr ) {
                     groups.initialize( LIST_BLOCK_MIN );
                 }
                 groups.last_endpoint_group->number_of_elements = 1;
                 end_node.next = end_node.previous = last_endpoint = begin_iterator.node_pointer =
                                                         groups.last_endpoint_group->nodes;
                 node_pointer_allocator_pair.total_number_of_elements = 1;
                 if LIST_CONSTEXPR( std::is_nothrow_constructible<element_type, arguments ...>::value ) {
                     LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint++,
                                     end_iterator.node_pointer, end_iterator.node_pointer, std::forward<arguments>( parameters )... );
                 } else {
                     try {
                         LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint++,
                                         end_iterator.node_pointer, end_iterator.node_pointer, std::forward<arguments>( parameters )... );
                     } catch( ... ) {
                         reset();
                         throw;
                     }
                 }
                 return begin_iterator;
             }
         }
References cata::list< element_type, element_allocator_type >::group_vector::add_new(), cata::list< element_type, element_allocator_type >::group_vector::block_pointer, cata::list< element_type, element_allocator_type >::group_vector::get_nearest_freelist_group(), cata::list< element_type, element_allocator_type >::group_vector::initialize(), cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, LIST_BLOCK_MAX, LIST_BLOCK_MIN, LIST_CONSTEXPR, LIST_CONSTRUCT, cata::list< element_type, element_allocator_type >::node_base::next, cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, cata::list< element_type, element_allocator_type >::node_base::previous, and cata::list< element_type, element_allocator_type >::group_vector::size.
emplace_back()
template<class element_type , class element_allocator_type = std::allocator<element_type>> template<typename... arguments> LIST_FORCE_INLINE reference cata::list< element_type, element_allocator_type >::emplace_back (arguments &&... parameters) inline
Definition at line 1485 of file list.h.
{
             return emplace( end_iterator, std::forward<arguments>( parameters )... ).node_pointer->element;
         }
emplace_front()
template<class element_type , class element_allocator_type = std::allocator<element_type>> template<typename... arguments> LIST_FORCE_INLINE reference cata::list< element_type, element_allocator_type >::emplace_front (arguments &&... parameters) inline
Definition at line 1490 of file list.h.
{
             return emplace( begin_iterator,
                             std::forward<arguments>( parameters )... ).node_pointer->element;
         }
empty()
template<class element_type , class element_allocator_type = std::allocator<element_type>> bool cata::list< element_type, element_allocator_type >::empty () const inline noexcept
Definition at line 1882 of file list.h.
{
             return node_pointer_allocator_pair.total_number_of_elements == 0;
         }
end() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> const_iterator cata::list< element_type, element_allocator_type >::end () const inline noexcept
Definition at line 1139 of file list.h.
{
             return end_iterator;
         }
end() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> iterator cata::list< element_type, element_allocator_type >::end () inline noexcept
Definition at line 1135 of file list.h.
{
             return end_iterator;
         }
Referenced by cast_horizontal_zlight_segment(), and cast_vertical_zlight_segment().
erase() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> iterator cata::list< element_type, element_allocator_type >::erase (const const_iterator it) inline
Definition at line 1705 of file list.h.
{
             cata_assert( node_pointer_allocator_pair.total_number_of_elements != 0 );
             cata_assert( it.node_pointer != nullptr );
             cata_assert( it.node_pointer != end_iterator.node_pointer );
             if LIST_CONSTEXPR( !std::is_trivially_destructible<element_type>::value ) {
                 LIST_DESTROY( element_allocator_type, ( *this ),
                               &( it.node_pointer->element ) ); // Destruct element
             }
             --node_pointer_allocator_pair.total_number_of_elements;
             ++node_allocator_pair.number_of_erased_nodes;
             group_pointer_type node_group = groups.last_searched_group;
             // find nearest group with reusable (erased element) memory location:
             if( ( it.node_pointer < node_group->nodes ) || ( it.node_pointer >= node_group->beyond_end ) ) {
                 // Search left and right:
                 const group_pointer_type beyond_end_group = groups.last_endpoint_group + 1;
                 group_pointer_type left = node_group - 1;
                 bool right_not_beyond_back = ++node_group < beyond_end_group;
                 bool left_not_beyond_front = left >= groups.block_pointer;
                 while( true ) {
                     if( right_not_beyond_back ) {
                         if( ( it.node_pointer < node_group->beyond_end ) &&
                             ( it.node_pointer >= node_group->nodes ) ) { // usable location found
                             break;
                         }
                         right_not_beyond_back = ( ++node_group < beyond_end_group );
                     }
                     if( left_not_beyond_front ) {
                         if( ( it.node_pointer >= left->nodes ) &&
                             ( it.node_pointer < left->beyond_end ) ) { // usable location found
                             node_group = left;
                             break;
                         }
                         left_not_beyond_front = ( --left >= groups.block_pointer );
                     }
                 }
                 groups.last_searched_group = node_group;
             }
             it.node_pointer->next->previous = it.node_pointer->previous;
             it.node_pointer->previous->next = it.node_pointer->next;
             if( it.node_pointer == begin_iterator.node_pointer ) {
                 begin_iterator.node_pointer = it.node_pointer->next;
             }
             const iterator return_iterator( it.node_pointer->next );
             // ie. group is not empty yet, add node to free list
             if( --( node_group->number_of_elements ) != 0 ) {
                 // next == NULL so that destructor can detect the free list item as opposed to non-free-list item
                 it.node_pointer->next = nullptr;
                 it.node_pointer->previous = node_group->free_list_head;
                 node_group->free_list_head = it.node_pointer;
                 return return_iterator;
             } else if( node_group != groups.last_endpoint_group-- ) {
                 // remove group (and decrement active back group)
                 const group_size_type group_size = static_cast<group_size_type>( node_group->beyond_end -
                                                    node_group->nodes );
                 node_allocator_pair.number_of_erased_nodes -= group_size;
                 if LIST_CONSTEXPR( !std::is_trivially_destructible<node_pointer_type>::value ) {
                     destroy_all_node_pointers( node_group, node_group->beyond_end );
                 }
                 node_group->free_list_head = nullptr;
                 // Preserve only last (active) group or second/third-to-last group - seems to be best for performance under high-modification benchmarks
                 if( ( group_size == LIST_BLOCK_MAX ) | ( node_group >= groups.last_endpoint_group - 1 ) ) {
                     groups.move_to_back( node_group );
                 } else {
                     groups.remove( node_group );
                 }
                 return return_iterator;
             } else { // clear back group, leave trailing
                 if LIST_CONSTEXPR( !std::is_trivially_destructible<node_pointer_type>::value ) {
                     destroy_all_node_pointers( node_group, last_endpoint );
                 }
                 node_group->free_list_head = nullptr;
                 if( node_pointer_allocator_pair.total_number_of_elements != 0 ) {
                     node_allocator_pair.number_of_erased_nodes -= static_cast<group_size_type>
                             ( last_endpoint - node_group->nodes );
                     last_endpoint = groups.last_endpoint_group->beyond_end;
                 } else {
                     // If number of elements is zero, it indicates that this was the first group in the vector. In which case the last_endpoint_group would be invalid at this point due to the decrement in the above else-if statement. So it needs to be reset, as it will not be reset in the function call below.
                     groups.last_endpoint_group = groups.block_pointer;
                     clear();
                 }
                 return return_iterator;
             }
         }
References cata::list< element_type, element_allocator_type >::group_vector::block_pointer, cata_assert, clear, cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, cata::list< element_type, element_allocator_type >::group_vector::last_searched_group, LIST_BLOCK_MAX, LIST_CONSTEXPR, LIST_DESTROY, cata::list< element_type, element_allocator_type >::group_vector::move_to_back(), cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, and cata::list< element_type, element_allocator_type >::group_vector::remove().
Referenced by cast_horizontal_zlight_segment(), and cast_vertical_zlight_segment().
erase() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::erase (const const_iterator iterator1, const const_iterator iterator2) inline
Definition at line 1811 of file list.h.
{
             for( const_iterator current = iterator1; current != iterator2; ) {
                 current = erase( current );
             }
         }
References catacurses::erase().
free_unused_memory()
template<class element_type , class element_allocator_type = std::allocator<element_type>> LIST_FORCE_INLINE void cata::list< element_type, element_allocator_type >::free_unused_memory () inline noexcept
Definition at line 2109 of file list.h.
{
             groups.trim_trailing_groups();
         }
References cata::list< element_type, element_allocator_type >::group_vector::trim_trailing_groups().
front() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> reference cata::list< element_type, element_allocator_type >::front () inline
Definition at line 1167 of file list.h.
{
             cata_assert( begin_iterator.node_pointer != &end_node );
             return begin_iterator.node_pointer->element;
         }
References cata_assert, and cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer.
front() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> const_reference cata::list< element_type, element_allocator_type >::front () const inline
Definition at line 1172 of file list.h.
{
             cata_assert( begin_iterator.node_pointer != &end_node );
             return begin_iterator.node_pointer->element;
         }
References cata_assert, and cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer.
get_allocator()
template<class element_type , class element_allocator_type = std::allocator<element_type>> allocator_type cata::list< element_type, element_allocator_type >::get_allocator () const inline noexcept
Definition at line 2443 of file list.h.
{
             return element_allocator_type();
         }
group_fill_position()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::group_fill_position (const element_type & element, group_size_type number_of_elements, node_pointer_type const position) inline private
Definition at line 1497 of file list.h.
{
             position->previous->next = last_endpoint;
             groups.last_endpoint_group->number_of_elements += number_of_elements;
             node_pointer_type previous = position->previous;
             do {
                 if LIST_CONSTEXPR( std::is_nothrow_copy_constructible<element_type>::value ) {
                     LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint, last_endpoint + 1,
                                     previous, element );
                 } else {
                     try {
                         LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint, last_endpoint + 1,
                                         previous, element );
                     } catch( ... ) {
                         previous->next = position;
                         position->previous = --previous;
                         groups.last_endpoint_group->number_of_elements -= static_cast<group_size_type>
                                 ( number_of_elements - ( last_endpoint - position ) );
                         throw;
                     }
                 }
                 previous = last_endpoint++;
             } while( --number_of_elements != 0 );
             previous->next = position;
             position->previous = previous;
         }
References cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, LIST_CONSTEXPR, and LIST_CONSTRUCT.
insert() [1/5]
template<class element_type , class element_allocator_type = std::allocator<element_type>> iterator cata::list< element_type, element_allocator_type >::insert (const iterator it, const element_type & element) inline
Definition at line 1218 of file list.h.
{
             // ie. list is not empty
             if( last_endpoint != nullptr ) {
                 // No erased nodes available for reuse
                 if( node_allocator_pair.number_of_erased_nodes == 0 ) {
                     // last_endpoint is beyond the end of a group
                     if( last_endpoint == groups.last_endpoint_group->beyond_end ) {
                         // ie. there are no reusable groups available at the back of group vector
                         if( static_cast<size_type>( groups.last_endpoint_group - groups.block_pointer ) == groups.size -
                             1 ) {
                             groups.add_new( ( node_pointer_allocator_pair.total_number_of_elements < LIST_BLOCK_MAX ) ?
                                             static_cast<group_size_type>( node_pointer_allocator_pair.total_number_of_elements ) :
                                             LIST_BLOCK_MAX );
                         } else {
                             ++groups.last_endpoint_group;
                         }
                         last_endpoint = groups.last_endpoint_group->nodes;
                     }
                     LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint, it.node_pointer,
                                     it.node_pointer->previous, element );
                     ++( groups.last_endpoint_group->number_of_elements );
                     ++node_pointer_allocator_pair.total_number_of_elements;
                     if( it.node_pointer == begin_iterator.node_pointer ) {
                         begin_iterator.node_pointer = last_endpoint;
                     }
                     it.node_pointer->previous->next = last_endpoint;
                     it.node_pointer->previous = last_endpoint;
                     return iterator( last_endpoint++ );
                 } else {
                     group_pointer_type const node_group = groups.get_nearest_freelist_group( (
                             it.node_pointer != end_iterator.node_pointer ) ? it.node_pointer : end_node.previous );
                     node_pointer_type const selected_node = node_group->free_list_head;
                     const node_pointer_type previous = node_group->free_list_head->previous;
                     LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, selected_node, it.node_pointer,
                                     it.node_pointer->previous, element );
                     node_group->free_list_head = previous;
                     ++( node_group->number_of_elements );
                     ++node_pointer_allocator_pair.total_number_of_elements;
                     --node_allocator_pair.number_of_erased_nodes;
                     it.node_pointer->previous->next = selected_node;
                     it.node_pointer->previous = selected_node;
                     if( it.node_pointer == begin_iterator.node_pointer ) {
                         begin_iterator.node_pointer = selected_node;
                     }
                     return iterator( selected_node );
                 }
             } else { // list is empty
                 // In case of prior reserve/clear call as opposed to being uninitialized
                 if( groups.block_pointer == nullptr ) {
                     groups.initialize( LIST_BLOCK_MIN );
                 }
                 groups.last_endpoint_group->number_of_elements = 1;
                 end_node.next = end_node.previous = last_endpoint = begin_iterator.node_pointer =
                                                         groups.last_endpoint_group->nodes;
                 node_pointer_allocator_pair.total_number_of_elements = 1;
                 if LIST_CONSTEXPR(
                     std::is_nothrow_copy_constructible<node>::value ) { // Avoid try-catch code generation
                     LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint++,
                                     end_iterator.node_pointer, end_iterator.node_pointer, element );
                 } else {
                     try {
                         LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint++,
                                         end_iterator.node_pointer, end_iterator.node_pointer, element );
                     } catch( ... ) {
                         reset();
                         throw;
                     }
                 }
                 return begin_iterator;
             }
         }
References cata::list< element_type, element_allocator_type >::group_vector::add_new(), cata::list< element_type, element_allocator_type >::group_vector::block_pointer, cata::list< element_type, element_allocator_type >::group_vector::get_nearest_freelist_group(), cata::list< element_type, element_allocator_type >::group_vector::initialize(), cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, LIST_BLOCK_MAX, LIST_BLOCK_MIN, LIST_CONSTEXPR, LIST_CONSTRUCT, cata::list< element_type, element_allocator_type >::node_base::next, cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, cata::list< element_type, element_allocator_type >::node_base::previous, and cata::list< element_type, element_allocator_type >::group_vector::size.
insert() [2/5]
template<class element_type , class element_allocator_type = std::allocator<element_type>> iterator cata::list< element_type, element_allocator_type >::insert (const iterator it, const std::initializer_list< element_type > & element_list) inline
Definition at line 1682 of file list.h.
{
             // use range insert:
             return insert( it, element_list.begin(), element_list.end() );
         }
insert() [3/5]
template<class element_type , class element_allocator_type = std::allocator<element_type>> iterator cata::list< element_type, element_allocator_type >::insert (const iterator it, element_type && element) inline
Definition at line 1313 of file list.h.
{
             if( last_endpoint != nullptr ) {
                 if( node_allocator_pair.number_of_erased_nodes == 0 ) {
                     if( last_endpoint == groups.last_endpoint_group->beyond_end ) {
                         if( static_cast<size_type>( groups.last_endpoint_group - groups.block_pointer ) == groups.size -
                             1 ) {
                             groups.add_new( ( node_pointer_allocator_pair.total_number_of_elements < LIST_BLOCK_MAX ) ?
                                             static_cast<group_size_type>( node_pointer_allocator_pair.total_number_of_elements ) :
                                             LIST_BLOCK_MAX );
                         } else {
                             ++groups.last_endpoint_group;
                         }
                         last_endpoint = groups.last_endpoint_group->nodes;
                     }
                     LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint, it.node_pointer,
                                     it.node_pointer->previous, std::move( element ) );
                     ++( groups.last_endpoint_group->number_of_elements );
                     ++node_pointer_allocator_pair.total_number_of_elements;
                     if( it.node_pointer == begin_iterator.node_pointer ) {
                         begin_iterator.node_pointer = last_endpoint;
                     }
                     it.node_pointer->previous->next = last_endpoint;
                     it.node_pointer->previous = last_endpoint;
                     return iterator( last_endpoint++ );
                 } else {
                     group_pointer_type const node_group = groups.get_nearest_freelist_group( (
                             it.node_pointer != end_iterator.node_pointer ) ? it.node_pointer : end_node.previous );
                     node_pointer_type const selected_node = node_group->free_list_head;
                     const node_pointer_type previous = node_group->free_list_head->previous;
                     LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, selected_node, it.node_pointer,
                                     it.node_pointer->previous, std::move( element ) );
                     node_group->free_list_head = previous;
                     ++( node_group->number_of_elements );
                     ++node_pointer_allocator_pair.total_number_of_elements;
                     --node_allocator_pair.number_of_erased_nodes;
                     it.node_pointer->previous->next = selected_node;
                     it.node_pointer->previous = selected_node;
                     if( it.node_pointer == begin_iterator.node_pointer ) {
                         begin_iterator.node_pointer = selected_node;
                     }
                     return iterator( selected_node );
                 }
             } else {
                 if( groups.block_pointer == nullptr ) {
                     groups.initialize( LIST_BLOCK_MIN );
                 }
                 groups.last_endpoint_group->number_of_elements = 1;
                 end_node.next = end_node.previous = last_endpoint = begin_iterator.node_pointer =
                                                         groups.last_endpoint_group->nodes;
                 node_pointer_allocator_pair.total_number_of_elements = 1;
                 if LIST_CONSTEXPR( std::is_nothrow_move_constructible<node>::value ) {
                     LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint++,
                                     end_iterator.node_pointer, end_iterator.node_pointer, std::move( element ) );
                 } else {
                     try {
                         LIST_CONSTRUCT( node_allocator_type, node_allocator_pair, last_endpoint++,
                                         end_iterator.node_pointer, end_iterator.node_pointer, std::move( element ) );
                     } catch( ... ) {
                         reset();
                         throw;
                     }
                 }
                 return begin_iterator;
             }
         }
References cata::list< element_type, element_allocator_type >::group_vector::add_new(), cata::list< element_type, element_allocator_type >::group_vector::block_pointer, cata::list< element_type, element_allocator_type >::group_vector::get_nearest_freelist_group(), cata::list< element_type, element_allocator_type >::group_vector::initialize(), cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, LIST_BLOCK_MAX, LIST_BLOCK_MIN, LIST_CONSTEXPR, LIST_CONSTRUCT, cata::list< element_type, element_allocator_type >::node_base::next, cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, cata::list< element_type, element_allocator_type >::node_base::previous, and cata::list< element_type, element_allocator_type >::group_vector::size.
insert() [4/5]
template<class element_type , class element_allocator_type = std::allocator<element_type>> template<class iterator_type > iterator cata::list< element_type, element_allocator_type >::insert (const iterator it, typename plf_enable_if_c< !std::numeric_limits< iterator_type >::is_integer, iterator_type >::type first, const iterator_type last) inline
Definition at line 1665 of file list.h.
{
             if( first == last ) {
                 return end_iterator;
             }
             const iterator return_iterator = insert( it, *first );
             while( ++first != last ) {
                 insert( it, *first );
             }
             return return_iterator;
         }
References last.
insert() [5/5]
template<class element_type , class element_allocator_type = std::allocator<element_type>> iterator cata::list< element_type, element_allocator_type >::insert (iterator position, const size_type number_of_elements, const element_type & element) inline
Definition at line 1530 of file list.h.
{
             if( number_of_elements == 0 ) {
                 return end_iterator;
             } else if( number_of_elements == 1 ) {
                 return insert( position, element );
             }
             if( node_pointer_allocator_pair.total_number_of_elements == 0 && last_endpoint != nullptr &&
                 ( static_cast<size_type>( groups.block_pointer->beyond_end - groups.block_pointer->nodes ) <
                   number_of_elements ) &&
                 ( static_cast<size_type>( groups.block_pointer->beyond_end - groups.block_pointer->nodes ) <
                   LIST_BLOCK_MAX ) ) {
                 reset();
             }
             if( groups.block_pointer == nullptr ) { // ie. Uninitialized list
                 if( number_of_elements > LIST_BLOCK_MAX ) {
                     size_type multiples = number_of_elements / LIST_BLOCK_MAX;
                     const group_size_type remainder = static_cast<group_size_type>( number_of_elements -
                                                       ( multiples++ * LIST_BLOCK_MAX ) ); // ++ to aid while loop below
                     // Create and fill first group:
                     if( remainder != 0 ) { // make sure smallest block is first
                         if( remainder >= LIST_BLOCK_MIN ) {
                             groups.initialize( remainder );
                             end_node.next = end_node.previous = last_endpoint = begin_iterator.node_pointer =
                                                                     groups.last_endpoint_group->nodes;
                             group_fill_position( element, remainder, end_iterator.node_pointer );
                         } else {
                             // Create first group as BLOCK_MIN size then subtract difference between BLOCK_MIN and remainder from next group:
                             groups.initialize( LIST_BLOCK_MIN );
                             end_node.next = end_node.previous = last_endpoint = begin_iterator.node_pointer =
                                                                     groups.last_endpoint_group->nodes;
                             group_fill_position( element, LIST_BLOCK_MIN, end_iterator.node_pointer );
                             groups.add_new( LIST_BLOCK_MAX - ( LIST_BLOCK_MIN - remainder ) );
                             end_node.previous = last_endpoint = groups.last_endpoint_group->nodes;
                             group_fill_position( element, LIST_BLOCK_MAX - ( LIST_BLOCK_MIN - remainder ),
                                                  end_iterator.node_pointer );
                             --multiples;
                         }
                     } else {
                         groups.initialize( LIST_BLOCK_MAX );
                         end_node.next = end_node.previous = last_endpoint = begin_iterator.node_pointer =
                                                                 groups.last_endpoint_group->nodes;
                         group_fill_position( element, LIST_BLOCK_MAX, end_iterator.node_pointer );
                         --multiples;
                     }
                     while( --multiples != 0 ) {
                         groups.add_new( LIST_BLOCK_MAX );
                         end_node.previous = last_endpoint = groups.last_endpoint_group->nodes;
                         group_fill_position( element, LIST_BLOCK_MAX, end_iterator.node_pointer );
                     }
                 } else {
                     groups.initialize( ( number_of_elements < LIST_BLOCK_MIN ) ? LIST_BLOCK_MIN :
                                        static_cast<group_size_type>( number_of_elements ) ); // Construct first group
                     end_node.next = end_node.previous = last_endpoint = begin_iterator.node_pointer =
                                                             groups.last_endpoint_group->nodes;
                     group_fill_position( element, static_cast<group_size_type>( number_of_elements ),
                                          end_iterator.node_pointer );
                 }
                 node_pointer_allocator_pair.total_number_of_elements = number_of_elements;
                 return begin_iterator;
             } else {
                 // Insert first element, then use up any erased nodes:
                 size_type remainder = number_of_elements - 1;
                 const iterator return_iterator = insert( position, element );
                 while( node_allocator_pair.number_of_erased_nodes != 0 ) {
                     insert( position, element );
                     --node_allocator_pair.number_of_erased_nodes;
                     if( --remainder == 0 ) {
                         return return_iterator;
                     }
                 }
                 node_pointer_allocator_pair.total_number_of_elements += remainder;
                 // then use up remainder of last_endpoint_group:
                 const group_size_type remaining_nodes_in_group = static_cast<group_size_type>
                         ( groups.last_endpoint_group->beyond_end - last_endpoint );
                 if( remaining_nodes_in_group != 0 ) {
                     if( remaining_nodes_in_group < remainder ) {
                         group_fill_position( element, remaining_nodes_in_group, position.node_pointer );
                         remainder -= remaining_nodes_in_group;
                     } else {
                         group_fill_position( element, static_cast<group_size_type>( remainder ), position.node_pointer );
                         return return_iterator;
                     }
                 }
                 // use up trailing groups:
                 while( ( groups.last_endpoint_group != ( groups.block_pointer + groups.size - 1 ) ) &
                        ( remainder != 0 ) ) {
                     last_endpoint = ( ++groups.last_endpoint_group )->nodes;
                     const group_size_type group_size = static_cast<group_size_type>
                                                        ( groups.last_endpoint_group->beyond_end - groups.last_endpoint_group->nodes );
                     if( group_size < remainder ) {
                         group_fill_position( element, group_size, position.node_pointer );
                         remainder -= group_size;
                     } else {
                         group_fill_position( element, static_cast<group_size_type>( remainder ), position.node_pointer );
                         return return_iterator;
                     }
                 }
                 size_type multiples = remainder / static_cast<size_type>( LIST_BLOCK_MAX );
                 remainder -= multiples * LIST_BLOCK_MAX;
                 while( multiples-- != 0 ) {
                     groups.add_new( LIST_BLOCK_MAX );
                     last_endpoint = groups.last_endpoint_group->nodes;
                     group_fill_position( element, LIST_BLOCK_MAX, position.node_pointer );
                 }
                 if( remainder !=
                     0 ) { // Bit annoying to create a large block to house a lower number of elements, but beats the alternatives
                     groups.add_new( LIST_BLOCK_MAX );
                     last_endpoint = groups.last_endpoint_group->nodes;
                     group_fill_position( element, static_cast<group_size_type>( remainder ), position.node_pointer );
                 }
                 return return_iterator;
             }
         }
References cata::list< element_type, element_allocator_type >::group_vector::add_new(), cata::list< element_type, element_allocator_type >::group_vector::block_pointer, cata::list< element_type, element_allocator_type >::group_vector::initialize(), cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, LIST_BLOCK_MAX, LIST_BLOCK_MIN, cata::list< element_type, element_allocator_type >::node_base::next, cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, cata::list< element_type, element_allocator_type >::node_base::previous, and cata::list< element_type, element_allocator_type >::group_vector::size.
max_size()
template<class element_type , class element_allocator_type = std::allocator<element_type>> size_type cata::list< element_type, element_allocator_type >::max_size () const inline noexcept
Definition at line 1890 of file list.h.
{
             return std::allocator_traits<element_allocator_type>::max_size( *this );
         }
merge() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::merge (list< element_type, element_allocator_type > & source) inline
Definition at line 2199 of file list.h.
{
             cata_assert( &source != this );
             if( source.node_pointer_allocator_pair.total_number_of_elements == 0 ) {
                 return;
             } else if( node_pointer_allocator_pair.total_number_of_elements == 0 ) {
                 *this = std::move( source );
                 return;
             }
             node_pointer_type current1 = begin_iterator.node_pointer->next;
             node_pointer_type current2 = source.begin_iterator.node_pointer->next;
             node_pointer_type previous = source.begin_iterator.node_pointer;
             const node_pointer_type source_end = source.end_iterator.node_pointer;
             const node_pointer_type this_end = end_iterator.node_pointer;
             begin_iterator.node_pointer->next = source.begin_iterator.node_pointer;
             source.begin_iterator.node_pointer->previous = begin_iterator.node_pointer;
             while( ( current1 != this_end ) & ( current2 != source_end ) ) {
                 previous->next = current1;
                 current1->previous = previous;
                 previous = current1;
                 current1 = current1->next;
                 previous->next = current2;
                 current2->previous = previous;
                 previous = current2;
                 current2 = current2->next;
             }
             if( current1 != this_end ) {
                 previous->next = current1;
                 current1->previous = previous;
             } else {
                 end_node.previous = source.end_node.previous;
                 source.end_node.previous->next = end_iterator.node_pointer;
             }
             append_process( source );
         }
References cata::list< element_type, element_allocator_type >::begin_iterator, cata_assert, cata::list< element_type, element_allocator_type >::end_iterator, cata::list< element_type, element_allocator_type >::end_node, cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, cata::list< element_type, element_allocator_type >::node_pointer_allocator_pair, cata::list< element_type, element_allocator_type >::node_base::previous, and cata::list< element_type, element_allocator_type >::ebco_pair1::total_number_of_elements.
merge() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> template<class comparison_function > void cata::list< element_type, element_allocator_type >::merge (list< element_type, element_allocator_type > & source, comparison_function compare) inline
Definition at line 2192 of file list.h.
{
             cata_assert( &source != this );
             splice( ( source.node_pointer_allocator_pair.total_number_of_elements >=
                       node_pointer_allocator_pair.total_number_of_elements ) ? end_iterator : begin_iterator, source );
             sort( compare );
         }
References cata_assert, game_menus::inv::compare(), cata::list< element_type, element_allocator_type >::node_pointer_allocator_pair, and cata::list< element_type, element_allocator_type >::ebco_pair1::total_number_of_elements.
operator!=()
template<class element_type , class element_allocator_type = std::allocator<element_type>> bool cata::list< element_type, element_allocator_type >::operator!= (const list< element_type, element_allocator_type > & rh) const inline noexcept
Definition at line 1878 of file list.h.
{
             return !( *this == rh );
         }
operator=() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> list& cata::list< element_type, element_allocator_type >::operator= (const list< element_type, element_allocator_type > & source) inline
Definition at line 1825 of file list.h.
{
             cata_assert( &source != this );
             clear();
             reserve( source.node_pointer_allocator_pair.total_number_of_elements );
             insert( end_iterator, source.begin_iterator, source.end_iterator );
             return *this;
         }
References cata::list< element_type, element_allocator_type >::begin_iterator, cata_assert, clear, cata::list< element_type, element_allocator_type >::end_iterator, cata::list< element_type, element_allocator_type >::node_pointer_allocator_pair, and cata::list< element_type, element_allocator_type >::ebco_pair1::total_number_of_elements.
operator=() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> list& cata::list< element_type, element_allocator_type >::operator= (list< element_type, element_allocator_type > && source) inline
Definition at line 1836 of file list.h.
{
             cata_assert( &source != this );
             // Move source values across:
             groups.destroy_all_data( last_endpoint );
             groups = std::move( source.groups );
             end_node = std::move( source.end_node );
             last_endpoint = std::move( source.last_endpoint );
             begin_iterator.node_pointer = ( source.begin_iterator.node_pointer ==
                                             source.end_iterator.node_pointer ) ? end_iterator.node_pointer : std::move(
                                               source.begin_iterator.node_pointer );
             node_pointer_allocator_pair.total_number_of_elements =
                 source.node_pointer_allocator_pair.total_number_of_elements;
             node_allocator_pair.number_of_erased_nodes = source.node_allocator_pair.number_of_erased_nodes;
             end_node.previous->next = begin_iterator.node_pointer->previous = end_iterator.node_pointer;
             source.groups.blank();
             source.reset();
             return *this;
         }
References cata_assert, cata::list< element_type, element_allocator_type >::group_vector::destroy_all_data(), cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, and cata::list< element_type, element_allocator_type >::node_base::previous.
operator==()
template<class element_type , class element_allocator_type = std::allocator<element_type>> bool cata::list< element_type, element_allocator_type >::operator== (const list< element_type, element_allocator_type > & rh) const inline noexcept
Definition at line 1859 of file list.h.
{
             cata_assert( this != &rh );
             if( node_pointer_allocator_pair.total_number_of_elements !=
                 rh.node_pointer_allocator_pair.total_number_of_elements ) {
                 return false;
             }
             iterator rh_iterator = rh.begin_iterator;
             for( iterator lh_iterator = begin_iterator; lh_iterator != end_iterator; ) {
                 if( *rh_iterator++ != *lh_iterator++ ) {
                     return false;
                 }
             }
             return true;
         }
References cata_assert.
pop_back()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::pop_back () inline
Definition at line 1817 of file list.h.
                                { // Exception will occur on empty list
             erase( iterator( end_node.previous ) );
         }
References catacurses::erase(), and cata::list< element_type, element_allocator_type >::node_base::previous.
pop_front()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::pop_front () inline
Definition at line 1821 of file list.h.
                                 { // Exception will occur on empty list
             erase( begin_iterator );
         }
References catacurses::erase().
push_back() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> LIST_FORCE_INLINE void cata::list< element_type, element_allocator_type >::push_back (const element_type & element) inline
Definition at line 1304 of file list.h.
{
             insert( end_iterator, element );
         }
push_back() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> LIST_FORCE_INLINE void cata::list< element_type, element_allocator_type >::push_back (element_type && element) inline
Definition at line 1394 of file list.h.
{
             insert( end_iterator, std::move( element ) );
         }
push_front() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> LIST_FORCE_INLINE void cata::list< element_type, element_allocator_type >::push_front (const element_type & element) inline
Definition at line 1308 of file list.h.
{
             insert( begin_iterator, element );
         }
push_front() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> LIST_FORCE_INLINE void cata::list< element_type, element_allocator_type >::push_front (element_type && element) inline
Definition at line 1398 of file list.h.
{
             insert( begin_iterator, std::move( element ) );
         }
rbegin()
template<class element_type , class element_allocator_type = std::allocator<element_type>> reverse_iterator cata::list< element_type, element_allocator_type >::rbegin () const inline noexcept
Definition at line 1151 of file list.h.
{
             return reverse_iterator( end_node.previous );
         }
References cata::list< element_type, element_allocator_type >::node_base::previous.
remove()
template<class element_type , class element_allocator_type = std::allocator<element_type>> size_type cata::list< element_type, element_allocator_type >::remove (const element_type & value) inline
Definition at line 2394 of file list.h.
{
             return remove_if( eq_to( value ) );
         }
remove_if()
template<class element_type , class element_allocator_type = std::allocator<element_type>> template<class predicate_function > size_type cata::list< element_type, element_allocator_type >::remove_if (predicate_function predicate) inline
Definition at line 2325 of file list.h.
{
             const size_type original_number_of_elements = node_pointer_allocator_pair.total_number_of_elements;
             if( original_number_of_elements != 0 ) {
                 for( group_pointer_type current_group = groups.block_pointer;
                      current_group != groups.last_endpoint_group; ++current_group ) {
                     group_size_type num_elements = current_group->number_of_elements;
                     const node_pointer_type end = current_group->beyond_end;
                     // If there are erased nodes present in the group
                     if( end - current_group->nodes != num_elements ) {
                         for( node_pointer_type current_node = current_group->nodes; current_node != end; ++current_node ) {
                             // is not free list node and validates predicate
                             if( current_node->next != nullptr && predicate( current_node->element ) ) {
                                 erase( current_node );
                                 // i.e. group will be empty (and removed) now - nothing left to iterate over
                                 if( --num_elements == 0 ) {
                                     // As current group has been removed, subsequent groups have already shifted back by one, hence, the ++ to the current group in the for loop is unnecessary, and negated here
                                     --current_group;
                                     break;
                                 }
                             }
                         }
                     } else { // No erased nodes in group
                         for( node_pointer_type current_node = current_group->nodes; current_node != end; ++current_node ) {
                             if( predicate( current_node->element ) ) {
                                 erase( current_node );
                                 if( --num_elements == 0 ) {
                                     --current_group;
                                     break;
                                 }
                             }
                         }
                     }
                 }
                 group_size_type num_elements = groups.last_endpoint_group->number_of_elements;
                 // If there are erased nodes present in the group
                 if( last_endpoint - groups.last_endpoint_group->nodes != num_elements ) {
                     for( node_pointer_type current_node = groups.last_endpoint_group->nodes;
                          current_node != last_endpoint; ++current_node ) {
                         if( current_node->next != nullptr && predicate( current_node->element ) ) {
                             erase( current_node );
                             if( --num_elements == 0 ) {
                                 break;
                             }
                         }
                     }
                 } else {
                     for( node_pointer_type current_node = groups.last_endpoint_group->nodes;
                          current_node != last_endpoint; ++current_node ) {
                         if( predicate( current_node->element ) ) {
                             erase( current_node );
                             if( --num_elements == 0 ) {
                                 break;
                             }
                         }
                     }
                 }
             }
             return original_number_of_elements - node_pointer_allocator_pair.total_number_of_elements;
         }
References cata::list< element_type, element_allocator_type >::group_vector::block_pointer, keycode::end, catacurses::erase(), and cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group.
rend()
template<class element_type , class element_allocator_type = std::allocator<element_type>> reverse_iterator cata::list< element_type, element_allocator_type >::rend () const inline noexcept
Definition at line 1155 of file list.h.
{
             return reverse_iterator( end_iterator.node_pointer );
         }
References cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer.
reorder() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::reorder (const iterator position, const iterator first, const iterator last) inline noexcept
Definition at line 2014 of file list.h.
{
             last.node_pointer->next->previous = first.node_pointer->previous;
             first.node_pointer->previous->next = last.node_pointer->next;
             last.node_pointer->next = position.node_pointer;
             first.node_pointer->previous = position.node_pointer->previous;
             position.node_pointer->previous->next = first.node_pointer;
             position.node_pointer->previous = last.node_pointer;
             if( begin_iterator == position ) {
                 begin_iterator = first;
             }
         }
References last.
reorder() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::reorder (const iterator position, const iterator location) inline noexcept
Definition at line 2029 of file list.h.
{
             reorder( position, location, location );
         }
References location.
reserve()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::reserve (size_type reserve_amount) inline
Definition at line 2033 of file list.h.
{
             if( reserve_amount == 0 || reserve_amount <= groups.element_allocator_pair.capacity ) {
                 return;
             } else if( reserve_amount < LIST_BLOCK_MIN ) {
                 reserve_amount = LIST_BLOCK_MIN;
             } else if( reserve_amount > max_size() ) {
                 reserve_amount = max_size();
             }
             if( groups.block_pointer != nullptr && node_pointer_allocator_pair.total_number_of_elements == 0 ) {
                 // edge case: has been filled with elements then clear()'d - some groups may be smaller than would be desired, should be replaced
                 group_size_type end_group_size = static_cast<group_size_type>( ( groups.block_pointer + groups.size
                                                  - 1 )->beyond_end - ( groups.block_pointer + groups.size - 1 )->nodes );
                 // if last group isn't large enough, remove all groups
                 if( reserve_amount > end_group_size && end_group_size != LIST_BLOCK_MAX ) {
                     reset();
                 } else {
                     size_type number_of_full_groups_needed = reserve_amount / LIST_BLOCK_MAX;
                     group_size_type remainder = static_cast<group_size_type>( reserve_amount -
                                                 ( number_of_full_groups_needed * LIST_BLOCK_MAX ) );
                     // Remove any max_size groups which're not needed and any groups that're smaller than remainder:
                     for( group_pointer_type current_group = groups.block_pointer;
                          current_group < groups.block_pointer + groups.size; ) {
                         const group_size_type current_group_size = static_cast<group_size_type>
                                 ( groups.block_pointer->beyond_end - groups.block_pointer->nodes );
                         if( number_of_full_groups_needed != 0 && current_group_size == LIST_BLOCK_MAX ) {
                             --number_of_full_groups_needed;
                             ++current_group;
                         } else if( remainder != 0 && current_group_size >= remainder ) {
                             remainder = 0;
                             ++current_group;
                         } else {
                             groups.remove( current_group );
                         }
                     }
                     last_endpoint = groups.block_pointer->nodes;
                 }
             }
             reserve_amount -= groups.element_allocator_pair.capacity;
             // To correct from possible reallocation caused by add_new:
             const difference_type last_endpoint_group_number = groups.last_endpoint_group -
                     groups.block_pointer;
             size_type number_of_full_groups = reserve_amount / LIST_BLOCK_MAX;
             reserve_amount -= ( number_of_full_groups++ * LIST_BLOCK_MAX ); // ++ to aid while loop below
             // Previously uninitialized list or reset in above if statement; most common scenario
             if( groups.block_pointer == nullptr ) {
                 if( reserve_amount != 0 ) {
                     groups.initialize( static_cast<group_size_type>( ( ( reserve_amount < LIST_BLOCK_MIN ) ?
                                        LIST_BLOCK_MIN : reserve_amount ) ) );
                 } else {
                     groups.initialize( LIST_BLOCK_MAX );
                     --number_of_full_groups;
                 }
             } else if( reserve_amount != 0 ) {
                 // Create a group at least as large as the last group - may allocate more than necessary, but better solution than creating a very small group in the middle of the group vector, I think:
                 const group_size_type last_endpoint_group_capacity = static_cast<group_size_type>
                         ( groups.last_endpoint_group->beyond_end - groups.last_endpoint_group->nodes );
                 groups.add_new( static_cast<group_size_type>( ( reserve_amount < last_endpoint_group_capacity ) ?
                                 last_endpoint_group_capacity : reserve_amount ) );
             }
             while( --number_of_full_groups != 0 ) {
                 groups.add_new( LIST_BLOCK_MAX );
             }
             groups.last_endpoint_group = groups.block_pointer + last_endpoint_group_number;
         }
References cata::list< element_type, element_allocator_type >::group_vector::add_new(), cata::list< element_type, element_allocator_type >::group_vector::block_pointer, cata::list< element_type, element_allocator_type >::group_vector::ebco_pair2::capacity, cata::list< element_type, element_allocator_type >::group_vector::element_allocator_pair, cata::list< element_type, element_allocator_type >::group_vector::initialize(), cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, LIST_BLOCK_MAX, LIST_BLOCK_MIN, cata::list< element_type, element_allocator_type >::group_vector::remove(), and cata::list< element_type, element_allocator_type >::group_vector::size.
reset()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::reset () inline private noexcept
Definition at line 1206 of file list.h.
{
             groups.destroy_all_data( last_endpoint );
             last_endpoint = nullptr;
             end_node.next = reinterpret_cast<node_pointer_type>( &end_node );
             end_node.previous = reinterpret_cast<node_pointer_type>( &end_node );
             begin_iterator.node_pointer = end_iterator.node_pointer;
             node_pointer_allocator_pair.total_number_of_elements = 0;
             node_allocator_pair.number_of_erased_nodes = 0;
         }
References cata::list< element_type, element_allocator_type >::group_vector::destroy_all_data(), cata::list< element_type, element_allocator_type >::node_base::next, cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, and cata::list< element_type, element_allocator_type >::node_base::previous.
Referenced by cata::list< element_type, element_allocator_type >::append_process().
resize()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::resize (const size_type number_of_elements, const element_type & value = element_type()) inline
Definition at line 2398 of file list.h.
{
             if( node_pointer_allocator_pair.total_number_of_elements == number_of_elements ) {
                 return;
             } else if( number_of_elements == 0 ) {
                 clear();
                 return;
             } else if( node_pointer_allocator_pair.total_number_of_elements < number_of_elements ) {
                 insert( end_iterator, number_of_elements - node_pointer_allocator_pair.total_number_of_elements,
                         value );
             } else { // ie. node_pointer_allocator_pair.total_number_of_elements > number_of_elements
                 iterator current( end_node.previous );
                 for( size_type number_to_remove = node_pointer_allocator_pair.total_number_of_elements -
                                                   number_of_elements; number_to_remove != 0; --number_to_remove ) {
                     const node_pointer_type temp = current.node_pointer->previous;
                     erase( current );
                     current.node_pointer = temp;
                 }
             }
         }
References clear, catacurses::erase(), cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, cata::list< element_type, element_allocator_type >::node_base::previous, and temp.
reverse()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::reverse () inline noexcept
Definition at line 2241 of file list.h.
{
             if( node_pointer_allocator_pair.total_number_of_elements > 1 ) {
                 for( group_pointer_type current_group = groups.block_pointer;
                      current_group != groups.last_endpoint_group; ++current_group ) {
                     const node_pointer_type end = current_group->beyond_end;
                     for( node_pointer_type current_node = current_group->nodes; current_node != end; ++current_node ) {
                         if( current_node->next != nullptr ) { // is not free list node
                             // swap the pointers:
                             const node_pointer_type temp = current_node->next;
                             current_node->next = current_node->previous;
                             current_node->previous = temp;
                         }
                     }
                 }
                 for( node_pointer_type current_node = groups.last_endpoint_group->nodes;
                      current_node != last_endpoint; ++current_node ) {
                     if( current_node->next != nullptr ) {
                         const node_pointer_type temp = current_node->next;
                         current_node->next = current_node->previous;
                         current_node->previous = temp;
                     }
                 }
                 const node_pointer_type temp = end_node.previous;
                 end_node.previous = begin_iterator.node_pointer;
                 begin_iterator.node_pointer = temp;
                 end_node.previous->next = end_iterator.node_pointer;
                 begin_iterator.node_pointer->previous = end_iterator.node_pointer;
             }
         }
References cata::list< element_type, element_allocator_type >::group_vector::block_pointer, keycode::end, cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, cata::list< element_type, element_allocator_type >::node_base::previous, and temp.
shrink_to_fit()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::shrink_to_fit () inline
Definition at line 2113 of file list.h.
{
             if( ( last_endpoint == nullptr ) | ( node_pointer_allocator_pair.total_number_of_elements ==
                                                  groups.element_allocator_pair.capacity ) ) { // uninitialized list or full
                 return;
             } else if( node_pointer_allocator_pair.total_number_of_elements == 0 ) { // Edge case
                 reset();
                 return;
             } else if( node_allocator_pair.number_of_erased_nodes == 0 &&
                        last_endpoint ==
                        groups.last_endpoint_group->beyond_end ) { //edge case - currently no waste except for possible trailing groups
                 groups.trim_trailing_groups();
                 return;
             }
             list temp;
             temp.reserve( node_pointer_allocator_pair.total_number_of_elements );
             if LIST_CONSTEXPR( std::is_move_assignable<element_type>::value &&
                                std::is_move_constructible<element_type>::value ) { // move elements if possible, otherwise copy them
                 temp.insert( temp.end_iterator, std::make_move_iterator( begin_iterator ),
                              std::make_move_iterator( end_iterator ) );
             } else {
                 temp.insert( temp.end_iterator, begin_iterator, end_iterator );
             }
             *this = std::move( temp );
         }
References cata::list< element_type, element_allocator_type >::group_vector::ebco_pair2::capacity, cata::list< element_type, element_allocator_type >::group_vector::element_allocator_pair, cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, LIST_CONSTEXPR, temp, and cata::list< element_type, element_allocator_type >::group_vector::trim_trailing_groups().
size()
template<class element_type , class element_allocator_type = std::allocator<element_type>> size_type cata::list< element_type, element_allocator_type >::size () const inline noexcept
Definition at line 1886 of file list.h.
{
             return node_pointer_allocator_pair.total_number_of_elements;
         }
sort() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::sort () inline
Definition at line 2010 of file list.h.
{
             sort( less() );
         }
sort() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> template<class comparison_function > void cata::list< element_type, element_allocator_type >::sort (comparison_function compare) inline
Definition at line 1930 of file list.h.
{
             if( node_pointer_allocator_pair.total_number_of_elements < 2 ) {
                 return;
             }
             node_pointer_type *const node_pointers = LIST_ALLOCATE( node_pointer_allocator_type,
                     node_pointer_allocator_pair, node_pointer_allocator_pair.total_number_of_elements, nullptr );
             node_pointer_type *node_pointer = node_pointers;
             // According to the C++ standard, construction of a pointer (of any type) may not trigger an exception - hence, no try-catch blocks are necessary for constructing the pointers:
             for( group_pointer_type current_group = groups.block_pointer;
                  current_group != groups.last_endpoint_group; ++current_group ) {
                 const node_pointer_type end = current_group->beyond_end;
                 if( ( end - current_group->nodes ) !=
                     current_group->number_of_elements ) { // If there are erased nodes present in the group
                     for( node_pointer_type current_node = current_group->nodes; current_node != end; ++current_node ) {
                         if( current_node->next != nullptr ) { // is not free list node
                             LIST_CONSTRUCT( node_pointer_allocator_type, node_pointer_allocator_pair, node_pointer++,
                                             current_node );
                         }
                     }
                 } else {
                     for( node_pointer_type current_node = current_group->nodes; current_node != end; ++current_node ) {
                         LIST_CONSTRUCT( node_pointer_allocator_type, node_pointer_allocator_pair, node_pointer++,
                                         current_node );
                     }
                 }
             }
             if( ( last_endpoint - groups.last_endpoint_group->nodes ) !=
                 groups.last_endpoint_group->number_of_elements ) { // If there are erased nodes present in the group
                 for( node_pointer_type current_node = groups.last_endpoint_group->nodes;
                      current_node != last_endpoint; ++current_node ) {
                     if( current_node->next != nullptr ) {
                         LIST_CONSTRUCT( node_pointer_allocator_type, node_pointer_allocator_pair, node_pointer++,
                                         current_node );
                     }
                 }
             } else {
                 for( node_pointer_type current_node = groups.last_endpoint_group->nodes;
                      current_node != last_endpoint; ++current_node ) {
                     LIST_CONSTRUCT( node_pointer_allocator_type, node_pointer_allocator_pair, node_pointer++,
                                     current_node );
                 }
             }
             std::sort( node_pointers, node_pointers + node_pointer_allocator_pair.total_number_of_elements,
                        sort_dereferencer<comparison_function>( compare ) );
             begin_iterator.node_pointer = node_pointers[0];
             begin_iterator.node_pointer->next = node_pointers[1];
             begin_iterator.node_pointer->previous = end_iterator.node_pointer;
             end_node.next = node_pointers[0];
             end_node.previous = node_pointers[node_pointer_allocator_pair.total_number_of_elements - 1];
             end_node.previous->next = end_iterator.node_pointer;
             end_node.previous->previous = node_pointers[node_pointer_allocator_pair.total_number_of_elements -
                                                                                                2];
             node_pointer_type *const back = node_pointers +
                                             node_pointer_allocator_pair.total_number_of_elements - 1;
             for( node_pointer = node_pointers + 1; node_pointer != back; ++node_pointer ) {
                 ( *node_pointer )->next = *( node_pointer + 1 );
                 ( *node_pointer )->previous = *( node_pointer - 1 );
                 if LIST_CONSTEXPR( !std::is_trivially_destructible<node_pointer_type>::value ) {
                     LIST_DESTROY( node_pointer_allocator_type, node_pointer_allocator_pair, node_pointer - 1 );
                 }
             }
             if LIST_CONSTEXPR( !std::is_trivially_destructible<node_pointer_type>::value ) {
                 LIST_DESTROY( node_pointer_allocator_type, node_pointer_allocator_pair, back );
             }
             LIST_DEALLOCATE( node_pointer_allocator_type, node_pointer_allocator_pair, node_pointers,
                              node_pointer_allocator_pair.total_number_of_elements );
         }
References cata::list< element_type, element_allocator_type >::group_vector::block_pointer, game_menus::inv::compare(), keycode::end, cata::list< element_type, element_allocator_type >::group_vector::last_endpoint_group, LIST_ALLOCATE, LIST_CONSTEXPR, LIST_CONSTRUCT, LIST_DEALLOCATE, LIST_DESTROY, cata::list< element_type, element_allocator_type >::node_base::next, cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, and cata::list< element_type, element_allocator_type >::node_base::previous.
splice()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::splice (iterator position, list< element_type, element_allocator_type > & source) inline
Definition at line 2167 of file list.h.
{
             cata_assert( &source != this );
             if( source.node_pointer_allocator_pair.total_number_of_elements == 0 ) {
                 return;
             } else if( node_pointer_allocator_pair.total_number_of_elements == 0 ) {
                 *this = std::move( source );
                 return;
             }
             if( position.node_pointer ==
                 begin_iterator.node_pointer ) { // put source groups at front rather than back
                 swap( source );
                 position.node_pointer = end_iterator.node_pointer;
             }
             position.node_pointer->previous->next = source.begin_iterator.node_pointer;
             source.begin_iterator.node_pointer->previous = position.node_pointer->previous;
             position.node_pointer->previous = source.end_node.previous;
             source.end_node.previous->next = position.node_pointer;
             append_process( source );
         }
References cata::list< element_type, element_allocator_type >::begin_iterator, cata_assert, cata::list< element_type, element_allocator_type >::end_node, cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer, cata::list< element_type, element_allocator_type >::node_pointer_allocator_pair, cata::list< element_type, element_allocator_type >::node_base::previous, cata::swap(), and cata::list< element_type, element_allocator_type >::ebco_pair1::total_number_of_elements.
swap()
template<class element_type , class element_allocator_type = std::allocator<element_type>> void cata::list< element_type, element_allocator_type >::swap (list< element_type, element_allocator_type > & source) inline
Definition at line 2447 of file list.h.
{
             list temp( std::move( source ) );
             source = std::move( *this );
             *this = std::move( temp );
         }
References temp.
unique() [1/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> size_type cata::list< element_type, element_allocator_type >::unique () inline
Definition at line 2320 of file list.h.
{
             return unique( eq() );
         }
References math_opers::eq().
unique() [2/2]
template<class element_type , class element_allocator_type = std::allocator<element_type>> template<class comparison_function > size_type cata::list< element_type, element_allocator_type >::unique (comparison_function compare) inline
Definition at line 2302 of file list.h.
{
             const size_type original_number_of_elements = node_pointer_allocator_pair.total_number_of_elements;
             if( original_number_of_elements > 1 ) {
                 element_type *previous = &( begin_iterator.node_pointer->element );
                 for( iterator current = ++iterator( begin_iterator ); current != end_iterator; ) {
                     if( compare( *current, *previous ) ) {
                         current = erase( current );
                     } else {
                         previous = &( current++.node_pointer->element );
                     }
                 }
             }
             return original_number_of_elements - node_pointer_allocator_pair.total_number_of_elements;
         }
References game_menus::inv::compare(), catacurses::erase(), and cata::list< element_type, element_allocator_type >::list_iterator< is_const >::node_pointer.
Friends And Related Function Documentation
list_iterator< false >
template<class element_type , class element_allocator_type = std::allocator<element_type>> friend class list_iterator< false > friend
Definition at line 2455 of file list.h.
list_iterator< true >
template<class element_type , class element_allocator_type = std::allocator<element_type>> friend class list_iterator< true > friend
Definition at line 2455 of file list.h.
list_reverse_iterator< false >
template<class element_type , class element_allocator_type = std::allocator<element_type>> friend class list_reverse_iterator< false > friend
Definition at line 2455 of file list.h.
list_reverse_iterator< true >
template<class element_type , class element_allocator_type = std::allocator<element_type>> friend class list_reverse_iterator< true > friend
Definition at line 2455 of file list.h.
Member Data Documentation
begin_iterator
template<class element_type , class element_allocator_type = std::allocator<element_type>> iterator cata::list< element_type, element_allocator_type >::begin_iterator private
Definition at line 976 of file list.h.
Referenced by cata::list< element_type, element_allocator_type >::list(), cata::list< element_type, element_allocator_type >::merge(), cata::list< element_type, element_allocator_type >::operator=(), and cata::list< element_type, element_allocator_type >::splice().
end_iterator
template<class element_type , class element_allocator_type = std::allocator<element_type>> iterator cata::list< element_type, element_allocator_type >::end_iterator private
Definition at line 975 of file list.h.
Referenced by cata::list< element_type, element_allocator_type >::list(), cata::list< element_type, element_allocator_type >::merge(), and cata::list< element_type, element_allocator_type >::operator=().
end_node
template<class element_type , class element_allocator_type = std::allocator<element_type>> node_base cata::list< element_type, element_allocator_type >::end_node private
Definition at line 972 of file list.h.
Referenced by cata::list< element_type, element_allocator_type >::merge(), and cata::list< element_type, element_allocator_type >::splice().
groups
template<class element_type , class element_allocator_type = std::allocator<element_type>> group_vector cata::list< element_type, element_allocator_type >::groups private
Definition at line 971 of file list.h.
Referenced by cata::list< element_type, element_allocator_type >::append_process().
last_endpoint
template<class element_type , class element_allocator_type = std::allocator<element_type>> node_pointer_type cata::list< element_type, element_allocator_type >::last_endpoint private
Definition at line 974 of file list.h.
Referenced by cata::list< element_type, element_allocator_type >::append_process().
node_allocator_pair
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list::ebco_pair2 cata::list< element_type, element_allocator_type >::node_allocator_pair private
node_pointer_allocator_pair
template<class element_type , class element_allocator_type = std::allocator<element_type>> cata::list::ebco_pair1 cata::list< element_type, element_allocator_type >::node_pointer_allocator_pair private
Referenced by cata::list< element_type, element_allocator_type >::append_process(), cata::list< element_type, element_allocator_type >::list(), cata::list< element_type, element_allocator_type >::merge(), cata::list< element_type, element_allocator_type >::operator=(), and cata::list< element_type, element_allocator_type >::splice().
The documentation for this class was generated from the following file:
src/list.h