Cataclysm DDA: input_context Class Reference
input_context Class Reference
Represents a context in which a set of actions can be performed.
#include <input_context.h>
Public Types
using input_event_filter = std::function< bool(const input_event &)>
Public Member Functions
input_context ()
input_context (const std::string &category, const keyboard_mode preferred_keyboard_mode=keyboard_mode::keycode)
void register_action (const std::string &action_descriptor)
Register an action with this input context.
void register_action (const std::string &action_descriptor, const translation &name)
Same as other register_action function but allows a context specific action name.
std::string get_available_single_char_hotkeys (std::string requested_keys="abcdefghijkpqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-=:;'\",./<>?!@#$%^&*()_+[]\\{}|`~")
Get the set of available single character keyboard keys that do not conflict with any registered hotkeys.
std::string get_desc (const std::string &action_descriptor, unsigned int max_limit=0, const input_event_filter &evt_filter=allow_all_keys) const
Get a description text for the key/other input method associated with the given action.
std::string get_button_text (const std::string &action_descriptor) const
Get a description for the action parameter along with a printable hotkey for the description in the format [s] s.
std::string get_button_text (const std::string &action_descriptor, const std::string &action_text) const
Get a description for the action parameter along with a printable hotkey for the description in the format [s] s.
std::string get_desc (const std::string &action_descriptor, const std::string &text, const input_event_filter &evt_filter, const translation &inline_fmt, const translation &separate_fmt) const
Get a description based on text.
std::string get_desc (const std::string &action_descriptor, const std::string &text, const input_event_filter &evt_filter=allow_all_keys) const
std::string describe_key_and_name (const std::string &action_descriptor, const input_event_filter &evt_filter=allow_all_keys) const
Equivalent to get_desc(act, get_action_name(act), filter)
const std::string & handle_input ()
Handles input and returns the next action in the queue.
const std::string & handle_input (int timeout)
std::optional< tripoint > get_direction (const std::string &action) const
Convert a direction action (UP, DOWN etc) to a delta vector.
std::optional< tripoint_rel_ms > get_direction_rel_ms (const std::string &action) const
std::optional< tripoint > get_coordinates (const catacurses::window &capture_win_, const point &offset=point_zero, bool center_cursor=false) const
Get the coordinates associated with the last mouse click (if any).
void register_directions ()
void register_updown ()
void register_leftright ()
void register_cardinal ()
void register_navigate_ui_list ()
action_id display_menu (bool permit_execute_action=false)
Display the possible actions in the current context and their keybindings.
input_event get_raw_input ()
Temporary method to retrieve the raw input received, so that input_contexts can be used in screens where not all possible actions have been defined in keybindings.json yet.
std::optional< point > get_coordinates_text (const catacurses::window &capture_win) const
Get coordinate of text level from mouse input, difference between this and get_coordinates is that one is getting pixel level coordinate.
std::string get_action_name (const std::string &action_id) const
Get the human-readable name for an action.
std::string press_x (const std::string &action_id) const
std::string press_x (const std::string &action_id, const std::string &key_bound, const std::string &key_unbound) const
std::string press_x (const std::string &action_id, const std::string &key_bound_pre, const std::string &key_bound_suf, const std::string &key_unbound) const
std::vector< input_event > keys_bound_to (const std::string &action_descriptor, int maximum_modifier_count=-1, bool restrict_to_printable=true, bool restrict_to_keyboard=true) const
Keys (and only keys, other input types are not included) that trigger the given action.
void set_edittext (const std::string &s)
Get/Set edittext to display IME unspecified string.
std::string get_edittext ()
void set_iso (bool mode=true)
void set_timeout (int val)
Sets input polling timeout as appropriate for the current interface system.
void reset_timeout ()
input_event first_unassigned_hotkey (const hotkey_queue &queue) const
input_event next_unassigned_hotkey (const hotkey_queue &queue, const input_event &prev) const
const std::string & input_to_action (const input_event &inp) const
bool is_event_type_enabled (input_event_t type) const
bool is_registered_action (const std::string &action_name) const
Static Public Member Functions
static bool disallow_lower_case_or_non_modified_letters (const input_event &evt)
static bool allow_all_keys (const input_event &evt)
Private Member Functions
bool action_reset (const std::string &action_id)
Reset action to default keybindings.
bool action_add (const std::string &name, const std::string &action_id, bool is_local, kb_menu_status status)
Prompt the user to add an event to an action.
bool action_remove (const std::string &name, const std::string &action_id, bool is_local, bool is_empty)
Remove an action.
bool action_uses_input (const std::string &action_id, const input_event &event) const
Returns whether action uses the specified input.
std::string get_conflicts (const input_event &event, const std::string &ignore_action) const
Return a user presentable list of actions that conflict with the proposed keybinding.
void clear_conflicting_keybindings (const input_event &event, const std::string &ignore_action)
Clear an input_event from all conflicting keybindings (excluding conflicts for ignore_action) that are registered by this input_context in default and current context (see category).
bool resolve_conflicts (const std::vector< input_event > &events, const std::string &ignore_action)
Find all conflicts for all events (excluding conflicts for ignore_action).
std::vector< std::string > filter_strings_by_phrase (const std::vector< std::string > &strings, std::string_view phrase) const
Filter a vector of strings by a phrase, returning only strings that contain the phrase.
Private Attributes
std::vector< std::string > registered_actions
std::string edittext
bool registered_any_input
std::string category
point coordinate
bool coordinate_input_received
bool handling_coordinate_input
input_event next_action
bool iso_mode = false
int timeout = -1
keyboard_mode preferred_keyboard_mode = keyboard_mode::keycode
std::map< std::string, translation > action_name_overrides
When registering for actions within an input_context, callers can specify a custom action name that will override the action's normal name.
Friends
class keybindings_ui
Detailed Description
Represents a context in which a set of actions can be performed.
This class is responsible for registering possible actions (traditionally keypresses), handling input, and yielding the correct action string descriptors for given input.
This turns this class into an abstraction method between actual input(keyboard, gamepad etc.) and game.
Definition at line 39 of file input_context.h.
Member Typedef Documentation
input_event_filter
using input_context::input_event_filter = std::function<bool(const input_event &)>
Definition at line 199 of file input_context.h.
Constructor & Destructor Documentation
input_context() [1/2]
input_context::input_context () inline
Definition at line 48 of file input_context.h.
                         : registered_any_input( false ), category( "default" ),
             coordinate_input_received( false ), handling_coordinate_input( false ) {
 #if defined(__ANDROID__)
             input_context_stack.push_back( this );
             allow_text_entry = false;
 #endif
             register_action( "toggle_language_to_en" );
         }
References register_action().
input_context() [2/2]
input_context::input_context (const std::string & category, const keyboard_mode preferred_keyboard_mode = keyboard_mode::keycode) inline explicit
Definition at line 58 of file input_context.h.
             : registered_any_input( false ), category( category ),
               coordinate_input_received( false ), handling_coordinate_input( false ),
               preferred_keyboard_mode( preferred_keyboard_mode ) {
 #if defined(__ANDROID__)
             input_context_stack.push_back( this );
             allow_text_entry = false;
 #endif
             register_action( "toggle_language_to_en" );
         }
References register_action().
Member Function Documentation
action_add()
bool input_context::action_add (const std::string & name, const std::string & action_id, bool is_local, kb_menu_status status) private
Prompt the user to add an event to an action.
Prompt the user to resolve conflicts if they arise.
Returns
true if keybinding changed
Definition at line 909 of file input_context.cpp.
 {
     const input_event new_event = query_popup()
                                   .preferred_keyboard_mode( preferred_keyboard_mode )
                                   .message( _( "New key for %s" ), name )
                                   .allow_anykey( true )
                                   .query()
                                   .evt;
     if( action_uses_input( action_id, new_event )
         // Allow adding keys already used globally to local bindings
         && ( status == kb_menu_status::add_global || is_local ) ) {
         popup_getkey( _( "This key is already used for %s." ), name );
         return false;
     }
     if( !resolve_conflicts( { new_event }, action_id ) ) {
         return false;
     }
     // We might be adding a local or global action.
     std::string category_to_access = category;
     if( status == kb_menu_status::add_global ) {
         category_to_access = default_context_id;
     }
     inp_mngr.add_input_for_action( action_id, category_to_access, new_event );
     return true;
 }
References _, action_uses_input(), add_global, input_manager::add_input_for_action(), query_popup::allow_anykey(), category, default_context_id(), query_popup::result::evt, inp_mngr, query_popup::message(), om_direction::name(), popup_getkey(), preferred_keyboard_mode, query_popup::preferred_keyboard_mode(), query_popup::query(), resolve_conflicts(), and status.
Referenced by display_menu().
action_remove()
bool input_context::action_remove (const std::string & name, const std::string & action_id, bool is_local, bool is_empty) private
Remove an action.
Prompt the user to resolve conflicts if they arise.
Returns
true if keybinding changed
Definition at line 879 of file input_context.cpp.
 {
     // We don't want to completely delete a global context entry.
     // Only attempt removal for a local context, or when there's
     // bindings for the default context.
     if( get_option<bool>( "QUERY_KEYBIND_REMOVAL" )
         && !query_yn( is_local && is_empty
                       ? _( "Reset to global bindings for %s?" )
                       : _( "Clear keys for %s?" ), name )
       ) {
         return false;
     }
     // If it's global, reset the global actions.
     std::string category_to_access = is_local ? category : default_context_id;
     // Clear potential conflicts for keys this would uncover
     input_manager::t_action_contexts old_action_contexts( inp_mngr.action_contexts );
     bool uncovered_global = inp_mngr.remove_input_for_action( action_id, category_to_access );
     if( uncovered_global ) {
         const std::vector<input_event> &conflicting_events = inp_mngr.get_or_create_event_list( action_id,
                 default_context_id );
         if( !resolve_conflicts( conflicting_events, action_id ) ) {
             inp_mngr.action_contexts.swap( old_action_contexts );
             return false;
         }
     }
     return true;
 }
References _, input_manager::action_contexts, category, default_context_id(), input_manager::get_or_create_event_list(), inp_mngr, om_direction::name(), query_yn(), input_manager::remove_input_for_action(), and resolve_conflicts().
Referenced by display_menu().
action_reset()
bool input_context::action_reset (const std::string & action_id) private
Reset action to default keybindings.
Prompt the user to resolve conflicts if they arise.
Returns
true if keybinding changed
Definition at line 839 of file input_context.cpp.
 {
     // FIND CONFLICTS
     std::vector<input_event> conflicting_events;
     std::array<std::reference_wrapper<const std::string>, 2> contexts = { default_context_id, category };
     for( const std::string &context : contexts ) {
         const input_manager::t_actions &def = inp_mngr.basic_action_contexts.at( context );
         bool is_in_def = def.find( action_id ) != def.end();
         if( is_in_def ) {
             for( const input_event &event : def.at( action_id ).input_events ) {
                 conflicting_events.emplace_back( event );
             }
         }
     }
     if( !resolve_conflicts( conflicting_events, action_id ) ) {
         return false;
     }
     // RESET KEY BINDINGS
     for( const std::string &context : contexts ) {
         const input_manager::t_actions &def = inp_mngr.basic_action_contexts.at( context );
         const input_manager::t_actions &cus = inp_mngr.action_contexts.at( context );
         bool is_in_def = def.find( action_id ) != def.end();
         bool is_in_cus = cus.find( action_id ) != cus.end();
         if( is_in_cus ) {
             inp_mngr.remove_input_for_action( action_id, context );
         }
         if( is_in_def ) {
             for( const input_event &event : def.at( action_id ).input_events ) {
                 inp_mngr.add_input_for_action( action_id, context, event );
             }
         }
     }
     return true;
 }
References input_manager::action_contexts, input_manager::add_input_for_action(), input_manager::basic_action_contexts, category, context, default_context_id(), inp_mngr, input_manager::remove_input_for_action(), and resolve_conflicts().
Referenced by display_menu().
action_uses_input()
bool input_context::action_uses_input (const std::string & action_id, const input_event & event) const private
Returns whether action uses the specified input.
Definition at line 89 of file input_context.cpp.
 {
     const auto &events = inp_mngr.get_action_attributes( action_id, category ).input_events;
     return std::find( events.begin(), events.end(), event ) != events.end();
 }
References category, input_manager::get_action_attributes(), inp_mngr, and action_attributes::input_events.
Referenced by action_add().
allow_all_keys()
bool input_context::allow_all_keys (const input_event & evt) static
Definition at line 264 of file input_context.cpp.
 {
     return true;
 }
Referenced by game::cancel_activity_or_ignore_query(), Pickup::query_thief(), query_yn(), query_ynq(), computer_session::query_ynq(), select_crafter_and_crafting_recipe(), diary::show_diary_ui(), and veh_act_desc().
clear_conflicting_keybindings()
void input_context::clear_conflicting_keybindings (const input_event & event, const std::string & ignore_action) private
Clear an input_event from all conflicting keybindings (excluding conflicts for ignore_action) that are registered by this input_context in default and current context (see category).
Parameters
event The input event to be cleared from conflicting keybindings.
Definition at line 106 of file input_context.cpp.
 {
     // The default context is always included to cover cases where the same
     // keybinding exists for the same action in both the global and local
     // contexts.
     input_manager::t_actions &default_actions = inp_mngr.action_contexts[default_context_id];
     input_manager::t_actions &category_actions = inp_mngr.action_contexts[category];
     for( const std::string &registered_action : registered_actions ) {
         if( registered_action == ignore_action ) {
             continue;
         }
         input_manager::t_actions::iterator default_action = default_actions.find( registered_action );
         input_manager::t_actions::iterator category_action = category_actions.find( registered_action );
         if( default_action != default_actions.end() ) {
             std::vector<input_event> &events = default_action->second.input_events;
             events.erase( std::remove( events.begin(), events.end(), event ), events.end() );
         }
         if( category_action != category_actions.end() ) {
             std::vector<input_event> &events = category_action->second.input_events;
             events.erase( std::remove( events.begin(), events.end(), event ), events.end() );
         }
     }
 }
References input_manager::action_contexts, category, default_context_id(), inp_mngr, and registered_actions.
Referenced by resolve_conflicts().
describe_key_and_name()
std::string input_context::describe_key_and_name (const std::string & action_descriptor, const input_event_filter & evt_filter = allow_all_keys) const
Equivalent to get_desc(act, get_action_name(act), filter)
Definition at line 421 of file input_context.cpp.
 {
     return get_desc( action_descriptor, get_action_name( action_descriptor ), evt_filter );
 }
References get_action_name(), and get_desc().
Referenced by game_menus::inv::compare_items(), editmap::edit(), editmap::edit_feature(), editmap::edit_fld(), editmap::edit_mapgen(), editmap::mapgen_preview(), editmap::mapgen_retarget(), computer_session::query_ynq(), and editmap::select_shape().
disallow_lower_case_or_non_modified_letters()
bool input_context::disallow_lower_case_or_non_modified_letters (const input_event & evt) static
Definition at line 249 of file input_context.cpp.
 {
     const int ch = evt.get_first_input();
     switch( evt.type ) {
         case input_event_t::keyboard_char:
             // std::lower from <cctype> is undefined outside unsigned char range
             // and std::lower from <locale> may throw bad_cast for some locales
             return ch < 'a' || ch > 'z';
         case input_event_t::keyboard_code:
             return !( evt.modifiers.empty() && ( ( ch >= 'a' && ch <= 'z' ) || ( ch >= 'A' && ch <= 'Z' ) ) );
         default:
             return true;
     }
 }
References input_event::get_first_input(), keyboard_char, keyboard_code, input_event::modifiers, and input_event::type.
Referenced by game::cancel_activity_or_ignore_query(), Pickup::query_thief(), query_yn(), query_ynq(), and computer_session::query_ynq().
display_menu()
action_id input_context::display_menu (bool permit_execute_action = false)
Display the possible actions in the current context and their keybindings.
Parameters
permit_execute_action If true the function allows the user to specify an action to execute
Returns
action_id of any action the user specified to execute, or ACTION_NULL if none
Definition at line 940 of file input_context.cpp.
 {
     action_id action_to_execute = ACTION_NULL;
     input_context ctxt( "HELP_KEYBINDINGS", keyboard_mode::keychar );
     // Keybinding menu actions
     ctxt.register_action( "COORDINATE" );
     ctxt.register_action( "MOUSE_MOVE" );
     ctxt.register_action( "SELECT" );
     ctxt.register_action( "REMOVE" );
     ctxt.register_action( "RESET" );
     ctxt.register_action( "ADD_LOCAL" );
     ctxt.register_action( "ADD_GLOBAL" );
     ctxt.register_action( "TEXT.CLEAR" );
     ctxt.register_action( "TEXT.CONFIRM" );
     ctxt.register_action( "PAGE_UP" );
     ctxt.register_action( "PAGE_DOWN" );
     ctxt.register_action( "END" );
     ctxt.register_action( "HOME" );
     ctxt.register_action( "FILTER" );
     ctxt.register_action( "RESET_FILTER" );
     ctxt.register_action( "TEXT.INPUT_FROM_FILE" );
     if( permit_execute_action ) {
         ctxt.register_action( "EXECUTE" );
     }
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "ANY_INPUT" );
     if( category != "HELP_KEYBINDINGS" ) {
         // avoiding inception!
         ctxt.register_action( "HELP_KEYBINDINGS" );
     }
 #if defined(WIN32) || defined(TILES)
     ctxt.set_timeout( 50 );
 #endif
     // has the user changed something?
     bool changed = false;
     // keybindings before the user changed anything.
     input_manager::t_action_contexts old_action_contexts( inp_mngr.action_contexts );
     // copy of registered_actions, but without the ANY_INPUT and COORDINATE, which should not be shown
     std::vector<std::string> org_registered_actions( registered_actions );
     org_registered_actions.erase( std::remove_if( org_registered_actions.begin(),
                                   org_registered_actions.end(),
     []( const std::string & a ) {
         return a == ANY_INPUT || a == COORDINATE;
     } ), org_registered_actions.end() );
     std::string action;
     keybindings_ui kb_menu( permit_execute_action, this );
     kb_menu.filtered_registered_actions = org_registered_actions;
     kb_menu.hotkeys = ctxt.get_available_single_char_hotkeys( display_help_hotkeys );
     kb_menu.init();
     int raw_input_char = 0;
     //const auto redraw = [&]( ui_adaptor & ui ) {
     //};
     //ui.on_redraw( redraw );
     while( true ) {
         kb_menu.highlight_row_index = -1;
         ui_manager::redraw();
         if( kb_menu.has_button_action() ) {
             action = kb_menu.get_button_action();
             raw_input_char = 0;
         } else {
             action = ctxt.handle_input();
             raw_input_char = ctxt.get_raw_input().get_first_input();
         }
         for( const std::pair<const fallback_action, int> &v : fallback_keys ) {
             if( v.second == raw_input_char ) {
                 action.clear();
             }
         }
         kb_menu.filtered_registered_actions = filter_strings_by_phrase( org_registered_actions,
                                               kb_menu.get_filter() );
         // In addition to the modifiable hotkeys, we also check for hardcoded
         // keys, e.g. '+', '-', '=', '.' in order to prevent the user from
         // entering an unrecoverable state.
         if( kb_menu.status == kb_menu_status::filter ) {
             if( action == "QUIT" ) {
                 kb_menu.clear_filter();
                 kb_menu.status = kb_menu_status::show;
             } else if( action == "TEXT.CONFIRM" ) {
                 kb_menu.status = kb_menu_status::show;
             }
         } else if( action == "ADD_LOCAL"
                    || raw_input_char == fallback_keys.at( fallback_action::add_local ) ) {
             if( !kb_menu.filtered_registered_actions.empty() ) {
                 kb_menu.status = kb_menu_status::add;
             }
         } else if( action == "ADD_GLOBAL"
                    || raw_input_char == fallback_keys.at( fallback_action::add_global ) ) {
             if( !kb_menu.filtered_registered_actions.empty() ) {
                 kb_menu.status = kb_menu_status::add_global;
             }
         } else if( action == "REMOVE"
                    || raw_input_char == fallback_keys.at( fallback_action::remove ) ) {
             if( !kb_menu.filtered_registered_actions.empty() ) {
                 kb_menu.status = kb_menu_status::remove;
             }
         } else if( action == "RESET"
                    || raw_input_char == fallback_keys.at( fallback_action::reset ) ) {
             if( !kb_menu.filtered_registered_actions.empty() ) {
                 kb_menu.status = kb_menu_status::reset;
             }
         } else if( ( action == "EXECUTE"
                      || raw_input_char == fallback_keys.at( fallback_action::execute ) )
                    && permit_execute_action ) {
             if( !kb_menu.filtered_registered_actions.empty() ) {
                 kb_menu.status = kb_menu_status::execute;
             }
         } else if( action == "PAGE_UP" || action == "PAGE_DOWN" || action == "HOME" || action == "END" ) {
             continue; // do nothing - on tiles version for some reason this counts as pressing various alphabet keys
         } else if( action == "TEXT.CLEAR" ) {
             kb_menu.clear_filter();
             kb_menu.filtered_registered_actions = filter_strings_by_phrase( org_registered_actions,
                                                   "" );
         } else if( !kb_menu.get_is_open() ) {
             break;
         } else if( action == "FILTER" ) {
             kb_menu.status = kb_menu_status::filter;
         } else if( action == "RESET_FILTER" ) {
             kb_menu.clear_filter();
         } else if( action == "QUIT" ) {
             if( kb_menu.status != kb_menu_status::show ) {
                 kb_menu.status = kb_menu_status::show;
             } else {
                 break;
             }
         } else if( action == "HELP_KEYBINDINGS" ) {
             // update available hotkeys in case they've changed
             kb_menu.hotkeys = ctxt.get_available_single_char_hotkeys( display_help_hotkeys );
         } else if( !kb_menu.filtered_registered_actions.empty() &&
                    kb_menu.status != kb_menu_status::show ) {
             size_t action_index = SIZE_MAX;
             if( action == "SELECT" && kb_menu.highlight_row_index != -1 ) {
                 action_index = kb_menu.highlight_row_index;
             } else {
                 size_t hotkey_index = kb_menu.hotkeys.find_first_of( raw_input_char );
                 if( hotkey_index == std::string::npos ) {
                     continue;
                 }
                 action_index = hotkey_index + kb_menu.scroll_offset;
             }
             if( action_index >= kb_menu.filtered_registered_actions.size() ) {
                 continue;
             }
             const std::string &action_id = kb_menu.filtered_registered_actions[action_index];
             // Check if this entry is local or global.
             bool is_local = false;
             const action_attributes &actions = inp_mngr.get_action_attributes( action_id, category, &is_local );
             bool is_empty = actions.input_events.empty();
             const std::string name = get_action_name( action_id );
             // We don't want to completely delete a global context entry.
             // Only attempt removal for a local context, or when there's
             // bindings for the default context.
             if( kb_menu.status == kb_menu_status::remove && ( is_local || !is_empty ) ) {
                 changed = action_remove( name, action_id, is_local, is_empty );
             } else if( kb_menu.status == kb_menu_status::reset ) {
                 changed = action_reset( action_id );
             } else if( kb_menu.status == kb_menu_status::add_global && is_local ) {
                 // Disallow adding global actions to an action that already has a local defined.
                 popup( _( "There are already local keybindings defined for this action, please remove them first." ) );
             } else if( kb_menu.status == kb_menu_status::add ||
                        kb_menu.status == kb_menu_status::add_global ) {
                 changed = action_add( name, action_id, is_local, kb_menu.status );
             } else if( kb_menu.status == kb_menu_status::execute && permit_execute_action ) {
                 action_to_execute = look_up_action( action_id );
                 break;
             }
             kb_menu.status = kb_menu_status::show;
         }
     }
     if( changed && query_yn( _( "Save changes?" ) ) ) {
         try {
             inp_mngr.save();
             get_help().load();
         } catch( std::exception &err ) {
             popup( _( "saving keybindings failed: %s" ), err.what() );
         }
     } else if( changed ) {
         inp_mngr.action_contexts.swap( old_action_contexts );
     }
     return action_to_execute;
 }
References _, a, action, action_add(), input_manager::action_contexts, ACTION_NULL, action_remove(), action_reset(), add, add_global, category, cataimgui::window::clear_filter(), display_help_hotkeys, execute, fallback_keys, filter, filter_strings_by_phrase(), keybindings_ui::filtered_registered_actions, input_manager::get_action_attributes(), get_action_name(), get_available_single_char_hotkeys(), cataimgui::window::get_button_action(), cataimgui::window::get_filter(), input_event::get_first_input(), get_help(), cataimgui::window::get_is_open(), get_raw_input(), handle_input(), cataimgui::window::has_button_action(), keybindings_ui::highlight_row_index, keybindings_ui::hotkeys, keybindings_ui::init(), inp_mngr, action_attributes::input_events, keychar, help::load(), look_up_action(), om_direction::name(), popup(), query_yn(), ui_manager::redraw(), register_action(), registered_actions, remove, reset, input_manager::save(), keybindings_ui::scroll_offset, set_timeout(), show, and keybindings_ui::status.
Referenced by trade_selector::execute(), game::handle_action(), handle_input(), handle_player_display_action(), and main_menu::opening_screen().
filter_strings_by_phrase()
std::vector< std::string > input_context::filter_strings_by_phrase (const std::vector< std::string > & strings, std::string_view phrase) const private
Filter a vector of strings by a phrase, returning only strings that contain the phrase.
Parameters
strings The vector of strings to filter
phrase The phrase to search within each of the given strings
Returns
A vector of the filtered strings
Definition at line 1273 of file input_context.cpp.
 {
     std::vector<std::string> filtered_strings;
     for( const std::string &str : strings ) {
         if( lcmatch( remove_color_tags( get_action_name( str ) ), phrase ) ) {
             filtered_strings.push_back( str );
         }
     }
     return filtered_strings;
 }
References get_action_name(), lcmatch(), and remove_color_tags().
Referenced by display_menu().
first_unassigned_hotkey()
input_event input_context::first_unassigned_hotkey (const hotkey_queue & queue) const
Definition at line 1332 of file input_context.cpp.
 {
     input_event ret = queue.first( *this );
     while( ret.type != input_event_t::error
            && &input_to_action( ret ) != &CATA_ERROR ) {
         ret = queue.next( ret );
     }
     return ret;
 }
References CATA_ERROR, error, hotkey_queue::first(), input_to_action(), hotkey_queue::next(), and cata::hash64_detail::ret.
Referenced by uilist::calc_data(), veh_interact::calc_overview(), and dialogue::opt().
get_action_name()
std::string input_context::get_action_name (const std::string & action_id) const
Get the human-readable name for an action.
Definition at line 1196 of file input_context.cpp.
 {
     // 1) Check action name overrides specific to this input_context
     const auto action_name_override =
         action_name_overrides.find( action_id );
     if( action_name_override != action_name_overrides.end() ) {
         return action_name_override->second.translated();
     }
     // 2) Check if the hotkey has a name
     const action_attributes &attributes = inp_mngr.get_action_attributes( action_id, category, nullptr,
                                           true );
     if( !attributes.name.empty() ) {
         return attributes.name.translated();
     }
     // 3) If the hotkey has no name, the user has created a local hotkey in
     // this context that is masking the global hotkey. Fallback to the global
     // hotkey's name.
     const action_attributes &default_attributes = inp_mngr.get_action_attributes( action_id,
             default_context_id, nullptr, true );
     if( !default_attributes.name.empty() ) {
         return default_attributes.name.translated();
     }
     // 4) Unable to find suitable name. Keybindings configuration likely borked
     return action_id;
 }
References action_name_overrides, category, default_context_id(), translation::empty(), input_manager::get_action_attributes(), inp_mngr, action_attributes::name, and translation::translated().
Referenced by describe_key_and_name(), display_menu(), keybindings_ui::draw_controls(), overmap_ui::draw_om_sidebar(), filter_strings_by_phrase(), query_popup_impl::fold_query(), get_button_text(), handle_main_menu(), game::look_around(), and veh_app_interact::populate_app_actions().
get_available_single_char_hotkeys()
std::string input_context::get_available_single_char_hotkeys (std::string requested_keys = "abcdefghijkpqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-=:;'\",./<>?!@#$%^&*()_+[]\\{}|`~")
Get the set of available single character keyboard keys that do not conflict with any registered hotkeys.
The result will only include characters from the requested_keys parameter that have no conflicts i.e. the set difference requested_keys - conflicts.
Parameters
requested_keys The set of single character hotkeys to potentially use. Defaults to all printable ascii.
Returns
Returns the set of non-conflicting, single character keyboard keys suitable for use as hotkeys.
Definition at line 229 of file input_context.cpp.
 {
     for( const auto &registered_action : registered_actions ) {
         const std::vector<input_event> &events = inp_mngr.get_input_for_action( registered_action,
                 category );
         for( const input_event &events_event : events ) {
             // Only consider keyboard events without modifiers
             if( events_event.type == input_event_t::keyboard_char && events_event.modifiers.empty() ) {
                 requested_keys.erase( std::remove_if( requested_keys.begin(), requested_keys.end(),
                                                       ContainsPredicate<std::vector<int>, char>(
                                                               events_event.sequence ) ),
                                       requested_keys.end() );
             }
         }
     }
     return requested_keys;
 }
References category, input_manager::get_input_for_action(), inp_mngr, keyboard_char, and registered_actions.
Referenced by display_menu(), veh_app_interact::populate_app_actions(), and inventory_selector::reassign_custom_invlets().
get_button_text() [1/2]
std::string input_context::get_button_text (const std::string & action_descriptor) const
Get a description for the action parameter along with a printable hotkey for the description in the format [s] s.
Parameters
action_descriptor The action descriptor for which to return a description of the bound keys.
Definition at line 321 of file input_context.cpp.
 {
     std::string action_name = get_action_name( action_descriptor );
     if( action_name.empty() ) {
         action_name = action_descriptor;
     }
     return get_button_text( action_descriptor, action_name );
 }
References get_action_name().
Referenced by cataimgui::window::draw_filter().
get_button_text() [2/2]
std::string input_context::get_button_text (const std::string & action_descriptor, const std::string & action_text) const
Get a description for the action parameter along with a printable hotkey for the description in the format [s] s.
Parameters
action_descriptor The action descriptor for which to return a description of the bound keys.
action_text The human readable description of the action.
Definition at line 330 of file input_context.cpp.
 {
     if( action_descriptor == "ANY_INPUT" ) {
         return ""; // what sort of crazy button would this be?
     }
     bool is_local = false;
     const std::vector<input_event> &events = inp_mngr.get_input_for_action( action_descriptor,
             category, &is_local );
     if( events.empty() ) {
         return action_text;
     }
     std::vector<input_event> inputs_to_show;
     for( const input_event &event : events ) {
         if( is_event_type_enabled( event.type ) ) {
             inputs_to_show.push_back( event );
         }
     }
     if( inputs_to_show.empty() ) {
         return action_text;
     } else {
         return string_format( "[%s] %s", inputs_to_show[0].long_description(), action_text );
     }
 }
References category, input_manager::get_input_for_action(), inp_mngr, is_event_type_enabled(), and string_format().
get_conflicts()
std::string input_context::get_conflicts (const input_event & event, const std::string & ignore_action) const private
Return a user presentable list of actions that conflict with the proposed keybinding.
Returns an empty string if nothing conflicts.
Definition at line 96 of file input_context.cpp.
 {
     return enumerate_as_string( registered_actions.begin(), registered_actions.end(),
     [ this, &event, &ignore_action ]( const std::string & action ) {
         return action != ignore_action && action_uses_input( action, event )
                ? get_action_name( action ) : std::string();
     } );
 }
References action, enumerate_as_string(), and registered_actions.
Referenced by resolve_conflicts().
get_coordinates()
std::optional< tripoint > input_context::get_coordinates (const catacurses::window & capture_win_, const point & offset = point_zero, bool center_cursor = false) const
Get the coordinates associated with the last mouse click (if any).
Definition at line 1144 of file input_context.cpp.
 {
     if( !coordinate_input_received ) {
         return std::nullopt;
     }
     const point view_size( getmaxx( capture_win ), getmaxy( capture_win ) );
     const point win_min( getbegx( capture_win ),
                          getbegy( capture_win ) );
     const half_open_rectangle<point> win_bounds( win_min, win_min + view_size );
     if( !win_bounds.contains( coordinate ) ) {
         return std::nullopt;
     }
     point p = coordinate + offset;
     // If no offset is specified, account for the window location
     if( offset == point_zero ) {
         p -= win_min;
     }
     // Some windows (notably the overmap) want 0,0 to be the center of the screen
     if( center_cursor ) {
         p -= view_size / 2;
     }
     return tripoint( p, get_map().get_abs_sub().z() );
 }
References half_open_rectangle< Point, >::contains(), coordinate, coordinate_input_received, get_map(), catacurses::getbegx(), catacurses::getbegy(), catacurses::getmaxx(), catacurses::getmaxy(), point_zero, and tripoint.
Referenced by overmap_ui::display(), get_coordinates_text(), game::handle_action(), target_ui::handle_cursor_movement(), game::handle_mouseview(), and game::look_around().
get_coordinates_text()
std::optional< point > input_context::get_coordinates_text (const catacurses::window & capture_win) const
Get coordinate of text level from mouse input, difference between this and get_coordinates is that one is getting pixel level coordinate.
Definition at line 1171 of file input_context.cpp.
 {
 #if !defined( TILES )
     std::optional<tripoint> coord3d = get_coordinates( capture_win );
     if( coord3d.has_value() ) {
         return get_coordinates( capture_win )->xy();
     } else {
         return std::nullopt;
     }
 #else
     if( !coordinate_input_received ) {
         return std::nullopt;
     }
     const window_dimensions dim = get_window_dimensions( capture_win );
     const int &fw = dim.scaled_font_size.x;
     const int &fh = dim.scaled_font_size.y;
     const point &win_min = dim.window_pos_pixel;
     const point screen_pos = coordinate - win_min;
     const point selected( divide_round_down( screen_pos.x, fw ),
                           divide_round_down( screen_pos.y, fh ) );
     return selected;
 #endif
 }
References coordinate, coordinate_input_received, divide_round_down(), get_coordinates(), point::x, and point::y.
Referenced by help::display_help(), draw_item_info(), tab_manager::handle_input(), uilist::handle_mouse(), scrolling_text_view::handle_navigation(), multiline_list::handle_navigation(), handle_player_display_action(), exosuit_interact::interact_loop(), ma_style_callback::key(), main_menu::opening_screen(), worldfactory::pick_world(), inventory_selector::process_input(), set_hobbies(), set_profession(), set_scenario(), set_skills(), set_traits(), options_manager::show(), worldfactory::show_active_world_mods(), worldfactory::show_worldgen_basic(), and worldfactory::show_worldgen_tab_modselection().
get_desc() [1/3]
std::string input_context::get_desc (const std::string & action_descriptor, const std::string & text, const input_event_filter & evt_filter, const translation & inline_fmt, const translation & separate_fmt) const
Get a description based on text.
If a bound key for action_descriptor satisfying evt_filter is contained in text, surround the key with brackets and change the case if necessary (e.g. "(Y)es"). Otherwise prefix text with description of the first bound key satisfying evt_filter, surrounded in square brackets (e.g "[RETURN] Yes").
Parameters
action_descriptor The action descriptor for which to return a description of the bound keys.
text The base text for action description
evt_filter Only keys satisfying this function will be considered
inline_fmt Action description format when a key is found in the text (for example "(a)ctive")
separate_fmt Action description format when a key is not found in the text (for example "[X] active" or "[N/A] active")
Definition at line 358 of file input_context.cpp.
 {
     if( action_descriptor == "ANY_INPUT" ) {
         //~ keybinding description for anykey
         return string_format( separate_fmt, pgettext( "keybinding", "any" ), text );
     }
     const auto &events = inp_mngr.get_input_for_action( action_descriptor, category );
     bool na = true;
     for( const input_event &evt : events ) {
         if( is_event_type_enabled( evt.type ) && evt_filter( evt ) ) {
             na = false;
             if( ( evt.type == input_event_t::keyboard_char || evt.type == input_event_t::keyboard_code ) &&
                 evt.modifiers.empty() && evt.sequence.size() == 1 ) {
                 const int ch = evt.get_first_input();
                 if( ch > ' ' && ch <= '~' ) {
                     const std::string key = utf32_to_utf8( ch );
                     const int pos = ci_find_substr( text, key );
                     if( pos >= 0 ) {
                         return string_format( inline_fmt, text.substr( 0, pos ),
                                               key, text.substr( pos + key.size() ) );
                     }
                 }
             }
         }
     }
     if( na ) {
         //~ keybinding description for unbound or non-applicable keys
         return string_format( separate_fmt, pgettext( "keybinding", "n/a" ), text );
     } else {
         return string_format( separate_fmt, get_desc( action_descriptor, 1, evt_filter ), text );
     }
 }
References category, ci_find_substr(), get_desc(), input_manager::get_input_for_action(), inp_mngr, is_event_type_enabled(), keyboard_char, keyboard_code, pgettext, math_opers::pos(), string_format(), and utf32_to_utf8().
get_desc() [2/3]
std::string input_context::get_desc (const std::string & action_descriptor, const std::string & text, const input_event_filter & evt_filter = allow_all_keys) const
Definition at line 399 of file input_context.cpp.
 {
     // Keybinding tips
     static const translation inline_fmt = to_translation(
             //~ %1$s: action description text before key,
             //~ %2$s: key description,
             //~ %3$s: action description text after key.
             "keybinding", "%1$s[<color_light_green>%2$s</color>]%3$s" );
     static const translation separate_fmt = to_translation(
             // \u00A0 is the non-breaking space
             //~ %1$s: key description,
             //~ %2$s: action description.
             "keybinding", "[<color_light_green>%1$s</color>]\u00A0%2$s" );
     return get_desc( action_descriptor, text, evt_filter, inline_fmt,
                      separate_fmt );
 }
References get_desc(), and to_translation().
get_desc() [3/3]
std::string input_context::get_desc (const std::string & action_descriptor, unsigned int max_limit = 0, const input_event_filter & evt_filter = allow_all_keys) const
Get a description text for the key/other input method associated with the given action.
If there are multiple bound keys, no more than max_limit will be described in the result. In addition, only keys satisfying evt_filter will be described.
Parameters
action_descriptor The action descriptor for which to return a description of the bound keys.
max_limit No more than max_limit bound keys will be described in the returned description. A value of 0 indicates no limit.
evt_filter Only keys satisfying this function will be described.
Definition at line 269 of file input_context.cpp.
 {
     if( action_descriptor == "ANY_INPUT" ) {
         return "(*)"; // * for wildcard
     }
     bool is_local = false;
     const std::vector<input_event> &events = inp_mngr.get_input_for_action( action_descriptor,
             category, &is_local );
     if( events.empty() ) {
         if( is_local ) {
             bool global_empty = inp_mngr.get_input_for_action( action_descriptor ).empty();
             return global_empty ? _( "Unbound locally!" ) : _( "Unbound locally!  Underlying global." );
         } else {
             return _( "Unbound globally!" );
         }
     }
     std::vector<input_event> inputs_to_show;
     for( const input_event &event : events ) {
         if( is_event_type_enabled( event.type ) && evt_filter( event ) ) {
             inputs_to_show.push_back( event );
         }
         if( max_limit > 0 && inputs_to_show.size() == max_limit ) {
             break;
         }
     }
     if( inputs_to_show.empty() ) {
         return pgettext( "keybinding", "None applicable" );
     }
     const std::string separator = inputs_to_show.size() > 2 ? _( ", or " ) : _( " or " );
     std::string rval;
     for( size_t i = 0; i < inputs_to_show.size(); ++i ) {
         rval += inputs_to_show[i].long_description();
         // We're generating a list separated by "," and "or"
         if( i + 2 == inputs_to_show.size() ) {
             rval += separator;
         } else if( i + 1 < inputs_to_show.size() ) {
             rval += ", ";
         }
     }
     return rval;
 }
References _, category, input_manager::get_input_for_action(), inp_mngr, is_event_type_enabled(), and pgettext.
Referenced by assemble_description_help(), assemble_hobby_details(), assemble_profession_details(), assemble_scenario_details(), assemble_skill_help(), assemble_stat_help(), debug_menu::change_spells(), choose_ma_style(), describe_key_and_name(), dialogue_window::draw(), draw_bionics_tab(), draw_bionics_titlebar(), draw_center_win(), keybindings_ui::draw_controls(), target_ui::draw_controls_list(), draw_effects_tab(), draw_encumbrance_tab(), draw_filter_and_sorting_indicators(), inventory_selector::draw_footer(), prof_window::draw_header(), target_ui::draw_help_notice(), draw_medical_titlebar(), worldfactory::draw_modselection_borders(), overmap_ui::draw_notes(), overmap_ui::draw_om_sidebar(), draw_proficiencies_tab(), draw_skills_tab(), draw_stats_tab(), draw_tip(), draw_traits_tab(), editmap::edit(), editmap::edit_fld(), inventory_compare_selector::execute(), inventory_drop_selector::execute(), pickup_selector::execute(), inventory_multiselector::execute(), game::extended_description(), query_popup_impl::fold_query(), get_desc(), game::get_player_input(), handle_debug_mode(), unload_selector::hint_string(), basecamp::job_assignment_ui(), game::look_around(), editmap::mapgen_preview(), character_martial_arts::pick_style(), pickup_selector::pickup_selector(), overmap_ui::place_ter_or_special(), pocket_management_menu(), avatar::power_bionics(), prompt_world_name(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), smart_controller_ui::refresh(), wish_mutate_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), replace_keybind_tag(), overmap_ui::search(), select_crafter_and_crafting_recipe(), calendar_ui::select_time_point(), set_points(), robot_finds_kitten::show(), diary::show_diary_ui(), show_mutations_titlebar(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), veh_act_desc(), debug_menu::wishitem(), debug_menu::wishmonster(), and basecamp::worker_assignment_ui().
get_direction()
std::optional< tripoint > input_context::get_direction (const std::string & action) const
Convert a direction action (UP, DOWN etc) to a delta vector.
Returns
If the action is a movement action (UP, DOWN, ...), the delta vector associated with it. Otherwise returns an empty value. The returned vector will always have a z component of 0.
Definition at line 551 of file input_context.cpp.
 {
     static const auto noop = static_cast<tripoint( * )( tripoint )>( []( tripoint p ) {
         return p;
     } );
     static const auto rotate = static_cast<tripoint( * )( tripoint )>( []( tripoint p ) {
         rotate_direction_cw( p.x, p.y );
         return p;
     } );
     const auto transform = iso_mode && g->is_tileset_isometric() ? rotate : noop;
     if( action == "UP" ) {
         return transform( tripoint_north );
     } else if( action == "DOWN" ) {
         return transform( tripoint_south );
     } else if( action == "LEFT" ) {
         return transform( tripoint_west );
     } else if( action == "RIGHT" ) {
         return transform( tripoint_east );
     } else if( action == "LEFTUP" ) {
         return transform( tripoint_north_west );
     } else if( action == "RIGHTUP" ) {
         return transform( tripoint_north_east );
     } else if( action == "LEFTDOWN" ) {
         return transform( tripoint_south_west );
     } else if( action == "RIGHTDOWN" ) {
         return transform( tripoint_south_east );
     } else {
         return std::nullopt;
     }
 }
References action, g, iso_mode, anonymous_namespace{item_tname.cpp}::noop(), rotate(), rotate_direction_cw(), transform, tripoint_east, tripoint_north, tripoint_north_east, tripoint_north_west, tripoint_south, tripoint_south_east, tripoint_south_west, and tripoint_west.
Referenced by choose_direction(), overmap_ui::display(), veh_interact::do_main_loop(), editmap::eget_direction(), target_ui::handle_cursor_movement(), game::look_around(), editmap::mapgen_retarget(), overmap_ui::place_ter_or_special(), lightson_game::start_game(), minesweeper_game::start_game(), and sokoban_game::start_game().
get_direction_rel_ms()
std::optional< tripoint_rel_ms > input_context::get_direction_rel_ms (const std::string & action) const
Definition at line 583 of file input_context.cpp.
 {
     static const auto noop = static_cast<tripoint_rel_ms( * )( tripoint_rel_ms )>( [](
     tripoint_rel_ms p ) {
         return p;
     } );
     static const auto rotate = static_cast<tripoint_rel_ms( * )( tripoint_rel_ms )>( [](
     tripoint_rel_ms p ) {
         rotate_direction_cw( p.x(), p.y() );
         return p;
     } );
     const auto transform = iso_mode && g->is_tileset_isometric() ? rotate : noop;
     if( action == "UP" ) {
         return transform( tripoint_rel_ms( tripoint_north ) );
     } else if( action == "DOWN" ) {
         return transform( tripoint_rel_ms( tripoint_south ) );
     } else if( action == "LEFT" ) {
         return transform( tripoint_rel_ms( tripoint_west ) );
     } else if( action == "RIGHT" ) {
         return transform( tripoint_rel_ms( tripoint_east ) );
     } else if( action == "LEFTUP" ) {
         return transform( tripoint_rel_ms( tripoint_north_west ) );
     } else if( action == "RIGHTUP" ) {
         return transform( tripoint_rel_ms( tripoint_north_east ) );
     } else if( action == "LEFTDOWN" ) {
         return transform( tripoint_rel_ms( tripoint_south_west ) );
     } else if( action == "RIGHTDOWN" ) {
         return transform( tripoint_rel_ms( tripoint_south_east ) );
     } else {
         return std::nullopt;
     }
 }
References action, g, iso_mode, anonymous_namespace{item_tname.cpp}::noop(), rotate(), rotate_direction_cw(), transform, tripoint_east, tripoint_north, tripoint_north_east, tripoint_north_west, tripoint_south, tripoint_south_east, tripoint_south_west, and tripoint_west.
Referenced by choose_direction_rel_ms().
get_edittext()
std::string input_context::get_edittext ()
Definition at line 1292 of file input_context.cpp.
 {
     return edittext;
 }
References edittext.
Referenced by string_input_popup::query_string().
get_raw_input()
input_event input_context::get_raw_input ()
Temporary method to retrieve the raw input received, so that input_contexts can be used in screens where not all possible actions have been defined in keybindings.json yet.
Definition at line 1132 of file input_context.cpp.
 {
     return next_action;
 }
References next_action.
Referenced by help::display_help(), display_menu(), draw_item_info(), trade_selector::execute(), inventory_selector::get_input(), game::handle_action(), uilist::inputfilter(), game::mouse_edge_scrolling(), main_menu::opening_screen(), dialogue::opt(), veh_interact::overview(), avatar::power_bionics(), avatar::power_mutations(), robot_finds_kitten::process_input(), uilist::query(), query_popup::query_once(), string_input_popup::query_string(), and computer_session::query_ynq().
handle_input() [1/2]
const std::string & input_context::handle_input ()
Handles input and returns the next action in the queue.
This internally calls getch() or whatever other input method is available(e.g. gamepad).
If the action is mouse input, returns "MOUSE".
Parameters
timeout in milliseconds.
Returns
One of the input actions formerly registered with register_action(), or "ERROR" if an error happened.
Definition at line 427 of file input_context.cpp.
 {
     return handle_input( timeout );
 }
References timeout.
Referenced by debug_menu::change_spells(), choose_direction(), choose_direction_rel_ms(), game_menus::inv::compare_items(), Character::conduct_blood_analysis(), smart_controller_ui::control(), avatar::disp_medical(), game::disp_NPCs(), bodygraph_display::display(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), help::display_help(), display_menu(), veh_interact::do_change_shape(), veh_interact::do_install(), veh_interact::do_main_loop(), veh_interact::do_remove(), veh_interact::do_repair(), draw_item_info(), mission_ui::draw_mission_ui(), editmap::edit(), trade_selector::execute(), game::extended_description(), inventory_selector::get_input(), handle_key_blocking_activity(), game::handle_mouseview(), handle_player_display_action(), exosuit_interact::interact_loop(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), editmap::mapgen_retarget(), main_menu::opening_screen(), dialogue::opt(), veh_interact::overview(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), avatar::power_bionics(), avatar::power_mutations(), robot_finds_kitten::process_input(), uilist::query(), query_popup::query_once(), string_input_popup::query_string(), computer_session::query_ynq(), demo_ui::run(), target_ui::run(), prof_window::run(), scrollable_text(), overmap_ui::search(), editmap::select_shape(), set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), diary::show_diary_ui(), color_manager::show_gui(), show_scores_ui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
handle_input() [2/2]
const std::string & input_context::handle_input (int timeout)
Definition at line 432 of file input_context.cpp.
 {
     const int old_timeout = inp_mngr.get_timeout();
     if( timeout >= 0 ) {
         inp_mngr.set_timeout( timeout );
     }
     next_action.type = input_event_t::error;
     const std::string *result = &CATA_ERROR;
     while( true ) {
         next_action = inp_mngr.get_input_event( preferred_keyboard_mode );
         if( next_action.type == input_event_t::timeout ) {
             result = &TIMEOUT;
             break;
         }
         const std::string &action = input_to_action( next_action );
         //Special global key to toggle language to english and back
         if( action == "toggle_language_to_en" ) {
             g->toggle_language_to_en();
             ui_manager::invalidate_all_ui_adaptors();
             ui_manager::redraw_invalidated();
         }
         // Special help action
         if( action == "HELP_KEYBINDINGS" ) {
             inp_mngr.reset_timeout();
             display_menu();
             inp_mngr.set_timeout( timeout );
             result = &HELP_KEYBINDINGS;
             break;
         }
         if( next_action.type == input_event_t::mouse
             && !handling_coordinate_input && action == CATA_ERROR ) {
             continue; // Ignore mouse movement.
         }
         coordinate_input_received = true;
         coordinate = next_action.mouse_pos;
         if( action != CATA_ERROR ) {
             result = &action;
             break;
         }
         // If we registered to receive any input, return ANY_INPUT
         // to signify that an unregistered key was pressed.
         if( registered_any_input ) {
             result = &ANY_INPUT;
             break;
         }
         // If it's an invalid key, just keep looping until the user
         // enters something proper.
     }
     inp_mngr.set_timeout( old_timeout );
     return *result;
 }
References action, ANY_INPUT, CATA_ERROR, coordinate, coordinate_input_received, display_menu(), error, g, input_manager::get_input_event(), input_manager::get_timeout(), handling_coordinate_input, HELP_KEYBINDINGS, inp_mngr, input_to_action(), ui_manager::invalidate_all_ui_adaptors(), mouse, input_event::mouse_pos, next_action, preferred_keyboard_mode, ui_manager::redraw_invalidated(), registered_any_input, input_manager::reset_timeout(), input_manager::set_timeout(), TIMEOUT, timeout, timeout, and input_event::type.
input_to_action()
const std::string & input_context::input_to_action (const input_event & inp) const
Definition at line 138 of file input_context.cpp.
 {
     for( const std::string &elem : registered_actions ) {
         const std::string &action = elem;
         const std::vector<input_event> &check_inp = inp_mngr.get_input_for_action( action, category );
         // Does this action have our queried input event in its keybindings?
         for( const input_event &check_inp_i : check_inp ) {
             if( check_inp_i == inp ) {
                 return action;
             }
         }
     }
     return CATA_ERROR;
 }
References action, CATA_ERROR, category, input_manager::get_input_for_action(), inp_mngr, and registered_actions.
Referenced by inventory_selector::action_bound_to_key(), trade_selector::execute(), first_unassigned_hotkey(), handle_debug_mode(), handle_input(), uilist::inputfilter(), pocket_favorite_callback::key(), spellcasting_callback::key(), ma_style_callback::key(), actmenu_cb::key(), overmap_ui::map_notes_callback::key(), wish_item_callback::key(), and next_unassigned_hotkey().
is_event_type_enabled()
bool input_context::is_event_type_enabled (input_event_t type) const
Definition at line 1307 of file input_context.cpp.
 {
     switch( type ) {
         case input_event_t::error:
             return false;
         case input_event_t::timeout:
             return true;
         case input_event_t::keyboard_char:
             return input_manager::actual_keyboard_mode( preferred_keyboard_mode ) == keyboard_mode::keychar;
         case input_event_t::keyboard_code:
             return input_manager::actual_keyboard_mode( preferred_keyboard_mode ) == keyboard_mode::keycode;
         case input_event_t::gamepad:
             return gamepad_available();
         case input_event_t::mouse:
             return true;
     }
     return true;
 }
References input_manager::actual_keyboard_mode(), error, gamepad, gamepad_available(), keyboard_char, keyboard_code, keychar, keycode, mouse, preferred_keyboard_mode, timeout, and type.
Referenced by hotkey_queue::first(), get_button_text(), get_desc(), and keys_bound_to().
is_registered_action()
bool input_context::is_registered_action (const std::string & action_name) const
Definition at line 1326 of file input_context.cpp.
 {
     return std::find( registered_actions.begin(), registered_actions.end(),
                       action_name ) != registered_actions.end();
 }
References registered_actions.
Referenced by replace_keybind_tag().
keys_bound_to()
std::vector< input_event > input_context::keys_bound_to (const std::string & action_descriptor, int maximum_modifier_count = -1, bool restrict_to_printable = true, bool restrict_to_keyboard = true) const
Keys (and only keys, other input types are not included) that trigger the given action.
Parameters
action_descriptor The action descriptor for which to get the bound keys.
maximum_modifier_count Maximum number of modifiers allowed for the returned action. <0 means any number is allowed.
restrict_to_printable If true, the function returns the bound keys only if they are printable (space counts as non-printable here). If false, all keys (whether they are printable or not) are returned.
restrict_to_keyboard If true, the function returns the bound keys only if they are keyboard inputs. If false, all inputs, such as mouse inputs are included.
Returns
All keys bound to the given action descriptor.
Definition at line 203 of file input_context.cpp.
 {
     std::vector<input_event> result;
     const std::vector<input_event> &events = inp_mngr.get_input_for_action( action_descriptor,
             category );
     for( const input_event &events_event : events ) {
         // Ignore non-keyboard input
         if( ( !restrict_to_keyboard || ( events_event.type == input_event_t::keyboard_char
                                          || events_event.type == input_event_t::keyboard_code ) )
             && is_event_type_enabled( events_event.type )
             && events_event.sequence.size() == 1
             && ( maximum_modifier_count < 0
                  || events_event.modifiers.size() <= static_cast<size_t>( maximum_modifier_count ) ) ) {
             if( !restrict_to_printable || ( events_event.sequence.front() < 0xFF &&
                                             events_event.sequence.front() != ' ' &&
                                             isprint( events_event.sequence.front() ) ) ) {
                 result.emplace_back( events_event );
             }
         }
     }
     return result;
 }
References category, input_manager::get_input_for_action(), inp_mngr, is_event_type_enabled(), keyboard_char, and keyboard_code.
Referenced by calculate_ranged_chances(), target_ui::draw_controls_list(), haul(), key_bound_to(), keys_bound_to(), game::look_around(), veh_app_interact::populate_app_actions(), press_x_if_bound(), replace_keybind_tag(), and veh_keybind().
next_unassigned_hotkey()
input_event input_context::next_unassigned_hotkey (const hotkey_queue & queue, const input_event & prev) const
Definition at line 1342 of file input_context.cpp.
 {
     input_event ret = prev;
     do {
         ret = queue.next( ret );
     } while( ret.type != input_event_t::error
              && &input_to_action( ret ) != &CATA_ERROR );
     return ret;
 }
References CATA_ERROR, error, input_to_action(), hotkey_queue::next(), and cata::hash64_detail::ret.
Referenced by uilist::calc_data(), veh_interact::calc_overview(), and dialogue::opt().
press_x() [1/3]
std::string input_context::press_x (const std::string & action_id) const
Definition at line 1226 of file input_context.cpp.
 {
     return press_x( action_id, _( "Press " ), "", _( "Try" ) );
 }
References _.
Referenced by game::list_monsters(), press_x(), and press_x().
press_x() [2/3]
std::string input_context::press_x (const std::string & action_id, const std::string & key_bound, const std::string & key_unbound) const
Definition at line 1231 of file input_context.cpp.
 {
     return press_x( action_id, key_bound, "", key_unbound );
 }
References press_x().
press_x() [3/3]
std::string input_context::press_x (const std::string & action_id, const std::string & key_bound_pre, const std::string & key_bound_suf, const std::string & key_unbound) const
Definition at line 1238 of file input_context.cpp.
 {
     if( action_id == "ANY_INPUT" ) {
         return _( "any key" );
     }
     if( action_id == "COORDINATE" ) {
         return _( "mouse movement" );
     }
     input_manager::t_input_event_list events = inp_mngr.get_input_for_action( action_id, category );
     events.erase( std::remove_if( events.begin(), events.end(), [this]( const input_event & evt ) {
         return !is_event_type_enabled( evt.type );
     } ), events.end() );
     if( events.empty() ) {
         return key_unbound;
     }
     const std::string separator = _( " or " );
     std::string keyed = key_bound_pre;
     for( size_t j = 0; j < events.size(); j++ ) {
         keyed += events[j].long_description();
         if( j + 1 < events.size() ) {
             keyed += separator;
         }
     }
     keyed += key_bound_suf;
     return keyed;
 }
References _, category, input_manager::get_input_for_action(), and inp_mngr.
register_action() [1/2]
void input_context::register_action (const std::string & action_descriptor)
Register an action with this input context.
Only registered actions will be returned by handle_input(), it's thus possible to have multiple actions associated with the same keypress, as long as they don't ever occur in the same input context.
If action_descriptor is the special "ANY_INPUT", instead of ignoring unregistered keys, those keys will all be linked to this "ANY_INPUT" action.
If action_descriptor is the special "COORDINATE", coordinate input will be processed and the specified coordinates can be retrieved using get_coordinates(). Currently the only form of coordinate input is mouse input(you can directly click coordinates on the screen).
Parameters
action_descriptor String of action id.
Definition at line 180 of file input_context.cpp.
 {
     register_action( action_descriptor, translation() );
 }
Referenced by ammo_inventory_selector::ammo_inventory_selector(), bodygraph_display::bodygraph_display(), debug_menu::change_spells(), choose_direction(), choose_direction_rel_ms(), choose_ma_style(), game_menus::inv::compare_items(), Character::conduct_blood_analysis(), construction_menu(), string_input_popup::create_context(), uilist::create_filter_input_context(), uilist::create_main_input_context(), Character::disp_info(), avatar::disp_medical(), game::disp_NPCs(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), help::display_help(), display_menu(), draw_item_info(), mission_ui::draw_mission_ui(), editmap::edit(), exosuit_interact::exosuit_interact(), game::extended_description(), get_default_mode_input_context(), game::get_player_input(), handle_debug_mode(), target_ui::init_window_and_input(), input_context(), inventory_multiselector::inventory_multiselector(), inventory_selector::inventory_selector(), game::item_action_menu(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), make_crafting_context(), editmap::mapgen_retarget(), main_menu::opening_screen(), dialogue::opt(), character_martial_arts::pick_style(), worldfactory::pick_world(), pickup_selector::pickup_selector(), overmap_ui::place_ter_or_special(), avatar::power_bionics(), avatar::power_mutations(), robot_finds_kitten::process_input(), query_popup::query_once(), computer_session::query_ynq(), advanced_inventory::redraw_sidebar(), advanced_inventory::register_ctxt(), register_directions(), register_leftright(), register_navigate_ui_list(), register_updown(), demo_ui::run(), prof_window::run(), scrollable_text(), overmap_ui::search(), editmap::select_shape(), set_description(), scrollbar::set_draggable(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), multiline_list::set_up_navigation(), scrolling_text_view::set_up_navigation(), dialogue_window::set_up_scrolling(), tab_manager::set_up_tab_navigation(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), diary::show_diary_ui(), color_manager::show_gui(), show_scores_ui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), smart_controller_ui::smart_controller_ui(), outfit::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), trade_selector::trade_selector(), unload_selector::unload_selector(), veh_app_interact::veh_app_interact(), veh_interact::veh_interact(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
register_action() [2/2]
void input_context::register_action (const std::string & action_descriptor, const translation & name)
Same as other register_action function but allows a context specific action name.
The given name is displayed instead of the name taken from the input_manager.
Parameters
action_descriptor String of action id.
name Name of the action, displayed to the user. If empty use the name reported by the input_manager.
Definition at line 185 of file input_context.cpp.
 {
     if( action_descriptor == "ANY_INPUT" ) {
         registered_any_input = true;
     } else if( action_descriptor == "COORDINATE" ) {
         handling_coordinate_input = true;
     }
     if( std::find( registered_actions.begin(), registered_actions.end(),
                    action_descriptor ) == registered_actions.end() ) {
         registered_actions.push_back( action_descriptor );
     }
     if( !name.empty() ) {
         action_name_overrides[action_descriptor] = name;
     }
 }
References action_name_overrides, handling_coordinate_input, om_direction::name(), registered_actions, and registered_any_input.
register_cardinal()
void input_context::register_cardinal ()
Definition at line 513 of file input_context.cpp.
 {
     register_updown();
     register_leftright();
 }
References register_leftright(), and register_updown().
Referenced by help::display_help(), make_crafting_context(), main_menu::opening_screen(), robot_finds_kitten::process_input(), register_directions(), set_description(), set_skills(), set_stats(), options_manager::show(), show_scores_ui(), outfit::sort_armor(), minesweeper_game::start_game(), snake_game::start_game(), and sokoban_game::start_game().
register_directions()
void input_context::register_directions ()
Definition at line 492 of file input_context.cpp.
 {
     register_cardinal();
     register_action( "LEFTUP" );
     register_action( "LEFTDOWN" );
     register_action( "RIGHTUP" );
     register_action( "RIGHTDOWN" );
 }
References register_action(), and register_cardinal().
Referenced by choose_direction(), choose_direction_rel_ms(), overmap_ui::display(), editmap::edit(), target_ui::init_window_and_input(), game::look_around(), editmap::mapgen_retarget(), overmap_ui::place_ter_or_special(), editmap::select_shape(), smart_controller_ui::smart_controller_ui(), lightson_game::start_game(), veh_app_interact::veh_app_interact(), and veh_interact::veh_interact().
register_leftright()
void input_context::register_leftright ()
Definition at line 507 of file input_context.cpp.
 {
     register_action( "LEFT" );
     register_action( "RIGHT" );
 }
References register_action().
Referenced by bodygraph_display::bodygraph_display(), debug_menu::change_spells(), construction_menu(), faction_manager::display(), mission_ui::draw_mission_ui(), exosuit_interact::exosuit_interact(), register_cardinal(), prof_window::run(), set_traits(), auto_pickup::user_interface::show(), safemode::show(), diary::show_diary_ui(), color_manager::show_gui(), and worldfactory::show_worldgen_basic().
register_navigate_ui_list()
void input_context::register_navigate_ui_list ()
Definition at line 519 of file input_context.cpp.
 {
     register_action( "UP", to_translation( "Move cursor up" ) );
     register_action( "DOWN", to_translation( "Move cursor down" ) );
     register_action( "SCROLL_UP", to_translation( "Move cursor up" ) );
     register_action( "SCROLL_DOWN", to_translation( "Move cursor down" ) );
     register_action( "PAGE_UP", to_translation( "Fast scroll up" ) );
     register_action( "PAGE_DOWN", to_translation( "Fast scroll down" ) );
     register_action( "HOME", to_translation( "Scroll to top" ) );
     register_action( "END", to_translation( "Scroll to bottom" ) );
 }
References register_action(), and to_translation().
Referenced by bodygraph_display::bodygraph_display(), debug_menu::change_spells(), construction_menu(), Character::disp_info(), faction_manager::display(), mission_ui::draw_mission_ui(), exosuit_interact::exosuit_interact(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_monsters(), worldfactory::pick_world(), prof_window::run(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_traits(), auto_pickup::user_interface::show(), safemode::show(), worldfactory::show_active_world_mods(), diary::show_diary_ui(), color_manager::show_gui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
register_updown()
void input_context::register_updown ()
Definition at line 501 of file input_context.cpp.
 {
     register_action( "UP" );
     register_action( "DOWN" );
 }
References register_action().
Referenced by avatar::power_bionics(), avatar::power_mutations(), register_cardinal(), and multiline_list::set_up_navigation().
reset_timeout()
void input_context::reset_timeout ()
Definition at line 1302 of file input_context.cpp.
 {
     timeout = -1;
 }
References timeout.
Referenced by game::get_player_input(), game::look_around(), and game::zones_manager().
resolve_conflicts()
bool input_context::resolve_conflicts (const std::vector< input_event > & events, const std::string & ignore_action) private
Find all conflicts for all events (excluding conflicts for ignore_action).
If there are any, prompt the user "Should they be cleared?". Then, clear all input_events from all conflicting keybindings (actions) in both the default and current context (see category).
Parameters
events The input events to be cleared from conflicting actions
Returns
true if cleared (user agreed) or if no conflicts found
Definition at line 798 of file input_context.cpp.
 {
     // FIND CONFLICTS
     std::map<std::string, std::vector<input_event>> conflicting_actions_events;
     // for events we want to add
     for( const input_event &event : events ) {
         const std::string conflicting_action = get_conflicts( event, ignore_action );
         const bool has_conflicts = !conflicting_action.empty();
         if( has_conflicts ) {
             conflicting_actions_events[conflicting_action].emplace_back( event );
         }
     }
     // HUMAN READABLE
     std::string conflict_list;
     for( const auto &[action, events] : conflicting_actions_events ) {
         conflict_list += action + ": ";
         std::string sep;
         for( const input_event &event : events ) {
             conflict_list += sep + event.long_description();
             sep = ", ";
         }
         conflict_list += "\n";
     }
     // RESOLVE CONFLICTS
     if( !conflicting_actions_events.empty() &&
         !query_yn(
             _( "Conflict.  The following keybinding(s) will be removed from the respective action(s):\n" )
             + conflict_list + "\n"
             + _( "Continue?" ) )
       ) {
         return false;
     }
     for( const auto &action_events : conflicting_actions_events ) {
         for( const input_event &event : action_events.second ) {
             clear_conflicting_keybindings( event, ignore_action );
         }
     }
     return true;
 }
References _, action, clear_conflicting_keybindings(), get_conflicts(), and query_yn().
Referenced by action_add(), action_remove(), and action_reset().
set_edittext()
void input_context::set_edittext (const std::string & s)
Get/Set edittext to display IME unspecified string.
Definition at line 1287 of file input_context.cpp.
 {
     edittext = s;
 }
References edittext.
Referenced by string_input_popup::query_string().
set_iso()
void input_context::set_iso (bool mode = true)
Definition at line 1268 of file input_context.cpp.
 {
     iso_mode = mode;
 }
References iso_mode.
Referenced by choose_direction(), choose_direction_rel_ms(), editmap::edit(), editmap::eget_direction(), get_default_mode_input_context(), game::get_player_input(), target_ui::init_window_and_input(), game::look_around(), editmap::mapgen_retarget(), and editmap::select_shape().
set_timeout()
void input_context::set_timeout (int val)
Sets input polling timeout as appropriate for the current interface system.
Use this method to set timeouts when using input_context, rather than calling the old timeout() method or using input_manager::(re)set_timeout, as using this method will cause input_event_t::timeout events to be generated correctly, and will reset timeout correctly when a new input context is entered.
Definition at line 1297 of file input_context.cpp.
 {
     timeout = val;
 }
References timeout.
Referenced by display_menu(), mission_ui::draw_mission_ui(), game::get_player_input(), game::look_around(), query_popup::query_once(), and game::zones_manager().
Friends And Related Function Documentation
keybindings_ui
friend class keybindings_ui friend
Definition at line 41 of file input_context.h.
Member Data Documentation
action_name_overrides
std::map<std::string, translation> input_context::action_name_overrides private
When registering for actions within an input_context, callers can specify a custom action name that will override the action's normal name.
This map stores those overrides. The key is the action ID and the value is the user-visible name.
Definition at line 443 of file input_context.h.
Referenced by get_action_name(), and register_action().
category
std::string input_context::category private
Definition at line 428 of file input_context.h.
Referenced by action_add(), action_remove(), action_reset(), action_uses_input(), clear_conflicting_keybindings(), display_menu(), keybindings_ui::draw_controls(), get_action_name(), get_available_single_char_hotkeys(), get_button_text(), get_desc(), input_to_action(), keys_bound_to(), and press_x().
coordinate
point input_context::coordinate private
Definition at line 429 of file input_context.h.
Referenced by get_coordinates(), get_coordinates_text(), and handle_input().
coordinate_input_received
bool input_context::coordinate_input_received private
Definition at line 430 of file input_context.h.
Referenced by get_coordinates(), get_coordinates_text(), and handle_input().
edittext
std::string input_context::edittext private
Definition at line 421 of file input_context.h.
Referenced by get_edittext(), and set_edittext().
handling_coordinate_input
bool input_context::handling_coordinate_input private
Definition at line 431 of file input_context.h.
Referenced by handle_input(), and register_action().
iso_mode
bool input_context::iso_mode = false private
Definition at line 433 of file input_context.h.
Referenced by get_direction(), get_direction_rel_ms(), and set_iso().
next_action
input_event input_context::next_action private
Definition at line 432 of file input_context.h.
Referenced by get_raw_input(), and handle_input().
preferred_keyboard_mode
keyboard_mode input_context::preferred_keyboard_mode = keyboard_mode::keycode private
Definition at line 435 of file input_context.h.
Referenced by action_add(), handle_input(), and is_event_type_enabled().
registered_actions
std::vector<std::string> input_context::registered_actions private
Definition at line 420 of file input_context.h.
Referenced by clear_conflicting_keybindings(), display_menu(), get_available_single_char_hotkeys(), get_conflicts(), input_to_action(), is_registered_action(), and register_action().
registered_any_input
bool input_context::registered_any_input private
Definition at line 427 of file input_context.h.
Referenced by handle_input(), and register_action().
timeout
int input_context::timeout = -1 private
Definition at line 434 of file input_context.h.
Referenced by handle_input(), reset_timeout(), and set_timeout().
The documentation for this class was generated from the following files:
src/input_context.h
src/input_context.cpp