Cataclysm DDA: mapgen_function_json_nested Class Reference
mapgen_function_json_nested Class Reference
#include <mapgen.h>
Public Member Functions
void setup ()
void finalize_parameters ()
void check () const
mapgen_function_json_nested (const JsonObject &jsobj, const std::string &context)
~mapgen_function_json_nested () override=default
void nest (const mapgendata &md, const tripoint_rel_ms &offset, const std::string &outer_context) const
Public Member Functions inherited from mapgen_function_json_base
void merge_non_nest_parameters_into (mapgen_parameters &, const std::string &outer_context) const
bool check_inbounds (const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const JsonObject &jso) const
size_t calc_index (const point &p) const
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &offset) const
void add_placement_coords_to (std::unordered_set< point > &) const
const mapgen_parameters & get_parameters () const
Protected Member Functions
bool setup_internal (const JsonObject &jo) override
Protected Member Functions inherited from mapgen_function_json_base
mapgen_function_json_base (const JsonObject &jsobj, const std::string &context)
virtual ~mapgen_function_json_base ()
void setup_common ()
bool setup_common (const JsonObject &jo)
void setup_setmap (const JsonArray &parray)
virtual void setup_setmap_internal ()
void finalize_parameters_common ()
void check_common () const
mapgen_arguments get_args (const mapgendata &md, mapgen_parameter_scope) const
Private Attributes
jmapgen_int rotation
Additional Inherited Members
Protected Attributes inherited from mapgen_function_json_base
std::string context_
enum_bitset< jmapgen_flags > flags_
bool is_ready
point mapgensize
tripoint_rel_ms m_offset
point total_size
std::vector< jmapgen_setmap > setmap_points
jmapgen_objects objects
mapgen_parameters parameters
Detailed Description
Definition at line 539 of file mapgen.h.
Constructor & Destructor Documentation
mapgen_function_json_nested()
mapgen_function_json_nested::mapgen_function_json_nested (const JsonObject & jsobj, const std::string & context)
Definition at line 875 of file mapgen.cpp.
     : mapgen_function_json_base( jsobj, context )
     , rotation( 0 )
 {
 }
References context.
~mapgen_function_json_nested()
mapgen_function_json_nested::~mapgen_function_json_nested () override default
Member Function Documentation
check()
void mapgen_function_json_nested::check () const
Definition at line 4699 of file mapgen.cpp.
 {
     check_common();
 }
finalize_parameters()
void mapgen_function_json_nested::finalize_parameters ()
Definition at line 4479 of file mapgen.cpp.
 {
     finalize_parameters_common();
 }
nest()
void mapgen_function_json_nested::nest (const mapgendata & md, const tripoint_rel_ms & offset, const std::string & outer_context) const
Definition at line 5282 of file mapgen.cpp.
 {
     // TODO: Make rotation work for submaps, then pass this value into elem & objects apply.
     //int chosen_rotation = rotation.get() % 4;
     mapgendata md_with_params( md, get_args( md, mapgen_parameter_scope::nest ), flags_ );
     std::string context = context_;
     context += " in ";
     context += outer_context;
     apply_mapgen_in_phases( md_with_params, setmap_points, objects, offset, context );
 }
References apply_mapgen_in_phases(), context, and nest.
setup()
void mapgen_function_json_nested::setup ()
Definition at line 4464 of file mapgen.cpp.
 {
     setup_common();
 }
setup_internal()
bool mapgen_function_json_nested::setup_internal (const JsonObject & jo) override protected virtual
Implements mapgen_function_json_base.
Definition at line 4436 of file mapgen.cpp.
 {
     // Mandatory - nested mapgen must be explicitly sized
     if( jo.has_array( "mapgensize" ) ) {
         JsonArray jarr = jo.get_array( "mapgensize" );
         mapgensize = point( jarr.get_int( 0 ), jarr.get_int( 1 ) );
         if( mapgensize.x == 0 || mapgensize.x != mapgensize.y ) {
             // Non-square sizes not implemented yet
             jo.throw_error( "\"mapgensize\" must be an array of two identical, positive numbers" );
         }
         total_size = mapgensize;
     } else {
         jo.throw_error( "Nested mapgen must have \"mapgensize\" set" );
     }
     if( jo.has_member( "rotation" ) ) {
         rotation = jmapgen_int( jo, "rotation" );
     }
     // Nested mapgen is always halal because it can assume underlying map is.
     return true;
 }
References JsonObject::get_array(), JsonArray::get_int(), JsonObject::has_array(), JsonObject::has_member(), point, and JsonObject::throw_error().
Member Data Documentation
rotation
jmapgen_int mapgen_function_json_nested::rotation private
Definition at line 554 of file mapgen.h.
The documentation for this class was generated from the following files:
src/mapgen.h
src/mapgen.cpp