Cataclysm DDA: translation Class Reference
translation Class Reference
Class for storing translation context and raw string for deferred translation.
#include <translation.h>
Classes
struct no_translation_tag
struct plural_tag
Public Member Functions
translation ()
translation (plural_tag)
Same as translation(), but with plural form enabled.
void make_plural ()
Can be used to ensure a translation object has plural form enabled before loading into it from JSON.
void deserialize (const JsonValue &jsin)
Deserialize from json.
void deserialize (const JsonObject &jsobj)
std::string translated (int num=1) const
Returns raw string if no translation is needed, otherwise returns the translated string.
std::string untranslated () const =delete
Methods exposing the underlying raw strings are not implemented, and probably should not if there's no good reason to do so.
void serialize (JsonOut &jsout) const =delete
Similar to untranslated, serialization should not be defined because the saved string will not translate correctly when the source changes.
bool empty () const
Whether the underlying string is empty, not matter what the context is or whether translation is needed.
bool translated_lt (const translation &that) const
Compare translations by their translated strings (singular form).
bool translated_gt (const translation &that) const
bool translated_le (const translation &that) const
bool translated_ge (const translation &that) const
bool translated_eq (const translation &that) const
bool translated_ne (const translation &that) const
bool operator== (const translation &that) const
Compare translations by their context, raw strings (singular / plural), and no-translation flag.
bool operator!= (const translation &that) const
bool operator< (const translation &that) const =delete
Not defined for now.
bool operator> (const translation &that) const =delete
bool operator<= (const translation &that) const =delete
bool operator>= (const translation &that) const =delete
std::optional< int > legacy_hash () const
Only used for migrating old snippet hashes into snippet ids.
Static Public Member Functions
static translation to_translation (const std::string &raw)
Store a string, an optional plural form, and an optional context for translation.
static translation to_translation (const std::string &ctxt, const std::string &raw)
static translation pl_translation (const std::string &raw, const std::string &raw_pl)
static translation pl_translation (const std::string &ctxt, const std::string &raw, const std::string &raw_pl)
static translation no_translation (const std::string &str)
Store a string that needs no translation.
Private Member Functions
translation (const std::string &ctxt, const std::string &raw)
translation (const std::string &raw)
translation (const std::string &raw, const std::string &raw_pl, plural_tag)
translation (const std::string &ctxt, const std::string &raw, const std::string &raw_pl, plural_tag)
translation (const std::string &str, no_translation_tag)
Private Attributes
cata::value_ptr< std::string > ctxt
std::string raw
cata::value_ptr< std::string > raw_pl
bool needs_translation = false
int cached_language_version = INVALID_LANGUAGE_VERSION
int cached_num = 0
cata::value_ptr< std::string > cached_translation
Detailed Description
Class for storing translation context and raw string for deferred translation.
Definition at line 17 of file translation.h.
Constructor & Destructor Documentation
translation() [1/7]
translation::translation () inline
Definition at line 26 of file translation.h.
 {}
translation() [2/7]
translation::translation (plural_tag plural_tag) explicit
Same as translation(), but with plural form enabled.
Definition at line 12 of file translation.cpp.
 : raw_pl( cata::make_value<std::string>() ) {}
References string.
translation() [3/7]
translation::translation (const std::string & ctxt, const std::string & raw) private
Definition at line 14 of file translation.cpp.
     : ctxt( cata::make_value<std::string>( ctxt ) ), raw( raw ), needs_translation( true )
 {
 }
References string.
translation() [4/7]
translation::translation (const std::string & raw) explicit private
Definition at line 19 of file translation.cpp.
     : raw( raw ), needs_translation( true )
 {
 }
translation() [5/7]
translation::translation (const std::string & raw, const std::string & raw_pl, plural_tag plural_tag) private
Definition at line 24 of file translation.cpp.
     : raw( raw ), raw_pl( cata::make_value<std::string>( raw_pl ) ), needs_translation( true )
 {
 }
References string.
translation() [6/7]
translation::translation (const std::string & ctxt, const std::string & raw, const std::string & raw_pl, plural_tag plural_tag) private
Definition at line 30 of file translation.cpp.
     : ctxt( cata::make_value<std::string>( ctxt ) ),
       raw( raw ), raw_pl( cata::make_value<std::string>( raw_pl ) ), needs_translation( true )
 {
 }
References string.
translation() [7/7]
translation::translation (const std::string & str, no_translation_tag no_translation_tag) private
Definition at line 37 of file translation.cpp.
 : raw( str ) {}
Member Function Documentation
deserialize() [1/2]
void translation::deserialize (const JsonObject & jsobj)
Definition at line 177 of file translation.cpp.
 {
     // reset the cache
     cached_language_version = INVALID_LANGUAGE_VERSION;
     cached_num = 0;
     cached_translation = nullptr;
     if( std::optional<JsonValue> comments = jsobj.get_member_opt( "//~" );
         comments.has_value() && !comments->test_string() ) {
         // Ensure we have a string and mark the member as visited in the process
         try {
             jsobj.throw_error_at( "//~", "\"//~\" should be a string that contains comments for translators." );
         } catch( const JsonError &e ) {
             debugmsg( "(json-error)\n%s", e.what() );
         }
     }
     if( jsobj.has_member( "ctxt" ) ) {
         ctxt = cata::make_value<std::string>( jsobj.get_string( "ctxt" ) );
     } else {
         ctxt = nullptr;
     }
 #ifndef CATA_IN_TOOL
     const bool check_style = test_mode && !jsobj.has_member( "//NOLINT(cata-text-style)" );
 #else
     const bool check_style = false;
 #endif
     if( jsobj.has_member( "str_sp" ) ) {
         // same singular and plural forms
         // strings with plural forms are currently only simple names, and
         // need no text style check.
         raw = jsobj.get_string( "str_sp" );
         // if plural form is enabled
         if( raw_pl ) {
             raw_pl = cata::make_value<std::string>( raw );
 #ifndef CATA_IN_TOOL
             if( check_style ) {
                 try {
                     const std::pair<bool, std::string> suggested_pl = possible_plural_of( raw );
                     if( suggested_pl.first && *raw_pl == suggested_pl.second ) {
                         jsobj.throw_error_at(
                             "str_sp",
                             "\"str_sp\" is not necessary here since the plural form can be "
                             "automatically generated." );
                     }
                 } catch( const JsonError &e ) {
                     debugmsg( "(json-error)\n%s", e.what() );
                 }
             }
 #endif
         } else {
             try {
                 jsobj.throw_error_at( "str_sp", "str_sp not supported here" );
             } catch( const JsonError &e ) {
                 debugmsg( "(json-error)\n%s", e.what() );
             }
         }
     } else {
         if( raw_pl || !check_style ) {
             // strings with plural forms are currently only simple names, and
             // need no text style check.
             raw = jsobj.get_string( "str" );
         } else {
             raw = text_style_check_reader( text_style_check_reader::allow_object::no )
                   .get_next( jsobj.get_member( "str" ) );
         }
         // if plural form is enabled
         if( raw_pl ) {
             if( jsobj.has_member( "str_pl" ) ) {
                 raw_pl = cata::make_value<std::string>( jsobj.get_string( "str_pl" ) );
 #ifndef CATA_IN_TOOL
                 if( check_style ) {
                     try {
                         const std::pair<bool, std::string> suggested_pl = possible_plural_of( raw );
                         if( suggested_pl.first && *raw_pl == suggested_pl.second ) {
                             jsobj.throw_error_at(
                                 "str_pl",
                                 "\"str_pl\" is not necessary here since the plural form can "
                                 "be automatically generated." );
                         } else if( *raw_pl == raw ) {
                             jsobj.throw_error_at(
                                 "str_pl",
                                 "Please use \"str_sp\" instead of \"str\" and \"str_pl\" "
                                 "for text with identical singular and plural forms" );
                         }
                     } catch( const JsonError &e ) {
                         debugmsg( "(json-error)\n%s", e.what() );
                     }
                 }
 #endif
             } else {
                 const std::pair<bool, std::string> suggested_pl = possible_plural_of( raw );
                 raw_pl = cata::make_value<std::string>( suggested_pl.second );
 #ifndef CATA_IN_TOOL
                 if( !suggested_pl.first && check_style ) {
                     try {
                         jsobj.throw_error_at(
                             "str",
                             "Cannot autogenerate plural form.  Please specify the plural "
                             "form explicitly using 'str' and 'str_pl', or 'str_sp' if the "
                             "singular and plural forms are the same." );
                     } catch( const JsonError &e ) {
                         debugmsg( "(json-error)\n%s", e.what() );
                     }
                 }
 #endif
             }
         } else if( jsobj.has_member( "str_pl" ) ) {
             try {
                 jsobj.throw_error_at( "str_pl", "str_pl not supported here" );
             } catch( const JsonError &e ) {
                 debugmsg( "(json-error)\n%s", e.what() );
             }
         }
     }
     needs_translation = true;
 }
References cached_language_version, cached_num, cached_translation, ctxt, debugmsg, JsonObject::get_member(), JsonObject::get_member_opt(), text_style_check_reader::get_next(), JsonObject::get_string(), JsonObject::has_member(), INVALID_LANGUAGE_VERSION, needs_translation, text_style_check_reader::no, possible_plural_of(), raw, raw_pl, test_mode, and JsonObject::throw_error_at().
deserialize() [2/2]
void translation::deserialize (const JsonValue & jsin)
Deserialize from json.
Json format is: "text" or { "ctxt": "foo", "str": "bar", "str_pl": "baz" } "ctxt" and "str_pl" are optional. "str_pl" is only valid when an object of this class is constructed with plural_tag or pl_translation(), or converted using make_plural().
Definition at line 122 of file translation.cpp.
 {
     if( jsin.test_string() ) {
         // reset the cache
         cached_language_version = INVALID_LANGUAGE_VERSION;
         cached_num = 0;
         cached_translation = nullptr;
         ctxt = nullptr;
 #ifndef CATA_IN_TOOL
         const bool check_style = test_mode;
 #else
         const bool check_style = false;
 #endif
         if( raw_pl || !check_style ) {
             // strings with plural forms are currently only simple names, and
             // need no text style check.
             raw = jsin.get_string();
         } else {
             // We know it's a string, we need to save the offset after the string.
             raw = text_style_check_reader( text_style_check_reader::allow_object::no )
                   .get_next( jsin );
         }
         // if plural form is enabled
         if( raw_pl ) {
             const std::pair<bool, std::string> suggested_pl = possible_plural_of( raw );
             raw_pl = cata::make_value<std::string>( suggested_pl.second );
 #ifndef CATA_IN_TOOL
             if( !suggested_pl.first && check_style ) {
                 try {
                     jsin.throw_error_after( "Cannot autogenerate plural form.  "
                                             "Please specify the plural form explicitly using "
                                             "'str' and 'str_pl', or 'str_sp' if the singular "
                                             "and plural forms are the same." );
                 } catch( const JsonError &e ) {
                     debugmsg( "(json-error)\n%s", e.what() );
                 }
             }
 #endif
         }
         needs_translation = true;
     } else {
         deserialize( jsin.get_object() );
     }
     // Reset the underlying jsonin stream because errors leave it in an undefined state.
     // This will be removed once everything is migrated off JsonIn.
     if( jsin.test_string() ) {
         jsin.get_string();
     } else if( jsin.test_object() ) {
         jsin.get_object().allow_omitted_members();
     }
 }
References JsonObject::allow_omitted_members(), cached_language_version, cached_num, cached_translation, ctxt, debugmsg, text_style_check_reader::get_next(), JsonValue::get_object(), JsonValue::get_string(), INVALID_LANGUAGE_VERSION, needs_translation, text_style_check_reader::no, possible_plural_of(), raw, raw_pl, test_mode, JsonValue::test_object(), JsonValue::test_string(), and JsonValue::throw_error_after().
Referenced by json_object_read().
empty()
bool translation::empty () const
Whether the underlying string is empty, not matter what the context is or whether translation is needed.
Definition at line 327 of file translation.cpp.
 {
     return raw.empty();
 }
References raw.
Referenced by Character::ablative_armor_absorb(), temperature_effect::apply(), jmapgen_sign::apply(), jmapgen_graffiti::apply(), jmapgen_computer::apply(), butchery_drops_harvest(), fault::check_consistency(), game::climb_down_using(), score::description(), effect::disp_name(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), damage_info_order::finalize(), widget::finalize_label_width_recursive(), hacksaw_activity_actor::finish(), boltcutting_activity_actor::finish(), lockpick_activity_actor::finish(), oxytorch_activity_actor::finish(), json_talk_response::gen_responses(), input_context::get_action_name(), get_encumbrance_description(), iuse_transform::get_name(), message_iuse::get_name(), sound_iuse::get_name(), exosuit_interact::get_pocket_name(), shopkeeper_item_group::get_refusal(), effect::get_speed_name(), item::gun_info(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), game_menus::inv::holster(), jmapgen_graffiti::jmapgen_graffiti(), jmapgen_sign::jmapgen_sign(), widget::load(), place_trap_actor::load(), item_action_generator::load_item_action(), npc::load_npc_template(), spell::message(), MOD_INFORMATION::name(), photo_def_for_camera_point(), recipe::result_name(), gun_actor::shoot(), holster_actor::store(), gun_actor::try_target(), achievement_tracker::ui_text(), achievement_state::ui_text(), item::update_prefix_suffix_flags(), iuse_transform::use(), message_iuse::use(), place_monster_iuse::use(), reveal_map_actor::use(), fireweapon_off_actor::use(), manualnoise_actor::use(), holster_actor::use(), and place_trap_actor::use().
legacy_hash()
std::optional< int > translation::legacy_hash () const
Only used for migrating old snippet hashes into snippet ids.
Definition at line 410 of file translation.cpp.
 {
     if( needs_translation && !ctxt && !raw_pl ) {
         return djb2_hash( reinterpret_cast<const unsigned char *>( raw.c_str() ) );
     }
     // Otherwise the translation must have been added after snippets were changed
     // to use string ids only, so the translation doesn't have a legacy hash value.
     return std::nullopt;
 }
References ctxt, djb2_hash(), needs_translation, raw, and raw_pl.
make_plural()
void translation::make_plural ()
Can be used to ensure a translation object has plural form enabled before loading into it from JSON.
If plural form has not been enabled yet, the plural string will be set to the original singular string. n_gettext will ignore the new plural string and correctly retrieve the original translation. Note that a make_singular() function is not provided due to the potential loss of information.
Definition at line 65 of file translation.cpp.
 {
     if( needs_translation ) {
         // if plural form has not been enabled yet
         if( !raw_pl ) {
             // copy the singular string without appending "s" to preserve the original behavior
             raw_pl = cata::make_value<std::string>( raw );
         }
     } else if( !raw_pl ) {
         // just mark plural form as enabled
         raw_pl = cata::make_value<std::string>();
     }
     // reset the cache
     cached_language_version = INVALID_LANGUAGE_VERSION;
     cached_translation = nullptr;
 }
References cached_language_version, cached_translation, INVALID_LANGUAGE_VERSION, needs_translation, raw, and raw_pl.
Referenced by event_statistic::load(), itype_variant_data::load(), mtype::load(), and item_category::load().
no_translation()
translation translation::no_translation (const std::string & str) static
Store a string that needs no translation.
Definition at line 60 of file translation.cpp.
 {
     return { str, no_translation_tag() };
 }
Referenced by no_translation().
operator!=()
bool translation::operator!= (const translation & that) const
Definition at line 405 of file translation.cpp.
 {
     return !operator==( that );
 }
References operator==().
operator<()
bool translation::operator< (const translation & that) const delete
Not defined for now.
Use translated_(lt|gt|le|ge) if you want to do localized comparison.
operator<=()
bool translation::operator<= (const translation & that) const delete
operator==()
bool translation::operator== (const translation & that) const
Compare translations by their context, raw strings (singular / plural), and no-translation flag.
Use translated_(eq|ne) if you want to do localized comparison.
Definition at line 398 of file translation.cpp.
 {
     return value_ptr_equals( ctxt, that.ctxt ) && raw == that.raw &&
            value_ptr_equals( raw_pl, that.raw_pl ) &&
            needs_translation == that.needs_translation;
 }
References ctxt, needs_translation, raw, raw_pl, and cata::value_ptr_equals().
Referenced by operator!=().
operator>()
bool translation::operator> (const translation & that) const delete
operator>=()
bool translation::operator>= (const translation & that) const delete
pl_translation() [1/2]
translation translation::pl_translation (const std::string & ctxt, const std::string & raw, const std::string & raw_pl) static
Definition at line 54 of file translation.cpp.
 {
     return { ctxt, raw, raw_pl, plural_tag() };
 }
References ctxt, raw, and raw_pl.
pl_translation() [2/2]
translation translation::pl_translation (const std::string & raw, const std::string & raw_pl) static
Definition at line 49 of file translation.cpp.
 {
     return { raw, raw_pl, plural_tag() };
 }
References raw, and raw_pl.
Referenced by pl_translation().
serialize()
void translation::serialize (JsonOut & jsout) const delete
Similar to untranslated, serialization should not be defined because the saved string will not translate correctly when the source changes.
to_translation() [1/2]
translation translation::to_translation (const std::string & ctxt, const std::string & raw) static
Definition at line 44 of file translation.cpp.
 {
     return { ctxt, raw };
 }
References ctxt, and raw.
to_translation() [2/2]
translation translation::to_translation (const std::string & raw) static
Store a string, an optional plural form, and an optional context for translation.
Definition at line 39 of file translation.cpp.
 {
     return translation{ raw };
 }
References raw.
Referenced by to_translation().
translated()
std::string translation::translated (int num = 1) const
Returns raw string if no translation is needed, otherwise returns the translated string.
A number can be used to translate the plural form if the object has it.
Definition at line 294 of file translation.cpp.
 {
     if( !needs_translation || raw.empty() ) {
         return raw;
     }
     // Note1: `raw`, `raw_pl` and `ctxt` are effectively immutable for caching purposes:
     // in the places where they are changed, cache is explicitly invalidated
     // Note2: if `raw_pl` is defined, `num` becomes part of the "cache key"
     // otherwise `num` is ignored (for both translation and cache)
     if( cached_language_version != detail::get_current_language_version() ||
         ( raw_pl && cached_num != num ) || !cached_translation ) {
         cached_language_version = detail::get_current_language_version();
         cached_num = num;
         if( !ctxt ) {
             if( !raw_pl ) {
                 cached_translation = cata::make_value<std::string>( detail::_translate_internal( raw ) );
             } else {
                 cached_translation = cata::make_value<std::string>(
                                          n_gettext( raw.c_str(), raw_pl->c_str(), num ) );
             }
         } else {
             if( !raw_pl ) {
                 cached_translation = cata::make_value<std::string>( pgettext( ctxt->c_str(), raw.c_str() ) );
             } else {
                 cached_translation = cata::make_value<std::string>(
                                          npgettext( ctxt->c_str(), raw.c_str(), raw_pl->c_str(), num ) );
             }
         }
     }
     return *cached_translation;
 }
References detail::_translate_internal(), cached_language_version, cached_num, cached_translation, ctxt, detail::get_current_language_version(), n_gettext, needs_translation, npgettext, pgettext, raw, and raw_pl.
Referenced by Character::ablative_armor_absorb(), Creature::add_msg_if_npc(), Creature::add_msg_if_player(), Creature::add_msg_player_or_npc(), Creature::add_msg_player_or_say(), temperature_effect::apply(), jmapgen_sign::apply(), jmapgen_graffiti::apply(), jmapgen_computer::apply(), assemble_profession_details(), material_type::bash_dmg_verb(), item::basic_info(), basic_item_filter(), mattack::bio_op_takedown(), body_part_hp_bar_ui_text(), body_part_name(), body_part_name_accusative(), body_part_name_as_heading(), build_bionic_powerdesc_string(), butchery_drops_harvest(), debug_menu::change_spells(), choose_ma_style(), game::climb_down_using(), colorize(), npc::complain(), item::contents_info(), material_type::cut_dmg_verb(), spell::damage_type_string(), zone_type::desc(), mutation_branch::desc(), faction::describe(), fault::description(), spell::description(), map_extra::description(), proficiency::description(), Skill::description(), profession::description(), scenario::description(), score::description(), monster::die(), effect::disp_name(), SkillDisplayType::display_string(), npc::distance_string(), draw_bionics_tab(), draw_effects_summary(), dialogue::dynamic_line(), editmap::edit_fld(), encumb_text(), npc::execute_action(), vehicles::finalize_prototypes(), npc::find_corpse_to_pulp(), hacksaw_activity_actor::finish(), boltcutting_activity_actor::finish(), lockpick_activity_actor::finish(), oxytorch_activity_actor::finish(), enchant_cache::force_add(), vpart_info::format_description(), json_talk_response::gen_responses(), profession::gender_appropriate_name(), scenario::gender_appropriate_name(), input_context::get_action_name(), effect_type::get_blood_analysis_description(), npc::get_current_activity(), effect::get_death_message(), bonus_container::get_description(), mission::get_description(), mtype::get_description(), species_type::get_footsteps(), conditional_t::get_get_string(), npc_class::get_job_description(), vpart_variant::get_label(), field_effect::get_message(), weakpoint_effect::get_message(), field_effect::get_message_npc(), npc_class::get_name(), oter_t::get_name(), window_panel::get_name(), weakpoint::get_name(), iuse_transform::get_name(), message_iuse::get_name(), sound_iuse::get_name(), field_type::get_name(), exosuit_interact::get_pocket_name(), shopkeeper_item_group::get_refusal(), effect_type::get_remove_message(), recipe_result_info_cache::get_result_data(), snippet_library::get_snippets_by_category(), effect::get_speed_name(), widget::get_window_panel(), talker_npc::give_item_to(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), game_menus::inv::holster(), json_flag::info(), learn_spell_actor::info(), iuse_function_wrapper_with_info::info(), item::item(), item_filter_rule_string(), inscribe_actor::item_inscription(), fault::item_prefix(), lcmatch(), widget::load(), npc::load_npc_template(), item::magazine_info(), magic_train(), spell::make_sound(), Character::melee_attack_abstract(), melee_message(), activity_handlers::mend_item_finish(), vehicle::merge_appliance_into_grid(), harvest_list::message(), spell::message(), mutation_category_trait::mutagen_message(), Character::mutation_attacks(), ammunition_type::name(), zone_type::name(), construction_category::name(), construction_group::name(), fault::name(), json_flag::name(), spell::name(), map_extra::name(), map_data_common_t::name(), material_type::name(), MOD_INFORMATION::name(), move_mode::name(), mutation_category_trait::name(), panel_layout::name(), proficiency::name(), Skill::name(), start_location::name(), trap::name(), vpart_category::name(), vpart_info::name(), vitamin::name(), mutation_branch::name(), item_category::name_header(), item_category::name_noun(), mtype::nname(), Character::on_damage_of_type(), anonymous_namespace{bionics_ui.cpp}::bionic_sort_less::operator()(), operator+(), operator<<(), vehicle::part_removal_cleanup(), character_martial_arts::pick_style(), map::player_in_field(), practice_recipe_description(), outfit::prepare_bodymap_info(), print_damage_info(), mutation_branch::ranged_mutation_message(), json_flag::restriction(), recipe::result_name(), select_crafter_and_crafting_recipe(), character_martial_arts::selected_style_name(), spell_type::serialize(), gun_actor::shoot(), vpart_category::short_name(), auto_notes::auto_note_manager_gui::show(), options_manager::show(), sleep(), smash(), sort_body_parts(), sounds::sound(), mutation_branch::spawn_item_message(), talker_character_const::spell_seminar_text(), scenario::start_name(), holster_actor::store(), talker_character_const::style_seminar_text(), widget::sym_text(), widget::sym_text_cond(), avatar::talk_to(), activity_handlers::teach_finish(), widget::text(), widget::text_cond(), text_for_requirement(), gun_mode::tname(), gun_modifier_data::tname(), mission_type::tname(), translated_eq(), translated_lt(), try_consume(), gun_actor::try_target(), item::type_name(), target_ui::uitext_fire(), message_iuse::use(), sound_iuse::use(), consume_drug_iuse::use(), manualnoise_actor::use(), holster_actor::use(), place_trap_actor::use(), sew_advanced_actor::use(), learn_spell_actor::use(), item::variant_description(), vehicle::vehicle(), npc::wants_to_buy(), npc::warn_about(), npc::wear_if_wanted(), and debug_menu::wishitem().
translated_eq()
bool translation::translated_eq (const translation & that) const
Definition at line 352 of file translation.cpp.
 {
     return translated() == that.translated();
 }
References translated().
Referenced by translated_equal_to::operator()(), item_category::operator==(), and translated_ne().
translated_ge()
bool translation::translated_ge (const translation & that) const
Definition at line 347 of file translation.cpp.
 {
     return !translated_lt( that );
 }
References translated_lt().
Referenced by translated_greater_equal::operator()().
translated_gt()
bool translation::translated_gt (const translation & that) const
Definition at line 337 of file translation.cpp.
 {
     return that.translated_lt( *this );
 }
References translated_lt().
Referenced by translated_greater::operator()().
translated_le()
bool translation::translated_le (const translation & that) const
Definition at line 342 of file translation.cpp.
 {
     return !that.translated_lt( *this );
 }
References translated_lt().
Referenced by translated_less_equal::operator()().
translated_lt()
bool translation::translated_lt (const translation & that) const
Compare translations by their translated strings (singular form).
Be especially careful when using these to sort translations, as the translated result will change when switching the language.
When updating the comparison functions, please also update tools/clang-tidy-plugin/NoStaticTranslationCheck.cpp and tools/clang-tidy-plugin/test/no-static-translation.cpp.
Definition at line 332 of file translation.cpp.
 {
     return localized_compare( translated(), that.translated() );
 }
References localized_compare, and translated().
Referenced by Character::disp_info(), localized_comparator::operator()(), translated_less::operator()(), item_category::operator<(), translated_ge(), translated_gt(), and translated_le().
translated_ne()
bool translation::translated_ne (const translation & that) const
Definition at line 357 of file translation.cpp.
 {
     return !translated_eq( that );
 }
References translated_eq().
Referenced by translated_not_equal_to::operator()(), and item_category::operator<().
untranslated()
std::string translation::untranslated () const delete
Methods exposing the underlying raw strings are not implemented, and probably should not if there's no good reason to do so.
Most importantly, the underlying strings should not be re-saved to JSON: doing so risk the original string being changed during development and the saved string will then not be properly translated when loaded back. If you really want to save a translation, translate it early on, store it using no_translation, and retrieve it using translated() when saving. This ensures consistent behavior before and after saving and loading.
Member Data Documentation
cached_language_version
int translation::cached_language_version = INVALID_LANGUAGE_VERSION mutable private
Definition at line 151 of file translation.h.
Referenced by deserialize(), make_plural(), and translated().
cached_num
int translation::cached_num = 0 mutable private
Definition at line 153 of file translation.h.
Referenced by deserialize(), and translated().
cached_translation
cata::value_ptr<std::string> translation::cached_translation mutable private
Definition at line 154 of file translation.h.
Referenced by deserialize(), make_plural(), and translated().
ctxt
cata::value_ptr<std::string> translation::ctxt private
Definition at line 146 of file translation.h.
Referenced by deserialize(), legacy_hash(), operator==(), pl_translation(), to_translation(), and translated().
needs_translation
bool translation::needs_translation = false private
Definition at line 149 of file translation.h.
Referenced by deserialize(), legacy_hash(), make_plural(), operator==(), and translated().
raw
std::string translation::raw private
Definition at line 147 of file translation.h.
Referenced by deserialize(), empty(), legacy_hash(), make_plural(), operator==(), pl_translation(), to_translation(), and translated().
raw_pl
cata::value_ptr<std::string> translation::raw_pl private
Definition at line 148 of file translation.h.
Referenced by deserialize(), legacy_hash(), make_plural(), operator==(), pl_translation(), and translated().
The documentation for this class was generated from the following files:
src/translation.h
src/translation.cpp