Cataclysm DDA: vpart_category Class Reference
vpart_category Class Reference
#include <veh_type.h>
Public Member Functions
std::string get_id () const
std::string name () const
std::string short_name () const
bool operator< (const vpart_category &cat) const
Static Public Member Functions
static const std::vector< vpart_category > & all ()
static void load (const JsonObject &jo)
static void finalize ()
static void reset ()
Private Attributes
std::string id_
translation name_
translation short_name_
int priority_ = 0
Detailed Description
Definition at line 177 of file veh_type.h.
Member Function Documentation
all()
const std::vector< vpart_category > & vpart_category::all () static
Definition at line 1702 of file veh_type.cpp.
 {
     return vpart_categories_all;
 }
References vpart_categories_all.
Referenced by veh_interact::do_install().
finalize()
void vpart_category::finalize () static
Definition at line 1719 of file veh_type.cpp.
 {
     std::sort( vpart_categories_all.begin(), vpart_categories_all.end() );
 }
References vpart_categories_all.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_id()
std::string vpart_category::get_id () const inline
Definition at line 186 of file veh_type.h.
{
             return id_;
         }
References id_.
load()
void vpart_category::load (const JsonObject & jo) static
Definition at line 1707 of file veh_type.cpp.
 {
     vpart_category def;
     assign( jo, "id", def.id_ );
     assign( jo, "name", def.name_ );
     assign( jo, "short_name", def.short_name_ );
     assign( jo, "priority", def.priority_ );
     vpart_categories_all.push_back( def );
 }
References assign(), id_, name_, priority_, short_name_, and vpart_categories_all.
Referenced by DynamicDataLoader::initialize().
name()
std::string vpart_category::name () const inline
Definition at line 190 of file veh_type.h.
{
             return name_.translated();
         }
References name_, and translation::translated().
operator<()
bool vpart_category::operator< (const vpart_category & cat) const inline
Definition at line 198 of file veh_type.h.
{
             return priority_ < cat.priority_;
         }
References priority_.
reset()
void vpart_category::reset () static
Definition at line 1724 of file veh_type.cpp.
 {
     vpart_categories_all.clear();
 }
References vpart_categories_all.
Referenced by DynamicDataLoader::unload_data().
short_name()
std::string vpart_category::short_name () const inline
Definition at line 194 of file veh_type.h.
{
             return short_name_.translated();
         }
References short_name_, and translation::translated().
Member Data Documentation
id_
std::string vpart_category::id_ private
Definition at line 203 of file veh_type.h.
Referenced by get_id(), and load().
name_
translation vpart_category::name_ private
Definition at line 204 of file veh_type.h.
Referenced by load(), and name().
priority_
int vpart_category::priority_ = 0 private
Definition at line 206 of file veh_type.h.
Referenced by load(), and operator<().
short_name_
translation vpart_category::short_name_ private
Definition at line 205 of file veh_type.h.
Referenced by load(), and short_name().
The documentation for this class was generated from the following files:
src/veh_type.h
src/veh_type.cpp