Cataclysm DDA: auto_pickup::player_settings Class Reference
auto_pickup::player_settings Class Reference
#include <auto_pickup.h>
Public Member Functions
~player_settings () override=default
void create_rule (const item *it)
bool has_rule (const item *it)
void add_rule (const item *it, bool include)
void remove_rule (const item *it)
void clear_character_rules ()
void show ()
bool save_character ()
bool save_global ()
void load_character ()
void load_global ()
bool empty () const
Public Member Functions inherited from auto_pickup::base_settings
virtual ~base_settings ()=default
rule_state check_item (const std::string &sItemName) const
Private Member Functions
void load (bool bCharacter)
bool save (bool bCharacter)
void refresh_map_items (cache &map_items) const override
Private Attributes
rule_list global_rules
rule_list character_rules
Additional Inherited Members
Protected Member Functions inherited from auto_pickup::base_settings
void invalidate ()
Protected Attributes inherited from auto_pickup::base_settings
cache map_items
Detailed Description
Definition at line 118 of file auto_pickup.h.
Constructor & Destructor Documentation
~player_settings()
auto_pickup::player_settings::~player_settings () override default
Member Function Documentation
add_rule()
void player_settings::add_rule (const item * it, bool include)
Definition at line 757 of file auto_pickup.cpp.
 {
     character_rules.push_back( rule( it->tname( 1, false ), true, !include ) );
     create_rule( it );
     if( !get_option<bool>( "AUTO_PICKUP" ) &&
         query_yn( _( "Auto pickup is not enabled in the options.  Enable it now?" ) ) ) {
         get_options().get_option( "AUTO_PICKUP" ).setNext();
         get_options().save();
     }
 }
References _, character_rules, create_rule(), options_manager::get_option(), get_options(), query_yn(), options_manager::save(), options_manager::cOpt::setNext(), and item::tname().
Referenced by advanced_inventory::display(), and game::inventory_item_menu().
clear_character_rules()
void player_settings::clear_character_rules ()
Definition at line 919 of file auto_pickup.cpp.
 {
     character_rules.clear();
     invalidate();
 }
References character_rules, and auto_pickup::base_settings::invalidate().
Referenced by game::start_game().
create_rule()
void player_settings::create_rule (const item * it)
Definition at line 838 of file auto_pickup.cpp.
 {
     // TODO: change it to be a reference
     global_rules.create_rule( map_items, *it );
     character_rules.create_rule( map_items, *it );
 }
References character_rules, auto_pickup::rule_list::create_rule(), global_rules, and auto_pickup::base_settings::map_items.
Referenced by add_rule(), and get_autopickup_rule().
empty()
bool player_settings::empty () const
Definition at line 783 of file auto_pickup.cpp.
 {
     return global_rules.empty() && character_rules.empty();
 }
References character_rules, and global_rules.
has_rule()
bool player_settings::has_rule (const item * it)
Definition at line 746 of file auto_pickup.cpp.
 {
     const std::string &name = it->tname( 1 );
     for( auto_pickup::rule &elem : character_rules ) {
         if( name.length() == elem.sRule.length() && ci_find_substr( name, elem.sRule ) != -1 ) {
             return true;
         }
     }
     return false;
 }
References character_rules, ci_find_substr(), om_direction::name(), and item::tname().
Referenced by game::inventory_item_menu().
load()
void player_settings::load (bool bCharacter) private
Definition at line 965 of file auto_pickup.cpp.
 {
     cata_path sFile = PATH_INFO::autopickup();
     if( bCharacter ) {
         sFile = PATH_INFO::player_base_save_path_path() + ".apu.json";
     }
     read_from_file_optional_json( sFile, [&]( const JsonValue & jv ) {
         ( bCharacter ? character_rules : global_rules ).deserialize( jv );
     } ) ;
     invalidate();
 }
References PATH_INFO::autopickup(), character_rules, deserialize(), global_rules, auto_pickup::base_settings::invalidate(), PATH_INFO::player_base_save_path_path(), and read_from_file_optional_json().
Referenced by load_character(), and load_global().
load_character()
void player_settings::load_character ()
Definition at line 955 of file auto_pickup.cpp.
 {
     load( true );
 }
References load().
Referenced by game::load().
load_global()
void player_settings::load_global ()
Definition at line 960 of file auto_pickup.cpp.
 {
     load( false );
 }
References load().
Referenced by game::load_static_data().
refresh_map_items()
void player_settings::refresh_map_items (cache & map_items) const override private virtual
Implements auto_pickup::base_settings.
Definition at line 862 of file auto_pickup.cpp.
 {
     //process include/exclude in order of rules, global first, then character specific
     //if a specific item is being added, all the rules need to be checked now
     //may have some performance issues since exclusion needs to check all items also
     global_rules.refresh_map_items( map_items );
     character_rules.refresh_map_items( map_items );
 }
References character_rules, global_rules, auto_pickup::base_settings::map_items, and auto_pickup::rule_list::refresh_map_items().
remove_rule()
void player_settings::remove_rule (const item * it)
Definition at line 769 of file auto_pickup.cpp.
 {
     const std::string sRule = it->tname( 1, false );
     for( rule_list::iterator candidate = character_rules.begin();
          candidate != character_rules.end(); ++candidate ) {
         if( sRule.length() == candidate->sRule.length() &&
             ci_find_substr( sRule, candidate->sRule ) != -1 ) {
             character_rules.erase( candidate );
             invalidate();
             break;
         }
     }
 }
References character_rules, ci_find_substr(), auto_pickup::base_settings::invalidate(), and item::tname().
Referenced by advanced_inventory::display(), and game::inventory_item_menu().
save()
bool player_settings::save (bool bCharacter) private
Definition at line 935 of file auto_pickup.cpp.
 {
     cata_path savefile = PATH_INFO::autopickup();
     if( bCharacter ) {
         savefile = PATH_INFO::player_base_save_path_path() + ".apu.json";
         const std::string player_save = PATH_INFO::player_base_save_path() + ".sav";
         //Character not saved yet.
         if( !file_exist( player_save ) ) {
             return true;
         }
     }
     return write_to_file( savefile, [&]( std::ostream & fout ) {
         JsonOut jout( fout, true );
         ( bCharacter ? character_rules : global_rules ).serialize( jout );
     }, _( "auto pickup configuration" ) );
 }
References _, PATH_INFO::autopickup(), character_rules, file_exist(), global_rules, PATH_INFO::player_base_save_path(), PATH_INFO::player_base_save_path_path(), serialize(), and write_to_file().
Referenced by save_character(), and save_global().
save_character()
bool player_settings::save_character ()
Definition at line 925 of file auto_pickup.cpp.
 {
     return save( true );
 }
References save().
Referenced by game::save(), and show().
save_global()
bool player_settings::save_global ()
Definition at line 930 of file auto_pickup.cpp.
 {
     return save( false );
 }
References save().
Referenced by show().
show()
void player_settings::show ()
Definition at line 614 of file auto_pickup.cpp.
 {
     user_interface ui;
     Character &player_character = get_player_character();
     ui.title = _( "Auto pickup manager" );
     ui.tabs.emplace_back( _( "[<Global>]" ), global_rules );
     if( !player_character.name.empty() ) {
         ui.tabs.emplace_back( _( "[<Character>]" ), character_rules );
     }
     ui.show();
     if( !ui.bStuffChanged ) {
         return;
     }
     save_global();
     if( !player_character.name.empty() ) {
         save_character();
     }
     invalidate();
 }
References _, character_rules, get_player_character(), global_rules, auto_pickup::base_settings::invalidate(), Character::name, save_character(), and save_global().
Referenced by game::do_regular_action(), and main_menu::opening_screen().
Member Data Documentation
character_rules
rule_list auto_pickup::player_settings::character_rules private
Definition at line 125 of file auto_pickup.h.
Referenced by add_rule(), clear_character_rules(), create_rule(), empty(), has_rule(), load(), refresh_map_items(), remove_rule(), save(), and show().
global_rules
rule_list auto_pickup::player_settings::global_rules private
Definition at line 124 of file auto_pickup.h.
Referenced by create_rule(), empty(), load(), refresh_map_items(), save(), and show().
The documentation for this class was generated from the following files:
src/auto_pickup.h
src/auto_pickup.cpp