Cataclysm DDA: json_talk_repeat_response Class Reference
json_talk_repeat_response Class Reference
A structure for generating repeated responses.
#include <dialogue.h>
Public Member Functions
json_talk_repeat_response ()=default
json_talk_repeat_response (const JsonObject &jo)
Public Attributes
bool is_npc = false
bool include_containers = false
std::vector< itype_id > for_item
std::vector< item_category_id > for_category
json_talk_response response
Detailed Description
A structure for generating repeated responses.
Definition at line 393 of file dialogue.h.
Constructor & Destructor Documentation
json_talk_repeat_response() [1/2]
json_talk_repeat_response::json_talk_repeat_response () default
json_talk_repeat_response() [2/2]
json_talk_repeat_response::json_talk_repeat_response (const JsonObject & jo) explicit
Definition at line 6685 of file npctalk.cpp.
 {
     if( jo.has_bool( "is_npc" ) ) {
         is_npc = true;
     }
     if( jo.has_bool( "include_containers" ) ) {
         include_containers = true;
     }
     if( jo.has_string( "for_item" ) ) {
         for_item.emplace_back( jo.get_string( "for_item" ) );
     } else if( jo.has_array( "for_item" ) ) {
         for( const std::string line : jo.get_array( "for_item" ) ) {
             for_item.emplace_back( line );
         }
     } else if( jo.has_string( "for_category" ) ) {
         for_category.emplace_back( jo.get_string( "for_category" ) );
     } else if( jo.has_array( "for_category" ) ) {
         for( const std::string line : jo.get_array( "for_category" ) ) {
             for_category.emplace_back( line );
         }
     } else {
         jo.throw_error( "Repeat response with no repeat information!" );
     }
     if( for_item.empty() && for_category.empty() ) {
         jo.throw_error( "Repeat response with empty repeat information!" );
     }
     if( jo.has_object( "response" ) ) {
         JsonObject response_obj = jo.get_object( "response" );
         response = json_talk_response( response_obj );
     } else {
         jo.throw_error( "Repeat response with no response!" );
     }
 }
References for_category, for_item, JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_bool(), JsonObject::has_object(), JsonObject::has_string(), include_containers, is_npc, line, response, and JsonObject::throw_error().
Member Data Documentation
for_category
std::vector<item_category_id> json_talk_repeat_response::for_category
Definition at line 401 of file dialogue.h.
Referenced by json_talk_repeat_response().
for_item
std::vector<itype_id> json_talk_repeat_response::for_item
Definition at line 400 of file dialogue.h.
Referenced by json_talk_repeat_response().
include_containers
bool json_talk_repeat_response::include_containers = false
Definition at line 399 of file dialogue.h.
Referenced by json_talk_repeat_response().
is_npc
bool json_talk_repeat_response::is_npc = false
Definition at line 398 of file dialogue.h.
Referenced by json_talk_repeat_response().
response
json_talk_response json_talk_repeat_response::response
Definition at line 402 of file dialogue.h.
Referenced by json_talk_repeat_response().
The documentation for this class was generated from the following files:
src/dialogue.h
src/npctalk.cpp