Cataclysm DDA: ammo_inventory_selector Class Reference
ammo_inventory_selector Class Reference
#include <inventory_ui.h>
Public Member Functions
ammo_inventory_selector (Character &you, const item_location &reload_loc, const inventory_selector_preset &preset=default_preset)
drop_location execute ()
void set_all_entries_chosen_count ()
Public Member Functions inherited from inventory_selector
inventory_selector (Character &u, const inventory_selector_preset &preset=default_preset)
virtual ~inventory_selector ()
bool add_contained_items (item_location &container)
These functions add items from map / vehicles.
bool add_contained_items (item_location &container, inventory_column &column, const item_category *custom_category=nullptr, item_location const &topmost_parent={}, int indent=0)
void add_contained_gunmods (Character &you, item &gun)
void add_contained_ebooks (item_location &container)
void add_character_items (Character &character)
void add_map_items (const tripoint &target)
void add_vehicle_items (const tripoint &target)
void add_nearby_items (int radius=1)
void add_remote_map_items (tinymap *remote_map, const tripoint &target)
void add_basecamp_items (const basecamp &camp)
void clear_items ()
Remove all items.
void set_title (const std::string &title)
Assigns a title that will be shown on top of the menu.
void set_hint (const std::string &hint)
Assigns a hint.
void set_display_stats (bool display_stats)
Specify whether the header should show stats (weight and volume).
bool empty () const
bool has_available_choices () const
uint64_t item_entry_count () const
drop_location get_only_choice () const
void set_filter (const std::string &str)
Apply filter string to all columns.
std::string get_filter () const
Get last filter string set by set_filter or entered by player.
void set_invlet_type (selector_invlet_type type)
Set the letter group to use for automatic inventory letters.
selector_invlet_type invlet_type ()
void show_invlet (bool show)
Set whether to show inventory letters.
bool showing_invlet () const
void categorize_map_items (bool toggle)
bool highlight (const item_location &loc, bool hidden=false, bool front_only=false)
Highlight a location.
const inventory_entry & get_highlighted () const
item_location get_collation_next () const
void highlight_position (std::pair< size_t, size_t > position)
bool highlight_one_of (const std::vector< item_location > &locations, bool hidden=false)
std::pair< size_t, size_t > get_highlighted_position () const
inventory_column & get_column (size_t index) const
inventory_column & get_active_column () const
void toggle_categorize_contained ()
void set_active_column (size_t index)
void toggle_skip_unselectable ()
std::string action_bound_to_key (char key) const
Private Member Functions
void mod_chosen_count (inventory_entry &entry, int val)
Private Attributes
const item_location reload_loc
Additional Inherited Members
Public Types inherited from inventory_selector
enum selector_invlet_type { SELECTOR_INVLET_DEFAULT , SELECTOR_INVLET_NUMERIC , SELECTOR_INVLET_ALPHA }
enum class uimode : int { categories = 0 , hierarchy , last }
using stat = std::array< std::string, 4 >
using stats = std::array< stat, 3 >
Protected Member Functions inherited from inventory_selector
const item_category * naturalize_category (const item_category &category, const tripoint &pos)
inventory_entry * add_entry (inventory_column &target_column, std::vector< item_location > &&locations, const item_category *custom_category=nullptr, size_t chosen_count=0, item_location const &topmost_parent={}, bool chevron=false)
bool add_entry_rec (inventory_column &entry_column, inventory_column &children_column, item_location &loc, item_category const *entry_category=nullptr, item_category const *children_category=nullptr, item_location const &topmost_parent={}, int indent=0)
bool drag_drop_item (item *sourceItem, item *destItem)
inventory_input get_input ()
inventory_input process_input (const std::string &action, int ch)
void on_input (const inventory_input &input)
Given an action from the input_context, try to act according to it.
void on_change (const inventory_entry &entry)
Entry has been changed.
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
size_t get_layout_width () const
size_t get_layout_height () const
std::pair< bool, std::string > query_string (const std::string &val, bool end_with_toggle=false)
Query user for a string and return it.
void query_set_filter ()
Query the user for a filter and apply it.
int query_count (char init=0, bool end_with_toggle=false)
Query the user for count and return it.
virtual void rearrange_columns (size_t client_width)
Tackles screen overflow.
virtual stats get_raw_stats () const
Get stats to display in top right.
std::vector< std::string > get_stats () const
std::pair< std::string, nc_color > get_footer (navigation_mode m) const
size_t get_header_height () const
size_t get_header_min_width () const
size_t get_footer_min_width () const
inventory_entry * find_entry_by_invlet (int invlet) const
inventory_entry * find_entry_by_coordinate (const point &coordinate) const
inventory_entry * find_entry_by_location (item_location &loc) const
const std::vector< inventory_column * > & get_all_columns () const
std::vector< inventory_column * > get_visible_columns () const
void highlight ()
Highlight parent and contents of highlighted item.
void action_examine (const item_location &sitem)
Show detailed item information for the selected item.
virtual void reassign_custom_invlets ()
size_t get_columns_width (const std::vector< inventory_column * > &columns) const
double get_columns_occupancy_ratio (size_t client_width) const
bool are_columns_centered (size_t client_width) const
bool is_overflown (size_t client_width) const
bool is_active_column (const inventory_column &column) const
void append_column (inventory_column &column)
void toggle_active_column (scroll_direction dir)
Activates either previous or next column.
void refresh_active_column ()
void toggle_navigation_mode ()
const navigation_mode_data & get_navigation_data (navigation_mode m) const
Static Protected Member Functions inherited from inventory_selector
static stat get_weight_and_length_stat (units::mass weight_carried, units::mass weight_capacity, const units::length &longest_length)
static stat get_volume_stat (const units::volume &volume_carried, const units::volume &volume_capacity, const units::volume &largest_free_volume)
static stat get_holster_stat (const units::volume &holster_volume, int used_holsters, int total_holsters)
static stats get_weight_and_volume_and_holster_stats (units::mass weight_carried, units::mass weight_capacity, const units::volume &volume_carried, const units::volume &volume_capacity, const units::length &longest_length, const units::volume &largest_free_volume, const units::volume &holster_volume, int used_holsters, int total_holsters)
Protected Attributes inherited from inventory_selector
Character & u
const inventory_selector_preset & preset
input_context ctxt
The input context for navigation, already contains some actions for movement.
std::vector< std::pair< inclusive_rectangle< point >, inventory_entry * > > rect_entry_map
std::vector< inventory_column * > columns
point _fixed_origin { -1, -1 }
point _fixed_size { -1, -1 }
bool _categorize_map_items = false
bool force_single_column = false
Detailed Description
Definition at line 948 of file inventory_ui.h.
Constructor & Destructor Documentation
ammo_inventory_selector()
ammo_inventory_selector::ammo_inventory_selector (Character & you, const item_location & reload_loc, const inventory_selector_preset & preset = default_preset) explicit
Definition at line 3347 of file inventory_ui.cpp.
                                                                                    :
     inventory_selector( you, preset ), reload_loc( reload_loc )
 {
     ctxt.register_action( "INCREASE_COUNT" );
     ctxt.register_action( "DECREASE_COUNT" );
     force_single_column = true;
 }
References inventory_selector::ctxt, inventory_selector::force_single_column, and input_context::register_action().
Member Function Documentation
execute()
drop_location ammo_inventory_selector::execute ()
Definition at line 3417 of file inventory_ui.cpp.
 {
     shared_ptr_fast<ui_adaptor> ui = create_or_get_ui_adaptor();
     debug_print_timer( tp_start );
     while( true ) {
         ui_manager::redraw();
         const inventory_input input = get_input();
         if( input.entry != nullptr ) {
             if( input.action == "MOUSE_MOVE" ) {
                 if( highlight( input.entry->any_item() ) ) {
                     ui_manager::redraw();
                 }
             } else if( input.action == "ANY_INPUT" || input.action == "SELECT" ) {
                 return { input.entry->any_item(), static_cast<int>( input.entry->chosen_count ) };
             } else {
                 if( highlight( input.entry->any_item() ) ) {
                     ui_manager::redraw();
                 }
                 on_input( input );
             }
         } else if( input.action == "QUIT" ) {
             return drop_location();
         } else if( input.action == "CONFIRM" ) {
             const inventory_entry &highlighted = get_active_column().get_highlighted();
             if( highlighted && highlighted.is_selectable() ) {
                 return { highlighted.any_item(), static_cast<int>( highlighted.chosen_count ) };
             }
         } else if( input.action == "INCREASE_COUNT" ) {
             inventory_entry &highlighted = get_active_column().get_highlighted();
             mod_chosen_count( highlighted, 1 );
         } else if( input.action == "DECREASE_COUNT" ) {
             inventory_entry &highlighted = get_active_column().get_highlighted();
             mod_chosen_count( highlighted, -1 );
         } else {
             on_input( input );
         }
     }
 }
References inventory_input::action, inventory_entry::any_item(), inventory_entry::chosen_count, inventory_selector::create_or_get_ui_adaptor(), anonymous_namespace{inventory_ui.cpp}::debug_print_timer(), inventory_input::entry, inventory_selector::get_active_column(), inventory_column::get_highlighted(), inventory_selector::get_input(), inventory_selector::highlight(), inventory_entry::is_selectable(), mod_chosen_count(), inventory_selector::on_input(), ui_manager::redraw(), and anonymous_namespace{inventory_ui.cpp}::tp_start.
Referenced by game_menus::inv::select_ammo().
mod_chosen_count()
void ammo_inventory_selector::mod_chosen_count (inventory_entry & entry, int val) private
Definition at line 3399 of file inventory_ui.cpp.
 {
     if( !entry.any_item()->is_ammo() ) {
         return;
     }
     for( const item_location &loc : get_possible_reload_targets( reload_loc ) ) {
         if( loc->can_reload_with( *entry.any_item(), true ) ) {
             item::reload_option tmp_opt( &u, loc, entry.any_item() );
             tmp_opt.qty( entry.chosen_count + value );
             entry.chosen_count = tmp_opt.qty();
             break;
         }
     }
     entry.make_entry_cell_cache( preset );
     on_change( entry );
 }
References inventory_entry::any_item(), inventory_entry::chosen_count, get_possible_reload_targets(), item::is_ammo(), inventory_entry::make_entry_cell_cache(), inventory_selector::on_change(), inventory_selector::preset, item::reload_option::qty(), reload_loc, and inventory_selector::u.
Referenced by execute().
set_all_entries_chosen_count()
void ammo_inventory_selector::set_all_entries_chosen_count ()
Definition at line 3378 of file inventory_ui.cpp.
 {
     for( inventory_column *col : columns ) {
         for( inventory_entry *entry : col->get_entries( return_item, true ) ) {
             for( const item_location &loc : get_possible_reload_targets( reload_loc ) ) {
                 item_location it = entry->any_item();
                 if( loc->can_reload_with( *it, true ) ) {
                     item::reload_option tmp_opt( &u, loc, it );
                     int count = entry->get_available_count();
                     if( it->has_flag( flag_SPEEDLOADER ) || it->has_flag( flag_SPEEDLOADER_CLIP ) ) {
                         count = it->ammo_remaining();
                     }
                     tmp_opt.qty( count );
                     entry->chosen_count = tmp_opt.qty();
                     break;
                 }
             }
         }
     }
 }
References item::ammo_remaining(), inventory_selector::columns, flag_SPEEDLOADER, flag_SPEEDLOADER_CLIP, get_possible_reload_targets(), item::has_flag(), item::reload_option::qty(), reload_loc, anonymous_namespace{inventory_ui.cpp}::return_item(), and inventory_selector::u.
Referenced by game_menus::inv::select_ammo().
Member Data Documentation
reload_loc
const item_location ammo_inventory_selector::reload_loc private
Definition at line 958 of file inventory_ui.h.
Referenced by mod_chosen_count(), and set_all_entries_chosen_count().
The documentation for this class was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp