Cataclysm DDA: appliance_convert_examine_actor Class Reference
appliance_convert_examine_actor Class Reference
#include <iexamine_actors.h>
Public Member Functions
appliance_convert_examine_actor (const std::string &type="appliance_convert")
void load (const JsonObject &jo) override
void call (Character &you, const tripoint &examp) const override
void finalize () const override
std::unique_ptr< iexamine_actor > clone () const override
Public Member Functions inherited from iexamine_actor
iexamine_actor (const std::string &type)
virtual ~iexamine_actor ()=default
Private Attributes
std::optional< furn_str_id > furn_set = std::nullopt
std::optional< ter_str_id > ter_set = std::nullopt
itype_id appliance_item
Additional Inherited Members
Public Attributes inherited from iexamine_actor
const std::string type
Detailed Description
Definition at line 12 of file iexamine_actors.h.
Constructor & Destructor Documentation
appliance_convert_examine_actor()
appliance_convert_examine_actor::appliance_convert_examine_actor (const std::string & type = "appliance_convert") inline explicit
Definition at line 20 of file iexamine_actors.h.
             : iexamine_actor( type ) {}
Member Function Documentation
call()
void appliance_convert_examine_actor::call (Character & you, const tripoint & examp) const override virtual
Implements iexamine_actor.
Definition at line 26 of file iexamine_actors.cpp.
 {
     if( !query_yn( _( "Connect %s to grid?" ), item::nname( appliance_item ) ) ) {
         return;
     }
     map &here = get_map();
     if( furn_set ) {
         here.furn_set( examp, *furn_set );
     }
     if( ter_set ) {
         here.ter_set( examp, *ter_set );
     }
     place_appliance( examp, vpart_appliance_from_item( appliance_item ) );
 }
References _, appliance_item, furn_set, map::furn_set(), get_map(), item::nname(), place_appliance(), query_yn(), ter_set, map::ter_set(), and vpart_appliance_from_item().
clone()
std::unique_ptr< iexamine_actor > appliance_convert_examine_actor::clone () const override virtual
Implements iexamine_actor.
Definition at line 60 of file iexamine_actors.cpp.
 {
     return std::make_unique<appliance_convert_examine_actor>( *this );
 }
finalize()
void appliance_convert_examine_actor::finalize () const override virtual
Implements iexamine_actor.
Definition at line 42 of file iexamine_actors.cpp.
 {
     if( furn_set && !furn_set->is_valid() ) {
         debugmsg( "Invalid furniture id %s in appliance_convert action", furn_set->str() );
     }
     if( ter_set && !ter_set->is_valid() ) {
         debugmsg( "Invalid terrain id %s in appliance_convert action", ter_set->str() );
     }
     if( !appliance_item.is_valid() ) {
         debugmsg( "Invalid appliance item %s in appliance_convert action", appliance_item.str() );
     } else if( !vpart_appliance_from_item( appliance_item ).is_valid() ) {
         // This will never actually trigger now, but is here if the semantics of vpart_appliance_from_item change
         debugmsg( "In appliance_convert action, %s does not correspond to an appliance",
                   appliance_item.str() );
     }
 }
References appliance_item, debugmsg, furn_set, string_id< T >::is_valid(), string_id< T >::str(), ter_set, and vpart_appliance_from_item().
load()
void appliance_convert_examine_actor::load (const JsonObject & jo) override virtual
Implements iexamine_actor.
Definition at line 19 of file iexamine_actors.cpp.
 {
     optional( jo, false, "furn_set", furn_set );
     optional( jo, false, "ter_set", ter_set );
     mandatory( jo, false, "item", appliance_item );
 }
References appliance_item, furn_set, mandatory, optional(), and ter_set.
Member Data Documentation
appliance_item
itype_id appliance_convert_examine_actor::appliance_item private
Definition at line 17 of file iexamine_actors.h.
Referenced by call(), finalize(), and load().
furn_set
std::optional<furn_str_id> appliance_convert_examine_actor::furn_set = std::nullopt private
Definition at line 15 of file iexamine_actors.h.
Referenced by call(), finalize(), and load().
ter_set
std::optional<ter_str_id> appliance_convert_examine_actor::ter_set = std::nullopt private
Definition at line 16 of file iexamine_actors.h.
Referenced by call(), finalize(), and load().
The documentation for this class was generated from the following files:
src/iexamine_actors.h
src/iexamine_actors.cpp