Cataclysm DDA: jmapgen_npc Class Reference
jmapgen_npc Class Reference
Place an NPC.
Public Member Functions
jmapgen_npc (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
mapgen_value< string_id< npc_template > > npc_class
bool target
std::vector< trait_id > traits
std::string unique_id
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place an NPC.
"class": the npc class, see map::place_npc
Definition at line 1870 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_npc()
jmapgen_npc::jmapgen_npc (const JsonObject & jsi, const std::string_view) inline
Definition at line 1877 of file mapgen.cpp.
                                                                     :
             npc_class( jsi.get_member( "class" ) )
             , target( jsi.get_bool( "target", false ) ) {
             if( jsi.has_string( "add_trait" ) ) {
                 traits.emplace_back();
                 jsi.read( "add_trait", traits.back() );
             } else if( jsi.has_array( "add_trait" ) ) {
                 jsi.read( "add_trait", traits );
             }
             if( jsi.has_string( "unique_id" ) ) {
                 jsi.read( "unique_id", unique_id );
             }
         }
References JsonObject::has_array(), JsonObject::has_string(), mapgen_defer::jsi, JsonObject::read(), traits, and unique_id.
Member Function Documentation
apply()
void jmapgen_npc::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 1890 of file mapgen.cpp.
{
             string_id<npc_template> chosen_id = npc_class.get( dat );
             if( chosen_id.is_null() ) {
                 return;
             }
             if( !unique_id.empty() && g->unique_npc_exists( unique_id ) ) {
                 add_msg_debug( debugmode::DF_NPC, "NPC with unique id %s already exists.", unique_id );
                 return;
             }
             tripoint const dst( x.get(), y.get(), z.get() );
             // TODO: Make place_npc 3D aware.
             character_id npc_id = dat.m.place_npc( dst.xy(), chosen_id );
             if( get_map().inbounds( dat.m.getglobal( dst ) ) ) {
                 dat.m.queue_main_cleanup();
             }
             if( dat.mission() && target ) {
                 dat.mission()->set_target_npc_id( npc_id );
             }
             npc *p = g->find_npc( npc_id );
             if( p != nullptr ) {
                 for( const trait_id &new_trait : traits ) {
                     p->set_mutation( new_trait );
                 }
                 if( !unique_id.empty() ) {
                     p->set_unique_id( unique_id );
                 }
             }
         }
References add_msg_debug, debugmode::DF_NPC, g, jmapgen_int::get(), get_map(), map::getglobal(), string_id< T >::is_null(), mapgendata::m, mapgendata::mission(), map::place_npc(), map::queue_main_cleanup(), Character::set_mutation(), mission::set_target_npc_id(), npc::set_unique_id(), target, traits, unique_id, and tripoint::xy().
check()
void jmapgen_npc::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 1920 of file mapgen.cpp.
{
             npc_class.check( oter_name, parameters );
         }
Member Data Documentation
npc_class
mapgen_value<string_id<npc_template> > jmapgen_npc::npc_class
Definition at line 1873 of file mapgen.cpp.
target
bool jmapgen_npc::target
Definition at line 1874 of file mapgen.cpp.
Referenced by apply().
traits
std::vector<trait_id> jmapgen_npc::traits
Definition at line 1875 of file mapgen.cpp.
Referenced by apply(), and jmapgen_npc().
unique_id
std::string jmapgen_npc::unique_id
Definition at line 1876 of file mapgen.cpp.
Referenced by apply(), and jmapgen_npc().
The documentation for this class was generated from the following file:
src/mapgen.cpp