Cataclysm DDA: mapgen_basic_container Class Reference
mapgen_basic_container Class Reference
Public Member Functions
int add (const std::shared_ptr< mapgen_function > &ptr)
bool generate (mapgendata &dat, const int hardcoded_weight)
Pick a mapgen function randomly and call its generate function.
void setup ()
Calls mapgen_function::setup and sets up the internal weighted list using the current value of mapgen_function::weight.
void finalize_parameters ()
void check_consistency () const
void check_consistency_with (const oter_t &ter) const
mapgen_parameters get_mapgen_params (mapgen_parameter_scope scope, const std::string &context) const
Private Attributes
std::vector< std::shared_ptr< mapgen_function > > mapgens_
std::vector< std::shared_ptr< mapgen_function > > mapgens_to_recalc_
weighted_int_list< std::shared_ptr< mapgen_function > > weights_
Detailed Description
Definition at line 334 of file mapgen.cpp.
Member Function Documentation
add()
int mapgen_basic_container::add (const std::shared_ptr< mapgen_function > & ptr) inline
Definition at line 343 of file mapgen.cpp.
{
             cata_assert( ptr );
             if( std::find( mapgens_.begin(), mapgens_.end(), ptr ) != mapgens_.end() ) {
                 debugmsg( "Adding duplicate mapgen to container!" );
             }
             mapgens_.push_back( ptr );
             return mapgens_.size() - 1;
         }
References cata_assert, debugmsg, and mapgens_.
check_consistency()
void mapgen_basic_container::check_consistency () const inline
Definition at line 411 of file mapgen.cpp.
{
             for( const auto &mapgen_function_ptr : weights_ ) {
                 mapgen_function_ptr.obj->check();
             }
         }
References weights_.
check_consistency_with()
void mapgen_basic_container::check_consistency_with (const oter_t & ter) const inline
Definition at line 416 of file mapgen.cpp.
{
             for( const auto &mapgen_function_ptr : weights_ ) {
                 mapgen_function_ptr.obj->check_consistent_with( ter );
             }
         }
References weights_.
finalize_parameters()
void mapgen_basic_container::finalize_parameters () inline
Definition at line 406 of file mapgen.cpp.
{
             for( auto &mapgen_function_ptr : weights_ ) {
                 mapgen_function_ptr.obj->finalize_parameters();
             }
         }
References weights_.
generate()
bool mapgen_basic_container::generate (mapgendata & dat, const int hardcoded_weight) inline
Pick a mapgen function randomly and call its generate function.
This basically runs the mapgen functions with the given mapgendata as argument.
Returns
Whether the mapgen function has been run. It may not get run if the list of mapgen functions is effectively empty. hardcoded_weight Weight for an additional entry. If that entry is chosen, false is returned. If unsure, just use 0 for it.
Definition at line 360 of file mapgen.cpp.
{
             for( const std::shared_ptr<mapgen_function> &ptr : mapgens_to_recalc_ ) {
                 dialogue d( get_talker_for( get_avatar() ), std::make_unique<talker>() );
                 int const weight = ptr->weight.evaluate( d );
                 if( weight >= 1 ) {
                     weights_.add_or_replace( ptr, weight );
                 } else {
                     weights_.remove( ptr );
                 }
             }
             if( hardcoded_weight > 0 &&
                 rng( 1, weights_.get_weight() + hardcoded_weight ) > weights_.get_weight() ) {
                 return false;
             }
             const std::shared_ptr<mapgen_function> *const ptr = weights_.pick();
             if( !ptr ) {
                 return false;
             }
             cata_assert( *ptr );
             ( *ptr )->generate( dat );
             return true;
         }
References weighted_list< W, T >::add_or_replace(), cata_assert, get_avatar(), get_talker_for(), weighted_list< W, T >::get_weight(), mapgens_to_recalc_, weighted_list< W, T >::pick(), weighted_list< W, T >::remove(), rng(), and weights_.
get_mapgen_params()
mapgen_parameters mapgen_basic_container::get_mapgen_params (mapgen_parameter_scope scope, const std::string & context) const inline
Definition at line 422 of file mapgen.cpp.
{
             mapgen_parameters result;
             for( const weighted_object<int, std::shared_ptr<mapgen_function>> &p : weights_ ) {
                 result.check_and_merge( p.obj->get_mapgen_params( scope ), context );
             }
             return result;
         }
References mapgen_parameters::check_and_merge(), context, and weights_.
setup()
void mapgen_basic_container::setup () inline
Calls mapgen_function::setup and sets up the internal weighted list using the current value of mapgen_function::weight.
This value may have changed since it was first added, so this is needed to recalculate the weighted list.
Definition at line 388 of file mapgen.cpp.
                      {
             for( const std::shared_ptr<mapgen_function> &ptr : mapgens_ ) {
                 cata_assert( ptr->weight );
                 if( ptr->weight.is_constant() ) {
                     int const weight = ptr->weight.constant();
                     if( weight < 1 ) {
                         continue; // rejected!
                     }
                     weights_.add( ptr, weight );
                 } else {
                     mapgens_to_recalc_.push_back( ptr );
                 }
                 ptr->setup();
             }
             // Not needed anymore, pointers are now stored in weights_ (or not used at all)
             mapgens_.clear();
         }
References weighted_list< W, T >::add(), cata_assert, mapgens_, mapgens_to_recalc_, and weights_.
Member Data Documentation
mapgens_
std::vector<std::shared_ptr<mapgen_function> > mapgen_basic_container::mapgens_ private
Definition at line 337 of file mapgen.cpp.
Referenced by add(), and setup().
mapgens_to_recalc_
std::vector<std::shared_ptr<mapgen_function> > mapgen_basic_container::mapgens_to_recalc_ private
Definition at line 339 of file mapgen.cpp.
Referenced by generate(), and setup().
weights_
weighted_int_list<std::shared_ptr<mapgen_function> > mapgen_basic_container::weights_ private
Definition at line 340 of file mapgen.cpp.
Referenced by check_consistency(), check_consistency_with(), finalize_parameters(), generate(), get_mapgen_params(), and setup().
The documentation for this class was generated from the following file:
src/mapgen.cpp