Cataclysm DDA: cata::string_formatter Class Reference
cata::string_formatter Class Reference
Type-safe and undefined-behavior free wrapper over sprintf.
#include <string_formatter.h>
Public Member Functions
string_formatter (std::string_view format)
template<typename ... Args>
void parse (Args &&... args)
Does the actual sprintf.
std::string get_output () const
Static Public Member Functions
static std::string raw_string_format (const char *format,...) PRINTF_LIKE(1
Wrapper for calling vsprintf - see there for documentation.
Private Member Functions
char consume_next_input ()
Return the next character from format and increment current_index_in_format.
char get_current_input () const
Returns (like consume_next_input) the next character from format, but does not change current_index_in_format.
bool consume_next_input_if (char c)
If the next character to read from format is the given character, consume it (like consume_next_input) and return true.
bool has_digit () const
Return whether get_current_input has a decimal digit ('0'...'9').
int parse_integer ()
Consume decimal digits, interpret them as integer and return it.
void read_flags ()
Read and consume format flag characters and append them to current_format.
std::optional< int > read_width ()
Read and forward to current_format any width specifier from format.
std::optional< int > read_precision ()
See read_width. This does the same, but for the precision specifier.
std::optional< int > read_argument_index ()
Read and return the index of the printf-argument that is to be formatted.
std::optional< int > read_number_or_argument_index ()
void throw_error (std::string_view msg) const
Throws an exception containing the given message and the format.
void add_long_long_length_modifier ()
template<typename ... Args>
void read_conversion (const int format_arg_index, Args &&... args)
template<typename T >
void do_formatting (T &&value)
template<typename RT , unsigned int current_index>
RT get_nth_arg_as (const unsigned int requested) const
Extracts a printf argument from the argument list and converts it to the requested type.
template<typename RT , unsigned int current_index, typename T , typename ... Args>
RT get_nth_arg_as (const unsigned int requested, T &&head, Args &&... args) const
Private Attributes
const std::string_view format
Complete format string, including all format specifiers (the string passed to printf).
size_t current_index_in_format = 0
Used during parsing to denote the next character in format to be parsed.
std::string output
The formatted output string, filled during parsing of format, so it's only valid after the parsing has completed.
std::string current_format
The *currently parsed format specifiers.
int current_argument_index = 0
The index (not number) of the next argument to be formatted via current_format.
std::string temp_buffer
Friends
void throw_error (const string_formatter &sf, std::string_view msg)
const char * string_formatter_set_temp_buffer (const string_formatter &sf, std::string &&text)
Stores the given text in temp_buffer and returns c_str() of it.
Detailed Description
Type-safe and undefined-behavior free wrapper over sprintf.
See string_format for usage. Basically it extracts the format specifiers and calls sprintf for each one separately and with proper conversion of the input type. For example printf("%f", 7) would yield undefined behavior as "%f" requires a double as argument. This class detects the format specifier and converts the input to double before calling sprintf. Similar for printf("%d", "foo") (yields UB again), but this class will just throw an exception.
Definition at line 172 of file string_formatter.h.
Constructor & Destructor Documentation
string_formatter()
cata::string_formatter::string_formatter (std::string_view format) inline explicit
Parameters
format The format string as required by sprintf.
Definition at line 323 of file string_formatter.h.
 : format( format ) { }
Member Function Documentation
add_long_long_length_modifier()
void cata::string_formatter::add_long_long_length_modifier () private
Definition at line 121 of file string_formatter.cpp.
 {
     const char *modifier;
 #if !defined(__USE_MINGW_ANSI_STDIO) && (defined(__MINGW32__) || defined(__MINGW64__))
     // mingw does not support '%llu' normally (it does with __USE_MINGW_ANSI_STDIO)
     // instead one has to use '%I64u'/'I32u'
     if( sizeof( signed long long int ) == 4 ) {
         modifier = "I32";
     } else {
         static_assert( sizeof( signed long long int ) == 8,
                        "unexpected size of long long, format specifier 'I64' does not work" );
         modifier = "I64";
     }
 #else
     modifier = "ll";
 #endif
     current_format.insert( current_format.size() - 1, modifier );
 }
Referenced by read_conversion().
consume_next_input()
char cata::string_formatter::consume_next_input () private
Return the next character from format and increment current_index_in_format.
Returns a null-character when the end of the format has been reached (and does not change current_index_in_format).
Definition at line 9 of file string_formatter.cpp.
 {
     return current_index_in_format < format.size() ? format[current_index_in_format++] : '\0';
 }
References current_index_in_format, and format.
Referenced by parse(), and read_conversion().
consume_next_input_if()
bool cata::string_formatter::consume_next_input_if (char c) private
If the next character to read from format is the given character, consume it (like consume_next_input) and return true.
Otherwise don't do anything at all and return false.
Definition at line 19 of file string_formatter.cpp.
 {
     if( c == get_current_input() ) {
         consume_next_input();
         return true;
     } else {
         return false;
     }
 }
References c.
Referenced by parse(), and read_conversion().
do_formatting()
template<typename T > void cata::string_formatter::do_formatting (T && value) inline private
Definition at line 317 of file string_formatter.h.
{
             output.append( raw_string_format( current_format.c_str(), value ) );
         }
References current_format, output, and raw_string_format().
Referenced by read_conversion().
get_current_input()
char cata::string_formatter::get_current_input () const private
Returns (like consume_next_input) the next character from format, but does not change current_index_in_format.
Definition at line 14 of file string_formatter.cpp.
 {
     return current_index_in_format < format.size() ? format[current_index_in_format] : '\0';
 }
get_nth_arg_as() [1/2]
template<typename RT , unsigned int current_index> RT cata::string_formatter::get_nth_arg_as (const unsigned int requested) const inline private
Extracts a printf argument from the argument list and converts it to the requested type.
Template Parameters
RT The type that the argument should be converted to.
current_index The index of the first of the supplied arguments.
Exceptions
If there is no argument with the given index, or if the argument can not be converted to the requested type (via convert).
Definition at line 246 of file string_formatter.h.
{
             throw_error( "Requested argument " + std::to_string( requested ) + " but input has only " +
                          std::to_string( current_index ) );
         }
References throw_error(), and to_string().
get_nth_arg_as() [2/2]
template<typename RT , unsigned int current_index, typename T , typename ... Args> RT cata::string_formatter::get_nth_arg_as (const unsigned int requested, T && head, Args &&... args) const inline private
Definition at line 251 of file string_formatter.h.
{
             if( requested > current_index ) {
                 return get_nth_arg_as < RT, current_index + 1 > ( requested, std::forward<Args>( args )... );
             } else {
                 return convert( static_cast<RT *>( nullptr ), *this, std::forward<T>( head ), 0 );
             }
         }
References cata::convert().
get_output()
std::string cata::string_formatter::get_output () const inline
Definition at line 361 of file string_formatter.h.
{
             return output;
         }
References output.
Referenced by string_format().
has_digit()
bool cata::string_formatter::has_digit () const private
Return whether get_current_input has a decimal digit ('0'...'9').
Definition at line 37 of file string_formatter.cpp.
 {
     const char c = get_current_input();
     return c >= '0' && c <= '9';
 }
References c.
parse()
template<typename ... Args> void cata::string_formatter::parse (Args &&... args) inline
Does the actual sprintf.
It uses format and puts the formatted string into output. Note: use get_output to get the formatted string after a successful call to this function.
Exceptions
Exceptions when the arguments do not match the format specifiers, see get_nth_arg_as, or when the format is invalid for whatever reason. Note: string_format is a wrapper that handles those exceptions.
Definition at line 332 of file string_formatter.h.
{
             output.reserve( format.size() );
             output.resize( 0 );
             current_index_in_format = 0;
             current_argument_index = 0;
             while( const char c = consume_next_input() ) {
                 if( c != '%' ) {
                     output.push_back( c );
                     continue;
                 }
                 if( consume_next_input_if( '%' ) ) {
                     output.push_back( '%' );
                     continue;
                 }
                 current_format = "%";
                 const std::optional<int> format_arg_index = read_argument_index();
                 read_flags();
                 if( const std::optional<int> width_argument_index = read_width() ) {
                     const int w = get_nth_arg_as<int, 0>( *width_argument_index, std::forward<Args>( args )... );
                     current_format += std::to_string( w );
                 }
                 if( const std::optional<int> precision_argument_index = read_precision() ) {
                     const int p = get_nth_arg_as<int, 0>( *precision_argument_index, std::forward<Args>( args )... );
                     current_format += std::to_string( p );
                 }
                 const int arg = format_arg_index ? *format_arg_index : current_argument_index++;
                 read_conversion( arg, std::forward<Args>( args )... );
             }
         }
References c, consume_next_input(), consume_next_input_if(), current_argument_index, current_format, current_index_in_format, format, output, read_argument_index(), read_conversion(), read_flags(), read_precision(), read_width(), and to_string().
Referenced by string_format().
parse_integer()
int cata::string_formatter::parse_integer () private
Consume decimal digits, interpret them as integer and return it.
A starting '0' is allowed. Leaves format at the first non-digit character (or the end). Returns 0 if the first character is not a digit.
Definition at line 63 of file string_formatter.cpp.
 {
     int result = 0;
     while( has_digit() ) {
         // TODO: Check for overflow
         result = result * 10 + ( consume_next_input() - '0' );
     }
     return result;
 }
raw_string_format()
std::string cata::string_formatter::raw_string_format (const char * format, ...) static
Wrapper for calling vsprintf - see there for documentation.
Try to avoid it as it's not type safe and may easily lead to undefined behavior - use string_format instead.
Exceptions
std::exception if the format is invalid / does not match the arguments, but that's not guaranteed - technically it's undefined behavior.
Definition at line 2427 of file output.cpp.
 {
 #if defined(_WIN32)
     // For unknown reason, vsnprintf on Windows does not seem to support positional arguments (e.g. "%1$s")
     va_list args;
     va_start( args, format );
     va_list args_copy_1;
     va_copy( args_copy_1, args );
     // Return value of _vscprintf_p does not include the '\0' terminator
     const int characters = _vscprintf_p( format, args_copy_1 ) + 1;
     va_end( args_copy_1 );
     std::vector<char> buffer( characters, '\0' );
     va_list args_copy_2;
     va_copy( args_copy_2, args );
     _vsprintf_p( &buffer[0], characters, format, args_copy_2 );
     va_end( args_copy_2 );
     va_end( args );
     return std::string( &buffer[0] );
 #else
     va_list args;
     va_start( args, format );
     errno = 0; // Clear errno before trying
     std::vector<char> buffer( 1024, '\0' );
 #if defined(__CYGWIN__)
     std::string rewritten_format = rewrite_vsnprintf( format );
     format = rewritten_format.c_str();
 #endif
     for( ;; ) {
         const size_t buffer_size = buffer.size();
         va_list args_copy;
         va_copy( args_copy, args );
         const int result = vsnprintf( buffer.data(), buffer_size, format, args_copy );
         va_end( args_copy );
         // No error, and the buffer is big enough; we're done.
         if( result >= 0 && static_cast<size_t>( result ) < buffer_size ) {
             break;
         }
         // Standards conformant versions return -1 on error only.
         // Some non-standard versions return -1 to indicate a bigger buffer is needed.
         // Some of the latter set errno to ERANGE at the same time.
         if( result < 0 && errno && errno != ERANGE ) {
             throw std::runtime_error( "Bad format string for printf: \"" + std::string( format ) + "\"" );
         }
         // Looks like we need to grow... bigger, definitely bigger.
         buffer.resize( buffer_size * 2 );
     }
     va_end( args );
     return std::string( buffer.data() );
 #endif
 }
References rewrite_vsnprintf().
Referenced by do_formatting().
read_argument_index()
std::optional< int > cata::string_formatter::read_argument_index () private
Read and return the index of the printf-argument that is to be formatted.
Returns nothing if format does not refer to a specific index (caller should use current_argument_index).
Definition at line 43 of file string_formatter.cpp.
 {
     const char c = get_current_input();
     // can't use has_digit because '0' is not allowed as first character
     if( c >= '1' && c <= '9' ) {
         const size_t pos = format.find_first_not_of( "012345678", current_index_in_format + 1 );
         if( pos == std::string::npos || format[pos] != '$' ) {
             return std::nullopt;
         }
         const int result = parse_integer() - 1; // arguments are 1-based
         // We already know this is true because of the `find_first_not_of` check above.
         const bool had_next = consume_next_input_if( '$' );
         ( void ) had_next;
         cata_assert( had_next );
         return result;
     } else {
         return std::nullopt;
     }
 }
References c, cata_assert, and math_opers::pos().
Referenced by parse().
read_conversion()
template<typename ... Args> void cata::string_formatter::read_conversion (const int format_arg_index, Args &&... args) inline private
Definition at line 263 of file string_formatter.h.
{
             // Removes the prefix "ll", "l", "h" and "hh", "z", and "t".
             // We later add "ll" again and that
             // would interfere with the existing prefix. We convert *all* input to (un)signed
             // long long int and use the "ll" modifier all the time. This will print the
             // expected value all the time, even when the original modifier did not match.
             if( consume_next_input_if( 'l' ) ) {
                 consume_next_input_if( 'l' );
             } else if( consume_next_input_if( 'h' ) ) {
                 consume_next_input_if( 'h' );
             } else if( consume_next_input_if( 'z' ) ) { // NOLINT(bugprone-branch-clone)
                 // done with it
             } else if( consume_next_input_if( 't' ) ) {
                 // done with it
             }
             const char c = consume_next_input();
             current_format.push_back( c );
             switch( c ) {
                 case 'c':
                     return do_formatting( get_nth_arg_as<int, 0>( format_arg_index, std::forward<Args>( args )... ) );
                 case 'd':
                 case 'i':
                     add_long_long_length_modifier();
                     return do_formatting( get_nth_arg_as<signed long long int, 0>( format_arg_index,
                                           std::forward<Args>( args )... ) );
                 case 'o':
                 case 'u':
                 case 'x':
                 case 'X':
                     add_long_long_length_modifier();
                     return do_formatting( get_nth_arg_as<unsigned long long int, 0>( format_arg_index,
                                           std::forward<Args>( args )... ) );
                 case 'a':
                 case 'A':
                 case 'g':
                 case 'G':
                 case 'f':
                 case 'F':
                 case 'e':
                 case 'E':
                     return do_formatting( get_nth_arg_as<double, 0>( format_arg_index,
                                           std::forward<Args>( args )... ) );
                 case 'p':
                     return do_formatting( get_nth_arg_as<void *, 0>( format_arg_index,
                                           std::forward<Args>( args )... ) );
                 case 's':
                     return do_formatting( get_nth_arg_as<const char *, 0>( format_arg_index,
                                           std::forward<Args>( args )... ) );
                 default:
                     throw_error( "Unsupported format conversion: " + std::string( 1, c ) );
             }
         }
References add_long_long_length_modifier(), c, consume_next_input(), consume_next_input_if(), current_format, do_formatting(), and throw_error().
Referenced by parse().
read_flags()
void cata::string_formatter::read_flags () private
Read and consume format flag characters and append them to current_format.
Leaves format at the first character that is not a flag (or the end).
Definition at line 29 of file string_formatter.cpp.
 {
     static const std::string flag_characters( "#0 +'I-" );
     while( flag_characters.find( get_current_input() ) != std::string::npos ) {
         current_format.push_back( consume_next_input() );
     }
 }
Referenced by parse().
read_number_or_argument_index()
std::optional< int > cata::string_formatter::read_number_or_argument_index () private
Definition at line 73 of file string_formatter.cpp.
 {
     if( consume_next_input_if( '*' ) ) {
         if( !has_digit() ) {
             return current_argument_index++;
         }
         const int index = parse_integer() - 1; // format specifiers are 1-based
         if( !consume_next_input_if( '$' ) ) {
             throw_error( "expected '$' after field precision" );
         }
         return index;
     }
     while( has_digit() ) {
         current_format.push_back( consume_next_input() );
     }
     return std::nullopt;
 }
References cata::throw_error().
read_precision()
std::optional< int > cata::string_formatter::read_precision () private
See read_width. This does the same, but for the precision specifier.
Definition at line 96 of file string_formatter.cpp.
 {
     if( !consume_next_input_if( '.' ) ) {
         return std::nullopt;
     }
     current_format.push_back( '.' );
     return read_number_or_argument_index();
 }
Referenced by parse().
read_width()
std::optional< int > cata::string_formatter::read_width () private
Read and forward to current_format any width specifier from format.
Returns nothing if the width is not specified or if it is specified as fixed number, otherwise returns the index of the printf-argument to be used for the width.
Definition at line 91 of file string_formatter.cpp.
 {
     return read_number_or_argument_index();
 }
Referenced by parse().
throw_error()
void cata::string_formatter::throw_error (std::string_view msg) const private
Throws an exception containing the given message and the format.
Definition at line 105 of file string_formatter.cpp.
 {
     throw std::runtime_error(
         str_cat( msg, " at: \"", format.substr( 0, current_index_in_format ), "|",
                  format.substr( current_index_in_format ), "\"" ) );
 }
References str_cat().
Referenced by get_nth_arg_as(), and read_conversion().
Friends And Related Function Documentation
string_formatter_set_temp_buffer
const char* string_formatter_set_temp_buffer (const string_formatter & sf, std::string && text) friend
Stores the given text in temp_buffer and returns c_str() of it.
This is used for printing non-strings through "%s". It only works because this prints each format specifier separately, so the content of temp_buffer is only used once.
Definition at line 232 of file string_formatter.h.
{
             sf.temp_buffer = std::move( text );
             return sf.temp_buffer.c_str();
         }
throw_error
void throw_error (const string_formatter & sf, std::string_view msg) friend
Definition at line 225 of file string_formatter.h.
{
             sf.throw_error( msg );
         }
Member Data Documentation
current_argument_index
int cata::string_formatter::current_argument_index = 0 private
The index (not number) of the next argument to be formatted via current_format.
Definition at line 189 of file string_formatter.h.
Referenced by parse().
current_format
std::string cata::string_formatter::current_format private
The *currently parsed format specifiers.
This is extracted from format during parsing and given to sprintf (along with the actual argument). It is filled and reset during parsing for each format specifier in format.
Definition at line 187 of file string_formatter.h.
Referenced by do_formatting(), parse(), and read_conversion().
current_index_in_format
size_t cata::string_formatter::current_index_in_format = 0 private
Used during parsing to denote the next character in format to be parsed.
Definition at line 180 of file string_formatter.h.
Referenced by consume_next_input(), and parse().
format
const std::string_view cata::string_formatter::format private
Complete format string, including all format specifiers (the string passed to printf).
Definition at line 177 of file string_formatter.h.
Referenced by consume_next_input(), and parse().
output
std::string cata::string_formatter::output private
The formatted output string, filled during parsing of format, so it's only valid after the parsing has completed.
Definition at line 183 of file string_formatter.h.
Referenced by do_formatting(), get_output(), and parse().
temp_buffer
std::string cata::string_formatter::temp_buffer mutable private
Definition at line 228 of file string_formatter.h.
The documentation for this class was generated from the following files:
src/string_formatter.h
src/output.cpp
src/string_formatter.cpp