Cataclysm DDA: reveal_map_actor Class Reference
reveal_map_actor Class Reference
Reveals specific things on the overmap.
#include <iuse_actor.h>
Public Member Functions
void reveal_targets (const tripoint_abs_omt &center, const std::pair< std::string, ot_match_type > &target, int reveal_distance) const
reveal_map_actor (const std::string &type="reveal_map")
~reveal_map_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
int radius = 0
The radius of the overmap area that gets revealed.
std::vector< std::pair< std::string, ot_match_type > > omt_types
Overmap terrain types that get revealed.
translation message
The message displayed after revealing.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Reveals specific things on the overmap.
Definition at line 427 of file iuse_actor.h.
Constructor & Destructor Documentation
reveal_map_actor()
reveal_map_actor::reveal_map_actor (const std::string & type = "reveal_map") inline explicit
Definition at line 451 of file iuse_actor.h.
 : iuse_actor( type ) {}
~reveal_map_actor()
reveal_map_actor::~reveal_map_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > reveal_map_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 1188 of file iuse_actor.cpp.
 {
     return std::make_unique<reveal_map_actor>( *this );
 }
load()
void reveal_map_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 1193 of file iuse_actor.cpp.
 {
     radius = obj.get_int( "radius" );
     obj.get_member( "message" ).read( message );
     std::string ter;
     ot_match_type ter_match_type;
     for( const JsonValue entry : obj.get_array( "terrain" ) ) {
         if( entry.test_string() ) {
             ter = entry.get_string();
             ter_match_type = ot_match_type::contains;
         } else {
             JsonObject jo = entry.get_object();
             ter = jo.get_string( "om_terrain" );
             ter_match_type = jo.get_enum_value<ot_match_type>( "om_terrain_match_type",
                              ot_match_type::contains );
         }
         omt_types.emplace_back( ter, ter_match_type );
     }
 }
References contains, JsonObject::get_array(), JsonObject::get_enum_value(), JsonObject::get_int(), JsonObject::get_member(), JsonObject::get_object(), JsonObject::get_string(), message, omt_types, radius, and JsonValue::read().
reveal_targets()
void reveal_map_actor::reveal_targets (const tripoint_abs_omt & center, const std::pair< std::string, ot_match_type > & target, int reveal_distance) const
Definition at line 1213 of file iuse_actor.cpp.
 {
     const auto places = overmap_buffer.find_all( center, target.first, radius, false,
                         target.second );
     for( const tripoint_abs_omt &place : places ) {
         if( !overmap_buffer.seen( place ) ) {
             // Should be replaced with the character using the item passed as an argument if NPCs ever learn to use maps
             get_avatar().map_revealed_omts.emplace( place );
         }
         overmap_buffer.reveal( place, reveal_distance );
     }
 }
References center, overmapbuffer::find_all(), get_avatar(), Character::map_revealed_omts, overmap_buffer, radius, overmapbuffer::reveal(), and overmapbuffer::seen().
Referenced by use().
use()
std::optional< int > reveal_map_actor::use (Character * p, item & it, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 1228 of file iuse_actor.cpp.
 {
     if( it.already_used_by_player( *p ) ) {
         p->add_msg_if_player( _( "There isn't anything new on the %s." ), it.tname() );
         return std::nullopt;
     } else if( p->fine_detail_vision_mod() > 4 ) {
         p->add_msg_if_player( _( "It's too dark to read." ) );
         return std::nullopt;
     }
     const tripoint_abs_omt center( it.get_var( "reveal_map_center_omt",
                                    p->global_omt_location().raw() ) );
     // Clear highlight on previously revealed OMTs before revealing new ones
     p->map_revealed_omts.clear();
     for( const auto &omt : omt_types ) {
         for( int z = -OVERMAP_DEPTH; z <= OVERMAP_HEIGHT; z++ ) {
             reveal_targets( tripoint_abs_omt( center.xy(), z ), omt, 0 );
         }
     }
     if( !message.empty() ) {
         p->add_msg_if_player( m_good, "%s", message );
     }
     if( p->map_revealed_omts.empty() ) {
         p->add_msg_if_player( _( "You didn't learn anything new from the %s." ), it.tname() );
     }
     it.mark_as_used_by_player( *p );
     return 0;
 }
References _, Character::add_msg_if_player(), item::already_used_by_player(), center, translation::empty(), Character::fine_detail_vision_mod(), item::get_var(), Creature::global_omt_location(), m_good, Character::map_revealed_omts, item::mark_as_used_by_player(), message, omt, omt_types, OVERMAP_DEPTH, OVERMAP_HEIGHT, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), reveal_targets(), and item::tname().
Member Data Documentation
message
translation reveal_map_actor::message
The message displayed after revealing.
Definition at line 445 of file iuse_actor.h.
Referenced by load(), and use().
omt_types
std::vector<std::pair<std::string, ot_match_type> > reveal_map_actor::omt_types
Overmap terrain types that get revealed.
Definition at line 441 of file iuse_actor.h.
Referenced by load(), and use().
radius
int reveal_map_actor::radius = 0
The radius of the overmap area that gets revealed.
This is in overmap terrain coordinates. A radius of 1 means all terrains directly around center are revealed. The center is location of nearest city defined in reveal_map_center_omt variable of activated item (or current player global omt location if variable is not set).
Definition at line 437 of file iuse_actor.h.
Referenced by load(), and reveal_targets().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp