Cataclysm DDA: mood_face Class Reference
mood_face Class Reference
#include <mood_face.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
const mood_face_id & getId () const
const std::vector< mood_face_value > & values () const
Static Public Member Functions
static void load_mood_faces (const JsonObject &jo, const std::string &src)
static void reset ()
static const std::vector< mood_face > & get_all ()
Private Attributes
mood_face_id id
std::vector< std::pair< mood_face_id, mod_id > > src
bool was_loaded = false
std::vector< mood_face_value > values_
Friends
class generic_factory< mood_face >
struct mod_tracker
Detailed Description
Definition at line 15 of file mood_face.h.
Member Function Documentation
get_all()
const std::vector< mood_face > & mood_face::get_all () static
Definition at line 50 of file mood_face.cpp.
 {
     return mood_face_factory.get_all();
 }
References anonymous_namespace{mood_face.cpp}::mood_face_factory.
Referenced by avatar::character_mood_face().
getId()
const mood_face_id& mood_face::getId () const inline
Definition at line 25 of file mood_face.h.
{
             return id;
         }
References id.
Referenced by display::morale_emotion().
load()
void mood_face::load (const JsonObject & jo, std::string_view src)
Definition at line 41 of file mood_face.cpp.
 {
     mandatory( jo, was_loaded, "values", values_ );
     std::sort( values_.begin(), values_.end(),
     []( const mood_face_value & valueA, const mood_face_value & valueB ) {
         return valueA.value() > valueB.value();
     } );
 }
References mandatory, values_, and was_loaded.
load_mood_faces()
void mood_face::load_mood_faces (const JsonObject & jo, const std::string & src) static
Definition at line 31 of file mood_face.cpp.
 {
     mood_face_factory.load( jo, src );
 }
References anonymous_namespace{mood_face.cpp}::mood_face_factory, and src.
Referenced by DynamicDataLoader::initialize().
reset()
void mood_face::reset () static
Definition at line 36 of file mood_face.cpp.
 {
     mood_face_factory.reset();
 }
References anonymous_namespace{mood_face.cpp}::mood_face_factory.
Referenced by DynamicDataLoader::unload_data().
values()
const std::vector<mood_face_value>& mood_face::values () const inline
Definition at line 29 of file mood_face.h.
{
             return values_;
         }
Referenced by display::morale_emotion().
Friends And Related Function Documentation
generic_factory< mood_face >
friend class generic_factory< mood_face > friend
Definition at line 29 of file mood_face.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 35 of file mood_face.h.
Member Data Documentation
id
mood_face_id mood_face::id private
Definition at line 37 of file mood_face.h.
Referenced by getId().
src
std::vector<std::pair<mood_face_id, mod_id> > mood_face::src private
Definition at line 38 of file mood_face.h.
Referenced by load_mood_faces().
values_
std::vector<mood_face_value> mood_face::values_ private
Definition at line 42 of file mood_face.h.
Referenced by load().
was_loaded
bool mood_face::was_loaded = false private
Definition at line 39 of file mood_face.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/mood_face.h
src/mood_face.cpp