Cataclysm DDA: JsonArray Class Reference
JsonArray Class Reference
#include <flexbuffer_json.h>
Classes
class const_iterator
Public Member Functions
JsonArray ()
JsonArray (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath &&path)
JsonArray (const JsonArray &rhs)
JsonArray & operator= (const JsonArray &rhs)
JsonArray (JsonArray &&rhs) noexcept
JsonArray & operator= (JsonArray &&rhs) noexcept
const_iterator begin () const
const_iterator end () const
size_t size () const
bool empty () const
JsonValue operator[] (size_t idx) const
std::string get_string (size_t idx) const
int get_int (size_t idx) const
double get_float (size_t idx) const
JsonArray get_array (size_t idx) const
JsonObject get_object (size_t idx) const
bool has_string (size_t idx) const
bool has_bool (size_t idx) const
bool has_int (size_t idx) const
bool has_float (size_t idx) const
bool has_array (size_t idx) const
bool has_object (size_t idx) const
bool test_string () const
std::string next_string ()
bool test_bool () const
bool next_bool ()
bool test_int () const
int next_int ()
bool test_float () const
double next_float ()
bool test_array () const
JsonArray next_array ()
bool test_object () const
JsonObject next_object ()
JsonValue next_value ()
template<typename E , typename = std::enable_if_t<std::is_enum_v<E>>>
E next_enum_value ()
template<typename T , std::enable_if_t< !std::is_same_v< void, typename T::value_type > > * = nullptr>
auto read (T &v, bool throw_on_error=false) const -> decltype(v.front(), true)
template<typename T >
bool read_next (T &t, bool throw_on_error=false)
template<typename T >
bool read (size_t idx, T &t, bool throw_on_error=false) const
template<typename T = std::string, typename Res = std::set<T>>
Res get_tags (size_t idx) const
void string_error (size_t idx, int offset, const std::string &message) const
bool has_more () const
void throw_error (const std::string &message) const noexcept(false)
void throw_error (int offset, const std::string &message) const noexcept(false)
void throw_error_after (const std::string &message) const noexcept(false)
bool error_or_false (bool throw_on_error, const std::string &message) const noexcept(false)
Public Attributes
friend const_iterator
Private Member Functions
JsonValue get_next ()
void init (const flexbuffer &json, tiny_bitset *moved_visited_fields=nullptr) noexcept
void mark_visited (size_t idx) const
Private Member Functions inherited from JsonWithPath
void throw_error (const std::string &message) const noexcept(false)
void throw_error (int offset, const std::string &message) const noexcept(false)
void throw_error_after (const std::string &message) const noexcept(false)
JsonWithPath (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath &&path)
JsonWithPath (const JsonWithPath &)=default
JsonWithPath & operator= (const JsonWithPath &)=default
JsonWithPath (JsonWithPath &&) noexcept=default
JsonWithPath & operator= (JsonWithPath &&) noexcept=default
bool error_or_false (bool throw_on_error, const std::string &message) const noexcept(false)
Static Private Member Functions
static const auto & empty_array_ ()
Private Attributes
size_t size_ = 0
size_t next_ = 0
tiny_bitset visited_fields_bitset_
Private Attributes inherited from JsonWithPath
JsonPath path_
Detailed Description
Definition at line 346 of file flexbuffer_json.h.
Constructor & Destructor Documentation
JsonArray() [1/4]
JsonArray::JsonArray () inline
Definition at line 355 of file flexbuffer_json.h.
                     : JsonWithPath( empty_array_(),
                                         flexbuffer_root_from_storage( empty_array_()->get_storage() ), {} ) {
             init( json_ );
         }
JsonArray() [2/4]
JsonArray::JsonArray (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath && path) inline
Definition at line 360 of file flexbuffer_json.h.
             : JsonWithPath( std::move( root ), json, std::move( path ) ) {
             init( json_ );
         }
References init, and Json::json_.
JsonArray() [3/4]
JsonArray::JsonArray (const JsonArray & rhs) inline
Definition at line 368 of file flexbuffer_json.h.
                                           : JsonWithPath( rhs ) {
             init( json_ );
         }
References init, and Json::json_.
JsonArray() [4/4]
JsonArray::JsonArray (JsonArray && rhs) inline noexcept
Definition at line 378 of file flexbuffer_json.h.
                                               :
             JsonWithPath( std::move( static_cast<JsonWithPath &>( rhs ) ) ) {
             init( json_, &rhs.visited_fields_bitset_ );
             rhs.visited_fields_bitset_.set_all();
         }
References init, and Json::json_.
Member Function Documentation
begin()
auto JsonArray::begin () const inline
Definition at line 55 of file flexbuffer_json-inl.h.
 {
     return const_iterator( *this, 0 );
 }
References const_iterator.
empty()
bool JsonArray::empty () const inline
Definition at line 402 of file flexbuffer_json.h.
{
             return size() == 0;
         }
References om_direction::size.
Referenced by event_multiset::deserialize(), effect_type::extract_effect(), jmapgen_int::jmapgen_int(), recipe::load(), vpart_info::load(), Item_factory::load(), Item_factory::load_basic_info(), load_forest_mapgen_settings(), load_world_option(), parse_vp_control_reqs(), and parse_vp_reqs().
empty_array_()
static const auto& JsonArray::empty_array_ () inline static private
Definition at line 348 of file flexbuffer_json.h.
{
             // NOLINTNEXTLINE(cata-almost-never-auto)
             static auto empty_array = flexbuffer_cache::parse_buffer( "[]" );
             return empty_array;
         }
References flexbuffer_cache::parse_buffer().
end()
auto JsonArray::end () const inline
Definition at line 60 of file flexbuffer_json-inl.h.
 {
     return const_iterator( *this, size_ );
 }
References const_iterator, and size_.
error_or_false()
bool JsonWithPath::error_or_false inline noexcept
Definition at line 148 of file flexbuffer_json.h.
{
             if( throw_on_error ) {
                 throw_error( 0, message );
             }
             return false;
         }
Referenced by JsonValue::read().
get_array()
JsonArray JsonArray::get_array (size_t idx) const inline
Definition at line 648 of file flexbuffer_json-inl.h.
 {
     return ( *this )[ idx ];
 }
Referenced by event_multiset::deserialize(), mm_submap::deserialize(), mutation_branch::load(), vpart_info::load(), body_part_type::load(), character_modifier::load(), Item_factory::load_basic_info(), Item_factory::load_item_group_data(), load_mapgen(), load_place_mapings_alternatively(), mutation_branch::load_trait_group(), MonsterGroupManager::LoadMonsterGroup(), and Item_factory::set_use_methods_from_json().
get_float()
double JsonArray::get_float (size_t idx) const inline
Definition at line 643 of file flexbuffer_json-inl.h.
 {
     return ( *this )[ idx ];
 }
Referenced by int_distribution::deserialize(), effect_type::extract_effect(), body_part_type::load(), character_modifier::load(), damage_type::load(), and Item_factory::set_use_methods_from_json().
get_int()
int JsonArray::get_int (size_t idx) const inline
Definition at line 638 of file flexbuffer_json-inl.h.
 {
     return ( *this )[ idx ];
 }
Referenced by mtype::add_regeneration_modifier(), mtype::add_special_attack(), point::deserialize(), tripoint::deserialize(), armor_portion_data::deserialize(), mission::deserialize(), int_distribution::deserialize(), mm_submap::deserialize(), jmapgen_int::jmapgen_int(), fault_fix::load(), mtype::load(), mutation_branch::load(), recipe::load(), vpart_info::load(), body_part_type::load(), tool_comp::load(), item_comp::load(), color_loader< ColorType >::load_colors(), load_distribution(), Item_factory::load_item_group_data(), mutation_branch::load_trait_group(), and mapgen_function_json_nested::setup_internal().
get_next()
JsonValue JsonArray::get_next () inline private
Definition at line 797 of file flexbuffer_json-inl.h.
 {
     return ( *this )[ next_++ ];
 }
References next_.
Referenced by next_array(), next_bool(), next_float(), next_int(), next_object(), next_string(), next_value(), and read_next().
get_object()
JsonObject JsonArray::get_object (size_t idx) const inline
Definition at line 653 of file flexbuffer_json-inl.h.
 {
     return ( *this )[ idx ];
 }
Referenced by panel_manager::deserialize().
get_string()
std::string JsonArray::get_string (size_t idx) const inline
Definition at line 633 of file flexbuffer_json-inl.h.
 {
     return ( *this )[ idx ];
 }
Referenced by mtype::add_regeneration_modifier(), mtype::add_special_attack(), cata_variant::deserialize(), mm_submap::deserialize(), eoc_math::from_json(), item_reader::get_next(), fault_fix::load(), mtype::load(), recipe::load(), body_part_type::load(), character_modifier::load(), damage_type::load(), tool_comp::load(), item_comp::load(), Item_factory::load_basic_info(), load_forest_mapgen_settings(), Item_factory::load_item_group_data(), load_msg_help(), load_season_array(), mutation_branch::load_trait_group(), Item_factory::set_use_methods_from_json(), and mapgen_function_json_base::setup_common().
get_tags()
template<typename T , typename Res > Res JsonArray::get_tags (size_t idx) const
Definition at line 778 of file flexbuffer_json-inl.h.
 {
     Res res;
     JsonValue jv = ( *this )[ idx ];
     // allow single string as tag
     if( jv.test_string() ) {
         res.insert( T( jv.get_string() ) );
         return res;
     }
     for( const std::string line : jv.get_array() ) {
         res.insert( T( line ) );
     }
     return res;
 }
References JsonValue::get_array(), JsonValue::get_string(), line, and JsonValue::test_string().
has_array()
bool JsonArray::has_array (size_t idx) const inline
Definition at line 678 of file flexbuffer_json-inl.h.
 {
     return idx < size_ && ( *this )[ idx ].test_array();
 }
References size_.
Referenced by recipe::load(), and test_array().
has_bool()
bool JsonArray::has_bool (size_t idx) const inline
Definition at line 663 of file flexbuffer_json-inl.h.
 {
     return idx < size_ && ( *this )[ idx ].test_bool();
 }
References size_.
Referenced by test_bool().
has_float()
bool JsonArray::has_float (size_t idx) const inline
Definition at line 673 of file flexbuffer_json-inl.h.
 {
     return idx < size_ && ( *this )[ idx ].test_float();
 }
References size_.
Referenced by test_float().
has_int()
bool JsonArray::has_int (size_t idx) const inline
Definition at line 668 of file flexbuffer_json-inl.h.
 {
     return idx < size_ && ( *this )[ idx ].test_int();
 }
References size_.
Referenced by event_multiset::deserialize(), Item_factory::set_use_methods_from_json(), and test_int().
has_more()
bool JsonArray::has_more () const inline
Definition at line 463 of file flexbuffer_json.h.
{
             return next_ < size_;
         }
Referenced by Character::load(), monster::load(), test_data::load(), mtype::load(), overmap_special::load(), vpart_info::load(), submap::load(), Item_factory::load_basic_info(), load_distribution(), io::detail::has_archive_tag< T, typename enable_if_type< typename T::archive_type_tag >::type >::read(), overmap::unserialize(), and overmap::unserialize_view().
has_object()
bool JsonArray::has_object (size_t idx) const inline
Definition at line 683 of file flexbuffer_json-inl.h.
 {
     return idx < size_ && ( *this )[ idx ].test_object();
 }
References size_.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string(), and test_object().
has_string()
bool JsonArray::has_string (size_t idx) const inline
Definition at line 658 of file flexbuffer_json-inl.h.
 {
     return idx < size_ && ( *this )[ idx ].test_string();
 }
References size_.
Referenced by mtype::load(), and test_string().
init()
void JsonArray::init (const flexbuffer & json, tiny_bitset * moved_visited_fields = nullptr) inline private noexcept
Definition at line 478 of file flexbuffer_json.h.
{
             if( json.IsFixedTypedVector() ) {
                 size_ = json.AsFixedTypedVector().size();
             } else if( json.IsTypedVector() ) {
                 size_ = json.AsTypedVector().size();
             } else {
                 size_ = json.AsVector().size();
             }
             if( moved_visited_fields ) {
                 using namespace std;
                 swap( visited_fields_bitset_, *moved_visited_fields );
             } else {
                 visited_fields_bitset_.resize( size_ );
             }
         }
References cata::swap().
mark_visited()
void JsonArray::mark_visited (size_t idx) const inline private
Definition at line 496 of file flexbuffer_json.h.
{
             visited_fields_bitset_.set( idx );
         }
References tiny_bitset::set().
Referenced by JsonArray::const_iterator::operator*(), and operator[]().
next_array()
JsonArray JsonArray::next_array () inline
Definition at line 729 of file flexbuffer_json-inl.h.
 {
     return get_next();
 }
References get_next().
Referenced by submap::load(), overmap::load_monster_groups(), overmap::unserialize(), unserialize_array_from_compacted_sequence(), overmap::unserialize_omap(), and overmap::unserialize_view().
next_bool()
bool JsonArray::next_bool () inline
Definition at line 701 of file flexbuffer_json-inl.h.
 {
     return get_next();
 }
References get_next().
next_enum_value()
template<typename E , typename > E JsonArray::next_enum_value
Definition at line 749 of file flexbuffer_json-inl.h.
 {
     try {
         return io::string_to_enum<E>( next_string() );
     } catch( const io::InvalidEnumString & ) {
         --path_.last();
         throw_error( "invalid enumeration value" );
     }
 }
References JsonPath::last(), next_string(), JsonWithPath::path_, and throw_error().
next_float()
double JsonArray::next_float () inline
Definition at line 720 of file flexbuffer_json-inl.h.
 {
     return get_next();
 }
References get_next().
next_int()
int JsonArray::next_int () inline
Definition at line 710 of file flexbuffer_json-inl.h.
 {
     return get_next();
 }
References get_next().
Referenced by mapbuffer::deserialize(), Character::load(), submap::load(), load_place_mapings_alternatively(), MonsterGroupManager::LoadMonsterGroup(), overmap::unserialize(), and overmap::unserialize_omap().
next_object()
JsonObject JsonArray::next_object () inline
Definition at line 738 of file flexbuffer_json-inl.h.
 {
     return get_next();
 }
References get_next().
Referenced by mtype::load(), overmap_special::load(), vpart_info::load(), load_distribution(), overmap::unserialize(), and overmap::unserialize_omap().
next_string()
std::string JsonArray::next_string () inline
Definition at line 692 of file flexbuffer_json-inl.h.
 {
     return get_next();
 }
References get_next().
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string(), json_talk_topic::load(), submap::load(), Item_factory::load_basic_info(), load_season_array(), next_enum_value(), overmap::unserialize(), and overmap::unserialize_omap().
next_value()
JsonValue JsonArray::next_value () inline
Definition at line 743 of file flexbuffer_json-inl.h.
 {
     return get_next();
 }
References get_next().
Referenced by mm_region::deserialize(), conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string(), get_dbl_or_var(), get_duration_or_var(), submap::load(), load_place_mapings_alternatively(), and overmap::unserialize().
operator=() [1/2]
JsonArray& JsonArray::operator= (const JsonArray & rhs) inline
Definition at line 372 of file flexbuffer_json.h.
{
             JsonWithPath::operator=( rhs );
             init( json_ );
             return *this;
         }
References init, Json::json_, and JsonWithPath::operator=().
operator=() [2/2]
JsonArray& JsonArray::operator= (JsonArray && rhs) inline noexcept
Definition at line 384 of file flexbuffer_json.h.
{
             JsonWithPath::operator=( std::move( static_cast<JsonWithPath &>( rhs ) ) );
             init( json_, &rhs.visited_fields_bitset_ );
             rhs.visited_fields_bitset_.set_all();
             return *this;
         }
References init, Json::json_, and JsonWithPath::operator=().
operator[]()
JsonValue JsonArray::operator[] (size_t idx) const inline
Definition at line 612 of file flexbuffer_json-inl.h.
 {
     // Manually bsearch for the key idx to store in visited_fields_bitset_.
     // flexbuffers::Map::operator[] will probably be faster but won't give us the idx,
     // which we need to track visited fields.
     if( idx < size_ ) {
         mark_visited( idx );
         flexbuffers::Reference value;
         if( json_.IsFixedTypedVector() ) {
             value = json_.AsFixedTypedVector()[ idx ];
         } else if( json_.IsTypedVector() ) {
             value = json_.AsTypedVector()[ idx ];
         } else {
             value = json_.AsVector()[ idx ];
         }
         return JsonValue{ root_, value, &path_, idx };
     }
     throw_error( std::to_string( idx ) + " index is out of bounds." );
 }
References Json::json_, mark_visited(), JsonWithPath::path_, Json::root_, size_, throw_error(), and to_string().
read() [1/2]
template<typename T > bool JsonArray::read (size_t idx, T & t, bool throw_on_error = false) const
Definition at line 766 of file flexbuffer_json-inl.h.
 {
     return ( *this )[ idx ].read( t, throw_on_error );
 }
read() [2/2]
template<typename T , std::enable_if_t< !std::is_same_v< void, typename T::value_type > > * > auto JsonArray::read (T & v, bool throw_on_error = false) const -> decltype(v.front(), true)
Definition at line 592 of file flexbuffer_json-inl.h.
 {
     try {
         v.clear();
         for( JsonValue value : *this ) {
             typename T::value_type element;
             if( value.read( element, throw_on_error ) ) {
                 v.emplace_back( std::move( element ) );
             }
         }
     } catch( const JsonError & ) {
         if( throw_on_error ) {
             throw;
         }
         return false;
     }
     return true;
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::clear(), and JsonValue::read().
Referenced by assign(), overmap_special_locations::deserialize(), pos_dir< Tripoint >::deserialize(), vehicle_part::deserialize(), ma_technique::load(), tool_comp::load(), item_comp::load(), load_msg_help(), and JsonValue::read().
read_next()
template<typename T > bool JsonArray::read_next (T & t, bool throw_on_error = false)
Definition at line 760 of file flexbuffer_json-inl.h.
 {
     return get_next().read( t, throw_on_error );
 }
References get_next(), and JsonValue::read().
Referenced by cata_variant::deserialize(), numeric_interval< T, typename >::deserialize(), Character::load(), monster::load(), test_data::load(), load_min_max(), io::detail::has_archive_tag< T, E >::read(), and unserialize_array_from_compacted_sequence().
size()
size_t JsonArray::size () const inline
Definition at line 398 of file flexbuffer_json.h.
{
             return size_;
         }
Referenced by overmap_special_locations::deserialize(), pos_dir< Tripoint >::deserialize(), panel_manager::deserialize(), point::deserialize(), tripoint::deserialize(), vehicle_part::deserialize(), mission::deserialize(), int_distribution::deserialize(), cata_variant::deserialize(), numeric_interval< T, typename >::deserialize(), mm_submap::deserialize(), effect_type::extract_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_trigger_event(), eoc_math::from_json(), JsonObject::get_as_string_array(), JsonObject::get_int_array(), JsonObject::get_string_array(), jmapgen_int::jmapgen_int(), submap::load(), tool_comp::load(), item_comp::load(), load_forest_mapgen_settings(), load_mapgen(), load_place_mapings_alternatively(), load_region_overlay(), load_season_array(), JsonValue::read(), mapgen_function_json_base::setup_common(), and unserialize_array_from_compacted_sequence().
string_error()
void JsonArray::string_error (size_t idx, int offset, const std::string & message) const inline
Definition at line 771 of file flexbuffer_json-inl.h.
 {
     ( *this )[ idx ].string_error( path_, offset, message );
 }
References mapgen_defer::message, and JsonWithPath::path_.
Referenced by mapgen_function_json_base::setup_common().
test_array()
bool JsonArray::test_array () const inline
Definition at line 725 of file flexbuffer_json-inl.h.
 {
     return has_array( next_ );
 }
References has_array(), and next_.
Referenced by load_mapgen().
test_bool()
bool JsonArray::test_bool () const inline
Definition at line 697 of file flexbuffer_json-inl.h.
 {
     return has_bool( next_ );
 }
References has_bool(), and next_.
test_float()
bool JsonArray::test_float () const inline
Definition at line 715 of file flexbuffer_json-inl.h.
 {
     return has_float( next_ );
 }
References has_float(), and next_.
test_int()
bool JsonArray::test_int () const inline
Definition at line 706 of file flexbuffer_json-inl.h.
 {
     return has_int( next_ );
 }
References has_int(), and next_.
Referenced by load_place_mapings_alternatively().
test_object()
bool JsonArray::test_object () const inline
Definition at line 734 of file flexbuffer_json-inl.h.
 {
     return has_object( next_ );
 }
References has_object(), and next_.
Referenced by armor_portion_data::deserialize(), npc_class::load(), Item_factory::load(), Item_factory::load_basic_info(), and load_place_mapings_alternatively().
test_string()
bool JsonArray::test_string () const inline
Definition at line 688 of file flexbuffer_json-inl.h.
 {
     return has_string( next_ );
 }
References has_string(), and next_.
Referenced by load_place_mapings_alternatively().
throw_error() [1/2]
void JsonWithPath::throw_error inline noexcept
Definition at line 128 of file flexbuffer_json.h.
{
             throw_error( 0, message );
         }
Referenced by eoc_math::_validate_type(), mtype::add_special_attack(), overmap_special_locations::deserialize(), pos_dir< Tripoint >::deserialize(), panel_manager::deserialize(), point::deserialize(), tripoint::deserialize(), int_distribution::deserialize(), cata_variant::deserialize(), numeric_interval< T, typename >::deserialize(), mtype::load(), submap::load(), load_msg_help(), load_place_mapings_alternatively(), next_enum_value(), operator[](), mapgen_function_json_base::setup_common(), overmap::unserialize(), unserialize_array_from_compacted_sequence(), and overmap::unserialize_view().
throw_error() [2/2]
void JsonWithPath::throw_error inline noexcept
Definition at line 131 of file flexbuffer_json.h.
{
             Json::throw_error( path_, offset, message );
         }
throw_error_after()
void JsonWithPath::throw_error_after inline noexcept
Definition at line 134 of file flexbuffer_json.h.
{
             Json::throw_error_after( path_, message );
         }
Member Data Documentation
const_iterator
friend JsonArray::const_iterator
Definition at line 392 of file flexbuffer_json.h.
Referenced by begin(), and end().
next_
size_t JsonArray::next_ = 0 private
Definition at line 475 of file flexbuffer_json.h.
Referenced by get_next(), test_array(), test_bool(), test_float(), test_int(), test_object(), and test_string().
size_
size_t JsonArray::size_ = 0 private
Definition at line 474 of file flexbuffer_json.h.
Referenced by end(), has_array(), has_bool(), has_float(), has_int(), has_object(), has_string(), and operator[]().
visited_fields_bitset_
tiny_bitset JsonArray::visited_fields_bitset_ mutable private
Definition at line 494 of file flexbuffer_json.h.
The documentation for this class was generated from the following files:
src/flexbuffer_json.h
src/flexbuffer_json-inl.h