Cataclysm DDA: vpart_migration Class Reference
vpart_migration Class Reference
Holder for all vpart migrations, when loading parts with vpart_id present in the map keys they'll be replaced by vpart_id in the pair's value.
#include <veh_type.h>
Static Public Member Functions
static void load (const JsonObject &jo)
Handler for loading "vehicle_part_migration" type of json object.
static void reset ()
Clears migration list.
static void finalize ()
Finalizes migrations.
static void check ()
Checks migrations.
static const vpart_migration * find_migration (const vpart_id &original)
Find the last migration entry of the given vpart_id.
Public Attributes
vpart_id part_id_old
vpart_id part_id_new
std::optional< std::string > variant
std::vector< itype_id > add_veh_tools
Detailed Description
Holder for all vpart migrations, when loading parts with vpart_id present in the map keys they'll be replaced by vpart_id in the pair's value.
Definition at line 524 of file veh_type.h.
Member Function Documentation
check()
void vpart_migration::check () static
Checks migrations.
Definition at line 1755 of file veh_type.cpp.
 {
     for( const auto &[from_id, _] : vpart_migrations ) {
         const vpart_migration &vm = *find_migration( from_id );
         if( !vm.part_id_new.is_valid() ) {
             debugmsg( "vpart migration specifies invalid id '%s'", vm.part_id_new.str() );
             continue;
         }
         if( !vm.add_veh_tools.empty() && !vm.part_id_new->has_flag( "VEH_TOOLS" ) ) {
             debugmsg( "vpart migration from id '%s' specified 'add_veh_tools' but target id '%s' is not a VEH_TOOLS part",
                       from_id.str(), vm.part_id_new.str() );
         }
         if( vm.variant && vm.part_id_new->variants.count( vm.variant.value() ) <= 0 ) {
             debugmsg( "vpart migration chain from id '%s' to '%s' specifies invalid variant '%s'",
                       from_id.str(), vm.part_id_new.str(), vm.variant.value() );
         }
     }
 }
References _, add_veh_tools, debugmsg, find_migration(), vpart_info::has_flag(), string_id< T >::is_valid(), part_id_new, string_id< T >::str(), variant, vpart_info::variants, and vpart_migrations.
Referenced by DynamicDataLoader::check_consistency().
finalize()
void vpart_migration::finalize () static
Finalizes migrations.
Definition at line 1744 of file veh_type.cpp.
 {
     for( const auto &[from_id, migration] : vpart_migrations ) {
         if( !migration.add_veh_tools.empty() &&
             !migration.part_id_new->has_flag( "VEH_TOOLS" ) ) {
             debugmsg( "vpart migration from id '%s' specified 'add_veh_tools' but target id '%s' is not a VEH_TOOLS part",
                       from_id.str(), migration.part_id_new.str() );
         }
     }
 }
References debugmsg, and vpart_migrations.
Referenced by DynamicDataLoader::finalize_loaded_data().
find_migration()
const vpart_migration * vpart_migration::find_migration (const vpart_id & original) static
Find the last migration entry of the given vpart_id.
Definition at line 1774 of file veh_type.cpp.
 {
     vpart_migration *migration = nullptr;
     vpart_id pid = original;
     // limit up to 10 migrations per vpart (guard in case of accidental loops)
     for( int i = 0; i < 10; i++ ) {
         const auto &migration_it = vpart_migrations.find( pid );
         if( migration_it == vpart_migrations.cend() ) {
             break;
         }
         pid = migration_it->second.part_id_new;
         migration = &migration_it->second;
     }
     return migration;
 }
References vpart_migrations.
Referenced by check(), vehicle_part::deserialize(), and vehicles::finalize_prototypes().
load()
void vpart_migration::load (const JsonObject & jo) static
Handler for loading "vehicle_part_migration" type of json object.
Definition at line 1729 of file veh_type.cpp.
 {
     vpart_migration migration;
     mandatory( jo, /* was_loaded = */ true, "from", migration.part_id_old );
     mandatory( jo, /* was_loaded = */ true, "to", migration.part_id_new );
     optional( jo, /* was_loaded = */ true, "variant", migration.variant );
     optional( jo, /* was_loaded = */ true, "add_veh_tools", migration.add_veh_tools );
     vpart_migrations.emplace( migration.part_id_old, migration );
 }
References mandatory, optional(), migration::variant, and vpart_migrations.
Referenced by DynamicDataLoader::initialize().
reset()
void vpart_migration::reset () static
Clears migration list.
Definition at line 1739 of file veh_type.cpp.
 {
     vpart_migrations.clear();
 }
References vpart_migrations.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
add_veh_tools
std::vector<itype_id> vpart_migration::add_veh_tools
Definition at line 530 of file veh_type.h.
Referenced by check().
part_id_new
vpart_id vpart_migration::part_id_new
Definition at line 528 of file veh_type.h.
Referenced by check().
part_id_old
vpart_id vpart_migration::part_id_old
Definition at line 527 of file veh_type.h.
variant
std::optional<std::string> vpart_migration::variant
Definition at line 529 of file veh_type.h.
Referenced by check().
The documentation for this class was generated from the following files:
src/veh_type.h
src/veh_type.cpp