Cataclysm DDA: invoke_item_activity_actor Class Reference
invoke_item_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
invoke_item_activity_actor (item_location item, std::string method)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &)
Private Attributes
item_location item
std::string method
Detailed Description
Definition at line 1757 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
invoke_item_activity_actor()
invoke_item_activity_actor::invoke_item_activity_actor (item_location item, std::string method) inline
Definition at line 1760 of file activity_actor_definitions.h.
                                                                            :
             item( std::move( item ) ),
             method( std::move( method ) ) {};
Member Function Documentation
clone()
std::unique_ptr<activity_actor> invoke_item_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1771 of file activity_actor_definitions.h.
{
             return std::make_unique<invoke_item_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > invoke_item_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6184 of file activity_actor.cpp.
 {
     invoke_item_activity_actor actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "item", actor.item );
     data.read( "method", actor.method );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void invoke_item_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 6161 of file activity_actor.cpp.
 {
     item_location _item = item;
     std::string _method = method;
     if( method.empty() ) {
         who.cancel_activity();
         who.invoke_item( _item.get_item() );
         return;
     }
     who.cancel_activity();
     who.invoke_item( _item.get_item(), _method );
 }
References Character::cancel_activity(), item_location::get_item(), Character::invoke_item(), item, and method.
finish()
void invoke_item_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1769 of file activity_actor_definitions.h.
 {};
get_type()
activity_id invoke_item_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1763 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_INVOKE_ITEM" );
         }
References activity_id.
serialize()
void invoke_item_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6174 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "item", item );
     jsout.member( "method", method );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), method, and JsonOut::start_object().
start()
void invoke_item_activity_actor::start (player_activity & act, Character & who) inline override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1767 of file activity_actor_definitions.h.
 {};
Member Data Documentation
item
item_location invoke_item_activity_actor::item private
Definition at line 1779 of file activity_actor_definitions.h.
Referenced by do_turn().
method
std::string invoke_item_activity_actor::method private
Definition at line 1780 of file activity_actor_definitions.h.
Referenced by do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp