Cataclysm DDA: player_morale Class Reference
player_morale Class Reference
#include <morale.h>
Classes
struct body_part_data
class morale_point
struct mutation_data
Public Member Functions
player_morale ()
player_morale (player_morale &&) noexcept=default
player_morale (const player_morale &)=default
player_morale & operator= (player_morale &&)=default
player_morale & operator= (const player_morale &)=default
void add (const morale_type &type, int bonus, int max_bonus=0, const time_duration &duration=6_minutes, const time_duration &decay_start=3_minutes, bool capped=false, const itype *item_type=nullptr)
Adds morale to existing or creates one.
void set_permanent (const morale_type &type, int bonus, const itype *item_type=nullptr)
Sets the new level for the permanent morale, or creates one.
int has (const morale_type &type, const itype *item_type=nullptr) const
Returns bonus from specified morale.
void remove (const morale_type &type, const itype *item_type=nullptr)
Removes specified morale.
void clear ()
Clears up all morale points.
int get_level () const
Returns overall morale level.
void decay (const time_duration &ticks=1_turns)
Ticks down morale counters and removes them.
void display (int focus_eq, int pain_penalty, int sleepiness_penalty)
Displays morale screen.
bool consistent_with (const player_morale &morale) const
Returns false whether morale is inconsistent with the argument.
void calculate_percentage ()
calculates the percentage contribution for each morale point
int get_total_positive_value () const
int get_total_negative_value () const
int get_perceived_pain () const
Returns perceived pain.
void on_mutation_gain (const trait_id &mid)
void on_mutation_loss (const trait_id &mid)
void on_stat_change (const std::string &stat, int value)
void on_item_wear (const item &it)
void on_item_takeoff (const item &it)
void on_worn_item_transform (const item &old_it, const item &new_it)
void on_worn_item_washed (const item &it)
void on_effect_int_change (const efftype_id &eid, int intensity, const bodypart_id &bp=bodypart_id("bp_null"))
void store (JsonOut &jsout) const
void load (const JsonObject &jsin)
Protected Member Functions
morale_mult get_temper_mult () const
void set_prozac (bool new_took_prozac)
void set_prozac_bad (bool new_took_prozac_bad)
void set_stylish (bool new_stylish)
void set_worn (const item &it, bool worn)
void set_mutation (const trait_id &mid, bool active)
bool has_mutation (const trait_id &mid)
bool has_flag (const json_character_flag &flag)
void remove_if (const std::function< bool(const morale_point &)> &func)
void remove_expired ()
void invalidate ()
void update_stylish_bonus ()
void update_squeamish_penalty ()
void update_masochist_bonus ()
void update_radiophile_bonus ()
void update_bodytemp_penalty (const time_duration &ticks)
void update_constrained_penalty ()
Private Types
using mutation_handler = std::function< void(player_morale *)>
Private Attributes
std::vector< morale_point > points
std::map< bodypart_id, body_part_data > body_parts
body_part_data no_body_part
std::map< trait_id, mutation_data > mutations
std::map< itype_id, int > super_fancy_items
int level
bool level_is_valid
bool took_prozac
bool took_prozac_bad
bool stylish
int perceived_pain
int radiation
Detailed Description
Definition at line 21 of file morale.h.
Member Typedef Documentation
mutation_handler
using player_morale::mutation_handler = std::function<void (player_morale *)> private
Definition at line 181 of file morale.h.
Constructor & Destructor Documentation
player_morale() [1/3]
player_morale::player_morale ()
Definition at line 248 of file morale.cpp.
                              :
     level( 0 ),
     level_is_valid( false ),
     took_prozac( false ),
     took_prozac_bad( false ),
     stylish( false ),
     perceived_pain( 0 ),
     radiation( 0 )
 {
     // Cannot use 'this' because the object is copyable
     const auto set_optimist = []( player_morale * pm, int bonus ) {
         pm->set_permanent( MORALE_PERM_OPTIMIST, bonus, nullptr );
     };
     const auto set_badtemper = []( player_morale * pm, int bonus ) {
         pm->set_permanent( MORALE_PERM_BADTEMPER, bonus, nullptr );
     };
     const auto set_numb = []( player_morale * pm, int bonus ) {
         pm->set_permanent( MORALE_PERM_NUMB, bonus, nullptr );
     };
     const auto set_stylish = []( player_morale * pm, bool new_stylish ) {
         pm->set_stylish( new_stylish );
     };
     const auto update_constrained = []( player_morale * pm ) {
         pm->update_constrained_penalty();
     };
     const auto update_masochist = []( player_morale * pm ) {
         pm->update_masochist_bonus();
     };
     const auto update_radiophile = []( player_morale * pm ) {
         pm->update_radiophile_bonus();
     };
     mutations[trait_OPTIMISTIC] =
     mutation_data( [set_optimist]( player_morale * pm ) {
         return set_optimist( pm, 9 );
     },
     [set_optimist]( player_morale * pm ) {
         return set_optimist( pm, 0 );
     } );
     mutations[trait_BADTEMPER] =
     mutation_data( [set_badtemper]( player_morale * pm ) {
         return set_badtemper( pm, -9 );
     },
     [set_badtemper]( player_morale * pm ) {
         return set_badtemper( pm, 0 );
     } );
     mutations[trait_NUMB] =
     mutation_data( [set_numb]( player_morale * pm ) {
         return set_numb( pm, -1 );
     },
     [set_numb]( player_morale * pm ) {
         return set_numb( pm, 0 );
     } );
     mutations[trait_STYLISH] =
     mutation_data( [set_stylish]( player_morale * pm ) {
         return set_stylish( pm, true );
     },
     [set_stylish]( player_morale * pm ) {
         return set_stylish( pm, false );
     } );
     mutations[trait_FLOWERS]       = mutation_data( update_constrained );
     mutations[trait_ROOTS1]        = mutation_data( update_constrained );
     mutations[trait_ROOTS2]        = mutation_data( update_constrained );
     mutations[trait_ROOTS3]        = mutation_data( update_constrained );
     mutations[trait_CHLOROMORPH]   = mutation_data( update_constrained );
     mutations[trait_LEAVES2]       = mutation_data( update_constrained );
     mutations[trait_LEAVES3]       = mutation_data( update_constrained );
     mutations[trait_MASOCHIST]     = mutation_data( update_masochist );
     mutations[trait_MASOCHIST_MED] = mutation_data( update_masochist );
     mutations[trait_CENOBITE]      = mutation_data( update_masochist );
     mutations[trait_RADIOPHILE]    = mutation_data( update_radiophile );
     mutations[trait_VANITY]        = mutation_data( update_constrained );
 }
References MORALE_PERM_BADTEMPER, MORALE_PERM_NUMB, MORALE_PERM_OPTIMIST, mutations, set_permanent(), set_stylish(), trait_BADTEMPER, trait_CENOBITE, trait_CHLOROMORPH, trait_FLOWERS, trait_LEAVES2, trait_LEAVES3, trait_MASOCHIST, trait_MASOCHIST_MED, trait_NUMB, trait_OPTIMISTIC, trait_RADIOPHILE, trait_ROOTS1, trait_ROOTS2, trait_ROOTS3, trait_STYLISH, trait_VANITY, update_constrained_penalty(), update_masochist_bonus(), and update_radiophile_bonus().
player_morale() [2/3]
player_morale::player_morale (player_morale &&) default noexcept
player_morale() [3/3]
player_morale::player_morale (const player_morale &) default
Member Function Documentation
add()
void player_morale::add (const morale_type & type, int bonus, int max_bonus = 0, const time_duration & duration = 6_minutes, const time_duration & decay_start = 3_minutes, bool capped = false, const itype * item_type = nullptr)
Adds morale to existing or creates one.
Definition at line 322 of file morale.cpp.
 {
     if( ( duration == 0_turns ) && !is_permanent_morale( type ) ) {
         debugmsg( "Tried to set a non-permanent morale \"%s\" as permanent.",
                   type.obj().describe( item_type ) );
         return;
     }
     for( player_morale::morale_point &m : points ) {
         if( m.matches( type, item_type ) ) {
             const int prev_bonus = m.get_net_bonus();
             m.add( bonus, max_bonus, duration, decay_start, capped );
             if( m.is_expired() ) {
                 remove_expired();
             } else if( m.get_net_bonus() != prev_bonus ) {
                 invalidate();
             }
             return;
         }
     }
     morale_point new_morale( type, item_type, bonus, max_bonus, duration, decay_start, capped );
     if( !new_morale.is_expired() ) {
         points.push_back( new_morale );
         invalidate();
     }
 }
References debugmsg, invalidate(), player_morale::morale_point::is_expired(), anonymous_namespace{morale.cpp}::is_permanent_morale(), points, remove_expired(), and type.
Referenced by set_permanent(), and update_bodytemp_penalty().
calculate_percentage()
void player_morale::calculate_percentage ()
calculates the percentage contribution for each morale point
Definition at line 413 of file morale.cpp.
 {
     const morale_mult mult = get_temper_mult();
     int sum_of_positive_squares = 0;
     int sum_of_negative_squares = 0;
     for( player_morale::morale_point &m : points ) {
         const int bonus = m.get_net_bonus( mult );
         if( bonus > 0 ) {
             sum_of_positive_squares += std::pow( bonus, 2 );
         } else {
             sum_of_negative_squares += std::pow( bonus, 2 );
         }
     }
     for( player_morale::morale_point &m : points ) {
         const int bonus = m.get_net_bonus( mult );
         if( bonus > 0 ) {
             m.set_percent_contribution( ( std::pow( bonus, 2 ) / sum_of_positive_squares ) * 100 );
         } else {
             m.set_percent_contribution( ( std::pow( bonus, 2 ) / sum_of_negative_squares ) * 100 );
         }
     }
 }
References get_temper_mult(), and points.
Referenced by display().
clear()
void player_morale::clear ()
Clears up all morale points.
Definition at line 865 of file morale.cpp.
 {
     points.clear();
     no_body_part = body_part_data();
     body_parts.clear();
     for( auto &m : mutations ) {
         m.second.clear();
     }
     took_prozac = false;
     took_prozac_bad = false;
     stylish = false;
     super_fancy_items.clear();
     invalidate();
 }
References body_parts, invalidate(), mutations, no_body_part, points, stylish, super_fancy_items, took_prozac, and took_prozac_bad.
consistent_with()
bool player_morale::consistent_with (const player_morale & morale) const
Returns false whether morale is inconsistent with the argument.
Only permanent morale is checked
Definition at line 823 of file morale.cpp.
 {
     const auto test_points = []( const player_morale & lhs, const player_morale & rhs ) {
         for( const player_morale::morale_point &lhp : lhs.points ) {
             if( !lhp.is_permanent() ) {
                 continue;
             }
             const auto iter = std::find_if( rhs.points.begin(), rhs.points.end(),
             [ &lhp ]( const morale_point & rhp ) {
                 return lhp.matches( rhp );
             } );
             if( iter == rhs.points.end() || lhp.get_net_bonus() != iter->get_net_bonus() ) {
                 debugmsg( "Morale \"%s\" is inconsistent.", lhp.get_name() );
                 return false;
             }
         }
         return true;
     };
     if( took_prozac != morale.took_prozac ) {
         debugmsg( "player_morale::took_prozac is inconsistent." );
         return false;
     } else if( took_prozac_bad != morale.took_prozac_bad ) {
         debugmsg( "player_morale::took_prozac (bad) is inconsistent." );
         return false;
     } else if( stylish != morale.stylish ) {
         debugmsg( "player_morale::stylish is inconsistent." );
         return false;
     } else if( perceived_pain != morale.perceived_pain ) {
         debugmsg( "player_morale::perceived_pain is inconsistent." );
         return false;
     } else if( radiation != morale.radiation ) {
         debugmsg( "player_morale::radiation is inconsistent." );
         return false;
     }
     return test_points( *this, morale ) && test_points( morale, *this );
 }
References debugmsg, player_morale::morale_point::get_name(), player_morale::morale_point::get_net_bonus(), player_morale::morale_point::is_permanent(), spell_effect::morale(), perceived_pain, points, radiation, stylish, took_prozac, and took_prozac_bad.
decay()
void player_morale::decay (const time_duration & ticks = 1_turns)
Ticks down morale counters and removes them.
Definition at line 503 of file morale.cpp.
 {
     const auto do_decay = [ &ticks ]( morale_point & m ) {
         m.decay( ticks );
     };
     std::for_each( points.begin(), points.end(), do_decay );
     remove_expired();
     update_bodytemp_penalty( ticks );
     invalidate();
 }
References invalidate(), points, remove_expired(), and update_bodytemp_penalty().
display()
void player_morale::display (int focus_eq, int pain_penalty, int sleepiness_penalty)
Displays morale screen.
Definition at line 515 of file morale.cpp.
 {
     /*calculates the percent contributions of the morale points,
      * must be done before anything else in this method
      */
     calculate_percentage();
     constexpr int left_padding = 2; // including border
     constexpr int right_padding = 2; // including border
     constexpr int middle_padding_min = 2;
     constexpr int middle_padding_max = 12;
     class morale_line
     {
         public:
             enum class number_format : int {
                 normal,
                 signed_or_dash,
                 percent,
             };
             enum class line_color : int {
                 normal,
                 green_gray_red,
                 red_gray_green,
             };
             struct separation_line {};
         private:
             bool sep_line = false;
             std::string left;
             std::string right;
             nc_color color;
         public:
             morale_line() = default;
             explicit morale_line( const separation_line ) : sep_line( true ) {}
             morale_line( const std::string &text, const nc_color &color )
                 : left( text ), color( color ) {}
             morale_line( const std::string &left, const std::string &right,
                          const nc_color &color )
                 : left( left ), right( right ), color( color ) {}
             morale_line( const std::string &text, const int num,
                          const number_format num_fmt, const line_color col )
                 : left( text ) {
                 switch( num_fmt ) {
                     case number_format::normal:
                         right = string_format( "%d", num );
                         break;
                     case number_format::signed_or_dash:
                         if( num == 0 ) {
                             right = "-";
                         } else {
                             right = string_format( "%+d", num );
                         }
                         break;
                     case number_format::percent:
                         right = string_format( "%d%%", num );
                         break;
                 }
                 switch( col ) {
                     case line_color::normal:
                         color = c_white;
                         break;
                     case line_color::green_gray_red:
                     case line_color::red_gray_green:
                         if( num == 0 ) {
                             color = c_dark_gray;
                         } else if( ( num > 0 ) ^ ( col == line_color::red_gray_green ) ) {
                             color = c_green;
                         } else {
                             color = c_light_red;
                         }
                         break;
                 }
             }
             int max_width() const {
                 if( sep_line ) {
                     return 0;
                 } else if( right.empty() ) {
                     return left_padding + utf8_width( left ) + right_padding;
                 } else {
                     return left_padding + utf8_width( left ) + middle_padding_max
                            + utf8_width( right ) + right_padding;
                 }
             }
             void draw( catacurses::window &w, const int posy ) const {
                 int width = getmaxx( w );
                 if( sep_line ) {
                     mvwhline( w, point( 0, posy ), LINE_XXXO, 1 );
                     mvwhline( w, point( 1, posy ), 0, width - 2 );
                     mvwhline( w, point( width - 1, posy ), LINE_XOXX, 1 );
                 } else {
                     int text_width = width - left_padding - right_padding;
                     if( !right.empty() ) {
                         right_print( w, posy, right_padding, color, right );
                         text_width -= middle_padding_min + utf8_width( right );
                     }
                     trim_and_print( w, point( left_padding, posy ), text_width, color, left );
                 }
             }
     };
     // Separate and sort positive and negative morale
     const morale_mult mult = get_temper_mult();
     std::vector<morale_point> positive_morale;
     std::vector<morale_point> negative_morale;
     for( const morale_point &mp : points ) {
         const int bonus = mp.get_net_bonus( mult );
         if( bonus > 0 ) {
             positive_morale.emplace_back( mp );
         } else if( bonus < 0 ) {
             negative_morale.emplace_back( mp );
         }
     }
     const auto sort_morale = []( const morale_point & lhs, const morale_point & rhs ) -> bool {
         const int lhs_percent = lhs.get_percent_contribution();
         const int rhs_percent = rhs.get_percent_contribution();
         return localized_compare( std::make_pair( -lhs_percent, lhs.get_name() ),
                                   std::make_pair( -rhs_percent, rhs.get_name() ) );
     };
     std::sort( positive_morale.begin(), positive_morale.end(), sort_morale );
     std::sort( negative_morale.begin(), negative_morale.end(), sort_morale );
     // Initialize lines
     const std::vector<morale_line> top_lines {
         {},
         { _( "Morale" ), c_white },
         morale_line{ morale_line::separation_line {} },
         positive_morale.empty() &&negative_morale.empty() ?
         morale_line( _( "Nothing affects your morale" ), c_dark_gray ) :
         morale_line( _( "Source" ), _( "Value" ), c_light_gray ),
     };
     struct middle_morale_line {
         bool is_caption;
         morale_line ml;
         middle_morale_line( const bool is_caption, const morale_line &ml )
             : is_caption( is_caption ), ml( ml ) {}
     };
     std::vector<middle_morale_line> middle_lines;
     if( !positive_morale.empty() || !negative_morale.empty() ) {
         middle_lines.emplace_back( true, morale_line(
                                        _( "Total positive morale" ), get_total_positive_value(),
                                        morale_line::number_format::signed_or_dash,
                                        morale_line::line_color::green_gray_red
                                    ) );
         for( const morale_point &mp : positive_morale ) {
             middle_lines.emplace_back( false, morale_line(
                                            mp.get_name(), mp.get_percent_contribution(),
                                            morale_line::number_format::percent,
                                            morale_line::line_color::green_gray_red
                                        ) );
         }
         middle_lines.emplace_back( false, morale_line() );
         middle_lines.emplace_back( true, morale_line(
                                        _( "Total negative morale" ), -get_total_negative_value(),
                                        morale_line::number_format::signed_or_dash,
                                        morale_line::line_color::green_gray_red
                                    ) );
         for( const morale_point &mp : negative_morale ) {
             middle_lines.emplace_back( false, morale_line(
                                            mp.get_name(), mp.get_percent_contribution(),
                                            morale_line::number_format::percent,
                                            morale_line::line_color::red_gray_green
                                        ) );
         }
     }
     std::vector<morale_line> bottom_lines;
     bottom_lines.emplace_back( morale_line::separation_line {} );
     bottom_lines.emplace_back(
         _( "Total morale:" ), get_level(),
         morale_line::number_format::signed_or_dash,
         morale_line::line_color::green_gray_red
     );
     if( pain_penalty != 0 ) {
         bottom_lines.emplace_back(
             _( "Pain level:" ), -pain_penalty,
             morale_line::number_format::signed_or_dash,
             morale_line::line_color::green_gray_red
         );
     }
     if( sleepiness_penalty != 0 ) {
         bottom_lines.emplace_back(
             _( "Sleepiness level:" ), -sleepiness_penalty,
             morale_line::number_format::signed_or_dash,
             morale_line::line_color::green_gray_red
         );
     }
     bottom_lines.emplace_back(
         _( "Focus trends towards:" ), focus_eq,
         morale_line::number_format::normal,
         morale_line::line_color::normal
     );
     bottom_lines.emplace_back();
     const auto calc_max_width = []( const int width, const morale_line & ml ) -> int {
         return std::max( width, ml.max_width() );
     };
     const int max_window_width = std::max( {
         std::accumulate( top_lines.begin(), top_lines.end(), 0, calc_max_width ),
         std::accumulate( middle_lines.begin(), middle_lines.end(), 0,
         []( const int width, const middle_morale_line & ml ) -> int {
             return std::max( width, ml.ml.max_width() );
         } ),
         std::accumulate( bottom_lines.begin(), bottom_lines.end(), 0, calc_max_width )
     } );
     const int static_lines_height = top_lines.size() + bottom_lines.size();
     int win_w = 0;
     int win_h = 0;
     const int rows_total = middle_lines.size();
     int rows_visible = 0;
     int offset = 0;
     catacurses::window w;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         win_w = std::min( max_window_width, FULL_SCREEN_WIDTH );
         win_h = FULL_SCREEN_HEIGHT;
         const point win( ( TERMX - win_w ) / 2, ( TERMY - win_h ) / 2 );
         rows_visible = std::max( win_h - static_lines_height, 0 );
         if( rows_total < rows_visible ) {
             offset = 0;
         } else if( offset + rows_visible > rows_total ) {
             offset = rows_total - rows_visible;
         }
         w = catacurses::newwin( win_h, win_w, win );
         ui.position_from_window( w );
     } );
     ui.mark_resize();
     ui.on_redraw( [&]( const ui_adaptor & ) {
         werase( w );
         draw_border( w );
         int line = 0;
         for( const morale_line &ml : top_lines ) {
             ml.draw( w, line );
             ++line;
         }
         line = win_h - static_cast<int>( bottom_lines.size() );
         for( const morale_line &ml : bottom_lines ) {
             ml.draw( w, line );
             ++line;
         }
         bool caption_drawn = false;
         for( int mid_line = 0; offset + mid_line >= 0; --mid_line ) {
             if( offset + mid_line < rows_total ) {
                 const middle_morale_line &ml = middle_lines[offset + mid_line];
                 if( ml.is_caption ) {
                     ml.ml.draw( w, top_lines.size() );
                     caption_drawn = true;
                     break;
                 }
             }
         }
         for( int mid_line = caption_drawn ? 1 : 0;
              mid_line < rows_visible && offset + mid_line < rows_total;
              ++mid_line ) {
             if( offset + mid_line >= 0 ) {
                 const middle_morale_line &ml = middle_lines[offset + mid_line];
                 ml.ml.draw( w, static_cast<int>( top_lines.size() ) + mid_line );
             }
         }
         draw_scrollbar( w, offset, rows_visible, rows_total,
                         point( 0, top_lines.size() ), c_white, true );
         wnoutrefresh( w );
     } );
     input_context ctxt( "MORALE" );
     ctxt.register_action( "UP" );
     ctxt.register_action( "DOWN" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     std::string action;
     do {
         ui_manager::redraw();
         action = ctxt.handle_input();
         if( action == "DOWN" && offset < std::max( 0, rows_total - rows_visible ) ) {
             offset++;
         } else if( action == "UP" && offset > 0 ) {
             offset--;
         }
     } while( action != "CONFIRM" && action != "QUIT" );
 }
References _, action, c_dark_gray, c_green, c_light_gray, c_light_red, c_white, calculate_percentage(), color(), overmap_ui::draw(), draw_border(), draw_scrollbar(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, get_level(), player_morale::morale_point::get_name(), player_morale::morale_point::get_percent_contribution(), get_temper_mult(), get_total_negative_value(), get_total_positive_value(), catacurses::getmaxx(), input_context::handle_input(), left, line, LINE_XOXX, LINE_XXXO, localized_compare, max(), min(), catacurses::mvwhline(), catacurses::newwin(), temperatures::normal, point, points, ui_manager::redraw(), input_context::register_action(), right, right_print(), string_format(), TERMX, TERMY, trim_and_print(), utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
get_level()
int player_morale::get_level () const
Returns overall morale level.
Definition at line 471 of file morale.cpp.
 {
     if( !level_is_valid ) {
         const morale_mult mult = get_temper_mult();
         int sum_of_positive_squares = 0;
         int sum_of_negative_squares = 0;
         for( const morale_point &m : points ) {
             const int bonus = m.get_net_bonus( mult );
             if( bonus > 0 ) {
                 sum_of_positive_squares += std::pow( bonus, 2 );
             } else {
                 sum_of_negative_squares += std::pow( bonus, 2 );
             }
         }
         level = std::sqrt( sum_of_positive_squares ) - std::sqrt( sum_of_negative_squares );
         if( took_prozac ) {
             level *= morale_mults::prozac;
             if( took_prozac_bad ) {
                 level *= morale_mults::prozac_bad;
             }
         }
         level_is_valid = true;
     }
     return level;
 }
References get_temper_mult(), level, level_is_valid, points, morale_mults::prozac, morale_mults::prozac_bad, sqrt(), took_prozac, and took_prozac_bad.
Referenced by display().
get_perceived_pain()
int player_morale::get_perceived_pain () const
Returns perceived pain.
Only used in morale_test.cpp
Definition at line 452 of file morale.cpp.
 {
     return perceived_pain;
 }
References perceived_pain.
get_temper_mult()
morale_mult player_morale::get_temper_mult () const protected
Definition at line 396 of file morale.cpp.
 {
     morale_mult mult;
     if( has( MORALE_PERM_OPTIMIST ) ) {
         mult *= morale_mults::optimist;
     }
     if( has( MORALE_PERM_BADTEMPER ) ) {
         mult *= morale_mults::badtemper;
     }
     if( has( MORALE_PERM_NUMB ) ) {
         mult *= morale_mults::numb;
     }
     return mult;
 }
References morale_mults::badtemper, has(), MORALE_PERM_BADTEMPER, MORALE_PERM_NUMB, MORALE_PERM_OPTIMIST, morale_mults::numb, and morale_mults::optimist.
Referenced by calculate_percentage(), display(), get_level(), get_total_negative_value(), and get_total_positive_value().
get_total_negative_value()
int player_morale::get_total_negative_value () const
Definition at line 439 of file morale.cpp.
 {
     const morale_mult mult = get_temper_mult();
     int sum = 0;
     for( const morale_point &m : points ) {
         const int bonus = m.get_net_bonus( mult );
         if( bonus < 0 ) {
             sum += std::pow( bonus, 2 );
         }
     }
     return std::sqrt( sum );
 }
References get_temper_mult(), points, and sqrt().
Referenced by display().
get_total_positive_value()
int player_morale::get_total_positive_value () const
Definition at line 457 of file morale.cpp.
 {
     const morale_mult mult = get_temper_mult();
     int sum = 0;
     for( const morale_point &m : points ) {
         const int bonus = m.get_net_bonus( mult );
         if( bonus > 0 ) {
             sum += std::pow( bonus, 2 );
         }
     }
     return std::sqrt( sum );
 }
References get_temper_mult(), points, and sqrt().
Referenced by display().
has()
int player_morale::has (const morale_type & type, const itype * item_type = nullptr) const
Returns bonus from specified morale.
Definition at line 361 of file morale.cpp.
 {
     for( const morale_point &m : points ) {
         if( m.matches( type, item_type ) ) {
             return m.get_net_bonus();
         }
     }
     return 0;
 }
References points, and type.
Referenced by get_temper_mult().
has_flag()
bool player_morale::has_flag (const json_character_flag & flag) protected
Definition at line 892 of file morale.cpp.
 {
     return get_player_character().has_flag( flag );
 }
References get_player_character(), and Character::has_flag().
Referenced by update_bodytemp_penalty().
has_mutation()
bool player_morale::has_mutation (const trait_id & mid) protected
Definition at line 886 of file morale.cpp.
 {
     const auto &mutation = mutations.find( mid );
     return ( mutation != mutations.end() && mutation->second.get_active() );
 }
References mutation, and mutations.
Referenced by update_constrained_penalty(), update_masochist_bonus(), and update_radiophile_bonus().
invalidate()
void player_morale::invalidate () protected
Definition at line 881 of file morale.cpp.
 {
     level_is_valid = false;
 }
References level_is_valid.
Referenced by add(), clear(), decay(), remove_if(), set_prozac(), and set_prozac_bad().
load()
void player_morale::load (const JsonObject & jsin)
Definition at line 3909 of file savegame_json.cpp.
 {
     jsin.allow_omitted_members();
     jsin.read( "morale", points );
 }
References JsonObject::allow_omitted_members(), and JsonObject::read().
on_effect_int_change()
void player_morale::on_effect_int_change (const efftype_id & eid, int intensity, const bodypart_id & bp = bodypart_id("bp_null"))
Definition at line 964 of file morale.cpp.
 {
     const bodypart_id bp_null( "bp_null" );
     if( eid == effect_took_prozac && bp == bp_null ) {
         set_prozac( intensity != 0 );
     } else if( eid == effect_took_prozac_bad && bp == bp_null ) {
         set_prozac_bad( intensity != 0 );
     } else if( eid == effect_cold && bp != bp_null ) {
         body_parts[bp].cold = intensity;
     } else if( eid == effect_hot && bp != bp_null ) {
         body_parts[bp].hot = intensity;
     }
 }
References body_parts, bp, effect_cold, effect_hot, effect_took_prozac, effect_took_prozac_bad, intensity, set_prozac(), and set_prozac_bad().
Referenced by Character::check_and_recover_morale().
on_item_takeoff()
void player_morale::on_item_takeoff (const item & it)
Definition at line 932 of file morale.cpp.
 {
     set_worn( it, false );
 }
References set_worn().
on_item_wear()
void player_morale::on_item_wear (const item & it)
Definition at line 927 of file morale.cpp.
 {
     set_worn( it, true );
 }
References set_worn().
Referenced by outfit::check_and_recover_morale().
on_mutation_gain()
void player_morale::on_mutation_gain (const trait_id & mid)
Definition at line 905 of file morale.cpp.
 {
     set_mutation( mid, true );
 }
References set_mutation().
Referenced by Character::check_and_recover_morale().
on_mutation_loss()
void player_morale::on_mutation_loss (const trait_id & mid)
Definition at line 910 of file morale.cpp.
 {
     set_mutation( mid, false );
 }
References set_mutation().
on_stat_change()
void player_morale::on_stat_change (const std::string & stat, int value)
Definition at line 915 of file morale.cpp.
 {
     if( stat == "perceived_pain" ) {
         perceived_pain = value;
         update_masochist_bonus();
     }
     if( stat == "radiation" ) {
         radiation = value;
         update_radiophile_bonus();
     }
 }
References perceived_pain, radiation, update_masochist_bonus(), and update_radiophile_bonus().
Referenced by Character::check_and_recover_morale().
on_worn_item_transform()
void player_morale::on_worn_item_transform (const item & old_it, const item & new_it)
Definition at line 937 of file morale.cpp.
 {
     set_worn( old_it, false );
     set_worn( new_it, true );
 }
References set_worn().
on_worn_item_washed()
void player_morale::on_worn_item_washed (const item & it)
Definition at line 943 of file morale.cpp.
 {
     const auto update_body_part = [&]( body_part_data & bp_data ) {
         bp_data.filthy -= 1;
     };
     const body_part_set covered( it.get_covered_body_parts() );
     if( covered.any() ) {
         for( const bodypart_id &bp : get_player_character().get_all_body_parts() ) {
             if( covered.test( bp.id() ) ) {
                 update_body_part( body_parts[bp] );
             }
         }
     } else {
         update_body_part( no_body_part );
     }
     update_squeamish_penalty();
 }
References body_part_set::any(), body_parts, bp, item::get_covered_body_parts(), get_player_character(), int_id< T >::id(), no_body_part, body_part_set::test(), and update_squeamish_penalty().
operator=() [1/2]
player_morale& player_morale::operator= (const player_morale &) default
operator=() [2/2]
player_morale& player_morale::operator= (player_morale &&) default
remove()
void player_morale::remove (const morale_type & type, const itype * item_type = nullptr)
Removes specified morale.
Definition at line 381 of file morale.cpp.
 {
     remove_if( [ type, item_type ]( const morale_point & m ) -> bool {
         return m.matches( type, item_type );
     } );
 }
References player_morale::morale_point::matches(), remove_if(), and type.
remove_expired()
void player_morale::remove_expired () protected
Definition at line 389 of file morale.cpp.
 {
     remove_if( []( const morale_point & m ) -> bool {
         return m.is_expired();
     } );
 }
References player_morale::morale_point::is_expired(), and remove_if().
Referenced by add(), and decay().
remove_if()
void player_morale::remove_if (const std::function< bool(const morale_point &)> & func) protected
Definition at line 371 of file morale.cpp.
 {
     const auto new_end = std::remove_if( points.begin(), points.end(), func );
     if( new_end != points.end() ) {
         points.erase( new_end, points.end() );
         invalidate();
     }
 }
References invalidate(), and points.
Referenced by remove(), and remove_expired().
set_mutation()
void player_morale::set_mutation (const trait_id & mid, bool active) protected
Definition at line 897 of file morale.cpp.
 {
     const auto &mutation = mutations.find( mid );
     if( mutation != mutations.end() ) {
         mutation->second.set_active( this, active );
     }
 }
References active, mutation, and mutations.
Referenced by on_mutation_gain(), and on_mutation_loss().
set_permanent()
void player_morale::set_permanent (const morale_type & type, int bonus, const itype * item_type = nullptr)
Sets the new level for the permanent morale, or creates one.
Definition at line 356 of file morale.cpp.
 {
     add( type, bonus, bonus, 0_turns, 0_turns, true, item_type );
 }
References add(), and type.
Referenced by player_morale(), update_constrained_penalty(), update_masochist_bonus(), update_radiophile_bonus(), update_squeamish_penalty(), and update_stylish_bonus().
set_prozac()
void player_morale::set_prozac (bool new_took_prozac) protected
Definition at line 1036 of file morale.cpp.
 {
     if( took_prozac != new_took_prozac ) {
         took_prozac = new_took_prozac;
         update_masochist_bonus();
         invalidate();
     }
 }
References invalidate(), took_prozac, and update_masochist_bonus().
Referenced by on_effect_int_change().
set_prozac_bad()
void player_morale::set_prozac_bad (bool new_took_prozac_bad) protected
Definition at line 1045 of file morale.cpp.
 {
     if( took_prozac_bad != new_took_prozac_bad ) {
         took_prozac_bad = new_took_prozac_bad;
         invalidate();
     }
 }
References invalidate(), and took_prozac_bad.
Referenced by on_effect_int_change().
set_stylish()
void player_morale::set_stylish (bool new_stylish) protected
Definition at line 1053 of file morale.cpp.
 {
     if( stylish != new_stylish ) {
         stylish = new_stylish;
         update_stylish_bonus();
     }
 }
References stylish, and update_stylish_bonus().
Referenced by player_morale().
set_worn()
void player_morale::set_worn (const item & it, bool worn) protected
Definition at line 979 of file morale.cpp.
 {
     const bool fancy = it.has_flag( STATIC( flag_id( "FANCY" ) ) );
     const bool super_fancy = it.has_flag( STATIC( flag_id( "SUPER_FANCY" ) ) );
     const bool filthy_gear = it.has_flag( STATIC( flag_id( "FILTHY" ) ) );
     const bool integrated = it.has_flag( STATIC( flag_id( "INTEGRATED" ) ) );
     const int sign = worn ? 1 : -1;
     const auto update_body_part = [&]( body_part_data & bp_data ) {
         if( fancy || super_fancy ) {
             bp_data.fancy += sign;
         }
         if( filthy_gear ) {
             bp_data.filthy += sign;
         }
         // If armor is integrated (Subdermal CBM, Skin armor mutation) don't count it as covering
         if( !integrated ) {
             bp_data.covered += sign;
         }
     };
     const body_part_set covered( it.get_covered_body_parts() );
     if( covered.any() ) {
         for( const bodypart_id &bp : get_player_character().get_all_body_parts() ) {
             if( covered.test( bp.id() ) ) {
                 update_body_part( body_parts[bp] );
             }
         }
     } else {
         update_body_part( no_body_part );
     }
     if( super_fancy ) {
         const itype_id id = it.typeId();
         const auto iter = super_fancy_items.find( id );
         if( iter != super_fancy_items.end() ) {
             iter->second += sign;
             if( iter->second == 0 ) {
                 super_fancy_items.erase( iter );
             }
         } else if( worn ) {
             super_fancy_items[id] = 1;
         } else {
             debugmsg( "Tried to take off \"%s\" which isn't worn.", id.c_str() );
         }
     }
     if( fancy || super_fancy ) {
         update_stylish_bonus();
     }
     if( filthy_gear ) {
         update_squeamish_penalty();
     }
     update_constrained_penalty();
 }
References body_part_set::any(), body_parts, bp, debugmsg, flag_id, item::get_covered_body_parts(), get_player_character(), item::has_flag(), base_camps::id, int_id< T >::id(), no_body_part, iexamine::sign(), STATIC, super_fancy_items, body_part_set::test(), item::typeId(), update_constrained_penalty(), update_squeamish_penalty(), and update_stylish_bonus().
Referenced by on_item_takeoff(), on_item_wear(), and on_worn_item_transform().
store()
void player_morale::store (JsonOut & jsout) const
Definition at line 3904 of file savegame_json.cpp.
 {
     jsout.member( "morale", points );
 }
References JsonOut::member().
update_bodytemp_penalty()
void player_morale::update_bodytemp_penalty (const time_duration & ticks) protected
Definition at line 1111 of file morale.cpp.
 {
     float max_cold_penalty = 0.0f;
     float max_hot_penalty = 0.0f;
     for( const std::pair<const bodypart_id, body_part_data> &bpt : body_parts ) {
         const bodypart_id bp = bpt.first;
         max_cold_penalty += body_parts[bp].cold * bp->cold_morale_mod;
         max_hot_penalty += body_parts[bp].hot * bp->hot_morale_mod;
     }
     if( max_cold_penalty != 0.0f ) {
         add( MORALE_COLD, -2 * to_turns<int>( ticks ), -std::abs( max_cold_penalty ), 1_minutes, 30_seconds,
              true );
     }
     if( max_hot_penalty != 0 && !has_flag( STATIC( json_character_flag( "HEAT_IMMUNE" ) ) ) ) {
         add( MORALE_HOT, -2 * to_turns<int>( ticks ), -std::abs( max_hot_penalty ), 1_minutes, 30_seconds,
              true );
     }
 }
References abs(), add(), body_parts, bp, body_part_type::cold_morale_mod, has_flag(), body_part_type::hot_morale_mod, MORALE_COLD, MORALE_HOT, and STATIC.
Referenced by decay().
update_constrained_penalty()
void player_morale::update_constrained_penalty () protected
Definition at line 1130 of file morale.cpp.
 {
     const auto bp_pen = [ this ]( bodypart_id bp, int pen ) -> int {
         return ( body_parts[bp].covered > 0 ) ? pen : 0;
     };
     int pen = 0;
     if( has_mutation( trait_VANITY ) ) {
         pen += bp_pen( bodypart_id( "mouth" ), 5 );
         pen += bp_pen( bodypart_id( "eyes" ), 5 );
     }
     if( has_mutation( trait_FLOWERS ) ) {
         pen += bp_pen( bodypart_id( "head" ), 10 );
     }
     if( has_mutation( trait_ROOTS1 ) || has_mutation( trait_ROOTS2 ) ||
         has_mutation( trait_ROOTS3 ) || has_mutation( trait_CHLOROMORPH ) ) {
         pen += bp_pen( bodypart_id( "foot_l" ), 5 );
         pen += bp_pen( bodypart_id( "foot_r" ), 5 );
     }
     if( has_mutation( trait_LEAVES2 ) || has_mutation( trait_LEAVES3 ) ) {
         pen += bp_pen( bodypart_id( "arm_l" ), 5 );
         pen += bp_pen( bodypart_id( "arm_r" ), 5 );
     }
     set_permanent( MORALE_PERM_CONSTRAINED, -std::min( pen, 10 ) );
 }
References body_parts, bp, has_mutation(), min(), MORALE_PERM_CONSTRAINED, set_permanent(), trait_CHLOROMORPH, trait_FLOWERS, trait_LEAVES2, trait_LEAVES3, trait_ROOTS1, trait_ROOTS2, trait_ROOTS3, and trait_VANITY.
Referenced by player_morale(), and set_worn().
update_masochist_bonus()
void player_morale::update_masochist_bonus () protected
Definition at line 1078 of file morale.cpp.
 {
     const bool amateur_masochist = has_mutation( trait_MASOCHIST );
     const bool advanced_masochist = has_mutation( trait_MASOCHIST_MED ) ||
                                     has_mutation( trait_CENOBITE );
     const bool any_masochist = amateur_masochist || advanced_masochist;
     int bonus = 0;
     if( any_masochist ) {
         bonus = perceived_pain;
         if( amateur_masochist ) {
             bonus = std::min( bonus, 20 );
         }
         if( took_prozac ) {
             bonus = bonus / 2;
         }
     }
     set_permanent( MORALE_PERM_MASOCHIST, bonus );
 }
References has_mutation(), min(), MORALE_PERM_MASOCHIST, perceived_pain, set_permanent(), took_prozac, trait_CENOBITE, trait_MASOCHIST, and trait_MASOCHIST_MED.
Referenced by on_stat_change(), player_morale(), and set_prozac().
update_radiophile_bonus()
void player_morale::update_radiophile_bonus () protected
Definition at line 1099 of file morale.cpp.
 {
     const bool is_radiophile = has_mutation( trait_RADIOPHILE );
     int bonus = 0;
     if( is_radiophile ) {
         bonus = radiation / 20;
     }
     set_permanent( MORALE_PERM_RADIOPHILE, bonus );
 }
References has_mutation(), MORALE_PERM_RADIOPHILE, radiation, set_permanent(), and trait_RADIOPHILE.
Referenced by on_stat_change(), and player_morale().
update_squeamish_penalty()
void player_morale::update_squeamish_penalty () protected
Definition at line 1156 of file morale.cpp.
 {
     int penalty = 0;
     for( const std::pair<const bodypart_id, body_part_data> &bpt : body_parts ) {
         if( bpt.second.filthy > 0 ) {
             penalty += bpt.first->squeamish_penalty;
         }
     }
     penalty += 2 * std::min( static_cast<int>( no_body_part.filthy ), 3 );
     set_permanent( MORALE_PERM_FILTHY, -penalty );
 }
References body_parts, player_morale::body_part_data::filthy, min(), MORALE_PERM_FILTHY, no_body_part, and set_permanent().
Referenced by on_worn_item_washed(), and set_worn().
update_stylish_bonus()
void player_morale::update_stylish_bonus () protected
Definition at line 1061 of file morale.cpp.
 {
     int bonus = 0;
     if( stylish ) {
         float tmp_bonus = 0.0f;
         for( const std::pair<const bodypart_id, body_part_data> &bpt : body_parts ) {
             if( bpt.second.fancy > 0 ) {
                 tmp_bonus += bpt.first->stylish_bonus;
             }
         }
         bonus = std::min( static_cast<int>( 2 * super_fancy_items.size() ) +
                           2 * std::min( static_cast<int>( no_body_part.fancy ), 3 ) + static_cast<int>( tmp_bonus ), 20 );
     }
     set_permanent( MORALE_PERM_FANCY, bonus );
 }
References body_parts, player_morale::body_part_data::fancy, min(), MORALE_PERM_FANCY, no_body_part, set_permanent(), stylish, and super_fancy_items.
Referenced by set_stylish(), and set_worn().
Member Data Documentation
body_parts
std::map<bodypart_id, body_part_data> player_morale::body_parts private
Definition at line 178 of file morale.h.
Referenced by clear(), on_effect_int_change(), on_worn_item_washed(), set_worn(), update_bodytemp_penalty(), update_constrained_penalty(), update_squeamish_penalty(), and update_stylish_bonus().
level
int player_morale::level mutable private
Definition at line 204 of file morale.h.
Referenced by get_level().
level_is_valid
bool player_morale::level_is_valid mutable private
Definition at line 205 of file morale.h.
Referenced by get_level(), and invalidate().
mutations
std::map<trait_id, mutation_data> player_morale::mutations private
Definition at line 199 of file morale.h.
Referenced by clear(), has_mutation(), player_morale(), and set_mutation().
no_body_part
body_part_data player_morale::no_body_part private
Definition at line 179 of file morale.h.
Referenced by clear(), on_worn_item_washed(), set_worn(), update_squeamish_penalty(), and update_stylish_bonus().
perceived_pain
int player_morale::perceived_pain private
Definition at line 210 of file morale.h.
Referenced by consistent_with(), get_perceived_pain(), on_stat_change(), and update_masochist_bonus().
points
std::vector<morale_point> player_morale::points private
Definition at line 162 of file morale.h.
Referenced by add(), calculate_percentage(), clear(), consistent_with(), decay(), display(), get_level(), get_total_negative_value(), get_total_positive_value(), has(), and remove_if().
radiation
int player_morale::radiation private
Definition at line 211 of file morale.h.
Referenced by consistent_with(), on_stat_change(), and update_radiophile_bonus().
stylish
bool player_morale::stylish private
Definition at line 209 of file morale.h.
Referenced by clear(), consistent_with(), set_stylish(), and update_stylish_bonus().
super_fancy_items
std::map<itype_id, int> player_morale::super_fancy_items private
Definition at line 201 of file morale.h.
Referenced by clear(), set_worn(), and update_stylish_bonus().
took_prozac
bool player_morale::took_prozac private
Definition at line 207 of file morale.h.
Referenced by clear(), consistent_with(), get_level(), set_prozac(), and update_masochist_bonus().
took_prozac_bad
bool player_morale::took_prozac_bad private
Definition at line 208 of file morale.h.
Referenced by clear(), consistent_with(), get_level(), and set_prozac_bad().
The documentation for this class was generated from the following files:
src/morale.h
src/morale.cpp
src/savegame_json.cpp