Cataclysm DDA: jmapgen_nested::neighbor_flag_check Class Reference
jmapgen_nested::neighbor_flag_check Class Reference
Public Member Functions
neighbor_flag_check (const JsonObject &jsi)
bool test (const mapgendata &dat) const
Private Attributes
std::unordered_map< direction, cata::flat_set< oter_flags > > neighbors
Detailed Description
Definition at line 3616 of file mapgen.cpp.
Constructor & Destructor Documentation
neighbor_flag_check()
jmapgen_nested::neighbor_flag_check::neighbor_flag_check (const JsonObject & jsi) inline explicit
Definition at line 3621 of file mapgen.cpp.
{
                     for( direction dir : all_enum_values<direction>() ) {
                         cata::flat_set<oter_flags> dir_neighbors;
                         std::string location = io::enum_to_string( dir );
                         optional( jsi, false, location, dir_neighbors );
                         if( !dir_neighbors.empty() ) {
                             neighbors[dir] = std::move( dir_neighbors );
                         }
                     }
                 }
References io::enum_to_string(), mapgen_defer::jsi, location, neighbors, and optional().
Member Function Documentation
test()
bool jmapgen_nested::neighbor_flag_check::test (const mapgendata & dat) const inline
Definition at line 3632 of file mapgen.cpp.
{
                     for( const std::pair<const direction, cata::flat_set<oter_flags>> &p :
                          neighbors ) {
                         const direction dir = p.first;
                         const cata::flat_set<oter_flags> &allowed_flags = p.second;
                         cata_assert( !allowed_flags.empty() );
                         bool this_direction_has_flag = false;
                         for( const oter_flags &allowed_flag : allowed_flags ) {
                             this_direction_has_flag |=
                                 dat.neighbor_at( dir )->has_flag( allowed_flag );
                         }
                         if( !this_direction_has_flag ) {
                             return false;
                         }
                     }
                     return true;
                 }
References cata_assert, oter_t::has_flag(), mapgendata::neighbor_at(), and neighbors.
Referenced by jmapgen_nested::get_entries().
Member Data Documentation
neighbors
std::unordered_map<direction, cata::flat_set<oter_flags> > jmapgen_nested::neighbor_flag_check::neighbors private
Definition at line 3619 of file mapgen.cpp.
Referenced by neighbor_flag_check(), and test().
The documentation for this class was generated from the following file:
src/mapgen.cpp