Cataclysm DDA: nc_color Class Reference
nc_color Class Reference
#include <color.h>
Public Member Functions
nc_color ()
int to_color_pair_index () const
operator int () const
int to_int () const
int get_index () const
nc_color bold () const
bool is_bold () const
nc_color blink () const
bool is_blink () const
void serialize (JsonOut &jsout) const
void deserialize (int value)
Static Public Member Functions
static nc_color from_color_pair_index (int index)
Private Member Functions
nc_color (const int a)
nc_color (const int a, const int i)
Private Attributes
int attribute_value
int index
Friends
bool operator== (const nc_color &l, const nc_color &r)
bool operator!= (const nc_color &l, const nc_color &r)
bool operator< (const nc_color &l, const nc_color &r)
Detailed Description
Definition at line 347 of file color.h.
Constructor & Destructor Documentation
nc_color() [1/3]
nc_color::nc_color (const int a) inline explicit private
Definition at line 354 of file color.h.
 : attribute_value( a ), index( 0 ) { }
nc_color() [2/3]
nc_color::nc_color (const int a, const int i) inline explicit private
Definition at line 355 of file color.h.
 : attribute_value( a ), index( i ) { }
nc_color() [3/3]
nc_color::nc_color () inline
Definition at line 358 of file color.h.
 : attribute_value( 0 ), index( 0 ) { }
Referenced by blink(), bold(), and from_color_pair_index().
Member Function Documentation
blink()
nc_color nc_color::blink () const
Definition at line 523 of file ncurses_def.cpp.
 {
     return nc_color( attribute_value | A_BLINK, index );
 }
References attribute_value, index, and nc_color().
bold()
nc_color nc_color::bold () const
Definition at line 513 of file ncurses_def.cpp.
 {
     return nc_color( attribute_value | A_BOLD, index );
 }
References attribute_value, index, and nc_color().
deserialize()
void nc_color::deserialize (int value)
Definition at line 38 of file color.cpp.
 {
     attribute_value = value;
 }
References attribute_value.
from_color_pair_index()
nc_color nc_color::from_color_pair_index (int index) static
Definition at line 503 of file ncurses_def.cpp.
 {
     return nc_color( COLOR_PAIR( index ), index );
 }
References index, and nc_color().
Referenced by color_manager::load_default().
get_index()
int nc_color::get_index () const inline
Definition at line 373 of file color.h.
{
             return index;
         }
References index.
Referenced by cataimgui::window::draw_colored_text().
is_blink()
bool nc_color::is_blink () const
Definition at line 528 of file ncurses_def.cpp.
 {
     return attribute_value & A_BLINK;
 }
References attribute_value.
is_bold()
bool nc_color::is_bold () const
Definition at line 518 of file ncurses_def.cpp.
 {
     return attribute_value & A_BOLD;
 }
References attribute_value.
Referenced by cataimgui::window::draw_colored_text().
operator int()
nc_color::operator int () const inline explicit
Definition at line 366 of file color.h.
{
             return attribute_value;
         }
References attribute_value.
serialize()
void nc_color::serialize (JsonOut & jsout) const
Definition at line 33 of file color.cpp.
 {
     jsout.write( attribute_value );
 }
References attribute_value, and JsonOut::write().
to_color_pair_index()
int nc_color::to_color_pair_index () const
Definition at line 508 of file ncurses_def.cpp.
 {
     return ( attribute_value & 0x03fe0000 ) >> 17;
 }
References attribute_value.
to_int()
int nc_color::to_int () const inline
Definition at line 369 of file color.h.
{
             return attribute_value;
         }
References attribute_value.
Referenced by bgcolor_from_string(), color_from_string(), color_manager::get_invert(), disp_bodygraph_cache::is_valid_for(), color_manager::name_to_color(), catacurses::wattroff(), and catacurses::wattron().
Friends And Related Function Documentation
operator!=
bool operator!= (const nc_color & l, const nc_color & r) friend
Definition at line 390 of file color.h.
{
             return !( l == r );
         }
operator<
bool operator< (const nc_color & l, const nc_color & r) friend
Definition at line 393 of file color.h.
{
             return l.attribute_value < r.attribute_value;
         }
operator==
bool operator== (const nc_color & l, const nc_color & r) friend
Definition at line 387 of file color.h.
{
             return l.attribute_value == r.attribute_value;
         }
Member Data Documentation
attribute_value
int nc_color::attribute_value private
Definition at line 351 of file color.h.
Referenced by blink(), bold(), deserialize(), is_blink(), is_bold(), operator int(), serialize(), to_color_pair_index(), and to_int().
index
int nc_color::index private
Definition at line 352 of file color.h.
Referenced by blink(), bold(), from_color_pair_index(), and get_index().
The documentation for this class was generated from the following files:
src/color.h
src/color.cpp
src/ncurses_def.cpp