Cataclysm DDA: json_talk_response Class Reference
json_talk_response Class Reference
An extended response.
#include <dialogue.h>
Public Member Functions
json_talk_response ()=default
json_talk_response (const JsonObject &jo)
const talk_response & get_actual_response () const
bool has_condition () const
bool gen_responses (dialogue &d, bool switch_done) const
Callback from json_talk_topic::gen_responses, see there.
bool gen_repeat_response (dialogue &d, const itype_id &item_id, bool switch_done) const
Private Member Functions
void load_condition (const JsonObject &jo)
bool test_condition (dialogue &d) const
Private Attributes
talk_response actual_response
std::function< bool(dialogue &)> condition
bool has_condition_ = false
bool is_switch = false
bool is_default = false
translation failure_explanation
std::string failure_topic
Detailed Description
An extended response.
It contains the response itself and a condition, so we can include the response if, and only if the condition is met.
Definition at line 357 of file dialogue.h.
Constructor & Destructor Documentation
json_talk_response() [1/2]
json_talk_response::json_talk_response () default
json_talk_response() [2/2]
json_talk_response::json_talk_response (const JsonObject & jo) explicit
Definition at line 6719 of file npctalk.cpp.
     : actual_response( jo )
 {
     load_condition( jo );
 }
References load_condition().
Member Function Documentation
gen_repeat_response()
bool json_talk_response::gen_repeat_response (dialogue & d, const itype_id & item_id, bool switch_done) const
Definition at line 6772 of file npctalk.cpp.
 {
     if( !is_switch || !switch_done ) {
         if( test_condition( d ) ) {
             talk_response result = actual_response;
             result.success.next_topic.item_type = item_id;
             result.failure.next_topic.item_type = item_id;
             d.responses.insert( d.responses.begin(), result );
             return is_switch && !is_default;
         }
     }
     return false;
 }
References actual_response, talk_response::failure, is_default, is_switch, talk_topic::item_type, talk_effect_t::next_topic, dialogue::responses, talk_response::success, and test_condition().
gen_responses()
bool json_talk_response::gen_responses (dialogue & d, bool switch_done) const
Callback from json_talk_topic::gen_responses, see there.
Definition at line 6749 of file npctalk.cpp.
 {
     if( !is_switch || !switch_done ) {
         if( test_condition( d ) ) {
             d.responses.emplace_back( actual_response );
             return is_switch && !is_default;
         } else if( !failure_explanation.empty() || !failure_topic.empty() ) {
             // build additional talk responses for failed options with an explanation if details are given
             talk_response tr = talk_response();
             tr.truetext = no_translation(
                               string_format( pgettext( "failure_explanation: actual_response", "*%s: %s" ),
                                              failure_explanation.translated(), actual_response.truetext.translated() ) );
             if( !failure_topic.empty() ) {
                 // Default is TALK_NONE otherwise go to the failure topic provided
                 tr.success.next_topic = talk_topic( failure_topic );
             }
             d.responses.emplace_back( tr );
         }
     }
     return false;
 }
References actual_response, translation::empty(), failure_explanation, failure_topic, is_default, is_switch, talk_effect_t::next_topic, no_translation(), pgettext, dialogue::responses, string_format(), talk_response::success, test_condition(), translation::translated(), and talk_response::truetext.
get_actual_response()
const talk_response & json_talk_response::get_actual_response () const
Definition at line 6744 of file npctalk.cpp.
 {
     return actual_response;
 }
References actual_response.
has_condition()
bool json_talk_response::has_condition () const inline
Definition at line 379 of file dialogue.h.
{
             return has_condition_;
         }
References has_condition_.
load_condition()
void json_talk_response::load_condition (const JsonObject & jo) private
Definition at line 6725 of file npctalk.cpp.
 {
     has_condition_ = jo.has_member( "condition" );
     is_switch = jo.get_bool( "switch", false );
     is_default = jo.get_bool( "default", false );
     read_condition( jo, "condition", condition, true );
     optional( jo, true, "failure_explanation", failure_explanation );
     optional( jo, true, "failure_topic", failure_topic );
 }
References condition, failure_explanation, failure_topic, JsonObject::get_bool(), has_condition_, JsonObject::has_member(), is_default, is_switch, optional(), and read_condition().
Referenced by json_talk_response().
test_condition()
bool json_talk_response::test_condition (dialogue & d) const private
Definition at line 6736 of file npctalk.cpp.
 {
     if( condition ) {
         return condition( d );
     }
     return true;
 }
References condition.
Referenced by gen_repeat_response(), and gen_responses().
Member Data Documentation
actual_response
talk_response json_talk_response::actual_response private
Definition at line 360 of file dialogue.h.
Referenced by gen_repeat_response(), gen_responses(), and get_actual_response().
condition
std::function<bool(dialogue &)> json_talk_response::condition private
Definition at line 361 of file dialogue.h.
Referenced by load_condition(), and test_condition().
failure_explanation
translation json_talk_response::failure_explanation private
Definition at line 367 of file dialogue.h.
Referenced by gen_responses(), and load_condition().
failure_topic
std::string json_talk_response::failure_topic private
Definition at line 369 of file dialogue.h.
Referenced by gen_responses(), and load_condition().
has_condition_
bool json_talk_response::has_condition_ = false private
Definition at line 362 of file dialogue.h.
Referenced by has_condition(), and load_condition().
is_default
bool json_talk_response::is_default = false private
Definition at line 364 of file dialogue.h.
Referenced by gen_repeat_response(), gen_responses(), and load_condition().
is_switch
bool json_talk_response::is_switch = false private
Definition at line 363 of file dialogue.h.
Referenced by gen_repeat_response(), gen_responses(), and load_condition().
The documentation for this class was generated from the following files:
src/dialogue.h
src/npctalk.cpp