Cataclysm DDA: map_stack Class Reference
map_stack Class Reference
#include <map.h>
Public Member Functions
map_stack (cata::colony< item > *newstack, tripoint newloc, map *neworigin)
void insert (const item &newitem) override
iterator erase (const_iterator it) override
int count_limit () const override
Maximum number of items allowed here.
units::volume max_volume () const override
Maximum volume allowed here.
Public Member Functions inherited from item_stack
item_stack (cata::colony< item > *items)
virtual ~item_stack ()=default
size_t size () const
bool empty () const
virtual void clear ()
item & only_item ()
iterator get_iterator_from_pointer (item *it)
iterator get_iterator_from_index (size_t idx)
size_t get_index_from_iterator (const const_iterator &it)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
units::volume stored_volume () const
Total volume of the items here.
units::volume free_volume () const
int amount_can_fit (const item &it) const
Returns how many of the specified item (or how many charges if it's counted by charges) could be added without violating either the volume or itemcount limits.
item * stacks_with (const item &it)
Return the item (or nullptr) that stacks with the argument.
const item * stacks_with (const item &it) const
std::list< item > use_charges (const itype_id &type, int &quantity, const tripoint &pos, const std::function< bool(const item &)> &filter, bool in_tools=false)
Consumes specified charges (or fewer) from the stack.
Private Attributes
tripoint location
map * myorigin
Additional Inherited Members
Public Types inherited from item_stack
using iterator = cata::colony< item >::iterator
using const_iterator = cata::colony< item >::const_iterator
using reverse_iterator = cata::colony< item >::reverse_iterator
using const_reverse_iterator = cata::colony< item >::const_reverse_iterator
Protected Attributes inherited from item_stack
cata::colony< item > * items
Detailed Description
Definition at line 106 of file map.h.
Constructor & Destructor Documentation
map_stack()
map_stack::map_stack (cata::colony< item > * newstack, tripoint newloc, map * neworigin) inline
Definition at line 112 of file map.h.
                                                                                  :
             item_stack( newstack ), location( newloc ), myorigin( neworigin ) {}
Member Function Documentation
count_limit()
int map_stack::count_limit () const inline override virtual
Maximum number of items allowed here.
Implements item_stack.
Definition at line 116 of file map.h.
{
             return MAX_ITEM_IN_SQUARE;
         }
References MAX_ITEM_IN_SQUARE.
erase()
map_stack::iterator map_stack::erase (map_stack::const_iterator it) override virtual
Implements item_stack.
Definition at line 219 of file map.cpp.
 {
     return myorigin->i_rem( location, it );
 }
References map::i_rem(), location, and myorigin.
Referenced by Character::activate_bionic(), iexamine::arcfurnace_full(), map::bash_items(), MapExtras::burned_ground_parser(), complete_construction(), iexamine::compost_empty(), Character::consume_charges(), displace_items_except_one_liquid(), basecamp::distribute_food(), fetch_activity(), field_processor_fd_push_items(), game::forced_door_closing(), fromPumpFuel(), iexamine::fvat_empty(), iexamine::gaspump(), map::grow_plant(), liquid_handler::handle_liquid_from_ground(), iexamine::kiln_full(), talk_function::loot_building(), map::mop_spills(), vehicle::operate_reaper(), iexamine::quern_examine(), reload_furniture(), iexamine::smoker_options(), iexamine::toPumpFuel(), use_charges_from_furn(), and iexamine::vending().
insert()
void map_stack::insert (const item & newitem) override virtual
Implements item_stack.
Definition at line 224 of file map.cpp.
 {
     myorigin->add_item_or_charges( location, newitem );
 }
References map::add_item_or_charges(), location, and myorigin.
Referenced by board_up(), iexamine::compost_empty(), displace_items_except_one_liquid(), map::drop_furniture(), iexamine::fvat_empty(), game::grabbed_furn_move(), and talk_function::loot_building().
max_volume()
units::volume map_stack::max_volume () const override virtual
Maximum volume allowed here.
Implements item_stack.
Definition at line 229 of file map.cpp.
 {
     if( !myorigin->inbounds( location ) ) {
         return 0_ml;
     } else if( myorigin->has_furn( location ) ) {
         return myorigin->furn( location ).obj().max_volume;
     }
     return myorigin->ter( location ).obj().max_volume;
 }
References map::furn(), map::has_furn(), map::inbounds(), location, map_data_common_t::max_volume, myorigin, int_id< T >::obj(), and map::ter().
Referenced by map::max_volume().
Member Data Documentation
location
tripoint map_stack::location private
Definition at line 109 of file map.h.
Referenced by erase(), insert(), and max_volume().
myorigin
map* map_stack::myorigin private
Definition at line 110 of file map.h.
Referenced by erase(), insert(), and max_volume().
The documentation for this class was generated from the following files:
src/map.h
src/map.cpp