Cataclysm DDA: uimenu Class Reference
uimenu Class Reference
Hack ui list to behave as a multi column menu.
#include <ui.h>
Classes
struct col
Public Member Functions
uimenu (int columns)
void addentry (int retval, bool enabled, const std::vector< std::string > &col_content)
void set_selected (int index)
void set_title (const std::string &title)
int query ()
Private Member Functions
void finalize_addentries ()
Called in query to calculate sizes for multiple columns.
Private Attributes
std::vector< col > cols
uilist menu
int col_count
int suggest_width = 74
Detailed Description
Hack ui list to behave as a multi column menu.
Definition at line 534 of file ui.h.
Constructor & Destructor Documentation
uimenu()
uimenu::uimenu (int columns) inline explicit
Definition at line 537 of file ui.h.
{
             cata_assert( columns >= 1 );
             col_count = columns;
         }
References cata_assert, and col_count.
Member Function Documentation
addentry()
void uimenu::addentry (int retval, bool enabled, const std::vector< std::string > & col_content)
Parameters
retval return value of this option when selected during menu query
enable is entry enabled. disabled entries will be grayed out and won't be selectable
col_content each string will be displayed on the entry's respective column
Definition at line 1289 of file ui.cpp.
 {
     cata_assert( static_cast<int>( col_content.size() ) == col_count );
     cols.emplace_back( retval, enabled, col_content );
 }
References cata_assert, and enabled.
Referenced by choose_crafter().
finalize_addentries()
void uimenu::finalize_addentries () private
Called in query to calculate sizes for multiple columns.
Definition at line 1295 of file ui.cpp.
 {
     menu.entries.clear();
     std::vector<int> maxes( col_count, 0 );
     // get max width of each column
     for( col &c : cols ) {
         int i = 0;
         for( const std::string &entry : c.col_content ) {
             maxes[i] = std::max( maxes[i], utf8_width( entry, true ) );
             ++i;
         }
     }
     // adding spacing between columns
     int free_width = suggest_width - std::reduce( maxes.begin(), maxes.end() );
     int spacing = std::min( 3, col_count > 1 ? free_width / ( col_count - 1 ) : 0 );
     if( spacing > 0 ) {
         for( int i = 0; i < col_count - 1; ++i ) {
             maxes[i] += spacing;
         }
     }
     for( col &c : cols ) {
         std::string row;
         int i = 0;
         for( const std::string &entry : c.col_content ) {
             // Pad with spaces
             // Add length of tags to number of spaces to pad with
             // That is length(entry_with_tags) - length(entry_without_tags)
             // Otherwise the entry padding will be shorter by number of chars in tags
             int entry_len_plus_tags = maxes[i] + utf8_width( entry, false ) - utf8_width( entry, true );
             row += string_format( "%-*s", entry_len_plus_tags, entry );
             ++i;
         }
         menu.addentry( c.retval, c.enabled, -1, row );
     }
 }
References c, max(), min(), string_format(), and utf8_width().
query()
int uimenu::query ()
Definition at line 1342 of file ui.cpp.
 {
     finalize_addentries();
     menu.query();
     return menu.ret;
 }
Referenced by choose_crafter().
set_selected()
void uimenu::set_selected (int index)
Definition at line 1332 of file ui.cpp.
 {
     menu.selected = index;
 }
Referenced by choose_crafter().
set_title()
void uimenu::set_title (const std::string & title)
Definition at line 1337 of file ui.cpp.
 {
     menu.title = title;
 }
References uilist::title.
Referenced by choose_crafter().
Member Data Documentation
col_count
int uimenu::col_count private
Definition at line 566 of file ui.h.
Referenced by uimenu().
cols
std::vector<col> uimenu::cols private
Definition at line 564 of file ui.h.
menu
uilist uimenu::menu private
Definition at line 565 of file ui.h.
suggest_width
int uimenu::suggest_width = 74 private
Definition at line 568 of file ui.h.
The documentation for this class was generated from the following files:
src/ui.h
src/ui.cpp