Cataclysm DDA: item::craft_data Class Reference
item::craft_data Class Reference
Data for items that represent in-progress crafts.
Public Member Functions
void serialize (JsonOut &jsout) const
void deserialize (const JsonObject &obj)
Public Attributes
const recipe * making = nullptr
int next_failure_point = -1
std::vector< item_comp > comps_used
bool tools_to_continue = false
int batch_size = -1
std::vector< comp_selection< tool_comp > > cached_tool_selections
std::optional< units::mass > cached_weight
std::optional< units::volume > cached_volume
bool disassembly = false
Detailed Description
Data for items that represent in-progress crafts.
Definition at line 3110 of file item.h.
Member Function Documentation
deserialize()
void item::craft_data::deserialize (const JsonObject & obj)
Definition at line 2719 of file savegame_json.cpp.
 {
     obj.allow_omitted_members();
     std::string recipe_string = obj.get_string( "making" );
     disassembly = obj.get_bool( "disassembly", false );
     if( disassembly ) {
         making = &recipe_dictionary::get_uncraft( itype_id( recipe_string ) );
     } else {
         recipe_id rid( recipe_string );
         if( !rid.is_valid() ) {
             DebugLog( DebugLevel::D_WARNING, DebugClass::D_MAIN )
                     << "item::craft_data deserialized invalid recipe_id '" << recipe_string << "'";
             rid = recipe_id::NULL_ID();
         }
         making = &rid.obj();
     }
     obj.read( "comps_used", comps_used );
     next_failure_point = obj.get_int( "next_failure_point", -1 );
     tools_to_continue = obj.get_bool( "tools_to_continue", false );
     batch_size = obj.get_int( "batch_size", -1 );
     obj.read( "cached_tool_selections", cached_tool_selections );
 }
References JsonObject::allow_omitted_members(), D_MAIN, D_WARNING, DebugLog(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_string(), recipe_dictionary::get_uncraft(), string_id< T >::is_valid(), itype_id, string_id< recipe >::NULL_ID(), string_id< T >::obj(), and JsonObject::read().
serialize()
void item::craft_data::serialize (JsonOut & jsout) const
Definition at line 2706 of file savegame_json.cpp.
 {
     jsout.start_object();
     jsout.member( "making", making->ident().str() );
     jsout.member( "disassembly", disassembly );
     jsout.member( "comps_used", comps_used );
     jsout.member( "next_failure_point", next_failure_point );
     jsout.member( "tools_to_continue", tools_to_continue );
     jsout.member( "batch_size", batch_size );
     jsout.member( "cached_tool_selections", cached_tool_selections );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
batch_size
int item::craft_data::batch_size = -1
Definition at line 3118 of file item.h.
cached_tool_selections
std::vector<comp_selection<tool_comp> > item::craft_data::cached_tool_selections
Definition at line 3119 of file item.h.
cached_volume
std::optional<units::volume> item::craft_data::cached_volume
Definition at line 3121 of file item.h.
cached_weight
std::optional<units::mass> item::craft_data::cached_weight
Definition at line 3120 of file item.h.
comps_used
std::vector<item_comp> item::craft_data::comps_used
Definition at line 3115 of file item.h.
disassembly
bool item::craft_data::disassembly = false
Definition at line 3124 of file item.h.
making
const recipe* item::craft_data::making = nullptr
Definition at line 3113 of file item.h.
next_failure_point
int item::craft_data::next_failure_point = -1
Definition at line 3114 of file item.h.
tools_to_continue
bool item::craft_data::tools_to_continue = false
Definition at line 3117 of file item.h.
The documentation for this class was generated from the following files:
src/item.h
src/savegame_json.cpp