Cataclysm DDA: place_trap_actor Class Reference
place_trap_actor Class Reference
#include <iuse_actor.h>
Classes
struct data
Public Member Functions
bool is_allowed (Character &p, const tripoint &pos, const std::string &name) const
place_trap_actor (const std::string &type="place_trap")
~place_trap_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
bool allow_underwater = false
Whether one can place the trap when underwater.
bool allow_under_player = false
Whether one can place the trap directly under the character itself.
bool needs_solid_neighbor = false
Whether the trap needs solid neighbor squares (e.g.
ter_str_id needs_neighbor_terrain
Contains a terrain id of the terrain that must exist in a neighbor square to allow placing this trap.
data unburied_data
Data that applies to unburied traps and to traps that *can * not be buried.
translation bury_question
Contains the question asked when the player can bury the trap.
data buried_data
Data that applies to buried traps.
trap_str_id outer_layer_trap
The trap that makes up the outer layer of a multi-tile trap.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Definition at line 928 of file iuse_actor.h.
Constructor & Destructor Documentation
place_trap_actor()
place_trap_actor::place_trap_actor (const std::string & type = "place_trap") explicit
Definition at line 3754 of file iuse_actor.cpp.
                                                           :
     iuse_actor( type ), needs_neighbor_terrain( ter_str_id::NULL_ID() ),
     outer_layer_trap( trap_str_id::NULL_ID() ) {}
~place_trap_actor()
place_trap_actor::~place_trap_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > place_trap_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 3783 of file iuse_actor.cpp.
 {
     return std::make_unique<place_trap_actor>( *this );
 }
is_allowed()
bool place_trap_actor::is_allowed (Character & p, const tripoint & pos, const std::string & name) const
Definition at line 3807 of file iuse_actor.cpp.
 {
     if( !allow_under_player && pos == p.pos() ) {
         p.add_msg_if_player( m_info, _( "Yeah.  Place the %s at your feet.  Real damn smart move." ),
                              name );
         return false;
     }
     map &here = get_map();
     if( here.move_cost( pos ) != 2 ) {
         p.add_msg_if_player( m_info, _( "You can't place a %s there." ), name );
         return false;
     }
     if( needs_solid_neighbor ) {
         if( !is_solid_neighbor( pos, point_east ) && !is_solid_neighbor( pos, point_south ) &&
             !is_solid_neighbor( pos, point_south_east ) && !is_solid_neighbor( pos, point_north_east ) ) {
             p.add_msg_if_player( m_info, _( "You must place the %s between two solid tiles." ), name );
             return false;
         }
     }
     if( needs_neighbor_terrain && !has_neighbor( pos, needs_neighbor_terrain ) ) {
         p.add_msg_if_player( m_info, _( "The %s needs a %s adjacent to it." ), name,
                              needs_neighbor_terrain.obj().name() );
         return false;
     }
     const trap &existing_trap = here.tr_at( pos );
     if( !existing_trap.is_null() ) {
         if( existing_trap.can_see( pos, p ) ) {
             p.add_msg_if_player( m_info,
                                  existing_trap.is_benign()
                                  ? _( "You can't place a %s there.  It contains a deployed object already." )
                                  : _( "You can't place a %s there.  It contains a trap already." ),
                                  name );
         } else {
             p.add_msg_if_player( m_bad, _( "You trigger a %s!" ), existing_trap.name() );
             existing_trap.trigger( pos, p );
         }
         return false;
     }
     return true;
 }
References _, Character::add_msg_if_player(), allow_under_player, trap::can_see(), get_map(), has_neighbor(), trap::is_benign(), trap::is_null(), is_solid_neighbor(), m_bad, m_info, map::move_cost(), map_data_common_t::name(), trap::name(), om_direction::name(), needs_neighbor_terrain, needs_solid_neighbor, string_id< T >::obj(), point_east, point_north_east, point_south, point_south_east, Creature::pos(), math_opers::pos(), map::tr_at(), and trap::trigger().
Referenced by use().
load()
void place_trap_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 3768 of file iuse_actor.cpp.
 {
     assign( obj, "allow_underwater", allow_underwater );
     assign( obj, "allow_under_player", allow_under_player );
     assign( obj, "needs_solid_neighbor", needs_solid_neighbor );
     assign( obj, "needs_neighbor_terrain", needs_neighbor_terrain );
     assign( obj, "bury_question", bury_question );
     if( !bury_question.empty() ) {
         JsonObject buried_json = obj.get_object( "bury" );
         buried_data.load( buried_json );
     }
     unburied_data.load( obj );
     assign( obj, "outer_layer_trap", outer_layer_trap );
 }
References allow_under_player, allow_underwater, assign(), buried_data, bury_question, translation::empty(), JsonObject::get_object(), place_trap_actor::data::load(), needs_neighbor_terrain, needs_solid_neighbor, outer_layer_trap, and unburied_data.
use()
std::optional< int > place_trap_actor::use (Character * p, item & it, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 3859 of file iuse_actor.cpp.
 {
     const bool could_bury = !bury_question.empty();
     if( !allow_underwater && p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     const std::optional<tripoint> pos_ = choose_adjacent( string_format( _( "Place %s where?" ),
                                          it.tname() ) );
     if( !pos_ ) {
         return std::nullopt;
     }
     tripoint pos = *pos_;
     if( !is_allowed( *p, pos, it.tname() ) ) {
         return std::nullopt;
     }
     map &here = get_map();
     int distance_to_trap_center = unburied_data.trap.obj().get_trap_radius() +
                                   outer_layer_trap.obj().get_trap_radius() + 1;
     if( unburied_data.trap.obj().get_trap_radius() > 0 ) {
         // Math correction for multi-tile traps
         pos.x = ( pos.x - p->posx() ) * distance_to_trap_center + p->posx();
         pos.y = ( pos.y - p->posy() ) * distance_to_trap_center + p->posy();
         for( const tripoint &t : here.points_in_radius( pos, outer_layer_trap.obj().get_trap_radius(),
                 0 ) ) {
             if( !is_allowed( *p, t, it.tname() ) ) {
                 p->add_msg_if_player( m_info,
                                       _( "That trap needs a space in %d tiles radius to be clear, centered %d tiles from you." ),
                                       outer_layer_trap.obj().get_trap_radius(), distance_to_trap_center );
                 return std::nullopt;
             }
         }
     }
     const bool has_shovel = p->has_quality( qual_DIG, 3 );
     const bool is_diggable = here.has_flag( ter_furn_flag::TFLAG_DIGGABLE, pos );
     bool bury = false;
     if( could_bury && has_shovel && is_diggable ) {
         bury = query_yn( "%s", bury_question );
     }
     const place_trap_actor::data &data = bury ? buried_data : unburied_data;
     p->add_msg_if_player( m_info, data.done_message.translated(), here.tername( pos ) );
     p->practice( skill_traps, data.practice );
     p->practice_proficiency( proficiency_prof_traps,
                              time_duration::from_seconds( data.practice * 30 ) );
     p->practice_proficiency( proficiency_prof_trapsetting,
                              time_duration::from_seconds( data.practice * 30 ) );
     //Total time to set the trap will be determined by player's skills and proficiencies
     int move_cost_final = std::round( ( data.moves * std::min( 1,
                                         ( data.practice ^ 2 ) ) ) / ( p->get_skill_level( skill_traps ) <= 1 ? 1 : p->get_skill_level(
                                                 skill_traps ) ) );
     if( !p->has_proficiency( proficiency_prof_trapsetting ) ) {
         move_cost_final = move_cost_final * 2;
     }
     if( !p->has_proficiency( proficiency_prof_traps ) ) {
         move_cost_final = move_cost_final * 4;
     }
     //This probably needs to be done via assign_activity
     p->mod_moves( -move_cost_final );
     place_and_add_as_known( *p, pos, data.trap );
     for( const tripoint &t : here.points_in_radius( pos, data.trap.obj().get_trap_radius(), 0 ) ) {
         if( t != pos ) {
             place_and_add_as_known( *p, t, outer_layer_trap );
         }
     }
     return 1;
 }
References _, Character::add_msg_if_player(), allow_underwater, buried_data, bury_question, Character::cant_do_mounted(), Creature::cant_do_underwater(), choose_adjacent(), place_trap_actor::data::done_message, translation::empty(), time_duration::from_seconds(), get_map(), Character::get_skill_level(), trap::get_trap_radius(), map::has_flag(), Character::has_proficiency(), Character::has_quality(), is_allowed(), m_info, min(), Creature::mod_moves(), place_trap_actor::data::moves, string_id< T >::obj(), outer_layer_trap, place_and_add_as_known(), map::points_in_radius(), math_opers::pos(), Creature::posx(), Creature::posy(), Character::practice(), place_trap_actor::data::practice, Character::practice_proficiency(), proficiency_prof_traps, proficiency_prof_trapsetting, qual_DIG, query_yn(), round(), skill_traps, string_format(), map::tername(), TFLAG_DIGGABLE, item::tname(), translation::translated(), place_trap_actor::data::trap, and unburied_data.
Member Data Documentation
allow_under_player
bool place_trap_actor::allow_under_player = false
Whether one can place the trap directly under the character itself.
Definition at line 945 of file iuse_actor.h.
Referenced by is_allowed(), and load().
allow_underwater
bool place_trap_actor::allow_underwater = false
Whether one can place the trap when underwater.
Definition at line 943 of file iuse_actor.h.
Referenced by load(), and use().
buried_data
data place_trap_actor::buried_data
Data that applies to buried traps.
Definition at line 960 of file iuse_actor.h.
Referenced by load(), and use().
bury_question
translation place_trap_actor::bury_question
Contains the question asked when the player can bury the trap.
Something like "Bury the trap?"
Definition at line 958 of file iuse_actor.h.
Referenced by load(), and use().
needs_neighbor_terrain
ter_str_id place_trap_actor::needs_neighbor_terrain
Contains a terrain id of the terrain that must exist in a neighbor square to allow placing this trap.
If empty, it is ignored. This is for example for snare traps.
Definition at line 952 of file iuse_actor.h.
Referenced by is_allowed(), and load().
needs_solid_neighbor
bool place_trap_actor::needs_solid_neighbor = false
Whether the trap needs solid neighbor squares (e.g.
for trap wire).
Definition at line 947 of file iuse_actor.h.
Referenced by is_allowed(), and load().
outer_layer_trap
trap_str_id place_trap_actor::outer_layer_trap
The trap that makes up the outer layer of a multi-tile trap.
This is not supported for buried traps!
Definition at line 964 of file iuse_actor.h.
Referenced by load(), and use().
unburied_data
data place_trap_actor::unburied_data
Data that applies to unburied traps and to traps that *can * not be buried.
Definition at line 954 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp