Cataclysm DDA: tiny_bitset Class Reference
tiny_bitset Class Reference
#include <cata_bitset.h>
Classes
struct and_mapper
struct bit_setter
struct or_mapper
Public Types
using block_t = uintptr_t
Public Member Functions
tiny_bitset () noexcept
tiny_bitset (size_t initial_capacity) noexcept
~tiny_bitset () noexcept
tiny_bitset (const tiny_bitset &rhs) noexcept
tiny_bitset & operator= (const tiny_bitset &rhs) noexcept
tiny_bitset (tiny_bitset &&rhs) noexcept
tiny_bitset & operator= (tiny_bitset &&rhs) noexcept
void set (size_t idx)
bool test (size_t idx)
void clear (size_t idx)
void resize (size_t requested_bits) noexcept
bool is_inline () const
size_t size () const
size_t capacity () const
bool all () const
bool any () const
bool none () const
const block_t * bits () const
block_t * bits ()
void clear_all ()
void set_all ()
Static Public Attributes
static constexpr block_t kInlineSizeMask = 0b11111110
static constexpr block_t kStorageIsInlineMask = 0b00000001
static constexpr block_t kMetaMask = 0b11111111
static constexpr size_t kMaxInlineBits = std::numeric_limits<uintptr_t>::digits - 8
static constexpr size_t kBitsPerBlock = std::numeric_limits<uintptr_t>::digits
static constexpr size_t kInlineSizeBitsOffset = 1
static constexpr block_t kLowBit = 1
static constexpr block_t kHighBit = kLowBit << (kBitsPerBlock - 1)
static constexpr size_t kMinimumBlockPerAlloc = 4
Private Member Functions
template<typename Op >
void map (Op &&op)
block_t const * real_heap_allocation () const
block_t * real_heap_allocation ()
void resize_heap (size_t requested_bits) noexcept
void set_storage (block_t *data)
void set_size (size_t number_of_bits)
Private Attributes
uintptr_t storage_
Friends
void swap (tiny_bitset &lhs, tiny_bitset &rhs) noexcept
Detailed Description
Definition at line 14 of file cata_bitset.h.
Member Typedef Documentation
block_t
using tiny_bitset::block_t = uintptr_t
Definition at line 17 of file cata_bitset.h.
Constructor & Destructor Documentation
tiny_bitset() [1/4]
tiny_bitset::tiny_bitset () inline noexcept
Definition at line 44 of file cata_bitset.h.
 : tiny_bitset( kMaxInlineBits ) { }
tiny_bitset() [2/4]
tiny_bitset::tiny_bitset (size_t initial_capacity) inline explicit noexcept
Definition at line 46 of file cata_bitset.h.
{
             storage_ = kStorageIsInlineMask;
             resize( initial_capacity );
         }
References kStorageIsInlineMask, resize(), and storage_.
~tiny_bitset()
tiny_bitset::~tiny_bitset () inline noexcept
Definition at line 51 of file cata_bitset.h.
{
             if( !is_inline() ) {
                 free( real_heap_allocation() );
             }
         }
References is_inline(), and real_heap_allocation().
tiny_bitset() [3/4]
tiny_bitset::tiny_bitset (const tiny_bitset & rhs) inline noexcept
Definition at line 58 of file cata_bitset.h.
{
             if( rhs.is_inline() ) {
                 storage_ = rhs.storage_;
             } else {
                 resize( rhs.capacity() );
                 memcpy( bits(), rhs.bits(), rhs.size() / kBitsPerBlock );
             }
         }
References bits(), kBitsPerBlock, resize(), and storage_.
tiny_bitset() [4/4]
tiny_bitset::tiny_bitset (tiny_bitset && rhs) inline noexcept
Definition at line 84 of file cata_bitset.h.
{
             storage_ = rhs.storage_;
             rhs.storage_ = kStorageIsInlineMask;
         }
References kStorageIsInlineMask, and storage_.
Member Function Documentation
all()
bool tiny_bitset::all () const inline
Definition at line 154 of file cata_bitset.h.
{
             and_mapper mapper;
             const_cast<tiny_bitset &>( *this ).map( mapper );
             return ~mapper.value == 0;
         }
References map(), and tiny_bitset::and_mapper::value.
Referenced by JsonObject::report_unvisited(), and JsonObject::~JsonObject().
any()
bool tiny_bitset::any () const inline
Definition at line 160 of file cata_bitset.h.
{
             or_mapper mapper;
             const_cast<tiny_bitset &>( *this ).map( mapper );
             return mapper.value != 0;
         }
References map(), and tiny_bitset::or_mapper::value.
Referenced by none().
bits() [1/2]
block_t* tiny_bitset::bits () inline
Definition at line 175 of file cata_bitset.h.
{
             if( is_inline() ) {
                 return &storage_;
             } else {
                 // The hashtag blessed UB-avoiding way of type punning a pointer
                 // out of an integer.
                 block_t *ret;
                 memcpy( &ret, &storage_, sizeof( storage_ ) );
                 return ret;
             }
         }
References is_inline(), cata::hash64_detail::ret, and storage_.
bits() [2/2]
const block_t* tiny_bitset::bits () const inline
Definition at line 170 of file cata_bitset.h.
{
             return const_cast<tiny_bitset &>( *this ).bits();
         }
References bits().
Referenced by bits(), clear(), map(), tiny_bitset::and_mapper::operator()(), tiny_bitset::or_mapper::operator()(), tiny_bitset::bit_setter< set >::operator()(), operator=(), real_heap_allocation(), JsonObject::report_unvisited(), set(), test(), and tiny_bitset().
capacity()
size_t tiny_bitset::capacity () const inline
Definition at line 149 of file cata_bitset.h.
{
             // We don't track size and capacity separately for convenience.
             return size();
         }
References size().
clear()
void tiny_bitset::clear (size_t idx) inline
Definition at line 116 of file cata_bitset.h.
{
             cata_assert( idx < size() );
             size_t block_idx = idx / kBitsPerBlock;
             // Do not do uint8_t bit_mask = ~(1 << (idx % 8));
             // The RHS evaluates to an _int_
             block_t bit_mask = kHighBit >> ( idx % kBitsPerBlock );
             bits()[block_idx] &= ~bit_mask;
         }
References bits(), cata_assert, kBitsPerBlock, kHighBit, and size().
clear_all()
void tiny_bitset::clear_all () inline
Definition at line 187 of file cata_bitset.h.
{
             map( bit_setter<false> {} );
         }
References map().
Referenced by JsonObject::operator=().
is_inline()
bool tiny_bitset::is_inline () const inline
Definition at line 133 of file cata_bitset.h.
{
             // Heap pointers can generally be assumed to be aligned to at least 2 bytes.
             // Really, we can assume at least 8 byte alignment, but we only need one bit
             // to denote if we're on the heap or not.
             // If we're on the heap, at least the least significant bit will be 0.
             return static_cast<bool>( storage_ & kStorageIsInlineMask );
         }
References kStorageIsInlineMask, and storage_.
Referenced by bits(), map(), operator=(), resize(), set_size(), size(), and ~tiny_bitset().
map()
template<typename Op > void tiny_bitset::map (Op && op) inline private
Definition at line 248 of file cata_bitset.h.
{
             size_t bits_used = size();
             if( bits_used == 0 ) {
                 return;
             }
             if( is_inline() ) {
                 block_t unused_mask = ( kLowBit << ( kBitsPerBlock - bits_used ) ) - 1;
                 op( storage_, unused_mask );
                 return;
             }
             // The compiler auto vectorizer is too smart and inserts a bunch of code
             // to handle various cases of how big the data is. We expect things to be
             // small, so we can hand roll a loop which doesn't blow up code size or
             // insert a huge number of conditionals into the hot path, and probably
             // not measurably slower than the fully expanded vectorized code which handles
             // 128 bytes (1,024 bits!) in one pass.
             size_t used_blocks = bits_used / kBitsPerBlock;
             // The final block requires special handling.
             size_t used_bits_in_final_block = bits_used % kBitsPerBlock;
             size_t used_whole_blocks = used_bits_in_final_block > 0 &&
                                        used_blocks > 0 ? used_blocks - 1 : used_blocks;
             // Process 4 at a time for some manual unrolling.
             block_t *blocks = bits();
             size_t i = 0;
             for( size_t end = used_whole_blocks; i + 3 < end; i += 4 ) {
                 op( blocks[i + 0] );
                 op( blocks[i + 1] );
                 op( blocks[i + 2] );
                 op( blocks[i + 3] );
             }
             // final whole blocks that don't fit in unrolled loop.
             for( ; i < used_whole_blocks; ++i ) {
                 op( blocks[i] );
             }
             // final, partial block
             block_t unused_mask;
             if( used_bits_in_final_block != 0 ) {
                 // Create mask which is all bits set for bits not used in capacity.
                 // If we used N bits, create a mask of the k - N least significant bits by
                 // shifting a 1 k-N times, into the k-N'th bit _index_ (or k-N+1'th bit) then
                 // subtracting one, setting k-N of the least significant bits to 1.
                 unused_mask = ( kLowBit << ( kBitsPerBlock - used_bits_in_final_block ) ) - 1;
                 op( blocks[i], unused_mask );
             }
         }
References bits(), keycode::end, is_inline(), kBitsPerBlock, kLowBit, size(), and storage_.
Referenced by all(), any(), clear_all(), and set_all().
none()
bool tiny_bitset::none () const inline
Definition at line 166 of file cata_bitset.h.
{
             return !any();
         }
References any().
operator=() [1/2]
tiny_bitset& tiny_bitset::operator= (const tiny_bitset & rhs) inline noexcept
Definition at line 68 of file cata_bitset.h.
{
             if( this == &rhs ) {
                 return *this;
             }
             if( rhs.is_inline() ) {
                 if( !is_inline() ) {
                     free( real_heap_allocation() );
                 }
                 storage_ = rhs.storage_;
             } else {
                 resize( rhs.capacity() );
                 memcpy( bits(), rhs.bits(), rhs.size() / kBitsPerBlock );
             }
             return *this;
         }
References bits(), is_inline(), kBitsPerBlock, real_heap_allocation(), resize(), and storage_.
operator=() [2/2]
tiny_bitset& tiny_bitset::operator= (tiny_bitset && rhs) inline noexcept
Definition at line 89 of file cata_bitset.h.
{
             swap( *this, rhs );
             return *this;
         }
References swap.
real_heap_allocation() [1/2]
block_t* tiny_bitset::real_heap_allocation () inline private
Definition at line 300 of file cata_bitset.h.
{
             // When heapified, we store the capacity of the allocation shifted behind the data.
             // For convenience, we assume a size_t can fit into a uintptr_t.
             static_assert( sizeof( size_t ) <= sizeof( uintptr_t ), "What platform has size_t > uintptr_t?" );
             static_assert( alignof( size_t ) <= alignof( uintptr_t ),
                            "What platform has alignof(size_t) > alignof(uintptr_t)?" );
             return bits() - 1;
         }
References bits().
real_heap_allocation() [2/2]
block_t const* tiny_bitset::real_heap_allocation () const inline private
Definition at line 296 of file cata_bitset.h.
{
             return const_cast<tiny_bitset &>( *this ).real_heap_allocation();
         }
References real_heap_allocation().
Referenced by operator=(), real_heap_allocation(), set_size(), size(), and ~tiny_bitset().
resize()
void tiny_bitset::resize (size_t requested_bits) inline noexcept
Definition at line 125 of file cata_bitset.h.
{
             if( is_inline() && requested_bits <= kMaxInlineBits ) {
                 set_size( requested_bits );
                 return;
             }
             resize_heap( requested_bits );
         }
References is_inline(), kMaxInlineBits, resize_heap(), and set_size().
Referenced by JsonObject::init(), operator=(), and tiny_bitset().
resize_heap()
void tiny_bitset::resize_heap (size_t requested_bits) private noexcept
Definition at line 15 of file cata_bitset.cpp.
 {
     size_t blocks_needed = bit_count_to_block_count( requested_bits );
     // Round up to a multiple of the block allocation size.
     // The allocation size is stored by malloc so realloc() can be optimized if we keep resizing by small amounts.
     blocks_needed = ( ( blocks_needed + ( kMinimumBlockPerAlloc - 1 ) ) / kMinimumBlockPerAlloc ) *
                     kMinimumBlockPerAlloc + 1;
     if( is_inline() ) {
         // Allocate an extra block for prepending the capacity to.
         block_t *data = static_cast<block_t *>( malloc( sizeof( block_t ) * ( blocks_needed + 1 ) ) );
         cata_assert( data != nullptr );
         // Capacity goes at the front ahead of the actual bits.
         data[ 0 ] = requested_bits;
         // Copy inline bits to heap.
         data[ 1 ] = storage_ & ~kMetaMask;
         set_storage( data + 1 );
     } else {
         block_t *data = static_cast<block_t *>( realloc( real_heap_allocation(),
                                                 sizeof( block_t ) * ( blocks_needed + 1 ) ) );
         if( data != real_heap_allocation() ) {
             set_storage( data + 1 );
         }
     }
     set_size( requested_bits );
 }
References anonymous_namespace{cata_bitset.cpp}::bit_count_to_block_count(), and cata_assert.
Referenced by resize().
set()
void tiny_bitset::set (size_t idx) inline
Definition at line 100 of file cata_bitset.h.
{
             cata_assert( idx < size() );
             size_t block_idx = idx / kBitsPerBlock;
             block_t bit_mask = kHighBit >> ( idx % kBitsPerBlock );
             bits()[block_idx] |= bit_mask;
         }
References bits(), cata_assert, kBitsPerBlock, kHighBit, and size().
Referenced by JsonArray::mark_visited(), JsonObject::mark_visited(), and tiny_bitset::bit_setter< set >::operator()().
set_all()
void tiny_bitset::set_all () inline
Definition at line 191 of file cata_bitset.h.
{
             map( bit_setter<true> {} );
         }
References map().
Referenced by JsonObject::allow_omitted_members(), and JsonObject::report_unvisited().
set_size()
void tiny_bitset::set_size (size_t number_of_bits) inline private
Definition at line 314 of file cata_bitset.h.
{
             if( is_inline() ) {
                 cata_assert( number_of_bits <= kMaxInlineBits );
                 uint8_t inline_storage_bits = ( number_of_bits << kInlineSizeBitsOffset ) & kInlineSizeMask;
                 storage_ = ( storage_ & ~kInlineSizeMask ) | inline_storage_bits;
             } else {
                 *real_heap_allocation() = number_of_bits;
             }
         }
References cata_assert, is_inline(), kInlineSizeBitsOffset, kInlineSizeMask, kMaxInlineBits, real_heap_allocation(), and storage_.
Referenced by resize().
set_storage()
void tiny_bitset::set_storage (block_t * data) private
Definition at line 44 of file cata_bitset.cpp.
 {
     memcpy( &storage_, &data, sizeof( data ) );
 }
References storage_.
size()
size_t tiny_bitset::size () const inline
Definition at line 141 of file cata_bitset.h.
{
             if( is_inline() ) {
                 return ( storage_ & kInlineSizeMask ) >> kInlineSizeBitsOffset;
             } else {
                 return *real_heap_allocation();
             }
         }
References is_inline(), kInlineSizeBitsOffset, kInlineSizeMask, real_heap_allocation(), and storage_.
Referenced by capacity(), clear(), map(), JsonObject::report_unvisited(), set(), and test().
test()
bool tiny_bitset::test (size_t idx) inline
Definition at line 108 of file cata_bitset.h.
{
             cata_assert( idx < size() );
             size_t block_idx = idx / kBitsPerBlock;
             block_t bit_mask = kHighBit >> ( idx % kBitsPerBlock );
             return bits()[block_idx] & bit_mask;
         }
References bits(), cata_assert, kBitsPerBlock, kHighBit, and size().
Friends And Related Function Documentation
swap
void swap (tiny_bitset & lhs, tiny_bitset & rhs) friend
Definition at line 94 of file cata_bitset.h.
{
             using namespace std;
             swap( lhs.storage_, rhs.storage_ );
         }
Referenced by operator=().
Member Data Documentation
kBitsPerBlock
constexpr size_t tiny_bitset::kBitsPerBlock = std::numeric_limits<uintptr_t>::digits static constexpr
Definition at line 31 of file cata_bitset.h.
Referenced by anonymous_namespace{cata_bitset.cpp}::bit_count_to_block_count(), clear(), map(), operator=(), JsonObject::report_unvisited(), set(), test(), and tiny_bitset().
kHighBit
constexpr block_t tiny_bitset::kHighBit = kLowBit << (kBitsPerBlock - 1) static constexpr
Definition at line 39 of file cata_bitset.h.
Referenced by clear(), set(), and test().
kInlineSizeBitsOffset
constexpr size_t tiny_bitset::kInlineSizeBitsOffset = 1 static constexpr
Definition at line 34 of file cata_bitset.h.
Referenced by set_size(), and size().
kInlineSizeMask
constexpr block_t tiny_bitset::kInlineSizeMask = 0b11111110 static constexpr
Definition at line 24 of file cata_bitset.h.
Referenced by set_size(), and size().
kLowBit
constexpr block_t tiny_bitset::kLowBit = 1 static constexpr
Definition at line 38 of file cata_bitset.h.
Referenced by map(), and JsonObject::report_unvisited().
kMaxInlineBits
constexpr size_t tiny_bitset::kMaxInlineBits = std::numeric_limits<uintptr_t>::digits - 8 static constexpr
Definition at line 30 of file cata_bitset.h.
Referenced by resize(), and set_size().
kMetaMask
constexpr block_t tiny_bitset::kMetaMask = 0b11111111 static constexpr
Definition at line 27 of file cata_bitset.h.
kMinimumBlockPerAlloc
constexpr size_t tiny_bitset::kMinimumBlockPerAlloc = 4 static constexpr
Definition at line 42 of file cata_bitset.h.
kStorageIsInlineMask
constexpr block_t tiny_bitset::kStorageIsInlineMask = 0b00000001 static constexpr
Definition at line 25 of file cata_bitset.h.
Referenced by is_inline(), and tiny_bitset().
storage_
uintptr_t tiny_bitset::storage_ private
Definition at line 330 of file cata_bitset.h.
Referenced by bits(), is_inline(), map(), operator=(), set_size(), set_storage(), size(), and tiny_bitset().
The documentation for this class was generated from the following files:
src/cata_bitset.h
src/cata_bitset.cpp