Cataclysm DDA: take_off_inventory_preset Class Reference
take_off_inventory_preset Class Reference
Public Member Functions
take_off_inventory_preset (Character &you, const std::string &color)
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
Public Member Functions inherited from armor_inventory_preset
armor_inventory_preset (Character &pl, const std::string &color_in)
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from armor_inventory_preset
Character & you
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 427 of file game_inventory.cpp.
Constructor & Destructor Documentation
take_off_inventory_preset()
take_off_inventory_preset::take_off_inventory_preset (Character & you, const std::string & color) inline
Definition at line 430 of file game_inventory.cpp.
                                                                             :
             armor_inventory_preset( you, color )
         {}
Member Function Documentation
get_denial()
std::string take_off_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Definition at line 438 of file game_inventory.cpp.
{
             const ret_val<void> ret = you.can_takeoff( *loc );
             if( !ret.success() ) {
                 return trim_trailing_punctuations( ret.str() );
             }
             return std::string();
         }
References Character::can_takeoff(), cata::hash64_detail::ret, trim_trailing_punctuations(), and armor_inventory_preset::you.
is_shown()
bool take_off_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Definition at line 434 of file game_inventory.cpp.
{
             return loc->is_armor() && you.is_worn( *loc );
         }
References item::is_armor(), Character::is_worn(), and armor_inventory_preset::you.
The documentation for this class was generated from the following file:
src/game_inventory.cpp