Cataclysm DDA: viewer Class Reference
viewer Class Reference abstract
#include <viewer.h>
Public Member Functions
virtual bool sees (const tripoint &target, bool is_avatar=false, int range_mod=0) const =0
virtual bool sees (const tripoint_bub_ms &target, bool is_avatar=false, int range_mod=0) const =0
virtual bool sees (const Creature &target) const =0
virtual ~viewer ()=default
Detailed Description
Definition at line 10 of file viewer.h.
Constructor & Destructor Documentation
~viewer()
virtual viewer::~viewer () virtual default
Member Function Documentation
sees() [1/3]
virtual bool viewer::sees (const Creature & target) const pure virtual
Implemented in Creature, and Character.
sees() [2/3]
virtual bool viewer::sees (const tripoint & target, bool is_avatar = false, int range_mod = 0) const pure virtual
Implemented in Creature, and Character.
Referenced by Character::add_msg_player_or_say(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), leap_actor::call(), trapfunc::caltrops_glass(), trapfunc::crossbow(), trapfunc::dissector(), iuse::dog_whistle(), iuse::extinguisher(), conditional_fun::anonymous_namespace{condition.cpp}::f_player_see(), mattack::fungus_big_blossom(), npc::heal_player(), anonymous_namespace{animation.cpp}::is_point_visible(), monster::knock_back_to(), mattack::leech_spawner(), mattack::lunge(), iuse::mace(), Creature::messaging_projectile_attack(), monster::move_effects(), npc::mutiny(), mattack::nurse_assist(), Character::on_hit(), npc::pick_up_item(), trapfunc::shotgun(), npc::stow_item(), Character::uncanny_dodge(), Character::uninstall_bionic(), mattack::upgrade(), and npc::would_take_that().
sees() [3/3]
virtual bool viewer::sees (const tripoint_bub_ms & target, bool is_avatar = false, int range_mod = 0) const pure virtual
Implemented in Creature, and Character.
The documentation for this class was generated from the following file:
src/viewer.h