Cataclysm DDA: overmap_land_use_code Class Reference
overmap_land_use_code Class Reference
#include <omdata.h>
Public Member Functions
std::string get_symbol () const
void load (const JsonObject &jo, const std::string &src)
void finalize ()
void check () const
Public Attributes
overmap_land_use_code_id id = overmap_land_use_code_id::NULL_ID()
std::vector< std::pair< overmap_land_use_code_id, mod_id > > src
int land_use_code = 0
translation name
translation detailed_definition
uint32_t symbol = 0
nc_color color = c_black
bool was_loaded = false
Detailed Description
Definition at line 119 of file omdata.h.
Member Function Documentation
check()
void overmap_land_use_code::check () const
Definition at line 460 of file overmap.cpp.
 {
 }
finalize()
void overmap_land_use_code::finalize ()
Definition at line 455 of file overmap.cpp.
 {
 }
get_symbol()
std::string overmap_land_use_code::get_symbol () const
Definition at line 432 of file overmap.cpp.
 {
     return utf32_to_utf8( symbol );
 }
References symbol, and utf32_to_utf8().
load()
void overmap_land_use_code::load (const JsonObject & jo, const std::string & src)
Definition at line 437 of file overmap.cpp.
 {
     const bool strict = src == "dda";
     assign( jo, "land_use_code", land_use_code, strict );
     assign( jo, "name", name, strict );
     assign( jo, "detailed_definition", detailed_definition, strict );
     optional( jo, was_loaded, "sym", symbol, unicode_codepoint_from_symbol_reader, NULL_UNICODE );
     if( symbol == NULL_UNICODE ) {
         DebugLog( D_ERROR, D_GAME ) << "`sym` node is not defined properly for `land_use_code`: "
                                     << id.c_str() << " (" << name << ")";
     }
     assign( jo, "color", color );
 }
References assign(), color, D_ERROR, D_GAME, DebugLog(), detailed_definition, land_use_code, name, NULL_UNICODE, optional(), src, strict, symbol, unicode_codepoint_from_symbol_reader(), and was_loaded.
Member Data Documentation
color
nc_color overmap_land_use_code::color = c_black
Definition at line 129 of file omdata.h.
Referenced by oter_t::get_color(), and load().
detailed_definition
translation overmap_land_use_code::detailed_definition
Definition at line 127 of file omdata.h.
Referenced by load().
id
overmap_land_use_code_id overmap_land_use_code::id = overmap_land_use_code_id::NULL_ID()
Definition at line 122 of file omdata.h.
land_use_code
int overmap_land_use_code::land_use_code = 0
Definition at line 125 of file omdata.h.
Referenced by load().
name
translation overmap_land_use_code::name
Definition at line 126 of file omdata.h.
Referenced by load().
src
std::vector<std::pair<overmap_land_use_code_id, mod_id> > overmap_land_use_code::src
Definition at line 123 of file omdata.h.
Referenced by load().
symbol
uint32_t overmap_land_use_code::symbol = 0
Definition at line 128 of file omdata.h.
Referenced by get_symbol(), and load().
was_loaded
bool overmap_land_use_code::was_loaded = false
Definition at line 134 of file omdata.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/omdata.h
src/overmap.cpp