Cataclysm DDA: known_magic Class Reference
known_magic Class Reference
#include <magic.h>
Public Member Functions
known_magic ()
void learn_spell (const std::string &sp, Character &guy, bool force=false)
void learn_spell (const spell_id &sp, Character &guy, bool force=false)
void learn_spell (const spell_type *sp, Character &guy, bool force=false)
void forget_spell (const std::string &sp)
void forget_spell (const spell_id &sp)
void set_spell_level (const spell_id &, int, const Character *)
void set_spell_exp (const spell_id &, int, const Character *)
int time_to_learn_spell (const Character &guy, const spell_id &sp) const
int time_to_learn_spell (const Character &guy, const std::string &str) const
bool can_learn_spell (const Character &guy, const spell_id &sp) const
bool knows_spell (const std::string &sp) const
bool knows_spell (const spell_id &sp) const
bool knows_spell () const
std::vector< spell_id > spells () const
spell & get_spell (const spell_id &sp)
int select_spell (Character &guy)
std::vector< spell * > get_spells ()
std::map< spell_id, spell > & get_spellbook ()
int available_mana () const
int max_mana (const Character &guy) const
void mod_mana (const Character &guy, int add_mana)
void set_mana (int new_mana)
void update_mana (const Character &guy, float turns)
bool has_enough_energy (const Character &guy, const spell &sp) const
void clear_opens_spellbook_data ()
void evaluate_opens_spellbook_data ()
void on_mutation_gain (const trait_id &mid, Character &guy)
void on_mutation_loss (const trait_id &mid)
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
bool set_invlet (const spell_id &sp, int invlet, const std::set< int > &used_invlets)
void rem_invlet (const spell_id &sp)
void toggle_favorite (const spell_id &sp)
bool is_favorite (const spell_id &sp)
Public Attributes
bool casting_ignore = false
double caster_level_adjustment
std::map< spell_id, double > caster_level_adjustment_by_spell
std::map< trait_id, double > caster_level_adjustment_by_school
Private Member Functions
int get_spellname_max_width ()
int get_invlet (const spell_id &sp, std::set< int > &used_invlets)
Private Attributes
std::map< spell_id, spell > spellbook
std::map< spell_id, int > invlets
std::unordered_set< spell_id > favorites
int mana_base = 0
int mana = 0
Detailed Description
Definition at line 645 of file magic.h.
Constructor & Destructor Documentation
known_magic()
known_magic::known_magic ()
Definition at line 1917 of file magic.cpp.
 {
     mana_base = 1000;
     mana = mana_base;
 }
References mana, and mana_base.
Member Function Documentation
available_mana()
int known_magic::available_mana () const
Definition at line 2136 of file magic.cpp.
 {
     return mana;
 }
References mana.
Referenced by has_enough_energy().
can_learn_spell()
bool known_magic::can_learn_spell (const Character & guy, const spell_id & sp) const
Definition at line 2104 of file magic.cpp.
 {
     const spell_type &sp_t = sp.obj();
     if( sp_t.spell_class == trait_NONE ) {
         return true;
     }
     if( sp_t.spell_tags[spell_flag::MUST_HAVE_CLASS_TO_LEARN] ) {
         return guy.has_trait( sp_t.spell_class );
     } else {
         return !guy.has_opposite_trait( sp_t.spell_class );
     }
 }
References Character::has_opposite_trait(), Character::has_trait(), MUST_HAVE_CLASS_TO_LEARN, string_id< T >::obj(), spell_type::spell_class, spell_type::spell_tags, and trait_NONE.
Referenced by learn_spell().
clear_opens_spellbook_data()
void known_magic::clear_opens_spellbook_data ()
Definition at line 2209 of file magic.cpp.
 {
     caster_level_adjustment = 0;
     caster_level_adjustment_by_spell.clear();
     caster_level_adjustment_by_school.clear();
     for( spell *sp : get_spells() ) {
         sp->clear_temp_adjustments();
     }
 }
References caster_level_adjustment, caster_level_adjustment_by_school, caster_level_adjustment_by_spell, and get_spells().
deserialize()
void known_magic::deserialize (const JsonObject & data)
Definition at line 1944 of file magic.cpp.
 {
     data.read( "mana", mana );
     for( JsonObject jo : data.get_array( "spellbook" ) ) {
         std::string id = jo.get_string( "id" );
         spell_id sp = spell_id( id );
         int xp = jo.get_int( "xp" );
         if( knows_spell( sp ) ) {
             spellbook[sp].set_exp( xp );
         } else {
             spellbook.emplace( sp, spell( sp, xp ) );
         }
     }
     data.read( "invlets", invlets );
     data.read( "favorites", favorites );
 }
References favorites, JsonObject::get_array(), invlets, knows_spell(), mana, JsonObject::read(), spell_id, and spellbook.
evaluate_opens_spellbook_data()
void known_magic::evaluate_opens_spellbook_data ()
Definition at line 2219 of file magic.cpp.
 {
     for( spell *sp : get_spells() ) {
         double raw_level_adjust = caster_level_adjustment;
         std::map<trait_id, double>::iterator school_it =
             caster_level_adjustment_by_school.find( sp->spell_class() );
         if( school_it != caster_level_adjustment_by_school.end() ) {
             raw_level_adjust += school_it->second;
         }
         std::map<spell_id, double>::iterator spell_it =
             caster_level_adjustment_by_spell.find( sp->id() );
         if( spell_it != caster_level_adjustment_by_spell.end() ) {
             raw_level_adjust += spell_it->second;
         }
         int final_level = clamp( sp->get_level() + static_cast<int>( raw_level_adjust ), 0,
                                  sp->get_max_level( get_player_character() ) );
         sp->set_temp_level_adjustment( final_level - sp->get_level() );
     }
 }
References caster_level_adjustment, caster_level_adjustment_by_school, caster_level_adjustment_by_spell, clamp(), get_player_character(), and get_spells().
forget_spell() [1/2]
void known_magic::forget_spell (const spell_id & sp)
Definition at line 2047 of file magic.cpp.
 {
     if( !knows_spell( sp ) ) {
         debugmsg( "Can't forget a spell you don't know!" );
         return;
     }
     add_msg( m_bad, _( "All knowledge of %s leaves you." ), sp->name );
     // TODO: add parameter for owner of known_magic for this function
     get_event_bus().send<event_type::character_forgets_spell>( get_player_character().getID(), sp->id );
     spellbook.erase( sp );
 }
References _, add_msg(), character_forgets_spell, debugmsg, get_event_bus(), get_player_character(), Character::getID(), spell_type::id, knows_spell(), m_bad, spell_type::name, event_bus::send(), and spellbook.
forget_spell() [2/2]
void known_magic::forget_spell (const std::string & sp)
Definition at line 2042 of file magic.cpp.
 {
     forget_spell( spell_id( sp ) );
 }
References spell_id.
Referenced by on_mutation_loss().
get_invlet()
int known_magic::get_invlet (const spell_id & sp, std::set< int > & used_invlets) private
Definition at line 2707 of file magic.cpp.
 {
     auto found = invlets.find( sp );
     if( found != invlets.end() ) {
         return found->second;
     }
     for( const std::pair<const spell_id, int> &invlet_pair : invlets ) {
         used_invlets.emplace( invlet_pair.second );
     }
     for( int i = 'a'; i <= 'z'; i++ ) {
         if( used_invlets.count( i ) == 0 ) {
             used_invlets.emplace( i );
             return i;
         }
     }
     for( int i = 'A'; i <= 'Z'; i++ ) {
         if( used_invlets.count( i ) == 0 ) {
             used_invlets.emplace( i );
             return i;
         }
     }
     for( int i = '!'; i <= '-'; i++ ) {
         if( used_invlets.count( i ) == 0 ) {
             used_invlets.emplace( i );
             return i;
         }
     }
     return 0;
 }
References invlets.
Referenced by select_spell().
get_spell()
spell & known_magic::get_spell (const spell_id & sp)
Definition at line 2117 of file magic.cpp.
 {
     if( !knows_spell( sp ) ) {
         debugmsg( "ERROR: Tried to get unknown spell" );
     }
     spell &temp_spell = spellbook[ sp ];
     return temp_spell;
 }
References debugmsg, knows_spell(), and spellbook.
Referenced by on_mutation_gain(), set_spell_exp(), and set_spell_level().
get_spellbook()
std::map<spell_id, spell>& known_magic::get_spellbook () inline
Definition at line 690 of file magic.h.
{
             return spellbook;
         }
References spellbook.
get_spellname_max_width()
int known_magic::get_spellname_max_width () private
Definition at line 2253 of file magic.cpp.
 {
     int width = 0;
     for( const spell *sp : get_spells() ) {
         width = std::max( width, utf8_width( sp->name() ) );
     }
     return width;
 }
References get_spells(), max(), and utf8_width().
Referenced by select_spell().
get_spells()
std::vector< spell * > known_magic::get_spells ()
Definition at line 2126 of file magic.cpp.
 {
     std::vector<spell *> spells;
     spells.reserve( spellbook.size() );
     for( auto &spell_pair : spellbook ) {
         spells.emplace_back( &spell_pair.second );
     }
     return spells;
 }
References spellbook, and spells().
Referenced by clear_opens_spellbook_data(), evaluate_opens_spellbook_data(), get_spellname_max_width(), on_mutation_loss(), and select_spell().
has_enough_energy()
bool known_magic::has_enough_energy (const Character & guy, const spell & sp) const
Definition at line 2185 of file magic.cpp.
 {
     int cost = sp.energy_cost( guy );
     switch( sp.energy_source() ) {
         case magic_energy_type::mana:
             return available_mana() >= cost;
         case magic_energy_type::bionic:
             return guy.get_power_level() >= units::from_kilojoule( static_cast<std::int64_t>( cost ) );
         case magic_energy_type::stamina:
             return guy.get_stamina() >= cost;
         case magic_energy_type::hp:
             for( const std::pair<const bodypart_str_id, bodypart> &elem : guy.get_body() ) {
                 if( elem.second.get_hp_cur() > cost ) {
                     return true;
                 }
             }
             return false;
         case magic_energy_type::none:
             return true;
         default:
             return false;
     }
 }
References available_mana(), bionic, spell::energy_cost(), spell::energy_source(), units::from_kilojoule(), Creature::get_body(), Character::get_power_level(), Character::get_stamina(), hp, mana, none, and stamina.
is_favorite()
bool known_magic::is_favorite (const spell_id & sp)
Definition at line 2702 of file magic.cpp.
 {
     return favorites.count( sp ) > 0;
 }
References favorites.
knows_spell() [1/3]
bool known_magic::knows_spell () const
Definition at line 1972 of file magic.cpp.
 {
     return !spellbook.empty();
 }
References spellbook.
Referenced by deserialize(), forget_spell(), get_spell(), knows_spell(), set_spell_exp(), and set_spell_level().
knows_spell() [2/3]
bool known_magic::knows_spell (const spell_id & sp) const
Definition at line 1967 of file magic.cpp.
 {
     return spellbook.count( sp ) == 1;
 }
References spellbook.
knows_spell() [3/3]
bool known_magic::knows_spell (const std::string & sp) const
Definition at line 1962 of file magic.cpp.
 {
     return knows_spell( spell_id( sp ) );
 }
References knows_spell(), and spell_id.
learn_spell() [1/3]
void known_magic::learn_spell (const spell_id & sp, Character & guy, bool force = false)
Definition at line 1982 of file magic.cpp.
 {
     learn_spell( &sp.obj(), guy, force );
 }
References force, learn_spell(), and string_id< T >::obj().
learn_spell() [2/3]
void known_magic::learn_spell (const spell_type * sp, Character & guy, bool force = false)
Definition at line 1987 of file magic.cpp.
 {
     if( !sp->is_valid() ) {
         debugmsg( "Tried to learn invalid spell" );
         return;
     }
     if( guy.magic->knows_spell( sp->id ) ) {
         // you already know the spell
         return;
     }
     spell temp_spell( sp->id );
     if( !temp_spell.is_valid() ) {
         debugmsg( "Tried to learn invalid spell" );
         return;
     }
     if( !force && sp->spell_class != trait_NONE ) {
         if( can_learn_spell( guy, sp->id ) && !guy.has_trait( sp->spell_class ) ) {
             std::string trait_cancel;
             for( const trait_id &cancel : sp->spell_class->cancels ) {
                 if( cancel == sp->spell_class->cancels.back() &&
                     sp->spell_class->cancels.back() != sp->spell_class->cancels.front() ) {
                     trait_cancel = string_format( _( "%s and %s" ), trait_cancel, cancel->name() );
                 } else if( cancel == sp->spell_class->cancels.front() ) {
                     trait_cancel = cancel->name();
                     if( sp->spell_class->cancels.size() == 1 ) {
                         trait_cancel = string_format( "%s: %s", trait_cancel, cancel->desc() );
                     }
                 } else {
                     trait_cancel = string_format( _( "%s, %s" ), trait_cancel, cancel->name() );
                 }
                 if( cancel == sp->spell_class->cancels.back() ) {
                     trait_cancel += ".";
                 }
             }
             if( !guy.is_avatar() || query_yn(
                     _( "Learning this spell will make you a\n\n%s: %s\n\nand lock you out of\n\n%s\n\nContinue?" ),
                     sp->spell_class->name(), sp->spell_class->desc(), trait_cancel ) ) {
                 guy.set_mutation( sp->spell_class );
                 guy.on_mutation_gain( sp->spell_class );
                 guy.add_msg_if_player( sp->spell_class.obj().desc() );
             } else {
                 return;
             }
         }
     }
     if( force || can_learn_spell( guy, sp->id ) ) {
         spellbook.emplace( sp->id, temp_spell );
         get_event_bus().send<event_type::character_learns_spell>( guy.getID(), sp->id );
         guy.add_msg_player_or_npc( m_good, _( "You learned %s!" ), _( "<npcname> learned %s!" ), sp->name );
     } else {
         guy.add_msg_player_or_npc( m_bad, _( "You can't learn this spell." ),
                                    _( "<npcname> can't learn this spell." ) );
     }
 }
References _, Character::add_msg_if_player(), Character::add_msg_player_or_npc(), can_learn_spell(), cancel, mutation_branch::cancels, character_learns_spell, debugmsg, mutation_branch::desc(), force, get_event_bus(), Character::getID(), Character::has_trait(), spell_type::id, Creature::is_avatar(), spell_type::is_valid(), spell::is_valid(), m_bad, m_good, Character::magic, spell_type::name, mutation_branch::name(), string_id< T >::obj(), Character::on_mutation_gain(), query_yn(), event_bus::send(), Character::set_mutation(), spell_type::spell_class, spellbook, string_format(), and trait_NONE.
learn_spell() [3/3]
void known_magic::learn_spell (const std::string & sp, Character & guy, bool force = false)
Definition at line 1977 of file magic.cpp.
 {
     learn_spell( spell_id( sp ), guy, force );
 }
References force, and spell_id.
Referenced by learn_spell(), and on_mutation_gain().
max_mana()
int known_magic::max_mana (const Character & guy) const
Definition at line 2151 of file magic.cpp.
 {
     const float int_bonus = ( ( 0.2f + guy.get_int() * 0.1f ) - 1.0f ) * mana_base;
     int penalty_calc = std::round( std::max<int64_t>( 0,
                                    units::to_kilojoule( guy.get_power_level() ) ) );
     const int bionic_penalty = guy.enchantment_cache->modify_value(
                                    enchant_vals::mod::BIONIC_MANA_PENALTY, penalty_calc );
     const float unaugmented_mana = std::max( 0.0f,
                                    ( mana_base + int_bonus ) - bionic_penalty );
     return guy.calculate_by_enchantment( unaugmented_mana, enchant_vals::mod::MAX_MANA, true );
 }
References enchant_vals::BIONIC_MANA_PENALTY, Character::calculate_by_enchantment(), Character::enchantment_cache, Character::get_int(), Character::get_power_level(), mana_base, max(), enchant_vals::MAX_MANA, round(), and units::to_kilojoule().
Referenced by mod_mana(), and update_mana().
mod_mana()
void known_magic::mod_mana (const Character & guy, int add_mana)
Definition at line 2146 of file magic.cpp.
 {
     set_mana( clamp( mana + add_mana, 0, max_mana( guy ) ) );
 }
References clamp(), mana, max_mana(), and set_mana().
Referenced by update_mana().
on_mutation_gain()
void known_magic::on_mutation_gain (const trait_id & mid, Character & guy)
Definition at line 2817 of file magic.cpp.
 {
     for( const std::pair<const spell_id, int> &sp : mid->spells_learned ) {
         learn_spell( sp.first, guy, true );
         spell &temp_sp = get_spell( sp.first );
         for( int level = 0; level < sp.second; level++ ) {
             temp_sp.gain_level( guy );
         }
     }
 }
References spell::gain_level(), get_spell(), learn_spell(), and mutation_branch::spells_learned.
on_mutation_loss()
void known_magic::on_mutation_loss (const trait_id & mid)
Definition at line 2828 of file magic.cpp.
 {
     std::vector<spell_id> spells_to_forget;
     for( const spell *sp : get_spells() ) {
         if( sp->is_spell_class( mid ) ) {
             spells_to_forget.emplace_back( sp->id() );
         }
     }
     for( const spell_id &sp_id : spells_to_forget ) {
         forget_spell( sp_id );
     }
 }
References forget_spell(), and get_spells().
rem_invlet()
void known_magic::rem_invlet (const spell_id & sp)
Definition at line 2688 of file magic.cpp.
 {
     invlets.erase( sp );
 }
References invlets.
select_spell()
int known_magic::select_spell (Character & guy)
Definition at line 2737 of file magic.cpp.
 {
     // max width of spell names
     const int max_spell_name_length = get_spellname_max_width();
     std::vector<spell *> known_spells = get_spells();
     uilist spell_menu;
     spell_menu.w_height_setup = [&]() -> int {
         return clamp( static_cast<int>( known_spells.size() ), 24, TERMY * 9 / 10 );
     };
     const auto calc_width = []() -> int {
         return std::max( 80, TERMX * 3 / 8 );
     };
     spell_menu.w_width_setup = calc_width;
     spell_menu.pad_right_setup = [&]() -> int {
         return calc_width() - max_spell_name_length - 5;
     };
     spell_menu.title = _( "Choose a Spell" );
     spell_menu.input_category = "SPELL_MENU";
     spell_menu.additional_actions.emplace_back( "CHOOSE_INVLET", translation() );
     spell_menu.additional_actions.emplace_back( "CAST_IGNORE", translation() );
     spell_menu.additional_actions.emplace_back( "SCROLL_UP_SPELL_MENU", translation() );
     spell_menu.additional_actions.emplace_back( "SCROLL_DOWN_SPELL_MENU", translation() );
     spell_menu.additional_actions.emplace_back( "SCROLL_FAVORITE", translation() );
     spell_menu.hilight_disabled = true;
     spellcasting_callback cb( known_spells, casting_ignore );
     spell_menu.callback = &cb;
     spell_menu.add_category( "all", _( "All" ) );
     spell_menu.add_category( "favorites", _( "Favorites" ) );
     std::vector<std::pair<std::string, std::string>> categories;
     for( const spell *s : known_spells ) {
         if( s->can_cast( guy ) && ( s->spell_class().is_valid() || s->spell_class() == trait_NONE ) ) {
             const std::string spell_class_name = s->spell_class() == trait_NONE ? _( "Classless" ) :
                                                  s->spell_class().obj().name();
             categories.emplace_back( s->spell_class().str(), spell_class_name );
             std::sort( categories.begin(), categories.end(), []( const std::pair<std::string, std::string> &a,
             const std::pair<std::string, std::string> &b ) {
                 return localized_compare( a.second, b.second );
             } );
             const auto itr = std::unique( categories.begin(), categories.end() );
             categories.erase( itr, categories.end() );
         }
     }
     for( std::pair<std::string, std::string> &cat : categories ) {
         spell_menu.add_category( cat.first, cat.second );
     }
     spell_menu.set_category_filter( [&guy, known_spells]( const uilist_entry & entry,
     const std::string & key )->bool {
         if( key == "all" )
         {
             return true;
         } else if( key == "favorites" )
         {
             return guy.magic->is_favorite( known_spells[entry.retval]->id() );
         }
         return ( known_spells[entry.retval]->spell_class().is_valid() || known_spells[entry.retval]->spell_class() == trait_NONE ) && known_spells[entry.retval]->spell_class().str() == key;
     } );
     if( !favorites.empty() ) {
         spell_menu.set_category( "favorites" );
     } else {
         spell_menu.set_category( "all" );
     }
     std::set<int> used_invlets{ cb.reserved_invlets };
     for( size_t i = 0; i < known_spells.size(); i++ ) {
         spell_menu.addentry( static_cast<int>( i ), known_spells[i]->can_cast( guy ),
                              get_invlet( known_spells[i]->id(), used_invlets ), known_spells[i]->name() );
     }
     reflesh_favorite( &spell_menu, known_spells );
     spell_menu.query();
     casting_ignore = static_cast<spellcasting_callback *>( spell_menu.callback )->casting_ignore;
     return spell_menu.ret;
 }
References _, a, uilist::add_category(), uilist::addentry(), uilist::additional_actions, b, uilist::callback, casting_ignore, clamp(), favorites, get_invlet(), get_spellname_max_width(), get_spells(), uilist::hilight_disabled, uilist::input_category, Character::magic, max(), om_direction::name(), uilist::pad_right_setup, uilist::query(), reflesh_favorite(), spellcasting_callback::reserved_invlets, uilist::ret, uilist_entry::retval, uilist::set_category(), uilist::set_category_filter(), TERMX, TERMY, uilist::title, trait_NONE, uilist::w_height_setup, and uilist::w_width_setup.
serialize()
void known_magic::serialize (JsonOut & json) const
Definition at line 1923 of file magic.cpp.
 {
     json.start_object();
     json.member( "mana", mana );
     json.member( "spellbook" );
     json.start_array();
     for( const auto &pair : spellbook ) {
         json.start_object();
         json.member( "id", pair.second.id() );
         json.member( "xp", pair.second.xp() );
         json.end_object();
     }
     json.end_array();
     json.member( "invlets", invlets );
     json.member( "favorites", favorites );
     json.end_object();
 }
References JsonOut::end_array(), JsonOut::end_object(), favorites, invlets, mana, JsonOut::member(), spellbook, JsonOut::start_array(), and JsonOut::start_object().
set_invlet()
bool known_magic::set_invlet (const spell_id & sp, int invlet, const std::set< int > & used_invlets)
Definition at line 2679 of file magic.cpp.
 {
     if( used_invlets.count( invlet ) > 0 ) {
         return false;
     }
     invlets[sp] = invlet;
     return true;
 }
References invlets.
set_mana()
void known_magic::set_mana (int new_mana)
Definition at line 2141 of file magic.cpp.
 {
     mana = new_mana;
 }
References mana.
Referenced by mod_mana().
set_spell_exp()
void known_magic::set_spell_exp (const spell_id & sp, int new_exp, const Character * guy)
Definition at line 2079 of file magic.cpp.
 {
     spell temp_spell( sp->id );
     if( !knows_spell( sp ) ) {
         if( new_exp >= 0 ) {
             temp_spell.set_exp( new_exp );
             spellbook.emplace( sp->id, spell( temp_spell ) );
             get_event_bus().send<event_type::character_learns_spell>( guy->getID(), sp->id );
         }
     } else {
         if( new_exp >= 0 ) {
             spell &temp_sp = get_spell( sp );
             int old_level = temp_sp.get_level();
             temp_sp.set_exp( new_exp );
             if( guy->is_avatar() && old_level != temp_sp.get_level() ) {
                 get_event_bus().send<event_type::player_levels_spell>( guy->getID(), sp->id, temp_sp.get_level(),
                         sp->spell_class );
             }
         } else {
             get_event_bus().send<event_type::character_forgets_spell>( guy->getID(), sp->id );
             spellbook.erase( sp );
         }
     }
 }
References character_forgets_spell, character_learns_spell, get_event_bus(), spell::get_level(), get_spell(), Character::getID(), spell_type::id, Creature::is_avatar(), knows_spell(), player_levels_spell, event_bus::send(), spell::set_exp(), spell_type::spell_class, and spellbook.
set_spell_level()
void known_magic::set_spell_level (const spell_id & sp, int new_level, const Character * guy)
Definition at line 2059 of file magic.cpp.
 {
     spell temp_spell( sp->id );
     if( !knows_spell( sp ) ) {
         if( new_level >= 0 ) {
             temp_spell.set_level( *guy, new_level );
             spellbook.emplace( sp->id, spell( temp_spell ) );
             get_event_bus().send<event_type::character_learns_spell>( guy->getID(), sp->id );
         }
     } else {
         if( new_level >= 0 ) {
             spell &temp_sp = get_spell( sp );
             temp_sp.set_level( *guy, new_level );
         } else {
             get_event_bus().send<event_type::character_forgets_spell>( guy->getID(), sp->id );
             spellbook.erase( sp );
         }
     }
 }
References character_forgets_spell, character_learns_spell, get_event_bus(), get_spell(), Character::getID(), spell_type::id, knows_spell(), event_bus::send(), spell::set_level(), and spellbook.
spells()
std::vector< spell_id > known_magic::spells () const
Definition at line 2174 of file magic.cpp.
 {
     std::vector<spell_id> spell_ids;
     spell_ids.reserve( spellbook.size() );
     for( const std::pair<const spell_id, spell> &pair : spellbook ) {
         spell_ids.emplace_back( pair.first );
     }
     return spell_ids;
 }
References spellbook.
Referenced by get_spells().
time_to_learn_spell() [1/2]
int known_magic::time_to_learn_spell (const Character & guy, const spell_id & sp) const
Definition at line 2244 of file magic.cpp.
 {
     dialogue d( get_talker_for( guy ), nullptr );
     const int base_time = to_moves<int>( 30_minutes );
     const double int_modifier = ( guy.get_int() - 8.0 ) / 8.0;
     const double skill_modifier = guy.get_skill_level( sp->skill ) / 10.0;
     return base_time * ( 1.0 + sp->difficulty.evaluate( d ) / ( 1.0 + int_modifier + skill_modifier ) );
 }
References spell_type::difficulty, dbl_or_var::evaluate(), Character::get_int(), Character::get_skill_level(), get_talker_for(), and spell_type::skill.
Referenced by time_to_learn_spell().
time_to_learn_spell() [2/2]
int known_magic::time_to_learn_spell (const Character & guy, const std::string & str) const
Definition at line 2239 of file magic.cpp.
 {
     return time_to_learn_spell( guy, spell_id( str ) );
 }
References spell_id, and time_to_learn_spell().
toggle_favorite()
void known_magic::toggle_favorite (const spell_id & sp)
Definition at line 2693 of file magic.cpp.
 {
     if( favorites.count( sp ) > 0 ) {
         favorites.erase( sp );
     } else {
         favorites.emplace( sp );
     }
 }
References favorites.
update_mana()
void known_magic::update_mana (const Character & guy, float turns)
Definition at line 2165 of file magic.cpp.
 {
     // mana should replenish in 8 hours.
     const double full_replenish = to_turns<double>( 8_hours );
     const double ratio = turns / full_replenish;
     mod_mana( guy, std::floor( ratio * guy.calculate_by_enchantment( static_cast<double>( max_mana(
                                    guy ) ), enchant_vals::mod::REGEN_MANA ) ) );
 }
References Character::calculate_by_enchantment(), floor(), max_mana(), mod_mana(), and enchant_vals::REGEN_MANA.
Member Data Documentation
caster_level_adjustment
double known_magic::caster_level_adjustment
Definition at line 712 of file magic.h.
Referenced by clear_opens_spellbook_data(), and evaluate_opens_spellbook_data().
caster_level_adjustment_by_school
std::map<trait_id, double> known_magic::caster_level_adjustment_by_school
Definition at line 714 of file magic.h.
Referenced by clear_opens_spellbook_data(), and evaluate_opens_spellbook_data().
caster_level_adjustment_by_spell
std::map<spell_id, double> known_magic::caster_level_adjustment_by_spell
Definition at line 713 of file magic.h.
Referenced by clear_opens_spellbook_data(), and evaluate_opens_spellbook_data().
casting_ignore
bool known_magic::casting_ignore = false
Definition at line 661 of file magic.h.
Referenced by select_spell().
favorites
std::unordered_set<spell_id> known_magic::favorites private
Definition at line 653 of file magic.h.
Referenced by deserialize(), is_favorite(), select_spell(), serialize(), and toggle_favorite().
invlets
std::map<spell_id, int> known_magic::invlets private
Definition at line 651 of file magic.h.
Referenced by deserialize(), get_invlet(), rem_invlet(), serialize(), and set_invlet().
mana
int known_magic::mana = 0 private
Definition at line 657 of file magic.h.
Referenced by available_mana(), deserialize(), known_magic(), mod_mana(), serialize(), and set_mana().
mana_base
int known_magic::mana_base = 0 private
Definition at line 655 of file magic.h.
Referenced by known_magic(), and max_mana().
spellbook
std::map<spell_id, spell> known_magic::spellbook private
Definition at line 649 of file magic.h.
Referenced by deserialize(), forget_spell(), get_spell(), get_spellbook(), get_spells(), knows_spell(), learn_spell(), serialize(), set_spell_exp(), set_spell_level(), and spells().
The documentation for this class was generated from the following files:
src/magic.h
src/magic.cpp