Cataclysm DDA: recipe Class Reference
recipe Class Reference
#include <recipe.h>
Public Member Functions
recipe ()
bool is_null () const
operator bool () const
const itype_id & result () const
const std::string & variant () const
const itype_id & container_id () const
int get_difficulty (const Character &crafter) const
int get_skill_cap () const
const requirement_data & simple_requirements () const
Fetch combined requirement data (inline and via "using" syntax).
const deduped_requirement_data & deduped_requirements () const
const recipe_id & ident () const
bool is_blacklisted () const
bool will_be_blacklisted () const
std::function< bool(const item &)> get_component_filter (recipe_filter_flags=recipe_filter_flags::none) const
bool npc_can_craft (std::string &reason) const
requirement_data disassembly_requirements () const
If recipe can be used for disassembly fetch the combined requirements.
std::string result_name (bool decorated=false) const
std::string primary_skill_string (const Character &c) const
std::string required_skills_string (const Character &c) const
std::string required_proficiencies_string (const Character *c) const
std::string used_proficiencies_string (const Character *c) const
std::string missing_proficiencies_string (const Character *c) const
std::string recipe_proficiencies_string () const
std::vector< proficiency_id > required_proficiencies () const
bool character_has_required_proficiencies (const Character &c) const
std::vector< proficiency_id > used_proficiencies () const
float proficiency_time_maluses (const Character &crafter) const
float max_proficiency_time_maluses (const Character &crafter) const
float proficiency_skill_maluses (const Character &crafter) const
float max_proficiency_skill_maluses (const Character &crafter) const
float exertion_level () const
std::string required_all_skills_string (const std::map< skill_id, int > &) const
std::string batch_savings_string () const
std::vector< item > create_results (int batch=1, item_components *used=nullptr) const
std::vector< item > create_byproducts (int batch=1) const
std::map< itype_id, int > get_byproducts () const
bool in_byproducts (const itype_id &it) const
bool has_byproducts () const
int64_t batch_time (const Character &guy, int batch, float multiplier, size_t assistants) const
time_duration batch_duration (const Character &guy, int batch=1, float multiplier=1.0, size_t assistants=0) const
time_duration time_to_craft (const Character &guy, recipe_time_flag flags=recipe_time_flag::none) const
int64_t time_to_craft_moves (const Character &guy, recipe_time_flag flags=recipe_time_flag::none) const
bool has_flag (const std::string &flag_name) const
bool is_reversible () const
void load (const JsonObject &jo, const std::string &src)
void finalize ()
std::string get_consistency_error () const
Returns a non-empty string describing an inconsistency (if any) in the recipe.
bool is_practice () const
bool is_nested () const
bool is_blueprint () const
const update_mapgen_id & get_blueprint () const
const translation & blueprint_name () const
const translation & blueprint_parameter_ui_string (const std::string &param_name, const cata_variant &arg_value) const
const std::vector< itype_id > & blueprint_resources () const
const std::vector< std::pair< std::string, int > > & blueprint_provides () const
const std::vector< std::pair< std::string, int > > & blueprint_requires () const
const std::vector< std::pair< std::string, int > > & blueprint_excludes () const
const parameterized_build_reqs & blueprint_build_reqs () const
void check_blueprint_requirements ()
Calculate blueprint requirements according to changed terrain and furniture tiles, then check the calculated requirements against blueprint requirements specified in JSON.
bool hot_result () const
bool removes_raw () const
int makes_amount () const
Public Attributes
bool was_loaded = false
bool obsolete = false
std::string category
std::string subcategory
translation description
translation name_
int difficulty = 0
bool never_learn = false
Prevent this recipe from ever being added to the player's learned recipes (used for special NPC crafting)
std::vector< effect_on_condition_id > result_eocs
skill_id skill_used
std::map< skill_id, int > required_skills
std::vector< recipe_proficiency > proficiencies
std::map< skill_id, int > autolearn_requirements
std::map< skill_id, int > learn_by_disassembly
std::map< itype_id, book_recipe_data > booksets
std::optional< practice_recipe_data > practice_data
std::set< recipe_id > nested_category_data
std::set< flag_id > flags_to_delete
Private Types
using TranslationMap = std::map< std::string, translation >
Private Member Functions
std::vector< item > create_result (bool set_components, bool is_food, item_components *used=nullptr) const
void incorporate_build_reqs ()
void add_requirements (const std::vector< std::pair< requirement_id, int >> &reqs)
Private Attributes
itype_id result_ = itype_id::NULL_ID()
std::string variant_
int64_t time = 0
std::string exertion_str
float exertion = 0.0f
recipe_id id = recipe_id::NULL_ID()
std::vector< std::pair< recipe_id, mod_id > > src
abstract bool = false
Abstract recipes can be inherited from but are themselves disposed of at finalization.
bool autolearn = false
set learning requirements equal to required skills at finalization?
bool contained = false
Does the item spawn contained in container?
bool sealed = true
Does the container spawn sealed?
itype_id container = itype_id::NULL_ID()
What does the item spawn contained in? Unset ("null") means default container.
std::string container_variant
What variant of the above container should be used? Unset ("") means a randomly chosen variant if it has variants.
bool reversible = false
Can recipe be used for disassembly of result via disassembly_requirements.
int64_t uncraft_time = 0
Time (in moves) to disassemble if different to assembly.
std::vector< std::pair< requirement_id, int > > reqs_external
External requirements (via "using" syntax) where second field is multiplier.
std::vector< std::pair< requirement_id, int > > reqs_internal
Requires specified inline with the recipe (and replaced upon inheritance)
requirement_data requirements_
Combined requirements cached when recipe finalized.
deduped_requirement_data deduped_requirements_
Deduped version constructed from the above requirements_.
std::set< std::string > flags
std::optional< int > charges
If set (zero or positive) set charges of output result for items counted by charges.
std::map< itype_id, int > byproducts
Legacy definitions for byproducts.
std::optional< item_group_id > byproduct_group
Item group representing byproducts.
double batch_rscale = 0.0
int batch_rsize = 0
int result_mult = 1
update_mapgen_id blueprint
translation bp_name
std::map< std::string, TranslationMap > bp_parameter_names
std::vector< itype_id > bp_resources
std::vector< std::pair< std::string, int > > bp_provides
std::vector< std::pair< std::string, int > > bp_requires
bp_requires specifies which other basecamp components need to exist before this one.
std::vector< std::pair< std::string, int > > bp_excludes
bool bp_autocalc = false
Blueprint requirements either autocalculcated or explicitly specified.
bool check_blueprint_needs = false
cata::value_ptr< parameterized_build_reqs > bp_build_reqs
Friends
class recipe_dictionary
struct mod_tracker
Detailed Description
Definition at line 86 of file recipe.h.
Member Typedef Documentation
TranslationMap
using recipe::TranslationMap = std::map<std::string, translation> private
Definition at line 367 of file recipe.h.
Constructor & Destructor Documentation
recipe()
recipe::recipe ()
Definition at line 50 of file recipe.cpp.
 : skill_used( skill_id::NULL_ID() ) {}
Member Function Documentation
add_requirements()
void recipe::add_requirements (const std::vector< std::pair< requirement_id, int >> & reqs) private
Definition at line 658 of file recipe.cpp.
 {
     requirements_ = std::accumulate( reqs.begin(), reqs.end(), requirements_ );
 }
References requirements_.
Referenced by finalize().
batch_duration()
time_duration recipe::batch_duration (const Character & guy, int batch = 1, float multiplier = 1.0, size_t assistants = 0) const
Definition at line 71 of file recipe.cpp.
 {
     return time_duration::from_turns( batch_time( guy, batch, multiplier, assistants ) / 100 );
 }
References batch_time(), and time_duration::from_turns().
Referenced by basecamp::craft_description(), basecamp::om_upgrade_description(), basecamp::recipe_batch_max(), basecamp::start_crafting(), and basecamp::start_fortifications().
batch_savings_string()
std::string recipe::batch_savings_string () const
Definition at line 1209 of file recipe.cpp.
 {
     return ( batch_rsize != 0 ) ?
            string_format( _( "%d%% at >%d units" ), static_cast<int>( batch_rscale * 100 ), batch_rsize )
            : _( "none" );
 }
References _, batch_rscale, batch_rsize, and string_format().
Referenced by recipe_info().
batch_time()
int64_t recipe::batch_time (const Character & guy, int batch, float multiplier, size_t assistants) const
Definition at line 100 of file recipe.cpp.
 {
     // 1.0f is full speed
     // 0.33f is 1/3 speed
     if( multiplier == 0.0f ) {
         // If an item isn't craftable in the dark, show the time to complete as if you could craft it
         multiplier = 1.0f;
     }
     const double local_time = static_cast<double>( time_to_craft_moves( guy ) ) / multiplier;
     // if recipe does not benefit from batching and we have no assistants, don't do unnecessary additional calculations
     if( batch_rscale == 0.0 && assistants == 0 ) {
         return static_cast<int64_t>( local_time ) * batch;
     }
     double total_time = 0.0;
     // if recipe does not benefit from batching but we do have assistants, skip calculating the batching scale factor
     if( batch_rscale == 0.0f ) {
         total_time = local_time * batch;
     } else {
         // recipe benefits from batching, so batching scale factor needs to be calculated
         // At batch_rsize, incremental time increase is 99.5% of batch_rscale
         const double scale = batch_rsize / 6.0f;
         for( int x = 0; x < batch; x++ ) {
             // scaled logistic function output
             const double logf = ( 2.0 / ( 1.0 + std::exp( -( x / scale ) ) ) ) - 1.0;
             total_time += local_time * ( 1.0 - ( batch_rscale * logf ) );
         }
     }
     //Assistants can decrease the time for production but never less than that of one unit
     if( assistants == 1 ) {
         total_time = total_time * .75;
     } else if( assistants >= 2 ) {
         total_time = total_time * .60;
     }
     if( total_time < local_time ) {
         total_time = local_time;
     }
     return static_cast<int64_t>( total_time );
 }
References batch_rscale, batch_rsize, and time_to_craft_moves().
Referenced by batch_duration(), craft_activity_actor::do_turn(), and Character::expected_time_to_craft().
blueprint_build_reqs()
const parameterized_build_reqs & recipe::blueprint_build_reqs () const
Definition at line 1404 of file recipe.cpp.
 {
     if( !bp_build_reqs ) {
         cata_fatal( "Accessing absent blueprint_build_reqs in recipe %s", ident().str() );
     }
     return *bp_build_reqs;
 }
References bp_build_reqs, cata_fatal, and ident().
Referenced by basecamp::available_upgrades(), basecamp_action_components::choose_components(), basecamp::get_available_missions_by_dir(), basecamp::om_upgrade_description(), basecamp::start_multi_mission(), and basecamp::start_upgrade().
blueprint_excludes()
const std::vector< std::pair< std::string, int > > & recipe::blueprint_excludes () const
Definition at line 1399 of file recipe.cpp.
 {
     return bp_excludes;
 }
References bp_excludes.
Referenced by basecamp::available_upgrades().
blueprint_name()
const translation & recipe::blueprint_name () const
Definition at line 1356 of file recipe.cpp.
 {
     return bp_name;
 }
References bp_name.
Referenced by basecamp::available_upgrades(), and basecamp::survey_return().
blueprint_parameter_ui_string()
const translation & recipe::blueprint_parameter_ui_string (const std::string & param_name, const cata_variant & arg_value) const
Definition at line 1361 of file recipe.cpp.
 {
     auto param = bp_parameter_names.find( param_name );
     if( param == bp_parameter_names.end() ) {
         debugmsg( "Parameter name %s missing from bp_parameter_names in %s",
                   param_name, ident().str() );
         static const translation error = to_translation( "[bad param name]" );
         return error;
     }
     const TranslationMap &translations = param->second;
     auto arg = translations.find( arg_value.get_string() );
     if( arg == translations.end() ) {
         debugmsg( "Argument value %s missing from bp_parameter_names[\"%s\"] in %s",
                   arg_value.get_string(), param_name, ident().str() );
         static const translation error = to_translation( "[bad argument value]" );
         return error;
     }
     return arg->second;
 }
References bp_parameter_names, debugmsg, error, cata_variant::get_string(), ident(), and to_translation().
Referenced by basecamp::name_display_of().
blueprint_provides()
const std::vector< std::pair< std::string, int > > & recipe::blueprint_provides () const
Definition at line 1389 of file recipe.cpp.
 {
     return bp_provides;
 }
References bp_provides.
Referenced by basecamp::update_in_progress(), and basecamp::update_provides().
blueprint_requires()
const std::vector< std::pair< std::string, int > > & recipe::blueprint_requires () const
Definition at line 1394 of file recipe.cpp.
 {
     return bp_requires;
 }
References bp_requires.
Referenced by basecamp::available_upgrades(), and salt_water_pipe_segment_of().
blueprint_resources()
const std::vector< itype_id > & recipe::blueprint_resources () const
Definition at line 1384 of file recipe.cpp.
 {
     return bp_resources;
 }
References bp_resources.
Referenced by basecamp::update_resources().
character_has_required_proficiencies()
bool recipe::character_has_required_proficiencies (const Character & c) const
Definition at line 1008 of file recipe.cpp.
 {
     for( const proficiency_id &id : required_proficiencies() ) {
         if( !c.has_proficiency( id ) && !helpers_have_proficiencies( c, id ) ) {
             return false;
         }
     }
     return true;
 }
References c, helpers_have_proficiencies(), and required_proficiencies().
Referenced by anonymous_namespace{crafting_gui.cpp}::availability::availability(), Character::can_continue_craft(), Character::can_make(), Character::can_start_craft(), craft_command::execute(), and Character::recipe_success_roll_data().
check_blueprint_requirements()
void recipe::check_blueprint_requirements ()
Calculate blueprint requirements according to changed terrain and furniture tiles, then check the calculated requirements against blueprint requirements specified in JSON.
If there's any inconsistency, it issues a debug message. This is only used in unit tests so as to speed up data loading in gameplay.
Definition at line 1412 of file recipe.cpp.
 {
     build_reqs total_reqs =
         get_build_reqs_for_furn_ter_ids( get_changed_ids_from_update( blueprint, {} ) );
     if( bp_build_reqs->reqs_by_parameters.size() != 1 ) {
         debugmsg( "Cannot check blueprint reqs for blueprints with parameters" );
         return;
     }
     const std::pair<const mapgen_arguments, build_reqs> &no_param_reqs =
         *bp_build_reqs->reqs_by_parameters.begin();
     if( !no_param_reqs.first.map.empty() ) {
         debugmsg( "Cannot check blueprint reqs for blueprints with parameters" );
         return;
     }
     const build_reqs &reqs = no_param_reqs.second;
     requirement_data req_data_blueprint( reqs.raw_reqs );
     requirement_data req_data_calc( total_reqs.raw_reqs );
     // do not consolidate req_data_blueprint: it actually changes the meaning of the requirement.
     // instead we enforce specifying the exact consolidated requirement.
     req_data_calc.consolidate();
     if( reqs.time != total_reqs.time || reqs.skills != total_reqs.skills
         || !req_data_blueprint.has_same_requirements_as( req_data_calc ) ) {
         std::ostringstream os;
         JsonOut jsout( os, /*pretty_print=*/true );
         jsout.start_object();
         jsout.member( "time" );
         if( total_reqs.time % 100 == 0 ) {
             dump_to_json_string( time_duration::from_turns( total_reqs.time / 100 ),
                                  jsout, time_duration::units );
         } else {
             // cannot precisely represent the value using time_duration format,
             // write integer instead.
             jsout.write( total_reqs.time );
         }
         jsout.member( "skills" );
         jsout.start_array( /*wrap=*/!total_reqs.skills.empty() );
         for( const std::pair<const skill_id, int> &p : total_reqs.skills ) {
             jsout.start_array();
             jsout.write( p.first );
             jsout.write( p.second );
             jsout.end_array();
         }
         jsout.end_array();
         jsout.member( "inline" );
         req_data_calc.dump( jsout );
         jsout.end_object();
         debugmsg( "Specified blueprint requirements of %1$s does not match calculated requirements.\n"
                   "Make one of the following changes to resolve this issue:\n"
                   "- Specify \"check_blueprint_needs\": false to disable the check.\n"
                   "- Remove \"blueprint_needs\" from the recipe json to have the requirements be autocalculated.\n"
                   "- Update \"blueprint_needs\" to the following value (you can use tools/update_blueprint_needs.py):\n"
                   // mark it for the auto-update python script
                   "~~~ auto-update-blueprint: %1$s\n"
                   "%2$s\n"
                   "~~~ end-auto-update",
                   id.str(), os.str() );
     }
 }
References blueprint, bp_build_reqs, requirement_data::consolidate(), debugmsg, requirement_data::dump(), dump_to_json_string(), JsonOut::end_array(), JsonOut::end_object(), time_duration::from_turns(), get_build_reqs_for_furn_ter_ids(), get_changed_ids_from_update(), requirement_data::has_same_requirements_as(), JsonOut::member(), build_reqs::raw_reqs, build_reqs::skills, JsonOut::start_array(), JsonOut::start_object(), build_reqs::time, time_duration::units, and JsonOut::write().
Referenced by finalize().
container_id()
const itype_id& recipe::container_id () const inline
Definition at line 119 of file recipe.h.
{
             return container;
         }
References container.
Referenced by recipe_result_info_cache::get_result_data().
create_byproducts()
std::vector< item > recipe::create_byproducts (int batch = 1) const
Definition at line 858 of file recipe.cpp.
 {
     std::vector<item> bps;
     if( !byproducts.empty() ) {
         create_byproducts_legacy( byproducts, bps, batch );
     }
     if( !!byproduct_group ) {
         create_byproducts_group( *byproduct_group, bps, batch );
     }
     return bps;
 }
References byproduct_group, byproducts, create_byproducts_group(), and create_byproducts_legacy().
Referenced by Character::check_eligible_containers_for_crafting(), Character::complete_craft(), Character::compute_nutrient_range(), and basecamp::start_crafting().
create_result()
std::vector< item > recipe::create_result (bool set_components, bool is_food, item_components * used = nullptr) const private
Definition at line 723 of file recipe.cpp.
 {
     item newit( result_, calendar::turn, item::default_charges_tag{} );
     if( !variant().empty() ) {
         newit.set_itype_variant( variant() );
     }
     if( newit.has_flag( flag_VARSIZE ) ) {
         newit.set_flag( flag_FIT );
     }
     // Newly-crafted items are perfect by default. Inspect their materials to see if they shouldn't be
     if( used ) {
         newit.inherit_flags( *used, *this );
     }
     for( const flag_id &flag : flags_to_delete ) {
         newit.unset_flag( flag );
     }
     // If the recipe has a `FULL_MAGAZINE` flag, fill it with ammo
     if( newit.is_magazine() && has_flag( flag_FULL_MAGAZINE ) ) {
         newit.ammo_set( newit.ammo_default(),
                         newit.ammo_capacity( item::find_type( newit.ammo_default() )->ammo->type ) );
     }
     int amount = charges ? *charges : newit.count();
     bool is_cooked = hot_result() || removes_raw();
     if( set_components ) {
         set_new_comps( newit, amount, used, is_food, is_cooked );
     }
     if( contained ) {
         newit = newit.in_container( container, amount, sealed, container_variant );
         return { newit };
     } else if( newit.count_by_charges() ) {
         newit.charges = amount;
         return { newit };
     } else {
         std::vector<item> items;
         for( int i = 0; i < amount; i++ ) {
             if( set_components ) {
                 set_new_comps( newit, amount, used, is_food, is_cooked );
             }
             items.push_back( newit );
         }
         return items;
     }
 }
References itype::ammo, charges, contained, container, container_variant, item::find_type(), flag_FIT, flag_FULL_MAGAZINE(), flag_VARSIZE, flags_to_delete, has_flag(), hot_result(), removes_raw(), result_, sealed, item::set_itype_variant(), set_new_comps(), calendar::turn, and variant().
Referenced by create_results().
create_results()
std::vector< item > recipe::create_results (int batch = 1, item_components * used = nullptr) const
Definition at line 776 of file recipe.cpp.
 {
     std::vector<item> items;
     for( int i = 0; i < batch; i++ ) {
         item_components batch_comps;
         item temp( result_ );
         bool is_uncraftable = recipe_dictionary::get_uncraft( result_ ) && !result_->count_by_charges() &&
                               is_reversible();
         bool is_food_no_override = temp.is_food() && !temp.has_flag( flag_NUTRIENT_OVERRIDE );
         bool set_components = used && ( is_uncraftable || is_food_no_override );
         bool is_cooked = hot_result() || removes_raw();
         if( set_components ) {
             batch_comps = used->split( batch, i, is_cooked );
         }
         for( int j = 0; j < result_mult; j++ ) {
             item_components mult_comps = batch_comps.split( result_mult, j, is_cooked );
             std::vector<item> newits = create_result( set_components, temp.is_food(), &mult_comps );
             if( !result_->count_by_charges() ) {
                 items.reserve( items.size() + newits.size() );
                 items.insert( items.end(), newits.begin(), newits.end() );
             } else {
                 for( const item &it : newits ) {
                     // try to combine batch results for liquid handling
                     auto found = std::find_if( items.begin(), items.end(), [it]( const item & rhs ) {
                         return it.can_combine( rhs );
                     } );
                     if( found != items.end() ) {
                         found->combine( it );
                     } else {
                         items.emplace_back( it );
                     }
                 }
             }
         }
     }
     return items;
 }
References itype::count_by_charges(), create_result(), flag_NUTRIENT_OVERRIDE, recipe_dictionary::get_uncraft(), hot_result(), is_reversible(), removes_raw(), result_, result_mult, item_components::split(), and temp.
Referenced by Character::can_disassemble(), Character::check_eligible_containers_for_crafting(), Character::complete_craft(), iexamine::mill_finalize(), and basecamp::start_crafting().
deduped_requirements()
const deduped_requirement_data& recipe::deduped_requirements () const inline
Definition at line 151 of file recipe.h.
{
             return deduped_requirements_;
         }
References deduped_requirements_.
Referenced by basecamp::add_available_recipes(), anonymous_namespace{crafting_gui.cpp}::availability::availability(), Character::can_make(), Character::can_start_craft(), basecamp_action_components::choose_components(), choose_crafter(), craft_command::execute(), iuse::multicooker(), basecamp::recipe_batch_max(), recipe_info(), basecamp::start_crafting(), and basecamp::start_fortifications().
disassembly_requirements()
requirement_data recipe::disassembly_requirements () const inline
If recipe can be used for disassembly fetch the combined requirements.
Definition at line 176 of file recipe.h.
{
             if( reversible ) {
                 return simple_requirements().disassembly_requirements();
             } else {
                 return {};
             }
         }
References requirement_data::disassembly_requirements(), reversible, and simple_requirements().
Referenced by Character::can_disassemble(), can_do_activity_there(), Character::complete_disassemble(), disassemble_inventory_preset::disassemble_inventory_preset(), item::disassembly_info(), and item::get_uncraft_components().
exertion_level()
float recipe::exertion_level () const
Definition at line 1140 of file recipe.cpp.
 {
     return exertion;
 }
References exertion.
Referenced by basecamp::craft_description(), basecamp::get_available_missions_by_dir(), recipe_info(), disassemble_activity_actor::start(), craft_activity_actor::start(), basecamp::start_crafting(), and basecamp::start_multi_mission().
finalize()
void recipe::finalize ()
Definition at line 580 of file recipe.cpp.
 {
     if( bp_autocalc ) {
         bp_build_reqs = calculate_all_blueprint_reqs( blueprint, bp_parameter_names );
     } else if( test_mode && check_blueprint_needs ) {
         check_blueprint_requirements();
     }
     if( !blueprint.is_empty() ) {
         incorporate_build_reqs();
     } else {
         // concatenate both external and inline requirements
         add_requirements( reqs_external );
         add_requirements( reqs_internal );
         reqs_external.clear();
         reqs_internal.clear();
         deduped_requirements_ = deduped_requirement_data( requirements_, ident() );
     }
     if( contained && container.is_null() ) {
         container = item::find_type( result_ )->default_container.value_or( itype_null );
         if( item::find_type( result_ )->default_container_variant.has_value() ) {
             container_variant = item::find_type( result_ )->default_container_variant.value();
         }
     }
     std::set<proficiency_id> required;
     std::set<proficiency_id> used;
     for( recipe_proficiency &rpof : proficiencies ) {
         if( !rpof.id.is_valid() ) {
             debugmsg( "proficiency %s does not exist in recipe %s", rpof.id.str(), id.str() );
         }
         if( rpof.required && rpof.time_multiplier != 0.0f ) {
             debugmsg( "proficiencies in recipes cannot be both required and provide a malus in %s",
                       rpof.id.str(), id.str() );
         }
         if( required.count( rpof.id ) || used.count( rpof.id ) ) {
             debugmsg( "proficiency %s listed twice recipe %s", rpof.id.str(),
                       id.str() );
         }
         if( rpof.time_multiplier < 1.0f && rpof.id->default_time_multiplier() < 1.0f ) {
             debugmsg( "proficiency %s provides a time bonus for not being known in recipe %s.  Time multiplier: %s Default multiplier: %s",
                       rpof.id.str(), id.str(), rpof.time_multiplier, rpof.id->default_time_multiplier() );
         }
         if( rpof.time_multiplier == 0.0f ) {
             rpof.time_multiplier = rpof.id->default_time_multiplier();
         }
         if( !rpof._skill_penalty_assigned ) {
             rpof.skill_penalty = rpof.id->default_skill_penalty();
         }
         if( rpof.skill_penalty < 0.f && rpof.id->default_skill_penalty() < 0.f ) {
             debugmsg( "proficiency %s provides a skill bonus for not being known in recipe %s skill penalty: %g default multiplier: %g",
                       rpof.id.str(), id.str(), rpof.skill_penalty, rpof.id->default_skill_penalty() );
         }
         // Now that we've done the error checking, log that a proficiency with this id is used
         if( rpof.required ) {
             required.insert( rpof.id );
         } else {
             used.insert( rpof.id );
         }
     }
     if( autolearn && autolearn_requirements.empty() ) {
         autolearn_requirements = required_skills;
         if( skill_used ) {
             autolearn_requirements[ skill_used ] = difficulty;
         }
     }
 }
References add_requirements(), autolearn, autolearn_requirements, blueprint, bp_autocalc, bp_build_reqs, bp_parameter_names, calculate_all_blueprint_reqs(), check_blueprint_needs, check_blueprint_requirements(), contained, container, container_variant, debugmsg, deduped_requirements_, itype::default_container, itype::default_container_variant, difficulty, item::find_type(), ident(), incorporate_build_reqs(), string_id< T >::is_empty(), string_id< T >::is_null(), itype_null, proficiencies, reqs_external, reqs_internal, required_skills, requirements_, result_, skill_used, and test_mode.
get_blueprint()
const update_mapgen_id & recipe::get_blueprint () const
Definition at line 1351 of file recipe.cpp.
 {
     return blueprint;
 }
References blueprint.
Referenced by extract_and_check_orientation_flags(), talk_function::start_camp(), basecamp::start_upgrade(), and basecamp::upgrade_return().
get_byproducts()
std::map< itype_id, int > recipe::get_byproducts () const
Definition at line 870 of file recipe.cpp.
 {
     std::map<itype_id, int> ret;
     if( !byproducts.empty() ) {
         for( const std::pair<const itype_id, int> &byproduct : byproducts ) {
             int count = byproduct.first->count_by_charges() ? byproduct.first->charges_default() : 1;
             ret.emplace( byproduct.first, byproduct.second * count );
         }
     }
     if( !!byproduct_group ) {
         std::vector<item> tmp = item_group::items_from( *byproduct_group );
         for( const item &i : tmp ) {
             if( i.count_by_charges() ) {
                 ret.emplace( i.typeId(), i.charges );
             } else {
                 ret.emplace( i.typeId(), 1 );
             }
         }
     }
     return ret;
 }
References byproduct_group, byproducts, item_group::items_from(), and cata::hash64_detail::ret.
Referenced by recipe_result_info_cache::get_byproducts_data(), npc_can_craft(), and recipe_info().
get_component_filter()
std::function< bool(const item &)> recipe::get_component_filter (recipe_filter_flags flags = recipe_filter_flags::none) const
Definition at line 1256 of file recipe.cpp.
 {
     const item result( result_ );
     // Disallow crafting of non-perishables with rotten components
     // Make an exception for items with the ALLOW_ROTTEN flag such as seeds
     const bool recipe_forbids_rotten =
         result.is_food() && !result.goes_bad() && !has_flag( "ALLOW_ROTTEN" );
     const bool flags_forbid_rotten =
         static_cast<bool>( flags & recipe_filter_flags::no_rotten );
     const bool flags_forbid_favorites =
         static_cast<bool>( flags & recipe_filter_flags::no_favorite );
     std::function<bool( const item & )> rotten_filter = return_true<item>;
     if( recipe_forbids_rotten || flags_forbid_rotten ) {
         rotten_filter = []( const item & component ) {
             return !component.rotten();
         };
     }
     // Disallow crafting using favorited items as components
     std::function<bool( const item & )> favorite_filter = return_true<item>;
     if( flags_forbid_favorites ) {
         favorite_filter = []( const item & component ) {
             return !component.is_favorite;
         };
     }
     // If the result is made hot, we can allow frozen components.
     // EDIBLE_FROZEN components ( e.g. flour, chocolate ) are allowed as well
     // Otherwise forbid them
     std::function<bool( const item & )> frozen_filter = return_true<item>;
     if( result.has_temperature() && !hot_result() ) {
         frozen_filter = []( const item & component ) {
             return !component.has_flag( flag_FROZEN ) || component.has_flag( flag_EDIBLE_FROZEN );
         };
     }
     // Disallow usage of non-full magazines as components
     // This is primarily used to require a fully charged battery, but works for any magazine.
     std::function<bool( const item & )> magazine_filter = return_true<item>;
     if( has_flag( "NEED_FULL_MAGAZINE" ) ) {
         magazine_filter = []( const item & component ) {
             if( component.ammo_remaining() == 0 ) {
                 return false;
             }
             return !component.is_magazine() ||
                    ( component.ammo_remaining() >= component.ammo_capacity( component.ammo_data()->ammo->type ) );
         };
     }
     return [ rotten_filter, favorite_filter, frozen_filter,
                    magazine_filter ]( const item & component ) {
         return is_crafting_component( component ) &&
                rotten_filter( component ) &&
                favorite_filter( component ) &&
                frozen_filter( component ) &&
                magazine_filter( component );
     };
 }
References bool, flag_EDIBLE_FROZEN, flag_FROZEN, flags, has_flag(), hot_result(), is_crafting_component(), no_favorite, no_rotten, result(), result_, and component::type.
Referenced by basecamp::add_available_recipes(), anonymous_namespace{crafting_gui.cpp}::availability::availability(), basecamp::available_upgrades(), Character::can_continue_craft(), Character::can_make(), Character::can_start_craft(), craft_command::check_item_components_missing(), choose_crafter(), basecamp::craft_description(), craft_command::create_in_progress_craft(), craft_command::execute(), basecamp::om_upgrade_description(), basecamp::recipe_batch_max(), recipe_info(), basecamp::start_crafting(), basecamp::start_fortifications(), and basecamp::start_upgrade().
get_consistency_error()
std::string recipe::get_consistency_error () const
Returns a non-empty string describing an inconsistency (if any) in the recipe.
Definition at line 663 of file recipe.cpp.
 {
     if( category == "CC_BUILDING" ) {
         if( is_blueprint() || oter_str_id( result_.c_str() ).is_valid() ) {
             return std::string();
         }
         return "defines invalid result";
     }
     if( !item::type_is_defined( result_ ) ) {
         return "defines invalid result";
     }
     const auto is_invalid_bp = []( const std::pair<itype_id, int> &elem ) {
         return !item::type_is_defined( elem.first );
     };
     if( std::any_of( byproducts.begin(), byproducts.end(), is_invalid_bp ) ) {
         return "defines invalid byproducts";
     }
     if( !contained && !container.is_null() ) {
         return "defines container but not contained";
     }
     if( !item::type_is_defined( container ) ) {
         return "specifies unknown container";
     }
     const auto is_invalid_skill = []( const std::pair<skill_id, int> &elem ) {
         return !elem.first.is_valid();
     };
     if( ( skill_used && !skill_used.is_valid() ) ||
         std::any_of( required_skills.begin(), required_skills.end(), is_invalid_skill ) ) {
         return "uses invalid skill";
     }
     const auto is_invalid_book = []( const std::pair<itype_id, book_recipe_data> &elem ) {
         return !item::find_type( elem.first )->book;
     };
     if( std::any_of( booksets.begin(), booksets.end(), is_invalid_book ) ) {
         return "defines invalid book";
     }
     return std::string();
 }
References itype::book, booksets, byproducts, string_id< T >::c_str(), category, contained, container, item::find_type(), is_blueprint(), string_id< T >::is_null(), string_id< T >::is_valid(), required_skills, result_, skill_used, and item::type_is_defined().
Referenced by recipe_dictionary::finalize_internal().
get_difficulty()
int recipe::get_difficulty (const Character & crafter) const
Definition at line 52 of file recipe.cpp.
 {
     if( is_practice() && skill_used ) {
         return clamp( static_cast<int>( crafter.get_all_skills().get_skill_level( skill_used ) ),
                       practice_data->min_difficulty, practice_data->max_difficulty );
     } else {
         return difficulty;
     }
 }
References clamp(), difficulty, Character::get_all_skills(), SkillLevelMap::get_skill_level(), is_practice(), practice_data, and skill_used.
Referenced by anonymous_namespace{crafting_gui.cpp}::availability::availability(), and primary_skill_string().
get_skill_cap()
int recipe::get_skill_cap () const
Definition at line 62 of file recipe.cpp.
 {
     if( is_practice() ) {
         return practice_data->skill_limit - 1;
     } else {
         return difficulty * 1.25;
     }
 }
References difficulty, is_practice(), and practice_data.
Referenced by cannot_gain_skill_or_prof(), Character::craft_skill_gain(), and Character::start_craft().
has_byproducts()
bool recipe::has_byproducts () const
Definition at line 892 of file recipe.cpp.
 {
     return !byproducts.empty() || !!byproduct_group;
 }
References byproduct_group, and byproducts.
Referenced by Character::complete_craft(), recipe_result_info_cache::get_result_data(), and recipe_info().
has_flag()
bool recipe::has_flag (const std::string & flag_name) const
Definition at line 145 of file recipe.cpp.
 {
     return flags.count( flag_name );
 }
References flags.
Referenced by assemble_skill_details(), Character::complete_disassemble(), connection_direction_of(), Character::crafting_speed_multiplier(), create_result(), draw_can_craft_indicator(), extract_and_check_orientation_flags(), get_component_filter(), item::inherit_flags(), Character::initialize(), Character::lighting_craft_speed_multiplier(), recipe_info(), and basecamp::start_upgrade().
hot_result()
bool recipe::hot_result () const
Definition at line 1483 of file recipe.cpp.
 {
     // Check if the recipe tools make this food item hot upon making it.
     // We don't actually know which specific tool the player used/will use here, but
     // we're checking for a class of tools; because of the way requirements
     // processing works, the "surface_heat" id gets nuked into an actual
     // list of tools, see data/json/recipes/cooking_tools.json.
     //
     // Currently it's checking for a hotplate because that's a
     // suitable item in both the "surface_heat" and "water_boiling_heat"
     // tools, and it's usually the first item in a list of tools so if this
     // does get heated we'll find it right away.
     //
     // Atomic coffee is an outlier in that it is a hot drink that cannot be crafted
     // with any of the usual tools except the atomic coffee maker, which is why
     // the check includes this tool in addition to the hotplate.
     //
     // TODO: Make this less of a hack
     if( item( result_ ).has_temperature() ) {
         const requirement_data::alter_tool_comp_vector &tool_lists = simple_requirements().get_tools();
         for( const std::vector<tool_comp> &tools : tool_lists ) {
             for( const tool_comp &t : tools ) {
                 if( ( t.type == itype_hotplate ) || ( t.type == itype_atomic_coffeepot ) ) {
                     return true;
                 }
             }
         }
     }
     return false;
 }
References requirement_data::get_tools(), item, itype_atomic_coffeepot, itype_hotplate, result_, and simple_requirements().
Referenced by Character::complete_craft(), Character::compute_nutrient_range(), create_result(), create_results(), get_component_filter(), and Character::select_item_component().
ident()
const recipe_id& recipe::ident () const inline
Definition at line 155 of file recipe.h.
{
             return id;
         }
References id.
Referenced by blueprint_build_reqs(), blueprint_parameter_ui_string(), recipe_dictionary::check_consistency(), Character::complete_disassemble(), craft_command::execute(), recipe_subset::expanded(), recipe_subset::favorite(), finalize(), recipe_dictionary::find_obsoletes(), get_recipe_result_item(), Character::get_recipe_weighted_skill_average(), item::get_recursive_disassemble_moves(), recipe_subset::hidden(), game::inventory_item_menu(), recipe_dictionary::load(), iuse::multicooker(), rate_action_view_recipe(), select_crafter_and_crafting_recipe(), basecamp::start_upgrade(), and basecamp::upgrade_return().
in_byproducts()
bool recipe::in_byproducts (const itype_id & it) const
Definition at line 897 of file recipe.cpp.
 {
     return ( !byproducts.empty() && byproducts.find( it ) != byproducts.end() ) ||
            ( !!byproduct_group && item_group::group_contains_item( *byproduct_group, it ) );
 }
References byproduct_group, byproducts, and item_group::group_contains_item().
incorporate_build_reqs()
void recipe::incorporate_build_reqs () private
Definition at line 1525 of file recipe.cpp.
 {
     if( !bp_build_reqs ) {
         bp_build_reqs = cata::make_value<parameterized_build_reqs>();
     }
     for( std::pair<const mapgen_arguments, build_reqs> &p : bp_build_reqs->reqs_by_parameters ) {
         build_reqs &reqs = p.second;
         reqs.time += time;
         for( const std::pair<const skill_id, int> &p : required_skills ) {
             int &val = reqs.skills[p.first];
             val = std::max( val, p.second );
         }
         reqs.consolidate( reqs_internal, reqs_external );
     }
 }
References bp_build_reqs, build_reqs::consolidate(), max(), reqs_external, reqs_internal, required_skills, build_reqs::skills, build_reqs::time, and time.
Referenced by finalize().
is_blacklisted()
bool recipe::is_blacklisted () const inline
Definition at line 159 of file recipe.h.
{
             return requirements_.is_blacklisted();
         }
References requirement_data::is_blacklisted(), and requirements_.
Referenced by recipe_dictionary::finalize_internal().
is_blueprint()
bool recipe::is_blueprint () const
Definition at line 1346 of file recipe.cpp.
 {
     return !blueprint.is_empty();
 }
References blueprint, and string_id< T >::is_empty().
Referenced by basecamp_action_components::choose_components(), Item_factory::find_template(), get_consistency_error(), and basecamp::om_upgrade_description().
is_nested()
bool recipe::is_nested () const
Definition at line 1341 of file recipe.cpp.
 {
     return !nested_category_data.empty();
 }
References nested_category_data.
Referenced by anonymous_namespace{crafting_gui.cpp}::availability::availability(), check_nested_has_recipes(), choose_crafter(), list_nested(), recipe_info(), and select_crafter_and_crafting_recipe().
is_null()
bool recipe::is_null () const inline
Definition at line 103 of file recipe.h.
{
             return id.is_null();
         }
Referenced by item::final_info(), disassemble_inventory_preset::is_shown(), mill_activate(), iexamine::mill_finalize(), operator bool(), and rate_action_view_recipe().
is_practice()
bool recipe::is_practice () const
Definition at line 1336 of file recipe.cpp.
 {
     return practice_data.has_value();
 }
References practice_data.
Referenced by assemble_skill_details(), anonymous_namespace{crafting_gui.cpp}::availability::availability(), item::book_info(), choose_crafter(), Character::complete_craft(), craft_activity_actor::do_turn(), get_difficulty(), get_skill_cap(), avatar::identify(), Character::initialize(), npc_can_craft(), recipe_info(), and select_crafter_and_crafting_recipe().
is_reversible()
bool recipe::is_reversible () const inline
Definition at line 268 of file recipe.h.
{
             return reversible;
         }
References reversible.
Referenced by create_results(), and recipe_dictionary::finalize().
load()
void recipe::load (const JsonObject & jo, const std::string & src)
Definition at line 150 of file recipe.cpp.
 {
     bool strict = src == "dda";
     abstract = jo.has_string( "abstract" );
     const std::string type = jo.get_string( "type" );
     if( jo.has_member( "result_eocs" ) ) {
         result_eocs.clear();
         for( JsonValue jv : jo.get_array( "result_eocs" ) ) {
             result_eocs.push_back( effect_on_conditions::load_inline_eoc( jv, src ) );
         }
     }
     if( abstract ) {
         id = recipe_id( jo.get_string( "abstract" ) );
     } else if( type == "practice" ) {
         id = recipe_id( jo.get_string( "id" ) );
         if( jo.has_member( "result" ) ) {
             jo.throw_error_at( "result", "Practice recipes should not have result (use byproducts)" );
         }
         if( jo.has_member( "difficulty" ) ) {
             jo.throw_error_at( "difficulty",
                                "Practice recipes should not have difficulty (use practice_data)" );
         }
     } else if( type == "nested_category" ) {
         id = recipe_id( jo.get_string( "id" ) );
         if( jo.has_member( "result" ) ) {
             jo.throw_error_at( "result", "nested category should not have result" );
         }
         if( jo.has_member( "autolearn" ) ) {
             jo.throw_error_at( "autolearn",
                                "nested category should not have an autolearn, they are only displayed if one of their recipes should be." );
         }
         // nested recipes are never learned directly
         never_learn = true;
     } else {
         if( !jo.read( "result", result_, true ) && !result_ ) {
             if( result_eocs.empty() ) {
                 jo.throw_error( "Recipe missing result" );
             } else {
                 mandatory( jo, false, "name", name_ );
                 id = recipe_id( jo.get_string( "id" ) );
             }
         } else {
             id = recipe_id( result_.str() );
         }
     }
     if( type == "recipe" ) {
         optional( jo, was_loaded, "variant", variant_ );
         if( !variant_.empty() && !abstract ) {
             id = recipe_id( id.str() + "_" + variant_ );
         }
         if( jo.has_string( "id_suffix" ) ) {
             if( abstract ) {
                 jo.throw_error_at( "id_suffix", "abstract recipe cannot specify id_suffix" );
             }
             id = recipe_id( id.str() + "_" + jo.get_string( "id_suffix" ) );
         }
     }
     if( jo.has_bool( "obsolete" ) ) {
         assign( jo, "obsolete", obsolete );
     }
     // If it's an obsolete recipe, we don't need any more data, skip loading
     if( obsolete ) {
         return;
     }
     if( jo.has_string( "time" ) ) {
         time = to_moves<int>( read_from_json_string<time_duration>( jo.get_member( "time" ),
                               time_duration::units ) );
     }
     assign( jo, "difficulty", difficulty, strict, 0, MAX_SKILL );
     assign( jo, "flags", flags );
     // automatically set contained if we specify as container
     assign( jo, "contained", contained, strict );
     contained |= assign( jo, "container", container, strict );
     optional( jo, false, "container_variant", container_variant );
     assign( jo, "sealed", sealed, strict );
     if( jo.has_array( "batch_time_factors" ) ) {
         JsonArray batch = jo.get_array( "batch_time_factors" );
         batch_rscale = batch.get_int( 0 ) / 100.0;
         batch_rsize  = batch.get_int( 1 );
     }
     assign( jo, "charges", charges );
     assign( jo, "result_mult", result_mult );
     assign( jo, "skill_used", skill_used, strict );
     if( jo.has_member( "skills_required" ) ) {
         JsonArray sk = jo.get_array( "skills_required" );
         required_skills.clear();
         if( sk.empty() ) {
             // clear all requirements
         } else if( sk.has_array( 0 ) ) {
             // multiple requirements
             for( JsonArray arr : sk ) {
                 required_skills[skill_id( arr.get_string( 0 ) )] = arr.get_int( 1 );
             }
         } else {
             // single requirement
             required_skills[skill_id( sk.get_string( 0 ) )] = sk.get_int( 1 );
         }
     }
     jo.read( "proficiencies", proficiencies );
     // simplified autolearn sets requirements equal to required skills at finalization
     if( jo.has_bool( "autolearn" ) ) {
         assign( jo, "autolearn", autolearn );
     } else if( jo.has_array( "autolearn" ) ) {
         autolearn = true;
         for( JsonArray arr : jo.get_array( "autolearn" ) ) {
             autolearn_requirements[skill_id( arr.get_string( 0 ) )] = arr.get_int( 1 );
         }
     }
     // Mandatory: This recipe's exertion level
     mandatory( jo, was_loaded, "activity_level", exertion_str );
     // Remove after 0.H
     if( exertion_str == "fake" ) {
         debugmsg( "Depreciated activity level \"fake\" found in recipe %s from source %s. Setting activity level to MODERATE_EXERCISE.",
                   id.c_str(), src );
         exertion_str = "MODERATE_EXERCISE";
     }
     const auto it = activity_levels_map.find( exertion_str );
     if( it == activity_levels_map.end() ) {
         jo.throw_error_at(
             "activity_level", string_format( "Invalid activity level %s", exertion_str ) );
     }
     exertion = it->second;
     // Never let the player have a debug or NPC recipe
     if( jo.has_bool( "never_learn" ) ) {
         assign( jo, "never_learn", never_learn );
     }
     if( jo.has_member( "decomp_learn" ) ) {
         learn_by_disassembly.clear();
         if( jo.has_int( "decomp_learn" ) ) {
             if( !skill_used ) {
                 jo.throw_error( "decomp_learn specified with no skill_used" );
             }
             assign( jo, "decomp_learn", learn_by_disassembly[skill_used] );
         } else if( jo.has_array( "decomp_learn" ) ) {
             for( JsonArray arr : jo.get_array( "decomp_learn" ) ) {
                 learn_by_disassembly[skill_id( arr.get_string( 0 ) )] = arr.get_int( 1 );
             }
         }
     }
     if( jo.has_member( "book_learn" ) ) {
         booksets.clear();
         if( jo.has_array( "book_learn" ) ) {
             for( JsonArray arr : jo.get_array( "book_learn" ) ) {
                 booksets.emplace( itype_id( arr.get_string( 0 ) ), book_recipe_data{ arr.size() > 1 ? arr.get_int( 1 ) : -1 } );
             }
         } else {
             mandatory( jo, false, "book_learn", booksets );
         }
     }
     if( jo.has_member( "delete_flags" ) ) {
         flags_to_delete = jo.get_tags<flag_id>( "delete_flags" );
     }
     // recipes not specifying any external requirements inherit from their parent recipe (if any)
     if( jo.has_string( "using" ) ) {
         reqs_external = { { requirement_id( jo.get_string( "using" ) ), 1 } };
     } else if( jo.has_array( "using" ) ) {
         reqs_external.clear();
         for( JsonArray cur : jo.get_array( "using" ) ) {
             reqs_external.emplace_back( requirement_id( cur.get_string( 0 ) ), cur.get_int( 1 ) );
         }
     }
     // inline requirements are always replaced (cannot be inherited)
     reqs_internal.clear();
     // These cannot be inherited
     bp_autocalc = false;
     check_blueprint_needs = false;
     bp_build_reqs.reset();
     if( type == "recipe" ) {
         mandatory( jo, was_loaded, "category", category );
         mandatory( jo, was_loaded, "subcategory", subcategory );
         assign( jo, "description", description, strict );
         if( jo.has_bool( "reversible" ) ) {
             assign( jo, "reversible", reversible, strict );
         } else if( jo.has_object( "reversible" ) ) {
             reversible = true;
             // Convert duration to time in moves
             uncraft_time = to_moves<int>( read_from_json_string<time_duration>
                                           ( jo.get_object( "reversible" ).get_member( "time" ), time_duration::units ) );
         }
         if( jo.has_member( "byproducts" ) ) {
             if( this->reversible ) {
                 jo.throw_error( "Recipe cannot be reversible and have byproducts" );
             }
             byproducts.clear();
             for( JsonArray arr : jo.get_array( "byproducts" ) ) {
                 itype_id byproduct( arr.get_string( 0 ) );
                 byproducts[ byproduct ] += arr.size() == 2 ? arr.get_int( 1 ) : 1;
             }
         }
         if( jo.has_member( "byproduct_group" ) ) {
             if( this->reversible ) {
                 jo.throw_error( "Recipe cannot be reversible and have byproducts" );
             }
             byproduct_group = item_group::load_item_group( jo.get_member( "byproduct_group" ),
                               "collection", "byproducts of recipe " + id.str() );
         }
         assign( jo, "construction_blueprint", blueprint );
         if( !blueprint.is_empty() ) {
             assign( jo, "blueprint_name", bp_name );
             assign( jo, "blueprint_parameter_names", bp_parameter_names );
             bp_resources.clear();
             for( const std::string resource : jo.get_array( "blueprint_resources" ) ) {
                 bp_resources.emplace_back( resource );
             }
             for( JsonObject provide : jo.get_array( "blueprint_provides" ) ) {
                 bp_provides.emplace_back( provide.get_string( "id" ),
                                           provide.get_int( "amount", 1 ) );
             }
             // all blueprints provide themselves with needing it written in JSON
             bp_provides.emplace_back( result_.str(), 1 );
             for( JsonObject require : jo.get_array( "blueprint_requires" ) ) {
                 bp_requires.emplace_back( require.get_string( "id" ),
                                           require.get_int( "amount", 1 ) );
             }
             // all blueprints exclude themselves with needing it written in JSON
             bp_excludes.emplace_back( result_.str(), 1 );
             for( JsonObject exclude : jo.get_array( "blueprint_excludes" ) ) {
                 bp_excludes.emplace_back( exclude.get_string( "id" ),
                                           exclude.get_int( "amount", 1 ) );
             }
             check_blueprint_needs = jo.get_bool( "check_blueprint_needs", true );
             bool has_needs = jo.has_member( "blueprint_needs" );
             if( has_needs && !bp_parameter_names.empty() ) {
                 debugmsg( "blueprint %s has parameters but also provides explicit needs; "
                           "these are incompatible", result_.str() );
             }
             if( bp_parameter_names.empty() ) {
                 bp_build_reqs = cata::make_value<parameterized_build_reqs>();
                 build_reqs &default_reqs =
                     bp_build_reqs->reqs_by_parameters.emplace().first->second;
                 const JsonObject jneeds = jo.get_object( "blueprint_needs" );
                 if( jneeds.has_member( "time" ) ) {
                     default_reqs.time =
                         to_moves<int>( read_from_json_string<time_duration>(
                                            jneeds.get_member( "time" ), time_duration::units ) );
                 }
                 if( jneeds.has_member( "skills" ) ) {
                     std::vector<std::pair<skill_id, int>> blueprint_skills;
                     jneeds.read( "skills", blueprint_skills );
                     default_reqs.skills = { blueprint_skills.begin(), blueprint_skills.end() };
                 }
                 if( jneeds.has_member( "inline" ) ) {
                     const requirement_id req_id( "inline_blueprint_" + type + "_" + id.str() );
                     requirement_data::load_requirement( jneeds.get_object( "inline" ), req_id );
                     default_reqs.raw_reqs.emplace( req_id, 1 );
                 }
             }
             if( check_blueprint_needs && !has_needs ) {
                 bp_autocalc = true;
             }
         }
     } else if( type == "practice" ) {
         mandatory( jo, false, "name", name_ );
         mandatory( jo, was_loaded, "category", category );
         mandatory( jo, was_loaded, "subcategory", subcategory );
         assign( jo, "description", description, strict );
         mandatory( jo, was_loaded, "practice_data", practice_data );
         if( jo.has_member( "byproducts" ) ) {
             byproducts.clear();
             for( JsonArray arr : jo.get_array( "byproducts" ) ) {
                 itype_id byproduct( arr.get_string( 0 ) );
                 byproducts[ byproduct ] += arr.size() == 2 ? arr.get_int( 1 ) : 1;
             }
         }
         if( jo.has_member( "byproduct_group" ) ) {
             if( this->reversible ) {
                 jo.throw_error( "Recipe cannot be reversible and have byproducts" );
             }
             byproduct_group = item_group::load_item_group( jo.get_member( "byproduct_group" ),
                               "collection", "byproducts of recipe " + id.str() );
         }
     } else if( type == "uncraft" ) {
         reversible = true;
     } else if( type == "nested_category" ) {
         mandatory( jo, false, "name", name_ );
         mandatory( jo, was_loaded, "category", category );
         mandatory( jo, was_loaded, "subcategory", subcategory );
         assign( jo, "description", description, strict );
         mandatory( jo, was_loaded, "nested_category_data", nested_category_data );
     } else {
         jo.throw_error_at( "type", "unknown recipe type" );
     }
     const requirement_id req_id( "inline_" + type + "_" + id.str() );
     requirement_data::load_requirement( jo, req_id );
     reqs_internal.emplace_back( req_id, 1 );
 }
References activity_levels_map, assign(), autolearn, autolearn_requirements, batch_rscale, batch_rsize, blueprint, booksets, bp_autocalc, bp_build_reqs, bp_excludes, bp_name, bp_parameter_names, bp_provides, bp_requires, bp_resources, byproduct_group, byproducts, category, charges, check_blueprint_needs, contained, container, container_variant, debugmsg, description, difficulty, JsonArray::empty(), exertion, exertion_str, flags, flags_to_delete, JsonObject::get_array(), JsonObject::get_bool(), JsonArray::get_int(), JsonObject::get_member(), JsonObject::get_object(), JsonObject::get_string(), JsonArray::get_string(), JsonObject::get_tags(), JsonArray::has_array(), JsonObject::has_array(), JsonObject::has_bool(), JsonObject::has_int(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), string_id< T >::is_empty(), itype_id, learn_by_disassembly, effect_on_conditions::load_inline_eoc(), item_group::load_item_group(), requirement_data::load_requirement(), mandatory, MAX_SKILL, name_, nested_category_data, never_learn, obsolete, optional(), practice_data, proficiencies, build_reqs::raw_reqs, JsonObject::read(), reqs_external, reqs_internal, required_skills, result_, result_eocs, result_mult, reversible, sealed, skill_id, skill_used, build_reqs::skills, src, Json::str(), string_id< T >::str(), strict, string_format(), subcategory, JsonObject::throw_error(), JsonObject::throw_error_at(), build_reqs::time, time, type, uncraft_time, time_duration::units, variant_, and was_loaded.
Referenced by recipe_dictionary::load().
makes_amount()
int recipe::makes_amount () const
Definition at line 1514 of file recipe.cpp.
 {
     int makes = 1;
     if( charges.has_value() ) {
         makes = charges.value();
     } else if( item::count_by_charges( result_ ) ) {
         makes = item::find_type( result_ )->charges_default();
     }
     return makes * result_mult;
 }
References charges, itype::charges_default(), item::count_by_charges(), item::find_type(), result_, and result_mult.
Referenced by Character::compute_nutrient_range(), item::final_info(), recipe_result_info_cache::get_result_data(), and recipe_info().
max_proficiency_skill_maluses()
float recipe::max_proficiency_skill_maluses (const Character & crafter) const
Definition at line 1099 of file recipe.cpp.
 {
     float total_malus = 0.f;
     for( const recipe_proficiency &prof : proficiencies ) {
         total_malus += prof.skill_penalty;
     }
     return total_malus;
 }
References proficiencies.
Referenced by anonymous_namespace{crafting_gui.cpp}::availability::get_max_proficiency_skill_maluses().
max_proficiency_time_maluses()
float recipe::max_proficiency_time_maluses (const Character & crafter) const
Definition at line 1064 of file recipe.cpp.
 {
     float total_malus = 1.0f;
     for( const recipe_proficiency &prof : proficiencies ) {
         total_malus *= prof.time_multiplier;
     }
     return total_malus;
 }
References proficiencies.
Referenced by anonymous_namespace{crafting_gui.cpp}::availability::get_max_proficiency_time_maluses().
missing_proficiencies_string()
std::string recipe::missing_proficiencies_string (const Character * c) const
Definition at line 1108 of file recipe.cpp.
 {
     if( crafter == nullptr ) {
         return { };
     }
     std::vector<prof_penalty> missing_profs;
     const book_proficiency_bonuses book_bonuses =
         crafter->crafting_inventory().get_book_proficiency_bonuses();
     for( const recipe_proficiency &prof : proficiencies ) {
         if( !prof.required ) {
             if( !( crafter->has_proficiency( prof.id ) || helpers_have_proficiencies( *crafter, prof.id ) ) ) {
                 prof_penalty pen = { prof.id,
                                      proficiency_time_malus( *crafter, prof ),
                                      proficiency_skill_malus( *crafter, prof )
                                    };
                 pen.mitigated = book_bonuses.time_factor( pen.id ) != 0.0f ||
                                 book_bonuses.fail_factor( pen.id ) != 0.0f;
                 missing_profs.push_back( pen );
             }
         }
     }
     std::string color = "dark_gray";
     std::string missing = enumerate_as_string( missing_profs.begin(),
     missing_profs.end(), [&]( const prof_penalty & prof ) {
         return profstring( prof, color, crafter->has_prof_prereqs( prof.id ) ? "cyan" : "red" );
     } );
     return missing;
 }
References color(), Character::crafting_inventory(), enumerate_as_string(), book_proficiency_bonuses::fail_factor(), inventory::get_book_proficiency_bonuses(), Character::has_proficiency(), helpers_have_proficiencies(), Character::id, prof_penalty::id, prof_penalty::mitigated, proficiencies, proficiency_skill_malus(), proficiency_time_malus(), and book_proficiency_bonuses::time_factor().
Referenced by recipe_info().
npc_can_craft()
bool recipe::npc_can_craft (std::string & reason) const
Definition at line 1317 of file recipe.cpp.
 {
     if( is_practice() ) {
         reason = _( "Ordering NPC to practice is not implemented yet." );
         return false;
     }
     if( result()->phase != phase_id::SOLID ) {
         reason = _( "Ordering NPC to craft non-solid item is not implemented yet." );
         return false;
     }
     for( const auto& [bp, _] : get_byproducts() ) {
         if( bp->phase != phase_id::SOLID ) {
             reason = _( "Ordering NPC to craft non-solid item is not implemented yet." );
             return false;
         }
     }
     return true;
 }
References _, bp, get_byproducts(), is_practice(), result(), and SOLID.
Referenced by anonymous_namespace{crafting_gui.cpp}::availability::availability(), choose_crafter(), npc::do_npc_craft(), and recipe_info().
operator bool()
recipe::operator bool () const inline explicit
Definition at line 107 of file recipe.h.
{
             return !is_null();
         }
References is_null().
primary_skill_string()
std::string recipe::primary_skill_string (const Character & c) const
Definition at line 1183 of file recipe.cpp.
 {
     std::vector<std::pair<skill_id, int>> skillList;
     if( skill_used ) {
         skillList.emplace_back( skill_used, get_difficulty( c ) );
     }
     return required_skills_as_string( skillList, c );
 }
References c, get_difficulty(), required_skills_as_string(), and skill_used.
Referenced by recipe_info().
proficiency_skill_maluses()
float recipe::proficiency_skill_maluses (const Character & crafter) const
Definition at line 1090 of file recipe.cpp.
 {
     float total_malus = 0.f;
     for( const recipe_proficiency &prof : proficiencies ) {
         total_malus += proficiency_skill_malus( crafter, prof );
     }
     return total_malus;
 }
References proficiencies, and proficiency_skill_malus().
Referenced by anonymous_namespace{crafting_gui.cpp}::availability::get_proficiency_skill_maluses().
proficiency_time_maluses()
float recipe::proficiency_time_maluses (const Character & crafter) const
Definition at line 1055 of file recipe.cpp.
 {
     float total_malus = 1.0f;
     for( const recipe_proficiency &prof : proficiencies ) {
         total_malus *= proficiency_time_malus( crafter, prof );
     }
     return total_malus;
 }
References proficiencies, and proficiency_time_malus().
Referenced by anonymous_namespace{crafting_gui.cpp}::availability::get_proficiency_time_maluses(), and time_to_craft_moves().
recipe_proficiencies_string()
std::string recipe::recipe_proficiencies_string () const
Definition at line 981 of file recipe.cpp.
 {
     std::vector<proficiency_id> profs;
     profs.reserve( proficiencies.size() );
     for( const recipe_proficiency &rec : proficiencies ) {
         profs.push_back( rec.id );
     }
     std::string list = enumerate_as_string( profs.begin(),
     profs.end(), [&]( const proficiency_id & id ) {
         return id->name();
     } );
     return list;
 }
References enumerate_as_string(), and proficiencies.
removes_raw()
bool recipe::removes_raw () const
Definition at line 1477 of file recipe.cpp.
 {
     item result( result_ );
     return result.is_comestible() && !result.has_flag( flag_RAW );
 }
References flag_RAW, result(), and result_.
Referenced by create_result(), create_results(), and Character::select_item_component().
required_all_skills_string()
std::string recipe::required_all_skills_string (const std::map< skill_id, int > & skills) const
Definition at line 1199 of file recipe.cpp.
 {
     std::vector<std::pair<skill_id, int>> skillList = sorted_lex( skills );
     // There is primary skill used, add it to the front
     if( skill_used ) {
         skillList.insert( skillList.begin(), std::pair<skill_id, int>( skill_used, difficulty ) );
     }
     return required_skills_as_string( skillList );
 }
References difficulty, required_skills_as_string(), skill_used, and sorted_lex().
Referenced by basecamp::om_upgrade_description().
required_proficiencies()
std::vector< proficiency_id > recipe::required_proficiencies () const
Definition at line 997 of file recipe.cpp.
 {
     std::vector<proficiency_id> ret;
     for( const recipe_proficiency &rec : proficiencies ) {
         if( rec.required ) {
             ret.emplace_back( rec.id );
         }
     }
     return ret;
 }
References proficiencies, and cata::hash64_detail::ret.
Referenced by character_has_required_proficiencies().
required_proficiencies_string()
std::string recipe::required_proficiencies_string (const Character * c) const
Definition at line 903 of file recipe.cpp.
 {
     std::vector<proficiency_id> required_profs;
     for( const recipe_proficiency &rec : proficiencies ) {
         if( rec.required ) {
             required_profs.push_back( rec.id );
         }
     }
     std::string required = enumerate_as_string( required_profs.begin(),
     required_profs.end(), [&]( const proficiency_id & id ) {
         nc_color color;
         if( c != nullptr && c->has_proficiency( id ) ) {
             color = c_green;
         } else if( c != nullptr && helpers_have_proficiencies( *c, id ) ) {
             color = c_yellow;
         } else {
             color = c_red;
         }
         return colorize( id->name(), color );
     } );
     return required;
 }
References c, c_red, c_yellow, color(), colorize(), enumerate_as_string(), helpers_have_proficiencies(), id, and proficiencies.
Referenced by recipe_info().
required_skills_string()
std::string recipe::required_skills_string (const Character & c) const
Definition at line 1194 of file recipe.cpp.
 {
     return required_skills_as_string( sorted_lex( required_skills ), c );
 }
References c, required_skills, required_skills_as_string(), and sorted_lex().
Referenced by recipe_info().
result()
const itype_id& recipe::result () const inline
Definition at line 111 of file recipe.h.
{
             return result_;
         }
References result_.
Referenced by basecamp::available_upgrades(), game::butcher(), Character::complete_craft(), Character::compute_nutrient_range(), Item_factory::finalize(), recipe_dictionary::finalize(), Item_factory::finalize_item_blacklist(), get_component_filter(), get_recipe_result_item(), iuse::multicooker(), npc_can_craft(), peek_related_recipe(), recipe_info(), removes_raw(), and Character::select_item_component().
result_name()
std::string recipe::result_name (bool decorated = false) const
Returns
The name (item::nname) of the resulting item (result).
Parameters
decorated whether the result includes decoration (favorite mark, etc).
Definition at line 1216 of file recipe.cpp.
 {
     std::string name;
     if( !name_.empty() ) {
         name = name_.translated();
     } else if( !variant().empty() ) {
         auto iter_var = std::find_if( result_->variants.begin(), result_->variants.end(),
         [this]( const itype_variant_data & itvar ) {
             return itvar.id == variant();
         } );
         if( iter_var != result_->variants.end() ) {
             name = iter_var->alt_name.translated();
         }
     } else {
         name = item::tname( result_, 1, tname::item_name );
     }
     if( decorated &&
         uistate.favorite_recipes.find( this->ident() ) != uistate.favorite_recipes.end() ) {
         name = "* " + name;
     }
     return name;
 }
References translation::empty(), uistatedata::favorite_recipes, tname::item_name(), om_direction::name(), name_, result_, item::tname(), translation::translated(), uistate, variant(), and itype::variants.
Referenced by assemble_skill_details(), iuse::binder_manage_recipe(), item::book_info(), Character::complete_craft(), iuse::craft(), anonymous_namespace{item_tname.cpp}::craft(), craft_command::execute(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), bookbinder_copy_activity_actor::finish(), avatar::identify(), list_nested(), islot_book::recipe_with_description_t::name(), print_data_handling_tally(), basecamp::start_crafting(), item::tool_info(), and iexamine::workbench_internal().
simple_requirements()
const requirement_data& recipe::simple_requirements () const inline
Fetch combined requirement data (inline and via "using" syntax).
Use simple_requirements() for player display or when you just want to know the requirements as listed in the json files. Use deduped_requirements() to calculate actual craftability of a recipe.
Definition at line 147 of file recipe.h.
{
             return requirements_;
         }
References requirements_.
Referenced by anonymous_namespace{crafting_gui.cpp}::availability::availability(), Character::can_continue_craft(), can_do_activity_there(), Character::compute_nutrient_range(), basecamp::craft_description(), disassembly_requirements(), item::final_info(), recipe_dictionary::find_items_on_loops(), recipe_result_info_cache::get_item_header(), hot_result(), recipe_subset::include(), Character::making_would_work(), mill_activate(), iexamine::mill_finalize(), basecamp::om_upgrade_description(), peek_related_recipe(), and recipe_info().
time_to_craft()
time_duration recipe::time_to_craft (const Character & guy, recipe_time_flag flags = recipe_time_flag::none) const
Definition at line 87 of file recipe.cpp.
 {
     return time_duration::from_moves( time_to_craft_moves( guy, flags ) );
 }
References flags, time_duration::from_moves(), and time_to_craft_moves().
Referenced by add_disassemblables(), and item::disassembly_info().
time_to_craft_moves()
int64_t recipe::time_to_craft_moves (const Character & guy, recipe_time_flag flags = recipe_time_flag::none) const
Definition at line 92 of file recipe.cpp.
 {
     if( flags == recipe_time_flag::ignore_proficiencies ) {
         return time;
     }
     return time * proficiency_time_maluses( guy );
 }
References flags, ignore_proficiencies, proficiency_time_maluses(), and time.
Referenced by batch_time(), game::butcher(), Character::complete_craft(), Character::complete_disassemble(), Character::disassemble(), craft_activity_actor::do_turn(), generic_multi_activity_do(), item::get_recursive_disassemble_moves(), iuse::multicooker(), and time_to_craft().
used_proficiencies()
std::vector< proficiency_id > recipe::used_proficiencies () const
Definition at line 1018 of file recipe.cpp.
 {
     std::vector<proficiency_id> ret;
     for( const recipe_proficiency &rec : proficiencies ) {
         if( !rec.required ) {
             ret.emplace_back( rec.id );
         }
     }
     return ret;
 }
References proficiencies, and cata::hash64_detail::ret.
Referenced by cannot_gain_skill_or_prof().
used_proficiencies_string()
std::string recipe::used_proficiencies_string (const Character * c) const
Definition at line 957 of file recipe.cpp.
 {
     if( c == nullptr ) {
         return { };
     }
     std::vector<prof_penalty> used_profs;
     for( const recipe_proficiency &rec : proficiencies ) {
         if( !rec.required ) {
             if( c->has_proficiency( rec.id ) || helpers_have_proficiencies( *c, rec.id ) )  {
                 used_profs.push_back( { rec.id, rec.time_multiplier, rec.skill_penalty} );
             }
         }
     }
     std::string color = "light_green";
     std::string used = enumerate_as_string( used_profs.begin(),
     used_profs.end(), [&]( const prof_penalty & prof ) {
         return profstring( prof, color );
     } );
     return used;
 }
References c, color(), enumerate_as_string(), helpers_have_proficiencies(), and proficiencies.
Referenced by recipe_info().
variant()
const std::string& recipe::variant () const inline
Definition at line 115 of file recipe.h.
{
             return variant_;
         }
References variant_.
Referenced by create_result(), get_recipe_result_item(), and result_name().
will_be_blacklisted()
bool recipe::will_be_blacklisted () const
Definition at line 1239 of file recipe.cpp.
 {
     if( requirements_.is_blacklisted() ) {
         return true;
     }
     auto any_is_blacklisted = []( const std::vector<std::pair<requirement_id, int>> &reqs ) {
         auto req_is_blacklisted = []( const std::pair<requirement_id, int> &req ) {
             return req.first->is_blacklisted();
         };
         return std::any_of( reqs.begin(), reqs.end(), req_is_blacklisted );
     };
     return any_is_blacklisted( reqs_internal ) || any_is_blacklisted( reqs_external );
 }
References requirement_data::is_blacklisted(), reqs_external, reqs_internal, and requirements_.
Referenced by Item_factory::finalize().
Friends And Related Function Documentation
mod_tracker
friend struct mod_tracker friend
Definition at line 89 of file recipe.h.
recipe_dictionary
friend class recipe_dictionary friend
Definition at line 88 of file recipe.h.
Member Data Documentation
autolearn
bool recipe::autolearn = false private
set learning requirements equal to required skills at finalization?
Definition at line 317 of file recipe.h.
Referenced by finalize(), and load().
autolearn_requirements
std::map<skill_id, int> recipe::autolearn_requirements
Definition at line 192 of file recipe.h.
Referenced by assemble_skill_details(), finalize(), and load().
batch_rscale
double recipe::batch_rscale = 0.0 private
Definition at line 362 of file recipe.h.
Referenced by batch_savings_string(), batch_time(), and load().
batch_rsize
int recipe::batch_rsize = 0 private
Definition at line 363 of file recipe.h.
Referenced by batch_savings_string(), batch_time(), and load().
blueprint
update_mapgen_id recipe::blueprint private
Definition at line 365 of file recipe.h.
Referenced by check_blueprint_requirements(), recipe_dictionary::check_consistency(), finalize(), get_blueprint(), is_blueprint(), and load().
booksets
std::map<itype_id, book_recipe_data> recipe::booksets
Definition at line 195 of file recipe.h.
Referenced by recipe_dictionary::finalize(), Character::get_books_for_recipe(), get_consistency_error(), and load().
bool
abstract recipe::bool = false private
Abstract recipes can be inherited from but are themselves disposed of at finalization.
Definition at line 314 of file recipe.h.
Referenced by get_component_filter().
bp_autocalc
bool recipe::bp_autocalc = false private
Blueprint requirements either autocalculcated or explicitly specified.
These members relate to resolving those blueprint requirements into the standard recipe requirements.
Definition at line 380 of file recipe.h.
Referenced by finalize(), and load().
bp_build_reqs
cata::value_ptr<parameterized_build_reqs> recipe::bp_build_reqs private
Definition at line 382 of file recipe.h.
Referenced by blueprint_build_reqs(), check_blueprint_requirements(), finalize(), incorporate_build_reqs(), and load().
bp_excludes
std::vector<std::pair<std::string, int> > recipe::bp_excludes private
Definition at line 375 of file recipe.h.
Referenced by blueprint_excludes(), and load().
bp_name
translation recipe::bp_name private
Definition at line 366 of file recipe.h.
Referenced by blueprint_name(), and load().
bp_parameter_names
std::map<std::string, TranslationMap> recipe::bp_parameter_names private
Definition at line 368 of file recipe.h.
Referenced by blueprint_parameter_ui_string(), finalize(), and load().
bp_provides
std::vector<std::pair<std::string, int> > recipe::bp_provides private
Definition at line 370 of file recipe.h.
Referenced by blueprint_provides(), and load().
bp_requires
std::vector<std::pair<std::string, int> > recipe::bp_requires private
bp_requires specifies which other basecamp components need to exist before this one.
Whereas bp_build_reqs below contains the material and skills requirements
Definition at line 374 of file recipe.h.
Referenced by blueprint_requires(), and load().
bp_resources
std::vector<itype_id> recipe::bp_resources private
Definition at line 369 of file recipe.h.
Referenced by blueprint_resources(), and load().
byproduct_group
std::optional<item_group_id> recipe::byproduct_group private
Item group representing byproducts.
Definition at line 358 of file recipe.h.
Referenced by create_byproducts(), get_byproducts(), has_byproducts(), in_byproducts(), and load().
byproducts
std::map<itype_id, int> recipe::byproducts private
Legacy definitions for byproducts.
Definition at line 355 of file recipe.h.
Referenced by create_byproducts(), get_byproducts(), get_consistency_error(), has_byproducts(), in_byproducts(), and load().
category
std::string recipe::category
Definition at line 126 of file recipe.h.
Referenced by craft_activity_actor::canceled(), recipe_dictionary::check_consistency(), crafting_allowed(), get_consistency_error(), recipe_subset::include(), load(), and select_crafter_and_crafting_recipe().
charges
std::optional<int> recipe::charges private
If set (zero or positive) set charges of output result for items counted by charges.
Definition at line 352 of file recipe.h.
Referenced by create_result(), load(), and makes_amount().
check_blueprint_needs
bool recipe::check_blueprint_needs = false private
Definition at line 381 of file recipe.h.
Referenced by finalize(), and load().
contained
bool recipe::contained = false private
Does the item spawn contained in container?
Definition at line 320 of file recipe.h.
Referenced by create_result(), finalize(), get_consistency_error(), and load().
container
itype_id recipe::container = itype_id::NULL_ID() private
What does the item spawn contained in? Unset ("null") means default container.
Definition at line 326 of file recipe.h.
Referenced by container_id(), create_result(), finalize(), get_consistency_error(), and load().
container_variant
std::string recipe::container_variant private
What variant of the above container should be used? Unset ("") means a randomly chosen variant if it has variants.
Definition at line 329 of file recipe.h.
Referenced by create_result(), finalize(), and load().
deduped_requirements_
deduped_requirement_data recipe::deduped_requirements_ private
Deduped version constructed from the above requirements_.
Definition at line 347 of file recipe.h.
Referenced by deduped_requirements(), and finalize().
description
translation recipe::description
Definition at line 129 of file recipe.h.
Referenced by Item_factory::find_template(), recipe_result_info_cache::get_result_data(), load(), basecamp::om_upgrade_description(), practice_recipe_description(), and select_crafter_and_crafting_recipe().
difficulty
int recipe::difficulty = 0
Definition at line 133 of file recipe.h.
Referenced by assemble_skill_details(), Character::complete_craft(), Character::complete_disassemble(), basecamp::craft_description(), Character::craft_skill_gain(), SkillLevelMap::exceeds_recipe_requirements(), finalize(), recipe_dictionary::finalize(), item::get_available_recipes(), recipe_subset::get_custom_difficulty(), get_difficulty(), Character::get_recipe_weighted_skill_average(), get_skill_cap(), recipe_subset::include(), load(), Character::morale_crafting_speed_multiplier(), iuse::multicooker(), bookbinder_copy_activity_actor::pages_for_recipe(), Character::recipe_success_roll_data(), required_all_skills_string(), basecamp::start_upgrade(), SkillLevelMap::theoretical_recipe_requirements(), item::tool_info(), and basecamp::upgrade_return().
exertion
float recipe::exertion = 0.0f private
Definition at line 98 of file recipe.h.
Referenced by exertion_level(), and load().
exertion_str
std::string recipe::exertion_str private
Definition at line 97 of file recipe.h.
Referenced by load().
flags
std::set<std::string> recipe::flags private
Definition at line 349 of file recipe.h.
Referenced by get_component_filter(), has_flag(), load(), time_to_craft(), and time_to_craft_moves().
flags_to_delete
std::set<flag_id> recipe::flags_to_delete
Definition at line 201 of file recipe.h.
Referenced by create_result(), and load().
id
recipe_id recipe::id = recipe_id::NULL_ID() private
Definition at line 310 of file recipe.h.
Referenced by recipe_dictionary::finalize(), ident(), and required_proficiencies_string().
learn_by_disassembly
std::map<skill_id, int> recipe::learn_by_disassembly
Definition at line 193 of file recipe.h.
Referenced by Character::can_decomp_learn(), Character::complete_disassemble(), Character::disassemble(), and load().
name_
translation recipe::name_
Definition at line 131 of file recipe.h.
Referenced by load(), and result_name().
nested_category_data
std::set<recipe_id> recipe::nested_category_data
Definition at line 199 of file recipe.h.
Referenced by anonymous_namespace{crafting_gui.cpp}::availability::check_can_craft_nested(), check_nested_has_recipes(), is_nested(), list_nested(), and load().
never_learn
bool recipe::never_learn = false
Prevent this recipe from ever being added to the player's learned recipes (used for special NPC crafting)
Definition at line 173 of file recipe.h.
Referenced by assemble_skill_details(), Character::learn_recipe(), and load().
obsolete
bool recipe::obsolete = false
Definition at line 124 of file recipe.h.
Referenced by Item_factory::finalize(), recipe_dictionary::finalize(), recipe_dictionary::finalize_internal(), Item_factory::finalize_item_blacklist(), and load().
practice_data
std::optional<practice_recipe_data> recipe::practice_data
Definition at line 197 of file recipe.h.
Referenced by get_difficulty(), get_skill_cap(), is_practice(), load(), and practice_recipe_description().
proficiencies
std::vector<recipe_proficiency> recipe::proficiencies
Definition at line 190 of file recipe.h.
Referenced by Character::craft_proficiency_gain(), finalize(), Character::get_recipe_weighted_skill_average(), load(), max_proficiency_skill_maluses(), max_proficiency_time_maluses(), missing_proficiencies_string(), proficiency_skill_maluses(), proficiency_time_maluses(), recipe_proficiencies_string(), required_proficiencies(), required_proficiencies_string(), used_proficiencies(), and used_proficiencies_string().
reqs_external
std::vector<std::pair<requirement_id, int> > recipe::reqs_external private
External requirements (via "using" syntax) where second field is multiplier.
Definition at line 338 of file recipe.h.
Referenced by finalize(), incorporate_build_reqs(), load(), and will_be_blacklisted().
reqs_internal
std::vector<std::pair<requirement_id, int> > recipe::reqs_internal private
Requires specified inline with the recipe (and replaced upon inheritance)
Definition at line 341 of file recipe.h.
Referenced by finalize(), incorporate_build_reqs(), load(), and will_be_blacklisted().
required_skills
std::map<skill_id, int> recipe::required_skills
Definition at line 189 of file recipe.h.
Referenced by assemble_skill_details(), anonymous_namespace{crafting_gui.cpp}::availability::availability(), basecamp::common_salt_water_pipe_construction(), SkillLevelMap::exceeds_recipe_requirements(), finalize(), get_consistency_error(), Character::get_recipe_weighted_skill_average(), incorporate_build_reqs(), load(), Character::morale_crafting_speed_multiplier(), basecamp::om_upgrade_description(), recipe_info(), Character::recipe_success_roll_data(), required_skills_string(), basecamp::start_crafting(), basecamp::start_fortifications(), and SkillLevelMap::theoretical_recipe_requirements().
requirements_
requirement_data recipe::requirements_ private
Combined requirements cached when recipe finalized.
Definition at line 344 of file recipe.h.
Referenced by add_requirements(), finalize(), recipe_dictionary::finalize(), is_blacklisted(), simple_requirements(), and will_be_blacklisted().
result_
itype_id recipe::result_ = itype_id::NULL_ID() private
Definition at line 92 of file recipe.h.
Referenced by create_result(), create_results(), finalize(), recipe_dictionary::finalize(), get_component_filter(), get_consistency_error(), hot_result(), load(), makes_amount(), removes_raw(), result(), and result_name().
result_eocs
std::vector<effect_on_condition_id> recipe::result_eocs
Definition at line 187 of file recipe.h.
Referenced by Character::complete_craft(), and load().
result_mult
int recipe::result_mult = 1 private
Definition at line 364 of file recipe.h.
Referenced by create_results(), load(), and makes_amount().
reversible
bool recipe::reversible = false private
Can recipe be used for disassembly of result via disassembly_requirements.
Definition at line 332 of file recipe.h.
Referenced by disassembly_requirements(), recipe_dictionary::finalize(), is_reversible(), and load().
sealed
bool recipe::sealed = true private
Does the container spawn sealed?
Definition at line 323 of file recipe.h.
Referenced by create_result(), and load().
skill_used
skill_id recipe::skill_used
Definition at line 188 of file recipe.h.
Referenced by assemble_skill_details(), anonymous_namespace{crafting_gui.cpp}::availability::availability(), item::book_info(), cannot_gain_skill_or_prof(), Character::complete_craft(), Character::complete_disassemble(), basecamp::craft_description(), Character::craft_skill_gain(), SkillLevelMap::exceeds_recipe_requirements(), finalize(), item::get_available_recipes(), Character::get_books_for_recipe(), get_consistency_error(), get_difficulty(), Character::get_recipe_weighted_skill_average(), craft_command::get_skill_id(), Character::lighting_craft_speed_multiplier(), load(), Character::morale_crafting_speed_multiplier(), practice_recipe_description(), primary_skill_string(), Character::recipe_success_roll_data(), required_all_skills_string(), basecamp::start_upgrade(), SkillLevelMap::theoretical_recipe_requirements(), and item::tool_info().
src
std::vector<std::pair<recipe_id, mod_id> > recipe::src private
Definition at line 311 of file recipe.h.
Referenced by load(), and recipe_dictionary::load().
subcategory
std::string recipe::subcategory
Definition at line 127 of file recipe.h.
Referenced by recipe_dictionary::check_consistency(), recipe_subset::empty_category(), recipe_subset::in_category(), and load().
time
int64_t recipe::time = 0 private
Definition at line 95 of file recipe.h.
Referenced by recipe_dictionary::finalize(), incorporate_build_reqs(), load(), and time_to_craft_moves().
uncraft_time
int64_t recipe::uncraft_time = 0 private
Time (in moves) to disassemble if different to assembly.
Requires reversible = true
Definition at line 335 of file recipe.h.
Referenced by recipe_dictionary::finalize(), and load().
variant_
std::string recipe::variant_ private
Definition at line 93 of file recipe.h.
Referenced by load(), and variant().
was_loaded
bool recipe::was_loaded = false
Definition at line 123 of file recipe.h.
Referenced by load(), and recipe_dictionary::load().
The documentation for this class was generated from the following files:
src/recipe.h
src/recipe.cpp