Cataclysm DDA: jmapgen_ter_furn_transform Class Reference
jmapgen_ter_furn_transform Class Reference
Run a transformation.
Public Member Functions
jmapgen_ter_furn_transform (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
mapgen_value< ter_furn_transform_id > id
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Run a transformation.
"transform": id of the ter_furn_transform to run.
Definition at line 3075 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_ter_furn_transform()
jmapgen_ter_furn_transform::jmapgen_ter_furn_transform (const JsonObject & jsi, const std::string_view) inline
Definition at line 3079 of file mapgen.cpp.
                                                                                    :
             id( jsi.get_member( "transform" ) ) {}
Member Function Documentation
apply()
void jmapgen_ter_furn_transform::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 3082 of file mapgen.cpp.
{
             ter_furn_transform_id chosen_id = id.get( dat );
             if( chosen_id.is_null() ) {
                 return;
             }
             for( int ix = x.val; ix <= x.valmax; ix++ ) {
                 for( int iy = y.val; iy <= y.valmax; iy++ ) {
                     chosen_id->transform( dat.m, tripoint_bub_ms( ix, iy, dat.zlevel() + z.get() ) );
                 }
             }
         }
References jmapgen_int::get(), string_id< T >::is_null(), mapgendata::m, ter_furn_transform::transform(), jmapgen_int::val, jmapgen_int::valmax, and mapgendata::zlevel().
check()
void jmapgen_ter_furn_transform::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 3095 of file mapgen.cpp.
{
             id.check( oter_name, parameters );
         }
Member Data Documentation
id
mapgen_value<ter_furn_transform_id> jmapgen_ter_furn_transform::id
Definition at line 3078 of file mapgen.cpp.
The documentation for this class was generated from the following file:
src/mapgen.cpp