Cataclysm DDA: jmapgen_graffiti Class Reference
jmapgen_graffiti Class Reference
Place graffiti with some text or a snippet.
Public Member Functions
jmapgen_graffiti (const JsonObject &jsi, const std::string_view)
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
std::string apply_all_tags (std::string graffiti, const std::string &cityname) const
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual mapgen_phase phase () const
virtual void check (const std::string &, const mapgen_parameters &, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const
Sanity-check this piece.
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
translation text
std::string snippet
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place graffiti with some text or a snippet.
"text": the text of the graffiti. "snippet": snippet category to pull from for text instead.
Definition at line 2019 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_graffiti()
jmapgen_graffiti::jmapgen_graffiti (const JsonObject & jsi, const std::string_view) inline
Definition at line 2024 of file mapgen.cpp.
                                                                          :
             snippet( jsi.get_string( "snippet", "" ) ) {
             jsi.read( "text", text );
             if( text.empty() && snippet.empty() ) {
                 jsi.throw_error( "jmapgen_graffiti: needs either text or snippet" );
             }
         }
References translation::empty(), mapgen_defer::jsi, JsonObject::read(), snippet, text, and JsonObject::throw_error().
Member Function Documentation
apply()
void jmapgen_graffiti::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 2031 of file mapgen.cpp.
{
             const tripoint_bub_ms r( x.get(), y.get(), dat.zlevel() + z.get() );
             std::string graffiti;
             if( !snippet.empty() ) {
                 // select a snippet from the category
                 graffiti = SNIPPET.random_from_category( snippet ).value_or( translation() ).translated();
             } else if( !text.empty() ) {
                 graffiti = text.translated();
             }
             if( !graffiti.empty() ) {
                 // replace tags
                 std::string cityname = "illegible city name";
                 tripoint_abs_sm abs_sub = dat.m.get_abs_sub();
                 const city *c = overmap_buffer.closest_city( abs_sub ).city;
                 if( c != nullptr ) {
                     cityname = c->name;
                 }
                 graffiti = apply_all_tags( graffiti, cityname );
             }
             dat.m.set_graffiti( r.raw(), graffiti );
         }
References apply_all_tags(), c, city_reference::city, overmapbuffer::closest_city(), translation::empty(), jmapgen_int::get(), map::get_abs_sub(), mapgendata::m, overmap_buffer, snippet_library::random_from_category(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), map::set_graffiti(), snippet, SNIPPET, text, translation::translated(), and mapgendata::zlevel().
apply_all_tags()
std::string jmapgen_graffiti::apply_all_tags (std::string graffiti, const std::string & cityname) const inline
Definition at line 2055 of file mapgen.cpp.
{
             graffiti = SNIPPET.expand( graffiti );
             replace_city_tag( graffiti, cityname );
             return graffiti;
         }
References snippet_library::expand(), replace_city_tag(), and SNIPPET.
Referenced by apply().
Member Data Documentation
snippet
std::string jmapgen_graffiti::snippet
Definition at line 2023 of file mapgen.cpp.
Referenced by apply(), and jmapgen_graffiti().
text
translation jmapgen_graffiti::text
Definition at line 2022 of file mapgen.cpp.
Referenced by apply(), and jmapgen_graffiti().
The documentation for this class was generated from the following file:
src/mapgen.cpp