Cataclysm DDA: color_loader< ColorType > Class Template Reference
color_loader< ColorType > Class Template Reference
#include <color_loader.h>
Public Member Functions
void load (std::array< ColorType, COLOR_NAMES_COUNT > &windowsPalette)
Static Public Attributes
static constexpr size_t COLOR_NAMES_COUNT = 16
Private Member Functions
void load_colors (const JsonObject &jsobj)
ColorType ccolor (const std::string &color) const
void load_colorfile (const cata_path &path)
RGBTuple from_rgb (const int r, const int g, const int b)
Static Private Member Functions
static ColorType from_rgb (int r, int g, int b)
static const std::array< std::string, COLOR_NAMES_COUNT > & main_color_names ()
Private Attributes
std::map< std::string, ColorType > consolecolors
Detailed Description
template<typename ColorType>
class color_loader< ColorType >
Definition at line 16 of file color_loader.h.
Member Function Documentation
ccolor()
template<typename ColorType > ColorType color_loader< ColorType >::ccolor (const std::string & color) const inline private
Definition at line 41 of file color_loader.h.
{
             const auto it = consolecolors.find( color );
             if( it == consolecolors.end() ) {
                 throw std::runtime_error( std::string( "requested non-existing color " ) + color );
             }
             return it->second;
         }
References color(), and color_loader< ColorType >::consolecolors.
Referenced by color_loader< ColorType >::load().
from_rgb() [1/2]
RGBTuple color_loader< RGBTuple >::from_rgb (const int r, const int g, const int b) private
Definition at line 151 of file cata_imgui.cpp.
 {
     RGBTuple result;
     // Blue
     result.Blue = b;
     // Green
     result.Green = g;
     // Red
     result.Red = r;
     return result;
 }
References b, RGBTuple::Blue, g, RGBTuple::Green, and RGBTuple::Red.
from_rgb() [2/2]
template<typename ColorType > static ColorType color_loader< ColorType >::from_rgb (int r, int g, int b) static private
Referenced by color_loader< ColorType >::load_colors().
load()
template<typename ColorType > void color_loader< ColorType >::load (std::array< ColorType, COLOR_NAMES_COUNT > & windowsPalette) inline
Exceptions
std::exception upon any kind of error.
Definition at line 60 of file color_loader.h.
{
             const cata_path default_path = PATH_INFO::colors();
             const cata_path custom_path = PATH_INFO::base_colors();
             if( !file_exist( custom_path ) ) {
                 assure_dir_exist( PATH_INFO::config_dir() );
                 copy_file( default_path, custom_path );
             }
             try {
                 load_colorfile( custom_path );
             } catch( const JsonError &err ) {
                 debugmsg( "Failed to load color data from \"%s\": %s", custom_path.generic_u8string(), err.what() );
                 // this should succeed, otherwise the installation is botched
                 load_colorfile( default_path );
             }
             for( size_t c = 0; c < main_color_names().size(); c++ ) {
                 windowsPalette[c] = ccolor( main_color_names()[c] );
             }
         }
References assure_dir_exist(), PATH_INFO::base_colors(), c, color_loader< ColorType >::ccolor(), PATH_INFO::colors(), PATH_INFO::config_dir(), copy_file(), debugmsg, file_exist(), cata_path::generic_u8string(), color_loader< ColorType >::load_colorfile(), and color_loader< ColorType >::main_color_names().
Referenced by cataimgui::load_colors().
load_colorfile()
template<typename ColorType > void color_loader< ColorType >::load_colorfile (const cata_path & path) inline private
Definition at line 49 of file color_loader.h.
{
             JsonValue jsin = json_loader::from_path( path );
             for( JsonObject jo : jsin.get_array() ) {
                 // This isn't actually read (here), so just ignore it
                 jo.get_string( "type" );
                 load_colors( jo );
             }
         }
References json_loader::from_path(), JsonValue::get_array(), and color_loader< ColorType >::load_colors().
Referenced by color_loader< ColorType >::load().
load_colors()
template<typename ColorType > void color_loader< ColorType >::load_colors (const JsonObject & jsobj) inline private
Definition at line 35 of file color_loader.h.
{
             for( const std::string &color : main_color_names() ) {
                 JsonArray jsarr = jsobj.get_array( color );
                 consolecolors[color] = from_rgb( jsarr.get_int( 0 ), jsarr.get_int( 1 ), jsarr.get_int( 2 ) );
             }
         }
References color(), color_loader< ColorType >::consolecolors, color_loader< ColorType >::from_rgb(), JsonObject::get_array(), JsonArray::get_int(), and color_loader< ColorType >::main_color_names().
Referenced by color_loader< ColorType >::load_colorfile().
main_color_names()
template<typename ColorType > static const std::array<std::string, COLOR_NAMES_COUNT>& color_loader< ColorType >::main_color_names () inline static private
Definition at line 27 of file color_loader.h.
{
             static const std::array<std::string, COLOR_NAMES_COUNT> names{ { "BLACK", "RED", "GREEN",
                     "BROWN", "BLUE", "MAGENTA", "CYAN", "GRAY", "DGRAY", "LRED", "LGREEN", "YELLOW",
                     "LBLUE", "LMAGENTA", "LCYAN", "WHITE"
                 } };
             return names;
         }
References PATH_INFO::names().
Referenced by color_loader< ColorType >::load(), and color_loader< ColorType >::load_colors().
Member Data Documentation
COLOR_NAMES_COUNT
template<typename ColorType > constexpr size_t color_loader< ColorType >::COLOR_NAMES_COUNT = 16 static constexpr
Definition at line 19 of file color_loader.h.
consolecolors
template<typename ColorType > std::map<std::string, ColorType> color_loader< ColorType >::consolecolors private
Definition at line 24 of file color_loader.h.
Referenced by color_loader< ColorType >::ccolor(), and color_loader< ColorType >::load_colors().
The documentation for this class was generated from the following file:
src/color_loader.h