Cataclysm DDA: jmapgen_zone Class Reference
jmapgen_zone Class Reference
Place a zone.
Public Member Functions
jmapgen_zone (const JsonObject &jsi, const std::string_view)
mapgen_phase phase () const override
void apply (const mapgendata &dat, const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const std::string &) const override
Place something on the map from mapgendata &dat, at (x,y).
void check (const std::string &oter_name, const mapgen_parameters &parameters, const jmapgen_int &, const jmapgen_int &, const jmapgen_int &) const override
Sanity-check this piece.
Public Member Functions inherited from jmapgen_piece
virtual bool is_nop () const
virtual void merge_parameters_into (mapgen_parameters &, const std::string &) const
virtual ~jmapgen_piece ()=default
virtual bool has_vehicle_collision (const mapgendata &, const tripoint_rel_ms &) const
Public Attributes
mapgen_value< zone_type_id > zone_type
mapgen_value< faction_id > faction
std::string name
std::string filter
Public Attributes inherited from jmapgen_piece
jmapgen_int repeat
Additional Inherited Members
Protected Member Functions inherited from jmapgen_piece
jmapgen_piece ()
Detailed Description
Place a zone.
Definition at line 3359 of file mapgen.cpp.
Constructor & Destructor Documentation
jmapgen_zone()
jmapgen_zone::jmapgen_zone (const JsonObject & jsi, const std::string_view) inline
Definition at line 3366 of file mapgen.cpp.
             : zone_type( jsi.get_member( "type" ) )
             , faction( jsi.get_member( "faction" ) ) {
             if( jsi.has_string( "name" ) ) {
                 name = jsi.get_string( "name" );
             }
             if( jsi.has_string( "filter" ) ) {
                 filter = jsi.get_string( "filter" );
             }
         }
References filter, JsonObject::get_string(), JsonObject::has_string(), mapgen_defer::jsi, and name.
Member Function Documentation
apply()
void jmapgen_zone::apply (const mapgendata & dat, const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const std::string & context) const inline override virtual
Place something on the map from mapgendata &dat, at (x,y).
Implements jmapgen_piece.
Definition at line 3379 of file mapgen.cpp.
{
             zone_type_id chosen_zone_type = zone_type.get( dat );
             faction_id chosen_faction = faction.get( dat );
             const tripoint start = dat.m.getabs( tripoint( x.val, y.val, dat.zlevel() + z.get() ) );
             const tripoint end = dat.m.getabs( tripoint( x.valmax, y.valmax, dat.zlevel() + z.get() ) );
             mapgen_place_zone( start, end, chosen_zone_type, chosen_faction, name, filter, &dat.m );
         }
References keycode::end, filter, jmapgen_int::get(), map::getabs(), mapgendata::m, mapgen_place_zone(), name, tripoint, jmapgen_int::val, jmapgen_int::valmax, and mapgendata::zlevel().
check()
void jmapgen_zone::check (const std::string & , const mapgen_parameters & , const jmapgen_int & , const jmapgen_int & , const jmapgen_int &) const inline override virtual
Sanity-check this piece.
Reimplemented from jmapgen_piece.
Definition at line 3388 of file mapgen.cpp.
{
             zone_type.check( oter_name, parameters );
             faction.check( oter_name, parameters );
         }
phase()
mapgen_phase jmapgen_zone::phase () const inline override virtual
Reimplemented from jmapgen_piece.
Definition at line 3376 of file mapgen.cpp.
{
             return mapgen_phase::zones;
         }
References zones.
Member Data Documentation
faction
mapgen_value<faction_id> jmapgen_zone::faction
Definition at line 3363 of file mapgen.cpp.
filter
std::string jmapgen_zone::filter
Definition at line 3365 of file mapgen.cpp.
Referenced by apply(), and jmapgen_zone().
name
std::string jmapgen_zone::name
Definition at line 3364 of file mapgen.cpp.
Referenced by apply(), and jmapgen_zone().
zone_type
mapgen_value<zone_type_id> jmapgen_zone::zone_type
Definition at line 3362 of file mapgen.cpp.
The documentation for this class was generated from the following file:
src/mapgen.cpp