Cataclysm DDA: live_view Class Reference
live_view Class Reference
#include <live_view.h>
Public Member Functions
live_view ()
~live_view ()
void init ()
void show (const tripoint &p)
bool is_enabled ()
void hide ()
Private Attributes
tripoint mouse_position
catacurses::window win
std::unique_ptr< ui_adaptor > ui
Detailed Description
Definition at line 12 of file live_view.h.
Constructor & Destructor Documentation
live_view()
live_view::live_view () default
~live_view()
live_view::~live_view () default
Member Function Documentation
hide()
void live_view::hide ()
Definition at line 35 of file live_view.cpp.
 {
     ui = nullptr;
 }
Referenced by game::handle_mouseview(), and init().
init()
void live_view::init ()
Definition at line 30 of file live_view.cpp.
 {
     hide();
 }
References hide().
is_enabled()
bool live_view::is_enabled ()
Definition at line 77 of file live_view.cpp.
 {
     return ui != nullptr;
 }
Referenced by game::draw_look_around_cursor().
show()
void live_view::show (const tripoint & p)
Definition at line 40 of file live_view.cpp.
 {
     mouse_position = p;
     if( !ui ) {
         ui = std::make_unique<ui_adaptor>();
         ui->on_screen_resize( [this]( ui_adaptor & ui ) {
             panel_manager &mgr = panel_manager::get_manager();
             const bool sidebar_right = get_option<std::string>( "SIDEBAR_POSITION" ) == "right";
             const int width = sidebar_right ? mgr.get_width_right() : mgr.get_width_left();
             const int max_height = pixel_minimap_option ? TERMY / 2 : TERMY;
             const int line_limit = max_height - 2;
             const visibility_variables &cache = get_map().get_visibility_variables_cache();
             int line_out = START_LINE;
             // HACK: using dummy window to get the window height without refreshing.
             win = catacurses::newwin( 1, width, point_zero );
             g->pre_print_all_tile_info( mouse_position, win, line_out, line_limit, cache );
             const int live_view_box_height = std::min( max_height, std::max( line_out + 2, MIN_BOX_HEIGHT ) );
             win = catacurses::newwin( live_view_box_height, width,
                                       point( sidebar_right ? TERMX - width : 0, 0 ) );
             ui.position_from_window( win );
         } );
         ui->on_redraw( [this]( const ui_adaptor & ) {
             werase( win );
             const visibility_variables &cache = get_map().get_visibility_variables_cache();
             int line_out = START_LINE;
             g->pre_print_all_tile_info( mouse_position, win, line_out, getmaxy( win ) - 2, cache );
             draw_border( win );
             center_print( win, 0, c_white, _( "< <color_green>Mouse view</color> >" ) );
             wnoutrefresh( win );
         } );
     }
     // Always mark ui for resize as the required box height may have changed.
     ui->mark_resize();
 }
References _, c_white, center_print(), draw_border(), g, panel_manager::get_manager(), get_map(), map::get_visibility_variables_cache(), panel_manager::get_width_left(), panel_manager::get_width_right(), catacurses::getmaxy(), max(), min(), anonymous_namespace{live_view.cpp}::MIN_BOX_HEIGHT, mouse_position, catacurses::newwin(), pixel_minimap_option, point, point_zero, anonymous_namespace{live_view.cpp}::START_LINE, TERMX, TERMY, catacurses::werase(), win, and catacurses::wnoutrefresh().
Referenced by game::handle_mouseview().
Member Data Documentation
mouse_position
tripoint live_view::mouse_position private
Definition at line 24 of file live_view.h.
Referenced by show().
ui
std::unique_ptr<ui_adaptor> live_view::ui private
Definition at line 27 of file live_view.h.
win
catacurses::window live_view::win private
Definition at line 26 of file live_view.h.
Referenced by show().
The documentation for this class was generated from the following files:
src/live_view.h
src/live_view.cpp