Cataclysm DDA: maptile_impl< Submap > Class Template Reference
maptile_impl< Submap > Class Template Reference
A wrapper for a submap point.
#include <submap.h>
Public Types
using FieldEntry = cata::copy_const< Submap, field_entry >
Public Member Functions
Submap * wrapped_submap () const
point pos () const
trap_id get_trap () const
furn_id get_furn () const
ter_id get_ter () const
const trap & get_trap_t () const
const furn_t & get_furn_t () const
const ter_t & get_ter_t () const
const field & get_field () const
FieldEntry * find_field (const field_type_id &field_to_find)
int get_radiation () const
bool has_graffiti () const
const std::string & get_graffiti () const
bool has_signage () const
std::string get_signage () const
size_t get_item_count () const
const item & get_uppermost_item () const
const cata::colony< item > & get_items () const
Private Member Functions
maptile_impl (Submap *sub, const point &p)
template<typename OtherSubmap >
maptile_impl (const maptile_impl< OtherSubmap > &other)
Private Attributes
friend map
friend submap
Submap * sm
point pos_
Detailed Description
template<typename Submap>
class maptile_impl< Submap >
A wrapper for a submap point.
Allows getting multiple map features (terrain, furniture etc.) without directly accessing submaps or doing multiple bounds checks and submap gets.
Templated so that we can have const and non-const version; aliases in maptile_fwd.h
Definition at line 332 of file submap.h.
Member Typedef Documentation
FieldEntry
template<typename Submap > using maptile_impl< Submap >::FieldEntry = cata::copy_const<Submap, field_entry>
Definition at line 383 of file submap.h.
Constructor & Destructor Documentation
maptile_impl() [1/2]
template<typename Submap > maptile_impl< Submap >::maptile_impl (Submap * sub, const point & p) inline private
Definition at line 342 of file submap.h.
                                                     :
             sm( sub ), pos_( p ) { }
maptile_impl() [2/2]
template<typename Submap > template<typename OtherSubmap > maptile_impl< Submap >::maptile_impl (const maptile_impl< OtherSubmap > & other) inline private
Definition at line 346 of file submap.h.
                                                                :
             sm( other.wrapped_submap() ), pos_( other.pos() ) { }
Member Function Documentation
find_field()
template<typename Submap > FieldEntry* maptile_impl< Submap >::find_field (const field_type_id & field_to_find) inline
Definition at line 384 of file submap.h.
{
             return sm->get_field( pos() ).find_field( field_to_find );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by field_processor_fd_extinguisher(), map::gas_spread_to(), and maptile_field_intensity().
get_field()
template<typename Submap > const field& maptile_impl< Submap >::get_field () const inline
Definition at line 379 of file submap.h.
{
             return sm->get_field( pos() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by map::draw_maptile(), map::gas_can_spread_to(), map::route(), and map::update_pathfinding_cache().
get_furn()
template<typename Submap > furn_id maptile_impl< Submap >::get_furn () const inline
Definition at line 360 of file submap.h.
{
             return sm->get_furn( pos() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by Character::base_comfort_value(), and map::supports_above().
get_furn_t()
template<typename Submap > const furn_t& maptile_impl< Submap >::get_furn_t () const inline
Definition at line 372 of file submap.h.
{
             return sm->get_furn( pos() ).obj();
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by map::draw_from_above(), map::draw_maptile(), field_processor_fd_fungicidal_gas(), map::gas_can_spread_to(), map::route(), and map::update_pathfinding_cache().
get_graffiti()
template<typename Submap > const std::string& maptile_impl< Submap >::get_graffiti () const inline
Definition at line 396 of file submap.h.
{
             return sm->get_graffiti( pos() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
get_item_count()
template<typename Submap > size_t maptile_impl< Submap >::get_item_count () const inline
Definition at line 409 of file submap.h.
{
             return sm->get_items( pos() ).size();
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by editmap::draw_main_ui_overlay(), and map::draw_maptile().
get_items()
template<typename Submap > const cata::colony<item>& maptile_impl< Submap >::get_items () const inline
Definition at line 419 of file submap.h.
{
             return sm->get_items( pos() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
get_radiation()
template<typename Submap > int maptile_impl< Submap >::get_radiation () const inline
Definition at line 388 of file submap.h.
{
             return sm->get_radiation( pos() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
get_signage()
template<typename Submap > std::string maptile_impl< Submap >::get_signage () const inline
Definition at line 404 of file submap.h.
{
             return sm->get_signage( pos() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
get_ter()
template<typename Submap > ter_id maptile_impl< Submap >::get_ter () const inline
Definition at line 364 of file submap.h.
{
             return sm->get_ter( pos() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by Character::base_comfort_value(), get_best_fire(), and get_heat_radiation().
get_ter_t()
template<typename Submap > const ter_t& maptile_impl< Submap >::get_ter_t () const inline
Definition at line 375 of file submap.h.
{
             return sm->get_ter( pos() ).obj();
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by map::draw_from_above(), map::draw_maptile(), field_processor_fd_fungicidal_gas(), field_processor_underwater_dissipation(), map::gas_can_spread_to(), map::route(), map::supports_above(), and map::update_pathfinding_cache().
get_trap()
template<typename Submap > trap_id maptile_impl< Submap >::get_trap () const inline
Definition at line 356 of file submap.h.
{
             return sm->get_trap( pos() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by map::draw_maptile(), mremove_trap(), and ter_furn_transform::transform().
get_trap_t()
template<typename Submap > const trap& maptile_impl< Submap >::get_trap_t () const inline
Definition at line 368 of file submap.h.
{
             return sm->get_trap( pos() ).obj();
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by Character::base_comfort_value(), map::route(), and map::update_pathfinding_cache().
get_uppermost_item()
template<typename Submap > const item& maptile_impl< Submap >::get_uppermost_item () const inline
Definition at line 414 of file submap.h.
{
             return *std::prev( sm->get_items( pos() ).cend() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by editmap::draw_main_ui_overlay(), and map::draw_maptile().
has_graffiti()
template<typename Submap > bool maptile_impl< Submap >::has_graffiti () const inline
Definition at line 392 of file submap.h.
{
             return sm->has_graffiti( pos() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
Referenced by map::draw_maptile().
has_signage()
template<typename Submap > bool maptile_impl< Submap >::has_signage () const inline
Definition at line 400 of file submap.h.
{
             return sm->has_signage( pos() );
         }
References maptile_impl< Submap >::pos(), and maptile_impl< Submap >::sm.
pos()
template<typename Submap > point maptile_impl< Submap >::pos () const inline
Definition at line 352 of file submap.h.
{
             return pos_;
         }
References maptile_impl< Submap >::pos_.
Referenced by maptile_impl< Submap >::find_field(), maptile_impl< Submap >::get_field(), maptile_impl< Submap >::get_furn(), maptile_impl< Submap >::get_furn_t(), maptile_impl< Submap >::get_graffiti(), maptile_impl< Submap >::get_item_count(), maptile_impl< Submap >::get_items(), maptile_impl< Submap >::get_radiation(), maptile_impl< Submap >::get_signage(), maptile_impl< Submap >::get_ter(), maptile_impl< Submap >::get_ter_t(), maptile_impl< Submap >::get_trap(), maptile_impl< Submap >::get_trap_t(), maptile_impl< Submap >::get_uppermost_item(), maptile_impl< Submap >::has_graffiti(), maptile_impl< Submap >::has_signage(), and map::process_fields_in_submap().
wrapped_submap()
template<typename Submap > Submap* maptile_impl< Submap >::wrapped_submap () const inline
Definition at line 349 of file submap.h.
{
             return sm;
         }
References maptile_impl< Submap >::sm.
Member Data Documentation
map
template<typename Submap > friend maptile_impl< Submap >::map private
Definition at line 337 of file submap.h.
pos_
template<typename Submap > point maptile_impl< Submap >::pos_ private
Definition at line 340 of file submap.h.
Referenced by maptile_impl< Submap >::pos(), map::process_fields_in_submap(), and map::spread_gas().
sm
template<typename Submap > Submap* maptile_impl< Submap >::sm private
Definition at line 339 of file submap.h.
Referenced by maptile_impl< Submap >::find_field(), maptile_impl< Submap >::get_field(), maptile_impl< Submap >::get_furn(), maptile_impl< Submap >::get_furn_t(), maptile_impl< Submap >::get_graffiti(), maptile_impl< Submap >::get_item_count(), maptile_impl< Submap >::get_items(), maptile_impl< Submap >::get_radiation(), maptile_impl< Submap >::get_signage(), maptile_impl< Submap >::get_ter(), maptile_impl< Submap >::get_ter_t(), maptile_impl< Submap >::get_trap(), maptile_impl< Submap >::get_trap_t(), maptile_impl< Submap >::get_uppermost_item(), maptile_impl< Submap >::has_graffiti(), maptile_impl< Submap >::has_signage(), and maptile_impl< Submap >::wrapped_submap().
submap
template<typename Submap > friend maptile_impl< Submap >::submap private
Definition at line 338 of file submap.h.
The documentation for this class was generated from the following files:
src/maptile_fwd.h
src/submap.h