Cataclysm DDA: start_location Class Reference
start_location Class Reference
#include <start_location.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &src)
void finalize ()
void check () const
std::string name () const
int targets_count () const
omt_types_parameters random_target () const
const std::set< std::string > & flags () const
std::pair< tripoint_abs_omt, std::unordered_map< std::string, std::string > > find_player_initial_location (const point_abs_om &origin) const
Find a suitable start location on the overmap.
std::pair< tripoint_abs_omt, std::unordered_map< std::string, std::string > > find_player_initial_location (const city &origin) const
Find a suitable start location on the overmap in specific city.
void set_parameters (const tripoint_abs_omt &omtstart, const std::unordered_map< std::string, std::string > &parameters_to_set) const
Set any parameters assigned to the chosen start location.
void prepare_map (const tripoint_abs_omt &omtstart) const
Initialize the map at players start location using prepare_map.
void place_player (avatar &you, const tripoint_abs_omt &omtstart) const
Place the player somewhere in the reality bubble (g->m).
void burn (const tripoint_abs_omt &omtstart, size_t count, int rad) const
Burn random terrain / furniture with FLAMMABLE or FLAMMABLE_ASH tag.
void add_map_extra (const tripoint_abs_omt &omtstart, const map_extra_id &map_extra) const
Adds a map extra, see map_extras.h and map_extras.cpp.
void handle_heli_crash (avatar &you) const
void surround_with_monsters (const tripoint_abs_omt &omtstart, const mongroup_id &type, float expected_points) const
Adds surround start monsters.
const start_location_placement_constraints & get_constraints () const
bool requires_city () const
bool can_belong_to_city (const tripoint_om_omt &p, const city &cit) const
Public Attributes
start_location_id id
std::vector< std::pair< start_location_id, mod_id > > src
bool was_loaded = false
Private Member Functions
void prepare_map (tinymap &m) const
Private Attributes
translation _name
std::vector< omt_types_parameters > _locations
std::set< std::string > _flags
start_location_placement_constraints constraints_
Detailed Description
Definition at line 36 of file start_location.h.
Member Function Documentation
add_map_extra()
void start_location::add_map_extra (const tripoint_abs_omt & omtstart, const map_extra_id & map_extra) const
Adds a map extra, see map_extras.h and map_extras.cpp.
Look at the namespace MapExtras and class map_extras.
Definition at line 548 of file start_location.cpp.
 {
     tinymap m;
     m.load( omtstart, false );
     MapExtras::apply_function( map_extra, m, omtstart );
     m.save();
 }
References MapExtras::apply_function(), tinymap::load(), and tinymap::save().
Referenced by game::start_game().
burn()
void start_location::burn (const tripoint_abs_omt & omtstart, size_t count, int rad) const
Burn random terrain / furniture with FLAMMABLE or FLAMMABLE_ASH tag.
Doors and windows are excluded.
Parameters
omtstart Global overmap terrain coordinates where the player is to be spawned.
rad safe radius area to prevent player spawn next to burning wall.
count number of fire on the map.
Definition at line 521 of file start_location.cpp.
 {
     tinymap m;
     m.load( omtstart, false );
     m.build_outside_cache( m.get_abs_sub().z() );
     point player_pos = get_player_character().pos().xy();
     const point u( player_pos.x % HALF_MAPSIZE_X, player_pos.y % HALF_MAPSIZE_Y );
     std::vector<tripoint> valid;
     for( const tripoint &p : m.points_on_zlevel() ) {
         if( !( m.has_flag_ter( ter_furn_flag::TFLAG_DOOR, p ) ||
                m.has_flag_ter( ter_furn_flag::TFLAG_OPENCLOSE_INSIDE, p ) ||
                m.is_outside( p ) ||
                ( p.x >= u.x - rad && p.x <= u.x + rad && p.y >= u.y - rad && p.y <= u.y + rad ) ) ) {
             if( m.has_flag( ter_furn_flag::TFLAG_FLAMMABLE, p ) ||
                 m.has_flag( ter_furn_flag::TFLAG_FLAMMABLE_ASH, p ) ) {
                 valid.push_back( p );
             }
         }
     }
     std::shuffle( valid.begin(), valid.end(), rng_get_engine() );
     for( size_t i = 0; i < std::min( count, valid.size() ); i++ ) {
         m.add_field( valid[i], fd_fire, 3 );
     }
     m.save();
 }
References tinymap::add_field(), tinymap::build_outside_cache(), item::count(), fd_fire, tinymap::get_abs_sub(), get_player_character(), HALF_MAPSIZE_X, HALF_MAPSIZE_Y, tinymap::has_flag(), tinymap::has_flag_ter(), tinymap::is_outside(), tinymap::load(), min(), tinymap::points_on_zlevel(), Creature::pos(), rng_get_engine(), tinymap::save(), TFLAG_DOOR, TFLAG_FLAMMABLE, TFLAG_FLAMMABLE_ASH, TFLAG_OPENCLOSE_INSIDE, u, point::x, tripoint::xy(), point::y, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by game::start_game().
can_belong_to_city()
bool start_location::can_belong_to_city (const tripoint_om_omt & p, const city & cit) const
Returns
whether the start location at specified tripoint can belong to the specified city.
Definition at line 97 of file start_location.cpp.
 {
     if( !requires_city() ) {
         return true;
     }
     if( !cit || !constraints_.city_size.contains( cit.size ) ) {
         return false;
     }
     return constraints_.city_distance.contains( cit.get_distance_from( p ) - ( cit.size ) );
 }
References start_location_placement_constraints::city_distance, start_location_placement_constraints::city_size, constraints_, numeric_interval< T, typename >::contains(), city::get_distance_from(), requires_city(), and city::size.
Referenced by find_player_initial_location().
check()
void start_location::check () const
Definition at line 149 of file start_location.cpp.
 {
 }
finalize()
void start_location::finalize ()
Definition at line 153 of file start_location.cpp.
 {
 }
find_player_initial_location() [1/2]
std::pair< tripoint_abs_omt, std::unordered_map< std::string, std::string > > start_location::find_player_initial_location (const city & origin) const
Find a suitable start location on the overmap in specific city.
Returns
Global, absolute overmap terrain coordinates where the player should spawn. It may return overmap::invalid_tripoint if no suitable starting location could be found in the world.
Definition at line 279 of file start_location.cpp.
 {
     overmap &omap = overmap_buffer.get( origin.pos_om );
     std::vector<std::pair<tripoint_om_omt, omt_types_parameters>> valid;
     for( const point_om_omt &omp : closest_points_first( origin.pos, origin.size ) ) {
         for( int k = constraints_.allowed_z_levels.min; k <= constraints_.allowed_z_levels.max; k++ ) {
             tripoint_om_omt p( omp, k );
             if( !can_belong_to_city( p, origin ) ) {
                 continue;
             }
             auto target_is_ot_match = [&]( const omt_types_parameters & target ) {
                 return is_ot_match( target.omt, omap.ter( p ), target.omt_type );
             };
             auto it = std::find_if( _locations.begin(), _locations.end(),
                                     target_is_ot_match );
             if( it != _locations.end() ) {
                 valid.emplace_back( p, *it );
             }
         }
     }
     const std::pair<tripoint_om_omt, omt_types_parameters> random_valid = random_entry( valid,
             std::make_pair( tripoint_om_omt( tripoint_min ), omt_types_parameters() ) );
     const tripoint_om_omt omtstart = random_valid.first;
     if( omtstart.raw() != tripoint_min ) {
         return std::make_pair( project_combine( origin.pos_om, omtstart ), random_valid.second.parameters );
     }
     // Should never happen, if it does we messed up.
     popup( _( "Unable to generate a valid starting location %s [%s] in a city [%s], please report this failure." ),
            name(), id.str(), origin.name );
     return std::make_pair( overmap::invalid_tripoint, random_valid.second.parameters );
 }
References _, _locations, start_location_placement_constraints::allowed_z_levels, can_belong_to_city(), closest_points_first(), constraints_, overmapbuffer::get(), overmap::invalid_tripoint, is_ot_match(), numeric_interval< T, typename >::max, numeric_interval< T, typename >::min, name(), overmap_buffer, popup(), coords::project_combine(), random_entry(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), overmap::ter(), and tripoint_min.
find_player_initial_location() [2/2]
std::pair< tripoint_abs_omt, std::unordered_map< std::string, std::string > > start_location::find_player_initial_location (const point_abs_om & origin) const
Find a suitable start location on the overmap.
Returns
Global, absolute overmap terrain coordinates where the player should spawn. It may return overmap::invalid_tripoint if no suitable starting location could be found in the world.
Definition at line 258 of file start_location.cpp.
 {
     // Spiral out from the world origin scanning for a compatible starting location,
     // creating overmaps as necessary.
     const int radius = 3;
     const omt_types_parameters chosen_target = random_target();
     for( const point_abs_om &omp : closest_points_first( origin, radius ) ) {
         overmap &omap = overmap_buffer.get( omp );
         const tripoint_om_omt omtstart = omap.find_random_omt( std::make_pair( chosen_target.omt,
                                          chosen_target.omt_type ) );
         if( omtstart.raw() != tripoint_min ) {
             return std::make_pair( project_combine( omp, omtstart ), chosen_target.parameters );
         }
     }
     // Should never happen, if it does we messed up.
     popup( _( "Unable to generate a valid starting location %s [%s] in a radius of %d overmaps, please report this failure." ),
            name(), id.str(), radius );
     return std::make_pair( overmap::invalid_tripoint, chosen_target.parameters );
 }
References _, closest_points_first(), overmap::find_random_omt(), overmapbuffer::get(), overmap::invalid_tripoint, name(), omt_types_parameters::omt, omt_types_parameters::omt_type, overmap_buffer, omt_types_parameters::parameters, popup(), coords::project_combine(), random_target(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and tripoint_min.
Referenced by game::start_game().
flags()
const std::set< std::string > & start_location::flags () const
Definition at line 108 of file start_location.cpp.
 {
     return _flags;
 }
References _flags.
Referenced by place_player(), and prepare_map().
get_constraints()
const start_location_placement_constraints& start_location::get_constraints () const inline
Definition at line 102 of file start_location.h.
{
             return constraints_;
         }
References constraints_.
handle_heli_crash()
void start_location::handle_heli_crash (avatar & you) const
Definition at line 559 of file start_location.cpp.
 {
     for( const bodypart_id &bp : you.get_all_body_parts( get_body_part_flags::only_main ) ) {
         if( bp == bodypart_id( "head" ) || bp == bodypart_id( "torso" ) ) {
             continue;// Skip head + torso for balance reasons.
         }
         const int roll = static_cast<int>( rng( 1, 8 ) );
         switch( roll ) {
             // Damage + Bleed
             case 1:
             case 2:
                 you.add_effect( effect_bleed, 6_minutes, bp );
             /* fallthrough */
             case 3:
             case 4:
             // Just damage
             case 5: {
                 const int maxHp = you.get_hp_max( bp );
                 // Body part health will range from 33% to 66% with occasional bleed
                 const int dmg = static_cast<int>( rng( maxHp / 3, maxHp * 2 / 3 ) );
                 you.apply_damage( nullptr, bp, dmg );
                 break;
             }
             // No damage
             default:
                 break;
         }
     }
 }
References Creature::add_effect(), Character::apply_damage(), bp, effect_bleed, Creature::get_all_body_parts(), Creature::get_hp_max(), only_main, and rng().
Referenced by game::start_game().
load()
void start_location::load (const JsonObject & jo, const std::string & src)
Definition at line 113 of file start_location.cpp.
 {
     const bool strict = src == "dda";
     mandatory( jo, was_loaded, "name", _name );
     std::string ter;
     for( const JsonValue entry : jo.get_array( "terrain" ) ) {
         ot_match_type ter_match_type = ot_match_type::type;
         std::unordered_map<std::string, std::string> parameter_map;
         if( entry.test_string() ) {
             ter = entry.get_string();
         } else {
             JsonObject jot = entry.get_object();
             ter = jot.get_string( "om_terrain" );
             if( jot.has_string( "om_terrain_match_type" ) ) {
                 ter_match_type = jot.get_enum_value<ot_match_type>( "om_terrain_match_type", ter_match_type );
             }
             if( jot.has_object( "parameters" ) ) {
                 std::unordered_map<std::string, std::string> parameter_map;
                 jot.read( "parameters", parameter_map );
             }
         }
         _locations.emplace_back( omt_types_parameters{ ter, ter_match_type, parameter_map } );
     }
     if( jo.has_array( "city_sizes" ) ) {
         assign( jo, "city_sizes", constraints_.city_size, strict );
     }
     if( jo.has_array( "city_distance" ) ) {
         assign( jo, "city_distance", constraints_.city_distance, strict );
     }
     if( jo.has_array( "allowed_z_levels" ) ) {
         assign( jo, "allowed_z_levels", constraints_.allowed_z_levels, strict );
     }
     optional( jo, was_loaded, "flags", _flags, auto_flags_reader<> {} );
 }
References _flags, _locations, _name, start_location_placement_constraints::allowed_z_levels, assign(), start_location_placement_constraints::city_distance, start_location_placement_constraints::city_size, constraints_, JsonObject::get_array(), JsonObject::get_enum_value(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_object(), JsonObject::has_string(), mandatory, optional(), JsonObject::read(), src, strict, type, and was_loaded.
name()
std::string start_location::name () const
Definition at line 76 of file start_location.cpp.
 {
     return _name.translated();
 }
References _name, and translation::translated().
Referenced by char_creation::draw_location(), and find_player_initial_location().
place_player()
void start_location::place_player (avatar & you, const tripoint_abs_omt & omtstart) const
Place the player somewhere in the reality bubble (g->m).
Strength allows player to start behind less-bashable furniture and terrain
Definition at line 441 of file start_location.cpp.
 {
     // Need the "real" map with it's inside/outside cache and the like.
     map &here = get_map();
     // Start us off somewhere in the center of the map
     you.move_to( midpoint( project_bounds<coords::ms>( omtstart ) ) );
     here.invalidate_map_cache( here.get_abs_sub().z() );
     here.build_map_cache( here.get_abs_sub().z() );
     const bool must_be_inside = flags().count( "ALLOW_OUTSIDE" ) == 0;
     const bool accommodate_npc = flags().count( "LONE_START" ) == 0;
     ///\EFFECT_STR allows player to start behind less-bashable furniture and terrain
     // TODO: Allow using items here
     const int bash = you.get_str();
     // Remember biggest found location
     // Sometimes it may be impossible to automatically found an ideal location
     // but the player may be more creative than this algorithm and do away with just "good"
     int best_rate = 0;
     tripoint best_spot = you.pos();
     // In which attempt did this area get checked?
     // We can overwrite earlier attempts, but not start in them
     cata::mdarray<int, point_bub_ms> checked = {};
     bool found_good_spot = false;
     //Check if a start_point zone exists first
     const zone_manager &mgr = zone_manager::get_manager();
     for( const auto &i : mgr.get_zones() ) {
         const zone_data &zone = i.get();
         if( zone.get_type() == zone_type_ZONE_START_POINT ) {
             if( here.inbounds( zone.get_center_point() ) ) {
                 found_good_spot = true;
                 best_spot = here.getlocal( zone.get_center_point() );
                 break;
             }
         }
     }
     // Otherwise, find a random starting spot
     int tries = 0;
     const auto check_spot = [&]( const tripoint & pt ) {
         ++tries;
         const int rate = rate_location( here, pt, must_be_inside, accommodate_npc, bash, tries, checked );
         if( best_rate < rate ) {
             best_rate = rate;
             best_spot = pt;
             if( rate == INT_MAX ) {
                 return true;
             }
         }
         return false;
     };
     while( !found_good_spot && tries < 100 ) {
         tripoint rand_point( HALF_MAPSIZE_X + rng( 0, SEEX * 2 - 1 ),
                              HALF_MAPSIZE_Y + rng( 0, SEEY * 2 - 1 ),
                              you.posz() );
         found_good_spot = check_spot( rand_point );
     }
     // If we haven't got a good location by now, screw it and brute force it
     // This only happens in exotic locations (deep of a science lab), but it does happen
     if( !found_good_spot ) {
         tripoint tmp = you.pos();
         int &x = tmp.x;
         int &y = tmp.y;
         for( x = 0; x < MAPSIZE_X; x++ ) {
             for( y = 0; y < MAPSIZE_Y && !found_good_spot; y++ ) {
                 found_good_spot = check_spot( tmp );
             }
         }
     }
     you.setpos( best_spot );
     if( !found_good_spot ) {
         debugmsg( "Could not find a good starting place for character" );
     }
 }
References spell_effect::bash(), map::build_map_cache(), debugmsg, flags(), map::get_abs_sub(), zone_data::get_center_point(), zone_manager::get_manager(), get_map(), Character::get_str(), zone_data::get_type(), zone_manager::get_zones(), map::getlocal(), HALF_MAPSIZE_X, HALF_MAPSIZE_Y, map::inbounds(), map::invalidate_map_cache(), MAPSIZE_X, MAPSIZE_Y, midpoint(), Creature::move_to(), Creature::pos(), Creature::posz(), rate_location(), rng(), SEEX, SEEY, Creature::setpos(), tripoint::x, tripoint::y, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and zone_type_ZONE_START_POINT.
Referenced by game::start_game().
prepare_map() [1/2]
void start_location::prepare_map (const tripoint_abs_omt & omtstart) const
Initialize the map at players start location using prepare_map.
Parameters
omtstart Global overmap terrain coordinates where the player is to be spawned.
Definition at line 362 of file start_location.cpp.
 {
     // Now prepare the initial map (change terrain etc.)
     tinymap player_start;
     player_start.load( omtstart, false );
     prepare_map( player_start );
     player_start.save();
 }
References tinymap::load(), and tinymap::save().
Referenced by game::start_game().
prepare_map() [2/2]
void start_location::prepare_map (tinymap & m) const private
Definition at line 246 of file start_location.cpp.
 {
     const int z = m.get_abs_sub().z();
     if( flags().count( "BOARDED" ) > 0 ) {
         m.build_outside_cache( z );
         board_up( m, m.points_on_zlevel( z ) );
     } else {
         m.translate( ter_t_window_domestic, ter_t_curtains );
     }
 }
References board_up(), tinymap::build_outside_cache(), item::count(), flags(), tinymap::get_abs_sub(), tinymap::points_on_zlevel(), ter_t_curtains, ter_t_window_domestic, tinymap::translate(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
random_target()
omt_types_parameters start_location::random_target () const
Definition at line 86 of file start_location.cpp.
 {
     return random_entry( _locations );
 }
References _locations, and random_entry().
Referenced by find_player_initial_location().
requires_city()
bool start_location::requires_city () const
Returns
true if this start location requires a city
Definition at line 91 of file start_location.cpp.
 {
     return constraints_.city_size.min > 0 ||
            constraints_.city_distance.max < std::max( OMAPX, OMAPY );
 }
References start_location_placement_constraints::city_distance, start_location_placement_constraints::city_size, constraints_, numeric_interval< T, typename >::max, max(), numeric_interval< T, typename >::min, OMAPX, and OMAPY.
Referenced by can_belong_to_city().
set_parameters()
void start_location::set_parameters (const tripoint_abs_omt & omtstart, const std::unordered_map< std::string, std::string > & parameters_to_set) const
Set any parameters assigned to the chosen start location.
Definition at line 311 of file start_location.cpp.
 {
     if( parameters_to_set.empty() ) {
         return;
     }
     overmap_buffer.externally_set_args = true;
     std::optional<mapgen_arguments> *maybe_args = overmap_buffer.mapgen_args( omtstart );
     if( !maybe_args ) {
         debugmsg( "No overmap special args at start location." );
         return;
     }
     std::optional<overmap_special_id> s = overmap_buffer.overmap_special_at( omtstart );
     if( !s ) {
         debugmsg( "No overmap special at start location from which to fetch parameters." );
         return;
     }
     const overmap_special &special = **s;
     const mapgen_parameters &params = special.get_params();
     mapgen_arguments args;
     for( const auto &param_to_set : parameters_to_set ) {
         const std::string &param_name_to_set = param_to_set.first;
         const std::string &value_to_set = param_to_set.second;
         auto param_it = params.map.find( param_name_to_set );
         if( param_it == params.map.end() ) {
             debugmsg( "Parameter %s not found", param_name_to_set );
             continue;
         }
         const mapgen_parameter &param = param_it->second;
         if( param.scope() != mapgen_parameter_scope::overmap_special ) {
             debugmsg( "Parameter %s is not of scope overmap_special", param_name_to_set );
             continue;
         }
         std::vector<std::string> possible_values = param.all_possible_values( params );
         auto value_it = std::find( possible_values.begin(), possible_values.end(), value_to_set );
         if( value_it == possible_values.end() ) {
             debugmsg( "Parameter value %s for parameter %s not found", value_to_set, param_name_to_set );
             continue;
         }
         if( *maybe_args ) {
             maybe_args->value().map[param_name_to_set] =
                 cata_variant::from_string( param.type(), std::move( *value_it ) );
         } else {
             mapgen_arguments args;
             args.map[param_name_to_set] =
                 cata_variant::from_string( param.type(), std::move( *value_it ) );
             *maybe_args = args;
         }
     }
 }
References mapgen_parameter::all_possible_values(), debugmsg, overmapbuffer::externally_set_args, cata_variant::from_string(), overmap_special::get_params(), mapgen_parameters::map, mapgen_arguments::map, overmapbuffer::mapgen_args(), overmap_buffer, overmap_special, overmapbuffer::overmap_special_at(), mapgen_parameter::scope(), and mapgen_parameter::type().
Referenced by game::start_game().
surround_with_monsters()
void start_location::surround_with_monsters (const tripoint_abs_omt & omtstart, const mongroup_id & type, float expected_points) const
Adds surround start monsters.
Parameters
expected_points Expected value of "monster points" (map tiles times density from map::place_spawns).
Definition at line 602 of file start_location.cpp.
 {
     for( const tripoint_abs_omt &p : points_in_radius( omtstart, 1 ) ) {
         if( p != omtstart ) {
             add_monsters( p, type, roll_remainder( expected_points / 8.0f ) );
         }
     }
 }
References add_monsters(), points_in_radius(), roll_remainder(), and type.
Referenced by game::start_game().
targets_count()
int start_location::targets_count () const
Definition at line 81 of file start_location.cpp.
 {
     return _locations.size();
 }
References _locations.
Referenced by char_creation::draw_location().
Member Data Documentation
_flags
std::set<std::string> start_location::_flags private
Definition at line 112 of file start_location.h.
Referenced by flags(), and load().
_locations
std::vector<omt_types_parameters> start_location::_locations private
Definition at line 111 of file start_location.h.
Referenced by find_player_initial_location(), load(), random_target(), and targets_count().
_name
translation start_location::_name private
Definition at line 110 of file start_location.h.
Referenced by load(), and name().
constraints_
start_location_placement_constraints start_location::constraints_ private
Definition at line 113 of file start_location.h.
Referenced by can_belong_to_city(), find_player_initial_location(), get_constraints(), load(), and requires_city().
id
start_location_id start_location::id
Definition at line 39 of file start_location.h.
src
std::vector<std::pair<start_location_id, mod_id> > start_location::src
Definition at line 40 of file start_location.h.
Referenced by load().
was_loaded
bool start_location::was_loaded = false
Definition at line 41 of file start_location.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/start_location.h
src/start_location.cpp