Cataclysm DDA: spell Class Reference
spell Class Reference
#include <magic.h>
Public Member Functions
spell ()=default
spell (spell_id sp, int xp=0, int level_adjustment=0)
void set_message (const translation &msg)
int exp_to_next_level () const
std::string exp_progress () const
int xp () const
void gain_exp (const Character &guy, int nxp)
void set_exp (int nxp)
int casting_exp (const Character &guy) const
float exp_modifier (const Character &guy) const
void gain_level (const Character &guy)
void gain_levels (const Character &guy, int gains)
void set_level (const Character &guy, int nlevel)
bool is_max_level (const Creature &caster) const
int get_max_level (const Creature &caster) const
int get_temp_level_adjustment () const
void set_temp_level_adjustment (int adjustment)
void set_temp_adjustment (const std::string &target_property, float adjustment)
void clear_temp_adjustments ()
spell_shape shape () const
int field_intensity (const Creature &caster) const
int damage (const Creature &caster) const
int accuracy (Creature &caster) const
int damage_dot (const Creature &caster) const
damage_over_time_data damage_over_time (const std::vector< bodypart_str_id > &bps, const Creature &caster) const
dealt_damage_instance get_dealt_damage_instance (Creature &caster) const
dealt_projectile_attack get_projectile_attack (const tripoint &target, Creature &hit_critter, Creature &caster) const
damage_instance get_damage_instance (Creature &caster) const
float dps (const Character &caster, const Creature &target) const
std::optional< tripoint > select_target (Creature *source)
int aoe (const Creature &caster) const
std::set< tripoint > effect_area (const spell_effect::override_parameters &params, const tripoint &source, const tripoint &target) const
std::set< tripoint > effect_area (const tripoint &source, const tripoint &target, const Creature &caster) const
int range (const Creature &caster) const
std::vector< tripoint > targetable_locations (const Character &source) const
all of the tripoints the spell can be cast at.
int energy_cost (const Character &guy) const
int duration (const Creature &caster) const
time_duration duration_turns (const Creature &caster) const
float spell_fail (const Character &guy) const
std::string colorized_fail_percent (const Character &guy) const
int casting_time (const Character &guy, bool ignore_encumb=false) const
const requirement_data & components () const
bool has_components () const
bool can_cast (const Character &guy) const
bool can_learn (const Character &guy) const
bool is_valid () const
bool bp_is_affected (const bodypart_str_id &bp) const
bool has_flag (const spell_flag &flag) const
bool has_flag (const std::string &flag) const
bool no_hands () const
bool is_spell_class (const trait_id &mid) const
bool in_aoe (const tripoint &source, const tripoint &target, const Creature &caster) const
bool casting_time_encumbered (const Character &guy) const
bool energy_cost_encumbered (const Character &guy) const
std::string enumerate_spell_data (const Character &guy) const
spell_id id () const
trait_id spell_class () const
skill_id skill () const
std::string effect () const
std::string effect_data () const
vproto_id summon_vehicle_id () const
std::string name () const
std::string description () const
std::string message () const
std::string energy_string () const
std::string energy_cost_string (const Character &guy) const
std::string energy_cur_string (const Character &guy) const
std::string enumerate_targets () const
std::string list_targeted_monster_names () const
std::string list_targeted_species_names () const
std::string list_ignored_species_names () const
std::string damage_string (const Character &caster) const
std::string aoe_string (const Creature &caster) const
std::string duration_string (const Creature &caster) const
magic_energy_type energy_source () const
nc_color damage_type_color () const
std::string damage_type_string () const
int get_level () const
int get_effective_level () const
int get_difficulty (const Creature &caster) const
mod_id get_src () const
void create_field (const tripoint &at, Creature &caster) const
int sound_volume (const Creature &caster) const
void make_sound (const tripoint &target, Creature &caster) const
void make_sound (const tripoint &target, int loudness) const
int heal (const tripoint &target, Creature &caster) const
void cast_spell_effect (Creature &source, const tripoint &target) const
void cast_all_effects (Creature &source, const tripoint &target) const
void cast_extra_spell_effects (Creature &source, const tripoint &target) const
void use_components (Character &guy) const
bool check_if_component_in_hand (Character &guy) const
bool is_target_in_range (const Creature &caster, const tripoint &p) const
bool is_valid_target (const Creature &caster, const tripoint &p) const
bool is_valid_target (spell_target t) const
bool target_by_monster_id (const tripoint &p) const
bool target_by_species_id (const tripoint &p) const
bool ignore_by_species_id (const tripoint &p) const
std::optional< tripoint > random_valid_target (const Creature &caster, const tripoint &caster_pos) const
Static Public Member Functions
static int exp_for_level (int level)
Private Member Functions
const damage_type_id & dmg_type () const
int min_leveled_damage (const Creature &caster) const
int min_leveled_dot (const Creature &caster) const
int min_leveled_aoe (const Creature &caster) const
int min_leveled_duration (const Creature &caster) const
int min_leveled_accuracy (const Creature &caster) const
Private Attributes
spell_id type
int experience = 0
int temp_level_adjustment = 0
float temp_cast_time_multiplyer = 1
float temp_spell_cost_multiplyer = 1
float temp_aoe_multiplyer = 1
float temp_range_multiplyer = 1
float temp_duration_multiplyer = 1
int temp_difficulty_adjustment = 0
float temp_somatic_difficulty_multiplyer = 1
float temp_sound_multiplyer = 1
float temp_concentration_difficulty_multiplyer = 1
translation alt_message
Friends
class spell_events
Detailed Description
Definition at line 421 of file magic.h.
Constructor & Destructor Documentation
spell() [1/2]
spell::spell () default
spell() [2/2]
spell::spell (spell_id sp, int xp = 0, int level_adjustment = 0) explicit
Definition at line 651 of file magic.cpp.
                                                         :
     type( sp ),
     experience( xp ),
     temp_level_adjustment( level_adjustment )
 {}
Member Function Documentation
accuracy()
int spell::accuracy (Creature & caster) const
Definition at line 731 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     const int leveled_accuracy = min_leveled_accuracy( caster );
     if( type->min_accuracy.evaluate( d ) >= 0 ||
         type->max_accuracy.evaluate( d ) >= type->min_accuracy.evaluate( d ) ) {
         return std::min( leveled_accuracy, static_cast<int>( type->max_accuracy.evaluate( d ) ) );
     } else { // if it's negative, min and max work differently
         return std::max( leveled_accuracy, static_cast<int>( type->max_accuracy.evaluate( d ) ) );
     }
 }
References dbl_or_var::evaluate(), get_talker_for(), max(), spell_type::max_accuracy, min(), spell_type::min_accuracy, min_leveled_accuracy(), and type.
Referenced by damage_targets().
aoe()
int spell::aoe (const Creature & caster) const
Definition at line 854 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     const int leveled_aoe = min_leveled_aoe( caster );
     int return_value;
     if( has_flag( spell_flag::RANDOM_AOE ) ) {
         return_value = rng( std::min( leveled_aoe, static_cast<int>( type->max_aoe.evaluate( d ) ) ),
                             std::max( leveled_aoe, static_cast<int>( type->max_aoe.evaluate( d ) ) ) );
     } else {
         if( type->max_aoe.evaluate( d ) >= type->min_aoe.evaluate( d ) ) {
             return_value = std::min( leveled_aoe, static_cast<int>( type->max_aoe.evaluate( d ) ) );
         } else {
             return_value = std::max( leveled_aoe, static_cast<int>( type->max_aoe.evaluate( d ) ) );
         }
     }
     return return_value * temp_aoe_multiplyer;
 }
References dbl_or_var::evaluate(), get_talker_for(), has_flag(), max(), spell_type::max_aoe, min(), spell_type::min_aoe, min_leveled_aoe(), RANDOM_AOE, rng(), temp_aoe_multiplyer, and type.
Referenced by aoe_string(), spell_effect::area_pull(), spell_effect::area_push(), calculate_spell_effect_area(), spell_effect::dash(), spell_effect::explosion(), in_aoe(), spell_effect::map(), spell_effect::override_parameters::override_parameters(), target_ui::panel_spell_info(), spell_effect::short_range_teleport(), spell_effect::slime_split_on_death(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), and spell_remove_field().
aoe_string()
std::string spell::aoe_string (const Creature & caster) const
Definition at line 895 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     if( has_flag( spell_flag::RANDOM_AOE ) ) {
         return string_format( "%d-%d", min_leveled_aoe( caster ), type->max_aoe.evaluate( d ) );
     } else {
         return string_format( "%d", aoe( caster ) );
     }
 }
References aoe(), dbl_or_var::evaluate(), get_talker_for(), has_flag(), spell_type::max_aoe, min_leveled_aoe(), RANDOM_AOE, string_format(), and type.
Referenced by target_ui::panel_spell_info(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
bp_is_affected()
bool spell::bp_is_affected (const bodypart_str_id & bp) const
Definition at line 1400 of file magic.cpp.
 {
     return type->affected_bps.test( bp );
 }
References spell_type::affected_bps, bp, body_part_set::test(), and type.
Referenced by add_effect_to_target().
can_cast()
bool spell::can_cast (const Character & guy) const
Definition at line 1093 of file magic.cpp.
 {
     if( guy.has_flag( json_flag_NO_SPELLCASTING ) && !has_flag( spell_flag::PSIONIC ) ) {
         return false;
     }
     if( guy.has_flag( json_flag_NO_PSIONICS ) && has_flag( spell_flag::PSIONIC ) ) {
         return false;
     }
     if( !type->spell_components.is_empty() &&
         !type->spell_components->can_make_with_inventory( guy.crafting_inventory( guy.pos(), 0, false ),
                 return_true<item> ) ) {
         return false;
     }
     return guy.magic->has_enough_energy( guy, *this );
 }
References requirement_data::can_make_with_inventory(), Character::crafting_inventory(), Character::has_flag(), has_flag(), string_id< T >::is_empty(), json_flag_NO_PSIONICS, json_flag_NO_SPELLCASTING, Character::magic, Creature::pos(), PSIONIC, spell_type::spell_components, and type.
Referenced by npc_attack_spell::can_use(), cast_spell(), and target_ui::run().
can_learn()
bool spell::can_learn (const Character & guy) const
Definition at line 1032 of file magic.cpp.
 {
     if( type->spell_class == trait_NONE ) {
         return true;
     }
     return guy.has_trait( type->spell_class );
 }
References Character::has_trait(), spell_type::spell_class, trait_NONE, and type.
cast_all_effects()
void spell::cast_all_effects (Creature & source, const tripoint & target) const
Definition at line 1833 of file magic.cpp.
 {
     if( has_flag( spell_flag::WONDER ) ) {
         const auto iter = type->additional_spells.begin();
         for( int num_spells = std::abs( damage( source ) ); num_spells > 0; num_spells-- ) {
             if( type->additional_spells.empty() ) {
                 debugmsg( "ERROR: %s has WONDER flag but no spells to choose from!", type->id.c_str() );
                 return;
             }
             const int rand_spell = rng( 0, type->additional_spells.size() - 1 );
             spell sp = ( iter + rand_spell )->get_spell( source, get_effective_level() );
             const bool _self = ( iter + rand_spell )->self;
             // This spell flag makes it so the message of the spell that's cast using this spell will be sent.
             // if a message is added to the casting spell, it will be sent as well.
             source.add_msg_if_player( sp.message() );
             if( sp.has_flag( spell_flag::RANDOM_TARGET ) ) {
                 if( const std::optional<tripoint> new_target = sp.random_valid_target( source,
                         _self ? source.pos() : target ) ) {
                     sp.cast_all_effects( source, *new_target );
                 }
             } else {
                 if( _self ) {
                     sp.cast_all_effects( source, source.pos() );
                 } else {
                     sp.cast_all_effects( source, target );
                 }
             }
         }
     } else {
         if( has_flag( spell_flag::EXTRA_EFFECTS_FIRST ) ) {
             cast_extra_spell_effects( source, target );
             cast_spell_effect( source, target );
         } else {
             cast_spell_effect( source, target );
             cast_extra_spell_effects( source, target );
         }
     }
 }
References abs(), Creature::add_msg_if_player(), spell_type::additional_spells, string_id< T >::c_str(), cast_all_effects(), cast_extra_spell_effects(), cast_spell_effect(), damage(), debugmsg, EXTRA_EFFECTS_FIRST, get_effective_level(), has_flag(), spell_type::id, message(), Creature::pos(), RANDOM_TARGET, random_valid_target(), rng(), type, and WONDER.
Referenced by relic::activate(), enchant_cache::activate_passive(), timed_event::actualize(), mon_spellcasting_actor::call(), cast_all_effects(), enchant_cache::cast_enchantment_spell(), cast_extra_spell_effects(), trapfunc::cast_spell(), monster::die(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), and activity_handlers::spellcasting_finish().
cast_extra_spell_effects()
void spell::cast_extra_spell_effects (Creature & source, const tripoint & target) const
Definition at line 1874 of file magic.cpp.
 {
     for( const fake_spell &extra_spell : type->additional_spells ) {
         spell sp = extra_spell.get_spell( source, get_effective_level() );
         if( sp.has_flag( spell_flag::RANDOM_TARGET ) ) {
             if( const std::optional<tripoint> new_target = sp.random_valid_target( source,
                     extra_spell.self ? source.pos() : target ) ) {
                 sp.cast_all_effects( source, *new_target );
             }
         } else {
             if( extra_spell.self ) {
                 sp.cast_all_effects( source, source.pos() );
             } else {
                 sp.cast_all_effects( source, target );
             }
         }
     }
 }
References spell_type::additional_spells, cast_all_effects(), get_effective_level(), fake_spell::get_spell(), has_flag(), Creature::pos(), RANDOM_TARGET, random_valid_target(), fake_spell::self, and type.
Referenced by cast_all_effects().
cast_spell_effect()
void spell::cast_spell_effect (Creature & source, const tripoint & target) const
Definition at line 1819 of file magic.cpp.
 {
     Character *caster = source.as_character();
     if( caster ) {
         character_id c_id = caster->getID();
         // send casting to the event bus
         get_event_bus().send<event_type::character_casts_spell>( c_id, this->id(), this->spell_class(),
                 this->get_difficulty( source ), this->energy_cost( *caster ), this->casting_time( *caster ),
                 this->damage( source ) );
     }
     type->effect( *this, source, target );
 }
References Creature::as_character(), casting_time(), character_casts_spell, damage(), spell_type::effect, energy_cost(), get_difficulty(), get_event_bus(), Character::getID(), id(), event_bus::send(), spell_class(), and type.
Referenced by cast_all_effects().
casting_exp()
int spell::casting_exp (const Character & guy) const
Definition at line 1675 of file magic.cpp.
 {
     // the amount of xp you would get with no modifiers
     const int base_casting_xp = 75;
     return std::round( guy.adjust_for_focus( base_casting_xp * exp_modifier( guy ) ) );
 }
References Character::adjust_for_focus(), exp_modifier(), and round().
Referenced by activity_handlers::spellcasting_finish().
casting_time()
int spell::casting_time (const Character & guy, bool ignore_encumb = false) const
Definition at line 1158 of file magic.cpp.
 {
     // casting time in moves
     int casting_time = 0;
     dialogue d( get_talker_for( guy ), nullptr );
     if( type->base_casting_time.evaluate( d ) < type->final_casting_time.evaluate( d ) ) {
         casting_time = std::min( static_cast<int>( type->final_casting_time.evaluate( d ) ),
                                  static_cast<int>( std::round( type->base_casting_time.evaluate( d ) +
                                          type->casting_time_increment.evaluate( d ) *
                                          get_effective_level() ) ) );
     } else if( type->base_casting_time.evaluate( d ) > type->final_casting_time.evaluate( d ) ) {
         casting_time = std::max( static_cast<int>( type->final_casting_time.evaluate( d ) ),
                                  static_cast<int>( std::round( type->base_casting_time.evaluate( d ) +
                                          type->casting_time_increment.evaluate( d ) *
                                          get_effective_level() ) ) );
     } else {
         casting_time = type->base_casting_time.evaluate( d );
     }
     casting_time = guy.enchantment_cache->modify_value( enchant_vals::mod::CASTING_TIME_MULTIPLIER,
                    casting_time );
     if( !ignore_encumb && temp_somatic_difficulty_multiplyer > 0 ) {
         if( !has_flag( spell_flag::NO_LEGS ) ) {
             // the first 20 points of encumbrance combined is ignored
             const int legs_encumb = std::max( 0,
                                               guy.avg_encumb_of_limb_type( body_part_type::type::leg ) - 10 );
             casting_time += legs_encumb * 3 * temp_somatic_difficulty_multiplyer;
         }
         if( has_flag( spell_flag::SOMATIC ) && !guy.has_flag( json_flag_SUBTLE_SPELL ) ) {
             // the first 20 points of encumbrance combined is ignored
             const int arms_encumb = std::max( 0,
                                               guy.avg_encumb_of_limb_type( body_part_type::type::arm ) - 10 );
             casting_time += arms_encumb * 2 * temp_somatic_difficulty_multiplyer;
         }
     }
     return std::max( casting_time * temp_cast_time_multiplyer, 0.0f );
 }
References body_part_type::arm, Character::avg_encumb_of_limb_type(), spell_type::base_casting_time, spell_type::casting_time_increment, enchant_vals::CASTING_TIME_MULTIPLIER, Character::enchantment_cache, dbl_or_var::evaluate(), spell_type::final_casting_time, get_effective_level(), get_talker_for(), Character::has_flag(), has_flag(), json_flag_SUBTLE_SPELL, body_part_type::leg, max(), min(), NO_LEGS, round(), SOMATIC, temp_cast_time_multiplyer, temp_somatic_difficulty_multiplyer, and type.
Referenced by npc_attack_spell::base_time_penalty(), mon_spellcasting_actor::call(), Character::cast_spell(), cast_spell_effect(), dps(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), activity_handlers::spellcasting_finish(), and cast_spell_actor::use().
casting_time_encumbered()
bool spell::casting_time_encumbered (const Character & guy) const
Definition at line 2383 of file magic.cpp.
 {
     int encumb = 0;
     if( !has_flag( spell_flag::NO_LEGS ) && temp_somatic_difficulty_multiplyer > 0 ) {
         // the first 20 points of encumbrance combined is ignored
         encumb += std::max( 0, guy.avg_encumb_of_limb_type( body_part_type::type::leg ) - 10 );
     }
     if( has_flag( spell_flag::SOMATIC ) && !guy.has_flag( json_flag_SUBTLE_SPELL ) &&
         temp_somatic_difficulty_multiplyer > 0 ) {
         // the first 20 points of encumbrance combined is ignored
         encumb += std::max( 0, guy.avg_encumb_of_limb_type( body_part_type::type::arm ) - 10 );
     }
     return encumb > 0;
 }
References body_part_type::arm, Character::avg_encumb_of_limb_type(), encumb, Character::has_flag(), has_flag(), json_flag_SUBTLE_SPELL, body_part_type::leg, max(), NO_LEGS, SOMATIC, and temp_somatic_difficulty_multiplyer.
Referenced by debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
check_if_component_in_hand()
bool spell::check_if_component_in_hand (Character & guy) const
Definition at line 1129 of file magic.cpp.
 {
     if( type->spell_components.is_empty() ) {
         return false;
     }
     const requirement_data &spell_components = type->spell_components.obj();
     if( guy.has_weapon() ) {
         if( spell_components.can_make_with_inventory( *guy.get_wielded_item(), return_true<item> ) ) {
             return true;
         }
     }
     // if it isn't in hand, return false
     return false;
 }
References requirement_data::can_make_with_inventory(), Character::get_wielded_item(), Character::has_weapon(), string_id< T >::is_empty(), string_id< T >::obj(), spell_type::spell_components, and type.
Referenced by Character::cast_spell().
clear_temp_adjustments()
void spell::clear_temp_adjustments ()
Definition at line 1624 of file magic.cpp.
 {
     temp_level_adjustment = 0;
     temp_cast_time_multiplyer = 1;
     temp_spell_cost_multiplyer = 1;
     temp_aoe_multiplyer = 1;
     temp_range_multiplyer = 1;
     temp_duration_multiplyer = 1;
     temp_difficulty_adjustment = 0;
     temp_somatic_difficulty_multiplyer = 1;
     temp_sound_multiplyer = 1;
     temp_concentration_difficulty_multiplyer = 1;
 }
References temp_aoe_multiplyer, temp_cast_time_multiplyer, temp_concentration_difficulty_multiplyer, temp_difficulty_adjustment, temp_duration_multiplyer, temp_level_adjustment, temp_range_multiplyer, temp_somatic_difficulty_multiplyer, temp_sound_multiplyer, and temp_spell_cost_multiplyer.
colorized_fail_percent()
std::string spell::colorized_fail_percent (const Character & guy) const
Definition at line 1289 of file magic.cpp.
 {
     const float fail_fl = spell_fail( guy ) * 100.0f;
     std::string fail_str;
     fail_fl == 100.0f ? fail_str = _( "Too Difficult!" ) : fail_str = string_format( "%.1f %% %s",
                                    fail_fl, _( "Failure Chance" ) );
     nc_color color;
     if( fail_fl > 90.0f ) {
         color = c_magenta;
     } else if( fail_fl > 75.0f ) {
         color = c_red;
     } else if( fail_fl > 60.0f ) {
         color = c_light_red;
     } else if( fail_fl > 35.0f ) {
         color = c_yellow;
     } else if( fail_fl > 15.0f ) {
         color = c_green;
     } else {
         color = c_light_green;
     }
     return colorize( fail_str, color );
 }
References _, c_green, c_light_green, c_light_red, c_magenta, c_red, c_yellow, color(), colorize(), spell_fail(), and string_format().
Referenced by target_ui::panel_spell_info(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
components()
const requirement_data & spell::components () const
Definition at line 1197 of file magic.cpp.
 {
     return type->spell_components.obj();
 }
References string_id< T >::obj(), spell_type::spell_components, and type.
Referenced by debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
create_field()
void spell::create_field (const tripoint & at, Creature & caster) const
Definition at line 1405 of file magic.cpp.
 {
     if( !type->field ) {
         return;
     }
     dialogue d( get_talker_for( caster ), nullptr );
     const int intensity = field_intensity( caster ) + rng( -type->field_intensity_variance.evaluate(
                               d ) * field_intensity( caster ),
                           type->field_intensity_variance.evaluate( d ) * field_intensity( caster ) );
     if( intensity <= 0 ) {
         return;
     }
     if( one_in( type->field_chance.evaluate( d ) ) ) {
         map &here = get_map();
         field_entry *field = here.get_field( at, *type->field );
         if( field ) {
             field->set_field_intensity( field->get_field_intensity() + intensity );
         } else {
             here.add_field( at, *type->field, intensity, -duration_turns( caster ) );
         }
     }
 }
References map::add_field(), duration_turns(), dbl_or_var::evaluate(), spell_type::field, spell_type::field_chance, field_intensity(), spell_type::field_intensity_variance, map::get_field(), get_map(), get_talker_for(), intensity, one_in(), rng(), and type.
Referenced by damage_targets(), and spell_effect::dash().
damage()
int spell::damage (const Creature & caster) const
Definition at line 705 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     const int leveled_damage = min_leveled_damage( caster );
     if( has_flag( spell_flag::RANDOM_DAMAGE ) ) {
         return rng( std::min( leveled_damage, static_cast<int>( type->max_damage.evaluate( d ) ) ),
                     std::max( leveled_damage,
                               static_cast<int>( type->max_damage.evaluate( d ) ) ) );
     } else {
         if( type->min_damage.evaluate( d ) >= 0 ||
             type->max_damage.evaluate( d ) >= type->min_damage.evaluate( d ) ) {
             return std::min( leveled_damage, static_cast<int>( type->max_damage.evaluate( d ) ) );
         } else { // if it's negative, min and max work differently
             return std::max( leveled_damage, static_cast<int>( type->max_damage.evaluate( d ) ) );
         }
     }
 }
References dbl_or_var::evaluate(), get_talker_for(), has_flag(), max(), spell_type::max_damage, min(), spell_type::min_damage, min_leveled_damage(), RANDOM_DAMAGE, rng(), and type.
Referenced by spell_effect::banishment(), spell_effect::bash(), cast_all_effects(), cast_spell_effect(), spell_effect::charm_monster(), damage_string(), damage_targets(), spell_effect::directed_push(), dps(), spell_effect::explosion(), spell_effect::fungalize(), get_damage_instance(), get_dealt_damage_instance(), spell_effect::guilt(), heal(), spell_effect::mod_moves(), spell_effect::morale(), spell_effect::mutate(), spell_effect::noise(), spell_effect::recharge_vehicle(), spell_effect::recover_energy(), target_ui::run(), sound_volume(), spell_effect::spawn_ethereal_item(), spell_effect::spawn_summoned_monster(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), activity_handlers::spellcasting_finish(), spell_effect::targeted_polymorph(), spell_effect::transform_blast(), and spell_effect::upgrade().
damage_dot()
int spell::damage_dot (const Creature & caster) const
Definition at line 750 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     const int leveled_dot = min_leveled_dot( caster );
     if( type->min_dot.evaluate( d ) >= 0 ||
         type->max_dot.evaluate( d ) >= type->min_dot.evaluate( d ) ) {
         return std::min( leveled_dot, static_cast<int>( type->max_dot.evaluate( d ) ) );
     } else { // if it's negative, min and max work differently
         return std::max( leveled_dot, static_cast<int>( type->max_dot.evaluate( d ) ) );
     }
 }
References dbl_or_var::evaluate(), get_talker_for(), max(), spell_type::max_dot, min(), spell_type::min_dot, min_leveled_dot(), and type.
Referenced by damage_over_time(), dps(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
damage_over_time()
damage_over_time_data spell::damage_over_time (const std::vector< bodypart_str_id > & bps, const Creature & caster) const
Definition at line 762 of file magic.cpp.
 {
     damage_over_time_data temp;
     temp.bps = bps;
     temp.duration = duration_turns( caster );
     temp.amount = damage_dot( caster );
     temp.type = dmg_type();
     return temp;
 }
References damage_dot(), dmg_type(), duration_turns(), and temp.
Referenced by damage_targets().
damage_string()
std::string spell::damage_string (const Character & caster) const
Definition at line 773 of file magic.cpp.
 {
     std::string damage_string;
     dialogue d( get_talker_for( caster ), nullptr );
     if( has_flag( spell_flag::RANDOM_DAMAGE ) ) {
         damage_string = string_format( "%d-%d", min_leveled_damage( caster ),
                                        static_cast<int>( type->max_damage.evaluate( d ) ) );
     } else {
         const int dmg = damage( caster );
         if( dmg >= 0 ) {
             damage_string = string_format( "%d", dmg );
         } else {
             damage_string = string_format( "+%d", std::abs( dmg ) );
         }
     }
     if( has_flag( spell_flag::PERCENTAGE_DAMAGE ) ) {
         damage_string = string_format( "%s%% %s", damage_string, _( "of current HP" ) );
     }
     return damage_string;
 }
References _, abs(), damage(), dbl_or_var::evaluate(), get_talker_for(), has_flag(), spell_type::max_damage, min_leveled_damage(), PERCENTAGE_DAMAGE, RANDOM_DAMAGE, string_format(), and type.
Referenced by target_ui::panel_spell_info(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
damage_type_color()
nc_color spell::damage_type_color () const
Definition at line 1548 of file magic.cpp.
 {
     if( dmg_type().is_null() ) {
         return c_black;
     }
     return dmg_type()->magic_color;
 }
References c_black, dmg_type(), and damage_type::magic_color.
Referenced by debug_menu::spell_description(), spell_effect_area(), and spellcasting_callback::spell_info_text().
damage_type_string()
std::string spell::damage_type_string () const
Definition at line 1556 of file magic.cpp.
 {
     if( dmg_type().is_null() ) {
         return std::string();
     }
     return dmg_type()->name.translated();
 }
References dmg_type(), damage_type::name, and translation::translated().
Referenced by debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
description()
std::string spell::description () const
Definition at line 1543 of file magic.cpp.
 {
     return type->description.translated();
 }
References spell_type::description, translation::translated(), and type.
Referenced by target_ui::panel_spell_info(), diary::spell_changes(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
dmg_type()
const damage_type_id & spell::dmg_type () const private
Definition at line 1758 of file magic.cpp.
 {
     return type->dmg_type;
 }
References spell_type::dmg_type, and type.
Referenced by damage_over_time(), damage_type_color(), damage_type_string(), get_damage_instance(), and get_dealt_damage_instance().
dps()
float spell::dps (const Character & caster, const Creature & target) const
Definition at line 693 of file magic.cpp.
 {
     if( type->effect_name != "attack" ) {
         return 0.0f;
     }
     const float time_modifier = 100.0f / casting_time( caster );
     const float failure_modifier = 1.0f - spell_fail( caster );
     const float raw_dps = damage( caster ) + damage_dot( caster ) * duration_turns( caster ) / 1_turns;
     // TODO: calculate true dps with armor and resistances and any caster bonuses
     return raw_dps * time_modifier * failure_modifier;
 }
References casting_time(), damage(), damage_dot(), duration_turns(), spell_type::effect_name, spell_fail(), and type.
Referenced by npc_attack_spell::evaluate_tripoint().
duration()
int spell::duration (const Creature & caster) const
Definition at line 965 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     const int leveled_duration = min_leveled_duration( caster );
     float duration;
     if( has_flag( spell_flag::RANDOM_DURATION ) ) {
         return rng( std::min( leveled_duration, static_cast<int>( type->max_duration.evaluate( d ) ) ),
                     std::max( leveled_duration,
                               static_cast<int>( type->max_duration.evaluate( d ) ) ) );
     } else {
         if( type->max_duration.evaluate( d ) >= type->min_duration.evaluate( d ) ) {
             return std::min( leveled_duration, static_cast<int>( type->max_duration.evaluate( d ) ) );
         } else {
             return std::max( leveled_duration, static_cast<int>( type->max_duration.evaluate( d ) ) );
         }
     }
     return std::max( duration * temp_duration_multiplyer, 0.0f );
 }
References dbl_or_var::evaluate(), get_talker_for(), has_flag(), max(), spell_type::max_duration, min(), spell_type::min_duration, min_leveled_duration(), RANDOM_DURATION, rng(), temp_duration_multiplyer, and type.
Referenced by add_effect_to_target(), spell_effect::charm_monster(), duration_string(), duration_turns(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
duration_string()
std::string spell::duration_string (const Creature & caster) const
Definition at line 985 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     if( has_flag( spell_flag::RANDOM_DURATION ) ) {
         return string_format( "%s - %s", moves_to_string( min_leveled_duration( caster ) ),
                               moves_to_string( type->max_duration.evaluate( d ) ) );
     } else if( ( has_flag( spell_flag::PERMANENT ) && ( is_max_level( caster ) ||
                  effect() == "summon" ) ) ||
                has_flag( spell_flag::PERMANENT_ALL_LEVELS ) ) {
         return _( "Permanent" );
     } else {
         return moves_to_string( duration( caster ) );
     }
 }
References _, duration(), effect(), dbl_or_var::evaluate(), get_talker_for(), has_flag(), is_max_level(), spell_type::max_duration, min_leveled_duration(), moves_to_string(), PERMANENT, PERMANENT_ALL_LEVELS, RANDOM_DURATION, string_format(), and type.
Referenced by debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
duration_turns()
time_duration spell::duration_turns (const Creature & caster) const
Definition at line 1000 of file magic.cpp.
 {
     return time_duration::from_moves( duration( caster ) );
 }
References duration(), and time_duration::from_moves().
Referenced by create_field(), damage_over_time(), dps(), spell_effect::guilt(), spell_effect::morale(), spell_effect::slime_split_on_death(), spell_effect::spawn_ethereal_item(), spell_effect::spawn_summoned_monster(), spell_effect::spawn_summoned_vehicle(), and spell_effect::timed_event().
effect()
std::string spell::effect () const
Definition at line 1454 of file magic.cpp.
 {
     return type->effect_name;
 }
References spell_type::effect_name, and type.
Referenced by duration_string(), enumerate_spell_data(), target_ui::panel_spell_info(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
effect_area() [1/2]
std::set< tripoint > spell::effect_area (const spell_effect::override_parameters & params, const tripoint & source, const tripoint & target) const
Definition at line 873 of file magic.cpp.
 {
     return type->spell_area_function( params, source, target );
 }
References spell_type::spell_area_function, and type.
Referenced by calculate_spell_effect_area(), and effect_area().
effect_area() [2/2]
std::set< tripoint > spell::effect_area (const tripoint & source, const tripoint & target, const Creature & caster) const
Definition at line 879 of file magic.cpp.
 {
     return effect_area( spell_effect::override_parameters( *this, caster ), source, target );
 }
References effect_area().
effect_data()
std::string spell::effect_data () const
Definition at line 1794 of file magic.cpp.
 {
     return type->effect_str;
 }
References spell_type::effect_str, and type.
Referenced by add_effect_to_target(), add_summoned_mon(), spell_effect::add_trap(), damage_targets(), spell_effect::effect_on_condition(), spell_effect::emit(), spell_effect::guilt(), magical_polymorph(), spell_effect::morale(), spell_effect::mutate(), spell_effect::recover_energy(), spell_effect::remove_effect(), spell_effect::remove_field(), spell_effect::revive(), spell_effect::revive_dormant(), spell_effect::spawn_ethereal_item(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), spell_effect::timed_event(), and spell_effect::transform_blast().
energy_cost()
int spell::energy_cost (const Character & guy) const
Definition at line 1040 of file magic.cpp.
 {
     int cost;
     dialogue d( get_talker_for( guy ), nullptr );
     if( type->base_energy_cost.evaluate( d ) < type->final_energy_cost.evaluate( d ) ) {
         cost = std::min( static_cast<int>( type->final_energy_cost.evaluate( d ) ),
                          static_cast<int>( std::round( type->base_energy_cost.evaluate( d ) +
                                            type->energy_increment.evaluate( d ) * get_effective_level() ) ) );
     } else if( type->base_energy_cost.evaluate( d ) > type->final_energy_cost.evaluate( d ) ) {
         cost = std::max( static_cast<int>( type->final_energy_cost.evaluate( d ) ),
                          static_cast<int>( std::round( type->base_energy_cost.evaluate( d ) +
                                            type->energy_increment.evaluate( d ) * get_effective_level() ) ) );
     } else {
         cost = type->base_energy_cost.evaluate( d );
     }
     if( !no_hands() && !guy.has_flag( json_flag_SUBTLE_SPELL ) ) {
         // the first 10 points of combined encumbrance is ignored, but quickly adds up
         const int hands_encumb = std::max( 0,
                                            guy.avg_encumb_of_limb_type( body_part_type::type::hand ) - 5 );
         switch( type->energy_source ) {
             default:
                 cost += 10 * hands_encumb * temp_somatic_difficulty_multiplyer;
                 break;
             case magic_energy_type::hp:
                 cost += hands_encumb * temp_somatic_difficulty_multiplyer;
                 break;
             case magic_energy_type::stamina:
                 cost += 100 * hands_encumb * temp_somatic_difficulty_multiplyer;
                 break;
         }
     }
     return std::max( cost * temp_spell_cost_multiplyer, 0.0f );
 }
References Character::avg_encumb_of_limb_type(), spell_type::base_energy_cost, spell_type::energy_increment, spell_type::energy_source, dbl_or_var::evaluate(), spell_type::final_energy_cost, get_effective_level(), get_talker_for(), body_part_type::hand, Character::has_flag(), hp, json_flag_SUBTLE_SPELL, max(), min(), no_hands(), round(), stamina, temp_somatic_difficulty_multiplyer, temp_spell_cost_multiplyer, and type.
Referenced by cast_spell_effect(), energy_cost_string(), known_magic::has_enough_energy(), and activity_handlers::spellcasting_finish().
energy_cost_encumbered()
bool spell::energy_cost_encumbered (const Character & guy) const
Definition at line 2398 of file magic.cpp.
 {
     if( !no_hands() && !guy.has_flag( json_flag_SUBTLE_SPELL ) ) {
         return std::max( 0, guy.avg_encumb_of_limb_type( body_part_type::type:: hand ) - 5 ) >
                0;
     }
     return false;
 }
References Character::avg_encumb_of_limb_type(), body_part_type::hand, Character::has_flag(), json_flag_SUBTLE_SPELL, max(), and no_hands().
Referenced by debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
energy_cost_string()
std::string spell::energy_cost_string (const Character & guy) const
Definition at line 1353 of file magic.cpp.
 {
     if( energy_source() == magic_energy_type::none ) {
         return _( "none" );
     }
     if( energy_source() == magic_energy_type::bionic || energy_source() == magic_energy_type::mana ) {
         return colorize( std::to_string( energy_cost( guy ) ), c_light_blue );
     }
     if( energy_source() == magic_energy_type::hp ) {
         auto pair = get_hp_bar( energy_cost( guy ), guy.get_hp_max() / 6 );
         return colorize( pair.first, pair.second );
     }
     if( energy_source() == magic_energy_type::stamina ) {
         auto pair = get_hp_bar( energy_cost( guy ), guy.get_stamina_max() );
         return colorize( pair.first, pair.second );
     }
     debugmsg( "ERROR: Spell %s has invalid energy source.", id().c_str() );
     return _( "error: energy_type" );
 }
References _, bionic, c_light_blue, colorize(), debugmsg, energy_cost(), energy_source(), get_hp_bar(), Creature::get_hp_max(), Character::get_stamina_max(), hp, mana, none, stamina, and to_string().
Referenced by target_ui::panel_spell_info(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
energy_cur_string()
std::string spell::energy_cur_string (const Character & guy) const
Definition at line 1373 of file magic.cpp.
 {
     if( energy_source() == magic_energy_type::none ) {
         return _( "infinite" );
     }
     if( energy_source() == magic_energy_type::bionic ) {
         return colorize( std::to_string( units::to_kilojoule( guy.get_power_level() ) ), c_light_blue );
     }
     if( energy_source() == magic_energy_type::mana ) {
         return colorize( std::to_string( guy.magic->available_mana() ), c_light_blue );
     }
     if( energy_source() == magic_energy_type::stamina ) {
         auto pair = get_hp_bar( guy.get_stamina(), guy.get_stamina_max() );
         return colorize( pair.first, pair.second );
     }
     if( energy_source() == magic_energy_type::hp ) {
         return "";
     }
     debugmsg( "ERROR: Spell %s has invalid energy source.", id().c_str() );
     return _( "error: energy_type" );
 }
References _, bionic, c_light_blue, colorize(), debugmsg, energy_source(), get_hp_bar(), Character::get_power_level(), Character::get_stamina(), Character::get_stamina_max(), hp, Character::magic, mana, none, stamina, units::to_kilojoule(), and to_string().
Referenced by target_ui::panel_spell_info(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
energy_source()
magic_energy_type spell::energy_source () const
Definition at line 1459 of file magic.cpp.
 {
     return type->energy_source;
 }
References spell_type::energy_source, and type.
Referenced by Character::cast_spell(), energy_cost_string(), energy_cur_string(), known_magic::has_enough_energy(), target_ui::panel_spell_info(), spellcasting_callback::spell_info_text(), and activity_handlers::spellcasting_finish().
energy_string()
std::string spell::energy_string () const
Definition at line 1337 of file magic.cpp.
 {
     switch( type->energy_source ) {
         case magic_energy_type::hp:
             return _( "health" );
         case magic_energy_type::mana:
             return _( "mana" );
         case magic_energy_type::stamina:
             return _( "stamina" );
         case magic_energy_type::bionic:
             return _( "kJ" );
         default:
             return "";
     }
 }
References _, bionic, spell_type::energy_source, hp, mana, stamina, and type.
Referenced by Character::cast_spell(), target_ui::panel_spell_info(), target_ui::run(), and spellcasting_callback::spell_info_text().
enumerate_spell_data()
std::string spell::enumerate_spell_data (const Character & guy) const
Definition at line 2409 of file magic.cpp.
 {
     std::vector<std::string> spell_data;
     if( has_flag( spell_flag::PSIONIC ) ) {
         spell_data.emplace_back( _( "is a psionic power" ) );
     }
     if( has_flag( spell_flag::CONCENTRATE ) && !has_flag( spell_flag::PSIONIC ) &&
         temp_concentration_difficulty_multiplyer > 0 ) {
         spell_data.emplace_back( _( "requires concentration" ) );
     }
     if( has_flag( spell_flag::VERBAL ) && temp_sound_multiplyer > 0 ) {
         spell_data.emplace_back( _( "verbal" ) );
     }
     if( has_flag( spell_flag::SOMATIC ) && temp_somatic_difficulty_multiplyer > 0 ) {
         spell_data.emplace_back( _( "somatic" ) );
     }
     if( !no_hands() ) {
         spell_data.emplace_back( _( "impeded by gloves" ) );
     } else if( no_hands() && !has_flag( spell_flag::PSIONIC ) ) {
         spell_data.emplace_back( _( "does not require hands" ) );
     }
     if( !has_flag( spell_flag::NO_LEGS ) && temp_somatic_difficulty_multiplyer > 0 ) {
         spell_data.emplace_back( _( "requires mobility" ) );
     }
     if( effect() == "attack" && range( guy ) > 1 && has_flag( spell_flag::NO_PROJECTILE ) &&
         !has_flag( spell_flag::PSIONIC ) ) {
         spell_data.emplace_back( _( "can be cast through walls" ) );
     }
     if( effect() == "attack" && range( guy ) > 1 && has_flag( spell_flag::NO_PROJECTILE ) &&
         has_flag( spell_flag::PSIONIC ) ) {
         spell_data.emplace_back( _( "can be channeled through walls" ) );
     }
     return enumerate_as_string( spell_data );
 }
References _, CONCENTRATE, effect(), enumerate_as_string(), has_flag(), no_hands(), NO_LEGS, NO_PROJECTILE, PSIONIC, range(), SOMATIC, temp_concentration_difficulty_multiplyer, temp_somatic_difficulty_multiplyer, temp_sound_multiplyer, and VERBAL.
Referenced by debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
enumerate_targets()
std::string spell::enumerate_targets () const
Definition at line 1683 of file magic.cpp.
 {
     std::vector<std::string> all_valid_targets;
     int last_target = static_cast<int>( spell_target::num_spell_targets );
     for( int i = 0; i < last_target; ++i ) {
         spell_target t = static_cast<spell_target>( i );
         if( is_valid_target( t ) && t != spell_target::none ) {
             all_valid_targets.emplace_back( target_to_string( t ) );
         }
     }
     if( all_valid_targets.size() == 1 ) {
         return all_valid_targets[0];
     }
     std::string ret;
     // TODO: if only we had a function to enumerate strings and concatenate them...
     for( auto iter = all_valid_targets.begin(); iter != all_valid_targets.end(); iter++ ) {
         if( iter + 1 == all_valid_targets.end() ) {
             ret = string_format( _( "%s and %s" ), ret, *iter );
         } else if( iter == all_valid_targets.begin() ) {
             ret = *iter;
         } else {
             ret = string_format( _( "%s, %s" ), ret, *iter );
         }
     }
     return ret;
 }
References _, is_valid_target(), none, num_spell_targets, cata::hash64_detail::ret, string_format(), and target_to_string().
Referenced by debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
exp_for_level()
int spell::exp_for_level (int level) static
Definition at line 1641 of file magic.cpp.
 {
     // level 0 never needs xp
     if( level == 0 ) {
         return 0;
     }
     return std::ceil( std::exp( ( level - c ) * b ) ) - a;
 }
References a, b, c, and ceil().
Referenced by debug_menu::change_spells(), exp_progress(), exp_to_next_level(), fake_spell::get_spell(), and anonymous_namespace{math_parser_diag.cpp}::spell_exp_for_level_eval().
exp_modifier()
float spell::exp_modifier (const Character & guy) const
Definition at line 1666 of file magic.cpp.
 {
     const float int_modifier = ( guy.get_int() - 8.0f ) / 8.0f;
     const float difficulty_modifier = get_difficulty( guy ) / 20.0f;
     const float spellcraft_modifier = guy.get_skill_level( skill() ) / 10.0f;
     return ( int_modifier + difficulty_modifier + spellcraft_modifier ) / 5.0f + 1.0f;
 }
References get_difficulty(), Character::get_int(), Character::get_skill_level(), and skill().
Referenced by casting_exp(), magic_train(), and activity_handlers::study_spell_do_turn().
exp_progress()
std::string spell::exp_progress () const
Definition at line 1655 of file magic.cpp.
 {
     const int level = get_level();
     const int this_level_xp = exp_for_level( level );
     const int next_level_xp = exp_for_level( level + 1 );
     const int denominator = next_level_xp - this_level_xp;
     const float progress = static_cast<float>( xp() - this_level_xp ) / std::max( 1.0f,
                            static_cast<float>( denominator ) );
     return string_format( "%i%%", clamp( static_cast<int>( std::round( progress * 100 ) ), 0, 99 ) );
 }
References clamp(), exp_for_level(), get_level(), max(), round(), string_format(), and xp().
exp_to_next_level()
int spell::exp_to_next_level () const
Definition at line 1650 of file magic.cpp.
 {
     return exp_for_level( get_level() + 1 ) - xp();
 }
References exp_for_level(), get_level(), and xp().
Referenced by gain_level(), and spellcasting_callback::spell_info_text().
field_intensity()
int spell::field_intensity (const Creature & caster) const
Definition at line 677 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     return std::min( static_cast<int>( type->max_field_intensity.evaluate( d ) ),
                      static_cast<int>( type->min_field_intensity.evaluate( d ) + std::round( get_effective_level() *
                                        type->field_intensity_increment.evaluate( d ) ) ) );
 }
References dbl_or_var::evaluate(), spell_type::field_intensity_increment, get_effective_level(), get_talker_for(), spell_type::max_field_intensity, min(), spell_type::min_field_intensity, round(), and type.
Referenced by create_field(), and npc_attack_spell::evaluate_tripoint().
gain_exp()
void spell::gain_exp (const Character & guy, int nxp)
Definition at line 1322 of file magic.cpp.
 {
     int oldLevel = get_level();
     experience += nxp;
     if( guy.is_avatar() && oldLevel != get_level() ) {
         get_event_bus().send<event_type::player_levels_spell>( guy.getID(), id(), get_level(),
                 spell_class() );
     }
 }
References experience, get_event_bus(), get_level(), Character::getID(), id(), Creature::is_avatar(), player_levels_spell, event_bus::send(), and spell_class().
Referenced by gain_level(), magic_train(), activity_handlers::spellcasting_finish(), and activity_handlers::study_spell_do_turn().
gain_level()
void spell::gain_level (const Character & guy)
Definition at line 1005 of file magic.cpp.
 {
     gain_exp( guy, exp_to_next_level() );
 }
References exp_to_next_level(), and gain_exp().
Referenced by gain_levels(), profession::learn_spells(), known_magic::on_mutation_gain(), npc::randomize(), and activity_handlers::spellcasting_finish().
gain_levels()
void spell::gain_levels (const Character & guy, int gains)
Definition at line 1010 of file magic.cpp.
 {
     if( gains < 1 ) {
         return;
     }
     for( int gained = 0; gained < gains && !is_max_level( guy ); gained++ ) {
         gain_level( guy );
     }
 }
References gain_level(), and is_max_level().
Referenced by set_level().
get_damage_instance()
damage_instance spell::get_damage_instance (Creature & caster) const
Definition at line 1763 of file magic.cpp.
 {
     damage_instance dmg;
     dmg.add_damage( dmg_type(), damage( caster ) );
     return dmg;
 }
References damage_instance::add_damage(), damage(), and dmg_type().
Referenced by get_projectile_attack().
get_dealt_damage_instance()
dealt_damage_instance spell::get_dealt_damage_instance (Creature & caster) const
Definition at line 1770 of file magic.cpp.
 {
     dealt_damage_instance dmg;
     dmg.set_damage( dmg_type(), damage( caster ) );
     return dmg;
 }
References damage(), dmg_type(), and dealt_damage_instance::set_damage().
get_difficulty()
int spell::get_difficulty (const Creature & caster) const
Definition at line 1147 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     return type->difficulty.evaluate( d ) + temp_difficulty_adjustment;
 }
References spell_type::difficulty, dbl_or_var::evaluate(), get_talker_for(), temp_difficulty_adjustment, and type.
Referenced by calc_spell_training_cost(), cast_spell_effect(), exp_modifier(), debug_menu::spell_description(), spell_fail(), spellcasting_callback::spell_info_text(), talker_character_const::spell_training_text(), activity_handlers::spellcasting_finish(), activity_handlers::study_spell_do_turn(), and learn_spell_actor::use().
get_effective_level()
int spell::get_effective_level () const
Definition at line 1576 of file magic.cpp.
 {
     return get_level() + temp_level_adjustment;
 }
References get_level(), and temp_level_adjustment.
Referenced by cast_all_effects(), cast_extra_spell_effects(), casting_time(), energy_cost(), field_intensity(), spell_effect::guilt(), min_leveled_accuracy(), min_leveled_aoe(), min_leveled_damage(), min_leveled_dot(), min_leveled_duration(), range(), spell_fail(), and spellcasting_callback::spell_info_text().
get_level()
int spell::get_level () const
Definition at line 1570 of file magic.cpp.
 {
     // you aren't at the next level unless you have the requisite xp, so floor
     return std::max( static_cast<int>( std::floor( std::log( experience + a ) / b + c ) ), 0 );
 }
References a, b, c, experience, floor(), log(), and max().
Referenced by Character::add_bionic(), calc_spell_training_cost(), Character::cast_spell(), exp_progress(), exp_to_next_level(), gain_exp(), get_effective_level(), learn_spell_actor::info(), is_max_level(), profession::learn_spells(), diary::new_page(), target_ui::panel_spell_info(), npc::randomize(), known_magic::set_spell_exp(), talker_character_const::spell_training_text(), activity_handlers::spellcasting_finish(), Character::spells_offered_to(), talk_function::start_training_gen(), activity_handlers::study_spell_do_turn(), and learn_spell_actor::use().
get_max_level()
int spell::get_max_level (const Creature & caster) const
Definition at line 1581 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     return type->max_level.evaluate( d );
 }
References dbl_or_var::evaluate(), get_talker_for(), spell_type::max_level, and type.
Referenced by fake_spell::get_spell(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
get_projectile_attack()
dealt_projectile_attack spell::get_projectile_attack (const tripoint & target, Creature & hit_critter, Creature & caster) const
Definition at line 1777 of file magic.cpp.
 {
     projectile bolt;
     bolt.speed = 10000;
     bolt.impact = get_damage_instance( caster );
     bolt.proj_effects.emplace( "MAGIC" );
     dealt_projectile_attack atk;
     atk.end_point = target;
     atk.hit_critter = &hit_critter;
     atk.proj = bolt;
     atk.missed_by = 0.0;
     return atk;
 }
References dealt_projectile_attack::end_point, get_damage_instance(), dealt_projectile_attack::hit_critter, projectile::impact, dealt_projectile_attack::missed_by, dealt_projectile_attack::proj, projectile::proj_effects, and projectile::speed.
Referenced by damage_targets().
get_src()
mod_id spell::get_src () const
Definition at line 1153 of file magic.cpp.
 {
     return type->src_mod;
 }
References spell_type::src_mod, and type.
get_temp_level_adjustment()
int spell::get_temp_level_adjustment () const
Definition at line 1587 of file magic.cpp.
 {
     return temp_level_adjustment;
 }
References temp_level_adjustment.
Referenced by spellcasting_callback::spell_info_text().
has_components()
bool spell::has_components () const
Definition at line 1202 of file magic.cpp.
 {
     return !type->spell_components.is_empty();
 }
References string_id< T >::is_empty(), spell_type::spell_components, and type.
Referenced by debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
has_flag() [1/2]
bool spell::has_flag (const spell_flag & flag) const
Definition at line 1074 of file magic.cpp.
 {
     return type->spell_tags[flag];
 }
References spell_type::spell_tags, and type.
Referenced by add_effect_to_target(), add_summoned_mon(), aoe(), aoe_string(), spell_effect::attack(), npc_attack_spell::base_time_penalty(), spell_effect::bash(), calculate_spell_effect_area(), can_cast(), cast_all_effects(), cast_extra_spell_effects(), casting_time(), casting_time_encumbered(), spell_effect::charm_monster(), damage(), damage_string(), damage_targets(), duration(), duration_string(), enumerate_spell_data(), in_aoe(), is_summon_friendly(), magical_polymorph(), spell_effect::mutate(), no_hands(), spell_effect::override_parameters::override_parameters(), random_valid_target(), spell_effect::recover_energy(), select_target(), spell_effect::short_range_teleport(), spell_effect::slime_split_on_death(), sound_volume(), spell_effect::spawn_ethereal_item(), spell_effect::spawn_summoned_vehicle(), debug_menu::spell_description(), spell_effect_area(), spell_fail(), spellcasting_callback::spell_info_text(), activity_handlers::spellcasting_finish(), targetable_locations(), and npc_attack_spell::use().
has_flag() [2/2]
bool spell::has_flag (const std::string & flag) const
Definition at line 1079 of file magic.cpp.
 {
     return type->flags.count( flag ) > 0;
 }
References spell_type::flags, and type.
heal()
int spell::heal (const tripoint & target, Creature & caster) const
Definition at line 1804 of file magic.cpp.
 {
     creature_tracker &creatures = get_creature_tracker();
     monster *const mon = creatures.creature_at<monster>( target );
     if( mon ) {
         return mon->heal( -damage( caster ) );
     }
     Character *const p = creatures.creature_at<Character>( target );
     if( p ) {
         p->healall( -damage( caster ) );
         return -damage( caster );
     }
     return -1;
 }
References creature_tracker::creature_at(), damage(), get_creature_tracker(), monster::heal(), and Character::healall().
Referenced by damage_targets().
id()
spell_id spell::id () const
Definition at line 662 of file magic.cpp.
 {
     return type;
 }
References type.
Referenced by Character::cast_spell(), cast_spell_effect(), spell_effect::effect_on_condition(), gain_exp(), spell_effect::morale(), diary::new_page(), target_ui::set_cursor_pos(), debug_menu::spell_description(), spell_effect_area(), and cast_spell_actor::use().
ignore_by_species_id()
bool spell::ignore_by_species_id (const tripoint & p) const
Definition at line 1524 of file magic.cpp.
 {
     if( type->ignored_species_ids.empty() ) {
         return true;
     }
     bool valid = true;
     if( monster *const target = get_creature_tracker().creature_at<monster>( p ) ) {
         for( const species_id &spid : type->ignored_species_ids ) {
             if( target->type->in_species( spid ) ) {
                 valid = false;
             }
         }
     }
     return valid;
 }
References get_creature_tracker(), spell_type::ignored_species_ids, and type.
Referenced by is_valid_target().
in_aoe()
bool spell::in_aoe (const tripoint & source, const tripoint & target, const Creature & caster) const
Definition at line 885 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     if( has_flag( spell_flag::RANDOM_AOE ) ) {
         return rl_dist( source, target ) <= type->max_aoe.evaluate( d );
     } else {
         return rl_dist( source, target ) <= aoe( caster );
     }
 }
References aoe(), dbl_or_var::evaluate(), get_talker_for(), has_flag(), spell_type::max_aoe, RANDOM_AOE, rl_dist(), and type.
Referenced by target_ui::panel_spell_info().
is_max_level()
bool spell::is_max_level (const Creature & caster) const
Definition at line 1026 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     return get_level() >= type->max_level.evaluate( d );
 }
References dbl_or_var::evaluate(), get_level(), get_talker_for(), spell_type::max_level, and type.
Referenced by duration_string(), gain_levels(), learn_spell_actor::info(), profession::learn_spells(), npc::randomize(), spell_effect::spawn_ethereal_item(), spellcasting_callback::spell_info_text(), activity_handlers::spellcasting_finish(), Character::spells_offered_to(), and learn_spell_actor::use().
is_spell_class()
bool spell::is_spell_class (const trait_id & mid) const
Definition at line 1088 of file magic.cpp.
 {
     return mid == type->spell_class;
 }
References spell_type::spell_class, and type.
is_target_in_range()
bool spell::is_target_in_range (const Creature & caster, const tripoint & p) const
Definition at line 1464 of file magic.cpp.
 {
     return rl_dist( caster.pos(), p ) <= range( caster );
 }
References Creature::pos(), range(), and rl_dist().
Referenced by enchant_cache::cast_enchantment_spell(), and monster::die().
is_valid()
bool spell::is_valid () const
Definition at line 1395 of file magic.cpp.
 {
     return type.is_valid();
 }
References string_id< T >::is_valid(), and type.
Referenced by known_magic::learn_spell().
is_valid_target() [1/2]
bool spell::is_valid_target (const Creature & caster, const tripoint & p) const
Definition at line 1474 of file magic.cpp.
 {
     bool valid = false;
     if( Creature *const cr = get_creature_tracker().creature_at<Creature>( p ) ) {
         Creature::Attitude cr_att = cr->attitude_to( caster );
         valid = valid || ( cr_att != Creature::Attitude::FRIENDLY &&
                            is_valid_target( spell_target::hostile ) );
         valid = valid || ( cr_att == Creature::Attitude::FRIENDLY &&
                            is_valid_target( spell_target::ally ) &&
                            p != caster.pos() );
         valid = valid || ( is_valid_target( spell_target::self ) && p == caster.pos() );
         valid = valid && target_by_monster_id( p );
         valid = valid && target_by_species_id( p );
         valid = valid && ignore_by_species_id( p );
     } else {
         valid = is_valid_target( spell_target::ground );
     }
     return valid;
 }
References ally, Creature::FRIENDLY, get_creature_tracker(), ground, hostile, ignore_by_species_id(), Creature::pos(), self, target_by_monster_id(), and target_by_species_id().
Referenced by spell_effect::banishment(), spell_effect::bash(), calculate_spell_effect_area(), enchant_cache::cast_enchantment_spell(), spell_effect::charm_monster(), damage_targets(), spell_effect::directed_push(), spell_effect::effect_on_condition(), enumerate_targets(), spell_effect::flashbang(), spell_effect::mod_moves(), spell_effect::morale(), spell_effect::mutate(), random_valid_target(), select_target(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), spell_move(), activity_handlers::spellcasting_finish(), targetable_locations(), target_ui::update_status(), and spell_effect::vomit().
is_valid_target() [2/2]
bool spell::is_valid_target (spell_target t) const
Definition at line 1469 of file magic.cpp.
 {
     return type->valid_targets[t];
 }
References type, and spell_type::valid_targets.
list_ignored_species_names()
std::string spell::list_ignored_species_names () const
Definition at line 1742 of file magic.cpp.
 {
     if( type->ignored_species_ids.empty() ) {
         return "";
     }
     std::vector<std::string> all_valid_species_names;
     for( const species_id &species_id : type->ignored_species_ids ) {
         all_valid_species_names.emplace_back( species_id.str() );
     }
     //remove repeat names
     all_valid_species_names.erase( std::unique( all_valid_species_names.begin(),
                                    all_valid_species_names.end() ), all_valid_species_names.end() );
     std::string ret = enumerate_as_string( all_valid_species_names );
     return ret;
 }
References enumerate_as_string(), spell_type::ignored_species_ids, cata::hash64_detail::ret, string_id< T >::str(), and type.
list_targeted_monster_names()
std::string spell::list_targeted_monster_names () const
Definition at line 1710 of file magic.cpp.
 {
     if( type->targeted_monster_ids.empty() ) {
         return "";
     }
     std::vector<std::string> all_valid_monster_names;
     for( const mtype_id &mon_id : type->targeted_monster_ids ) {
         all_valid_monster_names.emplace_back( mon_id->nname() );
     }
     //remove repeat names
     all_valid_monster_names.erase( std::unique( all_valid_monster_names.begin(),
                                    all_valid_monster_names.end() ), all_valid_monster_names.end() );
     std::string ret = enumerate_as_string( all_valid_monster_names );
     return ret;
 }
References enumerate_as_string(), mtype::nname(), cata::hash64_detail::ret, spell_type::targeted_monster_ids, and type.
Referenced by debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
list_targeted_species_names()
std::string spell::list_targeted_species_names () const
Definition at line 1726 of file magic.cpp.
 {
     if( type->targeted_species_ids.empty() ) {
         return "";
     }
     std::vector<std::string> all_valid_species_names;
     for( const species_id &specie_id : type->targeted_species_ids ) {
         all_valid_species_names.emplace_back( specie_id.str() );
     }
     //remove repeat names
     all_valid_species_names.erase( std::unique( all_valid_species_names.begin(),
                                    all_valid_species_names.end() ), all_valid_species_names.end() );
     std::string ret = enumerate_as_string( all_valid_species_names );
     return ret;
 }
References enumerate_as_string(), cata::hash64_detail::ret, string_id< T >::str(), spell_type::targeted_species_ids, and type.
make_sound() [1/2]
void spell::make_sound (const tripoint & target, Creature & caster) const
Definition at line 1440 of file magic.cpp.
 {
     const int loudness = sound_volume( caster );
     if( loudness > 0 ) {
         make_sound( target, loudness );
     }
 }
References sound_volume().
Referenced by spell_effect::area_pull(), spell_effect::area_push(), trapfunc::cast_spell(), spell_effect::charm_monster(), damage_targets(), spell_effect::mod_moves(), spell_effect::morale(), spell_effect::mutate(), spell_effect::noise(), spell_effect::pain_split(), spell_effect::recover_energy(), spell_effect::remove_field(), spell_effect::slime_split_on_death(), spell_effect::spawn_ethereal_item(), spell_effect::spawn_summoned_monster(), spell_effect::timed_event(), and spell_effect::vomit().
make_sound() [2/2]
void spell::make_sound (const tripoint & target, int loudness) const
Definition at line 1448 of file magic.cpp.
 {
     sounds::sound( target, loudness, type->sound_type, type->sound_description.translated(),
                    type->sound_ambient, type->sound_id, type->sound_variant );
 }
References sounds::sound(), spell_type::sound_ambient, spell_type::sound_description, spell_type::sound_id, spell_type::sound_type, spell_type::sound_variant, translation::translated(), and type.
message()
std::string spell::message () const
Definition at line 1212 of file magic.cpp.
 {
     if( !alt_message.empty() ) {
         return alt_message.translated();
     }
     return type->message.translated();
 }
References alt_message, translation::empty(), spell_type::message, translation::translated(), and type.
Referenced by relic::activate(), mon_spellcasting_actor::call(), cast_all_effects(), and activity_handlers::spellcasting_finish().
min_leveled_accuracy()
int spell::min_leveled_accuracy (const Creature & caster) const private
Definition at line 724 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     return type->min_accuracy.evaluate( d ) + std::round( get_effective_level() *
             type->accuracy_increment.evaluate( d ) );
 }
References spell_type::accuracy_increment, dbl_or_var::evaluate(), get_effective_level(), get_talker_for(), spell_type::min_accuracy, round(), and type.
Referenced by accuracy().
min_leveled_aoe()
int spell::min_leveled_aoe (const Creature & caster) const private
Definition at line 847 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     return type->min_aoe.evaluate( d ) + std::round( get_effective_level() *
             type->aoe_increment.evaluate( d ) );
 }
References spell_type::aoe_increment, dbl_or_var::evaluate(), get_effective_level(), get_talker_for(), spell_type::min_aoe, round(), and type.
Referenced by aoe(), and aoe_string().
min_leveled_damage()
int spell::min_leveled_damage (const Creature & caster) const private
Definition at line 685 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     return type->min_damage.evaluate( d ) + std::round( get_effective_level() *
             type->damage_increment.evaluate(
                 d ) );
 }
References spell_type::damage_increment, dbl_or_var::evaluate(), get_effective_level(), get_talker_for(), spell_type::min_damage, round(), and type.
Referenced by damage(), and damage_string().
min_leveled_dot()
int spell::min_leveled_dot (const Creature & caster) const private
Definition at line 743 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     return type->min_dot.evaluate( d ) + std::round( get_effective_level() *
             type->dot_increment.evaluate( d ) );
 }
References spell_type::dot_increment, dbl_or_var::evaluate(), get_effective_level(), get_talker_for(), spell_type::min_dot, round(), and type.
Referenced by damage_dot().
min_leveled_duration()
int spell::min_leveled_duration (const Creature & caster) const private
Definition at line 958 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     return type->min_duration.evaluate( d ) + std::round( get_effective_level() *
             type->duration_increment.evaluate( d ) );
 }
References spell_type::duration_increment, dbl_or_var::evaluate(), get_effective_level(), get_talker_for(), spell_type::min_duration, round(), and type.
Referenced by duration(), and duration_string().
name()
std::string spell::name () const
Definition at line 1207 of file magic.cpp.
 {
     return type->name.translated();
 }
References spell_type::name, translation::translated(), and type.
Referenced by relic::activate(), mon_spellcasting_actor::call(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), spell_effect::none(), target_ui::panel_spell_info(), spell_effect::pull_to_caster(), spell_effect::recover_energy(), select_target(), diary::spell_changes(), debug_menu::spell_description(), talker_character_const::spell_training_text(), activity_handlers::spellcasting_finish(), activity_handlers::study_spell_do_turn(), and npc_attack_spell::use().
no_hands()
bool spell::no_hands () const
Definition at line 1083 of file magic.cpp.
 {
     return ( has_flag( spell_flag::NO_HANDS ) || temp_somatic_difficulty_multiplyer <= 0 );
 }
References has_flag(), NO_HANDS, and temp_somatic_difficulty_multiplyer.
Referenced by Character::cast_spell(), energy_cost(), energy_cost_encumbered(), and enumerate_spell_data().
random_valid_target()
std::optional< tripoint > spell::random_valid_target (const Creature & caster, const tripoint & caster_pos) const
Definition at line 1893 of file magic.cpp.
 {
     const bool ignore_ground = has_flag( spell_flag::RANDOM_CRITTER );
     std::set<tripoint> valid_area;
     spell_effect::override_parameters blast_params( *this, caster );
     // we want to pick a random target within range, not aoe
     blast_params.aoe_radius = range( caster );
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &target : spell_effect::spell_effect_blast(
              blast_params, caster_pos, caster_pos ) ) {
         if( target != caster_pos && is_valid_target( caster, target ) &&
             ( !ignore_ground || creatures.creature_at<Creature>( target ) ) ) {
             valid_area.emplace( target );
         }
     }
     if( valid_area.empty() ) {
         return std::nullopt;
     }
     return random_entry( valid_area );
 }
References spell_effect::override_parameters::aoe_radius, creature_tracker::creature_at(), get_creature_tracker(), has_flag(), is_valid_target(), RANDOM_CRITTER, random_entry(), range(), and spell_effect::spell_effect_blast().
Referenced by cast_all_effects(), cast_extra_spell_effects(), and select_target().
range()
int spell::range (const Creature & caster) const
Definition at line 905 of file magic.cpp.
 {
     dialogue d( get_talker_for( caster ), nullptr );
     const int leveled_range = type->min_range.evaluate( d ) + std::round( get_effective_level() *
                               type->range_increment.evaluate( d ) );
     float range;
     if( type->max_range.evaluate( d ) >= type->min_range.evaluate( d ) ) {
         range = std::min( leveled_range, static_cast<int>( type->max_range.evaluate( d ) ) );
     } else {
         range = std::max( leveled_range, static_cast<int>( type->max_range.evaluate( d ) ) );
     }
     return std::max( range * temp_range_multiplyer, 0.0f );
 }
References dbl_or_var::evaluate(), get_effective_level(), get_talker_for(), max(), spell_type::max_range, min(), spell_type::min_range, spell_type::range_increment, round(), temp_range_multiplyer, and type.
Referenced by mon_spellcasting_actor::call(), enumerate_spell_data(), is_target_in_range(), target_handler::mode_spell(), spell_effect::override_parameters::override_parameters(), random_valid_target(), select_target(), spell_effect::short_range_teleport(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), and targetable_locations().
select_target()
std::optional< tripoint > spell::select_target (Creature * source)
Definition at line 794 of file magic.cpp.
 {
     tripoint target = source->pos();
     bool target_is_valid = false;
     if( range( *source ) > 0 && !is_valid_target( spell_target::none ) &&
         !has_flag( spell_flag::RANDOM_TARGET ) ) {
         if( source->is_avatar() ) {
             do {
                 avatar &source_avatar = *source->as_avatar();
                 std::vector<tripoint> trajectory = target_handler::mode_spell( source_avatar, *this,
                                                    true,
                                                    true );
                 if( !trajectory.empty() ) {
                     target = trajectory.back();
                     target_is_valid = is_valid_target( source_avatar, target );
                     if( !( is_valid_target( spell_target::ground ) || source_avatar.sees( target ) ) ) {
                         target_is_valid = false;
                     }
                 } else {
                     target_is_valid = false;
                 }
                 if( !target_is_valid ) {
                     if( query_yn( _( "Stop targeting?  Time spent will be lost." ) ) ) {
                         return std::nullopt;
                     }
                 }
             } while( !target_is_valid );
         } else if( source->is_npc() ) {
             npc &source_npc = *source->as_npc();
             npc_attack_spell npc_spell( id() );
             // recalculate effectiveness because it's been a few turns since the npc started casting.
             const npc_attack_rating effectiveness = npc_spell.evaluate( source_npc,
                                                     source_npc.last_target.lock().get() );
             if( effectiveness < 0 ) {
                 add_msg_debug( debugmode::debug_filter::DF_NPC, "%s cancels casting %s, target lost",
                                source_npc.disp_name(), name() );
                 return std::nullopt;
             } else {
                 target = effectiveness.target();
             }
         } // TODO: move monster spell attack targeting here
     } else if( has_flag( spell_flag::RANDOM_TARGET ) ) {
         const std::optional<tripoint> target_ = random_valid_target( *source, source->pos() );
         if( !target_ ) {
             source->add_msg_if_player( game_message_params{ m_bad, gmf_bypass_cooldown },
                                        _( "You can't find a suitable target." ) );
             return std::nullopt;
         }
         target = *target_;
     }
     return target;
 }
References _, add_msg_debug, Creature::add_msg_if_player(), Creature::as_avatar(), Creature::as_npc(), debugmode::DF_NPC, Character::disp_name(), npc_attack_spell::evaluate(), gmf_bypass_cooldown, ground, has_flag(), Creature::is_avatar(), Creature::is_npc(), is_valid_target(), Character::last_target, m_bad, target_handler::mode_spell(), name(), none, Creature::pos(), query_yn(), RANDOM_TARGET, random_valid_target(), range(), Character::sees(), and npc_attack_rating::target().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), and activity_handlers::spellcasting_finish().
set_exp()
void spell::set_exp (int nxp)
Definition at line 1332 of file magic.cpp.
 {
     experience = nxp;
 }
References experience.
Referenced by fake_spell::get_spell(), and known_magic::set_spell_exp().
set_level()
void spell::set_level (const Character & guy, int nlevel)
Definition at line 1020 of file magic.cpp.
 {
     experience = 0;
     gain_levels( guy, nlevel );
 }
References experience, and gain_levels().
Referenced by Character::add_bionic(), known_magic::set_spell_level(), debug_menu::spell_description(), and activity_handlers::spellcasting_finish().
set_message()
void spell::set_message (const translation & msg)
Definition at line 657 of file magic.cpp.
 {
     alt_message = msg;
 }
References alt_message.
Referenced by mon_spellcasting_actor::call().
set_temp_adjustment()
void spell::set_temp_adjustment (const std::string & target_property, float adjustment)
Definition at line 1598 of file magic.cpp.
 {
     if( target_property == "caster_level" ) {
         temp_level_adjustment += adjustment;
     } else if( target_property == "casting_time" ) {
         temp_cast_time_multiplyer += adjustment;
     } else if( target_property == "cost" ) {
         temp_spell_cost_multiplyer += adjustment;
     } else if( target_property == "aoe" ) {
         temp_aoe_multiplyer += adjustment;
     } else if( target_property == "range" ) {
         temp_range_multiplyer += adjustment;
     } else if( target_property == "duration" ) {
         temp_duration_multiplyer += adjustment;
     } else if( target_property == "difficulty" ) {
         temp_difficulty_adjustment += adjustment;
     } else if( target_property == "somatic_difficulty" ) {
         temp_somatic_difficulty_multiplyer += adjustment;
     } else if( target_property == "sound" ) {
         temp_sound_multiplyer += adjustment;
     } else if( target_property == "concentration" ) {
         temp_concentration_difficulty_multiplyer += adjustment;
     } else {
         debugmsg( "ERROR: invalid spellcasting adjustment name: %s", target_property );
     }
 }
References debugmsg, temp_aoe_multiplyer, temp_cast_time_multiplyer, temp_concentration_difficulty_multiplyer, temp_difficulty_adjustment, temp_duration_multiplyer, temp_level_adjustment, temp_range_multiplyer, temp_somatic_difficulty_multiplyer, temp_sound_multiplyer, and temp_spell_cost_multiplyer.
set_temp_level_adjustment()
void spell::set_temp_level_adjustment (int adjustment)
Definition at line 1592 of file magic.cpp.
 {
     temp_level_adjustment = adjustment;
 }
References temp_level_adjustment.
shape()
spell_shape spell::shape () const
Definition at line 1312 of file magic.cpp.
 {
     return type->spell_area;
 }
References spell_type::spell_area, and type.
Referenced by calculate_spell_effect_area(), target_ui::panel_spell_info(), target_ui::set_cursor_pos(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
skill()
skill_id spell::skill () const
Definition at line 672 of file magic.cpp.
 {
     return type->skill;
 }
References spell_type::skill, and type.
Referenced by exp_modifier(), spell_fail(), activity_handlers::study_spell_do_turn(), and learn_spell_actor::use().
sound_volume()
int spell::sound_volume (const Creature & caster) const
Definition at line 1428 of file magic.cpp.
 {
     int loudness = 0;
     if( !has_flag( spell_flag::SILENT ) ) {
         loudness = std::abs( damage( caster ) ) / 3;
         if( has_flag( spell_flag::LOUD ) ) {
             loudness += 1 + damage( caster ) / 3;
         }
     }
     return std::max( loudness * temp_sound_multiplyer, 0.0f );
 }
References abs(), damage(), has_flag(), LOUD, max(), SILENT, and temp_sound_multiplyer.
Referenced by npc_attack_spell::can_use(), and make_sound().
spell_class()
trait_id spell::spell_class () const
Definition at line 667 of file magic.cpp.
 {
     return type->spell_class;
 }
References spell_type::spell_class, and type.
Referenced by cast_spell_effect(), gain_exp(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), and activity_handlers::spellcasting_finish().
spell_fail()
float spell::spell_fail (const Character & guy) const
Definition at line 1220 of file magic.cpp.
 {
     if( has_flag( spell_flag::NO_FAIL ) ) {
         return 0.0f;
     }
     const bool is_psi = has_flag( spell_flag::PSIONIC );
     // formula is based on the following:
     // exponential curve
     // effective skill of 0 or less is 100% failure
     // effective skill of 8 (8 int, 0 spellcraft, 0 spell level, spell difficulty 0) is ~50% failure
     // effective skill of 30 is 0% failure
     const float effective_skill = 2 * ( get_effective_level() - get_difficulty(
                                             guy ) ) + guy.get_int() +
                                   guy.get_skill_level( skill() );
     // skill for psi powers downplays power level and is much more based on level and intelligence
     // and goes up to 40 max--effective skill of 10 is 50% failure, effective skill of 40 is 0%
     // Int 8, Metaphysics 2, level 1, difficulty 1 is effective level 26.5
     // Int 10, Metaphysics 5, level 4, difficulty 5 is effective level 27
     // Int 12, Metaphysics 8, level 7, difficulty 10 is effective level 33.5
     const float two_thirds_power_level = static_cast<float>( get_effective_level() ) /
                                          static_cast<float>
                                          ( 1.5 );
     const float psi_effective_skill = 2 * ( ( guy.get_skill_level( skill() ) * 2 ) - get_difficulty(
             guy ) ) + ( guy.get_int() * 1.5 ) + two_thirds_power_level;
     // add an if statement in here because sufficiently large numbers will definitely overflow because of exponents
     if( ( effective_skill > 30.0f && !is_psi ) || ( psi_effective_skill > 40.0f && is_psi ) ) {
         return 0.0f;
     } else if( ( effective_skill < 0.0f && !is_psi ) || ( psi_effective_skill < 0.0f && is_psi ) ) {
         return 1.0f;
     }
     float fail_chance = std::pow( ( effective_skill - 30.0f ) / 30.0f, 2 );
     float psi_fail_chance = std::pow( ( psi_effective_skill - 40.0f ) / 40.0f, 2 );
     if( !is_psi ) {
         if( has_flag( spell_flag::SOMATIC ) &&
             !guy.has_flag( json_flag_SUBTLE_SPELL ) && temp_somatic_difficulty_multiplyer > 0 ) {
             // the first 20 points of encumbrance combined is ignored
             const int arms_encumb = std::max( 0,
                                               guy.avg_encumb_of_limb_type( body_part_type::type::arm ) - 10 );
             // each encumbrance point beyond the "gray" color counts as half an additional fail %
             fail_chance += ( arms_encumb / 200.0f ) * temp_somatic_difficulty_multiplyer;
         }
         if( has_flag( spell_flag::VERBAL ) &&
             !guy.has_flag( json_flag_SILENT_SPELL ) && temp_sound_multiplyer > 0 ) {
             // a little bit of mouth encumbrance is allowed, but not much
             const int mouth_encumb = std::max( 0,
                                                guy.avg_encumb_of_limb_type( body_part_type::type::mouth ) - 5 );
             fail_chance += ( mouth_encumb / 100.0f ) * temp_sound_multiplyer;
         }
     }
     // concentration spells work better than you'd expect with a higher focus pool
     if( has_flag( spell_flag::CONCENTRATE ) && temp_concentration_difficulty_multiplyer > 0 ) {
         if( guy.get_focus() <= 0 ) {
             return 0.0f;
         }
         float concentration_loss = ( 1.0f - ( guy.get_focus() / 100.0f ) ) *
                                    temp_concentration_difficulty_multiplyer;
         fail_chance /= 1.0f - concentration_loss;
         psi_fail_chance /= 1.0f - concentration_loss;
     }
     return clamp( is_psi ? psi_fail_chance : fail_chance, 0.0f, 1.0f );
 }
References body_part_type::arm, Character::avg_encumb_of_limb_type(), clamp(), CONCENTRATE, get_difficulty(), get_effective_level(), Character::get_focus(), Character::get_int(), Character::get_skill_level(), Character::has_flag(), has_flag(), json_flag_SILENT_SPELL, json_flag_SUBTLE_SPELL, max(), body_part_type::mouth, NO_FAIL, PSIONIC, skill(), SOMATIC, temp_concentration_difficulty_multiplyer, temp_somatic_difficulty_multiplyer, temp_sound_multiplyer, and VERBAL.
Referenced by colorized_fail_percent(), dps(), and activity_handlers::spellcasting_finish().
summon_vehicle_id()
vproto_id spell::summon_vehicle_id () const
Definition at line 1799 of file magic.cpp.
 {
     return vproto_id( type->effect_str );
 }
References spell_type::effect_str, and type.
Referenced by spell_effect::spawn_summoned_vehicle().
target_by_monster_id()
bool spell::target_by_monster_id (const tripoint & p) const
Definition at line 1494 of file magic.cpp.
 {
     if( type->targeted_monster_ids.empty() ) {
         return true;
     }
     bool valid = false;
     if( monster *const target = get_creature_tracker().creature_at<monster>( p ) ) {
         if( type->targeted_monster_ids.find( target->type->id ) != type->targeted_monster_ids.end() ) {
             valid = true;
         }
     }
     return valid;
 }
References get_creature_tracker(), spell_type::targeted_monster_ids, and type.
Referenced by is_valid_target().
target_by_species_id()
bool spell::target_by_species_id (const tripoint & p) const
Definition at line 1508 of file magic.cpp.
 {
     if( type->targeted_species_ids.empty() ) {
         return true;
     }
     bool valid = false;
     if( monster *const target = get_creature_tracker().creature_at<monster>( p ) ) {
         for( const species_id &spid : type->targeted_species_ids ) {
             if( target->type->in_species( spid ) ) {
                 valid = true;
             }
         }
     }
     return valid;
 }
References get_creature_tracker(), spell_type::targeted_species_ids, and type.
Referenced by is_valid_target().
targetable_locations()
std::vector< tripoint > spell::targetable_locations (const Character & source) const
all of the tripoints the spell can be cast at.
if the spell can't be cast through walls, does not return anything behind walls if the spell can't target the ground, can't target unseen locations, etc.
Definition at line 919 of file magic.cpp.
 {
     const tripoint char_pos = source.pos();
     const bool select_ground = is_valid_target( spell_target::ground );
     const bool ignore_walls = has_flag( spell_flag::NO_PROJECTILE );
     map &here = get_map();
     // TODO: put this in a namespace for reuse
     const auto has_obstruction = [&]( const tripoint & at ) {
         for( const tripoint &line_point : line_to( char_pos, at ) ) {
             if( here.impassable( line_point ) ) {
                 return true;
             }
         }
         return false;
     };
     std::vector<tripoint> selectable_targets;
     for( const tripoint &query : here.points_in_radius( char_pos, range( source ) ) ) {
         if( !ignore_walls && has_obstruction( query ) ) {
             // it's blocked somewhere!
             continue;
         }
         if( !select_ground ) {
             if( !source.sees( query ) ) {
                 // can't target a critter you can't see
                 continue;
             }
         }
         if( is_valid_target( source, query ) ) {
             selectable_targets.push_back( query );
         }
     }
     return selectable_targets;
 }
References get_map(), ground, has_flag(), has_obstruction(), map::impassable(), is_valid_target(), line_to(), NO_PROJECTILE, map::points_in_radius(), Creature::pos(), range(), and Character::sees().
Referenced by npc_attack_spell::all_evaluations(), and npc_attack_spell::evaluate().
use_components()
void spell::use_components (Character & guy) const
Definition at line 1112 of file magic.cpp.
 {
     if( type->spell_components.is_empty() ) {
         return;
     }
     const requirement_data &spell_components = type->spell_components.obj();
     // if we're here, we're assuming the Character has the correct components (using can_cast())
     inventory map_inv;
     map_inv.form_from_map( guy.pos(), 0, &guy, true, false );
     for( const std::vector<item_comp> &comp_vec : spell_components.get_components() ) {
         guy.consume_items( guy.select_item_component( comp_vec, 1, map_inv ), 1 );
     }
     for( const std::vector<tool_comp> &tool_vec : spell_components.get_tools() ) {
         guy.consume_tools( guy.select_tool_component( tool_vec, 1, map_inv ), 1 );
     }
 }
References Character::consume_items(), Character::consume_tools(), inventory::form_from_map(), requirement_data::get_components(), requirement_data::get_tools(), string_id< T >::is_empty(), string_id< T >::obj(), Creature::pos(), Character::select_item_component(), Character::select_tool_component(), spell_type::spell_components, and type.
Referenced by activity_handlers::spellcasting_finish().
xp()
int spell::xp () const
Definition at line 1317 of file magic.cpp.
 {
     return experience;
 }
References experience.
Referenced by exp_progress(), exp_to_next_level(), spellcasting_callback::spell_info_text(), and activity_handlers::spellcasting_finish().
Friends And Related Function Documentation
spell_events
friend class spell_events friend
Definition at line 424 of file magic.h.
Member Data Documentation
alt_message
translation spell::alt_message private
Definition at line 447 of file magic.h.
Referenced by message(), and set_message().
experience
int spell::experience = 0 private
Definition at line 429 of file magic.h.
Referenced by gain_exp(), get_level(), set_exp(), set_level(), and xp().
temp_aoe_multiplyer
float spell::temp_aoe_multiplyer = 1 private
Definition at line 437 of file magic.h.
Referenced by aoe(), clear_temp_adjustments(), and set_temp_adjustment().
temp_cast_time_multiplyer
float spell::temp_cast_time_multiplyer = 1 private
Definition at line 435 of file magic.h.
Referenced by casting_time(), clear_temp_adjustments(), and set_temp_adjustment().
temp_concentration_difficulty_multiplyer
float spell::temp_concentration_difficulty_multiplyer = 1 private
Definition at line 443 of file magic.h.
Referenced by clear_temp_adjustments(), enumerate_spell_data(), set_temp_adjustment(), and spell_fail().
temp_difficulty_adjustment
int spell::temp_difficulty_adjustment = 0 private
Definition at line 440 of file magic.h.
Referenced by clear_temp_adjustments(), get_difficulty(), and set_temp_adjustment().
temp_duration_multiplyer
float spell::temp_duration_multiplyer = 1 private
Definition at line 439 of file magic.h.
Referenced by clear_temp_adjustments(), duration(), and set_temp_adjustment().
temp_level_adjustment
int spell::temp_level_adjustment = 0 private
Definition at line 434 of file magic.h.
Referenced by clear_temp_adjustments(), get_effective_level(), get_temp_level_adjustment(), set_temp_adjustment(), and set_temp_level_adjustment().
temp_range_multiplyer
float spell::temp_range_multiplyer = 1 private
Definition at line 438 of file magic.h.
Referenced by clear_temp_adjustments(), range(), and set_temp_adjustment().
temp_somatic_difficulty_multiplyer
float spell::temp_somatic_difficulty_multiplyer = 1 private
Definition at line 441 of file magic.h.
Referenced by casting_time(), casting_time_encumbered(), clear_temp_adjustments(), energy_cost(), enumerate_spell_data(), no_hands(), set_temp_adjustment(), and spell_fail().
temp_sound_multiplyer
float spell::temp_sound_multiplyer = 1 private
Definition at line 442 of file magic.h.
Referenced by clear_temp_adjustments(), enumerate_spell_data(), set_temp_adjustment(), sound_volume(), and spell_fail().
temp_spell_cost_multiplyer
float spell::temp_spell_cost_multiplyer = 1 private
Definition at line 436 of file magic.h.
Referenced by clear_temp_adjustments(), energy_cost(), and set_temp_adjustment().
type
spell_id spell::type private
Definition at line 426 of file magic.h.
Referenced by accuracy(), aoe(), aoe_string(), bp_is_affected(), can_cast(), can_learn(), cast_all_effects(), cast_extra_spell_effects(), cast_spell_effect(), casting_time(), check_if_component_in_hand(), components(), create_field(), damage(), damage_dot(), damage_string(), description(), dmg_type(), dps(), duration(), duration_string(), effect(), effect_area(), effect_data(), energy_cost(), energy_source(), energy_string(), field_intensity(), get_difficulty(), get_max_level(), get_src(), has_components(), has_flag(), id(), ignore_by_species_id(), in_aoe(), is_max_level(), is_spell_class(), is_valid(), is_valid_target(), list_ignored_species_names(), list_targeted_monster_names(), list_targeted_species_names(), make_sound(), message(), min_leveled_accuracy(), min_leveled_aoe(), min_leveled_damage(), min_leveled_dot(), min_leveled_duration(), name(), range(), shape(), skill(), spell_class(), summon_vehicle_id(), target_by_monster_id(), target_by_species_id(), and use_components().
The documentation for this class was generated from the following files:
src/magic.h
src/magic.cpp