Cataclysm DDA: chop_logs_activity_actor Class Reference
chop_logs_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
chop_logs_activity_actor ()=default
chop_logs_activity_actor (int moves, const item_location &tool)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &who) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves
item_location tool
Detailed Description
Definition at line 1809 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
chop_logs_activity_actor() [1/2]
chop_logs_activity_actor::chop_logs_activity_actor () default
chop_logs_activity_actor() [2/2]
chop_logs_activity_actor::chop_logs_activity_actor (int moves, const item_location & tool) inline
Definition at line 1813 of file activity_actor_definitions.h.
 : moves( moves ), tool( tool ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> chop_logs_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1823 of file activity_actor_definitions.h.
{
             return std::make_unique<chop_logs_activity_actor>( *this );
         }
deserialize()
std::unique_ptr< activity_actor > chop_logs_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 6299 of file activity_actor.cpp.
 {
     chop_logs_activity_actor actor( {}, {} );
     JsonObject data = jsin.get_object();
     data.read( "moves", actor.moves );
     data.read( "tool", actor.tool );
     return actor.clone();
 }
References JsonValue::get_object(), and JsonObject::read().
do_turn()
void chop_logs_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 6242 of file activity_actor.cpp.
 {
     chop_single_do_turn( act );
 }
References act, and chop_single_do_turn().
finish()
void chop_logs_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 6247 of file activity_actor.cpp.
 {
     map &here = get_map();
     const tripoint &pos = here.getlocal( act.placement );
     int log_quan;
     int stick_quan;
     int splint_quan;
     if( here.ter( pos ) == ter_t_trunk ) {
         log_quan = rng( 2, 3 );
         stick_quan = rng( 0, 3 );
         splint_quan = 0;
     } else if( here.ter( pos ) == ter_t_stump ) {
         log_quan = rng( 0, 2 );
         stick_quan = 0;
         splint_quan = rng( 5, 15 );
     } else {
         log_quan = 0;
         stick_quan = 0;
         splint_quan = 0;
     }
     for( int i = 0; i != log_quan; ++i ) {
         item obj( itype_log, calendar::turn );
         obj.set_var( "activity_var", who.name );
         here.add_item_or_charges( pos, obj );
     }
     for( int i = 0; i != stick_quan; ++i ) {
         item obj( itype_stick_long, calendar::turn );
         obj.set_var( "activity_var", who.name );
         here.add_item_or_charges( pos, obj );
     }
     for( int i = 0; i != splint_quan; ++i ) {
         item obj( itype_splinter, calendar::turn );
         obj.set_var( "activity_var", who.name );
         here.add_item_or_charges( pos, obj );
     }
     here.ter_set( pos, ter_t_dirt );
     who.add_msg_if_player( m_good, _( "You finish chopping wood." ) );
     act.set_to_null();
     activity_handlers::resume_for_multi_activities( who );
 }
References _, act, map::add_item_or_charges(), Character::add_msg_if_player(), get_map(), map::getlocal(), itype_log, itype_splinter, itype_stick_long, m_good, Character::name, math_opers::pos(), activity_handlers::resume_for_multi_activities(), rng(), item::set_var(), map::ter(), map::ter_set(), ter_t_dirt, ter_t_stump, ter_t_trunk, and calendar::turn.
get_type()
activity_id chop_logs_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1815 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_CHOP_LOGS" );
         }
References activity_id.
serialize()
void chop_logs_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 6289 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves", moves );
     jsout.member( "tool", tool );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), moves, JsonOut::start_object(), and tool.
start()
void chop_logs_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 6236 of file activity_actor.cpp.
 {
     act.moves_total = moves;
     act.moves_left = moves;
 }
References act, and moves.
Member Data Documentation
moves
int chop_logs_activity_actor::moves private
Definition at line 1831 of file activity_actor_definitions.h.
Referenced by serialize(), and start().
tool
item_location chop_logs_activity_actor::tool private
Definition at line 1832 of file activity_actor_definitions.h.
Referenced by serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp