Cataclysm DDA: JsonValue Class Reference
JsonValue Class Reference
#include <flexbuffer_json.h>
Public Member Functions
JsonValue (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath const *parent_path, size_t path_index)
JsonValue (const JsonValue &)=default
JsonValue & operator= (const JsonValue &)=default
JsonValue (JsonValue &&) noexcept=default
JsonValue & operator= (JsonValue &&) noexcept=default
operator std::string () const
operator bool () const
operator int () const
operator unsigned () const
operator int64_t () const
operator uint64_t () const
operator double () const
operator JsonObject () const
operator JsonArray () const
bool test_string () const
bool test_bool () const
bool test_number () const
bool test_int () const
bool test_float () const
bool test_object () const
bool test_array () const
bool test_null () const
std::string get_string () const
bool get_bool () const
int get_int () const
unsigned int get_uint () const
int64_t get_int64 () const
uint64_t get_uint64 () const
double get_float () const
JsonArray get_array () const
JsonObject get_object () const
bool read (bool &b, bool throw_on_error=false) const
bool read (char &c, bool throw_on_error=false) const
bool read (signed char &c, bool throw_on_error=false) const
bool read (unsigned char &c, bool throw_on_error=false) const
bool read (short unsigned int &s, bool throw_on_error=false) const
bool read (short int &s, bool throw_on_error=false) const
bool read (int &i, bool throw_on_error=false) const
bool read (int64_t &i, bool throw_on_error=false) const
bool read (uint64_t &i, bool throw_on_error=false) const
bool read (unsigned int &u, bool throw_on_error=false) const
bool read (float &f, bool throw_on_error=false) const
bool read (double &d, bool throw_on_error=false) const
bool read (std::string &s, bool throw_on_error=false) const
template<typename T >
auto read (string_id< T > &thing, bool throw_on_error=false) const -> bool
template<typename T >
auto read (int_id< T > &thing, bool throw_on_error=false) const -> bool
template<typename T >
auto read (T &v, bool throw_on_error=false) const -> decltype(deserialize(v, *this), true)
Overload that calls a global function deserialize(T&,JsonIn&), if available.
template<typename T >
auto read (T &v, bool throw_on_error=false) const -> decltype(v.deserialize(*this), true)
Overload that calls a member function T::deserialize(JsonIn&), if available.
template<typename T , std::enable_if_t< std::is_enum_v< T >, int > = 0>
bool read (T &val, bool throw_on_error=false) const
template<typename T , typename U >
bool read (std::pair< T, U > &p, bool throw_on_error=false) const
Overload for std::pair.
template<typename T , std::enable_if_t< !std::is_same_v< void, typename T::value_type > > * = nullptr>
auto read (T &v, bool throw_on_error=false) const -> decltype(v.front(), true)
template<typename T , size_t N>
bool read (std::array< T, N > &v, bool throw_on_error=false) const
template<typename T , std::enable_if_t< std::is_same_v< typename T::key_type, typename T::value_type >> * = nullptr>
bool read (T &v, bool throw_on_error=false) const
template<typename T >
bool read (enum_bitset< T > &v, bool throw_on_error=false) const
template<typename T , std::enable_if_t< std::is_same_v< T, item >> * = nullptr>
bool read (cata::colony< T > &v, bool throw_on_error=false) const
template<typename T , std::enable_if_t< !std::is_same_v< T, item > > * = nullptr>
bool read (cata::colony< T > &v, bool throw_on_error=false) const
template<typename T , std::enable_if_t< !std::is_same_v< typename T::key_type, typename T::value_type > > * = nullptr>
bool read (T &m, bool throw_on_error=true) const
void string_error (const std::string &message) const noexcept(false)
void string_error (int offset, const std::string &message) const noexcept(false)
void throw_error (const std::string &message) const noexcept(false)
void throw_error (int offset, const std::string &message) const noexcept(false)
void throw_error_after (const std::string &message) const noexcept(false)
void throw_error (const JsonPath &path, int offset, const std::string &message) const
void throw_error_after (const JsonPath &path, const std::string &message) const
void string_error (const JsonPath &path, int offset, const std::string &message) const
Private Member Functions
bool error_or_false (bool throw_on_error, const std::string &message) const noexcept(false)
Private Member Functions inherited from Json
Json ()=delete
std::string str () const
void throw_error (const JsonPath &path, int offset, const std::string &message) const
void throw_error_after (const JsonPath &path, const std::string &message) const
void string_error (const JsonPath &path, int offset, const std::string &message) const
Json (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json)
~Json () noexcept=default
Json (const Json &)=default
Json & operator= (const Json &)=default
Json (Json &&) noexcept=default
Json & operator= (Json &&) noexcept=default
Private Attributes
JsonPath const * parent_path_
size_t path_index_
Private Attributes inherited from Json
std::shared_ptr< parsed_flexbuffer > root_
flexbuffer json_
Additional Inherited Members
Private Types inherited from Json
using flexbuffer = flexbuffers::Reference
Static Private Member Functions inherited from Json
static const std::string & flexbuffer_type_to_string (flexbuffers::Type t)
static bool globally_report_unvisited_members (bool do_report)
Detailed Description
Definition at line 166 of file flexbuffer_json.h.
Constructor & Destructor Documentation
JsonValue() [1/3]
JsonValue::JsonValue (std::shared_ptr< parsed_flexbuffer > root, flexbuffer json, JsonPath const * parent_path, size_t path_index) inline
Definition at line 169 of file flexbuffer_json.h.
                                                                     : Json(
                            std::move( root ),
                            json ), parent_path_{ parent_path }, path_index_{ path_index } {}
JsonValue() [2/3]
JsonValue::JsonValue (const JsonValue &) default
JsonValue() [3/3]
JsonValue::JsonValue (JsonValue &&) default noexcept
Member Function Documentation
error_or_false()
bool JsonValue::error_or_false (bool throw_on_error, const std::string & message) const inline private noexcept
Definition at line 338 of file flexbuffer_json.h.
{
             if( throw_on_error ) {
                 throw_error( 0, message );
             }
             return false;
         }
References mapgen_defer::message, and Json::throw_error().
Referenced by read().
get_array()
JsonArray JsonValue::get_array () const inline
Definition at line 263 of file flexbuffer_json-inl.h.
 {
     return static_cast<JsonArray>( *this );
 }
Referenced by int_distribution::deserialize(), cata_variant::deserialize(), numeric_interval< T, typename >::deserialize(), damage_instance::deserialize(), overmapbuffer::deserialize_placed_unique_specials(), generic_typed_reader< Derived >::erase_values_from(), item_reader::get_next(), JsonArray::get_tags(), generic_typed_reader< Derived >::insert_values_from(), inventory::json_load_invcache(), safemode::load(), input_manager::load(), clothing_mod::load(), anonymous_namespace{recipe_groups.cpp}::recipe_group_data::load(), npc_template::load(), tool_comp::load(), item_comp::load(), DynamicDataLoader::load_all_from_json(), color_loader< ColorType >::load_colorfile(), item_group::load_item_group(), requirement_data::load_obj_list(), load_place_mapings(), load_place_mapings_alternatively(), load_place_mapings_string(), item_pocket::load_presets(), trait_group::load_trait_group(), load_weighted_list(), read(), and overmap::unserialize_omap().
get_bool()
bool JsonValue::get_bool () const inline
Definition at line 238 of file flexbuffer_json-inl.h.
 {
     return static_cast<bool>( *this );
 }
Referenced by cata_variant::deserialize(), and read().
get_float()
double JsonValue::get_float () const inline
Definition at line 258 of file flexbuffer_json-inl.h.
 {
     return static_cast<double>( *this );
 }
Referenced by get_dbl_or_var_part(), get_duration_or_var_part(), and read().
get_int()
int JsonValue::get_int () const inline
Definition at line 242 of file flexbuffer_json-inl.h.
 {
     return static_cast<int>( *this );
 }
Referenced by int_distribution::deserialize(), time_duration::deserialize(), cata_variant::deserialize(), submap::load(), read(), and game::unserialize_master().
get_int64()
int64_t JsonValue::get_int64 () const inline
Definition at line 250 of file flexbuffer_json-inl.h.
 {
     return static_cast<int64_t>( *this );
 }
Referenced by read().
get_object()
JsonObject JsonValue::get_object () const inline
Definition at line 268 of file flexbuffer_json-inl.h.
 {
     return static_cast<JsonObject>( *this );
 }
Referenced by deserialize(), int_distribution::deserialize(), mission_id::deserialize(), mutable_overmap_join::deserialize(), mutable_overmap_terrain_join::deserialize(), damage_instance::deserialize(), diary::deserialize(), mapgen_value< Id >::deserialize(), overmap_static_spawns::deserialize(), overmap_special_spawns::deserialize(), overmap_special_connection::deserialize(), translation::deserialize(), computer::deserialize(), trait_and_var::deserialize(), data_handling_activity_actor::deserialize(), wear_activity_actor::deserialize(), wield_activity_actor::deserialize(), invoke_item_activity_actor::deserialize(), pickup_menu_activity_actor::deserialize(), aim_activity_actor::deserialize(), gunmod_remove_activity_actor::deserialize(), hacksaw_activity_actor::deserialize(), hacking_activity_actor::deserialize(), bookbinder_copy_activity_actor::deserialize(), hotwire_car_activity_actor::deserialize(), glide_activity_actor::deserialize(), bikerack_racking_activity_actor::deserialize(), bikerack_unracking_activity_actor::deserialize(), read_activity_actor::deserialize(), move_items_activity_actor::deserialize(), pickup_activity_actor::deserialize(), boltcutting_activity_actor::deserialize(), lockpick_activity_actor::deserialize(), ebooksave_activity_actor::deserialize(), open_gate_activity_actor::deserialize(), consume_activity_actor::deserialize(), try_sleep_activity_actor::deserialize(), safecracking_activity_actor::deserialize(), unload_activity_actor::deserialize(), craft_activity_actor::deserialize(), workout_activity_actor::deserialize(), drop_activity_actor::deserialize(), stash_activity_actor::deserialize(), harvest_activity_actor::deserialize(), reload_activity_actor::deserialize(), milk_activity_actor::deserialize(), shearing_activity_actor::deserialize(), disassemble_activity_actor::deserialize(), move_furniture_activity_actor::deserialize(), insert_item_activity_actor::deserialize(), tent_placement_activity_actor::deserialize(), oxytorch_activity_actor::deserialize(), play_with_pet_activity_actor::deserialize(), prying_activity_actor::deserialize(), tent_deconstruct_activity_actor::deserialize(), reel_cable_activity_actor::deserialize(), vehicle_folding_activity_actor::deserialize(), vehicle_unfolding_activity_actor::deserialize(), wash_activity_actor::deserialize(), chop_logs_activity_actor::deserialize(), chop_planks_activity_actor::deserialize(), chop_tree_activity_actor::deserialize(), churn_activity_actor::deserialize(), clear_rubble_activity_actor::deserialize(), disable_activity_actor::deserialize(), firstaid_activity_actor::deserialize(), forage_activity_actor::deserialize(), gunmod_add_activity_actor::deserialize(), longsalvage_activity_actor::deserialize(), mop_activity_actor::deserialize(), unload_loot_activity_actor::deserialize(), get_dbl_or_var_part(), get_duration_or_var_part(), ma_buff_reader::get_next(), text_style_check_reader::get_next(), faction_price_rules_reader::get_next(), shopkeeper_cons_rates_reader::get_next(), icg_entry_reader::get_next(), tech_effect_reader::get_next(), skilllevel_reader::get_next(), addiction_reader::get_next(), get_str_or_var(), get_str_translation_or_var(), get_translation_or_var(), npc::import_and_clean(), json_item_substitution::substitution::info::info(), jmapgen_trap::jmapgen_trap(), past_achievements_info::load(), Character::load(), weakpoint_family::load(), quality_requirement::load(), game::load(), DynamicDataLoader::load_all_from_json(), enchantment::load_inline_enchantment(), effect_on_conditions::load_inline_eoc(), item_group::load_item_group(), worldfactory::load_last_world_info(), load_place_mapings(), trait_group::load_trait_group(), mapgen_value< Id >::mapgen_value(), overmap::unserialize(), game::unserialize(), and overmap::unserialize_view().
get_string()
std::string JsonValue::get_string () const inline
Definition at line 234 of file flexbuffer_json-inl.h.
 {
     return static_cast<std::string>( *this );
 }
Referenced by mission_id::deserialize(), mutable_overmap_join::deserialize(), mapgen_value< Id >::deserialize(), translation::deserialize(), computer::deserialize(), get_duration_or_var_part(), ma_buff_reader::get_next(), enum_flags_reader< E >::get_next(), text_style_check_reader::get_next(), item_reader::get_next(), get_str_or_var(), JsonArray::get_tags(), weakpoint_family::load(), submap::load(), enchantment::load_inline_enchantment(), effect_on_conditions::load_inline_eoc(), item_group::load_item_group(), trait_group::load_trait_group(), mapgen_value< Id >::mapgen_value(), and read().
get_uint()
unsigned int JsonValue::get_uint () const inline
Definition at line 246 of file flexbuffer_json-inl.h.
 {
     return static_cast<unsigned int>( *this );
 }
Referenced by read().
get_uint64()
uint64_t JsonValue::get_uint64 () const inline
Definition at line 254 of file flexbuffer_json-inl.h.
 {
     return static_cast<uint64_t>( *this );
 }
Referenced by read().
operator bool()
JsonValue::operator bool () const inline
Definition at line 159 of file flexbuffer_json-inl.h.
 {
     if( json_.IsBool() ) {
         return json_.AsBool();
     }
     throw_error( "Expected a bool, got " + flexbuffer_type_to_string( json_.GetType() ) );
 }
References cata::throw_error().
operator double()
JsonValue::operator double () const inline
Definition at line 167 of file flexbuffer_json-inl.h.
 {
     if( json_.IsNumeric() ) {
         return json_.AsDouble();
     }
     throw_error( "Expected a double, got " + flexbuffer_type_to_string( json_.GetType() ) );
 }
References cata::throw_error().
operator int()
JsonValue::operator int () const inline
Definition at line 117 of file flexbuffer_json-inl.h.
 {
     if( json_.IsNumeric() ) {
         return static_cast<int>( json_.AsInt64() );
     }
     throw_error( "Expected an int, got " + flexbuffer_type_to_string( json_.GetType() ) );
 }
References cata::throw_error().
operator int64_t()
JsonValue::operator int64_t () const inline
Definition at line 125 of file flexbuffer_json-inl.h.
 {
     if( json_.IsNumeric() ) {
         return static_cast<int64_t>( json_.AsInt64() );
     }
     throw_error( "Expected an int64_t, got " + flexbuffer_type_to_string( json_.GetType() ) );
 }
References cata::throw_error().
operator JsonArray()
JsonValue::operator JsonArray () const inline
Definition at line 188 of file flexbuffer_json-inl.h.
 {
     JsonPath new_path;
     if( parent_path_ ) {
         new_path = *parent_path_ + path_index_;
     }
     if( json_.IsAnyVector() && !json_.IsMap() ) {
         return JsonArray( root_, flexbuffer( json_ ), std::move( new_path ) );
     }
     throw_error( new_path, 0, "Expected an array, got " +
                  flexbuffer_type_to_string( json_.GetType() ) );
 }
References cata::throw_error().
operator JsonObject()
JsonValue::operator JsonObject () const inline
Definition at line 175 of file flexbuffer_json-inl.h.
 {
     JsonPath new_path;
     if( parent_path_ ) {
         new_path = *parent_path_ + path_index_;
     }
     if( json_.IsMap() ) {
         return JsonObject( root_, flexbuffer( json_ ), std::move( new_path ) );
     }
     throw_error( new_path, 0, "Expected an object, got " +
                  flexbuffer_type_to_string( json_.GetType() ) );
 }
References cata::throw_error().
operator std::string()
JsonValue::operator std::string () const inline
Definition at line 109 of file flexbuffer_json-inl.h.
 {
     if( json_.IsString() ) {
         return json_.AsString().str();
     }
     throw_error( "Expected a string, got " + flexbuffer_type_to_string( json_.GetType() ) );
 }
References cata::throw_error().
operator uint64_t()
JsonValue::operator uint64_t () const inline
Definition at line 133 of file flexbuffer_json-inl.h.
 {
     if( json_.IsNumeric() ) {
         // These are always stored as signed ints.
         int64_t signed_value = json_.AsInt64();
         if( signed_value >= 0 ) {
             return static_cast<uint64_t>( signed_value );
         }
         throw_error( "uint64_t value out of range" );
     }
     throw_error( "Expected a uint64_t, got " + flexbuffer_type_to_string( json_.GetType() ) );
 }
References cata::throw_error().
operator unsigned()
JsonValue::operator unsigned () const inline
Definition at line 146 of file flexbuffer_json-inl.h.
 {
     if( json_.IsNumeric() ) {
         // These are always stored as signed ints.
         int64_t signed_value = json_.AsInt64();
         if( signed_value >= 0 ) {
             return static_cast<unsigned int>( signed_value );
         }
         throw_error( "unsigned int value out of range" );
     }
     throw_error( "Expected an uint32_t, got " + flexbuffer_type_to_string( json_.GetType() ) );
 }
References cata::throw_error().
operator=() [1/2]
JsonValue& JsonValue::operator= (const JsonValue &) default
operator=() [2/2]
JsonValue& JsonValue::operator= (JsonValue &&) default noexcept
read() [1/26]
bool JsonValue::read (bool & b, bool throw_on_error = false) const
Definition at line 143 of file flexbuffer_json.cpp.
 {
     if( !test_bool() ) {
         return error_or_false( throw_on_error, "Expected bool" );
     }
     b = get_bool();
     return true;
 }
References b, error_or_false(), get_bool(), and test_bool().
Referenced by migration::content::deserialize(), mapgen_arguments::deserialize(), mutable_overmap_terrain_join::deserialize(), mutable_overmap_phase::deserialize(), contents_change_handler::deserialize(), zone_manager::deserialize(), item_components::deserialize(), trait_and_var::deserialize(), body_part_set::deserialize(), deserialize(), faction_template::faction_template(), get_translation_or_var(), json_item_substitution::substitution::info::info(), Character::load(), mutation_category_trait::load(), delayed_transform_iuse::load(), reveal_map_actor::load(), fireweapon_on_actor::load(), manualnoise_actor::load(), submap::load(), tool_comp::load(), memorial_logger::load(), load_construction(), load_external_option(), zone_manager::load_world_zones(), JsonArray::read(), read(), item::read_extended_photos(), JsonArray::read_next(), and game::unserialize_master().
read() [2/26]
template<typename T , std::enable_if_t< !std::is_same_v< T, item > > * > bool JsonValue::read (cata::colony< T > & v, bool throw_on_error = false) const
Definition at line 489 of file flexbuffer_json-inl.h.
 {
     if( !test_array() ) {
         return error_or_false( throw_on_error, "Expected json array" );
     }
     try {
         v.clear();
         for( JsonValue jv : get_array() ) {
             T element;
             if( jv.test_array() ) {
                 JsonArray rle_element = jv;
                 if( rle_element.size() != 2 ) {
                     rle_element.error_or_false( throw_on_error, "Not enough values for RLE" );
                     continue;
                 }
                 int run_l;
                 if( rle_element[ 0 ].read( element, throw_on_error ) &&
                     rle_element[ 1 ].read( run_l, throw_on_error )
                   ) { // all is good
                     // first insert (run_l-1) elements
                     for( int i = 0; i < run_l - 1; i++ ) {
                         v.insert( element );
                     }
                     // micro-optimization, move last element
                     v.insert( std::move( element ) );
                 } else { // array is malformed, skipping it entirely
                     error_or_false( throw_on_error, "Expected end of array" );
                 }
             } else {
                 if( jv.read( element, throw_on_error ) ) {
                     v.insert( std::move( element ) );
                 }
             }
         }
     } catch( const JsonError & ) {
         if( throw_on_error ) {
             throw;
         }
         return false;
     }
     return true;
 }
References cata::colony< element_type, element_allocator_type, element_skipfield_type >::clear(), error_or_false(), JsonArray::error_or_false(), get_array(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::insert(), read(), JsonArray::size(), and test_array().
read() [3/26]
template<typename T , std::enable_if_t< !std::is_same_v< T, item > > * = nullptr> bool JsonValue::read (cata::colony< T > & v, bool throw_on_error = false) const
read() [4/26]
bool JsonValue::read (char & c, bool throw_on_error = false) const
Definition at line 151 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     c = get_int();
     return true;
 }
References c, error_or_false(), get_int(), and test_number().
read() [5/26]
bool JsonValue::read (double & d, bool throw_on_error = false) const
Definition at line 235 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     d = get_float();
     return true;
 }
References error_or_false(), get_float(), and test_number().
read() [6/26]
template<typename T > bool JsonValue::read (enum_bitset< T > & v, bool throw_on_error = false) const
Definition at line 458 of file flexbuffer_json-inl.h.
 {
     if( !test_array() ) {
         return error_or_false( throw_on_error, "Expected json array" );
     }
     try {
         v = {};
         for( JsonValue jv : get_array() ) {
             T element;
             if( jv.read( element, throw_on_error ) ) {
                 if( v.test( element ) ) {
                     return error_or_false(
                                throw_on_error,
                                "Duplicate entry in set defined by json array" );
                 }
                 v.set( element );
             }
         }
     } catch( const JsonError & ) {
         if( throw_on_error ) {
             throw;
         }
         return false;
     }
     return true;
 }
References error_or_false(), get_array(), enum_bitset< E >::set(), enum_bitset< E >::test(), and test_array().
read() [7/26]
bool JsonValue::read (float & f, bool throw_on_error = false) const
Definition at line 227 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     f = get_float();
     return true;
 }
References error_or_false(), get_float(), and test_number().
read() [8/26]
bool JsonValue::read (int & i, bool throw_on_error = false) const
Definition at line 195 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     i = get_int();
     return true;
 }
References error_or_false(), get_int(), and test_number().
read() [9/26]
bool JsonValue::read (int64_t & i, bool throw_on_error = false) const
Definition at line 203 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     i = get_int64();
     return true;
 }
References error_or_false(), get_int64(), and test_number().
read() [10/26]
template<typename T > auto JsonValue::read (int_id< T > & thing, bool throw_on_error = false) const -> bool
Definition at line 287 of file flexbuffer_json-inl.h.
 {
     std::string tmp;
     if( !read( tmp, throw_on_error ) ) {
         return false;
     }
     thing = int_id<T>( tmp );
     return true;
 }
References read().
read() [11/26]
bool JsonValue::read (short int & s, bool throw_on_error = false) const
Definition at line 186 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     // TODO: test for overflow
     s = get_int();
     return true;
 }
References error_or_false(), get_int(), and test_number().
read() [12/26]
bool JsonValue::read (short unsigned int & s, bool throw_on_error = false) const
Definition at line 177 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     // TODO: test for overflow
     s = get_int();
     return true;
 }
References error_or_false(), get_int(), and test_number().
read() [13/26]
bool JsonValue::read (signed char & c, bool throw_on_error = false) const
Definition at line 159 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     // TODO: test for overflow
     c = get_int();
     return true;
 }
References c, error_or_false(), get_int(), and test_number().
read() [14/26]
template<typename T , size_t N> bool JsonValue::read (std::array< T, N > & v, bool throw_on_error = false) const
Definition at line 399 of file flexbuffer_json-inl.h.
 {
     if( !test_array() ) {
         return error_or_false( throw_on_error, "Expected json array" );
     }
     try {
         JsonArray ja = get_array();
         if( ja.size() != N ) {
             if( ja.size() < N ) {
                 return error_or_false( throw_on_error, "Json array is too short" );
             } else {
                 return error_or_false( throw_on_error, "Json array is too long" );
             }
         }
         size_t i = 0;
         for( JsonValue jv : ja ) {
             if( !jv.read( v[ i ], throw_on_error ) ) {
                 return false; // invalid entry
             }
             ++i;
         }
         return true;
     } catch( const JsonError & ) {
         if( throw_on_error ) {
             throw;
         }
         return false;
     }
 }
References error_or_false(), get_array(), JsonArray::size(), and test_array().
read() [15/26]
template<typename T , typename U > bool JsonValue::read (std::pair< T, U > & p, bool throw_on_error = false) const
Overload for std::pair.
Definition at line 347 of file flexbuffer_json-inl.h.
 {
     if( !test_array() ) {
         return error_or_false( throw_on_error, "Expected json array encoding pair" );
     }
     try {
         JsonArray ja = get_array();
         if( ja.size() != 2 ) {
             return error_or_false( throw_on_error, "Array had wrong number of elements for pair" );
         }
         bool result = ja[ 0 ].read( p.first, throw_on_error ) &&
                       ja[ 1 ].read( p.second, throw_on_error );
         if( !result && throw_on_error ) {
             throw_error( "Array had wrong number of elements for pair" );
         }
         return result;
     } catch( const JsonError & ) {
         if( throw_on_error ) {
             throw;
         }
         return false;
     }
 }
References error_or_false(), get_array(), JsonArray::read(), JsonArray::size(), test_array(), and throw_error().
read() [16/26]
bool JsonValue::read (std::string & s, bool throw_on_error = false) const
Definition at line 243 of file flexbuffer_json.cpp.
 {
     if( !test_string() ) {
         return error_or_false( throw_on_error, "Expected string" );
     }
     s = get_string();
     return true;
 }
References error_or_false(), get_string(), and test_string().
read() [17/26]
template<typename T > auto JsonValue::read (string_id< T > & thing, bool throw_on_error = false) const -> bool
Definition at line 275 of file flexbuffer_json-inl.h.
 {
     std::string tmp;
     if( !read( tmp, throw_on_error ) ) {
         return false;
     }
     thing = string_id<T>( tmp );
     return true;
 }
References read().
read() [18/26]
template<typename T , std::enable_if_t< !std::is_same_v< typename T::key_type, typename T::value_type > > * = nullptr> bool JsonValue::read (T & m, bool throw_on_error = true) const
read() [19/26]
template<typename T , std::enable_if_t< std::is_same_v< typename T::key_type, typename T::value_type >> * = nullptr> bool JsonValue::read (T & v, bool throw_on_error = false) const
read() [20/26]
template<typename T > auto JsonValue::read (T & v, bool throw_on_error = false) const -> decltype(deserialize(v, *this), true)
Overload that calls a global function deserialize(T&,JsonIn&), if available.
Overload that calls a member function T::deserialize(JsonIn&), if available.
Definition at line 299 of file flexbuffer_json-inl.h.
 {
     try {
         deserialize( v, *this );
         return true;
     } catch( const JsonError & ) {
         if( throw_on_error ) {
             throw;
         }
         return false;
     }
 }
References deserialize().
read() [21/26]
template<typename T > auto JsonValue::read (T & v, bool throw_on_error = false) const -> decltype(v.deserialize(*this), true)
Overload that calls a member function T::deserialize(JsonIn&), if available.
read() [22/26]
template<typename T , std::enable_if_t< !std::is_same_v< void, typename T::value_type > > * > auto JsonValue::read (T & v, bool throw_on_error = false) const -> decltype(v.front(), true)
Definition at line 374 of file flexbuffer_json-inl.h.
 {
     if( !test_array() ) {
         return error_or_false( throw_on_error, "Expected json array" );
     }
     try {
         v.clear();
         for( JsonValue jv : get_array() ) {
             typename T::value_type element;
             if( jv.read( element, throw_on_error ) ) {
                 v.push_back( std::move( element ) );
             }
         }
     } catch( const JsonError & ) {
         if( throw_on_error ) {
             throw;
         }
         return false;
     }
     return true;
 }
read() [23/26]
template<typename T , std::enable_if_t< !std::is_same_v< typename T::key_type, typename T::value_type > > * > bool JsonValue::read (T & val, bool throw_on_error = false) const
Definition at line 330 of file flexbuffer_json-inl.h.
 {
     int i;
     if( read( i, false ) ) {
         val = static_cast<T>( i );
         return true;
     }
     std::string s;
     if( read( s, throw_on_error ) ) {
         val = io::string_to_enum<T>( s );
         return true;
     }
     return false;
 }
References read().
read() [24/26]
bool JsonValue::read (uint64_t & i, bool throw_on_error = false) const
Definition at line 211 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     i = get_uint64();
     return true;
 }
References error_or_false(), get_uint64(), and test_number().
read() [25/26]
bool JsonValue::read (unsigned char & c, bool throw_on_error = false) const
Definition at line 168 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     // TODO: test for overflow
     c = get_int();
     return true;
 }
References c, error_or_false(), get_int(), and test_number().
read() [26/26]
bool JsonValue::read (unsigned int & u, bool throw_on_error = false) const
Definition at line 219 of file flexbuffer_json.cpp.
 {
     if( !test_number() ) {
         return error_or_false( throw_on_error, "Expected number" );
     }
     u = get_uint();
     return true;
 }
References error_or_false(), get_uint(), test_number(), and u.
string_error() [1/3]
void Json::string_error
Definition at line 99 of file flexbuffer_json.cpp.
 {
     std::unique_ptr<std::istream> original_json = root_->get_source_stream();
     std::string source_path = [&] {
         if( root_->get_source_path().empty() )
         {
             return std::string{ "<unknown source file>" };
         }
         return root_->get_source_path().u8string();
     }();
     TextJsonIn jsin( *original_json, source_path );
     advance_jsin( &jsin, flexbuffer_root_from_storage( root_->get_storage() ), path );
     jsin.string_error( offset, message );
 }
string_error() [2/3]
void JsonValue::string_error (const std::string & message) const inline noexcept
Definition at line 302 of file flexbuffer_json.h.
{
             string_error( 0, message );
         }
References mapgen_defer::message, and Json::string_error().
Referenced by text_style_check_reader::get_next().
string_error() [3/3]
void JsonValue::string_error (int offset, const std::string & message) const inline noexcept
Definition at line 306 of file flexbuffer_json.h.
{
             JsonPath p;
             if( parent_path_ ) {
                 p = *parent_path_ + path_index_;
             }
             string_error( p, offset, message );
         }
References mapgen_defer::message, and Json::string_error().
test_array()
bool JsonValue::test_array () const inline
Definition at line 225 of file flexbuffer_json-inl.h.
 {
     return json_.IsVector() && !json_.IsMap();
 }
References Json::json_.
Referenced by int_distribution::deserialize(), mm_region::deserialize(), damage_instance::deserialize(), faction_manager::deserialize(), item_components::deserialize(), generic_typed_reader< Derived >::erase_values_from(), generic_typed_reader< Derived >::insert_values_from(), submap::load(), DynamicDataLoader::load_all_from_json(), item_group::load_item_group(), mod_manager::load_mod_info(), load_place_mapings_alternatively(), avatar::load_template(), trait_group::load_trait_group(), and read().
test_bool()
bool JsonValue::test_bool () const inline
Definition at line 205 of file flexbuffer_json-inl.h.
 {
     return json_.IsBool();
 }
References Json::json_.
Referenced by cata_variant::deserialize(), and read().
test_float()
bool JsonValue::test_float () const inline
Definition at line 217 of file flexbuffer_json-inl.h.
 {
     return json_.IsNumeric();
 }
References Json::json_.
Referenced by get_dbl_or_var_part().
test_int()
bool JsonValue::test_int () const inline
Definition at line 213 of file flexbuffer_json-inl.h.
 {
     return json_.IsNumeric();
 }
References Json::json_.
Referenced by int_distribution::deserialize(), cata_variant::deserialize(), get_duration_or_var_part(), and submap::load().
test_null()
bool JsonValue::test_null () const inline
Definition at line 229 of file flexbuffer_json-inl.h.
 {
     return json_.IsNull();
 }
References Json::json_.
Referenced by deserialize(), and mm_region::deserialize().
test_number()
bool JsonValue::test_number () const inline
Definition at line 209 of file flexbuffer_json-inl.h.
 {
     return json_.IsNumeric();
 }
References Json::json_.
Referenced by read().
test_object()
bool JsonValue::test_object () const inline
Definition at line 221 of file flexbuffer_json-inl.h.
 {
     return json_.IsMap();
 }
References Json::json_.
Referenced by int_distribution::deserialize(), mission_id::deserialize(), mutable_overmap_terrain_join::deserialize(), damage_instance::deserialize(), mapgen_value< Id >::deserialize(), translation::deserialize(), faction_manager::deserialize(), job_data::deserialize(), get_dbl_or_var_part(), get_duration_or_var_part(), text_style_check_reader::get_next(), get_str_or_var(), get_str_translation_or_var(), get_translation_or_var(), jmapgen_trap::jmapgen_trap(), DynamicDataLoader::load_all_from_json(), enchantment::load_inline_enchantment(), effect_on_conditions::load_inline_eoc(), item_group::load_item_group(), mod_manager::load_mod_info(), load_place_mapings(), load_place_mapings_string(), and trait_group::load_trait_group().
test_string()
bool JsonValue::test_string () const inline
Definition at line 201 of file flexbuffer_json-inl.h.
 {
     return json_.IsString();
 }
References Json::json_.
Referenced by mission_id::deserialize(), mutable_overmap_join::deserialize(), mutable_overmap_terrain_join::deserialize(), time_duration::deserialize(), translation::deserialize(), computer::deserialize(), trait_and_var::deserialize(), get_duration_or_var_part(), ma_buff_reader::get_next(), item_reader::get_next(), get_str_or_var(), JsonArray::get_tags(), json_item_substitution::substitution::info::info(), weakpoint_family::load(), submap::load(), tool_comp::load(), enchantment::load_inline_enchantment(), effect_on_conditions::load_inline_eoc(), item_group::load_item_group(), load_place_mapings_string(), trait_group::load_trait_group(), mapgen_value< Id >::mapgen_value(), and read().
throw_error() [1/3]
void Json::throw_error
Definition at line 97 of file flexbuffer_json.cpp.
 {
     std::unique_ptr<std::istream> original_json = root_->get_source_stream();
     std::string source_path = [&] {
         if( root_->get_source_path().empty() )
         {
             return std::string{ "<unknown source file>" };
         }
         return root_->get_source_path().u8string();
     }();
     TextJsonIn jsin( *original_json, source_path );
     advance_jsin( &jsin, flexbuffer_root_from_storage( root_->get_storage() ), path );
     jsin.error( offset, message );
 }
Referenced by read().
throw_error() [2/3]
void JsonValue::throw_error (const std::string & message) const inline noexcept
Definition at line 314 of file flexbuffer_json.h.
{
             throw_error( 0, message );
         }
References mapgen_defer::message, and Json::throw_error().
Referenced by int_distribution::deserialize(), mutable_overmap_terrain_join::deserialize(), damage_instance::deserialize(), get_dbl_or_var_part(), get_duration_or_var_part(), JsonObject::get_enum_value(), typed_flag_reader< T >::get_next(), enum_flags_reader< E >::get_next(), get_str_or_var(), get_translation_or_var(), tool_comp::load(), item_comp::load(), DynamicDataLoader::load_all_from_json(), enchantment::load_inline_enchantment(), effect_on_conditions::load_inline_eoc(), item_group::load_item_group(), mod_manager::load_mod_info(), load_place_mapings_string(), trait_group::load_trait_group(), and read_from_json_string().
throw_error() [3/3]
void JsonValue::throw_error (int offset, const std::string & message) const inline noexcept
Definition at line 318 of file flexbuffer_json.h.
{
             JsonPath p;
             if( parent_path_ ) {
                 p = *parent_path_ + path_index_;
             }
             throw_error( p, offset, message );
         }
References mapgen_defer::message, and Json::throw_error().
throw_error_after() [1/2]
void Json::throw_error_after
Definition at line 98 of file flexbuffer_json.cpp.
 {
     std::unique_ptr<std::istream> original_json = root_->get_source_stream();
     std::string source_path = [&] {
         if( root_->get_source_path().empty() )
         {
             return std::string{ "<unknown source file>" };
         }
         return root_->get_source_path().u8string();
     }();
     TextJsonIn jsin( *original_json, source_path );
     advance_jsin( &jsin, flexbuffer_root_from_storage( root_->get_storage() ), path );
     jsin.skip_value();
     jsin.error( message );
 }
throw_error_after() [2/2]
void JsonValue::throw_error_after (const std::string & message) const inline noexcept
Definition at line 326 of file flexbuffer_json.h.
{
             JsonPath p;
             if( parent_path_ ) {
                 p = *parent_path_ + path_index_;
             }
             throw_error_after( p, message );
         }
References mapgen_defer::message, and Json::throw_error_after().
Referenced by translation::deserialize().
Member Data Documentation
parent_path_
JsonPath const* JsonValue::parent_path_ private
Definition at line 334 of file flexbuffer_json.h.
path_index_
size_t JsonValue::path_index_ private
Definition at line 335 of file flexbuffer_json.h.
The documentation for this class was generated from the following files:
src/flexbuffer_json.h
src/flexbuffer_json-inl.h
src/flexbuffer_json.cpp