Cataclysm DDA: cata::event Class Reference
cata::event Class Reference
#include <event.h>
Public Types
using data_type = std::map< std::string, cata_variant >
using fields_type = std::unordered_map< std::string, cata_variant_type >
Public Member Functions
event (event_type type, time_point time, data_type &&data)
event ()
event_type type () const
time_point time () const
cata_variant get_variant (const std::string &key) const
cata_variant get_variant_or_void (const std::string &key) const
template<cata_variant_type Type>
auto get (const std::string &key) const
template<typename T >
auto get (const std::string &key) const
const data_type & data () const
Static Public Member Functions
template<event_type Type, typename... Args>
static event make (Args &&... args)
static event make_dyn (event_type type, std::vector< std::string > &args)
static fields_type get_fields (event_type)
Private Attributes
event_type type_
time_point time_
data_type data_
Detailed Description
Definition at line 923 of file event.h.
Member Typedef Documentation
data_type
using cata::event::data_type = std::map<std::string, cata_variant>
Definition at line 926 of file event.h.
fields_type
using cata::event::fields_type = std::unordered_map<std::string, cata_variant_type>
Definition at line 957 of file event.h.
Constructor & Destructor Documentation
event() [1/2]
cata::event::event (event_type type, time_point time, data_type && data) inline
Definition at line 928 of file event.h.
             : type_( type )
             , time_( time )
             , data_( std::move( data ) )
         {}
event() [2/2]
cata::event::event () inline
Definition at line 933 of file event.h.
 : type_( event_type::num_event_types ) {}
References num_event_types.
Member Function Documentation
data()
const data_type& cata::event::data () const inline
Definition at line 980 of file event.h.
{
             return data_;
         }
References data_.
Referenced by event_multiset::add(), event_transformation_impl::state::event_added(), and eoc_events::notify().
get() [1/2]
template<cata_variant_type Type> auto cata::event::get (const std::string & key) const inline
Definition at line 971 of file event.h.
{
             return get_variant( key ).get<Type>();
         }
References cata_variant::get(), and get_variant().
Referenced by event_statistic_total::state::event_added(), event_statistic_maximum::state::event_added(), event_statistic_minimum::state::event_added(), kill_tracker::notify(), spell_events::notify(), and memorial_logger::notify().
get() [2/2]
template<typename T > auto cata::event::get (const std::string & key) const inline
Definition at line 976 of file event.h.
{
             return get_variant( key ).get<T>();
         }
References cata_variant::get(), and get_variant().
get_fields()
event::fields_type cata::event::get_fields (event_type type) static
Definition at line 242 of file event.cpp.
 {
     return get_fields_helper(
                type, std::make_integer_sequence<int, static_cast<int>( event_type::num_event_types )> {} );
 }
References cata::get_fields_helper(), num_event_types, and type().
Referenced by event_type_event_source::fields(), and effect_type::verify().
get_variant()
cata_variant cata::event::get_variant (const std::string & key) const
Definition at line 248 of file event.cpp.
 {
     auto it = data_.find( key );
     if( it == data_.end() ) {
         cata_fatal( "No such key %s in event of type %s", key,
                     io::enum_to_string( type_ ) );
     }
     return it->second;
 }
References cata_fatal, data_, io::enum_to_string(), and type_.
Referenced by get().
get_variant_or_void()
cata_variant cata::event::get_variant_or_void (const std::string & key) const
Definition at line 258 of file event.cpp.
 {
     auto it = data_.find( key );
     if( it == data_.end() ) {
         return cata_variant();
     }
     return it->second;
 }
References data_.
Referenced by event_statistic_unique_value::state::event_added(), event_statistic_first_value::state::event_added(), event_statistic_last_value::state::event_added(), and eoc_events::notify().
make()
template<event_type Type, typename... Args> static event cata::event::make (Args &&... args) inline static
Definition at line 939 of file event.h.
{
             using Spec = event_detail::event_spec<Type>;
             // Using is_empty mostly just to verify that the type is defined at
             // all, but it so happens that it ought to be empty too.
             static_assert( std::is_empty_v<Spec>,
                            "spec for this event type must be defined and empty" );
             static_assert( sizeof...( Args ) == Spec::fields.size(),
                            "wrong number of arguments for event type" );
             return event_detail::make_event_helper <
                    Type, std::make_index_sequence<sizeof...( Args )>
                    > ()( calendar::turn, std::forward<Args>( args )... );
         }
References om_direction::size, and calendar::turn.
make_dyn()
cata::event cata::event::make_dyn (event_type type, std::vector< std::string > & args) static
Definition at line 161 of file event_bus.cpp.
 {
     constexpr size_t num_types = static_cast<size_t>( event_type::num_event_types );
     return _make_dyn_impl_2( type, std::make_index_sequence<num_types> {} )( args );
 }
References anonymous_namespace{event_bus.cpp}::_make_dyn_impl_2(), num_event_types, num_types, and type().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_trigger_event().
time()
time_point cata::event::time () const inline
Definition at line 963 of file event.h.
{
             return time_;
         }
References time_.
Referenced by event_summary::add(), and event_transformation_impl::state::event_added().
type()
event_type cata::event::type () const inline
Definition at line 960 of file event.h.
{
             return type_;
         }
References type_.
Referenced by event_transformation_impl::state::event_added(), get_fields(), make_dyn(), achievements_tracker::notify(), kill_tracker::notify(), spell_events::notify(), memorial_logger::notify(), stats_tracker::notify(), eoc_events::notify(), and event_bus::send().
Member Data Documentation
data_
data_type cata::event::data_ private
Definition at line 986 of file event.h.
Referenced by data(), get_variant(), and get_variant_or_void().
time_
time_point cata::event::time_ private
Definition at line 985 of file event.h.
Referenced by time().
type_
event_type cata::event::type_ private
Definition at line 984 of file event.h.
Referenced by get_variant(), and type().
The documentation for this class was generated from the following files:
src/event.h
src/event.cpp
src/event_bus.cpp