Cataclysm DDA: drop_activity_actor Class Reference
drop_activity_actor Class Reference
Activity to drop items to the ground or into a vehicle cargo part.
#include <activity_actor_definitions.h>
Public Member Functions
drop_activity_actor ()=default
drop_activity_actor (const std::vector< drop_or_stash_item_info > &items, const tripoint &placement, const bool force_ground)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &act, Character &who) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &act, Character &who) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
std::string get_progress_message (const player_activity &) const override
Used to generate the progress display at the top of the screen.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
std::vector< drop_or_stash_item_info > items
contents_change_handler handler
tripoint placement
bool force_ground = false
bool current_bulk_unload = false
Detailed Description
Activity to drop items to the ground or into a vehicle cargo part.
@items is the list of items to drop @placement is the offset to the current position of the actor (use tripoint_zero for current pos) @force_ground should the items be forced to the ground instead of e.g. a container at the position
Definition at line 1047 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
drop_activity_actor() [1/2]
drop_activity_actor::drop_activity_actor () default
drop_activity_actor() [2/2]
drop_activity_actor::drop_activity_actor (const std::vector< drop_or_stash_item_info > & items, const tripoint & placement, const bool force_ground) inline
Definition at line 1051 of file activity_actor_definitions.h.
             : items( items ), placement( placement ), force_ground( force_ground ) {}
Member Function Documentation
canceled()
void drop_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 4189 of file activity_actor.cpp.
 {
     handler.handle_by( who );
 }
References contents_change_handler::handle_by(), and handler.
clone()
std::unique_ptr<activity_actor> drop_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 1064 of file activity_actor_definitions.h.
{
             return std::make_unique<drop_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > drop_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 4205 of file activity_actor.cpp.
 {
     drop_activity_actor actor;
     JsonObject jsobj = jsin.get_object();
     jsobj.read( "items", actor.items );
     jsobj.read( "unhandled_containers", actor.handler );
     jsobj.read( "placement", actor.placement );
     jsobj.read( "force_ground", actor.force_ground );
     jsobj.read( "current_bulk_unload", actor.current_bulk_unload );
     return actor.clone();
 }
References clone(), current_bulk_unload, force_ground, JsonValue::get_object(), handler, items, placement, and JsonObject::read().
do_turn()
void drop_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 4175 of file activity_actor.cpp.
 {
     const tripoint_bub_ms pos = placement + who.pos_bub();
     put_into_vehicle_or_drop( who, item_drop_reason::deliberate,
                               obtain_activity_items( items, handler, who, current_bulk_unload ),
                               pos, force_ground );
     // Cancel activity if items is empty. Otherwise, we modified in place and we will continue
     // to resolve the drop next turn. This is different from the pickup logic which creates
     // a brand new activity every turn and cancels the old activity
     if( items.empty() ) {
         who.cancel_activity();
     }
 }
References Character::cancel_activity(), current_bulk_unload, deliberate, force_ground, handler, items, obtain_activity_items(), placement, math_opers::pos(), Creature::pos_bub(), and put_into_vehicle_or_drop().
finish()
void drop_activity_actor::finish (player_activity & act, Character & who) inline override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1061 of file activity_actor_definitions.h.
 {}
get_progress_message()
std::string drop_activity_actor::get_progress_message (const player_activity & act) const inline override virtual
Used to generate the progress display at the top of the screen.
Reimplemented from activity_actor.
Definition at line 1068 of file activity_actor_definitions.h.
{
             return std::string();
         }
get_type()
activity_id drop_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 1055 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_DROP" );
         }
References activity_id.
serialize()
void drop_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 4194 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "items", items );
     jsout.member( "unhandled_containers", handler );
     jsout.member( "placement", placement );
     jsout.member( "force_ground", force_ground );
     jsout.member( "current_bulk_unload", current_bulk_unload );
     jsout.end_object();
 }
References current_bulk_unload, JsonOut::end_object(), force_ground, handler, items, JsonOut::member(), placement, and JsonOut::start_object().
start()
void drop_activity_actor::start (player_activity & act, Character & who) inline override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 1059 of file activity_actor_definitions.h.
 {}
Member Data Documentation
current_bulk_unload
bool drop_activity_actor::current_bulk_unload = false private
Definition at line 1080 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
force_ground
bool drop_activity_actor::force_ground = false private
Definition at line 1079 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
handler
contents_change_handler drop_activity_actor::handler private
Definition at line 1077 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), do_turn(), and serialize().
items
std::vector<drop_or_stash_item_info> drop_activity_actor::items private
Definition at line 1076 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
placement
tripoint drop_activity_actor::placement private
Definition at line 1078 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp