Cataclysm DDA: save_t Class Reference
save_t Class Reference
#include <worldfactory.h>
Public Member Functions
std::string decoded_name () const
std::string base_path () const
bool operator== (const save_t &rhs) const
bool operator!= (const save_t &rhs) const
save_t (const save_t &)=default
save_t & operator= (const save_t &)=default
Static Public Member Functions
static save_t from_save_id (const std::string &save_id)
static save_t from_base_path (const std::string &base_path)
Private Member Functions
save_t (const std::string &name)
Private Attributes
std::string name
Detailed Description
Definition at line 28 of file worldfactory.h.
Constructor & Destructor Documentation
save_t() [1/2]
save_t::save_t (const std::string & name) explicit private
Definition at line 44 of file worldfactory.cpp.
 : name( name ) {}
Referenced by from_base_path(), and from_save_id().
save_t() [2/2]
save_t::save_t (const save_t &) default
Member Function Documentation
base_path()
std::string save_t::base_path () const
Definition at line 51 of file worldfactory.cpp.
 {
     return base64_encode( name );
 }
References base64_encode(), and name.
Referenced by from_base_path(), and get_playtime_from_save().
decoded_name()
std::string save_t::decoded_name () const
Definition at line 46 of file worldfactory.cpp.
 {
     return name;
 }
References name.
Referenced by game::list_active_saves(), and main_menu::load_game().
from_base_path()
save_t save_t::from_base_path (const std::string & base_path) static
Definition at line 61 of file worldfactory.cpp.
 {
     return save_t( base64_decode( base_path ) );
 }
References base64_decode(), base_path(), and save_t().
Referenced by worldfactory::init().
from_save_id()
save_t save_t::from_save_id (const std::string & save_id) static
Definition at line 56 of file worldfactory.cpp.
 {
     return save_t( save_id );
 }
References save_t().
Referenced by avatar::create(), main_menu::opening_screen(), game::quickload(), and game::save().
operator!=()
bool save_t::operator!= (const save_t & rhs) const inline
Definition at line 45 of file worldfactory.h.
{
             return !operator==( rhs );
         }
References operator==().
operator=()
save_t& save_t::operator= (const save_t &) default
operator==()
bool save_t::operator== (const save_t & rhs) const inline
Definition at line 42 of file worldfactory.h.
{
             return name == rhs.name;
         }
References name.
Referenced by operator!=().
Member Data Documentation
name
std::string save_t::name private
Definition at line 31 of file worldfactory.h.
Referenced by base_path(), decoded_name(), and operator==().
The documentation for this class was generated from the following files:
src/worldfactory.h
src/worldfactory.cpp