Cataclysm DDA: gun_type_type Class Reference
gun_type_type Class Reference
The type of gun. The second "_type" suffix is only to distinguish it from item::gun_type.
#include <itype.h>
Public Member Functions
gun_type_type (const std::string &name)
std::string name () const
Translated name.
Private Attributes
std::string name_
Friends
struct std::hash< gun_type_type >
bool operator== (const gun_type_type &l, const gun_type_type &r)
Detailed Description
The type of gun. The second "_type" suffix is only to distinguish it from item::gun_type.
Definition at line 799 of file itype.h.
Constructor & Destructor Documentation
gun_type_type()
gun_type_type::gun_type_type (const std::string & name) inline explicit
Parameters
name The untranslated name of the gun type. Must have been extracted for translation with the context "gun_type_type".
Definition at line 807 of file itype.h.
 : name_( name ) {}
Member Function Documentation
name()
std::string gun_type_type::name () const
Translated name.
Definition at line 228 of file itype.cpp.
 {
     const itype_id gun_type_as_id( name_ );
     return gun_type_as_id.is_valid()
            ? gun_type_as_id->nname( 1 )
            : pgettext( "gun_type_type", name_.c_str() );
 }
References string_id< T >::is_valid(), itype::nname(), and pgettext.
Referenced by item::gunmod_info().
Friends And Related Function Documentation
operator==
bool operator== (const gun_type_type & l, const gun_type_type & r) friend
Definition at line 811 of file itype.h.
{
             return l.name_ == r.name_;
         }
std::hash< gun_type_type >
friend struct std::hash< gun_type_type > friend
Definition at line 811 of file itype.h.
Member Data Documentation
name_
std::string gun_type_type::name_ private
Definition at line 802 of file itype.h.
The documentation for this class was generated from the following files:
src/itype.h
src/itype.cpp