Cataclysm DDA: gunmod_remove_activity_actor Class Reference
gunmod_remove_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
gunmod_remove_activity_actor (int moves_total, const item_location &gun, int gunmod_idx)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
void start (player_activity &act, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &act, Character &who) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &jsout) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
virtual void canceled (player_activity &, Character &)
Called just before Character::cancel_activity() executes.
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static bool gunmod_unload (Character &who, item &gunmod)
static void gunmod_remove (Character &who, item &gun, item &mod)
static std::unique_ptr< activity_actor > deserialize (JsonValue &jsin)
Private Attributes
int moves_total
item_location gun
int gunmod_idx
Detailed Description
Definition at line 144 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
gunmod_remove_activity_actor()
gunmod_remove_activity_actor::gunmod_remove_activity_actor (int moves_total, const item_location & gun, int gunmod_idx) inline
Definition at line 152 of file activity_actor_definitions.h.
           : moves_total( moves_total ), gun( gun ), gunmod_idx( gunmod_idx ) {}
Member Function Documentation
clone()
std::unique_ptr<activity_actor> gunmod_remove_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 166 of file activity_actor_definitions.h.
{
             return std::make_unique<gunmod_remove_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > gunmod_remove_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 717 of file activity_actor.cpp.
 {
     gunmod_remove_activity_actor actor( 0, item_location(), -1 );
     JsonObject data = jsin.get_object();
     data.read( "moves_total", actor.moves_total );
     data.read( "gun", actor.gun );
     data.read( "gunmod", actor.gunmod_idx );
     return actor.clone();
 }
References clone(), JsonValue::get_object(), gun, gunmod_idx, moves_total, and JsonObject::read().
do_turn()
void gunmod_remove_activity_actor::do_turn (player_activity & act, Character & who) inline override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 163 of file activity_actor_definitions.h.
 {}
finish()
void gunmod_remove_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 651 of file activity_actor.cpp.
 {
     item *it_gun = gun.get_item();
     if( !it_gun ) {
         debugmsg( "ACT_GUNMOD_REMOVE lost target gun" );
         act.set_to_null();
         return;
     }
     item *it_mod = nullptr;
     std::vector<item *> mods = it_gun->gunmods();
     if( gunmod_idx >= 0 && mods.size() > static_cast<size_t>( gunmod_idx ) ) {
         it_mod = mods[gunmod_idx];
     } else {
         debugmsg( "ACT_GUNMOD_REMOVE lost target gunmod" );
         act.set_to_null();
         return;
     }
     act.set_to_null();
     gunmod_remove( who, *it_gun, *it_mod );
     it_gun->on_contents_changed();
 }
References act, debugmsg, item_location::get_item(), gun, gunmod_idx, gunmod_remove(), item::gunmods(), anonymous_namespace{item_tname.cpp}::mods(), and item::on_contents_changed().
get_type()
activity_id gunmod_remove_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 158 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_GUNMOD_REMOVE" );
         }
References activity_id.
gunmod_remove()
void gunmod_remove_activity_actor::gunmod_remove (Character & who, item & gun, item & mod) static
Definition at line 689 of file activity_actor.cpp.
 {
     if( !gunmod_unload( who, mod ) ) {
         return;
     }
     gun.gun_set_mode( gun_mode_DEFAULT );
     const itype *modtype = mod.type;
     who.i_add_or_drop( mod );
     gun.remove_item( mod );
     //~ %1$s - gunmod, %2$s - gun.
     who.add_msg_if_player( _( "You remove your %1$s from your %2$s." ), modtype->nname( 1 ),
                            gun.tname() );
 }
References _, Character::add_msg_if_player(), gun, gun_mode_DEFAULT, gunmod_unload(), Character::i_add_or_drop(), itype::nname(), and item_location::remove_item().
Referenced by finish().
gunmod_unload()
bool gunmod_remove_activity_actor::gunmod_unload (Character & who, item & gunmod) static
Definition at line 673 of file activity_actor.cpp.
 {
     if( gunmod.has_flag( flag_BRASS_CATCHER ) ) {
         // Exclude brass catchers so that removing them wouldn't spill the casings
         return true;
     }
     // TODO: unloading gunmods happens instantaneously in some cases, but should take time
     // Also note, gunmod_unload is called twice, once in
     // gunmod_remove_activity_actor::gunmod_remove
     // and once in
     // Character::gunmod_remove
     // Remove one of them before making gunmod_unload take time
     item_location loc = item_location( who, &gunmod );
     return !( gunmod.ammo_remaining() && !who.unload( loc, true ) );
 }
References item::ammo_remaining(), flag_BRASS_CATCHER, item::has_flag(), and Character::unload().
Referenced by gunmod_remove(), and Character::gunmod_remove().
serialize()
void gunmod_remove_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 706 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "moves_total", moves_total );
     jsout.member( "gun", gun );
     jsout.member( "gunmod", gunmod_idx );
     jsout.end_object();
 }
References JsonOut::end_object(), gun, gunmod_idx, JsonOut::member(), moves_total, and JsonOut::start_object().
start()
void gunmod_remove_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 645 of file activity_actor.cpp.
 {
     act.moves_total = moves_total;
     act.moves_left = moves_total;
 }
References act, and moves_total.
Member Data Documentation
gun
item_location gunmod_remove_activity_actor::gun private
Definition at line 148 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), gunmod_remove(), and serialize().
gunmod_idx
int gunmod_remove_activity_actor::gunmod_idx private
Definition at line 149 of file activity_actor_definitions.h.
Referenced by deserialize(), finish(), and serialize().
moves_total
int gunmod_remove_activity_actor::moves_total private
Definition at line 147 of file activity_actor_definitions.h.
Referenced by deserialize(), serialize(), and start().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp