Cataclysm DDA: turret_data Class Reference
turret_data Class Reference
#include <vehicle.h>
Public Types
enum class status : int { invalid , no_ammo , no_power , ready }
Public Member Functions
turret_data ()=default
turret_data (const turret_data &)=delete
turret_data & operator= (const turret_data &)=delete
turret_data (turret_data &&)=default
turret_data & operator= (turret_data &&)=default
operator bool () const
Is this a valid instance?
std::string name () const
item_location base ()
Get base item location.
item_location base () const
bool uses_vehicle_tanks_or_batteries () const
int ammo_remaining () const
Quantity of ammunition available for use.
int ammo_capacity (const ammotype &ammo) const
Maximum quantity of ammunition turret can itself contain.
const itype * ammo_data () const
Specific ammo data or returns nullptr if no ammo available.
itype_id ammo_current () const
Specific ammo type or returns "null" if no ammo available.
std::set< itype_id > ammo_options () const
What ammo is available for this turret (may be multiple if uses tanks)
bool ammo_select (const itype_id &ammo)
Attempts selecting ammo type and returns true if selection was valid.
std::set< std::string > ammo_effects () const
Effects inclusive of any from ammo loaded from tanks.
int range () const
Maximum range considering current ammo (if any)
bool in_range (const tripoint &target) const
Check if target is in range of this turret (considers current ammo) Assumes this turret's status is 'ready'.
void prepare_fire (Character &you)
Prepare the turret for firing, called by firing function.
void post_fire (Character &you, int shots)
Reset state after firing a prepared turret, called by the firing function.
int fire (Character &c, const tripoint &target)
Fire the turret's gun at a given target.
bool can_reload () const
bool can_unload () const
status query () const
Protected Attributes
vehicle * veh = nullptr
vehicle_part * part = nullptr
Private Member Functions
turret_data (vehicle *veh, vehicle_part *part)
Private Attributes
friend vehicle
double cached_recoil = 0
Detailed Description
Definition at line 583 of file vehicle.h.
Member Enumeration Documentation
status
enum turret_data::status : int strong
Enumerator
invalid
no_ammo
no_power
ready
Definition at line 664 of file vehicle.h.
                           : int {
             invalid,
             no_ammo,
             no_power,
             ready
         };
Constructor & Destructor Documentation
turret_data() [1/4]
turret_data::turret_data () default
turret_data() [2/4]
turret_data::turret_data (const turret_data &) delete
turret_data() [3/4]
turret_data::turret_data (turret_data &&) default
turret_data() [4/4]
turret_data::turret_data (vehicle * veh, vehicle_part * part) inline private
Definition at line 674 of file vehicle.h.
             : veh( veh ), part( part ) {}
Member Function Documentation
ammo_capacity()
int turret_data::ammo_capacity (const ammotype & ammo) const
Maximum quantity of ammunition turret can itself contain.
Definition at line 107 of file turret.cpp.
 {
     if( !veh || !part || uses_vehicle_tanks_or_batteries() ) {
         return 0;
     }
     return part->base.ammo_capacity( ammo );
 }
References item::ammo_capacity(), vehicle_part::base, part, uses_vehicle_tanks_or_batteries(), and veh.
ammo_current()
itype_id turret_data::ammo_current () const
Specific ammo type or returns "null" if no ammo available.
Definition at line 126 of file turret.cpp.
 {
     auto opts = ammo_options();
     if( opts.count( part->ammo_pref ) ) {
         return part->ammo_pref;
     }
     if( opts.count( part->info().default_ammo ) ) {
         return part->info().default_ammo;
     }
     if( opts.count( part->base.ammo_default() ) ) {
         return part->base.ammo_default();
     }
     return opts.empty() ? itype_id::NULL_ID() : *opts.begin();
 }
References item::ammo_default(), ammo_options(), vehicle_part::ammo_pref, vehicle_part::base, vpart_info::default_ammo, vehicle_part::info(), string_id< itype >::NULL_ID(), and part.
Referenced by target_ui::action_switch_ammo(), target_ui::action_switch_mode(), ammo_data(), ammo_remaining(), post_fire(), prepare_fire(), and query().
ammo_data()
const itype * turret_data::ammo_data () const
Specific ammo data or returns nullptr if no ammo available.
Definition at line 115 of file turret.cpp.
 {
     if( !veh || !part ) {
         return nullptr;
     }
     if( uses_vehicle_tanks_or_batteries() ) {
         return !ammo_current().is_null() ? item::find_type( ammo_current() ) : nullptr;
     }
     return part->base.ammo_data();
 }
References ammo_current(), item::ammo_data(), vehicle_part::base, item::find_type(), string_id< T >::is_null(), part, uses_vehicle_tanks_or_batteries(), and veh.
Referenced by ammo_effects(), target_handler::mode_turret_manual(), and range().
ammo_effects()
std::set< std::string > turret_data::ammo_effects () const
Effects inclusive of any from ammo loaded from tanks.
Definition at line 178 of file turret.cpp.
 {
     if( !veh || !part ) {
         return std::set<std::string>();
     }
     auto res = part->base.ammo_effects();
     if( uses_vehicle_tanks_or_batteries() && ammo_data() ) {
         res.insert( ammo_data()->ammo->ammo_effects.begin(), ammo_data()->ammo->ammo_effects.end() );
     }
     return res;
 }
References ammo_data(), item::ammo_effects(), vehicle_part::base, part, uses_vehicle_tanks_or_batteries(), and veh.
ammo_options()
std::set< itype_id > turret_data::ammo_options () const
What ammo is available for this turret (may be multiple if uses tanks)
Definition at line 141 of file turret.cpp.
 {
     std::set<itype_id> opts;
     if( !veh || !part ) {
         return opts;
     }
     if( !uses_vehicle_tanks_or_batteries() ) {
         if( !part->base.ammo_current().is_null() ) {
             opts.insert( part->base.ammo_current() );
         }
     } else {
         for( const auto &e : veh->fuels_left() ) {
             const itype *fuel = item::find_type( e.first );
             if( fuel->ammo && part->base.ammo_types().count( fuel->ammo->type ) &&
                 e.second >= part->base.ammo_required() ) {
                 opts.insert( fuel->get_id() );
             }
         }
     }
     return opts;
 }
References itype::ammo, item::ammo_current(), item::ammo_required(), item::ammo_types(), vehicle_part::base, item::find_type(), vehicle::fuels_left(), itype::get_id(), string_id< T >::is_null(), part, uses_vehicle_tanks_or_batteries(), and veh.
Referenced by target_ui::action_switch_ammo(), ammo_current(), and ammo_select().
ammo_remaining()
int turret_data::ammo_remaining () const
Quantity of ammunition available for use.
Definition at line 96 of file turret.cpp.
 {
     if( !veh || !part ) {
         return 0;
     }
     if( uses_vehicle_tanks_or_batteries() ) {
         return veh->fuel_left( ammo_current() );
     }
     return part->base.ammo_remaining();
 }
References ammo_current(), item::ammo_remaining(), vehicle_part::base, vehicle::fuel_left(), part, uses_vehicle_tanks_or_batteries(), and veh.
ammo_select()
bool turret_data::ammo_select (const itype_id & ammo)
Attempts selecting ammo type and returns true if selection was valid.
Definition at line 168 of file turret.cpp.
 {
     if( !ammo_options().count( ammo ) ) {
         return false;
     }
     part->ammo_pref = ammo;
     return true;
 }
References ammo_options(), vehicle_part::ammo_pref, and part.
Referenced by target_ui::action_switch_ammo().
base() [1/2]
item_location turret_data::base ()
Get base item location.
Definition at line 79 of file turret.cpp.
 {
     return item_location( vehicle_cursor( *veh, veh->index_of_part( part ) ), &part->base );
 }
References vehicle_part::base, vehicle::index_of_part(), part, and veh.
Referenced by vehicle::build_interact_menu(), fire(), avatar_action::fire_turret_manual(), vehicle::idle(), target_handler::mode_turret_manual(), post_fire(), and prepare_fire().
base() [2/2]
item_location turret_data::base () const
Definition at line 84 of file turret.cpp.
 {
     return item_location( vehicle_cursor( *veh, veh->index_of_part( part ) ), &part->base );
 }
References vehicle_part::base, vehicle::index_of_part(), part, and veh.
can_reload()
bool turret_data::can_reload () const
Definition at line 212 of file turret.cpp.
 {
     if( !veh || !part || uses_vehicle_tanks_or_batteries() ) {
         return false;
     }
     if( !part->base.magazine_integral() ) {
         // always allow changing of magazines
         return true;
     }
     if( part->base.ammo_remaining() == 0 ) {
         return true;
     }
     return part->base.ammo_remaining() <
            part->base.ammo_capacity( part->base.ammo_data()->ammo->type );
 }
References itype::ammo, item::ammo_capacity(), item::ammo_data(), item::ammo_remaining(), vehicle_part::base, item::magazine_integral(), part, uses_vehicle_tanks_or_batteries(), and veh.
Referenced by vehicle::build_interact_menu().
can_unload()
bool turret_data::can_unload () const
Definition at line 228 of file turret.cpp.
 {
     if( !veh || !part || uses_vehicle_tanks_or_batteries() ) {
         return false;
     }
     return part->base.ammo_remaining() || part->base.magazine_current();
 }
References item::ammo_remaining(), vehicle_part::base, item::magazine_current(), part, uses_vehicle_tanks_or_batteries(), and veh.
Referenced by vehicle::build_interact_menu().
fire()
int turret_data::fire (Character & c, const tripoint & target)
Fire the turret's gun at a given target.
Parameters
p the player firing the turret, passed to pre_fire and post_fire calls.
target coordinates that will be fired on.
Returns
the number of shots actually fired (may be zero).
Definition at line 311 of file turret.cpp.
 {
     if( !veh || !part ) {
         return 0;
     }
     int shots = 0;
     gun_mode mode = base()->gun_current_mode();
     prepare_fire( c );
     shots = c.fire_gun( target, mode.qty, *mode );
     post_fire( c, shots );
     return shots;
 }
References base(), c, item::gun_current_mode(), part, post_fire(), prepare_fire(), gun_mode::qty, and veh.
Referenced by avatar_action::fire_turret_manual(), and vehicle::turrets_aim_and_fire().
in_range()
bool turret_data::in_range (const tripoint & target) const
Check if target is in range of this turret (considers current ammo) Assumes this turret's status is 'ready'.
Definition at line 202 of file turret.cpp.
 {
     if( !veh || !part ) {
         return false;
     }
     int range = veh->turret_query( *part ).range();
     int dist = rl_dist( veh->global_part_pos3( *part ), target );
     return range >= dist;
 }
References vehicle::global_part_pos3(), part, range(), rl_dist(), vehicle::turret_query(), and veh.
Referenced by vehicle::turrets_aim(), and target_ui::update_turrets_in_range().
name()
std::string turret_data::name () const
Definition at line 74 of file turret.cpp.
 {
     return part->name();
 }
References vehicle_part::name(), and part.
Referenced by vehicle::build_interact_menu(), and avatar_action::fire_turret_manual().
operator bool()
turret_data::operator bool () const inline explicit
Is this a valid instance?
Definition at line 595 of file vehicle.h.
{
             return veh && part;
         }
References part, and veh.
operator=() [1/2]
turret_data& turret_data::operator= (const turret_data &) delete
operator=() [2/2]
turret_data& turret_data::operator= (turret_data &&) default
post_fire()
void turret_data::post_fire (Character & you, int shots)
Reset state after firing a prepared turret, called by the firing function.
Parameters
p the player that just fired (or attempted to fire) the turret.
shots the number of shots fired by the most recent call to turret::fire.
Definition at line 280 of file turret.cpp.
 {
     // remove any temporary recoil adjustments
     you.remove_effect( effect_on_roof );
     you.recoil = cached_recoil;
     gun_mode mode = base()->gun_current_mode();
     // Clears item's MAGAZINE_WELL pockets, this gets rid of e.g. flamethrower's
     // "pressurized tanks", or chemoelectric cartridges etc that are left over after firing.
     static const auto clear_mag_wells = []( item & it ) {
         std::vector<item_pocket *> magazine_wells = it.get_contents().get_pockets(
         []( const item_pocket & pocket ) {
             return pocket.is_type( pocket_type::MAGAZINE_WELL );
         } );
         for( item_pocket *pocket : magazine_wells ) {
             pocket->clear_items();
         }
     };
     // handle draining of vehicle tanks or batteries, if applicable
     if( uses_vehicle_tanks_or_batteries() ) {
         veh->drain( ammo_current(), mode->ammo_required() * shots );
         mode->ammo_unset();
         clear_mag_wells( *base() );
     }
     veh->drain( fuel_type_battery, units::to_kilojoule( mode->get_gun_energy_drain() * shots ) );
 }
References ammo_current(), item::ammo_required(), item::ammo_unset(), base(), cached_recoil, item_pocket::clear_items(), vehicle::drain(), effect_on_roof, fuel_type_battery, item::get_gun_energy_drain(), item::gun_current_mode(), item_pocket::is_type(), MAGAZINE_WELL, Character::recoil, Creature::remove_effect(), units::to_kilojoule(), uses_vehicle_tanks_or_batteries(), and veh.
Referenced by fire().
prepare_fire()
void turret_data::prepare_fire (Character & you)
Prepare the turret for firing, called by firing function.
This sets up vehicle tanks, recoil adjustments, vehicle rooftop status, and performs any other actions that must be done before firing a turret.
Parameters
p the player that is firing the gun, subject to recoil adjustment.
Definition at line 262 of file turret.cpp.
 {
     // prevent turrets from shooting their own vehicles
     you.add_effect( effect_on_roof, 1_turns );
     // turrets are subject only to recoil_vehicle()
     cached_recoil = you.recoil;
     you.recoil = 0;
     // set fuel tank fluid as ammo, if appropriate
     if( uses_vehicle_tanks_or_batteries() ) {
         gun_mode mode = base()->gun_current_mode();
         int qty  = mode->ammo_required();
         int fuel_left = veh->fuel_left( ammo_current() );
         mode->ammo_set( ammo_current(), std::min( qty * mode.qty, fuel_left ) );
     }
 }
References Creature::add_effect(), ammo_current(), item::ammo_required(), item::ammo_set(), base(), cached_recoil, effect_on_roof, vehicle::fuel_left(), item::gun_current_mode(), min(), gun_mode::qty, Character::recoil, uses_vehicle_tanks_or_batteries(), and veh.
Referenced by fire().
query()
turret_data::status turret_data::query () const
Definition at line 236 of file turret.cpp.
 {
     if( !veh || !part ) {
         return status::invalid;
     }
     const item &gun = part->base;
     if( uses_vehicle_tanks_or_batteries() ) {
         if( veh->fuel_left( ammo_current() ) < gun.ammo_required() ) {
             return status::no_ammo;
         }
     } else {
         if( gun.ammo_required() && gun.ammo_remaining() < gun.ammo_required() ) {
             return status::no_ammo;
         }
     }
     const units::energy energy_drain = gun.get_gun_energy_drain() * gun.gun_current_mode().qty;
     if( energy_drain > units::from_kilojoule( veh->fuel_left( fuel_type_battery ) ) ) {
         return status::no_power;
     }
     return status::ready;
 }
References ammo_current(), vehicle_part::base, units::from_kilojoule(), vehicle::fuel_left(), fuel_type_battery, gun, invalid, no_ammo, no_power, part, ready, uses_vehicle_tanks_or_batteries(), and veh.
Referenced by vehicle::find_all_ready_turrets(), avatar_action::fire_turret_manual(), vehicle::turrets_aim_and_fire_single(), and target_ui::update_status().
range()
int turret_data::range () const
Maximum range considering current ammo (if any)
Definition at line 190 of file turret.cpp.
 {
     if( !veh || !part ) {
         return 0;
     }
     int res = part->base.gun_range();
     if( uses_vehicle_tanks_or_batteries() && ammo_data() ) {
         res += ammo_data()->ammo->range;
     }
     return res;
 }
References itype::ammo, ammo_data(), vehicle_part::base, item::gun_range(), part, uses_vehicle_tanks_or_batteries(), and veh.
Referenced by target_ui::action_switch_ammo(), target_ui::action_switch_mode(), in_range(), target_handler::mode_turret_manual(), and target_handler::mode_turrets().
uses_vehicle_tanks_or_batteries()
bool turret_data::uses_vehicle_tanks_or_batteries () const
Returns
true if turret is using vehicle tanks or batteries
Definition at line 89 of file turret.cpp.
 {
     const vpart_info &vpi = part->info();
     return vpi.has_flag( "USE_TANKS" ) ||
            vpi.has_flag( "USE_BATTERIES" );
 }
References vpart_info::has_flag(), vehicle_part::info(), and part.
Referenced by ammo_capacity(), ammo_data(), ammo_effects(), ammo_options(), ammo_remaining(), can_reload(), can_unload(), post_fire(), prepare_fire(), query(), and range().
Member Data Documentation
cached_recoil
double turret_data::cached_recoil = 0 private
Definition at line 676 of file vehicle.h.
Referenced by post_fire(), and prepare_fire().
part
vehicle_part* turret_data::part = nullptr protected
Definition at line 680 of file vehicle.h.
Referenced by ammo_capacity(), ammo_current(), ammo_data(), ammo_effects(), ammo_options(), ammo_remaining(), ammo_select(), base(), can_reload(), can_unload(), fire(), in_range(), name(), operator bool(), query(), range(), and uses_vehicle_tanks_or_batteries().
veh
vehicle* turret_data::veh = nullptr protected
Definition at line 679 of file vehicle.h.
Referenced by ammo_capacity(), ammo_data(), ammo_effects(), ammo_options(), ammo_remaining(), base(), can_reload(), can_unload(), fire(), in_range(), operator bool(), post_fire(), prepare_fire(), query(), and range().
vehicle
friend turret_data::vehicle private
Definition at line 585 of file vehicle.h.
Referenced by fire().
The documentation for this class was generated from the following files:
src/vehicle.h
src/turret.cpp