Cataclysm DDA: jmapgen_nested::neighbor_oter_check Class Reference
jmapgen_nested::neighbor_oter_check Class Reference
Public Member Functions
neighbor_oter_check (const JsonObject &jsi)
bool test (const mapgendata &dat) const
Private Attributes
std::unordered_map< direction, cata::flat_set< std::pair< std::string, ot_match_type > > > neighbors
Detailed Description
Definition at line 3520 of file mapgen.cpp.
Constructor & Destructor Documentation
neighbor_oter_check()
jmapgen_nested::neighbor_oter_check::neighbor_oter_check (const JsonObject & jsi) inline explicit
Definition at line 3525 of file mapgen.cpp.
{
                     for( direction dir : all_enum_values<direction>() ) {
                         std::string location = io::enum_to_string( dir );
                         cata::flat_set<std::pair<std::string, ot_match_type>> dir_neighbors;
                         if( !jsi.has_string( location ) ) {
                             for( const JsonValue entry : jsi.get_array( location ) ) {
                                 std::pair<std::string, ot_match_type> dir_neighbor;
                                 if( entry.test_string() ) {
                                     dir_neighbor.first = entry.get_string();
                                     dir_neighbor.second = ot_match_type::contains;
                                 } else {
                                     JsonObject jo = entry.get_object();
                                     dir_neighbor.first = jo.get_string( "om_terrain" );
                                     dir_neighbor.second = jo.get_enum_value<ot_match_type>( "om_terrain_match_type",
                                                           ot_match_type::contains );
                                 }
                                 dir_neighbors.insert( dir_neighbor );
                             }
                         } else {
                             std::pair<std::string, ot_match_type> dir_neighbor;
                             dir_neighbor.first = jsi.get_string( location );
                             dir_neighbor.second = ot_match_type::contains;
                             dir_neighbors.insert( dir_neighbor );
                         }
                         if( !dir_neighbors.empty() ) {
                             neighbors[dir] = std::move( dir_neighbors );
                         }
                     }
                 }
References contains, io::enum_to_string(), JsonObject::get_array(), JsonObject::get_enum_value(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_string(), cata::flat_set< T, Compare, Data >::insert(), mapgen_defer::jsi, location, and neighbors.
Member Function Documentation
test()
bool jmapgen_nested::neighbor_oter_check::test (const mapgendata & dat) const inline
Definition at line 3555 of file mapgen.cpp.
{
                     for( const std::pair<const direction, cata::flat_set<std::pair<std::string, ot_match_type>>> &p :
                          neighbors ) {
                         const direction dir = p.first;
                         const cata::flat_set<std::pair<std::string, ot_match_type>> &allowed_neighbors = p.second;
                         cata_assert( !allowed_neighbors.empty() );
                         bool this_direction_matches = false;
                         for( const std::pair<std::string, ot_match_type> &allowed_neighbor : allowed_neighbors ) {
                             this_direction_matches |=
                                 is_ot_match( allowed_neighbor.first, dat.neighbor_at( dir ).id(),
                                              allowed_neighbor.second );
                         }
                         if( !this_direction_matches ) {
                             return false;
                         }
                     }
                     return true;
                 }
References cata_assert, int_id< T >::id(), is_ot_match(), mapgendata::neighbor_at(), and neighbors.
Referenced by jmapgen_nested::get_entries().
Member Data Documentation
neighbors
std::unordered_map<direction, cata::flat_set<std::pair<std::string, ot_match_type> > > jmapgen_nested::neighbor_oter_check::neighbors private
Definition at line 3523 of file mapgen.cpp.
Referenced by neighbor_oter_check(), and test().
The documentation for this class was generated from the following file:
src/mapgen.cpp