Cataclysm DDA: activity_type Class Reference
activity_type Class Reference
A class that stores constant information that doesn't differ between activities of the same type.
#include <activity_type.h>
Public Member Functions
const activity_id & id () const
const std::set< distraction_type > & default_ignored_distractions () const
bool rooted () const
bool interruptable () const
bool interruptable_with_kb () const
std::string stop_phrase () const
const translation & verb () const
based_on_type based_on () const
bool can_resume () const
bool multi_activity () const
bool will_refuel_fires () const
If true, player will refuel one adjacent fire if there is firewood spot adjacent.
bool valid_auto_needs () const
If true, player will automatically consume from relevant auto-eat/drink zones during activity.
float exertion_level () const
void call_do_turn (player_activity *, Character *) const
bool call_finish (player_activity *, Character *) const
Returns whether it had a finish function or not.
Static Public Member Functions
static void load (const JsonObject &jo)
JSON stuff.
static void check_consistency ()
static void reset ()
Public Attributes
effect_on_condition_id completion_EOC
effect_on_condition_id do_turn_EOC
Private Attributes
activity_id id_
bool rooted_ = false
translation verb_ = to_translation("THIS IS A BUG")
bool interruptable_ = true
bool interruptable_with_kb_ = true
based_on_type based_on_ = based_on_type::SPEED
bool can_resume_ = true
bool multi_activity_ = false
bool refuel_fires = false
bool auto_needs = false
float activity_level = NO_EXERCISE
std::set< distraction_type > default_ignored_distractions_
Detailed Description
A class that stores constant information that doesn't differ between activities of the same type.
Definition at line 38 of file activity_type.h.
Member Function Documentation
based_on()
based_on_type activity_type::based_on () const inline
Definition at line 76 of file activity_type.h.
{
             return based_on_;
         }
References based_on_.
Referenced by player_activity::do_turn().
call_do_turn()
void activity_type::call_do_turn (player_activity * act, Character * you) const
Definition at line 155 of file activity_type.cpp.
 {
     const auto &pair = activity_handlers::do_turn_functions.find( id_ );
     if( pair != activity_handlers::do_turn_functions.end() ) {
         pair->second( act, you );
     }
 }
References act, activity_handlers::do_turn_functions, keycode::end, and id_.
Referenced by player_activity::do_turn().
call_finish()
bool activity_type::call_finish (player_activity * act, Character * you) const
Returns whether it had a finish function or not.
Definition at line 163 of file activity_type.cpp.
 {
     const auto &pair = activity_handlers::finish_functions.find( id_ );
     if( pair != activity_handlers::finish_functions.end() ) {
         pair->second( act, you );
         // kill activity sounds at finish
         sfx::end_activity_sounds();
         return true;
     }
     return false;
 }
References act, keycode::end, sfx::end_activity_sounds(), activity_handlers::finish_functions, and id_.
Referenced by player_activity::do_turn().
can_resume()
bool activity_type::can_resume () const inline
Definition at line 79 of file activity_type.h.
{
             return can_resume_;
         }
References can_resume_.
Referenced by player_activity::can_resume(), and player_activity::can_resume_with().
check_consistency()
void activity_type::check_consistency () static
Definition at line 123 of file activity_type.cpp.
 {
     for( const auto &pair : activity_type_all ) {
         if( pair.second.verb_.empty() ) {
             debugmsg( "%s doesn't have a verb", pair.first.c_str() );
         }
         const bool has_actor = activity_actors::deserialize_functions.find( pair.second.id_ ) !=
                                activity_actors::deserialize_functions.end();
         const bool has_turn_func = activity_handlers::do_turn_functions.find( pair.second.id_ ) !=
                                    activity_handlers::do_turn_functions.end();
         if( pair.second.based_on_ == based_on_type::NEITHER && !( has_turn_func || has_actor ) ) {
             debugmsg( "%s needs a do_turn function or activity actor if it's not based on time or speed.",
                       pair.second.id_.c_str() );
         }
     }
     for( const auto &pair : activity_handlers::do_turn_functions ) {
         if( activity_type_all.find( pair.first ) == activity_type_all.end() ) {
             debugmsg( "The do_turn function %s doesn't correspond to a valid activity_type.",
                       pair.first.c_str() );
         }
     }
     for( const auto &pair : activity_handlers::finish_functions ) {
         if( activity_type_all.find( pair.first ) == activity_type_all.end() ) {
             debugmsg( "The finish_function %s doesn't correspond to a valid activity_type",
                       pair.first.c_str() );
         }
     }
 }
References activity_type_all, debugmsg, activity_actors::deserialize_functions, activity_handlers::do_turn_functions, activity_handlers::finish_functions, and NEITHER.
Referenced by DynamicDataLoader::check_consistency().
default_ignored_distractions()
const std::set<distraction_type>& activity_type::default_ignored_distractions () const inline
Definition at line 60 of file activity_type.h.
{
             return default_ignored_distractions_;
         }
References default_ignored_distractions_.
Referenced by player_activity::player_activity().
exertion_level()
float activity_type::exertion_level () const inline
Definition at line 97 of file activity_type.h.
{
             return activity_level;
         }
References activity_level.
Referenced by activity_actor::exertion_level(), player_activity::exertion_level(), activity_handlers::hand_crank_do_turn(), activity_handlers::pulp_do_turn(), and activity_handlers::repair_item_do_turn().
id()
const activity_id& activity_type::id () const inline
Definition at line 57 of file activity_type.h.
{
             return id_;
         }
References id_.
Referenced by activity_handlers::butcher_finish(), and load().
interruptable()
bool activity_type::interruptable () const inline
Definition at line 66 of file activity_type.h.
{
             return interruptable_;
         }
References interruptable_.
Referenced by player_activity::is_interruptible().
interruptable_with_kb()
bool activity_type::interruptable_with_kb () const inline
Definition at line 69 of file activity_type.h.
{
             return interruptable_with_kb_;
         }
References interruptable_with_kb_.
Referenced by player_activity::is_interruptible_with_kb().
load()
void activity_type::load (const JsonObject & jo) static
JSON stuff.
Definition at line 89 of file activity_type.cpp.
 {
     activity_type result;
     result.id_ = activity_id( jo.get_string( "id" ) );
     assign( jo, "rooted", result.rooted_, true );
     assign( jo, "verb", result.verb_, true );
     assign( jo, "interruptable", result.interruptable_, true );
     assign( jo, "interruptable_with_kb", result.interruptable_with_kb_, true );
     assign( jo, "can_resume", result.can_resume_, true );
     assign( jo, "multi_activity", result.multi_activity_, false );
     assign( jo, "refuel_fires", result.refuel_fires, false );
     assign( jo, "auto_needs", result.auto_needs, false );
     optional( jo, false, "completion_eoc", result.completion_EOC );
     optional( jo, false, "do_turn_eoc", result.do_turn_EOC );
     optional( jo, false, "ignored_distractions", result.default_ignored_distractions_ );
     optional( jo, false, "based_on", result.based_on_ );
     auto act_level_it = activity_levels_map.find( jo.get_string( "activity_level", "undefined" ) );
     if( act_level_it == activity_levels_map.end() ) {
         debugmsg( "activity_type '%s' has invalid activity_level '%s', defaulting to 'LIGHT_EXERCISE'",
                   result.id().c_str() );
         result.activity_level = activity_levels_map.at( "LIGHT_EXERCISE" );
     } else {
         result.activity_level = act_level_it->second;
     }
     if( activity_type_all.count( result.id_ ) ) {
         debugmsg( "Redefinition of %s", result.id_.c_str() );
     } else {
         activity_type_all.emplace( result.id_, result );
     }
 }
References activity_id, activity_level, activity_levels_map, activity_type_all, assign(), auto_needs, based_on_, string_id< T >::c_str(), can_resume_, completion_EOC, debugmsg, default_ignored_distractions_, do_turn_EOC, JsonObject::get_string(), id(), id_, interruptable_, interruptable_with_kb_, multi_activity_, optional(), refuel_fires, rooted_, and verb_.
Referenced by DynamicDataLoader::initialize().
multi_activity()
bool activity_type::multi_activity () const inline
Definition at line 82 of file activity_type.h.
{
             return multi_activity_;
         }
References multi_activity_.
Referenced by player_activity::is_multi_type().
reset()
void activity_type::reset () static
Definition at line 176 of file activity_type.cpp.
 {
     activity_type_all.clear();
 }
References activity_type_all.
Referenced by DynamicDataLoader::unload_data().
rooted()
bool activity_type::rooted () const inline
Definition at line 63 of file activity_type.h.
{
             return rooted_;
         }
References rooted_.
Referenced by player_activity::do_turn(), and player_activity::rooted().
stop_phrase()
std::string activity_type::stop_phrase () const
Definition at line 181 of file activity_type.cpp.
 {
     return string_format( _( "Stop %s?" ), verb_ );
 }
References _, string_format(), and verb_.
Referenced by player_activity::get_stop_phrase().
valid_auto_needs()
bool activity_type::valid_auto_needs () const inline
If true, player will automatically consume from relevant auto-eat/drink zones during activity.
Definition at line 94 of file activity_type.h.
{
             return auto_needs;
         }
References auto_needs.
Referenced by player_activity::do_turn().
verb()
const translation& activity_type::verb () const inline
Definition at line 73 of file activity_type.h.
{
             return verb_;
         }
References verb_.
Referenced by npc::get_current_activity(), and player_activity::get_verb().
will_refuel_fires()
bool activity_type::will_refuel_fires () const inline
If true, player will refuel one adjacent fire if there is firewood spot adjacent.
Definition at line 88 of file activity_type.h.
{
             return refuel_fires;
         }
References refuel_fires.
Referenced by player_activity::do_turn().
Member Data Documentation
activity_level
float activity_type::activity_level = NO_EXERCISE private
Definition at line 51 of file activity_type.h.
Referenced by exertion_level(), and load().
auto_needs
bool activity_type::auto_needs = false private
Definition at line 50 of file activity_type.h.
Referenced by load(), and valid_auto_needs().
based_on_
based_on_type activity_type::based_on_ = based_on_type::SPEED private
Definition at line 46 of file activity_type.h.
Referenced by based_on(), and load().
can_resume_
bool activity_type::can_resume_ = true private
Definition at line 47 of file activity_type.h.
Referenced by can_resume(), and load().
completion_EOC
effect_on_condition_id activity_type::completion_EOC
Definition at line 54 of file activity_type.h.
Referenced by player_activity::do_turn(), and load().
default_ignored_distractions_
std::set<distraction_type> activity_type::default_ignored_distractions_ private
Definition at line 52 of file activity_type.h.
Referenced by default_ignored_distractions(), and load().
do_turn_EOC
effect_on_condition_id activity_type::do_turn_EOC
Definition at line 55 of file activity_type.h.
Referenced by player_activity::do_turn(), and load().
id_
activity_id activity_type::id_ private
Definition at line 41 of file activity_type.h.
Referenced by call_do_turn(), call_finish(), id(), and load().
interruptable_
bool activity_type::interruptable_ = true private
Definition at line 44 of file activity_type.h.
Referenced by interruptable(), and load().
interruptable_with_kb_
bool activity_type::interruptable_with_kb_ = true private
Definition at line 45 of file activity_type.h.
Referenced by interruptable_with_kb(), and load().
multi_activity_
bool activity_type::multi_activity_ = false private
Definition at line 48 of file activity_type.h.
Referenced by load(), and multi_activity().
refuel_fires
bool activity_type::refuel_fires = false private
Definition at line 49 of file activity_type.h.
Referenced by load(), and will_refuel_fires().
rooted_
bool activity_type::rooted_ = false private
Definition at line 42 of file activity_type.h.
Referenced by load(), and rooted().
verb_
translation activity_type::verb_ = to_translation("THIS IS A BUG") private
Definition at line 43 of file activity_type.h.
Referenced by load(), stop_phrase(), and verb().
The documentation for this class was generated from the following files:
src/activity_type.h
src/activity_type.cpp