Cataclysm DDA: npc_attack_rating Class Reference
npc_attack_rating Class Reference
#include <npc_attack.h>
Public Member Functions
npc_attack_rating ()=default
npc_attack_rating (const std::optional< int > &_value, const tripoint &_target)
std::optional< int > value () const
tripoint target () const
bool operator> (const npc_attack_rating &rhs) const
bool operator> (int rhs) const
bool operator< (int rhs) const
npc_attack_rating operator-= (int rhs)
Private Attributes
std::optional< int > _value = std::nullopt
tripoint _target
Detailed Description
Definition at line 17 of file npc_attack.h.
Constructor & Destructor Documentation
npc_attack_rating() [1/2]
npc_attack_rating::npc_attack_rating () default
npc_attack_rating() [2/2]
npc_attack_rating::npc_attack_rating (const std::optional< int > & _value, const tripoint & _target) inline
Definition at line 25 of file npc_attack.h.
                                                      : _value( _value ), _target( _target ) {}
Member Function Documentation
operator-=()
npc_attack_rating npc_attack_rating::operator-= (int rhs)
Definition at line 92 of file npc_attack.cpp.
 {
     if( _value ) {
         *_value -= rhs;
     }
     return *this;
 }
References _value.
operator<()
bool npc_attack_rating::operator< (int rhs) const
Definition at line 84 of file npc_attack.cpp.
 {
     if( !_value ) {
         return true;
     }
     return *_value < rhs;
 }
References _value.
operator>() [1/2]
bool npc_attack_rating::operator> (const npc_attack_rating & rhs) const
Definition at line 65 of file npc_attack.cpp.
 {
     if( !rhs._value ) {
         return true;
     }
     if( !_value ) {
         return false;
     }
     return *_value > *rhs._value;
 }
References _value.
operator>() [2/2]
bool npc_attack_rating::operator> (int rhs) const
Definition at line 76 of file npc_attack.cpp.
 {
     if( !_value ) {
         return false;
     }
     return *_value > rhs;
 }
References _value.
target()
tripoint npc_attack_rating::target () const inline
Definition at line 30 of file npc_attack.h.
{
             return _target;
         }
References _target.
Referenced by npc::execute_action(), and spell::select_target().
value()
std::optional<int> npc_attack_rating::value () const inline
Definition at line 27 of file npc_attack.h.
{
             return _value;
         }
References _value.
Referenced by npc::method_of_attack().
Member Data Documentation
_target
tripoint npc_attack_rating::_target private
Definition at line 22 of file npc_attack.h.
Referenced by target().
_value
std::optional<int> npc_attack_rating::_value = std::nullopt private
Definition at line 20 of file npc_attack.h.
Referenced by operator-=(), operator<(), operator>(), and value().
The documentation for this class was generated from the following files:
src/npc_attack.h
src/npc_attack.cpp