Cataclysm DDA: pickup_inventory_preset Class Reference
pickup_inventory_preset Class Reference
Public Member Functions
pickup_inventory_preset (const Character &you, bool skip_wield_check=false, bool ignore_liquidcont=false)
std::string get_denial (const item_location &loc) const override
The reason why this entry cannot be selected.
bool is_shown (const item_location &loc) const override
Does this entry satisfy the basic preset conditions?
Public Member Functions inherited from inventory_selector_preset
inventory_selector_preset ()
virtual ~inventory_selector_preset ()=default
virtual bool sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
Whether the first item is considered to go before the second.
virtual bool cat_sort_compare (const inventory_entry &lhs, const inventory_entry &rhs) const
virtual nc_color get_color (const inventory_entry &entry) const
Color that will be used to display the entry string.
std::string get_denial (const inventory_entry &entry) const
std::string get_cell_text (const inventory_entry &entry, size_t cell_index) const
Text in the cell.
bool is_stub_cell (const inventory_entry &entry, size_t cell_index) const
size_t get_cells_count () const
Number of cells in the preset.
bool get_checking_components () const
Whether items should make new stacks if components differ.
pocket_type get_pocket_type () const
virtual std::function< bool(const inventory_entry &)> get_filter (const std::string &filter) const
bool indent_entries () const
bool collate_entries () const
Private Attributes
const Character & you
bool skip_wield_check
bool ignore_liquidcont
Additional Inherited Members
Public Attributes inherited from inventory_selector_preset
inventory_selector_save_state * save_state = nullptr
Protected Member Functions inherited from inventory_selector_preset
virtual std::string get_caption (const inventory_entry &entry) const
Text of the first column (default: item name)
void append_cell (const std::function< std::string(const item_location &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Append a new cell to the preset.
void append_cell (const std::function< std::string(const inventory_entry &)> &func, const std::string &title=std::string(), const std::string &stub=std::string())
Protected Attributes inherited from inventory_selector_preset
bool check_components = false
bool _indent_entries = true
bool _collate_entries = false
pocket_type _pk_type = pocket_type::CONTAINER
Detailed Description
Definition at line 511 of file game_inventory.cpp.
Constructor & Destructor Documentation
pickup_inventory_preset()
pickup_inventory_preset::pickup_inventory_preset (const Character & you, bool skip_wield_check = false, bool ignore_liquidcont = false) inline explicit
Definition at line 514 of file game_inventory.cpp.
                                                                                                           : you( you ),
             skip_wield_check( skip_wield_check ), ignore_liquidcont( ignore_liquidcont ) {
             save_state = &pickup_sel_default_state;
             _pk_type = pocket_type::LAST;
         }
References inventory_selector_preset::_pk_type, LAST, pickup_sel_default_state, and inventory_selector_preset::save_state.
Member Function Documentation
get_denial()
std::string pickup_inventory_preset::get_denial (const item_location &) const inline override virtual
The reason why this entry cannot be selected.
Returns
Either the reason of denial or empty string if it's accepted.
Reimplemented from inventory_selector_preset.
Reimplemented in ebookread_inventory_preset, read_inventory_preset, ereader_inventory_preset, and activatable_inventory_preset.
Definition at line 521 of file game_inventory.cpp.
{
             if( !you.has_item( *loc ) ) {
                 if( loc->made_of_from_type( phase_id::GAS ) ) {
                     return _( "Can't pick up gasses." );
                 }
                 if( loc->made_of_from_type( phase_id::LIQUID ) && !loc->is_frozen_liquid() ) {
                     if( loc.has_parent() ) {
                         return _( "Can't pick up liquids." );
                     } else {
                         return _( "Can't pick up spilt liquids." );
                     }
                 } else if( loc->is_frozen_liquid() ) {
                     ret_val<crush_tool_type> can_crush = you.can_crush_frozen_liquid( loc );
                     if( you.can_pickVolume_partial( *loc, false, nullptr, false, true ) ) {
                         if( loc->has_flag( flag_SHREDDED ) ) {// NOLINT(bugprone-branch-clone)
                             return std::string();
                         } else if( !can_crush.success() ) {
                             return can_crush.str();
                         }
                     } else {
                         item item_copy( *loc );
                         item_copy.charges = 1;
                         item_copy.set_flag( flag_SHREDDED );
                         std::pair<item_location, item_pocket *> pocke = const_cast<Character &>( you ).best_pocket(
                                     item_copy, nullptr, false );
                         item_pocket *ip = pocke.second;
                         if( ip == nullptr || ( ip &&
                                                ( !ip->can_contain( item_copy ).success() ||
                                                  !ip->front().can_combine( item_copy ) ||
                                                  item_copy.typeId() != ip->front().typeId() ) ) ) {
                             return _( "Does not have any pocket for frozen liquids!" );
                         } else {
                             return std::string();
                         }
                     }
                 } else if( !you.can_pickVolume_partial( *loc, false, nullptr, false, true ) &&
                            ( skip_wield_check || you.has_wield_conflicts( *loc ) ) ) {
                     return _( "Does not fit in any pocket!" );
                 } else if( !you.can_pickWeight_partial( *loc, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
                     return _( "Too heavy to pick up!" );
                 }
             }
             return std::string();
         }
References _, item::can_combine(), item_pocket::can_contain(), Character::can_crush_frozen_liquid(), Character::can_pickVolume_partial(), Character::can_pickWeight_partial(), item::charges, flag_SHREDDED, item_pocket::front(), GAS, item::has_flag(), visitable::has_item(), item_location::has_parent(), Character::has_wield_conflicts(), item::is_frozen_liquid(), LIQUID, item::made_of_from_type(), item::set_flag(), skip_wield_check, ret_val_common::str(), ret_val_common::success(), item::typeId(), and you.
Referenced by activatable_inventory_preset::get_denial(), ereader_inventory_preset::get_denial(), and read_inventory_preset::get_denial().
is_shown()
bool pickup_inventory_preset::is_shown (const item_location &) const inline override virtual
Does this entry satisfy the basic preset conditions?
Reimplemented from inventory_selector_preset.
Reimplemented in steal_inventory_preset, read_inventory_preset, ereader_inventory_preset, and activatable_inventory_preset.
Definition at line 569 of file game_inventory.cpp.
{
             if( ignore_liquidcont && loc.where() == item_location::type::map &&
                 !loc->made_of( phase_id::SOLID ) ) {
                 map &here = get_map();
                 if( here.has_flag( ter_furn_flag::TFLAG_LIQUIDCONT, loc.position() ) ) {
                     return false;
                 }
             }
             return !( loc.has_parent() && loc.parent_item()->is_ammo_belt() );
         }
References get_map(), map::has_flag(), item_location::has_parent(), ignore_liquidcont, item::is_ammo_belt(), item::made_of(), item_location::map, item_location::parent_item(), item_location::position(), SOLID, TFLAG_LIQUIDCONT, and item_location::where().
Member Data Documentation
ignore_liquidcont
bool pickup_inventory_preset::ignore_liquidcont private
Definition at line 583 of file game_inventory.cpp.
Referenced by is_shown().
skip_wield_check
bool pickup_inventory_preset::skip_wield_check private
Definition at line 582 of file game_inventory.cpp.
Referenced by get_denial().
you
const Character& pickup_inventory_preset::you private
Definition at line 581 of file game_inventory.cpp.
Referenced by get_denial().
The documentation for this class was generated from the following file:
src/game_inventory.cpp