Cataclysm DDA: data_handling_activity_actor Class Reference
data_handling_activity_actor Class Reference
#include <activity_actor_definitions.h>
Public Member Functions
data_handling_activity_actor ()=default
data_handling_activity_actor (const item_location &, const std::vector< item_location > &)
activity_id get_type () const override
Should return the activity id of the corresponding activity.
bool can_resume_with_internal (const activity_actor &, const Character &) const override
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
void start (player_activity &, Character &) override
Called once at the start of the activity.
void do_turn (player_activity &, Character &) override
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
void finish (player_activity &, Character &) override
Called when the activity runs out of moves, assuming that it has not already been set to null.
void canceled (player_activity &, Character &) override
Called just before Character::cancel_activity() executes.
std::unique_ptr< activity_actor > clone () const override
Returns a deep copy of this object.
void serialize (JsonOut &) const override
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Public Member Functions inherited from activity_actor
virtual ~activity_actor ()=default
bool can_resume_with (const activity_actor &other, const Character &who) const
Called in player_activity::can_resume_with which allows suspended activities to be resumed instead of starting a new activity in certain cases.
virtual std::string get_progress_message (const player_activity &act) const
Used to generate the progress display at the top of the screen.
virtual float exertion_level () const
Called every turn, in player_activity::do_turn (with some indirection through player_activity::exertion_level) How strenuous this activity level is.
virtual bool do_drop_invalid_inventory () const
Override to false in actors that are slow because they frequently invalidate the inventory and trigger excessive drop_invalid_inventory() calls, and can guarantee that it is called appropriately themselves.
Static Public Member Functions
static std::unique_ptr< activity_actor > deserialize (JsonValue &)
Private Attributes
item_location recorder
std::vector< item_location > targets
time_duration time_until_next_card = 0_seconds
int handled_cards = 0
int encrypted_cards = 0
int downloaded_photos = 0
int downloaded_songs = 0
std::vector< recipe_id > downloaded_recipes
int downloaded_extended_photos = 0
int downloaded_monster_photos = 0
Static Private Attributes
static constexpr time_duration time_per_card = 1_minutes
Detailed Description
Definition at line 278 of file activity_actor_definitions.h.
Constructor & Destructor Documentation
data_handling_activity_actor() [1/2]
data_handling_activity_actor::data_handling_activity_actor () explicit default
data_handling_activity_actor() [2/2]
data_handling_activity_actor::data_handling_activity_actor (const item_location & recorder, const std::vector< item_location > & targets) explicit
Definition at line 953 of file activity_actor.cpp.
     : recorder( recorder ), targets( targets ) {}
Member Function Documentation
can_resume_with_internal()
bool data_handling_activity_actor::can_resume_with_internal (const activity_actor & , const Character &) const inline override virtual
Returns true if this activity is resumable, and this and other are "equivalent" i.e.
similar enough that this activity can be resumed instead of starting other. Many activities are not resumable, so the default is returning false.
Precondition
other is the same type of actor as this
Reimplemented from activity_actor.
Definition at line 288 of file activity_actor_definitions.h.
{
             return false;
         }
canceled()
void data_handling_activity_actor::canceled (player_activity & , Character &) override virtual
Called just before Character::cancel_activity() executes.
This may be used to perform cleanup
Reimplemented from activity_actor.
Definition at line 1127 of file activity_actor.cpp.
 {
     print_data_handling_tally( p, encrypted_cards, downloaded_photos, downloaded_songs,
                                downloaded_recipes, downloaded_extended_photos, downloaded_monster_photos );
     p.add_msg_if_player( m_info, _( "You stop downloading data after %d %s." ),
                          handled_cards, n_gettext( "card", "cards", handled_cards ) );
     act.set_to_null();
 }
References _, act, Character::add_msg_if_player(), downloaded_extended_photos, downloaded_monster_photos, downloaded_photos, downloaded_recipes, downloaded_songs, encrypted_cards, handled_cards, m_info, n_gettext, and print_data_handling_tally().
clone()
std::unique_ptr<activity_actor> data_handling_activity_actor::clone () const inline override virtual
Returns a deep copy of this object.
Example implementation:
class my_activity_actor {
    std::unique_ptr<activity_actor> clone() const override {
        return std::make_unique<my_activity_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements activity_actor.
Definition at line 297 of file activity_actor_definitions.h.
{
             return std::make_unique<data_handling_activity_actor>( *this );
         }
Referenced by deserialize().
deserialize()
std::unique_ptr< activity_actor > data_handling_activity_actor::deserialize (JsonValue & jsin) static
Definition at line 1161 of file activity_actor.cpp.
 {
     data_handling_activity_actor actor;
     JsonObject jsobj = jsin.get_object();
     jsobj.read( "recorder", actor.recorder );
     jsobj.read( "targets", actor.targets );
     jsobj.read( "time_until_next_action", actor.time_until_next_card );
     jsobj.read( "handled_cards", actor.handled_cards );
     jsobj.read( "encrypted_cards", actor.encrypted_cards );
     jsobj.read( "downloaded_photos", actor.downloaded_photos );
     jsobj.read( "downloaded_songs", actor.downloaded_songs );
     jsobj.read( "downloaded_recipes", actor.downloaded_recipes );
     jsobj.read( "downloaded_extended_photos", actor.downloaded_extended_photos );
     jsobj.read( "downloaded_monster_photos", actor.downloaded_monster_photos );
     return actor.clone();
 }
References clone(), downloaded_extended_photos, downloaded_monster_photos, downloaded_photos, downloaded_recipes, downloaded_songs, encrypted_cards, JsonValue::get_object(), handled_cards, JsonObject::read(), recorder, targets, and time_until_next_card.
do_turn()
void data_handling_activity_actor::do_turn (player_activity & act, Character & who) override virtual
Called on every turn of the activity It may be used to stop the activity prematurely by setting it to null.
Implements activity_actor.
Definition at line 973 of file activity_actor.cpp.
 {
     if( !recorder || !recorder->ammo_sufficient( &p ) ) {
         p.cancel_activity();
         p.add_msg_if_player( m_warning, _( "%s appears to have no energy." ), recorder->display_name() );
         return;
     }
     if( calendar::once_every( 5_minutes ) ) {
         recorder->ammo_consume( recorder->type->charges_to_use(), p.pos(), &p );
     }
     time_until_next_card -= 1_seconds;
     if( time_until_next_card > 0_seconds ) {
         return; // not yet
     }
     item &eink = *recorder;
     item &mc = *targets.back();
     targets.pop_back();
     if( targets.empty() ) {
         act.moves_left = 0;
     }
     time_until_next_card = time_per_card;
     handled_cards++;
     if( mc.has_var( "MC_EXTENDED_PHOTOS" ) ) {
         std::vector<item::extended_photo_def> extended_photos;
         try {
             mc.read_extended_photos( extended_photos, "MC_EXTENDED_PHOTOS", false );
             eink.read_extended_photos( extended_photos, "EIPC_EXTENDED_PHOTOS", true );
             eink.write_extended_photos( extended_photos, "EIPC_EXTENDED_PHOTOS" );
             downloaded_extended_photos++;
         } catch( const JsonError &e ) {
             debugmsg( "Error card reading photos (loaded photos = %i) : %s", extended_photos.size(),
                       e.c_str() );
         }
     }
     const std::string monster_photos = mc.get_var( "MC_MONSTER_PHOTOS" );
     if( !monster_photos.empty() ) {
         downloaded_monster_photos++;
         std::string photos = eink.get_var( "EINK_MONSTER_PHOTOS" );
         if( photos.empty() ) {
             eink.set_var( "EINK_MONSTER_PHOTOS", monster_photos );
         } else {
             std::istringstream f( monster_photos );
             std::string s;
             while( getline( f, s, ',' ) ) {
                 if( s.empty() ) {
                     continue;
                 }
                 const std::string mtype = s;
                 getline( f, s, ',' );
                 const int quality = get_quality_from_string( s );
                 const size_t eink_strpos = photos.find( "," + mtype + "," );
                 if( eink_strpos == std::string::npos ) {
                     photos += mtype + "," + string_format( "%d", quality ) + ",";
                 } else {
                     const size_t strqpos = eink_strpos + mtype.size() + 2;
                     const size_t next_comma = photos.find( ',', strqpos );
                     const int old_quality =
                         get_quality_from_string( photos.substr( strqpos, next_comma ) );
                     if( quality > old_quality ) {
                         const std::string quality_s = string_format( "%d", quality );
                         cata_assert( quality_s.size() == 1 );
                         photos[strqpos] = quality_s.front();
                     }
                 }
             }
             eink.set_var( "EINK_MONSTER_PHOTOS", photos );
         }
     }
     const memory_card_info *mmd = mc.type->memory_card_data ? &*mc.type->memory_card_data : nullptr;
     const bool failed_encrypted = mmd && mmd->data_chance < rng_float( 0.0, 1.0 );
     if( mmd && mmd->on_read_convert_to.is_valid() ) {
         mc.clear_vars();
         mc.unset_flags();
         mc.convert( mmd->on_read_convert_to );
     } // mc is invalid past this point
     if( !mmd || failed_encrypted ) {
         encrypted_cards += failed_encrypted ? 1 : 0;
         return;
     }
     if( mmd->photos_chance >= rng_float( 0.0, 1.0 ) ) {
         const int new_photos = rng( 1, mmd->photos_amount );
         eink.set_var( "EIPC_PHOTOS", eink.get_var( "EIPC_PHOTOS", 0 ) + new_photos );
         downloaded_photos += new_photos;
     }
     if( mmd->songs_chance >= rng_float( 0.0, 1.0 ) ) {
         const int new_songs = rng( 1, mmd->songs_amount );
         eink.set_var( "EIPC_MUSIC", eink.get_var( "EIPC_MUSIC", 0 ) + new_songs );
         downloaded_songs += new_songs;
     }
     if( mmd->recipes_chance >= rng_float( 0.0, 1.0 ) ) {
         std::set<recipe_id> saved_recipes = eink.get_saved_recipes();
         std::set<recipe_id> candidates;
         for( const auto& [rid, r] : recipe_dict ) {
             if( r.never_learn || r.obsolete || mmd->recipes_categories.count( r.category ) == 0 ||
                 saved_recipes.count( rid ) ||
                 r.difficulty > mmd->recipes_level_max || r.difficulty < mmd->recipes_level_min ||
                 ( r.has_flag( "SECRET" ) && !mmd->secret_recipes ) ) {
                 continue;
             }
             candidates.emplace( rid );
         }
         const int recipe_num = rng( 1, mmd->recipes_amount );
         for( int i = 0; i < recipe_num && !candidates.empty(); i++ ) {
             const recipe_id rid = random_entry_removed( candidates );
             if( saved_recipes.emplace( rid ).second ) {
                 downloaded_recipes.emplace_back( rid );
             } else {
                 debugmsg( "failed saving '%s' to '%s'", rid.str(), eink.display_name() );
             }
         }
         eink.set_saved_recipes( saved_recipes );
     }
 }
References _, act, Character::add_msg_if_player(), item::ammo_consume(), item::ammo_sufficient(), JsonError::c_str(), Character::cancel_activity(), cata_assert, itype::charges_to_use(), item::clear_vars(), item::convert(), memory_card_info::data_chance, debugmsg, item::display_name(), downloaded_extended_photos, downloaded_monster_photos, downloaded_photos, downloaded_recipes, downloaded_songs, encrypted_cards, get_quality_from_string(), item::get_saved_recipes(), item::get_var(), handled_cards, item::has_var(), string_id< T >::is_valid(), m_warning, itype::memory_card_data, memory_card_info::on_read_convert_to, calendar::once_every(), memory_card_info::photos_amount, memory_card_info::photos_chance, Creature::pos(), random_entry_removed(), item::read_extended_photos(), recipe_dict, memory_card_info::recipes_amount, memory_card_info::recipes_categories, memory_card_info::recipes_chance, memory_card_info::recipes_level_max, memory_card_info::recipes_level_min, recorder, rng(), rng_float(), memory_card_info::secret_recipes, item::set_saved_recipes(), item::set_var(), mtype::size, memory_card_info::songs_amount, memory_card_info::songs_chance, string_id< T >::str(), string_format(), targets, time_per_card, time_until_next_card, item::type, item::unset_flags(), and item::write_extended_photos().
finish()
void data_handling_activity_actor::finish (player_activity & act, Character & who) override virtual
Called when the activity runs out of moves, assuming that it has not already been set to null.
Implements activity_actor.
Definition at line 1136 of file activity_actor.cpp.
 {
     print_data_handling_tally( p, encrypted_cards, downloaded_photos, downloaded_songs,
                                downloaded_recipes, downloaded_extended_photos, downloaded_monster_photos );
     p.add_msg_if_player( m_info, _( "You finish downloading data from %d %s." ),
                          handled_cards, n_gettext( "card", "cards", handled_cards ) );
     act.set_to_null();
 }
References _, act, Character::add_msg_if_player(), downloaded_extended_photos, downloaded_monster_photos, downloaded_photos, downloaded_recipes, downloaded_songs, encrypted_cards, handled_cards, m_info, n_gettext, and print_data_handling_tally().
get_type()
activity_id data_handling_activity_actor::get_type () const inline override virtual
Should return the activity id of the corresponding activity.
Implements activity_actor.
Definition at line 284 of file activity_actor_definitions.h.
{
             return activity_id( "ACT_DATA_HANDLING" );
         }
References activity_id.
serialize()
void data_handling_activity_actor::serialize (JsonOut & jsout) const override virtual
Must write any custom members of the derived class to json Note that a static member function for deserialization must also be created and added to the activity_actor_deserializers hashmap in activity_actor.cpp.
Implements activity_actor.
Definition at line 1145 of file activity_actor.cpp.
 {
     jsout.start_object();
     jsout.member( "recorder", recorder );
     jsout.member( "targets", targets );
     jsout.member( "time_until_next_action", time_until_next_card );
     jsout.member( "handled_cards", handled_cards );
     jsout.member( "encrypted_cards", encrypted_cards );
     jsout.member( "downloaded_photos", downloaded_photos );
     jsout.member( "downloaded_songs", downloaded_songs );
     jsout.member( "downloaded_recipes", downloaded_recipes );
     jsout.member( "downloaded_extended_photos", downloaded_extended_photos );
     jsout.member( "downloaded_monster_photos", downloaded_monster_photos );
     jsout.end_object();
 }
References downloaded_extended_photos, downloaded_monster_photos, downloaded_photos, downloaded_recipes, downloaded_songs, encrypted_cards, JsonOut::end_object(), handled_cards, JsonOut::member(), recorder, JsonOut::start_object(), targets, and time_until_next_card.
start()
void data_handling_activity_actor::start (player_activity & act, Character & who) override virtual
Called once at the start of the activity.
This may be used to preform setup actions and/or set player_activity::moves_left/moves_total.
Implements activity_actor.
Definition at line 968 of file activity_actor.cpp.
 {
     act.moves_left = act.moves_total = targets.size() * to_moves<int>( time_per_card );
 }
References act, targets, and time_per_card.
Member Data Documentation
downloaded_extended_photos
int data_handling_activity_actor::downloaded_extended_photos = 0 private
Definition at line 313 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), do_turn(), finish(), and serialize().
downloaded_monster_photos
int data_handling_activity_actor::downloaded_monster_photos = 0 private
Definition at line 314 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), do_turn(), finish(), and serialize().
downloaded_photos
int data_handling_activity_actor::downloaded_photos = 0 private
Definition at line 310 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), do_turn(), finish(), and serialize().
downloaded_recipes
std::vector<recipe_id> data_handling_activity_actor::downloaded_recipes private
Definition at line 312 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), do_turn(), finish(), and serialize().
downloaded_songs
int data_handling_activity_actor::downloaded_songs = 0 private
Definition at line 311 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), do_turn(), finish(), and serialize().
encrypted_cards
int data_handling_activity_actor::encrypted_cards = 0 private
Definition at line 309 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), do_turn(), finish(), and serialize().
handled_cards
int data_handling_activity_actor::handled_cards = 0 private
Definition at line 308 of file activity_actor_definitions.h.
Referenced by canceled(), deserialize(), do_turn(), finish(), and serialize().
recorder
item_location data_handling_activity_actor::recorder private
Definition at line 305 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
targets
std::vector<item_location> data_handling_activity_actor::targets private
Definition at line 306 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), serialize(), and start().
time_per_card
constexpr time_duration data_handling_activity_actor::time_per_card = 1_minutes static constexpr private
Definition at line 304 of file activity_actor_definitions.h.
Referenced by do_turn(), and start().
time_until_next_card
time_duration data_handling_activity_actor::time_until_next_card = 0_seconds private
Definition at line 307 of file activity_actor_definitions.h.
Referenced by deserialize(), do_turn(), and serialize().
The documentation for this class was generated from the following files:
src/activity_actor_definitions.h
src/activity_actor.cpp