Cataclysm DDA: contents_change_handler Class Reference
contents_change_handler Class Reference
Records a batch of unsealed containers and handles spilling at once.
#include <contents_change_handler.h>
Public Member Functions
contents_change_handler ()=default
void add_unsealed (const item_location &loc)
Add an already unsealed container to the list.
void unseal_pocket_containing (const item_location &loc)
Unseal the pocket containing loc and add loc's parent to the list.
void handle_by (Character &guy)
Let the guy handle any container that needs spilling.
void serialize (JsonOut &jsout) const
Serialization for activities.
void deserialize (const JsonValue &jsin)
Deserialization for activities.
Private Attributes
std::vector< item_location > unsealed
Detailed Description
Records a batch of unsealed containers and handles spilling at once.
This is preferred over handling containers right after unsealing because the latter can cause items to be invalidated when later code still needs to access them. See Character::handle_contents_changed for more detail.
Definition at line 19 of file contents_change_handler.h.
Constructor & Destructor Documentation
contents_change_handler()
contents_change_handler::contents_change_handler () default
Member Function Documentation
add_unsealed()
void contents_change_handler::add_unsealed (const item_location & loc)
Add an already unsealed container to the list.
This item location should remain valid when handle_by is called.
Definition at line 13 of file contents_change_handler.cpp.
 {
     if( std::find( unsealed.begin(), unsealed.end(), loc ) == unsealed.end() ) {
         unsealed.emplace_back( loc );
     }
 }
References unsealed.
Referenced by insert_item_activity_actor::finish(), and unseal_pocket_containing().
deserialize()
void contents_change_handler::deserialize (const JsonValue & jsin)
Deserialization for activities.
Definition at line 54 of file contents_change_handler.cpp.
 {
     jsin.read( unsealed );
 }
References JsonValue::read(), and unsealed.
handle_by()
void contents_change_handler::handle_by (Character & guy)
Let the guy handle any container that needs spilling.
This may invalidate items in and out of the list of containers. The list is cleared after handling.
Definition at line 37 of file contents_change_handler.cpp.
 {
     // some containers could have been destroyed by e.g. monster attack
     auto it = std::remove_if( unsealed.begin(), unsealed.end(),
     []( const item_location & loc ) -> bool {
         return !loc;
     } );
     unsealed.erase( it, unsealed.end() );
     guy.handle_contents_changed( unsealed );
     unsealed.clear();
 }
References Character::handle_contents_changed(), and unsealed.
Referenced by insert_item_activity_actor::canceled(), drop_activity_actor::canceled(), stash_activity_actor::canceled(), veh_interact::complete_vehicle(), Character::consume(), wear_activity_actor::do_turn(), wield_activity_actor::do_turn(), insert_item_activity_actor::finish(), game::inventory_item_menu(), and unload_activity_actor::unload().
serialize()
void contents_change_handler::serialize (JsonOut & jsout) const
Serialization for activities.
Definition at line 49 of file contents_change_handler.cpp.
 {
     jsout.write( unsealed );
 }
References unsealed, and JsonOut::write().
unseal_pocket_containing()
void contents_change_handler::unseal_pocket_containing (const item_location & loc)
Unseal the pocket containing loc and add loc's parent to the list.
Does nothing if loc does not have a parent container. The parent of loc should remain valid when handle_by is called, but loc only needs to be valid here (for example, the item may be consumed afterwards).
Definition at line 20 of file contents_change_handler.cpp.
 {
     if( loc.has_parent() ) {
         item_location parent = loc.parent_item();
         item_pocket *const pocket = loc.parent_pocket();
         if( pocket ) {
             // on_contents_changed restacks the pocket and should be called later
             // in Character::handle_contents_changed
             pocket->unseal();
         } else {
             debugmsg( "parent container does not contain item" );
         }
         parent.on_contents_changed();
         add_unsealed( parent );
     }
 }
References add_unsealed(), debugmsg, item_location::has_parent(), item_location::on_contents_changed(), item_location::parent_item(), item_location::parent_pocket(), and item_pocket::unseal().
Referenced by veh_interact::complete_vehicle(), Character::consume(), wear_activity_actor::do_turn(), wield_activity_actor::do_turn(), insert_item_activity_actor::finish(), game::inventory_item_menu(), obtain_activity_items(), pick_one_up(), and unload_activity_actor::unload().
Member Data Documentation
unsealed
std::vector<item_location> contents_change_handler::unsealed private
Definition at line 49 of file contents_change_handler.h.
Referenced by add_unsealed(), deserialize(), handle_by(), and serialize().
The documentation for this class was generated from the following files:
src/contents_change_handler.h
src/contents_change_handler.cpp