Cataclysm DDA: overmap_special_batch Class Reference
overmap_special_batch Class Reference
#include <overmap.h>
Public Member Functions
overmap_special_batch (const point_abs_om &origin)
overmap_special_batch (const point_abs_om &origin, const std::vector< const overmap_special * > &specials)
std::vector< overmap_special_placement >::iterator begin ()
std::vector< overmap_special_placement >::const_iterator begin () const
std::vector< overmap_special_placement >::iterator end ()
std::vector< overmap_special_placement >::const_iterator end () const
std::vector< overmap_special_placement >::iterator erase (std::vector< overmap_special_placement >::iterator pos)
bool empty ()
point_abs_om get_origin () const
Private Attributes
std::vector< overmap_special_placement > placements
point_abs_om origin_overmap
Detailed Description
Definition at line 111 of file overmap.h.
Constructor & Destructor Documentation
overmap_special_batch() [1/2]
overmap_special_batch::overmap_special_batch (const point_abs_om & origin) inline explicit
Definition at line 114 of file overmap.h.
 : origin_overmap( origin ) {}
overmap_special_batch() [2/2]
overmap_special_batch::overmap_special_batch (const point_abs_om & origin, const std::vector< const overmap_special * > & specials) inline
Definition at line 115 of file overmap.h.
                                                                                     :
             origin_overmap( origin ) {
             std::transform( specials.begin(), specials.end(),
             std::back_inserter( placements ), []( const overmap_special * elem ) {
                 return overmap_special_placement{ 0, elem };
             } );
         }
References placements, and anonymous_namespace{overmap.cpp}::specials.
Member Function Documentation
begin() [1/2]
std::vector<overmap_special_placement>::iterator overmap_special_batch::begin () inline
Definition at line 126 of file overmap.h.
{
             return placements.begin();
         }
Referenced by overmap::place_special_attempt(), overmap::place_specials(), and overmap::populate().
begin() [2/2]
std::vector<overmap_special_placement>::const_iterator overmap_special_batch::begin () const inline
Definition at line 129 of file overmap.h.
{
             return placements.begin();
         }
empty()
bool overmap_special_batch::empty () inline
Definition at line 142 of file overmap.h.
                      {
             return placements.empty();
         }
Referenced by overmapbuffer::place_special(), overmap::place_specials(), and overmap::place_specials_pass().
end() [1/2]
std::vector<overmap_special_placement>::iterator overmap_special_batch::end () inline
Definition at line 132 of file overmap.h.
{
             return placements.end();
         }
Referenced by overmap::place_special_attempt(), overmap::place_specials(), and overmap::populate().
end() [2/2]
std::vector<overmap_special_placement>::const_iterator overmap_special_batch::end () const inline
Definition at line 135 of file overmap.h.
{
             return placements.end();
         }
erase()
std::vector<overmap_special_placement>::iterator overmap_special_batch::erase (std::vector< overmap_special_placement >::iterator pos) inline
Definition at line 138 of file overmap.h.
{
             return placements.erase( pos );
         }
References math_opers::pos().
Referenced by overmap::place_special_attempt(), overmap::place_specials(), and overmap::populate().
get_origin()
point_abs_om overmap_special_batch::get_origin () const inline
Definition at line 146 of file overmap.h.
{
             return origin_overmap;
         }
Referenced by overmap::place_specials().
Member Data Documentation
origin_overmap
point_abs_om overmap_special_batch::origin_overmap private
Definition at line 152 of file overmap.h.
placements
std::vector<overmap_special_placement> overmap_special_batch::placements private
Definition at line 151 of file overmap.h.
Referenced by overmap_special_batch().
The documentation for this class was generated from the following file:
src/overmap.h