Cataclysm DDA: enum_flags_reader< E > Class Template Reference
enum_flags_reader< E > Class Template Reference
Uses io::string_to_enum to convert the string from JSON to a C++ enum.
#include <generic_factory.h>
Public Member Functions
enum_flags_reader (const std::string &flag_type)
E get_next (const JsonValue &jv) const
Public Member Functions inherited from generic_typed_reader< enum_flags_reader< E > >
void insert_values_from (const JsonObject &jo, const std::string_view member_name, C &container) const
void insert_next (JsonValue &jv, C &container) const
void erase_values_from (const JsonObject &jo, const std::string_view member_name, C &container) const
void erase_next (JsonValue &jv, C &container) const
bool operator() (const JsonObject &jo, const std::string_view member_name, C &container, bool was_loaded) const
Implements the reader interface, handles members that are containers of flags.
bool operator() (const JsonObject &jo, const std::string_view member_name, C &member, bool) const
Implements the reader interface, handles a simple data member.
bool do_relative (const JsonObject &jo, const std::string_view name, C &) const
bool do_relative (const JsonObject &jo, const std::string_view name, C &member) const
bool read_normal (const JsonObject &jo, const std::string_view name, C &member) const
Private Attributes
const std::string flag_type
Detailed Description
template<typename E>
class enum_flags_reader< E >
Uses io::string_to_enum to convert the string from JSON to a C++ enum.
Definition at line 1293 of file generic_factory.h.
Constructor & Destructor Documentation
enum_flags_reader()
template<typename E > enum_flags_reader< E >::enum_flags_reader (const std::string & flag_type) inline explicit
Definition at line 1299 of file generic_factory.h.
                                                              : flag_type( flag_type ) {
     }
Member Function Documentation
get_next()
template<typename E > E enum_flags_reader< E >::get_next (const JsonValue & jv) const inline
Definition at line 1302 of file generic_factory.h.
{
         const std::string flag = jv.get_string();
         try {
             return io::string_to_enum<E>( flag );
         } catch( const io::InvalidEnumString & ) {
             jv.throw_error( string_format( "invalid %s: \"%s\"", flag_type, flag ) );
             throw; // ^^ throws already
         }
     }
References enum_flags_reader< E >::flag_type, JsonValue::get_string(), string_format(), and JsonValue::throw_error().
Member Data Documentation
flag_type
template<typename E > const std::string enum_flags_reader< E >::flag_type private
Definition at line 1296 of file generic_factory.h.
Referenced by enum_flags_reader< E >::get_next().
The documentation for this class was generated from the following file:
src/generic_factory.h