Cataclysm DDA: salvage_actor Class Reference
salvage_actor Class Reference
Cuts stuff up into components.
#include <iuse_actor.h>
Public Member Functions
std::optional< int > try_to_cut_up (Character &p, item &cutter, item_location &cut) const
int time_to_cut_up (const item &it) const
bool valid_to_cut_up (const Character *p, const item &it) const
salvage_actor (const std::string &type="salvage")
~salvage_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual ret_val< void > can_use (const Character &, const item &, const tripoint &) const
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
int moves_per_part = 25
Moves used per unit of volume of cut item.
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Private Member Functions
void cut_up (Character &p, item_location &cut) const
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Cuts stuff up into components.
Definition at line 500 of file iuse_actor.h.
Constructor & Destructor Documentation
salvage_actor()
salvage_actor::salvage_actor (const std::string & type = "salvage") inline explicit
Definition at line 510 of file iuse_actor.h.
 : iuse_actor( type ) {}
~salvage_actor()
salvage_actor::~salvage_actor () override default
Member Function Documentation
clone()
std::unique_ptr< iuse_actor > salvage_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 1462 of file iuse_actor.cpp.
 {
     return std::make_unique<salvage_actor>( *this );
 }
cut_up()
void salvage_actor::cut_up (Character & p, item_location & cut) const private
Fabrication reduces chance of losing components when cutting items up Dexterity randomly reduces component loss when cutting items up
Definition at line 1619 of file iuse_actor.cpp.
 {
     // Map of salvaged items (id, count)
     std::map<itype_id, int> salvage;
     std::map<material_id, units::mass> mat_to_weight;
     std::set<material_id> mat_set;
     for( std::pair<material_id, int> mat : cut.get_item()->made_of() ) {
         mat_set.insert( mat.first );
     }
     // Calculate efficiency losses
     float efficiency = 1.0;
     // Higher fabrication, less chance of entropy, but still a chance.
     /** @EFFECT_FABRICATION reduces chance of losing components when cutting items up */
     int entropy_threshold = std::max( 0,
                                       5 - static_cast<int>( round( p.get_skill_level( skill_fabrication ) ) ) );
     if( rng( 1, 10 ) <= entropy_threshold ) {
         efficiency *= 0.9;
     }
     // Fail dex roll, potentially lose more parts.
     /** @EFFECT_DEX randomly reduces component loss when cutting items up */
     if( dice( 3, 4 ) > p.dex_cur ) {
         efficiency *= 0.95;
     }
     // If the item being cut is damaged, additional losses will be incurred.
     efficiency *= std::pow( 0.8, cut.get_item()->damage_level() );
     auto distribute_uniformly = [&mat_to_weight]( const item & x, float num_adjusted ) -> void {
         for( const auto &type : x.made_of() )
         {
             mat_to_weight[type.first] += proportional_weight( x, type.second ) * num_adjusted;
         }
     };
     // efficiency is decreased every time the ingredients of a recipe have more mass than the output
     // num_adjusted represents the number of items and efficiency in one value
     std::function<void( item, float )> cut_up_component =
         [&salvage, &mat_set, &distribute_uniformly, &cut_up_component]
     ( const item & curr, float num_adjusted ) -> void {
         // If it is one of the basic components, add it into the list
         if( curr.type->is_basic_component() )
         {
             int num_actual = static_cast<int>( num_adjusted );
             salvage[curr.typeId()] += num_actual;
             return;
         }
         // Discard invalid component
         // Non-salvageable items are discarded even if made of appropriate material
         if( !curr.made_of_any( mat_set ) || !curr.is_salvageable() )
         {
             return;
         }
         // Items count by charges are not always smaller than base materials
         // Necessary for e.g. bones -> bone splinters
         if( curr.count_by_charges() )
         {
             distribute_uniformly( curr, num_adjusted );
             return;
         }
         // All intact components are also cut up and destroyed
         if( !curr.components.empty() )
         {
             for( const item_components::type_vector_pair &tvp : curr.components ) {
                 for( const item &iter : tvp.second ) {
                     cut_up_component( iter, num_adjusted );
                 }
             }
             return;
         }
         // Try to find an available recipe and "restore" its components
         std::optional<recipe> uncraft = find_uncraft_recipe( curr );
         if( uncraft )
         {
             const requirement_data requirements = uncraft->simple_requirements();
             units::mass ingredient_weight = 0_gram;
             for( const auto &altercomps : requirements.get_components() ) {
                 if( !altercomps.empty() && altercomps.front().type ) {
                     ingredient_weight += altercomps.front().type->weight * altercomps.front().count;
                 }
             }
             // We decrease efficiency so on avg no more mass is salvaged than the original item weighed
             num_adjusted *= std::min( 1.0f, static_cast<float>( curr.weight().value() )
                                       / static_cast<float>( ingredient_weight.value() ) );
             // Find default components set from recipe
             for( const auto &altercomps : requirements.get_components() ) {
                 const item_comp &comp = altercomps.front();
                 item next = item( comp.type, calendar::turn );
                 if( next.count_by_charges() ) {
                     next.charges = 1;
                 }
                 cut_up_component( next, num_adjusted * comp.count );
             }
         } else
         {
             // No recipe was found so we guess and distribute the weight uniformly.
             // This is imprecise but it can't be exploited as no recipe exists for the item
             distribute_uniformly( curr, num_adjusted );
         }
     };
     // Decompose the item into irreducible parts
     cut_up_component( *cut.get_item(), efficiency );
     // Not much practice, and you won't get very far ripping things up.
     p.practice( skill_fabrication, rng( 0, 5 ), 1 );
     // Add the uniformly distributed mass to the relevant salvage items
     for( const auto &iter : mat_to_weight ) {
         if( const std::optional<itype_id> id = iter.first->salvaged_into() ) {
             salvage[*id] += iter.second / id->obj().weight;
         }
     }
     add_msg( m_info, _( "You try to salvage materials from the %s." ),
              cut.get_item()->tname() );
     const item_location::type cut_type = cut.where();
     const tripoint pos = cut.position();
     const bool filthy = cut.get_item()->is_filthy();
     // Clean up before removing the item.
     remove_ammo( *cut.get_item(), p );
     // Original item has been consumed.
     cut.remove_item();
     // Force an encumbrance update in case they were wearing that item.
     p.calc_encumbrance();
     map &here = get_map();
     for( const auto &salvaged_mat : salvage ) {
         item result( salvaged_mat.first, calendar::turn );
         int amount = salvaged_mat.second;
         if( amount > 0 ) {
             // Time based on number of components.
             p.mod_moves( -moves_per_part );
             if( result.count_by_charges() ) {
                 result.charges = amount;
                 amount = 1;
             }
             add_msg( m_good, n_gettext( "Salvaged %1$i %2$s.", "Salvaged %1$i %2$s.", amount ),
                      amount, result.display_name( amount ) );
             if( filthy ) {
                 result.set_flag( flag_FILTHY );
             }
             if( cut_type == item_location::type::character ) {
                 p.i_add_or_drop( result, amount );
             } else {
                 for( int i = 0; i < amount; i++ ) {
                     here.add_item_or_charges( pos, result );
                 }
             }
         } else {
             add_msg( m_bad, _( "Could not salvage a %s." ), result.display_name() );
         }
     }
 }
References _, map::add_item_or_charges(), add_msg(), Character::calc_encumbrance(), item_location::character, item::charges, component::count, item::count_by_charges(), item::damage_level(), Character::dex_cur, dice(), item::display_name(), anonymous_namespace{item_tname.cpp}::filthy(), find_uncraft_recipe(), flag_FILTHY, requirement_data::get_components(), item_location::get_item(), get_map(), Character::get_skill_level(), Character::i_add_or_drop(), base_camps::id, item::is_filthy(), item, m_bad, m_good, m_info, item::made_of(), max(), min(), Creature::mod_moves(), moves_per_part, n_gettext, math_opers::pos(), item_location::position(), Character::practice(), proportional_weight(), remove_ammo(), item_location::remove_item(), rng(), round(), game_menus::inv::salvage(), item::set_flag(), skill_fabrication, item::tname(), calendar::turn, iuse_actor::type, component::type, units::quantity< V, U >::value(), item::weight(), and item_location::where().
Referenced by try_to_cut_up().
load()
void salvage_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 1456 of file iuse_actor.cpp.
 {
     assign( obj, "cost", cost );
     assign( obj, "moves_per_part", moves_per_part );
 }
References assign(), iuse_actor::cost, and moves_per_part.
time_to_cut_up()
int salvage_actor::time_to_cut_up (const item & it) const
Definition at line 1537 of file iuse_actor.cpp.
 {
     units::mass total_material_weight;
     int num_materials = 0;
     visit_salvage_products( it, [&total_material_weight, &num_materials]( const item & exemplar ) {
         total_material_weight += exemplar.weight();
         num_materials += 1;
     } );
     if( num_materials == 0 ) {
         return 0;
     }
     units::mass average_material_weight = total_material_weight / num_materials;
     int count = it.weight() / average_material_weight;
     return moves_per_part * count;
 }
References moves_per_part, visit_salvage_products(), and item::weight().
Referenced by add_salvagables(), game::butcher(), and salvage_inventory_preset::salvage_inventory_preset().
try_to_cut_up()
std::optional< int > salvage_actor::try_to_cut_up (Character & p, item & cutter, item_location & cut) const
Definition at line 1484 of file iuse_actor.cpp.
 {
     if( !valid_to_cut_up( &p, *cut.get_item() ) ) {
         // Messages should have already been displayed.
         return std::nullopt;
     }
     if( &cutter == cut.get_item() ) {
         add_msg( m_info, _( "You can not cut the %s with itself." ), cutter.tname() );
         return std::nullopt;
     }
     salvage_actor::cut_up( p, cut );
     // Return used charges from cutter
     return cost >= 0 ? cost : 1;
 }
References _, add_msg(), iuse_actor::cost, cut_up(), item_location::get_item(), m_info, item::tname(), and valid_to_cut_up().
Referenced by game::butcher(), longsalvage_activity_actor::finish(), and use().
use()
std::optional< int > salvage_actor::use (Character * p, item & cutter, const tripoint &) const override virtual
Implements iuse_actor.
Definition at line 1467 of file iuse_actor.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action salvage that requires character but no character is present",
                   cutter.typeId().str() );
         return std::nullopt;
     }
     item_location item_loc = game_menus::inv::salvage( *p, this );
     if( !item_loc ) {
         add_msg( _( "Never mind." ) );
         return std::nullopt;
     }
     return salvage_actor::try_to_cut_up( *p, cutter, item_loc );
 }
References _, add_msg(), debugmsg, game_menus::inv::salvage(), string_id< T >::str(), try_to_cut_up(), and item::typeId().
valid_to_cut_up()
bool salvage_actor::valid_to_cut_up (const Character * p, const item & it) const
Definition at line 1555 of file iuse_actor.cpp.
 {
     // There must be some historical significance to these items.
     if( !it.is_salvageable() ) {
         if( p ) {
             add_msg( m_info, _( "Can't salvage anything from %s." ), it.tname() );
         }
         if( it.is_disassemblable() ) {
             if( p ) {
                 add_msg( m_info, _( "Try disassembling the %s instead." ), it.tname() );
             }
         }
         return false;
     }
     if( !it.empty() ) {
         if( p ) {
             add_msg( m_info, _( "Please empty the %s before cutting it up." ), it.tname() );
         }
         return false;
     }
     if( !can_produce_results( it ) ) {
         if( p ) {
             add_msg( m_info, _( "The %s is too small to salvage material from." ), it.tname() );
         }
         return false;
     }
     if( p ) {
         // Softer warnings at the end so we don't ask permission and then tell them no.
         if( &it == p->get_wielded_item().get_item() ) {
             return query_yn( _( "You are wielding that, are you sure?" ) );
         } else if( p->is_worn( it ) ) {
             return query_yn( _( "You're wearing that, are you sure?" ) );
         }
     }
     return true;
 }
References _, add_msg(), can_produce_results(), item::empty(), item_location::get_item(), Character::get_wielded_item(), item::is_disassemblable(), item::is_salvageable(), Character::is_worn(), m_info, query_yn(), and item::tname().
Referenced by game::butcher(), longsalvage_activity_actor::finish(), salvage_inventory_preset::is_shown(), and try_to_cut_up().
Member Data Documentation
moves_per_part
int salvage_actor::moves_per_part = 25
Moves used per unit of volume of cut item.
Definition at line 504 of file iuse_actor.h.
Referenced by cut_up(), load(), and time_to_cut_up().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp