Cataclysm DDA: TextJsonValue Class Reference
TextJsonValue Class Reference
#include <json.h>
Public Member Functions
TextJsonValue (TextJsonIn &jsin, int pos)
operator std::string () const
operator int () const
operator bool () const
operator double () const
operator TextJsonObject () const
operator TextJsonArray () const
template<typename T >
bool read (T &t, bool throw_on_error=false) const
bool test_string () const
bool test_int () const
bool test_bool () const
bool test_float () const
bool test_object () const
bool test_array () const
bool test_null () const
std::string get_string () const
int get_int () const
bool get_bool () const
double get_float () const
TextJsonObject get_object () const
TextJsonArray get_array () const
void get_null () const
void string_error (const std::string &err) const
void string_error (int offset, const std::string &err) const
void throw_error (const std::string &err) const
void throw_error (int offset, const std::string &err) const
void throw_error_after (const std::string &err) const
Private Member Functions
TextJsonIn & seek () const
Private Attributes
TextJsonIn & jsin_
int pos_
Detailed Description
Definition at line 110 of file json.h.
Constructor & Destructor Documentation
TextJsonValue()
TextJsonValue::TextJsonValue (TextJsonIn & jsin, int pos) inline
Definition at line 119 of file json.h.
 : jsin_( jsin ), pos_( pos ) { }
Member Function Documentation
get_array()
TextJsonArray TextJsonValue::get_array () const inline
Definition at line 1428 of file json.h.
 {
     return seek().get_array();
 }
References TextJsonIn::get_array(), and seek().
Referenced by anonymous_namespace{flexbuffer_cache.cpp}::try_find_and_throw_json_error().
get_bool()
bool TextJsonValue::get_bool () const inline
Definition at line 1416 of file json.h.
 {
     return seek().get_bool();
 }
References TextJsonIn::get_bool(), and seek().
Referenced by TextJsonObject::get_bool().
get_float()
double TextJsonValue::get_float () const inline
Definition at line 1420 of file json.h.
 {
     return seek().get_float();
 }
References TextJsonIn::get_float(), and seek().
Referenced by TextJsonObject::get_float().
get_int()
int TextJsonValue::get_int () const inline
Definition at line 1412 of file json.h.
 {
     return seek().get_int();
 }
References TextJsonIn::get_int(), and seek().
Referenced by TextJsonObject::get_int().
get_null()
void TextJsonValue::get_null () const inline
Definition at line 1432 of file json.h.
 {
     seek().skip_null();
 }
References seek(), and TextJsonIn::skip_null().
Referenced by deserialize().
get_object()
TextJsonObject TextJsonValue::get_object () const inline
Definition at line 1424 of file json.h.
 {
     return seek().get_object();
 }
References TextJsonIn::get_object(), and seek().
Referenced by anonymous_namespace{flexbuffer_cache.cpp}::try_find_and_throw_json_error().
get_string()
std::string TextJsonValue::get_string () const inline
Definition at line 1408 of file json.h.
 {
     return seek().get_string();
 }
References TextJsonIn::get_string(), and seek().
Referenced by TextJsonObject::get_string().
operator bool()
TextJsonValue::operator bool () const inline
Definition at line 1354 of file json.h.
 {
     return seek().get_bool();
 }
operator double()
TextJsonValue::operator double () const inline
Definition at line 1359 of file json.h.
 {
     return seek().get_float();
 }
operator int()
TextJsonValue::operator int () const inline
Definition at line 1349 of file json.h.
 {
     return seek().get_int();
 }
operator std::string()
TextJsonValue::operator std::string () const inline
Definition at line 1344 of file json.h.
 {
     return seek().get_string();
 }
operator TextJsonArray()
TextJsonValue::operator TextJsonArray () const inline
Definition at line 1369 of file json.h.
 {
     return seek().get_array();
 }
References TextJsonArray::get_array().
operator TextJsonObject()
TextJsonValue::operator TextJsonObject () const inline
Definition at line 1364 of file json.h.
 {
     return seek().get_object();
 }
References TextJsonObject::get_object().
read()
template<typename T > bool TextJsonValue::read (T & t, bool throw_on_error = false) const inline
Definition at line 1374 of file json.h.
 {
     return seek().read( t, throw_on_error );
 }
References TextJsonIn::read(), and seek().
Referenced by deserialize().
seek()
TextJsonIn & TextJsonValue::seek () const private
Definition at line 2450 of file json.cpp.
 {
     jsin_.seek( pos_ );
     return jsin_;
 }
References jsin_, pos_, and TextJsonIn::seek().
Referenced by get_array(), get_bool(), get_float(), get_int(), get_null(), get_object(), get_string(), read(), string_error(), test_array(), test_bool(), test_float(), test_int(), test_null(), test_object(), test_string(), throw_error(), and throw_error_after().
string_error() [1/2]
void TextJsonValue::string_error (const std::string & err) const
Definition at line 85 of file json.cpp.
 {
     string_error( 0, err );
 }
string_error() [2/2]
void TextJsonValue::string_error (int offset, const std::string & err) const
Definition at line 90 of file json.cpp.
 {
     seek().string_error( offset, err );
 }
References seek(), and TextJsonIn::string_error().
test_array()
bool TextJsonValue::test_array () const inline
Definition at line 1399 of file json.h.
 {
     return seek().test_array();
 }
References seek(), and TextJsonIn::test_array().
Referenced by anonymous_namespace{flexbuffer_cache.cpp}::try_find_and_throw_json_error().
test_bool()
bool TextJsonValue::test_bool () const inline
Definition at line 1387 of file json.h.
 {
     return seek().test_bool();
 }
References seek(), and TextJsonIn::test_bool().
test_float()
bool TextJsonValue::test_float () const inline
Definition at line 1391 of file json.h.
 {
     return seek().test_float();
 }
References seek(), and TextJsonIn::test_float().
test_int()
bool TextJsonValue::test_int () const inline
Definition at line 1383 of file json.h.
 {
     return seek().test_int();
 }
References seek(), and TextJsonIn::test_int().
test_null()
bool TextJsonValue::test_null () const inline
Definition at line 1403 of file json.h.
 {
     return seek().test_null();
 }
References seek(), and TextJsonIn::test_null().
Referenced by deserialize().
test_object()
bool TextJsonValue::test_object () const inline
Definition at line 1395 of file json.h.
 {
     return seek().test_object();
 }
References seek(), and TextJsonIn::test_object().
Referenced by anonymous_namespace{flexbuffer_cache.cpp}::try_find_and_throw_json_error().
test_string()
bool TextJsonValue::test_string () const inline
Definition at line 1379 of file json.h.
 {
     return seek().test_string();
 }
References seek(), and TextJsonIn::test_string().
throw_error() [1/2]
void TextJsonValue::throw_error (const std::string & err) const
Definition at line 95 of file json.cpp.
 {
     throw_error( 0, err );
 }
throw_error() [2/2]
void TextJsonValue::throw_error (int offset, const std::string & err) const
Definition at line 100 of file json.cpp.
 {
     seek().error( offset, err );
 }
References TextJsonIn::error(), and seek().
throw_error_after()
void TextJsonValue::throw_error_after (const std::string & err) const
Definition at line 105 of file json.cpp.
 {
     seek().skip_value();
     jsin_.error( err );
 }
References TextJsonIn::error(), jsin_, seek(), and TextJsonIn::skip_value().
Member Data Documentation
jsin_
TextJsonIn& TextJsonValue::jsin_ private
Definition at line 113 of file json.h.
Referenced by seek(), and throw_error_after().
pos_
int TextJsonValue::pos_ private
Definition at line 114 of file json.h.
Referenced by seek().
The documentation for this class was generated from the following files:
src/json.h
src/json.cpp