Cataclysm DDA: TextJsonObject::const_iterator Class Reference
TextJsonObject::const_iterator Class Reference
#include <json.h>
Public Member Functions
const_iterator (const TextJsonObject &object, const decltype(iter_) &iter)
const_iterator & operator++ ()
TextJsonMember operator* () const
Private Attributes
const TextJsonObject & object_
decltype(TextJsonObject::positions) ::const_iterator iter_
Friends
bool operator== (const const_iterator &lhs, const const_iterator &rhs)
bool operator!= (const const_iterator &lhs, const const_iterator &rhs)
Detailed Description
Definition at line 1504 of file json.h.
Constructor & Destructor Documentation
const_iterator()
TextJsonObject::const_iterator::const_iterator (const TextJsonObject & object, const decltype(iter_) & iter) inline
Definition at line 1511 of file json.h.
                                                                                       : object_( object ),
             iter_( iter ) { }
Member Function Documentation
operator*()
TextJsonMember TextJsonObject::const_iterator::operator* () const inline
Definition at line 1518 of file json.h.
{
             object_.mark_visited( iter_->first );
             return TextJsonMember( iter_->first, TextJsonValue( *object_.jsin, iter_->second ) );
         }
References iter_, TextJsonObject::jsin, TextJsonObject::mark_visited(), and object_.
operator++()
const_iterator& TextJsonObject::const_iterator::operator++ () inline
Definition at line 1514 of file json.h.
{
             iter_++;
             return *this;
         }
References iter_.
Friends And Related Function Documentation
operator!=
bool operator!= (const const_iterator & lhs, const const_iterator & rhs) friend
Definition at line 1526 of file json.h.
{
             return !operator==( lhs, rhs );
         }
operator==
bool operator== (const const_iterator & lhs, const const_iterator & rhs) friend
Definition at line 1523 of file json.h.
{
             return lhs.iter_ == rhs.iter_;
         }
Member Data Documentation
iter_
decltype(TextJsonObject::positions) ::const_iterator TextJsonObject::const_iterator::iter_ private
Definition at line 1508 of file json.h.
Referenced by operator*(), and operator++().
object_
const TextJsonObject& TextJsonObject::const_iterator::object_ private
Definition at line 1507 of file json.h.
Referenced by operator*().
The documentation for this class was generated from the following file:
src/json.h