Cataclysm DDA: musical_instrument_actor Class Reference
musical_instrument_actor Class Reference
Plays music.
#include <iuse_actor.h>
Public Member Functions
musical_instrument_actor (const std::string &type="musical_instrument")
~musical_instrument_actor () override=default
void load (const JsonObject &obj) override
std::optional< int > use (Character *, item &, const tripoint &) const override
ret_val< void > can_use (const Character &, const item &, const tripoint &) const override
std::unique_ptr< iuse_actor > clone () const override
Returns a deep copy of this object.
Public Member Functions inherited from iuse_actor
virtual ~iuse_actor ()=default
virtual void info (const item &, std::vector< iteminfo > &) const
virtual bool is_valid () const
Returns whether the actor is valid (exists in the generator).
virtual std::string get_name () const
Returns the translated name of the action.
virtual std::string get_description () const
Returns the translated description of the action.
virtual void finalize (const itype_id &)
Finalizes the actor.
Public Attributes
int speed_penalty = 0
Speed penalty when playing the instrument.
int volume = 0
Volume of the music played.
int fun = 0
Base morale bonus/penalty.
int fun_bonus = 0
Morale bonus scaling (off current perception)
std::vector< translation > player_descriptions
List of sound descriptions for players.
std::vector< translation > npc_descriptions
List of sound descriptions for NPCs.
time_duration description_frequency = 0_turns
Display description once per this duration (calendar::once_every).
Public Attributes inherited from iuse_actor
const std::string type
The type of the action.
int cost
Units of ammo required per invocation (or use value from base item if negative)
Additional Inherited Members
Protected Member Functions inherited from iuse_actor
iuse_actor (const std::string &type, int cost=-1)
Detailed Description
Plays music.
Definition at line 642 of file iuse_actor.h.
Constructor & Destructor Documentation
musical_instrument_actor()
musical_instrument_actor::musical_instrument_actor (const std::string & type = "musical_instrument") inline explicit
Definition at line 674 of file iuse_actor.h.
                                                                                           : iuse_actor(
                 type ) {}
~musical_instrument_actor()
musical_instrument_actor::~musical_instrument_actor () override default
Member Function Documentation
can_use()
ret_val< void > musical_instrument_actor::can_use (const Character & p, const item & , const tripoint &) const override virtual
Reimplemented from iuse_actor.
Definition at line 2241 of file iuse_actor.cpp.
 {
     // TODO: (maybe): Mouth encumbrance? Smoke? Lack of arms? Hand encumbrance?
     if( p.is_underwater() ) {
         return ret_val<void>::make_failure( _( "You can't do that while underwater." ) );
     }
     if( p.is_mounted() ) {
         return ret_val<void>::make_failure( _( "You can't do that while mounted." ) );
     }
     return ret_val<void>::make_success();
 }
References _, Character::is_mounted(), Creature::is_underwater(), ret_val< T >::make_failure(), and ret_val< T >::make_success().
clone()
std::unique_ptr< iuse_actor > musical_instrument_actor::clone () const override virtual
Returns a deep copy of this object.
Example implementation:
class my_iuse_actor {
    std::unique_ptr<iuse_actor> clone() const override {
        return std::make_unique<my_iuse_actor>( *this );
    }
};
The returned value should behave like the original item and must have the same type.
Implements iuse_actor.
Definition at line 2107 of file iuse_actor.cpp.
 {
     return std::make_unique<musical_instrument_actor>( *this );
 }
load()
void musical_instrument_actor::load (const JsonObject & obj) override virtual
Implements iuse_actor.
Definition at line 2112 of file iuse_actor.cpp.
 {
     speed_penalty = obj.get_int( "speed_penalty", 10 );
     volume = obj.get_int( "volume" );
     fun = obj.get_int( "fun" );
     fun_bonus = obj.get_int( "fun_bonus", 0 );
     description_frequency = time_duration::from_turns( obj.get_int( "description_frequency", 0 ) );
     if( !obj.read( "description_frequency", description_frequency ) ) {
         obj.throw_error( "missing member \"description_frequency\"" );
     }
     obj.read( "player_descriptions", player_descriptions );
     obj.read( "npc_descriptions", npc_descriptions );
 }
References description_frequency, time_duration::from_turns(), fun, fun_bonus, JsonObject::get_int(), npc_descriptions, player_descriptions, JsonObject::read(), speed_penalty, JsonObject::throw_error(), and volume.
use()
std::optional< int > musical_instrument_actor::use (Character * p, item & it, const tripoint &) const override virtual
Perception increases morale bonus when playing an instrument
Implements iuse_actor.
Definition at line 2126 of file iuse_actor.cpp.
 {
     if( !p ) {
         it.active = false;
         return std::nullopt;
     }
     if( !p->is_npc() && music::is_active_music_id( music::music_id::instrument ) ) {
         music::deactivate_music_id( music::music_id::instrument );
         // Because musical instrument creates musical sound too
         if( music::is_active_music_id( music::music_id::sound ) ) {
             music::deactivate_music_id( music::music_id::sound );
         }
     }
     if( p->is_mounted() ) {
         p->add_msg_player_or_npc( m_bad, _( "You can't play music while mounted." ),
                                   _( "<npcname> can't play music while mounted." ) );
         it.active = false;
         return std::nullopt;
     }
     if( p->is_underwater() ) {
         p->add_msg_player_or_npc( m_bad,
                                   _( "You can't play music underwater." ),
                                   _( "<npcname> can't play music underwater." ) );
         it.active = false;
         return std::nullopt;
     }
     // Stop playing a wind instrument when winded or even eventually become winded while playing it?
     // It's impossible to distinguish instruments for now anyways.
     if( p->has_effect( effect_sleep ) || p->has_effect( effect_stunned ) ||
         p->has_effect( effect_asthma ) ) {
         p->add_msg_player_or_npc( m_bad,
                                   _( "You stop playing your %s." ),
                                   _( "<npcname> stops playing their %s." ),
                                   it.display_name() );
         it.active = false;
         return std::nullopt;
     }
     // Check for worn or wielded - no "floating"/bionic instruments for now
     // TODO: Distinguish instruments played with hands and with mouth, consider encumbrance
     const int inv_pos = p->get_item_position( &it );
     if( inv_pos >= 0 || inv_pos == INT_MIN ) {
         p->add_msg_player_or_npc( m_bad,
                                   _( "You need to hold or wear %s to play it." ),
                                   _( "<npcname> needs to hold or wear %s to play it." ),
                                   it.display_name() );
         it.active = false;
         return std::nullopt;
     }
     // At speed this low you can't coordinate your actions well enough to play the instrument
     if( p->get_speed() <= 25 + speed_penalty ) {
         p->add_msg_player_or_npc( m_bad,
                                   _( "You feel too weak to play your %s." ),
                                   _( "<npcname> feels too weak to play their %s." ),
                                   it.display_name() );
         it.active = false;
         return std::nullopt;
     }
     // We can play the music now
     if( !p->is_npc() ) {
         music::activate_music_id( music::music_id::instrument );
     }
     if( p->get_effect_int( effect_playing_instrument ) <= speed_penalty ) {
         // Only re-apply the effect if it wouldn't lower the intensity
         p->add_effect( effect_playing_instrument, 2_turns, false, speed_penalty );
     }
     std::string desc = "music";
     /** @EFFECT_PER increases morale bonus when playing an instrument */
     const int morale_effect = fun + fun_bonus * p->per_cur;
     if( morale_effect >= 0 && calendar::once_every( description_frequency ) ) {
         if( !player_descriptions.empty() && p->is_avatar() ) {
             desc = random_entry( player_descriptions ).translated();
         } else if( !npc_descriptions.empty() && p->is_npc() ) {
             //~ %1$s: npc name, %2$s: npc action description
             desc = string_format( pgettext( "play music", "%1$s %2$s" ), p->disp_name( false ),
                                   random_entry( npc_descriptions ) );
         }
     } else if( morale_effect < 0 && calendar::once_every( 1_minutes ) ) {
         // No musical skills = possible morale penalty
         if( p->is_avatar() ) {
             desc = _( "You produce an annoying sound." );
         } else {
             desc = string_format( _( "%s produces an annoying sound." ), p->disp_name( false ) );
         }
     }
     if( morale_effect >= 0 ) {
         sounds::sound( p->pos(), volume, sounds::sound_t::music, desc, true, "musical_instrument",
                        it.typeId().str() );
     } else {
         sounds::sound( p->pos(), volume, sounds::sound_t::music, desc, true, "musical_instrument_bad",
                        it.typeId().str() );
     }
     if( !p->has_effect( effect_music ) && p->can_hear( p->pos(), volume ) ) {
         // Sound code doesn't describe noises at the player position
         if( p->is_avatar() && desc != "music" ) {
             add_msg( m_info, desc );
         }
         p->add_effect( effect_music, 1_turns );
         const int sign = morale_effect > 0 ? 1 : -1;
         p->add_morale( MORALE_MUSIC, sign, morale_effect, 5_minutes, 2_minutes, true );
     }
     return 0;
 }
References _, music::activate_music_id(), item::active, Creature::add_effect(), Character::add_morale(), add_msg(), Character::add_msg_player_or_npc(), Character::can_hear(), music::deactivate_music_id(), description_frequency, Character::disp_name(), item::display_name(), effect_asthma, effect_music, effect_playing_instrument, effect_sleep, effect_stunned, fun, fun_bonus, Creature::get_effect_int(), Character::get_item_position(), Character::get_speed(), Creature::has_effect(), music::instrument, music::is_active_music_id(), Creature::is_avatar(), Character::is_mounted(), Character::is_npc(), Creature::is_underwater(), m_bad, m_info, MORALE_MUSIC, sounds::music, npc_descriptions, calendar::once_every(), Character::per_cur, pgettext, player_descriptions, Creature::pos(), random_entry(), iexamine::sign(), sounds::sound(), speed_penalty, string_id< T >::str(), string_format(), item::typeId(), and volume.
Member Data Documentation
description_frequency
time_duration musical_instrument_actor::description_frequency = 0_turns
Display description once per this duration (calendar::once_every).
Definition at line 672 of file iuse_actor.h.
Referenced by load(), and use().
fun
int musical_instrument_actor::fun = 0
Base morale bonus/penalty.
Definition at line 656 of file iuse_actor.h.
Referenced by load(), and use().
fun_bonus
int musical_instrument_actor::fun_bonus = 0
Morale bonus scaling (off current perception)
Definition at line 660 of file iuse_actor.h.
Referenced by load(), and use().
npc_descriptions
std::vector<translation> musical_instrument_actor::npc_descriptions
List of sound descriptions for NPCs.
Definition at line 668 of file iuse_actor.h.
Referenced by load(), and use().
player_descriptions
std::vector<translation> musical_instrument_actor::player_descriptions
List of sound descriptions for players.
Definition at line 664 of file iuse_actor.h.
Referenced by load(), and use().
speed_penalty
int musical_instrument_actor::speed_penalty = 0
Speed penalty when playing the instrument.
Definition at line 648 of file iuse_actor.h.
Referenced by load(), and use().
volume
int musical_instrument_actor::volume = 0
Volume of the music played.
Definition at line 652 of file iuse_actor.h.
Referenced by load(), and use().
The documentation for this class was generated from the following files:
src/iuse_actor.h
src/iuse_actor.cpp