Cataclysm DDA: blueprint_options Class Reference
blueprint_options Class Reference
#include <clzones.h>
Public Member Functions
blueprint_options ()=default
blueprint_options (std::string mark, construction_group_str_id const &group, construction_id const &index)
std::string get_mark () const override
construction_id get_index () const
bool has_options () const override
construction_id get_final_construction (const std::vector< construction > &list_constructions, const construction_id &idx, std::set< construction_id > &skip_index)
bool query_at_creation () override
bool query () override
std::string get_zone_name_suggestion () const override
std::vector< std::pair< std::string, std::string > > get_descriptions () const override
void serialize (JsonOut &json) const override
void deserialize (const JsonObject &jo_zone) override
Public Member Functions inherited from zone_options
virtual ~zone_options ()=default
Public Member Functions inherited from mark_option
virtual ~mark_option ()=default
Private Types
enum query_con_result { canceled , successful , changed }
Private Member Functions
query_con_result query_con ()
Private Attributes
std::string mark
construction_group_str_id group = construction_group_str_id::NULL_ID()
construction_id index
Additional Inherited Members
Static Public Member Functions inherited from zone_options
static shared_ptr_fast< zone_options > create (const zone_type_id &type)
static bool is_valid (const zone_type_id &type, const zone_options &options)
Detailed Description
Definition at line 163 of file clzones.h.
Member Enumeration Documentation
query_con_result
enum blueprint_options::query_con_result private
Enumerator
canceled
successful
changed
Definition at line 171 of file clzones.h.
{
             canceled,
             successful,
             changed,
         };
Constructor & Destructor Documentation
blueprint_options() [1/2]
blueprint_options::blueprint_options () default
blueprint_options() [2/2]
blueprint_options::blueprint_options (std::string mark, construction_group_str_id const & group, construction_id const & index) inline
Definition at line 181 of file clzones.h.
             : mark( std::move( mark ) ), group( group ), index( index ) {
         }
Member Function Documentation
deserialize()
void blueprint_options::deserialize (const JsonObject & jo_zone) override virtual
Reimplemented from zone_options.
Definition at line 507 of file clzones.cpp.
 {
     jo_zone.read( "mark", mark );
     jo_zone.read( "group", group );
     if( jo_zone.has_int( "index" ) ) {
         // Oops, saved incorrectly as an int id by legacy code. Just load it and hope for the best
         index = construction_id( jo_zone.get_int( "index" ) );
     } else {
         index = construction_str_id( jo_zone.get_string( "index" ) ).id();
     }
 }
References JsonObject::get_int(), JsonObject::get_string(), group, JsonObject::has_int(), string_id< T >::id(), index, mark, and JsonObject::read().
get_descriptions()
std::vector< std::pair< std::string, std::string > > blueprint_options::get_descriptions () const override virtual
Reimplemented from zone_options.
Definition at line 450 of file clzones.cpp.
 {
     std::vector<std::pair<std::string, std::string>> options =
                 std::vector<std::pair<std::string, std::string>>();
     options.emplace_back( _( "Construct: " ),
                           group ? group->name() : _( "No Construction" ) );
     return options;
 }
References _, group, construction_group::name(), and PATH_INFO::options().
get_final_construction()
construction_id blueprint_options::get_final_construction (const std::vector< construction > & list_constructions, const construction_id & idx, std::set< construction_id > & skip_index)
Definition at line 208 of file clzones.cpp.
 {
     const construction &con = idx.obj();
     if( con.post_terrain.empty() ) {
         return idx;
     }
     for( int i = 0; i < static_cast<int>( list_constructions.size() ); ++i ) {
         if( construction_id( i ) == idx || skip_index.find( construction_id( i ) ) != skip_index.end() ) {
             continue;
         }
         const construction &con_next = list_constructions[i];
         if( con.group == con_next.group &&
             con.post_terrain == con_next.pre_terrain ) {
             skip_index.insert( idx );
             return get_final_construction( list_constructions, construction_id( i ), skip_index );
         }
     }
     return idx;
 }
References construction::group, int_id< T >::obj(), construction::post_terrain, and construction::pre_terrain.
Referenced by query_con().
get_index()
construction_id blueprint_options::get_index () const inline
Definition at line 189 of file clzones.h.
{
             return index;
         }
References index.
get_mark()
std::string blueprint_options::get_mark () const inline override virtual
Implements mark_option.
Definition at line 186 of file clzones.h.
{
             return mark;
         }
References mark.
get_zone_name_suggestion()
std::string blueprint_options::get_zone_name_suggestion () const override virtual
Reimplemented from zone_options.
Definition at line 408 of file clzones.cpp.
 {
     if( group ) {
         return group->name();
     }
     return _( "No construction" );
 }
References _, group, and construction_group::name().
has_options()
bool blueprint_options::has_options () const inline override virtual
Reimplemented from zone_options.
Definition at line 193 of file clzones.h.
{
             return true;
         }
query()
bool blueprint_options::query () override virtual
Reimplemented from zone_options.
Definition at line 383 of file clzones.cpp.
 {
     return query_con() == changed;
 }
References changed, and query_con().
query_at_creation()
bool blueprint_options::query_at_creation () override virtual
Reimplemented from zone_options.
Definition at line 358 of file clzones.cpp.
 {
     return query_con() != canceled;
 }
References canceled, and query_con().
query_con()
blueprint_options::query_con_result blueprint_options::query_con () private
Definition at line 234 of file clzones.cpp.
 {
     construction_id con_index = construction_menu( true );
     if( con_index.is_valid() ) {
         const std::vector<construction> &list_constructions = get_constructions();
         std::set<construction_id> skip_index;
         con_index = get_final_construction( list_constructions, con_index, skip_index );
         const construction &chosen = con_index.obj();
         const construction_group_str_id &chosen_group = chosen.group;
         const std::string &chosen_mark = chosen.post_terrain;
         if( con_index != index || chosen_group != group || chosen_mark != mark ) {
             group = chosen_group;
             mark = chosen_mark;
             index = con_index;
             return changed;
         } else {
             return successful;
         }
     } else {
         return canceled;
     }
 }
References canceled, changed, construction_menu(), get_constructions(), get_final_construction(), group, construction::group, index, int_id< T >::is_valid(), mark, int_id< T >::obj(), construction::post_terrain, and successful.
Referenced by query(), and query_at_creation().
serialize()
void blueprint_options::serialize (JsonOut & json) const override virtual
Reimplemented from zone_options.
Definition at line 500 of file clzones.cpp.
 {
     json.member( "mark", mark );
     json.member( "group", group );
     json.member( "index", index.id() );
 }
References group, int_id< T >::id(), index, mark, and JsonOut::member().
Member Data Documentation
group
construction_group_str_id blueprint_options::group = construction_group_str_id::NULL_ID() private
Definition at line 168 of file clzones.h.
Referenced by deserialize(), get_descriptions(), get_zone_name_suggestion(), query_con(), and serialize().
index
construction_id blueprint_options::index private
Definition at line 169 of file clzones.h.
Referenced by deserialize(), get_index(), query_con(), and serialize().
mark
std::string blueprint_options::mark private
Definition at line 167 of file clzones.h.
Referenced by deserialize(), get_mark(), query_con(), and serialize().
The documentation for this class was generated from the following files:
src/clzones.h
src/clzones.cpp