Cataclysm DDA: units::quantity< V, U > Class Template Reference
units::quantity< V, U > Class Template Reference
#include <units.h>
Public Types
using value_type = V
using unit_type = U
using this_type = quantity< value_type, unit_type >
Public Member Functions
constexpr quantity ()
Create an empty quantity - its value_ is value initialized.
constexpr quantity (const value_type &v, unit_type)
Construct from value.
template<typename other_value_type >
constexpr quantity (const quantity< other_value_type, unit_type > &other)
Conversion from other value type, e.g.
constexpr const value_type & value () const
Access the raw dimensionless value.
constexpr this_type operator- () const
void serialize (JsonOut &jsout) const
void deserialize (const JsonValue &jv)
constexpr bool operator== (const this_type &rhs) const
The usual comparators, they compare the base value only.
constexpr bool operator!= (const this_type &rhs) const
constexpr bool operator< (const this_type &rhs) const
constexpr bool operator>= (const this_type &rhs) const
constexpr bool operator> (const this_type &rhs) const
constexpr bool operator<= (const this_type &rhs) const
template<typename other_value_type >
constexpr quantity< decltype(std::declval< value_type >)+std::declval< other_value_type >)), unit_type > operator+ (const quantity< other_value_type, unit_type > &rhs) const
Addition and subtraction of quantities of the same unit type.
template<typename other_value_type >
constexpr quantity< decltype(std::declval< value_type >)+std::declval< other_value_type >)), unit_type > operator- (const quantity< other_value_type, unit_type > &rhs) const
template<typename other_value_type >
this_type & operator+= (const quantity< other_value_type, unit_type > &rhs)
template<typename other_value_type >
this_type & operator-= (const quantity< other_value_type, unit_type > &rhs)
Private Attributes
value_type value_
Detailed Description
template<typename V, typename U>
class units::quantity< V, U >
Definition at line 28 of file units.h.
Member Typedef Documentation
this_type
template<typename V , typename U > using units::quantity< V, U >::this_type = quantity<value_type, unit_type>
Definition at line 33 of file units.h.
unit_type
template<typename V , typename U > using units::quantity< V, U >::unit_type = U
Definition at line 32 of file units.h.
value_type
template<typename V , typename U > using units::quantity< V, U >::value_type = V
Definition at line 31 of file units.h.
Constructor & Destructor Documentation
quantity() [1/3]
template<typename V , typename U > constexpr units::quantity< V, U >::quantity () inline constexpr
Create an empty quantity - its value_ is value initialized.
It does not need an explicitly named unit, it's always 0: 0 l == 0 ml == 0 Ml.
Definition at line 39 of file units.h.
                              : value_() {
         }
quantity() [2/3]
template<typename V , typename U > constexpr units::quantity< V, U >::quantity (const value_type & v, unit_type) inline constexpr
Construct from value.
This is supposed to be wrapped into a static function (e.g. from_liter(int)) to provide context.
Definition at line 45 of file units.h.
                                                              : value_( v ) {
         }
quantity() [3/3]
template<typename V , typename U > template<typename other_value_type > constexpr units::quantity< V, U >::quantity (const quantity< other_value_type, unit_type > & other) inline constexpr
Conversion from other value type, e.g.
from quantity<int, foo> to quantity<float, foo>. The unit type stays the same!
Definition at line 53 of file units.h.
                                                                                  :
             value_( other.value() ) {
         }
References other.
Member Function Documentation
deserialize()
void units::angle::deserialize (const JsonValue & jv)
Definition at line 21 of file units.cpp.
 {
     *this = read_from_json_string( jv, units::volume_units );
 }
References read_from_json_string(), and units::volume_units.
operator!=()
template<typename V , typename U > constexpr bool units::quantity< V, U >::operator!= (const this_type & rhs) const inline constexpr
Definition at line 71 of file units.h.
{
             return !operator==( rhs );
         }
References units::quantity< V, U >::operator==().
operator+()
template<typename V , typename U > template<typename other_value_type > constexpr quantity< decltype(std::declval<value_type>) + std::declval<other_value_type>)), unit_type > units::quantity< V, U >::operator+ (const quantity< other_value_type, unit_type > & rhs) const inline constexpr
Addition and subtraction of quantities of the same unit type.
Result is a quantity with the same unit as the input. Functions are templated to allow combining quantities with different value_type, e.g.
quantity<int, foo> a = ...;
quantity<double, foo> b = ...;
auto sum = a + b;
static_assert(std::is_same<decltype(sum), quantity<double, foo>>::value);
Note that += and -= accept any type as value_type for the other operand, but they convert this back to the type of the right hand, like in int a; a += 0.4;
quantity<int, foo> a(10, foo{});
quantity<double, foo> b(0.5, foo{});
a += b;
cata_assert(a == quantity<int, foo>(10 + 0.5, foo{}));
cata_assert(a == quantity<int, foo>(10, foo{}));
Definition at line 113 of file units.h.
{
             return { value_ + rhs.value(), unit_type{} };
         }
References units::quantity< V, U >::value(), and units::quantity< V, U >::value_.
operator+=()
template<typename V , typename U > template<typename other_value_type > this_type& units::quantity< V, U >::operator+= (const quantity< other_value_type, unit_type > & rhs) inline
Definition at line 124 of file units.h.
{
             value_ += rhs.value();
             return *this;
         }
References units::quantity< V, U >::value(), and units::quantity< V, U >::value_.
operator-() [1/2]
template<typename V , typename U > constexpr this_type units::quantity< V, U >::operator- () const inline constexpr
Definition at line 135 of file units.h.
{
             return this_type( -value_, unit_type{} );
         }
References units::quantity< V, U >::value_.
operator-() [2/2]
template<typename V , typename U > template<typename other_value_type > constexpr quantity< decltype(std::declval<value_type>) + std::declval<other_value_type>)), unit_type > units::quantity< V, U >::operator- (const quantity< other_value_type, unit_type > & rhs) const inline constexpr
Definition at line 119 of file units.h.
{
             return { value_ - rhs.value(), unit_type{} };
         }
References units::quantity< V, U >::value(), and units::quantity< V, U >::value_.
operator-=()
template<typename V , typename U > template<typename other_value_type > this_type& units::quantity< V, U >::operator-= (const quantity< other_value_type, unit_type > & rhs) inline
Definition at line 129 of file units.h.
{
             value_ -= rhs.value();
             return *this;
         }
References units::quantity< V, U >::value(), and units::quantity< V, U >::value_.
operator<()
template<typename V , typename U > constexpr bool units::quantity< V, U >::operator< (const this_type & rhs) const inline constexpr
Definition at line 74 of file units.h.
{
             return value_ < rhs.value_;
         }
References units::quantity< V, U >::value_.
Referenced by units::quantity< V, U >::operator>=().
operator<=()
template<typename V , typename U > constexpr bool units::quantity< V, U >::operator<= (const this_type & rhs) const inline constexpr
Definition at line 83 of file units.h.
{
             return !operator>( rhs );
         }
References units::quantity< V, U >::operator>().
operator==()
template<typename V , typename U > constexpr bool units::quantity< V, U >::operator== (const this_type & rhs) const inline constexpr
The usual comparators, they compare the base value only.
Definition at line 68 of file units.h.
{
             return value_ == rhs.value_;
         }
References units::quantity< V, U >::value_.
Referenced by units::quantity< V, U >::operator!=().
operator>()
template<typename V , typename U > constexpr bool units::quantity< V, U >::operator> (const this_type & rhs) const inline constexpr
Definition at line 80 of file units.h.
{
             return value_ > rhs.value_;
         }
References units::quantity< V, U >::value_.
Referenced by units::quantity< V, U >::operator<=().
operator>=()
template<typename V , typename U > constexpr bool units::quantity< V, U >::operator>= (const this_type & rhs) const inline constexpr
Definition at line 77 of file units.h.
{
             return !operator<( rhs );
         }
References units::quantity< V, U >::operator<().
serialize()
void units::angle::serialize (JsonOut & jsout) const
Definition at line 11 of file units.cpp.
 {
     if( value_ % 1000 == 0 ) {
         jsout.write( string_format( "%d L", value_ / 1000 ) );
     } else {
         jsout.write( string_format( "%d ml", value_ ) );
     }
 }
References string_format(), units::quantity< V, U >::value_, and JsonOut::write().
value()
template<typename V , typename U > constexpr const value_type& units::quantity< V, U >::value () const inline constexpr
Access the raw dimensionless value.
Use it in a properly named wrapper function only.
Definition at line 60 of file units.h.
{
             return value_;
         }
References units::quantity< V, U >::value_.
Referenced by mattack::absorb_items(), item::basic_info(), armor_portion_data::calc_encumbrance(), comestible_inventory_preset::comestible_inventory_preset(), salvage_actor::cut_up(), damage_instance::di_considering_length(), islot_ammo::dispersion_considering_length(), divide_round_up(), units::fabs(), advanced_inventory::fill_lists_with_pane_items(), units::fmod(), item_pocket::general_info(), basecamp::get_equipment(), conditional_t::get_get_dbl(), widget::get_var_value(), basecamp::give_equipment(), units::operator%(), advanced_inv_sorter::operator()(), units::operator*(), units::quantity< V, U >::operator+(), units::quantity< V, U >::operator+=(), units::quantity< V, U >::operator-(), units::quantity< V, U >::operator-=(), units::operator/(), units::operator<<(), display::power_balance_text_color(), advanced_inventory::print_items(), inventory::remove_randomly_by_volume(), rng_float(), vehicle::slowdown(), Character::throw_item(), units::to_celsius_delta(), units::to_gram(), units::to_joule_per_gram(), units::to_kelvin(), units::to_kelvin_delta(), units::to_kilogram(), units::to_liter(), units::to_milligram(), units::to_radians(), item::update_link_traits(), vol_to_info(), vol_to_string(), item::weight(), and weight_to_string().
Member Data Documentation
value_
template<typename V , typename U > value_type units::quantity< V, U >::value_ private
Definition at line 143 of file units.h.
Referenced by units::quantity< V, U >::operator+(), units::quantity< V, U >::operator+=(), units::quantity< V, U >::operator-(), units::quantity< V, U >::operator-=(), units::quantity< V, U >::operator<(), units::quantity< V, U >::operator==(), units::quantity< V, U >::operator>(), units::quantity< V, U >::serialize(), and units::quantity< V, U >::value().
The documentation for this class was generated from the following files:
src/units.h
src/units.cpp