Cataclysm DDA: jmapgen_nested::neighbor_join_check Class Reference
jmapgen_nested::neighbor_join_check Class Reference
Public Member Functions
neighbor_join_check (const JsonObject &jsi)
void check (const std::string_view, const mapgen_parameters &) const
bool test (const mapgendata &dat) const
Private Attributes
std::unordered_map< cube_direction, cata::flat_set< std::string > > neighbors
Detailed Description
Definition at line 3577 of file mapgen.cpp.
Constructor & Destructor Documentation
neighbor_join_check()
jmapgen_nested::neighbor_join_check::neighbor_join_check (const JsonObject & jsi) inline explicit
Definition at line 3582 of file mapgen.cpp.
{
                     for( cube_direction dir : all_enum_values<cube_direction>() ) {
                         cata::flat_set<std::string> dir_neighbors =
                             jsi.get_tags<std::string, cata::flat_set<std::string>>(
                                 io::enum_to_string( dir ) );
                         if( !dir_neighbors.empty() ) {
                             neighbors[dir] = std::move( dir_neighbors );
                         }
                     }
                 }
References io::enum_to_string(), JsonObject::get_tags(), mapgen_defer::jsi, and neighbors.
Member Function Documentation
check()
void jmapgen_nested::neighbor_join_check::check (const std::string_view , const mapgen_parameters &) const inline
Definition at line 3593 of file mapgen.cpp.
{
                     // TODO: check join ids are valid
                 }
Referenced by jmapgen_nested::check().
test()
bool jmapgen_nested::neighbor_join_check::test (const mapgendata & dat) const inline
Definition at line 3597 of file mapgen.cpp.
{
                     for( const std::pair<const cube_direction, cata::flat_set<std::string>> &p :
                          neighbors ) {
                         const cube_direction dir = p.first;
                         const cata::flat_set<std::string> &allowed_joins = p.second;
                         cata_assert( !allowed_joins.empty() );
                         bool this_direction_has_join = false;
                         for( const std::string &allowed_join : allowed_joins ) {
                             this_direction_has_join |= dat.has_join( dir, allowed_join );
                         }
                         if( !this_direction_has_join ) {
                             return false;
                         }
                     }
                     return true;
                 }
References cata_assert, mapgendata::has_join(), and neighbors.
Referenced by jmapgen_nested::get_entries().
Member Data Documentation
neighbors
std::unordered_map<cube_direction, cata::flat_set<std::string> > jmapgen_nested::neighbor_join_check::neighbors private
Definition at line 3580 of file mapgen.cpp.
Referenced by neighbor_join_check(), and test().
The documentation for this class was generated from the following file:
src/mapgen.cpp