Cataclysm DDA: Messages::dialog Class Reference
Messages::dialog Class Reference
Public Member Functions
dialog ()
void run ()
Private Member Functions
void init (ui_adaptor &ui)
void show ()
void input ()
void do_filter (const std::string &filter_str)
Static Private Member Functions
static std::vector< std::string > filter_help_text (int width)
Private Attributes
const nc_color border_color
const nc_color filter_color
const nc_color time_color
const nc_color bracket_color
const nc_color filter_help_color
int time_width = 0
int msg_width = 0
size_t max_lines = 0
int w_x = 0
int w_y = 0
int w_width = 0
int w_height = 0
catacurses::window w
int w_fh_x = 0
int w_fh_y = 0
int w_fh_width = 0
int w_fh_height = 0
catacurses::window w_filter_help
std::vector< std::string > help_text
string_input_popup filter
bool filtering = false
std::string filter_str
input_context ctxt
std::vector< std::pair< size_t, std::string > > folded_all
std::vector< size_t > folded_filtered
size_t offset = 0
bool canceled = false
bool errored = false
bool first_init = true
Static Private Attributes
static constexpr int border_width = 1
static constexpr int padding_width = 1
Detailed Description
Definition at line 515 of file messages.cpp.
Constructor & Destructor Documentation
dialog()
Messages::dialog::dialog ()
Definition at line 581 of file messages.cpp.
     : border_color( BORDER_COLOR ), filter_color( c_white ),
       time_color( c_light_blue ), bracket_color( c_dark_gray ),
       filter_help_color( c_cyan )
 {
 }
Member Function Documentation
do_filter()
void Messages::dialog::do_filter (const std::string & filter_str) private
Definition at line 770 of file messages.cpp.
 {
     // Split the search string into type and text
     bool has_type_filter = false;
     game_message_type filter_type = m_neutral;
     std::string filter_text;
     const size_t colon = filter_str.find( ':' );
     if( colon != std::string::npos ) {
         has_type_filter = msg_type_from_name( filter_type, filter_str.substr( 0, colon ) );
         filter_text = filter_str.substr( colon + 1 );
     } else {
         filter_text = filter_str;
     }
     // Start filtering the log
     folded_filtered.clear();
     for( size_t folded_ind = 0; folded_ind < folded_all.size(); ) {
         const size_t msg_ind = folded_all[folded_ind].first;
         const game_message &msg = player_messages.history( msg_ind );
         const bool match = ( !has_type_filter || filter_type == msg.type ) &&
                            ci_find_substr( remove_color_tags( msg.get_with_count() ), filter_text ) >= 0;
         // Always advance the index, but only add to filtered list if the original message matches
         for( ; folded_ind < folded_all.size() && folded_all[folded_ind].first == msg_ind; ++folded_ind ) {
             if( match ) {
                 folded_filtered.emplace_back( folded_ind );
             }
         }
     }
     // Reset view
     if( log_from_top || max_lines > folded_filtered.size() ) {
         offset = 0;
     } else {
         offset = folded_filtered.size() - max_lines;
     }
 }
References ci_find_substr(), anonymous_namespace{messages.cpp}::messages_impl::history(), log_from_top, m_neutral, msg_type_from_name(), anonymous_namespace{messages.cpp}::player_messages, and remove_color_tags().
filter_help_text()
std::vector< std::string > Messages::dialog::filter_help_text (int width) static private
Definition at line 876 of file messages.cpp.
 {
     const char *const &help_fmt = _(
                                       "<color_light_gray>The default is to search the entire message log.  "
                                       "Use message-types as prefixes followed by (:) to filter more specific.\n"
                                       "Valid message-type values are:</color> %s\n"
                                       "\n"
                                       "<color_white>Examples:</color>\n"
                                       "  <color_light_green>good</color><color_white>:mutation\n"
                                       "  :you pick up: 1</color>\n"
                                       "  <color_light_red>bad</color><color_white>:</color>\n"
                                       "\n"
                                   );
     std::string type_text;
     const auto &type_list = msg_type_and_names();
     for( auto it = type_list.begin(); it != type_list.end(); ++it ) {
         // Skip m_debug outside debug mode (but allow searching for it)
         if( debug_mode || it->first != m_debug ) {
             const std::string &col_name = get_all_colors().get_name( msgtype_to_color( it->first ) );
             auto next_it = std::next( it );
             // Skip m_debug outside debug mode
             if( !debug_mode && next_it != type_list.end() && next_it->first == m_debug ) {
                 next_it = std::next( next_it );
             }
             if( next_it != type_list.end() ) {
                 //~ the 2nd %s is a type name, this is used to format a list of type names
                 type_text += string_format( pgettext( "message log", "<color_%s>%s</color>, " ),
                                             col_name, pgettext( "message type", it->second ) );
             } else {
                 //~ the 2nd %s is a type name, this is used to format the last type name in a list of type names
                 type_text += string_format( pgettext( "message log", "<color_%s>%s</color>." ),
                                             col_name, pgettext( "message type", it->second ) );
             }
         }
     }
     return foldstring( string_format( help_fmt, type_text ), width );
 }
References _, debug_mode, foldstring(), get_all_colors(), color_manager::get_name(), m_debug, msg_type_and_names(), msgtype_to_color(), pgettext, and string_format().
init()
void Messages::dialog::init (ui_adaptor & ui) private
Definition at line 588 of file messages.cpp.
 {
     const int left_panel_width = panel_manager::get_manager().get_width_left();
     const int right_panel_width = panel_manager::get_manager().get_width_right();
     w_height = TERMY;
     w_y = 0;
     // try to center and not obscure sidebar
     w_x = std::max( left_panel_width, right_panel_width );
     w_width = TERMX - 2 * w_x;
     if( w_width < w_height * 3 ) {
         // try not to obscure sidebar
         w_x = left_panel_width;
         w_width = TERMX - left_panel_width - right_panel_width;
     }
     w = catacurses::newwin( w_height, w_width, point( w_x, w_y ) );
     if( first_init ) {
         ctxt = input_context( "MESSAGE_LOG" );
         ctxt.register_action( "UP", to_translation( "Scroll up" ) );
         ctxt.register_action( "DOWN", to_translation( "Scroll down" ) );
         ctxt.register_action( "PAGE_UP" );
         ctxt.register_action( "PAGE_DOWN" );
         ctxt.register_action( "FILTER" );
         ctxt.register_action( "RESET_FILTER" );
         ctxt.register_action( "QUIT" );
         ctxt.register_action( "HELP_KEYBINDINGS" );
         ctxt.register_action( "SCROLL_UP" );
         ctxt.register_action( "SCROLL_DOWN" );
         // Calculate time string display width. The translated strings are expected to
         // be aligned, so we choose an arbitrary duration here to calculate the width.
         time_width = utf8_width( to_string_clipped( 1_turns, clipped_align::right ) );
     }
     if( border_width * 2 + time_width + padding_width >= w_width ||
         border_width * 2 >= w_height ) {
         errored = true;
         return;
     }
     msg_width = w_width - border_width * 2 - time_width - padding_width;
     max_lines = static_cast<size_t>( w_height - border_width * 2 );
     // Initialize filter help text and window
     w_fh_width = w_width;
     w_fh_x = w_x;
     help_text = filter_help_text( w_fh_width - border_width * 2 );
     w_fh_height = help_text.size() + border_width * 2;
     w_fh_y = w_y + w_height - w_fh_height;
     w_filter_help = catacurses::newwin( w_fh_height, w_fh_width, point( w_fh_x, w_fh_y ) );
     // Initialize filter input
     filter.window( w_filter_help, point( border_width + 2, w_fh_height - 1 ),
                    w_fh_width - border_width - 2 );
     // Initialize folded messages
     folded_all.clear();
     folded_filtered.clear();
     const size_t msg_count = size();
     for( size_t ind = 0; ind < msg_count; ++ind ) {
         const size_t msg_ind = log_from_top ? ind : msg_count - 1 - ind;
         const game_message &msg = player_messages.history( msg_ind );
         const auto &folded = foldstring( msg.get_with_count(), msg_width );
         for( const auto &it : folded ) {
             folded_filtered.emplace_back( folded_all.size() );
             folded_all.emplace_back( msg_ind, it );
         }
     }
     do_filter( filter_str );
     ui.position_from_window( w );
     first_init = false;
 }
References filter, foldstring(), panel_manager::get_manager(), panel_manager::get_width_left(), panel_manager::get_width_right(), anonymous_namespace{messages.cpp}::messages_impl::history(), log_from_top, max(), catacurses::newwin(), anonymous_namespace{messages.cpp}::player_messages, right, Messages::size(), TERMX, TERMY, to_string_clipped(), to_translation(), and utf8_width().
input()
void Messages::dialog::input () private
Definition at line 808 of file messages.cpp.
 {
     canceled = false;
     if( filtering ) {
         filter.query( false );
         if( filter.confirmed() || filter.canceled() ) {
             filtering = false;
         }
         if( !filter.canceled() ) {
             const std::string &new_filter_str = filter.text();
             if( new_filter_str != filter_str ) {
                 filter_str = new_filter_str;
                 do_filter( filter_str );
             }
         } else {
             filter.text( filter_str );
         }
     } else {
         const std::string &action = ctxt.handle_input();
         if( ( action == "DOWN" || action == "SCROLL_DOWN" ) &&
             offset + max_lines < folded_filtered.size() ) {
             ++offset;
         } else if( ( action == "UP" || action == "SCROLL_UP" ) && offset > 0 ) {
             --offset;
         } else if( action == "PAGE_DOWN" ) {
             if( offset + max_lines * 2 <= folded_filtered.size() ) {
                 offset += max_lines;
             } else if( max_lines <= folded_filtered.size() ) {
                 offset = folded_filtered.size() - max_lines;
             } else {
                 offset = 0;
             }
         } else if( action == "PAGE_UP" ) {
             if( offset >= max_lines ) {
                 offset -= max_lines;
             } else {
                 offset = 0;
             }
         } else if( action == "FILTER" ) {
             filtering = true;
         } else if( action == "RESET_FILTER" ) {
             filter_str.clear();
             filter.text( filter_str );
             do_filter( filter_str );
         } else if( action == "QUIT" ) {
             canceled = true;
         }
     }
 }
References action, and filter.
run()
void Messages::dialog::run ()
Definition at line 859 of file messages.cpp.
 {
     ui_adaptor ui;
     ui.on_screen_resize( [this]( ui_adaptor & ui ) {
         init( ui );
     } );
     ui.mark_resize();
     ui.on_redraw( [this]( const ui_adaptor & ) {
         show();
     } );
     while( !errored && !canceled ) {
         ui_manager::redraw();
         input();
     }
 }
References init, ui_manager::redraw(), and show.
Referenced by Messages::display_messages().
show()
void Messages::dialog::show () private
Definition at line 665 of file messages.cpp.
 {
     werase( w );
     draw_border( w, border_color );
     scrollbar()
     .offset_x( 0 )
     .offset_y( border_width )
     .content_size( folded_filtered.size() )
     .viewport_pos( offset )
     .viewport_size( max_lines )
     .apply( w );
     // Range of window lines to print
     size_t line_from = 0;
     size_t line_to;
     if( offset < folded_filtered.size() ) {
         line_to = std::min( max_lines, folded_filtered.size() - offset );
     } else {
         line_to = 0;
     }
     if( !log_from_top ) {
         // Always print from new to old
         std::swap( line_from, line_to );
     }
     std::string prev_time_str;
     bool printing_range = false;
     for( size_t line = line_from; line != line_to; ) {
         // Decrement here if printing from bottom to get the correct line number
         if( !log_from_top ) {
             --line;
         }
         const size_t folded_ind = offset + line;
         const size_t msg_ind = folded_all[folded_filtered[folded_ind]].first;
         const game_message &msg = player_messages.history( msg_ind );
         nc_color col = msgtype_to_color( msg.type, false );
         // Print current line
         print_colored_text( w, point( border_width + time_width + padding_width, border_width + line ),
                             col, col, folded_all[folded_filtered[folded_ind]].second );
         // Generate aligned time string
         const time_point msg_time = msg.timestamp_in_turns;
         const std::string time_str = to_string_clipped( calendar::turn - msg_time, clipped_align::right );
         if( time_str != prev_time_str ) {
             // Time changed, print time string
             prev_time_str = time_str;
             right_print( w, border_width + line, border_width + msg_width + padding_width,
                          time_color, time_str );
             printing_range = false;
         } else {
             // Print line brackets to mark ranges of time
             if( printing_range ) {
                 const size_t last_line = log_from_top ? line - 1 : line + 1;
                 wattron( w, bracket_color );
                 mvwaddch( w, point( border_width + time_width - 1, border_width + last_line ), LINE_XOXO );
                 wattroff( w, bracket_color );
             }
             wattron( w, bracket_color );
             mvwaddch( w, point( border_width + time_width - 1, border_width + line ),
                       log_from_top ? LINE_XXOO : LINE_OXXO );
             wattroff( w, bracket_color );
             printing_range = true;
         }
         // Decrement for !log_from_top is done at the beginning
         if( log_from_top ) {
             ++line;
         }
     }
     if( filtering ) {
         wnoutrefresh( w );
         // Print the help text
         werase( w_filter_help );
         draw_border( w_filter_help, border_color );
         for( size_t line = 0; line < help_text.size(); ++line ) {
             nc_color col = filter_help_color;
             print_colored_text( w_filter_help, point( border_width, border_width + line ), col, col,
                                 help_text[line] );
         }
         mvwprintz( w_filter_help, point( border_width, w_fh_height - 1 ), border_color, "< " );
         mvwprintz( w_filter_help, point( w_fh_width - border_width - 2, w_fh_height - 1 ), border_color,
                    " >" );
         wnoutrefresh( w_filter_help );
         // This line is preventing this method from being const
         filter.query( false, true ); // Draw only
     } else {
         if( filter_str.empty() ) {
             mvwprintz( w, point( border_width, w_height - 1 ), border_color,
                        _( "< Press %s to filter, %s to reset >" ),
                        ctxt.get_desc( "FILTER" ), ctxt.get_desc( "RESET_FILTER" ) );
         } else {
             mvwprintz( w, point( border_width, w_height - 1 ), border_color, "< %s >", filter_str );
             mvwprintz( w, point( border_width + 2, w_height - 1 ), filter_color, "%s", filter_str );
         }
         wnoutrefresh( w );
     }
 }
References _, scrollbar::apply(), scrollbar::content_size(), draw_border(), filter, anonymous_namespace{messages.cpp}::messages_impl::history(), line(), LINE_OXXO, line_to(), LINE_XOXO, LINE_XXOO, log_from_top, min(), msgtype_to_color(), catacurses::mvwaddch(), mvwprintz(), scrollbar::offset_x(), scrollbar::offset_y(), anonymous_namespace{messages.cpp}::player_messages, print_colored_text(), right, right_print(), second, cata::swap(), to_string_clipped(), calendar::turn, scrollbar::viewport_pos(), scrollbar::viewport_size(), catacurses::wattroff(), catacurses::wattron(), catacurses::werase(), and catacurses::wnoutrefresh().
Member Data Documentation
border_color
const nc_color Messages::dialog::border_color private
Definition at line 527 of file messages.cpp.
border_width
constexpr int Messages::dialog::border_width = 1 static constexpr private
Definition at line 540 of file messages.cpp.
bracket_color
const nc_color Messages::dialog::bracket_color private
Definition at line 530 of file messages.cpp.
canceled
bool Messages::dialog::canceled = false private
Definition at line 574 of file messages.cpp.
ctxt
input_context Messages::dialog::ctxt private
Definition at line 565 of file messages.cpp.
errored
bool Messages::dialog::errored = false private
Definition at line 575 of file messages.cpp.
filter
string_input_popup Messages::dialog::filter private
Definition at line 561 of file messages.cpp.
filter_color
const nc_color Messages::dialog::filter_color private
Definition at line 528 of file messages.cpp.
filter_help_color
const nc_color Messages::dialog::filter_help_color private
Definition at line 531 of file messages.cpp.
filter_str
std::string Messages::dialog::filter_str private
Definition at line 563 of file messages.cpp.
filtering
bool Messages::dialog::filtering = false private
Definition at line 562 of file messages.cpp.
first_init
bool Messages::dialog::first_init = true private
Definition at line 577 of file messages.cpp.
folded_all
std::vector<std::pair<size_t, std::string> > Messages::dialog::folded_all private
Definition at line 568 of file messages.cpp.
folded_filtered
std::vector<size_t> Messages::dialog::folded_filtered private
Definition at line 570 of file messages.cpp.
help_text
std::vector<std::string> Messages::dialog::help_text private
Definition at line 559 of file messages.cpp.
max_lines
size_t Messages::dialog::max_lines = 0 private
Definition at line 545 of file messages.cpp.
msg_width
int Messages::dialog::msg_width = 0 private
Definition at line 543 of file messages.cpp.
offset
size_t Messages::dialog::offset = 0 private
Definition at line 572 of file messages.cpp.
padding_width
constexpr int Messages::dialog::padding_width = 1 static constexpr private
Definition at line 541 of file messages.cpp.
time_color
const nc_color Messages::dialog::time_color private
Definition at line 529 of file messages.cpp.
time_width
int Messages::dialog::time_width = 0 private
Definition at line 542 of file messages.cpp.
w
catacurses::window Messages::dialog::w private
Definition at line 551 of file messages.cpp.
w_fh_height
int Messages::dialog::w_fh_height = 0 private
Definition at line 556 of file messages.cpp.
w_fh_width
int Messages::dialog::w_fh_width = 0 private
Definition at line 555 of file messages.cpp.
w_fh_x
int Messages::dialog::w_fh_x = 0 private
Definition at line 553 of file messages.cpp.
w_fh_y
int Messages::dialog::w_fh_y = 0 private
Definition at line 554 of file messages.cpp.
w_filter_help
catacurses::window Messages::dialog::w_filter_help private
Definition at line 557 of file messages.cpp.
w_height
int Messages::dialog::w_height = 0 private
Definition at line 550 of file messages.cpp.
w_width
int Messages::dialog::w_width = 0 private
Definition at line 549 of file messages.cpp.
w_x
int Messages::dialog::w_x = 0 private
Definition at line 547 of file messages.cpp.
w_y
int Messages::dialog::w_y = 0 private
Definition at line 548 of file messages.cpp.
The documentation for this class was generated from the following file:
src/messages.cpp