Cataclysm DDA: event_statistic Class Reference
event_statistic Class Reference
#include <event_statistics.h>
Classes
class impl
Public Member Functions
cata_variant value (stats_tracker &) const
std::unique_ptr< stats_tracker_state > watch (stats_tracker &) const
void load (const JsonObject &, std::string_view)
void check () const
const translation & description () const
cata_variant_type type () const
monotonically monotonicity () const
Static Public Member Functions
static void load_statistic (const JsonObject &, const std::string &)
static void check_consistency ()
static void reset ()
Public Attributes
string_id< event_statistic > id
std::vector< std::pair< string_id< event_statistic >, mod_id > > src
bool was_loaded = false
Private Attributes
translation description_
cata::clone_ptr< impl > impl_
Detailed Description
Definition at line 71 of file event_statistics.h.
Member Function Documentation
check()
void event_statistic::check () const
Definition at line 1262 of file event_statistics.cpp.
 {
     impl_->check( id.str() );
 }
References impl_.
check_consistency()
void event_statistic::check_consistency () static
Definition at line 109 of file event_statistics.cpp.
 {
     event_statistic_factory.check();
 }
References anonymous_namespace{event_statistics.cpp}::event_statistic_factory.
Referenced by DynamicDataLoader::check_consistency().
description()
const translation& event_statistic::description () const inline
Definition at line 87 of file event_statistics.h.
{
             return description_;
         }
References description_.
Referenced by score::description(), and text_for_requirement().
load()
void event_statistic::load (const JsonObject & jo, std::string_view)
Definition at line 1220 of file event_statistics.cpp.
 {
     std::string type;
     mandatory( jo, was_loaded, "stat_type", type );
     description_.make_plural();
     optional( jo, was_loaded, "description", description_ );
     if( type == "count" ) {
         impl_ = std::make_unique<event_statistic_count>( id, event_source::load( jo ) );
     } else if( type == "total" ) {
         std::string field;
         mandatory( jo, was_loaded, "field", field );
         impl_ = std::make_unique<event_statistic_total>( id, event_source::load( jo ), field );
     } else if( type == "minimum" ) {
         std::string field;
         mandatory( jo, was_loaded, "field", field );
         impl_ = std::make_unique<event_statistic_minimum>( id, event_source::load( jo ), field );
     } else if( type == "maximum" ) {
         std::string field;
         mandatory( jo, was_loaded, "field", field );
         impl_ = std::make_unique<event_statistic_maximum>( id, event_source::load( jo ), field );
     } else if( type == "unique_value" ) {
         std::string field;
         mandatory( jo, was_loaded, "field", field );
         impl_ = std::make_unique<event_statistic_unique_value>(
                     id, event_source::load( jo ), field );
     } else if( type == "first_value" ) {
         std::string field;
         mandatory( jo, was_loaded, "field", field );
         impl_ = std::make_unique<event_statistic_first_value>(
                     id, event_source::load( jo ), field );
     } else if( type == "last_value" ) {
         std::string field;
         mandatory( jo, was_loaded, "field", field );
         impl_ = std::make_unique<event_statistic_last_value>(
                     id, event_source::load( jo ), field );
     } else {
         jo.throw_error( "Invalid stat_type '" + type + "'" );
     }
 }
References description_, field, impl_, event_source::load(), translation::make_plural(), mandatory, optional(), JsonObject::throw_error(), type(), and was_loaded.
load_statistic()
void event_statistic::load_statistic (const JsonObject & jo, const std::string & src) static
Definition at line 104 of file event_statistics.cpp.
 {
     event_statistic_factory.load( jo, src );
 }
References anonymous_namespace{event_statistics.cpp}::event_statistic_factory, and src.
Referenced by DynamicDataLoader::initialize().
monotonicity()
monotonically event_statistic::monotonicity () const
Definition at line 1272 of file event_statistics.cpp.
 {
     return impl_->monotonicity();
 }
References impl_.
Referenced by achievement_requirement::finalize().
reset()
void event_statistic::reset () static
Definition at line 114 of file event_statistics.cpp.
 {
     event_statistic_factory.reset();
 }
References anonymous_namespace{event_statistics.cpp}::event_statistic_factory.
Referenced by DynamicDataLoader::unload_data().
type()
cata_variant_type event_statistic::type () const
Definition at line 1267 of file event_statistics.cpp.
 {
     return impl_->type();
 }
References impl_.
Referenced by achievement_requirement::check(), and load().
value()
cata_variant event_statistic::value (stats_tracker & stats) const
Definition at line 1210 of file event_statistics.cpp.
 {
     return impl_->value( stats );
 }
References impl_.
Referenced by stats_tracker::value_of().
watch()
std::unique_ptr< stats_tracker_state > event_statistic::watch (stats_tracker & stats) const
Definition at line 1215 of file event_statistics.cpp.
 {
     return impl_->watch( stats );
 }
References impl_.
Member Data Documentation
description_
translation event_statistic::description_ private
Definition at line 97 of file event_statistics.h.
Referenced by description(), and load().
id
string_id<event_statistic> event_statistic::id
Definition at line 83 of file event_statistics.h.
impl_
cata::clone_ptr<impl> event_statistic::impl_ private
Definition at line 98 of file event_statistics.h.
Referenced by check(), load(), monotonicity(), type(), value(), and watch().
src
std::vector<std::pair<string_id<event_statistic>, mod_id> > event_statistic::src
Definition at line 84 of file event_statistics.h.
Referenced by load_statistic().
was_loaded
bool event_statistic::was_loaded = false
Definition at line 85 of file event_statistics.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/event_statistics.h
src/event_statistics.cpp