Cataclysm DDA: src/climbing.cpp File Reference
climbing.cpp File Reference
#include "climbing.h"
#include <cstdint>
#include <memory>
#include <set>
#include <utility>
#include "cata_utility.h"
#include "character.h"
#include "creature_tracker.h"
#include "debug.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "generic_factory.h"
#include "init.h"
#include "json_error.h"
#include "map.h"
#include "vpart_position.h"
Classes
struct enum_traits< climbing_aid::category >
Namespaces
anonymous_namespace{climbing.cpp}
io
Functions
template<>
std::string io::enum_to_string< climbing_aid::category > (climbing_aid::category data)
template<typename Lambda >
void for_each_aid_condition (const climbing_aid::condition_list &conditions, const Lambda &func)
template<typename Test >
static void detect_conditions_sub (climbing_aid::condition_list &list, climbing_aid::category category, const Test &test)
Variables
static const climbing_aid_id climbing_aid_default ("default")
generic_factory< climbing_aid > anonymous_namespace{climbing.cpp}::climbing_aid_factory ("climbing_aid")
static climbing_aid::lookup climbing_lookup
static const climbing_aid * climbing_aid_default_ptr = nullptr
Function Documentation
detect_conditions_sub()
template<typename Test > static void detect_conditions_sub (climbing_aid::condition_list & list, climbing_aid::category category, const Test & test) static
Definition at line 309 of file climbing.cpp.
 {
     std::string empty;
     const std::string *flag_already_tested = &empty;
     for( auto &[ flag, aid ] : climbing_lookup[ int( category ) ] ) {
         // climbing_lookup is a multimap, don't test flags twice.
         if( flag == *flag_already_tested ) {
             continue;
         }
         climbing_aid::condition cond = { category, flag };
         if( test( cond ) ) {
             list.emplace_back( cond );
         }
         flag_already_tested = &flag;
     }
 }
References climbing_lookup, and climbing_aid::list().
Referenced by climbing_aid::detect_conditions().
for_each_aid_condition()
template<typename Lambda > void for_each_aid_condition (const climbing_aid::condition_list & conditions, const Lambda & func)
Definition at line 241 of file climbing.cpp.
 {
     for( const climbing_aid::condition &cond : conditions ) {
         if( int( cond.cat ) < int( climbing_lookup.size() ) ) {
             auto &cat = climbing_lookup[ int( cond.cat ) ];
             auto range = cat.equal_range( cond.flag );
             for( auto i = range.first; i != range.second; ++i ) {
                 func( cond, *i->second );
             }
         }
     }
 }
References climbing_lookup.
Referenced by climbing_aid::get_safest(), climbing_aid::list(), and climbing_aid::list_all().
Variable Documentation
climbing_aid_default
const climbing_aid_id climbing_aid_default("default") ("default") static
Referenced by climbing_aid::check_consistency(), and climbing_aid::finalize().
climbing_aid_default_ptr
const climbing_aid* climbing_aid_default_ptr = nullptr static
Definition at line 32 of file climbing.cpp.
Referenced by climbing_aid::finalize(), climbing_aid::get_default(), climbing_aid::get_safest(), climbing_aid::list_all(), and climbing_aid::reset().
climbing_lookup
climbing_aid::lookup climbing_lookup static
Definition at line 30 of file climbing.cpp.
Referenced by detect_conditions_sub(), climbing_aid::finalize(), for_each_aid_condition(), and climbing_aid::reset().