Cataclysm DDA: src/clzones.h File Reference
clzones.h File Reference
#include <cstddef>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "coordinates.h"
#include "cuboid_rectangle.h"
#include "point.h"
#include "translation.h"
#include "type_id.h"
Classes
class zone_type
class zone_options
class mark_option
class plot_options
class blueprint_options
class ignorable_options
class loot_options
class unload_options
class zone_data
These are zones the player can designate.
class zone_manager
Macros
#define CATA_SRC_CLZONES_H
Typedefs
using faction_id = string_id< faction >
Functions
const faction_id your_fac ("your_followers")
void mapgen_place_zone (tripoint const &start, tripoint const &end, zone_type_id const &type, faction_id const &fac=your_fac, std::string const &name={}, std::string const &filter={}, map *pmap=nullptr)
Variables
const std::string type_fac_hash_str = "__FAC__"
constexpr int ACTIVITY_SEARCH_DISTANCE = 60
const std::vector< zone_type_id > ignorable_zone_types
Macro Definition Documentation
CATA_SRC_CLZONES_H
#define CATA_SRC_CLZONES_H
Definition at line 3 of file clzones.h.
Typedef Documentation
faction_id
using faction_id = string_id<faction>
Definition at line 32 of file clzones.h.
Function Documentation
mapgen_place_zone()
void mapgen_place_zone (tripoint const & start, tripoint const & end, zone_type_id const & type, faction_id const & fac = your_fac, std::string const & name = {}, std::string const & filter = {}, map * pmap = nullptr)
Definition at line 1802 of file clzones.cpp.
 {
     zone_manager &mgr = zone_manager::get_manager();
     auto options = zone_options::create( type );
     tripoint const s_ = std::min( start, end );
     tripoint const e_ = std::max( start, end );
     if( type == zone_type_LOOT_CUSTOM || type == zone_type_LOOT_ITEM_GROUP ) {
         if( dynamic_cast<loot_options *>( &*options ) != nullptr ) {
             dynamic_cast<loot_options *>( &*options )->set_mark( filter );
         }
     }
     mgr.add( name, type, fac, false, true, s_, e_, options, false, true, pmap );
 }
References zone_manager::add(), zone_options::create(), keycode::end, filter, zone_manager::get_manager(), max(), min(), om_direction::name(), PATH_INFO::options(), zone_type_LOOT_CUSTOM, and zone_type_LOOT_ITEM_GROUP.
Referenced by jmapgen_zone::apply(), and vehicle::place_zones().
your_fac()
const faction_id your_fac ("your_followers") inline
Referenced by basecamp::deserialize(), zone_data::deserialize(), and game::zones_manager().
Variable Documentation
ACTIVITY_SEARCH_DISTANCE
constexpr int ACTIVITY_SEARCH_DISTANCE = 60 constexpr
Definition at line 37 of file clzones.h.
Referenced by activity_on_turn_move_loot(), add_basecamp_storage_to_loot_zone_list(), unload_loot_activity_actor::do_turn(), npc::execute_action(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_handler(), generic_multi_activity_locations(), get_auto_consume_moves(), and game::zones_manager().
ignorable_zone_types
const std::vector<zone_type_id> ignorable_zone_types extern
Definition at line 83 of file clzones.cpp.
Referenced by activity_on_turn_move_loot(), zone_options::create(), and zone_options::is_valid().
type_fac_hash_str
const std::string type_fac_hash_str = "__FAC__"
Definition at line 34 of file clzones.h.
Referenced by zone_data::make_type_hash(), zone_data::unhash_fac(), and zone_data::unhash_type().