Cataclysm DDA: src/clzones.cpp File Reference
clzones.cpp File Reference
#include "clzones.h"
#include <algorithm>
#include <climits>
#include <functional>
#include <iosfwd>
#include <iterator>
#include <string>
#include <tuple>
#include "avatar.h"
#include "calendar.h"
#include "cata_path.h"
#include "cata_utility.h"
#include "character.h"
#include "color.h"
#include "construction.h"
#include "construction_group.h"
#include "debug.h"
#include "faction.h"
#include "field_type.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "iexamine.h"
#include "init.h"
#include "item.h"
#include "item_category.h"
#include "item_group.h"
#include "item_pocket.h"
#include "item_search.h"
#include "itype.h"
#include "json.h"
#include "json_error.h"
#include "localized_comparator.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "memory_fast.h"
#include "output.h"
#include "path_info.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "ui.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "visitable.h"
#include "vpart_position.h"
Namespaces
anonymous_namespace{clzones.cpp}
Functions
static std::pair< tripoint_abs_ms, tripoint_abs_ms > get_corners (tripoint_abs_ms a, tripoint_abs_ms b)
void anonymous_namespace{clzones.cpp}::_rotate_zone (map &target_map, zone_data &zone, int turns)
cata_path anonymous_namespace{clzones.cpp}::_savefile (std::string const &suffix, bool player)
void mapgen_place_zone (tripoint const &start, tripoint const &end, zone_type_id const &type, faction_id const &fac, std::string const &name, std::string const &filter, map *pmap)
Variables
static const faction_id faction_your_followers ("your_followers")
static const item_category_id item_category_food ("food")
static const itype_id itype_disassembly ("disassembly")
static const itype_id itype_null ("null")
static const zone_type_id zone_type_AUTO_DRINK ("AUTO_DRINK")
static const zone_type_id zone_type_AUTO_EAT ("AUTO_EAT")
static const zone_type_id zone_type_CAMP_FOOD ("CAMP_FOOD")
static const zone_type_id zone_type_CONSTRUCTION_BLUEPRINT ("CONSTRUCTION_BLUEPRINT")
static const zone_type_id zone_type_DISASSEMBLE ("DISASSEMBLE")
static const zone_type_id zone_type_FARM_PLOT ("FARM_PLOT")
static const zone_type_id zone_type_LOOT_CORPSE ("LOOT_CORPSE")
static const zone_type_id zone_type_LOOT_CUSTOM ("LOOT_CUSTOM")
static const zone_type_id zone_type_LOOT_DEFAULT ("LOOT_DEFAULT")
static const zone_type_id zone_type_LOOT_DRINK ("LOOT_DRINK")
static const zone_type_id zone_type_LOOT_FOOD ("LOOT_FOOD")
static const zone_type_id zone_type_LOOT_IGNORE ("LOOT_IGNORE")
static const zone_type_id zone_type_LOOT_ITEM_GROUP ("LOOT_ITEM_GROUP")
static const zone_type_id zone_type_LOOT_PDRINK ("LOOT_PDRINK")
static const zone_type_id zone_type_LOOT_PFOOD ("LOOT_PFOOD")
static const zone_type_id zone_type_LOOT_SEEDS ("LOOT_SEEDS")
static const zone_type_id zone_type_LOOT_UNSORTED ("LOOT_UNSORTED")
static const zone_type_id zone_type_LOOT_WOOD ("LOOT_WOOD")
static const zone_type_id zone_type_NO_AUTO_PICKUP ("NO_AUTO_PICKUP")
static const zone_type_id zone_type_NO_NPC_PICKUP ("NO_NPC_PICKUP")
static const zone_type_id zone_type_SOURCE_FIREWOOD ("SOURCE_FIREWOOD")
static const zone_type_id zone_type_STRIP_CORPSES ("STRIP_CORPSES")
static const zone_type_id zone_type_UNLOAD_ALL ("UNLOAD_ALL")
const std::vector< zone_type_id > ignorable_zone_types
static const std::unordered_map< std::string, zone_type_id > legacy_zone_types
generic_factory< zone_type > anonymous_namespace{clzones.cpp}::zone_type_factory ("zone_type")
Function Documentation
get_corners()
static std::pair<tripoint_abs_ms, tripoint_abs_ms> get_corners (tripoint_abs_ms a, tripoint_abs_ms b) static
Definition at line 705 of file clzones.cpp.
 {
     const tripoint_abs_ms start = tripoint_abs_ms( std::min( a.x(), b.x() ), std::min( a.y(), b.y() ),
                                   std::min( a.z(), b.z() ) );
     const tripoint_abs_ms end = tripoint_abs_ms( std::max( a.x(), b.x() ), std::max( a.y(), b.y() ),
                                 std::max( a.z(), b.z() ) );
     return { start, end };
 }
References a, b, keycode::end, max(), and min().
Referenced by zone_data::refresh_display().
mapgen_place_zone()
void mapgen_place_zone (tripoint const & start, tripoint const & end, zone_type_id const & type, faction_id const & fac, std::string const & name, std::string const & filter, map * pmap)
Definition at line 1802 of file clzones.cpp.
 {
     zone_manager &mgr = zone_manager::get_manager();
     auto options = zone_options::create( type );
     tripoint const s_ = std::min( start, end );
     tripoint const e_ = std::max( start, end );
     if( type == zone_type_LOOT_CUSTOM || type == zone_type_LOOT_ITEM_GROUP ) {
         if( dynamic_cast<loot_options *>( &*options ) != nullptr ) {
             dynamic_cast<loot_options *>( &*options )->set_mark( filter );
         }
     }
     mgr.add( name, type, fac, false, true, s_, e_, options, false, true, pmap );
 }
References zone_manager::add(), zone_options::create(), keycode::end, filter, zone_manager::get_manager(), max(), min(), om_direction::name(), PATH_INFO::options(), zone_type_LOOT_CUSTOM, and zone_type_LOOT_ITEM_GROUP.
Referenced by jmapgen_zone::apply(), and vehicle::place_zones().
Variable Documentation
faction_your_followers
const faction_id faction_your_followers("your_followers") ("your_followers") static
Referenced by zone_manager::deserialize(), and zone_manager::load_world_zones().
ignorable_zone_types
const std::vector<zone_type_id> ignorable_zone_types
Initial value:
= {
    zone_type_AUTO_EAT,
    zone_type_AUTO_DRINK,
    zone_type_DISASSEMBLE,
    zone_type_SOURCE_FIREWOOD,
}
Definition at line 83 of file clzones.cpp.
Referenced by activity_on_turn_move_loot(), zone_options::create(), and zone_options::is_valid().
item_category_food
const item_category_id item_category_food("food") ("food") static
Referenced by zone_manager::get_near_zone_type_for_item().
itype_disassembly
const itype_id itype_disassembly("disassembly") ("disassembly") static
Referenced by zone_manager::get_near_zone_type_for_item().
itype_null
const itype_id itype_null("null") ("null") static
Referenced by plot_options::query_seed().
legacy_zone_types
const std::unordered_map< std::string, zone_type_id> legacy_zone_types static
Initial value:
= {
    {"zone_disassemble", zone_type_DISASSEMBLE},
    {"zone_strip", zone_type_STRIP_CORPSES},
    {"zone_unload_all", zone_type_UNLOAD_ALL}
}
Definition at line 90 of file clzones.cpp.
Referenced by zone_data::deserialize().
zone_type_AUTO_DRINK
const zone_type_id zone_type_AUTO_DRINK("AUTO_DRINK") ("AUTO_DRINK") static
zone_type_AUTO_EAT
const zone_type_id zone_type_AUTO_EAT("AUTO_EAT") ("AUTO_EAT") static
zone_type_CAMP_FOOD
const zone_type_id zone_type_CAMP_FOOD("CAMP_FOOD") ("CAMP_FOOD") static
Referenced by zone_manager::has_loot_dest_near().
zone_type_CONSTRUCTION_BLUEPRINT
const zone_type_id zone_type_CONSTRUCTION_BLUEPRINT("CONSTRUCTION_BLUEPRINT") ("CONSTRUCTION_BLUEPRINT") static
Referenced by zone_manager::add(), zone_options::create(), zone_manager::has_loot_dest_near(), and zone_options::is_valid().
zone_type_DISASSEMBLE
const zone_type_id zone_type_DISASSEMBLE("DISASSEMBLE") ("DISASSEMBLE") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_type_FARM_PLOT
const zone_type_id zone_type_FARM_PLOT("FARM_PLOT") ("FARM_PLOT") static
Referenced by zone_manager::add(), zone_options::create(), zone_manager::has_loot_dest_near(), and zone_options::is_valid().
zone_type_LOOT_CORPSE
const zone_type_id zone_type_LOOT_CORPSE("LOOT_CORPSE") ("LOOT_CORPSE") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_type_LOOT_CUSTOM
const zone_type_id zone_type_LOOT_CUSTOM("LOOT_CUSTOM") ("LOOT_CUSTOM") static
Referenced by zone_options::create(), zone_manager::custom_loot_has(), zone_manager::get_near(), zone_manager::get_near_zone_type_for_item(), zone_options::is_valid(), and mapgen_place_zone().
zone_type_LOOT_DEFAULT
const zone_type_id zone_type_LOOT_DEFAULT("LOOT_DEFAULT") ("LOOT_DEFAULT") static
zone_type_LOOT_DRINK
const zone_type_id zone_type_LOOT_DRINK("LOOT_DRINK") ("LOOT_DRINK") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_type_LOOT_FOOD
const zone_type_id zone_type_LOOT_FOOD("LOOT_FOOD") ("LOOT_FOOD") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_type_LOOT_IGNORE
const zone_type_id zone_type_LOOT_IGNORE("LOOT_IGNORE") ("LOOT_IGNORE") static
Referenced by zone_manager::has_loot_dest_near().
zone_type_LOOT_ITEM_GROUP
const zone_type_id zone_type_LOOT_ITEM_GROUP("LOOT_ITEM_GROUP") ("LOOT_ITEM_GROUP") static
Referenced by zone_options::create(), zone_manager::custom_loot_has(), zone_manager::get_near(), zone_manager::get_near_zone_type_for_item(), zone_options::is_valid(), and mapgen_place_zone().
zone_type_LOOT_PDRINK
const zone_type_id zone_type_LOOT_PDRINK("LOOT_PDRINK") ("LOOT_PDRINK") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_type_LOOT_PFOOD
const zone_type_id zone_type_LOOT_PFOOD("LOOT_PFOOD") ("LOOT_PFOOD") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_type_LOOT_SEEDS
const zone_type_id zone_type_LOOT_SEEDS("LOOT_SEEDS") ("LOOT_SEEDS") static
Referenced by plot_options::query_seed().
zone_type_LOOT_UNSORTED
const zone_type_id zone_type_LOOT_UNSORTED("LOOT_UNSORTED") ("LOOT_UNSORTED") static
Referenced by zone_manager::has_loot_dest_near().
zone_type_LOOT_WOOD
const zone_type_id zone_type_LOOT_WOOD("LOOT_WOOD") ("LOOT_WOOD") static
Referenced by zone_manager::get_near_zone_type_for_item().
zone_type_NO_AUTO_PICKUP
const zone_type_id zone_type_NO_AUTO_PICKUP("NO_AUTO_PICKUP") ("NO_AUTO_PICKUP") static
Referenced by zone_manager::has_loot_dest_near().
zone_type_NO_NPC_PICKUP
const zone_type_id zone_type_NO_NPC_PICKUP("NO_NPC_PICKUP") ("NO_NPC_PICKUP") static
Referenced by zone_manager::get_point_set_loot(), and zone_manager::has_loot_dest_near().
zone_type_SOURCE_FIREWOOD
const zone_type_id zone_type_SOURCE_FIREWOOD("SOURCE_FIREWOOD") ("SOURCE_FIREWOOD") static
zone_type_STRIP_CORPSES
const zone_type_id zone_type_STRIP_CORPSES("STRIP_CORPSES") ("STRIP_CORPSES") static
zone_type_UNLOAD_ALL
const zone_type_id zone_type_UNLOAD_ALL("UNLOAD_ALL") ("UNLOAD_ALL") static
Referenced by zone_options::create(), and zone_options::is_valid().