Cataclysm DDA: src/color.cpp File Reference
color.cpp File Reference
#include "color.h"
#include <algorithm>
#include <cstddef>
#include <filesystem>
#include <iterator>
#include <map>
#include <memory>
#include <utility>
#include <vector>
#include "cata_path.h"
#include "cata_utility.h"
#include "cursesdef.h"
#include "debug.h"
#include "filesystem.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "input_context.h"
#include "json.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
#include "cata_imgui.h"
Functions
color_manager & get_all_colors ()
void init_colors ()
nc_color invert_color (const nc_color &c)
nc_color hilite (const nc_color &c)
nc_color red_background (const nc_color &c)
nc_color white_background (const nc_color &c)
nc_color green_background (const nc_color &c)
nc_color yellow_background (const nc_color &c)
nc_color magenta_background (const nc_color &c)
nc_color cyan_background (const nc_color &c)
std::string hilite_string (const std::string &text)
nc_color color_from_string (const std::string_view color, const report_color_error color_error)
Given the name of a foreground color, returns the nc_color value that matches.
std::string string_from_color (const nc_color &color)
The reverse of color_from_string.
nc_color bgcolor_from_string (const std::string &color)
Given the name of a background color (that is, one of the i_xxxxx colors), returns the nc_color constant that matches.
color_tag_parse_result get_color_from_tag (const std::string_view s, const report_color_error color_error)
std::string get_tag_from_color (const nc_color &color)
std::string colorize (const std::string &text, const nc_color &color)
std::string colorize (const translation &text, const nc_color &color)
std::string get_note_string_from_color (const nc_color &color)
nc_color get_note_color (const std::string_view note_id)
const std::unordered_map< std::string, note_color > & get_note_color_names ()
static void draw_header (const catacurses::window &w)
Variables
static std::unordered_map< std::string, note_color > color_by_string_map
Function Documentation
bgcolor_from_string()
nc_color bgcolor_from_string (const std::string & color)
Given the name of a background color (that is, one of the i_xxxxx colors), returns the nc_color constant that matches.
If no match is found, i_white is returned.
Parameters
color The color to get, as a std::string.
Returns
The nc_color constant that matches the input.
Definition at line 685 of file color.cpp.
 {
     std::string new_color = "i_" + color;
     const std::array<std::pair<std::string, std::string>, 2> pSearch = { {
             { "light_", "lt" }, { "dark_", "dk" }
         }
     };
     for( const auto &i : pSearch ) {
         size_t pos = 0;
         while( ( pos = new_color.find( i.second, pos ) ) != std::string::npos ) {
             new_color.replace( pos, i.second.length(), i.first );
             pos += i.first.length();
             debugmsg( "Deprecated background color suffix was used: (%s) in (%s).  Please update mod that uses that.",
                       i.second, color );
         }
     }
     const nc_color col = all_colors.name_to_color( new_color );
     if( col.to_int() > 0 ) {
         return col;
     }
     return i_white;
 }
References all_colors, color(), debugmsg, i_white, math_opers::pos(), and nc_color::to_int().
Referenced by map_data_common_t::load_symbol().
color_from_string()
nc_color color_from_string (const std::string_view color, const report_color_error color_error)
Given the name of a foreground color, returns the nc_color value that matches.
If no match is found, c_unset is returned. Special cases: {"black" , c_black}, // missing default prefix c_ {"<c|h|i>_black" , h_black}, // has prefix c_ or h_ or i_ {"dark_gray_red" , c_dark_gray_red}, // use dark_ instead of dk as the latter is being deprecated {"light_blue_red" , c_light_blue_red}, // use light_ instead of lt as the latter is being deprecated
Parameters
color The color to get, as a std::string.
Returns
The nc_color constant that matches the input.
Definition at line 629 of file color.cpp.
 {
     if( color.empty() ) {
         return c_unset;
     }
     std::string new_color( color );
     if( new_color.substr( 1, 1 ) != "_" ) { //c_  //i_  //h_
         new_color = "c_" + new_color;
     }
     const std::array<std::pair<std::string, std::string>, 2> pSearch = { {
             { "light_", "lt" }, { "dark_", "dk" }
         }
     };
     for( const auto &i : pSearch ) {
         size_t pos = 0;
         while( ( pos = new_color.find( i.second, pos ) ) != std::string::npos ) {
             new_color.replace( pos, i.second.length(), i.first );
             pos += i.first.length();
             if( color_error == report_color_error::yes ) {
                 debugmsg( "Deprecated foreground color suffix was used: (%s) in (%s).  Please update mod that uses that.",
                           i.second, color );
             }
         }
     }
     const nc_color col = all_colors.name_to_color( new_color, color_error );
     if( col.to_int() > 0 ) {
         return col;
     }
     return c_unset;
 }
References all_colors, c_unset, color(), debugmsg, math_opers::pos(), nc_color::to_int(), and yes.
Referenced by assign(), get_color_from_tag(), itype_variant_data::load(), widget_clause::load(), bodygraph::load(), field_type::load(), map_extra::load(), damage_type::load(), explosion_iuse::load(), Item_factory::load_basic_info(), and map_data_common_t::load_symbol().
colorize() [1/2]
std::string colorize (const std::string & text, const nc_color & color)
Definition at line 742 of file color.cpp.
 {
     const std::string tag = get_tag_from_color( color );
     size_t strpos = text.find( '\n' );
     if( strpos == std::string::npos ) {
         return tag + text + "</color>";
     }
     size_t prevpos = 0;
     std::string ret;
     while( ( strpos = text.find( '\n', prevpos ) ) != std::string::npos ) {
         ret += tag + text.substr( prevpos, strpos - prevpos ) + "</color>\n";
         prevpos = strpos + 1;
     }
     ret += tag + text.substr( prevpos, text.size() - prevpos ) + "</color>";
     return ret;
 }
References color(), get_tag_from_color(), and cata::hash64_detail::ret.
Referenced by trade_ui::_draw_header(), achievement_attained(), computer_session::action_list_mutations(), Character::activate_bionic(), add_electronic_toggle(), item::armor_info(), assemble_hobby_details(), assemble_profession_details(), assemble_scenario_details(), assemble_skill_details(), assemble_stat_details(), iexamine::autodoc(), iuse::blood_draw(), blood_magic(), Character::body_window(), vehicle::build_electronics_menu(), butcher_submenu(), veh_interact::calc_lift_requirements(), veh_interact::calc_overview(), veh_interact::can_remove_part(), anonymous_namespace{item_tname.cpp}::category(), debug_menu::character_edit_needs_menu(), game::check_safe_mode_allowed(), choose_crafter(), color_number(), widget::color_text_function_string(), widget::color_value_string(), colorize(), display::colorized_bodygraph_text(), display::colorized_compass_legend_text(), spell::colorized_fail_percent(), colorized_feature_description_at(), colorized_field_description_at(), colorized_item_name(), display::colorized_overmap_text(), colorized_ter_name_flags_at(), colorized_trap_name_at(), coloured_stat_display(), construction_menu(), anonymous_namespace{item_tname.cpp}::contents(), item::contents_info(), item_pocket::contents_info(), overmap_ui::create_note(), Character::crush_frozen_liquid(), item::degradation_symbol(), item_location::impl::item_on_vehicle::describe(), Character::disassemble(), Character::disp_info(), faction_manager::display(), item::display_name(), display_stat(), main_menu::display_sub_menu(), veh_interact::do_repair(), inventory_column::draw(), dialogue_window::draw(), draw_bionics_titlebar(), bodygraph_display::draw_borders(), keybindings_ui::draw_controls(), target_ui::draw_controls_list(), prof_window::draw_details(), draw_effects_summary(), draw_filter_and_sorting_indicators(), bodygraph_display::draw_graph(), prof_window::draw_header(), draw_health_summary(), overmap_ui::draw_notes(), bodygraph_display::draw_partlist(), draw_proficiencies_info(), draw_spellbook_info(), draw_stats_summary(), draw_traits_info(), game_menus::inv::ebooksave(), effects_description_for_creature(), spell::energy_cost_string(), spell::energy_cur_string(), enumerate_objects_around_point(), Character::extended_description(), monster::extended_description(), mtype::faction_display(), format_item_info(), format_requirements(), formatted_hotkey(), get_achievements_text(), basecamp::get_available_missions_by_dir(), get_bodygraph_lines(), get_compass_for_direction(), get_consume_needs_hint(), overmapbuffer::get_description_at(), get_encumbrance_description(), talk_data::get_entry(), requirement_data::get_folded_components_list(), requirement_data::get_folded_list(), requirement_data::get_folded_tools_list(), inventory_selector::get_holster_stat(), mod_ui::get_information(), kill_tracker::get_kills_text(), help::get_note_colors(), get_opt_slider(), get_score_text(), construction::get_time_string(), inventory_selector::get_volume_stat(), inventory_selector::get_weight_and_length_stat(), Character::gunmod_add(), display::health_string(), hilite_string(), main_menu::init_strings(), item_save_monsters(), ma_style_callback::key(), keybindings_ui::keybindings_ui(), diary::kill_changes(), list_items_filter_history_help(), list_nested(), iuse::marloss_seed(), Character::mend_item(), widget::number_cond(), target_ui::panel_cursor_info(), target_ui::panel_gun_info(), target_ui::panel_spell_info(), photo_def_for_camera_point(), character_martial_arts::pick_style(), pickup_selector::pickup_selector(), overmap_ui::place_ter_or_special(), outfit::prepare_bodymap_info(), bodygraph_display::prepare_infotext(), selection_line::print(), computer_session::print_error(), computer_session::print_gibberish_line(), monster::print_info(), multiline_list::print_line(), main_menu::print_menu_items(), vehicle::print_vparts_descs(), iexamine::quern_examine(), recipe_info(), pocket_favorite_callback::refresh(), zone_data::refresh_display(), repair_inventory_preset::repair_inventory_preset(), replace_keybind_tag(), recipe::required_proficiencies_string(), satiety_bar(), overmap_ui::search(), iuse::seed(), calendar_ui::select_time_point(), set_skills(), set_traits(), shortcut_text(), auto_notes::auto_note_manager_gui::show(), show_mutations_titlebar(), worldfactory::show_worldgen_basic(), iexamine::smoker_options(), outfit::sort_armor(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), display::sundial_text_color(), widget::sym_cond(), widget::sym_text_cond(), texitify_bandage_power(), texitify_base_healing_power(), texitify_healing_power(), widget::text_cond(), text_for_requirement(), zone_data::toggle_display(), inventory_multiselector::toggle_entries(), Character::toolmod_add(), avatar::total_daily_calories_string(), diary::trait_changes(), achievement_tracker::ui_text(), achievement::time_bound::ui_text(), achievement_state::ui_text(), achievements_tracker::ui_text_for(), veh_interact::update_part_requirements(), sew_advanced_actor::use(), query_popup::wait_text(), iuse::wash_items(), anonymous_namespace{item_tname.cpp}::wbl_mark(), Character::weapname_ammo(), display::weight_string(), Character::will_eat(), and debug_menu::wisheffect().
colorize() [2/2]
std::string colorize (const translation & text, const nc_color & color)
Definition at line 760 of file color.cpp.
 {
     return colorize( text.translated(), color );
 }
References color(), colorize(), and translation::translated().
cyan_background()
nc_color cyan_background (const nc_color & c)
Definition at line 582 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_CYAN );
     return static_cast<int>( color ) > 0 ? color : c_black_cyan;
 }
References all_colors, c, c_black_cyan, color(), and HL_CYAN.
Referenced by map::draw_from_above(), editmap::draw_main_ui_overlay(), editmap_hilight::setup(), and Character::symbol_color().
draw_header()
static void draw_header (const catacurses::window & w) static
Definition at line 804 of file color.cpp.
 {
     int tmpx = 0;
     tmpx += shortcut_print( w, point( tmpx, 0 ), c_white, c_light_green,
                             _( "<R>emove custom color" ) ) + 2;
     tmpx += shortcut_print( w, point( tmpx, 0 ), c_white, c_light_green,
                             _( "<Arrow Keys> To navigate" ) ) + 2;
     shortcut_print( w, point( tmpx, 0 ), c_white, c_light_green, _( "<Enter>-Edit" ) );
     tmpx = 0;
     tmpx += shortcut_print( w, point( tmpx, 1 ), c_white, c_light_green,
                             _( "Load a <C>olor theme" ) ) + 2;
     shortcut_print( w, point( tmpx, 1 ), c_white, c_light_green, _( "Load <T>emplate" ) );
     // NOLINTNEXTLINE(cata-use-named-point-constants)
     mvwprintz( w, point( 0, 2 ), c_white, _( "Some color changes may require a restart." ) );
     mvwhline( w, point( 0, 3 ), LINE_OXOX, getmaxx( w ) ); // Draw line under header
     mvwputch( w, point( 48, 3 ), BORDER_COLOR, LINE_OXXX ); //^|^
     mvwprintz( w, point( 3, 4 ), c_white, _( "Colorname" ) );
     mvwprintz( w, point( 21, 4 ), c_white, _( "Normal" ) );
     mvwprintz( w, point( 52, 4 ), c_white, _( "Invert" ) );
     wnoutrefresh( w );
 }
References _, BORDER_COLOR, c_light_green, c_white, catacurses::getmaxx(), LINE_OXOX, LINE_OXXX, catacurses::mvwhline(), mvwprintz(), mvwputch(), shortcut_print(), and catacurses::wnoutrefresh().
Referenced by color_manager::show_gui().
get_all_colors()
color_manager& get_all_colors ()
Definition at line 43 of file color.cpp.
 {
     static color_manager single_instance;
     return single_instance;
 }
Referenced by colorize_symbols(), Messages::dialog::filter_help_text(), auto_notes::custom_symbol::get_color_string(), overmap_ui::get_scent_glyph(), widget::load(), liquid_handler::perform_liquid_transfer(), replace_colors(), auto_notes::custom_symbol::set_color(), and auto_notes::auto_note_manager_gui::show().
get_color_from_tag()
color_tag_parse_result get_color_from_tag (const std::string_view s, const report_color_error color_error)
Definition at line 712 of file color.cpp.
 {
     if( s.empty() || s[0] != '<' ) {
         return { color_tag_parse_result::non_color_tag, {} };
     }
     if( s.substr( 0, 8 ) == "</color>" ) {
         return { color_tag_parse_result::close_color_tag, {} };
     }
     if( s.substr( 0, 7 ) != "<color_" ) {
         return { color_tag_parse_result::non_color_tag, {} };
     }
     size_t tag_close = s.find( '>' );
     if( tag_close == std::string::npos ) {
         return { color_tag_parse_result::non_color_tag, {} };
     }
     std::string_view color_name = s.substr( 7, tag_close - 7 );
     const nc_color color = color_from_string( color_name, color_error );
     if( color != c_unset ) {
         return { color_tag_parse_result::open_color_tag, color };
     } else {
         return { color_tag_parse_result::non_color_tag, color };
     }
 }
References c_unset, color_tag_parse_result::close_color_tag, color(), color_from_string(), color_tag_parse_result::non_color_tag, and color_tag_parse_result::open_color_tag.
Referenced by hilite_string(), display::morale_emotion(), and update_color_stack().
get_note_color()
nc_color get_note_color (const std::string_view note_id)
Definition at line 776 of file color.cpp.
 {
     // TODO in C++20 we can pass a string_view in directly rather than
     // constructing a string to use as the find argument
     const auto candidate_color = color_by_string_map.find( std::string( note_id ) );
     if( candidate_color != std::end( color_by_string_map ) ) {
         return candidate_color->second.color;
     }
     // The default note color.
     return c_yellow;
 }
References c_yellow, color_by_string_map, and keycode::end.
Referenced by overmap_ui::get_note_display_info().
get_note_color_names()
const std::unordered_map<std::string, note_color>& get_note_color_names ()
Definition at line 788 of file color.cpp.
 {
     return color_by_string_map;
 }
References color_by_string_map.
Referenced by overmap_ui::create_note(), help::get_note_colors(), and auto_notes::auto_note_manager_gui::show().
get_note_string_from_color()
std::string get_note_string_from_color (const nc_color & color)
Definition at line 765 of file color.cpp.
 {
     for( const std::pair<const std::string, note_color> &i : color_by_string_map ) {
         if( i.second.color == color ) {
             return i.first;
         }
     }
     // The default note string.
     return "Y";
 }
References color(), and color_by_string_map.
Referenced by overmap::add_extra_note().
get_tag_from_color()
std::string get_tag_from_color (const nc_color & color)
Definition at line 737 of file color.cpp.
 {
     return "<color_" + string_from_color( color ) + ">";
 }
References color(), and string_from_color().
Referenced by colorize(), requirement_data::get_folded_list(), hilite_string(), and monster::print_info().
green_background()
nc_color green_background (const nc_color & c)
Definition at line 564 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_GREEN );
     return static_cast<int>( color ) > 0 ? color : c_black_green;
 }
References all_colors, c, c_black_green, color(), and HL_GREEN.
Referenced by editmap::draw_main_ui_overlay(), editmap_hilight::setup(), and Character::symbol_color().
hilite()
nc_color hilite (const nc_color & c)
Definition at line 546 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_BLUE );
     return static_cast<int>( color ) > 0 ? color : h_white;
 }
References all_colors, c, color(), h_white, and HL_BLUE.
Referenced by debug_menu::change_spells(), monster::color_with_effects(), display::colorized_overmap_text(), construction_color(), faction_manager::display(), veh_interact::display_list(), veh_interact::display_overview(), main_menu::display_sub_menu(), veh_interact::display_veh(), draw_bionics_tab(), lightson_game::draw_level(), map::draw_maptile(), help::draw_menu(), bodygraph_display::draw_partlist(), draw_proficiencies_tab(), prof_window::draw_profs(), draw_speed_tab(), draw_traits_tab(), requirement_data::get_folded_components_list(), requirement_data::get_folded_list(), hilite_string(), basecamp::job_assignment_ui(), game::list_items(), game::list_monsters(), mvwputch_hi(), worldfactory::pick_world(), advanced_inventory::print_items(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), main_menu::print_menu_items(), vehicle::print_part_list(), smart_controller_ui::refresh(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), lightson_game::start_game(), minesweeper_game::start_game(), sokoban_game::start_game(), display::sundial_text_color(), Character::symbol_color(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), and basecamp::worker_assignment_ui().
hilite_string()
std::string hilite_string (const std::string & text)
Definition at line 588 of file color.cpp.
 {
     std::string highlighted = text;
     size_t pos = 0;
     size_t tag_length = 0;
     int color_tag_count = 0;
     while( ( pos = highlighted.find( "<color_", pos ) ) != std::string::npos ) {
         tag_length = highlighted.find( '>', pos ) - pos + 1;
         if( tag_length <= 0 ) {
             debugmsg( "Tag length calculated incorrectly.  Unable to highlight text %s", text );
             return text;
         }
         std::string tag = highlighted.substr( pos, tag_length );
         color_tag_parse_result old_color = get_color_from_tag( tag );
         if( old_color.type != color_tag_parse_result::open_color_tag ) {
             debugmsg( "Unable to highlight text %s, parsing color tag %s failed", text, tag );
             return text;
         }
         nc_color new_color = hilite( old_color.color );
         std::string new_tag = get_tag_from_color( new_color );
         highlighted.replace( pos, tag_length, new_tag );
         pos += new_tag.length();
         ++color_tag_count;
     }
     if( color_tag_count < 1 ) {
         highlighted = colorize( highlighted, h_white );
     }
     return highlighted;
 }
References color_tag_parse_result::color, colorize(), debugmsg, get_color_from_tag(), get_tag_from_color(), h_white, hilite(), color_tag_parse_result::open_color_tag, math_opers::pos(), and color_tag_parse_result::type.
Referenced by inventory_column::draw(), and multiline_list::print_line().
init_colors()
void init_colors ()
Definition at line 421 of file color.cpp.
 {
     using namespace catacurses; // to get the base_color enumeration
     init_pair( 1, white,      black );
     init_pair( 2, red,        black );
     init_pair( 3, green,      black );
     init_pair( 4, blue,       black );
     init_pair( 5, cyan,       black );
     init_pair( 6, magenta,    black );
     init_pair( 7, yellow,     black );
     // Inverted Colors
     init_pair( 8, black,      white );
     init_pair( 9, black,      red );
     init_pair( 10, black,      green );
     init_pair( 11, black,      blue );
     init_pair( 12, black,      cyan );
     init_pair( 13, black,      magenta );
     init_pair( 14, black,      yellow );
     // Highlighted - blue background
     init_pair( 15, white,      blue );
     init_pair( 16, red,        blue );
     init_pair( 17, green,      blue );
     init_pair( 18, blue,       blue );
     init_pair( 19, cyan,       blue );
     init_pair( 20, black,      blue );
     init_pair( 21, magenta,    blue );
     init_pair( 22, yellow,     blue );
     // Red background - for monsters on fire
     init_pair( 23, white,      red );
     init_pair( 24, red,        red );
     init_pair( 25, green,      red );
     init_pair( 26, blue,       red );
     init_pair( 27, cyan,       red );
     init_pair( 28, magenta,    red );
     init_pair( 29, yellow,     red );
     init_pair( 30, black,      black );
     init_pair( 31, white,      black );
     init_pair( 32, black,      white );
     init_pair( 33, white,      white );
     init_pair( 34, red,        white );
     init_pair( 35, green,      white );
     init_pair( 36, yellow,     white );
     init_pair( 37, blue,       white );
     init_pair( 38, magenta,    white );
     init_pair( 39, cyan,       white );
     init_pair( 40, black,      green );
     init_pair( 41, white,      green );
     init_pair( 42, red,        green );
     init_pair( 43, green,      green );
     init_pair( 44, yellow,     green );
     init_pair( 45, blue,       green );
     init_pair( 46, magenta,    green );
     init_pair( 47, cyan,       green );
     init_pair( 48, black,      yellow );
     init_pair( 49, white,      yellow );
     init_pair( 50, red,        yellow );
     init_pair( 51, green,      yellow );
     init_pair( 52, yellow,     yellow );
     init_pair( 53, blue,       yellow );
     init_pair( 54, magenta,    yellow );
     init_pair( 55, cyan,       yellow );
     init_pair( 56, black,      magenta );
     init_pair( 57, white,      magenta );
     init_pair( 58, red,        magenta );
     init_pair( 59, green,      magenta );
     init_pair( 60, yellow,     magenta );
     init_pair( 61, blue,       magenta );
     init_pair( 62, magenta,    magenta );
     init_pair( 63, cyan,       magenta );
     init_pair( 64, black,      cyan );
     init_pair( 65, white,      cyan );
     init_pair( 66, red,        cyan );
     init_pair( 67, green,      cyan );
     init_pair( 68, yellow,     cyan );
     init_pair( 69, blue,       cyan );
     init_pair( 70, magenta,    cyan );
     init_pair( 71, cyan,       cyan );
     init_pair( 72, dark_gray,  black );
     init_pair( 73, dark_gray,  red );
     init_pair( 74, dark_gray,  green );
     init_pair( 75, dark_gray,  blue );
     init_pair( 76, dark_gray,  cyan );
     init_pair( 77, dark_gray,  magenta );
     init_pair( 78, dark_gray,  yellow );
     init_pair( 79, dark_gray,  white );
     init_pair( 80, black,      dark_gray );
     init_pair( 81, red,        dark_gray );
     init_pair( 82, green,      dark_gray );
     init_pair( 83, blue,       dark_gray );
     init_pair( 84, cyan,       dark_gray );
     init_pair( 85, magenta,    dark_gray );
     init_pair( 86, yellow,     dark_gray );
     init_pair( 87, white,      dark_gray );
     all_colors.load_default();
     all_colors.load_custom( {} );
     // The short color codes (e.g. "br") are intentionally untranslatable.
     color_by_string_map = {
         {"br", {c_brown, to_translation( "brown" )}}, {"lg", {c_light_gray, to_translation( "light gray" )}},
         {"dg", {c_dark_gray, to_translation( "dark gray" )}}, {"r", {c_light_red, to_translation( "light red" )}},
         {"R", {c_red, to_translation( "red" )}}, {"g", {c_light_green, to_translation( "light green" )}},
         {"G", {c_green, to_translation( "green" )}}, {"b", {c_light_blue, to_translation( "light blue" )}},
         {"B", {c_blue, to_translation( "blue" )}}, {"W", {c_white, to_translation( "white" )}},
         {"C", {c_cyan, to_translation( "cyan" )}}, {"c", {c_light_cyan, to_translation( "light cyan" )}},
         {"P", {c_pink, to_translation( "pink" )}}, {"m", {c_magenta, to_translation( "magenta" )}}
     };
 }
References all_colors, catacurses::black, catacurses::blue, c_blue, c_brown, c_cyan, c_dark_gray, c_green, c_light_blue, c_light_cyan, c_light_gray, c_light_green, c_light_red, c_magenta, c_pink, c_red, c_white, color_by_string_map, catacurses::cyan, catacurses::dark_gray, catacurses::green, catacurses::init_pair(), catacurses::magenta, catacurses::red, to_translation(), catacurses::white, and catacurses::yellow.
Referenced by catacurses::init_interface(), and main().
invert_color()
nc_color invert_color (const nc_color & c)
Definition at line 540 of file color.cpp.
 {
     const nc_color color = all_colors.get_invert( c );
     return static_cast<int>( color ) > 0 ? color : c_pink;
 }
References all_colors, c, c_pink, and color().
Referenced by monster::color_with_effects(), map::draw_from_above(), map::draw_maptile(), advanced_inventory::draw_minimap(), anonymous_namespace{animation.cpp}::draw_zones_curses(), vehicle::get_display_of_tile(), and mvwputch_inv().
magenta_background()
nc_color magenta_background (const nc_color & c)
Definition at line 576 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_MAGENTA );
     return static_cast<int>( color ) > 0 ? color : c_black_magenta;
 }
References all_colors, c, c_black_magenta, color(), and HL_MAGENTA.
Referenced by advanced_inventory::print_items(), and editmap_hilight::setup().
red_background()
nc_color red_background (const nc_color & c)
Definition at line 552 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_RED );
     return static_cast<int>( color ) > 0 ? color : c_white_red;
 }
References all_colors, c, c_white_red, color(), and HL_RED.
Referenced by monster::color_with_effects(), veh_interact::display_veh(), overmap_ui::draw_ascii(), anonymous_namespace{animation.cpp}::draw_hit_mon_curses(), anonymous_namespace{animation.cpp}::draw_hit_player_curses(), sokoban_game::draw_level(), map::draw_maptile(), game::draw_minimap(), overmap_ui::draw_overmap_chunk(), display::overmap_tile_symbol_color(), editmap_hilight::setup(), Character::symbol_color(), auto_pickup::rule::test_pattern(), and safemode::test_pattern().
string_from_color()
std::string string_from_color (const nc_color & color)
The reverse of color_from_string.
Definition at line 667 of file color.cpp.
 {
     std::string sColor = all_colors.get_name( color );
     if( sColor != "c_unset" ) {
         return sColor;
     }
     return "c_white";
 }
References all_colors, and color().
Referenced by vpart_info::format_description(), get_tag_from_color(), and overmap_ui::place_ter_or_special().
white_background()
nc_color white_background (const nc_color & c)
Definition at line 558 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_WHITE );
     return static_cast<int>( color ) > 0 ? color : c_black_white;
 }
References all_colors, c, c_black_white, color(), and HL_WHITE.
Referenced by Character::symbol_color().
yellow_background()
nc_color yellow_background (const nc_color & c)
Definition at line 570 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_YELLOW );
     return static_cast<int>( color ) > 0 ? color : c_black_yellow;
 }
References all_colors, c, c_black_yellow, color(), and HL_YELLOW.
Referenced by anonymous_namespace{animation.cpp}::draw_hit_player_curses(), requirement_data::get_folded_list(), and editmap_hilight::setup().
Variable Documentation
color_by_string_map
std::unordered_map<std::string, note_color> color_by_string_map static
Definition at line 49 of file color.cpp.
Referenced by get_note_color(), get_note_color_names(), get_note_string_from_color(), and init_colors().