Cataclysm DDA: src/color.h File Reference
color.h File Reference
#include <array>
#include <iosfwd>
#include <string>
#include <string_view>
#include <unordered_map>
#include "translation.h"
Classes
class nc_color
struct std::hash< nc_color >
class color_manager
struct color_manager::color_struct
class deferred_color
For color values that are created before the color definitions are loaded from JSON.
struct note_color
struct color_tag_parse_result
Macros
#define CATA_SRC_COLOR_H
#define all_colors get_all_colors()
#define c_black all_colors.get(def_c_black)
#define c_white all_colors.get(def_c_white)
#define c_light_gray all_colors.get(def_c_light_gray)
#define c_dark_gray all_colors.get(def_c_dark_gray)
#define c_red all_colors.get(def_c_red)
#define c_green all_colors.get(def_c_green)
#define c_blue all_colors.get(def_c_blue)
#define c_cyan all_colors.get(def_c_cyan)
#define c_magenta all_colors.get(def_c_magenta)
#define c_brown all_colors.get(def_c_brown)
#define c_light_red all_colors.get(def_c_light_red)
#define c_light_green all_colors.get(def_c_light_green)
#define c_light_blue all_colors.get(def_c_light_blue)
#define c_light_cyan all_colors.get(def_c_light_cyan)
#define c_pink all_colors.get(def_c_pink)
#define c_yellow all_colors.get(def_c_yellow)
#define h_black all_colors.get(def_h_black)
#define h_white all_colors.get(def_h_white)
#define h_light_gray all_colors.get(def_h_light_gray)
#define h_dark_gray all_colors.get(def_h_dark_gray)
#define h_red all_colors.get(def_h_red)
#define h_green all_colors.get(def_h_green)
#define h_blue all_colors.get(def_h_blue)
#define h_cyan all_colors.get(def_h_cyan)
#define h_magenta all_colors.get(def_h_magenta)
#define h_brown all_colors.get(def_h_brown)
#define h_light_red all_colors.get(def_h_light_red)
#define h_light_green all_colors.get(def_h_light_green)
#define h_light_blue all_colors.get(def_h_light_blue)
#define h_light_cyan all_colors.get(def_h_light_cyan)
#define h_pink all_colors.get(def_h_pink)
#define h_yellow all_colors.get(def_h_yellow)
#define i_black all_colors.get(def_i_black)
#define i_white all_colors.get(def_i_white)
#define i_light_gray all_colors.get(def_i_light_gray)
#define i_dark_gray all_colors.get(def_i_dark_gray)
#define i_red all_colors.get(def_i_red)
#define i_green all_colors.get(def_i_green)
#define i_blue all_colors.get(def_i_blue)
#define i_cyan all_colors.get(def_i_cyan)
#define i_magenta all_colors.get(def_i_magenta)
#define i_brown all_colors.get(def_i_brown)
#define i_light_red all_colors.get(def_i_light_red)
#define i_light_green all_colors.get(def_i_light_green)
#define i_light_blue all_colors.get(def_i_light_blue)
#define i_light_cyan all_colors.get(def_i_light_cyan)
#define i_pink all_colors.get(def_i_pink)
#define i_yellow all_colors.get(def_i_yellow)
#define c_unset all_colors.get(def_c_unset)
#define c_white_red all_colors.get(def_c_white_red)
#define c_light_gray_red all_colors.get(def_c_light_gray_red)
#define c_dark_gray_red all_colors.get(def_c_dark_gray_red)
#define c_red_red all_colors.get(def_c_red_red)
#define c_green_red all_colors.get(def_c_green_red)
#define c_blue_red all_colors.get(def_c_blue_red)
#define c_cyan_red all_colors.get(def_c_cyan_red)
#define c_magenta_red all_colors.get(def_c_magenta_red)
#define c_brown_red all_colors.get(def_c_brown_red)
#define c_light_red_red all_colors.get(def_c_light_red_red)
#define c_light_green_red all_colors.get(def_c_light_green_red)
#define c_light_blue_red all_colors.get(def_c_light_blue_red)
#define c_light_cyan_red all_colors.get(def_c_light_cyan_red)
#define c_pink_red all_colors.get(def_c_pink_red)
#define c_yellow_red all_colors.get(def_c_yellow_red)
#define c_black_white all_colors.get(def_c_black_white)
#define c_dark_gray_white all_colors.get(def_c_dark_gray_white)
#define c_light_gray_white all_colors.get(def_c_light_gray_white)
#define c_white_white all_colors.get(def_c_white_white)
#define c_red_white all_colors.get(def_c_red_white)
#define c_light_red_white all_colors.get(def_c_light_red_white)
#define c_green_white all_colors.get(def_c_green_white)
#define c_light_green_white all_colors.get(def_c_light_green_white)
#define c_brown_white all_colors.get(def_c_brown_white)
#define c_yellow_white all_colors.get(def_c_yellow_white)
#define c_blue_white all_colors.get(def_c_blue_white)
#define c_light_blue_white all_colors.get(def_c_light_blue_white)
#define c_magenta_white all_colors.get(def_c_magenta_white)
#define c_pink_white all_colors.get(def_c_pink_white)
#define c_cyan_white all_colors.get(def_c_cyan_white)
#define c_light_cyan_white all_colors.get(def_c_light_cyan_white)
#define c_black_green all_colors.get(def_c_black_green)
#define c_dark_gray_green all_colors.get(def_c_dark_gray_green)
#define c_light_gray_green all_colors.get(def_c_light_gray_green)
#define c_white_green all_colors.get(def_c_white_green)
#define c_red_green all_colors.get(def_c_red_green)
#define c_light_red_green all_colors.get(def_c_light_red_green)
#define c_green_green all_colors.get(def_c_green_green)
#define c_light_green_green all_colors.get(def_c_light_green_green)
#define c_brown_green all_colors.get(def_c_brown_green)
#define c_yellow_green all_colors.get(def_c_yellow_green)
#define c_blue_green all_colors.get(def_c_blue_green)
#define c_light_blue_green all_colors.get(def_c_light_blue_green)
#define c_magenta_green all_colors.get(def_c_magenta_green)
#define c_pink_green all_colors.get(def_c_pink_green)
#define c_cyan_green all_colors.get(def_c_cyan_green)
#define c_light_cyan_green all_colors.get(def_c_light_cyan_green)
#define c_black_yellow all_colors.get(def_c_black_yellow)
#define c_dark_gray_yellow all_colors.get(def_c_dark_gray_yellow)
#define c_light_gray_yellow all_colors.get(def_c_light_gray_yellow)
#define c_white_yellow all_colors.get(def_c_white_yellow)
#define c_red_yellow all_colors.get(def_c_red_yellow)
#define c_light_red_yellow all_colors.get(def_c_light_red_yellow)
#define c_green_yellow all_colors.get(def_c_green_yellow)
#define c_light_green_yellow all_colors.get(def_c_light_green_yellow)
#define c_brown_yellow all_colors.get(def_c_brown_yellow)
#define c_yellow_yellow all_colors.get(def_c_yellow_yellow)
#define c_blue_yellow all_colors.get(def_c_blue_yellow)
#define c_light_blue_yellow all_colors.get(def_c_light_blue_yellow)
#define c_magenta_yellow all_colors.get(def_c_magenta_yellow)
#define c_pink_yellow all_colors.get(def_c_pink_yellow)
#define c_cyan_yellow all_colors.get(def_c_cyan_yellow)
#define c_light_cyan_yellow all_colors.get(def_c_light_cyan_yellow)
#define c_black_magenta all_colors.get(def_c_black_magenta)
#define c_dark_gray_magenta all_colors.get(def_c_dark_gray_magenta)
#define c_light_gray_magenta all_colors.get(def_c_light_gray_magenta)
#define c_white_magenta all_colors.get(def_c_white_magenta)
#define c_red_magenta all_colors.get(def_c_red_magenta)
#define c_light_red_magenta all_colors.get(def_c_light_red_magenta)
#define c_green_magenta all_colors.get(def_c_green_magenta)
#define c_light_green_magenta all_colors.get(def_c_light_green_magenta)
#define c_brown_magenta all_colors.get(def_c_brown_magenta)
#define c_yellow_magenta all_colors.get(def_c_yellow_magenta)
#define c_blue_magenta all_colors.get(def_c_blue_magenta)
#define c_light_blue_magenta all_colors.get(def_c_light_blue_magenta)
#define c_magenta_magenta all_colors.get(def_c_magenta_magenta)
#define c_pink_magenta all_colors.get(def_c_pink_magenta)
#define c_cyan_magenta all_colors.get(def_c_cyan_magenta)
#define c_light_cyan_magenta all_colors.get(def_c_light_cyan_magenta)
#define c_black_cyan all_colors.get(def_c_black_cyan)
#define c_dark_gray_cyan all_colors.get(def_c_dark_gray_cyan)
#define c_light_gray_cyan all_colors.get(def_c_light_gray_cyan)
#define c_white_cyan all_colors.get(def_c_white_cyan)
#define c_red_cyan all_colors.get(def_c_red_cyan)
#define c_light_red_cyan all_colors.get(def_c_light_red_cyan)
#define c_green_cyan all_colors.get(def_c_green_cyan)
#define c_light_green_cyan all_colors.get(def_c_light_green_cyan)
#define c_brown_cyan all_colors.get(def_c_brown_cyan)
#define c_yellow_cyan all_colors.get(def_c_yellow_cyan)
#define c_blue_cyan all_colors.get(def_c_blue_cyan)
#define c_light_blue_cyan all_colors.get(def_c_light_blue_cyan)
#define c_magenta_cyan all_colors.get(def_c_magenta_cyan)
#define c_pink_cyan all_colors.get(def_c_pink_cyan)
#define c_cyan_cyan all_colors.get(def_c_cyan_cyan)
#define c_light_cyan_cyan all_colors.get(def_c_light_cyan_cyan)
Enumerations
enum color_id {
def_c_black = 0 , def_c_white , def_c_light_gray , def_c_dark_gray ,
def_c_red , def_c_green , def_c_blue , def_c_cyan ,
def_c_magenta , def_c_brown , def_c_light_red , def_c_light_green ,
def_c_light_blue , def_c_light_cyan , def_c_pink , def_c_yellow ,
def_h_black , def_h_white , def_h_light_gray , def_h_dark_gray ,
def_h_red , def_h_green , def_h_blue , def_h_cyan ,
def_h_magenta , def_h_brown , def_h_light_red , def_h_light_green ,
def_h_light_blue , def_h_light_cyan , def_h_pink , def_h_yellow ,
def_i_black , def_i_white , def_i_light_gray , def_i_dark_gray ,
def_i_red , def_i_green , def_i_blue , def_i_cyan ,
def_i_magenta , def_i_brown , def_i_light_red , def_i_light_green ,
def_i_light_blue , def_i_light_cyan , def_i_pink , def_i_yellow ,
def_c_unset , def_c_black_red , def_c_white_red , def_c_light_gray_red ,
def_c_dark_gray_red , def_c_red_red , def_c_green_red , def_c_blue_red ,
def_c_cyan_red , def_c_magenta_red , def_c_brown_red , def_c_light_red_red ,
def_c_light_green_red , def_c_light_blue_red , def_c_light_cyan_red , def_c_pink_red ,
def_c_yellow_red , def_c_black_white , def_c_dark_gray_white , def_c_light_gray_white ,
def_c_white_white , def_c_red_white , def_c_light_red_white , def_c_green_white ,
def_c_light_green_white , def_c_brown_white , def_c_yellow_white , def_c_blue_white ,
def_c_light_blue_white , def_c_magenta_white , def_c_pink_white , def_c_cyan_white ,
def_c_light_cyan_white , def_c_black_green , def_c_dark_gray_green , def_c_light_gray_green ,
def_c_white_green , def_c_red_green , def_c_light_red_green , def_c_green_green ,
def_c_light_green_green , def_c_brown_green , def_c_yellow_green , def_c_blue_green ,
def_c_light_blue_green , def_c_magenta_green , def_c_pink_green , def_c_cyan_green ,
def_c_light_cyan_green , def_c_black_yellow , def_c_dark_gray_yellow , def_c_light_gray_yellow ,
def_c_white_yellow , def_c_red_yellow , def_c_light_red_yellow , def_c_green_yellow ,
def_c_light_green_yellow , def_c_brown_yellow , def_c_yellow_yellow , def_c_blue_yellow ,
def_c_light_blue_yellow , def_c_magenta_yellow , def_c_pink_yellow , def_c_cyan_yellow ,
def_c_light_cyan_yellow , def_c_black_magenta , def_c_dark_gray_magenta , def_c_light_gray_magenta ,
def_c_white_magenta , def_c_red_magenta , def_c_light_red_magenta , def_c_green_magenta ,
def_c_light_green_magenta , def_c_brown_magenta , def_c_yellow_magenta , def_c_blue_magenta ,
def_c_light_blue_magenta , def_c_magenta_magenta , def_c_pink_magenta , def_c_cyan_magenta ,
def_c_light_cyan_magenta , def_c_black_cyan , def_c_dark_gray_cyan , def_c_light_gray_cyan ,
def_c_white_cyan , def_c_red_cyan , def_c_light_red_cyan , def_c_green_cyan ,
def_c_light_green_cyan , def_c_brown_cyan , def_c_yellow_cyan , def_c_blue_cyan ,
def_c_light_blue_cyan , def_c_magenta_cyan , def_c_pink_cyan , def_c_cyan_cyan ,
def_c_light_cyan_cyan , num_colors
}
enum hl_enum {
HL_BLUE = 0 , HL_RED , HL_WHITE , HL_GREEN ,
HL_YELLOW , HL_MAGENTA , HL_CYAN , NUM_HL
}
enum class report_color_error { no , yes }
Functions
void init_colors ()
color_manager & get_all_colors ()
nc_color hilite (const nc_color &c)
nc_color invert_color (const nc_color &c)
nc_color red_background (const nc_color &c)
nc_color white_background (const nc_color &c)
nc_color green_background (const nc_color &c)
nc_color yellow_background (const nc_color &c)
nc_color magenta_background (const nc_color &c)
nc_color cyan_background (const nc_color &c)
std::string hilite_string (const std::string &text)
nc_color color_from_string (std::string_view color, report_color_error color_error=report_color_error::yes)
Given the name of a foreground color, returns the nc_color value that matches.
std::string string_from_color (const nc_color &color)
The reverse of color_from_string.
nc_color bgcolor_from_string (const std::string &color)
Given the name of a background color (that is, one of the i_xxxxx colors), returns the nc_color constant that matches.
color_tag_parse_result get_color_from_tag (std::string_view s, report_color_error color_error=report_color_error::yes)
std::string get_tag_from_color (const nc_color &color)
std::string colorize (const std::string &text, const nc_color &color)
std::string colorize (const translation &text, const nc_color &color)
std::string get_note_string_from_color (const nc_color &color)
nc_color get_note_color (std::string_view note_id)
const std::unordered_map< std::string, note_color > & get_note_color_names ()
Macro Definition Documentation
all_colors
#define all_colors get_all_colors()
Definition at line 13 of file color.h.
c_black
#define c_black all_colors.get(def_c_black)
Definition at line 15 of file color.h.
c_black_cyan
#define c_black_cyan all_colors.get(def_c_black_cyan)
Definition at line 152 of file color.h.
c_black_green
#define c_black_green all_colors.get(def_c_black_green)
Definition at line 101 of file color.h.
c_black_magenta
#define c_black_magenta all_colors.get(def_c_black_magenta)
Definition at line 135 of file color.h.
c_black_white
#define c_black_white all_colors.get(def_c_black_white)
Definition at line 84 of file color.h.
c_black_yellow
#define c_black_yellow all_colors.get(def_c_black_yellow)
Definition at line 118 of file color.h.
c_blue
#define c_blue all_colors.get(def_c_blue)
Definition at line 21 of file color.h.
c_blue_cyan
#define c_blue_cyan all_colors.get(def_c_blue_cyan)
Definition at line 162 of file color.h.
c_blue_green
#define c_blue_green all_colors.get(def_c_blue_green)
Definition at line 111 of file color.h.
c_blue_magenta
#define c_blue_magenta all_colors.get(def_c_blue_magenta)
Definition at line 145 of file color.h.
c_blue_red
#define c_blue_red all_colors.get(def_c_blue_red)
Definition at line 73 of file color.h.
c_blue_white
#define c_blue_white all_colors.get(def_c_blue_white)
Definition at line 94 of file color.h.
c_blue_yellow
#define c_blue_yellow all_colors.get(def_c_blue_yellow)
Definition at line 128 of file color.h.
c_brown
#define c_brown all_colors.get(def_c_brown)
Definition at line 24 of file color.h.
c_brown_cyan
#define c_brown_cyan all_colors.get(def_c_brown_cyan)
Definition at line 160 of file color.h.
c_brown_green
#define c_brown_green all_colors.get(def_c_brown_green)
Definition at line 109 of file color.h.
c_brown_magenta
#define c_brown_magenta all_colors.get(def_c_brown_magenta)
Definition at line 143 of file color.h.
c_brown_red
#define c_brown_red all_colors.get(def_c_brown_red)
Definition at line 76 of file color.h.
c_brown_white
#define c_brown_white all_colors.get(def_c_brown_white)
Definition at line 92 of file color.h.
c_brown_yellow
#define c_brown_yellow all_colors.get(def_c_brown_yellow)
Definition at line 126 of file color.h.
c_cyan
#define c_cyan all_colors.get(def_c_cyan)
Definition at line 22 of file color.h.
c_cyan_cyan
#define c_cyan_cyan all_colors.get(def_c_cyan_cyan)
Definition at line 166 of file color.h.
c_cyan_green
#define c_cyan_green all_colors.get(def_c_cyan_green)
Definition at line 115 of file color.h.
c_cyan_magenta
#define c_cyan_magenta all_colors.get(def_c_cyan_magenta)
Definition at line 149 of file color.h.
c_cyan_red
#define c_cyan_red all_colors.get(def_c_cyan_red)
Definition at line 74 of file color.h.
c_cyan_white
#define c_cyan_white all_colors.get(def_c_cyan_white)
Definition at line 98 of file color.h.
c_cyan_yellow
#define c_cyan_yellow all_colors.get(def_c_cyan_yellow)
Definition at line 132 of file color.h.
c_dark_gray
#define c_dark_gray all_colors.get(def_c_dark_gray)
Definition at line 18 of file color.h.
c_dark_gray_cyan
#define c_dark_gray_cyan all_colors.get(def_c_dark_gray_cyan)
Definition at line 153 of file color.h.
c_dark_gray_green
#define c_dark_gray_green all_colors.get(def_c_dark_gray_green)
Definition at line 102 of file color.h.
c_dark_gray_magenta
#define c_dark_gray_magenta all_colors.get(def_c_dark_gray_magenta)
Definition at line 136 of file color.h.
c_dark_gray_red
#define c_dark_gray_red all_colors.get(def_c_dark_gray_red)
Definition at line 70 of file color.h.
c_dark_gray_white
#define c_dark_gray_white all_colors.get(def_c_dark_gray_white)
Definition at line 85 of file color.h.
c_dark_gray_yellow
#define c_dark_gray_yellow all_colors.get(def_c_dark_gray_yellow)
Definition at line 119 of file color.h.
c_green
#define c_green all_colors.get(def_c_green)
Definition at line 20 of file color.h.
c_green_cyan
#define c_green_cyan all_colors.get(def_c_green_cyan)
Definition at line 158 of file color.h.
c_green_green
#define c_green_green all_colors.get(def_c_green_green)
Definition at line 107 of file color.h.
c_green_magenta
#define c_green_magenta all_colors.get(def_c_green_magenta)
Definition at line 141 of file color.h.
c_green_red
#define c_green_red all_colors.get(def_c_green_red)
Definition at line 72 of file color.h.
c_green_white
#define c_green_white all_colors.get(def_c_green_white)
Definition at line 90 of file color.h.
c_green_yellow
#define c_green_yellow all_colors.get(def_c_green_yellow)
Definition at line 124 of file color.h.
c_light_blue
#define c_light_blue all_colors.get(def_c_light_blue)
Definition at line 27 of file color.h.
c_light_blue_cyan
#define c_light_blue_cyan all_colors.get(def_c_light_blue_cyan)
Definition at line 163 of file color.h.
c_light_blue_green
#define c_light_blue_green all_colors.get(def_c_light_blue_green)
Definition at line 112 of file color.h.
c_light_blue_magenta
#define c_light_blue_magenta all_colors.get(def_c_light_blue_magenta)
Definition at line 146 of file color.h.
c_light_blue_red
#define c_light_blue_red all_colors.get(def_c_light_blue_red)
Definition at line 79 of file color.h.
c_light_blue_white
#define c_light_blue_white all_colors.get(def_c_light_blue_white)
Definition at line 95 of file color.h.
c_light_blue_yellow
#define c_light_blue_yellow all_colors.get(def_c_light_blue_yellow)
Definition at line 129 of file color.h.
c_light_cyan
#define c_light_cyan all_colors.get(def_c_light_cyan)
Definition at line 28 of file color.h.
c_light_cyan_cyan
#define c_light_cyan_cyan all_colors.get(def_c_light_cyan_cyan)
Definition at line 167 of file color.h.
c_light_cyan_green
#define c_light_cyan_green all_colors.get(def_c_light_cyan_green)
Definition at line 116 of file color.h.
c_light_cyan_magenta
#define c_light_cyan_magenta all_colors.get(def_c_light_cyan_magenta)
Definition at line 150 of file color.h.
c_light_cyan_red
#define c_light_cyan_red all_colors.get(def_c_light_cyan_red)
Definition at line 80 of file color.h.
c_light_cyan_white
#define c_light_cyan_white all_colors.get(def_c_light_cyan_white)
Definition at line 99 of file color.h.
c_light_cyan_yellow
#define c_light_cyan_yellow all_colors.get(def_c_light_cyan_yellow)
Definition at line 133 of file color.h.
c_light_gray
#define c_light_gray all_colors.get(def_c_light_gray)
Definition at line 17 of file color.h.
c_light_gray_cyan
#define c_light_gray_cyan all_colors.get(def_c_light_gray_cyan)
Definition at line 154 of file color.h.
c_light_gray_green
#define c_light_gray_green all_colors.get(def_c_light_gray_green)
Definition at line 103 of file color.h.
c_light_gray_magenta
#define c_light_gray_magenta all_colors.get(def_c_light_gray_magenta)
Definition at line 137 of file color.h.
c_light_gray_red
#define c_light_gray_red all_colors.get(def_c_light_gray_red)
Definition at line 69 of file color.h.
c_light_gray_white
#define c_light_gray_white all_colors.get(def_c_light_gray_white)
Definition at line 86 of file color.h.
c_light_gray_yellow
#define c_light_gray_yellow all_colors.get(def_c_light_gray_yellow)
Definition at line 120 of file color.h.
c_light_green
#define c_light_green all_colors.get(def_c_light_green)
Definition at line 26 of file color.h.
c_light_green_cyan
#define c_light_green_cyan all_colors.get(def_c_light_green_cyan)
Definition at line 159 of file color.h.
c_light_green_green
#define c_light_green_green all_colors.get(def_c_light_green_green)
Definition at line 108 of file color.h.
c_light_green_magenta
#define c_light_green_magenta all_colors.get(def_c_light_green_magenta)
Definition at line 142 of file color.h.
c_light_green_red
#define c_light_green_red all_colors.get(def_c_light_green_red)
Definition at line 78 of file color.h.
c_light_green_white
#define c_light_green_white all_colors.get(def_c_light_green_white)
Definition at line 91 of file color.h.
c_light_green_yellow
#define c_light_green_yellow all_colors.get(def_c_light_green_yellow)
Definition at line 125 of file color.h.
c_light_red
#define c_light_red all_colors.get(def_c_light_red)
Definition at line 25 of file color.h.
c_light_red_cyan
#define c_light_red_cyan all_colors.get(def_c_light_red_cyan)
Definition at line 157 of file color.h.
c_light_red_green
#define c_light_red_green all_colors.get(def_c_light_red_green)
Definition at line 106 of file color.h.
c_light_red_magenta
#define c_light_red_magenta all_colors.get(def_c_light_red_magenta)
Definition at line 140 of file color.h.
c_light_red_red
#define c_light_red_red all_colors.get(def_c_light_red_red)
Definition at line 77 of file color.h.
c_light_red_white
#define c_light_red_white all_colors.get(def_c_light_red_white)
Definition at line 89 of file color.h.
c_light_red_yellow
#define c_light_red_yellow all_colors.get(def_c_light_red_yellow)
Definition at line 123 of file color.h.
c_magenta
#define c_magenta all_colors.get(def_c_magenta)
Definition at line 23 of file color.h.
c_magenta_cyan
#define c_magenta_cyan all_colors.get(def_c_magenta_cyan)
Definition at line 164 of file color.h.
c_magenta_green
#define c_magenta_green all_colors.get(def_c_magenta_green)
Definition at line 113 of file color.h.
c_magenta_magenta
#define c_magenta_magenta all_colors.get(def_c_magenta_magenta)
Definition at line 147 of file color.h.
c_magenta_red
#define c_magenta_red all_colors.get(def_c_magenta_red)
Definition at line 75 of file color.h.
c_magenta_white
#define c_magenta_white all_colors.get(def_c_magenta_white)
Definition at line 96 of file color.h.
c_magenta_yellow
#define c_magenta_yellow all_colors.get(def_c_magenta_yellow)
Definition at line 130 of file color.h.
c_pink
#define c_pink all_colors.get(def_c_pink)
Definition at line 29 of file color.h.
c_pink_cyan
#define c_pink_cyan all_colors.get(def_c_pink_cyan)
Definition at line 165 of file color.h.
c_pink_green
#define c_pink_green all_colors.get(def_c_pink_green)
Definition at line 114 of file color.h.
c_pink_magenta
#define c_pink_magenta all_colors.get(def_c_pink_magenta)
Definition at line 148 of file color.h.
c_pink_red
#define c_pink_red all_colors.get(def_c_pink_red)
Definition at line 81 of file color.h.
c_pink_white
#define c_pink_white all_colors.get(def_c_pink_white)
Definition at line 97 of file color.h.
c_pink_yellow
#define c_pink_yellow all_colors.get(def_c_pink_yellow)
Definition at line 131 of file color.h.
c_red
#define c_red all_colors.get(def_c_red)
Definition at line 19 of file color.h.
c_red_cyan
#define c_red_cyan all_colors.get(def_c_red_cyan)
Definition at line 156 of file color.h.
c_red_green
#define c_red_green all_colors.get(def_c_red_green)
Definition at line 105 of file color.h.
c_red_magenta
#define c_red_magenta all_colors.get(def_c_red_magenta)
Definition at line 139 of file color.h.
c_red_red
#define c_red_red all_colors.get(def_c_red_red)
Definition at line 71 of file color.h.
c_red_white
#define c_red_white all_colors.get(def_c_red_white)
Definition at line 88 of file color.h.
c_red_yellow
#define c_red_yellow all_colors.get(def_c_red_yellow)
Definition at line 122 of file color.h.
c_unset
#define c_unset all_colors.get(def_c_unset)
Definition at line 66 of file color.h.
c_white
#define c_white all_colors.get(def_c_white)
Definition at line 16 of file color.h.
c_white_cyan
#define c_white_cyan all_colors.get(def_c_white_cyan)
Definition at line 155 of file color.h.
c_white_green
#define c_white_green all_colors.get(def_c_white_green)
Definition at line 104 of file color.h.
c_white_magenta
#define c_white_magenta all_colors.get(def_c_white_magenta)
Definition at line 138 of file color.h.
c_white_red
#define c_white_red all_colors.get(def_c_white_red)
Definition at line 68 of file color.h.
c_white_white
#define c_white_white all_colors.get(def_c_white_white)
Definition at line 87 of file color.h.
c_white_yellow
#define c_white_yellow all_colors.get(def_c_white_yellow)
Definition at line 121 of file color.h.
c_yellow
#define c_yellow all_colors.get(def_c_yellow)
Definition at line 30 of file color.h.
c_yellow_cyan
#define c_yellow_cyan all_colors.get(def_c_yellow_cyan)
Definition at line 161 of file color.h.
c_yellow_green
#define c_yellow_green all_colors.get(def_c_yellow_green)
Definition at line 110 of file color.h.
c_yellow_magenta
#define c_yellow_magenta all_colors.get(def_c_yellow_magenta)
Definition at line 144 of file color.h.
c_yellow_red
#define c_yellow_red all_colors.get(def_c_yellow_red)
Definition at line 82 of file color.h.
c_yellow_white
#define c_yellow_white all_colors.get(def_c_yellow_white)
Definition at line 93 of file color.h.
c_yellow_yellow
#define c_yellow_yellow all_colors.get(def_c_yellow_yellow)
Definition at line 127 of file color.h.
CATA_SRC_COLOR_H
#define CATA_SRC_COLOR_H
Definition at line 3 of file color.h.
h_black
#define h_black all_colors.get(def_h_black)
Definition at line 32 of file color.h.
h_blue
#define h_blue all_colors.get(def_h_blue)
Definition at line 38 of file color.h.
h_brown
#define h_brown all_colors.get(def_h_brown)
Definition at line 41 of file color.h.
h_cyan
#define h_cyan all_colors.get(def_h_cyan)
Definition at line 39 of file color.h.
h_dark_gray
#define h_dark_gray all_colors.get(def_h_dark_gray)
Definition at line 35 of file color.h.
h_green
#define h_green all_colors.get(def_h_green)
Definition at line 37 of file color.h.
h_light_blue
#define h_light_blue all_colors.get(def_h_light_blue)
Definition at line 44 of file color.h.
h_light_cyan
#define h_light_cyan all_colors.get(def_h_light_cyan)
Definition at line 45 of file color.h.
h_light_gray
#define h_light_gray all_colors.get(def_h_light_gray)
Definition at line 34 of file color.h.
h_light_green
#define h_light_green all_colors.get(def_h_light_green)
Definition at line 43 of file color.h.
h_light_red
#define h_light_red all_colors.get(def_h_light_red)
Definition at line 42 of file color.h.
h_magenta
#define h_magenta all_colors.get(def_h_magenta)
Definition at line 40 of file color.h.
h_pink
#define h_pink all_colors.get(def_h_pink)
Definition at line 46 of file color.h.
h_red
#define h_red all_colors.get(def_h_red)
Definition at line 36 of file color.h.
h_white
#define h_white all_colors.get(def_h_white)
Definition at line 33 of file color.h.
h_yellow
#define h_yellow all_colors.get(def_h_yellow)
Definition at line 47 of file color.h.
i_black
#define i_black all_colors.get(def_i_black)
Definition at line 49 of file color.h.
i_blue
#define i_blue all_colors.get(def_i_blue)
Definition at line 55 of file color.h.
i_brown
#define i_brown all_colors.get(def_i_brown)
Definition at line 58 of file color.h.
i_cyan
#define i_cyan all_colors.get(def_i_cyan)
Definition at line 56 of file color.h.
i_dark_gray
#define i_dark_gray all_colors.get(def_i_dark_gray)
Definition at line 52 of file color.h.
i_green
#define i_green all_colors.get(def_i_green)
Definition at line 54 of file color.h.
i_light_blue
#define i_light_blue all_colors.get(def_i_light_blue)
Definition at line 61 of file color.h.
i_light_cyan
#define i_light_cyan all_colors.get(def_i_light_cyan)
Definition at line 62 of file color.h.
i_light_gray
#define i_light_gray all_colors.get(def_i_light_gray)
Definition at line 51 of file color.h.
i_light_green
#define i_light_green all_colors.get(def_i_light_green)
Definition at line 60 of file color.h.
i_light_red
#define i_light_red all_colors.get(def_i_light_red)
Definition at line 59 of file color.h.
i_magenta
#define i_magenta all_colors.get(def_i_magenta)
Definition at line 57 of file color.h.
i_pink
#define i_pink all_colors.get(def_i_pink)
Definition at line 63 of file color.h.
i_red
#define i_red all_colors.get(def_i_red)
Definition at line 53 of file color.h.
i_white
#define i_white all_colors.get(def_i_white)
Definition at line 50 of file color.h.
i_yellow
#define i_yellow all_colors.get(def_i_yellow)
Definition at line 64 of file color.h.
Enumeration Type Documentation
color_id
enum color_id
Enumerator
def_c_black
def_c_white
def_c_light_gray
def_c_dark_gray
def_c_red
def_c_green
def_c_blue
def_c_cyan
def_c_magenta
def_c_brown
def_c_light_red
def_c_light_green
def_c_light_blue
def_c_light_cyan
def_c_pink
def_c_yellow
def_h_black
def_h_white
def_h_light_gray
def_h_dark_gray
def_h_red
def_h_green
def_h_blue
def_h_cyan
def_h_magenta
def_h_brown
def_h_light_red
def_h_light_green
def_h_light_blue
def_h_light_cyan
def_h_pink
def_h_yellow
def_i_black
def_i_white
def_i_light_gray
def_i_dark_gray
def_i_red
def_i_green
def_i_blue
def_i_cyan
def_i_magenta
def_i_brown
def_i_light_red
def_i_light_green
def_i_light_blue
def_i_light_cyan
def_i_pink
def_i_yellow
def_c_unset
def_c_black_red
def_c_white_red
def_c_light_gray_red
def_c_dark_gray_red
def_c_red_red
def_c_green_red
def_c_blue_red
def_c_cyan_red
def_c_magenta_red
def_c_brown_red
def_c_light_red_red
def_c_light_green_red
def_c_light_blue_red
def_c_light_cyan_red
def_c_pink_red
def_c_yellow_red
def_c_black_white
def_c_dark_gray_white
def_c_light_gray_white
def_c_white_white
def_c_red_white
def_c_light_red_white
def_c_green_white
def_c_light_green_white
def_c_brown_white
def_c_yellow_white
def_c_blue_white
def_c_light_blue_white
def_c_magenta_white
def_c_pink_white
def_c_cyan_white
def_c_light_cyan_white
def_c_black_green
def_c_dark_gray_green
def_c_light_gray_green
def_c_white_green
def_c_red_green
def_c_light_red_green
def_c_green_green
def_c_light_green_green
def_c_brown_green
def_c_yellow_green
def_c_blue_green
def_c_light_blue_green
def_c_magenta_green
def_c_pink_green
def_c_cyan_green
def_c_light_cyan_green
def_c_black_yellow
def_c_dark_gray_yellow
def_c_light_gray_yellow
def_c_white_yellow
def_c_red_yellow
def_c_light_red_yellow
def_c_green_yellow
def_c_light_green_yellow
def_c_brown_yellow
def_c_yellow_yellow
def_c_blue_yellow
def_c_light_blue_yellow
def_c_magenta_yellow
def_c_pink_yellow
def_c_cyan_yellow
def_c_light_cyan_yellow
def_c_black_magenta
def_c_dark_gray_magenta
def_c_light_gray_magenta
def_c_white_magenta
def_c_red_magenta
def_c_light_red_magenta
def_c_green_magenta
def_c_light_green_magenta
def_c_brown_magenta
def_c_yellow_magenta
def_c_blue_magenta
def_c_light_blue_magenta
def_c_magenta_magenta
def_c_pink_magenta
def_c_cyan_magenta
def_c_light_cyan_magenta
def_c_black_cyan
def_c_dark_gray_cyan
def_c_light_gray_cyan
def_c_white_cyan
def_c_red_cyan
def_c_light_red_cyan
def_c_green_cyan
def_c_light_green_cyan
def_c_brown_cyan
def_c_yellow_cyan
def_c_blue_cyan
def_c_light_blue_cyan
def_c_magenta_cyan
def_c_pink_cyan
def_c_cyan_cyan
def_c_light_cyan_cyan
num_colors
Definition at line 170 of file color.h.
               {
     def_c_black = 0,
     def_c_white,
     def_c_light_gray,
     def_c_dark_gray,
     def_c_red,
     def_c_green,
     def_c_blue,
     def_c_cyan,
     def_c_magenta,
     def_c_brown,
     def_c_light_red,
     def_c_light_green,
     def_c_light_blue,
     def_c_light_cyan,
     def_c_pink,
     def_c_yellow,
     def_h_black,
     def_h_white,
     def_h_light_gray,
     def_h_dark_gray,
     def_h_red,
     def_h_green,
     def_h_blue,
     def_h_cyan,
     def_h_magenta,
     def_h_brown,
     def_h_light_red,
     def_h_light_green,
     def_h_light_blue,
     def_h_light_cyan,
     def_h_pink,
     def_h_yellow,
     def_i_black,
     def_i_white,
     def_i_light_gray,
     def_i_dark_gray,
     def_i_red,
     def_i_green,
     def_i_blue,
     def_i_cyan,
     def_i_magenta,
     def_i_brown,
     def_i_light_red,
     def_i_light_green,
     def_i_light_blue,
     def_i_light_cyan,
     def_i_pink,
     def_i_yellow,
     def_c_unset,
     def_c_black_red,
     def_c_white_red,
     def_c_light_gray_red,
     def_c_dark_gray_red,
     def_c_red_red,
     def_c_green_red,
     def_c_blue_red,
     def_c_cyan_red,
     def_c_magenta_red,
     def_c_brown_red,
     def_c_light_red_red,
     def_c_light_green_red,
     def_c_light_blue_red,
     def_c_light_cyan_red,
     def_c_pink_red,
     def_c_yellow_red,
     def_c_black_white,
     def_c_dark_gray_white,
     def_c_light_gray_white,
     def_c_white_white,
     def_c_red_white,
     def_c_light_red_white,
     def_c_green_white,
     def_c_light_green_white,
     def_c_brown_white,
     def_c_yellow_white,
     def_c_blue_white,
     def_c_light_blue_white,
     def_c_magenta_white,
     def_c_pink_white,
     def_c_cyan_white,
     def_c_light_cyan_white,
     def_c_black_green,
     def_c_dark_gray_green,
     def_c_light_gray_green,
     def_c_white_green,
     def_c_red_green,
     def_c_light_red_green,
     def_c_green_green,
     def_c_light_green_green,
     def_c_brown_green,
     def_c_yellow_green,
     def_c_blue_green,
     def_c_light_blue_green,
     def_c_magenta_green,
     def_c_pink_green,
     def_c_cyan_green,
     def_c_light_cyan_green,
     def_c_black_yellow,
     def_c_dark_gray_yellow,
     def_c_light_gray_yellow,
     def_c_white_yellow,
     def_c_red_yellow,
     def_c_light_red_yellow,
     def_c_green_yellow,
     def_c_light_green_yellow,
     def_c_brown_yellow,
     def_c_yellow_yellow,
     def_c_blue_yellow,
     def_c_light_blue_yellow,
     def_c_magenta_yellow,
     def_c_pink_yellow,
     def_c_cyan_yellow,
     def_c_light_cyan_yellow,
     def_c_black_magenta,
     def_c_dark_gray_magenta,
     def_c_light_gray_magenta,
     def_c_white_magenta,
     def_c_red_magenta,
     def_c_light_red_magenta,
     def_c_green_magenta,
     def_c_light_green_magenta,
     def_c_brown_magenta,
     def_c_yellow_magenta,
     def_c_blue_magenta,
     def_c_light_blue_magenta,
     def_c_magenta_magenta,
     def_c_pink_magenta,
     def_c_cyan_magenta,
     def_c_light_cyan_magenta,
     def_c_black_cyan,
     def_c_dark_gray_cyan,
     def_c_light_gray_cyan,
     def_c_white_cyan,
     def_c_red_cyan,
     def_c_light_red_cyan,
     def_c_green_cyan,
     def_c_light_green_cyan,
     def_c_brown_cyan,
     def_c_yellow_cyan,
     def_c_blue_cyan,
     def_c_light_blue_cyan,
     def_c_magenta_cyan,
     def_c_pink_cyan,
     def_c_cyan_cyan,
     def_c_light_cyan_cyan,
     num_colors
 };
hl_enum
enum hl_enum
Enumerator
HL_BLUE
HL_RED
HL_WHITE
HL_GREEN
HL_YELLOW
HL_MAGENTA
HL_CYAN
NUM_HL
Definition at line 336 of file color.h.
              {
     HL_BLUE = 0,
     HL_RED,
     HL_WHITE,
     HL_GREEN,
     HL_YELLOW,
     HL_MAGENTA,
     HL_CYAN,
     NUM_HL
 };
report_color_error
enum report_color_error strong
Enumerator
no
yes
Definition at line 409 of file color.h.
{
     no, yes
 };
Function Documentation
bgcolor_from_string()
nc_color bgcolor_from_string (const std::string & color)
Given the name of a background color (that is, one of the i_xxxxx colors), returns the nc_color constant that matches.
If no match is found, i_white is returned.
Parameters
color The color to get, as a std::string.
Returns
The nc_color constant that matches the input.
Definition at line 685 of file color.cpp.
 {
     std::string new_color = "i_" + color;
     const std::array<std::pair<std::string, std::string>, 2> pSearch = { {
             { "light_", "lt" }, { "dark_", "dk" }
         }
     };
     for( const auto &i : pSearch ) {
         size_t pos = 0;
         while( ( pos = new_color.find( i.second, pos ) ) != std::string::npos ) {
             new_color.replace( pos, i.second.length(), i.first );
             pos += i.first.length();
             debugmsg( "Deprecated background color suffix was used: (%s) in (%s).  Please update mod that uses that.",
                       i.second, color );
         }
     }
     const nc_color col = all_colors.name_to_color( new_color );
     if( col.to_int() > 0 ) {
         return col;
     }
     return i_white;
 }
References all_colors, color(), debugmsg, i_white, math_opers::pos(), and nc_color::to_int().
Referenced by map_data_common_t::load_symbol().
color_from_string()
nc_color color_from_string (const std::string_view color, const report_color_error color_error)
Given the name of a foreground color, returns the nc_color value that matches.
If no match is found, c_unset is returned. Special cases: {"black" , c_black}, // missing default prefix c_ {"<c|h|i>_black" , h_black}, // has prefix c_ or h_ or i_ {"dark_gray_red" , c_dark_gray_red}, // use dark_ instead of dk as the latter is being deprecated {"light_blue_red" , c_light_blue_red}, // use light_ instead of lt as the latter is being deprecated
Parameters
color The color to get, as a std::string.
Returns
The nc_color constant that matches the input.
Definition at line 629 of file color.cpp.
 {
     if( color.empty() ) {
         return c_unset;
     }
     std::string new_color( color );
     if( new_color.substr( 1, 1 ) != "_" ) { //c_  //i_  //h_
         new_color = "c_" + new_color;
     }
     const std::array<std::pair<std::string, std::string>, 2> pSearch = { {
             { "light_", "lt" }, { "dark_", "dk" }
         }
     };
     for( const auto &i : pSearch ) {
         size_t pos = 0;
         while( ( pos = new_color.find( i.second, pos ) ) != std::string::npos ) {
             new_color.replace( pos, i.second.length(), i.first );
             pos += i.first.length();
             if( color_error == report_color_error::yes ) {
                 debugmsg( "Deprecated foreground color suffix was used: (%s) in (%s).  Please update mod that uses that.",
                           i.second, color );
             }
         }
     }
     const nc_color col = all_colors.name_to_color( new_color, color_error );
     if( col.to_int() > 0 ) {
         return col;
     }
     return c_unset;
 }
References all_colors, c_unset, color(), debugmsg, math_opers::pos(), nc_color::to_int(), and yes.
Referenced by assign(), get_color_from_tag(), itype_variant_data::load(), widget_clause::load(), bodygraph::load(), field_type::load(), map_extra::load(), damage_type::load(), explosion_iuse::load(), Item_factory::load_basic_info(), and map_data_common_t::load_symbol().
colorize() [1/2]
std::string colorize (const std::string & text, const nc_color & color)
Definition at line 742 of file color.cpp.
 {
     const std::string tag = get_tag_from_color( color );
     size_t strpos = text.find( '\n' );
     if( strpos == std::string::npos ) {
         return tag + text + "</color>";
     }
     size_t prevpos = 0;
     std::string ret;
     while( ( strpos = text.find( '\n', prevpos ) ) != std::string::npos ) {
         ret += tag + text.substr( prevpos, strpos - prevpos ) + "</color>\n";
         prevpos = strpos + 1;
     }
     ret += tag + text.substr( prevpos, text.size() - prevpos ) + "</color>";
     return ret;
 }
References color(), get_tag_from_color(), and cata::hash64_detail::ret.
Referenced by trade_ui::_draw_header(), achievement_attained(), computer_session::action_list_mutations(), Character::activate_bionic(), add_electronic_toggle(), item::armor_info(), assemble_hobby_details(), assemble_profession_details(), assemble_scenario_details(), assemble_skill_details(), assemble_stat_details(), iexamine::autodoc(), iuse::blood_draw(), blood_magic(), Character::body_window(), vehicle::build_electronics_menu(), butcher_submenu(), veh_interact::calc_lift_requirements(), veh_interact::calc_overview(), veh_interact::can_remove_part(), anonymous_namespace{item_tname.cpp}::category(), debug_menu::character_edit_needs_menu(), game::check_safe_mode_allowed(), choose_crafter(), color_number(), widget::color_text_function_string(), widget::color_value_string(), colorize(), display::colorized_bodygraph_text(), display::colorized_compass_legend_text(), spell::colorized_fail_percent(), colorized_feature_description_at(), colorized_field_description_at(), colorized_item_name(), display::colorized_overmap_text(), colorized_ter_name_flags_at(), colorized_trap_name_at(), coloured_stat_display(), construction_menu(), anonymous_namespace{item_tname.cpp}::contents(), item::contents_info(), item_pocket::contents_info(), overmap_ui::create_note(), Character::crush_frozen_liquid(), item::degradation_symbol(), item_location::impl::item_on_vehicle::describe(), Character::disassemble(), Character::disp_info(), faction_manager::display(), item::display_name(), display_stat(), main_menu::display_sub_menu(), veh_interact::do_repair(), inventory_column::draw(), dialogue_window::draw(), draw_bionics_titlebar(), bodygraph_display::draw_borders(), keybindings_ui::draw_controls(), target_ui::draw_controls_list(), prof_window::draw_details(), draw_effects_summary(), draw_filter_and_sorting_indicators(), bodygraph_display::draw_graph(), prof_window::draw_header(), draw_health_summary(), overmap_ui::draw_notes(), bodygraph_display::draw_partlist(), draw_proficiencies_info(), draw_spellbook_info(), draw_stats_summary(), draw_traits_info(), game_menus::inv::ebooksave(), effects_description_for_creature(), spell::energy_cost_string(), spell::energy_cur_string(), enumerate_objects_around_point(), Character::extended_description(), monster::extended_description(), mtype::faction_display(), format_item_info(), format_requirements(), formatted_hotkey(), get_achievements_text(), basecamp::get_available_missions_by_dir(), get_bodygraph_lines(), get_compass_for_direction(), get_consume_needs_hint(), overmapbuffer::get_description_at(), get_encumbrance_description(), talk_data::get_entry(), requirement_data::get_folded_components_list(), requirement_data::get_folded_list(), requirement_data::get_folded_tools_list(), inventory_selector::get_holster_stat(), mod_ui::get_information(), kill_tracker::get_kills_text(), help::get_note_colors(), get_opt_slider(), get_score_text(), construction::get_time_string(), inventory_selector::get_volume_stat(), inventory_selector::get_weight_and_length_stat(), Character::gunmod_add(), display::health_string(), hilite_string(), main_menu::init_strings(), item_save_monsters(), ma_style_callback::key(), keybindings_ui::keybindings_ui(), diary::kill_changes(), list_items_filter_history_help(), list_nested(), iuse::marloss_seed(), Character::mend_item(), widget::number_cond(), target_ui::panel_cursor_info(), target_ui::panel_gun_info(), target_ui::panel_spell_info(), photo_def_for_camera_point(), character_martial_arts::pick_style(), pickup_selector::pickup_selector(), overmap_ui::place_ter_or_special(), outfit::prepare_bodymap_info(), bodygraph_display::prepare_infotext(), selection_line::print(), computer_session::print_error(), computer_session::print_gibberish_line(), monster::print_info(), multiline_list::print_line(), main_menu::print_menu_items(), vehicle::print_vparts_descs(), iexamine::quern_examine(), recipe_info(), pocket_favorite_callback::refresh(), zone_data::refresh_display(), repair_inventory_preset::repair_inventory_preset(), replace_keybind_tag(), recipe::required_proficiencies_string(), satiety_bar(), overmap_ui::search(), iuse::seed(), calendar_ui::select_time_point(), set_skills(), set_traits(), shortcut_text(), auto_notes::auto_note_manager_gui::show(), show_mutations_titlebar(), worldfactory::show_worldgen_basic(), iexamine::smoker_options(), outfit::sort_armor(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), display::sundial_text_color(), widget::sym_cond(), widget::sym_text_cond(), texitify_bandage_power(), texitify_base_healing_power(), texitify_healing_power(), widget::text_cond(), text_for_requirement(), zone_data::toggle_display(), inventory_multiselector::toggle_entries(), Character::toolmod_add(), avatar::total_daily_calories_string(), diary::trait_changes(), achievement_tracker::ui_text(), achievement::time_bound::ui_text(), achievement_state::ui_text(), achievements_tracker::ui_text_for(), veh_interact::update_part_requirements(), sew_advanced_actor::use(), query_popup::wait_text(), iuse::wash_items(), anonymous_namespace{item_tname.cpp}::wbl_mark(), Character::weapname_ammo(), display::weight_string(), Character::will_eat(), and debug_menu::wisheffect().
colorize() [2/2]
std::string colorize (const translation & text, const nc_color & color)
Definition at line 760 of file color.cpp.
 {
     return colorize( text.translated(), color );
 }
References color(), colorize(), and translation::translated().
cyan_background()
nc_color cyan_background (const nc_color & c)
Definition at line 582 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_CYAN );
     return static_cast<int>( color ) > 0 ? color : c_black_cyan;
 }
References all_colors, c, c_black_cyan, color(), and HL_CYAN.
Referenced by map::draw_from_above(), editmap::draw_main_ui_overlay(), editmap_hilight::setup(), and Character::symbol_color().
get_all_colors()
color_manager& get_all_colors ()
Definition at line 43 of file color.cpp.
 {
     static color_manager single_instance;
     return single_instance;
 }
Referenced by colorize_symbols(), Messages::dialog::filter_help_text(), auto_notes::custom_symbol::get_color_string(), overmap_ui::get_scent_glyph(), widget::load(), liquid_handler::perform_liquid_transfer(), replace_colors(), auto_notes::custom_symbol::set_color(), and auto_notes::auto_note_manager_gui::show().
get_color_from_tag()
color_tag_parse_result get_color_from_tag (std::string_view s, report_color_error color_error = report_color_error::yes)
Definition at line 712 of file color.cpp.
 {
     if( s.empty() || s[0] != '<' ) {
         return { color_tag_parse_result::non_color_tag, {} };
     }
     if( s.substr( 0, 8 ) == "</color>" ) {
         return { color_tag_parse_result::close_color_tag, {} };
     }
     if( s.substr( 0, 7 ) != "<color_" ) {
         return { color_tag_parse_result::non_color_tag, {} };
     }
     size_t tag_close = s.find( '>' );
     if( tag_close == std::string::npos ) {
         return { color_tag_parse_result::non_color_tag, {} };
     }
     std::string_view color_name = s.substr( 7, tag_close - 7 );
     const nc_color color = color_from_string( color_name, color_error );
     if( color != c_unset ) {
         return { color_tag_parse_result::open_color_tag, color };
     } else {
         return { color_tag_parse_result::non_color_tag, color };
     }
 }
References c_unset, color_tag_parse_result::close_color_tag, color(), color_from_string(), color_tag_parse_result::non_color_tag, and color_tag_parse_result::open_color_tag.
Referenced by hilite_string(), display::morale_emotion(), and update_color_stack().
get_note_color()
nc_color get_note_color (std::string_view note_id)
Definition at line 776 of file color.cpp.
 {
     // TODO in C++20 we can pass a string_view in directly rather than
     // constructing a string to use as the find argument
     const auto candidate_color = color_by_string_map.find( std::string( note_id ) );
     if( candidate_color != std::end( color_by_string_map ) ) {
         return candidate_color->second.color;
     }
     // The default note color.
     return c_yellow;
 }
References c_yellow, color_by_string_map, and keycode::end.
Referenced by overmap_ui::get_note_display_info().
get_note_color_names()
const std::unordered_map<std::string, note_color>& get_note_color_names ()
Definition at line 788 of file color.cpp.
 {
     return color_by_string_map;
 }
References color_by_string_map.
Referenced by overmap_ui::create_note(), help::get_note_colors(), and auto_notes::auto_note_manager_gui::show().
get_note_string_from_color()
std::string get_note_string_from_color (const nc_color & color)
Definition at line 765 of file color.cpp.
 {
     for( const std::pair<const std::string, note_color> &i : color_by_string_map ) {
         if( i.second.color == color ) {
             return i.first;
         }
     }
     // The default note string.
     return "Y";
 }
References color(), and color_by_string_map.
Referenced by overmap::add_extra_note().
get_tag_from_color()
std::string get_tag_from_color (const nc_color & color)
Definition at line 737 of file color.cpp.
 {
     return "<color_" + string_from_color( color ) + ">";
 }
References color(), and string_from_color().
Referenced by colorize(), requirement_data::get_folded_list(), hilite_string(), and monster::print_info().
green_background()
nc_color green_background (const nc_color & c)
Definition at line 564 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_GREEN );
     return static_cast<int>( color ) > 0 ? color : c_black_green;
 }
References all_colors, c, c_black_green, color(), and HL_GREEN.
Referenced by editmap::draw_main_ui_overlay(), editmap_hilight::setup(), and Character::symbol_color().
hilite()
nc_color hilite (const nc_color & c)
Definition at line 546 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_BLUE );
     return static_cast<int>( color ) > 0 ? color : h_white;
 }
References all_colors, c, color(), h_white, and HL_BLUE.
Referenced by debug_menu::change_spells(), monster::color_with_effects(), display::colorized_overmap_text(), construction_color(), faction_manager::display(), veh_interact::display_list(), veh_interact::display_overview(), main_menu::display_sub_menu(), veh_interact::display_veh(), draw_bionics_tab(), lightson_game::draw_level(), map::draw_maptile(), help::draw_menu(), bodygraph_display::draw_partlist(), draw_proficiencies_tab(), prof_window::draw_profs(), draw_speed_tab(), draw_traits_tab(), requirement_data::get_folded_components_list(), requirement_data::get_folded_list(), hilite_string(), basecamp::job_assignment_ui(), game::list_items(), game::list_monsters(), mvwputch_hi(), worldfactory::pick_world(), advanced_inventory::print_items(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), main_menu::print_menu_items(), vehicle::print_part_list(), smart_controller_ui::refresh(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), lightson_game::start_game(), minesweeper_game::start_game(), sokoban_game::start_game(), display::sundial_text_color(), Character::symbol_color(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), and basecamp::worker_assignment_ui().
hilite_string()
std::string hilite_string (const std::string & text)
Definition at line 588 of file color.cpp.
 {
     std::string highlighted = text;
     size_t pos = 0;
     size_t tag_length = 0;
     int color_tag_count = 0;
     while( ( pos = highlighted.find( "<color_", pos ) ) != std::string::npos ) {
         tag_length = highlighted.find( '>', pos ) - pos + 1;
         if( tag_length <= 0 ) {
             debugmsg( "Tag length calculated incorrectly.  Unable to highlight text %s", text );
             return text;
         }
         std::string tag = highlighted.substr( pos, tag_length );
         color_tag_parse_result old_color = get_color_from_tag( tag );
         if( old_color.type != color_tag_parse_result::open_color_tag ) {
             debugmsg( "Unable to highlight text %s, parsing color tag %s failed", text, tag );
             return text;
         }
         nc_color new_color = hilite( old_color.color );
         std::string new_tag = get_tag_from_color( new_color );
         highlighted.replace( pos, tag_length, new_tag );
         pos += new_tag.length();
         ++color_tag_count;
     }
     if( color_tag_count < 1 ) {
         highlighted = colorize( highlighted, h_white );
     }
     return highlighted;
 }
References color_tag_parse_result::color, colorize(), debugmsg, get_color_from_tag(), get_tag_from_color(), h_white, hilite(), color_tag_parse_result::open_color_tag, math_opers::pos(), and color_tag_parse_result::type.
Referenced by inventory_column::draw(), and multiline_list::print_line().
init_colors()
void init_colors ()
Definition at line 421 of file color.cpp.
 {
     using namespace catacurses; // to get the base_color enumeration
     init_pair( 1, white,      black );
     init_pair( 2, red,        black );
     init_pair( 3, green,      black );
     init_pair( 4, blue,       black );
     init_pair( 5, cyan,       black );
     init_pair( 6, magenta,    black );
     init_pair( 7, yellow,     black );
     // Inverted Colors
     init_pair( 8, black,      white );
     init_pair( 9, black,      red );
     init_pair( 10, black,      green );
     init_pair( 11, black,      blue );
     init_pair( 12, black,      cyan );
     init_pair( 13, black,      magenta );
     init_pair( 14, black,      yellow );
     // Highlighted - blue background
     init_pair( 15, white,      blue );
     init_pair( 16, red,        blue );
     init_pair( 17, green,      blue );
     init_pair( 18, blue,       blue );
     init_pair( 19, cyan,       blue );
     init_pair( 20, black,      blue );
     init_pair( 21, magenta,    blue );
     init_pair( 22, yellow,     blue );
     // Red background - for monsters on fire
     init_pair( 23, white,      red );
     init_pair( 24, red,        red );
     init_pair( 25, green,      red );
     init_pair( 26, blue,       red );
     init_pair( 27, cyan,       red );
     init_pair( 28, magenta,    red );
     init_pair( 29, yellow,     red );
     init_pair( 30, black,      black );
     init_pair( 31, white,      black );
     init_pair( 32, black,      white );
     init_pair( 33, white,      white );
     init_pair( 34, red,        white );
     init_pair( 35, green,      white );
     init_pair( 36, yellow,     white );
     init_pair( 37, blue,       white );
     init_pair( 38, magenta,    white );
     init_pair( 39, cyan,       white );
     init_pair( 40, black,      green );
     init_pair( 41, white,      green );
     init_pair( 42, red,        green );
     init_pair( 43, green,      green );
     init_pair( 44, yellow,     green );
     init_pair( 45, blue,       green );
     init_pair( 46, magenta,    green );
     init_pair( 47, cyan,       green );
     init_pair( 48, black,      yellow );
     init_pair( 49, white,      yellow );
     init_pair( 50, red,        yellow );
     init_pair( 51, green,      yellow );
     init_pair( 52, yellow,     yellow );
     init_pair( 53, blue,       yellow );
     init_pair( 54, magenta,    yellow );
     init_pair( 55, cyan,       yellow );
     init_pair( 56, black,      magenta );
     init_pair( 57, white,      magenta );
     init_pair( 58, red,        magenta );
     init_pair( 59, green,      magenta );
     init_pair( 60, yellow,     magenta );
     init_pair( 61, blue,       magenta );
     init_pair( 62, magenta,    magenta );
     init_pair( 63, cyan,       magenta );
     init_pair( 64, black,      cyan );
     init_pair( 65, white,      cyan );
     init_pair( 66, red,        cyan );
     init_pair( 67, green,      cyan );
     init_pair( 68, yellow,     cyan );
     init_pair( 69, blue,       cyan );
     init_pair( 70, magenta,    cyan );
     init_pair( 71, cyan,       cyan );
     init_pair( 72, dark_gray,  black );
     init_pair( 73, dark_gray,  red );
     init_pair( 74, dark_gray,  green );
     init_pair( 75, dark_gray,  blue );
     init_pair( 76, dark_gray,  cyan );
     init_pair( 77, dark_gray,  magenta );
     init_pair( 78, dark_gray,  yellow );
     init_pair( 79, dark_gray,  white );
     init_pair( 80, black,      dark_gray );
     init_pair( 81, red,        dark_gray );
     init_pair( 82, green,      dark_gray );
     init_pair( 83, blue,       dark_gray );
     init_pair( 84, cyan,       dark_gray );
     init_pair( 85, magenta,    dark_gray );
     init_pair( 86, yellow,     dark_gray );
     init_pair( 87, white,      dark_gray );
     all_colors.load_default();
     all_colors.load_custom( {} );
     // The short color codes (e.g. "br") are intentionally untranslatable.
     color_by_string_map = {
         {"br", {c_brown, to_translation( "brown" )}}, {"lg", {c_light_gray, to_translation( "light gray" )}},
         {"dg", {c_dark_gray, to_translation( "dark gray" )}}, {"r", {c_light_red, to_translation( "light red" )}},
         {"R", {c_red, to_translation( "red" )}}, {"g", {c_light_green, to_translation( "light green" )}},
         {"G", {c_green, to_translation( "green" )}}, {"b", {c_light_blue, to_translation( "light blue" )}},
         {"B", {c_blue, to_translation( "blue" )}}, {"W", {c_white, to_translation( "white" )}},
         {"C", {c_cyan, to_translation( "cyan" )}}, {"c", {c_light_cyan, to_translation( "light cyan" )}},
         {"P", {c_pink, to_translation( "pink" )}}, {"m", {c_magenta, to_translation( "magenta" )}}
     };
 }
References all_colors, catacurses::black, catacurses::blue, c_blue, c_brown, c_cyan, c_dark_gray, c_green, c_light_blue, c_light_cyan, c_light_gray, c_light_green, c_light_red, c_magenta, c_pink, c_red, c_white, color_by_string_map, catacurses::cyan, catacurses::dark_gray, catacurses::green, catacurses::init_pair(), catacurses::magenta, catacurses::red, to_translation(), catacurses::white, and catacurses::yellow.
Referenced by catacurses::init_interface(), and main().
invert_color()
nc_color invert_color (const nc_color & c)
Definition at line 540 of file color.cpp.
 {
     const nc_color color = all_colors.get_invert( c );
     return static_cast<int>( color ) > 0 ? color : c_pink;
 }
References all_colors, c, c_pink, and color().
Referenced by monster::color_with_effects(), map::draw_from_above(), map::draw_maptile(), advanced_inventory::draw_minimap(), anonymous_namespace{animation.cpp}::draw_zones_curses(), vehicle::get_display_of_tile(), and mvwputch_inv().
magenta_background()
nc_color magenta_background (const nc_color & c)
Definition at line 576 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_MAGENTA );
     return static_cast<int>( color ) > 0 ? color : c_black_magenta;
 }
References all_colors, c, c_black_magenta, color(), and HL_MAGENTA.
Referenced by advanced_inventory::print_items(), and editmap_hilight::setup().
red_background()
nc_color red_background (const nc_color & c)
Definition at line 552 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_RED );
     return static_cast<int>( color ) > 0 ? color : c_white_red;
 }
References all_colors, c, c_white_red, color(), and HL_RED.
Referenced by monster::color_with_effects(), veh_interact::display_veh(), overmap_ui::draw_ascii(), anonymous_namespace{animation.cpp}::draw_hit_mon_curses(), anonymous_namespace{animation.cpp}::draw_hit_player_curses(), sokoban_game::draw_level(), map::draw_maptile(), game::draw_minimap(), overmap_ui::draw_overmap_chunk(), display::overmap_tile_symbol_color(), editmap_hilight::setup(), Character::symbol_color(), auto_pickup::rule::test_pattern(), and safemode::test_pattern().
string_from_color()
std::string string_from_color (const nc_color & color)
The reverse of color_from_string.
Definition at line 667 of file color.cpp.
 {
     std::string sColor = all_colors.get_name( color );
     if( sColor != "c_unset" ) {
         return sColor;
     }
     return "c_white";
 }
References all_colors, and color().
Referenced by vpart_info::format_description(), get_tag_from_color(), and overmap_ui::place_ter_or_special().
white_background()
nc_color white_background (const nc_color & c)
Definition at line 558 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_WHITE );
     return static_cast<int>( color ) > 0 ? color : c_black_white;
 }
References all_colors, c, c_black_white, color(), and HL_WHITE.
Referenced by Character::symbol_color().
yellow_background()
nc_color yellow_background (const nc_color & c)
Definition at line 570 of file color.cpp.
 {
     const nc_color color = all_colors.get_highlight( c, HL_YELLOW );
     return static_cast<int>( color ) > 0 ? color : c_black_yellow;
 }
References all_colors, c, c_black_yellow, color(), and HL_YELLOW.
Referenced by anonymous_namespace{animation.cpp}::draw_hit_player_curses(), requirement_data::get_folded_list(), and editmap_hilight::setup().